SDRAngel: SWGSDRangel::SWGPerseusReport Class Reference
SWGSDRangel::SWGPerseusReport Class Reference
#include <SWGPerseusReport.h>
Public Member Functions
SWGPerseusReport ()
SWGPerseusReport (QString *json)
virtual ~SWGPerseusReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGPerseusReport * fromJson (QString &jsonString) override
QList< SWGSampleRate * > * getSampleRates ()
void setSampleRates (QList< SWGSampleRate *> *sample_rates)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QList< SWGSampleRate * > * sample_rates
bool m_sample_rates_isSet
Detailed Description
Definition at line 33 of file SWGPerseusReport.h.
Constructor & Destructor Documentation
SWGPerseusReport() [1/2]
SWGSDRangel::SWGPerseusReport::SWGPerseusReport ()
Definition at line 30 of file SWGPerseusReport.cpp.
References m_sample_rates_isSet, and sample_rates.
{
     sample_rates = nullptr;
     m_sample_rates_isSet = false;
 }
SWGPerseusReport() [2/2]
SWGSDRangel::SWGPerseusReport::SWGPerseusReport (QString * json)
Definition at line 25 of file SWGPerseusReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGPerseusReport()
SWGSDRangel::SWGPerseusReport::~SWGPerseusReport () virtual
Definition at line 35 of file SWGPerseusReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGPerseusReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 72 of file SWGPerseusReport.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGPerseusReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 83 of file SWGPerseusReport.cpp.
References sample_rates, and SWGSDRangel::toJsonArray().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(sample_rates->size() > 0){
         toJsonArray((QList<void*>*)sample_rates, obj, "sampleRates", "SWGSampleRate");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGPerseusReport::cleanup ()
Definition at line 46 of file SWGPerseusReport.cpp.
References sample_rates.
Referenced by ~SWGPerseusReport().
{
     if(sample_rates != nullptr) {
         auto arr = sample_rates;
         for(auto o: *arr) {
             delete o;
         }
         delete sample_rates;
     }
 }
fromJson()
SWGPerseusReport * SWGSDRangel::SWGPerseusReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 57 of file SWGPerseusReport.cpp.
References fromJsonObject().
Referenced by SWGPerseusReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGPerseusReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 66 of file SWGPerseusReport.cpp.
References sample_rates, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&sample_rates, pJson["sampleRates"], "QList", "SWGSampleRate");
 }
getSampleRates()
QList< SWGSampleRate * > * SWGSDRangel::SWGPerseusReport::getSampleRates ()
Definition at line 93 of file SWGPerseusReport.cpp.
References sample_rates.
Referenced by PerseusInput::webapiFormatDeviceReport().
{
     return sample_rates;
 }
init()
void SWGSDRangel::SWGPerseusReport::init ()
Definition at line 40 of file SWGPerseusReport.cpp.
References m_sample_rates_isSet, and sample_rates.
Referenced by SWGPerseusReport(), and PerseusInput::webapiReportGet().
{
     sample_rates = new QList<SWGSampleRate*>();
     m_sample_rates_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGPerseusReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 104 of file SWGPerseusReport.cpp.
References sample_rates.
Referenced by SWGSDRangel::SWGDeviceReport::asJsonObject(), and SWGSDRangel::SWGDeviceReport::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(sample_rates->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setSampleRates()
void SWGSDRangel::SWGPerseusReport::setSampleRates (QList< SWGSampleRate *> * sample_rates)
Definition at line 97 of file SWGPerseusReport.cpp.
References m_sample_rates_isSet, and sample_rates.
Referenced by PerseusInput::webapiFormatDeviceReport().
{
     this->sample_rates = sample_rates;
     this->m_sample_rates_isSet = true;
 }
Member Data Documentation
m_sample_rates_isSet
bool SWGSDRangel::SWGPerseusReport::m_sample_rates_isSet private
Definition at line 54 of file SWGPerseusReport.h.
Referenced by init(), setSampleRates(), and SWGPerseusReport().
sample_rates
QList<SWGSampleRate*>* SWGSDRangel::SWGPerseusReport::sample_rates private
Definition at line 53 of file SWGPerseusReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSampleRates(), init(), isSet(), setSampleRates(), and SWGPerseusReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGPerseusReport.h
swagger/sdrangel/code/qt5/client/SWGPerseusReport.cpp