SDRAngel: RTPSink Class Reference
RTPSink Class Reference
#include <rtpsink.h>
Public Types
enum PayloadType {
PayloadL16Mono, PayloadL16Stereo, PayloadL8, PayloadPCMA8,
PayloadPCMU8, PayloadG722, PayloadOpus
}
Public Member Functions
RTPSink (QUdpSocket *udpSocket, int sampleRate, bool stereo)
~RTPSink ()
bool isValid () const
void setPayloadInformation (PayloadType payloadType, int sampleRate)
void setDestination (const QString &address, uint16_t port)
void deleteDestination (const QString &address, uint16_t port)
void addDestination (const QString &address, uint16_t port)
void write (const uint8_t *sampleByte)
void write (const uint8_t *sampleByteL, const uint8_t *sampleByteR)
void write (const uint8_t *sampleByte, int nbSamples)
Static Protected Member Functions
static void writeNetBuf (uint8_t *dest, const uint8_t *src, unsigned int elemLen, unsigned int bytesLen, bool endianReverse)
static unsigned int elemLength (PayloadType payloadType)
Protected Attributes
bool m_valid
PayloadType m_payloadType
int m_sampleRate
int m_sampleBytes
int m_packetSamples
int m_bufferSize
int m_sampleBufferIndex
uint8_t * m_byteBuffer
QHostAddress m_destip
uint16_t m_destport
qrtplib::RTPSession m_rtpSession
qrtplib::RTPSessionParams m_rtpSessionParams
qrtplib::RTPUDPTransmissionParams m_rtpTransmissionParams
qrtplib::RTPUDPTransmitter m_rtpTransmitter
bool m_endianReverse
QMutex m_mutex
Detailed Description
Definition at line 39 of file rtpsink.h.
Member Enumeration Documentation
PayloadType
enum RTPSink::PayloadType
Enumerator
PayloadL16Mono
PayloadL16Stereo
PayloadL8
PayloadPCMA8
PayloadPCMU8
PayloadG722
PayloadOpus
Definition at line 42 of file rtpsink.h.
     {
         PayloadL16Mono,
         PayloadL16Stereo,
         PayloadL8,
         PayloadPCMA8,
         PayloadPCMU8,
         PayloadG722,
         PayloadOpus
     } PayloadType;
Constructor & Destructor Documentation
RTPSink()
RTPSink::RTPSink (QUdpSocket * udpSocket, int sampleRate, bool stereo)
Definition at line 23 of file rtpsink.cpp.
References qrtplib::RTPSession::Create(), qrtplib::RTPUDPTransmitter::Create(), qrtplib::RTPSessionParams::GetMaximumPacketSize(), qrtplib::RTPUDPTransmitter::Init(), m_endianReverse, m_payloadType, m_rtpSession, m_rtpSessionParams, m_rtpTransmissionParams, m_rtpTransmitter, m_sampleRate, m_valid, qrtplib::RTPGetErrorString(), qrtplib::RTPSessionParams::SetOwnTimestampUnit(), setPayloadInformation(), qrtplib::RTPUDPTransmissionParams::SetRTCPMultiplexing(), and qrtplib::RTPUDPTransmissionParams::SetUseExistingSockets().
                                                                    :
     m_payloadType(stereo ? RTPSink::PayloadL16Stereo : RTPSink::PayloadL16Mono),
     m_sampleRate(sampleRate),
     m_sampleBytes(0),
     m_packetSamples(0),
     m_bufferSize(0),
     m_sampleBufferIndex(0),
     m_byteBuffer(0),
     m_destport(9998),
     m_mutex(QMutex::Recursive)
 {
     m_rtpSessionParams.SetOwnTimestampUnit(1.0 / (double) m_sampleRate);
     m_rtpTransmissionParams.SetRTCPMultiplexing(true); // do not allocate another socket for RTCP
     m_rtpTransmissionParams.SetUseExistingSockets(udpSocket, udpSocket);
     int status = m_rtpTransmitter.Init();
     if (status < 0) {
         qCritical("RTPSink::RTPSink: cannot initialize transmitter: %s", qrtplib::RTPGetErrorString(status).c_str());
         m_valid = false;
     } else {
         qDebug("RTPSink::RTPSink: initialized transmitter: %s", qrtplib::RTPGetErrorString(status).c_str());
     }
     m_rtpTransmitter.Create(m_rtpSessionParams.GetMaximumPacketSize(), &m_rtpTransmissionParams);
     qDebug("RTPSink::RTPSink: created transmitter: %s", qrtplib::RTPGetErrorString(status).c_str());
     status = m_rtpSession.Create(m_rtpSessionParams, &m_rtpTransmitter);
     if (status < 0) {
         qCritical("RTPSink::RTPSink: cannot create session: %s", qrtplib::RTPGetErrorString(status).c_str());
         m_valid = false;
     } else {
         qDebug("RTPSink::RTPSink: created session: %s", qrtplib::RTPGetErrorString(status).c_str());
     }
     setPayloadInformation(m_payloadType, m_sampleRate);
     m_valid = true;
     uint32_t endianTest32 = 1;
     uint8_t *ptr = (uint8_t*) &endianTest32;
     m_endianReverse = (*ptr == 1);
 }
~RTPSink()
RTPSink::~RTPSink ()
Definition at line 65 of file rtpsink.cpp.
References qrtplib::RTPSession::BYEDestroy(), m_byteBuffer, and m_rtpSession.
 {
     qrtplib::RTPTime delay = qrtplib::RTPTime(10.0);
     m_rtpSession.BYEDestroy(delay, "Time's up", 9);
     if (m_byteBuffer) {
         delete[] m_byteBuffer;
     }
 }
Member Function Documentation
addDestination()
void RTPSink::addDestination (const QString & address, uint16_t port)
Definition at line 205 of file rtpsink.cpp.
References qrtplib::RTPSession::AddDestination(), m_rtpSession, and qrtplib::RTPGetErrorString().
Referenced by AudioNetSink::addDestination(), and isValid().
 {
     QHostAddress destip(address);
     int status = m_rtpSession.AddDestination(qrtplib::RTPAddress(destip, port));
     if (status < 0) {
         qCritical("RTPSink::addDestination: cannot add destination address: %s", qrtplib::RTPGetErrorString(status).c_str());
     } else {
         qDebug("RTPSink::addDestination: destination address set to %s:%d: %s",
                 address.toStdString().c_str(),
                 port,
                 qrtplib::RTPGetErrorString(status).c_str());
     }
 }
deleteDestination()
void RTPSink::deleteDestination (const QString & address, uint16_t port)
Definition at line 194 of file rtpsink.cpp.
References qrtplib::RTPSession::DeleteDestination(), m_rtpSession, and qrtplib::RTPGetErrorString().
Referenced by AudioNetSink::deleteDestination(), and isValid().
 {
     QHostAddress destip(address);
     int status =  m_rtpSession.DeleteDestination(qrtplib::RTPAddress(destip, port));
     if (status < 0) {
         qCritical("RTPSink::deleteDestination: cannot delete destination address: %s", qrtplib::RTPGetErrorString(status).c_str());
     }
 }
elemLength()
unsigned int RTPSink::elemLength (PayloadType payloadType) static protected
Definition at line 334 of file rtpsink.cpp.
References PayloadG722, PayloadL16Mono, PayloadL16Stereo, PayloadL8, PayloadOpus, PayloadPCMA8, and PayloadPCMU8.
Referenced by isValid(), and write().
 {
     switch (payloadType)
     {
     case PayloadPCMA8:
     case PayloadPCMU8:
     case PayloadG722:
     case PayloadOpus:
     case PayloadL8:
         return sizeof(int8_t);
         break;
     case PayloadL16Stereo:
     case PayloadL16Mono:
     default:
         return sizeof(int16_t);
         break;
     }
 }
isValid()
bool RTPSink::isValid () const inline
Definition at line 56 of file rtpsink.h.
References addDestination(), deleteDestination(), elemLength(), m_valid, setDestination(), setPayloadInformation(), write(), and writeNetBuf().
Referenced by AudioNetSink::isRTPCapable().
 { return m_valid; }
setDestination()
void RTPSink::setDestination (const QString & address, uint16_t port)
Definition at line 180 of file rtpsink.cpp.
References qrtplib::RTPSession::AddDestination(), qrtplib::RTPSession::ClearDestinations(), qrtplib::RTPSession::DeleteDestination(), m_destip, m_destport, m_rtpSession, and qrtplib::RTPGetErrorString().
Referenced by isValid(), and AudioNetSink::setDestination().
 {
     m_rtpSession.ClearDestinations();
     m_rtpSession.DeleteDestination(qrtplib::RTPAddress(m_destip, m_destport));
     m_destip.setAddress(address);
     m_destport = port;
     int status = m_rtpSession.AddDestination(qrtplib::RTPAddress(m_destip, m_destport));
     if (status < 0) {
         qCritical("RTPSink::setDestination: cannot set destination address: %s", qrtplib::RTPGetErrorString(status).c_str());
     }
 }
setPayloadInformation()
void RTPSink::setPayloadInformation (PayloadType payloadType, int sampleRate)
Definition at line 75 of file rtpsink.cpp.
References m_bufferSize, m_byteBuffer, m_mutex, m_packetSamples, m_payloadType, m_rtpSession, m_sampleBufferIndex, m_sampleBytes, m_sampleRate, PayloadG722, PayloadL16Mono, PayloadL16Stereo, PayloadL8, PayloadOpus, PayloadPCMA8, PayloadPCMU8, RTP_MINPACKETSIZE, qrtplib::RTPGetErrorString(), qrtplib::RTPSession::SetDefaultMark(), qrtplib::RTPSession::SetDefaultPayloadType(), qrtplib::RTPSession::SetDefaultTimestampIncrement(), qrtplib::RTPSession::SetMaximumPacketSize(), and qrtplib::RTPSession::SetTimestampUnit().
Referenced by isValid(), RTPSink(), and AudioNetSink::setParameters().
 {
     uint32_t timestampinc;
     QMutexLocker locker(&m_mutex);
     qDebug("RTPSink::setPayloadInformation: payloadType: %d sampleRate: %d", payloadType, sampleRate);
     switch (payloadType)
     {
     case PayloadPCMA8:
         m_sampleBytes = 1;
         m_rtpSession.SetDefaultPayloadType(8);
         m_packetSamples = m_sampleRate / 50; // 20ms packet samples
         timestampinc = m_sampleRate / 50;    // 1 channel
         break;
     case PayloadPCMU8:
         m_sampleBytes = 1;
         m_rtpSession.SetDefaultPayloadType(0);
         m_packetSamples = m_sampleRate / 50; // 20ms packet samples
         timestampinc = m_sampleRate / 50;    // 1 channel
         break;
     case PayloadL8:
         m_sampleBytes = 1;
         m_rtpSession.SetDefaultPayloadType(96);
         m_packetSamples = m_sampleRate / 50; // 20ms packet samples
         timestampinc = m_sampleRate / 50;    // 1 channel
         break;
     case PayloadL16Stereo:
         m_sampleBytes = 4;
         m_rtpSession.SetDefaultPayloadType(96);
         m_packetSamples = m_sampleRate / 50; // 20ms packet samples
         timestampinc = m_sampleRate / 100;   // 2 channels
         break;
     case PayloadG722:
         m_sampleBytes = 1;
         m_rtpSession.SetDefaultPayloadType(9);
         m_packetSamples = 160; // Fixed 8 kB/s 20ms packet samples
         timestampinc = 160;    // 1 channel
         break;
     case PayloadOpus:
         m_sampleBytes = 1;
         m_rtpSession.SetDefaultPayloadType(96);
         m_packetSamples = 160; // Payload size is 160 bytes
         timestampinc = 960;    // But increment is 960
         break;
     case PayloadL16Mono:
     default:
         m_sampleBytes = 2;
         m_rtpSession.SetDefaultPayloadType(96);
         m_packetSamples = m_sampleRate / 50; // 20ms packet samples
         timestampinc = m_sampleRate / 50;    // 1 channel
         break;
     }
     m_bufferSize = m_packetSamples * m_sampleBytes;
     if (m_byteBuffer) {
         delete[] m_byteBuffer;
     }
     m_byteBuffer = new uint8_t[m_bufferSize];
     m_sampleBufferIndex = 0;
     m_payloadType = payloadType;
     int status = m_rtpSession.SetTimestampUnit(1.0 / (double) m_sampleRate);
     if (status < 0) {
         qCritical("RTPSink::setPayloadInformation: cannot set timestamp unit: %s", qrtplib::RTPGetErrorString(status).c_str());
     } else {
         qDebug("RTPSink::setPayloadInformation: timestamp unit set to %f: %s",
                1.0 / (double) m_sampleRate,
                qrtplib::RTPGetErrorString(status).c_str());
     }
     status = m_rtpSession.SetDefaultMark(false);
     if (status < 0) {
         qCritical("RTPSink::setPayloadInformation: cannot set default mark: %s", qrtplib::RTPGetErrorString(status).c_str());
     } else {
         qDebug("RTPSink::setPayloadInformation: set default mark to false: %s", qrtplib::RTPGetErrorString(status).c_str());
     }
     status = m_rtpSession.SetDefaultTimestampIncrement(timestampinc);
     if (status < 0) {
         qCritical("RTPSink::setPayloadInformation: cannot set default timestamp increment: %s", qrtplib::RTPGetErrorString(status).c_str());
     } else {
         qDebug("RTPSink::setPayloadInformation: set default timestamp increment to %d: %s", timestampinc, qrtplib::RTPGetErrorString(status).c_str());
     }
     int maximumPacketSize = m_bufferSize+20; // was +40
     while (maximumPacketSize < RTP_MINPACKETSIZE) {
         maximumPacketSize += m_bufferSize;
     }
     status = m_rtpSession.SetMaximumPacketSize(maximumPacketSize);
     if (status < 0) {
         qCritical("RTPSink::setPayloadInformation: cannot set maximum packet size: %s", qrtplib::RTPGetErrorString(status).c_str());
     } else {
         qDebug("RTPSink::setPayloadInformation: set maximum packet size to %d bytes: %s", maximumPacketSize, qrtplib::RTPGetErrorString(status).c_str());
     }
 }
write() [1/3]
void RTPSink::write (const uint8_t * sampleByte)
Definition at line 221 of file rtpsink.cpp.
References elemLength(), m_bufferSize, m_byteBuffer, m_endianReverse, m_mutex, m_packetSamples, m_payloadType, m_rtpSession, m_sampleBufferIndex, m_sampleBytes, qrtplib::RTPGetErrorString(), qrtplib::RTPSession::SendPacket(), and writeNetBuf().
Referenced by isValid(), and AudioNetSink::write().
 {
     QMutexLocker locker(&m_mutex);
     if (m_sampleBufferIndex < m_packetSamples)
     {
         writeNetBuf(&m_byteBuffer[m_sampleBufferIndex*m_sampleBytes],
                 sampleByte,
                 elemLength(m_payloadType),
                 m_sampleBytes,
                 m_endianReverse);
         m_sampleBufferIndex++;
     }
     else
     {
         int status = m_rtpSession.SendPacket((const void *) m_byteBuffer, (std::size_t) m_bufferSize);
         if (status < 0) {
             qCritical("RTPSink::write: cannot write packet: %s", qrtplib::RTPGetErrorString(status).c_str());
         }
         writeNetBuf(&m_byteBuffer[0],
             sampleByte,
             elemLength(m_payloadType),
             m_sampleBytes,
             m_endianReverse);
         m_sampleBufferIndex = 1;
     }
 }
write() [2/3]
void RTPSink::write (const uint8_t * sampleByteL, const uint8_t * sampleByteR)
Definition at line 251 of file rtpsink.cpp.
References elemLength(), m_bufferSize, m_byteBuffer, m_endianReverse, m_mutex, m_packetSamples, m_payloadType, m_rtpSession, m_sampleBufferIndex, m_sampleBytes, qrtplib::RTPGetErrorString(), qrtplib::RTPSession::SendPacket(), and writeNetBuf().
 {
     QMutexLocker locker(&m_mutex);
     if (m_sampleBufferIndex < m_packetSamples)
     {
         writeNetBuf(&m_byteBuffer[m_sampleBufferIndex*m_sampleBytes],
                 sampleByteL,
                 elemLength(m_payloadType),
                 m_sampleBytes,
                 m_endianReverse);
         writeNetBuf(&m_byteBuffer[m_sampleBufferIndex*m_sampleBytes + elemLength(m_payloadType)],
                 sampleByteR,
                 elemLength(m_payloadType),
                 m_sampleBytes,
                 m_endianReverse);
         m_sampleBufferIndex++;
     }
     else
     {
         int status = m_rtpSession.SendPacket((const void *) m_byteBuffer, (std::size_t) m_bufferSize);
         if (status < 0) {
             qCritical("RTPSink::write: cannot write packet: %s", qrtplib::RTPGetErrorString(status).c_str());
         }
         writeNetBuf(&m_byteBuffer[0], sampleByteL,  elemLength(m_payloadType), m_sampleBytes, m_endianReverse);
         writeNetBuf(&m_byteBuffer[2], sampleByteR,  elemLength(m_payloadType), m_sampleBytes, m_endianReverse);
         m_sampleBufferIndex = 1;
     }
 }
write() [3/3]
void RTPSink::write (const uint8_t * sampleByte, int nbSamples)
Definition at line 284 of file rtpsink.cpp.
References elemLength(), m_bufferSize, m_byteBuffer, m_endianReverse, m_mutex, m_packetSamples, m_payloadType, m_rtpSession, m_sampleBufferIndex, m_sampleBytes, qrtplib::RTPSession::SendPacket(), and writeNetBuf().
 {
     int samplesIndex = 0;
     QMutexLocker locker(&m_mutex);
     // fill remainder of buffer and send it
     if (m_sampleBufferIndex + nbSamples > m_packetSamples)
     {
         writeNetBuf(&m_byteBuffer[m_sampleBufferIndex*m_sampleBytes],
                 &samples[samplesIndex*m_sampleBytes],
                 elemLength(m_payloadType),
                 (m_packetSamples - m_sampleBufferIndex)*m_sampleBytes,
                 m_endianReverse);
         m_rtpSession.SendPacket((const void *) m_byteBuffer, (std::size_t) m_bufferSize);
         nbSamples -= (m_packetSamples - m_sampleBufferIndex);
         m_sampleBufferIndex = 0;
     }
     // send complete packets
     while (nbSamples > m_packetSamples)
     {
         writeNetBuf(m_byteBuffer,
                 samples,
                 elemLength(m_payloadType),
                 m_bufferSize,
                 m_endianReverse);
         m_rtpSession.SendPacket((const void *) m_byteBuffer, (std::size_t) m_bufferSize);
         samplesIndex += m_packetSamples;
         nbSamples -= m_packetSamples;
     }
     // copy remainder of input to buffer
     writeNetBuf(&m_byteBuffer[m_sampleBufferIndex*m_sampleBytes],
             &samples[samplesIndex*m_sampleBytes],
             elemLength(m_payloadType),
             nbSamples*m_sampleBytes,m_endianReverse);
 }
writeNetBuf()
void RTPSink::writeNetBuf (uint8_t * dest, const uint8_t * src, unsigned int elemLen, unsigned int bytesLen, bool endianReverse) static protected
Reverse endianess in destination buffer
Definition at line 322 of file rtpsink.cpp.
References i.
Referenced by isValid(), and write().
 {
     for (unsigned int i = 0; i < bytesLen; i += elemLen)
     {
         memcpy(&dest[i], &src[i], elemLen);
         if (endianReverse) {
             std::reverse(&dest[i], &dest[i+elemLen]);
         }
     }
 }
Member Data Documentation
m_bufferSize
int RTPSink::m_bufferSize protected
Definition at line 77 of file rtpsink.h.
Referenced by setPayloadInformation(), and write().
m_byteBuffer
uint8_t* RTPSink::m_byteBuffer protected
Definition at line 79 of file rtpsink.h.
Referenced by setPayloadInformation(), write(), and ~RTPSink().
m_destip
QHostAddress RTPSink::m_destip protected
Definition at line 80 of file rtpsink.h.
Referenced by setDestination().
m_destport
uint16_t RTPSink::m_destport protected
Definition at line 81 of file rtpsink.h.
Referenced by setDestination().
m_endianReverse
bool RTPSink::m_endianReverse protected
Definition at line 86 of file rtpsink.h.
Referenced by RTPSink(), and write().
m_mutex
QMutex RTPSink::m_mutex protected
Definition at line 87 of file rtpsink.h.
Referenced by setPayloadInformation(), and write().
m_packetSamples
int RTPSink::m_packetSamples protected
Definition at line 76 of file rtpsink.h.
Referenced by setPayloadInformation(), and write().
m_payloadType
PayloadType RTPSink::m_payloadType protected
Definition at line 73 of file rtpsink.h.
Referenced by RTPSink(), setPayloadInformation(), and write().
m_rtpSession
qrtplib::RTPSession RTPSink::m_rtpSession protected
Definition at line 82 of file rtpsink.h.
Referenced by addDestination(), deleteDestination(), RTPSink(), setDestination(), setPayloadInformation(), write(), and ~RTPSink().
m_rtpSessionParams
qrtplib::RTPSessionParams RTPSink::m_rtpSessionParams protected
Definition at line 83 of file rtpsink.h.
Referenced by RTPSink().
m_rtpTransmissionParams
qrtplib::RTPUDPTransmissionParams RTPSink::m_rtpTransmissionParams protected
Definition at line 84 of file rtpsink.h.
Referenced by RTPSink().
m_rtpTransmitter
qrtplib::RTPUDPTransmitter RTPSink::m_rtpTransmitter protected
Definition at line 85 of file rtpsink.h.
Referenced by RTPSink().
m_sampleBufferIndex
int RTPSink::m_sampleBufferIndex protected
Definition at line 78 of file rtpsink.h.
Referenced by setPayloadInformation(), and write().
m_sampleBytes
int RTPSink::m_sampleBytes protected
Definition at line 75 of file rtpsink.h.
Referenced by setPayloadInformation(), and write().
m_sampleRate
int RTPSink::m_sampleRate protected
Definition at line 74 of file rtpsink.h.
Referenced by RTPSink(), and setPayloadInformation().
m_valid
bool RTPSink::m_valid protected
Definition at line 72 of file rtpsink.h.
Referenced by isValid(), and RTPSink().
The documentation for this class was generated from the following files:
sdrbase/util/rtpsink.h
sdrbase/util/rtpsink.cpp