SDRAngel: MagAGC Class Reference
MagAGC Class Reference
#include <agc.h>
Public Member Functions
MagAGC (int historySize, double R, double threshold)
virtual ~MagAGC ()
void setSquared (bool squared)
void resize (int historySize, int stepLength, Real R)
void setOrder (double R)
virtual void feed (Complex &ci)
double feedAndGetValue (const Complex &ci)
double getMagSq () const
void setThreshold (double threshold)
void setThresholdEnable (bool enable)
void setGate (int gate)
void setStepDownDelay (int stepDownDelay)
void setClamping (bool clamping)
void setClampMax (double clampMax)
int getStepDownDelay () const
float getStepValue () const
void setHardLimiting (bool hardLimiting)
Public Member Functions inherited from AGC
AGC (int historySize, double R)
virtual ~AGC ()
void resize (int historySize, double R)
void setOrder (double R)
Real getValue ()
Real getAverage ()
Private Member Functions
double hardLimiter (double multiplier, double magsq)
Private Attributes
bool m_squared
use squared magnitude (power) to compute AGC value
double m_magsq
current squared magnitude (power)
double m_threshold
squelch on magsq average
bool m_thresholdEnable
enable squelch on power threshold
int m_gate
power threshold gate in number of samples
int m_stepLength
transition step length in number of samples
double m_stepDelta
transition step unit by sample
int m_stepUpCounter
step up transition samples counter
int m_stepDownCounter
step down transition samples counter
int m_gateCounter
threshold gate samples counter
int m_stepDownDelay
delay in samples before cutoff (release)
bool m_clamping
clamping active
double m_R2
square of ordered magnitude
double m_clampMax
maximum to clamp to as power value
bool m_hardLimiting
hard limit multiplier so that resulting sample magnitude does not exceed 1.0
Additional Inherited Members
Protected Attributes inherited from AGC
double m_u0
AGC factor.
double m_R
ordered magnitude
MovingAverage< double > m_moving_average
Averaging engine. The stack length conditions the smoothness of AGC.
int m_historySize
Averaging length (attack)
int m_count
Samples counter.
Detailed Description
Definition at line 36 of file agc.h.
Constructor & Destructor Documentation
MagAGC()
MagAGC::MagAGC (int historySize, double R, double threshold)
Definition at line 43 of file agc.cpp.
                                                           :
     AGC(historySize, R),
     m_squared(false),
     m_magsq(0.0),
     m_threshold(threshold),
     m_thresholdEnable(true),
     m_gate(0),
     m_stepLength(std::min(2400, historySize/2)), // max 50 ms (at 48 kHz)
     m_stepDelta(1.0/m_stepLength),
     m_stepUpCounter(0),
     m_stepDownCounter(0),
     m_gateCounter(0),
     m_stepDownDelay(historySize),
     m_clamping(false),
     m_R2(R*R),
     m_clampMax(1.0),
     m_hardLimiting(false)
 {}
~MagAGC()
MagAGC::~MagAGC () virtual
Definition at line 62 of file agc.cpp.
 {}
Member Function Documentation
feed()
void MagAGC::feed (Complex & ci) virtual
Implements AGC.
Definition at line 94 of file agc.cpp.
References feedAndGetValue().
 {
     ci *= feedAndGetValue(ci);
 }
feedAndGetValue()
double MagAGC::feedAndGetValue (const Complex & ci)
Definition at line 108 of file agc.cpp.
References MovingAverage< Type >::average(), MovingAverage< Type >::feed(), hardLimiter(), m_clamping, m_clampMax, AGC::m_count, m_gate, m_gateCounter, m_magsq, AGC::m_moving_average, AGC::m_R, m_squared, m_stepDelta, m_stepDownCounter, m_stepDownDelay, m_stepLength, m_stepUpCounter, m_threshold, m_thresholdEnable, AGC::m_u0, StepFunctions::smootherstep(), and sqrt().
Referenced by feed(), UDPSink::feed(), AMDemod::processOneSample(), and SSBDemod::processOneSample().
 {
     m_magsq = ci.real()*ci.real() + ci.imag()*ci.imag();
     m_moving_average.feed(m_magsq);
     if (m_clamping)
     {
         if (m_squared)
         {
             if (m_magsq > m_clampMax) {
                 m_u0 = m_clampMax / m_magsq;
             } else {
                 m_u0 = m_R / m_moving_average.average();
             }
         }
         else
         {
             if (sqrt(m_magsq) > m_clampMax) {
                 m_u0 = m_clampMax / sqrt(m_magsq);
             } else {
                 m_u0 = m_R / sqrt(m_moving_average.average());
             }
         }
     }
     else
     {
         m_u0 = m_R / (m_squared ? m_moving_average.average() : sqrt(m_moving_average.average()));
     }
     if (m_thresholdEnable)
     {
         bool open = false;
         if (m_magsq > m_threshold)
         {
             if (m_gateCounter < m_gate) {
                 m_gateCounter++;
             } else {
                 open = true;
             }
         }
         else
         {
             m_gateCounter = 0;
         }
         if (open)
         {
             m_count = m_stepDownDelay; // delay before step down (grace delay)
         }
         else
         {
             m_count--;
             m_gateCounter = m_gate; // keep gate open during grace
         }
         if (m_count > 0) // up phase
         {
             m_stepDownCounter = m_stepUpCounter; // prepare for step down
             if (m_stepUpCounter < m_stepLength) // step up
             {
                 m_stepUpCounter++;
                 return hardLimiter(m_u0 * StepFunctions::smootherstep(m_stepUpCounter * m_stepDelta), m_magsq);
             }
             else // steady open
             {
                 return hardLimiter(m_u0, m_magsq);
             }
         }
         else // down phase
         {
             m_stepUpCounter = m_stepDownCounter; // prepare for step up
             if (m_stepDownCounter > 0) // step down
             {
                 m_stepDownCounter--;
                 return hardLimiter(m_u0 * StepFunctions::smootherstep(m_stepDownCounter * m_stepDelta), m_magsq);
             }
             else // steady closed
             {
                 return 0.0;
             }
         }
     }
     else
     {
         return hardLimiter(m_u0, m_magsq);
     }
 }
getMagSq()
double MagAGC::getMagSq () const inline
Definition at line 46 of file agc.h.
Referenced by UDPSink::feed().
 { return m_magsq; }
getStepDownDelay()
int MagAGC::getStepDownDelay () const inline
Definition at line 53 of file agc.h.
Referenced by SSBDemod::processOneSample().
 { return m_stepDownDelay; }
getStepValue()
float MagAGC::getStepValue () const
Definition at line 199 of file agc.cpp.
References AGC::m_count, m_stepDelta, m_stepDownCounter, m_stepUpCounter, and StepFunctions::smootherstep().
Referenced by SSBDemod::processOneSample().
 {
     if (m_count > 0) // up phase
     {
         return StepFunctions::smootherstep(m_stepUpCounter * m_stepDelta); // step up
     }
     else // down phase
     {
         return StepFunctions::smootherstep(m_stepDownCounter * m_stepDelta); // step down
     }
 }
hardLimiter()
double MagAGC::hardLimiter (double multiplier, double magsq) private
Definition at line 99 of file agc.cpp.
References m_hardLimiting, and sqrt().
Referenced by feedAndGetValue().
 {
     if ((m_hardLimiting) && (multiplier*multiplier*magsq > 1.0)) {
         return 1.0 / (multiplier*sqrt(magsq));
     } else {
         return multiplier;
     }
 }
resize()
void MagAGC::resize (int historySize, int stepLength, Real R)
Definition at line 65 of file agc.cpp.
References MovingAverage< Type >::fill(), AGC::m_moving_average, m_R2, m_stepDelta, m_stepDownCounter, m_stepLength, m_stepUpCounter, and AGC::resize().
Referenced by AMDemod::AMDemod(), AMDemod::applyAudioSampleRate(), SSBDemod::applyAudioSampleRate(), UDPSink::applySettings(), and SSBDemod::applySettings().
 {
     m_R2 = R*R;
     m_stepLength = stepLength;
     m_stepDelta = 1.0 / m_stepLength;
     m_stepUpCounter = 0;
     m_stepDownCounter = 0;
     AGC::resize(historySize, R);
     m_moving_average.fill(0);
 }
setClamping()
void MagAGC::setClamping (bool clamping) inline
Definition at line 51 of file agc.h.
Referenced by SSBDemod::applySettings(), SSBDemod::SSBDemod(), and UDPSink::UDPSink().
 { m_clamping = clamping; }
setClampMax()
void MagAGC::setClampMax (double clampMax) inline
Definition at line 52 of file agc.h.
Referenced by SSBDemod::SSBDemod(), and UDPSink::UDPSink().
 { m_clampMax = clampMax; }
setGate()
void MagAGC::setGate (int gate) inline
Definition at line 49 of file agc.h.
Referenced by SSBDemod::applyAudioSampleRate(), UDPSink::applySettings(), and SSBDemod::applySettings().
 { m_gate = gate; m_gateCounter = 0; m_count = 0; }
setHardLimiting()
void MagAGC::setHardLimiting (bool hardLimiting) inline
Definition at line 55 of file agc.h.
 { m_hardLimiting = hardLimiting; }
setOrder()
void MagAGC::setOrder (double R)
Definition at line 76 of file agc.cpp.
References MovingAverage< Type >::fill(), AGC::m_moving_average, m_R2, and AGC::setOrder().
 {
     m_R2 = R*R;
     AGC::setOrder(R);
     m_moving_average.fill(0);
 }
setSquared()
void MagAGC::setSquared (bool squared) inline
Definition at line 41 of file agc.h.
References AGC::feed(), AGC::resize(), and AGC::setOrder().
 { m_squared = squared; }
setStepDownDelay()
void MagAGC::setStepDownDelay (int stepDownDelay) inline
Definition at line 50 of file agc.h.
Referenced by SSBDemod::applyAudioSampleRate(), UDPSink::applySettings(), and SSBDemod::applySettings().
 { m_stepDownDelay = stepDownDelay; m_gateCounter = 0; m_count = 0; }
setThreshold()
void MagAGC::setThreshold (double threshold) inline
Definition at line 47 of file agc.h.
Referenced by UDPSink::applySettings(), and SSBDemod::applySettings().
 { m_threshold = threshold; }
setThresholdEnable()
void MagAGC::setThresholdEnable (bool enable)
Definition at line 83 of file agc.cpp.
References m_stepDownCounter, m_stepUpCounter, and m_thresholdEnable.
Referenced by AMDemod::AMDemod(), and SSBDemod::applySettings().
 {
     if (m_thresholdEnable != enable)
     {
         m_stepUpCounter = 0;
         m_stepDownCounter = 0;
     }
     m_thresholdEnable = enable;
 }
Member Data Documentation
m_clamping
bool MagAGC::m_clamping private
clamping active
Definition at line 69 of file agc.h.
Referenced by feedAndGetValue().
m_clampMax
double MagAGC::m_clampMax private
maximum to clamp to as power value
Definition at line 71 of file agc.h.
Referenced by feedAndGetValue().
m_gate
int MagAGC::m_gate private
power threshold gate in number of samples
Definition at line 62 of file agc.h.
Referenced by feedAndGetValue().
m_gateCounter
int MagAGC::m_gateCounter private
threshold gate samples counter
Definition at line 67 of file agc.h.
Referenced by feedAndGetValue().
m_hardLimiting
bool MagAGC::m_hardLimiting private
hard limit multiplier so that resulting sample magnitude does not exceed 1.0
Definition at line 72 of file agc.h.
Referenced by hardLimiter().
m_magsq
double MagAGC::m_magsq private
current squared magnitude (power)
Definition at line 59 of file agc.h.
Referenced by feedAndGetValue().
m_R2
double MagAGC::m_R2 private
square of ordered magnitude
Definition at line 70 of file agc.h.
Referenced by resize(), and setOrder().
m_squared
bool MagAGC::m_squared private
use squared magnitude (power) to compute AGC value
Definition at line 58 of file agc.h.
Referenced by feedAndGetValue().
m_stepDelta
double MagAGC::m_stepDelta private
transition step unit by sample
Definition at line 64 of file agc.h.
Referenced by feedAndGetValue(), getStepValue(), and resize().
m_stepDownCounter
int MagAGC::m_stepDownCounter private
step down transition samples counter
Definition at line 66 of file agc.h.
Referenced by feedAndGetValue(), getStepValue(), resize(), and setThresholdEnable().
m_stepDownDelay
int MagAGC::m_stepDownDelay private
delay in samples before cutoff (release)
Definition at line 68 of file agc.h.
Referenced by feedAndGetValue().
m_stepLength
int MagAGC::m_stepLength private
transition step length in number of samples
Definition at line 63 of file agc.h.
Referenced by feedAndGetValue(), and resize().
m_stepUpCounter
int MagAGC::m_stepUpCounter private
step up transition samples counter
Definition at line 65 of file agc.h.
Referenced by feedAndGetValue(), getStepValue(), resize(), and setThresholdEnable().
m_threshold
double MagAGC::m_threshold private
squelch on magsq average
Definition at line 60 of file agc.h.
Referenced by feedAndGetValue().
m_thresholdEnable
bool MagAGC::m_thresholdEnable private
enable squelch on power threshold
Definition at line 61 of file agc.h.
Referenced by feedAndGetValue(), and setThresholdEnable().
The documentation for this class was generated from the following files:
sdrbase/dsp/agc.h
sdrbase/dsp/agc.cpp