SDRAngel: qtwebapp::HttpRequestHandler Class Reference
qtwebapp::HttpRequestHandler Class Reference
#include <httprequesthandler.h>
Public Member Functions
HttpRequestHandler (QObject *parent=NULL)
virtual ~HttpRequestHandler ()
virtual void service (HttpRequest &request, HttpResponse &response)
Detailed Description
The request handler generates a response for each HTTP request. Web Applications usually have one central request handler that maps incoming requests to several controllers (servlets) based on the requested path.
You need to override the service() method or you will always get an HTTP error 501.
Warning
Be aware that the main request handler instance must be created on the heap and that it is used by multiple threads simultaneously.
See also
StaticFileController which delivers static local files.
Definition at line 29 of file httprequesthandler.h.
Constructor & Destructor Documentation
HttpRequestHandler()
HttpRequestHandler::HttpRequestHandler (QObject * parent = NULL)
Constructor.
Parameters
parent Parent object.
Definition at line 10 of file httprequesthandler.cpp.
     : QObject(parent)
 {}
~HttpRequestHandler()
HttpRequestHandler::~HttpRequestHandler () virtual
Destructor
Definition at line 14 of file httprequesthandler.cpp.
 {}
Member Function Documentation
service()
void HttpRequestHandler::service (HttpRequest & request, HttpResponse & response) virtual
Generate a response for an incoming HTTP request.
Parameters
request The received HTTP request
response Must be used to return the response
Warning
This method must be thread safe
Reimplemented in qtwebapp::StaticFileController, and WebAPIRequestMapper.
Definition at line 17 of file httprequesthandler.cpp.
References qtwebapp::HttpRequest::getMethod(), qtwebapp::HttpRequest::getPath(), qtwebapp::HttpRequest::getVersion(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by qtwebapp::HttpConnectionHandler::read().
 {
     qCritical("HttpRequestHandler: you need to override the service() function");
     qDebug("HttpRequestHandler: request=%s %s %s",request.getMethod().data(),request.getPath().data(),request.getVersion().data());
     response.setStatus(501,"not implemented");
     response.write("501 not implemented",true);
 }
The documentation for this class was generated from the following files:
httpserver/httprequesthandler.h
httpserver/httprequesthandler.cpp