SDRAngel: SDRPlayBands Class Reference
SDRPlayBands Class Reference
#include <sdrplayinput.h>
Static Public Member Functions
static QString getBandName (unsigned int band_index)
static unsigned int getBandLow (unsigned int band_index)
static unsigned int getBandHigh (unsigned int band_index)
static unsigned int getNbBands ()
Static Private Attributes
static const unsigned int m_nb_bands = 8
static unsigned int m_bandLow [m_nb_bands]
static unsigned int m_bandHigh [m_nb_bands]
static const char * m_bandName [m_nb_bands]
Detailed Description
Definition at line 242 of file sdrplayinput.h.
Member Function Documentation
getBandHigh()
unsigned int SDRPlayBands::getBandHigh (unsigned int band_index) static
Definition at line 1170 of file sdrplayinput.cpp.
Referenced by SDRPlayGui::on_fBand_currentIndexChanged(), and SDRPlayInput::webapiFormatDeviceReport().
 {
     if (band_index < m_nb_bands)
     {
         return m_bandHigh[band_index];
     }
     else
     {
         return m_bandHigh[0];
     }
 }
getBandLow()
unsigned int SDRPlayBands::getBandLow (unsigned int band_index) static
Definition at line 1158 of file sdrplayinput.cpp.
Referenced by SDRPlayGui::on_fBand_currentIndexChanged(), and SDRPlayInput::webapiFormatDeviceReport().
 {
     if (band_index < m_nb_bands)
     {
         return m_bandLow[band_index];
     }
     else
     {
         return m_bandLow[0];
     }
 }
getBandName()
QString SDRPlayBands::getBandName (unsigned int band_index) static
Definition at line 1146 of file sdrplayinput.cpp.
Referenced by SDRPlayGui::SDRPlayGui(), and SDRPlayInput::webapiFormatDeviceReport().
 {
     if (band_index < m_nb_bands)
     {
         return QString(m_bandName[band_index]);
     }
     else
     {
         return QString(m_bandName[0]);
     }
 }
getNbBands()
unsigned int SDRPlayBands::getNbBands () static
Definition at line 1183 of file sdrplayinput.cpp.
References m_nb_bands.
Referenced by SDRPlayGui::SDRPlayGui(), and SDRPlayInput::webapiFormatDeviceReport().
 {
     return SDRPlayBands::m_nb_bands;
 }
Member Data Documentation
m_bandHigh
unsigned int SDRPlayBands::m_bandHigh static private
Initial value:
= {
        12000,
        30000,
        50000,
        120000,
        250000,
        380000,
        1000000,
        2000000,
}
Lower frequency bound in kHz exclusive
Definition at line 251 of file sdrplayinput.h.
Referenced by SDRPlayIF::getNbIFs().
m_bandLow
unsigned int SDRPlayBands::m_bandLow static private
Initial value:
= {
        10,
        12000,
        30000,
        50000,
        120000,
        250000,
        380000,
        1000000,
}
Lower frequency bound in kHz inclusive
Definition at line 250 of file sdrplayinput.h.
Referenced by SDRPlayIF::getNbIFs().
m_bandName
const char * SDRPlayBands::m_bandName static private
Initial value:
= {
        "10k-12M",
        "12-30M",
        "30-50M",
        "50-120M",
        "120-250M",
        "250-380M",
        "380M-1G",
        "1-2G",
}
Definition at line 252 of file sdrplayinput.h.
Referenced by SDRPlayIF::getNbIFs().
m_nb_bands
const unsigned int SDRPlayBands::m_nb_bands = 8 static private
Definition at line 249 of file sdrplayinput.h.
Referenced by getNbBands().
The documentation for this class was generated from the following files:
plugins/samplesource/sdrplay/sdrplayinput.h
plugins/samplesource/sdrplay/sdrplayinput.cpp