SDRAngel: KiwiSDRGui Class Reference
KiwiSDRGui Class Reference
#include <kiwisdrgui.h>
Public Member Functions
KiwiSDRGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~KiwiSDRGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_startStop_toggled (bool checked)
void on_centerFrequency_changed (quint64 value)
void on_record_toggled (bool checked)
void on_gain_valueChanged (int value)
void on_agc_toggled (bool checked)
void on_serverAddress_returnPressed ()
void on_serverAddressApplyButton_clicked ()
void on_dcBlock_toggled (bool checked)
void openDeviceSettingsDialog (const QPoint &p)
void updateStatus ()
void updateHardware ()
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void sendSettings ()
void updateSampleRateAndFrequency ()
Private Attributes
Ui::KiwiSDRGui * ui
DeviceUISet * m_deviceUISet
KiwiSDRSettings m_settings
QTimer m_updateTimer
QTimer m_statusTimer
bool m_doApplySettings
bool m_forceSettings
DeviceSampleSource * m_sampleSource
std::size_t m_tickCount
int m_deviceSampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
std::vector< QString > m_statusColors
std::vector< QString > m_statusTooltips
Detailed Description
Definition at line 37 of file kiwisdrgui.h.
Constructor & Destructor Documentation
KiwiSDRGui()
KiwiSDRGui::KiwiSDRGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 42 of file kiwisdrgui.cpp.
References displaySettings(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_sampleSource, m_statusColors, m_statusTimer, m_statusTooltips, m_updateTimer, openDeviceSettingsDialog(), DeviceSampleSource::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                                 :
     QWidget(parent),
     ui(new Ui::KiwiSDRGui),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_sampleSource(0),
     m_tickCount(0),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     qDebug("KiwiSDRGui::KiwiSDRGui");
     m_sampleSource = m_deviceUISet->m_deviceAPI->getSampleSource();
     m_statusTooltips.push_back("Idle");          // 0
     m_statusTooltips.push_back("Connecting..."); // 1
     m_statusTooltips.push_back("Connected");     // 2
     m_statusTooltips.push_back("Error");         // 3
     m_statusTooltips.push_back("Disconnected");  // 4
     m_statusColors.push_back("gray");               // Idle
     m_statusColors.push_back("rgb(232, 212, 35)");  // Connecting (yellow)
     m_statusColors.push_back("rgb(35, 138, 35)");   // Connected (green)
     m_statusColors.push_back("rgb(232, 85, 85)");   // Error (red)
     m_statusColors.push_back("rgb(232, 85, 232)");  // Disconnected (magenta)
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, 0, 9999999);
     displaySettings();
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
 }
~KiwiSDRGui()
KiwiSDRGui::~KiwiSDRGui () virtual
Definition at line 85 of file kiwisdrgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void KiwiSDRGui::blockApplySettings (bool block) inline private
Definition at line 74 of file kiwisdrgui.h.
Referenced by displaySettings(), and handleMessage().
 { m_doApplySettings = !block; }
deserialize()
bool KiwiSDRGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 129 of file kiwisdrgui.cpp.
References KiwiSDRSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void KiwiSDRGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 90 of file kiwisdrgui.cpp.
 {
     delete this;
 }
displaySettings()
void KiwiSDRGui::displaySettings () private
Definition at line 199 of file kiwisdrgui.cpp.
References blockApplySettings(), KiwiSDRSettings::m_centerFrequency, KiwiSDRSettings::m_dcBlock, KiwiSDRSettings::m_gain, KiwiSDRSettings::m_serverAddress, m_settings, KiwiSDRSettings::m_useAGC, and ui.
Referenced by deserialize(), handleMessage(), KiwiSDRGui(), resetToDefaults(), and setCenterFrequency().
 {
     blockApplySettings(true);
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     ui->serverAddress->setText(m_settings.m_serverAddress);
     ui->gain->setValue(m_settings.m_gain);
     ui->gainText->setText(QString::number(m_settings.m_gain) + " dB");
     ui->agc->setChecked(m_settings.m_useAGC);
     ui->dcBlock->setChecked(m_settings.m_dcBlock);
     blockApplySettings(false);
 }
getCenterFrequency()
qint64 KiwiSDRGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 112 of file kiwisdrgui.cpp.
References KiwiSDRSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* KiwiSDRGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 53 of file kiwisdrgui.h.
 { return &m_inputMessageQueue; }
getName()
QString KiwiSDRGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 100 of file kiwisdrgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void KiwiSDRGui::handleInputMessages () private slot
Definition at line 296 of file kiwisdrgui.cpp.
References DSPSignalNotification::getCenterFrequency(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_deviceSampleRate, m_inputMessageQueue, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by KiwiSDRGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_deviceSampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("KiwiSDRGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu",
                     notif->getSampleRate(),
                     notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool KiwiSDRGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 260 of file kiwisdrgui.cpp.
References blockApplySettings(), displaySettings(), KiwiSDRInput::MsgConfigureKiwiSDR::getSettings(), KiwiSDRInput::MsgStartStop::getStartStop(), KiwiSDRInput::MsgSetStatus::getStatus(), m_settings, m_statusColors, m_statusTooltips, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (KiwiSDRInput::MsgConfigureKiwiSDR::match(message))
     {
         qDebug("KiwiSDRGui::handleMessage: MsgConfigureKiwiSDR");
         const KiwiSDRInput::MsgConfigureKiwiSDR& cfg = (KiwiSDRInput::MsgConfigureKiwiSDR&) message;
         m_settings = cfg.getSettings();
         displaySettings();
         return true;
     }
     else if (KiwiSDRInput::MsgStartStop::match(message))
     {
         qDebug("KiwiSDRGui::handleMessage: MsgStartStop");
         KiwiSDRInput::MsgStartStop& notif = (KiwiSDRInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else if (KiwiSDRInput::MsgSetStatus::match(message))
     {
         qDebug("KiwiSDRGui::handleMessage: MsgSetStatus");
         KiwiSDRInput::MsgSetStatus& notif = (KiwiSDRInput::MsgSetStatus&) message;
         int status = notif.getStatus();
         ui->statusIndicator->setToolTip(m_statusTooltips[status]);
         ui->statusIndicator->setStyleSheet("QLabel { background-color: " +
             m_statusColors[status] + "; border-radius: 7px; }");
         return true;
     }
     else
     {
         return false;
     }
 }
on_agc_toggled
void KiwiSDRGui::on_agc_toggled (bool checked) private slot
Definition at line 186 of file kiwisdrgui.cpp.
References m_settings, KiwiSDRSettings::m_useAGC, and sendSettings().
 {
     m_settings.m_useAGC = checked;
     sendSettings();
 }
on_centerFrequency_changed
void KiwiSDRGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 151 of file kiwisdrgui.cpp.
References KiwiSDRSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_dcBlock_toggled
void KiwiSDRGui::on_dcBlock_toggled (bool checked) private slot
Definition at line 168 of file kiwisdrgui.cpp.
References KiwiSDRSettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_gain_valueChanged
void KiwiSDRGui::on_gain_valueChanged (int value) private slot
Definition at line 192 of file kiwisdrgui.cpp.
References KiwiSDRSettings::m_gain, m_settings, sendSettings(), and ui.
 {
     m_settings.m_gain = value;
     ui->gainText->setText(QString::number(m_settings.m_gain) + " dB");
     sendSettings();
 }
on_record_toggled
void KiwiSDRGui::on_record_toggled (bool checked) private slot
Definition at line 174 of file kiwisdrgui.cpp.
References KiwiSDRInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     KiwiSDRInput::MsgFileRecord* message = KiwiSDRInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_serverAddress_returnPressed
void KiwiSDRGui::on_serverAddress_returnPressed () private slot
Definition at line 157 of file kiwisdrgui.cpp.
References on_serverAddressApplyButton_clicked().
 {
     on_serverAddressApplyButton_clicked();
 }
on_serverAddressApplyButton_clicked
void KiwiSDRGui::on_serverAddressApplyButton_clicked () private slot
Definition at line 162 of file kiwisdrgui.cpp.
References KiwiSDRSettings::m_serverAddress, m_settings, sendSettings(), and ui.
Referenced by on_serverAddress_returnPressed().
 {
     m_settings.m_serverAddress = ui->serverAddress->text();
     sendSettings();
 }
on_startStop_toggled
void KiwiSDRGui::on_startStop_toggled (bool checked) private slot
Definition at line 142 of file kiwisdrgui.cpp.
References KiwiSDRInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         KiwiSDRInput::MsgStartStop *message = KiwiSDRInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
openDeviceSettingsDialog
void KiwiSDRGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 331 of file kiwisdrgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), KiwiSDRSettings::m_reverseAPIAddress, KiwiSDRSettings::m_reverseAPIDeviceIndex, KiwiSDRSettings::m_reverseAPIPort, m_settings, KiwiSDRSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by KiwiSDRGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void KiwiSDRGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 105 of file kiwisdrgui.cpp.
References displaySettings(), m_settings, KiwiSDRSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void KiwiSDRGui::sendSettings () private
Definition at line 213 of file kiwisdrgui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_agc_toggled(), on_centerFrequency_changed(), on_dcBlock_toggled(), on_gain_valueChanged(), on_serverAddressApplyButton_clicked(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if (!m_updateTimer.isActive()) {
         m_updateTimer.start(100);
     }
 }
serialize()
QByteArray KiwiSDRGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 124 of file kiwisdrgui.cpp.
References m_settings, and KiwiSDRSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void KiwiSDRGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 117 of file kiwisdrgui.cpp.
References displaySettings(), KiwiSDRSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void KiwiSDRGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 95 of file kiwisdrgui.cpp.
 {
     setObjectName(name);
 }
updateHardware
void KiwiSDRGui::updateHardware () private slot
Definition at line 220 of file kiwisdrgui.cpp.
References KiwiSDRInput::MsgConfigureKiwiSDR::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by KiwiSDRGui().
 {
     if (m_doApplySettings)
     {
         KiwiSDRInput::MsgConfigureKiwiSDR* message = KiwiSDRInput::MsgConfigureKiwiSDR::create(m_settings, m_forceSettings);
         m_sampleSource->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void KiwiSDRGui::updateSampleRateAndFrequency () private
Definition at line 324 of file kiwisdrgui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceSampleRate, m_deviceUISet, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_deviceSampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg((float)m_deviceSampleRate / 1000));
 }
updateStatus
void KiwiSDRGui::updateStatus () private slot
Definition at line 231 of file kiwisdrgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by KiwiSDRGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if (m_lastEngineState != state)
     {
         switch (state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 KiwiSDRGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 68 of file kiwisdrgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceSampleRate
int KiwiSDRGui::m_deviceSampleRate private
Definition at line 67 of file kiwisdrgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* KiwiSDRGui::m_deviceUISet private
Definition at line 59 of file kiwisdrgui.h.
Referenced by KiwiSDRGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool KiwiSDRGui::m_doApplySettings private
Definition at line 63 of file kiwisdrgui.h.
Referenced by on_startStop_toggled(), and updateHardware().
m_forceSettings
bool KiwiSDRGui::m_forceSettings private
Definition at line 64 of file kiwisdrgui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue KiwiSDRGui::m_inputMessageQueue private
Definition at line 70 of file kiwisdrgui.h.
Referenced by handleInputMessages(), and KiwiSDRGui().
m_lastEngineState
int KiwiSDRGui::m_lastEngineState private
Definition at line 69 of file kiwisdrgui.h.
Referenced by updateStatus().
m_sampleSource
DeviceSampleSource* KiwiSDRGui::m_sampleSource private
Definition at line 65 of file kiwisdrgui.h.
Referenced by KiwiSDRGui(), on_record_toggled(), on_startStop_toggled(), and updateHardware().
m_settings
KiwiSDRSettings KiwiSDRGui::m_settings private
Definition at line 60 of file kiwisdrgui.h.
Referenced by deserialize(), displaySettings(), getCenterFrequency(), handleMessage(), on_agc_toggled(), on_centerFrequency_changed(), on_dcBlock_toggled(), on_gain_valueChanged(), on_serverAddressApplyButton_clicked(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), and updateHardware().
m_statusColors
std::vector<QString> KiwiSDRGui::m_statusColors private
Definition at line 71 of file kiwisdrgui.h.
Referenced by handleMessage(), and KiwiSDRGui().
m_statusTimer
QTimer KiwiSDRGui::m_statusTimer private
Definition at line 62 of file kiwisdrgui.h.
Referenced by KiwiSDRGui().
m_statusTooltips
std::vector<QString> KiwiSDRGui::m_statusTooltips private
Definition at line 72 of file kiwisdrgui.h.
Referenced by handleMessage(), and KiwiSDRGui().
m_tickCount
std::size_t KiwiSDRGui::m_tickCount private
Definition at line 66 of file kiwisdrgui.h.
m_updateTimer
QTimer KiwiSDRGui::m_updateTimer private
Definition at line 61 of file kiwisdrgui.h.
Referenced by KiwiSDRGui(), sendSettings(), and updateHardware().
ui
Ui::KiwiSDRGui* KiwiSDRGui::ui private
Definition at line 57 of file kiwisdrgui.h.
Referenced by displaySettings(), handleMessage(), KiwiSDRGui(), on_gain_valueChanged(), on_record_toggled(), on_serverAddressApplyButton_clicked(), updateSampleRateAndFrequency(), updateStatus(), and ~KiwiSDRGui().
The documentation for this class was generated from the following files:
plugins/samplesource/kiwisdr/kiwisdrgui.h
plugins/samplesource/kiwisdr/kiwisdrgui.cpp