SDRAngel: ScopeVis::TraceControl Struct Reference
ScopeVis::TraceControl Struct Reference
Public Member Functions
TraceControl ()
~TraceControl ()
void initProjector (Projector::ProjectionType projectionType)
void releaseProjector ()
void reset ()
Public Attributes
Projector m_projector
Projector transform from complex trace to real (displayable) trace.
uint32_t m_traceCount [2]
Count of samples processed (double buffered)
double m_maxPow
Maximum power over the current trace for MagDB overlay display.
double m_sumPow
Cumulative power over the current trace for MagDB overlay display.
int m_nbPow
Number of power samples over the current trace for MagDB overlay display.
Detailed Description
Displayable trace stuff
Definition at line 838 of file scopevis.h.
Constructor & Destructor Documentation
TraceControl()
ScopeVis::TraceControl::TraceControl () inline
Definition at line 846 of file scopevis.h.
                        : m_projector(Projector::ProjectionReal)
         {
             reset();
         }
~TraceControl()
ScopeVis::TraceControl::~TraceControl () inline
Definition at line 851 of file scopevis.h.
         {
         }
Member Function Documentation
initProjector()
void ScopeVis::TraceControl::initProjector (Projector::ProjectionType projectionType) inline
Definition at line 855 of file scopevis.h.
References Projector::settProjectionType().
Referenced by ScopeVis::Traces::addTrace(), ScopeVis::Traces::changeTrace(), and ScopeVis::Traces::moveTrace().
         {
             m_projector.settProjectionType(projectionType);
         }
releaseProjector()
void ScopeVis::TraceControl::releaseProjector () inline
Definition at line 860 of file scopevis.h.
Referenced by ScopeVis::Traces::changeTrace(), ScopeVis::Traces::moveTrace(), and ScopeVis::Traces::removeTrace().
         {
         }
reset()
void ScopeVis::TraceControl::reset () inline
Definition at line 864 of file scopevis.h.
         {
             m_traceCount[0] = 0;
             m_traceCount[1] = 0;
             m_maxPow = 0.0f;
             m_sumPow = 0.0f;
             m_nbPow = 0;
         }
Member Data Documentation
m_maxPow
double ScopeVis::TraceControl::m_maxPow
Maximum power over the current trace for MagDB overlay display.
Definition at line 842 of file scopevis.h.
m_nbPow
int ScopeVis::TraceControl::m_nbPow
Number of power samples over the current trace for MagDB overlay display.
Definition at line 844 of file scopevis.h.
m_projector
Projector ScopeVis::TraceControl::m_projector
Projector transform from complex trace to real (displayable) trace.
Definition at line 840 of file scopevis.h.
m_sumPow
double ScopeVis::TraceControl::m_sumPow
Cumulative power over the current trace for MagDB overlay display.
Definition at line 843 of file scopevis.h.
m_traceCount
uint32_t ScopeVis::TraceControl::m_traceCount[2]
Count of samples processed (double buffered)
Definition at line 841 of file scopevis.h.
The documentation for this struct was generated from the following file:
sdrgui/dsp/scopevis.h