SDRAngel: CommandOutputDialog Class Reference
CommandOutputDialog Class Reference
#include <commandoutputdialog.h>
Inherits QDialog.
Public Member Functions
CommandOutputDialog (Command &command, QWidget *parent=0)
~CommandOutputDialog ()
void fromCommand (const Command &command)
Private Slots
void on_processRefresh_toggled (bool checked)
void on_processKill_toggled (bool checked)
Private Member Functions
void refresh ()
void setErrorText (const QProcess::ProcessError &processError)
void setExitText (const QProcess::ExitStatus &processExit)
Private Attributes
Ui::CommandOutputDialog * ui
Command & m_command
Detailed Description
Definition at line 32 of file commandoutputdialog.h.
Constructor & Destructor Documentation
CommandOutputDialog()
CommandOutputDialog::CommandOutputDialog (Command & command, QWidget * parent = 0) explicit
Definition at line 24 of file commandoutputdialog.cpp.
References refresh(), and ui.
                                                                           :
     QDialog(parent),
     ui(new Ui::CommandOutputDialog),
     m_command(command)
 {
     ui->setupUi(this);
     refresh();
 }
~CommandOutputDialog()
CommandOutputDialog::~CommandOutputDialog ()
Definition at line 33 of file commandoutputdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
fromCommand()
void CommandOutputDialog::fromCommand (const Command & command)
on_processKill_toggled
void CommandOutputDialog::on_processKill_toggled (bool checked) private slot
Definition at line 160 of file commandoutputdialog.cpp.
References Command::kill(), m_command, and ui.
 {
     if (checked)
     {
         m_command.kill();
         ui->processKill->setChecked(false);
     }
 }
on_processRefresh_toggled
void CommandOutputDialog::on_processRefresh_toggled (bool checked) private slot
Definition at line 151 of file commandoutputdialog.cpp.
References refresh(), and ui.
 {
     if (checked)
     {
         refresh();
         ui->processRefresh->setChecked(false);
     }
 }
refresh()
void CommandOutputDialog::refresh () private
Definition at line 38 of file commandoutputdialog.cpp.
References arg(), Command::getLastProcessCommandLine(), Command::getLastProcessError(), Command::getLastProcessExit(), Command::getLastProcessFinishTimestampms(), Command::getLastProcessLog(), Command::getLastProcessPid(), Command::getLastProcessStartTimestampms(), Command::getLastProcessState(), m_command, setErrorText(), setExitText(), and ui.
Referenced by CommandOutputDialog(), and on_processRefresh_toggled().
 {
     ui->commandText->setText(m_command.getLastProcessCommandLine());
     ui->processPid->setText(QString("%1").arg(m_command.getLastProcessPid()));
     if (m_command.getLastProcessStartTimestampms() == 0) {
         ui->startTime->setText(("..."));
     }
     else
     {
         QDateTime dt = QDateTime::fromMSecsSinceEpoch(m_command.getLastProcessStartTimestampms());
         QString dateStr = dt.toString("yyyy-MM-dd HH:mm:ss.zzz");
         ui->startTime->setText(dateStr);
     }
     if (m_command.getLastProcessFinishTimestampms() == 0) {
         ui->endTime->setText(("..."));
     }
     else
     {
         QDateTime dt = QDateTime::fromMSecsSinceEpoch(m_command.getLastProcessFinishTimestampms());
         QString dateStr = dt.toString("yyyy-MM-dd HH:mm:ss.zzz");
         ui->endTime->setText(dateStr);
     }
     ui->runningState->setChecked(m_command.getLastProcessState() == QProcess::Running);
     QProcess::ProcessError processError;
     if (m_command.getLastProcessStartTimestampms() == 0) // not started
     {
         ui->errorText->setText("...");
         ui->exitCode->setText("-");
         ui->exitText->setText("...");
         ui->runningState->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     else if (m_command.getLastProcessState() != QProcess::NotRunning) // running
     {
         ui->errorText->setText("...");
         ui->runningState->setStyleSheet("QToolButton { background-color : orange; }");
     }
     else // finished
     {
         if (m_command.getLastProcessError(processError)) // finished
         {
             ui->runningState->setStyleSheet("QToolButton { background-color : red; }");
             setErrorText(processError);
         }
         else
         {
             ui->runningState->setStyleSheet("QToolButton { background-color : green; }");
             ui->errorText->setText("No error");
         }
         int processExitCode;
         QProcess::ExitStatus processExitStatus;
         if (m_command.getLastProcessExit(processExitCode, processExitStatus))
         {
             ui->exitCode->setText(QString("%1").arg(processExitCode));
             setExitText(processExitStatus);
         }
         else
         {
             ui->exitCode->setText("-");
             ui->exitText->setText("...");
         }
     }
     ui->logEdit->setPlainText(m_command.getLastProcessLog());
 }
setErrorText()
void CommandOutputDialog::setErrorText (const QProcess::ProcessError & processError) private
Definition at line 109 of file commandoutputdialog.cpp.
References ui.
Referenced by refresh().
 {
     switch(processError)
     {
     case QProcess::FailedToStart:
         ui->errorText->setText("Failed to start");
         break;
     case QProcess::Crashed:
         ui->errorText->setText("Crashed");
         break;
     case QProcess::Timedout:
         ui->errorText->setText("Timed out");
         break;
     case QProcess::WriteError:
         ui->errorText->setText("Write error");
         break;
     case QProcess::ReadError:
         ui->errorText->setText("Read error");
         break;
     case QProcess::UnknownError:
     default:
         ui->errorText->setText("Unknown error");
         break;
     }
 }
setExitText()
void CommandOutputDialog::setExitText (const QProcess::ExitStatus & processExit) private
Definition at line 135 of file commandoutputdialog.cpp.
References ui.
Referenced by refresh().
 {
     switch(processExit)
     {
     case QProcess::NormalExit:
         ui->exitText->setText("Normal exit");
         break;
     case QProcess::CrashExit:
         ui->exitText->setText("Program crashed");
         break;
     default:
         ui->exitText->setText("Unknown state");
         break;
     }
 }
Member Data Documentation
m_command
Command& CommandOutputDialog::m_command private
Definition at line 43 of file commandoutputdialog.h.
Referenced by on_processKill_toggled(), and refresh().
ui
Ui::CommandOutputDialog* CommandOutputDialog::ui private
Definition at line 42 of file commandoutputdialog.h.
Referenced by CommandOutputDialog(), on_processKill_toggled(), on_processRefresh_toggled(), refresh(), setErrorText(), setExitText(), and ~CommandOutputDialog().
The documentation for this class was generated from the following files:
sdrgui/gui/commandoutputdialog.h
sdrgui/gui/commandoutputdialog.cpp