SDRAngel: ATVMod::MsgReportEffectiveSampleRate Class Reference
ATVMod::MsgReportEffectiveSampleRate Class Reference
#include <atvmod.h>
Public Member Functions
int getSampleRate () const
uint32_t gatNbPointsPerLine () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportEffectiveSampleRate * create (int sampleRate, uint32_t nbPointsPerLine)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportEffectiveSampleRate (int sampleRate, uint32_t nbPointsPerLine)
Protected Attributes
int m_sampleRate
uint32_t m_nbPointsPerLine
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 332 of file atvmod.h.
Constructor & Destructor Documentation
MsgReportEffectiveSampleRate()
ATVMod::MsgReportEffectiveSampleRate::MsgReportEffectiveSampleRate (int sampleRate, uint32_t nbPointsPerLine) inline protected
Definition at line 349 of file atvmod.h.
References ATVMod::ATVMod(), and ATVMod::~ATVMod().
                                           :
             Message(),
             m_sampleRate(sampleRate),
             m_nbPointsPerLine(nbPointsPerLine)
         { }
Member Function Documentation
create()
static MsgReportEffectiveSampleRate* ATVMod::MsgReportEffectiveSampleRate::create (int sampleRate, uint32_t nbPointsPerLine) inline static
Definition at line 340 of file atvmod.h.
Referenced by ATVMod::applyChannelSettings(), and ATVMod::applySettings().
         {
             return new MsgReportEffectiveSampleRate(sampleRate, nbPointsPerLine);
         }
gatNbPointsPerLine()
uint32_t ATVMod::MsgReportEffectiveSampleRate::gatNbPointsPerLine () const inline
Definition at line 338 of file atvmod.h.
 { return m_nbPointsPerLine; }
getSampleRate()
int ATVMod::MsgReportEffectiveSampleRate::getSampleRate () const inline
Definition at line 337 of file atvmod.h.
 { return m_sampleRate; }
Member Data Documentation
m_nbPointsPerLine
uint32_t ATVMod::MsgReportEffectiveSampleRate::m_nbPointsPerLine protected
Definition at line 347 of file atvmod.h.
m_sampleRate
int ATVMod::MsgReportEffectiveSampleRate::m_sampleRate protected
Definition at line 346 of file atvmod.h.
The documentation for this class was generated from the following file:
plugins/channeltx/modatv/atvmod.h