SDRAngel: SWGSDRangel::SWGSoapySDRFrequencySetting Class Reference
SWGSDRangel::SWGSoapySDRFrequencySetting Class Reference
#include <SWGSoapySDRFrequencySetting.h>
Public Member Functions
SWGSoapySDRFrequencySetting ()
SWGSoapySDRFrequencySetting (QString *json)
virtual ~SWGSoapySDRFrequencySetting ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGSoapySDRFrequencySetting * fromJson (QString &jsonString) override
QString * getName ()
void setName (QString *name)
QList< SWGRangeFloat * > * getRanges ()
void setRanges (QList< SWGRangeFloat *> *ranges)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * name
bool m_name_isSet
QList< SWGRangeFloat * > * ranges
bool m_ranges_isSet
Detailed Description
Definition at line 34 of file SWGSoapySDRFrequencySetting.h.
Constructor & Destructor Documentation
SWGSoapySDRFrequencySetting() [1/2]
SWGSDRangel::SWGSoapySDRFrequencySetting::SWGSoapySDRFrequencySetting ()
Definition at line 30 of file SWGSoapySDRFrequencySetting.cpp.
References m_name_isSet, m_ranges_isSet, name, and ranges.
{
     name = nullptr;
     m_name_isSet = false;
     ranges = nullptr;
     m_ranges_isSet = false;
 }
SWGSoapySDRFrequencySetting() [2/2]
SWGSDRangel::SWGSoapySDRFrequencySetting::SWGSoapySDRFrequencySetting (QString * json)
Definition at line 25 of file SWGSoapySDRFrequencySetting.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGSoapySDRFrequencySetting()
SWGSDRangel::SWGSoapySDRFrequencySetting::~SWGSoapySDRFrequencySetting () virtual
Definition at line 37 of file SWGSoapySDRFrequencySetting.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGSoapySDRFrequencySetting::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 81 of file SWGSoapySDRFrequencySetting.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGSoapySDRFrequencySetting::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 92 of file SWGSoapySDRFrequencySetting.cpp.
References name, ranges, SWGSDRangel::toJsonArray(), and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(name != nullptr && *name != QString("")){
         toJsonValue(QString("name"), name, obj, QString("QString"));
     }
     if(ranges->size() > 0){
         toJsonArray((QList<void*>*)ranges, obj, "ranges", "SWGRangeFloat");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGSoapySDRFrequencySetting::cleanup ()
Definition at line 50 of file SWGSoapySDRFrequencySetting.cpp.
References name, and ranges.
Referenced by ~SWGSoapySDRFrequencySetting().
{
     if(name != nullptr) {
         delete name;
     }
     if(ranges != nullptr) {
         auto arr = ranges;
         for(auto o: *arr) {
             delete o;
         }
         delete ranges;
     }
 }
fromJson()
SWGSoapySDRFrequencySetting * SWGSDRangel::SWGSoapySDRFrequencySetting::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 64 of file SWGSoapySDRFrequencySetting.cpp.
References fromJsonObject().
Referenced by SWGSoapySDRFrequencySetting().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGSoapySDRFrequencySetting::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 73 of file SWGSoapySDRFrequencySetting.cpp.
References name, ranges, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&name, pJson["name"], "QString", "QString");
     ::SWGSDRangel::setValue(&ranges, pJson["ranges"], "QList", "SWGRangeFloat");
 }
getName()
QString * SWGSDRangel::SWGSoapySDRFrequencySetting::getName ()
Definition at line 105 of file SWGSoapySDRFrequencySetting.cpp.
References name.
{
     return name;
 }
getRanges()
QList< SWGRangeFloat * > * SWGSDRangel::SWGSoapySDRFrequencySetting::getRanges ()
Definition at line 115 of file SWGSoapySDRFrequencySetting.cpp.
References ranges.
{
     return ranges;
 }
init()
void SWGSDRangel::SWGSoapySDRFrequencySetting::init ()
Definition at line 42 of file SWGSoapySDRFrequencySetting.cpp.
References m_name_isSet, m_ranges_isSet, name, and ranges.
Referenced by SWGSoapySDRFrequencySetting().
{
     name = new QString("");
     m_name_isSet = false;
     ranges = new QList<SWGRangeFloat*>();
     m_ranges_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGSoapySDRFrequencySetting::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 126 of file SWGSoapySDRFrequencySetting.cpp.
References name, and ranges.
{
     bool isObjectUpdated = false;
     do{
         if(name != nullptr && *name != QString("")){ isObjectUpdated = true; break;}
         if(ranges->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setName()
void SWGSDRangel::SWGSoapySDRFrequencySetting::setName (QString * name)
Definition at line 109 of file SWGSoapySDRFrequencySetting.cpp.
References m_name_isSet, and name.
{
     this->name = name;
     this->m_name_isSet = true;
 }
setRanges()
void SWGSDRangel::SWGSoapySDRFrequencySetting::setRanges (QList< SWGRangeFloat *> * ranges)
Definition at line 119 of file SWGSoapySDRFrequencySetting.cpp.
References m_ranges_isSet, and ranges.
{
     this->ranges = ranges;
     this->m_ranges_isSet = true;
 }
Member Data Documentation
m_name_isSet
bool SWGSDRangel::SWGSoapySDRFrequencySetting::m_name_isSet private
Definition at line 58 of file SWGSoapySDRFrequencySetting.h.
Referenced by init(), setName(), and SWGSoapySDRFrequencySetting().
m_ranges_isSet
bool SWGSDRangel::SWGSoapySDRFrequencySetting::m_ranges_isSet private
Definition at line 61 of file SWGSoapySDRFrequencySetting.h.
Referenced by init(), setRanges(), and SWGSoapySDRFrequencySetting().
name
QString* SWGSDRangel::SWGSoapySDRFrequencySetting::name private
Definition at line 57 of file SWGSoapySDRFrequencySetting.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getName(), init(), isSet(), setName(), and SWGSoapySDRFrequencySetting().
ranges
QList<SWGRangeFloat*>* SWGSDRangel::SWGSoapySDRFrequencySetting::ranges private
Definition at line 60 of file SWGSoapySDRFrequencySetting.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getRanges(), init(), isSet(), setRanges(), and SWGSoapySDRFrequencySetting().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGSoapySDRFrequencySetting.h
swagger/sdrangel/code/qt5/client/SWGSoapySDRFrequencySetting.cpp