SDRAngel: SWGSDRangel::SWGChannelsDetail Class Reference
SWGSDRangel::SWGChannelsDetail Class Reference
#include <SWGChannelsDetail.h>
Public Member Functions
SWGChannelsDetail ()
SWGChannelsDetail (QString *json)
virtual ~SWGChannelsDetail ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGChannelsDetail * fromJson (QString &jsonString) override
qint32 getChannelcount ()
void setChannelcount (qint32 channelcount)
QList< SWGChannel * > * getChannels ()
void setChannels (QList< SWGChannel *> *channels)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 channelcount
bool m_channelcount_isSet
QList< SWGChannel * > * channels
bool m_channels_isSet
Detailed Description
Definition at line 33 of file SWGChannelsDetail.h.
Constructor & Destructor Documentation
SWGChannelsDetail() [1/2]
SWGSDRangel::SWGChannelsDetail::SWGChannelsDetail ()
Definition at line 30 of file SWGChannelsDetail.cpp.
References channelcount, channels, m_channelcount_isSet, and m_channels_isSet.
{
     channelcount = 0;
     m_channelcount_isSet = false;
     channels = nullptr;
     m_channels_isSet = false;
 }
SWGChannelsDetail() [2/2]
SWGSDRangel::SWGChannelsDetail::SWGChannelsDetail (QString * json)
Definition at line 25 of file SWGChannelsDetail.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGChannelsDetail()
SWGSDRangel::SWGChannelsDetail::~SWGChannelsDetail () virtual
Definition at line 37 of file SWGChannelsDetail.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGChannelsDetail::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 79 of file SWGChannelsDetail.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::devicesetChannelsReportService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGChannelsDetail::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 90 of file SWGChannelsDetail.cpp.
References channelcount, channels, m_channelcount_isSet, and SWGSDRangel::toJsonArray().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_channelcount_isSet){
         obj->insert("channelcount", QJsonValue(channelcount));
     }
     if(channels->size() > 0){
         toJsonArray((QList<void*>*)channels, obj, "channels", "SWGChannel");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGChannelsDetail::cleanup ()
Definition at line 50 of file SWGChannelsDetail.cpp.
References channels.
Referenced by ~SWGChannelsDetail().
{
     if(channels != nullptr) {
         auto arr = channels;
         for(auto o: *arr) {
             delete o;
         }
         delete channels;
     }
 }
fromJson()
SWGChannelsDetail * SWGSDRangel::SWGChannelsDetail::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 62 of file SWGChannelsDetail.cpp.
References fromJsonObject().
Referenced by SWGChannelsDetail().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGChannelsDetail::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 71 of file SWGChannelsDetail.cpp.
References channelcount, channels, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&channelcount, pJson["channelcount"], "qint32", "");
     ::SWGSDRangel::setValue(&channels, pJson["channels"], "QList", "SWGChannel");
 }
getChannelcount()
qint32 SWGSDRangel::SWGChannelsDetail::getChannelcount ()
Definition at line 103 of file SWGChannelsDetail.cpp.
References channelcount.
Referenced by WebAPIAdapterGUI::getChannelsDetail(), and WebAPIAdapterSrv::getChannelsDetail().
{
     return channelcount;
 }
getChannels()
QList< SWGChannel * > * SWGSDRangel::SWGChannelsDetail::getChannels ()
Definition at line 113 of file SWGChannelsDetail.cpp.
References channels.
Referenced by WebAPIAdapterGUI::getChannelsDetail(), and WebAPIAdapterSrv::getChannelsDetail().
{
     return channels;
 }
init()
void SWGSDRangel::SWGChannelsDetail::init ()
Definition at line 42 of file SWGChannelsDetail.cpp.
References channelcount, channels, m_channelcount_isSet, and m_channels_isSet.
Referenced by WebAPIAdapterGUI::getChannelsDetail(), WebAPIAdapterSrv::getChannelsDetail(), and SWGChannelsDetail().
{
     channelcount = 0;
     m_channelcount_isSet = false;
     channels = new QList<SWGChannel*>();
     m_channels_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGChannelsDetail::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 124 of file SWGChannelsDetail.cpp.
References channels, and m_channelcount_isSet.
{
     bool isObjectUpdated = false;
     do{
         if(m_channelcount_isSet){ isObjectUpdated = true; break;}
         if(channels->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setChannelcount()
void SWGSDRangel::SWGChannelsDetail::setChannelcount (qint32 channelcount)
Definition at line 107 of file SWGChannelsDetail.cpp.
References channelcount, and m_channelcount_isSet.
Referenced by WebAPIAdapterGUI::getChannelsDetail(), and WebAPIAdapterSrv::getChannelsDetail().
{
     this->channelcount = channelcount;
     this->m_channelcount_isSet = true;
 }
setChannels()
void SWGSDRangel::SWGChannelsDetail::setChannels (QList< SWGChannel *> * channels)
Definition at line 117 of file SWGChannelsDetail.cpp.
References channels, and m_channels_isSet.
{
     this->channels = channels;
     this->m_channels_isSet = true;
 }
Member Data Documentation
channelcount
qint32 SWGSDRangel::SWGChannelsDetail::channelcount private
Definition at line 56 of file SWGChannelsDetail.h.
Referenced by asJsonObject(), fromJsonObject(), getChannelcount(), init(), setChannelcount(), and SWGChannelsDetail().
channels
QList<SWGChannel*>* SWGSDRangel::SWGChannelsDetail::channels private
Definition at line 59 of file SWGChannelsDetail.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getChannels(), init(), isSet(), setChannels(), and SWGChannelsDetail().
m_channelcount_isSet
bool SWGSDRangel::SWGChannelsDetail::m_channelcount_isSet private
Definition at line 57 of file SWGChannelsDetail.h.
Referenced by asJsonObject(), init(), isSet(), setChannelcount(), and SWGChannelsDetail().
m_channels_isSet
bool SWGSDRangel::SWGChannelsDetail::m_channels_isSet private
Definition at line 60 of file SWGChannelsDetail.h.
Referenced by init(), setChannels(), and SWGChannelsDetail().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGChannelsDetail.h
swagger/sdrangel/code/qt5/client/SWGChannelsDetail.cpp