SDRAngel: XTRXOutputPlugin Class Reference
XTRXOutputPlugin Class Reference
#include <xtrxoutputplugin.h>
Public Member Functions
XTRXOutputPlugin (QObject *parent=0)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "XTRX"
static const QString m_deviceTypeID = XTRXOUTPUT_DEVICE_TYPE_ID
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 28 of file xtrxoutputplugin.h.
Constructor & Destructor Documentation
XTRXOutputPlugin()
XTRXOutputPlugin::XTRXOutputPlugin (QObject * parent = 0) explicit
Definition at line 47 of file xtrxoutputplugin.cpp.
                                                   :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSinkPluginInstance()
DeviceSampleSink * XTRXOutputPlugin::createSampleSinkPluginInstance (const QString & sinkId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 118 of file xtrxoutputplugin.cpp.
References m_deviceTypeID.
 {
     if(sinkId == m_deviceTypeID)
     {
         XTRXOutput* output = new XTRXOutput(deviceAPI);
         return output;
     }
     else
     {
         return 0;
     }
 }
createSampleSinkPluginInstanceGUI()
PluginInstanceGUI * XTRXOutputPlugin::createSampleSinkPluginInstanceGUI (const QString & sinkId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 100 of file xtrxoutputplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSinks().
 {
     if(sinkId == m_deviceTypeID)
     {
         XTRXOutputGUI* gui = new XTRXOutputGUI(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSinks()
PluginInterface::SamplingDevices XTRXOutputPlugin::enumSampleSinks () virtual
Reimplemented from PluginInterface.
Definition at line 62 of file xtrxoutputplugin.cpp.
References arg(), createSampleSinkPluginInstanceGUI(), i, m_deviceTypeID, m_hardwareID, DeviceXTRXParams::m_nbTxChannels, PluginInterface::SamplingDevice::PhysicalDevice, and PluginInterface::SamplingDevice::StreamSingleTx.
 {
     SamplingDevices result;
     xtrx_device_info_t devs[32];
     int res = xtrx_discovery(devs, 32);
     int i;
     for (i = 0; i < res; i++) {
         DeviceXTRXParams XTRXParams;
         for (unsigned int j = 0; j < XTRXParams.m_nbTxChannels; j++)
         {
             qDebug("XTRXInputPlugin::enumSampleSinks: device #%d channel %u: %s", i, j, devs[i].uniqname);
             QString displayedName(QString("XTRX[%1:%2] %3").arg(i).arg(j).arg(devs[i].uniqname));
             result.append(SamplingDevice(displayedName,
                                          m_hardwareID,
                                          m_deviceTypeID,
                                          QString(devs[i].uniqname),
                                          i,
                                          PluginInterface::SamplingDevice::PhysicalDevice,
                                          PluginInterface::SamplingDevice::StreamSingleTx,
                                          XTRXParams.m_nbTxChannels,
                                          j));
         }
     }
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & XTRXOutputPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 52 of file xtrxoutputplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void XTRXOutputPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 57 of file xtrxoutputplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSink().
 {
     pluginAPI->registerSampleSink(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString XTRXOutputPlugin::m_deviceTypeID = XTRXOUTPUT_DEVICE_TYPE_ID static
Definition at line 47 of file xtrxoutputplugin.h.
Referenced by createSampleSinkPluginInstance(), createSampleSinkPluginInstanceGUI(), enumSampleSinks(), and initPlugin().
m_hardwareID
const QString XTRXOutputPlugin::m_hardwareID = "XTRX" static
Definition at line 46 of file xtrxoutputplugin.h.
Referenced by enumSampleSinks().
m_pluginDescriptor
const PluginDescriptor XTRXOutputPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("XTRX Output"),
    QString("4.5.4"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 50 of file xtrxoutputplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesink/xtrxoutput/xtrxoutputplugin.h
plugins/samplesink/xtrxoutput/xtrxoutputplugin.cpp