SDRAngel: LoRaDemodGUI Class Reference
LoRaDemodGUI Class Reference
#include <lorademodgui.h>
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static LoRaDemodGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceAPI, BasebandSampleSink *rxChannel)
Private Slots
void viewChanged ()
void on_BW_valueChanged (int value)
void on_Spread_valueChanged (int value)
void onWidgetRolled (QWidget *widget, bool rollDown)
Private Member Functions
LoRaDemodGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *parent=0)
virtual ~LoRaDemodGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
Private Attributes
Ui::LoRaDemodGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
LoRaDemodSettings m_settings
bool m_doApplySettings
LoRaDemod * m_LoRaDemod
SpectrumVis * m_spectrumVis
MessageQueue m_inputMessageQueue
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 21 of file lorademodgui.h.
Constructor & Destructor Documentation
LoRaDemodGUI()
LoRaDemodGUI::LoRaDemodGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * parent = 0) explicit private
Definition at line 111 of file lorademodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), displaySettings(), BasebandSampleSink::getInputMessageQueue(), LoRaDemod::m_channelIdURI, m_channelMarker, m_deviceUISet, m_LoRaDemod, m_settings, m_spectrumVis, onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), SDR_RX_SCALEF, LoRaDemodSettings::setChannelMarker(), ChannelMarker::setMovable(), LoRaDemodSettings::setSpectrumGUI(), LoRaDemod::setSpectrumSink(), ChannelMarker::setVisible(), ui, viewChanged(), and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                          :
     RollupWidget(parent),
     ui(new Ui::LoRaDemodGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_doApplySettings(true)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     m_spectrumVis = new SpectrumVis(SDR_RX_SCALEF, ui->glSpectrum);
     m_LoRaDemod = (LoRaDemod*) rxChannel; //new LoRaDemod(m_deviceUISet->m_deviceSourceAPI);
     m_LoRaDemod->setSpectrumSink(m_spectrumVis);
     ui->glSpectrum->setCenterFrequency(16000);
     ui->glSpectrum->setSampleRate(32000);
     ui->glSpectrum->setDisplayWaterfall(true);
     ui->glSpectrum->setDisplayMaxHold(true);
     m_channelMarker.setMovable(false);
     m_channelMarker.setVisible(true);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(viewChanged()));
     m_deviceUISet->registerRxChannelInstance(LoRaDemod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     ui->spectrumGUI->setBuddies(m_spectrumVis->getInputMessageQueue(), m_spectrumVis, ui->glSpectrum);
     m_settings.setChannelMarker(&m_channelMarker);
     m_settings.setSpectrumGUI(ui->spectrumGUI);
     displaySettings();
     applySettings(true);
 }
~LoRaDemodGUI()
LoRaDemodGUI::~LoRaDemodGUI () private virtual
Definition at line 150 of file lorademodgui.cpp.
References m_deviceUISet, m_LoRaDemod, m_spectrumVis, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_LoRaDemod; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete m_spectrumVis;
     delete ui;
 }
Member Function Documentation
applySettings()
void LoRaDemodGUI::applySettings (bool force = false) private
Definition at line 163 of file lorademodgui.cpp.
References LoRaDemodSettings::bandwidths, LoRaDemod::MsgConfigureLoRaDemod::create(), LoRaDemod::MsgConfigureChannelizer::create(), ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasebandSampleSink::getInputMessageQueue(), LoRaDemodSettings::m_bandwidthIndex, m_channelMarker, m_doApplySettings, m_LoRaDemod, m_settings, MessageQueue::push(), and RollupWidget::setTitleColor().
Referenced by deserialize(), LoRaDemodGUI(), on_BW_valueChanged(), resetToDefaults(), setCenterFrequency(), and viewChanged().
 {
     if (m_doApplySettings)
     {
         setTitleColor(m_channelMarker.getColor());
         LoRaDemod::MsgConfigureChannelizer* channelConfigMsg = LoRaDemod::MsgConfigureChannelizer::create(
                 LoRaDemodSettings::bandwidths[m_settings.m_bandwidthIndex],
                 m_channelMarker.getCenterFrequency());
         m_LoRaDemod->getInputMessageQueue()->push(channelConfigMsg);
         LoRaDemod::MsgConfigureLoRaDemod* message = LoRaDemod::MsgConfigureLoRaDemod::create( m_settings, force);
         m_LoRaDemod->getInputMessageQueue()->push(message);
     }
 }
blockApplySettings()
void LoRaDemodGUI::blockApplySettings (bool block) private
Definition at line 158 of file lorademodgui.cpp.
References m_doApplySettings.
Referenced by displaySettings().
 {
     m_doApplySettings = !block;
 }
create()
LoRaDemodGUI * LoRaDemodGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceAPI, BasebandSampleSink * rxChannel) static
Definition at line 17 of file lorademodgui.cpp.
References LoRaDemodGUI().
Referenced by LoRaPlugin::createRxChannelGUI().
 {
     LoRaDemodGUI* gui = new LoRaDemodGUI(pluginAPI, deviceUISet, rxChannel);
     return gui;
 }
deserialize()
bool LoRaDemodGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 60 of file lorademodgui.cpp.
References applySettings(), LoRaDemodSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void LoRaDemodGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 23 of file lorademodgui.cpp.
 {
     delete this;
 }
displaySettings()
void LoRaDemodGUI::displaySettings () private
Definition at line 179 of file lorademodgui.cpp.
References arg(), LoRaDemodSettings::bandwidths, blockApplySettings(), LoRaDemodSettings::m_bandwidthIndex, m_channelMarker, LoRaDemodSettings::m_rgbColor, m_settings, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), RollupWidget::setTitleColor(), and ui.
Referenced by deserialize(), LoRaDemodGUI(), and resetToDefaults().
 {
     int thisBW = LoRaDemodSettings::bandwidths[m_settings.m_bandwidthIndex];
     m_channelMarker.blockSignals(true);
     m_channelMarker.setBandwidth(thisBW);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     setTitleColor(m_settings.m_rgbColor);
     m_channelMarker.blockSignals(false);
     blockApplySettings(true);
     ui->BWText->setText(QString("%1 Hz").arg(thisBW));
     ui->BW->setValue(m_settings.m_bandwidthIndex);
     blockApplySettings(false);
 }
getCenterFrequency()
qint64 LoRaDemodGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 38 of file lorademodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
{
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* LoRaDemodGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 36 of file lorademodgui.h.
 { return &m_inputMessageQueue; }
getName()
QString LoRaDemodGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 33 of file lorademodgui.cpp.
 {
     return objectName();
 }
handleMessage()
bool LoRaDemodGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 72 of file lorademodgui.cpp.
 {
     (void) message;
     return false;
 }
on_BW_valueChanged
void LoRaDemodGUI::on_BW_valueChanged (int value) private slot
Definition at line 83 of file lorademodgui.cpp.
References applySettings(), arg(), LoRaDemodSettings::bandwidths, LoRaDemodSettings::m_bandwidthIndex, m_channelMarker, m_settings, LoRaDemodSettings::nb_bandwidths, ChannelMarker::setBandwidth(), and ui.
 {
     if (value < 0) {
         m_settings.m_bandwidthIndex = 0;
     } else if (value < LoRaDemodSettings::nb_bandwidths) {
         m_settings.m_bandwidthIndex = value;
     } else {
         m_settings.m_bandwidthIndex = LoRaDemodSettings::nb_bandwidths - 1;
     }
     int thisBW = LoRaDemodSettings::bandwidths[value];
     ui->BWText->setText(QString("%1 Hz").arg(thisBW));
     m_channelMarker.setBandwidth(thisBW);
     applySettings();
 }
on_Spread_valueChanged
void LoRaDemodGUI::on_Spread_valueChanged (int value) private slot
Definition at line 100 of file lorademodgui.cpp.
 {
     (void) value;
 }
onWidgetRolled
void LoRaDemodGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 105 of file lorademodgui.cpp.
Referenced by LoRaDemodGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void LoRaDemodGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 48 of file lorademodgui.cpp.
References applySettings(), displaySettings(), m_settings, and LoRaDemodSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
serialize()
QByteArray LoRaDemodGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 55 of file lorademodgui.cpp.
References m_settings, and LoRaDemodSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void LoRaDemodGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 42 of file lorademodgui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     applySettings();
 }
setName()
void LoRaDemodGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 28 of file lorademodgui.cpp.
 {
     setObjectName(name);
 }
viewChanged
void LoRaDemodGUI::viewChanged () private slot
Definition at line 78 of file lorademodgui.cpp.
References applySettings().
Referenced by LoRaDemodGUI().
 {
     applySettings();
 }
Member Data Documentation
m_channelMarker
ChannelMarker LoRaDemodGUI::m_channelMarker private
Definition at line 49 of file lorademodgui.h.
Referenced by applySettings(), displaySettings(), getCenterFrequency(), LoRaDemodGUI(), on_BW_valueChanged(), and setCenterFrequency().
m_deviceUISet
DeviceUISet* LoRaDemodGUI::m_deviceUISet private
Definition at line 48 of file lorademodgui.h.
Referenced by LoRaDemodGUI(), and ~LoRaDemodGUI().
m_doApplySettings
bool LoRaDemodGUI::m_doApplySettings private
Definition at line 51 of file lorademodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_inputMessageQueue
MessageQueue LoRaDemodGUI::m_inputMessageQueue private
Definition at line 55 of file lorademodgui.h.
m_LoRaDemod
LoRaDemod* LoRaDemodGUI::m_LoRaDemod private
Definition at line 53 of file lorademodgui.h.
Referenced by applySettings(), LoRaDemodGUI(), and ~LoRaDemodGUI().
m_pluginAPI
PluginAPI* LoRaDemodGUI::m_pluginAPI private
Definition at line 47 of file lorademodgui.h.
m_settings
LoRaDemodSettings LoRaDemodGUI::m_settings private
Definition at line 50 of file lorademodgui.h.
Referenced by applySettings(), deserialize(), displaySettings(), LoRaDemodGUI(), on_BW_valueChanged(), resetToDefaults(), and serialize().
m_spectrumVis
SpectrumVis* LoRaDemodGUI::m_spectrumVis private
Definition at line 54 of file lorademodgui.h.
Referenced by LoRaDemodGUI(), and ~LoRaDemodGUI().
ui
Ui::LoRaDemodGUI* LoRaDemodGUI::ui private
Definition at line 46 of file lorademodgui.h.
Referenced by displaySettings(), LoRaDemodGUI(), on_BW_valueChanged(), and ~LoRaDemodGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/demodlora/lorademodgui.h
plugins/channelrx/demodlora/lorademodgui.cpp