SDRAngel: ThreadedBasebandSampleSink Class Reference
ThreadedBasebandSampleSink Class Reference
#include <threadedbasebandsamplesink.h>
Inherits QObject.
Public Member Functions
ThreadedBasebandSampleSink (BasebandSampleSink *sampleSink, QObject *parent=0)
~ThreadedBasebandSampleSink ()
const BasebandSampleSink * getSink () const
void start ()
this thread start()
void stop ()
this thread exit() and wait()
bool handleSinkMessage (const Message &cmd)
Send message to sink synchronously.
void feed (SampleVector::const_iterator begin, SampleVector::const_iterator end, bool positiveOnly)
Feed sink with samples.
QString getSampleSinkObjectName () const
const QThread * getThread () const
Protected Attributes
QThread * m_thread
The thead object.
ThreadedBasebandSampleSinkFifo * m_threadedBasebandSampleSinkFifo
BasebandSampleSink * m_basebandSampleSink
Detailed Description
This class is a wrapper for SampleSink that runs the SampleSink object in its own thread
Definition at line 54 of file threadedbasebandsamplesink.h.
Constructor & Destructor Documentation
ThreadedBasebandSampleSink()
ThreadedBasebandSampleSink::ThreadedBasebandSampleSink (BasebandSampleSink * sampleSink, QObject * parent = 0)
Definition at line 66 of file threadedbasebandsamplesink.cpp.
References BasebandSampleSink::MsgThreadedSink::create(), BasebandSampleSink::handleMessage(), m_basebandSampleSink, m_thread, and m_threadedBasebandSampleSinkFifo.
                                                                                                       :
     m_basebandSampleSink(sampleSink)
 {
     QString name = "ThreadedBasebandSampleSink(" + m_basebandSampleSink->objectName() + ")";
     setObjectName(name);
     qDebug() << "ThreadedBasebandSampleSink::ThreadedBasebandSampleSink: " << name;
     m_thread = new QThread(parent);
     m_threadedBasebandSampleSinkFifo = new ThreadedBasebandSampleSinkFifo(m_basebandSampleSink);
     //moveToThread(m_thread); // FIXME: Fixed? the intermediate FIFO should be handled within the sink. Define a new type of sink that is compatible with threading
     m_basebandSampleSink->moveToThread(m_thread);
     m_threadedBasebandSampleSinkFifo->moveToThread(m_thread);
     BasebandSampleSink::MsgThreadedSink *msg = BasebandSampleSink::MsgThreadedSink::create(m_thread); // inform of the new thread
     m_basebandSampleSink->handleMessage(*msg);
     delete msg;
     //m_sampleFifo.moveToThread(m_thread);
     //connect(&m_sampleFifo, SIGNAL(dataReady()), this, SLOT(handleData()));
     //m_sampleFifo.setSize(262144);
     qDebug() << "ThreadedBasebandSampleSink::ThreadedBasebandSampleSink: thread: " << thread() << " m_thread: " << m_thread;
 }
~ThreadedBasebandSampleSink()
ThreadedBasebandSampleSink::~ThreadedBasebandSampleSink ()
Definition at line 89 of file threadedbasebandsamplesink.cpp.
References m_thread, m_threadedBasebandSampleSinkFifo, and stop().
 {
     if (m_thread->isRunning()) {
         stop();
     }
     delete m_threadedBasebandSampleSinkFifo; // Valgrind memcheck
     delete m_thread;
 }
Member Function Documentation
feed()
void ThreadedBasebandSampleSink::feed (SampleVector::const_iterator begin, SampleVector::const_iterator end, bool positiveOnly)
Feed sink with samples.
Definition at line 114 of file threadedbasebandsamplesink.cpp.
References m_threadedBasebandSampleSinkFifo, and ThreadedBasebandSampleSinkFifo::writeToFifo().
 {
     (void) positiveOnly;
     //m_sampleSink->feed(begin, end, positiveOnly);
     //m_sampleFifo.write(begin, end);
     m_threadedBasebandSampleSinkFifo->writeToFifo(begin, end);
 }
getSampleSinkObjectName()
QString ThreadedBasebandSampleSink::getSampleSinkObjectName () const
Definition at line 127 of file threadedbasebandsamplesink.cpp.
References m_basebandSampleSink.
 {
     return m_basebandSampleSink->objectName();
 }
getSink()
const BasebandSampleSink* ThreadedBasebandSampleSink::getSink () const inline
Definition at line 61 of file threadedbasebandsamplesink.h.
 { return m_basebandSampleSink; }
getThread()
const QThread* ThreadedBasebandSampleSink::getThread () const inline
Definition at line 70 of file threadedbasebandsamplesink.h.
 { return m_thread; }
handleSinkMessage()
bool ThreadedBasebandSampleSink::handleSinkMessage (const Message & cmd)
Send message to sink synchronously.
Definition at line 122 of file threadedbasebandsamplesink.cpp.
References BasebandSampleSink::handleMessage(), and m_basebandSampleSink.
Referenced by DSPDeviceSourceEngine::handleSynchronousMessages(), and DSPDeviceMIMOEngine::handleSynchronousMessages().
 {
     return m_basebandSampleSink->handleMessage(cmd);
 }
start()
void ThreadedBasebandSampleSink::start ()
this thread start()
Definition at line 99 of file threadedbasebandsamplesink.cpp.
References m_basebandSampleSink, m_thread, and BasebandSampleSink::start().
Referenced by DSPDeviceSourceEngine::handleSynchronousMessages(), and DSPDeviceMIMOEngine::handleSynchronousMessages().
 {
     qDebug() << "ThreadedBasebandSampleSink::start";
     m_thread->start();
     m_basebandSampleSink->start();
 }
stop()
void ThreadedBasebandSampleSink::stop ()
this thread exit() and wait()
Definition at line 106 of file threadedbasebandsamplesink.cpp.
References m_basebandSampleSink, m_thread, and BasebandSampleSink::stop().
Referenced by DSPDeviceSourceEngine::handleSynchronousMessages(), DSPDeviceMIMOEngine::handleSynchronousMessages(), and ~ThreadedBasebandSampleSink().
 {
     qDebug() << "ThreadedBasebandSampleSink::stop";
     m_basebandSampleSink->stop();
     m_thread->exit();
     m_thread->wait();
 }
Member Data Documentation
m_basebandSampleSink
BasebandSampleSink* ThreadedBasebandSampleSink::m_basebandSampleSink protected
Definition at line 76 of file threadedbasebandsamplesink.h.
Referenced by getSampleSinkObjectName(), handleSinkMessage(), start(), stop(), and ThreadedBasebandSampleSink().
m_thread
QThread* ThreadedBasebandSampleSink::m_thread protected
The thead object.
Definition at line 74 of file threadedbasebandsamplesink.h.
Referenced by start(), stop(), ThreadedBasebandSampleSink(), and ~ThreadedBasebandSampleSink().
m_threadedBasebandSampleSinkFifo
ThreadedBasebandSampleSinkFifo* ThreadedBasebandSampleSink::m_threadedBasebandSampleSinkFifo protected
Definition at line 75 of file threadedbasebandsamplesink.h.
Referenced by feed(), ThreadedBasebandSampleSink(), and ~ThreadedBasebandSampleSink().
The documentation for this class was generated from the following files:
sdrbase/dsp/threadedbasebandsamplesink.h
sdrbase/dsp/threadedbasebandsamplesink.cpp