SDRAngel: Fixed< IntType, IntBits > Class Template Reference
Fixed< IntType, IntBits > Class Template Reference
#include <fixed.h>
Classes
struct internal
Public Member Functions
Fixed ()
Fixed (internal, IntType nVal)
Fixed (int64_t nVal)
Fixed (int nVal)
Fixed (short nVal)
Fixed (uint64_t nVal)
Fixed (unsigned int nVal)
Fixed (unsigned short nVal)
Fixed (double nVal)
Fixed (float nVal)
template<typename T >
Fixed & operator= (T other)
Fixed & operator= (Fixed const &other)
operator bool () const
operator double () const
IntType as_internal () const
float as_float () const
double as_double () const
int64_t as_long () const
int64_t as_int64 () const
int as_int () const
uint64_t as_unsigned_long () const
uint64_t as_unsigned_int64 () const
unsigned int as_unsigned_int () const
short as_short () const
unsigned short as_unsigned_short () const
Fixed operator++ ()
Fixed operator-- ()
Fixed floor () const
Fixed ceil () const
Fixed sqrt () const
Fixed exp () const
Fixed log () const
Fixed & operator%= (Fixed const &other)
Fixed & operator*= (Fixed const &val)
Fixed & operator/= (Fixed const &val)
Fixed & operator-= (Fixed const &val)
Fixed & operator+= (Fixed const &val)
Fixed & operator*= (double val)
Fixed & operator*= (float val)
Fixed & operator*= (int64_t val)
Fixed & operator*= (int val)
Fixed & operator*= (short val)
Fixed & operator*= (char val)
Fixed & operator*= (uint64_t val)
Fixed & operator*= (unsigned int val)
Fixed & operator*= (unsigned short val)
Fixed & operator*= (unsigned char val)
Fixed & operator/= (double val)
Fixed & operator/= (float val)
Fixed & operator/= (int64_t val)
Fixed & operator/= (int val)
Fixed & operator/= (short val)
Fixed & operator/= (char val)
Fixed & operator/= (uint64_t val)
Fixed & operator/= (unsigned int val)
Fixed & operator/= (unsigned short val)
Fixed & operator/= (unsigned char val)
bool operator! () const
Fixed modf (Fixed *integral_part) const
Fixed atan () const
Fixed sin () const
Fixed cos () const
Fixed tan () const
Fixed operator- () const
Fixed abs () const
Static Public Member Functions
static void sin_cos (Fixed const &theta, Fixed *s, Fixed *c)
static void to_polar (Fixed const &x, Fixed const &y, Fixed *r, Fixed *theta)
Static Public Attributes
static const Fixed fixed_max
static const Fixed fixed_one
static const Fixed fixed_zero
static const Fixed fixed_half
static const Fixed fixed_pi
static const Fixed fixed_two_pi
static const Fixed fixed_half_pi
static const Fixed fixed_quarter_pi
Static Private Member Functions
static int64_t scale_cordic_result (int64_t a)
static int64_t right_shift (int64_t val, int shift)
static void perform_cordic_rotation (int64_t &px, int64_t &py, int64_t theta)
static void perform_cordic_polarization (int64_t &argx, int64_t &argy)
Private Attributes
IntType m_nVal
Friends
bool operator== (Fixed const &lhs, Fixed const &rhs)
bool operator!= (Fixed const &lhs, Fixed const &rhs)
bool operator< (Fixed const &lhs, Fixed const &rhs)
bool operator> (Fixed const &lhs, Fixed const &rhs)
bool operator<= (Fixed const &lhs, Fixed const &rhs)
bool operator>= (Fixed const &lhs, Fixed const &rhs)
Detailed Description
template<typename IntType, uint32_t IntBits>
class Fixed< IntType, IntBits >
Definition at line 42 of file fixed.h.
Constructor & Destructor Documentation
Fixed() [1/10]
template<typename IntType, uint32_t IntBits> Fixed< IntType, IntBits >::Fixed () inline
Definition at line 65 of file fixed.h.
Referenced by Fixed< IntType, IntBits >::operator*=(), Fixed< IntType, IntBits >::operator-(), Fixed< IntType, IntBits >::operator/=(), and Fixed< IntType, IntBits >::operator=().
            :
         m_nVal(0)
     {}
Fixed() [2/10]
template<typename IntType, uint32_t IntBits> Fixed< IntType, IntBits >::Fixed (internal , IntType nVal) inline
Definition at line 69 of file fixed.h.
                                  :
         m_nVal(nVal)
     {}
Fixed() [3/10]
template<typename IntType, uint32_t IntBits> Fixed< IntType, IntBits >::Fixed (int64_t nVal) inline
Definition at line 72 of file fixed.h.
                        :
         m_nVal(nVal << FixedTraits<IntBits>::fixed_resolution_shift)
     {}
Fixed() [4/10]
template<typename IntType, uint32_t IntBits> Fixed< IntType, IntBits >::Fixed (int nVal) inline
Definition at line 76 of file fixed.h.
                    :
         m_nVal(int64_t(nVal) << FixedTraits<IntBits>::fixed_resolution_shift)
     {}
Fixed() [5/10]
template<typename IntType, uint32_t IntBits> Fixed< IntType, IntBits >::Fixed (short nVal) inline
Definition at line 80 of file fixed.h.
                      :
         m_nVal(int64_t(nVal) << FixedTraits<IntBits>::fixed_resolution_shift)
     {}
Fixed() [6/10]
template<typename IntType, uint32_t IntBits> Fixed< IntType, IntBits >::Fixed (uint64_t nVal) inline
Definition at line 84 of file fixed.h.
                         :
         m_nVal(nVal << FixedTraits<IntBits>::fixed_resolution_shift)
     {}
Fixed() [7/10]
template<typename IntType, uint32_t IntBits> Fixed< IntType, IntBits >::Fixed (unsigned int nVal) inline
Definition at line 88 of file fixed.h.
                             :
         m_nVal(int64_t(nVal) << FixedTraits<IntBits>::fixed_resolution_shift)
     {}
Fixed() [8/10]
template<typename IntType, uint32_t IntBits> Fixed< IntType, IntBits >::Fixed (unsigned short nVal) inline
Definition at line 91 of file fixed.h.
                               :
         m_nVal(int64_t(nVal) << FixedTraits<IntBits>::fixed_resolution_shift)
     {}
Fixed() [9/10]
template<typename IntType, uint32_t IntBits> Fixed< IntType, IntBits >::Fixed (double nVal) inline
Definition at line 94 of file fixed.h.
                       :
         m_nVal(static_cast<int64_t>(nVal*static_cast<double>(FixedTraits<IntBits>::fixed_resolution)))
     {}
Fixed() [10/10]
template<typename IntType, uint32_t IntBits> Fixed< IntType, IntBits >::Fixed (float nVal) inline
Definition at line 97 of file fixed.h.
                      :
         m_nVal(static_cast<int64_t>(nVal*static_cast<float>(FixedTraits<IntBits>::fixed_resolution)))
     {}
Member Function Documentation
abs()
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > Fixed< IntType, IntBits >::abs () const inline
Definition at line 2383 of file fixed.h.
References Fixed< IntType, IntBits >::m_nVal.
Referenced by abs(), and Fixed< IntType, IntBits >::operator!().
 {
     return Fixed<IntType, IntBits>(Fixed<IntType, IntBits>::internal(), m_nVal < 0 ? -m_nVal : m_nVal);
 }
as_double()
template<typename IntType, uint32_t IntBits> double Fixed< IntType, IntBits >::as_double () const inline
Definition at line 164 of file fixed.h.
Referenced by Fixed< IntType, IntBits >::operator double().
     {
         return m_nVal / (double) FixedTraits<IntBits>::fixed_resolution;
     }
as_float()
template<typename IntType, uint32_t IntBits> float Fixed< IntType, IntBits >::as_float () const inline
Definition at line 159 of file fixed.h.
     {
         return m_nVal / (float) FixedTraits<IntBits>::fixed_resolution;
     }
as_int()
template<typename IntType, uint32_t IntBits> int Fixed< IntType, IntBits >::as_int () const inline
Definition at line 178 of file fixed.h.
     {
         return (int) (m_nVal / FixedTraits<IntBits>::fixed_resolution);
     }
as_int64()
template<typename IntType, uint32_t IntBits> int64_t Fixed< IntType, IntBits >::as_int64 () const inline
Definition at line 173 of file fixed.h.
     {
         return m_nVal / FixedTraits<IntBits>::fixed_resolution;
     }
as_internal()
template<typename IntType, uint32_t IntBits> IntType Fixed< IntType, IntBits >::as_internal () const inline
Definition at line 154 of file fixed.h.
References Fixed< IntType, IntBits >::m_nVal.
Referenced by DSPDeviceSourceEngine::iqCorrections(), and DSPDeviceMIMOEngine::iqCorrections().
     {
         return m_nVal;
     }
as_long()
template<typename IntType, uint32_t IntBits> int64_t Fixed< IntType, IntBits >::as_long () const inline
Definition at line 169 of file fixed.h.
     {
         return (int64_t) (m_nVal / FixedTraits<IntBits>::fixed_resolution);
     }
as_short()
template<typename IntType, uint32_t IntBits> short Fixed< IntType, IntBits >::as_short () const inline
Definition at line 197 of file fixed.h.
     {
         return (short) (m_nVal / FixedTraits<IntBits>::fixed_resolution);
     }
as_unsigned_int()
template<typename IntType, uint32_t IntBits> unsigned int Fixed< IntType, IntBits >::as_unsigned_int () const inline
Definition at line 192 of file fixed.h.
     {
         return (unsigned int) (m_nVal / FixedTraits<IntBits>::fixed_resolution);
     }
as_unsigned_int64()
template<typename IntType, uint32_t IntBits> uint64_t Fixed< IntType, IntBits >::as_unsigned_int64 () const inline
Definition at line 187 of file fixed.h.
     {
         return (uint64_t) (m_nVal / FixedTraits<IntBits>::fixed_resolution);
     }
as_unsigned_long()
template<typename IntType, uint32_t IntBits> uint64_t Fixed< IntType, IntBits >::as_unsigned_long () const inline
Definition at line 183 of file fixed.h.
     {
         return (uint64_t) (m_nVal / FixedTraits<IntBits>::fixed_resolution);
     }
as_unsigned_short()
template<typename IntType, uint32_t IntBits> unsigned short Fixed< IntType, IntBits >::as_unsigned_short () const inline
Definition at line 202 of file fixed.h.
     {
         return (unsigned short) (m_nVal / FixedTraits<IntBits>::fixed_resolution);
     }
atan()
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > Fixed< IntType, IntBits >::atan () const
Definition at line 763 of file fixed.h.
References Fixed< IntType, IntBits >::to_polar().
Referenced by Fixed< IntType, IntBits >::operator!().
 {
     Fixed<IntType, IntBits> r, theta;
     to_polar(1, *this, &r, &theta);
     return theta;
 }
ceil()
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > Fixed< IntType, IntBits >::ceil () const inline
Definition at line 2325 of file fixed.h.
References Fixed< IntType, IntBits >::floor(), and Fixed< IntType, IntBits >::m_nVal.
Referenced by ceil(), and Fixed< IntType, IntBits >::operator--().
 {
     if (m_nVal % FixedTraits<IntBits>::fixed_resolution) {
         return floor()+1;
     } else {
         return *this;
     }
 }
cos()
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > Fixed< IntType, IntBits >::cos () const inline
Definition at line 2361 of file fixed.h.
References Fixed< IntType, IntBits >::sin_cos().
Referenced by cos(), and Fixed< IntType, IntBits >::operator!().
 {
     Fixed res;
     sin_cos(*this, 0, &res);
     return res;
 }
exp()
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > Fixed< IntType, IntBits >::exp () const
Definition at line 532 of file fixed.h.
References Fixed< IntType, IntBits >::fixed_max, and Fixed< IntType, IntBits >::m_nVal.
Referenced by exp(), and Fixed< IntType, IntBits >::operator--().
 {
     if (m_nVal >= FixedTraits<IntBits>::log_two_power_n_reversed[0])
     {
         return fixed_max;
     }
     if (m_nVal < -FixedTraits<IntBits>::log_two_power_n_reversed[63 - 2*FixedTraits<IntBits>::fixed_resolution_shift])
     {
         return Fixed<IntType, IntBits>(internal(), 0);
     }
     if (!m_nVal)
     {
         return Fixed<IntType, IntBits>(internal(), FixedTraits<IntBits>::fixed_resolution);
     }
     int64_t res = FixedTraits<IntBits>::fixed_resolution;
     if (m_nVal > 0)
     {
         int power = FixedTraits<IntBits>::max_power;
         int64_t const* log_entry = FixedTraits<IntBits>::log_two_power_n_reversed;
         int64_t temp=m_nVal;
         while (temp && power>(-(int)FixedTraits<IntBits>::fixed_resolution_shift))
         {
             while (!power || (temp<*log_entry))
             {
                 if (!power) {
                     log_entry = FixedTraits<IntBits>::log_one_plus_two_power_minus_n;
                 } else {
                     ++log_entry;
                 }
                 --power;
             }
             temp -= *log_entry;
             if (power < 0) {
                 res += (res >> (-power));
             } else {
                 res <<= power;
             }
         }
     }
     else
     {
         int power = FixedTraits<IntBits>::fixed_resolution_shift;
         int64_t const* log_entry = FixedTraits<IntBits>::log_two_power_n_reversed + (FixedTraits<IntBits>::max_power-power);
         int64_t temp=m_nVal;
         while (temp && (power > (-(int) FixedTraits<IntBits>::fixed_resolution_shift)))
         {
             while (!power || (temp > (-*log_entry)))
             {
                 if(!power) {
                     log_entry = FixedTraits<IntBits>::log_one_over_one_minus_two_power_minus_n;
                 } else {
                     ++log_entry;
                 }
                 --power;
             }
             temp += *log_entry;
             if (power <0 ) {
                 res -= (res >> (-power));
             } else {
                 res >>= power;
             }
         }
     }
     return Fixed<IntType, IntBits>(Fixed<IntType, IntBits>::internal(), res);
 }
floor()
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > Fixed< IntType, IntBits >::floor () const inline
Definition at line 2335 of file fixed.h.
References Fixed< IntType, IntBits >::m_nVal.
Referenced by Fixed< IntType, IntBits >::ceil(), floor(), and Fixed< IntType, IntBits >::operator--().
 {
     Fixed res(*this);
     int64_t const remainder = m_nVal % FixedTraits<IntBits>::fixed_resolution;
     if (remainder)
     {
         res.m_nVal -= remainder;
         if(m_nVal<0) {
             res-=1;
         }
     }
     return res;
 }
log()
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > Fixed< IntType, IntBits >::log () const
Definition at line 612 of file fixed.h.
References Fixed< IntType, IntBits >::fixed_max, Fixed< IntType, IntBits >::fixed_zero, Fixed< IntType, IntBits >::m_nVal, and Fixed< IntType, IntBits >::right_shift().
Referenced by log(), and Fixed< IntType, IntBits >::operator--().
 {
     if ( m_nVal <= 0) {
         return -fixed_max;
     }
     if (m_nVal == FixedTraits<IntBits>::fixed_resolution) {
         return fixed_zero;
     }
     uint64_t temp = m_nVal;
     int left_shift = 0;
     uint64_t const scale_position = 0x8000000000000000ULL;
     while (temp < scale_position)
     {
         ++left_shift;
         temp <<= 1;
     }
     int64_t res = (left_shift < FixedTraits<IntBits>::max_power) ?
             FixedTraits<IntBits>::log_two_power_n_reversed[left_shift] :
             -FixedTraits<IntBits>::log_two_power_n_reversed[2*FixedTraits<IntBits>::max_power - left_shift];
     unsigned int right_shift = 1;
     uint64_t shifted_temp = temp >> 1;
     while (temp && (right_shift < FixedTraits<IntBits>::fixed_resolution_shift))
     {
         while ((right_shift < FixedTraits<IntBits>::fixed_resolution_shift) && (temp < (shifted_temp + scale_position)))
         {
             shifted_temp >>= 1;
             ++right_shift;
         }
         temp -= shifted_temp;
         shifted_temp = temp >> right_shift;
         res += FixedTraits<IntBits>::log_one_over_one_minus_two_power_minus_n[right_shift-1];
     }
     return Fixed<IntType, IntBits>(Fixed<IntType, IntBits>::internal(), res);
 }
modf()
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > Fixed< IntType, IntBits >::modf (Fixed< IntType, IntBits > * integral_part) const inline
Definition at line 2389 of file fixed.h.
References Fixed< IntType, IntBits >::m_nVal.
Referenced by modf(), and Fixed< IntType, IntBits >::operator!().
 {
     int64_t fractional_part = m_nVal % FixedTraits<IntBits>::fixed_resolution;
     if ((m_nVal < 0) && (fractional_part > 0)) {
         fractional_part -= FixedTraits<IntBits>::fixed_resolution;
     }
     integral_part->m_nVal = m_nVal - fractional_part;
     return Fixed<IntType, IntBits>(Fixed<IntType, IntBits>::internal(), fractional_part);
 }
operator bool()
template<typename IntType, uint32_t IntBits> Fixed< IntType, IntBits >::operator bool () const inline
Definition at line 144 of file fixed.h.
     {
         return m_nVal ? true : false;
     }
operator double()
template<typename IntType, uint32_t IntBits> Fixed< IntType, IntBits >::operator double () const inline
Definition at line 149 of file fixed.h.
References Fixed< IntType, IntBits >::as_double().
     {
         return as_double();
     }
operator!()
template<typename IntType, uint32_t IntBits> bool Fixed< IntType, IntBits >::operator! () const inline
Definition at line 356 of file fixed.h.
References Fixed< IntType, IntBits >::abs(), Fixed< IntType, IntBits >::atan(), Fixed< IntType, IntBits >::cos(), Fixed< IntType, IntBits >::modf(), Fixed< IntType, IntBits >::operator-(), Fixed< IntType, IntBits >::sin(), Fixed< IntType, IntBits >::sin_cos(), Fixed< IntType, IntBits >::tan(), and Fixed< IntType, IntBits >::to_polar().
     {
         return m_nVal == 0;
     }
operator%=()
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > & Fixed< IntType, IntBits >::operator%= (Fixed< IntType, IntBits > const & other)
Definition at line 382 of file fixed.h.
References Fixed< IntType, IntBits >::m_nVal.
Referenced by Fixed< IntType, IntBits >::operator--().
 {
     m_nVal = m_nVal%other.m_nVal;
     return *this;
 }
operator*=() [1/11]
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > & Fixed< IntType, IntBits >::operator*= (Fixed< IntType, IntBits > const & val)
Definition at line 389 of file fixed.h.
References Fixed< IntType, IntBits >::m_nVal.
Referenced by Fixed< IntType, IntBits >::operator--().
 {
     bool const val_negative = val.m_nVal < 0;
     bool const this_negative = m_nVal < 0;
     bool const negate = val_negative ^ this_negative;
     uint64_t const other = val_negative ? -val.m_nVal : val.m_nVal;
     uint64_t const self = this_negative ? -m_nVal : m_nVal;
     if (uint64_t const self_upper = (self >> 32)) {
         m_nVal = (self_upper*other) << (32 - FixedTraits<IntBits>::fixed_resolution_shift);
     } else {
         m_nVal = 0;
     }
     if (uint64_t const self_lower = (self&0xffffffff))
     {
         uint64_t const other_upper = static_cast<uint64_t>(other >> 32);
         uint64_t const other_lower = static_cast<uint64_t>(other & 0xffffffff);
         uint64_t const lower_self_upper_other_res = self_lower*other_upper;
         uint64_t const lower_self_lower_other_res = self_lower*other_lower;
         m_nVal += (lower_self_upper_other_res << (32 - FixedTraits<IntBits>::fixed_resolution_shift))
             + (lower_self_lower_other_res >> FixedTraits<IntBits>::fixed_resolution_shift);
     }
     if (negate) {
         m_nVal=-m_nVal;
     }
     return *this;
 }
operator*=() [2/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator*= (double val) inline
Definition at line 240 of file fixed.h.
References Fixed< IntType, IntBits >::Fixed().
     {
         return (*this) *= Fixed(val);
     }
operator*=() [3/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator*= (float val) inline
Definition at line 245 of file fixed.h.
References Fixed< IntType, IntBits >::Fixed().
     {
         return (*this) *= Fixed(val);
     }
operator*=() [4/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator*= (int64_t val) inline
Definition at line 250 of file fixed.h.
     {
         m_nVal *= val;
         return *this;
     }
operator*=() [5/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator*= (int val) inline
Definition at line 256 of file fixed.h.
     {
         m_nVal *= val;
         return *this;
     }
operator*=() [6/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator*= (short val) inline
Definition at line 262 of file fixed.h.
     {
         m_nVal *= val;
         return *this;
     }
operator*=() [7/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator*= (char val) inline
Definition at line 268 of file fixed.h.
     {
         m_nVal *= val;
         return *this;
     }
operator*=() [8/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator*= (uint64_t val) inline
Definition at line 274 of file fixed.h.
     {
         m_nVal *= val;
         return *this;
     }
operator*=() [9/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator*= (unsigned int val) inline
Definition at line 280 of file fixed.h.
     {
         m_nVal *= val;
         return *this;
     }
operator*=() [10/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator*= (unsigned short val) inline
Definition at line 286 of file fixed.h.
     {
         m_nVal *= val;
         return *this;
     }
operator*=() [11/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator*= (unsigned char val) inline
Definition at line 292 of file fixed.h.
     {
         m_nVal *= val;
         return *this;
     }
operator++()
template<typename IntType, uint32_t IntBits> Fixed Fixed< IntType, IntBits >::operator++ () inline
Definition at line 207 of file fixed.h.
     {
         m_nVal += FixedTraits<IntBits>::fixed_resolution;
         return *this;
     }
operator+=()
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator+= (Fixed< IntType, IntBits > const & val) inline
Definition at line 234 of file fixed.h.
References Fixed< IntType, IntBits >::m_nVal.
     {
         m_nVal += val.m_nVal;
         return *this;
     }
operator-()
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > Fixed< IntType, IntBits >::operator- () const inline
Definition at line 2377 of file fixed.h.
References Fixed< IntType, IntBits >::Fixed(), and Fixed< IntType, IntBits >::m_nVal.
Referenced by Fixed< IntType, IntBits >::operator!().
 {
     return Fixed(internal(), -m_nVal);
 }
operator--()
template<typename IntType, uint32_t IntBits> Fixed Fixed< IntType, IntBits >::operator-- () inline
Definition at line 213 of file fixed.h.
References Fixed< IntType, IntBits >::ceil(), Fixed< IntType, IntBits >::exp(), Fixed< IntType, IntBits >::floor(), Fixed< IntType, IntBits >::log(), Fixed< IntType, IntBits >::operator%=(), Fixed< IntType, IntBits >::operator*=(), Fixed< IntType, IntBits >::operator/=(), and Fixed< IntType, IntBits >::sqrt().
     {
         m_nVal -= FixedTraits<IntBits>::fixed_resolution;
         return *this;
     }
operator-=()
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator-= (Fixed< IntType, IntBits > const & val) inline
Definition at line 228 of file fixed.h.
References Fixed< IntType, IntBits >::m_nVal.
     {
         m_nVal -= val.m_nVal;
         return *this;
     }
operator/=() [1/11]
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > & Fixed< IntType, IntBits >::operator/= (Fixed< IntType, IntBits > const & val)
Definition at line 421 of file fixed.h.
References Fixed< IntType, IntBits >::fixed_max, Fixed< IntType, IntBits >::m_nVal, and Fixed< IntType, IntBits >::right_shift().
Referenced by Fixed< IntType, IntBits >::operator--().
 {
     if( !divisor.m_nVal)
     {
         m_nVal = fixed_max.m_nVal;
     }
     else
     {
         bool const negate_this = (m_nVal < 0);
         bool const negate_divisor = (divisor.m_nVal < 0);
         bool const negate = negate_this ^ negate_divisor;
         uint64_t a = negate_this ? -m_nVal : m_nVal;
         uint64_t b = negate_divisor ? -divisor.m_nVal : divisor.m_nVal;
         uint64_t res = 0;
         uint64_t temp = b;
         bool const a_large = a > b;
         unsigned shift = FixedTraits<IntBits>::fixed_resolution_shift;
         if(a_large)
         {
             uint64_t const half_a = a>>1;
             while (temp < half_a)
             {
                 temp <<= 1;
                 ++shift;
             }
         }
         uint64_t d = 1LL << shift;
         if (a_large)
         {
             a -= temp;
             res += d;
         }
         while (a && temp && shift)
         {
             unsigned right_shift = 0;
             while(right_shift < shift && (temp > a))
             {
                 temp >>= 1;
                 ++right_shift;
             }
             d >>= right_shift;
             shift -= right_shift;
             a -= temp;
             res += d;
         }
         m_nVal = (negate ? -(int64_t) res : res);
     }
     return *this;
 }
operator/=() [2/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator/= (double val) inline
Definition at line 298 of file fixed.h.
References Fixed< IntType, IntBits >::Fixed().
     {
         return (*this) /= Fixed(val);
     }
operator/=() [3/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator/= (float val) inline
Definition at line 303 of file fixed.h.
References Fixed< IntType, IntBits >::Fixed().
     {
         return (*this) /= Fixed(val);
     }
operator/=() [4/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator/= (int64_t val) inline
Definition at line 308 of file fixed.h.
     {
         m_nVal /= val;
         return *this;
     }
operator/=() [5/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator/= (int val) inline
Definition at line 314 of file fixed.h.
     {
         m_nVal /= val;
         return *this;
     }
operator/=() [6/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator/= (short val) inline
Definition at line 320 of file fixed.h.
     {
         m_nVal /= val;
         return *this;
     }
operator/=() [7/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator/= (char val) inline
Definition at line 326 of file fixed.h.
     {
         m_nVal /= val;
         return *this;
     }
operator/=() [8/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator/= (uint64_t val) inline
Definition at line 332 of file fixed.h.
     {
         m_nVal /= val;
         return *this;
     }
operator/=() [9/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator/= (unsigned int val) inline
Definition at line 338 of file fixed.h.
     {
         m_nVal/=val;
         return *this;
     }
operator/=() [10/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator/= (unsigned short val) inline
Definition at line 344 of file fixed.h.
     {
         m_nVal /= val;
         return *this;
     }
operator/=() [11/11]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator/= (unsigned char val) inline
Definition at line 350 of file fixed.h.
     {
         m_nVal /= val;
         return *this;
     }
operator=() [1/2]
template<typename IntType, uint32_t IntBits> template<typename T > Fixed& Fixed< IntType, IntBits >::operator= (T other) inline
Definition at line 102 of file fixed.h.
References Fixed< IntType, IntBits >::Fixed().
     {
         m_nVal = Fixed(other).m_nVal;
         return *this;
     }
operator=() [2/2]
template<typename IntType, uint32_t IntBits> Fixed& Fixed< IntType, IntBits >::operator= (Fixed< IntType, IntBits > const & other) inline
Definition at line 108 of file fixed.h.
References Fixed< IntType, IntBits >::m_nVal.
     {
         m_nVal = other.m_nVal;
         return *this;
     }
perform_cordic_polarization()
template<typename IntType , uint32_t IntBits> void Fixed< IntType, IntBits >::perform_cordic_polarization (int64_t & argx, int64_t & argy) static private
Definition at line 696 of file fixed.h.
References i, Fixed< IntType, IntBits >::right_shift(), and Fixed< IntType, IntBits >::scale_cordic_result().
Referenced by Fixed< IntType, IntBits >::to_polar().
 {
     int64_t theta = 0;
     int64_t x = argx, y = argy;
     int64_t const *arctanptr = FixedTraits<IntBits>::arctantab;
     for (int i = -1; i <= (int) FixedTraits<IntBits>::fixed_resolution_shift; ++i)
     {
         int64_t const yshift = right_shift(y,i);
         int64_t const xshift = right_shift(x,i);
         if(y < 0)
         {
             y += xshift;
             x -= yshift;
             theta -= *arctanptr++;
         }
         else
         {
             y -= xshift;
             x += yshift;
             theta += *arctanptr++;
         }
     }
     argx = scale_cordic_result(x);
     argy = theta;
 }
perform_cordic_rotation()
template<typename IntType , uint32_t IntBits> void Fixed< IntType, IntBits >::perform_cordic_rotation (int64_t & px, int64_t & py, int64_t theta) static private
Definition at line 668 of file fixed.h.
References i, Fixed< IntType, IntBits >::right_shift(), and Fixed< IntType, IntBits >::scale_cordic_result().
Referenced by Fixed< IntType, IntBits >::sin_cos().
 {
     int64_t x = px, y = py;
     int64_t const *arctanptr = FixedTraits<IntBits>::arctantab;
     for (int i = -1; i <= (int) FixedTraits<IntBits>::fixed_resolution_shift; ++i)
     {
         int64_t const yshift = right_shift(y,i);
         int64_t const xshift = right_shift(x,i);
         if (theta < 0)
         {
             x += yshift;
             y -= xshift;
             theta += *arctanptr++;
         }
         else
         {
             x -= yshift;
             y += xshift;
             theta -= *arctanptr++;
         }
     }
     px = scale_cordic_result(x);
     py = scale_cordic_result(y);
 }
right_shift()
template<typename IntType , uint32_t IntBits> int64_t Fixed< IntType, IntBits >::right_shift (int64_t val, int shift) static private
Definition at line 662 of file fixed.h.
Referenced by Fixed< IntType, IntBits >::log(), Fixed< IntType, IntBits >::operator/=(), Fixed< IntType, IntBits >::perform_cordic_polarization(), Fixed< IntType, IntBits >::perform_cordic_rotation(), and Fixed< IntType, IntBits >::to_polar().
 {
     return (shift < 0) ? (val << -shift) : (val >> shift);
 }
scale_cordic_result()
template<typename IntType , uint32_t IntBits> int64_t Fixed< IntType, IntBits >::scale_cordic_result (int64_t a) static private
Definition at line 655 of file fixed.h.
Referenced by Fixed< IntType, IntBits >::perform_cordic_polarization(), and Fixed< IntType, IntBits >::perform_cordic_rotation().
 {
     int64_t const cordic_scale_factor = 0x22C2DD1C; /* 0.271572 * 2^31*/
     return (int64_t)((((int64_t)a)*cordic_scale_factor) >> 31);
 }
sin()
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > Fixed< IntType, IntBits >::sin () const inline
Definition at line 2353 of file fixed.h.
References Fixed< IntType, IntBits >::sin_cos().
Referenced by Fixed< IntType, IntBits >::operator!(), and sin().
 {
     Fixed res;
     sin_cos(*this, &res, 0);
     return res;
 }
sin_cos()
template<typename IntType , uint32_t IntBits> void Fixed< IntType, IntBits >::sin_cos (Fixed< IntType, IntBits > const & theta, Fixed< IntType, IntBits > * s, Fixed< IntType, IntBits > * c) static
Definition at line 726 of file fixed.h.
References Fixed< IntType, IntBits >::m_nVal, and Fixed< IntType, IntBits >::perform_cordic_rotation().
Referenced by Fixed< IntType, IntBits >::cos(), Fixed< IntType, IntBits >::operator!(), polar(), Fixed< IntType, IntBits >::sin(), and Fixed< IntType, IntBits >::tan().
 {
     int64_t x = theta.m_nVal % FixedTraits<IntBits>::internal_two_pi;
     if (x < 0) {
         x += FixedTraits<IntBits>::internal_two_pi;
     }
     bool negate_cos = false;
     bool negate_sin = false;
     if (x > FixedTraits<IntBits>::internal_pi)
     {
         x = FixedTraits<IntBits>::internal_two_pi - x;
         negate_sin=true;
     }
     if (x > FixedTraits<IntBits>::internal_half_pi)
     {
         x = FixedTraits<IntBits>::internal_pi - x;
         negate_cos=true;
     }
     int64_t x_cos = 1<<FixedTraits<IntBits>::fixed_resolution_shift, x_sin = 0;
     perform_cordic_rotation(x_cos, x_sin, (int64_t) x);
     if (s) {
         s->m_nVal = negate_sin ? -x_sin : x_sin;
     }
     if(c) {
         c->m_nVal = negate_cos ? -x_cos : x_cos;
     }
 }
sqrt()
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > Fixed< IntType, IntBits >::sqrt () const
Definition at line 483 of file fixed.h.
References Fixed< IntType, IntBits >::m_nVal.
Referenced by Fixed< IntType, IntBits >::operator--(), and sqrt().
 {
     unsigned int const max_shift = 62;
     uint64_t a_squared = 1LL << max_shift;
     unsigned int b_shift = (max_shift + FixedTraits<IntBits>::fixed_resolution_shift) / 2;
     uint64_t a = 1LL << b_shift;
     uint64_t x = m_nVal;
     while (b_shift && (a_squared > x))
     {
         a >>= 1;
         a_squared >>= 2;
         --b_shift;
     }
     uint64_t remainder = x - a_squared;
     --b_shift;
     while (remainder && b_shift)
     {
         uint64_t b_squared = 1LL << (2*b_shift - FixedTraits<IntBits>::fixed_resolution_shift);
         int const two_a_b_shift = b_shift + 1 - FixedTraits<IntBits>::fixed_resolution_shift;
         uint64_t two_a_b = (two_a_b_shift > 0) ? (a << two_a_b_shift) : (a >> -two_a_b_shift);
         while (b_shift && (remainder < (b_squared+two_a_b)))
         {
             b_squared >>= 2;
             two_a_b >>= 1;
             --b_shift;
         }
         uint64_t const delta = b_squared + two_a_b;
         if ((2*remainder) > delta)
         {
             a += (1LL << b_shift);
             remainder -= delta;
             if (b_shift) {
                 --b_shift;
             }
         }
     }
     return Fixed<IntType, IntBits>(Fixed<IntType, IntBits>::internal(), a);
 }
tan()
template<typename IntType , uint32_t IntBits> Fixed< IntType, IntBits > Fixed< IntType, IntBits >::tan () const inline
Definition at line 2369 of file fixed.h.
References Fixed< IntType, IntBits >::sin_cos().
Referenced by Fixed< IntType, IntBits >::operator!(), and tan().
 {
     Fixed s, c;
     sin_cos(*this, &s, &c);
     return s/c;
 }
to_polar()
template<typename IntType , uint32_t IntBits> void Fixed< IntType, IntBits >::to_polar (Fixed< IntType, IntBits > const & x, Fixed< IntType, IntBits > const & y, Fixed< IntType, IntBits > * r, Fixed< IntType, IntBits > * theta) static
Definition at line 771 of file fixed.h.
References Fixed< IntType, IntBits >::m_nVal, Fixed< IntType, IntBits >::perform_cordic_polarization(), and Fixed< IntType, IntBits >::right_shift().
Referenced by arg(), Fixed< IntType, IntBits >::atan(), and Fixed< IntType, IntBits >::operator!().
 {
     bool const negative_x = x.m_nVal < 0;
     bool const negative_y = y.m_nVal < 0;
     uint64_t a = negative_x ? -x.m_nVal : x.m_nVal;
     uint64_t b = negative_y ? -y.m_nVal : y.m_nVal;
     unsigned int right_shift = 0;
     unsigned const max_value = 1U << FixedTraits<IntBits>::fixed_resolution_shift;
     while ((a >= max_value) || (b >= max_value))
     {
         ++right_shift;
         a >>= 1;
         b >>= 1;
     }
     int64_t xtemp = (int64_t) a;
     int64_t ytemp = (int64_t) b;
     perform_cordic_polarization(xtemp, ytemp);
     r->m_nVal = int64_t(xtemp) << right_shift;
     theta->m_nVal = ytemp;
     if (negative_x && negative_y) {
         theta->m_nVal -= FixedTraits<IntBits>::internal_pi;
     } else if (negative_x) {
         theta->m_nVal = FixedTraits<IntBits>::internal_pi - theta->m_nVal;
     }
     else if(negative_y) {
         theta->m_nVal = -theta->m_nVal;
     }
 }
Friends And Related Function Documentation
operator!=
template<typename IntType, uint32_t IntBits> bool operator!= (Fixed< IntType, IntBits > const & lhs, Fixed< IntType, IntBits > const & rhs) friend
Definition at line 119 of file fixed.h.
     {
         return lhs.m_nVal != rhs.m_nVal;
     }
operator<
template<typename IntType, uint32_t IntBits> bool operator< (Fixed< IntType, IntBits > const & lhs, Fixed< IntType, IntBits > const & rhs) friend
Definition at line 124 of file fixed.h.
     {
         return lhs.m_nVal < rhs.m_nVal;
     }
operator<=
template<typename IntType, uint32_t IntBits> bool operator<= (Fixed< IntType, IntBits > const & lhs, Fixed< IntType, IntBits > const & rhs) friend
Definition at line 134 of file fixed.h.
     {
         return lhs.m_nVal <= rhs.m_nVal;
     }
operator==
template<typename IntType, uint32_t IntBits> bool operator== (Fixed< IntType, IntBits > const & lhs, Fixed< IntType, IntBits > const & rhs) friend
Definition at line 114 of file fixed.h.
     {
         return lhs.m_nVal == rhs.m_nVal;
     }
operator>
template<typename IntType, uint32_t IntBits> bool operator> (Fixed< IntType, IntBits > const & lhs, Fixed< IntType, IntBits > const & rhs) friend
Definition at line 129 of file fixed.h.
     {
         return lhs.m_nVal > rhs.m_nVal;
     }
operator>=
template<typename IntType, uint32_t IntBits> bool operator>= (Fixed< IntType, IntBits > const & lhs, Fixed< IntType, IntBits > const & rhs) friend
Definition at line 139 of file fixed.h.
     {
         return lhs.m_nVal >= rhs.m_nVal;
     }
Member Data Documentation
fixed_half
template<typename IntType, uint32_t IntBits> const Fixed< IntType, IntBits > Fixed< IntType, IntBits >::fixed_half static
Definition at line 56 of file fixed.h.
Referenced by polar().
fixed_half_pi
template<typename IntType, uint32_t IntBits> const Fixed< IntType, IntBits > Fixed< IntType, IntBits >::fixed_half_pi static
Definition at line 59 of file fixed.h.
Referenced by polar().
fixed_max
template<typename IntType, uint32_t IntBits> const Fixed< IntType, IntBits > Fixed< IntType, IntBits >::fixed_max static
Definition at line 53 of file fixed.h.
Referenced by Fixed< IntType, IntBits >::exp(), Fixed< IntType, IntBits >::log(), Fixed< IntType, IntBits >::operator/=(), and polar().
fixed_one
template<typename IntType, uint32_t IntBits> const Fixed< IntType, IntBits > Fixed< IntType, IntBits >::fixed_one static
Definition at line 54 of file fixed.h.
Referenced by polar().
fixed_pi
template<typename IntType, uint32_t IntBits> const Fixed< IntType, IntBits > Fixed< IntType, IntBits >::fixed_pi static
Definition at line 57 of file fixed.h.
Referenced by polar().
fixed_quarter_pi
template<typename IntType, uint32_t IntBits> const Fixed< IntType, IntBits > Fixed< IntType, IntBits >::fixed_quarter_pi static
Definition at line 60 of file fixed.h.
Referenced by polar().
fixed_two_pi
template<typename IntType, uint32_t IntBits> const Fixed< IntType, IntBits > Fixed< IntType, IntBits >::fixed_two_pi static
Definition at line 58 of file fixed.h.
Referenced by polar().
fixed_zero
template<typename IntType, uint32_t IntBits> const Fixed< IntType, IntBits > Fixed< IntType, IntBits >::fixed_zero static
Definition at line 55 of file fixed.h.
Referenced by Fixed< IntType, IntBits >::log(), and polar().
m_nVal
template<typename IntType, uint32_t IntBits> IntType Fixed< IntType, IntBits >::m_nVal private
Definition at line 45 of file fixed.h.
Referenced by Fixed< IntType, IntBits >::abs(), Fixed< IntType, IntBits >::as_internal(), Fixed< IntType, IntBits >::ceil(), Fixed< IntType, IntBits >::exp(), Fixed< IntType, IntBits >::floor(), Fixed< IntType, IntBits >::log(), Fixed< IntType, IntBits >::modf(), Fixed< IntType, IntBits >::operator%=(), Fixed< IntType, IntBits >::operator*=(), Fixed< IntType, IntBits >::operator+=(), Fixed< IntType, IntBits >::operator-(), Fixed< IntType, IntBits >::operator-=(), Fixed< IntType, IntBits >::operator/=(), Fixed< IntType, IntBits >::operator=(), Fixed< IntType, IntBits >::sin_cos(), Fixed< IntType, IntBits >::sqrt(), and Fixed< IntType, IntBits >::to_polar().
The documentation for this class was generated from the following file:
sdrbase/util/fixed.h