SDRAngel: SWGSDRangel::SWGChannelReport Class Reference
SWGSDRangel::SWGChannelReport Class Reference
#include <SWGChannelReport.h>
Public Member Functions
SWGChannelReport ()
SWGChannelReport (QString *json)
virtual ~SWGChannelReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGChannelReport * fromJson (QString &jsonString) override
QString * getChannelType ()
void setChannelType (QString *channel_type)
qint32 getDirection ()
void setDirection (qint32 direction)
SWGAMDemodReport * getAmDemodReport ()
void setAmDemodReport (SWGAMDemodReport *am_demod_report)
SWGAMModReport * getAmModReport ()
void setAmModReport (SWGAMModReport *am_mod_report)
SWGATVModReport * getAtvModReport ()
void setAtvModReport (SWGATVModReport *atv_mod_report)
SWGBFMDemodReport * getBfmDemodReport ()
void setBfmDemodReport (SWGBFMDemodReport *bfm_demod_report)
SWGDSDDemodReport * getDsdDemodReport ()
void setDsdDemodReport (SWGDSDDemodReport *dsd_demod_report)
SWGFileSourceReport * getFileSourceReport ()
void setFileSourceReport (SWGFileSourceReport *file_source_report)
SWGFreeDVDemodReport * getFreeDvDemodReport ()
void setFreeDvDemodReport (SWGFreeDVDemodReport *free_dv_demod_report)
SWGFreeDVModReport * getFreeDvModReport ()
void setFreeDvModReport (SWGFreeDVModReport *free_dv_mod_report)
SWGFreqTrackerReport * getFreqTrackerReport ()
void setFreqTrackerReport (SWGFreqTrackerReport *freq_tracker_report)
SWGNFMDemodReport * getNfmDemodReport ()
void setNfmDemodReport (SWGNFMDemodReport *nfm_demod_report)
SWGNFMModReport * getNfmModReport ()
void setNfmModReport (SWGNFMModReport *nfm_mod_report)
SWGSSBDemodReport * getSsbDemodReport ()
void setSsbDemodReport (SWGSSBDemodReport *ssb_demod_report)
SWGRemoteSourceReport * getRemoteSourceReport ()
void setRemoteSourceReport (SWGRemoteSourceReport *remote_source_report)
SWGSSBModReport * getSsbModReport ()
void setSsbModReport (SWGSSBModReport *ssb_mod_report)
SWGUDPSourceReport * getUdpSourceReport ()
void setUdpSourceReport (SWGUDPSourceReport *udp_source_report)
SWGUDPSinkReport * getUdpSinkReport ()
void setUdpSinkReport (SWGUDPSinkReport *udp_sink_report)
SWGWFMDemodReport * getWfmDemodReport ()
void setWfmDemodReport (SWGWFMDemodReport *wfm_demod_report)
SWGWFMModReport * getWfmModReport ()
void setWfmModReport (SWGWFMModReport *wfm_mod_report)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * channel_type
bool m_channel_type_isSet
qint32 direction
bool m_direction_isSet
SWGAMDemodReport * am_demod_report
bool m_am_demod_report_isSet
SWGAMModReport * am_mod_report
bool m_am_mod_report_isSet
SWGATVModReport * atv_mod_report
bool m_atv_mod_report_isSet
SWGBFMDemodReport * bfm_demod_report
bool m_bfm_demod_report_isSet
SWGDSDDemodReport * dsd_demod_report
bool m_dsd_demod_report_isSet
SWGFileSourceReport * file_source_report
bool m_file_source_report_isSet
SWGFreeDVDemodReport * free_dv_demod_report
bool m_free_dv_demod_report_isSet
SWGFreeDVModReport * free_dv_mod_report
bool m_free_dv_mod_report_isSet
SWGFreqTrackerReport * freq_tracker_report
bool m_freq_tracker_report_isSet
SWGNFMDemodReport * nfm_demod_report
bool m_nfm_demod_report_isSet
SWGNFMModReport * nfm_mod_report
bool m_nfm_mod_report_isSet
SWGSSBDemodReport * ssb_demod_report
bool m_ssb_demod_report_isSet
SWGRemoteSourceReport * remote_source_report
bool m_remote_source_report_isSet
SWGSSBModReport * ssb_mod_report
bool m_ssb_mod_report_isSet
SWGUDPSourceReport * udp_source_report
bool m_udp_source_report_isSet
SWGUDPSinkReport * udp_sink_report
bool m_udp_sink_report_isSet
SWGWFMDemodReport * wfm_demod_report
bool m_wfm_demod_report_isSet
SWGWFMModReport * wfm_mod_report
bool m_wfm_mod_report_isSet
Detailed Description
Definition at line 50 of file SWGChannelReport.h.
Constructor & Destructor Documentation
SWGChannelReport() [1/2]
SWGSDRangel::SWGChannelReport::SWGChannelReport ()
Definition at line 30 of file SWGChannelReport.cpp.
References am_demod_report, am_mod_report, atv_mod_report, bfm_demod_report, channel_type, direction, dsd_demod_report, file_source_report, free_dv_demod_report, free_dv_mod_report, freq_tracker_report, m_am_demod_report_isSet, m_am_mod_report_isSet, m_atv_mod_report_isSet, m_bfm_demod_report_isSet, m_channel_type_isSet, m_direction_isSet, m_dsd_demod_report_isSet, m_file_source_report_isSet, m_free_dv_demod_report_isSet, m_free_dv_mod_report_isSet, m_freq_tracker_report_isSet, m_nfm_demod_report_isSet, m_nfm_mod_report_isSet, m_remote_source_report_isSet, m_ssb_demod_report_isSet, m_ssb_mod_report_isSet, m_udp_sink_report_isSet, m_udp_source_report_isSet, m_wfm_demod_report_isSet, m_wfm_mod_report_isSet, nfm_demod_report, nfm_mod_report, remote_source_report, ssb_demod_report, ssb_mod_report, udp_sink_report, udp_source_report, wfm_demod_report, and wfm_mod_report.
{
     channel_type = nullptr;
     m_channel_type_isSet = false;
     direction = 0;
     m_direction_isSet = false;
     am_demod_report = nullptr;
     m_am_demod_report_isSet = false;
     am_mod_report = nullptr;
     m_am_mod_report_isSet = false;
     atv_mod_report = nullptr;
     m_atv_mod_report_isSet = false;
     bfm_demod_report = nullptr;
     m_bfm_demod_report_isSet = false;
     dsd_demod_report = nullptr;
     m_dsd_demod_report_isSet = false;
     file_source_report = nullptr;
     m_file_source_report_isSet = false;
     free_dv_demod_report = nullptr;
     m_free_dv_demod_report_isSet = false;
     free_dv_mod_report = nullptr;
     m_free_dv_mod_report_isSet = false;
     freq_tracker_report = nullptr;
     m_freq_tracker_report_isSet = false;
     nfm_demod_report = nullptr;
     m_nfm_demod_report_isSet = false;
     nfm_mod_report = nullptr;
     m_nfm_mod_report_isSet = false;
     ssb_demod_report = nullptr;
     m_ssb_demod_report_isSet = false;
     remote_source_report = nullptr;
     m_remote_source_report_isSet = false;
     ssb_mod_report = nullptr;
     m_ssb_mod_report_isSet = false;
     udp_source_report = nullptr;
     m_udp_source_report_isSet = false;
     udp_sink_report = nullptr;
     m_udp_sink_report_isSet = false;
     wfm_demod_report = nullptr;
     m_wfm_demod_report_isSet = false;
     wfm_mod_report = nullptr;
     m_wfm_mod_report_isSet = false;
 }
SWGChannelReport() [2/2]
SWGSDRangel::SWGChannelReport::SWGChannelReport (QString * json)
Definition at line 25 of file SWGChannelReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGChannelReport()
SWGSDRangel::SWGChannelReport::~SWGChannelReport () virtual
Definition at line 73 of file SWGChannelReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGChannelReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 237 of file SWGChannelReport.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::devicesetChannelReportService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGChannelReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 248 of file SWGChannelReport.cpp.
References am_demod_report, am_mod_report, atv_mod_report, bfm_demod_report, channel_type, direction, dsd_demod_report, file_source_report, free_dv_demod_report, free_dv_mod_report, freq_tracker_report, SWGSDRangel::SWGATVModReport::isSet(), SWGSDRangel::SWGSSBModReport::isSet(), SWGSDRangel::SWGAMModReport::isSet(), SWGSDRangel::SWGFreeDVModReport::isSet(), SWGSDRangel::SWGWFMModReport::isSet(), SWGSDRangel::SWGNFMModReport::isSet(), SWGSDRangel::SWGWFMDemodReport::isSet(), SWGSDRangel::SWGFreeDVDemodReport::isSet(), SWGSDRangel::SWGUDPSinkReport::isSet(), SWGSDRangel::SWGFreqTrackerReport::isSet(), SWGSDRangel::SWGSSBDemodReport::isSet(), SWGSDRangel::SWGAMDemodReport::isSet(), SWGSDRangel::SWGUDPSourceReport::isSet(), SWGSDRangel::SWGNFMDemodReport::isSet(), SWGSDRangel::SWGBFMDemodReport::isSet(), SWGSDRangel::SWGFileSourceReport::isSet(), SWGSDRangel::SWGRemoteSourceReport::isSet(), SWGSDRangel::SWGDSDDemodReport::isSet(), m_direction_isSet, nfm_demod_report, nfm_mod_report, remote_source_report, ssb_demod_report, ssb_mod_report, SWGSDRangel::toJsonValue(), udp_sink_report, udp_source_report, wfm_demod_report, and wfm_mod_report.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(channel_type != nullptr && *channel_type != QString("")){
         toJsonValue(QString("channelType"), channel_type, obj, QString("QString"));
     }
     if(m_direction_isSet){
         obj->insert("direction", QJsonValue(direction));
     }
     if((am_demod_report != nullptr) && (am_demod_report->isSet())){
         toJsonValue(QString("AMDemodReport"), am_demod_report, obj, QString("SWGAMDemodReport"));
     }
     if((am_mod_report != nullptr) && (am_mod_report->isSet())){
         toJsonValue(QString("AMModReport"), am_mod_report, obj, QString("SWGAMModReport"));
     }
     if((atv_mod_report != nullptr) && (atv_mod_report->isSet())){
         toJsonValue(QString("ATVModReport"), atv_mod_report, obj, QString("SWGATVModReport"));
     }
     if((bfm_demod_report != nullptr) && (bfm_demod_report->isSet())){
         toJsonValue(QString("BFMDemodReport"), bfm_demod_report, obj, QString("SWGBFMDemodReport"));
     }
     if((dsd_demod_report != nullptr) && (dsd_demod_report->isSet())){
         toJsonValue(QString("DSDDemodReport"), dsd_demod_report, obj, QString("SWGDSDDemodReport"));
     }
     if((file_source_report != nullptr) && (file_source_report->isSet())){
         toJsonValue(QString("FileSourceReport"), file_source_report, obj, QString("SWGFileSourceReport"));
     }
     if((free_dv_demod_report != nullptr) && (free_dv_demod_report->isSet())){
         toJsonValue(QString("FreeDVDemodReport"), free_dv_demod_report, obj, QString("SWGFreeDVDemodReport"));
     }
     if((free_dv_mod_report != nullptr) && (free_dv_mod_report->isSet())){
         toJsonValue(QString("FreeDVModReport"), free_dv_mod_report, obj, QString("SWGFreeDVModReport"));
     }
     if((freq_tracker_report != nullptr) && (freq_tracker_report->isSet())){
         toJsonValue(QString("FreqTrackerReport"), freq_tracker_report, obj, QString("SWGFreqTrackerReport"));
     }
     if((nfm_demod_report != nullptr) && (nfm_demod_report->isSet())){
         toJsonValue(QString("NFMDemodReport"), nfm_demod_report, obj, QString("SWGNFMDemodReport"));
     }
     if((nfm_mod_report != nullptr) && (nfm_mod_report->isSet())){
         toJsonValue(QString("NFMModReport"), nfm_mod_report, obj, QString("SWGNFMModReport"));
     }
     if((ssb_demod_report != nullptr) && (ssb_demod_report->isSet())){
         toJsonValue(QString("SSBDemodReport"), ssb_demod_report, obj, QString("SWGSSBDemodReport"));
     }
     if((remote_source_report != nullptr) && (remote_source_report->isSet())){
         toJsonValue(QString("RemoteSourceReport"), remote_source_report, obj, QString("SWGRemoteSourceReport"));
     }
     if((ssb_mod_report != nullptr) && (ssb_mod_report->isSet())){
         toJsonValue(QString("SSBModReport"), ssb_mod_report, obj, QString("SWGSSBModReport"));
     }
     if((udp_source_report != nullptr) && (udp_source_report->isSet())){
         toJsonValue(QString("UDPSourceReport"), udp_source_report, obj, QString("SWGUDPSourceReport"));
     }
     if((udp_sink_report != nullptr) && (udp_sink_report->isSet())){
         toJsonValue(QString("UDPSinkReport"), udp_sink_report, obj, QString("SWGUDPSinkReport"));
     }
     if((wfm_demod_report != nullptr) && (wfm_demod_report->isSet())){
         toJsonValue(QString("WFMDemodReport"), wfm_demod_report, obj, QString("SWGWFMDemodReport"));
     }
     if((wfm_mod_report != nullptr) && (wfm_mod_report->isSet())){
         toJsonValue(QString("WFMModReport"), wfm_mod_report, obj, QString("SWGWFMModReport"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGChannelReport::cleanup ()
Definition at line 122 of file SWGChannelReport.cpp.
References am_demod_report, am_mod_report, atv_mod_report, bfm_demod_report, channel_type, dsd_demod_report, file_source_report, free_dv_demod_report, free_dv_mod_report, freq_tracker_report, nfm_demod_report, nfm_mod_report, remote_source_report, ssb_demod_report, ssb_mod_report, udp_sink_report, udp_source_report, wfm_demod_report, and wfm_mod_report.
Referenced by WebAPIRequestMapper::resetChannelReport(), and ~SWGChannelReport().
{
     if(channel_type != nullptr) {
         delete channel_type;
     }
     if(am_demod_report != nullptr) {
         delete am_demod_report;
     }
     if(am_mod_report != nullptr) {
         delete am_mod_report;
     }
     if(atv_mod_report != nullptr) {
         delete atv_mod_report;
     }
     if(bfm_demod_report != nullptr) {
         delete bfm_demod_report;
     }
     if(dsd_demod_report != nullptr) {
         delete dsd_demod_report;
     }
     if(file_source_report != nullptr) {
         delete file_source_report;
     }
     if(free_dv_demod_report != nullptr) {
         delete free_dv_demod_report;
     }
     if(free_dv_mod_report != nullptr) {
         delete free_dv_mod_report;
     }
     if(freq_tracker_report != nullptr) {
         delete freq_tracker_report;
     }
     if(nfm_demod_report != nullptr) {
         delete nfm_demod_report;
     }
     if(nfm_mod_report != nullptr) {
         delete nfm_mod_report;
     }
     if(ssb_demod_report != nullptr) {
         delete ssb_demod_report;
     }
     if(remote_source_report != nullptr) {
         delete remote_source_report;
     }
     if(ssb_mod_report != nullptr) {
         delete ssb_mod_report;
     }
     if(udp_source_report != nullptr) {
         delete udp_source_report;
     }
     if(udp_sink_report != nullptr) {
         delete udp_sink_report;
     }
     if(wfm_demod_report != nullptr) {
         delete wfm_demod_report;
     }
     if(wfm_mod_report != nullptr) {
         delete wfm_mod_report;
     }
 }
fromJson()
SWGChannelReport * SWGSDRangel::SWGChannelReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 184 of file SWGChannelReport.cpp.
References fromJsonObject().
Referenced by SWGChannelReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGChannelReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 193 of file SWGChannelReport.cpp.
References am_demod_report, am_mod_report, atv_mod_report, bfm_demod_report, channel_type, direction, dsd_demod_report, file_source_report, free_dv_demod_report, free_dv_mod_report, freq_tracker_report, nfm_demod_report, nfm_mod_report, remote_source_report, SWGSDRangel::setValue(), ssb_demod_report, ssb_mod_report, udp_sink_report, udp_source_report, wfm_demod_report, and wfm_mod_report.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&channel_type, pJson["channelType"], "QString", "QString");
     ::SWGSDRangel::setValue(&direction, pJson["direction"], "qint32", "");
     ::SWGSDRangel::setValue(&am_demod_report, pJson["AMDemodReport"], "SWGAMDemodReport", "SWGAMDemodReport");
     ::SWGSDRangel::setValue(&am_mod_report, pJson["AMModReport"], "SWGAMModReport", "SWGAMModReport");
     ::SWGSDRangel::setValue(&atv_mod_report, pJson["ATVModReport"], "SWGATVModReport", "SWGATVModReport");
     ::SWGSDRangel::setValue(&bfm_demod_report, pJson["BFMDemodReport"], "SWGBFMDemodReport", "SWGBFMDemodReport");
     ::SWGSDRangel::setValue(&dsd_demod_report, pJson["DSDDemodReport"], "SWGDSDDemodReport", "SWGDSDDemodReport");
     ::SWGSDRangel::setValue(&file_source_report, pJson["FileSourceReport"], "SWGFileSourceReport", "SWGFileSourceReport");
     ::SWGSDRangel::setValue(&free_dv_demod_report, pJson["FreeDVDemodReport"], "SWGFreeDVDemodReport", "SWGFreeDVDemodReport");
     ::SWGSDRangel::setValue(&free_dv_mod_report, pJson["FreeDVModReport"], "SWGFreeDVModReport", "SWGFreeDVModReport");
     ::SWGSDRangel::setValue(&freq_tracker_report, pJson["FreqTrackerReport"], "SWGFreqTrackerReport", "SWGFreqTrackerReport");
     ::SWGSDRangel::setValue(&nfm_demod_report, pJson["NFMDemodReport"], "SWGNFMDemodReport", "SWGNFMDemodReport");
     ::SWGSDRangel::setValue(&nfm_mod_report, pJson["NFMModReport"], "SWGNFMModReport", "SWGNFMModReport");
     ::SWGSDRangel::setValue(&ssb_demod_report, pJson["SSBDemodReport"], "SWGSSBDemodReport", "SWGSSBDemodReport");
     ::SWGSDRangel::setValue(&remote_source_report, pJson["RemoteSourceReport"], "SWGRemoteSourceReport", "SWGRemoteSourceReport");
     ::SWGSDRangel::setValue(&ssb_mod_report, pJson["SSBModReport"], "SWGSSBModReport", "SWGSSBModReport");
     ::SWGSDRangel::setValue(&udp_source_report, pJson["UDPSourceReport"], "SWGUDPSourceReport", "SWGUDPSourceReport");
     ::SWGSDRangel::setValue(&udp_sink_report, pJson["UDPSinkReport"], "SWGUDPSinkReport", "SWGUDPSinkReport");
     ::SWGSDRangel::setValue(&wfm_demod_report, pJson["WFMDemodReport"], "SWGWFMDemodReport", "SWGWFMDemodReport");
     ::SWGSDRangel::setValue(&wfm_mod_report, pJson["WFMModReport"], "SWGWFMModReport", "SWGWFMModReport");
 }
getAmDemodReport()
SWGAMDemodReport * SWGSDRangel::SWGChannelReport::getAmDemodReport ()
Definition at line 335 of file SWGChannelReport.cpp.
References am_demod_report.
Referenced by AMDemod::webapiFormatChannelReport(), and AMDemod::webapiReportGet().
{
     return am_demod_report;
 }
getAmModReport()
SWGAMModReport * SWGSDRangel::SWGChannelReport::getAmModReport ()
Definition at line 345 of file SWGChannelReport.cpp.
References am_mod_report.
Referenced by AMMod::webapiFormatChannelReport(), and AMMod::webapiReportGet().
{
     return am_mod_report;
 }
getAtvModReport()
SWGATVModReport * SWGSDRangel::SWGChannelReport::getAtvModReport ()
Definition at line 355 of file SWGChannelReport.cpp.
References atv_mod_report.
Referenced by ATVMod::webapiFormatChannelReport(), and ATVMod::webapiReportGet().
{
     return atv_mod_report;
 }
getBfmDemodReport()
SWGBFMDemodReport * SWGSDRangel::SWGChannelReport::getBfmDemodReport ()
Definition at line 365 of file SWGChannelReport.cpp.
References bfm_demod_report.
Referenced by BFMDemod::webapiFormatChannelReport(), and BFMDemod::webapiReportGet().
{
     return bfm_demod_report;
 }
getChannelType()
QString * SWGSDRangel::SWGChannelReport::getChannelType ()
Definition at line 315 of file SWGChannelReport.cpp.
References channel_type.
Referenced by WebAPIAdapterGUI::devicesetChannelReportGet(), and WebAPIAdapterSrv::devicesetChannelReportGet().
{
     return channel_type;
 }
getDirection()
qint32 SWGSDRangel::SWGChannelReport::getDirection ()
Definition at line 325 of file SWGChannelReport.cpp.
References direction.
{
     return direction;
 }
getDsdDemodReport()
SWGDSDDemodReport * SWGSDRangel::SWGChannelReport::getDsdDemodReport ()
Definition at line 375 of file SWGChannelReport.cpp.
References dsd_demod_report.
Referenced by DSDDemod::webapiFormatChannelReport(), and DSDDemod::webapiReportGet().
{
     return dsd_demod_report;
 }
getFileSourceReport()
SWGFileSourceReport * SWGSDRangel::SWGChannelReport::getFileSourceReport ()
Definition at line 385 of file SWGChannelReport.cpp.
References file_source_report.
Referenced by FileSource::webapiFormatChannelReport(), and FileSource::webapiReportGet().
{
     return file_source_report;
 }
getFreeDvDemodReport()
SWGFreeDVDemodReport * SWGSDRangel::SWGChannelReport::getFreeDvDemodReport ()
Definition at line 395 of file SWGChannelReport.cpp.
References free_dv_demod_report.
Referenced by FreeDVDemod::webapiFormatChannelReport(), and FreeDVDemod::webapiReportGet().
{
     return free_dv_demod_report;
 }
getFreeDvModReport()
SWGFreeDVModReport * SWGSDRangel::SWGChannelReport::getFreeDvModReport ()
Definition at line 405 of file SWGChannelReport.cpp.
References free_dv_mod_report.
Referenced by FreeDVMod::webapiFormatChannelReport(), and FreeDVMod::webapiReportGet().
{
     return free_dv_mod_report;
 }
getFreqTrackerReport()
SWGFreqTrackerReport * SWGSDRangel::SWGChannelReport::getFreqTrackerReport ()
Definition at line 415 of file SWGChannelReport.cpp.
References freq_tracker_report.
Referenced by FreqTracker::webapiFormatChannelReport(), and FreqTracker::webapiReportGet().
{
     return freq_tracker_report;
 }
getNfmDemodReport()
SWGNFMDemodReport * SWGSDRangel::SWGChannelReport::getNfmDemodReport ()
Definition at line 425 of file SWGChannelReport.cpp.
References nfm_demod_report.
Referenced by NFMDemod::webapiFormatChannelReport(), and NFMDemod::webapiReportGet().
{
     return nfm_demod_report;
 }
getNfmModReport()
SWGNFMModReport * SWGSDRangel::SWGChannelReport::getNfmModReport ()
Definition at line 435 of file SWGChannelReport.cpp.
References nfm_mod_report.
Referenced by NFMMod::webapiFormatChannelReport(), and NFMMod::webapiReportGet().
{
     return nfm_mod_report;
 }
getRemoteSourceReport()
SWGRemoteSourceReport * SWGSDRangel::SWGChannelReport::getRemoteSourceReport ()
Definition at line 455 of file SWGChannelReport.cpp.
References remote_source_report.
Referenced by RemoteSource::webapiFormatChannelReport(), and RemoteSource::webapiReportGet().
{
     return remote_source_report;
 }
getSsbDemodReport()
SWGSSBDemodReport * SWGSDRangel::SWGChannelReport::getSsbDemodReport ()
Definition at line 445 of file SWGChannelReport.cpp.
References ssb_demod_report.
Referenced by SSBDemod::webapiFormatChannelReport(), and SSBDemod::webapiReportGet().
{
     return ssb_demod_report;
 }
getSsbModReport()
SWGSSBModReport * SWGSDRangel::SWGChannelReport::getSsbModReport ()
Definition at line 465 of file SWGChannelReport.cpp.
References ssb_mod_report.
Referenced by SSBMod::webapiFormatChannelReport(), and SSBMod::webapiReportGet().
{
     return ssb_mod_report;
 }
getUdpSinkReport()
SWGUDPSinkReport * SWGSDRangel::SWGChannelReport::getUdpSinkReport ()
Definition at line 485 of file SWGChannelReport.cpp.
References udp_sink_report.
Referenced by UDPSink::webapiFormatChannelReport(), and UDPSink::webapiReportGet().
{
     return udp_sink_report;
 }
getUdpSourceReport()
SWGUDPSourceReport * SWGSDRangel::SWGChannelReport::getUdpSourceReport ()
Definition at line 475 of file SWGChannelReport.cpp.
References udp_source_report.
Referenced by UDPSource::webapiFormatChannelReport(), and UDPSource::webapiReportGet().
{
     return udp_source_report;
 }
getWfmDemodReport()
SWGWFMDemodReport * SWGSDRangel::SWGChannelReport::getWfmDemodReport ()
Definition at line 495 of file SWGChannelReport.cpp.
References wfm_demod_report.
Referenced by WFMDemod::webapiFormatChannelReport(), and WFMDemod::webapiReportGet().
{
     return wfm_demod_report;
 }
getWfmModReport()
SWGWFMModReport * SWGSDRangel::SWGChannelReport::getWfmModReport ()
Definition at line 505 of file SWGChannelReport.cpp.
References wfm_mod_report.
Referenced by WFMMod::webapiFormatChannelReport(), and WFMMod::webapiReportGet().
{
     return wfm_mod_report;
 }
init()
void SWGSDRangel::SWGChannelReport::init ()
Definition at line 78 of file SWGChannelReport.cpp.
References am_demod_report, am_mod_report, atv_mod_report, bfm_demod_report, channel_type, direction, dsd_demod_report, file_source_report, free_dv_demod_report, free_dv_mod_report, freq_tracker_report, m_am_demod_report_isSet, m_am_mod_report_isSet, m_atv_mod_report_isSet, m_bfm_demod_report_isSet, m_channel_type_isSet, m_direction_isSet, m_dsd_demod_report_isSet, m_file_source_report_isSet, m_free_dv_demod_report_isSet, m_free_dv_mod_report_isSet, m_freq_tracker_report_isSet, m_nfm_demod_report_isSet, m_nfm_mod_report_isSet, m_remote_source_report_isSet, m_ssb_demod_report_isSet, m_ssb_mod_report_isSet, m_udp_sink_report_isSet, m_udp_source_report_isSet, m_wfm_demod_report_isSet, m_wfm_mod_report_isSet, nfm_demod_report, nfm_mod_report, remote_source_report, ssb_demod_report, ssb_mod_report, udp_sink_report, udp_source_report, wfm_demod_report, and wfm_mod_report.
Referenced by SWGChannelReport().
{
     channel_type = new QString("");
     m_channel_type_isSet = false;
     direction = 0;
     m_direction_isSet = false;
     am_demod_report = new SWGAMDemodReport();
     m_am_demod_report_isSet = false;
     am_mod_report = new SWGAMModReport();
     m_am_mod_report_isSet = false;
     atv_mod_report = new SWGATVModReport();
     m_atv_mod_report_isSet = false;
     bfm_demod_report = new SWGBFMDemodReport();
     m_bfm_demod_report_isSet = false;
     dsd_demod_report = new SWGDSDDemodReport();
     m_dsd_demod_report_isSet = false;
     file_source_report = new SWGFileSourceReport();
     m_file_source_report_isSet = false;
     free_dv_demod_report = new SWGFreeDVDemodReport();
     m_free_dv_demod_report_isSet = false;
     free_dv_mod_report = new SWGFreeDVModReport();
     m_free_dv_mod_report_isSet = false;
     freq_tracker_report = new SWGFreqTrackerReport();
     m_freq_tracker_report_isSet = false;
     nfm_demod_report = new SWGNFMDemodReport();
     m_nfm_demod_report_isSet = false;
     nfm_mod_report = new SWGNFMModReport();
     m_nfm_mod_report_isSet = false;
     ssb_demod_report = new SWGSSBDemodReport();
     m_ssb_demod_report_isSet = false;
     remote_source_report = new SWGRemoteSourceReport();
     m_remote_source_report_isSet = false;
     ssb_mod_report = new SWGSSBModReport();
     m_ssb_mod_report_isSet = false;
     udp_source_report = new SWGUDPSourceReport();
     m_udp_source_report_isSet = false;
     udp_sink_report = new SWGUDPSinkReport();
     m_udp_sink_report_isSet = false;
     wfm_demod_report = new SWGWFMDemodReport();
     m_wfm_demod_report_isSet = false;
     wfm_mod_report = new SWGWFMModReport();
     m_wfm_mod_report_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGChannelReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 516 of file SWGChannelReport.cpp.
References am_demod_report, am_mod_report, atv_mod_report, bfm_demod_report, channel_type, dsd_demod_report, file_source_report, free_dv_demod_report, free_dv_mod_report, freq_tracker_report, SWGSDRangel::SWGATVModReport::isSet(), SWGSDRangel::SWGWFMModReport::isSet(), SWGSDRangel::SWGFreeDVModReport::isSet(), SWGSDRangel::SWGNFMModReport::isSet(), SWGSDRangel::SWGAMModReport::isSet(), SWGSDRangel::SWGSSBModReport::isSet(), SWGSDRangel::SWGFreeDVDemodReport::isSet(), SWGSDRangel::SWGUDPSinkReport::isSet(), SWGSDRangel::SWGWFMDemodReport::isSet(), SWGSDRangel::SWGFreqTrackerReport::isSet(), SWGSDRangel::SWGAMDemodReport::isSet(), SWGSDRangel::SWGSSBDemodReport::isSet(), SWGSDRangel::SWGUDPSourceReport::isSet(), SWGSDRangel::SWGNFMDemodReport::isSet(), SWGSDRangel::SWGBFMDemodReport::isSet(), SWGSDRangel::SWGFileSourceReport::isSet(), SWGSDRangel::SWGRemoteSourceReport::isSet(), SWGSDRangel::SWGDSDDemodReport::isSet(), m_direction_isSet, nfm_demod_report, nfm_mod_report, remote_source_report, ssb_demod_report, ssb_mod_report, udp_sink_report, udp_source_report, wfm_demod_report, and wfm_mod_report.
Referenced by SWGSDRangel::SWGChannel::asJsonObject(), and SWGSDRangel::SWGChannel::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(channel_type != nullptr && *channel_type != QString("")){ isObjectUpdated = true; break;}
         if(m_direction_isSet){ isObjectUpdated = true; break;}
         if(am_demod_report != nullptr && am_demod_report->isSet()){ isObjectUpdated = true; break;}
         if(am_mod_report != nullptr && am_mod_report->isSet()){ isObjectUpdated = true; break;}
         if(atv_mod_report != nullptr && atv_mod_report->isSet()){ isObjectUpdated = true; break;}
         if(bfm_demod_report != nullptr && bfm_demod_report->isSet()){ isObjectUpdated = true; break;}
         if(dsd_demod_report != nullptr && dsd_demod_report->isSet()){ isObjectUpdated = true; break;}
         if(file_source_report != nullptr && file_source_report->isSet()){ isObjectUpdated = true; break;}
         if(free_dv_demod_report != nullptr && free_dv_demod_report->isSet()){ isObjectUpdated = true; break;}
         if(free_dv_mod_report != nullptr && free_dv_mod_report->isSet()){ isObjectUpdated = true; break;}
         if(freq_tracker_report != nullptr && freq_tracker_report->isSet()){ isObjectUpdated = true; break;}
         if(nfm_demod_report != nullptr && nfm_demod_report->isSet()){ isObjectUpdated = true; break;}
         if(nfm_mod_report != nullptr && nfm_mod_report->isSet()){ isObjectUpdated = true; break;}
         if(ssb_demod_report != nullptr && ssb_demod_report->isSet()){ isObjectUpdated = true; break;}
         if(remote_source_report != nullptr && remote_source_report->isSet()){ isObjectUpdated = true; break;}
         if(ssb_mod_report != nullptr && ssb_mod_report->isSet()){ isObjectUpdated = true; break;}
         if(udp_source_report != nullptr && udp_source_report->isSet()){ isObjectUpdated = true; break;}
         if(udp_sink_report != nullptr && udp_sink_report->isSet()){ isObjectUpdated = true; break;}
         if(wfm_demod_report != nullptr && wfm_demod_report->isSet()){ isObjectUpdated = true; break;}
         if(wfm_mod_report != nullptr && wfm_mod_report->isSet()){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setAmDemodReport()
void SWGSDRangel::SWGChannelReport::setAmDemodReport (SWGAMDemodReport * am_demod_report)
Definition at line 339 of file SWGChannelReport.cpp.
References am_demod_report, and m_am_demod_report_isSet.
Referenced by WebAPIRequestMapper::resetChannelReport(), and AMDemod::webapiReportGet().
{
     this->am_demod_report = am_demod_report;
     this->m_am_demod_report_isSet = true;
 }
setAmModReport()
void SWGSDRangel::SWGChannelReport::setAmModReport (SWGAMModReport * am_mod_report)
Definition at line 349 of file SWGChannelReport.cpp.
References am_mod_report, and m_am_mod_report_isSet.
Referenced by WebAPIRequestMapper::resetChannelReport(), and AMMod::webapiReportGet().
{
     this->am_mod_report = am_mod_report;
     this->m_am_mod_report_isSet = true;
 }
setAtvModReport()
void SWGSDRangel::SWGChannelReport::setAtvModReport (SWGATVModReport * atv_mod_report)
Definition at line 359 of file SWGChannelReport.cpp.
References atv_mod_report, and m_atv_mod_report_isSet.
Referenced by WebAPIRequestMapper::resetChannelReport(), and ATVMod::webapiReportGet().
{
     this->atv_mod_report = atv_mod_report;
     this->m_atv_mod_report_isSet = true;
 }
setBfmDemodReport()
void SWGSDRangel::SWGChannelReport::setBfmDemodReport (SWGBFMDemodReport * bfm_demod_report)
Definition at line 369 of file SWGChannelReport.cpp.
References bfm_demod_report, and m_bfm_demod_report_isSet.
Referenced by WebAPIRequestMapper::resetChannelReport(), and BFMDemod::webapiReportGet().
{
     this->bfm_demod_report = bfm_demod_report;
     this->m_bfm_demod_report_isSet = true;
 }
setChannelType()
void SWGSDRangel::SWGChannelReport::setChannelType (QString * channel_type)
Definition at line 319 of file SWGChannelReport.cpp.
References channel_type, and m_channel_type_isSet.
Referenced by WebAPIAdapterGUI::devicesetChannelReportGet(), WebAPIAdapterSrv::devicesetChannelReportGet(), and WebAPIRequestMapper::resetChannelReport().
{
     this->channel_type = channel_type;
     this->m_channel_type_isSet = true;
 }
setDirection()
void SWGSDRangel::SWGChannelReport::setDirection (qint32 direction)
Definition at line 329 of file SWGChannelReport.cpp.
References direction, and m_direction_isSet.
Referenced by WebAPIAdapterGUI::devicesetChannelReportGet(), and WebAPIAdapterSrv::devicesetChannelReportGet().
{
     this->direction = direction;
     this->m_direction_isSet = true;
 }
setDsdDemodReport()
void SWGSDRangel::SWGChannelReport::setDsdDemodReport (SWGDSDDemodReport * dsd_demod_report)
Definition at line 379 of file SWGChannelReport.cpp.
References dsd_demod_report, and m_dsd_demod_report_isSet.
Referenced by WebAPIRequestMapper::resetChannelReport(), and DSDDemod::webapiReportGet().
{
     this->dsd_demod_report = dsd_demod_report;
     this->m_dsd_demod_report_isSet = true;
 }
setFileSourceReport()
void SWGSDRangel::SWGChannelReport::setFileSourceReport (SWGFileSourceReport * file_source_report)
Definition at line 389 of file SWGChannelReport.cpp.
References file_source_report, and m_file_source_report_isSet.
Referenced by FileSource::webapiReportGet().
{
     this->file_source_report = file_source_report;
     this->m_file_source_report_isSet = true;
 }
setFreeDvDemodReport()
void SWGSDRangel::SWGChannelReport::setFreeDvDemodReport (SWGFreeDVDemodReport * free_dv_demod_report)
Definition at line 399 of file SWGChannelReport.cpp.
References free_dv_demod_report, and m_free_dv_demod_report_isSet.
Referenced by FreeDVDemod::webapiReportGet().
{
     this->free_dv_demod_report = free_dv_demod_report;
     this->m_free_dv_demod_report_isSet = true;
 }
setFreeDvModReport()
void SWGSDRangel::SWGChannelReport::setFreeDvModReport (SWGFreeDVModReport * free_dv_mod_report)
Definition at line 409 of file SWGChannelReport.cpp.
References free_dv_mod_report, and m_free_dv_mod_report_isSet.
Referenced by FreeDVMod::webapiReportGet().
{
     this->free_dv_mod_report = free_dv_mod_report;
     this->m_free_dv_mod_report_isSet = true;
 }
setFreqTrackerReport()
void SWGSDRangel::SWGChannelReport::setFreqTrackerReport (SWGFreqTrackerReport * freq_tracker_report)
Definition at line 419 of file SWGChannelReport.cpp.
References freq_tracker_report, and m_freq_tracker_report_isSet.
Referenced by FreqTracker::webapiReportGet().
{
     this->freq_tracker_report = freq_tracker_report;
     this->m_freq_tracker_report_isSet = true;
 }
setNfmDemodReport()
void SWGSDRangel::SWGChannelReport::setNfmDemodReport (SWGNFMDemodReport * nfm_demod_report)
Definition at line 429 of file SWGChannelReport.cpp.
References m_nfm_demod_report_isSet, and nfm_demod_report.
Referenced by WebAPIRequestMapper::resetChannelReport(), and NFMDemod::webapiReportGet().
{
     this->nfm_demod_report = nfm_demod_report;
     this->m_nfm_demod_report_isSet = true;
 }
setNfmModReport()
void SWGSDRangel::SWGChannelReport::setNfmModReport (SWGNFMModReport * nfm_mod_report)
Definition at line 439 of file SWGChannelReport.cpp.
References m_nfm_mod_report_isSet, and nfm_mod_report.
Referenced by WebAPIRequestMapper::resetChannelReport(), and NFMMod::webapiReportGet().
{
     this->nfm_mod_report = nfm_mod_report;
     this->m_nfm_mod_report_isSet = true;
 }
setRemoteSourceReport()
void SWGSDRangel::SWGChannelReport::setRemoteSourceReport (SWGRemoteSourceReport * remote_source_report)
Definition at line 459 of file SWGChannelReport.cpp.
References m_remote_source_report_isSet, and remote_source_report.
Referenced by WebAPIRequestMapper::resetChannelReport(), and RemoteSource::webapiReportGet().
{
     this->remote_source_report = remote_source_report;
     this->m_remote_source_report_isSet = true;
 }
setSsbDemodReport()
void SWGSDRangel::SWGChannelReport::setSsbDemodReport (SWGSSBDemodReport * ssb_demod_report)
Definition at line 449 of file SWGChannelReport.cpp.
References m_ssb_demod_report_isSet, and ssb_demod_report.
Referenced by WebAPIRequestMapper::resetChannelReport(), and SSBDemod::webapiReportGet().
{
     this->ssb_demod_report = ssb_demod_report;
     this->m_ssb_demod_report_isSet = true;
 }
setSsbModReport()
void SWGSDRangel::SWGChannelReport::setSsbModReport (SWGSSBModReport * ssb_mod_report)
Definition at line 469 of file SWGChannelReport.cpp.
References m_ssb_mod_report_isSet, and ssb_mod_report.
Referenced by WebAPIRequestMapper::resetChannelReport(), and SSBMod::webapiReportGet().
{
     this->ssb_mod_report = ssb_mod_report;
     this->m_ssb_mod_report_isSet = true;
 }
setUdpSinkReport()
void SWGSDRangel::SWGChannelReport::setUdpSinkReport (SWGUDPSinkReport * udp_sink_report)
Definition at line 489 of file SWGChannelReport.cpp.
References m_udp_sink_report_isSet, and udp_sink_report.
Referenced by WebAPIRequestMapper::resetChannelReport(), and UDPSink::webapiReportGet().
{
     this->udp_sink_report = udp_sink_report;
     this->m_udp_sink_report_isSet = true;
 }
setUdpSourceReport()
void SWGSDRangel::SWGChannelReport::setUdpSourceReport (SWGUDPSourceReport * udp_source_report)
Definition at line 479 of file SWGChannelReport.cpp.
References m_udp_source_report_isSet, and udp_source_report.
Referenced by WebAPIRequestMapper::resetChannelReport(), and UDPSource::webapiReportGet().
{
     this->udp_source_report = udp_source_report;
     this->m_udp_source_report_isSet = true;
 }
setWfmDemodReport()
void SWGSDRangel::SWGChannelReport::setWfmDemodReport (SWGWFMDemodReport * wfm_demod_report)
Definition at line 499 of file SWGChannelReport.cpp.
References m_wfm_demod_report_isSet, and wfm_demod_report.
Referenced by WebAPIRequestMapper::resetChannelReport(), and WFMDemod::webapiReportGet().
{
     this->wfm_demod_report = wfm_demod_report;
     this->m_wfm_demod_report_isSet = true;
 }
setWfmModReport()
void SWGSDRangel::SWGChannelReport::setWfmModReport (SWGWFMModReport * wfm_mod_report)
Definition at line 509 of file SWGChannelReport.cpp.
References m_wfm_mod_report_isSet, and wfm_mod_report.
Referenced by WebAPIRequestMapper::resetChannelReport(), and WFMMod::webapiReportGet().
{
     this->wfm_mod_report = wfm_mod_report;
     this->m_wfm_mod_report_isSet = true;
 }
Member Data Documentation
am_demod_report
SWGAMDemodReport* SWGSDRangel::SWGChannelReport::am_demod_report private
Definition at line 133 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getAmDemodReport(), init(), isSet(), setAmDemodReport(), and SWGChannelReport().
am_mod_report
SWGAMModReport* SWGSDRangel::SWGChannelReport::am_mod_report private
Definition at line 136 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getAmModReport(), init(), isSet(), setAmModReport(), and SWGChannelReport().
atv_mod_report
SWGATVModReport* SWGSDRangel::SWGChannelReport::atv_mod_report private
Definition at line 139 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getAtvModReport(), init(), isSet(), setAtvModReport(), and SWGChannelReport().
bfm_demod_report
SWGBFMDemodReport* SWGSDRangel::SWGChannelReport::bfm_demod_report private
Definition at line 142 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getBfmDemodReport(), init(), isSet(), setBfmDemodReport(), and SWGChannelReport().
channel_type
QString* SWGSDRangel::SWGChannelReport::channel_type private
Definition at line 127 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getChannelType(), init(), isSet(), setChannelType(), and SWGChannelReport().
direction
qint32 SWGSDRangel::SWGChannelReport::direction private
Definition at line 130 of file SWGChannelReport.h.
Referenced by asJsonObject(), fromJsonObject(), getDirection(), init(), setDirection(), and SWGChannelReport().
dsd_demod_report
SWGDSDDemodReport* SWGSDRangel::SWGChannelReport::dsd_demod_report private
Definition at line 145 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getDsdDemodReport(), init(), isSet(), setDsdDemodReport(), and SWGChannelReport().
file_source_report
SWGFileSourceReport* SWGSDRangel::SWGChannelReport::file_source_report private
Definition at line 148 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFileSourceReport(), init(), isSet(), setFileSourceReport(), and SWGChannelReport().
free_dv_demod_report
SWGFreeDVDemodReport* SWGSDRangel::SWGChannelReport::free_dv_demod_report private
Definition at line 151 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFreeDvDemodReport(), init(), isSet(), setFreeDvDemodReport(), and SWGChannelReport().
free_dv_mod_report
SWGFreeDVModReport* SWGSDRangel::SWGChannelReport::free_dv_mod_report private
Definition at line 154 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFreeDvModReport(), init(), isSet(), setFreeDvModReport(), and SWGChannelReport().
freq_tracker_report
SWGFreqTrackerReport* SWGSDRangel::SWGChannelReport::freq_tracker_report private
Definition at line 157 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFreqTrackerReport(), init(), isSet(), setFreqTrackerReport(), and SWGChannelReport().
m_am_demod_report_isSet
bool SWGSDRangel::SWGChannelReport::m_am_demod_report_isSet private
Definition at line 134 of file SWGChannelReport.h.
Referenced by init(), setAmDemodReport(), and SWGChannelReport().
m_am_mod_report_isSet
bool SWGSDRangel::SWGChannelReport::m_am_mod_report_isSet private
Definition at line 137 of file SWGChannelReport.h.
Referenced by init(), setAmModReport(), and SWGChannelReport().
m_atv_mod_report_isSet
bool SWGSDRangel::SWGChannelReport::m_atv_mod_report_isSet private
Definition at line 140 of file SWGChannelReport.h.
Referenced by init(), setAtvModReport(), and SWGChannelReport().
m_bfm_demod_report_isSet
bool SWGSDRangel::SWGChannelReport::m_bfm_demod_report_isSet private
Definition at line 143 of file SWGChannelReport.h.
Referenced by init(), setBfmDemodReport(), and SWGChannelReport().
m_channel_type_isSet
bool SWGSDRangel::SWGChannelReport::m_channel_type_isSet private
Definition at line 128 of file SWGChannelReport.h.
Referenced by init(), setChannelType(), and SWGChannelReport().
m_direction_isSet
bool SWGSDRangel::SWGChannelReport::m_direction_isSet private
Definition at line 131 of file SWGChannelReport.h.
Referenced by asJsonObject(), init(), isSet(), setDirection(), and SWGChannelReport().
m_dsd_demod_report_isSet
bool SWGSDRangel::SWGChannelReport::m_dsd_demod_report_isSet private
Definition at line 146 of file SWGChannelReport.h.
Referenced by init(), setDsdDemodReport(), and SWGChannelReport().
m_file_source_report_isSet
bool SWGSDRangel::SWGChannelReport::m_file_source_report_isSet private
Definition at line 149 of file SWGChannelReport.h.
Referenced by init(), setFileSourceReport(), and SWGChannelReport().
m_free_dv_demod_report_isSet
bool SWGSDRangel::SWGChannelReport::m_free_dv_demod_report_isSet private
Definition at line 152 of file SWGChannelReport.h.
Referenced by init(), setFreeDvDemodReport(), and SWGChannelReport().
m_free_dv_mod_report_isSet
bool SWGSDRangel::SWGChannelReport::m_free_dv_mod_report_isSet private
Definition at line 155 of file SWGChannelReport.h.
Referenced by init(), setFreeDvModReport(), and SWGChannelReport().
m_freq_tracker_report_isSet
bool SWGSDRangel::SWGChannelReport::m_freq_tracker_report_isSet private
Definition at line 158 of file SWGChannelReport.h.
Referenced by init(), setFreqTrackerReport(), and SWGChannelReport().
m_nfm_demod_report_isSet
bool SWGSDRangel::SWGChannelReport::m_nfm_demod_report_isSet private
Definition at line 161 of file SWGChannelReport.h.
Referenced by init(), setNfmDemodReport(), and SWGChannelReport().
m_nfm_mod_report_isSet
bool SWGSDRangel::SWGChannelReport::m_nfm_mod_report_isSet private
Definition at line 164 of file SWGChannelReport.h.
Referenced by init(), setNfmModReport(), and SWGChannelReport().
m_remote_source_report_isSet
bool SWGSDRangel::SWGChannelReport::m_remote_source_report_isSet private
Definition at line 170 of file SWGChannelReport.h.
Referenced by init(), setRemoteSourceReport(), and SWGChannelReport().
m_ssb_demod_report_isSet
bool SWGSDRangel::SWGChannelReport::m_ssb_demod_report_isSet private
Definition at line 167 of file SWGChannelReport.h.
Referenced by init(), setSsbDemodReport(), and SWGChannelReport().
m_ssb_mod_report_isSet
bool SWGSDRangel::SWGChannelReport::m_ssb_mod_report_isSet private
Definition at line 173 of file SWGChannelReport.h.
Referenced by init(), setSsbModReport(), and SWGChannelReport().
m_udp_sink_report_isSet
bool SWGSDRangel::SWGChannelReport::m_udp_sink_report_isSet private
Definition at line 179 of file SWGChannelReport.h.
Referenced by init(), setUdpSinkReport(), and SWGChannelReport().
m_udp_source_report_isSet
bool SWGSDRangel::SWGChannelReport::m_udp_source_report_isSet private
Definition at line 176 of file SWGChannelReport.h.
Referenced by init(), setUdpSourceReport(), and SWGChannelReport().
m_wfm_demod_report_isSet
bool SWGSDRangel::SWGChannelReport::m_wfm_demod_report_isSet private
Definition at line 182 of file SWGChannelReport.h.
Referenced by init(), setWfmDemodReport(), and SWGChannelReport().
m_wfm_mod_report_isSet
bool SWGSDRangel::SWGChannelReport::m_wfm_mod_report_isSet private
Definition at line 185 of file SWGChannelReport.h.
Referenced by init(), setWfmModReport(), and SWGChannelReport().
nfm_demod_report
SWGNFMDemodReport* SWGSDRangel::SWGChannelReport::nfm_demod_report private
Definition at line 160 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getNfmDemodReport(), init(), isSet(), setNfmDemodReport(), and SWGChannelReport().
nfm_mod_report
SWGNFMModReport* SWGSDRangel::SWGChannelReport::nfm_mod_report private
Definition at line 163 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getNfmModReport(), init(), isSet(), setNfmModReport(), and SWGChannelReport().
remote_source_report
SWGRemoteSourceReport* SWGSDRangel::SWGChannelReport::remote_source_report private
Definition at line 169 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getRemoteSourceReport(), init(), isSet(), setRemoteSourceReport(), and SWGChannelReport().
ssb_demod_report
SWGSSBDemodReport* SWGSDRangel::SWGChannelReport::ssb_demod_report private
Definition at line 166 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSsbDemodReport(), init(), isSet(), setSsbDemodReport(), and SWGChannelReport().
ssb_mod_report
SWGSSBModReport* SWGSDRangel::SWGChannelReport::ssb_mod_report private
Definition at line 172 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSsbModReport(), init(), isSet(), setSsbModReport(), and SWGChannelReport().
udp_sink_report
SWGUDPSinkReport* SWGSDRangel::SWGChannelReport::udp_sink_report private
Definition at line 178 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getUdpSinkReport(), init(), isSet(), setUdpSinkReport(), and SWGChannelReport().
udp_source_report
SWGUDPSourceReport* SWGSDRangel::SWGChannelReport::udp_source_report private
Definition at line 175 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getUdpSourceReport(), init(), isSet(), setUdpSourceReport(), and SWGChannelReport().
wfm_demod_report
SWGWFMDemodReport* SWGSDRangel::SWGChannelReport::wfm_demod_report private
Definition at line 181 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getWfmDemodReport(), init(), isSet(), setWfmDemodReport(), and SWGChannelReport().
wfm_mod_report
SWGWFMModReport* SWGSDRangel::SWGChannelReport::wfm_mod_report private
Definition at line 184 of file SWGChannelReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getWfmModReport(), init(), isSet(), setWfmModReport(), and SWGChannelReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGChannelReport.h
swagger/sdrangel/code/qt5/client/SWGChannelReport.cpp