SDRAngel: AMMod::MsgConfigureAMMod Class Reference
AMMod::MsgConfigureAMMod Class Reference
#include <ammod.h>
Public Member Functions
const AMModSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureAMMod * create (const AMModSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureAMMod (const AMModSettings &settings, bool force)
Private Attributes
AMModSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 51 of file ammod.h.
Constructor & Destructor Documentation
MsgConfigureAMMod()
AMMod::MsgConfigureAMMod::MsgConfigureAMMod (const AMModSettings & settings, bool force) inline private
Definition at line 67 of file ammod.h.
Referenced by create().
                                                                      :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureAMMod* AMMod::MsgConfigureAMMod::create (const AMModSettings & settings, bool force) inline static
Definition at line 58 of file ammod.h.
References MsgConfigureAMMod().
Referenced by AMModGUI::applySettings(), AMMod::deserialize(), and AMMod::webapiSettingsPutPatch().
         {
             return new MsgConfigureAMMod(settings, force);
         }
getForce()
bool AMMod::MsgConfigureAMMod::getForce () const inline
Definition at line 56 of file ammod.h.
References m_force.
Referenced by AMMod::handleMessage().
 { return m_force; }
getSettings()
const AMModSettings& AMMod::MsgConfigureAMMod::getSettings () const inline
Definition at line 55 of file ammod.h.
References m_settings.
Referenced by AMModGUI::handleMessage(), and AMMod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool AMMod::MsgConfigureAMMod::m_force private
Definition at line 65 of file ammod.h.
Referenced by getForce().
m_settings
AMModSettings AMMod::MsgConfigureAMMod::m_settings private
Definition at line 64 of file ammod.h.
Referenced by AMMod::getCenterFrequency(), getSettings(), AMMod::getStreamCenterFrequency(), and AMMod::getTitle().
The documentation for this class was generated from the following file:
plugins/channeltx/modam/ammod.h