SDRAngel: LocalInput Class Reference
LocalInput Class Reference
#include <localinput.h>
Classes
class MsgConfigureLocalInput
class MsgFileRecord
class MsgReportSampleRateAndFrequency
class MsgStartStop
Public Member Functions
LocalInput (DeviceAPI *deviceAPI)
virtual ~LocalInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applySettings (const LocalInputSettings &settings, bool force=false)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const LocalInputSettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const LocalInputSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
LocalInputSettings m_settings
qint64 m_centerFrequency
int m_sampleRate
QString m_remoteAddress
QString m_deviceDescription
FileRecord * m_fileSink
File sink to record device I/Q output.
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 39 of file localinput.h.
Constructor & Destructor Documentation
LocalInput()
LocalInput::LocalInput (DeviceAPI * deviceAPI)
Definition at line 43 of file localinput.cpp.
References arg().
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
                                            :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_centerFrequency(0),
     m_deviceDescription("LocalInput")
 {
     m_sampleFifo.setSize(96000 * 4);
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~LocalInput()
LocalInput::~LocalInput () virtual
Definition at line 59 of file localinput.cpp.
References m_deviceAPI, m_fileSink, m_networkManager, networkManagerFinished(), DeviceAPI::removeAncillarySink(), and stop().
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     stop();
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
 }
Member Function Documentation
applySettings()
void LocalInput::applySettings (const LocalInputSettings & settings, bool force = false) private
Definition at line 229 of file localinput.cpp.
References DeviceAPI::configureCorrections(), LocalInputSettings::m_dcBlock, m_deviceAPI, LocalInputSettings::m_fileRecordName, LocalInputSettings::m_iqCorrection, m_mutex, m_remoteAddress, LocalInputSettings::m_reverseAPIAddress, LocalInputSettings::m_reverseAPIDeviceIndex, LocalInputSettings::m_reverseAPIPort, m_settings, LocalInputSettings::m_useReverseAPI, and webapiReverseSendSettings().
Referenced by handleMessage(), and init().
 {
     QMutexLocker mutexLocker(&m_mutex);
     std::ostringstream os;
     QString remoteAddress;
     QList<QString> reverseAPIKeys;
     if ((m_settings.m_dcBlock != settings.m_dcBlock) || force) {
         reverseAPIKeys.append("dcBlock");
     }
     if ((m_settings.m_iqCorrection != settings.m_iqCorrection) || force) {
         reverseAPIKeys.append("iqCorrection");
     }
     if ((m_settings.m_fileRecordName != settings.m_fileRecordName) || force) {
         reverseAPIKeys.append("fileRecordName");
     }
     if ((m_settings.m_dcBlock != settings.m_dcBlock) || (m_settings.m_iqCorrection != settings.m_iqCorrection) || force)
     {
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqCorrection);
         qDebug("LocalInput::applySettings: corrections: DC block: %s IQ imbalance: %s",
                 settings.m_dcBlock ? "true" : "false",
                 settings.m_iqCorrection ? "true" : "false");
     }
     mutexLocker.unlock();
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     m_remoteAddress = remoteAddress;
     qDebug() << "LocalInput::applySettings: "
             << " m_dcBlock: " << m_settings.m_dcBlock
             << " m_iqCorrection: " << m_settings.m_iqCorrection
             << " m_fileRecordName: " << m_settings.m_fileRecordName
             << " m_remoteAddress: " << m_remoteAddress;
 }
deserialize()
bool LocalInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 94 of file localinput.cpp.
References LocalInput::MsgConfigureLocalInput::create(), LocalInputSettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and LocalInputSettings::resetToDefaults().
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureLocalInput* message = MsgConfigureLocalInput::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureLocalInput* messageToGUI = MsgConfigureLocalInput::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void LocalInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 68 of file localinput.cpp.
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     delete this;
 }
getCenterFrequency()
quint64 LocalInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 145 of file localinput.cpp.
References m_centerFrequency.
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     return m_centerFrequency;
 }
getDeviceDescription()
const QString & LocalInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 121 of file localinput.cpp.
References m_deviceDescription.
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     return m_deviceDescription;
 }
getSampleRate()
int LocalInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 126 of file localinput.cpp.
References m_sampleRate.
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     return m_sampleRate;
 }
handleMessage()
bool LocalInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 164 of file localinput.cpp.
References applySettings(), FileRecord::genUniqueFileName(), DeviceAPI::getDeviceUID(), LocalInput::MsgConfigureLocalInput::getForce(), Message::getIdentifier(), LocalInput::MsgConfigureLocalInput::getSettings(), LocalInput::MsgFileRecord::getStartStop(), LocalInput::MsgStartStop::getStartStop(), FileRecord::handleMessage(), DeviceAPI::initDeviceEngine(), m_deviceAPI, LocalInputSettings::m_fileRecordName, m_fileSink, m_settings, LocalInputSettings::m_useReverseAPI, Message::match(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     if (DSPSignalNotification::match(message))
     {
         DSPSignalNotification& notif = (DSPSignalNotification&) message;
         return m_fileSink->handleMessage(notif); // forward to file sink
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "LocalInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "LocalInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else if (MsgConfigureLocalInput::match(message))
     {
         qDebug() << "LocalInput::handleMessage:" << message.getIdentifier();
         MsgConfigureLocalInput& conf = (MsgConfigureLocalInput&) message;
         applySettings(conf.getSettings(), conf.getForce());
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void LocalInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 73 of file localinput.cpp.
References applySettings(), and m_settings.
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void LocalInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 465 of file localinput.cpp.
Referenced by ~LocalInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "LocalInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("LocalInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
serialize()
QByteArray LocalInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 89 of file localinput.cpp.
References m_settings, and LocalInputSettings::serialize().
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void LocalInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 150 of file localinput.cpp.
References LocalInput::MsgReportSampleRateAndFrequency::create(), DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceSampleSource::getMessageQueueToGUI(), m_centerFrequency, m_deviceAPI, m_sampleRate, and MessageQueue::push().
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     m_centerFrequency = centerFrequency;
     DSPSignalNotification *notif = new DSPSignalNotification(m_sampleRate, m_centerFrequency); // Frequency in Hz for the DSP engine
     m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     if (getMessageQueueToGUI())
     {
         MsgReportSampleRateAndFrequency *msg = MsgReportSampleRateAndFrequency::create(m_sampleRate, m_centerFrequency);
         getMessageQueueToGUI()->push(msg);
     }
 }
setMessageQueueToGUI()
void LocalInput::setMessageQueueToGUI (MessageQueue * queue) virtual
Implements DeviceSampleSource.
Definition at line 116 of file localinput.cpp.
References DeviceSampleSource::m_guiMessageQueue.
Referenced by LocalInputGui::LocalInputGui(), and LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     m_guiMessageQueue = queue;
 }
setSampleRate()
void LocalInput::setSampleRate (int sampleRate) virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 131 of file localinput.cpp.
References LocalInput::MsgReportSampleRateAndFrequency::create(), DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceSampleSource::getMessageQueueToGUI(), m_centerFrequency, m_deviceAPI, m_sampleRate, and MessageQueue::push().
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     m_sampleRate = sampleRate;
     DSPSignalNotification *notif = new DSPSignalNotification(m_sampleRate, m_centerFrequency); // Frequency in Hz for the DSP engine
     m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     if (getMessageQueueToGUI())
     {
         MsgReportSampleRateAndFrequency *msg = MsgReportSampleRateAndFrequency::create(m_sampleRate, m_centerFrequency);
         getMessageQueueToGUI()->push(msg);
     }
 }
start()
bool LocalInput::start () virtual
Implements DeviceSampleSource.
Definition at line 78 of file localinput.cpp.
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     qDebug() << "LocalInput::start";
     return true;
 }
stop()
void LocalInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 84 of file localinput.cpp.
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency(), and ~LocalInput().
 {
     qDebug() << "LocalInput::stop";
 }
webapiFormatDeviceReport()
void LocalInput::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 392 of file localinput.cpp.
References SWGSDRangel::SWGDeviceReport::getLocalInputReport(), m_centerFrequency, m_sampleRate, SWGSDRangel::SWGLocalInputReport::setCenterFrequency(), and SWGSDRangel::SWGLocalInputReport::setSampleRate().
Referenced by webapiReportGet().
 {
     response.getLocalInputReport()->setCenterFrequency(m_centerFrequency);
     response.getLocalInputReport()->setSampleRate(m_sampleRate);
 }
webapiFormatDeviceSettings()
void LocalInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const LocalInputSettings & settings) private
Definition at line 358 of file localinput.cpp.
References SWGSDRangel::SWGLocalInputSettings::getFileRecordName(), SWGSDRangel::SWGDeviceSettings::getLocalInputSettings(), SWGSDRangel::SWGLocalInputSettings::getReverseApiAddress(), LocalInputSettings::m_dcBlock, LocalInputSettings::m_fileRecordName, LocalInputSettings::m_iqCorrection, LocalInputSettings::m_reverseAPIAddress, LocalInputSettings::m_reverseAPIDeviceIndex, LocalInputSettings::m_reverseAPIPort, LocalInputSettings::m_useReverseAPI, SWGSDRangel::SWGLocalInputSettings::setDcBlock(), SWGSDRangel::SWGLocalInputSettings::setFileRecordName(), SWGSDRangel::SWGLocalInputSettings::setIqCorrection(), SWGSDRangel::SWGLocalInputSettings::setReverseApiAddress(), SWGSDRangel::SWGLocalInputSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGLocalInputSettings::setReverseApiPort(), and SWGSDRangel::SWGLocalInputSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getLocalInputSettings()->setDcBlock(settings.m_dcBlock ? 1 : 0);
     response.getLocalInputSettings()->setIqCorrection(settings.m_iqCorrection);
     if (response.getLocalInputSettings()->getFileRecordName()) {
         *response.getLocalInputSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getLocalInputSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getLocalInputSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getLocalInputSettings()->getReverseApiAddress()) {
         *response.getLocalInputSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getLocalInputSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getLocalInputSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getLocalInputSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int LocalInput::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 381 of file localinput.cpp.
References SWGSDRangel::SWGDeviceReport::getLocalInputReport(), SWGSDRangel::SWGLocalInputReport::init(), SWGSDRangel::SWGDeviceReport::setLocalInputReport(), and webapiFormatDeviceReport().
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     (void) errorMessage;
     response.setLocalInputReport(new SWGSDRangel::SWGLocalInputReport());
     response.getLocalInputReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void LocalInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const LocalInputSettings & settings, bool force) private
Definition at line 398 of file localinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getLocalInputSettings(), LocalInputSettings::m_dcBlock, m_deviceAPI, LocalInputSettings::m_fileRecordName, LocalInputSettings::m_iqCorrection, m_networkManager, m_networkRequest, LocalInputSettings::m_reverseAPIAddress, LocalInputSettings::m_reverseAPIDeviceIndex, LocalInputSettings::m_reverseAPIPort, SWGSDRangel::SWGLocalInputSettings::setDcBlock(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGLocalInputSettings::setFileRecordName(), SWGSDRangel::SWGLocalInputSettings::setIqCorrection(), SWGSDRangel::SWGDeviceSettings::setLocalInputSettings(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("LocalInput"));
     swgDeviceSettings->setLocalInputSettings(new SWGSDRangel::SWGLocalInputSettings());
     SWGSDRangel::SWGLocalInputSettings *swgLocalInputSettings = swgDeviceSettings->getLocalInputSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("dcBlock") || force) {
         swgLocalInputSettings->setDcBlock(settings.m_dcBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("iqCorrection") || force) {
         swgLocalInputSettings->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgLocalInputSettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void LocalInput::webapiReverseSendStartStop (bool start) private
Definition at line 437 of file localinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, LocalInputSettings::m_reverseAPIAddress, LocalInputSettings::m_reverseAPIDeviceIndex, LocalInputSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("LocalInput"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int LocalInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 284 of file localinput.cpp.
References LocalInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int LocalInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 275 of file localinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int LocalInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 303 of file localinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getLocalInputSettings(), SWGSDRangel::SWGLocalInputSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setLocalInputSettings(), and webapiFormatDeviceSettings().
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     (void) errorMessage;
     response.setLocalInputSettings(new SWGSDRangel::SWGLocalInputSettings());
     response.getLocalInputSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int LocalInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 314 of file localinput.cpp.
References LocalInput::MsgConfigureLocalInput::create(), SWGSDRangel::SWGLocalInputSettings::getDcBlock(), SWGSDRangel::SWGLocalInputSettings::getFileRecordName(), SWGSDRangel::SWGLocalInputSettings::getIqCorrection(), SWGSDRangel::SWGDeviceSettings::getLocalInputSettings(), SWGSDRangel::SWGLocalInputSettings::getReverseApiAddress(), SWGSDRangel::SWGLocalInputSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGLocalInputSettings::getReverseApiPort(), SWGSDRangel::SWGLocalInputSettings::getUseReverseApi(), LocalInputSettings::m_dcBlock, LocalInputSettings::m_fileRecordName, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, LocalInputSettings::m_iqCorrection, LocalInputSettings::m_reverseAPIAddress, LocalInputSettings::m_reverseAPIDeviceIndex, LocalInputSettings::m_reverseAPIPort, m_settings, LocalInputSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     (void) errorMessage;
     LocalInputSettings settings = m_settings;
     if (deviceSettingsKeys.contains("dcBlock")) {
         settings.m_dcBlock = response.getLocalInputSettings()->getDcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("iqCorrection")) {
         settings.m_iqCorrection = response.getLocalInputSettings()->getIqCorrection() != 0;
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getLocalInputSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getLocalInputSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getLocalInputSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getLocalInputSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getLocalInputSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureLocalInput *msg = MsgConfigureLocalInput::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureLocalInput *msgToGUI = MsgConfigureLocalInput::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_centerFrequency
qint64 LocalInput::m_centerFrequency private
Definition at line 172 of file localinput.h.
Referenced by LocalInput::MsgReportSampleRateAndFrequency::getCenterFrequency(), getCenterFrequency(), setCenterFrequency(), setSampleRate(), and webapiFormatDeviceReport().
m_deviceAPI
DeviceAPI* LocalInput::m_deviceAPI private
Definition at line 169 of file localinput.h.
Referenced by applySettings(), handleMessage(), setCenterFrequency(), setSampleRate(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~LocalInput().
m_deviceDescription
QString LocalInput::m_deviceDescription private
Definition at line 175 of file localinput.h.
Referenced by getDeviceDescription().
m_fileSink
FileRecord* LocalInput::m_fileSink private
File sink to record device I/Q output.
Definition at line 176 of file localinput.h.
Referenced by handleMessage(), and ~LocalInput().
m_mutex
QMutex LocalInput::m_mutex private
Definition at line 170 of file localinput.h.
Referenced by applySettings().
m_networkManager
QNetworkAccessManager* LocalInput::m_networkManager private
Definition at line 177 of file localinput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~LocalInput().
m_networkRequest
QNetworkRequest LocalInput::m_networkRequest private
Definition at line 178 of file localinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_remoteAddress
QString LocalInput::m_remoteAddress private
Definition at line 174 of file localinput.h.
Referenced by applySettings().
m_sampleRate
int LocalInput::m_sampleRate private
Definition at line 173 of file localinput.h.
Referenced by LocalInput::MsgReportSampleRateAndFrequency::getSampleRate(), getSampleRate(), setCenterFrequency(), setSampleRate(), and webapiFormatDeviceReport().
m_settings
LocalInputSettings LocalInput::m_settings private
Definition at line 171 of file localinput.h.
Referenced by applySettings(), deserialize(), handleMessage(), init(), serialize(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
The documentation for this class was generated from the following files:
plugins/samplesource/localinput/localinput.h
plugins/samplesource/localinput/localinput.cpp