SDRAngel: HackRFOutput::MsgReportHackRF Class Reference
HackRFOutput::MsgReportHackRF Class Reference
#include <hackrfoutput.h>
Static Public Member Functions
static MsgReportHackRF * create ()
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportHackRF ()
Additional Inherited Members
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 81 of file hackrfoutput.h.
Constructor & Destructor Documentation
MsgReportHackRF()
HackRFOutput::MsgReportHackRF::MsgReportHackRF () inline protected
Definition at line 93 of file hackrfoutput.h.
References HackRFOutput::deserialize(), HackRFOutput::destroy(), HackRFOutput::HackRFOutput(), HackRFOutput::init(), HackRFOutput::serialize(), HackRFOutput::start(), HackRFOutput::stop(), and HackRFOutput::~HackRFOutput().
                           :
             Message()
         { }
Member Function Documentation
create()
static MsgReportHackRF* HackRFOutput::MsgReportHackRF::create () inline static
Definition at line 86 of file hackrfoutput.h.
         {
             return new MsgReportHackRF();
         }
The documentation for this class was generated from the following file:
plugins/samplesink/hackrfoutput/hackrfoutput.h