SDRAngel: SWGSDRangel::SWGSuccessResponse Class Reference
SWGSDRangel::SWGSuccessResponse Class Reference
#include <SWGSuccessResponse.h>
Public Member Functions
SWGSuccessResponse ()
SWGSuccessResponse (QString *json)
virtual ~SWGSuccessResponse ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGSuccessResponse * fromJson (QString &jsonString) override
QString * getMessage ()
void setMessage (QString *message)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * message
bool m_message_isSet
Detailed Description
Definition at line 32 of file SWGSuccessResponse.h.
Constructor & Destructor Documentation
SWGSuccessResponse() [1/2]
SWGSDRangel::SWGSuccessResponse::SWGSuccessResponse ()
Definition at line 30 of file SWGSuccessResponse.cpp.
References m_message_isSet, and message.
{
     message = nullptr;
     m_message_isSet = false;
 }
SWGSuccessResponse() [2/2]
SWGSDRangel::SWGSuccessResponse::SWGSuccessResponse (QString * json)
Definition at line 25 of file SWGSuccessResponse.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGSuccessResponse()
SWGSDRangel::SWGSuccessResponse::~SWGSuccessResponse () virtual
Definition at line 35 of file SWGSuccessResponse.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGSuccessResponse::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 68 of file SWGSuccessResponse.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::devicesetChannelIndexService(), WebAPIRequestMapper::devicesetChannelService(), WebAPIRequestMapper::devicesetFocusService(), WebAPIRequestMapper::instanceAMBEDevicesService(), WebAPIRequestMapper::instanceAudioInputCleanupService(), WebAPIRequestMapper::instanceAudioOutputCleanupService(), WebAPIRequestMapper::instanceDeviceSetService(), and WebAPIRequestMapper::instanceSummaryService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGSuccessResponse::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 79 of file SWGSuccessResponse.cpp.
References message, and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(message != nullptr && *message != QString("")){
         toJsonValue(QString("message"), message, obj, QString("QString"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGSuccessResponse::cleanup ()
Definition at line 46 of file SWGSuccessResponse.cpp.
References message.
Referenced by ~SWGSuccessResponse().
{
     if(message != nullptr) {
         delete message;
     }
 }
fromJson()
SWGSuccessResponse * SWGSDRangel::SWGSuccessResponse::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 53 of file SWGSuccessResponse.cpp.
References fromJsonObject().
Referenced by SWGSuccessResponse().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGSuccessResponse::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 62 of file SWGSuccessResponse.cpp.
References message, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&message, pJson["message"], "QString", "QString");
 }
getMessage()
QString * SWGSDRangel::SWGSuccessResponse::getMessage ()
Definition at line 89 of file SWGSuccessResponse.cpp.
References message.
Referenced by WebAPIAdapterGUI::devicesetChannelDelete(), WebAPIAdapterSrv::devicesetChannelDelete(), WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterSrv::devicesetChannelPost(), WebAPIAdapterGUI::devicesetFocusPatch(), WebAPIAdapterGUI::instanceAMBEDevicesDelete(), WebAPIAdapterSrv::instanceAMBEDevicesDelete(), WebAPIAdapterSrv::instanceAudioInputCleanupPatch(), WebAPIAdapterGUI::instanceAudioInputCleanupPatch(), WebAPIAdapterGUI::instanceAudioOutputCleanupPatch(), WebAPIAdapterSrv::instanceAudioOutputCleanupPatch(), WebAPIAdapterSrv::instanceDelete(), WebAPIAdapterGUI::instanceDeviceSetDelete(), WebAPIAdapterSrv::instanceDeviceSetDelete(), WebAPIAdapterGUI::instanceDeviceSetPost(), and WebAPIAdapterSrv::instanceDeviceSetPost().
{
     return message;
 }
init()
void SWGSDRangel::SWGSuccessResponse::init ()
Definition at line 40 of file SWGSuccessResponse.cpp.
References m_message_isSet, and message.
Referenced by WebAPIAdapterGUI::devicesetChannelDelete(), WebAPIAdapterSrv::devicesetChannelDelete(), WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterSrv::devicesetChannelPost(), WebAPIAdapterGUI::devicesetFocusPatch(), WebAPIAdapterSrv::instanceAMBEDevicesDelete(), WebAPIAdapterGUI::instanceAMBEDevicesDelete(), WebAPIAdapterSrv::instanceAudioInputCleanupPatch(), WebAPIAdapterGUI::instanceAudioInputCleanupPatch(), WebAPIAdapterGUI::instanceAudioOutputCleanupPatch(), WebAPIAdapterSrv::instanceAudioOutputCleanupPatch(), WebAPIAdapterSrv::instanceDelete(), WebAPIAdapterGUI::instanceDeviceSetDelete(), WebAPIAdapterSrv::instanceDeviceSetDelete(), WebAPIAdapterGUI::instanceDeviceSetPost(), WebAPIAdapterSrv::instanceDeviceSetPost(), and SWGSuccessResponse().
{
     message = new QString("");
     m_message_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGSuccessResponse::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 100 of file SWGSuccessResponse.cpp.
References message.
{
     bool isObjectUpdated = false;
     do{
         if(message != nullptr && *message != QString("")){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setMessage()
void SWGSDRangel::SWGSuccessResponse::setMessage (QString * message)
Definition at line 93 of file SWGSuccessResponse.cpp.
References m_message_isSet, and message.
{
     this->message = message;
     this->m_message_isSet = true;
 }
Member Data Documentation
m_message_isSet
bool SWGSDRangel::SWGSuccessResponse::m_message_isSet private
Definition at line 53 of file SWGSuccessResponse.h.
Referenced by init(), setMessage(), and SWGSuccessResponse().
message
QString* SWGSDRangel::SWGSuccessResponse::message private
Definition at line 52 of file SWGSuccessResponse.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getMessage(), init(), isSet(), setMessage(), and SWGSuccessResponse().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGSuccessResponse.h
swagger/sdrangel/code/qt5/client/SWGSuccessResponse.cpp