SDRAngel: SecondOrderRecursiveFilter Class Reference
SecondOrderRecursiveFilter Class Reference
#include <recursivefilters.h>
Public Member Functions
SecondOrderRecursiveFilter (float samplingFrequency, float centerFrequency, float r)
~SecondOrderRecursiveFilter ()
void setFrequencies (float samplingFrequency, float centerFrequency)
void setR (float r)
short run (short sample)
float run (float sample)
Private Member Functions
void init ()
Private Attributes
float m_r
float m_frequencyRatio
float m_f
float m_v [3]
Detailed Description
: This is a second order bandpass filter using recursive method. r is in range ]0..1[ the higher the steeper the filter. inspired by:http://www.ece.umd.edu/~tretter/commlab/c6713slides/FSKSlides.pdf
Definition at line 27 of file recursivefilters.h.
Constructor & Destructor Documentation
SecondOrderRecursiveFilter()
SecondOrderRecursiveFilter::SecondOrderRecursiveFilter (float samplingFrequency, float centerFrequency, float r)
Definition at line 24 of file recursivefilters.cpp.
References init().
                                                                                                               :
         m_r(r),
         m_frequencyRatio(centerFrequency/samplingFrequency),
         m_f(cos(2.0*M_PI*(m_frequencyRatio)))
 {
     init();
 }
~SecondOrderRecursiveFilter()
SecondOrderRecursiveFilter::~SecondOrderRecursiveFilter ()
Definition at line 32 of file recursivefilters.cpp.
 {}
Member Function Documentation
init()
void SecondOrderRecursiveFilter::init () private
Definition at line 68 of file recursivefilters.cpp.
References i, and m_v.
Referenced by SecondOrderRecursiveFilter(), setFrequencies(), and setR().
 {
     for (int i = 0; i < 3; i++)
     {
         m_v[i] = 0.0f;
     }
 }
run() [1/2]
short SecondOrderRecursiveFilter::run (short sample)
Definition at line 48 of file recursivefilters.cpp.
References m_f, m_r, and m_v.
Referenced by ATVDemod::demod().
 {
     m_v[0] = ((1.0f - m_r) * (float) sample) + (2.0f * m_r * m_f * m_v[1]) - (m_r * m_r * m_v[2]);
     float y = m_v[0] - m_v[2];
     m_v[2] = m_v[1];
     m_v[1] = m_v[0];
     return (short) y;
 }
run() [2/2]
float SecondOrderRecursiveFilter::run (float sample)
Definition at line 58 of file recursivefilters.cpp.
References m_f, m_r, and m_v.
 {
     m_v[0] = ((1.0f - m_r) * sample) + (2.0f * m_r * m_f * m_v[1]) - (m_r * m_r * m_v[2]);
     float y = m_v[0] - m_v[2];
     m_v[2] = m_v[1];
     m_v[1] = m_v[0];
     return y;
 }
setFrequencies()
void SecondOrderRecursiveFilter::setFrequencies (float samplingFrequency, float centerFrequency)
Definition at line 35 of file recursivefilters.cpp.
References cos(), init(), m_f, m_frequencyRatio, and M_PI.
Referenced by ATVDemod::applySettings().
 {
     m_frequencyRatio = centerFrequency / samplingFrequency;
     m_f = cos(2.0*M_PI*m_frequencyRatio);
     init();
 }
setR()
void SecondOrderRecursiveFilter::setR (float r)
Definition at line 42 of file recursivefilters.cpp.
References init(), and m_r.
 {
     m_r = r;
     init();
 }
Member Data Documentation
m_f
float SecondOrderRecursiveFilter::m_f private
Definition at line 43 of file recursivefilters.h.
Referenced by run(), and setFrequencies().
m_frequencyRatio
float SecondOrderRecursiveFilter::m_frequencyRatio private
Definition at line 42 of file recursivefilters.h.
Referenced by setFrequencies().
m_r
float SecondOrderRecursiveFilter::m_r private
Definition at line 41 of file recursivefilters.h.
Referenced by run(), and setR().
m_v
float SecondOrderRecursiveFilter::m_v[3] private
Definition at line 44 of file recursivefilters.h.
Referenced by init(), and run().
The documentation for this class was generated from the following files:
sdrbase/dsp/recursivefilters.h
sdrbase/dsp/recursivefilters.cpp