SDRAngel: qtwebapp::Logger Class Reference
qtwebapp::Logger Class Reference
#include <logger.h>
Public Member Functions
Logger (QObject *parent)
Logger (const QString msgFormat="{timestamp} {type} {msg}", const QString timestampFormat="yyyy-MM-dd HH:mm:ss.zzz", const QtMsgType minLevel=QtDebugMsg, const int bufferSize=0, QObject *parent=0)
virtual ~Logger ()
virtual void log (const QtMsgType type, const QString &message, const QString &file="", const QString &function="", const int line=0)
void installMsgHandler ()
void setMinMessageLevel (const QtMsgType &minMsgLevel)
QtMsgType getMinMessageLevel () const
virtual void clear (const bool buffer=true, const bool variables=true)
Static Public Member Functions
static void set (const QString &name, const QString &value)
Protected Member Functions
virtual void write (const LogMessage *logMessage)
Protected Attributes
QString msgFormat
QString timestampFormat
QtMsgType minLevel
int bufferSize
Static Protected Attributes
static QMutex mutex
Static Private Member Functions
static void msgHandler (const QtMsgType type, const QString &message, const QString &file="", const QString &function="", const int line=0)
static void msgHandler4 (const QtMsgType type, const char *message)
Private Attributes
QThreadStorage< QList< LogMessage * > * > buffers
Static Private Attributes
static Logger * defaultLogger =0
static QThreadStorage< QHash< QString, QString > * > logVars
Detailed Description
Decorates and writes log messages to the console, stderr.
The decorator uses a predefined msgFormat string to enrich log messages with additional information (e.g. timestamp).
The msgFormat string and also the message text may contain additional variable names in the form {name} that are filled by values taken from a static thread local dictionary.
The logger keeps a configurable number of messages in a ring-buffer. A log message with a severity >= minLevel flushes the buffer, so the stored messages get written out. If the buffer is disabled, then only messages with severity >= minLevel are written out.
If you enable the buffer and use minLevel=2, then the application logs only errors together with some buffered debug messages. But as long no error occurs, nothing gets written out.
Each thread has it's own buffer.
The logger can be registered to handle messages from the static global functions qDebug(), qWarning(), qCritical() and qFatal().
See also
set() describes how to set logger variables
LogMessage for a description of the message decoration.
Warning
You should prefer a derived class, for example FileLogger, because logging to the console is less useful.
Definition at line 52 of file logger.h.
Constructor & Destructor Documentation
Logger() [1/2]
Logger::Logger (QObject * parent)
Constructor. Uses the same defaults as the other constructor.
Parameters
parent Parent object
Definition at line 25 of file logger.cpp.
Referenced by qtwebapp::LoggerWithFile::LoggerWithFile().
     : QObject(parent),
     msgFormat("{timestamp} {type} {msg}"),
     timestampFormat("yyyy-MM-dd HH:mm:ss.zzz"),
     minLevel(QtDebugMsg),
     bufferSize(0)
     {}
Logger() [2/2]
Logger::Logger (const QString msgFormat = "{timestamp} {type} {msg}", const QString timestampFormat = "yyyy-MM-dd HH:mm:ss.zzz", const QtMsgType minLevel = QtDebugMsg, const int bufferSize = 0, QObject * parent = 0)
Constructor.
Parameters
msgFormat Format of the decoration, e.g. "{timestamp} {type} thread={thread}: {msg}"
timestampFormat Format of timestamp, e.g. "yyyy-MM-dd HH:mm:ss.zzz"
minLevel Minimum severity that genertes an output (0=debug, 1=warning, 2=critical, 3=fatal).
bufferSize Size of the backtrace buffer, number of messages per thread. 0=disabled.
parent Parent object
See also
LogMessage for a description of the message decoration.
Definition at line 34 of file logger.cpp.
References bufferSize, minLevel, msgFormat, and timestampFormat.
     :QObject(parent)
 {
     this->msgFormat=msgFormat;
     this->timestampFormat=timestampFormat;
     this->minLevel=minLevel;
     this->bufferSize=bufferSize;
 }
~Logger()
Logger::~Logger () virtual
Destructor
Definition at line 90 of file logger.cpp.
References defaultLogger.
 {
     if (defaultLogger==this)
     {
 #if QT_VERSION >= 0x050000
         qInstallMessageHandler(0);
 #else
         qInstallMsgHandler(0);
 #endif
         defaultLogger=0;
     }
 }
Member Function Documentation
clear()
void Logger::clear (const bool buffer = true, const bool variables = true) virtual
Clear the thread-local data of the current thread. This method is thread safe.
Parameters
buffer Whether to clear the backtrace buffer
variables Whether to clear the log variables
Reimplemented in qtwebapp::DualFileLogger, and qtwebapp::LoggerWithFile.
Definition at line 134 of file logger.cpp.
References buffers, logVars, and mutex.
Referenced by qtwebapp::LoggerWithFile::clear(), and qtwebapp::DualFileLogger::clear().
 {
     mutex.lock();
     if (buffer && buffers.hasLocalData())
     {
         QList<LogMessage*>* buffer=buffers.localData();
         while (buffer && !buffer->isEmpty()) {
             LogMessage* logMessage=buffer->takeLast();
             delete logMessage;
         }
     }
     if (variables && logVars.hasLocalData())
     {
         logVars.localData()->clear();
     }
     mutex.unlock();
 }
getMinMessageLevel()
QtMsgType qtwebapp::Logger::getMinMessageLevel () const inline
Get the current message level
Definition at line 107 of file logger.h.
Referenced by qtwebapp::LoggerWithFile::getConsoleMinMessageLevelStr(), and qtwebapp::LoggerWithFile::getFileMinMessageLevelStr().
{
         return minLevel;
     }
installMsgHandler()
void Logger::installMsgHandler ()
Installs this logger as the default message handler, so it can be used through the global static logging functions (e.g. qDebug()).
Definition at line 111 of file logger.cpp.
References defaultLogger, and msgHandler4().
Referenced by main().
 {
     defaultLogger=this;
 #if QT_VERSION >= 0x050000
     qInstallMessageHandler(msgHandler5);
 #else
     qInstallMsgHandler(msgHandler4);
 #endif
 }
log()
void Logger::log (const QtMsgType type, const QString & message, const QString & file = "", const QString & function = "", const int line = 0) virtual
Decorate and log the message, if type>=minLevel. This method is thread safe.
Parameters
type Message type (level)
message Message text
file Name of the source file where the message was generated (usually filled with the macro FILE)
function Name of the function where the message was generated (usually filled with the macro LINE)
line Line Number of the source file, where the message was generated (usually filles with the macro func or FUNCTION)
See also
LogMessage for a description of the message decoration.
Reimplemented in qtwebapp::DualFileLogger, and qtwebapp::LoggerWithFile.
Definition at line 153 of file logger.cpp.
References buffers, bufferSize, logVars, minLevel, mutex, and write().
Referenced by qtwebapp::LoggerWithFile::log(), qtwebapp::DualFileLogger::log(), qtwebapp::LoggerWithFile::logToFile(), and msgHandler().
 {
     mutex.lock();
     // If the buffer is enabled, write the message into it
     if (bufferSize>0) {
         // Create new thread local buffer, if necessary
         if (!buffers.hasLocalData()) {
             buffers.setLocalData(new QList<LogMessage*>());
         }
         QList<LogMessage*>* buffer=buffers.localData();
         // Append the decorated log message
         LogMessage* logMessage=new LogMessage(type,message,logVars.localData(),file,function,line);
         buffer->append(logMessage);
         // Delete oldest message if the buffer became too large
         if (buffer->size()>bufferSize)
         {
             delete buffer->takeFirst();
         }
         // If the type of the message is high enough, print the whole buffer
         if (type>=minLevel) {
             while (!buffer->isEmpty())
             {
                 LogMessage* logMessage=buffer->takeFirst();
                 write(logMessage);
                 delete logMessage;
             }
         }
     }
     // Buffer is disabled, print the message if the type is high enough
     else {
         if (type>=minLevel)
         {
             LogMessage logMessage(type,message,logVars.localData(),file,function,line);
             write(&logMessage);
         }
     }
     mutex.unlock();
 }
msgHandler()
void Logger::msgHandler (const QtMsgType type, const QString & message, const QString & file = "", const QString & function = "", const int line = 0) static private
Message Handler for the global static logging functions (e.g. qDebug()). Forward calls to the default logger.
In case of a fatal message, the program will abort. Variables in the in the message are replaced by their values. This method is thread safe.
Parameters
type Message type (level)
message Message text
file Name of the source file where the message was generated (usually filled with the macro FILE)
function Name of the function where the message was generated (usually filled with the macro LINE)
line Line Number of the source file, where the message was generated (usually filles with the macro func or FUNCTION)
Definition at line 44 of file logger.cpp.
References defaultLogger, and log().
Referenced by msgHandler4().
 {
     static QMutex recursiveMutex(QMutex::Recursive);
     static QMutex nonRecursiveMutex(QMutex::NonRecursive);
     // Prevent multiple threads from calling this method simultaneoulsy.
     // But allow recursive calls, which is required to prevent a deadlock
     // if the logger itself produces an error message.
     recursiveMutex.lock();
     // Fall back to stderr when this method has been called recursively.
     if (defaultLogger && nonRecursiveMutex.tryLock())
     {
         defaultLogger->log(type, message, file, function, line);
         nonRecursiveMutex.unlock();
     }
     else
     {
         fputs(qPrintable(message),stderr);
         fflush(stderr);
     }
     // Abort the program after logging a fatal message
     if (type==QtFatalMsg)
     {
         abort();
     }
     recursiveMutex.unlock();
 }
msgHandler4()
void Logger::msgHandler4 (const QtMsgType type, const char * message) static private
Wrapper for QT version 4.
Parameters
type Message type (level)
message Message text
See also
msgHandler()
Definition at line 83 of file logger.cpp.
References msgHandler().
Referenced by installMsgHandler().
     {
         msgHandler(type,message);
     }
set()
void Logger::set (const QString & name, const QString & value) static
Sets a thread-local variable that may be used to decorate log messages. This method is thread safe.
Parameters
name Name of the variable
value Value of the variable
Definition at line 122 of file logger.cpp.
References logVars, and mutex.
 {
     mutex.lock();
     if (!logVars.hasLocalData())
     {
         logVars.setLocalData(new QHash<QString,QString>);
     }
     logVars.localData()->insert(name,value);
     mutex.unlock();
 }
setMinMessageLevel()
void qtwebapp::Logger::setMinMessageLevel (const QtMsgType & minMsgLevel) inline
Sets the minimum message level on the fly
Definition at line 100 of file logger.h.
Referenced by qtwebapp::LoggerWithFile::setConsoleMinMessageLevel(), and qtwebapp::LoggerWithFile::setFileMinMessageLevel().
{
         minLevel = minMsgLevel;
     }
write()
void Logger::write (const LogMessage * logMessage) protected virtual
Decorate and write a log message to stderr. Override this method to provide a different output medium.
Reimplemented in qtwebapp::FileLogger.
Definition at line 104 of file logger.cpp.
References msgFormat, timestampFormat, and qtwebapp::LogMessage::toString().
Referenced by log(), and qtwebapp::FileLogger::write().
 {
     fputs(qPrintable(logMessage->toString(msgFormat,timestampFormat)),stderr);
     fflush(stderr);
 }
Member Data Documentation
buffers
QThreadStorage<QList<LogMessage*>*> qtwebapp::Logger::buffers private
Thread local backtrace buffers
Definition at line 198 of file logger.h.
Referenced by clear(), and log().
bufferSize
int qtwebapp::Logger::bufferSize protected
Size of backtrace buffer, number of messages per thread. 0=disabled
Definition at line 139 of file logger.h.
Referenced by log(), Logger(), qtwebapp::FileLogger::refreshFileLogSettings(), and qtwebapp::FileLogger::refreshQtSettings().
defaultLogger
Logger * Logger::defaultLogger =0 static private
Pointer to the default logger, used by msgHandler()
Definition at line 153 of file logger.h.
Referenced by installMsgHandler(), msgHandler(), and ~Logger().
logVars
QThreadStorage< QHash< QString, QString > * > Logger::logVars static private
Thread local variables to be used in log messages
Definition at line 195 of file logger.h.
Referenced by clear(), log(), and set().
minLevel
QtMsgType qtwebapp::Logger::minLevel protected
Minimum level of message types that are written out
Definition at line 136 of file logger.h.
Referenced by log(), Logger(), qtwebapp::FileLogger::refreshFileLogSettings(), and qtwebapp::FileLogger::refreshQtSettings().
msgFormat
QString qtwebapp::Logger::msgFormat protected
Format string for message decoration
Definition at line 130 of file logger.h.
Referenced by Logger(), qtwebapp::FileLogger::refreshFileLogSettings(), qtwebapp::FileLogger::refreshQtSettings(), qtwebapp::FileLogger::write(), and write().
mutex
QMutex Logger::mutex static protected
Used to synchronize access of concurrent threads
Definition at line 142 of file logger.h.
Referenced by clear(), log(), qtwebapp::FileLogger::refreshSettings(), set(), and qtwebapp::FileLogger::timerEvent().
timestampFormat
QString qtwebapp::Logger::timestampFormat protected
Format string of timestamps
Definition at line 133 of file logger.h.
Referenced by Logger(), qtwebapp::FileLogger::refreshFileLogSettings(), qtwebapp::FileLogger::refreshQtSettings(), qtwebapp::FileLogger::write(), and write().
The documentation for this class was generated from the following files:
logging/logger.h
logging/logger.cpp