SDRAngel: SWGSDRangel::SWGLocalOutputSettings Class Reference
SWGSDRangel::SWGLocalOutputSettings Class Reference
#include <SWGLocalOutputSettings.h>
Public Member Functions
SWGLocalOutputSettings ()
SWGLocalOutputSettings (QString *json)
virtual ~SWGLocalOutputSettings ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGLocalOutputSettings * fromJson (QString &jsonString) override
qint32 getUseReverseApi ()
void setUseReverseApi (qint32 use_reverse_api)
QString * getReverseApiAddress ()
void setReverseApiAddress (QString *reverse_api_address)
qint32 getReverseApiPort ()
void setReverseApiPort (qint32 reverse_api_port)
qint32 getReverseApiDeviceIndex ()
void setReverseApiDeviceIndex (qint32 reverse_api_device_index)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 use_reverse_api
bool m_use_reverse_api_isSet
QString * reverse_api_address
bool m_reverse_api_address_isSet
qint32 reverse_api_port
bool m_reverse_api_port_isSet
qint32 reverse_api_device_index
bool m_reverse_api_device_index_isSet
Detailed Description
Definition at line 32 of file SWGLocalOutputSettings.h.
Constructor & Destructor Documentation
SWGLocalOutputSettings() [1/2]
SWGSDRangel::SWGLocalOutputSettings::SWGLocalOutputSettings ()
Definition at line 30 of file SWGLocalOutputSettings.cpp.
References m_reverse_api_address_isSet, m_reverse_api_device_index_isSet, m_reverse_api_port_isSet, m_use_reverse_api_isSet, reverse_api_address, reverse_api_device_index, reverse_api_port, and use_reverse_api.
{
     use_reverse_api = 0;
     m_use_reverse_api_isSet = false;
     reverse_api_address = nullptr;
     m_reverse_api_address_isSet = false;
     reverse_api_port = 0;
     m_reverse_api_port_isSet = false;
     reverse_api_device_index = 0;
     m_reverse_api_device_index_isSet = false;
 }
SWGLocalOutputSettings() [2/2]
SWGSDRangel::SWGLocalOutputSettings::SWGLocalOutputSettings (QString * json)
Definition at line 25 of file SWGLocalOutputSettings.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGLocalOutputSettings()
SWGSDRangel::SWGLocalOutputSettings::~SWGLocalOutputSettings () virtual
Definition at line 41 of file SWGLocalOutputSettings.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGLocalOutputSettings::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 89 of file SWGLocalOutputSettings.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGLocalOutputSettings::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 100 of file SWGLocalOutputSettings.cpp.
References m_reverse_api_device_index_isSet, m_reverse_api_port_isSet, m_use_reverse_api_isSet, reverse_api_address, reverse_api_device_index, reverse_api_port, SWGSDRangel::toJsonValue(), and use_reverse_api.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_use_reverse_api_isSet){
         obj->insert("useReverseAPI", QJsonValue(use_reverse_api));
     }
     if(reverse_api_address != nullptr && *reverse_api_address != QString("")){
         toJsonValue(QString("reverseAPIAddress"), reverse_api_address, obj, QString("QString"));
     }
     if(m_reverse_api_port_isSet){
         obj->insert("reverseAPIPort", QJsonValue(reverse_api_port));
     }
     if(m_reverse_api_device_index_isSet){
         obj->insert("reverseAPIDeviceIndex", QJsonValue(reverse_api_device_index));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGLocalOutputSettings::cleanup ()
Definition at line 58 of file SWGLocalOutputSettings.cpp.
References reverse_api_address.
Referenced by ~SWGLocalOutputSettings().
{
     if(reverse_api_address != nullptr) {
         delete reverse_api_address;
     }
 }
fromJson()
SWGLocalOutputSettings * SWGSDRangel::SWGLocalOutputSettings::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 68 of file SWGLocalOutputSettings.cpp.
References fromJsonObject().
Referenced by SWGLocalOutputSettings().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGLocalOutputSettings::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 77 of file SWGLocalOutputSettings.cpp.
References reverse_api_address, reverse_api_device_index, reverse_api_port, SWGSDRangel::setValue(), and use_reverse_api.
Referenced by fromJson(), and WebAPIRequestMapper::validateDeviceSettings().
{
     ::SWGSDRangel::setValue(&use_reverse_api, pJson["useReverseAPI"], "qint32", "");
     ::SWGSDRangel::setValue(&reverse_api_address, pJson["reverseAPIAddress"], "QString", "QString");
     ::SWGSDRangel::setValue(&reverse_api_port, pJson["reverseAPIPort"], "qint32", "");
     ::SWGSDRangel::setValue(&reverse_api_device_index, pJson["reverseAPIDeviceIndex"], "qint32", "");
 }
getReverseApiAddress()
QString * SWGSDRangel::SWGLocalOutputSettings::getReverseApiAddress ()
Definition at line 129 of file SWGLocalOutputSettings.cpp.
References reverse_api_address.
Referenced by LocalOutput::webapiFormatDeviceSettings(), and LocalOutput::webapiSettingsPutPatch().
{
     return reverse_api_address;
 }
getReverseApiDeviceIndex()
qint32 SWGSDRangel::SWGLocalOutputSettings::getReverseApiDeviceIndex ()
Definition at line 149 of file SWGLocalOutputSettings.cpp.
References reverse_api_device_index.
Referenced by LocalOutput::webapiSettingsPutPatch().
{
     return reverse_api_device_index;
 }
getReverseApiPort()
qint32 SWGSDRangel::SWGLocalOutputSettings::getReverseApiPort ()
Definition at line 139 of file SWGLocalOutputSettings.cpp.
References reverse_api_port.
Referenced by LocalOutput::webapiSettingsPutPatch().
{
     return reverse_api_port;
 }
getUseReverseApi()
qint32 SWGSDRangel::SWGLocalOutputSettings::getUseReverseApi ()
Definition at line 119 of file SWGLocalOutputSettings.cpp.
References use_reverse_api.
Referenced by LocalOutput::webapiSettingsPutPatch().
{
     return use_reverse_api;
 }
init()
void SWGSDRangel::SWGLocalOutputSettings::init ()
Definition at line 46 of file SWGLocalOutputSettings.cpp.
References m_reverse_api_address_isSet, m_reverse_api_device_index_isSet, m_reverse_api_port_isSet, m_use_reverse_api_isSet, reverse_api_address, reverse_api_device_index, reverse_api_port, and use_reverse_api.
Referenced by SWGLocalOutputSettings(), and LocalOutput::webapiSettingsGet().
{
     use_reverse_api = 0;
     m_use_reverse_api_isSet = false;
     reverse_api_address = new QString("");
     m_reverse_api_address_isSet = false;
     reverse_api_port = 0;
     m_reverse_api_port_isSet = false;
     reverse_api_device_index = 0;
     m_reverse_api_device_index_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGLocalOutputSettings::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 160 of file SWGLocalOutputSettings.cpp.
References m_reverse_api_device_index_isSet, m_reverse_api_port_isSet, m_use_reverse_api_isSet, and reverse_api_address.
Referenced by SWGSDRangel::SWGDeviceSettings::asJsonObject(), SWGSDRangel::SWGDeviceSettings_2::asJsonObject(), SWGSDRangel::SWGDeviceSettings_2::isSet(), and SWGSDRangel::SWGDeviceSettings::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(m_use_reverse_api_isSet){ isObjectUpdated = true; break;}
         if(reverse_api_address != nullptr && *reverse_api_address != QString("")){ isObjectUpdated = true; break;}
         if(m_reverse_api_port_isSet){ isObjectUpdated = true; break;}
         if(m_reverse_api_device_index_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setReverseApiAddress()
void SWGSDRangel::SWGLocalOutputSettings::setReverseApiAddress (QString * reverse_api_address)
Definition at line 133 of file SWGLocalOutputSettings.cpp.
References m_reverse_api_address_isSet, and reverse_api_address.
Referenced by LocalOutput::webapiFormatDeviceSettings().
{
     this->reverse_api_address = reverse_api_address;
     this->m_reverse_api_address_isSet = true;
 }
setReverseApiDeviceIndex()
void SWGSDRangel::SWGLocalOutputSettings::setReverseApiDeviceIndex (qint32 reverse_api_device_index)
Definition at line 153 of file SWGLocalOutputSettings.cpp.
References m_reverse_api_device_index_isSet, and reverse_api_device_index.
Referenced by LocalOutput::webapiFormatDeviceSettings().
{
     this->reverse_api_device_index = reverse_api_device_index;
     this->m_reverse_api_device_index_isSet = true;
 }
setReverseApiPort()
void SWGSDRangel::SWGLocalOutputSettings::setReverseApiPort (qint32 reverse_api_port)
Definition at line 143 of file SWGLocalOutputSettings.cpp.
References m_reverse_api_port_isSet, and reverse_api_port.
Referenced by LocalOutput::webapiFormatDeviceSettings().
{
     this->reverse_api_port = reverse_api_port;
     this->m_reverse_api_port_isSet = true;
 }
setUseReverseApi()
void SWGSDRangel::SWGLocalOutputSettings::setUseReverseApi (qint32 use_reverse_api)
Definition at line 123 of file SWGLocalOutputSettings.cpp.
References m_use_reverse_api_isSet, and use_reverse_api.
Referenced by LocalOutput::webapiFormatDeviceSettings().
{
     this->use_reverse_api = use_reverse_api;
     this->m_use_reverse_api_isSet = true;
 }
Member Data Documentation
m_reverse_api_address_isSet
bool SWGSDRangel::SWGLocalOutputSettings::m_reverse_api_address_isSet private
Definition at line 65 of file SWGLocalOutputSettings.h.
Referenced by init(), setReverseApiAddress(), and SWGLocalOutputSettings().
m_reverse_api_device_index_isSet
bool SWGSDRangel::SWGLocalOutputSettings::m_reverse_api_device_index_isSet private
Definition at line 71 of file SWGLocalOutputSettings.h.
Referenced by asJsonObject(), init(), isSet(), setReverseApiDeviceIndex(), and SWGLocalOutputSettings().
m_reverse_api_port_isSet
bool SWGSDRangel::SWGLocalOutputSettings::m_reverse_api_port_isSet private
Definition at line 68 of file SWGLocalOutputSettings.h.
Referenced by asJsonObject(), init(), isSet(), setReverseApiPort(), and SWGLocalOutputSettings().
m_use_reverse_api_isSet
bool SWGSDRangel::SWGLocalOutputSettings::m_use_reverse_api_isSet private
Definition at line 62 of file SWGLocalOutputSettings.h.
Referenced by asJsonObject(), init(), isSet(), setUseReverseApi(), and SWGLocalOutputSettings().
reverse_api_address
QString* SWGSDRangel::SWGLocalOutputSettings::reverse_api_address private
Definition at line 64 of file SWGLocalOutputSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getReverseApiAddress(), init(), isSet(), setReverseApiAddress(), and SWGLocalOutputSettings().
reverse_api_device_index
qint32 SWGSDRangel::SWGLocalOutputSettings::reverse_api_device_index private
Definition at line 70 of file SWGLocalOutputSettings.h.
Referenced by asJsonObject(), fromJsonObject(), getReverseApiDeviceIndex(), init(), setReverseApiDeviceIndex(), and SWGLocalOutputSettings().
reverse_api_port
qint32 SWGSDRangel::SWGLocalOutputSettings::reverse_api_port private
Definition at line 67 of file SWGLocalOutputSettings.h.
Referenced by asJsonObject(), fromJsonObject(), getReverseApiPort(), init(), setReverseApiPort(), and SWGLocalOutputSettings().
use_reverse_api
qint32 SWGSDRangel::SWGLocalOutputSettings::use_reverse_api private
Definition at line 61 of file SWGLocalOutputSettings.h.
Referenced by asJsonObject(), fromJsonObject(), getUseReverseApi(), init(), setUseReverseApi(), and SWGLocalOutputSettings().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGLocalOutputSettings.h
swagger/sdrangel/code/qt5/client/SWGLocalOutputSettings.cpp