SDRAngel: LevelMeterVU Class Reference
LevelMeterVU Class Reference
#include <levelmeter.h>
Public Member Functions
LevelMeterVU (QWidget *parent=0)
virtual ~LevelMeterVU ()
Public Member Functions inherited from LevelMeter
LevelMeter (QWidget *parent=0)
virtual ~LevelMeter ()
void paintEvent (QPaintEvent *event)
void resizeEvent (QResizeEvent *event)
void setAverageSmoothing (uint32_t smoothingFactor)
Protected Member Functions
virtual void render (QPainter *painter)
virtual void resized ()
Protected Member Functions inherited from LevelMeter
int shiftx (int val, int width)
Additional Inherited Members
Public Slots inherited from LevelMeter
void reset ()
void levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples)
Protected Slots inherited from LevelMeter
void redrawTimerExpired ()
Protected Attributes inherited from LevelMeter
qreal m_avgLevel
qreal m_peakLevel
qreal m_decayedPeakLevel
QTime m_peakLevelChanged
qreal m_peakDecayRate
qreal m_peakHoldLevel
QTime m_peakHoldLevelChanged
uint32_t m_avgSmoothing
QTimer * m_redrawTimer
QColor m_avgColor
QColor m_peakColor
QColor m_decayedPeakColor
ScaleEngine m_scaleEngine
QPixmap * m_backgroundPixmap
Detailed Description
Definition at line 148 of file levelmeter.h.
Constructor & Destructor Documentation
LevelMeterVU()
LevelMeterVU::LevelMeterVU (QWidget * parent = 0)
Definition at line 154 of file levelmeter.cpp.
References LevelMeter::m_scaleEngine, Unit::Percent, resized(), ScaleEngine::setFont(), ScaleEngine::setOrientation(), and ScaleEngine::setRange().
                                           :
         LevelMeter(parent)
 {
     m_scaleEngine.setFont(font());
     m_scaleEngine.setOrientation(Qt::Horizontal);
     m_scaleEngine.setRange(Unit::Percent, 0, 100);
     resized();
 }
~LevelMeterVU()
LevelMeterVU::~LevelMeterVU () virtual
Definition at line 164 of file levelmeter.cpp.
 {
 }
Member Function Documentation
render()
void LevelMeterVU::render (QPainter * painter) protected virtual
Implements LevelMeter.
Definition at line 222 of file levelmeter.cpp.
References LevelMeter::m_avgColor, LevelMeterSignalDB::m_avgColor, LevelMeter::m_avgLevel, LevelMeter::m_backgroundPixmap, LevelMeter::m_decayedPeakColor, LevelMeterSignalDB::m_decayedPeakColor, LevelMeter::m_decayedPeakLevel, LevelMeter::m_peakColor, LevelMeterSignalDB::m_peakColor, and LevelMeter::m_peakHoldLevel.
 {
     painter->drawPixmap(rect(), *m_backgroundPixmap);
     QRect bar = rect();
     // Bottom moving gauge
     bar.setTop(0.5 * rect().height() + 2);
     bar.setBottom(rect().height() - 1);
     bar.setRight(rect().right() - (1.0 - 0.75*m_peakHoldLevel) * rect().width());
     bar.setLeft(bar.right() - 2);
     painter->fillRect(bar, m_peakColor);
     bar.setBottom(0.75*rect().height());
     bar.setRight(rect().right() - (1.0 - 0.75*m_avgLevel) * rect().width());
     bar.setLeft(1);
     painter->fillRect(bar, m_avgColor);
     bar.setTop(0.75 * rect().height() + 1);
     bar.setBottom(rect().height() - 1);
     bar.setRight(rect().right() - (1.0 - 0.75*m_decayedPeakLevel) * rect().width());
     painter->fillRect(bar, m_decayedPeakColor);
     // borders
     painter->setPen(QColor(0,0,0));
     painter->drawLine(0, 0, rect().width() - 2, 0);
     painter->drawLine(0, rect().height() - 1, 0, 0);
     painter->setPen(QColor(80,80,80));
     painter->drawLine(1, rect().height() - 1, rect().width() - 1, rect().height() - 1);
     painter->drawLine(rect().width() - 1, rect().height() - 1, rect().width() - 1, 0);
 }
resized()
void LevelMeterVU::resized () protected virtual
Implements LevelMeter.
Definition at line 168 of file levelmeter.cpp.
References ScaleEngine::getTickList(), i, LevelMeter::m_backgroundPixmap, LevelMeter::m_scaleEngine, ScaleEngine::Tick::major, ScaleEngine::Tick::pos, ScaleEngine::setSize(), LevelMeter::shiftx(), ScaleEngine::Tick::text, ScaleEngine::Tick::textPos, and ScaleEngine::Tick::textSize.
Referenced by LevelMeterVU().
 {
     if (m_backgroundPixmap)
     {
         delete m_backgroundPixmap;
     }
     m_backgroundPixmap = new QPixmap(rect().width(), rect().height());
     m_backgroundPixmap->fill(QColor(42, 42, 42, 255));
     QPainter painter(m_backgroundPixmap);
     QRect barTop = m_backgroundPixmap->rect();
     barTop.setBottom(0.5 * rect().height() - 2);
     barTop.setTop(2);
     barTop.setLeft(0.75* rect().width());
     painter.fillRect(barTop, Qt::red);
     QRect bar = m_backgroundPixmap->rect();
     // 100% full height white line
     painter.setPen(Qt::white);
     painter.setFont(font());
 //    painter.drawLine(0.75*bar.width(), 0, 0.75*bar.width(), bar.height());
     m_scaleEngine.setSize(0.75*bar.width());
     const ScaleEngine::TickList& scaleTickList = m_scaleEngine.getTickList();
     for (int i = 0; i < scaleTickList.count(); i++)
     {
 //        qDebug() << "LevelMeterVU::resized: tick #" << i
 //                << " major: " << scaleTickList[i].major
 //                << " pos: " << scaleTickList[i].pos
 //                << " text: " << scaleTickList[i].text
 //                << " textPos: " << scaleTickList[i].textPos
 //                << " textSize: " << scaleTickList[i].textSize;
         const ScaleEngine::Tick tick = scaleTickList[i];
         if(tick.major)
         {
             if ((tick.textSize > 0) && (tick.textPos > 0))
             {
                 painter.drawText(QPointF(tick.textPos - (tick.textSize/2) - 4, bar.height()/2 - 3), tick.text);
             }
             painter.drawLine(shiftx(tick.pos, bar.width()), 0, shiftx(scaleTickList[i].pos, bar.width()), bar.height());
         }
         else
         {
             painter.drawLine(tick.pos, bar.height()/2 - 2, scaleTickList[i].pos, bar.height()/2);
         }
     }
 }
The documentation for this class was generated from the following files:
sdrgui/gui/levelmeter.h
sdrgui/gui/levelmeter.cpp