SDRAngel: ATVModGUI Class Reference
ATVModGUI Class Reference
#include <atvmodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static ATVModGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx)
Private Slots
void handleSourceMessages ()
void on_deltaFrequency_changed (qint64 value)
void on_channelMute_toggled (bool checked)
void on_forceDecimator_toggled (bool checked)
void on_modulation_currentIndexChanged (int index)
void on_rfScaling_valueChanged (int value)
void on_fmExcursion_valueChanged (int value)
void on_rfBW_valueChanged (int value)
void on_rfOppBW_valueChanged (int value)
void on_nbLines_currentIndexChanged (int index)
void on_fps_currentIndexChanged (int index)
void on_standard_currentIndexChanged (int index)
void on_invertVideo_clicked (bool checked)
void on_uniformLevel_valueChanged (int value)
void on_inputSelect_currentIndexChanged (int index)
void on_imageFileDialog_clicked (bool checked)
void on_videoFileDialog_clicked (bool checked)
void on_playVideo_toggled (bool checked)
void on_playLoop_toggled (bool checked)
void on_navTimeSlider_valueChanged (int value)
void on_playCamera_toggled (bool checked)
void on_camSelect_currentIndexChanged (int index)
void on_cameraManualFPSEnable_toggled (bool checked)
void on_cameraManualFPS_valueChanged (int value)
void on_overlayTextShow_toggled (bool checked)
void on_overlayText_textEdited (const QString &arg1)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void configureImageFileName ()
void configureVideoFileName ()
void tick ()
Private Member Functions
ATVModGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx, QWidget *parent=0)
virtual ~ATVModGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
void updateWithStreamData ()
void updateWithStreamTime ()
void setRFFiltersSlidersRange (int sampleRate)
void setChannelMarkerBandwidth ()
int getNbLines ()
int getFPS ()
int getNbLinesIndex (int nbLines)
int getFPSIndex (int fps)
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::ATVModGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
ATVModSettings m_settings
bool m_doApplySettings
ATVMod * m_atvMod
MovingAverageUtil< double, double, 20 > m_channelPowerDbAvg
QString m_imageFileName
QString m_videoFileName
quint32 m_videoLength
video file length in seconds
float m_videoFrameRate
video file frame rate
int m_frameCount
std::size_t m_tickCount
bool m_enableNavTime
QMessageBox * m_camBusyFPSMessageBox
int m_rfSliderDivisor
MessageQueue m_inputMessageQueue
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 39 of file atvmodgui.h.
Constructor & Destructor Documentation
ATVModGUI()
ATVModGUI::ATVModGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx, QWidget * parent = 0) explicit private
Definition at line 647 of file atvmodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), arg(), channelMarkerChangedByCursor(), displaySettings(), ATVMod::getCameraNumbers(), ChannelMarker::getColor(), getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, handleSourceMessages(), m_atvMod, ATVMod::m_channelIdURI, m_channelMarker, m_deviceUISet, ATVModSettings::m_rgbColor, m_settings, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerTxChannelInstance(), resetToDefaults(), ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ATVModSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSource::setMessageQueueToGUI(), ChannelMarker::setSourceOrSinkStream(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                      :
     RollupWidget(parent),
     ui(new Ui::ATVModGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_doApplySettings(true),
     m_videoLength(0),
     m_videoFrameRate(48000),
     m_frameCount(0),
     m_tickCount(0),
     m_enableNavTime(false),
     m_camBusyFPSMessageBox(0),
     m_rfSliderDivisor(100000)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_atvMod = (ATVMod*) channelTx; //new ATVMod(m_deviceUISet->m_deviceSinkAPI);
     m_atvMod->setMessageQueueToGUI(getInputMessageQueue());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     m_channelMarker.setBandwidth(5000);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("ATV Modulator");
     m_channelMarker.setSourceOrSinkStream(false);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     setTitleColor(m_channelMarker.getColor());
     m_settings.setChannelMarker(&m_channelMarker);
     m_deviceUISet->registerTxChannelInstance(ATVMod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     resetToDefaults();
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     connect(m_atvMod, SIGNAL(levelChanged(qreal, qreal, int)), ui->volumeMeter, SLOT(levelChanged(qreal, qreal, int)));
     std::vector<int> cameraNumbers;
     m_atvMod->getCameraNumbers(cameraNumbers);
     for (std::vector<int>::iterator it = cameraNumbers.begin(); it != cameraNumbers.end(); ++it) {
         ui->camSelect->addItem(tr("%1").arg(*it));
     }
     QChar delta = QChar(0x94, 0x03);
     ui->fmExcursionLabel->setText(delta);
     displaySettings();
     applySettings(true);
 }
~ATVModGUI()
ATVModGUI::~ATVModGUI () private virtual
Definition at line 713 of file atvmodgui.cpp.
References m_atvMod, m_deviceUISet, DeviceUISet::removeTxChannelInstance(), and ui.
 {
     m_deviceUISet->removeTxChannelInstance(this);
     delete m_atvMod; // TODO: check this: when the GUI closes it has to delete the modulator
     delete ui;
 }
Member Function Documentation
applySettings()
void ATVModGUI::applySettings (bool force = false) private
Definition at line 725 of file atvmodgui.cpp.
References ATVMod::MsgConfigureATVMod::create(), ATVMod::MsgConfigureChannelizer::create(), ChannelMarker::getCenterFrequency(), BasebandSampleSource::getInputMessageQueue(), m_atvMod, m_channelMarker, m_doApplySettings, m_settings, and MessageQueue::push().
Referenced by ATVModGUI(), channelMarkerChangedByCursor(), deserialize(), on_channelMute_toggled(), on_deltaFrequency_changed(), on_fmExcursion_valueChanged(), on_forceDecimator_toggled(), on_fps_currentIndexChanged(), on_inputSelect_currentIndexChanged(), on_invertVideo_clicked(), on_modulation_currentIndexChanged(), on_nbLines_currentIndexChanged(), on_overlayText_textEdited(), on_overlayTextShow_toggled(), on_playCamera_toggled(), on_playLoop_toggled(), on_playVideo_toggled(), on_rfBW_valueChanged(), on_rfOppBW_valueChanged(), on_rfScaling_valueChanged(), on_standard_currentIndexChanged(), on_uniformLevel_valueChanged(), onMenuDialogCalled(), and setCenterFrequency().
 {
     if (m_doApplySettings)
     {
         ATVMod::MsgConfigureChannelizer *msgChan = ATVMod::MsgConfigureChannelizer::create(
                 m_channelMarker.getCenterFrequency());
         m_atvMod->getInputMessageQueue()->push(msgChan);
         ATVMod::MsgConfigureATVMod *msg = ATVMod::MsgConfigureATVMod::create(m_settings, force);
         m_atvMod->getInputMessageQueue()->push(msg);
     }
 }
blockApplySettings()
void ATVModGUI::blockApplySettings (bool block) private
Definition at line 720 of file atvmodgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void ATVModGUI::channelMarkerChangedByCursor () slot
Definition at line 180 of file atvmodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, ATVModSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by ATVModGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
configureImageFileName
void ATVModGUI::configureImageFileName () private slot
Definition at line 595 of file atvmodgui.cpp.
References ATVMod::MsgConfigureImageFileName::create(), BasebandSampleSource::getInputMessageQueue(), m_atvMod, m_imageFileName, and MessageQueue::push().
Referenced by on_imageFileDialog_clicked().
 {
     qDebug() << "ATVModGUI::configureImageFileName: " << m_imageFileName.toStdString().c_str();
     ATVMod::MsgConfigureImageFileName* message = ATVMod::MsgConfigureImageFileName::create(m_imageFileName);
     m_atvMod->getInputMessageQueue()->push(message);
 }
configureVideoFileName
void ATVModGUI::configureVideoFileName () private slot
Definition at line 602 of file atvmodgui.cpp.
References ATVMod::MsgConfigureVideoFileName::create(), BasebandSampleSource::getInputMessageQueue(), m_atvMod, m_videoFileName, and MessageQueue::push().
Referenced by on_videoFileDialog_clicked().
 {
     qDebug() << "ATVModGUI::configureVideoFileName: " << m_videoFileName.toStdString().c_str();
     ATVMod::MsgConfigureVideoFileName* message = ATVMod::MsgConfigureVideoFileName::create(m_videoFileName);
     m_atvMod->getInputMessageQueue()->push(message);
 }
create()
ATVModGUI * ATVModGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx) static
Definition at line 38 of file atvmodgui.cpp.
References ATVModGUI().
Referenced by ATVModPlugin::createTxChannelGUI().
 {
     ATVModGUI* gui = new ATVModGUI(pluginAPI, deviceUISet, channelTx);
     return gui;
 }
deserialize()
bool ATVModGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 79 of file atvmodgui.cpp.
References applySettings(), ATVModSettings::deserialize(), displaySettings(), m_settings, and ATVModSettings::resetToDefaults().
 {
     if(m_settings.deserialize(data))
     {
         displaySettings();
         applySettings(true); // will have true
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         displaySettings();
         applySettings(true); // will have true
         return false;
     }
 }
destroy()
void ATVModGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 44 of file atvmodgui.cpp.
 {
     delete this;
 }
displaySettings()
void ATVModGUI::displaySettings () private
Definition at line 738 of file atvmodgui.cpp.
References arg(), blockApplySettings(), ATVMod::getEffectiveSampleRate(), getFPS(), getFPSIndex(), getNbLines(), getNbLinesIndex(), ChannelMarker::getTitle(), m_atvMod, ATVModSettings::m_atvModInput, ATVModSettings::m_atvModulation, ATVModSettings::m_atvStd, ATVModSettings::m_cameraPlay, m_channelMarker, ATVModSettings::m_channelMute, ATVModSettings::m_fmExcursion, ATVModSettings::m_forceDecimator, ATVModSettings::m_fps, ATVModSettings::m_inputFrequencyOffset, ATVModSettings::m_invertedVideo, ATVModSettings::m_nbLines, ATVModSettings::m_overlayText, ATVModSettings::m_rfBandwidth, ATVModSettings::m_rfOppBandwidth, ATVModSettings::m_rfScalingFactor, m_rfSliderDivisor, ATVModSettings::m_rgbColor, m_settings, ATVModSettings::m_showOverlayText, ATVModSettings::m_title, ATVModSettings::m_uniformLevel, ATVModSettings::m_videoPlay, ATVModSettings::m_videoPlayLoop, ChannelMarker::setCenterFrequency(), setChannelMarkerBandwidth(), ChannelMarker::setColor(), setRFFiltersSlidersRange(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by ATVModGUI(), deserialize(), and handleMessage().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setTitle(m_settings.m_title);
     setChannelMarkerBandwidth();
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->deltaFrequency->setValue(m_settings.m_inputFrequencyOffset);
     ui->modulation->setCurrentIndex((int) m_settings.m_atvModulation);
     setRFFiltersSlidersRange(m_atvMod->getEffectiveSampleRate());
     ui->rfBW->setValue(roundf(m_settings.m_rfBandwidth / m_rfSliderDivisor));
     ui->rfBWText->setText(QString("%1k").arg((ui->rfBW->value()*m_rfSliderDivisor) / 1000.0, 0, 'f', 1));
     ui->rfOppBW->setValue(roundf(m_settings.m_rfOppBandwidth / m_rfSliderDivisor));
     ui->rfOppBWText->setText(QString("%1k").arg((ui->rfOppBW->value()*m_rfSliderDivisor) / 1000.0, 0, 'f', 1));
     ui->forceDecimator->setChecked(m_settings.m_forceDecimator);
     ui->channelMute->setChecked(m_settings.m_channelMute);
     ui->fmExcursion->setValue(roundf(m_settings.m_fmExcursion * 1000.0));
     ui->fmExcursionText->setText(tr("%1").arg(ui->fmExcursion->value() / 10.0, 0, 'f', 1));
     ui->rfScaling->setValue(roundf(m_settings.m_rfScalingFactor / 327.68f));
     ui->rfScalingText->setText(tr("%1").arg(ui->rfScaling->value()));
     int validNbLinesIndex = getNbLinesIndex(m_settings.m_nbLines);
     ui->nbLines->setCurrentIndex(validNbLinesIndex);
     m_settings.m_nbLines = getNbLines(); // normalize
     int validFPSIndex = getFPSIndex(m_settings.m_fps);
     ui->fps->setCurrentIndex(validFPSIndex);
     m_settings.m_fps = getFPS(); // normalize
     ui->standard->setCurrentIndex((int) m_settings.m_atvStd);
     ui->inputSelect->setCurrentIndex((int) m_settings.m_atvModInput);
     ui->invertVideo->setChecked(m_settings.m_invertedVideo);
     ui->uniformLevel->setValue(roundf(m_settings.m_uniformLevel * 100.0));
     ui->uniformLevelText->setText(QString("%1").arg(ui->uniformLevel->value()));
     ui->overlayText->setText(m_settings.m_overlayText);
     ui->overlayTextShow->setChecked(m_settings.m_showOverlayText);
     ui->playCamera->setChecked(m_settings.m_cameraPlay);
     ui->playVideo->setChecked(m_settings.m_videoPlay);
     ui->playLoop->setChecked(m_settings.m_videoPlayLoop);
     blockApplySettings(false);
 }
enterEvent()
void ATVModGUI::enterEvent (QEvent *) private
Definition at line 802 of file atvmodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 ATVModGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 59 of file atvmodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
{
     return m_channelMarker.getCenterFrequency();
 }
getFPS()
int ATVModGUI::getFPS () private
Definition at line 294 of file atvmodgui.cpp.
References ui.
Referenced by displaySettings(), and on_fps_currentIndexChanged().
 {
     switch(ui->fps->currentIndex())
     {
     case 0:
         return 30;
         break;
     case 2:
         return 20;
         break;
     case 3:
         return 16;
         break;
     case 4:
         return 12;
         break;
     case 5:
         return 10;
         break;
     case 6:
         return 8;
         break;
     case 7:
         return 5;
         break;
     case 8:
         return 2;
         break;
     case 9:
         return 1;
         break;
     case 1:
     default:
         return 25;
         break;
     }
 }
getFPSIndex()
int ATVModGUI::getFPSIndex (int fps) private
Definition at line 332 of file atvmodgui.cpp.
Referenced by displaySettings().
 {
     if (fps < 1) {
         return 1;
     } else if (fps < 2) {
         return 9;
     } else if (fps < 5) {
         return 8;
     } else if (fps < 8) {
         return 7;
     } else if (fps < 10) {
         return 6;
     } else if (fps < 12) {
         return 5;
     } else if (fps < 16) {
         return 4;
     } else if (fps < 20) {
         return 3;
     } else if (fps < 25) {
         return 2;
     } else if (fps < 30) {
         return 1;
     } else {
         return 0;
     }
 }
getInputMessageQueue()
virtual MessageQueue* ATVModGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 54 of file atvmodgui.h.
Referenced by ATVModGUI(), and handleSourceMessages().
 { return &m_inputMessageQueue; }
getName()
QString ATVModGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 54 of file atvmodgui.cpp.
 {
     return objectName();
 }
getNbLines()
int ATVModGUI::getNbLines () private
Definition at line 214 of file atvmodgui.cpp.
References ui.
Referenced by displaySettings(), and on_nbLines_currentIndexChanged().
 {
     switch(ui->nbLines->currentIndex())
     {
     case 0:
         return 640;
         break;
     case 2:
         return 525;
         break;
     case 3:
         return 480;
         break;
     case 4:
         return 405;
         break;
     case 5:
         return 360;
         break;
     case 6:
         return 343;
         break;
     case 7:
         return 240;
         break;
     case 8:
         return 180;
         break;
     case 9:
         return 120;
         break;
     case 10:
         return 90;
         break;
     case 11:
         return 60;
         break;
     case 12:
         return 32;
         break;
     case 1:
     default:
         return 625;
         break;
     }
 }
getNbLinesIndex()
int ATVModGUI::getNbLinesIndex (int nbLines) private
Definition at line 261 of file atvmodgui.cpp.
Referenced by displaySettings().
 {
     if (nbLines < 32) {
         return 1;
     } else if (nbLines < 60) {
         return 12;
     } else if (nbLines < 90) {
         return 11;
     } else if (nbLines < 120) {
         return 10;
     } else if (nbLines < 180) {
         return 9;
     } else if (nbLines < 240) {
         return 8;
     } else if (nbLines < 343) {
         return 7;
     } else if (nbLines < 360) {
         return 6;
     } else if (nbLines < 405) {
         return 5;
     } else if (nbLines < 480) {
         return 4;
     } else if (nbLines < 525) {
         return 3;
     } else if (nbLines < 625) {
         return 2;
     } else if (nbLines < 640) {
         return 1;
     } else {
         return 0;
     }
 }
handleMessage()
bool ATVModGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 96 of file atvmodgui.cpp.
References arg(), blockApplySettings(), displaySettings(), ATVMod::MsgReportCameraData::getdeviceNumber(), ATVMod::MsgConfigureImageFileName::getFileName(), ATVMod::MsgConfigureVideoFileName::getFileName(), ATVMod::MsgReportCameraData::getFPS(), ATVMod::MsgReportCameraData::getFPSManual(), ATVMod::MsgReportCameraData::getFPSManualEnable(), ATVMod::MsgReportCameraData::getHeight(), ATVMod::MsgConfigureATVMod::getSettings(), ATVMod::MsgReportCameraData::getStatus(), ATVMod::MsgReportCameraData::getWidth(), m_camBusyFPSMessageBox, m_frameCount, m_settings, m_videoFrameRate, m_videoLength, Message::match(), setRFFiltersSlidersRange(), ui, updateWithStreamData(), and updateWithStreamTime().
Referenced by handleSourceMessages().
 {
     if (ATVMod::MsgReportVideoFileSourceStreamData::match(message))
     {
         m_videoFrameRate = ((ATVMod::MsgReportVideoFileSourceStreamData&)message).getFrameRate();
         m_videoLength = ((ATVMod::MsgReportVideoFileSourceStreamData&)message).getVideoLength();
         m_frameCount = 0;
         updateWithStreamData();
         return true;
     }
     else if (ATVMod::MsgReportVideoFileSourceStreamTiming::match(message))
     {
         m_frameCount = ((ATVMod::MsgReportVideoFileSourceStreamTiming&)message).getFrameCount();
         updateWithStreamTime();
         return true;
     }
     else if (ATVMod::MsgReportCameraData::match(message))
     {
         ATVMod::MsgReportCameraData& rpt = (ATVMod::MsgReportCameraData&) message;
         ui->cameraDeviceNumber->setText(tr("#%1").arg(rpt.getdeviceNumber()));
         ui->camerFPS->setText(tr("%1 FPS").arg(rpt.getFPS(), 0, 'f', 2));
         ui->cameraImageSize->setText(tr("%1x%2").arg(rpt.getWidth()).arg(rpt.getHeight()));
         ui->cameraManualFPSText->setText(tr("%1 FPS").arg(rpt.getFPSManual(), 0, 'f', 1));
         ui->cameraManualFPSEnable->setChecked(rpt.getFPSManualEnable());
         ui->cameraManualFPS->setValue((int) rpt.getFPSManual()*10.0f);
         int status = rpt.getStatus();
         if (status == 1) // camera FPS scan is startng
         {
             m_camBusyFPSMessageBox = new QMessageBox();
             m_camBusyFPSMessageBox->setText("Computing camera FPS. Please wait");
             m_camBusyFPSMessageBox->setStandardButtons(0);
             m_camBusyFPSMessageBox->show();
         }
         else if (status == 2) // camera FPS scan is finished
         {
             if (m_camBusyFPSMessageBox)
             {
                 m_camBusyFPSMessageBox->close();
                 delete m_camBusyFPSMessageBox;
             }
             m_camBusyFPSMessageBox = 0;
         }
         return true;
     }
     else if (ATVMod::MsgReportEffectiveSampleRate::match(message))
     {
         int sampleRate = ((ATVMod::MsgReportEffectiveSampleRate&)message).getSampleRate();
         uint32_t nbPointsPerLine = ((ATVMod::MsgReportEffectiveSampleRate&)message).gatNbPointsPerLine();
         ui->channelSampleRateText->setText(tr("%1k").arg(sampleRate/1000.0f, 0, 'f', 2));
         ui->nbPointsPerLineText->setText(tr("%1p").arg(nbPointsPerLine));
         setRFFiltersSlidersRange(sampleRate);
         return true;
     }
     else if (ATVMod::MsgConfigureATVMod::match(message))
     {
         const ATVMod::MsgConfigureATVMod& cfg = (ATVMod::MsgConfigureATVMod&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (ATVMod::MsgConfigureImageFileName::match(message))
     {
         const ATVMod::MsgConfigureImageFileName& cfg = (ATVMod::MsgConfigureImageFileName&) message;
         ui->imageFileText->setText(cfg.getFileName());
         return true;
     }
     else if (ATVMod::MsgConfigureVideoFileName::match(message))
     {
         const ATVMod::MsgConfigureVideoFileName& cfg = (ATVMod::MsgConfigureVideoFileName&) message;
         ui->videoFileText->setText(cfg.getFileName());
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void ATVModGUI::handleSourceMessages () private slot
Definition at line 359 of file atvmodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by ATVModGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void ATVModGUI::leaveEvent (QEvent *) private
Definition at line 797 of file atvmodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_cameraManualFPS_valueChanged
void ATVModGUI::on_cameraManualFPS_valueChanged (int value) private slot
Definition at line 572 of file atvmodgui.cpp.
References arg(), ATVMod::MsgConfigureCameraData::create(), BasebandSampleSource::getInputMessageQueue(), m_atvMod, MessageQueue::push(), and ui.
 {
     ui->cameraManualFPSText->setText(tr("%1 FPS").arg(value / 10.0f, 0, 'f', 1));
     ATVMod::MsgConfigureCameraData* message = ATVMod::MsgConfigureCameraData::create(
             ui->camSelect->currentIndex(),
             value / 10.0f,
             ui->cameraManualFPSEnable->isChecked());
     m_atvMod->getInputMessageQueue()->push(message);
 }
on_cameraManualFPSEnable_toggled
void ATVModGUI::on_cameraManualFPSEnable_toggled (bool checked) private slot
Definition at line 563 of file atvmodgui.cpp.
References ATVMod::MsgConfigureCameraData::create(), BasebandSampleSource::getInputMessageQueue(), m_atvMod, MessageQueue::push(), and ui.
 {
     ATVMod::MsgConfigureCameraData* message = ATVMod::MsgConfigureCameraData::create(
             ui->camSelect->currentIndex(),
             ui->cameraManualFPS->value() / 10.0f,
             checked);
     m_atvMod->getInputMessageQueue()->push(message);
 }
on_camSelect_currentIndexChanged
void ATVModGUI::on_camSelect_currentIndexChanged (int index) private slot
Definition at line 557 of file atvmodgui.cpp.
References ATVMod::MsgConfigureCameraIndex::create(), BasebandSampleSource::getInputMessageQueue(), m_atvMod, and MessageQueue::push().
 {
     ATVMod::MsgConfigureCameraIndex* message = ATVMod::MsgConfigureCameraIndex::create(index);
     m_atvMod->getInputMessageQueue()->push(message);
 }
on_channelMute_toggled
void ATVModGUI::on_channelMute_toggled (bool checked) private slot
Definition at line 488 of file atvmodgui.cpp.
References applySettings(), ATVModSettings::m_channelMute, and m_settings.
 {
     m_settings.m_channelMute = checked;
     applySettings();
 }
on_deltaFrequency_changed
void ATVModGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 372 of file atvmodgui.cpp.
References applySettings(), m_channelMarker, ATVModSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = value;
     applySettings();
 }
on_fmExcursion_valueChanged
void ATVModGUI::on_fmExcursion_valueChanged (int value) private slot
Definition at line 394 of file atvmodgui.cpp.
References applySettings(), arg(), ATVModSettings::m_fmExcursion, m_settings, and ui.
 {
     ui->fmExcursionText->setText(tr("%1").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_fmExcursion = value / 1000.0; // pro mill
     applySettings();
 }
on_forceDecimator_toggled
void ATVModGUI::on_forceDecimator_toggled (bool checked) private slot
Definition at line 494 of file atvmodgui.cpp.
References applySettings(), ATVModSettings::m_forceDecimator, and m_settings.
 {
     m_settings.m_forceDecimator = checked;
     applySettings();
 }
on_fps_currentIndexChanged
void ATVModGUI::on_fps_currentIndexChanged (int index) private slot
Definition at line 455 of file atvmodgui.cpp.
References applySettings(), getFPS(), ATVModSettings::m_fps, and m_settings.
 {
     (void) index;
     m_settings.m_fps = getFPS();
     applySettings();
 }
on_imageFileDialog_clicked
void ATVModGUI::on_imageFileDialog_clicked (bool checked) private slot
Definition at line 500 of file atvmodgui.cpp.
References configureImageFileName(), m_imageFileName, and ui.
 {
     (void) checked;
     QString fileName = QFileDialog::getOpenFileName(this,
         tr("Open image file"), ".", tr("Image Files (*.png *.jpg *.bmp *.gif *.tiff)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "")
     {
         m_imageFileName = fileName;
         ui->imageFileText->setText(m_imageFileName);
         configureImageFileName();
     }
 }
on_inputSelect_currentIndexChanged
void ATVModGUI::on_inputSelect_currentIndexChanged (int index) private slot
Definition at line 482 of file atvmodgui.cpp.
References applySettings(), ATVModSettings::m_atvModInput, and m_settings.
 {
     m_settings.m_atvModInput = (ATVModSettings::ATVModInput) index;
     applySettings();
 }
on_invertVideo_clicked
void ATVModGUI::on_invertVideo_clicked (bool checked) private slot
Definition at line 476 of file atvmodgui.cpp.
References applySettings(), ATVModSettings::m_invertedVideo, and m_settings.
 {
     m_settings.m_invertedVideo = checked;
     applySettings();
 }
on_modulation_currentIndexChanged
void ATVModGUI::on_modulation_currentIndexChanged (int index) private slot
Definition at line 379 of file atvmodgui.cpp.
References applySettings(), ATVMod::getEffectiveSampleRate(), m_atvMod, ATVModSettings::m_atvModulation, m_settings, setChannelMarkerBandwidth(), and setRFFiltersSlidersRange().
 {
     m_settings.m_atvModulation = (ATVModSettings::ATVModulation) index;
     setRFFiltersSlidersRange(m_atvMod->getEffectiveSampleRate());
     setChannelMarkerBandwidth();
     applySettings();
 }
on_navTimeSlider_valueChanged
void ATVModGUI::on_navTimeSlider_valueChanged (int value) private slot
Definition at line 542 of file atvmodgui.cpp.
References ATVMod::MsgConfigureVideoFileSourceSeek::create(), BasebandSampleSource::getInputMessageQueue(), m_atvMod, m_enableNavTime, and MessageQueue::push().
 {
     if (m_enableNavTime && ((value >= 0) && (value <= 100)))
     {
         ATVMod::MsgConfigureVideoFileSourceSeek* message = ATVMod::MsgConfigureVideoFileSourceSeek::create(value);
         m_atvMod->getInputMessageQueue()->push(message);
     }
 }
on_nbLines_currentIndexChanged
void ATVModGUI::on_nbLines_currentIndexChanged (int index) private slot
Definition at line 448 of file atvmodgui.cpp.
References applySettings(), getNbLines(), ATVModSettings::m_nbLines, and m_settings.
 {
     (void) index;
     m_settings.m_nbLines = getNbLines();
     applySettings();
 }
on_overlayText_textEdited
void ATVModGUI::on_overlayText_textEdited (const QString & arg1) private slot
Definition at line 588 of file atvmodgui.cpp.
References applySettings(), ATVModSettings::m_overlayText, and m_settings.
 {
     (void) arg1;
     m_settings.m_overlayText = arg1;
     applySettings();
 }
on_overlayTextShow_toggled
void ATVModGUI::on_overlayTextShow_toggled (bool checked) private slot
Definition at line 582 of file atvmodgui.cpp.
References applySettings(), m_settings, and ATVModSettings::m_showOverlayText.
 {
     m_settings.m_showOverlayText = checked;
     applySettings();
 }
on_playCamera_toggled
void ATVModGUI::on_playCamera_toggled (bool checked) private slot
Definition at line 551 of file atvmodgui.cpp.
References applySettings(), ATVModSettings::m_cameraPlay, and m_settings.
 {
     m_settings.m_cameraPlay = checked;
     applySettings();
 }
on_playLoop_toggled
void ATVModGUI::on_playLoop_toggled (bool checked) private slot
Definition at line 528 of file atvmodgui.cpp.
References applySettings(), m_settings, and ATVModSettings::m_videoPlayLoop.
 {
     m_settings.m_videoPlayLoop = checked;
     applySettings();
 }
on_playVideo_toggled
void ATVModGUI::on_playVideo_toggled (bool checked) private slot
Definition at line 534 of file atvmodgui.cpp.
References applySettings(), m_enableNavTime, m_settings, ATVModSettings::m_videoPlay, and ui.
 {
     m_settings.m_videoPlay = checked;
     ui->navTimeSlider->setEnabled(!checked);
     m_enableNavTime = !checked;
     applySettings();
 }
on_rfBW_valueChanged
void ATVModGUI::on_rfBW_valueChanged (int value) private slot
Definition at line 401 of file atvmodgui.cpp.
References applySettings(), arg(), ATVModSettings::m_rfBandwidth, m_rfSliderDivisor, m_settings, setChannelMarkerBandwidth(), and ui.
 {
     ui->rfBWText->setText(QString("%1k").arg((value*m_rfSliderDivisor) / 1000.0, 0, 'f', 1));
     m_settings.m_rfBandwidth = value * m_rfSliderDivisor * 1.0f;
     setChannelMarkerBandwidth();
     applySettings();
 }
on_rfOppBW_valueChanged
void ATVModGUI::on_rfOppBW_valueChanged (int value) private slot
Definition at line 409 of file atvmodgui.cpp.
References applySettings(), arg(), ATVModSettings::m_rfOppBandwidth, m_rfSliderDivisor, m_settings, setChannelMarkerBandwidth(), and ui.
 {
     ui->rfOppBWText->setText(QString("%1k").arg((value*m_rfSliderDivisor) / 1000.0, 0, 'f', 1));
     m_settings.m_rfOppBandwidth = value * m_rfSliderDivisor * 1.0f;
     setChannelMarkerBandwidth();
     applySettings();
 }
on_rfScaling_valueChanged
void ATVModGUI::on_rfScaling_valueChanged (int value) private slot
Definition at line 387 of file atvmodgui.cpp.
References applySettings(), arg(), ATVModSettings::m_rfScalingFactor, m_settings, and ui.
 {
     ui->rfScalingText->setText(tr("%1").arg(value));
     m_settings.m_rfScalingFactor = value * 327.68f;
     applySettings();
 }
on_standard_currentIndexChanged
void ATVModGUI::on_standard_currentIndexChanged (int index) private slot
Definition at line 463 of file atvmodgui.cpp.
References applySettings(), ATVModSettings::m_atvStd, and m_settings.
 {
     m_settings.m_atvStd = (ATVModSettings::ATVStd) index;
     applySettings();
 }
on_uniformLevel_valueChanged
void ATVModGUI::on_uniformLevel_valueChanged (int value) private slot
Definition at line 469 of file atvmodgui.cpp.
References applySettings(), arg(), m_settings, ATVModSettings::m_uniformLevel, and ui.
 {
     ui->uniformLevelText->setText(QString("%1").arg(value));
     m_settings.m_uniformLevel = value / 100.0f;
     applySettings();
 }
on_videoFileDialog_clicked
void ATVModGUI::on_videoFileDialog_clicked (bool checked) private slot
Definition at line 514 of file atvmodgui.cpp.
References configureVideoFileName(), m_videoFileName, and ui.
 {
     (void) checked;
     QString fileName = QFileDialog::getOpenFileName(this,
         tr("Open video file"), ".", tr("Video Files (*.avi *.mpg *.mp4 *.mov *.m4v *.mkv *.vob *.wmv)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "")
     {
         m_videoFileName = fileName;
         ui->videoFileText->setText(m_videoFileName);
         configureVideoFileName();
     }
 }
onMenuDialogCalled
void ATVModGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 615 of file atvmodgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, ATVModSettings::m_inputFrequencyOffset, ATVModSettings::m_reverseAPIAddress, ATVModSettings::m_reverseAPIChannelIndex, ATVModSettings::m_reverseAPIDeviceIndex, ATVModSettings::m_reverseAPIPort, ATVModSettings::m_rgbColor, m_settings, ATVModSettings::m_title, ATVModSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by ATVModGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void ATVModGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 609 of file atvmodgui.cpp.
Referenced by ATVModGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void ATVModGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 69 of file atvmodgui.cpp.
References m_settings, and ATVModSettings::resetToDefaults().
Referenced by ATVModGUI().
 {
     m_settings.resetToDefaults();
 }
serialize()
QByteArray ATVModGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 74 of file atvmodgui.cpp.
References m_settings, and ATVModSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void ATVModGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 63 of file atvmodgui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     applySettings();
 }
setChannelMarkerBandwidth()
void ATVModGUI::setChannelMarkerBandwidth () private
Definition at line 417 of file atvmodgui.cpp.
References ATVModSettings::ATVModulationLSB, ATVModSettings::ATVModulationUSB, ATVModSettings::ATVModulationVestigialLSB, ATVModSettings::ATVModulationVestigialUSB, ChannelMarker::dsb, ChannelMarker::lsb, m_channelMarker, m_rfSliderDivisor, ChannelMarker::setBandwidth(), ChannelMarker::setOppositeBandwidth(), ChannelMarker::setSidebands(), ui, ChannelMarker::usb, ChannelMarker::vlsb, and ChannelMarker::vusb.
Referenced by displaySettings(), on_modulation_currentIndexChanged(), on_rfBW_valueChanged(), and on_rfOppBW_valueChanged().
 {
     if (ui->modulation->currentIndex() == (int) ATVModSettings::ATVModulationLSB)
     {
         m_channelMarker.setBandwidth(-ui->rfBW->value()*m_rfSliderDivisor*2);
         m_channelMarker.setSidebands(ChannelMarker::lsb);
     }
     else if (ui->modulation->currentIndex() == (int) ATVModSettings::ATVModulationVestigialLSB)
     {
         m_channelMarker.setBandwidth(ui->rfBW->value()*m_rfSliderDivisor);
         m_channelMarker.setOppositeBandwidth(ui->rfOppBW->value()*m_rfSliderDivisor);
         m_channelMarker.setSidebands(ChannelMarker::vlsb);
     }
     else if (ui->modulation->currentIndex() == (int) ATVModSettings::ATVModulationUSB)
     {
         m_channelMarker.setBandwidth(ui->rfBW->value()*m_rfSliderDivisor*2);
         m_channelMarker.setSidebands(ChannelMarker::usb);
     }
     else if (ui->modulation->currentIndex() == (int) ATVModSettings::ATVModulationVestigialUSB)
     {
         m_channelMarker.setBandwidth(ui->rfBW->value()*m_rfSliderDivisor);
         m_channelMarker.setOppositeBandwidth(ui->rfOppBW->value()*m_rfSliderDivisor);
         m_channelMarker.setSidebands(ChannelMarker::vusb);
     }
     else
     {
         m_channelMarker.setBandwidth(ui->rfBW->value()*m_rfSliderDivisor);
         m_channelMarker.setSidebands(ChannelMarker::dsb);
     }
 }
setName()
void ATVModGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 49 of file atvmodgui.cpp.
 {
     setObjectName(name);
 }
setRFFiltersSlidersRange()
void ATVModGUI::setRFFiltersSlidersRange (int sampleRate) private
Definition at line 187 of file atvmodgui.cpp.
References arg(), ATVModSettings::ATVModulationLSB, ATVModSettings::ATVModulationUSB, ATVModSettings::ATVModulationVestigialLSB, ATVModSettings::ATVModulationVestigialUSB, m_rfSliderDivisor, and ui.
Referenced by displaySettings(), handleMessage(), and on_modulation_currentIndexChanged().
 {
     int scaleFactor = (int) std::log10(sampleRate/2);
     m_rfSliderDivisor = std::pow(10.0, scaleFactor-1);
     if (sampleRate/m_rfSliderDivisor < 50) {
         m_rfSliderDivisor /= 10;
     }
     if ((ui->modulation->currentIndex() == (int) ATVModSettings::ATVModulationLSB) ||
         (ui->modulation->currentIndex() == (int) ATVModSettings::ATVModulationUSB) ||
         (ui->modulation->currentIndex() == (int) ATVModSettings::ATVModulationVestigialLSB) ||
         (ui->modulation->currentIndex() == (int) ATVModSettings::ATVModulationVestigialUSB))
     {
         ui->rfBW->setMaximum((sampleRate) / (2*m_rfSliderDivisor));
         ui->rfOppBW->setMaximum((sampleRate) / (2*m_rfSliderDivisor));
     }
     else
     {
         ui->rfBW->setMaximum((sampleRate) / m_rfSliderDivisor);
         ui->rfOppBW->setMaximum((sampleRate) / m_rfSliderDivisor);
     }
     ui->rfBWText->setText(QString("%1k").arg((ui->rfBW->value()*m_rfSliderDivisor) / 1000.0, 0, 'f', 1));
     ui->rfOppBWText->setText(QString("%1k").arg((ui->rfOppBW->value()*m_rfSliderDivisor) / 1000.0, 0, 'f', 1));
 }
tick
void ATVModGUI::tick () private slot
Definition at line 807 of file atvmodgui.cpp.
References arg(), ATVModSettings::ATVModInputVideo, ATVMod::MsgConfigureVideoFileSourceStreamTiming::create(), CalcDb::dbPower(), BasebandSampleSource::getInputMessageQueue(), ATVMod::getMagSq(), m_atvMod, m_channelPowerDbAvg, m_tickCount, MessageQueue::push(), and ui.
Referenced by ATVModGUI().
 {
     double powDb = CalcDb::dbPower(m_atvMod->getMagSq());
     m_channelPowerDbAvg(powDb);
     ui->channelPower->setText(tr("%1 dB").arg(m_channelPowerDbAvg.asDouble(), 0, 'f', 1));
     if (((++m_tickCount & 0xf) == 0) && (ui->inputSelect->currentIndex() == (int) ATVModSettings::ATVModInputVideo))
     {
         ATVMod::MsgConfigureVideoFileSourceStreamTiming* message = ATVMod::MsgConfigureVideoFileSourceStreamTiming::create();
         m_atvMod->getInputMessageQueue()->push(message);
     }
 }
updateWithStreamData()
void ATVModGUI::updateWithStreamData () private
Definition at line 820 of file atvmodgui.cpp.
References m_videoFrameRate, m_videoLength, ui, and updateWithStreamTime().
Referenced by handleMessage().
 {
     QTime recordLength(0, 0, 0, 0);
     recordLength = recordLength.addSecs(m_videoLength / m_videoFrameRate);
     QString s_time = recordLength.toString("HH:mm:ss");
     ui->recordLengthText->setText(s_time);
     updateWithStreamTime();
 }
updateWithStreamTime()
void ATVModGUI::updateWithStreamTime () private
Definition at line 829 of file atvmodgui.cpp.
References m_enableNavTime, m_frameCount, m_videoFrameRate, m_videoLength, and ui.
Referenced by handleMessage(), and updateWithStreamData().
 {
     int t_sec = 0;
     int t_msec = 0;
     if (m_videoFrameRate > 0.0f)
     {
         float secs = m_frameCount / m_videoFrameRate;
         t_sec = (int) secs;
         t_msec = (int) ((secs - t_sec) * 1000.0f);
     }
     QTime t(0, 0, 0, 0);
     t = t.addSecs(t_sec);
     t = t.addMSecs(t_msec);
     QString s_timems = t.toString("HH:mm:ss.zzz");
     QString s_time = t.toString("HH:mm:ss");
     ui->relTimeText->setText(s_timems);
     if (!m_enableNavTime)
     {
         float posRatio = (t_sec *  m_videoFrameRate) / m_videoLength;
         ui->navTimeSlider->setValue((int) (posRatio * 100.0));
     }
 }
Member Data Documentation
m_atvMod
ATVMod* ATVModGUI::m_atvMod private
Definition at line 68 of file atvmodgui.h.
Referenced by applySettings(), ATVModGUI(), configureImageFileName(), configureVideoFileName(), displaySettings(), on_cameraManualFPS_valueChanged(), on_cameraManualFPSEnable_toggled(), on_camSelect_currentIndexChanged(), on_modulation_currentIndexChanged(), on_navTimeSlider_valueChanged(), tick(), and ~ATVModGUI().
m_camBusyFPSMessageBox
QMessageBox* ATVModGUI::m_camBusyFPSMessageBox private
Definition at line 78 of file atvmodgui.h.
Referenced by handleMessage().
m_channelMarker
ChannelMarker ATVModGUI::m_channelMarker private
Definition at line 64 of file atvmodgui.h.
Referenced by applySettings(), ATVModGUI(), channelMarkerChangedByCursor(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), onMenuDialogCalled(), setCenterFrequency(), and setChannelMarkerBandwidth().
m_channelPowerDbAvg
MovingAverageUtil<double, double, 20> ATVModGUI::m_channelPowerDbAvg private
Definition at line 69 of file atvmodgui.h.
Referenced by tick().
m_deviceUISet
DeviceUISet* ATVModGUI::m_deviceUISet private
Definition at line 63 of file atvmodgui.h.
Referenced by ATVModGUI(), and ~ATVModGUI().
m_doApplySettings
bool ATVModGUI::m_doApplySettings private
Definition at line 66 of file atvmodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_enableNavTime
bool ATVModGUI::m_enableNavTime private
Definition at line 77 of file atvmodgui.h.
Referenced by on_navTimeSlider_valueChanged(), on_playVideo_toggled(), and updateWithStreamTime().
m_frameCount
int ATVModGUI::m_frameCount private
Definition at line 75 of file atvmodgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_imageFileName
QString ATVModGUI::m_imageFileName private
Definition at line 71 of file atvmodgui.h.
Referenced by configureImageFileName(), and on_imageFileDialog_clicked().
m_inputMessageQueue
MessageQueue ATVModGUI::m_inputMessageQueue private
Definition at line 80 of file atvmodgui.h.
m_pluginAPI
PluginAPI* ATVModGUI::m_pluginAPI private
Definition at line 62 of file atvmodgui.h.
m_rfSliderDivisor
int ATVModGUI::m_rfSliderDivisor private
Definition at line 79 of file atvmodgui.h.
Referenced by displaySettings(), on_rfBW_valueChanged(), on_rfOppBW_valueChanged(), setChannelMarkerBandwidth(), and setRFFiltersSlidersRange().
m_settings
ATVModSettings ATVModGUI::m_settings private
Definition at line 65 of file atvmodgui.h.
Referenced by applySettings(), ATVModGUI(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), handleMessage(), on_channelMute_toggled(), on_deltaFrequency_changed(), on_fmExcursion_valueChanged(), on_forceDecimator_toggled(), on_fps_currentIndexChanged(), on_inputSelect_currentIndexChanged(), on_invertVideo_clicked(), on_modulation_currentIndexChanged(), on_nbLines_currentIndexChanged(), on_overlayText_textEdited(), on_overlayTextShow_toggled(), on_playCamera_toggled(), on_playLoop_toggled(), on_playVideo_toggled(), on_rfBW_valueChanged(), on_rfOppBW_valueChanged(), on_rfScaling_valueChanged(), on_standard_currentIndexChanged(), on_uniformLevel_valueChanged(), onMenuDialogCalled(), resetToDefaults(), and serialize().
m_tickCount
std::size_t ATVModGUI::m_tickCount private
Definition at line 76 of file atvmodgui.h.
Referenced by tick().
m_videoFileName
QString ATVModGUI::m_videoFileName private
Definition at line 72 of file atvmodgui.h.
Referenced by configureVideoFileName(), and on_videoFileDialog_clicked().
m_videoFrameRate
float ATVModGUI::m_videoFrameRate private
video file frame rate
Definition at line 74 of file atvmodgui.h.
Referenced by handleMessage(), updateWithStreamData(), and updateWithStreamTime().
m_videoLength
quint32 ATVModGUI::m_videoLength private
video file length in seconds
Definition at line 73 of file atvmodgui.h.
Referenced by handleMessage(), updateWithStreamData(), and updateWithStreamTime().
ui
Ui::ATVModGUI* ATVModGUI::ui private
Definition at line 61 of file atvmodgui.h.
Referenced by ATVModGUI(), channelMarkerChangedByCursor(), displaySettings(), getFPS(), getNbLines(), handleMessage(), on_cameraManualFPS_valueChanged(), on_cameraManualFPSEnable_toggled(), on_fmExcursion_valueChanged(), on_imageFileDialog_clicked(), on_playVideo_toggled(), on_rfBW_valueChanged(), on_rfOppBW_valueChanged(), on_rfScaling_valueChanged(), on_uniformLevel_valueChanged(), on_videoFileDialog_clicked(), setChannelMarkerBandwidth(), setRFFiltersSlidersRange(), tick(), updateWithStreamData(), updateWithStreamTime(), and ~ATVModGUI().
The documentation for this class was generated from the following files:
plugins/channeltx/modatv/atvmodgui.h
plugins/channeltx/modatv/atvmodgui.cpp