SDRAngel: DeviceLimeSDRShared::MsgReportBuddyChange Class Reference
DeviceLimeSDRShared::MsgReportBuddyChange Class Reference
#include <devicelimesdrshared.h>
Public Member Functions
int getDevSampleRate () const
int getLog2HardDecimInterp () const
uint64_t getCenterFrequency () const
bool getRxElseTx () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportBuddyChange * create (int devSampleRate, int log2HardDecimInterp, uint64_t centerFrequency, bool rxElseTx)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportBuddyChange (int devSampleRate, int log2HardDecimInterp, uint64_t centerFrequency, bool rxElseTx)
Private Attributes
int m_devSampleRate
device/host sample rate
int m_log2HardDecimInterp
log2 of hardware decimation or interpolation
uint64_t m_centerFrequency
Center frequency.
bool m_rxElseTx
tells which side initiated the message
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 32 of file devicelimesdrshared.h.
Constructor & Destructor Documentation
MsgReportBuddyChange()
DeviceLimeSDRShared::MsgReportBuddyChange::MsgReportBuddyChange (int devSampleRate, int log2HardDecimInterp, uint64_t centerFrequency, bool rxElseTx) inline private
Definition at line 60 of file devicelimesdrshared.h.
                                :
             Message(),
             m_devSampleRate(devSampleRate),
             m_log2HardDecimInterp(log2HardDecimInterp),
             m_centerFrequency(centerFrequency),
             m_rxElseTx(rxElseTx)
         { }
Member Function Documentation
create()
static MsgReportBuddyChange* DeviceLimeSDRShared::MsgReportBuddyChange::create (int devSampleRate, int log2HardDecimInterp, uint64_t centerFrequency, bool rxElseTx) inline static
Definition at line 41 of file devicelimesdrshared.h.
Referenced by LimeSDROutput::applySettings(), LimeSDRInput::applySettings(), LimeSDROutput::handleMessage(), and LimeSDRInput::handleMessage().
         {
             return new MsgReportBuddyChange(
                     devSampleRate,
                     log2HardDecimInterp,
                     centerFrequency,
                     rxElseTx);
         }
getCenterFrequency()
uint64_t DeviceLimeSDRShared::MsgReportBuddyChange::getCenterFrequency () const inline
Definition at line 38 of file devicelimesdrshared.h.
Referenced by LimeSDRInputGUI::handleMessage(), LimeSDROutputGUI::handleMessage(), LimeSDROutput::handleMessage(), and LimeSDRInput::handleMessage().
 { return m_centerFrequency; }
getDevSampleRate()
int DeviceLimeSDRShared::MsgReportBuddyChange::getDevSampleRate () const inline
Definition at line 36 of file devicelimesdrshared.h.
Referenced by LimeSDRInputGUI::handleMessage(), LimeSDROutputGUI::handleMessage(), LimeSDROutput::handleMessage(), and LimeSDRInput::handleMessage().
 { return m_devSampleRate; }
getLog2HardDecimInterp()
int DeviceLimeSDRShared::MsgReportBuddyChange::getLog2HardDecimInterp () const inline
Definition at line 37 of file devicelimesdrshared.h.
Referenced by LimeSDRInputGUI::handleMessage(), LimeSDROutputGUI::handleMessage(), LimeSDROutput::handleMessage(), and LimeSDRInput::handleMessage().
 { return m_log2HardDecimInterp; }
getRxElseTx()
bool DeviceLimeSDRShared::MsgReportBuddyChange::getRxElseTx () const inline
Definition at line 39 of file devicelimesdrshared.h.
Referenced by LimeSDRInputGUI::handleMessage(), LimeSDROutputGUI::handleMessage(), LimeSDROutput::handleMessage(), and LimeSDRInput::handleMessage().
 { return m_rxElseTx; }
Member Data Documentation
m_centerFrequency
uint64_t DeviceLimeSDRShared::MsgReportBuddyChange::m_centerFrequency private
Center frequency.
Definition at line 57 of file devicelimesdrshared.h.
m_devSampleRate
int DeviceLimeSDRShared::MsgReportBuddyChange::m_devSampleRate private
device/host sample rate
Definition at line 55 of file devicelimesdrshared.h.
m_log2HardDecimInterp
int DeviceLimeSDRShared::MsgReportBuddyChange::m_log2HardDecimInterp private
log2 of hardware decimation or interpolation
Definition at line 56 of file devicelimesdrshared.h.
m_rxElseTx
bool DeviceLimeSDRShared::MsgReportBuddyChange::m_rxElseTx private
tells which side initiated the message
Definition at line 58 of file devicelimesdrshared.h.
The documentation for this class was generated from the following file:
devices/limesdr/devicelimesdrshared.h