SDRAngel: SWGSDRangel::SWGHttpRequestWorker Class Reference
SWGSDRangel::SWGHttpRequestWorker Class Reference
#include <SWGHttpRequest.h>
Inherits QObject.
Signals
void on_execution_finished (SWGHttpRequestWorker *worker)
Public Member Functions
SWGHttpRequestWorker (QObject *parent=0)
virtual ~SWGHttpRequestWorker ()
QString http_attribute_encode (QString attribute_name, QString input)
void execute (SWGHttpRequestInput *input)
Public Attributes
QByteArray response
QNetworkReply::NetworkError error_type
QString error_str
Static Public Attributes
static QSslConfiguration * sslDefaultConfiguration
Private Slots
void on_manager_finished (QNetworkReply *reply)
Private Attributes
QNetworkAccessManager * manager
Detailed Description
Definition at line 65 of file SWGHttpRequest.h.
Constructor & Destructor Documentation
SWGHttpRequestWorker()
SWGSDRangel::SWGHttpRequestWorker::SWGHttpRequestWorker (QObject * parent = 0) explicit
Definition at line 53 of file SWGHttpRequest.cpp.
References manager, and on_manager_finished().
     : QObject(parent), manager(nullptr)
 {
     qsrand(QDateTime::currentDateTime().toTime_t());
     manager = new QNetworkAccessManager(this);
     connect(manager, SIGNAL(finished(QNetworkReply*)), this, SLOT(on_manager_finished(QNetworkReply*)));
 }
~SWGHttpRequestWorker()
SWGSDRangel::SWGHttpRequestWorker::~SWGHttpRequestWorker () virtual
Definition at line 62 of file SWGHttpRequest.cpp.
{
 }
Member Function Documentation
execute()
void SWGSDRangel::SWGHttpRequestWorker::execute (SWGHttpRequestInput * input)
Definition at line 113 of file SWGHttpRequest.cpp.
References SWGSDRangel::ADDRESS, arg(), error_str, error_type, SWGSDRangel::SWGHttpRequestInput::files, SWGSDRangel::SWGHttpRequestInput::headers, http_attribute_encode(), SWGSDRangel::SWGHttpRequestInput::http_method, manager, SWGSDRangel::MULTIPART, SWGSDRangel::NOT_SET, SWGSDRangel::SWGHttpRequestInput::request_body, response, sslDefaultConfiguration, SWGSDRangel::URL_ENCODED, SWGSDRangel::SWGHttpRequestInput::url_str, SWGSDRangel::SWGHttpRequestInput::var_layout, and SWGSDRangel::SWGHttpRequestInput::vars.
Referenced by SWGSDRangel::SWGDeviceSetApi::devicesetChannelDelete(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelPost(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelReportGet(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsGet(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPatch(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPut(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelsReportGet(), SWGSDRangel::SWGDeviceSetApi::devicesetDevicePut(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceReportGet(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunDelete(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunGet(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunPost(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsGet(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPatch(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPut(), SWGSDRangel::SWGDeviceSetApi::devicesetFocusPatch(), SWGSDRangel::SWGDeviceSetApi::devicesetGet(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesDelete(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesGet(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPatch(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPut(), SWGSDRangel::SWGInstanceApi::instanceAMBESerialGet(), SWGSDRangel::SWGInstanceApi::instanceAudioGet(), SWGSDRangel::SWGInstanceApi::instanceAudioInputCleanupPatch(), SWGSDRangel::SWGInstanceApi::instanceAudioInputDelete(), SWGSDRangel::SWGInstanceApi::instanceAudioInputPatch(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputCleanupPatch(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputDelete(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputPatch(), SWGSDRangel::SWGInstanceApi::instanceChannels(), SWGSDRangel::SWGInstanceApi::instanceConfig(), SWGSDRangel::SWGInstanceApi::instanceDelete(), SWGSDRangel::SWGInstanceApi::instanceDevices(), SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetDelete(), SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetPost(), SWGSDRangel::SWGInstanceApi::instanceDeviceSetsGet(), SWGSDRangel::SWGInstanceApi::instanceLocationGet(), SWGSDRangel::SWGInstanceApi::instanceLocationPut(), SWGSDRangel::SWGInstanceApi::instanceLoggingGet(), SWGSDRangel::SWGInstanceApi::instanceLoggingPut(), SWGSDRangel::SWGInstanceApi::instancePresetDelete(), SWGSDRangel::SWGInstanceApi::instancePresetFilePost(), SWGSDRangel::SWGInstanceApi::instancePresetFilePut(), SWGSDRangel::SWGInstanceApi::instancePresetGet(), SWGSDRangel::SWGInstanceApi::instancePresetPatch(), SWGSDRangel::SWGInstanceApi::instancePresetPost(), SWGSDRangel::SWGInstanceApi::instancePresetPut(), and SWGSDRangel::SWGInstanceApi::instanceSummary().
{
     // reset variables
     QByteArray request_content = "";
     response = "";
     error_type = QNetworkReply::NoError;
     error_str = "";
     bool isFormData = false;
     // decide on the variable layout
     if (input->files.length() > 0) {
         input->var_layout = MULTIPART;
     }
     if (input->var_layout == NOT_SET) {
         input->var_layout = input->http_method == "GET" || input->http_method == "HEAD" ? ADDRESS : URL_ENCODED;
     }
     // prepare request content
     QString boundary = "";
     if (input->var_layout == ADDRESS || input->var_layout == URL_ENCODED) {
         // variable layout is ADDRESS or URL_ENCODED
         if (input->vars.count() > 0) {
             bool first = true;
             isFormData = true;
             foreach (QString key, input->vars.keys()) {
                 if (!first) {
                     request_content.append("&");
                 }
                 first = false;
                 request_content.append(QUrl::toPercentEncoding(key));
                 request_content.append("=");
                 request_content.append(QUrl::toPercentEncoding(input->vars.value(key)));
             }
             if (input->var_layout == ADDRESS) {
                 input->url_str += "?" + request_content;
                 request_content = "";
             }
         }
     }
     else {
         // variable layout is MULTIPART
         boundary = "__-----------------------"
             + QString::number(QDateTime::currentDateTime().toTime_t())
             + QString::number(qrand());
         QString boundary_delimiter = "--";
         QString new_line = "\r\n";
         // add variables
         foreach (QString key, input->vars.keys()) {
             // add boundary
             request_content.append(boundary_delimiter);
             request_content.append(boundary);
             request_content.append(new_line);
             // add header
             request_content.append("Content-Disposition: form-data; ");
             request_content.append(http_attribute_encode("name", key));
             request_content.append(new_line);
             request_content.append("Content-Type: text/plain");
             request_content.append(new_line);
             // add header to body splitter
             request_content.append(new_line);
             // add variable content
             request_content.append(input->vars.value(key));
             request_content.append(new_line);
         }
         // add files
         for (QList<SWGHttpRequestInputFileElement>::iterator file_info = input->files.begin(); file_info != input->files.end(); file_info++) {
             QFileInfo fi(file_info->local_filename);
             // ensure necessary variables are available
             if (
                 file_info->local_filename == nullptr || file_info->local_filename.isEmpty()
                 || file_info->variable_name == nullptr || file_info->variable_name.isEmpty()
                 || !fi.exists() || !fi.isFile() || !fi.isReadable()
             ) {
                 // silent abort for the current file
                 continue;
             }
             QFile file(file_info->local_filename);
             if (!file.open(QIODevice::ReadOnly)) {
                 // silent abort for the current file
                 continue;
             }
             // ensure filename for the request
             if (file_info->request_filename == nullptr || file_info->request_filename.isEmpty()) {
                 file_info->request_filename = fi.fileName();
                 if (file_info->request_filename.isEmpty()) {
                     file_info->request_filename = "file";
                 }
             }
             // add boundary
             request_content.append(boundary_delimiter);
             request_content.append(boundary);
             request_content.append(new_line);
             // add header
             request_content.append(QString("Content-Disposition: form-data; %1; %2").arg(
                 http_attribute_encode("name", file_info->variable_name),
                 http_attribute_encode("filename", file_info->request_filename)
             ));
             request_content.append(new_line);
             if (file_info->mime_type != nullptr && !file_info->mime_type.isEmpty()) {
                 request_content.append("Content-Type: ");
                 request_content.append(file_info->mime_type);
                 request_content.append(new_line);
             }
             request_content.append("Content-Transfer-Encoding: binary");
             request_content.append(new_line);
             // add header to body splitter
             request_content.append(new_line);
             // add file content
             request_content.append(file.readAll());
             request_content.append(new_line);
             file.close();
         }
         // add end of body
         request_content.append(boundary_delimiter);
         request_content.append(boundary);
         request_content.append(boundary_delimiter);
     }
     if(input->request_body.size() > 0) {
         qDebug() << "got a request body";
         request_content.clear();
         request_content.append(input->request_body);
     }
     // prepare connection
     QNetworkRequest request = QNetworkRequest(QUrl(input->url_str));
     if (SWGHttpRequestWorker::sslDefaultConfiguration != nullptr) {
         request.setSslConfiguration(*SWGHttpRequestWorker::sslDefaultConfiguration);
     }
     request.setRawHeader("User-Agent", "Swagger-Client");
     foreach(QString key, input->headers.keys()) {
         request.setRawHeader(key.toStdString().c_str(), input->headers.value(key).toStdString().c_str());
     }
     if (request_content.size() > 0 && !isFormData) {
         request.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     }
     else if (input->var_layout == URL_ENCODED) {
         request.setHeader(QNetworkRequest::ContentTypeHeader, "application/x-www-form-urlencoded");
     }
     else if (input->var_layout == MULTIPART) {
         request.setHeader(QNetworkRequest::ContentTypeHeader, "multipart/form-data; boundary=" + boundary);
     }
     if (input->http_method == "GET") {
         manager->get(request);
     }
     else if (input->http_method == "POST") {
         manager->post(request, request_content);
     }
     else if (input->http_method == "PUT") {
         manager->put(request, request_content);
     }
     else if (input->http_method == "HEAD") {
         manager->head(request);
     }
     else if (input->http_method == "DELETE") {
         manager->deleteResource(request);
     }
     else {
 #if (QT_VERSION >= 0x050800)
         manager->sendCustomRequest(request, input->http_method.toLatin1(), request_content);
 #else
         QBuffer *buffer = new QBuffer;
         buffer->setData(request_content);
         buffer->open(QIODevice::ReadOnly);
         QNetworkReply* reply = manager->sendCustomRequest(request, input->http_method.toLatin1(), buffer);
         buffer->setParent(reply);
 #endif
     }
 }
http_attribute_encode()
QString SWGSDRangel::SWGHttpRequestWorker::http_attribute_encode (QString attribute_name, QString input)
Definition at line 65 of file SWGHttpRequest.cpp.
References i.
Referenced by execute().
{
     // result structure follows RFC 5987
     bool need_utf_encoding = false;
     QString result = "";
     QByteArray input_c = input.toLocal8Bit();
     char c;
     for (int i = 0; i < input_c.length(); i++) {
         c = input_c.at(i);
         if (c == '\\' || c == '/' || c == '\0' || c < ' ' || c > '~') {
             // ignore and request utf-8 version
             need_utf_encoding = true;
         }
         else if (c == '"') {
             result += "\\\"";
         }
         else {
             result += c;
         }
     }
     if (result.length() == 0) {
         need_utf_encoding = true;
     }
     if (!need_utf_encoding) {
         // return simple version
         return QString("%1=\"%2\"").arg(attribute_name, result);
     }
     QString result_utf8 = "";
     for (int i = 0; i < input_c.length(); i++) {
         c = input_c.at(i);
         if (
             (c >= '0' && c <= '9')
             || (c >= 'A' && c <= 'Z')
             || (c >= 'a' && c <= 'z')
         ) {
             result_utf8 += c;
         }
         else {
             result_utf8 += "%" + QString::number(static_cast<unsigned char>(input_c.at(i)), 16).toUpper();
         }
     }
     // return enhanced version with UTF-8 support
     return QString("%1=\"%2\"; %1*=utf-8''%3").arg(attribute_name, result, result_utf8);
 }
on_execution_finished
void SWGSDRangel::SWGHttpRequestWorker::on_execution_finished (SWGHttpRequestWorker * worker) signal
Referenced by SWGSDRangel::SWGDeviceSetApi::devicesetChannelDelete(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelPost(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelReportGet(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsGet(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPatch(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPut(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelsReportGet(), SWGSDRangel::SWGDeviceSetApi::devicesetDevicePut(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceReportGet(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunDelete(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunGet(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunPost(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsGet(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPatch(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPut(), SWGSDRangel::SWGDeviceSetApi::devicesetFocusPatch(), SWGSDRangel::SWGDeviceSetApi::devicesetGet(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesDelete(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesGet(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPatch(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPut(), SWGSDRangel::SWGInstanceApi::instanceAMBESerialGet(), SWGSDRangel::SWGInstanceApi::instanceAudioGet(), SWGSDRangel::SWGInstanceApi::instanceAudioInputCleanupPatch(), SWGSDRangel::SWGInstanceApi::instanceAudioInputDelete(), SWGSDRangel::SWGInstanceApi::instanceAudioInputPatch(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputCleanupPatch(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputDelete(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputPatch(), SWGSDRangel::SWGInstanceApi::instanceChannels(), SWGSDRangel::SWGInstanceApi::instanceConfig(), SWGSDRangel::SWGInstanceApi::instanceDelete(), SWGSDRangel::SWGInstanceApi::instanceDevices(), SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetDelete(), SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetPost(), SWGSDRangel::SWGInstanceApi::instanceDeviceSetsGet(), SWGSDRangel::SWGInstanceApi::instanceLocationGet(), SWGSDRangel::SWGInstanceApi::instanceLocationPut(), SWGSDRangel::SWGInstanceApi::instanceLoggingGet(), SWGSDRangel::SWGInstanceApi::instanceLoggingPut(), SWGSDRangel::SWGInstanceApi::instancePresetDelete(), SWGSDRangel::SWGInstanceApi::instancePresetFilePost(), SWGSDRangel::SWGInstanceApi::instancePresetFilePut(), SWGSDRangel::SWGInstanceApi::instancePresetGet(), SWGSDRangel::SWGInstanceApi::instancePresetPatch(), SWGSDRangel::SWGInstanceApi::instancePresetPost(), SWGSDRangel::SWGInstanceApi::instancePresetPut(), SWGSDRangel::SWGInstanceApi::instanceSummary(), and on_manager_finished().
on_manager_finished
void SWGSDRangel::SWGHttpRequestWorker::on_manager_finished (QNetworkReply * reply) private slot
Definition at line 313 of file SWGHttpRequest.cpp.
References error_str, error_type, on_execution_finished(), response, and sslDefaultConfiguration.
Referenced by SWGHttpRequestWorker().
{
     error_type = reply->error();
     response = reply->readAll();
     error_str = reply->errorString();
     reply->deleteLater();
     emit on_execution_finished(this);
 }
Member Data Documentation
error_str
QString SWGSDRangel::SWGHttpRequestWorker::error_str
Definition at line 71 of file SWGHttpRequest.h.
Referenced by SWGSDRangel::SWGDeviceSetApi::devicesetChannelDeleteCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelPostCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelReportGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPatchCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPutCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelsReportGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDevicePutCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceReportGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunDeleteCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunPostCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPatchCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPutCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetFocusPatchCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetGetCallback(), execute(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesGetCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPutCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBESerialGetCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioGetCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioInputCleanupPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioInputDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioInputPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputCleanupPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceChannelsCallback(), SWGSDRangel::SWGInstanceApi::instanceConfigCallback(), SWGSDRangel::SWGInstanceApi::instanceDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceDevicesCallback(), SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetDeleteCallback(), SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetPostCallback(), SWGSDRangel::SWGInstanceApi::instanceDeviceSetsGetCallback(), SWGSDRangel::SWGInstanceApi::instanceLocationGetCallback(), SWGSDRangel::SWGInstanceApi::instanceLocationPutCallback(), SWGSDRangel::SWGInstanceApi::instanceLoggingGetCallback(), SWGSDRangel::SWGInstanceApi::instanceLoggingPutCallback(), SWGSDRangel::SWGInstanceApi::instancePresetDeleteCallback(), SWGSDRangel::SWGInstanceApi::instancePresetFilePostCallback(), SWGSDRangel::SWGInstanceApi::instancePresetFilePutCallback(), SWGSDRangel::SWGInstanceApi::instancePresetGetCallback(), SWGSDRangel::SWGInstanceApi::instancePresetPatchCallback(), SWGSDRangel::SWGInstanceApi::instancePresetPostCallback(), SWGSDRangel::SWGInstanceApi::instancePresetPutCallback(), SWGSDRangel::SWGInstanceApi::instanceSummaryCallback(), and on_manager_finished().
error_type
QNetworkReply::NetworkError SWGSDRangel::SWGHttpRequestWorker::error_type
Definition at line 70 of file SWGHttpRequest.h.
Referenced by SWGSDRangel::SWGDeviceSetApi::devicesetChannelDeleteCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelPostCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelReportGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPatchCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPutCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelsReportGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDevicePutCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceReportGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunDeleteCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunPostCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPatchCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPutCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetFocusPatchCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetGetCallback(), execute(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesGetCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPutCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBESerialGetCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioGetCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioInputCleanupPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioInputDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioInputPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputCleanupPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceChannelsCallback(), SWGSDRangel::SWGInstanceApi::instanceConfigCallback(), SWGSDRangel::SWGInstanceApi::instanceDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceDevicesCallback(), SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetDeleteCallback(), SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetPostCallback(), SWGSDRangel::SWGInstanceApi::instanceDeviceSetsGetCallback(), SWGSDRangel::SWGInstanceApi::instanceLocationGetCallback(), SWGSDRangel::SWGInstanceApi::instanceLocationPutCallback(), SWGSDRangel::SWGInstanceApi::instanceLoggingGetCallback(), SWGSDRangel::SWGInstanceApi::instanceLoggingPutCallback(), SWGSDRangel::SWGInstanceApi::instancePresetDeleteCallback(), SWGSDRangel::SWGInstanceApi::instancePresetFilePostCallback(), SWGSDRangel::SWGInstanceApi::instancePresetFilePutCallback(), SWGSDRangel::SWGInstanceApi::instancePresetGetCallback(), SWGSDRangel::SWGInstanceApi::instancePresetPatchCallback(), SWGSDRangel::SWGInstanceApi::instancePresetPostCallback(), SWGSDRangel::SWGInstanceApi::instancePresetPutCallback(), SWGSDRangel::SWGInstanceApi::instanceSummaryCallback(), and on_manager_finished().
manager
QNetworkAccessManager* SWGSDRangel::SWGHttpRequestWorker::manager private
Definition at line 84 of file SWGHttpRequest.h.
Referenced by execute(), and SWGHttpRequestWorker().
response
QByteArray SWGSDRangel::SWGHttpRequestWorker::response
Definition at line 69 of file SWGHttpRequest.h.
Referenced by SWGSDRangel::SWGDeviceSetApi::devicesetChannelDeleteCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelPostCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelReportGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPatchCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPutCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelsReportGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDevicePutCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceReportGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunDeleteCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunPostCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPatchCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPutCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetFocusPatchCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetGetCallback(), execute(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesGetCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPutCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBESerialGetCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioGetCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioInputCleanupPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioInputDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioInputPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputCleanupPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceChannelsCallback(), SWGSDRangel::SWGInstanceApi::instanceConfigCallback(), SWGSDRangel::SWGInstanceApi::instanceDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceDevicesCallback(), SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetDeleteCallback(), SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetPostCallback(), SWGSDRangel::SWGInstanceApi::instanceDeviceSetsGetCallback(), SWGSDRangel::SWGInstanceApi::instanceLocationGetCallback(), SWGSDRangel::SWGInstanceApi::instanceLocationPutCallback(), SWGSDRangel::SWGInstanceApi::instanceLoggingGetCallback(), SWGSDRangel::SWGInstanceApi::instanceLoggingPutCallback(), SWGSDRangel::SWGInstanceApi::instancePresetDeleteCallback(), SWGSDRangel::SWGInstanceApi::instancePresetFilePostCallback(), SWGSDRangel::SWGInstanceApi::instancePresetFilePutCallback(), SWGSDRangel::SWGInstanceApi::instancePresetGetCallback(), SWGSDRangel::SWGInstanceApi::instancePresetPatchCallback(), SWGSDRangel::SWGInstanceApi::instancePresetPostCallback(), SWGSDRangel::SWGInstanceApi::instancePresetPutCallback(), SWGSDRangel::SWGInstanceApi::instanceSummaryCallback(), and on_manager_finished().
sslDefaultConfiguration
QSslConfiguration * SWGSDRangel::SWGHttpRequestWorker::sslDefaultConfiguration static
Definition at line 78 of file SWGHttpRequest.h.
Referenced by execute(), and on_manager_finished().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGHttpRequest.h
swagger/sdrangel/code/qt5/client/SWGHttpRequest.cpp