SDRAngel: FreeDVDemod::MsgConfigureChannelizer Class Reference
FreeDVDemod::MsgConfigureChannelizer Class Reference
#include <freedvdemod.h>
Public Member Functions
int getSampleRate () const
int getCenterFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (int sampleRate, int centerFrequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (int sampleRate, int centerFrequency)
Private Attributes
int m_sampleRate
int m_centerFrequency
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 89 of file freedvdemod.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
FreeDVDemod::MsgConfigureChannelizer::MsgConfigureChannelizer (int sampleRate, int centerFrequency) inline private
Definition at line 105 of file freedvdemod.h.
References FreeDVDemod::FreeDVDemod(), and FreeDVDemod::~FreeDVDemod().
                                                                      :
             Message(),
             m_sampleRate(sampleRate),
             m_centerFrequency(centerFrequency)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* FreeDVDemod::MsgConfigureChannelizer::create (int sampleRate, int centerFrequency) inline static
Definition at line 96 of file freedvdemod.h.
Referenced by FreeDVDemod::applyFreeDVMode(), FreeDVDemodGUI::applySettings(), and FreeDVDemod::webapiSettingsPutPatch().
         {
             return new MsgConfigureChannelizer(sampleRate, centerFrequency);
         }
getCenterFrequency()
int FreeDVDemod::MsgConfigureChannelizer::getCenterFrequency () const inline
Definition at line 94 of file freedvdemod.h.
Referenced by FreeDVDemod::handleMessage().
 { return m_centerFrequency; }
getSampleRate()
int FreeDVDemod::MsgConfigureChannelizer::getSampleRate () const inline
Definition at line 93 of file freedvdemod.h.
Referenced by FreeDVDemod::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_centerFrequency
int FreeDVDemod::MsgConfigureChannelizer::m_centerFrequency private
Definition at line 103 of file freedvdemod.h.
m_sampleRate
int FreeDVDemod::MsgConfigureChannelizer::m_sampleRate private
Definition at line 102 of file freedvdemod.h.
The documentation for this class was generated from the following file:
plugins/channelrx/demodfreedv/freedvdemod.h