SDRAngel: FFTWindow Class Reference
FFTWindow Class Reference
#include <fftwindow.h>
Public Types
enum Function {
Bartlett, BlackmanHarris, Flattop, Hamming,
Hanning, Rectangle
}
Public Member Functions
void create (Function function, int n)
void apply (const std::vector< Real > &in, std::vector< Real > *out)
void apply (const std::vector< Complex > &in, std::vector< Complex > *out)
void apply (const Complex *in, Complex *out)
Static Private Member Functions
static Real flatTop (Real n, Real i)
static Real bartlett (Real n, Real i)
static Real blackmanHarris (Real n, Real i)
static Real hamming (Real n, Real i)
static Real hanning (Real n, Real i)
static Real rectangle (Real, Real)
Private Attributes
std::vector< float > m_window
Detailed Description
Definition at line 31 of file fftwindow.h.
Member Enumeration Documentation
Function
enum FFTWindow::Function
Enumerator
Bartlett
BlackmanHarris
Flattop
Hamming
Hanning
Rectangle
Definition at line 33 of file fftwindow.h.
                   {
         Bartlett,
         BlackmanHarris,
         Flattop,
         Hamming,
         Hanning,
         Rectangle
     };
Member Function Documentation
apply() [1/3]
void FFTWindow::apply (const std::vector< Real > & in, std::vector< Real > * out)
Definition at line 58 of file fftwindow.cpp.
References i, and m_window.
Referenced by SpectrumVis::feed().
 {
     for(size_t i = 0; i < m_window.size(); i++)
         (*out)[i] = in[i] * m_window[i];
 }
apply() [2/3]
void FFTWindow::apply (const std::vector< Complex > & in, std::vector< Complex > * out)
Definition at line 64 of file fftwindow.cpp.
References i, and m_window.
 {
     for(size_t i = 0; i < m_window.size(); i++)
         (*out)[i] = in[i] * m_window[i];
 }
apply() [3/3]
void FFTWindow::apply (const Complex * in, Complex * out)
Definition at line 70 of file fftwindow.cpp.
References i, and m_window.
 {
     for(size_t i = 0; i < m_window.size(); i++)
         out[i] = in[i] * m_window[i];
 }
bartlett()
static Real FFTWindow::bartlett (Real n, Real i) inline static private
Definition at line 56 of file fftwindow.h.
Referenced by create().
     {
         // amplitude correction = 2.0
         return (2.0 / (n - 1.0)) * ( (n - 1.0) / 2.0 - fabs(i - (n - 1.0) / 2.0)) * 2.0;
     }
blackmanHarris()
static Real FFTWindow::blackmanHarris (Real n, Real i) inline static private
Definition at line 62 of file fftwindow.h.
References cos(), and M_PI.
Referenced by create().
     {
         // amplitude correction = 2.79
         return (0.35875 - 0.48829 * cos((2.0 * M_PI * i) / n) + 0.14128 * cos((4.0 * M_PI * i) / n) - 0.01168 * cos((6.0 * M_PI * i) / n)) * 2.79;
     }
create()
void FFTWindow::create (Function function, int n)
Definition at line 21 of file fftwindow.cpp.
References Bartlett, bartlett(), BlackmanHarris, blackmanHarris(), Flattop, flatTop(), Hamming, hamming(), Hanning, hanning(), i, m_window, Rectangle, and rectangle().
Referenced by SpectrumVis::handleConfigure().
 {
     Real (*wFunc)(Real n, Real i);
     m_window.clear();
     switch(function) {
         case Flattop:
             wFunc = flatTop;
             break;
         case Bartlett:
             wFunc = bartlett;
             break;
         case BlackmanHarris:
             wFunc = blackmanHarris;
             break;
         case Hamming:
             wFunc = hamming;
             break;
         case Hanning:
             wFunc = hanning;
             break;
         case Rectangle:
         default:
             wFunc = rectangle;
             break;
     }
     for(int i = 0; i < n; i++)
         m_window.push_back(wFunc(n, i));
 }
flatTop()
static Real FFTWindow::flatTop (Real n, Real i) inline static private
Definition at line 50 of file fftwindow.h.
References cos(), and M_PI.
Referenced by create().
     {
         // correction ?
         return 1.0 - 1.93 * cos((2.0 * M_PI * i) / n) + 1.29 * cos((4.0 * M_PI * i) / n) - 0.388 * cos((6.0 * M_PI * i) / n) + 0.03222 * cos((8.0 * M_PI * i) / n);
     }
hamming()
static Real FFTWindow::hamming (Real n, Real i) inline static private
Definition at line 68 of file fftwindow.h.
References cos(), and M_PI.
Referenced by create().
     {
         // amplitude correction = 1.855, energy correction = 1.586
         return (0.54 - 0.46 * cos((2.0 * M_PI * i) / n)) * 1.855;
     }
hanning()
static Real FFTWindow::hanning (Real n, Real i) inline static private
Definition at line 74 of file fftwindow.h.
References cos(), and M_PI.
Referenced by create().
     {
         // amplitude correction = 2.0, energy correction = 1.633
         return (0.5 - 0.5 * cos((2.0 * M_PI * i) / n)) * 2.0;
     }
rectangle()
static Real FFTWindow::rectangle (Real , Real) inline static private
Definition at line 80 of file fftwindow.h.
Referenced by create().
     {
         return 1.0;
     }
Member Data Documentation
m_window
std::vector<float> FFTWindow::m_window private
Definition at line 48 of file fftwindow.h.
Referenced by apply(), and create().
The documentation for this class was generated from the following files:
sdrbase/dsp/fftwindow.h
sdrbase/dsp/fftwindow.cpp