SDRAngel: RemoteSink Class Reference
RemoteSink Class Reference
#include <remotesink.h>
Classes
class MsgConfigureChannelizer
class MsgConfigureRemoteSink
class MsgSampleRateNotification
Signals
void dataBlockAvailable (RemoteDataBlock *dataBlock)
Public Member Functions
RemoteSink (DeviceAPI *deviceAPI)
virtual ~RemoteSink ()
virtual void destroy ()
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool po)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
void setCenterFrequency (uint64_t centerFrequency)
void setSampleRate (uint32_t sampleRate)
void setNbBlocksFEC (int nbBlocksFEC)
void setTxDelay (int txDelay, int nbBlocksFEC)
void setDataAddress (const QString &address)
void setDataPort (uint16_t port)
void setChannelizer (unsigned int log2Decim, unsigned int filterChainHash)
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.remotesink"
static const QString m_channelId = "RemoteSink"
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applySettings (const RemoteSinkSettings &settings, bool force=false)
void validateFilterChainHash (RemoteSinkSettings &settings)
void calculateFrequencyOffset ()
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const RemoteSinkSettings &settings)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const RemoteSinkSettings &settings, bool force)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
bool m_running
RemoteSinkSettings m_settings
RemoteSinkThread * m_sinkThread
int m_txBlockIndex
Current index in blocks to transmit in the Tx row.
uint16_t m_frameCount
transmission frame count
int m_sampleIndex
Current sample index in protected block data.
RemoteSuperBlock m_superBlock
RemoteMetaDataFEC m_currentMetaFEC
RemoteDataBlock * m_dataBlock
QMutex m_dataBlockMutex
uint64_t m_centerFrequency
int64_t m_frequencyOffset
uint32_t m_sampleRate
uint32_t m_deviceSampleRate
int m_nbBlocksFEC
int m_txDelay
QString m_dataAddress
uint16_t m_dataPort
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 43 of file remotesink.h.
Constructor & Destructor Documentation
RemoteSink()
RemoteSink::RemoteSink (DeviceAPI * deviceAPI)
Definition at line 58 of file remotesink.cpp.
References DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), m_channelId, m_channelizer, m_deviceAPI, m_networkManager, m_threadedChannelizer, and networkManagerFinished().
Referenced by RemoteSink::MsgConfigureChannelizer::MsgConfigureChannelizer().
                                            :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(deviceAPI),
         m_running(false),
         m_sinkThread(0),
         m_txBlockIndex(0),
         m_frameCount(0),
         m_sampleIndex(0),
         m_dataBlock(0),
         m_centerFrequency(0),
         m_frequencyOffset(0),
         m_sampleRate(48000),
         m_deviceSampleRate(48000),
         m_nbBlocksFEC(0),
         m_txDelay(35),
         m_dataAddress("127.0.0.1"),
         m_dataPort(9090)
 {
     setObjectName(m_channelId);
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~RemoteSink()
RemoteSink::~RemoteSink () virtual
Definition at line 87 of file remotesink.cpp.
References m_channelizer, RemoteTxControlBlock::m_complete, m_dataBlock, m_dataBlockMutex, m_deviceAPI, m_networkManager, m_threadedChannelizer, RemoteDataBlock::m_txControlBlock, networkManagerFinished(), DeviceAPI::removeChannelSink(), and DeviceAPI::removeChannelSinkAPI().
Referenced by RemoteSink::MsgConfigureChannelizer::MsgConfigureChannelizer().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     m_dataBlockMutex.lock();
     if (m_dataBlock && !m_dataBlock->m_txControlBlock.m_complete) {
         delete m_dataBlock;
     }
     m_dataBlockMutex.unlock();
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
 }
Member Function Documentation
applySettings()
void RemoteSink::applySettings (const RemoteSinkSettings & settings, bool force = false) private
Definition at line 366 of file remotesink.cpp.
References RemoteSinkSettings::m_dataAddress, m_dataAddress, RemoteSinkSettings::m_dataPort, m_dataPort, RemoteSinkSettings::m_nbFECBlocks, RemoteSinkSettings::m_reverseAPIAddress, RemoteSinkSettings::m_reverseAPIChannelIndex, RemoteSinkSettings::m_reverseAPIDeviceIndex, RemoteSinkSettings::m_reverseAPIPort, m_settings, RemoteSinkSettings::m_txDelay, RemoteSinkSettings::m_useReverseAPI, setNbBlocksFEC(), setTxDelay(), and webapiReverseSendSettings().
Referenced by handleMessage().
 {
     qDebug() << "RemoteSink::applySettings:"
             << " m_nbFECBlocks: " << settings.m_nbFECBlocks
             << " m_txDelay: " << settings.m_txDelay
             << " m_dataAddress: " << settings.m_dataAddress
             << " m_dataPort: " << settings.m_dataPort
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if ((m_settings.m_nbFECBlocks != settings.m_nbFECBlocks) || force)
     {
         reverseAPIKeys.append("nbFECBlocks");
         setNbBlocksFEC(settings.m_nbFECBlocks);
         setTxDelay(settings.m_txDelay, settings.m_nbFECBlocks);
     }
     if ((m_settings.m_txDelay != settings.m_txDelay) || force)
     {
         reverseAPIKeys.append("txDelay");
         setTxDelay(settings.m_txDelay, settings.m_nbFECBlocks);
     }
     if ((m_settings.m_dataAddress != settings.m_dataAddress) || force)
     {
         reverseAPIKeys.append("dataAddress");
         m_dataAddress = settings.m_dataAddress;
     }
     if ((m_settings.m_dataPort != settings.m_dataPort) || force)
     {
         reverseAPIKeys.append("dataPort");
         m_dataPort = settings.m_dataPort;
     }
     if ((settings.m_useReverseAPI) && (reverseAPIKeys.size() != 0))
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
calculateFrequencyOffset()
void RemoteSink::calculateFrequencyOffset () private
Definition at line 426 of file remotesink.cpp.
References HBFilterChainConverter::getShiftFactor(), m_deviceSampleRate, RemoteSinkSettings::m_filterChainHash, m_frequencyOffset, RemoteSinkSettings::m_log2Decim, and m_settings.
Referenced by handleMessage().
 {
     double shiftFactor = HBFilterChainConverter::getShiftFactor(m_settings.m_log2Decim, m_settings.m_filterChainHash);
     m_frequencyOffset = m_deviceSampleRate * shiftFactor;
 }
dataBlockAvailable
void RemoteSink::dataBlockAvailable (RemoteDataBlock * dataBlock) signal
Referenced by start().
deserialize()
bool RemoteSink::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 348 of file remotesink.cpp.
References RemoteSink::MsgConfigureRemoteSink::create(), RemoteSinkSettings::deserialize(), BasebandSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and RemoteSinkSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     (void) data;
     if (m_settings.deserialize(data))
     {
         MsgConfigureRemoteSink *msg = MsgConfigureRemoteSink::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureRemoteSink *msg = MsgConfigureRemoteSink::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void RemoteSink::destroy () inline virtual
Implements ChannelAPI.
Definition at line 114 of file remotesink.h.
References feed(), handleMessage(), start(), and stop().
 { delete this; }
feed()
void RemoteSink::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool po) virtual
Implements BasebandSampleSink.
Definition at line 123 of file remotesink.cpp.
References m_centerFrequency, m_frequencyOffset, m_sampleRate, m_txBlockIndex, and SDR_RX_SAMP_SZ.
Referenced by destroy().
 {
     (void) firstOfBurst;
     SampleVector::const_iterator it = begin;
     while (it != end)
     {
         int inSamplesIndex = it - begin;
         int inRemainingSamples = end - it;
         if (m_txBlockIndex == 0)
         {
             struct timeval tv;
             RemoteMetaDataFEC metaData;
             gettimeofday(&tv, 0);
             metaData.m_centerFrequency = m_centerFrequency + m_frequencyOffset;
             metaData.m_sampleRate = m_sampleRate;
             metaData.m_sampleBytes = (SDR_RX_SAMP_SZ <= 16 ? 2 : 4);
             metaData.m_sampleBits = SDR_RX_SAMP_SZ;
             metaData.m_nbOriginalBlocks = RemoteNbOrginalBlocks;
             metaData.m_nbFECBlocks = m_nbBlocksFEC;
             metaData.m_tv_sec = tv.tv_sec;
             metaData.m_tv_usec = tv.tv_usec;
             if (!m_dataBlock) { // on the very first cycle there is no data block allocated
                 m_dataBlock = new RemoteDataBlock();
             }
             boost::crc_32_type crc32;
             crc32.process_bytes(&metaData, sizeof(RemoteMetaDataFEC)-4);
             metaData.m_crc32 = crc32.checksum();
             RemoteSuperBlock& superBlock = m_dataBlock->m_superBlocks[0]; // first block
             superBlock.init();
             superBlock.m_header.m_frameIndex = m_frameCount;
             superBlock.m_header.m_blockIndex = m_txBlockIndex;
             superBlock.m_header.m_sampleBytes = (SDR_RX_SAMP_SZ <= 16 ? 2 : 4);
             superBlock.m_header.m_sampleBits = SDR_RX_SAMP_SZ;
             RemoteMetaDataFEC *destMeta = (RemoteMetaDataFEC *) &superBlock.m_protectedBlock;
             *destMeta = metaData;
             if (!(metaData == m_currentMetaFEC))
             {
                 qDebug() << "RemoteSink::feed: meta: "
                         << "|" << metaData.m_centerFrequency
                         << ":" << metaData.m_sampleRate
                         << ":" << (int) (metaData.m_sampleBytes & 0xF)
                         << ":" << (int) metaData.m_sampleBits
                         << "|" << (int) metaData.m_nbOriginalBlocks
                         << ":" << (int) metaData.m_nbFECBlocks
                         << "|" << metaData.m_tv_sec
                         << ":" << metaData.m_tv_usec;
                 m_currentMetaFEC = metaData;
             }
             m_txBlockIndex = 1; // next Tx block with data
         } // block zero
         // handle different sample sizes...
         int samplesPerBlock = RemoteNbBytesPerBlock / (SDR_RX_SAMP_SZ <= 16 ? 4 : 8); // two I or Q samples
         if (m_sampleIndex + inRemainingSamples < samplesPerBlock) // there is still room in the current super block
         {
             memcpy((void *) &m_superBlock.m_protectedBlock.buf[m_sampleIndex*sizeof(Sample)],
                     (const void *) &(*(begin+inSamplesIndex)),
                     inRemainingSamples * sizeof(Sample));
             m_sampleIndex += inRemainingSamples;
             it = end; // all input samples are consumed
         }
         else // complete super block and initiate the next if not end of frame
         {
             memcpy((void *) &m_superBlock.m_protectedBlock.buf[m_sampleIndex*sizeof(Sample)],
                     (const void *) &(*(begin+inSamplesIndex)),
                     (samplesPerBlock - m_sampleIndex) * sizeof(Sample));
             it += samplesPerBlock - m_sampleIndex;
             m_sampleIndex = 0;
             m_superBlock.m_header.m_frameIndex = m_frameCount;
             m_superBlock.m_header.m_blockIndex = m_txBlockIndex;
             m_superBlock.m_header.m_sampleBytes = (SDR_RX_SAMP_SZ <= 16 ? 2 : 4);
             m_superBlock.m_header.m_sampleBits = SDR_RX_SAMP_SZ;
             m_dataBlock->m_superBlocks[m_txBlockIndex] = m_superBlock;
             if (m_txBlockIndex == RemoteNbOrginalBlocks - 1) // frame complete
             {
                 m_dataBlockMutex.lock();
                 m_dataBlock->m_txControlBlock.m_frameIndex = m_frameCount;
                 m_dataBlock->m_txControlBlock.m_processed = false;
                 m_dataBlock->m_txControlBlock.m_complete = true;
                 m_dataBlock->m_txControlBlock.m_nbBlocksFEC = m_nbBlocksFEC;
                 m_dataBlock->m_txControlBlock.m_txDelay = m_txDelay;
                 m_dataBlock->m_txControlBlock.m_dataAddress = m_dataAddress;
                 m_dataBlock->m_txControlBlock.m_dataPort = m_dataPort;
                 emit dataBlockAvailable(m_dataBlock);
                 m_dataBlock = new RemoteDataBlock(); // create a new one immediately
                 m_dataBlockMutex.unlock();
                 m_txBlockIndex = 0;
                 m_frameCount++;
             }
             else
             {
                 m_txBlockIndex++;
             }
         }
     }
 }
getCenterFrequency()
virtual qint64 RemoteSink::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 123 of file remotesink.h.
References deserialize(), m_frequencyOffset, and serialize().
 { return m_frequencyOffset; }
getIdentifier()
virtual void RemoteSink::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 121 of file remotesink.h.
 { id = objectName(); }
getNbSinkStreams()
virtual int RemoteSink::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 128 of file remotesink.h.
 { return 1; }
getNbSourceStreams()
virtual int RemoteSink::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 129 of file remotesink.h.
 { return 0; }
getStreamCenterFrequency()
virtual qint64 RemoteSink::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 131 of file remotesink.h.
References m_frequencyOffset, webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_frequencyOffset;
     }
getTitle()
virtual void RemoteSink::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 122 of file remotesink.h.
 { title = "Remote Sink"; }
handleMessage()
bool RemoteSink::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 267 of file remotesink.cpp.
References applySettings(), calculateFrequencyOffset(), RemoteSink::MsgSampleRateNotification::create(), DSPSignalNotification::getCenterFrequency(), RemoteSink::MsgConfigureChannelizer::getFilterChainHash(), RemoteSink::MsgConfigureRemoteSink::getForce(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSink::getInputMessageQueue(), RemoteSink::MsgConfigureChannelizer::getLog2Decim(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), DSPSignalNotification::getSampleRate(), RemoteSink::MsgConfigureRemoteSink::getSettings(), m_channelizer, m_deviceSampleRate, RemoteSinkSettings::m_filterChainHash, BasebandSampleSink::m_guiMessageQueue, RemoteSinkSettings::m_log2Decim, RemoteSinkSettings::m_nbFECBlocks, m_settings, RemoteSinkSettings::m_txDelay, Message::match(), MessageQueue::push(), DownChannelizer::set(), setCenterFrequency(), setSampleRate(), and setTxDelay().
Referenced by destroy().
 {
     (void) cmd;
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& notif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "RemoteSink::handleMessage: MsgChannelizerNotification:"
                 << " channelSampleRate: " << notif.getSampleRate()
                 << " offsetFrequency: " << notif.getFrequencyOffset();
         if (notif.getSampleRate() > 0) {
             setSampleRate(notif.getSampleRate());
         }
         setTxDelay(m_settings.m_txDelay, m_settings.m_nbFECBlocks);
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         DSPSignalNotification& notif = (DSPSignalNotification&) cmd;
         qDebug() << "RemoteSink::handleMessage: DSPSignalNotification:"
                 << " inputSampleRate: " << notif.getSampleRate()
                 << " centerFrequency: " << notif.getCenterFrequency();
         setCenterFrequency(notif.getCenterFrequency());
         m_deviceSampleRate = notif.getSampleRate();
         calculateFrequencyOffset(); // This is when device sample rate changes
         // Redo the channelizer stuff with the new sample rate to re-synchronize everything
         m_channelizer->set(m_channelizer->getInputMessageQueue(),
             m_settings.m_log2Decim,
             m_settings.m_filterChainHash);
         if (m_guiMessageQueue)
         {
             MsgSampleRateNotification *msg = MsgSampleRateNotification::create(notif.getSampleRate());
             m_guiMessageQueue->push(msg);
         }
         return true;
     }
     else if (MsgConfigureRemoteSink::match(cmd))
     {
         MsgConfigureRemoteSink& cfg = (MsgConfigureRemoteSink&) cmd;
         qDebug() << "RemoteSink::handleMessage: MsgConfigureRemoteSink";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         m_settings.m_log2Decim = cfg.getLog2Decim();
         m_settings.m_filterChainHash =  cfg.getFilterChainHash();
         qDebug() << "RemoteSink::handleMessage: MsgConfigureChannelizer:"
                 << " log2Decim: " << m_settings.m_log2Decim
                 << " filterChainHash: " << m_settings.m_filterChainHash;
         m_channelizer->set(m_channelizer->getInputMessageQueue(),
             m_settings.m_log2Decim,
             m_settings.m_filterChainHash);
         calculateFrequencyOffset(); // This is when decimation or filter chain changes
         return true;
     }
     else
     {
         return false;
     }
 }
networkManagerFinished
void RemoteSink::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 634 of file remotesink.cpp.
Referenced by RemoteSink(), and ~RemoteSink().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "RemoteSink::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("RemoteSink::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
serialize()
QByteArray RemoteSink::serialize () const virtual
Implements ChannelAPI.
Definition at line 343 of file remotesink.cpp.
References m_settings, and RemoteSinkSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void RemoteSink::setCenterFrequency (uint64_t centerFrequency) inline
Set center frequency given in Hz
Definition at line 149 of file remotesink.h.
References m_centerFrequency.
Referenced by handleMessage().
 { m_centerFrequency = centerFrequency; }
setChannelizer()
void RemoteSink::setChannelizer (unsigned int log2Decim, unsigned int filterChainHash)
Referenced by setDataPort().
setDataAddress()
void RemoteSink::setDataAddress (const QString & address) inline
Definition at line 156 of file remotesink.h.
References m_dataAddress.
 { m_dataAddress = address; }
setDataPort()
void RemoteSink::setDataPort (uint16_t port) inline
Definition at line 157 of file remotesink.h.
References m_dataPort, and setChannelizer().
 { m_dataPort = port; }
setNbBlocksFEC()
void RemoteSink::setNbBlocksFEC (int nbBlocksFEC)
Definition at line 117 of file remotesink.cpp.
References m_nbBlocksFEC.
Referenced by applySettings(), and setSampleRate().
 {
     qDebug() << "RemoteSink::setNbBlocksFEC: nbBlocksFEC: " << nbBlocksFEC;
     m_nbBlocksFEC = nbBlocksFEC;
 }
setSampleRate()
void RemoteSink::setSampleRate (uint32_t sampleRate) inline
Set sample rate given in Hz
Definition at line 152 of file remotesink.h.
References m_sampleRate, setNbBlocksFEC(), and setTxDelay().
Referenced by handleMessage().
 { m_sampleRate = sampleRate; }
setTxDelay()
void RemoteSink::setTxDelay (int txDelay, int nbBlocksFEC)
Definition at line 104 of file remotesink.cpp.
Referenced by applySettings(), handleMessage(), and setSampleRate().
 {
     double txDelayRatio = txDelay / 100.0;
     int samplesPerBlock = RemoteNbBytesPerBlock / sizeof(Sample);
     double delay = m_sampleRate == 0 ? 1.0 : (127*samplesPerBlock*txDelayRatio) / m_sampleRate;
     delay /= 128 + nbBlocksFEC;
     m_txDelay = roundf(delay*1e6); // microseconds
     qDebug() << "RemoteSink::setTxDelay:"
             << " " << txDelay
             << "% m_txDelay: " << m_txDelay << "us"
             << " m_sampleRate: " << m_sampleRate << "S/s";
 }
start()
void RemoteSink::start () virtual
Implements BasebandSampleSink.
Definition at line 233 of file remotesink.cpp.
References dataBlockAvailable(), m_currentMetaFEC, m_running, m_sinkThread, RemoteSinkThread::startStop(), and stop().
Referenced by destroy().
 {
     qDebug("RemoteSink::start");
     memset((void *) &m_currentMetaFEC, 0, sizeof(RemoteMetaDataFEC));
     if (m_running) {
         stop();
     }
     m_sinkThread = new RemoteSinkThread();
     connect(this,
             SIGNAL(dataBlockAvailable(RemoteDataBlock *)),
             m_sinkThread,
             SLOT(processDataBlock(RemoteDataBlock *)),
             Qt::QueuedConnection);
     m_sinkThread->startStop(true);
     m_running = true;
 }
stop()
void RemoteSink::stop () virtual
Implements BasebandSampleSink.
Definition at line 253 of file remotesink.cpp.
References m_running, m_sinkThread, and RemoteSinkThread::startStop().
Referenced by destroy(), and start().
 {
     qDebug("RemoteSink::stop");
     if (m_sinkThread != 0)
     {
         m_sinkThread->startStop(false);
         m_sinkThread->deleteLater();
         m_sinkThread = 0;
     }
     m_running = false;
 }
validateFilterChainHash()
void RemoteSink::validateFilterChainHash (RemoteSinkSettings & settings) private
Definition at line 415 of file remotesink.cpp.
References i, RemoteSinkSettings::m_filterChainHash, and RemoteSinkSettings::m_log2Decim.
Referenced by webapiSettingsPutPatch().
 {
     unsigned int s = 1;
     for (unsigned int i = 0; i < settings.m_log2Decim; i++) {
         s *= 3;
     }
     settings.m_filterChainHash = settings.m_filterChainHash >= s ? s-1 : settings.m_filterChainHash;
 }
webapiFormatChannelSettings()
void RemoteSink::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const RemoteSinkSettings & settings) private
Definition at line 542 of file remotesink.cpp.
References SWGSDRangel::SWGRemoteSinkSettings::getDataAddress(), SWGSDRangel::SWGChannelSettings::getRemoteSinkSettings(), SWGSDRangel::SWGRemoteSinkSettings::getReverseApiAddress(), SWGSDRangel::SWGRemoteSinkSettings::getTitle(), RemoteSinkSettings::m_dataAddress, RemoteSinkSettings::m_dataPort, RemoteSinkSettings::m_filterChainHash, RemoteSinkSettings::m_log2Decim, RemoteSinkSettings::m_nbFECBlocks, RemoteSinkSettings::m_reverseAPIAddress, RemoteSinkSettings::m_reverseAPIChannelIndex, RemoteSinkSettings::m_reverseAPIDeviceIndex, RemoteSinkSettings::m_reverseAPIPort, RemoteSinkSettings::m_rgbColor, RemoteSinkSettings::m_title, RemoteSinkSettings::m_txDelay, RemoteSinkSettings::m_useReverseAPI, SWGSDRangel::SWGRemoteSinkSettings::setDataAddress(), SWGSDRangel::SWGRemoteSinkSettings::setDataPort(), SWGSDRangel::SWGRemoteSinkSettings::setFilterChainHash(), SWGSDRangel::SWGRemoteSinkSettings::setLog2Decim(), SWGSDRangel::SWGRemoteSinkSettings::setNbFecBlocks(), SWGSDRangel::SWGRemoteSinkSettings::setReverseApiAddress(), SWGSDRangel::SWGRemoteSinkSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGRemoteSinkSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGRemoteSinkSettings::setReverseApiPort(), SWGSDRangel::SWGRemoteSinkSettings::setRgbColor(), SWGSDRangel::SWGRemoteSinkSettings::setTitle(), SWGSDRangel::SWGRemoteSinkSettings::setTxDelay(), and SWGSDRangel::SWGRemoteSinkSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getRemoteSinkSettings()->setNbFecBlocks(settings.m_nbFECBlocks);
     response.getRemoteSinkSettings()->setTxDelay(settings.m_txDelay);
     if (response.getRemoteSinkSettings()->getDataAddress()) {
         *response.getRemoteSinkSettings()->getDataAddress() = settings.m_dataAddress;
     } else {
         response.getRemoteSinkSettings()->setDataAddress(new QString(settings.m_dataAddress));
     }
     response.getRemoteSinkSettings()->setDataPort(settings.m_dataPort);
     response.getRemoteSinkSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getRemoteSinkSettings()->getTitle()) {
         *response.getRemoteSinkSettings()->getTitle() = settings.m_title;
     } else {
         response.getRemoteSinkSettings()->setTitle(new QString(settings.m_title));
     }
     response.getRemoteSinkSettings()->setLog2Decim(settings.m_log2Decim);
     response.getRemoteSinkSettings()->setFilterChainHash(settings.m_filterChainHash);
     response.getRemoteSinkSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getRemoteSinkSettings()->getReverseApiAddress()) {
         *response.getRemoteSinkSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getRemoteSinkSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getRemoteSinkSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getRemoteSinkSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getRemoteSinkSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReverseSendSettings()
void RemoteSink::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const RemoteSinkSettings & settings, bool force) private
Definition at line 577 of file remotesink.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), SWGSDRangel::SWGChannelSettings::getRemoteSinkSettings(), RemoteSinkSettings::m_dataAddress, RemoteSinkSettings::m_dataPort, RemoteSinkSettings::m_filterChainHash, RemoteSinkSettings::m_log2Decim, RemoteSinkSettings::m_nbFECBlocks, m_networkManager, m_networkRequest, RemoteSinkSettings::m_reverseAPIAddress, RemoteSinkSettings::m_reverseAPIChannelIndex, RemoteSinkSettings::m_reverseAPIDeviceIndex, RemoteSinkSettings::m_reverseAPIPort, RemoteSinkSettings::m_rgbColor, RemoteSinkSettings::m_title, RemoteSinkSettings::m_txDelay, SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGRemoteSinkSettings::setDataAddress(), SWGSDRangel::SWGRemoteSinkSettings::setDataPort(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGRemoteSinkSettings::setFilterChainHash(), SWGSDRangel::SWGRemoteSinkSettings::setLog2Decim(), SWGSDRangel::SWGRemoteSinkSettings::setNbFecBlocks(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGChannelSettings::setRemoteSinkSettings(), SWGSDRangel::SWGRemoteSinkSettings::setRgbColor(), SWGSDRangel::SWGRemoteSinkSettings::setTitle(), and SWGSDRangel::SWGRemoteSinkSettings::setTxDelay().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(0); // single sink (Rx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("RemoteSink"));
     swgChannelSettings->setRemoteSinkSettings(new SWGSDRangel::SWGRemoteSinkSettings());
     SWGSDRangel::SWGRemoteSinkSettings *swgRemoteSinkSettings = swgChannelSettings->getRemoteSinkSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("nbFECBlocks") || force) {
         swgRemoteSinkSettings->setNbFecBlocks(settings.m_nbFECBlocks);
     }
     if (channelSettingsKeys.contains("txDelay") || force)
     {
         swgRemoteSinkSettings->setTxDelay(settings.m_txDelay);
     }
     if (channelSettingsKeys.contains("dataAddress") || force) {
         swgRemoteSinkSettings->setDataAddress(new QString(settings.m_dataAddress));
     }
     if (channelSettingsKeys.contains("dataPort") || force) {
         swgRemoteSinkSettings->setDataPort(settings.m_dataPort);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgRemoteSinkSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgRemoteSinkSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("log2Decim") || force) {
         swgRemoteSinkSettings->setLog2Decim(settings.m_log2Decim);
     }
     if (channelSettingsKeys.contains("filterChainHash") || force) {
         swgRemoteSinkSettings->setFilterChainHash(settings.m_filterChainHash);
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int RemoteSink::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 432 of file remotesink.cpp.
References SWGSDRangel::SWGChannelSettings::getRemoteSinkSettings(), SWGSDRangel::SWGRemoteSinkSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setRemoteSinkSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setRemoteSinkSettings(new SWGSDRangel::SWGRemoteSinkSettings());
     response.getRemoteSinkSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int RemoteSink::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 443 of file remotesink.cpp.
References RemoteSink::MsgConfigureRemoteSink::create(), RemoteSink::MsgConfigureChannelizer::create(), SWGSDRangel::SWGRemoteSinkSettings::getDataAddress(), SWGSDRangel::SWGRemoteSinkSettings::getDataPort(), SWGSDRangel::SWGRemoteSinkSettings::getFilterChainHash(), SWGSDRangel::SWGRemoteSinkSettings::getLog2Decim(), SWGSDRangel::SWGRemoteSinkSettings::getNbFecBlocks(), SWGSDRangel::SWGChannelSettings::getRemoteSinkSettings(), SWGSDRangel::SWGRemoteSinkSettings::getReverseApiAddress(), SWGSDRangel::SWGRemoteSinkSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGRemoteSinkSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGRemoteSinkSettings::getReverseApiPort(), SWGSDRangel::SWGRemoteSinkSettings::getRgbColor(), SWGSDRangel::SWGRemoteSinkSettings::getTitle(), SWGSDRangel::SWGRemoteSinkSettings::getTxDelay(), SWGSDRangel::SWGRemoteSinkSettings::getUseReverseApi(), RemoteSinkSettings::m_dataAddress, RemoteSinkSettings::m_dataPort, RemoteSinkSettings::m_filterChainHash, BasebandSampleSink::m_guiMessageQueue, BasebandSampleSink::m_inputMessageQueue, RemoteSinkSettings::m_log2Decim, RemoteSinkSettings::m_nbFECBlocks, RemoteSinkSettings::m_reverseAPIAddress, RemoteSinkSettings::m_reverseAPIChannelIndex, RemoteSinkSettings::m_reverseAPIDeviceIndex, RemoteSinkSettings::m_reverseAPIPort, RemoteSinkSettings::m_rgbColor, m_settings, RemoteSinkSettings::m_title, RemoteSinkSettings::m_txDelay, RemoteSinkSettings::m_useReverseAPI, MessageQueue::push(), validateFilterChainHash(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     RemoteSinkSettings settings = m_settings;
     if (channelSettingsKeys.contains("nbFECBlocks"))
     {
         int nbFECBlocks = response.getRemoteSinkSettings()->getNbFecBlocks();
         if ((nbFECBlocks < 0) || (nbFECBlocks > 127)) {
             settings.m_nbFECBlocks = 8;
         } else {
             settings.m_nbFECBlocks = response.getRemoteSinkSettings()->getNbFecBlocks();
         }
     }
     if (channelSettingsKeys.contains("txDelay"))
     {
         int txDelay = response.getRemoteSinkSettings()->getTxDelay();
         if (txDelay < 0) {
             settings.m_txDelay = 35;
         } else {
             settings.m_txDelay = txDelay;
         }
     }
     if (channelSettingsKeys.contains("dataAddress")) {
         settings.m_dataAddress = *response.getRemoteSinkSettings()->getDataAddress();
     }
     if (channelSettingsKeys.contains("dataPort"))
     {
         int dataPort = response.getRemoteSinkSettings()->getDataPort();
         if ((dataPort < 1024) || (dataPort > 65535)) {
             settings.m_dataPort = 9090;
         } else {
             settings.m_dataPort = dataPort;
         }
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getRemoteSinkSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getRemoteSinkSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getRemoteSinkSettings()->getLog2Decim();
     }
     if (channelSettingsKeys.contains("filterChainHash"))
     {
         settings.m_filterChainHash = response.getRemoteSinkSettings()->getFilterChainHash();
         validateFilterChainHash(settings);
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getRemoteSinkSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getRemoteSinkSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getRemoteSinkSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getRemoteSinkSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getRemoteSinkSettings()->getReverseApiChannelIndex();
     }
     MsgConfigureRemoteSink *msg = MsgConfigureRemoteSink::create(settings, force);
     m_inputMessageQueue.push(msg);
     if ((settings.m_log2Decim != m_settings.m_log2Decim) || (settings.m_filterChainHash != m_settings.m_filterChainHash) || force)
     {
         MsgConfigureChannelizer *msg = MsgConfigureChannelizer::create(settings.m_log2Decim, settings.m_filterChainHash);
         m_inputMessageQueue.push(msg);
     }
     qDebug("RemoteSink::webapiSettingsPutPatch: forward to GUI: %p", m_guiMessageQueue);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureRemoteSink *msgToGUI = MsgConfigureRemoteSink::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_centerFrequency
uint64_t RemoteSink::m_centerFrequency private
Definition at line 183 of file remotesink.h.
Referenced by feed(), and setCenterFrequency().
m_channelId
const QString RemoteSink::m_channelId = "RemoteSink" static
Definition at line 161 of file remotesink.h.
Referenced by RemoteSinkPlugin::initPlugin(), and RemoteSink().
m_channelIdURI
const QString RemoteSink::m_channelIdURI = "sdrangel.channel.remotesink" static
Definition at line 160 of file remotesink.h.
Referenced by RemoteSinkPlugin::initPlugin(), and RemoteSinkGUI::RemoteSinkGUI().
m_channelizer
DownChannelizer* RemoteSink::m_channelizer private
Definition at line 169 of file remotesink.h.
Referenced by handleMessage(), RemoteSink(), and ~RemoteSink().
m_currentMetaFEC
RemoteMetaDataFEC RemoteSink::m_currentMetaFEC private
Definition at line 179 of file remotesink.h.
Referenced by start().
m_dataAddress
QString RemoteSink::m_dataAddress private
Definition at line 189 of file remotesink.h.
Referenced by applySettings(), and setDataAddress().
m_dataBlock
RemoteDataBlock* RemoteSink::m_dataBlock private
Definition at line 180 of file remotesink.h.
Referenced by ~RemoteSink().
m_dataBlockMutex
QMutex RemoteSink::m_dataBlockMutex private
Definition at line 181 of file remotesink.h.
Referenced by ~RemoteSink().
m_dataPort
uint16_t RemoteSink::m_dataPort private
Definition at line 190 of file remotesink.h.
Referenced by applySettings(), and setDataPort().
m_deviceAPI
DeviceAPI* RemoteSink::m_deviceAPI private
Definition at line 167 of file remotesink.h.
Referenced by RemoteSink(), and ~RemoteSink().
m_deviceSampleRate
uint32_t RemoteSink::m_deviceSampleRate private
Definition at line 186 of file remotesink.h.
Referenced by calculateFrequencyOffset(), and handleMessage().
m_frameCount
uint16_t RemoteSink::m_frameCount private
transmission frame count
Definition at line 176 of file remotesink.h.
m_frequencyOffset
int64_t RemoteSink::m_frequencyOffset private
Definition at line 184 of file remotesink.h.
Referenced by calculateFrequencyOffset(), feed(), getCenterFrequency(), and getStreamCenterFrequency().
m_nbBlocksFEC
int RemoteSink::m_nbBlocksFEC private
Definition at line 187 of file remotesink.h.
Referenced by setNbBlocksFEC().
m_networkManager
QNetworkAccessManager* RemoteSink::m_networkManager private
Definition at line 191 of file remotesink.h.
Referenced by RemoteSink(), webapiReverseSendSettings(), and ~RemoteSink().
m_networkRequest
QNetworkRequest RemoteSink::m_networkRequest private
Definition at line 192 of file remotesink.h.
Referenced by webapiReverseSendSettings().
m_running
bool RemoteSink::m_running private
Definition at line 170 of file remotesink.h.
Referenced by start(), and stop().
m_sampleIndex
int RemoteSink::m_sampleIndex private
Current sample index in protected block data.
Definition at line 177 of file remotesink.h.
m_sampleRate
uint32_t RemoteSink::m_sampleRate private
Definition at line 185 of file remotesink.h.
Referenced by feed(), RemoteSink::MsgSampleRateNotification::getSampleRate(), and setSampleRate().
m_settings
RemoteSinkSettings RemoteSink::m_settings private
Definition at line 172 of file remotesink.h.
Referenced by applySettings(), calculateFrequencyOffset(), deserialize(), handleMessage(), serialize(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_sinkThread
RemoteSinkThread* RemoteSink::m_sinkThread private
Definition at line 173 of file remotesink.h.
Referenced by start(), and stop().
m_superBlock
RemoteSuperBlock RemoteSink::m_superBlock private
Definition at line 178 of file remotesink.h.
m_threadedChannelizer
ThreadedBasebandSampleSink* RemoteSink::m_threadedChannelizer private
Definition at line 168 of file remotesink.h.
Referenced by RemoteSink(), and ~RemoteSink().
m_txBlockIndex
int RemoteSink::m_txBlockIndex private
Current index in blocks to transmit in the Tx row.
Definition at line 175 of file remotesink.h.
Referenced by feed().
m_txDelay
int RemoteSink::m_txDelay private
Definition at line 188 of file remotesink.h.
The documentation for this class was generated from the following files:
plugins/channelrx/remotesink/remotesink.h
plugins/channelrx/remotesink/remotesink.cpp