SDRAngel: TestSourceGui Class Reference
TestSourceGui Class Reference
#include <testsourcegui.h>
Public Member Functions
TestSourceGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~TestSourceGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_startStop_toggled (bool checked)
void on_centerFrequency_changed (quint64 value)
void on_autoCorr_currentIndexChanged (int index)
void on_frequencyShift_changed (qint64 value)
void on_decimation_currentIndexChanged (int index)
void on_fcPos_currentIndexChanged (int index)
void on_sampleRate_changed (quint64 value)
void on_sampleSize_currentIndexChanged (int index)
void on_amplitudeCoarse_valueChanged (int value)
void on_amplitudeFine_valueChanged (int value)
void on_modulation_currentIndexChanged (int index)
void on_modulationFrequency_valueChanged (int value)
void on_amModulation_valueChanged (int value)
void on_fmDeviation_valueChanged (int value)
void on_dcBias_valueChanged (int value)
void on_iBias_valueChanged (int value)
void on_qBias_valueChanged (int value)
void on_phaseImbalance_valueChanged (int value)
void on_record_toggled (bool checked)
void openDeviceSettingsDialog (const QPoint &p)
void updateStatus ()
void updateHardware ()
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void displayAmplitude ()
void updateAmpCoarseLimit ()
void updateAmpFineLimit ()
void updateFrequencyShiftLimit ()
Private Attributes
Ui::TestSourceGui * ui
DeviceUISet * m_deviceUISet
TestSourceSettings m_settings
QTimer m_updateTimer
QTimer m_statusTimer
bool m_doApplySettings
bool m_forceSettings
DeviceSampleSource * m_sampleSource
std::size_t m_tickCount
int m_deviceSampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 36 of file testsourcegui.h.
Constructor & Destructor Documentation
TestSourceGui()
TestSourceGui::TestSourceGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 41 of file testsourcegui.cpp.
References arg(), displaySettings(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_sampleSource, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), DeviceSampleSource::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                                       :
     QWidget(parent),
     ui(new Ui::TestSourceGui),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_sampleSource(0),
     m_tickCount(0),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     qDebug("TestSourceGui::TestSourceGui");
     m_sampleSource = m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, 0, 9999999);
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(7, 48000, 9999999);
     ui->frequencyShift->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->frequencyShift->setValueRange(false, 7, -9999999, 9999999);
     ui->frequencyShiftLabel->setText(QString("%1").arg(QChar(0x94, 0x03)));
     displaySettings();
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
 }
~TestSourceGui()
TestSourceGui::~TestSourceGui () virtual
Definition at line 77 of file testsourcegui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void TestSourceGui::blockApplySettings (bool block) inline private
Definition at line 71 of file testsourcegui.h.
Referenced by displaySettings(), and handleMessage().
 { m_doApplySettings = !block; }
deserialize()
bool TestSourceGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 121 of file testsourcegui.cpp.
References TestSourceSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void TestSourceGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 82 of file testsourcegui.cpp.
 {
     delete this;
 }
displayAmplitude()
void TestSourceGui::displayAmplitude () private
Definition at line 295 of file testsourcegui.cpp.
References arg(), CalcDb::dbPower(), and ui.
Referenced by displaySettings(), on_amplitudeCoarse_valueChanged(), on_amplitudeFine_valueChanged(), and on_sampleSize_currentIndexChanged().
 {
     int amplitudeInt = ui->amplitudeCoarse->value() * 100 + ui->amplitudeFine->value();
     double power;
     switch (ui->sampleSize->currentIndex())
     {
     case 0: // 8 bits: 128
         power = (double) amplitudeInt*amplitudeInt / (double) (1<<14);
         break;
     case 1: // 12 bits 2048
         power = (double) amplitudeInt*amplitudeInt / (double) (1<<22);
         break;
     case 2: // 16 bits 32768
     default:
         power = (double) amplitudeInt*amplitudeInt / (double) (1<<30);
         break;
     }
     ui->amplitudeBits->setText(QString(tr("%1 b").arg(amplitudeInt)));
     double powerDb = CalcDb::dbPower(power);
     ui->power->setText(QString(tr("%1 dB").arg(QString::number(powerDb, 'f', 1))));
 }
displaySettings()
void TestSourceGui::displaySettings () private
Definition at line 371 of file testsourcegui.cpp.
References arg(), blockApplySettings(), displayAmplitude(), TestSourceSettings::m_amModulation, TestSourceSettings::m_amplitudeBits, TestSourceSettings::m_autoCorrOptions, TestSourceSettings::m_centerFrequency, TestSourceSettings::m_dcFactor, TestSourceSettings::m_fcPos, TestSourceSettings::m_fmDeviation, TestSourceSettings::m_frequencyShift, TestSourceSettings::m_iFactor, TestSourceSettings::m_log2Decim, TestSourceSettings::m_modulation, TestSourceSettings::m_modulationTone, TestSourceSettings::m_phaseImbalance, TestSourceSettings::m_qFactor, TestSourceSettings::m_sampleRate, TestSourceSettings::m_sampleSizeIndex, m_settings, ui, updateAmpCoarseLimit(), updateAmpFineLimit(), and updateFrequencyShiftLimit().
Referenced by deserialize(), handleMessage(), resetToDefaults(), setCenterFrequency(), and TestSourceGui().
 {
     blockApplySettings(true);
     ui->sampleSize->blockSignals(true);
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     ui->decimation->setCurrentIndex(m_settings.m_log2Decim);
     ui->fcPos->setCurrentIndex((int) m_settings.m_fcPos);
     ui->sampleRate->setValue(m_settings.m_sampleRate);
     updateFrequencyShiftLimit();
     ui->frequencyShift->setValue(m_settings.m_frequencyShift);
     ui->sampleSize->setCurrentIndex(m_settings.m_sampleSizeIndex);
     updateAmpCoarseLimit();
     int amplitudeBits = m_settings.m_amplitudeBits;
     ui->amplitudeCoarse->setValue(amplitudeBits/100);
     updateAmpFineLimit();
     ui->amplitudeFine->setValue(amplitudeBits%100);
     displayAmplitude();
     int dcBiasPercent = roundf(m_settings.m_dcFactor * 100.0f);
     ui->dcBias->setValue((int) dcBiasPercent);
     ui->dcBiasText->setText(QString(tr("%1 %").arg(dcBiasPercent)));
     int iBiasPercent = roundf(m_settings.m_iFactor * 100.0f);
     ui->iBias->setValue((int) iBiasPercent);
     ui->iBiasText->setText(QString(tr("%1 %").arg(iBiasPercent)));
     int qBiasPercent = roundf(m_settings.m_qFactor * 100.0f);
     ui->qBias->setValue((int) qBiasPercent);
     ui->qBiasText->setText(QString(tr("%1 %").arg(qBiasPercent)));
     int phaseImbalancePercent = roundf(m_settings.m_phaseImbalance * 100.0f);
     ui->phaseImbalance->setValue((int) phaseImbalancePercent);
     ui->phaseImbalanceText->setText(QString(tr("%1 %").arg(phaseImbalancePercent)));
     ui->autoCorr->setCurrentIndex(m_settings.m_autoCorrOptions);
     ui->sampleSize->blockSignals(false);
     ui->modulation->setCurrentIndex((int) m_settings.m_modulation);
     ui->modulationFrequency->setValue(m_settings.m_modulationTone);
     ui->modulationFrequencyText->setText(QString("%1").arg(m_settings.m_modulationTone / 100.0, 0, 'f', 2));
     ui->amModulation->setValue(m_settings.m_amModulation);
     ui->amModulationText->setText(QString("%1").arg(m_settings.m_amModulation));
     ui->fmDeviation->setValue(m_settings.m_fmDeviation);
     ui->fmDeviationText->setText(QString("%1").arg(m_settings.m_fmDeviation / 10.0, 0, 'f', 1));
     blockApplySettings(false);
 }
getCenterFrequency()
qint64 TestSourceGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 104 of file testsourcegui.cpp.
References TestSourceSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* TestSourceGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 52 of file testsourcegui.h.
 { return &m_inputMessageQueue; }
getName()
QString TestSourceGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 92 of file testsourcegui.cpp.
 {
     return objectName();
 }
handleInputMessages
void TestSourceGui::handleInputMessages () private slot
Definition at line 486 of file testsourcegui.cpp.
References DSPSignalNotification::getCenterFrequency(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_deviceSampleRate, m_inputMessageQueue, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by TestSourceGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_deviceSampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("TestSourceGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu",
                     notif->getSampleRate(),
                     notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool TestSourceGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 460 of file testsourcegui.cpp.
References blockApplySettings(), displaySettings(), TestSourceInput::MsgConfigureTestSource::getSettings(), TestSourceInput::MsgStartStop::getStartStop(), m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (TestSourceInput::MsgConfigureTestSource::match(message))
     {
         qDebug("TestSourceGui::handleMessage: MsgConfigureTestSource");
         const TestSourceInput::MsgConfigureTestSource& cfg = (TestSourceInput::MsgConfigureTestSource&) message;
         m_settings = cfg.getSettings();
         displaySettings();
         return true;
     }
     else if (TestSourceInput::MsgStartStop::match(message))
     {
         qDebug("TestSourceGui::handleMessage: MsgStartStop");
         TestSourceInput::MsgStartStop& notif = (TestSourceInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_amModulation_valueChanged
void TestSourceGui::on_amModulation_valueChanged (int value) private slot
Definition at line 241 of file testsourcegui.cpp.
References arg(), TestSourceSettings::m_amModulation, m_settings, sendSettings(), and ui.
 {
     m_settings.m_amModulation = value;
     ui->amModulationText->setText(QString("%1").arg(m_settings.m_amModulation));
     sendSettings();
 }
on_amplitudeCoarse_valueChanged
void TestSourceGui::on_amplitudeCoarse_valueChanged (int value) private slot
Definition at line 207 of file testsourcegui.cpp.
References displayAmplitude(), TestSourceSettings::m_amplitudeBits, m_settings, sendSettings(), ui, and updateAmpFineLimit().
 {
     (void) value;
     updateAmpFineLimit();
     displayAmplitude();
     m_settings.m_amplitudeBits = ui->amplitudeCoarse->value() * 100 + ui->amplitudeFine->value();
     sendSettings();
 }
on_amplitudeFine_valueChanged
void TestSourceGui::on_amplitudeFine_valueChanged (int value) private slot
Definition at line 216 of file testsourcegui.cpp.
References displayAmplitude(), TestSourceSettings::m_amplitudeBits, m_settings, sendSettings(), and ui.
 {
     (void) value;
     displayAmplitude();
     m_settings.m_amplitudeBits = ui->amplitudeCoarse->value() * 100 + ui->amplitudeFine->value();
     sendSettings();
 }
on_autoCorr_currentIndexChanged
void TestSourceGui::on_autoCorr_currentIndexChanged (int index) private slot
Definition at line 149 of file testsourcegui.cpp.
References TestSourceSettings::AutoCorrLast, TestSourceSettings::m_autoCorrOptions, m_settings, and sendSettings().
 {
     if ((index < 0) || (index > TestSourceSettings::AutoCorrLast)) {
         return;
     }
     m_settings.m_autoCorrOptions = (TestSourceSettings::AutoCorrOptions) index;
     sendSettings();
 }
on_centerFrequency_changed
void TestSourceGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 143 of file testsourcegui.cpp.
References TestSourceSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_dcBias_valueChanged
void TestSourceGui::on_dcBias_valueChanged (int value) private slot
Definition at line 255 of file testsourcegui.cpp.
References arg(), TestSourceSettings::m_dcFactor, m_settings, sendSettings(), and ui.
 {
     ui->dcBiasText->setText(QString(tr("%1 %").arg(value)));
     m_settings.m_dcFactor = value / 100.0f;
     sendSettings();
 }
on_decimation_currentIndexChanged
void TestSourceGui::on_decimation_currentIndexChanged (int index) private slot
Definition at line 165 of file testsourcegui.cpp.
References TestSourceSettings::m_log2Decim, m_settings, and sendSettings().
 {
     if ((index < 0) || (index > 6)) {
         return;
     }
     m_settings.m_log2Decim = index;
     sendSettings();
 }
on_fcPos_currentIndexChanged
void TestSourceGui::on_fcPos_currentIndexChanged (int index) private slot
Definition at line 175 of file testsourcegui.cpp.
References TestSourceSettings::m_fcPos, m_settings, and sendSettings().
 {
     if ((index < 0) || (index > 2)) {
         return;
     }
     m_settings.m_fcPos = (TestSourceSettings::fcPos_t) index;
     sendSettings();
 }
on_fmDeviation_valueChanged
void TestSourceGui::on_fmDeviation_valueChanged (int value) private slot
Definition at line 248 of file testsourcegui.cpp.
References arg(), TestSourceSettings::m_fmDeviation, m_settings, sendSettings(), and ui.
 {
     m_settings.m_fmDeviation = value;
     ui->fmDeviationText->setText(QString("%1").arg(m_settings.m_fmDeviation / 10.0, 0, 'f', 1));
     sendSettings();
 }
on_frequencyShift_changed
void TestSourceGui::on_frequencyShift_changed (qint64 value) private slot
Definition at line 159 of file testsourcegui.cpp.
References TestSourceSettings::m_frequencyShift, m_settings, and sendSettings().
 {
     m_settings.m_frequencyShift = value;
     sendSettings();
 }
on_iBias_valueChanged
void TestSourceGui::on_iBias_valueChanged (int value) private slot
Definition at line 262 of file testsourcegui.cpp.
References arg(), TestSourceSettings::m_iFactor, m_settings, sendSettings(), and ui.
 {
     ui->iBiasText->setText(QString(tr("%1 %").arg(value)));
     m_settings.m_iFactor = value / 100.0f;
     sendSettings();
 }
on_modulation_currentIndexChanged
void TestSourceGui::on_modulation_currentIndexChanged (int index) private slot
Definition at line 224 of file testsourcegui.cpp.
References TestSourceSettings::m_modulation, m_settings, TestSourceSettings::ModulationLast, and sendSettings().
 {
     if ((index < 0) || (index > TestSourceSettings::ModulationLast)) {
         return;
     }
     m_settings.m_modulation = (TestSourceSettings::Modulation) index;
     sendSettings();
 }
on_modulationFrequency_valueChanged
void TestSourceGui::on_modulationFrequency_valueChanged (int value) private slot
Definition at line 234 of file testsourcegui.cpp.
References arg(), TestSourceSettings::m_modulationTone, m_settings, sendSettings(), and ui.
 {
     m_settings.m_modulationTone = value;
     ui->modulationFrequencyText->setText(QString("%1").arg(m_settings.m_modulationTone / 100.0, 0, 'f', 2));
     sendSettings();
 }
on_phaseImbalance_valueChanged
void TestSourceGui::on_phaseImbalance_valueChanged (int value) private slot
Definition at line 276 of file testsourcegui.cpp.
References arg(), TestSourceSettings::m_phaseImbalance, m_settings, sendSettings(), and ui.
 {
     ui->phaseImbalanceText->setText(QString(tr("%1 %").arg(value)));
     m_settings.m_phaseImbalance = value / 100.0f;
     sendSettings();
 }
on_qBias_valueChanged
void TestSourceGui::on_qBias_valueChanged (int value) private slot
Definition at line 269 of file testsourcegui.cpp.
References arg(), TestSourceSettings::m_qFactor, m_settings, sendSettings(), and ui.
 {
     ui->qBiasText->setText(QString(tr("%1 %").arg(value)));
     m_settings.m_qFactor = value / 100.0f;
     sendSettings();
 }
on_record_toggled
void TestSourceGui::on_record_toggled (bool checked) private slot
Definition at line 283 of file testsourcegui.cpp.
References TestSourceInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     TestSourceInput::MsgFileRecord* message = TestSourceInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_sampleRate_changed
void TestSourceGui::on_sampleRate_changed (quint64 value) private slot
Definition at line 185 of file testsourcegui.cpp.
References TestSourceSettings::m_frequencyShift, TestSourceSettings::m_sampleRate, m_settings, sendSettings(), ui, and updateFrequencyShiftLimit().
 {
     updateFrequencyShiftLimit();
     m_settings.m_frequencyShift = ui->frequencyShift->getValueNew();
     m_settings.m_sampleRate = value;
     sendSettings();
 }
on_sampleSize_currentIndexChanged
void TestSourceGui::on_sampleSize_currentIndexChanged (int index) private slot
Definition at line 193 of file testsourcegui.cpp.
References displayAmplitude(), TestSourceSettings::m_amplitudeBits, TestSourceSettings::m_sampleSizeIndex, m_settings, sendSettings(), ui, updateAmpCoarseLimit(), and updateAmpFineLimit().
 {
     if ((index < 0) || (index > 2)) {
         return;
     }
     updateAmpCoarseLimit();
     updateAmpFineLimit();
     displayAmplitude();
     m_settings.m_amplitudeBits = ui->amplitudeCoarse->value() * 100 + ui->amplitudeFine->value();
     m_settings.m_sampleSizeIndex = index;
     sendSettings();
 }
on_startStop_toggled
void TestSourceGui::on_startStop_toggled (bool checked) private slot
Definition at line 134 of file testsourcegui.cpp.
References TestSourceInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         TestSourceInput::MsgStartStop *message = TestSourceInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
openDeviceSettingsDialog
void TestSourceGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 521 of file testsourcegui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), TestSourceSettings::m_reverseAPIAddress, TestSourceSettings::m_reverseAPIDeviceIndex, TestSourceSettings::m_reverseAPIPort, m_settings, TestSourceSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by TestSourceGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void TestSourceGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 97 of file testsourcegui.cpp.
References displaySettings(), m_settings, TestSourceSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void TestSourceGui::sendSettings () private
Definition at line 413 of file testsourcegui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_amModulation_valueChanged(), on_amplitudeCoarse_valueChanged(), on_amplitudeFine_valueChanged(), on_autoCorr_currentIndexChanged(), on_centerFrequency_changed(), on_dcBias_valueChanged(), on_decimation_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_fmDeviation_valueChanged(), on_frequencyShift_changed(), on_iBias_valueChanged(), on_modulation_currentIndexChanged(), on_modulationFrequency_valueChanged(), on_phaseImbalance_valueChanged(), on_qBias_valueChanged(), on_sampleRate_changed(), on_sampleSize_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive()) {
         m_updateTimer.start(100);
     }
 }
serialize()
QByteArray TestSourceGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 116 of file testsourcegui.cpp.
References m_settings, and TestSourceSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void TestSourceGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 109 of file testsourcegui.cpp.
References displaySettings(), TestSourceSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void TestSourceGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 87 of file testsourcegui.cpp.
 {
     setObjectName(name);
 }
updateAmpCoarseLimit()
void TestSourceGui::updateAmpCoarseLimit () private
Definition at line 319 of file testsourcegui.cpp.
References ui.
Referenced by displaySettings(), and on_sampleSize_currentIndexChanged().
 {
     switch (ui->sampleSize->currentIndex())
     {
     case 0: // 8 bits: 128
         ui->amplitudeCoarse->setMaximum(1);
         break;
     case 1: // 12 bits 2048
         ui->amplitudeCoarse->setMaximum(20);
         break;
     case 2: // 16 bits 32768
     default:
         ui->amplitudeCoarse->setMaximum(327);
         break;
     }
 }
updateAmpFineLimit()
void TestSourceGui::updateAmpFineLimit () private
Definition at line 336 of file testsourcegui.cpp.
References ui.
Referenced by displaySettings(), on_amplitudeCoarse_valueChanged(), and on_sampleSize_currentIndexChanged().
 {
     switch (ui->sampleSize->currentIndex())
     {
     case 0: // 8 bits: 128
         if (ui->amplitudeCoarse->value() == 1) {
             ui->amplitudeFine->setMaximum(27);
         } else {
             ui->amplitudeFine->setMaximum(99);
         }
         break;
     case 1: // 12 bits 2048
         if (ui->amplitudeCoarse->value() == 20) {
             ui->amplitudeFine->setMaximum(47);
         } else {
             ui->amplitudeFine->setMaximum(99);
         }
         break;
     case 2: // 16 bits 32768
     default:
         if (ui->amplitudeCoarse->value() == 327) {
             ui->amplitudeFine->setMaximum(67);
         } else {
             ui->amplitudeFine->setMaximum(99);
         }
         break;
     }
 }
updateFrequencyShiftLimit()
void TestSourceGui::updateFrequencyShiftLimit () private
Definition at line 365 of file testsourcegui.cpp.
References ui.
Referenced by displaySettings(), and on_sampleRate_changed().
 {
     int sampleRate = ui->sampleRate->getValueNew();
     ui->frequencyShift->setValueRange(false, 7, -sampleRate, sampleRate);
 }
updateHardware
void TestSourceGui::updateHardware () private slot
Definition at line 420 of file testsourcegui.cpp.
References TestSourceInput::MsgConfigureTestSource::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by TestSourceGui().
 {
     if (m_doApplySettings)
     {
         TestSourceInput::MsgConfigureTestSource* message = TestSourceInput::MsgConfigureTestSource::create(m_settings, m_forceSettings);
         m_sampleSource->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void TestSourceGui::updateSampleRateAndFrequency () private
Definition at line 514 of file testsourcegui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceSampleRate, m_deviceUISet, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_deviceSampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg((float)m_deviceSampleRate / 1000));
 }
updateStatus
void TestSourceGui::updateStatus () private slot
Definition at line 431 of file testsourcegui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by TestSourceGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 TestSourceGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 67 of file testsourcegui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceSampleRate
int TestSourceGui::m_deviceSampleRate private
Definition at line 66 of file testsourcegui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* TestSourceGui::m_deviceUISet private
Definition at line 58 of file testsourcegui.h.
Referenced by TestSourceGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool TestSourceGui::m_doApplySettings private
Definition at line 62 of file testsourcegui.h.
Referenced by on_startStop_toggled(), and updateHardware().
m_forceSettings
bool TestSourceGui::m_forceSettings private
Definition at line 63 of file testsourcegui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue TestSourceGui::m_inputMessageQueue private
Definition at line 69 of file testsourcegui.h.
Referenced by handleInputMessages(), and TestSourceGui().
m_lastEngineState
int TestSourceGui::m_lastEngineState private
Definition at line 68 of file testsourcegui.h.
Referenced by updateStatus().
m_sampleSource
DeviceSampleSource* TestSourceGui::m_sampleSource private
Definition at line 64 of file testsourcegui.h.
Referenced by on_record_toggled(), on_startStop_toggled(), TestSourceGui(), and updateHardware().
m_settings
TestSourceSettings TestSourceGui::m_settings private
Definition at line 59 of file testsourcegui.h.
Referenced by deserialize(), displaySettings(), getCenterFrequency(), handleMessage(), on_amModulation_valueChanged(), on_amplitudeCoarse_valueChanged(), on_amplitudeFine_valueChanged(), on_autoCorr_currentIndexChanged(), on_centerFrequency_changed(), on_dcBias_valueChanged(), on_decimation_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_fmDeviation_valueChanged(), on_frequencyShift_changed(), on_iBias_valueChanged(), on_modulation_currentIndexChanged(), on_modulationFrequency_valueChanged(), on_phaseImbalance_valueChanged(), on_qBias_valueChanged(), on_sampleRate_changed(), on_sampleSize_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), and updateHardware().
m_statusTimer
QTimer TestSourceGui::m_statusTimer private
Definition at line 61 of file testsourcegui.h.
Referenced by TestSourceGui().
m_tickCount
std::size_t TestSourceGui::m_tickCount private
Definition at line 65 of file testsourcegui.h.
m_updateTimer
QTimer TestSourceGui::m_updateTimer private
Definition at line 60 of file testsourcegui.h.
Referenced by sendSettings(), TestSourceGui(), and updateHardware().
ui
Ui::TestSourceGui* TestSourceGui::ui private
Definition at line 56 of file testsourcegui.h.
Referenced by displayAmplitude(), displaySettings(), handleMessage(), on_amModulation_valueChanged(), on_amplitudeCoarse_valueChanged(), on_amplitudeFine_valueChanged(), on_dcBias_valueChanged(), on_fmDeviation_valueChanged(), on_iBias_valueChanged(), on_modulationFrequency_valueChanged(), on_phaseImbalance_valueChanged(), on_qBias_valueChanged(), on_record_toggled(), on_sampleRate_changed(), on_sampleSize_currentIndexChanged(), TestSourceGui(), updateAmpCoarseLimit(), updateAmpFineLimit(), updateFrequencyShiftLimit(), updateSampleRateAndFrequency(), updateStatus(), and ~TestSourceGui().
The documentation for this class was generated from the following files:
plugins/samplesource/testsource/testsourcegui.h
plugins/samplesource/testsource/testsourcegui.cpp