SDRAngel: FreeDVModGUI Class Reference
FreeDVModGUI Class Reference
#include <freedvmodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static FreeDVModGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx)
Private Slots
void handleSourceMessages ()
void on_deltaFrequency_changed (qint64 value)
void on_spanLog2_valueChanged (int value)
void on_gaugeInput_toggled (bool checked)
void on_volume_valueChanged (int value)
void on_audioMute_toggled (bool checked)
void on_freeDVMode_currentIndexChanged (int index)
void on_tone_toggled (bool checked)
void on_toneFrequency_valueChanged (int value)
void on_mic_toggled (bool checked)
void on_play_toggled (bool checked)
void on_playLoop_toggled (bool checked)
void on_morseKeyer_toggled (bool checked)
void on_navTimeSlider_valueChanged (int value)
void on_showFileDialog_clicked (bool checked)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void configureFileName ()
void audioSelect ()
void tick ()
Private Member Functions
FreeDVModGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx, QWidget *parent=0)
virtual ~FreeDVModGUI ()
bool blockApplySettings (bool block)
void applySettings (bool force=false)
void applyBandwidths (int spanLog2, bool force=false)
void displayBandwidths (int spanLog2)
void displaySettings ()
void updateWithStreamData ()
void updateWithStreamTime ()
void channelMarkerUpdate ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::FreeDVModGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
FreeDVModSettings m_settings
bool m_doApplySettings
int m_spectrumRate
SpectrumVis * m_spectrumVis
FreeDVMod * m_freeDVMod
MovingAverageUtil< double, double, 20 > m_channelPowerDbAvg
QString m_fileName
quint32 m_recordLength
int m_recordSampleRate
int m_samplesCount
std::size_t m_tickCount
bool m_enableNavTime
MessageQueue m_inputMessageQueue
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 41 of file freedvmodgui.h.
Constructor & Destructor Documentation
FreeDVModGUI()
FreeDVModGUI::FreeDVModGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx, QWidget * parent = 0) explicit private
Definition at line 337 of file freedvmodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applyBandwidths(), arg(), audioSelect(), channelMarkerChangedByCursor(), displaySettings(), FreeDVMod::getCWKeyer(), getInputMessageQueue(), BasebandSampleSink::getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, handleSourceMessages(), FreeDVMod::m_channelIdURI, m_channelMarker, m_deviceUISet, m_freeDVMod, m_settings, m_spectrumRate, m_spectrumVis, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerTxChannelInstance(), resetToDefaults(), SDR_TX_SCALEF, FreeDVModSettings::setChannelMarker(), FreeDVModSettings::setCWKeyerGUI(), BasebandSampleSource::setMessageQueueToGUI(), ChannelMarker::setSourceOrSinkStream(), FreeDVModSettings::setSpectrumGUI(), FreeDVMod::setSpectrumSampleSink(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                            :
     RollupWidget(parent),
     ui(new Ui::FreeDVModGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_doApplySettings(true),
     m_spectrumRate(6000),
     m_recordLength(0),
     m_recordSampleRate(48000),
     m_samplesCount(0),
     m_tickCount(0),
     m_enableNavTime(false)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_spectrumVis = new SpectrumVis(SDR_TX_SCALEF, ui->glSpectrum);
     m_freeDVMod = (FreeDVMod*) channelTx;
     m_freeDVMod->setSpectrumSampleSink(m_spectrumVis);
     m_freeDVMod->setMessageQueueToGUI(getInputMessageQueue());
     resetToDefaults();
     ui->glSpectrum->setCenterFrequency(m_spectrumRate/2);
     ui->glSpectrum->setSampleRate(m_spectrumRate);
     ui->glSpectrum->setDisplayWaterfall(true);
     ui->glSpectrum->setDisplayMaxHold(true);
     ui->glSpectrum->setSsbSpectrum(true);
     ui->glSpectrum->connectTimer(MainWindow::getInstance()->getMasterTimer());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     CRightClickEnabler *audioMuteRightClickEnabler = new CRightClickEnabler(ui->mic);
     connect(audioMuteRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioSelect()));
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     m_channelMarker.setSourceOrSinkStream(false);
     m_channelMarker.setVisible(true);
     m_deviceUISet->registerTxChannelInstance(FreeDVMod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     ui->cwKeyerGUI->setCWKeyer(m_freeDVMod->getCWKeyer());
     ui->spectrumGUI->setBuddies(m_spectrumVis->getInputMessageQueue(), m_spectrumVis, ui->glSpectrum);
     m_settings.setChannelMarker(&m_channelMarker);
     m_settings.setSpectrumGUI(ui->spectrumGUI);
     m_settings.setCWKeyerGUI(ui->cwKeyerGUI);
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     connect(m_freeDVMod, SIGNAL(levelChanged(qreal, qreal, int)), ui->volumeMeter, SLOT(levelChanged(qreal, qreal, int)));
     displaySettings();
     applyBandwidths(5 - ui->spanLog2->value(), true); // does applySettings(true)
 }
~FreeDVModGUI()
FreeDVModGUI::~FreeDVModGUI () private virtual
Definition at line 402 of file freedvmodgui.cpp.
References m_deviceUISet, m_freeDVMod, m_spectrumVis, DeviceUISet::removeTxChannelInstance(), and ui.
 {
     m_deviceUISet->removeTxChannelInstance(this);
     delete m_freeDVMod; // TODO: check this: when the GUI closes it has to delete the modulator
     delete m_spectrumVis;
     delete ui;
 }
Member Function Documentation
applyBandwidths()
void FreeDVModGUI::applyBandwidths (int spanLog2, bool force = false) private
Definition at line 430 of file freedvmodgui.cpp.
References applySettings(), displayBandwidths(), m_settings, and FreeDVModSettings::m_spanLog2.
Referenced by deserialize(), FreeDVModGUI(), handleMessage(), and on_spanLog2_valueChanged().
 {
     displayBandwidths(spanLog2);
     m_settings.m_spanLog2 = spanLog2;
     applySettings(force);
 }
applySettings()
void FreeDVModGUI::applySettings (bool force = false) private
Definition at line 417 of file freedvmodgui.cpp.
References FreeDVMod::MsgConfigureFreeDVMod::create(), FreeDVMod::MsgConfigureChannelizer::create(), BasebandSampleSource::getInputMessageQueue(), m_doApplySettings, m_freeDVMod, FreeDVModSettings::m_inputFrequencyOffset, m_settings, and MessageQueue::push().
Referenced by applyBandwidths(), audioSelect(), channelMarkerChangedByCursor(), channelMarkerUpdate(), on_audioMute_toggled(), on_deltaFrequency_changed(), on_freeDVMode_currentIndexChanged(), on_gaugeInput_toggled(), on_mic_toggled(), on_morseKeyer_toggled(), on_play_toggled(), on_playLoop_toggled(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), and setCenterFrequency().
 {
     if (m_doApplySettings)
     {
         FreeDVMod::MsgConfigureChannelizer *msgChan = FreeDVMod::MsgConfigureChannelizer::create(
                 48000, m_settings.m_inputFrequencyOffset);
         m_freeDVMod->getInputMessageQueue()->push(msgChan);
         FreeDVMod::MsgConfigureFreeDVMod *msg = FreeDVMod::MsgConfigureFreeDVMod::create(m_settings, force);
         m_freeDVMod->getInputMessageQueue()->push(msg);
     }
 }
audioSelect
void FreeDVModGUI::audioSelect () private slot
Definition at line 522 of file freedvmodgui.cpp.
References applySettings(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, FreeDVModSettings::m_audioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by FreeDVModGUI().
 {
     qDebug("FreeDVModGUI::audioSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName, true); // true for input
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_audioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
blockApplySettings()
bool FreeDVModGUI::blockApplySettings (bool block) private
Definition at line 410 of file freedvmodgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     bool ret = !m_doApplySettings;
     m_doApplySettings = !block;
     return ret;
 }
channelMarkerChangedByCursor
void FreeDVModGUI::channelMarkerChangedByCursor () slot
Definition at line 143 of file freedvmodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, FreeDVModSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by FreeDVModGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
channelMarkerUpdate()
void FreeDVModGUI::channelMarkerUpdate () private
Definition at line 150 of file freedvmodgui.cpp.
References applySettings(), displaySettings(), ChannelMarker::getColor(), m_channelMarker, FreeDVModSettings::m_rgbColor, and m_settings.
 {
     m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
     displaySettings();
     applySettings();
 }
configureFileName
void FreeDVModGUI::configureFileName () private slot
Definition at line 292 of file freedvmodgui.cpp.
References FreeDVMod::MsgConfigureFileSourceName::create(), BasebandSampleSource::getInputMessageQueue(), m_fileName, m_freeDVMod, and MessageQueue::push().
Referenced by on_showFileDialog_clicked().
 {
     qDebug() << "FileSourceGui::configureFileName: " << m_fileName.toStdString().c_str();
     FreeDVMod::MsgConfigureFileSourceName* message = FreeDVMod::MsgConfigureFileSourceName::create(m_fileName);
     m_freeDVMod->getInputMessageQueue()->push(message);
 }
create()
FreeDVModGUI * FreeDVModGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx) static
Definition at line 39 of file freedvmodgui.cpp.
References FreeDVModGUI().
Referenced by FreeDVModPlugin::createTxChannelGUI().
 {
     FreeDVModGUI* gui = new FreeDVModGUI(pluginAPI, deviceUISet, channelTx);
     return gui;
 }
deserialize()
bool FreeDVModGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 81 of file freedvmodgui.cpp.
References applyBandwidths(), FreeDVModSettings::deserialize(), displaySettings(), m_settings, FreeDVModSettings::resetToDefaults(), and ui.
 {
     if(m_settings.deserialize(data))
     {
         qDebug("FreeDVModGUI::deserialize");
         displaySettings();
         applyBandwidths(5 - ui->spanLog2->value(), true); // does applySettings(true)
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         displaySettings();
         applyBandwidths(5 - ui->spanLog2->value(), true); // does applySettings(true)
         return false;
     }
 }
destroy()
void FreeDVModGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 45 of file freedvmodgui.cpp.
 {
     delete this;
 }
displayBandwidths()
void FreeDVModGUI::displayBandwidths (int spanLog2) private
Definition at line 437 of file freedvmodgui.cpp.
References arg(), FreeDVMod::getModemSampleRate(), m_freeDVMod, m_spectrumRate, and ui.
Referenced by applyBandwidths(), and displaySettings().
 {
     m_spectrumRate = m_freeDVMod->getModemSampleRate() / (1<<spanLog2);
     int bwMax = m_freeDVMod->getModemSampleRate() / (100*(1<<spanLog2));
     qDebug() << "FreeDVModGUI::displayBandwidths:"
             << " spanLog2: " << spanLog2
             << " m_spectrumRate: " << m_spectrumRate
             << " bwMax: " << bwMax;
     QString spanStr = QString::number(bwMax/10.0, 'f', 1);
     ui->spanText->setText(tr("%1k").arg(spanStr));
     ui->glSpectrum->setCenterFrequency(m_spectrumRate/2);
     ui->glSpectrum->setSampleRate(m_spectrumRate);
     ui->glSpectrum->setSsbSpectrum(true);
     ui->glSpectrum->setLsbDisplay(false);
 }
displaySettings()
void FreeDVModGUI::displaySettings () private
Definition at line 456 of file freedvmodgui.cpp.
References arg(), blockApplySettings(), displayBandwidths(), FreeDVModSettings::getHiCutoff(), FreeDVModSettings::getLowCutoff(), ChannelMarker::getTitle(), FreeDVModSettings::m_audioMute, m_channelMarker, FreeDVModSettings::m_freeDVMode, FreeDVModSettings::m_gaugeInputElseModem, FreeDVModSettings::m_inputFrequencyOffset, FreeDVModSettings::m_modAFInput, FreeDVModSettings::m_playLoop, FreeDVModSettings::m_rgbColor, m_settings, FreeDVModSettings::m_spanLog2, FreeDVModSettings::m_title, FreeDVModSettings::m_toneFrequency, FreeDVModSettings::m_volumeFactor, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setLowCutoff(), ChannelMarker::setSidebands(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ui, and ChannelMarker::usb.
Referenced by channelMarkerUpdate(), deserialize(), FreeDVModGUI(), and handleMessage().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.setBandwidth(FreeDVModSettings::getHiCutoff(m_settings.m_freeDVMode) * 2);
     m_channelMarker.setLowCutoff(FreeDVModSettings::getLowCutoff(m_settings.m_freeDVMode));
     m_channelMarker.setSidebands(ChannelMarker::usb);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->freeDVMode->setCurrentIndex((int) m_settings.m_freeDVMode);
     ui->audioMute->setChecked(m_settings.m_audioMute);
     ui->playLoop->setChecked(m_settings.m_playLoop);
     // Prevent uncontrolled triggering of applyBandwidths
     ui->spanLog2->blockSignals(true);
     ui->spanLog2->setValue(5 - m_settings.m_spanLog2);
     displayBandwidths(m_settings.m_spanLog2);
     ui->spanLog2->blockSignals(false);
     ui->gaugeInput->setChecked(m_settings.m_gaugeInputElseModem);
     // The only one of the four signals triggering applyBandwidths will trigger it once only with all other values
     // set correctly and therefore validate the settings and apply them to dependent widgets
     ui->deltaFrequency->setValue(m_settings.m_inputFrequencyOffset);
     ui->toneFrequency->setValue(roundf(m_settings.m_toneFrequency / 10.0));
     ui->toneFrequencyText->setText(QString("%1k").arg(m_settings.m_toneFrequency / 1000.0, 0, 'f', 2));
     ui->volume->setValue(m_settings.m_volumeFactor * 10.0);
     ui->volumeText->setText(QString("%1").arg(m_settings.m_volumeFactor, 0, 'f', 1));
     ui->tone->setEnabled((m_settings.m_modAFInput == FreeDVModSettings::FreeDVModInputAF::FreeDVModInputTone)
             || (m_settings.m_modAFInput == FreeDVModSettings::FreeDVModInputAF::FreeDVModInputNone));
     ui->mic->setEnabled((m_settings.m_modAFInput == FreeDVModSettings::FreeDVModInputAF::FreeDVModInputAudio)
             || (m_settings.m_modAFInput == FreeDVModSettings::FreeDVModInputAF::FreeDVModInputNone));
     ui->play->setEnabled((m_settings.m_modAFInput == FreeDVModSettings::FreeDVModInputAF::FreeDVModInputFile)
             || (m_settings.m_modAFInput == FreeDVModSettings::FreeDVModInputAF::FreeDVModInputNone));
     ui->morseKeyer->setEnabled((m_settings.m_modAFInput == FreeDVModSettings::FreeDVModInputAF::FreeDVModInputCWTone)
             || (m_settings.m_modAFInput == FreeDVModSettings::FreeDVModInputAF::FreeDVModInputNone));
     ui->tone->setChecked(m_settings.m_modAFInput == FreeDVModSettings::FreeDVModInputAF::FreeDVModInputTone);
     ui->mic->setChecked(m_settings.m_modAFInput == FreeDVModSettings::FreeDVModInputAF::FreeDVModInputAudio);
     ui->play->setChecked(m_settings.m_modAFInput == FreeDVModSettings::FreeDVModInputAF::FreeDVModInputFile);
     ui->morseKeyer->setChecked(m_settings.m_modAFInput == FreeDVModSettings::FreeDVModInputAF::FreeDVModInputCWTone);
     blockApplySettings(false);
 }
enterEvent()
void FreeDVModGUI::enterEvent (QEvent *) private
Definition at line 517 of file freedvmodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 FreeDVModGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 60 of file freedvmodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
{
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* FreeDVModGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 56 of file freedvmodgui.h.
Referenced by FreeDVModGUI(), and handleSourceMessages().
 { return &m_inputMessageQueue; }
getName()
QString FreeDVModGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 55 of file freedvmodgui.cpp.
 {
     return objectName();
 }
handleMessage()
bool FreeDVModGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 99 of file freedvmodgui.cpp.
References applyBandwidths(), blockApplySettings(), displaySettings(), FreeDVMod::getModemSampleRate(), FreeDVMod::MsgConfigureFreeDVMod::getSettings(), CWKeyer::MsgConfigureCWKeyer::getSettings(), m_freeDVMod, m_recordLength, m_recordSampleRate, m_samplesCount, m_settings, Message::match(), ui, updateWithStreamData(), and updateWithStreamTime().
Referenced by handleSourceMessages().
 {
     if (FreeDVMod::MsgReportFileSourceStreamData::match(message))
     {
         m_recordSampleRate = ((FreeDVMod::MsgReportFileSourceStreamData&)message).getSampleRate();
         m_recordLength = ((FreeDVMod::MsgReportFileSourceStreamData&)message).getRecordLength();
         m_samplesCount = 0;
         updateWithStreamData();
         return true;
     }
     else if (FreeDVMod::MsgReportFileSourceStreamTiming::match(message))
     {
         m_samplesCount = ((FreeDVMod::MsgReportFileSourceStreamTiming&)message).getSamplesCount();
         updateWithStreamTime();
         return true;
     }
     else if (DSPConfigureAudio::match(message))
     {
         qDebug("FreeDVModGUI::handleMessage: DSPConfigureAudio: %d", m_freeDVMod->getModemSampleRate());
         applyBandwidths(5 - ui->spanLog2->value()); // will update spectrum details with new sample rate
         return true;
     }
     else if (FreeDVMod::MsgConfigureFreeDVMod::match(message))
     {
         const FreeDVMod::MsgConfigureFreeDVMod& cfg = (FreeDVMod::MsgConfigureFreeDVMod&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (CWKeyer::MsgConfigureCWKeyer::match(message))
     {
         const CWKeyer::MsgConfigureCWKeyer& cfg = (CWKeyer::MsgConfigureCWKeyer&) message;
         ui->cwKeyerGUI->setSettings(cfg.getSettings());
         ui->cwKeyerGUI->displaySettings();
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void FreeDVModGUI::handleSourceMessages () private slot
Definition at line 157 of file freedvmodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by FreeDVModGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void FreeDVModGUI::leaveEvent (QEvent *) private
Definition at line 512 of file freedvmodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_audioMute_toggled
void FreeDVModGUI::on_audioMute_toggled (bool checked) private slot
Definition at line 206 of file freedvmodgui.cpp.
References applySettings(), FreeDVModSettings::m_audioMute, and m_settings.
 {
     m_settings.m_audioMute = checked;
     applySettings();
 }
on_deltaFrequency_changed
void FreeDVModGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 170 of file freedvmodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, FreeDVModSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_freeDVMode_currentIndexChanged
void FreeDVModGUI::on_freeDVMode_currentIndexChanged (int index) private slot
Definition at line 212 of file freedvmodgui.cpp.
References applySettings(), FreeDVModSettings::getHiCutoff(), FreeDVModSettings::getLowCutoff(), m_channelMarker, FreeDVModSettings::m_freeDVMode, m_settings, ChannelMarker::setBandwidth(), and ChannelMarker::setLowCutoff().
 {
     m_settings.m_freeDVMode = (FreeDVModSettings::FreeDVMode) index;
     m_channelMarker.setBandwidth(FreeDVModSettings::getHiCutoff(m_settings.m_freeDVMode) * 2);
     m_channelMarker.setLowCutoff(FreeDVModSettings::getLowCutoff(m_settings.m_freeDVMode));
     applySettings();
 }
on_gaugeInput_toggled
void FreeDVModGUI::on_gaugeInput_toggled (bool checked) private slot
Definition at line 186 of file freedvmodgui.cpp.
References applySettings(), FreeDVModSettings::m_gaugeInputElseModem, and m_settings.
 {
     m_settings.m_gaugeInputElseModem = checked;
     applySettings();
 }
on_mic_toggled
void FreeDVModGUI::on_mic_toggled (bool checked) private slot
Definition at line 255 of file freedvmodgui.cpp.
References applySettings(), FreeDVModSettings::FreeDVModInputAudio, FreeDVModSettings::FreeDVModInputNone, FreeDVModSettings::m_modAFInput, m_settings, and ui.
 {
     ui->play->setEnabled(!checked); // release other source inputs
     ui->morseKeyer->setEnabled(!checked);
     ui->tone->setEnabled(!checked); // release other source inputs
     m_settings.m_modAFInput = checked ? FreeDVModSettings::FreeDVModInputAudio : FreeDVModSettings::FreeDVModInputNone;
     applySettings();
 }
on_morseKeyer_toggled
void FreeDVModGUI::on_morseKeyer_toggled (bool checked) private slot
Definition at line 246 of file freedvmodgui.cpp.
References applySettings(), FreeDVModSettings::FreeDVModInputCWTone, FreeDVModSettings::FreeDVModInputNone, FreeDVModSettings::m_modAFInput, m_settings, and ui.
 {
     ui->play->setEnabled(!checked); // release other source inputs
     ui->tone->setEnabled(!checked); // release other source inputs
     ui->mic->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? FreeDVModSettings::FreeDVModInputCWTone : FreeDVModSettings::FreeDVModInputNone;
     applySettings();
 }
on_navTimeSlider_valueChanged
void FreeDVModGUI::on_navTimeSlider_valueChanged (int value) private slot
Definition at line 264 of file freedvmodgui.cpp.
References FreeDVMod::MsgConfigureFileSourceSeek::create(), BasebandSampleSource::getInputMessageQueue(), m_enableNavTime, m_freeDVMod, m_recordLength, and MessageQueue::push().
 {
     if (m_enableNavTime && ((value >= 0) && (value <= 100)))
     {
         int t_sec = (m_recordLength * value) / 100;
         QTime t(0, 0, 0, 0);
         t = t.addSecs(t_sec);
         FreeDVMod::MsgConfigureFileSourceSeek* message = FreeDVMod::MsgConfigureFileSourceSeek::create(value);
         m_freeDVMod->getInputMessageQueue()->push(message);
     }
 }
on_play_toggled
void FreeDVModGUI::on_play_toggled (bool checked) private slot
Definition at line 226 of file freedvmodgui.cpp.
References applySettings(), FreeDVModSettings::FreeDVModInputFile, FreeDVModSettings::FreeDVModInputNone, m_enableNavTime, FreeDVModSettings::m_modAFInput, m_settings, and ui.
 {
     ui->tone->setEnabled(!checked); // release other source inputs
     ui->morseKeyer->setEnabled(!checked);
     ui->mic->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? FreeDVModSettings::FreeDVModInputFile : FreeDVModSettings::FreeDVModInputNone;
     applySettings();
     ui->navTimeSlider->setEnabled(!checked);
     m_enableNavTime = !checked;
 }
on_playLoop_toggled
void FreeDVModGUI::on_playLoop_toggled (bool checked) private slot
Definition at line 220 of file freedvmodgui.cpp.
References applySettings(), FreeDVModSettings::m_playLoop, and m_settings.
 {
     m_settings.m_playLoop = checked;
     applySettings();
 }
on_showFileDialog_clicked
void FreeDVModGUI::on_showFileDialog_clicked (bool checked) private slot
Definition at line 277 of file freedvmodgui.cpp.
References configureFileName(), m_fileName, and ui.
 {
     (void) checked;
     QString fileName = QFileDialog::getOpenFileName(this,
         tr("Open raw audio file"), ".", tr("Raw audio Files (*.raw)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "")
     {
         m_fileName = fileName;
         ui->recordFileText->setText(m_fileName);
         ui->play->setEnabled(true);
         configureFileName();
     }
 }
on_spanLog2_valueChanged
void FreeDVModGUI::on_spanLog2_valueChanged (int value) private slot
Definition at line 177 of file freedvmodgui.cpp.
References applyBandwidths().
 {
     if ((value < 0) || (value > 4)) {
         return;
     }
     applyBandwidths(5 - value);
 }
on_tone_toggled
void FreeDVModGUI::on_tone_toggled (bool checked) private slot
Definition at line 237 of file freedvmodgui.cpp.
References applySettings(), FreeDVModSettings::FreeDVModInputNone, FreeDVModSettings::FreeDVModInputTone, FreeDVModSettings::m_modAFInput, m_settings, and ui.
 {
     ui->play->setEnabled(!checked); // release other source inputs
     ui->morseKeyer->setEnabled(!checked);
     ui->mic->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? FreeDVModSettings::FreeDVModInputTone : FreeDVModSettings::FreeDVModInputNone;
     applySettings();
 }
on_toneFrequency_valueChanged
void FreeDVModGUI::on_toneFrequency_valueChanged (int value) private slot
Definition at line 192 of file freedvmodgui.cpp.
References applySettings(), arg(), m_settings, FreeDVModSettings::m_toneFrequency, and ui.
 {
     ui->toneFrequencyText->setText(QString("%1k").arg(value / 100.0, 0, 'f', 2));
     m_settings.m_toneFrequency = value * 10.0;
     applySettings();
 }
on_volume_valueChanged
void FreeDVModGUI::on_volume_valueChanged (int value) private slot
Definition at line 199 of file freedvmodgui.cpp.
References applySettings(), arg(), m_settings, FreeDVModSettings::m_volumeFactor, and ui.
 {
     ui->volumeText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_volumeFactor = value / 10.0;
     applySettings();
 }
onMenuDialogCalled
void FreeDVModGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 305 of file freedvmodgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, FreeDVModSettings::m_inputFrequencyOffset, FreeDVModSettings::m_reverseAPIAddress, FreeDVModSettings::m_reverseAPIChannelIndex, FreeDVModSettings::m_reverseAPIDeviceIndex, FreeDVModSettings::m_reverseAPIPort, FreeDVModSettings::m_rgbColor, m_settings, FreeDVModSettings::m_title, FreeDVModSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by FreeDVModGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void FreeDVModGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 299 of file freedvmodgui.cpp.
Referenced by FreeDVModGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void FreeDVModGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 71 of file freedvmodgui.cpp.
References m_settings, and FreeDVModSettings::resetToDefaults().
Referenced by FreeDVModGUI().
 {
     m_settings.resetToDefaults();
 }
serialize()
QByteArray FreeDVModGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 76 of file freedvmodgui.cpp.
References m_settings, and FreeDVModSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void FreeDVModGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 64 of file freedvmodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, FreeDVModSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
setName()
void FreeDVModGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 50 of file freedvmodgui.cpp.
 {
     setObjectName(name);
 }
tick
void FreeDVModGUI::tick () private slot
Definition at line 535 of file freedvmodgui.cpp.
References arg(), FreeDVMod::MsgConfigureFileSourceStreamTiming::create(), CalcDb::dbPower(), FreeDVModSettings::FreeDVModInputFile, BasebandSampleSource::getInputMessageQueue(), FreeDVMod::getMagSq(), m_channelPowerDbAvg, m_freeDVMod, FreeDVModSettings::m_modAFInput, m_settings, m_tickCount, MessageQueue::push(), and ui.
Referenced by FreeDVModGUI().
 {
     double powDb = CalcDb::dbPower(m_freeDVMod->getMagSq());
     m_channelPowerDbAvg(powDb);
     ui->channelPower->setText(tr("%1 dB").arg(m_channelPowerDbAvg.asDouble(), 0, 'f', 1));
     if (((++m_tickCount & 0xf) == 0) && (m_settings.m_modAFInput == FreeDVModSettings::FreeDVModInputFile))
     {
         FreeDVMod::MsgConfigureFileSourceStreamTiming* message = FreeDVMod::MsgConfigureFileSourceStreamTiming::create();
         m_freeDVMod->getInputMessageQueue()->push(message);
     }
 }
updateWithStreamData()
void FreeDVModGUI::updateWithStreamData () private
Definition at line 548 of file freedvmodgui.cpp.
References m_recordLength, ui, and updateWithStreamTime().
Referenced by handleMessage().
 {
     QTime recordLength(0, 0, 0, 0);
     recordLength = recordLength.addSecs(m_recordLength);
     QString s_time = recordLength.toString("HH:mm:ss");
     ui->recordLengthText->setText(s_time);
     updateWithStreamTime();
 }
updateWithStreamTime()
void FreeDVModGUI::updateWithStreamTime () private
Definition at line 557 of file freedvmodgui.cpp.
References m_enableNavTime, m_recordLength, m_recordSampleRate, m_samplesCount, and ui.
Referenced by handleMessage(), and updateWithStreamData().
 {
     int t_sec = 0;
     int t_msec = 0;
     if (m_recordSampleRate > 0)
     {
         t_msec = ((m_samplesCount * 1000) / m_recordSampleRate) % 1000;
         t_sec = m_samplesCount / m_recordSampleRate;
     }
     QTime t(0, 0, 0, 0);
     t = t.addSecs(t_sec);
     t = t.addMSecs(t_msec);
     QString s_timems = t.toString("HH:mm:ss.zzz");
     QString s_time = t.toString("HH:mm:ss");
     ui->relTimeText->setText(s_timems);
     if (!m_enableNavTime)
     {
         float posRatio = (float) t_sec / (float) m_recordLength;
         ui->navTimeSlider->setValue((int) (posRatio * 100.0));
     }
 }
Member Data Documentation
m_channelMarker
ChannelMarker FreeDVModGUI::m_channelMarker private
Definition at line 66 of file freedvmodgui.h.
Referenced by channelMarkerChangedByCursor(), channelMarkerUpdate(), displaySettings(), enterEvent(), FreeDVModGUI(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), on_freeDVMode_currentIndexChanged(), onMenuDialogCalled(), and setCenterFrequency().
m_channelPowerDbAvg
MovingAverageUtil<double, double, 20> FreeDVModGUI::m_channelPowerDbAvg private
Definition at line 73 of file freedvmodgui.h.
Referenced by tick().
m_deviceUISet
DeviceUISet* FreeDVModGUI::m_deviceUISet private
Definition at line 65 of file freedvmodgui.h.
Referenced by FreeDVModGUI(), and ~FreeDVModGUI().
m_doApplySettings
bool FreeDVModGUI::m_doApplySettings private
Definition at line 68 of file freedvmodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_enableNavTime
bool FreeDVModGUI::m_enableNavTime private
Definition at line 80 of file freedvmodgui.h.
Referenced by on_navTimeSlider_valueChanged(), on_play_toggled(), and updateWithStreamTime().
m_fileName
QString FreeDVModGUI::m_fileName private
Definition at line 75 of file freedvmodgui.h.
Referenced by configureFileName(), and on_showFileDialog_clicked().
m_freeDVMod
FreeDVMod* FreeDVModGUI::m_freeDVMod private
Definition at line 72 of file freedvmodgui.h.
Referenced by applySettings(), configureFileName(), displayBandwidths(), FreeDVModGUI(), handleMessage(), on_navTimeSlider_valueChanged(), tick(), and ~FreeDVModGUI().
m_inputMessageQueue
MessageQueue FreeDVModGUI::m_inputMessageQueue private
Definition at line 81 of file freedvmodgui.h.
m_pluginAPI
PluginAPI* FreeDVModGUI::m_pluginAPI private
Definition at line 64 of file freedvmodgui.h.
m_recordLength
quint32 FreeDVModGUI::m_recordLength private
Definition at line 76 of file freedvmodgui.h.
Referenced by handleMessage(), on_navTimeSlider_valueChanged(), updateWithStreamData(), and updateWithStreamTime().
m_recordSampleRate
int FreeDVModGUI::m_recordSampleRate private
Definition at line 77 of file freedvmodgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_samplesCount
int FreeDVModGUI::m_samplesCount private
Definition at line 78 of file freedvmodgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_settings
FreeDVModSettings FreeDVModGUI::m_settings private
Definition at line 67 of file freedvmodgui.h.
Referenced by applyBandwidths(), applySettings(), audioSelect(), channelMarkerChangedByCursor(), channelMarkerUpdate(), deserialize(), displaySettings(), FreeDVModGUI(), handleMessage(), on_audioMute_toggled(), on_deltaFrequency_changed(), on_freeDVMode_currentIndexChanged(), on_gaugeInput_toggled(), on_mic_toggled(), on_morseKeyer_toggled(), on_play_toggled(), on_playLoop_toggled(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), serialize(), setCenterFrequency(), and tick().
m_spectrumRate
int FreeDVModGUI::m_spectrumRate private
Definition at line 69 of file freedvmodgui.h.
Referenced by displayBandwidths(), and FreeDVModGUI().
m_spectrumVis
SpectrumVis* FreeDVModGUI::m_spectrumVis private
Definition at line 71 of file freedvmodgui.h.
Referenced by FreeDVModGUI(), and ~FreeDVModGUI().
m_tickCount
std::size_t FreeDVModGUI::m_tickCount private
Definition at line 79 of file freedvmodgui.h.
Referenced by tick().
ui
Ui::FreeDVModGUI* FreeDVModGUI::ui private
Definition at line 63 of file freedvmodgui.h.
Referenced by channelMarkerChangedByCursor(), deserialize(), displayBandwidths(), displaySettings(), FreeDVModGUI(), handleMessage(), on_mic_toggled(), on_morseKeyer_toggled(), on_play_toggled(), on_showFileDialog_clicked(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), tick(), updateWithStreamData(), updateWithStreamTime(), and ~FreeDVModGUI().
The documentation for this class was generated from the following files:
plugins/channeltx/modfreedv/freedvmodgui.h
plugins/channeltx/modfreedv/freedvmodgui.cpp