SDRAngel: FCDProPlusGui Class Reference
FCDProPlusGui Class Reference
#include <fcdproplusgui.h>
Public Member Functions
FCDProPlusGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~FCDProPlusGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_centerFrequency_changed (quint64 value)
void on_decim_currentIndexChanged (int index)
void on_fcPos_currentIndexChanged (int index)
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_checkBoxG_stateChanged (int state)
void on_checkBoxB_stateChanged (int state)
void on_mixGain_stateChanged (int state)
void on_ifGain_valueChanged (int value)
void on_filterRF_currentIndexChanged (int index)
void on_filterIF_currentIndexChanged (int index)
void on_ppm_valueChanged (int value)
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void on_transverter_clicked ()
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void updateFrequencyLimits ()
Private Attributes
Ui::FCDProPlusGui * ui
DeviceUISet * m_deviceUISet
bool m_doApplySettings
bool m_forceSettings
FCDProPlusSettings m_settings
QTimer m_updateTimer
QTimer m_statusTimer
std::vector< int > m_gains
DeviceSampleSource * m_sampleSource
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 35 of file fcdproplusgui.h.
Constructor & Destructor Documentation
FCDProPlusGui()
FCDProPlusGui::FCDProPlusGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 35 of file fcdproplusgui.cpp.
References displaySettings(), FCDProPlusConstants::fcdproplus_if_filter_nb_values(), FCDProPlusConstants::fcdproplus_rf_filter_nb_values(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, handleInputMessages(), i, FCDProPlusConstants::if_filters, DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_sampleSource, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), FCDProPlusConstants::rf_filters, DeviceSampleSource::setMessageQueueToGUI(), ui, updateFrequencyLimits(), updateHardware(), and updateStatus().
                                                                       :
     QWidget(parent),
     ui(new Ui::FCDProPlusGui),
     m_deviceUISet(deviceUISet),
     m_forceSettings(true),
     m_settings(),
     m_sampleSource(NULL),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     m_sampleSource = (FCDProPlusInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     updateFrequencyLimits();
     ui->filterIF->clear();
     for (int i = 0; i < FCDProPlusConstants::fcdproplus_if_filter_nb_values(); i++)
     {
         ui->filterIF->addItem(QString(FCDProPlusConstants::if_filters[i].label.c_str()), i);
     }
     ui->filterRF->clear();
     for (int i = 0; i < FCDProPlusConstants::fcdproplus_rf_filter_nb_values(); i++)
     {
         ui->filterRF->addItem(QString(FCDProPlusConstants::rf_filters[i].label.c_str()), i);
     }
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
 }
~FCDProPlusGui()
FCDProPlusGui::~FCDProPlusGui () virtual
Definition at line 76 of file fcdproplusgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void FCDProPlusGui::blockApplySettings (bool block) inline private
Definition at line 70 of file fcdproplusgui.h.
Referenced by handleMessage().
 { m_doApplySettings = !block; }
deserialize()
bool FCDProPlusGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 120 of file fcdproplusgui.cpp.
References FCDProPlusSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void FCDProPlusGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 81 of file fcdproplusgui.cpp.
 {
     delete this;
 }
displaySettings()
void FCDProPlusGui::displaySettings () private
Definition at line 210 of file fcdproplusgui.cpp.
References arg(), FCDProPlusSettings::m_biasT, FCDProPlusSettings::m_centerFrequency, FCDProPlusSettings::m_dcBlock, FCDProPlusSettings::m_fcPos, FCDProPlusSettings::m_ifFilterIndex, FCDProPlusSettings::m_ifGain, FCDProPlusSettings::m_iqImbalance, FCDProPlusSettings::m_lnaGain, FCDProPlusSettings::m_log2Decim, FCDProPlusSettings::m_LOppmTenths, FCDProPlusSettings::m_mixGain, FCDProPlusSettings::m_rfFilterIndex, m_settings, FCDProPlusSettings::m_transverterDeltaFrequency, FCDProPlusSettings::m_transverterMode, ui, and updateFrequencyLimits().
Referenced by deserialize(), FCDProPlusGui(), handleMessage(), on_ifGain_valueChanged(), on_ppm_valueChanged(), resetToDefaults(), and setCenterFrequency().
 {
     ui->transverter->setDeltaFrequency(m_settings.m_transverterDeltaFrequency);
     ui->transverter->setDeltaFrequencyActive(m_settings.m_transverterMode);
     updateFrequencyLimits();
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     ui->decim->setCurrentIndex(m_settings.m_log2Decim);
     ui->fcPos->setCurrentIndex((int) m_settings.m_fcPos);
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqImbalance);
     ui->checkBoxG->setChecked(m_settings.m_lnaGain);
     ui->checkBoxB->setChecked(m_settings.m_biasT);
     ui->mixGain->setChecked(m_settings.m_mixGain);
     ui->ifGain->setValue(m_settings.m_ifGain);
     ui->ifGainText->setText(QString("%1dB").arg(m_settings.m_ifGain));
     ui->filterIF->setCurrentIndex(m_settings.m_ifFilterIndex);
     ui->filterRF->setCurrentIndex(m_settings.m_rfFilterIndex);
     ui->ppm->setValue(m_settings.m_LOppmTenths);
     ui->ppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
 }
getCenterFrequency()
qint64 FCDProPlusGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 103 of file fcdproplusgui.cpp.
References FCDProPlusSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* FCDProPlusGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 51 of file fcdproplusgui.h.
 { return &m_inputMessageQueue; }
getName()
QString FCDProPlusGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 91 of file fcdproplusgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void FCDProPlusGui::handleInputMessages () private slot
Definition at line 162 of file fcdproplusgui.cpp.
References DSPSignalNotification::getCenterFrequency(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by FCDProPlusGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("FCDProPlusGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool FCDProPlusGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 136 of file fcdproplusgui.cpp.
References blockApplySettings(), displaySettings(), FCDProPlusInput::MsgConfigureFCDProPlus::getSettings(), FCDProPlusInput::MsgStartStop::getStartStop(), m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (FCDProPlusInput::MsgConfigureFCDProPlus::match(message))
     {
         const FCDProPlusInput::MsgConfigureFCDProPlus& cfg = (FCDProPlusInput::MsgConfigureFCDProPlus&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (FCDProPlusInput::MsgStartStop::match(message))
     {
         FCDProPlusInput::MsgStartStop& notif = (FCDProPlusInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_centerFrequency_changed
void FCDProPlusGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 237 of file fcdproplusgui.cpp.
References FCDProPlusSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_checkBoxB_stateChanged
void FCDProPlusGui::on_checkBoxB_stateChanged (int state) private slot
Definition at line 322 of file fcdproplusgui.cpp.
References FCDProPlusSettings::m_biasT, m_settings, and sendSettings().
 {
     m_settings.m_biasT = (state == Qt::Checked);
     sendSettings();
 }
on_checkBoxG_stateChanged
void FCDProPlusGui::on_checkBoxG_stateChanged (int state) private slot
Definition at line 316 of file fcdproplusgui.cpp.
References FCDProPlusSettings::m_lnaGain, m_settings, and sendSettings().
 {
     m_settings.m_lnaGain = (state == Qt::Checked);
     sendSettings();
 }
on_dcOffset_toggled
void FCDProPlusGui::on_dcOffset_toggled (bool checked) private slot
Definition at line 267 of file fcdproplusgui.cpp.
References FCDProPlusSettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_decim_currentIndexChanged
void FCDProPlusGui::on_decim_currentIndexChanged (int index) private slot
Definition at line 243 of file fcdproplusgui.cpp.
References FCDProPlusSettings::m_log2Decim, m_settings, and sendSettings().
 {
     if ((index < 0) || (index > 6)) {
         return;
     }
     m_settings.m_log2Decim = index;
     sendSettings();
 }
on_fcPos_currentIndexChanged
void FCDProPlusGui::on_fcPos_currentIndexChanged (int index) private slot
Definition at line 253 of file fcdproplusgui.cpp.
References FCDProPlusSettings::FC_POS_CENTER, FCDProPlusSettings::FC_POS_INFRA, FCDProPlusSettings::FC_POS_SUPRA, FCDProPlusSettings::m_fcPos, m_settings, and sendSettings().
 {
     if (index == 0) {
         m_settings.m_fcPos = FCDProPlusSettings::FC_POS_INFRA;
         sendSettings();
     } else if (index == 1) {
         m_settings.m_fcPos = FCDProPlusSettings::FC_POS_SUPRA;
         sendSettings();
     } else if (index == 2) {
         m_settings.m_fcPos = FCDProPlusSettings::FC_POS_CENTER;
         sendSettings();
     }
 }
on_filterIF_currentIndexChanged
void FCDProPlusGui::on_filterIF_currentIndexChanged (int index) private slot
Definition at line 334 of file fcdproplusgui.cpp.
References FCDProPlusSettings::m_ifFilterIndex, m_settings, and sendSettings().
 {
     m_settings.m_ifFilterIndex = index;
     sendSettings();
 }
on_filterRF_currentIndexChanged
void FCDProPlusGui::on_filterRF_currentIndexChanged (int index) private slot
Definition at line 340 of file fcdproplusgui.cpp.
References FCDProPlusSettings::m_rfFilterIndex, m_settings, and sendSettings().
 {
     m_settings.m_rfFilterIndex = index;
     sendSettings();
 }
on_ifGain_valueChanged
void FCDProPlusGui::on_ifGain_valueChanged (int value) private slot
Definition at line 346 of file fcdproplusgui.cpp.
References displaySettings(), FCDProPlusSettings::m_ifGain, m_settings, and sendSettings().
 {
     m_settings.m_ifGain = value;
     displaySettings();
     sendSettings();
 }
on_iqImbalance_toggled
void FCDProPlusGui::on_iqImbalance_toggled (bool checked) private slot
Definition at line 273 of file fcdproplusgui.cpp.
References FCDProPlusSettings::m_iqImbalance, m_settings, and sendSettings().
 {
     m_settings.m_iqImbalance = checked;
     sendSettings();
 }
on_mixGain_stateChanged
void FCDProPlusGui::on_mixGain_stateChanged (int state) private slot
Definition at line 328 of file fcdproplusgui.cpp.
References FCDProPlusSettings::m_mixGain, m_settings, and sendSettings().
 {
     m_settings.m_mixGain = (state == Qt::Checked);
     sendSettings();
 }
on_ppm_valueChanged
void FCDProPlusGui::on_ppm_valueChanged (int value) private slot
Definition at line 353 of file fcdproplusgui.cpp.
References displaySettings(), FCDProPlusSettings::m_LOppmTenths, m_settings, and sendSettings().
 {
     m_settings.m_LOppmTenths = value;
     displaySettings();
     sendSettings();
 }
on_record_toggled
void FCDProPlusGui::on_record_toggled (bool checked) private slot
Definition at line 366 of file fcdproplusgui.cpp.
References FCDProPlusInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     FCDProPlusInput::MsgFileRecord* message = FCDProPlusInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_startStop_toggled
void FCDProPlusGui::on_startStop_toggled (bool checked) private slot
Definition at line 360 of file fcdproplusgui.cpp.
References FCDProPlusInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, and MessageQueue::push().
 {
     FCDProPlusInput::MsgStartStop *message = FCDProPlusInput::MsgStartStop::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_transverter_clicked
void FCDProPlusGui::on_transverter_clicked () private slot
Definition at line 378 of file fcdproplusgui.cpp.
References FCDProPlusSettings::m_centerFrequency, m_settings, FCDProPlusSettings::m_transverterDeltaFrequency, FCDProPlusSettings::m_transverterMode, sendSettings(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("FCDProPlusGui::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     m_settings.m_centerFrequency = ui->centerFrequency->getValueNew()*1000;
     sendSettings();
 }
openDeviceSettingsDialog
void FCDProPlusGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 388 of file fcdproplusgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), FCDProPlusSettings::m_reverseAPIAddress, FCDProPlusSettings::m_reverseAPIDeviceIndex, FCDProPlusSettings::m_reverseAPIPort, m_settings, FCDProPlusSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by FCDProPlusGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void FCDProPlusGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 96 of file fcdproplusgui.cpp.
References displaySettings(), m_settings, FCDProPlusSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void FCDProPlusGui::sendSettings () private
Definition at line 231 of file fcdproplusgui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_centerFrequency_changed(), on_checkBoxB_stateChanged(), on_checkBoxG_stateChanged(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_filterIF_currentIndexChanged(), on_filterRF_currentIndexChanged(), on_ifGain_valueChanged(), on_iqImbalance_toggled(), on_mixGain_stateChanged(), on_ppm_valueChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray FCDProPlusGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 115 of file fcdproplusgui.cpp.
References m_settings, and FCDProPlusSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void FCDProPlusGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 108 of file fcdproplusgui.cpp.
References displaySettings(), FCDProPlusSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void FCDProPlusGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 86 of file fcdproplusgui.cpp.
 {
     setObjectName(name);
 }
updateFrequencyLimits()
void FCDProPlusGui::updateFrequencyLimits () private
Definition at line 195 of file fcdproplusgui.cpp.
References m_settings, FCDProPlusSettings::m_transverterDeltaFrequency, FCDProPlusSettings::m_transverterMode, and ui.
Referenced by displaySettings(), FCDProPlusGui(), and on_transverter_clicked().
 {
     // values in kHz
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     qint64 minLimit = fcd_traits<ProPlus>::loLowLimitFreq/1000 + deltaFrequency;
     qint64 maxLimit = fcd_traits<ProPlus>::loHighLimitFreq/1000 + deltaFrequency;
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("FCDProPlusGui::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void FCDProPlusGui::updateHardware () private slot
Definition at line 279 of file fcdproplusgui.cpp.
References FCDProPlusInput::MsgConfigureFCDProPlus::create(), DeviceSampleSource::getInputMessageQueue(), m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by FCDProPlusGui().
 {
     FCDProPlusInput::MsgConfigureFCDProPlus* message = FCDProPlusInput::MsgConfigureFCDProPlus::create(m_settings, m_forceSettings);
     m_sampleSource->getInputMessageQueue()->push(message);
     m_forceSettings = false;
     m_updateTimer.stop();
 }
updateSampleRateAndFrequency()
void FCDProPlusGui::updateSampleRateAndFrequency () private
Definition at line 188 of file fcdproplusgui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg((float)m_sampleRate / 1000));
 }
updateStatus
void FCDProPlusGui::updateStatus () private slot
Definition at line 287 of file fcdproplusgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by FCDProPlusGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 FCDProPlusGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 66 of file fcdproplusgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* FCDProPlusGui::m_deviceUISet private
Definition at line 57 of file fcdproplusgui.h.
Referenced by FCDProPlusGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool FCDProPlusGui::m_doApplySettings private
Definition at line 58 of file fcdproplusgui.h.
m_forceSettings
bool FCDProPlusGui::m_forceSettings private
Definition at line 59 of file fcdproplusgui.h.
Referenced by deserialize(), and updateHardware().
m_gains
std::vector<int> FCDProPlusGui::m_gains private
Definition at line 63 of file fcdproplusgui.h.
m_inputMessageQueue
MessageQueue FCDProPlusGui::m_inputMessageQueue private
Definition at line 68 of file fcdproplusgui.h.
Referenced by FCDProPlusGui(), and handleInputMessages().
m_lastEngineState
int FCDProPlusGui::m_lastEngineState private
Definition at line 67 of file fcdproplusgui.h.
Referenced by updateStatus().
m_sampleRate
int FCDProPlusGui::m_sampleRate private
Definition at line 65 of file fcdproplusgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleSource
DeviceSampleSource* FCDProPlusGui::m_sampleSource private
Definition at line 64 of file fcdproplusgui.h.
Referenced by FCDProPlusGui(), on_record_toggled(), on_startStop_toggled(), and updateHardware().
m_settings
FCDProPlusSettings FCDProPlusGui::m_settings private
Definition at line 60 of file fcdproplusgui.h.
Referenced by deserialize(), displaySettings(), getCenterFrequency(), handleMessage(), on_centerFrequency_changed(), on_checkBoxB_stateChanged(), on_checkBoxG_stateChanged(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_filterIF_currentIndexChanged(), on_filterRF_currentIndexChanged(), on_ifGain_valueChanged(), on_iqImbalance_toggled(), on_mixGain_stateChanged(), on_ppm_valueChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), updateFrequencyLimits(), and updateHardware().
m_statusTimer
QTimer FCDProPlusGui::m_statusTimer private
Definition at line 62 of file fcdproplusgui.h.
Referenced by FCDProPlusGui().
m_updateTimer
QTimer FCDProPlusGui::m_updateTimer private
Definition at line 61 of file fcdproplusgui.h.
Referenced by FCDProPlusGui(), sendSettings(), and updateHardware().
ui
Ui::FCDProPlusGui* FCDProPlusGui::ui private
Definition at line 55 of file fcdproplusgui.h.
Referenced by displaySettings(), FCDProPlusGui(), handleMessage(), on_record_toggled(), on_transverter_clicked(), updateFrequencyLimits(), updateSampleRateAndFrequency(), updateStatus(), and ~FCDProPlusGui().
The documentation for this class was generated from the following files:
plugins/samplesource/fcdproplus/fcdproplusgui.h
plugins/samplesource/fcdproplus/fcdproplusgui.cpp