SDRAngel: FreeDVMod::MsgConfigureFreeDVMod Class Reference
FreeDVMod::MsgConfigureFreeDVMod Class Reference
#include <freedvmod.h>
Public Member Functions
const FreeDVModSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureFreeDVMod * create (const FreeDVModSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureFreeDVMod (const FreeDVModSettings &settings, bool force)
Private Attributes
FreeDVModSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 55 of file freedvmod.h.
Constructor & Destructor Documentation
MsgConfigureFreeDVMod()
FreeDVMod::MsgConfigureFreeDVMod::MsgConfigureFreeDVMod (const FreeDVModSettings & settings, bool force) inline private
Definition at line 71 of file freedvmod.h.
Referenced by create().
                                                                              :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureFreeDVMod* FreeDVMod::MsgConfigureFreeDVMod::create (const FreeDVModSettings & settings, bool force) inline static
Definition at line 62 of file freedvmod.h.
References MsgConfigureFreeDVMod().
Referenced by FreeDVModGUI::applySettings(), FreeDVMod::deserialize(), and FreeDVMod::webapiSettingsPutPatch().
         {
             return new MsgConfigureFreeDVMod(settings, force);
         }
getForce()
bool FreeDVMod::MsgConfigureFreeDVMod::getForce () const inline
Definition at line 60 of file freedvmod.h.
References m_force.
Referenced by FreeDVMod::handleMessage().
 { return m_force; }
getSettings()
const FreeDVModSettings& FreeDVMod::MsgConfigureFreeDVMod::getSettings () const inline
Definition at line 59 of file freedvmod.h.
References m_settings.
Referenced by FreeDVModGUI::handleMessage(), and FreeDVMod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool FreeDVMod::MsgConfigureFreeDVMod::m_force private
Definition at line 69 of file freedvmod.h.
Referenced by getForce().
m_settings
FreeDVModSettings FreeDVMod::MsgConfigureFreeDVMod::m_settings private
Definition at line 68 of file freedvmod.h.
Referenced by FreeDVMod::getCenterFrequency(), getSettings(), FreeDVMod::getStreamCenterFrequency(), and FreeDVMod::getTitle().
The documentation for this class was generated from the following file:
plugins/channeltx/modfreedv/freedvmod.h