SDRAngel: leansdr::gf2x_p< Te, Tp, P, N, ALPHA > Struct Template Reference
leansdr::gf2x_p< Te, Tp, P, N, ALPHA > Struct Template Reference
#include <rs.h>
Public Member Functions
gf2x_p ()
Te add (Te x, Te y)
Te sub (Te x, Te y)
Te mul (Te x, Te y)
Te div (Te x, Te y)
Te inv (Te x)
Te exp (Te x)
Te log (Te x)
Static Public Attributes
static const Te alpha = ALPHA
Private Attributes
Te lut_exp [(1<< N) *2]
Te lut_log [1<< N]
Detailed Description
template<typename Te, typename Tp, Tp P, int N, Te ALPHA>
struct leansdr::gf2x_p< Te, Tp, P, N, ALPHA >
Definition at line 48 of file rs.h.
Constructor & Destructor Documentation
gf2x_p()
template<typename Te, typename Tp, Tp P, int N, Te ALPHA> leansdr::gf2x_p< Te, Tp, P, N, ALPHA >::gf2x_p () inline
Definition at line 50 of file rs.h.
     {
         if (ALPHA != 2)
             fail("alpha!=2 not implemented");
         // Precompute log and exp tables.
         Tp alpha_i = 1;
         for (Tp i = 0; i < (1 << N); ++i)
         {
             lut_exp[i] = alpha_i;
             lut_exp[((1 << N) - 1) + i] = alpha_i;
             lut_log[alpha_i] = i;
             alpha_i <<= 1; // Multiply by alpha=[X] i.e. increase degrees
             if (alpha_i & (1 << N))
                 alpha_i ^= P; // Modulo P iteratively
         }
     }
Member Function Documentation
add()
template<typename Te, typename Tp, Tp P, int N, Te ALPHA> Te leansdr::gf2x_p< Te, Tp, P, N, ALPHA >::add (Te x, Te y) inline
Definition at line 67 of file rs.h.
Referenced by leansdr::rs_engine::eval_poly(), and leansdr::rs_engine::eval_poly_rev().
 { return x ^ y; } // Addition modulo 2
div()
template<typename Te, typename Tp, Tp P, int N, Te ALPHA> Te leansdr::gf2x_p< Te, Tp, P, N, ALPHA >::div (Te x, Te y) inline
Definition at line 75 of file rs.h.
Referenced by leansdr::rs_engine::correct(), and leansdr::rs_engine::encode().
     {
         //if ( ! y ) fail("div"); // TODO
         if (!x)
             return 0;
         return lut_exp[lut_log[x] + ((1 << N) - 1) - lut_log[y]];
     }
exp()
template<typename Te, typename Tp, Tp P, int N, Te ALPHA> Te leansdr::gf2x_p< Te, Tp, P, N, ALPHA >::exp (Te x) inline
Definition at line 87 of file rs.h.
Referenced by leansdr::rs_engine::correct(), leansdr::rs_engine::rs_engine(), and leansdr::rs_engine::syndromes().
 { return lut_exp[x]; }
inv()
template<typename Te, typename Tp, Tp P, int N, Te ALPHA> Te leansdr::gf2x_p< Te, Tp, P, N, ALPHA >::inv (Te x) inline
Definition at line 82 of file rs.h.
Referenced by leansdr::rs_engine::correct().
     {
         //    if ( ! x ) fail("inv");
         return lut_exp[((1 << N) - 1) - lut_log[x]];
     }
log()
template<typename Te, typename Tp, Tp P, int N, Te ALPHA> Te leansdr::gf2x_p< Te, Tp, P, N, ALPHA >::log (Te x) inline
Definition at line 88 of file rs.h.
 { return lut_log[x]; }
mul()
template<typename Te, typename Tp, Tp P, int N, Te ALPHA> Te leansdr::gf2x_p< Te, Tp, P, N, ALPHA >::mul (Te x, Te y) inline
Definition at line 69 of file rs.h.
Referenced by leansdr::rs_engine::correct(), leansdr::rs_engine::encode(), leansdr::rs_engine::eval_poly(), leansdr::rs_engine::eval_poly_rev(), and leansdr::rs_engine::rs_engine().
     {
         if (!x || !y)
             return 0;
         return lut_exp[lut_log[x] + lut_log[y]];
     }
sub()
template<typename Te, typename Tp, Tp P, int N, Te ALPHA> Te leansdr::gf2x_p< Te, Tp, P, N, ALPHA >::sub (Te x, Te y) inline
Definition at line 68 of file rs.h.
Referenced by leansdr::rs_engine::encode(), and leansdr::rs_engine::rs_engine().
 { return x ^ y; } // Subtraction modulo 2
Member Data Documentation
alpha
template<typename Te, typename Tp, Tp P, int N, Te ALPHA> const Te leansdr::gf2x_p< Te, Tp, P, N, ALPHA >::alpha = ALPHA static
Definition at line 66 of file rs.h.
lut_exp
template<typename Te, typename Tp, Tp P, int N, Te ALPHA> Te leansdr::gf2x_p< Te, Tp, P, N, ALPHA >::lut_exp[(1<< N) *2] private
Definition at line 91 of file rs.h.
Referenced by leansdr::gf2x_p< unsigned char, unsigned short, 0x11d, 8, 2 >::div(), leansdr::gf2x_p< unsigned char, unsigned short, 0x11d, 8, 2 >::exp(), leansdr::gf2x_p< unsigned char, unsigned short, 0x11d, 8, 2 >::gf2x_p(), leansdr::gf2x_p< unsigned char, unsigned short, 0x11d, 8, 2 >::inv(), and leansdr::gf2x_p< unsigned char, unsigned short, 0x11d, 8, 2 >::mul().
lut_log
template<typename Te, typename Tp, Tp P, int N, Te ALPHA> Te leansdr::gf2x_p< Te, Tp, P, N, ALPHA >::lut_log[1<< N] private
Definition at line 92 of file rs.h.
Referenced by leansdr::gf2x_p< unsigned char, unsigned short, 0x11d, 8, 2 >::div(), leansdr::gf2x_p< unsigned char, unsigned short, 0x11d, 8, 2 >::gf2x_p(), leansdr::gf2x_p< unsigned char, unsigned short, 0x11d, 8, 2 >::inv(), leansdr::gf2x_p< unsigned char, unsigned short, 0x11d, 8, 2 >::log(), and leansdr::gf2x_p< unsigned char, unsigned short, 0x11d, 8, 2 >::mul().
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/rs.h