SDRAngel: SWGSDRangel::SWGSoapySDRGainSetting Class Reference
SWGSDRangel::SWGSoapySDRGainSetting Class Reference
#include <SWGSoapySDRGainSetting.h>
Public Member Functions
SWGSoapySDRGainSetting ()
SWGSoapySDRGainSetting (QString *json)
virtual ~SWGSoapySDRGainSetting ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGSoapySDRGainSetting * fromJson (QString &jsonString) override
QString * getName ()
void setName (QString *name)
SWGRangeFloat * getRange ()
void setRange (SWGRangeFloat *range)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * name
bool m_name_isSet
SWGRangeFloat * range
bool m_range_isSet
Detailed Description
Definition at line 33 of file SWGSoapySDRGainSetting.h.
Constructor & Destructor Documentation
SWGSoapySDRGainSetting() [1/2]
SWGSDRangel::SWGSoapySDRGainSetting::SWGSoapySDRGainSetting ()
Definition at line 30 of file SWGSoapySDRGainSetting.cpp.
References m_name_isSet, m_range_isSet, name, and range.
{
     name = nullptr;
     m_name_isSet = false;
     range = nullptr;
     m_range_isSet = false;
 }
SWGSoapySDRGainSetting() [2/2]
SWGSDRangel::SWGSoapySDRGainSetting::SWGSoapySDRGainSetting (QString * json)
Definition at line 25 of file SWGSoapySDRGainSetting.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGSoapySDRGainSetting()
SWGSDRangel::SWGSoapySDRGainSetting::~SWGSoapySDRGainSetting () virtual
Definition at line 37 of file SWGSoapySDRGainSetting.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGSoapySDRGainSetting::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 77 of file SWGSoapySDRGainSetting.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGSoapySDRGainSetting::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 88 of file SWGSoapySDRGainSetting.cpp.
References SWGSDRangel::SWGRangeFloat::isSet(), name, range, and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(name != nullptr && *name != QString("")){
         toJsonValue(QString("name"), name, obj, QString("QString"));
     }
     if((range != nullptr) && (range->isSet())){
         toJsonValue(QString("range"), range, obj, QString("SWGRangeFloat"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGSoapySDRGainSetting::cleanup ()
Definition at line 50 of file SWGSoapySDRGainSetting.cpp.
References name, and range.
Referenced by ~SWGSoapySDRGainSetting().
{
     if(name != nullptr) {
         delete name;
     }
     if(range != nullptr) {
         delete range;
     }
 }
fromJson()
SWGSoapySDRGainSetting * SWGSDRangel::SWGSoapySDRGainSetting::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 60 of file SWGSoapySDRGainSetting.cpp.
References fromJsonObject().
Referenced by SWGSoapySDRGainSetting().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGSoapySDRGainSetting::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 69 of file SWGSoapySDRGainSetting.cpp.
References name, range, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&name, pJson["name"], "QString", "QString");
     ::SWGSDRangel::setValue(&range, pJson["range"], "SWGRangeFloat", "SWGRangeFloat");
 }
getName()
QString * SWGSDRangel::SWGSoapySDRGainSetting::getName ()
Definition at line 101 of file SWGSoapySDRGainSetting.cpp.
References name.
{
     return name;
 }
getRange()
SWGRangeFloat * SWGSDRangel::SWGSoapySDRGainSetting::getRange ()
Definition at line 111 of file SWGSoapySDRGainSetting.cpp.
References range.
{
     return range;
 }
init()
void SWGSDRangel::SWGSoapySDRGainSetting::init ()
Definition at line 42 of file SWGSoapySDRGainSetting.cpp.
References m_name_isSet, m_range_isSet, name, and range.
Referenced by SWGSoapySDRGainSetting().
{
     name = new QString("");
     m_name_isSet = false;
     range = new SWGRangeFloat();
     m_range_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGSoapySDRGainSetting::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 122 of file SWGSoapySDRGainSetting.cpp.
References SWGSDRangel::SWGRangeFloat::isSet(), name, and range.
{
     bool isObjectUpdated = false;
     do{
         if(name != nullptr && *name != QString("")){ isObjectUpdated = true; break;}
         if(range != nullptr && range->isSet()){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setName()
void SWGSDRangel::SWGSoapySDRGainSetting::setName (QString * name)
Definition at line 105 of file SWGSoapySDRGainSetting.cpp.
References m_name_isSet, and name.
{
     this->name = name;
     this->m_name_isSet = true;
 }
setRange()
void SWGSDRangel::SWGSoapySDRGainSetting::setRange (SWGRangeFloat * range)
Definition at line 115 of file SWGSoapySDRGainSetting.cpp.
References m_range_isSet, and range.
{
     this->range = range;
     this->m_range_isSet = true;
 }
Member Data Documentation
m_name_isSet
bool SWGSDRangel::SWGSoapySDRGainSetting::m_name_isSet private
Definition at line 57 of file SWGSoapySDRGainSetting.h.
Referenced by init(), setName(), and SWGSoapySDRGainSetting().
m_range_isSet
bool SWGSDRangel::SWGSoapySDRGainSetting::m_range_isSet private
Definition at line 60 of file SWGSoapySDRGainSetting.h.
Referenced by init(), setRange(), and SWGSoapySDRGainSetting().
name
QString* SWGSDRangel::SWGSoapySDRGainSetting::name private
Definition at line 56 of file SWGSoapySDRGainSetting.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getName(), init(), isSet(), setName(), and SWGSoapySDRGainSetting().
range
SWGRangeFloat* SWGSDRangel::SWGSoapySDRGainSetting::range private
Definition at line 59 of file SWGSoapySDRGainSetting.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getRange(), init(), isSet(), setRange(), and SWGSoapySDRGainSetting().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGSoapySDRGainSetting.h
swagger/sdrangel/code/qt5/client/SWGSoapySDRGainSetting.cpp