SDRAngel: WFMMod::MsgConfigureChannelizer Class Reference
WFMMod::MsgConfigureChannelizer Class Reference
#include <wfmmod.h>
Public Member Functions
int getSampleRate () const
int getCenterFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (int sampleRate, int centerFrequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (int sampleRate, int centerFrequency)
Private Attributes
int m_sampleRate
int m_centerFrequency
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 75 of file wfmmod.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
WFMMod::MsgConfigureChannelizer::MsgConfigureChannelizer (int sampleRate, int centerFrequency) inline private
Definition at line 91 of file wfmmod.h.
                                                                      :
             Message(),
             m_sampleRate(sampleRate),
             m_centerFrequency(centerFrequency)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* WFMMod::MsgConfigureChannelizer::create (int sampleRate, int centerFrequency) inline static
Definition at line 82 of file wfmmod.h.
Referenced by WFMModGUI::applySettings(), and WFMMod::webapiSettingsPutPatch().
         {
             return new MsgConfigureChannelizer(sampleRate, centerFrequency);
         }
getCenterFrequency()
int WFMMod::MsgConfigureChannelizer::getCenterFrequency () const inline
Definition at line 80 of file wfmmod.h.
Referenced by WFMMod::handleMessage().
 { return m_centerFrequency; }
getSampleRate()
int WFMMod::MsgConfigureChannelizer::getSampleRate () const inline
Definition at line 79 of file wfmmod.h.
References WFMMod::m_sampleRate.
Referenced by WFMMod::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_centerFrequency
int WFMMod::MsgConfigureChannelizer::m_centerFrequency private
Definition at line 89 of file wfmmod.h.
m_sampleRate
int WFMMod::MsgConfigureChannelizer::m_sampleRate private
Definition at line 88 of file wfmmod.h.
The documentation for this class was generated from the following file:
plugins/channeltx/modwfm/wfmmod.h