SDRAngel: AirspyPlugin Class Reference
AirspyPlugin Class Reference
#include <airspyplugin.h>
Public Member Functions
AirspyPlugin (QObject *parent=NULL)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "Airspy"
static const QString m_deviceTypeID = AIRSPY_DEVICE_TYPE_ID
static const int m_maxDevices = 32
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 28 of file airspyplugin.h.
Constructor & Destructor Documentation
AirspyPlugin()
AirspyPlugin::AirspyPlugin (QObject * parent = NULL) explicit
Definition at line 45 of file airspyplugin.cpp.
                                           :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSourcePluginInstance()
DeviceSampleSource * AirspyPlugin::createSampleSourcePluginInstance (const QString & sourceId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 161 of file airspyplugin.cpp.
References m_deviceTypeID.
 {
     if (sourceId == m_deviceTypeID)
     {
         AirspyInput* input = new AirspyInput(deviceAPI);
         return input;
     }
     else
     {
         return 0;
     }
 }
createSampleSourcePluginInstanceGUI()
PluginInstanceGUI * AirspyPlugin::createSampleSourcePluginInstanceGUI (const QString & sourceId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 143 of file airspyplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSources().
 {
     if (sourceId == m_deviceTypeID)
     {
         AirspyGui* gui = new AirspyGui(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSources()
PluginInterface::SamplingDevices AirspyPlugin::enumSampleSources () virtual
Reimplemented from PluginInterface.
Definition at line 60 of file airspyplugin.cpp.
References arg(), createSampleSourcePluginInstanceGUI(), i, m_deviceTypeID, m_hardwareID, m_maxDevices, PluginInterface::SamplingDevice::PhysicalDevice, and PluginInterface::SamplingDevice::StreamSingleRx.
 {
     SamplingDevices result;
     airspy_read_partid_serialno_t read_partid_serialno;
     struct airspy_device *devinfo;
     uint32_t serial_msb = 0;
     uint32_t serial_lsb = 0;
     airspy_error rc;
     int i;
     rc = (airspy_error) airspy_init();
     if (rc != AIRSPY_SUCCESS)
     {
         qCritical("AirspyPlugin::enumSampleSources: failed to initiate Airspy library: %s", airspy_error_name(rc));
     }
     for (i=0; i < m_maxDevices; i++)
     {
         rc = (airspy_error) airspy_open(&devinfo);
         if (rc == AIRSPY_SUCCESS)
         {
             qDebug("AirspyPlugin::enumSampleSources: try to enumerate Airspy device #%d", i);
             rc = (airspy_error) airspy_board_partid_serialno_read(devinfo, &read_partid_serialno);
             if (rc != AIRSPY_SUCCESS)
             {
                 qDebug("AirspyPlugin::enumSampleSources: failed to read serial no: %s", airspy_error_name(rc));
                 airspy_close(devinfo);
                 continue; // next
             }
             if ((read_partid_serialno.serial_no[2] != serial_msb) && (read_partid_serialno.serial_no[3] != serial_lsb))
             {
                 serial_msb = read_partid_serialno.serial_no[2];
                 serial_lsb = read_partid_serialno.serial_no[3];
                 QString serial_str = QString::number(serial_msb, 16) + QString::number(serial_lsb, 16);
                 //uint64_t serial_num = (((uint64_t) serial_msb)<<32) + serial_lsb;
                 QString displayedName(QString("Airspy[%1] %2").arg(i).arg(serial_str));
                 result.append(SamplingDevice(displayedName,
                         m_hardwareID,
                         m_deviceTypeID,
                         serial_str,
                         i,
                         PluginInterface::SamplingDevice::PhysicalDevice,
                         PluginInterface::SamplingDevice::StreamSingleRx,
                         1,
                         0));
                 qDebug("AirspyPlugin::enumSampleSources: enumerated Airspy device #%d", i);
             }
             airspy_close(devinfo);
         }
         else
         {
             qDebug("AirspyPlugin::enumSampleSources: enumerated %d Airspy devices %s", i, airspy_error_name(rc));
             break; // finished
         }
     }
     rc = (airspy_error) airspy_exit();
     qDebug("AirspyPlugin::enumSampleSources: airspy_exit: %s", airspy_error_name(rc));
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & AirspyPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 50 of file airspyplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void AirspyPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 55 of file airspyplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSource().
 {
     pluginAPI->registerSampleSource(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString AirspyPlugin::m_deviceTypeID = AIRSPY_DEVICE_TYPE_ID static
Definition at line 47 of file airspyplugin.h.
Referenced by createSampleSourcePluginInstance(), createSampleSourcePluginInstanceGUI(), enumSampleSources(), and initPlugin().
m_hardwareID
const QString AirspyPlugin::m_hardwareID = "Airspy" static
Definition at line 46 of file airspyplugin.h.
Referenced by enumSampleSources().
m_maxDevices
const int AirspyPlugin::m_maxDevices = 32 static
Definition at line 48 of file airspyplugin.h.
Referenced by enumSampleSources(), and AirspyInput::open_airspy_from_sequence().
m_pluginDescriptor
const PluginDescriptor AirspyPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("Airspy Input"),
    QString("4.5.2"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 51 of file airspyplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesource/airspy/airspyplugin.h
plugins/samplesource/airspy/airspyplugin.cpp