SDRAngel: SWGSDRangel::SWGRemoteOutputReport Class Reference
SWGSDRangel::SWGRemoteOutputReport Class Reference
#include <SWGRemoteOutputReport.h>
Public Member Functions
SWGRemoteOutputReport ()
SWGRemoteOutputReport (QString *json)
virtual ~SWGRemoteOutputReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGRemoteOutputReport * fromJson (QString &jsonString) override
float getBufferRwBalance ()
void setBufferRwBalance (float buffer_rw_balance)
qint32 getSampleCount ()
void setSampleCount (qint32 sample_count)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
float buffer_rw_balance
bool m_buffer_rw_balance_isSet
qint32 sample_count
bool m_sample_count_isSet
Detailed Description
Definition at line 31 of file SWGRemoteOutputReport.h.
Constructor & Destructor Documentation
SWGRemoteOutputReport() [1/2]
SWGSDRangel::SWGRemoteOutputReport::SWGRemoteOutputReport ()
Definition at line 30 of file SWGRemoteOutputReport.cpp.
References buffer_rw_balance, m_buffer_rw_balance_isSet, m_sample_count_isSet, and sample_count.
{
     buffer_rw_balance = 0.0f;
     m_buffer_rw_balance_isSet = false;
     sample_count = 0;
     m_sample_count_isSet = false;
 }
SWGRemoteOutputReport() [2/2]
SWGSDRangel::SWGRemoteOutputReport::SWGRemoteOutputReport (QString * json)
Definition at line 25 of file SWGRemoteOutputReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGRemoteOutputReport()
SWGSDRangel::SWGRemoteOutputReport::~SWGRemoteOutputReport () virtual
Definition at line 37 of file SWGRemoteOutputReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGRemoteOutputReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 73 of file SWGRemoteOutputReport.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGRemoteOutputReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 84 of file SWGRemoteOutputReport.cpp.
References buffer_rw_balance, m_buffer_rw_balance_isSet, m_sample_count_isSet, and sample_count.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_buffer_rw_balance_isSet){
         obj->insert("bufferRWBalance", QJsonValue(buffer_rw_balance));
     }
     if(m_sample_count_isSet){
         obj->insert("sampleCount", QJsonValue(sample_count));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGRemoteOutputReport::cleanup ()
Definition at line 50 of file SWGRemoteOutputReport.cpp.
Referenced by ~SWGRemoteOutputReport().
{
 }
fromJson()
SWGRemoteOutputReport * SWGSDRangel::SWGRemoteOutputReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 56 of file SWGRemoteOutputReport.cpp.
References fromJsonObject().
Referenced by SWGRemoteOutputReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGRemoteOutputReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 65 of file SWGRemoteOutputReport.cpp.
References buffer_rw_balance, sample_count, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&buffer_rw_balance, pJson["bufferRWBalance"], "float", "");
     ::SWGSDRangel::setValue(&sample_count, pJson["sampleCount"], "qint32", "");
 }
getBufferRwBalance()
float SWGSDRangel::SWGRemoteOutputReport::getBufferRwBalance ()
Definition at line 97 of file SWGRemoteOutputReport.cpp.
References buffer_rw_balance.
{
     return buffer_rw_balance;
 }
getSampleCount()
qint32 SWGSDRangel::SWGRemoteOutputReport::getSampleCount ()
Definition at line 107 of file SWGRemoteOutputReport.cpp.
References sample_count.
{
     return sample_count;
 }
init()
void SWGSDRangel::SWGRemoteOutputReport::init ()
Definition at line 42 of file SWGRemoteOutputReport.cpp.
References buffer_rw_balance, m_buffer_rw_balance_isSet, m_sample_count_isSet, and sample_count.
Referenced by SWGRemoteOutputReport(), and RemoteOutput::webapiReportGet().
{
     buffer_rw_balance = 0.0f;
     m_buffer_rw_balance_isSet = false;
     sample_count = 0;
     m_sample_count_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGRemoteOutputReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 118 of file SWGRemoteOutputReport.cpp.
References m_buffer_rw_balance_isSet, and m_sample_count_isSet.
Referenced by SWGSDRangel::SWGDeviceReport::asJsonObject(), and SWGSDRangel::SWGDeviceReport::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(m_buffer_rw_balance_isSet){ isObjectUpdated = true; break;}
         if(m_sample_count_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setBufferRwBalance()
void SWGSDRangel::SWGRemoteOutputReport::setBufferRwBalance (float buffer_rw_balance)
Definition at line 101 of file SWGRemoteOutputReport.cpp.
References buffer_rw_balance, and m_buffer_rw_balance_isSet.
Referenced by RemoteOutput::webapiFormatDeviceReport().
{
     this->buffer_rw_balance = buffer_rw_balance;
     this->m_buffer_rw_balance_isSet = true;
 }
setSampleCount()
void SWGSDRangel::SWGRemoteOutputReport::setSampleCount (qint32 sample_count)
Definition at line 111 of file SWGRemoteOutputReport.cpp.
References m_sample_count_isSet, and sample_count.
Referenced by RemoteOutput::webapiFormatDeviceReport().
{
     this->sample_count = sample_count;
     this->m_sample_count_isSet = true;
 }
Member Data Documentation
buffer_rw_balance
float SWGSDRangel::SWGRemoteOutputReport::buffer_rw_balance private
Definition at line 54 of file SWGRemoteOutputReport.h.
Referenced by asJsonObject(), fromJsonObject(), getBufferRwBalance(), init(), setBufferRwBalance(), and SWGRemoteOutputReport().
m_buffer_rw_balance_isSet
bool SWGSDRangel::SWGRemoteOutputReport::m_buffer_rw_balance_isSet private
Definition at line 55 of file SWGRemoteOutputReport.h.
Referenced by asJsonObject(), init(), isSet(), setBufferRwBalance(), and SWGRemoteOutputReport().
m_sample_count_isSet
bool SWGSDRangel::SWGRemoteOutputReport::m_sample_count_isSet private
Definition at line 58 of file SWGRemoteOutputReport.h.
Referenced by asJsonObject(), init(), isSet(), setSampleCount(), and SWGRemoteOutputReport().
sample_count
qint32 SWGSDRangel::SWGRemoteOutputReport::sample_count private
Definition at line 57 of file SWGRemoteOutputReport.h.
Referenced by asJsonObject(), fromJsonObject(), getSampleCount(), init(), setSampleCount(), and SWGRemoteOutputReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGRemoteOutputReport.h
swagger/sdrangel/code/qt5/client/SWGRemoteOutputReport.cpp