SDRAngel: UDPSocket Class Reference
UDPSocket Class Reference
#include <UDPSocket.h>
Public Member Functions
UDPSocket ()
UDPSocket (unsigned short localPort)
UDPSocket (const string &localAddress, unsigned short localPort)
void DisconnectFromHost ()
void SendDataGram (const void *buffer, int bufferLen, const string &foreignAddress, unsigned short foreignPort)
int RecvDataGram (void *buffer, int bufferLen, string &sourceAddress, unsigned short &sourcePort)
void SetMulticastTTL (unsigned char multicastTTL)
void JoinGroup (const string &multicastGroup)
void LeaveGroup (const string &multicastGroup)
Public Member Functions inherited from CSocket
virtual ~CSocket ()
string GetLocalAddress ()
unsigned short GetLocalPort ()
void BindLocalPort (unsigned short localPort)
void BindLocalAddressAndPort (const string &localAddress, unsigned short localPort=0)
unsigned long int GetReadBufferSize ()
void SetReadBufferSize (unsigned int nSize)
void SetNonBlocking (bool bBlocking)
void ConnectToHost (const string &foreignAddress, unsigned short foreignPort)
void Send (const void *buffer, int bufferLen)
int Recv (void *buffer, int bufferLen)
string GetPeerAddress ()
unsigned short GetPeerPort ()
CSocket & operator<< (const string &sStr)
CSocket & operator>> (string &sStr)
virtual int OnDataRead (unsigned long timeToWait=ULONG_MAX)
void SetBindToDevice (const string &sInterface)
Private Member Functions
void SetBroadcast ()
Additional Inherited Members
Public Types inherited from CSocket
enum SocketType { TcpSocket = SOCK_STREAM, UdpSocket = SOCK_DGRAM, UnknownSocketType =-1 }
enum NetworkLayerProtocol { IPv4Protocol = AF_INET, IPv6Protocol = AF_INET6, UnknownNetworkLayerProtocol = -1 }
enum ReadResult { DATA_ARRIVED = 0, DATA_TIMED_OUT = ETIMEDOUT, DATA_EXCEPTION = 255 }
Protected Member Functions inherited from CSocket
CSocket (SocketType type, NetworkLayerProtocol protocol)
CSocket (int sockDesc)
Static Protected Member Functions inherited from CSocket
static void FillAddr (const string &localAddress, unsigned short localPort, sockaddr_in &localAddr)
Protected Attributes inherited from CSocket
int m_sockDesc
Detailed Description
UDP Socket class.
Definition at line 251 of file UDPSocket.h.
Constructor & Destructor Documentation
UDPSocket() [1/3]
UDPSocket::UDPSocket ()
Construct a UDP socket
Exceptions
SocketException thrown if unable to create UDP socket
Definition at line 299 of file UDPSocket.cpp.
References SetBroadcast().
                     :CSocket(UdpSocket,IPv4Protocol)
 {
     SetBroadcast();
 }
UDPSocket() [2/3]
UDPSocket::UDPSocket (unsigned short localPort)
Construct a UDP socket with the given local port
Parameters
localPort local port
Exceptions
SocketException thrown if unable to create UDP socket
Definition at line 304 of file UDPSocket.cpp.
References CSocket::BindLocalPort(), and SetBroadcast().
                                               :
 CSocket(UdpSocket,IPv4Protocol)
 {
     BindLocalPort(localPort);
     SetBroadcast();
 }
UDPSocket() [3/3]
UDPSocket::UDPSocket (const string & localAddress, unsigned short localPort)
Construct a UDP socket with the given local port and address
Parameters
localAddress local address
localPort local port
Exceptions
SocketException thrown if unable to create UDP socket
Definition at line 311 of file UDPSocket.cpp.
References CSocket::BindLocalAddressAndPort(), and SetBroadcast().
                                                                           :
 CSocket(UdpSocket,IPv4Protocol)
 {
     BindLocalAddressAndPort(localAddress, localPort);
     SetBroadcast();
 }
Member Function Documentation
DisconnectFromHost()
void UDPSocket::DisconnectFromHost ()
Unset foreign address and port
Returns
true if disassociation is successful
Exceptions
SocketException thrown if unable to disconnect UDP socket Unset foreign address and port
Returns
true if disassociation is successful
Exceptions
SocketException thrown if unable to disconnect UDP socket
Definition at line 318 of file UDPSocket.cpp.
References CSocket::m_sockDesc.
 {
     sockaddr_in nullAddr;
     memset(&nullAddr, 0, sizeof(nullAddr));
     nullAddr.sin_family = AF_UNSPEC;
     // Try to disconnect
     if (::connect(m_sockDesc, (sockaddr *) &nullAddr, sizeof(nullAddr)) < 0)
     {
         if (errno != EAFNOSUPPORT)
         {
             throw CSocketException("Disconnect failed (connect())", true);
         }
     }
 }
JoinGroup()
void UDPSocket::JoinGroup (const string & multicastGroup)
Join the specified multicast group
Parameters
multicastGroup multicast group address to join
Exceptions
SocketException thrown if unable to join group
Definition at line 371 of file UDPSocket.cpp.
References CSocket::m_sockDesc.
 {
     struct ip_mreq multicastRequest;
     multicastRequest.imr_multiaddr.s_addr = inet_addr(multicastGroup.c_str());
     multicastRequest.imr_interface.s_addr = htonl(INADDR_ANY);
     if (setsockopt(m_sockDesc, IPPROTO_IP, IP_ADD_MEMBERSHIP,
         (void *) &multicastRequest,
         sizeof(multicastRequest)) < 0)
     {
         throw CSocketException("Multicast group join failed (setsockopt())", true);
     }
 }
LeaveGroup()
void UDPSocket::LeaveGroup (const string & multicastGroup)
Leave the specified multicast group
Parameters
multicastGroup multicast group address to leave
Exceptions
SocketException thrown if unable to leave group
Definition at line 386 of file UDPSocket.cpp.
References CSocket::m_sockDesc.
 {
     struct ip_mreq multicastRequest;
     multicastRequest.imr_multiaddr.s_addr = inet_addr(multicastGroup.c_str());
     multicastRequest.imr_interface.s_addr = htonl(INADDR_ANY);
     if (setsockopt(m_sockDesc, IPPROTO_IP, IP_DROP_MEMBERSHIP,
         (void *) &multicastRequest,
         sizeof(multicastRequest)) < 0)
     {
         throw CSocketException("Multicast group leave failed (setsockopt())", true);
     }
 }
RecvDataGram()
int UDPSocket::RecvDataGram (void * buffer, int bufferLen, string & sourceAddress, unsigned short & sourcePort)
Read read up to bufferLen bytes data from this socket. The given buffer is where the data will be placed
Parameters
buffer buffer to receive data
bufferLen maximum number of bytes to receive
sourceAddress address of datagram source
sourcePort port of data source
Returns
number of bytes received and -1 for error
Exceptions
SocketException thrown if unable to receive datagram
Definition at line 346 of file UDPSocket.cpp.
References CSocket::m_sockDesc.
 {
     sockaddr_in clntAddr;
     socklen_t addrLen = sizeof(clntAddr);
     int nBytes;
     if ((nBytes = recvfrom(m_sockDesc, (void *) buffer, bufferLen, 0, (sockaddr *) &clntAddr,
         (socklen_t *) &addrLen)) < 0)
     {
         throw CSocketException("Receive failed (recvfrom())", true);
     }
     sourceAddress = inet_ntoa(clntAddr.sin_addr);
     sourcePort    = ntohs(clntAddr.sin_port);
     char* sData = static_cast<char *>(buffer);
     sData[nBytes] = '\0';
     return nBytes;
 }
SendDataGram()
void UDPSocket::SendDataGram (const void * buffer, int bufferLen, const string & foreignAddress, unsigned short foreignPort)
Send the given buffer as a UDP datagram to the specified address/port
Parameters
buffer buffer to be written
bufferLen number of bytes to write
foreignAddress address (IP address or name) to send to
foreignPort port number to send to
Returns
true if send is successful
Exceptions
SocketException thrown if unable to send datagram
Definition at line 333 of file UDPSocket.cpp.
References CSocket::FillAddr(), and CSocket::m_sockDesc.
 {
     sockaddr_in destAddr;
     FillAddr(foreignAddress, foreignPort, destAddr);
     // Write out the whole buffer as a single message.
     if (sendto(m_sockDesc, (void *) buffer, bufferLen, 0,(sockaddr *) &destAddr, sizeof(destAddr)) != bufferLen)
     {
         throw CSocketException("Send failed (sendto())", true);
     }
 }
SetBroadcast()
void UDPSocket::SetBroadcast () private
Definition at line 401 of file UDPSocket.cpp.
References CSocket::m_sockDesc.
Referenced by UDPSocket().
 {
     // If this fails, we'll hear about it when we try to send.  This will allow
     // system that cannot broadcast to continue if they don't plan to broadcast
     int broadcastPermission = 1;
     setsockopt(m_sockDesc, SOL_SOCKET, SO_BROADCAST,
         (void *) &broadcastPermission, sizeof(broadcastPermission));
 }
SetMulticastTTL()
void UDPSocket::SetMulticastTTL (unsigned char multicastTTL)
Set the multicast TTL
Parameters
multicastTTL multicast TTL
Exceptions
SocketException thrown if unable to set TTL
Definition at line 363 of file UDPSocket.cpp.
References CSocket::m_sockDesc.
 {
     if (setsockopt(m_sockDesc, IPPROTO_IP, IP_MULTICAST_TTL, (void *) &multicastTTL, sizeof(multicastTTL)) < 0)
     {
         throw CSocketException("Multicast TTL set failed (setsockopt())", true);
     }
 }
The documentation for this class was generated from the following files:
plugins/samplesink/remoteoutput/UDPSocket.h
plugins/samplesink/remoteoutput/UDPSocket.cpp