SDRAngel: RemoteSinkGUI Class Reference
RemoteSinkGUI Class Reference
#include <remotesinkgui.h>
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static RemoteSinkGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
Private Slots
void handleSourceMessages ()
void on_decimationFactor_currentIndexChanged (int index)
void on_position_valueChanged (int value)
void on_dataAddress_returnPressed ()
void on_dataPort_returnPressed ()
void on_dataApplyButton_clicked (bool checked)
void on_nbFECBlocks_valueChanged (int value)
void on_txDelay_valueChanged (int value)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void tick ()
Private Member Functions
RemoteSinkGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *parent=0)
virtual ~RemoteSinkGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void applyChannelSettings ()
void displaySettings ()
void displayRateAndShift ()
void updateTxDelayTime ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
void applyDecimation ()
void applyPosition ()
Private Attributes
Ui::RemoteSinkGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
RemoteSinkSettings m_settings
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
double m_shiftFrequencyFactor
Channel frequency shift factor.
bool m_doApplySettings
RemoteSink * m_remoteSink
MessageQueue m_inputMessageQueue
QTime m_time
uint32_t m_tickCount
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 42 of file remotesinkgui.h.
Constructor & Destructor Documentation
RemoteSinkGUI()
RemoteSinkGUI::RemoteSinkGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * parent = 0) explicit private
Definition at line 109 of file remotesinkgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), displaySettings(), getInputMessageQueue(), handleSourceMessages(), RemoteSink::m_channelIdURI, m_channelMarker, m_deviceUISet, m_remoteSink, RemoteSinkSettings::m_rgbColor, m_settings, m_time, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), ChannelMarker::setCenterFrequency(), RemoteSinkSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSink::setMessageQueueToGUI(), ChannelMarker::setTitle(), ChannelMarker::setVisible(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                            :
         RollupWidget(parent),
         ui(new Ui::RemoteSinkGUI),
         m_pluginAPI(pluginAPI),
         m_deviceUISet(deviceUISet),
         m_sampleRate(0),
         m_tickCount(0)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_remoteSink = (RemoteSink*) channelrx;
     m_remoteSink->setMessageQueueToGUI(getInputMessageQueue());
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("Remote source");
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     m_settings.setChannelMarker(&m_channelMarker);
     m_deviceUISet->registerRxChannelInstance(RemoteSink::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     //connect(&(m_deviceUISet->m_deviceSourceAPI->getMasterTimer()), SIGNAL(timeout()), this, SLOT(tick()));
     m_time.start();
     displaySettings();
     applySettings(true);
 }
~RemoteSinkGUI()
RemoteSinkGUI::~RemoteSinkGUI () private virtual
Definition at line 147 of file remotesinkgui.cpp.
References m_deviceUISet, m_remoteSink, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_remoteSink; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete ui;
 }
Member Function Documentation
applyChannelSettings()
void RemoteSinkGUI::applyChannelSettings () private
Definition at line 170 of file remotesinkgui.cpp.
References RemoteSink::MsgConfigureChannelizer::create(), BasebandSampleSink::getInputMessageQueue(), m_doApplySettings, RemoteSinkSettings::m_filterChainHash, RemoteSinkSettings::m_log2Decim, m_remoteSink, m_settings, and MessageQueue::push().
Referenced by applyPosition().
 {
     if (m_doApplySettings)
     {
         RemoteSink::MsgConfigureChannelizer *msgChan = RemoteSink::MsgConfigureChannelizer::create(
                 m_settings.m_log2Decim,
                 m_settings.m_filterChainHash);
         m_remoteSink->getInputMessageQueue()->push(msgChan);
     }
 }
applyDecimation()
void RemoteSinkGUI::applyDecimation () private
Definition at line 359 of file remotesinkgui.cpp.
References applyPosition(), i, RemoteSinkSettings::m_filterChainHash, RemoteSinkSettings::m_log2Decim, m_settings, and ui.
Referenced by displaySettings(), and on_decimationFactor_currentIndexChanged().
 {
     uint32_t maxHash = 1;
     for (uint32_t i = 0; i < m_settings.m_log2Decim; i++) {
         maxHash *= 3;
     }
     ui->position->setMaximum(maxHash-1);
     ui->position->setValue(m_settings.m_filterChainHash);
     m_settings.m_filterChainHash = ui->position->value();
     applyPosition();
 }
applyPosition()
void RemoteSinkGUI::applyPosition () private
Definition at line 373 of file remotesinkgui.cpp.
References applyChannelSettings(), arg(), HBFilterChainConverter::convertToString(), displayRateAndShift(), RemoteSinkSettings::m_filterChainHash, RemoteSinkSettings::m_log2Decim, m_settings, m_shiftFrequencyFactor, and ui.
Referenced by applyDecimation(), and on_position_valueChanged().
 {
     ui->filterChainIndex->setText(tr("%1").arg(m_settings.m_filterChainHash));
     QString s;
     m_shiftFrequencyFactor = HBFilterChainConverter::convertToString(m_settings.m_log2Decim, m_settings.m_filterChainHash, s);
     ui->filterChainText->setText(s);
     displayRateAndShift();
     applyChannelSettings();
 }
applySettings()
void RemoteSinkGUI::applySettings (bool force = false) private
Definition at line 159 of file remotesinkgui.cpp.
References RemoteSink::MsgConfigureRemoteSink::create(), ChannelMarker::getColor(), BasebandSampleSink::getInputMessageQueue(), m_channelMarker, m_doApplySettings, m_remoteSink, m_settings, MessageQueue::push(), and RollupWidget::setTitleColor().
Referenced by deserialize(), on_dataAddress_returnPressed(), on_dataApplyButton_clicked(), on_dataPort_returnPressed(), on_nbFECBlocks_valueChanged(), on_txDelay_valueChanged(), onMenuDialogCalled(), RemoteSinkGUI(), and resetToDefaults().
 {
     if (m_doApplySettings)
     {
         setTitleColor(m_channelMarker.getColor());
         RemoteSink::MsgConfigureRemoteSink* message = RemoteSink::MsgConfigureRemoteSink::create(m_settings, force);
         m_remoteSink->getInputMessageQueue()->push(message);
     }
 }
blockApplySettings()
void RemoteSinkGUI::blockApplySettings (bool block) private
Definition at line 154 of file remotesinkgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
create()
RemoteSinkGUI * RemoteSinkGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) static
Definition at line 29 of file remotesinkgui.cpp.
References RemoteSinkGUI().
Referenced by RemoteSinkPlugin::createRxChannelGUI().
 {
     RemoteSinkGUI* gui = new RemoteSinkGUI(pluginAPI, deviceUISet, channelRx);
     return gui;
 }
deserialize()
bool RemoteSinkGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 71 of file remotesinkgui.cpp.
References applySettings(), RemoteSinkSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void RemoteSinkGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 35 of file remotesinkgui.cpp.
 {
     delete this;
 }
displayRateAndShift()
void RemoteSinkGUI::displayRateAndShift () private
Definition at line 208 of file remotesinkgui.cpp.
References arg(), m_channelMarker, RemoteSinkSettings::m_log2Decim, m_sampleRate, m_settings, m_shiftFrequencyFactor, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), and ui.
Referenced by applyPosition(), and handleMessage().
 {
     int shift = m_shiftFrequencyFactor * m_sampleRate;
     double channelSampleRate = ((double) m_sampleRate) / (1<<m_settings.m_log2Decim);
     QLocale loc;
     ui->offsetFrequencyText->setText(tr("%1 Hz").arg(loc.toString(shift)));
     ui->channelRateText->setText(tr("%1k").arg(QString::number(channelSampleRate / 1000.0, 'g', 5)));
     m_channelMarker.setCenterFrequency(shift);
     m_channelMarker.setBandwidth(channelSampleRate);
 }
displaySettings()
void RemoteSinkGUI::displaySettings () private
Definition at line 181 of file remotesinkgui.cpp.
References applyDecimation(), arg(), blockApplySettings(), ChannelMarker::getTitle(), m_channelMarker, RemoteSinkSettings::m_dataAddress, RemoteSinkSettings::m_dataPort, RemoteSinkSettings::m_log2Decim, RemoteSinkSettings::m_nbFECBlocks, RemoteSinkSettings::m_rgbColor, m_sampleRate, m_settings, RemoteSinkSettings::m_title, RemoteSinkSettings::m_txDelay, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setMovable(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ui, and updateTxDelayTime().
Referenced by deserialize(), handleMessage(), RemoteSinkGUI(), and resetToDefaults().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.setBandwidth(m_sampleRate); // TODO
     m_channelMarker.setMovable(false); // do not let user move the center arbitrarily
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->decimationFactor->setCurrentIndex(m_settings.m_log2Decim);
     ui->dataAddress->setText(m_settings.m_dataAddress);
     ui->dataPort->setText(tr("%1").arg(m_settings.m_dataPort));
     QString s = QString::number(128 + m_settings.m_nbFECBlocks, 'f', 0);
     QString s1 = QString::number(m_settings.m_nbFECBlocks, 'f', 0);
     ui->nominalNbBlocksText->setText(tr("%1/%2").arg(s).arg(s1));
     ui->txDelayText->setText(tr("%1%").arg(m_settings.m_txDelay));
     ui->txDelay->setValue(m_settings.m_txDelay);
     updateTxDelayTime();
     applyDecimation();
     blockApplySettings(false);
 }
enterEvent()
void RemoteSinkGUI::enterEvent (QEvent *) private
Definition at line 224 of file remotesinkgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 RemoteSinkGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 50 of file remotesinkgui.cpp.
{
     return 0;
 }
getInputMessageQueue()
virtual MessageQueue* RemoteSinkGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 56 of file remotesinkgui.h.
Referenced by handleSourceMessages(), and RemoteSinkGUI().
 { return &m_inputMessageQueue; }
getName()
QString RemoteSinkGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 45 of file remotesinkgui.cpp.
 {
     return objectName();
 }
handleMessage()
bool RemoteSinkGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 83 of file remotesinkgui.cpp.
References blockApplySettings(), displayRateAndShift(), displaySettings(), RemoteSink::MsgSampleRateNotification::getSampleRate(), RemoteSink::MsgConfigureRemoteSink::getSettings(), m_sampleRate, m_settings, Message::match(), and updateTxDelayTime().
Referenced by handleSourceMessages().
 {
     if (RemoteSink::MsgSampleRateNotification::match(message))
     {
         RemoteSink::MsgSampleRateNotification& notif = (RemoteSink::MsgSampleRateNotification&) message;
         //m_channelMarker.setBandwidth(notif.getSampleRate());
         m_sampleRate = notif.getSampleRate();
         updateTxDelayTime();
         displayRateAndShift();
         return true;
     }
     else if (RemoteSink::MsgConfigureRemoteSink::match(message))
     {
         const RemoteSink::MsgConfigureRemoteSink& cfg = (RemoteSink::MsgConfigureRemoteSink&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void RemoteSinkGUI::handleSourceMessages () private slot
Definition at line 229 of file remotesinkgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by RemoteSinkGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void RemoteSinkGUI::leaveEvent (QEvent *) private
Definition at line 219 of file remotesinkgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_dataAddress_returnPressed
void RemoteSinkGUI::on_dataAddress_returnPressed () private slot
Definition at line 291 of file remotesinkgui.cpp.
References applySettings(), RemoteSinkSettings::m_dataAddress, m_settings, and ui.
 {
     m_settings.m_dataAddress = ui->dataAddress->text();
     applySettings();
 }
on_dataApplyButton_clicked
void RemoteSinkGUI::on_dataApplyButton_clicked (bool checked) private slot
Definition at line 314 of file remotesinkgui.cpp.
References applySettings(), RemoteSinkSettings::m_dataAddress, RemoteSinkSettings::m_dataPort, m_settings, and ui.
 {
     (void) checked;
     m_settings.m_dataAddress = ui->dataAddress->text();
     bool dataOk;
     int udpDataPort = ui->dataPort->text().toInt(&dataOk);
     if((dataOk) && (udpDataPort >= 1024) && (udpDataPort < 65535))
     {
         m_settings.m_dataPort = udpDataPort;
     }
     applySettings();
 }
on_dataPort_returnPressed
void RemoteSinkGUI::on_dataPort_returnPressed () private slot
Definition at line 297 of file remotesinkgui.cpp.
References applySettings(), RemoteSinkSettings::m_dataPort, m_settings, and ui.
 {
     bool dataOk;
     int dataPort = ui->dataPort->text().toInt(&dataOk);
     if((!dataOk) || (dataPort < 1024) || (dataPort > 65535))
     {
         return;
     }
     else
     {
         m_settings.m_dataPort = dataPort;
     }
     applySettings();
 }
on_decimationFactor_currentIndexChanged
void RemoteSinkGUI::on_decimationFactor_currentIndexChanged (int index) private slot
Definition at line 279 of file remotesinkgui.cpp.
References applyDecimation(), RemoteSinkSettings::m_log2Decim, and m_settings.
 {
     m_settings.m_log2Decim = index;
     applyDecimation();
 }
on_nbFECBlocks_valueChanged
void RemoteSinkGUI::on_nbFECBlocks_valueChanged (int value) private slot
Definition at line 338 of file remotesinkgui.cpp.
References applySettings(), arg(), RemoteSinkSettings::m_nbFECBlocks, m_settings, ui, and updateTxDelayTime().
 {
     m_settings.m_nbFECBlocks = value;
     int nbOriginalBlocks = 128;
     int nbFECBlocks = value;
     QString s = QString::number(nbOriginalBlocks + nbFECBlocks, 'f', 0);
     QString s1 = QString::number(nbFECBlocks, 'f', 0);
     ui->nominalNbBlocksText->setText(tr("%1/%2").arg(s).arg(s1));
     updateTxDelayTime();
     applySettings();
 }
on_position_valueChanged
void RemoteSinkGUI::on_position_valueChanged (int value) private slot
Definition at line 285 of file remotesinkgui.cpp.
References applyPosition(), RemoteSinkSettings::m_filterChainHash, and m_settings.
 {
     m_settings.m_filterChainHash = value;
     applyPosition();
 }
on_txDelay_valueChanged
void RemoteSinkGUI::on_txDelay_valueChanged (int value) private slot
Definition at line 330 of file remotesinkgui.cpp.
References applySettings(), arg(), m_settings, RemoteSinkSettings::m_txDelay, ui, and updateTxDelayTime().
 {
     m_settings.m_txDelay = value; // percentage
     ui->txDelayText->setText(tr("%1%").arg(value));
     updateTxDelayTime();
     applySettings();
 }
onMenuDialogCalled
void RemoteSinkGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 248 of file remotesinkgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, RemoteSinkSettings::m_reverseAPIAddress, RemoteSinkSettings::m_reverseAPIChannelIndex, RemoteSinkSettings::m_reverseAPIDeviceIndex, RemoteSinkSettings::m_reverseAPIPort, RemoteSinkSettings::m_rgbColor, m_settings, RemoteSinkSettings::m_title, RemoteSinkSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by RemoteSinkGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void RemoteSinkGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 242 of file remotesinkgui.cpp.
Referenced by RemoteSinkGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void RemoteSinkGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 59 of file remotesinkgui.cpp.
References applySettings(), displaySettings(), m_settings, and RemoteSinkSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
serialize()
QByteArray RemoteSinkGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 66 of file remotesinkgui.cpp.
References m_settings, and RemoteSinkSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void RemoteSinkGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 54 of file remotesinkgui.cpp.
 {
     (void) centerFrequency;
 }
setName()
void RemoteSinkGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 40 of file remotesinkgui.cpp.
 {
     setObjectName(name);
 }
tick
void RemoteSinkGUI::tick () private slot
Definition at line 384 of file remotesinkgui.cpp.
References m_tickCount.
 {
     if (++m_tickCount == 20) { // once per second
         m_tickCount = 0;
     }
 }
updateTxDelayTime()
void RemoteSinkGUI::updateTxDelayTime () private
Definition at line 350 of file remotesinkgui.cpp.
References m_settings, and RemoteSinkSettings::m_txDelay.
Referenced by displaySettings(), handleMessage(), on_nbFECBlocks_valueChanged(), and on_txDelay_valueChanged().
 {
     double txDelayRatio = m_settings.m_txDelay / 100.0;
     int samplesPerBlock = RemoteNbBytesPerBlock / sizeof(Sample);
     double delay = m_sampleRate == 0 ? 0.0 : (127*samplesPerBlock*txDelayRatio) / m_sampleRate;
     delay /= 128 + m_settings.m_nbFECBlocks;
     ui->txDelayTime->setText(tr("%1s").arg(QString::number(delay*1e6, 'f', 0)));
 }
Member Data Documentation
m_channelMarker
ChannelMarker RemoteSinkGUI::m_channelMarker private
Definition at line 63 of file remotesinkgui.h.
Referenced by applySettings(), displayRateAndShift(), displaySettings(), enterEvent(), leaveEvent(), onMenuDialogCalled(), and RemoteSinkGUI().
m_deviceCenterFrequency
quint64 RemoteSinkGUI::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 66 of file remotesinkgui.h.
m_deviceUISet
DeviceUISet* RemoteSinkGUI::m_deviceUISet private
Definition at line 62 of file remotesinkgui.h.
Referenced by RemoteSinkGUI(), and ~RemoteSinkGUI().
m_doApplySettings
bool RemoteSinkGUI::m_doApplySettings private
Definition at line 68 of file remotesinkgui.h.
Referenced by applyChannelSettings(), applySettings(), and blockApplySettings().
m_inputMessageQueue
MessageQueue RemoteSinkGUI::m_inputMessageQueue private
Definition at line 71 of file remotesinkgui.h.
m_pluginAPI
PluginAPI* RemoteSinkGUI::m_pluginAPI private
Definition at line 61 of file remotesinkgui.h.
m_remoteSink
RemoteSink* RemoteSinkGUI::m_remoteSink private
Definition at line 70 of file remotesinkgui.h.
Referenced by applyChannelSettings(), applySettings(), RemoteSinkGUI(), and ~RemoteSinkGUI().
m_sampleRate
int RemoteSinkGUI::m_sampleRate private
Definition at line 65 of file remotesinkgui.h.
Referenced by displayRateAndShift(), displaySettings(), and handleMessage().
m_settings
RemoteSinkSettings RemoteSinkGUI::m_settings private
Definition at line 64 of file remotesinkgui.h.
Referenced by applyChannelSettings(), applyDecimation(), applyPosition(), applySettings(), deserialize(), displayRateAndShift(), displaySettings(), handleMessage(), on_dataAddress_returnPressed(), on_dataApplyButton_clicked(), on_dataPort_returnPressed(), on_decimationFactor_currentIndexChanged(), on_nbFECBlocks_valueChanged(), on_position_valueChanged(), on_txDelay_valueChanged(), onMenuDialogCalled(), RemoteSinkGUI(), resetToDefaults(), serialize(), and updateTxDelayTime().
m_shiftFrequencyFactor
double RemoteSinkGUI::m_shiftFrequencyFactor private
Channel frequency shift factor.
Definition at line 67 of file remotesinkgui.h.
Referenced by applyPosition(), and displayRateAndShift().
m_tickCount
uint32_t RemoteSinkGUI::m_tickCount private
Definition at line 74 of file remotesinkgui.h.
Referenced by tick().
m_time
QTime RemoteSinkGUI::m_time private
Definition at line 73 of file remotesinkgui.h.
Referenced by RemoteSinkGUI().
ui
Ui::RemoteSinkGUI* RemoteSinkGUI::ui private
Definition at line 60 of file remotesinkgui.h.
Referenced by applyDecimation(), applyPosition(), displayRateAndShift(), displaySettings(), on_dataAddress_returnPressed(), on_dataApplyButton_clicked(), on_dataPort_returnPressed(), on_nbFECBlocks_valueChanged(), on_txDelay_valueChanged(), RemoteSinkGUI(), and ~RemoteSinkGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/remotesink/remotesinkgui.h
plugins/channelrx/remotesink/remotesinkgui.cpp