SDRAngel: FreeDVDemod::MsgConfigureFreeDVDemod Class Reference
FreeDVDemod::MsgConfigureFreeDVDemod Class Reference
#include <freedvdemod.h>
Public Member Functions
const FreeDVDemodSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureFreeDVDemod * create (const FreeDVDemodSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureFreeDVDemod (const FreeDVDemodSettings &settings, bool force)
Private Attributes
FreeDVDemodSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 53 of file freedvdemod.h.
Constructor & Destructor Documentation
MsgConfigureFreeDVDemod()
FreeDVDemod::MsgConfigureFreeDVDemod::MsgConfigureFreeDVDemod (const FreeDVDemodSettings & settings, bool force) inline private
Definition at line 69 of file freedvdemod.h.
Referenced by create().
                                                                                  :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureFreeDVDemod* FreeDVDemod::MsgConfigureFreeDVDemod::create (const FreeDVDemodSettings & settings, bool force) inline static
Definition at line 60 of file freedvdemod.h.
References MsgConfigureFreeDVDemod().
Referenced by FreeDVDemodGUI::applySettings(), FreeDVDemod::deserialize(), and FreeDVDemod::webapiSettingsPutPatch().
         {
             return new MsgConfigureFreeDVDemod(settings, force);
         }
getForce()
bool FreeDVDemod::MsgConfigureFreeDVDemod::getForce () const inline
Definition at line 58 of file freedvdemod.h.
References m_force.
Referenced by FreeDVDemod::handleMessage().
 { return m_force; }
getSettings()
const FreeDVDemodSettings& FreeDVDemod::MsgConfigureFreeDVDemod::getSettings () const inline
Definition at line 57 of file freedvdemod.h.
References m_settings.
Referenced by FreeDVDemodGUI::handleMessage(), and FreeDVDemod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool FreeDVDemod::MsgConfigureFreeDVDemod::m_force private
Definition at line 67 of file freedvdemod.h.
Referenced by getForce().
m_settings
FreeDVDemodSettings FreeDVDemod::MsgConfigureFreeDVDemod::m_settings private
Definition at line 66 of file freedvdemod.h.
Referenced by FreeDVDemod::getCenterFrequency(), getSettings(), FreeDVDemod::getStreamCenterFrequency(), and FreeDVDemod::getTitle().
The documentation for this class was generated from the following file:
plugins/channelrx/demodfreedv/freedvdemod.h