SDRAngel: ATVDemodGUI Class Reference
ATVDemodGUI Class Reference
#include <atvdemodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
void channelMarkerHighlightedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &strName)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 intCenterFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &arrData)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &objMessage)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static ATVDemodGUI * create (PluginAPI *objPluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
Private Slots
void handleSourceMessages ()
void onWidgetRolled (QWidget *widget, bool rollDown)
void tick ()
void on_synchLevel_valueChanged (int value)
void on_blackLevel_valueChanged (int value)
void on_lineTime_valueChanged (int value)
void on_topTime_valueChanged (int value)
void on_hSync_clicked ()
void on_vSync_clicked ()
void on_invertVideo_clicked ()
void on_halfImage_clicked ()
void on_modulation_currentIndexChanged (int index)
void on_nbLines_currentIndexChanged (int index)
void on_fps_currentIndexChanged (int index)
void on_standard_currentIndexChanged (int index)
void on_reset_clicked (bool checked)
void on_rfBW_valueChanged (int value)
void on_rfOppBW_valueChanged (int value)
void on_rfFiltering_toggled (bool checked)
void on_decimatorEnable_toggled (bool checked)
void on_deltaFrequency_changed (qint64 value)
void on_bfo_valueChanged (int value)
void on_fmDeviation_valueChanged (int value)
void on_screenTabWidget_currentChanged (int index)
Private Member Functions
ATVDemodGUI (PluginAPI *objPluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *objParent=0)
virtual ~ATVDemodGUI ()
void blockApplySettings (bool blnBlock)
void applySettings ()
void applyRFSettings ()
void setChannelMarkerBandwidth ()
void setRFFiltersSlidersRange (int sampleRate)
void lineTimeUpdate ()
void topTimeUpdate ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Static Private Member Functions
static float getFps (int fpsIndex)
static float getNominalLineTime (int nbLinesIndex, int fpsIndex)
static int getNumberOfLines (int nbLinesIndex)
Private Attributes
Ui::ATVDemodGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
ATVDemod * m_atvDemod
bool m_blnDoApplySettings
MovingAverageUtil< double, double, 4 > m_objMagSqAverage
int m_intTickCount
ScopeVis * m_scopeVis
float m_fltLineTimeMultiplier
float m_fltTopTimeMultiplier
int m_rfSliderDivisor
int m_inputSampleRate
MessageQueue m_inputMessageQueue
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 39 of file atvdemodgui.h.
Constructor & Destructor Documentation
ATVDemodGUI()
ATVDemodGUI::ATVDemodGUI (PluginAPI * objPluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * objParent = 0) explicit private
Definition at line 272 of file atvdemodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), arg(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), ChannelMarker::getColor(), getInputMessageQueue(), BasebandSampleSink::getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, handleSourceMessages(), ScopeVis::TraceData::m_amp, ScopeVis::TraceData::m_ampIndex, m_atvDemod, ATVDemod::m_channelIdURI, m_channelMarker, m_deviceUISet, ScopeVis::TraceData::m_ofs, ScopeVis::TraceData::m_ofsCoarse, m_scopeVis, ScopeVis::TriggerData::m_triggerLevel, ScopeVis::TriggerData::m_triggerLevelCoarse, ScopeVis::TriggerData::m_triggerPositiveEdge, onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), resetToDefaults(), ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), BasebandSampleSink::setMessageQueueToGUI(), ATVDemod::setScopeSink(), RollupWidget::setTitleColor(), ATVDemod::setTVScreen(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                              :
         RollupWidget(objParent),
         ui(new Ui::ATVDemodGUI),
         m_pluginAPI(objPluginAPI),
         m_deviceUISet(deviceUISet),
         m_channelMarker(this),
         m_blnDoApplySettings(true),
         m_intTickCount(0),
         m_inputSampleRate(48000)
 {
     ui->setupUi(this);
     ui->screenTV->setColor(false);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     m_scopeVis = new ScopeVis(ui->glScope);
     m_atvDemod = (ATVDemod*) rxChannel; //new ATVDemod(m_deviceUISet->m_deviceSourceAPI);
     m_atvDemod->setMessageQueueToGUI(getInputMessageQueue());
     m_atvDemod->setScopeSink(m_scopeVis);
     m_atvDemod->setTVScreen(ui->screenTV);
     ui->glScope->connectTimer(MainWindow::getInstance()->getMasterTimer());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick())); // 50 ms
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(Qt::white);
     m_channelMarker.setBandwidth(6000000);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     setTitleColor(m_channelMarker.getColor());
     m_deviceUISet->registerRxChannelInstance(ATVDemod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     ui->scopeGUI->setBuddies(m_scopeVis->getInputMessageQueue(), m_scopeVis, ui->glScope);
     resetToDefaults(); // does applySettings()
     ui->scopeGUI->setPreTrigger(1);
     ScopeVis::TraceData traceData;
     traceData.m_amp = 2.0;      // amplification factor
     traceData.m_ampIndex = 1;   // this is second step
     traceData.m_ofs = 0.5;      // direct offset
     traceData.m_ofsCoarse = 50; // this is 50 coarse steps
     ui->scopeGUI->changeTrace(0, traceData);
     ui->scopeGUI->focusOnTrace(0); // re-focus to take changes into account in the GUI
     ScopeVis::TriggerData triggerData;
     triggerData.m_triggerLevel = 0.1;
     triggerData.m_triggerLevelCoarse = 10;
     triggerData.m_triggerPositiveEdge = false;
     ui->scopeGUI->changeTrigger(0, triggerData);
     ui->scopeGUI->focusOnTrigger(0); // re-focus to take changes into account in the GUI
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(&m_channelMarker, SIGNAL(highlightedByCursor()), this, SLOT(channelMarkerHighlightedByCursor()));
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     QChar delta = QChar(0x94, 0x03);
     ui->fmDeviationLabel->setText(delta);
 }
~ATVDemodGUI()
ATVDemodGUI::~ATVDemodGUI () private virtual
Definition at line 340 of file atvdemodgui.cpp.
References m_atvDemod, m_deviceUISet, m_scopeVis, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_atvDemod; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete m_scopeVis;
     delete ui;
 }
Member Function Documentation
applyRFSettings()
void ATVDemodGUI::applyRFSettings () private
Definition at line 381 of file atvdemodgui.cpp.
References ATVDemod::configureRF(), ChannelMarker::getCenterFrequency(), BasebandSampleSink::getInputMessageQueue(), m_atvDemod, m_blnDoApplySettings, m_channelMarker, m_rfSliderDivisor, and ui.
Referenced by channelMarkerChangedByCursor(), handleMessage(), on_bfo_valueChanged(), on_decimatorEnable_toggled(), on_deltaFrequency_changed(), on_fmDeviation_valueChanged(), on_modulation_currentIndexChanged(), on_rfBW_valueChanged(), on_rfFiltering_toggled(), and on_rfOppBW_valueChanged().
 {
     if (m_blnDoApplySettings)
     {
         m_atvDemod->configureRF(m_atvDemod->getInputMessageQueue(),
                 m_channelMarker.getCenterFrequency(),
                 (ATVDemod::ATVModulation) ui->modulation->currentIndex(),
                 ui->rfBW->value() * m_rfSliderDivisor * 1.0f,
                 ui->rfOppBW->value() * m_rfSliderDivisor * 1.0f,
                 ui->rfFiltering->isChecked(),
                 ui->decimatorEnable->isChecked(),
                 ui->bfo->value(),
                 ui->fmDeviation->value() / 500.0f);
     }
 }
applySettings()
void ATVDemodGUI::applySettings () private
Definition at line 353 of file atvdemodgui.cpp.
References ATVDemod::configure(), ATVDemod::MsgConfigureChannelizer::create(), ChannelMarker::getCenterFrequency(), getFps(), BasebandSampleSink::getInputMessageQueue(), getNominalLineTime(), getNumberOfLines(), ATVDemod::getSampleRate(), m_atvDemod, m_blnDoApplySettings, m_channelMarker, m_fltLineTimeMultiplier, m_fltTopTimeMultiplier, m_inputSampleRate, MessageQueue::push(), and ui.
Referenced by channelMarkerChangedByCursor(), deserialize(), handleMessage(), on_blackLevel_valueChanged(), on_fps_currentIndexChanged(), on_halfImage_clicked(), on_hSync_clicked(), on_invertVideo_clicked(), on_lineTime_valueChanged(), on_nbLines_currentIndexChanged(), on_screenTabWidget_currentChanged(), on_standard_currentIndexChanged(), on_synchLevel_valueChanged(), on_topTime_valueChanged(), on_vSync_clicked(), resetToDefaults(), and setCenterFrequency().
 {
     if (m_blnDoApplySettings)
     {
         ATVDemod::MsgConfigureChannelizer *msgChan = ATVDemod::MsgConfigureChannelizer::create(
                 m_channelMarker.getCenterFrequency());
         m_atvDemod->getInputMessageQueue()->push(msgChan);
         m_atvDemod->configure(m_atvDemod->getInputMessageQueue(),
                 getNominalLineTime(ui->nbLines->currentIndex(), ui->fps->currentIndex()) + ui->lineTime->value() * m_fltLineTimeMultiplier,
                 getNominalLineTime(ui->nbLines->currentIndex(), ui->fps->currentIndex()) * (4.7f / 64.0f) + ui->topTime->value() * m_fltTopTimeMultiplier,
                 getFps(ui->fps->currentIndex()),
                 (ATVDemod::ATVStd) ui->standard->currentIndex(),
                 getNumberOfLines(ui->nbLines->currentIndex()),
                 (ui->halfImage->checkState() == Qt::Checked) ? 0.5f : 1.0f,
                 ui->synchLevel->value() / 1000.0f,
                 ui->blackLevel->value() / 1000.0f,
                 ui->hSync->isChecked(),
                 ui->vSync->isChecked(),
                 ui->invertVideo->isChecked(),
                 ui->screenTabWidget->currentIndex());
         qDebug() << "ATVDemodGUI::applySettings:"
                 << " m_objChannelizer.inputSampleRate: " << m_inputSampleRate
                 << " m_objATVDemod.sampleRate: " << m_atvDemod->getSampleRate();
     }
 }
blockApplySettings()
void ATVDemodGUI::blockApplySettings (bool blnBlock) private
Definition at line 348 of file atvdemodgui.cpp.
References m_blnDoApplySettings.
Referenced by deserialize(), and resetToDefaults().
 {
     m_blnDoApplySettings = !blnBlock;
 }
channelMarkerChangedByCursor
void ATVDemodGUI::channelMarkerChangedByCursor () slot
Definition at line 239 of file atvdemodgui.cpp.
References applyRFSettings(), applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, and ui.
Referenced by ATVDemodGUI().
 {
     qDebug("ATVDemodGUI::channelMarkerChangedByCursor");
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     applySettings();
     applyRFSettings();
 }
channelMarkerHighlightedByCursor
void ATVDemodGUI::channelMarkerHighlightedByCursor () slot
Definition at line 248 of file atvdemodgui.cpp.
References ChannelMarker::getHighlighted(), m_channelMarker, and RollupWidget::setHighlighted().
Referenced by ATVDemodGUI().
 {
     setHighlighted(m_channelMarker.getHighlighted());
 }
create()
ATVDemodGUI * ATVDemodGUI::create (PluginAPI * objPluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) static
Definition at line 38 of file atvdemodgui.cpp.
References ATVDemodGUI().
Referenced by ATVDemodPlugin::createRxChannelGUI().
 {
     ATVDemodGUI* gui = new ATVDemodGUI(objPluginAPI, deviceUISet, rxChannel);
     return gui;
 }
deserialize()
bool ATVDemodGUI::deserialize (const QByteArray & arrData) virtual
Implements PluginInstanceGUI.
Definition at line 129 of file atvdemodgui.cpp.
References applySettings(), blockApplySettings(), ChannelMarker::emitChangedByAPI(), SimpleDeserializer::getVersion(), SimpleDeserializer::isValid(), lineTimeUpdate(), m_channelMarker, SimpleDeserializer::readBool(), SimpleDeserializer::readS32(), resetToDefaults(), ChannelMarker::setCenterFrequency(), topTimeUpdate(), and ui.
 {
     SimpleDeserializer d(arrData);
     if (!d.isValid())
     {
         resetToDefaults();
         return false;
     }
     if (d.getVersion() == 1)
     {
         QByteArray bytetmp;
         int tmp;
         bool booltmp;
         blockApplySettings(true);
         m_channelMarker.blockSignals(true);
         d.readS32(1, &tmp, 0);
         m_channelMarker.setCenterFrequency(tmp);
 //        if (d.readU32(2, &u32tmp)) {
 //            m_objChannelMarker.setColor(u32tmp);
 //        } else {
 //            m_objChannelMarker.setColor(Qt::white);
 //        }
         d.readS32(3, &tmp, 100);
         ui->synchLevel->setValue(tmp);
         d.readS32(4, &tmp, 310);
         ui->blackLevel->setValue(tmp);
         d.readS32(5, &tmp, 0);
         ui->lineTime->setValue(tmp);
         d.readS32(6, &tmp, 3);
         ui->topTime->setValue(tmp);
         d.readS32(7, &tmp, 0);
         ui->modulation->setCurrentIndex(tmp);
         d.readS32(8, &tmp, 0);
         ui->fps->setCurrentIndex(tmp);
         d.readBool(9, &booltmp, true);
         ui->hSync->setChecked(booltmp);
         d.readBool(10, &booltmp, true);
         ui->vSync->setChecked(booltmp);
         d.readBool(11, &booltmp, false);
         ui->halfImage->setChecked(booltmp);
         d.readS32(12, &tmp, 10);
         ui->rfBW->setValue(tmp);
         d.readS32(13, &tmp, 10);
         ui->rfOppBW->setValue(tmp);
         d.readS32(14, &tmp, 10);
         ui->bfo->setValue(tmp);
         d.readBool(15, &booltmp, true);
         ui->invertVideo->setChecked(booltmp);
         d.readS32(16, &tmp, 0);
         ui->nbLines->setCurrentIndex(tmp);
         d.readS32(17, &tmp, 250);
         ui->fmDeviation->setValue(tmp);
         d.readS32(18, &tmp, 1);
         ui->standard->setCurrentIndex(tmp);
         blockApplySettings(false);
         m_channelMarker.blockSignals(false);
         m_channelMarker.emitChangedByAPI();
         lineTimeUpdate();
         topTimeUpdate();
         applySettings();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void ATVDemodGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 46 of file atvdemodgui.cpp.
 {
     delete this;
 }
enterEvent()
void ATVDemodGUI::enterEvent (QEvent *) private
Definition at line 461 of file atvdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 ATVDemodGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 61 of file atvdemodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
 {
     return m_channelMarker.getCenterFrequency();
 }
getFps()
float ATVDemodGUI::getFps (int fpsIndex) static private
Definition at line 678 of file atvdemodgui.cpp.
Referenced by applySettings(), and getNominalLineTime().
 {
     switch(fpsIndex)
     {
     case 0:
         return 30.0f;
         break;
     case 2:
         return 20.0f;
         break;
     case 3:
         return 16.0f;
         break;
     case 4:
         return 12.0f;
         break;
     case 5:
         return 10.0f;
         break;
     case 6:
         return 8.0f;
         break;
     case 7:
         return 5.0f;
         break;
     case 8:
         return 2.0f;
         break;
     case 9:
         return 1.0f;
         break;
     case 1:
     default:
         return 25.0f;
         break;
     }
 }
getInputMessageQueue()
virtual MessageQueue* ATVDemodGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 55 of file atvdemodgui.h.
Referenced by ATVDemodGUI(), and handleSourceMessages().
 { return &m_inputMessageQueue; }
getName()
QString ATVDemodGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 56 of file atvdemodgui.cpp.
 {
     return objectName();
 }
getNominalLineTime()
float ATVDemodGUI::getNominalLineTime (int nbLinesIndex, int fpsIndex) static private
Definition at line 716 of file atvdemodgui.cpp.
References getFps(), and getNumberOfLines().
Referenced by applySettings(), lineTimeUpdate(), and topTimeUpdate().
 {
     float fps = getFps(fpsIndex);
     int   nbLines = getNumberOfLines(nbLinesIndex);
     return 1.0f / (nbLines * fps);
 }
getNumberOfLines()
int ATVDemodGUI::getNumberOfLines (int nbLinesIndex) static private
Definition at line 724 of file atvdemodgui.cpp.
Referenced by applySettings(), and getNominalLineTime().
 {
     switch(nbLinesIndex)
     {
     case 0:
         return 640;
         break;
     case 2:
         return 525;
         break;
     case 3:
         return 480;
         break;
     case 4:
         return 405;
         break;
     case 5:
         return 360;
         break;
     case 6:
         return 343;
         break;
     case 7:
         return 240;
         break;
     case 8:
         return 180;
         break;
     case 9:
         return 120;
         break;
     case 10:
         return 90;
         break;
     case 11:
         return 60;
         break;
     case 12:
         return 32;
         break;
     case 1:
     default:
         return 625;
         break;
     }
 }
handleMessage()
bool ATVDemodGUI::handleMessage (const Message & objMessage) virtual
Implements PluginInstanceGUI.
Definition at line 206 of file atvdemodgui.cpp.
References applyRFSettings(), applySettings(), arg(), ATVDemod::MsgReportChannelSampleRateChanged::getSampleRate(), lineTimeUpdate(), m_inputSampleRate, m_scopeVis, Message::match(), ScopeVis::setLiveRate(), setRFFiltersSlidersRange(), topTimeUpdate(), and ui.
Referenced by handleSourceMessages().
 {
     if (ATVDemod::MsgReportEffectiveSampleRate::match(objMessage))
     {
         int sampleRate = ((ATVDemod::MsgReportEffectiveSampleRate&)objMessage).getSampleRate();
         int nbPointsPerLine =  ((ATVDemod::MsgReportEffectiveSampleRate&)objMessage).getNbPointsPerLine();
         ui->channelSampleRateText->setText(tr("%1k").arg(sampleRate/1000.0f, 0, 'f', 2));
         ui->nbPointsPerLineText->setText(tr("%1p").arg(nbPointsPerLine));
         m_scopeVis->setLiveRate(sampleRate);
         setRFFiltersSlidersRange(sampleRate);
         lineTimeUpdate();
         topTimeUpdate();
         return true;
     }
     else if (ATVDemod::MsgReportChannelSampleRateChanged::match(objMessage))
     {
         ATVDemod::MsgReportChannelSampleRateChanged report = (ATVDemod::MsgReportChannelSampleRateChanged&) objMessage;
         m_inputSampleRate = report.getSampleRate();
         qDebug("ATVDemodGUI::handleMessage: MsgReportChannelSampleRateChanged: %d", m_inputSampleRate);
         applySettings();
         applyRFSettings();
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void ATVDemodGUI::handleSourceMessages () private slot
Definition at line 253 of file atvdemodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by ATVDemodGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void ATVDemodGUI::leaveEvent (QEvent *) private
Definition at line 456 of file atvdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
lineTimeUpdate()
void ATVDemodGUI::lineTimeUpdate () private
Definition at line 628 of file atvdemodgui.cpp.
References arg(), ATVDemod::getEffectiveSampleRate(), getNominalLineTime(), m_atvDemod, m_fltLineTimeMultiplier, and ui.
Referenced by deserialize(), handleMessage(), on_fps_currentIndexChanged(), on_lineTime_valueChanged(), on_nbLines_currentIndexChanged(), and resetToDefaults().
 {
     float nominalLineTime = getNominalLineTime(ui->nbLines->currentIndex(), ui->fps->currentIndex());
     int lineTimeScaleFactor = (int) std::log10(nominalLineTime);
     if (m_atvDemod->getEffectiveSampleRate() == 0) {
         m_fltLineTimeMultiplier = std::pow(10.0, lineTimeScaleFactor-3);
     } else {
         m_fltLineTimeMultiplier = 1.0f / m_atvDemod->getEffectiveSampleRate();
     }
     float lineTime = nominalLineTime + m_fltLineTimeMultiplier * ui->lineTime->value();
     if (lineTime < 0.0)
         ui->lineTimeText->setText("invalid");
     else if(lineTime < 0.000001)
         ui->lineTimeText->setText(tr("%1 ns").arg(lineTime * 1000000000.0, 0, 'f', 2));
     else if(lineTime < 0.001)
         ui->lineTimeText->setText(tr("%1 s").arg(lineTime * 1000000.0, 0, 'f', 2));
     else if(lineTime < 1.0)
         ui->lineTimeText->setText(tr("%1 ms").arg(lineTime * 1000.0, 0, 'f', 2));
     else
         ui->lineTimeText->setText(tr("%1 s").arg(lineTime * 1.0, 0, 'f', 2));
 }
on_bfo_valueChanged
void ATVDemodGUI::on_bfo_valueChanged (int value) private slot
Definition at line 610 of file atvdemodgui.cpp.
References applyRFSettings(), arg(), and ui.
 {
     ui->bfoText->setText(QString("%1").arg(value * 1.0, 0, 'f', 0));
     applyRFSettings();
 }
on_blackLevel_valueChanged
void ATVDemodGUI::on_blackLevel_valueChanged (int value) private slot
Definition at line 499 of file atvdemodgui.cpp.
References applySettings(), arg(), and ui.
 {
     applySettings();
     ui->blackLevelText->setText(QString("%1 mV").arg(value));
 }
on_decimatorEnable_toggled
void ATVDemodGUI::on_decimatorEnable_toggled (bool checked) private slot
Definition at line 597 of file atvdemodgui.cpp.
References applyRFSettings(), and setChannelMarkerBandwidth().
 {
     (void) checked;
     setChannelMarkerBandwidth();
     applyRFSettings();
 }
on_deltaFrequency_changed
void ATVDemodGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 604 of file atvdemodgui.cpp.
References applyRFSettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     applyRFSettings();
 }
on_fmDeviation_valueChanged
void ATVDemodGUI::on_fmDeviation_valueChanged (int value) private slot
Definition at line 616 of file atvdemodgui.cpp.
References applyRFSettings(), arg(), and ui.
 {
     ui->fmDeviationText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     applyRFSettings();
 }
on_fps_currentIndexChanged
void ATVDemodGUI::on_fps_currentIndexChanged (int index) private slot
Definition at line 547 of file atvdemodgui.cpp.
References applySettings(), lineTimeUpdate(), and topTimeUpdate().
 {
     (void) index;
     lineTimeUpdate();
     topTimeUpdate();
     applySettings();
 }
on_halfImage_clicked
void ATVDemodGUI::on_halfImage_clicked () private slot
Definition at line 534 of file atvdemodgui.cpp.
References applySettings().
 {
     applySettings();
 }
on_hSync_clicked
void ATVDemodGUI::on_hSync_clicked () private slot
Definition at line 519 of file atvdemodgui.cpp.
References applySettings().
 {
     applySettings();
 }
on_invertVideo_clicked
void ATVDemodGUI::on_invertVideo_clicked () private slot
Definition at line 529 of file atvdemodgui.cpp.
References applySettings().
 {
     applySettings();
 }
on_lineTime_valueChanged
void ATVDemodGUI::on_lineTime_valueChanged (int value) private slot
Definition at line 505 of file atvdemodgui.cpp.
References applySettings(), arg(), lineTimeUpdate(), and ui.
 {
     ui->lineTime->setToolTip(QString("Line length adjustment (%1)").arg(value));
     lineTimeUpdate();
     applySettings();
 }
on_modulation_currentIndexChanged
void ATVDemodGUI::on_modulation_currentIndexChanged (int index) private slot
Definition at line 567 of file atvdemodgui.cpp.
References applyRFSettings(), ATVDemod::getEffectiveSampleRate(), m_atvDemod, setChannelMarkerBandwidth(), and setRFFiltersSlidersRange().
 {
     (void) index;
     setRFFiltersSlidersRange(m_atvDemod->getEffectiveSampleRate());
     setChannelMarkerBandwidth();
     applyRFSettings();
 }
on_nbLines_currentIndexChanged
void ATVDemodGUI::on_nbLines_currentIndexChanged (int index) private slot
Definition at line 539 of file atvdemodgui.cpp.
References applySettings(), lineTimeUpdate(), and topTimeUpdate().
 {
     (void) index;
     lineTimeUpdate();
     topTimeUpdate();
     applySettings();
 }
on_reset_clicked
void ATVDemodGUI::on_reset_clicked (bool checked) private slot
Definition at line 561 of file atvdemodgui.cpp.
References resetToDefaults().
 {
     (void) checked;
     resetToDefaults();
 }
on_rfBW_valueChanged
void ATVDemodGUI::on_rfBW_valueChanged (int value) private slot
Definition at line 575 of file atvdemodgui.cpp.
References applyRFSettings(), arg(), m_rfSliderDivisor, setChannelMarkerBandwidth(), and ui.
 {
     ui->rfBWText->setText(QString("%1k").arg((value * m_rfSliderDivisor) / 1000.0, 0, 'f', 0));
     setChannelMarkerBandwidth();
     applyRFSettings();
 }
on_rfFiltering_toggled
void ATVDemodGUI::on_rfFiltering_toggled (bool checked) private slot
Definition at line 589 of file atvdemodgui.cpp.
References applyRFSettings(), ATVDemod::getEffectiveSampleRate(), m_atvDemod, setChannelMarkerBandwidth(), and setRFFiltersSlidersRange().
 {
     (void) checked;
     setRFFiltersSlidersRange(m_atvDemod->getEffectiveSampleRate());
     setChannelMarkerBandwidth();
     applyRFSettings();
 }
on_rfOppBW_valueChanged
void ATVDemodGUI::on_rfOppBW_valueChanged (int value) private slot
Definition at line 582 of file atvdemodgui.cpp.
References applyRFSettings(), arg(), m_rfSliderDivisor, setChannelMarkerBandwidth(), and ui.
 {
     ui->rfOppBWText->setText(QString("%1k").arg((value * m_rfSliderDivisor) / 1000.0, 0, 'f', 0));
     setChannelMarkerBandwidth();
     applyRFSettings();
 }
on_screenTabWidget_currentChanged
void ATVDemodGUI::on_screenTabWidget_currentChanged (int index) private slot
Definition at line 622 of file atvdemodgui.cpp.
References applySettings().
 {
     (void) index;
     applySettings();
 }
on_standard_currentIndexChanged
void ATVDemodGUI::on_standard_currentIndexChanged (int index) private slot
Definition at line 555 of file atvdemodgui.cpp.
References applySettings().
 {
     (void) index;
     applySettings();
 }
on_synchLevel_valueChanged
void ATVDemodGUI::on_synchLevel_valueChanged (int value) private slot
Definition at line 493 of file atvdemodgui.cpp.
References applySettings(), arg(), and ui.
 {
     applySettings();
     ui->synchLevelText->setText(QString("%1 mV").arg(value));
 }
on_topTime_valueChanged
void ATVDemodGUI::on_topTime_valueChanged (int value) private slot
Definition at line 512 of file atvdemodgui.cpp.
References applySettings(), arg(), topTimeUpdate(), and ui.
 {
     ui->topTime->setToolTip(QString("Horizontal sync pulse length adjustment (%1)").arg(value));
     topTimeUpdate();
     applySettings();
 }
on_vSync_clicked
void ATVDemodGUI::on_vSync_clicked () private slot
Definition at line 524 of file atvdemodgui.cpp.
References applySettings().
 {
     applySettings();
 }
onWidgetRolled
void ATVDemodGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 266 of file atvdemodgui.cpp.
Referenced by ATVDemodGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void ATVDemodGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 72 of file atvdemodgui.cpp.
References applySettings(), blockApplySettings(), lineTimeUpdate(), topTimeUpdate(), and ui.
Referenced by ATVDemodGUI(), deserialize(), and on_reset_clicked().
 {
     blockApplySettings(true);
     //********** ATV Default values **********
     ui->synchLevel->setValue(100);
     ui->blackLevel->setValue(310);
     ui->lineTime->setValue(0);
     ui->topTime->setValue(3);
     ui->modulation->setCurrentIndex(0);
     ui->fps->setCurrentIndex(0);
     ui->hSync->setChecked(true);
     ui->vSync->setChecked(true);
     ui->halfImage->setChecked(false);
     ui->invertVideo->setChecked(false);
     ui->standard->setCurrentIndex(1);
     //********** RF Default values **********
     ui->decimatorEnable->setChecked(false);
     ui->rfFiltering->setChecked(false);
     ui->rfBW->setValue(10);
     ui->rfOppBW->setValue(10);
     ui->bfo->setValue(0);
     ui->fmDeviation->setValue(250);
     blockApplySettings(false);
     lineTimeUpdate();
     topTimeUpdate();
     applySettings();
 }
serialize()
QByteArray ATVDemodGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 103 of file atvdemodgui.cpp.
References SimpleSerializer::final(), ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), m_channelMarker, ui, SimpleSerializer::writeBool(), SimpleSerializer::writeS32(), and SimpleSerializer::writeU32().
 {
     SimpleSerializer s(1);
     s.writeS32(1, m_channelMarker.getCenterFrequency());
     s.writeU32(2, m_channelMarker.getColor().rgb());
     s.writeS32(3, ui->synchLevel->value());
     s.writeS32(4, ui->blackLevel->value());
     s.writeS32(5, ui->lineTime->value());
     s.writeS32(6, ui->topTime->value());
     s.writeS32(7, ui->modulation->currentIndex());
     s.writeS32(8, ui->fps->currentIndex());
     s.writeBool(9, ui->hSync->isChecked());
     s.writeBool(10, ui->vSync->isChecked());
     s.writeBool(11, ui->halfImage->isChecked());
     s.writeS32(12, ui->rfBW->value());
     s.writeS32(13, ui->rfOppBW->value());
     s.writeS32(14, ui->bfo->value());
     s.writeBool(15, ui->invertVideo->isChecked());
     s.writeS32(16, ui->nbLines->currentIndex());
     s.writeS32(17, ui->fmDeviation->value());
     s.writeS32(18, ui->standard->currentIndex());
     return s.final();
 }
setCenterFrequency()
void ATVDemodGUI::setCenterFrequency (qint64 intCenterFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 66 of file atvdemodgui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(intCenterFrequency);
     applySettings();
 }
setChannelMarkerBandwidth()
void ATVDemodGUI::setChannelMarkerBandwidth () private
Definition at line 397 of file atvdemodgui.cpp.
References ATVDemod::ATV_LSB, ATVDemod::ATV_USB, ChannelMarker::dsb, ChannelMarker::emitChangedByAPI(), m_blnDoApplySettings, m_channelMarker, m_inputSampleRate, m_rfSliderDivisor, ChannelMarker::setBandwidth(), ChannelMarker::setOppositeBandwidth(), ChannelMarker::setSidebands(), ui, ChannelMarker::vlsb, and ChannelMarker::vusb.
Referenced by on_decimatorEnable_toggled(), on_modulation_currentIndexChanged(), on_rfBW_valueChanged(), on_rfFiltering_toggled(), and on_rfOppBW_valueChanged().
 {
     m_blnDoApplySettings = false; // avoid infinite recursion
     m_channelMarker.blockSignals(true);
     if (ui->rfFiltering->isChecked()) // FFT filter
     {
         m_channelMarker.setBandwidth(ui->rfBW->value()*m_rfSliderDivisor);
         m_channelMarker.setOppositeBandwidth(ui->rfOppBW->value()*m_rfSliderDivisor);
         if (ui->modulation->currentIndex() == (int) ATVDemod::ATV_LSB) {
             m_channelMarker.setSidebands(ChannelMarker::vlsb);
         } else if (ui->modulation->currentIndex() == (int) ATVDemod::ATV_USB) {
             m_channelMarker.setSidebands(ChannelMarker::vusb);
         } else {
             m_channelMarker.setSidebands(ChannelMarker::vusb);
         }
     }
     else
     {
         if (ui->decimatorEnable->isChecked()) {
             m_channelMarker.setBandwidth(ui->rfBW->value()*m_rfSliderDivisor);
         } else {
             m_channelMarker.setBandwidth(m_inputSampleRate);
         }
         m_channelMarker.setSidebands(ChannelMarker::dsb);
     }
     m_channelMarker.blockSignals(false);
     m_channelMarker.emitChangedByAPI();
     m_blnDoApplySettings = true;
 }
setName()
void ATVDemodGUI::setName (const QString & strName) virtual
Implements PluginInstanceGUI.
Definition at line 51 of file atvdemodgui.cpp.
 {
     setObjectName(strName);
 }
setRFFiltersSlidersRange()
void ATVDemodGUI::setRFFiltersSlidersRange (int sampleRate) private
Definition at line 431 of file atvdemodgui.cpp.
References arg(), m_rfSliderDivisor, and ui.
Referenced by handleMessage(), on_modulation_currentIndexChanged(), and on_rfFiltering_toggled().
 {
     // RF filters sliders range
     int scaleFactor = (int) std::log10(sampleRate/2);
     m_rfSliderDivisor = std::pow(10.0, scaleFactor-1);
     if (sampleRate/m_rfSliderDivisor < 50) {
         m_rfSliderDivisor /= 10;
     }
     if (ui->rfFiltering->isChecked())
     {
         ui->rfBW->setMaximum((sampleRate) / (2*m_rfSliderDivisor));
         ui->rfOppBW->setMaximum((sampleRate) / (2*m_rfSliderDivisor));
     }
     else
     {
         ui->rfBW->setMaximum((sampleRate) / m_rfSliderDivisor);
         ui->rfOppBW->setMaximum((sampleRate) / m_rfSliderDivisor);
     }
     ui->rfBWText->setText(QString("%1k").arg((ui->rfBW->value() * m_rfSliderDivisor) / 1000.0, 0, 'f', 0));
     ui->rfOppBWText->setText(QString("%1k").arg((ui->rfOppBW->value() * m_rfSliderDivisor) / 1000.0, 0, 'f', 0));
 }
tick
void ATVDemodGUI::tick () private slot
Definition at line 466 of file atvdemodgui.cpp.
References arg(), CalcDb::dbPower(), ATVDemod::getBFOLocked(), ATVDemod::getMagSq(), m_atvDemod, m_intTickCount, m_objMagSqAverage, SDR_RX_SCALED, and ui.
Referenced by ATVDemodGUI().
 {
     if (m_intTickCount < 4) // ~200 ms
     {
         m_intTickCount++;
     }
     else
     {
         if (m_atvDemod)
         {
             m_objMagSqAverage(m_atvDemod->getMagSq());
             double magSqDB = CalcDb::dbPower(m_objMagSqAverage / (SDR_RX_SCALED*SDR_RX_SCALED));
             ui->channePowerText->setText(tr("%1 dB").arg(magSqDB, 0, 'f', 1));
             if (m_atvDemod->getBFOLocked()) {
                 ui->bfoLockedLabel->setStyleSheet("QLabel { background-color : green; }");
             } else {
                 ui->bfoLockedLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
             }
         }
         m_intTickCount = 0;
     }
     return;
 }
topTimeUpdate()
void ATVDemodGUI::topTimeUpdate () private
Definition at line 653 of file atvdemodgui.cpp.
References arg(), ATVDemod::getEffectiveSampleRate(), getNominalLineTime(), m_atvDemod, m_fltTopTimeMultiplier, and ui.
Referenced by deserialize(), handleMessage(), on_fps_currentIndexChanged(), on_nbLines_currentIndexChanged(), on_topTime_valueChanged(), and resetToDefaults().
 {
     float nominalTopTime = getNominalLineTime(ui->nbLines->currentIndex(), ui->fps->currentIndex()) * (4.7f / 64.0f);
     int topTimeScaleFactor = (int) std::log10(nominalTopTime);
     if (m_atvDemod->getEffectiveSampleRate() == 0) {
         m_fltTopTimeMultiplier = std::pow(10.0, topTimeScaleFactor-3);
     } else {
         m_fltTopTimeMultiplier = 1.0f / m_atvDemod->getEffectiveSampleRate();
     }
     float topTime = nominalTopTime + m_fltTopTimeMultiplier * ui->topTime->value();
     if (topTime < 0.0)
         ui->topTimeText->setText("invalid");
     else if (topTime < 0.000001)
         ui->topTimeText->setText(tr("%1 ns").arg(topTime * 1000000000.0, 0, 'f', 2));
     else if(topTime < 0.001)
         ui->topTimeText->setText(tr("%1 s").arg(topTime * 1000000.0, 0, 'f', 2));
     else if(topTime < 1.0)
         ui->topTimeText->setText(tr("%1 ms").arg(topTime * 1000.0, 0, 'f', 2));
     else
         ui->topTimeText->setText(tr("%1 s").arg(topTime * 1.0, 0, 'f', 2));
 }
Member Data Documentation
m_atvDemod
ATVDemod* ATVDemodGUI::m_atvDemod private
Definition at line 67 of file atvdemodgui.h.
Referenced by applyRFSettings(), applySettings(), ATVDemodGUI(), lineTimeUpdate(), on_modulation_currentIndexChanged(), on_rfFiltering_toggled(), tick(), topTimeUpdate(), and ~ATVDemodGUI().
m_blnDoApplySettings
bool ATVDemodGUI::m_blnDoApplySettings private
Definition at line 69 of file atvdemodgui.h.
Referenced by applyRFSettings(), applySettings(), blockApplySettings(), and setChannelMarkerBandwidth().
m_channelMarker
ChannelMarker ATVDemodGUI::m_channelMarker private
Definition at line 66 of file atvdemodgui.h.
Referenced by applyRFSettings(), applySettings(), ATVDemodGUI(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), deserialize(), enterEvent(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), serialize(), setCenterFrequency(), and setChannelMarkerBandwidth().
m_deviceUISet
DeviceUISet* ATVDemodGUI::m_deviceUISet private
Definition at line 65 of file atvdemodgui.h.
Referenced by ATVDemodGUI(), and ~ATVDemodGUI().
m_fltLineTimeMultiplier
float ATVDemodGUI::m_fltLineTimeMultiplier private
Definition at line 76 of file atvdemodgui.h.
Referenced by applySettings(), and lineTimeUpdate().
m_fltTopTimeMultiplier
float ATVDemodGUI::m_fltTopTimeMultiplier private
Definition at line 77 of file atvdemodgui.h.
Referenced by applySettings(), and topTimeUpdate().
m_inputMessageQueue
MessageQueue ATVDemodGUI::m_inputMessageQueue private
Definition at line 80 of file atvdemodgui.h.
m_inputSampleRate
int ATVDemodGUI::m_inputSampleRate private
Definition at line 79 of file atvdemodgui.h.
Referenced by applySettings(), handleMessage(), and setChannelMarkerBandwidth().
m_intTickCount
int ATVDemodGUI::m_intTickCount private
Definition at line 72 of file atvdemodgui.h.
Referenced by tick().
m_objMagSqAverage
MovingAverageUtil<double, double, 4> ATVDemodGUI::m_objMagSqAverage private
Definition at line 71 of file atvdemodgui.h.
Referenced by tick().
m_pluginAPI
PluginAPI* ATVDemodGUI::m_pluginAPI private
Definition at line 64 of file atvdemodgui.h.
m_rfSliderDivisor
int ATVDemodGUI::m_rfSliderDivisor private
Definition at line 78 of file atvdemodgui.h.
Referenced by applyRFSettings(), on_rfBW_valueChanged(), on_rfOppBW_valueChanged(), setChannelMarkerBandwidth(), and setRFFiltersSlidersRange().
m_scopeVis
ScopeVis* ATVDemodGUI::m_scopeVis private
Definition at line 74 of file atvdemodgui.h.
Referenced by ATVDemodGUI(), handleMessage(), and ~ATVDemodGUI().
ui
Ui::ATVDemodGUI* ATVDemodGUI::ui private
Definition at line 63 of file atvdemodgui.h.
Referenced by applyRFSettings(), applySettings(), ATVDemodGUI(), channelMarkerChangedByCursor(), deserialize(), handleMessage(), lineTimeUpdate(), on_bfo_valueChanged(), on_blackLevel_valueChanged(), on_fmDeviation_valueChanged(), on_lineTime_valueChanged(), on_rfBW_valueChanged(), on_rfOppBW_valueChanged(), on_synchLevel_valueChanged(), on_topTime_valueChanged(), resetToDefaults(), serialize(), setChannelMarkerBandwidth(), setRFFiltersSlidersRange(), tick(), topTimeUpdate(), and ~ATVDemodGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/demodatv/atvdemodgui.h
plugins/channelrx/demodatv/atvdemodgui.cpp