SDRAngel: SoapySDROutput::MsgConfigureSoapySDROutput Class Reference
SoapySDROutput::MsgConfigureSoapySDROutput Class Reference
#include <soapysdroutput.h>
Public Member Functions
const SoapySDROutputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureSoapySDROutput * create (const SoapySDROutputSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureSoapySDROutput (const SoapySDROutputSettings &settings, bool force)
Private Attributes
SoapySDROutputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 52 of file soapysdroutput.h.
Constructor & Destructor Documentation
MsgConfigureSoapySDROutput()
SoapySDROutput::MsgConfigureSoapySDROutput::MsgConfigureSoapySDROutput (const SoapySDROutputSettings & settings, bool force) inline private
Definition at line 68 of file soapysdroutput.h.
                                                                                        :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureSoapySDROutput* SoapySDROutput::MsgConfigureSoapySDROutput::create (const SoapySDROutputSettings & settings, bool force) inline static
Definition at line 59 of file soapysdroutput.h.
Referenced by SoapySDROutput::deserialize(), SoapySDROutput::handleMessage(), SoapySDROutput::setCenterFrequency(), SoapySDROutputGui::updateHardware(), and SoapySDROutput::webapiSettingsPutPatch().
         {
             return new MsgConfigureSoapySDROutput(settings, force);
         }
getForce()
bool SoapySDROutput::MsgConfigureSoapySDROutput::getForce () const inline
Definition at line 57 of file soapysdroutput.h.
Referenced by SoapySDROutput::handleMessage().
 { return m_force; }
getSettings()
const SoapySDROutputSettings& SoapySDROutput::MsgConfigureSoapySDROutput::getSettings () const inline
Definition at line 56 of file soapysdroutput.h.
Referenced by SoapySDROutputGui::handleMessage(), and SoapySDROutput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool SoapySDROutput::MsgConfigureSoapySDROutput::m_force private
Definition at line 66 of file soapysdroutput.h.
m_settings
SoapySDROutputSettings SoapySDROutput::MsgConfigureSoapySDROutput::m_settings private
Definition at line 65 of file soapysdroutput.h.
The documentation for this class was generated from the following file:
plugins/samplesink/soapysdroutput/soapysdroutput.h