SDRAngel: UDPSinkFECWorker::MsgStartStop Class Reference
UDPSinkFECWorker::MsgStartStop Class Reference
#include <udpsinkfecworker.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 96 of file udpsinkfecworker.h.
Constructor & Destructor Documentation
MsgStartStop()
UDPSinkFECWorker::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 109 of file udpsinkfecworker.h.
References UDPSinkFECWorker::pushTxFrame(), UDPSinkFECWorker::setRemoteAddress(), UDPSinkFECWorker::startStop(), UDPSinkFECWorker::UDPSinkFECWorker(), and UDPSinkFECWorker::~UDPSinkFECWorker().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* UDPSinkFECWorker::MsgStartStop::create (bool startStop) inline static
Definition at line 102 of file udpsinkfecworker.h.
Referenced by UDPSinkFECWorker::startStop().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool UDPSinkFECWorker::MsgStartStop::getStartStop () const inline
Definition at line 100 of file udpsinkfecworker.h.
Referenced by UDPSinkFECWorker::handleInputMessages().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool UDPSinkFECWorker::MsgStartStop::m_startStop protected
Definition at line 107 of file udpsinkfecworker.h.
The documentation for this class was generated from the following file:
plugins/samplesink/remoteoutput/udpsinkfecworker.h