SDRAngel: FreqTrackerGUI Class Reference
FreqTrackerGUI Class Reference
#include <freqtrackergui.h>
Public Slots
void channelMarkerChangedByCursor ()
void channelMarkerHighlightedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static FreqTrackerGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
Private Slots
void on_deltaFrequency_changed (qint64 value)
void on_log2Decim_currentIndexChanged (int index)
void on_rfBW_valueChanged (int value)
void on_tracking_toggled (bool checked)
void on_alphaEMA_valueChanged (int value)
void on_trackerType_currentIndexChanged (int index)
void on_pllPskOrder_currentIndexChanged (int index)
void on_rrc_toggled (bool checked)
void on_rrcRolloff_valueChanged (int value)
void on_squelch_valueChanged (int value)
void on_squelchGate_valueChanged (int value)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void handleInputMessages ()
void tick ()
Private Member Functions
FreqTrackerGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *parent=0)
virtual ~FreqTrackerGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::FreqTrackerGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
FreqTrackerSettings m_settings
int m_channelSampleRate
bool m_doApplySettings
FreqTracker * m_freqTracker
bool m_squelchOpen
uint32_t m_tickCount
MessageQueue m_inputMessageQueue
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 40 of file freqtrackergui.h.
Constructor & Destructor Documentation
FreqTrackerGUI()
FreqTrackerGUI::FreqTrackerGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * parent = 0) explicit private
Definition at line 278 of file freqtrackergui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), arg(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), LevelMeterSignalDB::ColorGreenAndBlue, displaySettings(), ChannelMarker::getColor(), getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, handleInputMessages(), FreqTracker::m_channelIdURI, m_channelMarker, m_deviceUISet, m_freqTracker, m_settings, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), FreqTrackerSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSink::setMessageQueueToGUI(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                              :
     RollupWidget(parent),
     ui(new Ui::FreqTrackerGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_channelSampleRate(0),
     m_doApplySettings(true),
     m_squelchOpen(false),
     m_tickCount(0)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_freqTracker = reinterpret_cast<FreqTracker*>(rxChannel); //new FreqTracker(m_deviceUISet->m_deviceSourceAPI);
     m_freqTracker->setMessageQueueToGUI(getInputMessageQueue());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick())); // 50 ms
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     ui->channelPowerMeter->setColorTheme(LevelMeterSignalDB::ColorGreenAndBlue);
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(Qt::yellow);
     m_channelMarker.setBandwidth(5000);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("AM Demodulator");
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     setTitleColor(m_channelMarker.getColor());
     m_settings.setChannelMarker(&m_channelMarker);
     m_deviceUISet->registerRxChannelInstance(FreqTracker::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(&m_channelMarker, SIGNAL(highlightedByCursor()), this, SLOT(channelMarkerHighlightedByCursor()));
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
     displaySettings();
     applySettings(true);
 }
~FreqTrackerGUI()
FreqTrackerGUI::~FreqTrackerGUI () private virtual
Definition at line 327 of file freqtrackergui.cpp.
References m_deviceUISet, m_freqTracker, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_freqTracker; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete ui;
 }
Member Function Documentation
applySettings()
void FreqTrackerGUI::applySettings (bool force = false) private
Definition at line 339 of file freqtrackergui.cpp.
References FreqTracker::MsgConfigureFreqTracker::create(), BasebandSampleSink::getInputMessageQueue(), m_doApplySettings, m_freqTracker, m_settings, and MessageQueue::push().
Referenced by channelMarkerChangedByCursor(), deserialize(), FreqTrackerGUI(), on_alphaEMA_valueChanged(), on_deltaFrequency_changed(), on_log2Decim_currentIndexChanged(), on_pllPskOrder_currentIndexChanged(), on_rfBW_valueChanged(), on_rrc_toggled(), on_rrcRolloff_valueChanged(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_trackerType_currentIndexChanged(), on_tracking_toggled(), onMenuDialogCalled(), resetToDefaults(), and setCenterFrequency().
 {
     if (m_doApplySettings)
     {
         FreqTracker::MsgConfigureFreqTracker* message = FreqTracker::MsgConfigureFreqTracker::create( m_settings, force);
         m_freqTracker->getInputMessageQueue()->push(message);
     }
 }
blockApplySettings()
void FreqTrackerGUI::blockApplySettings (bool block) private
Definition at line 334 of file freqtrackergui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void FreqTrackerGUI::channelMarkerChangedByCursor () slot
Definition at line 144 of file freqtrackergui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, FreqTrackerSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by FreqTrackerGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
channelMarkerHighlightedByCursor
void FreqTrackerGUI::channelMarkerHighlightedByCursor () slot
Definition at line 151 of file freqtrackergui.cpp.
References ChannelMarker::getHighlighted(), m_channelMarker, and RollupWidget::setHighlighted().
Referenced by FreqTrackerGUI().
 {
     setHighlighted(m_channelMarker.getHighlighted());
 }
create()
FreqTrackerGUI * FreqTrackerGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) static
Definition at line 40 of file freqtrackergui.cpp.
References FreqTrackerGUI().
Referenced by FreqTrackerPlugin::createRxChannelGUI().
 {
     FreqTrackerGUI* gui = new FreqTrackerGUI(pluginAPI, deviceUISet, rxChannel);
     return gui;
 }
deserialize()
bool FreqTrackerGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 83 of file freqtrackergui.cpp.
References applySettings(), FreqTrackerSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void FreqTrackerGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 46 of file freqtrackergui.cpp.
 {
     delete this;
 }
displaySettings()
void FreqTrackerGUI::displaySettings () private
Definition at line 348 of file freqtrackergui.cpp.
References arg(), blockApplySettings(), ChannelMarker::getCenterFrequency(), ChannelMarker::getTitle(), i, FreqTrackerSettings::m_alphaEMA, m_channelMarker, FreqTrackerSettings::m_inputFrequencyOffset, FreqTrackerSettings::m_log2Decim, FreqTrackerSettings::m_pllPskOrder, FreqTrackerSettings::m_rfBandwidth, FreqTrackerSettings::m_rgbColor, FreqTrackerSettings::m_rrc, FreqTrackerSettings::m_rrcRolloff, m_settings, FreqTrackerSettings::m_squelch, FreqTrackerSettings::m_squelchGate, FreqTrackerSettings::m_title, FreqTrackerSettings::m_trackerType, FreqTrackerSettings::m_tracking, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by deserialize(), FreqTrackerGUI(), handleMessage(), and resetToDefaults().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setBandwidth(m_settings.m_rfBandwidth);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     ui->log2Decim->setCurrentIndex(m_settings.m_log2Decim);
     int displayValue = m_settings.m_rfBandwidth/100.0;
     ui->rfBW->setValue(displayValue);
     ui->rfBWText->setText(QString("%1 kHz").arg(displayValue / 10.0, 0, 'f', 1));
     ui->squelch->setValue(m_settings.m_squelch);
     ui->squelchText->setText(QString("%1 dB").arg(m_settings.m_squelch));
     ui->tracking->setChecked(m_settings.m_tracking);
     ui->trackerType->setCurrentIndex((int) m_settings.m_trackerType);
     QString alphaEMAStr = QString::number(m_settings.m_alphaEMA, 'f', 2);
     ui->alphaEMAText->setText(alphaEMAStr);
     ui->alphaEMA->setValue(m_settings.m_alphaEMA*100.0);
     int i = 0;
     for(; ((m_settings.m_pllPskOrder>>i) & 1) == 0; i++);
     ui->pllPskOrder->setCurrentIndex(i);
     ui->rrc->setChecked(m_settings.m_rrc);
     ui->rrcRolloff->setValue(m_settings.m_rrcRolloff);
     QString rolloffStr = QString::number(m_settings.m_rrcRolloff/100.0, 'f', 2);
     ui->rrcRolloffText->setText(rolloffStr);
     ui->squelchGateText->setText(QString("%1").arg(m_settings.m_squelchGate * 10.0f, 0, 'f', 0));
     ui->squelchGate->setValue(m_settings.m_squelchGate);
     blockApplySettings(false);
 }
enterEvent()
void FreqTrackerGUI::enterEvent (QEvent *) private
Definition at line 394 of file freqtrackergui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 FreqTrackerGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 61 of file freqtrackergui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
{
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* FreqTrackerGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 55 of file freqtrackergui.h.
Referenced by FreqTrackerGUI(), and handleInputMessages().
 { return &m_inputMessageQueue; }
getName()
QString FreqTrackerGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 56 of file freqtrackergui.cpp.
 {
     return objectName();
 }
handleInputMessages
void FreqTrackerGUI::handleInputMessages () private slot
Definition at line 131 of file freqtrackergui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by FreqTrackerGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
bool FreqTrackerGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 95 of file freqtrackergui.cpp.
References arg(), blockApplySettings(), displaySettings(), FreqTracker::MsgSampleRateNotification::getFrequencyOffset(), FreqTracker::MsgSampleRateNotification::getSampleRate(), FreqTracker::MsgConfigureFreqTracker::getSettings(), m_channelMarker, m_channelSampleRate, FreqTrackerSettings::m_inputFrequencyOffset, m_settings, FreqTrackerSettings::m_tracking, Message::match(), ChannelMarker::setCenterFrequency(), and ui.
Referenced by handleInputMessages().
 {
     if (FreqTracker::MsgConfigureFreqTracker::match(message))
     {
         qDebug("FreqTrackerGUI::handleMessage: FreqTracker::MsgConfigureFreqTracker");
         const FreqTracker::MsgConfigureFreqTracker& cfg = (FreqTracker::MsgConfigureFreqTracker&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (FreqTracker::MsgSampleRateNotification::match(message))
     {
         if (!m_settings.m_tracking) {
             qDebug("FreqTrackerGUI::handleMessage: FreqTracker::MsgSampleRateNotification");
         }
         const FreqTracker::MsgSampleRateNotification& cfg = (FreqTracker::MsgSampleRateNotification&) message;
         m_channelSampleRate = cfg.getSampleRate();
         ui->channelSampleRateText->setText(tr("%1k").arg(QString::number(m_channelSampleRate / 1000.0f, 'g', 5)));
         blockApplySettings(true);
         m_settings.m_inputFrequencyOffset = cfg.getFrequencyOffset();
         ui->deltaFrequency->setValue(m_settings.m_inputFrequencyOffset);
         m_channelMarker.setCenterFrequency(cfg.getFrequencyOffset());
         blockApplySettings(false);
         if (m_channelSampleRate > 1000) {
             ui->rfBW->setMaximum(m_channelSampleRate/100);
         }
         return true;
     }
     return false;
 }
leaveEvent()
void FreqTrackerGUI::leaveEvent (QEvent *) private
Definition at line 389 of file freqtrackergui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_alphaEMA_valueChanged
void FreqTrackerGUI::on_alphaEMA_valueChanged (int value) private slot
Definition at line 189 of file freqtrackergui.cpp.
References applySettings(), FreqTrackerSettings::m_alphaEMA, m_settings, and ui.
 {
     m_settings.m_alphaEMA = value / 100.0;
     QString alphaEMAStr = QString::number(m_settings.m_alphaEMA, 'f', 2);
     ui->alphaEMAText->setText(alphaEMAStr);
     applySettings();
 }
on_deltaFrequency_changed
void FreqTrackerGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 156 of file freqtrackergui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, FreqTrackerSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_log2Decim_currentIndexChanged
void FreqTrackerGUI::on_log2Decim_currentIndexChanged (int index) private slot
Definition at line 163 of file freqtrackergui.cpp.
References applySettings(), FreqTrackerSettings::m_log2Decim, and m_settings.
 {
     m_settings.m_log2Decim = index < 0 ? 0 : index > 6 ? 6 : index;
     applySettings();
 }
on_pllPskOrder_currentIndexChanged
void FreqTrackerGUI::on_pllPskOrder_currentIndexChanged (int index) private slot
Definition at line 203 of file freqtrackergui.cpp.
References applySettings(), FreqTrackerSettings::m_pllPskOrder, and m_settings.
 {
     if ((index < 0) || (index > 5)) {
         return;
     }
     m_settings.m_pllPskOrder = 1<<index;
     applySettings();
 }
on_rfBW_valueChanged
void FreqTrackerGUI::on_rfBW_valueChanged (int value) private slot
Definition at line 169 of file freqtrackergui.cpp.
References applySettings(), arg(), m_channelMarker, FreqTrackerSettings::m_rfBandwidth, m_settings, ChannelMarker::setBandwidth(), and ui.
 {
     ui->rfBWText->setText(QString("%1 kHz").arg(value / 10.0, 0, 'f', 1));
     m_channelMarker.setBandwidth(value * 100);
     m_settings.m_rfBandwidth = value * 100;
     applySettings();
 }
on_rrc_toggled
void FreqTrackerGUI::on_rrc_toggled (bool checked) private slot
Definition at line 213 of file freqtrackergui.cpp.
References applySettings(), FreqTrackerSettings::m_rrc, and m_settings.
 {
     m_settings.m_rrc = checked;
     applySettings();
 }
on_rrcRolloff_valueChanged
void FreqTrackerGUI::on_rrcRolloff_valueChanged (int value) private slot
Definition at line 219 of file freqtrackergui.cpp.
References applySettings(), FreqTrackerSettings::m_rrcRolloff, m_settings, and ui.
 {
     m_settings.m_rrcRolloff = value < 0 ? 0 : value > 100 ? 100 : value;
     QString rolloffStr = QString::number(value/100.0, 'f', 2);
     ui->rrcRolloffText->setText(rolloffStr);
     applySettings();
 }
on_squelch_valueChanged
void FreqTrackerGUI::on_squelch_valueChanged (int value) private slot
Definition at line 227 of file freqtrackergui.cpp.
References applySettings(), arg(), m_settings, FreqTrackerSettings::m_squelch, and ui.
 {
     ui->squelchText->setText(QString("%1 dB").arg(value));
     m_settings.m_squelch = value;
     applySettings();
 }
on_squelchGate_valueChanged
void FreqTrackerGUI::on_squelchGate_valueChanged (int value) private slot
Definition at line 234 of file freqtrackergui.cpp.
References applySettings(), arg(), m_settings, FreqTrackerSettings::m_squelchGate, and ui.
 {
     ui->squelchGateText->setText(QString("%1").arg(value * 10.0f, 0, 'f', 0));
     m_settings.m_squelchGate = value;
     applySettings();
 }
on_trackerType_currentIndexChanged
void FreqTrackerGUI::on_trackerType_currentIndexChanged (int index) private slot
Definition at line 197 of file freqtrackergui.cpp.
References applySettings(), m_settings, and FreqTrackerSettings::m_trackerType.
 {
     m_settings.m_trackerType = (FreqTrackerSettings::TrackerType) index;
     applySettings();
 }
on_tracking_toggled
void FreqTrackerGUI::on_tracking_toggled (bool checked) private slot
Definition at line 177 of file freqtrackergui.cpp.
References applySettings(), m_settings, FreqTrackerSettings::m_tracking, and ui.
 {
     if (!checked)
     {
         ui->tracking->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         ui->tracking->setToolTip(tr("PLL for synchronous AM"));
     }
     m_settings.m_tracking = checked;
     applySettings();
 }
onMenuDialogCalled
void FreqTrackerGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 247 of file freqtrackergui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, FreqTrackerSettings::m_inputFrequencyOffset, FreqTrackerSettings::m_reverseAPIAddress, FreqTrackerSettings::m_reverseAPIChannelIndex, FreqTrackerSettings::m_reverseAPIDeviceIndex, FreqTrackerSettings::m_reverseAPIPort, FreqTrackerSettings::m_rgbColor, m_settings, FreqTrackerSettings::m_title, FreqTrackerSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by FreqTrackerGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void FreqTrackerGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 241 of file freqtrackergui.cpp.
Referenced by FreqTrackerGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void FreqTrackerGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 71 of file freqtrackergui.cpp.
References applySettings(), displaySettings(), m_settings, and FreqTrackerSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
serialize()
QByteArray FreqTrackerGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 78 of file freqtrackergui.cpp.
References m_settings, and FreqTrackerSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void FreqTrackerGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 65 of file freqtrackergui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     applySettings();
 }
setName()
void FreqTrackerGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 51 of file freqtrackergui.cpp.
 {
     setObjectName(name);
 }
tick
void FreqTrackerGUI::tick () private slot
Definition at line 399 of file freqtrackergui.cpp.
References arg(), CalcDb::dbPower(), FreqTracker::getAvgDeltaFreq(), FreqTracker::getMagSqLevels(), FreqTracker::getPllLocked(), FreqTracker::getSquelchOpen(), m_freqTracker, m_settings, m_tickCount, FreqTrackerSettings::m_tracking, and ui.
Referenced by FreqTrackerGUI().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     m_freqTracker->getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     double powDbAvg = CalcDb::dbPower(magsqAvg);
     double powDbPeak = CalcDb::dbPower(magsqPeak);
     ui->channelPowerMeter->levelChanged(
             (100.0f + powDbAvg) / 100.0f,
             (100.0f + powDbPeak) / 100.0f,
             nbMagsqSamples);
     if (m_tickCount % 4 == 0) {
         ui->channelPower->setText(QString::number(powDbAvg, 'f', 1));
     }
     bool squelchOpen = m_freqTracker->getSquelchOpen();
     if (squelchOpen) {
         ui->squelchLabel->setStyleSheet("QLabel { background-color : green; }");
     } else {
         ui->squelchLabel->setStyleSheet("QLabel { background:rgb(50,50,50); }");
     }
     if (m_freqTracker->getPllLocked()) {
         ui->tracking->setStyleSheet("QToolButton { background-color : green; }");
     } else {
         ui->tracking->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     int freq = m_freqTracker->getAvgDeltaFreq();
     QLocale loc;
     ui->trackingFrequencyText->setText(tr("%1 Hz").arg(loc.toString(freq)));
     if (m_settings.m_tracking) {
         ui->tracking->setToolTip("Tracking on");
     } else {
         ui->tracking->setToolTip("Tracking off");
     }
     m_tickCount++;
 }
Member Data Documentation
m_channelMarker
ChannelMarker FreqTrackerGUI::m_channelMarker private
Definition at line 66 of file freqtrackergui.h.
Referenced by channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), displaySettings(), enterEvent(), FreqTrackerGUI(), getCenterFrequency(), handleMessage(), leaveEvent(), on_deltaFrequency_changed(), on_rfBW_valueChanged(), onMenuDialogCalled(), and setCenterFrequency().
m_channelSampleRate
int FreqTrackerGUI::m_channelSampleRate private
Definition at line 68 of file freqtrackergui.h.
Referenced by handleMessage().
m_deviceUISet
DeviceUISet* FreqTrackerGUI::m_deviceUISet private
Definition at line 65 of file freqtrackergui.h.
Referenced by FreqTrackerGUI(), and ~FreqTrackerGUI().
m_doApplySettings
bool FreqTrackerGUI::m_doApplySettings private
Definition at line 69 of file freqtrackergui.h.
Referenced by applySettings(), and blockApplySettings().
m_freqTracker
FreqTracker* FreqTrackerGUI::m_freqTracker private
Definition at line 71 of file freqtrackergui.h.
Referenced by applySettings(), FreqTrackerGUI(), tick(), and ~FreqTrackerGUI().
m_inputMessageQueue
MessageQueue FreqTrackerGUI::m_inputMessageQueue private
Definition at line 74 of file freqtrackergui.h.
m_pluginAPI
PluginAPI* FreqTrackerGUI::m_pluginAPI private
Definition at line 64 of file freqtrackergui.h.
m_settings
FreqTrackerSettings FreqTrackerGUI::m_settings private
Definition at line 67 of file freqtrackergui.h.
Referenced by applySettings(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), FreqTrackerGUI(), handleMessage(), on_alphaEMA_valueChanged(), on_deltaFrequency_changed(), on_log2Decim_currentIndexChanged(), on_pllPskOrder_currentIndexChanged(), on_rfBW_valueChanged(), on_rrc_toggled(), on_rrcRolloff_valueChanged(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_trackerType_currentIndexChanged(), on_tracking_toggled(), onMenuDialogCalled(), resetToDefaults(), serialize(), and tick().
m_squelchOpen
bool FreqTrackerGUI::m_squelchOpen private
Definition at line 72 of file freqtrackergui.h.
m_tickCount
uint32_t FreqTrackerGUI::m_tickCount private
Definition at line 73 of file freqtrackergui.h.
Referenced by tick().
ui
Ui::FreqTrackerGUI* FreqTrackerGUI::ui private
Definition at line 63 of file freqtrackergui.h.
Referenced by channelMarkerChangedByCursor(), displaySettings(), FreqTrackerGUI(), handleMessage(), on_alphaEMA_valueChanged(), on_rfBW_valueChanged(), on_rrcRolloff_valueChanged(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_tracking_toggled(), tick(), and ~FreqTrackerGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/freqtracker/freqtrackergui.h
plugins/channelrx/freqtracker/freqtrackergui.cpp