SDRAngel: Bladerf1OutputGui Class Reference
Bladerf1OutputGui Class Reference
#include <bladerf1outputgui.h>
Public Member Functions
Bladerf1OutputGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~Bladerf1OutputGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_centerFrequency_changed (quint64 value)
void on_sampleRate_changed (quint64 value)
void on_bandwidth_currentIndexChanged (int index)
void on_interp_currentIndexChanged (int index)
void on_vga1_valueChanged (int value)
void on_vga2_valueChanged (int value)
void on_xb200_currentIndexChanged (int index)
void on_startStop_toggled (bool checked)
void on_sampleRateMode_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void displaySampleRate ()
void sendSettings ()
unsigned int getXb200Index (bool xb_200, bladerf_xb200_path xb200Path, bladerf_xb200_filter xb200Filter)
void updateSampleRateAndFrequency ()
Private Attributes
Ui::Bladerf1OutputGui * ui
DeviceUISet * m_deviceUISet
bool m_doApplySettings
bool m_forceSettings
BladeRF1OutputSettings m_settings
bool m_sampleRateMode
true: device, false: base band sample rate update mode
QTimer m_updateTimer
QTimer m_statusTimer
DeviceSampleSink * m_deviceSampleSink
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 36 of file bladerf1outputgui.h.
Constructor & Destructor Documentation
Bladerf1OutputGui()
Bladerf1OutputGui::Bladerf1OutputGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 34 of file bladerf1outputgui.cpp.
References displaySettings(), BladerfBandwidths::getBandwidth(), BladerfBandwidths::getNbBandwidths(), DeviceAPI::getSampleSink(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, handleInputMessages(), i, DeviceUISet::m_deviceAPI, m_deviceSampleSink, m_deviceUISet, m_inputMessageQueue, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), ui, updateHardware(), and updateStatus().
                                                                               :
     QWidget(parent),
     ui(new Ui::Bladerf1OutputGui),
     m_deviceUISet(deviceUISet),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_settings(),
     m_sampleRateMode(true),
     m_deviceSampleSink(nullptr),
     m_sampleRate(0),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     m_deviceSampleSink = (Bladerf1Output*) m_deviceUISet->m_deviceAPI->getSampleSink();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, BLADERF_FREQUENCY_MIN_XB200/1000, BLADERF_FREQUENCY_MAX/1000);
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(8, BLADERF_SAMPLERATE_MIN, BLADERF_SAMPLERATE_REC_MAX);
     ui->bandwidth->clear();
     for (unsigned int i = 0; i < BladerfBandwidths::getNbBandwidths(); i++)
     {
         ui->bandwidth->addItem(QString::number(BladerfBandwidths::getBandwidth(i)));
     }
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
 }
~Bladerf1OutputGui()
Bladerf1OutputGui::~Bladerf1OutputGui () virtual
Definition at line 74 of file bladerf1outputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void Bladerf1OutputGui::blockApplySettings (bool block) inline private
Definition at line 71 of file bladerf1outputgui.h.
Referenced by handleMessage().
 { m_doApplySettings = !block; }
deserialize()
bool Bladerf1OutputGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 118 of file bladerf1outputgui.cpp.
References BladeRF1OutputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void Bladerf1OutputGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 79 of file bladerf1outputgui.cpp.
 {
     delete this;
 }
displaySampleRate()
void Bladerf1OutputGui::displaySampleRate () private
Definition at line 196 of file bladerf1outputgui.cpp.
References arg(), BladeRF1OutputSettings::m_devSampleRate, BladeRF1OutputSettings::m_log2Interp, m_sampleRateMode, m_settings, and ui.
Referenced by displaySettings(), on_interp_currentIndexChanged(), on_sampleRateMode_toggled(), and updateSampleRateAndFrequency().
 {
     ui->sampleRate->blockSignals(true);
     if (m_sampleRateMode)
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(60,60,60); }");
         ui->sampleRateMode->setText("SR");
         ui->sampleRate->setValueRange(8, BLADERF_SAMPLERATE_MIN, BLADERF_SAMPLERATE_REC_MAX);
         ui->sampleRate->setValue(m_settings.m_devSampleRate);
         ui->sampleRate->setToolTip("Host to device sample rate (S/s)");
         ui->deviceRateText->setToolTip("Baseband sample rate (S/s)");
         uint32_t basebandSampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Interp);
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(basebandSampleRate / 1000.0f, 'g', 5)));
     }
     else
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(50,50,50); }");
         ui->sampleRateMode->setText("BB");
         ui->sampleRate->setValueRange(8, BLADERF_SAMPLERATE_MIN/(1<<m_settings.m_log2Interp), BLADERF_SAMPLERATE_REC_MAX/(1<<m_settings.m_log2Interp));
         ui->sampleRate->setValue(m_settings.m_devSampleRate/(1<<m_settings.m_log2Interp));
         ui->sampleRate->setToolTip("Baseband sample rate (S/s)");
         ui->deviceRateText->setToolTip("Host to device sample rate (S/s)");
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_settings.m_devSampleRate / 1000.0f, 'g', 5)));
     }
     ui->sampleRate->blockSignals(false);
 }
displaySettings()
void Bladerf1OutputGui::displaySettings () private
Definition at line 225 of file bladerf1outputgui.cpp.
References arg(), displaySampleRate(), BladerfBandwidths::getBandwidthIndex(), getXb200Index(), BladeRF1OutputSettings::m_bandwidth, BladeRF1OutputSettings::m_centerFrequency, BladeRF1OutputSettings::m_log2Interp, m_settings, BladeRF1OutputSettings::m_vga1, BladeRF1OutputSettings::m_vga2, BladeRF1OutputSettings::m_xb200, BladeRF1OutputSettings::m_xb200Filter, BladeRF1OutputSettings::m_xb200Path, and ui.
Referenced by Bladerf1OutputGui(), deserialize(), handleMessage(), resetToDefaults(), and setCenterFrequency().
 {
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     displaySampleRate();
     unsigned int bandwidthIndex = BladerfBandwidths::getBandwidthIndex(m_settings.m_bandwidth);
     ui->bandwidth->setCurrentIndex(bandwidthIndex);
     ui->interp->setCurrentIndex(m_settings.m_log2Interp);
     ui->vga1Text->setText(tr("%1dB").arg(m_settings.m_vga1));
     ui->vga1->setValue(m_settings.m_vga1);
     ui->vga2Text->setText(tr("%1dB").arg(m_settings.m_vga2));
     ui->vga2->setValue(m_settings.m_vga2);
     ui->xb200->setCurrentIndex(getXb200Index(m_settings.m_xb200, m_settings.m_xb200Path, m_settings.m_xb200Filter));
 }
getCenterFrequency()
qint64 Bladerf1OutputGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 101 of file bladerf1outputgui.cpp.
References BladeRF1OutputSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* Bladerf1OutputGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 52 of file bladerf1outputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString Bladerf1OutputGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 89 of file bladerf1outputgui.cpp.
 {
     return objectName();
 }
getXb200Index()
unsigned int Bladerf1OutputGui::getXb200Index (bool xb_200, bladerf_xb200_path xb200Path, bladerf_xb200_filter xb200Filter) private
Definition at line 425 of file bladerf1outputgui.cpp.
Referenced by displaySettings().
 {
     if (xb_200)
     {
         if (xb200Path == BLADERF_XB200_BYPASS)
         {
             return 1;
         }
         else
         {
             if (xb200Filter == BLADERF_XB200_AUTO_1DB)
             {
                 return 2;
             }
             else if (xb200Filter == BLADERF_XB200_AUTO_3DB)
             {
                 return 3;
             }
             else if (xb200Filter == BLADERF_XB200_CUSTOM)
             {
                 return 4;
             }
             else if (xb200Filter == BLADERF_XB200_50M)
             {
                 return 5;
             }
             else if (xb200Filter == BLADERF_XB200_144M)
             {
                 return 6;
             }
             else // xb200Filter == BLADERF_XB200_222M
             {
                 return 7;
             }
         }
     }
     else
     {
         return 0;
     }
 }
handleInputMessages
void Bladerf1OutputGui::handleInputMessages () private slot
Definition at line 161 of file bladerf1outputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by Bladerf1OutputGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("BladerfOutputGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("BladerfOutputGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool Bladerf1OutputGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 131 of file bladerf1outputgui.cpp.
References blockApplySettings(), displaySettings(), Bladerf1Output::MsgConfigureBladerf1::getSettings(), Bladerf1Output::MsgStartStop::getStartStop(), m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (Bladerf1Output::MsgConfigureBladerf1::match(message))
     {
         const Bladerf1Output::MsgConfigureBladerf1& cfg = (Bladerf1Output::MsgConfigureBladerf1&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (Bladerf1Output::MsgReportBladerf1::match(message))
     {
         displaySettings();
         return true;
     }
     else if (Bladerf1Output::MsgStartStop::match(message))
     {
         Bladerf1Output::MsgStartStop& notif = (Bladerf1Output::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_bandwidth_currentIndexChanged
void Bladerf1OutputGui::on_bandwidth_currentIndexChanged (int index) private slot
Definition at line 267 of file bladerf1outputgui.cpp.
References BladerfBandwidths::getBandwidth(), BladeRF1OutputSettings::m_bandwidth, m_settings, and sendSettings().
 {
     int newbw = BladerfBandwidths::getBandwidth(index);
     m_settings.m_bandwidth = newbw * 1000;
     sendSettings();
 }
on_centerFrequency_changed
void Bladerf1OutputGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 250 of file bladerf1outputgui.cpp.
References BladeRF1OutputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_interp_currentIndexChanged
void Bladerf1OutputGui::on_interp_currentIndexChanged (int index) private slot
Definition at line 274 of file bladerf1outputgui.cpp.
References displaySampleRate(), BladeRF1OutputSettings::m_devSampleRate, BladeRF1OutputSettings::m_log2Interp, m_sampleRateMode, m_settings, sendSettings(), and ui.
 {
     if ((index <0) || (index > 6)) {
         return;
     }
     m_settings.m_log2Interp = index;
     displaySampleRate();
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     } else {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew() * (1 << m_settings.m_log2Interp);
     }
     sendSettings();
 }
on_sampleRate_changed
void Bladerf1OutputGui::on_sampleRate_changed (quint64 value) private slot
Definition at line 256 of file bladerf1outputgui.cpp.
References BladeRF1OutputSettings::m_devSampleRate, BladeRF1OutputSettings::m_log2Interp, m_sampleRateMode, m_settings, and sendSettings().
 {
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = value;
     } else {
         m_settings.m_devSampleRate = value * (1 << m_settings.m_log2Interp);
     }
     sendSettings();
 }
on_sampleRateMode_toggled
void Bladerf1OutputGui::on_sampleRateMode_toggled (bool checked) private slot
Definition at line 381 of file bladerf1outputgui.cpp.
References displaySampleRate(), and m_sampleRateMode.
 {
     m_sampleRateMode = checked;
     displaySampleRate();
 }
on_startStop_toggled
void Bladerf1OutputGui::on_startStop_toggled (bool checked) private slot
Definition at line 372 of file bladerf1outputgui.cpp.
References Bladerf1Output::MsgStartStop::create(), DeviceSampleSink::getInputMessageQueue(), m_deviceSampleSink, m_doApplySettings, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         Bladerf1Output::MsgStartStop *message = Bladerf1Output::MsgStartStop::create(checked);
         m_deviceSampleSink->getInputMessageQueue()->push(message);
     }
 }
on_vga1_valueChanged
void Bladerf1OutputGui::on_vga1_valueChanged (int value) private slot
Definition at line 292 of file bladerf1outputgui.cpp.
References arg(), m_settings, BladeRF1OutputSettings::m_vga1, sendSettings(), and ui.
 {
     if ((value < BLADERF_TXVGA1_GAIN_MIN) || (value > BLADERF_TXVGA1_GAIN_MAX))
         return;
     ui->vga1Text->setText(tr("%1dB").arg(value));
     m_settings.m_vga1 = value;
     sendSettings();
 }
on_vga2_valueChanged
void Bladerf1OutputGui::on_vga2_valueChanged (int value) private slot
Definition at line 302 of file bladerf1outputgui.cpp.
References arg(), m_settings, BladeRF1OutputSettings::m_vga2, sendSettings(), and ui.
 {
     if ((value < BLADERF_TXVGA2_GAIN_MIN) || (value > BLADERF_TXVGA2_GAIN_MAX))
         return;
     ui->vga2Text->setText(tr("%1dB").arg(value));
     m_settings.m_vga2 = value;
     sendSettings();
 }
on_xb200_currentIndexChanged
void Bladerf1OutputGui::on_xb200_currentIndexChanged (int index) private slot
Definition at line 312 of file bladerf1outputgui.cpp.
References m_settings, BladeRF1OutputSettings::m_xb200, BladeRF1OutputSettings::m_xb200Filter, BladeRF1OutputSettings::m_xb200Path, sendSettings(), and ui.
 {
     if (index == 1) // bypass
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_BYPASS;
     }
     else if (index == 2) // Auto 1dB
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_MIX;
         m_settings.m_xb200Filter = BLADERF_XB200_AUTO_1DB;
     }
     else if (index == 3) // Auto 3dB
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_MIX;
         m_settings.m_xb200Filter = BLADERF_XB200_AUTO_3DB;
     }
     else if (index == 4) // Custom
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_MIX;
         m_settings.m_xb200Filter = BLADERF_XB200_CUSTOM;
     }
     else if (index == 5) // 50 MHz
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_MIX;
         m_settings.m_xb200Filter = BLADERF_XB200_50M;
     }
     else if (index == 6) // 144 MHz
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_MIX;
         m_settings.m_xb200Filter = BLADERF_XB200_144M;
     }
     else if (index == 7) // 222 MHz
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_MIX;
         m_settings.m_xb200Filter = BLADERF_XB200_222M;
     }
     else // no xb200
     {
         m_settings.m_xb200 = false;
     }
     if (m_settings.m_xb200)
     {
         ui->centerFrequency->setValueRange(7, BLADERF_FREQUENCY_MIN_XB200/1000, BLADERF_FREQUENCY_MAX/1000);
     }
     else
     {
         ui->centerFrequency->setValueRange(7, BLADERF_FREQUENCY_MIN/1000, BLADERF_FREQUENCY_MAX/1000);
     }
     sendSettings();
 }
openDeviceSettingsDialog
void Bladerf1OutputGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 467 of file bladerf1outputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), BladeRF1OutputSettings::m_reverseAPIAddress, BladeRF1OutputSettings::m_reverseAPIDeviceIndex, BladeRF1OutputSettings::m_reverseAPIPort, m_settings, BladeRF1OutputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by Bladerf1OutputGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void Bladerf1OutputGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 94 of file bladerf1outputgui.cpp.
References displaySettings(), m_settings, BladeRF1OutputSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void Bladerf1OutputGui::sendSettings () private
Definition at line 244 of file bladerf1outputgui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_bandwidth_currentIndexChanged(), on_centerFrequency_changed(), on_interp_currentIndexChanged(), on_sampleRate_changed(), on_vga1_valueChanged(), on_vga2_valueChanged(), on_xb200_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray Bladerf1OutputGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 113 of file bladerf1outputgui.cpp.
References m_settings, and BladeRF1OutputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void Bladerf1OutputGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 106 of file bladerf1outputgui.cpp.
References displaySettings(), BladeRF1OutputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void Bladerf1OutputGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 84 of file bladerf1outputgui.cpp.
 {
     setObjectName(name);
 }
updateHardware
void Bladerf1OutputGui::updateHardware () private slot
Definition at line 387 of file bladerf1outputgui.cpp.
References Bladerf1Output::MsgConfigureBladerf1::create(), DeviceSampleSink::getInputMessageQueue(), m_deviceSampleSink, m_forceSettings, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by Bladerf1OutputGui().
 {
     qDebug() << "BladerfGui::updateHardware";
     Bladerf1Output::MsgConfigureBladerf1* message = Bladerf1Output::MsgConfigureBladerf1::create( m_settings, m_forceSettings);
     m_deviceSampleSink->getInputMessageQueue()->push(message);
     m_forceSettings = false;
     m_updateTimer.stop();
 }
updateSampleRateAndFrequency()
void Bladerf1OutputGui::updateSampleRateAndFrequency () private
Definition at line 189 of file bladerf1outputgui.cpp.
References displaySampleRate(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), and GLSpectrum::setSampleRate().
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     displaySampleRate();
 }
updateStatus
void Bladerf1OutputGui::updateStatus () private slot
Definition at line 396 of file bladerf1outputgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by Bladerf1OutputGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 Bladerf1OutputGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 67 of file bladerf1outputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceSampleSink
DeviceSampleSink* Bladerf1OutputGui::m_deviceSampleSink private
Definition at line 65 of file bladerf1outputgui.h.
Referenced by Bladerf1OutputGui(), on_startStop_toggled(), and updateHardware().
m_deviceUISet
DeviceUISet* Bladerf1OutputGui::m_deviceUISet private
Definition at line 58 of file bladerf1outputgui.h.
Referenced by Bladerf1OutputGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool Bladerf1OutputGui::m_doApplySettings private
Definition at line 59 of file bladerf1outputgui.h.
Referenced by on_startStop_toggled().
m_forceSettings
bool Bladerf1OutputGui::m_forceSettings private
Definition at line 60 of file bladerf1outputgui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue Bladerf1OutputGui::m_inputMessageQueue private
Definition at line 69 of file bladerf1outputgui.h.
Referenced by Bladerf1OutputGui(), and handleInputMessages().
m_lastEngineState
int Bladerf1OutputGui::m_lastEngineState private
Definition at line 68 of file bladerf1outputgui.h.
Referenced by updateStatus().
m_sampleRate
int Bladerf1OutputGui::m_sampleRate private
Definition at line 66 of file bladerf1outputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateMode
bool Bladerf1OutputGui::m_sampleRateMode private
true: device, false: base band sample rate update mode
Definition at line 62 of file bladerf1outputgui.h.
Referenced by displaySampleRate(), on_interp_currentIndexChanged(), on_sampleRate_changed(), and on_sampleRateMode_toggled().
m_settings
BladeRF1OutputSettings Bladerf1OutputGui::m_settings private
Definition at line 61 of file bladerf1outputgui.h.
Referenced by deserialize(), displaySampleRate(), displaySettings(), getCenterFrequency(), handleMessage(), on_bandwidth_currentIndexChanged(), on_centerFrequency_changed(), on_interp_currentIndexChanged(), on_sampleRate_changed(), on_vga1_valueChanged(), on_vga2_valueChanged(), on_xb200_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), and updateHardware().
m_statusTimer
QTimer Bladerf1OutputGui::m_statusTimer private
Definition at line 64 of file bladerf1outputgui.h.
Referenced by Bladerf1OutputGui().
m_updateTimer
QTimer Bladerf1OutputGui::m_updateTimer private
Definition at line 63 of file bladerf1outputgui.h.
Referenced by Bladerf1OutputGui(), sendSettings(), and updateHardware().
ui
Ui::Bladerf1OutputGui* Bladerf1OutputGui::ui private
Definition at line 56 of file bladerf1outputgui.h.
Referenced by Bladerf1OutputGui(), displaySampleRate(), displaySettings(), handleMessage(), on_interp_currentIndexChanged(), on_vga1_valueChanged(), on_vga2_valueChanged(), on_xb200_currentIndexChanged(), updateStatus(), and ~Bladerf1OutputGui().
The documentation for this class was generated from the following files:
plugins/samplesink/bladerf1output/bladerf1outputgui.h
plugins/samplesink/bladerf1output/bladerf1outputgui.cpp