SDRAngel: AMBEDevicesDialog Class Reference
AMBEDevicesDialog Class Reference
#include <ambedevicesdialog.h>
Inherits QDialog.
Public Member Functions
AMBEDevicesDialog (AMBEEngine *ambeEngine, QWidget *parent=nullptr)
~AMBEDevicesDialog ()
Private Slots
void on_importSerial_clicked (bool checked)
void on_importAllSerial_clicked (bool checked)
void on_removeAmbeDevice_clicked (bool checked)
void on_refreshAmbeList_clicked (bool checked)
void on_clearAmbeList_clicked (bool checked)
void on_importAddress_clicked (bool checked)
Private Member Functions
void populateSerialList ()
void refreshInUseList ()
Private Attributes
Ui::AMBEDevicesDialog * ui
AMBEEngine * m_ambeEngine
Detailed Description
Definition at line 33 of file ambedevicesdialog.h.
Constructor & Destructor Documentation
AMBEDevicesDialog()
AMBEDevicesDialog::AMBEDevicesDialog (AMBEEngine * ambeEngine, QWidget * parent = nullptr) explicit
Definition at line 25 of file ambedevicesdialog.cpp.
References populateSerialList(), refreshInUseList(), and ui.
                                                                             :
     QDialog(parent),
     ui(new Ui::AMBEDevicesDialog),
     m_ambeEngine(ambeEngine)
 {
     ui->setupUi(this);
     populateSerialList();
     refreshInUseList();
 }
~AMBEDevicesDialog()
AMBEDevicesDialog::~AMBEDevicesDialog ()
Definition at line 35 of file ambedevicesdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
on_clearAmbeList_clicked
void AMBEDevicesDialog::on_clearAmbeList_clicked (bool checked) private slot
Definition at line 146 of file ambedevicesdialog.cpp.
References m_ambeEngine, AMBEEngine::releaseAll(), and ui.
 {
     if (ui->ambeDeviceRefs->count() == 0)
     {
         ui->statusText->setText("No active items");
         return;
     }
     m_ambeEngine->releaseAll();
     ui->ambeDeviceRefs->clear();
     ui->statusText->setText("All items released");
 }
on_importAddress_clicked
void AMBEDevicesDialog::on_importAddress_clicked (bool checked) private slot
Definition at line 159 of file ambedevicesdialog.cpp.
References arg(), m_ambeEngine, AMBEEngine::registerController(), and ui.
 {
     QString addressAndPort = ui->ambeAddressText->text();
     QList<QListWidgetItem*> foundItems = ui->ambeDeviceRefs->findItems(addressAndPort, Qt::MatchFixedString|Qt::MatchCaseSensitive);
     if (foundItems.size() == 0)
     {
         if (m_ambeEngine->registerController(addressAndPort.toStdString()))
         {
             ui->ambeDeviceRefs->addItem(addressAndPort);
             ui->statusText->setText(tr("%1 added").arg(addressAndPort));
         }
         else
         {
             ui->statusText->setText(tr("Cannot open %1").arg(addressAndPort));
         }
     }
     else
     {
         ui->statusText->setText("Address already in use");
     }
 }
on_importAllSerial_clicked
void AMBEDevicesDialog::on_importAllSerial_clicked (bool checked) private slot
Definition at line 99 of file ambedevicesdialog.cpp.
References arg(), i, m_ambeEngine, AMBEEngine::registerController(), and ui.
 {
     (void) checked;
     int count = 0;
     for (int i = 0; i < ui->ambeSerialDevices->count(); i++)
     {
         const QListWidgetItem *serialItem = ui->ambeSerialDevices->item(i);
         QString serialName = serialItem->text();
         QList<QListWidgetItem*> foundItems = ui->ambeDeviceRefs->findItems(serialName, Qt::MatchFixedString|Qt::MatchCaseSensitive);
         if (foundItems.size() == 0)
         {
             if (m_ambeEngine->registerController(serialName.toStdString()))
             {
                 ui->ambeDeviceRefs->addItem(serialName);
                 count++;
             }
         }
     }
     ui->statusText->setText(tr("%1 devices added").arg(count));
 }
on_importSerial_clicked
void AMBEDevicesDialog::on_importSerial_clicked (bool checked) private slot
Definition at line 67 of file ambedevicesdialog.cpp.
References arg(), m_ambeEngine, AMBEEngine::registerController(), and ui.
 {
     (void) checked;
     QListWidgetItem *serialItem = ui->ambeSerialDevices->currentItem();
     if (!serialItem)
     {
         ui->statusText->setText("No selection");
         return;
     }
     QString serialName = serialItem->text();
     QList<QListWidgetItem*> foundItems = ui->ambeDeviceRefs->findItems(serialName, Qt::MatchFixedString|Qt::MatchCaseSensitive);
     if (foundItems.size() == 0)
     {
         if (m_ambeEngine->registerController(serialName.toStdString()))
         {
             ui->ambeDeviceRefs->addItem(serialName);
             ui->statusText->setText(tr("%1 added").arg(serialName));
         }
         else
         {
             ui->statusText->setText(tr("Cannot open %1").arg(serialName));
         }
     }
     else
     {
         ui->statusText->setText("Device already in use");
     }
 }
on_refreshAmbeList_clicked
void AMBEDevicesDialog::on_refreshAmbeList_clicked (bool checked) private slot
Definition at line 140 of file ambedevicesdialog.cpp.
References refreshInUseList(), and ui.
 {
     refreshInUseList();
     ui->statusText->setText("In use refreshed");
 }
on_removeAmbeDevice_clicked
void AMBEDevicesDialog::on_removeAmbeDevice_clicked (bool checked) private slot
Definition at line 123 of file ambedevicesdialog.cpp.
References arg(), m_ambeEngine, refreshInUseList(), AMBEEngine::releaseController(), and ui.
 {
     (void) checked;
     QListWidgetItem *deviceItem = ui->ambeDeviceRefs->currentItem();
     if (!deviceItem)
     {
         ui->statusText->setText("No selection");
         return;
     }
     QString deviceName = deviceItem->text();
     m_ambeEngine->releaseController(deviceName.toStdString());
     ui->statusText->setText(tr("%1 removed").arg(deviceName));
     refreshInUseList();
 }
populateSerialList()
void AMBEDevicesDialog::populateSerialList () private
Definition at line 40 of file ambedevicesdialog.cpp.
References m_ambeEngine, AMBEEngine::scan(), and ui.
Referenced by AMBEDevicesDialog().
 {
     std::vector<QString> ambeSerialDevices;
     m_ambeEngine->scan(ambeSerialDevices);
     ui->ambeSerialDevices->clear();
     std::vector<QString>::const_iterator it = ambeSerialDevices.begin();
     for (; it != ambeSerialDevices.end(); ++it)
     {
         ui->ambeSerialDevices->addItem(QString(*it));
     }
 }
refreshInUseList()
void AMBEDevicesDialog::refreshInUseList () private
Definition at line 53 of file ambedevicesdialog.cpp.
References AMBEEngine::getDeviceRefs(), m_ambeEngine, and ui.
Referenced by AMBEDevicesDialog(), on_refreshAmbeList_clicked(), and on_removeAmbeDevice_clicked().
 {
     std::vector<QString> inUseDevices;
     m_ambeEngine->getDeviceRefs(inUseDevices);
     ui->ambeDeviceRefs->clear();
     std::vector<QString>::const_iterator it = inUseDevices.begin();
     for (; it != inUseDevices.end(); ++it)
     {
         qDebug("AMBEDevicesDialog::refreshInUseList: %s", qPrintable(*it));
         ui->ambeDeviceRefs->addItem(*it);
     }
 }
Member Data Documentation
m_ambeEngine
AMBEEngine* AMBEDevicesDialog::m_ambeEngine private
Definition at line 45 of file ambedevicesdialog.h.
Referenced by on_clearAmbeList_clicked(), on_importAddress_clicked(), on_importAllSerial_clicked(), on_importSerial_clicked(), on_removeAmbeDevice_clicked(), populateSerialList(), and refreshInUseList().
ui
Ui::AMBEDevicesDialog* AMBEDevicesDialog::ui private
Definition at line 44 of file ambedevicesdialog.h.
Referenced by AMBEDevicesDialog(), on_clearAmbeList_clicked(), on_importAddress_clicked(), on_importAllSerial_clicked(), on_importSerial_clicked(), on_refreshAmbeList_clicked(), on_removeAmbeDevice_clicked(), populateSerialList(), refreshInUseList(), and ~AMBEDevicesDialog().
The documentation for this class was generated from the following files:
sdrgui/gui/ambedevicesdialog.h
sdrgui/gui/ambedevicesdialog.cpp