SDRAngel: IntHalfbandFilterDB< AccuType, HBFilterOrder > Class Template Reference
IntHalfbandFilterDB< AccuType, HBFilterOrder > Class Template Reference
#include <inthalfbandfilterdb.h>
Public Member Functions
IntHalfbandFilterDB ()
bool workDecimateCenter (Sample *sample)
bool workInterpolateCenterZeroStuffing (Sample *sampleIn, Sample *SampleOut)
bool workInterpolateCenter (Sample *sampleIn, Sample *SampleOut)
bool workDecimateLowerHalf (Sample *sample)
bool workInterpolateLowerHalf (Sample *sampleIn, Sample *sampleOut)
bool workInterpolateLowerHalfZeroStuffing (Sample *sampleIn, Sample *sampleOut)
bool workDecimateUpperHalf (Sample *sample)
bool workInterpolateUpperHalf (Sample *sampleIn, Sample *sampleOut)
bool workInterpolateUpperHalfZeroStuffing (Sample *sampleIn, Sample *sampleOut)
void myDecimate (const Sample *sample1, Sample *sample2)
void myDecimate (AccuType x1, AccuType y1, AccuType *x2, AccuType *y2)
void myInterpolateZeroStuffing (Sample *sample1, Sample *sample2)
void myInterpolate (qint32 *x1, qint32 *y1, qint32 *x2, qint32 *y2)
void myInterpolateInf (qint32 *x1, qint32 *y1, qint32 *x2, qint32 *y2, qint32 *x3, qint32 *y3, qint32 *x4, qint32 *y4)
void myInterpolateSup (qint32 *x1, qint32 *y1, qint32 *x2, qint32 *y2, qint32 *x3, qint32 *y3, qint32 *x4, qint32 *y4)
Protected Member Functions
void storeSampleFixReal (const FixReal &sampleI, const FixReal &sampleQ)
void storeSampleAccu (AccuType x, AccuType y)
void advancePointer ()
void doFIR (Sample *sample)
void doFIR (qint32 *x, qint32 *y)
void doFIRAccu (AccuType *x, AccuType *y)
void doInterpolateFIR (Sample *sample)
void doInterpolateFIR (qint32 *x, qint32 *y)
Protected Attributes
AccuType m_samplesDB [2 *(HBFIRFilterTraits< HBFilterOrder >::hbOrder - 1)][2]
int m_ptr
int m_size
int m_state
Detailed Description
template<typename AccuType, uint32_t HBFilterOrder>
class IntHalfbandFilterDB< AccuType, HBFilterOrder >
Definition at line 30 of file inthalfbandfilterdb.h.
Constructor & Destructor Documentation
IntHalfbandFilterDB()
template<typename AccuType, uint32_t HBFilterOrder> IntHalfbandFilterDB< AccuType, HBFilterOrder >::IntHalfbandFilterDB () inline
Definition at line 32 of file inthalfbandfilterdb.h.
     {
         m_size = HBFIRFilterTraits<HBFilterOrder>::hbOrder - 1;
         for (int i = 0; i < m_size; i++)
         {
             m_samplesDB[i][0] = 0;
             m_samplesDB[i][1] = 0;
         }
         m_ptr = 0;
         m_state = 0;
     }
Member Function Documentation
advancePointer()
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::advancePointer () inline protected
Definition at line 687 of file inthalfbandfilterdb.h.
Referenced by IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myDecimate(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myInterpolateZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateLowerHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateUpperHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), and IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing().
     {
         m_ptr = m_ptr + 1 < m_size ? m_ptr + 1: 0;
     }
doFIR() [1/2]
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::doFIR (Sample * sample) inline protected
Definition at line 692 of file inthalfbandfilterdb.h.
Referenced by IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myDecimate(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myInterpolateZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateLowerHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateUpperHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), and IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing().
     {
         int a = m_ptr + m_size; // tip pointer
         int b = m_ptr + 1; // tail pointer
         AccuType iAcc = 0;
         AccuType qAcc = 0;
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += (m_samplesDB[a][0] + m_samplesDB[b][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             qAcc += (m_samplesDB[a][1] + m_samplesDB[b][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             a -= 2;
             b += 2;
         }
         iAcc += m_samplesDB[b-1][0] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         qAcc += m_samplesDB[b-1][1] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         sample->setReal(iAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1));
         sample->setImag(qAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1));
     }
doFIR() [2/2]
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::doFIR (qint32 * x, qint32 * y) inline protected
Definition at line 714 of file inthalfbandfilterdb.h.
     {
         int a = m_ptr + m_size; // tip pointer
         int b = m_ptr + 1; // tail pointer
         AccuType iAcc = 0;
         AccuType qAcc = 0;
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += (m_samplesDB[a][0] + m_samplesDB[b][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             qAcc += (m_samplesDB[a][1] + m_samplesDB[b][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             a -= 2;
             b += 2;
         }
         iAcc += m_samplesDB[b-1][0] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         qAcc += m_samplesDB[b-1][1] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         *x = iAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1); // HB_SHIFT incorrect do not loose the gained bit
         *y = qAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
     }
doFIRAccu()
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::doFIRAccu (AccuType * x, AccuType * y) inline protected
Definition at line 736 of file inthalfbandfilterdb.h.
Referenced by IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myDecimate().
     {
         int a = m_ptr + m_size; // tip pointer
         int b = m_ptr + 1; // tail pointer
         AccuType iAcc = 0;
         AccuType qAcc = 0;
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += (m_samplesDB[a][0] + m_samplesDB[b][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             qAcc += (m_samplesDB[a][1] + m_samplesDB[b][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             a -= 2;
             b += 2;
         }
         iAcc += m_samplesDB[b-1][0] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         qAcc += m_samplesDB[b-1][1] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         *x = iAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1); // HB_SHIFT incorrect do not loose the gained bit
         *y = qAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
     }
doInterpolateFIR() [1/2]
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::doInterpolateFIR (Sample * sample) inline protected
Definition at line 758 of file inthalfbandfilterdb.h.
Referenced by IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myInterpolate(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), and IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf().
     {
         qint16 a = m_ptr;
         qint16 b = m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder / 2) - 1;
         // go through samples in buffer
         AccuType iAcc = 0;
         AccuType qAcc = 0;
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += (m_samplesDB[a][0] + m_samplesDB[b][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             qAcc += (m_samplesDB[a][1] + m_samplesDB[b][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             a++;
             b--;
         }
         sample->setReal(iAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1));
         sample->setImag(qAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1));
     }
doInterpolateFIR() [2/2]
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::doInterpolateFIR (qint32 * x, qint32 * y) inline protected
Definition at line 779 of file inthalfbandfilterdb.h.
     {
         qint16 a = m_ptr;
         qint16 b = m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder / 2) - 1;
         // go through samples in buffer
         AccuType iAcc = 0;
         AccuType qAcc = 0;
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += (m_samplesDB[a][0] + m_samplesDB[b][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             qAcc += (m_samplesDB[a][1] + m_samplesDB[b][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             a++;
             b--;
         }
         *x = iAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
         *y = qAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
     }
myDecimate() [1/2]
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::myDecimate (const Sample * sample1, Sample * sample2) inline
Definition at line 565 of file inthalfbandfilterdb.h.
     {
         storeSampleFixReal((FixReal) sample1->real(), (FixReal) sample1->imag());
         advancePointer();
         storeSampleFixReal((FixReal) sample2->real(), (FixReal) sample2->imag());
         doFIR(sample2);
         advancePointer();
     }
myDecimate() [2/2]
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::myDecimate (AccuType x1, AccuType y1, AccuType * x2, AccuType * y2) inline
Definition at line 575 of file inthalfbandfilterdb.h.
     {
         storeSampleAccu(x1, y1);
         advancePointer();
         storeSampleAccu(*x2, *y2);
         doFIRAccu(x2, y2);
         advancePointer();
     }
myInterpolate()
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::myInterpolate (qint32 * x1, qint32 * y1, qint32 * x2, qint32 * y2) inline
Simple zero stuffing and filter Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 610 of file inthalfbandfilterdb.h.
Referenced by IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myInterpolateInf(), and IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myInterpolateSup().
     {
         // insert sample into ring double buffer
         m_samplesDB[m_ptr][0] = *x1;
         m_samplesDB[m_ptr][1] = *y1;
         m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = *x1;
         m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = *y1;
         // advance pointer
         if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
             m_ptr++;
         } else {
             m_ptr = 0;
         }
         // first output sample calculated with the middle peak
         *x1 = m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0];
         *y1 = m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1];
         // second sample calculated with the filter
         doInterpolateFIR(x2, y2);
     }
myInterpolateInf()
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::myInterpolateInf (qint32 * x1, qint32 * y1, qint32 * x2, qint32 * y2, qint32 * x3, qint32 * y3, qint32 * x4, qint32 * y4) inline
Definition at line 633 of file inthalfbandfilterdb.h.
     {
         myInterpolate(x1, y1, x2, y2);
         myInterpolate(x3, y3, x4, y4);
         // rotation
         qint32 x;
         x = *x1;
         *x1 = *y1;
         *y1 = -x;
         *x2 = -*x2;
         *y2 = -*y2;
         x = *x3;
         *x3 = -*y3;
         *y3 = x;
     }
myInterpolateSup()
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::myInterpolateSup (qint32 * x1, qint32 * y1, qint32 * x2, qint32 * y2, qint32 * x3, qint32 * y3, qint32 * x4, qint32 * y4) inline
Definition at line 649 of file inthalfbandfilterdb.h.
     {
         myInterpolate(x1, y1, x2, y2);
         myInterpolate(x3, y3, x4, y4);
         // rotation
         qint32 x;
         x = *x1;
         *x1 = -*y1;
         *y1 = x;
         *x2 = -*x2;
         *y2 = -*y2;
         x = *x3;
         *x3 = *y3;
         *y3 = -x;
     }
myInterpolateZeroStuffing()
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::myInterpolateZeroStuffing (Sample * sample1, Sample * sample2) inline
Simple zero stuffing and filter
Definition at line 586 of file inthalfbandfilterdb.h.
     {
         storeSampleFixReal((FixReal) sample1->real(), (FixReal) sample1->imag());
         doFIR(sample1);
         advancePointer();
         storeSampleFixReal((FixReal) 0, (FixReal) 0);
         doFIR(sample2);
         advancePointer();
     }
storeSampleAccu()
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::storeSampleAccu (AccuType x, AccuType y) inline protected
Definition at line 679 of file inthalfbandfilterdb.h.
Referenced by IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myDecimate().
     {
         m_samplesDB[m_ptr][0] = x;
         m_samplesDB[m_ptr][1] = y;
         m_samplesDB[m_ptr + m_size][0] = x;
         m_samplesDB[m_ptr + m_size][1] = y;
     }
storeSampleFixReal()
template<typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterDB< AccuType, HBFilterOrder >::storeSampleFixReal (const FixReal & sampleI, const FixReal & sampleQ) inline protected
Definition at line 671 of file inthalfbandfilterdb.h.
Referenced by IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myDecimate(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myInterpolateZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateLowerHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateUpperHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), and IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing().
     {
         m_samplesDB[m_ptr][0] = sampleI;
         m_samplesDB[m_ptr][1] = sampleQ;
         m_samplesDB[m_ptr + m_size][0] = sampleI;
         m_samplesDB[m_ptr + m_size][1] = sampleQ;
     }
workDecimateCenter()
template<typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterDB< AccuType, HBFilterOrder >::workDecimateCenter (Sample * sample) inline
Definition at line 47 of file inthalfbandfilterdb.h.
     {
         // insert sample into ring-buffer
         storeSampleFixReal((FixReal) sample->real(), (FixReal) sample->imag());
         switch(m_state)
         {
             case 0:
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workDecimateLowerHalf()
template<typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterDB< AccuType, HBFilterOrder >::workDecimateLowerHalf (Sample * sample) inline
Definition at line 168 of file inthalfbandfilterdb.h.
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSampleFixReal((FixReal) -sample->imag(), (FixReal) sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             case 1:
                 // insert sample into ring-buffer
                 storeSampleFixReal((FixReal) -sample->real(), (FixReal) -sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 2;
                 // tell caller we have a new sample
                 return true;
             case 2:
                 // insert sample into ring-buffer
                 storeSampleFixReal((FixReal) sample->imag(), (FixReal) -sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 3;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSampleFixReal((FixReal) sample->real(), (FixReal) sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workDecimateUpperHalf()
template<typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterDB< AccuType, HBFilterOrder >::workDecimateUpperHalf (Sample * sample) inline
Definition at line 367 of file inthalfbandfilterdb.h.
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSampleFixReal((FixReal) sample->imag(), (FixReal) -sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             case 1:
                 // insert sample into ring-buffer
                 storeSampleFixReal((FixReal) -sample->real(), (FixReal) -sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 2;
                 // tell caller we have a new sample
                 return true;
             case 2:
                 // insert sample into ring-buffer
                 storeSampleFixReal((FixReal) -sample->imag(), (FixReal) sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 3;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSampleFixReal((FixReal) sample->real(), (FixReal) sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workInterpolateCenter()
template<typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterDB< AccuType, HBFilterOrder >::workInterpolateCenter (Sample * sampleIn, Sample * SampleOut) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 107 of file inthalfbandfilterdb.h.
     {
         switch(m_state)
         {
         case 0:
             // return the middle peak
             SampleOut->setReal(m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]);
             SampleOut->setImag(m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);
             m_state = 1;  // next state
             return false; // tell caller we didn't consume the sample
         default:
             // calculate with non null samples
             doInterpolateFIR(SampleOut);
             // insert sample into ring double buffer
             m_samplesDB[m_ptr][0] = sampleIn->real();
             m_samplesDB[m_ptr][1] = sampleIn->imag();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 0; // next state
             return true; // tell caller we consumed the sample
         }
     }
workInterpolateCenterZeroStuffing()
template<typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterDB< AccuType, HBFilterOrder >::workInterpolateCenterZeroStuffing (Sample * sampleIn, Sample * SampleOut) inline
Definition at line 76 of file inthalfbandfilterdb.h.
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSampleFixReal((FixReal) 0, (FixReal) 0);
                 // save result
                 doFIR(SampleOut);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we didn't consume the sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSampleFixReal((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
                 // save result
                 doFIR(SampleOut);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we consumed the sample
                 return true;
         }
     }
workInterpolateLowerHalf()
template<typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterDB< AccuType, HBFilterOrder >::workInterpolateLowerHalf (Sample * sampleIn, Sample * sampleOut) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 219 of file inthalfbandfilterdb.h.
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // return the middle peak
             sampleOut->setReal(m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);  // imag
             sampleOut->setImag(-m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]); // - real
             m_state = 1;  // next state
             return false; // tell caller we didn't consume the sample
         case 1:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // insert sample into ring double buffer
             m_samplesDB[m_ptr][0] = sampleIn->real();
             m_samplesDB[m_ptr][1] = sampleIn->imag();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 2; // next state
             return true; // tell caller we consumed the sample
         case 2:
             // return the middle peak
             sampleOut->setReal(-m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);  // - imag
             sampleOut->setImag(m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]); // real
             m_state = 3;  // next state
             return false; // tell caller we didn't consume the sample
         default:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // insert sample into ring double buffer
             m_samplesDB[m_ptr][0] = sampleIn->real();
             m_samplesDB[m_ptr][1] = sampleIn->imag();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 0; // next state
             return true; // tell caller we consumed the sample
         }
     }
workInterpolateLowerHalfZeroStuffing()
template<typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterDB< AccuType, HBFilterOrder >::workInterpolateLowerHalfZeroStuffing (Sample * sampleIn, Sample * sampleOut) inline
Definition at line 286 of file inthalfbandfilterdb.h.
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // insert sample into ring-buffer
             storeSampleFixReal((FixReal) 0, (FixReal) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(s.imag());
             sampleOut->setImag(-s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 1;
             // tell caller we didn't consume the sample
             return false;
         case 1:
             // insert sample into ring-buffer
             storeSampleFixReal((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 2;
             // tell caller we consumed the sample
             return true;
         case 2:
             // insert sample into ring-buffer
             storeSampleFixReal((FixReal) 0, (FixReal) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.imag());
             sampleOut->setImag(s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 3;
             // tell caller we didn't consume the sample
             return false;
         default:
             // insert sample into ring-buffer
             storeSampleFixReal((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 0;
             // tell caller we consumed the sample
             return true;
         }
     }
workInterpolateUpperHalf()
template<typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterDB< AccuType, HBFilterOrder >::workInterpolateUpperHalf (Sample * sampleIn, Sample * sampleOut) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 418 of file inthalfbandfilterdb.h.
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // return the middle peak
             sampleOut->setReal(-m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]); // - imag
             sampleOut->setImag(m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]); // + real
             m_state = 1;  // next state
             return false; // tell caller we didn't consume the sample
         case 1:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // insert sample into ring double buffer
             m_samplesDB[m_ptr][0] = sampleIn->real();
             m_samplesDB[m_ptr][1] = sampleIn->imag();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 2; // next state
             return true; // tell caller we consumed the sample
         case 2:
             // return the middle peak
             sampleOut->setReal(m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);  // + imag
             sampleOut->setImag(-m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]);   // - real
             m_state = 3;  // next state
             return false; // tell caller we didn't consume the sample
         default:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // insert sample into ring double buffer
             m_samplesDB[m_ptr][0] = sampleIn->real();
             m_samplesDB[m_ptr][1] = sampleIn->imag();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 0; // next state
             return true; // tell caller we consumed the sample
         }
     }
workInterpolateUpperHalfZeroStuffing()
template<typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterDB< AccuType, HBFilterOrder >::workInterpolateUpperHalfZeroStuffing (Sample * sampleIn, Sample * sampleOut) inline
Definition at line 485 of file inthalfbandfilterdb.h.
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // insert sample into ring-buffer
             storeSampleFixReal((FixReal) 0, (FixReal) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.imag());
             sampleOut->setImag(s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 1;
             // tell caller we didn't consume the sample
             return false;
         case 1:
             // insert sample into ring-buffer
             storeSampleFixReal((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 2;
             // tell caller we consumed the sample
             return true;
         case 2:
             // insert sample into ring-buffer
             storeSampleFixReal((FixReal) 0, (FixReal) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(s.imag());
             sampleOut->setImag(-s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 3;
             // tell caller we didn't consume the sample
             return false;
         default:
             // insert sample into ring-buffer
             storeSampleFixReal((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 0;
             // tell caller we consumed the sample
             return true;
         }
     }
Member Data Documentation
m_ptr
template<typename AccuType, uint32_t HBFilterOrder> int IntHalfbandFilterDB< AccuType, HBFilterOrder >::m_ptr protected
Definition at line 667 of file inthalfbandfilterdb.h.
Referenced by IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::doInterpolateFIR(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::IntHalfbandFilterDB(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myInterpolate(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::storeSampleAccu(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::storeSampleFixReal(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), and IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf().
m_samplesDB
template<typename AccuType, uint32_t HBFilterOrder> AccuType IntHalfbandFilterDB< AccuType, HBFilterOrder >::m_samplesDB[2 *(HBFIRFilterTraits< HBFilterOrder >::hbOrder - 1)][2] protected
Definition at line 666 of file inthalfbandfilterdb.h.
Referenced by IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::doFIR(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::doFIRAccu(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::doInterpolateFIR(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::IntHalfbandFilterDB(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myInterpolate(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::storeSampleAccu(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::storeSampleFixReal(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), and IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf().
m_size
template<typename AccuType, uint32_t HBFilterOrder> int IntHalfbandFilterDB< AccuType, HBFilterOrder >::m_size protected
Definition at line 668 of file inthalfbandfilterdb.h.
Referenced by IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::doFIR(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::doFIRAccu(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::IntHalfbandFilterDB(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::storeSampleAccu(), and IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::storeSampleFixReal().
m_state
template<typename AccuType, uint32_t HBFilterOrder> int IntHalfbandFilterDB< AccuType, HBFilterOrder >::m_state protected
Definition at line 669 of file inthalfbandfilterdb.h.
Referenced by IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::IntHalfbandFilterDB(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateLowerHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateUpperHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf(), and IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing().
The documentation for this class was generated from the following file:
sdrbase/dsp/inthalfbandfilterdb.h