SDRAngel: UpChannelizer Class Reference
UpChannelizer Class Reference
#include <upchannelizer.h>
Classes
struct FilterStage
class MsgChannelizerNotification
class MsgSetChannelizer
Signals
void outputSampleRateChanged ()
Public Member Functions
UpChannelizer (BasebandSampleSource *sampleSink)
virtual ~UpChannelizer ()
void configure (MessageQueue *messageQueue, int sampleRate, int centerFrequency)
void set (MessageQueue *messageQueue, unsigned int log2Interp, unsigned int filterChainHash)
int getOutputSampleRate () const
virtual void start ()
virtual void stop ()
virtual void pull (Sample &sample)
virtual void pullAudio (int nbSamples)
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
Public Member Functions inherited from BasebandSampleSource
BasebandSampleSource ()
virtual ~BasebandSampleSource ()
void feed (SampleSourceFifo *sampleFifo, int nbSamples)
SampleSourceFifo & getSampleSourceFifo ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
void setDeviceSampleSourceFifo (SampleSourceFifo *deviceSampleFifo)
Protected Types
typedef std::vector< FilterStage * > FilterStages
Protected Member Functions
void applyConfiguration ()
void applySetting (unsigned int log2Decim, unsigned int filterChainHash)
bool signalContainsChannel (Real sigStart, Real sigEnd, Real chanStart, Real chanEnd) const
Real createFilterChain (Real sigStart, Real sigEnd, Real chanStart, Real chanEnd)
double setFilterChain (const std::vector< unsigned int > &stageIndexes)
returns offset in ratio of sample rate
void freeFilterChain ()
Protected Member Functions inherited from BasebandSampleSource
void handleWriteToFifo (SampleSourceFifo *sampleFifo, int nbSamples)
Protected Attributes
FilterStages m_filterStages
bool m_filterChainSetMode
std::vector< Sample > m_stageSamples
BasebandSampleSource * m_sampleSource
Modulator.
int m_outputSampleRate
int m_requestedInputSampleRate
int m_requestedCenterFrequency
int m_currentInputSampleRate
int m_currentCenterFrequency
SampleVector m_sampleBuffer
Sample m_sampleIn
QMutex m_mutex
Protected Attributes inherited from BasebandSampleSource
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
SampleSourceFifo m_sampleFifo
Internal FIFO for multi-channel processing.
SampleSourceFifo * m_deviceSampleFifo
Reference to the device FIFO for single channel processing.
Additional Inherited Members
Protected Slots inherited from BasebandSampleSource
void handleInputMessages ()
void handleWriteToFifo (int nbSamples)
void handleWriteToDeviceFifo (int nbSamples)
Detailed Description
Definition at line 37 of file upchannelizer.h.
Member Typedef Documentation
FilterStages
typedef std::vector<FilterStage*> UpChannelizer::FilterStages protected
Definition at line 123 of file upchannelizer.h.
Constructor & Destructor Documentation
UpChannelizer()
UpChannelizer::UpChannelizer (BasebandSampleSource * sampleSink)
Definition at line 31 of file upchannelizer.cpp.
                                                                :
     m_filterChainSetMode(false),
     m_sampleSource(sampleSource),
     m_outputSampleRate(0),
     m_requestedInputSampleRate(0),
     m_requestedCenterFrequency(0),
     m_currentInputSampleRate(0),
     m_currentCenterFrequency(0)
 {
     QString name = "UpChannelizer(" + m_sampleSource->objectName() + ")";
     setObjectName(name);
 }
~UpChannelizer()
UpChannelizer::~UpChannelizer () virtual
Definition at line 44 of file upchannelizer.cpp.
References freeFilterChain().
 {
     freeFilterChain();
 }
Member Function Documentation
applyConfiguration()
void UpChannelizer::applyConfiguration () protected
Definition at line 194 of file upchannelizer.cpp.
References UpChannelizer::MsgChannelizerNotification::create(), createFilterChain(), freeFilterChain(), BasebandSampleSource::getInputMessageQueue(), m_currentCenterFrequency, m_currentInputSampleRate, m_filterChainSetMode, m_filterStages, m_mutex, m_outputSampleRate, m_requestedCenterFrequency, m_requestedInputSampleRate, m_sampleSource, and MessageQueue::push().
Referenced by handleMessage().
 {
     m_filterChainSetMode = false;
     if (m_outputSampleRate == 0)
     {
         qDebug() << "UpChannelizer::applyConfiguration: aborting (out=0):"
                 << " out =" << m_outputSampleRate
                 << ", req =" << m_requestedInputSampleRate
                 << ", in =" << m_currentInputSampleRate
                 << ", fc =" << m_currentCenterFrequency;
         return;
     }
     m_mutex.lock();
     freeFilterChain();
     m_currentCenterFrequency = createFilterChain(
         m_outputSampleRate / -2, m_outputSampleRate / 2,
         m_requestedCenterFrequency - m_requestedInputSampleRate / 2, m_requestedCenterFrequency + m_requestedInputSampleRate / 2);
     m_mutex.unlock();
     m_currentInputSampleRate = m_outputSampleRate / (1 << m_filterStages.size());
     qDebug() << "UpChannelizer::applyConfiguration:"
             << " out=" << m_outputSampleRate
             << ", req=" << m_requestedInputSampleRate
             << ", in=" << m_currentInputSampleRate
             << ", fc=" << m_currentCenterFrequency;
     if (m_sampleSource != 0)
     {
         MsgChannelizerNotification *notif = MsgChannelizerNotification::create(m_outputSampleRate, m_currentInputSampleRate, m_currentCenterFrequency);
         m_sampleSource->getInputMessageQueue()->push(notif);
     }
 }
applySetting()
void UpChannelizer::applySetting (unsigned int log2Decim, unsigned int filterChainHash) protected
Definition at line 234 of file upchannelizer.cpp.
References HBFilterChainConverter::convertToIndexes(), UpChannelizer::MsgChannelizerNotification::create(), UpChannelizer::FilterStage::FilterStage(), freeFilterChain(), BasebandSampleSource::getInputMessageQueue(), m_currentCenterFrequency, m_currentInputSampleRate, m_filterChainSetMode, m_filterStages, m_mutex, m_outputSampleRate, m_requestedCenterFrequency, m_requestedInputSampleRate, m_sampleSource, MessageQueue::push(), and setFilterChain().
Referenced by handleMessage().
 {
     m_filterChainSetMode = true;
     std::vector<unsigned int> stageIndexes;
     m_currentCenterFrequency = m_outputSampleRate * HBFilterChainConverter::convertToIndexes(log2Interp, filterChainHash, stageIndexes);
     m_requestedCenterFrequency = m_currentCenterFrequency;
     m_mutex.lock();
     freeFilterChain();
     m_currentCenterFrequency = m_outputSampleRate * setFilterChain(stageIndexes);
     m_mutex.unlock();
     m_currentInputSampleRate = m_outputSampleRate / (1 << m_filterStages.size());
     m_requestedInputSampleRate = m_currentInputSampleRate;
     qDebug() << "UpChannelizer::applySetting in=" << m_outputSampleRate
             << ", out=" << m_currentInputSampleRate
             << ", fc=" << m_currentCenterFrequency;
     if (m_sampleSource != 0)
     {
         MsgChannelizerNotification *notif = MsgChannelizerNotification::create(m_outputSampleRate, m_currentInputSampleRate, m_currentCenterFrequency);
         m_sampleSource->getInputMessageQueue()->push(notif);
     }
 }
configure()
void UpChannelizer::configure (MessageQueue * messageQueue, int sampleRate, int centerFrequency)
Definition at line 49 of file upchannelizer.cpp.
References MessageQueue::push().
Referenced by UDPSource::handleMessage(), AMMod::handleMessage(), WFMMod::handleMessage(), NFMMod::handleMessage(), SSBMod::handleMessage(), FreeDVMod::handleMessage(), and ATVMod::handleMessage().
 {
     Message* cmd = new DSPConfigureChannelizer(sampleRate, centerFrequency);
     messageQueue->push(cmd);
 }
createFilterChain()
Real UpChannelizer::createFilterChain (Real sigStart, Real sigEnd, Real chanStart, Real chanEnd) protected
Definition at line 315 of file upchannelizer.cpp.
References UpChannelizer::FilterStage::FilterStage(), m_filterStages, m_stageSamples, UpChannelizer::FilterStage::ModeCenter, UpChannelizer::FilterStage::ModeLowerHalf, UpChannelizer::FilterStage::ModeUpperHalf, and signalContainsChannel().
Referenced by applyConfiguration().
 {
     Real sigBw = sigEnd - sigStart;
     Real rot = sigBw / 4;
     Sample s;
     qDebug() << "UpChannelizer::createFilterChain: start:"
             << " sig: ["  << sigStart << ":" << sigEnd << "]"
             << " BW: " << sigBw
             << " chan: [" << chanStart << ":" << chanEnd << "]"
             << " rot: " << rot;
     // check if it fits into the left half
     if(signalContainsChannel(sigStart, sigStart + sigBw / 2.0, chanStart, chanEnd))
     {
         qDebug() << "UpChannelizer::createFilterChain: take left half (rotate by +1/4 and decimate by 2):"
                 << " [" << m_filterStages.size() << "]"
                 << " sig: ["  << sigStart << ":" << sigStart + sigBw / 2.0 << "]";
         m_filterStages.push_back(new FilterStage(FilterStage::ModeLowerHalf));
         m_stageSamples.push_back(s);
         return createFilterChain(sigStart, sigStart + sigBw / 2.0, chanStart, chanEnd);
     }
     // check if it fits into the right half
     if(signalContainsChannel(sigEnd - sigBw / 2.0f, sigEnd, chanStart, chanEnd))
     {
         qDebug() << "UpChannelizer::createFilterChain: take right half (rotate by -1/4 and decimate by 2):"
                 << " [" << m_filterStages.size() << "]"
                 << " sig: ["  << sigEnd - sigBw / 2.0f << ":" << sigEnd << "]";
         m_filterStages.push_back(new FilterStage(FilterStage::ModeUpperHalf));
         m_stageSamples.push_back(s);
         return createFilterChain(sigEnd - sigBw / 2.0f, sigEnd, chanStart, chanEnd);
     }
     // check if it fits into the center
     // Was: if(signalContainsChannel(sigStart + rot + safetyMargin, sigStart + rot + sigBw / 2.0f - safetyMargin, chanStart, chanEnd)) {
     if(signalContainsChannel(sigStart + rot, sigEnd - rot, chanStart, chanEnd))
     {
         qDebug() << "UpChannelizer::createFilterChain: take center half (decimate by 2):"
                 << " [" << m_filterStages.size() << "]"
                 << " sig: ["  << sigStart + rot << ":" << sigEnd - rot << "]";
         m_filterStages.push_back(new FilterStage(FilterStage::ModeCenter));
         m_stageSamples.push_back(s);
         // Was: return createFilterChain(sigStart + rot, sigStart + sigBw / 2.0f + rot, chanStart, chanEnd);
         return createFilterChain(sigStart + rot, sigEnd - rot, chanStart, chanEnd);
     }
     Real ofs = ((chanEnd - chanStart) / 2.0 + chanStart) - ((sigEnd - sigStart) / 2.0 + sigStart);
     qDebug() << "UpChannelizer::createFilterChain: complete:"
             << " #stages: " << m_filterStages.size()
             << " BW: "  << sigBw
             << " ofs: " << ofs;
     return ofs;
 }
freeFilterChain()
void UpChannelizer::freeFilterChain () protected
Definition at line 408 of file upchannelizer.cpp.
References m_filterStages, and m_stageSamples.
Referenced by applyConfiguration(), applySetting(), and ~UpChannelizer().
 {
     for(FilterStages::iterator it = m_filterStages.begin(); it != m_filterStages.end(); ++it)
         delete *it;
     m_filterStages.clear();
     m_stageSamples.clear();
 }
getOutputSampleRate()
int UpChannelizer::getOutputSampleRate () const inline
Definition at line 89 of file upchannelizer.h.
Referenced by ATVMod::handleMessage().
 { return m_outputSampleRate; }
handleMessage()
bool UpChannelizer::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSource.
Definition at line 133 of file upchannelizer.cpp.
References applyConfiguration(), applySetting(), DSPConfigureChannelizer::getCenterFrequency(), UpChannelizer::MsgSetChannelizer::getFilterChainHash(), Message::getIdentifier(), BasebandSampleSource::getInputMessageQueue(), UpChannelizer::MsgSetChannelizer::getLog2Interp(), DSPSignalNotification::getSampleRate(), DSPConfigureChannelizer::getSampleRate(), m_filterChainSetMode, m_outputSampleRate, m_requestedCenterFrequency, m_requestedInputSampleRate, m_sampleSource, Message::match(), outputSampleRateChanged(), and MessageQueue::push().
 {
     qDebug() << "UpChannelizer::handleMessage: " << cmd.getIdentifier();
     // TODO: apply changes only if input sample rate or requested output sample rate change. Change of center frequency has no impact.
     if (DSPSignalNotification::match(cmd))
     {
         DSPSignalNotification& notif = (DSPSignalNotification&) cmd;
         m_outputSampleRate = notif.getSampleRate();
         qDebug() << "UpChannelizer::handleMessage: DSPSignalNotification: m_outputSampleRate: " << m_outputSampleRate;
         if (!m_filterChainSetMode) {
             applyConfiguration();
         }
         if (m_sampleSource != 0)
         {
             DSPSignalNotification* rep = new DSPSignalNotification(notif); // make a copy
             m_sampleSource->getInputMessageQueue()->push(rep);
         }
         emit outputSampleRateChanged();
         return true;
     }
     else if (DSPConfigureChannelizer::match(cmd))
     {
         DSPConfigureChannelizer& chan = (DSPConfigureChannelizer&) cmd;
         m_requestedInputSampleRate = chan.getSampleRate();
         m_requestedCenterFrequency = chan.getCenterFrequency();
         qDebug() << "UpChannelizer::handleMessage: DSPConfigureChannelizer:"
                 << " m_requestedInputSampleRate: " << m_requestedInputSampleRate
                 << " m_requestedCenterFrequency: " << m_requestedCenterFrequency;
         applyConfiguration();
         return true;
     }
     else if (MsgSetChannelizer::match(cmd))
     {
         MsgSetChannelizer& chan = (MsgSetChannelizer&) cmd;
         qDebug() << "UpChannelizer::handleMessage: MsgSetChannelizer";
         applySetting(chan.getLog2Interp(), chan.getFilterChainHash());
         return true;
     }
     else
     {
         return false;
 //        if (m_sampleSource != 0)
 //        {
 //            return m_sampleSource->handleMessage(cmd);
 //        }
 //        else
 //        {
 //            return false;
 //        }
     }
 }
outputSampleRateChanged
void UpChannelizer::outputSampleRateChanged () signal
Referenced by handleMessage().
pull()
void UpChannelizer::pull (Sample & sample) virtual
Implements BasebandSampleSource.
Definition at line 61 of file upchannelizer.cpp.
References m_filterStages, m_mutex, m_sampleBuffer, m_sampleIn, m_sampleSource, m_stageSamples, and BasebandSampleSource::pull().
 {
     if(m_sampleSource == 0) {
         m_sampleBuffer.clear();
         return;
     }
     if (m_filterStages.size() == 0) // optimization when no downsampling is done anyway
     {
         m_sampleSource->pull(sample);
     }
     else
     {
         m_mutex.lock();
         FilterStages::iterator stage = m_filterStages.begin();
         std::vector<Sample>::iterator stageSample = m_stageSamples.begin();
         for (; stage != m_filterStages.end(); ++stage, ++stageSample)
         {
             if(stage == m_filterStages.end() - 1)
             {
                 if ((*stage)->work(&m_sampleIn, &(*stageSample)))
                 {
                     m_sampleSource->pull(m_sampleIn); // get new input sample
                 }
             }
             else
             {
                 if (!(*stage)->work(&(*(stageSample+1)), &(*stageSample)))
                 {
                     break;
                 }
             }
         }
         sample = *m_stageSamples.begin();
 //      for (; stage != m_filterStages.end(); ++stage)
 //      {
 //          // let's make it work for one stage only (96 kS/s < SR < 192 kS/s)
 //          if(stage == m_filterStages.end() - 1)
 //          {
 //              if ((*stage)->work(&m_sampleIn, &sample))
 //              {
 //                  m_sampleSource->pull(m_sampleIn); // get new input sample
 //              }
 //          }
 //      }
         m_mutex.unlock();
     }
 }
pullAudio()
virtual void UpChannelizer::pullAudio (int nbSamples) inline virtual
Reimplemented from BasebandSampleSource.
Definition at line 94 of file upchannelizer.h.
 { if (m_sampleSource) m_sampleSource->pullAudio(nbSamples); }
set()
void UpChannelizer::set (MessageQueue * messageQueue, unsigned int log2Interp, unsigned int filterChainHash)
Definition at line 55 of file upchannelizer.cpp.
References MessageQueue::push().
Referenced by LocalSource::handleMessage(), and FileSource::handleMessage().
 {
     Message* cmd = new MsgSetChannelizer(log2Interp, filterChainHash);
     messageQueue->push(cmd);
 }
setFilterChain()
double UpChannelizer::setFilterChain (const std::vector< unsigned int > & stageIndexes) protected
returns offset in ratio of sample rate
Definition at line 372 of file upchannelizer.cpp.
References UpChannelizer::FilterStage::FilterStage(), m_filterStages, m_stageSamples, UpChannelizer::FilterStage::ModeCenter, UpChannelizer::FilterStage::ModeLowerHalf, and UpChannelizer::FilterStage::ModeUpperHalf.
Referenced by applySetting().
 {
     // filters are described from lower to upper level but the chain is constructed the other way round
     std::vector<unsigned int>::const_reverse_iterator rit = stageIndexes.rbegin();
     double ofs = 0.0, ofs_stage = 0.25;
     Sample s;
     // Each index is a base 3 number with 0 = low, 1 = center, 2 = high
     // Functions at upper level will convert a number to base 3 to describe the filter chain. Common converting
     // algorithms will go from LSD to MSD. This explains the reverse order.
     for (; rit != stageIndexes.rend(); ++rit)
     {
         if (*rit == 0)
         {
             m_filterStages.push_back(new FilterStage(FilterStage::ModeLowerHalf));
             m_stageSamples.push_back(s);
             ofs -= ofs_stage;
         }
         else if (*rit == 1)
         {
             m_filterStages.push_back(new FilterStage(FilterStage::ModeCenter));
             m_stageSamples.push_back(s);
         }
         else if (*rit == 2)
         {
             m_filterStages.push_back(new FilterStage(FilterStage::ModeUpperHalf));
             m_stageSamples.push_back(s);
             ofs += ofs_stage;
         }
         ofs_stage /= 2;
     }
     return ofs;
 }
signalContainsChannel()
bool UpChannelizer::signalContainsChannel (Real sigStart, Real sigEnd, Real chanStart, Real chanEnd) const protected
Definition at line 305 of file upchannelizer.cpp.
Referenced by createFilterChain().
 {
     //qDebug("   testing signal [%f, %f], channel [%f, %f]", sigStart, sigEnd, chanStart, chanEnd);
     if(sigEnd <= sigStart)
         return false;
     if(chanEnd <= chanStart)
         return false;
     return (sigStart <= chanStart) && (sigEnd >= chanEnd);
 }
start()
void UpChannelizer::start () virtual
Implements BasebandSampleSource.
Definition at line 115 of file upchannelizer.cpp.
References m_outputSampleRate, m_requestedCenterFrequency, m_requestedInputSampleRate, m_sampleSource, and BasebandSampleSource::start().
 {
     if (m_sampleSource != 0)
     {
         qDebug() << "UpChannelizer::start: thread: " << thread()
                 << " m_outputSampleRate: " << m_outputSampleRate
                 << " m_requestedInputSampleRate: " << m_requestedInputSampleRate
                 << " m_requestedCenterFrequency: " << m_requestedCenterFrequency;
         m_sampleSource->start();
     }
 }
stop()
void UpChannelizer::stop () virtual
Implements BasebandSampleSource.
Definition at line 127 of file upchannelizer.cpp.
References m_sampleSource, and BasebandSampleSource::stop().
 {
     if(m_sampleSource != 0)
         m_sampleSource->stop();
 }
Member Data Documentation
m_currentCenterFrequency
int UpChannelizer::m_currentCenterFrequency protected
Definition at line 132 of file upchannelizer.h.
Referenced by applyConfiguration(), and applySetting().
m_currentInputSampleRate
int UpChannelizer::m_currentInputSampleRate protected
Definition at line 131 of file upchannelizer.h.
Referenced by applyConfiguration(), and applySetting().
m_filterChainSetMode
bool UpChannelizer::m_filterChainSetMode protected
Definition at line 125 of file upchannelizer.h.
Referenced by applyConfiguration(), applySetting(), and handleMessage().
m_filterStages
FilterStages UpChannelizer::m_filterStages protected
Definition at line 124 of file upchannelizer.h.
Referenced by applyConfiguration(), applySetting(), createFilterChain(), freeFilterChain(), pull(), and setFilterChain().
m_mutex
QMutex UpChannelizer::m_mutex protected
Definition at line 135 of file upchannelizer.h.
Referenced by applyConfiguration(), applySetting(), and pull().
m_outputSampleRate
int UpChannelizer::m_outputSampleRate protected
Definition at line 128 of file upchannelizer.h.
Referenced by applyConfiguration(), applySetting(), handleMessage(), and start().
m_requestedCenterFrequency
int UpChannelizer::m_requestedCenterFrequency protected
Definition at line 130 of file upchannelizer.h.
Referenced by applyConfiguration(), applySetting(), handleMessage(), and start().
m_requestedInputSampleRate
int UpChannelizer::m_requestedInputSampleRate protected
Definition at line 129 of file upchannelizer.h.
Referenced by applyConfiguration(), applySetting(), handleMessage(), and start().
m_sampleBuffer
SampleVector UpChannelizer::m_sampleBuffer protected
Definition at line 133 of file upchannelizer.h.
Referenced by pull().
m_sampleIn
Sample UpChannelizer::m_sampleIn protected
Definition at line 134 of file upchannelizer.h.
Referenced by pull().
m_sampleSource
BasebandSampleSource* UpChannelizer::m_sampleSource protected
Modulator.
Definition at line 127 of file upchannelizer.h.
Referenced by applyConfiguration(), applySetting(), handleMessage(), pull(), start(), and stop().
m_stageSamples
std::vector<Sample> UpChannelizer::m_stageSamples protected
Definition at line 126 of file upchannelizer.h.
Referenced by createFilterChain(), freeFilterChain(), pull(), and setFilterChain().
The documentation for this class was generated from the following files:
sdrbase/dsp/upchannelizer.h
sdrbase/dsp/upchannelizer.cpp