SDRAngel: BasebandSampleSink Class Reference
BasebandSampleSink Class Reference abstract
#include <basebandsamplesink.h>
Classes
class MsgThreadedSink
Public Member Functions
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
virtual void start ()=0
virtual void stop ()=0
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool positiveOnly)=0
virtual bool handleMessage (const Message &cmd)=0
Processing of a message. Returns true if message has actually been processed.
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Protected Slots
void handleInputMessages ()
Protected Attributes
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 30 of file basebandsamplesink.h.
Constructor & Destructor Documentation
BasebandSampleSink()
BasebandSampleSink::BasebandSampleSink ()
Definition at line 5 of file basebandsamplesink.cpp.
                                        :
     m_guiMessageQueue(0)
 {
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
 }
~BasebandSampleSink()
BasebandSampleSink::~BasebandSampleSink () virtual
Definition at line 11 of file basebandsamplesink.cpp.
 {
 }
Member Function Documentation
feed()
virtual void BasebandSampleSink::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool positiveOnly) pure virtual
Implemented in ScopeVis, ATVDemod, DATVDemod, ChannelAnalyzer, FreeDVDemod, BFMDemod, FreqTracker, NFMDemod, SSBDemod, RemoteSink, LocalSink, UDPSink, DSDDemod, AMDemod, WFMDemod, LoRaDemod, DownChannelizer, SpectrumVis, FileRecord, ScopeVisXY, SpectrumScopeComboVis, and NullSink.
Referenced by DownChannelizer::feed(), LoRaDemod::feed(), DSDDemod::feed(), UDPSink::feed(), BFMDemod::feed(), FreeDVDemod::feed(), ChannelAnalyzer::feed(), ATVDemod::feed(), ThreadedBasebandSampleSinkFifo::handleFifoData(), DSPDeviceSinkEngine::handleForwardToSpectrumSink(), DSPDeviceMIMOEngine::handleForwardToSpectrumSink(), UDPSource::modulateSample(), SSBDemod::processOneSample(), FreeDVMod::pullAF(), SSBMod::pullAF(), DSPDeviceMIMOEngine::work(), and DSPDeviceMIMOEngine::workSampleSink().
getInputMessageQueue()
MessageQueue* BasebandSampleSink::getInputMessageQueue () inline
Get the queue for asynchronous inbound communication.
Definition at line 62 of file basebandsamplesink.h.
Referenced by ScopeVis::addTrace(), ScopeVis::addTrigger(), AMDemod::AMDemod(), LocalSinkGUI::applyChannelSettings(), RemoteSinkGUI::applyChannelSettings(), DownChannelizer::applyConfiguration(), ATVDemodGUI::applyRFSettings(), DownChannelizer::applySetting(), WFMDemodGUI::applySettings(), LoRaDemodGUI::applySettings(), NFMDemodGUI::applySettings(), AMDemodGUI::applySettings(), SSBDemodGUI::applySettings(), FreqTrackerGUI::applySettings(), LocalSinkGUI::applySettings(), RemoteSinkGUI::applySettings(), BFMDemodGUI::applySettings(), ATVDemodGUI::applySettings(), UDPSinkGUI::applySettings(), ChannelAnalyzerGUI::applySettings(), FreeDVDemodGUI::applySettings(), DSDDemodGUI::applySettings(), DATVDemodGUI::applySettings(), WFMDemod::applySettings(), AMDemod::applySettings(), UDPSink::applySettings(), NFMDemod::applySettings(), DSDDemod::applySettings(), BFMDemod::applySettings(), SSBDemod::applySettings(), FreeDVDemod::applySettings(), DATVDemod::applySettings(), UDPSinkGUI::applySettingsImmediate(), ATVDemodGUI::ATVDemodGUI(), BFMDemod::BFMDemod(), BFMDemodGUI::BFMDemodGUI(), ScopeVis::changeTrace(), ScopeVis::changeTrigger(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), ScopeVis::configure(), FreqTracker::configureChannelizer(), DeviceUISet::DeviceUISet(), DSDDemod::DSDDemod(), ScopeVis::focusOnTrace(), ScopeVis::focusOnTrigger(), FreeDVDemod::FreeDVDemod(), FreeDVDemodGUI::FreeDVDemodGUI(), FreeDVModGUI::FreeDVModGUI(), ThreadedBasebandSampleSinkFifo::handleFifoData(), DownChannelizer::handleMessage(), LoRaDemod::handleMessage(), AMDemod::handleMessage(), WFMDemod::handleMessage(), DSDDemod::handleMessage(), LocalSink::handleMessage(), UDPSink::handleMessage(), RemoteSink::handleMessage(), SSBDemod::handleMessage(), NFMDemod::handleMessage(), BFMDemod::handleMessage(), FreeDVDemod::handleMessage(), ChannelAnalyzer::handleMessage(), DATVDemod::handleMessage(), ATVDemod::handleMessage(), LoRaDemodGUI::LoRaDemodGUI(), ScopeVis::moveTrace(), ScopeVis::moveTrigger(), NFMDemod::NFMDemod(), FreeDVDemodGUI::on_reSync_clicked(), UDPSinkGUI::onWidgetRolled(), ScopeVis::removeTrace(), ScopeVis::removeTrigger(), ScopeVis::setMemoryIndex(), ScopeVis::setOneShot(), SSBDemod::SSBDemod(), SSBDemodGUI::SSBDemodGUI(), SSBModGUI::SSBModGUI(), UDPSinkGUI::UDPSinkGUI(), UDPSourceGUI::UDPSourceGUI(), DSDDemodGUI::updateMyPosition(), and WFMDemod::WFMDemod().
getMessageQueueToGUI()
MessageQueue* BasebandSampleSink::getMessageQueueToGUI () inline
Definition at line 64 of file basebandsamplesink.h.
Referenced by FreeDVDemod::applyFreeDVMode(), ATVDemod::applySettings(), ATVDemod::channelSampleRateChanged(), DATVDemod::feed(), BFMDemod::handleMessage(), ChannelAnalyzer::handleMessage(), and NFMDemod::processOneSample().
 { return m_guiMessageQueue; }
handleInputMessages
void BasebandSampleSink::handleInputMessages () protected slot
Definition at line 15 of file basebandsamplesink.cpp.
References handleMessage(), m_inputMessageQueue, and MessageQueue::pop().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
virtual bool BasebandSampleSink::handleMessage (const Message & cmd) pure virtual
Processing of a message. Returns true if message has actually been processed.
Implemented in ScopeVis, ATVDemod, DATVDemod, ChannelAnalyzer, FreeDVDemod, BFMDemod, FreqTracker, NFMDemod, SSBDemod, RemoteSink, LocalSink, UDPSink, DSDDemod, AMDemod, WFMDemod, LoRaDemod, DownChannelizer, SpectrumVis, FileRecord, ScopeVisXY, SpectrumScopeComboVis, and NullSink.
Referenced by DSPDeviceSinkEngine::gotoInit(), handleInputMessages(), DSPDeviceMIMOEngine::handleInputMessages(), DownChannelizer::handleMessage(), LoRaDemod::handleMessage(), UDPSource::handleMessage(), UDPSink::handleMessage(), SSBDemod::handleMessage(), BFMDemod::handleMessage(), FreeDVDemod::handleMessage(), ATVDemod::handleMessage(), ThreadedBasebandSampleSink::handleSinkMessage(), DSPDeviceSourceEngine::handleSynchronousMessages(), DSPDeviceMIMOEngine::handleSynchronousMessages(), and ThreadedBasebandSampleSink::ThreadedBasebandSampleSink().
setMessageQueueToGUI()
virtual void BasebandSampleSink::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Definition at line 63 of file basebandsamplesink.h.
Referenced by AMDemodGUI::AMDemodGUI(), ATVDemodGUI::ATVDemodGUI(), BFMDemodGUI::BFMDemodGUI(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), DATVDemodGUI::DATVDemodGUI(), DSDDemodGUI::DSDDemodGUI(), FreeDVDemodGUI::FreeDVDemodGUI(), FreqTrackerGUI::FreqTrackerGUI(), LocalSinkGUI::LocalSinkGUI(), NFMDemodGUI::NFMDemodGUI(), RemoteSinkGUI::RemoteSinkGUI(), SSBDemodGUI::SSBDemodGUI(), UDPSinkGUI::UDPSinkGUI(), and WFMDemodGUI::WFMDemodGUI().
 { m_guiMessageQueue = queue; }
start()
virtual void BasebandSampleSink::start () pure virtual
Implemented in ScopeVis, ATVDemod, DATVDemod, ChannelAnalyzer, FreeDVDemod, BFMDemod, FreqTracker, NFMDemod, SSBDemod, RemoteSink, LocalSink, UDPSink, DSDDemod, AMDemod, WFMDemod, LoRaDemod, DownChannelizer, SpectrumVis, FileRecord, ScopeVisXY, SpectrumScopeComboVis, and NullSink.
Referenced by DSPDeviceSinkEngine::gotoRunning(), DSPDeviceSourceEngine::handleSynchronousMessages(), DSPDeviceMIMOEngine::handleSynchronousMessages(), ThreadedBasebandSampleSink::start(), and DownChannelizer::start().
stop()
virtual void BasebandSampleSink::stop () pure virtual
Implemented in ScopeVis, ATVDemod, DATVDemod, ChannelAnalyzer, FreeDVDemod, BFMDemod, FreqTracker, NFMDemod, SSBDemod, RemoteSink, LocalSink, UDPSink, DSDDemod, AMDemod, WFMDemod, LoRaDemod, DownChannelizer, SpectrumVis, FileRecord, ScopeVisXY, SpectrumScopeComboVis, and NullSink.
Referenced by DSPDeviceSinkEngine::gotoIdle(), DSPDeviceSinkEngine::handleSynchronousMessages(), DSPDeviceSourceEngine::handleSynchronousMessages(), DSPDeviceMIMOEngine::handleSynchronousMessages(), ThreadedBasebandSampleSink::stop(), and DownChannelizer::stop().
Member Data Documentation
m_guiMessageQueue
MessageQueue* BasebandSampleSink::m_guiMessageQueue protected
Input message queue to the GUI.
Definition at line 68 of file basebandsamplesink.h.
Referenced by SSBDemod::applyAudioSampleRate(), FreqTracker::configureChannelizer(), LocalSink::handleMessage(), RemoteSink::handleMessage(), AMDemod::webapiSettingsPutPatch(), LocalSink::webapiSettingsPutPatch(), UDPSink::webapiSettingsPutPatch(), RemoteSink::webapiSettingsPutPatch(), WFMDemod::webapiSettingsPutPatch(), NFMDemod::webapiSettingsPutPatch(), FreqTracker::webapiSettingsPutPatch(), DSDDemod::webapiSettingsPutPatch(), SSBDemod::webapiSettingsPutPatch(), FreeDVDemod::webapiSettingsPutPatch(), and BFMDemod::webapiSettingsPutPatch().
m_inputMessageQueue
MessageQueue BasebandSampleSink::m_inputMessageQueue protected
Queue for asynchronous inbound communication.
Definition at line 67 of file basebandsamplesink.h.
Referenced by AMDemod::applyAudioSampleRate(), NFMDemod::applyAudioSampleRate(), SSBDemod::applyAudioSampleRate(), FreeDVDemod::applyFreeDVMode(), LoRaDemod::deserialize(), AMDemod::deserialize(), WFMDemod::deserialize(), DSDDemod::deserialize(), LocalSink::deserialize(), UDPSink::deserialize(), RemoteSink::deserialize(), SSBDemod::deserialize(), NFMDemod::deserialize(), FreqTracker::deserialize(), BFMDemod::deserialize(), FreeDVDemod::deserialize(), handleInputMessages(), AMDemod::webapiSettingsPutPatch(), LocalSink::webapiSettingsPutPatch(), UDPSink::webapiSettingsPutPatch(), RemoteSink::webapiSettingsPutPatch(), WFMDemod::webapiSettingsPutPatch(), NFMDemod::webapiSettingsPutPatch(), FreqTracker::webapiSettingsPutPatch(), DSDDemod::webapiSettingsPutPatch(), SSBDemod::webapiSettingsPutPatch(), FreeDVDemod::webapiSettingsPutPatch(), and BFMDemod::webapiSettingsPutPatch().
The documentation for this class was generated from the following files:
sdrbase/dsp/basebandsamplesink.h
sdrbase/dsp/basebandsamplesink.cpp