SDRAngel: Blderf2InputPlugin Class Reference
Blderf2InputPlugin Class Reference
#include <bladerf2inputplugin.h>
Public Member Functions
Blderf2InputPlugin (QObject *parent=0)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "BladeRF2"
static const QString m_deviceTypeID = BLADERF2INPUT_DEVICE_TYPE_ID
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 30 of file bladerf2inputplugin.h.
Constructor & Destructor Documentation
Blderf2InputPlugin()
Blderf2InputPlugin::Blderf2InputPlugin (QObject * parent = 0) explicit
Definition at line 43 of file bladerf2inputplugin.cpp.
                                                       :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSourcePluginInstance()
DeviceSampleSource * Blderf2InputPlugin::createSampleSourcePluginInstance (const QString & sourceId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 145 of file bladerf2inputplugin.cpp.
References m_deviceTypeID.
 {
     if (sourceId == m_deviceTypeID)
     {
         BladeRF2Input *input = new BladeRF2Input(deviceAPI);
         return input;
     }
     else
     {
         return 0;
     }
 }
createSampleSourcePluginInstanceGUI()
PluginInstanceGUI * Blderf2InputPlugin::createSampleSourcePluginInstanceGUI (const QString & sourceId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 127 of file bladerf2inputplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSources().
 {
     if(sourceId == m_deviceTypeID)
     {
         BladeRF2InputGui* gui = new BladeRF2InputGui(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSources()
PluginInterface::SamplingDevices Blderf2InputPlugin::enumSampleSources () virtual
Reimplemented from PluginInterface.
Definition at line 58 of file bladerf2inputplugin.cpp.
References arg(), createSampleSourcePluginInstanceGUI(), i, m_deviceTypeID, m_hardwareID, PluginInterface::SamplingDevice::PhysicalDevice, and PluginInterface::SamplingDevice::StreamSingleRx.
 {
     SamplingDevices result;
     struct bladerf_devinfo *devinfo = 0;
     int count = bladerf_get_device_list(&devinfo);
     if (devinfo)
     {
         for(int i = 0; i < count; i++)
         {
             struct bladerf *dev;
             int status = bladerf_open_with_devinfo(&dev, &devinfo[i]);
             if (status == BLADERF_ERR_NODEV)
             {
                 qCritical("Blderf2InputPlugin::enumSampleSources: No device at index %d", i);
                 continue;
             }
             else if (status != 0)
             {
                 qCritical("Blderf2InputPlugin::enumSampleSources: Failed to open device at index %d", i);
                 continue;
             }
             const char *boardName = bladerf_get_board_name(dev);
             if (strcmp(boardName, "bladerf2") == 0)
             {
                 unsigned int nbRxChannels = bladerf_get_channel_count(dev, BLADERF_RX);
                 for (unsigned int j = 0; j < nbRxChannels; j++)
                 {
                     qDebug("Blderf2InputPlugin::enumSampleSources: device #%d (%s) channel %u", i, devinfo[i].serial, j);
                     QString displayedName(QString("BladeRF2[%1:%2] %3").arg(devinfo[i].instance).arg(j).arg(devinfo[i].serial));
                     result.append(SamplingDevice(displayedName,
                             m_hardwareID,
                             m_deviceTypeID,
                             QString(devinfo[i].serial),
                             i,
                             PluginInterface::SamplingDevice::PhysicalDevice,
                             PluginInterface::SamplingDevice::StreamSingleRx,
                             nbRxChannels,
                             j));
                 }
             }
             bladerf_close(dev);
         }
         bladerf_free_device_list(devinfo); // Valgrind memcheck
     }
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & Blderf2InputPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 48 of file bladerf2inputplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void Blderf2InputPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 53 of file bladerf2inputplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSource().
 {
     pluginAPI->registerSampleSource(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString Blderf2InputPlugin::m_deviceTypeID = BLADERF2INPUT_DEVICE_TYPE_ID static
Definition at line 49 of file bladerf2inputplugin.h.
Referenced by createSampleSourcePluginInstance(), createSampleSourcePluginInstanceGUI(), enumSampleSources(), and initPlugin().
m_hardwareID
const QString Blderf2InputPlugin::m_hardwareID = "BladeRF2" static
Definition at line 48 of file bladerf2inputplugin.h.
Referenced by enumSampleSources().
m_pluginDescriptor
const PluginDescriptor Blderf2InputPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("BladeRF2 Input"),
    QString("4.5.4"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 52 of file bladerf2inputplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesource/bladerf2input/bladerf2inputplugin.h
plugins/samplesource/bladerf2input/bladerf2inputplugin.cpp