SDRAngel: UDPSourceUDPHandler::MsgUDPAddressAndPort Class Reference
UDPSourceUDPHandler::MsgUDPAddressAndPort Class Reference
Public Member Functions
const QString & getAddress () const
quint16 getPort () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgUDPAddressAndPort * create (QString address, quint16 port)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgUDPAddressAndPort (QString address, quint16 port)
Private Attributes
QString m_address
quint16 m_port
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 68 of file udpsourceudphandler.h.
Constructor & Destructor Documentation
MsgUDPAddressAndPort()
UDPSourceUDPHandler::MsgUDPAddressAndPort::MsgUDPAddressAndPort (QString address, quint16 port) inline private
Definition at line 84 of file udpsourceudphandler.h.
References UDPSourceUDPHandler::advanceReadPointer(), UDPSourceUDPHandler::applyUDPLink(), UDPSourceUDPHandler::char(), UDPSourceUDPHandler::handleMessage(), UDPSourceUDPHandler::m_udpBlockSize, and UDPSourceUDPHandler::moveData().
Referenced by create().
                                                             :
             Message(),
             m_address(address),
             m_port(port)
         { }
Member Function Documentation
create()
static MsgUDPAddressAndPort* UDPSourceUDPHandler::MsgUDPAddressAndPort::create (QString address, quint16 port) inline static
Definition at line 75 of file udpsourceudphandler.h.
References MsgUDPAddressAndPort().
Referenced by UDPSourceUDPHandler::configureUDPLink().
         {
             return new MsgUDPAddressAndPort(address, port);
         }
getAddress()
const QString& UDPSourceUDPHandler::MsgUDPAddressAndPort::getAddress () const inline
Definition at line 72 of file udpsourceudphandler.h.
References m_address.
Referenced by UDPSourceUDPHandler::handleMessage().
 { return m_address; }
getPort()
quint16 UDPSourceUDPHandler::MsgUDPAddressAndPort::getPort () const inline
Definition at line 73 of file udpsourceudphandler.h.
References m_port.
Referenced by UDPSourceUDPHandler::handleMessage().
 { return m_port; }
Member Data Documentation
m_address
QString UDPSourceUDPHandler::MsgUDPAddressAndPort::m_address private
Definition at line 81 of file udpsourceudphandler.h.
Referenced by getAddress().
m_port
quint16 UDPSourceUDPHandler::MsgUDPAddressAndPort::m_port private
Definition at line 82 of file udpsourceudphandler.h.
Referenced by getPort().
The documentation for this class was generated from the following file:
plugins/channeltx/udpsource/udpsourceudphandler.h