SDRAngel: TestMIPlugin Class Reference
TestMIPlugin Class Reference
#include <testmiplugin.h>
Public Member Functions
TestMIPlugin (QObject *parent=NULL)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "TestMI"
static const QString m_deviceTypeID = TESTMI_DEVICE_TYPE_ID
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 28 of file testmiplugin.h.
Constructor & Destructor Documentation
TestMIPlugin()
TestMIPlugin::TestMIPlugin (QObject * parent = NULL) explicit
Definition at line 42 of file testmiplugin.cpp.
                                           :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleMIMOPluginInstance()
DeviceSampleMIMO * TestMIPlugin::createSampleMIMOPluginInstance (const QString & sourceId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 102 of file testmiplugin.cpp.
References m_deviceTypeID.
 {
     if (mimoId == m_deviceTypeID)
     {
         TestMI* input = new TestMI(deviceAPI);
         return input;
     }
     else
     {
         return nullptr;
     }
 }
createSampleMIMOPluginInstanceGUI()
PluginInstanceGUI * TestMIPlugin::createSampleMIMOPluginInstanceGUI (const QString & sourceId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 87 of file testmiplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleMIMO().
 {
     if (sourceId == m_deviceTypeID) {
         TestMIGui* gui = new TestMIGui(deviceUISet);
         *widget = gui;
         return gui;
     } else {
         return nullptr;
     }
 }
enumSampleMIMO()
PluginInterface::SamplingDevices TestMIPlugin::enumSampleMIMO () virtual
Reimplemented from PluginInterface.
Definition at line 57 of file testmiplugin.cpp.
References PluginInterface::SamplingDevice::BuiltInDevice, createSampleMIMOPluginInstanceGUI(), m_deviceTypeID, m_hardwareID, and PluginInterface::SamplingDevice::StreamMIMO.
 {
     SamplingDevices result;
     result.append(SamplingDevice(
             "TestMI",
             m_hardwareID,
             m_deviceTypeID,
             QString::null,
             0,
             PluginInterface::SamplingDevice::BuiltInDevice,
             PluginInterface::SamplingDevice::StreamMIMO,
             1,
             0));
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & TestMIPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 47 of file testmiplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void TestMIPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 52 of file testmiplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleMIMO().
 {
     pluginAPI->registerSampleMIMO(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString TestMIPlugin::m_deviceTypeID = TESTMI_DEVICE_TYPE_ID static
Definition at line 47 of file testmiplugin.h.
Referenced by createSampleMIMOPluginInstance(), createSampleMIMOPluginInstanceGUI(), enumSampleMIMO(), and initPlugin().
m_hardwareID
const QString TestMIPlugin::m_hardwareID = "TestMI" static
Definition at line 46 of file testmiplugin.h.
Referenced by enumSampleMIMO().
m_pluginDescriptor
const PluginDescriptor TestMIPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("Test Multiple Input"),
    QString("4.8.1"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 50 of file testmiplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplemimo/testmi/testmiplugin.h
plugins/samplemimo/testmi/testmiplugin.cpp