SDRAngel: LocalOutputSettings Struct Reference
LocalOutputSettings Struct Reference
#include <localoutputsettings.h>
Public Member Functions
LocalOutputSettings ()
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
Public Attributes
bool m_useReverseAPI
QString m_reverseAPIAddress
uint16_t m_reverseAPIPort
uint16_t m_reverseAPIDeviceIndex
Detailed Description
Definition at line 24 of file localoutputsettings.h.
Constructor & Destructor Documentation
LocalOutputSettings()
LocalOutputSettings::LocalOutputSettings ()
Definition at line 21 of file localoutputsettings.cpp.
References resetToDefaults().
 {
     resetToDefaults();
 }
Member Function Documentation
deserialize()
bool LocalOutputSettings::deserialize (const QByteArray & data)
Definition at line 45 of file localoutputsettings.cpp.
References SimpleDeserializer::getVersion(), SimpleDeserializer::isValid(), m_reverseAPIAddress, m_reverseAPIDeviceIndex, m_reverseAPIPort, SimpleDeserializer::readString(), SimpleDeserializer::readU32(), and resetToDefaults().
Referenced by LocalOutputGui::deserialize(), and LocalOutput::deserialize().
 {
     SimpleDeserializer d(data);
     if (!d.isValid())
     {
         resetToDefaults();
         return false;
     }
     if (d.getVersion() == 1)
     {
         quint32 uintval;
         d.readString(4, &m_reverseAPIAddress, "127.0.0.1");
         d.readU32(5, &uintval, 0);
         if ((uintval > 1023) && (uintval < 65535)) {
             m_reverseAPIPort = uintval;
         } else {
             m_reverseAPIPort = 8888;
         }
         d.readU32(6, &uintval, 0);
         m_reverseAPIDeviceIndex = uintval > 99 ? 99 : uintval;
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
resetToDefaults()
void LocalOutputSettings::resetToDefaults ()
Definition at line 26 of file localoutputsettings.cpp.
References m_reverseAPIAddress, m_reverseAPIDeviceIndex, m_reverseAPIPort, and m_useReverseAPI.
Referenced by deserialize(), LocalOutput::deserialize(), LocalOutputSettings(), and LocalOutputGui::resetToDefaults().
 {
     m_useReverseAPI = false;
     m_reverseAPIAddress = "127.0.0.1";
     m_reverseAPIPort = 8888;
     m_reverseAPIDeviceIndex = 0;
 }
serialize()
QByteArray LocalOutputSettings::serialize () const
Definition at line 34 of file localoutputsettings.cpp.
References SimpleSerializer::final(), m_reverseAPIAddress, m_reverseAPIDeviceIndex, m_reverseAPIPort, SimpleSerializer::writeString(), and SimpleSerializer::writeU32().
Referenced by LocalOutputGui::serialize(), and LocalOutput::serialize().
 {
     SimpleSerializer s(1);
     s.writeString(4, m_reverseAPIAddress);
     s.writeU32(5, m_reverseAPIPort);
     s.writeU32(6, m_reverseAPIDeviceIndex);
     return s.final();
 }
Member Data Documentation
m_reverseAPIAddress
QString LocalOutputSettings::m_reverseAPIAddress
Definition at line 26 of file localoutputsettings.h.
Referenced by LocalOutput::applySettings(), deserialize(), LocalOutputGui::openDeviceSettingsDialog(), resetToDefaults(), serialize(), LocalOutput::webapiFormatDeviceSettings(), LocalOutput::webapiReverseSendSettings(), LocalOutput::webapiReverseSendStartStop(), and LocalOutput::webapiSettingsPutPatch().
m_reverseAPIDeviceIndex
uint16_t LocalOutputSettings::m_reverseAPIDeviceIndex
Definition at line 28 of file localoutputsettings.h.
Referenced by LocalOutput::applySettings(), deserialize(), LocalOutputGui::openDeviceSettingsDialog(), resetToDefaults(), serialize(), LocalOutput::webapiFormatDeviceSettings(), LocalOutput::webapiReverseSendSettings(), LocalOutput::webapiReverseSendStartStop(), and LocalOutput::webapiSettingsPutPatch().
m_reverseAPIPort
uint16_t LocalOutputSettings::m_reverseAPIPort
Definition at line 27 of file localoutputsettings.h.
Referenced by LocalOutput::applySettings(), deserialize(), LocalOutputGui::openDeviceSettingsDialog(), resetToDefaults(), serialize(), LocalOutput::webapiFormatDeviceSettings(), LocalOutput::webapiReverseSendSettings(), LocalOutput::webapiReverseSendStartStop(), and LocalOutput::webapiSettingsPutPatch().
m_useReverseAPI
bool LocalOutputSettings::m_useReverseAPI
Definition at line 25 of file localoutputsettings.h.
Referenced by LocalOutput::applySettings(), LocalOutput::handleMessage(), LocalOutputGui::openDeviceSettingsDialog(), resetToDefaults(), LocalOutput::webapiFormatDeviceSettings(), and LocalOutput::webapiSettingsPutPatch().
The documentation for this struct was generated from the following files:
plugins/samplesink/localoutput/localoutputsettings.h
plugins/samplesink/localoutput/localoutputsettings.cpp