SDRAngel: DSPSignalNotification Class Reference
DSPSignalNotification Class Reference
#include <dspcommands.h>
Public Member Functions
DSPSignalNotification (int samplerate, qint64 centerFrequency)
int getSampleRate () const
qint64 getCenterFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Private Attributes
int m_sampleRate
qint64 m_centerFrequency
Additional Inherited Members
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 318 of file dspcommands.h.
Constructor & Destructor Documentation
DSPSignalNotification()
DSPSignalNotification::DSPSignalNotification (int samplerate, qint64 centerFrequency) inline
Definition at line 322 of file dspcommands.h.
                                                                   :
         Message(),
         m_sampleRate(samplerate),
         m_centerFrequency(centerFrequency)
     { }
Member Function Documentation
getCenterFrequency()
qint64 DSPSignalNotification::getCenterFrequency () const inline
Definition at line 329 of file dspcommands.h.
Referenced by FCDProPlusGui::handleInputMessages(), FCDProGui::handleInputMessages(), Bladerf1OutputGui::handleInputMessages(), SDRPlayGui::handleInputMessages(), Bladerf1InputGui::handleInputMessages(), KiwiSDRGui::handleInputMessages(), BladeRF2OutputGui::handleInputMessages(), TestSourceGui::handleInputMessages(), BladeRF2InputGui::handleInputMessages(), RTLSDRGui::handleInputMessages(), XTRXOutputGUI::handleInputMessages(), XTRXInputGUI::handleInputMessages(), LimeSDRInputGUI::handleInputMessages(), FileSinkGui::handleInputMessages(), HackRFInputGui::handleInputMessages(), HackRFOutputGui::handleInputMessages(), LocalOutputGui::handleInputMessages(), FileInputGUI::handleInputMessages(), PerseusGui::handleInputMessages(), PlutoSDROutputGUI::handleInputMessages(), AirspyGui::handleInputMessages(), AirspyHFGui::handleInputMessages(), PlutoSDRInputGui::handleInputMessages(), SoapySDRInputGui::handleInputMessages(), SoapySDROutputGui::handleInputMessages(), LocalInputGui::handleInputMessages(), RemoteInputGui::handleInputMessages(), DSPDeviceSinkEngine::handleInputMessages(), RemoteOutputSinkGui::handleInputMessages(), DSPDeviceSourceEngine::handleInputMessages(), FileRecord::handleMessage(), LocalSink::handleMessage(), LocalSource::handleMessage(), RemoteSink::handleMessage(), FreqTracker::handleMessage(), and FileSource::handleMessage().
 { return m_centerFrequency; }
getSampleRate()
int DSPSignalNotification::getSampleRate () const inline
Definition at line 328 of file dspcommands.h.
Referenced by FCDProPlusGui::handleInputMessages(), FCDProGui::handleInputMessages(), Bladerf1OutputGui::handleInputMessages(), SDRPlayGui::handleInputMessages(), Bladerf1InputGui::handleInputMessages(), KiwiSDRGui::handleInputMessages(), BladeRF2OutputGui::handleInputMessages(), TestSourceGui::handleInputMessages(), BladeRF2InputGui::handleInputMessages(), RTLSDRGui::handleInputMessages(), XTRXOutputGUI::handleInputMessages(), XTRXInputGUI::handleInputMessages(), LimeSDRInputGUI::handleInputMessages(), FileSinkGui::handleInputMessages(), HackRFInputGui::handleInputMessages(), HackRFOutputGui::handleInputMessages(), LocalOutputGui::handleInputMessages(), FileInputGUI::handleInputMessages(), PerseusGui::handleInputMessages(), PlutoSDROutputGUI::handleInputMessages(), AirspyGui::handleInputMessages(), AirspyHFGui::handleInputMessages(), PlutoSDRInputGui::handleInputMessages(), SoapySDRInputGui::handleInputMessages(), LocalInputGui::handleInputMessages(), SoapySDROutputGui::handleInputMessages(), RemoteInputGui::handleInputMessages(), DSPDeviceSinkEngine::handleInputMessages(), RemoteOutputSinkGui::handleInputMessages(), DSPDeviceSourceEngine::handleInputMessages(), FileRecord::handleMessage(), DownChannelizer::handleMessage(), UpChannelizer::handleMessage(), LocalSink::handleMessage(), LocalSource::handleMessage(), RemoteSink::handleMessage(), FreqTracker::handleMessage(), ScopeVis::handleMessage(), and FileSource::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_centerFrequency
qint64 DSPSignalNotification::m_centerFrequency private
Definition at line 333 of file dspcommands.h.
m_sampleRate
int DSPSignalNotification::m_sampleRate private
Definition at line 332 of file dspcommands.h.
The documentation for this class was generated from the following file:
sdrbase/dsp/dspcommands.h