SDRAngel: LimeSDRInput::MsgReportStreamInfo Class Reference
LimeSDRInput::MsgReportStreamInfo Class Reference
#include <limesdrinput.h>
Public Member Functions
bool getSuccess () const
bool getActive () const
uint32_t getFifoFilledCount () const
uint32_t getFifoSize () const
uint32_t getUnderrun () const
uint32_t getOverrun () const
uint32_t getDroppedPackets () const
float getLinkRate () const
uint64_t getTimestamp () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportStreamInfo * create (bool success, bool active, uint32_t fifoFilledCount, uint32_t fifoSize, uint32_t underrun, uint32_t overrun, uint32_t droppedPackets, float linkRate, uint64_t timestamp)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportStreamInfo (bool success, bool active, uint32_t fifoFilledCount, uint32_t fifoSize, uint32_t underrun, uint32_t overrun, uint32_t droppedPackets, float linkRate, uint64_t timestamp)
Private Attributes
bool m_success
bool m_active
Indicates whether the stream is currently active.
uint32_t m_fifoFilledCount
Number of samples in FIFO buffer.
uint32_t m_fifoSize
Size of FIFO buffer.
uint32_t m_underrun
FIFO underrun count.
uint32_t m_overrun
FIFO overrun count.
uint32_t m_droppedPackets
Number of dropped packets by HW.
float m_linkRate
Combined data rate of all stream of the same direction (TX or RX)
uint64_t m_timestamp
Current HW timestamp.
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 94 of file limesdrinput.h.
Constructor & Destructor Documentation
MsgReportStreamInfo()
LimeSDRInput::MsgReportStreamInfo::MsgReportStreamInfo (bool success, bool active, uint32_t fifoFilledCount, uint32_t fifoSize, uint32_t underrun, uint32_t overrun, uint32_t droppedPackets, float linkRate, uint64_t timestamp) inline private
Definition at line 145 of file limesdrinput.h.
                   :
             Message(),
             m_success(success),
             m_active(active),
             m_fifoFilledCount(fifoFilledCount),
             m_fifoSize(fifoSize),
             m_underrun(underrun),
             m_overrun(overrun),
             m_droppedPackets(droppedPackets),
             m_linkRate(linkRate),
             m_timestamp(timestamp)
         { }
Member Function Documentation
create()
static MsgReportStreamInfo* LimeSDRInput::MsgReportStreamInfo::create (bool success, bool active, uint32_t fifoFilledCount, uint32_t fifoSize, uint32_t underrun, uint32_t overrun, uint32_t droppedPackets, float linkRate, uint64_t timestamp) inline static
Definition at line 108 of file limesdrinput.h.
Referenced by LimeSDRInput::handleMessage().
         {
             return new MsgReportStreamInfo(
                     success,
                     active,
                     fifoFilledCount,
                     fifoSize,
                     underrun,
                     overrun,
                     droppedPackets,
                     linkRate,
                     timestamp
                     );
         }
getActive()
bool LimeSDRInput::MsgReportStreamInfo::getActive () const inline
Definition at line 99 of file limesdrinput.h.
Referenced by LimeSDRInputGUI::handleMessage().
 { return m_active; }
getDroppedPackets()
uint32_t LimeSDRInput::MsgReportStreamInfo::getDroppedPackets () const inline
Definition at line 104 of file limesdrinput.h.
Referenced by LimeSDRInputGUI::handleMessage().
 { return m_droppedPackets; }
getFifoFilledCount()
uint32_t LimeSDRInput::MsgReportStreamInfo::getFifoFilledCount () const inline
Definition at line 100 of file limesdrinput.h.
Referenced by LimeSDRInputGUI::handleMessage().
 { return m_fifoFilledCount; }
getFifoSize()
uint32_t LimeSDRInput::MsgReportStreamInfo::getFifoSize () const inline
Definition at line 101 of file limesdrinput.h.
Referenced by LimeSDRInputGUI::handleMessage().
 { return m_fifoSize; }
getLinkRate()
float LimeSDRInput::MsgReportStreamInfo::getLinkRate () const inline
Definition at line 105 of file limesdrinput.h.
Referenced by LimeSDRInputGUI::handleMessage().
 { return m_linkRate; }
getOverrun()
uint32_t LimeSDRInput::MsgReportStreamInfo::getOverrun () const inline
Definition at line 103 of file limesdrinput.h.
Referenced by LimeSDRInputGUI::handleMessage().
 { return m_overrun; }
getSuccess()
bool LimeSDRInput::MsgReportStreamInfo::getSuccess () const inline
Definition at line 98 of file limesdrinput.h.
Referenced by LimeSDRInputGUI::handleMessage().
 { return m_success; }
getTimestamp()
uint64_t LimeSDRInput::MsgReportStreamInfo::getTimestamp () const inline
Definition at line 106 of file limesdrinput.h.
 { return m_timestamp; }
getUnderrun()
uint32_t LimeSDRInput::MsgReportStreamInfo::getUnderrun () const inline
Definition at line 102 of file limesdrinput.h.
Referenced by LimeSDRInputGUI::handleMessage().
 { return m_underrun; }
Member Data Documentation
m_active
bool LimeSDRInput::MsgReportStreamInfo::m_active private
Indicates whether the stream is currently active.
Definition at line 136 of file limesdrinput.h.
m_droppedPackets
uint32_t LimeSDRInput::MsgReportStreamInfo::m_droppedPackets private
Number of dropped packets by HW.
Definition at line 141 of file limesdrinput.h.
m_fifoFilledCount
uint32_t LimeSDRInput::MsgReportStreamInfo::m_fifoFilledCount private
Number of samples in FIFO buffer.
Definition at line 137 of file limesdrinput.h.
m_fifoSize
uint32_t LimeSDRInput::MsgReportStreamInfo::m_fifoSize private
Size of FIFO buffer.
Definition at line 138 of file limesdrinput.h.
m_linkRate
float LimeSDRInput::MsgReportStreamInfo::m_linkRate private
Combined data rate of all stream of the same direction (TX or RX)
Definition at line 142 of file limesdrinput.h.
m_overrun
uint32_t LimeSDRInput::MsgReportStreamInfo::m_overrun private
FIFO overrun count.
Definition at line 140 of file limesdrinput.h.
m_success
bool LimeSDRInput::MsgReportStreamInfo::m_success private
Definition at line 134 of file limesdrinput.h.
m_timestamp
uint64_t LimeSDRInput::MsgReportStreamInfo::m_timestamp private
Current HW timestamp.
Definition at line 143 of file limesdrinput.h.
m_underrun
uint32_t LimeSDRInput::MsgReportStreamInfo::m_underrun private
FIFO underrun count.
Definition at line 139 of file limesdrinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/limesdrinput/limesdrinput.h