SDRAngel: DSPDeviceSinkEngine Class Reference
DSPDeviceSinkEngine Class Reference
#include <dspdevicesinkengine.h>
Inherits QThread.
Public Types
enum State {
StNotStarted, StIdle, StReady, StRunning,
StError
}
Public Member Functions
DSPDeviceSinkEngine (uint32_t uid, QObject *parent=NULL)
~DSPDeviceSinkEngine ()
uint32_t getUID () const
MessageQueue * getInputMessageQueue ()
void start ()
This thread start.
void stop ()
This thread stop.
bool initGeneration ()
Initialize generation sequence.
bool startGeneration ()
Start generation sequence.
void stopGeneration ()
Stop generation sequence.
void setSink (DeviceSampleSink *sink)
Set the sample sink type.
DeviceSampleSink * getSink ()
void setSinkSequence (int sequence)
Set the sample sink sequence in type.
void addThreadedSource (ThreadedBasebandSampleSource *source)
Add a baseband sample source that will run on its own thread.
void removeThreadedSource (ThreadedBasebandSampleSource *source)
Remove a baseband sample source that runs on its own thread.
void addSpectrumSink (BasebandSampleSink *spectrumSink)
Add a spectrum vis baseband sample sink.
void removeSpectrumSink (BasebandSampleSink *spectrumSink)
Add a spectrum vis baseband sample sink.
State state () const
Return DSP engine current state.
QString errorMessage ()
Return the current error message.
QString sinkDeviceDescription ()
Return the sink device description.
Private Types
typedef std::list< BasebandSampleSource * > BasebandSampleSources
typedef std::list< ThreadedBasebandSampleSource * > ThreadedBasebandSampleSources
typedef std::map< BasebandSampleSource *, SampleVector::iterator > BasebandSampleSourcesIteratorMap
typedef std::pair< BasebandSampleSource *, SampleVector::iterator > BasebandSampleSourcesIteratorMapKV
typedef std::map< ThreadedBasebandSampleSource *, SampleVector::iterator > ThreadedBasebandSampleSourcesIteratorMap
typedef std::pair< ThreadedBasebandSampleSource *, SampleVector::iterator > ThreadedBasebandSampleSourcesIteratorMapKV
Private Slots
void handleData (int nbSamples)
Handle data when samples have to be written to the sample FIFO.
void handleInputMessages ()
Handle input message queue.
void handleSynchronousMessages ()
Handle synchronous messages with the thread.
void handleForwardToSpectrumSink (int nbSamples)
Private Member Functions
void run ()
void work (int nbWriteSamples)
transfer samples from beseband sources to sink if in running state
State gotoIdle ()
Go to the idle state.
State gotoInit ()
Go to the acquisition init state from idle.
State gotoRunning ()
Go to the running state from ready state.
State gotoError (const QString &errorMsg)
Go to an error state.
void handleSetSink (DeviceSampleSink *sink)
Manage sink setting.
void checkNumberOfBasebandSources ()
Private Attributes
uint32_t m_uid
unique ID
MessageQueue m_inputMessageQueue
SyncMessenger m_syncMessenger
Used to process messages synchronously with the thread.
State m_state
QString m_errorMessage
QString m_deviceDescription
DeviceSampleSink * m_deviceSampleSink
int m_sampleSinkSequence
BasebandSampleSources m_basebandSampleSources
baseband sample sources within main thread (usually file input)
ThreadedBasebandSampleSources m_threadedBasebandSampleSources
baseband sample sources on their own threads (usually channels)
BasebandSampleSourcesIteratorMap m_basebandSampleSourcesIteratorMap
ThreadedBasebandSampleSourcesIteratorMap m_threadedBasebandSampleSourcesIteratorMap
BasebandSampleSink * m_spectrumSink
uint32_t m_sampleRate
quint64 m_centerFrequency
uint32_t m_multipleSourcesDivisionFactor
Detailed Description
Definition at line 40 of file dspdevicesinkengine.h.
Member Typedef Documentation
BasebandSampleSources
typedef std::list<BasebandSampleSource*> DSPDeviceSinkEngine::BasebandSampleSources private
Definition at line 95 of file dspdevicesinkengine.h.
BasebandSampleSourcesIteratorMap
typedef std::map<BasebandSampleSource*, SampleVector::iterator> DSPDeviceSinkEngine::BasebandSampleSourcesIteratorMap private
Definition at line 101 of file dspdevicesinkengine.h.
BasebandSampleSourcesIteratorMapKV
typedef std::pair<BasebandSampleSource*, SampleVector::iterator> DSPDeviceSinkEngine::BasebandSampleSourcesIteratorMapKV private
Definition at line 102 of file dspdevicesinkengine.h.
ThreadedBasebandSampleSources
typedef std::list<ThreadedBasebandSampleSource*> DSPDeviceSinkEngine::ThreadedBasebandSampleSources private
Definition at line 98 of file dspdevicesinkengine.h.
ThreadedBasebandSampleSourcesIteratorMap
typedef std::map<ThreadedBasebandSampleSource*, SampleVector::iterator> DSPDeviceSinkEngine::ThreadedBasebandSampleSourcesIteratorMap private
Definition at line 105 of file dspdevicesinkengine.h.
ThreadedBasebandSampleSourcesIteratorMapKV
typedef std::pair<ThreadedBasebandSampleSource*, SampleVector::iterator> DSPDeviceSinkEngine::ThreadedBasebandSampleSourcesIteratorMapKV private
Definition at line 106 of file dspdevicesinkengine.h.
Member Enumeration Documentation
State
enum DSPDeviceSinkEngine::State
Enumerator
StNotStarted
engine is before initialization
StIdle
engine is idle
StReady
engine is ready to run
StRunning
engine is running
StError
engine is in error
Definition at line 44 of file dspdevicesinkengine.h.
                {
         StNotStarted,
         StIdle,
         StReady,
         StRunning,
         StError
     };
Constructor & Destructor Documentation
DSPDeviceSinkEngine()
DSPDeviceSinkEngine::DSPDeviceSinkEngine (uint32_t uid, QObject * parent = NULL)
Definition at line 32 of file dspdevicesinkengine.cpp.
References handleInputMessages(), handleSynchronousMessages(), m_inputMessageQueue, and m_syncMessenger.
                                                                       :
     QThread(parent),
     m_uid(uid),
     m_state(StNotStarted),
     m_deviceSampleSink(nullptr),
     m_sampleSinkSequence(0),
     m_basebandSampleSources(),
     m_spectrumSink(nullptr),
     m_sampleRate(0),
     m_centerFrequency(0),
     m_multipleSourcesDivisionFactor(1)
 {
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     connect(&m_syncMessenger, SIGNAL(messageSent()), this, SLOT(handleSynchronousMessages()), Qt::QueuedConnection);
     moveToThread(this);
 }
~DSPDeviceSinkEngine()
DSPDeviceSinkEngine::~DSPDeviceSinkEngine ()
Definition at line 50 of file dspdevicesinkengine.cpp.
References stop().
 {
     stop();
     wait();
 }
Member Function Documentation
addSpectrumSink()
void DSPDeviceSinkEngine::addSpectrumSink (BasebandSampleSink * spectrumSink)
Add a spectrum vis baseband sample sink.
Definition at line 130 of file dspdevicesinkengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::addAncillarySink(), and MainWindow::addSinkDevice().
 {
     qDebug() << "DSPDeviceSinkEngine::addSpectrumSink: " << spectrumSink->objectName().toStdString().c_str();
     DSPAddSpectrumSink cmd(spectrumSink);
     m_syncMessenger.sendWait(cmd);
 }
addThreadedSource()
void DSPDeviceSinkEngine::addThreadedSource (ThreadedBasebandSampleSource * source)
Add a baseband sample source that will run on its own thread.
Definition at line 116 of file dspdevicesinkengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::addChannelSource().
 {
     qDebug() << "DSPDeviceSinkEngine::addThreadedSource: " << source->objectName().toStdString().c_str();
     DSPAddThreadedBasebandSampleSource cmd(source);
     m_syncMessenger.sendWait(cmd);
 }
checkNumberOfBasebandSources()
void DSPDeviceSinkEngine::checkNumberOfBasebandSources () private
Definition at line 570 of file dspdevicesinkengine.cpp.
References DeviceSampleSink::getSampleFifo(), handleData(), m_basebandSampleSources, m_deviceSampleSink, m_multipleSourcesDivisionFactor, and m_threadedBasebandSampleSources.
Referenced by handleSynchronousMessages().
 {
     SampleSourceFifo* sampleFifo = m_deviceSampleSink->getSampleFifo();
     // single channel source handling
     if ((m_threadedBasebandSampleSources.size() + m_basebandSampleSources.size()) == 1)
     {
         qDebug("DSPDeviceSinkEngine::checkNumberOfBasebandSources: single channel mode");
         disconnect(sampleFifo, SIGNAL(dataWrite(int)), this, SLOT(handleData(int)));
         if (m_threadedBasebandSampleSources.size() == 1) {
             m_threadedBasebandSampleSources.back()->setDeviceSampleSourceFifo(sampleFifo);
         } else if (m_basebandSampleSources.size() == 1) {
             m_basebandSampleSources.back()->setDeviceSampleSourceFifo(sampleFifo);
         }
         m_multipleSourcesDivisionFactor = 1; // for consistency but it is not used in this case
     }
     // null or multiple channel sources handling
     else
     {
         int nbSources = 0;
         for (ThreadedBasebandSampleSources::iterator it = m_threadedBasebandSampleSources.begin(); it != m_threadedBasebandSampleSources.end(); ++it)
         {
             (*it)->setDeviceSampleSourceFifo(0);
             nbSources++;
         }
         for (BasebandSampleSources::iterator it = m_basebandSampleSources.begin(); it != m_basebandSampleSources.end(); ++it)
         {
             (*it)->setDeviceSampleSourceFifo(0);
             nbSources++;
         }
         if (nbSources == 0) {
             m_multipleSourcesDivisionFactor = 1;
         } else if (nbSources < 3) {
             m_multipleSourcesDivisionFactor = nbSources;
         } else {
             m_multipleSourcesDivisionFactor = 1<<nbSources;
         }
         if (nbSources > 1) {
             connect(sampleFifo, SIGNAL(dataWrite(int)), this, SLOT(handleData(int)), Qt::QueuedConnection);
         }
         qDebug("DSPDeviceSinkEngine::checkNumberOfBasebandSources: handle %d channel(s)", nbSources);
     }
 }
errorMessage()
QString DSPDeviceSinkEngine::errorMessage ()
Return the current error message.
Definition at line 144 of file dspdevicesinkengine.cpp.
References DSPGetErrorMessage::getErrorMessage(), m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::errorMessage(), and gotoError().
 {
     qDebug() << "DSPDeviceSinkEngine::errorMessage";
     DSPGetErrorMessage cmd;
     m_syncMessenger.sendWait(cmd);
     return cmd.getErrorMessage();
 }
getInputMessageQueue()
MessageQueue* DSPDeviceSinkEngine::getInputMessageQueue () inline
Definition at line 57 of file dspdevicesinkengine.h.
Referenced by DeviceAPI::getDeviceEngineInputMessageQueue().
 { return &m_inputMessageQueue; }
getSink()
DeviceSampleSink* DSPDeviceSinkEngine::getSink () inline
Definition at line 67 of file dspdevicesinkengine.h.
Referenced by WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), LocalSource::getLocalDevice(), LocalSource::getLocalDevices(), DeviceAPI::getSampleSink(), DeviceAPI::getSamplingDeviceGUIMessageQueue(), DeviceAPI::getSamplingDeviceInputMessageQueue(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), DeviceAPI::loadSamplingDeviceSettings(), and DeviceAPI::saveSamplingDeviceSettings().
 { return m_deviceSampleSink; }
getUID()
uint32_t DSPDeviceSinkEngine::getUID () const inline
Definition at line 55 of file dspdevicesinkengine.h.
Referenced by MainCore::addSinkDevice(), MainWindow::addSinkDevice(), DeviceAPI::getDeviceUID(), and LocalSource::getLocalDevice().
 { return m_uid; }
gotoError()
DSPDeviceSinkEngine::State DSPDeviceSinkEngine::gotoError (const QString & errorMsg) private
Go to an error state.
Definition at line 378 of file dspdevicesinkengine.cpp.
References errorMessage(), m_deviceDescription, m_errorMessage, m_state, and StError.
Referenced by gotoInit(), and gotoRunning().
 {
     qDebug() << "DSPDeviceSinkEngine::gotoError";
     m_errorMessage = errorMessage;
     m_deviceDescription.clear();
     m_state = StError;
     return StError;
 }
gotoIdle()
DSPDeviceSinkEngine::State DSPDeviceSinkEngine::gotoIdle () private
Go to the idle state.
Definition at line 212 of file dspdevicesinkengine.cpp.
References DeviceSampleSink::getSampleFifo(), handleForwardToSpectrumSink(), m_basebandSampleSources, m_deviceDescription, m_deviceSampleSink, m_sampleRate, m_spectrumSink, m_state, m_threadedBasebandSampleSources, StError, StIdle, StNotStarted, DeviceSampleSink::stop(), BasebandSampleSink::stop(), StReady, and StRunning.
Referenced by handleSetSink(), handleSynchronousMessages(), and stop().
 {
     qDebug() << "DSPDeviceSinkEngine::gotoIdle";
     switch(m_state) {
         case StNotStarted:
             return StNotStarted;
         case StIdle:
         case StError:
             return StIdle;
         case StReady:
         case StRunning:
             break;
     }
     if(m_deviceSampleSink == 0)
     {
         return StIdle;
     }
     // stop everything
     for(BasebandSampleSources::const_iterator it = m_basebandSampleSources.begin(); it != m_basebandSampleSources.end(); it++)
     {
         qDebug() << "DSPDeviceSinkEngine::gotoIdle: stopping " << (*it)->objectName().toStdString().c_str();
         (*it)->stop();
     }
     for(ThreadedBasebandSampleSources::const_iterator it = m_threadedBasebandSampleSources.begin(); it != m_threadedBasebandSampleSources.end(); it++)
     {
         qDebug() << "DSPDeviceSinkEngine::gotoIdle: stopping ThreadedSampleSource(" << (*it)->getSampleSourceObjectName().toStdString().c_str() << ")";
         (*it)->stop();
     }
     if (m_spectrumSink)
     {
         disconnect(m_deviceSampleSink->getSampleFifo(), SIGNAL(dataRead(int)), this, SLOT(handleForwardToSpectrumSink(int)));
         m_spectrumSink->stop();
     }
     m_deviceSampleSink->stop();
     m_deviceDescription.clear();
     m_sampleRate = 0;
     return StIdle;
 }
gotoInit()
DSPDeviceSinkEngine::State DSPDeviceSinkEngine::gotoInit () private
Go to the acquisition init state from idle.
Definition at line 261 of file dspdevicesinkengine.cpp.
References DeviceSampleSink::getCenterFrequency(), DeviceSampleSink::getDeviceDescription(), DeviceSampleSink::getMessageQueueToGUI(), DeviceSampleSink::getSampleRate(), gotoError(), BasebandSampleSink::handleMessage(), m_basebandSampleSources, m_centerFrequency, m_deviceDescription, m_deviceSampleSink, m_sampleRate, m_spectrumSink, m_state, m_threadedBasebandSampleSources, MessageQueue::push(), StError, StIdle, StNotStarted, StReady, and StRunning.
Referenced by handleSynchronousMessages().
 {
     switch(m_state) {
         case StNotStarted:
             return StNotStarted;
         case StRunning: // FIXME: assumes it goes first through idle state. Could we get back to init from running directly?
             return StRunning;
         case StReady:
             return StReady;
         case StIdle:
         case StError:
             break;
     }
     if (m_deviceSampleSink == 0)
     {
         return gotoError("DSPDeviceSinkEngine::gotoInit: No sample source configured");
     }
     // init: pass sample rate and center frequency to all sample rate and/or center frequency dependent sinks and wait for completion
     m_deviceDescription = m_deviceSampleSink->getDeviceDescription();
     m_centerFrequency = m_deviceSampleSink->getCenterFrequency();
     m_sampleRate = m_deviceSampleSink->getSampleRate();
     qDebug() << "DSPDeviceSinkEngine::gotoInit: "
             << " m_deviceDescription: " << m_deviceDescription.toStdString().c_str()
             << " sampleRate: " << m_sampleRate
             << " centerFrequency: " << m_centerFrequency;
     DSPSignalNotification notif(m_sampleRate, m_centerFrequency);
     for (BasebandSampleSources::const_iterator it = m_basebandSampleSources.begin(); it != m_basebandSampleSources.end(); ++it)
     {
         qDebug() << "DSPDeviceSinkEngine::gotoInit: initializing " << (*it)->objectName().toStdString().c_str();
         (*it)->handleMessage(notif);
     }
     for (ThreadedBasebandSampleSources::const_iterator it = m_threadedBasebandSampleSources.begin(); it != m_threadedBasebandSampleSources.end(); ++it)
     {
         qDebug() << "DSPDeviceSinkEngine::gotoInit: initializing ThreadedSampleSource(" << (*it)->getSampleSourceObjectName().toStdString().c_str() << ")";
         (*it)->handleSourceMessage(notif);
     }
     if (m_spectrumSink) {
         m_spectrumSink->handleMessage(notif);
     }
     // pass data to listeners
     if (m_deviceSampleSink->getMessageQueueToGUI())
     {
         DSPSignalNotification* rep = new DSPSignalNotification(notif); // make a copy for the output queue
         m_deviceSampleSink->getMessageQueueToGUI()->push(rep);
     }
     return StReady;
 }
gotoRunning()
DSPDeviceSinkEngine::State DSPDeviceSinkEngine::gotoRunning () private
Go to the running state from ready state.
Definition at line 322 of file dspdevicesinkengine.cpp.
References DeviceSampleSink::getSampleFifo(), gotoError(), handleForwardToSpectrumSink(), m_basebandSampleSources, m_deviceDescription, m_deviceSampleSink, m_inputMessageQueue, m_spectrumSink, m_state, m_threadedBasebandSampleSources, MessageQueue::size(), DeviceSampleSink::start(), BasebandSampleSink::start(), StError, StIdle, StNotStarted, StReady, and StRunning.
Referenced by handleSynchronousMessages().
 {
     qDebug() << "DSPDeviceSinkEngine::gotoRunning";
     switch(m_state)
     {
         case StNotStarted:
             return StNotStarted;
         case StIdle:
             return StIdle;
         case StRunning:
             return StRunning;
         case StReady:
         case StError:
             break;
     }
     if(m_deviceSampleSink == 0) {
         return gotoError("DSPDeviceSinkEngine::gotoRunning: No sample source configured");
     }
     qDebug() << "DSPDeviceSinkEngine::gotoRunning: " << m_deviceDescription.toStdString().c_str() << " started";
     // Start everything
     if(!m_deviceSampleSink->start())
     {
         return gotoError("DSPDeviceSinkEngine::gotoRunning: Could not start sample sink");
     }
     for(BasebandSampleSources::const_iterator it = m_basebandSampleSources.begin(); it != m_basebandSampleSources.end(); it++)
     {
         qDebug() << "DSPDeviceSinkEngine::gotoRunning: starting " << (*it)->objectName().toStdString().c_str();
         (*it)->start();
     }
     for (ThreadedBasebandSampleSources::const_iterator it = m_threadedBasebandSampleSources.begin(); it != m_threadedBasebandSampleSources.end(); ++it)
     {
         qDebug() << "DSPDeviceSinkEngine::gotoRunning: starting ThreadedSampleSource(" << (*it)->getSampleSourceObjectName().toStdString().c_str() << ")";
         (*it)->start();
     }
     if (m_spectrumSink)
     {
         connect(m_deviceSampleSink->getSampleFifo(), SIGNAL(dataRead(int)), this, SLOT(handleForwardToSpectrumSink(int)));
         m_spectrumSink->start();
     }
     qDebug() << "DSPDeviceSinkEngine::gotoRunning: input message queue pending: " << m_inputMessageQueue.size();
     return StRunning;
 }
handleData
void DSPDeviceSinkEngine::handleData (int nbSamples) private slot
Handle data when samples have to be written to the sample FIFO.
Definition at line 401 of file dspdevicesinkengine.cpp.
References m_state, StRunning, and work().
Referenced by checkNumberOfBasebandSources().
 {
     if(m_state == StRunning)
     {
         work(nbSamples);
     }
 }
handleForwardToSpectrumSink
void DSPDeviceSinkEngine::handleForwardToSpectrumSink (int nbSamples) private slot
Definition at line 559 of file dspdevicesinkengine.cpp.
References BasebandSampleSink::feed(), SampleSourceFifo::getReadIterator(), DeviceSampleSink::getSampleFifo(), m_deviceSampleSink, and m_spectrumSink.
Referenced by gotoIdle(), and gotoRunning().
 {
     if (m_spectrumSink)
     {
         SampleSourceFifo* sampleFifo = m_deviceSampleSink->getSampleFifo();
         SampleVector::iterator readUntil;
         sampleFifo->getReadIterator(readUntil);
         m_spectrumSink->feed(readUntil - nbSamples, readUntil, false);
     }
 }
handleInputMessages
void DSPDeviceSinkEngine::handleInputMessages () private slot
Handle input message queue.
Definition at line 508 of file dspdevicesinkengine.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DeviceSampleSink::getMessageQueueToGUI(), DSPSignalNotification::getSampleRate(), m_basebandSampleSources, m_centerFrequency, m_deviceSampleSink, m_inputMessageQueue, m_sampleRate, m_threadedBasebandSampleSources, Message::match(), MessageQueue::pop(), and MessageQueue::push().
Referenced by DSPDeviceSinkEngine().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("DSPDeviceSinkEngine::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification *notif = (DSPSignalNotification *) message;
             // update DSP values
             m_sampleRate = notif->getSampleRate();
             m_centerFrequency = notif->getCenterFrequency();
             qDebug() << "DSPDeviceSinkEngine::handleInputMessages: DSPSignalNotification:"
                 << " m_sampleRate: " << m_sampleRate
                 << " m_centerFrequency: " << m_centerFrequency;
             // forward source changes to sources with immediate execution
             for(BasebandSampleSources::const_iterator it = m_basebandSampleSources.begin(); it != m_basebandSampleSources.end(); it++)
             {
                 qDebug() << "DSPDeviceSinkEngine::handleInputMessages: forward message to " << (*it)->objectName().toStdString().c_str();
                 (*it)->handleMessage(*message);
             }
             for (ThreadedBasebandSampleSources::const_iterator it = m_threadedBasebandSampleSources.begin(); it != m_threadedBasebandSampleSources.end(); ++it)
             {
                 qDebug() << "DSPDeviceSinkEngine::handleSourceMessages: forward message to ThreadedSampleSource(" << (*it)->getSampleSourceObjectName().toStdString().c_str() << ")";
                 (*it)->handleSourceMessage(*message);
             }
             // forward changes to listeners on DSP output queue
             MessageQueue *guiMessageQueue = m_deviceSampleSink->getMessageQueueToGUI();
             qDebug("DSPDeviceSinkEngine::handleInputMessages: DSPSignalNotification: guiMessageQueue: %p", guiMessageQueue);
             if (guiMessageQueue)
             {
                 DSPSignalNotification* rep = new DSPSignalNotification(*notif); // make a copy for the output queue
                 guiMessageQueue->push(rep);
             }
             delete message;
         }
     }
 }
handleSetSink()
void DSPDeviceSinkEngine::handleSetSink (DeviceSampleSink * sink) private
Manage sink setting.
Definition at line 388 of file dspdevicesinkengine.cpp.
References DeviceSampleSink::getDeviceDescription(), gotoIdle(), and m_deviceSampleSink.
Referenced by handleSynchronousMessages().
 {
     gotoIdle();
     m_deviceSampleSink = sink;
     if(m_deviceSampleSink != 0) {
         qDebug("DSPDeviceSinkEngine::handleSetSink: set %s", qPrintable(sink->getDeviceDescription()));
     } else {
         qDebug("DSPDeviceSinkEngine::handleSetSource: set none");
     }
 }
handleSynchronousMessages
void DSPDeviceSinkEngine::handleSynchronousMessages () private slot
Handle synchronous messages with the thread.
Definition at line 409 of file dspdevicesinkengine.cpp.
References checkNumberOfBasebandSources(), SyncMessenger::done(), Message::getIdentifier(), SyncMessenger::getMessage(), gotoIdle(), gotoInit(), gotoRunning(), BasebandSampleSource::handleMessage(), handleSetSink(), ThreadedBasebandSampleSource::handleSourceMessage(), m_basebandSampleSources, m_centerFrequency, m_deviceDescription, m_errorMessage, m_sampleRate, m_spectrumSink, m_state, m_syncMessenger, m_threadedBasebandSampleSources, Message::match(), BasebandSampleSource::start(), ThreadedBasebandSampleSource::start(), StIdle, BasebandSampleSource::stop(), ThreadedBasebandSampleSource::stop(), BasebandSampleSink::stop(), StReady, and StRunning.
Referenced by DSPDeviceSinkEngine(), and stopGeneration().
 {
     Message *message = m_syncMessenger.getMessage();
     qDebug() << "DSPDeviceSinkEngine::handleSynchronousMessages: " << message->getIdentifier();
     if (DSPGenerationInit::match(*message))
     {
         m_state = gotoIdle();
         if(m_state == StIdle) {
             m_state = gotoInit(); // State goes ready if init is performed
         }
     }
     else if (DSPGenerationStart::match(*message))
     {
         if(m_state == StReady) {
             m_state = gotoRunning();
         }
     }
     else if (DSPGenerationStop::match(*message))
     {
         m_state = gotoIdle();
     }
     else if (DSPGetSinkDeviceDescription::match(*message))
     {
         ((DSPGetSinkDeviceDescription*) message)->setDeviceDescription(m_deviceDescription);
     }
     else if (DSPGetErrorMessage::match(*message))
     {
         ((DSPGetErrorMessage*) message)->setErrorMessage(m_errorMessage);
     }
     else if (DSPSetSink::match(*message)) {
         handleSetSink(((DSPSetSink*) message)->getSampleSink());
     }
     else if (DSPAddSpectrumSink::match(*message))
     {
         m_spectrumSink = ((DSPAddSpectrumSink*) message)->getSampleSink();
     }
     else if (DSPRemoveSpectrumSink::match(*message))
     {
         BasebandSampleSink* spectrumSink = ((DSPRemoveSpectrumSink*) message)->getSampleSink();
         if(m_state == StRunning) {
             spectrumSink->stop();
         }
         m_spectrumSink = 0;
     }
     else if (DSPAddBasebandSampleSource::match(*message))
     {
         BasebandSampleSource* source = ((DSPAddBasebandSampleSource*) message)->getSampleSource();
         m_basebandSampleSources.push_back(source);
         DSPSignalNotification notif(m_sampleRate, m_centerFrequency);
         source->handleMessage(notif);
         checkNumberOfBasebandSources();
         if (m_state == StRunning)
         {
             source->start();
         }
     }
     else if (DSPRemoveBasebandSampleSource::match(*message))
     {
         BasebandSampleSource* source = ((DSPRemoveBasebandSampleSource*) message)->getSampleSource();
         if(m_state == StRunning) {
             source->stop();
         }
         m_basebandSampleSources.remove(source);
         checkNumberOfBasebandSources();
     }
     else if (DSPAddThreadedBasebandSampleSource::match(*message))
     {
         ThreadedBasebandSampleSource *threadedSource = ((DSPAddThreadedBasebandSampleSource*) message)->getThreadedSampleSource();
         m_threadedBasebandSampleSources.push_back(threadedSource);
         DSPSignalNotification notif(m_sampleRate, m_centerFrequency);
         threadedSource->handleSourceMessage(notif);
         checkNumberOfBasebandSources();
         if (m_state == StRunning)
         {
             threadedSource->start();
         }
     }
     else if (DSPRemoveThreadedBasebandSampleSource::match(*message))
     {
         ThreadedBasebandSampleSource* threadedSource = ((DSPRemoveThreadedBasebandSampleSource*) message)->getThreadedSampleSource();
         if (m_state == StRunning) {
             threadedSource->stop();
         }
         m_threadedBasebandSampleSources.remove(threadedSource);
         checkNumberOfBasebandSources();
     }
     m_syncMessenger.done(m_state);
 }
initGeneration()
bool DSPDeviceSinkEngine::initGeneration ()
Initialize generation sequence.
Definition at line 79 of file dspdevicesinkengine.cpp.
References m_syncMessenger, SyncMessenger::sendWait(), and StReady.
Referenced by DeviceAPI::initDeviceEngine().
 {
     qDebug() << "DSPDeviceSinkEngine::initGeneration";
     DSPGenerationInit cmd;
     return m_syncMessenger.sendWait(cmd) == StReady;
 }
removeSpectrumSink()
void DSPDeviceSinkEngine::removeSpectrumSink (BasebandSampleSink * spectrumSink)
Add a spectrum vis baseband sample sink.
Definition at line 137 of file dspdevicesinkengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::removeAncillarySink(), and MainWindow::removeLastDevice().
 {
     qDebug() << "DSPDeviceSinkEngine::removeSpectrumSink: " << spectrumSink->objectName().toStdString().c_str();
     DSPRemoveSpectrumSink cmd(spectrumSink);
     m_syncMessenger.sendWait(cmd);
 }
removeThreadedSource()
void DSPDeviceSinkEngine::removeThreadedSource (ThreadedBasebandSampleSource * source)
Remove a baseband sample source that runs on its own thread.
Definition at line 123 of file dspdevicesinkengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::removeChannelSource().
 {
     qDebug() << "DSPDeviceSinkEngine::removeThreadedSource: " << source->objectName().toStdString().c_str();
     DSPRemoveThreadedBasebandSampleSource cmd(source);
     m_syncMessenger.sendWait(cmd);
 }
run()
void DSPDeviceSinkEngine::run () private
Definition at line 56 of file dspdevicesinkengine.cpp.
References m_state, and StIdle.
 {
     qDebug() << "DSPDeviceSinkEngine::run";
     m_state = StIdle;
     exec();
 }
setSink()
void DSPDeviceSinkEngine::setSink (DeviceSampleSink * sink)
Set the sample sink type.
Definition at line 103 of file dspdevicesinkengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::setSampleSink().
 {
     qDebug() << "DSPDeviceSinkEngine::setSink";
     DSPSetSink cmd(sink);
     m_syncMessenger.sendWait(cmd);
 }
setSinkSequence()
void DSPDeviceSinkEngine::setSinkSequence (int sequence)
Set the sample sink sequence in type.
Definition at line 110 of file dspdevicesinkengine.cpp.
References m_sampleSinkSequence.
 {
     qDebug("DSPDeviceSinkEngine::setSinkSequence: seq: %d", sequence);
     m_sampleSinkSequence = sequence;
 }
sinkDeviceDescription()
QString DSPDeviceSinkEngine::sinkDeviceDescription ()
Return the sink device description.
Definition at line 152 of file dspdevicesinkengine.cpp.
References DSPGetSinkDeviceDescription::getDeviceDescription(), m_syncMessenger, and SyncMessenger::sendWait().
 {
     qDebug() << "DSPDeviceSinkEngine::sinkDeviceDescription";
     DSPGetSinkDeviceDescription cmd;
     m_syncMessenger.sendWait(cmd);
     return cmd.getDeviceDescription();
 }
start()
void DSPDeviceSinkEngine::start ()
This thread start.
Definition at line 63 of file dspdevicesinkengine.cpp.
Referenced by MainCore::addSinkDevice(), and MainWindow::addSinkDevice().
 {
     qDebug() << "DSPDeviceSinkEngine::start";
     QThread::start();
 }
startGeneration()
bool DSPDeviceSinkEngine::startGeneration ()
Start generation sequence.
Definition at line 87 of file dspdevicesinkengine.cpp.
References m_syncMessenger, SyncMessenger::sendWait(), and StRunning.
Referenced by DeviceAPI::startDeviceEngine().
 {
     qDebug() << "DSPDeviceSinkEngine::startGeneration";
     DSPGenerationStart cmd;
     return m_syncMessenger.sendWait(cmd) == StRunning;
 }
state()
State DSPDeviceSinkEngine::state () const inline
Return DSP engine current state.
Definition at line 76 of file dspdevicesinkengine.h.
Referenced by Bladerf1Input::applySettings(), DeviceAPI::getDeviceEngineStateStr(), and DeviceAPI::state().
stop()
void DSPDeviceSinkEngine::stop ()
This thread stop.
Definition at line 69 of file dspdevicesinkengine.cpp.
References gotoIdle(), m_state, and StNotStarted.
Referenced by MainCore::removeLastDevice(), MainWindow::removeLastDevice(), and ~DSPDeviceSinkEngine().
 {
     qDebug() << "DSPDeviceSinkEngine::stop";
     gotoIdle();
     m_state = StNotStarted;
     QThread::exit();
 //  DSPExit cmd;
 //  m_syncMessenger.sendWait(cmd);
 }
stopGeneration()
void DSPDeviceSinkEngine::stopGeneration ()
Stop generation sequence.
Definition at line 95 of file dspdevicesinkengine.cpp.
References handleSynchronousMessages(), m_syncMessenger, and SyncMessenger::storeMessage().
Referenced by MainCore::removeLastDevice(), MainWindow::removeLastDevice(), and DeviceAPI::stopDeviceEngine().
 {
     qDebug() << "DSPDeviceSinkEngine::stopGeneration";
     DSPGenerationStop cmd;
     m_syncMessenger.storeMessage(cmd);
     handleSynchronousMessages();
 }
work()
void DSPDeviceSinkEngine::work (int nbWriteSamples) private
transfer samples from beseband sources to sink if in running state
Definition at line 160 of file dspdevicesinkengine.cpp.
References SampleSourceFifo::bumpIndex(), DeviceSampleSink::getSampleFifo(), SampleSourceFifo::getWriteIterator(), m_basebandSampleSources, m_deviceSampleSink, m_multipleSourcesDivisionFactor, and m_threadedBasebandSampleSources.
Referenced by handleData().
 {
     // multiple channel sources handling
     if ((m_threadedBasebandSampleSources.size() + m_basebandSampleSources.size()) > 1)
     {
 //      qDebug("DSPDeviceSinkEngine::work: multiple channel sources handling: %u", m_multipleSourcesDivisionFactor);
         SampleVector::iterator writeBegin;
         SampleSourceFifo* sampleFifo = m_deviceSampleSink->getSampleFifo();
         sampleFifo->getWriteIterator(writeBegin);
         SampleVector::iterator writeAt = writeBegin;
         std::vector<SampleVector::iterator> sampleSourceIterators;
         for (ThreadedBasebandSampleSources::iterator it = m_threadedBasebandSampleSources.begin(); it != m_threadedBasebandSampleSources.end(); ++it)
         {
             sampleSourceIterators.push_back(SampleVector::iterator());
             (*it)->getSampleSourceFifo().readAdvance(sampleSourceIterators.back(), nbWriteSamples);
             sampleSourceIterators.back() -= nbWriteSamples;
         }
         for (BasebandSampleSources::iterator it = m_basebandSampleSources.begin(); it != m_basebandSampleSources.end(); ++it)
         {
             sampleSourceIterators.push_back(SampleVector::iterator());
             (*it)->getSampleSourceFifo().readAdvance(sampleSourceIterators.back(), nbWriteSamples);
             sampleSourceIterators.back() -= nbWriteSamples;
         }
         for (int is = 0; is < nbWriteSamples; is++)
         {
             // pull data from sources FIFOs and merge them in the device sample FIFO
             for (std::vector<SampleVector::iterator>::iterator it = sampleSourceIterators.begin(); it != sampleSourceIterators.end(); ++it)
             {
                 Sample s = (**it);
                 s /= m_multipleSourcesDivisionFactor;
                 ++(*it);
                 if (it == sampleSourceIterators.begin()) {
                     (*writeAt) = s;
                 } else {
                     (*writeAt) += s;
                 }
             }
             sampleFifo->bumpIndex(writeAt);
         }
     }
 }
Member Data Documentation
m_basebandSampleSources
BasebandSampleSources DSPDeviceSinkEngine::m_basebandSampleSources private
baseband sample sources within main thread (usually file input)
Definition at line 96 of file dspdevicesinkengine.h.
Referenced by checkNumberOfBasebandSources(), gotoIdle(), gotoInit(), gotoRunning(), handleInputMessages(), handleSynchronousMessages(), and work().
m_basebandSampleSourcesIteratorMap
BasebandSampleSourcesIteratorMap DSPDeviceSinkEngine::m_basebandSampleSourcesIteratorMap private
Definition at line 103 of file dspdevicesinkengine.h.
m_centerFrequency
quint64 DSPDeviceSinkEngine::m_centerFrequency private
Definition at line 112 of file dspdevicesinkengine.h.
Referenced by gotoInit(), handleInputMessages(), and handleSynchronousMessages().
m_deviceDescription
QString DSPDeviceSinkEngine::m_deviceDescription private
Definition at line 90 of file dspdevicesinkengine.h.
Referenced by gotoError(), gotoIdle(), gotoInit(), gotoRunning(), and handleSynchronousMessages().
m_deviceSampleSink
DeviceSampleSink* DSPDeviceSinkEngine::m_deviceSampleSink private
Definition at line 92 of file dspdevicesinkengine.h.
Referenced by checkNumberOfBasebandSources(), gotoIdle(), gotoInit(), gotoRunning(), handleForwardToSpectrumSink(), handleInputMessages(), handleSetSink(), and work().
m_errorMessage
QString DSPDeviceSinkEngine::m_errorMessage private
Definition at line 89 of file dspdevicesinkengine.h.
Referenced by gotoError(), and handleSynchronousMessages().
m_inputMessageQueue
MessageQueue DSPDeviceSinkEngine::m_inputMessageQueue private
Definition at line 84 of file dspdevicesinkengine.h.
Referenced by DSPDeviceSinkEngine(), gotoRunning(), and handleInputMessages().
m_multipleSourcesDivisionFactor
uint32_t DSPDeviceSinkEngine::m_multipleSourcesDivisionFactor private
Definition at line 113 of file dspdevicesinkengine.h.
Referenced by checkNumberOfBasebandSources(), and work().
m_sampleRate
uint32_t DSPDeviceSinkEngine::m_sampleRate private
Definition at line 111 of file dspdevicesinkengine.h.
Referenced by gotoIdle(), gotoInit(), handleInputMessages(), and handleSynchronousMessages().
m_sampleSinkSequence
int DSPDeviceSinkEngine::m_sampleSinkSequence private
Definition at line 93 of file dspdevicesinkengine.h.
Referenced by setSinkSequence().
m_spectrumSink
BasebandSampleSink* DSPDeviceSinkEngine::m_spectrumSink private
Definition at line 109 of file dspdevicesinkengine.h.
Referenced by gotoIdle(), gotoInit(), gotoRunning(), handleForwardToSpectrumSink(), and handleSynchronousMessages().
m_state
State DSPDeviceSinkEngine::m_state private
Definition at line 87 of file dspdevicesinkengine.h.
Referenced by gotoError(), gotoIdle(), gotoInit(), gotoRunning(), handleData(), handleSynchronousMessages(), run(), and stop().
m_syncMessenger
SyncMessenger DSPDeviceSinkEngine::m_syncMessenger private
Used to process messages synchronously with the thread.
Definition at line 85 of file dspdevicesinkengine.h.
Referenced by addSpectrumSink(), addThreadedSource(), DSPDeviceSinkEngine(), errorMessage(), handleSynchronousMessages(), initGeneration(), removeSpectrumSink(), removeThreadedSource(), setSink(), sinkDeviceDescription(), startGeneration(), and stopGeneration().
m_threadedBasebandSampleSources
ThreadedBasebandSampleSources DSPDeviceSinkEngine::m_threadedBasebandSampleSources private
baseband sample sources on their own threads (usually channels)
Definition at line 99 of file dspdevicesinkengine.h.
Referenced by checkNumberOfBasebandSources(), gotoIdle(), gotoInit(), gotoRunning(), handleInputMessages(), handleSynchronousMessages(), and work().
m_threadedBasebandSampleSourcesIteratorMap
ThreadedBasebandSampleSourcesIteratorMap DSPDeviceSinkEngine::m_threadedBasebandSampleSourcesIteratorMap private
Definition at line 107 of file dspdevicesinkengine.h.
m_uid
uint32_t DSPDeviceSinkEngine::m_uid private
unique ID
Definition at line 82 of file dspdevicesinkengine.h.
The documentation for this class was generated from the following files:
sdrbase/dsp/dspdevicesinkengine.h
sdrbase/dsp/dspdevicesinkengine.cpp