SDRAngel: appbench/main.cpp File Reference
main.cpp File Reference
#include <QCoreApplication>
#include <QSysInfo>
#include <QTimer>
#include <signal.h>
#include <unistd.h>
#include <vector>
#include "loggerwithfile.h"
#include "mainbench.h"
#include "dsp/dsptypes.h"
Functions
void handler (int sig)
void catchUnixSignals (const std::vector< int > &quitSignals)
int main (int argc, char *argv[])
Function Documentation
catchUnixSignals()
void catchUnixSignals (const std::vector< int > & quitSignals)
Definition at line 38 of file main.cpp.
References handler().
{
     sigset_t blocking_mask;
     sigemptyset(&blocking_mask);
     for (std::vector<int>::const_iterator it = quitSignals.begin(); it != quitSignals.end(); ++it) {
         sigaddset(&blocking_mask, *it);
     }
     struct sigaction sa;
     sa.sa_handler = handler;
     sa.sa_mask    = blocking_mask;
     sa.sa_flags   = 0;
     for (std::vector<int>::const_iterator it = quitSignals.begin(); it != quitSignals.end(); ++it) {
         sigaction(*it, &sa, 0);
     }
 }
handler()
void handler (int sig)
Definition at line 32 of file main.cpp.
Referenced by catchUnixSignals(), qtwebapp::HttpConnectionHandlerPool::cleanup(), qtwebapp::HttpConnectionHandlerPool::getConnectionHandler(), and qtwebapp::HttpConnectionHandlerPool::~HttpConnectionHandlerPool().
                       {
     fprintf(stderr, "quit the application by signal(%d).\n", sig);
     QCoreApplication::quit();
 }
main()
int main (int argc, char * argv[])
Definition at line 106 of file main.cpp.
References qtwebapp::Logger::installMsgHandler().
       {
         qtwebapp::LoggerWithFile *logger = new qtwebapp::LoggerWithFile(qApp);
         logger->installMsgHandler();
         int res = runQtApplication(argc, argv, logger);
         qWarning("SDRangel quit.");
         return res;
       }