SDRAngel: Bladerf1Input::MsgStartStop Class Reference
Bladerf1Input::MsgStartStop Class Reference
#include <bladerf1input.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 83 of file bladerf1input.h.
Constructor & Destructor Documentation
MsgStartStop()
Bladerf1Input::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 96 of file bladerf1input.h.
References Bladerf1Input::Bladerf1Input(), Bladerf1Input::deserialize(), Bladerf1Input::destroy(), Bladerf1Input::init(), Bladerf1Input::serialize(), Bladerf1Input::start(), Bladerf1Input::stop(), and Bladerf1Input::~Bladerf1Input().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* Bladerf1Input::MsgStartStop::create (bool startStop) inline static
Definition at line 89 of file bladerf1input.h.
Referenced by Bladerf1InputGui::on_startStop_toggled(), and Bladerf1Input::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool Bladerf1Input::MsgStartStop::getStartStop () const inline
Definition at line 87 of file bladerf1input.h.
Referenced by Bladerf1InputGui::handleMessage(), and Bladerf1Input::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool Bladerf1Input::MsgStartStop::m_startStop protected
Definition at line 94 of file bladerf1input.h.
The documentation for this class was generated from the following file:
plugins/samplesource/bladerf1input/bladerf1input.h