SDRAngel: PlutoSDRInputGui Class Reference
PlutoSDRInputGui Class Reference
#include <plutosdrinputgui.h>
Public Member Functions
PlutoSDRInputGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~PlutoSDRInputGui ()
virtual void destroy ()
virtual void setName (const QString &name)
virtual QString getName () const
virtual void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void on_centerFrequency_changed (quint64 value)
void on_loPPM_valueChanged (int value)
void on_dcOffset_toggled (bool checked)
void on_rfDCOffset_toggled (bool checked)
void on_bbDCOffset_toggled (bool checked)
void on_hwIQImbalance_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_swDecim_currentIndexChanged (int index)
void on_fcPos_currentIndexChanged (int index)
void on_sampleRate_changed (quint64 value)
void on_lpf_changed (quint64 value)
void on_lpFIREnable_toggled (bool checked)
void on_lpFIR_changed (quint64 value)
void on_lpFIRDecimation_currentIndexChanged (int index)
void on_lpFIRGain_currentIndexChanged (int index)
void on_gainMode_currentIndexChanged (int index)
void on_gain_valueChanged (int value)
void on_antenna_currentIndexChanged (int index)
void on_transverter_clicked ()
void on_sampleRateMode_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void handleInputMessages ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void displaySettings ()
void displaySampleRate ()
void displayFcTooltip ()
void sendSettings (bool forceSettings=false)
void blockApplySettings (bool block)
void updateSampleRateAndFrequency ()
void setFIRBWLimits ()
void setSampleRateLimits ()
void updateFrequencyLimits ()
Private Attributes
Ui::PlutoSDRInputGUI * ui
DeviceUISet * m_deviceUISet
PlutoSDRInputSettings m_settings
bool m_sampleRateMode
true: device, false: base band sample rate update mode
bool m_forceSettings
QTimer m_updateTimer
QTimer m_statusTimer
DeviceSampleSource * m_sampleSource
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
bool m_doApplySettings
uint32_t m_statusCounter
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 38 of file plutosdrinputgui.h.
Constructor & Destructor Documentation
PlutoSDRInputGui()
PlutoSDRInputGui::PlutoSDRInputGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 34 of file plutosdrinputgui.cpp.
References blockApplySettings(), displaySettings(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, ColorMapper::GrayYellow, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_sampleSource, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), DeviceSampleSource::setMessageQueueToGUI(), DevicePlutoSDR::srHighLimitFreq, DevicePlutoSDR::srLowLimitFreq, ui, updateFrequencyLimits(), updateHardware(), and updateStatus().
                                                                             :
     QWidget(parent),
     ui(new Ui::PlutoSDRInputGUI),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_sampleRateMode(true),
     m_forceSettings(true),
     m_sampleSource(NULL),
     m_sampleRate(0),
     m_deviceCenterFrequency(0),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_doApplySettings(true),
     m_statusCounter(0)
 {
     m_sampleSource = (PlutoSDRInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     updateFrequencyLimits();
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(8, DevicePlutoSDR::srLowLimitFreq, DevicePlutoSDR::srHighLimitFreq);
     ui->lpf->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     quint32 minLimit, maxLimit;
     ((PlutoSDRInput *) m_sampleSource)->getbbLPRange(minLimit, maxLimit);
     ui->lpf->setValueRange(5, minLimit/1000, maxLimit/1000);
     ui->lpFIR->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     ui->lpFIR->setValueRange(5, 1U, 56000U); // will be dynamically recalculated
     ui->swDecimLabel->setText(QString::fromUtf8("S\u2193"));
     ui->lpFIRDecimationLabel->setText(QString::fromUtf8("\u2193"));
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     blockApplySettings(true);
     displaySettings();
     blockApplySettings(false);
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
 }
~PlutoSDRInputGui()
PlutoSDRInputGui::~PlutoSDRInputGui () virtual
Definition at line 84 of file plutosdrinputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void PlutoSDRInputGui::blockApplySettings (bool block) private
Definition at line 446 of file plutosdrinputgui.cpp.
References m_doApplySettings.
Referenced by deserialize(), handleMessage(), and PlutoSDRInputGui().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool PlutoSDRInputGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 126 of file plutosdrinputgui.cpp.
References blockApplySettings(), PlutoSDRInputSettings::deserialize(), displaySettings(), m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data))
     {
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         sendSettings(true);
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void PlutoSDRInputGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 89 of file plutosdrinputgui.cpp.
 {
     delete this;
 }
displayFcTooltip()
void PlutoSDRInputGui::displayFcTooltip () private
Definition at line 379 of file plutosdrinputgui.cpp.
References arg(), DeviceSampleSource::calculateFrequencyShift(), PlutoSDRInputSettings::m_devSampleRate, PlutoSDRInputSettings::m_fcPos, PlutoSDRInputSettings::m_log2Decim, m_settings, and ui.
Referenced by displaySampleRate(), on_fcPos_currentIndexChanged(), and on_sampleRate_changed().
 {
     int32_t fShift = DeviceSampleSource::calculateFrequencyShift(
         m_settings.m_log2Decim,
         (DeviceSampleSource::fcPos_t) m_settings.m_fcPos,
         m_settings.m_devSampleRate,
         DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD
     );
     ui->fcPos->setToolTip(tr("Relative position of device center frequency: %1 kHz").arg(QString::number(fShift / 1000.0f, 'g', 5)));
 }
displaySampleRate()
void PlutoSDRInputGui::displaySampleRate () private
Definition at line 349 of file plutosdrinputgui.cpp.
References arg(), displayFcTooltip(), PlutoSDRInputSettings::m_devSampleRate, PlutoSDRInputSettings::m_log2Decim, m_sampleRateMode, m_settings, DevicePlutoSDR::srHighLimitFreq, DevicePlutoSDR::srLowLimitFreq, and ui.
Referenced by displaySettings(), on_sampleRateMode_toggled(), on_swDecim_currentIndexChanged(), and updateSampleRateAndFrequency().
 {
     ui->sampleRate->blockSignals(true);
     displayFcTooltip();
     if (m_sampleRateMode)
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(60,60,60); }");
         ui->sampleRateMode->setText("SR");
         ui->sampleRate->setValueRange(8, DevicePlutoSDR::srLowLimitFreq, DevicePlutoSDR::srHighLimitFreq);
         ui->sampleRate->setValue(m_settings.m_devSampleRate);
         ui->sampleRate->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setToolTip("Baseband sample rate (S/s)");
         uint32_t basebandSampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Decim);
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(basebandSampleRate / 1000.0f, 'g', 5)));
     }
     else
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(50,50,50); }");
         ui->sampleRateMode->setText("BB");
         ui->sampleRate->setValueRange(8, DevicePlutoSDR::srLowLimitFreq/(1<<m_settings.m_log2Decim), DevicePlutoSDR::srHighLimitFreq/(1<<m_settings.m_log2Decim));
         ui->sampleRate->setValue(m_settings.m_devSampleRate/(1<<m_settings.m_log2Decim));
         ui->sampleRate->setToolTip("Baseband sample rate (S/s)");
         ui->deviceRateText->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_settings.m_devSampleRate / 1000.0f, 'g', 5)));
     }
     ui->sampleRate->blockSignals(false);
 }
displaySettings()
void PlutoSDRInputGui::displaySettings () private
Definition at line 390 of file plutosdrinputgui.cpp.
References arg(), displaySampleRate(), PlutoSDRInputSettings::m_antennaPath, PlutoSDRInputSettings::m_centerFrequency, PlutoSDRInputSettings::m_dcBlock, PlutoSDRInputSettings::m_fcPos, PlutoSDRInputSettings::m_gain, PlutoSDRInputSettings::m_gainMode, PlutoSDRInputSettings::m_hwBBDCBlock, PlutoSDRInputSettings::m_hwIQCorrection, PlutoSDRInputSettings::m_hwRFDCBlock, PlutoSDRInputSettings::m_iqCorrection, PlutoSDRInputSettings::m_log2Decim, PlutoSDRInputSettings::m_LOppmTenths, PlutoSDRInputSettings::m_lpfBW, PlutoSDRInputSettings::m_lpfFIRBW, PlutoSDRInputSettings::m_lpfFIREnable, PlutoSDRInputSettings::m_lpfFIRGain, PlutoSDRInputSettings::m_lpfFIRlog2Decim, m_settings, PlutoSDRInputSettings::m_transverterDeltaFrequency, PlutoSDRInputSettings::m_transverterMode, setFIRBWLimits(), setSampleRateLimits(), ui, and updateFrequencyLimits().
Referenced by deserialize(), handleMessage(), PlutoSDRInputGui(), and setCenterFrequency().
 {
     ui->transverter->setDeltaFrequency(m_settings.m_transverterDeltaFrequency);
     ui->transverter->setDeltaFrequencyActive(m_settings.m_transverterMode);
     updateFrequencyLimits();
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     displaySampleRate();
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqCorrection);
     ui->bbDCOffset->setChecked(m_settings.m_hwBBDCBlock);
     ui->rfDCOffset->setChecked(m_settings.m_hwRFDCBlock);
     ui->hwIQImbalance->setChecked(m_settings.m_hwIQCorrection);
     ui->loPPM->setValue(m_settings.m_LOppmTenths);
     ui->loPPMText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     ui->swDecim->setCurrentIndex(m_settings.m_log2Decim);
     ui->fcPos->setCurrentIndex((int) m_settings.m_fcPos);
     ui->lpf->setValue(m_settings.m_lpfBW / 1000);
     ui->lpFIREnable->setChecked(m_settings.m_lpfFIREnable);
     ui->lpFIR->setValue(m_settings.m_lpfFIRBW / 1000);
     ui->lpFIRDecimation->setCurrentIndex(m_settings.m_lpfFIRlog2Decim);
     ui->lpFIRGain->setCurrentIndex((m_settings.m_lpfFIRGain + 12)/6);
     ui->lpFIRDecimation->setEnabled(m_settings.m_lpfFIREnable);
     ui->lpFIRGain->setEnabled(m_settings.m_lpfFIREnable);
     ui->gainMode->setCurrentIndex((int) m_settings.m_gainMode);
     ui->gain->setValue(m_settings.m_gain);
     ui->gainText->setText(tr("%1").arg(m_settings.m_gain));
     ui->antenna->setCurrentIndex((int) m_settings.m_antennaPath);
     setFIRBWLimits();
     setSampleRateLimits();
 }
getCenterFrequency()
qint64 PlutoSDRInputGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 109 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* PlutoSDRInputGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 53 of file plutosdrinputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString PlutoSDRInputGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 99 of file plutosdrinputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void PlutoSDRInputGui::handleInputMessages () private slot
Definition at line 545 of file plutosdrinputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), setFIRBWLimits(), and updateSampleRateAndFrequency().
Referenced by PlutoSDRInputGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("PlutoSDRInputGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("PlutoSDRInputGui::handleInputMessages: DSPSignalNotification: SampleRate: %d, CenterFrequency: %llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             setFIRBWLimits();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool PlutoSDRInputGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 143 of file plutosdrinputgui.cpp.
References blockApplySettings(), displaySettings(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getDevSampleRate(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getLoPPMTenths(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getLpfFirbw(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getLpfFiRlog2IntDec(), PlutoSDRInput::MsgConfigurePlutoSDR::getSettings(), PlutoSDRInput::MsgStartStop::getStartStop(), DevicePlutoSDRShared::MsgCrossReportToBuddy::isLpfFirEnable(), PlutoSDRInputSettings::m_devSampleRate, PlutoSDRInputSettings::m_LOppmTenths, PlutoSDRInputSettings::m_lpfFIRBW, PlutoSDRInputSettings::m_lpfFIREnable, PlutoSDRInputSettings::m_lpfFIRlog2Decim, m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (PlutoSDRInput::MsgConfigurePlutoSDR::match(message))
     {
         const PlutoSDRInput::MsgConfigurePlutoSDR& cfg = (PlutoSDRInput::MsgConfigurePlutoSDR&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (PlutoSDRInput::MsgStartStop::match(message))
     {
         PlutoSDRInput::MsgStartStop& notif = (PlutoSDRInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else if (DevicePlutoSDRShared::MsgCrossReportToBuddy::match(message)) // message from buddy
     {
         DevicePlutoSDRShared::MsgCrossReportToBuddy& conf = (DevicePlutoSDRShared::MsgCrossReportToBuddy&) message;
         m_settings.m_devSampleRate = conf.getDevSampleRate();
         m_settings.m_lpfFIRlog2Decim = conf.getLpfFiRlog2IntDec();
         m_settings.m_lpfFIRBW = conf.getLpfFirbw();
         m_settings.m_LOppmTenths = conf.getLoPPMTenths();
         m_settings.m_lpfFIREnable = conf.isLpfFirEnable();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_antenna_currentIndexChanged
void PlutoSDRInputGui::on_antenna_currentIndexChanged (int index) private slot
Definition at line 327 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_antennaPath, m_settings, PlutoSDRInputSettings::RFPATH_END, and sendSettings().
 {
     m_settings.m_antennaPath = (PlutoSDRInputSettings::RFPath) (index < PlutoSDRInputSettings::RFPATH_END ? index : 0);
     sendSettings();
 }
on_bbDCOffset_toggled
void PlutoSDRInputGui::on_bbDCOffset_toggled (bool checked) private slot
Definition at line 235 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_hwBBDCBlock, m_settings, and sendSettings().
 {
     m_settings.m_hwBBDCBlock = checked;
     sendSettings();
 }
on_centerFrequency_changed
void PlutoSDRInputGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 204 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_dcOffset_toggled
void PlutoSDRInputGui::on_dcOffset_toggled (bool checked) private slot
Definition at line 217 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_fcPos_currentIndexChanged
void PlutoSDRInputGui::on_fcPos_currentIndexChanged (int index) private slot
Definition at line 261 of file plutosdrinputgui.cpp.
References displayFcTooltip(), PlutoSDRInputSettings::FC_POS_CENTER, PlutoSDRInputSettings::FC_POS_END, PlutoSDRInputSettings::m_fcPos, m_settings, and sendSettings().
 {
     m_settings.m_fcPos = (PlutoSDRInputSettings::fcPos_t) (index < (int) PlutoSDRInputSettings::FC_POS_END ? index : PlutoSDRInputSettings::FC_POS_CENTER);
     displayFcTooltip();
     sendSettings();
 }
on_gain_valueChanged
void PlutoSDRInputGui::on_gain_valueChanged (int value) private slot
Definition at line 320 of file plutosdrinputgui.cpp.
References arg(), PlutoSDRInputSettings::m_gain, m_settings, sendSettings(), and ui.
 {
     ui->gainText->setText(tr("%1").arg(value));
     m_settings.m_gain = value;
     sendSettings();
 }
on_gainMode_currentIndexChanged
void PlutoSDRInputGui::on_gainMode_currentIndexChanged (int index) private slot
Definition at line 313 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::GAIN_END, PlutoSDRInputSettings::GAIN_MANUAL, PlutoSDRInputSettings::m_gainMode, m_settings, sendSettings(), and ui.
 {
     m_settings.m_gainMode = (PlutoSDRInputSettings::GainMode) (index < PlutoSDRInputSettings::GAIN_END ? index : 0);
     ui->gain->setEnabled(m_settings.m_gainMode == PlutoSDRInputSettings::GAIN_MANUAL);
     sendSettings();
 }
on_hwIQImbalance_toggled
void PlutoSDRInputGui::on_hwIQImbalance_toggled (bool checked) private slot
Definition at line 241 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_hwIQCorrection, m_settings, and sendSettings().
 {
     m_settings.m_hwIQCorrection = checked;
     sendSettings();
 }
on_iqImbalance_toggled
void PlutoSDRInputGui::on_iqImbalance_toggled (bool checked) private slot
Definition at line 223 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_iqCorrection, m_settings, and sendSettings().
 {
     m_settings.m_iqCorrection = checked;
     sendSettings();
 }
on_loPPM_valueChanged
void PlutoSDRInputGui::on_loPPM_valueChanged (int value) private slot
Definition at line 210 of file plutosdrinputgui.cpp.
References arg(), PlutoSDRInputSettings::m_LOppmTenths, m_settings, sendSettings(), and ui.
 {
     ui->loPPMText->setText(QString("%1").arg(QString::number(value/10.0, 'f', 1)));
     m_settings.m_LOppmTenths = value;
     sendSettings();
 }
on_lpf_changed
void PlutoSDRInputGui::on_lpf_changed (quint64 value) private slot
Definition at line 280 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_lpfBW, m_settings, and sendSettings().
 {
     m_settings.m_lpfBW = value * 1000;
     sendSettings();
 }
on_lpFIR_changed
void PlutoSDRInputGui::on_lpFIR_changed (quint64 value) private slot
Definition at line 294 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_lpfFIRBW, m_settings, and sendSettings().
 {
     m_settings.m_lpfFIRBW = value * 1000;
     sendSettings();
 }
on_lpFIRDecimation_currentIndexChanged
void PlutoSDRInputGui::on_lpFIRDecimation_currentIndexChanged (int index) private slot
Definition at line 300 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_lpfFIRlog2Decim, m_settings, sendSettings(), and setSampleRateLimits().
 {
     m_settings.m_lpfFIRlog2Decim = index > 2 ? 2 : index;
     setSampleRateLimits();
     sendSettings();
 }
on_lpFIREnable_toggled
void PlutoSDRInputGui::on_lpFIREnable_toggled (bool checked) private slot
Definition at line 286 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_lpfFIREnable, m_settings, sendSettings(), and ui.
 {
     m_settings.m_lpfFIREnable = checked;
     ui->lpFIRDecimation->setEnabled(checked);
     ui->lpFIRGain->setEnabled(checked);
     sendSettings();
 }
on_lpFIRGain_currentIndexChanged
void PlutoSDRInputGui::on_lpFIRGain_currentIndexChanged (int index) private slot
Definition at line 307 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_lpfFIRGain, m_settings, and sendSettings().
 {
     m_settings.m_lpfFIRGain = 6*(index > 3 ? 3 : index) - 12;
     sendSettings();
 }
on_record_toggled
void PlutoSDRInputGui::on_record_toggled (bool checked) private slot
Definition at line 192 of file plutosdrinputgui.cpp.
References PlutoSDRInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     PlutoSDRInput::MsgFileRecord* message = PlutoSDRInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_rfDCOffset_toggled
void PlutoSDRInputGui::on_rfDCOffset_toggled (bool checked) private slot
Definition at line 229 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_hwRFDCBlock, m_settings, and sendSettings().
 {
     m_settings.m_hwRFDCBlock = checked;
     sendSettings();
 }
on_sampleRate_changed
void PlutoSDRInputGui::on_sampleRate_changed (quint64 value) private slot
Definition at line 268 of file plutosdrinputgui.cpp.
References displayFcTooltip(), PlutoSDRInputSettings::m_devSampleRate, PlutoSDRInputSettings::m_log2Decim, m_sampleRateMode, m_settings, and sendSettings().
 {
     m_settings.m_devSampleRate = value;
     if (!m_sampleRateMode) {
         m_settings.m_devSampleRate <<= m_settings.m_log2Decim;
     }
     displayFcTooltip();
     sendSettings();
 }
on_sampleRateMode_toggled
void PlutoSDRInputGui::on_sampleRateMode_toggled (bool checked) private slot
Definition at line 343 of file plutosdrinputgui.cpp.
References displaySampleRate(), and m_sampleRateMode.
 {
     m_sampleRateMode = checked;
     displaySampleRate();
 }
on_startStop_toggled
void PlutoSDRInputGui::on_startStop_toggled (bool checked) private slot
Definition at line 183 of file plutosdrinputgui.cpp.
References PlutoSDRInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         PlutoSDRInput::MsgStartStop *message = PlutoSDRInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
on_swDecim_currentIndexChanged
void PlutoSDRInputGui::on_swDecim_currentIndexChanged (int index) private slot
Definition at line 248 of file plutosdrinputgui.cpp.
References displaySampleRate(), PlutoSDRInputSettings::m_devSampleRate, PlutoSDRInputSettings::m_log2Decim, m_sampleRateMode, m_settings, sendSettings(), and ui.
 {
     m_settings.m_log2Decim = index > 6 ? 6 : index;
     displaySampleRate();
     m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     if (!m_sampleRateMode) {
         m_settings.m_devSampleRate <<= m_settings.m_log2Decim;
     }
     sendSettings();
 }
on_transverter_clicked
void PlutoSDRInputGui::on_transverter_clicked () private slot
Definition at line 333 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_centerFrequency, m_settings, PlutoSDRInputSettings::m_transverterDeltaFrequency, PlutoSDRInputSettings::m_transverterMode, sendSettings(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("PlutoSDRInputGui::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     m_settings.m_centerFrequency = ui->centerFrequency->getValueNew()*1000;
     sendSettings();
 }
openDeviceSettingsDialog
void PlutoSDRInputGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 581 of file plutosdrinputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), PlutoSDRInputSettings::m_reverseAPIAddress, PlutoSDRInputSettings::m_reverseAPIDeviceIndex, PlutoSDRInputSettings::m_reverseAPIPort, m_settings, PlutoSDRInputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by PlutoSDRInputGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void PlutoSDRInputGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 104 of file plutosdrinputgui.cpp.
Referenced by deserialize().
 {
 }
sendSettings()
void PlutoSDRInputGui::sendSettings (bool forceSettings = false) private
Definition at line 428 of file plutosdrinputgui.cpp.
References m_forceSettings, and m_updateTimer.
Referenced by deserialize(), on_antenna_currentIndexChanged(), on_bbDCOffset_toggled(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_fcPos_currentIndexChanged(), on_gain_valueChanged(), on_gainMode_currentIndexChanged(), on_hwIQImbalance_toggled(), on_iqImbalance_toggled(), on_loPPM_valueChanged(), on_lpf_changed(), on_lpFIR_changed(), on_lpFIRDecimation_currentIndexChanged(), on_lpFIREnable_toggled(), on_lpFIRGain_currentIndexChanged(), on_rfDCOffset_toggled(), on_sampleRate_changed(), on_swDecim_currentIndexChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), and setCenterFrequency().
 {
     m_forceSettings = forceSettings;
     if(!m_updateTimer.isActive()) { m_updateTimer.start(100); }
 }
serialize()
QByteArray PlutoSDRInputGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 121 of file plutosdrinputgui.cpp.
References m_settings, and PlutoSDRInputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void PlutoSDRInputGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 114 of file plutosdrinputgui.cpp.
References displaySettings(), PlutoSDRInputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setFIRBWLimits()
void PlutoSDRInputGui::setFIRBWLimits () private
Definition at line 512 of file plutosdrinputgui.cpp.
References DevicePlutoSDR::firBWHighLimitFactor, DevicePlutoSDR::firBWLowLimitFactor, PlutoSDRInputSettings::m_lpfFIRBW, m_sampleSource, m_settings, and ui.
Referenced by displaySettings(), and handleInputMessages().
 {
     float high = DevicePlutoSDR::firBWHighLimitFactor * ((PlutoSDRInput *) m_sampleSource)->getFIRSampleRate();
     float low = DevicePlutoSDR::firBWLowLimitFactor * ((PlutoSDRInput *) m_sampleSource)->getFIRSampleRate();
     ui->lpFIR->setValueRange(5, (int(low)/1000)+1, (int(high)/1000)+1);
     ui->lpFIR->setValue(m_settings.m_lpfFIRBW/1000);
 }
setName()
void PlutoSDRInputGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 94 of file plutosdrinputgui.cpp.
 {
     setObjectName(name);
 }
setSampleRateLimits()
void PlutoSDRInputGui::setSampleRateLimits () private
Definition at line 520 of file plutosdrinputgui.cpp.
References PlutoSDRInputSettings::m_devSampleRate, m_settings, DevicePlutoSDR::srHighLimitFreq, DevicePlutoSDR::srLowLimitFreq, and ui.
Referenced by displaySettings(), and on_lpFIRDecimation_currentIndexChanged().
 {
     uint32_t low = ui->lpFIREnable->isChecked() ? DevicePlutoSDR::srLowLimitFreq / (1<<ui->lpFIRDecimation->currentIndex()) : DevicePlutoSDR::srLowLimitFreq;
     ui->sampleRate->setValueRange(8, low, DevicePlutoSDR::srHighLimitFreq);
     ui->sampleRate->setValue(m_settings.m_devSampleRate);
 }
updateFrequencyLimits()
void PlutoSDRInputGui::updateFrequencyLimits () private
Definition at line 527 of file plutosdrinputgui.cpp.
References m_sampleSource, m_settings, PlutoSDRInputSettings::m_transverterDeltaFrequency, PlutoSDRInputSettings::m_transverterMode, and ui.
Referenced by displaySettings(), on_transverter_clicked(), and PlutoSDRInputGui().
 {
     qint64 minLimit, maxLimit;
     // values should be in kHz
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     ((PlutoSDRInput *) m_sampleSource)->getLORange(minLimit, maxLimit);
     minLimit = minLimit/1000 + deltaFrequency;
     maxLimit = maxLimit/1000 + deltaFrequency;
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("PlutoSDRInputGui::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void PlutoSDRInputGui::updateHardware () private slot
Definition at line 434 of file plutosdrinputgui.cpp.
References PlutoSDRInput::MsgConfigurePlutoSDR::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by PlutoSDRInputGui().
 {
     if (m_doApplySettings)
     {
         qDebug() << "PlutoSDRInputGui::updateHardware";
         PlutoSDRInput::MsgConfigurePlutoSDR* message = PlutoSDRInput::MsgConfigurePlutoSDR::create(m_settings, m_forceSettings);
         m_sampleSource->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void PlutoSDRInputGui::updateSampleRateAndFrequency () private
Definition at line 574 of file plutosdrinputgui.cpp.
References displaySampleRate(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), and GLSpectrum::setSampleRate().
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     displaySampleRate();
 }
updateStatus
void PlutoSDRInputGui::updateStatus () private slot
Definition at line 451 of file plutosdrinputgui.cpp.
References arg(), DeviceAPI::errorMessage(), DeviceAPI::isBuddyLeader(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, m_sampleSource, m_statusCounter, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by PlutoSDRInputGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
     if (m_statusCounter % 2 == 0) // 1s
     {
         uint32_t adcRate = ((PlutoSDRInput *) m_sampleSource)->getADCSampleRate();
         if (adcRate < 100000000) {
             ui->adcRateText->setText(tr("%1k").arg(QString::number(adcRate / 1000.0f, 'g', 5)));
         } else {
             ui->adcRateText->setText(tr("%1M").arg(QString::number(adcRate / 1000000.0f, 'g', 5)));
         }
     }
     if (m_statusCounter % 4 == 0) // 2s
     {
         std::string rssiStr;
         ((PlutoSDRInput *) m_sampleSource)->getRSSI(rssiStr);
         ui->rssiText->setText(tr("-%1").arg(QString::fromStdString(rssiStr)));
         int gaindB;
         ((PlutoSDRInput *) m_sampleSource)->getGain(gaindB);
         ui->actualGainText->setText(tr("%1").arg(gaindB));
     }
     if (m_statusCounter % 10 == 0) // 5s
     {
         if (m_deviceUISet->m_deviceAPI->isBuddyLeader()) {
             ((PlutoSDRInput *) m_sampleSource)->fetchTemperature();
         }
         ui->temperatureText->setText(tr("%1C").arg(QString::number(((PlutoSDRInput *) m_sampleSource)->getTemperature(), 'f', 0)));
     }
     m_statusCounter++;
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 PlutoSDRInputGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 66 of file plutosdrinputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* PlutoSDRInputGui::m_deviceUISet private
Definition at line 58 of file plutosdrinputgui.h.
Referenced by PlutoSDRInputGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool PlutoSDRInputGui::m_doApplySettings private
Definition at line 68 of file plutosdrinputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_forceSettings
bool PlutoSDRInputGui::m_forceSettings private
Definition at line 61 of file plutosdrinputgui.h.
Referenced by sendSettings(), and updateHardware().
m_inputMessageQueue
MessageQueue PlutoSDRInputGui::m_inputMessageQueue private
Definition at line 70 of file plutosdrinputgui.h.
Referenced by handleInputMessages(), and PlutoSDRInputGui().
m_lastEngineState
int PlutoSDRInputGui::m_lastEngineState private
Definition at line 67 of file plutosdrinputgui.h.
Referenced by updateStatus().
m_sampleRate
int PlutoSDRInputGui::m_sampleRate private
Definition at line 65 of file plutosdrinputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateMode
bool PlutoSDRInputGui::m_sampleRateMode private
true: device, false: base band sample rate update mode
Definition at line 60 of file plutosdrinputgui.h.
Referenced by displaySampleRate(), on_sampleRate_changed(), on_sampleRateMode_toggled(), and on_swDecim_currentIndexChanged().
m_sampleSource
DeviceSampleSource* PlutoSDRInputGui::m_sampleSource private
Definition at line 64 of file plutosdrinputgui.h.
Referenced by on_record_toggled(), on_startStop_toggled(), PlutoSDRInputGui(), setFIRBWLimits(), updateFrequencyLimits(), updateHardware(), and updateStatus().
m_settings
PlutoSDRInputSettings PlutoSDRInputGui::m_settings private
Definition at line 59 of file plutosdrinputgui.h.
Referenced by deserialize(), displayFcTooltip(), displaySampleRate(), displaySettings(), getCenterFrequency(), handleMessage(), on_antenna_currentIndexChanged(), on_bbDCOffset_toggled(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_fcPos_currentIndexChanged(), on_gain_valueChanged(), on_gainMode_currentIndexChanged(), on_hwIQImbalance_toggled(), on_iqImbalance_toggled(), on_loPPM_valueChanged(), on_lpf_changed(), on_lpFIR_changed(), on_lpFIRDecimation_currentIndexChanged(), on_lpFIREnable_toggled(), on_lpFIRGain_currentIndexChanged(), on_rfDCOffset_toggled(), on_sampleRate_changed(), on_swDecim_currentIndexChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), serialize(), setCenterFrequency(), setFIRBWLimits(), setSampleRateLimits(), updateFrequencyLimits(), and updateHardware().
m_statusCounter
uint32_t PlutoSDRInputGui::m_statusCounter private
Definition at line 69 of file plutosdrinputgui.h.
Referenced by updateStatus().
m_statusTimer
QTimer PlutoSDRInputGui::m_statusTimer private
Definition at line 63 of file plutosdrinputgui.h.
Referenced by PlutoSDRInputGui().
m_updateTimer
QTimer PlutoSDRInputGui::m_updateTimer private
Definition at line 62 of file plutosdrinputgui.h.
Referenced by PlutoSDRInputGui(), sendSettings(), and updateHardware().
ui
Ui::PlutoSDRInputGUI* PlutoSDRInputGui::ui private
Definition at line 57 of file plutosdrinputgui.h.
Referenced by displayFcTooltip(), displaySampleRate(), displaySettings(), handleMessage(), on_gain_valueChanged(), on_gainMode_currentIndexChanged(), on_loPPM_valueChanged(), on_lpFIREnable_toggled(), on_record_toggled(), on_swDecim_currentIndexChanged(), on_transverter_clicked(), PlutoSDRInputGui(), setFIRBWLimits(), setSampleRateLimits(), updateFrequencyLimits(), updateStatus(), and ~PlutoSDRInputGui().
The documentation for this class was generated from the following files:
plugins/samplesource/plutosdrinput/plutosdrinputgui.h
plugins/samplesource/plutosdrinput/plutosdrinputgui.cpp