SDRAngel: PlutoSDROutputThread Class Reference
PlutoSDROutputThread Class Reference
#include <plutosdroutputthread.h>
Public Member Functions
PlutoSDROutputThread (uint32_t blocksize, DevicePlutoSDRBox *plutoBox, SampleSourceFifo *sampleFifo, QObject *parent=0)
~PlutoSDROutputThread ()
virtual void startWork ()
virtual void stopWork ()
virtual void setDeviceSampleRate (int sampleRate)
virtual bool isRunning ()
void setLog2Interpolation (unsigned int log2_interp)
Private Member Functions
void run ()
void convert (qint16 *buf, qint32 len)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
DevicePlutoSDRBox * m_plutoBox
int16_t * m_buf
holds I+Q values of each sample from devce
uint32_t m_blockSizeSamples
buffer sizes in number of (I,Q) samples
SampleSourceFifo * m_sampleFifo
DSP sample FIFO (I,Q)
unsigned int m_log2Interp
Interpolators< qint16, SDR_TX_SAMP_SZ, 16 > m_interpolators
Pluto is on 12 bit but iio_channel_convert_inverse converts from 16 to 12 bits.
Detailed Description
Definition at line 31 of file plutosdroutputthread.h.
Constructor & Destructor Documentation
PlutoSDROutputThread()
PlutoSDROutputThread::PlutoSDROutputThread (uint32_t blocksize, DevicePlutoSDRBox * plutoBox, SampleSourceFifo * sampleFifo, QObject * parent = 0)
Definition at line 23 of file plutosdroutputthread.cpp.
References m_buf.
                                                                                                                                                 :
     QThread(parent),
     m_running(false),
     m_plutoBox(plutoBox),
     m_blockSizeSamples(blocksizeSamples),
     m_sampleFifo(sampleFifo),
     m_log2Interp(0)
 {
     m_buf = new qint16[blocksizeSamples*2];
 //    m_bufConv = new qint16[blocksizeSamples*(sizeof(Sample)/sizeof(qint16))];
 }
~PlutoSDROutputThread()
PlutoSDROutputThread::~PlutoSDROutputThread ()
Definition at line 35 of file plutosdroutputthread.cpp.
References m_buf, and stopWork().
 {
     stopWork();
     delete[] m_buf;
 }
Member Function Documentation
convert()
void PlutoSDROutputThread::convert (qint16 * buf, qint32 len) private
Definition at line 115 of file plutosdroutputthread.cpp.
References Interpolators< T, SdrBits, OutputBits >::interpolate1(), Interpolators< T, SdrBits, OutputBits >::interpolate16_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate2_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate32_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate4_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate64_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate8_cen(), m_interpolators, m_log2Interp, m_sampleFifo, and SampleSourceFifo::readAdvance().
Referenced by run().
 {
     // pull samples from baseband generator
     SampleVector::iterator beginRead;
     m_sampleFifo->readAdvance(beginRead, len/(2*(1<<m_log2Interp)));
     beginRead -= len/2;
     if (m_log2Interp == 0)
     {
         m_interpolators.interpolate1(&beginRead, buf, len);
     }
     else
     {
         switch (m_log2Interp)
         {
         case 1:
             m_interpolators.interpolate2_cen(&beginRead, buf, len);
             break;
         case 2:
             m_interpolators.interpolate4_cen(&beginRead, buf, len);
             break;
         case 3:
             m_interpolators.interpolate8_cen(&beginRead, buf, len);
             break;
         case 4:
             m_interpolators.interpolate16_cen(&beginRead, buf, len);
             break;
         case 5:
             m_interpolators.interpolate32_cen(&beginRead, buf, len);
             break;
         case 6:
             m_interpolators.interpolate64_cen(&beginRead, buf, len);
             break;
         default:
             break;
         }
     }
 }
isRunning()
virtual bool PlutoSDROutputThread::isRunning () inline virtual
Implements DevicePlutoSDRShared::ThreadInterface.
Definition at line 42 of file plutosdroutputthread.h.
References m_running, and setLog2Interpolation().
Referenced by PlutoSDROutput::applySettings().
 { return m_running; }
run()
void PlutoSDROutputThread::run () private
Definition at line 65 of file plutosdroutputthread.cpp.
References convert(), DevicePlutoSDRBox::getRxSampleSize(), DevicePlutoSDRBox::getTxSampleSize(), m_blockSizeSamples, m_buf, m_plutoBox, m_running, m_startWaiter, DevicePlutoSDRBox::txBufferEnd(), DevicePlutoSDRBox::txBufferFirst(), DevicePlutoSDRBox::txBufferPush(), DevicePlutoSDRBox::txBufferStep(), and DevicePlutoSDRBox::txChannelConvert().
 {
     std::ptrdiff_t p_inc = m_plutoBox->txBufferStep();
     qDebug("PlutoSDROutputThread::run: txBufferStep: %ld bytes", p_inc);
     qDebug("PlutoSDROutputThread::run: Rx sample size is %ld bytes", m_plutoBox->getRxSampleSize());
     qDebug("PlutoSDROutputThread::run: Tx sample size is %ld bytes", m_plutoBox->getTxSampleSize());
     qDebug("PlutoSDROutputThread::run: nominal nbytes_tx is %d bytes", m_blockSizeSamples*4);
     m_running = true;
     m_startWaiter.wakeAll();
     while (m_running)
     {
         ssize_t nbytes_tx;
         char *p_dat, *p_end;
         int ihs; // half sample index (I then Q to make a sample)
         convert(m_buf, 2*m_blockSizeSamples); // size given in number of int16_t (I and Q interleaved)
         // WRITE: Get pointers to TX buf and write IQ to TX buf port 0
         p_end = m_plutoBox->txBufferEnd();
         ihs = 0;
         // p_inc is 2 on a char* buffer therefore each iteration processes only the I or Q sample
         // I and Q samples are processed one after the other
         // conversion is not needed as samples are little endian
         for (p_dat = m_plutoBox->txBufferFirst(), ihs = 0; p_dat < p_end; p_dat += p_inc, ihs += 2)
         {
             m_plutoBox->txChannelConvert((int16_t*) p_dat, &m_buf[ihs]);
         }
         // Schedule TX buffer for sending
         nbytes_tx = m_plutoBox->txBufferPush();
         if (nbytes_tx != 4*m_blockSizeSamples)
         {
             qDebug("PlutoSDROutputThread::run: error pushing buf %d / %d", (int) nbytes_tx, (int) 4*m_blockSizeSamples);
             usleep(200000);
             continue;
         }
     }
     m_running = false;
 }
setDeviceSampleRate()
virtual void PlutoSDROutputThread::setDeviceSampleRate (int sampleRate) inline virtual
Implements DevicePlutoSDRShared::ThreadInterface.
Definition at line 41 of file plutosdroutputthread.h.
 { (void) sampleRate; }
setLog2Interpolation()
void PlutoSDROutputThread::setLog2Interpolation (unsigned int log2_interp)
Definition at line 60 of file plutosdroutputthread.cpp.
References m_log2Interp.
Referenced by PlutoSDROutput::applySettings(), isRunning(), and PlutoSDROutput::start().
 {
     m_log2Interp = log2_interp;
 }
startWork()
void PlutoSDROutputThread::startWork () virtual
Implements DevicePlutoSDRShared::ThreadInterface.
Definition at line 41 of file plutosdroutputthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by PlutoSDROutput::applySettings(), and PlutoSDROutput::start().
 {
     if (m_running) return; // return if running already
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void PlutoSDROutputThread::stopWork () virtual
Implements DevicePlutoSDRShared::ThreadInterface.
Definition at line 52 of file plutosdroutputthread.cpp.
References m_running.
Referenced by PlutoSDROutput::applySettings(), PlutoSDROutput::stop(), and ~PlutoSDROutputThread().
 {
     if (!m_running) return; // return if not running
     m_running = false;
     wait();
 }
Member Data Documentation
m_blockSizeSamples
uint32_t PlutoSDROutputThread::m_blockSizeSamples private
buffer sizes in number of (I,Q) samples
Definition at line 53 of file plutosdroutputthread.h.
Referenced by run().
m_buf
int16_t* PlutoSDROutputThread::m_buf private
holds I+Q values of each sample from devce
Definition at line 51 of file plutosdroutputthread.h.
Referenced by PlutoSDROutputThread(), run(), and ~PlutoSDROutputThread().
m_interpolators
Interpolators<qint16, SDR_TX_SAMP_SZ, 16> PlutoSDROutputThread::m_interpolators private
Pluto is on 12 bit but iio_channel_convert_inverse converts from 16 to 12 bits.
Definition at line 58 of file plutosdroutputthread.h.
Referenced by convert().
m_log2Interp
unsigned int PlutoSDROutputThread::m_log2Interp private
Definition at line 56 of file plutosdroutputthread.h.
Referenced by convert(), and setLog2Interpolation().
m_plutoBox
DevicePlutoSDRBox* PlutoSDROutputThread::m_plutoBox private
Definition at line 50 of file plutosdroutputthread.h.
Referenced by run().
m_running
bool PlutoSDROutputThread::m_running private
Definition at line 48 of file plutosdroutputthread.h.
Referenced by isRunning(), run(), startWork(), and stopWork().
m_sampleFifo
SampleSourceFifo* PlutoSDROutputThread::m_sampleFifo private
DSP sample FIFO (I,Q)
Definition at line 54 of file plutosdroutputthread.h.
Referenced by convert().
m_startWaiter
QWaitCondition PlutoSDROutputThread::m_startWaiter private
Definition at line 47 of file plutosdroutputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex PlutoSDROutputThread::m_startWaitMutex private
Definition at line 46 of file plutosdroutputthread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/samplesink/plutosdroutput/plutosdroutputthread.h
plugins/samplesink/plutosdroutput/plutosdroutputthread.cpp