SDRAngel: UDPSourceUDPHandler Class Reference
UDPSourceUDPHandler Class Reference
#include <udpsourceudphandler.h>
Inherits QObject.
Classes
class MsgUDPAddressAndPort
Public Slots
void dataReadyRead ()
Public Member Functions
UDPSourceUDPHandler ()
virtual ~UDPSourceUDPHandler ()
void start ()
void stop ()
void configureUDPLink (const QString &address, quint16 port)
void resetReadIndex ()
void resizeBuffer (float sampleRate)
void readSample (qint16 &t)
audio mono
void readSample (AudioSample &a)
audio stereo
void readSample (Sample &s)
I/Q stream.
void setAutoRWBalance (bool autoRWBalance)
void setFeedbackMessageQueue (MessageQueue *messageQueue)
int32_t getBufferGauge () const
Static Public Attributes
static const int m_udpBlockSize = 512
static const int m_minNbUDPFrames = 256
Private Slots
void handleMessages ()
Private Member Functions
typedef char (udpBlk_t)[m_udpBlockSize]
void moveData (char *blk)
void advanceReadPointer (int nbBytes)
void applyUDPLink (const QString &address, quint16 port)
bool handleMessage (const Message &message)
Private Attributes
QUdpSocket * m_dataSocket
QHostAddress m_dataAddress
QHostAddress m_remoteAddress
quint16 m_dataPort
quint16 m_remotePort
bool m_dataConnected
udpBlk_t * m_udpBuf
char m_udpDump [m_udpBlockSize+8192]
int m_udpDumpIndex
int m_nbUDPFrames
int m_nbAllocatedUDPFrames
int m_writeFrameIndex
int m_readFrameIndex
int m_readIndex
int m_rwDelta
float m_d
bool m_autoRWBalance
MessageQueue * m_feedbackMessageQueue
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 31 of file udpsourceudphandler.h.
Constructor & Destructor Documentation
UDPSourceUDPHandler()
UDPSourceUDPHandler::UDPSourceUDPHandler ()
Definition at line 28 of file udpsourceudphandler.cpp.
                                          :
     m_dataSocket(0),
     m_dataAddress(QHostAddress::LocalHost),
     m_remoteAddress(QHostAddress::LocalHost),
     m_dataPort(9999),
     m_remotePort(0),
     m_dataConnected(false),
     m_udpDumpIndex(0),
     m_nbUDPFrames(m_minNbUDPFrames),
     m_nbAllocatedUDPFrames(m_minNbUDPFrames),
     m_writeFrameIndex(0),
     m_readFrameIndex(m_minNbUDPFrames/2),
     m_readIndex(0),
     m_rwDelta(m_minNbUDPFrames/2),
     m_d(0),
     m_autoRWBalance(true),
     m_feedbackMessageQueue(0)
 {
     m_udpBuf = new udpBlk_t[m_minNbUDPFrames];
     std::fill(m_udpDump, m_udpDump + m_udpBlockSize + 8192, 0);
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleMessages()));
 }
~UDPSourceUDPHandler()
UDPSourceUDPHandler::~UDPSourceUDPHandler () virtual
Definition at line 51 of file udpsourceudphandler.cpp.
References m_udpBuf.
 {
     delete[] m_udpBuf;
 }
Member Function Documentation
advanceReadPointer()
void UDPSourceUDPHandler::advanceReadPointer (int nbBytes) private
Definition at line 184 of file udpsourceudphandler.cpp.
References UDPSourceMessages::MsgSampleRateCorrection::create(), m_autoRWBalance, m_d, m_feedbackMessageQueue, m_nbUDPFrames, m_readFrameIndex, m_readIndex, m_rwDelta, m_udpBlockSize, m_writeFrameIndex, MessageQueue::push(), and resetReadIndex().
Referenced by UDPSourceUDPHandler::MsgUDPAddressAndPort::MsgUDPAddressAndPort(), and readSample().
 {
     if (m_readIndex < m_udpBlockSize - 2*nbBytes)
     {
         m_readIndex += nbBytes;
     }
     else
     {
         m_readIndex = 0;
         if (m_readFrameIndex < m_nbUDPFrames - 1)
         {
             m_readFrameIndex++;
         }
         else
         {
             m_rwDelta = m_writeFrameIndex; // raw R/W delta estimate
             int nbUDPFrames2 = m_nbUDPFrames/2;
             float d = (m_rwDelta - nbUDPFrames2)/(float) m_nbUDPFrames;
             //qDebug("UDPSourceUDPHandler::advanceReadPointer: w: %02d d: %f", m_writeIndex, d);
             if ((d < -0.45) || (d > 0.45))
             {
                 resetReadIndex();
             }
             else
             {
                 float dd = d - m_d; // derivative
                 float c = (d / 15.0) + (dd / 20.0); // damping and scaling
                 c = c < -0.05 ? -0.05 : c > 0.05 ? 0.05 : c; // limit
                 UDPSourceMessages::MsgSampleRateCorrection *msg = UDPSourceMessages::MsgSampleRateCorrection::create(c, d);
                 if (m_autoRWBalance && m_feedbackMessageQueue) {
                     m_feedbackMessageQueue->push(msg);
                 }
                 m_readFrameIndex = 0;
                 m_d = d;
             }
         }
     }
 }
applyUDPLink()
void UDPSourceUDPHandler::applyUDPLink (const QString & address, quint16 port) private
Definition at line 233 of file udpsourceudphandler.cpp.
References m_dataAddress, m_dataPort, resetReadIndex(), start(), and stop().
Referenced by handleMessage(), and UDPSourceUDPHandler::MsgUDPAddressAndPort::MsgUDPAddressAndPort().
 {
     qDebug("UDPSourceUDPHandler::configureUDPLink: %s:%d", address.toStdString().c_str(), port);
     bool addressOK = m_dataAddress.setAddress(address);
     if (!addressOK)
     {
         qWarning("UDPSourceUDPHandler::configureUDPLink: invalid address %s. Set to localhost.", address.toStdString().c_str());
         m_dataAddress = QHostAddress::LocalHost;
     }
     stop();
     m_dataPort = port;
     resetReadIndex();
     start();
 }
char()
typedef UDPSourceUDPHandler::char (udpBlk_t) private
Referenced by UDPSourceUDPHandler::MsgUDPAddressAndPort::MsgUDPAddressAndPort().
configureUDPLink()
void UDPSourceUDPHandler::configureUDPLink (const QString & address, quint16 port)
Definition at line 227 of file udpsourceudphandler.cpp.
References UDPSourceUDPHandler::MsgUDPAddressAndPort::create(), m_inputMessageQueue, and MessageQueue::push().
Referenced by UDPSource::applySettings().
 {
     Message* msg = MsgUDPAddressAndPort::create(address, port);
     m_inputMessageQueue.push(msg);
 }
dataReadyRead
void UDPSourceUDPHandler::dataReadyRead () slot
Definition at line 99 of file udpsourceudphandler.cpp.
References m_dataConnected, m_dataSocket, m_remoteAddress, m_remotePort, m_udpBlockSize, m_udpDump, m_udpDumpIndex, and moveData().
Referenced by start(), and stop().
 {
     while (m_dataSocket->hasPendingDatagrams() && m_dataConnected)
     {
         qint64 pendingDataSize = m_dataSocket->pendingDatagramSize();
         qint64 bytesRead = m_dataSocket->readDatagram(&m_udpDump[m_udpDumpIndex], pendingDataSize, &m_remoteAddress, &m_remotePort);
         if (bytesRead < 0)
         {
             qWarning("UDPSourceUDPHandler::dataReadyRead: UDP read error");
         }
         else
         {
             int udpDumpSize = m_udpDumpIndex + bytesRead;
             int udpDumpPtr = 0;
             while (udpDumpSize >= m_udpBlockSize)
             {
                 moveData(&m_udpDump[udpDumpPtr]);
                 udpDumpPtr += m_udpBlockSize;
                 udpDumpSize -= m_udpBlockSize;
             }
             if (udpDumpSize > 0)
             {
                 memcpy(m_udpDump, &m_udpDump[udpDumpPtr], udpDumpSize);
             }
             m_udpDumpIndex = udpDumpSize;
         }
     }
 }
getBufferGauge()
int32_t UDPSourceUDPHandler::getBufferGauge () const inline
Get buffer gauge value in % of buffer size ([-50:50]) [-50:0] : write leads or read lags [0:50] : read leads or write lags
Definition at line 55 of file udpsourceudphandler.h.
References m_nbUDPFrames, and m_rwDelta.
Referenced by UDPSource::getBufferGauge().
     {
         int32_t val = m_rwDelta - (m_nbUDPFrames/2);
         return (100*val) / m_nbUDPFrames;
     }
handleMessage()
bool UDPSourceUDPHandler::handleMessage (const Message & message) private
Definition at line 289 of file udpsourceudphandler.cpp.
References applyUDPLink(), UDPSourceUDPHandler::MsgUDPAddressAndPort::getAddress(), UDPSourceUDPHandler::MsgUDPAddressAndPort::getPort(), and Message::match().
Referenced by handleMessages(), and UDPSourceUDPHandler::MsgUDPAddressAndPort::MsgUDPAddressAndPort().
 {
     if (UDPSourceUDPHandler::MsgUDPAddressAndPort::match(cmd))
     {
         UDPSourceUDPHandler::MsgUDPAddressAndPort& notif = (UDPSourceUDPHandler::MsgUDPAddressAndPort&) cmd;
         applyUDPLink(notif.getAddress(), notif.getPort());
         return true;
     }
     else
     {
         return false;
     }
 }
handleMessages
void UDPSourceUDPHandler::handleMessages () private slot
Definition at line 276 of file udpsourceudphandler.cpp.
References handleMessage(), m_inputMessageQueue, and MessageQueue::pop().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
moveData()
void UDPSourceUDPHandler::moveData (char * blk) private
Definition at line 132 of file udpsourceudphandler.cpp.
References m_nbUDPFrames, m_udpBlockSize, m_udpBuf, and m_writeFrameIndex.
Referenced by dataReadyRead(), and UDPSourceUDPHandler::MsgUDPAddressAndPort::MsgUDPAddressAndPort().
 {
     memcpy(m_udpBuf[m_writeFrameIndex], blk, m_udpBlockSize);
     if (m_writeFrameIndex < m_nbUDPFrames - 1) {
         m_writeFrameIndex++;
     } else {
         m_writeFrameIndex = 0;
     }
 }
readSample() [1/3]
void UDPSourceUDPHandler::readSample (qint16 & t)
audio mono
Definition at line 143 of file udpsourceudphandler.cpp.
References advanceReadPointer(), m_readFrameIndex, m_readIndex, m_udpBuf, and m_writeFrameIndex.
Referenced by UDPSource::modulateSample(), and UDPSource::readMonoSample().
 {
     if (m_readFrameIndex == m_writeFrameIndex) // block until more writes
     {
         t = 0;
     }
     else
     {
         memcpy(&t, &m_udpBuf[m_readFrameIndex][m_readIndex], sizeof(qint16));
         advanceReadPointer((int) sizeof(qint16));
     }
 }
readSample() [2/3]
void UDPSourceUDPHandler::readSample (AudioSample & a)
audio stereo
Definition at line 156 of file udpsourceudphandler.cpp.
References advanceReadPointer(), AudioSample::l, m_readFrameIndex, m_readIndex, m_udpBuf, m_writeFrameIndex, and AudioSample::r.
 {
     if (m_readFrameIndex == m_writeFrameIndex) // block until more writes
     {
         a.l = 0;
         a.r = 0;
     }
     else
     {
         memcpy(&a, &m_udpBuf[m_readFrameIndex][m_readIndex], sizeof(AudioSample));
         advanceReadPointer((int) sizeof(AudioSample));
     }
 }
readSample() [3/3]
void UDPSourceUDPHandler::readSample (Sample & s)
I/Q stream.
Definition at line 170 of file udpsourceudphandler.cpp.
References advanceReadPointer(), Sample::m_imag, m_readFrameIndex, m_readIndex, Sample::m_real, m_udpBuf, and m_writeFrameIndex.
 {
     if (m_readFrameIndex == m_writeFrameIndex) // block until more writes
     {
         s.m_real = 0;
         s.m_imag = 0;
     }
     else
     {
         memcpy(&s, &m_udpBuf[m_readFrameIndex][m_readIndex], sizeof(Sample));
         advanceReadPointer((int) sizeof(Sample));
     }
 }
resetReadIndex()
void UDPSourceUDPHandler::resetReadIndex ()
Definition at line 250 of file udpsourceudphandler.cpp.
References m_d, m_nbUDPFrames, m_readFrameIndex, m_readIndex, m_rwDelta, and m_writeFrameIndex.
Referenced by advanceReadPointer(), UDPSource::applySettings(), applyUDPLink(), UDPSource::handleMessage(), and resizeBuffer().
 {
     m_readFrameIndex = (m_writeFrameIndex + (m_nbUDPFrames/2)) % m_nbUDPFrames;
     m_rwDelta = m_nbUDPFrames/2;
     m_readIndex = 0;
     m_d = 0.0f;
 }
resizeBuffer()
void UDPSourceUDPHandler::resizeBuffer (float sampleRate)
Definition at line 258 of file udpsourceudphandler.cpp.
References m_minNbUDPFrames, m_nbAllocatedUDPFrames, m_nbUDPFrames, m_udpBuf, m_writeFrameIndex, leansdr::max(), and resetReadIndex().
Referenced by UDPSource::applySettings().
 {
     int halfNbFrames = std::max((sampleRate / 375.0), (m_minNbUDPFrames / 2.0));
     qDebug("UDPSourceUDPHandler::resizeBuffer: nb_frames: %d", 2*halfNbFrames);
     if (2*halfNbFrames > m_nbAllocatedUDPFrames)
     {
         delete[] m_udpBuf;
         m_udpBuf = new udpBlk_t[2*halfNbFrames];
         m_nbAllocatedUDPFrames = 2*halfNbFrames;
     }
     m_nbUDPFrames = 2*halfNbFrames;
     m_writeFrameIndex = 0;
     resetReadIndex();
 }
setAutoRWBalance()
void UDPSourceUDPHandler::setAutoRWBalance (bool autoRWBalance) inline
Definition at line 48 of file udpsourceudphandler.h.
References m_autoRWBalance.
Referenced by UDPSource::applySettings().
 { m_autoRWBalance = autoRWBalance; }
setFeedbackMessageQueue()
void UDPSourceUDPHandler::setFeedbackMessageQueue (MessageQueue * messageQueue) inline
Definition at line 49 of file udpsourceudphandler.h.
References m_feedbackMessageQueue.
Referenced by UDPSource::UDPSource().
 { m_feedbackMessageQueue = messageQueue; }
start()
void UDPSourceUDPHandler::start ()
Definition at line 56 of file udpsourceudphandler.cpp.
References dataReadyRead(), m_dataAddress, m_dataConnected, m_dataPort, and m_dataSocket.
Referenced by applyUDPLink(), and UDPSource::start().
 {
     qDebug("UDPSourceUDPHandler::start");
     if (!m_dataSocket)
     {
         m_dataSocket = new QUdpSocket(this);
     }
     if (!m_dataConnected)
     {
         if (m_dataSocket->bind(m_dataAddress, m_dataPort))
         {
             qDebug("UDPSourceUDPHandler::start: bind data socket to %s:%d", m_dataAddress.toString().toStdString().c_str(),  m_dataPort);
             connect(m_dataSocket, SIGNAL(readyRead()), this, SLOT(dataReadyRead())); // , Qt::QueuedConnection gets stuck since Qt 5.8.0
             m_dataConnected = true;
         }
         else
         {
             qWarning("UDPSourceUDPHandler::start: cannot bind data socket to %s:%d", m_dataAddress.toString().toStdString().c_str(),  m_dataPort);
             m_dataConnected = false;
         }
     }
 }
stop()
void UDPSourceUDPHandler::stop ()
Definition at line 82 of file udpsourceudphandler.cpp.
References dataReadyRead(), m_dataConnected, and m_dataSocket.
Referenced by applyUDPLink(), and UDPSource::stop().
 {
     qDebug("UDPSourceUDPHandler::stop");
     if (m_dataConnected)
     {
         m_dataConnected = false;
         disconnect(m_dataSocket, SIGNAL(readyRead()), this, SLOT(dataReadyRead()));
     }
     if (m_dataSocket)
     {
         delete m_dataSocket;
         m_dataSocket = 0;
     }
 }
Member Data Documentation
m_autoRWBalance
bool UDPSourceUDPHandler::m_autoRWBalance private
Definition at line 114 of file udpsourceudphandler.h.
Referenced by advanceReadPointer(), and setAutoRWBalance().
m_d
float UDPSourceUDPHandler::m_d private
Definition at line 113 of file udpsourceudphandler.h.
Referenced by advanceReadPointer(), and resetReadIndex().
m_dataAddress
QHostAddress UDPSourceUDPHandler::m_dataAddress private
Definition at line 99 of file udpsourceudphandler.h.
Referenced by applyUDPLink(), and start().
m_dataConnected
bool UDPSourceUDPHandler::m_dataConnected private
Definition at line 103 of file udpsourceudphandler.h.
Referenced by dataReadyRead(), start(), and stop().
m_dataPort
quint16 UDPSourceUDPHandler::m_dataPort private
Definition at line 101 of file udpsourceudphandler.h.
Referenced by applyUDPLink(), and start().
m_dataSocket
QUdpSocket* UDPSourceUDPHandler::m_dataSocket private
Definition at line 98 of file udpsourceudphandler.h.
Referenced by dataReadyRead(), start(), and stop().
m_feedbackMessageQueue
MessageQueue* UDPSourceUDPHandler::m_feedbackMessageQueue private
Definition at line 115 of file udpsourceudphandler.h.
Referenced by advanceReadPointer(), and setFeedbackMessageQueue().
m_inputMessageQueue
MessageQueue UDPSourceUDPHandler::m_inputMessageQueue private
Definition at line 116 of file udpsourceudphandler.h.
Referenced by configureUDPLink(), and handleMessages().
m_minNbUDPFrames
const int UDPSourceUDPHandler::m_minNbUDPFrames = 256 static
Definition at line 62 of file udpsourceudphandler.h.
Referenced by resizeBuffer().
m_nbAllocatedUDPFrames
int UDPSourceUDPHandler::m_nbAllocatedUDPFrames private
Definition at line 108 of file udpsourceudphandler.h.
Referenced by resizeBuffer().
m_nbUDPFrames
int UDPSourceUDPHandler::m_nbUDPFrames private
Definition at line 107 of file udpsourceudphandler.h.
Referenced by advanceReadPointer(), getBufferGauge(), moveData(), resetReadIndex(), and resizeBuffer().
m_readFrameIndex
int UDPSourceUDPHandler::m_readFrameIndex private
Definition at line 110 of file udpsourceudphandler.h.
Referenced by advanceReadPointer(), readSample(), and resetReadIndex().
m_readIndex
int UDPSourceUDPHandler::m_readIndex private
Definition at line 111 of file udpsourceudphandler.h.
Referenced by advanceReadPointer(), readSample(), and resetReadIndex().
m_remoteAddress
QHostAddress UDPSourceUDPHandler::m_remoteAddress private
Definition at line 100 of file udpsourceudphandler.h.
Referenced by dataReadyRead().
m_remotePort
quint16 UDPSourceUDPHandler::m_remotePort private
Definition at line 102 of file udpsourceudphandler.h.
Referenced by dataReadyRead().
m_rwDelta
int UDPSourceUDPHandler::m_rwDelta private
Definition at line 112 of file udpsourceudphandler.h.
Referenced by advanceReadPointer(), getBufferGauge(), and resetReadIndex().
m_udpBlockSize
const int UDPSourceUDPHandler::m_udpBlockSize = 512 static
Definition at line 61 of file udpsourceudphandler.h.
Referenced by advanceReadPointer(), dataReadyRead(), moveData(), and UDPSourceUDPHandler::MsgUDPAddressAndPort::MsgUDPAddressAndPort().
m_udpBuf
udpBlk_t* UDPSourceUDPHandler::m_udpBuf private
Definition at line 104 of file udpsourceudphandler.h.
Referenced by moveData(), readSample(), resizeBuffer(), and ~UDPSourceUDPHandler().
m_udpDump
char UDPSourceUDPHandler::m_udpDump[m_udpBlockSize+8192] private
Definition at line 105 of file udpsourceudphandler.h.
Referenced by dataReadyRead().
m_udpDumpIndex
int UDPSourceUDPHandler::m_udpDumpIndex private
Definition at line 106 of file udpsourceudphandler.h.
Referenced by dataReadyRead().
m_writeFrameIndex
int UDPSourceUDPHandler::m_writeFrameIndex private
Definition at line 109 of file udpsourceudphandler.h.
Referenced by advanceReadPointer(), moveData(), readSample(), resetReadIndex(), and resizeBuffer().
The documentation for this class was generated from the following files:
plugins/channeltx/udpsource/udpsourceudphandler.h
plugins/channeltx/udpsource/udpsourceudphandler.cpp