SDRAngel: PlutoSDROutput Class Reference
PlutoSDROutput Class Reference
#include <plutosdroutput.h>
Classes
class MsgConfigurePlutoSDR
class MsgStartStop
Public Member Functions
PlutoSDROutput (DeviceAPI *deviceAPI)
~PlutoSDROutput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the sink.
virtual void setSampleRate (int sampleRate)
For when the sink sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the sink.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
uint32_t getDACSampleRate () const
uint32_t getFIRSampleRate () const
void getRSSI (std::string &rssiStr)
void getLORange (qint64 &minLimit, qint64 &maxLimit)
void getbbLPRange (quint32 &minLimit, quint32 &maxLimit)
bool fetchTemperature ()
float getTemperature ()
Public Member Functions inherited from DeviceSampleSink
DeviceSampleSink ()
virtual ~DeviceSampleSink ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSourceFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
void suspendBuddies ()
void resumeBuddies ()
bool applySettings (const PlutoSDROutputSettings &settings, bool force=false)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const PlutoSDROutputSettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const PlutoSDROutputSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QString m_deviceDescription
PlutoSDROutputSettings m_settings
bool m_running
DevicePlutoSDRShared m_deviceShared
struct iio_buffer * m_plutoTxBuffer
PlutoSDROutputThread * m_plutoSDROutputThread
DevicePlutoSDRBox::SampleRates m_deviceSampleRates
QMutex m_mutex
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSink
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
Static Public Member Functions inherited from DeviceSampleSink
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Interp, fcPos_t fcPos, quint32 devSampleRate)
Protected Slots inherited from DeviceSampleSink
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSink
SampleSourceFifo m_sampleSourceFifo
MessageQueue m_inputMessageQueue
Input queue to the sink.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 36 of file plutosdroutput.h.
Constructor & Destructor Documentation
PlutoSDROutput()
PlutoSDROutput::PlutoSDROutput (DeviceAPI * deviceAPI)
Definition at line 41 of file plutosdroutput.cpp.
Referenced by PlutoSDROutput::MsgStartStop::MsgStartStop().
                                                    :
     m_deviceAPI(deviceAPI),
     m_deviceDescription("PlutoSDROutput"),
     m_settings(),
     m_running(false),
     m_plutoTxBuffer(0),
     m_plutoSDROutputThread(0)
 {
     m_deviceAPI->setNbSinkStreams(1);
     m_deviceSampleRates.m_addaConnvRate = 0;
     m_deviceSampleRates.m_bbRateHz = 0;
     m_deviceSampleRates.m_firRate = 0;
     m_deviceSampleRates.m_hb1Rate = 0;
     m_deviceSampleRates.m_hb2Rate = 0;
     m_deviceSampleRates.m_hb3Rate = 0;
     suspendBuddies();
     openDevice();
     resumeBuddies();
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~PlutoSDROutput()
PlutoSDROutput::~PlutoSDROutput ()
Definition at line 65 of file plutosdroutput.cpp.
References closeDevice(), m_networkManager, networkManagerFinished(), resumeBuddies(), and suspendBuddies().
Referenced by PlutoSDROutput::MsgStartStop::MsgStartStop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     suspendBuddies();
     closeDevice();
     resumeBuddies();
 }
Member Function Documentation
applySettings()
bool PlutoSDROutput::applySettings (const PlutoSDROutputSettings & settings, bool force = false) private
Definition at line 323 of file plutosdroutput.cpp.
References arg(), DevicePlutoSDRShared::MsgCrossReportToBuddy::create(), DevicePlutoSDRBox::DEVICE_PHY, DevicePlutoSDRParams::getBox(), DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceAPI::getSourceBuddies(), DevicePlutoSDRBox::getTxSampleRates(), PlutoSDROutputThread::isRunning(), DevicePlutoSDRBox::SampleRates::m_addaConnvRate, PlutoSDROutputSettings::m_antennaPath, PlutoSDROutputSettings::m_att, DevicePlutoSDRBox::SampleRates::m_bbRateHz, PlutoSDROutputSettings::m_centerFrequency, m_deviceAPI, DevicePlutoSDRShared::m_deviceParams, m_deviceSampleRates, m_deviceShared, PlutoSDROutputSettings::m_devSampleRate, DevicePlutoSDRBox::SampleRates::m_firRate, DevicePlutoSDRBox::SampleRates::m_hb1Rate, DevicePlutoSDRBox::SampleRates::m_hb2Rate, DevicePlutoSDRBox::SampleRates::m_hb3Rate, PlutoSDROutputSettings::m_log2Interp, PlutoSDROutputSettings::m_LOppmTenths, PlutoSDROutputSettings::m_lpfBW, PlutoSDROutputSettings::m_lpfFIRBW, PlutoSDROutputSettings::m_lpfFIREnable, PlutoSDROutputSettings::m_lpfFIRGain, PlutoSDROutputSettings::m_lpfFIRlog2Interp, m_plutoSDROutputThread, PlutoSDROutputSettings::m_reverseAPIAddress, PlutoSDROutputSettings::m_reverseAPIDeviceIndex, PlutoSDROutputSettings::m_reverseAPIPort, DeviceSampleSink::m_sampleSourceFifo, m_settings, DevicePlutoSDRShared::m_thread, DevicePlutoSDRShared::m_threadWasRunning, PlutoSDROutputSettings::m_transverterDeltaFrequency, PlutoSDROutputSettings::m_transverterMode, PlutoSDROutputSettings::m_useReverseAPI, PLUTOSDR_BLOCKSIZE_SAMPLES, MessageQueue::push(), SampleSourceFifo::resize(), DevicePlutoSDRBox::set_params(), DevicePlutoSDRBox::setFIR(), DevicePlutoSDRBox::setFIREnable(), PlutoSDROutputThread::setLog2Interpolation(), DevicePlutoSDRBox::setLOPPMTenths(), DevicePlutoSDRBox::setSampleRate(), PlutoSDROutputThread::startWork(), DevicePlutoSDRShared::ThreadInterface::startWork(), PlutoSDROutputThread::stopWork(), DevicePlutoSDRShared::ThreadInterface::stopWork(), PlutoSDROutputSettings::translateRFPath(), DevicePlutoSDRBox::USE_TX, and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     bool forwardChangeOwnDSP    = false;
     bool forwardChangeOtherDSP  = false;
     bool ownThreadWasRunning    = false;
     bool suspendAllOtherThreads = false; // All others means Rx in fact
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     QLocale loc;
     QList<QString> reverseAPIKeys;
     qDebug().noquote() << "PlutoSDROutput::applySettings: center freq: " << m_settings.m_centerFrequency << " Hz"
             << " m_devSampleRate: " << loc.toString(m_settings.m_devSampleRate) << "S/s"
             << " m_LOppmTenths: " << m_settings.m_LOppmTenths
             << " m_lpfFIREnable: " << m_settings.m_lpfFIREnable
             << " m_lpfFIRBW: " << loc.toString(m_settings.m_lpfFIRBW)
             << " m_lpfFIRlog2Interp: " << m_settings.m_lpfFIRlog2Interp
             << " m_lpfFIRGain: " << m_settings.m_lpfFIRGain
             << " m_log2Interp: " << loc.toString(1<<m_settings.m_log2Interp)
             << " m_lpfBW: " << loc.toString(m_settings.m_lpfBW)
             << " m_att: " << m_settings.m_att
             << " m_antennaPath: " << (int) m_settings.m_antennaPath
             << " m_transverterMode: " << m_settings.m_transverterMode
             << " m_transverterDeltaFrequency: " << m_settings.m_transverterDeltaFrequency
             << " force: " << force;
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || force) {
         reverseAPIKeys.append("devSampleRate");
     }
     if ((m_settings.m_lpfFIREnable != settings.m_lpfFIREnable) || force) {
         reverseAPIKeys.append("lpfFIREnable");
     }
     if ((m_settings.m_lpfFIRlog2Interp != settings.m_lpfFIRlog2Interp) || force) {
         reverseAPIKeys.append("lpfFIRlog2Interp");
     }
     if ((m_settings.m_lpfFIRBW != settings.m_lpfFIRBW) || force) {
         reverseAPIKeys.append("lpfFIRBW");
     }
     if ((m_settings.m_lpfFIRGain != settings.m_lpfFIRGain) || force) {
         reverseAPIKeys.append("lpfFIRGain");
     }
     if ((m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force) {
         reverseAPIKeys.append("LOppmTenths");
     }
     // determine if buddies threads or own thread need to be suspended
     // changes affecting all buddies can occur if
     //   - device to host sample rate is changed
     //   - FIR filter is enabled or disabled
     //   - FIR filter is changed
     //   - LO correction is changed
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) ||
         (m_settings.m_lpfFIREnable != settings.m_lpfFIREnable) ||
         (m_settings.m_lpfFIRlog2Interp != settings.m_lpfFIRlog2Interp) ||
         (settings.m_lpfFIRBW != m_settings.m_lpfFIRBW) ||
         (settings.m_lpfFIRGain != m_settings.m_lpfFIRGain) ||
         (m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force)
     {
         suspendAllOtherThreads = true;
     }
     if (suspendAllOtherThreads)
     {
         const std::vector<DeviceAPI*>& sourceBuddies = m_deviceAPI->getSourceBuddies();
         std::vector<DeviceAPI*>::const_iterator itSink = sourceBuddies.begin();
         for (; itSink != sourceBuddies.end(); ++itSink)
         {
             DevicePlutoSDRShared *buddySharedPtr = (DevicePlutoSDRShared *) (*itSink)->getBuddySharedPtr();
             if (buddySharedPtr->m_thread) {
                 buddySharedPtr->m_thread->stopWork();
                 buddySharedPtr->m_threadWasRunning = true;
             }
             else
             {
                 buddySharedPtr->m_threadWasRunning = false;
             }
         }
     }
     if (m_plutoSDROutputThread && m_plutoSDROutputThread->isRunning())
     {
         m_plutoSDROutputThread->stopWork();
         ownThreadWasRunning = true;
     }
     // apply settings
     // Change affecting device sample rate chain and other buddies
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) ||
         (m_settings.m_lpfFIREnable != settings.m_lpfFIREnable) ||
         (m_settings.m_lpfFIRlog2Interp != settings.m_lpfFIRlog2Interp) ||
         (settings.m_lpfFIRBW != m_settings.m_lpfFIRBW) ||
         (settings.m_lpfFIRGain != m_settings.m_lpfFIRGain) || force)
     {
         plutoBox->setFIR(settings.m_devSampleRate, settings.m_lpfFIRlog2Interp, DevicePlutoSDRBox::USE_TX, settings.m_lpfFIRBW, settings.m_lpfFIRGain);
         plutoBox->setFIREnable(settings.m_lpfFIREnable);   // eventually enable/disable FIR
         plutoBox->setSampleRate(settings.m_devSampleRate); // and set end point sample rate
         plutoBox->getTxSampleRates(m_deviceSampleRates); // pick up possible new rates
         qDebug() << "PlutoSDRInput::applySettings: BBPLL(Hz): " << m_deviceSampleRates.m_bbRateHz
                  << " DAC: " << m_deviceSampleRates.m_addaConnvRate
                  << " <-HB3- " << m_deviceSampleRates.m_hb3Rate
                  << " <-HB2- " << m_deviceSampleRates.m_hb2Rate
                  << " <-HB1- " << m_deviceSampleRates.m_hb1Rate
                  << " <-FIR- " << m_deviceSampleRates.m_firRate;
         forwardChangeOtherDSP = true;
         forwardChangeOwnDSP = (m_settings.m_devSampleRate != settings.m_devSampleRate) || force;
     }
     if ((m_settings.m_log2Interp != settings.m_log2Interp) || force)
     {
         reverseAPIKeys.append("log2Interp");
         m_sampleSourceFifo.resize((32*PLUTOSDR_BLOCKSIZE_SAMPLES)/(1<<settings.m_log2Interp));
         if (m_plutoSDROutputThread != 0)
         {
             m_plutoSDROutputThread->setLog2Interpolation(settings.m_log2Interp);
             qDebug() << "PlutoSDROutput::applySettings: set soft interpolation in thread to " << (1<<settings.m_log2Interp);
         }
         forwardChangeOwnDSP = true;
     }
     if ((m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force)
     {
         plutoBox->setLOPPMTenths(settings.m_LOppmTenths);
         forwardChangeOtherDSP = true;
     }
     std::vector<std::string> params;
     bool paramsToSet = false;
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency) || force) {
         reverseAPIKeys.append("centerFrequency");
     }
     if ((m_settings.m_transverterMode != settings.m_transverterMode) || force) {
         reverseAPIKeys.append("transverterMode");
     }
     if ((m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency) || force) {
         reverseAPIKeys.append("transverterDeltaFrequency");
     }
     if (force || (m_settings.m_centerFrequency != settings.m_centerFrequency)
         || (m_settings.m_transverterMode != settings.m_transverterMode)
         || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency))
     {
         qint64 deviceCenterFrequency = settings.m_centerFrequency;
         deviceCenterFrequency -= settings.m_transverterMode ? settings.m_transverterDeltaFrequency : 0;
         deviceCenterFrequency = deviceCenterFrequency < 0 ? 0 : deviceCenterFrequency;
         params.push_back(QString(tr("out_altvoltage1_TX_LO_frequency=%1").arg(deviceCenterFrequency)).toStdString());
         paramsToSet = true;
         forwardChangeOwnDSP = true;
         qDebug() << "PlutoSDROutput::applySettings: center freq: " << settings.m_centerFrequency << " Hz"
                 << " device center freq: " << deviceCenterFrequency << " Hz";
     }
     if ((m_settings.m_lpfBW != settings.m_lpfBW) || force)
     {
         reverseAPIKeys.append("lpfBW");
         params.push_back(QString(tr("out_voltage_rf_bandwidth=%1").arg(settings.m_lpfBW)).toStdString());
         paramsToSet = true;
     }
     if ((m_settings.m_antennaPath != settings.m_antennaPath) || force)
     {
         reverseAPIKeys.append("antennaPath");
         QString rfPortStr;
         PlutoSDROutputSettings::translateRFPath(settings.m_antennaPath, rfPortStr);
         params.push_back(QString(tr("out_voltage0_rf_port_select=%1").arg(rfPortStr)).toStdString());
         paramsToSet = true;
     }
     if ((m_settings.m_att != settings.m_att) || force)
     {
         reverseAPIKeys.append("att");
         float attF = settings.m_att * 0.25f;
         params.push_back(QString(tr("out_voltage0_hardwaregain=%1").arg(attF)).toStdString());
         paramsToSet = true;
     }
     if (paramsToSet)
     {
         plutoBox->set_params(DevicePlutoSDRBox::DEVICE_PHY, params);
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     if (suspendAllOtherThreads)
     {
         const std::vector<DeviceAPI*>& sourceBuddies = m_deviceAPI->getSourceBuddies();
         std::vector<DeviceAPI*>::const_iterator itSource = sourceBuddies.begin();
         for (; itSource != sourceBuddies.end(); ++itSource)
         {
             DevicePlutoSDRShared *buddySharedPtr = (DevicePlutoSDRShared *) (*itSource)->getBuddySharedPtr();
             if (buddySharedPtr->m_threadWasRunning) {
                 buddySharedPtr->m_thread->startWork();
             }
         }
     }
     if (ownThreadWasRunning) {
         m_plutoSDROutputThread->startWork();
     }
     // TODO: forward changes to other (Rx) DSP
     if (forwardChangeOtherDSP)
     {
         qDebug("PlutoSDROutput::applySettings: forwardChangeOtherDSP");
         const std::vector<DeviceAPI*>& sourceBuddies = m_deviceAPI->getSourceBuddies();
         std::vector<DeviceAPI*>::const_iterator itSource = sourceBuddies.begin();
         for (; itSource != sourceBuddies.end(); ++itSource)
         {
             DevicePlutoSDRShared::MsgCrossReportToBuddy *msg = DevicePlutoSDRShared::MsgCrossReportToBuddy::create(
                     settings.m_devSampleRate,
                     settings.m_lpfFIREnable,
                     settings.m_lpfFIRlog2Interp,
                     settings.m_lpfFIRBW,
                     settings.m_LOppmTenths);
             if ((*itSource)->getSamplingDeviceGUIMessageQueue())
             {
                 DevicePlutoSDRShared::MsgCrossReportToBuddy *msgToGUI = new DevicePlutoSDRShared::MsgCrossReportToBuddy(*msg);
                 (*itSource)->getSamplingDeviceGUIMessageQueue()->push(msgToGUI);
             }
             (*itSource)->getSamplingDeviceInputMessageQueue()->push(msg);
         }
     }
     if (forwardChangeOwnDSP)
     {
         qDebug("PlutoSDROutput::applySettings: forward change to self");
         int sampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Interp);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, m_settings.m_centerFrequency);
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     return true;
 }
closeDevice()
void PlutoSDROutput::closeDevice () private
Definition at line 279 of file plutosdroutput.cpp.
References DevicePlutoSDRParams::close(), DevicePlutoSDRParams::getBox(), DeviceAPI::getSourceBuddies(), m_deviceAPI, DevicePlutoSDRShared::m_deviceParams, and m_deviceShared.
Referenced by ~PlutoSDROutput().
 {
     if (m_deviceShared.m_deviceParams->getBox() == 0) { // was never open
         return;
     }
     if (m_deviceAPI->getSourceBuddies().size() == 0)
     {
         m_deviceShared.m_deviceParams->close();
         delete m_deviceShared.m_deviceParams;
         m_deviceShared.m_deviceParams = 0;
     }
 }
deserialize()
bool PlutoSDROutput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSink.
Definition at line 127 of file plutosdroutput.cpp.
References PlutoSDROutput::MsgConfigurePlutoSDR::create(), PlutoSDROutputSettings::deserialize(), DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and PlutoSDROutputSettings::resetToDefaults().
Referenced by PlutoSDROutput::MsgStartStop::MsgStartStop().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigurePlutoSDR* message = MsgConfigurePlutoSDR::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigurePlutoSDR* messageToGUI = MsgConfigurePlutoSDR::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void PlutoSDROutput::destroy () virtual
Implements DeviceSampleSink.
Definition at line 75 of file plutosdroutput.cpp.
Referenced by PlutoSDROutput::MsgStartStop::MsgStartStop().
 {
     delete this;
 }
fetchTemperature()
bool PlutoSDROutput::fetchTemperature ()
Definition at line 614 of file plutosdroutput.cpp.
References DevicePlutoSDRBox::fetchTemp(), DevicePlutoSDRParams::getBox(), DevicePlutoSDRShared::m_deviceParams, and m_deviceShared.
Referenced by getFIRSampleRate(), and webapiFormatDeviceReport().
 {
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     return plutoBox->fetchTemp();
 }
getbbLPRange()
void PlutoSDROutput::getbbLPRange (quint32 & minLimit, quint32 & maxLimit)
Definition at line 604 of file plutosdroutput.cpp.
References DevicePlutoSDRBox::getbbLPTxRange(), DevicePlutoSDRParams::getBox(), DevicePlutoSDRShared::m_deviceParams, m_deviceShared, leansdr::max(), and leansdr::min().
Referenced by getFIRSampleRate().
 {
     uint32_t min, max;
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     plutoBox->getbbLPTxRange(min, max);
     minLimit = min;
     maxLimit = max;
 }
getCenterFrequency()
quint64 PlutoSDROutput::getCenterFrequency () const virtual
Center frequency exposed by the sink.
Implements DeviceSampleSink.
Definition at line 158 of file plutosdroutput.cpp.
References PlutoSDROutputSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDACSampleRate()
uint32_t PlutoSDROutput::getDACSampleRate () const inline
Definition at line 124 of file plutosdroutput.h.
References DevicePlutoSDRBox::SampleRates::m_addaConnvRate, and m_deviceSampleRates.
Referenced by webapiFormatDeviceReport().
 { return m_deviceSampleRates.m_addaConnvRate; }
getDeviceDescription()
const QString & PlutoSDROutput::getDeviceDescription () const virtual
Implements DeviceSampleSink.
Definition at line 149 of file plutosdroutput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getFIRSampleRate()
uint32_t PlutoSDROutput::getFIRSampleRate () const inline
Definition at line 125 of file plutosdroutput.h.
References fetchTemperature(), getbbLPRange(), getLORange(), getRSSI(), getTemperature(), m_deviceSampleRates, and DevicePlutoSDRBox::SampleRates::m_hb1Rate.
 { return m_deviceSampleRates.m_hb1Rate; }
getLORange()
void PlutoSDROutput::getLORange (qint64 & minLimit, qint64 & maxLimit)
Definition at line 594 of file plutosdroutput.cpp.
References DevicePlutoSDRParams::getBox(), DevicePlutoSDRBox::getTxLORange(), DevicePlutoSDRShared::m_deviceParams, m_deviceShared, leansdr::max(), and leansdr::min().
Referenced by getFIRSampleRate().
 {
     uint64_t min, max;
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     plutoBox->getTxLORange(min, max);
     minLimit = min;
     maxLimit = max;
 }
getRSSI()
void PlutoSDROutput::getRSSI (std::string & rssiStr)
Definition at line 585 of file plutosdroutput.cpp.
References DevicePlutoSDRParams::getBox(), DevicePlutoSDRBox::getTxRSSI(), DevicePlutoSDRShared::m_deviceParams, and m_deviceShared.
Referenced by getFIRSampleRate(), and webapiFormatDeviceReport().
 {
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     if (!plutoBox->getTxRSSI(rssiStr, 0)) {
         rssiStr = "xxx dB";
     }
 }
getSampleRate()
int PlutoSDROutput::getSampleRate () const virtual
Sample rate exposed by the sink.
Implements DeviceSampleSink.
Definition at line 153 of file plutosdroutput.cpp.
References PlutoSDROutputSettings::m_devSampleRate, PlutoSDROutputSettings::m_log2Interp, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     return (m_settings.m_devSampleRate / (1<<m_settings.m_log2Interp));
 }
getTemperature()
float PlutoSDROutput::getTemperature ()
Definition at line 620 of file plutosdroutput.cpp.
References DevicePlutoSDRParams::getBox(), DevicePlutoSDRBox::getTemp(), DevicePlutoSDRShared::m_deviceParams, and m_deviceShared.
Referenced by getFIRSampleRate(), and webapiFormatDeviceReport().
 {
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     return plutoBox->getTemp();
 }
handleMessage()
bool PlutoSDROutput::handleMessage (const Message & message) virtual
Implements DeviceSampleSink.
Definition at line 178 of file plutosdroutput.cpp.
References applySettings(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getDevSampleRate(), PlutoSDROutput::MsgConfigurePlutoSDR::getForce(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getLoPPMTenths(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getLpfFirbw(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getLpfFiRlog2IntDec(), PlutoSDROutput::MsgConfigurePlutoSDR::getSettings(), PlutoSDROutput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), DevicePlutoSDRShared::MsgCrossReportToBuddy::isLpfFirEnable(), m_deviceAPI, PlutoSDROutputSettings::m_devSampleRate, PlutoSDROutputSettings::m_LOppmTenths, PlutoSDROutputSettings::m_lpfFIRBW, PlutoSDROutputSettings::m_lpfFIREnable, PlutoSDROutputSettings::m_lpfFIRlog2Interp, m_settings, PlutoSDROutputSettings::m_useReverseAPI, Message::match(), DeviceAPI::startDeviceEngine(), DeviceAPI::stopDeviceEngine(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (MsgConfigurePlutoSDR::match(message))
     {
         MsgConfigurePlutoSDR& conf = (MsgConfigurePlutoSDR&) message;
         qDebug() << "PlutoSDROutput::handleMessage: MsgConfigurePlutoSDR";
         if (!applySettings(conf.getSettings(), conf.getForce()))
         {
             qDebug("PlutoSDROutput::handleMessage config error");
         }
         return true;
     }
     else if (DevicePlutoSDRShared::MsgCrossReportToBuddy::match(message)) // message from buddy
     {
         DevicePlutoSDRShared::MsgCrossReportToBuddy& conf = (DevicePlutoSDRShared::MsgCrossReportToBuddy&) message;
         m_settings.m_devSampleRate = conf.getDevSampleRate();
         m_settings.m_lpfFIRlog2Interp = conf.getLpfFiRlog2IntDec();
         m_settings.m_lpfFIRBW = conf.getLpfFirbw();
         m_settings.m_LOppmTenths = conf.getLoPPMTenths();
         PlutoSDROutputSettings newSettings = m_settings;
         newSettings.m_lpfFIREnable = conf.isLpfFirEnable();
         applySettings(newSettings);
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "PlutoSDROutput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void PlutoSDROutput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSink.
Definition at line 80 of file plutosdroutput.cpp.
References applySettings(), and m_settings.
Referenced by PlutoSDROutput::MsgStartStop::MsgStartStop().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void PlutoSDROutput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 886 of file plutosdroutput.cpp.
Referenced by ~PlutoSDROutput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "PlutoSDROutput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("PlutoSDROutput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openDevice()
bool PlutoSDROutput::openDevice () private
Definition at line 234 of file plutosdroutput.cpp.
References DevicePlutoSDRBox::createTxBuffer(), DevicePlutoSDRParams::getBox(), DeviceAPI::getBuddySharedPtr(), DeviceAPI::getSamplingDeviceSerial(), DeviceAPI::getSourceBuddies(), m_deviceAPI, DevicePlutoSDRShared::m_deviceParams, m_deviceShared, m_plutoTxBuffer, DeviceSampleSink::m_sampleSourceFifo, DevicePlutoSDRParams::open(), DevicePlutoSDRBox::openTx(), PLUTOSDR_BLOCKSIZE_SAMPLES, SampleSourceFifo::resize(), and DeviceAPI::setBuddySharedPtr().
 {
     m_sampleSourceFifo.resize(32*PLUTOSDR_BLOCKSIZE_SAMPLES);
     // look for Rx buddy and get reference to common parameters
     if (m_deviceAPI->getSourceBuddies().size() > 0) // then sink
     {
         qDebug("PlutoSDROutput::openDevice: look at Rx buddy");
         DeviceAPI *sourceBuddy = m_deviceAPI->getSourceBuddies()[0];
         DevicePlutoSDRShared* buddySharedPtr = (DevicePlutoSDRShared*) sourceBuddy->getBuddySharedPtr();
         m_deviceShared.m_deviceParams = buddySharedPtr->m_deviceParams;
         if (m_deviceShared.m_deviceParams == 0)
         {
             qCritical("PlutoSDROutput::openDevice: cannot get device parameters from Rx buddy");
             return false; // the device params should have been created by the buddy
         }
         else
         {
             qDebug("PlutoSDROutput::openDevice: getting device parameters from Rx buddy");
         }
     }
     // There is no buddy then create the first PlutoSDR common parameters
     // open the device this will also populate common fields
     else
     {
         qDebug("PlutoSDROutput::openDevice: open device here");
         m_deviceShared.m_deviceParams = new DevicePlutoSDRParams();
         char serial[256];
         strcpy(serial, qPrintable(m_deviceAPI->getSamplingDeviceSerial()));
         m_deviceShared.m_deviceParams->open(serial);
     }
     m_deviceAPI->setBuddySharedPtr(&m_deviceShared); // propagate common parameters to API
     // acquire the channel
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     plutoBox->openTx();
     m_plutoTxBuffer = plutoBox->createTxBuffer(PLUTOSDR_BLOCKSIZE_SAMPLES, false); // PlutoSDR buffer size is counted in number of (I,Q) samples
     return true;
 }
resumeBuddies()
void PlutoSDROutput::resumeBuddies () private
Definition at line 308 of file plutosdroutput.cpp.
References DeviceAPI::getBuddySharedPtr(), DeviceAPI::getSourceBuddies(), i, m_deviceAPI, DevicePlutoSDRShared::m_thread, and DevicePlutoSDRShared::ThreadInterface::startWork().
Referenced by ~PlutoSDROutput().
 {
     // resume Rx buddy's thread
     for (unsigned int i = 0; i < m_deviceAPI->getSourceBuddies().size(); i++)
     {
         DeviceAPI *buddy = m_deviceAPI->getSourceBuddies()[i];
         DevicePlutoSDRShared *buddyShared = (DevicePlutoSDRShared *) buddy->getBuddySharedPtr();
         if (buddyShared->m_thread) {
             buddyShared->m_thread->startWork();
         }
     }
 }
serialize()
QByteArray PlutoSDROutput::serialize () const virtual
Implements DeviceSampleSink.
Definition at line 122 of file plutosdroutput.cpp.
References m_settings, and PlutoSDROutputSettings::serialize().
Referenced by PlutoSDROutput::MsgStartStop::MsgStartStop().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void PlutoSDROutput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSink.
Definition at line 163 of file plutosdroutput.cpp.
References PlutoSDROutput::MsgConfigurePlutoSDR::create(), PlutoSDROutputSettings::m_centerFrequency, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     PlutoSDROutputSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigurePlutoSDR* message = MsgConfigurePlutoSDR::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigurePlutoSDR* messageToGUI = MsgConfigurePlutoSDR::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setMessageQueueToGUI()
virtual void PlutoSDROutput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSink.
Definition at line 92 of file plutosdroutput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSink::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void PlutoSDROutput::setSampleRate (int sampleRate) inline virtual
For when the sink sample rate is set externally.
Implements DeviceSampleSink.
Definition at line 95 of file plutosdroutput.h.
References getCenterFrequency(), handleMessage(), setCenterFrequency(), webapiReportGet(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
start()
bool PlutoSDROutput::start () virtual
Implements DeviceSampleSink.
Definition at line 85 of file plutosdroutput.cpp.
References applySettings(), DevicePlutoSDRParams::getBox(), DevicePlutoSDRShared::m_deviceParams, m_deviceShared, PlutoSDROutputSettings::m_log2Interp, m_plutoSDROutputThread, m_running, DeviceSampleSink::m_sampleSourceFifo, m_settings, DevicePlutoSDRShared::m_thread, PLUTOSDR_BLOCKSIZE_SAMPLES, PlutoSDROutputThread::setLog2Interpolation(), PlutoSDROutputThread::startWork(), and stop().
Referenced by PlutoSDROutput::MsgStartStop::MsgStartStop().
 {
     if (!m_deviceShared.m_deviceParams->getBox()) {
         return false;
     }
     if (m_running) stop();
     // start / stop streaming is done in the thread.
     m_plutoSDROutputThread = new PlutoSDROutputThread(PLUTOSDR_BLOCKSIZE_SAMPLES, m_deviceShared.m_deviceParams->getBox(), &m_sampleSourceFifo);
     qDebug("PlutoSDROutput::start: thread created");
     applySettings(m_settings, true);
     m_plutoSDROutputThread->setLog2Interpolation(m_settings.m_log2Interp);
     m_plutoSDROutputThread->startWork();
     m_deviceShared.m_thread = m_plutoSDROutputThread;
     m_running = true;
     return true;
 }
stop()
void PlutoSDROutput::stop () virtual
Implements DeviceSampleSink.
Definition at line 109 of file plutosdroutput.cpp.
References m_deviceShared, m_plutoSDROutputThread, m_running, DevicePlutoSDRShared::m_thread, and PlutoSDROutputThread::stopWork().
Referenced by PlutoSDROutput::MsgStartStop::MsgStartStop(), and start().
 {
     if (m_plutoSDROutputThread != 0)
     {
         m_plutoSDROutputThread->stopWork();
         delete m_plutoSDROutputThread;
         m_plutoSDROutputThread = 0;
     }
     m_deviceShared.m_thread = 0;
     m_running = false;
 }
suspendBuddies()
void PlutoSDROutput::suspendBuddies () private
Definition at line 293 of file plutosdroutput.cpp.
References DeviceAPI::getBuddySharedPtr(), DeviceAPI::getSourceBuddies(), i, m_deviceAPI, DevicePlutoSDRShared::m_thread, and DevicePlutoSDRShared::ThreadInterface::stopWork().
Referenced by ~PlutoSDROutput().
 {
     // suspend Rx buddy's thread
     for (unsigned int i = 0; i < m_deviceAPI->getSourceBuddies().size(); i++)
     {
         DeviceAPI *buddy = m_deviceAPI->getSourceBuddies()[i];
         DevicePlutoSDRShared *buddyShared = (DevicePlutoSDRShared *) buddy->getBuddySharedPtr();
         if (buddyShared->m_thread) {
             buddyShared->m_thread->stopWork();
         }
     }
 }
webapiFormatDeviceReport()
void PlutoSDROutput::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 779 of file plutosdroutput.cpp.
References fetchTemperature(), getDACSampleRate(), SWGSDRangel::SWGDeviceReport::getPlutoSdrOutputReport(), getRSSI(), getTemperature(), SWGSDRangel::SWGPlutoSdrOutputReport::setDacRate(), SWGSDRangel::SWGPlutoSdrOutputReport::setRssi(), and SWGSDRangel::SWGPlutoSdrOutputReport::setTemperature().
Referenced by webapiReportGet().
 {
     response.getPlutoSdrOutputReport()->setDacRate(getDACSampleRate());
     std::string rssiStr;
     getRSSI(rssiStr);
     response.getPlutoSdrOutputReport()->setRssi(new QString(rssiStr.c_str()));
     fetchTemperature();
     response.getPlutoSdrOutputReport()->setTemperature(getTemperature());
 }
webapiFormatDeviceSettings()
void PlutoSDROutput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const PlutoSDROutputSettings & settings) private
Definition at line 752 of file plutosdroutput.cpp.
References SWGSDRangel::SWGDeviceSettings::getPlutoSdrOutputSettings(), SWGSDRangel::SWGPlutoSdrOutputSettings::getReverseApiAddress(), PlutoSDROutputSettings::m_antennaPath, PlutoSDROutputSettings::m_att, PlutoSDROutputSettings::m_centerFrequency, PlutoSDROutputSettings::m_devSampleRate, PlutoSDROutputSettings::m_log2Interp, PlutoSDROutputSettings::m_LOppmTenths, PlutoSDROutputSettings::m_lpfBW, PlutoSDROutputSettings::m_lpfFIRBW, PlutoSDROutputSettings::m_lpfFIREnable, PlutoSDROutputSettings::m_lpfFIRGain, PlutoSDROutputSettings::m_lpfFIRlog2Interp, PlutoSDROutputSettings::m_reverseAPIAddress, PlutoSDROutputSettings::m_reverseAPIDeviceIndex, PlutoSDROutputSettings::m_reverseAPIPort, PlutoSDROutputSettings::m_transverterDeltaFrequency, PlutoSDROutputSettings::m_transverterMode, PlutoSDROutputSettings::m_useReverseAPI, SWGSDRangel::SWGPlutoSdrOutputSettings::setAntennaPath(), SWGSDRangel::SWGPlutoSdrOutputSettings::setAtt(), SWGSDRangel::SWGPlutoSdrOutputSettings::setCenterFrequency(), SWGSDRangel::SWGPlutoSdrOutputSettings::setDevSampleRate(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLog2Interp(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLOppmTenths(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLpfBw(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLpfFirbw(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLpfFirEnable(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLpfFirGain(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLpfFiRlog2Interp(), SWGSDRangel::SWGPlutoSdrOutputSettings::setReverseApiAddress(), SWGSDRangel::SWGPlutoSdrOutputSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGPlutoSdrOutputSettings::setReverseApiPort(), SWGSDRangel::SWGPlutoSdrOutputSettings::setTransverterDeltaFrequency(), SWGSDRangel::SWGPlutoSdrOutputSettings::setTransverterMode(), and SWGSDRangel::SWGPlutoSdrOutputSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getPlutoSdrOutputSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getPlutoSdrOutputSettings()->setDevSampleRate(settings.m_devSampleRate);
     response.getPlutoSdrOutputSettings()->setLOppmTenths(settings.m_LOppmTenths);
     response.getPlutoSdrOutputSettings()->setLpfFirEnable(settings.m_lpfFIREnable ? 1 : 0);
     response.getPlutoSdrOutputSettings()->setLpfFirbw(settings.m_lpfFIRBW);
     response.getPlutoSdrOutputSettings()->setLpfFiRlog2Interp(settings.m_lpfFIRlog2Interp);
     response.getPlutoSdrOutputSettings()->setLpfFirGain(settings.m_lpfFIRGain);
     response.getPlutoSdrOutputSettings()->setLog2Interp(settings.m_log2Interp);
     response.getPlutoSdrOutputSettings()->setLpfBw(settings.m_lpfBW);
     response.getPlutoSdrOutputSettings()->setAtt(settings.m_att);
     response.getPlutoSdrOutputSettings()->setAntennaPath((int) settings.m_antennaPath);
     response.getPlutoSdrOutputSettings()->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     response.getPlutoSdrOutputSettings()->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     response.getPlutoSdrOutputSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getPlutoSdrOutputSettings()->getReverseApiAddress()) {
         *response.getPlutoSdrOutputSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getPlutoSdrOutputSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getPlutoSdrOutputSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getPlutoSdrOutputSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int PlutoSDROutput::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 741 of file plutosdroutput.cpp.
References SWGSDRangel::SWGDeviceReport::getPlutoSdrOutputReport(), SWGSDRangel::SWGPlutoSdrOutputReport::init(), SWGSDRangel::SWGDeviceReport::setPlutoSdrOutputReport(), and webapiFormatDeviceReport().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setPlutoSdrOutputReport(new SWGSDRangel::SWGPlutoSdrOutputReport());
     response.getPlutoSdrOutputReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void PlutoSDROutput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const PlutoSDROutputSettings & settings, bool force) private
Definition at line 789 of file plutosdroutput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getPlutoSdrOutputSettings(), PlutoSDROutputSettings::m_antennaPath, PlutoSDROutputSettings::m_att, PlutoSDROutputSettings::m_centerFrequency, m_deviceAPI, PlutoSDROutputSettings::m_devSampleRate, PlutoSDROutputSettings::m_log2Interp, PlutoSDROutputSettings::m_LOppmTenths, PlutoSDROutputSettings::m_lpfBW, PlutoSDROutputSettings::m_lpfFIRBW, PlutoSDROutputSettings::m_lpfFIREnable, PlutoSDROutputSettings::m_lpfFIRGain, PlutoSDROutputSettings::m_lpfFIRlog2Interp, m_networkManager, m_networkRequest, PlutoSDROutputSettings::m_reverseAPIAddress, PlutoSDROutputSettings::m_reverseAPIDeviceIndex, PlutoSDROutputSettings::m_reverseAPIPort, PlutoSDROutputSettings::m_transverterDeltaFrequency, PlutoSDROutputSettings::m_transverterMode, SWGSDRangel::SWGPlutoSdrOutputSettings::setAntennaPath(), SWGSDRangel::SWGPlutoSdrOutputSettings::setAtt(), SWGSDRangel::SWGPlutoSdrOutputSettings::setCenterFrequency(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGPlutoSdrOutputSettings::setDevSampleRate(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLog2Interp(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLOppmTenths(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLpfBw(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLpfFirbw(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLpfFirEnable(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLpfFirGain(), SWGSDRangel::SWGPlutoSdrOutputSettings::setLpfFiRlog2Interp(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGDeviceSettings::setPlutoSdrOutputSettings(), SWGSDRangel::SWGPlutoSdrOutputSettings::setTransverterDeltaFrequency(), and SWGSDRangel::SWGPlutoSdrOutputSettings::setTransverterMode().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(1); // single Tx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("PlutoSDR"));
     swgDeviceSettings->setPlutoSdrOutputSettings(new SWGSDRangel::SWGPlutoSdrOutputSettings());
     SWGSDRangel::SWGPlutoSdrOutputSettings *swgPlutoSdrOutputSettings = swgDeviceSettings->getPlutoSdrOutputSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgPlutoSdrOutputSettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("devSampleRate") || force) {
         swgPlutoSdrOutputSettings->setDevSampleRate(settings.m_devSampleRate);
     }
     if (deviceSettingsKeys.contains("LOppmTenths") || force) {
         swgPlutoSdrOutputSettings->setLOppmTenths(settings.m_LOppmTenths);
     }
     if (deviceSettingsKeys.contains("lpfFIREnable") || force) {
         swgPlutoSdrOutputSettings->setLpfFirEnable(settings.m_lpfFIREnable ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("lpfFIRBW") || force) {
         swgPlutoSdrOutputSettings->setLpfFirbw(settings.m_lpfFIRBW);
     }
     if (deviceSettingsKeys.contains("lpfFIRlog2Interp") || force) {
         swgPlutoSdrOutputSettings->setLpfFiRlog2Interp(settings.m_lpfFIRlog2Interp);
     }
     if (deviceSettingsKeys.contains("lpfFIRGain") || force) {
         swgPlutoSdrOutputSettings->setLpfFirGain(settings.m_lpfFIRGain);
     }
     if (deviceSettingsKeys.contains("log2Interp") || force) {
         swgPlutoSdrOutputSettings->setLog2Interp(settings.m_log2Interp);
     }
     if (deviceSettingsKeys.contains("lpfBW") || force) {
         swgPlutoSdrOutputSettings->setLpfBw(settings.m_lpfBW);
     }
     if (deviceSettingsKeys.contains("att") || force) {
         swgPlutoSdrOutputSettings->setAtt(settings.m_att);
     }
     if (deviceSettingsKeys.contains("antennaPath") || force) {
         swgPlutoSdrOutputSettings->setAntennaPath((int) settings.m_antennaPath);
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency") || force) {
         swgPlutoSdrOutputSettings->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     }
     if (deviceSettingsKeys.contains("transverterMode") || force) {
         swgPlutoSdrOutputSettings->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void PlutoSDROutput::webapiReverseSendStartStop (bool start) private
Definition at line 858 of file plutosdroutput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, PlutoSDROutputSettings::m_reverseAPIAddress, PlutoSDROutputSettings::m_reverseAPIDeviceIndex, PlutoSDROutputSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(1); // single Tx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("PlutoSDR"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int PlutoSDROutput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 635 of file plutosdroutput.cpp.
References PlutoSDROutput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgStartStop *messagetoGui = MsgStartStop::create(run);
         m_guiMessageQueue->push(messagetoGui);
     }
     return 200;
 }
webapiRunGet()
int PlutoSDROutput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 626 of file plutosdroutput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int PlutoSDROutput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 654 of file plutosdroutput.cpp.
References SWGSDRangel::SWGDeviceSettings::getPlutoSdrOutputSettings(), SWGSDRangel::SWGPlutoSdrOutputSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setPlutoSdrOutputSettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setPlutoSdrOutputSettings(new SWGSDRangel::SWGPlutoSdrOutputSettings());
     response.getPlutoSdrOutputSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int PlutoSDROutput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 665 of file plutosdroutput.cpp.
References PlutoSDROutput::MsgConfigurePlutoSDR::create(), SWGSDRangel::SWGPlutoSdrOutputSettings::getAntennaPath(), SWGSDRangel::SWGPlutoSdrOutputSettings::getAtt(), SWGSDRangel::SWGPlutoSdrOutputSettings::getCenterFrequency(), SWGSDRangel::SWGPlutoSdrOutputSettings::getDevSampleRate(), SWGSDRangel::SWGPlutoSdrOutputSettings::getLog2Interp(), SWGSDRangel::SWGPlutoSdrOutputSettings::getLOppmTenths(), SWGSDRangel::SWGPlutoSdrOutputSettings::getLpfBw(), SWGSDRangel::SWGPlutoSdrOutputSettings::getLpfFirbw(), SWGSDRangel::SWGPlutoSdrOutputSettings::getLpfFirEnable(), SWGSDRangel::SWGPlutoSdrOutputSettings::getLpfFirGain(), SWGSDRangel::SWGPlutoSdrOutputSettings::getLpfFiRlog2Interp(), SWGSDRangel::SWGDeviceSettings::getPlutoSdrOutputSettings(), SWGSDRangel::SWGPlutoSdrOutputSettings::getReverseApiAddress(), SWGSDRangel::SWGPlutoSdrOutputSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGPlutoSdrOutputSettings::getReverseApiPort(), SWGSDRangel::SWGPlutoSdrOutputSettings::getTransverterDeltaFrequency(), SWGSDRangel::SWGPlutoSdrOutputSettings::getTransverterMode(), SWGSDRangel::SWGPlutoSdrOutputSettings::getUseReverseApi(), PlutoSDROutputSettings::m_antennaPath, PlutoSDROutputSettings::m_att, PlutoSDROutputSettings::m_centerFrequency, PlutoSDROutputSettings::m_devSampleRate, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, PlutoSDROutputSettings::m_log2Interp, PlutoSDROutputSettings::m_LOppmTenths, PlutoSDROutputSettings::m_lpfBW, PlutoSDROutputSettings::m_lpfFIRBW, PlutoSDROutputSettings::m_lpfFIREnable, PlutoSDROutputSettings::m_lpfFIRGain, PlutoSDROutputSettings::m_lpfFIRlog2Interp, PlutoSDROutputSettings::m_reverseAPIAddress, PlutoSDROutputSettings::m_reverseAPIDeviceIndex, PlutoSDROutputSettings::m_reverseAPIPort, m_settings, PlutoSDROutputSettings::m_transverterDeltaFrequency, PlutoSDROutputSettings::m_transverterMode, PlutoSDROutputSettings::m_useReverseAPI, MessageQueue::push(), PlutoSDROutputSettings::RFPATH_END, and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     PlutoSDROutputSettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getPlutoSdrOutputSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("devSampleRate")) {
         settings.m_devSampleRate = response.getPlutoSdrOutputSettings()->getDevSampleRate();
     }
     if (deviceSettingsKeys.contains("LOppmTenths")) {
         settings.m_LOppmTenths = response.getPlutoSdrOutputSettings()->getLOppmTenths();
     }
     if (deviceSettingsKeys.contains("lpfFIREnable")) {
         settings.m_lpfFIREnable = response.getPlutoSdrOutputSettings()->getLpfFirEnable() != 0;
     }
     if (deviceSettingsKeys.contains("lpfFIRBW")) {
         settings.m_lpfFIRBW = response.getPlutoSdrOutputSettings()->getLpfFirbw();
     }
     if (deviceSettingsKeys.contains("lpfFIRlog2Interp")) {
         settings.m_lpfFIRlog2Interp = response.getPlutoSdrOutputSettings()->getLpfFiRlog2Interp();
     }
     if (deviceSettingsKeys.contains("lpfFIRGain")) {
         settings.m_lpfFIRGain = response.getPlutoSdrOutputSettings()->getLpfFirGain();
     }
     if (deviceSettingsKeys.contains("log2Interp")) {
         settings.m_log2Interp = response.getPlutoSdrOutputSettings()->getLog2Interp();
     }
     if (deviceSettingsKeys.contains("lpfBW")) {
         settings.m_lpfBW = response.getPlutoSdrOutputSettings()->getLpfBw();
     }
     if (deviceSettingsKeys.contains("att")) {
         settings.m_att = response.getPlutoSdrOutputSettings()->getAtt();
     }
     if (deviceSettingsKeys.contains("antennaPath")) {
         int antennaPath = response.getPlutoSdrOutputSettings()->getAntennaPath();
         antennaPath = antennaPath < 0 ? 0 : antennaPath >= PlutoSDROutputSettings::RFPATH_END ? PlutoSDROutputSettings::RFPATH_END-1 : antennaPath;
         settings.m_antennaPath = (PlutoSDROutputSettings::RFPath) antennaPath;
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency")) {
         settings.m_transverterDeltaFrequency = response.getPlutoSdrOutputSettings()->getTransverterDeltaFrequency();
     }
     if (deviceSettingsKeys.contains("transverterMode")) {
         settings.m_transverterMode = response.getPlutoSdrOutputSettings()->getTransverterMode() != 0;
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getPlutoSdrOutputSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getPlutoSdrOutputSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getPlutoSdrOutputSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getPlutoSdrOutputSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigurePlutoSDR *msg = MsgConfigurePlutoSDR::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigurePlutoSDR *msgToGUI = MsgConfigurePlutoSDR::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_deviceAPI
DeviceAPI* PlutoSDROutput::m_deviceAPI private
Definition at line 133 of file plutosdroutput.h.
Referenced by applySettings(), closeDevice(), handleMessage(), openDevice(), resumeBuddies(), suspendBuddies(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), and webapiRunGet().
m_deviceDescription
QString PlutoSDROutput::m_deviceDescription private
Definition at line 134 of file plutosdroutput.h.
Referenced by getDeviceDescription().
m_deviceSampleRates
DevicePlutoSDRBox::SampleRates PlutoSDROutput::m_deviceSampleRates private
Definition at line 140 of file plutosdroutput.h.
Referenced by applySettings(), getDACSampleRate(), and getFIRSampleRate().
m_deviceShared
DevicePlutoSDRShared PlutoSDROutput::m_deviceShared private
Definition at line 137 of file plutosdroutput.h.
Referenced by applySettings(), closeDevice(), fetchTemperature(), getbbLPRange(), getLORange(), getRSSI(), getTemperature(), openDevice(), start(), and stop().
m_mutex
QMutex PlutoSDROutput::m_mutex private
Definition at line 141 of file plutosdroutput.h.
m_networkManager
QNetworkAccessManager* PlutoSDROutput::m_networkManager private
Definition at line 142 of file plutosdroutput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~PlutoSDROutput().
m_networkRequest
QNetworkRequest PlutoSDROutput::m_networkRequest private
Definition at line 143 of file plutosdroutput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_plutoSDROutputThread
PlutoSDROutputThread* PlutoSDROutput::m_plutoSDROutputThread private
Definition at line 139 of file plutosdroutput.h.
Referenced by applySettings(), start(), and stop().
m_plutoTxBuffer
struct iio_buffer* PlutoSDROutput::m_plutoTxBuffer private
Definition at line 138 of file plutosdroutput.h.
Referenced by openDevice().
m_running
bool PlutoSDROutput::m_running private
Definition at line 136 of file plutosdroutput.h.
Referenced by start(), and stop().
m_settings
PlutoSDROutputSettings PlutoSDROutput::m_settings private
Definition at line 135 of file plutosdroutput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), serialize(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
The documentation for this class was generated from the following files:
plugins/samplesink/plutosdroutput/plutosdroutput.h
plugins/samplesink/plutosdroutput/plutosdroutput.cpp