SDRAngel: BasicChannelSettingsDialog Class Reference
BasicChannelSettingsDialog Class Reference
#include <basicchannelsettingsdialog.h>
Inherits QDialog.
Public Member Functions
BasicChannelSettingsDialog (ChannelMarker *marker, QWidget *parent=0)
~BasicChannelSettingsDialog ()
bool hasChanged () const
bool useReverseAPI () const
const QString & getReverseAPIAddress () const
uint16_t getReverseAPIPort () const
uint16_t getReverseAPIDeviceIndex () const
uint16_t getReverseAPIChannelIndex () const
void setUseReverseAPI (bool useReverseAPI)
void setReverseAPIAddress (const QString &address)
void setReverseAPIPort (uint16_t port)
void setReverseAPIDeviceIndex (uint16_t deviceIndex)
void setReverseAPIChannelIndex (uint16_t channelIndex)
Private Slots
void on_colorBtn_clicked ()
void on_reverseAPI_toggled (bool checked)
void on_reverseAPIAddress_editingFinished ()
void on_reverseAPIPort_editingFinished ()
void on_reverseAPIDeviceIndex_editingFinished ()
void on_reverseAPIChannelIndex_editingFinished ()
void accept ()
Private Member Functions
void paintColor ()
Private Attributes
Ui::BasicChannelSettingsDialog * ui
ChannelMarker * m_channelMarker
QColor m_color
bool m_useReverseAPI
QString m_reverseAPIAddress
uint16_t m_reverseAPIPort
uint16_t m_reverseAPIDeviceIndex
uint16_t m_reverseAPIChannelIndex
bool m_hasChanged
Detailed Description
Definition at line 14 of file basicchannelsettingsdialog.h.
Constructor & Destructor Documentation
BasicChannelSettingsDialog()
BasicChannelSettingsDialog::BasicChannelSettingsDialog (ChannelMarker * marker, QWidget * parent = 0) explicit
Definition at line 8 of file basicchannelsettingsdialog.cpp.
References ChannelMarker::getColor(), ChannelMarker::getFrequencyScaleDisplayType(), ChannelMarker::getTitle(), m_channelMarker, m_color, paintColor(), setReverseAPIAddress(), setReverseAPIChannelIndex(), setReverseAPIDeviceIndex(), setReverseAPIPort(), setUseReverseAPI(), and ui.
                                                                                              :
     QDialog(parent),
     ui(new Ui::BasicChannelSettingsDialog),
     m_channelMarker(marker),
     m_hasChanged(false)
 {
     ui->setupUi(this);
     ui->title->setText(m_channelMarker->getTitle());
     m_color = m_channelMarker->getColor();
     ui->fScaleDisplayType->setCurrentIndex((int) m_channelMarker->getFrequencyScaleDisplayType());
     setUseReverseAPI(false);
     setReverseAPIAddress("127.0.0.1");
     setReverseAPIPort(8888);
     setReverseAPIDeviceIndex(0);
     setReverseAPIChannelIndex(0);
     paintColor();
 }
~BasicChannelSettingsDialog()
BasicChannelSettingsDialog::~BasicChannelSettingsDialog ()
Definition at line 26 of file basicchannelsettingsdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
accept
void BasicChannelSettingsDialog::accept () private slot
Definition at line 135 of file basicchannelsettingsdialog.cpp.
References m_channelMarker, m_color, m_hasChanged, ChannelMarker::setColor(), ChannelMarker::setFrequencyScaleDisplayType(), ChannelMarker::setTitle(), and ui.
 {
     m_channelMarker->blockSignals(true);
     m_channelMarker->setTitle(ui->title->text());
     if(m_color.isValid()) {
         m_channelMarker->setColor(m_color);
     }
     m_channelMarker->setFrequencyScaleDisplayType((ChannelMarker::frequencyScaleDisplay_t) ui->fScaleDisplayType->currentIndex());
     m_channelMarker->blockSignals(false);
     m_hasChanged = true;
     QDialog::accept();
 }
getReverseAPIAddress()
const QString& BasicChannelSettingsDialog::getReverseAPIAddress () const inline
Definition at line 23 of file basicchannelsettingsdialog.h.
Referenced by WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), and DSDDemodGUI::onMenuDialogCalled().
 { return m_reverseAPIAddress; }
getReverseAPIChannelIndex()
uint16_t BasicChannelSettingsDialog::getReverseAPIChannelIndex () const inline
Definition at line 26 of file basicchannelsettingsdialog.h.
Referenced by WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), and DSDDemodGUI::onMenuDialogCalled().
 { return m_reverseAPIChannelIndex; }
getReverseAPIDeviceIndex()
uint16_t BasicChannelSettingsDialog::getReverseAPIDeviceIndex () const inline
Definition at line 25 of file basicchannelsettingsdialog.h.
Referenced by WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), and DSDDemodGUI::onMenuDialogCalled().
 { return m_reverseAPIDeviceIndex; }
getReverseAPIPort()
uint16_t BasicChannelSettingsDialog::getReverseAPIPort () const inline
Definition at line 24 of file basicchannelsettingsdialog.h.
Referenced by WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), and DSDDemodGUI::onMenuDialogCalled().
 { return m_reverseAPIPort; }
hasChanged()
bool BasicChannelSettingsDialog::hasChanged () const inline
Definition at line 21 of file basicchannelsettingsdialog.h.
 { return m_hasChanged; }
on_colorBtn_clicked
void BasicChannelSettingsDialog::on_colorBtn_clicked () private slot
Definition at line 77 of file basicchannelsettingsdialog.cpp.
References m_color, and paintColor().
 {
     QColor c = m_color;
     c = QColorDialog::getColor(c, this, tr("Select Color for Channel"), QColorDialog::DontUseNativeDialog);
     if (c.isValid())
     {
         m_color = c;
         paintColor();
     }
 }
on_reverseAPI_toggled
void BasicChannelSettingsDialog::on_reverseAPI_toggled (bool checked) private slot
Definition at line 89 of file basicchannelsettingsdialog.cpp.
References m_useReverseAPI.
 {
     m_useReverseAPI = checked;
 }
on_reverseAPIAddress_editingFinished
void BasicChannelSettingsDialog::on_reverseAPIAddress_editingFinished () private slot
Definition at line 94 of file basicchannelsettingsdialog.cpp.
References m_reverseAPIAddress, and ui.
 {
     m_reverseAPIAddress = ui->reverseAPIAddress->text();
 }
on_reverseAPIChannelIndex_editingFinished
void BasicChannelSettingsDialog::on_reverseAPIChannelIndex_editingFinished () private slot
Definition at line 123 of file basicchannelsettingsdialog.cpp.
References m_reverseAPIChannelIndex, and ui.
 {
     bool dataOk;
     int reverseAPIChannelIndex = ui->reverseAPIChannelIndex->text().toInt(&dataOk);
     if ((!dataOk) || (reverseAPIChannelIndex < 0)) {
         return;
     } else {
         m_reverseAPIChannelIndex = reverseAPIChannelIndex;
     }
 }
on_reverseAPIDeviceIndex_editingFinished
void BasicChannelSettingsDialog::on_reverseAPIDeviceIndex_editingFinished () private slot
Definition at line 111 of file basicchannelsettingsdialog.cpp.
References m_reverseAPIDeviceIndex, and ui.
 {
     bool dataOk;
     int reverseAPIDeviceIndex = ui->reverseAPIDeviceIndex->text().toInt(&dataOk);
     if ((!dataOk) || (reverseAPIDeviceIndex < 0)) {
         return;
     } else {
         m_reverseAPIDeviceIndex = reverseAPIDeviceIndex;
     }
 }
on_reverseAPIPort_editingFinished
void BasicChannelSettingsDialog::on_reverseAPIPort_editingFinished () private slot
Definition at line 99 of file basicchannelsettingsdialog.cpp.
References m_reverseAPIPort, and ui.
 {
     bool dataOk;
     int reverseAPIPort = ui->reverseAPIPort->text().toInt(&dataOk);
     if((!dataOk) || (reverseAPIPort < 1024) || (reverseAPIPort > 65535)) {
         return;
     } else {
         m_reverseAPIPort = reverseAPIPort;
     }
 }
paintColor()
void BasicChannelSettingsDialog::paintColor () private
Definition at line 66 of file basicchannelsettingsdialog.cpp.
References arg(), m_color, and ui.
Referenced by BasicChannelSettingsDialog(), and on_colorBtn_clicked().
 {
     QPixmap pm(24, 24);
     pm.fill(m_color);
     ui->colorBtn->setIcon(pm);
     ui->colorText->setText(tr("#%1%2%3")
         .arg(m_color.red(), 2, 16, QChar('0'))
         .arg(m_color.green(), 2, 16, QChar('0'))
         .arg(m_color.blue(), 2, 16, QChar('0')));
 }
setReverseAPIAddress()
void BasicChannelSettingsDialog::setReverseAPIAddress (const QString & address)
Definition at line 37 of file basicchannelsettingsdialog.cpp.
References m_reverseAPIAddress, and ui.
Referenced by BasicChannelSettingsDialog(), WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), and DSDDemodGUI::onMenuDialogCalled().
 {
     m_reverseAPIAddress = address;
     ui->reverseAPIAddress->setText(m_reverseAPIAddress);
 }
setReverseAPIChannelIndex()
void BasicChannelSettingsDialog::setReverseAPIChannelIndex (uint16_t channelIndex)
Definition at line 60 of file basicchannelsettingsdialog.cpp.
References arg(), m_reverseAPIChannelIndex, and ui.
Referenced by BasicChannelSettingsDialog(), WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), and DSDDemodGUI::onMenuDialogCalled().
 {
     m_reverseAPIChannelIndex = channelIndex > 99 ? 99 : channelIndex;
     ui->reverseAPIChannelIndex->setText(tr("%1").arg(m_reverseAPIChannelIndex));
 }
setReverseAPIDeviceIndex()
void BasicChannelSettingsDialog::setReverseAPIDeviceIndex (uint16_t deviceIndex)
Definition at line 54 of file basicchannelsettingsdialog.cpp.
References arg(), m_reverseAPIDeviceIndex, and ui.
Referenced by BasicChannelSettingsDialog(), WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), and DSDDemodGUI::onMenuDialogCalled().
 {
     m_reverseAPIDeviceIndex = deviceIndex > 99 ? 99 : deviceIndex;
     ui->reverseAPIDeviceIndex->setText(tr("%1").arg(m_reverseAPIDeviceIndex));
 }
setReverseAPIPort()
void BasicChannelSettingsDialog::setReverseAPIPort (uint16_t port)
Definition at line 43 of file basicchannelsettingsdialog.cpp.
References arg(), m_reverseAPIPort, and ui.
Referenced by BasicChannelSettingsDialog(), WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), and DSDDemodGUI::onMenuDialogCalled().
 {
     if (port < 1024) {
         return;
     } else {
         m_reverseAPIPort = port;
     }
     ui->reverseAPIPort->setText(tr("%1").arg(m_reverseAPIPort));
 }
setUseReverseAPI()
void BasicChannelSettingsDialog::setUseReverseAPI (bool useReverseAPI)
Definition at line 31 of file basicchannelsettingsdialog.cpp.
References m_useReverseAPI, ui, and useReverseAPI().
Referenced by BasicChannelSettingsDialog(), WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), and DSDDemodGUI::onMenuDialogCalled().
 {
     m_useReverseAPI = useReverseAPI;
     ui->reverseAPI->setChecked(m_useReverseAPI);
 }
useReverseAPI()
bool BasicChannelSettingsDialog::useReverseAPI () const inline
Definition at line 22 of file basicchannelsettingsdialog.h.
Referenced by WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), DSDDemodGUI::onMenuDialogCalled(), and setUseReverseAPI().
 { return m_useReverseAPI; }
Member Data Documentation
m_channelMarker
ChannelMarker* BasicChannelSettingsDialog::m_channelMarker private
Definition at line 44 of file basicchannelsettingsdialog.h.
Referenced by accept(), and BasicChannelSettingsDialog().
m_color
QColor BasicChannelSettingsDialog::m_color private
Definition at line 45 of file basicchannelsettingsdialog.h.
Referenced by accept(), BasicChannelSettingsDialog(), on_colorBtn_clicked(), and paintColor().
m_hasChanged
bool BasicChannelSettingsDialog::m_hasChanged private
Definition at line 51 of file basicchannelsettingsdialog.h.
Referenced by accept().
m_reverseAPIAddress
QString BasicChannelSettingsDialog::m_reverseAPIAddress private
Definition at line 47 of file basicchannelsettingsdialog.h.
Referenced by on_reverseAPIAddress_editingFinished(), and setReverseAPIAddress().
m_reverseAPIChannelIndex
uint16_t BasicChannelSettingsDialog::m_reverseAPIChannelIndex private
Definition at line 50 of file basicchannelsettingsdialog.h.
Referenced by on_reverseAPIChannelIndex_editingFinished(), and setReverseAPIChannelIndex().
m_reverseAPIDeviceIndex
uint16_t BasicChannelSettingsDialog::m_reverseAPIDeviceIndex private
Definition at line 49 of file basicchannelsettingsdialog.h.
Referenced by on_reverseAPIDeviceIndex_editingFinished(), and setReverseAPIDeviceIndex().
m_reverseAPIPort
uint16_t BasicChannelSettingsDialog::m_reverseAPIPort private
Definition at line 48 of file basicchannelsettingsdialog.h.
Referenced by on_reverseAPIPort_editingFinished(), and setReverseAPIPort().
m_useReverseAPI
bool BasicChannelSettingsDialog::m_useReverseAPI private
Definition at line 46 of file basicchannelsettingsdialog.h.
Referenced by on_reverseAPI_toggled(), and setUseReverseAPI().
ui
Ui::BasicChannelSettingsDialog* BasicChannelSettingsDialog::ui private
Definition at line 43 of file basicchannelsettingsdialog.h.
Referenced by accept(), BasicChannelSettingsDialog(), on_reverseAPIAddress_editingFinished(), on_reverseAPIChannelIndex_editingFinished(), on_reverseAPIDeviceIndex_editingFinished(), on_reverseAPIPort_editingFinished(), paintColor(), setReverseAPIAddress(), setReverseAPIChannelIndex(), setReverseAPIDeviceIndex(), setReverseAPIPort(), setUseReverseAPI(), and ~BasicChannelSettingsDialog().
The documentation for this class was generated from the following files:
sdrgui/gui/basicchannelsettingsdialog.h
sdrgui/gui/basicchannelsettingsdialog.cpp