SDRAngel: SimpleDeserializer Class Reference
SimpleDeserializer Class Reference
#include <simpleserializer.h>
Classes
struct Element
Public Member Functions
SimpleDeserializer (const QByteArray &data)
bool readS32 (quint32 id, qint32 *result, qint32 def=0) const
bool readU32 (quint32 id, quint32 *result, quint32 def=0) const
bool readS64 (quint32 id, qint64 *result, qint64 def=0) const
bool readU64 (quint32 id, quint64 *result, quint64 def=0) const
bool readFloat (quint32 id, float *result, float def=0) const
bool readDouble (quint32 id, double *result, double def=0) const
bool readReal (quint32 id, Real *result, Real def=0) const
bool readBool (quint32 id, bool *result, bool def=false) const
bool readString (quint32 id, QString *result, const QString &def=QString::null) const
bool readBlob (quint32 id, QByteArray *result, const QByteArray &def=QByteArray()) const
bool isValid () const
quint32 getVersion () const
void dump () const
Private Types
enum Type {
TSigned32 = 0, TUnsigned32 = 1, TSigned64 = 2, TUnsigned64 = 3,
TFloat = 4, TDouble = 5, TBool = 6, TString = 7,
TBlob = 8, TVersion = 9
}
typedef QMap< quint32, Element > Elements
Private Member Functions
bool parseAll ()
bool readTag (uint *readOfs, uint readEnd, Type *type, quint32 *id, quint32 *length) const
quint8 readByte (uint *readOfs) const
Private Attributes
QByteArray m_data
bool m_valid
Elements m_elements
quint32 m_version
Detailed Description
Definition at line 51 of file simpleserializer.h.
Member Typedef Documentation
Elements
typedef QMap<quint32, Element> SimpleDeserializer::Elements private
Definition at line 95 of file simpleserializer.h.
Member Enumeration Documentation
Type
enum SimpleDeserializer::Type private
Enumerator
TSigned32
TUnsigned32
TSigned64
TUnsigned64
TFloat
TDouble
TBool
TString
TBlob
TVersion
Definition at line 71 of file simpleserializer.h.
               {
         TSigned32 = 0,
         TUnsigned32 = 1,
         TSigned64 = 2,
         TUnsigned64 = 3,
         TFloat = 4,
         TDouble = 5,
         TBool = 6,
         TString = 7,
         TBlob = 8,
         TVersion = 9
     };
Constructor & Destructor Documentation
SimpleDeserializer()
SimpleDeserializer::SimpleDeserializer (const QByteArray & data)
Definition at line 297 of file simpleserializer.cpp.
References i, m_elements, m_valid, m_version, parseAll(), readByte(), and TVersion.
                                                              :
     m_data(data)
 {
     m_valid = parseAll();
     // read version information
     uint readOfs;
     Elements::const_iterator it = m_elements.constFind(0);
     if(it == m_elements.constEnd())
         goto setInvalid;
     if(it->type != TVersion)
         goto setInvalid;
     if(it->length > 4)
         goto setInvalid;
     readOfs = it->ofs;
     m_version = 0;
     for(uint i = 0; i < it->length; i++)
         m_version = (m_version << 8) | readByte(&readOfs);
     return;
 setInvalid:
     m_valid = false;
 }
Member Function Documentation
dump()
void SimpleDeserializer::dump () const
Definition at line 587 of file simpleserializer.cpp.
References m_elements, m_valid, m_version, PRINTF_FORMAT_S32, PRINTF_FORMAT_U32, readBlob(), readBool(), readDouble(), readFloat(), readS32(), readS64(), readString(), readU32(), readU64(), TBlob, TBool, TDouble, TFloat, TSigned32, TSigned64, TString, TUnsigned32, TUnsigned64, and TVersion.
 {
     if(!m_valid) {
         qDebug("SimpleDeserializer dump: data invalid");
         return;
     } else {
         qDebug("SimpleDeserializer dump: version %u", m_version);
     }
     for(Elements::const_iterator it = m_elements.constBegin(); it != m_elements.constEnd(); ++it) {
         switch(it->type) {
             case TSigned32: {
                 qint32 tmp;
                 readS32(it.key(), &tmp);
                 qDebug("id %d, S32, len %d: " PRINTF_FORMAT_S32, it.key(), it->length, tmp);
                 break;
             }
             case TUnsigned32: {
                 quint32 tmp;
                 readU32(it.key(), &tmp);
                 qDebug("id %d, U32, len %d: " PRINTF_FORMAT_U32, it.key(), it->length, tmp);
                 break;
             }
             case TSigned64: {
                 qint64 tmp;
                 readS64(it.key(), &tmp);
 //              qDebug("id %d, S64, len %d: " PRINTF_FORMAT_S64, it.key(), it->length, (int)tmp);
                 break;
             }
             case TUnsigned64: {
                 quint64 tmp;
                 readU64(it.key(), &tmp);
 //              qDebug("id %d, U64, len %d: " PRINTF_FORMAT_U64, it.key(), it->length, (uint)tmp);
                 break;
             }
             case TFloat: {
                 float tmp;
                 readFloat(it.key(), &tmp);
                 qDebug("id %d, FLOAT, len %d: %f", it.key(), it->length, tmp);
                 break;
             }
             case TDouble: {
                 double tmp;
                 readDouble(it.key(), &tmp);
                 qDebug("id %d, DOUBLE, len %d: %f", it.key(), it->length, tmp);
                 break;
             }
             case TBool: {
                 bool tmp;
                 readBool(it.key(), &tmp);
                 qDebug("id %d, BOOL, len %d: %s", it.key(), it->length, tmp ? "true" : "false");
                 break;
             }
             case TString: {
                 QString tmp;
                 readString(it.key(), &tmp);
                 qDebug("id %d, STRING, len %d: \"%s\"", it.key(), it->length, qPrintable(tmp));
                 break;
             }
             case TBlob: {
                 QByteArray tmp;
                 readBlob(it.key(), &tmp);
                 qDebug("id %d, BLOB, len %d", it.key(), it->length);
                 break;
             }
             case TVersion: {
                 qDebug("id %d, VERSION, len %d", it.key(), it->length);
                 break;
             }
             default: {
                 qDebug("id %d, UNKNOWN TYPE 0x%02x, len %d", it.key(), it->type, it->length);
                 break;
             }
         }
     }
 }
getVersion()
quint32 SimpleDeserializer::getVersion () const inline
Definition at line 67 of file simpleserializer.h.
Referenced by Preferences::deserialize(), LoRaDemodSettings::deserialize(), FileSinkSettings::deserialize(), LocalOutputSettings::deserialize(), GLSpectrumGUI::deserialize(), LocalInputSettings::deserialize(), RemoteInputSettings::deserialize(), Command::deserialize(), FileInputSettings::deserialize(), KiwiSDRSettings::deserialize(), BladeRF2OutputSettings::deserialize(), RemoteOutputSettings::deserialize(), BladeRF1OutputSettings::deserialize(), RemoteSourceSettings::deserialize(), LocalSourceSettings::deserialize(), LocalSinkSettings::deserialize(), FileSourceSettings::deserialize(), AirspyHFSettings::deserialize(), HackRFOutputSettings::deserialize(), SoapySDROutputSettings::deserialize(), HackRFInputSettings::deserialize(), DeviceUserArgs::deserialize(), BladeRF2InputSettings::deserialize(), WFMDemodSettings::deserialize(), ATVDemodGUI::deserialize(), AirspySettings::deserialize(), BladeRF1InputSettings::deserialize(), FCDProPlusSettings::deserialize(), PerseusSettings::deserialize(), RTLSDRSettings::deserialize(), RemoteSinkSettings::deserialize(), CWKeyerSettings::deserialize(), BFMDemodSettings::deserialize(), XTRXOutputSettings::deserialize(), AMDemodSettings::deserialize(), SDRPlaySettings::deserialize(), PlutoSDROutputSettings::deserialize(), GLScopeGUI::deserialize(), NFMDemodSettings::deserialize(), SSBDemodSettings::deserialize(), ChannelAnalyzerSettings::deserialize(), FreqTrackerSettings::deserialize(), FreeDVDemodSettings::deserialize(), FCDProSettings::deserialize(), SoapySDRInputSettings::deserialize(), DSDDemodSettings::deserialize(), AMModSettings::deserialize(), WFMModSettings::deserialize(), XTRXInputSettings::deserialize(), Preset::deserialize(), LimeSDROutputSettings::deserialize(), NFMModSettings::deserialize(), TestSourceSettings::deserialize(), UDPSourceSettings::deserialize(), FreeDVModSettings::deserialize(), SSBModSettings::deserialize(), TestMISettings::deserialize(), LimeSDRInputSettings::deserialize(), UDPSinkSettings::deserialize(), ChannelMarker::deserialize(), PlutoSDRInputSettings::deserialize(), ATVModSettings::deserialize(), ATVDemodSettings::deserialize(), DATVDemodSettings::deserialize(), DoubleBufferSimple< Sample >::deserialize(), AudioDeviceManager::deserialize(), ScopeVis::TraceBackBuffer::deserialize(), ScopeVis::TraceBackDiscreteMemory::deserialize(), ScopeVis::deserializeMemory(), and SampleSourceSerializer::readSerializedData().
 { return m_version; }
isValid()
bool SimpleDeserializer::isValid () const inline
Definition at line 66 of file simpleserializer.h.
Referenced by Preferences::deserialize(), LoRaDemodSettings::deserialize(), FileSinkSettings::deserialize(), LocalOutputSettings::deserialize(), GLSpectrumGUI::deserialize(), LocalInputSettings::deserialize(), RemoteInputSettings::deserialize(), Command::deserialize(), FileInputSettings::deserialize(), KiwiSDRSettings::deserialize(), BladeRF2OutputSettings::deserialize(), RemoteOutputSettings::deserialize(), BladeRF1OutputSettings::deserialize(), RemoteSourceSettings::deserialize(), LocalSourceSettings::deserialize(), LocalSinkSettings::deserialize(), FileSourceSettings::deserialize(), AirspyHFSettings::deserialize(), HackRFOutputSettings::deserialize(), SoapySDROutputSettings::deserialize(), HackRFInputSettings::deserialize(), DeviceUserArgs::deserialize(), BladeRF2InputSettings::deserialize(), WFMDemodSettings::deserialize(), ATVDemodGUI::deserialize(), AirspySettings::deserialize(), BladeRF1InputSettings::deserialize(), FCDProPlusSettings::deserialize(), PerseusSettings::deserialize(), RTLSDRSettings::deserialize(), RemoteSinkSettings::deserialize(), CWKeyerSettings::deserialize(), BFMDemodSettings::deserialize(), XTRXOutputSettings::deserialize(), AMDemodSettings::deserialize(), SDRPlaySettings::deserialize(), PlutoSDROutputSettings::deserialize(), GLScopeGUI::deserialize(), NFMDemodSettings::deserialize(), SSBDemodSettings::deserialize(), ChannelAnalyzerSettings::deserialize(), FreqTrackerSettings::deserialize(), FreeDVDemodSettings::deserialize(), FCDProSettings::deserialize(), SoapySDRInputSettings::deserialize(), DSDDemodSettings::deserialize(), AMModSettings::deserialize(), WFMModSettings::deserialize(), XTRXInputSettings::deserialize(), Preset::deserialize(), LimeSDROutputSettings::deserialize(), NFMModSettings::deserialize(), TestSourceSettings::deserialize(), UDPSourceSettings::deserialize(), FreeDVModSettings::deserialize(), SSBModSettings::deserialize(), TestMISettings::deserialize(), LimeSDRInputSettings::deserialize(), UDPSinkSettings::deserialize(), ChannelMarker::deserialize(), PlutoSDRInputSettings::deserialize(), ATVModSettings::deserialize(), ATVDemodSettings::deserialize(), DATVDemodSettings::deserialize(), DoubleBufferSimple< Sample >::deserialize(), AudioDeviceManager::deserialize(), ScopeVis::TraceBackBuffer::deserialize(), ScopeVis::TraceBackDiscreteMemory::deserialize(), ScopeVis::deserializeMemory(), and SampleSourceSerializer::readSerializedData().
 { return m_valid; }
parseAll()
bool SimpleDeserializer::parseAll () private
Definition at line 664 of file simpleserializer.cpp.
References m_data, m_elements, and readTag().
Referenced by SimpleDeserializer().
 {
     uint readOfs = 0;
     Type type;
     quint32 id;
     quint32 length;
     /*
     QString hex;
     for(int i = 0; i < m_data.size(); i++)
         hex.append(QString("%1 ").arg((quint8)m_data[i], 2, 16, QChar('0')));
     qDebug("%s", qPrintable(hex));
     qDebug("==");
     */
     while(readOfs < (uint)m_data.size()) {
         if(!readTag(&readOfs, m_data.size(), &type, &id, &length))
             return false;
         //qDebug("-- id %d, TYPE 0x%02x, len %d", id, type, length);
         if(m_elements.contains(id)) {
             qDebug("SimpleDeserializer: same ID found twice (id %u)", id);
             return false;
         }
         m_elements.insert(id, Element(type, readOfs, length));
         readOfs += length;
         if(readOfs == (uint)m_data.size())
             return true;
     }
     return false;
 }
readBlob()
bool SimpleDeserializer::readBlob (quint32 id, QByteArray * result, const QByteArray & def = QByteArray()) const
Definition at line 571 of file simpleserializer.cpp.
References m_data, m_elements, and TBlob.
Referenced by LoRaDemodSettings::deserialize(), SoapySDROutputSettings::deserialize(), DeviceUserArgs::deserialize(), WFMDemodSettings::deserialize(), BFMDemodSettings::deserialize(), AMDemodSettings::deserialize(), SSBDemodSettings::deserialize(), NFMDemodSettings::deserialize(), ChannelAnalyzerSettings::deserialize(), FreqTrackerSettings::deserialize(), FreeDVDemodSettings::deserialize(), DSDDemodSettings::deserialize(), SoapySDRInputSettings::deserialize(), AMModSettings::deserialize(), WFMModSettings::deserialize(), Preset::deserialize(), NFMModSettings::deserialize(), UDPSourceSettings::deserialize(), FreeDVModSettings::deserialize(), SSBModSettings::deserialize(), UDPSinkSettings::deserialize(), ATVModSettings::deserialize(), DATVDemodSettings::deserialize(), DoubleBufferSimple< Sample >::deserialize(), AudioDeviceManager::deserialize(), ScopeVis::TraceBackBuffer::deserialize(), ScopeVis::TraceBackDiscreteMemory::deserialize(), ScopeVis::deserializeMemory(), and dump().
 {
     Elements::const_iterator it = m_elements.constFind(id);
     if(it == m_elements.constEnd())
         goto returnDefault;
     if(it->type != TBlob)
         goto returnDefault;
     *result = QByteArray(m_data.data() + it->ofs, it->length);
     return true;
 returnDefault:
     *result = def;
     return false;
 }
readBool()
bool SimpleDeserializer::readBool (quint32 id, bool * result, bool def = false) const
Definition at line 531 of file simpleserializer.cpp.
References m_elements, readByte(), and TBool.
Referenced by Preferences::deserialize(), LocalInputSettings::deserialize(), GLSpectrumGUI::deserialize(), RemoteInputSettings::deserialize(), Command::deserialize(), BladeRF2OutputSettings::deserialize(), FileInputSettings::deserialize(), KiwiSDRSettings::deserialize(), RemoteOutputSettings::deserialize(), RemoteSourceSettings::deserialize(), BladeRF1OutputSettings::deserialize(), LocalSourceSettings::deserialize(), LocalSinkSettings::deserialize(), FileSourceSettings::deserialize(), AirspyHFSettings::deserialize(), HackRFOutputSettings::deserialize(), SoapySDROutputSettings::deserialize(), HackRFInputSettings::deserialize(), BladeRF2InputSettings::deserialize(), WFMDemodSettings::deserialize(), ATVDemodGUI::deserialize(), AirspySettings::deserialize(), BladeRF1InputSettings::deserialize(), FCDProPlusSettings::deserialize(), PerseusSettings::deserialize(), RTLSDRSettings::deserialize(), CWKeyerSettings::deserialize(), RemoteSinkSettings::deserialize(), XTRXOutputSettings::deserialize(), BFMDemodSettings::deserialize(), AMDemodSettings::deserialize(), SDRPlaySettings::deserialize(), NFMDemodSettings::deserialize(), SSBDemodSettings::deserialize(), GLScopeGUI::deserialize(), PlutoSDROutputSettings::deserialize(), ChannelAnalyzerSettings::deserialize(), FreqTrackerSettings::deserialize(), FreeDVDemodSettings::deserialize(), FCDProSettings::deserialize(), DSDDemodSettings::deserialize(), SoapySDRInputSettings::deserialize(), AMModSettings::deserialize(), WFMModSettings::deserialize(), XTRXInputSettings::deserialize(), Preset::deserialize(), TestSourceSettings::deserialize(), LimeSDROutputSettings::deserialize(), NFMModSettings::deserialize(), UDPSourceSettings::deserialize(), FreeDVModSettings::deserialize(), SSBModSettings::deserialize(), LimeSDRInputSettings::deserialize(), TestMISettings::deserialize(), UDPSinkSettings::deserialize(), PlutoSDRInputSettings::deserialize(), ATVModSettings::deserialize(), ATVDemodSettings::deserialize(), DATVDemodSettings::deserialize(), and dump().
 {
     uint readOfs;
     quint8 tmp;
     Elements::const_iterator it = m_elements.constFind(id);
     if(it == m_elements.constEnd())
         goto returnDefault;
     if(it->type != TBool)
         goto returnDefault;
     if(it->length != 1)
         goto returnDefault;
     readOfs = it->ofs;
     tmp = readByte(&readOfs);
     if(tmp == 0x00)
         *result = false;
     else *result = true;
     return true;
 returnDefault:
     *result = def;
     return false;
 }
readByte()
quint8 SimpleDeserializer::readByte (uint * readOfs) const inline private
Definition at line 104 of file simpleserializer.h.
Referenced by readBool(), readDouble(), readFloat(), readReal(), readS32(), readS64(), readTag(), readU32(), readU64(), and SimpleDeserializer().
     {
         quint8 res = m_data[*readOfs];
         (*readOfs)++;
         return res;
     }
readDouble()
bool SimpleDeserializer::readDouble (quint32 id, double * result, double def = 0) const
Definition at line 450 of file simpleserializer.cpp.
References doubleasint::d, i, m_elements, readByte(), TDouble, and doubleasint::u.
Referenced by SoapySDROutputSettings::deserialize(), XTRXOutputSettings::deserialize(), SoapySDRInputSettings::deserialize(), XTRXInputSettings::deserialize(), and dump().
 {
     uint readOfs;
     union doubleasint tmp;
     Elements::const_iterator it = m_elements.constFind(id);
     if(it == m_elements.constEnd())
         goto returnDefault;
     if(it->type != TDouble)
         goto returnDefault;
     if(it->length != 8)
         goto returnDefault;
     readOfs = it->ofs;
     tmp.u = 0;
     for(int i = 0; i < 8; i++)
         tmp.u = (tmp.u << 8) | readByte(&readOfs);
     *result = tmp.d;
     return true;
 returnDefault:
     *result = def;
     return false;
 }
readFloat()
bool SimpleDeserializer::readFloat (quint32 id, float * result, float def = 0) const
Definition at line 426 of file simpleserializer.cpp.
References floatasint::f, i, m_elements, readByte(), TFloat, and floatasint::u.
Referenced by Preferences::deserialize(), RemoteOutputSettings::deserialize(), XTRXOutputSettings::deserialize(), GLScopeGUI::deserialize(), FreqTrackerSettings::deserialize(), XTRXInputSettings::deserialize(), TestSourceSettings::deserialize(), LimeSDROutputSettings::deserialize(), LimeSDRInputSettings::deserialize(), TestMISettings::deserialize(), DATVDemodSettings::deserialize(), and dump().
 {
     uint readOfs;
     union floatasint tmp;
     Elements::const_iterator it = m_elements.constFind(id);
     if(it == m_elements.constEnd())
         goto returnDefault;
     if(it->type != TFloat)
         goto returnDefault;
     if(it->length != 4)
         goto returnDefault;
     readOfs = it->ofs;
     tmp.u = 0;
     for(int i = 0; i < 4; i++)
         tmp.u = (tmp.u << 8) | readByte(&readOfs);
     *result = tmp.f;
     return true;
 returnDefault:
     *result = def;
     return false;
 }
readReal()
bool SimpleDeserializer::readReal (quint32 id, Real * result, Real def = 0) const
Definition at line 484 of file simpleserializer.cpp.
References i, m_elements, real4asint::r, real8asint::r, readByte(), TDouble, TFloat, real4asint::u, and real8asint::u.
Referenced by GLSpectrumGUI::deserialize(), AMModSettings::deserialize(), WFMModSettings::deserialize(), NFMModSettings::deserialize(), UDPSourceSettings::deserialize(), SSBModSettings::deserialize(), UDPSinkSettings::deserialize(), and ATVModSettings::deserialize().
 {
     if(sizeof(Real) == 4) {
         uint readOfs;
         union real4asint tmp;
         Elements::const_iterator it = m_elements.constFind(id);
         if(it == m_elements.constEnd())
             goto returnDefault32;
         if(it->type != TFloat)
             goto returnDefault32;
         if(it->length != 4)
             goto returnDefault32;
         readOfs = it->ofs;
         tmp.u = 0;
         for(int i = 0; i < 4; i++)
             tmp.u = (tmp.u << 8) | readByte(&readOfs);
         *result = tmp.r;
         return true;
     returnDefault32:
         *result = def;
         return false;
     } else {
         uint readOfs;
         union real8asint tmp;
         Elements::const_iterator it = m_elements.constFind(id);
         if(it == m_elements.constEnd())
             goto returnDefault64;
         if(it->type != TDouble)
             goto returnDefault64;
         if(it->length != 8)
             goto returnDefault64;
         readOfs = it->ofs;
         tmp.u = 0;
         for(int i = 0; i < 8; i++)
             tmp.u = (tmp.u << 8) | readByte(&readOfs);
         *result = tmp.r;
         return true;
     returnDefault64:
         *result = def;
         return false;
     }
 }
readS32()
bool SimpleDeserializer::readS32 (quint32 id, qint32 * result, qint32 def = 0) const
Definition at line 322 of file simpleserializer.cpp.
References i, m_elements, readByte(), and TSigned32.
Referenced by Preferences::deserialize(), LoRaDemodSettings::deserialize(), GLSpectrumGUI::deserialize(), Command::deserialize(), BladeRF2OutputSettings::deserialize(), BladeRF1OutputSettings::deserialize(), FileSourceSettings::deserialize(), AirspyHFSettings::deserialize(), HackRFOutputSettings::deserialize(), HackRFInputSettings::deserialize(), SoapySDROutputSettings::deserialize(), BladeRF2InputSettings::deserialize(), WFMDemodSettings::deserialize(), ATVDemodGUI::deserialize(), BladeRF1InputSettings::deserialize(), FCDProPlusSettings::deserialize(), PerseusSettings::deserialize(), RTLSDRSettings::deserialize(), CWKeyerSettings::deserialize(), AirspySettings::deserialize(), BFMDemodSettings::deserialize(), XTRXOutputSettings::deserialize(), SDRPlaySettings::deserialize(), AMDemodSettings::deserialize(), NFMDemodSettings::deserialize(), SSBDemodSettings::deserialize(), GLScopeGUI::deserialize(), PlutoSDROutputSettings::deserialize(), ChannelAnalyzerSettings::deserialize(), FreqTrackerSettings::deserialize(), FreeDVDemodSettings::deserialize(), FCDProSettings::deserialize(), SoapySDRInputSettings::deserialize(), DSDDemodSettings::deserialize(), AMModSettings::deserialize(), WFMModSettings::deserialize(), XTRXInputSettings::deserialize(), Preset::deserialize(), TestSourceSettings::deserialize(), NFMModSettings::deserialize(), LimeSDROutputSettings::deserialize(), UDPSourceSettings::deserialize(), FreeDVModSettings::deserialize(), SSBModSettings::deserialize(), TestMISettings::deserialize(), LimeSDRInputSettings::deserialize(), UDPSinkSettings::deserialize(), ChannelMarker::deserialize(), PlutoSDRInputSettings::deserialize(), ATVModSettings::deserialize(), ATVDemodSettings::deserialize(), DATVDemodSettings::deserialize(), DoubleBufferSimple< Sample >::deserialize(), ScopeVis::deserializeMemory(), dump(), and SampleSourceSerializer::readSerializedData().
 {
     uint readOfs;
     qint32 tmp;
     Elements::const_iterator it = m_elements.constFind(id);
     if(it == m_elements.constEnd())
         goto returnDefault;
     if(it->type != TSigned32)
         goto returnDefault;
     if(it->length > 4)
         goto returnDefault;
     readOfs = it->ofs;
     tmp = 0;
     for(uint i = 0; i < it->length; i++) {
         quint8 byte = readByte(&readOfs);
         if((i == 0) && (byte & 0x80))
             tmp = -1;
         tmp = (tmp << 8) | byte;
     }
     *result = tmp;
     return true;
 returnDefault:
     *result = def;
     return false;
 }
readS64()
bool SimpleDeserializer::readS64 (quint32 id, qint64 * result, qint64 def = 0) const
Definition at line 374 of file simpleserializer.cpp.
References i, m_elements, readByte(), and TSigned64.
Referenced by BladeRF2OutputSettings::deserialize(), AirspyHFSettings::deserialize(), SoapySDROutputSettings::deserialize(), BladeRF2InputSettings::deserialize(), FCDProPlusSettings::deserialize(), AirspySettings::deserialize(), PerseusSettings::deserialize(), RTLSDRSettings::deserialize(), PlutoSDROutputSettings::deserialize(), FCDProSettings::deserialize(), SoapySDRInputSettings::deserialize(), LimeSDROutputSettings::deserialize(), LimeSDRInputSettings::deserialize(), PlutoSDRInputSettings::deserialize(), and dump().
 {
     uint readOfs;
     qint64 tmp;
     Elements::const_iterator it = m_elements.constFind(id);
     if(it == m_elements.constEnd())
         goto returnDefault;
     if(it->type != TSigned64)
         goto returnDefault;
     if(it->length > 8)
         goto returnDefault;
     readOfs = it->ofs;
     tmp = 0;
     for(uint i = 0; i < it->length; i++) {
         quint8 byte = readByte(&readOfs);
         if((i == 0) && (byte & 0x80))
             tmp = -1;
         tmp = (tmp << 8) | byte;
     }
     *result = tmp;
     return true;
 returnDefault:
     *result = def;
     return false;
 }
readString()
bool SimpleDeserializer::readString (quint32 id, QString * result, const QString & def = QString::null) const
Definition at line 555 of file simpleserializer.cpp.
References m_data, m_elements, and TString.
Referenced by Preferences::deserialize(), LoRaDemodSettings::deserialize(), LocalOutputSettings::deserialize(), LocalInputSettings::deserialize(), RemoteInputSettings::deserialize(), Command::deserialize(), FileInputSettings::deserialize(), KiwiSDRSettings::deserialize(), BladeRF2OutputSettings::deserialize(), RemoteOutputSettings::deserialize(), RemoteSourceSettings::deserialize(), BladeRF1OutputSettings::deserialize(), LocalSourceSettings::deserialize(), LocalSinkSettings::deserialize(), FileSourceSettings::deserialize(), AirspyHFSettings::deserialize(), HackRFOutputSettings::deserialize(), SoapySDROutputSettings::deserialize(), HackRFInputSettings::deserialize(), WFMDemodSettings::deserialize(), BladeRF2InputSettings::deserialize(), AirspySettings::deserialize(), BladeRF1InputSettings::deserialize(), FCDProPlusSettings::deserialize(), PerseusSettings::deserialize(), RTLSDRSettings::deserialize(), RemoteSinkSettings::deserialize(), CWKeyerSettings::deserialize(), XTRXOutputSettings::deserialize(), BFMDemodSettings::deserialize(), SDRPlaySettings::deserialize(), AMDemodSettings::deserialize(), SSBDemodSettings::deserialize(), NFMDemodSettings::deserialize(), PlutoSDROutputSettings::deserialize(), ChannelAnalyzerSettings::deserialize(), FreqTrackerSettings::deserialize(), FreeDVDemodSettings::deserialize(), FCDProSettings::deserialize(), SoapySDRInputSettings::deserialize(), DSDDemodSettings::deserialize(), AMModSettings::deserialize(), WFMModSettings::deserialize(), XTRXInputSettings::deserialize(), Preset::deserialize(), TestSourceSettings::deserialize(), NFMModSettings::deserialize(), LimeSDROutputSettings::deserialize(), UDPSourceSettings::deserialize(), FreeDVModSettings::deserialize(), SSBModSettings::deserialize(), LimeSDRInputSettings::deserialize(), TestMISettings::deserialize(), UDPSinkSettings::deserialize(), ChannelMarker::deserialize(), PlutoSDRInputSettings::deserialize(), ATVModSettings::deserialize(), DATVDemodSettings::deserialize(), and dump().
 {
     Elements::const_iterator it = m_elements.constFind(id);
     if(it == m_elements.constEnd())
         goto returnDefault;
     if(it->type != TString)
         goto returnDefault;
     *result = QString::fromUtf8(m_data.data() + it->ofs, it->length);
     return true;
 returnDefault:
     *result = def;
     return false;
 }
readTag()
bool SimpleDeserializer::readTag (uint * readOfs, uint readEnd, Type * type, quint32 * id, quint32 * length) const private
Definition at line 700 of file simpleserializer.cpp.
References i, and readByte().
Referenced by parseAll().
 {
     quint8 tag = readByte(readOfs);
     *type = (Type)(tag >> 4);
     int idLen = ((tag >> 2) & 0x03) + 1;
     int lengthLen = (tag & 0x03) + 1;
     // make sure we have enough header bytes left
     if(((*readOfs) + idLen + lengthLen) > readEnd)
         return false;
     quint32 tmp = 0;
     for(int i = 0; i < idLen; i++)
         tmp = (tmp << 8) | readByte(readOfs);
     *id = tmp;
     tmp = 0;
     for(int i = 0; i < lengthLen; i++)
         tmp = (tmp << 8) | readByte(readOfs);
     *length = tmp;
     // check if payload fits the buffer
     if(((*readOfs) + (*length)) > readEnd)
         return false;
     else return true;
 }
readU32()
bool SimpleDeserializer::readU32 (quint32 id, quint32 * result, quint32 def = 0) const
Definition at line 350 of file simpleserializer.cpp.
References i, m_elements, readByte(), and TUnsigned32.
Referenced by FileSinkSettings::deserialize(), LocalOutputSettings::deserialize(), LocalInputSettings::deserialize(), RemoteInputSettings::deserialize(), FileInputSettings::deserialize(), KiwiSDRSettings::deserialize(), BladeRF2OutputSettings::deserialize(), RemoteOutputSettings::deserialize(), RemoteSourceSettings::deserialize(), BladeRF1OutputSettings::deserialize(), LocalSinkSettings::deserialize(), LocalSourceSettings::deserialize(), FileSourceSettings::deserialize(), AirspyHFSettings::deserialize(), HackRFOutputSettings::deserialize(), SoapySDROutputSettings::deserialize(), HackRFInputSettings::deserialize(), BladeRF2InputSettings::deserialize(), WFMDemodSettings::deserialize(), AirspySettings::deserialize(), BladeRF1InputSettings::deserialize(), FCDProPlusSettings::deserialize(), PerseusSettings::deserialize(), RTLSDRSettings::deserialize(), CWKeyerSettings::deserialize(), RemoteSinkSettings::deserialize(), XTRXOutputSettings::deserialize(), BFMDemodSettings::deserialize(), AMDemodSettings::deserialize(), SDRPlaySettings::deserialize(), SSBDemodSettings::deserialize(), GLScopeGUI::deserialize(), NFMDemodSettings::deserialize(), PlutoSDROutputSettings::deserialize(), ChannelAnalyzerSettings::deserialize(), FreqTrackerSettings::deserialize(), FreeDVDemodSettings::deserialize(), FCDProSettings::deserialize(), DSDDemodSettings::deserialize(), SoapySDRInputSettings::deserialize(), AMModSettings::deserialize(), WFMModSettings::deserialize(), XTRXInputSettings::deserialize(), TestSourceSettings::deserialize(), NFMModSettings::deserialize(), LimeSDROutputSettings::deserialize(), UDPSourceSettings::deserialize(), FreeDVModSettings::deserialize(), SSBModSettings::deserialize(), TestMISettings::deserialize(), LimeSDRInputSettings::deserialize(), UDPSinkSettings::deserialize(), ChannelMarker::deserialize(), PlutoSDRInputSettings::deserialize(), ATVModSettings::deserialize(), DATVDemodSettings::deserialize(), DoubleBufferSimple< Sample >::deserialize(), ScopeVis::TraceBackBuffer::deserialize(), ScopeVis::TraceBackDiscreteMemory::deserialize(), ScopeVis::deserializeMemory(), dump(), and SampleSourceSerializer::readSerializedData().
 {
     uint readOfs;
     quint32 tmp;
     Elements::const_iterator it = m_elements.constFind(id);
     if(it == m_elements.constEnd())
         goto returnDefault;
     if(it->type != TUnsigned32)
         goto returnDefault;
     if(it->length > 4)
         goto returnDefault;
     readOfs = it->ofs;
     tmp = 0;
     for(uint i = 0; i < it->length; i++)
         tmp = (tmp << 8) | readByte(&readOfs);
     *result = tmp;
     return true;
 returnDefault:
     *result = def;
     return false;
 }
readU64()
bool SimpleDeserializer::readU64 (quint32 id, quint64 * result, quint64 def = 0) const
Definition at line 402 of file simpleserializer.cpp.
References i, m_elements, readByte(), and TUnsigned64.
Referenced by FileSinkSettings::deserialize(), RemoteOutputSettings::deserialize(), HackRFOutputSettings::deserialize(), HackRFInputSettings::deserialize(), PlutoSDROutputSettings::deserialize(), Preset::deserialize(), PlutoSDRInputSettings::deserialize(), dump(), and SampleSourceSerializer::readSerializedData().
 {
     uint readOfs;
     quint64 tmp;
     Elements::const_iterator it = m_elements.constFind(id);
     if(it == m_elements.constEnd())
         goto returnDefault;
     if(it->type != TUnsigned64)
         goto returnDefault;
     if(it->length > 8)
         goto returnDefault;
     readOfs = it->ofs;
     tmp = 0;
     for(uint i = 0; i < it->length; i++)
         tmp = (tmp << 8) | readByte(&readOfs);
     *result = tmp;
     return true;
 returnDefault:
     *result = def;
     return false;
 }
Member Data Documentation
m_data
QByteArray SimpleDeserializer::m_data private
Definition at line 97 of file simpleserializer.h.
Referenced by parseAll(), readBlob(), and readString().
m_elements
Elements SimpleDeserializer::m_elements private
Definition at line 99 of file simpleserializer.h.
Referenced by dump(), parseAll(), readBlob(), readBool(), readDouble(), readFloat(), readReal(), readS32(), readS64(), readString(), readU32(), readU64(), and SimpleDeserializer().
m_valid
bool SimpleDeserializer::m_valid private
Definition at line 98 of file simpleserializer.h.
Referenced by dump(), and SimpleDeserializer().
m_version
quint32 SimpleDeserializer::m_version private
Definition at line 100 of file simpleserializer.h.
Referenced by dump(), and SimpleDeserializer().
The documentation for this class was generated from the following files:
sdrbase/util/simpleserializer.h
sdrbase/util/simpleserializer.cpp