SDRAngel: FCDProPlugin Class Reference
FCDProPlugin Class Reference
#include <fcdproplugin.h>
Public Member Functions
FCDProPlugin (QObject *parent=NULL)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 11 of file fcdproplugin.h.
Constructor & Destructor Documentation
FCDProPlugin()
FCDProPlugin::FCDProPlugin (QObject * parent = NULL) explicit
Definition at line 39 of file fcdproplugin.cpp.
                                           :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSourcePluginInstance()
DeviceSampleSource * FCDProPlugin::createSampleSourcePluginInstance (const QString & sourceId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 113 of file fcdproplugin.cpp.
 {
     if (sourceId == fcd_traits<Pro>::interfaceIID)
     {
         FCDProInput* input = new FCDProInput(deviceAPI);
         return input;
     }
     else
     {
         return 0;
     }
 }
createSampleSourcePluginInstanceGUI()
PluginInstanceGUI * FCDProPlugin::createSampleSourcePluginInstanceGUI (const QString & sourceId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 95 of file fcdproplugin.cpp.
Referenced by enumSampleSources().
 {
     if(sourceId == fcd_traits<Pro>::interfaceIID)
     {
         FCDProGui* gui = new FCDProGui(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSources()
PluginInterface::SamplingDevices FCDProPlugin::enumSampleSources () virtual
Reimplemented from PluginInterface.
Definition at line 54 of file fcdproplugin.cpp.
References arg(), createSampleSourcePluginInstanceGUI(), hid_enumerate(), i, hid_device_info::next, PluginInterface::SamplingDevice::PhysicalDevice, hid_device_info::serial_number, and PluginInterface::SamplingDevice::StreamSingleRx.
 {
     SamplingDevices result;
     int i = 0;
     struct hid_device_info *device_info = hid_enumerate(fcd_traits<Pro>::vendorId, fcd_traits<Pro>::productId);
     while (device_info != 0)
     {
         QString serialNumber = QString::fromWCharArray(device_info->serial_number);
         QString displayedName(QString("%1[%2] %3").arg(fcd_traits<Pro>::displayedName).arg(i).arg(serialNumber));
         result.append(SamplingDevice(displayedName,
                 fcd_traits<Pro>::hardwareID,
                 fcd_traits<Pro>::interfaceIID,
                 serialNumber,
                 i,
                 PluginInterface::SamplingDevice::PhysicalDevice,
                 PluginInterface::SamplingDevice::StreamSingleRx,
                 1,
                 0));
         device_info = device_info->next;
         i++;
     }
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & FCDProPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 44 of file fcdproplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void FCDProPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 49 of file fcdproplugin.cpp.
References PluginAPI::registerSampleSource().
 {
     pluginAPI->registerSampleSource(fcd_traits<Pro>::interfaceIID, this);
 }
Member Data Documentation
m_pluginDescriptor
const PluginDescriptor FCDProPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString(fcd_traits<Pro>::pluginDisplayedName),
    QString(fcd_traits<Pro>::pluginVersion),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 30 of file fcdproplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesource/fcdpro/fcdproplugin.h
plugins/samplesource/fcdpro/fcdproplugin.cpp