SDRAngel: MainWindow::MsgDeleteChannel Class Reference
MainWindow::MsgDeleteChannel Class Reference
Public Member Functions
int getDeviceSetIndex () const
int getChannelIndex () const
bool isTx () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgDeleteChannel * create (int deviceSetIndex, int channelIndex, bool tx)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgDeleteChannel (int deviceSetIndex, int channelIndex, bool tx)
Private Attributes
int m_deviceSetIndex
int m_channelIndex
bool m_tx
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 246 of file mainwindow.h.
Constructor & Destructor Documentation
MsgDeleteChannel()
MainWindow::MsgDeleteChannel::MsgDeleteChannel (int deviceSetIndex, int channelIndex, bool tx) inline private
Definition at line 264 of file mainwindow.h.
                                                                         :
             Message(),
             m_deviceSetIndex(deviceSetIndex),
             m_channelIndex(channelIndex),
             m_tx(tx)
         { }
Member Function Documentation
create()
static MsgDeleteChannel* MainWindow::MsgDeleteChannel::create (int deviceSetIndex, int channelIndex, bool tx) inline static
Definition at line 254 of file mainwindow.h.
Referenced by WebAPIAdapterGUI::devicesetChannelDelete().
         {
             return new MsgDeleteChannel(deviceSetIndex, channelIndex, tx);
         }
getChannelIndex()
int MainWindow::MsgDeleteChannel::getChannelIndex () const inline
Definition at line 251 of file mainwindow.h.
Referenced by MainWindow::handleMessage().
 { return m_channelIndex; }
getDeviceSetIndex()
int MainWindow::MsgDeleteChannel::getDeviceSetIndex () const inline
Definition at line 250 of file mainwindow.h.
Referenced by MainWindow::handleMessage().
 { return m_deviceSetIndex; }
isTx()
bool MainWindow::MsgDeleteChannel::isTx () const inline
Definition at line 252 of file mainwindow.h.
 { return m_tx; }
Member Data Documentation
m_channelIndex
int MainWindow::MsgDeleteChannel::m_channelIndex private
Definition at line 261 of file mainwindow.h.
m_deviceSetIndex
int MainWindow::MsgDeleteChannel::m_deviceSetIndex private
Definition at line 260 of file mainwindow.h.
m_tx
bool MainWindow::MsgDeleteChannel::m_tx private
Definition at line 262 of file mainwindow.h.
The documentation for this class was generated from the following file:
sdrgui/mainwindow.h