SDRAngel: SSBDemod::MsgConfigureSSBDemod Class Reference
SSBDemod::MsgConfigureSSBDemod Class Reference
#include <ssbdemod.h>
Public Member Functions
const SSBDemodSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureSSBDemod * create (const SSBDemodSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureSSBDemod (const SSBDemodSettings &settings, bool force)
Private Attributes
SSBDemodSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 51 of file ssbdemod.h.
Constructor & Destructor Documentation
MsgConfigureSSBDemod()
SSBDemod::MsgConfigureSSBDemod::MsgConfigureSSBDemod (const SSBDemodSettings & settings, bool force) inline private
Definition at line 67 of file ssbdemod.h.
Referenced by create().
                                                                            :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureSSBDemod* SSBDemod::MsgConfigureSSBDemod::create (const SSBDemodSettings & settings, bool force) inline static
Definition at line 58 of file ssbdemod.h.
References MsgConfigureSSBDemod().
Referenced by SSBDemodGUI::applySettings(), SSBDemod::deserialize(), and SSBDemod::webapiSettingsPutPatch().
         {
             return new MsgConfigureSSBDemod(settings, force);
         }
getForce()
bool SSBDemod::MsgConfigureSSBDemod::getForce () const inline
Definition at line 56 of file ssbdemod.h.
References m_force.
Referenced by SSBDemod::handleMessage().
 { return m_force; }
getSettings()
const SSBDemodSettings& SSBDemod::MsgConfigureSSBDemod::getSettings () const inline
Definition at line 55 of file ssbdemod.h.
References m_settings.
Referenced by SSBDemodGUI::handleMessage(), and SSBDemod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool SSBDemod::MsgConfigureSSBDemod::m_force private
Definition at line 65 of file ssbdemod.h.
Referenced by getForce().
m_settings
SSBDemodSettings SSBDemod::MsgConfigureSSBDemod::m_settings private
Definition at line 64 of file ssbdemod.h.
Referenced by SSBDemod::getCenterFrequency(), getSettings(), SSBDemod::getStreamCenterFrequency(), and SSBDemod::getTitle().
The documentation for this class was generated from the following file:
plugins/channelrx/demodssb/ssbdemod.h