SDRAngel: NFMDemod::MsgReportCTCSSFreq Class Reference
NFMDemod::MsgReportCTCSSFreq Class Reference
#include <nfmdemod.h>
Public Member Functions
Real getFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportCTCSSFreq * create (Real freq)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportCTCSSFreq (Real freq)
Private Attributes
Real m_freq
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 99 of file nfmdemod.h.
Constructor & Destructor Documentation
MsgReportCTCSSFreq()
NFMDemod::MsgReportCTCSSFreq::MsgReportCTCSSFreq (Real freq) inline private
Definition at line 113 of file nfmdemod.h.
References NFMDemod::NFMDemod(), and NFMDemod::~NFMDemod().
                                       :
             Message(),
             m_freq(freq)
         { }
Member Function Documentation
create()
static MsgReportCTCSSFreq* NFMDemod::MsgReportCTCSSFreq::create (Real freq) inline static
Definition at line 105 of file nfmdemod.h.
Referenced by NFMDemod::processOneSample().
         {
             return new MsgReportCTCSSFreq(freq);
         }
getFrequency()
Real NFMDemod::MsgReportCTCSSFreq::getFrequency () const inline
Definition at line 103 of file nfmdemod.h.
Referenced by NFMDemodGUI::handleMessage().
 { return m_freq; }
Member Data Documentation
m_freq
Real NFMDemod::MsgReportCTCSSFreq::m_freq private
Definition at line 111 of file nfmdemod.h.
The documentation for this class was generated from the following file:
plugins/channelrx/demodnfm/nfmdemod.h