SDRAngel: ATVMod::MsgConfigureChannelizer Class Reference
ATVMod::MsgConfigureChannelizer Class Reference
#include <atvmod.h>
Public Member Functions
int getCenterFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (int centerFrequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (int centerFrequency)
Private Attributes
int m_centerFrequency
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 76 of file atvmod.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
ATVMod::MsgConfigureChannelizer::MsgConfigureChannelizer (int centerFrequency) inline private
Definition at line 90 of file atvmod.h.
                                                      :
             Message(),
             m_centerFrequency(centerFrequency)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* ATVMod::MsgConfigureChannelizer::create (int centerFrequency) inline static
Definition at line 82 of file atvmod.h.
Referenced by ATVModGUI::applySettings(), and ATVMod::webapiSettingsPutPatch().
         {
             return new MsgConfigureChannelizer(centerFrequency);
         }
getCenterFrequency()
int ATVMod::MsgConfigureChannelizer::getCenterFrequency () const inline
Definition at line 80 of file atvmod.h.
Referenced by ATVMod::handleMessage().
 { return m_centerFrequency; }
Member Data Documentation
m_centerFrequency
int ATVMod::MsgConfigureChannelizer::m_centerFrequency private
Definition at line 88 of file atvmod.h.
The documentation for this class was generated from the following file:
plugins/channeltx/modatv/atvmod.h