SDRAngel: MainBench Class Reference
MainBench Class Reference
#include <mainbench.h>
Inherits QObject.
Public Slots
void run ()
Signals
void finished ()
Public Member Functions
MainBench (qtwebapp::LoggerWithFile *logger, const ParserBench &parser, QObject *parent=0)
~MainBench ()
Private Member Functions
void testDecimateII (ParserBench::TestType testType=ParserBench::TestDecimatorsII)
void testDecimateIF ()
void testDecimateFI ()
void testDecimateFF ()
void testAMBE ()
void decimateII (const qint16 *buf, int len)
void decimateInfII (const qint16 *buf, int len)
void decimateSupII (const qint16 *buf, int len)
void decimateIF (const qint16 *buf, int len)
void decimateFI (const float *buf, int len)
void decimateFF (const float *buf, int len)
void printResults (const QString &prefix, qint64 nsecs)
Private Attributes
qtwebapp::LoggerWithFile * m_logger
const ParserBench & m_parser
std::mt19937 m_generator
std::uniform_real_distribution< float > m_uniform_distribution_f
std::uniform_int_distribution< qint16 > m_uniform_distribution_s16
Decimators< qint32, qint16, SDR_RX_SAMP_SZ, 12 > m_decimatorsII
DecimatorsIF< qint16, 12 > m_decimatorsIF
DecimatorsFI m_decimatorsFI
DecimatorsFF m_decimatorsFF
SampleVector m_convertBuffer
FSampleVector m_convertBufferF
Static Private Attributes
static MainBench * m_instance = 0
Detailed Description
Definition at line 37 of file mainbench.h.
Constructor & Destructor Documentation
MainBench()
MainBench::MainBench (qtwebapp::LoggerWithFile * logger, const ParserBench & parser, QObject * parent = 0) explicit
Definition at line 29 of file mainbench.cpp.
References m_instance.
                                                                                                :
     QObject(parent),
     m_logger(logger),
     m_parser(parser),
     m_uniform_distribution_f(-1.0, 1.0),
     m_uniform_distribution_s16(-2048, 2047)
 {
     qDebug() << "MainBench::MainBench: start";
     m_instance = this;
     qDebug() << "MainBench::MainBench: end";
 }
~MainBench()
MainBench::~MainBench ()
Definition at line 41 of file mainbench.cpp.
 {}
Member Function Documentation
decimateFF()
void MainBench::decimateFF (const float * buf, int len) private
Definition at line 370 of file mainbench.cpp.
References DecimatorsFF::decimate1(), DecimatorsFF::decimate16_cen(), DecimatorsFF::decimate2_cen(), DecimatorsFF::decimate32_cen(), DecimatorsFF::decimate4_cen(), DecimatorsFF::decimate64_cen(), DecimatorsFF::decimate8_cen(), ParserBench::getLog2Factor(), m_convertBufferF, m_decimatorsFF, and m_parser.
Referenced by testDecimateFF().
 {
     FSampleVector::iterator it = m_convertBufferF.begin();
     switch (m_parser.getLog2Factor())
     {
     case 0:
         m_decimatorsFF.decimate1(&it, buf, len);
         break;
     case 1:
         m_decimatorsFF.decimate2_cen(&it, buf, len);
         break;
     case 2:
         m_decimatorsFF.decimate4_cen(&it, buf, len);
         break;
     case 3:
         m_decimatorsFF.decimate8_cen(&it, buf, len);
         break;
     case 4:
         m_decimatorsFF.decimate16_cen(&it, buf, len);
         break;
     case 5:
         m_decimatorsFF.decimate32_cen(&it, buf, len);
         break;
     case 6:
         m_decimatorsFF.decimate64_cen(&it, buf, len);
         break;
     default:
         break;
     }
 }
decimateFI()
void MainBench::decimateFI (const float * buf, int len) private
Definition at line 338 of file mainbench.cpp.
References DecimatorsFI::decimate1(), DecimatorsFI::decimate16_cen(), DecimatorsFI::decimate2_cen(), DecimatorsFI::decimate32_cen(), DecimatorsFI::decimate4_cen(), DecimatorsFI::decimate64_cen(), DecimatorsFI::decimate8_cen(), ParserBench::getLog2Factor(), m_convertBuffer, m_decimatorsFI, and m_parser.
Referenced by testDecimateFI().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     switch (m_parser.getLog2Factor())
     {
     case 0:
         m_decimatorsFI.decimate1(&it, buf, len);
         break;
     case 1:
         m_decimatorsFI.decimate2_cen(&it, buf, len);
         break;
     case 2:
         m_decimatorsFI.decimate4_cen(&it, buf, len);
         break;
     case 3:
         m_decimatorsFI.decimate8_cen(&it, buf, len);
         break;
     case 4:
         m_decimatorsFI.decimate16_cen(&it, buf, len);
         break;
     case 5:
         m_decimatorsFI.decimate32_cen(&it, buf, len);
         break;
     case 6:
         m_decimatorsFI.decimate64_cen(&it, buf, len);
         break;
     default:
         break;
     }
 }
decimateIF()
void MainBench::decimateIF (const qint16 * buf, int len) private
Definition at line 306 of file mainbench.cpp.
References DecimatorsIF< T, InputBits >::decimate1(), DecimatorsIF< T, InputBits >::decimate16_cen(), DecimatorsIF< T, InputBits >::decimate2_cen(), DecimatorsIF< T, InputBits >::decimate32_cen(), DecimatorsIF< T, InputBits >::decimate4_cen(), DecimatorsIF< T, InputBits >::decimate64_cen(), DecimatorsIF< T, InputBits >::decimate8_cen(), ParserBench::getLog2Factor(), m_convertBufferF, m_decimatorsIF, and m_parser.
Referenced by testDecimateIF().
 {
     FSampleVector::iterator it = m_convertBufferF.begin();
     switch (m_parser.getLog2Factor())
     {
     case 0:
         m_decimatorsIF.decimate1(&it, buf, len);
         break;
     case 1:
         m_decimatorsIF.decimate2_cen(&it, buf, len);
         break;
     case 2:
         m_decimatorsIF.decimate4_cen(&it, buf, len);
         break;
     case 3:
         m_decimatorsIF.decimate8_cen(&it, buf, len);
         break;
     case 4:
         m_decimatorsIF.decimate16_cen(&it, buf, len);
         break;
     case 5:
         m_decimatorsIF.decimate32_cen(&it, buf, len);
         break;
     case 6:
         m_decimatorsIF.decimate64_cen(&it, buf, len);
         break;
     default:
         break;
     }
 }
decimateII()
void MainBench::decimateII (const qint16 * buf, int len) private
Definition at line 210 of file mainbench.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), ParserBench::getLog2Factor(), m_convertBuffer, m_decimatorsII, and m_parser.
Referenced by testDecimateII().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     switch (m_parser.getLog2Factor())
     {
     case 0:
         m_decimatorsII.decimate1(&it, buf, len);
         break;
     case 1:
         m_decimatorsII.decimate2_cen(&it, buf, len);
         break;
     case 2:
         m_decimatorsII.decimate4_cen(&it, buf, len);
         break;
     case 3:
         m_decimatorsII.decimate8_cen(&it, buf, len);
         break;
     case 4:
         m_decimatorsII.decimate16_cen(&it, buf, len);
         break;
     case 5:
         m_decimatorsII.decimate32_cen(&it, buf, len);
         break;
     case 6:
         m_decimatorsII.decimate64_cen(&it, buf, len);
         break;
     default:
         break;
     }
 }
decimateInfII()
void MainBench::decimateInfII (const qint16 * buf, int len) private
Definition at line 242 of file mainbench.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf(), ParserBench::getLog2Factor(), m_convertBuffer, m_decimatorsII, and m_parser.
Referenced by testDecimateII().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     switch (m_parser.getLog2Factor())
     {
     case 0:
         m_decimatorsII.decimate1(&it, buf, len);
         break;
     case 1:
         m_decimatorsII.decimate2_inf(&it, buf, len);
         break;
     case 2:
         m_decimatorsII.decimate4_inf(&it, buf, len);
         break;
     case 3:
         m_decimatorsII.decimate8_inf(&it, buf, len);
         break;
     case 4:
         m_decimatorsII.decimate16_inf(&it, buf, len);
         break;
     case 5:
         m_decimatorsII.decimate32_inf(&it, buf, len);
         break;
     case 6:
         m_decimatorsII.decimate64_inf(&it, buf, len);
         break;
     default:
         break;
     }
 }
decimateSupII()
void MainBench::decimateSupII (const qint16 * buf, int len) private
Definition at line 274 of file mainbench.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup(), ParserBench::getLog2Factor(), m_convertBuffer, m_decimatorsII, and m_parser.
Referenced by testDecimateII().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     switch (m_parser.getLog2Factor())
     {
     case 0:
         m_decimatorsII.decimate1(&it, buf, len);
         break;
     case 1:
         m_decimatorsII.decimate2_sup(&it, buf, len);
         break;
     case 2:
         m_decimatorsII.decimate4_sup(&it, buf, len);
         break;
     case 3:
         m_decimatorsII.decimate8_sup(&it, buf, len);
         break;
     case 4:
         m_decimatorsII.decimate16_sup(&it, buf, len);
         break;
     case 5:
         m_decimatorsII.decimate32_sup(&it, buf, len);
         break;
     case 6:
         m_decimatorsII.decimate64_sup(&it, buf, len);
         break;
     default:
         break;
     }
 }
finished
void MainBench::finished () signal
Referenced by run().
printResults()
void MainBench::printResults (const QString & prefix, qint64 nsecs) private
Definition at line 402 of file mainbench.cpp.
References ParserBench::getNbSamples(), ParserBench::getRepetition(), and m_parser.
Referenced by testDecimateFF(), testDecimateFI(), testDecimateIF(), and testDecimateII().
 {
     double ratekSs = (m_parser.getNbSamples()*m_parser.getRepetition() / (double) nsecs) * 1e6;
     QDebug info = qInfo();
     info.noquote();
     info << tr("%1: ran test in %L2 ns - sample rate: %3 kS/s").arg(prefix).arg(nsecs).arg(ratekSs);
 }
run
void MainBench::run () slot
Definition at line 44 of file mainbench.cpp.
References finished(), ParserBench::getLog2Factor(), ParserBench::getNbSamples(), ParserBench::getRepetition(), ParserBench::getTestStr(), ParserBench::getTestType(), m_parser, ParserBench::TestAMBE, testAMBE(), testDecimateFF(), testDecimateFI(), testDecimateIF(), testDecimateII(), ParserBench::TestDecimatorsFF, ParserBench::TestDecimatorsFI, ParserBench::TestDecimatorsIF, ParserBench::TestDecimatorsII, ParserBench::TestDecimatorsInfII, and ParserBench::TestDecimatorsSupII.
 {
     qDebug() << "MainBench::run: parameters:"
         << " testStr: " << m_parser.getTestStr()
         << " testType: " << (int) m_parser.getTestType()
         << " nsamples: " << m_parser.getNbSamples()
         << " repet: " << m_parser.getRepetition()
         << " log2f: " << m_parser.getLog2Factor();
     if (m_parser.getTestType() == ParserBench::TestDecimatorsII) {
         testDecimateII();
     } else if (m_parser.getTestType() == ParserBench::TestDecimatorsInfII) {
         testDecimateII(ParserBench::TestDecimatorsInfII);
     } else if (m_parser.getTestType() == ParserBench::TestDecimatorsSupII) {
         testDecimateII(ParserBench::TestDecimatorsSupII);
     } else if (m_parser.getTestType() == ParserBench::TestDecimatorsIF) {
         testDecimateIF();
     } else if (m_parser.getTestType() == ParserBench::TestDecimatorsFI) {
         testDecimateFI();
     } else if (m_parser.getTestType() == ParserBench::TestDecimatorsFF) {
         testDecimateFF();
     } else if (m_parser.getTestType() == ParserBench::TestAMBE) {
         testAMBE();
     } else {
         qDebug() << "MainBench::run: unknown test type: " << m_parser.getTestType();
     }
     emit finished();
 }
testAMBE()
void MainBench::testAMBE () private
Definition at line 198 of file mainbench.cpp.
References AMBEEngine::scan().
Referenced by run().
 {
     qDebug() << "MainBench::testAMBE";
     AMBEEngine ambeEngine;
     std::vector<QString> ambeDevices;
     ambeEngine.scan(ambeDevices);
     for (std::vector<QString>::const_iterator it = ambeDevices.begin(); it != ambeDevices.end(); ++it) {
         qDebug("MainBench::testAMBE: detected AMBE device %s", qPrintable(*it));
     }
 }
testDecimateFF()
void MainBench::testDecimateFF () private
Definition at line 171 of file mainbench.cpp.
References decimateFF(), ParserBench::getLog2Factor(), ParserBench::getNbSamples(), ParserBench::getRepetition(), i, m_convertBufferF, m_generator, m_parser, m_uniform_distribution_f, and printResults().
Referenced by run().
 {
     QElapsedTimer timer;
     qint64 nsecs = 0;
     qDebug() << "MainBench::testDecimateFF: create test data";
     float *buf = new float[m_parser.getNbSamples()*2];
     m_convertBufferF.resize(m_parser.getNbSamples()/(1<<m_parser.getLog2Factor()));
     auto my_rand = std::bind(m_uniform_distribution_f, m_generator);
     std::generate(buf, buf + m_parser.getNbSamples()*2 - 1, my_rand); // make sure data is in [-1.0..1.0] range
     qDebug() << "MainBench::testDecimateFF: run test";
     for (uint32_t i = 0; i < m_parser.getRepetition(); i++)
     {
         timer.start();
         decimateFF(buf, m_parser.getNbSamples()*2);
         nsecs += timer.nsecsElapsed();
     }
     printResults("MainBench::testDecimateFF", nsecs);
     qDebug() << "MainBench::testDecimateFF: cleanup test data";
     delete[] buf;
 }
testDecimateFI()
void MainBench::testDecimateFI () private
Definition at line 144 of file mainbench.cpp.
References decimateFI(), ParserBench::getLog2Factor(), ParserBench::getNbSamples(), ParserBench::getRepetition(), i, m_convertBuffer, m_generator, m_parser, m_uniform_distribution_f, and printResults().
Referenced by run().
 {
     QElapsedTimer timer;
     qint64 nsecs = 0;
     qDebug() << "MainBench::testDecimateFI: create test data";
     float *buf = new float[m_parser.getNbSamples()*2];
     m_convertBuffer.resize(m_parser.getNbSamples()/(1<<m_parser.getLog2Factor()));
     auto my_rand = std::bind(m_uniform_distribution_f, m_generator);
     std::generate(buf, buf + m_parser.getNbSamples()*2 - 1, my_rand); // make sure data is in [-1.0..1.0] range
     qDebug() << "MainBench::testDecimateFI: run test";
     for (uint32_t i = 0; i < m_parser.getRepetition(); i++)
     {
         timer.start();
         decimateFI(buf, m_parser.getNbSamples()*2);
         nsecs += timer.nsecsElapsed();
     }
     printResults("MainBench::testDecimateFI", nsecs);
     qDebug() << "MainBench::testDecimateFI: cleanup test data";
     delete[] buf;
 }
testDecimateIF()
void MainBench::testDecimateIF () private
Definition at line 117 of file mainbench.cpp.
References decimateIF(), ParserBench::getLog2Factor(), ParserBench::getNbSamples(), ParserBench::getRepetition(), i, m_convertBufferF, m_generator, m_parser, m_uniform_distribution_s16, and printResults().
Referenced by run().
 {
     QElapsedTimer timer;
     qint64 nsecs = 0;
     qDebug() << "MainBench::testDecimateIF: create test data";
     qint16 *buf = new qint16[m_parser.getNbSamples()*2];
     m_convertBufferF.resize(m_parser.getNbSamples()/(1<<m_parser.getLog2Factor()));
     auto my_rand = std::bind(m_uniform_distribution_s16, m_generator);
     std::generate(buf, buf + m_parser.getNbSamples()*2 - 1, my_rand);
     qDebug() << "MainBench::testDecimateIF: run test";
     for (uint32_t i = 0; i < m_parser.getRepetition(); i++)
     {
         timer.start();
         decimateIF(buf, m_parser.getNbSamples()*2);
         nsecs += timer.nsecsElapsed();
     }
     printResults("MainBench::testDecimateIF", nsecs);
     qDebug() << "MainBench::testDecimateIF: cleanup test data";
     delete[] buf;
 }
testDecimateII()
void MainBench::testDecimateII (ParserBench::TestType testType = ParserBench::TestDecimatorsII) private
Definition at line 74 of file mainbench.cpp.
References decimateII(), decimateInfII(), decimateSupII(), ParserBench::getLog2Factor(), ParserBench::getNbSamples(), ParserBench::getRepetition(), i, m_convertBuffer, m_generator, m_parser, m_uniform_distribution_s16, printResults(), ParserBench::TestDecimatorsII, ParserBench::TestDecimatorsInfII, and ParserBench::TestDecimatorsSupII.
Referenced by run().
 {
     QElapsedTimer timer;
     qint64 nsecs = 0;
     qDebug() << "MainBench::testDecimateII: create test data";
     qint16 *buf = new qint16[m_parser.getNbSamples()*2];
     m_convertBuffer.resize(m_parser.getNbSamples()/(1<<m_parser.getLog2Factor()));
     auto my_rand = std::bind(m_uniform_distribution_s16, m_generator);
     std::generate(buf, buf + m_parser.getNbSamples()*2 - 1, my_rand);
     qDebug() << "MainBench::testDecimateII: run test";
     for (uint32_t i = 0; i < m_parser.getRepetition(); i++)
     {
         switch (testType)
         {
         case ParserBench::TestDecimatorsInfII:
             timer.start();
             decimateInfII(buf, m_parser.getNbSamples()*2);
             nsecs += timer.nsecsElapsed();
             break;
         case ParserBench::TestDecimatorsSupII:
             timer.start();
             decimateSupII(buf, m_parser.getNbSamples()*2);
             nsecs += timer.nsecsElapsed();
             break;
         case ParserBench::TestDecimatorsII:
         default:
             timer.start();
             decimateII(buf, m_parser.getNbSamples()*2);
             nsecs += timer.nsecsElapsed();
             break;
         }
     }
     printResults("MainBench::testDecimateII", nsecs);
     qDebug() << "MainBench::testDecimateII: cleanup test data";
     delete[] buf;
 }
Member Data Documentation
m_convertBuffer
SampleVector MainBench::m_convertBuffer private
Definition at line 76 of file mainbench.h.
Referenced by decimateFI(), decimateII(), decimateInfII(), decimateSupII(), testDecimateFI(), and testDecimateII().
m_convertBufferF
FSampleVector MainBench::m_convertBufferF private
Definition at line 77 of file mainbench.h.
Referenced by decimateFF(), decimateIF(), testDecimateFF(), and testDecimateIF().
m_decimatorsFF
DecimatorsFF MainBench::m_decimatorsFF private
Definition at line 74 of file mainbench.h.
Referenced by decimateFF().
m_decimatorsFI
DecimatorsFI MainBench::m_decimatorsFI private
Definition at line 73 of file mainbench.h.
Referenced by decimateFI().
m_decimatorsIF
DecimatorsIF<qint16, 12> MainBench::m_decimatorsIF private
Definition at line 72 of file mainbench.h.
Referenced by decimateIF().
m_decimatorsII
Decimators<qint32, qint16, SDR_RX_SAMP_SZ, 12> MainBench::m_decimatorsII private
Definition at line 71 of file mainbench.h.
Referenced by decimateII(), decimateInfII(), and decimateSupII().
m_generator
std::mt19937 MainBench::m_generator private
Definition at line 67 of file mainbench.h.
Referenced by testDecimateFF(), testDecimateFI(), testDecimateIF(), and testDecimateII().
m_instance
MainBench * MainBench::m_instance = 0 static private
Definition at line 64 of file mainbench.h.
Referenced by MainBench().
m_logger
qtwebapp::LoggerWithFile* MainBench::m_logger private
Definition at line 65 of file mainbench.h.
m_parser
const ParserBench& MainBench::m_parser private
Definition at line 66 of file mainbench.h.
Referenced by decimateFF(), decimateFI(), decimateIF(), decimateII(), decimateInfII(), decimateSupII(), printResults(), run(), testDecimateFF(), testDecimateFI(), testDecimateIF(), and testDecimateII().
m_uniform_distribution_f
std::uniform_real_distribution<float> MainBench::m_uniform_distribution_f private
Definition at line 68 of file mainbench.h.
Referenced by testDecimateFF(), and testDecimateFI().
m_uniform_distribution_s16
std::uniform_int_distribution<qint16> MainBench::m_uniform_distribution_s16 private
Definition at line 69 of file mainbench.h.
Referenced by testDecimateIF(), and testDecimateII().
The documentation for this class was generated from the following files:
sdrbench/mainbench.h
sdrbench/mainbench.cpp