SDRAngel: CommandKeyReceiver Class Reference
CommandKeyReceiver Class Reference
#include <commandkeyreceiver.h>
Inherits QObject.
Signals
void capturedKey (Qt::Key key, Qt::KeyboardModifiers keyModifiers, bool release)
Public Member Functions
CommandKeyReceiver ()
void setRelease (bool release)
void setPass (bool release)
Protected Member Functions
bool eventFilter (QObject *obj, QEvent *event)
Private Member Functions
void keyEventHandler (QKeyEvent *e, Qt::Key &key, Qt::KeyboardModifiers &keyModifiers)
bool isComposeKey (Qt::Key key)
Private Attributes
bool m_release
check release events
bool m_pass
do not block events just tap them
Static Private Attributes
static const std::vector< Qt::Key > m_composeKeys = {Qt::Key_Shift, Qt::Key_Control, Qt::Key_Meta, Qt::Key_Alt, Qt::Key_AltGr}
Detailed Description
Definition at line 27 of file commandkeyreceiver.h.
Constructor & Destructor Documentation
CommandKeyReceiver()
CommandKeyReceiver::CommandKeyReceiver ()
Definition at line 24 of file commandkeyreceiver.cpp.
                                        :
     m_release(false),
     m_pass(true)
 {
 }
Member Function Documentation
capturedKey
void CommandKeyReceiver::capturedKey (Qt::Key key, Qt::KeyboardModifiers keyModifiers, bool release) signal
Referenced by eventFilter().
eventFilter()
bool CommandKeyReceiver::eventFilter (QObject * obj, QEvent * event) protected
Definition at line 30 of file commandkeyreceiver.cpp.
References capturedKey(), isComposeKey(), keyEventHandler(), m_pass, and m_release.
 {
     if (event->type() == QEvent::KeyPress)
     {
         QKeyEvent* keyEvent = static_cast<QKeyEvent*>(event);
         if ((!keyEvent->isAutoRepeat()) && (!isComposeKey(static_cast<Qt::Key>(keyEvent->key()))))
         {
 //            qDebug("KeyReceiver::eventFilter: KeyPress");
             Qt::Key key;
             Qt::KeyboardModifiers keyModifiers;
             keyEventHandler(keyEvent, key, keyModifiers);
             emit capturedKey(key, keyModifiers, false);
             if (!m_pass) { // do not pass the event
                 return true;
             }
         }
     }
     else if (m_release && (event->type()==QEvent::KeyRelease))
     {
         QKeyEvent* keyEvent = static_cast<QKeyEvent*>(event);
         if ((!keyEvent->isAutoRepeat()) && (!isComposeKey(static_cast<Qt::Key>(keyEvent->key()))))
         {
 //            qDebug("KeyReceiver::eventFilter: KeyRelease");
             Qt::Key key;
             Qt::KeyboardModifiers keyModifiers;
             keyEventHandler(keyEvent, key, keyModifiers);
             emit capturedKey(key, keyModifiers, true);
             if (!m_pass) { // do not pass the event
                 return true;
             }
         }
     }
     return QObject::eventFilter(obj, event); // pass the event on
 }
isComposeKey()
bool CommandKeyReceiver::isComposeKey (Qt::Key key) private
Definition at line 84 of file commandkeyreceiver.cpp.
References m_composeKeys.
Referenced by eventFilter().
 {
     auto it = std::find(m_composeKeys.begin(), m_composeKeys.end(), key);
     return it != m_composeKeys.end();
 }
keyEventHandler()
void CommandKeyReceiver::keyEventHandler (QKeyEvent * e, Qt::Key & key, Qt::KeyboardModifiers & keyModifiers) private
Definition at line 70 of file commandkeyreceiver.cpp.
Referenced by eventFilter().
 {
     key = static_cast<Qt::Key>(e->key());
     if (e->modifiers())
     {
         keyModifiers = e->modifiers();
     }
     else
     {
         keyModifiers = Qt::NoModifier;
     }
 }
setPass()
void CommandKeyReceiver::setPass (bool release) inline
Definition at line 34 of file commandkeyreceiver.h.
 { m_release = release; }
setRelease()
void CommandKeyReceiver::setRelease (bool release) inline
Definition at line 33 of file commandkeyreceiver.h.
Referenced by CWKeyerGUI::commandKeyPressed(), CWKeyerGUI::CWKeyerGUI(), MainWindow::MainWindow(), and CWKeyerGUI::on_keyDashCapture_toggled().
 { m_release = release; }
Member Data Documentation
m_composeKeys
const std::vector< Qt::Key > CommandKeyReceiver::m_composeKeys = {Qt::Key_Shift, Qt::Key_Control, Qt::Key_Meta, Qt::Key_Alt, Qt::Key_AltGr} static private
Definition at line 46 of file commandkeyreceiver.h.
Referenced by isComposeKey().
m_pass
bool CommandKeyReceiver::m_pass private
do not block events just tap them
Definition at line 41 of file commandkeyreceiver.h.
Referenced by eventFilter().
m_release
bool CommandKeyReceiver::m_release private
check release events
Definition at line 40 of file commandkeyreceiver.h.
Referenced by eventFilter().
The documentation for this class was generated from the following files:
sdrgui/gui/commandkeyreceiver.h
sdrgui/gui/commandkeyreceiver.cpp