SDRAngel: KiwiSDRInput Class Reference
KiwiSDRInput Class Reference
#include <kiwisdrinput.h>
Classes
class MsgConfigureKiwiSDR
class MsgFileRecord
class MsgSetStatus
class MsgStartStop
Signals
void startWorker ()
void stopWorker ()
void setWorkerCenterFrequency (quint64 centerFrequency)
void setWorkerServerAddress (QString serverAddress)
void setWorkerGain (quint32 gain, bool useAGC)
Public Member Functions
KiwiSDRInput (DeviceAPI *deviceAPI)
virtual ~KiwiSDRInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Private Slots
void setWorkerStatus (int status)
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
int getStatus () const
bool applySettings (const KiwiSDRSettings &settings, bool force)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const KiwiSDRSettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const KiwiSDRSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
FileRecord * m_fileSink
File sink to record device I/Q output.
QMutex m_mutex
KiwiSDRSettings m_settings
KiwiSDRWorker * m_kiwiSDRWorker
QThread m_kiwiSDRWorkerThread
QString m_deviceDescription
bool m_running
const QTimer & m_masterTimer
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 37 of file kiwisdrinput.h.
Constructor & Destructor Documentation
KiwiSDRInput()
KiwiSDRInput::KiwiSDRInput (DeviceAPI * deviceAPI)
Definition at line 45 of file kiwisdrinput.cpp.
References start().
Referenced by KiwiSDRInput::MsgSetStatus::MsgSetStatus().
                                                :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_kiwiSDRWorker(nullptr),
     m_deviceDescription(),
     m_running(false),
     m_masterTimer(deviceAPI->getMasterTimer())
 {
     m_kiwiSDRWorkerThread.start();
     m_fileSink = new FileRecord();
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     if (!m_sampleFifo.setSize(getSampleRate() * 2)) {
         qCritical("KiwiSDRInput::KiwiSDRInput: Could not allocate SampleFifo");
     }
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~KiwiSDRInput()
KiwiSDRInput::~KiwiSDRInput () virtual
Definition at line 67 of file kiwisdrinput.cpp.
References m_deviceAPI, m_fileSink, m_kiwiSDRWorkerThread, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::removeAncillarySink(), and stop().
Referenced by KiwiSDRInput::MsgSetStatus::MsgSetStatus().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     m_kiwiSDRWorkerThread.quit();
     m_kiwiSDRWorkerThread.wait();
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
 }
Member Function Documentation
applySettings()
bool KiwiSDRInput::applySettings (const KiwiSDRSettings & settings, bool force) private
Definition at line 270 of file kiwisdrinput.cpp.
References DeviceAPI::configureCorrections(), DeviceAPI::getDeviceEngineInputMessageQueue(), getSampleRate(), FileRecord::handleMessage(), KiwiSDRSettings::m_centerFrequency, KiwiSDRSettings::m_dcBlock, m_deviceAPI, KiwiSDRSettings::m_fileRecordName, m_fileSink, KiwiSDRSettings::m_gain, KiwiSDRSettings::m_reverseAPIAddress, KiwiSDRSettings::m_reverseAPIDeviceIndex, KiwiSDRSettings::m_reverseAPIPort, KiwiSDRSettings::m_serverAddress, m_settings, KiwiSDRSettings::m_useAGC, KiwiSDRSettings::m_useReverseAPI, MessageQueue::push(), setWorkerCenterFrequency(), setWorkerGain(), setWorkerServerAddress(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     qDebug() << "KiwiSDRInput::applySettings: "
         << " m_serverAddress: " << settings.m_serverAddress
         << " m_centerFrequency: " << settings.m_centerFrequency
         << " m_gain: " << settings.m_gain
         << " m_useAGC: " << settings.m_useAGC
         << " m_fileRecordName: " << settings.m_fileRecordName
         << " m_useAGC: " << settings.m_useAGC
         << " m_useReverseAPI: " << settings.m_useReverseAPI
         << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
         << " m_reverseAPIPort: " << settings.m_reverseAPIPort
         << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex;
     QList<QString> reverseAPIKeys;
     if (m_settings.m_serverAddress != settings.m_serverAddress || force)
     {
         reverseAPIKeys.append("serverAddress");
         emit setWorkerServerAddress(settings.m_serverAddress);
     }
     if (m_settings.m_gain != settings.m_gain || force) {
         reverseAPIKeys.append("gain");
     }
     if (m_settings.m_useAGC != settings.m_useAGC || force) {
         reverseAPIKeys.append("useAGC");
     }
     if (m_settings.m_gain != settings.m_gain ||
         m_settings.m_useAGC != settings.m_useAGC || force)
     {
         emit setWorkerGain(settings.m_gain, settings.m_useAGC);
     }
     if (m_settings.m_dcBlock != settings.m_dcBlock)
     {
         reverseAPIKeys.append("dcBlock");
         m_deviceAPI->configureCorrections(settings.m_dcBlock, false);
     }
     if (m_settings.m_centerFrequency != settings.m_centerFrequency || force)
     {
         reverseAPIKeys.append("centerFrequency");
         emit setWorkerCenterFrequency(settings.m_centerFrequency);
         DSPSignalNotification *notif = new DSPSignalNotification(
             getSampleRate(), settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     if (settings.m_useReverseAPI)
     {
         qDebug("KiwiSDRInput::applySettings: call webapiReverseSendSettings");
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     return true;
 }
deserialize()
bool KiwiSDRInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 135 of file kiwisdrinput.cpp.
References KiwiSDRInput::MsgConfigureKiwiSDR::create(), KiwiSDRSettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and KiwiSDRSettings::resetToDefaults().
Referenced by KiwiSDRInput::MsgSetStatus::MsgSetStatus().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureKiwiSDR* message = MsgConfigureKiwiSDR::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureKiwiSDR* messageToGUI = MsgConfigureKiwiSDR::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void KiwiSDRInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 83 of file kiwisdrinput.cpp.
Referenced by KiwiSDRInput::MsgSetStatus::MsgSetStatus().
 {
     delete this;
 }
getCenterFrequency()
quint64 KiwiSDRInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 167 of file kiwisdrinput.cpp.
References KiwiSDRSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & KiwiSDRInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 157 of file kiwisdrinput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getSampleRate()
int KiwiSDRInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 162 of file kiwisdrinput.cpp.
Referenced by applySettings(), and setMessageQueueToGUI().
 {
     return 12000;
 }
getStatus()
int KiwiSDRInput::getStatus () const private
Definition at line 261 of file kiwisdrinput.cpp.
References KiwiSDRWorker::getStatus(), and m_kiwiSDRWorker.
Referenced by webapiFormatDeviceReport().
 {
     if (m_kiwiSDRWorker) {
         return m_kiwiSDRWorker->getStatus();
     } else {
         return 0;
     }
 }
handleMessage()
bool KiwiSDRInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 194 of file kiwisdrinput.cpp.
References applySettings(), FileRecord::genUniqueFileName(), DeviceAPI::getDeviceUID(), KiwiSDRInput::MsgConfigureKiwiSDR::getForce(), KiwiSDRInput::MsgConfigureKiwiSDR::getSettings(), KiwiSDRInput::MsgFileRecord::getStartStop(), KiwiSDRInput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), m_deviceAPI, KiwiSDRSettings::m_fileRecordName, m_fileSink, m_settings, KiwiSDRSettings::m_useReverseAPI, Message::match(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (MsgConfigureKiwiSDR::match(message))
     {
         MsgConfigureKiwiSDR& conf = (MsgConfigureKiwiSDR&) message;
         qDebug() << "KiwiSDRInput::handleMessage: MsgConfigureKiwiSDR";
         bool success = applySettings(conf.getSettings(), conf.getForce());
         if (!success)
         {
             qDebug("KiwiSDRInput::handleMessage: config error");
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "KiwiSDRInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "KiwiSDRInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void KiwiSDRInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 88 of file kiwisdrinput.cpp.
References applySettings(), and m_settings.
Referenced by KiwiSDRInput::MsgSetStatus::MsgSetStatus().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void KiwiSDRInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 552 of file kiwisdrinput.cpp.
Referenced by ~KiwiSDRInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "KiwiSDRInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("KiwiSDRInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
serialize()
QByteArray KiwiSDRInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 130 of file kiwisdrinput.cpp.
References m_settings, and KiwiSDRSettings::serialize().
Referenced by KiwiSDRInput::MsgSetStatus::MsgSetStatus().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void KiwiSDRInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 172 of file kiwisdrinput.cpp.
References KiwiSDRInput::MsgConfigureKiwiSDR::create(), KiwiSDRSettings::m_centerFrequency, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     KiwiSDRSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureKiwiSDR* message = MsgConfigureKiwiSDR::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureKiwiSDR* messageToGUI = MsgConfigureKiwiSDR::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setMessageQueueToGUI()
virtual void KiwiSDRInput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 131 of file kiwisdrinput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSource::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void KiwiSDRInput::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 134 of file kiwisdrinput.h.
References getCenterFrequency(), handleMessage(), setCenterFrequency(), webapiReportGet(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
setWorkerCenterFrequency
void KiwiSDRInput::setWorkerCenterFrequency (quint64 centerFrequency) signal
Referenced by applySettings(), and start().
setWorkerGain
void KiwiSDRInput::setWorkerGain (quint32 gain, bool useAGC) signal
Referenced by applySettings(), and start().
setWorkerServerAddress
void KiwiSDRInput::setWorkerServerAddress (QString serverAddress) signal
Referenced by applySettings(), and start().
setWorkerStatus
void KiwiSDRInput::setWorkerStatus (int status) private slot
Definition at line 187 of file kiwisdrinput.cpp.
References KiwiSDRInput::MsgSetStatus::create(), DeviceSampleSource::m_guiMessageQueue, and MessageQueue::push().
Referenced by start(), and stop().
 {
     if (m_guiMessageQueue) {
         m_guiMessageQueue->push(MsgSetStatus::create(status));
     }
 }
start()
bool KiwiSDRInput::start () virtual
Implements DeviceSampleSource.
Definition at line 93 of file kiwisdrinput.cpp.
References applySettings(), m_kiwiSDRWorker, m_kiwiSDRWorkerThread, m_mutex, m_running, DeviceSampleSource::m_sampleFifo, m_settings, KiwiSDRWorker::onCenterFrequencyChanged(), KiwiSDRWorker::onGainChanged(), KiwiSDRWorker::onServerAddressChanged(), setWorkerCenterFrequency(), setWorkerGain(), setWorkerServerAddress(), setWorkerStatus(), stop(), and KiwiSDRWorker::updateStatus().
Referenced by KiwiSDRInput(), and KiwiSDRInput::MsgSetStatus::MsgSetStatus().
 {
     QMutexLocker mutexLocker(&m_mutex);
     if (m_running) stop();
     m_kiwiSDRWorker = new KiwiSDRWorker(&m_sampleFifo);
     m_kiwiSDRWorker->moveToThread(&m_kiwiSDRWorkerThread);
     connect(this, &KiwiSDRInput::setWorkerCenterFrequency, m_kiwiSDRWorker, &KiwiSDRWorker::onCenterFrequencyChanged);
     connect(this, &KiwiSDRInput::setWorkerServerAddress, m_kiwiSDRWorker, &KiwiSDRWorker::onServerAddressChanged);
     connect(this, &KiwiSDRInput::setWorkerGain, m_kiwiSDRWorker, &KiwiSDRWorker::onGainChanged);
     connect(m_kiwiSDRWorker, &KiwiSDRWorker::updateStatus, this, &KiwiSDRInput::setWorkerStatus);
     mutexLocker.unlock();
     applySettings(m_settings, true);
     m_running = true;
     return true;
 }
startWorker
void KiwiSDRInput::startWorker () signal
stop()
void KiwiSDRInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 115 of file kiwisdrinput.cpp.
References m_kiwiSDRWorker, m_mutex, m_running, and setWorkerStatus().
Referenced by KiwiSDRInput::MsgSetStatus::MsgSetStatus(), start(), and ~KiwiSDRInput().
 {
     QMutexLocker mutexLocker(&m_mutex);
     setWorkerStatus(0);
     if (m_kiwiSDRWorker != 0)
     {
         m_kiwiSDRWorker->deleteLater();
         m_kiwiSDRWorker = 0;
     }
     m_running = false;
 }
stopWorker
void KiwiSDRInput::stopWorker () signal
webapiFormatDeviceReport()
void KiwiSDRInput::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 471 of file kiwisdrinput.cpp.
References SWGSDRangel::SWGDeviceReport::getKiwiSdrReport(), getStatus(), and SWGSDRangel::SWGKiwiSDRReport::setStatus().
Referenced by webapiReportGet().
 {
     response.getKiwiSdrReport()->setStatus(getStatus());
 }
webapiFormatDeviceSettings()
void KiwiSDRInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const KiwiSDRSettings & settings) private
Definition at line 440 of file kiwisdrinput.cpp.
References SWGSDRangel::SWGKiwiSDRSettings::getFileRecordName(), SWGSDRangel::SWGDeviceSettings::getKiwiSdrSettings(), SWGSDRangel::SWGKiwiSDRSettings::getReverseApiAddress(), SWGSDRangel::SWGKiwiSDRSettings::getServerAddress(), KiwiSDRSettings::m_centerFrequency, KiwiSDRSettings::m_dcBlock, KiwiSDRSettings::m_fileRecordName, KiwiSDRSettings::m_gain, KiwiSDRSettings::m_reverseAPIAddress, KiwiSDRSettings::m_reverseAPIDeviceIndex, KiwiSDRSettings::m_reverseAPIPort, KiwiSDRSettings::m_serverAddress, KiwiSDRSettings::m_useAGC, KiwiSDRSettings::m_useReverseAPI, SWGSDRangel::SWGKiwiSDRSettings::setCenterFrequency(), SWGSDRangel::SWGKiwiSDRSettings::setDcBlock(), SWGSDRangel::SWGKiwiSDRSettings::setFileRecordName(), SWGSDRangel::SWGKiwiSDRSettings::setGain(), SWGSDRangel::SWGKiwiSDRSettings::setReverseApiAddress(), SWGSDRangel::SWGKiwiSDRSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGKiwiSDRSettings::setReverseApiPort(), SWGSDRangel::SWGKiwiSDRSettings::setServerAddress(), SWGSDRangel::SWGKiwiSDRSettings::setUseAgc(), and SWGSDRangel::SWGKiwiSDRSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getKiwiSdrSettings()->setGain(settings.m_gain);
     response.getKiwiSdrSettings()->setUseAgc(settings.m_useAGC ? 1 : 0);
     response.getKiwiSdrSettings()->setDcBlock(settings.m_dcBlock ? 1 : 0);
     response.getKiwiSdrSettings()->setCenterFrequency(settings.m_centerFrequency);
     if (response.getKiwiSdrSettings()->getServerAddress()) {
         *response.getKiwiSdrSettings()->getServerAddress() = settings.m_serverAddress;
     } else {
         response.getKiwiSdrSettings()->setServerAddress(new QString(settings.m_serverAddress));
     }
     if (response.getKiwiSdrSettings()->getFileRecordName()) {
         *response.getKiwiSdrSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getKiwiSdrSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getKiwiSdrSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getKiwiSdrSettings()->getReverseApiAddress()) {
         *response.getKiwiSdrSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getKiwiSdrSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getKiwiSdrSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getKiwiSdrSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int KiwiSDRInput::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 429 of file kiwisdrinput.cpp.
References SWGSDRangel::SWGDeviceReport::getKiwiSdrReport(), SWGSDRangel::SWGKiwiSDRReport::init(), SWGSDRangel::SWGDeviceReport::setKiwiSdrReport(), and webapiFormatDeviceReport().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setKiwiSdrReport(new SWGSDRangel::SWGKiwiSDRReport());
     response.getKiwiSdrReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void KiwiSDRInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const KiwiSDRSettings & settings, bool force) private
Definition at line 476 of file kiwisdrinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getKiwiSdrSettings(), KiwiSDRSettings::m_centerFrequency, KiwiSDRSettings::m_dcBlock, m_deviceAPI, KiwiSDRSettings::m_fileRecordName, KiwiSDRSettings::m_gain, m_networkManager, m_networkRequest, KiwiSDRSettings::m_reverseAPIAddress, KiwiSDRSettings::m_reverseAPIDeviceIndex, KiwiSDRSettings::m_reverseAPIPort, KiwiSDRSettings::m_serverAddress, KiwiSDRSettings::m_useAGC, SWGSDRangel::SWGKiwiSDRSettings::setCenterFrequency(), SWGSDRangel::SWGKiwiSDRSettings::setDcBlock(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGKiwiSDRSettings::setFileRecordName(), SWGSDRangel::SWGKiwiSDRSettings::setGain(), SWGSDRangel::SWGDeviceSettings::setKiwiSdrSettings(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGKiwiSDRSettings::setServerAddress(), and SWGSDRangel::SWGKiwiSDRSettings::setUseAgc().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("KiwiSDR"));
     swgDeviceSettings->setKiwiSdrSettings(new SWGSDRangel::SWGKiwiSDRSettings());
     SWGSDRangel::SWGKiwiSDRSettings *swgKiwiSDRSettings = swgDeviceSettings->getKiwiSdrSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("gain")) {
         swgKiwiSDRSettings->setGain(settings.m_gain);
     }
     if (deviceSettingsKeys.contains("useAGC")) {
         swgKiwiSDRSettings->setUseAgc(settings.m_useAGC ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("dcBlock") || force) {
         swgKiwiSDRSettings->setDcBlock(settings.m_dcBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgKiwiSDRSettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("serverAddress") || force) {
         swgKiwiSDRSettings->setServerAddress(new QString(settings.m_serverAddress));
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgKiwiSDRSettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void KiwiSDRInput::webapiReverseSendStartStop (bool start) private
Definition at line 524 of file kiwisdrinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, KiwiSDRSettings::m_reverseAPIAddress, KiwiSDRSettings::m_reverseAPIDeviceIndex, KiwiSDRSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("KiwiSDR"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int KiwiSDRInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 346 of file kiwisdrinput.cpp.
References KiwiSDRInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int KiwiSDRInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 337 of file kiwisdrinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int KiwiSDRInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 365 of file kiwisdrinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getKiwiSdrSettings(), SWGSDRangel::SWGKiwiSDRSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setKiwiSdrSettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setKiwiSdrSettings(new SWGSDRangel::SWGKiwiSDRSettings());
     response.getKiwiSdrSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int KiwiSDRInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 376 of file kiwisdrinput.cpp.
References KiwiSDRInput::MsgConfigureKiwiSDR::create(), SWGSDRangel::SWGKiwiSDRSettings::getCenterFrequency(), SWGSDRangel::SWGKiwiSDRSettings::getDcBlock(), SWGSDRangel::SWGKiwiSDRSettings::getFileRecordName(), SWGSDRangel::SWGKiwiSDRSettings::getGain(), SWGSDRangel::SWGDeviceSettings::getKiwiSdrSettings(), SWGSDRangel::SWGKiwiSDRSettings::getReverseApiAddress(), SWGSDRangel::SWGKiwiSDRSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGKiwiSDRSettings::getReverseApiPort(), SWGSDRangel::SWGKiwiSDRSettings::getServerAddress(), SWGSDRangel::SWGKiwiSDRSettings::getUseAgc(), SWGSDRangel::SWGKiwiSDRSettings::getUseReverseApi(), KiwiSDRSettings::m_centerFrequency, KiwiSDRSettings::m_dcBlock, KiwiSDRSettings::m_fileRecordName, KiwiSDRSettings::m_gain, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, KiwiSDRSettings::m_reverseAPIAddress, KiwiSDRSettings::m_reverseAPIDeviceIndex, KiwiSDRSettings::m_reverseAPIPort, KiwiSDRSettings::m_serverAddress, m_settings, KiwiSDRSettings::m_useAGC, KiwiSDRSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     KiwiSDRSettings settings = m_settings;
     if (deviceSettingsKeys.contains("gain")) {
         settings.m_gain = response.getKiwiSdrSettings()->getGain();
     }
     if (deviceSettingsKeys.contains("useAGC")) {
         settings.m_useAGC = response.getKiwiSdrSettings()->getUseAgc();
     }
     if (deviceSettingsKeys.contains("dcBlock")) {
         settings.m_dcBlock = response.getKiwiSdrSettings()->getDcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getKiwiSdrSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("serverAddress")) {
         settings.m_serverAddress = *response.getKiwiSdrSettings()->getServerAddress();
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getKiwiSdrSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getKiwiSdrSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getKiwiSdrSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getKiwiSdrSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getKiwiSdrSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureKiwiSDR *msg = MsgConfigureKiwiSDR::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureKiwiSDR *msgToGUI = MsgConfigureKiwiSDR::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_deviceAPI
DeviceAPI* KiwiSDRInput::m_deviceAPI private
Definition at line 164 of file kiwisdrinput.h.
Referenced by applySettings(), handleMessage(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~KiwiSDRInput().
m_deviceDescription
QString KiwiSDRInput::m_deviceDescription private
Definition at line 170 of file kiwisdrinput.h.
Referenced by getDeviceDescription().
m_fileSink
FileRecord* KiwiSDRInput::m_fileSink private
File sink to record device I/Q output.
Definition at line 165 of file kiwisdrinput.h.
Referenced by applySettings(), handleMessage(), and ~KiwiSDRInput().
m_kiwiSDRWorker
KiwiSDRWorker* KiwiSDRInput::m_kiwiSDRWorker private
Definition at line 168 of file kiwisdrinput.h.
Referenced by getStatus(), start(), and stop().
m_kiwiSDRWorkerThread
QThread KiwiSDRInput::m_kiwiSDRWorkerThread private
Definition at line 169 of file kiwisdrinput.h.
Referenced by start(), and ~KiwiSDRInput().
m_masterTimer
const QTimer& KiwiSDRInput::m_masterTimer private
Definition at line 172 of file kiwisdrinput.h.
m_mutex
QMutex KiwiSDRInput::m_mutex private
Definition at line 166 of file kiwisdrinput.h.
Referenced by start(), and stop().
m_networkManager
QNetworkAccessManager* KiwiSDRInput::m_networkManager private
Definition at line 173 of file kiwisdrinput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~KiwiSDRInput().
m_networkRequest
QNetworkRequest KiwiSDRInput::m_networkRequest private
Definition at line 174 of file kiwisdrinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool KiwiSDRInput::m_running private
Definition at line 171 of file kiwisdrinput.h.
Referenced by start(), stop(), and ~KiwiSDRInput().
m_settings
KiwiSDRSettings KiwiSDRInput::m_settings private
Definition at line 167 of file kiwisdrinput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), handleMessage(), init(), serialize(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
The documentation for this class was generated from the following files:
plugins/samplesource/kiwisdr/kiwisdrinput.h
plugins/samplesource/kiwisdr/kiwisdrinput.cpp