SDRAngel: SWGSDRangel::SWGObject Class Reference
SWGSDRangel::SWGObject Class Reference
#include <SWGObject.h>
Public Member Functions
virtual QJsonObject * asJsonObject ()
virtual ~SWGObject ()
virtual SWGObject * fromJson (QString &jsonString)
virtual void fromJsonObject (QJsonObject &json)
virtual QString asJson ()
virtual bool isSet ()
Detailed Description
Definition at line 20 of file SWGObject.h.
Constructor & Destructor Documentation
~SWGObject()
virtual SWGSDRangel::SWGObject::~SWGObject () inline virtual
Definition at line 25 of file SWGObject.h.
 {}
Member Function Documentation
asJson()
virtual QString SWGSDRangel::SWGObject::asJson () inline virtual
Reimplemented in SWGSDRangel::SWGDeviceSettings, SWGSDRangel::SWGDeviceSettings_2, SWGSDRangel::SWGChannelSettings, SWGSDRangel::SWGChannelSettings_2, SWGSDRangel::SWGDeviceReport, SWGSDRangel::SWGChannelReport, SWGSDRangel::SWGSoapySDRReport, SWGSDRangel::SWGPreset, SWGSDRangel::SWGSDRPlayReport, SWGSDRangel::SWGBladeRF2InputReport, SWGSDRangel::SWGInstanceConfigResponse, SWGSDRangel::SWGSoapySDRInputSettings, SWGSDRangel::SWGSoapySDROutputSettings, SWGSDRangel::SWGArgInfo, SWGSDRangel::SWGAudioDevices, SWGSDRangel::SWGDeviceSet, SWGSDRangel::SWGInstanceSummaryResponse, SWGSDRangel::SWGPresetGroup, SWGSDRangel::SWGRDSReport, SWGSDRangel::SWGSoapySDRFrequencySetting, SWGSDRangel::SWGTestMISettings, SWGSDRangel::SWGAirspyHFReport, SWGSDRangel::SWGAirspyReport, SWGSDRangel::SWGAMBEDevices, SWGSDRangel::SWGAMModSettings, SWGSDRangel::SWGBladeRF2OutputReport, SWGSDRangel::SWGChannel, SWGSDRangel::SWGChannelConfig, SWGSDRangel::SWGChannelsDetail, SWGSDRangel::SWGDeviceConfig, SWGSDRangel::SWGDeviceSetList, SWGSDRangel::SWGDVSerialDevices, SWGSDRangel::SWGFreeDVModSettings, SWGSDRangel::SWGInstanceChannelsResponse, SWGSDRangel::SWGInstanceDevicesResponse, SWGSDRangel::SWGNFMModSettings, SWGSDRangel::SWGPerseusReport, SWGSDRangel::SWGPresetExport, SWGSDRangel::SWGPresets, SWGSDRangel::SWGRtlSdrReport, SWGSDRangel::SWGSoapySDRGainSetting, SWGSDRangel::SWGSSBModSettings, SWGSDRangel::SWGWFMModSettings, SWGSDRangel::SWGAirspyHFSettings, SWGSDRangel::SWGAirspySettings, SWGSDRangel::SWGAMBEDevice, SWGSDRangel::SWGAMDemodSettings, SWGSDRangel::SWGArgValue, SWGSDRangel::SWGATVModSettings, SWGSDRangel::SWGAudioInputDevice, SWGSDRangel::SWGAudioOutputDevice, SWGSDRangel::SWGBFMDemodReport, SWGSDRangel::SWGBFMDemodSettings, SWGSDRangel::SWGBladeRF1InputSettings, SWGSDRangel::SWGBladeRF1OutputSettings, SWGSDRangel::SWGBladeRF2InputSettings, SWGSDRangel::SWGBladeRF2OutputSettings, SWGSDRangel::SWGChannelListItem, SWGSDRangel::SWGCommand, SWGSDRangel::SWGCWKeyerSettings, SWGSDRangel::SWGDeviceListItem, SWGSDRangel::SWGDeviceState, SWGSDRangel::SWGDSDDemodReport, SWGSDRangel::SWGDSDDemodSettings, SWGSDRangel::SWGDVSerialDevice, SWGSDRangel::SWGErrorResponse, SWGSDRangel::SWGFCDProPlusSettings, SWGSDRangel::SWGFCDProSettings, SWGSDRangel::SWGFileInputReport, SWGSDRangel::SWGFileInputSettings, SWGSDRangel::SWGFileSourceReport, SWGSDRangel::SWGFileSourceSettings, SWGSDRangel::SWGFreeDVDemodSettings, SWGSDRangel::SWGFreqTrackerSettings, SWGSDRangel::SWGFrequencyBand, SWGSDRangel::SWGHackRFInputSettings, SWGSDRangel::SWGHackRFOutputSettings, SWGSDRangel::SWGKiwiSDRSettings, SWGSDRangel::SWGLimeSdrInputSettings, SWGSDRangel::SWGLimeSdrOutputSettings, SWGSDRangel::SWGLocalInputSettings, SWGSDRangel::SWGLocalOutputSettings, SWGSDRangel::SWGLocalSinkSettings, SWGSDRangel::SWGLocalSourceSettings, SWGSDRangel::SWGLoggingInfo, SWGSDRangel::SWGNamedEnum, SWGSDRangel::SWGNFMDemodSettings, SWGSDRangel::SWGPerseusSettings, SWGSDRangel::SWGPlutoSdrInputReport, SWGSDRangel::SWGPlutoSdrInputSettings, SWGSDRangel::SWGPlutoSdrOutputReport, SWGSDRangel::SWGPlutoSdrOutputSettings, SWGSDRangel::SWGPreferences, SWGSDRangel::SWGPresetIdentifier, SWGSDRangel::SWGPresetImport, SWGSDRangel::SWGPresetItem, SWGSDRangel::SWGPresetTransfer, SWGSDRangel::SWGRemoteInputReport, SWGSDRangel::SWGRemoteInputSettings, SWGSDRangel::SWGRemoteOutputSettings, SWGSDRangel::SWGRemoteSinkSettings, SWGSDRangel::SWGRemoteSourceSettings, SWGSDRangel::SWGRtlSdrSettings, SWGSDRangel::SWGSamplingDevice, SWGSDRangel::SWGSDRPlaySettings, SWGSDRangel::SWGSSBDemodSettings, SWGSDRangel::SWGSuccessResponse, SWGSDRangel::SWGTestSourceSettings, SWGSDRangel::SWGUDPSinkSettings, SWGSDRangel::SWGUDPSourceSettings, SWGSDRangel::SWGWFMDemodSettings, SWGSDRangel::SWGXtrxInputSettings, SWGSDRangel::SWGXtrxOutputSettings, SWGSDRangel::SWGAMDemodReport, SWGSDRangel::SWGAMModReport, SWGSDRangel::SWGATVModReport, SWGSDRangel::SWGBandwidth, SWGSDRangel::SWGComplex, SWGSDRangel::SWGFreeDVDemodReport, SWGSDRangel::SWGFreeDVModReport, SWGSDRangel::SWGFreqTrackerReport, SWGSDRangel::SWGFrequency, SWGSDRangel::SWGFrequencyRange, SWGSDRangel::SWGGain, SWGSDRangel::SWGGLSpectrum, SWGSDRangel::SWGKiwiSDRReport, SWGSDRangel::SWGLimeSdrInputReport, SWGSDRangel::SWGLimeSdrOutputReport, SWGSDRangel::SWGLocalInputReport, SWGSDRangel::SWGLocalOutputReport, SWGSDRangel::SWGLocationInformation, SWGSDRangel::SWGNFMDemodReport, SWGSDRangel::SWGNFMModReport, SWGSDRangel::SWGRange, SWGSDRangel::SWGRangeFloat, SWGSDRangel::SWGRDSReport_altFrequencies, SWGSDRangel::SWGRemoteOutputReport, SWGSDRangel::SWGRemoteSourceReport, SWGSDRangel::SWGSampleRate, SWGSDRangel::SWGSSBDemodReport, SWGSDRangel::SWGSSBModReport, SWGSDRangel::SWGTestMiStreamSettings, SWGSDRangel::SWGUDPSinkReport, SWGSDRangel::SWGUDPSourceReport, SWGSDRangel::SWGWFMDemodReport, SWGSDRangel::SWGWFMModReport, SWGSDRangel::SWGXtrxInputReport, and SWGSDRangel::SWGXtrxOutputReport.
Definition at line 33 of file SWGObject.h.
{
         return QString("");
     }
asJsonObject()
virtual QJsonObject* SWGSDRangel::SWGObject::asJsonObject () inline virtual
Reimplemented in SWGSDRangel::SWGDeviceSettings, SWGSDRangel::SWGDeviceSettings_2, SWGSDRangel::SWGChannelSettings, SWGSDRangel::SWGChannelSettings_2, SWGSDRangel::SWGDeviceReport, SWGSDRangel::SWGChannelReport, SWGSDRangel::SWGSoapySDRReport, SWGSDRangel::SWGPreset, SWGSDRangel::SWGSDRPlayReport, SWGSDRangel::SWGBladeRF2InputReport, SWGSDRangel::SWGInstanceConfigResponse, SWGSDRangel::SWGSoapySDRInputSettings, SWGSDRangel::SWGSoapySDROutputSettings, SWGSDRangel::SWGArgInfo, SWGSDRangel::SWGAudioDevices, SWGSDRangel::SWGDeviceSet, SWGSDRangel::SWGInstanceSummaryResponse, SWGSDRangel::SWGPresetGroup, SWGSDRangel::SWGRDSReport, SWGSDRangel::SWGSoapySDRFrequencySetting, SWGSDRangel::SWGTestMISettings, SWGSDRangel::SWGAirspyHFReport, SWGSDRangel::SWGAirspyReport, SWGSDRangel::SWGAMBEDevices, SWGSDRangel::SWGAMModSettings, SWGSDRangel::SWGBladeRF2OutputReport, SWGSDRangel::SWGChannel, SWGSDRangel::SWGChannelConfig, SWGSDRangel::SWGChannelsDetail, SWGSDRangel::SWGDeviceConfig, SWGSDRangel::SWGDeviceSetList, SWGSDRangel::SWGDVSerialDevices, SWGSDRangel::SWGFreeDVModSettings, SWGSDRangel::SWGInstanceChannelsResponse, SWGSDRangel::SWGInstanceDevicesResponse, SWGSDRangel::SWGNFMModSettings, SWGSDRangel::SWGPerseusReport, SWGSDRangel::SWGPresetExport, SWGSDRangel::SWGPresets, SWGSDRangel::SWGRtlSdrReport, SWGSDRangel::SWGSoapySDRGainSetting, SWGSDRangel::SWGSSBModSettings, SWGSDRangel::SWGWFMModSettings, SWGSDRangel::SWGAirspyHFSettings, SWGSDRangel::SWGAirspySettings, SWGSDRangel::SWGAMBEDevice, SWGSDRangel::SWGAMDemodSettings, SWGSDRangel::SWGArgValue, SWGSDRangel::SWGATVModSettings, SWGSDRangel::SWGAudioInputDevice, SWGSDRangel::SWGAudioOutputDevice, SWGSDRangel::SWGBFMDemodReport, SWGSDRangel::SWGBFMDemodSettings, SWGSDRangel::SWGBladeRF1InputSettings, SWGSDRangel::SWGBladeRF1OutputSettings, SWGSDRangel::SWGBladeRF2InputSettings, SWGSDRangel::SWGBladeRF2OutputSettings, SWGSDRangel::SWGChannelListItem, SWGSDRangel::SWGCommand, SWGSDRangel::SWGCWKeyerSettings, SWGSDRangel::SWGDeviceListItem, SWGSDRangel::SWGDeviceState, SWGSDRangel::SWGDSDDemodReport, SWGSDRangel::SWGDSDDemodSettings, SWGSDRangel::SWGDVSerialDevice, SWGSDRangel::SWGErrorResponse, SWGSDRangel::SWGFCDProPlusSettings, SWGSDRangel::SWGFCDProSettings, SWGSDRangel::SWGFileInputReport, SWGSDRangel::SWGFileInputSettings, SWGSDRangel::SWGFileSourceReport, SWGSDRangel::SWGFileSourceSettings, SWGSDRangel::SWGFreeDVDemodSettings, SWGSDRangel::SWGFreqTrackerSettings, SWGSDRangel::SWGFrequencyBand, SWGSDRangel::SWGHackRFInputSettings, SWGSDRangel::SWGHackRFOutputSettings, SWGSDRangel::SWGKiwiSDRSettings, SWGSDRangel::SWGLimeSdrInputSettings, SWGSDRangel::SWGLimeSdrOutputSettings, SWGSDRangel::SWGLocalInputSettings, SWGSDRangel::SWGLocalOutputSettings, SWGSDRangel::SWGLocalSinkSettings, SWGSDRangel::SWGLocalSourceSettings, SWGSDRangel::SWGLoggingInfo, SWGSDRangel::SWGNamedEnum, SWGSDRangel::SWGNFMDemodSettings, SWGSDRangel::SWGPerseusSettings, SWGSDRangel::SWGPlutoSdrInputReport, SWGSDRangel::SWGPlutoSdrInputSettings, SWGSDRangel::SWGPlutoSdrOutputReport, SWGSDRangel::SWGPlutoSdrOutputSettings, SWGSDRangel::SWGPreferences, SWGSDRangel::SWGPresetIdentifier, SWGSDRangel::SWGPresetImport, SWGSDRangel::SWGPresetItem, SWGSDRangel::SWGPresetTransfer, SWGSDRangel::SWGRemoteInputReport, SWGSDRangel::SWGRemoteInputSettings, SWGSDRangel::SWGRemoteOutputSettings, SWGSDRangel::SWGRemoteSinkSettings, SWGSDRangel::SWGRemoteSourceSettings, SWGSDRangel::SWGRtlSdrSettings, SWGSDRangel::SWGSamplingDevice, SWGSDRangel::SWGSDRPlaySettings, SWGSDRangel::SWGSSBDemodSettings, SWGSDRangel::SWGSuccessResponse, SWGSDRangel::SWGTestSourceSettings, SWGSDRangel::SWGUDPSinkSettings, SWGSDRangel::SWGUDPSourceSettings, SWGSDRangel::SWGWFMDemodSettings, SWGSDRangel::SWGXtrxInputSettings, SWGSDRangel::SWGXtrxOutputSettings, SWGSDRangel::SWGAMDemodReport, SWGSDRangel::SWGAMModReport, SWGSDRangel::SWGATVModReport, SWGSDRangel::SWGBandwidth, SWGSDRangel::SWGComplex, SWGSDRangel::SWGFreeDVDemodReport, SWGSDRangel::SWGFreeDVModReport, SWGSDRangel::SWGFreqTrackerReport, SWGSDRangel::SWGFrequency, SWGSDRangel::SWGFrequencyRange, SWGSDRangel::SWGGain, SWGSDRangel::SWGGLSpectrum, SWGSDRangel::SWGKiwiSDRReport, SWGSDRangel::SWGLimeSdrInputReport, SWGSDRangel::SWGLimeSdrOutputReport, SWGSDRangel::SWGLocalInputReport, SWGSDRangel::SWGLocalOutputReport, SWGSDRangel::SWGLocationInformation, SWGSDRangel::SWGNFMDemodReport, SWGSDRangel::SWGNFMModReport, SWGSDRangel::SWGRange, SWGSDRangel::SWGRangeFloat, SWGSDRangel::SWGRDSReport_altFrequencies, SWGSDRangel::SWGRemoteOutputReport, SWGSDRangel::SWGRemoteSourceReport, SWGSDRangel::SWGSampleRate, SWGSDRangel::SWGSSBDemodReport, SWGSDRangel::SWGSSBModReport, SWGSDRangel::SWGTestMiStreamSettings, SWGSDRangel::SWGUDPSinkReport, SWGSDRangel::SWGUDPSourceReport, SWGSDRangel::SWGWFMDemodReport, SWGSDRangel::SWGWFMModReport, SWGSDRangel::SWGXtrxInputReport, and SWGSDRangel::SWGXtrxOutputReport.
Definition at line 22 of file SWGObject.h.
Referenced by SWGSDRangel::toJsonArray(), and SWGSDRangel::toJsonValue().
{
       return new QJsonObject();
     }
fromJson()
virtual SWGObject* SWGSDRangel::SWGObject::fromJson (QString & jsonString) inline virtual
Reimplemented in SWGSDRangel::SWGDeviceSettings, SWGSDRangel::SWGDeviceSettings_2, SWGSDRangel::SWGChannelSettings, SWGSDRangel::SWGChannelSettings_2, SWGSDRangel::SWGDeviceReport, SWGSDRangel::SWGChannelReport, SWGSDRangel::SWGSoapySDRReport, SWGSDRangel::SWGPreset, SWGSDRangel::SWGSDRPlayReport, SWGSDRangel::SWGBladeRF2InputReport, SWGSDRangel::SWGInstanceConfigResponse, SWGSDRangel::SWGSoapySDRInputSettings, SWGSDRangel::SWGSoapySDROutputSettings, SWGSDRangel::SWGArgInfo, SWGSDRangel::SWGAudioDevices, SWGSDRangel::SWGDeviceSet, SWGSDRangel::SWGInstanceSummaryResponse, SWGSDRangel::SWGPresetGroup, SWGSDRangel::SWGRDSReport, SWGSDRangel::SWGSoapySDRFrequencySetting, SWGSDRangel::SWGTestMISettings, SWGSDRangel::SWGAirspyHFReport, SWGSDRangel::SWGAirspyReport, SWGSDRangel::SWGAMBEDevices, SWGSDRangel::SWGAMModSettings, SWGSDRangel::SWGBladeRF2OutputReport, SWGSDRangel::SWGChannel, SWGSDRangel::SWGChannelConfig, SWGSDRangel::SWGChannelsDetail, SWGSDRangel::SWGDeviceConfig, SWGSDRangel::SWGDeviceSetList, SWGSDRangel::SWGDVSerialDevices, SWGSDRangel::SWGFreeDVModSettings, SWGSDRangel::SWGInstanceChannelsResponse, SWGSDRangel::SWGInstanceDevicesResponse, SWGSDRangel::SWGNFMModSettings, SWGSDRangel::SWGPerseusReport, SWGSDRangel::SWGPresetExport, SWGSDRangel::SWGPresets, SWGSDRangel::SWGRtlSdrReport, SWGSDRangel::SWGSoapySDRGainSetting, SWGSDRangel::SWGSSBModSettings, SWGSDRangel::SWGWFMModSettings, SWGSDRangel::SWGAirspyHFSettings, SWGSDRangel::SWGAirspySettings, SWGSDRangel::SWGAMBEDevice, SWGSDRangel::SWGAMDemodSettings, SWGSDRangel::SWGArgValue, SWGSDRangel::SWGATVModSettings, SWGSDRangel::SWGAudioInputDevice, SWGSDRangel::SWGAudioOutputDevice, SWGSDRangel::SWGBFMDemodReport, SWGSDRangel::SWGBFMDemodSettings, SWGSDRangel::SWGBladeRF1InputSettings, SWGSDRangel::SWGBladeRF1OutputSettings, SWGSDRangel::SWGBladeRF2InputSettings, SWGSDRangel::SWGBladeRF2OutputSettings, SWGSDRangel::SWGChannelListItem, SWGSDRangel::SWGCommand, SWGSDRangel::SWGCWKeyerSettings, SWGSDRangel::SWGDeviceListItem, SWGSDRangel::SWGDeviceState, SWGSDRangel::SWGDSDDemodReport, SWGSDRangel::SWGDSDDemodSettings, SWGSDRangel::SWGDVSerialDevice, SWGSDRangel::SWGErrorResponse, SWGSDRangel::SWGFCDProPlusSettings, SWGSDRangel::SWGFCDProSettings, SWGSDRangel::SWGFileInputReport, SWGSDRangel::SWGFileInputSettings, SWGSDRangel::SWGFileSourceReport, SWGSDRangel::SWGFileSourceSettings, SWGSDRangel::SWGFreeDVDemodSettings, SWGSDRangel::SWGFreqTrackerSettings, SWGSDRangel::SWGFrequencyBand, SWGSDRangel::SWGHackRFInputSettings, SWGSDRangel::SWGHackRFOutputSettings, SWGSDRangel::SWGKiwiSDRSettings, SWGSDRangel::SWGLimeSdrInputSettings, SWGSDRangel::SWGLimeSdrOutputSettings, SWGSDRangel::SWGLocalInputSettings, SWGSDRangel::SWGLocalOutputSettings, SWGSDRangel::SWGLocalSinkSettings, SWGSDRangel::SWGLocalSourceSettings, SWGSDRangel::SWGLoggingInfo, SWGSDRangel::SWGNamedEnum, SWGSDRangel::SWGNFMDemodSettings, SWGSDRangel::SWGPerseusSettings, SWGSDRangel::SWGPlutoSdrInputReport, SWGSDRangel::SWGPlutoSdrInputSettings, SWGSDRangel::SWGPlutoSdrOutputReport, SWGSDRangel::SWGPlutoSdrOutputSettings, SWGSDRangel::SWGPreferences, SWGSDRangel::SWGPresetIdentifier, SWGSDRangel::SWGPresetImport, SWGSDRangel::SWGPresetItem, SWGSDRangel::SWGPresetTransfer, SWGSDRangel::SWGRemoteInputReport, SWGSDRangel::SWGRemoteInputSettings, SWGSDRangel::SWGRemoteOutputSettings, SWGSDRangel::SWGRemoteSinkSettings, SWGSDRangel::SWGRemoteSourceSettings, SWGSDRangel::SWGRtlSdrSettings, SWGSDRangel::SWGSamplingDevice, SWGSDRangel::SWGSDRPlaySettings, SWGSDRangel::SWGSSBDemodSettings, SWGSDRangel::SWGSuccessResponse, SWGSDRangel::SWGTestSourceSettings, SWGSDRangel::SWGUDPSinkSettings, SWGSDRangel::SWGUDPSourceSettings, SWGSDRangel::SWGWFMDemodSettings, SWGSDRangel::SWGXtrxInputSettings, SWGSDRangel::SWGXtrxOutputSettings, SWGSDRangel::SWGAMDemodReport, SWGSDRangel::SWGAMModReport, SWGSDRangel::SWGATVModReport, SWGSDRangel::SWGBandwidth, SWGSDRangel::SWGComplex, SWGSDRangel::SWGFreeDVDemodReport, SWGSDRangel::SWGFreeDVModReport, SWGSDRangel::SWGFreqTrackerReport, SWGSDRangel::SWGFrequency, SWGSDRangel::SWGFrequencyRange, SWGSDRangel::SWGGain, SWGSDRangel::SWGGLSpectrum, SWGSDRangel::SWGKiwiSDRReport, SWGSDRangel::SWGLimeSdrInputReport, SWGSDRangel::SWGLimeSdrOutputReport, SWGSDRangel::SWGLocalInputReport, SWGSDRangel::SWGLocalOutputReport, SWGSDRangel::SWGLocationInformation, SWGSDRangel::SWGNFMDemodReport, SWGSDRangel::SWGNFMModReport, SWGSDRangel::SWGRange, SWGSDRangel::SWGRangeFloat, SWGSDRangel::SWGRDSReport_altFrequencies, SWGSDRangel::SWGRemoteOutputReport, SWGSDRangel::SWGRemoteSourceReport, SWGSDRangel::SWGSampleRate, SWGSDRangel::SWGSSBDemodReport, SWGSDRangel::SWGSSBModReport, SWGSDRangel::SWGTestMiStreamSettings, SWGSDRangel::SWGUDPSinkReport, SWGSDRangel::SWGUDPSourceReport, SWGSDRangel::SWGWFMDemodReport, SWGSDRangel::SWGWFMModReport, SWGSDRangel::SWGXtrxInputReport, and SWGSDRangel::SWGXtrxOutputReport.
Definition at line 26 of file SWGObject.h.
Referenced by SWGSDRangel::create().
{
         Q_UNUSED(jsonString);
         return new SWGObject();
     }
fromJsonObject()
virtual void SWGSDRangel::SWGObject::fromJsonObject (QJsonObject & json) inline virtual
Reimplemented in SWGSDRangel::SWGDeviceSettings, SWGSDRangel::SWGDeviceSettings_2, SWGSDRangel::SWGChannelSettings, SWGSDRangel::SWGChannelSettings_2, SWGSDRangel::SWGDeviceReport, SWGSDRangel::SWGChannelReport, SWGSDRangel::SWGSoapySDRReport, SWGSDRangel::SWGPreset, SWGSDRangel::SWGSDRPlayReport, SWGSDRangel::SWGBladeRF2InputReport, SWGSDRangel::SWGInstanceConfigResponse, SWGSDRangel::SWGSoapySDRInputSettings, SWGSDRangel::SWGSoapySDROutputSettings, SWGSDRangel::SWGArgInfo, SWGSDRangel::SWGAudioDevices, SWGSDRangel::SWGDeviceSet, SWGSDRangel::SWGInstanceSummaryResponse, SWGSDRangel::SWGPresetGroup, SWGSDRangel::SWGRDSReport, SWGSDRangel::SWGSoapySDRFrequencySetting, SWGSDRangel::SWGTestMISettings, SWGSDRangel::SWGAirspyHFReport, SWGSDRangel::SWGAirspyReport, SWGSDRangel::SWGAMBEDevices, SWGSDRangel::SWGAMModSettings, SWGSDRangel::SWGBladeRF2OutputReport, SWGSDRangel::SWGChannel, SWGSDRangel::SWGChannelConfig, SWGSDRangel::SWGChannelsDetail, SWGSDRangel::SWGDeviceConfig, SWGSDRangel::SWGDeviceSetList, SWGSDRangel::SWGDVSerialDevices, SWGSDRangel::SWGFreeDVModSettings, SWGSDRangel::SWGInstanceChannelsResponse, SWGSDRangel::SWGInstanceDevicesResponse, SWGSDRangel::SWGNFMModSettings, SWGSDRangel::SWGPerseusReport, SWGSDRangel::SWGPresetExport, SWGSDRangel::SWGPresets, SWGSDRangel::SWGRtlSdrReport, SWGSDRangel::SWGSoapySDRGainSetting, SWGSDRangel::SWGSSBModSettings, SWGSDRangel::SWGWFMModSettings, SWGSDRangel::SWGAirspyHFSettings, SWGSDRangel::SWGAirspySettings, SWGSDRangel::SWGAMBEDevice, SWGSDRangel::SWGAMDemodSettings, SWGSDRangel::SWGArgValue, SWGSDRangel::SWGATVModSettings, SWGSDRangel::SWGAudioInputDevice, SWGSDRangel::SWGAudioOutputDevice, SWGSDRangel::SWGBFMDemodReport, SWGSDRangel::SWGBFMDemodSettings, SWGSDRangel::SWGBladeRF1InputSettings, SWGSDRangel::SWGBladeRF1OutputSettings, SWGSDRangel::SWGBladeRF2InputSettings, SWGSDRangel::SWGBladeRF2OutputSettings, SWGSDRangel::SWGChannelListItem, SWGSDRangel::SWGCommand, SWGSDRangel::SWGCWKeyerSettings, SWGSDRangel::SWGDeviceListItem, SWGSDRangel::SWGDeviceState, SWGSDRangel::SWGDSDDemodReport, SWGSDRangel::SWGDSDDemodSettings, SWGSDRangel::SWGDVSerialDevice, SWGSDRangel::SWGErrorResponse, SWGSDRangel::SWGFCDProPlusSettings, SWGSDRangel::SWGFCDProSettings, SWGSDRangel::SWGFileInputReport, SWGSDRangel::SWGFileInputSettings, SWGSDRangel::SWGFileSourceReport, SWGSDRangel::SWGFileSourceSettings, SWGSDRangel::SWGFreeDVDemodSettings, SWGSDRangel::SWGFreqTrackerSettings, SWGSDRangel::SWGFrequencyBand, SWGSDRangel::SWGHackRFInputSettings, SWGSDRangel::SWGHackRFOutputSettings, SWGSDRangel::SWGKiwiSDRSettings, SWGSDRangel::SWGLimeSdrInputSettings, SWGSDRangel::SWGLimeSdrOutputSettings, SWGSDRangel::SWGLocalInputSettings, SWGSDRangel::SWGLocalOutputSettings, SWGSDRangel::SWGLocalSinkSettings, SWGSDRangel::SWGLocalSourceSettings, SWGSDRangel::SWGLoggingInfo, SWGSDRangel::SWGNamedEnum, SWGSDRangel::SWGNFMDemodSettings, SWGSDRangel::SWGPerseusSettings, SWGSDRangel::SWGPlutoSdrInputReport, SWGSDRangel::SWGPlutoSdrInputSettings, SWGSDRangel::SWGPlutoSdrOutputReport, SWGSDRangel::SWGPlutoSdrOutputSettings, SWGSDRangel::SWGPreferences, SWGSDRangel::SWGPresetIdentifier, SWGSDRangel::SWGPresetImport, SWGSDRangel::SWGPresetItem, SWGSDRangel::SWGPresetTransfer, SWGSDRangel::SWGRemoteInputReport, SWGSDRangel::SWGRemoteInputSettings, SWGSDRangel::SWGRemoteOutputSettings, SWGSDRangel::SWGRemoteSinkSettings, SWGSDRangel::SWGRemoteSourceSettings, SWGSDRangel::SWGRtlSdrSettings, SWGSDRangel::SWGSamplingDevice, SWGSDRangel::SWGSDRPlaySettings, SWGSDRangel::SWGSSBDemodSettings, SWGSDRangel::SWGSuccessResponse, SWGSDRangel::SWGTestSourceSettings, SWGSDRangel::SWGUDPSinkSettings, SWGSDRangel::SWGUDPSourceSettings, SWGSDRangel::SWGWFMDemodSettings, SWGSDRangel::SWGXtrxInputSettings, SWGSDRangel::SWGXtrxOutputSettings, SWGSDRangel::SWGAMDemodReport, SWGSDRangel::SWGAMModReport, SWGSDRangel::SWGATVModReport, SWGSDRangel::SWGBandwidth, SWGSDRangel::SWGComplex, SWGSDRangel::SWGFreeDVDemodReport, SWGSDRangel::SWGFreeDVModReport, SWGSDRangel::SWGFreqTrackerReport, SWGSDRangel::SWGFrequency, SWGSDRangel::SWGFrequencyRange, SWGSDRangel::SWGGain, SWGSDRangel::SWGGLSpectrum, SWGSDRangel::SWGKiwiSDRReport, SWGSDRangel::SWGLimeSdrInputReport, SWGSDRangel::SWGLimeSdrOutputReport, SWGSDRangel::SWGLocalInputReport, SWGSDRangel::SWGLocalOutputReport, SWGSDRangel::SWGLocationInformation, SWGSDRangel::SWGNFMDemodReport, SWGSDRangel::SWGNFMModReport, SWGSDRangel::SWGRange, SWGSDRangel::SWGRangeFloat, SWGSDRangel::SWGRDSReport_altFrequencies, SWGSDRangel::SWGRemoteOutputReport, SWGSDRangel::SWGRemoteSourceReport, SWGSDRangel::SWGSampleRate, SWGSDRangel::SWGSSBDemodReport, SWGSDRangel::SWGSSBModReport, SWGSDRangel::SWGTestMiStreamSettings, SWGSDRangel::SWGUDPSinkReport, SWGSDRangel::SWGUDPSourceReport, SWGSDRangel::SWGWFMDemodReport, SWGSDRangel::SWGWFMModReport, SWGSDRangel::SWGXtrxInputReport, and SWGSDRangel::SWGXtrxOutputReport.
Definition at line 30 of file SWGObject.h.
Referenced by SWGSDRangel::setValue().
{
         Q_UNUSED(json);
     }
isSet()
virtual bool SWGSDRangel::SWGObject::isSet () inline virtual
Reimplemented in SWGSDRangel::SWGDeviceSettings, SWGSDRangel::SWGDeviceSettings_2, SWGSDRangel::SWGChannelSettings, SWGSDRangel::SWGChannelSettings_2, SWGSDRangel::SWGDeviceReport, SWGSDRangel::SWGFCDProSettings, SWGSDRangel::SWGATVModSettings, SWGSDRangel::SWGLimeSdrInputSettings, SWGSDRangel::SWGDSDDemodSettings, SWGSDRangel::SWGSoapySDRInputSettings, SWGSDRangel::SWGChannelReport, SWGSDRangel::SWGPlutoSdrInputSettings, SWGSDRangel::SWGUDPSinkSettings, SWGSDRangel::SWGUDPSourceSettings, SWGSDRangel::SWGSSBModSettings, SWGSDRangel::SWGSoapySDROutputSettings, SWGSDRangel::SWGXtrxInputSettings, SWGSDRangel::SWGSSBDemodSettings, SWGSDRangel::SWGLimeSdrOutputSettings, SWGSDRangel::SWGTestSourceSettings, SWGSDRangel::SWGGLSpectrum, SWGSDRangel::SWGNFMModSettings, SWGSDRangel::SWGAirspySettings, SWGSDRangel::SWGFCDProPlusSettings, SWGSDRangel::SWGNFMDemodSettings, SWGSDRangel::SWGRtlSdrSettings, SWGSDRangel::SWGSDRPlaySettings, SWGSDRangel::SWGAirspyHFSettings, SWGSDRangel::SWGFreeDVModSettings, SWGSDRangel::SWGWFMModSettings, SWGSDRangel::SWGBladeRF1InputSettings, SWGSDRangel::SWGBladeRF2InputSettings, SWGSDRangel::SWGFreqTrackerSettings, SWGSDRangel::SWGAMModSettings, SWGSDRangel::SWGAMDemodSettings, SWGSDRangel::SWGBFMDemodSettings, SWGSDRangel::SWGHackRFInputSettings, SWGSDRangel::SWGPlutoSdrOutputSettings, SWGSDRangel::SWGTestMiStreamSettings, SWGSDRangel::SWGXtrxOutputSettings, SWGSDRangel::SWGSoapySDRReport, SWGSDRangel::SWGFreeDVDemodSettings, SWGSDRangel::SWGPerseusSettings, SWGSDRangel::SWGRemoteOutputSettings, SWGSDRangel::SWGWFMDemodSettings, SWGSDRangel::SWGRDSReport, SWGSDRangel::SWGBladeRF1OutputSettings, SWGSDRangel::SWGBladeRF2OutputSettings, SWGSDRangel::SWGDSDDemodReport, SWGSDRangel::SWGHackRFOutputSettings, SWGSDRangel::SWGRemoteSinkSettings, SWGSDRangel::SWGRemoteSourceReport, SWGSDRangel::SWGAudioOutputDevice, SWGSDRangel::SWGFileSourceSettings, SWGSDRangel::SWGLimeSdrInputReport, SWGSDRangel::SWGLimeSdrOutputReport, SWGSDRangel::SWGPreset, SWGSDRangel::SWGPreferences, SWGSDRangel::SWGRemoteInputSettings, SWGSDRangel::SWGInstanceSummaryResponse, SWGSDRangel::SWGCWKeyerSettings, SWGSDRangel::SWGKiwiSDRSettings, SWGSDRangel::SWGLocalSinkSettings, SWGSDRangel::SWGLocalSourceSettings, SWGSDRangel::SWGSamplingDevice, SWGSDRangel::SWGArgInfo, SWGSDRangel::SWGDeviceListItem, SWGSDRangel::SWGRemoteSourceSettings, SWGSDRangel::SWGCommand, SWGSDRangel::SWGFileSourceReport, SWGSDRangel::SWGBFMDemodReport, SWGSDRangel::SWGFileInputSettings, SWGSDRangel::SWGLocalInputSettings, SWGSDRangel::SWGTestMISettings, SWGSDRangel::SWGChannel, SWGSDRangel::SWGAudioInputDevice, SWGSDRangel::SWGBladeRF2InputReport, SWGSDRangel::SWGChannelListItem, SWGSDRangel::SWGFileInputReport, SWGSDRangel::SWGRemoteInputReport, SWGSDRangel::SWGSDRPlayReport, SWGSDRangel::SWGInstanceConfigResponse, SWGSDRangel::SWGAudioDevices, SWGSDRangel::SWGNFMDemodReport, SWGSDRangel::SWGUDPSourceReport, SWGSDRangel::SWGXtrxInputReport, SWGSDRangel::SWGXtrxOutputReport, SWGSDRangel::SWGBladeRF2OutputReport, SWGSDRangel::SWGDeviceConfig, SWGSDRangel::SWGLocalOutputSettings, SWGSDRangel::SWGLoggingInfo, SWGSDRangel::SWGPlutoSdrInputReport, SWGSDRangel::SWGPresetIdentifier, SWGSDRangel::SWGAMDemodReport, SWGSDRangel::SWGDeviceSet, SWGSDRangel::SWGFreeDVDemodReport, SWGSDRangel::SWGFreqTrackerReport, SWGSDRangel::SWGPresetGroup, SWGSDRangel::SWGSSBDemodReport, SWGSDRangel::SWGUDPSinkReport, SWGSDRangel::SWGWFMDemodReport, SWGSDRangel::SWGChannelConfig, SWGSDRangel::SWGDeviceSetList, SWGSDRangel::SWGArgValue, SWGSDRangel::SWGFrequencyBand, SWGSDRangel::SWGPlutoSdrOutputReport, SWGSDRangel::SWGPresetImport, SWGSDRangel::SWGPresetItem, SWGSDRangel::SWGAMModReport, SWGSDRangel::SWGFreeDVModReport, SWGSDRangel::SWGFrequencyRange, SWGSDRangel::SWGNFMModReport, SWGSDRangel::SWGRange, SWGSDRangel::SWGRangeFloat, SWGSDRangel::SWGSoapySDRFrequencySetting, SWGSDRangel::SWGSSBModReport, SWGSDRangel::SWGWFMModReport, SWGSDRangel::SWGAMBEDevices, SWGSDRangel::SWGChannelsDetail, SWGSDRangel::SWGDVSerialDevices, SWGSDRangel::SWGInstanceChannelsResponse, SWGSDRangel::SWGInstanceDevicesResponse, SWGSDRangel::SWGPresetExport, SWGSDRangel::SWGPresets, SWGSDRangel::SWGSoapySDRGainSetting, SWGSDRangel::SWGAMBEDevice, SWGSDRangel::SWGNamedEnum, SWGSDRangel::SWGPresetTransfer, SWGSDRangel::SWGATVModReport, SWGSDRangel::SWGComplex, SWGSDRangel::SWGLocalInputReport, SWGSDRangel::SWGLocalOutputReport, SWGSDRangel::SWGLocationInformation, SWGSDRangel::SWGRemoteOutputReport, SWGSDRangel::SWGAirspyHFReport, SWGSDRangel::SWGAirspyReport, SWGSDRangel::SWGPerseusReport, SWGSDRangel::SWGRtlSdrReport, SWGSDRangel::SWGDeviceState, SWGSDRangel::SWGDVSerialDevice, SWGSDRangel::SWGErrorResponse, SWGSDRangel::SWGSuccessResponse, SWGSDRangel::SWGBandwidth, SWGSDRangel::SWGFrequency, SWGSDRangel::SWGGain, SWGSDRangel::SWGKiwiSDRReport, SWGSDRangel::SWGRDSReport_altFrequencies, and SWGSDRangel::SWGSampleRate.
Definition at line 36 of file SWGObject.h.
{
         return false;
     }
The documentation for this class was generated from the following file:
swagger/sdrangel/code/qt5/client/SWGObject.h