SDRAngel: GLShaderTextured Class Reference
GLShaderTextured Class Reference
#include <glshadertextured.h>
Public Member Functions
GLShaderTextured ()
~GLShaderTextured ()
void initializeGL ()
void initTexture (const QImage &image, QOpenGLTexture::WrapMode wrapMode=QOpenGLTexture::Repeat)
void subTexture (int xOffset, int yOffset, int width, int height, const void *pixels)
void drawSurface (const QMatrix4x4 &transformMatrix, GLfloat *textureCoords, GLfloat *vertices, int nbVertices)
void cleanup ()
Private Member Functions
void draw (unsigned int mode, const QMatrix4x4 &transformMatrix, GLfloat *textureCoords, GLfloat *vertices, int nbVertices)
Private Attributes
QOpenGLShaderProgram * m_program
QOpenGLTexture * m_texture
int m_matrixLoc
int m_textureLoc
Static Private Attributes
static const QString m_vertexShaderSourceTextured
static const QString m_fragmentShaderSourceTextured
Detailed Description
Definition at line 35 of file glshadertextured.h.
Constructor & Destructor Documentation
GLShaderTextured()
GLShaderTextured::GLShaderTextured ()
Definition at line 29 of file glshadertextured.cpp.
                                    :
     m_program(0),
     m_texture(0),
     m_matrixLoc(0),
     m_textureLoc(0)
 { }
~GLShaderTextured()
GLShaderTextured::~GLShaderTextured ()
Definition at line 36 of file glshadertextured.cpp.
References cleanup().
 {
     cleanup();
 }
Member Function Documentation
cleanup()
void GLShaderTextured::cleanup ()
Definition at line 117 of file glshadertextured.cpp.
References m_fragmentShaderSourceTextured, m_program, m_texture, and m_vertexShaderSourceTextured.
Referenced by GLScope::cleanup(), GLSpectrum::cleanup(), and ~GLShaderTextured().
 {
     if (m_program)  {
         delete m_program;
         m_program = 0;
     }
     if (m_texture) {
         delete m_texture;
         m_texture = 0;
     }
 }
draw()
void GLShaderTextured::draw (unsigned int mode, const QMatrix4x4 & transformMatrix, GLfloat * textureCoords, GLfloat * vertices, int nbVertices) private
Definition at line 96 of file glshadertextured.cpp.
References m_matrixLoc, m_program, m_texture, and m_textureLoc.
Referenced by drawSurface().
 {
     if (!m_texture) {
         qDebug("GLShaderTextured::draw: no texture defined. Doing nothing");
         return;
     }
     QOpenGLFunctions *f = QOpenGLContext::currentContext()->functions();
     m_program->bind();
     m_program->setUniformValue(m_matrixLoc, transformMatrix);
     m_texture->bind();
     m_program->setUniformValue(m_textureLoc, 0); // Use texture unit 0 which magically contains our texture
     f->glEnableVertexAttribArray(0); // vertex
     f->glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, vertices);
     f->glEnableVertexAttribArray(1); // texture coordinates
     f->glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, 0, textureCoords);
     f->glDrawArrays(mode, 0, nbVertices);
     f->glDisableVertexAttribArray(0);
     m_program->release();
 }
drawSurface()
void GLShaderTextured::drawSurface (const QMatrix4x4 & transformMatrix, GLfloat * textureCoords, GLfloat * vertices, int nbVertices)
Definition at line 91 of file glshadertextured.cpp.
References draw().
Referenced by GLScope::drawChannelOverlay(), GLScope::paintGL(), and GLSpectrum::paintGL().
 {
     draw(GL_TRIANGLE_FAN, transformMatrix, textureCoords, vertices, nbVertices);
 }
initializeGL()
void GLShaderTextured::initializeGL ()
Definition at line 41 of file glshadertextured.cpp.
References m_fragmentShaderSourceTextured, m_matrixLoc, m_program, m_textureLoc, and m_vertexShaderSourceTextured.
Referenced by GLScope::initializeGL(), and GLSpectrum::initializeGL().
 {
     m_program = new QOpenGLShaderProgram;
     if (!m_program->addShaderFromSourceCode(QOpenGLShader::Vertex, m_vertexShaderSourceTextured)) {
         qDebug() << "GLShaderTextured::initializeGL: error in vertex shader: " << m_program->log();
     }
     if (!m_program->addShaderFromSourceCode(QOpenGLShader::Fragment, m_fragmentShaderSourceTextured)) {
         qDebug() << "GLShaderTextured::initializeGL: error in fragment shader: " << m_program->log();
     }
     m_program->bindAttributeLocation("vertex", 0);
     m_program->bindAttributeLocation("texCoord", 1);
     if (!m_program->link()) {
         qDebug() << "GLShaderTextured::initializeGL: error linking shader: " << m_program->log();
     }
     m_program->bind();
     m_matrixLoc = m_program->uniformLocation("uMatrix");
     m_textureLoc = m_program->uniformLocation("uTexture");
     m_program->release();
 }
initTexture()
void GLShaderTextured::initTexture (const QImage & image, QOpenGLTexture::WrapMode wrapMode = QOpenGLTexture::Repeat)
Definition at line 66 of file glshadertextured.cpp.
References m_texture.
Referenced by GLSpectrum::applyChanges(), GLScope::drawChannelOverlay(), GLScope::setHorizontalDisplays(), GLScope::setPolarDisplays(), GLScope::setUniqueDisplays(), and GLScope::setVerticalDisplays().
 {
     if (m_texture) {
         delete m_texture;
     }
     m_texture = new QOpenGLTexture(image);
     m_texture->setMinificationFilter(QOpenGLTexture::Linear);
     m_texture->setMagnificationFilter(QOpenGLTexture::Linear);
     m_texture->setWrapMode(wrapMode);
 }
subTexture()
void GLShaderTextured::subTexture (int xOffset, int yOffset, int width, int height, const void * pixels)
Definition at line 79 of file glshadertextured.cpp.
References m_texture.
Referenced by GLSpectrum::paintGL().
 {
     if (!m_texture) {
         qDebug("GLShaderTextured::subTexture: no texture defined. Doing nothing");
         return;
     }
     QOpenGLFunctions *f = QOpenGLContext::currentContext()->functions();
     m_texture->bind();
     f->glTexSubImage2D(GL_TEXTURE_2D, 0, xOffset, yOffset, width, height, GL_RGBA, GL_UNSIGNED_BYTE, pixels);
 }
Member Data Documentation
m_fragmentShaderSourceTextured
const QString GLShaderTextured::m_fragmentShaderSourceTextured static private
Initial value:
= QString(
        "uniform lowp sampler2D uTexture;\n"
        "varying mediump vec2 texCoordVar;\n"
        "void main() {\n"
        "    gl_FragColor = texture2D(uTexture, texCoordVar);\n"
        "}\n"
        )
Definition at line 55 of file glshadertextured.h.
Referenced by cleanup(), and initializeGL().
m_matrixLoc
int GLShaderTextured::m_matrixLoc private
Definition at line 52 of file glshadertextured.h.
Referenced by draw(), and initializeGL().
m_program
QOpenGLShaderProgram* GLShaderTextured::m_program private
Definition at line 50 of file glshadertextured.h.
Referenced by cleanup(), draw(), and initializeGL().
m_texture
QOpenGLTexture* GLShaderTextured::m_texture private
Definition at line 51 of file glshadertextured.h.
Referenced by cleanup(), draw(), initTexture(), and subTexture().
m_textureLoc
int GLShaderTextured::m_textureLoc private
Definition at line 53 of file glshadertextured.h.
Referenced by draw(), and initializeGL().
m_vertexShaderSourceTextured
const QString GLShaderTextured::m_vertexShaderSourceTextured static private
Initial value:
= QString(
        "uniform highp mat4 uMatrix;\n"
        "attribute highp vec4 vertex;\n"
        "attribute highp vec2 texCoord;\n"
        "varying mediump vec2 texCoordVar;\n"
        "void main() {\n"
        "    gl_Position = uMatrix * vertex;\n"
        "    texCoordVar = texCoord;\n"
        "}\n"
        )
Definition at line 54 of file glshadertextured.h.
Referenced by cleanup(), and initializeGL().
The documentation for this class was generated from the following files:
sdrgui/gui/glshadertextured.h
sdrgui/gui/glshadertextured.cpp