SDRAngel: DeviceEnumerator Class Reference
DeviceEnumerator Class Reference
#include <deviceenumerator.h>
Classes
struct DeviceEnumeration
Public Member Functions
DeviceEnumerator ()
~DeviceEnumerator ()
void enumerateRxDevices (PluginManager *pluginManager)
void enumerateTxDevices (PluginManager *pluginManager)
void enumerateMIMODevices (PluginManager *pluginManager)
void listRxDeviceNames (QList< QString > &list, std::vector< int > &indexes) const
void listTxDeviceNames (QList< QString > &list, std::vector< int > &indexes) const
void listMIMODeviceNames (QList< QString > &list, std::vector< int > &indexes) const
void changeRxSelection (int tabIndex, int deviceIndex)
void changeTxSelection (int tabIndex, int deviceIndex)
void changeMIMOSelection (int tabIndex, int deviceIndex)
void removeRxSelection (int tabIndex)
void removeTxSelection (int tabIndex)
void removeMIMOSelection (int tabIndex)
int getNbRxSamplingDevices () const
int getNbTxSamplingDevices () const
int getNbMIMOSamplingDevices () const
const PluginInterface::SamplingDevice * getRxSamplingDevice (int deviceIndex) const
const PluginInterface::SamplingDevice * getTxSamplingDevice (int deviceIndex) const
const PluginInterface::SamplingDevice * getMIMOSamplingDevice (int deviceIndex) const
PluginInterface * getRxPluginInterface (int deviceIndex)
PluginInterface * getTxPluginInterface (int deviceIndex)
PluginInterface * getMIMOPluginInterface (int deviceIndex)
int getFileInputDeviceIndex () const
Get Rx default device.
int getFileSinkDeviceIndex () const
Get Tx default device.
int getTestMIMODeviceIndex () const
Get MIMO default device.
int getRxSamplingDeviceIndex (const QString &deviceId, int sequence)
int getTxSamplingDeviceIndex (const QString &deviceId, int sequence)
int getMIMOSamplingDeviceIndex (const QString &deviceId, int sequence)
Static Public Member Functions
static DeviceEnumerator * instance ()
Private Types
typedef std::vector< DeviceEnumeration > DevicesEnumeration
Private Attributes
DevicesEnumeration m_rxEnumeration
DevicesEnumeration m_txEnumeration
DevicesEnumeration m_mimoEnumeration
Detailed Description
Definition at line 28 of file deviceenumerator.h.
Member Typedef Documentation
DevicesEnumeration
typedef std::vector<DeviceEnumeration> DeviceEnumerator::DevicesEnumeration private
Definition at line 78 of file deviceenumerator.h.
Constructor & Destructor Documentation
DeviceEnumerator()
DeviceEnumerator::DeviceEnumerator ()
Definition at line 29 of file deviceenumerator.cpp.
 {}
~DeviceEnumerator()
DeviceEnumerator::~DeviceEnumerator ()
Definition at line 32 of file deviceenumerator.cpp.
 {}
Member Function Documentation
changeMIMOSelection()
void DeviceEnumerator::changeMIMOSelection (int tabIndex, int deviceIndex)
Definition at line 172 of file deviceenumerator.cpp.
References m_mimoEnumeration.
Referenced by SamplingDeviceDialog::accept(), and SamplingDeviceControl::setSelectedDeviceIndex().
 {
     for (DevicesEnumeration::iterator it = m_mimoEnumeration.begin(); it != m_mimoEnumeration.end(); ++it)
     {
         if (it->m_samplingDevice.claimed == tabIndex) {
             it->m_samplingDevice.claimed = -1;
         }
         if (it->m_index == deviceIndex) {
             it->m_samplingDevice.claimed = tabIndex;
         }
     }
 }
changeRxSelection()
void DeviceEnumerator::changeRxSelection (int tabIndex, int deviceIndex)
Definition at line 146 of file deviceenumerator.cpp.
References m_rxEnumeration.
Referenced by SamplingDeviceDialog::accept(), and SamplingDeviceControl::setSelectedDeviceIndex().
 {
     for (DevicesEnumeration::iterator it = m_rxEnumeration.begin(); it != m_rxEnumeration.end(); ++it)
     {
         if (it->m_samplingDevice.claimed == tabIndex) {
             it->m_samplingDevice.claimed = -1;
         }
         if (it->m_index == deviceIndex) {
             it->m_samplingDevice.claimed = tabIndex;
         }
     }
 }
changeTxSelection()
void DeviceEnumerator::changeTxSelection (int tabIndex, int deviceIndex)
Definition at line 159 of file deviceenumerator.cpp.
References m_txEnumeration.
Referenced by SamplingDeviceDialog::accept(), and SamplingDeviceControl::setSelectedDeviceIndex().
 {
     for (DevicesEnumeration::iterator it = m_txEnumeration.begin(); it != m_txEnumeration.end(); ++it)
     {
         if (it->m_samplingDevice.claimed == tabIndex) {
             it->m_samplingDevice.claimed = -1;
         }
         if (it->m_index == deviceIndex) {
             it->m_samplingDevice.claimed = tabIndex;
         }
     }
 }
enumerateMIMODevices()
void DeviceEnumerator::enumerateMIMODevices (PluginManager * pluginManager)
Definition at line 85 of file deviceenumerator.cpp.
References PluginManager::getMIMODeviceRegistrations(), i, and m_mimoEnumeration.
Referenced by PluginManager::loadPluginsFinal().
 {
     m_mimoEnumeration.clear();
     PluginAPI::SamplingDeviceRegistrations& mimoDeviceRegistrations = pluginManager->getMIMODeviceRegistrations();
     int index = 0;
     for (int i = 0; i < mimoDeviceRegistrations.count(); i++)
     {
         qDebug("DeviceEnumerator::enumerateMIMODevices: %s", qPrintable(mimoDeviceRegistrations[i].m_deviceId));
         PluginInterface::SamplingDevices samplingDevices = mimoDeviceRegistrations[i].m_plugin->enumSampleMIMO();
         for (int j = 0; j < samplingDevices.count(); j++)
         {
             m_mimoEnumeration.push_back(
                 DeviceEnumeration(
                     samplingDevices[j],
                     mimoDeviceRegistrations[i].m_plugin,
                     index
                 )
             );
             index++;
         }
     }
 }
enumerateRxDevices()
void DeviceEnumerator::enumerateRxDevices (PluginManager * pluginManager)
Definition at line 35 of file deviceenumerator.cpp.
References PluginManager::getSourceDeviceRegistrations(), i, and m_rxEnumeration.
Referenced by PluginManager::loadPluginsFinal().
 {
     m_rxEnumeration.clear();
     PluginAPI::SamplingDeviceRegistrations& rxDeviceRegistrations = pluginManager->getSourceDeviceRegistrations();
     int index = 0;
     for (int i = 0; i < rxDeviceRegistrations.count(); i++)
     {
         qDebug("DeviceEnumerator::enumerateRxDevices: %s", qPrintable(rxDeviceRegistrations[i].m_deviceId));
         PluginInterface::SamplingDevices samplingDevices = rxDeviceRegistrations[i].m_plugin->enumSampleSources();
         for (int j = 0; j < samplingDevices.count(); j++)
         {
             m_rxEnumeration.push_back(
                 DeviceEnumeration(
                     samplingDevices[j],
                     rxDeviceRegistrations[i].m_plugin,
                     index
                 )
             );
             index++;
         }
     }
 }
enumerateTxDevices()
void DeviceEnumerator::enumerateTxDevices (PluginManager * pluginManager)
Definition at line 60 of file deviceenumerator.cpp.
References PluginManager::getSinkDeviceRegistrations(), i, and m_txEnumeration.
Referenced by PluginManager::loadPluginsFinal().
 {
     m_txEnumeration.clear();
     PluginAPI::SamplingDeviceRegistrations& txDeviceRegistrations = pluginManager->getSinkDeviceRegistrations();
     int index = 0;
     for (int i = 0; i < txDeviceRegistrations.count(); i++)
     {
         qDebug("DeviceEnumerator::enumerateTxDevices: %s", qPrintable(txDeviceRegistrations[i].m_deviceId));
         PluginInterface::SamplingDevices samplingDevices = txDeviceRegistrations[i].m_plugin->enumSampleSinks();
         for (int j = 0; j < samplingDevices.count(); j++)
         {
             m_txEnumeration.push_back(
                 DeviceEnumeration(
                     samplingDevices[j],
                     txDeviceRegistrations[i].m_plugin,
                     index
                 )
             );
             index++;
         }
     }
 }
getFileInputDeviceIndex()
int DeviceEnumerator::getFileInputDeviceIndex () const
Get Rx default device.
Definition at line 215 of file deviceenumerator.cpp.
References PluginManager::getFileInputDeviceId(), and m_rxEnumeration.
Referenced by MainCore::addSourceDevice(), and MainWindow::addSourceDevice().
 {
     for (DevicesEnumeration::const_iterator it = m_rxEnumeration.begin(); it != m_rxEnumeration.end(); ++it)
     {
         if (it->m_samplingDevice.id == PluginManager::getFileInputDeviceId()) {
             return it->m_index;
         }
     }
     return -1;
 }
getFileSinkDeviceIndex()
int DeviceEnumerator::getFileSinkDeviceIndex () const
Get Tx default device.
Definition at line 227 of file deviceenumerator.cpp.
References PluginManager::getFileSinkDeviceId(), and m_txEnumeration.
Referenced by MainCore::addSinkDevice(), and MainWindow::addSinkDevice().
 {
     for (DevicesEnumeration::const_iterator it = m_txEnumeration.begin(); it != m_txEnumeration.end(); ++it)
     {
         if (it->m_samplingDevice.id == PluginManager::getFileSinkDeviceId()) {
             return it->m_index;
         }
     }
     return -1;
 }
getMIMOPluginInterface()
PluginInterface* DeviceEnumerator::getMIMOPluginInterface (int deviceIndex) inline
Definition at line 56 of file deviceenumerator.h.
 { return m_mimoEnumeration[deviceIndex].m_pluginInterface; }
getMIMOSamplingDevice()
const PluginInterface::SamplingDevice* DeviceEnumerator::getMIMOSamplingDevice (int deviceIndex) const inline
Definition at line 53 of file deviceenumerator.h.
Referenced by MainWindow::addMIMODevice(), DeviceUserArgsDialog::DeviceUserArgsDialog(), MainWindow::sampleMIMOChanged(), and SamplingDeviceControl::setSelectedDeviceIndex().
 { return &m_mimoEnumeration[deviceIndex].m_samplingDevice; }
getMIMOSamplingDeviceIndex()
int DeviceEnumerator::getMIMOSamplingDeviceIndex (const QString & deviceId, int sequence)
Definition at line 275 of file deviceenumerator.cpp.
References m_mimoEnumeration.
 {
     for (DevicesEnumeration::iterator it = m_mimoEnumeration.begin(); it != m_mimoEnumeration.end(); ++it)
     {
         if ((it->m_samplingDevice.id == deviceId) && (it->m_samplingDevice.sequence == sequence)) {
             return it->m_index;
         }
     }
     return -1;
 }
getNbMIMOSamplingDevices()
int DeviceEnumerator::getNbMIMOSamplingDevices () const inline
Definition at line 50 of file deviceenumerator.h.
Referenced by DeviceUserArgsDialog::DeviceUserArgsDialog().
 { return m_mimoEnumeration.size(); }
getNbRxSamplingDevices()
int DeviceEnumerator::getNbRxSamplingDevices () const inline
Definition at line 48 of file deviceenumerator.h.
Referenced by WebAPIAdapterGUI::devicesetDevicePut(), WebAPIAdapterSrv::devicesetDevicePut(), DeviceUserArgsDialog::DeviceUserArgsDialog(), WebAPIAdapterSrv::instanceDevices(), and WebAPIAdapterGUI::instanceDevices().
 { return m_rxEnumeration.size(); }
getNbTxSamplingDevices()
int DeviceEnumerator::getNbTxSamplingDevices () const inline
Definition at line 49 of file deviceenumerator.h.
Referenced by WebAPIAdapterGUI::devicesetDevicePut(), WebAPIAdapterSrv::devicesetDevicePut(), DeviceUserArgsDialog::DeviceUserArgsDialog(), WebAPIAdapterSrv::instanceDevices(), and WebAPIAdapterGUI::instanceDevices().
 { return m_txEnumeration.size(); }
getRxPluginInterface()
PluginInterface* DeviceEnumerator::getRxPluginInterface (int deviceIndex) inline
Definition at line 54 of file deviceenumerator.h.
 { return m_rxEnumeration[deviceIndex].m_pluginInterface; }
getRxSamplingDevice()
const PluginInterface::SamplingDevice* DeviceEnumerator::getRxSamplingDevice (int deviceIndex) const inline
Definition at line 51 of file deviceenumerator.h.
Referenced by MainCore::addSourceDevice(), MainWindow::addSourceDevice(), MainCore::changeSampleSource(), WebAPIAdapterGUI::devicesetDevicePut(), WebAPIAdapterSrv::devicesetDevicePut(), DeviceUserArgsDialog::DeviceUserArgsDialog(), WebAPIAdapterSrv::instanceDevices(), WebAPIAdapterGUI::instanceDevices(), MainWindow::sampleSourceChanged(), and SamplingDeviceControl::setSelectedDeviceIndex().
 { return &m_rxEnumeration[deviceIndex].m_samplingDevice; }
getRxSamplingDeviceIndex()
int DeviceEnumerator::getRxSamplingDeviceIndex (const QString & deviceId, int sequence)
Definition at line 251 of file deviceenumerator.cpp.
References m_rxEnumeration.
Referenced by MainWindow::MainWindow().
 {
     for (DevicesEnumeration::iterator it = m_rxEnumeration.begin(); it != m_rxEnumeration.end(); ++it)
     {
         if ((it->m_samplingDevice.id == deviceId) && (it->m_samplingDevice.sequence == sequence)) {
             return it->m_index;
         }
     }
     return -1;
 }
getTestMIMODeviceIndex()
int DeviceEnumerator::getTestMIMODeviceIndex () const
Get MIMO default device.
Definition at line 239 of file deviceenumerator.cpp.
References PluginManager::getTestMIMODeviceId(), and m_mimoEnumeration.
Referenced by MainWindow::addMIMODevice().
 {
     for (DevicesEnumeration::const_iterator it = m_mimoEnumeration.begin(); it != m_mimoEnumeration.end(); ++it)
     {
         if (it->m_samplingDevice.id == PluginManager::getTestMIMODeviceId()) {
             return it->m_index;
         }
     }
     return -1;
 }
getTxPluginInterface()
PluginInterface* DeviceEnumerator::getTxPluginInterface (int deviceIndex) inline
Definition at line 55 of file deviceenumerator.h.
 { return m_txEnumeration[deviceIndex].m_pluginInterface; }
getTxSamplingDevice()
const PluginInterface::SamplingDevice* DeviceEnumerator::getTxSamplingDevice (int deviceIndex) const inline
Definition at line 52 of file deviceenumerator.h.
Referenced by MainCore::addSinkDevice(), MainWindow::addSinkDevice(), MainCore::changeSampleSink(), WebAPIAdapterGUI::devicesetDevicePut(), WebAPIAdapterSrv::devicesetDevicePut(), DeviceUserArgsDialog::DeviceUserArgsDialog(), WebAPIAdapterSrv::instanceDevices(), WebAPIAdapterGUI::instanceDevices(), MainWindow::sampleSinkChanged(), and SamplingDeviceControl::setSelectedDeviceIndex().
 { return &m_txEnumeration[deviceIndex].m_samplingDevice; }
getTxSamplingDeviceIndex()
int DeviceEnumerator::getTxSamplingDeviceIndex (const QString & deviceId, int sequence)
Definition at line 263 of file deviceenumerator.cpp.
References m_txEnumeration.
 {
     for (DevicesEnumeration::iterator it = m_txEnumeration.begin(); it != m_txEnumeration.end(); ++it)
     {
         if ((it->m_samplingDevice.id == deviceId) && (it->m_samplingDevice.sequence == sequence)) {
             return it->m_index;
         }
     }
     return -1;
 }
instance()
DeviceEnumerator * DeviceEnumerator::instance () static
Definition at line 24 of file deviceenumerator.cpp.
Referenced by SamplingDeviceDialog::accept(), MainWindow::addMIMODevice(), MainCore::addSinkDevice(), MainWindow::addSinkDevice(), MainCore::addSourceDevice(), MainWindow::addSourceDevice(), MainCore::changeSampleSink(), MainCore::changeSampleSource(), WebAPIAdapterGUI::devicesetDevicePut(), WebAPIAdapterSrv::devicesetDevicePut(), WebAPIAdapterSrv::instanceDevices(), WebAPIAdapterGUI::instanceDevices(), PluginManager::loadPluginsFinal(), MainWindow::MainWindow(), MainWindow::on_action_DeviceUserArguments_triggered(), SamplingDeviceControl::removeSelectedDeviceIndex(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), MainWindow::sampleSourceChanged(), SamplingDeviceDialog::SamplingDeviceDialog(), and SamplingDeviceControl::setSelectedDeviceIndex().
 {
     return deviceEnumerator;
 }
listMIMODeviceNames()
void DeviceEnumerator::listMIMODeviceNames (QList< QString > & list, std::vector< int > & indexes) const
Definition at line 134 of file deviceenumerator.cpp.
References PluginInterface::SamplingDevice::BuiltInDevice, and m_mimoEnumeration.
Referenced by SamplingDeviceDialog::SamplingDeviceDialog().
 {
     for (DevicesEnumeration::const_iterator it = m_mimoEnumeration.begin(); it != m_mimoEnumeration.end(); ++it)
     {
         if ((it->m_samplingDevice.claimed < 0) || (it->m_samplingDevice.type == PluginInterface::SamplingDevice::BuiltInDevice))
         {
             list.append(it->m_samplingDevice.displayedName);
             indexes.push_back(it->m_index);
         }
     }
 }
listRxDeviceNames()
void DeviceEnumerator::listRxDeviceNames (QList< QString > & list, std::vector< int > & indexes) const
Definition at line 110 of file deviceenumerator.cpp.
References PluginInterface::SamplingDevice::BuiltInDevice, and m_rxEnumeration.
Referenced by SamplingDeviceDialog::SamplingDeviceDialog().
 {
     for (DevicesEnumeration::const_iterator it = m_rxEnumeration.begin(); it != m_rxEnumeration.end(); ++it)
     {
         if ((it->m_samplingDevice.claimed < 0) || (it->m_samplingDevice.type == PluginInterface::SamplingDevice::BuiltInDevice))
         {
             list.append(it->m_samplingDevice.displayedName);
             indexes.push_back(it->m_index);
         }
     }
 }
listTxDeviceNames()
void DeviceEnumerator::listTxDeviceNames (QList< QString > & list, std::vector< int > & indexes) const
Definition at line 122 of file deviceenumerator.cpp.
References PluginInterface::SamplingDevice::BuiltInDevice, and m_txEnumeration.
Referenced by SamplingDeviceDialog::SamplingDeviceDialog().
 {
     for (DevicesEnumeration::const_iterator it = m_txEnumeration.begin(); it != m_txEnumeration.end(); ++it)
     {
         if ((it->m_samplingDevice.claimed < 0) || (it->m_samplingDevice.type == PluginInterface::SamplingDevice::BuiltInDevice))
         {
             list.append(it->m_samplingDevice.displayedName);
             indexes.push_back(it->m_index);
         }
     }
 }
removeMIMOSelection()
void DeviceEnumerator::removeMIMOSelection (int tabIndex)
Definition at line 205 of file deviceenumerator.cpp.
References m_mimoEnumeration.
 {
     for (DevicesEnumeration::iterator it = m_mimoEnumeration.begin(); it != m_mimoEnumeration.end(); ++it)
     {
         if (it->m_samplingDevice.claimed == tabIndex) {
             it->m_samplingDevice.claimed = -1;
         }
     }
 }
removeRxSelection()
void DeviceEnumerator::removeRxSelection (int tabIndex)
Definition at line 185 of file deviceenumerator.cpp.
References m_rxEnumeration.
Referenced by SamplingDeviceControl::removeSelectedDeviceIndex().
 {
     for (DevicesEnumeration::iterator it = m_rxEnumeration.begin(); it != m_rxEnumeration.end(); ++it)
     {
         if (it->m_samplingDevice.claimed == tabIndex) {
             it->m_samplingDevice.claimed = -1;
         }
     }
 }
removeTxSelection()
void DeviceEnumerator::removeTxSelection (int tabIndex)
Definition at line 195 of file deviceenumerator.cpp.
References m_txEnumeration.
Referenced by SamplingDeviceControl::removeSelectedDeviceIndex().
 {
     for (DevicesEnumeration::iterator it = m_txEnumeration.begin(); it != m_txEnumeration.end(); ++it)
     {
         if (it->m_samplingDevice.claimed == tabIndex) {
             it->m_samplingDevice.claimed = -1;
         }
     }
 }
Member Data Documentation
m_mimoEnumeration
DevicesEnumeration DeviceEnumerator::m_mimoEnumeration private
Definition at line 82 of file deviceenumerator.h.
Referenced by changeMIMOSelection(), enumerateMIMODevices(), getMIMOSamplingDeviceIndex(), getTestMIMODeviceIndex(), listMIMODeviceNames(), and removeMIMOSelection().
m_rxEnumeration
DevicesEnumeration DeviceEnumerator::m_rxEnumeration private
Definition at line 80 of file deviceenumerator.h.
Referenced by changeRxSelection(), enumerateRxDevices(), getFileInputDeviceIndex(), getRxSamplingDeviceIndex(), listRxDeviceNames(), and removeRxSelection().
m_txEnumeration
DevicesEnumeration DeviceEnumerator::m_txEnumeration private
Definition at line 81 of file deviceenumerator.h.
Referenced by changeTxSelection(), enumerateTxDevices(), getFileSinkDeviceIndex(), getTxSamplingDeviceIndex(), listTxDeviceNames(), and removeTxSelection().
The documentation for this class was generated from the following files:
sdrbase/device/deviceenumerator.h
sdrbase/device/deviceenumerator.cpp