SDRAngel: FileSinkOutput::MsgConfigureFileSink Class Reference
FileSinkOutput::MsgConfigureFileSink Class Reference
#include <filesinkoutput.h>
Public Member Functions
const FileSinkSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureFileSink * create (const FileSinkSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureFileSink (const FileSinkSettings &settings, bool force)
Private Attributes
FileSinkSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 35 of file filesinkoutput.h.
Constructor & Destructor Documentation
MsgConfigureFileSink()
FileSinkOutput::MsgConfigureFileSink::MsgConfigureFileSink (const FileSinkSettings & settings, bool force) inline private
Definition at line 51 of file filesinkoutput.h.
Referenced by create().
                                                                            :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureFileSink* FileSinkOutput::MsgConfigureFileSink::create (const FileSinkSettings & settings, bool force) inline static
Definition at line 42 of file filesinkoutput.h.
References MsgConfigureFileSink().
Referenced by FileSinkOutput::deserialize(), FileSinkOutput::setCenterFrequency(), and FileSinkGui::updateHardware().
         {
             return new MsgConfigureFileSink(settings, force);
         }
getForce()
bool FileSinkOutput::MsgConfigureFileSink::getForce () const inline
Definition at line 40 of file filesinkoutput.h.
References m_force.
Referenced by FileSinkOutput::handleMessage().
 { return m_force; }
getSettings()
const FileSinkSettings& FileSinkOutput::MsgConfigureFileSink::getSettings () const inline
Definition at line 39 of file filesinkoutput.h.
References m_settings.
Referenced by FileSinkGui::handleMessage(), and FileSinkOutput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool FileSinkOutput::MsgConfigureFileSink::m_force private
Definition at line 49 of file filesinkoutput.h.
Referenced by getForce().
m_settings
FileSinkSettings FileSinkOutput::MsgConfigureFileSink::m_settings private
Definition at line 48 of file filesinkoutput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesink/filesink/filesinkoutput.h