SDRAngel: HackRFOutputThread Class Reference
HackRFOutputThread Class Reference
#include <hackrfoutputthread.h>
Inherits QThread.
Public Member Functions
HackRFOutputThread (hackrf_device *dev, SampleSourceFifo *sampleFifo, QObject *parent=NULL)
~HackRFOutputThread ()
void startWork ()
void stopWork ()
void setLog2Interpolation (unsigned int log2_interp)
void setFcPos (int fcPos)
Private Member Functions
void run ()
void callback (qint8 *buf, qint32 len)
Static Private Member Functions
static int tx_callback (hackrf_transfer *transfer)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
hackrf_device * m_dev
qint8 m_buf [2 *HACKRF_BLOCKSIZE]
SampleSourceFifo * m_sampleFifo
unsigned int m_log2Interp
int m_fcPos
Interpolators< qint8, SDR_TX_SAMP_SZ, 8 > m_interpolators
Detailed Description
Definition at line 31 of file hackrfoutputthread.h.
Constructor & Destructor Documentation
HackRFOutputThread()
HackRFOutputThread::HackRFOutputThread (hackrf_device * dev, SampleSourceFifo * sampleFifo, QObject * parent = NULL)
Definition at line 25 of file hackrfoutputthread.cpp.
References HACKRF_BLOCKSIZE, and m_buf.
                                                                                                         :
     QThread(parent),
     m_running(false),
     m_dev(dev),
     m_sampleFifo(sampleFifo),
     m_log2Interp(0),
     m_fcPos(2)
 {
     std::fill(m_buf, m_buf + 2*HACKRF_BLOCKSIZE, 0);
 }
~HackRFOutputThread()
HackRFOutputThread::~HackRFOutputThread ()
Definition at line 36 of file hackrfoutputthread.cpp.
References stopWork().
 {
     stopWork();
 }
Member Function Documentation
callback()
void HackRFOutputThread::callback (qint8 * buf, qint32 len) private
Definition at line 119 of file hackrfoutputthread.cpp.
References Interpolators< T, SdrBits, OutputBits >::interpolate1(), Interpolators< T, SdrBits, OutputBits >::interpolate16_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate16_inf(), Interpolators< T, SdrBits, OutputBits >::interpolate16_sup(), Interpolators< T, SdrBits, OutputBits >::interpolate2_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate2_inf(), Interpolators< T, SdrBits, OutputBits >::interpolate2_sup(), Interpolators< T, SdrBits, OutputBits >::interpolate32_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate32_inf(), Interpolators< T, SdrBits, OutputBits >::interpolate32_sup(), Interpolators< T, SdrBits, OutputBits >::interpolate4_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate4_inf(), Interpolators< T, SdrBits, OutputBits >::interpolate4_sup(), Interpolators< T, SdrBits, OutputBits >::interpolate64_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate64_inf(), Interpolators< T, SdrBits, OutputBits >::interpolate64_sup(), Interpolators< T, SdrBits, OutputBits >::interpolate8_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate8_inf(), Interpolators< T, SdrBits, OutputBits >::interpolate8_sup(), m_fcPos, m_interpolators, m_log2Interp, m_sampleFifo, and SampleSourceFifo::readAdvance().
Referenced by tx_callback().
 {
     SampleVector::iterator beginRead;
     m_sampleFifo->readAdvance(beginRead, len/(2*(1<<m_log2Interp)));
     beginRead -= len/2;
     if (m_log2Interp == 0)
     {
         m_interpolators.interpolate1(&beginRead, buf, len);
     }
     else
     {
         if (m_fcPos == 0) // Infra
         {
             switch (m_log2Interp)
             {
             case 1:
                 m_interpolators.interpolate2_inf(&beginRead, buf, len);
                 break;
             case 2:
                 m_interpolators.interpolate4_inf(&beginRead, buf, len);
                 break;
             case 3:
                 m_interpolators.interpolate8_inf(&beginRead, buf, len);
                 break;
             case 4:
                 m_interpolators.interpolate16_inf(&beginRead, buf, len);
                 break;
             case 5:
                 m_interpolators.interpolate32_inf(&beginRead, buf, len);
                 break;
             case 6:
                 m_interpolators.interpolate64_inf(&beginRead, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 1) // Supra
         {
             switch (m_log2Interp)
             {
             case 1:
                 m_interpolators.interpolate2_sup(&beginRead, buf, len);
                 break;
             case 2:
                 m_interpolators.interpolate4_sup(&beginRead, buf, len);
                 break;
             case 3:
                 m_interpolators.interpolate8_sup(&beginRead, buf, len);
                 break;
             case 4:
                 m_interpolators.interpolate16_sup(&beginRead, buf, len);
                 break;
             case 5:
                 m_interpolators.interpolate32_sup(&beginRead, buf, len);
                 break;
             case 6:
                 m_interpolators.interpolate64_sup(&beginRead, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 2) // Center
         {
             switch (m_log2Interp)
             {
             case 1:
                 m_interpolators.interpolate2_cen(&beginRead, buf, len);
                 break;
             case 2:
                 m_interpolators.interpolate4_cen(&beginRead, buf, len);
                 break;
             case 3:
                 m_interpolators.interpolate8_cen(&beginRead, buf, len);
                 break;
             case 4:
                 m_interpolators.interpolate16_cen(&beginRead, buf, len);
                 break;
             case 5:
                 m_interpolators.interpolate32_cen(&beginRead, buf, len);
                 break;
             case 6:
                 m_interpolators.interpolate64_cen(&beginRead, buf, len);
                 break;
             default:
                 break;
             }
         }
     }
 }
run()
void HackRFOutputThread::run () private
Definition at line 68 of file hackrfoutputthread.cpp.
References m_dev, m_running, m_startWaiter, and tx_callback().
 {
     hackrf_error rc;
     m_running = true;
     m_startWaiter.wakeAll();
     if (hackrf_is_streaming(m_dev) == HACKRF_TRUE)
     {
         qDebug("HackRFInputThread::run: HackRF is streaming already");
     }
     else
     {
         qDebug("HackRFInputThread::run: HackRF is not streaming");
         rc = (hackrf_error) hackrf_start_tx(m_dev, tx_callback, this);
         if (rc == HACKRF_SUCCESS)
         {
             qDebug("HackRFOutputThread::run: started HackRF Tx");
         }
         else
         {
             qDebug("HackRFOutputThread::run: failed to start HackRF Tx: %s", hackrf_error_name(rc));
         }
     }
     while ((m_running) && (hackrf_is_streaming(m_dev) == HACKRF_TRUE))
     {
         usleep(200000);
     }
     if (hackrf_is_streaming(m_dev) == HACKRF_TRUE)
     {
         rc = (hackrf_error) hackrf_stop_tx(m_dev);
         if (rc == HACKRF_SUCCESS)
         {
             qDebug("HackRFOutputThread::run: stopped HackRF Tx");
         }
         else
         {
             qDebug("HackRFOutputThread::run: failed to stop HackRF Tx: %s", hackrf_error_name(rc));
         }
     }
     m_running = false;
 }
setFcPos()
void HackRFOutputThread::setFcPos (int fcPos)
Definition at line 63 of file hackrfoutputthread.cpp.
References m_fcPos.
Referenced by HackRFOutput::applySettings(), and HackRFOutput::start().
 {
     m_fcPos = fcPos;
 }
setLog2Interpolation()
void HackRFOutputThread::setLog2Interpolation (unsigned int log2_interp)
Definition at line 58 of file hackrfoutputthread.cpp.
References m_log2Interp.
Referenced by HackRFOutput::applySettings(), and HackRFOutput::start().
 {
     m_log2Interp = log2Interp;
 }
startWork()
void HackRFOutputThread::startWork ()
Definition at line 41 of file hackrfoutputthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by HackRFOutput::applySettings(), and HackRFOutput::start().
 {
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void HackRFOutputThread::stopWork ()
Definition at line 50 of file hackrfoutputthread.cpp.
References m_running.
Referenced by HackRFOutput::applySettings(), HackRFOutput::stop(), and ~HackRFOutputThread().
 {
     if (!m_running) return;
     qDebug("HackRFOutputThread::stopWork");
     m_running = false;
     wait();
 }
tx_callback()
int HackRFOutputThread::tx_callback (hackrf_transfer * transfer) static private
Definition at line 212 of file hackrfoutputthread.cpp.
References callback().
Referenced by run().
 {
     HackRFOutputThread *thread = (HackRFOutputThread *) transfer->tx_ctx;
     qint32 bytes_to_write = transfer->valid_length;
     thread->callback((qint8 *) transfer->buffer, bytes_to_write);
     return 0;
 }
Member Data Documentation
m_buf
qint8 HackRFOutputThread::m_buf[2 *HACKRF_BLOCKSIZE] private
Definition at line 49 of file hackrfoutputthread.h.
Referenced by HackRFOutputThread().
m_dev
hackrf_device* HackRFOutputThread::m_dev private
Definition at line 48 of file hackrfoutputthread.h.
Referenced by run().
m_fcPos
int HackRFOutputThread::m_fcPos private
Definition at line 53 of file hackrfoutputthread.h.
Referenced by callback(), and setFcPos().
m_interpolators
Interpolators<qint8, SDR_TX_SAMP_SZ, 8> HackRFOutputThread::m_interpolators private
Definition at line 55 of file hackrfoutputthread.h.
Referenced by callback().
m_log2Interp
unsigned int HackRFOutputThread::m_log2Interp private
Definition at line 52 of file hackrfoutputthread.h.
Referenced by callback(), and setLog2Interpolation().
m_running
bool HackRFOutputThread::m_running private
Definition at line 46 of file hackrfoutputthread.h.
Referenced by run(), startWork(), and stopWork().
m_sampleFifo
SampleSourceFifo* HackRFOutputThread::m_sampleFifo private
Definition at line 50 of file hackrfoutputthread.h.
Referenced by callback().
m_startWaiter
QWaitCondition HackRFOutputThread::m_startWaiter private
Definition at line 45 of file hackrfoutputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex HackRFOutputThread::m_startWaitMutex private
Definition at line 44 of file hackrfoutputthread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/samplesink/hackrfoutput/hackrfoutputthread.h
plugins/samplesink/hackrfoutput/hackrfoutputthread.cpp