SDRAngel: qrtplib::RTPAddress Class Reference
qrtplib::RTPAddress Class Reference
#include <rtpaddress.h>
Public Member Functions
RTPAddress ()
RTPAddress (const QHostAddress &address, uint16_t port)
QAbstractSocket::NetworkLayerProtocol GetAddressType () const
RTPAddress * CreateCopy () const
bool IsSameAddress (const RTPAddress *addr) const
bool IsFromSameHost (const RTPAddress *addr) const
bool operator== (const RTPAddress &otherAddress) const
const QHostAddress & getAddress () const
void setAddress (const QHostAddress &address)
uint16_t getPort () const
void setPort (uint16_t port)
uint16_t getRtcpsendport () const
void setRtcpsendport (uint16_t rtcpsendport)
Private Attributes
QHostAddress address
uint16_t port
uint16_t rtcpsendport
Detailed Description
This class is an abstract class which is used to specify destinations, multicast groups etc.
Definition at line 52 of file rtpaddress.h.
Constructor & Destructor Documentation
RTPAddress() [1/2]
qrtplib::RTPAddress::RTPAddress () inline
Default constructor. Address and port set via setters
Definition at line 56 of file rtpaddress.h.
Referenced by CreateCopy().
                  : port(0), rtcpsendport(0)
     {}
RTPAddress() [2/2]
qrtplib::RTPAddress::RTPAddress (const QHostAddress & address, uint16_t port) inline
Constructor with address and port
Definition at line 60 of file rtpaddress.h.
                                                            :
         address(address),
         port(port),
         rtcpsendport(0)
     {}
Member Function Documentation
CreateCopy()
RTPAddress * qrtplib::RTPAddress::CreateCopy () const
Creates a copy of the RTPAddress instance. Creates a copy of the RTPAddress instance. If mgr is not NULL, the corresponding memory manager will be used to allocate the memory for the address copy.
Definition at line 38 of file rtpaddress.cpp.
References address, port, rtcpsendport, and RTPAddress().
Referenced by qrtplib::RTPInternalSourceData::SetRTCPDataAddress(), qrtplib::RTPInternalSourceData::SetRTPDataAddress(), and qrtplib::RTPCollisionList::UpdateAddress().
 {
     RTPAddress *a = new RTPAddress();
     a->address = address;
     a->port = port;
     a->rtcpsendport = rtcpsendport;
     return a;
 }
getAddress()
const QHostAddress& qrtplib::RTPAddress::getAddress () const inline
Get host address
Definition at line 100 of file rtpaddress.h.
Referenced by qrtplib::RTPUDPTransmitter::ComesFromThisTransmitter(), qrtplib::RTPUDPTransmitter::JoinMulticastGroup(), and qrtplib::RTPUDPTransmitter::LeaveMulticastGroup().
     {
         return address;
     }
GetAddressType()
QAbstractSocket::NetworkLayerProtocol qrtplib::RTPAddress::GetAddressType () const inline
Returns the type of address the actual implementation represents.
Definition at line 67 of file rtpaddress.h.
References leansdr::operator==().
     {
         return address.protocol();
     }
getPort()
uint16_t qrtplib::RTPAddress::getPort () const inline
Get RTP port
Definition at line 112 of file rtpaddress.h.
Referenced by qrtplib::RTPUDPTransmitter::ComesFromThisTransmitter().
     {
         return port;
     }
getRtcpsendport()
uint16_t qrtplib::RTPAddress::getRtcpsendport () const inline
Get RTCP port
Definition at line 124 of file rtpaddress.h.
Referenced by qrtplib::RTPUDPTransmitter::ComesFromThisTransmitter().
     {
         return rtcpsendport;
     }
IsFromSameHost()
bool qrtplib::RTPAddress::IsFromSameHost (const RTPAddress * addr) const
Checks if the address addr represents the same host as this instance. Checks if the address addr represents the same host as this instance. Implementations must be able to handle a NULL argument.
Note that this function is only used for received packets.
Definition at line 67 of file rtpaddress.cpp.
References address.
Referenced by qrtplib::RTPSources::CheckCollision().
 {
     if (addr == 0) {
         return false;
     }
     if (addr->address.protocol() != address.protocol()) {
         return false;
     }
     return addr->address == address;
 }
IsSameAddress()
bool qrtplib::RTPAddress::IsSameAddress (const RTPAddress * addr) const
Checks if the address addr is the same address as the one this instance represents. Checks if the address addr is the same address as the one this instance represents. Implementations must be able to handle a NULL argument.
Note that this function is only used for received packets, and for those the rtcpsendport variable is not important and should be ignored.
Definition at line 47 of file rtpaddress.cpp.
References address, and port.
Referenced by qrtplib::RTPSources::CheckCollision(), and operator==().
 {
     if (addr == 0) {
         return false;
     }
     if (addr->address.protocol() != address.protocol()) {
         return false;
     }
     if (addr->address == address)
     {
         return addr->port == port;
     }
     else
     {
         return false;
     }
 }
operator==()
bool qrtplib::RTPAddress::operator== (const RTPAddress & otherAddress) const
Equality
Definition at line 80 of file rtpaddress.cpp.
References IsSameAddress().
 {
     return IsSameAddress(&otherAddress);
 }
setAddress()
void qrtplib::RTPAddress::setAddress (const QHostAddress & address) inline
Set host address
Definition at line 106 of file rtpaddress.h.
Referenced by qrtplib::RTPUDPTransmitter::readRTCPPendingDatagrams(), and qrtplib::RTPUDPTransmitter::readRTPPendingDatagrams().
     {
         this->address = address;
     }
setPort()
void qrtplib::RTPAddress::setPort (uint16_t port) inline
Set RTP port
Definition at line 118 of file rtpaddress.h.
Referenced by qrtplib::RTPUDPTransmitter::readRTCPPendingDatagrams(), and qrtplib::RTPUDPTransmitter::readRTPPendingDatagrams().
     {
         this->port = port;
     }
setRtcpsendport()
void qrtplib::RTPAddress::setRtcpsendport (uint16_t rtcpsendport) inline
Set RTCP port
Definition at line 130 of file rtpaddress.h.
     {
         this->rtcpsendport = rtcpsendport;
     }
Member Data Documentation
address
QHostAddress qrtplib::RTPAddress::address private
Definition at line 136 of file rtpaddress.h.
Referenced by CreateCopy(), IsFromSameHost(), and IsSameAddress().
port
uint16_t qrtplib::RTPAddress::port private
Definition at line 137 of file rtpaddress.h.
Referenced by CreateCopy(), and IsSameAddress().
rtcpsendport
uint16_t qrtplib::RTPAddress::rtcpsendport private
Definition at line 138 of file rtpaddress.h.
Referenced by CreateCopy().
The documentation for this class was generated from the following files:
qrtplib/rtpaddress.h
qrtplib/rtpaddress.cpp