SDRAngel: RemoteInputUDPHandler Class Reference
RemoteInputUDPHandler Class Reference
#include <remoteinputudphandler.h>
Inherits QObject.
Public Slots
void dataReadyRead ()
Public Member Functions
RemoteInputUDPHandler (SampleSinkFifo *sampleFifo, DeviceAPI *deviceAPI)
~RemoteInputUDPHandler ()
void setMessageQueueToGUI (MessageQueue *queue)
void start ()
void stop ()
void configureUDPLink (const QString &address, quint16 port)
void getRemoteAddress (QString &s) const
int getNbOriginalBlocks () const
bool isStreaming () const
int getSampleRate () const
int getCenterFrequency () const
int getBufferGauge () const
uint64_t getTVmSec () const
int getMinNbBlocks ()
int getMaxNbRecovery ()
Private Slots
void tick ()
Private Member Functions
void connectTimer ()
void disconnectTimer ()
void processData ()
Private Attributes
DeviceAPI * m_deviceAPI
const QTimer & m_masterTimer
bool m_masterTimerConnected
bool m_running
uint32_t m_rateDivider
RemoteInputBuffer m_remoteInputBuffer
QUdpSocket * m_dataSocket
QHostAddress m_dataAddress
QHostAddress m_remoteAddress
quint16 m_dataPort
bool m_dataConnected
char * m_udpBuf
qint64 m_udpReadBytes
SampleSinkFifo * m_sampleFifo
uint32_t m_samplerate
uint64_t m_centerFrequency
uint64_t m_tv_msec
MessageQueue * m_outputMessageQueueToGUI
uint32_t m_tickCount
std::size_t m_samplesCount
QTimer * m_timer
QElapsedTimer m_elapsedTimer
int m_throttlems
int32_t m_readLengthSamples
uint32_t m_readLength
int32_t * m_converterBuffer
uint32_t m_converterBufferNbSamples
bool m_throttleToggle
bool m_autoCorrBuffer
Detailed Description
Definition at line 36 of file remoteinputudphandler.h.
Constructor & Destructor Documentation
RemoteInputUDPHandler()
RemoteInputUDPHandler::RemoteInputUDPHandler (SampleSinkFifo * sampleFifo, DeviceAPI * deviceAPI)
Definition at line 29 of file remoteinputudphandler.cpp.
References m_udpBuf.
                                                                                              :
     m_deviceAPI(deviceAPI),
     m_masterTimer(deviceAPI->getMasterTimer()),
     m_masterTimerConnected(false),
     m_running(false),
     m_rateDivider(1000/REMOTEINPUT_THROTTLE_MS),
     m_dataSocket(0),
     m_dataAddress(QHostAddress::LocalHost),
     m_remoteAddress(QHostAddress::LocalHost),
     m_dataPort(9090),
     m_dataConnected(false),
     m_udpBuf(0),
     m_udpReadBytes(0),
     m_sampleFifo(sampleFifo),
     m_samplerate(0),
     m_centerFrequency(0),
     m_tv_msec(0),
     m_outputMessageQueueToGUI(0),
     m_tickCount(0),
     m_samplesCount(0),
     m_timer(0),
     m_throttlems(REMOTEINPUT_THROTTLE_MS),
     m_readLengthSamples(0),
     m_readLength(0),
     m_converterBuffer(0),
     m_converterBufferNbSamples(0),
     m_throttleToggle(false),
     m_autoCorrBuffer(true)
 {
     m_udpBuf = new char[RemoteUdpSize];
 #ifdef USE_INTERNAL_TIMER
 #warning "Uses internal timer"
     m_timer = new QTimer();
     m_timer->start(50);
     m_throttlems = m_timer->interval();
 #else
     m_throttlems = m_masterTimer.interval();
 #endif
     m_rateDivider = 1000 / m_throttlems;
 }
~RemoteInputUDPHandler()
RemoteInputUDPHandler::~RemoteInputUDPHandler ()
Definition at line 71 of file remoteinputudphandler.cpp.
References m_converterBuffer, m_timer, m_udpBuf, and stop().
 {
     stop();
     delete[] m_udpBuf;
     if (m_converterBuffer) { delete[] m_converterBuffer; }
 #ifdef USE_INTERNAL_TIMER
     if (m_timer) {
         delete m_timer;
     }
 #endif
 }
Member Function Documentation
configureUDPLink()
void RemoteInputUDPHandler::configureUDPLink (const QString & address, quint16 port)
Definition at line 144 of file remoteinputudphandler.cpp.
References m_dataAddress, m_dataPort, start(), and stop().
Referenced by RemoteInput::applySettings(), and setMessageQueueToGUI().
 {
     qDebug("RemoteInputUDPHandler::configureUDPLink: %s:%d", address.toStdString().c_str(), port);
     bool addressOK = m_dataAddress.setAddress(address);
     if (!addressOK)
     {
         qWarning("RemoteInputUDPHandler::configureUDPLink: invalid address %s. Set to localhost.", address.toStdString().c_str());
         m_dataAddress = QHostAddress::LocalHost;
     }
     m_dataPort = port;
     stop();
     start();
 }
connectTimer()
void RemoteInputUDPHandler::connectTimer () private
Definition at line 217 of file remoteinputudphandler.cpp.
References m_masterTimer, m_masterTimerConnected, m_timer, and tick().
Referenced by processData().
 {
     if (!m_masterTimerConnected)
     {
         qDebug() << "RemoteInputUDPHandler::connectTimer";
 #ifdef USE_INTERNAL_TIMER
 #warning "Uses internal timer"
         connect(m_timer, SIGNAL(timeout()), this, SLOT(tick()));
 #else
         connect(&m_masterTimer, SIGNAL(timeout()), this, SLOT(tick()));
 #endif
         m_masterTimerConnected = true;
     }
 }
dataReadyRead
void RemoteInputUDPHandler::dataReadyRead () slot
Definition at line 160 of file remoteinputudphandler.cpp.
References m_dataConnected, m_dataSocket, m_remoteAddress, m_udpBuf, and m_udpReadBytes.
Referenced by getMaxNbRecovery(), start(), and stop().
 {
     m_udpReadBytes = 0;
     while (m_dataSocket->hasPendingDatagrams() && m_dataConnected)
     {
         qint64 pendingDataSize = m_dataSocket->pendingDatagramSize();
         m_udpReadBytes += m_dataSocket->readDatagram(&m_udpBuf[m_udpReadBytes], pendingDataSize, &m_remoteAddress, 0);
         if (m_udpReadBytes == RemoteUdpSize) {
             processData();
             m_udpReadBytes = 0;
         }
     }
 }
disconnectTimer()
void RemoteInputUDPHandler::disconnectTimer () private
Definition at line 232 of file remoteinputudphandler.cpp.
References m_masterTimer, m_masterTimerConnected, m_timer, and tick().
Referenced by stop().
 {
     if (m_masterTimerConnected)
     {
         qDebug() << "RemoteInputUDPHandler::disconnectTimer";
 #ifdef USE_INTERNAL_TIMER
 #warning "Uses internal timer"
         disconnect(m_timer, SIGNAL(timeout()), this, SLOT(tick()));
 #else
         disconnect(&m_masterTimer, SIGNAL(timeout()), this, SLOT(tick()));
 #endif
         m_masterTimerConnected = false;
     }
 }
getBufferGauge()
int RemoteInputUDPHandler::getBufferGauge () const inline
Definition at line 51 of file remoteinputudphandler.h.
References RemoteInputBuffer::getBufferGauge(), and m_remoteInputBuffer.
Referenced by RemoteInput::webapiFormatDeviceReport().
 { return m_remoteInputBuffer.getBufferGauge(); }
getCenterFrequency()
int RemoteInputUDPHandler::getCenterFrequency () const inline
Definition at line 50 of file remoteinputudphandler.h.
References m_centerFrequency.
Referenced by RemoteInput::getCenterFrequency(), and RemoteInput::webapiFormatDeviceReport().
 { return m_centerFrequency; }
getMaxNbRecovery()
int RemoteInputUDPHandler::getMaxNbRecovery () inline
Definition at line 54 of file remoteinputudphandler.h.
References dataReadyRead(), RemoteInputBuffer::getMaxNbRecovery(), and m_remoteInputBuffer.
Referenced by RemoteInput::webapiFormatDeviceReport().
 { return m_remoteInputBuffer.getMaxNbRecovery(); }
getMinNbBlocks()
int RemoteInputUDPHandler::getMinNbBlocks () inline
Definition at line 53 of file remoteinputudphandler.h.
References RemoteInputBuffer::getMinNbBlocks(), and m_remoteInputBuffer.
Referenced by RemoteInput::webapiFormatDeviceReport().
 { return m_remoteInputBuffer.getMinNbBlocks(); }
getNbOriginalBlocks()
int RemoteInputUDPHandler::getNbOriginalBlocks () const inline
Definition at line 47 of file remoteinputudphandler.h.
 { return RemoteNbOrginalBlocks; }
getRemoteAddress()
void RemoteInputUDPHandler::getRemoteAddress (QString & s) const inline
Definition at line 46 of file remoteinputudphandler.h.
References m_remoteAddress.
Referenced by RemoteInput::applySettings().
 { s = m_remoteAddress.toString(); }
getSampleRate()
int RemoteInputUDPHandler::getSampleRate () const inline
Definition at line 49 of file remoteinputudphandler.h.
References m_samplerate.
Referenced by RemoteInput::getSampleRate(), and RemoteInput::webapiFormatDeviceReport().
 { return m_samplerate; }
getTVmSec()
uint64_t RemoteInputUDPHandler::getTVmSec () const inline
Definition at line 52 of file remoteinputudphandler.h.
References m_tv_msec.
Referenced by RemoteInput::webapiFormatDeviceReport().
 { return m_tv_msec; }
isStreaming()
bool RemoteInputUDPHandler::isStreaming () const inline
Definition at line 48 of file remoteinputudphandler.h.
References m_masterTimerConnected.
Referenced by RemoteInput::isStreaming().
 { return m_masterTimerConnected; }
processData()
void RemoteInputUDPHandler::processData () private
Definition at line 176 of file remoteinputudphandler.cpp.
References connectTimer(), RemoteInput::MsgReportRemoteInputStreamData::create(), RemoteInputBuffer::getCurrentMeta(), DeviceAPI::getDeviceEngineInputMessageQueue(), RemoteInputBuffer::getTVOutMSec(), RemoteMetaDataFEC::m_centerFrequency, m_centerFrequency, m_deviceAPI, m_outputMessageQueueToGUI, m_remoteInputBuffer, RemoteMetaDataFEC::m_sampleRate, m_samplerate, m_tv_msec, m_udpBuf, MessageQueue::push(), and RemoteInputBuffer::writeData().
 {
     m_remoteInputBuffer.writeData(m_udpBuf);
     const RemoteMetaDataFEC& metaData =  m_remoteInputBuffer.getCurrentMeta();
     bool change = false;
     m_tv_msec = m_remoteInputBuffer.getTVOutMSec();
     if (m_centerFrequency != metaData.m_centerFrequency)
     {
         m_centerFrequency = metaData.m_centerFrequency;
         change = true;
     }
     if (m_samplerate != metaData.m_sampleRate)
     {
         m_samplerate = metaData.m_sampleRate;
         change = true;
     }
     if (change && (m_samplerate != 0))
     {
         qDebug("RemoteInputUDPHandler::processData: m_samplerate: %u S/s m_centerFrequency: %lu Hz", m_samplerate, m_centerFrequency);
         DSPSignalNotification *notif = new DSPSignalNotification(m_samplerate, m_centerFrequency); // Frequency in Hz for the DSP engine
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
         if (m_outputMessageQueueToGUI)
         {
             RemoteInput::MsgReportRemoteInputStreamData *report = RemoteInput::MsgReportRemoteInputStreamData::create(
                 m_samplerate,
                 m_centerFrequency, // Frequency in Hz for the GUI
                 m_tv_msec);
             m_outputMessageQueueToGUI->push(report);
         }
         connectTimer();
     }
 }
setMessageQueueToGUI()
void RemoteInputUDPHandler::setMessageQueueToGUI (MessageQueue * queue) inline
Definition at line 42 of file remoteinputudphandler.h.
References configureUDPLink(), m_outputMessageQueueToGUI, start(), and stop().
Referenced by RemoteInput::setMessageQueueToGUI().
 { m_outputMessageQueueToGUI = queue; }
start()
void RemoteInputUDPHandler::start ()
Definition at line 83 of file remoteinputudphandler.cpp.
References dataReadyRead(), m_dataAddress, m_dataConnected, m_dataPort, m_dataSocket, m_elapsedTimer, and m_running.
Referenced by configureUDPLink(), setMessageQueueToGUI(), and RemoteInput::start().
 {
     qDebug("RemoteInputUDPHandler::start");
     if (m_running) {
         return;
     }
     if (!m_dataSocket)
     {
         m_dataSocket = new QUdpSocket(this);
     }
     if (!m_dataConnected)
     {
         connect(m_dataSocket, SIGNAL(readyRead()), this, SLOT(dataReadyRead())); //, Qt::QueuedConnection);
         if (m_dataSocket->bind(m_dataAddress, m_dataPort))
         {
             qDebug("RemoteInputUDPHandler::start: bind data socket to %s:%d", m_dataAddress.toString().toStdString().c_str(),  m_dataPort);
             m_dataConnected = true;
         }
         else
         {
             qWarning("RemoteInputUDPHandler::start: cannot bind data port %d", m_dataPort);
             disconnect(m_dataSocket, SIGNAL(readyRead()), this, SLOT(dataReadyRead()));
             m_dataConnected = false;
         }
     }
     m_elapsedTimer.start();
     m_running = true;
 }
stop()
void RemoteInputUDPHandler::stop ()
Definition at line 117 of file remoteinputudphandler.cpp.
References dataReadyRead(), disconnectTimer(), m_centerFrequency, m_dataConnected, m_dataSocket, m_running, and m_samplerate.
Referenced by configureUDPLink(), setMessageQueueToGUI(), RemoteInput::stop(), and ~RemoteInputUDPHandler().
 {
     qDebug("RemoteInputUDPHandler::stop");
     if (!m_running) {
         return;
     }
     disconnectTimer();
     if (m_dataConnected)
     {
         m_dataConnected = false;
         disconnect(m_dataSocket, SIGNAL(readyRead()), this, SLOT(dataReadyRead()));
     }
     if (m_dataSocket)
     {
         delete m_dataSocket;
         m_dataSocket = 0;
     }
     m_centerFrequency = 0;
     m_samplerate = 0;
     m_running = false;
 }
tick
void RemoteInputUDPHandler::tick () private slot
Definition at line 247 of file remoteinputudphandler.cpp.
References RemoteInput::MsgReportRemoteInputStreamTiming::create(), RemoteInputBuffer::getAvgNbBlocks(), RemoteInputBuffer::getAvgNbRecovery(), RemoteInputBuffer::getAvgOriginalBlocks(), RemoteInputBuffer::getBufferGauge(), RemoteInputBuffer::getBufferLengthInSecs(), RemoteInputBuffer::getCurrentMeta(), RemoteInputBuffer::getMaxNbRecovery(), RemoteInputBuffer::getMinNbBlocks(), RemoteInputBuffer::getMinOriginalBlocks(), RemoteInputBuffer::getRWBalanceCorrection(), m_autoCorrBuffer, m_converterBuffer, m_converterBufferNbSamples, m_elapsedTimer, RemoteMetaDataFEC::m_nbFECBlocks, RemoteMetaDataFEC::m_nbOriginalBlocks, m_outputMessageQueueToGUI, m_rateDivider, m_readLength, m_readLengthSamples, m_remoteInputBuffer, RemoteMetaDataFEC::m_sampleBits, RemoteMetaDataFEC::m_sampleBytes, m_sampleFifo, RemoteMetaDataFEC::m_sampleRate, m_samplesCount, m_throttlems, m_throttleToggle, m_tickCount, m_tv_msec, MessageQueue::push(), RemoteInputBuffer::readData(), SDR_RX_SAMP_SZ, and SampleSinkFifo::write().
Referenced by connectTimer(), and disconnectTimer().
 {
     // auto throttling
     int throttlems = m_elapsedTimer.restart();
     if (throttlems != m_throttlems)
     {
         m_throttlems = throttlems;
         m_readLengthSamples = (m_remoteInputBuffer.getCurrentMeta().m_sampleRate * (m_throttlems+(m_throttleToggle ? 1 : 0))) / 1000;
         m_throttleToggle = !m_throttleToggle;
     }
     if (m_autoCorrBuffer)
     {
         m_readLengthSamples += m_remoteInputBuffer.getRWBalanceCorrection();
         // Eliminate negative or excessively high values
         m_readLengthSamples = m_readLengthSamples < 0 ?
             0 : m_readLengthSamples > (int) m_remoteInputBuffer.getCurrentMeta().m_sampleRate/5 ?
                 m_remoteInputBuffer.getCurrentMeta().m_sampleRate/5 : m_readLengthSamples;
     }
     const RemoteMetaDataFEC& metaData =  m_remoteInputBuffer.getCurrentMeta();
     m_readLength = m_readLengthSamples * (metaData.m_sampleBytes & 0xF) * 2;
     if ((metaData.m_sampleBits == 16) && (SDR_RX_SAMP_SZ == 24)) // 16 -> 24 bits
     {
         if (m_readLengthSamples > (int) m_converterBufferNbSamples)
         {
             if (m_converterBuffer) { delete[] m_converterBuffer; }
             m_converterBuffer = new int32_t[m_readLengthSamples*2];
         }
         uint8_t *buf = m_remoteInputBuffer.readData(m_readLength);
         for (int is = 0; is < m_readLengthSamples; is++)
         {
             m_converterBuffer[2*is] = ((int16_t*)buf)[2*is]; // I
             m_converterBuffer[2*is]<<=8;
             m_converterBuffer[2*is+1] = ((int16_t*)buf)[2*is+1]; // Q
             m_converterBuffer[2*is+1]<<=8;
         }
         m_sampleFifo->write(reinterpret_cast<quint8*>(m_converterBuffer), m_readLengthSamples*sizeof(Sample));
     }
     else if ((metaData.m_sampleBits == 24) && (SDR_RX_SAMP_SZ == 16)) // 24 -> 16 bits
     {
         if (m_readLengthSamples > (int) m_converterBufferNbSamples)
         {
             if (m_converterBuffer) { delete[] m_converterBuffer; }
             m_converterBuffer = new int32_t[m_readLengthSamples];
         }
         uint8_t *buf = m_remoteInputBuffer.readData(m_readLength);
         for (int is = 0; is < m_readLengthSamples; is++)
         {
             m_converterBuffer[is] =  ((int32_t *)buf)[2*is+1]>>8; // Q -> MSB
             m_converterBuffer[is] <<=16;
             m_converterBuffer[is] += ((int32_t *)buf)[2*is]>>8; // I -> LSB
         }
         m_sampleFifo->write(reinterpret_cast<quint8*>(m_converterBuffer), m_readLengthSamples*sizeof(Sample));
     }
     else if ((metaData.m_sampleBits == 16) || (metaData.m_sampleBits == 24)) // same sample size and valid size
     {
         // read samples directly feeding the SampleFifo (no callback)
         m_sampleFifo->write(reinterpret_cast<quint8*>(m_remoteInputBuffer.readData(m_readLength)), m_readLength);
         m_samplesCount += m_readLengthSamples;
     }
     else // invalid size
     {
         qWarning("RemoteInputUDPHandler::tick: unexpected sample size in stream: %d bits", (int) metaData.m_sampleBits);
     }
     if (m_tickCount < m_rateDivider)
     {
         m_tickCount++;
     }
     else
     {
         m_tickCount = 0;
         if (m_outputMessageQueueToGUI)
         {
             int framesDecodingStatus;
             int minNbBlocks = m_remoteInputBuffer.getMinNbBlocks();
             int minNbOriginalBlocks = m_remoteInputBuffer.getMinOriginalBlocks();
             int nbOriginalBlocks = m_remoteInputBuffer.getCurrentMeta().m_nbOriginalBlocks;
             int nbFECblocks = m_remoteInputBuffer.getCurrentMeta().m_nbFECBlocks;
             int sampleBits = m_remoteInputBuffer.getCurrentMeta().m_sampleBits;
             int sampleBytes = m_remoteInputBuffer.getCurrentMeta().m_sampleBytes;
             //framesDecodingStatus = (minNbOriginalBlocks == nbOriginalBlocks ? 2 : (minNbOriginalBlocks < nbOriginalBlocks - nbFECblocks ? 0 : 1));
             if (minNbBlocks < nbOriginalBlocks) {
                 framesDecodingStatus = 0;
             } else if (minNbBlocks < nbOriginalBlocks + nbFECblocks) {
                 framesDecodingStatus = 1;
             } else {
                 framesDecodingStatus = 2;
             }
             RemoteInput::MsgReportRemoteInputStreamTiming *report = RemoteInput::MsgReportRemoteInputStreamTiming::create(
                 m_tv_msec,
                 m_remoteInputBuffer.getBufferLengthInSecs(),
                 m_remoteInputBuffer.getBufferGauge(),
                 framesDecodingStatus,
                 minNbBlocks == nbOriginalBlocks + nbFECblocks,
                 minNbBlocks,
                 minNbOriginalBlocks,
                 m_remoteInputBuffer.getMaxNbRecovery(),
                 m_remoteInputBuffer.getAvgNbBlocks(),
                 m_remoteInputBuffer.getAvgOriginalBlocks(),
                 m_remoteInputBuffer.getAvgNbRecovery(),
                 nbOriginalBlocks,
                 nbFECblocks,
                 sampleBits,
                 sampleBytes);
                 m_outputMessageQueueToGUI->push(report);
         }
     }
 }
Member Data Documentation
m_autoCorrBuffer
bool RemoteInputUDPHandler::m_autoCorrBuffer private
Definition at line 88 of file remoteinputudphandler.h.
Referenced by tick().
m_centerFrequency
uint64_t RemoteInputUDPHandler::m_centerFrequency private
Definition at line 74 of file remoteinputudphandler.h.
Referenced by getCenterFrequency(), processData(), and stop().
m_converterBuffer
int32_t* RemoteInputUDPHandler::m_converterBuffer private
Definition at line 85 of file remoteinputudphandler.h.
Referenced by tick(), and ~RemoteInputUDPHandler().
m_converterBufferNbSamples
uint32_t RemoteInputUDPHandler::m_converterBufferNbSamples private
Definition at line 86 of file remoteinputudphandler.h.
Referenced by tick().
m_dataAddress
QHostAddress RemoteInputUDPHandler::m_dataAddress private
Definition at line 66 of file remoteinputudphandler.h.
Referenced by configureUDPLink(), and start().
m_dataConnected
bool RemoteInputUDPHandler::m_dataConnected private
Definition at line 69 of file remoteinputudphandler.h.
Referenced by dataReadyRead(), start(), and stop().
m_dataPort
quint16 RemoteInputUDPHandler::m_dataPort private
Definition at line 68 of file remoteinputudphandler.h.
Referenced by configureUDPLink(), and start().
m_dataSocket
QUdpSocket* RemoteInputUDPHandler::m_dataSocket private
Definition at line 65 of file remoteinputudphandler.h.
Referenced by dataReadyRead(), start(), and stop().
m_deviceAPI
DeviceAPI* RemoteInputUDPHandler::m_deviceAPI private
Definition at line 59 of file remoteinputudphandler.h.
Referenced by processData().
m_elapsedTimer
QElapsedTimer RemoteInputUDPHandler::m_elapsedTimer private
Definition at line 81 of file remoteinputudphandler.h.
Referenced by start(), and tick().
m_masterTimer
const QTimer& RemoteInputUDPHandler::m_masterTimer private
Definition at line 60 of file remoteinputudphandler.h.
Referenced by connectTimer(), and disconnectTimer().
m_masterTimerConnected
bool RemoteInputUDPHandler::m_masterTimerConnected private
Definition at line 61 of file remoteinputudphandler.h.
Referenced by connectTimer(), disconnectTimer(), and isStreaming().
m_outputMessageQueueToGUI
MessageQueue* RemoteInputUDPHandler::m_outputMessageQueueToGUI private
Definition at line 76 of file remoteinputudphandler.h.
Referenced by processData(), setMessageQueueToGUI(), and tick().
m_rateDivider
uint32_t RemoteInputUDPHandler::m_rateDivider private
Definition at line 63 of file remoteinputudphandler.h.
Referenced by tick().
m_readLength
uint32_t RemoteInputUDPHandler::m_readLength private
Definition at line 84 of file remoteinputudphandler.h.
Referenced by tick().
m_readLengthSamples
int32_t RemoteInputUDPHandler::m_readLengthSamples private
Definition at line 83 of file remoteinputudphandler.h.
Referenced by tick().
m_remoteAddress
QHostAddress RemoteInputUDPHandler::m_remoteAddress private
Definition at line 67 of file remoteinputudphandler.h.
Referenced by dataReadyRead(), and getRemoteAddress().
m_remoteInputBuffer
RemoteInputBuffer RemoteInputUDPHandler::m_remoteInputBuffer private
Definition at line 64 of file remoteinputudphandler.h.
Referenced by getBufferGauge(), getMaxNbRecovery(), getMinNbBlocks(), processData(), and tick().
m_running
bool RemoteInputUDPHandler::m_running private
Definition at line 62 of file remoteinputudphandler.h.
Referenced by start(), and stop().
m_sampleFifo
SampleSinkFifo* RemoteInputUDPHandler::m_sampleFifo private
Definition at line 72 of file remoteinputudphandler.h.
Referenced by tick().
m_samplerate
uint32_t RemoteInputUDPHandler::m_samplerate private
Definition at line 73 of file remoteinputudphandler.h.
Referenced by getSampleRate(), processData(), and stop().
m_samplesCount
std::size_t RemoteInputUDPHandler::m_samplesCount private
Definition at line 78 of file remoteinputudphandler.h.
Referenced by tick().
m_throttlems
int RemoteInputUDPHandler::m_throttlems private
Definition at line 82 of file remoteinputudphandler.h.
Referenced by tick().
m_throttleToggle
bool RemoteInputUDPHandler::m_throttleToggle private
Definition at line 87 of file remoteinputudphandler.h.
Referenced by tick().
m_tickCount
uint32_t RemoteInputUDPHandler::m_tickCount private
Definition at line 77 of file remoteinputudphandler.h.
Referenced by tick().
m_timer
QTimer* RemoteInputUDPHandler::m_timer private
Definition at line 79 of file remoteinputudphandler.h.
Referenced by connectTimer(), disconnectTimer(), and ~RemoteInputUDPHandler().
m_tv_msec
uint64_t RemoteInputUDPHandler::m_tv_msec private
Definition at line 75 of file remoteinputudphandler.h.
Referenced by getTVmSec(), processData(), and tick().
m_udpBuf
char* RemoteInputUDPHandler::m_udpBuf private
Definition at line 70 of file remoteinputudphandler.h.
Referenced by dataReadyRead(), processData(), RemoteInputUDPHandler(), and ~RemoteInputUDPHandler().
m_udpReadBytes
qint64 RemoteInputUDPHandler::m_udpReadBytes private
Definition at line 71 of file remoteinputudphandler.h.
Referenced by dataReadyRead().
The documentation for this class was generated from the following files:
plugins/samplesource/remoteinput/remoteinputudphandler.h
plugins/samplesource/remoteinput/remoteinputudphandler.cpp