SDRAngel: RemoteOutput::MsgStartStop Class Reference
RemoteOutput::MsgStartStop Class Reference
#include <remoteoutput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 86 of file remoteoutput.h.
Constructor & Destructor Documentation
MsgStartStop()
RemoteOutput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 99 of file remoteoutput.h.
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* RemoteOutput::MsgStartStop::create (bool startStop) inline static
Definition at line 92 of file remoteoutput.h.
Referenced by RemoteOutputSinkGui::on_startStop_toggled(), and RemoteOutput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool RemoteOutput::MsgStartStop::getStartStop () const inline
Definition at line 90 of file remoteoutput.h.
Referenced by RemoteOutputSinkGui::handleMessage(), and RemoteOutput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool RemoteOutput::MsgStartStop::m_startStop protected
Definition at line 97 of file remoteoutput.h.
The documentation for this class was generated from the following file:
plugins/samplesink/remoteoutput/remoteoutput.h