SDRAngel: SWGSDRangel::SWGRange Class Reference
SWGSDRangel::SWGRange Class Reference
#include <SWGRange.h>
Public Member Functions
SWGRange ()
SWGRange (QString *json)
virtual ~SWGRange ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGRange * fromJson (QString &jsonString) override
qint32 getMin ()
void setMin (qint32 min)
qint32 getMax ()
void setMax (qint32 max)
qint32 getStep ()
void setStep (qint32 step)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 min
bool m_min_isSet
qint32 max
bool m_max_isSet
qint32 step
bool m_step_isSet
Detailed Description
Definition at line 31 of file SWGRange.h.
Constructor & Destructor Documentation
SWGRange() [1/2]
SWGSDRangel::SWGRange::SWGRange ()
Definition at line 30 of file SWGRange.cpp.
References m_max_isSet, m_min_isSet, m_step_isSet, max, min, and step.
                    {
     min = 0;
     m_min_isSet = false;
     max = 0;
     m_max_isSet = false;
     step = 0;
     m_step_isSet = false;
 }
SWGRange() [2/2]
SWGSDRangel::SWGRange::SWGRange (QString * json)
Definition at line 25 of file SWGRange.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGRange()
SWGSDRangel::SWGRange::~SWGRange () virtual
Definition at line 39 of file SWGRange.cpp.
References cleanup().
                     {
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGRange::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 80 of file SWGRange.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGRange::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 91 of file SWGRange.cpp.
References m_max_isSet, m_min_isSet, m_step_isSet, max, min, and step.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_min_isSet){
         obj->insert("min", QJsonValue(min));
     }
     if(m_max_isSet){
         obj->insert("max", QJsonValue(max));
     }
     if(m_step_isSet){
         obj->insert("step", QJsonValue(step));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGRange::cleanup ()
Definition at line 54 of file SWGRange.cpp.
Referenced by ~SWGRange().
                   {
 }
fromJson()
SWGRange * SWGSDRangel::SWGRange::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 61 of file SWGRange.cpp.
References fromJsonObject().
Referenced by SWGRange().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGRange::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 70 of file SWGRange.cpp.
References max, min, SWGSDRangel::setValue(), and step.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&min, pJson["min"], "qint32", "");
     ::SWGSDRangel::setValue(&max, pJson["max"], "qint32", "");
     ::SWGSDRangel::setValue(&step, pJson["step"], "qint32", "");
 }
getMax()
qint32 SWGSDRangel::SWGRange::getMax ()
Definition at line 117 of file SWGRange.cpp.
References max.
                  {
     return max;
 }
getMin()
qint32 SWGSDRangel::SWGRange::getMin ()
Definition at line 107 of file SWGRange.cpp.
References min.
                  {
     return min;
 }
getStep()
qint32 SWGSDRangel::SWGRange::getStep ()
Definition at line 127 of file SWGRange.cpp.
References step.
                   {
     return step;
 }
init()
void SWGSDRangel::SWGRange::init ()
Definition at line 44 of file SWGRange.cpp.
References m_max_isSet, m_min_isSet, m_step_isSet, max, min, and step.
Referenced by SWGRange().
                {
     min = 0;
     m_min_isSet = false;
     max = 0;
     m_max_isSet = false;
     step = 0;
     m_step_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGRange::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 138 of file SWGRange.cpp.
References m_max_isSet, m_min_isSet, and m_step_isSet.
Referenced by SWGSDRangel::SWGBladeRF2OutputReport::asJsonObject(), SWGSDRangel::SWGBladeRF2InputReport::asJsonObject(), SWGSDRangel::SWGBladeRF2OutputReport::isSet(), and SWGSDRangel::SWGBladeRF2InputReport::isSet().
                {
     bool isObjectUpdated = false;
     do{
         if(m_min_isSet){ isObjectUpdated = true; break;}
         if(m_max_isSet){ isObjectUpdated = true; break;}
         if(m_step_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setMax()
void SWGSDRangel::SWGRange::setMax (qint32 max)
Definition at line 121 of file SWGRange.cpp.
References m_max_isSet, and max.
Referenced by BladeRF2Output::webapiFormatDeviceReport(), and BladeRF2Input::webapiFormatDeviceReport().
{
     this->max = max;
     this->m_max_isSet = true;
 }
setMin()
void SWGSDRangel::SWGRange::setMin (qint32 min)
Definition at line 111 of file SWGRange.cpp.
References m_min_isSet, and min.
Referenced by BladeRF2Output::webapiFormatDeviceReport(), and BladeRF2Input::webapiFormatDeviceReport().
{
     this->min = min;
     this->m_min_isSet = true;
 }
setStep()
void SWGSDRangel::SWGRange::setStep (qint32 step)
Definition at line 131 of file SWGRange.cpp.
References m_step_isSet, and step.
Referenced by BladeRF2Output::webapiFormatDeviceReport(), and BladeRF2Input::webapiFormatDeviceReport().
{
     this->step = step;
     this->m_step_isSet = true;
 }
Member Data Documentation
m_max_isSet
bool SWGSDRangel::SWGRange::m_max_isSet private
Definition at line 61 of file SWGRange.h.
Referenced by asJsonObject(), init(), isSet(), setMax(), and SWGRange().
m_min_isSet
bool SWGSDRangel::SWGRange::m_min_isSet private
Definition at line 58 of file SWGRange.h.
Referenced by asJsonObject(), init(), isSet(), setMin(), and SWGRange().
m_step_isSet
bool SWGSDRangel::SWGRange::m_step_isSet private
Definition at line 64 of file SWGRange.h.
Referenced by asJsonObject(), init(), isSet(), setStep(), and SWGRange().
max
qint32 SWGSDRangel::SWGRange::max private
Definition at line 60 of file SWGRange.h.
Referenced by asJsonObject(), fromJsonObject(), getMax(), init(), setMax(), and SWGRange().
min
qint32 SWGSDRangel::SWGRange::min private
Definition at line 57 of file SWGRange.h.
Referenced by asJsonObject(), fromJsonObject(), getMin(), init(), setMin(), and SWGRange().
step
qint32 SWGSDRangel::SWGRange::step private
Definition at line 63 of file SWGRange.h.
Referenced by asJsonObject(), fromJsonObject(), getStep(), init(), setStep(), and SWGRange().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGRange.h
swagger/sdrangel/code/qt5/client/SWGRange.cpp