SDRAngel: SWGSDRangel::SWGDVSerialDevices Class Reference
SWGSDRangel::SWGDVSerialDevices Class Reference
#include <SWGDVSerialDevices.h>
Public Member Functions
SWGDVSerialDevices ()
SWGDVSerialDevices (QString *json)
virtual ~SWGDVSerialDevices ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGDVSerialDevices * fromJson (QString &jsonString) override
qint32 getNbDevices ()
void setNbDevices (qint32 nb_devices)
QList< SWGDVSerialDevice * > * getDvSerialDevices ()
void setDvSerialDevices (QList< SWGDVSerialDevice *> *dv_serial_devices)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 nb_devices
bool m_nb_devices_isSet
QList< SWGDVSerialDevice * > * dv_serial_devices
bool m_dv_serial_devices_isSet
Detailed Description
Definition at line 33 of file SWGDVSerialDevices.h.
Constructor & Destructor Documentation
SWGDVSerialDevices() [1/2]
SWGSDRangel::SWGDVSerialDevices::SWGDVSerialDevices ()
Definition at line 30 of file SWGDVSerialDevices.cpp.
References dv_serial_devices, m_dv_serial_devices_isSet, m_nb_devices_isSet, and nb_devices.
{
     nb_devices = 0;
     m_nb_devices_isSet = false;
     dv_serial_devices = nullptr;
     m_dv_serial_devices_isSet = false;
 }
SWGDVSerialDevices() [2/2]
SWGSDRangel::SWGDVSerialDevices::SWGDVSerialDevices (QString * json)
Definition at line 25 of file SWGDVSerialDevices.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGDVSerialDevices()
SWGSDRangel::SWGDVSerialDevices::~SWGDVSerialDevices () virtual
Definition at line 37 of file SWGDVSerialDevices.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGDVSerialDevices::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 79 of file SWGDVSerialDevices.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::instanceAMBESerialService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGDVSerialDevices::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 90 of file SWGDVSerialDevices.cpp.
References dv_serial_devices, m_nb_devices_isSet, nb_devices, and SWGSDRangel::toJsonArray().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_nb_devices_isSet){
         obj->insert("nbDevices", QJsonValue(nb_devices));
     }
     if(dv_serial_devices->size() > 0){
         toJsonArray((QList<void*>*)dv_serial_devices, obj, "dvSerialDevices", "SWGDVSerialDevice");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGDVSerialDevices::cleanup ()
Definition at line 50 of file SWGDVSerialDevices.cpp.
References dv_serial_devices.
Referenced by ~SWGDVSerialDevices().
{
     if(dv_serial_devices != nullptr) {
         auto arr = dv_serial_devices;
         for(auto o: *arr) {
             delete o;
         }
         delete dv_serial_devices;
     }
 }
fromJson()
SWGDVSerialDevices * SWGSDRangel::SWGDVSerialDevices::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 62 of file SWGDVSerialDevices.cpp.
References fromJsonObject().
Referenced by SWGDVSerialDevices().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGDVSerialDevices::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 71 of file SWGDVSerialDevices.cpp.
References dv_serial_devices, nb_devices, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&nb_devices, pJson["nbDevices"], "qint32", "");
     ::SWGSDRangel::setValue(&dv_serial_devices, pJson["dvSerialDevices"], "QList", "SWGDVSerialDevice");
 }
getDvSerialDevices()
QList< SWGDVSerialDevice * > * SWGSDRangel::SWGDVSerialDevices::getDvSerialDevices ()
Definition at line 113 of file SWGDVSerialDevices.cpp.
References dv_serial_devices.
Referenced by WebAPIAdapterGUI::instanceAMBESerialGet(), WebAPIAdapterSrv::instanceAMBESerialGet(), WebAPIAdapterSrv::instanceDVSerialGet(), WebAPIAdapterGUI::instanceDVSerialGet(), WebAPIAdapterGUI::instanceDVSerialPatch(), and WebAPIAdapterSrv::instanceDVSerialPatch().
{
     return dv_serial_devices;
 }
getNbDevices()
qint32 SWGSDRangel::SWGDVSerialDevices::getNbDevices ()
Definition at line 103 of file SWGDVSerialDevices.cpp.
References nb_devices.
{
     return nb_devices;
 }
init()
void SWGSDRangel::SWGDVSerialDevices::init ()
Definition at line 42 of file SWGDVSerialDevices.cpp.
References dv_serial_devices, m_dv_serial_devices_isSet, m_nb_devices_isSet, and nb_devices.
Referenced by WebAPIAdapterGUI::instanceAMBESerialGet(), WebAPIAdapterSrv::instanceAMBESerialGet(), WebAPIAdapterSrv::instanceDVSerialGet(), WebAPIAdapterGUI::instanceDVSerialGet(), WebAPIAdapterGUI::instanceDVSerialPatch(), WebAPIAdapterSrv::instanceDVSerialPatch(), and SWGDVSerialDevices().
{
     nb_devices = 0;
     m_nb_devices_isSet = false;
     dv_serial_devices = new QList<SWGDVSerialDevice*>();
     m_dv_serial_devices_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGDVSerialDevices::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 124 of file SWGDVSerialDevices.cpp.
References dv_serial_devices, and m_nb_devices_isSet.
{
     bool isObjectUpdated = false;
     do{
         if(m_nb_devices_isSet){ isObjectUpdated = true; break;}
         if(dv_serial_devices->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setDvSerialDevices()
void SWGSDRangel::SWGDVSerialDevices::setDvSerialDevices (QList< SWGDVSerialDevice *> * dv_serial_devices)
Definition at line 117 of file SWGDVSerialDevices.cpp.
References dv_serial_devices, and m_dv_serial_devices_isSet.
{
     this->dv_serial_devices = dv_serial_devices;
     this->m_dv_serial_devices_isSet = true;
 }
setNbDevices()
void SWGSDRangel::SWGDVSerialDevices::setNbDevices (qint32 nb_devices)
Definition at line 107 of file SWGDVSerialDevices.cpp.
References m_nb_devices_isSet, and nb_devices.
Referenced by WebAPIAdapterGUI::instanceAMBESerialGet(), WebAPIAdapterSrv::instanceAMBESerialGet(), WebAPIAdapterSrv::instanceDVSerialGet(), WebAPIAdapterGUI::instanceDVSerialGet(), WebAPIAdapterGUI::instanceDVSerialPatch(), and WebAPIAdapterSrv::instanceDVSerialPatch().
{
     this->nb_devices = nb_devices;
     this->m_nb_devices_isSet = true;
 }
Member Data Documentation
dv_serial_devices
QList<SWGDVSerialDevice*>* SWGSDRangel::SWGDVSerialDevices::dv_serial_devices private
Definition at line 59 of file SWGDVSerialDevices.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getDvSerialDevices(), init(), isSet(), setDvSerialDevices(), and SWGDVSerialDevices().
m_dv_serial_devices_isSet
bool SWGSDRangel::SWGDVSerialDevices::m_dv_serial_devices_isSet private
Definition at line 60 of file SWGDVSerialDevices.h.
Referenced by init(), setDvSerialDevices(), and SWGDVSerialDevices().
m_nb_devices_isSet
bool SWGSDRangel::SWGDVSerialDevices::m_nb_devices_isSet private
Definition at line 57 of file SWGDVSerialDevices.h.
Referenced by asJsonObject(), init(), isSet(), setNbDevices(), and SWGDVSerialDevices().
nb_devices
qint32 SWGSDRangel::SWGDVSerialDevices::nb_devices private
Definition at line 56 of file SWGDVSerialDevices.h.
Referenced by asJsonObject(), fromJsonObject(), getNbDevices(), init(), setNbDevices(), and SWGDVSerialDevices().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGDVSerialDevices.h
swagger/sdrangel/code/qt5/client/SWGDVSerialDevices.cpp