SDRAngel: WFMDemod::MsgConfigureWFMDemod Class Reference
WFMDemod::MsgConfigureWFMDemod Class Reference
#include <wfmdemod.h>
Public Member Functions
const WFMDemodSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureWFMDemod * create (const WFMDemodSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureWFMDemod (const WFMDemodSettings &settings, bool force)
Private Attributes
WFMDemodSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 51 of file wfmdemod.h.
Constructor & Destructor Documentation
MsgConfigureWFMDemod()
WFMDemod::MsgConfigureWFMDemod::MsgConfigureWFMDemod (const WFMDemodSettings & settings, bool force) inline private
Definition at line 67 of file wfmdemod.h.
Referenced by create().
                                                                            :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureWFMDemod* WFMDemod::MsgConfigureWFMDemod::create (const WFMDemodSettings & settings, bool force) inline static
Definition at line 58 of file wfmdemod.h.
References MsgConfigureWFMDemod().
Referenced by WFMDemodGUI::applySettings(), WFMDemod::deserialize(), and WFMDemod::webapiSettingsPutPatch().
         {
             return new MsgConfigureWFMDemod(settings, force);
         }
getForce()
bool WFMDemod::MsgConfigureWFMDemod::getForce () const inline
Definition at line 56 of file wfmdemod.h.
References m_force.
Referenced by WFMDemod::handleMessage().
 { return m_force; }
getSettings()
const WFMDemodSettings& WFMDemod::MsgConfigureWFMDemod::getSettings () const inline
Definition at line 55 of file wfmdemod.h.
References m_settings.
Referenced by WFMDemodGUI::handleMessage(), and WFMDemod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool WFMDemod::MsgConfigureWFMDemod::m_force private
Definition at line 65 of file wfmdemod.h.
Referenced by getForce().
m_settings
WFMDemodSettings WFMDemod::MsgConfigureWFMDemod::m_settings private
Definition at line 64 of file wfmdemod.h.
Referenced by WFMDemod::getCenterFrequency(), getSettings(), WFMDemod::getStreamCenterFrequency(), and WFMDemod::getTitle().
The documentation for this class was generated from the following file:
plugins/channelrx/demodwfm/wfmdemod.h