SDRAngel: SSBDemodGUI Class Reference
SSBDemodGUI Class Reference
#include <ssbdemodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
void channelMarkerHighlightedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static SSBDemodGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
Private Slots
void on_deltaFrequency_changed (qint64 value)
void on_audioBinaural_toggled (bool binaural)
void on_audioFlipChannels_toggled (bool flip)
void on_dsb_toggled (bool dsb)
void on_BW_valueChanged (int value)
void on_lowCut_valueChanged (int value)
void on_volume_valueChanged (int value)
void on_agc_toggled (bool checked)
void on_agcClamping_toggled (bool checked)
void on_agcTimeLog2_valueChanged (int value)
void on_agcPowerThreshold_valueChanged (int value)
void on_agcThresholdGate_valueChanged (int value)
void on_audioMute_toggled (bool checked)
void on_spanLog2_valueChanged (int value)
void on_flipSidebands_clicked (bool checked)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void handleInputMessages ()
void audioSelect ()
void tick ()
Private Member Functions
SSBDemodGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *parent=0)
virtual ~SSBDemodGUI ()
bool blockApplySettings (bool block)
void applySettings (bool force=false)
void applyBandwidths (int spanLog2, bool force=false)
int spanLog2Limit (int spanLog2)
void displaySettings ()
void displayAGCPowerThreshold (int value)
void displayAGCThresholdGate (int value)
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::SSBDemodGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
SSBDemodSettings m_settings
bool m_doApplySettings
int m_spectrumRate
bool m_audioBinaural
bool m_audioFlipChannels
bool m_audioMute
bool m_squelchOpen
uint32_t m_tickCount
SSBDemod * m_ssbDemod
SpectrumVis * m_spectrumVis
MessageQueue m_inputMessageQueue
QIcon m_iconDSBUSB
QIcon m_iconDSBLSB
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 25 of file ssbdemodgui.h.
Constructor & Destructor Documentation
SSBDemodGUI()
SSBDemodGUI::SSBDemodGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * parent = 0) explicit private
Definition at line 275 of file ssbdemodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applyBandwidths(), arg(), audioSelect(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), LevelMeterSignalDB::ColorGreenAndBlue, displaySettings(), ChannelMarker::getColor(), getInputMessageQueue(), BasebandSampleSink::getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, handleInputMessages(), SSBDemod::m_channelIdURI, m_channelMarker, m_deviceUISet, m_iconDSBLSB, m_iconDSBUSB, m_settings, SSBDemodSettings::m_spanLog2, m_spectrumRate, m_spectrumVis, m_ssbDemod, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), SDR_RX_SCALEF, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), SSBDemodSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSink::setMessageQueueToGUI(), SSBDemod::setSampleSink(), SSBDemodSettings::setSpectrumGUI(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                        :
     RollupWidget(parent),
     ui(new Ui::SSBDemodGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_doApplySettings(true),
     m_spectrumRate(6000),
     m_audioBinaural(false),
     m_audioFlipChannels(false),
     m_audioMute(false),
     m_squelchOpen(false)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_spectrumVis = new SpectrumVis(SDR_RX_SCALEF, ui->glSpectrum);
     m_ssbDemod = (SSBDemod*) rxChannel; //new SSBDemod(m_deviceUISet->m_deviceSourceAPI);
     m_ssbDemod->setMessageQueueToGUI(getInputMessageQueue());
     m_ssbDemod->setSampleSink(m_spectrumVis);
     CRightClickEnabler *audioMuteRightClickEnabler = new CRightClickEnabler(ui->audioMute);
     connect(audioMuteRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioSelect()));
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     ui->channelPowerMeter->setColorTheme(LevelMeterSignalDB::ColorGreenAndBlue);
     ui->glSpectrum->setCenterFrequency(m_spectrumRate/2);
     ui->glSpectrum->setSampleRate(m_spectrumRate);
     ui->glSpectrum->setDisplayWaterfall(true);
     ui->glSpectrum->setDisplayMaxHold(true);
     ui->glSpectrum->setSsbSpectrum(true);
     ui->glSpectrum->connectTimer(MainWindow::getInstance()->getMasterTimer());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(Qt::green);
     m_channelMarker.setBandwidth(6000);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("SSB Demodulator");
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     setTitleColor(m_channelMarker.getColor());
     m_settings.setChannelMarker(&m_channelMarker);
     m_settings.setSpectrumGUI(ui->spectrumGUI);
     m_deviceUISet->registerRxChannelInstance(SSBDemod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(&m_channelMarker, SIGNAL(highlightedByCursor()), this, SLOT(channelMarkerHighlightedByCursor()));
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
     ui->spectrumGUI->setBuddies(m_spectrumVis->getInputMessageQueue(), m_spectrumVis, ui->glSpectrum);
     m_iconDSBUSB.addPixmap(QPixmap("://dsb.png"), QIcon::Normal, QIcon::On);
     m_iconDSBUSB.addPixmap(QPixmap("://usb.png"), QIcon::Normal, QIcon::Off);
     m_iconDSBLSB.addPixmap(QPixmap("://dsb.png"), QIcon::Normal, QIcon::On);
     m_iconDSBLSB.addPixmap(QPixmap("://lsb.png"), QIcon::Normal, QIcon::Off);
     displaySettings();
     applyBandwidths(m_settings.m_spanLog2, true); // does applySettings(true)
 }
~SSBDemodGUI()
SSBDemodGUI::~SSBDemodGUI () private virtual
Definition at line 347 of file ssbdemodgui.cpp.
References m_deviceUISet, m_spectrumVis, m_ssbDemod, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_ssbDemod; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete m_spectrumVis;
     delete ui;
 }
Member Function Documentation
applyBandwidths()
void SSBDemodGUI::applyBandwidths (int spanLog2, bool force = false) private
Definition at line 384 of file ssbdemodgui.cpp.
References applySettings(), arg(), blockApplySettings(), ChannelMarker::dsb, SSBDemod::getAudioSampleRate(), SSBDemod::getInputSampleRate(), ChannelMarker::lsb, m_channelMarker, SSBDemodSettings::m_dsb, m_iconDSBLSB, m_iconDSBUSB, SSBDemodSettings::m_lowCutoff, SSBDemodSettings::m_minPowerThresholdDB, SSBDemodSettings::m_rfBandwidth, m_settings, SSBDemodSettings::m_spanLog2, m_spectrumRate, m_ssbDemod, leansdr::min(), ChannelMarker::setBandwidth(), ChannelMarker::setLowCutoff(), ChannelMarker::setSidebands(), spanLog2Limit(), ui, and ChannelMarker::usb.
Referenced by deserialize(), handleMessage(), on_BW_valueChanged(), on_dsb_toggled(), on_lowCut_valueChanged(), on_spanLog2_valueChanged(), and SSBDemodGUI().
 {
     spanLog2 = spanLog2Limit(spanLog2);
     ui->spanLog2->setMaximum(5 - spanLog2Limit(1));
     bool dsb = ui->dsb->isChecked();
     //int spanLog2 = ui->spanLog2->value();
     m_spectrumRate = m_ssbDemod->getAudioSampleRate() / (1<<spanLog2);
     int bw = ui->BW->value();
     int lw = ui->lowCut->value();
     int bwMax = std::min(m_ssbDemod->getAudioSampleRate() / (100*(1<<spanLog2)), m_ssbDemod->getInputSampleRate()/100);
     int tickInterval = m_spectrumRate / 1200;
     tickInterval = tickInterval == 0 ? 1 : tickInterval;
     qDebug() << "SSBDemodGUI::applyBandwidths:"
             << " dsb: " << dsb
             << " spanLog2: " << spanLog2
             << " m_spectrumRate: " << m_spectrumRate
             << " bw: " << bw
             << " lw: " << lw
             << " bwMax: " << bwMax
             << " tickInterval: " << tickInterval;
     ui->BW->setTickInterval(tickInterval);
     ui->lowCut->setTickInterval(tickInterval);
     bw = bw < -bwMax ? -bwMax : bw > bwMax ? bwMax : bw;
     if (bw < 0) {
         lw = lw < bw+1 ? bw+1 : lw < 0 ? lw : 0;
     } else if (bw > 0) {
         lw = lw > bw-1 ? bw-1 : lw < 0 ? 0 : lw;
     } else {
         lw = 0;
     }
     if (dsb)
     {
         bw = bw < 0 ? -bw : bw;
         lw = 0;
     }
     QString spanStr = QString::number(bwMax/10.0, 'f', 1);
     QString bwStr   = QString::number(bw/10.0, 'f', 1);
     QString lwStr   = QString::number(lw/10.0, 'f', 1);
     if (dsb)
     {
         ui->BWText->setText(tr("%1%2k").arg(QChar(0xB1, 0x00)).arg(bwStr));
         ui->spanText->setText(tr("%1%2k").arg(QChar(0xB1, 0x00)).arg(spanStr));
         ui->scaleMinus->setText("0");
         ui->scaleCenter->setText("");
         ui->scalePlus->setText(tr("%1").arg(QChar(0xB1, 0x00)));
         ui->lsbLabel->setText("");
         ui->usbLabel->setText("");
         ui->glSpectrum->setCenterFrequency(0);
         ui->glSpectrum->setSampleRate(2*m_spectrumRate);
         ui->glSpectrum->setSsbSpectrum(false);
         ui->glSpectrum->setLsbDisplay(false);
     }
     else
     {
         ui->BWText->setText(tr("%1k").arg(bwStr));
         ui->spanText->setText(tr("%1k").arg(spanStr));
         ui->scaleMinus->setText("-");
         ui->scaleCenter->setText("0");
         ui->scalePlus->setText("+");
         ui->lsbLabel->setText("LSB");
         ui->usbLabel->setText("USB");
         ui->glSpectrum->setCenterFrequency(m_spectrumRate/2);
         ui->glSpectrum->setSampleRate(m_spectrumRate);
         ui->glSpectrum->setSsbSpectrum(true);
         ui->glSpectrum->setLsbDisplay(bw < 0);
     }
     ui->lowCutText->setText(tr("%1k").arg(lwStr));
     ui->BW->blockSignals(true);
     ui->lowCut->blockSignals(true);
     ui->BW->setMaximum(bwMax);
     ui->BW->setMinimum(dsb ? 0 : -bwMax);
     ui->BW->setValue(bw);
     ui->lowCut->setMaximum(dsb ? 0 :  bwMax);
     ui->lowCut->setMinimum(dsb ? 0 : -bwMax);
     ui->lowCut->setValue(lw);
     ui->lowCut->blockSignals(false);
     ui->BW->blockSignals(false);
     ui->channelPowerMeter->setRange(SSBDemodSettings::m_minPowerThresholdDB, 0);
     m_settings.m_dsb = dsb;
     m_settings.m_spanLog2 = spanLog2;
     m_settings.m_rfBandwidth = bw * 100;
     m_settings.m_lowCutoff = lw * 100;
     applySettings(force);
     bool wasBlocked = blockApplySettings(true);
     m_channelMarker.setBandwidth(bw * 200);
     m_channelMarker.setSidebands(dsb ? ChannelMarker::dsb : bw < 0 ? ChannelMarker::lsb : ChannelMarker::usb);
     ui->dsb->setIcon(bw < 0 ? m_iconDSBLSB: m_iconDSBUSB);
     if (!dsb) { m_channelMarker.setLowCutoff(lw * 100); }
     blockApplySettings(wasBlocked);
 }
applySettings()
void SSBDemodGUI::applySettings (bool force = false) private
Definition at line 362 of file ssbdemodgui.cpp.
References SSBDemod::MsgConfigureSSBDemod::create(), SSBDemod::MsgConfigureChannelizer::create(), SSBDemod::getAudioSampleRate(), ChannelMarker::getCenterFrequency(), BasebandSampleSink::getInputMessageQueue(), m_channelMarker, m_doApplySettings, m_settings, m_ssbDemod, and MessageQueue::push().
Referenced by applyBandwidths(), audioSelect(), channelMarkerChangedByCursor(), on_agc_toggled(), on_agcClamping_toggled(), on_agcPowerThreshold_valueChanged(), on_agcThresholdGate_valueChanged(), on_agcTimeLog2_valueChanged(), on_audioBinaural_toggled(), on_audioFlipChannels_toggled(), on_audioMute_toggled(), on_deltaFrequency_changed(), on_volume_valueChanged(), onMenuDialogCalled(), and setCenterFrequency().
 {
     if (m_doApplySettings)
     {
         SSBDemod::MsgConfigureChannelizer* channelConfigMsg = SSBDemod::MsgConfigureChannelizer::create(
                 m_ssbDemod->getAudioSampleRate(), m_channelMarker.getCenterFrequency());
         m_ssbDemod->getInputMessageQueue()->push(channelConfigMsg);
         SSBDemod::MsgConfigureSSBDemod* message = SSBDemod::MsgConfigureSSBDemod::create( m_settings, force);
         m_ssbDemod->getInputMessageQueue()->push(message);
     }
 }
audioSelect
void SSBDemodGUI::audioSelect () private slot
Definition at line 610 of file ssbdemodgui.cpp.
References applySettings(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, SSBDemodSettings::m_audioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by SSBDemodGUI().
 {
     qDebug("SSBDemodGUI::audioSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName);
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_audioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
blockApplySettings()
bool SSBDemodGUI::blockApplySettings (bool block) private
Definition at line 355 of file ssbdemodgui.cpp.
References m_doApplySettings.
Referenced by applyBandwidths(), displaySettings(), and handleMessage().
 {
     bool ret = !m_doApplySettings;
     m_doApplySettings = !block;
     return ret;
 }
channelMarkerChangedByCursor
void SSBDemodGUI::channelMarkerChangedByCursor () slot
Definition at line 118 of file ssbdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, SSBDemodSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by SSBDemodGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
channelMarkerHighlightedByCursor
void SSBDemodGUI::channelMarkerHighlightedByCursor () slot
Definition at line 125 of file ssbdemodgui.cpp.
References ChannelMarker::getHighlighted(), m_channelMarker, and RollupWidget::setHighlighted().
Referenced by SSBDemodGUI().
 {
     setHighlighted(m_channelMarker.getHighlighted());
 }
create()
SSBDemodGUI * SSBDemodGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) static
Definition at line 21 of file ssbdemodgui.cpp.
References SSBDemodGUI().
Referenced by SSBPlugin::createRxChannelGUI().
 {
     SSBDemodGUI* gui = new SSBDemodGUI(pluginAPI, deviceUISet, rxChannel);
     return gui;
 }
deserialize()
bool SSBDemodGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 64 of file ssbdemodgui.cpp.
References applyBandwidths(), SSBDemodSettings::deserialize(), displaySettings(), m_settings, SSBDemodSettings::m_spanLog2, and SSBDemodSettings::resetToDefaults().
 {
     if(m_settings.deserialize(data))
     {
         displaySettings();
         applyBandwidths(m_settings.m_spanLog2, true); // does applySettings(true)
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         displaySettings();
         applyBandwidths(m_settings.m_spanLog2, true); // does applySettings(true)
         return false;
     }
 }
destroy()
void SSBDemodGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 27 of file ssbdemodgui.cpp.
 {
     delete this;
 }
displayAGCPowerThreshold()
void SSBDemodGUI::displayAGCPowerThreshold (int value) private
Definition at line 574 of file ssbdemodgui.cpp.
References SSBDemodSettings::m_minPowerThresholdDB, and ui.
Referenced by displaySettings(), and on_agcPowerThreshold_valueChanged().
 {
     if (value == SSBDemodSettings::m_minPowerThresholdDB)
     {
         ui->agcPowerThresholdText->setText("---");
     }
     else
     {
         QString s = QString::number(value, 'f', 0);
         ui->agcPowerThresholdText->setText(s);
     }
 }
displayAGCThresholdGate()
void SSBDemodGUI::displayAGCThresholdGate (int value) private
Definition at line 587 of file ssbdemodgui.cpp.
References ui.
Referenced by displaySettings().
 {
     QString s = QString::number(value, 'f', 0);
     ui->agcThresholdGateText->setText(s);
     int dialValue = value;
     if (value > 20) {
         dialValue = ((value - 20) / 10) + 20;
     }
     ui->agcThresholdGate->setValue(dialValue);
 }
displaySettings()
void SSBDemodGUI::displaySettings () private
Definition at line 492 of file ssbdemodgui.cpp.
References arg(), blockApplySettings(), displayAGCPowerThreshold(), displayAGCThresholdGate(), ChannelMarker::dsb, ChannelMarker::getCenterFrequency(), ChannelMarker::getTitle(), ChannelMarker::lsb, SSBDemodSettings::m_agc, SSBDemodSettings::m_agcClamping, SSBDemodSettings::m_agcPowerThreshold, SSBDemodSettings::m_agcThresholdGate, SSBDemodSettings::m_agcTimeLog2, SSBDemodSettings::m_audioBinaural, SSBDemodSettings::m_audioFlipChannels, SSBDemodSettings::m_audioMute, m_channelMarker, SSBDemodSettings::m_dsb, m_iconDSBLSB, m_iconDSBUSB, SSBDemodSettings::m_inputFrequencyOffset, SSBDemodSettings::m_lowCutoff, SSBDemodSettings::m_rfBandwidth, SSBDemodSettings::m_rgbColor, m_settings, SSBDemodSettings::m_spanLog2, SSBDemodSettings::m_title, SSBDemodSettings::m_volume, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setLowCutoff(), ChannelMarker::setSidebands(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ui, and ChannelMarker::usb.
Referenced by deserialize(), handleMessage(), and SSBDemodGUI().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setBandwidth(m_settings.m_rfBandwidth * 2);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.setLowCutoff(m_settings.m_lowCutoff);
     ui->flipSidebands->setEnabled(!m_settings.m_dsb);
     if (m_settings.m_dsb) {
         m_channelMarker.setSidebands(ChannelMarker::dsb);
     } else {
         if (m_settings.m_rfBandwidth < 0) {
             m_channelMarker.setSidebands(ChannelMarker::lsb);
             ui->dsb->setIcon(m_iconDSBLSB);
         } else {
             m_channelMarker.setSidebands(ChannelMarker::usb);
             ui->dsb->setIcon(m_iconDSBUSB);
         }
     }
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     ui->agc->setChecked(m_settings.m_agc);
     ui->agcClamping->setChecked(m_settings.m_agcClamping);
     ui->audioBinaural->setChecked(m_settings.m_audioBinaural);
     ui->audioFlipChannels->setChecked(m_settings.m_audioFlipChannels);
     ui->audioMute->setChecked(m_settings.m_audioMute);
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     // Prevent uncontrolled triggering of applyBandwidths
     ui->spanLog2->blockSignals(true);
     ui->dsb->blockSignals(true);
     ui->BW->blockSignals(true);
     ui->dsb->setChecked(m_settings.m_dsb);
     ui->spanLog2->setValue(5 - m_settings.m_spanLog2);
     ui->BW->setValue(m_settings.m_rfBandwidth / 100.0);
     QString s = QString::number(m_settings.m_rfBandwidth/1000.0, 'f', 1);
     if (m_settings.m_dsb)
     {
         ui->BWText->setText(tr("%1%2k").arg(QChar(0xB1, 0x00)).arg(s));
     }
     else
     {
         ui->BWText->setText(tr("%1k").arg(s));
     }
     ui->spanLog2->blockSignals(false);
     ui->dsb->blockSignals(false);
     ui->BW->blockSignals(false);
     // The only one of the four signals triggering applyBandwidths will trigger it once only with all other values
     // set correctly and therefore validate the settings and apply them to dependent widgets
     ui->lowCut->setValue(m_settings.m_lowCutoff / 100.0);
     ui->lowCutText->setText(tr("%1k").arg(m_settings.m_lowCutoff / 1000.0));
     ui->volume->setValue(m_settings.m_volume * 10.0);
     ui->volumeText->setText(QString("%1").arg(m_settings.m_volume, 0, 'f', 1));
     ui->agcTimeLog2->setValue(m_settings.m_agcTimeLog2);
     s = QString::number((1<<ui->agcTimeLog2->value()), 'f', 0);
     ui->agcTimeText->setText(s);
     ui->agcPowerThreshold->setValue(m_settings.m_agcPowerThreshold);
     displayAGCPowerThreshold(ui->agcPowerThreshold->value());
     displayAGCThresholdGate(m_settings.m_agcThresholdGate);
     blockApplySettings(false);
 }
enterEvent()
void SSBDemodGUI::enterEvent (QEvent *) private
Definition at line 605 of file ssbdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 SSBDemodGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 42 of file ssbdemodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
 {
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* SSBDemodGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 40 of file ssbdemodgui.h.
Referenced by handleInputMessages(), and SSBDemodGUI().
 { return &m_inputMessageQueue; }
getName()
QString SSBDemodGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 37 of file ssbdemodgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void SSBDemodGUI::handleInputMessages () private slot
Definition at line 105 of file ssbdemodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by SSBDemodGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
bool SSBDemodGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 81 of file ssbdemodgui.cpp.
References applyBandwidths(), blockApplySettings(), displaySettings(), SSBDemod::getAudioSampleRate(), SSBDemod::MsgConfigureSSBDemod::getSettings(), m_settings, m_ssbDemod, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (SSBDemod::MsgConfigureSSBDemod::match(message))
     {
         qDebug("SSBDemodGUI::handleMessage: SSBDemod::MsgConfigureSSBDemod");
         const SSBDemod::MsgConfigureSSBDemod& cfg = (SSBDemod::MsgConfigureSSBDemod&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (DSPConfigureAudio::match(message))
     {
         qDebug("SSBDemodGUI::handleMessage: DSPConfigureAudio: %d", m_ssbDemod->getAudioSampleRate());
         applyBandwidths(5 - ui->spanLog2->value()); // will update spectrum details with new sample rate
         return true;
     }
     else
     {
         return false;
     }
 }
leaveEvent()
void SSBDemodGUI::leaveEvent (QEvent *) private
Definition at line 600 of file ssbdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_agc_toggled
void SSBDemodGUI::on_agc_toggled (bool checked) private slot
Definition at line 176 of file ssbdemodgui.cpp.
References applySettings(), SSBDemodSettings::m_agc, and m_settings.
 {
     m_settings.m_agc = checked;
     applySettings();
 }
on_agcClamping_toggled
void SSBDemodGUI::on_agcClamping_toggled (bool checked) private slot
Definition at line 182 of file ssbdemodgui.cpp.
References applySettings(), SSBDemodSettings::m_agcClamping, and m_settings.
 {
     m_settings.m_agcClamping = checked;
     applySettings();
 }
on_agcPowerThreshold_valueChanged
void SSBDemodGUI::on_agcPowerThreshold_valueChanged (int value) private slot
Definition at line 196 of file ssbdemodgui.cpp.
References applySettings(), displayAGCPowerThreshold(), SSBDemodSettings::m_agcPowerThreshold, and m_settings.
 {
     displayAGCPowerThreshold(value);
     m_settings.m_agcPowerThreshold = value;
     applySettings();
 }
on_agcThresholdGate_valueChanged
void SSBDemodGUI::on_agcThresholdGate_valueChanged (int value) private slot
Definition at line 203 of file ssbdemodgui.cpp.
References applySettings(), SSBDemodSettings::m_agcThresholdGate, m_settings, and ui.
 {
     int agcThresholdGate = value < 20 ? value : ((value - 20) * 10) + 20;
     QString s = QString::number(agcThresholdGate, 'f', 0);
     ui->agcThresholdGateText->setText(s);
     m_settings.m_agcThresholdGate = agcThresholdGate;
     applySettings();
 }
on_agcTimeLog2_valueChanged
void SSBDemodGUI::on_agcTimeLog2_valueChanged (int value) private slot
Definition at line 188 of file ssbdemodgui.cpp.
References applySettings(), SSBDemodSettings::m_agcTimeLog2, m_settings, and ui.
 {
     QString s = QString::number((1<<value), 'f', 0);
     ui->agcTimeText->setText(s);
     m_settings.m_agcTimeLog2 = value;
     applySettings();
 }
on_audioBinaural_toggled
void SSBDemodGUI::on_audioBinaural_toggled (bool binaural) private slot
Definition at line 130 of file ssbdemodgui.cpp.
References applySettings(), SSBDemodSettings::m_audioBinaural, m_audioBinaural, and m_settings.
 {
     m_audioBinaural = binaural;
     m_settings.m_audioBinaural = binaural;
     applySettings();
 }
on_audioFlipChannels_toggled
void SSBDemodGUI::on_audioFlipChannels_toggled (bool flip) private slot
Definition at line 137 of file ssbdemodgui.cpp.
References applySettings(), SSBDemodSettings::m_audioFlipChannels, m_audioFlipChannels, and m_settings.
 {
     m_audioFlipChannels = flip;
     m_settings.m_audioFlipChannels = flip;
     applySettings();
 }
on_audioMute_toggled
void SSBDemodGUI::on_audioMute_toggled (bool checked) private slot
Definition at line 212 of file ssbdemodgui.cpp.
References applySettings(), SSBDemodSettings::m_audioMute, m_audioMute, and m_settings.
 {
     m_audioMute = checked;
     m_settings.m_audioMute = checked;
     applySettings();
 }
on_BW_valueChanged
void SSBDemodGUI::on_BW_valueChanged (int value) private slot
Definition at line 157 of file ssbdemodgui.cpp.
References applyBandwidths(), and ui.
 {
     (void) value;
     applyBandwidths(5 - ui->spanLog2->value());
 }
on_deltaFrequency_changed
void SSBDemodGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 150 of file ssbdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, SSBDemodSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_dsb_toggled
void SSBDemodGUI::on_dsb_toggled (bool dsb) private slot
Definition at line 144 of file ssbdemodgui.cpp.
References applyBandwidths(), and ui.
 {
     ui->flipSidebands->setEnabled(!dsb);
     applyBandwidths(5 - ui->spanLog2->value());
 }
on_flipSidebands_clicked
void SSBDemodGUI::on_flipSidebands_clicked (bool checked) private slot
Definition at line 228 of file ssbdemodgui.cpp.
References ui.
 {
     (void) checked;
     int bwValue = ui->BW->value();
     int lcValue = ui->lowCut->value();
     ui->BW->setValue(-bwValue);
     ui->lowCut->setValue(-lcValue);
 }
on_lowCut_valueChanged
void SSBDemodGUI::on_lowCut_valueChanged (int value) private slot
Definition at line 163 of file ssbdemodgui.cpp.
References applyBandwidths(), and ui.
 {
     (void) value;
     applyBandwidths(5 - ui->spanLog2->value());
 }
on_spanLog2_valueChanged
void SSBDemodGUI::on_spanLog2_valueChanged (int value) private slot
Definition at line 219 of file ssbdemodgui.cpp.
References applyBandwidths(), and ui.
 {
     if ((value < 0) || (value > 4)) {
         return;
     }
     applyBandwidths(5 - ui->spanLog2->value());
 }
on_volume_valueChanged
void SSBDemodGUI::on_volume_valueChanged (int value) private slot
Definition at line 169 of file ssbdemodgui.cpp.
References applySettings(), arg(), m_settings, SSBDemodSettings::m_volume, and ui.
 {
     ui->volumeText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_volume = value / 10.0;
     applySettings();
 }
onMenuDialogCalled
void SSBDemodGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 237 of file ssbdemodgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, SSBDemodSettings::m_inputFrequencyOffset, SSBDemodSettings::m_reverseAPIAddress, SSBDemodSettings::m_reverseAPIChannelIndex, SSBDemodSettings::m_reverseAPIDeviceIndex, SSBDemodSettings::m_reverseAPIPort, SSBDemodSettings::m_rgbColor, m_settings, SSBDemodSettings::m_title, SSBDemodSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by SSBDemodGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void SSBDemodGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 269 of file ssbdemodgui.cpp.
Referenced by SSBDemodGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void SSBDemodGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 54 of file ssbdemodgui.cpp.
References m_settings, and SSBDemodSettings::resetToDefaults().
 {
     m_settings.resetToDefaults();
 }
serialize()
QByteArray SSBDemodGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 59 of file ssbdemodgui.cpp.
References m_settings, and SSBDemodSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void SSBDemodGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 47 of file ssbdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, SSBDemodSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
setName()
void SSBDemodGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 32 of file ssbdemodgui.cpp.
 {
     setObjectName(name);
 }
spanLog2Limit()
int SSBDemodGUI::spanLog2Limit (int spanLog2) private
Definition at line 375 of file ssbdemodgui.cpp.
References SSBDemod::getAudioSampleRate(), SSBDemod::getInputSampleRate(), and m_ssbDemod.
Referenced by applyBandwidths().
 {
     while (((m_ssbDemod->getAudioSampleRate() / (1<<spanLog2)) > m_ssbDemod->getInputSampleRate()) && (spanLog2 < 4)) {
         spanLog2++;
     }
     return spanLog2;
 }
tick
void SSBDemodGUI::tick () private slot
Definition at line 623 of file ssbdemodgui.cpp.
References arg(), CalcDb::dbPower(), SSBDemod::getAudioActive(), SSBDemod::getMagSqLevels(), SSBDemodSettings::m_mminPowerThresholdDBf, m_squelchOpen, m_ssbDemod, m_tickCount, and ui.
Referenced by SSBDemodGUI().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     m_ssbDemod->getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     double powDbAvg = CalcDb::dbPower(magsqAvg);
     double powDbPeak = CalcDb::dbPower(magsqPeak);
     ui->channelPowerMeter->levelChanged(
             (SSBDemodSettings::m_mminPowerThresholdDBf + powDbAvg) / SSBDemodSettings::m_mminPowerThresholdDBf,
             (SSBDemodSettings::m_mminPowerThresholdDBf + powDbPeak) / SSBDemodSettings::m_mminPowerThresholdDBf,
             nbMagsqSamples);
     if (m_tickCount % 4 == 0) {
         ui->channelPower->setText(tr("%1 dB").arg(powDbAvg, 0, 'f', 1));
     }
     bool squelchOpen = m_ssbDemod->getAudioActive();
     if (squelchOpen != m_squelchOpen)
     {
         if (squelchOpen) {
             ui->audioMute->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->audioMute->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         }
         m_squelchOpen = squelchOpen;
     }
     m_tickCount++;
 }
Member Data Documentation
m_audioBinaural
bool SSBDemodGUI::m_audioBinaural private
Definition at line 55 of file ssbdemodgui.h.
Referenced by on_audioBinaural_toggled().
m_audioFlipChannels
bool SSBDemodGUI::m_audioFlipChannels private
Definition at line 56 of file ssbdemodgui.h.
Referenced by on_audioFlipChannels_toggled().
m_audioMute
bool SSBDemodGUI::m_audioMute private
Definition at line 57 of file ssbdemodgui.h.
Referenced by on_audioMute_toggled().
m_channelMarker
ChannelMarker SSBDemodGUI::m_channelMarker private
Definition at line 51 of file ssbdemodgui.h.
Referenced by applyBandwidths(), applySettings(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), onMenuDialogCalled(), setCenterFrequency(), and SSBDemodGUI().
m_deviceUISet
DeviceUISet* SSBDemodGUI::m_deviceUISet private
Definition at line 50 of file ssbdemodgui.h.
Referenced by SSBDemodGUI(), and ~SSBDemodGUI().
m_doApplySettings
bool SSBDemodGUI::m_doApplySettings private
Definition at line 53 of file ssbdemodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_iconDSBLSB
QIcon SSBDemodGUI::m_iconDSBLSB private
Definition at line 66 of file ssbdemodgui.h.
Referenced by applyBandwidths(), displaySettings(), and SSBDemodGUI().
m_iconDSBUSB
QIcon SSBDemodGUI::m_iconDSBUSB private
Definition at line 65 of file ssbdemodgui.h.
Referenced by applyBandwidths(), displaySettings(), and SSBDemodGUI().
m_inputMessageQueue
MessageQueue SSBDemodGUI::m_inputMessageQueue private
Definition at line 63 of file ssbdemodgui.h.
m_pluginAPI
PluginAPI* SSBDemodGUI::m_pluginAPI private
Definition at line 49 of file ssbdemodgui.h.
m_settings
SSBDemodSettings SSBDemodGUI::m_settings private
Definition at line 52 of file ssbdemodgui.h.
Referenced by applyBandwidths(), applySettings(), audioSelect(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), handleMessage(), on_agc_toggled(), on_agcClamping_toggled(), on_agcPowerThreshold_valueChanged(), on_agcThresholdGate_valueChanged(), on_agcTimeLog2_valueChanged(), on_audioBinaural_toggled(), on_audioFlipChannels_toggled(), on_audioMute_toggled(), on_deltaFrequency_changed(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), serialize(), setCenterFrequency(), and SSBDemodGUI().
m_spectrumRate
int SSBDemodGUI::m_spectrumRate private
Definition at line 54 of file ssbdemodgui.h.
Referenced by applyBandwidths(), and SSBDemodGUI().
m_spectrumVis
SpectrumVis* SSBDemodGUI::m_spectrumVis private
Definition at line 62 of file ssbdemodgui.h.
Referenced by SSBDemodGUI(), and ~SSBDemodGUI().
m_squelchOpen
bool SSBDemodGUI::m_squelchOpen private
Definition at line 58 of file ssbdemodgui.h.
Referenced by tick().
m_ssbDemod
SSBDemod* SSBDemodGUI::m_ssbDemod private
Definition at line 61 of file ssbdemodgui.h.
Referenced by applyBandwidths(), applySettings(), handleMessage(), spanLog2Limit(), SSBDemodGUI(), tick(), and ~SSBDemodGUI().
m_tickCount
uint32_t SSBDemodGUI::m_tickCount private
Definition at line 59 of file ssbdemodgui.h.
Referenced by tick().
ui
Ui::SSBDemodGUI* SSBDemodGUI::ui private
Definition at line 48 of file ssbdemodgui.h.
Referenced by applyBandwidths(), channelMarkerChangedByCursor(), displayAGCPowerThreshold(), displayAGCThresholdGate(), displaySettings(), handleMessage(), on_agcThresholdGate_valueChanged(), on_agcTimeLog2_valueChanged(), on_BW_valueChanged(), on_dsb_toggled(), on_flipSidebands_clicked(), on_lowCut_valueChanged(), on_spanLog2_valueChanged(), on_volume_valueChanged(), SSBDemodGUI(), tick(), and ~SSBDemodGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/demodssb/ssbdemodgui.h
plugins/channelrx/demodssb/ssbdemodgui.cpp