SDRAngel: RTLSDRPlugin Class Reference
RTLSDRPlugin Class Reference
#include <rtlsdrplugin.h>
Public Member Functions
RTLSDRPlugin (QObject *parent=NULL)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "RTLSDR"
static const QString m_deviceTypeID = RTLSDR_DEVICE_TYPE_ID
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 11 of file rtlsdrplugin.h.
Constructor & Destructor Documentation
RTLSDRPlugin()
RTLSDRPlugin::RTLSDRPlugin (QObject * parent = NULL) explicit
Definition at line 26 of file rtlsdrplugin.cpp.
                                           :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSourcePluginInstance()
DeviceSampleSource * RTLSDRPlugin::createSampleSourcePluginInstance (const QString & sourceId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 98 of file rtlsdrplugin.cpp.
References m_deviceTypeID.
 {
     if (sourceId == m_deviceTypeID)
     {
         RTLSDRInput* input = new RTLSDRInput(deviceAPI);
         return input;
     }
     else
     {
         return 0;
     }
 }
createSampleSourcePluginInstanceGUI()
PluginInstanceGUI * RTLSDRPlugin::createSampleSourcePluginInstanceGUI (const QString & sourceId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 83 of file rtlsdrplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSources().
 {
     if(sourceId == m_deviceTypeID) {
         RTLSDRGui* gui = new RTLSDRGui(deviceUISet);
         *widget = gui;
         return gui;
     } else {
         return 0;
     }
 }
enumSampleSources()
PluginInterface::SamplingDevices RTLSDRPlugin::enumSampleSources () virtual
Reimplemented from PluginInterface.
Definition at line 41 of file rtlsdrplugin.cpp.
References arg(), createSampleSourcePluginInstanceGUI(), i, m_deviceTypeID, m_hardwareID, PluginInterface::SamplingDevice::PhysicalDevice, and PluginInterface::SamplingDevice::StreamSingleRx.
 {
     SamplingDevices result;
     int count = rtlsdr_get_device_count();
     char vendor[256];
     char product[256];
     char serial[256];
     for(int i = 0; i < count; i++) {
         vendor[0] = '\0';
         product[0] = '\0';
         serial[0] = '\0';
         if(rtlsdr_get_device_usb_strings((uint32_t)i, vendor, product, serial) != 0)
             continue;
         QString displayedName(QString("RTL-SDR[%1] %2").arg(i).arg(serial));
         result.append(SamplingDevice(displayedName,
                 m_hardwareID,
                 m_deviceTypeID,
                 QString(serial),
                 i,
                 PluginInterface::SamplingDevice::PhysicalDevice,
                 PluginInterface::SamplingDevice::StreamSingleRx,
                 1,
                 0));
     }
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & RTLSDRPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 31 of file rtlsdrplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void RTLSDRPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 36 of file rtlsdrplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSource().
 {
     pluginAPI->registerSampleSource(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString RTLSDRPlugin::m_deviceTypeID = RTLSDR_DEVICE_TYPE_ID static
Definition at line 30 of file rtlsdrplugin.h.
Referenced by createSampleSourcePluginInstance(), createSampleSourcePluginInstanceGUI(), enumSampleSources(), and initPlugin().
m_hardwareID
const QString RTLSDRPlugin::m_hardwareID = "RTLSDR" static
Definition at line 29 of file rtlsdrplugin.h.
Referenced by enumSampleSources().
m_pluginDescriptor
const PluginDescriptor RTLSDRPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("RTL-SDR Input"),
    QString("4.5.4"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 33 of file rtlsdrplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesource/rtlsdr/rtlsdrplugin.h
plugins/samplesource/rtlsdr/rtlsdrplugin.cpp