SDRAngel: LocalSource::MsgConfigureLocalSource Class Reference
LocalSource::MsgConfigureLocalSource Class Reference
#include <localsource.h>
Public Member Functions
const LocalSourceSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureLocalSource * create (const LocalSourceSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureLocalSource (const LocalSourceSettings &settings, bool force)
Private Attributes
LocalSourceSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 41 of file localsource.h.
Constructor & Destructor Documentation
MsgConfigureLocalSource()
LocalSource::MsgConfigureLocalSource::MsgConfigureLocalSource (const LocalSourceSettings & settings, bool force) inline private
Definition at line 57 of file localsource.h.
Referenced by create().
                                                                                  :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureLocalSource* LocalSource::MsgConfigureLocalSource::create (const LocalSourceSettings & settings, bool force) inline static
Definition at line 48 of file localsource.h.
References MsgConfigureLocalSource().
Referenced by LocalSourceGUI::applySettings(), LocalSource::deserialize(), and LocalSource::webapiSettingsPutPatch().
         {
             return new MsgConfigureLocalSource(settings, force);
         }
getForce()
bool LocalSource::MsgConfigureLocalSource::getForce () const inline
Definition at line 46 of file localsource.h.
References m_force.
Referenced by LocalSource::handleMessage().
 { return m_force; }
getSettings()
const LocalSourceSettings& LocalSource::MsgConfigureLocalSource::getSettings () const inline
Definition at line 45 of file localsource.h.
References m_settings.
Referenced by LocalSourceGUI::handleMessage(), and LocalSource::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool LocalSource::MsgConfigureLocalSource::m_force private
Definition at line 55 of file localsource.h.
Referenced by getForce().
m_settings
LocalSourceSettings LocalSource::MsgConfigureLocalSource::m_settings private
Definition at line 54 of file localsource.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/channeltx/localsource/localsource.h