SDRAngel: UDPSink::MsgConfigureUDPSource Class Reference
UDPSink::MsgConfigureUDPSource Class Reference
#include <udpsink.h>
Public Member Functions
const UDPSinkSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureUDPSource * create (const UDPSinkSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureUDPSource (const UDPSinkSettings &settings, bool force)
Private Attributes
UDPSinkSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 52 of file udpsink.h.
Constructor & Destructor Documentation
MsgConfigureUDPSource()
UDPSink::MsgConfigureUDPSource::MsgConfigureUDPSource (const UDPSinkSettings & settings, bool force) inline private
Definition at line 68 of file udpsink.h.
Referenced by create().
                                                                            :
             Message(),
             m_settings(settings),
             m_force(force)
         {
         }
Member Function Documentation
create()
static MsgConfigureUDPSource* UDPSink::MsgConfigureUDPSource::create (const UDPSinkSettings & settings, bool force) inline static
Definition at line 59 of file udpsink.h.
References MsgConfigureUDPSource().
Referenced by UDPSinkGUI::applySettings(), UDPSinkGUI::applySettingsImmediate(), UDPSink::deserialize(), and UDPSink::webapiSettingsPutPatch().
         {
             return new MsgConfigureUDPSource(settings, force);
         }
getForce()
bool UDPSink::MsgConfigureUDPSource::getForce () const inline
Definition at line 57 of file udpsink.h.
References m_force.
Referenced by UDPSink::handleMessage().
 { return m_force; }
getSettings()
const UDPSinkSettings& UDPSink::MsgConfigureUDPSource::getSettings () const inline
Definition at line 56 of file udpsink.h.
References m_settings.
Referenced by UDPSinkGUI::handleMessage(), and UDPSink::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool UDPSink::MsgConfigureUDPSource::m_force private
Definition at line 66 of file udpsink.h.
Referenced by getForce().
m_settings
UDPSinkSettings UDPSink::MsgConfigureUDPSource::m_settings private
Definition at line 65 of file udpsink.h.
Referenced by UDPSink::getCenterFrequency(), getSettings(), UDPSink::getStreamCenterFrequency(), and UDPSink::getTitle().
The documentation for this class was generated from the following file:
plugins/channelrx/udpsink/udpsink.h