SDRAngel: qrtplib::RTPTimeInitializerObject Class Reference
qrtplib::RTPTimeInitializerObject Class Reference
#include <rtptimeutilities.h>
Public Member Functions
RTPTimeInitializerObject ()
void Dummy ()
Private Attributes
int dummy
Detailed Description
Definition at line 403 of file rtptimeutilities.h.
Constructor & Destructor Documentation
RTPTimeInitializerObject()
qrtplib::RTPTimeInitializerObject::RTPTimeInitializerObject ()
Definition at line 39 of file rtptimeutilities.cpp.
References dummy.
 {
     dummy = -1;
 }
Member Function Documentation
Dummy()
void qrtplib::RTPTimeInitializerObject::Dummy () inline
Definition at line 407 of file rtptimeutilities.h.
Referenced by qrtplib::RTCPPacketBuilder::RTCPPacketBuilder(), qrtplib::RTCPSchedulerParams::RTCPSchedulerParams(), qrtplib::RTPCollisionList::RTPCollisionList(), qrtplib::RTPPacketBuilder::RTPPacketBuilder(), qrtplib::RTPSession::RTPSession(), and qrtplib::RTPTransmitter::RTPTransmitter().
     {
         dummy++;
     }
Member Data Documentation
dummy
int qrtplib::RTPTimeInitializerObject::dummy private
Definition at line 412 of file rtptimeutilities.h.
Referenced by RTPTimeInitializerObject().
The documentation for this class was generated from the following files:
qrtplib/rtptimeutilities.h
qrtplib/rtptimeutilities.cpp