SDRAngel: FileSinkOutput Class Reference
FileSinkOutput Class Reference
#include <filesinkoutput.h>
Classes
class MsgConfigureFileSink
class MsgConfigureFileSinkName
class MsgConfigureFileSinkStreamTiming
class MsgConfigureFileSinkWork
class MsgReportFileSinkGeneration
class MsgReportFileSinkStreamTiming
class MsgStartStop
Public Member Functions
FileSinkOutput (DeviceAPI *deviceAPI)
virtual ~FileSinkOutput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the sink.
virtual void setSampleRate (int sampleRate)
For when the sink sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the sink.
virtual void setCenterFrequency (qint64 centerFrequency)
std::time_t getStartingTimeStamp () const
virtual bool handleMessage (const Message &message)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSink
DeviceSampleSink ()
virtual ~DeviceSampleSink ()
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSourceFifo * getSampleFifo ()
Private Member Functions
void openFileStream ()
void applySettings (const FileSinkSettings &settings, bool force=false)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
FileSinkSettings m_settings
std::ofstream m_ofstream
FileSinkThread * m_fileSinkThread
QString m_deviceDescription
QString m_fileName
std::time_t m_startingTimeStamp
const QTimer & m_masterTimer
Additional Inherited Members
Public Types inherited from DeviceSampleSink
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
Static Public Member Functions inherited from DeviceSampleSink
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Interp, fcPos_t fcPos, quint32 devSampleRate)
Protected Slots inherited from DeviceSampleSink
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSink
SampleSourceFifo m_sampleSourceFifo
MessageQueue m_inputMessageQueue
Input queue to the sink.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 33 of file filesinkoutput.h.
Constructor & Destructor Documentation
FileSinkOutput()
FileSinkOutput::FileSinkOutput (DeviceAPI * deviceAPI)
Definition at line 43 of file filesinkoutput.cpp.
Referenced by FileSinkOutput::MsgReportFileSinkStreamTiming::MsgReportFileSinkStreamTiming().
                                                    :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_fileSinkThread(0),
     m_deviceDescription("FileSink"),
     m_fileName("./test.sdriq"),
     m_startingTimeStamp(0),
     m_masterTimer(deviceAPI->getMasterTimer())
 {
     m_deviceAPI->setNbSinkStreams(1);
 }
~FileSinkOutput()
FileSinkOutput::~FileSinkOutput () virtual
Definition at line 55 of file filesinkoutput.cpp.
References stop().
Referenced by FileSinkOutput::MsgReportFileSinkStreamTiming::MsgReportFileSinkStreamTiming().
 {
     stop();
 }
Member Function Documentation
applySettings()
void FileSinkOutput::applySettings (const FileSinkSettings & settings, bool force = false) private
Definition at line 274 of file filesinkoutput.cpp.
References DeviceAPI::getDeviceEngineInputMessageQueue(), FileSinkSettings::m_centerFrequency, m_deviceAPI, m_fileSinkThread, FileSinkSettings::m_log2Interp, m_mutex, FileSinkSettings::m_sampleRate, m_settings, MessageQueue::push(), FileSinkThread::setLog2Interpolation(), and FileSinkThread::setSamplerate().
Referenced by handleMessage(), and init().
 {
     QMutexLocker mutexLocker(&m_mutex);
     bool forwardChange = false;
     if (force || (m_settings.m_centerFrequency != settings.m_centerFrequency))
     {
         m_settings.m_centerFrequency = settings.m_centerFrequency;
         forwardChange = true;
     }
     if (force || (m_settings.m_sampleRate != settings.m_sampleRate))
     {
         m_settings.m_sampleRate = settings.m_sampleRate;
         if (m_fileSinkThread != 0)
         {
             m_fileSinkThread->setSamplerate(m_settings.m_sampleRate);
         }
         forwardChange = true;
     }
     if (force || (m_settings.m_log2Interp != settings.m_log2Interp))
     {
         m_settings.m_log2Interp = settings.m_log2Interp;
         if (m_fileSinkThread != 0)
         {
             m_fileSinkThread->setLog2Interpolation(m_settings.m_log2Interp);
         }
         forwardChange = true;
     }
     if (forwardChange)
     {
         qDebug("FileSinkOutput::applySettings: forward: m_centerFrequency: %llu m_sampleRate: %llu m_log2Interp: %d",
                 m_settings.m_centerFrequency,
                 m_settings.m_sampleRate,
                 m_settings.m_log2Interp);
         DSPSignalNotification *notif = new DSPSignalNotification(m_settings.m_sampleRate, m_settings.m_centerFrequency);
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
 }
deserialize()
bool FileSinkOutput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSink.
Definition at line 145 of file filesinkoutput.cpp.
References FileSinkOutput::MsgConfigureFileSink::create(), FileSinkSettings::deserialize(), DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and FileSinkSettings::resetToDefaults().
Referenced by FileSinkOutput::MsgReportFileSinkStreamTiming::MsgReportFileSinkStreamTiming().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureFileSink* message = MsgConfigureFileSink::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureFileSink* messageToGUI = MsgConfigureFileSink::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void FileSinkOutput::destroy () virtual
Implements DeviceSampleSink.
Definition at line 60 of file filesinkoutput.cpp.
Referenced by FileSinkOutput::MsgReportFileSinkStreamTiming::MsgReportFileSinkStreamTiming().
 {
     delete this;
 }
getCenterFrequency()
quint64 FileSinkOutput::getCenterFrequency () const virtual
Center frequency exposed by the sink.
Implements DeviceSampleSink.
Definition at line 177 of file filesinkoutput.cpp.
References FileSinkSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & FileSinkOutput::getDeviceDescription () const virtual
Implements DeviceSampleSink.
Definition at line 167 of file filesinkoutput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getSampleRate()
int FileSinkOutput::getSampleRate () const virtual
Sample rate exposed by the sink.
Implements DeviceSampleSink.
Definition at line 172 of file filesinkoutput.cpp.
References FileSinkSettings::m_sampleRate, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     return m_settings.m_sampleRate;
 }
getStartingTimeStamp()
std::time_t FileSinkOutput::getStartingTimeStamp () const
Definition at line 197 of file filesinkoutput.cpp.
References m_startingTimeStamp.
Referenced by setSampleRate().
 {
     return m_startingTimeStamp;
 }
handleMessage()
bool FileSinkOutput::handleMessage (const Message & message) virtual
Implements DeviceSampleSink.
Definition at line 202 of file filesinkoutput.cpp.
References applySettings(), FileSinkOutput::MsgReportFileSinkStreamTiming::create(), FileSinkOutput::MsgConfigureFileSinkName::getFileName(), FileSinkOutput::MsgConfigureFileSink::getForce(), DeviceSampleSink::getMessageQueueToGUI(), FileSinkThread::getSamplesCount(), FileSinkOutput::MsgConfigureFileSink::getSettings(), FileSinkOutput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), FileSinkOutput::MsgConfigureFileSinkWork::isWorking(), m_deviceAPI, m_fileName, m_fileSinkThread, Message::match(), openFileStream(), MessageQueue::push(), DeviceAPI::startDeviceEngine(), FileSinkThread::startWork(), DeviceAPI::stopDeviceEngine(), and FileSinkThread::stopWork().
Referenced by setSampleRate().
 {
     if (MsgConfigureFileSinkName::match(message))
     {
         MsgConfigureFileSinkName& conf = (MsgConfigureFileSinkName&) message;
         m_fileName = conf.getFileName();
         openFileStream();
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "FileSinkOutput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         return true;
     }
     else if (MsgConfigureFileSink::match(message))
     {
         qDebug() << "FileSinkOutput::handleMessage: MsgConfigureFileSink";
         MsgConfigureFileSink& conf = (MsgConfigureFileSink&) message;
         applySettings(conf.getSettings(), conf.getForce());
         return true;
     }
     else if (MsgConfigureFileSinkWork::match(message))
     {
         MsgConfigureFileSinkWork& conf = (MsgConfigureFileSinkWork&) message;
         bool working = conf.isWorking();
         if (m_fileSinkThread != 0)
         {
             if (working)
             {
                 m_fileSinkThread->startWork();
             }
             else
             {
                 m_fileSinkThread->stopWork();
             }
         }
         return true;
     }
     else if (MsgConfigureFileSinkStreamTiming::match(message))
     {
         MsgReportFileSinkStreamTiming *report;
         if (m_fileSinkThread != 0 && getMessageQueueToGUI())
         {
             report = MsgReportFileSinkStreamTiming::create(m_fileSinkThread->getSamplesCount());
             getMessageQueueToGUI()->push(report);
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void FileSinkOutput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSink.
Definition at line 86 of file filesinkoutput.cpp.
References applySettings(), and m_settings.
Referenced by FileSinkOutput::MsgReportFileSinkStreamTiming::MsgReportFileSinkStreamTiming().
 {
     applySettings(m_settings, true);
 }
openFileStream()
void FileSinkOutput::openFileStream () private
Definition at line 65 of file filesinkoutput.cpp.
References FileRecord::Header::centerFrequency, FileSinkSettings::m_centerFrequency, m_fileName, FileSinkSettings::m_log2Interp, m_ofstream, FileSinkSettings::m_sampleRate, m_settings, m_startingTimeStamp, FileRecord::Header::sampleRate, FileRecord::Header::sampleSize, SDR_RX_SAMP_SZ, FileRecord::Header::startTimeStamp, and FileRecord::writeHeader().
Referenced by handleMessage(), and start().
 {
     if (m_ofstream.is_open()) {
         m_ofstream.close();
     }
     m_ofstream.open(m_fileName.toStdString().c_str(), std::ios::binary);
     FileRecord::Header header;
     int actualSampleRate = m_settings.m_sampleRate * (1<<m_settings.m_log2Interp);
     header.sampleRate = actualSampleRate;
     header.centerFrequency = m_settings.m_centerFrequency;
     m_startingTimeStamp = time(0);
     header.startTimeStamp = m_startingTimeStamp;
     header.sampleSize = SDR_RX_SAMP_SZ;
     FileRecord::writeHeader(m_ofstream, header);
     qDebug() << "FileSinkOutput::openFileStream: " << m_fileName.toStdString().c_str();
 }
serialize()
QByteArray FileSinkOutput::serialize () const virtual
Implements DeviceSampleSink.
Definition at line 140 of file filesinkoutput.cpp.
References m_settings, and FileSinkSettings::serialize().
Referenced by FileSinkOutput::MsgReportFileSinkStreamTiming::MsgReportFileSinkStreamTiming().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void FileSinkOutput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSink.
Definition at line 182 of file filesinkoutput.cpp.
References FileSinkOutput::MsgConfigureFileSink::create(), FileSinkSettings::m_centerFrequency, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     FileSinkSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureFileSink* message = MsgConfigureFileSink::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureFileSink* messageToGUI = MsgConfigureFileSink::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setMessageQueueToGUI()
virtual void FileSinkOutput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSink.
Definition at line 185 of file filesinkoutput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSink::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void FileSinkOutput::setSampleRate (int sampleRate) inline virtual
For when the sink sample rate is set externally.
Implements DeviceSampleSink.
Definition at line 188 of file filesinkoutput.h.
References getCenterFrequency(), getStartingTimeStamp(), handleMessage(), setCenterFrequency(), webapiRun(), and webapiRunGet().
 { (void) sampleRate; }
start()
bool FileSinkOutput::start () virtual
Implements DeviceSampleSink.
Definition at line 91 of file filesinkoutput.cpp.
References FileSinkThread::connectTimer(), FileSinkOutput::MsgReportFileSinkGeneration::create(), DeviceSampleSink::getMessageQueueToGUI(), m_fileSinkThread, FileSinkSettings::m_log2Interp, m_masterTimer, m_mutex, m_ofstream, FileSinkSettings::m_sampleRate, DeviceSampleSink::m_sampleSourceFifo, m_settings, openFileStream(), MessageQueue::push(), FileSinkThread::setLog2Interpolation(), FileSinkThread::setSamplerate(), and FileSinkThread::startWork().
Referenced by FileSinkOutput::MsgReportFileSinkStreamTiming::MsgReportFileSinkStreamTiming().
 {
     QMutexLocker mutexLocker(&m_mutex);
     qDebug() << "FileSinkOutput::start";
     openFileStream();
     m_fileSinkThread = new FileSinkThread(&m_ofstream, &m_sampleSourceFifo);
     m_fileSinkThread->setSamplerate(m_settings.m_sampleRate);
     m_fileSinkThread->setLog2Interpolation(m_settings.m_log2Interp);
     m_fileSinkThread->connectTimer(m_masterTimer);
     m_fileSinkThread->startWork();
     mutexLocker.unlock();
     //applySettings(m_generalSettings, m_settings, true);
     qDebug("FileSinkOutput::start: started");
     if (getMessageQueueToGUI())
     {
         MsgReportFileSinkGeneration *report = MsgReportFileSinkGeneration::create(true); // acquisition on
         getMessageQueueToGUI()->push(report);
     }
     return true;
 }
stop()
void FileSinkOutput::stop () virtual
Implements DeviceSampleSink.
Definition at line 117 of file filesinkoutput.cpp.
References FileSinkOutput::MsgReportFileSinkGeneration::create(), DeviceSampleSink::getMessageQueueToGUI(), m_fileSinkThread, m_mutex, m_ofstream, MessageQueue::push(), and FileSinkThread::stopWork().
Referenced by FileSinkOutput::MsgReportFileSinkStreamTiming::MsgReportFileSinkStreamTiming(), and ~FileSinkOutput().
 {
     qDebug() << "FileSourceInput::stop";
     QMutexLocker mutexLocker(&m_mutex);
     if(m_fileSinkThread != 0)
     {
         m_fileSinkThread->stopWork();
         delete m_fileSinkThread;
         m_fileSinkThread = 0;
     }
     if (m_ofstream.is_open()) {
         m_ofstream.close();
     }
     if (getMessageQueueToGUI())
     {
         MsgReportFileSinkGeneration *report = MsgReportFileSinkGeneration::create(false); // acquisition off
         getMessageQueueToGUI()->push(report);
     }
 }
webapiRun()
int FileSinkOutput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 330 of file filesinkoutput.cpp.
References FileSinkOutput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgStartStop *messagetoGui = MsgStartStop::create(run);
         m_guiMessageQueue->push(messagetoGui);
     }
     return 200;
 }
webapiRunGet()
int FileSinkOutput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 321 of file filesinkoutput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
Member Data Documentation
m_deviceAPI
DeviceAPI* FileSinkOutput::m_deviceAPI private
Definition at line 205 of file filesinkoutput.h.
Referenced by applySettings(), handleMessage(), webapiRun(), and webapiRunGet().
m_deviceDescription
QString FileSinkOutput::m_deviceDescription private
Definition at line 210 of file filesinkoutput.h.
Referenced by getDeviceDescription().
m_fileName
QString FileSinkOutput::m_fileName private
Definition at line 211 of file filesinkoutput.h.
Referenced by FileSinkOutput::MsgConfigureFileSinkName::getFileName(), handleMessage(), and openFileStream().
m_fileSinkThread
FileSinkThread* FileSinkOutput::m_fileSinkThread private
Definition at line 209 of file filesinkoutput.h.
Referenced by applySettings(), handleMessage(), start(), and stop().
m_masterTimer
const QTimer& FileSinkOutput::m_masterTimer private
Definition at line 213 of file filesinkoutput.h.
Referenced by start().
m_mutex
QMutex FileSinkOutput::m_mutex private
Definition at line 206 of file filesinkoutput.h.
Referenced by applySettings(), start(), and stop().
m_ofstream
std::ofstream FileSinkOutput::m_ofstream private
Definition at line 208 of file filesinkoutput.h.
Referenced by openFileStream(), start(), and stop().
m_settings
FileSinkSettings FileSinkOutput::m_settings private
Definition at line 207 of file filesinkoutput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), init(), openFileStream(), serialize(), setCenterFrequency(), and start().
m_startingTimeStamp
std::time_t FileSinkOutput::m_startingTimeStamp private
Definition at line 212 of file filesinkoutput.h.
Referenced by getStartingTimeStamp(), and openFileStream().
The documentation for this class was generated from the following files:
plugins/samplesink/filesink/filesinkoutput.h
plugins/samplesink/filesink/filesinkoutput.cpp