SDRAngel: LimeSDRInputThread Class Reference
LimeSDRInputThread Class Reference
#include <limesdrinputthread.h>
Public Member Functions
LimeSDRInputThread (lms_stream_t *stream, SampleSinkFifo *sampleFifo, QObject *parent=0)
~LimeSDRInputThread ()
virtual void startWork ()
virtual void stopWork ()
virtual void setDeviceSampleRate (int sampleRate)
virtual bool isRunning ()
void setLog2Decimation (unsigned int log2_decim)
Private Member Functions
void run ()
void callback (const qint16 *buf, qint32 len)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
lms_stream_t * m_stream
qint16 m_buf [2 *LIMESDR_BLOCKSIZE]
SampleVector m_convertBuffer
SampleSinkFifo * m_sampleFifo
unsigned int m_log2Decim
Decimators< qint32, qint16, SDR_RX_SAMP_SZ, 12 > m_decimators
Detailed Description
Definition at line 33 of file limesdrinputthread.h.
Constructor & Destructor Documentation
LimeSDRInputThread()
LimeSDRInputThread::LimeSDRInputThread (lms_stream_t * stream, SampleSinkFifo * sampleFifo, QObject * parent = 0)
Definition at line 24 of file limesdrinputthread.cpp.
References LIMESDR_BLOCKSIZE, and m_buf.
                                                                                                         :
     QThread(parent),
     m_running(false),
     m_stream(stream),
     m_convertBuffer(LIMESDR_BLOCKSIZE),
     m_sampleFifo(sampleFifo),
     m_log2Decim(0)
 {
     std::fill(m_buf, m_buf + 2*LIMESDR_BLOCKSIZE, 0);
 }
~LimeSDRInputThread()
LimeSDRInputThread::~LimeSDRInputThread ()
Definition at line 35 of file limesdrinputthread.cpp.
References stopWork().
 {
     stopWork();
 }
Member Function Documentation
callback()
void LimeSDRInputThread::callback (const qint16 * buf, qint32 len) private
Definition at line 104 of file limesdrinputthread.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), m_convertBuffer, m_decimators, m_log2Decim, m_sampleFifo, and SampleSinkFifo::write().
Referenced by run().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     switch (m_log2Decim)
     {
     case 0:
         m_decimators.decimate1(&it, buf, len);
         break;
     case 1:
         m_decimators.decimate2_cen(&it, buf, len);
         break;
     case 2:
         m_decimators.decimate4_cen(&it, buf, len);
         break;
     case 3:
         m_decimators.decimate8_cen(&it, buf, len);
         break;
     case 4:
         m_decimators.decimate16_cen(&it, buf, len);
         break;
     case 5:
         m_decimators.decimate32_cen(&it, buf, len);
         break;
     case 6:
         m_decimators.decimate64_cen(&it, buf, len);
         break;
     default:
         break;
     }
     m_sampleFifo->write(m_convertBuffer.begin(), it);
 }
isRunning()
virtual bool LimeSDRInputThread::isRunning () inline virtual
Implements DeviceLimeSDRShared::ThreadInterface.
Definition at line 44 of file limesdrinputthread.h.
References m_running, and setLog2Decimation().
Referenced by LimeSDRInput::applySettings().
 { return m_running; }
run()
void LimeSDRInputThread::run () private
Definition at line 78 of file limesdrinputthread.cpp.
References callback(), LIMESDR_BLOCKSIZE, m_buf, m_running, m_startWaiter, and m_stream.
 {
     int res;
     lms_stream_meta_t metadata;          //Use metadata for additional control over sample receive function behaviour
     metadata.flushPartialPacket = false; //Do not discard data remainder when read size differs from packet size
     metadata.waitForTimestamp = false;   //Do not wait for specific timestamps
     m_running = true;
     m_startWaiter.wakeAll();
     while (m_running)
     {
         if ((res = LMS_RecvStream(m_stream, (void *) m_buf, LIMESDR_BLOCKSIZE, &metadata, 1000)) < 0)
         {
             qCritical("LimeSDRInputThread::run read error: %s", strerror(errno));
             break;
         }
         callback(m_buf, 2 * res);
     }
     m_running = false;
 }
setDeviceSampleRate()
virtual void LimeSDRInputThread::setDeviceSampleRate (int sampleRate) inline virtual
Implements DeviceLimeSDRShared::ThreadInterface.
Definition at line 43 of file limesdrinputthread.h.
 { (void) sampleRate; }
setLog2Decimation()
void LimeSDRInputThread::setLog2Decimation (unsigned int log2_decim)
Definition at line 73 of file limesdrinputthread.cpp.
References m_log2Decim.
Referenced by LimeSDRInput::applySettings(), isRunning(), and LimeSDRInput::start().
 {
     m_log2Decim = log2_decim;
 }
startWork()
void LimeSDRInputThread::startWork () virtual
Implements DeviceLimeSDRShared::ThreadInterface.
Definition at line 40 of file limesdrinputthread.cpp.
References m_running, m_startWaiter, m_startWaitMutex, and m_stream.
Referenced by LimeSDRInput::applySettings(), and LimeSDRInput::start().
 {
     if (m_running) return; // return if running already
     if (LMS_StartStream(m_stream) < 0) {
         qCritical("LimeSDRInputThread::startWork: could not start stream");
     } else {
         usleep(50000);
         qDebug("LimeSDRInputThread::startWork: stream started");
     }
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void LimeSDRInputThread::stopWork () virtual
Implements DeviceLimeSDRShared::ThreadInterface.
Definition at line 58 of file limesdrinputthread.cpp.
References m_running, and m_stream.
Referenced by LimeSDRInput::applySettings(), LimeSDRInput::stop(), and ~LimeSDRInputThread().
 {
     if (!m_running) return; // return if not running
     m_running = false;
     wait();
     if (LMS_StopStream(m_stream) < 0) {
         qCritical("LimeSDRInputThread::stopWork: could not stop stream");
     } else {
         usleep(50000);
         qDebug("LimeSDRInputThread::stopWork: stream stopped");
     }
 }
Member Data Documentation
m_buf
qint16 LimeSDRInputThread::m_buf[2 *LIMESDR_BLOCKSIZE] private
Definition at line 53 of file limesdrinputthread.h.
Referenced by LimeSDRInputThread(), and run().
m_convertBuffer
SampleVector LimeSDRInputThread::m_convertBuffer private
Definition at line 54 of file limesdrinputthread.h.
Referenced by callback().
m_decimators
Decimators<qint32, qint16, SDR_RX_SAMP_SZ, 12> LimeSDRInputThread::m_decimators private
Definition at line 59 of file limesdrinputthread.h.
Referenced by callback().
m_log2Decim
unsigned int LimeSDRInputThread::m_log2Decim private
Definition at line 57 of file limesdrinputthread.h.
Referenced by callback(), and setLog2Decimation().
m_running
bool LimeSDRInputThread::m_running private
Definition at line 50 of file limesdrinputthread.h.
Referenced by isRunning(), run(), startWork(), and stopWork().
m_sampleFifo
SampleSinkFifo* LimeSDRInputThread::m_sampleFifo private
Definition at line 55 of file limesdrinputthread.h.
Referenced by callback().
m_startWaiter
QWaitCondition LimeSDRInputThread::m_startWaiter private
Definition at line 49 of file limesdrinputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex LimeSDRInputThread::m_startWaitMutex private
Definition at line 48 of file limesdrinputthread.h.
Referenced by startWork().
m_stream
lms_stream_t* LimeSDRInputThread::m_stream private
Definition at line 52 of file limesdrinputthread.h.
Referenced by run(), startWork(), and stopWork().
The documentation for this class was generated from the following files:
plugins/samplesource/limesdrinput/limesdrinputthread.h
plugins/samplesource/limesdrinput/limesdrinputthread.cpp