SDRAngel: LimeSDRInputGUI Class Reference
LimeSDRInputGUI Class Reference
#include <limesdrinputgui.h>
Public Member Functions
LimeSDRInputGUI (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~LimeSDRInputGUI ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void on_centerFrequency_changed (quint64 value)
void on_ncoFrequency_changed (qint64 value)
void on_ncoEnable_toggled (bool checked)
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_sampleRate_changed (quint64 value)
void on_hwDecim_currentIndexChanged (int index)
void on_swDecim_currentIndexChanged (int index)
void on_lpf_changed (quint64 value)
void on_lpFIREnable_toggled (bool checked)
void on_lpFIR_changed (quint64 value)
void on_gainMode_currentIndexChanged (int index)
void on_gain_valueChanged (int value)
void on_lnaGain_valueChanged (int value)
void on_tiaGain_currentIndexChanged (int index)
void on_pgaGain_valueChanged (int value)
void on_antenna_currentIndexChanged (int index)
void on_extClock_clicked ()
void on_transverter_clicked ()
void on_sampleRateMode_toggled (bool checked)
void openDeviceSettingsDialog (const QPoint &p)
void updateHardware ()
void updateStatus ()
Private Member Functions
void displaySettings ()
void displaySampleRate ()
void setNCODisplay ()
void setCenterFrequencyDisplay ()
void setCenterFrequencySetting (uint64_t kHzValue)
void sendSettings ()
void updateSampleRateAndFrequency ()
void updateADCRate ()
void updateFrequencyLimits ()
void blockApplySettings (bool block)
Private Attributes
Ui::LimeSDRInputGUI * ui
DeviceUISet * m_deviceUISet
LimeSDRInput * m_limeSDRInput
Same object as above but gives easy access to LimeSDRInput methods and attributes that are used intensively.
LimeSDRInputSettings m_settings
bool m_sampleRateMode
true: device, false: base band sample rate update mode
QTimer m_updateTimer
QTimer m_statusTimer
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
bool m_doApplySettings
bool m_forceSettings
int m_statusCounter
int m_deviceStatusCounter
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 35 of file limesdrinputgui.h.
Constructor & Destructor Documentation
LimeSDRInputGUI()
LimeSDRInputGUI::LimeSDRInputGUI (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 35 of file limesdrinputgui.cpp.
References arg(), displaySettings(), LimeSDRInput::getChannelIndex(), LimeSDRInput::getLimeType(), LimeSDRInput::getLORange(), LimeSDRInput::getLPRange(), DeviceAPI::getSampleSource(), LimeSDRInput::getSRRange(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, ColorMapper::GrayYellow, handleInputMessages(), DeviceLimeSDRParams::LimeMini, DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_limeSDRInput, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), LimeSDRInput::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                                           :
     QWidget(parent),
     ui(new Ui::LimeSDRInputGUI),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_sampleRateMode(true),
     m_sampleRate(0),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_statusCounter(0),
     m_deviceStatusCounter(0)
 {
     m_limeSDRInput = (LimeSDRInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     float minF, maxF;
     m_limeSDRInput->getLORange(minF, maxF);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, ((uint32_t) minF)/1000, ((uint32_t) maxF)/1000); // frequency dial is in kHz
     m_limeSDRInput->getSRRange(minF, maxF);
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(8, (uint32_t) minF, (uint32_t) maxF);
     m_limeSDRInput->getLPRange(minF, maxF);
     ui->lpf->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     ui->lpf->setValueRange(6, (minF/1000)+1, maxF/1000);
     ui->lpFIR->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     ui->lpFIR->setValueRange(5, 1U, 56000U);
     ui->ncoFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->channelNumberText->setText(tr("#%1").arg(m_limeSDRInput->getChannelIndex()));
     if (m_limeSDRInput->getLimeType() == DeviceLimeSDRParams::LimeMini)
     {
         ui->antenna->setItemText(2, "NC");
         ui->antenna->setItemText(3, "Lo");
     }
     else
     {
         ui->antenna->setItemText(2, "Lo");
         ui->antenna->setItemText(3, "Wi");
     }
     ui->hwDecimLabel->setText(QString::fromUtf8("H\u2193"));
     ui->swDecimLabel->setText(QString::fromUtf8("S\u2193"));
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     displaySettings();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_limeSDRInput->setMessageQueueToGUI(&m_inputMessageQueue);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
 }
~LimeSDRInputGUI()
LimeSDRInputGUI::~LimeSDRInputGUI () virtual
Definition at line 100 of file limesdrinputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void LimeSDRInputGUI::blockApplySettings (bool block) private
Definition at line 534 of file limesdrinputgui.cpp.
References m_doApplySettings.
Referenced by handleMessage().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool LimeSDRInputGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 144 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if (m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void LimeSDRInputGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 105 of file limesdrinputgui.cpp.
 {
     delete this;
 }
displaySampleRate()
void LimeSDRInputGUI::displaySampleRate () private
Definition at line 333 of file limesdrinputgui.cpp.
References arg(), LimeSDRInput::getSRRange(), LimeSDRInputSettings::m_devSampleRate, m_limeSDRInput, LimeSDRInputSettings::m_log2SoftDecim, m_sampleRateMode, m_settings, and ui.
Referenced by displaySettings(), on_sampleRateMode_toggled(), on_swDecim_currentIndexChanged(), and updateSampleRateAndFrequency().
 {
     float minF, maxF;
     m_limeSDRInput->getSRRange(minF, maxF);
     ui->sampleRate->blockSignals(true);
     if (m_sampleRateMode)
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(60,60,60); }");
         ui->sampleRateMode->setText("SR");
         ui->sampleRate->setValueRange(8, (uint32_t) minF, (uint32_t) maxF);
         ui->sampleRate->setValue(m_settings.m_devSampleRate);
         ui->sampleRate->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setToolTip("Baseband sample rate (S/s)");
         uint32_t basebandSampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2SoftDecim);
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(basebandSampleRate / 1000.0f, 'g', 5)));
     }
     else
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(50,50,50); }");
         ui->sampleRateMode->setText("BB");
         ui->sampleRate->setValueRange(8, (uint32_t) minF/(1<<m_settings.m_log2SoftDecim), (uint32_t) maxF/(1<<m_settings.m_log2SoftDecim));
         ui->sampleRate->setValue(m_settings.m_devSampleRate/(1<<m_settings.m_log2SoftDecim));
         ui->sampleRate->setToolTip("Baseband sample rate (S/s)");
         ui->deviceRateText->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_settings.m_devSampleRate / 1000.0f, 'g', 5)));
     }
     ui->sampleRate->blockSignals(false);
 }
displaySettings()
void LimeSDRInputGUI::displaySettings () private
Definition at line 366 of file limesdrinputgui.cpp.
References arg(), displaySampleRate(), LimeSDRInputSettings::GAIN_AUTO, LimeSDRInputSettings::m_antennaPath, LimeSDRInputSettings::m_dcBlock, LimeSDRInputSettings::m_extClock, LimeSDRInputSettings::m_extClockFreq, LimeSDRInputSettings::m_gain, LimeSDRInputSettings::m_gainMode, LimeSDRInputSettings::m_iqCorrection, LimeSDRInputSettings::m_lnaGain, LimeSDRInputSettings::m_log2HardDecim, LimeSDRInputSettings::m_log2SoftDecim, LimeSDRInputSettings::m_lpfBW, LimeSDRInputSettings::m_lpfFIRBW, LimeSDRInputSettings::m_lpfFIREnable, LimeSDRInputSettings::m_ncoEnable, LimeSDRInputSettings::m_pgaGain, m_settings, LimeSDRInputSettings::m_tiaGain, LimeSDRInputSettings::m_transverterDeltaFrequency, LimeSDRInputSettings::m_transverterMode, setCenterFrequencyDisplay(), setNCODisplay(), ui, and updateADCRate().
Referenced by deserialize(), handleInputMessages(), handleMessage(), LimeSDRInputGUI(), resetToDefaults(), and setCenterFrequency().
 {
     ui->transverter->setDeltaFrequency(m_settings.m_transverterDeltaFrequency);
     ui->transverter->setDeltaFrequencyActive(m_settings.m_transverterMode);
     ui->extClock->setExternalClockFrequency(m_settings.m_extClockFreq);
     ui->extClock->setExternalClockActive(m_settings.m_extClock);
     setCenterFrequencyDisplay();
     displaySampleRate();
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqCorrection);
     ui->hwDecim->setCurrentIndex(m_settings.m_log2HardDecim);
     ui->swDecim->setCurrentIndex(m_settings.m_log2SoftDecim);
     updateADCRate();
     ui->lpf->setValue(m_settings.m_lpfBW / 1000);
     ui->lpFIREnable->setChecked(m_settings.m_lpfFIREnable);
     ui->lpFIR->setValue(m_settings.m_lpfFIRBW / 1000);
     ui->gain->setValue(m_settings.m_gain);
     ui->gainText->setText(tr("%1").arg(m_settings.m_gain));
     ui->antenna->setCurrentIndex((int) m_settings.m_antennaPath);
     ui->gainMode->setCurrentIndex((int) m_settings.m_gainMode);
     ui->lnaGain->setValue(m_settings.m_lnaGain);
     ui->tiaGain->setCurrentIndex(m_settings.m_tiaGain - 1);
     ui->pgaGain->setValue(m_settings.m_pgaGain);
     if (m_settings.m_gainMode == LimeSDRInputSettings::GAIN_AUTO)
     {
         ui->gain->setEnabled(true);
         ui->lnaGain->setEnabled(false);
         ui->tiaGain->setEnabled(false);
         ui->pgaGain->setEnabled(false);
     }
     else
     {
         ui->gain->setEnabled(false);
         ui->lnaGain->setEnabled(true);
         ui->tiaGain->setEnabled(true);
         ui->pgaGain->setEnabled(true);
     }
     setNCODisplay();
     ui->ncoEnable->setChecked(m_settings.m_ncoEnable);
 }
getCenterFrequency()
qint64 LimeSDRInputGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 127 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::m_centerFrequency, LimeSDRInputSettings::m_ncoEnable, LimeSDRInputSettings::m_ncoFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency + (m_settings.m_ncoEnable ? m_settings.m_ncoFrequency : 0);
 }
getInputMessageQueue()
virtual MessageQueue* LimeSDRInputGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 51 of file limesdrinputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString LimeSDRInputGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 115 of file limesdrinputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void LimeSDRInputGUI::handleInputMessages () private slot
Definition at line 282 of file limesdrinputgui.cpp.
References displaySettings(), DSPSignalNotification::getCenterFrequency(), DSPSignalNotification::getSampleRate(), LimeSDRInput::MsgConfigureLimeSDR::getSettings(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, m_settings, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by LimeSDRInputGUI().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("LimeSDRInputGUI::handleInputMessages: DSPSignalNotification: SampleRate: %d, CenterFrequency: %llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else if (LimeSDRInput::MsgConfigureLimeSDR::match(*message))
         {
             const LimeSDRInput::MsgConfigureLimeSDR& cfg = (LimeSDRInput::MsgConfigureLimeSDR&) *message;
             m_settings = cfg.getSettings();
             displaySettings();
             delete message;
         }
         else
         {
             if (handleMessage(*message)) {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool LimeSDRInputGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 160 of file limesdrinputgui.cpp.
References arg(), blockApplySettings(), displaySettings(), LimeSDRInput::MsgReportStreamInfo::getActive(), DeviceLimeSDRShared::MsgReportBuddyChange::getCenterFrequency(), DeviceLimeSDRShared::MsgReportBuddyChange::getDevSampleRate(), LimeSDRInput::MsgReportStreamInfo::getDroppedPackets(), DeviceLimeSDRShared::MsgReportClockSourceChange::getExtClock(), DeviceLimeSDRShared::MsgReportClockSourceChange::getExtClockFeq(), LimeSDRInput::MsgReportStreamInfo::getFifoFilledCount(), LimeSDRInput::MsgReportStreamInfo::getFifoSize(), DeviceLimeSDRShared::MsgReportDeviceInfo::getGPIOPins(), LimeSDRInput::MsgReportStreamInfo::getLinkRate(), DeviceLimeSDRShared::MsgReportBuddyChange::getLog2HardDecimInterp(), LimeSDRInput::MsgReportStreamInfo::getOverrun(), DeviceLimeSDRShared::MsgReportBuddyChange::getRxElseTx(), LimeSDRInput::MsgConfigureLimeSDR::getSettings(), LimeSDRInput::MsgStartStop::getStartStop(), LimeSDRInput::MsgReportStreamInfo::getSuccess(), DeviceLimeSDRShared::MsgReportDeviceInfo::getTemperature(), LimeSDRInput::MsgReportStreamInfo::getUnderrun(), LimeSDRInputSettings::m_centerFrequency, LimeSDRInputSettings::m_devSampleRate, LimeSDRInputSettings::m_extClock, LimeSDRInputSettings::m_extClockFreq, LimeSDRInputSettings::m_log2HardDecim, m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (LimeSDRInput::MsgConfigureLimeSDR::match(message))
     {
         const LimeSDRInput::MsgConfigureLimeSDR& cfg = (LimeSDRInput::MsgConfigureLimeSDR&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (DeviceLimeSDRShared::MsgReportBuddyChange::match(message))
     {
         DeviceLimeSDRShared::MsgReportBuddyChange& report = (DeviceLimeSDRShared::MsgReportBuddyChange&) message;
         m_settings.m_devSampleRate = report.getDevSampleRate();
         m_settings.m_log2HardDecim = report.getLog2HardDecimInterp();
         if (report.getRxElseTx()) {
             m_settings.m_centerFrequency = report.getCenterFrequency();
         }
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (DeviceLimeSDRShared::MsgReportClockSourceChange::match(message))
     {
         DeviceLimeSDRShared::MsgReportClockSourceChange& report = (DeviceLimeSDRShared::MsgReportClockSourceChange&) message;
         m_settings.m_extClockFreq = report.getExtClockFeq();
         m_settings.m_extClock = report.getExtClock();
         blockApplySettings(true);
         ui->extClock->setExternalClockFrequency(m_settings.m_extClockFreq);
         ui->extClock->setExternalClockActive(m_settings.m_extClock);
         blockApplySettings(false);
         return true;
     }
     else if (LimeSDRInput::MsgReportStreamInfo::match(message))
     {
         LimeSDRInput::MsgReportStreamInfo& report = (LimeSDRInput::MsgReportStreamInfo&) message;
         if (report.getSuccess())
         {
             if (report.getActive()) {
                 ui->streamStatusLabel->setStyleSheet("QLabel { background-color : green; }");
             } else {
                 ui->streamStatusLabel->setStyleSheet("QLabel { background-color : blue; }");
             }
             ui->streamLinkRateText->setText(tr("%1 MB/s").arg(QString::number(report.getLinkRate() / 1000000.0f, 'f', 3)));
             if (report.getUnderrun() > 0) {
                 ui->underrunLabel->setStyleSheet("QLabel { background-color : red; }");
             } else {
                 ui->underrunLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
             }
             if (report.getOverrun() > 0) {
                 ui->overrunLabel->setStyleSheet("QLabel { background-color : red; }");
             } else {
                 ui->overrunLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
             }
             if (report.getDroppedPackets() > 0) {
                 ui->droppedLabel->setStyleSheet("QLabel { background-color : red; }");
             } else {
                 ui->droppedLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
             }
             ui->fifoBar->setMaximum(report.getFifoSize());
             ui->fifoBar->setValue(report.getFifoFilledCount());
             ui->fifoBar->setToolTip(tr("FIFO fill %1/%2 samples").arg(QString::number(report.getFifoFilledCount())).arg(QString::number(report.getFifoSize())));
         }
         else
         {
             ui->streamStatusLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
         }
         return true;
     }
     else if (DeviceLimeSDRShared::MsgReportDeviceInfo::match(message))
     {
         DeviceLimeSDRShared::MsgReportDeviceInfo& report = (DeviceLimeSDRShared::MsgReportDeviceInfo&) message;
         ui->temperatureText->setText(tr("%1C").arg(QString::number(report.getTemperature(), 'f', 0)));
         ui->gpioText->setText(tr("%1").arg(report.getGPIOPins(), 2, 16, QChar('0')).toUpper());
         return true;
     }
     else if (LimeSDRInput::MsgStartStop::match(message))
     {
         LimeSDRInput::MsgStartStop& notif = (LimeSDRInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_antenna_currentIndexChanged
void LimeSDRInputGUI::on_antenna_currentIndexChanged (int index) private slot
Definition at line 699 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::m_antennaPath, m_settings, and sendSettings().
 {
     m_settings.m_antennaPath = (LimeSDRInputSettings::PathRFE) index;
     sendSettings();
 }
on_centerFrequency_changed
void LimeSDRInputGUI::on_centerFrequency_changed (quint64 value) private slot
Definition at line 560 of file limesdrinputgui.cpp.
References sendSettings(), and setCenterFrequencySetting().
 {
     setCenterFrequencySetting(value);
     sendSettings();
 }
on_dcOffset_toggled
void LimeSDRInputGUI::on_dcOffset_toggled (bool checked) private slot
Definition at line 580 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_extClock_clicked
void LimeSDRInputGUI::on_extClock_clicked () private slot
Definition at line 705 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::m_extClock, LimeSDRInputSettings::m_extClockFreq, m_settings, sendSettings(), and ui.
 {
     m_settings.m_extClock = ui->extClock->getExternalClockActive();
     m_settings.m_extClockFreq = ui->extClock->getExternalClockFrequency();
     qDebug("LimeSDRInputGUI::on_extClock_clicked: %u Hz %s", m_settings.m_extClockFreq, m_settings.m_extClock ? "on" : "off");
     sendSettings();
 }
on_gain_valueChanged
void LimeSDRInputGUI::on_gain_valueChanged (int value) private slot
Definition at line 672 of file limesdrinputgui.cpp.
References arg(), LimeSDRInputSettings::m_gain, m_settings, sendSettings(), and ui.
 {
     m_settings.m_gain = value;
     ui->gainText->setText(tr("%1").arg(m_settings.m_gain));
     sendSettings();
 }
on_gainMode_currentIndexChanged
void LimeSDRInputGUI::on_gainMode_currentIndexChanged (int index) private slot
Definition at line 650 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::m_gainMode, m_settings, sendSettings(), and ui.
 {
     m_settings.m_gainMode = (LimeSDRInputSettings::GainMode) index;
     if (index == 0)
     {
         ui->gain->setEnabled(true);
         ui->lnaGain->setEnabled(false);
         ui->tiaGain->setEnabled(false);
         ui->pgaGain->setEnabled(false);
     }
     else
     {
         ui->gain->setEnabled(false);
         ui->lnaGain->setEnabled(true);
         ui->tiaGain->setEnabled(true);
         ui->pgaGain->setEnabled(true);
     }
     sendSettings();
 }
on_hwDecim_currentIndexChanged
void LimeSDRInputGUI::on_hwDecim_currentIndexChanged (int index) private slot
Definition at line 604 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::m_log2HardDecim, m_settings, sendSettings(), setNCODisplay(), and updateADCRate().
 {
     if ((index <0) || (index > 5))
         return;
     m_settings.m_log2HardDecim = index;
     updateADCRate();
     setNCODisplay();
     sendSettings();
 }
on_iqImbalance_toggled
void LimeSDRInputGUI::on_iqImbalance_toggled (bool checked) private slot
Definition at line 586 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::m_iqCorrection, m_settings, and sendSettings().
 {
     m_settings.m_iqCorrection = checked;
     sendSettings();
 }
on_lnaGain_valueChanged
void LimeSDRInputGUI::on_lnaGain_valueChanged (int value) private slot
Definition at line 679 of file limesdrinputgui.cpp.
References arg(), LimeSDRInputSettings::m_lnaGain, m_settings, sendSettings(), and ui.
 {
     m_settings.m_lnaGain = value;
     ui->lnaGainText->setText(tr("%1").arg(m_settings.m_lnaGain));
     sendSettings();
 }
on_lpf_changed
void LimeSDRInputGUI::on_lpf_changed (quint64 value) private slot
Definition at line 632 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::m_lpfBW, m_settings, and sendSettings().
 {
     m_settings.m_lpfBW = value * 1000;
     sendSettings();
 }
on_lpFIR_changed
void LimeSDRInputGUI::on_lpFIR_changed (quint64 value) private slot
Definition at line 644 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::m_lpfFIRBW, m_settings, and sendSettings().
 {
     m_settings.m_lpfFIRBW = value * 1000;
     sendSettings();
 }
on_lpFIREnable_toggled
void LimeSDRInputGUI::on_lpFIREnable_toggled (bool checked) private slot
Definition at line 638 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::m_lpfFIREnable, m_settings, and sendSettings().
 {
     m_settings.m_lpfFIREnable = checked;
     sendSettings();
 }
on_ncoEnable_toggled
void LimeSDRInputGUI::on_ncoEnable_toggled (bool checked) private slot
Definition at line 573 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::m_ncoEnable, m_settings, sendSettings(), and setCenterFrequencyDisplay().
 {
     m_settings.m_ncoEnable = checked;
     setCenterFrequencyDisplay();
     sendSettings();
 }
on_ncoFrequency_changed
void LimeSDRInputGUI::on_ncoFrequency_changed (qint64 value) private slot
Definition at line 566 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::m_ncoFrequency, m_settings, sendSettings(), and setCenterFrequencyDisplay().
 {
     m_settings.m_ncoFrequency = value;
     setCenterFrequencyDisplay();
     sendSettings();
 }
on_pgaGain_valueChanged
void LimeSDRInputGUI::on_pgaGain_valueChanged (int value) private slot
Definition at line 692 of file limesdrinputgui.cpp.
References arg(), LimeSDRInputSettings::m_pgaGain, m_settings, sendSettings(), and ui.
 {
     m_settings.m_pgaGain = value;
     ui->pgaGainText->setText(tr("%1").arg(m_settings.m_pgaGain));
     sendSettings();
 }
on_record_toggled
void LimeSDRInputGUI::on_record_toggled (bool checked) private slot
Definition at line 548 of file limesdrinputgui.cpp.
References LimeSDRInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_limeSDRInput, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     LimeSDRInput::MsgFileRecord* message = LimeSDRInput::MsgFileRecord::create(checked);
     m_limeSDRInput->getInputMessageQueue()->push(message);
 }
on_sampleRate_changed
void LimeSDRInputGUI::on_sampleRate_changed (quint64 value) private slot
Definition at line 592 of file limesdrinputgui.cpp.
References LimeSDRInputSettings::m_devSampleRate, LimeSDRInputSettings::m_log2SoftDecim, m_sampleRateMode, m_settings, sendSettings(), setNCODisplay(), and updateADCRate().
 {
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = value;
     } else {
         m_settings.m_devSampleRate = value * (1 << m_settings.m_log2SoftDecim);
     }
     updateADCRate();
     setNCODisplay();
     sendSettings();}
on_sampleRateMode_toggled
void LimeSDRInputGUI::on_sampleRateMode_toggled (bool checked) private slot
Definition at line 723 of file limesdrinputgui.cpp.
References displaySampleRate(), and m_sampleRateMode.
 {
     m_sampleRateMode = checked;
     displaySampleRate();
 }
on_startStop_toggled
void LimeSDRInputGUI::on_startStop_toggled (bool checked) private slot
Definition at line 539 of file limesdrinputgui.cpp.
References LimeSDRInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_limeSDRInput, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         LimeSDRInput::MsgStartStop *message = LimeSDRInput::MsgStartStop::create(checked);
         m_limeSDRInput->getInputMessageQueue()->push(message);
     }
 }
on_swDecim_currentIndexChanged
void LimeSDRInputGUI::on_swDecim_currentIndexChanged (int index) private slot
Definition at line 614 of file limesdrinputgui.cpp.
References displaySampleRate(), LimeSDRInputSettings::m_devSampleRate, LimeSDRInputSettings::m_log2SoftDecim, m_sampleRateMode, m_settings, sendSettings(), and ui.
 {
     if ((index <0) || (index > 6)) {
         return;
     }
     m_settings.m_log2SoftDecim = index;
     displaySampleRate();
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     } else {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew() * (1 << m_settings.m_log2SoftDecim);
     }
     sendSettings();
 }
on_tiaGain_currentIndexChanged
void LimeSDRInputGUI::on_tiaGain_currentIndexChanged (int index) private slot
Definition at line 686 of file limesdrinputgui.cpp.
References m_settings, LimeSDRInputSettings::m_tiaGain, and sendSettings().
 {
     m_settings.m_tiaGain = index + 1;
     sendSettings();
 }
on_transverter_clicked
void LimeSDRInputGUI::on_transverter_clicked () private slot
Definition at line 713 of file limesdrinputgui.cpp.
References m_settings, LimeSDRInputSettings::m_transverterDeltaFrequency, LimeSDRInputSettings::m_transverterMode, sendSettings(), setCenterFrequencySetting(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("LimeSDRInputGUI::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     setCenterFrequencySetting(ui->centerFrequency->getValueNew());
     sendSettings();
 }
openDeviceSettingsDialog
void LimeSDRInputGUI::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 729 of file limesdrinputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), LimeSDRInputSettings::m_reverseAPIAddress, LimeSDRInputSettings::m_reverseAPIDeviceIndex, LimeSDRInputSettings::m_reverseAPIPort, m_settings, LimeSDRInputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by LimeSDRInputGUI().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void LimeSDRInputGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 120 of file limesdrinputgui.cpp.
References displaySettings(), m_settings, LimeSDRInputSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void LimeSDRInputGUI::sendSettings () private
Definition at line 461 of file limesdrinputgui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_antenna_currentIndexChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_extClock_clicked(), on_gain_valueChanged(), on_gainMode_currentIndexChanged(), on_hwDecim_currentIndexChanged(), on_iqImbalance_toggled(), on_lnaGain_valueChanged(), on_lpf_changed(), on_lpFIR_changed(), on_lpFIREnable_toggled(), on_ncoEnable_toggled(), on_ncoFrequency_changed(), on_pgaGain_valueChanged(), on_sampleRate_changed(), on_swDecim_currentIndexChanged(), on_tiaGain_currentIndexChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray LimeSDRInputGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 139 of file limesdrinputgui.cpp.
References m_settings, and LimeSDRInputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void LimeSDRInputGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 132 of file limesdrinputgui.cpp.
References displaySettings(), LimeSDRInputSettings::m_centerFrequency, LimeSDRInputSettings::m_ncoEnable, LimeSDRInputSettings::m_ncoFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency - (m_settings.m_ncoEnable ? m_settings.m_ncoFrequency : 0);
     displaySettings();
     sendSettings();
 }
setCenterFrequencyDisplay()
void LimeSDRInputGUI::setCenterFrequencyDisplay () private
Definition at line 435 of file limesdrinputgui.cpp.
References arg(), LimeSDRInputSettings::m_centerFrequency, LimeSDRInputSettings::m_ncoEnable, LimeSDRInputSettings::m_ncoFrequency, m_settings, and ui.
Referenced by displaySettings(), on_ncoEnable_toggled(), and on_ncoFrequency_changed().
 {
     int64_t centerFrequency = m_settings.m_centerFrequency;
     ui->centerFrequency->setToolTip(QString("Main center frequency in kHz (LO: %1 kHz)").arg(centerFrequency/1000));
     if (m_settings.m_ncoEnable) {
         centerFrequency += m_settings.m_ncoFrequency;
     }
     ui->centerFrequency->blockSignals(true);
     ui->centerFrequency->setValue(centerFrequency < 0 ? 0 : (uint64_t) centerFrequency/1000); // kHz
     ui->centerFrequency->blockSignals(false);
 }
setCenterFrequencySetting()
void LimeSDRInputGUI::setCenterFrequencySetting (uint64_t kHzValue) private
Definition at line 449 of file limesdrinputgui.cpp.
References arg(), LimeSDRInputSettings::m_centerFrequency, LimeSDRInputSettings::m_ncoEnable, LimeSDRInputSettings::m_ncoFrequency, m_settings, and ui.
Referenced by on_centerFrequency_changed(), and on_transverter_clicked().
 {
     int64_t centerFrequency = kHzValue*1000;
     if (m_settings.m_ncoEnable) {
         centerFrequency -= m_settings.m_ncoFrequency;
     }
     m_settings.m_centerFrequency = centerFrequency < 0 ? 0 : (uint64_t) centerFrequency;
     ui->centerFrequency->setToolTip(QString("Main center frequency in kHz (LO: %1 kHz)").arg(centerFrequency/1000));
 }
setName()
void LimeSDRInputGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 110 of file limesdrinputgui.cpp.
 {
     setObjectName(name);
 }
setNCODisplay()
void LimeSDRInputGUI::setNCODisplay () private
Definition at line 420 of file limesdrinputgui.cpp.
References arg(), LimeSDRInputSettings::m_devSampleRate, LimeSDRInputSettings::m_log2HardDecim, LimeSDRInputSettings::m_ncoFrequency, m_settings, and ui.
Referenced by displaySettings(), on_hwDecim_currentIndexChanged(), and on_sampleRate_changed().
 {
     int ncoHalfRange = (m_settings.m_devSampleRate * (1<<(m_settings.m_log2HardDecim)))/2;
     ui->ncoFrequency->setValueRange(
             false,
             8,
             -ncoHalfRange,
             ncoHalfRange);
     ui->ncoFrequency->blockSignals(true);
     ui->ncoFrequency->setToolTip(QString("NCO frequency shift in Hz (Range: +/- %1 kHz)").arg(ncoHalfRange/1000));
     ui->ncoFrequency->setValue(m_settings.m_ncoFrequency);
     ui->ncoFrequency->blockSignals(false);
 }
updateADCRate()
void LimeSDRInputGUI::updateADCRate () private
Definition at line 315 of file limesdrinputgui.cpp.
References arg(), LimeSDRInputSettings::m_devSampleRate, LimeSDRInputSettings::m_log2HardDecim, m_settings, and ui.
Referenced by displaySettings(), on_hwDecim_currentIndexChanged(), and on_sampleRate_changed().
 {
     uint32_t adcRate = m_settings.m_devSampleRate * (1<<m_settings.m_log2HardDecim);
     if (adcRate < 100000000) {
         ui->adcRateLabel->setText(tr("%1k").arg(QString::number(adcRate / 1000.0f, 'g', 5)));
     } else {
         ui->adcRateLabel->setText(tr("%1M").arg(QString::number(adcRate / 1000000.0f, 'g', 5)));
     }
 }
updateFrequencyLimits()
void LimeSDRInputGUI::updateFrequencyLimits () private
Definition at line 265 of file limesdrinputgui.cpp.
References LimeSDRInput::getLORange(), m_limeSDRInput, m_settings, LimeSDRInputSettings::m_transverterDeltaFrequency, LimeSDRInputSettings::m_transverterMode, and ui.
Referenced by on_transverter_clicked().
 {
     // values in kHz
     float minF, maxF;
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     m_limeSDRInput->getLORange(minF, maxF);
     qint64 minLimit = minF/1000 + deltaFrequency;
     qint64 maxLimit = maxF/1000 + deltaFrequency;
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("LimeSDRInputGUI::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void LimeSDRInputGUI::updateHardware () private slot
Definition at line 467 of file limesdrinputgui.cpp.
References LimeSDRInput::MsgConfigureLimeSDR::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_limeSDRInput, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by LimeSDRInputGUI().
 {
     if (m_doApplySettings)
     {
         qDebug() << "LimeSDRInputGUI::updateHardware";
         LimeSDRInput::MsgConfigureLimeSDR* message = LimeSDRInput::MsgConfigureLimeSDR::create(m_settings, m_forceSettings);
         m_limeSDRInput->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void LimeSDRInputGUI::updateSampleRateAndFrequency () private
Definition at line 326 of file limesdrinputgui.cpp.
References displaySampleRate(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), and GLSpectrum::setSampleRate().
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     displaySampleRate();
 }
updateStatus
void LimeSDRInputGUI::updateStatus () private slot
Definition at line 479 of file limesdrinputgui.cpp.
References LimeSDRInput::MsgGetStreamInfo::create(), LimeSDRInput::MsgGetDeviceInfo::create(), DeviceAPI::errorMessage(), DeviceSampleSource::getInputMessageQueue(), DeviceAPI::isBuddyLeader(), DeviceUISet::m_deviceAPI, m_deviceStatusCounter, m_deviceUISet, m_lastEngineState, m_limeSDRInput, m_statusCounter, MessageQueue::push(), DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by LimeSDRInputGUI().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
     if (m_statusCounter < 1)
     {
         m_statusCounter++;
     }
     else
     {
         LimeSDRInput::MsgGetStreamInfo* message = LimeSDRInput::MsgGetStreamInfo::create();
         m_limeSDRInput->getInputMessageQueue()->push(message);
         m_statusCounter = 0;
     }
     if (m_deviceStatusCounter < 10)
     {
         m_deviceStatusCounter++;
     }
     else
     {
         if (m_deviceUISet->m_deviceAPI->isBuddyLeader())
         {
             LimeSDRInput::MsgGetDeviceInfo* message = LimeSDRInput::MsgGetDeviceInfo::create();
             m_limeSDRInput->getInputMessageQueue()->push(message);
         }
         m_deviceStatusCounter = 0;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 LimeSDRInputGUI::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 64 of file limesdrinputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceStatusCounter
int LimeSDRInputGUI::m_deviceStatusCounter private
Definition at line 69 of file limesdrinputgui.h.
Referenced by updateStatus().
m_deviceUISet
DeviceUISet* LimeSDRInputGUI::m_deviceUISet private
Definition at line 57 of file limesdrinputgui.h.
Referenced by LimeSDRInputGUI(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool LimeSDRInputGUI::m_doApplySettings private
Definition at line 66 of file limesdrinputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_forceSettings
bool LimeSDRInputGUI::m_forceSettings private
Definition at line 67 of file limesdrinputgui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue LimeSDRInputGUI::m_inputMessageQueue private
Definition at line 70 of file limesdrinputgui.h.
Referenced by handleInputMessages(), and LimeSDRInputGUI().
m_lastEngineState
int LimeSDRInputGUI::m_lastEngineState private
Definition at line 65 of file limesdrinputgui.h.
Referenced by updateStatus().
m_limeSDRInput
LimeSDRInput* LimeSDRInputGUI::m_limeSDRInput private
Same object as above but gives easy access to LimeSDRInput methods and attributes that are used intensively.
Definition at line 58 of file limesdrinputgui.h.
Referenced by displaySampleRate(), LimeSDRInputGUI(), on_record_toggled(), on_startStop_toggled(), updateFrequencyLimits(), updateHardware(), and updateStatus().
m_sampleRate
int LimeSDRInputGUI::m_sampleRate private
Definition at line 63 of file limesdrinputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateMode
bool LimeSDRInputGUI::m_sampleRateMode private
true: device, false: base band sample rate update mode
Definition at line 60 of file limesdrinputgui.h.
Referenced by displaySampleRate(), on_sampleRate_changed(), on_sampleRateMode_toggled(), and on_swDecim_currentIndexChanged().
m_settings
LimeSDRInputSettings LimeSDRInputGUI::m_settings private
Definition at line 59 of file limesdrinputgui.h.
Referenced by deserialize(), displaySampleRate(), displaySettings(), getCenterFrequency(), handleInputMessages(), handleMessage(), on_antenna_currentIndexChanged(), on_dcOffset_toggled(), on_extClock_clicked(), on_gain_valueChanged(), on_gainMode_currentIndexChanged(), on_hwDecim_currentIndexChanged(), on_iqImbalance_toggled(), on_lnaGain_valueChanged(), on_lpf_changed(), on_lpFIR_changed(), on_lpFIREnable_toggled(), on_ncoEnable_toggled(), on_ncoFrequency_changed(), on_pgaGain_valueChanged(), on_sampleRate_changed(), on_swDecim_currentIndexChanged(), on_tiaGain_currentIndexChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), setCenterFrequencyDisplay(), setCenterFrequencySetting(), setNCODisplay(), updateADCRate(), updateFrequencyLimits(), and updateHardware().
m_statusCounter
int LimeSDRInputGUI::m_statusCounter private
Definition at line 68 of file limesdrinputgui.h.
Referenced by updateStatus().
m_statusTimer
QTimer LimeSDRInputGUI::m_statusTimer private
Definition at line 62 of file limesdrinputgui.h.
Referenced by LimeSDRInputGUI().
m_updateTimer
QTimer LimeSDRInputGUI::m_updateTimer private
Definition at line 61 of file limesdrinputgui.h.
Referenced by LimeSDRInputGUI(), sendSettings(), and updateHardware().
ui
Ui::LimeSDRInputGUI* LimeSDRInputGUI::ui private
Definition at line 55 of file limesdrinputgui.h.
Referenced by displaySampleRate(), displaySettings(), handleMessage(), LimeSDRInputGUI(), on_extClock_clicked(), on_gain_valueChanged(), on_gainMode_currentIndexChanged(), on_lnaGain_valueChanged(), on_pgaGain_valueChanged(), on_record_toggled(), on_swDecim_currentIndexChanged(), on_transverter_clicked(), setCenterFrequencyDisplay(), setCenterFrequencySetting(), setNCODisplay(), updateADCRate(), updateFrequencyLimits(), updateStatus(), and ~LimeSDRInputGUI().
The documentation for this class was generated from the following files:
plugins/samplesource/limesdrinput/limesdrinputgui.h
plugins/samplesource/limesdrinput/limesdrinputgui.cpp