SDRAngel: ThreadedBasebandSampleSinkFifo Class Reference
ThreadedBasebandSampleSinkFifo Class Reference
#include <threadedbasebandsamplesink.h>
Inherits QObject.
Public Slots
void handleFifoData ()
Public Member Functions
ThreadedBasebandSampleSinkFifo (BasebandSampleSink *sampleSink, std::size_t size=1<< 18)
~ThreadedBasebandSampleSinkFifo ()
void writeToFifo (SampleVector::const_iterator &begin, SampleVector::const_iterator &end)
Public Attributes
BasebandSampleSink * m_sampleSink
SampleSinkFifo m_sampleFifo
Detailed Description
Because Qt is a piece of shit this class cannot be a nested protected class of ThreadedSampleSink So let's make everything public
Definition at line 36 of file threadedbasebandsamplesink.h.
Constructor & Destructor Documentation
ThreadedBasebandSampleSinkFifo()
ThreadedBasebandSampleSinkFifo::ThreadedBasebandSampleSinkFifo (BasebandSampleSink * sampleSink, std::size_t size = 1<<18)
Definition at line 8 of file threadedbasebandsamplesink.cpp.
References handleFifoData(), m_sampleFifo, and SampleSinkFifo::setSize().
                                                                                                              :
     m_sampleSink(sampleSink)
 {
     connect(&m_sampleFifo, SIGNAL(dataReady()), this, SLOT(handleFifoData()));
     m_sampleFifo.setSize(size);
 }
~ThreadedBasebandSampleSinkFifo()
ThreadedBasebandSampleSinkFifo::~ThreadedBasebandSampleSinkFifo ()
Definition at line 15 of file threadedbasebandsamplesink.cpp.
References SampleSinkFifo::fill(), m_sampleFifo, and SampleSinkFifo::readCommit().
 {
     m_sampleFifo.readCommit(m_sampleFifo.fill());
 }
Member Function Documentation
handleFifoData
void ThreadedBasebandSampleSinkFifo::handleFifoData () slot
Definition at line 25 of file threadedbasebandsamplesink.cpp.
References BasebandSampleSink::feed(), SampleSinkFifo::fill(), BasebandSampleSink::getInputMessageQueue(), m_sampleFifo, m_sampleSink, SampleSinkFifo::readBegin(), SampleSinkFifo::readCommit(), and MessageQueue::size().
Referenced by ThreadedBasebandSampleSinkFifo().
 {
     bool positiveOnly = false;
     while ((m_sampleFifo.fill() > 0) && (m_sampleSink->getInputMessageQueue()->size() == 0))
     {
         SampleVector::iterator part1begin;
         SampleVector::iterator part1end;
         SampleVector::iterator part2begin;
         SampleVector::iterator part2end;
         std::size_t count = m_sampleFifo.readBegin(m_sampleFifo.fill(), &part1begin, &part1end, &part2begin, &part2end);
         // first part of FIFO data
         if (count > 0)
         {
             // handle data
             if(m_sampleSink != NULL)
             {
                 m_sampleSink->feed(part1begin, part1end, positiveOnly);
             }
             m_sampleFifo.readCommit(part1end - part1begin);
         }
         // second part of FIFO data (used when block wraps around)
         if(part2begin != part2end)
         {
             // handle data
             if(m_sampleSink != NULL)
             {
                 m_sampleSink->feed(part2begin, part2end, positiveOnly);
             }
             m_sampleFifo.readCommit(part2end - part2begin);
         }
     }
 }
writeToFifo()
void ThreadedBasebandSampleSinkFifo::writeToFifo (SampleVector::const_iterator & begin, SampleVector::const_iterator & end)
Definition at line 20 of file threadedbasebandsamplesink.cpp.
References m_sampleFifo, and SampleSinkFifo::write().
Referenced by ThreadedBasebandSampleSink::feed().
 {
     m_sampleFifo.write(begin, end);
 }
Member Data Documentation
m_sampleFifo
SampleSinkFifo ThreadedBasebandSampleSinkFifo::m_sampleFifo
Definition at line 45 of file threadedbasebandsamplesink.h.
Referenced by handleFifoData(), ThreadedBasebandSampleSinkFifo(), writeToFifo(), and ~ThreadedBasebandSampleSinkFifo().
m_sampleSink
BasebandSampleSink* ThreadedBasebandSampleSinkFifo::m_sampleSink
Definition at line 44 of file threadedbasebandsamplesink.h.
Referenced by handleFifoData().
The documentation for this class was generated from the following files:
sdrbase/dsp/threadedbasebandsamplesink.h
sdrbase/dsp/threadedbasebandsamplesink.cpp