SDRAngel: SampleSinkFifoDoubleBuffered Class Reference
SampleSinkFifoDoubleBuffered Class Reference
#include <samplesinkfifodoublebuffered.h>
Inherits QObject.
Signals
void dataReady ()
Public Member Functions
SampleSinkFifoDoubleBuffered (uint32_t size, uint32_t signalThreshold)
~SampleSinkFifoDoubleBuffered ()
void getWriteIterator (SampleVector::iterator &it1)
void bumpIndex (SampleVector::iterator &it1)
void read (SampleVector::iterator &begin, SampleVector::iterator &end)
Private Attributes
uint32_t m_size
uint32_t m_signalThreshold
SampleVector m_data
uint32_t m_i
uint32_t m_count
uint32_t m_readIndex
uint32_t m_readCount
QMutex m_mutex
Detailed Description
Definition at line 28 of file samplesinkfifodoublebuffered.h.
Constructor & Destructor Documentation
SampleSinkFifoDoubleBuffered()
SampleSinkFifoDoubleBuffered::SampleSinkFifoDoubleBuffered (uint32_t size, uint32_t signalThreshold)
Definition at line 20 of file samplesinkfifodoublebuffered.cpp.
References m_data, m_signalThreshold, and m_size.
                                                                                                   :
     m_size(size),
     m_signalThreshold(signalThreshold),
     m_i(0),
     m_count(0),
     m_readIndex(0),
     m_readCount(0)
 {
     assert(m_signalThreshold < m_size/2);
     m_data.resize(2*m_size);
 }
~SampleSinkFifoDoubleBuffered()
SampleSinkFifoDoubleBuffered::~SampleSinkFifoDoubleBuffered ()
Definition at line 32 of file samplesinkfifodoublebuffered.cpp.
 {
 }
Member Function Documentation
bumpIndex()
void SampleSinkFifoDoubleBuffered::bumpIndex (SampleVector::iterator & it1)
Definition at line 41 of file samplesinkfifodoublebuffered.cpp.
References dataReady(), m_count, m_data, m_i, m_mutex, m_readCount, m_readIndex, m_signalThreshold, and m_size.
Referenced by SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate1(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate16_cen(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate16_inf(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate16_sup(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate2_cen(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate2_inf(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate2_sup(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate2_u(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate32_cen(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate32_inf(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate32_sup(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate4_cen(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate4_inf(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate4_sup(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate64_cen(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate64_inf(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate64_sup(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate8_cen(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate8_inf(), and SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate8_sup().
 {
     m_data[m_i+m_size] = m_data[m_i];
     m_i = (m_i+1) % m_size;
     it1 = m_data.begin() + m_i;
     if (m_count < m_signalThreshold)
     {
         m_count++;
     }
     else
     {
         QMutexLocker mutexLocker(&m_mutex);
         m_readIndex = m_i + m_size - m_count;
         m_readCount = m_count;
         m_count = 0;
         emit dataReady();
     }
 }
dataReady
void SampleSinkFifoDoubleBuffered::dataReady () signal
Referenced by bumpIndex().
getWriteIterator()
void SampleSinkFifoDoubleBuffered::getWriteIterator (SampleVector::iterator & it1)
Definition at line 36 of file samplesinkfifodoublebuffered.cpp.
References m_data, and m_i.
Referenced by SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate1(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate16_cen(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate16_inf(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate16_sup(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate2_cen(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate2_inf(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate2_sup(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate2_u(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate32_cen(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate32_inf(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate32_sup(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate4_cen(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate4_inf(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate4_sup(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate64_cen(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate64_inf(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate64_sup(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate8_cen(), SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate8_inf(), and SampleSinkFifoDecimator< T, SdrBits, InputBits >::decimate8_sup().
 {
     it1 = m_data.begin() + m_i;
 }
read()
void SampleSinkFifoDoubleBuffered::read (SampleVector::iterator & begin, SampleVector::iterator & end)
Definition at line 61 of file samplesinkfifodoublebuffered.cpp.
References m_data, m_mutex, m_readCount, and m_readIndex.
 {
     QMutexLocker mutexLocker(&m_mutex);
     begin = m_data.begin() + m_readIndex;
     end = begin + m_readCount;
 }
Member Data Documentation
m_count
uint32_t SampleSinkFifoDoubleBuffered::m_count private
Definition at line 44 of file samplesinkfifodoublebuffered.h.
Referenced by bumpIndex().
m_data
SampleVector SampleSinkFifoDoubleBuffered::m_data private
Definition at line 42 of file samplesinkfifodoublebuffered.h.
Referenced by bumpIndex(), getWriteIterator(), read(), and SampleSinkFifoDoubleBuffered().
m_i
uint32_t SampleSinkFifoDoubleBuffered::m_i private
Definition at line 43 of file samplesinkfifodoublebuffered.h.
Referenced by bumpIndex(), and getWriteIterator().
m_mutex
QMutex SampleSinkFifoDoubleBuffered::m_mutex private
Definition at line 47 of file samplesinkfifodoublebuffered.h.
Referenced by bumpIndex(), and read().
m_readCount
uint32_t SampleSinkFifoDoubleBuffered::m_readCount private
Definition at line 46 of file samplesinkfifodoublebuffered.h.
Referenced by bumpIndex(), and read().
m_readIndex
uint32_t SampleSinkFifoDoubleBuffered::m_readIndex private
Definition at line 45 of file samplesinkfifodoublebuffered.h.
Referenced by bumpIndex(), and read().
m_signalThreshold
uint32_t SampleSinkFifoDoubleBuffered::m_signalThreshold private
Definition at line 41 of file samplesinkfifodoublebuffered.h.
Referenced by bumpIndex(), and SampleSinkFifoDoubleBuffered().
m_size
uint32_t SampleSinkFifoDoubleBuffered::m_size private
Definition at line 40 of file samplesinkfifodoublebuffered.h.
Referenced by bumpIndex(), and SampleSinkFifoDoubleBuffered().
The documentation for this class was generated from the following files:
sdrbase/dsp/samplesinkfifodoublebuffered.h
sdrbase/dsp/samplesinkfifodoublebuffered.cpp