SDRAngel: UpChannelizer::MsgChannelizerNotification Class Reference
UpChannelizer::MsgChannelizerNotification Class Reference
#include <upchannelizer.h>
Public Member Functions
MsgChannelizerNotification (int basebandSampleRate, int samplerate, qint64 frequencyOffset)
int getBasebandSampleRate () const
int getSampleRate () const
qint64 getFrequencyOffset () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgChannelizerNotification * create (int basebandSampleRate, int samplerate, qint64 frequencyOffset)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Attributes
int m_basebandSampleRate
int m_sampleRate
qint64 m_frequencyOffset
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 40 of file upchannelizer.h.
Constructor & Destructor Documentation
MsgChannelizerNotification()
UpChannelizer::MsgChannelizerNotification::MsgChannelizerNotification (int basebandSampleRate, int samplerate, qint64 frequencyOffset) inline
Definition at line 44 of file upchannelizer.h.
                                                                                                    :
             Message(),
             m_basebandSampleRate(basebandSampleRate),
             m_sampleRate(samplerate),
             m_frequencyOffset(frequencyOffset)
         { }
Member Function Documentation
create()
static MsgChannelizerNotification* UpChannelizer::MsgChannelizerNotification::create (int basebandSampleRate, int samplerate, qint64 frequencyOffset) inline static
Definition at line 55 of file upchannelizer.h.
Referenced by UpChannelizer::applyConfiguration(), and UpChannelizer::applySetting().
         {
             return new MsgChannelizerNotification(basebandSampleRate, samplerate, frequencyOffset);
         }
getBasebandSampleRate()
int UpChannelizer::MsgChannelizerNotification::getBasebandSampleRate () const inline
Definition at line 51 of file upchannelizer.h.
Referenced by UDPSource::handleMessage(), RemoteSource::handleMessage(), AMMod::handleMessage(), WFMMod::handleMessage(), NFMMod::handleMessage(), SSBMod::handleMessage(), and FreeDVMod::handleMessage().
 { return m_basebandSampleRate; }
getFrequencyOffset()
qint64 UpChannelizer::MsgChannelizerNotification::getFrequencyOffset () const inline
Definition at line 53 of file upchannelizer.h.
Referenced by UDPSource::handleMessage(), LocalSource::handleMessage(), RemoteSource::handleMessage(), AMMod::handleMessage(), WFMMod::handleMessage(), NFMMod::handleMessage(), SSBMod::handleMessage(), FreeDVMod::handleMessage(), FileSource::handleMessage(), and ATVMod::handleMessage().
 { return m_frequencyOffset; }
getSampleRate()
int UpChannelizer::MsgChannelizerNotification::getSampleRate () const inline
Definition at line 52 of file upchannelizer.h.
Referenced by UDPSource::handleMessage(), LocalSource::handleMessage(), RemoteSource::handleMessage(), AMMod::handleMessage(), WFMMod::handleMessage(), NFMMod::handleMessage(), SSBMod::handleMessage(), FreeDVMod::handleMessage(), FileSource::handleMessage(), and ATVMod::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_basebandSampleRate
int UpChannelizer::MsgChannelizerNotification::m_basebandSampleRate private
Definition at line 61 of file upchannelizer.h.
m_frequencyOffset
qint64 UpChannelizer::MsgChannelizerNotification::m_frequencyOffset private
Definition at line 63 of file upchannelizer.h.
m_sampleRate
int UpChannelizer::MsgChannelizerNotification::m_sampleRate private
Definition at line 62 of file upchannelizer.h.
The documentation for this class was generated from the following file:
sdrbase/dsp/upchannelizer.h