SDRAngel: RemoteSinkThread::MsgStartStop Class Reference
RemoteSinkThread::MsgStartStop Class Reference
#include <remotesinkthread.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 45 of file remotesinkthread.h.
Constructor & Destructor Documentation
MsgStartStop()
RemoteSinkThread::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 58 of file remotesinkthread.h.
References RemoteSinkThread::processDataBlock(), RemoteSinkThread::RemoteSinkThread(), RemoteSinkThread::startStop(), and RemoteSinkThread::~RemoteSinkThread().
Referenced by create().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* RemoteSinkThread::MsgStartStop::create (bool startStop) inline static
Definition at line 51 of file remotesinkthread.h.
References MsgStartStop().
Referenced by RemoteSinkThread::startStop().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool RemoteSinkThread::MsgStartStop::getStartStop () const inline
Definition at line 49 of file remotesinkthread.h.
References m_startStop.
Referenced by RemoteSinkThread::handleInputMessages().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool RemoteSinkThread::MsgStartStop::m_startStop protected
Definition at line 56 of file remotesinkthread.h.
Referenced by getStartStop().
The documentation for this class was generated from the following file:
plugins/channelrx/remotesink/remotesinkthread.h