SDRAngel: LimeSDROutput::MsgStartStop Class Reference
LimeSDROutput::MsgStartStop Class Reference
#include <limesdroutput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 63 of file limesdroutput.h.
Constructor & Destructor Documentation
MsgStartStop()
LimeSDROutput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 76 of file limesdroutput.h.
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* LimeSDROutput::MsgStartStop::create (bool startStop) inline static
Definition at line 69 of file limesdroutput.h.
Referenced by LimeSDROutputGUI::on_startStop_toggled(), and LimeSDROutput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool LimeSDROutput::MsgStartStop::getStartStop () const inline
Definition at line 67 of file limesdroutput.h.
Referenced by LimeSDROutputGUI::handleInputMessages(), and LimeSDROutput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool LimeSDROutput::MsgStartStop::m_startStop protected
Definition at line 74 of file limesdroutput.h.
The documentation for this class was generated from the following file:
plugins/samplesink/limesdroutput/limesdroutput.h