SDRAngel: qrtplib::RTCPSDESInfo Class Reference
qrtplib::RTCPSDESInfo Class Reference
#include <rtcpsdesinfo.h>
Classes
class SDESItem
class SDESPrivateItem
Public Member Functions
RTCPSDESInfo ()
virtual ~RTCPSDESInfo ()
void Clear ()
int SetCNAME (const uint8_t *s, std::size_t l)
int SetName (const uint8_t *s, std::size_t l)
int SetEMail (const uint8_t *s, std::size_t l)
int SetPhone (const uint8_t *s, std::size_t l)
int SetLocation (const uint8_t *s, std::size_t l)
int SetTool (const uint8_t *s, std::size_t l)
int SetNote (const uint8_t *s, std::size_t l)
int SetPrivateValue (const uint8_t *prefix, std::size_t prefixlen, const uint8_t *value, std::size_t valuelen)
int DeletePrivatePrefix (const uint8_t *s, std::size_t len)
uint8_t * GetCNAME (std::size_t *len) const
uint8_t * GetName (std::size_t *len) const
uint8_t * GetEMail (std::size_t *len) const
uint8_t * GetPhone (std::size_t *len) const
uint8_t * GetLocation (std::size_t *len) const
uint8_t * GetTool (std::size_t *len) const
uint8_t * GetNote (std::size_t *len) const
void GotoFirstPrivateValue ()
bool GetNextPrivateValue (uint8_t **prefix, std::size_t *prefixlen, uint8_t **value, std::size_t *valuelen)
bool GetPrivateValue (const uint8_t *prefix, std::size_t prefixlen, uint8_t **value, std::size_t *valuelen) const
Private Member Functions
int SetNonPrivateItem (int itemno, const uint8_t *s, std::size_t l)
uint8_t * GetNonPrivateItem (int itemno, std::size_t *len) const
Private Attributes
SDESItem nonprivateitems [RTCP_SDES_NUMITEMS_NONPRIVATE]
std::list< SDESPrivateItem * > privitems
std::list< SDESPrivateItem * >::const_iterator curitem
Detailed Description
The class RTCPSDESInfo is a container for RTCP SDES information.
Definition at line 54 of file rtcpsdesinfo.h.
Constructor & Destructor Documentation
RTCPSDESInfo()
qrtplib::RTCPSDESInfo::RTCPSDESInfo () inline
Constructs an instance, optionally installing a memory manager.
Definition at line 58 of file rtcpsdesinfo.h.
     {
     }
~RTCPSDESInfo()
virtual qrtplib::RTCPSDESInfo::~RTCPSDESInfo () inline virtual
Definition at line 61 of file rtcpsdesinfo.h.
     {
         Clear();
     }
Member Function Documentation
Clear()
void qrtplib::RTCPSDESInfo::Clear ()
Clears all SDES information.
Definition at line 38 of file rtcpsdesinfo.cpp.
References privitems.
Referenced by qrtplib::RTCPPacketBuilder::Destroy().
 {
 #ifdef RTP_SUPPORT_SDESPRIV
     std::list<SDESPrivateItem *>::const_iterator it;
     for (it = privitems.begin(); it != privitems.end(); ++it)
         delete *it;
     privitems.clear();
 #endif // RTP_SUPPORT_SDESPRIV
 }
DeletePrivatePrefix()
int qrtplib::RTCPSDESInfo::DeletePrivatePrefix (const uint8_t * s, std::size_t len)
Deletes the entry for the prefix specified by s with length len.
Definition at line 99 of file rtcpsdesinfo.cpp.
References ERR_RTP_SDES_PREFIXNOTFOUND, and privitems.
 {
     std::list<SDESPrivateItem *>::iterator it;
     bool found;
     found = false;
     it = privitems.begin();
     while (!found && it != privitems.end())
     {
         uint8_t *p;
         std::size_t l;
         p = (*it)->GetPrefix(&l);
         if (l == prefixlen)
         {
             if (l <= 0)
                 found = true;
             else if (memcmp(prefix, p, l) == 0)
                 found = true;
             else
                 ++it;
         }
         else
             ++it;
     }
     if (!found)
         return ERR_RTP_SDES_PREFIXNOTFOUND;
     delete *it;
     privitems.erase(it);
     return 0;
 }
GetCNAME()
uint8_t* qrtplib::RTCPSDESInfo::GetCNAME (std::size_t * len) const inline
Returns the SDES CNAME item and stores its length in len.
Definition at line 123 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_CNAME.
Referenced by qrtplib::RTCPPacketBuilder::BuildBYEPacket(), qrtplib::RTCPPacketBuilder::BuildNextPacket(), and qrtplib::RTPInternalSourceData::ProcessSDESItem().
     {
         return GetNonPrivateItem(RTCP_SDES_ID_CNAME - 1, len);
     }
GetEMail()
uint8_t* qrtplib::RTCPSDESInfo::GetEMail (std::size_t * len) const inline
Returns the SDES e-mail item and stores its length in len.
Definition at line 135 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_EMAIL.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES(), and qrtplib::RTPInternalSourceData::ProcessSDESItem().
     {
         return GetNonPrivateItem(RTCP_SDES_ID_EMAIL - 1, len);
     }
GetLocation()
uint8_t* qrtplib::RTCPSDESInfo::GetLocation (std::size_t * len) const inline
Returns the SDES location item and stores its length in len.
Definition at line 147 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_LOCATION.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
     {
         return GetNonPrivateItem(RTCP_SDES_ID_LOCATION - 1, len);
     }
GetName()
uint8_t* qrtplib::RTCPSDESInfo::GetName (std::size_t * len) const inline
Returns the SDES name item and stores its length in len.
Definition at line 129 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_NAME.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES(), and qrtplib::RTPInternalSourceData::ProcessSDESItem().
     {
         return GetNonPrivateItem(RTCP_SDES_ID_NAME - 1, len);
     }
GetNextPrivateValue()
bool qrtplib::RTCPSDESInfo::GetNextPrivateValue (uint8_t ** prefix, std::size_t * prefixlen, uint8_t ** value, std::size_t * valuelen)
Returns SDES priv item information. If available, returns true and stores the next SDES private item prefix in prefix and its length in prefixlen. The associated value and its length are then stored in value and valuelen. Otherwise, it returns false.
Definition at line 137 of file rtcpsdesinfo.cpp.
References curitem, and privitems.
 {
     if (curitem == privitems.end())
         return false;
     *prefix = (*curitem)->GetPrefix(prefixlen);
     *value = (*curitem)->GetInfo(valuelen);
     ++curitem;
     return true;
 }
GetNonPrivateItem()
uint8_t* qrtplib::RTCPSDESInfo::GetNonPrivateItem (int itemno, std::size_t * len) const inline private
Definition at line 192 of file rtcpsdesinfo.h.
     {
         return nonprivateitems[itemno].GetInfo(len);
     }
GetNote()
uint8_t* qrtplib::RTCPSDESInfo::GetNote (std::size_t * len) const inline
Returns the SDES note item and stores its length in len.
Definition at line 159 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_NOTE.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
     {
         return GetNonPrivateItem(RTCP_SDES_ID_NOTE - 1, len);
     }
GetPhone()
uint8_t* qrtplib::RTCPSDESInfo::GetPhone (std::size_t * len) const inline
Returns the SDES phone item and stores its length in len.
Definition at line 141 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_PHONE.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
     {
         return GetNonPrivateItem(RTCP_SDES_ID_PHONE - 1, len);
     }
GetPrivateValue()
bool qrtplib::RTCPSDESInfo::GetPrivateValue (const uint8_t * prefix, std::size_t prefixlen, uint8_t ** value, std::size_t * valuelen) const
Returns SDES priv item information. Looks for the entry which corresponds to the SDES private item prefix prefix with length prefixlen. If found, the function returns true and stores the associated value and its length in value and valuelen respectively.
Definition at line 147 of file rtcpsdesinfo.cpp.
References privitems.
 {
     std::list<SDESPrivateItem *>::const_iterator it;
     bool found;
     found = false;
     it = privitems.begin();
     while (!found && it != privitems.end())
     {
         uint8_t *p;
         std::size_t l;
         p = (*it)->GetPrefix(&l);
         if (l == prefixlen)
         {
             if (l <= 0)
                 found = true;
             else if (memcmp(prefix, p, l) == 0)
                 found = true;
             else
                 ++it;
         }
         else
             ++it;
     }
     if (found)
         *value = (*it)->GetInfo(valuelen);
     return found;
 }
GetTool()
uint8_t* qrtplib::RTCPSDESInfo::GetTool (std::size_t * len) const inline
Returns the SDES tool item and stores its length in len.
Definition at line 153 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_TOOL.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES(), and qrtplib::RTPInternalSourceData::ProcessSDESItem().
     {
         return GetNonPrivateItem(RTCP_SDES_ID_TOOL - 1, len);
     }
GotoFirstPrivateValue()
void qrtplib::RTCPSDESInfo::GotoFirstPrivateValue ()
Starts the iteration over the stored SDES private item prefixes and their associated values.
Definition at line 132 of file rtcpsdesinfo.cpp.
References curitem, and privitems.
 {
     curitem = privitems.begin();
 }
SetCNAME()
int qrtplib::RTCPSDESInfo::SetCNAME (const uint8_t * s, std::size_t l) inline
Sets the SDES CNAME item to s with length l.
Definition at line 70 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_CNAME.
Referenced by qrtplib::RTCPPacketBuilder::Init(), and qrtplib::RTPInternalSourceData::ProcessSDESItem().
     {
         return SetNonPrivateItem(RTCP_SDES_ID_CNAME - 1, s, l);
     }
SetEMail()
int qrtplib::RTCPSDESInfo::SetEMail (const uint8_t * s, std::size_t l) inline
Sets the SDES e-mail item to s with length l.
Definition at line 82 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_EMAIL.
Referenced by qrtplib::RTPInternalSourceData::ProcessSDESItem().
     {
         return SetNonPrivateItem(RTCP_SDES_ID_EMAIL - 1, s, l);
     }
SetLocation()
int qrtplib::RTCPSDESInfo::SetLocation (const uint8_t * s, std::size_t l) inline
Sets the SDES location item to s with length l.
Definition at line 94 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_LOCATION.
Referenced by qrtplib::RTPInternalSourceData::ProcessSDESItem().
     {
         return SetNonPrivateItem(RTCP_SDES_ID_LOCATION - 1, s, l);
     }
SetName()
int qrtplib::RTCPSDESInfo::SetName (const uint8_t * s, std::size_t l) inline
Sets the SDES name item to s with length l.
Definition at line 76 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_NAME.
Referenced by qrtplib::RTPInternalSourceData::ProcessSDESItem().
     {
         return SetNonPrivateItem(RTCP_SDES_ID_NAME - 1, s, l);
     }
SetNonPrivateItem()
int qrtplib::RTCPSDESInfo::SetNonPrivateItem (int itemno, const uint8_t * s, std::size_t l) inline private
Definition at line 186 of file rtcpsdesinfo.h.
References ERR_RTP_SDES_LENGTHTOOBIG, and RTCP_SDES_MAXITEMLENGTH.
     {
         if (l > RTCP_SDES_MAXITEMLENGTH)
             return ERR_RTP_SDES_LENGTHTOOBIG;
         return nonprivateitems[itemno].SetInfo(s, l);
     }
SetNote()
int qrtplib::RTCPSDESInfo::SetNote (const uint8_t * s, std::size_t l) inline
Sets the SDES note item to s with length l.
Definition at line 106 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_NOTE.
Referenced by qrtplib::RTPInternalSourceData::ProcessSDESItem().
     {
         return SetNonPrivateItem(RTCP_SDES_ID_NOTE - 1, s, l);
     }
SetPhone()
int qrtplib::RTCPSDESInfo::SetPhone (const uint8_t * s, std::size_t l) inline
Sets the SDES phone item to s with length l.
Definition at line 88 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_PHONE.
Referenced by qrtplib::RTPInternalSourceData::ProcessSDESItem().
     {
         return SetNonPrivateItem(RTCP_SDES_ID_PHONE - 1, s, l);
     }
SetPrivateValue()
int qrtplib::RTCPSDESInfo::SetPrivateValue (const uint8_t * prefix, std::size_t prefixlen, const uint8_t * value, std::size_t valuelen)
Sets the entry for the prefix string specified by prefix with length prefixlen to contain the value string specified by value with length valuelen (if the maximum allowed number of prefixes was reached, the error code ERR_RTP_SDES_MAXPRIVITEMS is returned.
Definition at line 50 of file rtcpsdesinfo.cpp.
References ERR_RTP_SDES_MAXPRIVITEMS, privitems, RTP_MAXPRIVITEMS, qrtplib::RTCPSDESInfo::SDESItem::SetInfo(), and qrtplib::RTCPSDESInfo::SDESPrivateItem::SetPrefix().
Referenced by qrtplib::RTPInternalSourceData::ProcessPrivateSDESItem().
 {
     std::list<SDESPrivateItem *>::const_iterator it;
     bool found;
     found = false;
     it = privitems.begin();
     while (!found && it != privitems.end())
     {
         uint8_t *p;
         std::size_t l;
         p = (*it)->GetPrefix(&l);
         if (l == prefixlen)
         {
             if (l <= 0)
                 found = true;
             else if (memcmp(prefix, p, l) == 0)
                 found = true;
             else
                 ++it;
         }
         else
             ++it;
     }
     SDESPrivateItem *item;
     if (found) // replace the value for this entry
         item = *it;
     else // no entry for this prefix found... add it
     {
         if (privitems.size() >= RTP_MAXPRIVITEMS) // too many items present, just ignore it
             return ERR_RTP_SDES_MAXPRIVITEMS;
         int status;
         item = new SDESPrivateItem();
         if ((status = item->SetPrefix(prefix, prefixlen)) < 0)
         {
             delete item;
             return status;
         }
         privitems.push_front(item);
     }
     return item->SetInfo(value, valuelen);
 }
SetTool()
int qrtplib::RTCPSDESInfo::SetTool (const uint8_t * s, std::size_t l) inline
Sets the SDES tool item to s with length l.
Definition at line 100 of file rtcpsdesinfo.h.
References RTCP_SDES_ID_TOOL.
Referenced by qrtplib::RTPInternalSourceData::ProcessSDESItem().
     {
         return SetNonPrivateItem(RTCP_SDES_ID_TOOL - 1, s, l);
     }
Member Data Documentation
curitem
std::list<SDESPrivateItem *>::const_iterator qrtplib::RTCPSDESInfo::curitem private
Definition at line 277 of file rtcpsdesinfo.h.
Referenced by GetNextPrivateValue(), and GotoFirstPrivateValue().
nonprivateitems
SDESItem qrtplib::RTCPSDESInfo::nonprivateitems[RTCP_SDES_NUMITEMS_NONPRIVATE] private
Definition at line 246 of file rtcpsdesinfo.h.
privitems
std::list<SDESPrivateItem *> qrtplib::RTCPSDESInfo::privitems private
Definition at line 276 of file rtcpsdesinfo.h.
Referenced by Clear(), DeletePrivatePrefix(), GetNextPrivateValue(), GetPrivateValue(), GotoFirstPrivateValue(), and SetPrivateValue().
The documentation for this class was generated from the following files:
qrtplib/rtcpsdesinfo.h
qrtplib/rtcpsdesinfo.cpp