SDRAngel: DeviceXTRXShared::ThreadInterface Class Reference
DeviceXTRXShared::ThreadInterface Class Reference abstract
#include <devicextrxshared.h>
Public Member Functions
virtual void startWork ()=0
virtual void stopWork ()=0
virtual bool isRunning ()=0
Detailed Description
Definition at line 128 of file devicextrxshared.h.
Member Function Documentation
isRunning()
virtual bool DeviceXTRXShared::ThreadInterface::isRunning () pure virtual
Implemented in XTRXInputThread, and XTRXOutputThread.
Referenced by XTRXOutput::suspendRxThread(), and XTRXInput::suspendTxThread().
startWork()
virtual void DeviceXTRXShared::ThreadInterface::startWork () pure virtual
Implemented in XTRXInputThread, and XTRXOutputThread.
Referenced by XTRXOutput::resumeRxThread(), and XTRXInput::resumeTxThread().
stopWork()
virtual void DeviceXTRXShared::ThreadInterface::stopWork () pure virtual
Implemented in XTRXInputThread, and XTRXOutputThread.
Referenced by XTRXOutput::suspendRxThread(), and XTRXInput::suspendTxThread().
The documentation for this class was generated from the following file:
devices/xtrx/devicextrxshared.h