SDRAngel: LimeSDROutputGUI Class Reference
LimeSDROutputGUI Class Reference
#include <limesdroutputgui.h>
Public Member Functions
LimeSDROutputGUI (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~LimeSDROutputGUI ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_startStop_toggled (bool checked)
void on_centerFrequency_changed (quint64 value)
void on_ncoFrequency_changed (qint64 value)
void on_ncoEnable_toggled (bool checked)
void on_sampleRate_changed (quint64 value)
void on_hwInterp_currentIndexChanged (int index)
void on_swInterp_currentIndexChanged (int index)
void on_lpf_changed (quint64 value)
void on_lpFIREnable_toggled (bool checked)
void on_lpFIR_changed (quint64 value)
void on_gain_valueChanged (int value)
void on_antenna_currentIndexChanged (int index)
void on_extClock_clicked ()
void on_transverter_clicked ()
void on_sampleRateMode_toggled (bool checked)
void openDeviceSettingsDialog (const QPoint &p)
void updateHardware ()
void updateStatus ()
Private Member Functions
void displaySettings ()
void displaySampleRate ()
void setNCODisplay ()
void setCenterFrequencyDisplay ()
void setCenterFrequencySetting (uint64_t kHzValue)
void sendSettings ()
void updateSampleRateAndFrequency ()
void updateDACRate ()
void updateFrequencyLimits ()
void blockApplySettings (bool block)
Private Attributes
Ui::LimeSDROutputGUI * ui
DeviceUISet * m_deviceUISet
LimeSDROutput * m_limeSDROutput
Same object as above but gives easy access to LimeSDROutput methods and attributes that are used intensively.
LimeSDROutputSettings m_settings
bool m_sampleRateMode
true: device, false: base band sample rate update mode
QTimer m_updateTimer
QTimer m_statusTimer
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
bool m_doApplySettings
bool m_forceSettings
int m_statusCounter
int m_deviceStatusCounter
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 36 of file limesdroutputgui.h.
Constructor & Destructor Documentation
LimeSDROutputGUI()
LimeSDROutputGUI::LimeSDROutputGUI (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 32 of file limesdroutputgui.cpp.
References arg(), displaySettings(), LimeSDROutput::getChannelIndex(), DeviceAPI::getDeviceUID(), LimeSDROutput::getLimeType(), LimeSDROutput::getLORange(), LimeSDROutput::getLPRange(), DeviceAPI::getSampleSink(), LimeSDROutput::getSRRange(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, ColorMapper::GrayYellow, handleInputMessages(), DeviceLimeSDRParams::LimeMini, DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_limeSDROutput, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), sendSettings(), ui, updateHardware(), and updateStatus().
                                                                             :
     QWidget(parent),
     ui(new Ui::LimeSDROutputGUI),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_sampleRateMode(true),
     m_sampleRate(0),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_statusCounter(0),
     m_deviceStatusCounter(0)
 {
     m_limeSDROutput = (LimeSDROutput*) m_deviceUISet->m_deviceAPI->getSampleSink();
     ui->setupUi(this);
     float minF, maxF;
     m_limeSDROutput->getLORange(minF, maxF);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, ((uint32_t) minF)/1000, ((uint32_t) maxF)/1000); // frequency dial is in kHz
     m_limeSDROutput->getSRRange(minF, maxF);
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(8, (uint32_t) minF, (uint32_t) maxF);
     m_limeSDROutput->getLPRange(minF, maxF);
     ui->lpf->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     ui->lpf->setValueRange(6, (minF/1000)+1, maxF/1000);
     ui->lpFIR->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     ui->lpFIR->setValueRange(5, 1U, 56000U);
     ui->ncoFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->channelNumberText->setText(tr("#%1").arg(m_limeSDROutput->getChannelIndex()));
     if (m_limeSDROutput->getLimeType() == DeviceLimeSDRParams::LimeMini)
     {
         ui->antenna->setItemText(1, "Hi");
         ui->antenna->setItemText(2, "Lo");
     }
     else
     {
         ui->antenna->setItemText(1, "Lo");
         ui->antenna->setItemText(2, "Hi");
     }
     ui->hwInterpLabel->setText(QString::fromUtf8("H\u2191"));
     ui->swInterpLabel->setText(QString::fromUtf8("S\u2191"));
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     displaySettings();
     char recFileNameCStr[30];
     sprintf(recFileNameCStr, "test_%d.sdriq", m_deviceUISet->m_deviceAPI->getDeviceUID());
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     sendSettings();
 }
~LimeSDROutputGUI()
LimeSDROutputGUI::~LimeSDROutputGUI () virtual
Definition at line 101 of file limesdroutputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void LimeSDROutputGUI::blockApplySettings (bool block) private
Definition at line 509 of file limesdroutputgui.cpp.
References m_doApplySettings.
Referenced by handleInputMessages(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool LimeSDROutputGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 145 of file limesdroutputgui.cpp.
References LimeSDROutputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if (m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void LimeSDROutputGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 106 of file limesdroutputgui.cpp.
 {
     delete this;
 }
displaySampleRate()
void LimeSDROutputGUI::displaySampleRate () private
Definition at line 332 of file limesdroutputgui.cpp.
References arg(), LimeSDROutput::getSRRange(), LimeSDROutputSettings::m_devSampleRate, m_limeSDROutput, LimeSDROutputSettings::m_log2SoftInterp, m_sampleRateMode, m_settings, and ui.
Referenced by displaySettings(), on_sampleRateMode_toggled(), on_swInterp_currentIndexChanged(), and updateSampleRateAndFrequency().
 {
     float minF, maxF;
     m_limeSDROutput->getSRRange(minF, maxF);
     ui->sampleRate->blockSignals(true);
     if (m_sampleRateMode)
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(60,60,60); }");
         ui->sampleRateMode->setText("SR");
         ui->sampleRate->setValueRange(8, (uint32_t) minF, (uint32_t) maxF);
         ui->sampleRate->setValue(m_settings.m_devSampleRate);
         ui->sampleRate->setToolTip("Host to device sample rate (S/s)");
         ui->deviceRateText->setToolTip("Baseband sample rate (S/s)");
         uint32_t basebandSampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2SoftInterp);
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(basebandSampleRate / 1000.0f, 'g', 5)));
     }
     else
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(50,50,50); }");
         ui->sampleRateMode->setText("BB");
         ui->sampleRate->setValueRange(8, (uint32_t) minF/(1<<m_settings.m_log2SoftInterp), (uint32_t) maxF/(1<<m_settings.m_log2SoftInterp));
         ui->sampleRate->setValue(m_settings.m_devSampleRate/(1<<m_settings.m_log2SoftInterp));
         ui->sampleRate->setToolTip("Baseband sample rate (S/s)");
         ui->deviceRateText->setToolTip("Host to device sample rate (S/s)");
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_settings.m_devSampleRate / 1000.0f, 'g', 5)));
     }
     ui->sampleRate->blockSignals(false);
 }
displaySettings()
void LimeSDROutputGUI::displaySettings () private
Definition at line 364 of file limesdroutputgui.cpp.
References arg(), displaySampleRate(), LimeSDROutputSettings::m_antennaPath, LimeSDROutputSettings::m_extClock, LimeSDROutputSettings::m_extClockFreq, LimeSDROutputSettings::m_gain, LimeSDROutputSettings::m_log2HardInterp, LimeSDROutputSettings::m_log2SoftInterp, LimeSDROutputSettings::m_lpfBW, LimeSDROutputSettings::m_lpfFIRBW, LimeSDROutputSettings::m_lpfFIREnable, LimeSDROutputSettings::m_ncoEnable, m_settings, LimeSDROutputSettings::m_transverterDeltaFrequency, LimeSDROutputSettings::m_transverterMode, setCenterFrequencyDisplay(), setNCODisplay(), ui, and updateDACRate().
Referenced by deserialize(), handleInputMessages(), handleMessage(), LimeSDROutputGUI(), resetToDefaults(), and setCenterFrequency().
 {
     ui->transverter->setDeltaFrequency(m_settings.m_transverterDeltaFrequency);
     ui->transverter->setDeltaFrequencyActive(m_settings.m_transverterMode);
     ui->extClock->setExternalClockFrequency(m_settings.m_extClockFreq);
     ui->extClock->setExternalClockActive(m_settings.m_extClock);
     setCenterFrequencyDisplay();
     displaySampleRate();
     ui->hwInterp->setCurrentIndex(m_settings.m_log2HardInterp);
     ui->swInterp->setCurrentIndex(m_settings.m_log2SoftInterp);
     updateDACRate();
     ui->lpf->setValue(m_settings.m_lpfBW / 1000);
     ui->lpFIREnable->setChecked(m_settings.m_lpfFIREnable);
     ui->lpFIR->setValue(m_settings.m_lpfFIRBW / 1000);
     ui->gain->setValue(m_settings.m_gain);
     ui->gainText->setText(tr("%1dB").arg(m_settings.m_gain));
     ui->antenna->setCurrentIndex((int) m_settings.m_antennaPath);
     setNCODisplay();
     ui->ncoEnable->setChecked(m_settings.m_ncoEnable);
 }
getCenterFrequency()
qint64 LimeSDROutputGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 128 of file limesdroutputgui.cpp.
References LimeSDROutputSettings::m_centerFrequency, LimeSDROutputSettings::m_ncoEnable, LimeSDROutputSettings::m_ncoFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency + (m_settings.m_ncoEnable ? m_settings.m_ncoFrequency : 0);
 }
getInputMessageQueue()
virtual MessageQueue* LimeSDROutputGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 52 of file limesdroutputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString LimeSDROutputGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 116 of file limesdroutputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void LimeSDROutputGUI::handleInputMessages () private slot
Definition at line 272 of file limesdroutputgui.cpp.
References blockApplySettings(), displaySettings(), Message::getIdentifier(), LimeSDROutput::MsgConfigureLimeSDR::getSettings(), LimeSDROutput::MsgStartStop::getStartStop(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, m_settings, Message::match(), MessageQueue::pop(), ui, and updateSampleRateAndFrequency().
Referenced by LimeSDROutputGUI().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (DSPSignalNotification::match(*message))
         {
             qDebug("LimeSDROutputGUI::handleInputMessages: message: %s", message->getIdentifier());
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("LimeSDROutputGUI::handleInputMessages: DSPSignalNotification: SampleRate: %d, CenterFrequency: %llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else if (LimeSDROutput::MsgConfigureLimeSDR::match(*message))
         {
             const LimeSDROutput::MsgConfigureLimeSDR& cfg = (LimeSDROutput::MsgConfigureLimeSDR&) *message;
             m_settings = cfg.getSettings();
             displaySettings();
             delete message;
         }
         else if (LimeSDROutput::MsgStartStop::match(*message))
         {
             LimeSDROutput::MsgStartStop& notif = (LimeSDROutput::MsgStartStop&) *message;
             blockApplySettings(true);
             ui->startStop->setChecked(notif.getStartStop());
             blockApplySettings(false);
             delete message;
         }
         else
         {
             if (handleMessage(*message)) {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool LimeSDROutputGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 178 of file limesdroutputgui.cpp.
References arg(), blockApplySettings(), displaySettings(), LimeSDROutput::MsgReportStreamInfo::getActive(), DeviceLimeSDRShared::MsgReportBuddyChange::getCenterFrequency(), DeviceLimeSDRShared::MsgReportBuddyChange::getDevSampleRate(), LimeSDROutput::MsgReportStreamInfo::getDroppedPackets(), DeviceLimeSDRShared::MsgReportClockSourceChange::getExtClock(), DeviceLimeSDRShared::MsgReportClockSourceChange::getExtClockFeq(), LimeSDROutput::MsgReportStreamInfo::getFifoFilledCount(), LimeSDROutput::MsgReportStreamInfo::getFifoSize(), DeviceLimeSDRShared::MsgReportDeviceInfo::getGPIOPins(), LimeSDROutput::MsgReportStreamInfo::getLinkRate(), DeviceLimeSDRShared::MsgReportBuddyChange::getLog2HardDecimInterp(), LimeSDROutput::MsgReportStreamInfo::getOverrun(), DeviceLimeSDRShared::MsgReportBuddyChange::getRxElseTx(), LimeSDROutput::MsgConfigureLimeSDR::getSettings(), LimeSDROutput::MsgReportStreamInfo::getSuccess(), DeviceLimeSDRShared::MsgReportDeviceInfo::getTemperature(), LimeSDROutput::MsgReportStreamInfo::getUnderrun(), LimeSDROutputSettings::m_centerFrequency, LimeSDROutputSettings::m_devSampleRate, LimeSDROutputSettings::m_extClock, LimeSDROutputSettings::m_extClockFreq, LimeSDROutputSettings::m_log2HardInterp, m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (LimeSDROutput::MsgConfigureLimeSDR::match(message))
     {
         const LimeSDROutput::MsgConfigureLimeSDR& cfg = (LimeSDROutput::MsgConfigureLimeSDR&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (DeviceLimeSDRShared::MsgReportBuddyChange::match(message))
     {
         DeviceLimeSDRShared::MsgReportBuddyChange& report = (DeviceLimeSDRShared::MsgReportBuddyChange&) message;
         m_settings.m_devSampleRate = report.getDevSampleRate();
         m_settings.m_log2HardInterp = report.getLog2HardDecimInterp();
         if (!report.getRxElseTx()) {
             m_settings.m_centerFrequency = report.getCenterFrequency();
         }
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (DeviceLimeSDRShared::MsgReportClockSourceChange::match(message))
     {
         DeviceLimeSDRShared::MsgReportClockSourceChange& report = (DeviceLimeSDRShared::MsgReportClockSourceChange&) message;
         m_settings.m_extClockFreq = report.getExtClockFeq();
         m_settings.m_extClock = report.getExtClock();
         blockApplySettings(true);
         ui->extClock->setExternalClockFrequency(m_settings.m_extClockFreq);
         ui->extClock->setExternalClockActive(m_settings.m_extClock);
         blockApplySettings(false);
         return true;
     }
     else if (LimeSDROutput::MsgReportStreamInfo::match(message))
     {
         LimeSDROutput::MsgReportStreamInfo& report = (LimeSDROutput::MsgReportStreamInfo&) message;
         if (report.getSuccess())
         {
             if (report.getActive()) {
                 ui->streamStatusLabel->setStyleSheet("QLabel { background-color : green; }");
             } else {
                 ui->streamStatusLabel->setStyleSheet("QLabel { background-color : blue; }");
             }
             ui->streamLinkRateText->setText(tr("%1 MB/s").arg(QString::number(report.getLinkRate() / 1000000.0f, 'f', 3)));
             if (report.getUnderrun() > 0) {
                 ui->underrunLabel->setStyleSheet("QLabel { background-color : red; }");
             } else {
                 ui->underrunLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
             }
             if (report.getOverrun() > 0) {
                 ui->overrunLabel->setStyleSheet("QLabel { background-color : red; }");
             } else {
                 ui->overrunLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
             }
             if (report.getDroppedPackets() > 0) {
                 ui->droppedLabel->setStyleSheet("QLabel { background-color : red; }");
             } else {
                 ui->droppedLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
             }
             ui->fifoBar->setMaximum(report.getFifoSize());
             ui->fifoBar->setValue(report.getFifoFilledCount());
             ui->fifoBar->setToolTip(tr("FIFO fill %1/%2 samples").arg(QString::number(report.getFifoFilledCount())).arg(QString::number(report.getFifoSize())));
         }
         else
         {
             ui->streamStatusLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
         }
         return true;
     }
     else if (DeviceLimeSDRShared::MsgReportDeviceInfo::match(message))
     {
         DeviceLimeSDRShared::MsgReportDeviceInfo& report = (DeviceLimeSDRShared::MsgReportDeviceInfo&) message;
         ui->temperatureText->setText(tr("%1C").arg(QString::number(report.getTemperature(), 'f', 0)));
         ui->gpioText->setText(tr("%1").arg(report.getGPIOPins(), 2, 16, QChar('0')).toUpper());
         return true;
     }
     return false;
 }
on_antenna_currentIndexChanged
void LimeSDROutputGUI::on_antenna_currentIndexChanged (int index) private slot
Definition at line 608 of file limesdroutputgui.cpp.
References LimeSDROutputSettings::m_antennaPath, m_settings, and sendSettings().
 {
     m_settings.m_antennaPath = (LimeSDROutputSettings::PathRFE) index;
     sendSettings();
 }
on_centerFrequency_changed
void LimeSDROutputGUI::on_centerFrequency_changed (quint64 value) private slot
Definition at line 523 of file limesdroutputgui.cpp.
References sendSettings(), and setCenterFrequencySetting().
 {
     setCenterFrequencySetting(value);
     sendSettings();
 }
on_extClock_clicked
void LimeSDROutputGUI::on_extClock_clicked () private slot
Definition at line 614 of file limesdroutputgui.cpp.
References LimeSDROutputSettings::m_extClock, LimeSDROutputSettings::m_extClockFreq, m_settings, sendSettings(), and ui.
 {
     m_settings.m_extClock = ui->extClock->getExternalClockActive();
     m_settings.m_extClockFreq = ui->extClock->getExternalClockFrequency();
     qDebug("LimeSDROutputGUI::on_extClock_clicked: %u Hz %s", m_settings.m_extClockFreq, m_settings.m_extClock ? "on" : "off");
     sendSettings();
 }
on_gain_valueChanged
void LimeSDROutputGUI::on_gain_valueChanged (int value) private slot
Definition at line 601 of file limesdroutputgui.cpp.
References arg(), LimeSDROutputSettings::m_gain, m_settings, sendSettings(), and ui.
 {
     m_settings.m_gain = value;
     ui->gainText->setText(tr("%1dB").arg(m_settings.m_gain));
     sendSettings();
 }
on_hwInterp_currentIndexChanged
void LimeSDROutputGUI::on_hwInterp_currentIndexChanged (int index) private slot
Definition at line 555 of file limesdroutputgui.cpp.
References LimeSDROutputSettings::m_log2HardInterp, m_settings, sendSettings(), setNCODisplay(), and updateDACRate().
 {
     if ((index <0) || (index > 5))
         return;
     m_settings.m_log2HardInterp = index;
     updateDACRate();
     setNCODisplay();
     sendSettings();
 }
on_lpf_changed
void LimeSDROutputGUI::on_lpf_changed (quint64 value) private slot
Definition at line 583 of file limesdroutputgui.cpp.
References LimeSDROutputSettings::m_lpfBW, m_settings, and sendSettings().
 {
     m_settings.m_lpfBW = value * 1000;
     sendSettings();
 }
on_lpFIR_changed
void LimeSDROutputGUI::on_lpFIR_changed (quint64 value) private slot
Definition at line 595 of file limesdroutputgui.cpp.
References LimeSDROutputSettings::m_lpfFIRBW, m_settings, and sendSettings().
 {
     m_settings.m_lpfFIRBW = value * 1000;
     sendSettings();
 }
on_lpFIREnable_toggled
void LimeSDROutputGUI::on_lpFIREnable_toggled (bool checked) private slot
Definition at line 589 of file limesdroutputgui.cpp.
References LimeSDROutputSettings::m_lpfFIREnable, m_settings, and sendSettings().
 {
     m_settings.m_lpfFIREnable = checked;
     sendSettings();
 }
on_ncoEnable_toggled
void LimeSDROutputGUI::on_ncoEnable_toggled (bool checked) private slot
Definition at line 536 of file limesdroutputgui.cpp.
References LimeSDROutputSettings::m_ncoEnable, m_settings, sendSettings(), and setCenterFrequencyDisplay().
 {
     m_settings.m_ncoEnable = checked;
     setCenterFrequencyDisplay();
     sendSettings();
 }
on_ncoFrequency_changed
void LimeSDROutputGUI::on_ncoFrequency_changed (qint64 value) private slot
Definition at line 529 of file limesdroutputgui.cpp.
References LimeSDROutputSettings::m_ncoFrequency, m_settings, sendSettings(), and setCenterFrequencyDisplay().
 {
     m_settings.m_ncoFrequency = value;
     setCenterFrequencyDisplay();
     sendSettings();
 }
on_sampleRate_changed
void LimeSDROutputGUI::on_sampleRate_changed (quint64 value) private slot
Definition at line 543 of file limesdroutputgui.cpp.
References LimeSDROutputSettings::m_devSampleRate, LimeSDROutputSettings::m_log2SoftInterp, m_sampleRateMode, m_settings, sendSettings(), setNCODisplay(), and updateDACRate().
 {
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = value;
     } else {
         m_settings.m_devSampleRate = value * (1 << m_settings.m_log2SoftInterp);
     }
     updateDACRate();
     setNCODisplay();
     sendSettings();}
on_sampleRateMode_toggled
void LimeSDROutputGUI::on_sampleRateMode_toggled (bool checked) private slot
Definition at line 632 of file limesdroutputgui.cpp.
References displaySampleRate(), and m_sampleRateMode.
 {
     m_sampleRateMode = checked;
     displaySampleRate();
 }
on_startStop_toggled
void LimeSDROutputGUI::on_startStop_toggled (bool checked) private slot
Definition at line 514 of file limesdroutputgui.cpp.
References LimeSDROutput::MsgStartStop::create(), DeviceSampleSink::getInputMessageQueue(), m_doApplySettings, m_limeSDROutput, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         LimeSDROutput::MsgStartStop *message = LimeSDROutput::MsgStartStop::create(checked);
         m_limeSDROutput->getInputMessageQueue()->push(message);
     }
 }
on_swInterp_currentIndexChanged
void LimeSDROutputGUI::on_swInterp_currentIndexChanged (int index) private slot
Definition at line 565 of file limesdroutputgui.cpp.
References displaySampleRate(), LimeSDROutputSettings::m_devSampleRate, LimeSDROutputSettings::m_log2SoftInterp, m_sampleRateMode, m_settings, sendSettings(), and ui.
 {
     if ((index <0) || (index > 6)) {
         return;
     }
     m_settings.m_log2SoftInterp = index;
     displaySampleRate();
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     } else {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew() * (1 << m_settings.m_log2SoftInterp);
     }
     sendSettings();
 }
on_transverter_clicked
void LimeSDROutputGUI::on_transverter_clicked () private slot
Definition at line 622 of file limesdroutputgui.cpp.
References m_settings, LimeSDROutputSettings::m_transverterDeltaFrequency, LimeSDROutputSettings::m_transverterMode, sendSettings(), setCenterFrequencySetting(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("LimeSDRInputGUI::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     setCenterFrequencySetting(ui->centerFrequency->getValueNew());
     sendSettings();
 }
openDeviceSettingsDialog
void LimeSDROutputGUI::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 638 of file limesdroutputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), LimeSDROutputSettings::m_reverseAPIAddress, LimeSDROutputSettings::m_reverseAPIDeviceIndex, LimeSDROutputSettings::m_reverseAPIPort, m_settings, LimeSDROutputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by LimeSDROutputGUI().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void LimeSDROutputGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 121 of file limesdroutputgui.cpp.
References displaySettings(), m_settings, LimeSDROutputSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void LimeSDROutputGUI::sendSettings () private
Definition at line 436 of file limesdroutputgui.cpp.
References m_updateTimer.
Referenced by deserialize(), LimeSDROutputGUI(), on_antenna_currentIndexChanged(), on_centerFrequency_changed(), on_extClock_clicked(), on_gain_valueChanged(), on_hwInterp_currentIndexChanged(), on_lpf_changed(), on_lpFIR_changed(), on_lpFIREnable_toggled(), on_ncoEnable_toggled(), on_ncoFrequency_changed(), on_sampleRate_changed(), on_swInterp_currentIndexChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray LimeSDROutputGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 140 of file limesdroutputgui.cpp.
References m_settings, and LimeSDROutputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void LimeSDROutputGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 133 of file limesdroutputgui.cpp.
References displaySettings(), LimeSDROutputSettings::m_centerFrequency, LimeSDROutputSettings::m_ncoEnable, LimeSDROutputSettings::m_ncoFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency - (m_settings.m_ncoEnable ? m_settings.m_ncoFrequency : 0);
     displaySettings();
     sendSettings();
 }
setCenterFrequencyDisplay()
void LimeSDROutputGUI::setCenterFrequencyDisplay () private
Definition at line 410 of file limesdroutputgui.cpp.
References arg(), LimeSDROutputSettings::m_centerFrequency, LimeSDROutputSettings::m_ncoEnable, LimeSDROutputSettings::m_ncoFrequency, m_settings, and ui.
Referenced by displaySettings(), on_ncoEnable_toggled(), and on_ncoFrequency_changed().
 {
     int64_t centerFrequency = m_settings.m_centerFrequency;
     ui->centerFrequency->setToolTip(QString("Main center frequency in kHz (LO: %1 kHz)").arg(centerFrequency/1000));
     if (m_settings.m_ncoEnable) {
         centerFrequency += m_settings.m_ncoFrequency;
     }
     ui->centerFrequency->blockSignals(true);
     ui->centerFrequency->setValue(centerFrequency < 0 ? 0 : (uint64_t) centerFrequency/1000); // kHz
     ui->centerFrequency->blockSignals(false);
 }
setCenterFrequencySetting()
void LimeSDROutputGUI::setCenterFrequencySetting (uint64_t kHzValue) private
Definition at line 424 of file limesdroutputgui.cpp.
References arg(), LimeSDROutputSettings::m_centerFrequency, LimeSDROutputSettings::m_ncoEnable, LimeSDROutputSettings::m_ncoFrequency, m_settings, and ui.
Referenced by on_centerFrequency_changed(), and on_transverter_clicked().
 {
     int64_t centerFrequency = kHzValue*1000;
     if (m_settings.m_ncoEnable) {
         centerFrequency -= m_settings.m_ncoFrequency;
     }
     m_settings.m_centerFrequency = centerFrequency < 0 ? 0 : (uint64_t) centerFrequency;
     ui->centerFrequency->setToolTip(QString("Main center frequency in kHz (LO: %1 kHz)").arg(centerFrequency/1000));
 }
setName()
void LimeSDROutputGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 111 of file limesdroutputgui.cpp.
 {
     setObjectName(name);
 }
setNCODisplay()
void LimeSDROutputGUI::setNCODisplay () private
Definition at line 395 of file limesdroutputgui.cpp.
References arg(), LimeSDROutputSettings::m_devSampleRate, LimeSDROutputSettings::m_log2HardInterp, LimeSDROutputSettings::m_ncoFrequency, m_settings, and ui.
Referenced by displaySettings(), on_hwInterp_currentIndexChanged(), and on_sampleRate_changed().
 {
     int ncoHalfRange = (m_settings.m_devSampleRate * (1<<(m_settings.m_log2HardInterp)))/2;
     ui->ncoFrequency->setValueRange(
             false,
             8,
             -ncoHalfRange,
             ncoHalfRange);
     ui->ncoFrequency->blockSignals(true);
     ui->ncoFrequency->setToolTip(QString("NCO frequency shift in Hz (Range: +/- %1 kHz)").arg(ncoHalfRange/1000));
     ui->ncoFrequency->setValue(m_settings.m_ncoFrequency);
     ui->ncoFrequency->blockSignals(false);
 }
updateDACRate()
void LimeSDROutputGUI::updateDACRate () private
Definition at line 321 of file limesdroutputgui.cpp.
References arg(), LimeSDROutputSettings::m_devSampleRate, LimeSDROutputSettings::m_log2HardInterp, m_settings, and ui.
Referenced by displaySettings(), on_hwInterp_currentIndexChanged(), and on_sampleRate_changed().
 {
     uint32_t dacRate = m_settings.m_devSampleRate * (1<<m_settings.m_log2HardInterp);
     if (dacRate < 100000000) {
         ui->dacRateLabel->setText(tr("%1k").arg(QString::number(dacRate / 1000.0f, 'g', 5)));
     } else {
         ui->dacRateLabel->setText(tr("%1M").arg(QString::number(dacRate / 1000000.0f, 'g', 5)));
     }
 }
updateFrequencyLimits()
void LimeSDROutputGUI::updateFrequencyLimits () private
Definition at line 161 of file limesdroutputgui.cpp.
References LimeSDROutput::getLORange(), m_limeSDROutput, m_settings, LimeSDROutputSettings::m_transverterDeltaFrequency, LimeSDROutputSettings::m_transverterMode, and ui.
Referenced by on_transverter_clicked().
 {
     // values in kHz
     float minF, maxF;
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     m_limeSDROutput->getLORange(minF, maxF);
     qint64 minLimit = minF/1000 + deltaFrequency;
     qint64 maxLimit = maxF/1000 + deltaFrequency;
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("LimeSDROutputGUI::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void LimeSDROutputGUI::updateHardware () private slot
Definition at line 442 of file limesdroutputgui.cpp.
References LimeSDROutput::MsgConfigureLimeSDR::create(), DeviceSampleSink::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_limeSDROutput, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by LimeSDROutputGUI().
 {
     if (m_doApplySettings)
     {
         qDebug() << "LimeSDROutputGUI::updateHardware";
         LimeSDROutput::MsgConfigureLimeSDR* message = LimeSDROutput::MsgConfigureLimeSDR::create(m_settings, m_forceSettings);
         m_limeSDROutput->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void LimeSDROutputGUI::updateSampleRateAndFrequency () private
Definition at line 314 of file limesdroutputgui.cpp.
References displaySampleRate(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), and GLSpectrum::setSampleRate().
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     displaySampleRate();
 }
updateStatus
void LimeSDROutputGUI::updateStatus () private slot
Definition at line 454 of file limesdroutputgui.cpp.
References LimeSDROutput::MsgGetStreamInfo::create(), LimeSDROutput::MsgGetDeviceInfo::create(), DeviceAPI::errorMessage(), DeviceSampleSink::getInputMessageQueue(), DeviceAPI::isBuddyLeader(), DeviceUISet::m_deviceAPI, m_deviceStatusCounter, m_deviceUISet, m_lastEngineState, m_limeSDROutput, m_statusCounter, MessageQueue::push(), DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by LimeSDROutputGUI().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
     if (m_statusCounter < 1)
     {
         m_statusCounter++;
     }
     else
     {
         LimeSDROutput::MsgGetStreamInfo* message = LimeSDROutput::MsgGetStreamInfo::create();
         m_limeSDROutput->getInputMessageQueue()->push(message);
         m_statusCounter = 0;
     }
     if (m_deviceStatusCounter < 10)
     {
         m_deviceStatusCounter++;
     }
     else
     {
         if (m_deviceUISet->m_deviceAPI->isBuddyLeader())
         {
             LimeSDROutput::MsgGetDeviceInfo* message = LimeSDROutput::MsgGetDeviceInfo::create();
             m_limeSDROutput->getInputMessageQueue()->push(message);
         }
         m_deviceStatusCounter = 0;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 LimeSDROutputGUI::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 65 of file limesdroutputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceStatusCounter
int LimeSDROutputGUI::m_deviceStatusCounter private
Definition at line 70 of file limesdroutputgui.h.
Referenced by updateStatus().
m_deviceUISet
DeviceUISet* LimeSDROutputGUI::m_deviceUISet private
Definition at line 58 of file limesdroutputgui.h.
Referenced by LimeSDROutputGUI(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool LimeSDROutputGUI::m_doApplySettings private
Definition at line 67 of file limesdroutputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_forceSettings
bool LimeSDROutputGUI::m_forceSettings private
Definition at line 68 of file limesdroutputgui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue LimeSDROutputGUI::m_inputMessageQueue private
Definition at line 71 of file limesdroutputgui.h.
Referenced by handleInputMessages(), and LimeSDROutputGUI().
m_lastEngineState
int LimeSDROutputGUI::m_lastEngineState private
Definition at line 66 of file limesdroutputgui.h.
Referenced by updateStatus().
m_limeSDROutput
LimeSDROutput* LimeSDROutputGUI::m_limeSDROutput private
Same object as above but gives easy access to LimeSDROutput methods and attributes that are used intensively.
Definition at line 59 of file limesdroutputgui.h.
Referenced by displaySampleRate(), LimeSDROutputGUI(), on_startStop_toggled(), updateFrequencyLimits(), updateHardware(), and updateStatus().
m_sampleRate
int LimeSDROutputGUI::m_sampleRate private
Definition at line 64 of file limesdroutputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateMode
bool LimeSDROutputGUI::m_sampleRateMode private
true: device, false: base band sample rate update mode
Definition at line 61 of file limesdroutputgui.h.
Referenced by displaySampleRate(), on_sampleRate_changed(), on_sampleRateMode_toggled(), and on_swInterp_currentIndexChanged().
m_settings
LimeSDROutputSettings LimeSDROutputGUI::m_settings private
Definition at line 60 of file limesdroutputgui.h.
Referenced by deserialize(), displaySampleRate(), displaySettings(), getCenterFrequency(), handleInputMessages(), handleMessage(), on_antenna_currentIndexChanged(), on_extClock_clicked(), on_gain_valueChanged(), on_hwInterp_currentIndexChanged(), on_lpf_changed(), on_lpFIR_changed(), on_lpFIREnable_toggled(), on_ncoEnable_toggled(), on_ncoFrequency_changed(), on_sampleRate_changed(), on_swInterp_currentIndexChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), setCenterFrequencyDisplay(), setCenterFrequencySetting(), setNCODisplay(), updateDACRate(), updateFrequencyLimits(), and updateHardware().
m_statusCounter
int LimeSDROutputGUI::m_statusCounter private
Definition at line 69 of file limesdroutputgui.h.
Referenced by updateStatus().
m_statusTimer
QTimer LimeSDROutputGUI::m_statusTimer private
Definition at line 63 of file limesdroutputgui.h.
Referenced by LimeSDROutputGUI().
m_updateTimer
QTimer LimeSDROutputGUI::m_updateTimer private
Definition at line 62 of file limesdroutputgui.h.
Referenced by LimeSDROutputGUI(), sendSettings(), and updateHardware().
ui
Ui::LimeSDROutputGUI* LimeSDROutputGUI::ui private
Definition at line 56 of file limesdroutputgui.h.
Referenced by displaySampleRate(), displaySettings(), handleInputMessages(), handleMessage(), LimeSDROutputGUI(), on_extClock_clicked(), on_gain_valueChanged(), on_swInterp_currentIndexChanged(), on_transverter_clicked(), setCenterFrequencyDisplay(), setCenterFrequencySetting(), setNCODisplay(), updateDACRate(), updateFrequencyLimits(), updateStatus(), and ~LimeSDROutputGUI().
The documentation for this class was generated from the following files:
plugins/samplesink/limesdroutput/limesdroutputgui.h
plugins/samplesink/limesdroutput/limesdroutputgui.cpp