SDRAngel: PlutoSDRInputPlugin Class Reference
PlutoSDRInputPlugin Class Reference
#include <plutosdrinputplugin.h>
Public Member Functions
PlutoSDRInputPlugin (QObject *parent=NULL)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "PlutoSDR"
static const QString m_deviceTypeID = PLUTOSDR_DEVICE_TYPE_ID
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 28 of file plutosdrinputplugin.h.
Constructor & Destructor Documentation
PlutoSDRInputPlugin()
PlutoSDRInputPlugin::PlutoSDRInputPlugin (QObject * parent = NULL) explicit
Definition at line 44 of file plutosdrinputplugin.cpp.
                                                         :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSourcePluginInstance()
DeviceSampleSource * PlutoSDRInputPlugin::createSampleSourcePluginInstance (const QString & sourceId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 121 of file plutosdrinputplugin.cpp.
References m_deviceTypeID.
 {
     if (sourceId == m_deviceTypeID)
     {
         PlutoSDRInput* input = new PlutoSDRInput(deviceAPI);
         return input;
     }
     else
     {
         return 0;
     }
 }
createSampleSourcePluginInstanceGUI()
PluginInstanceGUI * PlutoSDRInputPlugin::createSampleSourcePluginInstanceGUI (const QString & sourceId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 103 of file plutosdrinputplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSources().
 {
     if(sourceId == m_deviceTypeID)
     {
         PlutoSDRInputGui* gui = new PlutoSDRInputGui(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSources()
PluginInterface::SamplingDevices PlutoSDRInputPlugin::enumSampleSources () virtual
Reimplemented from PluginInterface.
Definition at line 60 of file plutosdrinputplugin.cpp.
References arg(), createSampleSourcePluginInstanceGUI(), DevicePlutoSDR::getSerials(), i, DevicePlutoSDR::instance(), m_deviceTypeID, m_hardwareID, PluginInterface::SamplingDevice::PhysicalDevice, DevicePlutoSDR::scan(), and PluginInterface::SamplingDevice::StreamSingleRx.
 {
     DevicePlutoSDR::instance().scan();
     std::vector<std::string> serials;
     DevicePlutoSDR::instance().getSerials(serials);
     std::vector<std::string>::const_iterator it = serials.begin();
     int i;
     SamplingDevices result;
     for (i = 0; it != serials.end(); ++it, ++i)
     {
         QString serial_str = QString::fromLocal8Bit(it->c_str());
         QString displayedName(QString("PlutoSDR[%1] %2").arg(i).arg(serial_str));
         result.append(SamplingDevice(displayedName,
                 m_hardwareID,
                 m_deviceTypeID,
                 serial_str,
                 i,
                 PluginInterface::SamplingDevice::PhysicalDevice,
                 PluginInterface::SamplingDevice::StreamSingleRx,
                 1,
                 0));
         qDebug("PlutoSDRInputPlugin::enumSampleSources: enumerated PlutoSDR device #%d", i);
     }
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & PlutoSDRInputPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 49 of file plutosdrinputplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void PlutoSDRInputPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 54 of file plutosdrinputplugin.cpp.
References DevicePlutoSDR::instance(), m_deviceTypeID, and PluginAPI::registerSampleSource().
 {
     pluginAPI->registerSampleSource(m_deviceTypeID, this);
     DevicePlutoSDR::instance(); // create singleton
 }
Member Data Documentation
m_deviceTypeID
const QString PlutoSDRInputPlugin::m_deviceTypeID = PLUTOSDR_DEVICE_TYPE_ID static
Definition at line 47 of file plutosdrinputplugin.h.
Referenced by createSampleSourcePluginInstance(), createSampleSourcePluginInstanceGUI(), enumSampleSources(), and initPlugin().
m_hardwareID
const QString PlutoSDRInputPlugin::m_hardwareID = "PlutoSDR" static
Definition at line 46 of file plutosdrinputplugin.h.
Referenced by enumSampleSources().
m_pluginDescriptor
const PluginDescriptor PlutoSDRInputPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("PlutoSDR Input"),
    QString("4.11.3"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 50 of file plutosdrinputplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesource/plutosdrinput/plutosdrinputplugin.h
plugins/samplesource/plutosdrinput/plutosdrinputplugin.cpp