SDRAngel: RemoteInput Class Reference
RemoteInput Class Reference
#include <remoteinput.h>
Classes
class MsgConfigureRemoteInput
class MsgConfigureRemoteInputTiming
class MsgFileRecord
class MsgReportRemoteInputAcquisition
class MsgReportRemoteInputStreamData
class MsgReportRemoteInputStreamTiming
class MsgStartStop
Public Member Functions
RemoteInput (DeviceAPI *deviceAPI)
virtual ~RemoteInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
std::time_t getStartingTimeStamp () const
bool isStreaming () const
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applySettings (const RemoteInputSettings &settings, bool force=false)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const RemoteInputSettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const RemoteInputSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
RemoteInputSettings m_settings
RemoteInputUDPHandler * m_remoteInputUDPHandler
QString m_remoteAddress
QString m_deviceDescription
std::time_t m_startingTimeStamp
FileRecord * m_fileSink
File sink to record device I/Q output.
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 40 of file remoteinput.h.
Constructor & Destructor Documentation
RemoteInput()
RemoteInput::RemoteInput (DeviceAPI * deviceAPI)
Definition at line 47 of file remoteinput.cpp.
References arg().
Referenced by RemoteInput::MsgStartStop::MsgStartStop().
                                              :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_remoteInputUDPHandler(0),
     m_deviceDescription(),
     m_startingTimeStamp(0)
 {
     m_sampleFifo.setSize(96000 * 4);
     m_remoteInputUDPHandler = new RemoteInputUDPHandler(&m_sampleFifo, m_deviceAPI);
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~RemoteInput()
RemoteInput::~RemoteInput () virtual
Definition at line 65 of file remoteinput.cpp.
References m_deviceAPI, m_fileSink, m_networkManager, m_remoteInputUDPHandler, networkManagerFinished(), DeviceAPI::removeAncillarySink(), and stop().
Referenced by RemoteInput::MsgStartStop::MsgStartStop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     stop();
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
     delete m_remoteInputUDPHandler;
 }
Member Function Documentation
applySettings()
void RemoteInput::applySettings (const RemoteInputSettings & settings, bool force = false) private
Definition at line 226 of file remoteinput.cpp.
References DeviceAPI::configureCorrections(), RemoteInputUDPHandler::configureUDPLink(), RemoteInputUDPHandler::getRemoteAddress(), RemoteInputSettings::m_apiAddress, RemoteInputSettings::m_apiPort, RemoteInputSettings::m_dataAddress, RemoteInputSettings::m_dataPort, RemoteInputSettings::m_dcBlock, m_deviceAPI, RemoteInputSettings::m_fileRecordName, RemoteInputSettings::m_iqCorrection, m_mutex, m_remoteAddress, m_remoteInputUDPHandler, RemoteInputSettings::m_reverseAPIAddress, RemoteInputSettings::m_reverseAPIDeviceIndex, RemoteInputSettings::m_reverseAPIPort, m_settings, RemoteInputSettings::m_useReverseAPI, and webapiReverseSendSettings().
Referenced by handleMessage(), and init().
 {
     QMutexLocker mutexLocker(&m_mutex);
     std::ostringstream os;
     QString remoteAddress;
     m_remoteInputUDPHandler->getRemoteAddress(remoteAddress);
     QList<QString> reverseAPIKeys;
     if ((m_settings.m_dcBlock != settings.m_dcBlock) || force) {
         reverseAPIKeys.append("dcBlock");
     }
     if ((m_settings.m_iqCorrection != settings.m_iqCorrection) || force) {
         reverseAPIKeys.append("iqCorrection");
     }
     if ((m_settings.m_dataAddress != settings.m_dataAddress) || force) {
         reverseAPIKeys.append("dataAddress");
     }
     if ((m_settings.m_dataPort != settings.m_dataPort) || force) {
         reverseAPIKeys.append("dataPort");
     }
     if ((m_settings.m_apiAddress != settings.m_apiAddress) || force) {
         reverseAPIKeys.append("apiAddress");
     }
     if ((m_settings.m_apiPort != settings.m_apiPort) || force) {
         reverseAPIKeys.append("apiPort");
     }
     if ((m_settings.m_fileRecordName != settings.m_fileRecordName) || force) {
         reverseAPIKeys.append("fileRecordName");
     }
     if ((m_settings.m_dcBlock != settings.m_dcBlock) || (m_settings.m_iqCorrection != settings.m_iqCorrection) || force)
     {
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqCorrection);
         qDebug("RemoteInput::applySettings: corrections: DC block: %s IQ imbalance: %s",
                 settings.m_dcBlock ? "true" : "false",
                 settings.m_iqCorrection ? "true" : "false");
     }
     m_remoteInputUDPHandler->configureUDPLink(settings.m_dataAddress, settings.m_dataPort);
     m_remoteInputUDPHandler->getRemoteAddress(remoteAddress);
     mutexLocker.unlock();
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     m_remoteAddress = remoteAddress;
     qDebug() << "RemoteInput::applySettings: "
             << " m_dataAddress: " << m_settings.m_dataAddress
             << " m_dataPort: " << m_settings.m_dataPort
             << " m_apiAddress: " << m_settings.m_apiAddress
             << " m_apiPort: " << m_settings.m_apiPort
             << " m_remoteAddress: " << m_remoteAddress;
 }
deserialize()
bool RemoteInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 103 of file remoteinput.cpp.
References RemoteInput::MsgConfigureRemoteInput::create(), RemoteInputSettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and RemoteInputSettings::resetToDefaults().
Referenced by RemoteInput::MsgStartStop::MsgStartStop().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureRemoteInput* message = MsgConfigureRemoteInput::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureRemoteInput* messageToGUI = MsgConfigureRemoteInput::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void RemoteInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 75 of file remoteinput.cpp.
Referenced by RemoteInput::MsgStartStop::MsgStartStop().
 {
     delete this;
 }
getCenterFrequency()
quint64 RemoteInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 141 of file remoteinput.cpp.
References RemoteInputUDPHandler::getCenterFrequency(), and m_remoteInputUDPHandler.
Referenced by setSampleRate().
 {
     return m_remoteInputUDPHandler->getCenterFrequency();
 }
getDeviceDescription()
const QString & RemoteInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 131 of file remoteinput.cpp.
References m_deviceDescription.
Referenced by RemoteInput::MsgStartStop::MsgStartStop().
 {
     return m_deviceDescription;
 }
getSampleRate()
int RemoteInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 136 of file remoteinput.cpp.
References RemoteInputUDPHandler::getSampleRate(), and m_remoteInputUDPHandler.
Referenced by RemoteInput::MsgStartStop::MsgStartStop().
 {
     return m_remoteInputUDPHandler->getSampleRate();
 }
getStartingTimeStamp()
std::time_t RemoteInput::getStartingTimeStamp () const
Definition at line 151 of file remoteinput.cpp.
References m_startingTimeStamp.
Referenced by setSampleRate().
 {
     return m_startingTimeStamp;
 }
handleMessage()
bool RemoteInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 161 of file remoteinput.cpp.
References applySettings(), FileRecord::genUniqueFileName(), DeviceAPI::getDeviceUID(), RemoteInput::MsgConfigureRemoteInput::getForce(), Message::getIdentifier(), RemoteInput::MsgConfigureRemoteInput::getSettings(), RemoteInput::MsgFileRecord::getStartStop(), RemoteInput::MsgStartStop::getStartStop(), FileRecord::handleMessage(), DeviceAPI::initDeviceEngine(), m_deviceAPI, RemoteInputSettings::m_fileRecordName, m_fileSink, m_settings, RemoteInputSettings::m_useReverseAPI, Message::match(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (DSPSignalNotification::match(message))
     {
         DSPSignalNotification& notif = (DSPSignalNotification&) message;
         return m_fileSink->handleMessage(notif); // forward to file sink
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "RemoteInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "RemoteInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else if (MsgConfigureRemoteInput::match(message))
     {
         qDebug() << "RemoteInput::handleMessage:" << message.getIdentifier();
         MsgConfigureRemoteInput& conf = (MsgConfigureRemoteInput&) message;
         applySettings(conf.getSettings(), conf.getForce());
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void RemoteInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 80 of file remoteinput.cpp.
References applySettings(), and m_settings.
Referenced by RemoteInput::MsgStartStop::MsgStartStop().
 {
     applySettings(m_settings, true);
 }
isStreaming()
bool RemoteInput::isStreaming () const
Definition at line 156 of file remoteinput.cpp.
References RemoteInputUDPHandler::isStreaming(), and m_remoteInputUDPHandler.
Referenced by setSampleRate(), and RemoteInputGui::updateStatus().
 {
     return m_remoteInputUDPHandler->isStreaming();
 }
networkManagerFinished
void RemoteInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 514 of file remoteinput.cpp.
Referenced by ~RemoteInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "RemoteInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("RemoteInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
serialize()
QByteArray RemoteInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 98 of file remoteinput.cpp.
References m_settings, and RemoteInputSettings::serialize().
Referenced by RemoteInput::MsgStartStop::MsgStartStop().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void RemoteInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 146 of file remoteinput.cpp.
Referenced by setSampleRate().
 {
     (void) centerFrequency;
 }
setMessageQueueToGUI()
void RemoteInput::setMessageQueueToGUI (MessageQueue * queue) virtual
Implements DeviceSampleSource.
Definition at line 125 of file remoteinput.cpp.
References DeviceSampleSource::m_guiMessageQueue, m_remoteInputUDPHandler, and RemoteInputUDPHandler::setMessageQueueToGUI().
Referenced by RemoteInput::MsgStartStop::MsgStartStop(), and RemoteInputGui::RemoteInputGui().
 {
     m_guiMessageQueue = queue;
     m_remoteInputUDPHandler->setMessageQueueToGUI(queue);
 }
setSampleRate()
virtual void RemoteInput::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 285 of file remoteinput.h.
References getCenterFrequency(), getStartingTimeStamp(), handleMessage(), isStreaming(), setCenterFrequency(), webapiReportGet(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
start()
bool RemoteInput::start () virtual
Implements DeviceSampleSource.
Definition at line 85 of file remoteinput.cpp.
References m_remoteInputUDPHandler, and RemoteInputUDPHandler::start().
Referenced by RemoteInput::MsgStartStop::MsgStartStop().
 {
     qDebug() << "RemoteInput::start";
     m_remoteInputUDPHandler->start();
     return true;
 }
stop()
void RemoteInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 92 of file remoteinput.cpp.
References m_remoteInputUDPHandler, and RemoteInputUDPHandler::stop().
Referenced by RemoteInput::MsgStartStop::MsgStartStop(), and ~RemoteInput().
 {
     qDebug() << "RemoteInput::stop";
     m_remoteInputUDPHandler->stop();
 }
webapiFormatDeviceReport()
void RemoteInput::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 422 of file remoteinput.cpp.
References RemoteInputUDPHandler::getBufferGauge(), RemoteInputUDPHandler::getCenterFrequency(), RemoteInputUDPHandler::getMaxNbRecovery(), RemoteInputUDPHandler::getMinNbBlocks(), SWGSDRangel::SWGDeviceReport::getRemoteInputReport(), RemoteInputUDPHandler::getSampleRate(), RemoteInputUDPHandler::getTVmSec(), m_remoteInputUDPHandler, SWGSDRangel::SWGRemoteInputReport::setBufferRwBalance(), SWGSDRangel::SWGRemoteInputReport::setCenterFrequency(), SWGSDRangel::SWGRemoteInputReport::setMaxNbRecovery(), SWGSDRangel::SWGRemoteInputReport::setMinNbBlocks(), SWGSDRangel::SWGRemoteInputReport::setRemoteTimestamp(), and SWGSDRangel::SWGRemoteInputReport::setSampleRate().
Referenced by webapiReportGet().
 {
     response.getRemoteInputReport()->setCenterFrequency(m_remoteInputUDPHandler->getCenterFrequency());
     response.getRemoteInputReport()->setSampleRate(m_remoteInputUDPHandler->getSampleRate());
     response.getRemoteInputReport()->setBufferRwBalance(m_remoteInputUDPHandler->getBufferGauge());
     QDateTime dt = QDateTime::fromMSecsSinceEpoch(m_remoteInputUDPHandler->getTVmSec());
     response.getRemoteInputReport()->setRemoteTimestamp(new QString(dt.toString("yyyy-MM-dd  HH:mm:ss.zzz")));
     response.getRemoteInputReport()->setMinNbBlocks(m_remoteInputUDPHandler->getMinNbBlocks());
     response.getRemoteInputReport()->setMaxNbRecovery(m_remoteInputUDPHandler->getMaxNbRecovery());
 }
webapiFormatDeviceSettings()
void RemoteInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const RemoteInputSettings & settings) private
Definition at line 384 of file remoteinput.cpp.
References SWGSDRangel::SWGRemoteInputSettings::getFileRecordName(), SWGSDRangel::SWGDeviceSettings::getRemoteInputSettings(), SWGSDRangel::SWGRemoteInputSettings::getReverseApiAddress(), RemoteInputSettings::m_apiAddress, RemoteInputSettings::m_apiPort, RemoteInputSettings::m_dataAddress, RemoteInputSettings::m_dataPort, RemoteInputSettings::m_dcBlock, RemoteInputSettings::m_fileRecordName, RemoteInputSettings::m_iqCorrection, RemoteInputSettings::m_reverseAPIAddress, RemoteInputSettings::m_reverseAPIDeviceIndex, RemoteInputSettings::m_reverseAPIPort, RemoteInputSettings::m_useReverseAPI, SWGSDRangel::SWGRemoteInputSettings::setApiAddress(), SWGSDRangel::SWGRemoteInputSettings::setApiPort(), SWGSDRangel::SWGRemoteInputSettings::setDataAddress(), SWGSDRangel::SWGRemoteInputSettings::setDataPort(), SWGSDRangel::SWGRemoteInputSettings::setDcBlock(), SWGSDRangel::SWGRemoteInputSettings::setFileRecordName(), SWGSDRangel::SWGRemoteInputSettings::setIqCorrection(), SWGSDRangel::SWGRemoteInputSettings::setReverseApiAddress(), SWGSDRangel::SWGRemoteInputSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGRemoteInputSettings::setReverseApiPort(), and SWGSDRangel::SWGRemoteInputSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getRemoteInputSettings()->setApiAddress(new QString(settings.m_apiAddress));
     response.getRemoteInputSettings()->setApiPort(settings.m_apiPort);
     response.getRemoteInputSettings()->setDataAddress(new QString(settings.m_dataAddress));
     response.getRemoteInputSettings()->setDataPort(settings.m_dataPort);
     response.getRemoteInputSettings()->setDcBlock(settings.m_dcBlock ? 1 : 0);
     response.getRemoteInputSettings()->setIqCorrection(settings.m_iqCorrection);
     if (response.getRemoteInputSettings()->getFileRecordName()) {
         *response.getRemoteInputSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getRemoteInputSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getRemoteInputSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getRemoteInputSettings()->getReverseApiAddress()) {
         *response.getRemoteInputSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getRemoteInputSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getRemoteInputSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getRemoteInputSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int RemoteInput::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 411 of file remoteinput.cpp.
References SWGSDRangel::SWGDeviceReport::getRemoteInputReport(), SWGSDRangel::SWGRemoteInputReport::init(), SWGSDRangel::SWGDeviceReport::setRemoteInputReport(), and webapiFormatDeviceReport().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setRemoteInputReport(new SWGSDRangel::SWGRemoteInputReport());
     response.getRemoteInputReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void RemoteInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const RemoteInputSettings & settings, bool force) private
Definition at line 435 of file remoteinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getRemoteInputSettings(), RemoteInputSettings::m_apiAddress, RemoteInputSettings::m_apiPort, RemoteInputSettings::m_dataAddress, RemoteInputSettings::m_dataPort, RemoteInputSettings::m_dcBlock, m_deviceAPI, RemoteInputSettings::m_fileRecordName, RemoteInputSettings::m_iqCorrection, m_networkManager, m_networkRequest, RemoteInputSettings::m_reverseAPIAddress, RemoteInputSettings::m_reverseAPIDeviceIndex, RemoteInputSettings::m_reverseAPIPort, SWGSDRangel::SWGRemoteInputSettings::setApiAddress(), SWGSDRangel::SWGRemoteInputSettings::setApiPort(), SWGSDRangel::SWGRemoteInputSettings::setDataAddress(), SWGSDRangel::SWGRemoteInputSettings::setDataPort(), SWGSDRangel::SWGRemoteInputSettings::setDcBlock(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGRemoteInputSettings::setFileRecordName(), SWGSDRangel::SWGRemoteInputSettings::setIqCorrection(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), and SWGSDRangel::SWGDeviceSettings::setRemoteInputSettings().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("RemoteInput"));
     swgDeviceSettings->setRemoteInputSettings(new SWGSDRangel::SWGRemoteInputSettings());
     SWGSDRangel::SWGRemoteInputSettings *swgRemoteInputSettings = swgDeviceSettings->getRemoteInputSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("apiAddress") || force) {
         swgRemoteInputSettings->setApiAddress(new QString(settings.m_apiAddress));
     }
     if (deviceSettingsKeys.contains("apiPort") || force) {
         swgRemoteInputSettings->setApiPort(settings.m_apiPort);
     }
     if (deviceSettingsKeys.contains("dataAddress") || force) {
         swgRemoteInputSettings->setDataAddress(new QString(settings.m_dataAddress));
     }
     if (deviceSettingsKeys.contains("dataPort") || force) {
         swgRemoteInputSettings->setDataPort(settings.m_dataPort);
     }
     if (deviceSettingsKeys.contains("dcBlock") || force) {
         swgRemoteInputSettings->setDcBlock(settings.m_dcBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("iqCorrection") || force) {
         swgRemoteInputSettings->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgRemoteInputSettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void RemoteInput::webapiReverseSendStartStop (bool start) private
Definition at line 486 of file remoteinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, RemoteInputSettings::m_reverseAPIAddress, RemoteInputSettings::m_reverseAPIDeviceIndex, RemoteInputSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("RemoteInput"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int RemoteInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 298 of file remoteinput.cpp.
References RemoteInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int RemoteInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 289 of file remoteinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int RemoteInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 317 of file remoteinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getRemoteInputSettings(), SWGSDRangel::SWGRemoteInputSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setRemoteInputSettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setRemoteInputSettings(new SWGSDRangel::SWGRemoteInputSettings());
     response.getRemoteInputSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int RemoteInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 328 of file remoteinput.cpp.
References RemoteInput::MsgConfigureRemoteInput::create(), SWGSDRangel::SWGRemoteInputSettings::getApiAddress(), SWGSDRangel::SWGRemoteInputSettings::getApiPort(), SWGSDRangel::SWGRemoteInputSettings::getDataAddress(), SWGSDRangel::SWGRemoteInputSettings::getDataPort(), SWGSDRangel::SWGRemoteInputSettings::getDcBlock(), SWGSDRangel::SWGRemoteInputSettings::getFileRecordName(), SWGSDRangel::SWGRemoteInputSettings::getIqCorrection(), SWGSDRangel::SWGDeviceSettings::getRemoteInputSettings(), SWGSDRangel::SWGRemoteInputSettings::getReverseApiAddress(), SWGSDRangel::SWGRemoteInputSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGRemoteInputSettings::getReverseApiPort(), SWGSDRangel::SWGRemoteInputSettings::getUseReverseApi(), RemoteInputSettings::m_apiAddress, RemoteInputSettings::m_apiPort, RemoteInputSettings::m_dataAddress, RemoteInputSettings::m_dataPort, RemoteInputSettings::m_dcBlock, RemoteInputSettings::m_fileRecordName, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, RemoteInputSettings::m_iqCorrection, RemoteInputSettings::m_reverseAPIAddress, RemoteInputSettings::m_reverseAPIDeviceIndex, RemoteInputSettings::m_reverseAPIPort, m_settings, RemoteInputSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     RemoteInputSettings settings = m_settings;
     if (deviceSettingsKeys.contains("apiAddress")) {
         settings.m_apiAddress = *response.getRemoteInputSettings()->getApiAddress();
     }
     if (deviceSettingsKeys.contains("apiPort")) {
         settings.m_apiPort = response.getRemoteInputSettings()->getApiPort();
     }
     if (deviceSettingsKeys.contains("dataAddress")) {
         settings.m_dataAddress = *response.getRemoteInputSettings()->getDataAddress();
     }
     if (deviceSettingsKeys.contains("dataPort")) {
         settings.m_dataPort = response.getRemoteInputSettings()->getDataPort();
     }
     if (deviceSettingsKeys.contains("dcBlock")) {
         settings.m_dcBlock = response.getRemoteInputSettings()->getDcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("iqCorrection")) {
         settings.m_iqCorrection = response.getRemoteInputSettings()->getIqCorrection() != 0;
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getRemoteInputSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getRemoteInputSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getRemoteInputSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getRemoteInputSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getRemoteInputSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureRemoteInput *msg = MsgConfigureRemoteInput::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureRemoteInput *msgToGUI = MsgConfigureRemoteInput::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_deviceAPI
DeviceAPI* RemoteInput::m_deviceAPI private
Definition at line 317 of file remoteinput.h.
Referenced by applySettings(), handleMessage(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~RemoteInput().
m_deviceDescription
QString RemoteInput::m_deviceDescription private
Definition at line 322 of file remoteinput.h.
Referenced by getDeviceDescription().
m_fileSink
FileRecord* RemoteInput::m_fileSink private
File sink to record device I/Q output.
Definition at line 324 of file remoteinput.h.
Referenced by handleMessage(), and ~RemoteInput().
m_mutex
QMutex RemoteInput::m_mutex private
Definition at line 318 of file remoteinput.h.
Referenced by applySettings().
m_networkManager
QNetworkAccessManager* RemoteInput::m_networkManager private
Definition at line 325 of file remoteinput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~RemoteInput().
m_networkRequest
QNetworkRequest RemoteInput::m_networkRequest private
Definition at line 326 of file remoteinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_remoteAddress
QString RemoteInput::m_remoteAddress private
Definition at line 321 of file remoteinput.h.
Referenced by applySettings().
m_remoteInputUDPHandler
RemoteInputUDPHandler* RemoteInput::m_remoteInputUDPHandler private
Definition at line 320 of file remoteinput.h.
Referenced by applySettings(), getCenterFrequency(), getSampleRate(), isStreaming(), setMessageQueueToGUI(), start(), stop(), webapiFormatDeviceReport(), and ~RemoteInput().
m_settings
RemoteInputSettings RemoteInput::m_settings private
Definition at line 319 of file remoteinput.h.
Referenced by applySettings(), deserialize(), handleMessage(), init(), serialize(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_startingTimeStamp
std::time_t RemoteInput::m_startingTimeStamp private
Definition at line 323 of file remoteinput.h.
Referenced by getStartingTimeStamp().
The documentation for this class was generated from the following files:
plugins/samplesource/remoteinput/remoteinput.h
plugins/samplesource/remoteinput/remoteinput.cpp