SDRAngel: SampleSourceFifo Class Reference
SampleSourceFifo Class Reference
#include <samplesourcefifo.h>
Inherits QObject.
Signals
void dataWrite (int nbSamples)
void dataRead (int nbSamples)
Public Member Functions
SampleSourceFifo (uint32_t size, QObject *parent=nullptr)
SampleSourceFifo (const SampleSourceFifo &other)
~SampleSourceFifo ()
void resize (uint32_t size)
uint32_t size () const
void init ()
void readAdvance (SampleVector::iterator &readUntil, unsigned int nbSamples)
void getReadIterator (SampleVector::iterator &readUntil)
get iterator past the last sample of a read advance operation (i.e. current read iterator)
void getWriteIterator (SampleVector::iterator &writeAt)
get iterator to current item for update - write phase 1
void bumpIndex (SampleVector::iterator &writeAt)
copy current item to second buffer and bump write index - write phase 2
int getIteratorOffset (const SampleVector::iterator &iterator)
void setIteratorFromOffset (SampleVector::iterator &iterator, int offset)
void write (const Sample &sample)
write directly - phase 1 + phase 2
float getRWBalance () const
Private Attributes
uint32_t m_size
SampleVector m_data
uint32_t m_iw
uint32_t m_ir
bool m_init
QMutex m_mutex
Detailed Description
Definition at line 28 of file samplesourcefifo.h.
Constructor & Destructor Documentation
SampleSourceFifo() [1/2]
SampleSourceFifo::SampleSourceFifo (uint32_t size, QObject * parent = nullptr)
Definition at line 22 of file samplesourcefifo.cpp.
References init(), m_data, and m_size.
                                                                  :
     QObject(parent),
     m_size(size),
     m_init(false)
 {
     m_data.resize(2*m_size);
     init();
 }
SampleSourceFifo() [2/2]
SampleSourceFifo::SampleSourceFifo (const SampleSourceFifo & other)
Definition at line 31 of file samplesourcefifo.cpp.
References init().
                                                                 :
     QObject(other.parent()),
     m_size(other.m_size),
     m_data(other.m_data)
 {
     init();
 }
~SampleSourceFifo()
SampleSourceFifo::~SampleSourceFifo ()
Definition at line 39 of file samplesourcefifo.cpp.
 {}
Member Function Documentation
bumpIndex()
void SampleSourceFifo::bumpIndex (SampleVector::iterator & writeAt)
copy current item to second buffer and bump write index - write phase 2
Definition at line 92 of file samplesourcefifo.cpp.
References m_data, m_iw, and m_size.
Referenced by BasebandSampleSource::feed(), BasebandSampleSource::handleWriteToFifo(), and DSPDeviceSinkEngine::work().
 {
     m_data[m_iw+m_size] = m_data[m_iw];
     {
 //        QMutexLocker mutexLocker(&m_mutex);
         m_iw = (m_iw+1) % m_size;
     }
     writeAt = m_data.begin() + m_iw;
 }
dataRead
void SampleSourceFifo::dataRead (int nbSamples) signal
Referenced by readAdvance().
dataWrite
void SampleSourceFifo::dataWrite (int nbSamples) signal
Referenced by readAdvance().
getIteratorOffset()
int SampleSourceFifo::getIteratorOffset (const SampleVector::iterator & iterator)
Definition at line 104 of file samplesourcefifo.cpp.
References m_data.
Referenced by LocalSourceThread::pullSamples().
 {
     return iterator - m_data.begin();
 }
getReadIterator()
void SampleSourceFifo::getReadIterator (SampleVector::iterator & readUntil)
get iterator past the last sample of a read advance operation (i.e. current read iterator)
Definition at line 82 of file samplesourcefifo.cpp.
References m_data, m_ir, and m_size.
Referenced by DSPDeviceSinkEngine::handleForwardToSpectrumSink(), and DSPDeviceMIMOEngine::handleForwardToSpectrumSink().
 {
     readUntil = m_data.begin() + m_size + m_ir;
 }
getRWBalance()
float SampleSourceFifo::getRWBalance () const inline
returns ratio of off center over buffer size with sign: negative read lags and positive read leads
Definition at line 51 of file samplesourcefifo.h.
Referenced by XTRXOutputThread::callback(), BladeRF2OutputThread::callbackSO(), XTRXOutputThread::callbackSO(), SoapySDROutputThread::callbackSO12(), SoapySDROutputThread::callbackSO16(), SoapySDROutputThread::callbackSO8(), SoapySDROutputThread::callbackSOIF(), and RemoteOutput::webapiFormatDeviceReport().
     {
         int delta;
         if (m_iw > m_ir) {
             delta = (m_size/2) - (m_iw - m_ir);
         } else {
             delta = (m_ir - m_iw) - (m_size/2);
         }
         return delta / (float) m_size;
     }
getWriteIterator()
void SampleSourceFifo::getWriteIterator (SampleVector::iterator & writeAt)
get iterator to current item for update - write phase 1
Definition at line 87 of file samplesourcefifo.cpp.
References m_data, and m_iw.
Referenced by BasebandSampleSource::feed(), BasebandSampleSource::handleWriteToFifo(), and DSPDeviceSinkEngine::work().
 {
     writeAt = m_data.begin() + m_iw;
 }
init()
void SampleSourceFifo::init ()
Definition at line 51 of file samplesourcefifo.cpp.
References m_data, m_init, m_ir, m_iw, and m_size.
Referenced by resize(), and SampleSourceFifo().
 {
     static Sample zero = {0,0};
     std::fill(m_data.begin(), m_data.end(), zero);
     m_ir = 0;
     m_iw = m_size/2;
     m_init = true;
 }
readAdvance()
void SampleSourceFifo::readAdvance (SampleVector::iterator & readUntil, unsigned int nbSamples)
advance read pointer for the given length and activate R/W signals
Definition at line 60 of file samplesourcefifo.cpp.
References dataRead(), dataWrite(), m_data, m_ir, and m_size.
Referenced by Bladerf1OutputThread::callback(), HackRFOutputThread::callback(), LimeSDROutputThread::callback(), XTRXOutputThread::callback(), BladeRF2OutputThread::callbackSO(), XTRXOutputThread::callbackSO(), SoapySDROutputThread::callbackSO12(), SoapySDROutputThread::callbackSO16(), SoapySDROutputThread::callbackSO8(), SoapySDROutputThread::callbackSOIF(), PlutoSDROutputThread::convert(), LocalSourceThread::pullSamples(), FileSinkThread::tick(), and RemoteOutputThread::tick().
 {
 //    QMutexLocker mutexLocker(&m_mutex);
     assert(nbSamples <= m_size/2);
     emit dataWrite(nbSamples);
     m_ir = (m_ir + nbSamples) % m_size;
     readUntil =  m_data.begin() + m_size + m_ir;
     emit dataRead(nbSamples);
 }
resize()
void SampleSourceFifo::resize (uint32_t size)
Definition at line 42 of file samplesourcefifo.cpp.
References init(), m_data, m_size, and size().
Referenced by PlutoSDROutput::applySettings(), Bladerf1Output::applySettings(), HackRFOutput::applySettings(), BladeRF2Output::applySettings(), SoapySDROutput::applySettings(), LimeSDROutput::applySettings(), LocalSource::handleMessage(), PlutoSDROutput::openDevice(), Bladerf1Output::openDevice(), HackRFOutput::openDevice(), BladeRF2Output::openDevice(), SoapySDROutput::openDevice(), XTRXOutput::openDevice(), FileSinkThread::setSamplerate(), and RemoteOutputThread::setSamplerate().
 {
     qDebug("SampleSourceFifo::resize: %d", size);
     m_size = size;
     m_data.resize(2*m_size);
     init();
 }
setIteratorFromOffset()
void SampleSourceFifo::setIteratorFromOffset (SampleVector::iterator & iterator, int offset)
Definition at line 109 of file samplesourcefifo.cpp.
References m_data.
Referenced by LocalSource::processSamples().
 {
     iterator = m_data.begin() + offset;
 }
size()
uint32_t SampleSourceFifo::size () const inline
Definition at line 37 of file samplesourcefifo.h.
Referenced by resize(), and LocalSource::start().
 { return m_size; }
write()
void SampleSourceFifo::write (const Sample & sample)
write directly - phase 1 + phase 2
Definition at line 71 of file samplesourcefifo.cpp.
References m_data, m_iw, and m_size.
 {
     m_data[m_iw] = sample;
     m_data[m_iw+m_size] = sample;
     {
 //        QMutexLocker mutexLocker(&m_mutex);
         m_iw = (m_iw+1) % m_size;
     }
 }
Member Data Documentation
m_data
SampleVector SampleSourceFifo::m_data private
Definition at line 64 of file samplesourcefifo.h.
Referenced by bumpIndex(), getIteratorOffset(), getReadIterator(), getWriteIterator(), init(), readAdvance(), resize(), SampleSourceFifo(), setIteratorFromOffset(), and write().
m_init
bool SampleSourceFifo::m_init private
Definition at line 67 of file samplesourcefifo.h.
Referenced by init().
m_ir
uint32_t SampleSourceFifo::m_ir private
Definition at line 66 of file samplesourcefifo.h.
Referenced by getReadIterator(), init(), and readAdvance().
m_iw
uint32_t SampleSourceFifo::m_iw private
Definition at line 65 of file samplesourcefifo.h.
Referenced by bumpIndex(), getWriteIterator(), init(), and write().
m_mutex
QMutex SampleSourceFifo::m_mutex private
Definition at line 68 of file samplesourcefifo.h.
m_size
uint32_t SampleSourceFifo::m_size private
Definition at line 63 of file samplesourcefifo.h.
Referenced by bumpIndex(), getReadIterator(), init(), readAdvance(), resize(), SampleSourceFifo(), and write().
The documentation for this class was generated from the following files:
sdrbase/dsp/samplesourcefifo.h
sdrbase/dsp/samplesourcefifo.cpp