SDRAngel: AMDemod Class Reference
AMDemod Class Reference
#include <amdemod.h>
Classes
struct MagSqLevelsStore
class MsgConfigureAMDemod
class MsgConfigureChannelizer
Public Member Functions
AMDemod (DeviceAPI *deviceAPI)
~AMDemod ()
virtual void destroy ()
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool po)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
uint32_t getAudioSampleRate () const
double getMagSq () const
bool getSquelchOpen () const
bool getPllLocked () const
Real getPllFrequency () const
void getMagSqLevels (double &avg, double &peak, int &nbSamples)
uint32_t getNumberOfDeviceStreams () const
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.amdemod"
static const QString m_channelId = "AMDemod"
Private Types
enum RateState { RSInitialFill, RSRunning }
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const AMDemodSettings &settings, bool force=false)
void applyAudioSampleRate (int sampleRate)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const AMDemodSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const AMDemodSettings &settings, bool force)
void processOneSample (Complex &ci)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
int m_inputSampleRate
int m_inputFrequencyOffset
AMDemodSettings m_settings
uint32_t m_audioSampleRate
bool m_running
NCO m_nco
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
Real m_squelchLevel
uint32_t m_squelchCount
bool m_squelchOpen
DoubleBufferFIFO< Real > m_squelchDelayLine
double m_magsq
double m_magsqSum
double m_magsqPeak
int m_magsqCount
MagSqLevelsStore m_magSqLevelStore
MovingAverageUtil< Real, double, 16 > m_movingAverage
SimpleAGC< 4800 > m_volumeAGC
Bandpass< Real > m_bandpass
Lowpass< Real > m_lowpass
Lowpass< std::complex< float > > m_pllFilt
PhaseLockComplex m_pll
fftfilt * DSBFilter
fftfilt * SSBFilter
Real m_syncAMBuff [2 *1024]
uint32_t m_syncAMBuffIndex
MagAGC m_syncAMAGC
AudioVector m_audioBuffer
uint32_t m_audioBufferFill
AudioFifo m_audioFifo
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
QMutex m_settingsMutex
Static Private Attributes
static const int m_udpBlockSize = 512
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 48 of file amdemod.h.
Member Enumeration Documentation
RateState
enum AMDemod::RateState private
Enumerator
RSInitialFill
RSRunning
Definition at line 177 of file amdemod.h.
                    {
         RSInitialFill,
         RSRunning
     };
Constructor & Destructor Documentation
AMDemod()
AMDemod::AMDemod (DeviceAPI * deviceAPI)
Definition at line 52 of file amdemod.cpp.
References AudioDeviceManager::addAudioSink(), DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), applyChannelSettings(), applySettings(), PhaseLockComplex::computeCoefficients(), Lowpass< Type >::create(), DSBFilter, DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_channelId, m_channelizer, m_deviceAPI, m_inputFrequencyOffset, m_inputSampleRate, m_magsq, m_networkManager, m_pll, m_pllFilt, AMDemodSettings::m_rfBandwidth, m_settings, m_syncAMAGC, m_syncAMBuffIndex, m_threadedChannelizer, networkManagerFinished(), MagAGC::resize(), MagAGC::setThresholdEnable(), and SSBFilter.
Referenced by AMDemod::MsgConfigureChannelizer::MsgConfigureChannelizer().
                                      :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(deviceAPI),
         m_inputSampleRate(48000),
         m_inputFrequencyOffset(0),
         m_running(false),
         m_squelchOpen(false),
         m_squelchDelayLine(9600),
         m_magsqSum(0.0f),
         m_magsqPeak(0.0f),
         m_magsqCount(0),
         m_volumeAGC(0.003),
         m_syncAMAGC(12000, 0.1, 1e-2),
         m_audioFifo(48000),
         m_settingsMutex(QMutex::Recursive)
 {
     setObjectName(m_channelId);
     m_audioBuffer.resize(1<<14);
     m_audioBufferFill = 0;
     m_magsq = 0.0;
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSink(&m_audioFifo, getInputMessageQueue());
     m_audioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getOutputSampleRate();
     DSBFilter = new fftfilt((2.0f * m_settings.m_rfBandwidth) / m_audioSampleRate, 2 * 1024);
     SSBFilter = new fftfilt(0.0f, m_settings.m_rfBandwidth / m_audioSampleRate, 1024);
     m_syncAMAGC.setThresholdEnable(false);
     m_syncAMAGC.resize(12000, 6000, 0.1);
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
     m_pllFilt.create(101, m_audioSampleRate, 200.0);
     m_pll.computeCoefficients(0.05, 0.707, 1000);
     m_syncAMBuffIndex = 0;
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~AMDemod()
AMDemod::~AMDemod ()
Definition at line 98 of file amdemod.cpp.
References DSBFilter, DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo, m_channelizer, m_deviceAPI, m_networkManager, m_threadedChannelizer, networkManagerFinished(), AudioDeviceManager::removeAudioSink(), DeviceAPI::removeChannelSink(), DeviceAPI::removeChannelSinkAPI(), and SSBFilter.
Referenced by AMDemod::MsgConfigureChannelizer::MsgConfigureChannelizer().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_audioFifo);
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete DSBFilter;
     delete SSBFilter;
 }
Member Function Documentation
applyAudioSampleRate()
void AMDemod::applyAudioSampleRate (int sampleRate) private
Definition at line 377 of file amdemod.cpp.
References Bandpass< Type >::create(), Lowpass< Type >::create(), Interpolator::create(), AMDemod::MsgConfigureChannelizer::create(), fftfilt::create_dsb_filter(), DSBFilter, m_audioFifo, m_audioSampleRate, m_bandpass, AMDemodSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_lowpass, AMDemodSettings::m_pll, m_pll, m_pllFilt, AMDemodSettings::m_rfBandwidth, m_settings, m_settingsMutex, m_squelchDelayLine, m_syncAMAGC, m_volumeAGC, MessageQueue::push(), DoubleBufferFIFO< T >::resize(), MagAGC::resize(), SimpleAGC< AvgSize >::resizeNew(), PhaseLockComplex::setSampleRate(), and AudioFifo::setSize().
Referenced by applySettings(), and handleMessage().
 {
     qDebug("AMDemod::applyAudioSampleRate: sampleRate: %d m_inputSampleRate: %d", sampleRate, m_inputSampleRate);
     MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
             sampleRate, m_settings.m_inputFrequencyOffset);
     m_inputMessageQueue.push(channelConfigMsg);
     m_settingsMutex.lock();
     m_interpolator.create(16, m_inputSampleRate, m_settings.m_rfBandwidth / 2.2f);
     m_interpolatorDistanceRemain = 0;
     m_interpolatorDistance = (Real) m_inputSampleRate / (Real) sampleRate;
     m_bandpass.create(301, sampleRate, 300.0, m_settings.m_rfBandwidth / 2.0f);
     m_lowpass.create(301, sampleRate,  m_settings.m_rfBandwidth / 2.0f);
     m_audioFifo.setSize(sampleRate);
     m_squelchDelayLine.resize(sampleRate/5);
     DSBFilter->create_dsb_filter((2.0f * m_settings.m_rfBandwidth) / (float) sampleRate);
     m_pllFilt.create(101, sampleRate, 200.0);
     if (m_settings.m_pll) {
         m_volumeAGC.resizeNew(sampleRate, 0.003);
     } else {
         m_volumeAGC.resizeNew(sampleRate/10, 0.003);
     }
     m_syncAMAGC.resize(sampleRate/4, sampleRate/8, 0.1);
     m_pll.setSampleRate(sampleRate);
     m_settingsMutex.unlock();
     m_audioSampleRate = sampleRate;
 }
applyChannelSettings()
void AMDemod::applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 410 of file amdemod.cpp.
References Interpolator::create(), m_audioSampleRate, m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_nco, AMDemodSettings::m_rfBandwidth, m_settings, m_settingsMutex, and NCO::setFreq().
Referenced by AMDemod(), applySettings(), handleMessage(), and start().
 {
     qDebug() << "AMDemod::applyChannelSettings:"
             << " inputSampleRate: " << inputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset
             << " m_audioSampleRate: " << m_audioSampleRate;
     if ((m_inputFrequencyOffset != inputFrequencyOffset) ||
         (m_inputSampleRate != inputSampleRate) || force)
     {
         m_nco.setFreq(-inputFrequencyOffset, inputSampleRate);
     }
     if ((m_inputSampleRate != inputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_interpolator.create(16, inputSampleRate, m_settings.m_rfBandwidth / 2.2f);
         m_interpolatorDistanceRemain = 0;
         m_interpolatorDistance = (Real) inputSampleRate / (Real) m_audioSampleRate;
         m_settingsMutex.unlock();
     }
     m_inputSampleRate = inputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applySettings()
void AMDemod::applySettings (const AMDemodSettings & settings, bool force = false) private
Definition at line 436 of file amdemod.cpp.
References AudioDeviceManager::addAudioSink(), DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), applyAudioSampleRate(), applyChannelSettings(), Bandpass< Type >::create(), Lowpass< Type >::create(), Interpolator::create(), fftfilt::create_dsb_filter(), DSBFilter, DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputDeviceIndex(), AudioDeviceManager::getOutputSampleRate(), DeviceAPI::getSampleMIMO(), DeviceSampleMIMO::getSourceSampleRate(), DSPEngine::instance(), AMDemodSettings::m_audioDeviceName, m_audioFifo, AMDemodSettings::m_audioMute, m_audioSampleRate, m_bandpass, AMDemodSettings::m_bandpassEnable, m_deviceAPI, AMDemodSettings::m_inputFrequencyOffset, m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_lowpass, AMDemodSettings::m_pll, AMDemodSettings::m_reverseAPIAddress, AMDemodSettings::m_reverseAPIChannelIndex, AMDemodSettings::m_reverseAPIDeviceIndex, AMDemodSettings::m_reverseAPIPort, AMDemodSettings::m_rfBandwidth, m_settings, m_settingsMutex, AMDemodSettings::m_squelch, m_squelchLevel, AMDemodSettings::m_streamIndex, m_syncAMBuffIndex, AMDemodSettings::m_syncAMOperation, m_threadedChannelizer, AMDemodSettings::m_useReverseAPI, AMDemodSettings::m_volume, m_volumeAGC, CalcDb::powerFromdB(), DeviceAPI::removeChannelSink(), DeviceAPI::removeChannelSinkAPI(), SimpleAGC< AvgSize >::resizeNew(), and webapiReverseSendSettings().
Referenced by AMDemod(), and handleMessage().
 {
     qDebug() << "AMDemod::applySettings:"
             << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
             << " m_rfBandwidth: " << settings.m_rfBandwidth
             << " m_volume: " << settings.m_volume
             << " m_squelch: " << settings.m_squelch
             << " m_audioMute: " << settings.m_audioMute
             << " m_bandpassEnable: " << settings.m_bandpassEnable
             << " m_audioDeviceName: " << settings.m_audioDeviceName
             << " m_pll: " << settings.m_pll
             << " m_syncAMOperation: " << (int) settings.m_syncAMOperation
             << " m_streamIndex: " << settings.m_streamIndex
             << " m_useReverseAPI: " << settings.m_useReverseAPI
             << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
             << " m_reverseAPIPort: " << settings.m_reverseAPIPort
             << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex
             << " m_reverseAPIChannelIndex: " << settings.m_reverseAPIChannelIndex
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if((m_settings.m_rfBandwidth != settings.m_rfBandwidth) ||
         (m_settings.m_bandpassEnable != settings.m_bandpassEnable) || force)
     {
         m_settingsMutex.lock();
         m_interpolator.create(16, m_inputSampleRate, settings.m_rfBandwidth / 2.2f);
         m_interpolatorDistanceRemain = 0;
         m_interpolatorDistance = (Real) m_inputSampleRate / (Real) m_audioSampleRate;
         m_bandpass.create(301, m_audioSampleRate, 300.0, settings.m_rfBandwidth / 2.0f);
         m_lowpass.create(301, m_audioSampleRate,  settings.m_rfBandwidth / 2.0f);
         DSBFilter->create_dsb_filter((2.0f * settings.m_rfBandwidth) / (float) m_audioSampleRate);
         m_settingsMutex.unlock();
         if ((m_settings.m_rfBandwidth != settings.m_rfBandwidth) || force) {
             reverseAPIKeys.append("rfBandwidth");
         }
         if ((m_settings.m_bandpassEnable != settings.m_bandpassEnable) || force) {
             reverseAPIKeys.append("bandpassEnable");
         }
     }
     if ((m_settings.m_squelch != settings.m_squelch) || force)
     {
         m_squelchLevel = CalcDb::powerFromdB(settings.m_squelch);
         reverseAPIKeys.append("squelch");
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force)
     {
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getOutputDeviceIndex(settings.m_audioDeviceName);
         //qDebug("AMDemod::applySettings: audioDeviceName: %s audioDeviceIndex: %d", qPrintable(settings.m_audioDeviceName), audioDeviceIndex);
         audioDeviceManager->addAudioSink(&m_audioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getOutputSampleRate(audioDeviceIndex);
         if (m_audioSampleRate != audioSampleRate) {
             applyAudioSampleRate(audioSampleRate);
         }
         reverseAPIKeys.append("audioDeviceName");
     }
     if ((m_settings.m_pll != settings.m_pll) || force)
     {
         if (settings.m_pll)
         {
             m_volumeAGC.resizeNew(m_audioSampleRate/4, 0.003);
             m_syncAMBuffIndex = 0;
         }
         else
         {
             m_volumeAGC.resizeNew(m_audioSampleRate/10, 0.003);
         }
         reverseAPIKeys.append("pll");
         reverseAPIKeys.append("syncAMOperation");
     }
     if ((m_settings.m_syncAMOperation != settings.m_syncAMOperation) || force)
     {
         m_syncAMBuffIndex = 0;
         reverseAPIKeys.append("pll");
         reverseAPIKeys.append("syncAMOperation");
     }
     if ((m_settings.m_inputFrequencyOffset != settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if ((m_settings.m_audioMute != settings.m_audioMute) || force) {
         reverseAPIKeys.append("audioMute");
     }
     if ((m_settings.m_volume != settings.m_volume) || force) {
         reverseAPIKeys.append("volume");
     }
     if (m_settings.m_streamIndex != settings.m_streamIndex)
     {
         if (m_deviceAPI->getSampleMIMO()) // change of stream is possible for MIMO devices only
         {
             m_deviceAPI->removeChannelSinkAPI(this, m_settings.m_streamIndex);
             m_deviceAPI->removeChannelSink(m_threadedChannelizer, m_settings.m_streamIndex);
             m_deviceAPI->addChannelSink(m_threadedChannelizer, settings.m_streamIndex);
             m_deviceAPI->addChannelSinkAPI(this, settings.m_streamIndex);
             // apply stream sample rate to itself
             applyChannelSettings(m_deviceAPI->getSampleMIMO()->getSourceSampleRate(settings.m_streamIndex), m_inputFrequencyOffset);
         }
         reverseAPIKeys.append("streamIndex");
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
deserialize()
bool AMDemod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 567 of file amdemod.cpp.
References AMDemod::MsgConfigureAMDemod::create(), AMDemodSettings::deserialize(), BasebandSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and AMDemodSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureAMDemod *msg = MsgConfigureAMDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureAMDemod *msg = MsgConfigureAMDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void AMDemod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 99 of file amdemod.h.
References feed(), handleMessage(), start(), and stop().
 { delete this; }
feed()
void AMDemod::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool po) virtual
Implements BasebandSampleSink.
Definition at line 116 of file amdemod.cpp.
References Interpolator::decimate(), Interpolator::interpolate(), m_audioBuffer, m_audioBufferFill, m_audioFifo, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_nco, m_running, m_settingsMutex, NCO::nextIQ(), processOneSample(), and AudioFifo::write().
Referenced by destroy().
 {
     (void) firstOfBurst;
     Complex ci;
     if (!m_running) {
         return;
     }
     m_settingsMutex.lock();
     for (SampleVector::const_iterator it = begin; it != end; ++it)
     {
         Complex c(it->real(), it->imag());
         c *= m_nco.nextIQ();
         if (m_interpolatorDistance < 1.0f) // interpolate
         {
             while (!m_interpolator.interpolate(&m_interpolatorDistanceRemain, c, &ci))
             {
                 processOneSample(ci);
                 m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
         }
         else // decimate
         {
             if (m_interpolator.decimate(&m_interpolatorDistanceRemain, c, &ci))
             {
                 processOneSample(ci);
                 m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
         }
     }
     if (m_audioBufferFill > 0)
     {
         uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
         if (res != m_audioBufferFill)
         {
             qDebug("AMDemod::feed: %u/%u tail samples written", res, m_audioBufferFill);
         }
         m_audioBufferFill = 0;
     }
     m_settingsMutex.unlock();
 }
getAudioSampleRate()
uint32_t AMDemod::getAudioSampleRate () const inline
Definition at line 137 of file amdemod.h.
References m_audioSampleRate.
Referenced by AMDemodGUI::applySettings(), and AMDemodGUI::tick().
 { return m_audioSampleRate; }
getCenterFrequency()
virtual qint64 AMDemod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 108 of file amdemod.h.
References deserialize(), AMDemodSettings::m_inputFrequencyOffset, AMDemod::MsgConfigureAMDemod::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getIdentifier()
virtual void AMDemod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 106 of file amdemod.h.
 { id = objectName(); }
getMagSq()
double AMDemod::getMagSq () const inline
Definition at line 138 of file amdemod.h.
References m_magsq.
 { return m_magsq; }
getMagSqLevels()
void AMDemod::getMagSqLevels (double & avg, double & peak, int & nbSamples) inline
Definition at line 143 of file amdemod.h.
References getNumberOfDeviceStreams(), AMDemod::MagSqLevelsStore::m_magsq, m_magsq, m_magsqCount, m_magSqLevelStore, AMDemod::MagSqLevelsStore::m_magsqPeak, m_magsqPeak, and m_magsqSum.
Referenced by AMDemodGUI::tick(), and webapiFormatChannelReport().
     {
         if (m_magsqCount > 0)
         {
             m_magsq = m_magsqSum / m_magsqCount;
             m_magSqLevelStore.m_magsq = m_magsq;
             m_magSqLevelStore.m_magsqPeak = m_magsqPeak;
         }
         avg = m_magSqLevelStore.m_magsq;
         peak = m_magSqLevelStore.m_magsqPeak;
         nbSamples = m_magsqCount == 0 ? 1 : m_magsqCount;
         m_magsqSum = 0.0f;
         m_magsqPeak = 0.0f;
         m_magsqCount = 0;
     }
getNbSinkStreams()
virtual int AMDemod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 113 of file amdemod.h.
 { return 1; }
getNbSourceStreams()
virtual int AMDemod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 114 of file amdemod.h.
 { return 0; }
getNumberOfDeviceStreams()
uint32_t AMDemod::getNumberOfDeviceStreams () const
Definition at line 111 of file amdemod.cpp.
References DeviceAPI::getNbSourceStreams(), and m_deviceAPI.
Referenced by getMagSqLevels(), and AMDemodGUI::onMenuDialogCalled().
 {
     return m_deviceAPI->getNbSourceStreams();
 }
getPllFrequency()
Real AMDemod::getPllFrequency () const inline
Definition at line 141 of file amdemod.h.
References PhaseLockComplex::getFreq(), and m_pll.
Referenced by AMDemodGUI::tick().
 { return m_pll.getFreq(); }
getPllLocked()
bool AMDemod::getPllLocked () const inline
Definition at line 140 of file amdemod.h.
References PhaseLockComplex::locked(), AMDemodSettings::m_pll, m_pll, and AMDemod::MsgConfigureAMDemod::m_settings.
Referenced by AMDemodGUI::tick().
 { return m_settings.m_pll && m_pll.locked(); }
getSquelchOpen()
bool AMDemod::getSquelchOpen () const inline
Definition at line 139 of file amdemod.h.
References m_squelchOpen.
Referenced by AMDemodGUI::tick().
 { return m_squelchOpen; }
getStreamCenterFrequency()
virtual qint64 AMDemod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 116 of file amdemod.h.
References AMDemodSettings::m_inputFrequencyOffset, AMDemod::MsgConfigureAMDemod::m_settings, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void AMDemod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 107 of file amdemod.h.
References AMDemod::MsgConfigureAMDemod::m_settings, and AMDemodSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool AMDemod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 310 of file amdemod.cpp.
References applyAudioSampleRate(), applyChannelSettings(), applySettings(), DownChannelizer::configure(), AMDemod::MsgConfigureChannelizer::getCenterFrequency(), AMDemod::MsgConfigureAMDemod::getForce(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSink::getInputMessageQueue(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), AMDemod::MsgConfigureChannelizer::getSampleRate(), DSPConfigureAudio::getSampleRate(), AMDemod::MsgConfigureAMDemod::getSettings(), BasebandSampleSink::MsgThreadedSink::getThread(), m_audioSampleRate, m_channelizer, and Message::match().
Referenced by destroy().
 {
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& notif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "AMDemod::handleMessage: MsgChannelizerNotification:"
                 << " inputSampleRate: " << notif.getSampleRate()
                 << " inputFrequencyOffset: " << notif.getFrequencyOffset();
         applyChannelSettings(notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "AMDemod::handleMessage: MsgConfigureChannelizer:"
                 << " sampleRate: " << cfg.getSampleRate()
                 << " inputFrequencyOffset: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureAMDemod::match(cmd))
     {
         MsgConfigureAMDemod& cfg = (MsgConfigureAMDemod&) cmd;
         qDebug() << "AMDemod::handleMessage: MsgConfigureAMDemod";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (BasebandSampleSink::MsgThreadedSink::match(cmd))
     {
         BasebandSampleSink::MsgThreadedSink& cfg = (BasebandSampleSink::MsgThreadedSink&) cmd;
         const QThread *thread = cfg.getThread();
         qDebug("AMDemod::handleMessage: BasebandSampleSink::MsgThreadedSink: %p", thread);
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else if (DSPConfigureAudio::match(cmd))
     {
         DSPConfigureAudio& cfg = (DSPConfigureAudio&) cmd;
         uint32_t sampleRate = cfg.getSampleRate();
         qDebug() << "AMDemod::handleMessage: DSPConfigureAudio:"
                 << " sampleRate: " << sampleRate;
         if (sampleRate != m_audioSampleRate) {
             applyAudioSampleRate(sampleRate);
         }
         return true;
     }
     else
     {
         return false;
     }
 }
networkManagerFinished
void AMDemod::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 816 of file amdemod.cpp.
Referenced by AMDemod(), and ~AMDemod().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "AMDemod::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("AMDemod::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
processOneSample()
void AMDemod::processOneSample (Complex & ci) private
Definition at line 165 of file amdemod.cpp.
References MovingAverageUtil< T, Total, N >::asDouble(), AudioFifo::clear(), DSBFilter, PhaseLockComplex::feed(), SimpleAGC< AvgSize >::feed(), MagAGC::feedAndGetValue(), Lowpass< Type >::filter(), Bandpass< Type >::filter(), PhaseLockComplex::getImag(), PhaseLockComplex::getReal(), SimpleAGC< AvgSize >::getValue(), i, m_audioBuffer, m_audioBufferFill, m_audioFifo, AMDemodSettings::m_audioMute, m_audioSampleRate, m_bandpass, AMDemodSettings::m_bandpassEnable, m_lowpass, m_magsq, m_magsqCount, m_magsqPeak, m_magsqSum, m_movingAverage, AMDemodSettings::m_pll, m_pll, m_pllFilt, m_settings, m_squelchCount, m_squelchDelayLine, m_squelchLevel, m_squelchOpen, m_syncAMAGC, m_syncAMBuff, m_syncAMBuffIndex, AMDemodSettings::m_syncAMOperation, AMDemodSettings::m_volume, m_volumeAGC, DoubleBufferFIFO< T >::readBack(), fftfilt::runDSB(), fftfilt::runSSB(), SDR_RX_SCALEF, StepFunctions::smootherstep(), sqrt(), SSBFilter, AMDemodSettings::SyncAMDSB, AMDemodSettings::SyncAMUSB, AudioFifo::write(), and DoubleBufferFIFO< T >::write().
Referenced by feed().
 {
     Real re = ci.real() / SDR_RX_SCALEF;
     Real im = ci.imag() / SDR_RX_SCALEF;
     Real magsq = re*re + im*im;
     m_movingAverage(magsq);
     m_magsq = m_movingAverage.asDouble();
     m_magsqSum += magsq;
     if (magsq > m_magsqPeak)
     {
         m_magsqPeak = magsq;
     }
     m_magsqCount++;
     m_squelchDelayLine.write(magsq);
     if (m_magsq < m_squelchLevel)
     {
         if (m_squelchCount > 0) {
             m_squelchCount--;
         }
     }
     else
     {
         if (m_squelchCount < m_audioSampleRate / 10) {
             m_squelchCount++;
         }
     }
     qint16 sample;
     m_squelchOpen = (m_squelchCount >= m_audioSampleRate / 20);
     if (m_squelchOpen && !m_settings.m_audioMute)
     {
         Real demod;
         if (m_settings.m_pll)
         {
             std::complex<float> s(re, im);
             s = m_pllFilt.filter(s);
             m_pll.feed(s.real(), s.imag());
             float yr = re * m_pll.getImag() - im * m_pll.getReal();
             float yi = re * m_pll.getReal() + im * m_pll.getImag();
             fftfilt::cmplx *sideband;
             std::complex<float> cs(yr, yi);
             int n_out;
             if (m_settings.m_syncAMOperation == AMDemodSettings::SyncAMDSB) {
                 n_out = DSBFilter->runDSB(cs, &sideband, false);
             } else {
                 n_out = SSBFilter->runSSB(cs, &sideband, m_settings.m_syncAMOperation == AMDemodSettings::SyncAMUSB, false);
             }
             for (int i = 0; i < n_out; i++)
             {
                 float agcVal = m_syncAMAGC.feedAndGetValue(sideband[i]);
                 fftfilt::cmplx z = sideband[i] * agcVal; // * m_syncAMAGC.getStepValue();
                 if (m_settings.m_syncAMOperation == AMDemodSettings::SyncAMDSB) {
                     m_syncAMBuff[i] = (z.real() + z.imag());
                 } else if (m_settings.m_syncAMOperation == AMDemodSettings::SyncAMUSB) {
                     m_syncAMBuff[i] = (z.real() + z.imag());
                 } else {
                     m_syncAMBuff[i] = (z.real() + z.imag());
                 }
 //                    if (m_settings.m_syncAMOperation == AMDemodSettings::SyncAMDSB) {
 //                        m_syncAMBuff[i] = (sideband[i].real() + sideband[i].imag())/2.0f;
 //                    } else if (m_settings.m_syncAMOperation == AMDemodSettings::SyncAMUSB) {
 //                        m_syncAMBuff[i] = (sideband[i].real() + sideband[i].imag());
 //                    } else {
 //                        m_syncAMBuff[i] = (sideband[i].real() + sideband[i].imag());
 //                    }
                 m_syncAMBuffIndex = 0;
             }
             m_syncAMBuffIndex = m_syncAMBuffIndex < 2*1024 ? m_syncAMBuffIndex : 0;
             demod = m_syncAMBuff[m_syncAMBuffIndex++]*4.0f; // mos pifometrico
 //                demod = m_syncAMBuff[m_syncAMBuffIndex++]*(SDR_RX_SCALEF/602.0f);
 //                m_volumeAGC.feed(demod);
 //                demod /= (10.0*m_volumeAGC.getValue());
         }
         else
         {
             demod = sqrt(m_squelchDelayLine.readBack(m_audioSampleRate/20));
             m_volumeAGC.feed(demod);
             demod = (demod - m_volumeAGC.getValue()) / m_volumeAGC.getValue();
         }
         if (m_settings.m_bandpassEnable)
         {
             demod = m_bandpass.filter(demod);
             demod /= 301.0f;
         }
         else
         {
             demod = m_lowpass.filter(demod);
         }
         Real attack = (m_squelchCount - 0.05f * m_audioSampleRate) / (0.05f * m_audioSampleRate);
         sample = demod * StepFunctions::smootherstep(attack) * (m_audioSampleRate/24) * m_settings.m_volume;
     }
     else
     {
         sample = 0;
     }
     m_audioBuffer[m_audioBufferFill].l = sample;
     m_audioBuffer[m_audioBufferFill].r = sample;
     ++m_audioBufferFill;
     if (m_audioBufferFill >= m_audioBuffer.size())
     {
         uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
         if (res != m_audioBufferFill)
         {
             qDebug("AMDemod::processOneSample: %u/%u audio samples written", res, m_audioBufferFill);
             m_audioFifo.clear();
         }
         m_audioBufferFill = 0;
     }
 }
serialize()
QByteArray AMDemod::serialize () const virtual
Implements ChannelAPI.
Definition at line 562 of file amdemod.cpp.
References m_settings, and AMDemodSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
start()
void AMDemod::start () virtual
Implements BasebandSampleSink.
Definition at line 295 of file amdemod.cpp.
References applyChannelSettings(), AudioFifo::clear(), m_audioFifo, m_inputFrequencyOffset, m_inputSampleRate, m_running, and m_squelchCount.
Referenced by destroy().
 {
     qDebug("AMDemod::start");
     m_squelchCount = 0;
     m_audioFifo.clear();
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
     m_running = true;
 }
stop()
void AMDemod::stop () virtual
Implements BasebandSampleSink.
Definition at line 304 of file amdemod.cpp.
References m_running.
Referenced by destroy().
 {
     qDebug("AMDemod::stop");
     m_running = false;
 }
webapiFormatChannelReport()
void AMDemod::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 736 of file amdemod.cpp.
References CalcDb::dbPower(), SWGSDRangel::SWGChannelReport::getAmDemodReport(), getMagSqLevels(), m_audioSampleRate, m_inputSampleRate, m_squelchOpen, SWGSDRangel::SWGAMDemodReport::setAudioSampleRate(), SWGSDRangel::SWGAMDemodReport::setChannelPowerDb(), SWGSDRangel::SWGAMDemodReport::setChannelSampleRate(), and SWGSDRangel::SWGAMDemodReport::setSquelch().
Referenced by webapiReportGet().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     response.getAmDemodReport()->setChannelPowerDb(CalcDb::dbPower(magsqAvg));
     response.getAmDemodReport()->setSquelch(m_squelchOpen ? 1 : 0);
     response.getAmDemodReport()->setAudioSampleRate(m_audioSampleRate);
     response.getAmDemodReport()->setChannelSampleRate(m_inputSampleRate);
 }
webapiFormatChannelSettings()
void AMDemod::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const AMDemodSettings & settings) private
Definition at line 698 of file amdemod.cpp.
References SWGSDRangel::SWGChannelSettings::getAmDemodSettings(), SWGSDRangel::SWGAMDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGAMDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGAMDemodSettings::getTitle(), AMDemodSettings::m_audioDeviceName, AMDemodSettings::m_audioMute, AMDemodSettings::m_bandpassEnable, AMDemodSettings::m_inputFrequencyOffset, AMDemodSettings::m_pll, AMDemodSettings::m_reverseAPIAddress, AMDemodSettings::m_reverseAPIChannelIndex, AMDemodSettings::m_reverseAPIDeviceIndex, AMDemodSettings::m_reverseAPIPort, AMDemodSettings::m_rfBandwidth, AMDemodSettings::m_rgbColor, m_settings, AMDemodSettings::m_squelch, AMDemodSettings::m_streamIndex, AMDemodSettings::m_syncAMOperation, AMDemodSettings::m_title, AMDemodSettings::m_useReverseAPI, AMDemodSettings::m_volume, SWGSDRangel::SWGAMDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGAMDemodSettings::setAudioMute(), SWGSDRangel::SWGAMDemodSettings::setBandpassEnable(), SWGSDRangel::SWGAMDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGAMDemodSettings::setPll(), SWGSDRangel::SWGAMDemodSettings::setReverseApiAddress(), SWGSDRangel::SWGAMDemodSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGAMDemodSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGAMDemodSettings::setReverseApiPort(), SWGSDRangel::SWGAMDemodSettings::setRfBandwidth(), SWGSDRangel::SWGAMDemodSettings::setRgbColor(), SWGSDRangel::SWGAMDemodSettings::setSquelch(), SWGSDRangel::SWGAMDemodSettings::setStreamIndex(), SWGSDRangel::SWGAMDemodSettings::setSyncAmOperation(), SWGSDRangel::SWGAMDemodSettings::setTitle(), SWGSDRangel::SWGAMDemodSettings::setUseReverseApi(), and SWGSDRangel::SWGAMDemodSettings::setVolume().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getAmDemodSettings()->setAudioMute(settings.m_audioMute ? 1 : 0);
     response.getAmDemodSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getAmDemodSettings()->setRfBandwidth(settings.m_rfBandwidth);
     response.getAmDemodSettings()->setRgbColor(settings.m_rgbColor);
     response.getAmDemodSettings()->setSquelch(settings.m_squelch);
     response.getAmDemodSettings()->setVolume(settings.m_volume);
     response.getAmDemodSettings()->setBandpassEnable(settings.m_bandpassEnable ? 1 : 0);
     if (response.getAmDemodSettings()->getTitle()) {
         *response.getAmDemodSettings()->getTitle() = settings.m_title;
     } else {
         response.getAmDemodSettings()->setTitle(new QString(settings.m_title));
     }
     if (response.getAmDemodSettings()->getAudioDeviceName()) {
         *response.getAmDemodSettings()->getAudioDeviceName() = settings.m_audioDeviceName;
     } else {
         response.getAmDemodSettings()->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     response.getAmDemodSettings()->setPll(settings.m_pll ? 1 : 0);
     response.getAmDemodSettings()->setSyncAmOperation((int) m_settings.m_syncAMOperation);
     response.getAmDemodSettings()->setStreamIndex(m_settings.m_streamIndex);
     response.getAmDemodSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getAmDemodSettings()->getReverseApiAddress()) {
         *response.getAmDemodSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getAmDemodSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getAmDemodSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getAmDemodSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getAmDemodSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int AMDemod::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 687 of file amdemod.cpp.
References SWGSDRangel::SWGChannelReport::getAmDemodReport(), SWGSDRangel::SWGAMDemodReport::init(), SWGSDRangel::SWGChannelReport::setAmDemodReport(), and webapiFormatChannelReport().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setAmDemodReport(new SWGSDRangel::SWGAMDemodReport());
     response.getAmDemodReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendSettings()
void AMDemod::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const AMDemodSettings & settings, bool force) private
Definition at line 748 of file amdemod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), SWGSDRangel::SWGChannelSettings::getAmDemodSettings(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), AMDemodSettings::m_audioDeviceName, AMDemodSettings::m_audioMute, AMDemodSettings::m_bandpassEnable, AMDemodSettings::m_inputFrequencyOffset, m_networkManager, m_networkRequest, AMDemodSettings::m_pll, AMDemodSettings::m_reverseAPIAddress, AMDemodSettings::m_reverseAPIChannelIndex, AMDemodSettings::m_reverseAPIDeviceIndex, AMDemodSettings::m_reverseAPIPort, AMDemodSettings::m_rfBandwidth, AMDemodSettings::m_rgbColor, AMDemodSettings::m_squelch, AMDemodSettings::m_streamIndex, AMDemodSettings::m_syncAMOperation, AMDemodSettings::m_title, AMDemodSettings::m_volume, SWGSDRangel::SWGChannelSettings::setAmDemodSettings(), SWGSDRangel::SWGAMDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGAMDemodSettings::setAudioMute(), SWGSDRangel::SWGAMDemodSettings::setBandpassEnable(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGAMDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGAMDemodSettings::setPll(), SWGSDRangel::SWGAMDemodSettings::setRfBandwidth(), SWGSDRangel::SWGAMDemodSettings::setRgbColor(), SWGSDRangel::SWGAMDemodSettings::setSquelch(), SWGSDRangel::SWGAMDemodSettings::setStreamIndex(), SWGSDRangel::SWGAMDemodSettings::setSyncAmOperation(), SWGSDRangel::SWGAMDemodSettings::setTitle(), and SWGSDRangel::SWGAMDemodSettings::setVolume().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(0); // Single sink (Rx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("AMDemod"));
     swgChannelSettings->setAmDemodSettings(new SWGSDRangel::SWGAMDemodSettings());
     SWGSDRangel::SWGAMDemodSettings *swgAMDemodSettings = swgChannelSettings->getAmDemodSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("audioMute") || force) {
         swgAMDemodSettings->setAudioMute(settings.m_audioMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgAMDemodSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("rfBandwidth") || force) {
         swgAMDemodSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgAMDemodSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("squelch") || force) {
         swgAMDemodSettings->setSquelch(settings.m_squelch);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgAMDemodSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("volume") || force) {
         swgAMDemodSettings->setVolume(settings.m_volume);
     }
     if (channelSettingsKeys.contains("bandpassEnable") || force) {
         swgAMDemodSettings->setBandpassEnable(settings.m_bandpassEnable ? 1 : 0);
     }
     if (channelSettingsKeys.contains("audioDeviceName") || force) {
         swgAMDemodSettings->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     if (channelSettingsKeys.contains("pll") || force) {
         swgAMDemodSettings->setPll(settings.m_pll);
     }
     if (channelSettingsKeys.contains("syncAMOperation") || force) {
         swgAMDemodSettings->setSyncAmOperation((int) settings.m_syncAMOperation);
     }
     if (channelSettingsKeys.contains("streamIndex") || force) {
         swgAMDemodSettings->setStreamIndex(settings.m_streamIndex);
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int AMDemod::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 584 of file amdemod.cpp.
References SWGSDRangel::SWGChannelSettings::getAmDemodSettings(), SWGSDRangel::SWGAMDemodSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setAmDemodSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setAmDemodSettings(new SWGSDRangel::SWGAMDemodSettings());
     response.getAmDemodSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int AMDemod::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 595 of file amdemod.cpp.
References AMDemod::MsgConfigureAMDemod::create(), AMDemod::MsgConfigureChannelizer::create(), SWGSDRangel::SWGChannelSettings::getAmDemodSettings(), SWGSDRangel::SWGAMDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGAMDemodSettings::getAudioMute(), SWGSDRangel::SWGAMDemodSettings::getBandpassEnable(), SWGSDRangel::SWGAMDemodSettings::getInputFrequencyOffset(), SWGSDRangel::SWGAMDemodSettings::getPll(), SWGSDRangel::SWGAMDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGAMDemodSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGAMDemodSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGAMDemodSettings::getReverseApiPort(), SWGSDRangel::SWGAMDemodSettings::getRfBandwidth(), SWGSDRangel::SWGAMDemodSettings::getRgbColor(), SWGSDRangel::SWGAMDemodSettings::getSquelch(), SWGSDRangel::SWGAMDemodSettings::getStreamIndex(), SWGSDRangel::SWGAMDemodSettings::getSyncAmOperation(), SWGSDRangel::SWGAMDemodSettings::getTitle(), SWGSDRangel::SWGAMDemodSettings::getUseReverseApi(), SWGSDRangel::SWGAMDemodSettings::getVolume(), AMDemodSettings::m_audioDeviceName, AMDemodSettings::m_audioMute, m_audioSampleRate, AMDemodSettings::m_bandpassEnable, BasebandSampleSink::m_guiMessageQueue, AMDemodSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, AMDemodSettings::m_pll, AMDemodSettings::m_reverseAPIAddress, AMDemodSettings::m_reverseAPIChannelIndex, AMDemodSettings::m_reverseAPIDeviceIndex, AMDemodSettings::m_reverseAPIPort, AMDemodSettings::m_rfBandwidth, AMDemodSettings::m_rgbColor, m_settings, AMDemodSettings::m_squelch, AMDemodSettings::m_streamIndex, AMDemodSettings::m_syncAMOperation, AMDemodSettings::m_title, AMDemodSettings::m_useReverseAPI, AMDemodSettings::m_volume, MessageQueue::push(), AMDemodSettings::SyncAMDSB, AMDemodSettings::SyncAMLSB, and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     AMDemodSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
     if (channelSettingsKeys.contains("audioMute")) {
         settings.m_audioMute = response.getAmDemodSettings()->getAudioMute() != 0;
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getAmDemodSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getAmDemodSettings()->getRfBandwidth();
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getAmDemodSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("squelch")) {
         settings.m_squelch = response.getAmDemodSettings()->getSquelch();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getAmDemodSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("volume")) {
         settings.m_volume = response.getAmDemodSettings()->getVolume();
     }
     if (channelSettingsKeys.contains("bandpassEnable")) {
         settings.m_bandpassEnable = response.getAmDemodSettings()->getBandpassEnable() != 0;
     }
     if (channelSettingsKeys.contains("audioDeviceName")) {
         settings.m_audioDeviceName = *response.getAmDemodSettings()->getAudioDeviceName();
     }
     if (channelSettingsKeys.contains("pll")) {
         settings.m_pll = response.getAmDemodSettings()->getPll();
     }
     if (channelSettingsKeys.contains("syncAMOperation")) {
         qint32 syncAMOperationCode = response.getAmDemodSettings()->getSyncAmOperation();
         settings.m_syncAMOperation = syncAMOperationCode < 0 ?
                 AMDemodSettings::SyncAMDSB : syncAMOperationCode > 2 ?
                         AMDemodSettings::SyncAMLSB : (AMDemodSettings::SyncAMOperation) syncAMOperationCode;
     }
     if (channelSettingsKeys.contains("streamIndex")) {
         settings.m_streamIndex = response.getAmDemodSettings()->getStreamIndex();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getAmDemodSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getAmDemodSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getAmDemodSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getAmDemodSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getAmDemodSettings()->getReverseApiChannelIndex();
     }
     if (frequencyOffsetChanged)
     {
         MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
                 m_audioSampleRate, settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(channelConfigMsg);
     }
     MsgConfigureAMDemod *msg = MsgConfigureAMDemod::create(settings, force);
     m_inputMessageQueue.push(msg);
     qDebug("AMDemod::webapiSettingsPutPatch: forward to GUI: %p", m_guiMessageQueue);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureAMDemod *msgToGUI = MsgConfigureAMDemod::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
DSBFilter
fftfilt* AMDemod::DSBFilter private
Definition at line 213 of file amdemod.h.
Referenced by AMDemod(), applyAudioSampleRate(), applySettings(), processOneSample(), and ~AMDemod().
m_audioBuffer
AudioVector AMDemod::m_audioBuffer private
Definition at line 219 of file amdemod.h.
Referenced by AMDemod(), feed(), and processOneSample().
m_audioBufferFill
uint32_t AMDemod::m_audioBufferFill private
Definition at line 220 of file amdemod.h.
Referenced by AMDemod(), feed(), and processOneSample().
m_audioFifo
AudioFifo AMDemod::m_audioFifo private
Definition at line 221 of file amdemod.h.
Referenced by AMDemod(), applyAudioSampleRate(), applySettings(), feed(), processOneSample(), start(), and ~AMDemod().
m_audioSampleRate
uint32_t AMDemod::m_audioSampleRate private
Definition at line 189 of file amdemod.h.
Referenced by AMDemod(), applyAudioSampleRate(), applyChannelSettings(), applySettings(), getAudioSampleRate(), handleMessage(), processOneSample(), webapiFormatChannelReport(), and webapiSettingsPutPatch().
m_bandpass
Bandpass<Real> AMDemod::m_bandpass private
Definition at line 209 of file amdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), and processOneSample().
m_channelId
const QString AMDemod::m_channelId = "AMDemod" static
Definition at line 164 of file amdemod.h.
Referenced by AMDemod(), and AMDemodPlugin::initPlugin().
m_channelIdURI
const QString AMDemod::m_channelIdURI = "sdrangel.channel.amdemod" static
Definition at line 163 of file amdemod.h.
Referenced by AMDemodGUI::AMDemodGUI(), and AMDemodPlugin::initPlugin().
m_channelizer
DownChannelizer* AMDemod::m_channelizer private
Definition at line 184 of file amdemod.h.
Referenced by AMDemod(), handleMessage(), and ~AMDemod().
m_deviceAPI
DeviceAPI* AMDemod::m_deviceAPI private
Definition at line 182 of file amdemod.h.
Referenced by AMDemod(), applySettings(), getNumberOfDeviceStreams(), and ~AMDemod().
m_inputFrequencyOffset
int AMDemod::m_inputFrequencyOffset private
Definition at line 187 of file amdemod.h.
Referenced by AMDemod(), applyChannelSettings(), applySettings(), and start().
m_inputSampleRate
int AMDemod::m_inputSampleRate private
Definition at line 186 of file amdemod.h.
Referenced by AMDemod(), applyAudioSampleRate(), applyChannelSettings(), applySettings(), start(), and webapiFormatChannelReport().
m_interpolator
Interpolator AMDemod::m_interpolator private
Definition at line 193 of file amdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_interpolatorDistance
Real AMDemod::m_interpolatorDistance private
Definition at line 194 of file amdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_interpolatorDistanceRemain
Real AMDemod::m_interpolatorDistanceRemain private
Definition at line 195 of file amdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_lowpass
Lowpass<Real> AMDemod::m_lowpass private
Definition at line 210 of file amdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), and processOneSample().
m_magsq
double AMDemod::m_magsq private
Definition at line 201 of file amdemod.h.
Referenced by AMDemod(), getMagSq(), getMagSqLevels(), and processOneSample().
m_magsqCount
int AMDemod::m_magsqCount private
Definition at line 204 of file amdemod.h.
Referenced by getMagSqLevels(), and processOneSample().
m_magSqLevelStore
MagSqLevelsStore AMDemod::m_magSqLevelStore private
Definition at line 205 of file amdemod.h.
Referenced by getMagSqLevels().
m_magsqPeak
double AMDemod::m_magsqPeak private
Definition at line 203 of file amdemod.h.
Referenced by getMagSqLevels(), and processOneSample().
m_magsqSum
double AMDemod::m_magsqSum private
Definition at line 202 of file amdemod.h.
Referenced by getMagSqLevels(), and processOneSample().
m_movingAverage
MovingAverageUtil<Real, double, 16> AMDemod::m_movingAverage private
Definition at line 207 of file amdemod.h.
Referenced by processOneSample().
m_nco
NCO AMDemod::m_nco private
Definition at line 192 of file amdemod.h.
Referenced by applyChannelSettings(), and feed().
m_networkManager
QNetworkAccessManager* AMDemod::m_networkManager private
Definition at line 225 of file amdemod.h.
Referenced by AMDemod(), webapiReverseSendSettings(), and ~AMDemod().
m_networkRequest
QNetworkRequest AMDemod::m_networkRequest private
Definition at line 226 of file amdemod.h.
Referenced by webapiReverseSendSettings().
m_pll
PhaseLockComplex AMDemod::m_pll private
Definition at line 212 of file amdemod.h.
Referenced by AMDemod(), applyAudioSampleRate(), getPllFrequency(), getPllLocked(), and processOneSample().
m_pllFilt
Lowpass<std::complex<float> > AMDemod::m_pllFilt private
Definition at line 211 of file amdemod.h.
Referenced by AMDemod(), applyAudioSampleRate(), and processOneSample().
m_running
bool AMDemod::m_running private
Definition at line 190 of file amdemod.h.
Referenced by feed(), start(), and stop().
m_settings
AMDemodSettings AMDemod::m_settings private
Definition at line 188 of file amdemod.h.
Referenced by AMDemod(), applyAudioSampleRate(), applyChannelSettings(), applySettings(), deserialize(), processOneSample(), serialize(), webapiFormatChannelSettings(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex AMDemod::m_settingsMutex private
Definition at line 228 of file amdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_squelchCount
uint32_t AMDemod::m_squelchCount private
Definition at line 198 of file amdemod.h.
Referenced by processOneSample(), and start().
m_squelchDelayLine
DoubleBufferFIFO<Real> AMDemod::m_squelchDelayLine private
Definition at line 200 of file amdemod.h.
Referenced by applyAudioSampleRate(), and processOneSample().
m_squelchLevel
Real AMDemod::m_squelchLevel private
Definition at line 197 of file amdemod.h.
Referenced by applySettings(), and processOneSample().
m_squelchOpen
bool AMDemod::m_squelchOpen private
Definition at line 199 of file amdemod.h.
Referenced by getSquelchOpen(), processOneSample(), and webapiFormatChannelReport().
m_syncAMAGC
MagAGC AMDemod::m_syncAMAGC private
Definition at line 217 of file amdemod.h.
Referenced by AMDemod(), applyAudioSampleRate(), and processOneSample().
m_syncAMBuff
Real AMDemod::m_syncAMBuff[2 *1024] private
Definition at line 215 of file amdemod.h.
Referenced by processOneSample().
m_syncAMBuffIndex
uint32_t AMDemod::m_syncAMBuffIndex private
Definition at line 216 of file amdemod.h.
Referenced by AMDemod(), applySettings(), and processOneSample().
m_threadedChannelizer
ThreadedBasebandSampleSink* AMDemod::m_threadedChannelizer private
Definition at line 183 of file amdemod.h.
Referenced by AMDemod(), applySettings(), and ~AMDemod().
m_udpBlockSize
const int AMDemod::m_udpBlockSize = 512 static private
Definition at line 223 of file amdemod.h.
m_volumeAGC
SimpleAGC<4800> AMDemod::m_volumeAGC private
Definition at line 208 of file amdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), and processOneSample().
SSBFilter
fftfilt* AMDemod::SSBFilter private
Definition at line 214 of file amdemod.h.
Referenced by AMDemod(), processOneSample(), and ~AMDemod().
The documentation for this class was generated from the following files:
plugins/channelrx/demodam/amdemod.h
plugins/channelrx/demodam/amdemod.cpp