SDRAngel: StringRangeGUI Class Reference
StringRangeGUI Class Reference
#include <stringrangegui.h>
Inherits QWidget.
Signals
void valueChanged ()
Public Member Functions
StringRangeGUI (QWidget *parent=0)
virtual ~StringRangeGUI ()
void setLabel (const QString &text)
void setUnits (const QString &units)
void addItem (const QString &itemStr, const std::string &itemValue)
const std::string & getCurrentValue ()
void setValue (const std::string &value)
Private Slots
void on_rangeCombo_currentIndexChanged (int index)
Private Attributes
Ui::DiscreteRangeGUI * ui
std::vector< std::string > itemValues
Detailed Description
Definition at line 29 of file stringrangegui.h.
Constructor & Destructor Documentation
StringRangeGUI()
StringRangeGUI::StringRangeGUI (QWidget * parent = 0) explicit
Definition at line 22 of file stringrangegui.cpp.
References ui.
                                               :
     QWidget(parent),
     ui(new Ui::DiscreteRangeGUI)
 {
     ui->setupUi(this);
 }
~StringRangeGUI()
StringRangeGUI::~StringRangeGUI () virtual
Definition at line 29 of file stringrangegui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
addItem()
void StringRangeGUI::addItem (const QString & itemStr, const std::string & itemValue)
Definition at line 44 of file stringrangegui.cpp.
References itemValues, and ui.
Referenced by SoapySDRInputGui::createAntennasControl(), and SoapySDROutputGui::createAntennasControl().
 {
     ui->rangeCombo->blockSignals(true);
     ui->rangeCombo->addItem(itemStr);
     itemValues.push_back(itemValue);
     ui->rangeCombo->blockSignals(false);
 }
getCurrentValue()
const std::string & StringRangeGUI::getCurrentValue ()
Definition at line 52 of file stringrangegui.cpp.
References itemValues, and ui.
Referenced by SoapySDRInputGui::antennasChanged(), and SoapySDROutputGui::antennasChanged().
 {
     return itemValues[ui->rangeCombo->currentIndex()];
 }
on_rangeCombo_currentIndexChanged
void StringRangeGUI::on_rangeCombo_currentIndexChanged (int index) private slot
Definition at line 75 of file stringrangegui.cpp.
References valueChanged().
 {
     (void) index;
     emit valueChanged();
 }
setLabel()
void StringRangeGUI::setLabel (const QString & text)
Definition at line 34 of file stringrangegui.cpp.
References ui.
Referenced by SoapySDRInputGui::createAntennasControl(), and SoapySDROutputGui::createAntennasControl().
 {
     ui->rangeLabel->setText(text);
 }
setUnits()
void StringRangeGUI::setUnits (const QString & units)
Definition at line 39 of file stringrangegui.cpp.
References ui.
Referenced by SoapySDRInputGui::createAntennasControl(), and SoapySDROutputGui::createAntennasControl().
 {
     ui->rangeUnits->setText(units);
 }
setValue()
void StringRangeGUI::setValue (const std::string & value)
Definition at line 57 of file stringrangegui.cpp.
References itemValues, and ui.
Referenced by SoapySDRInputGui::displaySettings(), and SoapySDROutputGui::displaySettings().
 {
     int index = 0;
     for (const auto &it : itemValues)
     {
         if (it == value)
         {
             ui->rangeCombo->blockSignals(true);
             ui->rangeCombo->setCurrentIndex(index);
             ui->rangeCombo->blockSignals(false);
             break;
         }
         index++;
     }
 }
valueChanged
void StringRangeGUI::valueChanged () signal
Referenced by on_rangeCombo_currentIndexChanged().
Member Data Documentation
itemValues
std::vector<std::string> StringRangeGUI::itemValues private
Definition at line 50 of file stringrangegui.h.
Referenced by addItem(), getCurrentValue(), and setValue().
ui
Ui::DiscreteRangeGUI* StringRangeGUI::ui private
Definition at line 49 of file stringrangegui.h.
Referenced by addItem(), getCurrentValue(), setLabel(), setUnits(), setValue(), StringRangeGUI(), and ~StringRangeGUI().
The documentation for this class was generated from the following files:
sdrgui/soapygui/stringrangegui.h
sdrgui/soapygui/stringrangegui.cpp