SDRAngel: FreeDVDemod Class Reference
FreeDVDemod Class Reference
#include <freedvdemod.h>
Classes
struct FreeDVSNR
struct FreeDVStats
struct LevelRMS
struct MagSqLevelsStore
class MsgConfigureChannelizer
class MsgConfigureFreeDVDemod
class MsgConfigureFreeDVDemodPrivate
class MsgResyncFreeDVDemod
Signals
void levelInChanged (qreal rmsLevel, qreal peakLevel, int numSamples)
Public Member Functions
FreeDVDemod (DeviceAPI *deviceAPI)
virtual ~FreeDVDemod ()
virtual void destroy ()
void setSampleSink (BasebandSampleSink *sampleSink)
void configure (MessageQueue *messageQueue, Real Bandwidth, Real LowCutoff, Real volume, int spanLog2, bool audioBinaural, bool audioFlipChannels, bool dsb, bool audioMute, bool agc, bool agcClamping, int agcTimeLog2, int agcPowerThreshold, int agcThresholdGate)
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool positiveOnly)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
uint32_t getAudioSampleRate () const
uint32_t getModemSampleRate () const
double getMagSq () const
bool getAudioActive () const
void getMagSqLevels (double &avg, double &peak, int &nbSamples)
void getSNRLevels (double &avg, double &peak, int &nbSamples)
int getBER () const
float getFrequencyOffset () const
bool isSync () const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.freedvdemod"
static const QString m_channelId = "FreeDVDemod"
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void pushSampleToDV (int16_t sample)
void pushSampleToAudio (int16_t sample)
void applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const FreeDVDemodSettings &settings, bool force=false)
void applyAudioSampleRate (int sampleRate)
void applyFreeDVMode (FreeDVDemodSettings::FreeDVMode mode)
void processOneSample (Complex &ci)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const FreeDVDemodSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const FreeDVDemodSettings &settings, bool force)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
FreeDVDemodSettings m_settings
Real m_hiCutoff
Real m_lowCutoff
Real m_volume
int m_spanLog2
fftfilt::cmplx m_sum
int m_undersampleCount
int m_inputSampleRate
uint32_t m_modemSampleRate
uint32_t m_speechSampleRate
uint32_t m_audioSampleRate
int m_inputFrequencyOffset
bool m_audioMute
double m_magsq
double m_magsqSum
double m_magsqPeak
int m_magsqCount
MagSqLevelsStore m_magSqLevelStore
SimpleAGC< 4800 > m_simpleAGC
bool m_agcActive
DoubleBufferFIFO< fftfilt::cmplx > m_squelchDelayLine
bool m_audioActive
True if an audio signal is produced (no AGC or AGC and above threshold)
NCOF m_nco
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
fftfilt * SSBFilter
BasebandSampleSink * m_sampleSink
SampleVector m_sampleBuffer
AudioVector m_audioBuffer
uint m_audioBufferFill
AudioFifo m_audioFifo
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
struct freedv * m_freeDV
int m_nSpeechSamples
int m_nMaxModemSamples
int m_nin
int m_iSpeech
int m_iModem
int16_t * m_speechOut
int16_t * m_modIn
AudioResampler m_audioResampler
FreeDVStats m_freeDVStats
FreeDVSNR m_freeDVSNR
LevelRMS m_levelIn
int m_levelInNbSamples
QMutex m_settingsMutex
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 50 of file freedvdemod.h.
Constructor & Destructor Documentation
FreeDVDemod()
FreeDVDemod::FreeDVDemod (DeviceAPI * deviceAPI)
Definition at line 148 of file freedvdemod.cpp.
References AudioDeviceManager::addAudioSink(), DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), applyAudioSampleRate(), applyChannelSettings(), applySettings(), DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), m_agcActive, m_audioActive, m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioMute, m_channelId, m_channelizer, m_deviceAPI, m_freeDV, m_hiCutoff, m_iModem, m_inputFrequencyOffset, m_inputSampleRate, m_iSpeech, m_levelInNbSamples, m_lowCutoff, m_magsq, m_magsqCount, m_magsqPeak, m_magsqSum, m_modemSampleRate, m_modIn, m_networkManager, m_nMaxModemSamples, m_nSpeechSamples, m_sampleSink, m_settings, m_settingsMutex, m_simpleAGC, m_speechOut, m_speechSampleRate, m_squelchDelayLine, m_threadedChannelizer, m_undersampleCount, networkManagerFinished(), SimpleAGC< AvgSize >::resizeNew(), ssbFftLen, and SSBFilter.
Referenced by FreeDVDemod::MsgConfigureChannelizer::MsgConfigureChannelizer().
                                              :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(deviceAPI),
         m_hiCutoff(6000),
         m_lowCutoff(0),
         m_volume(2),
         m_spanLog2(3),
         m_sum(fftfilt::cmplx{0,0}),
         m_inputSampleRate(48000),
         m_modemSampleRate(48000),
         m_speechSampleRate(8000), // fixed 8 kS/s
         m_inputFrequencyOffset(0),
         m_audioMute(false),
         m_simpleAGC(0.003f, 0.0f, 1e-6f),
         m_agcActive(false),
         m_squelchDelayLine(2*48000),
         m_audioActive(false),
         m_sampleSink(0),
         m_audioFifo(24000),
         m_freeDV(0),
         m_nSpeechSamples(0),
         m_nMaxModemSamples(0),
         m_iSpeech(0),
         m_iModem(0),
         m_speechOut(0),
         m_modIn(0),
         m_levelInNbSamples(480), // 10ms @ 48 kS/s
         m_settingsMutex(QMutex::Recursive)
 {
     setObjectName(m_channelId);
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSink(&m_audioFifo, getInputMessageQueue());
     uint32_t audioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getOutputSampleRate();
     applyAudioSampleRate(audioSampleRate);
     m_audioBuffer.resize(1<<14);
     m_audioBufferFill = 0;
     m_undersampleCount = 0;
     m_magsq = 0.0f;
     m_magsqSum = 0.0f;
     m_magsqPeak = 0.0f;
     m_magsqCount = 0;
     m_simpleAGC.resizeNew(m_modemSampleRate/10, 0.003);
     SSBFilter = new fftfilt(m_lowCutoff / m_modemSampleRate, m_hiCutoff / m_modemSampleRate, ssbFftLen);
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~FreeDVDemod()
FreeDVDemod::~FreeDVDemod () virtual
Definition at line 208 of file freedvdemod.cpp.
References DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo, m_channelizer, m_deviceAPI, m_networkManager, m_threadedChannelizer, networkManagerFinished(), AudioDeviceManager::removeAudioSink(), DeviceAPI::removeChannelSink(), DeviceAPI::removeChannelSinkAPI(), and SSBFilter.
Referenced by FreeDVDemod::MsgConfigureChannelizer::MsgConfigureChannelizer().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_audioFifo);
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete SSBFilter;
 }
Member Function Documentation
applyAudioSampleRate()
void FreeDVDemod::applyAudioSampleRate (int sampleRate) private
Definition at line 539 of file freedvdemod.cpp.
References m_audioFifo, m_audioResampler, m_audioSampleRate, m_settingsMutex, m_speechSampleRate, AudioResampler::setAudioFilters(), AudioResampler::setDecimation(), and AudioFifo::setSize().
Referenced by applySettings(), FreeDVDemod(), and handleMessage().
 {
     qDebug("FreeDVDemod::applyAudioSampleRate: %d", sampleRate);
     m_settingsMutex.lock();
     m_audioFifo.setSize(sampleRate);
     m_audioResampler.setDecimation(sampleRate / m_speechSampleRate);
     m_audioResampler.setAudioFilters(sampleRate, sampleRate, 250, 3300, 4.0f);
     m_settingsMutex.unlock();
     m_audioSampleRate = sampleRate;
 }
applyChannelSettings()
void FreeDVDemod::applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 514 of file freedvdemod.cpp.
References Interpolator::create(), m_hiCutoff, m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_modemSampleRate, m_nco, m_settingsMutex, and NCOF::setFreq().
Referenced by FreeDVDemod(), handleMessage(), and start().
 {
     qDebug() << "FreeDVDemod::applyChannelSettings:"
             << " inputSampleRate: " << inputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if ((m_inputFrequencyOffset != inputFrequencyOffset) ||
         (m_inputSampleRate != inputSampleRate) || force)
     {
         m_nco.setFreq(-inputFrequencyOffset, inputSampleRate);
     }
     if ((m_inputSampleRate != inputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_interpolator.create(16, inputSampleRate, m_hiCutoff * 1.5f, 2.0f);
         m_interpolatorDistanceRemain = 0;
         m_interpolatorDistance = (Real) inputSampleRate / (Real) m_modemSampleRate;
         m_settingsMutex.unlock();
     }
     m_inputSampleRate = inputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applyFreeDVMode()
void FreeDVDemod::applyFreeDVMode (FreeDVDemodSettings::FreeDVMode mode) private
Definition at line 552 of file freedvdemod.cpp.
References DSPConfigureAudio::AudioOutput, Interpolator::create(), FreeDVDemod::MsgConfigureChannelizer::create(), fftfilt::create_filter(), FreeDVDemodSettings::FreeDVMode1600, FreeDVDemodSettings::FreeDVMode2400A, FreeDVDemodSettings::FreeDVMode700C, FreeDVDemodSettings::FreeDVMode700D, FreeDVDemodSettings::FreeDVMode800XA, FreeDVDemodSettings::getHiCutoff(), FreeDVDemodSettings::getLowCutoff(), BasebandSampleSink::getMessageQueueToGUI(), FreeDVDemodSettings::getModSampleRate(), FreeDVDemod::FreeDVStats::init(), FreeDVDemod::FreeDVStats::m_fps, m_freeDV, m_freeDVStats, m_hiCutoff, m_iModem, FreeDVDemodSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_iSpeech, m_levelInNbSamples, m_lowCutoff, m_modemSampleRate, m_modIn, m_nin, m_nMaxModemSamples, m_nSpeechSamples, m_settings, m_settingsMutex, m_simpleAGC, m_speechOut, MessageQueue::push(), SimpleAGC< AvgSize >::resizeNew(), and SSBFilter.
Referenced by applySettings().
 {
     m_hiCutoff = FreeDVDemodSettings::getHiCutoff(mode);
     m_lowCutoff = FreeDVDemodSettings::getLowCutoff(mode);
     uint32_t modemSampleRate = FreeDVDemodSettings::getModSampleRate(mode);
     m_settingsMutex.lock();
     SSBFilter->create_filter(m_lowCutoff / (float) modemSampleRate, m_hiCutoff / (float) modemSampleRate);
     // baseband interpolator
     if (modemSampleRate != m_modemSampleRate)
     {
         MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
                 modemSampleRate, m_settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(channelConfigMsg);
         m_interpolatorDistanceRemain = 0;
         //m_interpolatorConsumed = false;
         m_interpolatorDistance = (Real) m_inputSampleRate / (Real) modemSampleRate;
         m_interpolator.create(16, m_inputSampleRate, m_hiCutoff * 1.5f, 2.0f);
         m_modemSampleRate = modemSampleRate;
         m_simpleAGC.resizeNew(modemSampleRate/10, 0.003);
         m_levelInNbSamples = m_modemSampleRate / 100; // 10ms
         if (getMessageQueueToGUI())
         {
             DSPConfigureAudio *cfg = new DSPConfigureAudio(m_modemSampleRate, DSPConfigureAudio::AudioOutput);
             getMessageQueueToGUI()->push(cfg);
         }
     }
     // FreeDV object
     if (m_freeDV) {
         freedv_close(m_freeDV);
     }
     int fdv_mode = -1;
     switch(mode)
     {
     case FreeDVDemodSettings::FreeDVMode700C:
         fdv_mode = FREEDV_MODE_700C;
         break;
     case FreeDVDemodSettings::FreeDVMode700D:
         fdv_mode = FREEDV_MODE_700D;
         break;
     case FreeDVDemodSettings::FreeDVMode800XA:
         fdv_mode = FREEDV_MODE_800XA;
         break;
     case FreeDVDemodSettings::FreeDVMode1600:
         fdv_mode = FREEDV_MODE_1600;
         break;
     case FreeDVDemodSettings::FreeDVMode2400A:
     default:
         fdv_mode = FREEDV_MODE_2400A;
         break;
     }
     if (fdv_mode == FREEDV_MODE_700D)
     {
         struct freedv_advanced adv;
         adv.interleave_frames = 1;
         m_freeDV = freedv_open_advanced(fdv_mode, &adv);
     }
     else
     {
         m_freeDV = freedv_open(fdv_mode);
     }
     if (m_freeDV)
     {
         freedv_set_test_frames(m_freeDV, 0);
         freedv_set_snr_squelch_thresh(m_freeDV, -100.0);
         freedv_set_squelch_en(m_freeDV, 0);
         freedv_set_clip(m_freeDV, 0);
         freedv_set_ext_vco(m_freeDV, 0);
         freedv_set_sync(m_freeDV, FREEDV_SYNC_MANUAL);
         freedv_set_callback_txt(m_freeDV, nullptr, nullptr, nullptr);
         freedv_set_callback_protocol(m_freeDV, nullptr, nullptr, nullptr);
         freedv_set_callback_data(m_freeDV, nullptr, nullptr, nullptr);
         int nSpeechSamples = freedv_get_n_speech_samples(m_freeDV);
         int nMaxModemSamples = freedv_get_n_max_modem_samples(m_freeDV);
         int Fs = freedv_get_modem_sample_rate(m_freeDV);
         int Rs = freedv_get_modem_symbol_rate(m_freeDV);
         m_freeDVStats.init();
         if (nSpeechSamples != m_nSpeechSamples)
         {
             if (m_speechOut) {
                 delete[] m_speechOut;
             }
             m_speechOut = new int16_t[nSpeechSamples];
             m_nSpeechSamples = nSpeechSamples;
         }
         if (nMaxModemSamples != m_nMaxModemSamples)
         {
             if (m_modIn) {
                 delete[] m_modIn;
             }
             m_modIn = new int16_t[nMaxModemSamples];
             m_nMaxModemSamples = nMaxModemSamples;
         }
         m_iSpeech = 0;
         m_iModem = 0;
         m_nin = freedv_nin(m_freeDV);
         if (m_nin > 0) {
             m_freeDVStats.m_fps = m_modemSampleRate / m_nin;
         }
         qDebug() << "FreeDVMod::applyFreeDVMode:"
                 << " fdv_mode: " << fdv_mode
                 << " m_modemSampleRate: " << m_modemSampleRate
                 << " m_lowCutoff: " << m_lowCutoff
                 << " m_hiCutoff: " << m_hiCutoff
                 << " Fs: " << Fs
                 << " Rs: " << Rs
                 << " m_nSpeechSamples: " << m_nSpeechSamples
                 << " m_nMaxModemSamples: " << m_nMaxModemSamples
                 << " m_nin: " << m_nin
                 << " FPS: " << m_freeDVStats.m_fps;
     }
     m_settingsMutex.unlock();
 }
applySettings()
void FreeDVDemod::applySettings (const FreeDVDemodSettings & settings, bool force = false) private
Definition at line 686 of file freedvdemod.cpp.
References AudioDeviceManager::addAudioSink(), applyAudioSampleRate(), applyFreeDVMode(), DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputDeviceIndex(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), FreeDVDemodSettings::m_agc, m_agcActive, FreeDVDemodSettings::m_audioDeviceName, m_audioFifo, FreeDVDemodSettings::m_audioMute, m_audioMute, m_audioSampleRate, FreeDVDemodSettings::m_freeDVMode, FreeDVDemodSettings::m_inputFrequencyOffset, FreeDVDemodSettings::m_reverseAPIAddress, FreeDVDemodSettings::m_reverseAPIChannelIndex, FreeDVDemodSettings::m_reverseAPIDeviceIndex, FreeDVDemodSettings::m_reverseAPIPort, m_settings, FreeDVDemodSettings::m_spanLog2, m_spanLog2, FreeDVDemodSettings::m_useReverseAPI, FreeDVDemodSettings::m_volume, m_volume, FreeDVDemodSettings::m_volumeIn, and webapiReverseSendSettings().
Referenced by FreeDVDemod(), and handleMessage().
 {
     qDebug() << "FreeDVDemod::applySettings:"
             << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
             << " m_volume: " << settings.m_volume
             << " m_volumeIn: " << settings.m_volumeIn
             << " m_spanLog2: " << settings.m_spanLog2
             << " m_audioMute: " << settings.m_audioMute
             << " m_agcActive: " << settings.m_agc
             << " m_audioDeviceName: " << settings.m_audioDeviceName
             << " m_useReverseAPI: " << settings.m_useReverseAPI
             << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
             << " m_reverseAPIPort: " << settings.m_reverseAPIPort
             << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex
             << " m_reverseAPIChannelIndex: " << settings.m_reverseAPIChannelIndex
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if((m_settings.m_inputFrequencyOffset != settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if ((m_settings.m_volume != settings.m_volume) || force)
     {
         reverseAPIKeys.append("volume");
         m_volume = settings.m_volume;
         m_volume /= 4.0; // for 3276.8
     }
     if ((m_settings.m_volumeIn != settings.m_volumeIn) || force)
     {
         reverseAPIKeys.append("volumeIn");
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force)
     {
         reverseAPIKeys.append("audioDeviceName");
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getOutputDeviceIndex(settings.m_audioDeviceName);
         audioDeviceManager->addAudioSink(&m_audioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getOutputSampleRate(audioDeviceIndex);
         if (m_audioSampleRate != audioSampleRate) {
             applyAudioSampleRate(audioSampleRate);
         }
     }
     if ((m_settings.m_spanLog2 != settings.m_spanLog2) || force) {
         reverseAPIKeys.append("spanLog2");
     }
     if ((m_settings.m_audioMute != settings.m_audioMute) || force) {
         reverseAPIKeys.append("audioMute");
     }
     if ((m_settings.m_agc != settings.m_agc) || force) {
         reverseAPIKeys.append("agc");
     }
     if ((settings.m_freeDVMode != m_settings.m_freeDVMode) || force) {
         applyFreeDVMode(settings.m_freeDVMode);
     }
     m_spanLog2 = settings.m_spanLog2;
     m_audioMute = settings.m_audioMute;
     m_agcActive = settings.m_agc;
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
configure()
void FreeDVDemod::configure (MessageQueue * messageQueue, Real Bandwidth, Real LowCutoff, Real volume, int spanLog2, bool audioBinaural, bool audioFlipChannels, bool dsb, bool audioMute, bool agc, bool agcClamping, int agcTimeLog2, int agcPowerThreshold, int agcThresholdGate)
Definition at line 221 of file freedvdemod.cpp.
References FreeDVDemod::MsgConfigureFreeDVDemodPrivate::create(), and MessageQueue::push().
Referenced by setSampleSink().
 {
     Message* cmd = MsgConfigureFreeDVDemodPrivate::create(
             Bandwidth,
             LowCutoff,
             volume,
             spanLog2,
             audioBinaural,
             audioFlipChannel,
             dsb,
             audioMute,
             agc,
             agcClamping,
             agcTimeLog2,
             agcPowerThreshold,
             agcThresholdGate);
     messageQueue->push(cmd);
 }
deserialize()
bool FreeDVDemod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 787 of file freedvdemod.cpp.
References FreeDVDemod::MsgConfigureFreeDVDemod::create(), FreeDVDemodSettings::deserialize(), BasebandSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and FreeDVDemodSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureFreeDVDemod *msg = MsgConfigureFreeDVDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureFreeDVDemod *msg = MsgConfigureFreeDVDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void FreeDVDemod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 114 of file freedvdemod.h.
 { delete this; }
feed()
void FreeDVDemod::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool positiveOnly) virtual
Implements BasebandSampleSink.
Definition at line 253 of file freedvdemod.cpp.
References Interpolator::decimate(), BasebandSampleSink::feed(), Interpolator::interpolate(), m_audioBuffer, m_audioBufferFill, m_audioFifo, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_nco, m_sampleBuffer, m_sampleSink, m_settingsMutex, m_spanLog2, NCOF::nextIQ(), processOneSample(), and AudioFifo::write().
Referenced by setSampleSink().
 {
     (void) positiveOnly;
     Complex ci;
     fftfilt::cmplx *sideband;
     int n_out;
     m_settingsMutex.lock();
     int decim = 1<<(m_spanLog2 - 1);
     unsigned char decim_mask = decim - 1; // counter LSB bit mask for decimation by 2^(m_scaleLog2 - 1)
     for(SampleVector::const_iterator it = begin; it < end; ++it)
     {
         Complex c(it->real(), it->imag());
         c *= m_nco.nextIQ();
         if (m_interpolatorDistance < 1.0f) // interpolate
         {
             while (!m_interpolator.interpolate(&m_interpolatorDistanceRemain, c, &ci))
             {
                 processOneSample(ci);
                 m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
         }
         else
         {
             if (m_interpolator.decimate(&m_interpolatorDistanceRemain, c, &ci))
             {
                 processOneSample(ci);
                 m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
         }
     }
     uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
     if (res != m_audioBufferFill)
     {
         qDebug("FreeDVDemod::feed: %u/%u tail samples written", res, m_audioBufferFill);
     }
     m_audioBufferFill = 0;
     if (m_sampleSink != 0)
     {
         m_sampleSink->feed(m_sampleBuffer.begin(), m_sampleBuffer.end(), true);
     }
     m_sampleBuffer.clear();
     m_settingsMutex.unlock();
 }
getAudioActive()
bool FreeDVDemod::getAudioActive () const inline
Definition at line 157 of file freedvdemod.h.
References m_audioActive.
Referenced by FreeDVDemodGUI::tick().
 { return m_audioActive; }
getAudioSampleRate()
uint32_t FreeDVDemod::getAudioSampleRate () const inline
Definition at line 154 of file freedvdemod.h.
References m_audioSampleRate.
Referenced by FreeDVDemodGUI::applySettings(), and FreeDVDemodGUI::handleMessage().
 { return m_audioSampleRate; }
getBER()
int FreeDVDemod::getBER () const inline
Definition at line 178 of file freedvdemod.h.
References FreeDVDemod::FreeDVStats::m_ber, and m_freeDVStats.
Referenced by FreeDVDemodGUI::tick().
 { return m_freeDVStats.m_ber; }
getCenterFrequency()
virtual qint64 FreeDVDemod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 139 of file freedvdemod.h.
References deserialize(), FreeDVDemodSettings::m_inputFrequencyOffset, FreeDVDemod::MsgConfigureFreeDVDemod::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getFrequencyOffset()
float FreeDVDemod::getFrequencyOffset () const inline
Definition at line 179 of file freedvdemod.h.
References m_freeDVStats, and FreeDVDemod::FreeDVStats::m_freqOffset.
Referenced by FreeDVDemodGUI::tick().
 { return m_freeDVStats.m_freqOffset; }
getIdentifier()
virtual void FreeDVDemod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 137 of file freedvdemod.h.
 { id = objectName(); }
getMagSq()
double FreeDVDemod::getMagSq () const inline
Definition at line 156 of file freedvdemod.h.
References m_magsq.
 { return m_magsq; }
getMagSqLevels()
void FreeDVDemod::getMagSqLevels (double & avg, double & peak, int & nbSamples) inline
Definition at line 159 of file freedvdemod.h.
References getSNRLevels(), FreeDVDemod::MagSqLevelsStore::m_magsq, m_magsq, m_magsqCount, m_magSqLevelStore, FreeDVDemod::MagSqLevelsStore::m_magsqPeak, m_magsqPeak, and m_magsqSum.
Referenced by FreeDVDemodGUI::tick(), and webapiFormatChannelReport().
     {
         if (m_magsqCount > 0)
         {
             m_magsq = m_magsqSum / m_magsqCount;
             m_magSqLevelStore.m_magsq = m_magsq;
             m_magSqLevelStore.m_magsqPeak = m_magsqPeak;
         }
         avg = m_magSqLevelStore.m_magsq;
         peak = m_magSqLevelStore.m_magsqPeak;
         nbSamples = m_magsqCount == 0 ? 1 : m_magsqCount;
         m_magsqSum = 0.0f;
         m_magsqPeak = 0.0f;
         m_magsqCount = 0;
     }
getModemSampleRate()
uint32_t FreeDVDemod::getModemSampleRate () const inline
Definition at line 155 of file freedvdemod.h.
References m_modemSampleRate.
Referenced by FreeDVDemodGUI::displayBandwidths().
 { return m_modemSampleRate; }
getNbSinkStreams()
virtual int FreeDVDemod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 144 of file freedvdemod.h.
 { return 1; }
getNbSourceStreams()
virtual int FreeDVDemod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 145 of file freedvdemod.h.
 { return 0; }
getSNRLevels()
void FreeDVDemod::getSNRLevels (double & avg, double & peak, int & nbSamples)
Definition at line 765 of file freedvdemod.cpp.
References CalcDb::dbPower(), m_freeDVSNR, FreeDVDemod::FreeDVSNR::m_n, FreeDVDemod::FreeDVSNR::m_peak, FreeDVDemod::FreeDVSNR::m_reset, and FreeDVDemod::FreeDVSNR::m_sum.
Referenced by getMagSqLevels(), and FreeDVDemodGUI::tick().
 {
     if (m_freeDVSNR.m_n > 0)
     {
         avg = CalcDb::dbPower(m_freeDVSNR.m_sum / m_freeDVSNR.m_n);
         peak = m_freeDVSNR.m_peak;
         nbSamples = m_freeDVSNR.m_n;
         m_freeDVSNR.m_reset = true;
     }
     else
     {
         avg = 0.0;
         peak = 0.0;
         nbSamples = 1;
     }
 }
getStreamCenterFrequency()
virtual qint64 FreeDVDemod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 147 of file freedvdemod.h.
References FreeDVDemodSettings::m_inputFrequencyOffset, and FreeDVDemod::MsgConfigureFreeDVDemod::m_settings.
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void FreeDVDemod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 138 of file freedvdemod.h.
References FreeDVDemod::MsgConfigureFreeDVDemod::m_settings, and FreeDVDemodSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool FreeDVDemod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 372 of file freedvdemod.cpp.
References applyAudioSampleRate(), applyChannelSettings(), applySettings(), DownChannelizer::configure(), FreeDVDemod::MsgConfigureChannelizer::getCenterFrequency(), FreeDVDemod::MsgConfigureFreeDVDemod::getForce(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSink::getInputMessageQueue(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), FreeDVDemod::MsgConfigureChannelizer::getSampleRate(), DSPConfigureAudio::getSampleRate(), FreeDVDemod::MsgConfigureFreeDVDemod::getSettings(), BasebandSampleSink::MsgThreadedSink::getThread(), BasebandSampleSink::handleMessage(), m_audioSampleRate, m_channelizer, m_freeDV, m_sampleSink, m_settingsMutex, and Message::match().
Referenced by setSampleSink().
 {
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& notif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         qDebug("FreeDVDemod::handleMessage: MsgChannelizerNotification: m_sampleRate");
         applyChannelSettings(notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "FreeDVDemod::handleMessage: MsgConfigureChannelizer: sampleRate: " << cfg.getSampleRate()
                 << " centerFrequency: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureFreeDVDemod::match(cmd))
     {
         MsgConfigureFreeDVDemod& cfg = (MsgConfigureFreeDVDemod&) cmd;
         qDebug("FreeDVDemod::handleMessage: MsgConfigureFreeDVDemod");
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgResyncFreeDVDemod::match(cmd))
     {
         qDebug("FreeDVDemod::handleMessage: MsgResyncFreeDVDemod");
         m_settingsMutex.lock();
         freedv_set_sync(m_freeDV, FREEDV_SYNC_UNSYNC);
         m_settingsMutex.unlock();
         return true;
     }
     else if (BasebandSampleSink::MsgThreadedSink::match(cmd))
     {
         BasebandSampleSink::MsgThreadedSink& cfg = (BasebandSampleSink::MsgThreadedSink&) cmd;
         const QThread *thread = cfg.getThread();
         qDebug("FreeDVDemod::handleMessage: BasebandSampleSink::MsgThreadedSink: %p", thread);
         return true;
     }
     else if (DSPConfigureAudio::match(cmd))
     {
         DSPConfigureAudio& cfg = (DSPConfigureAudio&) cmd;
         uint32_t sampleRate = cfg.getSampleRate();
         qDebug() << "FreeDVDemod::handleMessage: DSPConfigureAudio:"
                 << " sampleRate: " << sampleRate;
         if (sampleRate != m_audioSampleRate) {
             applyAudioSampleRate(sampleRate);
         }
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         if(m_sampleSink != 0)
         {
            return m_sampleSink->handleMessage(cmd);
         }
         else
         {
             return false;
         }
     }
 }
isSync()
bool FreeDVDemod::isSync () const inline
Definition at line 180 of file freedvdemod.h.
References m_freeDVStats, FreeDVDemod::FreeDVStats::m_sync, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
Referenced by FreeDVDemodGUI::tick().
 { return m_freeDVStats.m_sync; }
levelInChanged
void FreeDVDemod::levelInChanged (qreal rmsLevel, qreal peakLevel, int numSamples) signal
Level changed
Parameters
rmsLevel RMS level in range 0.0 - 1.0
peakLevel Peak level in range 0.0 - 1.0
numSamples Number of audio samples analyzed
Referenced by pushSampleToDV().
networkManagerFinished
void FreeDVDemod::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 1017 of file freedvdemod.cpp.
Referenced by FreeDVDemod(), and ~FreeDVDemod().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "FreeDVDemod::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("FreeDVDemod::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
processOneSample()
void FreeDVDemod::processOneSample (Complex & ci) private
Definition at line 307 of file freedvdemod.cpp.
References SimpleAGC< AvgSize >::feed(), SimpleAGC< AvgSize >::getValue(), i, m_agcActive, m_magsq, m_magsqCount, m_magsqPeak, m_magsqSum, m_sampleBuffer, m_settings, m_simpleAGC, m_spanLog2, m_sum, m_undersampleCount, FreeDVDemodSettings::m_volumeIn, pushSampleToDV(), fftfilt::runSSB(), SDR_RX_SCALED, and SSBFilter.
Referenced by feed().
 {
     fftfilt::cmplx *sideband;
     int n_out = 0;
     int decim = 1<<(m_spanLog2 - 1);
     unsigned char decim_mask = decim - 1; // counter LSB bit mask for decimation by 2^(m_scaleLog2 - 1)
     n_out = SSBFilter->runSSB(ci, &sideband, true); // always USB side
     for (int i = 0; i < n_out; i++)
     {
         // Downsample by 2^(m_scaleLog2 - 1) for SSB band spectrum display
         // smart decimation with bit gain using float arithmetic (23 bits significand)
         m_sum += sideband[i];
         if (!(m_undersampleCount++ & decim_mask))
         {
             Real avgr = m_sum.real() / decim;
             Real avgi = m_sum.imag() / decim;
             m_magsq = (avgr * avgr + avgi * avgi) / (SDR_RX_SCALED*SDR_RX_SCALED);
             m_magsqSum += m_magsq;
             if (m_magsq > m_magsqPeak)
             {
                 m_magsqPeak = m_magsq;
             }
             m_magsqCount++;
             m_sampleBuffer.push_back(Sample(avgr, avgi));
             m_sum.real(0.0);
             m_sum.imag(0.0);
         }
         // fftfilt::cmplx z = sideband[i];
         // Real demod = (z.real() + z.imag()) * 0.7;
         Real demod = sideband[i].real(); // works as good
         if (m_agcActive)
         {
             m_simpleAGC.feed(demod);
             demod *= (m_settings.m_volumeIn * 3276.8f) / m_simpleAGC.getValue(); // provision for peak to average ratio (here 10) compensated by m_volumeIn
             // if (i == 0) {
             //     qDebug("FreeDVDemod::feed: m_simpleAGC: %f", m_simpleAGC.getValue());
             // }
         }
         else
         {
             demod *= m_settings.m_volumeIn;
         }
         pushSampleToDV((qint16) demod);
     }
 }
pushSampleToAudio()
void FreeDVDemod::pushSampleToAudio (int16_t sample) private
Definition at line 496 of file freedvdemod.cpp.
References m_audioBuffer, m_audioBufferFill, m_audioFifo, m_volume, and AudioFifo::write().
Referenced by pushSampleToDV().
 {
     m_audioBuffer[m_audioBufferFill].l = sample * m_volume;
     m_audioBuffer[m_audioBufferFill].r = sample * m_volume;
     ++m_audioBufferFill;
     if (m_audioBufferFill >= m_audioBuffer.size())
     {
         uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
         if (res != m_audioBufferFill) {
             qDebug("FreeDVDemod::pushSampleToAudio: %u/%u samples written", res, m_audioBufferFill);
         }
         m_audioBufferFill = 0;
     }
 }
pushSampleToDV()
void FreeDVDemod::pushSampleToDV (int16_t sample) private
Definition at line 450 of file freedvdemod.cpp.
References FreeDVDemod::FreeDVSNR::accumulate(), FreeDVDemod::LevelRMS::accumulate(), FreeDVDemod::FreeDVStats::collect(), AudioResampler::getDecimation(), i, levelInChanged(), FreeDVDemodSettings::m_audioMute, m_audioResampler, m_freeDV, m_freeDVSNR, m_freeDVStats, m_iModem, m_iSpeech, m_levelIn, m_levelInNbSamples, m_modIn, FreeDVDemod::LevelRMS::m_n, m_nin, FreeDVDemod::LevelRMS::m_peak, FreeDVDemod::LevelRMS::m_reset, m_settings, FreeDVDemod::FreeDVStats::m_snrEst, m_speechOut, FreeDVDemod::LevelRMS::m_sum, pushSampleToAudio(), sqrt(), and AudioResampler::upSample().
Referenced by processOneSample().
 {
     qint16 audioSample;
     if (m_levelIn.m_n >= m_levelInNbSamples)
     {
         qreal rmsLevel = sqrt(m_levelIn.m_sum / m_levelInNbSamples);
         // qDebug("FreeDVDemod::pushSampleToDV: rmsLevel: %f m_peak: %f m_levelInNbSamples: %d",
         //     rmsLevel, m_levelIn.m_peak, m_levelInNbSamples);
         emit levelInChanged(rmsLevel, m_levelIn.m_peak, m_levelInNbSamples);
         m_levelIn.m_reset = true;
     }
     m_levelIn.accumulate(sample/29491.2f); // scale on 90% (0.9 * 32768.0)
     if (m_iModem == m_nin)
     {
         int nout = freedv_rx(m_freeDV, m_speechOut, m_modIn);
         m_freeDVStats.collect(m_freeDV);
         m_freeDVSNR.accumulate(m_freeDVStats.m_snrEst);
         if (m_settings.m_audioMute)
         {
             for (uint32_t i = 0; i < nout * m_audioResampler.getDecimation(); i++) {
                 pushSampleToAudio(0);
             }
         }
         else
         {
             for (int i = 0; i < nout; i++)
             {
                 while (!m_audioResampler.upSample(m_speechOut[i], audioSample)) {
                     pushSampleToAudio(audioSample);
                 }
                 pushSampleToAudio(audioSample);
             }
         }
         m_iModem = 0;
         m_iSpeech = 0;
     }
     m_modIn[m_iModem++] = sample;
 }
serialize()
QByteArray FreeDVDemod::serialize () const virtual
Implements ChannelAPI.
Definition at line 782 of file freedvdemod.cpp.
References m_settings, and FreeDVDemodSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
setSampleSink()
void FreeDVDemod::setSampleSink (BasebandSampleSink * sampleSink) inline
Definition at line 115 of file freedvdemod.h.
References configure(), feed(), handleMessage(), m_sampleSink, start(), and stop().
Referenced by FreeDVDemodGUI::FreeDVDemodGUI().
 { m_sampleSink = sampleSink; }
start()
void FreeDVDemod::start () virtual
Implements BasebandSampleSink.
Definition at line 363 of file freedvdemod.cpp.
References applyChannelSettings(), m_inputFrequencyOffset, and m_inputSampleRate.
Referenced by setSampleSink().
 {
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void FreeDVDemod::stop () virtual
Implements BasebandSampleSink.
Definition at line 368 of file freedvdemod.cpp.
Referenced by setSampleSink().
 {
 }
webapiFormatChannelReport()
void FreeDVDemod::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 943 of file freedvdemod.cpp.
References CalcDb::dbPower(), SWGSDRangel::SWGChannelReport::getFreeDvDemodReport(), getMagSqLevels(), m_audioActive, m_audioSampleRate, m_inputSampleRate, SWGSDRangel::SWGFreeDVDemodReport::setAudioSampleRate(), SWGSDRangel::SWGFreeDVDemodReport::setChannelPowerDb(), SWGSDRangel::SWGFreeDVDemodReport::setChannelSampleRate(), and SWGSDRangel::SWGFreeDVDemodReport::setSquelch().
Referenced by webapiReportGet().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     response.getFreeDvDemodReport()->setChannelPowerDb(CalcDb::dbPower(magsqAvg));
     response.getFreeDvDemodReport()->setSquelch(m_audioActive ? 1 : 0);
     response.getFreeDvDemodReport()->setAudioSampleRate(m_audioSampleRate);
     response.getFreeDvDemodReport()->setChannelSampleRate(m_inputSampleRate);
 }
webapiFormatChannelSettings()
void FreeDVDemod::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const FreeDVDemodSettings & settings) private
Definition at line 906 of file freedvdemod.cpp.
References SWGSDRangel::SWGFreeDVDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGChannelSettings::getFreeDvDemodSettings(), SWGSDRangel::SWGFreeDVDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGFreeDVDemodSettings::getTitle(), FreeDVDemodSettings::m_agc, FreeDVDemodSettings::m_audioDeviceName, FreeDVDemodSettings::m_audioMute, FreeDVDemodSettings::m_freeDVMode, FreeDVDemodSettings::m_inputFrequencyOffset, FreeDVDemodSettings::m_reverseAPIAddress, FreeDVDemodSettings::m_reverseAPIChannelIndex, FreeDVDemodSettings::m_reverseAPIDeviceIndex, FreeDVDemodSettings::m_reverseAPIPort, FreeDVDemodSettings::m_rgbColor, FreeDVDemodSettings::m_spanLog2, FreeDVDemodSettings::m_title, FreeDVDemodSettings::m_useReverseAPI, FreeDVDemodSettings::m_volume, FreeDVDemodSettings::m_volumeIn, SWGSDRangel::SWGFreeDVDemodSettings::setAgc(), SWGSDRangel::SWGFreeDVDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGFreeDVDemodSettings::setAudioMute(), SWGSDRangel::SWGFreeDVDemodSettings::setFreeDvMode(), SWGSDRangel::SWGFreeDVDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGFreeDVDemodSettings::setReverseApiAddress(), SWGSDRangel::SWGFreeDVDemodSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGFreeDVDemodSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGFreeDVDemodSettings::setReverseApiPort(), SWGSDRangel::SWGFreeDVDemodSettings::setRgbColor(), SWGSDRangel::SWGFreeDVDemodSettings::setSpanLog2(), SWGSDRangel::SWGFreeDVDemodSettings::setTitle(), SWGSDRangel::SWGFreeDVDemodSettings::setUseReverseApi(), SWGSDRangel::SWGFreeDVDemodSettings::setVolume(), and SWGSDRangel::SWGFreeDVDemodSettings::setVolumeIn().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getFreeDvDemodSettings()->setAudioMute(settings.m_audioMute ? 1 : 0);
     response.getFreeDvDemodSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getFreeDvDemodSettings()->setVolume(settings.m_volume);
     response.getFreeDvDemodSettings()->setVolumeIn(settings.m_volumeIn);
     response.getFreeDvDemodSettings()->setSpanLog2(settings.m_spanLog2);
     response.getFreeDvDemodSettings()->setAudioMute(settings.m_audioMute ? 1 : 0);
     response.getFreeDvDemodSettings()->setAgc(settings.m_agc ? 1 : 0);
     response.getFreeDvDemodSettings()->setRgbColor(settings.m_rgbColor);
     response.getFreeDvDemodSettings()->setFreeDvMode((int) settings.m_freeDVMode);
     if (response.getFreeDvDemodSettings()->getTitle()) {
         *response.getFreeDvDemodSettings()->getTitle() = settings.m_title;
     } else {
         response.getFreeDvDemodSettings()->setTitle(new QString(settings.m_title));
     }
     if (response.getFreeDvDemodSettings()->getAudioDeviceName()) {
         *response.getFreeDvDemodSettings()->getAudioDeviceName() = settings.m_audioDeviceName;
     } else {
         response.getFreeDvDemodSettings()->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     response.getFreeDvDemodSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getFreeDvDemodSettings()->getReverseApiAddress()) {
         *response.getFreeDvDemodSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getFreeDvDemodSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getFreeDvDemodSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getFreeDvDemodSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getFreeDvDemodSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int FreeDVDemod::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 895 of file freedvdemod.cpp.
References SWGSDRangel::SWGChannelReport::getFreeDvDemodReport(), SWGSDRangel::SWGFreeDVDemodReport::init(), SWGSDRangel::SWGChannelReport::setFreeDvDemodReport(), and webapiFormatChannelReport().
Referenced by isSync().
 {
     (void) errorMessage;
     response.setFreeDvDemodReport(new SWGSDRangel::SWGFreeDVDemodReport());
     response.getFreeDvDemodReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendSettings()
void FreeDVDemod::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const FreeDVDemodSettings & settings, bool force) private
Definition at line 955 of file freedvdemod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), ChannelAPI::getDeviceSetIndex(), SWGSDRangel::SWGChannelSettings::getFreeDvDemodSettings(), ChannelAPI::getIndexInDeviceSet(), FreeDVDemodSettings::m_agc, FreeDVDemodSettings::m_audioDeviceName, FreeDVDemodSettings::m_audioMute, FreeDVDemodSettings::m_freeDVMode, FreeDVDemodSettings::m_inputFrequencyOffset, m_networkManager, m_networkRequest, FreeDVDemodSettings::m_reverseAPIAddress, FreeDVDemodSettings::m_reverseAPIChannelIndex, FreeDVDemodSettings::m_reverseAPIDeviceIndex, FreeDVDemodSettings::m_reverseAPIPort, FreeDVDemodSettings::m_rgbColor, FreeDVDemodSettings::m_spanLog2, FreeDVDemodSettings::m_title, FreeDVDemodSettings::m_volume, FreeDVDemodSettings::m_volumeIn, SWGSDRangel::SWGFreeDVDemodSettings::setAgc(), SWGSDRangel::SWGFreeDVDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGFreeDVDemodSettings::setAudioMute(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGChannelSettings::setFreeDvDemodSettings(), SWGSDRangel::SWGFreeDVDemodSettings::setFreeDvMode(), SWGSDRangel::SWGFreeDVDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGFreeDVDemodSettings::setRgbColor(), SWGSDRangel::SWGFreeDVDemodSettings::setSpanLog2(), SWGSDRangel::SWGFreeDVDemodSettings::setTitle(), SWGSDRangel::SWGFreeDVDemodSettings::setVolume(), and SWGSDRangel::SWGFreeDVDemodSettings::setVolumeIn().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(0); // single sink (Rx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("SSBDemod"));
     swgChannelSettings->setFreeDvDemodSettings(new SWGSDRangel::SWGFreeDVDemodSettings());
     SWGSDRangel::SWGFreeDVDemodSettings *swgFreeDVDemodSettings = swgChannelSettings->getFreeDvDemodSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgFreeDVDemodSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("freeDVMode") || force) {
         swgFreeDVDemodSettings->setFreeDvMode((int) settings.m_freeDVMode);
     }
     if (channelSettingsKeys.contains("volume") || force) {
         swgFreeDVDemodSettings->setVolume(settings.m_volume);
     }
     if (channelSettingsKeys.contains("volumeIn") || force) {
         swgFreeDVDemodSettings->setVolumeIn(settings.m_volumeIn);
     }
     if (channelSettingsKeys.contains("spanLog2") || force) {
         swgFreeDVDemodSettings->setSpanLog2(settings.m_spanLog2);
     }
     if (channelSettingsKeys.contains("audioMute") || force) {
         swgFreeDVDemodSettings->setAudioMute(settings.m_audioMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("agc") || force) {
         swgFreeDVDemodSettings->setAgc(settings.m_agc ? 1 : 0);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgFreeDVDemodSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgFreeDVDemodSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("audioDeviceName") || force) {
         swgFreeDVDemodSettings->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int FreeDVDemod::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 804 of file freedvdemod.cpp.
References SWGSDRangel::SWGChannelSettings::getFreeDvDemodSettings(), SWGSDRangel::SWGFreeDVDemodSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setFreeDvDemodSettings(), and webapiFormatChannelSettings().
Referenced by isSync().
 {
     (void) errorMessage;
     response.setFreeDvDemodSettings(new SWGSDRangel::SWGFreeDVDemodSettings());
     response.getFreeDvDemodSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int FreeDVDemod::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 815 of file freedvdemod.cpp.
References FreeDVDemod::MsgConfigureFreeDVDemod::create(), FreeDVDemod::MsgConfigureChannelizer::create(), SWGSDRangel::SWGFreeDVDemodSettings::getAgc(), SWGSDRangel::SWGFreeDVDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGFreeDVDemodSettings::getAudioMute(), SWGSDRangel::SWGChannelSettings::getFreeDvDemodSettings(), SWGSDRangel::SWGFreeDVDemodSettings::getFreeDvMode(), SWGSDRangel::SWGFreeDVDemodSettings::getInputFrequencyOffset(), SWGSDRangel::SWGFreeDVDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGFreeDVDemodSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGFreeDVDemodSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGFreeDVDemodSettings::getReverseApiPort(), SWGSDRangel::SWGFreeDVDemodSettings::getRgbColor(), SWGSDRangel::SWGFreeDVDemodSettings::getSpanLog2(), SWGSDRangel::SWGFreeDVDemodSettings::getTitle(), SWGSDRangel::SWGFreeDVDemodSettings::getUseReverseApi(), SWGSDRangel::SWGFreeDVDemodSettings::getVolume(), SWGSDRangel::SWGFreeDVDemodSettings::getVolumeIn(), FreeDVDemodSettings::m_agc, FreeDVDemodSettings::m_audioDeviceName, FreeDVDemodSettings::m_audioMute, FreeDVDemodSettings::m_freeDVMode, BasebandSampleSink::m_guiMessageQueue, FreeDVDemodSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, m_modemSampleRate, FreeDVDemodSettings::m_reverseAPIAddress, FreeDVDemodSettings::m_reverseAPIChannelIndex, FreeDVDemodSettings::m_reverseAPIDeviceIndex, FreeDVDemodSettings::m_reverseAPIPort, FreeDVDemodSettings::m_rgbColor, m_settings, FreeDVDemodSettings::m_spanLog2, FreeDVDemodSettings::m_title, FreeDVDemodSettings::m_useReverseAPI, FreeDVDemodSettings::m_volume, FreeDVDemodSettings::m_volumeIn, MessageQueue::push(), and webapiFormatChannelSettings().
Referenced by isSync().
 {
     (void) errorMessage;
     FreeDVDemodSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getFreeDvDemodSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("freeDVMode")) {
         settings.m_freeDVMode = (FreeDVDemodSettings::FreeDVMode) response.getFreeDvDemodSettings()->getFreeDvMode();
     }
     if (channelSettingsKeys.contains("volume")) {
         settings.m_volume = response.getFreeDvDemodSettings()->getVolume();
     }
     if (channelSettingsKeys.contains("volumeIn")) {
         settings.m_volumeIn = response.getFreeDvDemodSettings()->getVolumeIn();
     }
     if (channelSettingsKeys.contains("spanLog2")) {
         settings.m_spanLog2 = response.getFreeDvDemodSettings()->getSpanLog2();
     }
     if (channelSettingsKeys.contains("audioMute")) {
         settings.m_audioMute = response.getFreeDvDemodSettings()->getAudioMute() != 0;
     }
     if (channelSettingsKeys.contains("agc")) {
         settings.m_agc = response.getFreeDvDemodSettings()->getAgc() != 0;
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getFreeDvDemodSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getFreeDvDemodSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("audioDeviceName")) {
         settings.m_audioDeviceName = *response.getFreeDvDemodSettings()->getAudioDeviceName();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getFreeDvDemodSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getFreeDvDemodSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getFreeDvDemodSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getFreeDvDemodSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getFreeDvDemodSettings()->getReverseApiChannelIndex();
     }
     if (frequencyOffsetChanged)
     {
         MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
                 m_modemSampleRate, settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(channelConfigMsg);
     }
     MsgConfigureFreeDVDemod *msg = MsgConfigureFreeDVDemod::create(settings, force);
     m_inputMessageQueue.push(msg);
     qDebug("FreeDVDemod::webapiSettingsPutPatch: forward to GUI: %p", m_guiMessageQueue);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureFreeDVDemod *msgToGUI = MsgConfigureFreeDVDemod::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_agcActive
bool FreeDVDemod::m_agcActive private
Definition at line 376 of file freedvdemod.h.
Referenced by applySettings(), FreeDVDemod(), and processOneSample().
m_audioActive
bool FreeDVDemod::m_audioActive private
True if an audio signal is produced (no AGC or AGC and above threshold)
Definition at line 378 of file freedvdemod.h.
Referenced by FreeDVDemod(), getAudioActive(), and webapiFormatChannelReport().
m_audioBuffer
AudioVector FreeDVDemod::m_audioBuffer private
Definition at line 389 of file freedvdemod.h.
Referenced by feed(), FreeDVDemod(), and pushSampleToAudio().
m_audioBufferFill
uint FreeDVDemod::m_audioBufferFill private
Definition at line 390 of file freedvdemod.h.
Referenced by feed(), FreeDVDemod(), and pushSampleToAudio().
m_audioFifo
AudioFifo FreeDVDemod::m_audioFifo private
Definition at line 391 of file freedvdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), feed(), FreeDVDemod(), pushSampleToAudio(), and ~FreeDVDemod().
m_audioMute
bool FreeDVDemod::m_audioMute private
Definition at line 369 of file freedvdemod.h.
Referenced by applySettings(), FreeDVDemod(), and FreeDVDemod::MsgConfigureFreeDVDemodPrivate::getAudioMute().
m_audioResampler
AudioResampler FreeDVDemod::m_audioResampler private
Definition at line 404 of file freedvdemod.h.
Referenced by applyAudioSampleRate(), and pushSampleToDV().
m_audioSampleRate
uint32_t FreeDVDemod::m_audioSampleRate private
Definition at line 367 of file freedvdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), getAudioSampleRate(), handleMessage(), and webapiFormatChannelReport().
m_channelId
const QString FreeDVDemod::m_channelId = "FreeDVDemod" static
Definition at line 197 of file freedvdemod.h.
Referenced by FreeDVDemod(), and FreeDVPlugin::initPlugin().
m_channelIdURI
const QString FreeDVDemod::m_channelIdURI = "sdrangel.channel.freedvdemod" static
Definition at line 196 of file freedvdemod.h.
Referenced by FreeDVDemodGUI::FreeDVDemodGUI(), and FreeDVPlugin::initPlugin().
m_channelizer
DownChannelizer* FreeDVDemod::m_channelizer private
Definition at line 355 of file freedvdemod.h.
Referenced by FreeDVDemod(), handleMessage(), and ~FreeDVDemod().
m_deviceAPI
DeviceAPI* FreeDVDemod::m_deviceAPI private
Definition at line 353 of file freedvdemod.h.
Referenced by FreeDVDemod(), and ~FreeDVDemod().
m_freeDV
struct freedv* FreeDVDemod::m_freeDV private
Definition at line 396 of file freedvdemod.h.
Referenced by applyFreeDVMode(), FreeDVDemod(), handleMessage(), and pushSampleToDV().
m_freeDVSNR
FreeDVSNR FreeDVDemod::m_freeDVSNR private
Definition at line 406 of file freedvdemod.h.
Referenced by getSNRLevels(), and pushSampleToDV().
m_freeDVStats
FreeDVStats FreeDVDemod::m_freeDVStats private
Definition at line 405 of file freedvdemod.h.
Referenced by applyFreeDVMode(), getBER(), getFrequencyOffset(), isSync(), and pushSampleToDV().
m_hiCutoff
Real FreeDVDemod::m_hiCutoff private
Definition at line 358 of file freedvdemod.h.
Referenced by applyChannelSettings(), applyFreeDVMode(), and FreeDVDemod().
m_iModem
int FreeDVDemod::m_iModem private
Definition at line 401 of file freedvdemod.h.
Referenced by applyFreeDVMode(), FreeDVDemod(), and pushSampleToDV().
m_inputFrequencyOffset
int FreeDVDemod::m_inputFrequencyOffset private
Definition at line 368 of file freedvdemod.h.
Referenced by applyChannelSettings(), FreeDVDemod(), and start().
m_inputSampleRate
int FreeDVDemod::m_inputSampleRate private
Definition at line 364 of file freedvdemod.h.
Referenced by applyChannelSettings(), applyFreeDVMode(), FreeDVDemod(), start(), and webapiFormatChannelReport().
m_interpolator
Interpolator FreeDVDemod::m_interpolator private
Definition at line 381 of file freedvdemod.h.
Referenced by applyChannelSettings(), applyFreeDVMode(), and feed().
m_interpolatorDistance
Real FreeDVDemod::m_interpolatorDistance private
Definition at line 382 of file freedvdemod.h.
Referenced by applyChannelSettings(), applyFreeDVMode(), and feed().
m_interpolatorDistanceRemain
Real FreeDVDemod::m_interpolatorDistanceRemain private
Definition at line 383 of file freedvdemod.h.
Referenced by applyChannelSettings(), applyFreeDVMode(), and feed().
m_iSpeech
int FreeDVDemod::m_iSpeech private
Definition at line 400 of file freedvdemod.h.
Referenced by applyFreeDVMode(), FreeDVDemod(), and pushSampleToDV().
m_levelIn
LevelRMS FreeDVDemod::m_levelIn private
Definition at line 407 of file freedvdemod.h.
Referenced by pushSampleToDV().
m_levelInNbSamples
int FreeDVDemod::m_levelInNbSamples private
Definition at line 408 of file freedvdemod.h.
Referenced by applyFreeDVMode(), FreeDVDemod(), and pushSampleToDV().
m_lowCutoff
Real FreeDVDemod::m_lowCutoff private
Definition at line 359 of file freedvdemod.h.
Referenced by applyFreeDVMode(), and FreeDVDemod().
m_magsq
double FreeDVDemod::m_magsq private
Definition at line 370 of file freedvdemod.h.
Referenced by FreeDVDemod(), getMagSq(), getMagSqLevels(), and processOneSample().
m_magsqCount
int FreeDVDemod::m_magsqCount private
Definition at line 373 of file freedvdemod.h.
Referenced by FreeDVDemod(), getMagSqLevels(), and processOneSample().
m_magSqLevelStore
MagSqLevelsStore FreeDVDemod::m_magSqLevelStore private
Definition at line 374 of file freedvdemod.h.
Referenced by getMagSqLevels().
m_magsqPeak
double FreeDVDemod::m_magsqPeak private
Definition at line 372 of file freedvdemod.h.
Referenced by FreeDVDemod(), getMagSqLevels(), and processOneSample().
m_magsqSum
double FreeDVDemod::m_magsqSum private
Definition at line 371 of file freedvdemod.h.
Referenced by FreeDVDemod(), getMagSqLevels(), and processOneSample().
m_modemSampleRate
uint32_t FreeDVDemod::m_modemSampleRate private
Definition at line 365 of file freedvdemod.h.
Referenced by applyChannelSettings(), applyFreeDVMode(), FreeDVDemod(), getModemSampleRate(), and webapiSettingsPutPatch().
m_modIn
int16_t* FreeDVDemod::m_modIn private
Definition at line 403 of file freedvdemod.h.
Referenced by applyFreeDVMode(), FreeDVDemod(), and pushSampleToDV().
m_nco
NCOF FreeDVDemod::m_nco private
Definition at line 380 of file freedvdemod.h.
Referenced by applyChannelSettings(), and feed().
m_networkManager
QNetworkAccessManager* FreeDVDemod::m_networkManager private
Definition at line 393 of file freedvdemod.h.
Referenced by FreeDVDemod(), webapiReverseSendSettings(), and ~FreeDVDemod().
m_networkRequest
QNetworkRequest FreeDVDemod::m_networkRequest private
Definition at line 394 of file freedvdemod.h.
Referenced by webapiReverseSendSettings().
m_nin
int FreeDVDemod::m_nin private
Definition at line 399 of file freedvdemod.h.
Referenced by applyFreeDVMode(), and pushSampleToDV().
m_nMaxModemSamples
int FreeDVDemod::m_nMaxModemSamples private
Definition at line 398 of file freedvdemod.h.
Referenced by applyFreeDVMode(), and FreeDVDemod().
m_nSpeechSamples
int FreeDVDemod::m_nSpeechSamples private
Definition at line 397 of file freedvdemod.h.
Referenced by applyFreeDVMode(), and FreeDVDemod().
m_sampleBuffer
SampleVector FreeDVDemod::m_sampleBuffer private
Definition at line 387 of file freedvdemod.h.
Referenced by feed(), and processOneSample().
m_sampleSink
BasebandSampleSink* FreeDVDemod::m_sampleSink private
Definition at line 386 of file freedvdemod.h.
Referenced by feed(), FreeDVDemod(), handleMessage(), and setSampleSink().
m_settings
FreeDVDemodSettings FreeDVDemod::m_settings private
Definition at line 356 of file freedvdemod.h.
Referenced by applyFreeDVMode(), applySettings(), deserialize(), FreeDVDemod(), processOneSample(), pushSampleToDV(), serialize(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex FreeDVDemod::m_settingsMutex private
Definition at line 410 of file freedvdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applyFreeDVMode(), feed(), FreeDVDemod(), and handleMessage().
m_simpleAGC
SimpleAGC<4800> FreeDVDemod::m_simpleAGC private
Definition at line 375 of file freedvdemod.h.
Referenced by applyFreeDVMode(), FreeDVDemod(), and processOneSample().
m_spanLog2
int FreeDVDemod::m_spanLog2 private
Definition at line 361 of file freedvdemod.h.
Referenced by applySettings(), feed(), FreeDVDemod::MsgConfigureFreeDVDemodPrivate::getSpanLog2(), and processOneSample().
m_speechOut
int16_t* FreeDVDemod::m_speechOut private
Definition at line 402 of file freedvdemod.h.
Referenced by applyFreeDVMode(), FreeDVDemod(), and pushSampleToDV().
m_speechSampleRate
uint32_t FreeDVDemod::m_speechSampleRate private
Definition at line 366 of file freedvdemod.h.
Referenced by applyAudioSampleRate(), and FreeDVDemod().
m_squelchDelayLine
DoubleBufferFIFO<fftfilt::cmplx> FreeDVDemod::m_squelchDelayLine private
Definition at line 377 of file freedvdemod.h.
Referenced by FreeDVDemod().
m_sum
fftfilt::cmplx FreeDVDemod::m_sum private
Definition at line 362 of file freedvdemod.h.
Referenced by FreeDVDemod::FreeDVSNR::accumulate(), FreeDVDemod::LevelRMS::accumulate(), FreeDVDemod::FreeDVSNR::FreeDVSNR(), FreeDVDemod::LevelRMS::LevelRMS(), and processOneSample().
m_threadedChannelizer
ThreadedBasebandSampleSink* FreeDVDemod::m_threadedChannelizer private
Definition at line 354 of file freedvdemod.h.
Referenced by FreeDVDemod(), and ~FreeDVDemod().
m_undersampleCount
int FreeDVDemod::m_undersampleCount private
Definition at line 363 of file freedvdemod.h.
Referenced by FreeDVDemod(), and processOneSample().
m_volume
Real FreeDVDemod::m_volume private
Definition at line 360 of file freedvdemod.h.
Referenced by applySettings(), FreeDVDemod::MsgConfigureFreeDVDemodPrivate::getVolume(), and pushSampleToAudio().
SSBFilter
fftfilt* FreeDVDemod::SSBFilter private
Definition at line 384 of file freedvdemod.h.
Referenced by applyFreeDVMode(), FreeDVDemod(), processOneSample(), and ~FreeDVDemod().
The documentation for this class was generated from the following files:
plugins/channelrx/demodfreedv/freedvdemod.h
plugins/channelrx/demodfreedv/freedvdemod.cpp