SDRAngel: Bladerf1InputGui Class Reference
Bladerf1InputGui Class Reference
#include <bladerf1inputgui.h>
Public Member Functions
Bladerf1InputGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~Bladerf1InputGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_centerFrequency_changed (quint64 value)
void on_sampleRate_changed (quint64 value)
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_bandwidth_currentIndexChanged (int index)
void on_decim_currentIndexChanged (int index)
void on_lna_currentIndexChanged (int index)
void on_vga1_valueChanged (int value)
void on_vga2_valueChanged (int value)
void on_xb200_currentIndexChanged (int index)
void on_fcPos_currentIndexChanged (int index)
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void on_sampleRateMode_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void displaySettings ()
void displaySampleRate ()
void displayFcTooltip ()
void sendSettings ()
unsigned int getXb200Index (bool xb_200, bladerf_xb200_path xb200Path, bladerf_xb200_filter xb200Filter)
void updateSampleRateAndFrequency ()
void blockApplySettings (bool block)
Private Attributes
Ui::Bladerf1InputGui * ui
DeviceUISet * m_deviceUISet
bool m_forceSettings
bool m_doApplySettings
BladeRF1InputSettings m_settings
bool m_sampleRateMode
true: device, false: base band sample rate update mode
QTimer m_updateTimer
QTimer m_statusTimer
std::vector< int > m_gains
DeviceSampleSource * m_sampleSource
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 35 of file bladerf1inputgui.h.
Constructor & Destructor Documentation
Bladerf1InputGui()
Bladerf1InputGui::Bladerf1InputGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 35 of file bladerf1inputgui.cpp.
References displaySettings(), BladerfBandwidths::getBandwidth(), BladerfBandwidths::getNbBandwidths(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, handleInputMessages(), i, DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_sampleSource, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), sendSettings(), DeviceSampleSource::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                                             :
     QWidget(parent),
     ui(new Ui::Bladerf1InputGui),
     m_deviceUISet(deviceUISet),
     m_forceSettings(true),
     m_doApplySettings(true),
     m_settings(),
     m_sampleRateMode(true),
     m_sampleSource(NULL),
     m_sampleRate(0),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     m_sampleSource = (Bladerf1Input*) m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, BLADERF_FREQUENCY_MIN_XB200/1000, BLADERF_FREQUENCY_MAX/1000);
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     // BladeRF can go as low as 80 kS/s but because of buffering in practice experience is not good below 330 kS/s
     ui->sampleRate->setValueRange(8, 330000U, BLADERF_SAMPLERATE_REC_MAX);
     ui->bandwidth->clear();
     for (unsigned int i = 0; i < BladerfBandwidths::getNbBandwidths(); i++)
     {
         ui->bandwidth->addItem(QString::number(BladerfBandwidths::getBandwidth(i)));
     }
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
     sendSettings();
 }
~Bladerf1InputGui()
Bladerf1InputGui::~Bladerf1InputGui () virtual
Definition at line 78 of file bladerf1inputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void Bladerf1InputGui::blockApplySettings (bool block) private
Definition at line 467 of file bladerf1inputgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool Bladerf1InputGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 122 of file bladerf1inputgui.cpp.
References BladeRF1InputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void Bladerf1InputGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 83 of file bladerf1inputgui.cpp.
 {
     delete this;
 }
displayFcTooltip()
void Bladerf1InputGui::displayFcTooltip () private
Definition at line 228 of file bladerf1inputgui.cpp.
References arg(), DeviceSampleSource::calculateFrequencyShift(), BladeRF1InputSettings::m_devSampleRate, BladeRF1InputSettings::m_fcPos, BladeRF1InputSettings::m_log2Decim, m_settings, and ui.
Referenced by displaySampleRate(), on_fcPos_currentIndexChanged(), and on_sampleRate_changed().
 {
     int32_t fShift = DeviceSampleSource::calculateFrequencyShift(
         m_settings.m_log2Decim,
         (DeviceSampleSource::fcPos_t) m_settings.m_fcPos,
         m_settings.m_devSampleRate,
         DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD
     );
     ui->fcPos->setToolTip(tr("Relative position of device center frequency: %1 kHz").arg(QString::number(fShift / 1000.0f, 'g', 5)));
 }
displaySampleRate()
void Bladerf1InputGui::displaySampleRate () private
Definition at line 196 of file bladerf1inputgui.cpp.
References arg(), displayFcTooltip(), BladeRF1InputSettings::m_devSampleRate, BladeRF1InputSettings::m_log2Decim, m_sampleRateMode, m_settings, and ui.
Referenced by displaySettings(), on_decim_currentIndexChanged(), on_sampleRateMode_toggled(), and updateSampleRateAndFrequency().
 {
     ui->sampleRate->blockSignals(true);
     displayFcTooltip();
     if (m_sampleRateMode)
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(60,60,60); }");
         ui->sampleRateMode->setText("SR");
         // BladeRF can go as low as 80 kS/s but because of buffering in practice experience is not good below 330 kS/s
         ui->sampleRate->setValueRange(8, 330000U, BLADERF_SAMPLERATE_REC_MAX);
         ui->sampleRate->setValue(m_settings.m_devSampleRate);
         ui->sampleRate->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setToolTip("Baseband sample rate (S/s)");
         uint32_t basebandSampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Decim);
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(basebandSampleRate / 1000.0f, 'g', 5)));
     }
     else
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(50,50,50); }");
         ui->sampleRateMode->setText("BB");
         // BladeRF can go as low as 80 kS/s but because of buffering in practice experience is not good below 330 kS/s
         ui->sampleRate->setValueRange(8, 330000U/(1<<m_settings.m_log2Decim), BLADERF_SAMPLERATE_REC_MAX/(1<<m_settings.m_log2Decim));
         ui->sampleRate->setValue(m_settings.m_devSampleRate/(1<<m_settings.m_log2Decim));
         ui->sampleRate->setToolTip("Baseband sample rate (S/s)");
         ui->deviceRateText->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_settings.m_devSampleRate / 1000.0f, 'g', 5)));
     }
     ui->sampleRate->blockSignals(false);
 }
displaySettings()
void Bladerf1InputGui::displaySettings () private
Definition at line 239 of file bladerf1inputgui.cpp.
References arg(), blockApplySettings(), displaySampleRate(), BladerfBandwidths::getBandwidthIndex(), getXb200Index(), BladeRF1InputSettings::m_bandwidth, BladeRF1InputSettings::m_centerFrequency, BladeRF1InputSettings::m_dcBlock, BladeRF1InputSettings::m_fcPos, BladeRF1InputSettings::m_iqCorrection, BladeRF1InputSettings::m_lnaGain, BladeRF1InputSettings::m_log2Decim, m_settings, BladeRF1InputSettings::m_vga1, BladeRF1InputSettings::m_vga2, BladeRF1InputSettings::m_xb200, BladeRF1InputSettings::m_xb200Filter, BladeRF1InputSettings::m_xb200Path, and ui.
Referenced by Bladerf1InputGui(), deserialize(), handleMessage(), resetToDefaults(), and setCenterFrequency().
 {
     blockApplySettings(true);
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     displaySampleRate();
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqCorrection);
     unsigned int bandwidthIndex = BladerfBandwidths::getBandwidthIndex(m_settings.m_bandwidth);
     ui->bandwidth->setCurrentIndex(bandwidthIndex);
     ui->decim->setCurrentIndex(m_settings.m_log2Decim);
     ui->fcPos->setCurrentIndex((int) m_settings.m_fcPos);
     ui->lna->setCurrentIndex(m_settings.m_lnaGain);
     ui->vga1Text->setText(tr("%1dB").arg(m_settings.m_vga1));
     ui->vga1->setValue(m_settings.m_vga1);
     ui->vga2Text->setText(tr("%1dB").arg(m_settings.m_vga2));
     ui->vga2->setValue(m_settings.m_vga2);
     ui->xb200->setCurrentIndex(getXb200Index(m_settings.m_xb200, m_settings.m_xb200Path, m_settings.m_xb200Filter));
     blockApplySettings(false);
 }
getCenterFrequency()
qint64 Bladerf1InputGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 105 of file bladerf1inputgui.cpp.
References BladeRF1InputSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* Bladerf1InputGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 51 of file bladerf1inputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString Bladerf1InputGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 93 of file bladerf1inputgui.cpp.
 {
     return objectName();
 }
getXb200Index()
unsigned int Bladerf1InputGui::getXb200Index (bool xb_200, bladerf_xb200_path xb200Path, bladerf_xb200_filter xb200Filter) private
Definition at line 501 of file bladerf1inputgui.cpp.
Referenced by displaySettings().
 {
     if (xb_200)
     {
         if (xb200Path == BLADERF_XB200_BYPASS)
         {
             return 1;
         }
         else
         {
             if (xb200Filter == BLADERF_XB200_AUTO_1DB)
             {
                 return 2;
             }
             else if (xb200Filter == BLADERF_XB200_AUTO_3DB)
             {
                 return 3;
             }
             else if (xb200Filter == BLADERF_XB200_CUSTOM)
             {
                 return 4;
             }
             else if (xb200Filter == BLADERF_XB200_50M)
             {
                 return 5;
             }
             else if (xb200Filter == BLADERF_XB200_144M)
             {
                 return 6;
             }
             else // xb200Filter == BLADERF_XB200_222M
             {
                 return 7;
             }
         }
     }
     else
     {
         return 0;
     }
 }
handleInputMessages
void Bladerf1InputGui::handleInputMessages () private slot
Definition at line 161 of file bladerf1inputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by Bladerf1InputGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("BladerfGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("BladerfGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool Bladerf1InputGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 135 of file bladerf1inputgui.cpp.
References blockApplySettings(), displaySettings(), Bladerf1Input::MsgConfigureBladerf1::getSettings(), Bladerf1Input::MsgStartStop::getStartStop(), m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (Bladerf1Input::MsgConfigureBladerf1::match(message))
     {
         const Bladerf1Input::MsgConfigureBladerf1& cfg = (Bladerf1Input::MsgConfigureBladerf1&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (Bladerf1Input::MsgStartStop::match(message))
     {
         Bladerf1Input::MsgStartStop& notif = (Bladerf1Input::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_bandwidth_currentIndexChanged
void Bladerf1InputGui::on_bandwidth_currentIndexChanged (int index) private slot
Definition at line 305 of file bladerf1inputgui.cpp.
References BladerfBandwidths::getBandwidth(), BladeRF1InputSettings::m_bandwidth, m_settings, and sendSettings().
 {
     int newbw = BladerfBandwidths::getBandwidth(index);
     m_settings.m_bandwidth = newbw * 1000;
     sendSettings();
 }
on_centerFrequency_changed
void Bladerf1InputGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 275 of file bladerf1inputgui.cpp.
References BladeRF1InputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_dcOffset_toggled
void Bladerf1InputGui::on_dcOffset_toggled (bool checked) private slot
Definition at line 293 of file bladerf1inputgui.cpp.
References BladeRF1InputSettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_decim_currentIndexChanged
void Bladerf1InputGui::on_decim_currentIndexChanged (int index) private slot
Definition at line 312 of file bladerf1inputgui.cpp.
References displaySampleRate(), BladeRF1InputSettings::m_devSampleRate, BladeRF1InputSettings::m_log2Decim, m_sampleRateMode, m_settings, sendSettings(), and ui.
 {
     if ((index <0) || (index > 6)) {
         return;
     }
     m_settings.m_log2Decim = index;
     displaySampleRate();
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     } else {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew() * (1 << m_settings.m_log2Decim);
     }
     sendSettings();
 }
on_fcPos_currentIndexChanged
void Bladerf1InputGui::on_fcPos_currentIndexChanged (int index) private slot
Definition at line 330 of file bladerf1inputgui.cpp.
References displayFcTooltip(), BladeRF1InputSettings::m_fcPos, m_settings, and sendSettings().
 {
     m_settings.m_fcPos = (BladeRF1InputSettings::fcPos_t) (index < 0 ? 0 : index > 2 ? 2 : index);
     displayFcTooltip();
     sendSettings();
 }
on_iqImbalance_toggled
void Bladerf1InputGui::on_iqImbalance_toggled (bool checked) private slot
Definition at line 299 of file bladerf1inputgui.cpp.
References BladeRF1InputSettings::m_iqCorrection, m_settings, and sendSettings().
 {
     m_settings.m_iqCorrection = checked;
     sendSettings();
 }
on_lna_currentIndexChanged
void Bladerf1InputGui::on_lna_currentIndexChanged (int index) private slot
Definition at line 337 of file bladerf1inputgui.cpp.
References BladeRF1InputSettings::m_lnaGain, m_settings, and sendSettings().
 {
     qDebug() << "BladerfGui: LNA gain = " << index * 3 << " dB";
     if ((index < 0) || (index > 2))
         return;
     m_settings.m_lnaGain = index;
     sendSettings();
 }
on_record_toggled
void Bladerf1InputGui::on_record_toggled (bool checked) private slot
Definition at line 437 of file bladerf1inputgui.cpp.
References Bladerf1Input::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     Bladerf1Input::MsgFileRecord* message = Bladerf1Input::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_sampleRate_changed
void Bladerf1InputGui::on_sampleRate_changed (quint64 value) private slot
Definition at line 281 of file bladerf1inputgui.cpp.
References displayFcTooltip(), BladeRF1InputSettings::m_devSampleRate, BladeRF1InputSettings::m_log2Decim, m_sampleRateMode, m_settings, and sendSettings().
 {
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = value;
     } else {
         m_settings.m_devSampleRate = value * (1 << m_settings.m_log2Decim);
     }
     displayFcTooltip();
     sendSettings();
 }
on_sampleRateMode_toggled
void Bladerf1InputGui::on_sampleRateMode_toggled (bool checked) private slot
Definition at line 449 of file bladerf1inputgui.cpp.
References displaySampleRate(), and m_sampleRateMode.
 {
     m_sampleRateMode = checked;
     displaySampleRate();
 }
on_startStop_toggled
void Bladerf1InputGui::on_startStop_toggled (bool checked) private slot
Definition at line 428 of file bladerf1inputgui.cpp.
References Bladerf1Input::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         Bladerf1Input::MsgStartStop *message = Bladerf1Input::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
on_vga1_valueChanged
void Bladerf1InputGui::on_vga1_valueChanged (int value) private slot
Definition at line 348 of file bladerf1inputgui.cpp.
References arg(), m_settings, BladeRF1InputSettings::m_vga1, sendSettings(), and ui.
 {
     if ((value < BLADERF_RXVGA1_GAIN_MIN) || (value > BLADERF_RXVGA1_GAIN_MAX))
         return;
     ui->vga1Text->setText(tr("%1dB").arg(value));
     m_settings.m_vga1 = value;
     sendSettings();
 }
on_vga2_valueChanged
void Bladerf1InputGui::on_vga2_valueChanged (int value) private slot
Definition at line 358 of file bladerf1inputgui.cpp.
References arg(), m_settings, BladeRF1InputSettings::m_vga2, sendSettings(), and ui.
 {
     if ((value < BLADERF_RXVGA2_GAIN_MIN) || (value > BLADERF_RXVGA2_GAIN_MAX))
         return;
     ui->vga2Text->setText(tr("%1dB").arg(value));
     m_settings.m_vga2 = value;
     sendSettings();
 }
on_xb200_currentIndexChanged
void Bladerf1InputGui::on_xb200_currentIndexChanged (int index) private slot
Definition at line 368 of file bladerf1inputgui.cpp.
References m_settings, BladeRF1InputSettings::m_xb200, BladeRF1InputSettings::m_xb200Filter, BladeRF1InputSettings::m_xb200Path, sendSettings(), and ui.
 {
     if (index == 1) // bypass
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_BYPASS;
     }
     else if (index == 2) // Auto 1dB
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_MIX;
         m_settings.m_xb200Filter = BLADERF_XB200_AUTO_1DB;
     }
     else if (index == 3) // Auto 3dB
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_MIX;
         m_settings.m_xb200Filter = BLADERF_XB200_AUTO_3DB;
     }
     else if (index == 4) // Custom
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_MIX;
         m_settings.m_xb200Filter = BLADERF_XB200_CUSTOM;
     }
     else if (index == 5) // 50 MHz
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_MIX;
         m_settings.m_xb200Filter = BLADERF_XB200_50M;
     }
     else if (index == 6) // 144 MHz
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_MIX;
         m_settings.m_xb200Filter = BLADERF_XB200_144M;
     }
     else if (index == 7) // 222 MHz
     {
         m_settings.m_xb200 = true;
         m_settings.m_xb200Path = BLADERF_XB200_MIX;
         m_settings.m_xb200Filter = BLADERF_XB200_222M;
     }
     else // no xb200
     {
         m_settings.m_xb200 = false;
     }
     if (m_settings.m_xb200)
     {
         ui->centerFrequency->setValueRange(7, BLADERF_FREQUENCY_MIN_XB200/1000, BLADERF_FREQUENCY_MAX/1000);
     }
     else
     {
         ui->centerFrequency->setValueRange(7, BLADERF_FREQUENCY_MIN/1000, BLADERF_FREQUENCY_MAX/1000);
     }
     sendSettings();
 }
openDeviceSettingsDialog
void Bladerf1InputGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 543 of file bladerf1inputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), BladeRF1InputSettings::m_reverseAPIAddress, BladeRF1InputSettings::m_reverseAPIDeviceIndex, BladeRF1InputSettings::m_reverseAPIPort, m_settings, BladeRF1InputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by Bladerf1InputGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void Bladerf1InputGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 98 of file bladerf1inputgui.cpp.
References displaySettings(), m_settings, BladeRF1InputSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void Bladerf1InputGui::sendSettings () private
Definition at line 269 of file bladerf1inputgui.cpp.
References m_updateTimer.
Referenced by Bladerf1InputGui(), deserialize(), on_bandwidth_currentIndexChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_iqImbalance_toggled(), on_lna_currentIndexChanged(), on_sampleRate_changed(), on_vga1_valueChanged(), on_vga2_valueChanged(), on_xb200_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray Bladerf1InputGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 117 of file bladerf1inputgui.cpp.
References m_settings, and BladeRF1InputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void Bladerf1InputGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 110 of file bladerf1inputgui.cpp.
References displaySettings(), BladeRF1InputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void Bladerf1InputGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 88 of file bladerf1inputgui.cpp.
 {
     setObjectName(name);
 }
updateHardware
void Bladerf1InputGui::updateHardware () private slot
Definition at line 455 of file bladerf1inputgui.cpp.
References Bladerf1Input::MsgConfigureBladerf1::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by Bladerf1InputGui().
 {
     if (m_doApplySettings)
     {
         qDebug() << "BladerfGui::updateHardware";
         Bladerf1Input::MsgConfigureBladerf1* message = Bladerf1Input::MsgConfigureBladerf1::create(m_settings, m_forceSettings);
         m_sampleSource->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void Bladerf1InputGui::updateSampleRateAndFrequency () private
Definition at line 189 of file bladerf1inputgui.cpp.
References displaySampleRate(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), and GLSpectrum::setSampleRate().
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     displaySampleRate();
 }
updateStatus
void Bladerf1InputGui::updateStatus () private slot
Definition at line 472 of file bladerf1inputgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by Bladerf1InputGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 Bladerf1InputGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 67 of file bladerf1inputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* Bladerf1InputGui::m_deviceUISet private
Definition at line 57 of file bladerf1inputgui.h.
Referenced by Bladerf1InputGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool Bladerf1InputGui::m_doApplySettings private
Definition at line 59 of file bladerf1inputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_forceSettings
bool Bladerf1InputGui::m_forceSettings private
Definition at line 58 of file bladerf1inputgui.h.
Referenced by deserialize(), and updateHardware().
m_gains
std::vector<int> Bladerf1InputGui::m_gains private
Definition at line 64 of file bladerf1inputgui.h.
m_inputMessageQueue
MessageQueue Bladerf1InputGui::m_inputMessageQueue private
Definition at line 69 of file bladerf1inputgui.h.
Referenced by Bladerf1InputGui(), and handleInputMessages().
m_lastEngineState
int Bladerf1InputGui::m_lastEngineState private
Definition at line 68 of file bladerf1inputgui.h.
Referenced by updateStatus().
m_sampleRate
int Bladerf1InputGui::m_sampleRate private
Definition at line 66 of file bladerf1inputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateMode
bool Bladerf1InputGui::m_sampleRateMode private
true: device, false: base band sample rate update mode
Definition at line 61 of file bladerf1inputgui.h.
Referenced by displaySampleRate(), on_decim_currentIndexChanged(), on_sampleRate_changed(), and on_sampleRateMode_toggled().
m_sampleSource
DeviceSampleSource* Bladerf1InputGui::m_sampleSource private
Definition at line 65 of file bladerf1inputgui.h.
Referenced by Bladerf1InputGui(), on_record_toggled(), on_startStop_toggled(), and updateHardware().
m_settings
BladeRF1InputSettings Bladerf1InputGui::m_settings private
Definition at line 60 of file bladerf1inputgui.h.
Referenced by deserialize(), displayFcTooltip(), displaySampleRate(), displaySettings(), getCenterFrequency(), handleMessage(), on_bandwidth_currentIndexChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_iqImbalance_toggled(), on_lna_currentIndexChanged(), on_sampleRate_changed(), on_vga1_valueChanged(), on_vga2_valueChanged(), on_xb200_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), and updateHardware().
m_statusTimer
QTimer Bladerf1InputGui::m_statusTimer private
Definition at line 63 of file bladerf1inputgui.h.
Referenced by Bladerf1InputGui().
m_updateTimer
QTimer Bladerf1InputGui::m_updateTimer private
Definition at line 62 of file bladerf1inputgui.h.
Referenced by Bladerf1InputGui(), sendSettings(), and updateHardware().
ui
Ui::Bladerf1InputGui* Bladerf1InputGui::ui private
Definition at line 55 of file bladerf1inputgui.h.
Referenced by Bladerf1InputGui(), displayFcTooltip(), displaySampleRate(), displaySettings(), handleMessage(), on_decim_currentIndexChanged(), on_record_toggled(), on_vga1_valueChanged(), on_vga2_valueChanged(), on_xb200_currentIndexChanged(), updateStatus(), and ~Bladerf1InputGui().
The documentation for this class was generated from the following files:
plugins/samplesource/bladerf1input/bladerf1inputgui.h
plugins/samplesource/bladerf1input/bladerf1inputgui.cpp