SDRAngel: NFMDemod::MsgConfigureNFMDemod Class Reference
NFMDemod::MsgConfigureNFMDemod Class Reference
#include <nfmdemod.h>
Public Member Functions
const NFMDemodSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureNFMDemod * create (const NFMDemodSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureNFMDemod (const NFMDemodSettings &settings, bool force)
Private Attributes
NFMDemodSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 53 of file nfmdemod.h.
Constructor & Destructor Documentation
MsgConfigureNFMDemod()
NFMDemod::MsgConfigureNFMDemod::MsgConfigureNFMDemod (const NFMDemodSettings & settings, bool force) inline private
Definition at line 69 of file nfmdemod.h.
Referenced by create().
                                                                            :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureNFMDemod* NFMDemod::MsgConfigureNFMDemod::create (const NFMDemodSettings & settings, bool force) inline static
Definition at line 60 of file nfmdemod.h.
References MsgConfigureNFMDemod().
Referenced by NFMDemodGUI::applySettings(), NFMDemod::deserialize(), and NFMDemod::webapiSettingsPutPatch().
         {
             return new MsgConfigureNFMDemod(settings, force);
         }
getForce()
bool NFMDemod::MsgConfigureNFMDemod::getForce () const inline
Definition at line 58 of file nfmdemod.h.
References m_force.
Referenced by NFMDemod::handleMessage().
 { return m_force; }
getSettings()
const NFMDemodSettings& NFMDemod::MsgConfigureNFMDemod::getSettings () const inline
Definition at line 57 of file nfmdemod.h.
References m_settings.
Referenced by NFMDemodGUI::handleMessage(), and NFMDemod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool NFMDemod::MsgConfigureNFMDemod::m_force private
Definition at line 67 of file nfmdemod.h.
Referenced by getForce().
m_settings
NFMDemodSettings NFMDemod::MsgConfigureNFMDemod::m_settings private
Definition at line 66 of file nfmdemod.h.
Referenced by NFMDemod::getCenterFrequency(), getSettings(), NFMDemod::getStreamCenterFrequency(), and NFMDemod::getTitle().
The documentation for this class was generated from the following file:
plugins/channelrx/demodnfm/nfmdemod.h