SDRAngel: FCDProInput Class Reference
FCDProInput Class Reference
#include <fcdproinput.h>
Classes
class MsgConfigureFCDPro
class MsgFileRecord
class MsgStartStop
Public Member Functions
FCDProInput (DeviceAPI *deviceAPI)
virtual ~FCDProInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
void set_center_freq (double freq)
void set_bias_t (bool on)
void set_lnaGain (int index)
void set_rfFilter (int index)
void set_lnaEnhance (int index)
void set_band (int index)
void set_mixerGain (int index)
void set_mixerFilter (int index)
void set_biasCurrent (int index)
void set_mode (int index)
void set_gain1 (int index)
void set_rcFilter (int index)
void set_gain2 (int index)
void set_gain3 (int index)
void set_gain4 (int index)
void set_ifFilter (int index)
void set_gain5 (int index)
void set_gain6 (int index)
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
bool openFCDAudio (const char *filename)
void closeFCDAudio ()
void applySettings (const FCDProSettings &settings, bool force)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const FCDProSettings &settings)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const FCDProSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
hid_device * m_dev
AudioInput m_fcdAudioInput
AudioFifo m_fcdFIFO
QMutex m_mutex
FCDProSettings m_settings
FCDProThread * m_FCDThread
QString m_deviceDescription
bool m_running
FileRecord * m_fileSink
File sink to record device I/Q output.
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 45 of file fcdproinput.h.
Constructor & Destructor Documentation
FCDProInput()
FCDProInput::FCDProInput (DeviceAPI * deviceAPI)
Definition at line 42 of file fcdproinput.cpp.
References arg().
                                              :
     m_deviceAPI(deviceAPI),
     m_dev(0),
     m_settings(),
     m_FCDThread(0),
     m_deviceDescription(fcd_traits<Pro>::displayedName),
     m_running(false)
 {
     m_fcdFIFO.setSize(20*fcd_traits<Pro>::convBufSize);
     openDevice();
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~FCDProInput()
FCDProInput::~FCDProInput () virtual
Definition at line 59 of file fcdproinput.cpp.
References closeDevice(), m_deviceAPI, m_fileSink, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::removeAncillarySink(), and stop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
     closeDevice();
 }
Member Function Documentation
applySettings()
void FCDProInput::applySettings (const FCDProSettings & settings, bool force) private
Definition at line 323 of file fcdproinput.cpp.
References DeviceSampleSource::calculateDeviceCenterFrequency(), DeviceAPI::configureCorrections(), DeviceAPI::getDeviceEngineInputMessageQueue(), FileRecord::handleMessage(), FCDProSettings::m_bandIndex, FCDProSettings::m_biasCurrentIndex, FCDProSettings::m_centerFrequency, FCDProSettings::m_dcBlock, m_dev, m_deviceAPI, m_FCDThread, FCDProSettings::m_fcPos, m_fileSink, FCDProSettings::m_gain1Index, FCDProSettings::m_gain2Index, FCDProSettings::m_gain3Index, FCDProSettings::m_gain4Index, FCDProSettings::m_gain5Index, FCDProSettings::m_gain6Index, FCDProSettings::m_ifFilterIndex, FCDProSettings::m_iqCorrection, FCDProSettings::m_lnaEnhanceIndex, FCDProSettings::m_lnaGainIndex, FCDProSettings::m_log2Decim, FCDProSettings::m_LOppmTenths, FCDProSettings::m_mixerFilterIndex, FCDProSettings::m_mixerGainIndex, FCDProSettings::m_modeIndex, FCDProSettings::m_rcFilterIndex, FCDProSettings::m_reverseAPIAddress, FCDProSettings::m_reverseAPIDeviceIndex, FCDProSettings::m_reverseAPIPort, FCDProSettings::m_rfFilterIndex, m_settings, FCDProSettings::m_transverterDeltaFrequency, FCDProSettings::m_transverterMode, FCDProSettings::m_useReverseAPI, MessageQueue::push(), set_band(), set_biasCurrent(), set_center_freq(), set_gain1(), set_gain2(), set_gain3(), set_gain4(), set_gain5(), set_gain6(), set_ifFilter(), set_lnaEnhance(), set_lnaGain(), set_mixerFilter(), set_mixerGain(), set_mode(), set_rcFilter(), set_rfFilter(), FCDProThread::setFcPos(), FCDProThread::setLog2Decimation(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     bool forwardChange = false;
     QList<QString> reverseAPIKeys;
     if (force || (m_settings.m_centerFrequency != settings.m_centerFrequency)) {
         reverseAPIKeys.append("centerFrequency");
     }
     if (force || (m_settings.m_transverterMode != settings.m_transverterMode)) {
         reverseAPIKeys.append("transverterMode");
     }
     if (force || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency)) {
         reverseAPIKeys.append("transverterDeltaFrequency");
     }
     if ((m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force) {
         reverseAPIKeys.append("LOppmTenths");
     }
     if (force || (m_settings.m_centerFrequency != settings.m_centerFrequency)
         || (m_settings.m_LOppmTenths != settings.m_LOppmTenths)
         || (m_settings.m_fcPos != settings.m_fcPos)
         || (m_settings.m_log2Decim != settings.m_log2Decim)
         || (m_settings.m_transverterMode != settings.m_transverterMode)
         || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency))
     {
         qint64 deviceCenterFrequency = DeviceSampleSource::calculateDeviceCenterFrequency(
                 settings.m_centerFrequency,
                 settings.m_transverterDeltaFrequency,
                 settings.m_log2Decim,
                 (DeviceSampleSource::fcPos_t) settings.m_fcPos,
                 fcd_traits<Pro>::sampleRate,
                 DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD,
                 settings.m_transverterMode);
         if (m_dev != 0)
         {
             set_center_freq((double) deviceCenterFrequency);
         }
         qDebug() << "FCDProInput::applySettings: center freq: " << settings.m_centerFrequency << " Hz"
                 << " device center freq: " << deviceCenterFrequency << " Hz";
         forwardChange = (m_settings.m_centerFrequency != settings.m_centerFrequency) || force;
         m_settings.m_centerFrequency = settings.m_centerFrequency;
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         reverseAPIKeys.append("log2Decim");
         forwardChange = true;
         if (m_FCDThread != 0)
         {
             m_FCDThread->setLog2Decimation(settings.m_log2Decim);
             qDebug() << "FCDProInput::applySettings: set decimation to " << (1<<settings.m_log2Decim);
         }
     }
     if ((m_settings.m_fcPos != settings.m_fcPos) || force)
     {
         reverseAPIKeys.append("fcPos");
         if (m_FCDThread != 0) {
             m_FCDThread->setFcPos((int) settings.m_fcPos);
         }
         qDebug() << "FCDProInput::applySettings: set fc pos (enum) to " << (int) settings.m_fcPos;
     }
     if ((m_settings.m_lnaGainIndex != settings.m_lnaGainIndex) || force)
     {
         reverseAPIKeys.append("lnaGainIndex");
         if (m_dev != 0) {
             set_lnaGain(settings.m_lnaGainIndex);
         }
     }
     if ((m_settings.m_rfFilterIndex != settings.m_rfFilterIndex) || force)
     {
         reverseAPIKeys.append("rfFilterIndex");
         if (m_dev != 0) {
             set_rfFilter(settings.m_rfFilterIndex);
         }
     }
     if ((m_settings.m_lnaEnhanceIndex != settings.m_lnaEnhanceIndex) || force)
     {
         reverseAPIKeys.append("lnaEnhanceIndex");
         if (m_dev != 0) {
             set_lnaEnhance(settings.m_lnaEnhanceIndex);
         }
     }
     if ((m_settings.m_bandIndex != settings.m_bandIndex) || force)
     {
         reverseAPIKeys.append("bandIndex");
         if (m_dev != 0) {
             set_band(settings.m_bandIndex);
         }
     }
     if ((m_settings.m_mixerGainIndex != settings.m_mixerGainIndex) || force)
     {
         reverseAPIKeys.append("mixerGainIndex");
         if (m_dev != 0) {
             set_mixerGain(settings.m_mixerGainIndex);
         }
     }
     if ((m_settings.m_mixerFilterIndex != settings.m_mixerFilterIndex) || force)
     {
         reverseAPIKeys.append("mixerFilterIndex");
         if (m_dev != 0) {
             set_mixerFilter(settings.m_mixerFilterIndex);
         }
     }
     if ((m_settings.m_biasCurrentIndex != settings.m_biasCurrentIndex) || force)
     {
         reverseAPIKeys.append("biasCurrentIndex");
         if (m_dev != 0) {
             set_biasCurrent(settings.m_biasCurrentIndex);
         }
     }
     if ((m_settings.m_modeIndex != settings.m_modeIndex) || force)
     {
         reverseAPIKeys.append("modeIndex");
         if (m_dev != 0) {
             set_mode(settings.m_modeIndex);
         }
     }
     if ((m_settings.m_gain1Index != settings.m_gain1Index) || force)
     {
         reverseAPIKeys.append("gain1Index");
         if (m_dev != 0) {
             set_gain1(settings.m_gain1Index);
         }
     }
     if ((m_settings.m_rcFilterIndex != settings.m_rcFilterIndex) || force)
     {
         reverseAPIKeys.append("rcFilterIndex");
         if (m_dev != 0) {
             set_rcFilter(settings.m_rcFilterIndex);
         }
     }
     if ((m_settings.m_gain2Index != settings.m_gain2Index) || force)
     {
         reverseAPIKeys.append("gain2Index");
         if (m_dev != 0) {
             set_gain2(settings.m_gain2Index);
         }
     }
     if ((m_settings.m_gain3Index != settings.m_gain3Index) || force)
     {
         reverseAPIKeys.append("gain3Index");
         if (m_dev != 0) {
             set_gain3(settings.m_gain3Index);
         }
     }
     if ((m_settings.m_gain4Index != settings.m_gain4Index) || force)
     {
         reverseAPIKeys.append("gain4Index");
         if (m_dev != 0) {
             set_gain4(settings.m_gain4Index);
         }
     }
     if ((m_settings.m_ifFilterIndex != settings.m_ifFilterIndex) || force)
     {
         reverseAPIKeys.append("ifFilterIndex");
         if (m_dev != 0) {
             set_ifFilter(settings.m_ifFilterIndex);
         }
     }
     if ((m_settings.m_gain5Index != settings.m_gain5Index) || force)
     {
         reverseAPIKeys.append("gain5Index");
         if (m_dev != 0) {
             set_gain5(settings.m_gain5Index);
         }
     }
     if ((m_settings.m_gain6Index != settings.m_gain6Index) || force)
     {
         reverseAPIKeys.append("gain6Index");
         if (m_dev != 0) {
             set_gain6(settings.m_gain6Index);
         }
     }
     if ((m_settings.m_dcBlock != settings.m_dcBlock) || force)
     {
         reverseAPIKeys.append("dcBlock");
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqCorrection);
     }
     if ((m_settings.m_iqCorrection != settings.m_iqCorrection) || force)
     {
         reverseAPIKeys.append("iqCorrection");
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqCorrection);
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     if (forwardChange)
     {
         DSPSignalNotification *notif = new DSPSignalNotification(fcd_traits<Pro>::sampleRate/(1<<m_settings.m_log2Decim), m_settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
 }
closeDevice()
void FCDProInput::closeDevice () private
Definition at line 150 of file fcdproinput.cpp.
References closeFCDAudio(), fcdClose(), and m_dev.
Referenced by openDevice(), and ~FCDProInput().
 {
     if (m_dev == 0) { // was never open
         return;
     }
     fcdClose(m_dev);
     m_dev = 0;
     closeFCDAudio();
 }
closeFCDAudio()
void FCDProInput::closeFCDAudio () private
Definition at line 185 of file fcdproinput.cpp.
References m_fcdAudioInput, m_fcdFIFO, AudioInput::removeFifo(), and AudioInput::stop().
Referenced by closeDevice().
 {
     m_fcdAudioInput.removeFifo(&m_fcdFIFO);
     m_fcdAudioInput.stop();
 }
deserialize()
bool FCDProInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 211 of file fcdproinput.cpp.
References FCDProInput::MsgConfigureFCDPro::create(), FCDProSettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and FCDProSettings::resetToDefaults().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureFCDPro* message = MsgConfigureFCDPro::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureFCDPro* messageToGUI = MsgConfigureFCDPro::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void FCDProInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 74 of file fcdproinput.cpp.
 {
     delete this;
 }
getCenterFrequency()
quint64 FCDProInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 243 of file fcdproinput.cpp.
References FCDProSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & FCDProInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 233 of file fcdproinput.cpp.
References m_deviceDescription.
 {
     return m_deviceDescription;
 }
getSampleRate()
int FCDProInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 238 of file fcdproinput.cpp.
References FCDProSettings::m_log2Decim, and m_settings.
 {
     return fcd_traits<Pro>::sampleRate/(1<<m_settings.m_log2Decim);
 }
handleMessage()
bool FCDProInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 263 of file fcdproinput.cpp.
References applySettings(), FileRecord::genUniqueFileName(), DeviceAPI::getDeviceUID(), FCDProInput::MsgConfigureFCDPro::getForce(), FCDProInput::MsgConfigureFCDPro::getSettings(), FCDProInput::MsgFileRecord::getStartStop(), FCDProInput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), m_deviceAPI, FCDProSettings::m_fileRecordName, m_fileSink, m_settings, FCDProSettings::m_useReverseAPI, Message::match(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
 {
     if(MsgConfigureFCDPro::match(message))
     {
         qDebug() << "FCDProInput::handleMessage: MsgConfigureFCD";
         MsgConfigureFCDPro& conf = (MsgConfigureFCDPro&) message;
         applySettings(conf.getSettings(), conf.getForce());
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "FCDProInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "FCDProInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void FCDProInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 108 of file fcdproinput.cpp.
References applySettings(), and m_settings.
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void FCDProInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 1156 of file fcdproinput.cpp.
Referenced by ~FCDProInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "FCDProInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("FCDProInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openDevice()
bool FCDProInput::openDevice () private
Definition at line 79 of file fcdproinput.cpp.
References closeDevice(), fcdOpen(), DeviceAPI::getSamplingDeviceSequence(), m_dev, m_deviceAPI, and openFCDAudio().
 {
     if (m_dev != 0) {
         closeDevice();
     }
     int device = m_deviceAPI->getSamplingDeviceSequence();
     qDebug() << "FCDProInput::openDevice with device #" << device;
     m_dev = fcdOpen(fcd_traits<Pro>::vendorId, fcd_traits<Pro>::productId, device);
     if (m_dev == 0)
     {
         qCritical("FCDProInput::start: could not open FCD");
         return false;
     }
     if (!openFCDAudio(fcd_traits<Pro>::qtDeviceName))
     {
         qCritical("FCDProInput::start: could not open FCD audio source");
         return false;
     }
     else
     {
         qDebug("FCDProInput::start: FCD audio source opened");
     }
     return true;
 }
openFCDAudio()
bool FCDProInput::openFCDAudio (const char * filename) private
Definition at line 162 of file fcdproinput.cpp.
References AudioInput::addFifo(), DSPEngine::getAudioDeviceManager(), AudioDeviceManager::getInputDeviceIndex(), AudioDeviceManager::getInputDevices(), AudioInput::getRate(), DSPEngine::instance(), m_fcdAudioInput, m_fcdFIFO, and AudioInput::start().
Referenced by openDevice().
 {
     AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
     const QList<QAudioDeviceInfo>& audioList = audioDeviceManager->getInputDevices();
     for (const auto &itAudio : audioList)
     {
         if (itAudio.deviceName().contains(QString(cardname)))
         {
             int fcdDeviceIndex = audioDeviceManager->getInputDeviceIndex(itAudio.deviceName());
             m_fcdAudioInput.start(fcdDeviceIndex, fcd_traits<Pro>::sampleRate);
             int fcdSampleRate = m_fcdAudioInput.getRate();
             qDebug("FCDProPlusInput::openFCDAudio: %s index %d at %d S/s",
                     itAudio.deviceName().toStdString().c_str(), fcdDeviceIndex, fcdSampleRate);
             m_fcdAudioInput.addFifo(&m_fcdFIFO);
             return true;
         }
     }
     qCritical("FCDProInput::openFCDAudio: device with name %s not found", cardname);
     return false;
 }
serialize()
QByteArray FCDProInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 206 of file fcdproinput.cpp.
References m_settings, and FCDProSettings::serialize().
 {
     return m_settings.serialize();
 }
set_band()
void FCDProInput::set_band (int index)
Definition at line 633 of file fcdproinput.cpp.
References FCDProConstants::bands, FCD_MODE_APP, fcdAppSetParam(), FCDProConstants::fcdpro_band_nb_values(), FCDPRO_HID_CMD_SET_BAND, m_dev, and fcdpro_band::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_band_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::bands[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_BAND, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_band: failed to set at " << cmd_value;
     }
 }
set_bias_t()
void FCDProInput::set_bias_t (bool on)
Definition at line 579 of file fcdproinput.cpp.
 {
     (void) on;
     //quint8 cmd = on ? 1 : 0;
     // TODO: use FCD Pro controls
     //fcdAppSetParam(m_dev, FCD_CMD_APP_SET_BIAS_TEE, &cmd, 1);
 }
set_biasCurrent()
void FCDProInput::set_biasCurrent (int index)
Definition at line 678 of file fcdproinput.cpp.
References FCDProConstants::bias_currents, FCD_MODE_APP, fcdAppSetParam(), FCDProConstants::fcdpro_bias_current_nb_values(), FCDPRO_HID_CMD_SET_BIAS_CURRENT, m_dev, and fcdpro_bias_current::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_bias_current_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::bias_currents[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_BIAS_CURRENT, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_biasCurrent: failed to set at " << cmd_value;
     }
 }
set_center_freq()
void FCDProInput::set_center_freq (double freq)
Definition at line 568 of file fcdproinput.cpp.
References FCD_MODE_NONE, fcdAppSetFreq(), m_dev, FCDProSettings::m_LOppmTenths, and m_settings.
Referenced by applySettings().
 {
     freq += freq*(((double) m_settings.m_LOppmTenths)/10000000.0);
     if (fcdAppSetFreq(m_dev, freq) == FCD_MODE_NONE)
     {
         qDebug("No FCD HID found for frquency change");
     }
 }
set_gain1()
void FCDProInput::set_gain1 (int index)
Definition at line 708 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_IF_GAIN1, FCDProConstants::fcdpro_if_gain1_nb_values(), FCDProConstants::if_gains1, m_dev, and fcdpro_if_gain1::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_if_gain1_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::if_gains1[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_IF_GAIN1, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_gain1: failed to set at " << cmd_value;
     }
 }
set_gain2()
void FCDProInput::set_gain2 (int index)
Definition at line 738 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_IF_GAIN2, FCDProConstants::fcdpro_if_gain2_nb_values(), FCDProConstants::if_gains2, m_dev, and fcdpro_if_gain2::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_if_gain2_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::if_gains2[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_IF_GAIN2, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_gain2: failed to set at " << cmd_value;
     }
 }
set_gain3()
void FCDProInput::set_gain3 (int index)
Definition at line 753 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_IF_GAIN3, FCDProConstants::fcdpro_if_gain3_nb_values(), FCDProConstants::if_gains3, m_dev, and fcdpro_if_gain3::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_if_gain3_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::if_gains3[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_IF_GAIN3, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_gain3: failed to set at " << cmd_value;
     }
 }
set_gain4()
void FCDProInput::set_gain4 (int index)
Definition at line 768 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_IF_GAIN4, FCDProConstants::fcdpro_if_gain4_nb_values(), FCDProConstants::if_gains4, m_dev, and fcdpro_if_gain4::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_if_gain4_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::if_gains4[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_IF_GAIN4, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_gain4: failed to set at " << cmd_value;
     }
 }
set_gain5()
void FCDProInput::set_gain5 (int index)
Definition at line 799 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_IF_GAIN5, FCDProConstants::fcdpro_if_gain5_nb_values(), FCDProConstants::if_gains5, m_dev, and fcdpro_if_gain5::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_if_gain5_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::if_gains5[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_IF_GAIN5, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_gain5: failed to set at " << cmd_value;
     }
 }
set_gain6()
void FCDProInput::set_gain6 (int index)
Definition at line 814 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_IF_GAIN6, FCDProConstants::fcdpro_if_gain6_nb_values(), FCDProConstants::if_gains6, m_dev, and fcdpro_if_gain6::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_if_gain6_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::if_gains6[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_IF_GAIN6, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_gain6: failed to set at " << cmd_value;
     }
 }
set_ifFilter()
void FCDProInput::set_ifFilter (int index)
Definition at line 783 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_IF_FILTER, FCDProConstants::fcdpro_if_filter_nb_values(), FCDProConstants::if_filters, m_dev, and fcdpro_if_filter::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_if_filter_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::if_filters[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_IF_FILTER, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_ifFilter: failed to set at " << cmd_value;
     }
 }
set_lnaEnhance()
void FCDProInput::set_lnaEnhance (int index)
Definition at line 618 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_LNA_ENHANCE, FCDProConstants::fcdpro_lna_enhance_nb_values(), FCDProConstants::lna_enhances, m_dev, and fcdpro_lna_enhance::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_lna_enhance_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::lna_enhances[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_LNA_ENHANCE, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_lnaEnhance: failed to set at " << cmd_value;
     }
 }
set_lnaGain()
void FCDProInput::set_lnaGain (int index)
Definition at line 588 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_LNA_GAIN, FCDProConstants::fcdpro_lna_gain_nb_values(), FCDProConstants::lna_gains, m_dev, and fcdpro_lna_gain::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_lna_gain_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::lna_gains[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_LNA_GAIN, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_lnaGain: failed to set at " << cmd_value;
     }
 }
set_mixerFilter()
void FCDProInput::set_mixerFilter (int index)
Definition at line 663 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_MIXER_FILTER, FCDProConstants::fcdpro_mixer_filter_nb_values(), m_dev, FCDProConstants::mixer_filters, and fcdpro_mixer_filter::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_mixer_filter_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::mixer_filters[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_MIXER_FILTER, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_mixerFilter: failed to set at " << cmd_value;
     }
 }
set_mixerGain()
void FCDProInput::set_mixerGain (int index)
Definition at line 648 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_MIXER_GAIN, FCDProConstants::fcdpro_mixer_gain_nb_values(), m_dev, FCDProConstants::mixer_gains, and fcdpro_mixer_gain::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_mixer_gain_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::mixer_gains[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_MIXER_GAIN, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_mixerGain: failed to set at " << cmd_value;
     }
 }
set_mode()
void FCDProInput::set_mode (int index)
Definition at line 693 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_IF_GAIN_MODE, FCDProConstants::fcdpro_if_gain_mode_nb_values(), FCDProConstants::if_gain_modes, m_dev, and fcdpro_if_gain_mode::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_if_gain_mode_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::if_gain_modes[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_IF_GAIN_MODE, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_mode: failed to set at " << cmd_value;
     }
 }
set_rcFilter()
void FCDProInput::set_rcFilter (int index)
Definition at line 723 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_IF_RC_FILTER, FCDProConstants::fcdpro_if_rc_filter_nb_values(), FCDProConstants::if_rc_filters, m_dev, and fcdpro_if_rc_filter::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_if_rc_filter_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::if_rc_filters[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_IF_RC_FILTER, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_rcFilter: failed to set at " << cmd_value;
     }
 }
set_rfFilter()
void FCDProInput::set_rfFilter (int index)
Definition at line 603 of file fcdproinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPRO_HID_CMD_SET_RF_FILTER, FCDProConstants::fcdpro_rf_filter_nb_values(), m_dev, FCDProConstants::rf_filters, and fcdpro_rf_filter::value.
Referenced by applySettings().
 {
     if ((index < 0) || (index >= FCDProConstants::fcdpro_rf_filter_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProConstants::rf_filters[index].value;
     if (fcdAppSetParam(m_dev, FCDPRO_HID_CMD_SET_RF_FILTER, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_rfFilter: failed to set at " << cmd_value;
     }
 }
setCenterFrequency()
void FCDProInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 248 of file fcdproinput.cpp.
References FCDProInput::MsgConfigureFCDPro::create(), FCDProSettings::m_centerFrequency, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
 {
     FCDProSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureFCDPro* message = MsgConfigureFCDPro::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureFCDPro* messageToGUI = MsgConfigureFCDPro::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setMessageQueueToGUI()
virtual void FCDProInput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 120 of file fcdproinput.h.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void FCDProInput::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 123 of file fcdproinput.h.
 { (void) sampleRate; }
start()
bool FCDProInput::start () virtual
Implements DeviceSampleSource.
Definition at line 113 of file fcdproinput.cpp.
References applySettings(), m_dev, m_fcdFIFO, m_FCDThread, m_running, DeviceSampleSource::m_sampleFifo, m_settings, SampleSinkFifo::setSize(), FCDProThread::startWork(), and stop().
 {
     qDebug() << "FCDProInput::start";
 //  QMutexLocker mutexLocker(&m_mutex);
     if (!m_dev) {
         return false;
     }
     if (m_running) stop();
     /* Apply settings before streaming to avoid bus contention;
      * there is very little spare bandwidth on a full speed USB device.
      * Failure is harmless if no device is found
      * ... This is rubbish...*/
     //applySettings(m_settings, true);
     if(!m_sampleFifo.setSize(96000*4))
     {
         qCritical("Could not allocate SampleFifo");
         return false;
     }
     m_FCDThread = new FCDProThread(&m_sampleFifo, &m_fcdFIFO);
     m_FCDThread->startWork();
 //  mutexLocker.unlock();
     applySettings(m_settings, true);
     qDebug("FCDProInput::started");
     m_running = true;
     return true;
 }
stop()
void FCDProInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 191 of file fcdproinput.cpp.
References m_FCDThread, m_running, and FCDProThread::stopWork().
Referenced by start(), and ~FCDProInput().
 {
 //  QMutexLocker mutexLocker(&m_mutex);
     if (m_FCDThread)
     {
         m_FCDThread->stopWork();
         // wait for thread to quit ?
         delete m_FCDThread;
         m_FCDThread = nullptr;
     }
     m_running = false;
 }
webapiFormatDeviceSettings()
void FCDProInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const FCDProSettings & settings) private
Definition at line 978 of file fcdproinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getFcdProSettings(), SWGSDRangel::SWGFCDProSettings::getFileRecordName(), SWGSDRangel::SWGFCDProSettings::getReverseApiAddress(), FCDProSettings::m_bandIndex, FCDProSettings::m_biasCurrentIndex, FCDProSettings::m_centerFrequency, FCDProSettings::m_dcBlock, FCDProSettings::m_fcPos, FCDProSettings::m_fileRecordName, FCDProSettings::m_gain1Index, FCDProSettings::m_gain2Index, FCDProSettings::m_gain3Index, FCDProSettings::m_gain4Index, FCDProSettings::m_gain5Index, FCDProSettings::m_gain6Index, FCDProSettings::m_ifFilterIndex, FCDProSettings::m_iqCorrection, FCDProSettings::m_lnaEnhanceIndex, FCDProSettings::m_lnaGainIndex, FCDProSettings::m_log2Decim, FCDProSettings::m_LOppmTenths, FCDProSettings::m_mixerFilterIndex, FCDProSettings::m_mixerGainIndex, FCDProSettings::m_modeIndex, FCDProSettings::m_rcFilterIndex, FCDProSettings::m_reverseAPIAddress, FCDProSettings::m_reverseAPIDeviceIndex, FCDProSettings::m_reverseAPIPort, FCDProSettings::m_rfFilterIndex, FCDProSettings::m_transverterDeltaFrequency, FCDProSettings::m_transverterMode, FCDProSettings::m_useReverseAPI, SWGSDRangel::SWGFCDProSettings::setBandIndex(), SWGSDRangel::SWGFCDProSettings::setBiasCurrentIndex(), SWGSDRangel::SWGFCDProSettings::setCenterFrequency(), SWGSDRangel::SWGFCDProSettings::setDcBlock(), SWGSDRangel::SWGFCDProSettings::setFcPos(), SWGSDRangel::SWGFCDProSettings::setFileRecordName(), SWGSDRangel::SWGFCDProSettings::setGain1Index(), SWGSDRangel::SWGFCDProSettings::setGain2Index(), SWGSDRangel::SWGFCDProSettings::setGain3Index(), SWGSDRangel::SWGFCDProSettings::setGain4Index(), SWGSDRangel::SWGFCDProSettings::setGain5Index(), SWGSDRangel::SWGFCDProSettings::setGain6Index(), SWGSDRangel::SWGFCDProSettings::setIfFilterIndex(), SWGSDRangel::SWGFCDProSettings::setIqCorrection(), SWGSDRangel::SWGFCDProSettings::setLnaEnhanceIndex(), SWGSDRangel::SWGFCDProSettings::setLnaGainIndex(), SWGSDRangel::SWGFCDProSettings::setLog2Decim(), SWGSDRangel::SWGFCDProSettings::setLOppmTenths(), SWGSDRangel::SWGFCDProSettings::setMixerFilterIndex(), SWGSDRangel::SWGFCDProSettings::setMixerGainIndex(), SWGSDRangel::SWGFCDProSettings::setModeIndex(), SWGSDRangel::SWGFCDProSettings::setRcFilterIndex(), SWGSDRangel::SWGFCDProSettings::setReverseApiAddress(), SWGSDRangel::SWGFCDProSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGFCDProSettings::setReverseApiPort(), SWGSDRangel::SWGFCDProSettings::setRfFilterIndex(), SWGSDRangel::SWGFCDProSettings::setTransverterDeltaFrequency(), SWGSDRangel::SWGFCDProSettings::setTransverterMode(), and SWGSDRangel::SWGFCDProSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getFcdProSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getFcdProSettings()->setLOppmTenths(settings.m_LOppmTenths);
     response.getFcdProSettings()->setLnaGainIndex(settings.m_lnaGainIndex);
     response.getFcdProSettings()->setRfFilterIndex(settings.m_rfFilterIndex);
     response.getFcdProSettings()->setLnaEnhanceIndex(settings.m_lnaEnhanceIndex);
     response.getFcdProSettings()->setBandIndex(settings.m_bandIndex);
     response.getFcdProSettings()->setMixerGainIndex(settings.m_mixerGainIndex);
     response.getFcdProSettings()->setMixerFilterIndex(settings.m_mixerFilterIndex);
     response.getFcdProSettings()->setBiasCurrentIndex(settings.m_biasCurrentIndex);
     response.getFcdProSettings()->setModeIndex(settings.m_modeIndex);
     response.getFcdProSettings()->setGain1Index(settings.m_gain1Index);
     response.getFcdProSettings()->setGain2Index(settings.m_gain2Index);
     response.getFcdProSettings()->setGain3Index(settings.m_gain3Index);
     response.getFcdProSettings()->setGain4Index(settings.m_gain4Index);
     response.getFcdProSettings()->setGain5Index(settings.m_gain5Index);
     response.getFcdProSettings()->setGain6Index(settings.m_gain6Index);
     response.getFcdProSettings()->setLog2Decim(settings.m_log2Decim);
     response.getFcdProSettings()->setFcPos((int) settings.m_fcPos);
     response.getFcdProSettings()->setRcFilterIndex(settings.m_rcFilterIndex);
     response.getFcdProSettings()->setIfFilterIndex(settings.m_ifFilterIndex);
     response.getFcdProSettings()->setDcBlock(settings.m_dcBlock ? 1 : 0);
     response.getFcdProSettings()->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     response.getFcdProSettings()->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     response.getFcdProSettings()->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     if (response.getFcdProSettings()->getFileRecordName()) {
         *response.getFcdProSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getFcdProSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getFcdProSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getFcdProSettings()->getReverseApiAddress()) {
         *response.getFcdProSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getFcdProSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getFcdProSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getFcdProSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReverseSendSettings()
void FCDProInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const FCDProSettings & settings, bool force) private
Definition at line 1023 of file fcdproinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getFcdProSettings(), FCDProSettings::m_bandIndex, FCDProSettings::m_biasCurrentIndex, FCDProSettings::m_centerFrequency, FCDProSettings::m_dcBlock, m_deviceAPI, FCDProSettings::m_fcPos, FCDProSettings::m_fileRecordName, FCDProSettings::m_gain1Index, FCDProSettings::m_gain2Index, FCDProSettings::m_gain3Index, FCDProSettings::m_gain4Index, FCDProSettings::m_gain5Index, FCDProSettings::m_gain6Index, FCDProSettings::m_ifFilterIndex, FCDProSettings::m_iqCorrection, FCDProSettings::m_lnaEnhanceIndex, FCDProSettings::m_lnaGainIndex, FCDProSettings::m_log2Decim, FCDProSettings::m_LOppmTenths, FCDProSettings::m_mixerFilterIndex, FCDProSettings::m_mixerGainIndex, FCDProSettings::m_modeIndex, m_networkManager, m_networkRequest, FCDProSettings::m_rcFilterIndex, FCDProSettings::m_reverseAPIAddress, FCDProSettings::m_reverseAPIDeviceIndex, FCDProSettings::m_reverseAPIPort, FCDProSettings::m_rfFilterIndex, FCDProSettings::m_transverterDeltaFrequency, FCDProSettings::m_transverterMode, SWGSDRangel::SWGFCDProSettings::setBandIndex(), SWGSDRangel::SWGFCDProSettings::setBiasCurrentIndex(), SWGSDRangel::SWGFCDProSettings::setCenterFrequency(), SWGSDRangel::SWGFCDProSettings::setDcBlock(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGDeviceSettings::setFcdProSettings(), SWGSDRangel::SWGFCDProSettings::setFcPos(), SWGSDRangel::SWGFCDProSettings::setFileRecordName(), SWGSDRangel::SWGFCDProSettings::setGain1Index(), SWGSDRangel::SWGFCDProSettings::setGain2Index(), SWGSDRangel::SWGFCDProSettings::setGain3Index(), SWGSDRangel::SWGFCDProSettings::setGain4Index(), SWGSDRangel::SWGFCDProSettings::setGain5Index(), SWGSDRangel::SWGFCDProSettings::setGain6Index(), SWGSDRangel::SWGFCDProSettings::setIfFilterIndex(), SWGSDRangel::SWGFCDProSettings::setIqCorrection(), SWGSDRangel::SWGFCDProSettings::setLnaEnhanceIndex(), SWGSDRangel::SWGFCDProSettings::setLnaGainIndex(), SWGSDRangel::SWGFCDProSettings::setLog2Decim(), SWGSDRangel::SWGFCDProSettings::setLOppmTenths(), SWGSDRangel::SWGFCDProSettings::setMixerFilterIndex(), SWGSDRangel::SWGFCDProSettings::setMixerGainIndex(), SWGSDRangel::SWGFCDProSettings::setModeIndex(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGFCDProSettings::setRcFilterIndex(), SWGSDRangel::SWGFCDProSettings::setRfFilterIndex(), SWGSDRangel::SWGFCDProSettings::setTransverterDeltaFrequency(), and SWGSDRangel::SWGFCDProSettings::setTransverterMode().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("FCDPro"));
     swgDeviceSettings->setFcdProSettings(new SWGSDRangel::SWGFCDProSettings());
     SWGSDRangel::SWGFCDProSettings *swgFCDProSettings = swgDeviceSettings->getFcdProSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgFCDProSettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("LOppmTenths") || force) {
         swgFCDProSettings->setLOppmTenths(settings.m_LOppmTenths);
     }
     if (deviceSettingsKeys.contains("lnaGainIndex") || force) {
         swgFCDProSettings->setLnaGainIndex(settings.m_lnaGainIndex);
     }
     if (deviceSettingsKeys.contains("rfFilterIndex") || force) {
         swgFCDProSettings->setRfFilterIndex(settings.m_rfFilterIndex);
     }
     if (deviceSettingsKeys.contains("lnaEnhanceIndex") || force) {
         swgFCDProSettings->setLnaEnhanceIndex(settings.m_lnaEnhanceIndex);
     }
     if (deviceSettingsKeys.contains("bandIndex") || force) {
         swgFCDProSettings->setBandIndex(settings.m_bandIndex);
     }
     if (deviceSettingsKeys.contains("mixerGainIndex") || force) {
         swgFCDProSettings->setMixerGainIndex(settings.m_mixerGainIndex);
     }
     if (deviceSettingsKeys.contains("mixerFilterIndex") || force) {
         swgFCDProSettings->setMixerFilterIndex(settings.m_mixerFilterIndex);
     }
     if (deviceSettingsKeys.contains("biasCurrentIndex") || force) {
         swgFCDProSettings->setBiasCurrentIndex(settings.m_biasCurrentIndex);
     }
     if (deviceSettingsKeys.contains("modeIndex") || force) {
         swgFCDProSettings->setModeIndex(settings.m_modeIndex);
     }
     if (deviceSettingsKeys.contains("gain1Index") || force) {
         swgFCDProSettings->setGain1Index(settings.m_gain1Index);
     }
     if (deviceSettingsKeys.contains("gain2Index") || force) {
         swgFCDProSettings->setGain2Index(settings.m_gain2Index);
     }
     if (deviceSettingsKeys.contains("gain3Index") || force) {
         swgFCDProSettings->setGain3Index(settings.m_gain3Index);
     }
     if (deviceSettingsKeys.contains("gain4Index") || force) {
         swgFCDProSettings->setGain4Index(settings.m_gain4Index);
     }
     if (deviceSettingsKeys.contains("gain5Index") || force) {
         swgFCDProSettings->setGain5Index(settings.m_gain5Index);
     }
     if (deviceSettingsKeys.contains("gain6Index") || force) {
         swgFCDProSettings->setGain6Index(settings.m_gain6Index);
     }
     if (deviceSettingsKeys.contains("log2Decim") || force) {
         swgFCDProSettings->setLog2Decim(settings.m_log2Decim);
     }
     if (deviceSettingsKeys.contains("fcPos") || force) {
         swgFCDProSettings->setFcPos(settings.m_fcPos);
     }
     if (deviceSettingsKeys.contains("rcFilterIndex") || force) {
         swgFCDProSettings->setRcFilterIndex(settings.m_rcFilterIndex);
     }
     if (deviceSettingsKeys.contains("ifFilterIndex") || force) {
         swgFCDProSettings->setIfFilterIndex(settings.m_ifFilterIndex);
     }
     if (deviceSettingsKeys.contains("dcBlock") || force) {
         swgFCDProSettings->setDcBlock(settings.m_dcBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("iqCorrection") || force) {
         swgFCDProSettings->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency") || force) {
         swgFCDProSettings->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     }
     if (deviceSettingsKeys.contains("transverterMode") || force) {
         swgFCDProSettings->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgFCDProSettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void FCDProInput::webapiReverseSendStartStop (bool start) private
Definition at line 1128 of file fcdproinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, FCDProSettings::m_reverseAPIAddress, FCDProSettings::m_reverseAPIDeviceIndex, FCDProSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("FCDPro"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int FCDProInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 838 of file fcdproinput.cpp.
References FCDProInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int FCDProInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 829 of file fcdproinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int FCDProInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 857 of file fcdproinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getFcdProSettings(), SWGSDRangel::SWGFCDProSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setFcdProSettings(), and webapiFormatDeviceSettings().
 {
     (void) errorMessage;
     response.setFcdProSettings(new SWGSDRangel::SWGFCDProSettings());
     response.getFcdProSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int FCDProInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 868 of file fcdproinput.cpp.
References FCDProInput::MsgConfigureFCDPro::create(), SWGSDRangel::SWGFCDProSettings::getBandIndex(), SWGSDRangel::SWGFCDProSettings::getBiasCurrentIndex(), SWGSDRangel::SWGFCDProSettings::getCenterFrequency(), SWGSDRangel::SWGFCDProSettings::getDcBlock(), SWGSDRangel::SWGDeviceSettings::getFcdProSettings(), SWGSDRangel::SWGFCDProSettings::getFcPos(), SWGSDRangel::SWGFCDProSettings::getFileRecordName(), SWGSDRangel::SWGFCDProSettings::getGain1Index(), SWGSDRangel::SWGFCDProSettings::getGain2Index(), SWGSDRangel::SWGFCDProSettings::getGain3Index(), SWGSDRangel::SWGFCDProSettings::getGain4Index(), SWGSDRangel::SWGFCDProSettings::getGain5Index(), SWGSDRangel::SWGFCDProSettings::getGain6Index(), SWGSDRangel::SWGFCDProSettings::getIfFilterIndex(), SWGSDRangel::SWGFCDProSettings::getIqCorrection(), SWGSDRangel::SWGFCDProSettings::getLnaEnhanceIndex(), SWGSDRangel::SWGFCDProSettings::getLnaGainIndex(), SWGSDRangel::SWGFCDProSettings::getLog2Decim(), SWGSDRangel::SWGFCDProSettings::getLOppmTenths(), SWGSDRangel::SWGFCDProSettings::getMixerFilterIndex(), SWGSDRangel::SWGFCDProSettings::getMixerGainIndex(), SWGSDRangel::SWGFCDProSettings::getModeIndex(), SWGSDRangel::SWGFCDProSettings::getRcFilterIndex(), SWGSDRangel::SWGFCDProSettings::getReverseApiAddress(), SWGSDRangel::SWGFCDProSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGFCDProSettings::getReverseApiPort(), SWGSDRangel::SWGFCDProSettings::getRfFilterIndex(), SWGSDRangel::SWGFCDProSettings::getTransverterDeltaFrequency(), SWGSDRangel::SWGFCDProSettings::getTransverterMode(), SWGSDRangel::SWGFCDProSettings::getUseReverseApi(), FCDProSettings::m_bandIndex, FCDProSettings::m_biasCurrentIndex, FCDProSettings::m_centerFrequency, FCDProSettings::m_dcBlock, FCDProSettings::m_fcPos, FCDProSettings::m_fileRecordName, FCDProSettings::m_gain1Index, FCDProSettings::m_gain2Index, FCDProSettings::m_gain3Index, FCDProSettings::m_gain4Index, FCDProSettings::m_gain5Index, FCDProSettings::m_gain6Index, DeviceSampleSource::m_guiMessageQueue, FCDProSettings::m_ifFilterIndex, DeviceSampleSource::m_inputMessageQueue, FCDProSettings::m_iqCorrection, FCDProSettings::m_lnaEnhanceIndex, FCDProSettings::m_lnaGainIndex, FCDProSettings::m_log2Decim, FCDProSettings::m_LOppmTenths, FCDProSettings::m_mixerFilterIndex, FCDProSettings::m_mixerGainIndex, FCDProSettings::m_modeIndex, FCDProSettings::m_rcFilterIndex, FCDProSettings::m_reverseAPIAddress, FCDProSettings::m_reverseAPIDeviceIndex, FCDProSettings::m_reverseAPIPort, FCDProSettings::m_rfFilterIndex, m_settings, FCDProSettings::m_transverterDeltaFrequency, FCDProSettings::m_transverterMode, FCDProSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatDeviceSettings().
 {
     (void) errorMessage;
     FCDProSettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getFcdProSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("LOppmTenths")) {
         settings.m_LOppmTenths = response.getFcdProSettings()->getLOppmTenths();
     }
     if (deviceSettingsKeys.contains("lnaGainIndex")) {
         settings.m_lnaGainIndex = response.getFcdProSettings()->getLnaGainIndex();
     }
     if (deviceSettingsKeys.contains("rfFilterIndex")) {
         settings.m_rfFilterIndex = response.getFcdProSettings()->getRfFilterIndex();
     }
     if (deviceSettingsKeys.contains("lnaEnhanceIndex")) {
         settings.m_lnaEnhanceIndex = response.getFcdProSettings()->getLnaEnhanceIndex();
     }
     if (deviceSettingsKeys.contains("bandIndex")) {
         settings.m_bandIndex = response.getFcdProSettings()->getBandIndex();
     }
     if (deviceSettingsKeys.contains("mixerGainIndex")) {
         settings.m_mixerGainIndex = response.getFcdProSettings()->getMixerGainIndex();
     }
     if (deviceSettingsKeys.contains("mixerFilterIndex")) {
         settings.m_mixerFilterIndex = response.getFcdProSettings()->getMixerFilterIndex();
     }
     if (deviceSettingsKeys.contains("biasCurrentIndex")) {
         settings.m_biasCurrentIndex = response.getFcdProSettings()->getBiasCurrentIndex();
     }
     if (deviceSettingsKeys.contains("modeIndex")) {
         settings.m_modeIndex = response.getFcdProSettings()->getModeIndex();
     }
     if (deviceSettingsKeys.contains("gain1Index")) {
         settings.m_gain1Index = response.getFcdProSettings()->getGain1Index();
     }
     if (deviceSettingsKeys.contains("gain2Index")) {
         settings.m_gain2Index = response.getFcdProSettings()->getGain2Index();
     }
     if (deviceSettingsKeys.contains("gain3Index")) {
         settings.m_gain3Index = response.getFcdProSettings()->getGain3Index();
     }
     if (deviceSettingsKeys.contains("gain4Index")) {
         settings.m_gain4Index = response.getFcdProSettings()->getGain4Index();
     }
     if (deviceSettingsKeys.contains("gain5Index")) {
         settings.m_gain5Index = response.getFcdProSettings()->getGain5Index();
     }
     if (deviceSettingsKeys.contains("gain6Index")) {
         settings.m_gain6Index = response.getFcdProSettings()->getGain6Index();
     }
     if (deviceSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getFcdProSettings()->getLog2Decim();
     }
     if (deviceSettingsKeys.contains("fcPos")) {
         settings.m_fcPos = (FCDProSettings::fcPos_t) response.getFcdProSettings()->getFcPos();
     }
     if (deviceSettingsKeys.contains("rcFilterIndex")) {
         settings.m_rcFilterIndex = response.getFcdProSettings()->getRcFilterIndex();
     }
     if (deviceSettingsKeys.contains("ifFilterIndex")) {
         settings.m_ifFilterIndex = response.getFcdProSettings()->getIfFilterIndex();
     }
     if (deviceSettingsKeys.contains("dcBlock")) {
         settings.m_dcBlock = response.getFcdProSettings()->getDcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("iqCorrection")) {
         settings.m_iqCorrection = response.getFcdProSettings()->getIqCorrection() != 0;
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency")) {
         settings.m_transverterDeltaFrequency = response.getFcdProSettings()->getTransverterDeltaFrequency();
     }
     if (deviceSettingsKeys.contains("transverterMode")) {
         settings.m_transverterMode = response.getFcdProSettings()->getTransverterMode() != 0;
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getFcdProSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getFcdProSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getFcdProSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getFcdProSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getFcdProSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureFCDPro *msg = MsgConfigureFCDPro::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureFCDPro *msgToGUI = MsgConfigureFCDPro::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_dev
hid_device* FCDProInput::m_dev private
Definition at line 169 of file fcdproinput.h.
Referenced by applySettings(), closeDevice(), openDevice(), set_band(), set_biasCurrent(), set_center_freq(), set_gain1(), set_gain2(), set_gain3(), set_gain4(), set_gain5(), set_gain6(), set_ifFilter(), set_lnaEnhance(), set_lnaGain(), set_mixerFilter(), set_mixerGain(), set_mode(), set_rcFilter(), set_rfFilter(), and start().
m_deviceAPI
DeviceAPI* FCDProInput::m_deviceAPI private
Definition at line 168 of file fcdproinput.h.
Referenced by applySettings(), handleMessage(), openDevice(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~FCDProInput().
m_deviceDescription
QString FCDProInput::m_deviceDescription private
Definition at line 175 of file fcdproinput.h.
Referenced by getDeviceDescription().
m_fcdAudioInput
AudioInput FCDProInput::m_fcdAudioInput private
Definition at line 170 of file fcdproinput.h.
Referenced by closeFCDAudio(), and openFCDAudio().
m_fcdFIFO
AudioFifo FCDProInput::m_fcdFIFO private
Definition at line 171 of file fcdproinput.h.
Referenced by closeFCDAudio(), openFCDAudio(), and start().
m_FCDThread
FCDProThread* FCDProInput::m_FCDThread private
Definition at line 174 of file fcdproinput.h.
Referenced by applySettings(), start(), and stop().
m_fileSink
FileRecord* FCDProInput::m_fileSink private
File sink to record device I/Q output.
Definition at line 177 of file fcdproinput.h.
Referenced by applySettings(), handleMessage(), and ~FCDProInput().
m_mutex
QMutex FCDProInput::m_mutex private
Definition at line 172 of file fcdproinput.h.
m_networkManager
QNetworkAccessManager* FCDProInput::m_networkManager private
Definition at line 178 of file fcdproinput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~FCDProInput().
m_networkRequest
QNetworkRequest FCDProInput::m_networkRequest private
Definition at line 179 of file fcdproinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool FCDProInput::m_running private
Definition at line 176 of file fcdproinput.h.
Referenced by start(), stop(), and ~FCDProInput().
m_settings
FCDProSettings FCDProInput::m_settings private
Definition at line 173 of file fcdproinput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), serialize(), set_center_freq(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
The documentation for this class was generated from the following files:
plugins/samplesource/fcdpro/fcdproinput.h
plugins/samplesource/fcdpro/fcdproinput.cpp