SDRAngel: AirspyGui Class Reference
AirspyGui Class Reference
#include <airspygui.h>
Public Member Functions
AirspyGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~AirspyGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
uint32_t getDevSampleRate (unsigned int index)
int getDevSampleRateIndex (uint32_t sampleRate)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void on_centerFrequency_changed (quint64 value)
void on_LOppm_valueChanged (int value)
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_sampleRate_currentIndexChanged (int index)
void on_biasT_stateChanged (int state)
void on_decim_currentIndexChanged (int index)
void on_fcPos_currentIndexChanged (int index)
void on_lna_valueChanged (int value)
void on_mix_valueChanged (int value)
void on_vga_valueChanged (int value)
void on_lnaAGC_stateChanged (int state)
void on_mixAGC_stateChanged (int state)
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void on_transverter_clicked ()
void updateHardware ()
void updateStatus ()
void handleInputMessages ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void displaySampleRates ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void updateFrequencyLimits ()
Private Attributes
Ui::AirspyGui * ui
DeviceUISet * m_deviceUISet
bool m_doApplySettings
bool m_forceSettings
AirspySettings m_settings
QTimer m_updateTimer
QTimer m_statusTimer
std::vector< uint32_t > m_rates
DeviceSampleSource * m_sampleSource
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 35 of file airspygui.h.
Constructor & Destructor Documentation
AirspyGui()
AirspyGui::AirspyGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 37 of file airspygui.cpp.
References displaySampleRates(), displaySettings(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_rates, m_sampleSource, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), sendSettings(), DeviceSampleSource::setMessageQueueToGUI(), ui, updateFrequencyLimits(), updateHardware(), and updateStatus().
                                                               :
     QWidget(parent),
     ui(new Ui::AirspyGui),
     m_deviceUISet(deviceUISet),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_settings(),
     m_sampleSource(0),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     m_sampleSource = (AirspyInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     updateFrequencyLimits();
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     m_rates = ((AirspyInput*) m_sampleSource)->getSampleRates();
     displaySampleRates();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
     sendSettings();
 }
~AirspyGui()
AirspyGui::~AirspyGui () virtual
Definition at line 70 of file airspygui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void AirspyGui::blockApplySettings (bool block) inline private
Definition at line 72 of file airspygui.h.
Referenced by handleMessage().
 { m_doApplySettings = !block; }
deserialize()
bool AirspyGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 114 of file airspygui.cpp.
References AirspySettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void AirspyGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 75 of file airspygui.cpp.
 {
     delete this;
 }
displaySampleRates()
void AirspyGui::displaySampleRates () private
Definition at line 236 of file airspygui.cpp.
References arg(), i, AirspySettings::m_devSampleRateIndex, m_rates, m_settings, and ui.
Referenced by AirspyGui().
 {
     unsigned int savedIndex = m_settings.m_devSampleRateIndex;
     ui->sampleRate->blockSignals(true);
     if (m_rates.size() > 0)
     {
         ui->sampleRate->clear();
         for (unsigned int i = 0; i < m_rates.size(); i++)
         {
             ui->sampleRate->addItem(QString("%1").arg(QString::number(m_rates[i]/1000000.0, 'f', 1)));
         }
     }
     ui->sampleRate->blockSignals(false);
     if (savedIndex < m_rates.size())
     {
         ui->sampleRate->setCurrentIndex(savedIndex);
     }
     else
     {
         ui->sampleRate->setCurrentIndex((int) m_rates.size()-1);
     }
 }
displaySettings()
void AirspyGui::displaySettings () private
Definition at line 203 of file airspygui.cpp.
References arg(), AirspySettings::m_biasT, AirspySettings::m_centerFrequency, AirspySettings::m_dcBlock, AirspySettings::m_devSampleRateIndex, AirspySettings::m_fcPos, AirspySettings::m_iqCorrection, AirspySettings::m_lnaAGC, AirspySettings::m_lnaGain, AirspySettings::m_log2Decim, AirspySettings::m_LOppmTenths, AirspySettings::m_mixerAGC, AirspySettings::m_mixerGain, m_settings, AirspySettings::m_transverterDeltaFrequency, AirspySettings::m_transverterMode, AirspySettings::m_vgaGain, ui, and updateFrequencyLimits().
Referenced by AirspyGui(), deserialize(), handleMessage(), resetToDefaults(), and setCenterFrequency().
 {
     ui->transverter->setDeltaFrequency(m_settings.m_transverterDeltaFrequency);
     ui->transverter->setDeltaFrequencyActive(m_settings.m_transverterMode);
     updateFrequencyLimits();
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     ui->LOppm->setValue(m_settings.m_LOppmTenths);
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     ui->sampleRate->setCurrentIndex(m_settings.m_devSampleRateIndex);
     ui->biasT->setChecked(m_settings.m_biasT);
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqCorrection);
     ui->decim->setCurrentIndex(m_settings.m_log2Decim);
     ui->fcPos->setCurrentIndex((int) m_settings.m_fcPos);
     ui->lnaGainText->setText(tr("%1dB").arg(m_settings.m_lnaGain));
     ui->lna->setValue(m_settings.m_lnaGain);
     ui->mixText->setText(tr("%1dB").arg(m_settings.m_mixerGain));
     ui->mix->setValue(m_settings.m_mixerGain);
     ui->vgaText->setText(tr("%1dB").arg(m_settings.m_vgaGain));
     ui->vga->setValue(m_settings.m_vgaGain);
     ui->lnaAGC->setChecked(m_settings.m_lnaAGC);
     ui->mixAGC->setChecked(m_settings.m_mixerAGC);
 }
getCenterFrequency()
qint64 AirspyGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 97 of file airspygui.cpp.
References AirspySettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getDevSampleRate()
uint32_t AirspyGui::getDevSampleRate (unsigned int index)
Definition at line 439 of file airspygui.cpp.
References m_rates.
 {
     if (rate_index < m_rates.size())
     {
         return m_rates[rate_index];
     }
     else
     {
         return m_rates[0];
     }
 }
getDevSampleRateIndex()
int AirspyGui::getDevSampleRateIndex (uint32_t sampleRate)
Definition at line 451 of file airspygui.cpp.
References i, and m_rates.
 {
     for (unsigned int i=0; i < m_rates.size(); i++)
     {
         if (sampeRate == m_rates[i])
         {
             return i;
         }
     }
     return -1;
 }
getInputMessageQueue()
virtual MessageQueue* AirspyGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 51 of file airspygui.h.
 { return &m_inputMessageQueue; }
getName()
QString AirspyGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 85 of file airspygui.cpp.
 {
     return objectName();
 }
handleInputMessages
void AirspyGui::handleInputMessages () private slot
Definition at line 153 of file airspygui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by AirspyGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("AirspyGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("AirspyGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool AirspyGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 127 of file airspygui.cpp.
References blockApplySettings(), displaySettings(), AirspyInput::MsgConfigureAirspy::getSettings(), AirspyInput::MsgStartStop::getStartStop(), m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (AirspyInput::MsgConfigureAirspy::match(message))
     {
         const AirspyInput::MsgConfigureAirspy& cfg = (AirspyInput::MsgConfigureAirspy&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (AirspyInput::MsgStartStop::match(message))
     {
         AirspyInput::MsgStartStop& notif = (AirspyInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_biasT_stateChanged
void AirspyGui::on_biasT_stateChanged (int state) private slot
Definition at line 300 of file airspygui.cpp.
References AirspySettings::m_biasT, m_settings, and sendSettings().
 {
     m_settings.m_biasT = (state == Qt::Checked);
     sendSettings();
 }
on_centerFrequency_changed
void AirspyGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 269 of file airspygui.cpp.
References AirspySettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_dcOffset_toggled
void AirspyGui::on_dcOffset_toggled (bool checked) private slot
Definition at line 282 of file airspygui.cpp.
References AirspySettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_decim_currentIndexChanged
void AirspyGui::on_decim_currentIndexChanged (int index) private slot
Definition at line 318 of file airspygui.cpp.
References AirspySettings::m_log2Decim, m_settings, and sendSettings().
 {
     if ((index <0) || (index > 6))
         return;
     m_settings.m_log2Decim = index;
     sendSettings();
 }
on_fcPos_currentIndexChanged
void AirspyGui::on_fcPos_currentIndexChanged (int index) private slot
Definition at line 326 of file airspygui.cpp.
References AirspySettings::FC_POS_CENTER, AirspySettings::FC_POS_INFRA, AirspySettings::FC_POS_SUPRA, AirspySettings::m_fcPos, m_settings, and sendSettings().
 {
     if (index == 0) {
         m_settings.m_fcPos = AirspySettings::FC_POS_INFRA;
         sendSettings();
     } else if (index == 1) {
         m_settings.m_fcPos = AirspySettings::FC_POS_SUPRA;
         sendSettings();
     } else if (index == 2) {
         m_settings.m_fcPos = AirspySettings::FC_POS_CENTER;
         sendSettings();
     }
 }
on_iqImbalance_toggled
void AirspyGui::on_iqImbalance_toggled (bool checked) private slot
Definition at line 288 of file airspygui.cpp.
References AirspySettings::m_iqCorrection, m_settings, and sendSettings().
 {
     m_settings.m_iqCorrection = checked;
     sendSettings();
 }
on_lna_valueChanged
void AirspyGui::on_lna_valueChanged (int value) private slot
Definition at line 340 of file airspygui.cpp.
References arg(), AirspySettings::m_lnaGain, m_settings, sendSettings(), and ui.
 {
     if ((value < 0) || (value > 14))
         return;
     ui->lnaGainText->setText(tr("%1dB").arg(value));
     m_settings.m_lnaGain = value;
     sendSettings();
 }
on_lnaAGC_stateChanged
void AirspyGui::on_lnaAGC_stateChanged (int state) private slot
Definition at line 306 of file airspygui.cpp.
References AirspySettings::m_lnaAGC, m_settings, and sendSettings().
 {
     m_settings.m_lnaAGC = (state == Qt::Checked);
     sendSettings();
 }
on_LOppm_valueChanged
void AirspyGui::on_LOppm_valueChanged (int value) private slot
Definition at line 275 of file airspygui.cpp.
References arg(), AirspySettings::m_LOppmTenths, m_settings, sendSettings(), and ui.
 {
     m_settings.m_LOppmTenths = value;
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     sendSettings();
 }
on_mix_valueChanged
void AirspyGui::on_mix_valueChanged (int value) private slot
Definition at line 350 of file airspygui.cpp.
References arg(), AirspySettings::m_mixerGain, m_settings, sendSettings(), and ui.
 {
     if ((value < 0) || (value > 15))
         return;
     ui->mixText->setText(tr("%1dB").arg(value));
     m_settings.m_mixerGain = value;
     sendSettings();
 }
on_mixAGC_stateChanged
void AirspyGui::on_mixAGC_stateChanged (int state) private slot
Definition at line 312 of file airspygui.cpp.
References AirspySettings::m_mixerAGC, m_settings, and sendSettings().
 {
     m_settings.m_mixerAGC = (state == Qt::Checked);
     sendSettings();
 }
on_record_toggled
void AirspyGui::on_record_toggled (bool checked) private slot
Definition at line 379 of file airspygui.cpp.
References AirspyInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     AirspyInput::MsgFileRecord* message = AirspyInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_sampleRate_currentIndexChanged
void AirspyGui::on_sampleRate_currentIndexChanged (int index) private slot
Definition at line 294 of file airspygui.cpp.
References AirspySettings::m_devSampleRateIndex, m_settings, and sendSettings().
 {
     m_settings.m_devSampleRateIndex = index;
     sendSettings();
 }
on_startStop_toggled
void AirspyGui::on_startStop_toggled (bool checked) private slot
Definition at line 370 of file airspygui.cpp.
References AirspyInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         AirspyInput::MsgStartStop *message = AirspyInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
on_transverter_clicked
void AirspyGui::on_transverter_clicked () private slot
Definition at line 391 of file airspygui.cpp.
References AirspySettings::m_centerFrequency, m_settings, AirspySettings::m_transverterDeltaFrequency, AirspySettings::m_transverterMode, sendSettings(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("AirspyGui::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     m_settings.m_centerFrequency = ui->centerFrequency->getValueNew()*1000;
     sendSettings();
 }
on_vga_valueChanged
void AirspyGui::on_vga_valueChanged (int value) private slot
Definition at line 360 of file airspygui.cpp.
References arg(), m_settings, AirspySettings::m_vgaGain, sendSettings(), and ui.
 {
     if ((value < 0) || (value > 15))
         return;
     ui->vgaText->setText(tr("%1dB").arg(value));
     m_settings.m_vgaGain = value;
     sendSettings();
 }
openDeviceSettingsDialog
void AirspyGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 464 of file airspygui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), AirspySettings::m_reverseAPIAddress, AirspySettings::m_reverseAPIDeviceIndex, AirspySettings::m_reverseAPIPort, m_settings, AirspySettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by AirspyGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void AirspyGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 90 of file airspygui.cpp.
References displaySettings(), m_settings, AirspySettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void AirspyGui::sendSettings () private
Definition at line 263 of file airspygui.cpp.
References m_updateTimer.
Referenced by AirspyGui(), deserialize(), on_biasT_stateChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_iqImbalance_toggled(), on_lna_valueChanged(), on_lnaAGC_stateChanged(), on_LOppm_valueChanged(), on_mix_valueChanged(), on_mixAGC_stateChanged(), on_sampleRate_currentIndexChanged(), on_transverter_clicked(), on_vga_valueChanged(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray AirspyGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 109 of file airspygui.cpp.
References m_settings, and AirspySettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void AirspyGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 102 of file airspygui.cpp.
References displaySettings(), AirspySettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void AirspyGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 80 of file airspygui.cpp.
 {
     setObjectName(name);
 }
updateFrequencyLimits()
void AirspyGui::updateFrequencyLimits () private
Definition at line 188 of file airspygui.cpp.
References AirspyInput::loHighLimitFreq, AirspyInput::loLowLimitFreq, m_settings, AirspySettings::m_transverterDeltaFrequency, AirspySettings::m_transverterMode, and ui.
Referenced by AirspyGui(), displaySettings(), and on_transverter_clicked().
 {
     // values in kHz
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     qint64 minLimit = AirspyInput::loLowLimitFreq/1000 + deltaFrequency;
     qint64 maxLimit = AirspyInput::loHighLimitFreq/1000 + deltaFrequency;
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("AirspyGui::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void AirspyGui::updateHardware () private slot
Definition at line 401 of file airspygui.cpp.
References AirspyInput::MsgConfigureAirspy::create(), DeviceSampleSource::getInputMessageQueue(), m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by AirspyGui().
 {
     qDebug() << "AirspyGui::updateHardware";
     AirspyInput::MsgConfigureAirspy* message = AirspyInput::MsgConfigureAirspy::create(m_settings, m_forceSettings);
     m_sampleSource->getInputMessageQueue()->push(message);
     m_forceSettings = false;
     m_updateTimer.stop();
 }
updateSampleRateAndFrequency()
void AirspyGui::updateSampleRateAndFrequency () private
Definition at line 181 of file airspygui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg((float)m_sampleRate / 1000));
 }
updateStatus
void AirspyGui::updateStatus () private slot
Definition at line 410 of file airspygui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by AirspyGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 AirspyGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 68 of file airspygui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* AirspyGui::m_deviceUISet private
Definition at line 59 of file airspygui.h.
Referenced by AirspyGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool AirspyGui::m_doApplySettings private
Definition at line 60 of file airspygui.h.
Referenced by on_startStop_toggled().
m_forceSettings
bool AirspyGui::m_forceSettings private
Definition at line 61 of file airspygui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue AirspyGui::m_inputMessageQueue private
Definition at line 70 of file airspygui.h.
Referenced by AirspyGui(), and handleInputMessages().
m_lastEngineState
int AirspyGui::m_lastEngineState private
Definition at line 69 of file airspygui.h.
Referenced by updateStatus().
m_rates
std::vector<uint32_t> AirspyGui::m_rates private
Definition at line 65 of file airspygui.h.
Referenced by AirspyGui(), displaySampleRates(), getDevSampleRate(), and getDevSampleRateIndex().
m_sampleRate
int AirspyGui::m_sampleRate private
Definition at line 67 of file airspygui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleSource
DeviceSampleSource* AirspyGui::m_sampleSource private
Definition at line 66 of file airspygui.h.
Referenced by AirspyGui(), on_record_toggled(), on_startStop_toggled(), and updateHardware().
m_settings
AirspySettings AirspyGui::m_settings private
Definition at line 62 of file airspygui.h.
Referenced by deserialize(), displaySampleRates(), displaySettings(), getCenterFrequency(), handleMessage(), on_biasT_stateChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_iqImbalance_toggled(), on_lna_valueChanged(), on_lnaAGC_stateChanged(), on_LOppm_valueChanged(), on_mix_valueChanged(), on_mixAGC_stateChanged(), on_sampleRate_currentIndexChanged(), on_transverter_clicked(), on_vga_valueChanged(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), updateFrequencyLimits(), and updateHardware().
m_statusTimer
QTimer AirspyGui::m_statusTimer private
Definition at line 64 of file airspygui.h.
Referenced by AirspyGui().
m_updateTimer
QTimer AirspyGui::m_updateTimer private
Definition at line 63 of file airspygui.h.
Referenced by AirspyGui(), sendSettings(), and updateHardware().
ui
Ui::AirspyGui* AirspyGui::ui private
Definition at line 57 of file airspygui.h.
Referenced by AirspyGui(), displaySampleRates(), displaySettings(), handleMessage(), on_lna_valueChanged(), on_LOppm_valueChanged(), on_mix_valueChanged(), on_record_toggled(), on_transverter_clicked(), on_vga_valueChanged(), updateFrequencyLimits(), updateSampleRateAndFrequency(), updateStatus(), and ~AirspyGui().
The documentation for this class was generated from the following files:
plugins/samplesource/airspy/airspygui.h
plugins/samplesource/airspy/airspygui.cpp