SDRAngel: qtwebapp::HttpSession Class Reference
qtwebapp::HttpSession Class Reference
#include <httpsession.h>
Classes
struct HttpSessionData
Public Member Functions
HttpSession (bool canStore=false)
HttpSession (const HttpSession &other)
HttpSession & operator= (const HttpSession &other)
virtual ~HttpSession ()
QByteArray getId () const
bool isNull () const
void set (const QByteArray &key, const QVariant &value)
void remove (const QByteArray &key)
QVariant get (const QByteArray &key) const
bool contains (const QByteArray &key) const
QMap< QByteArray, QVariant > getAll () const
qint64 getLastAccess () const
void setLastAccess ()
Private Attributes
HttpSessionData * dataPtr
Detailed Description
This class stores data for a single HTTP session. A session can store any number of key/value pairs. This class uses implicit sharing for read and write access. This class is thread safe.
See also
HttpSessionStore should be used to create and get instances of this class.
Definition at line 25 of file httpsession.h.
Constructor & Destructor Documentation
HttpSession() [1/2]
HttpSession::HttpSession (bool canStore = false)
Constructor.
Parameters
canStore The session can store data, if this parameter is true. Otherwise all calls to set() and remove() do not have any effect.
Definition at line 12 of file httpsession.cpp.
References dataPtr, qtwebapp::HttpSession::HttpSessionData::id, qtwebapp::HttpSession::HttpSessionData::lastAccess, and qtwebapp::HttpSession::HttpSessionData::refCount.
 {
     if (canStore)
     {
         dataPtr=new HttpSessionData();
         dataPtr->refCount=1;
         dataPtr->lastAccess=QDateTime::currentMSecsSinceEpoch();
         dataPtr->id=QUuid::createUuid().toString().toLocal8Bit();
 #ifdef SUPERVERBOSE
         qDebug("HttpSession: created new session data with id %s",dataPtr->id.data());
 #endif
     }
     else
     {
         dataPtr=0;
     }
 }
HttpSession() [2/2]
HttpSession::HttpSession (const HttpSession & other)
Copy constructor. Creates another HttpSession object that shares the data of the other object.
Definition at line 30 of file httpsession.cpp.
References dataPtr, qtwebapp::HttpSession::HttpSessionData::id, qtwebapp::HttpSession::HttpSessionData::lock, and qtwebapp::HttpSession::HttpSessionData::refCount.
 {
     dataPtr=other.dataPtr;
     if (dataPtr)
     {
         dataPtr->lock.lockForWrite();
         dataPtr->refCount++;
 #ifdef SUPERVERBOSE
         qDebug("HttpSession: refCount of %s is %i",dataPtr->id.data(),dataPtr->refCount);
 #endif
         dataPtr->lock.unlock();
     }
 }
~HttpSession()
HttpSession::~HttpSession () virtual
Destructor. Detaches from the shared data.
Definition at line 78 of file httpsession.cpp.
References dataPtr, qtwebapp::HttpSession::HttpSessionData::id, qtwebapp::HttpSession::HttpSessionData::lock, and qtwebapp::HttpSession::HttpSessionData::refCount.
 {
     if (dataPtr) {
         int refCount;
         dataPtr->lock.lockForRead();
         refCount=--dataPtr->refCount;
 #ifdef SUPERVERBOSE
         qDebug("HttpSession: refCount of %s is %i",dataPtr->id.data(),dataPtr->refCount);
 #endif
         dataPtr->lock.unlock();
         if (refCount==0)
         {
             qDebug("HttpSession: deleting data");
             delete dataPtr;
         }
     }
 }
Member Function Documentation
contains()
bool HttpSession::contains (const QByteArray & key) const
Check if a key exists. This method is thread safe.
Definition at line 145 of file httpsession.cpp.
References dataPtr, qtwebapp::HttpSession::HttpSessionData::lock, and qtwebapp::HttpSession::HttpSessionData::values.
 {
     bool found=false;
     if (dataPtr)
     {
         dataPtr->lock.lockForRead();
         found=dataPtr->values.contains(key);
         dataPtr->lock.unlock();
     }
     return found;
 }
get()
QVariant HttpSession::get (const QByteArray & key) const
Get a value. This method is thread safe.
Definition at line 133 of file httpsession.cpp.
References dataPtr, qtwebapp::HttpSession::HttpSessionData::lock, and qtwebapp::HttpSession::HttpSessionData::values.
 {
     QVariant value;
     if (dataPtr)
     {
         dataPtr->lock.lockForRead();
         value=dataPtr->values.value(key);
         dataPtr->lock.unlock();
     }
     return value;
 }
getAll()
QMap< QByteArray, QVariant > HttpSession::getAll () const
Get a copy of all data stored in this session. Changes to the session do not affect the copy and vice versa. This method is thread safe.
Definition at line 157 of file httpsession.cpp.
References dataPtr, qtwebapp::HttpSession::HttpSessionData::lock, and qtwebapp::HttpSession::HttpSessionData::values.
 {
     QMap<QByteArray,QVariant> values;
     if (dataPtr)
     {
         dataPtr->lock.lockForRead();
         values=dataPtr->values;
         dataPtr->lock.unlock();
     }
     return values;
 }
getId()
QByteArray HttpSession::getId () const
Get the unique ID of this session. This method is thread safe.
Definition at line 97 of file httpsession.cpp.
References dataPtr, and qtwebapp::HttpSession::HttpSessionData::id.
Referenced by qtwebapp::HttpSessionStore::getSession(), qtwebapp::HttpSessionStore::removeSession(), and qtwebapp::HttpSessionStore::sessionTimerEvent().
 {
     if (dataPtr)
     {
         return dataPtr->id;
     }
     else
     {
         return QByteArray();
     }
 }
getLastAccess()
qint64 HttpSession::getLastAccess () const
Get the timestamp of last access. That is the time when the last HttpSessionStore::getSession() has been called. This method is thread safe.
Definition at line 169 of file httpsession.cpp.
References dataPtr, qtwebapp::HttpSession::HttpSessionData::lastAccess, and qtwebapp::HttpSession::HttpSessionData::lock.
Referenced by qtwebapp::HttpSessionStore::sessionTimerEvent().
 {
     qint64 value=0;
     if (dataPtr)
     {
         dataPtr->lock.lockForRead();
         value=dataPtr->lastAccess;
         dataPtr->lock.unlock();
     }
     return value;
 }
isNull()
bool HttpSession::isNull () const
Null sessions cannot store data. All calls to set() and remove() do not have any effect.This method is thread safe.
Definition at line 109 of file httpsession.cpp.
References dataPtr.
Referenced by qtwebapp::HttpSessionStore::getSession().
{
     return dataPtr==0;
 }
operator=()
HttpSession & HttpSession::operator= (const HttpSession & other)
Copy operator. Detaches from the current shared data and attaches to the data of the other object.
Definition at line 44 of file httpsession.cpp.
References dataPtr, qtwebapp::HttpSession::HttpSessionData::id, qtwebapp::HttpSession::HttpSessionData::lastAccess, qtwebapp::HttpSession::HttpSessionData::lock, and qtwebapp::HttpSession::HttpSessionData::refCount.
 {
     if (this == &other) {
         return *this;
     }
     HttpSessionData* oldPtr=dataPtr;
     dataPtr=other.dataPtr;
     if (dataPtr)
     {
         dataPtr->lock.lockForWrite();
         dataPtr->refCount++;
 #ifdef SUPERVERBOSE
         qDebug("HttpSession: refCount of %s is %i",dataPtr->id.data(),dataPtr->refCount);
 #endif
         dataPtr->lastAccess=QDateTime::currentMSecsSinceEpoch();
         dataPtr->lock.unlock();
     }
     if (oldPtr)
     {
         int refCount;
         oldPtr->lock.lockForRead();
         refCount=oldPtr->refCount--;
 #ifdef SUPERVERBOSE
         qDebug("HttpSession: refCount of %s is %i",oldPtr->id.data(),oldPtr->refCount);
 #endif
         oldPtr->lock.unlock();
         if (refCount==0)
         {
             delete oldPtr;
         }
     }
     return *this;
 }
remove()
void HttpSession::remove (const QByteArray & key)
Remove a value. This method is thread safe.
Definition at line 123 of file httpsession.cpp.
References dataPtr, qtwebapp::HttpSession::HttpSessionData::lock, and qtwebapp::HttpSession::HttpSessionData::values.
 {
     if (dataPtr)
     {
         dataPtr->lock.lockForWrite();
         dataPtr->values.remove(key);
         dataPtr->lock.unlock();
     }
 }
set()
void HttpSession::set (const QByteArray & key, const QVariant & value)
Set a value. This method is thread safe.
Definition at line 113 of file httpsession.cpp.
References dataPtr, qtwebapp::HttpSession::HttpSessionData::lock, and qtwebapp::HttpSession::HttpSessionData::values.
 {
     if (dataPtr)
     {
         dataPtr->lock.lockForWrite();
         dataPtr->values.insert(key,value);
         dataPtr->lock.unlock();
     }
 }
setLastAccess()
void HttpSession::setLastAccess ()
Set the timestamp of last access, to renew the timeout period. Called by HttpSessionStore::getSession(). This method is thread safe.
Definition at line 182 of file httpsession.cpp.
References dataPtr, qtwebapp::HttpSession::HttpSessionData::lastAccess, and qtwebapp::HttpSession::HttpSessionData::lock.
Referenced by qtwebapp::HttpSessionStore::getSession().
 {
     if (dataPtr)
     {
         dataPtr->lock.lockForRead();
         dataPtr->lastAccess=QDateTime::currentMSecsSinceEpoch();
         dataPtr->lock.unlock();
     }
 }
Member Data Documentation
dataPtr
HttpSessionData* qtwebapp::HttpSession::dataPtr private
Pointer to the shared data.
Definition at line 118 of file httpsession.h.
Referenced by contains(), get(), getAll(), getId(), getLastAccess(), HttpSession(), isNull(), operator=(), remove(), set(), setLastAccess(), and ~HttpSession().
The documentation for this class was generated from the following files:
httpserver/httpsession.h
httpserver/httpsession.cpp