SDRAngel: RemoteInput::MsgStartStop Class Reference
RemoteInput::MsgStartStop Class Reference
#include <remoteinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 252 of file remoteinput.h.
Constructor & Destructor Documentation
MsgStartStop()
RemoteInput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 265 of file remoteinput.h.
References RemoteInput::deserialize(), RemoteInput::destroy(), RemoteInput::getDeviceDescription(), RemoteInput::getSampleRate(), RemoteInput::init(), RemoteInput::RemoteInput(), RemoteInput::serialize(), RemoteInput::setMessageQueueToGUI(), RemoteInput::start(), RemoteInput::stop(), and RemoteInput::~RemoteInput().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* RemoteInput::MsgStartStop::create (bool startStop) inline static
Definition at line 258 of file remoteinput.h.
Referenced by RemoteInputGui::on_startStop_toggled(), and RemoteInput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool RemoteInput::MsgStartStop::getStartStop () const inline
Definition at line 256 of file remoteinput.h.
Referenced by RemoteInputGui::handleMessage(), and RemoteInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool RemoteInput::MsgStartStop::m_startStop protected
Definition at line 263 of file remoteinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/remoteinput/remoteinput.h