SDRAngel: SSBMod::MsgConfigureSSBMod Class Reference
SSBMod::MsgConfigureSSBMod Class Reference
#include <ssbmod.h>
Public Member Functions
const SSBModSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureSSBMod * create (const SSBModSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureSSBMod (const SSBModSettings &settings, bool force)
Private Attributes
SSBModSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 53 of file ssbmod.h.
Constructor & Destructor Documentation
MsgConfigureSSBMod()
SSBMod::MsgConfigureSSBMod::MsgConfigureSSBMod (const SSBModSettings & settings, bool force) inline private
Definition at line 69 of file ssbmod.h.
Referenced by create().
                                                                        :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureSSBMod* SSBMod::MsgConfigureSSBMod::create (const SSBModSettings & settings, bool force) inline static
Definition at line 60 of file ssbmod.h.
References MsgConfigureSSBMod().
Referenced by SSBModGUI::applySettings(), SSBMod::deserialize(), and SSBMod::webapiSettingsPutPatch().
         {
             return new MsgConfigureSSBMod(settings, force);
         }
getForce()
bool SSBMod::MsgConfigureSSBMod::getForce () const inline
Definition at line 58 of file ssbmod.h.
References m_force.
Referenced by SSBMod::handleMessage().
 { return m_force; }
getSettings()
const SSBModSettings& SSBMod::MsgConfigureSSBMod::getSettings () const inline
Definition at line 57 of file ssbmod.h.
References m_settings.
Referenced by SSBModGUI::handleMessage(), and SSBMod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool SSBMod::MsgConfigureSSBMod::m_force private
Definition at line 67 of file ssbmod.h.
Referenced by getForce().
m_settings
SSBModSettings SSBMod::MsgConfigureSSBMod::m_settings private
Definition at line 66 of file ssbmod.h.
Referenced by SSBMod::getCenterFrequency(), getSettings(), SSBMod::getStreamCenterFrequency(), and SSBMod::getTitle().
The documentation for this class was generated from the following file:
plugins/channeltx/modssb/ssbmod.h