SDRAngel: FCDProInput::MsgConfigureFCDPro Class Reference
FCDProInput::MsgConfigureFCDPro Class Reference
#include <fcdproinput.h>
Public Member Functions
const FCDProSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureFCDPro * create (const FCDProSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureFCDPro (const FCDProSettings &settings, bool force)
Private Attributes
FCDProSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 48 of file fcdproinput.h.
Constructor & Destructor Documentation
MsgConfigureFCDPro()
FCDProInput::MsgConfigureFCDPro::MsgConfigureFCDPro (const FCDProSettings & settings, bool force) inline private
Definition at line 64 of file fcdproinput.h.
                                                                        :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureFCDPro* FCDProInput::MsgConfigureFCDPro::create (const FCDProSettings & settings, bool force) inline static
Definition at line 55 of file fcdproinput.h.
Referenced by FCDProInput::deserialize(), FCDProInput::setCenterFrequency(), FCDProGui::updateHardware(), and FCDProInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureFCDPro(settings, force);
         }
getForce()
bool FCDProInput::MsgConfigureFCDPro::getForce () const inline
Definition at line 53 of file fcdproinput.h.
Referenced by FCDProInput::handleMessage().
 { return m_force; }
getSettings()
const FCDProSettings& FCDProInput::MsgConfigureFCDPro::getSettings () const inline
Definition at line 52 of file fcdproinput.h.
Referenced by FCDProGui::handleMessage(), and FCDProInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool FCDProInput::MsgConfigureFCDPro::m_force private
Definition at line 62 of file fcdproinput.h.
m_settings
FCDProSettings FCDProInput::MsgConfigureFCDPro::m_settings private
Definition at line 61 of file fcdproinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/fcdpro/fcdproinput.h