SDRAngel: DATVDemod Class Reference
DATVDemod Class Reference
#include <datvdemod.h>
Classes
class MsgConfigureChannelizer
class MsgConfigureDATVDemod
class MsgReportModcodCstlnChange
Public Member Functions
DATVDemod (DeviceAPI *)
~DATVDemod ()
virtual void destroy ()
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool po)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
bool SetTVScreen (TVScreen *objScreen)
DATVideostream * SetVideoRender (DATVideoRender *objScreen)
bool audioActive ()
bool audioDecodeOK ()
bool videoActive ()
bool videoDecodeOK ()
bool PlayVideo (bool blnStartStop)
void InitDATVParameters (int intMsps, int intRFBandwidth, int intCenterFrequency, DATVDemodSettings::dvb_version enmStandard, DATVDemodSettings::DATVModulation enmModulation, leansdr::code_rate enmFEC, int intSampleRate, int intSymbolRate, int intNotchFilters, bool blnAllowDrift, bool blnFastLock, DATVDemodSettings::dvb_sampler enmFilter, bool blnHardMetric, float fltRollOff, bool blnViterbi, int intEExcursion)
void CleanUpDATVFramework (bool blnRelease)
int GetSampleRate ()
void InitDATVFramework ()
void InitDATVS2Framework ()
double getMagSq () const
Beware this is scaled to 2^30.
int getModcodModulation () const
int getModcodCodeRate () const
bool isCstlnSetByModcod () const
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Member Functions
static DATVDemodSettings::DATVCodeRate getCodeRateFromLeanDVBCode (int leanDVBCodeRate)
static DATVDemodSettings::DATVModulation getModulationFromLeanDVBCode (int leanDVBModulation)
static int getLeanDVBCodeRateFromDATV (DATVDemodSettings::DATVCodeRate datvCodeRate)
static int getLeanDVBModulationFromDATV (DATVDemodSettings::DATVModulation datvModulation)
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.demoddatv"
static const QString m_channelId = "DATVDemod"
Private Member Functions
void applySettings (const DATVDemodSettings &settings, bool force=false)
void applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force=false)
Private Attributes
unsigned long m_lngExpectedReadIQ
long m_lngReadIQ
unsigned long BUF_BASEBAND
unsigned long BUF_SYMBOLS
unsigned long BUF_BYTES
unsigned long BUF_MPEGBYTES
unsigned long BUF_PACKETS
unsigned long BUF_SLOW
unsigned long BUF_SLOTS
unsigned long BUF_FRAMES
unsigned long BUF_S2PACKETS
unsigned long S2_MAX_SYMBOLS
leansdr::scheduler * m_objScheduler
struct config m_objCfg
bool m_blnDVBInitialized
bool m_blnNeedConfigUpdate
leansdr::pipebuf< leansdr::cf32 > * p_rawiq
leansdr::pipewriter< leansdr::cf32 > * p_rawiq_writer
leansdr::pipebuf< leansdr::cf32 > * p_preprocessed
leansdr::auto_notch< leansdr::f32 > * r_auto_notch
leansdr::pipebuf< leansdr::cf32 > * p_autonotched
leansdr::pipebuf< leansdr::cf32 > * p_derot
leansdr::rotator< leansdr::f32 > * r_derot
leansdr::pipebuf< leansdr::f32 > * p_cnr
leansdr::cnr_fft< leansdr::f32 > * r_cnr
leansdr::fir_filter< leansdr::cf32, float > * r_resample
leansdr::pipebuf< leansdr::cf32 > * p_resampled
float * coeffs
int ncoeffs
leansdr::sampler_interface< leansdr::f32 > * sampler
float * coeffs_sampler
int ncoeffs_sampler
leansdr::pipebuf< leansdr::eucl_ss > * p_symbols
leansdr::pipebuf< leansdr::f32 > * p_freq
leansdr::pipebuf< leansdr::f32 > * p_ss
leansdr::pipebuf< leansdr::f32 > * p_mer
leansdr::pipebuf< leansdr::cf32 > * p_sampled
void * p_slots_dvbs2
leansdr::pipebuf< leansdr::cf32 > * p_cstln
leansdr::pipebuf< leansdr::cf32 > * p_cstln_pls
leansdr::pipebuf< int > * p_framelock
void * m_objDemodulatorDVBS2
void * p_fecframes
void * p_bbframes
void * p_s2_deinterleaver
void * r_fecdec
void * p_deframer
leansdr::pipebuf< leansdr::cf32 > * p_decimated
leansdr::decimator< leansdr::cf32 > * p_decim
leansdr::file_writer< leansdr::cf32 > * r_ppout
leansdr::cstln_receiver< leansdr::f32, leansdr::eucl_ss > * m_objDemodulator
leansdr::pipebuf< leansdr::u8 > * p_bytes
leansdr::deconvol_sync_simple * r_deconv
leansdr::viterbi_sync * r
leansdr::pipebuf< leansdr::u8 > * p_descrambled
leansdr::pipebuf< leansdr::u8 > * p_frames
leansdr::etr192_descrambler * r_etr192_descrambler
leansdr::hdlc_sync * r_sync
leansdr::pipebuf< leansdr::u8 > * p_mpegbytes
leansdr::pipebuf< int > * p_lock
leansdr::pipebuf< leansdr::u32 > * p_locktime
leansdr::mpeg_sync< leansdr::u8, 0 > * r_sync_mpeg
leansdr::pipebuf< leansdr::rspacket< leansdr::u8 > > * p_rspackets
leansdr::deinterleaver< leansdr::u8 > * r_deinter
leansdr::pipebuf< int > * p_vbitcount
leansdr::pipebuf< int > * p_verrcount
leansdr::pipebuf< leansdr::tspacket > * p_rtspackets
leansdr::rs_decoder< leansdr::u8, 0 > * r_rsdec
leansdr::pipebuf< float > * p_vber
leansdr::rate_estimator< float > * r_vber
leansdr::pipebuf< leansdr::tspacket > * p_tspackets
leansdr::derandomizer * r_derand
leansdr::file_writer< leansdr::tspacket > * r_stdout
leansdr::datvvideoplayer< leansdr::tspacket > * r_videoplayer
leansdr::datvconstellation< leansdr::f32 > * r_scope_symbols
leansdr::datvdvbs2constellation< leansdr::f32 > * r_scope_symbols_dvbs2
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
TVScreen * m_objRegisteredTVScreen
DATVideoRender * m_objRegisteredVideoRender
DATVideostream * m_objVideoStream
DATVUDPStream m_udpStream
DATVideoRenderThread * m_objRenderThread
AudioFifo m_audioFifo
fftfilt * m_objRFFilter
NCO m_objNCO
bool m_blnInitialized
bool m_blnRenderingVideo
bool m_blnStartStopVideo
bool m_cstlnSetByModcod
int m_modcodModulation
int m_modcodCodeRate
DATVDemodSettings::DATVModulation m_enmModulation
DATVDemodSettings m_settings
int m_sampleRate
int m_inputFrequencyOffset
MovingAverageUtil< double, double, 32 > m_objMagSqAverage
QMutex m_objSettingsMutex
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 125 of file datvdemod.h.
Constructor & Destructor Documentation
DATVDemod()
DATVDemod::DATVDemod (DeviceAPI * deviceAPI)
Definition at line 42 of file datvdemod.cpp.
References AudioDeviceManager::addAudioSink(), DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), and rfFilterFftLength.
                                          :
     ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
     m_blnNeedConfigUpdate(false),
     m_deviceAPI(deviceAPI),
     m_objRegisteredTVScreen(0),
     m_objRegisteredVideoRender(0),
     m_objVideoStream(nullptr),
     m_udpStream(leansdr::tspacket::SIZE),
     m_objRenderThread(nullptr),
     m_audioFifo(48000),
     m_blnRenderingVideo(false),
     m_blnStartStopVideo(false),
     m_cstlnSetByModcod(false),
     m_modcodModulation(-1),
     m_modcodCodeRate(-1),
     m_enmModulation(DATVDemodSettings::BPSK /*DATV_FM1*/),
     m_sampleRate(1024000),
     m_objSettingsMutex(QMutex::NonRecursive)
 {
     setObjectName("DATVDemod");
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSink(&m_audioFifo, getInputMessageQueue());
     //m_audioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getOutputSampleRate();
     //*************** DATV PARAMETERS  ***************
     m_blnInitialized=false;
     CleanUpDATVFramework(false);
     m_objVideoStream = new DATVideostream();
     m_objRFFilter = new fftfilt(-256000.0 / 1024000.0, 256000.0 / 1024000.0, rfFilterFftLength);
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
 }
~DATVDemod()
DATVDemod::~DATVDemod ()
Definition at line 80 of file datvdemod.cpp.
References CleanUpDATVFramework(), DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo, m_blnInitialized, m_channelizer, m_deviceAPI, m_objRenderThread, m_objRFFilter, m_objVideoStream, m_threadedChannelizer, AudioDeviceManager::removeAudioSink(), DeviceAPI::removeChannelSink(), DeviceAPI::removeChannelSinkAPI(), DATVideoRenderThread::stopRendering(), and DATVideostream::ThreadTimeOut.
 {
     m_blnInitialized=false;
     if(m_objVideoStream!=nullptr)
     {
         //Immediately exit from DATVideoStream if waiting for data before killing thread
         m_objVideoStream->ThreadTimeOut=0;
     }
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_audioFifo);
     if(m_objRenderThread!=nullptr)
     {
         if(m_objRenderThread->isRunning())
         {
            m_objRenderThread->stopRendering();
            m_objRenderThread->quit();
         }
         m_objRenderThread->wait(2000);
     }
     CleanUpDATVFramework(true);
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete m_objRFFilter;
 }
Member Function Documentation
applyChannelSettings()
void DATVDemod::applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 1356 of file datvdemod.cpp.
References applySettings(), fftfilt::create_filter(), DATVDemodSettings::m_centerFrequency, m_objNCO, m_objRFFilter, DATVDemodSettings::m_rfBandwidth, m_sampleRate, m_settings, and NCO::setFreq().
Referenced by handleMessage().
 {
     qDebug() << "DATVDemod::applyChannelSettings:"
             << " inputSampleRate: " << inputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     bool callApplySettings = false;
     if ((m_settings.m_centerFrequency != inputFrequencyOffset) ||
         (m_sampleRate != inputSampleRate) || force)
     {
         m_objNCO.setFreq(-(float) inputFrequencyOffset, (float) inputSampleRate);
         qDebug("DATVDemod::applyChannelSettings: NCO: IF: %d <> TF: %d ISR: %d",
             inputFrequencyOffset, m_settings.m_centerFrequency, inputSampleRate);
         callApplySettings = true;
     }
     if ((m_sampleRate != inputSampleRate) || force)
     {
         //Bandpass filter shaping
         Real fltLowCut = -((float) m_settings.m_rfBandwidth / 2.0) / (float) inputSampleRate;
         Real fltHiCut  = ((float) m_settings.m_rfBandwidth / 2.0) / (float) inputSampleRate;
         m_objRFFilter->create_filter(fltLowCut, fltHiCut);
     }
     m_sampleRate = inputSampleRate;
     m_settings.m_centerFrequency = inputFrequencyOffset;
     if (callApplySettings) {
         applySettings(m_settings, true);
     }
 }
applySettings()
void DATVDemod::applySettings (const DATVDemodSettings & settings, bool force = false) private
Definition at line 1389 of file datvdemod.cpp.
References AudioDeviceManager::addAudioSink(), fftfilt::create_filter(), DATVDemodSettings::debug(), DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputDeviceIndex(), DSPEngine::instance(), DATVDemodSettings::isDifferent(), DATVDemodSettings::m_audioDeviceName, m_audioFifo, DATVDemodSettings::m_audioMute, DATVDemodSettings::m_audioVolume, m_blnNeedConfigUpdate, DATVDemodSettings::m_centerFrequency, m_objNCO, m_objRegisteredVideoRender, m_objRFFilter, DATVDemodSettings::m_rfBandwidth, m_sampleRate, m_settings, m_udpStream, DATVDemodSettings::m_udpTS, DATVDemodSettings::m_udpTSAddress, DATVDemodSettings::m_udpTSPort, DATVDemodSettings::m_videoMute, DATVUDPStream::setActive(), DATVUDPStream::setAddress(), DATVideoRender::setAudioMute(), DATVideoRender::setAudioVolume(), NCO::setFreq(), DATVUDPStream::setPort(), and DATVideoRender::setVideoMute().
Referenced by applyChannelSettings(), and handleMessage().
 {
     QString msg = tr("DATVDemod::applySettings: force: %1").arg(force);
     settings.debug(msg);
     qDebug("DATVDemod::applySettings: m_sampleRate: %d", m_sampleRate);
     if (m_sampleRate == 0) {
         return;
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force)
     {
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getOutputDeviceIndex(settings.m_audioDeviceName);
         audioDeviceManager->addAudioSink(&m_audioFifo, getInputMessageQueue(), audioDeviceIndex); // removes from current if necessary
         // uint32_t audioSampleRate = audioDeviceManager->getOutputSampleRate(audioDeviceIndex);
         // if (m_audioSampleRate != audioSampleRate) {
         //     applyAudioSampleRate(audioSampleRate);
         // }
     }
     if ((settings.m_audioVolume) != (m_settings.m_audioVolume) || force)
     {
         if (m_objRegisteredVideoRender) {
             m_objRegisteredVideoRender->setAudioVolume(settings.m_audioVolume);
         }
     }
     if ((settings.m_audioMute) != (m_settings.m_audioMute) || force)
     {
         if (m_objRegisteredVideoRender) {
             m_objRegisteredVideoRender->setAudioMute(settings.m_audioMute);
         }
     }
     if ((settings.m_videoMute) != (m_settings.m_videoMute) || force)
     {
         if (m_objRegisteredVideoRender) {
             m_objRegisteredVideoRender->setVideoMute(settings.m_videoMute);
         }
     }
     if ((m_settings.m_rfBandwidth != settings.m_rfBandwidth)
         || force)
     {
         //Bandpass filter shaping
         Real fltLowCut = -((float) settings.m_rfBandwidth / 2.0) / (float) m_sampleRate;
         Real fltHiCut  = ((float) settings.m_rfBandwidth / 2.0) / (float) m_sampleRate;
         m_objRFFilter->create_filter(fltLowCut, fltHiCut);
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency)
         || force)
     {
         m_objNCO.setFreq(-(float) settings.m_centerFrequency, (float) m_sampleRate);
     }
     if ((m_settings.m_udpTS != settings.m_udpTS) || force) {
         m_udpStream.setActive(settings.m_udpTS);
     }
     if ((m_settings.m_udpTSAddress != settings.m_udpTSAddress) || force) {
         m_udpStream.setAddress(settings.m_udpTSAddress);
     }
     if ((m_settings.m_udpTSPort != settings.m_udpTSPort) || force) {
         m_udpStream.setPort(settings.m_udpTSPort);
     }
     if (m_settings.isDifferent(settings) || force)
     {
         m_blnNeedConfigUpdate = true;
     }
     m_settings = settings;
 }
audioActive()
bool DATVDemod::audioActive ()
Definition at line 126 of file datvdemod.cpp.
References DATVideoRender::getAudioStreamIndex(), and m_objRegisteredVideoRender.
Referenced by DATVDemodGUI::tick().
 {
     if (m_objRegisteredVideoRender) {
         return m_objRegisteredVideoRender->getAudioStreamIndex() >= 0;
     } else {
         return false;
     }
 }
audioDecodeOK()
bool DATVDemod::audioDecodeOK ()
Definition at line 144 of file datvdemod.cpp.
References DATVideoRender::getAudioDecodeOK(), and m_objRegisteredVideoRender.
Referenced by DATVDemodGUI::tick().
 {
     if (m_objRegisteredVideoRender) {
         return m_objRegisteredVideoRender->getAudioDecodeOK();
     } else {
         return false;
     }
 }
CleanUpDATVFramework()
void DATVDemod::CleanUpDATVFramework (bool blnRelease)
Definition at line 205 of file datvdemod.cpp.
References coeffs, coeffs_sampler, m_objDemodulator, m_objDemodulatorDVBS2, m_objScheduler, ncoeffs, ncoeffs_sampler, p_autonotched, p_bbframes, p_bytes, p_cnr, p_cstln, p_cstln_pls, p_decim, p_decimated, p_deframer, p_derot, p_descrambled, p_fecframes, p_framelock, p_frames, p_freq, p_lock, p_locktime, p_mer, p_mpegbytes, p_preprocessed, p_rawiq, p_rawiq_writer, p_resampled, p_rspackets, p_rtspackets, p_s2_deinterleaver, p_sampled, p_slots_dvbs2, p_ss, p_symbols, p_tspackets, p_vber, p_vbitcount, p_verrcount, r, r_auto_notch, r_cnr, r_deconv, r_deinter, r_derand, r_derot, r_etr192_descrambler, r_fecdec, r_ppout, r_resample, r_rsdec, r_scope_symbols, r_scope_symbols_dvbs2, r_stdout, r_sync, r_sync_mpeg, r_vber, r_videoplayer, sampler, and leansdr::scheduler::shutdown().
Referenced by InitDATVFramework(), InitDATVS2Framework(), and ~DATVDemod().
 {
     if (blnRelease == true)
     {
         if (m_objScheduler != nullptr)
         {
             m_objScheduler->shutdown();
             delete m_objScheduler;
         }
         // NOTCH FILTER
         if (r_auto_notch != nullptr) {
             delete r_auto_notch;
         }
         if (p_autonotched != nullptr) {
             delete p_autonotched;
         }
         // FREQUENCY CORRECTION : DEROTATOR
         if (p_derot != nullptr) {
             delete p_derot;
         }
         if (r_derot != nullptr) {
             delete r_derot;
         }
         // CNR ESTIMATION
         if (p_cnr != nullptr) {
             delete p_cnr;
         }
         if (r_cnr != nullptr) {
             delete r_cnr;
         }
         //FILTERING
         if (r_resample != nullptr) {
             delete r_resample;
         }
         if (p_resampled != nullptr) {
             delete p_resampled;
         }
         if (coeffs != nullptr) {
             delete coeffs;
         }
         // OUTPUT PREPROCESSED DATA
         if (sampler != nullptr) {
             delete sampler;
         }
         if (coeffs_sampler != nullptr) {
             delete coeffs_sampler;
         }
         if (p_symbols != nullptr) {
             delete p_symbols;
         }
         if (p_freq != nullptr) {
             delete p_freq;
         }
         if (p_ss != nullptr) {
             delete p_ss;
         }
         if (p_mer != nullptr) {
             delete p_mer;
         }
         if (p_sampled != nullptr) {
             delete p_sampled;
         }
         //DECIMATION
         if (p_decimated != nullptr) {
             delete p_decimated;
         }
         if (p_decim != nullptr) {
             delete p_decim;
         }
         if (r_ppout != nullptr) {
             delete r_ppout;
         }
         //GENERIC CONSTELLATION RECEIVER
         if (m_objDemodulator != nullptr) {
             delete m_objDemodulator;
         }
         //DECONVOLUTION AND SYNCHRONIZATION
         if (p_bytes != nullptr) {
             delete p_bytes;
         }
         if (r_deconv != nullptr) {
             delete r_deconv;
         }
         if (r != nullptr) {
             delete r;
         }
         if (p_descrambled != nullptr) {
             delete p_descrambled;
         }
         if (p_frames != nullptr) {
             delete p_frames;
         }
         if (r_etr192_descrambler != nullptr) {
             delete r_etr192_descrambler;
         }
         if (r_sync != nullptr) {
             delete r_sync;
         }
         if (p_mpegbytes != nullptr) {
             delete p_mpegbytes;
         }
         if (p_lock != nullptr) {
             delete p_lock;
         }
         if (p_locktime != nullptr) {
             delete p_locktime;
         }
         if (r_sync_mpeg != nullptr) {
             delete r_sync_mpeg;
         }
         // DEINTERLEAVING
         if (p_rspackets != nullptr) {
             delete p_rspackets;
         }
         if (r_deinter != nullptr) {
             delete r_deinter;
         }
         if (p_vbitcount != nullptr) {
             delete p_vbitcount;
         }
         if (p_verrcount != nullptr) {
             delete p_verrcount;
         }
         if (p_rtspackets != nullptr) {
             delete p_rtspackets;
         }
         if (r_rsdec != nullptr) {
             delete r_rsdec;
         }
         //BER ESTIMATION
         if (p_vber != nullptr) {
             delete p_vber;
         }
         if (r_vber != nullptr) {
             delete r_vber;
         }
         // DERANDOMIZATION
         if (p_tspackets != nullptr) {
             delete p_tspackets;
         }
         if (r_derand != nullptr) {
             delete r_derand;
         }
         //OUTPUT : To remove
         if (r_stdout != nullptr) {
             delete r_stdout;
         }
         if (r_videoplayer != nullptr) {
             delete r_videoplayer;
         }
         //CONSTELLATION
         if (r_scope_symbols != nullptr) {
             delete r_scope_symbols;
         }
         // INPUT
         //if(p_rawiq!=nullptr) delete p_rawiq;
         //if(p_rawiq_writer!=nullptr) delete p_rawiq_writer;
         //if(p_preprocessed!=nullptr) delete p_preprocessed;
         //DVB-S2
         if(p_slots_dvbs2  != nullptr)
         {
             delete (leansdr::pipebuf< leansdr::plslot<leansdr::llr_ss> >*) p_slots_dvbs2;
         }
         if(p_cstln  != nullptr)
         {
             delete p_cstln;
         }
         if(p_cstln_pls != nullptr)
         {
             delete p_cstln_pls;
         }
         if(p_framelock != nullptr)
         {
             delete p_framelock;
         }
         if(m_objDemodulatorDVBS2 != nullptr)
         {
             delete (leansdr::s2_frame_receiver<leansdr::f32, leansdr::llr_ss>*) m_objDemodulatorDVBS2;
         }
         if(p_fecframes != nullptr)
         {
             delete (leansdr::pipebuf< leansdr::fecframe<leansdr::hard_sb> >*) p_fecframes;
         }
         if(p_bbframes != nullptr)
         {
             delete (leansdr::pipebuf<leansdr::bbframe>*) p_bbframes;
         }
         if(p_s2_deinterleaver != nullptr)
         {
             delete (leansdr::s2_deinterleaver<leansdr::llr_ss,leansdr::hard_sb>*) p_s2_deinterleaver;
         }
         if(r_fecdec != nullptr)
         {
             delete (leansdr::s2_fecdec<bool, leansdr::hard_sb>*) r_fecdec;
         }
         if(p_deframer != nullptr)
         {
             delete (leansdr::s2_deframer*) p_deframer;
         }
         if(r_scope_symbols_dvbs2 != nullptr)
         {
             delete r_scope_symbols_dvbs2;
         }
     }
     m_objScheduler=nullptr;
     // INPUT
     p_rawiq = nullptr;
     p_rawiq_writer = nullptr;
     p_preprocessed = nullptr;
     // NOTCH FILTER
     r_auto_notch = nullptr;
     p_autonotched = nullptr;
     // FREQUENCY CORRECTION : DEROTATOR
     p_derot = nullptr;
     r_derot=nullptr;
     // CNR ESTIMATION
     p_cnr = nullptr;
     r_cnr = nullptr;
     //FILTERING
     r_resample = nullptr;
     p_resampled = nullptr;
     coeffs = nullptr;
     ncoeffs=0;
     // OUTPUT PREPROCESSED DATA
     sampler = nullptr;
     coeffs_sampler=nullptr;
     ncoeffs_sampler=0;
     p_symbols = nullptr;
     p_freq = nullptr;
     p_ss = nullptr;
     p_mer = nullptr;
     p_sampled = nullptr;
     //DECIMATION
     p_decimated = nullptr;
     p_decim = nullptr;
     r_ppout = nullptr;
     //GENERIC CONSTELLATION RECEIVER
     m_objDemodulator = nullptr;
     //DECONVOLUTION AND SYNCHRONIZATION
     p_bytes=nullptr;
     r_deconv=nullptr;
     r = nullptr;
     p_descrambled = nullptr;
     p_frames = nullptr;
     r_etr192_descrambler = nullptr;
     r_sync = nullptr;
     p_mpegbytes = nullptr;
     p_lock = nullptr;
     p_locktime = nullptr;
     r_sync_mpeg = nullptr;
     // DEINTERLEAVING
     p_rspackets = nullptr;
     r_deinter = nullptr;
     p_vbitcount = nullptr;
     p_verrcount = nullptr;
     p_rtspackets = nullptr;
     r_rsdec = nullptr;
     //BER ESTIMATION
     p_vber = nullptr;
     r_vber  = nullptr;
     // DERANDOMIZATION
     p_tspackets = nullptr;
     r_derand = nullptr;
     //OUTPUT : To remove void *
     r_stdout = nullptr;
     r_videoplayer = nullptr;
     //CONSTELLATION
     r_scope_symbols = nullptr;
     //DVB-S2
     p_slots_dvbs2 = nullptr;
     p_cstln = nullptr;
     p_cstln_pls = nullptr;
     p_framelock = nullptr;
     m_objDemodulatorDVBS2 = nullptr;
     p_fecframes = nullptr;
     p_bbframes = nullptr;
     p_s2_deinterleaver = nullptr;
     r_fecdec = nullptr;
     p_deframer = nullptr;
     r_scope_symbols_dvbs2 = nullptr;
 }
deserialize()
virtual bool DATVDemod::deserialize (const QByteArray & data) inline virtual
Implements ChannelAPI.
Definition at line 140 of file datvdemod.h.
 { (void) data; return false; }
destroy()
virtual void DATVDemod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 134 of file datvdemod.h.
 { delete this; }
feed()
void DATVDemod::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool po) virtual
Implements BasebandSampleSink.
Definition at line 1154 of file datvdemod.cpp.
References leansdr::datvdvbs2constellation< T >::calculate_cstln_points(), DATVDemod::MsgReportModcodCstlnChange::create(), leansdr::s2_frame_receiver< T, SOFTSYMB >::cstln, DATVDemodSettings::DVB_S2, getCodeRateFromLeanDVBCode(), BasebandSampleSink::getMessageQueueToGUI(), getModulationFromLeanDVBCode(), leansdr::complex< T >::im, InitDATVFramework(), InitDATVS2Framework(), m_blnDVBInitialized, m_blnNeedConfigUpdate, m_cstlnSetByModcod, m_lngReadIQ, m_modcodCodeRate, m_modcodModulation, leansdr::s2_frame_receiver< T, SOFTSYMB >::m_modcodRate, leansdr::s2_frame_receiver< T, SOFTSYMB >::m_modcodType, m_objDemodulatorDVBS2, m_objMagSqAverage, m_objNCO, m_objRFFilter, m_objScheduler, m_objSettingsMutex, m_settings, DATVDemodSettings::m_standard, NCO::nextIQ(), p_rawiq_writer, MessageQueue::push(), r_scope_symbols_dvbs2, leansdr::complex< T >::re, fftfilt::runFilt(), and leansdr::scheduler::step().
 {
     (void) firstOfBurst;
     float fltI;
     float fltQ;
     leansdr::cf32 objIQ;
     //Complex objC;
     fftfilt::cmplx *objRF;
     int intRFOut;
     double magSq;
     int lngWritable=0;
     //********** Bis repetita : Let's rock and roll buddy ! **********
 #ifdef EXTENDED_DIRECT_SAMPLE
     qint16 * ptrBuffer;
     qint32 intLen;
     //********** Reading direct samples **********
     SampleVector::const_iterator it = begin;
     intLen = it->intLen;
     ptrBuffer = it->ptrBuffer;
     ptrBufferToRelease = ptrBuffer;
     ++it;
     for(qint32 intInd=0; intInd<intLen-1; intInd +=2)
     {
         fltI= ((qint32) (*ptrBuffer)) << 4;
         ptrBuffer ++;
         fltQ= ((qint32) (*ptrBuffer)) << 4;
         ptrBuffer ++;
 #else
     for (SampleVector::const_iterator it = begin; it != end; ++it /* ++it **/)
     {
         fltI = it->real();
         fltQ = it->imag();
 #endif
         //********** demodulation **********
         if (m_blnNeedConfigUpdate)
         {
             qDebug("DATVDemod::feed: Settings applied. Standard : %d...", m_settings.m_standard);
             m_objSettingsMutex.lock();
             m_blnNeedConfigUpdate=false;
             if(m_settings.m_standard==DATVDemodSettings::DVB_S2)
             {
                 printf("SWITCHING TO DVBS-2\r\n");
                 InitDATVS2Framework();
             }
             else
             {
                 printf("SWITCHING TO DVBS\r\n");
                 InitDATVFramework();
             }
             m_objSettingsMutex.unlock();
         }
         //********** iq stream ****************
         Complex objC(fltI,fltQ);
         objC *= m_objNCO.nextIQ();
         intRFOut = m_objRFFilter->runFilt(objC, &objRF); // filter RF before demod
         for (int intI = 0 ; intI < intRFOut; intI++)
         {
             objIQ.re = objRF->real();
             objIQ.im = objRF->imag();
             magSq = objIQ.re*objIQ.re + objIQ.im*objIQ.im;
             m_objMagSqAverage(magSq);
             objRF ++;
             if (m_blnDVBInitialized
                && (p_rawiq_writer!=nullptr)
                && (m_objScheduler!=nullptr))
             {
                 p_rawiq_writer->write(objIQ);
                 m_lngReadIQ++;
                 lngWritable = p_rawiq_writer->writable();
                 //Leave +1 by safety
                 //if(((m_lngReadIQ+1)>=lngWritable) || (m_lngReadIQ>=768))
                 if((m_lngReadIQ+1)>=lngWritable)
                 {
                     m_objScheduler->step();
                     m_lngReadIQ=0;
                     //delete p_rawiq_writer;
                     //p_rawiq_writer = new leansdr::pipewriter<leansdr::cf32>(*p_rawiq);
                 }
             }
         }
     } // Samples for loop
     // DVBS2: Track change of constellation via MODCOD
     if (m_settings.m_standard==DATVDemodSettings::DVB_S2)
     {
         leansdr::s2_frame_receiver<leansdr::f32, leansdr::llr_ss> * objDemodulatorDVBS2 = (leansdr::s2_frame_receiver<leansdr::f32, leansdr::llr_ss> *) m_objDemodulatorDVBS2;
         if (objDemodulatorDVBS2->cstln->m_setByModcod && !m_cstlnSetByModcod)
         {
             qDebug("DATVDemod::feed: change by MODCOD detected");
             if (r_scope_symbols_dvbs2) {
                 r_scope_symbols_dvbs2->calculate_cstln_points();
             }
             if (getMessageQueueToGUI())
             {
                 MsgReportModcodCstlnChange *msg = MsgReportModcodCstlnChange::create(
                     getModulationFromLeanDVBCode(objDemodulatorDVBS2->cstln->m_typeCode),
                     getCodeRateFromLeanDVBCode(objDemodulatorDVBS2->cstln->m_rateCode)
                 );
                 getMessageQueueToGUI()->push(msg);
             }
         }
         m_cstlnSetByModcod = objDemodulatorDVBS2->cstln->m_setByModcod;
         m_modcodModulation = objDemodulatorDVBS2->m_modcodType;
         m_modcodCodeRate = objDemodulatorDVBS2->m_modcodRate;
     }
 }
getCenterFrequency()
virtual qint64 DATVDemod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 137 of file datvdemod.h.
 { return m_settings.m_centerFrequency; }
getCodeRateFromLeanDVBCode()
DATVDemodSettings::DATVCodeRate DATVDemod::getCodeRateFromLeanDVBCode (int leanDVBCodeRate) static
Definition at line 1474 of file datvdemod.cpp.
References leansdr::FEC12, leansdr::FEC13, leansdr::FEC14, leansdr::FEC23, leansdr::FEC25, leansdr::FEC34, leansdr::FEC35, leansdr::FEC45, leansdr::FEC46, leansdr::FEC56, leansdr::FEC78, leansdr::FEC89, and leansdr::FEC910.
Referenced by feed(), and DATVDemodGUI::tick().
 {
     if (leanDVBCodeRate == leansdr::code_rate::FEC12) {
         return DATVDemodSettings::DATVCodeRate::FEC12;
     } else if (leanDVBCodeRate == leansdr::code_rate::FEC13) {
         return DATVDemodSettings::DATVCodeRate::FEC13;
     } else if (leanDVBCodeRate == leansdr::code_rate::FEC14) {
         return DATVDemodSettings::DATVCodeRate::FEC14;
     } else if (leanDVBCodeRate == leansdr::code_rate::FEC23) {
         return DATVDemodSettings::DATVCodeRate::FEC23;
     } else if (leanDVBCodeRate == leansdr::code_rate::FEC25) {
         return DATVDemodSettings::DATVCodeRate::FEC25;
     } else if (leanDVBCodeRate == leansdr::code_rate::FEC34) {
         return DATVDemodSettings::DATVCodeRate::FEC34;
     } else if (leanDVBCodeRate == leansdr::code_rate::FEC35) {
         return DATVDemodSettings::DATVCodeRate::FEC35;
     } else if (leanDVBCodeRate == leansdr::code_rate::FEC45) {
         return DATVDemodSettings::DATVCodeRate::FEC45;
     } else if (leanDVBCodeRate == leansdr::code_rate::FEC46) {
         return DATVDemodSettings::DATVCodeRate::FEC46;
     } else if (leanDVBCodeRate == leansdr::code_rate::FEC56) {
         return DATVDemodSettings::DATVCodeRate::FEC56;
     } else if (leanDVBCodeRate == leansdr::code_rate::FEC78) {
         return DATVDemodSettings::DATVCodeRate::FEC78;
     } else if (leanDVBCodeRate == leansdr::code_rate::FEC89) {
         return DATVDemodSettings::DATVCodeRate::FEC89;
     } else if (leanDVBCodeRate == leansdr::code_rate::FEC910) {
         return DATVDemodSettings::DATVCodeRate::FEC910;
     } else {
         return DATVDemodSettings::DATVCodeRate::RATE_UNSET;
     }
 }
getIdentifier()
virtual void DATVDemod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 135 of file datvdemod.h.
 { id = objectName(); }
getLeanDVBCodeRateFromDATV()
int DATVDemod::getLeanDVBCodeRateFromDATV (DATVDemodSettings::DATVCodeRate datvCodeRate) static
Definition at line 1532 of file datvdemod.cpp.
References leansdr::FEC12, leansdr::FEC13, leansdr::FEC14, leansdr::FEC23, leansdr::FEC25, leansdr::FEC34, leansdr::FEC35, leansdr::FEC45, leansdr::FEC46, leansdr::FEC56, leansdr::FEC78, leansdr::FEC89, and leansdr::FEC910.
Referenced by InitDATVFramework(), and InitDATVS2Framework().
 {
     if (datvCodeRate == DATVDemodSettings::DATVCodeRate::FEC12) {
         return (int)  leansdr::code_rate::FEC12;
     } else if (datvCodeRate == DATVDemodSettings::DATVCodeRate::FEC13) {
         return (int) leansdr::code_rate::FEC13;
     } else if (datvCodeRate == DATVDemodSettings::DATVCodeRate::FEC14) {
         return (int) leansdr::code_rate::FEC14;
     } else if (datvCodeRate == DATVDemodSettings::DATVCodeRate::FEC23) {
         return (int) leansdr::code_rate::FEC23;
     } else if (datvCodeRate == DATVDemodSettings::DATVCodeRate::FEC25) {
         return (int) leansdr::code_rate::FEC25;
     } else if (datvCodeRate == DATVDemodSettings::DATVCodeRate::FEC34) {
         return (int) leansdr::code_rate::FEC34;
     } else if (datvCodeRate == DATVDemodSettings::DATVCodeRate::FEC35) {
         return (int) leansdr::code_rate::FEC35;
     } else if (datvCodeRate == DATVDemodSettings::DATVCodeRate::FEC45) {
         return (int) leansdr::code_rate::FEC45;
     } else if (datvCodeRate == DATVDemodSettings::DATVCodeRate::FEC46) {
         return (int) leansdr::code_rate::FEC46;
     } else if (datvCodeRate == DATVDemodSettings::DATVCodeRate::FEC56) {
         return (int) leansdr::code_rate::FEC56;
     } else if (datvCodeRate == DATVDemodSettings::DATVCodeRate::FEC78) {
         return (int) leansdr::code_rate::FEC78;
     } else if (datvCodeRate == DATVDemodSettings::DATVCodeRate::FEC89) {
         return (int) leansdr::code_rate::FEC89;
     } else if (datvCodeRate == DATVDemodSettings::DATVCodeRate::FEC910) {
         return (int) leansdr::code_rate::FEC910;
     } else {
         return -1;
     }
 }
getLeanDVBModulationFromDATV()
int DATVDemod::getLeanDVBModulationFromDATV (DATVDemodSettings::DATVModulation datvModulation) static
Definition at line 1565 of file datvdemod.cpp.
 {
     if (datvModulation == DATVDemodSettings::DATVModulation::APSK16) {
         return (int) leansdr::cstln_base::predef::APSK16;
     } else if (datvModulation == DATVDemodSettings::DATVModulation::APSK32) {
         return (int) leansdr::cstln_base::predef::APSK32;
     } else if (datvModulation == DATVDemodSettings::DATVModulation::APSK64E) {
         return (int) leansdr::cstln_base::predef::APSK64E;
     } else if (datvModulation == DATVDemodSettings::DATVModulation::BPSK) {
         return (int) leansdr::cstln_base::predef::BPSK;
     } else if (datvModulation == DATVDemodSettings::DATVModulation::PSK8) {
         return (int) leansdr::cstln_base::predef::PSK8;
     } else if (datvModulation == DATVDemodSettings::DATVModulation::QAM16) {
         return (int) leansdr::cstln_base::predef::QAM16;
     } else if (datvModulation == DATVDemodSettings::DATVModulation::QAM64) {
         return (int) leansdr::cstln_base::predef::QAM64;
     } else if (datvModulation == DATVDemodSettings::DATVModulation::QAM256) {
         return (int) leansdr::cstln_base::predef::QAM256;
     } else if (datvModulation == DATVDemodSettings::DATVModulation::QPSK) {
         return (int) leansdr::cstln_base::predef::QPSK;
     } else {
         return -1;
     }
 }
getMagSq()
double DATVDemod::getMagSq () const inline
Beware this is scaled to 2^30.
Definition at line 188 of file datvdemod.h.
Referenced by DATVDemodGUI::tick().
getModcodCodeRate()
int DATVDemod::getModcodCodeRate () const inline
Definition at line 190 of file datvdemod.h.
Referenced by DATVDemodGUI::tick().
 { return m_modcodCodeRate; }
getModcodModulation()
int DATVDemod::getModcodModulation () const inline
Definition at line 189 of file datvdemod.h.
Referenced by DATVDemodGUI::tick().
 { return m_modcodModulation; }
getModulationFromLeanDVBCode()
DATVDemodSettings::DATVModulation DATVDemod::getModulationFromLeanDVBCode (int leanDVBModulation) static
Definition at line 1507 of file datvdemod.cpp.
Referenced by feed(), and DATVDemodGUI::tick().
 {
     if (leanDVBModulation == leansdr::cstln_base::predef::APSK16) {
         return DATVDemodSettings::DATVModulation::APSK16;
     } else if (leanDVBModulation == leansdr::cstln_base::predef::APSK32) {
         return DATVDemodSettings::DATVModulation::APSK32;
     } else if (leanDVBModulation == leansdr::cstln_base::predef::APSK64E) {
         return DATVDemodSettings::DATVModulation::APSK64E;
     } else if (leanDVBModulation == leansdr::cstln_base::predef::BPSK) {
         return DATVDemodSettings::DATVModulation::BPSK;
     } else if (leanDVBModulation == leansdr::cstln_base::predef::PSK8) {
         return DATVDemodSettings::DATVModulation::PSK8;
     } else if (leanDVBModulation == leansdr::cstln_base::predef::QAM16) {
         return DATVDemodSettings::DATVModulation::QAM16;
     } else if (leanDVBModulation == leansdr::cstln_base::predef::QAM64) {
         return DATVDemodSettings::DATVModulation::QAM64;
     } else if (leanDVBModulation == leansdr::cstln_base::predef::QAM256) {
         return DATVDemodSettings::DATVModulation::QAM256;
     } else if (leanDVBModulation == leansdr::cstln_base::predef::QPSK) {
         return DATVDemodSettings::DATVModulation::QPSK;
     } else {
         return DATVDemodSettings::DATVModulation::MOD_UNSET;
     }
 }
getNbSinkStreams()
virtual int DATVDemod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 147 of file datvdemod.h.
 { return 1; }
getNbSourceStreams()
virtual int DATVDemod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 148 of file datvdemod.h.
 { return 0; }
GetSampleRate()
int DATVDemod::GetSampleRate ()
Definition at line 1469 of file datvdemod.cpp.
References m_sampleRate.
 {
     return m_sampleRate;
 }
getStreamCenterFrequency()
virtual qint64 DATVDemod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 150 of file datvdemod.h.
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_centerFrequency;
     }
getTitle()
virtual void DATVDemod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 136 of file datvdemod.h.
 { title = objectName(); }
handleMessage()
bool DATVDemod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 1303 of file datvdemod.cpp.
References applyChannelSettings(), applySettings(), DownChannelizer::configure(), DATVDemod::MsgConfigureChannelizer::getCenterFrequency(), DATVDemod::MsgConfigureDATVDemod::getForce(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSink::getInputMessageQueue(), DownChannelizer::getInputSampleRate(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), DATVDemod::MsgConfigureDATVDemod::getSettings(), m_channelizer, m_inputFrequencyOffset, m_sampleRate, and Message::match().
 {
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& objNotif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "DATVDemod::handleMessage: MsgChannelizerNotification:"
             << " m_intSampleRate: " << objNotif.getSampleRate()
             << " m_intFrequencyOffset: " << objNotif.getFrequencyOffset();
         m_inputFrequencyOffset = objNotif.getFrequencyOffset();
         applyChannelSettings(m_sampleRate /*objNotif.getSampleRate()*/, m_inputFrequencyOffset);
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
                 m_channelizer->getInputSampleRate(), // do not change sample rate
                 cfg.getCenterFrequency());
         qDebug() << "DATVDemod::handleMessage: MsgConfigureChannelizer: sampleRate: " << m_channelizer->getInputSampleRate()
             << " centerFrequency: " << cfg.getCenterFrequency();
         m_sampleRate = m_channelizer->getInputSampleRate();
         applyChannelSettings(m_sampleRate /*objNotif.getSampleRate()*/, m_inputFrequencyOffset);
         return true;
     }
     else if (MsgConfigureDATVDemod::match(cmd))
     {
         MsgConfigureDATVDemod& objCfg = (MsgConfigureDATVDemod&) cmd;
         qDebug() << "DATVDemod::handleMessage: MsgConfigureDATVDemod";
         applySettings(objCfg.getSettings(), objCfg.getForce());
         return true;
     }
     else if(DSPSignalNotification::match(cmd))
     {
         m_sampleRate = m_channelizer->getInputSampleRate();
         qDebug("DATVDemod::handleMessage: DSPSignalNotification: sent sample rate: %d", m_sampleRate);
         applyChannelSettings(m_sampleRate /*objNotif.getSampleRate()*/, m_inputFrequencyOffset);
         return true;
     }
     else
     {
         return false;
     }
 }
InitDATVFramework()
void DATVDemod::InitDATVFramework ()
Definition at line 541 of file datvdemod.cpp.
References config::allow_drift, config::anf, DATVDemodSettings::APSK16, DATVDemodSettings::APSK32, DATVDemodSettings::APSK64E, DATVDemodSettings::BPSK, BUF_BASEBAND, BUF_BYTES, config::buf_factor, BUF_MPEGBYTES, BUF_PACKETS, BUF_SLOW, BUF_SYMBOLS, CleanUpDATVFramework(), config::cnr, coeffs_sampler, config::constellation, leansdr::cstln_receiver< T, SOFTSYMB >::cstln, decimation(), leansdr::cnr_fft< T >::decimation, DATVDemodSettings::DVB_S, DATVDemodSettings::DVB_S2, config::fastlock, config::fec, config::Fm, config::Fs, getLeanDVBCodeRateFromDATV(), config::hard_metric, DATVDemodSettings::m_allowDrift, m_blnDVBInitialized, DATVDemodSettings::m_excursion, DATVDemodSettings::m_fastLock, DATVDemodSettings::m_fec, DATVDemodSettings::m_filter, DATVDemodSettings::m_hardMetric, m_lngExpectedReadIQ, m_lngReadIQ, DATVDemodSettings::m_modulation, DATVDemodSettings::m_notchFilters, m_objCfg, m_objDemodulator, m_objScheduler, DATVDemodSettings::m_rollOff, m_sampleRate, m_settings, DATVDemodSettings::m_standard, DATVDemodSettings::m_symbolRate, DATVDemodSettings::m_viterbi, leansdr::max(), ncoeffs_sampler, p_autonotched, p_cnr, p_freq, p_mer, p_preprocessed, p_rawiq, p_rawiq_writer, p_sampled, p_ss, p_symbols, DATVDemodSettings::PSK8, DATVDemodSettings::QAM16, DATVDemodSettings::QAM256, DATVDemodSettings::QAM64, DATVDemodSettings::QPSK, r_auto_notch, r_cnr, config::rolloff, leansdr::filtergen::root_raised_cosine(), config::rrc_rej, config::rrc_steps, DATVDemodSettings::SAMP_LINEAR, DATVDemodSettings::SAMP_NEAREST, DATVDemodSettings::SAMP_RRC, config::sampler, sampler, config::standard, and config::viterbi.
Referenced by feed().
 {
     m_blnDVBInitialized = false;
     m_lngReadIQ = 0;
     CleanUpDATVFramework(false);
     qDebug()  << "DATVDemod::InitDATVFramework:"
         <<  " Standard: " << m_settings.m_standard
         <<  " Symbol Rate: " << m_settings.m_symbolRate
         <<  " Modulation: " << m_settings.m_modulation
         <<  " Notch Filters: " << m_settings.m_notchFilters
         <<  " Allow Drift: " << m_settings.m_allowDrift
         <<  " Fast Lock: " << m_settings.m_fastLock
         <<  " Filter: " << m_settings.m_filter
         <<  " HARD METRIC: " << m_settings.m_hardMetric
         <<  " RollOff: " << m_settings.m_rollOff
         <<  " Viterbi: " << m_settings.m_viterbi
         <<  " Excursion: " << m_settings.m_excursion
         <<  " Sample rate: " << m_sampleRate;
     m_objCfg.standard = m_settings.m_standard;
     m_objCfg.fec = (leansdr::code_rate) getLeanDVBCodeRateFromDATV(m_settings.m_fec);
     m_objCfg.Fs = (float) m_sampleRate;
     m_objCfg.Fm = (float) m_settings.m_symbolRate;
     m_objCfg.fastlock = m_settings.m_fastLock;
     m_objCfg.sampler = m_settings.m_filter;
     m_objCfg.rolloff = m_settings.m_rollOff;  //0...1
     m_objCfg.rrc_rej = (float) m_settings.m_excursion;  //dB
     m_objCfg.rrc_steps = 0; //auto
     switch(m_settings.m_modulation)
     {
         case DATVDemodSettings::BPSK:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::eucl_ss, 256>::BPSK;
            break;
         case DATVDemodSettings::QPSK:
             m_objCfg.constellation = leansdr::cstln_lut<leansdr::eucl_ss, 256>::QPSK;
             break;
         case DATVDemodSettings::PSK8:
             m_objCfg.constellation = leansdr::cstln_lut<leansdr::eucl_ss, 256>::PSK8;
             break;
         case DATVDemodSettings::APSK16:
             m_objCfg.constellation = leansdr::cstln_lut<leansdr::eucl_ss, 256>::APSK16;
             break;
         case DATVDemodSettings::APSK32:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::eucl_ss, 256>::APSK32;
            break;
         case DATVDemodSettings::APSK64E:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::eucl_ss, 256>::APSK64E;
            break;
         case DATVDemodSettings::QAM16:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::eucl_ss, 256>::QAM16;
            break;
         case DATVDemodSettings::QAM64:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::eucl_ss, 256>::QAM64;
            break;
         case DATVDemodSettings::QAM256:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::eucl_ss, 256>::QAM256;
            break;
         default:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::eucl_ss, 256>::BPSK;
            break;
     }
     m_objCfg.allow_drift = m_settings.m_allowDrift;
     m_objCfg.anf = m_settings.m_notchFilters;
     m_objCfg.hard_metric = m_settings.m_hardMetric;
     m_objCfg.sampler = m_settings.m_filter;
     m_objCfg.viterbi = m_settings.m_viterbi;
     // Min buffer size for baseband data
     //   scopes: 1024
     //   ss_estimator: 1024
     //   anf: 4096
     //   cstln_receiver: reads in chunks of 128+1
     BUF_BASEBAND = 4096 * m_objCfg.buf_factor;
     // Min buffer size for IQ symbols
     //   cstln_receiver: writes in chunks of 128/omega symbols (margin 128)
     //   deconv_sync: reads at least 64+32
     // A larger buffer improves performance significantly.
     BUF_SYMBOLS = 1024 * m_objCfg.buf_factor;
     // Min buffer size for unsynchronized bytes
     //   deconv_sync: writes 32 bytes
     //   mpeg_sync: reads up to 204*scan_syncs = 1632 bytes
     BUF_BYTES = 2048 * m_objCfg.buf_factor;
     // Min buffer size for synchronized (but interleaved) bytes
     //   mpeg_sync: writes 1 rspacket
     //   deinterleaver: reads 17*11*12+204 = 2448 bytes
     BUF_MPEGBYTES = 2448 * m_objCfg.buf_factor;
     // Min buffer size for packets: 1
     BUF_PACKETS = m_objCfg.buf_factor;
     // Min buffer size for misc measurements: 1
     BUF_SLOW = m_objCfg.buf_factor;
     m_lngExpectedReadIQ  = BUF_BASEBAND;
     m_objScheduler = new leansdr::scheduler();
     //***************
     p_rawiq = new leansdr::pipebuf<leansdr::cf32>(m_objScheduler, "rawiq", BUF_BASEBAND);
     p_rawiq_writer = new leansdr::pipewriter<leansdr::cf32>(*p_rawiq);
     p_preprocessed = p_rawiq;
     // NOTCH FILTER
     if (m_objCfg.anf>0)
     {
         p_autonotched = new leansdr::pipebuf<leansdr::cf32>(m_objScheduler, "autonotched", BUF_BASEBAND);
         r_auto_notch = new leansdr::auto_notch<leansdr::f32>(m_objScheduler, *p_preprocessed, *p_autonotched, m_objCfg.anf, 0);
         p_preprocessed = p_autonotched;
     }
     // FREQUENCY CORRECTION
     //******** -> if ( m_objCfg.Fderot>0 )
     // CNR ESTIMATION
     p_cnr = new leansdr::pipebuf<leansdr::f32>(m_objScheduler, "cnr", BUF_SLOW);
     if (m_objCfg.cnr == true)
     {
         r_cnr = new leansdr::cnr_fft<leansdr::f32>(m_objScheduler, *p_preprocessed, *p_cnr, m_objCfg.Fm/m_objCfg.Fs);
         r_cnr->decimation = decimation(m_objCfg.Fs, 1);  // 1 Hz
     }
     // FILTERING
     int decim = 1;
     //******** -> if ( m_objCfg.resample )
     // DECIMATION
     // (Unless already done in resampler)
     //******** -> if ( !m_objCfg.resample && m_objCfg.decim>1 )
     //Resampling FS
     // Generic constellation receiver
     p_symbols = new leansdr::pipebuf<leansdr::eucl_ss>(m_objScheduler, "PSK soft-symbols", BUF_SYMBOLS);
     p_freq = new leansdr::pipebuf<leansdr::f32> (m_objScheduler, "freq", BUF_SLOW);
     p_ss = new leansdr::pipebuf<leansdr::f32> (m_objScheduler, "SS", BUF_SLOW);
     p_mer = new leansdr::pipebuf<leansdr::f32> (m_objScheduler, "MER", BUF_SLOW);
     p_sampled = new leansdr::pipebuf<leansdr::cf32> (m_objScheduler, "PSK symbols", BUF_BASEBAND);
     switch (m_objCfg.sampler)
     {
         case DATVDemodSettings::SAMP_NEAREST:
           sampler = new leansdr::nearest_sampler<float>();
           break;
         case DATVDemodSettings::SAMP_LINEAR:
           sampler = new leansdr::linear_sampler<float>();
           break;
         case DATVDemodSettings::SAMP_RRC:
         {
           if (m_objCfg.rrc_steps == 0)
           {
             // At least 64 discrete sampling points between symbols
             m_objCfg.rrc_steps = std::max(1, (int)(64*m_objCfg.Fm / m_objCfg.Fs));
           }
           float Frrc = m_objCfg.Fs * m_objCfg.rrc_steps;  // Sample freq of the RRC filter
           float transition = (m_objCfg.Fm/2) * m_objCfg.rolloff;
           int order = m_objCfg.rrc_rej * Frrc / (22*transition);
           ncoeffs_sampler = leansdr::filtergen::root_raised_cosine(order, m_objCfg.Fm/Frrc, m_objCfg.rolloff, &coeffs_sampler);
           sampler = new leansdr::fir_sampler<float,float>(ncoeffs_sampler, coeffs_sampler, m_objCfg.rrc_steps);
           break;
         }
         default:
           qCritical("DATVDemod::InitDATVFramework: Interpolator not implemented");
           return;
     }
     m_objDemodulator = new leansdr::cstln_receiver<leansdr::f32, leansdr::eucl_ss>(
             m_objScheduler,
             sampler,
             *p_preprocessed,
             *p_symbols,
             p_freq,
             p_ss,
             p_mer,
             p_sampled);
     if (m_objCfg.standard == DATVDemodSettings::DVB_S)
     {
         if ( m_objCfg.constellation != leansdr::cstln_lut<leansdr::eucl_ss, 256>::QPSK
             && m_objCfg.constellation != leansdr::cstln_lut<leansdr::eucl_ss, 256>::BPSK )
         {
             qWarning("DATVDemod::InitDATVFramework: non-standard constellation for DVB-S");
         }
     }
     if (m_objCfg.standard == DATVDemodSettings::DVB_S2)
     {
         // For DVB-S2 testing only.
         // Constellation should be determined from PL signalling.
         qDebug("DATVDemod::InitDATVFramework: DVB-S2: Testing symbol sampler only.");
     }
     m_objDemodulator->cstln = make_dvbs_constellation(m_objCfg.constellation, m_objCfg.fec);
     if (m_objCfg.hard_metric) {
         m_objDemodulator->cstln->harden();
     }
     m_objDemodulator->set_omega(m_objCfg.Fs/m_objCfg.Fm);
     //******** if ( m_objCfg.Ftune )
     //{
     //  m_objDemodulator->set_freq(m_objCfg.Ftune/m_objCfg.Fs);
     //}
     if (m_objCfg.allow_drift) {
         m_objDemodulator->set_allow_drift(true);
     }
     //******** -> if ( m_objCfg.viterbi )
     if (m_objCfg.viterbi) {
         m_objDemodulator->pll_adjustment /= 6;
     }
     m_objDemodulator->meas_decimation = decimation(m_objCfg.Fs, m_objCfg.Finfo);
     // TRACKING FILTERS
     if (r_cnr)
     {
         r_cnr->freq_tap = &m_objDemodulator->freq_tap;
         r_cnr->tap_multiplier = 1.0 / decim;
     }
     //constellation
     if (m_objRegisteredTVScreen)
     {
         qDebug("DATVDemod::InitDATVFramework: Register DVBSTVSCREEN");
         m_objRegisteredTVScreen->resizeTVScreen(256,256);
         r_scope_symbols = new leansdr::datvconstellation<leansdr::f32>(m_objScheduler, *p_sampled, -128,128, nullptr, m_objRegisteredTVScreen);
         r_scope_symbols->decimation = 1;
         r_scope_symbols->cstln = &m_objDemodulator->cstln;
         r_scope_symbols->calculate_cstln_points();
     }
     // DECONVOLUTION AND SYNCHRONIZATION
     p_bytes = new leansdr::pipebuf<leansdr::u8>(m_objScheduler, "bytes", BUF_BYTES);
     r_deconv = nullptr;
     //******** -> if ( m_objCfg.viterbi )
     if (m_objCfg.viterbi)
     {
         if (m_objCfg.fec == leansdr::FEC23 && (m_objDemodulator->cstln->nsymbols == 4 || m_objDemodulator->cstln->nsymbols == 64)) {
             m_objCfg.fec = leansdr::FEC46;
         }
         //To uncomment -> Linking Problem : undefined symbol: _ZN7leansdr21viterbi_dec_interfaceIhhiiE6updateEPiS2_
         r = new leansdr::viterbi_sync(m_objScheduler, (*p_symbols), (*p_bytes), m_objDemodulator->cstln, m_objCfg.fec);
         if (m_objCfg.fastlock) {
             r->resync_period = 1;
         }
     }
     else
     {
         r_deconv = make_deconvol_sync_simple(m_objScheduler, (*p_symbols), (*p_bytes), m_objCfg.fec);
         r_deconv->fastlock = m_objCfg.fastlock;
     }
     //******* -> if ( m_objCfg.hdlc )
     p_mpegbytes = new leansdr::pipebuf<leansdr::u8> (m_objScheduler, "mpegbytes", BUF_MPEGBYTES);
     p_lock = new leansdr::pipebuf<int> (m_objScheduler, "lock", BUF_SLOW);
     p_locktime = new leansdr::pipebuf<leansdr::u32> (m_objScheduler, "locktime", BUF_PACKETS);
     r_sync_mpeg = new leansdr::mpeg_sync<leansdr::u8, 0>(m_objScheduler, *p_bytes, *p_mpegbytes, r_deconv, p_lock, p_locktime);
     r_sync_mpeg->fastlock = m_objCfg.fastlock;
     // DEINTERLEAVING
     p_rspackets = new leansdr::pipebuf<leansdr::rspacket<leansdr::u8> >(m_objScheduler, "RS-enc packets", BUF_PACKETS);
     r_deinter = new leansdr::deinterleaver<leansdr::u8>(m_objScheduler, *p_mpegbytes, *p_rspackets);
     // REED-SOLOMON
     p_vbitcount = new leansdr::pipebuf<int>(m_objScheduler, "Bits processed", BUF_PACKETS);
     p_verrcount = new leansdr::pipebuf<int>(m_objScheduler, "Bits corrected", BUF_PACKETS);
     p_rtspackets = new leansdr::pipebuf<leansdr::tspacket>(m_objScheduler, "rand TS packets", BUF_PACKETS);
     r_rsdec = new leansdr::rs_decoder<leansdr::u8, 0>(m_objScheduler, *p_rspackets, *p_rtspackets, p_vbitcount, p_verrcount);
     // BER ESTIMATION
     /*
      p_vber = new pipebuf<float> (m_objScheduler, "VBER", BUF_SLOW);
      r_vber = new rate_estimator<float> (m_objScheduler, *p_verrcount, *p_vbitcount, *p_vber);
      r_vber->sample_size = m_objCfg.Fm/2;  // About twice per second, depending on CR
      // Require resolution better than 2E-5
      if ( r_vber->sample_size < 50000 )
      {
      r_vber->sample_size = 50000;
      }
      */
     // DERANDOMIZATION
     p_tspackets = new leansdr::pipebuf<leansdr::tspacket>(m_objScheduler, "TS packets", BUF_PACKETS);
     r_derand = new leansdr::derandomizer(m_objScheduler, *p_rtspackets, *p_tspackets);
     // OUTPUT
     r_videoplayer = new leansdr::datvvideoplayer<leansdr::tspacket>(m_objScheduler, *p_tspackets, m_objVideoStream, &m_udpStream);
     m_blnDVBInitialized = true;
 }
InitDATVParameters()
void DATVDemod::InitDATVParameters (int intMsps, int intRFBandwidth, int intCenterFrequency, DATVDemodSettings::dvb_version enmStandard, DATVDemodSettings::DATVModulation enmModulation, leansdr::code_rate enmFEC, int intSampleRate, int intSymbolRate, int intNotchFilters, bool blnAllowDrift, bool blnFastLock, DATVDemodSettings::dvb_sampler enmFilter, bool blnHardMetric, float fltRollOff, bool blnViterbi, int intEExcursion)
InitDATVS2Framework()
void DATVDemod::InitDATVS2Framework ()
p_cnr = new leansdr::pipebuf<leansdr::f32>(m_objScheduler, "cnr", BUF_SLOW);
if (m_objCfg.cnr == true) { r_cnr = new leansdr::cnr_fft<leansdr::f32>(m_objScheduler, *p_preprocessed, *p_cnr, m_objCfg.Fm/m_objCfg.Fs); r_cnr->decimation = decimation(m_objCfg.Fs, 1); // 1 Hz }
Definition at line 869 of file datvdemod.cpp.
References config::allow_drift, config::anf, DATVDemodSettings::APSK16, DATVDemodSettings::APSK32, DATVDemodSettings::APSK64E, DATVDemodSettings::BPSK, BUF_BASEBAND, config::buf_factor, BUF_FRAMES, BUF_S2PACKETS, BUF_SLOTS, BUF_SLOW, BUF_SYMBOLS, CleanUpDATVFramework(), coeffs_sampler, config::constellation, leansdr::s2_frame_receiver< T, SOFTSYMB >::cstln, decimation(), config::fastlock, config::fec, config::Finfo, config::Fm, leansdr::s2_frame_receiver< T, SOFTSYMB >::Fm, config::Fs, config::Ftune, leansdr::s2_frame_receiver< T, SOFTSYMB >::Ftune, getLeanDVBCodeRateFromDATV(), config::hard_metric, DATVDemodSettings::m_allowDrift, m_blnDVBInitialized, DATVDemodSettings::m_excursion, DATVDemodSettings::m_fastLock, DATVDemodSettings::m_fec, DATVDemodSettings::m_filter, DATVDemodSettings::m_hardMetric, m_lngExpectedReadIQ, m_lngReadIQ, DATVDemodSettings::m_modulation, DATVDemodSettings::m_notchFilters, m_objCfg, m_objDemodulatorDVBS2, m_objScheduler, DATVDemodSettings::m_rollOff, m_sampleRate, m_settings, DATVDemodSettings::m_standard, DATVDemodSettings::m_symbolRate, DATVDemodSettings::m_viterbi, leansdr::max(), leansdr::modcod_info::MAX_SLOTS_PER_FRAME, leansdr::s2_frame_receiver< T, SOFTSYMB >::meas_decimation, ncoeffs_sampler, leansdr::s2_frame_receiver< T, SOFTSYMB >::omega, p_autonotched, p_cstln, p_cstln_pls, p_framelock, p_freq, p_mer, p_preprocessed, p_rawiq, p_rawiq_writer, p_slots_dvbs2, p_ss, DATVDemodSettings::PSK8, DATVDemodSettings::QAM16, DATVDemodSettings::QAM256, DATVDemodSettings::QAM64, DATVDemodSettings::QPSK, r_auto_notch, config::rolloff, leansdr::filtergen::root_raised_cosine(), config::rrc_rej, config::rrc_steps, S2_MAX_SYMBOLS, DATVDemodSettings::SAMP_LINEAR, DATVDemodSettings::SAMP_NEAREST, DATVDemodSettings::SAMP_RRC, config::sampler, sampler, config::standard, leansdr::s2_frame_receiver< T, SOFTSYMB >::strongpls, and config::viterbi.
Referenced by feed().
 {
     leansdr::s2_frame_receiver<leansdr::f32, leansdr::llr_ss> * objDemodulatorDVBS2;
     m_blnDVBInitialized = false;
     m_lngReadIQ = 0;
     CleanUpDATVFramework(false);
     qDebug()  << "DATVDemod::InitDATVS2Framework:"
         <<  " Standard: " << m_settings.m_standard
         <<  " Symbol Rate: " << m_settings.m_symbolRate
         <<  " Modulation: " << m_settings.m_modulation
         <<  " Notch Filters: " << m_settings.m_notchFilters
         <<  " Allow Drift: " << m_settings.m_allowDrift
         <<  " Fast Lock: " << m_settings.m_fastLock
         <<  " Filter: " << m_settings.m_filter
         <<  " HARD METRIC: " << m_settings.m_hardMetric
         <<  " RollOff: " << m_settings.m_rollOff
         <<  " Viterbi: " << m_settings.m_viterbi
         <<  " Excursion: " << m_settings.m_excursion
         <<  " Sample rate: " << m_sampleRate ;
     m_objCfg.standard = m_settings.m_standard;
     m_objCfg.fec = (leansdr::code_rate) getLeanDVBCodeRateFromDATV(m_settings.m_fec);
     m_objCfg.Fs = (float) m_sampleRate;
     m_objCfg.Fm = (float) m_settings.m_symbolRate;
     m_objCfg.fastlock = m_settings.m_fastLock;
     m_objCfg.sampler = m_settings.m_filter;
     m_objCfg.rolloff = m_settings.m_rollOff;  //0...1
     m_objCfg.rrc_rej = (float) m_settings.m_excursion;  //dB
     m_objCfg.rrc_steps = 0; //auto
     switch(m_settings.m_modulation)
     {
         case DATVDemodSettings::BPSK:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::llr_ss, 256>::BPSK;
            break;
         case DATVDemodSettings::QPSK:
             m_objCfg.constellation = leansdr::cstln_lut<leansdr::llr_ss, 256>::QPSK;
             break;
         case DATVDemodSettings::PSK8:
             m_objCfg.constellation = leansdr::cstln_lut<leansdr::llr_ss, 256>::PSK8;
             break;
         case DATVDemodSettings::APSK16:
             m_objCfg.constellation = leansdr::cstln_lut<leansdr::llr_ss, 256>::APSK16;
             break;
         case DATVDemodSettings::APSK32:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::llr_ss, 256>::APSK32;
            break;
         case DATVDemodSettings::APSK64E:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::llr_ss, 256>::APSK64E;
            break;
         case DATVDemodSettings::QAM16:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::llr_ss, 256>::QAM16;
            break;
         case DATVDemodSettings::QAM64:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::llr_ss, 256>::QAM64;
            break;
         case DATVDemodSettings::QAM256:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::llr_ss, 256>::QAM256;
            break;
         default:
            m_objCfg.constellation = leansdr::cstln_lut<leansdr::llr_ss, 256>::BPSK;
            break;
     }
     m_objCfg.allow_drift = m_settings.m_allowDrift;
     m_objCfg.anf = m_settings.m_notchFilters;
     m_objCfg.hard_metric = m_settings.m_hardMetric;
     m_objCfg.sampler = m_settings.m_filter;
     m_objCfg.viterbi = m_settings.m_viterbi;
     // Min buffer size for baseband data
     S2_MAX_SYMBOLS = (90*(1+360)+36*((360-1)/16));
     BUF_BASEBAND = S2_MAX_SYMBOLS * 2 * (m_objCfg.Fs/m_objCfg.Fm) * m_objCfg.buf_factor;
     // Min buffer size for IQ symbols
     //   cstln_receiver: writes in chunks of 128/omega symbols (margin 128)
     //   deconv_sync: reads at least 64+32
     // A larger buffer improves performance significantly.
     BUF_SYMBOLS = 1024 * m_objCfg.buf_factor;
     // Min buffer size for misc measurements: 1
     BUF_SLOW = m_objCfg.buf_factor;
     // dvbs2 : Min buffer size for slots: 4 for deinterleaver
     BUF_SLOTS = leansdr::modcod_info::MAX_SLOTS_PER_FRAME * m_objCfg.buf_factor;
     BUF_FRAMES = m_objCfg.buf_factor;
      // Min buffer size for TS packets: Up to 39 per BBFRAME
     BUF_S2PACKETS = (leansdr::fec_info::KBCH_MAX/188/8+1) * m_objCfg.buf_factor;
     m_lngExpectedReadIQ  = BUF_BASEBAND;
     m_objScheduler = new leansdr::scheduler();
     //***************
     p_rawiq = new leansdr::pipebuf<leansdr::cf32>(m_objScheduler, "rawiq", BUF_BASEBAND);
     p_rawiq_writer = new leansdr::pipewriter<leansdr::cf32>(*p_rawiq);
     p_preprocessed = p_rawiq;
     // NOTCH FILTER
     if (m_objCfg.anf>0)
     {
         p_autonotched = new leansdr::pipebuf<leansdr::cf32>(m_objScheduler, "autonotched", BUF_BASEBAND);
         r_auto_notch = new leansdr::auto_notch<leansdr::f32>(m_objScheduler, *p_preprocessed, *p_autonotched, m_objCfg.anf, 0);
         p_preprocessed = p_autonotched;
     }
     // FREQUENCY CORRECTION
     //******** -> if ( m_objCfg.Fderot>0 )
     // CNR ESTIMATION
     // FILTERING
     int decim = 1;
     //******** -> if ( m_objCfg.resample )
     // DECIMATION
     // (Unless already done in resampler)
     //******** -> if ( !m_objCfg.resample && m_objCfg.decim>1 )
     //Resampling FS
     // Generic constellation receiver
     p_freq = new leansdr::pipebuf<leansdr::f32> (m_objScheduler, "freq", BUF_SLOW);
     p_ss = new leansdr::pipebuf<leansdr::f32> (m_objScheduler, "SS", BUF_SLOW);
     p_mer = new leansdr::pipebuf<leansdr::f32> (m_objScheduler, "MER", BUF_SLOW);
     switch (m_objCfg.sampler)
     {
         case DATVDemodSettings::SAMP_NEAREST:
           sampler = new leansdr::nearest_sampler<float>();
           break;
         case DATVDemodSettings::SAMP_LINEAR:
           sampler = new leansdr::linear_sampler<float>();
           break;
         case DATVDemodSettings::SAMP_RRC:
         {
           if (m_objCfg.rrc_steps == 0)
           {
             // At least 64 discrete sampling points between symbols
             m_objCfg.rrc_steps = std::max(1, (int)(64*m_objCfg.Fm / m_objCfg.Fs));
           }
           float Frrc = m_objCfg.Fs * m_objCfg.rrc_steps;  // Sample freq of the RRC filter
           float transition = (m_objCfg.Fm/2) * m_objCfg.rolloff;
           int order = m_objCfg.rrc_rej * Frrc / (22*transition);
           ncoeffs_sampler = leansdr::filtergen::root_raised_cosine(order, m_objCfg.Fm/Frrc, m_objCfg.rolloff, &coeffs_sampler);
           sampler = new leansdr::fir_sampler<float,float>(ncoeffs_sampler, coeffs_sampler, m_objCfg.rrc_steps);
           break;
         }
         default:
           qCritical("DATVDemod::InitDATVS2Framework: Interpolator not implemented");
           return;
     }
     p_slots_dvbs2 = new leansdr::pipebuf< leansdr::plslot<leansdr::llr_ss> > (m_objScheduler, "PL slots", BUF_SLOTS);
     p_cstln = new leansdr::pipebuf<leansdr::cf32>(m_objScheduler, "cstln", BUF_BASEBAND);
     p_cstln_pls = new leansdr::pipebuf<leansdr::cf32>(m_objScheduler, "PLS cstln", BUF_BASEBAND);
     p_framelock = new leansdr::pipebuf<int>(m_objScheduler, "frame lock", BUF_SLOW);
     m_objDemodulatorDVBS2 = new leansdr::s2_frame_receiver<leansdr::f32, leansdr::llr_ss>(
                         m_objScheduler,
                         sampler,
                         *p_preprocessed,
                         *(leansdr::pipebuf< leansdr::plslot<leansdr::llr_ss> > *) p_slots_dvbs2,
                         /* p_freq */ nullptr,
                         /* p_ss */ nullptr,
                         /* p_mer */ nullptr,
                         p_cstln,
                         /* p_cstln_pls */ nullptr,
                         /*p_iqsymbols*/ nullptr,
                         /* p_framelock */nullptr);
     objDemodulatorDVBS2 = (leansdr::s2_frame_receiver<leansdr::f32, leansdr::llr_ss> *) m_objDemodulatorDVBS2;
     objDemodulatorDVBS2->omega = m_objCfg.Fs/m_objCfg.Fm;
 //objDemodulatorDVBS2->mu=1;
     m_objCfg.Ftune=0.0f;
     objDemodulatorDVBS2->Ftune = m_objCfg.Ftune / m_objCfg.Fm;
 /*
   demod.strongpls = cfg.strongpls;
 */
     objDemodulatorDVBS2->Fm = m_objCfg.Fm;
     objDemodulatorDVBS2->meas_decimation = decimation(m_objCfg.Fs, m_objCfg.Finfo);
     objDemodulatorDVBS2->strongpls = false;
     objDemodulatorDVBS2->cstln = make_dvbs2_constellation(m_objCfg.constellation, m_objCfg.fec);
     m_cstlnSetByModcod = false;
     //constellation
     if (m_objRegisteredTVScreen)
     {
         qDebug("DATVDemod::InitDATVS2Framework: Register DVBS 2 TVSCREEN");
         m_objRegisteredTVScreen->resizeTVScreen(256,256);
         r_scope_symbols_dvbs2 = new leansdr::datvdvbs2constellation<leansdr::f32>(m_objScheduler, *p_cstln /* *p_sampled */ /* *p_cstln */, -128,128, nullptr, m_objRegisteredTVScreen);
         r_scope_symbols_dvbs2->decimation = 1;
         r_scope_symbols_dvbs2->cstln = (leansdr::cstln_base**) &objDemodulatorDVBS2->cstln;
         r_scope_symbols_dvbs2->calculate_cstln_points();
     }
     // Bit-flipping mode.
     // Deinterleave into hard bits.
     p_bbframes = new leansdr::pipebuf<leansdr::bbframe>(m_objScheduler, "BB frames", BUF_FRAMES);
     p_fecframes = new leansdr::pipebuf< leansdr::fecframe<leansdr::hard_sb> >(m_objScheduler, "FEC frames", BUF_FRAMES);
     p_s2_deinterleaver = new leansdr::s2_deinterleaver<leansdr::llr_ss,leansdr::hard_sb>(
         m_objScheduler,
         *(leansdr::pipebuf< leansdr::plslot<leansdr::llr_ss> > *) p_slots_dvbs2,
         *(leansdr::pipebuf< leansdr::fecframe<leansdr::hard_sb> > * ) p_fecframes
     );
     p_vbitcount= new leansdr::pipebuf<int>(m_objScheduler, "Bits processed", BUF_S2PACKETS);
     p_verrcount = new leansdr::pipebuf<int>(m_objScheduler, "Bits corrected", BUF_S2PACKETS);
     r_fecdec =  new leansdr::s2_fecdec<bool, leansdr::hard_sb>(
         m_objScheduler, *(leansdr::pipebuf< leansdr::fecframe<leansdr::hard_sb> > * ) p_fecframes,
         *(leansdr::pipebuf<leansdr::bbframe> *) p_bbframes,
         p_vbitcount,
         p_verrcount
     );
     leansdr::s2_fecdec<bool, leansdr::hard_sb> *fecdec = (leansdr::s2_fecdec<bool, leansdr::hard_sb> * ) r_fecdec;
     fecdec->bitflips=0;
     /*
     fecdec->bitflips = cfg.ldpc_bf; //int TODO
     if ( ! cfg.ldpc_bf )
     fprintf(stderr, "Warning: No LDPC error correction selected.\n")
     */
     // Deframe BB frames to TS packets
     p_lock = new leansdr::pipebuf<int> (m_objScheduler, "lock", BUF_SLOW);
     p_locktime = new leansdr::pipebuf<leansdr::u32> (m_objScheduler, "locktime", BUF_S2PACKETS);
     p_tspackets = new leansdr::pipebuf<leansdr::tspacket>(m_objScheduler, "TS packets", BUF_S2PACKETS);
     p_deframer = new leansdr::s2_deframer(m_objScheduler,*(leansdr::pipebuf<leansdr::bbframe> *) p_bbframes, *p_tspackets, p_lock, p_locktime);
 /*
  if ( cfg.fd_gse >= 0 ) deframer.fd_gse = cfg.fd_gse;
 */
     //**********************************************
     // OUTPUT
     r_videoplayer = new leansdr::datvvideoplayer<leansdr::tspacket>(m_objScheduler, *p_tspackets, m_objVideoStream, &m_udpStream);
     m_blnDVBInitialized = true;
 }
isCstlnSetByModcod()
bool DATVDemod::isCstlnSetByModcod () const inline
Definition at line 191 of file datvdemod.h.
Referenced by DATVDemodGUI::tick().
 { return m_cstlnSetByModcod; }
PlayVideo()
bool DATVDemod::PlayVideo (bool blnStartStop)
Definition at line 162 of file datvdemod.cpp.
References DATVideostream::bytesAvailable(), m_blnStartStopVideo, m_objRegisteredVideoRender, m_objRenderThread, m_objVideoStream, DATVideostream::MultiThreaded, DATVideoRenderThread::setStreamAndRenderer(), DATVideoRenderThread::stopRendering(), and DATVideostream::ThreadTimeOut.
Referenced by DATVDemodGUI::tick().
 {
     if (m_objVideoStream == nullptr) {
         return false;
     }
     if (m_objRegisteredVideoRender == nullptr) {
         return false;
     }
     if (m_objRenderThread == nullptr) {
         return false;
     }
     if (m_blnStartStopVideo && !blnStartStop) {
         return true;
     }
     if (blnStartStop == true) {
         m_blnStartStopVideo = true;
     }
     if (m_objRenderThread->isRunning())
     {
         if (blnStartStop == true) {
             m_objRenderThread->stopRendering();
         }
         return true;
     }
     if (m_objVideoStream->bytesAvailable() > 0)
     {
         m_objRenderThread->setStreamAndRenderer(m_objRegisteredVideoRender, m_objVideoStream);
         m_objVideoStream->MultiThreaded = true;
         m_objVideoStream->ThreadTimeOut = 5000; //5000 ms
         m_objRenderThread->start();
     }
     return true;
 }
serialize()
virtual QByteArray DATVDemod::serialize () const inline virtual
Implements ChannelAPI.
Definition at line 139 of file datvdemod.h.
 { return QByteArray(); }
SetTVScreen()
bool DATVDemod::SetTVScreen (TVScreen * objScreen)
Definition at line 112 of file datvdemod.cpp.
References m_objRegisteredTVScreen.
Referenced by DATVDemodGUI::DATVDemodGUI().
 {
     m_objRegisteredTVScreen = objScreen;
     return true;
 }
SetVideoRender()
DATVideostream * DATVDemod::SetVideoRender (DATVideoRender * objScreen)
Definition at line 118 of file datvdemod.cpp.
References m_audioFifo, m_objRegisteredVideoRender, m_objRenderThread, m_objVideoStream, and DATVideoRender::setAudioFIFO().
Referenced by DATVDemodGUI::DATVDemodGUI().
 {
     m_objRegisteredVideoRender = objScreen;
     m_objRegisteredVideoRender->setAudioFIFO(&m_audioFifo);
     m_objRenderThread = new DATVideoRenderThread(m_objRegisteredVideoRender, m_objVideoStream);
     return m_objVideoStream;
 }
start()
void DATVDemod::start () virtual
Implements BasebandSampleSink.
Definition at line 1294 of file datvdemod.cpp.
References AudioFifo::clear(), and m_audioFifo.
 {
     m_audioFifo.clear();
 }
stop()
void DATVDemod::stop () virtual
Implements BasebandSampleSink.
Definition at line 1299 of file datvdemod.cpp.
 {
 }
videoActive()
bool DATVDemod::videoActive ()
Definition at line 135 of file datvdemod.cpp.
References DATVideoRender::getVideoStreamIndex(), and m_objRegisteredVideoRender.
Referenced by DATVDemodGUI::tick().
 {
     if (m_objRegisteredVideoRender) {
         return m_objRegisteredVideoRender->getVideoStreamIndex() >= 0;
     } else {
         return false;
     }
 }
videoDecodeOK()
bool DATVDemod::videoDecodeOK ()
Definition at line 153 of file datvdemod.cpp.
References DATVideoRender::getVideoDecodeOK(), and m_objRegisteredVideoRender.
Referenced by DATVDemodGUI::tick().
 {
     if (m_objRegisteredVideoRender) {
         return m_objRegisteredVideoRender->getVideoDecodeOK();
     } else {
         return false;
     }
 }
Member Data Documentation
BUF_BASEBAND
unsigned long DATVDemod::BUF_BASEBAND private
Definition at line 276 of file datvdemod.h.
Referenced by InitDATVFramework(), and InitDATVS2Framework().
BUF_BYTES
unsigned long DATVDemod::BUF_BYTES private
Definition at line 278 of file datvdemod.h.
Referenced by InitDATVFramework().
BUF_FRAMES
unsigned long DATVDemod::BUF_FRAMES private
Definition at line 286 of file datvdemod.h.
Referenced by InitDATVS2Framework().
BUF_MPEGBYTES
unsigned long DATVDemod::BUF_MPEGBYTES private
Definition at line 279 of file datvdemod.h.
Referenced by InitDATVFramework().
BUF_PACKETS
unsigned long DATVDemod::BUF_PACKETS private
Definition at line 280 of file datvdemod.h.
Referenced by InitDATVFramework().
BUF_S2PACKETS
unsigned long DATVDemod::BUF_S2PACKETS private
Definition at line 287 of file datvdemod.h.
Referenced by InitDATVS2Framework().
BUF_SLOTS
unsigned long DATVDemod::BUF_SLOTS private
Definition at line 285 of file datvdemod.h.
Referenced by InitDATVS2Framework().
BUF_SLOW
unsigned long DATVDemod::BUF_SLOW private
Definition at line 281 of file datvdemod.h.
Referenced by InitDATVFramework(), and InitDATVS2Framework().
BUF_SYMBOLS
unsigned long DATVDemod::BUF_SYMBOLS private
Definition at line 277 of file datvdemod.h.
Referenced by InitDATVFramework(), and InitDATVS2Framework().
coeffs
float* DATVDemod::coeffs private
Definition at line 320 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
coeffs_sampler
float* DATVDemod::coeffs_sampler private
Definition at line 325 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), InitDATVFramework(), and InitDATVS2Framework().
m_audioFifo
AudioFifo DATVDemod::m_audioFifo private
Definition at line 412 of file datvdemod.h.
Referenced by applySettings(), SetVideoRender(), start(), and ~DATVDemod().
m_blnDVBInitialized
bool DATVDemod::m_blnDVBInitialized private
Definition at line 295 of file datvdemod.h.
Referenced by feed(), InitDATVFramework(), and InitDATVS2Framework().
m_blnInitialized
bool DATVDemod::m_blnInitialized private
Definition at line 417 of file datvdemod.h.
Referenced by ~DATVDemod().
m_blnNeedConfigUpdate
bool DATVDemod::m_blnNeedConfigUpdate private
Definition at line 296 of file datvdemod.h.
Referenced by applySettings(), and feed().
m_blnRenderingVideo
bool DATVDemod::m_blnRenderingVideo private
Definition at line 418 of file datvdemod.h.
m_blnStartStopVideo
bool DATVDemod::m_blnStartStopVideo private
Definition at line 419 of file datvdemod.h.
Referenced by PlayVideo().
m_channelId
const QString DATVDemod::m_channelId = "DATVDemod" static
Definition at line 198 of file datvdemod.h.
Referenced by DATVDemodPlugin::initPlugin().
m_channelIdURI
const QString DATVDemod::m_channelIdURI = "sdrangel.channel.demoddatv" static
Definition at line 197 of file datvdemod.h.
Referenced by DATVDemodGUI::DATVDemodGUI(), and DATVDemodPlugin::initPlugin().
m_channelizer
DownChannelizer* DATVDemod::m_channelizer private
Definition at line 402 of file datvdemod.h.
Referenced by handleMessage(), and ~DATVDemod().
m_cstlnSetByModcod
bool DATVDemod::m_cstlnSetByModcod private
Definition at line 420 of file datvdemod.h.
Referenced by feed().
m_deviceAPI
DeviceAPI* DATVDemod::m_deviceAPI private
Definition at line 399 of file datvdemod.h.
Referenced by ~DATVDemod().
m_enmModulation
DATVDemodSettings::DATVModulation DATVDemod::m_enmModulation private
Definition at line 424 of file datvdemod.h.
m_inputFrequencyOffset
int DATVDemod::m_inputFrequencyOffset private
Definition at line 429 of file datvdemod.h.
Referenced by handleMessage().
m_lngExpectedReadIQ
unsigned long DATVDemod::m_lngExpectedReadIQ private
Definition at line 271 of file datvdemod.h.
Referenced by InitDATVFramework(), and InitDATVS2Framework().
m_lngReadIQ
long DATVDemod::m_lngReadIQ private
Definition at line 272 of file datvdemod.h.
Referenced by feed(), InitDATVFramework(), and InitDATVS2Framework().
m_modcodCodeRate
int DATVDemod::m_modcodCodeRate private
Definition at line 422 of file datvdemod.h.
Referenced by feed().
m_modcodModulation
int DATVDemod::m_modcodModulation private
Definition at line 421 of file datvdemod.h.
Referenced by feed().
m_objCfg
struct config DATVDemod::m_objCfg private
Definition at line 293 of file datvdemod.h.
Referenced by InitDATVFramework(), and InitDATVS2Framework().
m_objDemodulator
leansdr::cstln_receiver<leansdr::f32, leansdr::eucl_ss>* DATVDemod::m_objDemodulator private
Definition at line 354 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), and InitDATVFramework().
m_objDemodulatorDVBS2
void* DATVDemod::m_objDemodulatorDVBS2 private
Definition at line 339 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), feed(), and InitDATVS2Framework().
m_objMagSqAverage
MovingAverageUtil<double, double, 32> DATVDemod::m_objMagSqAverage private
Definition at line 430 of file datvdemod.h.
Referenced by feed().
m_objNCO
NCO DATVDemod::m_objNCO private
Definition at line 415 of file datvdemod.h.
Referenced by applyChannelSettings(), applySettings(), and feed().
m_objRegisteredTVScreen
TVScreen* DATVDemod::m_objRegisteredTVScreen private
Definition at line 405 of file datvdemod.h.
Referenced by SetTVScreen().
m_objRegisteredVideoRender
DATVideoRender* DATVDemod::m_objRegisteredVideoRender private
Definition at line 406 of file datvdemod.h.
Referenced by applySettings(), audioActive(), audioDecodeOK(), PlayVideo(), SetVideoRender(), videoActive(), and videoDecodeOK().
m_objRenderThread
DATVideoRenderThread* DATVDemod::m_objRenderThread private
Definition at line 409 of file datvdemod.h.
Referenced by PlayVideo(), SetVideoRender(), and ~DATVDemod().
m_objRFFilter
fftfilt* DATVDemod::m_objRFFilter private
Definition at line 414 of file datvdemod.h.
Referenced by applyChannelSettings(), applySettings(), feed(), and ~DATVDemod().
m_objScheduler
leansdr::scheduler* DATVDemod::m_objScheduler private
Definition at line 292 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), feed(), InitDATVFramework(), and InitDATVS2Framework().
m_objSettingsMutex
QMutex DATVDemod::m_objSettingsMutex private
Definition at line 432 of file datvdemod.h.
Referenced by feed().
m_objVideoStream
DATVideostream* DATVDemod::m_objVideoStream private
Definition at line 407 of file datvdemod.h.
Referenced by PlayVideo(), SetVideoRender(), and ~DATVDemod().
m_sampleRate
int DATVDemod::m_sampleRate private
Definition at line 428 of file datvdemod.h.
Referenced by applyChannelSettings(), applySettings(), GetSampleRate(), handleMessage(), InitDATVFramework(), and InitDATVS2Framework().
m_settings
DATVDemodSettings DATVDemod::m_settings private
Definition at line 427 of file datvdemod.h.
Referenced by applyChannelSettings(), applySettings(), feed(), InitDATVFramework(), and InitDATVS2Framework().
m_threadedChannelizer
ThreadedBasebandSampleSink* DATVDemod::m_threadedChannelizer private
Definition at line 401 of file datvdemod.h.
Referenced by ~DATVDemod().
m_udpStream
DATVUDPStream DATVDemod::m_udpStream private
Definition at line 408 of file datvdemod.h.
Referenced by applySettings().
ncoeffs
int DATVDemod::ncoeffs private
Definition at line 321 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
ncoeffs_sampler
int DATVDemod::ncoeffs_sampler private
Definition at line 326 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), InitDATVFramework(), and InitDATVS2Framework().
p_autonotched
leansdr::pipebuf<leansdr::cf32>* DATVDemod::p_autonotched private
Definition at line 307 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), InitDATVFramework(), and InitDATVS2Framework().
p_bbframes
void* DATVDemod::p_bbframes private
Definition at line 341 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_bytes
leansdr::pipebuf<leansdr::u8>* DATVDemod::p_bytes private
Definition at line 357 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_cnr
leansdr::pipebuf<leansdr::f32>* DATVDemod::p_cnr private
Definition at line 314 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), and InitDATVFramework().
p_cstln
leansdr::pipebuf<leansdr::cf32>* DATVDemod::p_cstln private
Definition at line 336 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), and InitDATVS2Framework().
p_cstln_pls
leansdr::pipebuf<leansdr::cf32>* DATVDemod::p_cstln_pls private
Definition at line 337 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), and InitDATVS2Framework().
p_decim
leansdr::decimator<leansdr::cf32>* DATVDemod::p_decim private
Definition at line 348 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_decimated
leansdr::pipebuf<leansdr::cf32>* DATVDemod::p_decimated private
Definition at line 347 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_deframer
void* DATVDemod::p_deframer private
Definition at line 344 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_derot
leansdr::pipebuf<leansdr::cf32>* DATVDemod::p_derot private
Definition at line 310 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_descrambled
leansdr::pipebuf<leansdr::u8>* DATVDemod::p_descrambled private
Definition at line 360 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_fecframes
void* DATVDemod::p_fecframes private
Definition at line 340 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_framelock
leansdr::pipebuf<int>* DATVDemod::p_framelock private
Definition at line 338 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), and InitDATVS2Framework().
p_frames
leansdr::pipebuf<leansdr::u8>* DATVDemod::p_frames private
Definition at line 361 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_freq
leansdr::pipebuf<leansdr::f32>* DATVDemod::p_freq private
Definition at line 329 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), InitDATVFramework(), and InitDATVS2Framework().
p_lock
leansdr::pipebuf<int>* DATVDemod::p_lock private
Definition at line 367 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_locktime
leansdr::pipebuf<leansdr::u32>* DATVDemod::p_locktime private
Definition at line 368 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_mer
leansdr::pipebuf<leansdr::f32>* DATVDemod::p_mer private
Definition at line 331 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), InitDATVFramework(), and InitDATVS2Framework().
p_mpegbytes
leansdr::pipebuf<leansdr::u8>* DATVDemod::p_mpegbytes private
Definition at line 366 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_preprocessed
leansdr::pipebuf<leansdr::cf32>* DATVDemod::p_preprocessed private
Definition at line 303 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), InitDATVFramework(), and InitDATVS2Framework().
p_rawiq
leansdr::pipebuf<leansdr::cf32>* DATVDemod::p_rawiq private
Definition at line 301 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), InitDATVFramework(), and InitDATVS2Framework().
p_rawiq_writer
leansdr::pipewriter<leansdr::cf32>* DATVDemod::p_rawiq_writer private
Definition at line 302 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), feed(), InitDATVFramework(), and InitDATVS2Framework().
p_resampled
leansdr::pipebuf<leansdr::cf32>* DATVDemod::p_resampled private
Definition at line 319 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_rspackets
leansdr::pipebuf<leansdr::rspacket<leansdr::u8> >* DATVDemod::p_rspackets private
Definition at line 373 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_rtspackets
leansdr::pipebuf<leansdr::tspacket>* DATVDemod::p_rtspackets private
Definition at line 379 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_s2_deinterleaver
void* DATVDemod::p_s2_deinterleaver private
Definition at line 342 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_sampled
leansdr::pipebuf<leansdr::cf32>* DATVDemod::p_sampled private
Definition at line 332 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), and InitDATVFramework().
p_slots_dvbs2
void* DATVDemod::p_slots_dvbs2 private
Definition at line 335 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), and InitDATVS2Framework().
p_ss
leansdr::pipebuf<leansdr::f32>* DATVDemod::p_ss private
Definition at line 330 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), InitDATVFramework(), and InitDATVS2Framework().
p_symbols
leansdr::pipebuf<leansdr::eucl_ss>* DATVDemod::p_symbols private
Definition at line 328 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), and InitDATVFramework().
p_tspackets
leansdr::pipebuf<leansdr::tspacket>* DATVDemod::p_tspackets private
Definition at line 387 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_vber
leansdr::pipebuf<float>* DATVDemod::p_vber private
Definition at line 383 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_vbitcount
leansdr::pipebuf<int>* DATVDemod::p_vbitcount private
Definition at line 377 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
p_verrcount
leansdr::pipebuf<int>* DATVDemod::p_verrcount private
Definition at line 378 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r
leansdr::viterbi_sync* DATVDemod::r private
Definition at line 359 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_auto_notch
leansdr::auto_notch<leansdr::f32>* DATVDemod::r_auto_notch private
Definition at line 306 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), InitDATVFramework(), and InitDATVS2Framework().
r_cnr
leansdr::cnr_fft<leansdr::f32>* DATVDemod::r_cnr private
Definition at line 315 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), and InitDATVFramework().
r_deconv
leansdr::deconvol_sync_simple* DATVDemod::r_deconv private
Definition at line 358 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_deinter
leansdr::deinterleaver<leansdr::u8>* DATVDemod::r_deinter private
Definition at line 374 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_derand
leansdr::derandomizer* DATVDemod::r_derand private
Definition at line 388 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_derot
leansdr::rotator<leansdr::f32>* DATVDemod::r_derot private
Definition at line 311 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_etr192_descrambler
leansdr::etr192_descrambler* DATVDemod::r_etr192_descrambler private
Definition at line 363 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_fecdec
void* DATVDemod::r_fecdec private
Definition at line 343 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_ppout
leansdr::file_writer<leansdr::cf32>* DATVDemod::r_ppout private
Definition at line 351 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_resample
leansdr::fir_filter<leansdr::cf32,float>* DATVDemod::r_resample private
Definition at line 318 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_rsdec
leansdr::rs_decoder<leansdr::u8, 0>* DATVDemod::r_rsdec private
Definition at line 380 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_scope_symbols
leansdr::datvconstellation<leansdr::f32>* DATVDemod::r_scope_symbols private
Definition at line 396 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_scope_symbols_dvbs2
leansdr::datvdvbs2constellation<leansdr::f32>* DATVDemod::r_scope_symbols_dvbs2 private
Definition at line 397 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), and feed().
r_stdout
leansdr::file_writer<leansdr::tspacket>* DATVDemod::r_stdout private
Definition at line 392 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_sync
leansdr::hdlc_sync* DATVDemod::r_sync private
Definition at line 364 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_sync_mpeg
leansdr::mpeg_sync<leansdr::u8, 0>* DATVDemod::r_sync_mpeg private
Definition at line 369 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_vber
leansdr::rate_estimator<float>* DATVDemod::r_vber private
Definition at line 384 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
r_videoplayer
leansdr::datvvideoplayer<leansdr::tspacket>* DATVDemod::r_videoplayer private
Definition at line 393 of file datvdemod.h.
Referenced by CleanUpDATVFramework().
S2_MAX_SYMBOLS
unsigned long DATVDemod::S2_MAX_SYMBOLS private
Definition at line 288 of file datvdemod.h.
Referenced by InitDATVS2Framework().
sampler
leansdr::sampler_interface<leansdr::f32>* DATVDemod::sampler private
Definition at line 324 of file datvdemod.h.
Referenced by CleanUpDATVFramework(), InitDATVFramework(), and InitDATVS2Framework().
The documentation for this class was generated from the following files:
plugins/channelrx/demoddatv/datvdemod.h
plugins/channelrx/demoddatv/datvdemod.cpp