SDRAngel: LocalSourceGUI Class Reference
LocalSourceGUI Class Reference
#include <localsourcegui.h>
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static LocalSourceGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
Private Slots
void handleSourceMessages ()
void on_interpolationFactor_currentIndexChanged (int index)
void on_position_valueChanged (int value)
void on_localDevice_currentIndexChanged (int index)
void on_localDevicesRefresh_clicked (bool checked)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void tick ()
Private Member Functions
LocalSourceGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *txChannel, QWidget *parent=0)
virtual ~LocalSourceGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void applyChannelSettings ()
void displaySettings ()
void displayRateAndShift ()
void updateLocalDevices ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
void applyInterpolation ()
void applyPosition ()
Private Attributes
Ui::LocalSourceGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
LocalSourceSettings m_settings
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
double m_shiftFrequencyFactor
Channel frequency shift factor.
bool m_doApplySettings
LocalSource * m_localSource
MessageQueue m_inputMessageQueue
QTime m_time
uint32_t m_tickCount
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 42 of file localsourcegui.h.
Constructor & Destructor Documentation
LocalSourceGUI()
LocalSourceGUI::LocalSourceGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * txChannel, QWidget * parent = 0) explicit private
Definition at line 108 of file localsourcegui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), displaySettings(), getInputMessageQueue(), handleSourceMessages(), LocalSource::m_channelIdURI, m_channelMarker, m_deviceUISet, m_localSource, LocalSourceSettings::m_rgbColor, m_settings, m_time, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerTxChannelInstance(), ChannelMarker::setCenterFrequency(), LocalSourceSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSource::setMessageQueueToGUI(), ChannelMarker::setSourceOrSinkStream(), ChannelMarker::setTitle(), ChannelMarker::setVisible(), ui, updateLocalDevices(), and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                                :
         RollupWidget(parent),
         ui(new Ui::LocalSourceGUI),
         m_pluginAPI(pluginAPI),
         m_deviceUISet(deviceUISet),
         m_sampleRate(0),
         m_tickCount(0)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_localSource = (LocalSource*) channeltx;
     m_localSource->setMessageQueueToGUI(getInputMessageQueue());
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("Local Source");
     m_channelMarker.setSourceOrSinkStream(false);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     m_settings.setChannelMarker(&m_channelMarker);
     m_deviceUISet->registerTxChannelInstance(LocalSource::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     //connect(&(m_deviceUISet->m_deviceSourceAPI->getMasterTimer()), SIGNAL(timeout()), this, SLOT(tick()));
     m_time.start();
     updateLocalDevices();
     displaySettings();
     applySettings(true);
 }
~LocalSourceGUI()
LocalSourceGUI::~LocalSourceGUI () private virtual
Definition at line 148 of file localsourcegui.cpp.
References m_deviceUISet, m_localSource, DeviceUISet::removeTxChannelInstance(), and ui.
 {
     m_deviceUISet->removeTxChannelInstance(this);
     delete m_localSource; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete ui;
 }
Member Function Documentation
applyChannelSettings()
void LocalSourceGUI::applyChannelSettings () private
Definition at line 171 of file localsourcegui.cpp.
References LocalSource::MsgConfigureChannelizer::create(), BasebandSampleSource::getInputMessageQueue(), m_doApplySettings, LocalSourceSettings::m_filterChainHash, m_localSource, LocalSourceSettings::m_log2Interp, m_settings, and MessageQueue::push().
Referenced by applyPosition().
 {
     if (m_doApplySettings)
     {
         LocalSource::MsgConfigureChannelizer *msgChan = LocalSource::MsgConfigureChannelizer::create(
                 m_settings.m_log2Interp,
                 m_settings.m_filterChainHash);
         m_localSource->getInputMessageQueue()->push(msgChan);
     }
 }
applyInterpolation()
void LocalSourceGUI::applyInterpolation () private
Definition at line 308 of file localsourcegui.cpp.
References applyPosition(), i, LocalSourceSettings::m_filterChainHash, LocalSourceSettings::m_log2Interp, m_settings, and ui.
Referenced by displaySettings(), and on_interpolationFactor_currentIndexChanged().
 {
     uint32_t maxHash = 1;
     for (uint32_t i = 0; i < m_settings.m_log2Interp; i++) {
         maxHash *= 3;
     }
     ui->position->setMaximum(maxHash-1);
     ui->position->setValue(m_settings.m_filterChainHash);
     m_settings.m_filterChainHash = ui->position->value();
     applyPosition();
 }
applyPosition()
void LocalSourceGUI::applyPosition () private
Definition at line 322 of file localsourcegui.cpp.
References applyChannelSettings(), arg(), HBFilterChainConverter::convertToString(), displayRateAndShift(), LocalSourceSettings::m_filterChainHash, LocalSourceSettings::m_log2Interp, m_settings, m_shiftFrequencyFactor, and ui.
Referenced by applyInterpolation(), and on_position_valueChanged().
 {
     ui->filterChainIndex->setText(tr("%1").arg(m_settings.m_filterChainHash));
     QString s;
     m_shiftFrequencyFactor = HBFilterChainConverter::convertToString(m_settings.m_log2Interp, m_settings.m_filterChainHash, s);
     ui->filterChainText->setText(s);
     displayRateAndShift();
     applyChannelSettings();
 }
applySettings()
void LocalSourceGUI::applySettings (bool force = false) private
Definition at line 160 of file localsourcegui.cpp.
References LocalSource::MsgConfigureLocalSource::create(), ChannelMarker::getColor(), BasebandSampleSource::getInputMessageQueue(), m_channelMarker, m_doApplySettings, m_localSource, m_settings, MessageQueue::push(), and RollupWidget::setTitleColor().
Referenced by deserialize(), LocalSourceGUI(), on_localDevice_currentIndexChanged(), onMenuDialogCalled(), and resetToDefaults().
 {
     if (m_doApplySettings)
     {
         setTitleColor(m_channelMarker.getColor());
         LocalSource::MsgConfigureLocalSource* message = LocalSource::MsgConfigureLocalSource::create(m_settings, force);
         m_localSource->getInputMessageQueue()->push(message);
     }
 }
blockApplySettings()
void LocalSourceGUI::blockApplySettings (bool block) private
Definition at line 155 of file localsourcegui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
create()
LocalSourceGUI * LocalSourceGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * txChannel) static
Definition at line 29 of file localsourcegui.cpp.
References LocalSourceGUI().
Referenced by LocalSourcePlugin::createTxChannelGUI().
 {
     LocalSourceGUI* gui = new LocalSourceGUI(pluginAPI, deviceUISet, channelTx);
     return gui;
 }
deserialize()
bool LocalSourceGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 71 of file localsourcegui.cpp.
References applySettings(), LocalSourceSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void LocalSourceGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 35 of file localsourcegui.cpp.
 {
     delete this;
 }
displayRateAndShift()
void LocalSourceGUI::displayRateAndShift () private
Definition at line 201 of file localsourcegui.cpp.
References arg(), m_channelMarker, LocalSourceSettings::m_log2Interp, m_sampleRate, m_settings, m_shiftFrequencyFactor, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), and ui.
Referenced by applyPosition(), and handleMessage().
 {
     int shift = m_shiftFrequencyFactor * m_sampleRate;
     double channelSampleRate = ((double) m_sampleRate) / (1<<m_settings.m_log2Interp);
     QLocale loc;
     ui->offsetFrequencyText->setText(tr("%1 Hz").arg(loc.toString(shift)));
     ui->channelRateText->setText(tr("%1k").arg(QString::number(channelSampleRate / 1000.0, 'g', 5)));
     m_channelMarker.setCenterFrequency(shift);
     m_channelMarker.setBandwidth(channelSampleRate);
 }
displaySettings()
void LocalSourceGUI::displaySettings () private
Definition at line 182 of file localsourcegui.cpp.
References applyInterpolation(), blockApplySettings(), ChannelMarker::getTitle(), m_channelMarker, LocalSourceSettings::m_log2Interp, LocalSourceSettings::m_rgbColor, m_sampleRate, m_settings, LocalSourceSettings::m_title, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setMovable(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by deserialize(), handleMessage(), LocalSourceGUI(), and resetToDefaults().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.setBandwidth(m_sampleRate); // TODO
     m_channelMarker.setMovable(false); // do not let user move the center arbitrarily
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->interpolationFactor->setCurrentIndex(m_settings.m_log2Interp);
     applyInterpolation();
     blockApplySettings(false);
 }
enterEvent()
void LocalSourceGUI::enterEvent (QEvent *) private
Definition at line 229 of file localsourcegui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 LocalSourceGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 50 of file localsourcegui.cpp.
{
     return 0;
 }
getInputMessageQueue()
virtual MessageQueue* LocalSourceGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 56 of file localsourcegui.h.
Referenced by handleSourceMessages(), and LocalSourceGUI().
 { return &m_inputMessageQueue; }
getName()
QString LocalSourceGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 45 of file localsourcegui.cpp.
 {
     return objectName();
 }
handleMessage()
bool LocalSourceGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 83 of file localsourcegui.cpp.
References blockApplySettings(), displayRateAndShift(), displaySettings(), LocalSource::MsgSampleRateNotification::getSampleRate(), LocalSource::MsgConfigureLocalSource::getSettings(), m_sampleRate, m_settings, and Message::match().
Referenced by handleSourceMessages().
 {
     if (LocalSource::MsgSampleRateNotification::match(message))
     {
         LocalSource::MsgSampleRateNotification& notif = (LocalSource::MsgSampleRateNotification&) message;
         //m_channelMarker.setBandwidth(notif.getSampleRate());
         m_sampleRate = notif.getSampleRate();
         displayRateAndShift();
         return true;
     }
     else if (LocalSource::MsgConfigureLocalSource::match(message))
     {
         const LocalSource::MsgConfigureLocalSource& cfg = (LocalSource::MsgConfigureLocalSource&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void LocalSourceGUI::handleSourceMessages () private slot
Definition at line 234 of file localsourcegui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by LocalSourceGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void LocalSourceGUI::leaveEvent (QEvent *) private
Definition at line 224 of file localsourcegui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_interpolationFactor_currentIndexChanged
void LocalSourceGUI::on_interpolationFactor_currentIndexChanged (int index) private slot
Definition at line 284 of file localsourcegui.cpp.
References applyInterpolation(), LocalSourceSettings::m_log2Interp, and m_settings.
 {
     m_settings.m_log2Interp = index;
     applyInterpolation();
 }
on_localDevice_currentIndexChanged
void LocalSourceGUI::on_localDevice_currentIndexChanged (int index) private slot
Definition at line 296 of file localsourcegui.cpp.
References applySettings(), LocalSourceSettings::m_localDeviceIndex, m_settings, and ui.
 {
     m_settings.m_localDeviceIndex = ui->localDevice->itemData(index).toInt();
     applySettings();
 }
on_localDevicesRefresh_clicked
void LocalSourceGUI::on_localDevicesRefresh_clicked (bool checked) private slot
Definition at line 302 of file localsourcegui.cpp.
References updateLocalDevices().
 {
     (void) checked;
     updateLocalDevices();
 }
on_position_valueChanged
void LocalSourceGUI::on_position_valueChanged (int value) private slot
Definition at line 290 of file localsourcegui.cpp.
References applyPosition(), LocalSourceSettings::m_filterChainHash, and m_settings.
 {
     m_settings.m_filterChainHash = value;
     applyPosition();
 }
onMenuDialogCalled
void LocalSourceGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 253 of file localsourcegui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, LocalSourceSettings::m_reverseAPIAddress, LocalSourceSettings::m_reverseAPIChannelIndex, LocalSourceSettings::m_reverseAPIDeviceIndex, LocalSourceSettings::m_reverseAPIPort, LocalSourceSettings::m_rgbColor, m_settings, LocalSourceSettings::m_title, LocalSourceSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by LocalSourceGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void LocalSourceGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 247 of file localsourcegui.cpp.
Referenced by LocalSourceGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void LocalSourceGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 59 of file localsourcegui.cpp.
References applySettings(), displaySettings(), m_settings, and LocalSourceSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
serialize()
QByteArray LocalSourceGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 66 of file localsourcegui.cpp.
References m_settings, and LocalSourceSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void LocalSourceGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 54 of file localsourcegui.cpp.
 {
     (void) centerFrequency;
 }
setName()
void LocalSourceGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 40 of file localsourcegui.cpp.
 {
     setObjectName(name);
 }
tick
void LocalSourceGUI::tick () private slot
Definition at line 333 of file localsourcegui.cpp.
References m_tickCount.
 {
     if (++m_tickCount == 20) { // once per second
         m_tickCount = 0;
     }
 }
updateLocalDevices()
void LocalSourceGUI::updateLocalDevices () private
Definition at line 212 of file localsourcegui.cpp.
References arg(), LocalSource::getLocalDevices(), m_localSource, and ui.
Referenced by LocalSourceGUI(), and on_localDevicesRefresh_clicked().
 {
     std::vector<uint32_t> localDevicesIndexes;
     m_localSource->getLocalDevices(localDevicesIndexes);
     ui->localDevice->clear();
     std::vector<uint32_t>::const_iterator it = localDevicesIndexes.begin();
     for (; it != localDevicesIndexes.end(); ++it) {
         ui->localDevice->addItem(tr("%1").arg(*it), QVariant(*it));
     }
 }
Member Data Documentation
m_channelMarker
ChannelMarker LocalSourceGUI::m_channelMarker private
Definition at line 63 of file localsourcegui.h.
Referenced by applySettings(), displayRateAndShift(), displaySettings(), enterEvent(), leaveEvent(), LocalSourceGUI(), and onMenuDialogCalled().
m_deviceCenterFrequency
quint64 LocalSourceGUI::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 66 of file localsourcegui.h.
m_deviceUISet
DeviceUISet* LocalSourceGUI::m_deviceUISet private
Definition at line 62 of file localsourcegui.h.
Referenced by LocalSourceGUI(), and ~LocalSourceGUI().
m_doApplySettings
bool LocalSourceGUI::m_doApplySettings private
Definition at line 68 of file localsourcegui.h.
Referenced by applyChannelSettings(), applySettings(), and blockApplySettings().
m_inputMessageQueue
MessageQueue LocalSourceGUI::m_inputMessageQueue private
Definition at line 71 of file localsourcegui.h.
m_localSource
LocalSource* LocalSourceGUI::m_localSource private
Definition at line 70 of file localsourcegui.h.
Referenced by applyChannelSettings(), applySettings(), LocalSourceGUI(), updateLocalDevices(), and ~LocalSourceGUI().
m_pluginAPI
PluginAPI* LocalSourceGUI::m_pluginAPI private
Definition at line 61 of file localsourcegui.h.
m_sampleRate
int LocalSourceGUI::m_sampleRate private
Definition at line 65 of file localsourcegui.h.
Referenced by displayRateAndShift(), displaySettings(), and handleMessage().
m_settings
LocalSourceSettings LocalSourceGUI::m_settings private
Definition at line 64 of file localsourcegui.h.
Referenced by applyChannelSettings(), applyInterpolation(), applyPosition(), applySettings(), deserialize(), displayRateAndShift(), displaySettings(), handleMessage(), LocalSourceGUI(), on_interpolationFactor_currentIndexChanged(), on_localDevice_currentIndexChanged(), on_position_valueChanged(), onMenuDialogCalled(), resetToDefaults(), and serialize().
m_shiftFrequencyFactor
double LocalSourceGUI::m_shiftFrequencyFactor private
Channel frequency shift factor.
Definition at line 67 of file localsourcegui.h.
Referenced by applyPosition(), and displayRateAndShift().
m_tickCount
uint32_t LocalSourceGUI::m_tickCount private
Definition at line 74 of file localsourcegui.h.
Referenced by tick().
m_time
QTime LocalSourceGUI::m_time private
Definition at line 73 of file localsourcegui.h.
Referenced by LocalSourceGUI().
ui
Ui::LocalSourceGUI* LocalSourceGUI::ui private
Definition at line 60 of file localsourcegui.h.
Referenced by applyInterpolation(), applyPosition(), displayRateAndShift(), displaySettings(), LocalSourceGUI(), on_localDevice_currentIndexChanged(), updateLocalDevices(), and ~LocalSourceGUI().
The documentation for this class was generated from the following files:
plugins/channeltx/localsource/localsourcegui.h
plugins/channeltx/localsource/localsourcegui.cpp