SDRAngel: AirspyInput::MsgConfigureAirspy Class Reference
AirspyInput::MsgConfigureAirspy Class Reference
#include <airspyinput.h>
Public Member Functions
const AirspySettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureAirspy * create (const AirspySettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureAirspy (const AirspySettings &settings, bool force)
Private Attributes
AirspySettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 38 of file airspyinput.h.
Constructor & Destructor Documentation
MsgConfigureAirspy()
AirspyInput::MsgConfigureAirspy::MsgConfigureAirspy (const AirspySettings & settings, bool force) inline private
Definition at line 54 of file airspyinput.h.
Referenced by create().
                                                                        :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureAirspy* AirspyInput::MsgConfigureAirspy::create (const AirspySettings & settings, bool force) inline static
Definition at line 45 of file airspyinput.h.
References MsgConfigureAirspy().
Referenced by AirspyInput::deserialize(), AirspyInput::setCenterFrequency(), AirspyGui::updateHardware(), and AirspyInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureAirspy(settings, force);
         }
getForce()
bool AirspyInput::MsgConfigureAirspy::getForce () const inline
Definition at line 43 of file airspyinput.h.
References m_force.
Referenced by AirspyInput::handleMessage().
 { return m_force; }
getSettings()
const AirspySettings& AirspyInput::MsgConfigureAirspy::getSettings () const inline
Definition at line 42 of file airspyinput.h.
References m_settings.
Referenced by AirspyGui::handleMessage(), and AirspyInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool AirspyInput::MsgConfigureAirspy::m_force private
Definition at line 52 of file airspyinput.h.
Referenced by getForce().
m_settings
AirspySettings AirspyInput::MsgConfigureAirspy::m_settings private
Definition at line 51 of file airspyinput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/airspy/airspyinput.h