SDRAngel: SampleSourceSerializer Class Reference
SampleSourceSerializer Class Reference
#include <samplesourceserializer.h>
Classes
struct Data
Static Public Member Functions
static void writeSerializedData (const Data &data, QByteArray &serializedData)
static bool readSerializedData (const QByteArray &serializedData, Data &data)
static void setDefaults (Data &data)
static uint getSerializerVersion ()
Static Protected Attributes
static const uint m_version = 1
Detailed Description
Definition at line 24 of file samplesourceserializer.h.
Member Function Documentation
getSerializerVersion()
static uint SampleSourceSerializer::getSerializerVersion () inline static
Definition at line 44 of file samplesourceserializer.h.
 { return m_version; }
readSerializedData()
bool SampleSourceSerializer::readSerializedData (const QByteArray & serializedData, Data & data) static
Definition at line 40 of file samplesourceserializer.cpp.
References SimpleDeserializer::getVersion(), SimpleDeserializer::isValid(), SampleSourceSerializer::Data::m_bandwidth, SampleSourceSerializer::Data::m_correction, SampleSourceSerializer::Data::m_fcPosition, SampleSourceSerializer::Data::m_frequency, SampleSourceSerializer::Data::m_lnaGain, SampleSourceSerializer::Data::m_log2Decim, SampleSourceSerializer::Data::m_rate, SampleSourceSerializer::Data::m_RxGain1, SampleSourceSerializer::Data::m_RxGain2, SampleSourceSerializer::Data::m_RxGain3, m_version, SimpleDeserializer::readS32(), SimpleDeserializer::readU32(), SimpleDeserializer::readU64(), and setDefaults().
 {
     SimpleDeserializer d(serializedData);
     if (!d.isValid())
     {
         setDefaults(data);
         return false;
     }
     if (d.getVersion() == m_version)
     {
         d.readU64(1, &data.m_frequency, 0);
         d.readS32(2, &data.m_correction, 0);
         d.readS32(3, &data.m_rate, 0);
         d.readU32(4, &data.m_log2Decim, 0);
         d.readS32(5, &data.m_bandwidth, 0);
         d.readS32(6, &data.m_fcPosition, 0);
         d.readS32(7, &data.m_lnaGain, 0);
         d.readS32(8, &data.m_RxGain1, 0);
         d.readS32(9, &data.m_RxGain2, 0);
         d.readS32(10, &data.m_RxGain3, 0);
         return true;
     }
     else
     {
         setDefaults(data);
         return false;
     }
 }
setDefaults()
void SampleSourceSerializer::setDefaults (Data & data) static
Definition at line 72 of file samplesourceserializer.cpp.
References SampleSourceSerializer::Data::m_bandwidth, SampleSourceSerializer::Data::m_correction, SampleSourceSerializer::Data::m_fcPosition, SampleSourceSerializer::Data::m_frequency, SampleSourceSerializer::Data::m_lnaGain, SampleSourceSerializer::Data::m_log2Decim, SampleSourceSerializer::Data::m_rate, SampleSourceSerializer::Data::m_RxGain1, SampleSourceSerializer::Data::m_RxGain2, and SampleSourceSerializer::Data::m_RxGain3.
Referenced by readSerializedData().
 {
     data.m_frequency = 0;
     data.m_correction = 0;
     data.m_rate = 0;
     data.m_log2Decim = 0;
     data.m_bandwidth = 0;
     data.m_fcPosition = 0;
     data.m_lnaGain = 0;
     data.m_RxGain1 = 0;
     data.m_RxGain2 = 0;
     data.m_RxGain3 = 0;
 }
writeSerializedData()
void SampleSourceSerializer::writeSerializedData (const Data & data, QByteArray & serializedData) static
Definition at line 22 of file samplesourceserializer.cpp.
References SimpleSerializer::final(), SampleSourceSerializer::Data::m_bandwidth, SampleSourceSerializer::Data::m_correction, SampleSourceSerializer::Data::m_fcPosition, SampleSourceSerializer::Data::m_frequency, SampleSourceSerializer::Data::m_lnaGain, SampleSourceSerializer::Data::m_log2Decim, SampleSourceSerializer::Data::m_rate, SampleSourceSerializer::Data::m_RxGain1, SampleSourceSerializer::Data::m_RxGain2, SampleSourceSerializer::Data::m_RxGain3, SimpleSerializer::writeS32(), SimpleSerializer::writeU32(), and SimpleSerializer::writeU64().
 {
     SimpleSerializer s(1);
     s.writeU64(1, data.m_frequency);
     s.writeS32(2, data.m_correction);
     s.writeS32(3, data.m_rate);
     s.writeU32(4, data.m_log2Decim);
     s.writeS32(5, data.m_bandwidth);
     s.writeS32(6, data.m_fcPosition);
     s.writeS32(7, data.m_lnaGain);
     s.writeS32(8, data.m_RxGain1);
     s.writeS32(9, data.m_RxGain2);
     s.writeS32(10, data.m_RxGain3);
     serializedData = s.final();
 }
Member Data Documentation
m_version
const uint SampleSourceSerializer::m_version = 1 static protected
Definition at line 47 of file samplesourceserializer.h.
Referenced by readSerializedData().
The documentation for this class was generated from the following files:
sdrbase/util/samplesourceserializer.h
sdrbase/util/samplesourceserializer.cpp