SDRAngel: FileSource::MsgReportHeaderCRC Class Reference
FileSource::MsgReportHeaderCRC Class Reference
#include <filesource.h>
Public Member Functions
bool isOK () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportHeaderCRC * create (bool ok)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportHeaderCRC (bool ok)
Protected Attributes
bool m_ok
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 289 of file filesource.h.
Constructor & Destructor Documentation
MsgReportHeaderCRC()
FileSource::MsgReportHeaderCRC::MsgReportHeaderCRC (bool ok) inline protected
Definition at line 302 of file filesource.h.
References FileSource::FileSource(), and FileSource::~FileSource().
                                     :
             Message(),
             m_ok(ok)
         { }
Member Function Documentation
create()
static MsgReportHeaderCRC* FileSource::MsgReportHeaderCRC::create (bool ok) inline static
Definition at line 295 of file filesource.h.
Referenced by FileSource::openFileStream().
{
             return new MsgReportHeaderCRC(ok);
         }
isOK()
bool FileSource::MsgReportHeaderCRC::isOK () const inline
Definition at line 293 of file filesource.h.
Referenced by FileSourceGUI::handleMessage().
 { return m_ok; }
Member Data Documentation
m_ok
bool FileSource::MsgReportHeaderCRC::m_ok protected
Definition at line 300 of file filesource.h.
The documentation for this class was generated from the following file:
plugins/channeltx/filesource/filesource.h