SDRAngel: AirspyHFInput::MsgConfigureAirspyHF Class Reference
AirspyHFInput::MsgConfigureAirspyHF Class Reference
#include <airspyhfinput.h>
Public Member Functions
const AirspyHFSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureAirspyHF * create (const AirspyHFSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureAirspyHF (const AirspyHFSettings &settings, bool force)
Private Attributes
AirspyHFSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 39 of file airspyhfinput.h.
Constructor & Destructor Documentation
MsgConfigureAirspyHF()
AirspyHFInput::MsgConfigureAirspyHF::MsgConfigureAirspyHF (const AirspyHFSettings & settings, bool force) inline private
Definition at line 55 of file airspyhfinput.h.
Referenced by create().
                                                                            :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureAirspyHF* AirspyHFInput::MsgConfigureAirspyHF::create (const AirspyHFSettings & settings, bool force) inline static
Definition at line 46 of file airspyhfinput.h.
References MsgConfigureAirspyHF().
Referenced by AirspyHFInput::deserialize(), AirspyHFInput::setCenterFrequency(), AirspyHFGui::updateHardware(), and AirspyHFInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureAirspyHF(settings, force);
         }
getForce()
bool AirspyHFInput::MsgConfigureAirspyHF::getForce () const inline
Definition at line 44 of file airspyhfinput.h.
References m_force.
Referenced by AirspyHFInput::handleMessage().
 { return m_force; }
getSettings()
const AirspyHFSettings& AirspyHFInput::MsgConfigureAirspyHF::getSettings () const inline
Definition at line 43 of file airspyhfinput.h.
References m_settings.
Referenced by AirspyHFGui::handleMessage(), and AirspyHFInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool AirspyHFInput::MsgConfigureAirspyHF::m_force private
Definition at line 53 of file airspyhfinput.h.
Referenced by getForce().
m_settings
AirspyHFSettings AirspyHFInput::MsgConfigureAirspyHF::m_settings private
Definition at line 52 of file airspyhfinput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/airspyhf/airspyhfinput.h