SDRAngel: SWGSDRangel::SWGAudioOutputDevice Class Reference
SWGSDRangel::SWGAudioOutputDevice Class Reference
#include <SWGAudioOutputDevice.h>
Public Member Functions
SWGAudioOutputDevice ()
SWGAudioOutputDevice (QString *json)
virtual ~SWGAudioOutputDevice ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGAudioOutputDevice * fromJson (QString &jsonString) override
QString * getName ()
void setName (QString *name)
qint32 getIndex ()
void setIndex (qint32 index)
qint32 getSampleRate ()
void setSampleRate (qint32 sample_rate)
qint32 getIsSystemDefault ()
void setIsSystemDefault (qint32 is_system_default)
qint32 getDefaultUnregistered ()
void setDefaultUnregistered (qint32 default_unregistered)
qint32 getCopyToUdp ()
void setCopyToUdp (qint32 copy_to_udp)
qint32 getUdpUsesRtp ()
void setUdpUsesRtp (qint32 udp_uses_rtp)
qint32 getUdpChannelMode ()
void setUdpChannelMode (qint32 udp_channel_mode)
qint32 getUdpChannelCodec ()
void setUdpChannelCodec (qint32 udp_channel_codec)
qint32 getUdpDecimationFactor ()
void setUdpDecimationFactor (qint32 udp_decimation_factor)
QString * getUdpAddress ()
void setUdpAddress (QString *udp_address)
qint32 getUdpPort ()
void setUdpPort (qint32 udp_port)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * name
bool m_name_isSet
qint32 index
bool m_index_isSet
qint32 sample_rate
bool m_sample_rate_isSet
qint32 is_system_default
bool m_is_system_default_isSet
qint32 default_unregistered
bool m_default_unregistered_isSet
qint32 copy_to_udp
bool m_copy_to_udp_isSet
qint32 udp_uses_rtp
bool m_udp_uses_rtp_isSet
qint32 udp_channel_mode
bool m_udp_channel_mode_isSet
qint32 udp_channel_codec
bool m_udp_channel_codec_isSet
qint32 udp_decimation_factor
bool m_udp_decimation_factor_isSet
QString * udp_address
bool m_udp_address_isSet
qint32 udp_port
bool m_udp_port_isSet
Detailed Description
Definition at line 32 of file SWGAudioOutputDevice.h.
Constructor & Destructor Documentation
SWGAudioOutputDevice() [1/2]
SWGSDRangel::SWGAudioOutputDevice::SWGAudioOutputDevice ()
Definition at line 30 of file SWGAudioOutputDevice.cpp.
References copy_to_udp, default_unregistered, index, is_system_default, m_copy_to_udp_isSet, m_default_unregistered_isSet, m_index_isSet, m_is_system_default_isSet, m_name_isSet, m_sample_rate_isSet, m_udp_address_isSet, m_udp_channel_codec_isSet, m_udp_channel_mode_isSet, m_udp_decimation_factor_isSet, m_udp_port_isSet, m_udp_uses_rtp_isSet, name, sample_rate, udp_address, udp_channel_codec, udp_channel_mode, udp_decimation_factor, udp_port, and udp_uses_rtp.
{
     name = nullptr;
     m_name_isSet = false;
     index = 0;
     m_index_isSet = false;
     sample_rate = 0;
     m_sample_rate_isSet = false;
     is_system_default = 0;
     m_is_system_default_isSet = false;
     default_unregistered = 0;
     m_default_unregistered_isSet = false;
     copy_to_udp = 0;
     m_copy_to_udp_isSet = false;
     udp_uses_rtp = 0;
     m_udp_uses_rtp_isSet = false;
     udp_channel_mode = 0;
     m_udp_channel_mode_isSet = false;
     udp_channel_codec = 0;
     m_udp_channel_codec_isSet = false;
     udp_decimation_factor = 0;
     m_udp_decimation_factor_isSet = false;
     udp_address = nullptr;
     m_udp_address_isSet = false;
     udp_port = 0;
     m_udp_port_isSet = false;
 }
SWGAudioOutputDevice() [2/2]
SWGSDRangel::SWGAudioOutputDevice::SWGAudioOutputDevice (QString * json)
Definition at line 25 of file SWGAudioOutputDevice.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGAudioOutputDevice()
SWGSDRangel::SWGAudioOutputDevice::~SWGAudioOutputDevice () virtual
Definition at line 57 of file SWGAudioOutputDevice.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGAudioOutputDevice::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 147 of file SWGAudioOutputDevice.cpp.
References asJsonObject().
Referenced by SWGSDRangel::SWGInstanceApi::instanceAudioOutputDelete(), WebAPIRequestMapper::instanceAudioOutputParametersService(), and SWGSDRangel::SWGInstanceApi::instanceAudioOutputPatch().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGAudioOutputDevice::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 158 of file SWGAudioOutputDevice.cpp.
References copy_to_udp, default_unregistered, index, is_system_default, m_copy_to_udp_isSet, m_default_unregistered_isSet, m_index_isSet, m_is_system_default_isSet, m_sample_rate_isSet, m_udp_channel_codec_isSet, m_udp_channel_mode_isSet, m_udp_decimation_factor_isSet, m_udp_port_isSet, m_udp_uses_rtp_isSet, name, sample_rate, SWGSDRangel::toJsonValue(), udp_address, udp_channel_codec, udp_channel_mode, udp_decimation_factor, udp_port, and udp_uses_rtp.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(name != nullptr && *name != QString("")){
         toJsonValue(QString("name"), name, obj, QString("QString"));
     }
     if(m_index_isSet){
         obj->insert("index", QJsonValue(index));
     }
     if(m_sample_rate_isSet){
         obj->insert("sampleRate", QJsonValue(sample_rate));
     }
     if(m_is_system_default_isSet){
         obj->insert("isSystemDefault", QJsonValue(is_system_default));
     }
     if(m_default_unregistered_isSet){
         obj->insert("defaultUnregistered", QJsonValue(default_unregistered));
     }
     if(m_copy_to_udp_isSet){
         obj->insert("copyToUDP", QJsonValue(copy_to_udp));
     }
     if(m_udp_uses_rtp_isSet){
         obj->insert("udpUsesRTP", QJsonValue(udp_uses_rtp));
     }
     if(m_udp_channel_mode_isSet){
         obj->insert("udpChannelMode", QJsonValue(udp_channel_mode));
     }
     if(m_udp_channel_codec_isSet){
         obj->insert("udpChannelCodec", QJsonValue(udp_channel_codec));
     }
     if(m_udp_decimation_factor_isSet){
         obj->insert("udpDecimationFactor", QJsonValue(udp_decimation_factor));
     }
     if(udp_address != nullptr && *udp_address != QString("")){
         toJsonValue(QString("udpAddress"), udp_address, obj, QString("QString"));
     }
     if(m_udp_port_isSet){
         obj->insert("udpPort", QJsonValue(udp_port));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGAudioOutputDevice::cleanup ()
Definition at line 90 of file SWGAudioOutputDevice.cpp.
References name, and udp_address.
Referenced by WebAPIRequestMapper::resetAudioOutputDevice(), and ~SWGAudioOutputDevice().
{
     if(name != nullptr) {
         delete name;
     }
     if(udp_address != nullptr) {
         delete udp_address;
     }
 }
fromJson()
SWGAudioOutputDevice * SWGSDRangel::SWGAudioOutputDevice::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 110 of file SWGAudioOutputDevice.cpp.
References fromJsonObject().
Referenced by SWGAudioOutputDevice().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGAudioOutputDevice::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 119 of file SWGAudioOutputDevice.cpp.
References copy_to_udp, default_unregistered, index, is_system_default, name, sample_rate, SWGSDRangel::setValue(), udp_address, udp_channel_codec, udp_channel_mode, udp_decimation_factor, udp_port, and udp_uses_rtp.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&name, pJson["name"], "QString", "QString");
     ::SWGSDRangel::setValue(&index, pJson["index"], "qint32", "");
     ::SWGSDRangel::setValue(&sample_rate, pJson["sampleRate"], "qint32", "");
     ::SWGSDRangel::setValue(&is_system_default, pJson["isSystemDefault"], "qint32", "");
     ::SWGSDRangel::setValue(&default_unregistered, pJson["defaultUnregistered"], "qint32", "");
     ::SWGSDRangel::setValue(&copy_to_udp, pJson["copyToUDP"], "qint32", "");
     ::SWGSDRangel::setValue(&udp_uses_rtp, pJson["udpUsesRTP"], "qint32", "");
     ::SWGSDRangel::setValue(&udp_channel_mode, pJson["udpChannelMode"], "qint32", "");
     ::SWGSDRangel::setValue(&udp_channel_codec, pJson["udpChannelCodec"], "qint32", "");
     ::SWGSDRangel::setValue(&udp_decimation_factor, pJson["udpDecimationFactor"], "qint32", "");
     ::SWGSDRangel::setValue(&udp_address, pJson["udpAddress"], "QString", "QString");
     ::SWGSDRangel::setValue(&udp_port, pJson["udpPort"], "qint32", "");
 }
getCopyToUdp()
qint32 SWGSDRangel::SWGAudioOutputDevice::getCopyToUdp ()
Definition at line 251 of file SWGAudioOutputDevice.cpp.
References copy_to_udp.
Referenced by WebAPIAdapterGUI::instanceAudioOutputPatch(), and WebAPIAdapterSrv::instanceAudioOutputPatch().
{
     return copy_to_udp;
 }
getDefaultUnregistered()
qint32 SWGSDRangel::SWGAudioOutputDevice::getDefaultUnregistered ()
Definition at line 241 of file SWGAudioOutputDevice.cpp.
References default_unregistered.
{
     return default_unregistered;
 }
getIndex()
qint32 SWGSDRangel::SWGAudioOutputDevice::getIndex ()
Definition at line 211 of file SWGAudioOutputDevice.cpp.
References index.
Referenced by WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputPatch(), and WebAPIAdapterGUI::instanceAudioOutputPatch().
{
     return index;
 }
getIsSystemDefault()
qint32 SWGSDRangel::SWGAudioOutputDevice::getIsSystemDefault ()
Definition at line 231 of file SWGAudioOutputDevice.cpp.
References is_system_default.
{
     return is_system_default;
 }
getName()
QString * SWGSDRangel::SWGAudioOutputDevice::getName ()
Definition at line 201 of file SWGAudioOutputDevice.cpp.
References name.
{
     return name;
 }
getSampleRate()
qint32 SWGSDRangel::SWGAudioOutputDevice::getSampleRate ()
Definition at line 221 of file SWGAudioOutputDevice.cpp.
References sample_rate.
Referenced by WebAPIAdapterGUI::instanceAudioOutputPatch(), and WebAPIAdapterSrv::instanceAudioOutputPatch().
{
     return sample_rate;
 }
getUdpAddress()
QString * SWGSDRangel::SWGAudioOutputDevice::getUdpAddress ()
Definition at line 301 of file SWGAudioOutputDevice.cpp.
References udp_address.
Referenced by WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputPatch(), and WebAPIAdapterGUI::instanceAudioOutputPatch().
{
     return udp_address;
 }
getUdpChannelCodec()
qint32 SWGSDRangel::SWGAudioOutputDevice::getUdpChannelCodec ()
Definition at line 281 of file SWGAudioOutputDevice.cpp.
References udp_channel_codec.
Referenced by WebAPIAdapterGUI::instanceAudioOutputPatch().
{
     return udp_channel_codec;
 }
getUdpChannelMode()
qint32 SWGSDRangel::SWGAudioOutputDevice::getUdpChannelMode ()
Definition at line 271 of file SWGAudioOutputDevice.cpp.
References udp_channel_mode.
Referenced by WebAPIAdapterGUI::instanceAudioOutputPatch(), and WebAPIAdapterSrv::instanceAudioOutputPatch().
{
     return udp_channel_mode;
 }
getUdpDecimationFactor()
qint32 SWGSDRangel::SWGAudioOutputDevice::getUdpDecimationFactor ()
Definition at line 291 of file SWGAudioOutputDevice.cpp.
References udp_decimation_factor.
Referenced by WebAPIAdapterGUI::instanceAudioOutputPatch().
{
     return udp_decimation_factor;
 }
getUdpPort()
qint32 SWGSDRangel::SWGAudioOutputDevice::getUdpPort ()
Definition at line 311 of file SWGAudioOutputDevice.cpp.
References udp_port.
Referenced by WebAPIAdapterGUI::instanceAudioOutputPatch(), and WebAPIAdapterSrv::instanceAudioOutputPatch().
{
     return udp_port;
 }
getUdpUsesRtp()
qint32 SWGSDRangel::SWGAudioOutputDevice::getUdpUsesRtp ()
Definition at line 261 of file SWGAudioOutputDevice.cpp.
References udp_uses_rtp.
Referenced by WebAPIAdapterGUI::instanceAudioOutputPatch(), and WebAPIAdapterSrv::instanceAudioOutputPatch().
{
     return udp_uses_rtp;
 }
init()
void SWGSDRangel::SWGAudioOutputDevice::init ()
Definition at line 62 of file SWGAudioOutputDevice.cpp.
References copy_to_udp, default_unregistered, index, is_system_default, m_copy_to_udp_isSet, m_default_unregistered_isSet, m_index_isSet, m_is_system_default_isSet, m_name_isSet, m_sample_rate_isSet, m_udp_address_isSet, m_udp_channel_codec_isSet, m_udp_channel_mode_isSet, m_udp_decimation_factor_isSet, m_udp_port_isSet, m_udp_uses_rtp_isSet, name, sample_rate, udp_address, udp_channel_codec, udp_channel_mode, udp_decimation_factor, udp_port, and udp_uses_rtp.
Referenced by SWGAudioOutputDevice().
{
     name = new QString("");
     m_name_isSet = false;
     index = 0;
     m_index_isSet = false;
     sample_rate = 0;
     m_sample_rate_isSet = false;
     is_system_default = 0;
     m_is_system_default_isSet = false;
     default_unregistered = 0;
     m_default_unregistered_isSet = false;
     copy_to_udp = 0;
     m_copy_to_udp_isSet = false;
     udp_uses_rtp = 0;
     m_udp_uses_rtp_isSet = false;
     udp_channel_mode = 0;
     m_udp_channel_mode_isSet = false;
     udp_channel_codec = 0;
     m_udp_channel_codec_isSet = false;
     udp_decimation_factor = 0;
     m_udp_decimation_factor_isSet = false;
     udp_address = new QString("");
     m_udp_address_isSet = false;
     udp_port = 0;
     m_udp_port_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGAudioOutputDevice::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 322 of file SWGAudioOutputDevice.cpp.
References m_copy_to_udp_isSet, m_default_unregistered_isSet, m_index_isSet, m_is_system_default_isSet, m_sample_rate_isSet, m_udp_channel_codec_isSet, m_udp_channel_mode_isSet, m_udp_decimation_factor_isSet, m_udp_port_isSet, m_udp_uses_rtp_isSet, name, and udp_address.
{
     bool isObjectUpdated = false;
     do{
         if(name != nullptr && *name != QString("")){ isObjectUpdated = true; break;}
         if(m_index_isSet){ isObjectUpdated = true; break;}
         if(m_sample_rate_isSet){ isObjectUpdated = true; break;}
         if(m_is_system_default_isSet){ isObjectUpdated = true; break;}
         if(m_default_unregistered_isSet){ isObjectUpdated = true; break;}
         if(m_copy_to_udp_isSet){ isObjectUpdated = true; break;}
         if(m_udp_uses_rtp_isSet){ isObjectUpdated = true; break;}
         if(m_udp_channel_mode_isSet){ isObjectUpdated = true; break;}
         if(m_udp_channel_codec_isSet){ isObjectUpdated = true; break;}
         if(m_udp_decimation_factor_isSet){ isObjectUpdated = true; break;}
         if(udp_address != nullptr && *udp_address != QString("")){ isObjectUpdated = true; break;}
         if(m_udp_port_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setCopyToUdp()
void SWGSDRangel::SWGAudioOutputDevice::setCopyToUdp (qint32 copy_to_udp)
Definition at line 255 of file SWGAudioOutputDevice.cpp.
References copy_to_udp, and m_copy_to_udp_isSet.
Referenced by WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputPatch(), WebAPIAdapterGUI::instanceAudioOutputPatch(), and WebAPIRequestMapper::validateAudioOutputDevice().
{
     this->copy_to_udp = copy_to_udp;
     this->m_copy_to_udp_isSet = true;
 }
setDefaultUnregistered()
void SWGSDRangel::SWGAudioOutputDevice::setDefaultUnregistered (qint32 default_unregistered)
Definition at line 245 of file SWGAudioOutputDevice.cpp.
References default_unregistered, and m_default_unregistered_isSet.
{
     this->default_unregistered = default_unregistered;
     this->m_default_unregistered_isSet = true;
 }
setIndex()
void SWGSDRangel::SWGAudioOutputDevice::setIndex (qint32 index)
Definition at line 215 of file SWGAudioOutputDevice.cpp.
References index, and m_index_isSet.
Referenced by WebAPIRequestMapper::validateAudioOutputDevice().
{
     this->index = index;
     this->m_index_isSet = true;
 }
setIsSystemDefault()
void SWGSDRangel::SWGAudioOutputDevice::setIsSystemDefault (qint32 is_system_default)
Definition at line 235 of file SWGAudioOutputDevice.cpp.
References is_system_default, and m_is_system_default_isSet.
{
     this->is_system_default = is_system_default;
     this->m_is_system_default_isSet = true;
 }
setName()
void SWGSDRangel::SWGAudioOutputDevice::setName (QString * name)
Definition at line 205 of file SWGAudioOutputDevice.cpp.
References m_name_isSet, and name.
Referenced by WebAPIRequestMapper::resetAudioOutputDevice().
{
     this->name = name;
     this->m_name_isSet = true;
 }
setSampleRate()
void SWGSDRangel::SWGAudioOutputDevice::setSampleRate (qint32 sample_rate)
Definition at line 225 of file SWGAudioOutputDevice.cpp.
References m_sample_rate_isSet, and sample_rate.
Referenced by WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputPatch(), WebAPIAdapterGUI::instanceAudioOutputPatch(), and WebAPIRequestMapper::validateAudioOutputDevice().
{
     this->sample_rate = sample_rate;
     this->m_sample_rate_isSet = true;
 }
setUdpAddress()
void SWGSDRangel::SWGAudioOutputDevice::setUdpAddress (QString * udp_address)
Definition at line 305 of file SWGAudioOutputDevice.cpp.
References m_udp_address_isSet, and udp_address.
Referenced by WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputPatch(), WebAPIAdapterGUI::instanceAudioOutputPatch(), WebAPIRequestMapper::resetAudioOutputDevice(), and WebAPIRequestMapper::validateAudioOutputDevice().
{
     this->udp_address = udp_address;
     this->m_udp_address_isSet = true;
 }
setUdpChannelCodec()
void SWGSDRangel::SWGAudioOutputDevice::setUdpChannelCodec (qint32 udp_channel_codec)
Definition at line 285 of file SWGAudioOutputDevice.cpp.
References m_udp_channel_codec_isSet, and udp_channel_codec.
Referenced by WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputPatch(), WebAPIAdapterGUI::instanceAudioOutputPatch(), and WebAPIRequestMapper::validateAudioOutputDevice().
{
     this->udp_channel_codec = udp_channel_codec;
     this->m_udp_channel_codec_isSet = true;
 }
setUdpChannelMode()
void SWGSDRangel::SWGAudioOutputDevice::setUdpChannelMode (qint32 udp_channel_mode)
Definition at line 275 of file SWGAudioOutputDevice.cpp.
References m_udp_channel_mode_isSet, and udp_channel_mode.
Referenced by WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputPatch(), WebAPIAdapterGUI::instanceAudioOutputPatch(), and WebAPIRequestMapper::validateAudioOutputDevice().
{
     this->udp_channel_mode = udp_channel_mode;
     this->m_udp_channel_mode_isSet = true;
 }
setUdpDecimationFactor()
void SWGSDRangel::SWGAudioOutputDevice::setUdpDecimationFactor (qint32 udp_decimation_factor)
Definition at line 295 of file SWGAudioOutputDevice.cpp.
References m_udp_decimation_factor_isSet, and udp_decimation_factor.
Referenced by WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputPatch(), WebAPIAdapterGUI::instanceAudioOutputPatch(), and WebAPIRequestMapper::validateAudioOutputDevice().
{
     this->udp_decimation_factor = udp_decimation_factor;
     this->m_udp_decimation_factor_isSet = true;
 }
setUdpPort()
void SWGSDRangel::SWGAudioOutputDevice::setUdpPort (qint32 udp_port)
Definition at line 315 of file SWGAudioOutputDevice.cpp.
References m_udp_port_isSet, and udp_port.
Referenced by WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputPatch(), WebAPIAdapterGUI::instanceAudioOutputPatch(), and WebAPIRequestMapper::validateAudioOutputDevice().
{
     this->udp_port = udp_port;
     this->m_udp_port_isSet = true;
 }
setUdpUsesRtp()
void SWGSDRangel::SWGAudioOutputDevice::setUdpUsesRtp (qint32 udp_uses_rtp)
Definition at line 265 of file SWGAudioOutputDevice.cpp.
References m_udp_uses_rtp_isSet, and udp_uses_rtp.
Referenced by WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputPatch(), WebAPIAdapterGUI::instanceAudioOutputPatch(), and WebAPIRequestMapper::validateAudioOutputDevice().
{
     this->udp_uses_rtp = udp_uses_rtp;
     this->m_udp_uses_rtp_isSet = true;
 }
Member Data Documentation
copy_to_udp
qint32 SWGSDRangel::SWGAudioOutputDevice::copy_to_udp private
Definition at line 100 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getCopyToUdp(), init(), setCopyToUdp(), and SWGAudioOutputDevice().
default_unregistered
qint32 SWGSDRangel::SWGAudioOutputDevice::default_unregistered private
Definition at line 97 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getDefaultUnregistered(), init(), setDefaultUnregistered(), and SWGAudioOutputDevice().
index
qint32 SWGSDRangel::SWGAudioOutputDevice::index private
Definition at line 88 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getIndex(), init(), setIndex(), and SWGAudioOutputDevice().
is_system_default
qint32 SWGSDRangel::SWGAudioOutputDevice::is_system_default private
Definition at line 94 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getIsSystemDefault(), init(), setIsSystemDefault(), and SWGAudioOutputDevice().
m_copy_to_udp_isSet
bool SWGSDRangel::SWGAudioOutputDevice::m_copy_to_udp_isSet private
Definition at line 101 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setCopyToUdp(), and SWGAudioOutputDevice().
m_default_unregistered_isSet
bool SWGSDRangel::SWGAudioOutputDevice::m_default_unregistered_isSet private
Definition at line 98 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setDefaultUnregistered(), and SWGAudioOutputDevice().
m_index_isSet
bool SWGSDRangel::SWGAudioOutputDevice::m_index_isSet private
Definition at line 89 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setIndex(), and SWGAudioOutputDevice().
m_is_system_default_isSet
bool SWGSDRangel::SWGAudioOutputDevice::m_is_system_default_isSet private
Definition at line 95 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setIsSystemDefault(), and SWGAudioOutputDevice().
m_name_isSet
bool SWGSDRangel::SWGAudioOutputDevice::m_name_isSet private
Definition at line 86 of file SWGAudioOutputDevice.h.
Referenced by init(), setName(), and SWGAudioOutputDevice().
m_sample_rate_isSet
bool SWGSDRangel::SWGAudioOutputDevice::m_sample_rate_isSet private
Definition at line 92 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setSampleRate(), and SWGAudioOutputDevice().
m_udp_address_isSet
bool SWGSDRangel::SWGAudioOutputDevice::m_udp_address_isSet private
Definition at line 116 of file SWGAudioOutputDevice.h.
Referenced by init(), setUdpAddress(), and SWGAudioOutputDevice().
m_udp_channel_codec_isSet
bool SWGSDRangel::SWGAudioOutputDevice::m_udp_channel_codec_isSet private
Definition at line 110 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setUdpChannelCodec(), and SWGAudioOutputDevice().
m_udp_channel_mode_isSet
bool SWGSDRangel::SWGAudioOutputDevice::m_udp_channel_mode_isSet private
Definition at line 107 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setUdpChannelMode(), and SWGAudioOutputDevice().
m_udp_decimation_factor_isSet
bool SWGSDRangel::SWGAudioOutputDevice::m_udp_decimation_factor_isSet private
Definition at line 113 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setUdpDecimationFactor(), and SWGAudioOutputDevice().
m_udp_port_isSet
bool SWGSDRangel::SWGAudioOutputDevice::m_udp_port_isSet private
Definition at line 119 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setUdpPort(), and SWGAudioOutputDevice().
m_udp_uses_rtp_isSet
bool SWGSDRangel::SWGAudioOutputDevice::m_udp_uses_rtp_isSet private
Definition at line 104 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setUdpUsesRtp(), and SWGAudioOutputDevice().
name
QString* SWGSDRangel::SWGAudioOutputDevice::name private
Definition at line 85 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getName(), init(), isSet(), setName(), and SWGAudioOutputDevice().
sample_rate
qint32 SWGSDRangel::SWGAudioOutputDevice::sample_rate private
Definition at line 91 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getSampleRate(), init(), setSampleRate(), and SWGAudioOutputDevice().
udp_address
QString* SWGSDRangel::SWGAudioOutputDevice::udp_address private
Definition at line 115 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getUdpAddress(), init(), isSet(), setUdpAddress(), and SWGAudioOutputDevice().
udp_channel_codec
qint32 SWGSDRangel::SWGAudioOutputDevice::udp_channel_codec private
Definition at line 109 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getUdpChannelCodec(), init(), setUdpChannelCodec(), and SWGAudioOutputDevice().
udp_channel_mode
qint32 SWGSDRangel::SWGAudioOutputDevice::udp_channel_mode private
Definition at line 106 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getUdpChannelMode(), init(), setUdpChannelMode(), and SWGAudioOutputDevice().
udp_decimation_factor
qint32 SWGSDRangel::SWGAudioOutputDevice::udp_decimation_factor private
Definition at line 112 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getUdpDecimationFactor(), init(), setUdpDecimationFactor(), and SWGAudioOutputDevice().
udp_port
qint32 SWGSDRangel::SWGAudioOutputDevice::udp_port private
Definition at line 118 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getUdpPort(), init(), setUdpPort(), and SWGAudioOutputDevice().
udp_uses_rtp
qint32 SWGSDRangel::SWGAudioOutputDevice::udp_uses_rtp private
Definition at line 103 of file SWGAudioOutputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getUdpUsesRtp(), init(), setUdpUsesRtp(), and SWGAudioOutputDevice().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGAudioOutputDevice.h
swagger/sdrangel/code/qt5/client/SWGAudioOutputDevice.cpp