SDRAngel: DeviceLimeSDRShared::MsgReportDeviceInfo Class Reference
DeviceLimeSDRShared::MsgReportDeviceInfo Class Reference
#include <devicelimesdrshared.h>
Public Member Functions
float getTemperature () const
uint8_t getGPIOPins () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportDeviceInfo * create (float temperature, uint8_t gpioPins)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportDeviceInfo (float temperature, uint8_t gpioPins)
Private Attributes
float m_temperature
uint8_t m_gpioPins
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 102 of file devicelimesdrshared.h.
Constructor & Destructor Documentation
MsgReportDeviceInfo()
DeviceLimeSDRShared::MsgReportDeviceInfo::MsgReportDeviceInfo (float temperature, uint8_t gpioPins) inline private
Definition at line 118 of file devicelimesdrshared.h.
                                                                  :
             Message(),
             m_temperature(temperature),
             m_gpioPins(gpioPins)
         { }
Member Function Documentation
create()
static MsgReportDeviceInfo* DeviceLimeSDRShared::MsgReportDeviceInfo::create (float temperature, uint8_t gpioPins) inline static
Definition at line 109 of file devicelimesdrshared.h.
Referenced by LimeSDROutput::handleMessage(), and LimeSDRInput::handleMessage().
         {
             return new MsgReportDeviceInfo(temperature, gpioPins);
         }
getGPIOPins()
uint8_t DeviceLimeSDRShared::MsgReportDeviceInfo::getGPIOPins () const inline
Definition at line 107 of file devicelimesdrshared.h.
Referenced by LimeSDRInputGUI::handleMessage(), and LimeSDROutputGUI::handleMessage().
 { return m_gpioPins; }
getTemperature()
float DeviceLimeSDRShared::MsgReportDeviceInfo::getTemperature () const inline
Definition at line 106 of file devicelimesdrshared.h.
Referenced by LimeSDRInputGUI::handleMessage(), and LimeSDROutputGUI::handleMessage().
 { return m_temperature; }
Member Data Documentation
m_gpioPins
uint8_t DeviceLimeSDRShared::MsgReportDeviceInfo::m_gpioPins private
Definition at line 116 of file devicelimesdrshared.h.
m_temperature
float DeviceLimeSDRShared::MsgReportDeviceInfo::m_temperature private
Definition at line 115 of file devicelimesdrshared.h.
The documentation for this class was generated from the following file:
devices/limesdr/devicelimesdrshared.h