SDRAngel: RemoteSource Class Reference
RemoteSource Class Reference
#include <remotesource.h>
Classes
class MsgConfigureRemoteSource
class MsgQueryStreamData
class MsgReportStreamData
class MsgSampleRateNotification
Public Member Functions
RemoteSource (DeviceAPI *deviceAPI)
~RemoteSource ()
virtual void destroy ()
virtual void pull (Sample &sample)
virtual void pullAudio (int nbSamples)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
void setDataLink (const QString &dataAddress, uint16_t dataPort)
Public Member Functions inherited from BasebandSampleSource
BasebandSampleSource ()
virtual ~BasebandSampleSource ()
void feed (SampleSourceFifo *sampleFifo, int nbSamples)
SampleSourceFifo & getSampleSourceFifo ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
void setDeviceSampleSourceFifo (SampleSourceFifo *deviceSampleFifo)
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channeltx.remotesource"
static const QString m_channelId ="RemoteSource"
Private Slots
void networkManagerFinished (QNetworkReply *reply)
void handleData ()
Private Member Functions
void applySettings (const RemoteSourceSettings &settings, bool force=false)
void handleDataBlock (RemoteDataBlock *dataBlock)
void printMeta (const QString &header, RemoteMetaDataFEC *metaData)
uint32_t calculateDataReadQueueSize (int sampleRate)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const RemoteSourceSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const RemoteSourceSettings &settings, bool force)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSource * m_threadedChannelizer
UpChannelizer * m_channelizer
RemoteDataQueue m_dataQueue
RemoteSourceThread * m_sourceThread
CM256 m_cm256
CM256 * m_cm256p
bool m_running
RemoteSourceSettings m_settings
CM256::cm256_block m_cm256DescriptorBlocks [2 *RemoteNbOrginalBlocks]
CM256 decoder descriptors (block addresses and block indexes)
RemoteMetaDataFEC m_currentMeta
RemoteDataReadQueue m_dataReadQueue
uint32_t m_nbCorrectableErrors
count of correctable errors in number of blocks
uint32_t m_nbUncorrectableErrors
count of uncorrectable errors in number of blocks
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSource
void handleInputMessages ()
void handleWriteToFifo (int nbSamples)
void handleWriteToDeviceFifo (int nbSamples)
Protected Member Functions inherited from BasebandSampleSource
void handleWriteToFifo (SampleSourceFifo *sampleFifo, int nbSamples)
Protected Attributes inherited from BasebandSampleSource
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
SampleSourceFifo m_sampleFifo
Internal FIFO for multi-channel processing.
SampleSourceFifo * m_deviceSampleFifo
Reference to the device FIFO for single channel processing.
Detailed Description
Definition at line 44 of file remotesource.h.
Constructor & Destructor Documentation
RemoteSource()
RemoteSource::RemoteSource (DeviceAPI * deviceAPI)
Definition at line 54 of file remotesource.cpp.
References DeviceAPI::addChannelSource(), DeviceAPI::addChannelSourceAPI(), handleData(), RemoteMetaDataFEC::init(), m_channelId, m_channelizer, m_cm256, m_cm256p, m_currentMeta, m_dataQueue, m_deviceAPI, m_networkManager, m_threadedChannelizer, and networkManagerFinished().
Referenced by RemoteSource::MsgReportStreamData::MsgReportStreamData().
                                                :
     ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSource),
     m_deviceAPI(deviceAPI),
     m_sourceThread(0),
     m_running(false),
     m_nbCorrectableErrors(0),
     m_nbUncorrectableErrors(0)
 {
     setObjectName(m_channelId);
     connect(&m_dataQueue, SIGNAL(dataBlockEnqueued()), this, SLOT(handleData()), Qt::QueuedConnection);
     m_cm256p = m_cm256.isInitialized() ? &m_cm256 : 0;
     m_currentMeta.init();
     m_channelizer = new UpChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSource(m_channelizer, this);
     m_deviceAPI->addChannelSource(m_threadedChannelizer);
     m_deviceAPI->addChannelSourceAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~RemoteSource()
RemoteSource::~RemoteSource ()
Definition at line 77 of file remotesource.cpp.
References m_channelizer, m_deviceAPI, m_networkManager, m_threadedChannelizer, networkManagerFinished(), DeviceAPI::removeChannelSource(), and DeviceAPI::removeChannelSourceAPI().
Referenced by RemoteSource::MsgReportStreamData::MsgReportStreamData().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     m_deviceAPI->removeChannelSourceAPI(this);
     m_deviceAPI->removeChannelSource(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
 }
Member Function Documentation
applySettings()
void RemoteSource::applySettings (const RemoteSourceSettings & settings, bool force = false) private
Definition at line 211 of file remotesource.cpp.
References RemoteSourceThread::dataBind(), RemoteSourceSettings::m_dataAddress, RemoteSourceSettings::m_dataPort, RemoteSourceSettings::m_reverseAPIAddress, RemoteSourceSettings::m_reverseAPIChannelIndex, RemoteSourceSettings::m_reverseAPIDeviceIndex, RemoteSourceSettings::m_reverseAPIPort, m_settings, m_sourceThread, RemoteSourceSettings::m_useReverseAPI, and webapiReverseSendSettings().
Referenced by handleMessage().
 {
     qDebug() << "RemoteSource::applySettings:"
             << " m_dataAddress: " << settings.m_dataAddress
             << " m_dataPort: " << settings.m_dataPort
             << " force: " << force;
     bool change = false;
     QList<QString> reverseAPIKeys;
     if ((m_settings.m_dataAddress != settings.m_dataAddress) || force)
     {
         reverseAPIKeys.append("dataAddress");
         change = true;
     }
     if ((m_settings.m_dataPort != settings.m_dataPort) || force)
     {
         reverseAPIKeys.append("dataPort");
         change = true;
     }
     if (change && m_sourceThread)
     {
         reverseAPIKeys.append("sourceThread");
         m_sourceThread->dataBind(settings.m_dataAddress, settings.m_dataPort);
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
calculateDataReadQueueSize()
uint32_t RemoteSource::calculateDataReadQueueSize (int sampleRate) private
Definition at line 379 of file remotesource.cpp.
 {
     // scale for 20 blocks at 48 kS/s. Take next even number.
     uint32_t maxSize = sampleRate / 2400;
     maxSize = (maxSize % 2 == 0) ? maxSize : maxSize + 1;
     qDebug("RemoteSource::calculateDataReadQueueSize: set max queue size to %u blocks", maxSize);
     return maxSize;
 }
deserialize()
bool RemoteSource::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 193 of file remotesource.cpp.
References RemoteSource::MsgConfigureRemoteSource::create(), RemoteSourceSettings::deserialize(), BasebandSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and RemoteSourceSettings::resetToDefaults().
Referenced by getStreamCenterFrequency().
 {
     (void) data;
     if (m_settings.deserialize(data))
     {
         MsgConfigureRemoteSource *msg = MsgConfigureRemoteSource::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureRemoteSource *msg = MsgConfigureRemoteSource::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void RemoteSource::destroy () inline virtual
Implements ChannelAPI.
Definition at line 187 of file remotesource.h.
References handleMessage(), pull(), pullAudio(), start(), and stop().
 { delete this; }
getCenterFrequency()
virtual qint64 RemoteSource::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 197 of file remotesource.h.
 { return 0; }
getIdentifier()
virtual void RemoteSource::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 195 of file remotesource.h.
 { id = objectName(); }
getNbSinkStreams()
virtual int RemoteSource::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 199 of file remotesource.h.
 { return 0; }
getNbSourceStreams()
virtual int RemoteSource::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 200 of file remotesource.h.
 { return 1; }
getStreamCenterFrequency()
virtual qint64 RemoteSource::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 202 of file remotesource.h.
References deserialize(), serialize(), setDataLink(), webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return 0;
     }
getTitle()
virtual void RemoteSource::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 196 of file remotesource.h.
References RemoteSource::MsgConfigureRemoteSource::m_settings, and RemoteSourceSettings::m_title.
 { title = m_settings.m_title; }
handleData
void RemoteSource::handleData () private slot
Definition at line 356 of file remotesource.cpp.
References handleDataBlock(), m_dataQueue, m_running, and RemoteDataQueue::pop().
Referenced by RemoteSource().
 {
     RemoteDataBlock* dataBlock;
     while (m_running && ((dataBlock = m_dataQueue.pop()) != 0)) {
         handleDataBlock(dataBlock);
     }
 }
handleDataBlock()
void RemoteSource::handleDataBlock (RemoteDataBlock * dataBlock) private
Definition at line 252 of file remotesource.cpp.
References RemoteRxControlBlock::m_blockCount, and RemoteDataBlock::m_rxControlBlock.
Referenced by handleData().
 {
     (void) dataBlock;
     if (dataBlock->m_rxControlBlock.m_blockCount < RemoteNbOrginalBlocks)
     {
         qWarning("RemoteSource::handleDataBlock: incomplete data block: not processing");
     }
     else
     {
         int blockCount = 0;
         for (int blockIndex = 0; blockIndex < 256; blockIndex++)
         {
             if ((blockIndex == 0) && (dataBlock->m_rxControlBlock.m_metaRetrieved))
             {
                 m_cm256DescriptorBlocks[blockCount].Index = 0;
                 m_cm256DescriptorBlocks[blockCount].Block = (void *) &(dataBlock->m_superBlocks[0].m_protectedBlock);
                 blockCount++;
             }
             else if (dataBlock->m_superBlocks[blockIndex].m_header.m_blockIndex != 0)
             {
                 m_cm256DescriptorBlocks[blockCount].Index = dataBlock->m_superBlocks[blockIndex].m_header.m_blockIndex;
                 m_cm256DescriptorBlocks[blockCount].Block = (void *) &(dataBlock->m_superBlocks[blockIndex].m_protectedBlock);
                 blockCount++;
             }
         }
         //qDebug("RemoteSource::handleDataBlock: frame: %u blocks: %d", dataBlock.m_rxControlBlock.m_frameIndex, blockCount);
         // Need to use the CM256 recovery
         if (m_cm256p &&(dataBlock->m_rxControlBlock.m_originalCount < RemoteNbOrginalBlocks))
         {
             qDebug("RemoteSource::handleDataBlock: %d recovery blocks", dataBlock->m_rxControlBlock.m_recoveryCount);
             CM256::cm256_encoder_params paramsCM256;
             paramsCM256.BlockBytes = sizeof(RemoteProtectedBlock); // never changes
             paramsCM256.OriginalCount = RemoteNbOrginalBlocks;  // never changes
             if (m_currentMeta.m_tv_sec == 0) {
                 paramsCM256.RecoveryCount = dataBlock->m_rxControlBlock.m_recoveryCount;
             } else {
                 paramsCM256.RecoveryCount = m_currentMeta.m_nbFECBlocks;
             }
             // update counters
             if (dataBlock->m_rxControlBlock.m_originalCount < RemoteNbOrginalBlocks - paramsCM256.RecoveryCount) {
                 m_nbUncorrectableErrors += RemoteNbOrginalBlocks - paramsCM256.RecoveryCount - dataBlock->m_rxControlBlock.m_originalCount;
             } else {
                 m_nbCorrectableErrors += dataBlock->m_rxControlBlock.m_recoveryCount;
             }
             if (m_cm256.cm256_decode(paramsCM256, m_cm256DescriptorBlocks)) // CM256 decode
             {
                 qWarning() << "RemoteSource::handleDataBlock: decode CM256 error:"
                         << " m_originalCount: " << dataBlock->m_rxControlBlock.m_originalCount
                         << " m_recoveryCount: " << dataBlock->m_rxControlBlock.m_recoveryCount;
             }
             else
             {
                 for (int ir = 0; ir < dataBlock->m_rxControlBlock.m_recoveryCount; ir++) // restore missing blocks
                 {
                     int recoveryIndex = RemoteNbOrginalBlocks - dataBlock->m_rxControlBlock.m_recoveryCount + ir;
                     int blockIndex = m_cm256DescriptorBlocks[recoveryIndex].Index;
                     RemoteProtectedBlock *recoveredBlock =
                             (RemoteProtectedBlock *) m_cm256DescriptorBlocks[recoveryIndex].Block;
                     memcpy((void *) &(dataBlock->m_superBlocks[blockIndex].m_protectedBlock), recoveredBlock, sizeof(RemoteProtectedBlock));
                     if ((blockIndex == 0) && !dataBlock->m_rxControlBlock.m_metaRetrieved) {
                         dataBlock->m_rxControlBlock.m_metaRetrieved = true;
                     }
                 }
             }
         }
         // Validate block zero and retrieve its data
         if (dataBlock->m_rxControlBlock.m_metaRetrieved)
         {
             RemoteMetaDataFEC *metaData = (RemoteMetaDataFEC *) &(dataBlock->m_superBlocks[0].m_protectedBlock);
             boost::crc_32_type crc32;
             crc32.process_bytes(metaData, sizeof(RemoteMetaDataFEC)-4);
             if (crc32.checksum() == metaData->m_crc32)
             {
                 if (!(m_currentMeta == *metaData))
                 {
                     printMeta("RemoteSource::handleDataBlock", metaData);
                     if (m_currentMeta.m_sampleRate != metaData->m_sampleRate)
                     {
                         m_channelizer->configure(m_channelizer->getInputMessageQueue(), metaData->m_sampleRate, 0);
                         m_dataReadQueue.setSize(calculateDataReadQueueSize(metaData->m_sampleRate));
                     }
                 }
                 m_currentMeta = *metaData;
             }
             else
             {
                 qWarning() << "RemoteSource::handleDataBlock: recovered meta: invalid CRC32";
             }
         }
         m_dataReadQueue.push(dataBlock); // Push into R/W buffer
     }
 }
handleMessage()
bool RemoteSource::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSource.
Definition at line 135 of file remotesource.cpp.
References applySettings(), RemoteSource::MsgSampleRateNotification::create(), RemoteSource::MsgReportStreamData::create(), UpChannelizer::MsgChannelizerNotification::getBasebandSampleRate(), RemoteSource::MsgConfigureRemoteSource::getForce(), UpChannelizer::MsgChannelizerNotification::getFrequencyOffset(), UpChannelizer::MsgChannelizerNotification::getSampleRate(), RemoteSource::MsgConfigureRemoteSource::getSettings(), RemoteDataReadQueue::length(), RemoteMetaDataFEC::m_centerFrequency, m_currentMeta, m_dataReadQueue, BasebandSampleSource::m_guiMessageQueue, m_nbCorrectableErrors, RemoteMetaDataFEC::m_nbFECBlocks, RemoteMetaDataFEC::m_nbOriginalBlocks, m_nbUncorrectableErrors, RemoteMetaDataFEC::m_sampleRate, Message::match(), MessageQueue::push(), RemoteDataReadQueue::readSampleCount(), and RemoteDataReadQueue::size().
Referenced by destroy().
 {
     if (UpChannelizer::MsgChannelizerNotification::match(cmd))
     {
         UpChannelizer::MsgChannelizerNotification& notif = (UpChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "RemoteSource::handleMessage: MsgChannelizerNotification:"
                 << " basebandSampleRate: " << notif.getBasebandSampleRate()
                 << " outputSampleRate: " << notif.getSampleRate()
                 << " inputFrequencyOffset: " << notif.getFrequencyOffset();
         if (m_guiMessageQueue)
         {
             MsgSampleRateNotification *msg = MsgSampleRateNotification::create(notif.getBasebandSampleRate());
             m_guiMessageQueue->push(msg);
         }
         return true;
     }
     else if (MsgConfigureRemoteSource::match(cmd))
     {
         MsgConfigureRemoteSource& cfg = (MsgConfigureRemoteSource&) cmd;
         qDebug() << "MsgConfigureRemoteSource::handleMessage: MsgConfigureRemoteSource";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgQueryStreamData::match(cmd))
     {
         if (m_guiMessageQueue)
         {
             struct timeval tv;
             gettimeofday(&tv, 0);
             MsgReportStreamData *msg = MsgReportStreamData::create(
                     tv.tv_sec,
                     tv.tv_usec,
                     m_dataReadQueue.size(),
                     m_dataReadQueue.length(),
                     m_dataReadQueue.readSampleCount(),
                     m_nbCorrectableErrors,
                     m_nbUncorrectableErrors,
                     m_currentMeta.m_nbOriginalBlocks,
                     m_currentMeta.m_nbFECBlocks,
                     m_currentMeta.m_centerFrequency,
                     m_currentMeta.m_sampleRate);
             m_guiMessageQueue->push(msg);
         }
         return true;
     }
     return false;
 }
networkManagerFinished
void RemoteSource::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 563 of file remotesource.cpp.
Referenced by RemoteSource(), and ~RemoteSource().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "RemoteSource::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("RemoteSource::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
printMeta()
void RemoteSource::printMeta (const QString & header, RemoteMetaDataFEC * metaData) private
Definition at line 365 of file remotesource.cpp.
References RemoteMetaDataFEC::m_centerFrequency, RemoteMetaDataFEC::m_nbFECBlocks, RemoteMetaDataFEC::m_nbOriginalBlocks, RemoteMetaDataFEC::m_sampleBits, RemoteMetaDataFEC::m_sampleBytes, RemoteMetaDataFEC::m_sampleRate, RemoteMetaDataFEC::m_tv_sec, and RemoteMetaDataFEC::m_tv_usec.
 {
     qDebug().noquote() << header << ": "
             << "|" << metaData->m_centerFrequency
             << ":" << metaData->m_sampleRate
             << ":" << (int) (metaData->m_sampleBytes & 0xF)
             << ":" << (int) metaData->m_sampleBits
             << ":" << (int) metaData->m_nbOriginalBlocks
             << ":" << (int) metaData->m_nbFECBlocks
             << "|" << metaData->m_tv_sec
             << ":" << metaData->m_tv_usec
             << "|";
 }
pull()
void RemoteSource::pull (Sample & sample) virtual
Implements BasebandSampleSource.
Definition at line 87 of file remotesource.cpp.
References m_dataReadQueue, and RemoteDataReadQueue::readSample().
Referenced by destroy().
 {
     m_dataReadQueue.readSample(sample, true); // true is scale for Tx
 }
pullAudio()
void RemoteSource::pullAudio (int nbSamples) virtual
Reimplemented from BasebandSampleSource.
Definition at line 92 of file remotesource.cpp.
Referenced by destroy().
 {
     (void) nbSamples;
 }
serialize()
QByteArray RemoteSource::serialize () const virtual
Implements ChannelAPI.
Definition at line 188 of file remotesource.cpp.
References m_settings, and RemoteSourceSettings::serialize().
Referenced by getStreamCenterFrequency().
 {
     return m_settings.serialize();
 }
setDataLink()
void RemoteSource::setDataLink (const QString & dataAddress, uint16_t dataPort)
Definition at line 125 of file remotesource.cpp.
References RemoteSource::MsgConfigureRemoteSource::create(), RemoteSourceSettings::m_dataAddress, RemoteSourceSettings::m_dataPort, BasebandSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by getStreamCenterFrequency().
 {
     RemoteSourceSettings settings = m_settings;
     settings.m_dataAddress = dataAddress;
     settings.m_dataPort = dataPort;
     MsgConfigureRemoteSource *msg = MsgConfigureRemoteSource::create(settings, false);
     m_inputMessageQueue.push(msg);
 }
start()
void RemoteSource::start () virtual
Implements BasebandSampleSource.
Definition at line 97 of file remotesource.cpp.
References RemoteSourceThread::dataBind(), RemoteSourceSettings::m_dataAddress, RemoteSourceSettings::m_dataPort, m_dataQueue, m_running, m_settings, m_sourceThread, RemoteSourceThread::startStop(), and stop().
Referenced by destroy().
 {
     qDebug("RemoteSource::start");
     if (m_running) {
         stop();
     }
     m_sourceThread = new RemoteSourceThread(&m_dataQueue);
     m_sourceThread->startStop(true);
     m_sourceThread->dataBind(m_settings.m_dataAddress, m_settings.m_dataPort);
     m_running = true;
 }
stop()
void RemoteSource::stop () virtual
Implements BasebandSampleSource.
Definition at line 111 of file remotesource.cpp.
References m_running, m_sourceThread, and RemoteSourceThread::startStop().
Referenced by destroy(), and start().
 {
     qDebug("RemoteSource::stop");
     if (m_sourceThread != 0)
     {
         m_sourceThread->startStop(false);
         m_sourceThread->deleteLater();
         m_sourceThread = 0;
     }
     m_running = false;
 }
webapiFormatChannelReport()
void RemoteSource::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 499 of file remotesource.cpp.
References DeviceSampleSink::getCenterFrequency(), SWGSDRangel::SWGChannelReport::getRemoteSourceReport(), DeviceSampleSink::getSampleRate(), DeviceAPI::getSampleSink(), RemoteDataReadQueue::length(), RemoteMetaDataFEC::m_centerFrequency, m_currentMeta, m_dataReadQueue, m_deviceAPI, m_nbCorrectableErrors, RemoteMetaDataFEC::m_nbFECBlocks, RemoteMetaDataFEC::m_nbOriginalBlocks, m_nbUncorrectableErrors, RemoteMetaDataFEC::m_sampleRate, RemoteDataReadQueue::readSampleCount(), SWGSDRangel::SWGRemoteSourceReport::setCenterFreq(), SWGSDRangel::SWGRemoteSourceReport::setCorrectableErrorsCount(), SWGSDRangel::SWGRemoteSourceReport::setDeviceCenterFreq(), SWGSDRangel::SWGRemoteSourceReport::setDeviceSampleRate(), SWGSDRangel::SWGRemoteSourceReport::setNbFecBlocks(), SWGSDRangel::SWGRemoteSourceReport::setNbOriginalBlocks(), SWGSDRangel::SWGRemoteSourceReport::setQueueLength(), SWGSDRangel::SWGRemoteSourceReport::setQueueSize(), SWGSDRangel::SWGRemoteSourceReport::setSampleRate(), SWGSDRangel::SWGRemoteSourceReport::setSamplesCount(), SWGSDRangel::SWGRemoteSourceReport::setTvSec(), SWGSDRangel::SWGRemoteSourceReport::setTvUSec(), SWGSDRangel::SWGRemoteSourceReport::setUncorrectableErrorsCount(), and RemoteDataReadQueue::size().
Referenced by webapiReportGet().
 {
     struct timeval tv;
     gettimeofday(&tv, 0);
     response.getRemoteSourceReport()->setTvSec(tv.tv_sec);
     response.getRemoteSourceReport()->setTvUSec(tv.tv_usec);
     response.getRemoteSourceReport()->setQueueSize(m_dataReadQueue.size());
     response.getRemoteSourceReport()->setQueueLength(m_dataReadQueue.length());
     response.getRemoteSourceReport()->setSamplesCount(m_dataReadQueue.readSampleCount());
     response.getRemoteSourceReport()->setCorrectableErrorsCount(m_nbCorrectableErrors);
     response.getRemoteSourceReport()->setUncorrectableErrorsCount(m_nbUncorrectableErrors);
     response.getRemoteSourceReport()->setNbOriginalBlocks(m_currentMeta.m_nbOriginalBlocks);
     response.getRemoteSourceReport()->setNbFecBlocks(m_currentMeta.m_nbFECBlocks);
     response.getRemoteSourceReport()->setCenterFreq(m_currentMeta.m_centerFrequency);
     response.getRemoteSourceReport()->setSampleRate(m_currentMeta.m_sampleRate);
     response.getRemoteSourceReport()->setDeviceCenterFreq(m_deviceAPI->getSampleSink()->getCenterFrequency()/1000);
     response.getRemoteSourceReport()->setDeviceSampleRate(m_deviceAPI->getSampleSink()->getSampleRate());
 }
webapiFormatChannelSettings()
void RemoteSource::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const RemoteSourceSettings & settings) private
Definition at line 469 of file remotesource.cpp.
References SWGSDRangel::SWGRemoteSourceSettings::getDataAddress(), SWGSDRangel::SWGChannelSettings::getRemoteSourceSettings(), SWGSDRangel::SWGRemoteSourceSettings::getReverseApiAddress(), SWGSDRangel::SWGRemoteSourceSettings::getTitle(), RemoteSourceSettings::m_dataAddress, RemoteSourceSettings::m_dataPort, RemoteSourceSettings::m_reverseAPIAddress, RemoteSourceSettings::m_reverseAPIChannelIndex, RemoteSourceSettings::m_reverseAPIDeviceIndex, RemoteSourceSettings::m_reverseAPIPort, RemoteSourceSettings::m_rgbColor, RemoteSourceSettings::m_title, RemoteSourceSettings::m_useReverseAPI, SWGSDRangel::SWGRemoteSourceSettings::setDataAddress(), SWGSDRangel::SWGRemoteSourceSettings::setDataPort(), SWGSDRangel::SWGRemoteSourceSettings::setReverseApiAddress(), SWGSDRangel::SWGRemoteSourceSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGRemoteSourceSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGRemoteSourceSettings::setReverseApiPort(), SWGSDRangel::SWGRemoteSourceSettings::setRgbColor(), SWGSDRangel::SWGRemoteSourceSettings::setTitle(), and SWGSDRangel::SWGRemoteSourceSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     if (response.getRemoteSourceSettings()->getDataAddress()) {
         *response.getRemoteSourceSettings()->getDataAddress() = settings.m_dataAddress;
     } else {
         response.getRemoteSourceSettings()->setDataAddress(new QString(settings.m_dataAddress));
     }
     response.getRemoteSourceSettings()->setDataPort(settings.m_dataPort);
     response.getRemoteSourceSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getRemoteSourceSettings()->getTitle()) {
         *response.getRemoteSourceSettings()->getTitle() = settings.m_title;
     } else {
         response.getRemoteSourceSettings()->setTitle(new QString(settings.m_title));
     }
     response.getRemoteSourceSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getRemoteSourceSettings()->getReverseApiAddress()) {
         *response.getRemoteSourceSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getRemoteSourceSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getRemoteSourceSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getRemoteSourceSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getRemoteSourceSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int RemoteSource::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 458 of file remotesource.cpp.
References SWGSDRangel::SWGChannelReport::getRemoteSourceReport(), SWGSDRangel::SWGRemoteSourceReport::init(), SWGSDRangel::SWGChannelReport::setRemoteSourceReport(), and webapiFormatChannelReport().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setRemoteSourceReport(new SWGSDRangel::SWGRemoteSourceReport());
     response.getRemoteSourceReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendSettings()
void RemoteSource::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const RemoteSourceSettings & settings, bool force) private
Definition at line 519 of file remotesource.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), SWGSDRangel::SWGChannelSettings::getRemoteSourceSettings(), RemoteSourceSettings::m_dataAddress, RemoteSourceSettings::m_dataPort, m_networkManager, m_networkRequest, RemoteSourceSettings::m_reverseAPIAddress, RemoteSourceSettings::m_reverseAPIChannelIndex, RemoteSourceSettings::m_reverseAPIDeviceIndex, RemoteSourceSettings::m_reverseAPIPort, RemoteSourceSettings::m_rgbColor, RemoteSourceSettings::m_title, SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGRemoteSourceSettings::setDataAddress(), SWGSDRangel::SWGRemoteSourceSettings::setDataPort(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGChannelSettings::setRemoteSourceSettings(), SWGSDRangel::SWGRemoteSourceSettings::setRgbColor(), and SWGSDRangel::SWGRemoteSourceSettings::setTitle().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("RemoteSource"));
     swgChannelSettings->setRemoteSourceSettings(new SWGSDRangel::SWGRemoteSourceSettings());
     SWGSDRangel::SWGRemoteSourceSettings *swgRemoteSourceSettings = swgChannelSettings->getRemoteSourceSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("dataAddress") || force) {
         swgRemoteSourceSettings->setDataAddress(new QString(settings.m_dataAddress));
     }
     if (channelSettingsKeys.contains("dataPort") || force) {
         swgRemoteSourceSettings->setDataPort(settings.m_dataPort);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgRemoteSourceSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgRemoteSourceSettings->setTitle(new QString(settings.m_title));
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int RemoteSource::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 388 of file remotesource.cpp.
References SWGSDRangel::SWGChannelSettings::getRemoteSourceSettings(), SWGSDRangel::SWGRemoteSourceSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setRemoteSourceSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setRemoteSourceSettings(new SWGSDRangel::SWGRemoteSourceSettings());
     response.getRemoteSourceSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int RemoteSource::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 399 of file remotesource.cpp.
References RemoteSource::MsgConfigureRemoteSource::create(), SWGSDRangel::SWGRemoteSourceSettings::getDataAddress(), SWGSDRangel::SWGRemoteSourceSettings::getDataPort(), SWGSDRangel::SWGChannelSettings::getRemoteSourceSettings(), SWGSDRangel::SWGRemoteSourceSettings::getReverseApiAddress(), SWGSDRangel::SWGRemoteSourceSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGRemoteSourceSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGRemoteSourceSettings::getReverseApiPort(), SWGSDRangel::SWGRemoteSourceSettings::getRgbColor(), SWGSDRangel::SWGRemoteSourceSettings::getTitle(), SWGSDRangel::SWGRemoteSourceSettings::getUseReverseApi(), RemoteSourceSettings::m_dataAddress, RemoteSourceSettings::m_dataPort, BasebandSampleSource::m_guiMessageQueue, BasebandSampleSource::m_inputMessageQueue, RemoteSourceSettings::m_reverseAPIAddress, RemoteSourceSettings::m_reverseAPIChannelIndex, RemoteSourceSettings::m_reverseAPIDeviceIndex, RemoteSourceSettings::m_reverseAPIPort, RemoteSourceSettings::m_rgbColor, m_settings, RemoteSourceSettings::m_title, RemoteSourceSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     RemoteSourceSettings settings = m_settings;
     if (channelSettingsKeys.contains("dataAddress")) {
         settings.m_dataAddress = *response.getRemoteSourceSettings()->getDataAddress();
     }
     if (channelSettingsKeys.contains("dataPort"))
     {
         int dataPort = response.getRemoteSourceSettings()->getDataPort();
         if ((dataPort < 1024) || (dataPort > 65535)) {
             settings.m_dataPort = 9090;
         } else {
             settings.m_dataPort = dataPort;
         }
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getRemoteSourceSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getRemoteSourceSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getRemoteSourceSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getRemoteSourceSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getRemoteSourceSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getRemoteSourceSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getRemoteSourceSettings()->getReverseApiChannelIndex();
     }
     MsgConfigureRemoteSource *msg = MsgConfigureRemoteSource::create(settings, force);
     m_inputMessageQueue.push(msg);
     qDebug("RemoteSource::webapiSettingsPutPatch: forward to GUI: %p", m_guiMessageQueue);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureRemoteSource *msgToGUI = MsgConfigureRemoteSource::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_channelId
const QString RemoteSource::m_channelId ="RemoteSource" static
Definition at line 229 of file remotesource.h.
Referenced by RemoteSourcePlugin::initPlugin(), and RemoteSource().
m_channelIdURI
const QString RemoteSource::m_channelIdURI = "sdrangel.channeltx.remotesource" static
Definition at line 228 of file remotesource.h.
Referenced by RemoteSourcePlugin::initPlugin(), and RemoteSourceGUI::RemoteSourceGUI().
m_channelizer
UpChannelizer* RemoteSource::m_channelizer private
Definition at line 234 of file remotesource.h.
Referenced by RemoteSource(), and ~RemoteSource().
m_cm256
CM256 RemoteSource::m_cm256 private
Definition at line 237 of file remotesource.h.
Referenced by RemoteSource().
m_cm256DescriptorBlocks
CM256::cm256_block RemoteSource::m_cm256DescriptorBlocks[2 *RemoteNbOrginalBlocks] private
CM256 decoder descriptors (block addresses and block indexes)
Definition at line 243 of file remotesource.h.
m_cm256p
CM256* RemoteSource::m_cm256p private
Definition at line 238 of file remotesource.h.
Referenced by RemoteSource().
m_currentMeta
RemoteMetaDataFEC RemoteSource::m_currentMeta private
Definition at line 244 of file remotesource.h.
Referenced by handleMessage(), RemoteSource(), and webapiFormatChannelReport().
m_dataQueue
RemoteDataQueue RemoteSource::m_dataQueue private
Definition at line 235 of file remotesource.h.
Referenced by handleData(), RemoteSource(), and start().
m_dataReadQueue
RemoteDataReadQueue RemoteSource::m_dataReadQueue private
Definition at line 246 of file remotesource.h.
Referenced by handleMessage(), pull(), and webapiFormatChannelReport().
m_deviceAPI
DeviceAPI* RemoteSource::m_deviceAPI private
Definition at line 232 of file remotesource.h.
Referenced by RemoteSource(), webapiFormatChannelReport(), and ~RemoteSource().
m_nbCorrectableErrors
uint32_t RemoteSource::m_nbCorrectableErrors private
count of correctable errors in number of blocks
Definition at line 248 of file remotesource.h.
Referenced by RemoteSource::MsgReportStreamData::get_nbCorrectableErrors(), handleMessage(), and webapiFormatChannelReport().
m_nbUncorrectableErrors
uint32_t RemoteSource::m_nbUncorrectableErrors private
count of uncorrectable errors in number of blocks
Definition at line 249 of file remotesource.h.
Referenced by RemoteSource::MsgReportStreamData::get_nbUncorrectableErrors(), handleMessage(), and webapiFormatChannelReport().
m_networkManager
QNetworkAccessManager* RemoteSource::m_networkManager private
Definition at line 251 of file remotesource.h.
Referenced by RemoteSource(), webapiReverseSendSettings(), and ~RemoteSource().
m_networkRequest
QNetworkRequest RemoteSource::m_networkRequest private
Definition at line 252 of file remotesource.h.
Referenced by webapiReverseSendSettings().
m_running
bool RemoteSource::m_running private
Definition at line 239 of file remotesource.h.
Referenced by handleData(), start(), and stop().
m_settings
RemoteSourceSettings RemoteSource::m_settings private
Definition at line 241 of file remotesource.h.
Referenced by applySettings(), deserialize(), serialize(), setDataLink(), start(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_sourceThread
RemoteSourceThread* RemoteSource::m_sourceThread private
Definition at line 236 of file remotesource.h.
Referenced by applySettings(), start(), and stop().
m_threadedChannelizer
ThreadedBasebandSampleSource* RemoteSource::m_threadedChannelizer private
Definition at line 233 of file remotesource.h.
Referenced by RemoteSource(), and ~RemoteSource().
The documentation for this class was generated from the following files:
plugins/channeltx/remotesource/remotesource.h
plugins/channeltx/remotesource/remotesource.cpp