SDRAngel: sfft Class Reference
sfft Class Reference
#include <fftfilt.h>
Classes
struct vrot_bins_pair
Public Types
typedef std::complex< float > cmplx
Public Member Functions
sfft (int len)
~sfft ()
void run (const cmplx &input)
void fetch (float *result)
Private Attributes
int fftlen
int first
int last
int ptr
vrot_bins_pair * vrot_bins
cmplx * delay
float k2
Detailed Description
Definition at line 96 of file fftfilt.h.
Member Typedef Documentation
cmplx
typedef std::complex<float> sfft::cmplx
Definition at line 99 of file fftfilt.h.
Constructor & Destructor Documentation
sfft()
sfft::sfft (int len)
Definition at line 410 of file fftfilt.cpp.
References cos(), i, K1, M_PI, and sin().
 {
     vrot_bins = new vrot_bins_pair[len];
     delay  = new cmplx[len];
     fftlen = len;
     first = 0;
     last = len - 1;
     ptr = 0;
     double phi = 0.0, tau = 2.0 * M_PI/ len;
     k2 = 1.0;
     for (int i = 0; i < len; i++) {
         vrot_bins[i].vrot = cmplx( K1 * cos (phi), K1 * sin (phi) );
         phi += tau;
         delay[i] = vrot_bins[i].bins = 0.0;
         k2 *= K1;
     }
 }
~sfft()
sfft::~sfft ()
Definition at line 428 of file fftfilt.cpp.
 {
     delete [] vrot_bins;
     delete [] delay;
 }
Member Function Documentation
fetch()
void sfft::fetch (float * result)
Definition at line 451 of file fftfilt.cpp.
Referenced by LoRaDemod::detect().
 {
     for (vrot_bins_pair *itr = vrot_bins, *end = vrot_bins + last;  itr != end; ++itr, ++result)
         *result = itr->bins.real() * itr->bins.real()
                         + itr->bins.imag() * itr->bins.imag();
 }
run()
void sfft::run (const cmplx & input)
Definition at line 437 of file fftfilt.cpp.
Referenced by LoRaDemod::detect().
 {
     cmplx & de = delay[ptr];
     const cmplx z( input.real() - k2 * de.real(), input.imag() - k2 * de.imag());
     de = input;
     if (++ptr >= fftlen)
         ptr = 0;
     for (vrot_bins_pair *itr = vrot_bins + first, *end = vrot_bins + last; itr != end ; ++itr)
         itr->bins = (itr->bins + z) * itr->vrot;
 }
Member Data Documentation
delay
cmplx* sfft::delay private
Definition at line 111 of file fftfilt.h.
fftlen
int sfft::fftlen private
Definition at line 105 of file fftfilt.h.
first
int sfft::first private
Definition at line 106 of file fftfilt.h.
k2
float sfft::k2 private
Definition at line 112 of file fftfilt.h.
last
int sfft::last private
Definition at line 107 of file fftfilt.h.
ptr
int sfft::ptr private
Definition at line 108 of file fftfilt.h.
vrot_bins
vrot_bins_pair* sfft::vrot_bins private
Definition at line 109 of file fftfilt.h.
The documentation for this class was generated from the following files:
sdrbase/dsp/fftfilt.h
sdrbase/dsp/fftfilt.cpp