SDRAngel: FCDProGui Class Reference
FCDProGui Class Reference
#include <fcdprogui.h>
Public Member Functions
FCDProGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~FCDProGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_centerFrequency_changed (quint64 value)
void on_ppm_valueChanged (int value)
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_lnaGain_currentIndexChanged (int index)
void on_rfFilter_currentIndexChanged (int index)
void on_lnaEnhance_currentIndexChanged (int index)
void on_band_currentIndexChanged (int index)
void on_mixGain_currentIndexChanged (int index)
void on_mixFilter_currentIndexChanged (int index)
void on_bias_currentIndexChanged (int index)
void on_mode_currentIndexChanged (int index)
void on_gain1_currentIndexChanged (int index)
void on_rcFilter_currentIndexChanged (int index)
void on_gain2_currentIndexChanged (int index)
void on_gain3_currentIndexChanged (int index)
void on_gain4_currentIndexChanged (int index)
void on_ifFilter_currentIndexChanged (int index)
void on_gain5_currentIndexChanged (int index)
void on_gain6_currentIndexChanged (int index)
void on_decim_currentIndexChanged (int index)
void on_fcPos_currentIndexChanged (int index)
void on_setDefaults_clicked (bool checked)
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void on_transverter_clicked ()
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void updateFrequencyLimits ()
Private Attributes
Ui::FCDProGui * ui
DeviceUISet * m_deviceUISet
bool m_doApplySettings
bool m_forceSettings
FCDProSettings m_settings
QTimer m_updateTimer
QTimer m_statusTimer
std::vector< int > m_gains
DeviceSampleSource * m_sampleSource
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 36 of file fcdprogui.h.
Constructor & Destructor Documentation
FCDProGui()
FCDProGui::FCDProGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 34 of file fcdprogui.cpp.
References FCDProConstants::bands, FCDProConstants::bias_currents, displaySettings(), FCDProConstants::fcdpro_band_nb_values(), FCDProConstants::fcdpro_bias_current_nb_values(), FCDProConstants::fcdpro_if_filter_nb_values(), FCDProConstants::fcdpro_if_gain1_nb_values(), FCDProConstants::fcdpro_if_gain2_nb_values(), FCDProConstants::fcdpro_if_gain3_nb_values(), FCDProConstants::fcdpro_if_gain4_nb_values(), FCDProConstants::fcdpro_if_gain5_nb_values(), FCDProConstants::fcdpro_if_gain6_nb_values(), FCDProConstants::fcdpro_if_gain_mode_nb_values(), FCDProConstants::fcdpro_if_rc_filter_nb_values(), FCDProConstants::fcdpro_lna_enhance_nb_values(), FCDProConstants::fcdpro_lna_gain_nb_values(), FCDProConstants::fcdpro_mixer_filter_nb_values(), FCDProConstants::fcdpro_mixer_gain_nb_values(), FCDProConstants::fcdpro_rf_filter_nb_values(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, handleInputMessages(), i, FCDProConstants::if_filters, FCDProConstants::if_gain_modes, FCDProConstants::if_gains1, FCDProConstants::if_gains2, FCDProConstants::if_gains3, FCDProConstants::if_gains4, FCDProConstants::if_gains5, FCDProConstants::if_gains6, FCDProConstants::if_rc_filters, FCDProConstants::lna_enhances, FCDProConstants::lna_gains, DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_sampleSource, m_statusTimer, m_updateTimer, FCDProConstants::mixer_filters, FCDProConstants::mixer_gains, openDeviceSettingsDialog(), FCDProConstants::rf_filters, DeviceSampleSource::setMessageQueueToGUI(), ui, updateFrequencyLimits(), updateHardware(), and updateStatus().
                                                               :
     QWidget(parent),
     ui(new Ui::FCDProGui),
     m_deviceUISet(deviceUISet),
     m_forceSettings(true),
     m_settings(),
     m_sampleSource(NULL),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     m_sampleSource = (FCDProInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     updateFrequencyLimits();
     ui->lnaGain->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_lna_gain_nb_values(); i++)
     {
         ui->lnaGain->addItem(QString(FCDProConstants::lna_gains[i].label.c_str()), i);
     }
     ui->rfFilter->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_rf_filter_nb_values(); i++)
     {
         ui->rfFilter->addItem(QString(FCDProConstants::rf_filters[i].label.c_str()), i);
     }
     ui->lnaEnhance->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_lna_enhance_nb_values(); i++)
     {
         ui->lnaEnhance->addItem(QString(FCDProConstants::lna_enhances[i].label.c_str()), i);
     }
     ui->band->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_band_nb_values(); i++)
     {
         ui->band->addItem(QString(FCDProConstants::bands[i].label.c_str()), i);
     }
     ui->mixGain->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_mixer_gain_nb_values(); i++)
     {
         ui->mixGain->addItem(QString(FCDProConstants::mixer_gains[i].label.c_str()), i);
     }
     ui->mixFilter->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_mixer_filter_nb_values(); i++)
     {
         ui->mixFilter->addItem(QString(FCDProConstants::mixer_filters[i].label.c_str()), i);
     }
     ui->bias->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_bias_current_nb_values(); i++)
     {
         ui->bias->addItem(QString(FCDProConstants::bias_currents[i].label.c_str()), i);
     }
     ui->mode->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_if_gain_mode_nb_values(); i++)
     {
         ui->mode->addItem(QString(FCDProConstants::if_gain_modes[i].label.c_str()), i);
     }
     ui->gain1->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_if_gain1_nb_values(); i++)
     {
         ui->gain1->addItem(QString(FCDProConstants::if_gains1[i].label.c_str()), i);
     }
     ui->rcFilter->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_if_rc_filter_nb_values(); i++)
     {
         ui->rcFilter->addItem(QString(FCDProConstants::if_rc_filters[i].label.c_str()), i);
     }
     ui->gain2->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_if_gain2_nb_values(); i++)
     {
         ui->gain2->addItem(QString(FCDProConstants::if_gains2[i].label.c_str()), i);
     }
     ui->gain3->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_if_gain3_nb_values(); i++)
     {
         ui->gain3->addItem(QString(FCDProConstants::if_gains3[i].label.c_str()), i);
     }
     ui->gain4->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_if_gain4_nb_values(); i++)
     {
         ui->gain4->addItem(QString(FCDProConstants::if_gains4[i].label.c_str()), i);
     }
     ui->ifFilter->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_if_filter_nb_values(); i++)
     {
         ui->ifFilter->addItem(QString(FCDProConstants::if_filters[i].label.c_str()), i);
     }
     ui->gain5->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_if_gain5_nb_values(); i++)
     {
         ui->gain5->addItem(QString(FCDProConstants::if_gains5[i].label.c_str()), i);
     }
     ui->gain6->clear();
     for (int i = 0; i < FCDProConstants::fcdpro_if_gain6_nb_values(); i++)
     {
         ui->gain6->addItem(QString(FCDProConstants::if_gains6[i].label.c_str()), i);
     }
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
 }
~FCDProGui()
FCDProGui::~FCDProGui () virtual
Definition at line 158 of file fcdprogui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void FCDProGui::blockApplySettings (bool block) inline private
Definition at line 71 of file fcdprogui.h.
Referenced by handleMessage().
 { m_doApplySettings = !block; }
deserialize()
bool FCDProGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 202 of file fcdprogui.cpp.
References FCDProSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void FCDProGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 163 of file fcdprogui.cpp.
 {
     delete this;
 }
displaySettings()
void FCDProGui::displaySettings () private
Definition at line 294 of file fcdprogui.cpp.
References arg(), FCDProSettings::m_bandIndex, FCDProSettings::m_biasCurrentIndex, FCDProSettings::m_centerFrequency, FCDProSettings::m_dcBlock, FCDProSettings::m_fcPos, FCDProSettings::m_gain1Index, FCDProSettings::m_gain2Index, FCDProSettings::m_gain3Index, FCDProSettings::m_gain4Index, FCDProSettings::m_gain5Index, FCDProSettings::m_gain6Index, FCDProSettings::m_ifFilterIndex, FCDProSettings::m_iqCorrection, FCDProSettings::m_lnaEnhanceIndex, FCDProSettings::m_lnaGainIndex, FCDProSettings::m_log2Decim, FCDProSettings::m_LOppmTenths, FCDProSettings::m_mixerFilterIndex, FCDProSettings::m_mixerGainIndex, FCDProSettings::m_modeIndex, FCDProSettings::m_rcFilterIndex, FCDProSettings::m_rfFilterIndex, m_settings, FCDProSettings::m_transverterDeltaFrequency, FCDProSettings::m_transverterMode, ui, and updateFrequencyLimits().
Referenced by deserialize(), FCDProGui(), handleMessage(), on_ppm_valueChanged(), on_setDefaults_clicked(), resetToDefaults(), and setCenterFrequency().
 {
     ui->transverter->setDeltaFrequency(m_settings.m_transverterDeltaFrequency);
     ui->transverter->setDeltaFrequencyActive(m_settings.m_transverterMode);
     updateFrequencyLimits();
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     ui->ppm->setValue(m_settings.m_LOppmTenths);
     ui->ppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqCorrection);
     ui->lnaGain->setCurrentIndex(m_settings.m_lnaGainIndex);
     ui->rfFilter->setCurrentIndex(m_settings.m_rfFilterIndex);
     ui->lnaEnhance->setCurrentIndex(m_settings.m_lnaEnhanceIndex);
     ui->band->setCurrentIndex(m_settings.m_bandIndex);
     ui->mixGain->setCurrentIndex(m_settings.m_mixerGainIndex);
     ui->mixFilter->setCurrentIndex(m_settings.m_mixerFilterIndex);
     ui->bias->setCurrentIndex(m_settings.m_biasCurrentIndex);
     ui->mode->setCurrentIndex(m_settings.m_modeIndex);
     ui->gain1->setCurrentIndex(m_settings.m_gain1Index);
     ui->gain2->setCurrentIndex(m_settings.m_gain2Index);
     ui->gain3->setCurrentIndex(m_settings.m_gain3Index);
     ui->gain4->setCurrentIndex(m_settings.m_gain4Index);
     ui->gain5->setCurrentIndex(m_settings.m_gain5Index);
     ui->gain6->setCurrentIndex(m_settings.m_gain6Index);
     ui->decim->setCurrentIndex(m_settings.m_log2Decim);
     ui->fcPos->setCurrentIndex((int) m_settings.m_fcPos);
     ui->rcFilter->setCurrentIndex(m_settings.m_rcFilterIndex);
     ui->ifFilter->setCurrentIndex(m_settings.m_ifFilterIndex);
 }
getCenterFrequency()
qint64 FCDProGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 185 of file fcdprogui.cpp.
References FCDProSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* FCDProGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 52 of file fcdprogui.h.
 { return &m_inputMessageQueue; }
getName()
QString FCDProGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 173 of file fcdprogui.cpp.
 {
     return objectName();
 }
handleInputMessages
void FCDProGui::handleInputMessages () private slot
Definition at line 244 of file fcdprogui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by FCDProGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("FCDProGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("FCDProGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool FCDProGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 218 of file fcdprogui.cpp.
References blockApplySettings(), displaySettings(), FCDProInput::MsgConfigureFCDPro::getSettings(), FCDProInput::MsgStartStop::getStartStop(), m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (FCDProInput::MsgConfigureFCDPro::match(message))
     {
         const FCDProInput::MsgConfigureFCDPro& cfg = (FCDProInput::MsgConfigureFCDPro&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (FCDProInput::MsgStartStop::match(message))
     {
         FCDProInput::MsgStartStop& notif = (FCDProInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_band_currentIndexChanged
void FCDProGui::on_band_currentIndexChanged (int index) private slot
Definition at line 374 of file fcdprogui.cpp.
References FCDProSettings::m_bandIndex, m_settings, and sendSettings().
 {
     m_settings.m_bandIndex = index;
     sendSettings();
 }
on_bias_currentIndexChanged
void FCDProGui::on_bias_currentIndexChanged (int index) private slot
Definition at line 392 of file fcdprogui.cpp.
References FCDProSettings::m_biasCurrentIndex, m_settings, and sendSettings().
 {
     m_settings.m_biasCurrentIndex = index;
     sendSettings();
 }
on_centerFrequency_changed
void FCDProGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 331 of file fcdprogui.cpp.
References FCDProSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_dcOffset_toggled
void FCDProGui::on_dcOffset_toggled (bool checked) private slot
Definition at line 344 of file fcdprogui.cpp.
References FCDProSettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_decim_currentIndexChanged
void FCDProGui::on_decim_currentIndexChanged (int index) private slot
Definition at line 452 of file fcdprogui.cpp.
References FCDProSettings::m_log2Decim, m_settings, and sendSettings().
 {
     if ((index < 0) || (index > 6)) {
         return;
     }
     m_settings.m_log2Decim = index;
     sendSettings();
 }
on_fcPos_currentIndexChanged
void FCDProGui::on_fcPos_currentIndexChanged (int index) private slot
Definition at line 462 of file fcdprogui.cpp.
References FCDProSettings::FC_POS_CENTER, FCDProSettings::FC_POS_INFRA, FCDProSettings::FC_POS_SUPRA, FCDProSettings::m_fcPos, m_settings, and sendSettings().
 {
     if (index == 0) {
         m_settings.m_fcPos = FCDProSettings::FC_POS_INFRA;
         sendSettings();
     } else if (index == 1) {
         m_settings.m_fcPos = FCDProSettings::FC_POS_SUPRA;
         sendSettings();
     } else if (index == 2) {
         m_settings.m_fcPos = FCDProSettings::FC_POS_CENTER;
         sendSettings();
     }
 }
on_gain1_currentIndexChanged
void FCDProGui::on_gain1_currentIndexChanged (int index) private slot
Definition at line 404 of file fcdprogui.cpp.
References FCDProSettings::m_gain1Index, m_settings, and sendSettings().
 {
     m_settings.m_gain1Index = index;
     sendSettings();
 }
on_gain2_currentIndexChanged
void FCDProGui::on_gain2_currentIndexChanged (int index) private slot
Definition at line 416 of file fcdprogui.cpp.
References FCDProSettings::m_gain2Index, m_settings, and sendSettings().
 {
     m_settings.m_gain2Index = index;
     sendSettings();
 }
on_gain3_currentIndexChanged
void FCDProGui::on_gain3_currentIndexChanged (int index) private slot
Definition at line 422 of file fcdprogui.cpp.
References FCDProSettings::m_gain3Index, m_settings, and sendSettings().
 {
     m_settings.m_gain3Index = index;
     sendSettings();
 }
on_gain4_currentIndexChanged
void FCDProGui::on_gain4_currentIndexChanged (int index) private slot
Definition at line 428 of file fcdprogui.cpp.
References FCDProSettings::m_gain4Index, m_settings, and sendSettings().
 {
     m_settings.m_gain4Index = index;
     sendSettings();
 }
on_gain5_currentIndexChanged
void FCDProGui::on_gain5_currentIndexChanged (int index) private slot
Definition at line 440 of file fcdprogui.cpp.
References FCDProSettings::m_gain5Index, m_settings, and sendSettings().
 {
     m_settings.m_gain5Index = index;
     sendSettings();
 }
on_gain6_currentIndexChanged
void FCDProGui::on_gain6_currentIndexChanged (int index) private slot
Definition at line 446 of file fcdprogui.cpp.
References FCDProSettings::m_gain6Index, m_settings, and sendSettings().
 {
     m_settings.m_gain6Index = index;
     sendSettings();
 }
on_ifFilter_currentIndexChanged
void FCDProGui::on_ifFilter_currentIndexChanged (int index) private slot
Definition at line 434 of file fcdprogui.cpp.
References FCDProSettings::m_ifFilterIndex, m_settings, and sendSettings().
 {
     m_settings.m_ifFilterIndex = index;
     sendSettings();
 }
on_iqImbalance_toggled
void FCDProGui::on_iqImbalance_toggled (bool checked) private slot
Definition at line 350 of file fcdprogui.cpp.
References FCDProSettings::m_iqCorrection, m_settings, and sendSettings().
 {
     m_settings.m_iqCorrection = checked;
     sendSettings();
 }
on_lnaEnhance_currentIndexChanged
void FCDProGui::on_lnaEnhance_currentIndexChanged (int index) private slot
Definition at line 368 of file fcdprogui.cpp.
References FCDProSettings::m_lnaEnhanceIndex, m_settings, and sendSettings().
 {
     m_settings.m_lnaEnhanceIndex = index;
     sendSettings();
 }
on_lnaGain_currentIndexChanged
void FCDProGui::on_lnaGain_currentIndexChanged (int index) private slot
Definition at line 356 of file fcdprogui.cpp.
References FCDProSettings::m_lnaGainIndex, m_settings, and sendSettings().
 {
     m_settings.m_lnaGainIndex = index;
     sendSettings();
 }
on_mixFilter_currentIndexChanged
void FCDProGui::on_mixFilter_currentIndexChanged (int index) private slot
Definition at line 386 of file fcdprogui.cpp.
References FCDProSettings::m_mixerFilterIndex, m_settings, and sendSettings().
 {
     m_settings.m_mixerFilterIndex = index;
     sendSettings();
 }
on_mixGain_currentIndexChanged
void FCDProGui::on_mixGain_currentIndexChanged (int index) private slot
Definition at line 380 of file fcdprogui.cpp.
References FCDProSettings::m_mixerGainIndex, m_settings, and sendSettings().
 {
     m_settings.m_mixerGainIndex = index;
     sendSettings();
 }
on_mode_currentIndexChanged
void FCDProGui::on_mode_currentIndexChanged (int index) private slot
Definition at line 398 of file fcdprogui.cpp.
References FCDProSettings::m_modeIndex, m_settings, and sendSettings().
 {
     m_settings.m_modeIndex = index;
     sendSettings();
 }
on_ppm_valueChanged
void FCDProGui::on_ppm_valueChanged (int value) private slot
Definition at line 337 of file fcdprogui.cpp.
References displaySettings(), FCDProSettings::m_LOppmTenths, m_settings, and sendSettings().
 {
     m_settings.m_LOppmTenths = value;
     displaySettings();
     sendSettings();
 }
on_rcFilter_currentIndexChanged
void FCDProGui::on_rcFilter_currentIndexChanged (int index) private slot
Definition at line 410 of file fcdprogui.cpp.
References FCDProSettings::m_rcFilterIndex, m_settings, and sendSettings().
 {
     m_settings.m_rcFilterIndex = index;
     sendSettings();
 }
on_record_toggled
void FCDProGui::on_record_toggled (bool checked) private slot
Definition at line 507 of file fcdprogui.cpp.
References FCDProInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     FCDProInput::MsgFileRecord* message = FCDProInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_rfFilter_currentIndexChanged
void FCDProGui::on_rfFilter_currentIndexChanged (int index) private slot
Definition at line 362 of file fcdprogui.cpp.
References FCDProSettings::m_rfFilterIndex, m_settings, and sendSettings().
 {
     m_settings.m_rfFilterIndex = index;
     sendSettings();
 }
on_setDefaults_clicked
void FCDProGui::on_setDefaults_clicked (bool checked) private slot
Definition at line 476 of file fcdprogui.cpp.
References displaySettings(), FCDProSettings::m_biasCurrentIndex, FCDProSettings::m_gain1Index, FCDProSettings::m_gain2Index, FCDProSettings::m_gain3Index, FCDProSettings::m_gain4Index, FCDProSettings::m_gain5Index, FCDProSettings::m_gain6Index, FCDProSettings::m_ifFilterIndex, FCDProSettings::m_lnaEnhanceIndex, FCDProSettings::m_lnaGainIndex, FCDProSettings::m_mixerFilterIndex, FCDProSettings::m_mixerGainIndex, FCDProSettings::m_modeIndex, FCDProSettings::m_rcFilterIndex, m_settings, and sendSettings().
 {
     (void) checked;
     m_settings.m_lnaGainIndex = 8;        // +15 dB
     //m_settings.rfFilterIndex = 0;
     m_settings.m_mixerGainIndex = 1;      // +12 dB
     m_settings.m_mixerFilterIndex = 8;    // 1.9 MHz
     m_settings.m_gain1Index = 1;          // +6 dB
     m_settings.m_rcFilterIndex = 15;      // 1.0 MHz
     m_settings.m_gain2Index = 1;          // +3 dB
     m_settings.m_gain3Index = 1;          // +3 dB
     m_settings.m_gain4Index = 0;          // 0 dB
     m_settings.m_ifFilterIndex = 31;      // 2.15 MHz
     m_settings.m_gain5Index = 0;          // +3 dB
     m_settings.m_gain6Index = 0;          // +3 dB
     m_settings.m_lnaEnhanceIndex = 0;     // Off
     m_settings.m_biasCurrentIndex = 3;    // V/U band
     m_settings.m_modeIndex = 0;           // Linearity
     displaySettings();
     sendSettings();
 }
on_startStop_toggled
void FCDProGui::on_startStop_toggled (bool checked) private slot
Definition at line 498 of file fcdprogui.cpp.
References FCDProInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         FCDProInput::MsgStartStop *message = FCDProInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
on_transverter_clicked
void FCDProGui::on_transverter_clicked () private slot
Definition at line 519 of file fcdprogui.cpp.
References FCDProSettings::m_centerFrequency, m_settings, FCDProSettings::m_transverterDeltaFrequency, FCDProSettings::m_transverterMode, sendSettings(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("FCDProGui::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     m_settings.m_centerFrequency = ui->centerFrequency->getValueNew()*1000;
     sendSettings();
 }
openDeviceSettingsDialog
void FCDProGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 566 of file fcdprogui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), FCDProSettings::m_reverseAPIAddress, FCDProSettings::m_reverseAPIDeviceIndex, FCDProSettings::m_reverseAPIPort, m_settings, FCDProSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by FCDProGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void FCDProGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 178 of file fcdprogui.cpp.
References displaySettings(), m_settings, FCDProSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void FCDProGui::sendSettings () private
Definition at line 325 of file fcdprogui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_band_currentIndexChanged(), on_bias_currentIndexChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_gain1_currentIndexChanged(), on_gain2_currentIndexChanged(), on_gain3_currentIndexChanged(), on_gain4_currentIndexChanged(), on_gain5_currentIndexChanged(), on_gain6_currentIndexChanged(), on_ifFilter_currentIndexChanged(), on_iqImbalance_toggled(), on_lnaEnhance_currentIndexChanged(), on_lnaGain_currentIndexChanged(), on_mixFilter_currentIndexChanged(), on_mixGain_currentIndexChanged(), on_mode_currentIndexChanged(), on_ppm_valueChanged(), on_rcFilter_currentIndexChanged(), on_rfFilter_currentIndexChanged(), on_setDefaults_clicked(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray FCDProGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 197 of file fcdprogui.cpp.
References m_settings, and FCDProSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void FCDProGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 190 of file fcdprogui.cpp.
References displaySettings(), FCDProSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void FCDProGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 168 of file fcdprogui.cpp.
 {
     setObjectName(name);
 }
updateFrequencyLimits()
void FCDProGui::updateFrequencyLimits () private
Definition at line 279 of file fcdprogui.cpp.
References m_settings, FCDProSettings::m_transverterDeltaFrequency, FCDProSettings::m_transverterMode, and ui.
Referenced by displaySettings(), FCDProGui(), and on_transverter_clicked().
 {
     // values in kHz
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     qint64 minLimit = fcd_traits<Pro>::loLowLimitFreq/1000 + deltaFrequency;
     qint64 maxLimit = fcd_traits<Pro>::loHighLimitFreq/1000 + deltaFrequency;
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("FCDProGui::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void FCDProGui::updateHardware () private slot
Definition at line 558 of file fcdprogui.cpp.
References FCDProInput::MsgConfigureFCDPro::create(), DeviceSampleSource::getInputMessageQueue(), m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by FCDProGui().
 {
     FCDProInput::MsgConfigureFCDPro* message = FCDProInput::MsgConfigureFCDPro::create(m_settings, m_forceSettings);
     m_sampleSource->getInputMessageQueue()->push(message);
     m_forceSettings = false;
     m_updateTimer.stop();
 }
updateSampleRateAndFrequency()
void FCDProGui::updateSampleRateAndFrequency () private
Definition at line 272 of file fcdprogui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg((float)m_sampleRate / 1000));
 }
updateStatus
void FCDProGui::updateStatus () private slot
Definition at line 529 of file fcdprogui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by FCDProGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 FCDProGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 67 of file fcdprogui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* FCDProGui::m_deviceUISet private
Definition at line 58 of file fcdprogui.h.
Referenced by FCDProGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool FCDProGui::m_doApplySettings private
Definition at line 59 of file fcdprogui.h.
Referenced by on_startStop_toggled().
m_forceSettings
bool FCDProGui::m_forceSettings private
Definition at line 60 of file fcdprogui.h.
Referenced by deserialize(), and updateHardware().
m_gains
std::vector<int> FCDProGui::m_gains private
Definition at line 64 of file fcdprogui.h.
m_inputMessageQueue
MessageQueue FCDProGui::m_inputMessageQueue private
Definition at line 69 of file fcdprogui.h.
Referenced by FCDProGui(), and handleInputMessages().
m_lastEngineState
int FCDProGui::m_lastEngineState private
Definition at line 68 of file fcdprogui.h.
Referenced by updateStatus().
m_sampleRate
int FCDProGui::m_sampleRate private
Definition at line 66 of file fcdprogui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleSource
DeviceSampleSource* FCDProGui::m_sampleSource private
Definition at line 65 of file fcdprogui.h.
Referenced by FCDProGui(), on_record_toggled(), on_startStop_toggled(), and updateHardware().
m_settings
FCDProSettings FCDProGui::m_settings private
Definition at line 61 of file fcdprogui.h.
Referenced by deserialize(), displaySettings(), getCenterFrequency(), handleMessage(), on_band_currentIndexChanged(), on_bias_currentIndexChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_gain1_currentIndexChanged(), on_gain2_currentIndexChanged(), on_gain3_currentIndexChanged(), on_gain4_currentIndexChanged(), on_gain5_currentIndexChanged(), on_gain6_currentIndexChanged(), on_ifFilter_currentIndexChanged(), on_iqImbalance_toggled(), on_lnaEnhance_currentIndexChanged(), on_lnaGain_currentIndexChanged(), on_mixFilter_currentIndexChanged(), on_mixGain_currentIndexChanged(), on_mode_currentIndexChanged(), on_ppm_valueChanged(), on_rcFilter_currentIndexChanged(), on_rfFilter_currentIndexChanged(), on_setDefaults_clicked(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), updateFrequencyLimits(), and updateHardware().
m_statusTimer
QTimer FCDProGui::m_statusTimer private
Definition at line 63 of file fcdprogui.h.
Referenced by FCDProGui().
m_updateTimer
QTimer FCDProGui::m_updateTimer private
Definition at line 62 of file fcdprogui.h.
Referenced by FCDProGui(), sendSettings(), and updateHardware().
ui
Ui::FCDProGui* FCDProGui::ui private
Definition at line 56 of file fcdprogui.h.
Referenced by displaySettings(), FCDProGui(), handleMessage(), on_record_toggled(), on_transverter_clicked(), updateFrequencyLimits(), updateSampleRateAndFrequency(), updateStatus(), and ~FCDProGui().
The documentation for this class was generated from the following files:
plugins/samplesource/fcdpro/fcdprogui.h
plugins/samplesource/fcdpro/fcdprogui.cpp