SDRAngel: DeviceBladeRF2Shared::MsgReportBuddyChange Class Reference
DeviceBladeRF2Shared::MsgReportBuddyChange Class Reference
#include <devicebladerf2shared.h>
Public Member Functions
uint64_t getCenterFrequency () const
int getLOppmTenths () const
int getFcPos () const
int getDevSampleRate () const
bool getRxElseTx () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportBuddyChange * create (uint64_t centerFrequency, int LOppmTenths, int fcPos, int devSampleRate, bool rxElseTx)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportBuddyChange (uint64_t centerFrequency, int LOppmTenths, int fcPos, int devSampleRate, bool rxElseTx)
Private Attributes
uint64_t m_centerFrequency
Center frequency.
int m_LOppmTenths
LO soft correction in tenths of ppm.
int m_fcPos
Center frequency position.
int m_devSampleRate
device/host sample rate
bool m_rxElseTx
tells which side initiated the message
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 35 of file devicebladerf2shared.h.
Constructor & Destructor Documentation
MsgReportBuddyChange()
DeviceBladeRF2Shared::MsgReportBuddyChange::MsgReportBuddyChange (uint64_t centerFrequency, int LOppmTenths, int fcPos, int devSampleRate, bool rxElseTx) inline private
Definition at line 67 of file devicebladerf2shared.h.
                                :
             Message(),
             m_centerFrequency(centerFrequency),
             m_LOppmTenths(LOppmTenths),
             m_fcPos(fcPos),
             m_devSampleRate(devSampleRate),
             m_rxElseTx(rxElseTx)
         { }
Member Function Documentation
create()
static MsgReportBuddyChange* DeviceBladeRF2Shared::MsgReportBuddyChange::create (uint64_t centerFrequency, int LOppmTenths, int fcPos, int devSampleRate, bool rxElseTx) inline static
Definition at line 45 of file devicebladerf2shared.h.
Referenced by BladeRF2Output::applySettings(), and BladeRF2Input::applySettings().
         {
             return new MsgReportBuddyChange(
                     centerFrequency,
                     LOppmTenths,
                     fcPos,
                     devSampleRate,
                     rxElseTx);
         }
getCenterFrequency()
uint64_t DeviceBladeRF2Shared::MsgReportBuddyChange::getCenterFrequency () const inline
Definition at line 39 of file devicebladerf2shared.h.
Referenced by BladeRF2Output::handleMessage(), and BladeRF2Input::handleMessage().
 { return m_centerFrequency; }
getDevSampleRate()
int DeviceBladeRF2Shared::MsgReportBuddyChange::getDevSampleRate () const inline
Definition at line 42 of file devicebladerf2shared.h.
Referenced by BladeRF2Output::handleMessage(), and BladeRF2Input::handleMessage().
 { return m_devSampleRate; }
getFcPos()
int DeviceBladeRF2Shared::MsgReportBuddyChange::getFcPos () const inline
Definition at line 41 of file devicebladerf2shared.h.
Referenced by BladeRF2Input::handleMessage().
 { return m_fcPos; }
getLOppmTenths()
int DeviceBladeRF2Shared::MsgReportBuddyChange::getLOppmTenths () const inline
Definition at line 40 of file devicebladerf2shared.h.
Referenced by BladeRF2Output::handleMessage(), and BladeRF2Input::handleMessage().
 { return m_LOppmTenths; }
getRxElseTx()
bool DeviceBladeRF2Shared::MsgReportBuddyChange::getRxElseTx () const inline
Definition at line 43 of file devicebladerf2shared.h.
Referenced by BladeRF2Output::handleMessage(), and BladeRF2Input::handleMessage().
 { return m_rxElseTx; }
Member Data Documentation
m_centerFrequency
uint64_t DeviceBladeRF2Shared::MsgReportBuddyChange::m_centerFrequency private
Center frequency.
Definition at line 61 of file devicebladerf2shared.h.
m_devSampleRate
int DeviceBladeRF2Shared::MsgReportBuddyChange::m_devSampleRate private
device/host sample rate
Definition at line 64 of file devicebladerf2shared.h.
m_fcPos
int DeviceBladeRF2Shared::MsgReportBuddyChange::m_fcPos private
Center frequency position.
Definition at line 63 of file devicebladerf2shared.h.
m_LOppmTenths
int DeviceBladeRF2Shared::MsgReportBuddyChange::m_LOppmTenths private
LO soft correction in tenths of ppm.
Definition at line 62 of file devicebladerf2shared.h.
m_rxElseTx
bool DeviceBladeRF2Shared::MsgReportBuddyChange::m_rxElseTx private
tells which side initiated the message
Definition at line 65 of file devicebladerf2shared.h.
The documentation for this class was generated from the following file:
devices/bladerf2/devicebladerf2shared.h