SDRAngel: ChannelAPI Class Reference
ChannelAPI Class Reference abstract
#include <channelapi.h>
Public Types
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Public Member Functions
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void destroy ()=0
virtual void getIdentifier (QString &id)=0
virtual void getTitle (QString &title)=0
virtual void setName (const QString &name)
virtual const QString & getName () const
virtual qint64 getCenterFrequency () const =0
Applies to a default stream.
virtual QByteArray serialize () const =0
virtual bool deserialize (const QByteArray &data)=0
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
virtual int getNbSinkStreams () const =0
virtual int getNbSourceStreams () const =0
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const =0
Private Attributes
StreamType m_streamType
QString m_name
int m_indexInDeviceSet
int m_deviceSetIndex
DeviceAPI * m_deviceAPI
uint64_t m_uid
Detailed Description
Definition at line 37 of file channelapi.h.
Member Enumeration Documentation
StreamType
enum ChannelAPI::StreamType
< This is the same enum as in PluginInterface
Enumerator
StreamSingleSink
Exposes a single sink stream (input, Rx)
StreamSingleSource
Exposes a single source stream (output, Tx)
StreamMIMO
May expose any number of sink and/or source streams.
Definition at line 39 of file channelapi.h.
     {
         StreamSingleSink,
         StreamSingleSource,
         StreamMIMO
     };
Constructor & Destructor Documentation
ChannelAPI()
ChannelAPI::ChannelAPI (const QString & name, StreamType streamType)
Definition at line 23 of file channelapi.cpp.
                                                                  :
     m_streamType(streamType),
     m_name(name),
     m_indexInDeviceSet(-1),
     m_deviceSetIndex(0),
     m_deviceAPI(0),
     m_uid(UidCalculator::getNewObjectId())
 { }
~ChannelAPI()
virtual ChannelAPI::~ChannelAPI () inline virtual
Definition at line 47 of file channelapi.h.
 {}
Member Function Documentation
deserialize()
virtual bool ChannelAPI::deserialize (const QByteArray & data) pure virtual
Implemented in ATVMod, FileSource, ATVDemod, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, ChannelAnalyzer, FreeDVDemod, BFMDemod, DATVDemod, FreqTracker, NFMDemod, SSBDemod, RemoteSink, LocalSource, LocalSink, UDPSink, DSDDemod, AMDemod, WFMDemod, UDPSource, and LoRaDemod.
Referenced by DeviceSet::loadRxChannelSettings(), and DeviceSet::loadTxChannelSettings().
destroy()
virtual void ChannelAPI::destroy () pure virtual
Implemented in ATVMod, FileSource, FreeDVMod, NFMMod, SSBMod, WFMMod, AMMod, ATVDemod, RemoteSource, DATVDemod, BFMDemod, FreqTracker, NFMDemod, FreeDVDemod, RemoteSink, ChannelAnalyzer, LocalSource, LocalSink, DSDDemod, UDPSink, AMDemod, SSBDemod, WFMDemod, UDPSource, and LoRaDemod.
getCenterFrequency()
virtual qint64 ChannelAPI::getCenterFrequency () const pure virtual
Applies to a default stream.
Implemented in ATVMod, FileSource, ATVDemod, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, ChannelAnalyzer, FreeDVDemod, BFMDemod, DATVDemod, FreqTracker, NFMDemod, SSBDemod, RemoteSink, LocalSource, LocalSink, UDPSink, DSDDemod, AMDemod, WFMDemod, UDPSource, and LoRaDemod.
Referenced by WebAPIAdapterGUI::getChannelsDetail(), WebAPIAdapterSrv::getChannelsDetail(), WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), and DeviceSet::ChannelInstanceRegistration::operator<().
getDeviceAPI()
DeviceAPI* ChannelAPI::getDeviceAPI () inline
Definition at line 91 of file channelapi.h.
Referenced by LocalSink::getLocalDevice(), and LocalSource::getLocalDevice().
 { return m_deviceAPI; }
getDeviceSetIndex()
int ChannelAPI::getDeviceSetIndex () const inline
Definition at line 89 of file channelapi.h.
Referenced by LocalSink::webapiReverseSendSettings(), LocalSource::webapiReverseSendSettings(), RemoteSink::webapiReverseSendSettings(), WFMDemod::webapiReverseSendSettings(), AMDemod::webapiReverseSendSettings(), FreqTracker::webapiReverseSendSettings(), UDPSink::webapiReverseSendSettings(), RemoteSource::webapiReverseSendSettings(), UDPSource::webapiReverseSendSettings(), NFMDemod::webapiReverseSendSettings(), DSDDemod::webapiReverseSendSettings(), BFMDemod::webapiReverseSendSettings(), WFMMod::webapiReverseSendSettings(), AMMod::webapiReverseSendSettings(), SSBDemod::webapiReverseSendSettings(), NFMMod::webapiReverseSendSettings(), FreeDVMod::webapiReverseSendSettings(), SSBMod::webapiReverseSendSettings(), FreeDVDemod::webapiReverseSendSettings(), FileSource::webapiReverseSendSettings(), and ATVMod::webapiReverseSendSettings().
 { return m_deviceSetIndex; }
getIdentifier()
virtual void ChannelAPI::getIdentifier (QString & id) pure virtual
Implemented in ATVMod, FileSource, ATVDemod, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, ChannelAnalyzer, FreeDVDemod, BFMDemod, DATVDemod, FreqTracker, NFMDemod, SSBDemod, RemoteSink, LocalSource, LocalSink, UDPSink, DSDDemod, AMDemod, WFMDemod, UDPSource, and LoRaDemod.
Referenced by WebAPIAdapterGUI::devicesetChannelReportGet(), WebAPIAdapterSrv::devicesetChannelReportGet(), WebAPIAdapterGUI::devicesetChannelSettingsGet(), WebAPIAdapterSrv::devicesetChannelSettingsGet(), WebAPIAdapterGUI::devicesetChannelSettingsPutPatch(), WebAPIAdapterSrv::devicesetChannelSettingsPutPatch(), WebAPIAdapterGUI::getChannelsDetail(), WebAPIAdapterSrv::getChannelsDetail(), WebAPIAdapterGUI::getDeviceSet(), and WebAPIAdapterSrv::getDeviceSet().
getIndexInDeviceSet()
int ChannelAPI::getIndexInDeviceSet () const inline
Definition at line 87 of file channelapi.h.
Referenced by WebAPIAdapterGUI::getChannelsDetail(), WebAPIAdapterSrv::getChannelsDetail(), WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), LocalSink::webapiReverseSendSettings(), LocalSource::webapiReverseSendSettings(), RemoteSink::webapiReverseSendSettings(), WFMDemod::webapiReverseSendSettings(), AMDemod::webapiReverseSendSettings(), FreqTracker::webapiReverseSendSettings(), UDPSink::webapiReverseSendSettings(), RemoteSource::webapiReverseSendSettings(), UDPSource::webapiReverseSendSettings(), NFMDemod::webapiReverseSendSettings(), DSDDemod::webapiReverseSendSettings(), BFMDemod::webapiReverseSendSettings(), WFMMod::webapiReverseSendSettings(), AMMod::webapiReverseSendSettings(), SSBDemod::webapiReverseSendSettings(), NFMMod::webapiReverseSendSettings(), FreeDVMod::webapiReverseSendSettings(), SSBMod::webapiReverseSendSettings(), FreeDVDemod::webapiReverseSendSettings(), FileSource::webapiReverseSendSettings(), and ATVMod::webapiReverseSendSettings().
 { return m_indexInDeviceSet; }
getName()
virtual const QString& ChannelAPI::getName () const inline virtual
Definition at line 53 of file channelapi.h.
Referenced by DeviceSet::addRxChannel(), DeviceSet::addTxChannel(), and DeviceSet::ChannelInstanceRegistration::operator<().
 { return m_name; }
getNbSinkStreams()
virtual int ChannelAPI::getNbSinkStreams () const pure virtual
Implemented in ATVMod, FileSource, ATVDemod, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, ChannelAnalyzer, DATVDemod, FreeDVDemod, BFMDemod, FreqTracker, NFMDemod, SSBDemod, RemoteSink, LocalSource, LocalSink, UDPSink, DSDDemod, AMDemod, WFMDemod, UDPSource, and LoRaDemod.
getNbSourceStreams()
virtual int ChannelAPI::getNbSourceStreams () const pure virtual
Implemented in ATVMod, FileSource, ATVDemod, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, ChannelAnalyzer, DATVDemod, FreeDVDemod, BFMDemod, FreqTracker, NFMDemod, SSBDemod, RemoteSink, LocalSource, LocalSink, UDPSink, DSDDemod, AMDemod, WFMDemod, UDPSource, and LoRaDemod.
getStreamCenterFrequency()
virtual qint64 ChannelAPI::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const pure virtual
Implemented in ATVMod, FileSource, ATVDemod, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, ChannelAnalyzer, DATVDemod, FreeDVDemod, BFMDemod, FreqTracker, NFMDemod, SSBDemod, RemoteSink, LocalSource, LocalSink, UDPSink, DSDDemod, AMDemod, WFMDemod, UDPSource, and LoRaDemod.
getStreamType()
StreamType ChannelAPI::getStreamType () const inline
Definition at line 96 of file channelapi.h.
Referenced by DeviceSet::ChannelInstanceRegistration::ChannelInstanceRegistration().
 { return m_streamType; }
getTitle()
virtual void ChannelAPI::getTitle (QString & title) pure virtual
Implemented in ATVMod, FileSource, ATVDemod, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, ChannelAnalyzer, FreeDVDemod, BFMDemod, DATVDemod, FreqTracker, NFMDemod, SSBDemod, RemoteSink, LocalSource, LocalSink, UDPSink, DSDDemod, AMDemod, WFMDemod, UDPSource, and LoRaDemod.
Referenced by WebAPIAdapterGUI::getChannelsDetail(), WebAPIAdapterSrv::getChannelsDetail(), WebAPIAdapterGUI::getDeviceSet(), and WebAPIAdapterSrv::getDeviceSet().
getUID()
uint64_t ChannelAPI::getUID () const inline
Definition at line 93 of file channelapi.h.
Referenced by WebAPIAdapterGUI::getChannelsDetail(), WebAPIAdapterSrv::getChannelsDetail(), WebAPIAdapterGUI::getDeviceSet(), and WebAPIAdapterSrv::getDeviceSet().
 { return m_uid; }
serialize()
virtual QByteArray ChannelAPI::serialize () const pure virtual
Implemented in ATVMod, FileSource, ATVDemod, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, ChannelAnalyzer, FreeDVDemod, BFMDemod, DATVDemod, FreqTracker, NFMDemod, SSBDemod, RemoteSink, LocalSource, LocalSink, UDPSink, DSDDemod, AMDemod, WFMDemod, UDPSource, and LoRaDemod.
Referenced by DeviceSet::saveRxChannelSettings(), and DeviceSet::saveTxChannelSettings().
setDeviceAPI()
void ChannelAPI::setDeviceAPI (DeviceAPI * deviceAPI) inline
Definition at line 92 of file channelapi.h.
 { m_deviceAPI = deviceAPI; }
setDeviceSetIndex()
void ChannelAPI::setDeviceSetIndex (int deviceSetIndex) inline
Definition at line 90 of file channelapi.h.
 { m_deviceSetIndex = deviceSetIndex; }
setIndexInDeviceSet()
void ChannelAPI::setIndexInDeviceSet (int indexInDeviceSet) inline
Definition at line 88 of file channelapi.h.
Referenced by DeviceAPI::removeChannelSinkAPI(), and DeviceAPI::removeChannelSourceAPI().
 { m_indexInDeviceSet = indexInDeviceSet; }
setName()
virtual void ChannelAPI::setName (const QString & name) inline virtual
Definition at line 52 of file channelapi.h.
 { m_name = name; }
webapiReportGet()
virtual int ChannelAPI::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) inline virtual
Reimplemented in ATVMod, FileSource, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, BFMDemod, FreeDVDemod, SSBDemod, DSDDemod, FreqTracker, NFMDemod, WFMDemod, UDPSink, AMDemod, and UDPSource.
Definition at line 79 of file channelapi.h.
Referenced by WebAPIAdapterGUI::devicesetChannelReportGet(), WebAPIAdapterSrv::devicesetChannelReportGet(), WebAPIAdapterGUI::getChannelsDetail(), and WebAPIAdapterSrv::getChannelsDetail().
     {
         (void) response;
         errorMessage = "Not implemented"; return 501;
     }
webapiSettingsGet()
virtual int ChannelAPI::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) inline virtual
Reimplemented in ATVMod, FileSource, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, BFMDemod, FreeDVDemod, SSBDemod, DSDDemod, FreqTracker, NFMDemod, WFMDemod, RemoteSink, LocalSource, LocalSink, UDPSink, AMDemod, and UDPSource.
Definition at line 59 of file channelapi.h.
Referenced by WebAPIAdapterGUI::devicesetChannelSettingsGet(), and WebAPIAdapterSrv::devicesetChannelSettingsGet().
     {
         (void) response;
         errorMessage = "Not implemented"; return 501;
     }
webapiSettingsPutPatch()
virtual int ChannelAPI::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) inline virtual
Reimplemented in ATVMod, FileSource, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, BFMDemod, FreeDVDemod, SSBDemod, DSDDemod, FreqTracker, NFMDemod, WFMDemod, RemoteSink, LocalSource, LocalSink, UDPSink, AMDemod, and UDPSource.
Definition at line 67 of file channelapi.h.
Referenced by WebAPIAdapterGUI::devicesetChannelSettingsPutPatch(), and WebAPIAdapterSrv::devicesetChannelSettingsPutPatch().
     {
         (void) force;
         (void) channelSettingsKeys;
         (void) response;
         errorMessage = "Not implemented"; return 501;
     }
Member Data Documentation
m_deviceAPI
DeviceAPI* ChannelAPI::m_deviceAPI private
Definition at line 111 of file channelapi.h.
m_deviceSetIndex
int ChannelAPI::m_deviceSetIndex private
Definition at line 110 of file channelapi.h.
m_indexInDeviceSet
int ChannelAPI::m_indexInDeviceSet private
Definition at line 109 of file channelapi.h.
m_name
QString ChannelAPI::m_name private
Unique identifier in a device set used for sorting. Used when there is no GUI. In GUI version it is supported by GUI object name accessed through PluginInstanceGUI.
Definition at line 107 of file channelapi.h.
m_streamType
StreamType ChannelAPI::m_streamType private
Definition at line 103 of file channelapi.h.
m_uid
uint64_t ChannelAPI::m_uid private
Definition at line 112 of file channelapi.h.
The documentation for this class was generated from the following files:
sdrbase/channel/channelapi.h
sdrbase/channel/channelapi.cpp