SDRAngel: DATVDemod::MsgReportModcodCstlnChange Class Reference
DATVDemod::MsgReportModcodCstlnChange Class Reference
#include <datvdemod.h>
Public Member Functions
DATVDemodSettings::DATVModulation getModulation () const
DATVDemodSettings::DATVCodeRate getCodeRate () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportModcodCstlnChange * create (const DATVDemodSettings::DATVModulation &modulation, const DATVDemodSettings::DATVCodeRate &codeRate)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportModcodCstlnChange (const DATVDemodSettings::DATVModulation &modulation, const DATVDemodSettings::DATVCodeRate &codeRate)
Private Attributes
DATVDemodSettings::DATVModulation m_modulation
DATVDemodSettings::DATVCodeRate m_codeRate
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 243 of file datvdemod.h.
Constructor & Destructor Documentation
MsgReportModcodCstlnChange()
DATVDemod::MsgReportModcodCstlnChange::MsgReportModcodCstlnChange (const DATVDemodSettings::DATVModulation & modulation, const DATVDemodSettings::DATVCodeRate & codeRate) inline private
Definition at line 260 of file datvdemod.h.
           :
             Message(),
             m_modulation(modulation),
             m_codeRate(codeRate)
         { }
Member Function Documentation
create()
static MsgReportModcodCstlnChange* DATVDemod::MsgReportModcodCstlnChange::create (const DATVDemodSettings::DATVModulation & modulation, const DATVDemodSettings::DATVCodeRate & codeRate) inline static
Definition at line 250 of file datvdemod.h.
Referenced by DATVDemod::feed().
         {
             return new MsgReportModcodCstlnChange(modulation, codeRate);
         }
getCodeRate()
DATVDemodSettings::DATVCodeRate DATVDemod::MsgReportModcodCstlnChange::getCodeRate () const inline
Definition at line 248 of file datvdemod.h.
Referenced by DATVDemodGUI::handleMessage().
 { return m_codeRate; }
getModulation()
DATVDemodSettings::DATVModulation DATVDemod::MsgReportModcodCstlnChange::getModulation () const inline
Definition at line 247 of file datvdemod.h.
Referenced by DATVDemodGUI::handleMessage().
 { return m_modulation; }
Member Data Documentation
m_codeRate
DATVDemodSettings::DATVCodeRate DATVDemod::MsgReportModcodCstlnChange::m_codeRate private
Definition at line 258 of file datvdemod.h.
m_modulation
DATVDemodSettings::DATVModulation DATVDemod::MsgReportModcodCstlnChange::m_modulation private
Definition at line 257 of file datvdemod.h.
The documentation for this class was generated from the following file:
plugins/channelrx/demoddatv/datvdemod.h