SDRAngel: KiwiSDRInput::MsgStartStop Class Reference
KiwiSDRInput::MsgStartStop Class Reference
#include <kiwisdrinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 82 of file kiwisdrinput.h.
Constructor & Destructor Documentation
MsgStartStop()
KiwiSDRInput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 95 of file kiwisdrinput.h.
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* KiwiSDRInput::MsgStartStop::create (bool startStop) inline static
Definition at line 88 of file kiwisdrinput.h.
Referenced by KiwiSDRGui::on_startStop_toggled(), and KiwiSDRInput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool KiwiSDRInput::MsgStartStop::getStartStop () const inline
Definition at line 86 of file kiwisdrinput.h.
Referenced by KiwiSDRGui::handleMessage(), and KiwiSDRInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool KiwiSDRInput::MsgStartStop::m_startStop protected
Definition at line 93 of file kiwisdrinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/kiwisdr/kiwisdrinput.h