SDRAngel: FCDProInput::MsgStartStop Class Reference
FCDProInput::MsgStartStop Class Reference
#include <fcdproinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 90 of file fcdproinput.h.
Constructor & Destructor Documentation
MsgStartStop()
FCDProInput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 103 of file fcdproinput.h.
References fcd_buffer::start.
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* FCDProInput::MsgStartStop::create (bool startStop) inline static
Definition at line 96 of file fcdproinput.h.
Referenced by FCDProGui::on_startStop_toggled(), and FCDProInput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool FCDProInput::MsgStartStop::getStartStop () const inline
Definition at line 94 of file fcdproinput.h.
Referenced by FCDProGui::handleMessage(), and FCDProInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool FCDProInput::MsgStartStop::m_startStop protected
Definition at line 101 of file fcdproinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/fcdpro/fcdproinput.h