SDRAngel: FCDProPlusInput::MsgConfigureFCDProPlus Class Reference
FCDProPlusInput::MsgConfigureFCDProPlus Class Reference
#include <fcdproplusinput.h>
Public Member Functions
const FCDProPlusSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureFCDProPlus * create (const FCDProPlusSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureFCDProPlus (const FCDProPlusSettings &settings, bool force)
Private Attributes
FCDProPlusSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 48 of file fcdproplusinput.h.
Constructor & Destructor Documentation
MsgConfigureFCDProPlus()
FCDProPlusInput::MsgConfigureFCDProPlus::MsgConfigureFCDProPlus (const FCDProPlusSettings & settings, bool force) inline private
Definition at line 64 of file fcdproplusinput.h.
                                                                                :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureFCDProPlus* FCDProPlusInput::MsgConfigureFCDProPlus::create (const FCDProPlusSettings & settings, bool force) inline static
Definition at line 55 of file fcdproplusinput.h.
Referenced by FCDProPlusInput::deserialize(), FCDProPlusInput::setCenterFrequency(), FCDProPlusGui::updateHardware(), and FCDProPlusInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureFCDProPlus(settings, force);
         }
getForce()
bool FCDProPlusInput::MsgConfigureFCDProPlus::getForce () const inline
Definition at line 53 of file fcdproplusinput.h.
Referenced by FCDProPlusInput::handleMessage().
 { return m_force; }
getSettings()
const FCDProPlusSettings& FCDProPlusInput::MsgConfigureFCDProPlus::getSettings () const inline
Definition at line 52 of file fcdproplusinput.h.
Referenced by FCDProPlusGui::handleMessage(), and FCDProPlusInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool FCDProPlusInput::MsgConfigureFCDProPlus::m_force private
Definition at line 62 of file fcdproplusinput.h.
m_settings
FCDProPlusSettings FCDProPlusInput::MsgConfigureFCDProPlus::m_settings private
Definition at line 61 of file fcdproplusinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/fcdproplus/fcdproplusinput.h