SDRAngel: DownChannelizer Class Reference
DownChannelizer Class Reference
#include <downchannelizer.h>
Classes
struct FilterStage
class MsgChannelizerNotification
class MsgSetChannelizer
Signals
void inputSampleRateChanged ()
Public Member Functions
DownChannelizer (BasebandSampleSink *sampleSink)
virtual ~DownChannelizer ()
void configure (MessageQueue *messageQueue, int sampleRate, int centerFrequency)
void set (MessageQueue *messageQueue, unsigned int log2Decim, unsigned int filterChainHash)
int getInputSampleRate () const
int getRequestedCenterFrequency () const
virtual void start ()
virtual void stop ()
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool positiveOnly)
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Protected Types
typedef std::list< FilterStage * > FilterStages
Protected Member Functions
void applyConfiguration ()
void applySetting (unsigned int log2Decim, unsigned int filterChainHash)
bool signalContainsChannel (Real sigStart, Real sigEnd, Real chanStart, Real chanEnd) const
Real createFilterChain (Real sigStart, Real sigEnd, Real chanStart, Real chanEnd)
void setFilterChain (const std::vector< unsigned int > &stageIndexes)
void freeFilterChain ()
void debugFilterChain ()
Protected Attributes
FilterStages m_filterStages
bool m_filterChainSetMode
BasebandSampleSink * m_sampleSink
Demodulator.
int m_inputSampleRate
int m_requestedOutputSampleRate
int m_requestedCenterFrequency
int m_currentOutputSampleRate
int m_currentCenterFrequency
SampleVector m_sampleBuffer
QMutex m_mutex
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Additional Inherited Members
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Detailed Description
Definition at line 34 of file downchannelizer.h.
Member Typedef Documentation
FilterStages
typedef std::list<FilterStage*> DownChannelizer::FilterStages protected
Definition at line 119 of file downchannelizer.h.
Constructor & Destructor Documentation
DownChannelizer()
DownChannelizer::DownChannelizer (BasebandSampleSink * sampleSink)
Definition at line 30 of file downchannelizer.cpp.
                                                                :
     m_filterChainSetMode(false),
     m_sampleSink(sampleSink),
     m_inputSampleRate(0),
     m_requestedOutputSampleRate(0),
     m_requestedCenterFrequency(0),
     m_currentOutputSampleRate(0),
     m_currentCenterFrequency(0)
 {
     QString name = "DownChannelizer(" + m_sampleSink->objectName() + ")";
     setObjectName(name);
 }
~DownChannelizer()
DownChannelizer::~DownChannelizer () virtual
Definition at line 43 of file downchannelizer.cpp.
References freeFilterChain().
 {
     freeFilterChain();
 }
Member Function Documentation
applyConfiguration()
void DownChannelizer::applyConfiguration () protected
Definition at line 184 of file downchannelizer.cpp.
References DownChannelizer::MsgChannelizerNotification::create(), createFilterChain(), freeFilterChain(), BasebandSampleSink::getInputMessageQueue(), m_currentCenterFrequency, m_currentOutputSampleRate, m_filterChainSetMode, m_filterStages, m_inputSampleRate, m_mutex, m_requestedCenterFrequency, m_requestedOutputSampleRate, m_sampleSink, and MessageQueue::push().
Referenced by handleMessage().
 {
     m_filterChainSetMode = false;
     if (m_inputSampleRate == 0)
     {
         qDebug() << "DownChannelizer::applyConfiguration: m_inputSampleRate=0 aborting";
         return;
     }
     m_mutex.lock();
     freeFilterChain();
     m_currentCenterFrequency = createFilterChain(
         m_inputSampleRate / -2, m_inputSampleRate / 2,
         m_requestedCenterFrequency - m_requestedOutputSampleRate / 2, m_requestedCenterFrequency + m_requestedOutputSampleRate / 2);
     m_mutex.unlock();
     //debugFilterChain();
     m_currentOutputSampleRate = m_inputSampleRate / (1 << m_filterStages.size());
     qDebug() << "DownChannelizer::applyConfiguration in=" << m_inputSampleRate
             << ", req=" << m_requestedOutputSampleRate
             << ", out=" << m_currentOutputSampleRate
             << ", fc=" << m_currentCenterFrequency;
     if (m_sampleSink != 0)
     {
         MsgChannelizerNotification *notif = MsgChannelizerNotification::create(m_currentOutputSampleRate, m_currentCenterFrequency);
         m_sampleSink->getInputMessageQueue()->push(notif);
     }
 }
applySetting()
void DownChannelizer::applySetting (unsigned int log2Decim, unsigned int filterChainHash) protected
Definition at line 220 of file downchannelizer.cpp.
References HBFilterChainConverter::convertToIndexes(), DownChannelizer::MsgChannelizerNotification::create(), DownChannelizer::FilterStage::FilterStage(), freeFilterChain(), BasebandSampleSink::getInputMessageQueue(), m_currentCenterFrequency, m_currentOutputSampleRate, m_filterChainSetMode, m_filterStages, m_inputSampleRate, m_mutex, m_requestedCenterFrequency, m_requestedOutputSampleRate, m_sampleSink, MessageQueue::push(), and setFilterChain().
Referenced by handleMessage().
 {
     m_filterChainSetMode = true;
     std::vector<unsigned int> stageIndexes;
     m_currentCenterFrequency = m_inputSampleRate * HBFilterChainConverter::convertToIndexes(log2Decim, filterChainHash, stageIndexes);
     m_requestedCenterFrequency = m_currentCenterFrequency;
     m_mutex.lock();
     freeFilterChain();
     setFilterChain(stageIndexes);
     m_mutex.unlock();
     m_currentOutputSampleRate = m_inputSampleRate / (1 << m_filterStages.size());
     m_requestedOutputSampleRate = m_currentOutputSampleRate;
     qDebug() << "DownChannelizer::applySetting inputSampleRate:" << m_inputSampleRate
             << " currentOutputSampleRate: " << m_currentOutputSampleRate
             << " currentCenterFrequency: " << m_currentCenterFrequency
             << " nb_filters: " << stageIndexes.size()
             << " nb_stages: " << m_filterStages.size();
     if (m_sampleSink != 0)
     {
         MsgChannelizerNotification *notif = MsgChannelizerNotification::create(m_currentOutputSampleRate, m_currentCenterFrequency);
         m_sampleSink->getInputMessageQueue()->push(notif);
     }
 }
configure()
void DownChannelizer::configure (MessageQueue * messageQueue, int sampleRate, int centerFrequency)
Definition at line 48 of file downchannelizer.cpp.
References MessageQueue::push().
Referenced by FreqTracker::configureChannelizer(), LoRaDemod::handleMessage(), AMDemod::handleMessage(), WFMDemod::handleMessage(), DSDDemod::handleMessage(), UDPSink::handleMessage(), SSBDemod::handleMessage(), NFMDemod::handleMessage(), BFMDemod::handleMessage(), FreeDVDemod::handleMessage(), ChannelAnalyzer::handleMessage(), DATVDemod::handleMessage(), and ATVDemod::handleMessage().
 {
     Message* cmd = new DSPConfigureChannelizer(sampleRate, centerFrequency);
     messageQueue->push(cmd);
 }
createFilterChain()
Real DownChannelizer::createFilterChain (Real sigStart, Real sigEnd, Real chanStart, Real chanEnd) protected
Definition at line 307 of file downchannelizer.cpp.
References DownChannelizer::FilterStage::FilterStage(), m_filterStages, DownChannelizer::FilterStage::ModeCenter, DownChannelizer::FilterStage::ModeLowerHalf, DownChannelizer::FilterStage::ModeUpperHalf, and signalContainsChannel().
Referenced by applyConfiguration().
 {
     Real sigBw = sigEnd - sigStart;
     Real rot = sigBw / 4;
     //qDebug("DownChannelizer::createFilterChain: Signal [%.1f, %.1f] (BW %.1f), Channel [%.1f, %.1f], Rot %.1f", sigStart, sigEnd, sigBw, chanStart, chanEnd, rot);
     // check if it fits into the left half
     if(signalContainsChannel(sigStart, sigStart + sigBw / 2.0, chanStart, chanEnd))
     {
         //qDebug("DownChannelizer::createFilterChain: -> take left half (rotate by +1/4 and decimate by 2)");
         m_filterStages.push_back(new FilterStage(FilterStage::ModeLowerHalf));
         return createFilterChain(sigStart, sigStart + sigBw / 2.0, chanStart, chanEnd);
     }
     // check if it fits into the right half
     if(signalContainsChannel(sigEnd - sigBw / 2.0f, sigEnd, chanStart, chanEnd))
     {
         //qDebug("DownChannelizer::createFilterChain: -> take right half (rotate by -1/4 and decimate by 2)");
         m_filterStages.push_back(new FilterStage(FilterStage::ModeUpperHalf));
         return createFilterChain(sigEnd - sigBw / 2.0f, sigEnd, chanStart, chanEnd);
     }
     // check if it fits into the center
     if(signalContainsChannel(sigStart + rot, sigEnd - rot, chanStart, chanEnd))
     {
         //qDebug("DownChannelizer::createFilterChain: -> take center half (decimate by 2)");
         m_filterStages.push_back(new FilterStage(FilterStage::ModeCenter));
         return createFilterChain(sigStart + rot, sigEnd - rot, chanStart, chanEnd);
     }
     Real ofs = ((chanEnd - chanStart) / 2.0 + chanStart) - ((sigEnd - sigStart) / 2.0 + sigStart);
     //qDebug("DownChannelizer::createFilterChain: -> complete (final BW %.1f, frequency offset %.1f)", sigBw, ofs);
     return ofs;
 }
debugFilterChain()
void DownChannelizer::debugFilterChain () protected
Definition at line 370 of file downchannelizer.cpp.
References m_filterStages, DownChannelizer::FilterStage::ModeCenter, DownChannelizer::FilterStage::ModeLowerHalf, and DownChannelizer::FilterStage::ModeUpperHalf.
 {
     qDebug("DownChannelizer::debugFilterChain: %lu stages", m_filterStages.size());
     for(FilterStages::iterator it = m_filterStages.begin(); it != m_filterStages.end(); ++it)
     {
         switch ((*it)->m_mode)
         {
         case FilterStage::ModeCenter:
             qDebug("DownChannelizer::debugFilterChain: center %s", (*it)->m_sse ? "sse" : "no_sse");
             break;
         case FilterStage::ModeLowerHalf:
             qDebug("DownChannelizer::debugFilterChain: lower %s", (*it)->m_sse ? "sse" : "no_sse");
             break;
         case FilterStage::ModeUpperHalf:
             qDebug("DownChannelizer::debugFilterChain: upper %s", (*it)->m_sse ? "sse" : "no_sse");
             break;
         default:
             qDebug("DownChannelizer::debugFilterChain: none %s", (*it)->m_sse ? "sse" : "no_sse");
             break;
         }
     }
 }
feed()
void DownChannelizer::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool positiveOnly) virtual
Implements BasebandSampleSink.
Definition at line 60 of file downchannelizer.cpp.
References BasebandSampleSink::feed(), m_filterStages, Sample::m_imag, m_mutex, Sample::m_real, m_sampleBuffer, and m_sampleSink.
 {
     if(m_sampleSink == 0) {
         m_sampleBuffer.clear();
         return;
     }
     if (m_filterStages.size() == 0) // optimization when no downsampling is done anyway
     {
         m_sampleSink->feed(begin, end, positiveOnly);
     }
     else
     {
         m_mutex.lock();
         for(SampleVector::const_iterator sample = begin; sample != end; ++sample)
         {
             Sample s(*sample);
             FilterStages::iterator stage = m_filterStages.begin();
             for (; stage != m_filterStages.end(); ++stage)
             {
 #ifndef SDR_RX_SAMPLE_24BIT
                 s.m_real /= 2; // avoid saturation on 16 bit samples
                 s.m_imag /= 2;
 #endif
                 if(!(*stage)->work(&s))
                 {
                     break;
                 }
             }
             if(stage == m_filterStages.end())
             {
 #ifdef SDR_RX_SAMPLE_24BIT
                 s.m_real /= (1<<(m_filterStages.size())); // on 32 bit samples there is enough headroom to just divide the final result
                 s.m_imag /= (1<<(m_filterStages.size()));
 #endif
                 m_sampleBuffer.push_back(s);
             }
         }
         m_mutex.unlock();
         m_sampleSink->feed(m_sampleBuffer.begin(), m_sampleBuffer.end(), positiveOnly);
         m_sampleBuffer.clear();
     }
 }
freeFilterChain()
void DownChannelizer::freeFilterChain () protected
Definition at line 363 of file downchannelizer.cpp.
References m_filterStages.
Referenced by applyConfiguration(), applySetting(), and ~DownChannelizer().
 {
     for(FilterStages::iterator it = m_filterStages.begin(); it != m_filterStages.end(); ++it)
         delete *it;
     m_filterStages.clear();
 }
getInputSampleRate()
int DownChannelizer::getInputSampleRate () const inline
Definition at line 83 of file downchannelizer.h.
Referenced by ATVDemod::channelSampleRateChanged(), ChannelAnalyzerGUI::getRequestedChannelSampleRate(), DATVDemod::handleMessage(), and ATVDemod::handleMessage().
 { return m_inputSampleRate; }
getRequestedCenterFrequency()
int DownChannelizer::getRequestedCenterFrequency () const inline
Definition at line 84 of file downchannelizer.h.
 { return m_requestedCenterFrequency; }
handleMessage()
bool DownChannelizer::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 127 of file downchannelizer.cpp.
References applyConfiguration(), applySetting(), DSPConfigureChannelizer::getCenterFrequency(), DownChannelizer::MsgSetChannelizer::getFilterChainHash(), Message::getIdentifier(), BasebandSampleSink::getInputMessageQueue(), DownChannelizer::MsgSetChannelizer::getLog2Decim(), DSPSignalNotification::getSampleRate(), DSPConfigureChannelizer::getSampleRate(), BasebandSampleSink::handleMessage(), inputSampleRateChanged(), m_filterChainSetMode, m_inputSampleRate, m_requestedCenterFrequency, m_requestedOutputSampleRate, m_sampleSink, Message::match(), and MessageQueue::push().
 {
     // TODO: apply changes only if input sample rate or requested output sample rate change. Change of center frequency has no impact.
     if (DSPSignalNotification::match(cmd))
     {
         DSPSignalNotification& notif = (DSPSignalNotification&) cmd;
         m_inputSampleRate = notif.getSampleRate();
         qDebug() << "DownChannelizer::handleMessage: DSPSignalNotification: m_inputSampleRate: " << m_inputSampleRate;
         if (!m_filterChainSetMode) {
             applyConfiguration();
         }
         if (m_sampleSink != 0)
         {
             DSPSignalNotification* rep = new DSPSignalNotification(notif); // make a copy
             m_sampleSink->getInputMessageQueue()->push(rep);
         }
         emit inputSampleRateChanged();
         return true;
     }
     else if (DSPConfigureChannelizer::match(cmd))
     {
         DSPConfigureChannelizer& chan = (DSPConfigureChannelizer&) cmd;
         m_requestedOutputSampleRate = chan.getSampleRate();
         m_requestedCenterFrequency = chan.getCenterFrequency();
             // qDebug() << "DownChannelizer::handleMessage: DSPConfigureChannelizer:"
             //      << " m_requestedOutputSampleRate: " << m_requestedOutputSampleRate
             //      << " m_requestedCenterFrequency: " << m_requestedCenterFrequency;
         applyConfiguration();
         return true;
     }
     else if (MsgSetChannelizer::match(cmd))
     {
         MsgSetChannelizer& chan = (MsgSetChannelizer&) cmd;
         qDebug() << "DownChannelizer::handleMessage: MsgSetChannelizer";
         applySetting(chan.getLog2Decim(), chan.getFilterChainHash());
         return true;
     }
     else if (BasebandSampleSink::MsgThreadedSink::match(cmd))
     {
         qDebug() << "DownChannelizer::handleMessage: MsgThreadedSink: forwarded to demod";
         return m_sampleSink->handleMessage(cmd); // this message is passed to the demod
     }
     else
     {
         qDebug() << "DownChannelizer::handleMessage: " << cmd.getIdentifier() << " unhandled";
         return false;
     }
 }
inputSampleRateChanged
void DownChannelizer::inputSampleRateChanged () signal
Referenced by handleMessage().
set()
void DownChannelizer::set (MessageQueue * messageQueue, unsigned int log2Decim, unsigned int filterChainHash)
Definition at line 54 of file downchannelizer.cpp.
References MessageQueue::push().
Referenced by LocalSink::handleMessage(), and RemoteSink::handleMessage().
 {
     Message* cmd = new MsgSetChannelizer(log2Decim, filterChainHash);
     messageQueue->push(cmd);
 }
setFilterChain()
void DownChannelizer::setFilterChain (const std::vector< unsigned int > & stageIndexes) protected
Definition at line 343 of file downchannelizer.cpp.
References DownChannelizer::FilterStage::FilterStage(), m_filterStages, DownChannelizer::FilterStage::ModeCenter, DownChannelizer::FilterStage::ModeLowerHalf, and DownChannelizer::FilterStage::ModeUpperHalf.
Referenced by applySetting().
 {
     // filters are described from lower to upper level but the chain is constructed the other way round
     std::vector<unsigned int>::const_reverse_iterator rit = stageIndexes.rbegin();
     // Each index is a base 3 number with 0 = low, 1 = center, 2 = high
     // Functions at upper level will convert a number to base 3 to describe the filter chain. Common converting
     // algorithms will go from LSD to MSD. This explains the reverse order.
     for (; rit != stageIndexes.rend(); ++rit)
     {
         if (*rit == 0) {
             m_filterStages.push_back(new FilterStage(FilterStage::ModeLowerHalf));
         } else if (*rit == 1) {
             m_filterStages.push_back(new FilterStage(FilterStage::ModeCenter));
         } else if (*rit == 2) {
             m_filterStages.push_back(new FilterStage(FilterStage::ModeUpperHalf));
         }
     }
 }
signalContainsChannel()
bool DownChannelizer::signalContainsChannel (Real sigStart, Real sigEnd, Real chanStart, Real chanEnd) const protected
Definition at line 297 of file downchannelizer.cpp.
Referenced by createFilterChain().
 {
     //qDebug("   testing signal [%f, %f], channel [%f, %f]", sigStart, sigEnd, chanStart, chanEnd);
     if(sigEnd <= sigStart)
         return false;
     if(chanEnd <= chanStart)
         return false;
     return (sigStart <= chanStart) && (sigEnd >= chanEnd);
 }
start()
void DownChannelizer::start () virtual
Implements BasebandSampleSink.
Definition at line 109 of file downchannelizer.cpp.
References m_inputSampleRate, m_requestedCenterFrequency, m_requestedOutputSampleRate, m_sampleSink, and BasebandSampleSink::start().
 {
     if (m_sampleSink != 0)
     {
         qDebug() << "DownChannelizer::start: thread: " << thread()
                 << " m_inputSampleRate: " << m_inputSampleRate
                 << " m_requestedOutputSampleRate: " << m_requestedOutputSampleRate
                 << " m_requestedCenterFrequency: " << m_requestedCenterFrequency;
         m_sampleSink->start();
     }
 }
stop()
void DownChannelizer::stop () virtual
Implements BasebandSampleSink.
Definition at line 121 of file downchannelizer.cpp.
References m_sampleSink, and BasebandSampleSink::stop().
 {
     if(m_sampleSink != 0)
         m_sampleSink->stop();
 }
Member Data Documentation
m_currentCenterFrequency
int DownChannelizer::m_currentCenterFrequency protected
Definition at line 127 of file downchannelizer.h.
Referenced by applyConfiguration(), and applySetting().
m_currentOutputSampleRate
int DownChannelizer::m_currentOutputSampleRate protected
Definition at line 126 of file downchannelizer.h.
Referenced by applyConfiguration(), and applySetting().
m_filterChainSetMode
bool DownChannelizer::m_filterChainSetMode protected
Definition at line 121 of file downchannelizer.h.
Referenced by applyConfiguration(), applySetting(), and handleMessage().
m_filterStages
FilterStages DownChannelizer::m_filterStages protected
Definition at line 120 of file downchannelizer.h.
Referenced by applyConfiguration(), applySetting(), createFilterChain(), debugFilterChain(), feed(), freeFilterChain(), and setFilterChain().
m_inputSampleRate
int DownChannelizer::m_inputSampleRate protected
Definition at line 123 of file downchannelizer.h.
Referenced by applyConfiguration(), applySetting(), handleMessage(), and start().
m_mutex
QMutex DownChannelizer::m_mutex protected
Definition at line 129 of file downchannelizer.h.
Referenced by applyConfiguration(), applySetting(), and feed().
m_requestedCenterFrequency
int DownChannelizer::m_requestedCenterFrequency protected
Definition at line 125 of file downchannelizer.h.
Referenced by applyConfiguration(), applySetting(), handleMessage(), and start().
m_requestedOutputSampleRate
int DownChannelizer::m_requestedOutputSampleRate protected
Definition at line 124 of file downchannelizer.h.
Referenced by applyConfiguration(), applySetting(), handleMessage(), and start().
m_sampleBuffer
SampleVector DownChannelizer::m_sampleBuffer protected
Definition at line 128 of file downchannelizer.h.
Referenced by feed().
m_sampleSink
BasebandSampleSink* DownChannelizer::m_sampleSink protected
Demodulator.
Definition at line 122 of file downchannelizer.h.
Referenced by applyConfiguration(), applySetting(), feed(), handleMessage(), start(), and stop().
The documentation for this class was generated from the following files:
sdrbase/dsp/downchannelizer.h
sdrbase/dsp/downchannelizer.cpp