SDRAngel: ATVMod::MsgReportCameraData Class Reference
ATVMod::MsgReportCameraData Class Reference
#include <atvmod.h>
Public Member Functions
int getdeviceNumber () const
float getFPS () const
float getFPSManual () const
bool getFPSManualEnable () const
int getWidth () const
int getHeight () const
int getStatus () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportCameraData * create (int deviceNumber, float fps, float fpsManual, bool fpsManualEnable, int width, int height, int status)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportCameraData (int deviceNumber, float fps, float fpsManual, bool fpsManualEnable, int width, int height, int status)
Protected Attributes
int m_deviceNumber
float m_fps
float m_fpsManual
bool m_fpsManualEnable
int m_width
int m_height
int m_status
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 273 of file atvmod.h.
Constructor & Destructor Documentation
MsgReportCameraData()
ATVMod::MsgReportCameraData::MsgReportCameraData (int deviceNumber, float fps, float fpsManual, bool fpsManualEnable, int width, int height, int status) inline protected
Definition at line 313 of file atvmod.h.
                             :
             Message(),
             m_deviceNumber(deviceNumber),
             m_fps(fps),
             m_fpsManual(fpsManual),
             m_fpsManualEnable(fpsManualEnable),
             m_width(width),
             m_height(height),
             m_status(status)
         { }
Member Function Documentation
create()
static MsgReportCameraData* ATVMod::MsgReportCameraData::create (int deviceNumber, float fps, float fpsManual, bool fpsManualEnable, int width, int height, int status) inline static
Definition at line 285 of file atvmod.h.
Referenced by ATVMod::getCameraNumbers(), ATVMod::handleMessage(), and ATVMod::pullVideo().
         {
             return new MsgReportCameraData(
                     deviceNumber,
                     fps,
                     fpsManual,
                     fpsManualEnable,
                     width,
                     height,
                     status);
         }
getdeviceNumber()
int ATVMod::MsgReportCameraData::getdeviceNumber () const inline
Definition at line 277 of file atvmod.h.
Referenced by ATVModGUI::handleMessage().
 { return m_deviceNumber; }
getFPS()
float ATVMod::MsgReportCameraData::getFPS () const inline
Definition at line 278 of file atvmod.h.
References ATVMod::m_fps.
Referenced by ATVModGUI::handleMessage().
 { return m_fps; }
getFPSManual()
float ATVMod::MsgReportCameraData::getFPSManual () const inline
Definition at line 279 of file atvmod.h.
Referenced by ATVModGUI::handleMessage().
 { return m_fpsManual; }
getFPSManualEnable()
bool ATVMod::MsgReportCameraData::getFPSManualEnable () const inline
Definition at line 280 of file atvmod.h.
Referenced by ATVModGUI::handleMessage().
 { return m_fpsManualEnable; }
getHeight()
int ATVMod::MsgReportCameraData::getHeight () const inline
Definition at line 282 of file atvmod.h.
Referenced by ATVModGUI::handleMessage().
 { return m_height; }
getStatus()
int ATVMod::MsgReportCameraData::getStatus () const inline
Definition at line 283 of file atvmod.h.
Referenced by ATVModGUI::handleMessage().
 { return m_status; }
getWidth()
int ATVMod::MsgReportCameraData::getWidth () const inline
Definition at line 281 of file atvmod.h.
Referenced by ATVModGUI::handleMessage().
 { return m_width; }
Member Data Documentation
m_deviceNumber
int ATVMod::MsgReportCameraData::m_deviceNumber protected
Definition at line 305 of file atvmod.h.
m_fps
float ATVMod::MsgReportCameraData::m_fps protected
Definition at line 306 of file atvmod.h.
m_fpsManual
float ATVMod::MsgReportCameraData::m_fpsManual protected
Definition at line 307 of file atvmod.h.
m_fpsManualEnable
bool ATVMod::MsgReportCameraData::m_fpsManualEnable protected
Definition at line 308 of file atvmod.h.
m_height
int ATVMod::MsgReportCameraData::m_height protected
Definition at line 310 of file atvmod.h.
m_status
int ATVMod::MsgReportCameraData::m_status protected
Definition at line 311 of file atvmod.h.
m_width
int ATVMod::MsgReportCameraData::m_width protected
Definition at line 309 of file atvmod.h.
The documentation for this class was generated from the following file:
plugins/channeltx/modatv/atvmod.h