SDRAngel: LocalSink::MsgConfigureLocalSink Class Reference
LocalSink::MsgConfigureLocalSink Class Reference
#include <localsink.h>
Public Member Functions
const LocalSinkSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureLocalSink * create (const LocalSinkSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureLocalSink (const LocalSinkSettings &settings, bool force)
Private Attributes
LocalSinkSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 40 of file localsink.h.
Constructor & Destructor Documentation
MsgConfigureLocalSink()
LocalSink::MsgConfigureLocalSink::MsgConfigureLocalSink (const LocalSinkSettings & settings, bool force) inline private
Definition at line 56 of file localsink.h.
Referenced by create().
                                                                              :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureLocalSink* LocalSink::MsgConfigureLocalSink::create (const LocalSinkSettings & settings, bool force) inline static
Definition at line 47 of file localsink.h.
References MsgConfigureLocalSink().
Referenced by LocalSinkGUI::applySettings(), LocalSink::deserialize(), and LocalSink::webapiSettingsPutPatch().
         {
             return new MsgConfigureLocalSink(settings, force);
         }
getForce()
bool LocalSink::MsgConfigureLocalSink::getForce () const inline
Definition at line 45 of file localsink.h.
References m_force.
Referenced by LocalSink::handleMessage().
 { return m_force; }
getSettings()
const LocalSinkSettings& LocalSink::MsgConfigureLocalSink::getSettings () const inline
Definition at line 44 of file localsink.h.
References m_settings.
Referenced by LocalSinkGUI::handleMessage(), and LocalSink::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool LocalSink::MsgConfigureLocalSink::m_force private
Definition at line 54 of file localsink.h.
Referenced by getForce().
m_settings
LocalSinkSettings LocalSink::MsgConfigureLocalSink::m_settings private
Definition at line 53 of file localsink.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/channelrx/localsink/localsink.h