SDRAngel: SWGSDRangel::SWGATVModReport Class Reference
SWGSDRangel::SWGATVModReport Class Reference
#include <SWGATVModReport.h>
Public Member Functions
SWGATVModReport ()
SWGATVModReport (QString *json)
virtual ~SWGATVModReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGATVModReport * fromJson (QString &jsonString) override
float getChannelPowerDb ()
void setChannelPowerDb (float channel_power_db)
qint32 getChannelSampleRate ()
void setChannelSampleRate (qint32 channel_sample_rate)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
float channel_power_db
bool m_channel_power_db_isSet
qint32 channel_sample_rate
bool m_channel_sample_rate_isSet
Detailed Description
Definition at line 31 of file SWGATVModReport.h.
Constructor & Destructor Documentation
SWGATVModReport() [1/2]
SWGSDRangel::SWGATVModReport::SWGATVModReport ()
Definition at line 30 of file SWGATVModReport.cpp.
References channel_power_db, channel_sample_rate, m_channel_power_db_isSet, and m_channel_sample_rate_isSet.
{
     channel_power_db = 0.0f;
     m_channel_power_db_isSet = false;
     channel_sample_rate = 0;
     m_channel_sample_rate_isSet = false;
 }
SWGATVModReport() [2/2]
SWGSDRangel::SWGATVModReport::SWGATVModReport (QString * json)
Definition at line 25 of file SWGATVModReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGATVModReport()
SWGSDRangel::SWGATVModReport::~SWGATVModReport () virtual
Definition at line 37 of file SWGATVModReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGATVModReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 73 of file SWGATVModReport.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGATVModReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 84 of file SWGATVModReport.cpp.
References channel_power_db, channel_sample_rate, m_channel_power_db_isSet, and m_channel_sample_rate_isSet.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_channel_power_db_isSet){
         obj->insert("channelPowerDB", QJsonValue(channel_power_db));
     }
     if(m_channel_sample_rate_isSet){
         obj->insert("channelSampleRate", QJsonValue(channel_sample_rate));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGATVModReport::cleanup ()
Definition at line 50 of file SWGATVModReport.cpp.
Referenced by ~SWGATVModReport().
{
 }
fromJson()
SWGATVModReport * SWGSDRangel::SWGATVModReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 56 of file SWGATVModReport.cpp.
References fromJsonObject().
Referenced by SWGATVModReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGATVModReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 65 of file SWGATVModReport.cpp.
References channel_power_db, channel_sample_rate, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&channel_power_db, pJson["channelPowerDB"], "float", "");
     ::SWGSDRangel::setValue(&channel_sample_rate, pJson["channelSampleRate"], "qint32", "");
 }
getChannelPowerDb()
float SWGSDRangel::SWGATVModReport::getChannelPowerDb ()
Definition at line 97 of file SWGATVModReport.cpp.
References channel_power_db.
{
     return channel_power_db;
 }
getChannelSampleRate()
qint32 SWGSDRangel::SWGATVModReport::getChannelSampleRate ()
Definition at line 107 of file SWGATVModReport.cpp.
References channel_sample_rate.
{
     return channel_sample_rate;
 }
init()
void SWGSDRangel::SWGATVModReport::init ()
Definition at line 42 of file SWGATVModReport.cpp.
References channel_power_db, channel_sample_rate, m_channel_power_db_isSet, and m_channel_sample_rate_isSet.
Referenced by SWGATVModReport(), and ATVMod::webapiReportGet().
                       {
     channel_power_db = 0.0f;
     m_channel_power_db_isSet = false;
     channel_sample_rate = 0;
     m_channel_sample_rate_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGATVModReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 118 of file SWGATVModReport.cpp.
References m_channel_power_db_isSet, and m_channel_sample_rate_isSet.
Referenced by SWGSDRangel::SWGChannelReport::asJsonObject(), and SWGSDRangel::SWGChannelReport::isSet().
                       {
     bool isObjectUpdated = false;
     do{
         if(m_channel_power_db_isSet){ isObjectUpdated = true; break;}
         if(m_channel_sample_rate_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setChannelPowerDb()
void SWGSDRangel::SWGATVModReport::setChannelPowerDb (float channel_power_db)
Definition at line 101 of file SWGATVModReport.cpp.
References channel_power_db, and m_channel_power_db_isSet.
Referenced by ATVMod::webapiFormatChannelReport().
{
     this->channel_power_db = channel_power_db;
     this->m_channel_power_db_isSet = true;
 }
setChannelSampleRate()
void SWGSDRangel::SWGATVModReport::setChannelSampleRate (qint32 channel_sample_rate)
Definition at line 111 of file SWGATVModReport.cpp.
References channel_sample_rate, and m_channel_sample_rate_isSet.
Referenced by ATVMod::webapiFormatChannelReport().
{
     this->channel_sample_rate = channel_sample_rate;
     this->m_channel_sample_rate_isSet = true;
 }
Member Data Documentation
channel_power_db
float SWGSDRangel::SWGATVModReport::channel_power_db private
Definition at line 54 of file SWGATVModReport.h.
Referenced by asJsonObject(), fromJsonObject(), getChannelPowerDb(), init(), setChannelPowerDb(), and SWGATVModReport().
channel_sample_rate
qint32 SWGSDRangel::SWGATVModReport::channel_sample_rate private
Definition at line 57 of file SWGATVModReport.h.
Referenced by asJsonObject(), fromJsonObject(), getChannelSampleRate(), init(), setChannelSampleRate(), and SWGATVModReport().
m_channel_power_db_isSet
bool SWGSDRangel::SWGATVModReport::m_channel_power_db_isSet private
Definition at line 55 of file SWGATVModReport.h.
Referenced by asJsonObject(), init(), isSet(), setChannelPowerDb(), and SWGATVModReport().
m_channel_sample_rate_isSet
bool SWGSDRangel::SWGATVModReport::m_channel_sample_rate_isSet private
Definition at line 58 of file SWGATVModReport.h.
Referenced by asJsonObject(), init(), isSet(), setChannelSampleRate(), and SWGATVModReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGATVModReport.h
swagger/sdrangel/code/qt5/client/SWGATVModReport.cpp