SDRAngel: ScopeVis::MsgConfigureScopeVisNG Class Reference
ScopeVis::MsgConfigureScopeVisNG Class Reference
Public Member Functions
uint32_t getTraceSize () const
uint32_t getTimeBase () const
uint32_t getTimeOfsProMill () const
uint32_t getTriggerPre () const
bool getFreeRun () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureScopeVisNG * create (uint32_t traceSize, uint32_t timeBase, uint32_t timeOfsProMill, uint32_t triggerPre, bool freeRun)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureScopeVisNG (uint32_t traceSize, uint32_t timeBase, uint32_t timeOfsProMill, uint32_t triggerPre, bool freeRun)
Private Attributes
uint32_t m_traceSize
uint32_t m_timeBase
uint32_t m_timeOfsProMill
uint32_t m_triggerPre
bool m_freeRun
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 252 of file scopevis.h.
Constructor & Destructor Documentation
MsgConfigureScopeVisNG()
ScopeVis::MsgConfigureScopeVisNG::MsgConfigureScopeVisNG (uint32_t traceSize, uint32_t timeBase, uint32_t timeOfsProMill, uint32_t triggerPre, bool freeRun) inline private
Definition at line 279 of file scopevis.h.
                               :
             m_traceSize(traceSize),
             m_timeBase(timeBase),
             m_timeOfsProMill(timeOfsProMill),
             m_triggerPre(triggerPre),
             m_freeRun(freeRun)
         {}
Member Function Documentation
create()
static MsgConfigureScopeVisNG* ScopeVis::MsgConfigureScopeVisNG::create (uint32_t traceSize, uint32_t timeBase, uint32_t timeOfsProMill, uint32_t triggerPre, bool freeRun) inline static
Definition at line 256 of file scopevis.h.
Referenced by ScopeVis::configure().
         {
             return new MsgConfigureScopeVisNG(traceSize, timeBase, timeOfsProMill, triggerPre, freeRun);
         }
getFreeRun()
bool ScopeVis::MsgConfigureScopeVisNG::getFreeRun () const inline
Definition at line 270 of file scopevis.h.
Referenced by ScopeVis::handleMessage().
 { return m_freeRun; }
getTimeBase()
uint32_t ScopeVis::MsgConfigureScopeVisNG::getTimeBase () const inline
Definition at line 267 of file scopevis.h.
Referenced by ScopeVis::handleMessage().
 { return m_timeBase; }
getTimeOfsProMill()
uint32_t ScopeVis::MsgConfigureScopeVisNG::getTimeOfsProMill () const inline
Definition at line 268 of file scopevis.h.
Referenced by ScopeVis::handleMessage().
 { return m_timeOfsProMill; }
getTraceSize()
uint32_t ScopeVis::MsgConfigureScopeVisNG::getTraceSize () const inline
Definition at line 266 of file scopevis.h.
Referenced by ScopeVis::handleMessage().
 { return m_traceSize; }
getTriggerPre()
uint32_t ScopeVis::MsgConfigureScopeVisNG::getTriggerPre () const inline
Definition at line 269 of file scopevis.h.
Referenced by ScopeVis::handleMessage().
 { return m_triggerPre; }
Member Data Documentation
m_freeRun
bool ScopeVis::MsgConfigureScopeVisNG::m_freeRun private
Definition at line 277 of file scopevis.h.
m_timeBase
uint32_t ScopeVis::MsgConfigureScopeVisNG::m_timeBase private
Definition at line 274 of file scopevis.h.
m_timeOfsProMill
uint32_t ScopeVis::MsgConfigureScopeVisNG::m_timeOfsProMill private
Definition at line 275 of file scopevis.h.
m_traceSize
uint32_t ScopeVis::MsgConfigureScopeVisNG::m_traceSize private
Definition at line 273 of file scopevis.h.
m_triggerPre
uint32_t ScopeVis::MsgConfigureScopeVisNG::m_triggerPre private
Definition at line 276 of file scopevis.h.
The documentation for this class was generated from the following file:
sdrgui/dsp/scopevis.h