SDRAngel: SWGSDRangel::SWGKiwiSDRReport Class Reference
SWGSDRangel::SWGKiwiSDRReport Class Reference
#include <SWGKiwiSDRReport.h>
Public Member Functions
SWGKiwiSDRReport ()
SWGKiwiSDRReport (QString *json)
virtual ~SWGKiwiSDRReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGKiwiSDRReport * fromJson (QString &jsonString) override
qint32 getStatus ()
void setStatus (qint32 status)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 status
bool m_status_isSet
Detailed Description
Definition at line 31 of file SWGKiwiSDRReport.h.
Constructor & Destructor Documentation
SWGKiwiSDRReport() [1/2]
SWGSDRangel::SWGKiwiSDRReport::SWGKiwiSDRReport ()
Definition at line 30 of file SWGKiwiSDRReport.cpp.
References m_status_isSet, and status.
{
     status = 0;
     m_status_isSet = false;
 }
SWGKiwiSDRReport() [2/2]
SWGSDRangel::SWGKiwiSDRReport::SWGKiwiSDRReport (QString * json)
Definition at line 25 of file SWGKiwiSDRReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGKiwiSDRReport()
SWGSDRangel::SWGKiwiSDRReport::~SWGKiwiSDRReport () virtual
Definition at line 35 of file SWGKiwiSDRReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGKiwiSDRReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 66 of file SWGKiwiSDRReport.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGKiwiSDRReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 77 of file SWGKiwiSDRReport.cpp.
References m_status_isSet, and status.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_status_isSet){
         obj->insert("status", QJsonValue(status));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGKiwiSDRReport::cleanup ()
Definition at line 46 of file SWGKiwiSDRReport.cpp.
Referenced by ~SWGKiwiSDRReport().
{
 }
fromJson()
SWGKiwiSDRReport * SWGSDRangel::SWGKiwiSDRReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 51 of file SWGKiwiSDRReport.cpp.
References fromJsonObject().
Referenced by SWGKiwiSDRReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGKiwiSDRReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 60 of file SWGKiwiSDRReport.cpp.
References SWGSDRangel::setValue(), and status.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&status, pJson["status"], "qint32", "");
 }
getStatus()
qint32 SWGSDRangel::SWGKiwiSDRReport::getStatus ()
Definition at line 87 of file SWGKiwiSDRReport.cpp.
References status.
{
     return status;
 }
init()
void SWGSDRangel::SWGKiwiSDRReport::init ()
Definition at line 40 of file SWGKiwiSDRReport.cpp.
References m_status_isSet, and status.
Referenced by SWGKiwiSDRReport(), and KiwiSDRInput::webapiReportGet().
{
     status = 0;
     m_status_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGKiwiSDRReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 98 of file SWGKiwiSDRReport.cpp.
References m_status_isSet.
Referenced by SWGSDRangel::SWGDeviceReport::asJsonObject(), and SWGSDRangel::SWGDeviceReport::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(m_status_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setStatus()
void SWGSDRangel::SWGKiwiSDRReport::setStatus (qint32 status)
Definition at line 91 of file SWGKiwiSDRReport.cpp.
References m_status_isSet, and status.
Referenced by KiwiSDRInput::webapiFormatDeviceReport().
{
     this->status = status;
     this->m_status_isSet = true;
 }
Member Data Documentation
m_status_isSet
bool SWGSDRangel::SWGKiwiSDRReport::m_status_isSet private
Definition at line 52 of file SWGKiwiSDRReport.h.
Referenced by asJsonObject(), init(), isSet(), setStatus(), and SWGKiwiSDRReport().
status
qint32 SWGSDRangel::SWGKiwiSDRReport::status private
Definition at line 51 of file SWGKiwiSDRReport.h.
Referenced by asJsonObject(), fromJsonObject(), getStatus(), init(), setStatus(), and SWGKiwiSDRReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGKiwiSDRReport.h
swagger/sdrangel/code/qt5/client/SWGKiwiSDRReport.cpp