SDRAngel: TestMI Class Reference
TestMI Class Reference
#include <testmi.h>
Classes
struct DeviceSettingsKeys
class MsgConfigureTestSource
class MsgFileRecord
class MsgStartStop
Public Member Functions
TestMI (DeviceAPI *deviceAPI)
virtual ~TestMI ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSourceSampleRate (int index) const
Sample rate exposed by the source at index.
virtual void setSourceSampleRate (int sampleRate, int index)
For when the source sample rate is set externally.
virtual quint64 getSourceCenterFrequency (int index) const
Center frequency exposed by the source at index.
virtual void setSourceCenterFrequency (qint64 centerFrequency, int index)
virtual int getSinkSampleRate (int index) const
Sample rate exposed by the sink at index.
virtual void setSinkSampleRate (int sampleRate, int index)
For when the sink sample rate is set externally.
virtual quint64 getSinkCenterFrequency (int index) const
Center frequency exposed by the sink at index.
virtual void setSinkCenterFrequency (qint64 centerFrequency, int index)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
bool isRecording (unsigned int istream) const
Public Member Functions inherited from DeviceSampleMIMO
DeviceSampleMIMO ()
virtual ~DeviceSampleMIMO ()
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
unsigned int getNbSourceFifos () const
Get the number of Tx FIFOs.
unsigned int getNbSinkFifos () const
Get the number of Rx FIFOs.
SampleSourceFifo * getSampleSourceFifo (unsigned int index)
Get Tx FIFO at index.
SampleSinkFifo * getSampleSinkFifo (unsigned int index)
Get Rx FIFO at index.
unsigned int getNbSourceStreams () const
Commodity function same as getNbSinkFifos (Rx or source streams)
unsigned int getNbSinkStreams () const
Commodity function same as getNbSourceFifos (Tx or sink streams)
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool applySettings (const TestMISettings &settings, bool force)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const TestMISettings &settings)
void webapiReverseSendSettings (const DeviceSettingsKeys &deviceSettingsKeys, const TestMISettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
std::vector< FileRecord * > m_fileSinks
File sinks to record device I/Q output.
QMutex m_mutex
TestMISettings m_settings
std::vector< TestMIThread * > m_testSourceThreads
QString m_deviceDescription
bool m_running
const QTimer & m_masterTimer
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleMIMO
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
Protected Slots inherited from DeviceSampleMIMO
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleMIMO
std::vector< SampleSourceFifo > m_sampleSourceFifos
Tx FIFOs.
std::vector< SampleSinkFifo > m_sampleSinkFifos
Rx FIFOs.
MessageQueue m_inputMessageQueue
Input queue to the sink.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 35 of file testmi.h.
Constructor & Destructor Documentation
TestMI()
TestMI::TestMI (DeviceAPI * deviceAPI)
Definition at line 45 of file testmi.cpp.
Referenced by TestMI::MsgStartStop::MsgStartStop().
                                    :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_deviceDescription(),
     m_running(false),
     m_masterTimer(deviceAPI->getMasterTimer())
 {
     m_deviceAPI->setNbSourceStreams(2);
     m_deviceAPI->addSourceStream(true); // Add a new source stream data set in the engine - asynchronous handling of FIFOs
     m_deviceAPI->addSourceStream(true); // Add a new source stream data set in the engine - asynchronous handling of FIFOs
     m_sampleSinkFifos.push_back(SampleSinkFifo(96000 * 4));
     m_sampleSinkFifos.push_back(SampleSinkFifo(96000 * 4));
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~TestMI()
TestMI::~TestMI () virtual
Definition at line 61 of file testmi.cpp.
References m_deviceAPI, m_fileSinks, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::removeAncillarySink(), DeviceAPI::removeLastSourceStream(), and stop().
Referenced by TestMI::MsgStartStop::MsgStartStop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     std::vector<FileRecord*>::iterator it = m_fileSinks.begin();
     int istream = 0;
     for (; it != m_fileSinks.end(); ++it, istream++)
     {
         m_deviceAPI->removeAncillarySink(*it, istream);
         delete *it;
     }
     m_deviceAPI->removeLastSourceStream(); // Remove the last source stream data set in the engine
     m_deviceAPI->removeLastSourceStream(); // Remove the last source stream data set in the engine
 }
Member Function Documentation
applySettings()
bool TestMI::applySettings (const TestMISettings & settings, bool force) private
Definition at line 277 of file testmi.cpp.
References TestMIStreamSettings::AutoCorrDC, TestMIStreamSettings::AutoCorrDCAndIQ, TestMIStreamSettings::AutoCorrNone, DeviceSampleSource::calculateDeviceCenterFrequency(), DeviceSampleSource::calculateFrequencyShift(), DeviceAPI::configureCorrections(), DeviceSampleSource::FSHIFT_STD, DeviceAPI::getDeviceEngineInputMessageQueue(), m_deviceAPI, TestMISettings::m_fileRecordName, m_fileSinks, TestMISettings::m_reverseAPIAddress, TestMISettings::m_reverseAPIDeviceIndex, TestMISettings::m_reverseAPIPort, m_settings, TestMISettings::m_streams, TestMI::DeviceSettingsKeys::m_streamsSettingsKeys, m_testSourceThreads, TestMISettings::m_useReverseAPI, TestMIStreamSettings::ModulationPattern0, TestMIStreamSettings::ModulationPattern1, TestMIStreamSettings::ModulationPattern2, MessageQueue::push(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     DeviceSettingsKeys deviceSettingsKeys;
     qDebug() << "TestMI::applySettings: common: "
         << " m_fileRecordName: " << settings.m_fileRecordName
         << " m_useReverseAPI: " << settings.m_useReverseAPI
         << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
         << " m_reverseAPIPort: " << settings.m_reverseAPIPort
         << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex;
     for (unsigned int istream = 0; (istream < m_settings.m_streams.size()) && (istream < settings.m_streams.size()); istream++)
     {
         qDebug() << "TestMI::applySettings: stream #" << istream << ": "
             << " m_centerFrequency: " << settings.m_streams[istream].m_centerFrequency
             << " m_frequencyShift: " << settings.m_streams[istream].m_frequencyShift
             << " m_sampleRate: " << settings.m_streams[istream].m_sampleRate
             << " m_log2Decim: " << settings.m_streams[istream].m_log2Decim
             << " m_fcPos: " << settings.m_streams[istream].m_fcPos
             << " m_amplitudeBits: " << settings.m_streams[istream].m_amplitudeBits
             << " m_sampleSizeIndex: " << settings.m_streams[istream].m_sampleSizeIndex
             << " m_autoCorrOptions: " << settings.m_streams[istream].m_autoCorrOptions
             << " m_dcFactor: " << settings.m_streams[istream].m_dcFactor
             << " m_iFactor: " << settings.m_streams[istream].m_iFactor
             << " m_qFactor: " << settings.m_streams[istream].m_qFactor
             << " m_phaseImbalance: " << settings.m_streams[istream].m_phaseImbalance
             << " m_modulation: " << settings.m_streams[istream].m_modulation
             << " m_amModulation: " << settings.m_streams[istream].m_amModulation
             << " m_fmDeviation: " << settings.m_streams[istream].m_fmDeviation
             << " m_modulationTone: " << settings.m_streams[istream].m_modulationTone;
         deviceSettingsKeys.m_streamsSettingsKeys.push_back(QList<QString>());
         QList<QString>& reverseAPIKeys = deviceSettingsKeys.m_streamsSettingsKeys.back();
         if ((m_settings.m_streams[istream].m_autoCorrOptions != settings.m_streams[istream].m_autoCorrOptions) || force)
         {
             reverseAPIKeys.append("autoCorrOptions");
             switch(settings.m_streams[istream].m_autoCorrOptions)
             {
             case TestMIStreamSettings::AutoCorrDC:
                 m_deviceAPI->configureCorrections(true, false, istream);
                 break;
             case TestMIStreamSettings::AutoCorrDCAndIQ:
                 m_deviceAPI->configureCorrections(true, true, istream);
                 break;
             case TestMIStreamSettings::AutoCorrNone:
             default:
                 m_deviceAPI->configureCorrections(false, false, istream);
                 break;
             }
         }
         if ((m_settings.m_streams[istream].m_sampleRate != settings.m_streams[istream].m_sampleRate) || force)
         {
             reverseAPIKeys.append("sampleRate");
             if ((istream < m_testSourceThreads.size()) && (m_testSourceThreads[istream]))
             {
                 m_testSourceThreads[istream]->setSamplerate(settings.m_streams[istream].m_sampleRate);
                 qDebug("TestMI::applySettings: thread on stream: %u sample rate set to %d",
                     istream, settings.m_streams[istream].m_sampleRate);
             }
         }
         if ((m_settings.m_streams[istream].m_log2Decim != settings.m_streams[istream].m_log2Decim) || force)
         {
             reverseAPIKeys.append("log2Decim");
             if ((istream < m_testSourceThreads.size()) && (m_testSourceThreads[istream]))
             {
                 m_testSourceThreads[istream]->setLog2Decimation(settings.m_streams[istream].m_log2Decim);
                 qDebug("TestMI::applySettings: thread on stream: %u set decimation to %d",
                     istream, (1<<settings.m_streams[istream].m_log2Decim));
             }
         }
         if ((m_settings.m_streams[istream].m_centerFrequency != settings.m_streams[istream].m_centerFrequency)
             || (m_settings.m_streams[istream].m_fcPos != settings.m_streams[istream].m_fcPos)
             || (m_settings.m_streams[istream].m_frequencyShift != settings.m_streams[istream].m_frequencyShift)
             || (m_settings.m_streams[istream].m_sampleRate != settings.m_streams[istream].m_sampleRate)
             || (m_settings.m_streams[istream].m_log2Decim != settings.m_streams[istream].m_log2Decim) || force)
         {
             reverseAPIKeys.append("centerFrequency");
             reverseAPIKeys.append("fcPos");
             reverseAPIKeys.append("frequencyShift");
             qint64 deviceCenterFrequency = DeviceSampleSource::calculateDeviceCenterFrequency(
                     settings.m_streams[istream].m_centerFrequency,
                     0, // no transverter mode
                     settings.m_streams[istream].m_log2Decim,
                     (DeviceSampleSource::fcPos_t) settings.m_streams[istream].m_fcPos,
                     settings.m_streams[istream].m_sampleRate,
                     DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD,
                     false);
             int frequencyShift = settings.m_streams[istream].m_frequencyShift;
             quint32 devSampleRate = settings.m_streams[istream].m_sampleRate;
             if (settings.m_streams[istream].m_log2Decim != 0)
             {
                 frequencyShift += DeviceSampleSource::calculateFrequencyShift(
                         settings.m_streams[istream].m_log2Decim,
                         (DeviceSampleSource::fcPos_t) settings.m_streams[istream].m_fcPos,
                         settings.m_streams[istream].m_sampleRate,
                         DeviceSampleSource::FSHIFT_STD);
             }
             if ((istream < m_testSourceThreads.size()) && (m_testSourceThreads[istream]))
             {
                 m_testSourceThreads[istream]->setFcPos((int) settings.m_streams[istream].m_fcPos);
                 m_testSourceThreads[istream]->setFrequencyShift(frequencyShift);
                 qDebug() << "TestMI::applySettings:"
                         << " thread on istream: " << istream
                         << " center freq: " << settings.m_streams[istream].m_centerFrequency << " Hz"
                         << " device center freq: " << deviceCenterFrequency << " Hz"
                         << " device sample rate: " << devSampleRate << "Hz"
                         << " Actual sample rate: " << devSampleRate/(1<<m_settings.m_streams[istream].m_log2Decim) << "Hz"
                         << " f shift: " << settings.m_streams[istream].m_frequencyShift;
             }
         }
         if ((m_settings.m_streams[istream].m_amplitudeBits != settings.m_streams[istream].m_amplitudeBits) || force)
         {
             reverseAPIKeys.append("amplitudeBits");
             if ((istream < m_testSourceThreads.size()) && (m_testSourceThreads[istream])) {
                 m_testSourceThreads[istream]->setAmplitudeBits(settings.m_streams[istream].m_amplitudeBits);
             }
         }
         if ((m_settings.m_streams[istream].m_dcFactor != settings.m_streams[istream].m_dcFactor) || force)
         {
             reverseAPIKeys.append("dcFactor");
             if ((istream < m_testSourceThreads.size()) && (m_testSourceThreads[istream])) {
                 m_testSourceThreads[istream]->setDCFactor(settings.m_streams[istream].m_dcFactor);
             }
         }
         if ((m_settings.m_streams[istream].m_iFactor != settings.m_streams[istream].m_iFactor) || force)
         {
             reverseAPIKeys.append("iFactor");
             if ((istream < m_testSourceThreads.size()) && (m_testSourceThreads[istream])) {
                 m_testSourceThreads[istream]->setIFactor(settings.m_streams[istream].m_iFactor);
             }
         }
         if ((m_settings.m_streams[istream].m_qFactor != settings.m_streams[istream].m_qFactor) || force)
         {
             reverseAPIKeys.append("qFactor");
             if ((istream < m_testSourceThreads.size()) && (m_testSourceThreads[istream])) {
                 m_testSourceThreads[istream]->setQFactor(settings.m_streams[istream].m_qFactor);
             }
         }
         if ((m_settings.m_streams[istream].m_phaseImbalance != settings.m_streams[istream].m_phaseImbalance) || force)
         {
             reverseAPIKeys.append("phaseImbalance");
             if ((istream < m_testSourceThreads.size()) && (m_testSourceThreads[istream])) {
                 m_testSourceThreads[istream]->setPhaseImbalance(settings.m_streams[istream].m_phaseImbalance);
             }
         }
         if ((m_settings.m_streams[istream].m_sampleSizeIndex != settings.m_streams[istream].m_sampleSizeIndex) || force)
         {
             reverseAPIKeys.append("sampleSizeIndex");
             if ((istream < m_testSourceThreads.size()) && (m_testSourceThreads[istream])) {
                 m_testSourceThreads[istream]->setBitSize(settings.m_streams[istream].m_sampleSizeIndex);
             }
         }
         if ((m_settings.m_streams[istream].m_sampleRate != settings.m_streams[istream].m_sampleRate)
             || (m_settings.m_streams[istream].m_centerFrequency != settings.m_streams[istream].m_centerFrequency)
             || (m_settings.m_streams[istream].m_log2Decim != settings.m_streams[istream].m_log2Decim)
             || (m_settings.m_streams[istream].m_fcPos != settings.m_streams[istream].m_fcPos) || force)
         {
             int sampleRate = settings.m_streams[istream].m_sampleRate/(1<<settings.m_streams[istream].m_log2Decim);
             DSPSignalNotification notif(sampleRate, settings.m_streams[istream].m_centerFrequency);
             m_fileSinks[istream]->handleMessage(notif); // forward to file sink
             DSPMIMOSignalNotification *engineNotif = new DSPMIMOSignalNotification(
                 sampleRate, settings.m_streams[istream].m_centerFrequency, true, istream);
             m_deviceAPI->getDeviceEngineInputMessageQueue()->push(engineNotif);
         }
         if ((m_settings.m_streams[istream].m_modulationTone != settings.m_streams[istream].m_modulationTone) || force)
         {
             reverseAPIKeys.append("modulationTone");
             if ((istream < m_testSourceThreads.size()) && (m_testSourceThreads[istream])) {
                 m_testSourceThreads[istream]->setToneFrequency(settings.m_streams[istream].m_modulationTone * 10);
             }
         }
         if ((m_settings.m_streams[istream].m_modulation != settings.m_streams[istream].m_modulation) || force)
         {
             reverseAPIKeys.append("modulation");
             if ((istream < m_testSourceThreads.size()) && (m_testSourceThreads[istream]))
             {
                 m_testSourceThreads[istream]->setModulation(settings.m_streams[istream].m_modulation);
                 if (settings.m_streams[istream].m_modulation == TestMIStreamSettings::ModulationPattern0) {
                     m_testSourceThreads[istream]->setPattern0();
                 } else if (settings.m_streams[istream].m_modulation == TestMIStreamSettings::ModulationPattern1) {
                     m_testSourceThreads[istream]->setPattern1();
                 } else if (settings.m_streams[istream].m_modulation == TestMIStreamSettings::ModulationPattern2) {
                     m_testSourceThreads[istream]->setPattern2();
                 }
             }
         }
         if ((m_settings.m_streams[istream].m_amModulation != settings.m_streams[istream].m_amModulation) || force)
         {
             reverseAPIKeys.append("amModulation");
             if ((istream < m_testSourceThreads.size()) && (m_testSourceThreads[istream])) {
                 m_testSourceThreads[istream]->setAMModulation(settings.m_streams[istream].m_amModulation / 100.0f);
             }
         }
         if ((m_settings.m_streams[istream].m_fmDeviation != settings.m_streams[istream].m_fmDeviation) || force)
         {
             reverseAPIKeys.append("fmDeviation");
             if ((istream < m_testSourceThreads.size()) && (m_testSourceThreads[istream])) {
                 m_testSourceThreads[istream]->setFMDeviation(settings.m_streams[istream].m_fmDeviation * 100.0f);
             }
         }
     } // for each stream index
     if (settings.m_useReverseAPI)
     {
         qDebug("TestMI::applySettings: call webapiReverseSendSettings");
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(deviceSettingsKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     return true;
 }
deserialize()
bool TestMI::deserialize (const QByteArray & data) virtual
Implements DeviceSampleMIMO.
Definition at line 145 of file testmi.cpp.
References TestMI::MsgConfigureTestSource::create(), TestMISettings::deserialize(), DeviceSampleMIMO::m_guiMessageQueue, DeviceSampleMIMO::m_inputMessageQueue, m_settings, MessageQueue::push(), and TestMISettings::resetToDefaults().
Referenced by TestMI::MsgStartStop::MsgStartStop().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureTestSource* message = MsgConfigureTestSource::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureTestSource* messageToGUI = MsgConfigureTestSource::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void TestMI::destroy () virtual
Implements DeviceSampleMIMO.
Definition at line 83 of file testmi.cpp.
Referenced by TestMI::MsgStartStop::MsgStartStop().
 {
     delete this;
 }
getDeviceDescription()
const QString & TestMI::getDeviceDescription () const virtual
Implements DeviceSampleMIMO.
Definition at line 167 of file testmi.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getSinkCenterFrequency()
virtual quint64 TestMI::getSinkCenterFrequency (int index) const inline virtual
Center frequency exposed by the sink at index.
Implements DeviceSampleMIMO.
Definition at line 123 of file testmi.h.
 { return 0; (void) index; }
getSinkSampleRate()
virtual int TestMI::getSinkSampleRate (int index) const inline virtual
Sample rate exposed by the sink at index.
Implements DeviceSampleMIMO.
Definition at line 121 of file testmi.h.
 { return 0; (void) index; }
getSourceCenterFrequency()
quint64 TestMI::getSourceCenterFrequency (int index) const virtual
Center frequency exposed by the source at index.
Implements DeviceSampleMIMO.
Definition at line 181 of file testmi.cpp.
References m_settings, and TestMISettings::m_streams.
Referenced by setSourceSampleRate().
 {
     if (index < (int) m_settings.m_streams.size()) {
         return m_settings.m_streams[index].m_centerFrequency;
     } else {
         return 0;
     }
 }
getSourceSampleRate()
int TestMI::getSourceSampleRate (int index) const virtual
Sample rate exposed by the source at index.
Implements DeviceSampleMIMO.
Definition at line 172 of file testmi.cpp.
References m_settings, and TestMISettings::m_streams.
Referenced by setMessageQueueToGUI().
 {
     if (index < (int) m_settings.m_streams.size()) {
         return m_settings.m_streams[index].m_sampleRate/(1<<m_settings.m_streams[index].m_log2Decim);
     } else {
         return 0;
     }
 }
handleMessage()
bool TestMI::handleMessage (const Message & message) virtual
Implements DeviceSampleMIMO.
Definition at line 209 of file testmi.cpp.
References applySettings(), DeviceAPI::getDeviceUID(), TestMI::MsgConfigureTestSource::getForce(), TestMI::MsgConfigureTestSource::getSettings(), TestMI::MsgFileRecord::getStartStop(), TestMI::MsgStartStop::getStartStop(), TestMI::MsgFileRecord::getStreamIndex(), DeviceAPI::initDeviceEngine(), m_deviceAPI, TestMISettings::m_fileRecordName, m_fileSinks, m_settings, TestMISettings::m_useReverseAPI, Message::match(), DeviceAPI::startDeviceEngine(), DeviceAPI::stopDeviceEngine(), and webapiReverseSendStartStop().
Referenced by setSinkCenterFrequency().
 {
     if (MsgConfigureTestSource::match(message))
     {
         MsgConfigureTestSource& conf = (MsgConfigureTestSource&) message;
         qDebug() << "TestMI::handleMessage: MsgConfigureTestSource";
         bool success = applySettings(conf.getSettings(), conf.getForce());
         if (!success)
         {
             qDebug("TestMI::handleMessage: config error");
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "TestMI::handleMessage: MsgFileRecord: " << conf.getStartStop();
         int istream = conf.getStreamIndex();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSinks[istream]->setFileName(m_settings.m_fileRecordName + "_0.sdriq");
             } else {
                 m_fileSinks[istream]->genUniqueFileName(m_deviceAPI->getDeviceUID(), istream);
             }
             m_fileSinks[istream]->startRecording();
         }
         else
         {
             m_fileSinks[istream]->stopRecording();
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "TestMI::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void TestMI::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleMIMO.
Definition at line 88 of file testmi.cpp.
References DeviceAPI::addAncillarySink(), applySettings(), arg(), DeviceAPI::getDeviceUID(), m_deviceAPI, m_fileSinks, and m_settings.
Referenced by TestMI::MsgStartStop::MsgStartStop().
 {
     m_fileSinks.push_back(new FileRecord(QString("test_0_%1.sdriq").arg(m_deviceAPI->getDeviceUID())));
     m_fileSinks.push_back(new FileRecord(QString("test_1_%1.sdriq").arg(m_deviceAPI->getDeviceUID())));
     m_deviceAPI->addAncillarySink(m_fileSinks[0], 0);
     m_deviceAPI->addAncillarySink(m_fileSinks[1], 1);
     applySettings(m_settings, true);
 }
isRecording()
bool TestMI::isRecording (unsigned int istream) const
Definition at line 862 of file testmi.cpp.
References m_fileSinks.
Referenced by setSinkCenterFrequency().
 {
     if (istream < m_fileSinks.size()) {
         return m_fileSinks[istream]->isRecording();
     } else {
         return false;
     }
 }
networkManagerFinished
void TestMI::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 844 of file testmi.cpp.
Referenced by ~TestMI().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "TestMI::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("TestMI::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
serialize()
QByteArray TestMI::serialize () const virtual
Implements DeviceSampleMIMO.
Definition at line 140 of file testmi.cpp.
References m_settings, and TestMISettings::serialize().
Referenced by TestMI::MsgStartStop::MsgStartStop().
 {
     return m_settings.serialize();
 }
setMessageQueueToGUI()
virtual void TestMI::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleMIMO.
Definition at line 113 of file testmi.h.
References getDeviceDescription(), getSourceSampleRate(), and DeviceSampleMIMO::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSinkCenterFrequency()
virtual void TestMI::setSinkCenterFrequency (qint64 centerFrequency, int index) inline virtual
Implements DeviceSampleMIMO.
Definition at line 124 of file testmi.h.
References handleMessage(), isRecording(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) centerFrequency; (void) index; }
setSinkSampleRate()
virtual void TestMI::setSinkSampleRate (int sampleRate, int index) inline virtual
For when the sink sample rate is set externally.
Implements DeviceSampleMIMO.
Definition at line 122 of file testmi.h.
 { (void) sampleRate; (void) index; }
setSourceCenterFrequency()
void TestMI::setSourceCenterFrequency (qint64 centerFrequency, int index) virtual
Implements DeviceSampleMIMO.
Definition at line 190 of file testmi.cpp.
References TestMI::MsgConfigureTestSource::create(), DeviceSampleMIMO::m_guiMessageQueue, DeviceSampleMIMO::m_inputMessageQueue, m_settings, TestMISettings::m_streams, and MessageQueue::push().
Referenced by setSourceSampleRate().
 {
     TestMISettings settings = m_settings; // note: calls copy constructor
     if (index < (int) settings.m_streams.size())
     {
         settings.m_streams[index].m_centerFrequency = centerFrequency;
         MsgConfigureTestSource* message = MsgConfigureTestSource::create(settings, false);
         m_inputMessageQueue.push(message);
         if (m_guiMessageQueue)
         {
             MsgConfigureTestSource* messageToGUI = MsgConfigureTestSource::create(settings, false);
             m_guiMessageQueue->push(messageToGUI);
         }
     }
 }
setSourceSampleRate()
virtual void TestMI::setSourceSampleRate (int sampleRate, int index) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleMIMO.
Definition at line 117 of file testmi.h.
References getSourceCenterFrequency(), and setSourceCenterFrequency().
 { (void) sampleRate; (void) index; }
start()
bool TestMI::start () virtual
Implements DeviceSampleMIMO.
Definition at line 98 of file testmi.cpp.
References applySettings(), m_mutex, m_running, DeviceSampleMIMO::m_sampleSinkFifos, m_settings, TestMISettings::m_streams, m_testSourceThreads, and stop().
Referenced by TestMI::MsgStartStop::MsgStartStop().
 {
     qDebug("TestMI::start");
     QMutexLocker mutexLocker(&m_mutex);
     if (m_running) {
         stop();
     }
     m_testSourceThreads.push_back(new TestMIThread(&m_sampleSinkFifos[0], 0));
     m_testSourceThreads.back()->setSamplerate(m_settings.m_streams[0].m_sampleRate);
     m_testSourceThreads.back()->startStop(true);
     m_testSourceThreads.push_back(new TestMIThread(&m_sampleSinkFifos[1], 1));
     m_testSourceThreads.back()->setSamplerate(m_settings.m_streams[1].m_sampleRate);
     m_testSourceThreads.back()->startStop(true);
     mutexLocker.unlock();
     applySettings(m_settings, true);
     m_running = true;
     return true;
 }
stop()
void TestMI::stop () virtual
Implements DeviceSampleMIMO.
Definition at line 123 of file testmi.cpp.
References m_mutex, m_running, and m_testSourceThreads.
Referenced by TestMI::MsgStartStop::MsgStartStop(), start(), and ~TestMI().
 {
     qDebug("TestMI::stop");
     QMutexLocker mutexLocker(&m_mutex);
     std::vector<TestMIThread*>::iterator it = m_testSourceThreads.begin();
     for (; it != m_testSourceThreads.end(); ++it)
     {
         (*it)->startStop(false);
         (*it)->deleteLater();
     }
     m_testSourceThreads.clear();
     m_running = false;
 }
webapiFormatDeviceSettings()
void TestMI::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const TestMISettings & settings) private
Definition at line 672 of file testmi.cpp.
References SWGSDRangel::SWGTestMISettings::getFileRecordName(), SWGSDRangel::SWGTestMISettings::getReverseApiAddress(), SWGSDRangel::SWGTestMISettings::getStreams(), SWGSDRangel::SWGDeviceSettings::getTestMiSettings(), TestMISettings::m_fileRecordName, TestMISettings::m_reverseAPIAddress, TestMISettings::m_reverseAPIDeviceIndex, TestMISettings::m_reverseAPIPort, TestMISettings::m_streams, TestMISettings::m_useReverseAPI, SWGSDRangel::SWGTestMISettings::setFileRecordName(), SWGSDRangel::SWGTestMISettings::setReverseApiAddress(), SWGSDRangel::SWGTestMISettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGTestMISettings::setReverseApiPort(), and SWGSDRangel::SWGTestMISettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     std::vector<TestMIStreamSettings>::const_iterator it = settings.m_streams.begin();
     int istream = 0;
     for (; it != settings.m_streams.end(); ++it, istream++)
     {
         QList<SWGSDRangel::SWGTestMiStreamSettings*> *streams = response.getTestMiSettings()->getStreams();
         streams->append(new SWGSDRangel::SWGTestMiStreamSettings);
         streams->back()->init();
         streams->back()->setStreamIndex(istream);
         streams->back()->setCenterFrequency(it->m_centerFrequency);
         streams->back()->setFrequencyShift(it->m_frequencyShift);
         streams->back()->setSampleRate(it->m_sampleRate);
         streams->back()->setLog2Decim(it->m_log2Decim);
         streams->back()->setFcPos((int) it->m_fcPos);
         streams->back()->setSampleSizeIndex((int) it->m_sampleSizeIndex);
         streams->back()->setAmplitudeBits(it->m_amplitudeBits);
         streams->back()->setAutoCorrOptions((int) it->m_autoCorrOptions);
         streams->back()->setModulation((int) it->m_modulation);
         streams->back()->setModulationTone(it->m_modulationTone);
         streams->back()->setAmModulation(it->m_amModulation);
         streams->back()->setFmDeviation(it->m_fmDeviation);
         streams->back()->setDcFactor(it->m_dcFactor);
         streams->back()->setIFactor(it->m_iFactor);
         streams->back()->setQFactor(it->m_qFactor);
         streams->back()->setPhaseImbalance(it->m_phaseImbalance);
     }
     if (response.getTestMiSettings()->getFileRecordName()) {
         *response.getTestMiSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getTestMiSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getTestMiSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getTestMiSettings()->getReverseApiAddress()) {
         *response.getTestMiSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getTestMiSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getTestMiSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getTestMiSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReverseSendSettings()
void TestMI::webapiReverseSendSettings (const DeviceSettingsKeys & deviceSettingsKeys, const TestMISettings & settings, bool force) private
Definition at line 719 of file testmi.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGTestMISettings::getStreams(), SWGSDRangel::SWGDeviceSettings::getTestMiSettings(), TestMI::DeviceSettingsKeys::m_commonSettingsKeys, m_deviceAPI, TestMISettings::m_fileRecordName, m_networkManager, m_networkRequest, TestMISettings::m_reverseAPIAddress, TestMISettings::m_reverseAPIDeviceIndex, TestMISettings::m_reverseAPIPort, TestMISettings::m_streams, TestMI::DeviceSettingsKeys::m_streamsSettingsKeys, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGTestMISettings::setFileRecordName(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), and SWGSDRangel::SWGDeviceSettings::setTestMiSettings().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("TestSource"));
     swgDeviceSettings->setTestMiSettings(new SWGSDRangel::SWGTestMISettings());
     SWGSDRangel::SWGTestMISettings *swgTestMISettings = swgDeviceSettings->getTestMiSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     QList<QList<QString>>::const_iterator it = deviceSettingsKeys.m_streamsSettingsKeys.begin();
     int istream = 0;
     for (; it != deviceSettingsKeys.m_streamsSettingsKeys.end(); ++it, istream++)
     {
         if ((it->size() > 0) || force)
         {
             QList<SWGSDRangel::SWGTestMiStreamSettings*> *streams = swgTestMISettings->getStreams();
             streams->append(new SWGSDRangel::SWGTestMiStreamSettings);
             streams->back()->init();
             streams->back()->setStreamIndex(istream);
             const QList<QString>& streamSettingsKeys = *it;
             if (streamSettingsKeys.contains("centerFrequency") || force) {
                 streams->back()->setCenterFrequency(settings.m_streams[istream].m_centerFrequency);
             }
             if (streamSettingsKeys.contains("frequencyShift") || force) {
                 streams->back()->setFrequencyShift(settings.m_streams[istream].m_frequencyShift);
             }
             if (streamSettingsKeys.contains("sampleRate") || force) {
                 streams->back()->setSampleRate(settings.m_streams[istream].m_sampleRate);
             }
             if (streamSettingsKeys.contains("log2Decim") || force) {
                 streams->back()->setLog2Decim(settings.m_streams[istream].m_log2Decim);
             }
             if (streamSettingsKeys.contains("fcPos") || force) {
                 streams->back()->setFcPos((int) settings.m_streams[istream].m_fcPos);
             }
             if (streamSettingsKeys.contains("sampleSizeIndex") || force) {
                 streams->back()->setSampleSizeIndex(settings.m_streams[istream].m_sampleSizeIndex);
             }
             if (streamSettingsKeys.contains("amplitudeBits") || force) {
                 streams->back()->setAmplitudeBits(settings.m_streams[istream].m_amplitudeBits);
             }
             if (streamSettingsKeys.contains("autoCorrOptions") || force) {
                 streams->back()->setAutoCorrOptions((int) settings.m_streams[istream].m_sampleSizeIndex);
             }
             if (streamSettingsKeys.contains("modulation") || force) {
                 streams->back()->setModulation((int) settings.m_streams[istream].m_modulation);
             }
             if (streamSettingsKeys.contains("modulationTone")) {
                 streams->back()->setModulationTone(settings.m_streams[istream].m_modulationTone);
             }
             if (streamSettingsKeys.contains("amModulation") || force) {
                 streams->back()->setAmModulation(settings.m_streams[istream].m_amModulation);
             };
             if (streamSettingsKeys.contains("fmDeviation") || force) {
                 streams->back()->setFmDeviation(settings.m_streams[istream].m_fmDeviation);
             };
             if (streamSettingsKeys.contains("dcFactor") || force) {
                 streams->back()->setDcFactor(settings.m_streams[istream].m_dcFactor);
             };
             if (streamSettingsKeys.contains("iFactor") || force) {
                 streams->back()->setIFactor(settings.m_streams[istream].m_iFactor);
             };
             if (streamSettingsKeys.contains("qFactor") || force) {
                 streams->back()->setQFactor(settings.m_streams[istream].m_qFactor);
             };
             if (streamSettingsKeys.contains("phaseImbalance") || force) {
                 streams->back()->setPhaseImbalance(settings.m_streams[istream].m_phaseImbalance);
             };
         }
     }
     if (deviceSettingsKeys.m_commonSettingsKeys.contains("fileRecordName") || force) {
         swgTestMISettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void TestMI::webapiReverseSendStartStop (bool start) private
Definition at line 816 of file testmi.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, TestMISettings::m_reverseAPIAddress, TestMISettings::m_reverseAPIDeviceIndex, TestMISettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("TestSource"));
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int TestMI::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleMIMO.
Definition at line 535 of file testmi.cpp.
References TestMI::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleMIMO::m_guiMessageQueue, DeviceSampleMIMO::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSinkCenterFrequency().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int TestMI::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleMIMO.
Definition at line 526 of file testmi.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSinkCenterFrequency().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int TestMI::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleMIMO.
Definition at line 554 of file testmi.cpp.
References SWGSDRangel::SWGDeviceSettings::getTestMiSettings(), SWGSDRangel::SWGTestMISettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setTestMiSettings(), and webapiFormatDeviceSettings().
Referenced by setSinkCenterFrequency().
 {
     (void) errorMessage;
     response.setTestMiSettings(new SWGSDRangel::SWGTestMISettings());
     response.getTestMiSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int TestMI::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleMIMO.
Definition at line 565 of file testmi.cpp.
References arg(), TestMIStreamSettings::AutoCorrLast, TestMI::MsgConfigureTestSource::create(), SWGSDRangel::SWGTestMISettings::getFileRecordName(), SWGSDRangel::SWGTestMISettings::getReverseApiAddress(), SWGSDRangel::SWGTestMISettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGTestMISettings::getReverseApiPort(), SWGSDRangel::SWGTestMISettings::getStreams(), SWGSDRangel::SWGDeviceSettings::getTestMiSettings(), SWGSDRangel::SWGTestMISettings::getUseReverseApi(), TestMISettings::m_fileRecordName, DeviceSampleMIMO::m_guiMessageQueue, DeviceSampleMIMO::m_inputMessageQueue, TestMISettings::m_reverseAPIAddress, TestMISettings::m_reverseAPIDeviceIndex, TestMISettings::m_reverseAPIPort, m_settings, TestMISettings::m_streams, TestMISettings::m_useReverseAPI, TestMIStreamSettings::ModulationLast, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setSinkCenterFrequency().
 {
     (void) errorMessage;
     TestMISettings settings = m_settings;
     if (deviceSettingsKeys.contains("streams"))
     {
         QList<SWGSDRangel::SWGTestMiStreamSettings*> *streamsSettings = response.getTestMiSettings()->getStreams();
         QList<SWGSDRangel::SWGTestMiStreamSettings*>::const_iterator it = streamsSettings->begin();
         for (; it != streamsSettings->end(); ++it)
         {
             int istream = (*it)->getStreamIndex();
             if (deviceSettingsKeys.contains(tr("streams[%1].centerFrequency").arg(istream))) {
                 settings.m_streams[istream].m_centerFrequency = (*it)->getCenterFrequency();
             }
             if (deviceSettingsKeys.contains(tr("streams[%1].frequencyShift").arg(istream))) {
                 settings.m_streams[istream].m_frequencyShift = (*it)->getFrequencyShift();
             }
             if (deviceSettingsKeys.contains(tr("streams[%1].sampleRate").arg(istream))) {
                 settings.m_streams[istream].m_sampleRate = (*it)->getSampleRate();
             }
             if (deviceSettingsKeys.contains(tr("streams[%1].log2Decim").arg(istream))) {
                 settings.m_streams[istream].m_log2Decim = (*it)->getLog2Decim();
             }
             if (deviceSettingsKeys.contains(tr("streams[%1].fcPos").arg(istream))) {
                 int fcPos = (*it)->getFcPos();
                 fcPos = fcPos < 0 ? 0 : fcPos > 2 ? 2 : fcPos;
                 settings.m_streams[istream].m_fcPos = (TestMIStreamSettings::fcPos_t) fcPos;
             }
             if (deviceSettingsKeys.contains(tr("streams[%1].sampleSizeIndex").arg(istream))) {
                 int sampleSizeIndex = (*it)->getSampleSizeIndex();
                 sampleSizeIndex = sampleSizeIndex < 0 ? 0 : sampleSizeIndex > 1 ? 2 : sampleSizeIndex;
                 settings.m_streams[istream].m_sampleSizeIndex = sampleSizeIndex;
             }
             if (deviceSettingsKeys.contains(tr("streams[%1].amplitudeBits").arg(istream))) {
                 settings.m_streams[istream].m_amplitudeBits = (*it)->getAmplitudeBits();
             }
             if (deviceSettingsKeys.contains(tr("streams[%1].autoCorrOptions").arg(istream))) {
                 int autoCorrOptions = (*it)->getAutoCorrOptions();
                 autoCorrOptions = autoCorrOptions < 0 ? 0 : autoCorrOptions >= TestMIStreamSettings::AutoCorrLast ? TestMIStreamSettings::AutoCorrLast-1 : autoCorrOptions;
                 settings.m_streams[istream].m_sampleSizeIndex = (TestMIStreamSettings::AutoCorrOptions) autoCorrOptions;
             }
             if (deviceSettingsKeys.contains(tr("streams[%1].modulation").arg(istream))) {
                 int modulation = (*it)->getModulation();
                 modulation = modulation < 0 ? 0 : modulation >= TestMIStreamSettings::ModulationLast ? TestMIStreamSettings::ModulationLast-1 : modulation;
                 settings.m_streams[istream].m_modulation = (TestMIStreamSettings::Modulation) modulation;
             }
             if (deviceSettingsKeys.contains(tr("streams[%1].modulationTone").arg(istream))) {
                 settings.m_streams[istream].m_modulationTone = (*it)->getModulationTone();
             }
             if (deviceSettingsKeys.contains(tr("streams[%1].amModulation").arg(istream))) {
                 settings.m_streams[istream].m_amModulation = (*it)->getAmModulation();
             };
             if (deviceSettingsKeys.contains(tr("streams[%1].fmDeviation").arg(istream))) {
                 settings.m_streams[istream].m_fmDeviation = (*it)->getFmDeviation();
             };
             if (deviceSettingsKeys.contains(tr("streams[%1].dcFactor").arg(istream))) {
                 settings.m_streams[istream].m_dcFactor = (*it)->getDcFactor();
             };
             if (deviceSettingsKeys.contains(tr("streams[%1].iFactor").arg(istream))) {
                 settings.m_streams[istream].m_iFactor = (*it)->getIFactor();
             };
             if (deviceSettingsKeys.contains(tr("streams[%1].qFactor").arg(istream))) {
                 settings.m_streams[istream].m_qFactor = (*it)->getQFactor();
             };
             if (deviceSettingsKeys.contains(tr("streams[%1].phaseImbalance").arg(istream))) {
                 settings.m_streams[istream].m_phaseImbalance = (*it)->getPhaseImbalance();
             };
         }
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getTestMiSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getTestMiSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getTestMiSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getTestMiSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getTestMiSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureTestSource *msg = MsgConfigureTestSource::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureTestSource *msgToGUI = MsgConfigureTestSource::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_deviceAPI
DeviceAPI* TestMI::m_deviceAPI private
Definition at line 156 of file testmi.h.
Referenced by applySettings(), handleMessage(), init(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~TestMI().
m_deviceDescription
QString TestMI::m_deviceDescription private
Definition at line 161 of file testmi.h.
Referenced by getDeviceDescription().
m_fileSinks
std::vector<FileRecord *> TestMI::m_fileSinks private
File sinks to record device I/Q output.
Definition at line 157 of file testmi.h.
Referenced by applySettings(), handleMessage(), init(), isRecording(), and ~TestMI().
m_masterTimer
const QTimer& TestMI::m_masterTimer private
Definition at line 163 of file testmi.h.
m_mutex
QMutex TestMI::m_mutex private
Definition at line 158 of file testmi.h.
Referenced by start(), and stop().
m_networkManager
QNetworkAccessManager* TestMI::m_networkManager private
Definition at line 164 of file testmi.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~TestMI().
m_networkRequest
QNetworkRequest TestMI::m_networkRequest private
Definition at line 165 of file testmi.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool TestMI::m_running private
Definition at line 162 of file testmi.h.
Referenced by start(), stop(), and ~TestMI().
m_settings
TestMISettings TestMI::m_settings private
Definition at line 159 of file testmi.h.
Referenced by applySettings(), deserialize(), getSourceCenterFrequency(), getSourceSampleRate(), handleMessage(), init(), serialize(), setSourceCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_testSourceThreads
std::vector<TestMIThread*> TestMI::m_testSourceThreads private
Definition at line 160 of file testmi.h.
Referenced by applySettings(), start(), and stop().
The documentation for this class was generated from the following files:
plugins/samplemimo/testmi/testmi.h
plugins/samplemimo/testmi/testmi.cpp