SDRAngel: XTRXOutput::MsgReportStreamInfo Class Reference
XTRXOutput::MsgReportStreamInfo Class Reference
#include <xtrxoutput.h>
Public Member Functions
bool getSuccess () const
bool getActive () const
uint32_t getFifoFilledCount () const
uint32_t getFifoSize () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportStreamInfo * create (bool success, bool active, uint32_t fifoFilledCount, uint32_t fifoSize)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportStreamInfo (bool success, bool active, uint32_t fifoFilledCount, uint32_t fifoSize)
Private Attributes
bool m_success
bool m_active
Indicates whether the stream is currently active.
uint32_t m_fifoFilledCount
Number of samples in FIFO buffer.
uint32_t m_fifoSize
Size of FIFO buffer.
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 109 of file xtrxoutput.h.
Constructor & Destructor Documentation
MsgReportStreamInfo()
XTRXOutput::MsgReportStreamInfo::MsgReportStreamInfo (bool success, bool active, uint32_t fifoFilledCount, uint32_t fifoSize) inline private
Definition at line 140 of file xtrxoutput.h.
                   :
             Message(),
             m_success(success),
             m_active(active),
             m_fifoFilledCount(fifoFilledCount),
             m_fifoSize(fifoSize)
         { }
Member Function Documentation
create()
static MsgReportStreamInfo* XTRXOutput::MsgReportStreamInfo::create (bool success, bool active, uint32_t fifoFilledCount, uint32_t fifoSize) inline static
Definition at line 118 of file xtrxoutput.h.
Referenced by XTRXOutput::handleMessage().
         {
             return new MsgReportStreamInfo(
                         success,
                         active,
                         fifoFilledCount,
                         fifoSize
                         );
         }
getActive()
bool XTRXOutput::MsgReportStreamInfo::getActive () const inline
Definition at line 114 of file xtrxoutput.h.
Referenced by XTRXOutputGUI::handleMessage().
 { return m_active; }
getFifoFilledCount()
uint32_t XTRXOutput::MsgReportStreamInfo::getFifoFilledCount () const inline
Definition at line 115 of file xtrxoutput.h.
Referenced by XTRXOutputGUI::handleMessage().
 { return m_fifoFilledCount; }
getFifoSize()
uint32_t XTRXOutput::MsgReportStreamInfo::getFifoSize () const inline
Definition at line 116 of file xtrxoutput.h.
Referenced by XTRXOutputGUI::handleMessage().
 { return m_fifoSize; }
getSuccess()
bool XTRXOutput::MsgReportStreamInfo::getSuccess () const inline
Definition at line 113 of file xtrxoutput.h.
Referenced by XTRXOutputGUI::handleMessage().
 { return m_success; }
Member Data Documentation
m_active
bool XTRXOutput::MsgReportStreamInfo::m_active private
Indicates whether the stream is currently active.
Definition at line 136 of file xtrxoutput.h.
m_fifoFilledCount
uint32_t XTRXOutput::MsgReportStreamInfo::m_fifoFilledCount private
Number of samples in FIFO buffer.
Definition at line 137 of file xtrxoutput.h.
m_fifoSize
uint32_t XTRXOutput::MsgReportStreamInfo::m_fifoSize private
Size of FIFO buffer.
Definition at line 138 of file xtrxoutput.h.
m_success
bool XTRXOutput::MsgReportStreamInfo::m_success private
Definition at line 134 of file xtrxoutput.h.
The documentation for this class was generated from the following file:
plugins/samplesink/xtrxoutput/xtrxoutput.h