SDRAngel: AirspyHFThread Class Reference
AirspyHFThread Class Reference
#include <airspyhfthread.h>
Inherits QThread.
Public Member Functions
AirspyHFThread (airspyhf_device_t *dev, SampleSinkFifo *sampleFifo, QObject *parent=0)
~AirspyHFThread ()
void startWork ()
void stopWork ()
void setSamplerate (uint32_t samplerate)
void setLog2Decimation (unsigned int log2_decim)
Private Member Functions
void run ()
void callback (const float *buf, qint32 len)
Static Private Member Functions
static int rx_callback (airspyhf_transfer_t *transfer)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
airspyhf_device_t * m_dev
qint16 m_buf [2 *AIRSPYHF_BLOCKSIZE]
SampleVector m_convertBuffer
SampleSinkFifo * m_sampleFifo
int m_samplerate
unsigned int m_log2Decim
DecimatorsFI m_decimators
Static Private Attributes
static AirspyHFThread * m_this = 0
Detailed Description
Definition at line 31 of file airspyhfthread.h.
Constructor & Destructor Documentation
AirspyHFThread()
AirspyHFThread::AirspyHFThread (airspyhf_device_t * dev, SampleSinkFifo * sampleFifo, QObject * parent = 0)
Definition at line 27 of file airspyhfthread.cpp.
References AIRSPYHF_BLOCKSIZE, m_buf, and m_this.
                                                                                                   :
     QThread(parent),
     m_running(false),
     m_dev(dev),
     m_convertBuffer(AIRSPYHF_BLOCKSIZE),
     m_sampleFifo(sampleFifo),
     m_samplerate(10),
     m_log2Decim(0)
 {
     memset((char*) m_buf, 0, 2*AIRSPYHF_BLOCKSIZE*sizeof(qint16));
     m_this = this;
 }
~AirspyHFThread()
AirspyHFThread::~AirspyHFThread ()
Definition at line 40 of file airspyhfthread.cpp.
References m_this, and stopWork().
 {
     stopWork();
     m_this = 0;
 }
Member Function Documentation
callback()
void AirspyHFThread::callback (const float * buf, qint32 len) private
Definition at line 105 of file airspyhfthread.cpp.
References DecimatorsFI::decimate1(), DecimatorsFI::decimate16_cen(), DecimatorsFI::decimate2_cen(), DecimatorsFI::decimate32_cen(), DecimatorsFI::decimate4_cen(), DecimatorsFI::decimate64_cen(), DecimatorsFI::decimate8_cen(), m_convertBuffer, m_decimators, m_log2Decim, m_sampleFifo, and SampleSinkFifo::write().
Referenced by rx_callback().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     switch (m_log2Decim)
     {
     case 0:
         m_decimators.decimate1(&it, buf, len);
         break;
     case 1:
         m_decimators.decimate2_cen(&it, buf, len);
         break;
     case 2:
         m_decimators.decimate4_cen(&it, buf, len);
         break;
     case 3:
         m_decimators.decimate8_cen(&it, buf, len);
         break;
     case 4:
         m_decimators.decimate16_cen(&it, buf, len);
         break;
     case 5:
         m_decimators.decimate32_cen(&it, buf, len);
         break;
     case 6:
         m_decimators.decimate64_cen(&it, buf, len);
         break;
     default:
         break;
     }
     m_sampleFifo->write(m_convertBuffer.begin(), it);
 }
run()
void AirspyHFThread::run () private
Definition at line 72 of file airspyhfthread.cpp.
References m_dev, m_running, m_startWaiter, and rx_callback().
 {
     airspyhf_error rc;
     m_running = true;
     m_startWaiter.wakeAll();
     rc = (airspyhf_error) airspyhf_start(m_dev, rx_callback, 0);
     if (rc != AIRSPYHF_SUCCESS)
     {
         qCritical("AirspyHFFThread::run: failed to start Airspy HF Rx");
     }
     else
     {
         while ((m_running) && (airspyhf_is_streaming(m_dev) != 0))
         {
             sleep(1);
         }
     }
     rc = (airspyhf_error) airspyhf_stop(m_dev);
     if (rc == AIRSPYHF_SUCCESS) {
         qDebug("AirspyHFFThread::run: stopped Airspy HF Rx");
     } else {
         qDebug("AirspyHFFThread::run: failed to stop Airspy HF Rx");
     }
     m_running = false;
 }
rx_callback()
int AirspyHFThread::rx_callback (airspyhf_transfer_t * transfer) static private
Definition at line 140 of file airspyhfthread.cpp.
References callback(), and m_this.
Referenced by run().
 {
     qint32 nbIAndQ = transfer->sample_count * 2;
     m_this->callback((float *) transfer->samples, nbIAndQ);
     return 0;
 }
setLog2Decimation()
void AirspyHFThread::setLog2Decimation (unsigned int log2_decim)
Definition at line 67 of file airspyhfthread.cpp.
References m_log2Decim.
Referenced by AirspyHFInput::applySettings(), and AirspyHFInput::start().
 {
     m_log2Decim = log2_decim;
 }
setSamplerate()
void AirspyHFThread::setSamplerate (uint32_t samplerate)
Definition at line 62 of file airspyhfthread.cpp.
References m_samplerate.
Referenced by AirspyHFInput::applySettings(), and AirspyHFInput::start().
 {
     m_samplerate = samplerate;
 }
startWork()
void AirspyHFThread::startWork ()
Definition at line 46 of file airspyhfthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by AirspyHFInput::start().
 {
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void AirspyHFThread::stopWork ()
Definition at line 55 of file airspyhfthread.cpp.
References m_running.
Referenced by AirspyHFInput::stop(), and ~AirspyHFThread().
 {
     qDebug("AirspyThread::stopWork");
     m_running = false;
     wait();
 }
Member Data Documentation
m_buf
qint16 AirspyHFThread::m_buf[2 *AIRSPYHF_BLOCKSIZE] private
Definition at line 49 of file airspyhfthread.h.
Referenced by AirspyHFThread().
m_convertBuffer
SampleVector AirspyHFThread::m_convertBuffer private
Definition at line 50 of file airspyhfthread.h.
Referenced by callback().
m_decimators
DecimatorsFI AirspyHFThread::m_decimators private
Definition at line 57 of file airspyhfthread.h.
Referenced by callback().
m_dev
airspyhf_device_t* AirspyHFThread::m_dev private
Definition at line 48 of file airspyhfthread.h.
Referenced by run().
m_log2Decim
unsigned int AirspyHFThread::m_log2Decim private
Definition at line 54 of file airspyhfthread.h.
Referenced by callback(), and setLog2Decimation().
m_running
bool AirspyHFThread::m_running private
Definition at line 46 of file airspyhfthread.h.
Referenced by run(), startWork(), and stopWork().
m_sampleFifo
SampleSinkFifo* AirspyHFThread::m_sampleFifo private
Definition at line 51 of file airspyhfthread.h.
Referenced by callback().
m_samplerate
int AirspyHFThread::m_samplerate private
Definition at line 53 of file airspyhfthread.h.
Referenced by setSamplerate().
m_startWaiter
QWaitCondition AirspyHFThread::m_startWaiter private
Definition at line 45 of file airspyhfthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex AirspyHFThread::m_startWaitMutex private
Definition at line 44 of file airspyhfthread.h.
Referenced by startWork().
m_this
AirspyHFThread * AirspyHFThread::m_this = 0 static private
Definition at line 55 of file airspyhfthread.h.
Referenced by AirspyHFThread(), rx_callback(), and ~AirspyHFThread().
The documentation for this class was generated from the following files:
plugins/samplesource/airspyhf/airspyhfthread.h
plugins/samplesource/airspyhf/airspyhfthread.cpp