SDRAngel: LimeSDROutputThread Class Reference
LimeSDROutputThread Class Reference
#include <limesdroutputthread.h>
Public Member Functions
LimeSDROutputThread (lms_stream_t *stream, SampleSourceFifo *sampleFifo, QObject *parent=0)
~LimeSDROutputThread ()
virtual void startWork ()
virtual void stopWork ()
virtual void setDeviceSampleRate (int sampleRate)
virtual bool isRunning ()
void setLog2Interpolation (unsigned int log2_ioterp)
Private Member Functions
void run ()
void callback (qint16 *buf, qint32 len)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
lms_stream_t * m_stream
qint16 m_buf [2 *LIMESDROUTPUT_BLOCKSIZE]
SampleSourceFifo * m_sampleFifo
unsigned int m_log2Interp
Interpolators< qint16, SDR_TX_SAMP_SZ, 12 > m_interpolators
Detailed Description
Definition at line 33 of file limesdroutputthread.h.
Constructor & Destructor Documentation
LimeSDROutputThread()
LimeSDROutputThread::LimeSDROutputThread (lms_stream_t * stream, SampleSourceFifo * sampleFifo, QObject * parent = 0)
Definition at line 24 of file limesdroutputthread.cpp.
References LIMESDROUTPUT_BLOCKSIZE, and m_buf.
                                                                                                             :
     QThread(parent),
     m_running(false),
     m_stream(stream),
     m_sampleFifo(sampleFifo),
     m_log2Interp(0)
 {
     std::fill(m_buf, m_buf + 2*LIMESDROUTPUT_BLOCKSIZE, 0);
 }
~LimeSDROutputThread()
LimeSDROutputThread::~LimeSDROutputThread ()
Definition at line 34 of file limesdroutputthread.cpp.
References stopWork().
 {
     stopWork();
 }
Member Function Documentation
callback()
void LimeSDROutputThread::callback (qint16 * buf, qint32 len) private
Definition at line 109 of file limesdroutputthread.cpp.
References Interpolators< T, SdrBits, OutputBits >::interpolate1(), Interpolators< T, SdrBits, OutputBits >::interpolate16_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate2_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate32_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate4_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate64_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate8_cen(), m_interpolators, m_log2Interp, m_sampleFifo, and SampleSourceFifo::readAdvance().
Referenced by run().
 {
     SampleVector::iterator beginRead;
     m_sampleFifo->readAdvance(beginRead, len/(1<<m_log2Interp));
     beginRead -= len;
     if (m_log2Interp == 0)
     {
         m_interpolators.interpolate1(&beginRead, buf, len*2);
     }
     else
     {
         switch (m_log2Interp)
         {
         case 1:
             m_interpolators.interpolate2_cen(&beginRead, buf, len*2);
             break;
         case 2:
             m_interpolators.interpolate4_cen(&beginRead, buf, len*2);
             break;
         case 3:
             m_interpolators.interpolate8_cen(&beginRead, buf, len*2);
             break;
         case 4:
             m_interpolators.interpolate16_cen(&beginRead, buf, len*2);
             break;
         case 5:
             m_interpolators.interpolate32_cen(&beginRead, buf, len*2);
             break;
         case 6:
             m_interpolators.interpolate64_cen(&beginRead, buf, len*2);
             break;
         default:
             break;
         }
     }
 }
isRunning()
virtual bool LimeSDROutputThread::isRunning () inline virtual
Implements DeviceLimeSDRShared::ThreadInterface.
Definition at line 44 of file limesdroutputthread.h.
References m_running, and setLog2Interpolation().
Referenced by LimeSDROutput::applySettings().
 { return m_running; }
run()
void LimeSDROutputThread::run () private
Definition at line 77 of file limesdroutputthread.cpp.
References callback(), LIMESDROUTPUT_BLOCKSIZE, m_buf, m_running, m_startWaiter, and m_stream.
 {
     int res;
     lms_stream_meta_t metadata;          //Use metadata for additional control over sample receive function behaviour
     metadata.flushPartialPacket = false; //Do not discard data remainder when read size differs from packet size
     metadata.waitForTimestamp = false;   //Do not wait for specific timestamps
     m_running = true;
     m_startWaiter.wakeAll();
     while (m_running)
     {
         callback(m_buf, LIMESDROUTPUT_BLOCKSIZE);
         res = LMS_SendStream(m_stream, (void *) m_buf, LIMESDROUTPUT_BLOCKSIZE, &metadata, 1000000);
         if (res < 0)
         {
             qCritical("LimeSDROutputThread::run write error: %s", strerror(errno));
             break;
         }
         else if (res != LIMESDROUTPUT_BLOCKSIZE)
         {
             qDebug("LimeSDROutputThread::run written %d/%d samples", res, LIMESDROUTPUT_BLOCKSIZE);
         }
     }
     m_running = false;
 }
setDeviceSampleRate()
virtual void LimeSDROutputThread::setDeviceSampleRate (int sampleRate) inline virtual
Implements DeviceLimeSDRShared::ThreadInterface.
Definition at line 43 of file limesdroutputthread.h.
 { (void) sampleRate; }
setLog2Interpolation()
void LimeSDROutputThread::setLog2Interpolation (unsigned int log2_ioterp)
Definition at line 72 of file limesdroutputthread.cpp.
References m_log2Interp.
Referenced by LimeSDROutput::applySettings(), isRunning(), and LimeSDROutput::start().
 {
     m_log2Interp = log2_interp;
 }
startWork()
void LimeSDROutputThread::startWork () virtual
Implements DeviceLimeSDRShared::ThreadInterface.
Definition at line 39 of file limesdroutputthread.cpp.
References m_running, m_startWaiter, m_startWaitMutex, and m_stream.
Referenced by LimeSDROutput::applySettings(), and LimeSDROutput::start().
 {
     if (m_running) return; // return if running already
     if (LMS_StartStream(m_stream) < 0) {
         qCritical("LimeSDROutputThread::startWork: could not start stream");
     } else {
         usleep(50000);
         qDebug("LimeSDROutputThread::startWork: stream started");
     }
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void LimeSDROutputThread::stopWork () virtual
Implements DeviceLimeSDRShared::ThreadInterface.
Definition at line 57 of file limesdroutputthread.cpp.
References m_running, and m_stream.
Referenced by LimeSDROutput::applySettings(), LimeSDROutput::stop(), and ~LimeSDROutputThread().
 {
     if (!m_running) return; // return if not running
     m_running = false;
     wait();
     if (LMS_StopStream(m_stream) < 0) {
         qCritical("LimeSDROutputThread::stopWork: could not stop stream");
     } else {
         usleep(50000);
         qDebug("LimeSDROutputThread::stopWork: stream stopped");
     }
 }
Member Data Documentation
m_buf
qint16 LimeSDROutputThread::m_buf[2 *LIMESDROUTPUT_BLOCKSIZE] private
Definition at line 53 of file limesdroutputthread.h.
Referenced by LimeSDROutputThread(), and run().
m_interpolators
Interpolators<qint16, SDR_TX_SAMP_SZ, 12> LimeSDROutputThread::m_interpolators private
Definition at line 58 of file limesdroutputthread.h.
Referenced by callback().
m_log2Interp
unsigned int LimeSDROutputThread::m_log2Interp private
Definition at line 56 of file limesdroutputthread.h.
Referenced by callback(), and setLog2Interpolation().
m_running
bool LimeSDROutputThread::m_running private
Definition at line 50 of file limesdroutputthread.h.
Referenced by isRunning(), run(), startWork(), and stopWork().
m_sampleFifo
SampleSourceFifo* LimeSDROutputThread::m_sampleFifo private
Definition at line 54 of file limesdroutputthread.h.
Referenced by callback().
m_startWaiter
QWaitCondition LimeSDROutputThread::m_startWaiter private
Definition at line 49 of file limesdroutputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex LimeSDROutputThread::m_startWaitMutex private
Definition at line 48 of file limesdroutputthread.h.
Referenced by startWork().
m_stream
lms_stream_t* LimeSDROutputThread::m_stream private
Definition at line 52 of file limesdroutputthread.h.
Referenced by run(), startWork(), and stopWork().
The documentation for this class was generated from the following files:
plugins/samplesink/limesdroutput/limesdroutputthread.h
plugins/samplesink/limesdroutput/limesdroutputthread.cpp