SDRAngel: NFMDemod Class Reference
NFMDemod Class Reference
#include <nfmdemod.h>
Classes
struct MagSqLevelsStore
class MsgConfigureChannelizer
class MsgConfigureNFMDemod
class MsgReportCTCSSFreq
Public Member Functions
NFMDemod (DeviceAPI *deviceAPI)
~NFMDemod ()
virtual void destroy ()
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool po)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
const Real * getCtcssToneSet (int &nbTones) const
void setSelectedCtcssIndex (int selectedCtcssIndex)
Real getMag ()
bool getSquelchOpen () const
void getMagSqLevels (double &avg, double &peak, int &nbSamples)
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.nfmdemod"
static const QString m_channelId = "NFMDemod"
Private Types
enum RateState { RSInitialFill, RSRunning }
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const NFMDemodSettings &settings, bool force=false)
void applyAudioSampleRate (int sampleRate)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const NFMDemodSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const NFMDemodSettings &settings, bool force)
void processOneSample (Complex &ci)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
int m_inputSampleRate
int m_inputFrequencyOffset
NFMDemodSettings m_settings
uint32_t m_audioSampleRate
float m_discriCompensation
compensation factor that depends on audio rate (1 for 48 kS/s)
bool m_running
NCO m_nco
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
Lowpass< Real > m_ctcssLowpass
Bandpass< Real > m_bandpass
Lowpass< Real > m_lowpass
CTCSSDetector m_ctcssDetector
int m_ctcssIndex
int m_ctcssIndexSelected
int m_sampleCount
int m_squelchCount
int m_squelchGate
Real m_squelchLevel
bool m_squelchOpen
bool m_afSquelchOpen
double m_magsq
displayed averaged value
double m_magsqSum
double m_magsqPeak
int m_magsqCount
MagSqLevelsStore m_magSqLevelStore
MovingAverageUtil< Real, double, 32 > m_movingAverage
AFSquelch m_afSquelch
Real m_agcLevel
DoubleBufferFIFO< Real > m_squelchDelayLine
AudioVector m_audioBuffer
uint m_audioBufferFill
AudioFifo m_audioFifo
QMutex m_settingsMutex
PhaseDiscriminators m_phaseDiscri
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Static Private Attributes
static const int m_udpBlockSize = 512
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 50 of file nfmdemod.h.
Member Enumeration Documentation
RateState
enum NFMDemod::RateState private
Enumerator
RSInitialFill
RSRunning
Definition at line 203 of file nfmdemod.h.
                    {
         RSInitialFill,
         RSRunning
     };
Constructor & Destructor Documentation
NFMDemod()
NFMDemod::NFMDemod (DeviceAPI * deviceAPI)
Definition at line 55 of file nfmdemod.cpp.
References AudioDeviceManager::addAudioSink(), DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), m_afSquelch, m_agcLevel, m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_channelId, m_ctcssDetector, m_discriCompensation, CTCSSDetector::setCoefficients(), AFSquelch::setCoefficients(), and sqrt().
Referenced by NFMDemod::MsgReportCTCSSFreq::MsgReportCTCSSFreq().
                                       :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(devieAPI),
         m_inputSampleRate(48000),
         m_inputFrequencyOffset(0),
         m_running(false),
         m_ctcssIndex(0),
         m_sampleCount(0),
         m_squelchCount(0),
         m_squelchGate(4800),
         m_squelchLevel(-990),
         m_squelchOpen(false),
         m_afSquelchOpen(false),
         m_magsq(0.0f),
         m_magsqSum(0.0f),
         m_magsqPeak(0.0f),
         m_magsqCount(0),
         m_afSquelch(),
         m_squelchDelayLine(24000),
         m_audioFifo(48000),
         m_settingsMutex(QMutex::Recursive)
 {
     qDebug("NFMDemod::NFMDemod");
     setObjectName(m_channelId);
     m_audioBuffer.resize(1<<14);
     m_audioBufferFill = 0;
     m_agcLevel = 1.0;
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSink(&m_audioFifo, getInputMessageQueue());
     m_audioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getOutputSampleRate();
     m_discriCompensation = (m_audioSampleRate/48000.0f);
     m_discriCompensation *= sqrt(m_discriCompensation);
     m_ctcssDetector.setCoefficients(m_audioSampleRate/16, m_audioSampleRate/8.0f); // 0.5s / 2 Hz resolution
     m_afSquelch.setCoefficients(m_audioSampleRate/2000, 600, m_audioSampleRate, 200, 0, afSqTones); // 0.5ms test period, 300ms average span, audio SR, 100ms attack, no decay
     m_ctcssLowpass.create(301, m_audioSampleRate, 250.0);
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~NFMDemod()
NFMDemod::~NFMDemod ()
Definition at line 107 of file nfmdemod.cpp.
References DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo, m_channelizer, m_deviceAPI, m_networkManager, m_threadedChannelizer, networkManagerFinished(), AudioDeviceManager::removeAudioSink(), DeviceAPI::removeChannelSink(), and DeviceAPI::removeChannelSinkAPI().
Referenced by NFMDemod::MsgReportCTCSSFreq::MsgReportCTCSSFreq().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_audioFifo);
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
 }
Member Function Documentation
applyAudioSampleRate()
void NFMDemod::applyAudioSampleRate (int sampleRate) private
Definition at line 444 of file nfmdemod.cpp.
References Lowpass< Type >::create(), Bandpass< Type >::create(), Interpolator::create(), NFMDemod::MsgConfigureChannelizer::create(), NFMDemodSettings::m_afBandwidth, m_afSquelch, m_bandpass, m_ctcssDetector, m_ctcssLowpass, NFMDemodSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_lowpass, NFMDemodSettings::m_rfBandwidth, m_settings, m_settingsMutex, m_squelchCount, NFMDemodSettings::m_squelchGate, m_squelchGate, MessageQueue::push(), CTCSSDetector::setCoefficients(), and AFSquelch::setCoefficients().
Referenced by applySettings(), and handleMessage().
 {
     qDebug("NFMDemod::applyAudioSampleRate: %d", sampleRate);
     MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
             sampleRate, m_settings.m_inputFrequencyOffset);
     m_inputMessageQueue.push(channelConfigMsg);
     m_settingsMutex.lock();
     m_interpolator.create(16, m_inputSampleRate, m_settings.m_rfBandwidth / 2.2f);
     m_interpolatorDistanceRemain = 0;
     m_interpolatorDistance = (Real) m_inputSampleRate / (Real) sampleRate;
     m_ctcssLowpass.create(301, sampleRate, 250.0);
     m_bandpass.create(301, sampleRate, 300.0, m_settings.m_afBandwidth);
     m_lowpass.create(301, sampleRate, m_settings.m_afBandwidth);
     m_squelchGate = (sampleRate / 100) * m_settings.m_squelchGate; // gate is given in 10s of ms at 48000 Hz audio sample rate
     m_squelchCount = 0; // reset squelch open counter
     m_ctcssDetector.setCoefficients(sampleRate/16, sampleRate/8.0f); // 0.5s / 2 Hz resolution
     if (sampleRate < 16000) {
         m_afSquelch.setCoefficients(sampleRate/2000, 600, sampleRate, 200, 0, afSqTones_lowrate); // 0.5ms test period, 300ms average span, audio SR, 100ms attack, no decay
     } else {
         m_afSquelch.setCoefficients(sampleRate/2000, 600, sampleRate, 200, 0, afSqTones); // 0.5ms test period, 300ms average span, audio SR, 100ms attack, no decay
     }
     m_discriCompensation = (sampleRate/48000.0f);
     m_discriCompensation *= sqrt(m_discriCompensation);
     m_phaseDiscri.setFMScaling(sampleRate / static_cast<float>(m_settings.m_fmDeviation));
     m_audioFifo.setSize(sampleRate);
     m_squelchDelayLine.resize(sampleRate/2);
     m_settingsMutex.unlock();
     m_audioSampleRate = sampleRate;
 }
applyChannelSettings()
void NFMDemod::applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 483 of file nfmdemod.cpp.
References Interpolator::create(), m_audioSampleRate, m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_nco, NFMDemodSettings::m_rfBandwidth, m_settings, m_settingsMutex, and NCO::setFreq().
Referenced by handleMessage(), and start().
 {
     qDebug() << "NFMDemod::applyChannelSettings:"
             << " inputSampleRate: " << inputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if ((inputFrequencyOffset != m_inputFrequencyOffset) ||
         (inputSampleRate != m_inputSampleRate) || force)
     {
         m_nco.setFreq(-inputFrequencyOffset, inputSampleRate);
     }
     if ((inputSampleRate != m_inputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_interpolator.create(16, inputSampleRate, m_settings.m_rfBandwidth / 2.2f);
         m_interpolatorDistanceRemain = 0;
         m_interpolatorDistance =  (Real) inputSampleRate / (Real) m_audioSampleRate;
         m_settingsMutex.unlock();
     }
     m_inputSampleRate = inputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applySettings()
void NFMDemod::applySettings (const NFMDemodSettings & settings, bool force = false) private
Definition at line 508 of file nfmdemod.cpp.
References AudioDeviceManager::addAudioSink(), applyAudioSampleRate(), Bandpass< Type >::create(), Lowpass< Type >::create(), Interpolator::create(), DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputDeviceIndex(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), NFMDemodSettings::m_afBandwidth, m_afSquelch, NFMDemodSettings::m_audioDeviceName, m_audioFifo, NFMDemodSettings::m_audioMute, m_audioSampleRate, m_bandpass, NFMDemodSettings::m_ctcssIndex, NFMDemodSettings::m_ctcssOn, NFMDemodSettings::m_deltaSquelch, NFMDemodSettings::m_fmDeviation, NFMDemodSettings::m_highPass, NFMDemodSettings::m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_lowpass, m_movingAverage, m_phaseDiscri, NFMDemodSettings::m_reverseAPIAddress, NFMDemodSettings::m_reverseAPIChannelIndex, NFMDemodSettings::m_reverseAPIDeviceIndex, NFMDemodSettings::m_reverseAPIPort, NFMDemodSettings::m_rfBandwidth, NFMDemodSettings::m_rgbColor, m_settings, m_settingsMutex, NFMDemodSettings::m_squelch, m_squelchCount, NFMDemodSettings::m_squelchGate, m_squelchGate, m_squelchLevel, NFMDemodSettings::m_title, NFMDemodSettings::m_useReverseAPI, NFMDemodSettings::m_volume, MovingAverageUtil< T, Total, N >::reset(), AFSquelch::reset(), PhaseDiscriminators::setFMScaling(), setSelectedCtcssIndex(), AFSquelch::setThreshold(), and webapiReverseSendSettings().
Referenced by handleMessage().
 {
     qDebug() << "NFMDemod::applySettings:"
             << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
             << " m_rfBandwidth: " << settings.m_rfBandwidth
             << " m_afBandwidth: " << settings.m_afBandwidth
             << " m_fmDeviation: " << settings.m_fmDeviation
             << " m_volume: " << settings.m_volume
             << " m_squelchGate: " << settings.m_squelchGate
             << " m_deltaSquelch: " << settings.m_deltaSquelch
             << " m_squelch: " << settings.m_squelch
             << " m_ctcssIndex: " << settings.m_ctcssIndex
             << " m_ctcssOn: " << settings.m_ctcssOn
             << " m_highPass: " << settings.m_highPass
             << " m_audioMute: " << settings.m_audioMute
             << " m_audioDeviceName: " << settings.m_audioDeviceName
             << " m_useReverseAPI: " << settings.m_useReverseAPI
             << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
             << " m_reverseAPIPort: " << settings.m_reverseAPIPort
             << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex
             << " m_reverseAPIChannelIndex: " << settings.m_reverseAPIChannelIndex
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if ((settings.m_inputFrequencyOffset != m_settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if ((settings.m_volume != m_settings.m_volume) || force) {
         reverseAPIKeys.append("volume");
     }
     if ((settings.m_ctcssOn != m_settings.m_ctcssOn) || force) {
         reverseAPIKeys.append("ctcssOn");
     }
     if ((settings.m_audioMute != m_settings.m_audioMute) || force) {
         reverseAPIKeys.append("audioMute");
     }
     if ((settings.m_rgbColor != m_settings.m_rgbColor) || force) {
         reverseAPIKeys.append("rgbColor");
     }
     if ((settings.m_title != m_settings.m_title) || force) {
         reverseAPIKeys.append("title");
     }
     if ((settings.m_rfBandwidth != m_settings.m_rfBandwidth) || force)
     {
         reverseAPIKeys.append("rfBandwidth");
         m_settingsMutex.lock();
         m_interpolator.create(16, m_inputSampleRate, settings.m_rfBandwidth / 2.2);
         m_interpolatorDistanceRemain = 0;
         m_interpolatorDistance =  (Real) m_inputSampleRate / (Real) m_audioSampleRate;
         m_settingsMutex.unlock();
     }
     if ((settings.m_fmDeviation != m_settings.m_fmDeviation) || force)
     {
         reverseAPIKeys.append("fmDeviation");
         m_phaseDiscri.setFMScaling((8.0f*m_audioSampleRate) / static_cast<float>(settings.m_fmDeviation)); // integrate 4x factor
     }
     if ((settings.m_afBandwidth != m_settings.m_afBandwidth) || force)
     {
         reverseAPIKeys.append("afBandwidth");
         m_settingsMutex.lock();
         m_bandpass.create(301, m_audioSampleRate, 300.0, settings.m_afBandwidth);
         m_lowpass.create(301, m_audioSampleRate, settings.m_afBandwidth);
         m_settingsMutex.unlock();
     }
     if ((settings.m_squelchGate != m_settings.m_squelchGate) || force)
     {
         reverseAPIKeys.append("squelchGate");
         m_squelchGate = (m_audioSampleRate / 100) * settings.m_squelchGate; // gate is given in 10s of ms at 48000 Hz audio sample rate
         m_squelchCount = 0; // reset squelch open counter
     }
     if ((settings.m_squelch != m_settings.m_squelch) || force) {
         reverseAPIKeys.append("squelch");
     }
     if ((settings.m_deltaSquelch != m_settings.m_deltaSquelch) || force) {
         reverseAPIKeys.append("deltaSquelch");
     }
     if ((settings.m_squelch != m_settings.m_squelch) ||
         (settings.m_deltaSquelch != m_settings.m_deltaSquelch) || force)
     {
         if (settings.m_deltaSquelch)
         { // input is a value in negative centis
             m_squelchLevel = (- settings.m_squelch) / 100.0;
             m_afSquelch.setThreshold(m_squelchLevel);
             m_afSquelch.reset();
         }
         else
         { // input is a value in deci-Bels
             m_squelchLevel = std::pow(10.0, settings.m_squelch / 10.0);
             m_movingAverage.reset();
         }
         m_squelchCount = 0; // reset squelch open counter
     }
     if ((settings.m_ctcssIndex != m_settings.m_ctcssIndex) || force)
     {
         reverseAPIKeys.append("ctcssIndex");
         setSelectedCtcssIndex(settings.m_ctcssIndex);
     }
     if ((settings.m_highPass != m_settings.m_highPass) || force) {
         reverseAPIKeys.append("highPass");
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force)
     {
         reverseAPIKeys.append("audioDeviceName");
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getOutputDeviceIndex(settings.m_audioDeviceName);
         //qDebug("AMDemod::applySettings: audioDeviceName: %s audioDeviceIndex: %d", qPrintable(settings.m_audioDeviceName), audioDeviceIndex);
         audioDeviceManager->addAudioSink(&m_audioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getOutputSampleRate(audioDeviceIndex);
         if (m_audioSampleRate != audioSampleRate) {
             applyAudioSampleRate(audioSampleRate);
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
deserialize()
bool NFMDemod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 651 of file nfmdemod.cpp.
References NFMDemod::MsgConfigureNFMDemod::create(), NFMDemod::MsgConfigureChannelizer::create(), NFMDemodSettings::deserialize(), m_audioSampleRate, NFMDemodSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and NFMDemodSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     NFMDemod::MsgConfigureChannelizer* channelConfigMsg = NFMDemod::MsgConfigureChannelizer::create(
             m_audioSampleRate, m_settings.m_inputFrequencyOffset);
     m_inputMessageQueue.push(channelConfigMsg);
     MsgConfigureNFMDemod *msg = MsgConfigureNFMDemod::create(m_settings, true);
     m_inputMessageQueue.push(msg);
     return success;
 }
destroy()
virtual void NFMDemod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 121 of file nfmdemod.h.
References feed(), handleMessage(), start(), and stop().
 { delete this; }
feed()
void NFMDemod::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool po) virtual
Implements BasebandSampleSink.
Definition at line 150 of file nfmdemod.cpp.
References Interpolator::decimate(), Interpolator::interpolate(), m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_nco, m_running, m_settingsMutex, NCO::nextIQ(), and processOneSample().
Referenced by destroy().
 {
     (void) firstOfBurst;
     Complex ci;
     if (!m_running) {
         return;
     }
     m_settingsMutex.lock();
     for (SampleVector::const_iterator it = begin; it != end; ++it)
     {
         Complex c(it->real(), it->imag());
         c *= m_nco.nextIQ();
         if (m_interpolatorDistance < 1.0f) // interpolate
         {
             while (!m_interpolator.interpolate(&m_interpolatorDistanceRemain, c, &ci))
             {
                 processOneSample(ci);
                 m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
         }
         else // decimate
         {
             if (m_interpolator.decimate(&m_interpolatorDistanceRemain, c, &ci))
             {
                 processOneSample(ci);
                 m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
         }
     }
     m_settingsMutex.unlock();
 }
getCenterFrequency()
virtual qint64 NFMDemod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 130 of file nfmdemod.h.
References deserialize(), NFMDemodSettings::m_inputFrequencyOffset, NFMDemod::MsgConfigureNFMDemod::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getCtcssToneSet()
const Real* NFMDemod::getCtcssToneSet (int & nbTones) const inline
Definition at line 159 of file nfmdemod.h.
References CTCSSDetector::getNTones(), CTCSSDetector::getToneSet(), and m_ctcssDetector.
Referenced by NFMDemodGUI::NFMDemodGUI().
{
         nbTones = m_ctcssDetector.getNTones();
         return m_ctcssDetector.getToneSet();
     }
getIdentifier()
virtual void NFMDemod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 128 of file nfmdemod.h.
 { id = objectName(); }
getMag()
Real NFMDemod::getMag () inline
Definition at line 168 of file nfmdemod.h.
References m_magsq.
 { return m_magsq; }
getMagSqLevels()
void NFMDemod::getMagSqLevels (double & avg, double & peak, int & nbSamples) inline
Definition at line 171 of file nfmdemod.h.
References NFMDemod::MagSqLevelsStore::m_magsq, m_magsq, m_magsqCount, m_magSqLevelStore, NFMDemod::MagSqLevelsStore::m_magsqPeak, m_magsqPeak, and m_magsqSum.
Referenced by NFMDemodGUI::tick(), and webapiFormatChannelReport().
     {
         if (m_magsqCount > 0)
         {
             m_magsq = m_magsqSum / m_magsqCount;
             m_magSqLevelStore.m_magsq = m_magsq;
             m_magSqLevelStore.m_magsqPeak = m_magsqPeak;
         }
         avg = m_magSqLevelStore.m_magsq;
         peak = m_magSqLevelStore.m_magsqPeak;
         nbSamples = m_magsqCount == 0 ? 1 : m_magsqCount;
         m_magsqSum = 0.0f;
         m_magsqPeak = 0.0f;
         m_magsqCount = 0;
     }
getNbSinkStreams()
virtual int NFMDemod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 135 of file nfmdemod.h.
 { return 1; }
getNbSourceStreams()
virtual int NFMDemod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 136 of file nfmdemod.h.
 { return 0; }
getSquelchOpen()
bool NFMDemod::getSquelchOpen () const inline
Definition at line 169 of file nfmdemod.h.
References m_squelchOpen.
Referenced by NFMDemodGUI::tick().
 { return m_squelchOpen; }
getStreamCenterFrequency()
virtual qint64 NFMDemod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 138 of file nfmdemod.h.
References NFMDemodSettings::m_inputFrequencyOffset, NFMDemod::MsgConfigureNFMDemod::m_settings, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void NFMDemod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 129 of file nfmdemod.h.
References NFMDemod::MsgConfigureNFMDemod::m_settings, and NFMDemodSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool NFMDemod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 379 of file nfmdemod.cpp.
References applyAudioSampleRate(), applyChannelSettings(), applySettings(), DownChannelizer::configure(), NFMDemod::MsgConfigureChannelizer::getCenterFrequency(), NFMDemod::MsgConfigureNFMDemod::getForce(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSink::getInputMessageQueue(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), NFMDemod::MsgConfigureChannelizer::getSampleRate(), DSPConfigureAudio::getSampleRate(), NFMDemod::MsgConfigureNFMDemod::getSettings(), BasebandSampleSink::MsgThreadedSink::getThread(), m_audioSampleRate, m_channelizer, and Message::match().
Referenced by destroy().
 {
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& notif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "NFMDemod::handleMessage: DownChannelizer::MsgChannelizerNotification";
         applyChannelSettings(notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "NFMDemod::handleMessage: MsgConfigureChannelizer:"
                  << " sampleRate: " << cfg.getSampleRate()
                  << " centerFrequency: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureNFMDemod::match(cmd))
     {
         MsgConfigureNFMDemod& cfg = (MsgConfigureNFMDemod&) cmd;
         qDebug() << "NFMDemod::handleMessage: MsgConfigureNFMDemod";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (BasebandSampleSink::MsgThreadedSink::match(cmd))
     {
         BasebandSampleSink::MsgThreadedSink& cfg = (BasebandSampleSink::MsgThreadedSink&) cmd;
         const QThread *thread = cfg.getThread();
         qDebug("NFMDemod::handleMessage: BasebandSampleSink::MsgThreadedSink: %p", thread);
         return true;
     }
     else if (DSPConfigureAudio::match(cmd))
     {
         DSPConfigureAudio& cfg = (DSPConfigureAudio&) cmd;
         uint32_t sampleRate = cfg.getSampleRate();
         qDebug() << "NFMDemod::handleMessage: DSPConfigureAudio:"
                 << " sampleRate: " << sampleRate;
         if (sampleRate != m_audioSampleRate) {
             applyAudioSampleRate(sampleRate);
         }
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         return false;
     }
 }
networkManagerFinished
void NFMDemod::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 918 of file nfmdemod.cpp.
Referenced by ~NFMDemod().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "NFMDemod::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("NFMDemod::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
processOneSample()
void NFMDemod::processOneSample (Complex & ci) private
Definition at line 187 of file nfmdemod.cpp.
References CTCSSDetector::analyze(), AFSquelch::analyze(), NFMDemod::MsgReportCTCSSFreq::create(), AFSquelch::evaluate(), Lowpass< Type >::filter(), Bandpass< Type >::filter(), CTCSSDetector::getDetectedTone(), BasebandSampleSink::getMessageQueueToGUI(), CTCSSDetector::getToneSet(), m_afSquelch, m_afSquelchOpen, m_audioBuffer, m_audioBufferFill, m_audioFifo, NFMDemodSettings::m_audioMute, m_audioSampleRate, m_bandpass, m_ctcssDetector, m_ctcssIndex, m_ctcssIndexSelected, m_ctcssLowpass, NFMDemodSettings::m_ctcssOn, NFMDemodSettings::m_deltaSquelch, m_discriCompensation, NFMDemodSettings::m_highPass, m_lowpass, m_magsqCount, m_magsqPeak, m_magsqSum, m_movingAverage, m_phaseDiscri, m_sampleCount, m_settings, m_squelchCount, m_squelchDelayLine, m_squelchGate, m_squelchLevel, m_squelchOpen, NFMDemodSettings::m_volume, PhaseDiscriminators::phaseDiscriminatorDelta(), MessageQueue::push(), DoubleBufferFIFO< T >::readBack(), SDR_RX_SCALED, AudioFifo::write(), DoubleBufferFIFO< T >::write(), and DoubleBufferFIFO< T >::zeroBack().
Referenced by feed().
 {
     qint16 sample;
     double magsqRaw; // = ci.real()*ci.real() + c.imag()*c.imag();
     Real deviation;
     Real demod = m_phaseDiscri.phaseDiscriminatorDelta(ci, magsqRaw, deviation);
     Real magsq = magsqRaw / (SDR_RX_SCALED*SDR_RX_SCALED);
     m_movingAverage(magsq);
     m_magsqSum += magsq;
     if (magsq > m_magsqPeak)
     {
         m_magsqPeak = magsq;
     }
     m_magsqCount++;
     m_sampleCount++;
     // AF processing
     if (m_settings.m_deltaSquelch)
     {
         if (m_afSquelch.analyze(demod * m_discriCompensation))
         {
             m_afSquelchOpen = m_afSquelch.evaluate(); // ? m_squelchGate + m_squelchDecay : 0;
             if (!m_afSquelchOpen) {
                 m_squelchDelayLine.zeroBack(m_audioSampleRate/10); // zero out evaluation period
             }
         }
         if (m_afSquelchOpen)
         {
             m_squelchDelayLine.write(demod * m_discriCompensation);
             if (m_squelchCount < 2*m_squelchGate) {
                 m_squelchCount++;
             }
         }
         else
         {
             m_squelchDelayLine.write(0);
             if (m_squelchCount > 0) {
                 m_squelchCount--;
             }
         }
     }
     else
     {
         if ((Real) m_movingAverage < m_squelchLevel)
         {
             m_squelchDelayLine.write(0);
             if (m_squelchCount > 0) {
                 m_squelchCount--;
             }
         }
         else
         {
             m_squelchDelayLine.write(demod * m_discriCompensation);
             if (m_squelchCount < 2*m_squelchGate) {
                 m_squelchCount++;
             }
         }
     }
     m_squelchOpen = (m_squelchCount > m_squelchGate);
     if (m_settings.m_audioMute)
     {
         sample = 0;
     }
     else
     {
         if (m_squelchOpen)
         {
             if (m_settings.m_ctcssOn)
             {
                 Real ctcss_sample = m_ctcssLowpass.filter(demod * m_discriCompensation);
                 if ((m_sampleCount & 7) == 7) // decimate 48k -> 6k
                 {
                     if (m_ctcssDetector.analyze(&ctcss_sample))
                     {
                         int maxToneIndex;
                         if (m_ctcssDetector.getDetectedTone(maxToneIndex))
{
                             if (maxToneIndex+1 != m_ctcssIndex)
{
                                 if (getMessageQueueToGUI()) {
                                     MsgReportCTCSSFreq *msg = MsgReportCTCSSFreq::create(m_ctcssDetector.getToneSet()[maxToneIndex]);
                                     getMessageQueueToGUI()->push(msg);
                                 }
                                 m_ctcssIndex = maxToneIndex+1;
                             }
                         }
                         else
{
                             if (m_ctcssIndex != 0)
{
                                 if (getMessageQueueToGUI()) {
                                     MsgReportCTCSSFreq *msg = MsgReportCTCSSFreq::create(0);
                                     getMessageQueueToGUI()->push(msg);
                                 }
                                 m_ctcssIndex = 0;
                             }
                         }
                     }
                 }
             }
             if (m_settings.m_ctcssOn && m_ctcssIndexSelected && (m_ctcssIndexSelected != m_ctcssIndex))
             {
                 sample = 0;
             }
             else
             {
                 if (m_settings.m_highPass) {
                     sample = m_bandpass.filter(m_squelchDelayLine.readBack(m_squelchGate)) * m_settings.m_volume;
                 } else {
                     sample = m_lowpass.filter(m_squelchDelayLine.readBack(m_squelchGate)) * m_settings.m_volume * 301.0f;
                 }
             }
         }
         else
         {
             if (m_ctcssIndex != 0)
             {
                 if (getMessageQueueToGUI()) {
                     MsgReportCTCSSFreq *msg = MsgReportCTCSSFreq::create(0);
                     getMessageQueueToGUI()->push(msg);
                 }
                 m_ctcssIndex = 0;
             }
             sample = 0;
         }
     }
     m_audioBuffer[m_audioBufferFill].l = sample;
     m_audioBuffer[m_audioBufferFill].r = sample;
     ++m_audioBufferFill;
     if (m_audioBufferFill >= m_audioBuffer.size())
     {
         uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
         if (res != m_audioBufferFill)
         {
             qDebug("NFMDemod::feed: %u/%u audio samples written", res, m_audioBufferFill);
         }
         m_audioBufferFill = 0;
     }
     if (m_audioBufferFill > 0)
     {
         uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
         if (res != m_audioBufferFill)
         {
             qDebug("NFMDemod::feed: %u/%u tail samples written", res, m_audioBufferFill);
         }
         m_audioBufferFill = 0;
     }
 }
serialize()
QByteArray NFMDemod::serialize () const virtual
Implements ChannelAPI.
Definition at line 646 of file nfmdemod.cpp.
References m_settings, and NFMDemodSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
setSelectedCtcssIndex()
void NFMDemod::setSelectedCtcssIndex (int selectedCtcssIndex) inline
Definition at line 164 of file nfmdemod.h.
References m_ctcssIndexSelected.
Referenced by applySettings().
{
         m_ctcssIndexSelected = selectedCtcssIndex;
     }
start()
void NFMDemod::start () virtual
Implements BasebandSampleSink.
Definition at line 363 of file nfmdemod.cpp.
References applyChannelSettings(), AudioFifo::clear(), m_audioFifo, m_inputFrequencyOffset, m_inputSampleRate, m_phaseDiscri, m_running, m_squelchCount, and PhaseDiscriminators::reset().
Referenced by destroy().
 {
     qDebug() << "NFMDemod::start";
     m_squelchCount = 0;
     m_audioFifo.clear();
     m_phaseDiscri.reset();
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
     m_running = true;
 }
stop()
void NFMDemod::stop () virtual
Implements BasebandSampleSink.
Definition at line 373 of file nfmdemod.cpp.
References m_running.
Referenced by destroy().
 {
     qDebug() << "NFMDemod::stop";
     m_running = false;
 }
webapiFormatChannelReport()
void NFMDemod::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 828 of file nfmdemod.cpp.
References CalcDb::dbPower(), getMagSqLevels(), SWGSDRangel::SWGChannelReport::getNfmDemodReport(), CTCSSDetector::getToneSet(), m_audioSampleRate, m_ctcssDetector, m_ctcssIndex, NFMDemodSettings::m_ctcssOn, m_inputSampleRate, m_settings, m_squelchOpen, SWGSDRangel::SWGNFMDemodReport::setAudioSampleRate(), SWGSDRangel::SWGNFMDemodReport::setChannelPowerDb(), SWGSDRangel::SWGNFMDemodReport::setChannelSampleRate(), SWGSDRangel::SWGNFMDemodReport::setCtcssTone(), and SWGSDRangel::SWGNFMDemodReport::setSquelch().
Referenced by webapiReportGet().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     response.getNfmDemodReport()->setChannelPowerDb(CalcDb::dbPower(magsqAvg));
     response.getNfmDemodReport()->setCtcssTone(m_settings.m_ctcssOn ? (m_ctcssIndex ? 0 : m_ctcssDetector.getToneSet()[m_ctcssIndex-1]) : 0);
     response.getNfmDemodReport()->setSquelch(m_squelchOpen ? 1 : 0);
     response.getNfmDemodReport()->setAudioSampleRate(m_audioSampleRate);
     response.getNfmDemodReport()->setChannelSampleRate(m_inputSampleRate);
 }
webapiFormatChannelSettings()
void NFMDemod::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const NFMDemodSettings & settings) private
Definition at line 787 of file nfmdemod.cpp.
References SWGSDRangel::SWGNFMDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGChannelSettings::getNfmDemodSettings(), SWGSDRangel::SWGNFMDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGNFMDemodSettings::getTitle(), NFMDemodSettings::m_afBandwidth, NFMDemodSettings::m_audioDeviceName, NFMDemodSettings::m_audioMute, NFMDemodSettings::m_ctcssIndex, NFMDemodSettings::m_ctcssOn, NFMDemodSettings::m_deltaSquelch, NFMDemodSettings::m_fmDeviation, NFMDemodSettings::m_highPass, NFMDemodSettings::m_inputFrequencyOffset, NFMDemodSettings::m_reverseAPIAddress, NFMDemodSettings::m_reverseAPIChannelIndex, NFMDemodSettings::m_reverseAPIDeviceIndex, NFMDemodSettings::m_reverseAPIPort, NFMDemodSettings::m_rfBandwidth, NFMDemodSettings::m_rgbColor, NFMDemodSettings::m_squelch, NFMDemodSettings::m_squelchGate, NFMDemodSettings::m_title, NFMDemodSettings::m_useReverseAPI, NFMDemodSettings::m_volume, SWGSDRangel::SWGNFMDemodSettings::setAfBandwidth(), SWGSDRangel::SWGNFMDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGNFMDemodSettings::setAudioMute(), SWGSDRangel::SWGNFMDemodSettings::setCtcssIndex(), SWGSDRangel::SWGNFMDemodSettings::setCtcssOn(), SWGSDRangel::SWGNFMDemodSettings::setDeltaSquelch(), SWGSDRangel::SWGNFMDemodSettings::setFmDeviation(), SWGSDRangel::SWGNFMDemodSettings::setHighPass(), SWGSDRangel::SWGNFMDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGNFMDemodSettings::setReverseApiAddress(), SWGSDRangel::SWGNFMDemodSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGNFMDemodSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGNFMDemodSettings::setReverseApiPort(), SWGSDRangel::SWGNFMDemodSettings::setRfBandwidth(), SWGSDRangel::SWGNFMDemodSettings::setRgbColor(), SWGSDRangel::SWGNFMDemodSettings::setSquelch(), SWGSDRangel::SWGNFMDemodSettings::setSquelchGate(), SWGSDRangel::SWGNFMDemodSettings::setTitle(), SWGSDRangel::SWGNFMDemodSettings::setUseReverseApi(), and SWGSDRangel::SWGNFMDemodSettings::setVolume().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getNfmDemodSettings()->setAfBandwidth(settings.m_afBandwidth);
     response.getNfmDemodSettings()->setAudioMute(settings.m_audioMute ? 1 : 0);
     response.getNfmDemodSettings()->setHighPass(settings.m_highPass ? 1 : 0);
     response.getNfmDemodSettings()->setCtcssIndex(settings.m_ctcssIndex);
     response.getNfmDemodSettings()->setCtcssOn(settings.m_ctcssOn ? 1 : 0);
     response.getNfmDemodSettings()->setDeltaSquelch(settings.m_deltaSquelch ? 1 : 0);
     response.getNfmDemodSettings()->setFmDeviation(settings.m_fmDeviation);
     response.getNfmDemodSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getNfmDemodSettings()->setRfBandwidth(settings.m_rfBandwidth);
     response.getNfmDemodSettings()->setRgbColor(settings.m_rgbColor);
     response.getNfmDemodSettings()->setSquelch(settings.m_squelch);
     response.getNfmDemodSettings()->setSquelchGate(settings.m_squelchGate);
     response.getNfmDemodSettings()->setVolume(settings.m_volume);
     if (response.getNfmDemodSettings()->getTitle()) {
         *response.getNfmDemodSettings()->getTitle() = settings.m_title;
     } else {
         response.getNfmDemodSettings()->setTitle(new QString(settings.m_title));
     }
     if (response.getNfmDemodSettings()->getAudioDeviceName()) {
         *response.getNfmDemodSettings()->getAudioDeviceName() = settings.m_audioDeviceName;
     } else {
         response.getNfmDemodSettings()->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     response.getNfmDemodSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getNfmDemodSettings()->getReverseApiAddress()) {
         *response.getNfmDemodSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getNfmDemodSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getNfmDemodSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getNfmDemodSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getNfmDemodSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int NFMDemod::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 776 of file nfmdemod.cpp.
References SWGSDRangel::SWGChannelReport::getNfmDemodReport(), SWGSDRangel::SWGNFMDemodReport::init(), SWGSDRangel::SWGChannelReport::setNfmDemodReport(), and webapiFormatChannelReport().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setNfmDemodReport(new SWGSDRangel::SWGNFMDemodReport());
     response.getNfmDemodReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendSettings()
void NFMDemod::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const NFMDemodSettings & settings, bool force) private
Definition at line 841 of file nfmdemod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), SWGSDRangel::SWGChannelSettings::getNfmDemodSettings(), NFMDemodSettings::m_afBandwidth, NFMDemodSettings::m_audioDeviceName, NFMDemodSettings::m_audioMute, NFMDemodSettings::m_ctcssIndex, NFMDemodSettings::m_ctcssOn, NFMDemodSettings::m_deltaSquelch, NFMDemodSettings::m_fmDeviation, NFMDemodSettings::m_highPass, NFMDemodSettings::m_inputFrequencyOffset, m_networkManager, m_networkRequest, NFMDemodSettings::m_reverseAPIAddress, NFMDemodSettings::m_reverseAPIChannelIndex, NFMDemodSettings::m_reverseAPIDeviceIndex, NFMDemodSettings::m_reverseAPIPort, NFMDemodSettings::m_rfBandwidth, NFMDemodSettings::m_rgbColor, NFMDemodSettings::m_squelch, NFMDemodSettings::m_squelchGate, NFMDemodSettings::m_title, NFMDemodSettings::m_volume, SWGSDRangel::SWGNFMDemodSettings::setAfBandwidth(), SWGSDRangel::SWGNFMDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGNFMDemodSettings::setAudioMute(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGNFMDemodSettings::setCtcssIndex(), SWGSDRangel::SWGNFMDemodSettings::setCtcssOn(), SWGSDRangel::SWGNFMDemodSettings::setDeltaSquelch(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGNFMDemodSettings::setFmDeviation(), SWGSDRangel::SWGNFMDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGChannelSettings::setNfmDemodSettings(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGNFMDemodSettings::setRfBandwidth(), SWGSDRangel::SWGNFMDemodSettings::setRgbColor(), SWGSDRangel::SWGNFMDemodSettings::setSquelch(), SWGSDRangel::SWGNFMDemodSettings::setSquelchGate(), SWGSDRangel::SWGNFMDemodSettings::setTitle(), and SWGSDRangel::SWGNFMDemodSettings::setVolume().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(0); // single sink (Rx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("NFMDemod"));
     swgChannelSettings->setNfmDemodSettings(new SWGSDRangel::SWGNFMDemodSettings());
     SWGSDRangel::SWGNFMDemodSettings *swgNFMDemodSettings = swgChannelSettings->getNfmDemodSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("afBandwidth") || force) {
         swgNFMDemodSettings->setAfBandwidth(settings.m_afBandwidth);
     }
     if (channelSettingsKeys.contains("audioMute") || force) {
         swgNFMDemodSettings->setAudioMute(settings.m_audioMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("highPass") || force) {
         swgNFMDemodSettings->setAudioMute(settings.m_highPass ? 1 : 0);
     }
     if (channelSettingsKeys.contains("ctcssIndex") || force) {
         swgNFMDemodSettings->setCtcssIndex(settings.m_ctcssIndex);
     }
     if (channelSettingsKeys.contains("ctcssOn") || force) {
         swgNFMDemodSettings->setCtcssOn(settings.m_ctcssOn ? 1 : 0);
     }
     if (channelSettingsKeys.contains("deltaSquelch") || force) {
         swgNFMDemodSettings->setDeltaSquelch(settings.m_deltaSquelch ? 1 : 0);
     }
     if (channelSettingsKeys.contains("fmDeviation") || force) {
         swgNFMDemodSettings->setFmDeviation(settings.m_fmDeviation);
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgNFMDemodSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("rfBandwidth") || force) {
         swgNFMDemodSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgNFMDemodSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("squelch") || force) {
         swgNFMDemodSettings->setSquelch(settings.m_squelch);
     }
     if (channelSettingsKeys.contains("squelchGate") || force) {
         swgNFMDemodSettings->setSquelchGate(settings.m_squelchGate);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgNFMDemodSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("volume") || force) {
         swgNFMDemodSettings->setVolume(settings.m_volume);
     }
     if (channelSettingsKeys.contains("audioDeviceName") || force) {
         swgNFMDemodSettings->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int NFMDemod::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 671 of file nfmdemod.cpp.
References SWGSDRangel::SWGChannelSettings::getNfmDemodSettings(), SWGSDRangel::SWGNFMDemodSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setNfmDemodSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setNfmDemodSettings(new SWGSDRangel::SWGNFMDemodSettings());
     response.getNfmDemodSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int NFMDemod::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 682 of file nfmdemod.cpp.
References NFMDemod::MsgConfigureNFMDemod::create(), NFMDemod::MsgConfigureChannelizer::create(), SWGSDRangel::SWGNFMDemodSettings::getAfBandwidth(), SWGSDRangel::SWGNFMDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGNFMDemodSettings::getAudioMute(), SWGSDRangel::SWGNFMDemodSettings::getCtcssIndex(), SWGSDRangel::SWGNFMDemodSettings::getCtcssOn(), SWGSDRangel::SWGNFMDemodSettings::getDeltaSquelch(), SWGSDRangel::SWGNFMDemodSettings::getFmDeviation(), SWGSDRangel::SWGNFMDemodSettings::getHighPass(), SWGSDRangel::SWGNFMDemodSettings::getInputFrequencyOffset(), SWGSDRangel::SWGChannelSettings::getNfmDemodSettings(), SWGSDRangel::SWGNFMDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGNFMDemodSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGNFMDemodSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGNFMDemodSettings::getReverseApiPort(), SWGSDRangel::SWGNFMDemodSettings::getRfBandwidth(), SWGSDRangel::SWGNFMDemodSettings::getRgbColor(), SWGSDRangel::SWGNFMDemodSettings::getSquelch(), SWGSDRangel::SWGNFMDemodSettings::getSquelchGate(), SWGSDRangel::SWGNFMDemodSettings::getTitle(), SWGSDRangel::SWGNFMDemodSettings::getUseReverseApi(), SWGSDRangel::SWGNFMDemodSettings::getVolume(), NFMDemodSettings::m_afBandwidth, NFMDemodSettings::m_audioDeviceName, NFMDemodSettings::m_audioMute, m_audioSampleRate, NFMDemodSettings::m_ctcssIndex, NFMDemodSettings::m_ctcssOn, NFMDemodSettings::m_deltaSquelch, NFMDemodSettings::m_fmDeviation, BasebandSampleSink::m_guiMessageQueue, NFMDemodSettings::m_highPass, NFMDemodSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, NFMDemodSettings::m_reverseAPIAddress, NFMDemodSettings::m_reverseAPIChannelIndex, NFMDemodSettings::m_reverseAPIDeviceIndex, NFMDemodSettings::m_reverseAPIPort, NFMDemodSettings::m_rfBandwidth, NFMDemodSettings::m_rgbColor, m_settings, NFMDemodSettings::m_squelch, NFMDemodSettings::m_squelchGate, NFMDemodSettings::m_title, NFMDemodSettings::m_useReverseAPI, NFMDemodSettings::m_volume, MessageQueue::push(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     NFMDemodSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
     if (channelSettingsKeys.contains("afBandwidth")) {
         settings.m_afBandwidth = response.getNfmDemodSettings()->getAfBandwidth();
     }
     if (channelSettingsKeys.contains("audioMute")) {
         settings.m_audioMute = response.getNfmDemodSettings()->getAudioMute() != 0;
     }
     if (channelSettingsKeys.contains("highPass")) {
         settings.m_highPass = response.getNfmDemodSettings()->getHighPass() != 0;
     }
     if (channelSettingsKeys.contains("ctcssIndex")) {
         settings.m_ctcssIndex = response.getNfmDemodSettings()->getCtcssIndex();
     }
     if (channelSettingsKeys.contains("ctcssOn")) {
         settings.m_ctcssOn = response.getNfmDemodSettings()->getCtcssOn() != 0;
     }
     if (channelSettingsKeys.contains("deltaSquelch")) {
         settings.m_deltaSquelch = response.getNfmDemodSettings()->getDeltaSquelch() != 0;
     }
     if (channelSettingsKeys.contains("fmDeviation")) {
         settings.m_fmDeviation = response.getNfmDemodSettings()->getFmDeviation();
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getNfmDemodSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getNfmDemodSettings()->getRfBandwidth();
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getNfmDemodSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("squelch")) {
         settings.m_squelch = response.getNfmDemodSettings()->getSquelch();
     }
     if (channelSettingsKeys.contains("squelchGate")) {
         settings.m_squelchGate = response.getNfmDemodSettings()->getSquelchGate();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getNfmDemodSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("volume")) {
         settings.m_volume = response.getNfmDemodSettings()->getVolume();
     }
     if (channelSettingsKeys.contains("audioDeviceName")) {
         settings.m_audioDeviceName = *response.getNfmDemodSettings()->getAudioDeviceName();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getNfmDemodSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getNfmDemodSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getNfmDemodSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getNfmDemodSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getNfmDemodSettings()->getReverseApiChannelIndex();
     }
     if (frequencyOffsetChanged)
     {
         MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
                 m_audioSampleRate, settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(channelConfigMsg);
     }
     MsgConfigureNFMDemod *msg = MsgConfigureNFMDemod::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureNFMDemod *msgToGUI = MsgConfigureNFMDemod::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_afSquelch
AFSquelch NFMDemod::m_afSquelch private
Definition at line 243 of file nfmdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), NFMDemod(), and processOneSample().
m_afSquelchOpen
bool NFMDemod::m_afSquelchOpen private
Definition at line 235 of file nfmdemod.h.
Referenced by processOneSample().
m_agcLevel
Real NFMDemod::m_agcLevel private
Definition at line 244 of file nfmdemod.h.
Referenced by NFMDemod().
m_audioBuffer
AudioVector NFMDemod::m_audioBuffer private
Definition at line 247 of file nfmdemod.h.
Referenced by NFMDemod(), and processOneSample().
m_audioBufferFill
uint NFMDemod::m_audioBufferFill private
Definition at line 248 of file nfmdemod.h.
Referenced by NFMDemod(), and processOneSample().
m_audioFifo
AudioFifo NFMDemod::m_audioFifo private
Definition at line 249 of file nfmdemod.h.
Referenced by applySettings(), NFMDemod(), processOneSample(), start(), and ~NFMDemod().
m_audioSampleRate
uint32_t NFMDemod::m_audioSampleRate private
Definition at line 215 of file nfmdemod.h.
Referenced by applyChannelSettings(), applySettings(), deserialize(), handleMessage(), NFMDemod(), processOneSample(), webapiFormatChannelReport(), and webapiSettingsPutPatch().
m_bandpass
Bandpass<Real> NFMDemod::m_bandpass private
Definition at line 224 of file nfmdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), and processOneSample().
m_channelId
const QString NFMDemod::m_channelId = "NFMDemod" static
Definition at line 190 of file nfmdemod.h.
Referenced by NFMPlugin::initPlugin(), and NFMDemod().
m_channelIdURI
const QString NFMDemod::m_channelIdURI = "sdrangel.channel.nfmdemod" static
Definition at line 189 of file nfmdemod.h.
Referenced by NFMPlugin::initPlugin(), and NFMDemodGUI::NFMDemodGUI().
m_channelizer
DownChannelizer* NFMDemod::m_channelizer private
Definition at line 210 of file nfmdemod.h.
Referenced by handleMessage(), and ~NFMDemod().
m_ctcssDetector
CTCSSDetector NFMDemod::m_ctcssDetector private
Definition at line 226 of file nfmdemod.h.
Referenced by applyAudioSampleRate(), getCtcssToneSet(), NFMDemod(), processOneSample(), and webapiFormatChannelReport().
m_ctcssIndex
int NFMDemod::m_ctcssIndex private
Definition at line 227 of file nfmdemod.h.
Referenced by processOneSample(), and webapiFormatChannelReport().
m_ctcssIndexSelected
int NFMDemod::m_ctcssIndexSelected private
Definition at line 228 of file nfmdemod.h.
Referenced by processOneSample(), and setSelectedCtcssIndex().
m_ctcssLowpass
Lowpass<Real> NFMDemod::m_ctcssLowpass private
Definition at line 223 of file nfmdemod.h.
Referenced by applyAudioSampleRate(), and processOneSample().
m_deviceAPI
DeviceAPI* NFMDemod::m_deviceAPI private
Definition at line 208 of file nfmdemod.h.
Referenced by ~NFMDemod().
m_discriCompensation
float NFMDemod::m_discriCompensation private
compensation factor that depends on audio rate (1 for 48 kS/s)
Definition at line 216 of file nfmdemod.h.
Referenced by NFMDemod(), and processOneSample().
m_inputFrequencyOffset
int NFMDemod::m_inputFrequencyOffset private
Definition at line 213 of file nfmdemod.h.
Referenced by applyChannelSettings(), and start().
m_inputSampleRate
int NFMDemod::m_inputSampleRate private
Definition at line 212 of file nfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), start(), and webapiFormatChannelReport().
m_interpolator
Interpolator NFMDemod::m_interpolator private
Definition at line 220 of file nfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_interpolatorDistance
Real NFMDemod::m_interpolatorDistance private
Definition at line 221 of file nfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_interpolatorDistanceRemain
Real NFMDemod::m_interpolatorDistanceRemain private
Definition at line 222 of file nfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_lowpass
Lowpass<Real> NFMDemod::m_lowpass private
Definition at line 225 of file nfmdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), and processOneSample().
m_magsq
double NFMDemod::m_magsq private
displayed averaged value
Definition at line 236 of file nfmdemod.h.
Referenced by getMag(), and getMagSqLevels().
m_magsqCount
int NFMDemod::m_magsqCount private
Definition at line 239 of file nfmdemod.h.
Referenced by getMagSqLevels(), and processOneSample().
m_magSqLevelStore
MagSqLevelsStore NFMDemod::m_magSqLevelStore private
Definition at line 240 of file nfmdemod.h.
Referenced by getMagSqLevels().
m_magsqPeak
double NFMDemod::m_magsqPeak private
Definition at line 238 of file nfmdemod.h.
Referenced by getMagSqLevels(), and processOneSample().
m_magsqSum
double NFMDemod::m_magsqSum private
Definition at line 237 of file nfmdemod.h.
Referenced by getMagSqLevels(), and processOneSample().
m_movingAverage
MovingAverageUtil<Real, double, 32> NFMDemod::m_movingAverage private
Definition at line 242 of file nfmdemod.h.
Referenced by applySettings(), and processOneSample().
m_nco
NCO NFMDemod::m_nco private
Definition at line 219 of file nfmdemod.h.
Referenced by applyChannelSettings(), and feed().
m_networkManager
QNetworkAccessManager* NFMDemod::m_networkManager private
Definition at line 255 of file nfmdemod.h.
Referenced by webapiReverseSendSettings(), and ~NFMDemod().
m_networkRequest
QNetworkRequest NFMDemod::m_networkRequest private
Definition at line 256 of file nfmdemod.h.
Referenced by webapiReverseSendSettings().
m_phaseDiscri
PhaseDiscriminators NFMDemod::m_phaseDiscri private
Definition at line 253 of file nfmdemod.h.
Referenced by applySettings(), processOneSample(), and start().
m_running
bool NFMDemod::m_running private
Definition at line 217 of file nfmdemod.h.
Referenced by feed(), start(), and stop().
m_sampleCount
int NFMDemod::m_sampleCount private
Definition at line 229 of file nfmdemod.h.
Referenced by processOneSample().
m_settings
NFMDemodSettings NFMDemod::m_settings private
Definition at line 214 of file nfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), deserialize(), processOneSample(), serialize(), webapiFormatChannelReport(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex NFMDemod::m_settingsMutex private
Definition at line 251 of file nfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_squelchCount
int NFMDemod::m_squelchCount private
Definition at line 230 of file nfmdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), processOneSample(), and start().
m_squelchDelayLine
DoubleBufferFIFO<Real> NFMDemod::m_squelchDelayLine private
Definition at line 245 of file nfmdemod.h.
Referenced by processOneSample().
m_squelchGate
int NFMDemod::m_squelchGate private
Definition at line 231 of file nfmdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), and processOneSample().
m_squelchLevel
Real NFMDemod::m_squelchLevel private
Definition at line 233 of file nfmdemod.h.
Referenced by applySettings(), and processOneSample().
m_squelchOpen
bool NFMDemod::m_squelchOpen private
Definition at line 234 of file nfmdemod.h.
Referenced by getSquelchOpen(), processOneSample(), and webapiFormatChannelReport().
m_threadedChannelizer
ThreadedBasebandSampleSink* NFMDemod::m_threadedChannelizer private
Definition at line 209 of file nfmdemod.h.
Referenced by ~NFMDemod().
m_udpBlockSize
const int NFMDemod::m_udpBlockSize = 512 static private
Definition at line 258 of file nfmdemod.h.
The documentation for this class was generated from the following files:
plugins/channelrx/demodnfm/nfmdemod.h
plugins/channelrx/demodnfm/nfmdemod.cpp