SDRAngel: SWGSDRangel::SWGInstanceConfigResponse Class Reference
SWGSDRangel::SWGInstanceConfigResponse Class Reference
#include <SWGInstanceConfigResponse.h>
Public Member Functions
SWGInstanceConfigResponse ()
SWGInstanceConfigResponse (QString *json)
virtual ~SWGInstanceConfigResponse ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGInstanceConfigResponse * fromJson (QString &jsonString) override
SWGPreferences * getPreferences ()
void setPreferences (SWGPreferences *preferences)
SWGPreset * getWorkingPreset ()
void setWorkingPreset (SWGPreset *working_preset)
QList< SWGPreset * > * getPresets ()
void setPresets (QList< SWGPreset *> *presets)
QList< SWGCommand * > * getCommands ()
void setCommands (QList< SWGCommand *> *commands)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
SWGPreferences * preferences
bool m_preferences_isSet
SWGPreset * working_preset
bool m_working_preset_isSet
QList< SWGPreset * > * presets
bool m_presets_isSet
QList< SWGCommand * > * commands
bool m_commands_isSet
Detailed Description
Definition at line 35 of file SWGInstanceConfigResponse.h.
Constructor & Destructor Documentation
SWGInstanceConfigResponse() [1/2]
SWGSDRangel::SWGInstanceConfigResponse::SWGInstanceConfigResponse ()
Definition at line 30 of file SWGInstanceConfigResponse.cpp.
References commands, m_commands_isSet, m_preferences_isSet, m_presets_isSet, m_working_preset_isSet, preferences, presets, and working_preset.
{
     preferences = nullptr;
     m_preferences_isSet = false;
     working_preset = nullptr;
     m_working_preset_isSet = false;
     presets = nullptr;
     m_presets_isSet = false;
     commands = nullptr;
     m_commands_isSet = false;
 }
SWGInstanceConfigResponse() [2/2]
SWGSDRangel::SWGInstanceConfigResponse::SWGInstanceConfigResponse (QString * json)
Definition at line 25 of file SWGInstanceConfigResponse.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGInstanceConfigResponse()
SWGSDRangel::SWGInstanceConfigResponse::~SWGInstanceConfigResponse () virtual
Definition at line 41 of file SWGInstanceConfigResponse.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGInstanceConfigResponse::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 103 of file SWGInstanceConfigResponse.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::instanceConfigService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGInstanceConfigResponse::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 114 of file SWGInstanceConfigResponse.cpp.
References commands, SWGSDRangel::SWGPreferences::isSet(), SWGSDRangel::SWGPreset::isSet(), preferences, presets, SWGSDRangel::toJsonArray(), SWGSDRangel::toJsonValue(), and working_preset.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if((preferences != nullptr) && (preferences->isSet())){
         toJsonValue(QString("preferences"), preferences, obj, QString("SWGPreferences"));
     }
     if((working_preset != nullptr) && (working_preset->isSet())){
         toJsonValue(QString("workingPreset"), working_preset, obj, QString("SWGPreset"));
     }
     if(presets->size() > 0){
         toJsonArray((QList<void*>*)presets, obj, "presets", "SWGPreset");
     }
     if(commands->size() > 0){
         toJsonArray((QList<void*>*)commands, obj, "commands", "SWGCommand");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGInstanceConfigResponse::cleanup ()
Definition at line 58 of file SWGInstanceConfigResponse.cpp.
References commands, preferences, presets, and working_preset.
Referenced by ~SWGInstanceConfigResponse().
{
     if(preferences != nullptr) {
         delete preferences;
     }
     if(working_preset != nullptr) {
         delete working_preset;
     }
     if(presets != nullptr) {
         auto arr = presets;
         for(auto o: *arr) {
             delete o;
         }
         delete presets;
     }
     if(commands != nullptr) {
         auto arr = commands;
         for(auto o: *arr) {
             delete o;
         }
         delete commands;
     }
 }
fromJson()
SWGInstanceConfigResponse * SWGSDRangel::SWGInstanceConfigResponse::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 82 of file SWGInstanceConfigResponse.cpp.
References fromJsonObject().
Referenced by SWGInstanceConfigResponse().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGInstanceConfigResponse::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 91 of file SWGInstanceConfigResponse.cpp.
References commands, preferences, presets, SWGSDRangel::setValue(), and working_preset.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&preferences, pJson["preferences"], "SWGPreferences", "SWGPreferences");
     ::SWGSDRangel::setValue(&working_preset, pJson["workingPreset"], "SWGPreset", "SWGPreset");
     ::SWGSDRangel::setValue(&presets, pJson["presets"], "QList", "SWGPreset");
     ::SWGSDRangel::setValue(&commands, pJson["commands"], "QList", "SWGCommand");
 }
getCommands()
QList< SWGCommand * > * SWGSDRangel::SWGInstanceConfigResponse::getCommands ()
Definition at line 163 of file SWGInstanceConfigResponse.cpp.
References commands.
{
     return commands;
 }
getPreferences()
SWGPreferences * SWGSDRangel::SWGInstanceConfigResponse::getPreferences ()
Definition at line 133 of file SWGInstanceConfigResponse.cpp.
References preferences.
Referenced by WebAPIAdapterGUI::instanceConfigGet(), and WebAPIAdapterSrv::instanceConfigGet().
{
     return preferences;
 }
getPresets()
QList< SWGPreset * > * SWGSDRangel::SWGInstanceConfigResponse::getPresets ()
Definition at line 153 of file SWGInstanceConfigResponse.cpp.
References presets.
Referenced by WebAPIAdapterGUI::instanceConfigGet(), and WebAPIAdapterSrv::instanceConfigGet().
{
     return presets;
 }
getWorkingPreset()
SWGPreset * SWGSDRangel::SWGInstanceConfigResponse::getWorkingPreset ()
Definition at line 143 of file SWGInstanceConfigResponse.cpp.
References working_preset.
Referenced by WebAPIAdapterGUI::instanceConfigGet(), and WebAPIAdapterSrv::instanceConfigGet().
{
     return working_preset;
 }
init()
void SWGSDRangel::SWGInstanceConfigResponse::init ()
Definition at line 46 of file SWGInstanceConfigResponse.cpp.
References commands, m_commands_isSet, m_preferences_isSet, m_presets_isSet, m_working_preset_isSet, preferences, presets, and working_preset.
Referenced by WebAPIAdapterGUI::instanceConfigGet(), WebAPIAdapterSrv::instanceConfigGet(), and SWGInstanceConfigResponse().
{
     preferences = new SWGPreferences();
     m_preferences_isSet = false;
     working_preset = new SWGPreset();
     m_working_preset_isSet = false;
     presets = new QList<SWGPreset*>();
     m_presets_isSet = false;
     commands = new QList<SWGCommand*>();
     m_commands_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGInstanceConfigResponse::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 174 of file SWGInstanceConfigResponse.cpp.
References commands, SWGSDRangel::SWGPreferences::isSet(), SWGSDRangel::SWGPreset::isSet(), preferences, presets, and working_preset.
{
     bool isObjectUpdated = false;
     do{
         if(preferences != nullptr && preferences->isSet()){ isObjectUpdated = true; break;}
         if(working_preset != nullptr && working_preset->isSet()){ isObjectUpdated = true; break;}
         if(presets->size() > 0){ isObjectUpdated = true; break;}
         if(commands->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setCommands()
void SWGSDRangel::SWGInstanceConfigResponse::setCommands (QList< SWGCommand *> * commands)
Definition at line 167 of file SWGInstanceConfigResponse.cpp.
References commands, and m_commands_isSet.
{
     this->commands = commands;
     this->m_commands_isSet = true;
 }
setPreferences()
void SWGSDRangel::SWGInstanceConfigResponse::setPreferences (SWGPreferences * preferences)
Definition at line 137 of file SWGInstanceConfigResponse.cpp.
References m_preferences_isSet, and preferences.
{
     this->preferences = preferences;
     this->m_preferences_isSet = true;
 }
setPresets()
void SWGSDRangel::SWGInstanceConfigResponse::setPresets (QList< SWGPreset *> * presets)
Definition at line 157 of file SWGInstanceConfigResponse.cpp.
References m_presets_isSet, and presets.
{
     this->presets = presets;
     this->m_presets_isSet = true;
 }
setWorkingPreset()
void SWGSDRangel::SWGInstanceConfigResponse::setWorkingPreset (SWGPreset * working_preset)
Definition at line 147 of file SWGInstanceConfigResponse.cpp.
References m_working_preset_isSet, and working_preset.
{
     this->working_preset = working_preset;
     this->m_working_preset_isSet = true;
 }
Member Data Documentation
commands
QList<SWGCommand*>* SWGSDRangel::SWGInstanceConfigResponse::commands private
Definition at line 73 of file SWGInstanceConfigResponse.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getCommands(), init(), isSet(), setCommands(), and SWGInstanceConfigResponse().
m_commands_isSet
bool SWGSDRangel::SWGInstanceConfigResponse::m_commands_isSet private
Definition at line 74 of file SWGInstanceConfigResponse.h.
Referenced by init(), setCommands(), and SWGInstanceConfigResponse().
m_preferences_isSet
bool SWGSDRangel::SWGInstanceConfigResponse::m_preferences_isSet private
Definition at line 65 of file SWGInstanceConfigResponse.h.
Referenced by init(), setPreferences(), and SWGInstanceConfigResponse().
m_presets_isSet
bool SWGSDRangel::SWGInstanceConfigResponse::m_presets_isSet private
Definition at line 71 of file SWGInstanceConfigResponse.h.
Referenced by init(), setPresets(), and SWGInstanceConfigResponse().
m_working_preset_isSet
bool SWGSDRangel::SWGInstanceConfigResponse::m_working_preset_isSet private
Definition at line 68 of file SWGInstanceConfigResponse.h.
Referenced by init(), setWorkingPreset(), and SWGInstanceConfigResponse().
preferences
SWGPreferences* SWGSDRangel::SWGInstanceConfigResponse::preferences private
Definition at line 64 of file SWGInstanceConfigResponse.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getPreferences(), init(), isSet(), setPreferences(), and SWGInstanceConfigResponse().
presets
QList<SWGPreset*>* SWGSDRangel::SWGInstanceConfigResponse::presets private
Definition at line 70 of file SWGInstanceConfigResponse.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getPresets(), init(), isSet(), setPresets(), and SWGInstanceConfigResponse().
working_preset
SWGPreset* SWGSDRangel::SWGInstanceConfigResponse::working_preset private
Definition at line 67 of file SWGInstanceConfigResponse.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getWorkingPreset(), init(), isSet(), setWorkingPreset(), and SWGInstanceConfigResponse().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGInstanceConfigResponse.h
swagger/sdrangel/code/qt5/client/SWGInstanceConfigResponse.cpp