SDRAngel: RemoteInputGui Class Reference
RemoteInputGui Class Reference
#include <remoteinputgui.h>
Public Member Functions
RemoteInputGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~RemoteInputGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_apiApplyButton_clicked (bool checked)
void on_dataApplyButton_clicked (bool checked)
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_apiAddress_returnPressed ()
void on_apiPort_returnPressed ()
void on_dataAddress_returnPressed ()
void on_dataPort_returnPressed ()
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void on_eventCountsReset_clicked (bool checked)
void updateHardware ()
void updateStatus ()
void networkManagerFinished (QNetworkReply *reply)
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void displayTime ()
void sendSettings ()
void updateWithAcquisition ()
void updateWithStreamTime ()
void updateSampleRateAndFrequency ()
void displayEventCounts ()
void displayEventTimer ()
void analyzeApiReply (const QJsonObject &jsonObject)
Private Attributes
Ui::RemoteInputGui * ui
DeviceUISet * m_deviceUISet
RemoteInputSettings m_settings
current settings
RemoteInput * m_sampleSource
bool m_acquisition
int m_streamSampleRate
Sample rate of received stream.
quint64 m_streamCenterFrequency
Center frequency of received stream.
QTimer m_updateTimer
QTimer m_statusTimer
int m_lastEngineState
MessageQueue m_inputMessageQueue
uint64_t m_startingTimeStampms
int m_framesDecodingStatus
bool m_allBlocksReceived
float m_bufferLengthInSecs
int32_t m_bufferGauge
int m_minNbBlocks
int m_minNbOriginalBlocks
int m_maxNbRecovery
float m_avgNbBlocks
float m_avgNbOriginalBlocks
float m_avgNbRecovery
int m_nbOriginalBlocks
int m_nbFECBlocks
int m_sampleBits
int m_sampleBytes
int m_samplesCount
std::size_t m_tickCount
bool m_addressEdited
bool m_dataPortEdited
uint32_t m_countUnrecoverable
uint32_t m_countRecovered
QTime m_eventsTime
bool m_doApplySettings
bool m_forceSettings
double m_txDelay
QPalette m_paletteGreenText
QPalette m_paletteWhiteText
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Detailed Description
Definition at line 39 of file remoteinputgui.h.
Constructor & Destructor Documentation
RemoteInputGui()
RemoteInputGui::RemoteInputGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 47 of file remoteinputgui.cpp.
References displayEventCounts(), displayEventTimer(), displaySettings(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_eventsTime, m_forceSettings, m_inputMessageQueue, m_networkManager, m_paletteGreenText, m_paletteWhiteText, m_sampleSource, m_startingTimeStampms, m_statusTimer, m_updateTimer, networkManagerFinished(), openDeviceSettingsDialog(), sendSettings(), RemoteInput::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                                         :
     QWidget(parent),
     ui(new Ui::RemoteInputGui),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_sampleSource(0),
     m_acquisition(false),
     m_streamSampleRate(0),
     m_streamCenterFrequency(0),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_framesDecodingStatus(0),
     m_bufferLengthInSecs(0.0),
     m_bufferGauge(-50),
     m_nbOriginalBlocks(128),
     m_nbFECBlocks(0),
     m_sampleBits(16), // assume 16 bits to start with
     m_sampleBytes(2),
     m_samplesCount(0),
     m_tickCount(0),
     m_addressEdited(false),
     m_dataPortEdited(false),
     m_countUnrecoverable(0),
     m_countRecovered(0),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_txDelay(0.0)
 {
     m_paletteGreenText.setColor(QPalette::WindowText, Qt::green);
     m_paletteWhiteText.setColor(QPalette::WindowText, Qt::white);
     m_startingTimeStampms = 0;
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, 0, 9999999U);
     ui->centerFrequencyHz->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequencyHz->setValueRange(3, 0, 999U);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     m_sampleSource = (RemoteInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     m_eventsTime.start();
     displayEventCounts();
     displayEventTimer();
     m_forceSettings = true;
     sendSettings();
 }
~RemoteInputGui()
RemoteInputGui::~RemoteInputGui () virtual
Definition at line 111 of file remoteinputgui.cpp.
References m_networkManager, networkManagerFinished(), and ui.
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     delete ui;
 }
Member Function Documentation
analyzeApiReply()
void RemoteInputGui::analyzeApiReply (const QJsonObject & jsonObject) private
Definition at line 617 of file remoteinputgui.cpp.
References ui.
Referenced by networkManagerFinished().
 {
     QString infoLine;
     if (jsonObject.contains("version")) {
         infoLine = jsonObject["version"].toString();
     }
     if (jsonObject.contains("qtVersion")) {
         infoLine += " Qt" + jsonObject["qtVersion"].toString();
     }
     if (jsonObject.contains("architecture")) {
         infoLine += " " + jsonObject["architecture"].toString();
     }
     if (jsonObject.contains("os")) {
         infoLine += " " + jsonObject["os"].toString();
     }
     if (jsonObject.contains("dspRxBits") && jsonObject.contains("dspTxBits")) {
         infoLine +=  QString(" %1/%2b").arg(jsonObject["dspRxBits"].toInt()).arg(jsonObject["dspTxBits"].toInt());
     }
     if (infoLine.size() > 0) {
         ui->infoText->setText(infoLine);
     }
 }
blockApplySettings()
void RemoteInputGui::blockApplySettings (bool block) private
Definition at line 118 of file remoteinputgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), handleMessage(), and updateSampleRateAndFrequency().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool RemoteInputGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 151 of file remoteinputgui.cpp.
References RemoteInputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, and sendSettings().
 {
     qDebug("RemoteInputGui::deserialize");
     if (m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         return false;
     }
 }
destroy()
void RemoteInputGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 123 of file remoteinputgui.cpp.
 {
     delete this;
 }
displayEventCounts()
void RemoteInputGui::displayEventCounts () private
Definition at line 450 of file remoteinputgui.cpp.
References m_countRecovered, m_countUnrecoverable, and ui.
Referenced by on_eventCountsReset_clicked(), RemoteInputGui(), and updateWithStreamTime().
 {
     QString nstr = QString("%1").arg(m_countUnrecoverable, 3, 10, QChar('0'));
     ui->eventUnrecText->setText(nstr);
     nstr = QString("%1").arg(m_countRecovered, 3, 10, QChar('0'));
     ui->eventRecText->setText(nstr);
 }
displayEventTimer()
void RemoteInputGui::displayEventTimer () private
Definition at line 458 of file remoteinputgui.cpp.
References m_eventsTime, and ui.
Referenced by on_eventCountsReset_clicked(), RemoteInputGui(), and updateWithStreamTime().
 {
     int elapsedTimeMillis = m_eventsTime.elapsed();
     QTime recordLength(0, 0, 0, 0);
     recordLength = recordLength.addSecs(elapsedTimeMillis/1000);
     QString s_time = recordLength.toString("HH:mm:ss");
     ui->eventCountsTimeText->setText(s_time);
 }
displaySettings()
void RemoteInputGui::displaySettings () private
Definition at line 294 of file remoteinputgui.cpp.
References arg(), blockApplySettings(), RemoteInputSettings::m_apiAddress, RemoteInputSettings::m_apiPort, RemoteInputSettings::m_dataAddress, RemoteInputSettings::m_dataPort, RemoteInputSettings::m_dcBlock, RemoteInputSettings::m_iqCorrection, m_settings, m_streamCenterFrequency, m_streamSampleRate, and ui.
Referenced by deserialize(), handleMessage(), RemoteInputGui(), and resetToDefaults().
 {
     blockApplySettings(true);
     ui->centerFrequency->setValue(m_streamCenterFrequency / 1000);
     ui->centerFrequencyHz->setValue(m_streamCenterFrequency % 1000);
     ui->deviceRateText->setText(tr("%1k").arg(m_streamSampleRate / 1000.0));
     ui->apiAddress->setText(m_settings.m_apiAddress);
     ui->apiPort->setText(tr("%1").arg(m_settings.m_apiPort));
     ui->dataPort->setText(tr("%1").arg(m_settings.m_dataPort));
     ui->dataAddress->setText(m_settings.m_dataAddress);
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqCorrection);
     blockApplySettings(false);
 }
displayTime()
void RemoteInputGui::displayTime () private
getCenterFrequency()
qint64 RemoteInputGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 169 of file remoteinputgui.cpp.
References m_streamCenterFrequency.
 {
     return m_streamCenterFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* RemoteInputGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 55 of file remoteinputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString RemoteInputGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 133 of file remoteinputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void RemoteInputGui::handleInputMessages () private slot
Definition at line 247 of file remoteinputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), DeviceSampleSource::getInputMessageQueue(), DSPSignalNotification::getSampleRate(), handleMessage(), m_inputMessageQueue, m_sampleSource, m_streamCenterFrequency, m_streamSampleRate, Message::match(), MessageQueue::pop(), MessageQueue::push(), and updateSampleRateAndFrequency().
Referenced by RemoteInputGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         //qDebug("RemoteInputGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             if (notif->getSampleRate() != m_streamSampleRate) {
                 m_streamSampleRate = notif->getSampleRate();
             }
             m_streamCenterFrequency = notif->getCenterFrequency();
             qDebug("RemoteInputGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             DSPSignalNotification *fwd = new DSPSignalNotification(*notif);
             m_sampleSource->getInputMessageQueue()->push(fwd);
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool RemoteInputGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 179 of file remoteinputgui.cpp.
References blockApplySettings(), displaySettings(), RemoteInput::MsgConfigureRemoteInput::getSettings(), RemoteInput::MsgStartStop::getStartStop(), m_acquisition, m_allBlocksReceived, m_avgNbBlocks, m_avgNbOriginalBlocks, m_avgNbRecovery, m_bufferGauge, m_bufferLengthInSecs, m_framesDecodingStatus, m_maxNbRecovery, m_minNbBlocks, m_minNbOriginalBlocks, m_nbFECBlocks, m_nbOriginalBlocks, m_sampleBits, m_sampleBytes, m_settings, m_startingTimeStampms, Message::match(), ui, updateWithAcquisition(), and updateWithStreamTime().
Referenced by handleInputMessages().
 {
     if (RemoteInput::MsgConfigureRemoteInput::match(message))
     {
         const RemoteInput::MsgConfigureRemoteInput& cfg = (RemoteInput::MsgConfigureRemoteInput&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (RemoteInput::MsgReportRemoteInputAcquisition::match(message))
     {
         m_acquisition = ((RemoteInput::MsgReportRemoteInputAcquisition&)message).getAcquisition();
         updateWithAcquisition();
         return true;
     }
     else if (RemoteInput::MsgReportRemoteInputStreamData::match(message))
     {
         m_startingTimeStampms = ((RemoteInput::MsgReportRemoteInputStreamData&)message).get_tv_msec();
         qDebug() << "RemoteInputGui::handleMessage: RemoteInput::MsgReportRemoteInputStreamData: "
                 << " : " << m_startingTimeStampms << " ms";
         updateWithStreamTime();
         return true;
     }
     else if (RemoteInput::MsgReportRemoteInputStreamTiming::match(message))
     {
         m_startingTimeStampms = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).get_tv_msec();
         m_framesDecodingStatus = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).getFramesDecodingStatus();
         m_allBlocksReceived = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).allBlocksReceived();
         m_bufferLengthInSecs = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).getBufferLengthInSecs();
         m_bufferGauge = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).getBufferGauge();
         m_minNbBlocks = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).getMinNbBlocks();
         m_minNbOriginalBlocks = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).getMinNbOriginalBlocks();
         m_maxNbRecovery = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).getMaxNbRecovery();
         m_avgNbBlocks = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).getAvgNbBlocks();
         m_avgNbOriginalBlocks = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).getAvgNbOriginalBlocks();
         m_avgNbRecovery = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).getAvgNbRecovery();
         m_nbOriginalBlocks = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).getNbOriginalBlocksPerFrame();
         m_sampleBits = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).getSampleBits();
         m_sampleBytes = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).getSampleBytes();
         int nbFECBlocks = ((RemoteInput::MsgReportRemoteInputStreamTiming&)message).getNbFECBlocksPerFrame();
         if (m_nbFECBlocks != nbFECBlocks) {
             m_nbFECBlocks = nbFECBlocks;
         }
         updateWithStreamTime();
         return true;
     }
     else if (RemoteInput::MsgStartStop::match(message))
     {
         RemoteInput::MsgStartStop& notif = (RemoteInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
networkManagerFinished
void RemoteInputGui::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 577 of file remoteinputgui.cpp.
References analyzeApiReply(), and ui.
Referenced by RemoteInputGui(), and ~RemoteInputGui().
 {
     if (reply->error())
     {
         ui->apiAddressLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
         ui->statusText->setText(reply->errorString());
         return;
     }
     QString answer = reply->readAll();
     try
     {
         QByteArray jsonBytes(answer.toStdString().c_str());
         QJsonParseError error;
         QJsonDocument doc = QJsonDocument::fromJson(jsonBytes, &error);
         if (error.error == QJsonParseError::NoError)
         {
             ui->apiAddressLabel->setStyleSheet("QLabel { background-color : green; }");
             ui->statusText->setText(QString("API OK"));
             analyzeApiReply(doc.object());
         }
         else
         {
             ui->apiAddressLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
             QString errorMsg = QString("Reply JSON error: ") + error.errorString() + QString(" at offset ") + QString::number(error.offset);
             ui->statusText->setText(QString("JSON error. See log"));
             qInfo().noquote() << "RemoteInputGui::networkManagerFinished" << errorMsg;
         }
     }
     catch (const std::exception& ex)
     {
         ui->apiAddressLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
         QString errorMsg = QString("Error parsing request: ") + ex.what();
         ui->statusText->setText("Error parsing request. See log for details");
         qInfo().noquote() << "RemoteInputGui::networkManagerFinished" << errorMsg;
     }
 }
on_apiAddress_returnPressed
void RemoteInputGui::on_apiAddress_returnPressed () private slot
Definition at line 353 of file remoteinputgui.cpp.
References RemoteInputSettings::m_apiAddress, RemoteInputSettings::m_apiPort, m_networkManager, m_networkRequest, m_settings, sendSettings(), and ui.
 {
     m_settings.m_apiAddress = ui->apiAddress->text();
     QString infoURL = QString("http://%1:%2/sdrangel").arg(m_settings.m_apiAddress).arg(m_settings.m_apiPort);
     m_networkRequest.setUrl(QUrl(infoURL));
     m_networkManager->get(m_networkRequest);
     sendSettings();
 }
on_apiApplyButton_clicked
void RemoteInputGui::on_apiApplyButton_clicked (bool checked) private slot
Definition at line 319 of file remoteinputgui.cpp.
References RemoteInputSettings::m_apiAddress, RemoteInputSettings::m_apiPort, m_networkManager, m_networkRequest, m_settings, sendSettings(), and ui.
 {
     (void) checked;
     m_settings.m_apiAddress = ui->apiAddress->text();
     bool ctlOk;
     int udpApiPort = ui->apiPort->text().toInt(&ctlOk);
     if((ctlOk) && (udpApiPort >= 1024) && (udpApiPort < 65535)) {
         m_settings.m_apiPort = udpApiPort;
     }
     sendSettings();
     QString infoURL = QString("http://%1:%2/sdrangel").arg(m_settings.m_apiAddress).arg(m_settings.m_apiPort);
     m_networkRequest.setUrl(QUrl(infoURL));
     m_networkManager->get(m_networkRequest);
 }
on_apiPort_returnPressed
void RemoteInputGui::on_apiPort_returnPressed () private slot
Definition at line 386 of file remoteinputgui.cpp.
References RemoteInputSettings::m_apiAddress, RemoteInputSettings::m_apiPort, m_networkManager, m_networkRequest, m_settings, sendSettings(), and ui.
 {
     bool ctlOk;
     int udpApiPort = ui->apiPort->text().toInt(&ctlOk);
     if((!ctlOk) || (udpApiPort < 1024) || (udpApiPort > 65535))
     {
         return;
     }
     else
     {
         m_settings.m_apiPort = udpApiPort;
         QString infoURL = QString("http://%1:%2/sdrangel").arg(m_settings.m_apiAddress).arg(m_settings.m_apiPort);
         m_networkRequest.setUrl(QUrl(infoURL));
         m_networkManager->get(m_networkRequest);
         sendSettings();
     }
 }
on_dataAddress_returnPressed
void RemoteInputGui::on_dataAddress_returnPressed () private slot
Definition at line 364 of file remoteinputgui.cpp.
References RemoteInputSettings::m_dataAddress, m_settings, sendSettings(), and ui.
 {
     m_settings.m_dataAddress = ui->dataAddress->text();
     sendSettings();
 }
on_dataApplyButton_clicked
void RemoteInputGui::on_dataApplyButton_clicked (bool checked) private slot
Definition at line 338 of file remoteinputgui.cpp.
References RemoteInputSettings::m_dataAddress, RemoteInputSettings::m_dataPort, m_settings, sendSettings(), and ui.
 {
     (void) checked;
     m_settings.m_dataAddress = ui->dataAddress->text();
     bool dataOk;
     int udpDataPort = ui->dataPort->text().toInt(&dataOk);
     if((dataOk) && (udpDataPort >= 1024) && (udpDataPort < 65535)) {
         m_settings.m_dataPort = udpDataPort;
     }
     sendSettings();
 }
on_dataPort_returnPressed
void RemoteInputGui::on_dataPort_returnPressed () private slot
Definition at line 370 of file remoteinputgui.cpp.
References RemoteInputSettings::m_dataPort, m_settings, sendSettings(), and ui.
 {
     bool dataOk;
     int udpDataPort = ui->dataPort->text().toInt(&dataOk);
     if((!dataOk) || (udpDataPort < 1024) || (udpDataPort > 65535))
     {
         return;
     }
     else
     {
         m_settings.m_dataPort = udpDataPort;
         sendSettings();
     }
 }
on_dcOffset_toggled
void RemoteInputGui::on_dcOffset_toggled (bool checked) private slot
Definition at line 407 of file remoteinputgui.cpp.
References RemoteInputSettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_eventCountsReset_clicked
void RemoteInputGui::on_eventCountsReset_clicked (bool checked) private slot
Definition at line 440 of file remoteinputgui.cpp.
References displayEventCounts(), displayEventTimer(), m_countRecovered, m_countUnrecoverable, and m_eventsTime.
 {
     (void) checked;
     m_countUnrecoverable = 0;
     m_countRecovered = 0;
     m_eventsTime.start();
     displayEventCounts();
     displayEventTimer();
 }
on_iqImbalance_toggled
void RemoteInputGui::on_iqImbalance_toggled (bool checked) private slot
Definition at line 413 of file remoteinputgui.cpp.
References RemoteInputSettings::m_iqCorrection, m_settings, and sendSettings().
 {
     m_settings.m_iqCorrection = checked;
     sendSettings();
 }
on_record_toggled
void RemoteInputGui::on_record_toggled (bool checked) private slot
Definition at line 428 of file remoteinputgui.cpp.
References RemoteInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     RemoteInput::MsgFileRecord* message = RemoteInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_startStop_toggled
void RemoteInputGui::on_startStop_toggled (bool checked) private slot
Definition at line 419 of file remoteinputgui.cpp.
References RemoteInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         RemoteInput::MsgStartStop *message = RemoteInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
openDeviceSettingsDialog
void RemoteInputGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 646 of file remoteinputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), RemoteInputSettings::m_reverseAPIAddress, RemoteInputSettings::m_reverseAPIDeviceIndex, RemoteInputSettings::m_reverseAPIPort, m_settings, RemoteInputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by RemoteInputGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void RemoteInputGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 138 of file remoteinputgui.cpp.
References displaySettings(), m_forceSettings, m_settings, RemoteInputSettings::resetToDefaults(), and sendSettings().
 {
     m_settings.resetToDefaults();
     displaySettings();
     m_forceSettings = true;
     sendSettings();
 }
sendSettings()
void RemoteInputGui::sendSettings () private
Definition at line 313 of file remoteinputgui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_apiAddress_returnPressed(), on_apiApplyButton_clicked(), on_apiPort_returnPressed(), on_dataAddress_returnPressed(), on_dataApplyButton_clicked(), on_dataPort_returnPressed(), on_dcOffset_toggled(), on_iqImbalance_toggled(), openDeviceSettingsDialog(), RemoteInputGui(), and resetToDefaults().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray RemoteInputGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 146 of file remoteinputgui.cpp.
References m_settings, and RemoteInputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void RemoteInputGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 174 of file remoteinputgui.cpp.
 {
     (void) centerFrequency;
 }
setName()
void RemoteInputGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 128 of file remoteinputgui.cpp.
 {
     setObjectName(name);
 }
updateHardware
void RemoteInputGui::updateHardware () private slot
Definition at line 524 of file remoteinputgui.cpp.
References RemoteInput::MsgConfigureRemoteInput::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by RemoteInputGui().
 {
     if (m_doApplySettings)
     {
         qDebug() << "RemoteInputGui::updateHardware";
         RemoteInput::MsgConfigureRemoteInput* message =
                 RemoteInput::MsgConfigureRemoteInput::create(m_settings, m_forceSettings);
         m_sampleSource->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void RemoteInputGui::updateSampleRateAndFrequency () private
Definition at line 283 of file remoteinputgui.cpp.
References arg(), blockApplySettings(), DeviceUISet::getSpectrum(), m_deviceUISet, m_streamCenterFrequency, m_streamSampleRate, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_streamSampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_streamCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg((float)m_streamSampleRate / 1000));
     blockApplySettings(true);
     ui->centerFrequency->setValue(m_streamCenterFrequency / 1000);
     ui->centerFrequencyHz->setValue(m_streamCenterFrequency % 1000);
     blockApplySettings(false);
 }
updateStatus
void RemoteInputGui::updateStatus () private slot
Definition at line 537 of file remoteinputgui.cpp.
References DeviceAPI::errorMessage(), RemoteInput::isStreaming(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, m_sampleSource, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by RemoteInputGui().
 {
     if (m_sampleSource->isStreaming())
     {
         int state = m_deviceUISet->m_deviceAPI->state();
         if (m_lastEngineState != state)
         {
             switch(state)
             {
                 case DeviceAPI::StNotStarted:
                     ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                     break;
                 case DeviceAPI::StIdle:
                     ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                     break;
                 case DeviceAPI::StRunning:
                     ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                     break;
                 case DeviceAPI::StError:
                     ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                     QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                     break;
                 default:
                     break;
             }
             m_lastEngineState = state;
         }
         ui->startStop->setEnabled(true);
     }
     else
     {
         ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         ui->startStop->setChecked(false);
         ui->startStop->setEnabled(false);
     }
 }
updateWithAcquisition()
void RemoteInputGui::updateWithAcquisition () private
Definition at line 467 of file remoteinputgui.cpp.
Referenced by handleMessage().
 {
 }
updateWithStreamTime()
void RemoteInputGui::updateWithStreamTime () private
Definition at line 471 of file remoteinputgui.cpp.
References arg(), displayEventCounts(), displayEventTimer(), m_bufferGauge, m_bufferLengthInSecs, m_countRecovered, m_countUnrecoverable, m_framesDecodingStatus, m_maxNbRecovery, m_minNbBlocks, m_nbFECBlocks, m_nbOriginalBlocks, m_sampleBits, m_startingTimeStampms, and ui.
Referenced by handleMessage().
 {
     bool updateEventCounts = false;
     QDateTime dt = QDateTime::fromMSecsSinceEpoch(m_startingTimeStampms);
     QString s_date = dt.toString("yyyy-MM-dd  HH:mm:ss.zzz");
     ui->absTimeText->setText(s_date);
     if (m_framesDecodingStatus == 2)
     {
         ui->allFramesDecoded->setStyleSheet("QToolButton { background-color : green; }");
     }
     else if (m_framesDecodingStatus == 1)
     {
         if (m_countRecovered < 999) m_countRecovered++;
         updateEventCounts = true;
         ui->allFramesDecoded->setStyleSheet("QToolButton { background:rgb(56,56,56); }");
     }
     else
     {
         if (m_countUnrecoverable < 999) m_countUnrecoverable++;
         updateEventCounts = true;
         ui->allFramesDecoded->setStyleSheet("QToolButton { background-color : red; }");
     }
     QString s = QString::number(m_bufferLengthInSecs, 'f', 1);
     ui->bufferLenSecsText->setText(tr("%1").arg(s));
     s = QString::number(m_bufferGauge, 'f', 0);
     ui->bufferRWBalanceText->setText(tr("%1").arg(s));
     ui->bufferGaugeNegative->setValue((m_bufferGauge < 0 ? -m_bufferGauge : 0));
     ui->bufferGaugePositive->setValue((m_bufferGauge < 0 ? 0 : m_bufferGauge));
     s = QString::number(m_minNbBlocks, 'f', 0);
     ui->minNbBlocksText->setText(tr("%1").arg(s));
     s = QString("%1").arg(m_maxNbRecovery, 2, 10, QChar('0'));
     ui->maxNbRecoveryText->setText(tr("%1").arg(s));
     s = QString::number(m_nbOriginalBlocks + m_nbFECBlocks, 'f', 0);
     QString s1 = QString("%1").arg(m_nbFECBlocks, 2, 10, QChar('0'));
     ui->nominalNbBlocksText->setText(tr("%1/%2").arg(s).arg(s1));
     ui->sampleBitsText->setText(tr("%1b").arg(m_sampleBits));
     if (updateEventCounts)
     {
         displayEventCounts();
     }
     displayEventTimer();
 }
Member Data Documentation
m_acquisition
bool RemoteInputGui::m_acquisition private
Definition at line 64 of file remoteinputgui.h.
Referenced by handleMessage().
m_addressEdited
bool RemoteInputGui::m_addressEdited private
Definition at line 93 of file remoteinputgui.h.
m_allBlocksReceived
bool RemoteInputGui::m_allBlocksReceived private
Definition at line 76 of file remoteinputgui.h.
Referenced by handleMessage().
m_avgNbBlocks
float RemoteInputGui::m_avgNbBlocks private
Definition at line 82 of file remoteinputgui.h.
Referenced by handleMessage().
m_avgNbOriginalBlocks
float RemoteInputGui::m_avgNbOriginalBlocks private
Definition at line 83 of file remoteinputgui.h.
Referenced by handleMessage().
m_avgNbRecovery
float RemoteInputGui::m_avgNbRecovery private
Definition at line 84 of file remoteinputgui.h.
Referenced by handleMessage().
m_bufferGauge
int32_t RemoteInputGui::m_bufferGauge private
Definition at line 78 of file remoteinputgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_bufferLengthInSecs
float RemoteInputGui::m_bufferLengthInSecs private
Definition at line 77 of file remoteinputgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_countRecovered
uint32_t RemoteInputGui::m_countRecovered private
Definition at line 97 of file remoteinputgui.h.
Referenced by displayEventCounts(), on_eventCountsReset_clicked(), and updateWithStreamTime().
m_countUnrecoverable
uint32_t RemoteInputGui::m_countUnrecoverable private
Definition at line 96 of file remoteinputgui.h.
Referenced by displayEventCounts(), on_eventCountsReset_clicked(), and updateWithStreamTime().
m_dataPortEdited
bool RemoteInputGui::m_dataPortEdited private
Definition at line 94 of file remoteinputgui.h.
m_deviceUISet
DeviceUISet* RemoteInputGui::m_deviceUISet private
Definition at line 61 of file remoteinputgui.h.
Referenced by RemoteInputGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool RemoteInputGui::m_doApplySettings private
Definition at line 100 of file remoteinputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_eventsTime
QTime RemoteInputGui::m_eventsTime private
Definition at line 98 of file remoteinputgui.h.
Referenced by displayEventTimer(), on_eventCountsReset_clicked(), and RemoteInputGui().
m_forceSettings
bool RemoteInputGui::m_forceSettings private
Definition at line 101 of file remoteinputgui.h.
Referenced by deserialize(), RemoteInputGui(), resetToDefaults(), and updateHardware().
m_framesDecodingStatus
int RemoteInputGui::m_framesDecodingStatus private
Definition at line 75 of file remoteinputgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_inputMessageQueue
MessageQueue RemoteInputGui::m_inputMessageQueue private
Definition at line 70 of file remoteinputgui.h.
Referenced by handleInputMessages(), and RemoteInputGui().
m_lastEngineState
int RemoteInputGui::m_lastEngineState private
Definition at line 69 of file remoteinputgui.h.
Referenced by updateStatus().
m_maxNbRecovery
int RemoteInputGui::m_maxNbRecovery private
Definition at line 81 of file remoteinputgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_minNbBlocks
int RemoteInputGui::m_minNbBlocks private
Definition at line 79 of file remoteinputgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_minNbOriginalBlocks
int RemoteInputGui::m_minNbOriginalBlocks private
Definition at line 80 of file remoteinputgui.h.
Referenced by handleMessage().
m_nbFECBlocks
int RemoteInputGui::m_nbFECBlocks private
Definition at line 86 of file remoteinputgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_nbOriginalBlocks
int RemoteInputGui::m_nbOriginalBlocks private
Definition at line 85 of file remoteinputgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_networkManager
QNetworkAccessManager* RemoteInputGui::m_networkManager private
Definition at line 107 of file remoteinputgui.h.
Referenced by on_apiAddress_returnPressed(), on_apiApplyButton_clicked(), on_apiPort_returnPressed(), RemoteInputGui(), and ~RemoteInputGui().
m_networkRequest
QNetworkRequest RemoteInputGui::m_networkRequest private
Definition at line 108 of file remoteinputgui.h.
Referenced by on_apiAddress_returnPressed(), on_apiApplyButton_clicked(), and on_apiPort_returnPressed().
m_paletteGreenText
QPalette RemoteInputGui::m_paletteGreenText private
Definition at line 104 of file remoteinputgui.h.
Referenced by RemoteInputGui().
m_paletteWhiteText
QPalette RemoteInputGui::m_paletteWhiteText private
Definition at line 105 of file remoteinputgui.h.
Referenced by RemoteInputGui().
m_sampleBits
int RemoteInputGui::m_sampleBits private
Definition at line 87 of file remoteinputgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_sampleBytes
int RemoteInputGui::m_sampleBytes private
Definition at line 88 of file remoteinputgui.h.
Referenced by handleMessage().
m_samplesCount
int RemoteInputGui::m_samplesCount private
Definition at line 90 of file remoteinputgui.h.
m_sampleSource
RemoteInput* RemoteInputGui::m_sampleSource private
Definition at line 63 of file remoteinputgui.h.
Referenced by handleInputMessages(), on_record_toggled(), on_startStop_toggled(), RemoteInputGui(), updateHardware(), and updateStatus().
m_settings
RemoteInputSettings RemoteInputGui::m_settings private
current settings
Definition at line 62 of file remoteinputgui.h.
Referenced by deserialize(), displaySettings(), handleMessage(), on_apiAddress_returnPressed(), on_apiApplyButton_clicked(), on_apiPort_returnPressed(), on_dataAddress_returnPressed(), on_dataApplyButton_clicked(), on_dataPort_returnPressed(), on_dcOffset_toggled(), on_iqImbalance_toggled(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), and updateHardware().
m_startingTimeStampms
uint64_t RemoteInputGui::m_startingTimeStampms private
Definition at line 74 of file remoteinputgui.h.
Referenced by handleMessage(), RemoteInputGui(), and updateWithStreamTime().
m_statusTimer
QTimer RemoteInputGui::m_statusTimer private
Definition at line 68 of file remoteinputgui.h.
Referenced by RemoteInputGui().
m_streamCenterFrequency
quint64 RemoteInputGui::m_streamCenterFrequency private
Center frequency of received stream.
Definition at line 66 of file remoteinputgui.h.
Referenced by displaySettings(), getCenterFrequency(), handleInputMessages(), and updateSampleRateAndFrequency().
m_streamSampleRate
int RemoteInputGui::m_streamSampleRate private
Sample rate of received stream.
Definition at line 65 of file remoteinputgui.h.
Referenced by displaySettings(), handleInputMessages(), and updateSampleRateAndFrequency().
m_tickCount
std::size_t RemoteInputGui::m_tickCount private
Definition at line 91 of file remoteinputgui.h.
m_txDelay
double RemoteInputGui::m_txDelay private
Definition at line 102 of file remoteinputgui.h.
m_updateTimer
QTimer RemoteInputGui::m_updateTimer private
Definition at line 67 of file remoteinputgui.h.
Referenced by RemoteInputGui(), sendSettings(), and updateHardware().
ui
Ui::RemoteInputGui* RemoteInputGui::ui private
Definition at line 59 of file remoteinputgui.h.
Referenced by analyzeApiReply(), displayEventCounts(), displayEventTimer(), displaySettings(), handleMessage(), networkManagerFinished(), on_apiAddress_returnPressed(), on_apiApplyButton_clicked(), on_apiPort_returnPressed(), on_dataAddress_returnPressed(), on_dataApplyButton_clicked(), on_dataPort_returnPressed(), on_record_toggled(), RemoteInputGui(), updateSampleRateAndFrequency(), updateStatus(), updateWithStreamTime(), and ~RemoteInputGui().
The documentation for this class was generated from the following files:
plugins/samplesource/remoteinput/remoteinputgui.h
plugins/samplesource/remoteinput/remoteinputgui.cpp