SDRAngel: TVScreen Class Reference
TVScreen Class Reference
#include <tvscreen.h>
Signals
void traceSizeChanged (int)
void sampleRateChanged (int)
Public Member Functions
TVScreen (bool blnColor, QWidget *parent=0)
virtual ~TVScreen ()
void setColor (bool blnColor)
void resizeTVScreen (int intCols, int intRows)
void getSize (int &intCols, int &intRows) const
void renderImage (unsigned char *objData)
QRgb * getRowBuffer (int intRow)
void resetImage ()
void resetImage (int alpha)
bool selectRow (int intLine)
bool setDataColor (int intCol, int intRed, int intGreen, int intBlue)
bool setDataColor (int intCol, int intRed, int intGreen, int intBlue, int intAlpha)
void setAlphaBlend (bool blnAlphaBlend)
void setAlphaReset ()
void connectTimer (const QTimer &timer)
Static Public Attributes
static const int TV_COLS =256
static const int TV_ROWS =256
Protected Slots
void cleanup ()
void tick ()
Private Member Functions
void initializeGL ()
void resizeGL (int width, int height)
void paintGL ()
void mousePressEvent (QMouseEvent *)
Private Attributes
bool m_blnGLContextInitialized
int m_intAskedCols
int m_intAskedRows
QTimer m_objTimer
QMutex m_objMutex
bool m_blnDataChanged
bool m_blnConfigChanged
GLShaderTVArray m_objGLShaderArray
int m_cols
int m_rows
unsigned char * m_chrLastData
Detailed Description
Definition at line 39 of file tvscreen.h.
Constructor & Destructor Documentation
TVScreen()
TVScreen::TVScreen (bool blnColor, QWidget * parent = 0)
Definition at line 31 of file tvscreen.cpp.
References m_blnConfigChanged, m_blnDataChanged, m_blnGLContextInitialized, m_chrLastData, m_cols, m_intAskedCols, m_intAskedRows, m_objTimer, m_rows, tick(), TV_COLS, and TV_ROWS.
                                                  :
         QGLWidget(parent), m_objMutex(QMutex::NonRecursive), m_objGLShaderArray(blnColor)
 {
     setAttribute(Qt::WA_OpaquePaintEvent);
     connect(&m_objTimer, SIGNAL(timeout()), this, SLOT(tick()));
     m_objTimer.start(40); // capped at 25 FPS
     m_chrLastData = NULL;
     m_blnConfigChanged = false;
     m_blnDataChanged = false;
     m_blnGLContextInitialized = false;
     //Par défaut
     m_intAskedCols = TV_COLS;
     m_intAskedRows = TV_ROWS;
     m_cols = TV_COLS;
     m_rows = TV_ROWS;
 }
~TVScreen()
TVScreen::~TVScreen () virtual
Definition at line 50 of file tvscreen.cpp.
References cleanup().
 {
     cleanup();
 }
Member Function Documentation
cleanup
void TVScreen::cleanup () protected slot
Definition at line 204 of file tvscreen.cpp.
References GLShaderTVArray::Cleanup(), m_blnGLContextInitialized, and m_objGLShaderArray.
Referenced by initializeGL(), and ~TVScreen().
 {
     if (m_blnGLContextInitialized)
     {
         m_objGLShaderArray.Cleanup();
     }
 }
connectTimer()
void TVScreen::connectTimer (const QTimer & timer)
Definition at line 196 of file tvscreen.cpp.
References m_objTimer, and tick().
 {
      qDebug() << "TVScreen::connectTimer";
      disconnect(&m_objTimer, SIGNAL(timeout()), this, SLOT(tick()));
      connect(&objTimer, SIGNAL(timeout()), this, SLOT(tick()));
      m_objTimer.stop();
 }
getRowBuffer()
QRgb * TVScreen::getRowBuffer (int intRow)
Definition at line 60 of file tvscreen.cpp.
References GLShaderTVArray::GetRowBuffer(), m_blnGLContextInitialized, and m_objGLShaderArray.
 {
     if (!m_blnGLContextInitialized)
     {
         return NULL;
     }
     return m_objGLShaderArray.GetRowBuffer(intRow);
 }
getSize()
void TVScreen::getSize (int & intCols, int & intRows) const
Definition at line 95 of file tvscreen.cpp.
References m_cols, and m_rows.
Referenced by ScopeVisXY::feed().
 {
     intCols = m_cols;
     intRows = m_rows;
 }
initializeGL()
void TVScreen::initializeGL () private
Definition at line 101 of file tvscreen.cpp.
References cleanup(), m_blnGLContextInitialized, and m_objMutex.
 {
     m_objMutex.lock();
     QOpenGLContext *objGlCurrentContext = QOpenGLContext::currentContext();
     if (objGlCurrentContext)
     {
         if (QOpenGLContext::currentContext()->isValid())
         {
             qDebug() << "TVScreen::initializeGL: context:"
                     << " major: " << (QOpenGLContext::currentContext()->format()).majorVersion()
                     << " minor: " << (QOpenGLContext::currentContext()->format()).minorVersion()
                     << " ES: " << (QOpenGLContext::currentContext()->isOpenGLES() ? "yes" : "no");
         }
         else
         {
             qDebug() << "TVScreen::initializeGL: current context is invalid";
         }
     }
     else
     {
         qCritical() << "TVScreen::initializeGL: no current context";
         return;
     }
     QSurface *objSurface = objGlCurrentContext->surface();
     if (objSurface == NULL)
     {
         qCritical() << "TVScreen::initializeGL: no surface attached";
         return;
     }
     else
     {
         if (objSurface->surfaceType() != QSurface::OpenGLSurface)
         {
             qCritical() << "TVScreen::initializeGL: surface is not an OpenGLSurface: "
                     << objSurface->surfaceType()
                     << " cannot use an OpenGL context";
             return;
         }
         else
         {
             qDebug() << "TVScreen::initializeGL: OpenGL surface:"
                     << " class: " << (objSurface->surfaceClass() == QSurface::Window ? "Window" : "Offscreen");
         }
     }
     connect(objGlCurrentContext, &QOpenGLContext::aboutToBeDestroyed, this,
             &TVScreen::cleanup); // TODO: when migrating to QOpenGLWidget
     m_blnGLContextInitialized = true;
     m_objMutex.unlock();
 }
mousePressEvent()
void TVScreen::mousePressEvent (QMouseEvent * event) private
Definition at line 184 of file tvscreen.cpp.
 {
     (void) event;
 }
paintGL()
void TVScreen::paintGL () private
Definition at line 165 of file tvscreen.cpp.
References GLShaderTVArray::InitializeGL(), m_blnDataChanged, m_chrLastData, m_intAskedCols, m_intAskedRows, m_objGLShaderArray, m_objMutex, and GLShaderTVArray::RenderPixels().
 {
     if (!m_objMutex.tryLock(2))
         return;
     m_blnDataChanged = false;
     if ((m_intAskedCols != 0) && (m_intAskedRows != 0))
     {
         m_objGLShaderArray.InitializeGL(m_intAskedCols, m_intAskedRows);
         m_intAskedCols = 0;
         m_intAskedRows = 0;
     }
     m_objGLShaderArray.RenderPixels(m_chrLastData);
     m_objMutex.unlock();
 }
renderImage()
void TVScreen::renderImage (unsigned char * objData)
Definition at line 70 of file tvscreen.cpp.
References m_blnDataChanged, and m_chrLastData.
Referenced by ScopeVisXY::feed(), ATVDemod::processClassic(), ATVDemod::processHSkip(), DATVideoRender::RenderStream(), leansdr::datvconstellation< leansdr::f32 >::run(), and leansdr::datvdvbs2constellation< leansdr::f32 >::run().
 {
     m_chrLastData = objData;
     m_blnDataChanged = true;
 }
resetImage() [1/2]
void TVScreen::resetImage ()
Definition at line 76 of file tvscreen.cpp.
References m_objGLShaderArray, and GLShaderTVArray::ResetPixels().
Referenced by ScopeVisXY::feed(), DATVideoRender::RenderStream(), leansdr::datvconstellation< leansdr::f32 >::run(), and leansdr::datvdvbs2constellation< leansdr::f32 >::run().
 {
     m_objGLShaderArray.ResetPixels();
 }
resetImage() [2/2]
void TVScreen::resetImage (int alpha)
Definition at line 81 of file tvscreen.cpp.
References m_objGLShaderArray, and GLShaderTVArray::ResetPixels().
 {
     m_objGLShaderArray.ResetPixels(alpha);
 }
resizeGL()
void TVScreen::resizeGL (int width, int height) private
Definition at line 158 of file tvscreen.cpp.
References m_blnConfigChanged.
 {
     QOpenGLFunctions *ptrF = QOpenGLContext::currentContext()->functions();
     ptrF->glViewport(0, 0, intWidth, intHeight);
     m_blnConfigChanged = true;
 }
resizeTVScreen()
void TVScreen::resizeTVScreen (int intCols, int intRows)
Definition at line 86 of file tvscreen.cpp.
References m_cols, m_intAskedCols, m_intAskedRows, and m_rows.
Referenced by ATVDemod::applySettings(), and DATVideoRender::RenderStream().
 {
     qDebug("TVScreen::resizeTVScreen: cols: %d, rows: %d", intCols, intRows);
     m_intAskedCols = intCols;
     m_intAskedRows = intRows;
     m_cols = intCols;
     m_rows = intRows;
 }
sampleRateChanged
void TVScreen::sampleRateChanged (int) signal
selectRow()
bool TVScreen::selectRow (int intLine)
Definition at line 212 of file tvscreen.cpp.
References m_blnGLContextInitialized, m_objGLShaderArray, and GLShaderTVArray::SelectRow().
Referenced by ScopeVisXY::drawGraticule(), ScopeVisXY::feed(), ATVDemod::processClassic(), ATVDemod::processHSkip(), leansdr::datvconstellation< leansdr::f32 >::run(), and leansdr::datvdvbs2constellation< leansdr::f32 >::run().
 {
     if (m_blnGLContextInitialized)
     {
         return m_objGLShaderArray.SelectRow(intLine);
     }
     else
     {
         return false;
     }
 }
setAlphaBlend()
void TVScreen::setAlphaBlend (bool blnAlphaBlend) inline
Definition at line 59 of file tvscreen.h.
Referenced by ScopeVisXY::ScopeVisXY().
 { m_objGLShaderArray.setAlphaBlend(blnAlphaBlend); }
setAlphaReset()
void TVScreen::setAlphaReset () inline
Definition at line 60 of file tvscreen.h.
Referenced by ScopeVisXY::setPixelsPerFrame().
 { m_objGLShaderArray.setAlphaReset(); }
setColor()
void TVScreen::setColor (bool blnColor)
Definition at line 55 of file tvscreen.cpp.
References m_objGLShaderArray, and GLShaderTVArray::setColor().
 {
     m_objGLShaderArray.setColor(blnColor);
 }
setDataColor() [1/2]
bool TVScreen::setDataColor (int intCol, int intRed, int intGreen, int intBlue)
Definition at line 224 of file tvscreen.cpp.
References m_blnGLContextInitialized, m_objGLShaderArray, and GLShaderTVArray::SetDataColor().
Referenced by ScopeVisXY::drawGraticule(), ScopeVisXY::feed(), ATVDemod::processClassic(), ATVDemod::processHSkip(), leansdr::datvconstellation< leansdr::f32 >::run(), and leansdr::datvdvbs2constellation< leansdr::f32 >::run().
 {
     if (m_blnGLContextInitialized)
     {
         return m_objGLShaderArray.SetDataColor(intCol, qRgb(intBlue, intGreen, intRed)); // FIXME: blue <> red inversion in shader
     }
     else
     {
         return false;
     }
 }
setDataColor() [2/2]
bool TVScreen::setDataColor (int intCol, int intRed, int intGreen, int intBlue, int intAlpha)
Definition at line 236 of file tvscreen.cpp.
References m_blnGLContextInitialized, m_objGLShaderArray, and GLShaderTVArray::SetDataColor().
 {
     if (m_blnGLContextInitialized)
     {
         return m_objGLShaderArray.SetDataColor(intCol, qRgba(intBlue, intGreen, intRed, intAlpha)); // FIXME: blue <> red inversion in shader
     }
     else
     {
         return false;
     }
 }
tick
void TVScreen::tick () protected slot
Definition at line 189 of file tvscreen.cpp.
References m_blnDataChanged.
Referenced by connectTimer(), and TVScreen().
 {
     if (m_blnDataChanged) {
         update();
     }
 }
traceSizeChanged
void TVScreen::traceSizeChanged (int) signal
Member Data Documentation
m_blnConfigChanged
bool TVScreen::m_blnConfigChanged private
Definition at line 82 of file tvscreen.h.
Referenced by resizeGL(), and TVScreen().
m_blnDataChanged
bool TVScreen::m_blnDataChanged private
Definition at line 81 of file tvscreen.h.
Referenced by paintGL(), renderImage(), tick(), and TVScreen().
m_blnGLContextInitialized
bool TVScreen::m_blnGLContextInitialized private
Definition at line 73 of file tvscreen.h.
Referenced by cleanup(), getRowBuffer(), initializeGL(), selectRow(), setDataColor(), and TVScreen().
m_chrLastData
unsigned char* TVScreen::m_chrLastData private
Definition at line 95 of file tvscreen.h.
Referenced by paintGL(), renderImage(), and TVScreen().
m_cols
int TVScreen::m_cols private
Definition at line 86 of file tvscreen.h.
Referenced by getSize(), resizeTVScreen(), and TVScreen().
m_intAskedCols
int TVScreen::m_intAskedCols private
Definition at line 74 of file tvscreen.h.
Referenced by paintGL(), resizeTVScreen(), and TVScreen().
m_intAskedRows
int TVScreen::m_intAskedRows private
Definition at line 75 of file tvscreen.h.
Referenced by paintGL(), resizeTVScreen(), and TVScreen().
m_objGLShaderArray
GLShaderTVArray TVScreen::m_objGLShaderArray private
Definition at line 84 of file tvscreen.h.
Referenced by cleanup(), getRowBuffer(), paintGL(), resetImage(), selectRow(), setColor(), and setDataColor().
m_objMutex
QMutex TVScreen::m_objMutex private
Definition at line 80 of file tvscreen.h.
Referenced by initializeGL(), and paintGL().
m_objTimer
QTimer TVScreen::m_objTimer private
Definition at line 79 of file tvscreen.h.
Referenced by connectTimer(), and TVScreen().
m_rows
int TVScreen::m_rows private
Definition at line 87 of file tvscreen.h.
Referenced by getSize(), resizeTVScreen(), and TVScreen().
TV_COLS
const int TVScreen::TV_COLS =256 static
Definition at line 65 of file tvscreen.h.
Referenced by TVScreen().
TV_ROWS
const int TVScreen::TV_ROWS =256 static
Definition at line 66 of file tvscreen.h.
Referenced by TVScreen().
The documentation for this class was generated from the following files:
sdrgui/gui/tvscreen.h
sdrgui/gui/tvscreen.cpp