SDRAngel: RemoteDataReadQueue Class Reference
RemoteDataReadQueue Class Reference
#include <remotedatareadqueue.h>
Public Member Functions
RemoteDataReadQueue ()
~RemoteDataReadQueue ()
void push (RemoteDataBlock *dataBlock)
push block on the queue
RemoteDataBlock * pop ()
Pop block from the queue.
void readSample (Sample &s, bool scaleForTx=false)
Read sample from queue possibly scaling to Tx size.
uint32_t length () const
Returns queue length.
uint32_t size () const
Returns queue size (max length)
void setSize (uint32_t size)
Sets the queue size (max length)
uint32_t readSampleCount () const
Returns the absolute number of samples read.
Static Public Attributes
static const uint32_t MinimumMaxSize = 10
Private Member Functions
void convertDataToSample (Sample &s, uint32_t blockIndex, uint32_t sampleIndex, bool scaleForTx)
Private Attributes
QQueue< RemoteDataBlock * > m_dataReadQueue
RemoteDataBlock * m_dataBlock
uint32_t m_maxSize
uint32_t m_blockIndex
uint32_t m_sampleIndex
uint32_t m_sampleCount
use a counter capped below 2^31 as it is going to be converted to an int in the web interface
bool m_full
full condition was hit
Detailed Description
Definition at line 35 of file remotedatareadqueue.h.
Constructor & Destructor Documentation
RemoteDataReadQueue()
RemoteDataReadQueue::RemoteDataReadQueue ()
Definition at line 30 of file remotedatareadqueue.cpp.
                                          :
         m_dataBlock(0),
         m_maxSize(MinimumMaxSize),
         m_blockIndex(1),
         m_sampleIndex(0),
         m_sampleCount(0),
         m_full(false)
 {}
~RemoteDataReadQueue()
RemoteDataReadQueue::~RemoteDataReadQueue ()
Definition at line 39 of file remotedatareadqueue.cpp.
References pop().
 {
     RemoteDataBlock* data;
     while ((data = pop()) != 0)
     {
         qDebug("RemoteDataReadQueue::~RemoteDataReadQueue: data block was still in queue");
         delete data;
     }
 }
Member Function Documentation
convertDataToSample()
void RemoteDataReadQueue::convertDataToSample (Sample & s, uint32_t blockIndex, uint32_t sampleIndex, bool scaleForTx) inline private
Definition at line 60 of file remotedatareadqueue.h.
References RemoteProtectedBlock::buf, RemoteSuperBlock::m_header, RemoteSuperBlock::m_protectedBlock, RemoteHeader::m_sampleBits, RemoteHeader::m_sampleBytes, RemoteDataBlock::m_superBlocks, SDR_RX_SAMP_SZ, SDR_TX_SAMP_SZ, Sample::setImag(), and Sample::setReal().
Referenced by readSample().
     {
         int sampleSize = m_dataBlock->m_superBlocks[blockIndex].m_header.m_sampleBytes * 2; // I/Q sample size in data block
         int samplebits = m_dataBlock->m_superBlocks[blockIndex].m_header.m_sampleBits;      // I or Q sample size in bits
         int32_t iconv, qconv;
         if ((sizeof(Sample) == 4) && (sampleSize == 8)) // generally 24->16 bits
         {
             iconv = ((int32_t*) &(m_dataBlock->m_superBlocks[blockIndex].m_protectedBlock.buf[sampleIndex*sampleSize]))[0];
             qconv = ((int32_t*) &(m_dataBlock->m_superBlocks[blockIndex].m_protectedBlock.buf[sampleIndex*sampleSize+4]))[0];
             iconv >>= scaleForTx ? (SDR_TX_SAMP_SZ-SDR_RX_SAMP_SZ) : (samplebits-SDR_RX_SAMP_SZ);
             qconv >>= scaleForTx ? (SDR_TX_SAMP_SZ-SDR_RX_SAMP_SZ) : (samplebits-SDR_RX_SAMP_SZ);
             s.setReal(iconv);
             s.setImag(qconv);
         }
         else if ((sizeof(Sample) == 8) && (sampleSize == 4)) // generally 16->24 bits
         {
             iconv = ((int16_t*) &(m_dataBlock->m_superBlocks[blockIndex].m_protectedBlock.buf[sampleIndex*sampleSize]))[0];
             qconv = ((int16_t*) &(m_dataBlock->m_superBlocks[blockIndex].m_protectedBlock.buf[sampleIndex*sampleSize+2]))[0];
             iconv <<= scaleForTx ? (SDR_TX_SAMP_SZ-samplebits) : (SDR_RX_SAMP_SZ-samplebits);
             qconv <<= scaleForTx ? (SDR_TX_SAMP_SZ-samplebits) : (SDR_RX_SAMP_SZ-samplebits);
             s.setReal(iconv);
             s.setImag(qconv);
         }
         else if ((sampleSize == 4) || (sampleSize == 8)) // generally 16->16 or 24->24 bits
         {
             s = *((Sample*) &(m_dataBlock->m_superBlocks[blockIndex].m_protectedBlock.buf[sampleIndex*sampleSize]));
         }
         else // invalid size
         {
             s = Sample{0, 0};
         }
     }
length()
uint32_t RemoteDataReadQueue::length () const inline
Returns queue length.
Definition at line 44 of file remotedatareadqueue.h.
Referenced by RemoteSource::handleMessage(), push(), readSample(), and RemoteSource::webapiFormatChannelReport().
pop()
RemoteDataBlock * RemoteDataReadQueue::pop ()
Pop block from the queue.
Definition at line 69 of file remotedatareadqueue.cpp.
References m_blockIndex, m_dataReadQueue, and m_sampleIndex.
Referenced by ~RemoteDataReadQueue().
 {
     if (m_dataReadQueue.isEmpty())
     {
         return 0;
     }
     else
     {
         m_blockIndex = 1;
         m_sampleIndex = 0;
         return m_dataReadQueue.takeFirst();
     }
 }
push()
void RemoteDataReadQueue::push (RemoteDataBlock * dataBlock)
push block on the queue
Definition at line 50 of file remotedatareadqueue.cpp.
References length(), m_dataReadQueue, m_full, and m_maxSize.
 {
     if (length() >= m_maxSize)
     {
         qWarning("RemoteDataReadQueue::push: queue is full");
         m_full = true; // stop filling the queue
         RemoteDataBlock *data = m_dataReadQueue.takeLast();
         delete data;
     }
     if (m_full) {
         m_full = (length() > m_maxSize/2); // do not fill queue again before queue is half size
     }
     if (!m_full) {
         m_dataReadQueue.append(dataBlock);
     }
 }
readSample()
void RemoteDataReadQueue::readSample (Sample & s, bool scaleForTx = false)
Read sample from queue possibly scaling to Tx size.
Definition at line 91 of file remotedatareadqueue.cpp.
References convertDataToSample(), length(), m_blockIndex, m_dataBlock, m_dataReadQueue, RemoteSuperBlock::m_header, m_maxSize, RemoteHeader::m_sampleBytes, m_sampleCount, m_sampleIndex, and RemoteDataBlock::m_superBlocks.
Referenced by RemoteSource::pull().
 {
     // depletion/repletion state
     if (m_dataBlock == 0)
     {
         if (length() >= m_maxSize/2)
         {
             qDebug("RemoteDataReadQueue::readSample: initial pop new block: queue size: %u", length());
             m_blockIndex = 1;
             m_dataBlock = m_dataReadQueue.takeFirst();
             convertDataToSample(s, m_blockIndex, m_sampleIndex, scaleForTx);
             m_sampleIndex++;
             m_sampleCount++;
         }
         else
         {
             s = Sample{0, 0};
         }
         return;
     }
     int sampleSize = m_dataBlock->m_superBlocks[m_blockIndex].m_header.m_sampleBytes * 2;
     uint32_t samplesPerBlock = RemoteNbBytesPerBlock / sampleSize;
     if (m_sampleIndex < samplesPerBlock)
     {
         convertDataToSample(s, m_blockIndex, m_sampleIndex, scaleForTx);
         m_sampleIndex++;
         m_sampleCount++;
     }
     else
     {
         m_sampleIndex = 0;
         m_blockIndex++;
         if (m_blockIndex < RemoteNbOrginalBlocks)
         {
             convertDataToSample(s, m_blockIndex, m_sampleIndex, scaleForTx);
             m_sampleIndex++;
             m_sampleCount++;
         }
         else
         {
             delete m_dataBlock;
             m_dataBlock = 0;
             if (length() == 0) {
                 qWarning("RemoteDataReadQueue::readSample: try to pop new block but queue is empty");
             }
             if (length() > 0)
             {
                 //qDebug("RemoteDataReadQueue::readSample: pop new block: queue size: %u", length());
                 m_blockIndex = 1;
                 m_dataBlock = m_dataReadQueue.takeFirst();
                 convertDataToSample(s, m_blockIndex, m_sampleIndex, scaleForTx);
                 m_sampleIndex++;
                 m_sampleCount++;
             }
             else
             {
                 s = Sample{0, 0};
             }
         }
     }
 }
readSampleCount()
uint32_t RemoteDataReadQueue::readSampleCount () const inline
Returns the absolute number of samples read.
Definition at line 47 of file remotedatareadqueue.h.
Referenced by RemoteSource::handleMessage(), and RemoteSource::webapiFormatChannelReport().
setSize()
void RemoteDataReadQueue::setSize (uint32_t size)
Sets the queue size (max length)
Definition at line 84 of file remotedatareadqueue.cpp.
References m_maxSize, MinimumMaxSize, and size().
 {
     if (size != m_maxSize) {
         m_maxSize = size < MinimumMaxSize ? MinimumMaxSize : size;
     }
 }
size()
uint32_t RemoteDataReadQueue::size () const inline
Returns queue size (max length)
Definition at line 45 of file remotedatareadqueue.h.
Referenced by RemoteSource::handleMessage(), setSize(), and RemoteSource::webapiFormatChannelReport().
Member Data Documentation
m_blockIndex
uint32_t RemoteDataReadQueue::m_blockIndex private
Definition at line 55 of file remotedatareadqueue.h.
Referenced by pop(), and readSample().
m_dataBlock
RemoteDataBlock* RemoteDataReadQueue::m_dataBlock private
Definition at line 53 of file remotedatareadqueue.h.
Referenced by readSample().
m_dataReadQueue
QQueue<RemoteDataBlock*> RemoteDataReadQueue::m_dataReadQueue private
Definition at line 52 of file remotedatareadqueue.h.
Referenced by pop(), push(), and readSample().
m_full
bool RemoteDataReadQueue::m_full private
full condition was hit
Definition at line 58 of file remotedatareadqueue.h.
Referenced by push().
m_maxSize
uint32_t RemoteDataReadQueue::m_maxSize private
Definition at line 54 of file remotedatareadqueue.h.
Referenced by push(), readSample(), and setSize().
m_sampleCount
uint32_t RemoteDataReadQueue::m_sampleCount private
use a counter capped below 2^31 as it is going to be converted to an int in the web interface
Definition at line 57 of file remotedatareadqueue.h.
Referenced by readSample().
m_sampleIndex
uint32_t RemoteDataReadQueue::m_sampleIndex private
Definition at line 56 of file remotedatareadqueue.h.
Referenced by pop(), and readSample().
MinimumMaxSize
const uint32_t RemoteDataReadQueue::MinimumMaxSize = 10 static
Definition at line 49 of file remotedatareadqueue.h.
Referenced by setSize().
The documentation for this class was generated from the following files:
sdrbase/channel/remotedatareadqueue.h
sdrbase/channel/remotedatareadqueue.cpp