SDRAngel: FreeDVPlugin Class Reference
FreeDVPlugin Class Reference
#include <freedvplugin.h>
Public Member Functions
FreeDVPlugin (QObject *parent=NULL)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
Private Attributes
PluginAPI * m_pluginAPI
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Private Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Private Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Detailed Description
Definition at line 27 of file freedvplugin.h.
Constructor & Destructor Documentation
FreeDVPlugin()
FreeDVPlugin::FreeDVPlugin (QObject * parent = NULL) explicit
Definition at line 36 of file freedvplugin.cpp.
                                           :
     QObject(parent),
     m_pluginAPI(0)
 {
 }
Member Function Documentation
createRxChannelBS()
BasebandSampleSink * FreeDVPlugin::createRxChannelBS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 69 of file freedvplugin.cpp.
 {
     return new FreeDVDemod(deviceAPI);
 }
createRxChannelCS()
ChannelAPI * FreeDVPlugin::createRxChannelCS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 74 of file freedvplugin.cpp.
 {
     return new FreeDVDemod(deviceAPI);
 }
createRxChannelGUI()
PluginInstanceGUI * FreeDVPlugin::createRxChannelGUI (DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) virtual
Reimplemented from PluginInterface.
Definition at line 63 of file freedvplugin.cpp.
References FreeDVDemodGUI::create(), and m_pluginAPI.
Referenced by initPlugin().
 {
     return FreeDVDemodGUI::create(m_pluginAPI, deviceUISet, rxChannel);
 }
getPluginDescriptor()
const PluginDescriptor & FreeDVPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 42 of file freedvplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void FreeDVPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 47 of file freedvplugin.cpp.
References createRxChannelGUI(), FreeDVDemod::m_channelId, FreeDVDemod::m_channelIdURI, m_pluginAPI, and PluginAPI::registerRxChannel().
 {
     m_pluginAPI = pluginAPI;
     // register demodulator
     m_pluginAPI->registerRxChannel(FreeDVDemod::m_channelIdURI, FreeDVDemod::m_channelId, this);
 }
Member Data Documentation
m_pluginAPI
PluginAPI* FreeDVPlugin::m_pluginAPI private
Definition at line 45 of file freedvplugin.h.
Referenced by createRxChannelGUI(), and initPlugin().
m_pluginDescriptor
const PluginDescriptor FreeDVPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("FreeDV Demodulator"),
    QString("4.5.5"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 43 of file freedvplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/channelrx/demodfreedv/freedvplugin.h
plugins/channelrx/demodfreedv/freedvplugin.cpp