SDRAngel: DSDDemod::MsgConfigureDSDDemod Class Reference
DSDDemod::MsgConfigureDSDDemod Class Reference
#include <dsddemod.h>
Public Member Functions
const DSDDemodSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureDSDDemod * create (const DSDDemodSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureDSDDemod (const DSDDemodSettings &settings, bool force)
Private Attributes
DSDDemodSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 53 of file dsddemod.h.
Constructor & Destructor Documentation
MsgConfigureDSDDemod()
DSDDemod::MsgConfigureDSDDemod::MsgConfigureDSDDemod (const DSDDemodSettings & settings, bool force) inline private
Definition at line 69 of file dsddemod.h.
Referenced by create().
                                                                            :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureDSDDemod* DSDDemod::MsgConfigureDSDDemod::create (const DSDDemodSettings & settings, bool force) inline static
Definition at line 60 of file dsddemod.h.
References MsgConfigureDSDDemod().
Referenced by DSDDemodGUI::applySettings(), DSDDemod::deserialize(), and DSDDemod::webapiSettingsPutPatch().
         {
             return new MsgConfigureDSDDemod(settings, force);
         }
getForce()
bool DSDDemod::MsgConfigureDSDDemod::getForce () const inline
Definition at line 58 of file dsddemod.h.
References m_force.
Referenced by DSDDemod::handleMessage().
 { return m_force; }
getSettings()
const DSDDemodSettings& DSDDemod::MsgConfigureDSDDemod::getSettings () const inline
Definition at line 57 of file dsddemod.h.
References m_settings.
Referenced by DSDDemodGUI::handleMessage(), and DSDDemod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool DSDDemod::MsgConfigureDSDDemod::m_force private
Definition at line 67 of file dsddemod.h.
Referenced by getForce().
m_settings
DSDDemodSettings DSDDemod::MsgConfigureDSDDemod::m_settings private
Definition at line 66 of file dsddemod.h.
Referenced by DSDDemod::getCenterFrequency(), getSettings(), DSDDemod::getStreamCenterFrequency(), and DSDDemod::getTitle().
The documentation for this class was generated from the following file:
plugins/channelrx/demoddsd/dsddemod.h