SDRAngel: ATVMod::MsgConfigureCameraData Class Reference
ATVMod::MsgConfigureCameraData Class Reference
#include <atvmod.h>
Public Member Functions
int getIndex () const
float getManualFPS () const
bool getManualFPSEnable () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureCameraData * create (int index, float manualFPS, bool manualFPSEnable)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureCameraData (int index, float manualFPS, bool manualFPSEnable)
Private Attributes
int m_index
float m_manualFPS
bool m_manualFPSEnable
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 243 of file atvmod.h.
Constructor & Destructor Documentation
MsgConfigureCameraData()
ATVMod::MsgConfigureCameraData::MsgConfigureCameraData (int index, float manualFPS, bool manualFPSEnable) inline private
Definition at line 265 of file atvmod.h.
                                                                                  :
             Message(),
             m_index(index),
             m_manualFPS(manualFPS),
             m_manualFPSEnable(manualFPSEnable)
         { }
Member Function Documentation
create()
static MsgConfigureCameraData* ATVMod::MsgConfigureCameraData::create (int index, float manualFPS, bool manualFPSEnable) inline static
Definition at line 252 of file atvmod.h.
Referenced by ATVModGUI::on_cameraManualFPS_valueChanged(), and ATVModGUI::on_cameraManualFPSEnable_toggled().
         {
             return new MsgConfigureCameraData(index, manualFPS, manualFPSEnable);
         }
getIndex()
int ATVMod::MsgConfigureCameraData::getIndex () const inline
Definition at line 248 of file atvmod.h.
Referenced by ATVMod::handleMessage().
 { return m_index; }
getManualFPS()
float ATVMod::MsgConfigureCameraData::getManualFPS () const inline
Definition at line 249 of file atvmod.h.
Referenced by ATVMod::handleMessage().
 { return m_manualFPS; }
getManualFPSEnable()
bool ATVMod::MsgConfigureCameraData::getManualFPSEnable () const inline
Definition at line 250 of file atvmod.h.
Referenced by ATVMod::handleMessage().
 { return m_manualFPSEnable; }
Member Data Documentation
m_index
int ATVMod::MsgConfigureCameraData::m_index private
Definition at line 261 of file atvmod.h.
m_manualFPS
float ATVMod::MsgConfigureCameraData::m_manualFPS private
Definition at line 262 of file atvmod.h.
m_manualFPSEnable
bool ATVMod::MsgConfigureCameraData::m_manualFPSEnable private
Definition at line 263 of file atvmod.h.
The documentation for this class was generated from the following file:
plugins/channeltx/modatv/atvmod.h