SDRAngel: SWGSDRangel::SWGDeviceSetApi Class Reference
SWGSDRangel::SWGDeviceSetApi Class Reference
#include <SWGDeviceSetApi.h>
Inherits QObject.
Signals
void devicesetChannelDeleteSignal (SWGChannelSettings *summary)
void devicesetChannelPostSignal (SWGSuccessResponse *summary)
void devicesetChannelReportGetSignal (SWGChannelReport *summary)
void devicesetChannelSettingsGetSignal (SWGChannelSettings *summary)
void devicesetChannelSettingsPatchSignal (SWGChannelSettings *summary)
void devicesetChannelSettingsPutSignal (SWGChannelSettings *summary)
void devicesetChannelsReportGetSignal (SWGChannelsDetail *summary)
void devicesetDevicePutSignal (SWGDeviceListItem *summary)
void devicesetDeviceReportGetSignal (SWGDeviceReport *summary)
void devicesetDeviceRunDeleteSignal (SWGDeviceState *summary)
void devicesetDeviceRunGetSignal (SWGDeviceState *summary)
void devicesetDeviceRunPostSignal (SWGDeviceState *summary)
void devicesetDeviceSettingsGetSignal (SWGDeviceSettings *summary)
void devicesetDeviceSettingsPatchSignal (SWGDeviceSettings *summary)
void devicesetDeviceSettingsPutSignal (SWGDeviceSettings *summary)
void devicesetFocusPatchSignal (SWGSuccessResponse *summary)
void devicesetGetSignal (SWGDeviceSet *summary)
void instanceDeviceSetDeleteSignal (SWGSuccessResponse *summary)
void instanceDeviceSetPostSignal (SWGSuccessResponse *summary)
void devicesetChannelDeleteSignalE (SWGChannelSettings *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetChannelPostSignalE (SWGSuccessResponse *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetChannelReportGetSignalE (SWGChannelReport *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetChannelSettingsGetSignalE (SWGChannelSettings *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetChannelSettingsPatchSignalE (SWGChannelSettings *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetChannelSettingsPutSignalE (SWGChannelSettings *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetChannelsReportGetSignalE (SWGChannelsDetail *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDevicePutSignalE (SWGDeviceListItem *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceReportGetSignalE (SWGDeviceReport *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceRunDeleteSignalE (SWGDeviceState *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceRunGetSignalE (SWGDeviceState *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceRunPostSignalE (SWGDeviceState *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceSettingsGetSignalE (SWGDeviceSettings *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceSettingsPatchSignalE (SWGDeviceSettings *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceSettingsPutSignalE (SWGDeviceSettings *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetFocusPatchSignalE (SWGSuccessResponse *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetGetSignalE (SWGDeviceSet *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void instanceDeviceSetDeleteSignalE (SWGSuccessResponse *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void instanceDeviceSetPostSignalE (SWGSuccessResponse *summary, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetChannelDeleteSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetChannelPostSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetChannelReportGetSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetChannelSettingsGetSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetChannelSettingsPatchSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetChannelSettingsPutSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetChannelsReportGetSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDevicePutSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceReportGetSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceRunDeleteSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceRunGetSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceRunPostSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceSettingsGetSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceSettingsPatchSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetDeviceSettingsPutSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetFocusPatchSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void devicesetGetSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void instanceDeviceSetDeleteSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
void instanceDeviceSetPostSignalEFull (SWGHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString &error_str)
Public Member Functions
SWGDeviceSetApi ()
SWGDeviceSetApi (QString host, QString basePath)
~SWGDeviceSetApi ()
void devicesetChannelDelete (qint32 device_set_index, qint32 channel_index)
void devicesetChannelPost (qint32 device_set_index, SWGChannelSettings &body)
void devicesetChannelReportGet (qint32 device_set_index, qint32 channel_index)
void devicesetChannelSettingsGet (qint32 device_set_index, qint32 channel_index)
void devicesetChannelSettingsPatch (qint32 device_set_index, qint32 channel_index, SWGChannelSettings &body)
void devicesetChannelSettingsPut (qint32 device_set_index, qint32 channel_index, SWGChannelSettings &body)
void devicesetChannelsReportGet (qint32 device_set_index)
void devicesetDevicePut (qint32 device_set_index, SWGDeviceListItem &body)
void devicesetDeviceReportGet (qint32 device_set_index)
void devicesetDeviceRunDelete (qint32 device_set_index, SWGDeviceSettings &body)
void devicesetDeviceRunGet (qint32 device_set_index)
void devicesetDeviceRunPost (qint32 device_set_index, SWGDeviceSettings &body)
void devicesetDeviceSettingsGet (qint32 device_set_index)
void devicesetDeviceSettingsPatch (qint32 device_set_index, SWGDeviceSettings &body)
void devicesetDeviceSettingsPut (qint32 device_set_index, SWGDeviceSettings &body)
void devicesetFocusPatch (qint32 device_set_index)
void devicesetGet (qint32 device_set_index)
void instanceDeviceSetDelete ()
void instanceDeviceSetPost (qint32 direction)
Public Attributes
QString host
QString basePath
QMap< QString, QString > defaultHeaders
Private Member Functions
void devicesetChannelDeleteCallback (SWGHttpRequestWorker *worker)
void devicesetChannelPostCallback (SWGHttpRequestWorker *worker)
void devicesetChannelReportGetCallback (SWGHttpRequestWorker *worker)
void devicesetChannelSettingsGetCallback (SWGHttpRequestWorker *worker)
void devicesetChannelSettingsPatchCallback (SWGHttpRequestWorker *worker)
void devicesetChannelSettingsPutCallback (SWGHttpRequestWorker *worker)
void devicesetChannelsReportGetCallback (SWGHttpRequestWorker *worker)
void devicesetDevicePutCallback (SWGHttpRequestWorker *worker)
void devicesetDeviceReportGetCallback (SWGHttpRequestWorker *worker)
void devicesetDeviceRunDeleteCallback (SWGHttpRequestWorker *worker)
void devicesetDeviceRunGetCallback (SWGHttpRequestWorker *worker)
void devicesetDeviceRunPostCallback (SWGHttpRequestWorker *worker)
void devicesetDeviceSettingsGetCallback (SWGHttpRequestWorker *worker)
void devicesetDeviceSettingsPatchCallback (SWGHttpRequestWorker *worker)
void devicesetDeviceSettingsPutCallback (SWGHttpRequestWorker *worker)
void devicesetFocusPatchCallback (SWGHttpRequestWorker *worker)
void devicesetGetCallback (SWGHttpRequestWorker *worker)
void instanceDeviceSetDeleteCallback (SWGHttpRequestWorker *worker)
void instanceDeviceSetPostCallback (SWGHttpRequestWorker *worker)
Detailed Description
Definition at line 33 of file SWGDeviceSetApi.h.
Constructor & Destructor Documentation
SWGDeviceSetApi() [1/2]
SWGSDRangel::SWGDeviceSetApi::SWGDeviceSetApi ()
Definition at line 22 of file SWGDeviceSetApi.cpp.
 {}
SWGDeviceSetApi() [2/2]
SWGSDRangel::SWGDeviceSetApi::SWGDeviceSetApi (QString host, QString basePath)
Definition at line 26 of file SWGDeviceSetApi.cpp.
References basePath, and host.
{
     this->host = host;
     this->basePath = basePath;
 }
~SWGDeviceSetApi()
SWGSDRangel::SWGDeviceSetApi::~SWGDeviceSetApi ()
Definition at line 24 of file SWGDeviceSetApi.cpp.
 {}
Member Function Documentation
devicesetChannelDelete()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelDelete (qint32 device_set_index, qint32 channel_index)
Definition at line 32 of file SWGDeviceSetApi.cpp.
References basePath, defaultHeaders, devicesetChannelDeleteCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex}");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     QString channel_indexPathParam("{"); channel_indexPathParam.append("channelIndex").append("}");
     fullPath.replace(channel_indexPathParam, stringValue(channel_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "DELETE");
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetChannelDeleteCallback);
     worker->execute(&input);
 }
devicesetChannelDeleteCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelDeleteCallback (SWGHttpRequestWorker * worker) private
Definition at line 62 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetChannelDeleteSignal(), devicesetChannelDeleteSignalE(), devicesetChannelDeleteSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetChannelDelete().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGChannelSettings* output = static_cast<SWGChannelSettings*>(create(json, QString("SWGChannelSettings")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetChannelDeleteSignal(output);
     } else {
         emit devicesetChannelDeleteSignalE(output, error_type, error_str);
         emit devicesetChannelDeleteSignalEFull(worker, error_type, error_str);
     }
 }
devicesetChannelDeleteSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelDeleteSignal (SWGChannelSettings * summary) signal
Referenced by devicesetChannelDeleteCallback().
devicesetChannelDeleteSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelDeleteSignalE (SWGChannelSettings * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelDeleteCallback().
devicesetChannelDeleteSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelDeleteSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelDeleteCallback().
devicesetChannelPost()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelPost (qint32 device_set_index, SWGChannelSettings & body)
Definition at line 88 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), basePath, defaultHeaders, devicesetChannelPostCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), SWGSDRangel::SWGHttpRequestInput::request_body, and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/channel");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "POST");
     QString output = body.asJson();
     input.request_body.append(output);
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetChannelPostCallback);
     worker->execute(&input);
 }
devicesetChannelPostCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelPostCallback (SWGHttpRequestWorker * worker) private
Definition at line 119 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetChannelPostSignal(), devicesetChannelPostSignalE(), devicesetChannelPostSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetChannelPost().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGSuccessResponse* output = static_cast<SWGSuccessResponse*>(create(json, QString("SWGSuccessResponse")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetChannelPostSignal(output);
     } else {
         emit devicesetChannelPostSignalE(output, error_type, error_str);
         emit devicesetChannelPostSignalEFull(worker, error_type, error_str);
     }
 }
devicesetChannelPostSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelPostSignal (SWGSuccessResponse * summary) signal
Referenced by devicesetChannelPostCallback().
devicesetChannelPostSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelPostSignalE (SWGSuccessResponse * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelPostCallback().
devicesetChannelPostSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelPostSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelPostCallback().
devicesetChannelReportGet()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelReportGet (qint32 device_set_index, qint32 channel_index)
Definition at line 145 of file SWGDeviceSetApi.cpp.
References basePath, defaultHeaders, devicesetChannelReportGetCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex}/report");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     QString channel_indexPathParam("{"); channel_indexPathParam.append("channelIndex").append("}");
     fullPath.replace(channel_indexPathParam, stringValue(channel_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "GET");
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetChannelReportGetCallback);
     worker->execute(&input);
 }
devicesetChannelReportGetCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelReportGetCallback (SWGHttpRequestWorker * worker) private
Definition at line 175 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetChannelReportGetSignal(), devicesetChannelReportGetSignalE(), devicesetChannelReportGetSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetChannelReportGet().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGChannelReport* output = static_cast<SWGChannelReport*>(create(json, QString("SWGChannelReport")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetChannelReportGetSignal(output);
     } else {
         emit devicesetChannelReportGetSignalE(output, error_type, error_str);
         emit devicesetChannelReportGetSignalEFull(worker, error_type, error_str);
     }
 }
devicesetChannelReportGetSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelReportGetSignal (SWGChannelReport * summary) signal
Referenced by devicesetChannelReportGetCallback().
devicesetChannelReportGetSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelReportGetSignalE (SWGChannelReport * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelReportGetCallback().
devicesetChannelReportGetSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelReportGetSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelReportGetCallback().
devicesetChannelSettingsGet()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsGet (qint32 device_set_index, qint32 channel_index)
Definition at line 201 of file SWGDeviceSetApi.cpp.
References basePath, defaultHeaders, devicesetChannelSettingsGetCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex}/settings");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     QString channel_indexPathParam("{"); channel_indexPathParam.append("channelIndex").append("}");
     fullPath.replace(channel_indexPathParam, stringValue(channel_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "GET");
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetChannelSettingsGetCallback);
     worker->execute(&input);
 }
devicesetChannelSettingsGetCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsGetCallback (SWGHttpRequestWorker * worker) private
Definition at line 231 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetChannelSettingsGetSignal(), devicesetChannelSettingsGetSignalE(), devicesetChannelSettingsGetSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetChannelSettingsGet().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGChannelSettings* output = static_cast<SWGChannelSettings*>(create(json, QString("SWGChannelSettings")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetChannelSettingsGetSignal(output);
     } else {
         emit devicesetChannelSettingsGetSignalE(output, error_type, error_str);
         emit devicesetChannelSettingsGetSignalEFull(worker, error_type, error_str);
     }
 }
devicesetChannelSettingsGetSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsGetSignal (SWGChannelSettings * summary) signal
Referenced by devicesetChannelSettingsGetCallback().
devicesetChannelSettingsGetSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsGetSignalE (SWGChannelSettings * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelSettingsGetCallback().
devicesetChannelSettingsGetSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsGetSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelSettingsGetCallback().
devicesetChannelSettingsPatch()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPatch (qint32 device_set_index, qint32 channel_index, SWGChannelSettings & body)
Definition at line 257 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), basePath, defaultHeaders, devicesetChannelSettingsPatchCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), SWGSDRangel::SWGHttpRequestInput::request_body, and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex}/settings");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     QString channel_indexPathParam("{"); channel_indexPathParam.append("channelIndex").append("}");
     fullPath.replace(channel_indexPathParam, stringValue(channel_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "PATCH");
     QString output = body.asJson();
     input.request_body.append(output);
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetChannelSettingsPatchCallback);
     worker->execute(&input);
 }
devicesetChannelSettingsPatchCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPatchCallback (SWGHttpRequestWorker * worker) private
Definition at line 290 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetChannelSettingsPatchSignal(), devicesetChannelSettingsPatchSignalE(), devicesetChannelSettingsPatchSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetChannelSettingsPatch().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGChannelSettings* output = static_cast<SWGChannelSettings*>(create(json, QString("SWGChannelSettings")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetChannelSettingsPatchSignal(output);
     } else {
         emit devicesetChannelSettingsPatchSignalE(output, error_type, error_str);
         emit devicesetChannelSettingsPatchSignalEFull(worker, error_type, error_str);
     }
 }
devicesetChannelSettingsPatchSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPatchSignal (SWGChannelSettings * summary) signal
Referenced by devicesetChannelSettingsPatchCallback().
devicesetChannelSettingsPatchSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPatchSignalE (SWGChannelSettings * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelSettingsPatchCallback().
devicesetChannelSettingsPatchSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPatchSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelSettingsPatchCallback().
devicesetChannelSettingsPut()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPut (qint32 device_set_index, qint32 channel_index, SWGChannelSettings & body)
Definition at line 316 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), basePath, defaultHeaders, devicesetChannelSettingsPutCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), SWGSDRangel::SWGHttpRequestInput::request_body, and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex}/settings");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     QString channel_indexPathParam("{"); channel_indexPathParam.append("channelIndex").append("}");
     fullPath.replace(channel_indexPathParam, stringValue(channel_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "PUT");
     QString output = body.asJson();
     input.request_body.append(output);
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetChannelSettingsPutCallback);
     worker->execute(&input);
 }
devicesetChannelSettingsPutCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPutCallback (SWGHttpRequestWorker * worker) private
Definition at line 349 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetChannelSettingsPutSignal(), devicesetChannelSettingsPutSignalE(), devicesetChannelSettingsPutSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetChannelSettingsPut().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGChannelSettings* output = static_cast<SWGChannelSettings*>(create(json, QString("SWGChannelSettings")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetChannelSettingsPutSignal(output);
     } else {
         emit devicesetChannelSettingsPutSignalE(output, error_type, error_str);
         emit devicesetChannelSettingsPutSignalEFull(worker, error_type, error_str);
     }
 }
devicesetChannelSettingsPutSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPutSignal (SWGChannelSettings * summary) signal
Referenced by devicesetChannelSettingsPutCallback().
devicesetChannelSettingsPutSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPutSignalE (SWGChannelSettings * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelSettingsPutCallback().
devicesetChannelSettingsPutSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPutSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelSettingsPutCallback().
devicesetChannelsReportGet()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelsReportGet (qint32 device_set_index)
Definition at line 375 of file SWGDeviceSetApi.cpp.
References basePath, defaultHeaders, devicesetChannelsReportGetCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/channels/report");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "GET");
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetChannelsReportGetCallback);
     worker->execute(&input);
 }
devicesetChannelsReportGetCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelsReportGetCallback (SWGHttpRequestWorker * worker) private
Definition at line 403 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetChannelsReportGetSignal(), devicesetChannelsReportGetSignalE(), devicesetChannelsReportGetSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetChannelsReportGet().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGChannelsDetail* output = static_cast<SWGChannelsDetail*>(create(json, QString("SWGChannelsDetail")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetChannelsReportGetSignal(output);
     } else {
         emit devicesetChannelsReportGetSignalE(output, error_type, error_str);
         emit devicesetChannelsReportGetSignalEFull(worker, error_type, error_str);
     }
 }
devicesetChannelsReportGetSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelsReportGetSignal (SWGChannelsDetail * summary) signal
Referenced by devicesetChannelsReportGetCallback().
devicesetChannelsReportGetSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelsReportGetSignalE (SWGChannelsDetail * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelsReportGetCallback().
devicesetChannelsReportGetSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetChannelsReportGetSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetChannelsReportGetCallback().
devicesetDevicePut()
void SWGSDRangel::SWGDeviceSetApi::devicesetDevicePut (qint32 device_set_index, SWGDeviceListItem & body)
Definition at line 429 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::SWGDeviceListItem::asJson(), basePath, defaultHeaders, devicesetDevicePutCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), SWGSDRangel::SWGHttpRequestInput::request_body, and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/device");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "PUT");
     QString output = body.asJson();
     input.request_body.append(output);
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetDevicePutCallback);
     worker->execute(&input);
 }
devicesetDevicePutCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetDevicePutCallback (SWGHttpRequestWorker * worker) private
Definition at line 460 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetDevicePutSignal(), devicesetDevicePutSignalE(), devicesetDevicePutSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetDevicePut().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGDeviceListItem* output = static_cast<SWGDeviceListItem*>(create(json, QString("SWGDeviceListItem")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetDevicePutSignal(output);
     } else {
         emit devicesetDevicePutSignalE(output, error_type, error_str);
         emit devicesetDevicePutSignalEFull(worker, error_type, error_str);
     }
 }
devicesetDevicePutSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetDevicePutSignal (SWGDeviceListItem * summary) signal
Referenced by devicesetDevicePutCallback().
devicesetDevicePutSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetDevicePutSignalE (SWGDeviceListItem * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDevicePutCallback().
devicesetDevicePutSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetDevicePutSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDevicePutCallback().
devicesetDeviceReportGet()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceReportGet (qint32 device_set_index)
Definition at line 486 of file SWGDeviceSetApi.cpp.
References basePath, defaultHeaders, devicesetDeviceReportGetCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/device/report");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "GET");
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetDeviceReportGetCallback);
     worker->execute(&input);
 }
devicesetDeviceReportGetCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceReportGetCallback (SWGHttpRequestWorker * worker) private
Definition at line 514 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetDeviceReportGetSignal(), devicesetDeviceReportGetSignalE(), devicesetDeviceReportGetSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetDeviceReportGet().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGDeviceReport* output = static_cast<SWGDeviceReport*>(create(json, QString("SWGDeviceReport")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetDeviceReportGetSignal(output);
     } else {
         emit devicesetDeviceReportGetSignalE(output, error_type, error_str);
         emit devicesetDeviceReportGetSignalEFull(worker, error_type, error_str);
     }
 }
devicesetDeviceReportGetSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceReportGetSignal (SWGDeviceReport * summary) signal
Referenced by devicesetDeviceReportGetCallback().
devicesetDeviceReportGetSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceReportGetSignalE (SWGDeviceReport * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceReportGetCallback().
devicesetDeviceReportGetSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceReportGetSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceReportGetCallback().
devicesetDeviceRunDelete()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunDelete (qint32 device_set_index, SWGDeviceSettings & body)
Definition at line 540 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), basePath, defaultHeaders, devicesetDeviceRunDeleteCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), SWGSDRangel::SWGHttpRequestInput::request_body, and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/device/run");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "DELETE");
     QString output = body.asJson();
     input.request_body.append(output);
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetDeviceRunDeleteCallback);
     worker->execute(&input);
 }
devicesetDeviceRunDeleteCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunDeleteCallback (SWGHttpRequestWorker * worker) private
Definition at line 571 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetDeviceRunDeleteSignal(), devicesetDeviceRunDeleteSignalE(), devicesetDeviceRunDeleteSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetDeviceRunDelete().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGDeviceState* output = static_cast<SWGDeviceState*>(create(json, QString("SWGDeviceState")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetDeviceRunDeleteSignal(output);
     } else {
         emit devicesetDeviceRunDeleteSignalE(output, error_type, error_str);
         emit devicesetDeviceRunDeleteSignalEFull(worker, error_type, error_str);
     }
 }
devicesetDeviceRunDeleteSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunDeleteSignal (SWGDeviceState * summary) signal
Referenced by devicesetDeviceRunDeleteCallback().
devicesetDeviceRunDeleteSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunDeleteSignalE (SWGDeviceState * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceRunDeleteCallback().
devicesetDeviceRunDeleteSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunDeleteSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceRunDeleteCallback().
devicesetDeviceRunGet()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunGet (qint32 device_set_index)
Definition at line 597 of file SWGDeviceSetApi.cpp.
References basePath, defaultHeaders, devicesetDeviceRunGetCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/device/run");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "GET");
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetDeviceRunGetCallback);
     worker->execute(&input);
 }
devicesetDeviceRunGetCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunGetCallback (SWGHttpRequestWorker * worker) private
Definition at line 625 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetDeviceRunGetSignal(), devicesetDeviceRunGetSignalE(), devicesetDeviceRunGetSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetDeviceRunGet().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGDeviceState* output = static_cast<SWGDeviceState*>(create(json, QString("SWGDeviceState")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetDeviceRunGetSignal(output);
     } else {
         emit devicesetDeviceRunGetSignalE(output, error_type, error_str);
         emit devicesetDeviceRunGetSignalEFull(worker, error_type, error_str);
     }
 }
devicesetDeviceRunGetSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunGetSignal (SWGDeviceState * summary) signal
Referenced by devicesetDeviceRunGetCallback().
devicesetDeviceRunGetSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunGetSignalE (SWGDeviceState * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceRunGetCallback().
devicesetDeviceRunGetSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunGetSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceRunGetCallback().
devicesetDeviceRunPost()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunPost (qint32 device_set_index, SWGDeviceSettings & body)
Definition at line 651 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), basePath, defaultHeaders, devicesetDeviceRunPostCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), SWGSDRangel::SWGHttpRequestInput::request_body, and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/device/run");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "POST");
     QString output = body.asJson();
     input.request_body.append(output);
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetDeviceRunPostCallback);
     worker->execute(&input);
 }
devicesetDeviceRunPostCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunPostCallback (SWGHttpRequestWorker * worker) private
Definition at line 682 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetDeviceRunPostSignal(), devicesetDeviceRunPostSignalE(), devicesetDeviceRunPostSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetDeviceRunPost().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGDeviceState* output = static_cast<SWGDeviceState*>(create(json, QString("SWGDeviceState")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetDeviceRunPostSignal(output);
     } else {
         emit devicesetDeviceRunPostSignalE(output, error_type, error_str);
         emit devicesetDeviceRunPostSignalEFull(worker, error_type, error_str);
     }
 }
devicesetDeviceRunPostSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunPostSignal (SWGDeviceState * summary) signal
Referenced by devicesetDeviceRunPostCallback().
devicesetDeviceRunPostSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunPostSignalE (SWGDeviceState * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceRunPostCallback().
devicesetDeviceRunPostSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunPostSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceRunPostCallback().
devicesetDeviceSettingsGet()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsGet (qint32 device_set_index)
Definition at line 708 of file SWGDeviceSetApi.cpp.
References basePath, defaultHeaders, devicesetDeviceSettingsGetCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/device/settings");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "GET");
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetDeviceSettingsGetCallback);
     worker->execute(&input);
 }
devicesetDeviceSettingsGetCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsGetCallback (SWGHttpRequestWorker * worker) private
Definition at line 736 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetDeviceSettingsGetSignal(), devicesetDeviceSettingsGetSignalE(), devicesetDeviceSettingsGetSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetDeviceSettingsGet().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGDeviceSettings* output = static_cast<SWGDeviceSettings*>(create(json, QString("SWGDeviceSettings")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetDeviceSettingsGetSignal(output);
     } else {
         emit devicesetDeviceSettingsGetSignalE(output, error_type, error_str);
         emit devicesetDeviceSettingsGetSignalEFull(worker, error_type, error_str);
     }
 }
devicesetDeviceSettingsGetSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsGetSignal (SWGDeviceSettings * summary) signal
Referenced by devicesetDeviceSettingsGetCallback().
devicesetDeviceSettingsGetSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsGetSignalE (SWGDeviceSettings * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceSettingsGetCallback().
devicesetDeviceSettingsGetSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsGetSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceSettingsGetCallback().
devicesetDeviceSettingsPatch()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPatch (qint32 device_set_index, SWGDeviceSettings & body)
Definition at line 762 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), basePath, defaultHeaders, devicesetDeviceSettingsPatchCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), SWGSDRangel::SWGHttpRequestInput::request_body, and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/device/settings");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "PATCH");
     QString output = body.asJson();
     input.request_body.append(output);
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetDeviceSettingsPatchCallback);
     worker->execute(&input);
 }
devicesetDeviceSettingsPatchCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPatchCallback (SWGHttpRequestWorker * worker) private
Definition at line 793 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetDeviceSettingsPatchSignal(), devicesetDeviceSettingsPatchSignalE(), devicesetDeviceSettingsPatchSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetDeviceSettingsPatch().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGDeviceSettings* output = static_cast<SWGDeviceSettings*>(create(json, QString("SWGDeviceSettings")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetDeviceSettingsPatchSignal(output);
     } else {
         emit devicesetDeviceSettingsPatchSignalE(output, error_type, error_str);
         emit devicesetDeviceSettingsPatchSignalEFull(worker, error_type, error_str);
     }
 }
devicesetDeviceSettingsPatchSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPatchSignal (SWGDeviceSettings * summary) signal
Referenced by devicesetDeviceSettingsPatchCallback().
devicesetDeviceSettingsPatchSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPatchSignalE (SWGDeviceSettings * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceSettingsPatchCallback().
devicesetDeviceSettingsPatchSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPatchSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceSettingsPatchCallback().
devicesetDeviceSettingsPut()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPut (qint32 device_set_index, SWGDeviceSettings & body)
Definition at line 819 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), basePath, defaultHeaders, devicesetDeviceSettingsPutCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), SWGSDRangel::SWGHttpRequestInput::request_body, and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/device/settings");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "PUT");
     QString output = body.asJson();
     input.request_body.append(output);
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetDeviceSettingsPutCallback);
     worker->execute(&input);
 }
devicesetDeviceSettingsPutCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPutCallback (SWGHttpRequestWorker * worker) private
Definition at line 850 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetDeviceSettingsPutSignal(), devicesetDeviceSettingsPutSignalE(), devicesetDeviceSettingsPutSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetDeviceSettingsPut().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGDeviceSettings* output = static_cast<SWGDeviceSettings*>(create(json, QString("SWGDeviceSettings")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetDeviceSettingsPutSignal(output);
     } else {
         emit devicesetDeviceSettingsPutSignalE(output, error_type, error_str);
         emit devicesetDeviceSettingsPutSignalEFull(worker, error_type, error_str);
     }
 }
devicesetDeviceSettingsPutSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPutSignal (SWGDeviceSettings * summary) signal
Referenced by devicesetDeviceSettingsPutCallback().
devicesetDeviceSettingsPutSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPutSignalE (SWGDeviceSettings * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceSettingsPutCallback().
devicesetDeviceSettingsPutSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPutSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetDeviceSettingsPutCallback().
devicesetFocusPatch()
void SWGSDRangel::SWGDeviceSetApi::devicesetFocusPatch (qint32 device_set_index)
Definition at line 876 of file SWGDeviceSetApi.cpp.
References basePath, defaultHeaders, devicesetFocusPatchCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}/focus");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "PATCH");
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetFocusPatchCallback);
     worker->execute(&input);
 }
devicesetFocusPatchCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetFocusPatchCallback (SWGHttpRequestWorker * worker) private
Definition at line 904 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetFocusPatchSignal(), devicesetFocusPatchSignalE(), devicesetFocusPatchSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetFocusPatch().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGSuccessResponse* output = static_cast<SWGSuccessResponse*>(create(json, QString("SWGSuccessResponse")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetFocusPatchSignal(output);
     } else {
         emit devicesetFocusPatchSignalE(output, error_type, error_str);
         emit devicesetFocusPatchSignalEFull(worker, error_type, error_str);
     }
 }
devicesetFocusPatchSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetFocusPatchSignal (SWGSuccessResponse * summary) signal
Referenced by devicesetFocusPatchCallback().
devicesetFocusPatchSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetFocusPatchSignalE (SWGSuccessResponse * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetFocusPatchCallback().
devicesetFocusPatchSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetFocusPatchSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetFocusPatchCallback().
devicesetGet()
void SWGSDRangel::SWGDeviceSetApi::devicesetGet (qint32 device_set_index)
Definition at line 930 of file SWGDeviceSetApi.cpp.
References basePath, defaultHeaders, devicesetGetCallback(), SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset/{deviceSetIndex}");
     QString device_set_indexPathParam("{"); device_set_indexPathParam.append("deviceSetIndex").append("}");
     fullPath.replace(device_set_indexPathParam, stringValue(device_set_index));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "GET");
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::devicesetGetCallback);
     worker->execute(&input);
 }
devicesetGetCallback()
void SWGSDRangel::SWGDeviceSetApi::devicesetGetCallback (SWGHttpRequestWorker * worker) private
Definition at line 958 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), devicesetGetSignal(), devicesetGetSignalE(), devicesetGetSignalEFull(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by devicesetGet().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGDeviceSet* output = static_cast<SWGDeviceSet*>(create(json, QString("SWGDeviceSet")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit devicesetGetSignal(output);
     } else {
         emit devicesetGetSignalE(output, error_type, error_str);
         emit devicesetGetSignalEFull(worker, error_type, error_str);
     }
 }
devicesetGetSignal
void SWGSDRangel::SWGDeviceSetApi::devicesetGetSignal (SWGDeviceSet * summary) signal
Referenced by devicesetGetCallback().
devicesetGetSignalE
void SWGSDRangel::SWGDeviceSetApi::devicesetGetSignalE (SWGDeviceSet * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetGetCallback().
devicesetGetSignalEFull
void SWGSDRangel::SWGDeviceSetApi::devicesetGetSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by devicesetGetCallback().
instanceDeviceSetDelete()
void SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetDelete ()
Definition at line 984 of file SWGDeviceSetApi.cpp.
References basePath, defaultHeaders, SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, instanceDeviceSetDeleteCallback(), and SWGSDRangel::SWGHttpRequestWorker::on_execution_finished().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset");
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "DELETE");
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::instanceDeviceSetDeleteCallback);
     worker->execute(&input);
 }
instanceDeviceSetDeleteCallback()
void SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetDeleteCallback (SWGHttpRequestWorker * worker) private
Definition at line 1010 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, instanceDeviceSetDeleteSignal(), instanceDeviceSetDeleteSignalE(), instanceDeviceSetDeleteSignalEFull(), and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by instanceDeviceSetDelete().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGSuccessResponse* output = static_cast<SWGSuccessResponse*>(create(json, QString("SWGSuccessResponse")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit instanceDeviceSetDeleteSignal(output);
     } else {
         emit instanceDeviceSetDeleteSignalE(output, error_type, error_str);
         emit instanceDeviceSetDeleteSignalEFull(worker, error_type, error_str);
     }
 }
instanceDeviceSetDeleteSignal
void SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetDeleteSignal (SWGSuccessResponse * summary) signal
Referenced by instanceDeviceSetDeleteCallback().
instanceDeviceSetDeleteSignalE
void SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetDeleteSignalE (SWGSuccessResponse * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by instanceDeviceSetDeleteCallback().
instanceDeviceSetDeleteSignalEFull
void SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetDeleteSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by instanceDeviceSetDeleteCallback().
instanceDeviceSetPost()
void SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetPost (qint32 direction)
Definition at line 1036 of file SWGDeviceSetApi.cpp.
References basePath, defaultHeaders, SWGSDRangel::SWGHttpRequestWorker::execute(), SWGSDRangel::SWGHttpRequestInput::headers, host, instanceDeviceSetPostCallback(), SWGSDRangel::SWGHttpRequestWorker::on_execution_finished(), and SWGSDRangel::stringValue().
{
     QString fullPath;
     fullPath.append(this->host).append(this->basePath).append("/sdrangel/deviceset");
     if (fullPath.indexOf("?") > 0)
       fullPath.append("&");
     else
       fullPath.append("?");
     fullPath.append(QUrl::toPercentEncoding("direction"))
         .append("=")
         .append(QUrl::toPercentEncoding(stringValue(direction)));
     SWGHttpRequestWorker *worker = new SWGHttpRequestWorker();
     SWGHttpRequestInput input(fullPath, "POST");
     foreach(QString key, this->defaultHeaders.keys()) {
         input.headers.insert(key, this->defaultHeaders.value(key));
     }
     connect(worker,
             &SWGHttpRequestWorker::on_execution_finished,
             this,
             &SWGDeviceSetApi::instanceDeviceSetPostCallback);
     worker->execute(&input);
 }
instanceDeviceSetPostCallback()
void SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetPostCallback (SWGHttpRequestWorker * worker) private
Definition at line 1070 of file SWGDeviceSetApi.cpp.
References SWGSDRangel::create(), SWGSDRangel::SWGHttpRequestWorker::error_str, SWGSDRangel::SWGHttpRequestWorker::error_type, instanceDeviceSetPostSignal(), instanceDeviceSetPostSignalE(), instanceDeviceSetPostSignalEFull(), and SWGSDRangel::SWGHttpRequestWorker::response.
Referenced by instanceDeviceSetPost().
{
     QString msg;
     QString error_str = worker->error_str;
     QNetworkReply::NetworkError error_type = worker->error_type;
     if (worker->error_type == QNetworkReply::NoError) {
         msg = QString("Success! %1 bytes").arg(worker->response.length());
     }
     else {
         msg = "Error: " + worker->error_str;
     }
     QString json(worker->response);
     SWGSuccessResponse* output = static_cast<SWGSuccessResponse*>(create(json, QString("SWGSuccessResponse")));
     worker->deleteLater();
     if (worker->error_type == QNetworkReply::NoError) {
         emit instanceDeviceSetPostSignal(output);
     } else {
         emit instanceDeviceSetPostSignalE(output, error_type, error_str);
         emit instanceDeviceSetPostSignalEFull(worker, error_type, error_str);
     }
 }
instanceDeviceSetPostSignal
void SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetPostSignal (SWGSuccessResponse * summary) signal
Referenced by instanceDeviceSetPostCallback().
instanceDeviceSetPostSignalE
void SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetPostSignalE (SWGSuccessResponse * summary, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by instanceDeviceSetPostCallback().
instanceDeviceSetPostSignalEFull
void SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetPostSignalEFull (SWGHttpRequestWorker * worker, QNetworkReply::NetworkError error_type, QString & error_str) signal
Referenced by instanceDeviceSetPostCallback().
Member Data Documentation
basePath
QString SWGSDRangel::SWGDeviceSetApi::basePath
Definition at line 42 of file SWGDeviceSetApi.h.
Referenced by devicesetChannelDelete(), devicesetChannelPost(), devicesetChannelReportGet(), devicesetChannelSettingsGet(), devicesetChannelSettingsPatch(), devicesetChannelSettingsPut(), devicesetChannelsReportGet(), devicesetDevicePut(), devicesetDeviceReportGet(), devicesetDeviceRunDelete(), devicesetDeviceRunGet(), devicesetDeviceRunPost(), devicesetDeviceSettingsGet(), devicesetDeviceSettingsPatch(), devicesetDeviceSettingsPut(), devicesetFocusPatch(), devicesetGet(), instanceDeviceSetDelete(), instanceDeviceSetPost(), and SWGDeviceSetApi().
defaultHeaders
QMap<QString, QString> SWGSDRangel::SWGDeviceSetApi::defaultHeaders
Definition at line 43 of file SWGDeviceSetApi.h.
Referenced by devicesetChannelDelete(), devicesetChannelPost(), devicesetChannelReportGet(), devicesetChannelSettingsGet(), devicesetChannelSettingsPatch(), devicesetChannelSettingsPut(), devicesetChannelsReportGet(), devicesetDevicePut(), devicesetDeviceReportGet(), devicesetDeviceRunDelete(), devicesetDeviceRunGet(), devicesetDeviceRunPost(), devicesetDeviceSettingsGet(), devicesetDeviceSettingsPatch(), devicesetDeviceSettingsPut(), devicesetFocusPatch(), devicesetGet(), instanceDeviceSetDelete(), and instanceDeviceSetPost().
host
QString SWGSDRangel::SWGDeviceSetApi::host
Definition at line 41 of file SWGDeviceSetApi.h.
Referenced by devicesetChannelDelete(), devicesetChannelPost(), devicesetChannelReportGet(), devicesetChannelSettingsGet(), devicesetChannelSettingsPatch(), devicesetChannelSettingsPut(), devicesetChannelsReportGet(), devicesetDevicePut(), devicesetDeviceReportGet(), devicesetDeviceRunDelete(), devicesetDeviceRunGet(), devicesetDeviceRunPost(), devicesetDeviceSettingsGet(), devicesetDeviceSettingsPatch(), devicesetDeviceSettingsPut(), devicesetFocusPatch(), devicesetGet(), instanceDeviceSetDelete(), instanceDeviceSetPost(), and SWGDeviceSetApi().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGDeviceSetApi.h
swagger/sdrangel/code/qt5/client/SWGDeviceSetApi.cpp