SDRAngel: XTRXOutput::MsgConfigureXTRX Class Reference
XTRXOutput::MsgConfigureXTRX Class Reference
#include <xtrxoutput.h>
Public Member Functions
const XTRXOutputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureXTRX * create (const XTRXOutputSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureXTRX (const XTRXOutputSettings &settings, bool force)
Private Attributes
XTRXOutputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 41 of file xtrxoutput.h.
Constructor & Destructor Documentation
MsgConfigureXTRX()
XTRXOutput::MsgConfigureXTRX::MsgConfigureXTRX (const XTRXOutputSettings & settings, bool force) inline private
Definition at line 57 of file xtrxoutput.h.
Referenced by create().
                                                                          :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureXTRX* XTRXOutput::MsgConfigureXTRX::create (const XTRXOutputSettings & settings, bool force) inline static
Definition at line 48 of file xtrxoutput.h.
References MsgConfigureXTRX().
Referenced by XTRXOutput::deserialize(), XTRXOutput::setCenterFrequency(), XTRXOutputGUI::updateHardware(), and XTRXOutput::webapiSettingsPutPatch().
         {
             return new MsgConfigureXTRX(settings, force);
         }
getForce()
bool XTRXOutput::MsgConfigureXTRX::getForce () const inline
Definition at line 46 of file xtrxoutput.h.
References m_force.
Referenced by XTRXOutput::handleMessage().
 { return m_force; }
getSettings()
const XTRXOutputSettings& XTRXOutput::MsgConfigureXTRX::getSettings () const inline
Definition at line 45 of file xtrxoutput.h.
References m_settings.
Referenced by XTRXOutputGUI::handleInputMessages(), and XTRXOutput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool XTRXOutput::MsgConfigureXTRX::m_force private
Definition at line 55 of file xtrxoutput.h.
Referenced by getForce().
m_settings
XTRXOutputSettings XTRXOutput::MsgConfigureXTRX::m_settings private
Definition at line 54 of file xtrxoutput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesink/xtrxoutput/xtrxoutput.h