SDRAngel: qrtplib::RTCPReceiverReportInfo Class Reference
qrtplib::RTCPReceiverReportInfo Class Reference
#include <rtpsourcedata.h>
Public Member Functions
RTCPReceiverReportInfo ()
void Set (uint8_t fraclost, int32_t plost, uint32_t exthigh, uint32_t jit, uint32_t l, uint32_t dl, const RTPTime &rcvtime)
bool HasInfo () const
double GetFractionLost () const
int32_t GetPacketsLost () const
uint32_t GetExtendedHighestSequenceNumber () const
uint32_t GetJitter () const
uint32_t GetLastSRTimestamp () const
uint32_t GetDelaySinceLastSR () const
RTPTime GetReceiveTime () const
Private Attributes
bool hasinfo
double fractionlost
int32_t packetslost
uint32_t exthighseqnr
uint32_t jitter
uint32_t lsr
uint32_t dlsr
RTPTime receivetime
Detailed Description
Definition at line 110 of file rtpsourcedata.h.
Constructor & Destructor Documentation
RTCPReceiverReportInfo()
qrtplib::RTCPReceiverReportInfo::RTCPReceiverReportInfo () inline
Definition at line 113 of file rtpsourcedata.h.
                              :
             receivetime(0, 0)
     {
         hasinfo = false;
         fractionlost = 0;
         packetslost = 0;
         exthighseqnr = 0;
         jitter = 0;
         lsr = 0;
         dlsr = 0;
     }
Member Function Documentation
GetDelaySinceLastSR()
uint32_t qrtplib::RTCPReceiverReportInfo::GetDelaySinceLastSR () const inline
Definition at line 160 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSourceData::INF_GetRoundtripTime().
     {
         return dlsr;
     }
GetExtendedHighestSequenceNumber()
uint32_t qrtplib::RTCPReceiverReportInfo::GetExtendedHighestSequenceNumber () const inline
Definition at line 148 of file rtpsourcedata.h.
     {
         return exthighseqnr;
     }
GetFractionLost()
double qrtplib::RTCPReceiverReportInfo::GetFractionLost () const inline
Definition at line 140 of file rtpsourcedata.h.
     {
         return fractionlost;
     }
GetJitter()
uint32_t qrtplib::RTCPReceiverReportInfo::GetJitter () const inline
Definition at line 152 of file rtpsourcedata.h.
     {
         return jitter;
     }
GetLastSRTimestamp()
uint32_t qrtplib::RTCPReceiverReportInfo::GetLastSRTimestamp () const inline
Definition at line 156 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSourceData::INF_GetRoundtripTime().
     {
         return lsr;
     }
GetPacketsLost()
int32_t qrtplib::RTCPReceiverReportInfo::GetPacketsLost () const inline
Definition at line 144 of file rtpsourcedata.h.
     {
         return packetslost;
     }
GetReceiveTime()
RTPTime qrtplib::RTCPReceiverReportInfo::GetReceiveTime () const inline
Definition at line 164 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSourceData::INF_GetRoundtripTime().
     {
         return receivetime;
     }
HasInfo()
bool qrtplib::RTCPReceiverReportInfo::HasInfo () const inline
Definition at line 136 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSourceData::INF_GetRoundtripTime().
     {
         return hasinfo;
     }
Set()
void qrtplib::RTCPReceiverReportInfo::Set (uint8_t fraclost, int32_t plost, uint32_t exthigh, uint32_t jit, uint32_t l, uint32_t dl, const RTPTime & rcvtime) inline
Definition at line 124 of file rtpsourcedata.h.
     {
         fractionlost = ((double) fraclost) / 256.0;
         packetslost = plost;
         exthighseqnr = exthigh;
         jitter = jit;
         lsr = l;
         dlsr = dl;
         receivetime = rcvtime;
         hasinfo = true;
     }
Member Data Documentation
dlsr
uint32_t qrtplib::RTCPReceiverReportInfo::dlsr private
Definition at line 175 of file rtpsourcedata.h.
exthighseqnr
uint32_t qrtplib::RTCPReceiverReportInfo::exthighseqnr private
Definition at line 172 of file rtpsourcedata.h.
fractionlost
double qrtplib::RTCPReceiverReportInfo::fractionlost private
Definition at line 170 of file rtpsourcedata.h.
hasinfo
bool qrtplib::RTCPReceiverReportInfo::hasinfo private
Definition at line 169 of file rtpsourcedata.h.
jitter
uint32_t qrtplib::RTCPReceiverReportInfo::jitter private
Definition at line 173 of file rtpsourcedata.h.
lsr
uint32_t qrtplib::RTCPReceiverReportInfo::lsr private
Definition at line 174 of file rtpsourcedata.h.
packetslost
int32_t qrtplib::RTCPReceiverReportInfo::packetslost private
Definition at line 171 of file rtpsourcedata.h.
receivetime
RTPTime qrtplib::RTCPReceiverReportInfo::receivetime private
Definition at line 176 of file rtpsourcedata.h.
The documentation for this class was generated from the following file:
qrtplib/rtpsourcedata.h