SDRAngel: RTLSDRGui Class Reference
RTLSDRGui Class Reference
#include <rtlsdrgui.h>
Public Member Functions
RTLSDRGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~RTLSDRGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_centerFrequency_changed (quint64 value)
void on_sampleRate_changed (quint64 value)
void on_offsetTuning_toggled (bool checked)
void on_rfBW_changed (quint64 value)
void on_lowSampleRate_toggled (bool checked)
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_decim_currentIndexChanged (int index)
void on_fcPos_currentIndexChanged (int index)
void on_ppm_valueChanged (int value)
void on_gain_valueChanged (int value)
void on_checkBox_stateChanged (int state)
void on_agc_stateChanged (int state)
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void on_transverter_clicked ()
void on_sampleRateMode_toggled (bool checked)
void openDeviceSettingsDialog (const QPoint &p)
void updateHardware ()
void updateStatus ()
Private Member Functions
void displayGains ()
void displaySampleRate ()
void displayFcTooltip ()
void displaySettings ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void updateFrequencyLimits ()
void blockApplySettings (bool block)
Private Attributes
Ui::RTLSDRGui * ui
DeviceUISet * m_deviceUISet
bool m_doApplySettings
bool m_forceSettings
RTLSDRSettings m_settings
bool m_sampleRateMode
true: device, false: base band sample rate update mode
QTimer m_updateTimer
QTimer m_statusTimer
std::vector< int > m_gains
RTLSDRInput * m_sampleSource
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 36 of file rtlsdrgui.h.
Constructor & Destructor Documentation
RTLSDRGui()
RTLSDRGui::RTLSDRGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 36 of file rtlsdrgui.cpp.
References displayGains(), displaySettings(), RTLSDRInput::getGains(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, ColorMapper::GrayYellow, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_gains, m_inputMessageQueue, m_sampleSource, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), RTLSDRInput::setMessageQueueToGUI(), ui, updateFrequencyLimits(), updateHardware(), and updateStatus().
                                                               :
     QWidget(parent),
     ui(new Ui::RTLSDRGui),
     m_deviceUISet(deviceUISet),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_settings(),
     m_sampleRateMode(true),
     m_sampleSource(0),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     m_sampleSource = (RTLSDRInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     updateFrequencyLimits();
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->rfBW->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     ui->rfBW->setValueRange(4, 350, 8000);
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     displaySettings();
     m_gains = m_sampleSource->getGains();
     displayGains();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
 }
~RTLSDRGui()
RTLSDRGui::~RTLSDRGui () virtual
Definition at line 74 of file rtlsdrgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void RTLSDRGui::blockApplySettings (bool block) private
Definition at line 469 of file rtlsdrgui.cpp.
References m_doApplySettings.
Referenced by handleMessage().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool RTLSDRGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 130 of file rtlsdrgui.cpp.
References RTLSDRSettings::deserialize(), displayGains(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data))
     {
         displayGains();
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void RTLSDRGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 79 of file rtlsdrgui.cpp.
 {
     delete this;
 }
displayFcTooltip()
void RTLSDRGui::displayFcTooltip () private
Definition at line 295 of file rtlsdrgui.cpp.
References arg(), DeviceSampleSource::calculateFrequencyShift(), RTLSDRSettings::m_devSampleRate, RTLSDRSettings::m_fcPos, RTLSDRSettings::m_log2Decim, m_settings, and ui.
Referenced by displaySampleRate(), on_fcPos_currentIndexChanged(), and on_sampleRate_changed().
 {
     int32_t fShift = DeviceSampleSource::calculateFrequencyShift(
         m_settings.m_log2Decim,
         (DeviceSampleSource::fcPos_t) m_settings.m_fcPos,
         m_settings.m_devSampleRate,
         DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD
     );
     ui->fcPos->setToolTip(tr("Relative position of device center frequency: %1 kHz").arg(QString::number(fShift / 1000.0f, 'g', 5)));
 }
displayGains()
void RTLSDRGui::displayGains () private
Definition at line 224 of file rtlsdrgui.cpp.
References abs(), arg(), i, RTLSDRSettings::m_gain, m_gains, m_settings, and ui.
Referenced by deserialize(), handleMessage(), and RTLSDRGui().
 {
     if (m_gains.size() > 0)
     {
         int dist = abs(m_settings.m_gain - m_gains[0]);
         int pos = 0;
         for (uint i = 1; i < m_gains.size(); i++)
         {
             if (abs(m_settings.m_gain - m_gains[i]) < dist)
             {
                 dist = abs(m_settings.m_gain - m_gains[i]);
                 pos = i;
             }
         }
         ui->gainText->setText(tr("%1.%2").arg(m_gains[pos] / 10).arg(abs(m_gains[pos] % 10)));
         ui->gain->setMaximum(m_gains.size() - 1);
         ui->gain->setEnabled(true);
         ui->gain->setValue(pos);
     }
     else
     {
         ui->gain->setMaximum(0);
         ui->gain->setEnabled(false);
         ui->gain->setValue(0);
     }
 }
displaySampleRate()
void RTLSDRGui::displaySampleRate () private
Definition at line 253 of file rtlsdrgui.cpp.
References arg(), displayFcTooltip(), RTLSDRSettings::m_devSampleRate, RTLSDRSettings::m_log2Decim, RTLSDRSettings::m_lowSampleRate, m_sampleRateMode, m_settings, RTLSDRInput::sampleRateHighRangeMax, RTLSDRInput::sampleRateHighRangeMin, RTLSDRInput::sampleRateLowRangeMax, RTLSDRInput::sampleRateLowRangeMin, and ui.
Referenced by displaySettings(), on_decim_currentIndexChanged(), on_lowSampleRate_toggled(), on_sampleRateMode_toggled(), and updateSampleRateAndFrequency().
 {
     ui->sampleRate->blockSignals(true);
     displayFcTooltip();
     if (m_sampleRateMode)
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(60,60,60); }");
         ui->sampleRateMode->setText("SR");
         if (m_settings.m_lowSampleRate) {
             ui->sampleRate->setValueRange(7, RTLSDRInput::sampleRateLowRangeMin, RTLSDRInput::sampleRateLowRangeMax);
         } else {
             ui->sampleRate->setValueRange(7, RTLSDRInput::sampleRateHighRangeMin, RTLSDRInput::sampleRateHighRangeMax);
         }
         ui->sampleRate->setValue(m_settings.m_devSampleRate);
         ui->sampleRate->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setToolTip("Baseband sample rate (S/s)");
         uint32_t basebandSampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Decim);
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(basebandSampleRate / 1000.0f, 'g', 5)));
     }
     else
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(50,50,50); }");
         ui->sampleRateMode->setText("BB");
         if (m_settings.m_lowSampleRate) {
             ui->sampleRate->setValueRange(7, RTLSDRInput::sampleRateLowRangeMin/(1<<m_settings.m_log2Decim), RTLSDRInput::sampleRateLowRangeMax/(1<<m_settings.m_log2Decim));
         } else {
             ui->sampleRate->setValueRange(7, RTLSDRInput::sampleRateHighRangeMin/(1<<m_settings.m_log2Decim), RTLSDRInput::sampleRateHighRangeMax/(1<<m_settings.m_log2Decim));
         }
         ui->sampleRate->setValue(m_settings.m_devSampleRate/(1<<m_settings.m_log2Decim));
         ui->sampleRate->setToolTip("Baseband sample rate (S/s)");
         ui->deviceRateText->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_settings.m_devSampleRate / 1000.0f, 'g', 5)));
     }
     ui->sampleRate->blockSignals(false);
 }
displaySettings()
void RTLSDRGui::displaySettings () private
Definition at line 306 of file rtlsdrgui.cpp.
References arg(), displaySampleRate(), RTLSDRSettings::m_agc, RTLSDRSettings::m_centerFrequency, RTLSDRSettings::m_dcBlock, RTLSDRSettings::m_fcPos, RTLSDRSettings::m_iqImbalance, RTLSDRSettings::m_log2Decim, RTLSDRSettings::m_loPpmCorrection, RTLSDRSettings::m_lowSampleRate, RTLSDRSettings::m_noModMode, RTLSDRSettings::m_offsetTuning, RTLSDRSettings::m_rfBandwidth, m_settings, RTLSDRSettings::m_transverterDeltaFrequency, RTLSDRSettings::m_transverterMode, ui, and updateFrequencyLimits().
Referenced by deserialize(), handleMessage(), resetToDefaults(), RTLSDRGui(), and setCenterFrequency().
 {
     ui->transverter->setDeltaFrequency(m_settings.m_transverterDeltaFrequency);
     ui->transverter->setDeltaFrequencyActive(m_settings.m_transverterMode);
     updateFrequencyLimits();
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     displaySampleRate();
     ui->rfBW->setValue(m_settings.m_rfBandwidth / 1000);
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqImbalance);
     ui->ppm->setValue(m_settings.m_loPpmCorrection);
     ui->ppmText->setText(tr("%1").arg(m_settings.m_loPpmCorrection));
     ui->decim->setCurrentIndex(m_settings.m_log2Decim);
     ui->fcPos->setCurrentIndex((int) m_settings.m_fcPos);
     ui->checkBox->setChecked(m_settings.m_noModMode);
     ui->agc->setChecked(m_settings.m_agc);
     ui->lowSampleRate->setChecked(m_settings.m_lowSampleRate);
     ui->offsetTuning->setChecked(m_settings.m_offsetTuning);
 }
getCenterFrequency()
qint64 RTLSDRGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 101 of file rtlsdrgui.cpp.
References RTLSDRSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* RTLSDRGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 52 of file rtlsdrgui.h.
 { return &m_inputMessageQueue; }
getName()
QString RTLSDRGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 89 of file rtlsdrgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void RTLSDRGui::handleInputMessages () private slot
Definition at line 174 of file rtlsdrgui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by RTLSDRGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("RTLSDRGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("RTLSDRGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool RTLSDRGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 147 of file rtlsdrgui.cpp.
References blockApplySettings(), displayGains(), displaySettings(), RTLSDRInput::MsgConfigureRTLSDR::getSettings(), RTLSDRInput::MsgStartStop::getStartStop(), m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (RTLSDRInput::MsgConfigureRTLSDR::match(message))
     {
         const RTLSDRInput::MsgConfigureRTLSDR& cfg = (RTLSDRInput::MsgConfigureRTLSDR&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displayGains();
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (RTLSDRInput::MsgStartStop::match(message))
     {
         RTLSDRInput::MsgStartStop& notif = (RTLSDRInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_agc_stateChanged
void RTLSDRGui::on_agc_stateChanged (int state) private slot
Definition at line 497 of file rtlsdrgui.cpp.
References RTLSDRSettings::m_agc, m_settings, and sendSettings().
 {
     m_settings.m_agc = (state == Qt::Checked);
     sendSettings();
 }
on_centerFrequency_changed
void RTLSDRGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 334 of file rtlsdrgui.cpp.
References RTLSDRSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_checkBox_stateChanged
void RTLSDRGui::on_checkBox_stateChanged (int state) private slot
Definition at line 474 of file rtlsdrgui.cpp.
References RTLSDRSettings::m_centerFrequency, RTLSDRSettings::m_noModMode, m_settings, sendSettings(), ui, and updateFrequencyLimits().
 {
     if (state == Qt::Checked)
     {
         ui->gain->setEnabled(false);
         m_settings.m_noModMode = true;
         updateFrequencyLimits();
         ui->centerFrequency->setValue(7000);
         m_settings.m_centerFrequency = 7000 * 1000;
     }
     else
     {
         ui->gain->setEnabled(true);
         m_settings.m_noModMode = false;
         updateFrequencyLimits();
         ui->centerFrequency->setValue(434000);
         ui->gain->setValue(0);
         m_settings.m_centerFrequency = 435000 * 1000;
     }
     sendSettings();
 }
on_dcOffset_toggled
void RTLSDRGui::on_dcOffset_toggled (bool checked) private slot
Definition at line 113 of file rtlsdrgui.cpp.
References RTLSDRSettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_decim_currentIndexChanged
void RTLSDRGui::on_decim_currentIndexChanged (int index) private slot
Definition at line 340 of file rtlsdrgui.cpp.
References displaySampleRate(), RTLSDRSettings::m_devSampleRate, RTLSDRSettings::m_log2Decim, m_sampleRateMode, m_settings, sendSettings(), and ui.
 {
     if ((index <0) || (index > 6)) {
         return;
     }
     m_settings.m_log2Decim = index;
     displaySampleRate();
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     } else {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew() * (1 << m_settings.m_log2Decim);
     }
     sendSettings();
 }
on_fcPos_currentIndexChanged
void RTLSDRGui::on_fcPos_currentIndexChanged (int index) private slot
Definition at line 358 of file rtlsdrgui.cpp.
References displayFcTooltip(), RTLSDRSettings::m_fcPos, m_settings, and sendSettings().
 {
     m_settings.m_fcPos = (RTLSDRSettings::fcPos_t) (index < 0 ? 0 : index > 2 ? 2 : index);
     displayFcTooltip();
     sendSettings();
 }
on_gain_valueChanged
void RTLSDRGui::on_gain_valueChanged (int value) private slot
Definition at line 378 of file rtlsdrgui.cpp.
References abs(), arg(), RTLSDRSettings::m_gain, m_gains, m_settings, sendSettings(), and ui.
 {
     if (value > (int)m_gains.size())
     {
         return;
     }
     int gain = m_gains[value];
     ui->gainText->setText(tr("%1.%2").arg(gain / 10).arg(abs(gain % 10)));
     m_settings.m_gain = gain;
     sendSettings();
 }
on_iqImbalance_toggled
void RTLSDRGui::on_iqImbalance_toggled (bool checked) private slot
Definition at line 119 of file rtlsdrgui.cpp.
References RTLSDRSettings::m_iqImbalance, m_settings, and sendSettings().
 {
     m_settings.m_iqImbalance = checked;
     sendSettings();
 }
on_lowSampleRate_toggled
void RTLSDRGui::on_lowSampleRate_toggled (bool checked) private slot
Definition at line 527 of file rtlsdrgui.cpp.
References displaySampleRate(), RTLSDRSettings::m_devSampleRate, RTLSDRSettings::m_log2Decim, RTLSDRSettings::m_lowSampleRate, m_sampleRateMode, m_settings, sendSettings(), and ui.
 {
     m_settings.m_lowSampleRate = checked;
     displaySampleRate();
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     } else {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew() * (1 << m_settings.m_log2Decim);
     }
     qDebug("RTLSDRGui::on_lowSampleRate_toggled: %d S/s", m_settings.m_devSampleRate);
     sendSettings();
 }
on_offsetTuning_toggled
void RTLSDRGui::on_offsetTuning_toggled (bool checked) private slot
Definition at line 515 of file rtlsdrgui.cpp.
References RTLSDRSettings::m_offsetTuning, m_settings, and sendSettings().
 {
     m_settings.m_offsetTuning = checked;
     sendSettings();
 }
on_ppm_valueChanged
void RTLSDRGui::on_ppm_valueChanged (int value) private slot
Definition at line 365 of file rtlsdrgui.cpp.
References arg(), RTLSDRSettings::m_loPpmCorrection, m_settings, sendSettings(), and ui.
 {
     if ((value > 99) || (value < -99))
     {
         return;
     }
     ui->ppmText->setText(tr("%1").arg(value));
     m_settings.m_loPpmCorrection = value;
     sendSettings();
 }
on_record_toggled
void RTLSDRGui::on_record_toggled (bool checked) private slot
Definition at line 401 of file rtlsdrgui.cpp.
References RTLSDRInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     RTLSDRInput::MsgFileRecord* message = RTLSDRInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_rfBW_changed
void RTLSDRGui::on_rfBW_changed (quint64 value) private slot
Definition at line 521 of file rtlsdrgui.cpp.
References RTLSDRSettings::m_rfBandwidth, m_settings, and sendSettings().
 {
     m_settings.m_rfBandwidth = value * 1000;
     sendSettings();
 }
on_sampleRate_changed
void RTLSDRGui::on_sampleRate_changed (quint64 value) private slot
Definition at line 503 of file rtlsdrgui.cpp.
References displayFcTooltip(), RTLSDRSettings::m_devSampleRate, RTLSDRSettings::m_log2Decim, m_sampleRateMode, m_settings, and sendSettings().
 {
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = value;
     } else {
         m_settings.m_devSampleRate = value * (1 << m_settings.m_log2Decim);
     }
     displayFcTooltip();
     sendSettings();
 }
on_sampleRateMode_toggled
void RTLSDRGui::on_sampleRateMode_toggled (bool checked) private slot
Definition at line 423 of file rtlsdrgui.cpp.
References displaySampleRate(), and m_sampleRateMode.
 {
     m_sampleRateMode = checked;
     displaySampleRate();
 }
on_startStop_toggled
void RTLSDRGui::on_startStop_toggled (bool checked) private slot
Definition at line 392 of file rtlsdrgui.cpp.
References RTLSDRInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         RTLSDRInput::MsgStartStop *message = RTLSDRInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
on_transverter_clicked
void RTLSDRGui::on_transverter_clicked () private slot
Definition at line 413 of file rtlsdrgui.cpp.
References RTLSDRSettings::m_centerFrequency, m_settings, RTLSDRSettings::m_transverterDeltaFrequency, RTLSDRSettings::m_transverterMode, sendSettings(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("RTLSDRGui::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     m_settings.m_centerFrequency = ui->centerFrequency->getValueNew()*1000;
     sendSettings();
 }
openDeviceSettingsDialog
void RTLSDRGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 544 of file rtlsdrgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), RTLSDRSettings::m_reverseAPIAddress, RTLSDRSettings::m_reverseAPIDeviceIndex, RTLSDRSettings::m_reverseAPIPort, m_settings, RTLSDRSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by RTLSDRGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void RTLSDRGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 94 of file rtlsdrgui.cpp.
References displaySettings(), m_settings, RTLSDRSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void RTLSDRGui::sendSettings () private
Definition at line 326 of file rtlsdrgui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_agc_stateChanged(), on_centerFrequency_changed(), on_checkBox_stateChanged(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_gain_valueChanged(), on_iqImbalance_toggled(), on_lowSampleRate_toggled(), on_offsetTuning_toggled(), on_ppm_valueChanged(), on_rfBW_changed(), on_sampleRate_changed(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
     {
         m_updateTimer.start(100);
     }
 }
serialize()
QByteArray RTLSDRGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 125 of file rtlsdrgui.cpp.
References m_settings, and RTLSDRSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void RTLSDRGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 106 of file rtlsdrgui.cpp.
References displaySettings(), RTLSDRSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void RTLSDRGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 84 of file rtlsdrgui.cpp.
 {
     setObjectName(name);
 }
updateFrequencyLimits()
void RTLSDRGui::updateFrequencyLimits () private
Definition at line 209 of file rtlsdrgui.cpp.
References RTLSDRInput::frequencyHighRangeMax, RTLSDRInput::frequencyHighRangeMin, RTLSDRInput::frequencyLowRangeMax, RTLSDRInput::frequencyLowRangeMin, RTLSDRSettings::m_noModMode, m_settings, RTLSDRSettings::m_transverterDeltaFrequency, RTLSDRSettings::m_transverterMode, and ui.
Referenced by displaySettings(), on_checkBox_stateChanged(), on_transverter_clicked(), and RTLSDRGui().
 {
     // values in kHz
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     qint64 minLimit = (m_settings.m_noModMode ? RTLSDRInput::frequencyLowRangeMin : RTLSDRInput::frequencyHighRangeMin) + deltaFrequency;
     qint64 maxLimit = (m_settings.m_noModMode ? RTLSDRInput::frequencyLowRangeMax : RTLSDRInput::frequencyHighRangeMax) + deltaFrequency;
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("RTLSDRGui::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void RTLSDRGui::updateHardware () private slot
Definition at line 429 of file rtlsdrgui.cpp.
References RTLSDRInput::MsgConfigureRTLSDR::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by RTLSDRGui().
 {
     if (m_doApplySettings)
     {
         RTLSDRInput::MsgConfigureRTLSDR* message = RTLSDRInput::MsgConfigureRTLSDR::create(m_settings, m_forceSettings);
         m_sampleSource->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void RTLSDRGui::updateSampleRateAndFrequency () private
Definition at line 202 of file rtlsdrgui.cpp.
References displaySampleRate(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), and GLSpectrum::setSampleRate().
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     displaySampleRate();
 }
updateStatus
void RTLSDRGui::updateStatus () private slot
Definition at line 440 of file rtlsdrgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by RTLSDRGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 RTLSDRGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 68 of file rtlsdrgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* RTLSDRGui::m_deviceUISet private
Definition at line 58 of file rtlsdrgui.h.
Referenced by RTLSDRGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool RTLSDRGui::m_doApplySettings private
Definition at line 59 of file rtlsdrgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_forceSettings
bool RTLSDRGui::m_forceSettings private
Definition at line 60 of file rtlsdrgui.h.
Referenced by deserialize(), and updateHardware().
m_gains
std::vector<int> RTLSDRGui::m_gains private
Definition at line 65 of file rtlsdrgui.h.
Referenced by displayGains(), on_gain_valueChanged(), and RTLSDRGui().
m_inputMessageQueue
MessageQueue RTLSDRGui::m_inputMessageQueue private
Definition at line 70 of file rtlsdrgui.h.
Referenced by handleInputMessages(), and RTLSDRGui().
m_lastEngineState
int RTLSDRGui::m_lastEngineState private
Definition at line 69 of file rtlsdrgui.h.
Referenced by updateStatus().
m_sampleRate
int RTLSDRGui::m_sampleRate private
Definition at line 67 of file rtlsdrgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateMode
bool RTLSDRGui::m_sampleRateMode private
true: device, false: base band sample rate update mode
Definition at line 62 of file rtlsdrgui.h.
Referenced by displaySampleRate(), on_decim_currentIndexChanged(), on_lowSampleRate_toggled(), on_sampleRate_changed(), and on_sampleRateMode_toggled().
m_sampleSource
RTLSDRInput* RTLSDRGui::m_sampleSource private
Definition at line 66 of file rtlsdrgui.h.
Referenced by on_record_toggled(), on_startStop_toggled(), RTLSDRGui(), and updateHardware().
m_settings
RTLSDRSettings RTLSDRGui::m_settings private
Definition at line 61 of file rtlsdrgui.h.
Referenced by deserialize(), displayFcTooltip(), displayGains(), displaySampleRate(), displaySettings(), getCenterFrequency(), handleMessage(), on_agc_stateChanged(), on_centerFrequency_changed(), on_checkBox_stateChanged(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_gain_valueChanged(), on_iqImbalance_toggled(), on_lowSampleRate_toggled(), on_offsetTuning_toggled(), on_ppm_valueChanged(), on_rfBW_changed(), on_sampleRate_changed(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), updateFrequencyLimits(), and updateHardware().
m_statusTimer
QTimer RTLSDRGui::m_statusTimer private
Definition at line 64 of file rtlsdrgui.h.
Referenced by RTLSDRGui().
m_updateTimer
QTimer RTLSDRGui::m_updateTimer private
Definition at line 63 of file rtlsdrgui.h.
Referenced by RTLSDRGui(), sendSettings(), and updateHardware().
ui
Ui::RTLSDRGui* RTLSDRGui::ui private
Definition at line 56 of file rtlsdrgui.h.
Referenced by displayFcTooltip(), displayGains(), displaySampleRate(), displaySettings(), handleMessage(), on_checkBox_stateChanged(), on_decim_currentIndexChanged(), on_gain_valueChanged(), on_lowSampleRate_toggled(), on_ppm_valueChanged(), on_record_toggled(), on_transverter_clicked(), RTLSDRGui(), updateFrequencyLimits(), updateStatus(), and ~RTLSDRGui().
The documentation for this class was generated from the following files:
plugins/samplesource/rtlsdr/rtlsdrgui.h
plugins/samplesource/rtlsdr/rtlsdrgui.cpp