SDRAngel: AudioDeviceManager Class Reference
AudioDeviceManager Class Reference
#include <audiodevicemanager.h>
Classes
class InputDeviceInfo
class OutputDeviceInfo
Public Member Functions
AudioDeviceManager ()
~AudioDeviceManager ()
const QList< QAudioDeviceInfo > & getInputDevices () const
const QList< QAudioDeviceInfo > & getOutputDevices () const
bool getOutputDeviceName (int outputDeviceIndex, QString &deviceName) const
bool getInputDeviceName (int inputDeviceIndex, QString &deviceName) const
int getOutputDeviceIndex (const QString &deviceName) const
int getInputDeviceIndex (const QString &deviceName) const
void addAudioSink (AudioFifo *audioFifo, MessageQueue *sampleSinkMessageQueue, int outputDeviceIndex=-1)
Add the audio sink.
void removeAudioSink (AudioFifo *audioFifo)
Remove the audio sink.
void addAudioSource (AudioFifo *audioFifo, MessageQueue *sampleSourceMessageQueue, int inputDeviceIndex=-1)
Add an audio source.
void removeAudioSource (AudioFifo *audioFifo)
Remove an audio source.
bool getInputDeviceInfo (const QString &deviceName, InputDeviceInfo &deviceInfo) const
bool getOutputDeviceInfo (const QString &deviceName, OutputDeviceInfo &deviceInfo) const
int getInputSampleRate (int inputDeviceIndex=-1)
int getOutputSampleRate (int outputDeviceIndex=-1)
void setInputDeviceInfo (int inputDeviceIndex, const InputDeviceInfo &deviceInfo)
void setOutputDeviceInfo (int outputDeviceIndex, const OutputDeviceInfo &deviceInfo)
void unsetInputDeviceInfo (int inputDeviceIndex)
void unsetOutputDeviceInfo (int outputDeviceIndex)
void inputInfosCleanup ()
Remove input info from map for input devices not present.
void outputInfosCleanup ()
Remove output info from map for output devices not present.
Static Public Attributes
static const unsigned int m_defaultAudioSampleRate = 48000
static const float m_defaultAudioInputVolume = 1.0f
static const QString m_defaultUDPAddress = "127.0.0.1"
static const quint16 m_defaultUDPPort = 9998
static const QString m_defaultDeviceName = "System default device"
Private Member Functions
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
void startAudioOutput (int outputDeviceIndex)
void stopAudioOutput (int outputDeviceIndex)
void startAudioInput (int inputDeviceIndex)
void stopAudioInput (int inputDeviceIndex)
void serializeInputMap (QByteArray &data) const
void deserializeInputMap (QByteArray &data)
void debugAudioInputInfos () const
void serializeOutputMap (QByteArray &data) const
void deserializeOutputMap (QByteArray &data)
void debugAudioOutputInfos () const
Private Attributes
QList< QAudioDeviceInfo > m_inputDevicesInfo
QList< QAudioDeviceInfo > m_outputDevicesInfo
QMap< AudioFifo *, int > m_audioSinkFifos
QMap< AudioFifo *, MessageQueue * > m_audioFifoToSinkMessageQueues
audio sink FIFO to attached sink message queue
QMap< int, QList< MessageQueue * > > m_outputDeviceSinkMessageQueues
sink message queues attached to device
QMap< int, AudioOutput * > m_audioOutputs
audio device index to audio output map (index -1 is default device)
QMap< QString, OutputDeviceInfo > m_audioOutputInfos
audio device name to audio output info
QMap< AudioFifo *, int > m_audioSourceFifos
QMap< AudioFifo *, MessageQueue * > m_audioFifoToSourceMessageQueues
audio source FIFO to attached source message queue
QMap< int, QList< MessageQueue * > > m_inputDeviceSourceMessageQueues
sink message queues attached to device
QMap< int, AudioInput * > m_audioInputs
audio device index to audio input map (index -1 is default device)
QMap< QString, InputDeviceInfo > m_audioInputInfos
audio device name to audio input device info
Friends
class MainSettings
Detailed Description
Definition at line 35 of file audiodevicemanager.h.
Constructor & Destructor Documentation
AudioDeviceManager()
AudioDeviceManager::AudioDeviceManager ()
Definition at line 75 of file audiodevicemanager.cpp.
References i, m_inputDevicesInfo, and m_outputDevicesInfo.
 {
     qDebug("AudioDeviceManager::AudioDeviceManager: scan input devices");
     m_inputDevicesInfo = QAudioDeviceInfo::availableDevices(QAudio::AudioInput);
     for (int i = 0; i < m_inputDevicesInfo.size(); i++) {
         qDebug("AudioDeviceManager::AudioDeviceManager: input device #%d: %s", i, qPrintable(m_inputDevicesInfo[i].deviceName()));
     }
     qDebug("AudioDeviceManager::AudioDeviceManager: scan output devices");
     m_outputDevicesInfo = QAudioDeviceInfo::availableDevices(QAudio::AudioOutput);
     for (int i = 0; i < m_outputDevicesInfo.size(); i++) {
         qDebug("AudioDeviceManager::AudioDeviceManager: output device #%d: %s", i, qPrintable(m_outputDevicesInfo[i].deviceName()));
     }
 }
~AudioDeviceManager()
AudioDeviceManager::~AudioDeviceManager ()
Definition at line 92 of file audiodevicemanager.cpp.
References m_audioOutputs.
 {
     QMap<int, AudioOutput*>::iterator it = m_audioOutputs.begin();
     for (; it != m_audioOutputs.end(); ++it) {
         delete(*it);
     }
 }
Member Function Documentation
addAudioSink()
void AudioDeviceManager::addAudioSink (AudioFifo * audioFifo, MessageQueue * sampleSinkMessageQueue, int outputDeviceIndex = -1)
Add the audio sink.
Definition at line 249 of file audiodevicemanager.cpp.
References m_audioFifoToSinkMessageQueues, m_audioOutputs, m_audioSinkFifos, m_outputDeviceSinkMessageQueues, removeAudioSink(), and startAudioOutput().
Referenced by AMDemod::AMDemod(), AMMod::AMMod(), WFMDemod::applySettings(), AMDemod::applySettings(), UDPSink::applySettings(), NFMDemod::applySettings(), DSDDemod::applySettings(), BFMDemod::applySettings(), AMMod::applySettings(), NFMMod::applySettings(), SSBDemod::applySettings(), SSBMod::applySettings(), FreeDVDemod::applySettings(), DATVDemod::applySettings(), BFMDemod::BFMDemod(), DATVDemod::DATVDemod(), DSDDemod::DSDDemod(), FreeDVDemod::FreeDVDemod(), NFMDemod::NFMDemod(), NFMMod::NFMMod(), SSBDemod::SSBDemod(), SSBMod::SSBMod(), and WFMDemod::WFMDemod().
 {
     qDebug("AudioDeviceManager::addAudioSink: %d: %p", outputDeviceIndex, audioFifo);
     if (m_audioOutputs.find(outputDeviceIndex) == m_audioOutputs.end()) {
         m_audioOutputs[outputDeviceIndex] = new AudioOutput();
     }
     if (m_audioOutputs[outputDeviceIndex]->getNbFifos() == 0) {
         startAudioOutput(outputDeviceIndex);
     }
     if (m_audioSinkFifos.find(audioFifo) == m_audioSinkFifos.end()) // new FIFO
     {
         m_audioOutputs[outputDeviceIndex]->addFifo(audioFifo);
         m_audioSinkFifos[audioFifo] = outputDeviceIndex; // register audio FIFO
         m_audioFifoToSinkMessageQueues[audioFifo] = sampleSinkMessageQueue;
         m_outputDeviceSinkMessageQueues[outputDeviceIndex].append(sampleSinkMessageQueue);
     }
     else
     {
         int audioOutputDeviceIndex = m_audioSinkFifos[audioFifo];
         if (audioOutputDeviceIndex != outputDeviceIndex) // change of audio device
         {
             removeAudioSink(audioFifo); // remove from current
             m_audioOutputs[outputDeviceIndex]->addFifo(audioFifo); // add to new
             m_audioSinkFifos[audioFifo] = outputDeviceIndex; // new index
             m_outputDeviceSinkMessageQueues[audioOutputDeviceIndex].removeOne(sampleSinkMessageQueue);
             m_outputDeviceSinkMessageQueues[outputDeviceIndex].append(sampleSinkMessageQueue);
         }
     }
 }
addAudioSource()
void AudioDeviceManager::addAudioSource (AudioFifo * audioFifo, MessageQueue * sampleSourceMessageQueue, int inputDeviceIndex = -1)
Add an audio source.
Definition at line 305 of file audiodevicemanager.cpp.
References m_audioFifoToSourceMessageQueues, m_audioInputs, m_audioSourceFifos, m_outputDeviceSinkMessageQueues, removeAudioSource(), and startAudioInput().
Referenced by AMMod::AMMod(), WFMMod::applySettings(), AMMod::applySettings(), NFMMod::applySettings(), FreeDVMod::applySettings(), SSBMod::applySettings(), FreeDVMod::FreeDVMod(), NFMMod::NFMMod(), SSBMod::SSBMod(), and WFMMod::WFMMod().
 {
     qDebug("AudioDeviceManager::addAudioSource: %d: %p", inputDeviceIndex, audioFifo);
     if (m_audioInputs.find(inputDeviceIndex) == m_audioInputs.end()) {
         m_audioInputs[inputDeviceIndex] = new AudioInput();
     }
     if (m_audioInputs[inputDeviceIndex]->getNbFifos() == 0) {
         startAudioInput(inputDeviceIndex);
     }
     if (m_audioSourceFifos.find(audioFifo) == m_audioSourceFifos.end()) // new FIFO
     {
         m_audioInputs[inputDeviceIndex]->addFifo(audioFifo);
     }
     else
     {
         int audioInputDeviceIndex = m_audioSourceFifos[audioFifo];
         if (audioInputDeviceIndex != inputDeviceIndex) // change of audio device
         {
             removeAudioSource(audioFifo); // remove from current
             m_audioInputs[inputDeviceIndex]->addFifo(audioFifo); // add to new
         }
     }
     m_audioSourceFifos[audioFifo] = inputDeviceIndex; // register audio FIFO
     m_audioFifoToSourceMessageQueues[audioFifo] = sampleSourceMessageQueue;
     m_outputDeviceSinkMessageQueues[inputDeviceIndex].append(sampleSourceMessageQueue);
 }
debugAudioInputInfos()
void AudioDeviceManager::debugAudioInputInfos () const private
Definition at line 760 of file audiodevicemanager.cpp.
References m_audioInputInfos.
Referenced by deserialize(), and serialize().
 {
     QMap<QString, InputDeviceInfo>::const_iterator it = m_audioInputInfos.begin();
     for (; it != m_audioInputInfos.end(); ++it)
     {
         qDebug() << "AudioDeviceManager::debugAudioInputInfos:"
                 << " name: " << it.key()
                 << " sampleRate: " << it.value().sampleRate
                 << " volume: " << it.value().volume;
     }
 }
debugAudioOutputInfos()
void AudioDeviceManager::debugAudioOutputInfos () const private
Definition at line 773 of file audiodevicemanager.cpp.
References m_audioOutputInfos.
Referenced by deserialize(), and serialize().
 {
     QMap<QString, OutputDeviceInfo>::const_iterator it = m_audioOutputInfos.begin();
     for (; it != m_audioOutputInfos.end(); ++it)
     {
         qDebug() << "AudioDeviceManager::debugAudioOutputInfos:"
                 << " name: " << it.key()
                 << " sampleRate: " << it.value().sampleRate
                 << " udpAddress: " << it.value().udpAddress
                 << " udpPort: " << it.value().udpPort
                 << " copyToUDP: " << it.value().copyToUDP
                 << " udpUseRTP: " << it.value().udpUseRTP
                 << " udpChannelMode: " << (int) it.value().udpChannelMode
                 << " udpChannelCodec: " << (int) it.value().udpChannelCodec
                 << " decimationFactor: " << it.value().udpDecimationFactor;
     }
 }
deserialize()
bool AudioDeviceManager::deserialize (const QByteArray & data) private
Definition at line 205 of file audiodevicemanager.cpp.
References debugAudioInputInfos(), debugAudioOutputInfos(), deserializeInputMap(), deserializeOutputMap(), SimpleDeserializer::getVersion(), SimpleDeserializer::isValid(), SimpleDeserializer::readBlob(), and resetToDefaults().
Referenced by MainSettings::load().
 {
     qDebug("AudioDeviceManager::deserialize");
     SimpleDeserializer d(data);
     if(!d.isValid()) {
         resetToDefaults();
         return false;
     }
     if(d.getVersion() == 1)
     {
         QByteArray data;
         d.readBlob(1, &data);
         deserializeInputMap(data);
         d.readBlob(2, &data);
         deserializeOutputMap(data);
         debugAudioInputInfos();
         debugAudioOutputInfos();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
deserializeInputMap()
void AudioDeviceManager::deserializeInputMap (QByteArray & data) private
Definition at line 237 of file audiodevicemanager.cpp.
References m_audioInputInfos.
Referenced by deserialize().
 {
     QDataStream readStream(&data, QIODevice::ReadOnly);
     readStream >> m_audioInputInfos;
 }
deserializeOutputMap()
void AudioDeviceManager::deserializeOutputMap (QByteArray & data) private
Definition at line 243 of file audiodevicemanager.cpp.
References m_audioOutputInfos.
Referenced by deserialize().
 {
     QDataStream readStream(&data, QIODevice::ReadOnly);
     readStream >> m_audioOutputInfos;
 }
getInputDeviceIndex()
int AudioDeviceManager::getInputDeviceIndex (const QString & deviceName) const
Definition at line 156 of file audiodevicemanager.cpp.
References i, and m_inputDevicesInfo.
Referenced by WFMMod::applySettings(), AMMod::applySettings(), NFMMod::applySettings(), FreeDVMod::applySettings(), SSBMod::applySettings(), FCDProPlusInput::openFCDAudio(), and FCDProInput::openFCDAudio().
 {
     for (int i = 0; i < m_inputDevicesInfo.size(); i++)
     {
         //qDebug("AudioDeviceManager::getInputDeviceIndex: %d: %s|%s", i, qPrintable(deviceName), qPrintable(m_inputDevicesInfo[i].deviceName()));
         if (deviceName == m_inputDevicesInfo[i].deviceName()) {
             return i;
         }
     }
     return -1; // system default
 }
getInputDeviceInfo()
bool AudioDeviceManager::getInputDeviceInfo (const QString & deviceName, InputDeviceInfo & deviceInfo) const
Definition at line 452 of file audiodevicemanager.cpp.
References m_audioInputInfos.
Referenced by AudioDialogX::AudioDialogX(), AudioSelectDialog::getDeviceInfos(), getInputSampleRate(), WebAPIAdapterSrv::instanceAudioGet(), WebAPIAdapterGUI::instanceAudioGet(), WebAPIAdapterGUI::instanceAudioInputDelete(), WebAPIAdapterSrv::instanceAudioInputDelete(), WebAPIAdapterGUI::instanceAudioInputPatch(), WebAPIAdapterSrv::instanceAudioInputPatch(), AudioDialogX::on_audioInTree_currentItemChanged(), setInputDeviceInfo(), and unsetInputDeviceInfo().
 {
     if (m_audioInputInfos.find(deviceName) == m_audioInputInfos.end())
     {
         return false;
     }
     else
     {
         deviceInfo = m_audioInputInfos[deviceName];
         return true;
     }
 }
getInputDeviceName()
bool AudioDeviceManager::getInputDeviceName (int inputDeviceIndex, QString & deviceName) const
Definition at line 122 of file audiodevicemanager.cpp.
References m_defaultDeviceName, and m_inputDevicesInfo.
Referenced by AudioSelectDialog::accept(), getInputSampleRate(), WebAPIAdapterSrv::instanceAudioInputDelete(), WebAPIAdapterGUI::instanceAudioInputDelete(), WebAPIAdapterSrv::instanceAudioInputPatch(), WebAPIAdapterGUI::instanceAudioInputPatch(), setInputDeviceInfo(), startAudioInput(), and unsetInputDeviceInfo().
 {
     if (inputDeviceIndex < 0)
     {
         deviceName = m_defaultDeviceName;
         return true;
     }
     else
     {
         if (inputDeviceIndex < m_inputDevicesInfo.size())
         {
             deviceName = m_inputDevicesInfo[inputDeviceIndex].deviceName();
             return true;
         }
         else
         {
             return false;
         }
     }
 }
getInputDevices()
const QList<QAudioDeviceInfo>& AudioDeviceManager::getInputDevices () const inline
Definition at line 92 of file audiodevicemanager.h.
Referenced by AudioDialogX::AudioDialogX(), AudioSelectDialog::AudioSelectDialog(), WebAPIAdapterGUI::instanceAudioGet(), WebAPIAdapterSrv::instanceAudioGet(), FCDProPlusInput::openFCDAudio(), and FCDProInput::openFCDAudio().
 { return m_inputDevicesInfo; }
getInputSampleRate()
int AudioDeviceManager::getInputSampleRate (int inputDeviceIndex = -1)
Definition at line 478 of file audiodevicemanager.cpp.
References getInputDeviceInfo(), getInputDeviceName(), m_defaultAudioSampleRate, and AudioDeviceManager::InputDeviceInfo::sampleRate.
Referenced by AMMod::AMMod(), WFMMod::applySettings(), AMMod::applySettings(), NFMMod::applySettings(), FreeDVMod::applySettings(), SSBMod::applySettings(), FreeDVMod::FreeDVMod(), NFMMod::NFMMod(), SSBMod::SSBMod(), and WFMMod::WFMMod().
 {
     QString deviceName;
     if (!getInputDeviceName(inputDeviceIndex, deviceName))
     {
         qDebug("AudioDeviceManager::getInputSampleRate: unknown device index %d", inputDeviceIndex);
         return m_defaultAudioSampleRate;
     }
     InputDeviceInfo deviceInfo;
     if (!getInputDeviceInfo(deviceName, deviceInfo))
     {
         qDebug("AudioDeviceManager::getInputSampleRate: unknown device %s", qPrintable(deviceName));
         return m_defaultAudioSampleRate;
     }
     else
     {
         return deviceInfo.sampleRate;
     }
 }
getOutputDeviceIndex()
int AudioDeviceManager::getOutputDeviceIndex (const QString & deviceName) const
Definition at line 143 of file audiodevicemanager.cpp.
References i, and m_outputDevicesInfo.
Referenced by WFMDemod::applySettings(), AMDemod::applySettings(), NFMDemod::applySettings(), DSDDemod::applySettings(), BFMDemod::applySettings(), AMMod::applySettings(), NFMMod::applySettings(), SSBDemod::applySettings(), SSBMod::applySettings(), FreeDVDemod::applySettings(), and DATVDemod::applySettings().
 {
     for (int i = 0; i < m_outputDevicesInfo.size(); i++)
     {
         //qDebug("AudioDeviceManager::getOutputDeviceIndex: %d: %s|%s", i, qPrintable(deviceName), qPrintable(m_outputDevicesInfo[i].deviceName()));
         if (deviceName == m_outputDevicesInfo[i].deviceName()) {
             return i;
         }
     }
     return -1; // system default
 }
getOutputDeviceInfo()
bool AudioDeviceManager::getOutputDeviceInfo (const QString & deviceName, OutputDeviceInfo & deviceInfo) const
Definition at line 465 of file audiodevicemanager.cpp.
References m_audioOutputInfos.
Referenced by AudioDialogX::AudioDialogX(), AudioSelectDialog::getDeviceInfos(), getOutputSampleRate(), WebAPIAdapterSrv::instanceAudioGet(), WebAPIAdapterGUI::instanceAudioGet(), WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterGUI::instanceAudioOutputPatch(), WebAPIAdapterSrv::instanceAudioOutputPatch(), AudioDialogX::on_audioOutTree_currentItemChanged(), setOutputDeviceInfo(), and unsetOutputDeviceInfo().
 {
     if (m_audioOutputInfos.find(deviceName) == m_audioOutputInfos.end())
     {
         return false;
     }
     else
     {
         deviceInfo = m_audioOutputInfos[deviceName];
         return true;
     }
 }
getOutputDeviceName()
bool AudioDeviceManager::getOutputDeviceName (int outputDeviceIndex, QString & deviceName) const
Definition at line 101 of file audiodevicemanager.cpp.
References m_defaultDeviceName, and m_outputDevicesInfo.
Referenced by AudioSelectDialog::accept(), getOutputSampleRate(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputPatch(), WebAPIAdapterGUI::instanceAudioOutputPatch(), setOutputDeviceInfo(), startAudioOutput(), and unsetOutputDeviceInfo().
 {
     if (outputDeviceIndex < 0)
     {
         deviceName = m_defaultDeviceName;
         return true;
     }
     else
     {
         if (outputDeviceIndex < m_outputDevicesInfo.size())
         {
             deviceName = m_outputDevicesInfo[outputDeviceIndex].deviceName();
             return true;
         }
         else
         {
             return false;
         }
     }
 }
getOutputDevices()
const QList<QAudioDeviceInfo>& AudioDeviceManager::getOutputDevices () const inline
Definition at line 93 of file audiodevicemanager.h.
Referenced by AudioDialogX::AudioDialogX(), AudioSelectDialog::AudioSelectDialog(), WebAPIAdapterGUI::instanceAudioGet(), and WebAPIAdapterSrv::instanceAudioGet().
 { return m_outputDevicesInfo; }
getOutputSampleRate()
int AudioDeviceManager::getOutputSampleRate (int outputDeviceIndex = -1)
Definition at line 501 of file audiodevicemanager.cpp.
References getOutputDeviceInfo(), getOutputDeviceName(), m_defaultAudioSampleRate, and AudioDeviceManager::OutputDeviceInfo::sampleRate.
Referenced by AMDemod::AMDemod(), AMMod::AMMod(), WFMDemod::applySettings(), AMDemod::applySettings(), NFMDemod::applySettings(), DSDDemod::applySettings(), BFMDemod::applySettings(), AMMod::applySettings(), NFMMod::applySettings(), SSBDemod::applySettings(), SSBMod::applySettings(), FreeDVDemod::applySettings(), BFMDemod::BFMDemod(), DSDDemod::DSDDemod(), FreeDVDemod::FreeDVDemod(), NFMDemod::NFMDemod(), NFMMod::NFMMod(), SSBDemod::SSBDemod(), SSBMod::SSBMod(), and WFMDemod::WFMDemod().
 {
     QString deviceName;
     if (!getOutputDeviceName(outputDeviceIndex, deviceName))
     {
         qDebug("AudioDeviceManager::getOutputSampleRate: unknown device index %d", outputDeviceIndex);
         return m_defaultAudioSampleRate;
     }
     OutputDeviceInfo deviceInfo;
     if (!getOutputDeviceInfo(deviceName, deviceInfo))
     {
         qDebug("AudioDeviceManager::getOutputSampleRate: unknown device %s", qPrintable(deviceName));
         return m_defaultAudioSampleRate;
     }
     else
     {
         return deviceInfo.sampleRate;
     }
 }
inputInfosCleanup()
void AudioDeviceManager::inputInfosCleanup ()
Remove input info from map for input devices not present.
Definition at line 704 of file audiodevicemanager.cpp.
References m_audioInputInfos, m_defaultDeviceName, and m_inputDevicesInfo.
Referenced by WebAPIAdapterGUI::instanceAudioInputCleanupPatch(), WebAPIAdapterSrv::instanceAudioInputCleanupPatch(), and AudioDialogX::on_inputCleanup_clicked().
 {
     QSet<QString> deviceNames;
     deviceNames.insert(m_defaultDeviceName);
     QList<QAudioDeviceInfo>::const_iterator itd = m_inputDevicesInfo.begin();
     for (; itd != m_inputDevicesInfo.end(); ++itd)
     {
         qDebug("AudioDeviceManager::inputInfosCleanup: device: %s", qPrintable(itd->deviceName()));
         deviceNames.insert(itd->deviceName());
     }
     QMap<QString, InputDeviceInfo>::iterator itm = m_audioInputInfos.begin();
     for (; itm != m_audioInputInfos.end();)
     {
         if (!deviceNames.contains(itm.key()))
         {
             qDebug("AudioDeviceManager::inputInfosCleanup: removing key: %s", qPrintable(itm.key()));
             m_audioInputInfos.erase(itm++);
         }
         else
         {
             ++itm;
         }
     }
 }
outputInfosCleanup()
void AudioDeviceManager::outputInfosCleanup ()
Remove output info from map for output devices not present.
Definition at line 732 of file audiodevicemanager.cpp.
References m_audioOutputInfos, m_defaultDeviceName, and m_outputDevicesInfo.
Referenced by WebAPIAdapterGUI::instanceAudioOutputCleanupPatch(), WebAPIAdapterSrv::instanceAudioOutputCleanupPatch(), and AudioDialogX::on_outputCleanup_clicked().
 {
     QSet<QString> deviceNames;
     deviceNames.insert(m_defaultDeviceName);
     QList<QAudioDeviceInfo>::const_iterator itd = m_outputDevicesInfo.begin();
     for (; itd != m_outputDevicesInfo.end(); ++itd)
     {
         qDebug("AudioDeviceManager::outputInfosCleanup: device: %s", qPrintable(itd->deviceName()));
         deviceNames.insert(itd->deviceName());
     }
     QMap<QString, OutputDeviceInfo>::iterator itm = m_audioOutputInfos.begin();
     for (; itm != m_audioOutputInfos.end();)
     {
         if (!deviceNames.contains(itm.key()))
         {
             qDebug("AudioDeviceManager::outputInfosCleanup: removing key: %s", qPrintable(itm.key()));
             m_audioOutputInfos.erase(itm++);
         }
         else
         {
             ++itm;
         }
     }
 }
removeAudioSink()
void AudioDeviceManager::removeAudioSink (AudioFifo * audioFifo)
Remove the audio sink.
Definition at line 283 of file audiodevicemanager.cpp.
References m_audioFifoToSinkMessageQueues, m_audioOutputs, m_audioSinkFifos, m_outputDeviceSinkMessageQueues, and stopAudioOutput().
Referenced by addAudioSink(), UDPSink::applySettings(), AMDemod::~AMDemod(), AMMod::~AMMod(), BFMDemod::~BFMDemod(), DATVDemod::~DATVDemod(), DSDDemod::~DSDDemod(), FreeDVDemod::~FreeDVDemod(), NFMDemod::~NFMDemod(), NFMMod::~NFMMod(), SSBDemod::~SSBDemod(), SSBMod::~SSBMod(), UDPSink::~UDPSink(), and WFMDemod::~WFMDemod().
 {
     qDebug("AudioDeviceManager::removeAudioSink: %p", audioFifo);
     if (m_audioSinkFifos.find(audioFifo) == m_audioSinkFifos.end())
     {
         qWarning("AudioDeviceManager::removeAudioSink: audio FIFO %p not found", audioFifo);
         return;
     }
     int audioOutputDeviceIndex = m_audioSinkFifos[audioFifo];
     m_audioOutputs[audioOutputDeviceIndex]->removeFifo(audioFifo);
     if (m_audioOutputs[audioOutputDeviceIndex]->getNbFifos() == 0) {
         stopAudioOutput(audioOutputDeviceIndex);
     }
     m_audioSinkFifos.remove(audioFifo); // unregister audio FIFO
     m_outputDeviceSinkMessageQueues[audioOutputDeviceIndex].removeOne(m_audioFifoToSinkMessageQueues[audioFifo]);
     m_audioFifoToSinkMessageQueues.remove(audioFifo);
 }
removeAudioSource()
void AudioDeviceManager::removeAudioSource (AudioFifo * audioFifo)
Remove an audio source.
Definition at line 337 of file audiodevicemanager.cpp.
References m_audioFifoToSourceMessageQueues, m_audioInputs, m_audioSourceFifos, m_inputDeviceSourceMessageQueues, and stopAudioInput().
Referenced by addAudioSource(), AMMod::~AMMod(), FreeDVMod::~FreeDVMod(), NFMMod::~NFMMod(), SSBMod::~SSBMod(), and WFMMod::~WFMMod().
 {
     qDebug("AudioDeviceManager::removeAudioSource: %p", audioFifo);
     if (m_audioSourceFifos.find(audioFifo) == m_audioSourceFifos.end())
     {
         qWarning("AudioDeviceManager::removeAudioSource: audio FIFO %p not found", audioFifo);
         return;
     }
     int audioInputDeviceIndex = m_audioSourceFifos[audioFifo];
     m_audioInputs[audioInputDeviceIndex]->removeFifo(audioFifo);
     if (m_audioInputs[audioInputDeviceIndex]->getNbFifos() == 0) {
         stopAudioInput(audioInputDeviceIndex);
     }
     m_audioSourceFifos.remove(audioFifo); // unregister audio FIFO
     m_inputDeviceSourceMessageQueues[audioInputDeviceIndex].removeOne(m_audioFifoToSourceMessageQueues[audioFifo]);
     m_audioFifoToSourceMessageQueues.remove(audioFifo);
 }
resetToDefaults()
void AudioDeviceManager::resetToDefaults () private
Definition at line 170 of file audiodevicemanager.cpp.
Referenced by deserialize().
 {
 }
serialize()
QByteArray AudioDeviceManager::serialize () const private
Definition at line 174 of file audiodevicemanager.cpp.
References debugAudioInputInfos(), debugAudioOutputInfos(), SimpleSerializer::final(), serializeInputMap(), serializeOutputMap(), and SimpleSerializer::writeBlob().
Referenced by MainSettings::save().
 {
     qDebug("AudioDeviceManager::serialize");
     debugAudioInputInfos();
     debugAudioOutputInfos();
     SimpleSerializer s(1);
     QByteArray data;
     serializeInputMap(data);
     s.writeBlob(1, data);
     serializeOutputMap(data);
     s.writeBlob(2, data);
     return s.final();
 }
serializeInputMap()
void AudioDeviceManager::serializeInputMap (QByteArray & data) const private
Definition at line 191 of file audiodevicemanager.cpp.
References m_audioInputInfos.
Referenced by serialize().
 {
     QDataStream *stream = new QDataStream(&data, QIODevice::WriteOnly);
     *stream << m_audioInputInfos;
     delete stream;
 }
serializeOutputMap()
void AudioDeviceManager::serializeOutputMap (QByteArray & data) const private
Definition at line 198 of file audiodevicemanager.cpp.
References m_audioOutputInfos.
Referenced by serialize().
 {
     QDataStream *stream = new QDataStream(&data, QIODevice::WriteOnly);
     *stream << m_audioOutputInfos;
     delete stream;
 }
setInputDeviceInfo()
void AudioDeviceManager::setInputDeviceInfo (int inputDeviceIndex, const InputDeviceInfo & deviceInfo)
Definition at line 525 of file audiodevicemanager.cpp.
References DSPConfigureAudio::AudioInput, getInputDeviceInfo(), getInputDeviceName(), AudioInput::getRate(), m_audioInputInfos, m_audioInputs, m_inputDeviceSourceMessageQueues, AudioDeviceManager::InputDeviceInfo::sampleRate, AudioInput::setVolume(), AudioInput::start(), AudioInput::stop(), and AudioDeviceManager::InputDeviceInfo::volume.
Referenced by AudioDialogX::accept(), WebAPIAdapterSrv::instanceAudioInputPatch(), and WebAPIAdapterGUI::instanceAudioInputPatch().
 {
     QString deviceName;
     if (!getInputDeviceName(inputDeviceIndex, deviceName))
     {
         qWarning("AudioDeviceManager::setInputDeviceInfo: unknown device index %d", inputDeviceIndex);
         return;
     }
     InputDeviceInfo oldDeviceInfo;
     if (!getInputDeviceInfo(deviceName, oldDeviceInfo))
     {
         qDebug("AudioDeviceManager::setInputDeviceInfo: unknown device %s", qPrintable(deviceName));
     }
     m_audioInputInfos[deviceName] = deviceInfo;
     if (m_audioInputs.find(inputDeviceIndex) == m_audioInputs.end()) { // no FIFO registered yet hence no audio input has been allocated yet
         return;
     }
     AudioInput *audioInput = m_audioInputs[inputDeviceIndex];
     if (oldDeviceInfo.sampleRate != deviceInfo.sampleRate)
     {
         audioInput->stop();
         audioInput->start(inputDeviceIndex, deviceInfo.sampleRate);
         m_audioInputInfos[deviceName].sampleRate = audioInput->getRate(); // store actual sample rate
         // send message to attached channels
         QList<MessageQueue *>::const_iterator it = m_inputDeviceSourceMessageQueues[inputDeviceIndex].begin();
         for (; it != m_inputDeviceSourceMessageQueues[inputDeviceIndex].end(); ++it)
         {
             DSPConfigureAudio *msg = new DSPConfigureAudio(m_audioInputInfos[deviceName].sampleRate, DSPConfigureAudio::AudioInput);
             (*it)->push(msg);
         }
     }
     audioInput->setVolume(deviceInfo.volume);
 }
setOutputDeviceInfo()
void AudioDeviceManager::setOutputDeviceInfo (int outputDeviceIndex, const OutputDeviceInfo & deviceInfo)
Definition at line 569 of file audiodevicemanager.cpp.
References DSPConfigureAudio::AudioOutput, AudioDeviceManager::OutputDeviceInfo::copyToUDP, getOutputDeviceInfo(), getOutputDeviceName(), AudioOutput::getRate(), m_audioOutputInfos, m_audioOutputs, m_outputDeviceSinkMessageQueues, AudioDeviceManager::OutputDeviceInfo::sampleRate, AudioOutput::setUdpChannelFormat(), AudioOutput::setUdpChannelMode(), AudioOutput::setUdpCopyToUDP(), AudioOutput::setUdpDecimation(), AudioOutput::setUdpDestination(), AudioOutput::setUdpUseRTP(), AudioOutput::start(), AudioOutput::stop(), AudioDeviceManager::OutputDeviceInfo::udpAddress, AudioDeviceManager::OutputDeviceInfo::udpChannelCodec, AudioDeviceManager::OutputDeviceInfo::udpChannelMode, AudioOutput::UDPChannelStereo, AudioDeviceManager::OutputDeviceInfo::udpDecimationFactor, AudioDeviceManager::OutputDeviceInfo::udpPort, and AudioDeviceManager::OutputDeviceInfo::udpUseRTP.
Referenced by AudioDialogX::accept(), WebAPIAdapterSrv::instanceAudioOutputPatch(), and WebAPIAdapterGUI::instanceAudioOutputPatch().
 {
     QString deviceName;
     if (!getOutputDeviceName(outputDeviceIndex, deviceName))
     {
         qWarning("AudioDeviceManager::setOutputDeviceInfo: unknown device index %d", outputDeviceIndex);
         return;
     }
     OutputDeviceInfo oldDeviceInfo;
     if (!getOutputDeviceInfo(deviceName, oldDeviceInfo))
     {
         qInfo("AudioDeviceManager::setOutputDeviceInfo: unknown device %s", qPrintable(deviceName));
     }
     m_audioOutputInfos[deviceName] = deviceInfo;
     if (m_audioOutputs.find(outputDeviceIndex) == m_audioOutputs.end())
     {
         qWarning("AudioDeviceManager::setOutputDeviceInfo: index: %d device: %s no FIFO registered yet hence no audio output has been allocated yet",
                 outputDeviceIndex, qPrintable(deviceName));
         return;
     }
     AudioOutput *audioOutput = m_audioOutputs[outputDeviceIndex];
     if (oldDeviceInfo.sampleRate != deviceInfo.sampleRate)
     {
         audioOutput->stop();
         audioOutput->start(outputDeviceIndex, deviceInfo.sampleRate);
         m_audioOutputInfos[deviceName].sampleRate = audioOutput->getRate(); // store actual sample rate
         // send message to attached channels
         QList<MessageQueue *>::const_iterator it = m_outputDeviceSinkMessageQueues[outputDeviceIndex].begin();
         for (; it != m_outputDeviceSinkMessageQueues[outputDeviceIndex].end(); ++it)
         {
             DSPConfigureAudio *msg = new DSPConfigureAudio(m_audioOutputInfos[deviceName].sampleRate, DSPConfigureAudio::AudioOutput);
             (*it)->push(msg);
         }
     }
     audioOutput->setUdpCopyToUDP(deviceInfo.copyToUDP);
     audioOutput->setUdpDestination(deviceInfo.udpAddress, deviceInfo.udpPort);
     audioOutput->setUdpUseRTP(deviceInfo.udpUseRTP);
     audioOutput->setUdpChannelMode(deviceInfo.udpChannelMode);
     audioOutput->setUdpChannelFormat(deviceInfo.udpChannelCodec, deviceInfo.udpChannelMode == AudioOutput::UDPChannelStereo, deviceInfo.sampleRate);
     audioOutput->setUdpDecimation(deviceInfo.udpDecimationFactor);
     qDebug("AudioDeviceManager::setOutputDeviceInfo: index: %d device: %s updated",
             outputDeviceIndex, qPrintable(deviceName));
 }
startAudioInput()
void AudioDeviceManager::startAudioInput (int inputDeviceIndex) private
Definition at line 417 of file audiodevicemanager.cpp.
References getInputDeviceName(), m_audioInputInfos, m_audioInputs, m_defaultAudioInputVolume, and m_defaultAudioSampleRate.
Referenced by addAudioSource(), and unsetInputDeviceInfo().
 {
     unsigned int sampleRate;
     float volume;
     QString deviceName;
     if (getInputDeviceName(inputDeviceIndex, deviceName))
     {
         if (m_audioInputInfos.find(deviceName) == m_audioInputInfos.end())
         {
             sampleRate = m_defaultAudioSampleRate;
             volume = m_defaultAudioInputVolume;
         }
         else
         {
             sampleRate = m_audioInputInfos[deviceName].sampleRate;
             volume = m_audioInputInfos[deviceName].volume;
         }
         m_audioInputs[inputDeviceIndex]->start(inputDeviceIndex, sampleRate);
         m_audioInputs[inputDeviceIndex]->setVolume(volume);
         m_audioInputInfos[deviceName].sampleRate = m_audioInputs[inputDeviceIndex]->getRate();
         m_audioInputInfos[deviceName].volume = volume;
     }
     else
     {
         qWarning("AudioDeviceManager::startAudioInput: unknown device index %d", inputDeviceIndex);
     }
 }
startAudioOutput()
void AudioDeviceManager::startAudioOutput (int outputDeviceIndex) private
Definition at line 359 of file audiodevicemanager.cpp.
References getOutputDeviceName(), m_audioOutputInfos, m_audioOutputs, m_defaultAudioSampleRate, m_defaultUDPAddress, m_defaultUDPPort, AudioOutput::UDPChannelLeft, and AudioOutput::UDPCodecL16.
Referenced by addAudioSink(), and unsetOutputDeviceInfo().
 {
     unsigned int sampleRate;
     QString udpAddress;
     quint16 udpPort;
     bool copyAudioToUDP;
     bool udpUseRTP;
     AudioOutput::UDPChannelMode udpChannelMode;
     AudioOutput::UDPChannelCodec udpChannelCodec;
     uint32_t decimationFactor;
     QString deviceName;
     if (getOutputDeviceName(outputDeviceIndex, deviceName))
     {
         if (m_audioOutputInfos.find(deviceName) == m_audioOutputInfos.end())
         {
             sampleRate = m_defaultAudioSampleRate;
             udpAddress = m_defaultUDPAddress;
             udpPort = m_defaultUDPPort;
             copyAudioToUDP = false;
             udpUseRTP = false;
             udpChannelMode = AudioOutput::UDPChannelLeft;
             udpChannelCodec = AudioOutput::UDPCodecL16;
             decimationFactor = 1;
         }
         else
         {
             sampleRate = m_audioOutputInfos[deviceName].sampleRate;
             udpAddress = m_audioOutputInfos[deviceName].udpAddress;
             udpPort = m_audioOutputInfos[deviceName].udpPort;
             copyAudioToUDP = m_audioOutputInfos[deviceName].copyToUDP;
             udpUseRTP = m_audioOutputInfos[deviceName].udpUseRTP;
             udpChannelMode = m_audioOutputInfos[deviceName].udpChannelMode;
             udpChannelCodec = m_audioOutputInfos[deviceName].udpChannelCodec;
             decimationFactor = m_audioOutputInfos[deviceName].udpDecimationFactor;
         }
         m_audioOutputs[outputDeviceIndex]->start(outputDeviceIndex, sampleRate);
         m_audioOutputInfos[deviceName].sampleRate = m_audioOutputs[outputDeviceIndex]->getRate(); // update with actual rate
         m_audioOutputInfos[deviceName].udpAddress = udpAddress;
         m_audioOutputInfos[deviceName].udpPort = udpPort;
         m_audioOutputInfos[deviceName].copyToUDP = copyAudioToUDP;
         m_audioOutputInfos[deviceName].udpUseRTP = udpUseRTP;
         m_audioOutputInfos[deviceName].udpChannelMode = udpChannelMode;
         m_audioOutputInfos[deviceName].udpChannelCodec = udpChannelCodec;
         m_audioOutputInfos[deviceName].udpDecimationFactor = decimationFactor;
     }
     else
     {
         qWarning("AudioDeviceManager::startAudioOutput: unknown device index %d", outputDeviceIndex);
     }
 }
stopAudioInput()
void AudioDeviceManager::stopAudioInput (int inputDeviceIndex) private
Definition at line 447 of file audiodevicemanager.cpp.
References m_audioInputs.
Referenced by removeAudioSource(), and unsetInputDeviceInfo().
 {
     m_audioInputs[inputDeviceIndex]->stop();
 }
stopAudioOutput()
void AudioDeviceManager::stopAudioOutput (int outputDeviceIndex) private
Definition at line 412 of file audiodevicemanager.cpp.
References m_audioOutputs.
Referenced by removeAudioSink(), and unsetOutputDeviceInfo().
 {
     m_audioOutputs[outputDeviceIndex]->stop();
 }
unsetInputDeviceInfo()
void AudioDeviceManager::unsetInputDeviceInfo (int inputDeviceIndex)
Definition at line 664 of file audiodevicemanager.cpp.
References DSPConfigureAudio::AudioInput, getInputDeviceInfo(), getInputDeviceName(), m_audioInputInfos, m_audioInputs, m_inputDeviceSourceMessageQueues, AudioDeviceManager::InputDeviceInfo::sampleRate, startAudioInput(), and stopAudioInput().
Referenced by AudioDialogX::accept(), WebAPIAdapterGUI::instanceAudioInputDelete(), WebAPIAdapterSrv::instanceAudioInputDelete(), WebAPIAdapterGUI::instanceAudioOutputDelete(), and WebAPIAdapterSrv::instanceAudioOutputDelete().
 {
     QString deviceName;
     if (!getInputDeviceName(inputDeviceIndex, deviceName))
     {
         qWarning("AudioDeviceManager::unsetInputDeviceInfo: unknown device index %d", inputDeviceIndex);
         return;
     }
     InputDeviceInfo oldDeviceInfo;
     if (!getInputDeviceInfo(deviceName, oldDeviceInfo))
     {
         qDebug("AudioDeviceManager::unsetInputDeviceInfo: unregistered device %s", qPrintable(deviceName));
         return;
     }
     m_audioInputInfos.remove(deviceName);
     if (m_audioInputs.find(inputDeviceIndex) == m_audioInputs.end()) { // no FIFO registered yet hence no audio input has been allocated yet
         return;
     }
     stopAudioInput(inputDeviceIndex);
     startAudioInput(inputDeviceIndex);
     if (oldDeviceInfo.sampleRate != m_audioInputInfos[deviceName].sampleRate)
     {
         // send message to attached channels
         QList<MessageQueue *>::const_iterator it = m_inputDeviceSourceMessageQueues[inputDeviceIndex].begin();
         for (; it != m_inputDeviceSourceMessageQueues[inputDeviceIndex].end(); ++it)
         {
             DSPConfigureAudio *msg = new DSPConfigureAudio(m_audioInputInfos[deviceName].sampleRate, DSPConfigureAudio::AudioInput);
             (*it)->push(msg);
         }
     }
 }
unsetOutputDeviceInfo()
void AudioDeviceManager::unsetOutputDeviceInfo (int outputDeviceIndex)
Definition at line 624 of file audiodevicemanager.cpp.
References DSPConfigureAudio::AudioOutput, getOutputDeviceInfo(), getOutputDeviceName(), m_audioOutputInfos, m_audioOutputs, m_outputDeviceSinkMessageQueues, AudioDeviceManager::OutputDeviceInfo::sampleRate, startAudioOutput(), and stopAudioOutput().
Referenced by AudioDialogX::accept().
 {
     QString deviceName;
     if (!getOutputDeviceName(outputDeviceIndex, deviceName))
     {
         qWarning("AudioDeviceManager::unsetOutputDeviceInfo: unknown device index %d", outputDeviceIndex);
         return;
     }
     OutputDeviceInfo oldDeviceInfo;
     if (!getOutputDeviceInfo(deviceName, oldDeviceInfo))
     {
         qDebug("AudioDeviceManager::unsetOutputDeviceInfo: unregistered device %s", qPrintable(deviceName));
         return;
     }
     m_audioOutputInfos.remove(deviceName);
     if (m_audioOutputs.find(outputDeviceIndex) == m_audioOutputs.end()) { // no FIFO registered yet hence no audio output has been allocated yet
         return;
     }
     stopAudioOutput(outputDeviceIndex);
     startAudioOutput(outputDeviceIndex);
     if (oldDeviceInfo.sampleRate != m_audioOutputInfos[deviceName].sampleRate)
     {
         // send message to attached channels
         QList<MessageQueue *>::const_iterator it = m_outputDeviceSinkMessageQueues[outputDeviceIndex].begin();
         for (; it != m_outputDeviceSinkMessageQueues[outputDeviceIndex].end(); ++it)
         {
             DSPConfigureAudio *msg = new DSPConfigureAudio(m_audioOutputInfos[deviceName].sampleRate, DSPConfigureAudio::AudioOutput);
             (*it)->push(msg);
         }
     }
 }
Friends And Related Function Documentation
MainSettings
friend class MainSettings friend
Definition at line 156 of file audiodevicemanager.h.
Member Data Documentation
m_audioFifoToSinkMessageQueues
QMap<AudioFifo*, MessageQueue*> AudioDeviceManager::m_audioFifoToSinkMessageQueues private
audio sink FIFO to attached sink message queue
Definition at line 128 of file audiodevicemanager.h.
Referenced by addAudioSink(), and removeAudioSink().
m_audioFifoToSourceMessageQueues
QMap<AudioFifo*, MessageQueue*> AudioDeviceManager::m_audioFifoToSourceMessageQueues private
audio source FIFO to attached source message queue
Definition at line 134 of file audiodevicemanager.h.
Referenced by addAudioSource(), and removeAudioSource().
m_audioInputInfos
QMap<QString, InputDeviceInfo> AudioDeviceManager::m_audioInputInfos private
audio device name to audio input device info
Definition at line 137 of file audiodevicemanager.h.
Referenced by debugAudioInputInfos(), deserializeInputMap(), getInputDeviceInfo(), inputInfosCleanup(), serializeInputMap(), setInputDeviceInfo(), startAudioInput(), and unsetInputDeviceInfo().
m_audioInputs
QMap<int, AudioInput*> AudioDeviceManager::m_audioInputs private
audio device index to audio input map (index -1 is default device)
Definition at line 136 of file audiodevicemanager.h.
Referenced by addAudioSource(), removeAudioSource(), setInputDeviceInfo(), startAudioInput(), stopAudioInput(), and unsetInputDeviceInfo().
m_audioOutputInfos
QMap<QString, OutputDeviceInfo> AudioDeviceManager::m_audioOutputInfos private
audio device name to audio output info
Definition at line 131 of file audiodevicemanager.h.
Referenced by debugAudioOutputInfos(), deserializeOutputMap(), getOutputDeviceInfo(), outputInfosCleanup(), serializeOutputMap(), setOutputDeviceInfo(), startAudioOutput(), and unsetOutputDeviceInfo().
m_audioOutputs
QMap<int, AudioOutput*> AudioDeviceManager::m_audioOutputs private
audio device index to audio output map (index -1 is default device)
Definition at line 130 of file audiodevicemanager.h.
Referenced by addAudioSink(), removeAudioSink(), setOutputDeviceInfo(), startAudioOutput(), stopAudioOutput(), unsetOutputDeviceInfo(), and ~AudioDeviceManager().
m_audioSinkFifos
QMap<AudioFifo*, int> AudioDeviceManager::m_audioSinkFifos private
Definition at line 127 of file audiodevicemanager.h.
Referenced by addAudioSink(), and removeAudioSink().
m_audioSourceFifos
QMap<AudioFifo*, int> AudioDeviceManager::m_audioSourceFifos private
Definition at line 133 of file audiodevicemanager.h.
Referenced by addAudioSource(), and removeAudioSource().
m_defaultAudioInputVolume
const float AudioDeviceManager::m_defaultAudioInputVolume = 1.0f static
Definition at line 118 of file audiodevicemanager.h.
Referenced by startAudioInput().
m_defaultAudioSampleRate
const unsigned int AudioDeviceManager::m_defaultAudioSampleRate = 48000 static
Definition at line 117 of file audiodevicemanager.h.
Referenced by DSPEngine::getDefaultAudioSampleRate(), AudioSelectDialog::getDeviceInfos(), getInputSampleRate(), getOutputSampleRate(), startAudioInput(), and startAudioOutput().
m_defaultDeviceName
const QString AudioDeviceManager::m_defaultDeviceName = "System default device" static
Definition at line 121 of file audiodevicemanager.h.
Referenced by AudioSelectDialog::accept(), AudioDialogX::AudioDialogX(), AudioSelectDialog::AudioSelectDialog(), WFMDemodSettings::deserialize(), BFMDemodSettings::deserialize(), AMDemodSettings::deserialize(), NFMDemodSettings::deserialize(), SSBDemodSettings::deserialize(), FreeDVDemodSettings::deserialize(), DSDDemodSettings::deserialize(), AMModSettings::deserialize(), WFMModSettings::deserialize(), NFMModSettings::deserialize(), FreeDVModSettings::deserialize(), SSBModSettings::deserialize(), DATVDemodSettings::deserialize(), getInputDeviceName(), getOutputDeviceName(), inputInfosCleanup(), WebAPIAdapterSrv::instanceAudioGet(), WebAPIAdapterGUI::instanceAudioGet(), outputInfosCleanup(), WFMDemodSettings::resetToDefaults(), BFMDemodSettings::resetToDefaults(), AMDemodSettings::resetToDefaults(), SSBDemodSettings::resetToDefaults(), NFMDemodSettings::resetToDefaults(), FreeDVDemodSettings::resetToDefaults(), DSDDemodSettings::resetToDefaults(), AMModSettings::resetToDefaults(), WFMModSettings::resetToDefaults(), NFMModSettings::resetToDefaults(), FreeDVModSettings::resetToDefaults(), SSBModSettings::resetToDefaults(), and DATVDemodSettings::resetToDefaults().
m_defaultUDPAddress
const QString AudioDeviceManager::m_defaultUDPAddress = "127.0.0.1" static
Definition at line 119 of file audiodevicemanager.h.
Referenced by startAudioOutput().
m_defaultUDPPort
const quint16 AudioDeviceManager::m_defaultUDPPort = 9998 static
Definition at line 120 of file audiodevicemanager.h.
Referenced by startAudioOutput().
m_inputDevicesInfo
QList<QAudioDeviceInfo> AudioDeviceManager::m_inputDevicesInfo private
Definition at line 124 of file audiodevicemanager.h.
Referenced by AudioDeviceManager(), getInputDeviceIndex(), getInputDeviceName(), and inputInfosCleanup().
m_inputDeviceSourceMessageQueues
QMap<int, QList<MessageQueue*> > AudioDeviceManager::m_inputDeviceSourceMessageQueues private
sink message queues attached to device
Definition at line 135 of file audiodevicemanager.h.
Referenced by removeAudioSource(), setInputDeviceInfo(), and unsetInputDeviceInfo().
m_outputDevicesInfo
QList<QAudioDeviceInfo> AudioDeviceManager::m_outputDevicesInfo private
Definition at line 125 of file audiodevicemanager.h.
Referenced by AudioDeviceManager(), getOutputDeviceIndex(), getOutputDeviceName(), and outputInfosCleanup().
m_outputDeviceSinkMessageQueues
QMap<int, QList<MessageQueue*> > AudioDeviceManager::m_outputDeviceSinkMessageQueues private
sink message queues attached to device
Definition at line 129 of file audiodevicemanager.h.
Referenced by addAudioSink(), addAudioSource(), removeAudioSink(), setOutputDeviceInfo(), and unsetOutputDeviceInfo().
The documentation for this class was generated from the following files:
sdrbase/audio/audiodevicemanager.h
sdrbase/audio/audiodevicemanager.cpp