SDRAngel: Bladerf1OutputThread Class Reference
Bladerf1OutputThread Class Reference
#include <bladerf1outputthread.h>
Inherits QThread.
Public Member Functions
Bladerf1OutputThread (struct bladerf *dev, SampleSourceFifo *sampleFifo, QObject *parent=NULL)
~Bladerf1OutputThread ()
void startWork ()
void stopWork ()
void setLog2Interpolation (unsigned int log2_interp)
bool isRunning () const
Private Member Functions
void run ()
void callback (qint16 *buf, qint32 len)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
struct bladerf * m_dev
qint16 m_buf [2 *BLADERFOUTPUT_BLOCKSIZE]
SampleSourceFifo * m_sampleFifo
unsigned int m_log2Interp
Interpolators< qint16, SDR_TX_SAMP_SZ, 12 > m_interpolators
Detailed Description
Definition at line 30 of file bladerf1outputthread.h.
Constructor & Destructor Documentation
Bladerf1OutputThread()
Bladerf1OutputThread::Bladerf1OutputThread (struct bladerf * dev, SampleSourceFifo * sampleFifo, QObject * parent = NULL)
Definition at line 26 of file bladerf1outputthread.cpp.
References BLADERFOUTPUT_BLOCKSIZE, and m_buf.
                                                                                                              :
     QThread(parent),
     m_running(false),
     m_dev(dev),
     m_sampleFifo(sampleFifo),
     m_log2Interp(0)
 {
     std::fill(m_buf, m_buf + 2*BLADERFOUTPUT_BLOCKSIZE, 0);
 }
~Bladerf1OutputThread()
Bladerf1OutputThread::~Bladerf1OutputThread ()
Definition at line 36 of file bladerf1outputthread.cpp.
References stopWork().
 {
     stopWork();
 }
Member Function Documentation
callback()
void Bladerf1OutputThread::callback (qint16 * buf, qint32 len) private
Definition at line 83 of file bladerf1outputthread.cpp.
References Interpolators< T, SdrBits, OutputBits >::interpolate1(), Interpolators< T, SdrBits, OutputBits >::interpolate16_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate2_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate32_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate4_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate64_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate8_cen(), m_interpolators, m_log2Interp, m_sampleFifo, and SampleSourceFifo::readAdvance().
Referenced by run().
 {
     SampleVector::iterator beginRead;
     m_sampleFifo->readAdvance(beginRead, len/(1<<m_log2Interp));
     beginRead -= len;
     if (m_log2Interp == 0)
     {
         m_interpolators.interpolate1(&beginRead, buf, len*2);
     }
     else
     {
         switch (m_log2Interp)
         {
         case 1:
             m_interpolators.interpolate2_cen(&beginRead, buf, len*2, true);
             break;
         case 2:
             m_interpolators.interpolate4_cen(&beginRead, buf, len*2, true);
             break;
         case 3:
             m_interpolators.interpolate8_cen(&beginRead, buf, len*2, true);
             break;
         case 4:
             m_interpolators.interpolate16_cen(&beginRead, buf, len*2, true);
             break;
         case 5:
             m_interpolators.interpolate32_cen(&beginRead, buf, len*2, true);
             break;
         case 6:
             m_interpolators.interpolate64_cen(&beginRead, buf, len*2, true);
             break;
         default:
             break;
         }
     }
 }
isRunning()
bool Bladerf1OutputThread::isRunning () const inline
Definition at line 40 of file bladerf1outputthread.h.
References m_running.
Referenced by Bladerf1Output::applySettings().
 { return m_running; }
run()
void Bladerf1OutputThread::run () private
Definition at line 61 of file bladerf1outputthread.cpp.
References BLADERFOUTPUT_BLOCKSIZE, callback(), m_buf, m_dev, m_running, and m_startWaiter.
 {
     int res;
     m_running = true;
     m_startWaiter.wakeAll();
     while (m_running)
     {
         callback(m_buf, BLADERFOUTPUT_BLOCKSIZE);
         if((res = bladerf_sync_tx(m_dev, m_buf, BLADERFOUTPUT_BLOCKSIZE, NULL, 10000)) < 0)
         {
             qCritical("BladerdOutputThread:run: sync error: %s", strerror(errno));
             break;
         }
     }
     m_running = false;
 }
setLog2Interpolation()
void Bladerf1OutputThread::setLog2Interpolation (unsigned int log2_interp)
Definition at line 56 of file bladerf1outputthread.cpp.
References m_log2Interp.
Referenced by Bladerf1Output::applySettings(), and Bladerf1Output::start().
 {
     m_log2Interp = log2_interp;
 }
startWork()
void Bladerf1OutputThread::startWork ()
Definition at line 41 of file bladerf1outputthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by Bladerf1Output::applySettings(), and Bladerf1Output::start().
 {
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void Bladerf1OutputThread::stopWork ()
Definition at line 50 of file bladerf1outputthread.cpp.
References m_running.
Referenced by Bladerf1Output::applySettings(), Bladerf1Output::stop(), and ~Bladerf1OutputThread().
 {
     m_running = false;
     wait();
 }
Member Data Documentation
m_buf
qint16 Bladerf1OutputThread::m_buf[2 *BLADERFOUTPUT_BLOCKSIZE] private
Definition at line 48 of file bladerf1outputthread.h.
Referenced by Bladerf1OutputThread(), and run().
m_dev
struct bladerf* Bladerf1OutputThread::m_dev private
Definition at line 47 of file bladerf1outputthread.h.
Referenced by run().
m_interpolators
Interpolators<qint16, SDR_TX_SAMP_SZ, 12> Bladerf1OutputThread::m_interpolators private
Definition at line 53 of file bladerf1outputthread.h.
Referenced by callback().
m_log2Interp
unsigned int Bladerf1OutputThread::m_log2Interp private
Definition at line 51 of file bladerf1outputthread.h.
Referenced by callback(), and setLog2Interpolation().
m_running
bool Bladerf1OutputThread::m_running private
Definition at line 45 of file bladerf1outputthread.h.
Referenced by isRunning(), run(), startWork(), and stopWork().
m_sampleFifo
SampleSourceFifo* Bladerf1OutputThread::m_sampleFifo private
Definition at line 49 of file bladerf1outputthread.h.
Referenced by callback().
m_startWaiter
QWaitCondition Bladerf1OutputThread::m_startWaiter private
Definition at line 44 of file bladerf1outputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex Bladerf1OutputThread::m_startWaitMutex private
Definition at line 43 of file bladerf1outputthread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/samplesink/bladerf1output/bladerf1outputthread.h
plugins/samplesink/bladerf1output/bladerf1outputthread.cpp