SDRAngel: FreeDVMod Class Reference
FreeDVMod Class Reference
#include <freedvmod.h>
Classes
class MsgConfigureChannelizer
class MsgConfigureFileSourceName
class MsgConfigureFileSourceSeek
class MsgConfigureFileSourceStreamTiming
class MsgConfigureFreeDVMod
class MsgReportFileSourceStreamData
class MsgReportFileSourceStreamTiming
Signals
void levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples)
Public Member Functions
FreeDVMod (DeviceAPI *deviceAPI)
~FreeDVMod ()
virtual void destroy ()
void setSpectrumSampleSink (BasebandSampleSink *sampleSink)
virtual void pull (Sample &sample)
virtual void pullAudio (int nbSamples)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
uint32_t getAudioSampleRate () const
uint32_t getModemSampleRate () const
double getMagSq () const
Real getLowCutoff () const
Real getHiCutoff () const
CWKeyer * getCWKeyer ()
Public Member Functions inherited from BasebandSampleSource
BasebandSampleSource ()
virtual ~BasebandSampleSource ()
void feed (SampleSourceFifo *sampleFifo, int nbSamples)
SampleSourceFifo & getSampleSourceFifo ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
void setDeviceSampleSourceFifo (SampleSourceFifo *deviceSampleFifo)
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channeltx.freedvmod"
static const QString m_channelId = "FreeDVMod"
Private Types
enum RateState { RSInitialFill, RSRunning }
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applyAudioSampleRate (int sampleRate)
void applyChannelSettings (int basebandSampleRate, int outputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const FreeDVModSettings &settings, bool force=false)
void applyFreeDVMode (FreeDVModSettings::FreeDVMode mode)
void pullAF (Complex &sample)
void calculateLevel (Complex &sample)
void calculateLevel (qint16 &sample)
void modulateSample ()
void openFileStream ()
void seekFileStream (int seekPercentage)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const FreeDVModSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const FreeDVModSettings &settings, bool force)
void webapiReverseSendCWSettings (const CWKeyerSettings &settings)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSource * m_threadedChannelizer
UpChannelizer * m_channelizer
int m_basebandSampleRate
int m_outputSampleRate
int m_modemSampleRate
int m_inputFrequencyOffset
Real m_lowCutoff
Real m_hiCutoff
FreeDVModSettings m_settings
NCOF m_carrierNco
NCOF m_toneNco
Complex m_modSample
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
bool m_interpolatorConsumed
fftfilt * m_SSBFilter
Complex * m_SSBFilterBuffer
int m_SSBFilterBufferIndex
BasebandSampleSink * m_sampleSink
SampleVector m_sampleBuffer
fftfilt::cmplx m_sum
int m_undersampleCount
int m_sumCount
double m_magsq
MovingAverageUtil< double, double, 16 > m_movingAverage
quint32 m_audioSampleRate
AudioVector m_audioBuffer
uint m_audioBufferFill
AudioFifo m_audioFifo
QMutex m_settingsMutex
std::ifstream m_ifstream
QString m_fileName
quint64 m_fileSize
raw file size (bytes)
quint32 m_recordLength
record length in seconds computed from file size
int m_inputSampleRate
speech (input) sample rate (fixed 8000 S/s)
quint32 m_levelCalcCount
Real m_peakLevel
Real m_levelSum
CWKeyer m_cwKeyer
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
struct freedv * m_freeDV
int m_nSpeechSamples
int m_nNomModemSamples
int m_iSpeech
int m_iModem
int16_t * m_speechIn
int16_t * m_modOut
float m_scaleFactor
divide by this amount to scale from int16 to float in [-1.0, 1.0] interval
AudioResampler m_audioResampler
Static Private Attributes
static const int m_ssbFftLen = 1024
static const int m_levelNbSamples = 80
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSource
void handleInputMessages ()
void handleWriteToFifo (int nbSamples)
void handleWriteToDeviceFifo (int nbSamples)
Protected Member Functions inherited from BasebandSampleSource
void handleWriteToFifo (SampleSourceFifo *sampleFifo, int nbSamples)
Protected Attributes inherited from BasebandSampleSource
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
SampleSourceFifo m_sampleFifo
Internal FIFO for multi-channel processing.
SampleSourceFifo * m_deviceSampleFifo
Reference to the device FIFO for single channel processing.
Detailed Description
Definition at line 51 of file freedvmod.h.
Member Enumeration Documentation
RateState
enum FreeDVMod::RateState private
Enumerator
RSInitialFill
RSRunning
Definition at line 273 of file freedvmod.h.
                    {
         RSInitialFill,
         RSRunning
     };
Constructor & Destructor Documentation
FreeDVMod()
FreeDVMod::FreeDVMod (DeviceAPI * deviceAPI)
Definition at line 57 of file freedvmod.cpp.
References AudioDeviceManager::addAudioSource(), DeviceAPI::addChannelSource(), DeviceAPI::addChannelSourceAPI(), applyChannelSettings(), applySettings(), DSPEngine::getAudioDeviceManager(), BasebandSampleSource::getInputMessageQueue(), AudioDeviceManager::getInputSampleRate(), DSPEngine::instance(), m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_basebandSampleRate, m_channelId, m_channelizer, m_cwKeyer, m_deviceAPI, m_hiCutoff, m_inputFrequencyOffset, m_inputSampleRate, m_lowCutoff, m_magsq, m_networkManager, m_outputSampleRate, m_settings, m_ssbFftLen, m_SSBFilter, m_SSBFilterBuffer, m_sum, m_sumCount, m_threadedChannelizer, m_toneNco, m_undersampleCount, networkManagerFinished(), CWKeyer::reset(), NCOF::setFreq(), and CWKeyer::setSampleRate().
Referenced by FreeDVMod::MsgReportFileSourceStreamData::MsgReportFileSourceStreamData().
                                          :
     ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSource),
     m_deviceAPI(deviceAPI),
     m_basebandSampleRate(48000),
     m_outputSampleRate(48000),
     m_modemSampleRate(48000), // // default 2400A mode
     m_inputFrequencyOffset(0),
     m_lowCutoff(0.0),
     m_hiCutoff(6000.0),
     m_SSBFilter(0),
     m_SSBFilterBuffer(0),
     m_SSBFilterBufferIndex(0),
     m_sampleSink(0),
     m_audioFifo(4800),
     m_settingsMutex(QMutex::Recursive),
     m_fileSize(0),
     m_recordLength(0),
     m_inputSampleRate(8000), // all modes take 8000 S/s input
     m_levelCalcCount(0),
     m_peakLevel(0.0f),
     m_levelSum(0.0f),
     m_freeDV(0),
     m_nSpeechSamples(0),
     m_nNomModemSamples(0),
     m_iSpeech(0),
     m_iModem(0),
     m_speechIn(0),
     m_modOut(0),
     m_scaleFactor(SDR_TX_SCALEF)
 {
     setObjectName(m_channelId);
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSource(&m_audioFifo, getInputMessageQueue());
     m_audioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getInputSampleRate();
     m_SSBFilter = new fftfilt(m_lowCutoff / m_audioSampleRate, m_hiCutoff / m_audioSampleRate, m_ssbFftLen);
     m_SSBFilterBuffer = new Complex[m_ssbFftLen>>1]; // filter returns data exactly half of its size
     std::fill(m_SSBFilterBuffer, m_SSBFilterBuffer+(m_ssbFftLen>>1), Complex{0,0});
     m_audioBuffer.resize(1<<14);
     m_audioBufferFill = 0;
     m_sum.real(0.0f);
     m_sum.imag(0.0f);
     m_undersampleCount = 0;
     m_sumCount = 0;
     m_magsq = 0.0;
     m_toneNco.setFreq(1000.0, m_inputSampleRate);
     m_cwKeyer.setSampleRate(m_inputSampleRate);
     m_cwKeyer.reset();
     m_channelizer = new UpChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSource(m_channelizer, this);
     m_deviceAPI->addChannelSource(m_threadedChannelizer);
     m_deviceAPI->addChannelSourceAPI(this);
     applySettings(m_settings, true);
     applyChannelSettings(m_basebandSampleRate, m_outputSampleRate, m_inputFrequencyOffset, true);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~FreeDVMod()
FreeDVMod::~FreeDVMod ()
Definition at line 122 of file freedvmod.cpp.
References DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo, m_channelizer, m_deviceAPI, m_freeDV, m_networkManager, m_SSBFilter, m_SSBFilterBuffer, m_threadedChannelizer, networkManagerFinished(), AudioDeviceManager::removeAudioSource(), DeviceAPI::removeChannelSource(), and DeviceAPI::removeChannelSourceAPI().
Referenced by FreeDVMod::MsgReportFileSourceStreamData::MsgReportFileSourceStreamData().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSource(&m_audioFifo);
     m_deviceAPI->removeChannelSourceAPI(this);
     m_deviceAPI->removeChannelSource(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete m_SSBFilter;
     delete[] m_SSBFilterBuffer;
     if (m_freeDV) {
         freedv_close(m_freeDV);
     }
 }
Member Function Documentation
applyAudioSampleRate()
void FreeDVMod::applyAudioSampleRate (int sampleRate) private
Definition at line 567 of file freedvmod.cpp.
References m_audioResampler, m_audioSampleRate, m_inputSampleRate, m_settingsMutex, AudioResampler::setAudioFilters(), and AudioResampler::setDecimation().
Referenced by applySettings(), and handleMessage().
 {
     qDebug("FreeDVMod::applyAudioSampleRate: %d", sampleRate);
     // TODO: put up simple IIR interpolator when sampleRate < m_modemSampleRate
     m_settingsMutex.lock();
     m_audioResampler.setDecimation(sampleRate / m_inputSampleRate);
     m_audioResampler.setAudioFilters(sampleRate, sampleRate, 250, 3300);
     m_settingsMutex.unlock();
     m_audioSampleRate = sampleRate;
 }
applyChannelSettings()
void FreeDVMod::applyChannelSettings (int basebandSampleRate, int outputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 580 of file freedvmod.cpp.
References Interpolator::create(), m_basebandSampleRate, m_carrierNco, m_hiCutoff, m_inputFrequencyOffset, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, m_modemSampleRate, m_outputSampleRate, m_settingsMutex, and NCOF::setFreq().
Referenced by FreeDVMod(), handleMessage(), and start().
 {
     qDebug() << "FreeDVMod::applyChannelSettings:"
             << " basebandSampleRate: " << basebandSampleRate
             << " outputSampleRate: " << outputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if ((inputFrequencyOffset != m_inputFrequencyOffset) ||
         (outputSampleRate != m_outputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_carrierNco.setFreq(inputFrequencyOffset, outputSampleRate);
         m_settingsMutex.unlock();
     }
     if ((outputSampleRate != m_outputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_interpolatorDistanceRemain = 0;
         m_interpolatorConsumed = false;
         m_interpolatorDistance = (Real) m_modemSampleRate / (Real) outputSampleRate;
         m_interpolator.create(48, m_modemSampleRate, m_hiCutoff, 3.0);
         m_settingsMutex.unlock();
     }
     m_basebandSampleRate = basebandSampleRate;
     m_outputSampleRate = outputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applyFreeDVMode()
void FreeDVMod::applyFreeDVMode (FreeDVModSettings::FreeDVMode mode) private
Definition at line 610 of file freedvmod.cpp.
References DSPConfigureAudio::AudioInput, Interpolator::create(), FreeDVMod::MsgConfigureChannelizer::create(), fftfilt::create_filter(), FreeDVModSettings::FreeDVMode1600, FreeDVModSettings::FreeDVMode2400A, FreeDVModSettings::FreeDVMode700C, FreeDVModSettings::FreeDVMode700D, FreeDVModSettings::FreeDVMode800XA, FreeDVModSettings::getHiCutoff(), FreeDVModSettings::getLowCutoff(), BasebandSampleSource::getMessageQueueToGUI(), FreeDVModSettings::getModSampleRate(), m_freeDV, m_hiCutoff, m_iModem, FreeDVModSettings::m_inputFrequencyOffset, BasebandSampleSource::m_inputMessageQueue, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, m_iSpeech, m_lowCutoff, m_modemSampleRate, m_modOut, m_nNomModemSamples, m_nSpeechSamples, m_outputSampleRate, m_scaleFactor, m_settings, m_settingsMutex, m_speechIn, m_SSBFilter, MessageQueue::push(), and SDR_TX_SCALEF.
Referenced by applySettings().
 {
     m_hiCutoff = FreeDVModSettings::getHiCutoff(mode);
     m_lowCutoff = FreeDVModSettings::getLowCutoff(mode);
     int modemSampleRate = FreeDVModSettings::getModSampleRate(mode);
     m_settingsMutex.lock();
     m_SSBFilter->create_filter(m_lowCutoff / modemSampleRate, m_hiCutoff / modemSampleRate);
     // baseband interpolator and filter
     if (modemSampleRate != m_modemSampleRate)
     {
         MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
                 modemSampleRate, m_settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(channelConfigMsg);
         m_interpolatorDistanceRemain = 0;
         m_interpolatorConsumed = false;
         m_interpolatorDistance = (Real) modemSampleRate / (Real) m_outputSampleRate;
         m_interpolator.create(48, modemSampleRate, m_hiCutoff, 3.0);
         m_modemSampleRate = modemSampleRate;
         if (getMessageQueueToGUI())
         {
             DSPConfigureAudio *cfg = new DSPConfigureAudio(m_modemSampleRate, DSPConfigureAudio::AudioInput);
             getMessageQueueToGUI()->push(cfg);
         }
     }
     // FreeDV object
     if (m_freeDV) {
         freedv_close(m_freeDV);
     }
     int fdv_mode = -1;
     switch(mode)
     {
     case FreeDVModSettings::FreeDVMode700C:
         fdv_mode = FREEDV_MODE_700C;
         m_scaleFactor = SDR_TX_SCALEF / 3.2f;
         break;
     case FreeDVModSettings::FreeDVMode700D:
         fdv_mode = FREEDV_MODE_700D;
         m_scaleFactor = SDR_TX_SCALEF / 3.2f;
         break;
     case FreeDVModSettings::FreeDVMode800XA:
         fdv_mode = FREEDV_MODE_800XA;
         m_scaleFactor = SDR_TX_SCALEF / 8.2f;
         break;
     case FreeDVModSettings::FreeDVMode1600:
         fdv_mode = FREEDV_MODE_1600;
         m_scaleFactor = SDR_TX_SCALEF / 3.2f;
         break;
     case FreeDVModSettings::FreeDVMode2400A:
     default:
         fdv_mode = FREEDV_MODE_2400A;
         m_scaleFactor = SDR_TX_SCALEF / 8.2f;
         break;
     }
     if (fdv_mode == FREEDV_MODE_700D)
     {
         struct freedv_advanced adv;
         adv.interleave_frames = 1;
         m_freeDV = freedv_open_advanced(fdv_mode, &adv);
     }
     else
     {
         m_freeDV = freedv_open(fdv_mode);
     }
     if (m_freeDV)
     {
         freedv_set_test_frames(m_freeDV, 0);
         freedv_set_snr_squelch_thresh(m_freeDV, -100.0);
         freedv_set_squelch_en(m_freeDV, 1);
         freedv_set_clip(m_freeDV, 0);
         freedv_set_tx_bpf(m_freeDV, 1);
         freedv_set_ext_vco(m_freeDV, 0);
         freedv_set_callback_txt(m_freeDV, nullptr, nullptr, nullptr);
         freedv_set_callback_protocol(m_freeDV, nullptr, nullptr, nullptr);
         freedv_set_callback_data(m_freeDV, nullptr, nullptr, nullptr);
         int nSpeechSamples = freedv_get_n_speech_samples(m_freeDV);
         int nNomModemSamples = freedv_get_n_nom_modem_samples(m_freeDV);
         int Fs = freedv_get_modem_sample_rate(m_freeDV);
         int Rs = freedv_get_modem_symbol_rate(m_freeDV);
         if (nSpeechSamples != m_nSpeechSamples)
         {
             if (m_speechIn) {
                 delete[] m_speechIn;
             }
             m_speechIn = new int16_t[nSpeechSamples];
             m_nSpeechSamples = nSpeechSamples;
         }
         if (nNomModemSamples != m_nNomModemSamples)
         {
             if (m_modOut) {
                 delete[] m_modOut;
             }
             m_modOut = new int16_t[nNomModemSamples];
             m_nNomModemSamples = nNomModemSamples;
         }
         m_iSpeech = 0;
         m_iModem = 0;
         qDebug() << "FreeDVMod::applyFreeDVMode:"
                 << " fdv_mode: " << fdv_mode
                 << " m_modemSampleRate: " << m_modemSampleRate
                 << " m_lowCutoff: " << m_lowCutoff
                 << " m_hiCutoff: " << m_hiCutoff
                 << " Fs: " << Fs
                 << " Rs: " << Rs
                 << " m_nSpeechSamples: " << m_nSpeechSamples
                 << " m_nNomModemSamples: " << m_nNomModemSamples;
     }
     m_settingsMutex.unlock();
 }
applySettings()
void FreeDVMod::applySettings (const FreeDVModSettings & settings, bool force = false) private
Definition at line 738 of file freedvmod.cpp.
References AudioDeviceManager::addAudioSource(), applyAudioSampleRate(), applyFreeDVMode(), DSPEngine::getAudioDeviceManager(), AudioDeviceManager::getInputDeviceIndex(), BasebandSampleSource::getInputMessageQueue(), AudioDeviceManager::getInputSampleRate(), DSPEngine::instance(), FreeDVModSettings::m_audioDeviceName, m_audioFifo, FreeDVModSettings::m_audioMute, m_audioSampleRate, FreeDVModSettings::m_freeDVMode, FreeDVModSettings::m_gaugeInputElseModem, FreeDVModSettings::m_inputFrequencyOffset, m_inputSampleRate, FreeDVModSettings::m_modAFInput, FreeDVModSettings::m_playLoop, FreeDVModSettings::m_reverseAPIAddress, FreeDVModSettings::m_reverseAPIChannelIndex, FreeDVModSettings::m_reverseAPIDeviceIndex, FreeDVModSettings::m_reverseAPIPort, FreeDVModSettings::m_rgbColor, m_settings, m_settingsMutex, FreeDVModSettings::m_spanLog2, FreeDVModSettings::m_title, FreeDVModSettings::m_toneFrequency, m_toneNco, FreeDVModSettings::m_useReverseAPI, FreeDVModSettings::m_volumeFactor, NCOF::setFreq(), and webapiReverseSendSettings().
Referenced by FreeDVMod(), and handleMessage().
 {
     QList<QString> reverseAPIKeys;
     if ((settings.m_inputFrequencyOffset != m_settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if ((settings.m_toneFrequency != m_settings.m_toneFrequency) || force) {
         reverseAPIKeys.append("toneFrequency");
     }
     if ((settings.m_volumeFactor != m_settings.m_volumeFactor) || force) {
         reverseAPIKeys.append("volumeFactor");
     }
     if ((settings.m_spanLog2 != m_settings.m_spanLog2) || force) {
         reverseAPIKeys.append("spanLog2");
     }
     if ((settings.m_audioMute != m_settings.m_audioMute) || force) {
         reverseAPIKeys.append("audioMute");
     }
     if ((settings.m_playLoop != m_settings.m_playLoop) || force) {
         reverseAPIKeys.append("playLoop");
     }
     if ((settings.m_playLoop != m_settings.m_gaugeInputElseModem) || force) {
         reverseAPIKeys.append("gaugeInputElseModem");
     }
     if ((settings.m_rgbColor != m_settings.m_rgbColor) || force) {
         reverseAPIKeys.append("rgbColor");
     }
     if ((settings.m_title != m_settings.m_title) || force) {
         reverseAPIKeys.append("title");
     }
     if ((settings.m_freeDVMode != m_settings.m_freeDVMode) || force) {
         reverseAPIKeys.append("freeDVMode");
     }
     if ((settings.m_modAFInput != m_settings.m_modAFInput) || force) {
         reverseAPIKeys.append("modAFInput");
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force) {
         reverseAPIKeys.append("audioDeviceName");
     }
     if ((settings.m_toneFrequency != m_settings.m_toneFrequency) || force)
     {
         m_settingsMutex.lock();
         m_toneNco.setFreq(settings.m_toneFrequency, m_inputSampleRate);
         m_settingsMutex.unlock();
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force)
     {
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getInputDeviceIndex(settings.m_audioDeviceName);
         audioDeviceManager->addAudioSource(&m_audioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getInputSampleRate(audioDeviceIndex);
         if (m_audioSampleRate != audioSampleRate) {
             applyAudioSampleRate(audioSampleRate);
         }
     }
     if ((m_settings.m_freeDVMode != settings.m_freeDVMode) || force) {
         applyFreeDVMode(settings.m_freeDVMode);
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
calculateLevel() [1/2]
void FreeDVMod::calculateLevel (Complex & sample) private
Definition at line 375 of file freedvmod.cpp.
References levelChanged(), m_levelCalcCount, m_levelNbSamples, m_levelSum, m_peakLevel, leansdr::max(), and sqrt().
Referenced by modulateSample(), and pullAF().
 {
     Real t = sample.real(); // TODO: possibly adjust depending on sample type
     if (m_levelCalcCount < m_levelNbSamples)
     {
         m_peakLevel = std::max(std::fabs(m_peakLevel), t);
         m_levelSum += t * t;
         m_levelCalcCount++;
     }
     else
     {
         qreal rmsLevel = sqrt(m_levelSum / m_levelNbSamples);
         //qDebug("NFMMod::calculateLevel: %f %f", rmsLevel, m_peakLevel);
         emit levelChanged(rmsLevel, m_peakLevel, m_levelNbSamples);
         m_peakLevel = 0.0f;
         m_levelSum = 0.0f;
         m_levelCalcCount = 0;
     }
 }
calculateLevel() [2/2]
void FreeDVMod::calculateLevel (qint16 & sample) private
Definition at line 396 of file freedvmod.cpp.
References levelChanged(), m_levelCalcCount, m_levelNbSamples, m_levelSum, m_peakLevel, leansdr::max(), SDR_TX_SCALEF, and sqrt().
 {
     Real t = sample / SDR_TX_SCALEF;
     if (m_levelCalcCount < m_levelNbSamples)
     {
         m_peakLevel = std::max(std::fabs(m_peakLevel), t);
         m_levelSum += t * t;
         m_levelCalcCount++;
     }
     else
     {
         qreal rmsLevel = sqrt(m_levelSum / m_levelNbSamples);
         //qDebug("FreeDVMod::calculateLevel: %f %f", rmsLevel, m_peakLevel);
         emit levelChanged(rmsLevel, m_peakLevel, m_levelNbSamples);
         m_peakLevel = 0.0f;
         m_levelSum = 0.0f;
         m_levelCalcCount = 0;
     }
 }
deserialize()
bool FreeDVMod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 820 of file freedvmod.cpp.
References FreeDVMod::MsgConfigureFreeDVMod::create(), FreeDVModSettings::deserialize(), BasebandSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and FreeDVModSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureFreeDVMod *msg = MsgConfigureFreeDVMod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureFreeDVMod *msg = MsgConfigureFreeDVMod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void FreeDVMod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 210 of file freedvmod.h.
 { delete this; }
getAudioSampleRate()
uint32_t FreeDVMod::getAudioSampleRate () const inline
Definition at line 251 of file freedvmod.h.
References m_audioSampleRate.
 { return m_audioSampleRate; }
getCenterFrequency()
virtual qint64 FreeDVMod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 222 of file freedvmod.h.
References deserialize(), FreeDVModSettings::m_inputFrequencyOffset, FreeDVMod::MsgConfigureFreeDVMod::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getCWKeyer()
CWKeyer* FreeDVMod::getCWKeyer () inline
Definition at line 257 of file freedvmod.h.
References m_cwKeyer.
Referenced by FreeDVModGUI::FreeDVModGUI().
 { return &m_cwKeyer; }
getHiCutoff()
Real FreeDVMod::getHiCutoff () const inline
Definition at line 255 of file freedvmod.h.
References m_hiCutoff.
 { return m_hiCutoff; }
getIdentifier()
virtual void FreeDVMod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 220 of file freedvmod.h.
 { id = objectName(); }
getLowCutoff()
Real FreeDVMod::getLowCutoff () const inline
Definition at line 254 of file freedvmod.h.
References m_lowCutoff.
 { return m_lowCutoff; }
getMagSq()
double FreeDVMod::getMagSq () const inline
Definition at line 253 of file freedvmod.h.
References m_magsq.
Referenced by FreeDVModGUI::tick(), and webapiFormatChannelReport().
 { return m_magsq; }
getModemSampleRate()
uint32_t FreeDVMod::getModemSampleRate () const inline
Definition at line 252 of file freedvmod.h.
References m_modemSampleRate.
Referenced by FreeDVModGUI::displayBandwidths(), and FreeDVModGUI::handleMessage().
 { return m_modemSampleRate; }
getNbSinkStreams()
virtual int FreeDVMod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 227 of file freedvmod.h.
 { return 1; }
getNbSourceStreams()
virtual int FreeDVMod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 228 of file freedvmod.h.
 { return 0; }
getStreamCenterFrequency()
virtual qint64 FreeDVMod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 230 of file freedvmod.h.
References FreeDVModSettings::m_inputFrequencyOffset, FreeDVMod::MsgConfigureFreeDVMod::m_settings, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void FreeDVMod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 221 of file freedvmod.h.
References FreeDVMod::MsgConfigureFreeDVMod::m_settings, and FreeDVModSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool FreeDVMod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSource.
Definition at line 430 of file freedvmod.cpp.
References applyAudioSampleRate(), applyChannelSettings(), applySettings(), UpChannelizer::configure(), FreeDVMod::MsgReportFileSourceStreamTiming::create(), UpChannelizer::MsgChannelizerNotification::getBasebandSampleRate(), FreeDVMod::MsgConfigureChannelizer::getCenterFrequency(), FreeDVMod::MsgConfigureFileSourceName::getFileName(), FreeDVMod::MsgConfigureFreeDVMod::getForce(), UpChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSource::getInputMessageQueue(), BasebandSampleSource::getMessageQueueToGUI(), FreeDVMod::MsgConfigureFileSourceSeek::getPercentage(), UpChannelizer::MsgChannelizerNotification::getSampleRate(), FreeDVMod::MsgConfigureChannelizer::getSampleRate(), DSPConfigureAudio::getSampleRate(), FreeDVMod::MsgConfigureFreeDVMod::getSettings(), CWKeyer::MsgConfigureCWKeyer::getSettings(), m_audioSampleRate, m_channelizer, m_fileName, m_fileSize, m_ifstream, m_settings, FreeDVModSettings::m_useReverseAPI, Message::match(), openFileStream(), MessageQueue::push(), seekFileStream(), and webapiReverseSendCWSettings().
Referenced by setSpectrumSampleSink().
 {
     if (UpChannelizer::MsgChannelizerNotification::match(cmd))
     {
         UpChannelizer::MsgChannelizerNotification& notif = (UpChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "FreeDVMod::handleMessage: MsgChannelizerNotification";
         applyChannelSettings(notif.getBasebandSampleRate(), notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "FreeDVMod::handleMessage: MsgConfigureChannelizer: sampleRate: " << cfg.getSampleRate()
                 << " centerFrequency: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureFreeDVMod::match(cmd))
     {
         MsgConfigureFreeDVMod& cfg = (MsgConfigureFreeDVMod&) cmd;
         qDebug() << "FreeDVMod::handleMessage: MsgConfigureFreeDVMod";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgConfigureFileSourceName::match(cmd))
     {
         MsgConfigureFileSourceName& conf = (MsgConfigureFileSourceName&) cmd;
         m_fileName = conf.getFileName();
         openFileStream();
         return true;
     }
     else if (MsgConfigureFileSourceSeek::match(cmd))
     {
         MsgConfigureFileSourceSeek& conf = (MsgConfigureFileSourceSeek&) cmd;
         int seekPercentage = conf.getPercentage();
         seekFileStream(seekPercentage);
         return true;
     }
     else if (MsgConfigureFileSourceStreamTiming::match(cmd))
     {
         std::size_t samplesCount;
         if (m_ifstream.eof()) {
             samplesCount = m_fileSize / sizeof(int16_t);
         } else {
             samplesCount = m_ifstream.tellg() / sizeof(int16_t);
         }
         if (getMessageQueueToGUI())
         {
             MsgReportFileSourceStreamTiming *report;
             report = MsgReportFileSourceStreamTiming::create(samplesCount);
             getMessageQueueToGUI()->push(report);
         }
         return true;
     }
     else if (CWKeyer::MsgConfigureCWKeyer::match(cmd))
     {
         const CWKeyer::MsgConfigureCWKeyer& cfg = (CWKeyer::MsgConfigureCWKeyer&) cmd;
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendCWSettings(cfg.getSettings());
         }
         return true;
     }
     else if (DSPConfigureAudio::match(cmd))
     {
         DSPConfigureAudio& cfg = (DSPConfigureAudio&) cmd;
         uint32_t sampleRate = cfg.getSampleRate();
         qDebug() << "FreeDVMod::handleMessage: DSPConfigureAudio:"
                 << " sampleRate: " << sampleRate;
         if (sampleRate != m_audioSampleRate) {
             applyAudioSampleRate(sampleRate);
         }
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         return false;
     }
 }
levelChanged
void FreeDVMod::levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples) signal
Level changed
Parameters
rmsLevel RMS level in range 0.0 - 1.0
peakLevel Peak level in range 0.0 - 1.0
numSamples Number of audio samples analyzed
Referenced by calculateLevel().
modulateSample()
void FreeDVMod::modulateSample () private
Definition at line 194 of file freedvmod.cpp.
References calculateLevel(), m_audioBufferFill, FreeDVModSettings::m_gaugeInputElseModem, m_modSample, m_settings, and pullAF().
Referenced by pull().
 {
     pullAF(m_modSample);
     if (!m_settings.m_gaugeInputElseModem) {
         calculateLevel(m_modSample);
     }
     m_audioBufferFill++;
 }
networkManagerFinished
void FreeDVMod::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 1121 of file freedvmod.cpp.
Referenced by FreeDVMod(), and ~FreeDVMod().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "FreeDVMod::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("FreeDVMod::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openFileStream()
void FreeDVMod::openFileStream () private
Definition at line 530 of file freedvmod.cpp.
References FreeDVMod::MsgReportFileSourceStreamData::create(), BasebandSampleSource::getMessageQueueToGUI(), m_fileName, m_fileSize, m_ifstream, m_inputSampleRate, m_recordLength, and MessageQueue::push().
Referenced by handleMessage().
 {
     if (m_ifstream.is_open()) {
         m_ifstream.close();
     }
     m_ifstream.open(m_fileName.toStdString().c_str(), std::ios::binary | std::ios::ate);
     m_fileSize = m_ifstream.tellg();
     m_ifstream.seekg(0,std::ios_base::beg);
     m_recordLength = m_fileSize / (sizeof(int16_t) * m_inputSampleRate);
     qDebug() << "FreeDVMod::openFileStream: " << m_fileName.toStdString().c_str()
             << " fileSize: " << m_fileSize << "bytes"
             << " length: " << m_recordLength << " seconds";
     if (getMessageQueueToGUI())
     {
         MsgReportFileSourceStreamData *report;
         report = MsgReportFileSourceStreamData::create(m_inputSampleRate, m_recordLength);
         getMessageQueueToGUI()->push(report);
     }
 }
pull()
void FreeDVMod::pull (Sample & sample) virtual
Implements BasebandSampleSource.
Definition at line 142 of file freedvmod.cpp.
References MovingAverageUtil< T, Total, N >::asDouble(), Interpolator::decimate(), Interpolator::interpolate(), m_carrierNco, Sample::m_imag, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_magsq, m_modSample, m_movingAverage, Sample::m_real, m_settingsMutex, modulateSample(), NCOF::nextIQ(), SDR_TX_SCALED, and SDR_TX_SCALEF.
Referenced by setSpectrumSampleSink().
 {
     Complex ci;
     m_settingsMutex.lock();
     if (m_interpolatorDistance > 1.0f) // decimate
     {
         modulateSample();
         while (!m_interpolator.decimate(&m_interpolatorDistanceRemain, m_modSample, &ci))
         {
             modulateSample();
         }
     }
     else
     {
         if (m_interpolator.interpolate(&m_interpolatorDistanceRemain, m_modSample, &ci))
         {
             modulateSample();
         }
     }
     m_interpolatorDistanceRemain += m_interpolatorDistance;
     ci *= m_carrierNco.nextIQ(); // shift to carrier frequency
     ci *= 0.891235351562f * SDR_TX_SCALEF; //scaling at -1 dB to account for possible filter overshoot
     m_settingsMutex.unlock();
     double magsq = ci.real() * ci.real() + ci.imag() * ci.imag();
     magsq /= (SDR_TX_SCALED*SDR_TX_SCALED);
     m_movingAverage(magsq);
     m_magsq = m_movingAverage.asDouble();
     sample.m_real = (FixReal) ci.real();
     sample.m_imag = (FixReal) ci.imag();
 }
pullAF()
void FreeDVMod::pullAF (Complex & sample) private
Definition at line 203 of file freedvmod.cpp.
References calculateLevel(), AudioResampler::downSample(), BasebandSampleSink::feed(), FreeDVModSettings::FreeDVModInputAudio, FreeDVModSettings::FreeDVModInputCWTone, FreeDVModSettings::FreeDVModInputFile, FreeDVModSettings::FreeDVModInputNone, FreeDVModSettings::FreeDVModInputTone, CWKeyer::getCWSmoother(), CWSmoother::getFadeSample(), CWKeyer::getSample(), i, m_audioBuffer, m_audioBufferFill, FreeDVModSettings::m_audioMute, m_audioResampler, m_cwKeyer, m_freeDV, FreeDVModSettings::m_gaugeInputElseModem, m_ifstream, m_iModem, FreeDVModSettings::m_modAFInput, m_modOut, m_nNomModemSamples, m_nSpeechSamples, FreeDVModSettings::m_playLoop, m_sampleBuffer, m_sampleSink, m_scaleFactor, m_settings, FreeDVModSettings::m_spanLog2, m_speechIn, m_SSBFilter, m_SSBFilterBuffer, m_SSBFilterBufferIndex, m_sum, m_toneNco, m_undersampleCount, FreeDVModSettings::m_volumeFactor, NCOF::next(), fftfilt::runSSB(), SDR_TX_SCALEF, and NCOF::setPhase().
Referenced by modulateSample().
 {
     if (m_settings.m_audioMute)
     {
         sample.real(0.0f);
         sample.imag(0.0f);
         return;
     }
     Complex ci;
     fftfilt::cmplx *filtered;
     int n_out = 0;
     int decim = 1<<(m_settings.m_spanLog2 - 1);
     unsigned char decim_mask = decim - 1; // counter LSB bit mask for decimation by 2^(m_scaleLog2 - 1)
     if (m_iModem >= m_nNomModemSamples)
     {
         switch (m_settings.m_modAFInput)
         {
         case FreeDVModSettings::FreeDVModInputTone:
             for (int i = 0; i < m_nSpeechSamples; i++)
             {
                 m_speechIn[i] = m_toneNco.next() * 32768.0f * m_settings.m_volumeFactor;
                 if (m_settings.m_gaugeInputElseModem) {
                     calculateLevel(m_speechIn[i]);
                 }
             }
             freedv_tx(m_freeDV, m_modOut, m_speechIn);
             break;
         case FreeDVModSettings::FreeDVModInputFile:
             if (m_iModem >= m_nNomModemSamples)
             {
                 if (m_ifstream.is_open())
                 {
                     std::fill(m_speechIn, m_speechIn + m_nSpeechSamples, 0);
                     if (m_ifstream.eof())
                     {
                         if (m_settings.m_playLoop)
{
                             m_ifstream.clear();
                             m_ifstream.seekg(0, std::ios::beg);
                         }
                     }
                     if (m_ifstream.eof())
                     {
                         std::fill(m_modOut, m_modOut + m_nNomModemSamples, 0);
                     }
                     else
                     {
                         m_ifstream.read(reinterpret_cast<char*>(m_speechIn), sizeof(int16_t) * m_nSpeechSamples);
                         if ((m_settings.m_volumeFactor != 1.0) || m_settings.m_gaugeInputElseModem)
{
                             for (int i = 0; i < m_nSpeechSamples; i++)
{
                                 if (m_settings.m_volumeFactor != 1.0) {
                                     m_speechIn[i] *= m_settings.m_volumeFactor;
                                 }
                                 if (m_settings.m_gaugeInputElseModem) {
                                     calculateLevel(m_speechIn[i]);
                                 }
                             }
                         }
                         freedv_tx(m_freeDV, m_modOut, m_speechIn);
                     }
                 }
                 else
                 {
                     std::fill(m_modOut, m_modOut + m_nNomModemSamples, 0);
                 }
             }
             break;
         case FreeDVModSettings::FreeDVModInputAudio:
             for (int i = 0; i < m_nSpeechSamples; i++)
             {
                 qint16 audioSample = (m_audioBuffer[m_audioBufferFill].l + m_audioBuffer[m_audioBufferFill].r) * (m_settings.m_volumeFactor / 2.0f);
                 m_audioBufferFill++;
                 while (!m_audioResampler.downSample(audioSample, m_speechIn[i]))
                 {
                     audioSample = (m_audioBuffer[m_audioBufferFill].l + m_audioBuffer[m_audioBufferFill].r) * (m_settings.m_volumeFactor / 2.0f);
                     m_audioBufferFill++;
                 }
                 if (m_settings.m_gaugeInputElseModem) {
                     calculateLevel(m_speechIn[i]);
                 }
             }
             freedv_tx(m_freeDV, m_modOut, m_speechIn);
             break;
         case FreeDVModSettings::FreeDVModInputCWTone:
             for (int i = 0; i < m_nSpeechSamples; i++)
             {
                 Real fadeFactor;
                 if (m_cwKeyer.getSample())
                 {
                     m_cwKeyer.getCWSmoother().getFadeSample(true, fadeFactor);
                     m_speechIn[i] = m_toneNco.next() * 32768.0f * fadeFactor * m_settings.m_volumeFactor;
                 }
                 else
                 {
                     if (m_cwKeyer.getCWSmoother().getFadeSample(false, fadeFactor))
                     {
                         m_speechIn[i] = m_toneNco.next() * 32768.0f * fadeFactor * m_settings.m_volumeFactor;
                     }
                     else
                     {
                         m_speechIn[i] = 0;
                         m_toneNco.setPhase(0);
                     }
                 }
                 if (m_settings.m_gaugeInputElseModem) {
                     calculateLevel(m_speechIn[i]);
                 }
             }
             freedv_tx(m_freeDV, m_modOut, m_speechIn);
             break;
         case FreeDVModSettings::FreeDVModInputNone:
         default:
             std::fill(m_speechIn, m_speechIn + m_nSpeechSamples, 0);
             freedv_tx(m_freeDV, m_modOut, m_speechIn);
             break;
         }
         m_iModem = 0;
     }
     ci.real(m_modOut[m_iModem++] / m_scaleFactor);
     ci.imag(0.0f);
     n_out = m_SSBFilter->runSSB(ci, &filtered, true); // USB
     if (n_out > 0)
     {
         memcpy((void *) m_SSBFilterBuffer, (const void *) filtered, n_out*sizeof(Complex));
         m_SSBFilterBufferIndex = 0;
         for (int i = 0; i < n_out; i++)
         {
             // Downsample by 2^(m_scaleLog2 - 1) for SSB band spectrum display
             // smart decimation with bit gain using float arithmetic (23 bits significand)
             m_sum += filtered[i];
             if (!(m_undersampleCount++ & decim_mask))
             {
                 Real avgr = (m_sum.real() / decim) * 0.891235351562f * SDR_TX_SCALEF; //scaling at -1 dB to account for possible filter overshoot
                 Real avgi = (m_sum.imag() / decim) * 0.891235351562f * SDR_TX_SCALEF;
                 m_sampleBuffer.push_back(Sample(avgr, avgi));
                 m_sum.real(0.0);
                 m_sum.imag(0.0);
             }
         }
         if (m_sampleSink != 0)
         {
             m_sampleSink->feed(m_sampleBuffer.begin(), m_sampleBuffer.end(), true); // SSB
         }
         m_sampleBuffer.clear();
     }
     sample = m_SSBFilterBuffer[m_SSBFilterBufferIndex++];
 }
pullAudio()
void FreeDVMod::pullAudio (int nbSamples) virtual
Reimplemented from BasebandSampleSource.
Definition at line 181 of file freedvmod.cpp.
References m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_modemSampleRate, and AudioFifo::read().
Referenced by setSpectrumSampleSink().
 {
     unsigned int nbSamplesAudio = nbSamples * ((Real) m_audioSampleRate / (Real) m_modemSampleRate);
     if (nbSamplesAudio > m_audioBuffer.size())
     {
         m_audioBuffer.resize(nbSamplesAudio);
     }
     m_audioFifo.read(reinterpret_cast<quint8*>(&m_audioBuffer[0]), nbSamplesAudio);
     m_audioBufferFill = 0;
 }
seekFileStream()
void FreeDVMod::seekFileStream (int seekPercentage) private
Definition at line 554 of file freedvmod.cpp.
References m_ifstream, m_inputSampleRate, m_recordLength, and m_settingsMutex.
Referenced by handleMessage().
 {
     QMutexLocker mutexLocker(&m_settingsMutex);
     if (m_ifstream.is_open())
     {
         int seekPoint = ((m_recordLength * seekPercentage) / 100) * m_inputSampleRate;
         seekPoint *= sizeof(Real);
         m_ifstream.clear();
         m_ifstream.seekg(seekPoint, std::ios::beg);
     }
 }
serialize()
QByteArray FreeDVMod::serialize () const virtual
Implements ChannelAPI.
Definition at line 815 of file freedvmod.cpp.
References m_settings, and FreeDVModSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
setSpectrumSampleSink()
void FreeDVMod::setSpectrumSampleSink (BasebandSampleSink * sampleSink) inline
Definition at line 212 of file freedvmod.h.
References handleMessage(), m_sampleSink, pull(), pullAudio(), start(), and stop().
Referenced by FreeDVModGUI::FreeDVModGUI().
 { m_sampleSink = sampleSink; }
start()
void FreeDVMod::start () virtual
Implements BasebandSampleSource.
Definition at line 417 of file freedvmod.cpp.
References applyChannelSettings(), AudioFifo::clear(), m_audioFifo, m_basebandSampleRate, FreeDVModSettings::m_inputFrequencyOffset, m_inputFrequencyOffset, m_outputSampleRate, and m_settings.
Referenced by setSpectrumSampleSink().
 {
     qDebug() << "FreeDVMod::start: m_outputSampleRate: " << m_outputSampleRate
             << " m_inputFrequencyOffset: " << m_settings.m_inputFrequencyOffset;
     m_audioFifo.clear();
     applyChannelSettings(m_basebandSampleRate, m_outputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void FreeDVMod::stop () virtual
Implements BasebandSampleSource.
Definition at line 426 of file freedvmod.cpp.
Referenced by setSpectrumSampleSink().
 {
 }
webapiFormatChannelReport()
void FreeDVMod::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 1007 of file freedvmod.cpp.
References CalcDb::dbPower(), SWGSDRangel::SWGChannelReport::getFreeDvModReport(), getMagSq(), m_audioSampleRate, m_outputSampleRate, SWGSDRangel::SWGFreeDVModReport::setAudioSampleRate(), SWGSDRangel::SWGFreeDVModReport::setChannelPowerDb(), and SWGSDRangel::SWGFreeDVModReport::setChannelSampleRate().
Referenced by webapiReportGet().
 {
     response.getFreeDvModReport()->setChannelPowerDb(CalcDb::dbPower(getMagSq()));
     response.getFreeDvModReport()->setAudioSampleRate(m_audioSampleRate);
     response.getFreeDvModReport()->setChannelSampleRate(m_outputSampleRate);
 }
webapiFormatChannelSettings()
void FreeDVMod::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const FreeDVModSettings & settings) private
Definition at line 960 of file freedvmod.cpp.
References SWGSDRangel::SWGFreeDVModSettings::getAudioDeviceName(), SWGSDRangel::SWGFreeDVModSettings::getCwKeyer(), SWGSDRangel::SWGChannelSettings::getFreeDvModSettings(), SWGSDRangel::SWGFreeDVModSettings::getReverseApiAddress(), CWKeyer::getSettings(), SWGSDRangel::SWGFreeDVModSettings::getTitle(), FreeDVModSettings::m_audioDeviceName, FreeDVModSettings::m_audioMute, m_cwKeyer, FreeDVModSettings::m_freeDVMode, FreeDVModSettings::m_gaugeInputElseModem, FreeDVModSettings::m_inputFrequencyOffset, FreeDVModSettings::m_modAFInput, FreeDVModSettings::m_playLoop, FreeDVModSettings::m_reverseAPIAddress, FreeDVModSettings::m_reverseAPIChannelIndex, FreeDVModSettings::m_reverseAPIDeviceIndex, FreeDVModSettings::m_reverseAPIPort, FreeDVModSettings::m_rgbColor, FreeDVModSettings::m_spanLog2, FreeDVModSettings::m_title, FreeDVModSettings::m_toneFrequency, FreeDVModSettings::m_useReverseAPI, FreeDVModSettings::m_volumeFactor, SWGSDRangel::SWGFreeDVModSettings::setAudioDeviceName(), SWGSDRangel::SWGFreeDVModSettings::setAudioMute(), SWGSDRangel::SWGFreeDVModSettings::setCwKeyer(), SWGSDRangel::SWGFreeDVModSettings::setFreeDvMode(), SWGSDRangel::SWGFreeDVModSettings::setGaugeInputElseModem(), SWGSDRangel::SWGFreeDVModSettings::setInputFrequencyOffset(), SWGSDRangel::SWGFreeDVModSettings::setModAfInput(), SWGSDRangel::SWGFreeDVModSettings::setPlayLoop(), SWGSDRangel::SWGFreeDVModSettings::setReverseApiAddress(), SWGSDRangel::SWGFreeDVModSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGFreeDVModSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGFreeDVModSettings::setReverseApiPort(), SWGSDRangel::SWGFreeDVModSettings::setRgbColor(), SWGSDRangel::SWGFreeDVModSettings::setSpanLog2(), SWGSDRangel::SWGFreeDVModSettings::setTitle(), SWGSDRangel::SWGFreeDVModSettings::setToneFrequency(), SWGSDRangel::SWGFreeDVModSettings::setUseReverseApi(), SWGSDRangel::SWGFreeDVModSettings::setVolumeFactor(), and CWKeyer::webapiFormatChannelSettings().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getFreeDvModSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getFreeDvModSettings()->setToneFrequency(settings.m_toneFrequency);
     response.getFreeDvModSettings()->setVolumeFactor(settings.m_volumeFactor);
     response.getFreeDvModSettings()->setSpanLog2(settings.m_spanLog2);
     response.getFreeDvModSettings()->setAudioMute(settings.m_audioMute ? 1 : 0);
     response.getFreeDvModSettings()->setPlayLoop(settings.m_playLoop ? 1 : 0);
     response.getFreeDvModSettings()->setRgbColor(settings.m_rgbColor);
     response.getFreeDvModSettings()->setGaugeInputElseModem(settings.m_gaugeInputElseModem ? 1 : 0);
     if (response.getFreeDvModSettings()->getTitle()) {
         *response.getFreeDvModSettings()->getTitle() = settings.m_title;
     } else {
         response.getFreeDvModSettings()->setTitle(new QString(settings.m_title));
     }
     response.getFreeDvModSettings()->setModAfInput((int) settings.m_modAFInput);
     response.getFreeDvModSettings()->setFreeDvMode((int) settings.m_freeDVMode);
     if (response.getFreeDvModSettings()->getAudioDeviceName()) {
         *response.getFreeDvModSettings()->getAudioDeviceName() = settings.m_audioDeviceName;
     } else {
         response.getFreeDvModSettings()->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     if (!response.getFreeDvModSettings()->getCwKeyer()) {
         response.getFreeDvModSettings()->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings);
     }
     SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = response.getFreeDvModSettings()->getCwKeyer();
     const CWKeyerSettings& cwKeyerSettings = m_cwKeyer.getSettings();
     m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     response.getFreeDvModSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getFreeDvModSettings()->getReverseApiAddress()) {
         *response.getFreeDvModSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getFreeDvModSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getFreeDvModSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getFreeDvModSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getFreeDvModSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int FreeDVMod::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 949 of file freedvmod.cpp.
References SWGSDRangel::SWGChannelReport::getFreeDvModReport(), SWGSDRangel::SWGFreeDVModReport::init(), SWGSDRangel::SWGChannelReport::setFreeDvModReport(), and webapiFormatChannelReport().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setFreeDvModReport(new SWGSDRangel::SWGFreeDVModReport());
     response.getFreeDvModReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendCWSettings()
void FreeDVMod::webapiReverseSendCWSettings (const CWKeyerSettings & settings) private
Definition at line 1090 of file freedvmod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), SWGSDRangel::SWGFreeDVModSettings::getCwKeyer(), SWGSDRangel::SWGChannelSettings::getFreeDvModSettings(), m_cwKeyer, m_networkManager, m_networkRequest, FreeDVModSettings::m_reverseAPIAddress, FreeDVModSettings::m_reverseAPIChannelIndex, FreeDVModSettings::m_reverseAPIDeviceIndex, FreeDVModSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGFreeDVModSettings::setCwKeyer(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGChannelSettings::setFreeDvModSettings(), and CWKeyer::webapiFormatChannelSettings().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setChannelType(new QString("FreeDVMod"));
     swgChannelSettings->setFreeDvModSettings(new SWGSDRangel::SWGFreeDVModSettings());
     SWGSDRangel::SWGFreeDVModSettings *swgFreeDVModSettings = swgChannelSettings->getFreeDvModSettings();
     swgFreeDVModSettings->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings());
     SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = swgFreeDVModSettings->getCwKeyer();
     m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex)
             .arg(m_settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiReverseSendSettings()
void FreeDVMod::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const FreeDVModSettings & settings, bool force) private
Definition at line 1014 of file freedvmod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), SWGSDRangel::SWGFreeDVModSettings::getCwKeyer(), ChannelAPI::getDeviceSetIndex(), SWGSDRangel::SWGChannelSettings::getFreeDvModSettings(), ChannelAPI::getIndexInDeviceSet(), CWKeyer::getSettings(), FreeDVModSettings::m_audioDeviceName, FreeDVModSettings::m_audioMute, m_cwKeyer, FreeDVModSettings::m_freeDVMode, FreeDVModSettings::m_gaugeInputElseModem, FreeDVModSettings::m_inputFrequencyOffset, FreeDVModSettings::m_modAFInput, m_networkManager, m_networkRequest, FreeDVModSettings::m_playLoop, FreeDVModSettings::m_reverseAPIAddress, FreeDVModSettings::m_reverseAPIChannelIndex, FreeDVModSettings::m_reverseAPIDeviceIndex, FreeDVModSettings::m_reverseAPIPort, FreeDVModSettings::m_rgbColor, FreeDVModSettings::m_spanLog2, FreeDVModSettings::m_title, FreeDVModSettings::m_toneFrequency, FreeDVModSettings::m_volumeFactor, SWGSDRangel::SWGFreeDVModSettings::setAudioDeviceName(), SWGSDRangel::SWGFreeDVModSettings::setAudioMute(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGFreeDVModSettings::setCwKeyer(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGFreeDVModSettings::setFreeDvMode(), SWGSDRangel::SWGChannelSettings::setFreeDvModSettings(), SWGSDRangel::SWGFreeDVModSettings::setInputFrequencyOffset(), SWGSDRangel::SWGFreeDVModSettings::setModAfInput(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGFreeDVModSettings::setPlayLoop(), SWGSDRangel::SWGFreeDVModSettings::setRgbColor(), SWGSDRangel::SWGFreeDVModSettings::setSpanLog2(), SWGSDRangel::SWGFreeDVModSettings::setTitle(), SWGSDRangel::SWGFreeDVModSettings::setToneFrequency(), SWGSDRangel::SWGFreeDVModSettings::setVolumeFactor(), and CWKeyer::webapiFormatChannelSettings().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("FreeDVMod"));
     swgChannelSettings->setFreeDvModSettings(new SWGSDRangel::SWGFreeDVModSettings());
     SWGSDRangel::SWGFreeDVModSettings *swgFreeDVModSettings = swgChannelSettings->getFreeDvModSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgFreeDVModSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("toneFrequency") || force) {
         swgFreeDVModSettings->setToneFrequency(settings.m_toneFrequency);
     }
     if (channelSettingsKeys.contains("volumeFactor") || force) {
         swgFreeDVModSettings->setVolumeFactor(settings.m_volumeFactor);
     }
     if (channelSettingsKeys.contains("spanLog2") || force) {
         swgFreeDVModSettings->setSpanLog2(settings.m_spanLog2);
     }
     if (channelSettingsKeys.contains("audioMute") || force) {
         swgFreeDVModSettings->setAudioMute(settings.m_audioMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("playLoop") || force) {
         swgFreeDVModSettings->setPlayLoop(settings.m_playLoop ? 1 : 0);
     }
     if (channelSettingsKeys.contains("gaugeInputElseModem") || force) {
         swgFreeDVModSettings->setPlayLoop(settings.m_gaugeInputElseModem ? 1 : 0);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgFreeDVModSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgFreeDVModSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("freeDVMode") || force) {
         swgFreeDVModSettings->setFreeDvMode((int) settings.m_freeDVMode);
     }
     if (channelSettingsKeys.contains("modAFInput") || force) {
         swgFreeDVModSettings->setModAfInput((int) settings.m_modAFInput);
     }
     if (channelSettingsKeys.contains("audioDeviceName") || force) {
         swgFreeDVModSettings->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     if (force)
     {
         const CWKeyerSettings& cwKeyerSettings = m_cwKeyer.getSettings();
         swgFreeDVModSettings->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings());
         SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = swgFreeDVModSettings->getCwKeyer();
         m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int FreeDVMod::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 837 of file freedvmod.cpp.
References SWGSDRangel::SWGChannelSettings::getFreeDvModSettings(), SWGSDRangel::SWGFreeDVModSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setFreeDvModSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setFreeDvModSettings(new SWGSDRangel::SWGFreeDVModSettings());
     response.getFreeDvModSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int FreeDVMod::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 848 of file freedvmod.cpp.
References FreeDVMod::MsgConfigureFreeDVMod::create(), CWKeyer::MsgConfigureCWKeyer::create(), FreeDVMod::MsgConfigureChannelizer::create(), SWGSDRangel::SWGFreeDVModSettings::getAudioDeviceName(), SWGSDRangel::SWGFreeDVModSettings::getAudioMute(), SWGSDRangel::SWGFreeDVModSettings::getCwKeyer(), SWGSDRangel::SWGFreeDVModSettings::getFreeDvMode(), SWGSDRangel::SWGChannelSettings::getFreeDvModSettings(), SWGSDRangel::SWGFreeDVModSettings::getGaugeInputElseModem(), SWGSDRangel::SWGFreeDVModSettings::getInputFrequencyOffset(), CWKeyer::getInputMessageQueue(), SWGSDRangel::SWGFreeDVModSettings::getModAfInput(), SWGSDRangel::SWGFreeDVModSettings::getPlayLoop(), SWGSDRangel::SWGFreeDVModSettings::getReverseApiAddress(), SWGSDRangel::SWGFreeDVModSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGFreeDVModSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGFreeDVModSettings::getReverseApiPort(), SWGSDRangel::SWGFreeDVModSettings::getRgbColor(), CWKeyer::getSettings(), SWGSDRangel::SWGFreeDVModSettings::getSpanLog2(), SWGSDRangel::SWGFreeDVModSettings::getTitle(), SWGSDRangel::SWGFreeDVModSettings::getToneFrequency(), SWGSDRangel::SWGFreeDVModSettings::getUseReverseApi(), SWGSDRangel::SWGFreeDVModSettings::getVolumeFactor(), FreeDVModSettings::m_audioDeviceName, FreeDVModSettings::m_audioMute, m_audioSampleRate, m_cwKeyer, FreeDVModSettings::m_freeDVMode, FreeDVModSettings::m_gaugeInputElseModem, BasebandSampleSource::m_guiMessageQueue, FreeDVModSettings::m_inputFrequencyOffset, BasebandSampleSource::m_inputMessageQueue, FreeDVModSettings::m_modAFInput, FreeDVModSettings::m_playLoop, FreeDVModSettings::m_reverseAPIAddress, FreeDVModSettings::m_reverseAPIChannelIndex, FreeDVModSettings::m_reverseAPIDeviceIndex, FreeDVModSettings::m_reverseAPIPort, FreeDVModSettings::m_rgbColor, m_settings, FreeDVModSettings::m_spanLog2, FreeDVModSettings::m_title, FreeDVModSettings::m_toneFrequency, FreeDVModSettings::m_useReverseAPI, FreeDVModSettings::m_volumeFactor, MessageQueue::push(), webapiFormatChannelSettings(), and CWKeyer::webapiSettingsPutPatch().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     FreeDVModSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getFreeDvModSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("toneFrequency")) {
         settings.m_toneFrequency = response.getFreeDvModSettings()->getToneFrequency();
     }
     if (channelSettingsKeys.contains("volumeFactor")) {
         settings.m_volumeFactor = response.getFreeDvModSettings()->getVolumeFactor();
     }
     if (channelSettingsKeys.contains("spanLog2")) {
         settings.m_spanLog2 = response.getFreeDvModSettings()->getSpanLog2();
     }
     if (channelSettingsKeys.contains("audioMute")) {
         settings.m_audioMute = response.getFreeDvModSettings()->getAudioMute() != 0;
     }
     if (channelSettingsKeys.contains("playLoop")) {
         settings.m_playLoop = response.getFreeDvModSettings()->getPlayLoop() != 0;
     }
     if (channelSettingsKeys.contains("gaugeInputElseModem")) {
         settings.m_gaugeInputElseModem = response.getFreeDvModSettings()->getGaugeInputElseModem() != 0;
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getFreeDvModSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getFreeDvModSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("freeDVMode")) {
         settings.m_freeDVMode = (FreeDVModSettings::FreeDVMode) response.getFreeDvModSettings()->getFreeDvMode();
     }
     if (channelSettingsKeys.contains("modAFInput")) {
         settings.m_modAFInput = (FreeDVModSettings::FreeDVModInputAF) response.getFreeDvModSettings()->getModAfInput();
     }
     if (channelSettingsKeys.contains("audioDeviceName")) {
         settings.m_audioDeviceName = *response.getFreeDvModSettings()->getAudioDeviceName();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getFreeDvModSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getFreeDvModSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getFreeDvModSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getFreeDvModSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getFreeDvModSettings()->getReverseApiChannelIndex();
     }
     if (channelSettingsKeys.contains("cwKeyer"))
     {
         SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = response.getFreeDvModSettings()->getCwKeyer();
         CWKeyerSettings cwKeyerSettings = m_cwKeyer.getSettings();
         m_cwKeyer.webapiSettingsPutPatch(channelSettingsKeys, cwKeyerSettings, apiCwKeyerSettings);
         CWKeyer::MsgConfigureCWKeyer *msgCwKeyer = CWKeyer::MsgConfigureCWKeyer::create(cwKeyerSettings, force);
         m_cwKeyer.getInputMessageQueue()->push(msgCwKeyer);
         if (m_guiMessageQueue) // forward to GUI if any
         {
             CWKeyer::MsgConfigureCWKeyer *msgCwKeyerToGUI = CWKeyer::MsgConfigureCWKeyer::create(cwKeyerSettings, force);
             m_guiMessageQueue->push(msgCwKeyerToGUI);
         }
     }
     if (frequencyOffsetChanged)
     {
         FreeDVMod::MsgConfigureChannelizer *msgChan = FreeDVMod::MsgConfigureChannelizer::create(
                 m_audioSampleRate, settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(msgChan);
     }
     MsgConfigureFreeDVMod *msg = MsgConfigureFreeDVMod::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureFreeDVMod *msgToGUI = MsgConfigureFreeDVMod::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_audioBuffer
AudioVector FreeDVMod::m_audioBuffer private
Definition at line 313 of file freedvmod.h.
Referenced by FreeDVMod(), pullAF(), and pullAudio().
m_audioBufferFill
uint FreeDVMod::m_audioBufferFill private
Definition at line 314 of file freedvmod.h.
Referenced by FreeDVMod(), modulateSample(), pullAF(), and pullAudio().
m_audioFifo
AudioFifo FreeDVMod::m_audioFifo private
Definition at line 315 of file freedvmod.h.
Referenced by applySettings(), FreeDVMod(), pullAudio(), start(), and ~FreeDVMod().
m_audioResampler
AudioResampler FreeDVMod::m_audioResampler private
Definition at line 341 of file freedvmod.h.
Referenced by applyAudioSampleRate(), and pullAF().
m_audioSampleRate
quint32 FreeDVMod::m_audioSampleRate private
Definition at line 312 of file freedvmod.h.
Referenced by applyAudioSampleRate(), applySettings(), FreeDVMod(), getAudioSampleRate(), handleMessage(), pullAudio(), webapiFormatChannelReport(), and webapiSettingsPutPatch().
m_basebandSampleRate
int FreeDVMod::m_basebandSampleRate private
Definition at line 282 of file freedvmod.h.
Referenced by applyChannelSettings(), FreeDVMod(), and start().
m_carrierNco
NCOF FreeDVMod::m_carrierNco private
Definition at line 290 of file freedvmod.h.
Referenced by applyChannelSettings(), and pull().
m_channelId
const QString FreeDVMod::m_channelId = "FreeDVMod" static
Definition at line 260 of file freedvmod.h.
Referenced by FreeDVMod(), and FreeDVModPlugin::initPlugin().
m_channelIdURI
const QString FreeDVMod::m_channelIdURI = "sdrangel.channeltx.freedvmod" static
Definition at line 259 of file freedvmod.h.
Referenced by FreeDVModGUI::FreeDVModGUI(), and FreeDVModPlugin::initPlugin().
m_channelizer
UpChannelizer* FreeDVMod::m_channelizer private
Definition at line 280 of file freedvmod.h.
Referenced by FreeDVMod(), handleMessage(), and ~FreeDVMod().
m_cwKeyer
CWKeyer FreeDVMod::m_cwKeyer private
Definition at line 328 of file freedvmod.h.
Referenced by FreeDVMod(), getCWKeyer(), pullAF(), webapiFormatChannelSettings(), webapiReverseSendCWSettings(), webapiReverseSendSettings(), and webapiSettingsPutPatch().
m_deviceAPI
DeviceAPI* FreeDVMod::m_deviceAPI private
Definition at line 278 of file freedvmod.h.
Referenced by FreeDVMod(), and ~FreeDVMod().
m_fileName
QString FreeDVMod::m_fileName private
Definition at line 320 of file freedvmod.h.
Referenced by FreeDVMod::MsgConfigureFileSourceName::getFileName(), handleMessage(), and openFileStream().
m_fileSize
quint64 FreeDVMod::m_fileSize private
raw file size (bytes)
Definition at line 321 of file freedvmod.h.
Referenced by handleMessage(), and openFileStream().
m_freeDV
struct freedv* FreeDVMod::m_freeDV private
Definition at line 333 of file freedvmod.h.
Referenced by applyFreeDVMode(), pullAF(), and ~FreeDVMod().
m_hiCutoff
Real FreeDVMod::m_hiCutoff private
Definition at line 287 of file freedvmod.h.
Referenced by applyChannelSettings(), applyFreeDVMode(), FreeDVMod(), and getHiCutoff().
m_ifstream
std::ifstream FreeDVMod::m_ifstream private
Definition at line 319 of file freedvmod.h.
Referenced by handleMessage(), openFileStream(), pullAF(), and seekFileStream().
m_iModem
int FreeDVMod::m_iModem private
Definition at line 337 of file freedvmod.h.
Referenced by applyFreeDVMode(), and pullAF().
m_inputFrequencyOffset
int FreeDVMod::m_inputFrequencyOffset private
Definition at line 285 of file freedvmod.h.
Referenced by applyChannelSettings(), FreeDVMod(), and start().
m_inputSampleRate
int FreeDVMod::m_inputSampleRate private
speech (input) sample rate (fixed 8000 S/s)
Definition at line 323 of file freedvmod.h.
Referenced by applyAudioSampleRate(), applySettings(), FreeDVMod(), openFileStream(), and seekFileStream().
m_interpolator
Interpolator FreeDVMod::m_interpolator private
Definition at line 293 of file freedvmod.h.
Referenced by applyChannelSettings(), applyFreeDVMode(), and pull().
m_interpolatorConsumed
bool FreeDVMod::m_interpolatorConsumed private
Definition at line 296 of file freedvmod.h.
Referenced by applyChannelSettings(), and applyFreeDVMode().
m_interpolatorDistance
Real FreeDVMod::m_interpolatorDistance private
Definition at line 294 of file freedvmod.h.
Referenced by applyChannelSettings(), applyFreeDVMode(), and pull().
m_interpolatorDistanceRemain
Real FreeDVMod::m_interpolatorDistanceRemain private
Definition at line 295 of file freedvmod.h.
Referenced by applyChannelSettings(), applyFreeDVMode(), and pull().
m_iSpeech
int FreeDVMod::m_iSpeech private
Definition at line 336 of file freedvmod.h.
Referenced by applyFreeDVMode().
m_levelCalcCount
quint32 FreeDVMod::m_levelCalcCount private
Definition at line 325 of file freedvmod.h.
Referenced by calculateLevel().
m_levelNbSamples
const int FreeDVMod::m_levelNbSamples = 80 static private
Definition at line 343 of file freedvmod.h.
Referenced by calculateLevel().
m_levelSum
Real FreeDVMod::m_levelSum private
Definition at line 327 of file freedvmod.h.
Referenced by calculateLevel().
m_lowCutoff
Real FreeDVMod::m_lowCutoff private
Definition at line 286 of file freedvmod.h.
Referenced by applyFreeDVMode(), FreeDVMod(), and getLowCutoff().
m_magsq
double FreeDVMod::m_magsq private
Definition at line 309 of file freedvmod.h.
Referenced by FreeDVMod(), getMagSq(), and pull().
m_modemSampleRate
int FreeDVMod::m_modemSampleRate private
Definition at line 284 of file freedvmod.h.
Referenced by applyChannelSettings(), applyFreeDVMode(), getModemSampleRate(), and pullAudio().
m_modOut
int16_t* FreeDVMod::m_modOut private
Definition at line 339 of file freedvmod.h.
Referenced by applyFreeDVMode(), and pullAF().
m_modSample
Complex FreeDVMod::m_modSample private
Definition at line 292 of file freedvmod.h.
Referenced by modulateSample(), and pull().
m_movingAverage
MovingAverageUtil<double, double, 16> FreeDVMod::m_movingAverage private
Definition at line 310 of file freedvmod.h.
Referenced by pull().
m_networkManager
QNetworkAccessManager* FreeDVMod::m_networkManager private
Definition at line 330 of file freedvmod.h.
Referenced by FreeDVMod(), webapiReverseSendCWSettings(), webapiReverseSendSettings(), and ~FreeDVMod().
m_networkRequest
QNetworkRequest FreeDVMod::m_networkRequest private
Definition at line 331 of file freedvmod.h.
Referenced by webapiReverseSendCWSettings(), and webapiReverseSendSettings().
m_nNomModemSamples
int FreeDVMod::m_nNomModemSamples private
Definition at line 335 of file freedvmod.h.
Referenced by applyFreeDVMode(), and pullAF().
m_nSpeechSamples
int FreeDVMod::m_nSpeechSamples private
Definition at line 334 of file freedvmod.h.
Referenced by applyFreeDVMode(), and pullAF().
m_outputSampleRate
int FreeDVMod::m_outputSampleRate private
Definition at line 283 of file freedvmod.h.
Referenced by applyChannelSettings(), applyFreeDVMode(), FreeDVMod(), start(), and webapiFormatChannelReport().
m_peakLevel
Real FreeDVMod::m_peakLevel private
Definition at line 326 of file freedvmod.h.
Referenced by calculateLevel().
m_recordLength
quint32 FreeDVMod::m_recordLength private
record length in seconds computed from file size
Definition at line 322 of file freedvmod.h.
Referenced by FreeDVMod::MsgReportFileSourceStreamData::getRecordLength(), openFileStream(), and seekFileStream().
m_sampleBuffer
SampleVector FreeDVMod::m_sampleBuffer private
Definition at line 303 of file freedvmod.h.
Referenced by pullAF().
m_sampleSink
BasebandSampleSink* FreeDVMod::m_sampleSink private
Definition at line 302 of file freedvmod.h.
Referenced by pullAF(), and setSpectrumSampleSink().
m_scaleFactor
float FreeDVMod::m_scaleFactor private
divide by this amount to scale from int16 to float in [-1.0, 1.0] interval
Definition at line 340 of file freedvmod.h.
Referenced by applyFreeDVMode(), and pullAF().
m_settings
FreeDVModSettings FreeDVMod::m_settings private
Definition at line 288 of file freedvmod.h.
Referenced by applyFreeDVMode(), applySettings(), deserialize(), FreeDVMod(), handleMessage(), modulateSample(), pullAF(), serialize(), start(), webapiReverseSendCWSettings(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex FreeDVMod::m_settingsMutex private
Definition at line 317 of file freedvmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applyFreeDVMode(), applySettings(), pull(), and seekFileStream().
m_speechIn
int16_t* FreeDVMod::m_speechIn private
Definition at line 338 of file freedvmod.h.
Referenced by applyFreeDVMode(), and pullAF().
m_ssbFftLen
const int FreeDVMod::m_ssbFftLen = 1024 static private
Definition at line 300 of file freedvmod.h.
Referenced by FreeDVMod().
m_SSBFilter
fftfilt* FreeDVMod::m_SSBFilter private
Definition at line 297 of file freedvmod.h.
Referenced by applyFreeDVMode(), FreeDVMod(), pullAF(), and ~FreeDVMod().
m_SSBFilterBuffer
Complex* FreeDVMod::m_SSBFilterBuffer private
Definition at line 298 of file freedvmod.h.
Referenced by FreeDVMod(), pullAF(), and ~FreeDVMod().
m_SSBFilterBufferIndex
int FreeDVMod::m_SSBFilterBufferIndex private
Definition at line 299 of file freedvmod.h.
Referenced by pullAF().
m_sum
fftfilt::cmplx FreeDVMod::m_sum private
Definition at line 305 of file freedvmod.h.
Referenced by FreeDVMod(), and pullAF().
m_sumCount
int FreeDVMod::m_sumCount private
Definition at line 307 of file freedvmod.h.
Referenced by FreeDVMod().
m_threadedChannelizer
ThreadedBasebandSampleSource* FreeDVMod::m_threadedChannelizer private
Definition at line 279 of file freedvmod.h.
Referenced by FreeDVMod(), and ~FreeDVMod().
m_toneNco
NCOF FreeDVMod::m_toneNco private
Definition at line 291 of file freedvmod.h.
Referenced by applySettings(), FreeDVMod(), and pullAF().
m_undersampleCount
int FreeDVMod::m_undersampleCount private
Definition at line 306 of file freedvmod.h.
Referenced by FreeDVMod(), and pullAF().
The documentation for this class was generated from the following files:
plugins/channeltx/modfreedv/freedvmod.h
plugins/channeltx/modfreedv/freedvmod.cpp