SDRAngel: DATVideoRenderThread Class Reference
DATVideoRenderThread Class Reference
#include <datvideorender.h>
Inherits QThread.
Public Member Functions
DATVideoRenderThread ()
DATVideoRenderThread (DATVideoRender *renderer, DATVideostream *stream)
void setStreamAndRenderer (DATVideoRender *renderer, DATVideostream *stream)
void run ()
void stopRendering ()
Private Attributes
DATVideoRender * m_renderer
DATVideostream * m_stream
bool m_renderingVideo
Detailed Description
Definition at line 167 of file datvideorender.h.
Constructor & Destructor Documentation
DATVideoRenderThread() [1/2]
DATVideoRenderThread::DATVideoRenderThread () inline
Definition at line 170 of file datvideorender.h.
     {
         m_renderer = nullptr;
         m_stream = nullptr;
         m_renderingVideo = false;
     }
DATVideoRenderThread() [2/2]
DATVideoRenderThread::DATVideoRenderThread (DATVideoRender * renderer, DATVideostream * stream) inline
Definition at line 177 of file datvideorender.h.
     {
         m_renderer = renderer;
         m_stream = stream;
         m_renderingVideo = false;
     }
Member Function Documentation
run()
void DATVideoRenderThread::run () inline
Definition at line 191 of file datvideorender.h.
     {
         if (m_renderingVideo)
         {
             return;
         }
         if ((m_renderer == nullptr) || (m_stream == nullptr))
         {
             return;
         }
         m_renderingVideo = m_renderer->OpenStream(m_stream);
         if (!m_renderingVideo)
         {
             return;
         }
         while ((m_renderer->RenderStream()) && (m_renderingVideo == true))
         {
         }
         m_renderer->CloseStream(m_stream);
         m_renderingVideo = false;
     }
setStreamAndRenderer()
void DATVideoRenderThread::setStreamAndRenderer (DATVideoRender * renderer, DATVideostream * stream) inline
Definition at line 184 of file datvideorender.h.
Referenced by DATVDemod::PlayVideo().
     {
         m_renderer = renderer;
         m_stream = stream;
         m_renderingVideo = false;
     }
stopRendering()
void DATVideoRenderThread::stopRendering () inline
Definition at line 218 of file datvideorender.h.
Referenced by DATVDemod::PlayVideo(), and DATVDemod::~DATVDemod().
     {
         m_renderingVideo = false;
     }
Member Data Documentation
m_renderer
DATVideoRender* DATVideoRenderThread::m_renderer private
Definition at line 224 of file datvideorender.h.
m_renderingVideo
bool DATVideoRenderThread::m_renderingVideo private
Definition at line 226 of file datvideorender.h.
m_stream
DATVideostream* DATVideoRenderThread::m_stream private
Definition at line 225 of file datvideorender.h.
The documentation for this class was generated from the following file:
plugins/channelrx/demoddatv/datvideorender.h