SDRAngel: qrtplib::RTPNTPTime Class Reference
qrtplib::RTPNTPTime Class Reference
#include <rtptimeutilities.h>
Public Member Functions
RTPNTPTime (uint32_t m, uint32_t l)
uint32_t GetMSW () const
uint32_t GetLSW () const
Private Attributes
uint32_t msw
uint32_t lsw
Detailed Description
This is a simple wrapper for the most significant word (MSW) and least significant word (LSW) of an NTP timestamp.
Definition at line 74 of file rtptimeutilities.h.
Constructor & Destructor Documentation
RTPNTPTime()
qrtplib::RTPNTPTime::RTPNTPTime (uint32_t m, uint32_t l) inline
This constructor creates and instance with MSW m and LSW l.
Definition at line 78 of file rtptimeutilities.h.
     {
         msw = m;
         lsw = l;
     }
Member Function Documentation
GetLSW()
uint32_t qrtplib::RTPNTPTime::GetLSW () const inline
Returns the least significant word.
Definition at line 91 of file rtptimeutilities.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks(), qrtplib::RTPSourceData::INF_GetRoundtripTime(), qrtplib::RTPTime::RTPTime(), and qrtplib::RTCPCompoundPacketBuilder::StartSenderReport().
     {
         return lsw;
     }
GetMSW()
uint32_t qrtplib::RTPNTPTime::GetMSW () const inline
Returns the most significant word.
Definition at line 85 of file rtptimeutilities.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks(), qrtplib::RTPSourceData::INF_GetRoundtripTime(), qrtplib::RTPTime::RTPTime(), and qrtplib::RTCPCompoundPacketBuilder::StartSenderReport().
     {
         return msw;
     }
Member Data Documentation
lsw
uint32_t qrtplib::RTPNTPTime::lsw private
Definition at line 96 of file rtptimeutilities.h.
msw
uint32_t qrtplib::RTPNTPTime::msw private
Definition at line 96 of file rtptimeutilities.h.
The documentation for this class was generated from the following file:
qrtplib/rtptimeutilities.h