SDRAngel: FileInput Class Reference
FileInput Class Reference
#include <fileinput.h>
Classes
class MsgConfigureFileInput
class MsgConfigureFileInputStreamTiming
class MsgConfigureFileInputWork
class MsgConfigureFileSourceName
class MsgConfigureFileSourceSeek
class MsgPlayPause
class MsgReportFileInputStreamData
class MsgReportFileInputStreamTiming
class MsgReportFileSourceAcquisition
class MsgReportHeaderCRC
class MsgStartStop
Public Member Functions
FileInput (DeviceAPI *deviceAPI)
virtual ~FileInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
quint64 getStartingTimeStamp () const
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void openFileStream ()
void seekFileStream (int seekMillis)
bool applySettings (const FileInputSettings &settings, bool force=false)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const FileInputSettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const FileInputSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
FileInputSettings m_settings
std::ifstream m_ifstream
FileInputThread * m_fileInputThread
QString m_deviceDescription
QString m_fileName
int m_sampleRate
quint32 m_sampleSize
quint64 m_centerFrequency
quint64 m_recordLength
record length in seconds computed from file size
quint64 m_startingTimeStamp
QTimer m_masterTimer
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 38 of file fileinput.h.
Constructor & Destructor Documentation
FileInput()
FileInput::FileInput (DeviceAPI * deviceAPI)
Definition at line 52 of file fileinput.cpp.
Referenced by FileInput::MsgReportHeaderCRC::MsgReportHeaderCRC().
                                          :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_fileInputThread(nullptr),
     m_deviceDescription(),
     m_fileName("..."),
     m_sampleRate(0),
     m_sampleSize(0),
     m_centerFrequency(0),
     m_recordLength(0),
     m_startingTimeStamp(0)
 {
     m_deviceAPI->setNbSourceStreams(1);
     qDebug("FileInput::FileInput: device source engine: %p", m_deviceAPI->getDeviceSourceEngine());
     qDebug("FileInput::FileInput: device source engine message queue: %p", m_deviceAPI->getDeviceEngineInputMessageQueue());
     qDebug("FileInput::FileInput: device source: %p", m_deviceAPI->getDeviceSourceEngine()->getSource());
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     m_masterTimer.setTimerType(Qt::PreciseTimer);
     m_masterTimer.start(50);
 }
~FileInput()
FileInput::~FileInput () virtual
Definition at line 74 of file fileinput.cpp.
References m_masterTimer, m_networkManager, networkManagerFinished(), and stop().
Referenced by FileInput::MsgReportHeaderCRC::MsgReportHeaderCRC().
 {
     m_masterTimer.stop();
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     stop();
 }
Member Function Documentation
applySettings()
bool FileInput::applySettings (const FileInputSettings & settings, bool force = false) private
Definition at line 406 of file fileinput.cpp.
References FileInputSettings::m_accelerationFactor, FileInputSettings::m_centerFrequency, m_centerFrequency, m_fileInputThread, FileInputSettings::m_fileName, FileInputSettings::m_loop, m_mutex, FileInputSettings::m_reverseAPIAddress, FileInputSettings::m_reverseAPIDeviceIndex, FileInputSettings::m_reverseAPIPort, DeviceSampleSource::m_sampleFifo, m_sampleRate, m_sampleSize, m_settings, FileInputSettings::m_useReverseAPI, FileInputThread::setSampleRateAndSize(), SampleSinkFifo::setSize(), and webapiReverseSendSettings().
Referenced by handleMessage().
 {
     QList<QString> reverseAPIKeys;
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency) || force) {
         m_centerFrequency = settings.m_centerFrequency;
     }
     if ((m_settings.m_accelerationFactor != settings.m_accelerationFactor) || force)
     {
         reverseAPIKeys.append("accelerationFactor");
         if (m_fileInputThread)
         {
             QMutexLocker mutexLocker(&m_mutex);
             if (!m_sampleFifo.setSize(m_settings.m_accelerationFactor * m_sampleRate * sizeof(Sample))) {
                 qCritical("FileInput::applySettings: could not reallocate sample FIFO size to %lu",
                         m_settings.m_accelerationFactor * m_sampleRate * sizeof(Sample));
             }
             m_fileInputThread->setSampleRateAndSize(settings.m_accelerationFactor * m_sampleRate, m_sampleSize); // Fast Forward: 1 corresponds to live. 1/2 is half speed, 2 is double speed
         }
     }
     if ((m_settings.m_loop != settings.m_loop)) {
         reverseAPIKeys.append("loop");
     }
     if ((m_settings.m_fileName != settings.m_fileName)) {
         reverseAPIKeys.append("fileName");
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     return true;
 }
deserialize()
bool FileInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 238 of file fileinput.cpp.
References FileInput::MsgConfigureFileInput::create(), FileInputSettings::deserialize(), DeviceSampleSource::getMessageQueueToGUI(), DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and FileInputSettings::resetToDefaults().
Referenced by FileInput::MsgReportHeaderCRC::MsgReportHeaderCRC().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureFileInput* message = MsgConfigureFileInput::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (getMessageQueueToGUI())
     {
         MsgConfigureFileInput* messageToGUI = MsgConfigureFileInput::create(m_settings, true);
         getMessageQueueToGUI()->push(messageToGUI);
     }
     return success;
 }
destroy()
void FileInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 83 of file fileinput.cpp.
Referenced by FileInput::MsgReportHeaderCRC::MsgReportHeaderCRC().
 {
     delete this;
 }
getCenterFrequency()
quint64 FileInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 270 of file fileinput.cpp.
References m_centerFrequency.
Referenced by setSampleRate().
 {
     return m_centerFrequency;
 }
getDeviceDescription()
const QString & FileInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 260 of file fileinput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getSampleRate()
int FileInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 265 of file fileinput.cpp.
References m_sampleRate.
Referenced by setMessageQueueToGUI().
 {
     return m_sampleRate;
 }
getStartingTimeStamp()
quint64 FileInput::getStartingTimeStamp () const
Definition at line 290 of file fileinput.cpp.
References m_startingTimeStamp.
Referenced by setSampleRate().
 {
     return m_startingTimeStamp;
 }
handleMessage()
bool FileInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 295 of file fileinput.cpp.
References applySettings(), FileInput::MsgPlayPause::create(), FileInput::MsgReportFileInputStreamTiming::create(), FileInput::MsgConfigureFileSourceName::getFileName(), DeviceSampleSource::getMessageQueueToGUI(), FileInput::MsgConfigureFileSourceSeek::getMillis(), FileInputThread::getSamplesCount(), FileInput::MsgConfigureFileInput::getSettings(), FileInput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), FileInput::MsgConfigureFileInputWork::isWorking(), m_deviceAPI, m_fileInputThread, m_fileName, FileInputSettings::m_loop, m_settings, FileInputSettings::m_useReverseAPI, Message::match(), openFileStream(), MessageQueue::push(), seekFileStream(), DeviceAPI::startDeviceEngine(), FileInputThread::startWork(), DeviceAPI::stopDeviceEngine(), FileInputThread::stopWork(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (MsgConfigureFileInput::match(message))
     {
         MsgConfigureFileInput& conf = (MsgConfigureFileInput&) message;
         FileInputSettings settings = conf.getSettings();
         applySettings(settings);
         return true;
     }
     else if (MsgConfigureFileSourceName::match(message))
     {
         MsgConfigureFileSourceName& conf = (MsgConfigureFileSourceName&) message;
         m_fileName = conf.getFileName();
         openFileStream();
         return true;
     }
     else if (MsgConfigureFileInputWork::match(message))
     {
         MsgConfigureFileInputWork& conf = (MsgConfigureFileInputWork&) message;
         bool working = conf.isWorking();
         if (m_fileInputThread != 0)
         {
             if (working) {
                 m_fileInputThread->startWork();
             } else {
                 m_fileInputThread->stopWork();
             }
         }
         return true;
     }
     else if (MsgConfigureFileSourceSeek::match(message))
     {
         MsgConfigureFileSourceSeek& conf = (MsgConfigureFileSourceSeek&) message;
         int seekMillis = conf.getMillis();
         seekFileStream(seekMillis);
         return true;
     }
     else if (MsgConfigureFileInputStreamTiming::match(message))
     {
         MsgReportFileInputStreamTiming *report;
         if (m_fileInputThread != 0)
         {
             if (getMessageQueueToGUI())
             {
                 report = MsgReportFileInputStreamTiming::create(m_fileInputThread->getSamplesCount());
                 getMessageQueueToGUI()->push(report);
             }
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "FileInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else if (FileInputThread::MsgReportEOF::match(message))
     {
         qDebug() << "FileInput::handleMessage: MsgReportEOF";
         m_fileInputThread->stopWork();
         if (getMessageQueueToGUI())
         {
             MsgReportFileInputStreamTiming *report = MsgReportFileInputStreamTiming::create(m_fileInputThread->getSamplesCount());
             getMessageQueueToGUI()->push(report);
         }
         if (m_settings.m_loop)
         {
             seekFileStream(0);
             m_fileInputThread->startWork();
         }
         else
         {
             if (getMessageQueueToGUI())
             {
                 MsgPlayPause *report = MsgPlayPause::create(false);
                 getMessageQueueToGUI()->push(report);
             }
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void FileInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 170 of file fileinput.cpp.
References DeviceAPI::getDeviceEngineInputMessageQueue(), FileInputSettings::m_centerFrequency, m_deviceAPI, FileInputSettings::m_sampleRate, m_settings, and MessageQueue::push().
Referenced by FileInput::MsgReportHeaderCRC::MsgReportHeaderCRC().
 {
     DSPSignalNotification *notif = new DSPSignalNotification(m_settings.m_sampleRate, m_settings.m_centerFrequency);
     m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
 }
networkManagerFinished
void FileInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 664 of file fileinput.cpp.
Referenced by ~FileInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "FileInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("FileInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openFileStream()
void FileInput::openFileStream () private
Definition at line 88 of file fileinput.cpp.
References FileRecord::Header::centerFrequency, FileRecord::Header::crc32, FileInput::MsgReportFileInputStreamData::create(), FileInput::MsgReportHeaderCRC::create(), DeviceSampleSource::getMessageQueueToGUI(), m_centerFrequency, m_fileName, m_ifstream, m_recordLength, m_sampleRate, m_sampleSize, m_startingTimeStamp, MessageQueue::push(), FileRecord::readHeader(), FileRecord::Header::sampleRate, FileRecord::Header::sampleSize, and FileRecord::Header::startTimeStamp.
Referenced by handleMessage().
 {
     //stopInput();
     if (m_ifstream.is_open()) {
         m_ifstream.close();
     }
 #ifdef Q_OS_WIN
     m_ifstream.open(m_fileName.toStdWString().c_str(), std::ios::binary | std::ios::ate);
 #else
     m_ifstream.open(m_fileName.toStdString().c_str(), std::ios::binary | std::ios::ate);
 #endif
     quint64 fileSize = m_ifstream.tellg();
     if (fileSize > sizeof(FileRecord::Header))
     {
         FileRecord::Header header;
         m_ifstream.seekg(0,std::ios_base::beg);
         bool crcOK = FileRecord::readHeader(m_ifstream, header);
         m_sampleRate = header.sampleRate;
         m_centerFrequency = header.centerFrequency;
         m_startingTimeStamp = header.startTimeStamp;
         m_sampleSize = header.sampleSize;
         QString crcHex = QString("%1").arg(header.crc32 , 0, 16);
         if (crcOK)
         {
             qDebug("FileInput::openFileStream: CRC32 OK for header: %s", qPrintable(crcHex));
             m_recordLength = (fileSize - sizeof(FileRecord::Header)) / ((m_sampleSize == 24 ? 8 : 4) * m_sampleRate);
         }
         else
         {
             qCritical("FileInput::openFileStream: bad CRC32 for header: %s", qPrintable(crcHex));
             m_recordLength = 0;
         }
         if (getMessageQueueToGUI()) {
             MsgReportHeaderCRC *report = MsgReportHeaderCRC::create(crcOK);
             getMessageQueueToGUI()->push(report);
         }
     }
     else
     {
         m_recordLength = 0;
     }
     qDebug() << "FileInput::openFileStream: " << m_fileName.toStdString().c_str()
             << " fileSize: " << fileSize << " bytes"
             << " length: " << m_recordLength << " seconds"
             << " sample rate: " << m_sampleRate << " S/s"
             << " center frequency: " << m_centerFrequency << " Hz"
             << " sample size: " << m_sampleSize << " bits";
     if (getMessageQueueToGUI()) {
         MsgReportFileInputStreamData *report = MsgReportFileInputStreamData::create(m_sampleRate,
                 m_sampleSize,
                 m_centerFrequency,
                 m_startingTimeStamp,
                 m_recordLength); // file stream data
         getMessageQueueToGUI()->push(report);
     }
     if (m_recordLength == 0) {
         m_ifstream.close();
     }
 }
seekFileStream()
void FileInput::seekFileStream (int seekMillis) private
Definition at line 156 of file fileinput.cpp.
References FileInputThread::isRunning(), m_fileInputThread, m_ifstream, m_mutex, m_recordLength, m_sampleRate, m_sampleSize, and FileInputThread::setSamplesCount().
Referenced by handleMessage().
 {
     QMutexLocker mutexLocker(&m_mutex);
     if ((m_ifstream.is_open()) && m_fileInputThread && !m_fileInputThread->isRunning())
     {
         quint64 seekPoint = ((m_recordLength * seekMillis) / 1000) * m_sampleRate;
         m_fileInputThread->setSamplesCount(seekPoint);
         seekPoint *= (m_sampleSize == 24 ? 8 : 4); // + sizeof(FileSink::Header)
         m_ifstream.clear();
         m_ifstream.seekg(seekPoint + sizeof(FileRecord::Header), std::ios::beg);
     }
 }
serialize()
QByteArray FileInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 233 of file fileinput.cpp.
References m_settings, and FileInputSettings::serialize().
Referenced by FileInput::MsgReportHeaderCRC::MsgReportHeaderCRC().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void FileInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 275 of file fileinput.cpp.
References FileInput::MsgConfigureFileInput::create(), DeviceSampleSource::getMessageQueueToGUI(), FileInputSettings::m_centerFrequency, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     FileInputSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureFileInput* message = MsgConfigureFileInput::create(m_settings, false);
     m_inputMessageQueue.push(message);
     if (getMessageQueueToGUI())
     {
         MsgConfigureFileInput* messageToGUI = MsgConfigureFileInput::create(m_settings, false);
         getMessageQueueToGUI()->push(messageToGUI);
     }
 }
setMessageQueueToGUI()
virtual void FileInput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 289 of file fileinput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSource::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void FileInput::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 292 of file fileinput.h.
References getCenterFrequency(), getStartingTimeStamp(), handleMessage(), setCenterFrequency(), webapiReportGet(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
start()
bool FileInput::start () virtual
Implements DeviceSampleSource.
Definition at line 176 of file fileinput.cpp.
References FileInput::MsgReportFileSourceAcquisition::create(), DeviceSampleSource::getMessageQueueToGUI(), FileInputSettings::m_accelerationFactor, m_deviceDescription, m_fileInputThread, m_ifstream, DeviceSampleSource::m_inputMessageQueue, m_masterTimer, m_mutex, DeviceSampleSource::m_sampleFifo, m_sampleRate, m_sampleSize, m_settings, MessageQueue::push(), FileInputThread::setSampleRateAndSize(), SampleSinkFifo::setSize(), and FileInputThread::startWork().
Referenced by FileInput::MsgReportHeaderCRC::MsgReportHeaderCRC().
 {
     if (!m_ifstream.is_open())
     {
         qWarning("FileInput::start: file not open. not starting");
         return false;
     }
     QMutexLocker mutexLocker(&m_mutex);
     qDebug() << "FileInput::start";
     if (m_ifstream.tellg() != (std::streampos)0) {
         m_ifstream.clear();
         m_ifstream.seekg(sizeof(FileRecord::Header), std::ios::beg);
     }
     if(!m_sampleFifo.setSize(m_settings.m_accelerationFactor * m_sampleRate * sizeof(Sample))) {
         qCritical("Could not allocate SampleFifo");
         return false;
     }
     m_fileInputThread = new FileInputThread(&m_ifstream, &m_sampleFifo, m_masterTimer, &m_inputMessageQueue);
     m_fileInputThread->setSampleRateAndSize(m_settings.m_accelerationFactor * m_sampleRate, m_sampleSize); // Fast Forward: 1 corresponds to live. 1/2 is half speed, 2 is double speed
     m_fileInputThread->startWork();
     m_deviceDescription = "FileInput";
     mutexLocker.unlock();
     qDebug("FileInput::startInput: started");
     if (getMessageQueueToGUI()) {
         MsgReportFileSourceAcquisition *report = MsgReportFileSourceAcquisition::create(true); // acquisition on
         getMessageQueueToGUI()->push(report);
     }
     return true;
 }
stop()
void FileInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 213 of file fileinput.cpp.
References FileInput::MsgReportFileSourceAcquisition::create(), DeviceSampleSource::getMessageQueueToGUI(), m_deviceDescription, m_fileInputThread, m_mutex, MessageQueue::push(), and FileInputThread::stopWork().
Referenced by FileInput::MsgReportHeaderCRC::MsgReportHeaderCRC(), and ~FileInput().
 {
     qDebug() << "FileInput::stop";
     QMutexLocker mutexLocker(&m_mutex);
     if (m_fileInputThread)
     {
         m_fileInputThread->stopWork();
         delete m_fileInputThread;
         m_fileInputThread = nullptr;
     }
     m_deviceDescription.clear();
     if (getMessageQueueToGUI()) {
         MsgReportFileSourceAcquisition *report = MsgReportFileSourceAcquisition::create(false); // acquisition off
         getMessageQueueToGUI()->push(report);
     }
 }
webapiFormatDeviceReport()
void FileInput::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 561 of file fileinput.cpp.
References SWGSDRangel::SWGDeviceReport::getFileInputReport(), FileInputThread::getSamplesCount(), m_fileInputThread, m_fileName, m_recordLength, m_sampleRate, m_sampleSize, m_startingTimeStamp, SWGSDRangel::SWGFileInputReport::setAbsoluteTime(), SWGSDRangel::SWGFileInputReport::setDurationTime(), SWGSDRangel::SWGFileInputReport::setElapsedTime(), SWGSDRangel::SWGFileInputReport::setFileName(), SWGSDRangel::SWGFileInputReport::setSampleRate(), and SWGSDRangel::SWGFileInputReport::setSampleSize().
Referenced by webapiReportGet().
 {
     qint64 t_sec = 0;
     qint64 t_msec = 0;
     quint64 samplesCount = 0;
     if (m_fileInputThread) {
         samplesCount = m_fileInputThread->getSamplesCount();
     }
     if (m_sampleRate > 0)
     {
         t_sec = samplesCount / m_sampleRate;
         t_msec = (samplesCount - (t_sec * m_sampleRate)) * 1000 / m_sampleRate;
     }
     QTime t(0, 0, 0, 0);
     t = t.addSecs(t_sec);
     t = t.addMSecs(t_msec);
     response.getFileInputReport()->setElapsedTime(new QString(t.toString("HH:mm:ss.zzz")));
     qint64 startingTimeStampMsec = m_startingTimeStamp * 1000LL;
     QDateTime dt = QDateTime::fromMSecsSinceEpoch(startingTimeStampMsec);
     dt = dt.addSecs(t_sec);
     dt = dt.addMSecs(t_msec);
     response.getFileInputReport()->setAbsoluteTime(new QString(dt.toString("yyyy-MM-dd HH:mm:ss.zzz")));
     QTime recordLength(0, 0, 0, 0);
     recordLength = recordLength.addSecs(m_recordLength);
     response.getFileInputReport()->setDurationTime(new QString(recordLength.toString("HH:mm:ss")));
     response.getFileInputReport()->setFileName(new QString(m_fileName));
     response.getFileInputReport()->setSampleRate(m_sampleRate);
     response.getFileInputReport()->setSampleSize(m_sampleSize);
 }
webapiFormatDeviceSettings()
void FileInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const FileInputSettings & settings) private
Definition at line 543 of file fileinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getFileInputSettings(), SWGSDRangel::SWGFileInputSettings::getReverseApiAddress(), FileInputSettings::m_accelerationFactor, FileInputSettings::m_fileName, FileInputSettings::m_loop, FileInputSettings::m_reverseAPIAddress, FileInputSettings::m_reverseAPIDeviceIndex, FileInputSettings::m_reverseAPIPort, FileInputSettings::m_useReverseAPI, SWGSDRangel::SWGFileInputSettings::setAccelerationFactor(), SWGSDRangel::SWGFileInputSettings::setFileName(), SWGSDRangel::SWGFileInputSettings::setLoop(), SWGSDRangel::SWGFileInputSettings::setReverseApiAddress(), SWGSDRangel::SWGFileInputSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGFileInputSettings::setReverseApiPort(), and SWGSDRangel::SWGFileInputSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getFileInputSettings()->setFileName(new QString(settings.m_fileName));
     response.getFileInputSettings()->setAccelerationFactor(settings.m_accelerationFactor);
     response.getFileInputSettings()->setLoop(settings.m_loop ? 1 : 0);
     response.getFileInputSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getFileInputSettings()->getReverseApiAddress()) {
         *response.getFileInputSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getFileInputSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getFileInputSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getFileInputSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int FileInput::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 532 of file fileinput.cpp.
References SWGSDRangel::SWGDeviceReport::getFileInputReport(), SWGSDRangel::SWGFileInputReport::init(), SWGSDRangel::SWGDeviceReport::setFileInputReport(), and webapiFormatDeviceReport().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setFileInputReport(new SWGSDRangel::SWGFileInputReport());
     response.getFileInputReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void FileInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const FileInputSettings & settings, bool force) private
Definition at line 597 of file fileinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getFileInputSettings(), FileInputSettings::m_accelerationFactor, m_deviceAPI, FileInputSettings::m_fileName, FileInputSettings::m_loop, m_networkManager, m_networkRequest, FileInputSettings::m_reverseAPIAddress, FileInputSettings::m_reverseAPIDeviceIndex, FileInputSettings::m_reverseAPIPort, SWGSDRangel::SWGFileInputSettings::setAccelerationFactor(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGDeviceSettings::setFileInputSettings(), SWGSDRangel::SWGFileInputSettings::setFileName(), SWGSDRangel::SWGFileInputSettings::setLoop(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("FileInput"));
     swgDeviceSettings->setFileInputSettings(new SWGSDRangel::SWGFileInputSettings());
     SWGSDRangel::SWGFileInputSettings *swgFileInputSettings = swgDeviceSettings->getFileInputSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("accelerationFactor") || force) {
         swgFileInputSettings->setAccelerationFactor(settings.m_accelerationFactor);
     }
     if (deviceSettingsKeys.contains("loop") || force) {
         swgFileInputSettings->setLoop(settings.m_loop);
     }
     if (deviceSettingsKeys.contains("fileName") || force) {
         swgFileInputSettings->setFileName(new QString(settings.m_fileName));
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void FileInput::webapiReverseSendStartStop (bool start) private
Definition at line 636 of file fileinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, FileInputSettings::m_reverseAPIAddress, FileInputSettings::m_reverseAPIDeviceIndex, FileInputSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("FileInput"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int FileInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 513 of file fileinput.cpp.
References FileInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), DeviceSampleSource::getMessageQueueToGUI(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (getMessageQueueToGUI()) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         getMessageQueueToGUI()->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int FileInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 504 of file fileinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int FileInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 449 of file fileinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getFileInputSettings(), SWGSDRangel::SWGFileInputSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setFileInputSettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setFileInputSettings(new SWGSDRangel::SWGFileInputSettings());
     response.getFileInputSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int FileInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 460 of file fileinput.cpp.
References FileInput::MsgConfigureFileInput::create(), SWGSDRangel::SWGFileInputSettings::getAccelerationFactor(), SWGSDRangel::SWGDeviceSettings::getFileInputSettings(), SWGSDRangel::SWGFileInputSettings::getFileName(), SWGSDRangel::SWGFileInputSettings::getLoop(), SWGSDRangel::SWGFileInputSettings::getReverseApiAddress(), SWGSDRangel::SWGFileInputSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGFileInputSettings::getReverseApiPort(), SWGSDRangel::SWGFileInputSettings::getUseReverseApi(), FileInputSettings::m_accelerationFactor, FileInputSettings::m_fileName, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, FileInputSettings::m_loop, FileInputSettings::m_reverseAPIAddress, FileInputSettings::m_reverseAPIDeviceIndex, FileInputSettings::m_reverseAPIPort, m_settings, FileInputSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     FileInputSettings settings = m_settings;
     if (deviceSettingsKeys.contains("fileName")) {
         settings.m_fileName = *response.getFileInputSettings()->getFileName();
     }
     if (deviceSettingsKeys.contains("accelerationFactor")) {
         settings.m_accelerationFactor = response.getFileInputSettings()->getAccelerationFactor();
     }
     if (deviceSettingsKeys.contains("loop")) {
         settings.m_loop = response.getFileInputSettings()->getLoop() != 0;
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getFileInputSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getFileInputSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getFileInputSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getFileInputSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureFileInput *msg = MsgConfigureFileInput::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureFileInput *msgToGUI = MsgConfigureFileInput::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_centerFrequency
quint64 FileInput::m_centerFrequency private
Definition at line 332 of file fileinput.h.
Referenced by applySettings(), FileInput::MsgReportFileInputStreamData::getCenterFrequency(), getCenterFrequency(), and openFileStream().
m_deviceAPI
DeviceAPI* FileInput::m_deviceAPI private
Definition at line 323 of file fileinput.h.
Referenced by handleMessage(), init(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), and webapiRunGet().
m_deviceDescription
QString FileInput::m_deviceDescription private
Definition at line 328 of file fileinput.h.
Referenced by getDeviceDescription(), start(), and stop().
m_fileInputThread
FileInputThread* FileInput::m_fileInputThread private
Definition at line 327 of file fileinput.h.
Referenced by applySettings(), handleMessage(), seekFileStream(), start(), stop(), and webapiFormatDeviceReport().
m_fileName
QString FileInput::m_fileName private
Definition at line 329 of file fileinput.h.
Referenced by FileInput::MsgConfigureFileSourceName::getFileName(), handleMessage(), openFileStream(), and webapiFormatDeviceReport().
m_ifstream
std::ifstream FileInput::m_ifstream private
Definition at line 326 of file fileinput.h.
Referenced by openFileStream(), seekFileStream(), and start().
m_masterTimer
QTimer FileInput::m_masterTimer private
Definition at line 335 of file fileinput.h.
Referenced by start(), and ~FileInput().
m_mutex
QMutex FileInput::m_mutex private
Definition at line 324 of file fileinput.h.
Referenced by applySettings(), seekFileStream(), start(), and stop().
m_networkManager
QNetworkAccessManager* FileInput::m_networkManager private
Definition at line 336 of file fileinput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~FileInput().
m_networkRequest
QNetworkRequest FileInput::m_networkRequest private
Definition at line 337 of file fileinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_recordLength
quint64 FileInput::m_recordLength private
record length in seconds computed from file size
Definition at line 333 of file fileinput.h.
Referenced by FileInput::MsgReportFileInputStreamData::getRecordLength(), openFileStream(), seekFileStream(), and webapiFormatDeviceReport().
m_sampleRate
int FileInput::m_sampleRate private
Definition at line 330 of file fileinput.h.
Referenced by applySettings(), FileInput::MsgReportFileInputStreamData::getSampleRate(), getSampleRate(), openFileStream(), seekFileStream(), start(), and webapiFormatDeviceReport().
m_sampleSize
quint32 FileInput::m_sampleSize private
Definition at line 331 of file fileinput.h.
Referenced by applySettings(), FileInput::MsgReportFileInputStreamData::getSampleSize(), openFileStream(), seekFileStream(), start(), and webapiFormatDeviceReport().
m_settings
FileInputSettings FileInput::m_settings private
Definition at line 325 of file fileinput.h.
Referenced by applySettings(), deserialize(), handleMessage(), init(), serialize(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_startingTimeStamp
quint64 FileInput::m_startingTimeStamp private
Definition at line 334 of file fileinput.h.
Referenced by FileInput::MsgReportFileInputStreamData::getStartingTimeStamp(), getStartingTimeStamp(), openFileStream(), and webapiFormatDeviceReport().
The documentation for this class was generated from the following files:
plugins/samplesource/fileinput/fileinput.h
plugins/samplesource/fileinput/fileinput.cpp