SDRAngel: ComplexFactorGUI Class Reference
ComplexFactorGUI Class Reference
#include <complexfactorgui.h>
Inherits QWidget.
Signals
void moduleChanged (double value)
void argumentChanged (double value)
void automaticChanged (bool value)
Public Member Functions
ComplexFactorGUI (QWidget *parent=0)
~ComplexFactorGUI ()
double getModule () const
double getArgument () const
bool getAutomatic () const
void setModule (double value)
void setArgument (double value)
void setAutomatic (bool automatic)
void setAutomaticEnable (bool enable)
void setLabel (const QString &text)
void setToolTip (const QString &text)
Private Slots
void on_automatic_toggled (bool set)
void on_module_valueChanged (int value)
void on_arg_valueChanged (int value)
Private Attributes
Ui::ComplexFactorGUI * ui
Detailed Description
Definition at line 34 of file complexfactorgui.h.
Constructor & Destructor Documentation
ComplexFactorGUI()
ComplexFactorGUI::ComplexFactorGUI (QWidget * parent = 0) explicit
Definition at line 21 of file complexfactorgui.cpp.
References ui.
                                                   :
     QWidget(parent),
     ui(new Ui::ComplexFactorGUI)
 {
     ui->setupUi(this);
     ui->automatic->setChecked(false);
 }
~ComplexFactorGUI()
ComplexFactorGUI::~ComplexFactorGUI ()
Definition at line 29 of file complexfactorgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
argumentChanged
void ComplexFactorGUI::argumentChanged (double value) signal
Referenced by on_arg_valueChanged().
automaticChanged
void ComplexFactorGUI::automaticChanged (bool value) signal
Referenced by on_automatic_toggled().
getArgument()
double ComplexFactorGUI::getArgument () const
Definition at line 39 of file complexfactorgui.cpp.
References ui.
 {
     return ui->arg->value() * 1.0;
 }
getAutomatic()
bool ComplexFactorGUI::getAutomatic () const
Definition at line 44 of file complexfactorgui.cpp.
References ui.
 {
     return ui->automatic->isChecked();
 }
getModule()
double ComplexFactorGUI::getModule () const
Definition at line 34 of file complexfactorgui.cpp.
References ui.
 {
     return ui->module->value() / 100.0;
 }
moduleChanged
void ComplexFactorGUI::moduleChanged (double value) signal
Referenced by on_module_valueChanged().
on_arg_valueChanged
void ComplexFactorGUI::on_arg_valueChanged (int value) private slot
Definition at line 96 of file complexfactorgui.cpp.
References arg(), argumentChanged(), and ui.
 {
     ui->argText->setText(tr("%1").arg(value));
     emit argumentChanged(value);
 }
on_automatic_toggled
void ComplexFactorGUI::on_automatic_toggled (bool set) private slot
Definition at line 83 of file complexfactorgui.cpp.
References automaticChanged(), and ui.
 {
     ui->module->setEnabled(!set);
     ui->arg->setEnabled(!set);
     emit automaticChanged(set);
 }
on_module_valueChanged
void ComplexFactorGUI::on_module_valueChanged (int value) private slot
Definition at line 90 of file complexfactorgui.cpp.
References arg(), moduleChanged(), and ui.
 {
     ui->moduleText->setText(tr("%1").arg(value/100.0f, 0, 'f', 2));
     emit moduleChanged(value/100.0f);
 }
setArgument()
void ComplexFactorGUI::setArgument (double value)
Definition at line 56 of file complexfactorgui.cpp.
References arg(), and ui.
Referenced by SoapySDRInputGui::displayCorrectionsSettings(), and SoapySDROutputGui::displayCorrectionsSettings().
 {
     int argValue = (int) (value < -180.0 ? -180.0 : value > 180.0 ? 180.0 : value);
     ui->arg->setValue(argValue);
     ui->argText->setText(tr("%1").arg(value));
 }
setAutomatic()
void ComplexFactorGUI::setAutomatic (bool automatic)
Definition at line 63 of file complexfactorgui.cpp.
References ui.
Referenced by SoapySDRInputGui::displayCorrectionsSettings(), and SoapySDROutputGui::displayCorrectionsSettings().
 {
     ui->automatic->setChecked(automatic);
 }
setAutomaticEnable()
void ComplexFactorGUI::setAutomaticEnable (bool enable)
Definition at line 68 of file complexfactorgui.cpp.
References ui.
Referenced by SoapySDRInputGui::createCorrectionsControl(), and SoapySDROutputGui::createCorrectionsControl().
 {
     ui->automatic->setEnabled(enable);
 }
setLabel()
void ComplexFactorGUI::setLabel (const QString & text)
Definition at line 73 of file complexfactorgui.cpp.
References ui.
Referenced by SoapySDRInputGui::createCorrectionsControl(), and SoapySDROutputGui::createCorrectionsControl().
 {
     ui->label->setText(text);
 }
setModule()
void ComplexFactorGUI::setModule (double value)
Definition at line 49 of file complexfactorgui.cpp.
References arg(), and ui.
Referenced by SoapySDRInputGui::displayCorrectionsSettings(), and SoapySDROutputGui::displayCorrectionsSettings().
 {
     double modValue = value < -1.0 ? -1.0 : value > 1.0 ? 1.0 : value;
     ui->module->setValue((int) modValue*100.0f);
     ui->moduleText->setText(tr("%1").arg(modValue, 0, 'f', 2));
 }
setToolTip()
void ComplexFactorGUI::setToolTip (const QString & text)
Definition at line 78 of file complexfactorgui.cpp.
References ui.
Referenced by SoapySDRInputGui::createCorrectionsControl().
 {
     ui->label->setToolTip(text);
 }
Member Data Documentation
ui
Ui::ComplexFactorGUI* ComplexFactorGUI::ui private
Definition at line 64 of file complexfactorgui.h.
Referenced by ComplexFactorGUI(), getArgument(), getAutomatic(), getModule(), on_arg_valueChanged(), on_automatic_toggled(), on_module_valueChanged(), setArgument(), setAutomatic(), setAutomaticEnable(), setLabel(), setModule(), setToolTip(), and ~ComplexFactorGUI().
The documentation for this class was generated from the following files:
sdrgui/soapygui/complexfactorgui.h
sdrgui/soapygui/complexfactorgui.cpp