SDRAngel: StepFunctions Class Reference
StepFunctions Class Reference
#include <stepfunctions.h>
Static Public Member Functions
static float smootherstep (float x)
Detailed Description
Definition at line 21 of file stepfunctions.h.
Member Function Documentation
smootherstep()
static float StepFunctions::smootherstep (float x) inline static
Definition at line 24 of file stepfunctions.h.
Referenced by MagAGC::feedAndGetValue(), MagAGC::getStepValue(), AMDemod::processOneSample(), and CWSmoother::setNbFadeSamples().
     {
         if (x == 1.0f) {
             return 1.0f;
         } else if (x == 0.0f) {
             return 0.0f;
         }
         double x3 = x * x * x;
         double x4 = x * x3;
         double x5 = x * x4;
         return (float) (6.0*x5 - 15.0*x4 + 10.0*x3);
     }
The documentation for this class was generated from the following file:
sdrbase/util/stepfunctions.h