SDRAngel: UpChannelizer::FilterStage Struct Reference
UpChannelizer::FilterStage Struct Reference
#include <upchannelizer.h>
Public Types
enum Mode { ModeCenter, ModeLowerHalf, ModeUpperHalf }
typedef bool(IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::* WorkFunction) (Sample *sIn, Sample *sOut)
Public Member Functions
FilterStage (Mode mode)
~FilterStage ()
bool work (Sample *sampleIn, Sample *sampleOut)
Public Attributes
IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER > * m_filter
WorkFunction m_workFunction
Detailed Description
Definition at line 99 of file upchannelizer.h.
Member Typedef Documentation
WorkFunction
typedef bool(IntHalfbandFilterDB<qint32, UPCHANNELIZER_HB_FILTER_ORDER>::* UpChannelizer::FilterStage::WorkFunction) (Sample *sIn, Sample *sOut)
Definition at line 110 of file upchannelizer.h.
Member Enumeration Documentation
Mode
enum UpChannelizer::FilterStage::Mode
Enumerator
ModeCenter
ModeLowerHalf
ModeUpperHalf
Definition at line 100 of file upchannelizer.h.
                   {
             ModeCenter,
             ModeLowerHalf,
             ModeUpperHalf
         };
Constructor & Destructor Documentation
FilterStage()
UpChannelizer::FilterStage::FilterStage (Mode mode)
Definition at line 280 of file upchannelizer.cpp.
References m_workFunction, ModeCenter, ModeLowerHalf, and ModeUpperHalf.
Referenced by UpChannelizer::applySetting(), UpChannelizer::createFilterChain(), and UpChannelizer::setFilterChain().
                                                :
     m_filter(new IntHalfbandFilterDB<qint32, UPCHANNELIZER_HB_FILTER_ORDER>),
     m_workFunction(0)
 {
     switch(mode) {
         case ModeCenter:
             m_workFunction = &IntHalfbandFilterDB<qint32, UPCHANNELIZER_HB_FILTER_ORDER>::workInterpolateCenter;
             break;
         case ModeLowerHalf:
             m_workFunction = &IntHalfbandFilterDB<qint32, UPCHANNELIZER_HB_FILTER_ORDER>::workInterpolateLowerHalf;
             break;
         case ModeUpperHalf:
             m_workFunction = &IntHalfbandFilterDB<qint32, UPCHANNELIZER_HB_FILTER_ORDER>::workInterpolateUpperHalf;
             break;
     }
 }
~FilterStage()
UpChannelizer::FilterStage::~FilterStage ()
Definition at line 300 of file upchannelizer.cpp.
References m_filter.
 {
     delete m_filter;
 }
Member Function Documentation
work()
bool UpChannelizer::FilterStage::work (Sample * sampleIn, Sample * sampleOut) inline
Definition at line 118 of file upchannelizer.h.
         {
             return (m_filter->*m_workFunction)(sampleIn, sampleOut);
         }
Member Data Documentation
m_filter
IntHalfbandFilterDB<qint32, UPCHANNELIZER_HB_FILTER_ORDER>* UpChannelizer::FilterStage::m_filter
Definition at line 111 of file upchannelizer.h.
Referenced by ~FilterStage().
m_workFunction
WorkFunction UpChannelizer::FilterStage::m_workFunction
Definition at line 113 of file upchannelizer.h.
Referenced by FilterStage().
The documentation for this struct was generated from the following files:
sdrbase/dsp/upchannelizer.h
sdrbase/dsp/upchannelizer.cpp