SDRAngel: SWGSDRangel::SWGBladeRF2InputReport Class Reference
SWGSDRangel::SWGBladeRF2InputReport Class Reference
#include <SWGBladeRF2InputReport.h>
Public Member Functions
SWGBladeRF2InputReport ()
SWGBladeRF2InputReport (QString *json)
virtual ~SWGBladeRF2InputReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGBladeRF2InputReport * fromJson (QString &jsonString) override
SWGFrequencyRange * getFrequencyRange ()
void setFrequencyRange (SWGFrequencyRange *frequency_range)
SWGRange * getSampleRateRange ()
void setSampleRateRange (SWGRange *sample_rate_range)
SWGRange * getBandwidthRange ()
void setBandwidthRange (SWGRange *bandwidth_range)
SWGRange * getGlobalGainRange ()
void setGlobalGainRange (SWGRange *global_gain_range)
QList< SWGNamedEnum * > * getGainModes ()
void setGainModes (QList< SWGNamedEnum *> *gain_modes)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
SWGFrequencyRange * frequency_range
bool m_frequency_range_isSet
SWGRange * sample_rate_range
bool m_sample_rate_range_isSet
SWGRange * bandwidth_range
bool m_bandwidth_range_isSet
SWGRange * global_gain_range
bool m_global_gain_range_isSet
QList< SWGNamedEnum * > * gain_modes
bool m_gain_modes_isSet
Detailed Description
Definition at line 35 of file SWGBladeRF2InputReport.h.
Constructor & Destructor Documentation
SWGBladeRF2InputReport() [1/2]
SWGSDRangel::SWGBladeRF2InputReport::SWGBladeRF2InputReport ()
Definition at line 30 of file SWGBladeRF2InputReport.cpp.
References bandwidth_range, frequency_range, gain_modes, global_gain_range, m_bandwidth_range_isSet, m_frequency_range_isSet, m_gain_modes_isSet, m_global_gain_range_isSet, m_sample_rate_range_isSet, and sample_rate_range.
{
     frequency_range = nullptr;
     m_frequency_range_isSet = false;
     sample_rate_range = nullptr;
     m_sample_rate_range_isSet = false;
     bandwidth_range = nullptr;
     m_bandwidth_range_isSet = false;
     global_gain_range = nullptr;
     m_global_gain_range_isSet = false;
     gain_modes = nullptr;
     m_gain_modes_isSet = false;
 }
SWGBladeRF2InputReport() [2/2]
SWGSDRangel::SWGBladeRF2InputReport::SWGBladeRF2InputReport (QString * json)
Definition at line 25 of file SWGBladeRF2InputReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGBladeRF2InputReport()
SWGSDRangel::SWGBladeRF2InputReport::~SWGBladeRF2InputReport () virtual
Definition at line 43 of file SWGBladeRF2InputReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGBladeRF2InputReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 108 of file SWGBladeRF2InputReport.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGBladeRF2InputReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 119 of file SWGBladeRF2InputReport.cpp.
References bandwidth_range, frequency_range, gain_modes, global_gain_range, SWGSDRangel::SWGFrequencyRange::isSet(), SWGSDRangel::SWGRange::isSet(), sample_rate_range, SWGSDRangel::toJsonArray(), and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if((frequency_range != nullptr) && (frequency_range->isSet())){
         toJsonValue(QString("frequencyRange"), frequency_range, obj, QString("SWGFrequencyRange"));
     }
     if((sample_rate_range != nullptr) && (sample_rate_range->isSet())){
         toJsonValue(QString("sampleRateRange"), sample_rate_range, obj, QString("SWGRange"));
     }
     if((bandwidth_range != nullptr) && (bandwidth_range->isSet())){
         toJsonValue(QString("bandwidthRange"), bandwidth_range, obj, QString("SWGRange"));
     }
     if((global_gain_range != nullptr) && (global_gain_range->isSet())){
         toJsonValue(QString("globalGainRange"), global_gain_range, obj, QString("SWGRange"));
     }
     if(gain_modes->size() > 0){
         toJsonArray((QList<void*>*)gain_modes, obj, "gainModes", "SWGNamedEnum");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGBladeRF2InputReport::cleanup ()
Definition at line 62 of file SWGBladeRF2InputReport.cpp.
References bandwidth_range, frequency_range, gain_modes, global_gain_range, and sample_rate_range.
Referenced by ~SWGBladeRF2InputReport().
{
     if(frequency_range != nullptr) {
         delete frequency_range;
     }
     if(sample_rate_range != nullptr) {
         delete sample_rate_range;
     }
     if(bandwidth_range != nullptr) {
         delete bandwidth_range;
     }
     if(global_gain_range != nullptr) {
         delete global_gain_range;
     }
     if(gain_modes != nullptr) {
         auto arr = gain_modes;
         for(auto o: *arr) {
             delete o;
         }
         delete gain_modes;
     }
 }
fromJson()
SWGBladeRF2InputReport * SWGSDRangel::SWGBladeRF2InputReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 85 of file SWGBladeRF2InputReport.cpp.
References fromJsonObject().
Referenced by SWGBladeRF2InputReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGBladeRF2InputReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 94 of file SWGBladeRF2InputReport.cpp.
References bandwidth_range, frequency_range, gain_modes, global_gain_range, sample_rate_range, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&frequency_range, pJson["frequencyRange"], "SWGFrequencyRange", "SWGFrequencyRange");
     ::SWGSDRangel::setValue(&sample_rate_range, pJson["sampleRateRange"], "SWGRange", "SWGRange");
     ::SWGSDRangel::setValue(&bandwidth_range, pJson["bandwidthRange"], "SWGRange", "SWGRange");
     ::SWGSDRangel::setValue(&global_gain_range, pJson["globalGainRange"], "SWGRange", "SWGRange");
     ::SWGSDRangel::setValue(&gain_modes, pJson["gainModes"], "QList", "SWGNamedEnum");
 }
getBandwidthRange()
SWGRange * SWGSDRangel::SWGBladeRF2InputReport::getBandwidthRange ()
Definition at line 161 of file SWGBladeRF2InputReport.cpp.
References bandwidth_range.
Referenced by BladeRF2Input::webapiFormatDeviceReport().
{
     return bandwidth_range;
 }
getFrequencyRange()
SWGFrequencyRange * SWGSDRangel::SWGBladeRF2InputReport::getFrequencyRange ()
Definition at line 141 of file SWGBladeRF2InputReport.cpp.
References frequency_range.
Referenced by BladeRF2Input::webapiFormatDeviceReport().
{
     return frequency_range;
 }
getGainModes()
QList< SWGNamedEnum * > * SWGSDRangel::SWGBladeRF2InputReport::getGainModes ()
Definition at line 181 of file SWGBladeRF2InputReport.cpp.
References gain_modes.
Referenced by BladeRF2Input::webapiFormatDeviceReport().
{
     return gain_modes;
 }
getGlobalGainRange()
SWGRange * SWGSDRangel::SWGBladeRF2InputReport::getGlobalGainRange ()
Definition at line 171 of file SWGBladeRF2InputReport.cpp.
References global_gain_range.
Referenced by BladeRF2Input::webapiFormatDeviceReport().
{
     return global_gain_range;
 }
getSampleRateRange()
SWGRange * SWGSDRangel::SWGBladeRF2InputReport::getSampleRateRange ()
Definition at line 151 of file SWGBladeRF2InputReport.cpp.
References sample_rate_range.
Referenced by BladeRF2Input::webapiFormatDeviceReport().
{
     return sample_rate_range;
 }
init()
void SWGSDRangel::SWGBladeRF2InputReport::init ()
Definition at line 48 of file SWGBladeRF2InputReport.cpp.
References bandwidth_range, frequency_range, gain_modes, global_gain_range, m_bandwidth_range_isSet, m_frequency_range_isSet, m_gain_modes_isSet, m_global_gain_range_isSet, m_sample_rate_range_isSet, and sample_rate_range.
Referenced by SWGBladeRF2InputReport(), and BladeRF2Input::webapiReportGet().
{
     frequency_range = new SWGFrequencyRange();
     m_frequency_range_isSet = false;
     sample_rate_range = new SWGRange();
     m_sample_rate_range_isSet = false;
     bandwidth_range = new SWGRange();
     m_bandwidth_range_isSet = false;
     global_gain_range = new SWGRange();
     m_global_gain_range_isSet = false;
     gain_modes = new QList<SWGNamedEnum*>();
     m_gain_modes_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGBladeRF2InputReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 192 of file SWGBladeRF2InputReport.cpp.
References bandwidth_range, frequency_range, gain_modes, global_gain_range, SWGSDRangel::SWGRange::isSet(), SWGSDRangel::SWGFrequencyRange::isSet(), and sample_rate_range.
Referenced by SWGSDRangel::SWGDeviceReport::asJsonObject(), and SWGSDRangel::SWGDeviceReport::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(frequency_range != nullptr && frequency_range->isSet()){ isObjectUpdated = true; break;}
         if(sample_rate_range != nullptr && sample_rate_range->isSet()){ isObjectUpdated = true; break;}
         if(bandwidth_range != nullptr && bandwidth_range->isSet()){ isObjectUpdated = true; break;}
         if(global_gain_range != nullptr && global_gain_range->isSet()){ isObjectUpdated = true; break;}
         if(gain_modes->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setBandwidthRange()
void SWGSDRangel::SWGBladeRF2InputReport::setBandwidthRange (SWGRange * bandwidth_range)
Definition at line 165 of file SWGBladeRF2InputReport.cpp.
References bandwidth_range, and m_bandwidth_range_isSet.
Referenced by BladeRF2Input::webapiFormatDeviceReport().
{
     this->bandwidth_range = bandwidth_range;
     this->m_bandwidth_range_isSet = true;
 }
setFrequencyRange()
void SWGSDRangel::SWGBladeRF2InputReport::setFrequencyRange (SWGFrequencyRange * frequency_range)
Definition at line 145 of file SWGBladeRF2InputReport.cpp.
References frequency_range, and m_frequency_range_isSet.
Referenced by BladeRF2Input::webapiFormatDeviceReport().
{
     this->frequency_range = frequency_range;
     this->m_frequency_range_isSet = true;
 }
setGainModes()
void SWGSDRangel::SWGBladeRF2InputReport::setGainModes (QList< SWGNamedEnum *> * gain_modes)
Definition at line 185 of file SWGBladeRF2InputReport.cpp.
References gain_modes, and m_gain_modes_isSet.
Referenced by BladeRF2Input::webapiFormatDeviceReport().
{
     this->gain_modes = gain_modes;
     this->m_gain_modes_isSet = true;
 }
setGlobalGainRange()
void SWGSDRangel::SWGBladeRF2InputReport::setGlobalGainRange (SWGRange * global_gain_range)
Definition at line 175 of file SWGBladeRF2InputReport.cpp.
References global_gain_range, and m_global_gain_range_isSet.
Referenced by BladeRF2Input::webapiFormatDeviceReport().
{
     this->global_gain_range = global_gain_range;
     this->m_global_gain_range_isSet = true;
 }
setSampleRateRange()
void SWGSDRangel::SWGBladeRF2InputReport::setSampleRateRange (SWGRange * sample_rate_range)
Definition at line 155 of file SWGBladeRF2InputReport.cpp.
References m_sample_rate_range_isSet, and sample_rate_range.
Referenced by BladeRF2Input::webapiFormatDeviceReport().
{
     this->sample_rate_range = sample_rate_range;
     this->m_sample_rate_range_isSet = true;
 }
Member Data Documentation
bandwidth_range
SWGRange* SWGSDRangel::SWGBladeRF2InputReport::bandwidth_range private
Definition at line 73 of file SWGBladeRF2InputReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getBandwidthRange(), init(), isSet(), setBandwidthRange(), and SWGBladeRF2InputReport().
frequency_range
SWGFrequencyRange* SWGSDRangel::SWGBladeRF2InputReport::frequency_range private
Definition at line 67 of file SWGBladeRF2InputReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFrequencyRange(), init(), isSet(), setFrequencyRange(), and SWGBladeRF2InputReport().
gain_modes
QList<SWGNamedEnum*>* SWGSDRangel::SWGBladeRF2InputReport::gain_modes private
Definition at line 79 of file SWGBladeRF2InputReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getGainModes(), init(), isSet(), setGainModes(), and SWGBladeRF2InputReport().
global_gain_range
SWGRange* SWGSDRangel::SWGBladeRF2InputReport::global_gain_range private
Definition at line 76 of file SWGBladeRF2InputReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getGlobalGainRange(), init(), isSet(), setGlobalGainRange(), and SWGBladeRF2InputReport().
m_bandwidth_range_isSet
bool SWGSDRangel::SWGBladeRF2InputReport::m_bandwidth_range_isSet private
Definition at line 74 of file SWGBladeRF2InputReport.h.
Referenced by init(), setBandwidthRange(), and SWGBladeRF2InputReport().
m_frequency_range_isSet
bool SWGSDRangel::SWGBladeRF2InputReport::m_frequency_range_isSet private
Definition at line 68 of file SWGBladeRF2InputReport.h.
Referenced by init(), setFrequencyRange(), and SWGBladeRF2InputReport().
m_gain_modes_isSet
bool SWGSDRangel::SWGBladeRF2InputReport::m_gain_modes_isSet private
Definition at line 80 of file SWGBladeRF2InputReport.h.
Referenced by init(), setGainModes(), and SWGBladeRF2InputReport().
m_global_gain_range_isSet
bool SWGSDRangel::SWGBladeRF2InputReport::m_global_gain_range_isSet private
Definition at line 77 of file SWGBladeRF2InputReport.h.
Referenced by init(), setGlobalGainRange(), and SWGBladeRF2InputReport().
m_sample_rate_range_isSet
bool SWGSDRangel::SWGBladeRF2InputReport::m_sample_rate_range_isSet private
Definition at line 71 of file SWGBladeRF2InputReport.h.
Referenced by init(), setSampleRateRange(), and SWGBladeRF2InputReport().
sample_rate_range
SWGRange* SWGSDRangel::SWGBladeRF2InputReport::sample_rate_range private
Definition at line 70 of file SWGBladeRF2InputReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSampleRateRange(), init(), isSet(), setSampleRateRange(), and SWGBladeRF2InputReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGBladeRF2InputReport.h
swagger/sdrangel/code/qt5/client/SWGBladeRF2InputReport.cpp