SDRAngel: AudioOutput Class Reference
AudioOutput Class Reference
#include <audiooutput.h>
Inherits QIODevice.
Public Types
enum UDPChannelMode { UDPChannelLeft, UDPChannelRight, UDPChannelMixed, UDPChannelStereo }
enum UDPChannelCodec {
UDPCodecL16, UDPCodecL8, UDPCodecALaw, UDPCodecULaw,
UDPCodecG722, UDPCodecOpus
}
Public Member Functions
AudioOutput ()
virtual ~AudioOutput ()
bool start (int device, int rate)
void stop ()
void addFifo (AudioFifo *audioFifo)
void removeFifo (AudioFifo *audioFifo)
int getNbFifos () const
unsigned int getRate () const
void setOnExit (bool onExit)
void setUdpDestination (const QString &address, uint16_t port)
void setUdpCopyToUDP (bool copyToUDP)
void setUdpUseRTP (bool useRTP)
void setUdpChannelMode (UDPChannelMode udpChannelMode)
void setUdpChannelFormat (UDPChannelCodec udpChannelCodec, bool stereo, int sampleRate)
void setUdpDecimation (uint32_t decimation)
Private Member Functions
virtual qint64 readData (char *data, qint64 maxLen)
virtual qint64 writeData (const char *data, qint64 len)
Private Attributes
QMutex m_mutex
QAudioOutput * m_audioOutput
AudioNetSink * m_audioNetSink
bool m_copyAudioToUdp
UDPChannelMode m_udpChannelMode
UDPChannelCodec m_udpChannelCodec
uint m_audioUsageCount
bool m_onExit
std::list< AudioFifo * > m_audioFifos
std::vector< qint32 > m_mixBuffer
QAudioFormat m_audioFormat
Friends
class AudioOutputPipe
Detailed Description
Definition at line 35 of file audiooutput.h.
Member Enumeration Documentation
UDPChannelCodec
enum AudioOutput::UDPChannelCodec
Enumerator
UDPCodecL16
Linear 16 bit (no codec)
UDPCodecL8
Linear 8 bit.
UDPCodecALaw
PCM A-law 8 bit.
UDPCodecULaw
PCM Mu-law 8 bit.
UDPCodecG722
G722 compression.
UDPCodecOpus
Opus compression.
Definition at line 45 of file audiooutput.h.
     {
         UDPCodecL16,
         UDPCodecL8,
         UDPCodecALaw,
         UDPCodecULaw,
         UDPCodecG722,
         UDPCodecOpus
     };
UDPChannelMode
enum AudioOutput::UDPChannelMode
Enumerator
UDPChannelLeft
UDPChannelRight
UDPChannelMixed
UDPChannelStereo
Definition at line 37 of file audiooutput.h.
     {
         UDPChannelLeft,
         UDPChannelRight,
         UDPChannelMixed,
         UDPChannelStereo
     };
Constructor & Destructor Documentation
AudioOutput()
AudioOutput::AudioOutput ()
Definition at line 27 of file audiooutput.cpp.
                          :
     m_mutex(QMutex::Recursive),
     m_audioOutput(0),
     m_audioNetSink(0),
     m_copyAudioToUdp(false),
     m_udpChannelMode(UDPChannelLeft),
     m_udpChannelCodec(UDPCodecL16),
     m_audioUsageCount(0),
     m_onExit(false),
     m_audioFifos()
 {
 }
~AudioOutput()
AudioOutput::~AudioOutput () virtual
Definition at line 40 of file audiooutput.cpp.
 {
 //  stop();
 //
 //  QMutexLocker mutexLocker(&m_mutex);
 //
 //  for (std::list<AudioFifo*>::iterator it = m_audioFifos.begin(); it != m_audioFifos.end(); ++it)
 //  {
 //      delete *it;
 //  }
 //
 //  m_audioFifos.clear();
 }
Member Function Documentation
addFifo()
void AudioOutput::addFifo (AudioFifo * audioFifo)
Definition at line 160 of file audiooutput.cpp.
References m_audioFifos, and m_mutex.
 {
     QMutexLocker mutexLocker(&m_mutex);
     m_audioFifos.push_back(audioFifo);
 }
getNbFifos()
int AudioOutput::getNbFifos () const inline
Definition at line 63 of file audiooutput.h.
 { return m_audioFifos.size(); }
getRate()
unsigned int AudioOutput::getRate () const inline
Definition at line 65 of file audiooutput.h.
Referenced by AudioDeviceManager::setOutputDeviceInfo().
 { return m_audioFormat.sampleRate(); }
readData()
qint64 AudioOutput::readData (char * data, qint64 maxLen) private virtual
Definition at line 221 of file audiooutput.cpp.
References i, m_audioFifos, m_audioNetSink, m_copyAudioToUdp, m_mixBuffer, m_udpChannelMode, UDPChannelLeft, UDPChannelMixed, UDPChannelRight, UDPChannelStereo, and AudioNetSink::write().
 {
     //qDebug("AudioOutput::readData: %lld", maxLen);
     // Study this mutex on OSX, for now deadlocks possible
     // Removed as it may indeed cause lockups and is in fact useless.
 //#ifndef __APPLE__
 //    QMutexLocker mutexLocker(&m_mutex);
 //#endif
     unsigned int samplesPerBuffer = maxLen / 4;
     if (samplesPerBuffer == 0)
     {
         return 0;
     }
     if (m_mixBuffer.size() < samplesPerBuffer * 2)
     {
         m_mixBuffer.resize(samplesPerBuffer * 2); // allocate 2 qint32 per sample (stereo)
         if (m_mixBuffer.size() != samplesPerBuffer * 2)
         {
             return 0;
         }
     }
     memset(&m_mixBuffer[0], 0x00, 2 * samplesPerBuffer * sizeof(m_mixBuffer[0])); // start with silence
     // sum up a block from all fifos
     for (std::list<AudioFifo*>::iterator it = m_audioFifos.begin(); it != m_audioFifos.end(); ++it)
     {
         // use outputBuffer as temp - yes, one memcpy could be saved
         unsigned int samples = (*it)->read((quint8*) data, samplesPerBuffer);
         const qint16* src = (const qint16*) data;
         std::vector<qint32>::iterator dst = m_mixBuffer.begin();
 //      if (samples != framesPerBuffer)
 //      {
 //            qDebug("AudioOutput::readData: read %d samples vs %d requested", samples, framesPerBuffer);
 //      }
         for (unsigned int i = 0; i < samples; i++)
         {
             *dst += *src;
             ++src;
             ++dst;
             *dst += *src;
             ++src;
             ++dst;
         }
     }
     // convert to int16
     //std::vector<qint32>::const_iterator src = m_mixBuffer.begin(); // Valgrind optim
     qint16* dst = (qint16*) data;
     qint32 sl, sr;
     for (unsigned int i = 0; i < samplesPerBuffer; i++)
     {
         // left channel
         //s = *src++; // Valgrind optim
         sl = m_mixBuffer[2*i];
         if(sl < -32768)
         {
             sl = -32768;
         }
         else if (sl > 32767)
         {
             sl = 32767;
         }
         *dst++ = sl;
         // right channel
         //s = *src++; // Valgrind optim
         sr = m_mixBuffer[2*i + 1];
         if(sr < -32768)
         {
             sr = -32768;
         }
         else if (sr > 32767)
         {
             sr = 32767;
         }
         *dst++ = sr;
         if ((m_copyAudioToUdp) && (m_audioNetSink))
         {
             switch (m_udpChannelMode)
             {
             case UDPChannelStereo:
                 m_audioNetSink->write(sl, sr);
                 break;
             case UDPChannelMixed:
                 m_audioNetSink->write((sl+sr)/2);
                 break;
             case UDPChannelRight:
                 m_audioNetSink->write(sr);
                 break;
             case UDPChannelLeft:
             default:
                 m_audioNetSink->write(sl);
                 break;
             }
         }
     }
     return samplesPerBuffer * 4;
 }
removeFifo()
void AudioOutput::removeFifo (AudioFifo * audioFifo)
Definition at line 167 of file audiooutput.cpp.
References m_audioFifos, and m_mutex.
 {
     QMutexLocker mutexLocker(&m_mutex);
     m_audioFifos.remove(audioFifo);
 }
setOnExit()
void AudioOutput::setOnExit (bool onExit) inline
Definition at line 66 of file audiooutput.h.
References decimation().
 { m_onExit = onExit; }
setUdpChannelFormat()
void AudioOutput::setUdpChannelFormat (UDPChannelCodec udpChannelCodec, bool stereo, int sampleRate)
Definition at line 205 of file audiooutput.cpp.
References m_audioNetSink, m_udpChannelCodec, and AudioNetSink::setParameters().
Referenced by AudioDeviceManager::setOutputDeviceInfo().
 {
     m_udpChannelCodec = udpChannelCodec;
     if (m_audioNetSink) {
         m_audioNetSink->setParameters((AudioNetSink::Codec) m_udpChannelCodec, stereo, sampleRate);
     }
 }
setUdpChannelMode()
void AudioOutput::setUdpChannelMode (UDPChannelMode udpChannelMode)
Definition at line 200 of file audiooutput.cpp.
References m_udpChannelMode.
Referenced by AudioDeviceManager::setOutputDeviceInfo().
 {
     m_udpChannelMode = udpChannelMode;
 }
setUdpCopyToUDP()
void AudioOutput::setUdpCopyToUDP (bool copyToUDP)
Definition at line 188 of file audiooutput.cpp.
References m_copyAudioToUdp.
Referenced by AudioDeviceManager::setOutputDeviceInfo().
 {
     m_copyAudioToUdp = copyToUDP;
 }
setUdpDecimation()
void AudioOutput::setUdpDecimation (uint32_t decimation)
Definition at line 214 of file audiooutput.cpp.
References m_audioNetSink, and AudioNetSink::setDecimation().
Referenced by AudioDeviceManager::setOutputDeviceInfo().
 {
     if (m_audioNetSink) {
         m_audioNetSink->setDecimation(decimation);
     }
 }
setUdpDestination()
void AudioOutput::setUdpDestination (const QString & address, uint16_t port)
Definition at line 181 of file audiooutput.cpp.
References m_audioNetSink, and AudioNetSink::setDestination().
Referenced by AudioDeviceManager::setOutputDeviceInfo().
 {
     if (m_audioNetSink) {
         m_audioNetSink->setDestination(address, port);
     }
 }
setUdpUseRTP()
void AudioOutput::setUdpUseRTP (bool useRTP)
Definition at line 193 of file audiooutput.cpp.
References m_audioNetSink, AudioNetSink::selectType(), AudioNetSink::SinkRTP, and AudioNetSink::SinkUDP.
Referenced by AudioDeviceManager::setOutputDeviceInfo().
 {
     if (m_audioNetSink) {
         m_audioNetSink->selectType(useRTP ? AudioNetSink::SinkRTP : AudioNetSink::SinkUDP);
     }
 }
start()
bool AudioOutput::start (int device, int rate)
Definition at line 54 of file audiooutput.cpp.
References m_audioFormat, m_audioNetSink, m_audioOutput, and m_mutex.
Referenced by AudioDeviceManager::setOutputDeviceInfo().
 {
 //  if (m_audioUsageCount == 0)
 //  {
         QMutexLocker mutexLocker(&m_mutex);
         QAudioDeviceInfo devInfo;
         if (device < 0)
         {
             devInfo = QAudioDeviceInfo::defaultOutputDevice();
             qWarning("AudioOutput::start: using system default device %s", qPrintable(devInfo.defaultOutputDevice().deviceName()));
         }
         else
         {
             QList<QAudioDeviceInfo> devicesInfo = QAudioDeviceInfo::availableDevices(QAudio::AudioOutput);
             if (device < devicesInfo.size())
             {
                 devInfo = devicesInfo[device];
                 qWarning("AudioOutput::start: using audio device #%d: %s", device, qPrintable(devInfo.deviceName()));
             }
             else
             {
                 devInfo = QAudioDeviceInfo::defaultOutputDevice();
                 qWarning("AudioOutput::start: audio device #%d does not exist. Using system default device %s", device, qPrintable(devInfo.defaultOutputDevice().deviceName()));
             }
         }
         //QAudioDeviceInfo devInfo(QAudioDeviceInfo::defaultOutputDevice());
         m_audioFormat.setSampleRate(rate);
         m_audioFormat.setChannelCount(2);
         m_audioFormat.setSampleSize(16);
         m_audioFormat.setCodec("audio/pcm");
         m_audioFormat.setByteOrder(QAudioFormat::LittleEndian);
         m_audioFormat.setSampleType(QAudioFormat::SignedInt);
         if (!devInfo.isFormatSupported(m_audioFormat))
         {
             m_audioFormat = devInfo.nearestFormat(m_audioFormat);
             std::ostringstream os;
             os << " sampleRate: " << m_audioFormat.sampleRate()
                << " channelCount: " << m_audioFormat.channelCount()
                << " sampleSize: " << m_audioFormat.sampleSize()
                << " codec: "  << m_audioFormat.codec().toStdString()
                << " byteOrder: " <<  (m_audioFormat.byteOrder() == QAudioFormat::BigEndian ? "BE" : "LE")
                << " sampleType: " << (int) m_audioFormat.sampleType();
             qWarning("AudioOutput::start: format %d Hz 2xS16LE audio/pcm not supported. Using: %s", rate, os.str().c_str());
         }
         else
         {
             qInfo("AudioOutput::start: audio format OK");
         }
         if (m_audioFormat.sampleSize() != 16)
         {
             qWarning("AudioOutput::start: Audio device '%s' failed", qPrintable(devInfo.defaultOutputDevice().deviceName()));
             return false;
         }
         m_audioOutput = new QAudioOutput(devInfo, m_audioFormat);
         m_audioNetSink = new AudioNetSink(0, m_audioFormat.sampleRate(), false);
         QIODevice::open(QIODevice::ReadOnly);
         m_audioOutput->start(this);
         if (m_audioOutput->state() != QAudio::ActiveState)
         {
             qWarning("AudioOutput::start: cannot start");
         }
 //  }
 //
 //  m_audioUsageCount++;
     return true;
 }
stop()
void AudioOutput::stop ()
Definition at line 133 of file audiooutput.cpp.
References m_audioNetSink, m_audioOutput, and m_mutex.
Referenced by AudioDeviceManager::setOutputDeviceInfo().
 {
     qDebug("AudioOutput::stop");
     QMutexLocker mutexLocker(&m_mutex);
     m_audioOutput->stop();
     QIODevice::close();
     delete m_audioNetSink;
     m_audioNetSink = 0;
     delete m_audioOutput;
 //    if (m_audioUsageCount > 0)
 //    {
 //        m_audioUsageCount--;
 //
 //        if (m_audioUsageCount == 0)
 //        {
 //            QMutexLocker mutexLocker(&m_mutex);
 //            QIODevice::close();
 //
 //            if (!m_onExit) {
 //                delete m_audioOutput;
 //            }
 //        }
 //    }
 }
writeData()
qint64 AudioOutput::writeData (const char * data, qint64 len) private virtual
Definition at line 338 of file audiooutput.cpp.
 {
     Q_UNUSED(data);
     Q_UNUSED(len);
     return 0;
 }
Friends And Related Function Documentation
AudioOutputPipe
friend class AudioOutputPipe friend
Definition at line 94 of file audiooutput.h.
Member Data Documentation
m_audioFifos
std::list<AudioFifo*> AudioOutput::m_audioFifos private
Definition at line 85 of file audiooutput.h.
Referenced by addFifo(), readData(), and removeFifo().
m_audioFormat
QAudioFormat AudioOutput::m_audioFormat private
Definition at line 88 of file audiooutput.h.
Referenced by start().
m_audioNetSink
AudioNetSink* AudioOutput::m_audioNetSink private
Definition at line 78 of file audiooutput.h.
Referenced by readData(), setUdpChannelFormat(), setUdpDecimation(), setUdpDestination(), setUdpUseRTP(), start(), and stop().
m_audioOutput
QAudioOutput* AudioOutput::m_audioOutput private
Definition at line 77 of file audiooutput.h.
Referenced by start(), and stop().
m_audioUsageCount
uint AudioOutput::m_audioUsageCount private
Definition at line 82 of file audiooutput.h.
m_copyAudioToUdp
bool AudioOutput::m_copyAudioToUdp private
Definition at line 79 of file audiooutput.h.
Referenced by readData(), and setUdpCopyToUDP().
m_mixBuffer
std::vector<qint32> AudioOutput::m_mixBuffer private
Definition at line 86 of file audiooutput.h.
Referenced by readData().
m_mutex
QMutex AudioOutput::m_mutex private
Definition at line 76 of file audiooutput.h.
Referenced by addFifo(), removeFifo(), start(), and stop().
m_onExit
bool AudioOutput::m_onExit private
Definition at line 83 of file audiooutput.h.
m_udpChannelCodec
UDPChannelCodec AudioOutput::m_udpChannelCodec private
Definition at line 81 of file audiooutput.h.
Referenced by setUdpChannelFormat().
m_udpChannelMode
UDPChannelMode AudioOutput::m_udpChannelMode private
Definition at line 80 of file audiooutput.h.
Referenced by readData(), and setUdpChannelMode().
The documentation for this class was generated from the following files:
sdrbase/audio/audiooutput.h
sdrbase/audio/audiooutput.cpp