SDRAngel: CalcDb Class Reference
CalcDb Class Reference
#include <db.h>
Static Public Member Functions
static double dbPower (double magsq, double floor=1e-12)
static double powerFromdB (double powerdB)
Detailed Description
Definition at line 24 of file db.h.
Member Function Documentation
dbPower()
double CalcDb::dbPower (double magsq, double floor = 1e-12) static
Definition at line 22 of file db.cpp.
Referenced by TestSourceGui::displayAmplitude(), TestMIGui::displayAmplitude(), FreeDVDemod::getSNRLevels(), BFMDemodGUI::rdsUpdate(), DATVDemodGUI::tick(), WFMDemodGUI::tick(), NFMDemodGUI::tick(), AMDemodGUI::tick(), FreqTrackerGUI::tick(), ATVDemodGUI::tick(), SSBDemodGUI::tick(), FreeDVDemodGUI::tick(), UDPSourceGUI::tick(), BFMDemodGUI::tick(), ChannelAnalyzerGUI::tick(), UDPSinkGUI::tick(), FileSourceGUI::tick(), AMModGUI::tick(), FreeDVModGUI::tick(), NFMModGUI::tick(), WFMModGUI::tick(), SSBModGUI::tick(), ATVModGUI::tick(), DSDDemodGUI::tick(), WFMDemod::webapiFormatChannelReport(), AMDemod::webapiFormatChannelReport(), FreqTracker::webapiFormatChannelReport(), UDPSink::webapiFormatChannelReport(), UDPSource::webapiFormatChannelReport(), NFMDemod::webapiFormatChannelReport(), DSDDemod::webapiFormatChannelReport(), BFMDemod::webapiFormatChannelReport(), WFMMod::webapiFormatChannelReport(), AMMod::webapiFormatChannelReport(), SSBDemod::webapiFormatChannelReport(), NFMMod::webapiFormatChannelReport(), FreeDVMod::webapiFormatChannelReport(), SSBMod::webapiFormatChannelReport(), FreeDVDemod::webapiFormatChannelReport(), FileSource::webapiFormatChannelReport(), ATVMod::webapiFormatChannelReport(), and BFMDemod::webapiFormatRDSReport().
 {
     assert(floor > 0.0);
     if (magsq > floor)
     {
         return 10.0 * log10(magsq);
     }
     else
     {
         return 10.0 * log10(floor);
     }
 }
powerFromdB()
double CalcDb::powerFromdB (double powerdB) static
Definition at line 36 of file db.cpp.
Referenced by FreeDVDemod::FreeDVSNR::accumulate(), AMDemod::applySettings(), FreqTracker::applySettings(), UDPSink::applySettings(), UDPSource::applySettings(), SSBDemod::applySettings(), and FileSource::applySettings().
 {
     return pow(10.0, powerdB / 10.0);
 }
The documentation for this class was generated from the following files:
sdrbase/util/db.h
sdrbase/util/db.cpp