SDRAngel: LocalSource::MsgConfigureChannelizer Class Reference
LocalSource::MsgConfigureChannelizer Class Reference
#include <localsource.h>
Public Member Functions
int getLog2Interp () const
int getFilterChainHash () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (unsigned int m_log2Interp, unsigned int m_filterChainHash)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (unsigned int log2Interp, unsigned int filterChainHash)
Private Attributes
unsigned int m_log2Interp
unsigned int m_filterChainHash
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 84 of file localsource.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
LocalSource::MsgConfigureChannelizer::MsgConfigureChannelizer (unsigned int log2Interp, unsigned int filterChainHash) inline private
Definition at line 99 of file localsource.h.
References LocalSource::LocalSource(), and LocalSource::~LocalSource().
                                                                                        :
             Message(),
             m_log2Interp(log2Interp),
             m_filterChainHash(filterChainHash)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* LocalSource::MsgConfigureChannelizer::create (unsigned int m_log2Interp, unsigned int m_filterChainHash) inline static
Definition at line 91 of file localsource.h.
Referenced by LocalSourceGUI::applyChannelSettings(), and LocalSource::webapiSettingsPutPatch().
{
             return new MsgConfigureChannelizer(m_log2Interp, m_filterChainHash);
         }
getFilterChainHash()
int LocalSource::MsgConfigureChannelizer::getFilterChainHash () const inline
Definition at line 89 of file localsource.h.
Referenced by LocalSource::handleMessage().
 { return m_filterChainHash; }
getLog2Interp()
int LocalSource::MsgConfigureChannelizer::getLog2Interp () const inline
Definition at line 88 of file localsource.h.
Referenced by LocalSource::handleMessage().
 { return m_log2Interp; }
Member Data Documentation
m_filterChainHash
unsigned int LocalSource::MsgConfigureChannelizer::m_filterChainHash private
Definition at line 97 of file localsource.h.
m_log2Interp
unsigned int LocalSource::MsgConfigureChannelizer::m_log2Interp private
Definition at line 96 of file localsource.h.
The documentation for this class was generated from the following file:
plugins/channeltx/localsource/localsource.h