SDRAngel: MainCore Class Reference
MainCore Class Reference
#include <maincore.h>
Inherits QObject.
Classes
class MsgAddChannel
class MsgAddDeviceSet
class MsgDeleteChannel
class MsgDeleteInstance
class MsgDeletePreset
class MsgLoadPreset
class MsgRemoveLastDeviceSet
class MsgSavePreset
class MsgSetDevice
Signals
void finished ()
Public Member Functions
MainCore (qtwebapp::LoggerWithFile *logger, const MainParser &parser, QObject *parent=0)
~MainCore ()
MessageQueue * getInputMessageQueue ()
const QTimer & getMasterTimer () const
const MainSettings & getMainSettings () const
void addSourceDevice ()
void addSinkDevice ()
void removeLastDevice ()
void changeSampleSource (int deviceSetIndex, int selectedDeviceIndex)
void changeSampleSink (int deviceSetIndex, int selectedDeviceIndex)
void addChannel (int deviceSetIndex, int selectedChannelIndex)
void deleteChannel (int deviceSetIndex, int channelIndex)
Static Public Member Functions
static MainCore * getInstance ()
Private Slots
void handleMessages ()
Private Member Functions
void loadSettings ()
void loadPresetSettings (const Preset *preset, int tabIndex)
void savePresetSettings (Preset *preset, int tabIndex)
void setLoggingOptions ()
bool handleMessage (const Message &cmd)
Private Attributes
MainSettings m_settings
int m_masterTabIndex
DSPEngine * m_dspEngine
int m_lastEngineState
qtwebapp::LoggerWithFile * m_logger
MessageQueue m_inputMessageQueue
QTimer m_masterTimer
std::vector< DeviceSet * > m_deviceSets
PluginManager * m_pluginManager
WebAPIRequestMapper * m_requestMapper
WebAPIServer * m_apiServer
WebAPIAdapterSrv * m_apiAdapter
Static Private Attributes
static MainCore * m_instance = 0
Friends
class WebAPIAdapterSrv
Detailed Description
Definition at line 48 of file maincore.h.
Constructor & Destructor Documentation
MainCore()
MainCore::MainCore (qtwebapp::LoggerWithFile * logger, const MainParser & parser, QObject * parent = 0) explicit
Definition at line 50 of file maincore.cpp.
References DSPEngine::getAMBEEngine(), DSPEngine::getAudioDeviceManager(), MainParser::getMIMOSupport(), MainParser::getServerAddress(), MainParser::getServerPort(), handleMessages(), PluginManager::loadPlugins(), loadSettings(), m_apiAdapter, m_apiServer, m_dspEngine, m_inputMessageQueue, m_instance, m_masterTimer, m_pluginManager, m_requestMapper, m_settings, WebAPIRequestMapper::setAdapter(), MainSettings::setAMBEEngine(), MainSettings::setAudioDeviceManager(), DSPEngine::setMIMOSupport(), WebAPIServer::start(), and WebAPIAdapterSrv.
                                                                                             :
     QObject(parent),
     m_settings(),
     m_masterTabIndex(-1),
     m_dspEngine(DSPEngine::instance()),
     m_lastEngineState(DSPDeviceSourceEngine::StNotStarted),
     m_logger(logger)
 {
     qDebug() << "MainCore::MainCore: start";
     m_instance = this;
     m_settings.setAudioDeviceManager(m_dspEngine->getAudioDeviceManager());
     m_settings.setAMBEEngine(m_dspEngine->getAMBEEngine());
     m_pluginManager = new PluginManager(this);
     m_pluginManager->loadPlugins(QString("pluginssrv"));
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleMessages()), Qt::QueuedConnection);
     m_masterTimer.start(50);
     loadSettings();
     QString applicationDirPath = QCoreApplication::instance()->applicationDirPath();
     m_apiAdapter = new WebAPIAdapterSrv(*this);
     m_requestMapper = new WebAPIRequestMapper(this);
     m_requestMapper->setAdapter(m_apiAdapter);
     m_apiServer = new WebAPIServer(parser.getServerAddress(), parser.getServerPort(), m_requestMapper);
     m_apiServer->start();
     m_dspEngine->setMIMOSupport(parser.getMIMOSupport());
     qDebug() << "MainCore::MainCore: end";
 }
~MainCore()
MainCore::~MainCore ()
Definition at line 85 of file maincore.cpp.
References m_apiAdapter, m_apiServer, m_deviceSets, m_logger, m_pluginManager, m_requestMapper, m_settings, removeLastDevice(), MainSettings::save(), and WebAPIServer::stop().
 {
     while (m_deviceSets.size() > 0) {
         removeLastDevice();
     }
     m_apiServer->stop();
     m_settings.save();
     delete m_apiServer;
     delete m_requestMapper;
     delete m_apiAdapter;
     delete m_pluginManager;
     qDebug() << "MainCore::~MainCore: end";
     delete m_logger;
 }
Member Function Documentation
addChannel()
void MainCore::addChannel (int deviceSetIndex, int selectedChannelIndex)
Definition at line 530 of file maincore.cpp.
References DeviceSet::addRxChannel(), DeviceSet::addTxChannel(), PluginManager::getPluginAPI(), m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, and m_pluginManager.
Referenced by handleMessage().
 {
     if (deviceSetIndex >= 0)
     {
         DeviceSet *deviceSet = m_deviceSets[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine) // source device => Rx channels
         {
             deviceSet->addRxChannel(selectedChannelIndex, m_pluginManager->getPluginAPI());
         }
         else if (deviceSet->m_deviceSinkEngine) // sink device => Tx channels
         {
             deviceSet->addTxChannel(selectedChannelIndex, m_pluginManager->getPluginAPI());
         }
     }
 }
addSinkDevice()
void MainCore::addSinkDevice ()
Definition at line 258 of file maincore.cpp.
References DSPEngine::addDeviceSinkEngine(), PluginInterface::SamplingDevice::deviceItemIndex, PluginInterface::SamplingDevice::deviceNbItems, PluginInterface::SamplingDevice::displayedName, DeviceUserArgs::findUserArgs(), MainSettings::getDeviceUserArgs(), DeviceEnumerator::getFileSinkDeviceIndex(), DeviceEnumerator::getTxSamplingDevice(), DSPDeviceSinkEngine::getUID(), PluginInterface::SamplingDevice::hardwareId, PluginInterface::SamplingDevice::id, DeviceEnumerator::instance(), m_deviceSets, m_dspEngine, m_settings, PluginInterface::SamplingDevice::sequence, PluginInterface::SamplingDevice::serial, DSPDeviceSinkEngine::start(), and DeviceAPI::StreamSingleTx.
Referenced by handleMessage().
 {
     DSPDeviceSinkEngine *dspDeviceSinkEngine = m_dspEngine->addDeviceSinkEngine();
     dspDeviceSinkEngine->start();
     uint dspDeviceSinkEngineUID =  dspDeviceSinkEngine->getUID();
     char uidCStr[16];
     sprintf(uidCStr, "UID:%d", dspDeviceSinkEngineUID);
     int deviceTabIndex = m_deviceSets.size();
     m_deviceSets.push_back(new DeviceSet(deviceTabIndex));
     m_deviceSets.back()->m_deviceSourceEngine = 0;
     m_deviceSets.back()->m_deviceMIMOEngine = 0;
     char tabNameCStr[16];
     sprintf(tabNameCStr, "T%d", deviceTabIndex);
     DeviceAPI *deviceAPI = new DeviceAPI(DeviceAPI::StreamSingleTx, deviceTabIndex, nullptr, dspDeviceSinkEngine, nullptr);
     m_deviceSets.back()->m_deviceAPI = deviceAPI;
     QList<QString> channelNames;
     // create a file sink by default
     int fileSinkDeviceIndex = DeviceEnumerator::instance()->getFileSinkDeviceIndex();
     const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getTxSamplingDevice(fileSinkDeviceIndex);
     m_deviceSets.back()->m_deviceAPI->setSamplingDeviceSequence(samplingDevice->sequence);
     m_deviceSets.back()->m_deviceAPI->setDeviceNbItems(samplingDevice->deviceNbItems);
     m_deviceSets.back()->m_deviceAPI->setDeviceItemIndex(samplingDevice->deviceItemIndex);
     m_deviceSets.back()->m_deviceAPI->setHardwareId(samplingDevice->hardwareId);
     m_deviceSets.back()->m_deviceAPI->setSamplingDeviceId(samplingDevice->id);
     m_deviceSets.back()->m_deviceAPI->setSamplingDeviceSerial(samplingDevice->serial);
     m_deviceSets.back()->m_deviceAPI->setSamplingDeviceDisplayName(samplingDevice->displayedName);
     m_deviceSets.back()->m_deviceAPI->setSamplingDevicePluginInterface(DeviceEnumerator::instance()->getTxPluginInterface(fileSinkDeviceIndex));
     QString userArgs = m_settings.getDeviceUserArgs().findUserArgs(samplingDevice->hardwareId, samplingDevice->sequence);
     if (userArgs.size() > 0) {
         m_deviceSets.back()->m_deviceAPI->setHardwareUserArguments(userArgs);
     }
     DeviceSampleSink *sink = m_deviceSets.back()->m_deviceAPI->getPluginInterface()->createSampleSinkPluginInstance(
             m_deviceSets.back()->m_deviceAPI->getSamplingDeviceId(), m_deviceSets.back()->m_deviceAPI);
     m_deviceSets.back()->m_deviceAPI->setSampleSink(sink);
 }
addSourceDevice()
void MainCore::addSourceDevice ()
Definition at line 303 of file maincore.cpp.
References DSPEngine::addDeviceSourceEngine(), PluginInterface::SamplingDevice::deviceItemIndex, PluginInterface::SamplingDevice::deviceNbItems, PluginInterface::SamplingDevice::displayedName, DeviceUserArgs::findUserArgs(), MainSettings::getDeviceUserArgs(), DeviceEnumerator::getFileInputDeviceIndex(), DeviceEnumerator::getRxSamplingDevice(), DSPDeviceSourceEngine::getUID(), PluginInterface::SamplingDevice::hardwareId, PluginInterface::SamplingDevice::id, DeviceEnumerator::instance(), m_deviceSets, m_dspEngine, m_settings, PluginInterface::SamplingDevice::sequence, PluginInterface::SamplingDevice::serial, DSPDeviceSourceEngine::start(), and DeviceAPI::StreamSingleRx.
Referenced by handleMessage().
 {
     DSPDeviceSourceEngine *dspDeviceSourceEngine = m_dspEngine->addDeviceSourceEngine();
     dspDeviceSourceEngine->start();
     uint dspDeviceSourceEngineUID =  dspDeviceSourceEngine->getUID();
     char uidCStr[16];
     sprintf(uidCStr, "UID:%d", dspDeviceSourceEngineUID);
     int deviceTabIndex = m_deviceSets.size();
     m_deviceSets.push_back(new DeviceSet(deviceTabIndex));
     m_deviceSets.back()->m_deviceSourceEngine = dspDeviceSourceEngine;
     m_deviceSets.back()->m_deviceSinkEngine = 0;
     m_deviceSets.back()->m_deviceMIMOEngine = 0;
     char tabNameCStr[16];
     sprintf(tabNameCStr, "R%d", deviceTabIndex);
     DeviceAPI *deviceAPI = new DeviceAPI(DeviceAPI::StreamSingleRx, deviceTabIndex, dspDeviceSourceEngine, nullptr, nullptr);
     m_deviceSets.back()->m_deviceAPI = deviceAPI;
     // Create a file source instance by default
     int fileSourceDeviceIndex = DeviceEnumerator::instance()->getFileInputDeviceIndex();
     const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getRxSamplingDevice(fileSourceDeviceIndex);
     m_deviceSets.back()->m_deviceAPI->setSamplingDeviceSequence(samplingDevice->sequence);
     m_deviceSets.back()->m_deviceAPI->setDeviceNbItems(samplingDevice->deviceNbItems);
     m_deviceSets.back()->m_deviceAPI->setDeviceItemIndex(samplingDevice->deviceItemIndex);
     m_deviceSets.back()->m_deviceAPI->setHardwareId(samplingDevice->hardwareId);
     m_deviceSets.back()->m_deviceAPI->setSamplingDeviceId(samplingDevice->id);
     m_deviceSets.back()->m_deviceAPI->setSamplingDeviceSerial(samplingDevice->serial);
     m_deviceSets.back()->m_deviceAPI->setSamplingDeviceDisplayName(samplingDevice->displayedName);
     m_deviceSets.back()->m_deviceAPI->setSamplingDevicePluginInterface(DeviceEnumerator::instance()->getRxPluginInterface(fileSourceDeviceIndex));
     QString userArgs = m_settings.getDeviceUserArgs().findUserArgs(samplingDevice->hardwareId, samplingDevice->sequence);
     if (userArgs.size() > 0) {
         m_deviceSets.back()->m_deviceAPI->setHardwareUserArguments(userArgs);
     }
     DeviceSampleSource *source = m_deviceSets.back()->m_deviceAPI->getPluginInterface()->createSampleSourcePluginInstance(
             m_deviceSets.back()->m_deviceAPI->getSamplingDeviceId(), m_deviceSets.back()->m_deviceAPI);
     m_deviceSets.back()->m_deviceAPI->setSampleSource(source);
 }
changeSampleSink()
void MainCore::changeSampleSink (int deviceSetIndex, int selectedDeviceIndex)
Definition at line 462 of file maincore.cpp.
References DeviceAPI::clearBuddiesLists(), PluginInterface::createSampleSinkPluginInstance(), PluginInterface::deleteSampleSinkPluginInstanceOutput(), PluginInterface::SamplingDevice::deviceItemIndex, PluginInterface::SamplingDevice::deviceNbItems, PluginInterface::SamplingDevice::displayedName, DeviceAPI::getHardwareId(), DeviceAPI::getPluginInterface(), DeviceAPI::getSampleSink(), DeviceAPI::getSamplingDeviceId(), DeviceAPI::getSamplingDeviceSerial(), DeviceEnumerator::getTxSamplingDevice(), MainSettings::getWorkingPreset(), PluginInterface::SamplingDevice::hardwareId, PluginInterface::SamplingDevice::id, DeviceEnumerator::instance(), DeviceAPI::loadSamplingDeviceSettings(), DeviceSet::m_deviceAPI, m_deviceSets, m_settings, DeviceAPI::resetSamplingDeviceId(), DeviceAPI::saveSamplingDeviceSettings(), PluginInterface::SamplingDevice::sequence, PluginInterface::SamplingDevice::serial, DeviceAPI::setBuddyLeader(), DeviceAPI::setDeviceItemIndex(), DeviceAPI::setDeviceNbItems(), DeviceAPI::setHardwareId(), DeviceAPI::setSampleSink(), DeviceAPI::setSamplingDeviceDisplayName(), DeviceAPI::setSamplingDeviceId(), DeviceAPI::setSamplingDevicePluginInterface(), DeviceAPI::setSamplingDeviceSequence(), DeviceAPI::setSamplingDeviceSerial(), and DeviceAPI::stopDeviceEngine().
Referenced by handleMessage().
 {
     if (deviceSetIndex >= 0)
     {
         qDebug("MainCore::changeSampleSink: device set at %d", deviceSetIndex);
         DeviceSet *deviceSet = m_deviceSets[deviceSetIndex];
         deviceSet->m_deviceAPI->saveSamplingDeviceSettings(m_settings.getWorkingPreset()); // save old API settings
         deviceSet->m_deviceAPI->stopDeviceEngine();
         // deletes old UI and output object
         deviceSet->m_deviceAPI->resetSamplingDeviceId();
         deviceSet->m_deviceAPI->getPluginInterface()->deleteSampleSinkPluginInstanceOutput(
                 deviceSet->m_deviceAPI->getSampleSink());
         deviceSet->m_deviceAPI->clearBuddiesLists(); // clear old API buddies lists
         const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getTxSamplingDevice(selectedDeviceIndex);
         deviceSet->m_deviceAPI->setSamplingDeviceSequence(samplingDevice->sequence);
         deviceSet->m_deviceAPI->setDeviceNbItems(samplingDevice->deviceNbItems);
         deviceSet->m_deviceAPI->setDeviceItemIndex(samplingDevice->deviceItemIndex);
         deviceSet->m_deviceAPI->setHardwareId(samplingDevice->hardwareId);
         deviceSet->m_deviceAPI->setSamplingDeviceId(samplingDevice->id);
         deviceSet->m_deviceAPI->setSamplingDeviceSerial(samplingDevice->serial);
         deviceSet->m_deviceAPI->setSamplingDeviceDisplayName(samplingDevice->displayedName);
         deviceSet->m_deviceAPI->setSamplingDevicePluginInterface(DeviceEnumerator::instance()->getTxPluginInterface(selectedDeviceIndex));
         // add to buddies list
         std::vector<DeviceSet*>::iterator it = m_deviceSets.begin();
         int nbOfBuddies = 0;
         for (; it != m_deviceSets.end(); ++it)
         {
             if (*it != deviceSet) // do not add to itself
             {
                 if ((*it)->m_deviceSourceEngine) // it is a source device
                 {
                     if ((deviceSet->m_deviceAPI->getHardwareId() == (*it)->m_deviceAPI->getHardwareId()) &&
                         (deviceSet->m_deviceAPI->getSamplingDeviceSerial() == (*it)->m_deviceAPI->getSamplingDeviceSerial()))
                     {
                         (*it)->m_deviceAPI->addSinkBuddy(deviceSet->m_deviceAPI);
                         nbOfBuddies++;
                     }
                 }
                 if ((*it)->m_deviceSinkEngine) // it is a sink device
                 {
                     if ((deviceSet->m_deviceAPI->getHardwareId() == (*it)->m_deviceAPI->getHardwareId()) &&
                         (deviceSet->m_deviceAPI->getSamplingDeviceSerial() == (*it)->m_deviceAPI->getSamplingDeviceSerial()))
                     {
                         (*it)->m_deviceAPI->addSinkBuddy(deviceSet->m_deviceAPI);
                         nbOfBuddies++;
                     }
                 }
             }
         }
         if (nbOfBuddies == 0) {
             deviceSet->m_deviceAPI->setBuddyLeader(true);
         }
         // constructs new GUI and output object
         DeviceSampleSink *sink = deviceSet->m_deviceAPI->getPluginInterface()->createSampleSinkPluginInstance(
                 deviceSet->m_deviceAPI->getSamplingDeviceId(), deviceSet->m_deviceAPI);
         deviceSet->m_deviceAPI->setSampleSink(sink);
         deviceSet->m_deviceAPI->loadSamplingDeviceSettings(m_settings.getWorkingPreset()); // load new API settings
     }
 }
changeSampleSource()
void MainCore::changeSampleSource (int deviceSetIndex, int selectedDeviceIndex)
Definition at line 394 of file maincore.cpp.
References DeviceAPI::clearBuddiesLists(), PluginInterface::createSampleSourcePluginInstance(), PluginInterface::deleteSampleSourcePluginInstanceInput(), PluginInterface::SamplingDevice::deviceItemIndex, PluginInterface::SamplingDevice::deviceNbItems, PluginInterface::SamplingDevice::displayedName, DeviceAPI::getHardwareId(), DeviceAPI::getPluginInterface(), DeviceEnumerator::getRxSamplingDevice(), DeviceAPI::getSampleSource(), DeviceAPI::getSamplingDeviceId(), DeviceAPI::getSamplingDeviceSerial(), MainSettings::getWorkingPreset(), PluginInterface::SamplingDevice::hardwareId, PluginInterface::SamplingDevice::id, DeviceEnumerator::instance(), DeviceAPI::loadSamplingDeviceSettings(), DeviceSet::m_deviceAPI, m_deviceSets, m_settings, DeviceAPI::resetSamplingDeviceId(), DeviceAPI::saveSamplingDeviceSettings(), PluginInterface::SamplingDevice::sequence, PluginInterface::SamplingDevice::serial, DeviceAPI::setBuddyLeader(), DeviceAPI::setDeviceItemIndex(), DeviceAPI::setDeviceNbItems(), DeviceAPI::setHardwareId(), DeviceAPI::setSampleSource(), DeviceAPI::setSamplingDeviceDisplayName(), DeviceAPI::setSamplingDeviceId(), DeviceAPI::setSamplingDevicePluginInterface(), DeviceAPI::setSamplingDeviceSequence(), DeviceAPI::setSamplingDeviceSerial(), and DeviceAPI::stopDeviceEngine().
Referenced by handleMessage().
 {
     if (deviceSetIndex >= 0)
     {
         qDebug("MainCore::changeSampleSource: deviceSet at %d", deviceSetIndex);
         DeviceSet *deviceSet = m_deviceSets[deviceSetIndex];
         deviceSet->m_deviceAPI->saveSamplingDeviceSettings(m_settings.getWorkingPreset()); // save old API settings
         deviceSet->m_deviceAPI->stopDeviceEngine();
         // deletes old UI and input object
         deviceSet->m_deviceAPI->resetSamplingDeviceId();
         deviceSet->m_deviceAPI->getPluginInterface()->deleteSampleSourcePluginInstanceInput(
                 deviceSet->m_deviceAPI->getSampleSource());
         deviceSet->m_deviceAPI->clearBuddiesLists(); // clear old API buddies lists
         const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getRxSamplingDevice(selectedDeviceIndex);
         deviceSet->m_deviceAPI->setSamplingDeviceSequence(samplingDevice->sequence);
         deviceSet->m_deviceAPI->setDeviceNbItems(samplingDevice->deviceNbItems);
         deviceSet->m_deviceAPI->setDeviceItemIndex(samplingDevice->deviceItemIndex);
         deviceSet->m_deviceAPI->setHardwareId(samplingDevice->hardwareId);
         deviceSet->m_deviceAPI->setSamplingDeviceId(samplingDevice->id);
         deviceSet->m_deviceAPI->setSamplingDeviceSerial(samplingDevice->serial);
         deviceSet->m_deviceAPI->setSamplingDeviceDisplayName(samplingDevice->displayedName);
         deviceSet->m_deviceAPI->setSamplingDevicePluginInterface(DeviceEnumerator::instance()->getRxPluginInterface(selectedDeviceIndex));
         // add to buddies list
         std::vector<DeviceSet*>::iterator it = m_deviceSets.begin();
         int nbOfBuddies = 0;
         for (; it != m_deviceSets.end(); ++it)
         {
             if (*it != deviceSet) // do not add to itself
             {
                 if ((*it)->m_deviceSourceEngine) // it is a source device
                 {
                     if ((deviceSet->m_deviceAPI->getHardwareId() == (*it)->m_deviceAPI->getHardwareId()) &&
                         (deviceSet->m_deviceAPI->getSamplingDeviceSerial() == (*it)->m_deviceAPI->getSamplingDeviceSerial()))
                     {
                         (*it)->m_deviceAPI->addSourceBuddy(deviceSet->m_deviceAPI);
                         nbOfBuddies++;
                     }
                 }
                 if ((*it)->m_deviceSinkEngine) // it is a sink device
                 {
                     if ((deviceSet->m_deviceAPI->getHardwareId() == (*it)->m_deviceAPI->getHardwareId()) &&
                         (deviceSet->m_deviceAPI->getSamplingDeviceSerial() == (*it)->m_deviceAPI->getSamplingDeviceSerial()))
                     {
                         (*it)->m_deviceAPI->addSourceBuddy(deviceSet->m_deviceAPI);
                         nbOfBuddies++;
                     }
                 }
             }
         }
         if (nbOfBuddies == 0) {
             deviceSet->m_deviceAPI->setBuddyLeader(true);
         }
         // constructs new GUI and input object
         DeviceSampleSource *source = deviceSet->m_deviceAPI->getPluginInterface()->createSampleSourcePluginInstance(
                 deviceSet->m_deviceAPI->getSamplingDeviceId(), deviceSet->m_deviceAPI);
         deviceSet->m_deviceAPI->setSampleSource(source);
         deviceSet->m_deviceAPI->loadSamplingDeviceSettings(m_settings.getWorkingPreset()); // load new API settings
     }
 }
deleteChannel()
void MainCore::deleteChannel (int deviceSetIndex, int channelIndex)
Definition at line 547 of file maincore.cpp.
References DeviceSet::deleteRxChannel(), DeviceSet::deleteTxChannel(), m_deviceSets, DeviceSet::m_deviceSinkEngine, and DeviceSet::m_deviceSourceEngine.
Referenced by handleMessage().
 {
     if (deviceSetIndex >= 0)
     {
         DeviceSet *deviceSet = m_deviceSets[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine) // source device => Rx channels
         {
             deviceSet->deleteRxChannel(channelIndex);
         }
         else if (deviceSet->m_deviceSinkEngine) // sink device => Tx channels
         {
             deviceSet->deleteTxChannel(channelIndex);
         }
     }
 }
finished
void MainCore::finished () signal
Referenced by handleMessage().
getInputMessageQueue()
MessageQueue* MainCore::getInputMessageQueue () inline
Definition at line 56 of file maincore.h.
Referenced by WebAPIAdapterSrv::instanceDelete().
 { return &m_inputMessageQueue; }
getInstance()
static MainCore* MainCore::getInstance () inline static
Definition at line 54 of file maincore.h.
 { return m_instance; } // Main Core is de facto a singleton so this just returns its reference
getMainSettings()
const MainSettings& MainCore::getMainSettings () const inline
Definition at line 59 of file maincore.h.
Referenced by WebAPIAdapterSrv::instanceConfigGet().
 { return m_settings; }
getMasterTimer()
const QTimer& MainCore::getMasterTimer () const inline
Definition at line 58 of file maincore.h.
 { return m_masterTimer; }
handleMessage()
bool MainCore::handleMessage (const Message & cmd) private
Definition at line 103 of file maincore.cpp.
References addChannel(), addSinkDevice(), addSourceDevice(), changeSampleSink(), changeSampleSource(), deleteChannel(), MainSettings::deletePreset(), finished(), MainCore::MsgDeleteChannel::getChannelIndex(), MainCore::MsgAddChannel::getChannelRegistrationIndex(), MainCore::MsgSetDevice::getDeviceIndex(), MainCore::MsgLoadPreset::getDeviceSetIndex(), MainCore::MsgSavePreset::getDeviceSetIndex(), MainCore::MsgSetDevice::getDeviceSetIndex(), MainCore::MsgAddChannel::getDeviceSetIndex(), MainCore::MsgDeleteChannel::getDeviceSetIndex(), MainCore::MsgSetDevice::getDeviceType(), MainCore::MsgAddDeviceSet::getDirection(), MainCore::MsgLoadPreset::getPreset(), MainCore::MsgSavePreset::getPreset(), MainCore::MsgDeletePreset::getPreset(), loadPresetSettings(), m_deviceSets, m_settings, Message::match(), removeLastDevice(), MainSettings::save(), savePresetSettings(), and MainSettings::sortPresets().
Referenced by handleMessages().
 {
     if (MsgDeleteInstance::match(cmd))
     {
         while (m_deviceSets.size() > 0)
         {
             removeLastDevice();
         }
         emit finished();
         return true;
     }
     else if (MsgLoadPreset::match(cmd))
     {
         MsgLoadPreset& notif = (MsgLoadPreset&) cmd;
         loadPresetSettings(notif.getPreset(), notif.getDeviceSetIndex());
         return true;
     }
     else if (MsgSavePreset::match(cmd))
     {
         MsgSavePreset& notif = (MsgSavePreset&) cmd;
         savePresetSettings(notif.getPreset(), notif.getDeviceSetIndex());
         m_settings.sortPresets();
         m_settings.save();
         return true;
     }
     else if (MsgDeletePreset::match(cmd))
     {
         MsgDeletePreset& notif = (MsgDeletePreset&) cmd;
         const Preset *presetToDelete = notif.getPreset();
         // remove preset from settings
         m_settings.deletePreset(presetToDelete);
         return true;
     }
     else if (MsgAddDeviceSet::match(cmd))
     {
         MsgAddDeviceSet& notif = (MsgAddDeviceSet&) cmd;
         int direction = notif.getDirection();
         if (direction == 1) { // Single stream Tx
             addSinkDevice();
         } else if (direction == 0) { // Single stream Rx
             addSourceDevice();
         } // device type not (yet) supported
         return true;
     }
     else if (MsgRemoveLastDeviceSet::match(cmd))
     {
         if (m_deviceSets.size() > 0) {
             removeLastDevice();
         }
         return true;
     }
     else if (MsgSetDevice::match(cmd))
     {
         MsgSetDevice& notif = (MsgSetDevice&) cmd;
         if (notif.getDeviceType() == 1) {
             changeSampleSink(notif.getDeviceSetIndex(), notif.getDeviceIndex());
         } else if (notif.getDeviceType() == 0) {
             changeSampleSource(notif.getDeviceSetIndex(), notif.getDeviceIndex());
         } // TODO: for MIMO
         return true;
     }
     else if (MsgAddChannel::match(cmd))
     {
         MsgAddChannel& notif = (MsgAddChannel&) cmd;
         addChannel(notif.getDeviceSetIndex(), notif.getChannelRegistrationIndex());
         return true;
     }
     else if (MsgDeleteChannel::match(cmd))
     {
         MsgDeleteChannel& notif = (MsgDeleteChannel&) cmd;
         deleteChannel(notif.getDeviceSetIndex(), notif.getChannelIndex());
         return true;
     }
     else
     {
         return false;
     }
 }
handleMessages
void MainCore::handleMessages () private slot
Definition at line 188 of file maincore.cpp.
References Message::getIdentifier(), handleMessage(), m_inputMessageQueue, and MessageQueue::pop().
Referenced by MainCore().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("MainCore::handleMessages: message: %s", message->getIdentifier());
         handleMessage(*message);
         delete message;
     }
 }
loadPresetSettings()
void MainCore::loadPresetSettings (const Preset * preset, int tabIndex) private
Definition at line 564 of file maincore.cpp.
References Preset::getDescription(), Preset::getGroup(), PluginManager::getPluginAPI(), DeviceSet::loadRxChannelSettings(), DeviceAPI::loadSamplingDeviceSettings(), DeviceSet::loadTxChannelSettings(), DeviceSet::m_deviceAPI, m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, and m_pluginManager.
Referenced by handleMessage().
 {
     qDebug("MainCore::loadPresetSettings: preset [%s | %s]",
         qPrintable(preset->getGroup()),
         qPrintable(preset->getDescription()));
     if (tabIndex >= 0)
     {
         DeviceSet *deviceSet = m_deviceSets[tabIndex];
         if (deviceSet->m_deviceSourceEngine) // source device
         {
             deviceSet->m_deviceAPI->loadSamplingDeviceSettings(preset);
             deviceSet->loadRxChannelSettings(preset, m_pluginManager->getPluginAPI());
         }
         else if (deviceSet->m_deviceSinkEngine) // sink device
         {
             deviceSet->m_deviceAPI->loadSamplingDeviceSettings(preset);
             deviceSet->loadTxChannelSettings(preset, m_pluginManager->getPluginAPI());
         }
     }
 }
loadSettings()
void MainCore::loadSettings () private
Definition at line 200 of file maincore.cpp.
References MainSettings::load(), m_settings, setLoggingOptions(), and MainSettings::sortPresets().
Referenced by MainCore().
 {
     qDebug() << "MainCore::loadSettings";
     m_settings.load();
     m_settings.sortPresets();
     setLoggingOptions();
 }
removeLastDevice()
void MainCore::removeLastDevice ()
Definition at line 348 of file maincore.cpp.
References m_deviceSets, m_dspEngine, DSPEngine::removeLastDeviceSinkEngine(), DSPEngine::removeLastDeviceSourceEngine(), DSPDeviceSourceEngine::stop(), DSPDeviceSinkEngine::stop(), DSPDeviceSourceEngine::stopAcquistion(), and DSPDeviceSinkEngine::stopGeneration().
Referenced by handleMessage(), and ~MainCore().
 {
     if (m_deviceSets.back()->m_deviceSourceEngine) // source set
     {
         DSPDeviceSourceEngine *lastDeviceEngine = m_deviceSets.back()->m_deviceSourceEngine;
         lastDeviceEngine->stopAcquistion();
         // deletes old UI and input object
         m_deviceSets.back()->freeRxChannels();      // destroys the channel instances
         m_deviceSets.back()->m_deviceAPI->resetSamplingDeviceId();
         m_deviceSets.back()->m_deviceAPI->getPluginInterface()->deleteSampleSourcePluginInstanceInput(
                 m_deviceSets.back()->m_deviceAPI->getSampleSource());
         m_deviceSets.back()->m_deviceAPI->clearBuddiesLists(); // clear old API buddies lists
         DeviceAPI *sourceAPI = m_deviceSets.back()->m_deviceAPI;
         delete m_deviceSets.back();
         lastDeviceEngine->stop();
         m_dspEngine->removeLastDeviceSourceEngine();
         delete sourceAPI;
     }
     else if (m_deviceSets.back()->m_deviceSinkEngine) // sink set
     {
         DSPDeviceSinkEngine *lastDeviceEngine = m_deviceSets.back()->m_deviceSinkEngine;
         lastDeviceEngine->stopGeneration();
         // deletes old UI and output object
         m_deviceSets.back()->freeTxChannels();
         m_deviceSets.back()->m_deviceAPI->resetSamplingDeviceId();
         m_deviceSets.back()->m_deviceAPI->getPluginInterface()->deleteSampleSinkPluginInstanceOutput(
                 m_deviceSets.back()->m_deviceAPI->getSampleSink());
         m_deviceSets.back()->m_deviceAPI->clearBuddiesLists(); // clear old API buddies lists
         DeviceAPI *sinkAPI = m_deviceSets.back()->m_deviceAPI;
         delete m_deviceSets.back();
         lastDeviceEngine->stop();
         m_dspEngine->removeLastDeviceSinkEngine();
         delete sinkAPI;
     }
     m_deviceSets.pop_back();
 }
savePresetSettings()
void MainCore::savePresetSettings (Preset * preset, int tabIndex) private
Definition at line 587 of file maincore.cpp.
References Preset::clearChannels(), Preset::getDescription(), Preset::getGroup(), DeviceSet::m_deviceAPI, m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, DeviceSet::saveRxChannelSettings(), DeviceAPI::saveSamplingDeviceSettings(), DeviceSet::saveTxChannelSettings(), and Preset::setSourcePreset().
Referenced by handleMessage().
 {
     qDebug("MainCore::savePresetSettings: preset [%s | %s]",
         qPrintable(preset->getGroup()),
         qPrintable(preset->getDescription()));
     // Save from currently selected source tab
     //int currentSourceTabIndex = ui->tabInputsView->currentIndex();
     DeviceSet *deviceSet = m_deviceSets[tabIndex];
     if (deviceSet->m_deviceSourceEngine) // source device
     {
         preset->clearChannels();
         deviceSet->saveRxChannelSettings(preset);
         deviceSet->m_deviceAPI->saveSamplingDeviceSettings(preset);
     }
     else if (deviceSet->m_deviceSinkEngine) // sink device
     {
         preset->clearChannels();
         preset->setSourcePreset(false);
         deviceSet->saveTxChannelSettings(preset);
         deviceSet->m_deviceAPI->saveSamplingDeviceSettings(preset);
     }
 }
setLoggingOptions()
void MainCore::setLoggingOptions () private
Definition at line 209 of file maincore.cpp.
References arg(), qtwebapp::LoggerWithFile::createOrSetFileLogger(), qtwebapp::FileLoggerSettings::fileName, MainSettings::getConsoleMinLogLevel(), qtwebapp::LoggerWithFile::getFileLoggerSettings(), MainSettings::getFileMinLogLevel(), MainSettings::getLogFileName(), MainSettings::getUseLogFile(), qtwebapp::LoggerWithFile::hasFileLogger(), qtwebapp::LoggerWithFile::logToFile(), m_logger, m_settings, SDR_RX_SAMP_SZ, SDR_TX_SAMP_SZ, qtwebapp::LoggerWithFile::setConsoleMinMessageLevel(), qtwebapp::LoggerWithFile::setFileMinMessageLevel(), and qtwebapp::LoggerWithFile::setUseFileLogger().
Referenced by WebAPIAdapterSrv::instanceLoggingPut(), and loadSettings().
 {
     m_logger->setConsoleMinMessageLevel(m_settings.getConsoleMinLogLevel());
     if (m_settings.getUseLogFile())
     {
         qtwebapp::FileLoggerSettings fileLoggerSettings; // default values
         if (m_logger->hasFileLogger()) {
             fileLoggerSettings = m_logger->getFileLoggerSettings(); // values from file logger if it exists
         }
         fileLoggerSettings.fileName = m_settings.getLogFileName(); // put new values
         m_logger->createOrSetFileLogger(fileLoggerSettings, 2000); // create file logger if it does not exist and apply settings in any case
     }
     if (m_logger->hasFileLogger()) {
         m_logger->setFileMinMessageLevel(m_settings.getFileMinLogLevel());
     }
     m_logger->setUseFileLogger(m_settings.getUseLogFile());
     if (m_settings.getUseLogFile())
     {
 #if QT_VERSION >= 0x050400
         QString appInfoStr(tr("%1 %2 Qt %3 %4b %5 %6 DSP Rx:%7b Tx:%8b PID %9")
                 .arg(QCoreApplication::applicationName())
                 .arg(QCoreApplication::applicationVersion())
                 .arg(QT_VERSION_STR)
                 .arg(QT_POINTER_SIZE*8)
                 .arg(QSysInfo::currentCpuArchitecture())
                 .arg(QSysInfo::prettyProductName())
                 .arg(SDR_RX_SAMP_SZ)
                 .arg(SDR_TX_SAMP_SZ)
                 .arg(QCoreApplication::applicationPid()));
 #else
         QString appInfoStr(tr("%1 %2 Qt %3 %4b DSP Rx:%5b Tx:%6b PID %7")
                 .arg(QCoreApplication::applicationName())
                 .arg(QCoreApplication::applicationVersion())
                 .arg(QT_VERSION_STR)
                 .arg(QT_POINTER_SIZE*8)
                 .arg(SDR_RX_SAMP_SZ)
                 .arg(SDR_RX_SAMP_SZ)
                 .arg(QCoreApplication::applicationPid());
  #endif
         m_logger->logToFile(QtInfoMsg, appInfoStr);
     }
 }
Friends And Related Function Documentation
WebAPIAdapterSrv
friend class WebAPIAdapterSrv friend
Definition at line 69 of file maincore.h.
Referenced by MainCore().
Member Data Documentation
m_apiAdapter
WebAPIAdapterSrv* MainCore::m_apiAdapter private
Definition at line 286 of file maincore.h.
Referenced by MainCore(), and ~MainCore().
m_apiServer
WebAPIServer* MainCore::m_apiServer private
Definition at line 285 of file maincore.h.
Referenced by MainCore(), and ~MainCore().
m_deviceSets
std::vector<DeviceSet*> MainCore::m_deviceSets private
Definition at line 281 of file maincore.h.
Referenced by addChannel(), addSinkDevice(), addSourceDevice(), changeSampleSink(), changeSampleSource(), deleteChannel(), WebAPIAdapterSrv::devicesetChannelDelete(), WebAPIAdapterSrv::devicesetChannelPost(), WebAPIAdapterSrv::devicesetChannelReportGet(), WebAPIAdapterSrv::devicesetChannelSettingsGet(), WebAPIAdapterSrv::devicesetChannelSettingsPutPatch(), WebAPIAdapterSrv::devicesetChannelsReportGet(), WebAPIAdapterSrv::devicesetDevicePut(), WebAPIAdapterSrv::devicesetDeviceReportGet(), WebAPIAdapterSrv::devicesetDeviceRunDelete(), WebAPIAdapterSrv::devicesetDeviceRunGet(), WebAPIAdapterSrv::devicesetDeviceRunPost(), WebAPIAdapterSrv::devicesetDeviceSettingsGet(), WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch(), WebAPIAdapterSrv::devicesetGet(), WebAPIAdapterSrv::getDeviceSetList(), handleMessage(), WebAPIAdapterSrv::instanceDeviceSetDelete(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterSrv::instancePresetPut(), loadPresetSettings(), removeLastDevice(), savePresetSettings(), and ~MainCore().
m_dspEngine
DSPEngine* MainCore::m_dspEngine private
Definition at line 275 of file maincore.h.
Referenced by addSinkDevice(), addSourceDevice(), WebAPIAdapterSrv::instanceAMBEDevicesDelete(), WebAPIAdapterSrv::instanceAMBEDevicesGet(), WebAPIAdapterSrv::instanceAMBEDevicesPatch(), WebAPIAdapterSrv::instanceAMBEDevicesPut(), WebAPIAdapterSrv::instanceAMBESerialGet(), WebAPIAdapterSrv::instanceAudioGet(), WebAPIAdapterSrv::instanceAudioInputCleanupPatch(), WebAPIAdapterSrv::instanceAudioInputDelete(), WebAPIAdapterSrv::instanceAudioInputPatch(), WebAPIAdapterSrv::instanceAudioOutputCleanupPatch(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputPatch(), WebAPIAdapterSrv::instanceDVSerialGet(), WebAPIAdapterSrv::instanceDVSerialPatch(), MainCore(), and removeLastDevice().
m_inputMessageQueue
MessageQueue MainCore::m_inputMessageQueue private
Definition at line 279 of file maincore.h.
Referenced by WebAPIAdapterSrv::devicesetChannelDelete(), WebAPIAdapterSrv::devicesetChannelPost(), WebAPIAdapterSrv::devicesetDevicePut(), handleMessages(), WebAPIAdapterSrv::instanceDeviceSetDelete(), WebAPIAdapterSrv::instanceDeviceSetPost(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterSrv::instancePresetPut(), and MainCore().
m_instance
MainCore * MainCore::m_instance = 0 static private
Definition at line 272 of file maincore.h.
Referenced by MainCore().
m_lastEngineState
int MainCore::m_lastEngineState private
Definition at line 276 of file maincore.h.
m_logger
qtwebapp::LoggerWithFile* MainCore::m_logger private
Definition at line 277 of file maincore.h.
Referenced by WebAPIAdapterSrv::instanceLoggingGet(), WebAPIAdapterSrv::instanceSummary(), setLoggingOptions(), and ~MainCore().
m_masterTabIndex
int MainCore::m_masterTabIndex private
Definition at line 274 of file maincore.h.
m_masterTimer
QTimer MainCore::m_masterTimer private
Definition at line 280 of file maincore.h.
Referenced by MainCore().
m_pluginManager
PluginManager* MainCore::m_pluginManager private
Definition at line 282 of file maincore.h.
Referenced by addChannel(), WebAPIAdapterSrv::devicesetChannelPost(), WebAPIAdapterSrv::instanceChannels(), loadPresetSettings(), MainCore(), and ~MainCore().
m_requestMapper
WebAPIRequestMapper* MainCore::m_requestMapper private
Definition at line 284 of file maincore.h.
Referenced by MainCore(), and ~MainCore().
m_settings
MainSettings MainCore::m_settings private
Definition at line 273 of file maincore.h.
Referenced by addSinkDevice(), addSourceDevice(), changeSampleSink(), changeSampleSource(), handleMessage(), WebAPIAdapterSrv::instanceConfigGet(), WebAPIAdapterSrv::instanceLocationGet(), WebAPIAdapterSrv::instanceLocationPut(), WebAPIAdapterSrv::instanceLoggingPut(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterSrv::instancePresetFilePut(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterSrv::instancePresetPut(), WebAPIAdapterSrv::instancePresetsGet(), loadSettings(), MainCore(), setLoggingOptions(), and ~MainCore().
The documentation for this class was generated from the following files:
sdrsrv/maincore.h
sdrsrv/maincore.cpp