SDRAngel: WebAPIAdapterInterface Class Reference
WebAPIAdapterInterface Class Reference
#include <webapiadapterinterface.h>
Public Member Functions
virtual ~WebAPIAdapterInterface ()
virtual int instanceSummary (SWGSDRangel::SWGInstanceSummaryResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceDelete (SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceConfigGet (SWGSDRangel::SWGInstanceConfigResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceDevices (int direction, SWGSDRangel::SWGInstanceDevicesResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceChannels (int direction, SWGSDRangel::SWGInstanceChannelsResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceLoggingGet (SWGSDRangel::SWGLoggingInfo &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceLoggingPut (SWGSDRangel::SWGLoggingInfo &query, SWGSDRangel::SWGLoggingInfo &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioGet (SWGSDRangel::SWGAudioDevices &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioInputPatch (SWGSDRangel::SWGAudioInputDevice &response, const QStringList &audioInputKeys, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioOutputPatch (SWGSDRangel::SWGAudioOutputDevice &response, const QStringList &audioOutputKeys, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioInputDelete (SWGSDRangel::SWGAudioInputDevice &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioOutputDelete (SWGSDRangel::SWGAudioOutputDevice &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioInputCleanupPatch (SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioOutputCleanupPatch (SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceLocationGet (SWGSDRangel::SWGLocationInformation &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceLocationPut (SWGSDRangel::SWGLocationInformation &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAMBESerialGet (SWGSDRangel::SWGDVSerialDevices &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAMBEDevicesGet (SWGSDRangel::SWGAMBEDevices &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAMBEDevicesPut (SWGSDRangel::SWGAMBEDevices &query, SWGSDRangel::SWGAMBEDevices &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAMBEDevicesPatch (SWGSDRangel::SWGAMBEDevices &query, SWGSDRangel::SWGAMBEDevices &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAMBEDevicesDelete (SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetsGet (SWGSDRangel::SWGPresets &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetPatch (SWGSDRangel::SWGPresetTransfer &query, SWGSDRangel::SWGPresetIdentifier &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetPut (SWGSDRangel::SWGPresetTransfer &query, SWGSDRangel::SWGPresetIdentifier &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetPost (SWGSDRangel::SWGPresetTransfer &query, SWGSDRangel::SWGPresetIdentifier &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetDelete (SWGSDRangel::SWGPresetIdentifier &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetFilePut (SWGSDRangel::SWGPresetImport &query, SWGSDRangel::SWGPresetIdentifier &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetFilePost (SWGSDRangel::SWGPresetExport &query, SWGSDRangel::SWGPresetIdentifier &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceDeviceSetsGet (SWGSDRangel::SWGDeviceSetList &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceDeviceSetPost (int direction, SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceDeviceSetDelete (SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetGet (int deviceSetIndex, SWGSDRangel::SWGDeviceSet &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetFocusPatch (int deviceSetIndex, SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDevicePut (int deviceSetIndex, SWGSDRangel::SWGDeviceListItem &query, SWGSDRangel::SWGDeviceListItem &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDeviceSettingsGet (int deviceSetIndex, SWGSDRangel::SWGDeviceSettings &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDeviceSettingsPutPatch (int deviceSetIndex, bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDeviceRunGet (int deviceSetIndex, SWGSDRangel::SWGDeviceState &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDeviceRunPost (int deviceSetIndex, SWGSDRangel::SWGDeviceState &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDeviceRunDelete (int deviceSetIndex, SWGSDRangel::SWGDeviceState &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDeviceReportGet (int deviceSetIndex, SWGSDRangel::SWGDeviceReport &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetChannelsReportGet (int deviceSetIndex, SWGSDRangel::SWGChannelsDetail &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetChannelPost (int deviceSetIndex, SWGSDRangel::SWGChannelSettings &query, SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetChannelDelete (int deviceSetIndex, int channelIndex, SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetChannelSettingsGet (int deviceSetIndex, int channelIndex, SWGSDRangel::SWGChannelSettings &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetChannelSettingsPutPatch (int deviceSetIndex, int channelIndex, bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetChannelReportGet (int deviceSetIndex, int channelIndex, SWGSDRangel::SWGChannelReport &response, SWGSDRangel::SWGErrorResponse &error)
Static Public Attributes
static QString instanceSummaryURL = "/sdrangel"
static QString instanceConfigURL = "/sdrangel/config"
static QString instanceDevicesURL = "/sdrangel/devices"
static QString instanceChannelsURL = "/sdrangel/channels"
static QString instanceLoggingURL = "/sdrangel/logging"
static QString instanceAudioURL = "/sdrangel/audio"
static QString instanceAudioInputParametersURL = "/sdrangel/audio/input/parameters"
static QString instanceAudioOutputParametersURL = "/sdrangel/audio/output/parameters"
static QString instanceAudioInputCleanupURL = "/sdrangel/audio/input/cleanup"
static QString instanceAudioOutputCleanupURL = "/sdrangel/audio/output/cleanup"
static QString instanceLocationURL = "/sdrangel/location"
static QString instanceAMBESerialURL = "/sdrangel/ambe/serial"
static QString instanceAMBEDevicesURL = "/sdrangel/ambe/devices"
static QString instancePresetsURL = "/sdrangel/presets"
static QString instancePresetURL = "/sdrangel/preset"
static QString instancePresetFileURL = "/sdrangel/preset/file"
static QString instanceDeviceSetsURL = "/sdrangel/devicesets"
static QString instanceDeviceSetURL = "/sdrangel/deviceset"
static std::regex devicesetURLRe
static std::regex devicesetFocusURLRe
static std::regex devicesetDeviceURLRe
static std::regex devicesetDeviceSettingsURLRe
static std::regex devicesetDeviceRunURLRe
static std::regex devicesetDeviceReportURLRe
static std::regex devicesetChannelURLRe
static std::regex devicesetChannelIndexURLRe
static std::regex devicesetChannelSettingsURLRe
static std::regex devicesetChannelReportURLRe
static std::regex devicesetChannelsReportURLRe
Detailed Description
Definition at line 60 of file webapiadapterinterface.h.
Constructor & Destructor Documentation
~WebAPIAdapterInterface()
virtual WebAPIAdapterInterface::~WebAPIAdapterInterface () inline virtual
Definition at line 63 of file webapiadapterinterface.h.
 {}
Member Function Documentation
devicesetChannelDelete()
virtual int WebAPIAdapterInterface::devicesetChannelDelete (int deviceSetIndex, int channelIndex, SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex} (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 713 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetChannelIndexService().
     {
         (void) deviceSetIndex;
         (void) channelIndex;
         (void) response;
         (void) error;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetChannelPost()
virtual int WebAPIAdapterInterface::devicesetChannelPost (int deviceSetIndex, SWGSDRangel::SWGChannelSettings & query, SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{deviceSetIndex}/channel (POST) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 695 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetChannelService().
     {
         (void) deviceSetIndex;
         (void) query;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetChannelReportGet()
virtual int WebAPIAdapterInterface::devicesetChannelReportGet (int deviceSetIndex, int channelIndex, SWGSDRangel::SWGChannelReport & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex}/settings (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 773 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetChannelReportService().
     {
         (void) deviceSetIndex;
         (void) channelIndex;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetChannelSettingsGet()
virtual int WebAPIAdapterInterface::devicesetChannelSettingsGet (int deviceSetIndex, int channelIndex, SWGSDRangel::SWGChannelSettings & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex}/settings (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 732 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetChannelSettingsService().
     {
         (void) deviceSetIndex;
         (void) channelIndex;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetChannelSettingsPutPatch()
virtual int WebAPIAdapterInterface::devicesetChannelSettingsPutPatch (int deviceSetIndex, int channelIndex, bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex}/settings (PUT, PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 750 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetChannelSettingsService().
     {
         (void) deviceSetIndex;
         (void) channelIndex;
         (void) force;
         (void) channelSettingsKeys;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetChannelsReportGet()
virtual int WebAPIAdapterInterface::devicesetChannelsReportGet (int deviceSetIndex, SWGSDRangel::SWGChannelsDetail & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/channels/report (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 679 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetChannelsReportService().
     {
         (void) deviceSetIndex;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetDevicePut()
virtual int WebAPIAdapterInterface::devicesetDevicePut (int deviceSetIndex, SWGSDRangel::SWGDeviceListItem & query, SWGSDRangel::SWGDeviceListItem & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 561 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetDeviceService().
     {
         (void) deviceSetIndex;
         (void) query;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetDeviceReportGet()
virtual int WebAPIAdapterInterface::devicesetDeviceReportGet (int deviceSetIndex, SWGSDRangel::SWGDeviceReport & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device/report (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 663 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetDeviceReportService().
     {
         (void) deviceSetIndex;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetDeviceRunDelete()
virtual int WebAPIAdapterInterface::devicesetDeviceRunDelete (int deviceSetIndex, SWGSDRangel::SWGDeviceState & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device/run (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 647 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetDeviceRunService().
     {
         (void) deviceSetIndex;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetDeviceRunGet()
virtual int WebAPIAdapterInterface::devicesetDeviceRunGet (int deviceSetIndex, SWGSDRangel::SWGDeviceState & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device/run (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 615 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetDeviceRunService().
     {
         (void) deviceSetIndex;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetDeviceRunPost()
virtual int WebAPIAdapterInterface::devicesetDeviceRunPost (int deviceSetIndex, SWGSDRangel::SWGDeviceState & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device/run (POST) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 631 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetDeviceRunService().
     {
         (void) deviceSetIndex;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetDeviceSettingsGet()
virtual int WebAPIAdapterInterface::devicesetDeviceSettingsGet (int deviceSetIndex, SWGSDRangel::SWGDeviceSettings & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device/settings (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 579 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetDeviceSettingsService().
     {
         (void) deviceSetIndex;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetDeviceSettingsPutPatch()
virtual int WebAPIAdapterInterface::devicesetDeviceSettingsPutPatch (int deviceSetIndex, bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device/settings (PUT, PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Parameters
force true to force settings = put else patch
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 595 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetDeviceSettingsService().
     {
         (void) deviceSetIndex;
         (void) force;
         (void) channelSettingsKeys;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetFocusPatch()
virtual int WebAPIAdapterInterface::devicesetFocusPatch (int deviceSetIndex, SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/focus (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 545 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetFocusService().
     {
         (void) deviceSetIndex;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
devicesetGet()
virtual int WebAPIAdapterInterface::devicesetGet (int deviceSetIndex, SWGSDRangel::SWGDeviceSet & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset/{devicesetIndex} (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 529 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::devicesetService().
     {
         (void) deviceSetIndex;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceAMBEDevicesDelete()
virtual int WebAPIAdapterInterface::instanceAMBEDevicesDelete (SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/ambe/devices (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 363 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceAMBEDevicesService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceAMBEDevicesGet()
virtual int WebAPIAdapterInterface::instanceAMBEDevicesGet (SWGSDRangel::SWGAMBEDevices & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/ambe/devices (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 317 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceAMBEDevicesService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceAMBEDevicesPatch()
virtual int WebAPIAdapterInterface::instanceAMBEDevicesPatch (SWGSDRangel::SWGAMBEDevices & query, SWGSDRangel::SWGAMBEDevices & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/ambe/devices (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 347 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceAMBEDevicesService().
     {
         (void) query;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceAMBEDevicesPut()
virtual int WebAPIAdapterInterface::instanceAMBEDevicesPut (SWGSDRangel::SWGAMBEDevices & query, SWGSDRangel::SWGAMBEDevices & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/ambe/devices (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 331 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceAMBEDevicesService().
     {
         (void) query;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceAMBESerialGet()
virtual int WebAPIAdapterInterface::instanceAMBESerialGet (SWGSDRangel::SWGDVSerialDevices & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/ambe/serial (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 303 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceAMBESerialService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceAudioGet()
virtual int WebAPIAdapterInterface::instanceAudioGet (SWGSDRangel::SWGAudioDevices & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/audio (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 173 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceAudioService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceAudioInputCleanupPatch()
virtual int WebAPIAdapterInterface::instanceAudioInputCleanupPatch (SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/audio/input/cleanup (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 247 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceAudioInputCleanupService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceAudioInputDelete()
virtual int WebAPIAdapterInterface::instanceAudioInputDelete (SWGSDRangel::SWGAudioInputDevice & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/audio/input/parameters (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 219 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceAudioInputParametersService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceAudioInputPatch()
virtual int WebAPIAdapterInterface::instanceAudioInputPatch (SWGSDRangel::SWGAudioInputDevice & response, const QStringList & audioInputKeys, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/audio/input/parameters (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 187 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceAudioInputParametersService().
     {
         (void) response;
         (void) audioInputKeys;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceAudioOutputCleanupPatch()
virtual int WebAPIAdapterInterface::instanceAudioOutputCleanupPatch (SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/audio/output/cleanup (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 261 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceAudioOutputCleanupService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceAudioOutputDelete()
virtual int WebAPIAdapterInterface::instanceAudioOutputDelete (SWGSDRangel::SWGAudioOutputDevice & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/audio/output/paramaters (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 233 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceAudioOutputParametersService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceAudioOutputPatch()
virtual int WebAPIAdapterInterface::instanceAudioOutputPatch (SWGSDRangel::SWGAudioOutputDevice & response, const QStringList & audioOutputKeys, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/audio/output/parameters (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 203 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceAudioOutputParametersService().
     {
         (void) response;
         (void) audioOutputKeys;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceChannels()
virtual int WebAPIAdapterInterface::instanceChannels (int direction, SWGSDRangel::SWGInstanceChannelsResponse & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/channels (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 127 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceChannelsService().
     {
         (void) direction;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceConfigGet()
virtual int WebAPIAdapterInterface::instanceConfigGet (SWGSDRangel::SWGInstanceConfigResponse & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/config (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceSummary returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 97 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceConfigService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceDelete()
virtual int WebAPIAdapterInterface::instanceDelete (SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceSummary returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 83 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceSummaryService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceDevices()
virtual int WebAPIAdapterInterface::instanceDevices (int direction, SWGSDRangel::SWGInstanceDevicesResponse & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/devices (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceDevices returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 111 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceDevicesService().
     {
         (void) direction;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceDeviceSetDelete()
virtual int WebAPIAdapterInterface::instanceDeviceSetDelete (SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 515 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceDeviceSetService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceDeviceSetPost()
virtual int WebAPIAdapterInterface::instanceDeviceSetPost (int direction, SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/deviceset (POST) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 499 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceDeviceSetService().
     {
         (void) direction;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceDeviceSetsGet()
virtual int WebAPIAdapterInterface::instanceDeviceSetsGet (SWGSDRangel::SWGDeviceSetList & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/devicesets (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 485 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceDeviceSetsService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceLocationGet()
virtual int WebAPIAdapterInterface::instanceLocationGet (SWGSDRangel::SWGLocationInformation & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/location (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 275 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceLocationService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceLocationPut()
virtual int WebAPIAdapterInterface::instanceLocationPut (SWGSDRangel::SWGLocationInformation & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/location (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 289 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceLocationService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceLoggingGet()
virtual int WebAPIAdapterInterface::instanceLoggingGet (SWGSDRangel::SWGLoggingInfo & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/logging (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 143 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceLoggingService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceLoggingPut()
virtual int WebAPIAdapterInterface::instanceLoggingPut (SWGSDRangel::SWGLoggingInfo & query, SWGSDRangel::SWGLoggingInfo & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/logging (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 157 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceLoggingService().
     {
         (void) query;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instancePresetDelete()
virtual int WebAPIAdapterInterface::instancePresetDelete (SWGSDRangel::SWGPresetIdentifier & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/preset (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 439 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instancePresetService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instancePresetFilePost()
virtual int WebAPIAdapterInterface::instancePresetFilePost (SWGSDRangel::SWGPresetExport & query, SWGSDRangel::SWGPresetIdentifier & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/preset/file (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv.
Definition at line 469 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instancePresetFileService().
     {
         (void) query;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instancePresetFilePut()
virtual int WebAPIAdapterInterface::instancePresetFilePut (SWGSDRangel::SWGPresetImport & query, SWGSDRangel::SWGPresetIdentifier & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/preset/file (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv.
Definition at line 453 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instancePresetFileService().
     {
         (void) query;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instancePresetPatch()
virtual int WebAPIAdapterInterface::instancePresetPatch (SWGSDRangel::SWGPresetTransfer & query, SWGSDRangel::SWGPresetIdentifier & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/preset (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 391 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instancePresetService().
     {
         (void) query;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instancePresetPost()
virtual int WebAPIAdapterInterface::instancePresetPost (SWGSDRangel::SWGPresetTransfer & query, SWGSDRangel::SWGPresetIdentifier & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/preset (POST) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 423 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instancePresetService().
     {
         (void) query;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instancePresetPut()
virtual int WebAPIAdapterInterface::instancePresetPut (SWGSDRangel::SWGPresetTransfer & query, SWGSDRangel::SWGPresetIdentifier & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/preset (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 407 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instancePresetService().
     {
         (void) query;
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instancePresetsGet()
virtual int WebAPIAdapterInterface::instancePresetsGet (SWGSDRangel::SWGPresets & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel/presets (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterSrv, and WebAPIAdapterGUI.
Definition at line 377 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instancePresetsService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
instanceSummary()
virtual int WebAPIAdapterInterface::instanceSummary (SWGSDRangel::SWGInstanceSummaryResponse & response, SWGSDRangel::SWGErrorResponse & error) inline virtual
Handler of /sdrangel (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceSummary returns the Http status code (default 501: not implemented)
Reimplemented in WebAPIAdapterGUI, and WebAPIAdapterSrv.
Definition at line 69 of file webapiadapterinterface.h.
References SWGSDRangel::SWGErrorResponse::getMessage(), and SWGSDRangel::SWGErrorResponse::init().
Referenced by WebAPIRequestMapper::instanceSummaryService().
     {
         (void) response;
         error.init();
         *error.getMessage() = QString("Function not implemented");
         return 501;
     }
Member Data Documentation
devicesetChannelIndexURLRe
std::regex WebAPIAdapterInterface::devicesetChannelIndexURLRe static
Definition at line 812 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
devicesetChannelReportURLRe
std::regex WebAPIAdapterInterface::devicesetChannelReportURLRe static
Definition at line 814 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
devicesetChannelSettingsURLRe
std::regex WebAPIAdapterInterface::devicesetChannelSettingsURLRe static
Definition at line 813 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
devicesetChannelsReportURLRe
std::regex WebAPIAdapterInterface::devicesetChannelsReportURLRe static
Definition at line 815 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
devicesetChannelURLRe
std::regex WebAPIAdapterInterface::devicesetChannelURLRe static
Definition at line 811 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
devicesetDeviceReportURLRe
std::regex WebAPIAdapterInterface::devicesetDeviceReportURLRe static
Definition at line 810 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
devicesetDeviceRunURLRe
std::regex WebAPIAdapterInterface::devicesetDeviceRunURLRe static
Definition at line 809 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
devicesetDeviceSettingsURLRe
std::regex WebAPIAdapterInterface::devicesetDeviceSettingsURLRe static
Definition at line 808 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
devicesetDeviceURLRe
std::regex WebAPIAdapterInterface::devicesetDeviceURLRe static
Definition at line 807 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
devicesetFocusURLRe
std::regex WebAPIAdapterInterface::devicesetFocusURLRe static
Definition at line 806 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
devicesetURLRe
std::regex WebAPIAdapterInterface::devicesetURLRe static
Definition at line 805 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceAMBEDevicesURL
QString WebAPIAdapterInterface::instanceAMBEDevicesURL = "/sdrangel/ambe/devices" static
Definition at line 799 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceAMBESerialURL
QString WebAPIAdapterInterface::instanceAMBESerialURL = "/sdrangel/ambe/serial" static
Definition at line 798 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceAudioInputCleanupURL
QString WebAPIAdapterInterface::instanceAudioInputCleanupURL = "/sdrangel/audio/input/cleanup" static
Definition at line 795 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceAudioInputParametersURL
QString WebAPIAdapterInterface::instanceAudioInputParametersURL = "/sdrangel/audio/input/parameters" static
Definition at line 793 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceAudioOutputCleanupURL
QString WebAPIAdapterInterface::instanceAudioOutputCleanupURL = "/sdrangel/audio/output/cleanup" static
Definition at line 796 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceAudioOutputParametersURL
QString WebAPIAdapterInterface::instanceAudioOutputParametersURL = "/sdrangel/audio/output/parameters" static
Definition at line 794 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceAudioURL
QString WebAPIAdapterInterface::instanceAudioURL = "/sdrangel/audio" static
Definition at line 792 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceChannelsURL
QString WebAPIAdapterInterface::instanceChannelsURL = "/sdrangel/channels" static
Definition at line 790 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceConfigURL
QString WebAPIAdapterInterface::instanceConfigURL = "/sdrangel/config" static
Definition at line 788 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceDeviceSetsURL
QString WebAPIAdapterInterface::instanceDeviceSetsURL = "/sdrangel/devicesets" static
Definition at line 803 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceDeviceSetURL
QString WebAPIAdapterInterface::instanceDeviceSetURL = "/sdrangel/deviceset" static
Definition at line 804 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceDevicesURL
QString WebAPIAdapterInterface::instanceDevicesURL = "/sdrangel/devices" static
Definition at line 789 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceLocationURL
QString WebAPIAdapterInterface::instanceLocationURL = "/sdrangel/location" static
Definition at line 797 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceLoggingURL
QString WebAPIAdapterInterface::instanceLoggingURL = "/sdrangel/logging" static
Definition at line 791 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instancePresetFileURL
QString WebAPIAdapterInterface::instancePresetFileURL = "/sdrangel/preset/file" static
Definition at line 802 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instancePresetsURL
QString WebAPIAdapterInterface::instancePresetsURL = "/sdrangel/presets" static
Definition at line 800 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instancePresetURL
QString WebAPIAdapterInterface::instancePresetURL = "/sdrangel/preset" static
Definition at line 801 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
instanceSummaryURL
QString WebAPIAdapterInterface::instanceSummaryURL = "/sdrangel" static
Definition at line 787 of file webapiadapterinterface.h.
Referenced by WebAPIRequestMapper::service().
The documentation for this class was generated from the following files:
sdrbase/webapi/webapiadapterinterface.h
sdrbase/webapi/webapiadapterinterface.cpp