SDRAngel: HackRFOutputPlugin Class Reference
HackRFOutputPlugin Class Reference
#include <hackrfoutputplugin.h>
Public Member Functions
HackRFOutputPlugin (QObject *parent=NULL)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "HackRF"
static const QString m_deviceTypeID = HACKRFOUTPUT_DEVICE_TYPE_ID
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 28 of file hackrfoutputplugin.h.
Constructor & Destructor Documentation
HackRFOutputPlugin()
HackRFOutputPlugin::HackRFOutputPlugin (QObject * parent = NULL) explicit
Definition at line 43 of file hackrfoutputplugin.cpp.
                                                       :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSinkPluginInstance()
DeviceSampleSink * HackRFOutputPlugin::createSampleSinkPluginInstance (const QString & sinkId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 154 of file hackrfoutputplugin.cpp.
References m_deviceTypeID.
 {
     if(sinkId == m_deviceTypeID)
     {
         HackRFOutput* output = new HackRFOutput(deviceAPI);
         return output;
     }
     else
     {
         return 0;
     }
 }
createSampleSinkPluginInstanceGUI()
PluginInstanceGUI * HackRFOutputPlugin::createSampleSinkPluginInstanceGUI (const QString & sinkId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 136 of file hackrfoutputplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSinks().
 {
     if(sinkId == m_deviceTypeID)
     {
         HackRFOutputGui* gui = new HackRFOutputGui(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSinks()
PluginInterface::SamplingDevices HackRFOutputPlugin::enumSampleSinks () virtual
Reimplemented from PluginInterface.
Definition at line 58 of file hackrfoutputplugin.cpp.
References arg(), createSampleSinkPluginInstanceGUI(), i, m_deviceTypeID, m_hardwareID, PluginInterface::SamplingDevice::PhysicalDevice, and PluginInterface::SamplingDevice::StreamSingleTx.
 {
 //  hackrf_error rc = (hackrf_error) hackrf_init();
 //
 //  if (rc != HACKRF_SUCCESS)
 //  {
 //      qCritical("HackRFOutputPlugin::enumSampleSinks: failed to initiate HackRF library: %s", hackrf_error_name(rc));
 //  }
     SamplingDevices result;
     hackrf_device_list_t *hackrf_devices = hackrf_device_list();
     hackrf_device *hackrf_ptr;
     read_partid_serialno_t read_partid_serialno;
     int i;
     for (i=0; i < hackrf_devices->devicecount; i++)
     {
         hackrf_error rc = (hackrf_error) hackrf_device_list_open(hackrf_devices, i, &hackrf_ptr);
         if (rc == HACKRF_SUCCESS)
         {
             qDebug("HackRFOutputPlugin::enumSampleSinks: try to enumerate HackRF device #%d", i);
             rc = (hackrf_error) hackrf_board_partid_serialno_read(hackrf_ptr, &read_partid_serialno);
             if (rc != HACKRF_SUCCESS)
             {
                 qDebug("HackRFOutputPlugin::enumSampleSinks: failed to read serial no: %s", hackrf_error_name(rc));
                 hackrf_close(hackrf_ptr);
                 continue; // next
             }
             uint32_t serial_msb = read_partid_serialno.serial_no[2];
             uint32_t serial_lsb = read_partid_serialno.serial_no[3];
             QString serial_str = QString::number(serial_msb, 16) + QString::number(serial_lsb, 16);
             //uint64_t serial_num = (((uint64_t) serial_msb)<<32) + serial_lsb;
             QString displayedName(QString("HackRF[%1] %2").arg(i).arg(serial_str));
             result.append(SamplingDevice(displayedName,
                     m_hardwareID,
                     m_deviceTypeID,
                     serial_str,
                     i,
                     PluginInterface::SamplingDevice::PhysicalDevice,
                     PluginInterface::SamplingDevice::StreamSingleTx,
                     1,
                     0));
             qDebug("HackRFOutputPlugin::enumSampleSinks: enumerated HackRF device #%d", i);
             hackrf_close(hackrf_ptr);
         }
         else
         {
             qDebug("HackRFOutputPlugin::enumSampleSinks: failed to enumerate HackRF device #%d: %s", i, hackrf_error_name(rc));
         }
     }
     hackrf_device_list_free(hackrf_devices);
 //  rc = (hackrf_error) hackrf_exit();
 //  qDebug("HackRFOutputPlugin::enumSampleSinks: hackrf_exit: %s", hackrf_error_name(rc));
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & HackRFOutputPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 48 of file hackrfoutputplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void HackRFOutputPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 53 of file hackrfoutputplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSink().
 {
     pluginAPI->registerSampleSink(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString HackRFOutputPlugin::m_deviceTypeID = HACKRFOUTPUT_DEVICE_TYPE_ID static
Definition at line 47 of file hackrfoutputplugin.h.
Referenced by createSampleSinkPluginInstance(), createSampleSinkPluginInstanceGUI(), enumSampleSinks(), and initPlugin().
m_hardwareID
const QString HackRFOutputPlugin::m_hardwareID = "HackRF" static
Definition at line 46 of file hackrfoutputplugin.h.
Referenced by enumSampleSinks().
m_pluginDescriptor
const PluginDescriptor HackRFOutputPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("HackRF Output"),
    QString("4.5.5"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 50 of file hackrfoutputplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesink/hackrfoutput/hackrfoutputplugin.h
plugins/samplesink/hackrfoutput/hackrfoutputplugin.cpp