SDRAngel: PlutoSDRInputThread Class Reference
PlutoSDRInputThread Class Reference
#include <plutosdrinputthread.h>
Public Member Functions
PlutoSDRInputThread (uint32_t blocksize, DevicePlutoSDRBox *plutoBox, SampleSinkFifo *sampleFifo, QObject *parent=0)
~PlutoSDRInputThread ()
virtual void startWork ()
virtual void stopWork ()
virtual void setDeviceSampleRate (int sampleRate)
virtual bool isRunning ()
void setLog2Decimation (unsigned int log2_decim)
void setFcPos (int fcPos)
Private Member Functions
void run ()
void convert (const qint16 *buf, qint32 len)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
DevicePlutoSDRBox * m_plutoBox
int16_t * m_buf
holds I+Q values of each sample from devce
int16_t * m_bufConv
holds I+Q values of each sample converted to host format via iio_channel_convert
uint32_t m_blockSizeSamples
buffer sizes in number of (I,Q) samples
SampleVector m_convertBuffer
vector of (I,Q) samples used for decimation and scaling conversion
SampleVector::iterator m_convertIt
SampleSinkFifo * m_sampleFifo
DSP sample FIFO (I,Q)
unsigned int m_log2Decim
int m_fcPos
float m_phasor
Decimators< qint32, qint16, SDR_RX_SAMP_SZ, 12 > m_decimators
Detailed Description
Definition at line 31 of file plutosdrinputthread.h.
Constructor & Destructor Documentation
PlutoSDRInputThread()
PlutoSDRInputThread::PlutoSDRInputThread (uint32_t blocksize, DevicePlutoSDRBox * plutoBox, SampleSinkFifo * sampleFifo, QObject * parent = 0)
Definition at line 24 of file plutosdrinputthread.cpp.
References m_buf, and m_bufConv.
                                                                                                                                             :
     QThread(parent),
     m_running(false),
     m_plutoBox(plutoBox),
     m_blockSizeSamples(blocksizeSamples),
     m_convertBuffer(blocksizeSamples),
     m_convertIt(m_convertBuffer.begin()),
     m_sampleFifo(sampleFifo),
     m_log2Decim(0),
     m_fcPos(PlutoSDRInputSettings::FC_POS_CENTER),
     m_phasor(0)
 {
     m_buf     = new qint16[blocksizeSamples*2]; // (I,Q) -> 2 * int16_t
     m_bufConv = new qint16[blocksizeSamples*2]; // (I,Q) -> 2 * int16_t
 }
~PlutoSDRInputThread()
PlutoSDRInputThread::~PlutoSDRInputThread ()
Definition at line 40 of file plutosdrinputthread.cpp.
References m_buf, and stopWork().
 {
     stopWork();
     delete[] m_buf;
 }
Member Function Documentation
convert()
void PlutoSDRInputThread::convert (const qint16 * buf, qint32 len) private
Definition at line 150 of file plutosdrinputthread.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup(), m_convertBuffer, m_decimators, m_fcPos, m_log2Decim, m_sampleFifo, and SampleSinkFifo::write().
Referenced by run().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     if (m_log2Decim == 0)
     {
         m_decimators.decimate1(&it, buf, len);
     }
     else
     {
         if (m_fcPos == 0) // Infra
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_inf(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_inf(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_inf(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_inf(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_inf(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_inf(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 1) // Supra
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_sup(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_sup(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_sup(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_sup(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_sup(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_sup(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 2) // Center
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_cen(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_cen(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_cen(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_cen(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_cen(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_cen(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
     }
     m_sampleFifo->write(m_convertBuffer.begin(), it);
 }
isRunning()
virtual bool PlutoSDRInputThread::isRunning () inline virtual
Implements DevicePlutoSDRShared::ThreadInterface.
Definition at line 42 of file plutosdrinputthread.h.
References m_running, setFcPos(), and setLog2Decimation().
Referenced by PlutoSDRInput::applySettings().
 { return m_running; }
run()
void PlutoSDRInputThread::run () private
Definition at line 75 of file plutosdrinputthread.cpp.
References convert(), DevicePlutoSDRBox::getRxSampleSize(), DevicePlutoSDRBox::getTxSampleSize(), m_blockSizeSamples, m_buf, m_plutoBox, m_running, m_startWaiter, DevicePlutoSDRBox::rxBufferEnd(), DevicePlutoSDRBox::rxBufferFirst(), DevicePlutoSDRBox::rxBufferRefill(), and DevicePlutoSDRBox::rxBufferStep().
 {
     std::ptrdiff_t p_inc = m_plutoBox->rxBufferStep();
     qDebug("PlutoSDRInputThread::run: rxBufferStep: %ld bytes", p_inc);
     qDebug("PlutoSDRInputThread::run: Rx sample size is %ld bytes", m_plutoBox->getRxSampleSize());
     qDebug("PlutoSDRInputThread::run: Tx sample size is %ld bytes", m_plutoBox->getTxSampleSize());
     qDebug("PlutoSDRInputThread::run: nominal nbytes_rx is %d bytes with 2 refills", m_blockSizeSamples*2);
     m_running = true;
     m_startWaiter.wakeAll();
     while (m_running)
     {
         ssize_t nbytes_rx;
         char *p_dat, *p_end;
         int ihs; // half sample index (I then Q to make a sample)
         // Refill RX buffer
         nbytes_rx = m_plutoBox->rxBufferRefill();
         if (nbytes_rx != m_blockSizeSamples*2)
         {
             qWarning("PlutoSDRInputThread::run: error refilling buf (1) %d / %d",(int) nbytes_rx, (int)  m_blockSizeSamples*2);
             usleep(200000);
             continue;
         }
         // READ: Get pointers to RX buf and read IQ from RX buf port 0
         p_end = m_plutoBox->rxBufferEnd();
         ihs = 0;
         // p_inc is 2 on a char* buffer therefore each iteration processes only the I or Q sample
         // I and Q samples are processed one after the other
         // conversion is not needed as samples are little endian
         for (p_dat = m_plutoBox->rxBufferFirst(); p_dat < p_end; p_dat += p_inc)
         {
             m_buf[ihs] = *((int16_t *) p_dat);
 //            iio_channel_convert(m_plutoBox->getRxChannel0(), (void *) &m_bufConv[ihs], (const void *) &m_buf[ihs]);
             ihs++;
         }
         // Refill RX buffer again - we still need twice more samples to complete since they come as I followed by Q
         nbytes_rx = m_plutoBox->rxBufferRefill();
         if (nbytes_rx != m_blockSizeSamples*2)
         {
             qWarning("PlutoSDRInputThread::run: error refilling buf (2) %d / %d",(int) nbytes_rx, (int)  m_blockSizeSamples*2);
             usleep(200000);
             continue;
         }
         // READ: Get pointers to RX buf and read IQ from RX buf port 0
         p_end = m_plutoBox->rxBufferEnd();
         // p_inc is 2 on a char* buffer therefore each iteration processes only the I or Q sample
         // I and Q samples are processed one after the other
         // conversion is not needed as samples are little endian
         for (p_dat = m_plutoBox->rxBufferFirst(); p_dat < p_end; p_dat += p_inc)
         {
             m_buf[ihs] = *((int16_t *) p_dat);
 //            iio_channel_convert(m_plutoBox->getRxChannel0(), (void *) &m_bufConv[ihs], (const void *) &m_buf[ihs]);
             ihs++;
         }
         //m_sampleFifo->write((unsigned char *) m_buf, ihs*sizeof(int16_t));
         convert(m_buf, 2*m_blockSizeSamples); // size given in number of int16_t (I and Q interleaved)
     }
     m_running = false;
 }
setDeviceSampleRate()
virtual void PlutoSDRInputThread::setDeviceSampleRate (int sampleRate) inline virtual
Implements DevicePlutoSDRShared::ThreadInterface.
Definition at line 41 of file plutosdrinputthread.h.
 { (void) sampleRate; }
setFcPos()
void PlutoSDRInputThread::setFcPos (int fcPos)
Definition at line 70 of file plutosdrinputthread.cpp.
References m_fcPos.
Referenced by PlutoSDRInput::applySettings(), and isRunning().
 {
     m_fcPos = fcPos;
 }
setLog2Decimation()
void PlutoSDRInputThread::setLog2Decimation (unsigned int log2_decim)
Definition at line 65 of file plutosdrinputthread.cpp.
References m_log2Decim.
Referenced by PlutoSDRInput::applySettings(), isRunning(), and PlutoSDRInput::start().
 {
     m_log2Decim = log2_decim;
 }
startWork()
void PlutoSDRInputThread::startWork () virtual
Implements DevicePlutoSDRShared::ThreadInterface.
Definition at line 46 of file plutosdrinputthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by PlutoSDRInput::applySettings(), and PlutoSDRInput::start().
 {
     if (m_running) return; // return if running already
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void PlutoSDRInputThread::stopWork () virtual
Implements DevicePlutoSDRShared::ThreadInterface.
Definition at line 57 of file plutosdrinputthread.cpp.
References m_running.
Referenced by PlutoSDRInput::applySettings(), PlutoSDRInput::stop(), and ~PlutoSDRInputThread().
 {
     if (!m_running) return; // return if not running
     m_running = false;
     wait();
 }
Member Data Documentation
m_blockSizeSamples
uint32_t PlutoSDRInputThread::m_blockSizeSamples private
buffer sizes in number of (I,Q) samples
Definition at line 54 of file plutosdrinputthread.h.
Referenced by run().
m_buf
int16_t* PlutoSDRInputThread::m_buf private
holds I+Q values of each sample from devce
Definition at line 52 of file plutosdrinputthread.h.
Referenced by PlutoSDRInputThread(), run(), and ~PlutoSDRInputThread().
m_bufConv
int16_t* PlutoSDRInputThread::m_bufConv private
holds I+Q values of each sample converted to host format via iio_channel_convert
Definition at line 53 of file plutosdrinputthread.h.
Referenced by PlutoSDRInputThread().
m_convertBuffer
SampleVector PlutoSDRInputThread::m_convertBuffer private
vector of (I,Q) samples used for decimation and scaling conversion
Definition at line 55 of file plutosdrinputthread.h.
Referenced by convert().
m_convertIt
SampleVector::iterator PlutoSDRInputThread::m_convertIt private
Definition at line 56 of file plutosdrinputthread.h.
m_decimators
Decimators<qint32, qint16, SDR_RX_SAMP_SZ, 12> PlutoSDRInputThread::m_decimators private
Definition at line 63 of file plutosdrinputthread.h.
Referenced by convert().
m_fcPos
int PlutoSDRInputThread::m_fcPos private
Definition at line 60 of file plutosdrinputthread.h.
Referenced by convert(), and setFcPos().
m_log2Decim
unsigned int PlutoSDRInputThread::m_log2Decim private
Definition at line 59 of file plutosdrinputthread.h.
Referenced by convert(), and setLog2Decimation().
m_phasor
float PlutoSDRInputThread::m_phasor private
Definition at line 61 of file plutosdrinputthread.h.
m_plutoBox
DevicePlutoSDRBox* PlutoSDRInputThread::m_plutoBox private
Definition at line 51 of file plutosdrinputthread.h.
Referenced by run().
m_running
bool PlutoSDRInputThread::m_running private
Definition at line 49 of file plutosdrinputthread.h.
Referenced by isRunning(), run(), startWork(), and stopWork().
m_sampleFifo
SampleSinkFifo* PlutoSDRInputThread::m_sampleFifo private
DSP sample FIFO (I,Q)
Definition at line 57 of file plutosdrinputthread.h.
Referenced by convert().
m_startWaiter
QWaitCondition PlutoSDRInputThread::m_startWaiter private
Definition at line 48 of file plutosdrinputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex PlutoSDRInputThread::m_startWaitMutex private
Definition at line 47 of file plutosdrinputthread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/samplesource/plutosdrinput/plutosdrinputthread.h
plugins/samplesource/plutosdrinput/plutosdrinputthread.cpp