SDRAngel: SWGSDRangel::SWGAirspyReport Class Reference
SWGSDRangel::SWGAirspyReport Class Reference
#include <SWGAirspyReport.h>
Public Member Functions
SWGAirspyReport ()
SWGAirspyReport (QString *json)
virtual ~SWGAirspyReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGAirspyReport * fromJson (QString &jsonString) override
QList< SWGSampleRate * > * getSampleRates ()
void setSampleRates (QList< SWGSampleRate *> *sample_rates)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QList< SWGSampleRate * > * sample_rates
bool m_sample_rates_isSet
Detailed Description
Definition at line 33 of file SWGAirspyReport.h.
Constructor & Destructor Documentation
SWGAirspyReport() [1/2]
SWGSDRangel::SWGAirspyReport::SWGAirspyReport ()
Definition at line 30 of file SWGAirspyReport.cpp.
References m_sample_rates_isSet, and sample_rates.
{
     sample_rates = nullptr;
     m_sample_rates_isSet = false;
 }
SWGAirspyReport() [2/2]
SWGSDRangel::SWGAirspyReport::SWGAirspyReport (QString * json)
Definition at line 25 of file SWGAirspyReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGAirspyReport()
SWGSDRangel::SWGAirspyReport::~SWGAirspyReport () virtual
Definition at line 35 of file SWGAirspyReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGAirspyReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 72 of file SWGAirspyReport.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGAirspyReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 83 of file SWGAirspyReport.cpp.
References sample_rates, and SWGSDRangel::toJsonArray().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(sample_rates->size() > 0){
         toJsonArray((QList<void*>*)sample_rates, obj, "sampleRates", "SWGSampleRate");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGAirspyReport::cleanup ()
Definition at line 46 of file SWGAirspyReport.cpp.
References sample_rates.
Referenced by ~SWGAirspyReport().
{
     if(sample_rates != nullptr) {
         auto arr = sample_rates;
         for(auto o: *arr) {
             delete o;
         }
         delete sample_rates;
     }
 }
fromJson()
SWGAirspyReport * SWGSDRangel::SWGAirspyReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 57 of file SWGAirspyReport.cpp.
References fromJsonObject().
Referenced by SWGAirspyReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGAirspyReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 66 of file SWGAirspyReport.cpp.
References sample_rates, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&sample_rates, pJson["sampleRates"], "QList", "SWGSampleRate");
 }
getSampleRates()
QList< SWGSampleRate * > * SWGSDRangel::SWGAirspyReport::getSampleRates ()
Definition at line 93 of file SWGAirspyReport.cpp.
References sample_rates.
Referenced by AirspyInput::webapiFormatDeviceReport().
{
     return sample_rates;
 }
init()
void SWGSDRangel::SWGAirspyReport::init ()
Definition at line 40 of file SWGAirspyReport.cpp.
References m_sample_rates_isSet, and sample_rates.
Referenced by SWGAirspyReport(), and AirspyInput::webapiReportGet().
                       {
     sample_rates = new QList<SWGSampleRate*>();
     m_sample_rates_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGAirspyReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 104 of file SWGAirspyReport.cpp.
References sample_rates.
Referenced by SWGSDRangel::SWGDeviceReport::asJsonObject(), and SWGSDRangel::SWGDeviceReport::isSet().
                       {
     bool isObjectUpdated = false;
     do{
         if(sample_rates->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setSampleRates()
void SWGSDRangel::SWGAirspyReport::setSampleRates (QList< SWGSampleRate *> * sample_rates)
Definition at line 97 of file SWGAirspyReport.cpp.
References m_sample_rates_isSet, and sample_rates.
Referenced by AirspyInput::webapiFormatDeviceReport().
{
     this->sample_rates = sample_rates;
     this->m_sample_rates_isSet = true;
 }
Member Data Documentation
m_sample_rates_isSet
bool SWGSDRangel::SWGAirspyReport::m_sample_rates_isSet private
Definition at line 54 of file SWGAirspyReport.h.
Referenced by init(), setSampleRates(), and SWGAirspyReport().
sample_rates
QList<SWGSampleRate*>* SWGSDRangel::SWGAirspyReport::sample_rates private
Definition at line 53 of file SWGAirspyReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSampleRates(), init(), isSet(), setSampleRates(), and SWGAirspyReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGAirspyReport.h
swagger/sdrangel/code/qt5/client/SWGAirspyReport.cpp