SDRAngel: DevicePlutoSDRShared::ThreadInterface Class Reference
DevicePlutoSDRShared::ThreadInterface Class Reference abstract
#include <deviceplutosdrshared.h>
Public Member Functions
virtual void startWork ()=0
virtual void stopWork ()=0
virtual void setDeviceSampleRate (int sampleRate)=0
virtual bool isRunning ()=0
Detailed Description
Expose own samples processing thread control
Definition at line 37 of file deviceplutosdrshared.h.
Member Function Documentation
isRunning()
virtual bool DevicePlutoSDRShared::ThreadInterface::isRunning () pure virtual
Implemented in PlutoSDROutputThread, and PlutoSDRInputThread.
setDeviceSampleRate()
virtual void DevicePlutoSDRShared::ThreadInterface::setDeviceSampleRate (int sampleRate) pure virtual
Implemented in PlutoSDROutputThread, and PlutoSDRInputThread.
startWork()
virtual void DevicePlutoSDRShared::ThreadInterface::startWork () pure virtual
Implemented in PlutoSDROutputThread, and PlutoSDRInputThread.
Referenced by PlutoSDROutput::applySettings(), PlutoSDRInput::applySettings(), PlutoSDROutput::resumeBuddies(), and PlutoSDRInput::resumeBuddies().
stopWork()
virtual void DevicePlutoSDRShared::ThreadInterface::stopWork () pure virtual
Implemented in PlutoSDROutputThread, and PlutoSDRInputThread.
Referenced by PlutoSDROutput::applySettings(), PlutoSDRInput::applySettings(), PlutoSDROutput::suspendBuddies(), and PlutoSDRInput::suspendBuddies().
The documentation for this class was generated from the following file:
devices/plutosdr/deviceplutosdrshared.h