SDRAngel: PerseusInput::MsgConfigurePerseus Class Reference
PerseusInput::MsgConfigurePerseus Class Reference
#include <perseusinput.h>
Public Member Functions
const PerseusSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigurePerseus * create (const PerseusSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigurePerseus (const PerseusSettings &settings, bool force)
Private Attributes
PerseusSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 39 of file perseusinput.h.
Constructor & Destructor Documentation
MsgConfigurePerseus()
PerseusInput::MsgConfigurePerseus::MsgConfigurePerseus (const PerseusSettings & settings, bool force) inline private
Definition at line 55 of file perseusinput.h.
Referenced by create().
                                                                          :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigurePerseus* PerseusInput::MsgConfigurePerseus::create (const PerseusSettings & settings, bool force) inline static
Definition at line 46 of file perseusinput.h.
References MsgConfigurePerseus().
Referenced by PerseusInput::deserialize(), PerseusInput::setCenterFrequency(), PerseusGui::updateHardware(), and PerseusInput::webapiSettingsPutPatch().
         {
             return new MsgConfigurePerseus(settings, force);
         }
getForce()
bool PerseusInput::MsgConfigurePerseus::getForce () const inline
Definition at line 44 of file perseusinput.h.
References m_force.
Referenced by PerseusInput::handleMessage().
 { return m_force; }
getSettings()
const PerseusSettings& PerseusInput::MsgConfigurePerseus::getSettings () const inline
Definition at line 43 of file perseusinput.h.
References m_settings.
Referenced by PerseusGui::handleMessage(), and PerseusInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool PerseusInput::MsgConfigurePerseus::m_force private
Definition at line 53 of file perseusinput.h.
Referenced by getForce().
m_settings
PerseusSettings PerseusInput::MsgConfigurePerseus::m_settings private
Definition at line 52 of file perseusinput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/perseus/perseusinput.h