SDRAngel: BFMDemod Class Reference
BFMDemod Class Reference
#include <bfmdemod.h>
Classes
struct MagSqLevelsStore
class MsgConfigureBFMDemod
class MsgConfigureChannelizer
class MsgReportChannelSampleRateChanged
Public Member Functions
BFMDemod (DeviceAPI *deviceAPI)
virtual ~BFMDemod ()
virtual void destroy ()
void setSampleSink (BasebandSampleSink *sampleSink)
int getSampleRate () const
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool po)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
double getMagSq () const
bool getPilotLock () const
Real getPilotLevel () const
Real getDecoderQua () const
bool getDecoderSynced () const
Real getDemodAcc () const
Real getDemodQua () const
Real getDemodFclk () const
void getMagSqLevels (double &avg, double &peak, int &nbSamples)
RDSParser & getRDSParser ()
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Member Functions
static int requiredBW (int rfBW)
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.bfm"
static const QString m_channelId = "BFMDemod"
Private Types
enum RateState { RSInitialFill, RSRunning }
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applyAudioSampleRate (int sampleRate)
void applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const BFMDemodSettings &settings, bool force=false)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const BFMDemodSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiFormatRDSReport (SWGSDRangel::SWGRDSReport *report)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const BFMDemodSettings &settings, bool force)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
int m_inputSampleRate
int m_inputFrequencyOffset
BFMDemodSettings m_settings
quint32 m_audioSampleRate
NCO m_nco
Interpolator m_interpolator
Interpolator between fixed demod bandwidth and audio bandwidth (rational)
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
Interpolator m_interpolatorStereo
Twin Interpolator for stereo subcarrier.
Real m_interpolatorStereoDistance
Real m_interpolatorStereoDistanceRemain
Interpolator m_interpolatorRDS
Twin Interpolator for stereo subcarrier.
Real m_interpolatorRDSDistance
Real m_interpolatorRDSDistanceRemain
Lowpass< Real > m_lowpass
fftfilt * m_rfFilter
Real m_squelchLevel
int m_squelchState
Real m_m1Arg
double m_magsq
x^-1 real sample
double m_magsqSum
double m_magsqPeak
int m_magsqCount
MagSqLevelsStore m_magSqLevelStore
AudioVector m_audioBuffer
uint m_audioBufferFill
BasebandSampleSink * m_sampleSink
AudioFifo m_audioFifo
SampleVector m_sampleBuffer
QMutex m_settingsMutex
RDSPhaseLock m_pilotPLL
Real m_pilotPLLSamples [4]
RDSDemod m_rdsDemod
RDSDecoder m_rdsDecoder
RDSParser m_rdsParser
LowPassFilterRC m_deemphasisFilterX
LowPassFilterRC m_deemphasisFilterY
Real m_fmExcursion
PhaseDiscriminators m_phaseDiscri
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Static Private Attributes
static const int filtFftLen = 1024
static const Real default_deemphasis = 50.0
static const int default_excursion = 750000
static const int m_udpBlockSize = 512
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 55 of file bfmdemod.h.
Member Enumeration Documentation
RateState
enum BFMDemod::RateState private
Enumerator
RSInitialFill
RSRunning
Definition at line 220 of file bfmdemod.h.
                    {
         RSInitialFill,
         RSRunning
     };
Constructor & Destructor Documentation
BFMDemod()
BFMDemod::BFMDemod (DeviceAPI * deviceAPI)
Definition at line 55 of file bfmdemod.cpp.
References AudioDeviceManager::addAudioSink(), DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), applyChannelSettings(), applySettings(), LowPassFilterRC::configure(), default_deemphasis, filtFftLen, DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_channelId, m_channelizer, m_deemphasisFilterX, m_deemphasisFilterY, m_deviceAPI, m_fmExcursion, m_inputFrequencyOffset, m_inputSampleRate, m_interpolatorDistance, m_interpolatorDistanceRemain, m_interpolatorRDSDistance, m_interpolatorRDSDistanceRemain, m_interpolatorStereoDistance, m_interpolatorStereoDistanceRemain, m_m1Arg, m_magsq, m_magsqCount, m_magsqPeak, m_magsqSum, m_networkManager, m_phaseDiscri, m_rfFilter, m_sampleSink, m_settings, m_squelchLevel, m_squelchState, m_threadedChannelizer, networkManagerFinished(), and PhaseDiscriminators::setFMScaling().
                                        :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(deviceAPI),
         m_inputSampleRate(384000),
         m_inputFrequencyOffset(0),
         m_audioFifo(250000),
         m_settingsMutex(QMutex::Recursive),
         m_pilotPLL(19000/384000, 50/384000, 0.01),
         m_deemphasisFilterX(default_deemphasis * 48000 * 1.0e-6),
         m_deemphasisFilterY(default_deemphasis * 48000 * 1.0e-6),
     m_fmExcursion(default_excursion)
 {
     setObjectName(m_channelId);
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSink(&m_audioFifo, getInputMessageQueue());
     m_audioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getOutputSampleRate();
     m_magsq = 0.0f;
     m_magsqSum = 0.0f;
     m_magsqPeak = 0.0f;
     m_magsqCount = 0;
     m_squelchLevel = 0;
     m_squelchState = 0;
     m_interpolatorDistance = 0.0f;
     m_interpolatorDistanceRemain = 0.0f;
     m_interpolatorRDSDistance = 0.0f;
     m_interpolatorRDSDistanceRemain = 0.0f;
     m_interpolatorStereoDistance = 0.0f;
     m_interpolatorStereoDistanceRemain = 0.0f;
     m_sampleSink = 0;
     m_m1Arg = 0;
     m_rfFilter = new fftfilt(-50000.0 / 384000.0, 50000.0 / 384000.0, filtFftLen);
     m_deemphasisFilterX.configure(default_deemphasis * m_audioSampleRate * 1.0e-6);
     m_deemphasisFilterY.configure(default_deemphasis * m_audioSampleRate * 1.0e-6);
     m_phaseDiscri.setFMScaling(384000/m_fmExcursion);
     m_audioBuffer.resize(16384);
     m_audioBufferFill = 0;
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~BFMDemod()
BFMDemod::~BFMDemod () virtual
Definition at line 113 of file bfmdemod.cpp.
References DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo, m_channelizer, m_deviceAPI, m_networkManager, m_rfFilter, m_threadedChannelizer, networkManagerFinished(), AudioDeviceManager::removeAudioSink(), DeviceAPI::removeChannelSink(), and DeviceAPI::removeChannelSinkAPI().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_audioFifo);
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete m_rfFilter;
 }
Member Function Documentation
applyAudioSampleRate()
void BFMDemod::applyAudioSampleRate (int sampleRate) private
Definition at line 386 of file bfmdemod.cpp.
References LowPassFilterRC::configure(), Interpolator::create(), default_deemphasis, BFMDemodSettings::m_afBandwidth, m_audioSampleRate, m_deemphasisFilterX, m_deemphasisFilterY, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_interpolatorStereo, m_interpolatorStereoDistance, m_interpolatorStereoDistanceRemain, m_settings, and m_settingsMutex.
Referenced by applySettings(), and handleMessage().
 {
     qDebug("BFMDemod::applyAudioSampleRate: %d", sampleRate);
     m_settingsMutex.lock();
     m_interpolator.create(16, m_inputSampleRate, m_settings.m_afBandwidth);
     m_interpolatorDistanceRemain = (Real) m_inputSampleRate / sampleRate;
     m_interpolatorDistance =  (Real) m_inputSampleRate / (Real) sampleRate;
     m_interpolatorStereo.create(16, m_inputSampleRate, m_settings.m_afBandwidth);
     m_interpolatorStereoDistanceRemain = (Real) m_inputSampleRate / sampleRate;
     m_interpolatorStereoDistance =  (Real) m_inputSampleRate / (Real) sampleRate;
     m_deemphasisFilterX.configure(default_deemphasis * sampleRate * 1.0e-6);
     m_deemphasisFilterY.configure(default_deemphasis * sampleRate * 1.0e-6);
     m_settingsMutex.unlock();
     m_audioSampleRate = sampleRate;
 }
applyChannelSettings()
void BFMDemod::applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 408 of file bfmdemod.cpp.
References PhaseLock::configure(), Interpolator::create(), fftfilt::create_filter(), BFMDemodSettings::m_afBandwidth, m_audioSampleRate, m_fmExcursion, m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_interpolatorRDS, m_interpolatorRDSDistance, m_interpolatorRDSDistanceRemain, m_interpolatorStereo, m_interpolatorStereoDistance, m_interpolatorStereoDistanceRemain, m_nco, m_phaseDiscri, m_pilotPLL, BFMDemodSettings::m_rfBandwidth, m_rfFilter, m_settings, m_settingsMutex, PhaseDiscriminators::setFMScaling(), and NCO::setFreq().
Referenced by BFMDemod(), handleMessage(), and start().
 {
     qDebug() << "BFMDemod::applyChannelSettings:"
             << " inputSampleRate: " << inputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if((inputFrequencyOffset != m_inputFrequencyOffset) ||
         (inputSampleRate != m_inputSampleRate) || force)
     {
         m_nco.setFreq(-inputFrequencyOffset, inputSampleRate);
     }
     if ((inputSampleRate != m_inputSampleRate) || force)
     {
         m_pilotPLL.configure(19000.0/inputSampleRate, 50.0/inputSampleRate, 0.01);
         m_settingsMutex.lock();
         m_interpolator.create(16, inputSampleRate, m_settings.m_afBandwidth);
         m_interpolatorDistanceRemain = (Real) inputSampleRate / m_audioSampleRate;
         m_interpolatorDistance =  (Real) inputSampleRate / (Real) m_audioSampleRate;
         m_interpolatorStereo.create(16, inputSampleRate, m_settings.m_afBandwidth);
         m_interpolatorStereoDistanceRemain = (Real) inputSampleRate / m_audioSampleRate;
         m_interpolatorStereoDistance =  (Real) inputSampleRate / (Real) m_audioSampleRate;
         m_interpolatorRDS.create(4, inputSampleRate, 600.0);
         m_interpolatorRDSDistanceRemain = (Real) inputSampleRate / 250000.0;
         m_interpolatorRDSDistance =  (Real) inputSampleRate / 250000.0;
         Real lowCut = -(m_settings.m_rfBandwidth / 2.0) / inputSampleRate;
         Real hiCut  = (m_settings.m_rfBandwidth / 2.0) / inputSampleRate;
         m_rfFilter->create_filter(lowCut, hiCut);
         m_phaseDiscri.setFMScaling(inputSampleRate / m_fmExcursion);
         m_settingsMutex.unlock();
     }
     m_inputSampleRate = inputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applySettings()
void BFMDemod::applySettings (const BFMDemodSettings & settings, bool force = false) private
Definition at line 450 of file bfmdemod.cpp.
References AudioDeviceManager::addAudioSink(), applyAudioSampleRate(), PhaseLock::configure(), Lowpass< Type >::create(), Interpolator::create(), fftfilt::create_filter(), DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputDeviceIndex(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), BFMDemodSettings::m_afBandwidth, BFMDemodSettings::m_audioDeviceName, m_audioFifo, m_audioSampleRate, BFMDemodSettings::m_audioStereo, m_fmExcursion, BFMDemodSettings::m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_interpolatorRDS, m_interpolatorRDSDistance, m_interpolatorRDSDistanceRemain, m_interpolatorStereo, m_interpolatorStereoDistance, m_interpolatorStereoDistanceRemain, m_lowpass, BFMDemodSettings::m_lsbStereo, m_phaseDiscri, m_pilotPLL, BFMDemodSettings::m_rdsActive, BFMDemodSettings::m_reverseAPIAddress, BFMDemodSettings::m_reverseAPIChannelIndex, BFMDemodSettings::m_reverseAPIDeviceIndex, BFMDemodSettings::m_reverseAPIPort, BFMDemodSettings::m_rfBandwidth, m_rfFilter, m_settings, m_settingsMutex, BFMDemodSettings::m_showPilot, BFMDemodSettings::m_squelch, m_squelchLevel, BFMDemodSettings::m_useReverseAPI, BFMDemodSettings::m_volume, PhaseDiscriminators::setFMScaling(), and webapiReverseSendSettings().
Referenced by BFMDemod(), and handleMessage().
 {
     qDebug() << "BFMDemod::applySettings: MsgConfigureBFMDemod:"
             << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
             << " m_rfBandwidth: " << settings.m_rfBandwidth
             << " m_afBandwidth: " << settings.m_afBandwidth
             << " m_volume: " << settings.m_volume
             << " m_squelch: " << settings.m_squelch
             << " m_audioStereo: " << settings.m_audioStereo
             << " m_lsbStereo: " << settings.m_lsbStereo
             << " m_showPilot: " << settings.m_showPilot
             << " m_rdsActive: " << settings.m_rdsActive
             << " m_audioDeviceName: " << settings.m_audioDeviceName
             << " m_useReverseAPI: " << settings.m_useReverseAPI
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if ((settings.m_inputFrequencyOffset != m_settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if ((settings.m_volume != m_settings.m_volume) || force) {
         reverseAPIKeys.append("volume");
     }
     if ((settings.m_audioStereo != m_settings.m_audioStereo) || force) {
         reverseAPIKeys.append("audioStereo");
     }
     if ((settings.m_lsbStereo != m_settings.m_lsbStereo) || force) {
         reverseAPIKeys.append("lsbStereo");
     }
     if ((settings.m_showPilot != m_settings.m_showPilot) || force) {
         reverseAPIKeys.append("showPilot");
     }
     if ((settings.m_rdsActive != m_settings.m_rdsActive) || force) {
         reverseAPIKeys.append("rdsActive");
     }
     if ((settings.m_audioStereo && (settings.m_audioStereo != m_settings.m_audioStereo)) || force)
     {
         m_pilotPLL.configure(19000.0/m_inputSampleRate, 50.0/m_inputSampleRate, 0.01);
     }
     if ((settings.m_afBandwidth != m_settings.m_afBandwidth) || force)
     {
         reverseAPIKeys.append("afBandwidth");
         m_settingsMutex.lock();
         m_interpolator.create(16, m_inputSampleRate, settings.m_afBandwidth);
         m_interpolatorDistanceRemain = (Real) m_inputSampleRate / m_audioSampleRate;
         m_interpolatorDistance =  (Real) m_inputSampleRate / (Real) m_audioSampleRate;
         m_interpolatorStereo.create(16, m_inputSampleRate, settings.m_afBandwidth);
         m_interpolatorStereoDistanceRemain = (Real) m_inputSampleRate / m_audioSampleRate;
         m_interpolatorStereoDistance =  (Real) m_inputSampleRate / (Real) m_audioSampleRate;
         m_interpolatorRDS.create(4, m_inputSampleRate, 600.0);
         m_interpolatorRDSDistanceRemain = (Real) m_inputSampleRate / 250000.0;
         m_interpolatorRDSDistance =  (Real) m_inputSampleRate / 250000.0;
         m_lowpass.create(21, m_audioSampleRate, settings.m_afBandwidth);
         m_settingsMutex.unlock();
     }
     if ((settings.m_rfBandwidth != m_settings.m_rfBandwidth) || force)
     {
         reverseAPIKeys.append("rfBandwidth");
         m_settingsMutex.lock();
         Real lowCut = -(settings.m_rfBandwidth / 2.0) / m_inputSampleRate;
         Real hiCut  = (settings.m_rfBandwidth / 2.0) / m_inputSampleRate;
         m_rfFilter->create_filter(lowCut, hiCut);
         m_phaseDiscri.setFMScaling(m_inputSampleRate / m_fmExcursion);
         m_settingsMutex.unlock();
     }
     if ((settings.m_squelch != m_settings.m_squelch) || force)
     {
         reverseAPIKeys.append("squelch");
         m_squelchLevel = std::pow(10.0, settings.m_squelch / 10.0);
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force)
     {
         reverseAPIKeys.append("audioDeviceName");
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getOutputDeviceIndex(settings.m_audioDeviceName);
         //qDebug("AMDemod::applySettings: audioDeviceName: %s audioDeviceIndex: %d", qPrintable(settings.m_audioDeviceName), audioDeviceIndex);
         audioDeviceManager->addAudioSink(&m_audioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getOutputSampleRate(audioDeviceIndex);
         if (m_audioSampleRate != audioSampleRate) {
             applyAudioSampleRate(audioSampleRate);
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
deserialize()
bool BFMDemod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 563 of file bfmdemod.cpp.
References BFMDemod::MsgConfigureBFMDemod::create(), BFMDemodSettings::deserialize(), BasebandSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and BFMDemodSettings::resetToDefaults().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureBFMDemod *msg = MsgConfigureBFMDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureBFMDemod *msg = MsgConfigureBFMDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void BFMDemod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 126 of file bfmdemod.h.
 { delete this; }
feed()
void BFMDemod::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool po) virtual
Implements BasebandSampleSink.
Definition at line 127 of file bfmdemod.cpp.
References cos(), Interpolator::decimate(), BasebandSampleSink::feed(), RDSDecoder::frameSync(), RDSDecoder::getGroup(), i, m_audioBuffer, m_audioBufferFill, m_audioFifo, BFMDemodSettings::m_audioStereo, m_deemphasisFilterX, m_deemphasisFilterY, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_interpolatorRDS, m_interpolatorRDSDistance, m_interpolatorRDSDistanceRemain, m_interpolatorStereo, m_interpolatorStereoDistance, m_interpolatorStereoDistanceRemain, BFMDemodSettings::m_lsbStereo, m_magsqCount, m_magsqPeak, m_magsqSum, m_nco, m_phaseDiscri, m_pilotPLL, m_pilotPLLSamples, BFMDemodSettings::m_rdsActive, m_rdsDecoder, m_rdsDemod, m_rdsParser, BFMDemodSettings::m_rfBandwidth, m_rfFilter, m_sampleBuffer, m_sampleSink, m_settings, m_settingsMutex, BFMDemodSettings::m_showPilot, m_squelchLevel, m_squelchState, BFMDemodSettings::m_volume, NCO::nextIQ(), RDSParser::parseGroup(), PhaseDiscriminators::phaseDiscriminator(), RDSDemod::process(), LowPassFilterRC::process(), PhaseLock::process(), fftfilt::runFilt(), SDR_RX_SCALEF, and AudioFifo::write().
 {
     (void) firstOfBurst;
     Complex ci, cs, cr;
     fftfilt::cmplx *rf;
     int rf_out;
     double msq;
     Real demod;
     m_sampleBuffer.clear();
     m_settingsMutex.lock();
     for (SampleVector::const_iterator it = begin; it != end; ++it)
     {
         Complex c(it->real() / SDR_RX_SCALEF, it->imag() / SDR_RX_SCALEF);
         c *= m_nco.nextIQ();
         rf_out = m_rfFilter->runFilt(c, &rf); // filter RF before demod
         for (int i =0 ; i  <rf_out; i++)
         {
             msq = rf[i].real()*rf[i].real() + rf[i].imag()*rf[i].imag();
             m_magsqSum += msq;
             if (msq > m_magsqPeak) {
                 m_magsqPeak = msq;
             }
             m_magsqCount++;
             if (msq >= m_squelchLevel)
             {
                 if (m_squelchState < m_settings.m_rfBandwidth / 10) { // twice attack and decay rate
                     m_squelchState++;
                 }
             }
             else
             {
                 if (m_squelchState > 0) {
                     m_squelchState--;
                 }
             }
             if (m_squelchState > m_settings.m_rfBandwidth / 20) { // squelch open
                 demod = m_phaseDiscri.phaseDiscriminator(rf[i]);
             } else {
                 demod = 0;
             }
             if (!m_settings.m_showPilot) {
                 m_sampleBuffer.push_back(Sample(demod * SDR_RX_SCALEF, 0.0));
             }
             if (m_settings.m_rdsActive)
             {
                 //Complex r(demod * 2.0 * std::cos(3.0 * m_pilotPLLSamples[3]), 0.0);
                 Complex r(demod * 2.0 * std::cos(3.0 * m_pilotPLLSamples[3]), 0.0);
                 if (m_interpolatorRDS.decimate(&m_interpolatorRDSDistanceRemain, r, &cr))
                 {
                     bool bit;
                     if (m_rdsDemod.process(cr.real(), bit))
                     {
                         if (m_rdsDecoder.frameSync(bit)) {
                             m_rdsParser.parseGroup(m_rdsDecoder.getGroup());
                         }
                     }
                     m_interpolatorRDSDistanceRemain += m_interpolatorRDSDistance;
                 }
             }
             Real sampleStereo = 0.0f;
             // Process stereo if stereo mode is selected
             if (m_settings.m_audioStereo)
             {
                 m_pilotPLL.process(demod, m_pilotPLLSamples);
                 if (m_settings.m_showPilot) {
                     m_sampleBuffer.push_back(Sample(m_pilotPLLSamples[1] * SDR_RX_SCALEF, 0.0)); // debug 38 kHz pilot
                 }
                 if (m_settings.m_lsbStereo)
                 {
                     // 1.17 * 0.7 = 0.819
                     Complex s(demod * m_pilotPLLSamples[1], demod * m_pilotPLLSamples[2]);
                     if (m_interpolatorStereo.decimate(&m_interpolatorStereoDistanceRemain, s, &cs))
                     {
                         sampleStereo = cs.real() + cs.imag();
                         m_interpolatorStereoDistanceRemain += m_interpolatorStereoDistance;
                     }
                 }
                 else
                 {
                     Complex s(demod * 1.17 * m_pilotPLLSamples[1], 0);
                     if (m_interpolatorStereo.decimate(&m_interpolatorStereoDistanceRemain, s, &cs))
                     {
                         sampleStereo = cs.real();
                         m_interpolatorStereoDistanceRemain += m_interpolatorStereoDistance;
                     }
                 }
             }
             Complex e(demod, 0);
             if (m_interpolator.decimate(&m_interpolatorDistanceRemain, e, &ci))
             {
                 if (m_settings.m_audioStereo)
                 {
                     Real deemph_l, deemph_r; // Pre-emphasis is applied on each channel before multiplexing
                     m_deemphasisFilterX.process(ci.real() + sampleStereo, deemph_l);
                     m_deemphasisFilterY.process(ci.real() - sampleStereo, deemph_r);
                     m_audioBuffer[m_audioBufferFill].l = (qint16)(deemph_l * (1<<12) * m_settings.m_volume);
                     m_audioBuffer[m_audioBufferFill].r = (qint16)(deemph_r * (1<<12) * m_settings.m_volume);
                 }
                 else
                 {
                     Real deemph;
                     m_deemphasisFilterX.process(ci.real(), deemph);
                     quint16 sample = (qint16)(deemph * (1<<12) * m_settings.m_volume);
                     m_audioBuffer[m_audioBufferFill].l = sample;
                     m_audioBuffer[m_audioBufferFill].r = sample;
                 }
                 ++m_audioBufferFill;
                 if (m_audioBufferFill >= m_audioBuffer.size())
                 {
                     uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
                     if(res != m_audioBufferFill) {
                         qDebug("BFMDemod::feed: %u/%u audio samples written", res, m_audioBufferFill);
                     }
                     m_audioBufferFill = 0;
                 }
                 m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
         }
     }
     if (m_audioBufferFill > 0)
     {
         uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
         if (res != m_audioBufferFill) {
             qDebug("BFMDemod::feed: %u/%u tail samples written", res, m_audioBufferFill);
         }
         m_audioBufferFill = 0;
     }
     if (m_sampleSink != 0) {
         m_sampleSink->feed(m_sampleBuffer.begin(), m_sampleBuffer.end(), true);
     }
     m_sampleBuffer.clear();
     m_settingsMutex.unlock();
 }
getCenterFrequency()
virtual qint64 BFMDemod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 137 of file bfmdemod.h.
 { return m_settings.m_inputFrequencyOffset; }
getDecoderQua()
Real BFMDemod::getDecoderQua () const inline
Definition at line 157 of file bfmdemod.h.
Referenced by BFMDemodGUI::rdsUpdate(), and webapiFormatRDSReport().
 { return m_rdsDecoder.m_qua; }
getDecoderSynced()
bool BFMDemod::getDecoderSynced () const inline
Definition at line 158 of file bfmdemod.h.
Referenced by BFMDemodGUI::rdsUpdate().
 { return m_rdsDecoder.synced(); }
getDemodAcc()
Real BFMDemod::getDemodAcc () const inline
Definition at line 159 of file bfmdemod.h.
Referenced by BFMDemodGUI::rdsUpdate(), and webapiFormatRDSReport().
 { return m_rdsDemod.m_report.acc; }
getDemodFclk()
Real BFMDemod::getDemodFclk () const inline
Definition at line 161 of file bfmdemod.h.
Referenced by BFMDemodGUI::rdsUpdate(), and webapiFormatRDSReport().
 { return m_rdsDemod.m_report.fclk; }
getDemodQua()
Real BFMDemod::getDemodQua () const inline
Definition at line 160 of file bfmdemod.h.
Referenced by BFMDemodGUI::rdsUpdate(), and webapiFormatRDSReport().
 { return m_rdsDemod.m_report.qua; }
getIdentifier()
virtual void BFMDemod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 135 of file bfmdemod.h.
 { id = objectName(); }
getMagSq()
double BFMDemod::getMagSq () const inline
Definition at line 152 of file bfmdemod.h.
 { return m_magsq; }
getMagSqLevels()
void BFMDemod::getMagSqLevels (double & avg, double & peak, int & nbSamples) inline
Definition at line 163 of file bfmdemod.h.
Referenced by BFMDemodGUI::tick(), and webapiFormatChannelReport().
     {
         if (m_magsqCount > 0)
         {
             m_magsq = m_magsqSum / m_magsqCount;
             m_magSqLevelStore.m_magsq = m_magsq;
             m_magSqLevelStore.m_magsqPeak = m_magsqPeak;
         }
         avg = m_magSqLevelStore.m_magsq;
         peak = m_magSqLevelStore.m_magsqPeak;
         nbSamples = m_magsqCount == 0 ? 1 : m_magsqCount;
         m_magsqSum = 0.0f;
         m_magsqPeak = 0.0f;
         m_magsqCount = 0;
     }
getNbSinkStreams()
virtual int BFMDemod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 142 of file bfmdemod.h.
 { return 1; }
getNbSourceStreams()
virtual int BFMDemod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 143 of file bfmdemod.h.
 { return 0; }
getPilotLevel()
Real BFMDemod::getPilotLevel () const inline
Definition at line 155 of file bfmdemod.h.
Referenced by BFMDemodGUI::tick(), and webapiFormatChannelReport().
 { return m_pilotPLL.get_pilot_level(); }
getPilotLock()
bool BFMDemod::getPilotLock () const inline
Definition at line 154 of file bfmdemod.h.
Referenced by BFMDemodGUI::tick(), and webapiFormatChannelReport().
 { return m_pilotPLL.locked(); }
getRDSParser()
RDSParser& BFMDemod::getRDSParser () inline
Definition at line 181 of file bfmdemod.h.
Referenced by BFMDemodGUI::on_clearData_clicked(), BFMDemodGUI::on_g14ProgServiceNames_currentIndexChanged(), BFMDemodGUI::rdsUpdate(), BFMDemodGUI::rdsUpdateFixedFields(), and webapiFormatRDSReport().
 { return m_rdsParser; }
getSampleRate()
int BFMDemod::getSampleRate () const inline
Definition at line 129 of file bfmdemod.h.
Referenced by handleMessage().
 { return m_inputSampleRate; }
getStreamCenterFrequency()
virtual qint64 BFMDemod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 145 of file bfmdemod.h.
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void BFMDemod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 136 of file bfmdemod.h.
 { title = m_settings.m_title; }
handleMessage()
bool BFMDemod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 307 of file bfmdemod.cpp.
References applyAudioSampleRate(), applyChannelSettings(), applySettings(), DownChannelizer::configure(), BFMDemod::MsgReportChannelSampleRateChanged::create(), BFMDemod::MsgConfigureChannelizer::getCenterFrequency(), BFMDemod::MsgConfigureBFMDemod::getForce(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), Message::getIdentifier(), BasebandSampleSink::getInputMessageQueue(), BasebandSampleSink::getMessageQueueToGUI(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), BFMDemod::MsgConfigureChannelizer::getSampleRate(), getSampleRate(), DSPConfigureAudio::getSampleRate(), BFMDemod::MsgConfigureBFMDemod::getSettings(), BasebandSampleSink::handleMessage(), m_audioSampleRate, m_channelizer, m_sampleSink, Message::match(), and MessageQueue::push().
 {
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& notif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "BFMDemod::handleMessage: MsgChannelizerNotification:"
                 << " inputSampleRate: " << notif.getSampleRate()
                 << " inputFrequencyOffset: " << notif.getFrequencyOffset();
         applyChannelSettings(notif.getSampleRate(), notif.getFrequencyOffset());
         if (getMessageQueueToGUI())
         {
             MsgReportChannelSampleRateChanged *msg = MsgReportChannelSampleRateChanged::create(getSampleRate());
             getMessageQueueToGUI()->push(msg);
         }
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "BFMDemod::handleMessage: MsgConfigureChannelizer: sampleRate: " << cfg.getSampleRate()
                 << " centerFrequency: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureBFMDemod::match(cmd))
     {
         MsgConfigureBFMDemod& cfg = (MsgConfigureBFMDemod&) cmd;
         qDebug() << "BFMDemod::handleMessage: MsgConfigureBFMDemod";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (DSPConfigureAudio::match(cmd))
     {
         DSPConfigureAudio& cfg = (DSPConfigureAudio&) cmd;
         uint32_t sampleRate = cfg.getSampleRate();
         qDebug() << "BFMDemod::handleMessage: DSPConfigureAudio:"
                 << " sampleRate: " << sampleRate;
         if (sampleRate != m_audioSampleRate) {
             applyAudioSampleRate(sampleRate);
         }
         return true;
     }
     else if (BasebandSampleSink::MsgThreadedSink::match(cmd))
     {
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         qDebug() << "BFMDemod::handleMessage: passed: " << cmd.getIdentifier();
         if (m_sampleSink != 0)
         {
             return m_sampleSink->handleMessage(cmd);
         }
         else
         {
             return false;
         }
     }
 }
networkManagerFinished
void BFMDemod::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 846 of file bfmdemod.cpp.
Referenced by BFMDemod(), and ~BFMDemod().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "BFMDemod::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("BFMDemod::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
requiredBW()
static int BFMDemod::requiredBW (int rfBW) inline static
Definition at line 197 of file bfmdemod.h.
Referenced by BFMDemodGUI::applySettings(), and webapiSettingsPutPatch().
     {
         if (rfBW <= 48000) {
             return 48000;
         } else {
             return (3*rfBW)/2;
         }
     }
serialize()
QByteArray BFMDemod::serialize () const virtual
Implements ChannelAPI.
Definition at line 558 of file bfmdemod.cpp.
References m_settings, and BFMDemodSettings::serialize().
 {
     return m_settings.serialize();
 }
setSampleSink()
void BFMDemod::setSampleSink (BasebandSampleSink * sampleSink) inline
Definition at line 127 of file bfmdemod.h.
Referenced by BFMDemodGUI::BFMDemodGUI().
 { m_sampleSink = sampleSink; }
start()
void BFMDemod::start () virtual
Implements BasebandSampleSink.
Definition at line 295 of file bfmdemod.cpp.
References applyChannelSettings(), AudioFifo::clear(), m_audioFifo, m_inputFrequencyOffset, m_inputSampleRate, m_phaseDiscri, m_squelchState, and PhaseDiscriminators::reset().
 {
     m_squelchState = 0;
     m_audioFifo.clear();
     m_phaseDiscri.reset();
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void BFMDemod::stop () virtual
Implements BasebandSampleSink.
Definition at line 303 of file bfmdemod.cpp.
 {
 }
webapiFormatChannelReport()
void BFMDemod::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 726 of file bfmdemod.cpp.
References CalcDb::dbPower(), SWGSDRangel::SWGChannelReport::getBfmDemodReport(), getMagSqLevels(), getPilotLevel(), getPilotLock(), SWGSDRangel::SWGBFMDemodReport::getRdsReport(), m_audioSampleRate, m_inputSampleRate, BFMDemodSettings::m_rdsActive, m_settings, m_squelchState, SWGSDRangel::SWGBFMDemodReport::setAudioSampleRate(), SWGSDRangel::SWGBFMDemodReport::setChannelPowerDb(), SWGSDRangel::SWGBFMDemodReport::setChannelSampleRate(), SWGSDRangel::SWGBFMDemodReport::setPilotLocked(), SWGSDRangel::SWGBFMDemodReport::setPilotPowerDb(), SWGSDRangel::SWGBFMDemodReport::setRdsReport(), SWGSDRangel::SWGBFMDemodReport::setSquelch(), and webapiFormatRDSReport().
Referenced by webapiReportGet().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     response.getBfmDemodReport()->setChannelPowerDb(CalcDb::dbPower(magsqAvg));
     response.getBfmDemodReport()->setSquelch(m_squelchState > 0 ? 1 : 0);
     response.getBfmDemodReport()->setAudioSampleRate(m_audioSampleRate);
     response.getBfmDemodReport()->setChannelSampleRate(m_inputSampleRate);
     response.getBfmDemodReport()->setPilotLocked(getPilotLock() ? 1 : 0);
     response.getBfmDemodReport()->setPilotPowerDb(CalcDb::dbPower(getPilotLevel()));
     if (m_settings.m_rdsActive)
     {
         response.getBfmDemodReport()->setRdsReport(new SWGSDRangel::SWGRDSReport());
         webapiFormatRDSReport(response.getBfmDemodReport()->getRdsReport());
     }
     else
     {
         response.getBfmDemodReport()->setRdsReport(0);
     }
 }
webapiFormatChannelSettings()
void BFMDemod::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const BFMDemodSettings & settings) private
Definition at line 688 of file bfmdemod.cpp.
References SWGSDRangel::SWGBFMDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGChannelSettings::getBfmDemodSettings(), SWGSDRangel::SWGBFMDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGBFMDemodSettings::getTitle(), BFMDemodSettings::m_afBandwidth, BFMDemodSettings::m_audioDeviceName, BFMDemodSettings::m_audioStereo, BFMDemodSettings::m_inputFrequencyOffset, BFMDemodSettings::m_lsbStereo, BFMDemodSettings::m_rdsActive, BFMDemodSettings::m_reverseAPIAddress, BFMDemodSettings::m_reverseAPIChannelIndex, BFMDemodSettings::m_reverseAPIDeviceIndex, BFMDemodSettings::m_reverseAPIPort, BFMDemodSettings::m_rfBandwidth, BFMDemodSettings::m_rgbColor, BFMDemodSettings::m_showPilot, BFMDemodSettings::m_squelch, BFMDemodSettings::m_title, BFMDemodSettings::m_useReverseAPI, BFMDemodSettings::m_volume, SWGSDRangel::SWGBFMDemodSettings::setAfBandwidth(), SWGSDRangel::SWGBFMDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGBFMDemodSettings::setAudioStereo(), SWGSDRangel::SWGBFMDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGBFMDemodSettings::setLsbStereo(), SWGSDRangel::SWGBFMDemodSettings::setRdsActive(), SWGSDRangel::SWGBFMDemodSettings::setReverseApiAddress(), SWGSDRangel::SWGBFMDemodSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGBFMDemodSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGBFMDemodSettings::setReverseApiPort(), SWGSDRangel::SWGBFMDemodSettings::setRfBandwidth(), SWGSDRangel::SWGBFMDemodSettings::setRgbColor(), SWGSDRangel::SWGBFMDemodSettings::setShowPilot(), SWGSDRangel::SWGBFMDemodSettings::setSquelch(), SWGSDRangel::SWGBFMDemodSettings::setTitle(), SWGSDRangel::SWGBFMDemodSettings::setUseReverseApi(), and SWGSDRangel::SWGBFMDemodSettings::setVolume().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getBfmDemodSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getBfmDemodSettings()->setRfBandwidth(settings.m_rfBandwidth);
     response.getBfmDemodSettings()->setAfBandwidth(settings.m_afBandwidth);
     response.getBfmDemodSettings()->setVolume(settings.m_volume);
     response.getBfmDemodSettings()->setSquelch(settings.m_squelch);
     response.getBfmDemodSettings()->setAudioStereo(settings.m_audioStereo ? 1 : 0);
     response.getBfmDemodSettings()->setLsbStereo(settings.m_lsbStereo ? 1 : 0);
     response.getBfmDemodSettings()->setShowPilot(settings.m_showPilot ? 1 : 0);
     response.getBfmDemodSettings()->setRdsActive(settings.m_rdsActive ? 1 : 0);
     response.getBfmDemodSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getBfmDemodSettings()->getTitle()) {
         *response.getBfmDemodSettings()->getTitle() = settings.m_title;
     } else {
         response.getBfmDemodSettings()->setTitle(new QString(settings.m_title));
     }
     if (response.getBfmDemodSettings()->getAudioDeviceName()) {
         *response.getBfmDemodSettings()->getAudioDeviceName() = settings.m_audioDeviceName;
     } else {
         response.getBfmDemodSettings()->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     response.getBfmDemodSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getBfmDemodSettings()->getReverseApiAddress()) {
         *response.getBfmDemodSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getBfmDemodSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getBfmDemodSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getBfmDemodSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getBfmDemodSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiFormatRDSReport()
void BFMDemod::webapiFormatRDSReport (SWGSDRangel::SWGRDSReport * report) private
Definition at line 750 of file bfmdemod.cpp.
References CalcDb::dbPower(), SWGSDRangel::SWGRDSReport::getAltFrequencies(), getDecoderQua(), getDemodAcc(), getDemodFclk(), getDemodQua(), getRDSParser(), RDSParser::m_g0_alt_freq, SWGSDRangel::SWGRDSReport::setAltFrequencies(), SWGSDRangel::SWGRDSReport::setDecodStatus(), SWGSDRangel::SWGRDSReport::setDemodStatus(), SWGSDRangel::SWGRDSReport::setMonoStereo(), SWGSDRangel::SWGRDSReport::setMusicSpeech(), SWGSDRangel::SWGRDSReport::setPiCoverage(), SWGSDRangel::SWGRDSReport::setPid(), SWGSDRangel::SWGRDSReport::setPiType(), SWGSDRangel::SWGRDSReport::setProgServiceName(), SWGSDRangel::SWGRDSReport::setRadioText(), SWGSDRangel::SWGRDSReport::setRdsDemodAccumDb(), SWGSDRangel::SWGRDSReport::setRdsDemodFrequency(), and SWGSDRangel::SWGRDSReport::setTime().
Referenced by webapiFormatChannelReport().
 {
     report->setDemodStatus(round(getDemodQua()));
     report->setDecodStatus(round(getDecoderQua()));
     report->setRdsDemodAccumDb(CalcDb::dbPower(std::fabs(getDemodAcc())));
     report->setRdsDemodFrequency(getDemodFclk());
     report->setPid(new QString(str(boost::format("%04X") % getRDSParser().m_pi_program_identification).c_str()));
     report->setPiType(new QString(getRDSParser().pty_table[getRDSParser().m_pi_program_type].c_str()));
     report->setPiCoverage(new QString(getRDSParser().coverage_area_codes[getRDSParser().m_pi_area_coverage_index].c_str()));
     report->setProgServiceName(new QString(getRDSParser().m_g0_program_service_name));
     report->setMusicSpeech(new QString((getRDSParser().m_g0_music_speech ? "Music" : "Speech")));
     report->setMonoStereo(new QString((getRDSParser().m_g0_mono_stereo ? "Mono" : "Stereo")));
     report->setRadioText(new QString(getRDSParser().m_g2_radiotext));
     std::string time = str(boost::format("%4i-%02i-%02i %02i:%02i (%+.1fh)")\
         % (1900 + getRDSParser().m_g4_year) % getRDSParser().m_g4_month % getRDSParser().m_g4_day % getRDSParser().m_g4_hours % getRDSParser().m_g4_minutes % getRDSParser().m_g4_local_time_offset);
     report->setTime(new QString(time.c_str()));
     report->setAltFrequencies(new QList<SWGSDRangel::SWGRDSReport_altFrequencies*>);
     for (std::set<double>::iterator it = getRDSParser().m_g0_alt_freq.begin(); it != getRDSParser().m_g0_alt_freq.end(); ++it)
     {
         if (*it > 76.0)
         {
             report->getAltFrequencies()->append(new SWGSDRangel::SWGRDSReport_altFrequencies);
             report->getAltFrequencies()->back()->setFrequency(*it);
         }
     }
 }
webapiReportGet()
int BFMDemod::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 677 of file bfmdemod.cpp.
References SWGSDRangel::SWGChannelReport::getBfmDemodReport(), SWGSDRangel::SWGBFMDemodReport::init(), SWGSDRangel::SWGChannelReport::setBfmDemodReport(), and webapiFormatChannelReport().
 {
     (void) errorMessage;
     response.setBfmDemodReport(new SWGSDRangel::SWGBFMDemodReport());
     response.getBfmDemodReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendSettings()
void BFMDemod::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const BFMDemodSettings & settings, bool force) private
Definition at line 778 of file bfmdemod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), SWGSDRangel::SWGChannelSettings::getBfmDemodSettings(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), BFMDemodSettings::m_afBandwidth, BFMDemodSettings::m_audioDeviceName, BFMDemodSettings::m_audioStereo, BFMDemodSettings::m_inputFrequencyOffset, BFMDemodSettings::m_lsbStereo, m_networkManager, m_networkRequest, BFMDemodSettings::m_rdsActive, BFMDemodSettings::m_reverseAPIAddress, BFMDemodSettings::m_reverseAPIChannelIndex, BFMDemodSettings::m_reverseAPIDeviceIndex, BFMDemodSettings::m_reverseAPIPort, BFMDemodSettings::m_rfBandwidth, BFMDemodSettings::m_rgbColor, BFMDemodSettings::m_showPilot, BFMDemodSettings::m_squelch, BFMDemodSettings::m_title, BFMDemodSettings::m_volume, SWGSDRangel::SWGBFMDemodSettings::setAfBandwidth(), SWGSDRangel::SWGBFMDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGBFMDemodSettings::setAudioStereo(), SWGSDRangel::SWGChannelSettings::setBfmDemodSettings(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGBFMDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGBFMDemodSettings::setLsbStereo(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGBFMDemodSettings::setRdsActive(), SWGSDRangel::SWGBFMDemodSettings::setRfBandwidth(), SWGSDRangel::SWGBFMDemodSettings::setRgbColor(), SWGSDRangel::SWGBFMDemodSettings::setShowPilot(), SWGSDRangel::SWGBFMDemodSettings::setSquelch(), SWGSDRangel::SWGBFMDemodSettings::setTitle(), and SWGSDRangel::SWGBFMDemodSettings::setVolume().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(0); // single sink (Rx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("BFMDemod"));
     swgChannelSettings->setBfmDemodSettings(new SWGSDRangel::SWGBFMDemodSettings());
     SWGSDRangel::SWGBFMDemodSettings *swgBFMDemodSettings = swgChannelSettings->getBfmDemodSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgBFMDemodSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("rfBandwidth") || force) {
         swgBFMDemodSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (channelSettingsKeys.contains("afBandwidth") || force) {
         swgBFMDemodSettings->setAfBandwidth(settings.m_afBandwidth);
     }
     if (channelSettingsKeys.contains("volume") || force) {
         swgBFMDemodSettings->setVolume(settings.m_volume);
     }
     if (channelSettingsKeys.contains("squelch") || force) {
         swgBFMDemodSettings->setSquelch(settings.m_squelch);
     }
     if (channelSettingsKeys.contains("audioStereo") || force) {
         swgBFMDemodSettings->setAudioStereo(settings.m_audioStereo ? 1 : 0);
     }
     if (channelSettingsKeys.contains("lsbStereo") || force) {
         swgBFMDemodSettings->setLsbStereo(settings.m_lsbStereo ? 1 : 0);
     }
     if (channelSettingsKeys.contains("showPilot") || force) {
         swgBFMDemodSettings->setShowPilot(settings.m_showPilot ? 1 : 0);
     }
     if (channelSettingsKeys.contains("rdsActive") || force) {
         swgBFMDemodSettings->setRdsActive(settings.m_rdsActive ? 1 : 0);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgBFMDemodSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgBFMDemodSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("audioDeviceName") || force) {
         swgBFMDemodSettings->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int BFMDemod::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 580 of file bfmdemod.cpp.
References SWGSDRangel::SWGChannelSettings::getBfmDemodSettings(), SWGSDRangel::SWGBFMDemodSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setBfmDemodSettings(), and webapiFormatChannelSettings().
 {
     (void) errorMessage;
     response.setBfmDemodSettings(new SWGSDRangel::SWGBFMDemodSettings());
     response.getBfmDemodSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int BFMDemod::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 591 of file bfmdemod.cpp.
References BFMDemod::MsgConfigureBFMDemod::create(), BFMDemod::MsgConfigureChannelizer::create(), SWGSDRangel::SWGBFMDemodSettings::getAfBandwidth(), SWGSDRangel::SWGBFMDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGBFMDemodSettings::getAudioStereo(), SWGSDRangel::SWGChannelSettings::getBfmDemodSettings(), SWGSDRangel::SWGBFMDemodSettings::getInputFrequencyOffset(), SWGSDRangel::SWGBFMDemodSettings::getLsbStereo(), SWGSDRangel::SWGBFMDemodSettings::getRdsActive(), SWGSDRangel::SWGBFMDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGBFMDemodSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGBFMDemodSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGBFMDemodSettings::getReverseApiPort(), SWGSDRangel::SWGBFMDemodSettings::getRfBandwidth(), SWGSDRangel::SWGBFMDemodSettings::getRgbColor(), SWGSDRangel::SWGBFMDemodSettings::getShowPilot(), SWGSDRangel::SWGBFMDemodSettings::getSquelch(), SWGSDRangel::SWGBFMDemodSettings::getTitle(), SWGSDRangel::SWGBFMDemodSettings::getUseReverseApi(), SWGSDRangel::SWGBFMDemodSettings::getVolume(), BFMDemodSettings::m_afBandwidth, BFMDemodSettings::m_audioDeviceName, BFMDemodSettings::m_audioStereo, BasebandSampleSink::m_guiMessageQueue, BFMDemodSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, BFMDemodSettings::m_lsbStereo, BFMDemodSettings::m_rdsActive, BFMDemodSettings::m_reverseAPIAddress, BFMDemodSettings::m_reverseAPIChannelIndex, BFMDemodSettings::m_reverseAPIDeviceIndex, BFMDemodSettings::m_reverseAPIPort, BFMDemodSettings::m_rfBandwidth, BFMDemodSettings::m_rgbColor, m_settings, BFMDemodSettings::m_showPilot, BFMDemodSettings::m_squelch, BFMDemodSettings::m_title, BFMDemodSettings::m_useReverseAPI, BFMDemodSettings::m_volume, MessageQueue::push(), requiredBW(), and webapiFormatChannelSettings().
 {
     (void) errorMessage;
     BFMDemodSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getBfmDemodSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getBfmDemodSettings()->getRfBandwidth();
     }
     if (channelSettingsKeys.contains("afBandwidth")) {
         settings.m_afBandwidth = response.getBfmDemodSettings()->getAfBandwidth();
     }
     if (channelSettingsKeys.contains("volume")) {
         settings.m_volume = response.getBfmDemodSettings()->getVolume();
     }
     if (channelSettingsKeys.contains("squelch")) {
         settings.m_squelch = response.getBfmDemodSettings()->getSquelch();
     }
     if (channelSettingsKeys.contains("audioStereo")) {
         settings.m_audioStereo = response.getBfmDemodSettings()->getAudioStereo() != 0;
     }
     if (channelSettingsKeys.contains("lsbStereo")) {
         settings.m_lsbStereo = response.getBfmDemodSettings()->getLsbStereo() != 0;
     }
     if (channelSettingsKeys.contains("showPilot")) {
         settings.m_showPilot = response.getBfmDemodSettings()->getShowPilot() != 0;
     }
     if (channelSettingsKeys.contains("rdsActive")) {
         settings.m_rdsActive = response.getBfmDemodSettings()->getRdsActive() != 0;
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getBfmDemodSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getBfmDemodSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("audioDeviceName")) {
         settings.m_audioDeviceName = *response.getBfmDemodSettings()->getAudioDeviceName();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getBfmDemodSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getBfmDemodSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getBfmDemodSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getBfmDemodSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getBfmDemodSettings()->getReverseApiChannelIndex();
     }
     if (frequencyOffsetChanged)
     {
         MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
                 requiredBW(settings.m_rfBandwidth), settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(channelConfigMsg);
     }
     MsgConfigureBFMDemod *msg = MsgConfigureBFMDemod::create(settings, force);
     m_inputMessageQueue.push(msg);
     qDebug("BFMDemod::webapiSettingsPutPatch: forward to GUI: %p", m_guiMessageQueue);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureBFMDemod *msgToGUI = MsgConfigureBFMDemod::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
default_deemphasis
const Real BFMDemod::default_deemphasis = 50.0 static private
Definition at line 279 of file bfmdemod.h.
Referenced by applyAudioSampleRate(), and BFMDemod().
default_excursion
const int BFMDemod::default_excursion = 750000 static private
Definition at line 282 of file bfmdemod.h.
filtFftLen
const int BFMDemod::filtFftLen = 1024 static private
Definition at line 249 of file bfmdemod.h.
Referenced by BFMDemod().
m_audioBuffer
AudioVector BFMDemod::m_audioBuffer private
Definition at line 262 of file bfmdemod.h.
Referenced by BFMDemod(), and feed().
m_audioBufferFill
uint BFMDemod::m_audioBufferFill private
Definition at line 263 of file bfmdemod.h.
Referenced by BFMDemod(), and feed().
m_audioFifo
AudioFifo BFMDemod::m_audioFifo private
Definition at line 266 of file bfmdemod.h.
Referenced by applySettings(), BFMDemod(), feed(), start(), and ~BFMDemod().
m_audioSampleRate
quint32 BFMDemod::m_audioSampleRate private
Definition at line 232 of file bfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), BFMDemod(), handleMessage(), and webapiFormatChannelReport().
m_channelId
const QString BFMDemod::m_channelId = "BFMDemod" static
Definition at line 207 of file bfmdemod.h.
Referenced by BFMDemod(), and BFMPlugin::initPlugin().
m_channelIdURI
const QString BFMDemod::m_channelIdURI = "sdrangel.channel.bfm" static
Definition at line 206 of file bfmdemod.h.
Referenced by BFMDemodGUI::BFMDemodGUI(), and BFMPlugin::initPlugin().
m_channelizer
DownChannelizer* BFMDemod::m_channelizer private
Definition at line 227 of file bfmdemod.h.
Referenced by BFMDemod(), handleMessage(), and ~BFMDemod().
m_deemphasisFilterX
LowPassFilterRC BFMDemod::m_deemphasisFilterX private
Definition at line 277 of file bfmdemod.h.
Referenced by applyAudioSampleRate(), BFMDemod(), and feed().
m_deemphasisFilterY
LowPassFilterRC BFMDemod::m_deemphasisFilterY private
Definition at line 278 of file bfmdemod.h.
Referenced by applyAudioSampleRate(), BFMDemod(), and feed().
m_deviceAPI
DeviceAPI* BFMDemod::m_deviceAPI private
Definition at line 225 of file bfmdemod.h.
Referenced by BFMDemod(), and ~BFMDemod().
m_fmExcursion
Real BFMDemod::m_fmExcursion private
Definition at line 281 of file bfmdemod.h.
Referenced by applyChannelSettings(), applySettings(), and BFMDemod().
m_inputFrequencyOffset
int BFMDemod::m_inputFrequencyOffset private
Definition at line 230 of file bfmdemod.h.
Referenced by applyChannelSettings(), BFMDemod(), and start().
m_inputSampleRate
int BFMDemod::m_inputSampleRate private
Definition at line 229 of file bfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), BFMDemod(), start(), and webapiFormatChannelReport().
m_interpolator
Interpolator BFMDemod::m_interpolator private
Interpolator between fixed demod bandwidth and audio bandwidth (rational)
Definition at line 235 of file bfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_interpolatorDistance
Real BFMDemod::m_interpolatorDistance private
Definition at line 236 of file bfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), BFMDemod(), and feed().
m_interpolatorDistanceRemain
Real BFMDemod::m_interpolatorDistanceRemain private
Definition at line 237 of file bfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), BFMDemod(), and feed().
m_interpolatorRDS
Interpolator BFMDemod::m_interpolatorRDS private
Twin Interpolator for stereo subcarrier.
Definition at line 243 of file bfmdemod.h.
Referenced by applyChannelSettings(), applySettings(), and feed().
m_interpolatorRDSDistance
Real BFMDemod::m_interpolatorRDSDistance private
Definition at line 244 of file bfmdemod.h.
Referenced by applyChannelSettings(), applySettings(), BFMDemod(), and feed().
m_interpolatorRDSDistanceRemain
Real BFMDemod::m_interpolatorRDSDistanceRemain private
Definition at line 245 of file bfmdemod.h.
Referenced by applyChannelSettings(), applySettings(), BFMDemod(), and feed().
m_interpolatorStereo
Interpolator BFMDemod::m_interpolatorStereo private
Twin Interpolator for stereo subcarrier.
Definition at line 239 of file bfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_interpolatorStereoDistance
Real BFMDemod::m_interpolatorStereoDistance private
Definition at line 240 of file bfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), BFMDemod(), and feed().
m_interpolatorStereoDistanceRemain
Real BFMDemod::m_interpolatorStereoDistanceRemain private
Definition at line 241 of file bfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), BFMDemod(), and feed().
m_lowpass
Lowpass<Real> BFMDemod::m_lowpass private
Definition at line 247 of file bfmdemod.h.
Referenced by applySettings().
m_m1Arg
Real BFMDemod::m_m1Arg private
Definition at line 254 of file bfmdemod.h.
Referenced by BFMDemod().
m_magsq
double BFMDemod::m_magsq private
x^-1 real sample
Definition at line 256 of file bfmdemod.h.
Referenced by BFMDemod().
m_magsqCount
int BFMDemod::m_magsqCount private
Definition at line 259 of file bfmdemod.h.
Referenced by BFMDemod(), and feed().
m_magSqLevelStore
MagSqLevelsStore BFMDemod::m_magSqLevelStore private
Definition at line 260 of file bfmdemod.h.
m_magsqPeak
double BFMDemod::m_magsqPeak private
Definition at line 258 of file bfmdemod.h.
Referenced by BFMDemod(), and feed().
m_magsqSum
double BFMDemod::m_magsqSum private
Definition at line 257 of file bfmdemod.h.
Referenced by BFMDemod(), and feed().
m_nco
NCO BFMDemod::m_nco private
Definition at line 234 of file bfmdemod.h.
Referenced by applyChannelSettings(), and feed().
m_networkManager
QNetworkAccessManager* BFMDemod::m_networkManager private
Definition at line 288 of file bfmdemod.h.
Referenced by BFMDemod(), webapiReverseSendSettings(), and ~BFMDemod().
m_networkRequest
QNetworkRequest BFMDemod::m_networkRequest private
Definition at line 289 of file bfmdemod.h.
Referenced by webapiReverseSendSettings().
m_phaseDiscri
PhaseDiscriminators BFMDemod::m_phaseDiscri private
Definition at line 284 of file bfmdemod.h.
Referenced by applyChannelSettings(), applySettings(), BFMDemod(), feed(), and start().
m_pilotPLL
RDSPhaseLock BFMDemod::m_pilotPLL private
Definition at line 270 of file bfmdemod.h.
Referenced by applyChannelSettings(), applySettings(), and feed().
m_pilotPLLSamples
Real BFMDemod::m_pilotPLLSamples[4] private
Definition at line 271 of file bfmdemod.h.
Referenced by feed().
m_rdsDecoder
RDSDecoder BFMDemod::m_rdsDecoder private
Definition at line 274 of file bfmdemod.h.
Referenced by feed().
m_rdsDemod
RDSDemod BFMDemod::m_rdsDemod private
Definition at line 273 of file bfmdemod.h.
Referenced by feed().
m_rdsParser
RDSParser BFMDemod::m_rdsParser private
Definition at line 275 of file bfmdemod.h.
Referenced by feed().
m_rfFilter
fftfilt* BFMDemod::m_rfFilter private
Definition at line 248 of file bfmdemod.h.
Referenced by applyChannelSettings(), applySettings(), BFMDemod(), feed(), and ~BFMDemod().
m_sampleBuffer
SampleVector BFMDemod::m_sampleBuffer private
Definition at line 267 of file bfmdemod.h.
Referenced by feed().
m_sampleSink
BasebandSampleSink* BFMDemod::m_sampleSink private
Definition at line 265 of file bfmdemod.h.
Referenced by BFMDemod(), feed(), and handleMessage().
m_settings
BFMDemodSettings BFMDemod::m_settings private
Definition at line 231 of file bfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), BFMDemod(), deserialize(), feed(), serialize(), webapiFormatChannelReport(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex BFMDemod::m_settingsMutex private
Definition at line 268 of file bfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_squelchLevel
Real BFMDemod::m_squelchLevel private
Definition at line 251 of file bfmdemod.h.
Referenced by applySettings(), BFMDemod(), and feed().
m_squelchState
int BFMDemod::m_squelchState private
Definition at line 252 of file bfmdemod.h.
Referenced by BFMDemod(), feed(), start(), and webapiFormatChannelReport().
m_threadedChannelizer
ThreadedBasebandSampleSink* BFMDemod::m_threadedChannelizer private
Definition at line 226 of file bfmdemod.h.
Referenced by BFMDemod(), and ~BFMDemod().
m_udpBlockSize
const int BFMDemod::m_udpBlockSize = 512 static private
Definition at line 286 of file bfmdemod.h.
The documentation for this class was generated from the following files:
plugins/channelrx/demodbfm/bfmdemod.h
plugins/channelrx/demodbfm/bfmdemod.cpp