SDRAngel: UDPSourceGUI Class Reference
UDPSourceGUI Class Reference
#include <udpsourcegui.h>
Public Slots
void channelMarkerChangedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
virtual void resetToDefaults ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static UDPSourceGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx)
Private Slots
void handleSourceMessages ()
void on_deltaFrequency_changed (qint64 value)
void on_sampleFormat_currentIndexChanged (int index)
void on_localUDPAddress_editingFinished ()
void on_localUDPPort_editingFinished ()
void on_sampleRate_textEdited (const QString &arg1)
void on_rfBandwidth_textEdited (const QString &arg1)
void on_fmDeviation_textEdited (const QString &arg1)
void on_amModPercent_textEdited (const QString &arg1)
void on_applyBtn_clicked ()
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void on_gainIn_valueChanged (int value)
void on_gainOut_valueChanged (int value)
void on_squelch_valueChanged (int value)
void on_squelchGate_valueChanged (int value)
void on_channelMute_toggled (bool checked)
void on_resetUDPReadIndex_clicked ()
void on_autoRWBalance_toggled (bool checked)
void on_stereoInput_toggled (bool checked)
void tick ()
Private Member Functions
UDPSourceGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx, QWidget *parent=NULL)
virtual ~UDPSourceGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
void setSampleFormat (int index)
void setSampleFormatIndex (const UDPSourceSettings::SampleFormat &sampleFormat)
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::UDPSourceGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
SpectrumVis * m_spectrumVis
UDPSource * m_udpSource
MovingAverageUtil< double, double, 4 > m_channelPowerAvg
MovingAverageUtil< double, double, 4 > m_inPowerAvg
uint32_t m_tickCount
ChannelMarker m_channelMarker
UDPSourceSettings m_settings
bool m_rfBandwidthChanged
bool m_doApplySettings
MessageQueue m_inputMessageQueue
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 41 of file udpsourcegui.h.
Constructor & Destructor Documentation
UDPSourceGUI()
UDPSourceGUI::UDPSourceGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx, QWidget * parent = NULL) explicit private
Definition at line 117 of file udpsourcegui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), arg(), FFTWindow::BlackmanHarris, channelMarkerChangedByCursor(), SpectrumVis::configure(), displaySettings(), getInputMessageQueue(), BasebandSampleSink::getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, handleSourceMessages(), UDPSource::m_channelIdURI, m_channelMarker, m_deviceUISet, UDPSourceSettings::m_rgbColor, m_settings, m_spectrumVis, m_udpSource, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerTxChannelInstance(), SDR_TX_SCALEF, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), BasebandSampleSource::setMessageQueueToGUI(), ChannelMarker::setSourceOrSinkStream(), UDPSource::setSpectrumSink(), ChannelMarker::setTitle(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                            :
         RollupWidget(parent),
         ui(new Ui::UDPSourceGUI),
         m_pluginAPI(pluginAPI),
         m_deviceUISet(deviceUISet),
         m_tickCount(0),
         m_channelMarker(this),
         m_rfBandwidthChanged(false),
         m_doApplySettings(true)
 {
     ui->setupUi(this);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     setAttribute(Qt::WA_DeleteOnClose, true);
     m_spectrumVis = new SpectrumVis(SDR_TX_SCALEF, ui->glSpectrum);
     m_udpSource = (UDPSource*) channelTx;
     m_udpSource->setSpectrumSink(m_spectrumVis);
     m_udpSource->setMessageQueueToGUI(getInputMessageQueue());
     ui->fmDeviation->setEnabled(false);
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     ui->glSpectrum->setCenterFrequency(0);
     ui->glSpectrum->setSampleRate(ui->sampleRate->text().toInt());
     ui->glSpectrum->setDisplayWaterfall(true);
     ui->glSpectrum->setDisplayMaxHold(true);
     m_spectrumVis->configure(m_spectrumVis->getInputMessageQueue(),
             64, // FFT size
             10, // overlapping %
             0,  // number of averaging samples
             0,  // no averaging
             FFTWindow::BlackmanHarris,
             false); // logarithmic scale
     ui->glSpectrum->connectTimer(MainWindow::getInstance()->getMasterTimer());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     m_channelMarker.blockSignals(true);
     m_channelMarker.setBandwidth(16000);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     m_channelMarker.setTitle("UDP Sample Sink");
     m_channelMarker.setSourceOrSinkStream(false);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     m_deviceUISet->registerTxChannelInstance(UDPSource::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     ui->spectrumGUI->setBuddies(m_spectrumVis->getInputMessageQueue(), m_spectrumVis, ui->glSpectrum);
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     connect(m_udpSource, SIGNAL(levelChanged(qreal, qreal, int)), ui->volumeMeter, SLOT(levelChanged(qreal, qreal, int)));
     displaySettings();
     applySettings(true);
 }
~UDPSourceGUI()
UDPSourceGUI::~UDPSourceGUI () private virtual
Definition at line 181 of file udpsourcegui.cpp.
References m_deviceUISet, m_spectrumVis, m_udpSource, DeviceUISet::removeTxChannelInstance(), and ui.
 {
     m_deviceUISet->removeTxChannelInstance(this);
     delete m_udpSource; // TODO: check this: when the GUI closes it has to delete the modulator
     delete m_spectrumVis;
     delete ui;
 }
Member Function Documentation
applySettings()
void UDPSourceGUI::applySettings (bool force = false) private
Definition at line 194 of file udpsourcegui.cpp.
References UDPSource::MsgConfigureUDPSource::create(), UDPSource::MsgConfigureChannelizer::create(), BasebandSampleSource::getInputMessageQueue(), m_doApplySettings, UDPSourceSettings::m_inputFrequencyOffset, UDPSourceSettings::m_inputSampleRate, m_settings, m_udpSource, MessageQueue::push(), and ui.
Referenced by channelMarkerChangedByCursor(), deserialize(), on_applyBtn_clicked(), on_autoRWBalance_toggled(), on_channelMute_toggled(), on_deltaFrequency_changed(), on_gainIn_valueChanged(), on_gainOut_valueChanged(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_stereoInput_toggled(), onMenuDialogCalled(), resetToDefaults(), setCenterFrequency(), and UDPSourceGUI().
 {
     if (m_doApplySettings)
     {
         UDPSource::MsgConfigureChannelizer *msgChan = UDPSource::MsgConfigureChannelizer::create(
                 m_settings.m_inputSampleRate,
                 m_settings.m_inputFrequencyOffset);
         m_udpSource->getInputMessageQueue()->push(msgChan);
         UDPSource::MsgConfigureUDPSource* message = UDPSource::MsgConfigureUDPSource::create( m_settings, force);
         m_udpSource->getInputMessageQueue()->push(message);
         ui->applyBtn->setEnabled(false);
         ui->applyBtn->setStyleSheet("QPushButton { background:rgb(79,79,79); }");
     }
 }
blockApplySettings()
void UDPSourceGUI::blockApplySettings (bool block) private
Definition at line 189 of file udpsourcegui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void UDPSourceGUI::channelMarkerChangedByCursor () slot
Definition at line 263 of file udpsourcegui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, UDPSourceSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by UDPSourceGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
create()
UDPSourceGUI * UDPSourceGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx) static
Definition at line 31 of file udpsourcegui.cpp.
References UDPSourceGUI().
Referenced by UDPSourcePlugin::createTxChannelGUI().
 {
     UDPSourceGUI* gui = new UDPSourceGUI(pluginAPI, deviceUISet, channelTx);
     return gui;
 }
deserialize()
bool UDPSourceGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 74 of file udpsourcegui.cpp.
References applySettings(), UDPSourceSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data))
     {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void UDPSourceGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 37 of file udpsourcegui.cpp.
 {
     delete this;
 }
displaySettings()
void UDPSourceGUI::displaySettings () private
Definition at line 211 of file udpsourcegui.cpp.
References arg(), blockApplySettings(), ChannelMarker::getTitle(), UDPSourceSettings::m_amModFactor, UDPSourceSettings::m_autoRWBalance, m_channelMarker, UDPSourceSettings::m_channelMute, UDPSourceSettings::m_fmDeviation, UDPSourceSettings::m_gainIn, UDPSourceSettings::m_gainOut, UDPSourceSettings::m_inputFrequencyOffset, UDPSourceSettings::m_inputSampleRate, UDPSourceSettings::m_rfBandwidth, UDPSourceSettings::m_rgbColor, UDPSourceSettings::m_sampleFormat, m_settings, UDPSourceSettings::m_squelch, UDPSourceSettings::m_squelchEnabled, UDPSourceSettings::m_squelchGate, UDPSourceSettings::m_stereoInput, UDPSourceSettings::m_udpAddress, UDPSourceSettings::m_udpPort, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), setSampleFormatIndex(), RollupWidget::setTitleColor(), and ui.
Referenced by deserialize(), handleMessage(), resetToDefaults(), and UDPSourceGUI().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setBandwidth(m_settings.m_rfBandwidth);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     setTitleColor(m_settings.m_rgbColor);
     this->setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->deltaFrequency->setValue(m_settings.m_inputFrequencyOffset);
     ui->sampleRate->setText(QString("%1").arg(roundf(m_settings.m_inputSampleRate), 0));
     ui->glSpectrum->setSampleRate(m_settings.m_inputSampleRate);
     ui->rfBandwidth->setText(QString("%1").arg(roundf(m_settings.m_rfBandwidth), 0));
     ui->fmDeviation->setText(QString("%1").arg(m_settings.m_fmDeviation, 0));
     ui->amModPercent->setText(QString("%1").arg(roundf(m_settings.m_amModFactor * 100.0), 0));
     setSampleFormatIndex(m_settings.m_sampleFormat);
     ui->channelMute->setChecked(m_settings.m_channelMute);
     ui->autoRWBalance->setChecked(m_settings.m_autoRWBalance);
     ui->stereoInput->setChecked(m_settings.m_stereoInput);
     ui->gainInText->setText(tr("%1").arg(m_settings.m_gainIn, 0, 'f', 1));
     ui->gainIn->setValue(roundf(m_settings.m_gainIn * 10.0));
     ui->gainOutText->setText(tr("%1").arg(m_settings.m_gainOut, 0, 'f', 1));
     ui->gainOut->setValue(roundf(m_settings.m_gainOut * 10.0));
     if (m_settings.m_squelchEnabled) {
         ui->squelchText->setText(tr("%1").arg(m_settings.m_squelch, 0, 'f', 0));
     } else {
         ui->squelchText->setText("---");
     }
     ui->squelch->setValue(roundf(m_settings.m_squelch));
     ui->squelchGateText->setText(tr("%1").arg(roundf(m_settings.m_squelchGate * 1000.0), 0, 'f', 0));
     ui->squelchGate->setValue(roundf(m_settings.m_squelchGate * 100.0));
     ui->localUDPAddress->setText(m_settings.m_udpAddress);
     ui->localUDPPort->setText(tr("%1").arg(m_settings.m_udpPort));
     ui->applyBtn->setEnabled(false);
     ui->applyBtn->setStyleSheet("QPushButton { background:rgb(79,79,79); }");
     blockApplySettings(false);
 }
enterEvent()
void UDPSourceGUI::enterEvent (QEvent *) private
Definition at line 509 of file udpsourcegui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 UDPSourceGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 52 of file udpsourcegui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
{
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* UDPSourceGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 55 of file udpsourcegui.h.
Referenced by handleSourceMessages(), and UDPSourceGUI().
 { return &m_inputMessageQueue; }
getName()
QString UDPSourceGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 47 of file udpsourcegui.cpp.
 {
     return objectName();
 }
handleMessage()
bool UDPSourceGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 87 of file udpsourcegui.cpp.
References blockApplySettings(), displaySettings(), UDPSource::MsgConfigureUDPSource::getSettings(), m_settings, and Message::match().
Referenced by handleSourceMessages().
 {
     if (UDPSource::MsgConfigureUDPSource::match(message))
     {
         const UDPSource::MsgConfigureUDPSource& cfg = (UDPSource::MsgConfigureUDPSource&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void UDPSourceGUI::handleSourceMessages () private slot
Definition at line 104 of file udpsourcegui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by UDPSourceGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void UDPSourceGUI::leaveEvent (QEvent *) private
Definition at line 504 of file udpsourcegui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_amModPercent_textEdited
void UDPSourceGUI::on_amModPercent_textEdited (const QString & arg1) private slot
Definition at line 376 of file udpsourcegui.cpp.
References arg(), UDPSourceSettings::m_amModFactor, m_settings, and ui.
 {
     (void) arg1;
     bool ok;
     int amModPercent = ui->amModPercent->text().toInt(&ok);
     if ((!ok) || (amModPercent < 1) || (amModPercent > 100))
     {
         m_settings.m_amModFactor = 0.95;
         ui->amModPercent->setText(QString("%1").arg(95));
     } else {
         m_settings.m_amModFactor = amModPercent / 100.0;
     }
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_applyBtn_clicked
void UDPSourceGUI::on_applyBtn_clicked () private slot
Definition at line 435 of file udpsourcegui.cpp.
References applySettings(), m_channelMarker, UDPSourceSettings::m_inputSampleRate, UDPSourceSettings::m_rfBandwidth, m_rfBandwidthChanged, m_settings, ChannelMarker::setBandwidth(), and ui.
 {
     if (m_rfBandwidthChanged)
     {
         m_channelMarker.setBandwidth(m_settings.m_rfBandwidth);
         m_rfBandwidthChanged = false;
     }
     ui->glSpectrum->setSampleRate(m_settings.m_inputSampleRate);
     applySettings();
 }
on_autoRWBalance_toggled
void UDPSourceGUI::on_autoRWBalance_toggled (bool checked) private slot
Definition at line 453 of file udpsourcegui.cpp.
References applySettings(), UDPSourceSettings::m_autoRWBalance, and m_settings.
 {
     m_settings.m_autoRWBalance = checked;
     applySettings();
 }
on_channelMute_toggled
void UDPSourceGUI::on_channelMute_toggled (bool checked) private slot
Definition at line 429 of file udpsourcegui.cpp.
References applySettings(), UDPSourceSettings::m_channelMute, and m_settings.
 {
     m_settings.m_channelMute = checked;
     applySettings();
 }
on_deltaFrequency_changed
void UDPSourceGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 270 of file udpsourcegui.cpp.
References applySettings(), m_channelMarker, UDPSourceSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_settings.m_inputFrequencyOffset = value;
     m_channelMarker.setCenterFrequency(value);
     applySettings();
 }
on_fmDeviation_textEdited
void UDPSourceGUI::on_fmDeviation_textEdited (const QString & arg1) private slot
Definition at line 359 of file udpsourcegui.cpp.
References arg(), UDPSourceSettings::m_fmDeviation, m_settings, and ui.
 {
     (void) arg1;
     bool ok;
     int fmDeviation = ui->fmDeviation->text().toInt(&ok);
     if ((!ok) || (fmDeviation < 1)) {
         m_settings.m_fmDeviation = 2500;
         ui->fmDeviation->setText(QString("%1").arg(m_settings.m_fmDeviation));
     } else {
         m_settings.m_fmDeviation = fmDeviation;
     }
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_gainIn_valueChanged
void UDPSourceGUI::on_gainIn_valueChanged (int value) private slot
Definition at line 394 of file udpsourcegui.cpp.
References applySettings(), arg(), UDPSourceSettings::m_gainIn, m_settings, and ui.
 {
     m_settings.m_gainIn = value / 10.0;
     ui->gainInText->setText(tr("%1").arg(m_settings.m_gainIn, 0, 'f', 1));
     applySettings();
 }
on_gainOut_valueChanged
void UDPSourceGUI::on_gainOut_valueChanged (int value) private slot
Definition at line 401 of file udpsourcegui.cpp.
References applySettings(), arg(), UDPSourceSettings::m_gainOut, m_settings, and ui.
 {
     m_settings.m_gainOut = value / 10.0;
     ui->gainOutText->setText(tr("%1").arg(m_settings.m_gainOut, 0, 'f', 1));
     applySettings();
 }
on_localUDPAddress_editingFinished
void UDPSourceGUI::on_localUDPAddress_editingFinished () private slot
Definition at line 297 of file udpsourcegui.cpp.
References m_settings, UDPSourceSettings::m_udpAddress, and ui.
 {
     m_settings.m_udpAddress = ui->localUDPAddress->text();
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_localUDPPort_editingFinished
void UDPSourceGUI::on_localUDPPort_editingFinished () private slot
Definition at line 304 of file udpsourcegui.cpp.
References arg(), m_settings, UDPSourceSettings::m_udpPort, and ui.
 {
     bool ok;
     quint16 udpPort = ui->localUDPPort->text().toInt(&ok);
     if((!ok) || (udpPort < 1024)) {
         udpPort = 9998;
     }
     m_settings.m_udpPort = udpPort;
     ui->localUDPPort->setText(tr("%1").arg(m_settings.m_udpPort));
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_resetUDPReadIndex_clicked
void UDPSourceGUI::on_resetUDPReadIndex_clicked () private slot
Definition at line 448 of file udpsourcegui.cpp.
References m_udpSource, and UDPSource::resetReadIndex().
 {
     m_udpSource->resetReadIndex();
 }
on_rfBandwidth_textEdited
void UDPSourceGUI::on_rfBandwidth_textEdited (const QString & arg1) private slot
Definition at line 337 of file udpsourcegui.cpp.
References arg(), UDPSourceSettings::m_inputSampleRate, UDPSourceSettings::m_rfBandwidth, m_rfBandwidthChanged, m_settings, and ui.
 {
     (void) arg1;
     bool ok;
     Real rfBandwidth = ui->rfBandwidth->text().toDouble(&ok);
     if ((!ok) || (rfBandwidth > m_settings.m_inputSampleRate))
     {
         m_settings.m_rfBandwidth = m_settings.m_inputSampleRate;
         ui->rfBandwidth->setText(QString("%1").arg(m_settings.m_rfBandwidth, 0));
     }
     else
     {
         m_settings.m_rfBandwidth = rfBandwidth;
     }
     m_rfBandwidthChanged = true;
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_sampleFormat_currentIndexChanged
void UDPSourceGUI::on_sampleFormat_currentIndexChanged (int index) private slot
Definition at line 277 of file udpsourcegui.cpp.
References UDPSourceSettings::FormatAM, UDPSourceSettings::FormatNFM, setSampleFormat(), and ui.
 {
     if (index == (int) UDPSourceSettings::FormatNFM) {
         ui->fmDeviation->setEnabled(true);
     } else {
         ui->fmDeviation->setEnabled(false);
     }
     if (index == (int) UDPSourceSettings::FormatAM) {
         ui->amModPercent->setEnabled(true);
     } else {
         ui->amModPercent->setEnabled(false);
     }
     setSampleFormat(index);
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_sampleRate_textEdited
void UDPSourceGUI::on_sampleRate_textEdited (const QString & arg1) private slot
Definition at line 320 of file udpsourcegui.cpp.
References arg(), UDPSourceSettings::m_inputSampleRate, m_settings, and ui.
 {
     (void) arg1;
     bool ok;
     Real inputSampleRate = ui->sampleRate->text().toDouble(&ok);
     if ((!ok) || (inputSampleRate < 1000)) {
         m_settings.m_inputSampleRate = 48000;
         ui->sampleRate->setText(QString("%1").arg(m_settings.m_inputSampleRate, 0));
     } else {
         m_settings.m_inputSampleRate = inputSampleRate;
     }
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_squelch_valueChanged
void UDPSourceGUI::on_squelch_valueChanged (int value) private slot
Definition at line 408 of file udpsourcegui.cpp.
References applySettings(), arg(), m_settings, UDPSourceSettings::m_squelch, UDPSourceSettings::m_squelchEnabled, and ui.
 {
     m_settings.m_squelchEnabled = (value != -100);
     m_settings.m_squelch = value * 1.0;
     if (m_settings.m_squelchEnabled) {
         ui->squelchText->setText(tr("%1").arg(m_settings.m_squelch, 0, 'f', 0));
     } else {
         ui->squelchText->setText("---");
     }
     applySettings();
 }
on_squelchGate_valueChanged
void UDPSourceGUI::on_squelchGate_valueChanged (int value) private slot
Definition at line 422 of file udpsourcegui.cpp.
References applySettings(), arg(), m_settings, UDPSourceSettings::m_squelchGate, and ui.
 {
     m_settings.m_squelchGate = value / 100.0;
     ui->squelchGateText->setText(tr("%1").arg(roundf(value * 10.0), 0, 'f', 0));
     applySettings();
 }
on_stereoInput_toggled
void UDPSourceGUI::on_stereoInput_toggled (bool checked) private slot
Definition at line 459 of file udpsourcegui.cpp.
References applySettings(), m_settings, and UDPSourceSettings::m_stereoInput.
 {
     m_settings.m_stereoInput = checked;
     applySettings();
 }
onMenuDialogCalled
void UDPSourceGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 473 of file udpsourcegui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, UDPSourceSettings::m_inputFrequencyOffset, UDPSourceSettings::m_reverseAPIAddress, UDPSourceSettings::m_reverseAPIChannelIndex, UDPSourceSettings::m_reverseAPIDeviceIndex, UDPSourceSettings::m_reverseAPIPort, UDPSourceSettings::m_rgbColor, m_settings, UDPSourceSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by UDPSourceGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_channelMarker.getTitle());
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void UDPSourceGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 465 of file udpsourcegui.cpp.
References m_udpSource, UDPSource::setSpectrum(), and ui.
Referenced by UDPSourceGUI().
 {
     if ((widget == ui->spectrumBox) && (m_udpSource != 0))
     {
         m_udpSource->setSpectrum(rollDown);
     }
 }
resetToDefaults()
void UDPSourceGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 62 of file udpsourcegui.cpp.
References applySettings(), displaySettings(), m_settings, and UDPSourceSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
serialize()
QByteArray UDPSourceGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 69 of file udpsourcegui.cpp.
References m_settings, and UDPSourceSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void UDPSourceGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 56 of file udpsourcegui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     applySettings();
 }
setName()
void UDPSourceGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 42 of file udpsourcegui.cpp.
 {
     setObjectName(name);
 }
setSampleFormat()
void UDPSourceGUI::setSampleFormat (int index) private
Definition at line 581 of file udpsourcegui.cpp.
References UDPSourceSettings::FormatAM, UDPSourceSettings::FormatLSB, UDPSourceSettings::FormatNFM, UDPSourceSettings::FormatSnLE, UDPSourceSettings::FormatUSB, UDPSourceSettings::m_sampleFormat, m_settings, and ui.
Referenced by on_sampleFormat_currentIndexChanged().
 {
     switch(index)
     {
     case 0:
         m_settings.m_sampleFormat = UDPSourceSettings::FormatSnLE;
         ui->fmDeviation->setEnabled(false);
         ui->stereoInput->setChecked(true);
         ui->stereoInput->setEnabled(false);
         break;
     case 1:
         m_settings.m_sampleFormat = UDPSourceSettings::FormatNFM;
         ui->fmDeviation->setEnabled(true);
         ui->stereoInput->setEnabled(true);
         break;
     case 2:
         m_settings.m_sampleFormat = UDPSourceSettings::FormatLSB;
         ui->fmDeviation->setEnabled(false);
         ui->stereoInput->setEnabled(true);
         break;
     case 3:
         m_settings.m_sampleFormat = UDPSourceSettings::FormatUSB;
         ui->fmDeviation->setEnabled(false);
         ui->stereoInput->setEnabled(true);
         break;
     case 4:
         m_settings.m_sampleFormat = UDPSourceSettings::FormatAM;
         ui->fmDeviation->setEnabled(false);
         ui->stereoInput->setEnabled(true);
         break;
     default:
         m_settings.m_sampleFormat = UDPSourceSettings::FormatSnLE;
         ui->fmDeviation->setEnabled(false);
         ui->stereoInput->setChecked(true);
         ui->stereoInput->setEnabled(false);
         break;
     }
 }
setSampleFormatIndex()
void UDPSourceGUI::setSampleFormatIndex (const UDPSourceSettings::SampleFormat & sampleFormat) private
Definition at line 542 of file udpsourcegui.cpp.
References UDPSourceSettings::FormatAM, UDPSourceSettings::FormatLSB, UDPSourceSettings::FormatNFM, UDPSourceSettings::FormatSnLE, UDPSourceSettings::FormatUSB, and ui.
Referenced by displaySettings().
 {
     switch(sampleFormat)
     {
         case UDPSourceSettings::FormatSnLE:
             ui->sampleFormat->setCurrentIndex(0);
             ui->fmDeviation->setEnabled(false);
             ui->stereoInput->setChecked(true);
             ui->stereoInput->setEnabled(false);
             break;
         case UDPSourceSettings::FormatNFM:
             ui->sampleFormat->setCurrentIndex(1);
             ui->fmDeviation->setEnabled(true);
             ui->stereoInput->setEnabled(true);
             break;
         case UDPSourceSettings::FormatLSB:
             ui->sampleFormat->setCurrentIndex(2);
             ui->fmDeviation->setEnabled(false);
             ui->stereoInput->setEnabled(true);
             break;
         case UDPSourceSettings::FormatUSB:
             ui->sampleFormat->setCurrentIndex(3);
             ui->fmDeviation->setEnabled(false);
             ui->stereoInput->setEnabled(true);
             break;
         case UDPSourceSettings::FormatAM:
             ui->sampleFormat->setCurrentIndex(4);
             ui->fmDeviation->setEnabled(false);
             ui->stereoInput->setEnabled(true);
             break;
         default:
             ui->sampleFormat->setCurrentIndex(0);
             ui->fmDeviation->setEnabled(false);
             ui->stereoInput->setChecked(true);
             ui->stereoInput->setEnabled(false);
             break;
     }
 }
tick
void UDPSourceGUI::tick () private slot
Definition at line 514 of file udpsourcegui.cpp.
References arg(), MovingAverageUtil< T, Total, N >::asDouble(), CalcDb::dbPower(), UDPSource::getBufferGauge(), UDPSource::getInMagSq(), UDPSource::getMagSq(), UDPSource::getSquelchOpen(), m_channelPowerAvg, m_inPowerAvg, m_tickCount, m_udpSource, and ui.
Referenced by UDPSourceGUI().
 {
     m_channelPowerAvg(m_udpSource->getMagSq());
     m_inPowerAvg(m_udpSource->getInMagSq());
     if (m_tickCount % 4 == 0)
     {
         double powDb = CalcDb::dbPower(m_channelPowerAvg.asDouble());
         ui->channelPower->setText(tr("%1 dB").arg(powDb, 0, 'f', 1));
         double inPowDb = CalcDb::dbPower(m_inPowerAvg.asDouble());
         ui->inputPower->setText(tr("%1").arg(inPowDb, 0, 'f', 1));
     }
     int32_t bufferGauge = m_udpSource->getBufferGauge();
     ui->bufferGaugeNegative->setValue((bufferGauge < 0 ? -bufferGauge : 0));
     ui->bufferGaugePositive->setValue((bufferGauge < 0 ? 0 : bufferGauge));
     QString s = QString::number(bufferGauge, 'f', 0);
     ui->bufferRWBalanceText->setText(tr("%1").arg(s));
     if (m_udpSource->getSquelchOpen()) {
         ui->channelMute->setStyleSheet("QToolButton { background-color : green; }");
     } else {
         ui->channelMute->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     m_tickCount++;
 }
Member Data Documentation
m_channelMarker
ChannelMarker UDPSourceGUI::m_channelMarker private
Definition at line 70 of file udpsourcegui.h.
Referenced by channelMarkerChangedByCursor(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), on_applyBtn_clicked(), on_deltaFrequency_changed(), onMenuDialogCalled(), setCenterFrequency(), and UDPSourceGUI().
m_channelPowerAvg
MovingAverageUtil<double, double, 4> UDPSourceGUI::m_channelPowerAvg private
Definition at line 67 of file udpsourcegui.h.
Referenced by tick().
m_deviceUISet
DeviceUISet* UDPSourceGUI::m_deviceUISet private
Definition at line 64 of file udpsourcegui.h.
Referenced by UDPSourceGUI(), and ~UDPSourceGUI().
m_doApplySettings
bool UDPSourceGUI::m_doApplySettings private
Definition at line 75 of file udpsourcegui.h.
Referenced by applySettings(), and blockApplySettings().
m_inPowerAvg
MovingAverageUtil<double, double, 4> UDPSourceGUI::m_inPowerAvg private
Definition at line 68 of file udpsourcegui.h.
Referenced by tick().
m_inputMessageQueue
MessageQueue UDPSourceGUI::m_inputMessageQueue private
Definition at line 76 of file udpsourcegui.h.
m_pluginAPI
PluginAPI* UDPSourceGUI::m_pluginAPI private
Definition at line 63 of file udpsourcegui.h.
m_rfBandwidthChanged
bool UDPSourceGUI::m_rfBandwidthChanged private
Definition at line 74 of file udpsourcegui.h.
Referenced by on_applyBtn_clicked(), and on_rfBandwidth_textEdited().
m_settings
UDPSourceSettings UDPSourceGUI::m_settings private
Definition at line 73 of file udpsourcegui.h.
Referenced by applySettings(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), handleMessage(), on_amModPercent_textEdited(), on_applyBtn_clicked(), on_autoRWBalance_toggled(), on_channelMute_toggled(), on_deltaFrequency_changed(), on_fmDeviation_textEdited(), on_gainIn_valueChanged(), on_gainOut_valueChanged(), on_localUDPAddress_editingFinished(), on_localUDPPort_editingFinished(), on_rfBandwidth_textEdited(), on_sampleRate_textEdited(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_stereoInput_toggled(), onMenuDialogCalled(), resetToDefaults(), serialize(), setSampleFormat(), and UDPSourceGUI().
m_spectrumVis
SpectrumVis* UDPSourceGUI::m_spectrumVis private
Definition at line 65 of file udpsourcegui.h.
Referenced by UDPSourceGUI(), and ~UDPSourceGUI().
m_tickCount
uint32_t UDPSourceGUI::m_tickCount private
Definition at line 69 of file udpsourcegui.h.
Referenced by tick().
m_udpSource
UDPSource* UDPSourceGUI::m_udpSource private
Definition at line 66 of file udpsourcegui.h.
Referenced by applySettings(), on_resetUDPReadIndex_clicked(), onWidgetRolled(), tick(), UDPSourceGUI(), and ~UDPSourceGUI().
ui
Ui::UDPSourceGUI* UDPSourceGUI::ui private
Definition at line 62 of file udpsourcegui.h.
Referenced by applySettings(), channelMarkerChangedByCursor(), displaySettings(), on_amModPercent_textEdited(), on_applyBtn_clicked(), on_fmDeviation_textEdited(), on_gainIn_valueChanged(), on_gainOut_valueChanged(), on_localUDPAddress_editingFinished(), on_localUDPPort_editingFinished(), on_rfBandwidth_textEdited(), on_sampleFormat_currentIndexChanged(), on_sampleRate_textEdited(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), onWidgetRolled(), setSampleFormat(), setSampleFormatIndex(), tick(), UDPSourceGUI(), and ~UDPSourceGUI().
The documentation for this class was generated from the following files:
plugins/channeltx/udpsource/udpsourcegui.h
plugins/channeltx/udpsource/udpsourcegui.cpp