SDRAngel: PlutoSDROutput::MsgConfigurePlutoSDR Class Reference
PlutoSDROutput::MsgConfigurePlutoSDR Class Reference
#include <plutosdroutput.h>
Public Member Functions
const PlutoSDROutputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigurePlutoSDR * create (const PlutoSDROutputSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigurePlutoSDR (const PlutoSDROutputSettings &settings, bool force)
Private Attributes
PlutoSDROutputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 39 of file plutosdroutput.h.
Constructor & Destructor Documentation
MsgConfigurePlutoSDR()
PlutoSDROutput::MsgConfigurePlutoSDR::MsgConfigurePlutoSDR (const PlutoSDROutputSettings & settings, bool force) inline private
Definition at line 55 of file plutosdroutput.h.
Referenced by create().
                                                                                  :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigurePlutoSDR* PlutoSDROutput::MsgConfigurePlutoSDR::create (const PlutoSDROutputSettings & settings, bool force) inline static
Definition at line 46 of file plutosdroutput.h.
References MsgConfigurePlutoSDR().
Referenced by PlutoSDROutput::deserialize(), PlutoSDROutput::setCenterFrequency(), PlutoSDROutputGUI::updateHardware(), and PlutoSDROutput::webapiSettingsPutPatch().
         {
             return new MsgConfigurePlutoSDR(settings, force);
         }
getForce()
bool PlutoSDROutput::MsgConfigurePlutoSDR::getForce () const inline
Definition at line 44 of file plutosdroutput.h.
References m_force.
Referenced by PlutoSDROutput::handleMessage().
 { return m_force; }
getSettings()
const PlutoSDROutputSettings& PlutoSDROutput::MsgConfigurePlutoSDR::getSettings () const inline
Definition at line 43 of file plutosdroutput.h.
References m_settings.
Referenced by PlutoSDROutputGUI::handleMessage(), and PlutoSDROutput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool PlutoSDROutput::MsgConfigurePlutoSDR::m_force private
Definition at line 53 of file plutosdroutput.h.
Referenced by getForce().
m_settings
PlutoSDROutputSettings PlutoSDROutput::MsgConfigurePlutoSDR::m_settings private
Definition at line 52 of file plutosdroutput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesink/plutosdroutput/plutosdroutput.h