SDRAngel: AMDemodGUI Class Reference
AMDemodGUI Class Reference
#include <amdemodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
void channelMarkerHighlightedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static AMDemodGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
Private Slots
void on_deltaFrequency_changed (qint64 value)
void on_pll_toggled (bool checked)
void on_ssb_toggled (bool checked)
void on_bandpassEnable_toggled (bool checked)
void on_rfBW_valueChanged (int value)
void on_volume_valueChanged (int value)
void on_squelch_valueChanged (int value)
void on_audioMute_toggled (bool checked)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void handleInputMessages ()
void audioSelect ()
void samSSBSelect ()
void tick ()
Private Member Functions
AMDemodGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *parent=0)
virtual ~AMDemodGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
void displayStreamIndex ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::AMDemodGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
AMDemodSettings m_settings
bool m_doApplySettings
AMDemod * m_amDemod
bool m_squelchOpen
bool m_samUSB
uint32_t m_tickCount
MessageQueue m_inputMessageQueue
QIcon m_iconDSBUSB
QIcon m_iconDSBLSB
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 23 of file amdemodgui.h.
Constructor & Destructor Documentation
AMDemodGUI()
AMDemodGUI::AMDemodGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * parent = 0) explicit private
Definition at line 251 of file amdemodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), arg(), audioSelect(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), LevelMeterSignalDB::ColorGreenAndBlue, displaySettings(), ChannelMarker::getColor(), getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, handleInputMessages(), m_amDemod, AMDemod::m_channelIdURI, m_channelMarker, m_deviceUISet, m_iconDSBLSB, m_iconDSBUSB, m_settings, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), samSSBSelect(), ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), AMDemodSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSink::setMessageQueueToGUI(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                      :
     RollupWidget(parent),
     ui(new Ui::AMDemodGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_doApplySettings(true),
     m_squelchOpen(false),
     m_samUSB(true),
     m_tickCount(0)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_amDemod = reinterpret_cast<AMDemod*>(rxChannel); //new AMDemod(m_deviceUISet->m_deviceSourceAPI);
     m_amDemod->setMessageQueueToGUI(getInputMessageQueue());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick())); // 50 ms
     CRightClickEnabler *audioMuteRightClickEnabler = new CRightClickEnabler(ui->audioMute);
     connect(audioMuteRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioSelect()));
     CRightClickEnabler *samSidebandRightClickEnabler = new CRightClickEnabler(ui->ssb);
     connect(samSidebandRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(samSSBSelect()));
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     ui->channelPowerMeter->setColorTheme(LevelMeterSignalDB::ColorGreenAndBlue);
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(Qt::yellow);
     m_channelMarker.setBandwidth(5000);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("AM Demodulator");
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     setTitleColor(m_channelMarker.getColor());
     m_settings.setChannelMarker(&m_channelMarker);
     m_deviceUISet->registerRxChannelInstance(AMDemod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(&m_channelMarker, SIGNAL(highlightedByCursor()), this, SLOT(channelMarkerHighlightedByCursor()));
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
     m_iconDSBUSB.addPixmap(QPixmap("://dsb.png"), QIcon::Normal, QIcon::Off);
     m_iconDSBUSB.addPixmap(QPixmap("://usb.png"), QIcon::Normal, QIcon::On);
     m_iconDSBLSB.addPixmap(QPixmap("://dsb.png"), QIcon::Normal, QIcon::Off);
     m_iconDSBLSB.addPixmap(QPixmap("://lsb.png"), QIcon::Normal, QIcon::On);
     displaySettings();
     applySettings(true);
 }
~AMDemodGUI()
AMDemodGUI::~AMDemodGUI () private virtual
Definition at line 311 of file amdemodgui.cpp.
References m_amDemod, m_deviceUISet, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_amDemod; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete ui;
 }
Member Function Documentation
applySettings()
void AMDemodGUI::applySettings (bool force = false) private
Definition at line 323 of file amdemodgui.cpp.
References AMDemod::MsgConfigureAMDemod::create(), AMDemod::MsgConfigureChannelizer::create(), AMDemod::getAudioSampleRate(), ChannelMarker::getCenterFrequency(), BasebandSampleSink::getInputMessageQueue(), m_amDemod, m_channelMarker, m_doApplySettings, m_settings, and MessageQueue::push().
Referenced by AMDemodGUI(), audioSelect(), channelMarkerChangedByCursor(), deserialize(), on_audioMute_toggled(), on_bandpassEnable_toggled(), on_deltaFrequency_changed(), on_pll_toggled(), on_rfBW_valueChanged(), on_squelch_valueChanged(), on_ssb_toggled(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), samSSBSelect(), and setCenterFrequency().
 {
     if (m_doApplySettings)
     {
         AMDemod::MsgConfigureChannelizer* channelConfigMsg = AMDemod::MsgConfigureChannelizer::create(
                 m_amDemod->getAudioSampleRate(), m_channelMarker.getCenterFrequency());
         m_amDemod->getInputMessageQueue()->push(channelConfigMsg);
         AMDemod::MsgConfigureAMDemod* message = AMDemod::MsgConfigureAMDemod::create( m_settings, force);
         m_amDemod->getInputMessageQueue()->push(message);
     }
 }
audioSelect
void AMDemodGUI::audioSelect () private slot
Definition at line 420 of file amdemodgui.cpp.
References applySettings(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, AMDemodSettings::m_audioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by AMDemodGUI().
 {
     qDebug("AMDemodGUI::audioSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName);
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_audioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
blockApplySettings()
void AMDemodGUI::blockApplySettings (bool block) private
Definition at line 318 of file amdemodgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void AMDemodGUI::channelMarkerChangedByCursor () slot
Definition at line 126 of file amdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, AMDemodSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by AMDemodGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
channelMarkerHighlightedByCursor
void AMDemodGUI::channelMarkerHighlightedByCursor () slot
Definition at line 133 of file amdemodgui.cpp.
References ChannelMarker::getHighlighted(), m_channelMarker, and RollupWidget::setHighlighted().
Referenced by AMDemodGUI().
 {
     setHighlighted(m_channelMarker.getHighlighted());
 }
create()
AMDemodGUI * AMDemodGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) static
Definition at line 42 of file amdemodgui.cpp.
References AMDemodGUI().
Referenced by AMDemodPlugin::createRxChannelGUI().
 {
     AMDemodGUI* gui = new AMDemodGUI(pluginAPI, deviceUISet, rxChannel);
     return gui;
 }
deserialize()
bool AMDemodGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 85 of file amdemodgui.cpp.
References applySettings(), AMDemodSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void AMDemodGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 48 of file amdemodgui.cpp.
 {
     delete this;
 }
displaySettings()
void AMDemodGUI::displaySettings () private
Definition at line 337 of file amdemodgui.cpp.
References arg(), blockApplySettings(), displayStreamIndex(), ChannelMarker::getCenterFrequency(), ChannelMarker::getTitle(), AMDemodSettings::m_audioMute, AMDemodSettings::m_bandpassEnable, m_channelMarker, m_iconDSBLSB, m_iconDSBUSB, AMDemodSettings::m_inputFrequencyOffset, AMDemodSettings::m_pll, AMDemodSettings::m_rfBandwidth, AMDemodSettings::m_rgbColor, m_samUSB, m_settings, AMDemodSettings::m_squelch, AMDemodSettings::m_syncAMOperation, AMDemodSettings::m_title, AMDemodSettings::m_volume, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), AMDemodSettings::SyncAMLSB, AMDemodSettings::SyncAMUSB, and ui.
Referenced by AMDemodGUI(), deserialize(), handleMessage(), and resetToDefaults().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setBandwidth(m_settings.m_rfBandwidth);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     int displayValue = m_settings.m_rfBandwidth/100.0;
     ui->rfBW->setValue(displayValue);
     ui->rfBWText->setText(QString("%1 kHz").arg(displayValue / 10.0, 0, 'f', 1));
     ui->volume->setValue(m_settings.m_volume * 10.0);
     ui->volumeText->setText(QString("%1").arg(m_settings.m_volume, 0, 'f', 1));
     ui->squelch->setValue(m_settings.m_squelch);
     ui->squelchText->setText(QString("%1 dB").arg(m_settings.m_squelch));
     ui->audioMute->setChecked(m_settings.m_audioMute);
     ui->bandpassEnable->setChecked(m_settings.m_bandpassEnable);
     ui->pll->setChecked(m_settings.m_pll);
     qDebug() << "AMDemodGUI::displaySettings:"
             << " m_pll: " << m_settings.m_pll
             << " m_syncAMOperation: " << m_settings.m_syncAMOperation;
     if (m_settings.m_pll)
     {
         if (m_settings.m_syncAMOperation == AMDemodSettings::SyncAMLSB)
         {
             m_samUSB = false;
             ui->ssb->setChecked(true);
             ui->ssb->setIcon(m_iconDSBLSB);
         }
         else if (m_settings.m_syncAMOperation == AMDemodSettings::SyncAMUSB)
         {
             m_samUSB = true;
             ui->ssb->setChecked(true);
             ui->ssb->setIcon(m_iconDSBUSB);
         }
         else
         {
             ui->ssb->setChecked(false);
         }
     }
     else
     {
         ui->ssb->setChecked(false);
         ui->ssb->setIcon(m_iconDSBUSB);
     }
     displayStreamIndex();
     blockApplySettings(false);
 }
displayStreamIndex()
void AMDemodGUI::displayStreamIndex () private
Definition at line 401 of file amdemodgui.cpp.
References arg(), DeviceUISet::m_deviceMIMOEngine, m_deviceUISet, m_settings, AMDemodSettings::m_streamIndex, and RollupWidget::setStreamIndicator().
Referenced by displaySettings(), and onMenuDialogCalled().
 {
     if (m_deviceUISet->m_deviceMIMOEngine) {
         setStreamIndicator(tr("%1").arg(m_settings.m_streamIndex));
     } else {
         setStreamIndicator("S"); // single channel indicator
     }
 }
enterEvent()
void AMDemodGUI::enterEvent (QEvent *) private
Definition at line 415 of file amdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 AMDemodGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 63 of file amdemodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
{
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* AMDemodGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 38 of file amdemodgui.h.
Referenced by AMDemodGUI(), and handleInputMessages().
 { return &m_inputMessageQueue; }
getName()
QString AMDemodGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 58 of file amdemodgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void AMDemodGUI::handleInputMessages () private slot
Definition at line 113 of file amdemodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by AMDemodGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
bool AMDemodGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 97 of file amdemodgui.cpp.
References blockApplySettings(), displaySettings(), AMDemod::MsgConfigureAMDemod::getSettings(), m_settings, and Message::match().
Referenced by handleInputMessages().
 {
     if (AMDemod::MsgConfigureAMDemod::match(message))
     {
         qDebug("AMDemodGUI::handleMessage: AMDemod::MsgConfigureAMDemod");
         const AMDemod::MsgConfigureAMDemod& cfg = (AMDemod::MsgConfigureAMDemod&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     return false;
 }
leaveEvent()
void AMDemodGUI::leaveEvent (QEvent *) private
Definition at line 410 of file amdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_audioMute_toggled
void AMDemodGUI::on_audioMute_toggled (bool checked) private slot
Definition at line 191 of file amdemodgui.cpp.
References applySettings(), AMDemodSettings::m_audioMute, and m_settings.
 {
     m_settings.m_audioMute = checked;
     applySettings();
 }
on_bandpassEnable_toggled
void AMDemodGUI::on_bandpassEnable_toggled (bool checked) private slot
Definition at line 163 of file amdemodgui.cpp.
References applySettings(), AMDemodSettings::m_bandpassEnable, and m_settings.
 {
     m_settings.m_bandpassEnable = checked;
     applySettings();
 }
on_deltaFrequency_changed
void AMDemodGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 138 of file amdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, AMDemodSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_pll_toggled
void AMDemodGUI::on_pll_toggled (bool checked) private slot
Definition at line 145 of file amdemodgui.cpp.
References applySettings(), AMDemodSettings::m_pll, m_settings, and ui.
 {
     if (!checked)
     {
         ui->pll->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         ui->pll->setToolTip(tr("PLL for synchronous AM"));
     }
     m_settings.m_pll = checked;
     applySettings();
 }
on_rfBW_valueChanged
void AMDemodGUI::on_rfBW_valueChanged (int value) private slot
Definition at line 169 of file amdemodgui.cpp.
References applySettings(), arg(), m_channelMarker, AMDemodSettings::m_rfBandwidth, m_settings, ChannelMarker::setBandwidth(), and ui.
 {
     ui->rfBWText->setText(QString("%1 kHz").arg(value / 10.0, 0, 'f', 1));
     m_channelMarker.setBandwidth(value * 100);
     m_settings.m_rfBandwidth = value * 100;
     applySettings();
 }
on_squelch_valueChanged
void AMDemodGUI::on_squelch_valueChanged (int value) private slot
Definition at line 184 of file amdemodgui.cpp.
References applySettings(), arg(), m_settings, AMDemodSettings::m_squelch, and ui.
 {
     ui->squelchText->setText(QString("%1 dB").arg(value));
     m_settings.m_squelch = value;
     applySettings();
 }
on_ssb_toggled
void AMDemodGUI::on_ssb_toggled (bool checked) private slot
Definition at line 157 of file amdemodgui.cpp.
References applySettings(), m_samUSB, m_settings, AMDemodSettings::m_syncAMOperation, AMDemodSettings::SyncAMDSB, AMDemodSettings::SyncAMLSB, and AMDemodSettings::SyncAMUSB.
 {
     m_settings.m_syncAMOperation = checked ? m_samUSB ? AMDemodSettings::SyncAMUSB : AMDemodSettings::SyncAMLSB : AMDemodSettings::SyncAMDSB;
     applySettings();
 }
on_volume_valueChanged
void AMDemodGUI::on_volume_valueChanged (int value) private slot
Definition at line 177 of file amdemodgui.cpp.
References applySettings(), arg(), m_settings, AMDemodSettings::m_volume, and ui.
 {
     ui->volumeText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_volume = value / 10.0;
     applySettings();
 }
onMenuDialogCalled
void AMDemodGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 207 of file amdemodgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, RollupWidget::ContextMenuStreamSettings, displayStreamIndex(), ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), AMDemod::getNumberOfDeviceStreams(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), DeviceStreamSelectionDialog::getSelectedStreamIndex(), ChannelMarker::getTitle(), m_amDemod, m_channelMarker, RollupWidget::m_contextMenuType, DeviceUISet::m_deviceMIMOEngine, m_deviceUISet, AMDemodSettings::m_inputFrequencyOffset, AMDemodSettings::m_reverseAPIAddress, AMDemodSettings::m_reverseAPIChannelIndex, AMDemodSettings::m_reverseAPIDeviceIndex, AMDemodSettings::m_reverseAPIPort, AMDemodSettings::m_rgbColor, m_settings, AMDemodSettings::m_streamIndex, AMDemodSettings::m_title, AMDemodSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), DeviceStreamSelectionDialog::setNumberOfStreams(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), DeviceStreamSelectionDialog::setStreamIndex(), ChannelMarker::setStreamIndex(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by AMDemodGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     else if ((m_contextMenuType == ContextMenuStreamSettings) && (m_deviceUISet->m_deviceMIMOEngine))
     {
         DeviceStreamSelectionDialog dialog(this);
         dialog.setNumberOfStreams(m_amDemod->getNumberOfDeviceStreams());
         dialog.setStreamIndex(m_settings.m_streamIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_streamIndex = dialog.getSelectedStreamIndex();
         m_channelMarker.setStreamIndex(m_settings.m_streamIndex);
         displayStreamIndex();
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void AMDemodGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 197 of file amdemodgui.cpp.
Referenced by AMDemodGUI().
 {
     (void) widget;
     (void) rollDown;
     /*
     if((widget == ui->spectrumContainer) && (m_nfmDemod != NULL))
         m_nfmDemod->setSpectrum(m_threadedSampleSink->getMessageQueue(), rollDown);
     */
 }
resetToDefaults()
void AMDemodGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 73 of file amdemodgui.cpp.
References applySettings(), displaySettings(), m_settings, and AMDemodSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
samSSBSelect
void AMDemodGUI::samSSBSelect () private slot
Definition at line 433 of file amdemodgui.cpp.
References applySettings(), AMDemodSSBDialog::isUsb(), m_iconDSBLSB, m_iconDSBUSB, m_samUSB, m_settings, AMDemodSettings::m_syncAMOperation, AMDemodSettings::SyncAMDSB, AMDemodSettings::SyncAMLSB, AMDemodSettings::SyncAMUSB, and ui.
Referenced by AMDemodGUI().
 {
     AMDemodSSBDialog ssbSelect(m_samUSB);
     ssbSelect.exec();
     ui->ssb->setIcon(ssbSelect.isUsb() ? m_iconDSBUSB : m_iconDSBLSB);
     if (ssbSelect.isUsb() != m_samUSB)
     {
         qDebug("AMDemodGUI::samSSBSelect: %s", ssbSelect.isUsb() ? "usb" : "lsb");
         m_samUSB = ssbSelect.isUsb();
         if (m_settings.m_syncAMOperation != AMDemodSettings::SyncAMDSB)
         {
             m_settings.m_syncAMOperation = m_samUSB ? AMDemodSettings::SyncAMUSB : AMDemodSettings::SyncAMLSB;
             applySettings();
         }
     }
 }
serialize()
QByteArray AMDemodGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 80 of file amdemodgui.cpp.
References m_settings, and AMDemodSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void AMDemodGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 67 of file amdemodgui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     applySettings();
 }
setName()
void AMDemodGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 53 of file amdemodgui.cpp.
 {
     setObjectName(name);
 }
tick
void AMDemodGUI::tick () private slot
Definition at line 453 of file amdemodgui.cpp.
References arg(), CalcDb::dbPower(), AMDemod::getAudioSampleRate(), AMDemod::getMagSqLevels(), AMDemod::getPllFrequency(), AMDemod::getPllLocked(), AMDemod::getSquelchOpen(), m_amDemod, M_PI, AMDemodSettings::m_pll, m_settings, m_squelchOpen, m_tickCount, and ui.
Referenced by AMDemodGUI().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     m_amDemod->getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     double powDbAvg = CalcDb::dbPower(magsqAvg);
     double powDbPeak = CalcDb::dbPower(magsqPeak);
     ui->channelPowerMeter->levelChanged(
             (100.0f + powDbAvg) / 100.0f,
             (100.0f + powDbPeak) / 100.0f,
             nbMagsqSamples);
     if (m_tickCount % 4 == 0) {
         ui->channelPower->setText(QString::number(powDbAvg, 'f', 1));
     }
     bool squelchOpen = m_amDemod->getSquelchOpen();
     if (squelchOpen != m_squelchOpen)
     {
         m_squelchOpen = squelchOpen;
         if (m_squelchOpen) {
             ui->audioMute->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->audioMute->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         }
     }
     if (m_settings.m_pll)
     {
         if (m_amDemod->getPllLocked()) {
             ui->pll->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->pll->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         }
         int freq = (m_amDemod->getPllFrequency() * m_amDemod->getAudioSampleRate()) / (2.0*M_PI);
         ui->pll->setToolTip(tr("PLL for synchronous AM. Freq = %1 Hz").arg(freq));
     }
     m_tickCount++;
 }
Member Data Documentation
m_amDemod
AMDemod* AMDemodGUI::m_amDemod private
Definition at line 53 of file amdemodgui.h.
Referenced by AMDemodGUI(), applySettings(), onMenuDialogCalled(), tick(), and ~AMDemodGUI().
m_channelMarker
ChannelMarker AMDemodGUI::m_channelMarker private
Definition at line 49 of file amdemodgui.h.
Referenced by AMDemodGUI(), applySettings(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), on_rfBW_valueChanged(), onMenuDialogCalled(), and setCenterFrequency().
m_deviceUISet
DeviceUISet* AMDemodGUI::m_deviceUISet private
Definition at line 48 of file amdemodgui.h.
Referenced by AMDemodGUI(), displayStreamIndex(), onMenuDialogCalled(), and ~AMDemodGUI().
m_doApplySettings
bool AMDemodGUI::m_doApplySettings private
Definition at line 51 of file amdemodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_iconDSBLSB
QIcon AMDemodGUI::m_iconDSBLSB private
Definition at line 60 of file amdemodgui.h.
Referenced by AMDemodGUI(), displaySettings(), and samSSBSelect().
m_iconDSBUSB
QIcon AMDemodGUI::m_iconDSBUSB private
Definition at line 59 of file amdemodgui.h.
Referenced by AMDemodGUI(), displaySettings(), and samSSBSelect().
m_inputMessageQueue
MessageQueue AMDemodGUI::m_inputMessageQueue private
Definition at line 57 of file amdemodgui.h.
m_pluginAPI
PluginAPI* AMDemodGUI::m_pluginAPI private
Definition at line 47 of file amdemodgui.h.
m_samUSB
bool AMDemodGUI::m_samUSB private
Definition at line 55 of file amdemodgui.h.
Referenced by displaySettings(), on_ssb_toggled(), and samSSBSelect().
m_settings
AMDemodSettings AMDemodGUI::m_settings private
Definition at line 50 of file amdemodgui.h.
Referenced by AMDemodGUI(), applySettings(), audioSelect(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), displayStreamIndex(), handleMessage(), on_audioMute_toggled(), on_bandpassEnable_toggled(), on_deltaFrequency_changed(), on_pll_toggled(), on_rfBW_valueChanged(), on_squelch_valueChanged(), on_ssb_toggled(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), samSSBSelect(), serialize(), and tick().
m_squelchOpen
bool AMDemodGUI::m_squelchOpen private
Definition at line 54 of file amdemodgui.h.
Referenced by tick().
m_tickCount
uint32_t AMDemodGUI::m_tickCount private
Definition at line 56 of file amdemodgui.h.
Referenced by tick().
ui
Ui::AMDemodGUI* AMDemodGUI::ui private
Definition at line 46 of file amdemodgui.h.
Referenced by AMDemodGUI(), channelMarkerChangedByCursor(), displaySettings(), on_pll_toggled(), on_rfBW_valueChanged(), on_squelch_valueChanged(), on_volume_valueChanged(), samSSBSelect(), tick(), and ~AMDemodGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/demodam/amdemodgui.h
plugins/channelrx/demodam/amdemodgui.cpp