SDRAngel: qrtplib::RTCPBYEPacket Class Reference
qrtplib::RTCPBYEPacket Class Reference
#include <rtcpbyepacket.h>
Public Member Functions
RTCPBYEPacket (uint8_t *data, std::size_t datalen)
~RTCPBYEPacket ()
int GetSSRCCount () const
uint32_t GetSSRC (int index) const
bool HasReasonForLeaving () const
std::size_t GetReasonLength () const
uint8_t * GetReasonData ()
Public Member Functions inherited from qrtplib::RTCPPacket
virtual ~RTCPPacket ()
bool IsKnownFormat () const
PacketType GetPacketType () const
uint8_t * GetPacketData ()
std::size_t GetPacketLength () const
Private Attributes
RTPEndian m_endian
std::size_t reasonoffset
Additional Inherited Members
Public Types inherited from qrtplib::RTCPPacket
enum PacketType {
SR, RR, SDES, BYE,
APP, Unknown
}
Protected Member Functions inherited from qrtplib::RTCPPacket
RTCPPacket (PacketType t, uint8_t *d, std::size_t dlen)
Protected Attributes inherited from qrtplib::RTCPPacket
uint8_t * data
std::size_t datalen
bool knownformat
Detailed Description
Describes an RTCP BYE packet.
Definition at line 54 of file rtcpbyepacket.h.
Constructor & Destructor Documentation
RTCPBYEPacket()
qrtplib::RTCPBYEPacket::RTCPBYEPacket (uint8_t * data, std::size_t datalen)
Creates an instance based on the data in data with length datalen. Creates an instance based on the data in data with length datalen. Since the data pointer is referenced inside the class (no copy of the data is made) one must make sure that the memory it points to is valid as long as the class instance exists.
Definition at line 38 of file rtcpbyepacket.cpp.
References qrtplib::RTCPCommonHeader::count, qrtplib::RTCPPacket::knownformat, qrtplib::RTCPCommonHeader::padding, and reasonoffset.
                                                                 :
         RTCPPacket(BYE, data, datalength)
 {
     knownformat = false;
     reasonoffset = 0;
     RTCPCommonHeader *hdr;
     std::size_t len = datalength;
     hdr = (RTCPCommonHeader *) data;
     if (hdr->padding)
     {
         uint8_t padcount = data[datalength - 1];
         if ((padcount & 0x03) != 0) // not a multiple of four! (see rfc 3550 p 37)
             return;
         if (((std::size_t) padcount) >= len)
             return;
         len -= (std::size_t) padcount;
     }
     std::size_t ssrclen = ((std::size_t)(hdr->count)) * sizeof(uint32_t) + sizeof(RTCPCommonHeader);
     if (ssrclen > len)
         return;
     if (ssrclen < len) // there's probably a reason for leaving
     {
         uint8_t *reasonlength = (data + ssrclen);
         std::size_t reaslen = (std::size_t)(*reasonlength);
         if (reaslen > (len - ssrclen - 1))
             return;
         reasonoffset = ssrclen;
     }
     knownformat = true;
 }
~RTCPBYEPacket()
qrtplib::RTCPBYEPacket::~RTCPBYEPacket () inline
Definition at line 63 of file rtcpbyepacket.h.
     {
     }
Member Function Documentation
GetReasonData()
uint8_t * qrtplib::RTCPBYEPacket::GetReasonData () inline
Returns the actual reason for leaving data.
Definition at line 125 of file rtcpbyepacket.h.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     if (reasonoffset == 0)
         return 0;
     uint8_t *reasonlen = (data + reasonoffset);
     if ((*reasonlen) == 0)
         return 0;
     return (data + reasonoffset + 1);
 }
GetReasonLength()
std::size_t qrtplib::RTCPBYEPacket::GetReasonLength () const inline
Returns the length of the string which describes why the source(s) left.
Definition at line 115 of file rtcpbyepacket.h.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     if (reasonoffset == 0)
         return 0;
     uint8_t *reasonlen = (data + reasonoffset);
     return (std::size_t)(*reasonlen);
 }
GetSSRC()
uint32_t qrtplib::RTCPBYEPacket::GetSSRC (int index) const inline
Returns the SSRC described by index which may have a value from 0 to GetSSRCCount()-1 (note that no check is performed to see if index is valid).
Definition at line 98 of file rtcpbyepacket.h.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     uint32_t *ssrc = (uint32_t *) (data + sizeof(RTCPCommonHeader) + sizeof(uint32_t) * index);
     return m_endian.qToHost(*ssrc);
 }
GetSSRCCount()
int qrtplib::RTCPBYEPacket::GetSSRCCount () const inline
Returns the number of SSRC identifiers present in this BYE packet.
Definition at line 89 of file rtcpbyepacket.h.
References qrtplib::RTCPCommonHeader::count.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     RTCPCommonHeader *hdr = (RTCPCommonHeader *) data;
     return (int) (hdr->count);
 }
HasReasonForLeaving()
bool qrtplib::RTCPBYEPacket::HasReasonForLeaving () const inline
Returns true if the BYE packet contains a reason for leaving.
Definition at line 106 of file rtcpbyepacket.h.
 {
     if (!knownformat)
         return false;
     if (reasonoffset == 0)
         return false;
     return true;
 }
Member Data Documentation
m_endian
RTPEndian qrtplib::RTCPBYEPacket::m_endian private
Definition at line 85 of file rtcpbyepacket.h.
reasonoffset
std::size_t qrtplib::RTCPBYEPacket::reasonoffset private
Definition at line 86 of file rtcpbyepacket.h.
Referenced by RTCPBYEPacket().
The documentation for this class was generated from the following files:
qrtplib/rtcpbyepacket.h
qrtplib/rtcpbyepacket.cpp