SDRAngel: LocalSource Class Reference
LocalSource Class Reference
#include <localsource.h>
Classes
class MsgConfigureChannelizer
class MsgConfigureLocalSource
class MsgSampleRateNotification
Signals
void pullSamples (unsigned int count)
Public Member Functions
LocalSource (DeviceAPI *deviceAPI)
virtual ~LocalSource ()
virtual void destroy ()
virtual void pull (Sample &sample)
virtual void pullAudio (int nbSamples)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
void setCenterFrequency (uint64_t centerFrequency)
void setSampleRate (uint32_t sampleRate)
void setChannelizer (unsigned int log2Interp, unsigned int filterChainHash)
void getLocalDevices (std::vector< uint32_t > &indexes)
Public Member Functions inherited from BasebandSampleSource
BasebandSampleSource ()
virtual ~BasebandSampleSource ()
void feed (SampleSourceFifo *sampleFifo, int nbSamples)
SampleSourceFifo & getSampleSourceFifo ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
void setDeviceSampleSourceFifo (SampleSourceFifo *deviceSampleFifo)
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.localsource"
static const QString m_channelId = "LocalSource"
Private Slots
void networkManagerFinished (QNetworkReply *reply)
void processSamples (int offset)
Private Member Functions
void applySettings (const LocalSourceSettings &settings, bool force=false)
DeviceSampleSink * getLocalDevice (uint32_t index)
void propagateSampleRateAndFrequency (uint32_t index)
void validateFilterChainHash (LocalSourceSettings &settings)
void calculateFrequencyOffset ()
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const LocalSourceSettings &settings)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const LocalSourceSettings &settings, bool force)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSource * m_threadedChannelizer
UpChannelizer * m_channelizer
bool m_running
LocalSourceSettings m_settings
LocalSourceThread * m_sinkThread
SampleSourceFifo * m_localSampleSourceFifo
int m_chunkSize
SampleVector m_localSamples
int m_localSamplesIndex
int m_localSamplesIndexOffset
uint64_t m_centerFrequency
int64_t m_frequencyOffset
uint32_t m_sampleRate
uint32_t m_deviceSampleRate
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
QMutex m_settingsMutex
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSource
void handleInputMessages ()
void handleWriteToFifo (int nbSamples)
void handleWriteToDeviceFifo (int nbSamples)
Protected Member Functions inherited from BasebandSampleSource
void handleWriteToFifo (SampleSourceFifo *sampleFifo, int nbSamples)
Protected Attributes inherited from BasebandSampleSource
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
SampleSourceFifo m_sampleFifo
Internal FIFO for multi-channel processing.
SampleSourceFifo * m_deviceSampleFifo
Reference to the device FIFO for single channel processing.
Detailed Description
Definition at line 38 of file localsource.h.
Constructor & Destructor Documentation
LocalSource()
LocalSource::LocalSource (DeviceAPI * deviceAPI)
Definition at line 48 of file localsource.cpp.
References DeviceAPI::addChannelSource(), DeviceAPI::addChannelSourceAPI(), m_channelId, m_channelizer, m_deviceAPI, m_networkManager, m_threadedChannelizer, and networkManagerFinished().
Referenced by LocalSource::MsgConfigureChannelizer::MsgConfigureChannelizer().
                                              :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSource),
         m_deviceAPI(deviceAPI),
         m_running(false),
         m_sinkThread(nullptr),
         m_localSampleSourceFifo(nullptr),
         m_chunkSize(0),
         m_localSamplesIndex(0),
         m_localSamplesIndexOffset(0),
         m_centerFrequency(0),
         m_frequencyOffset(0),
         m_sampleRate(48000),
         m_deviceSampleRate(48000),
         m_settingsMutex(QMutex::Recursive)
 {
     setObjectName(m_channelId);
     m_channelizer = new UpChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSource(m_channelizer, this);
     m_deviceAPI->addChannelSource(m_threadedChannelizer);
     m_deviceAPI->addChannelSourceAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~LocalSource()
LocalSource::~LocalSource () virtual
Definition at line 74 of file localsource.cpp.
References m_channelizer, m_deviceAPI, m_networkManager, m_threadedChannelizer, networkManagerFinished(), DeviceAPI::removeChannelSource(), and DeviceAPI::removeChannelSourceAPI().
Referenced by LocalSource::MsgConfigureChannelizer::MsgConfigureChannelizer().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     m_deviceAPI->removeChannelSourceAPI(this);
     m_deviceAPI->removeChannelSource(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
 }
Member Function Documentation
applySettings()
void LocalSource::applySettings (const LocalSourceSettings & settings, bool force = false) private
Definition at line 354 of file localsource.cpp.
References getLocalDevice(), DeviceSampleSink::getSampleFifo(), LocalSourceSettings::m_localDeviceIndex, LocalSourceSettings::m_reverseAPIAddress, LocalSourceSettings::m_reverseAPIChannelIndex, LocalSourceSettings::m_reverseAPIDeviceIndex, LocalSourceSettings::m_reverseAPIPort, m_settings, m_sinkThread, LocalSourceSettings::m_useReverseAPI, propagateSampleRateAndFrequency(), LocalSourceThread::setSampleFifo(), and webapiReverseSendSettings().
Referenced by handleMessage().
 {
     qDebug() << "LocalSource::applySettings:"
             << " m_localDeviceIndex: " << settings.m_localDeviceIndex
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if ((settings.m_localDeviceIndex != m_settings.m_localDeviceIndex) || force)
     {
         reverseAPIKeys.append("localDeviceIndex");
         DeviceSampleSink *deviceSink = getLocalDevice(settings.m_localDeviceIndex);
         if (deviceSink)
         {
             if (m_sinkThread) {
                 m_sinkThread->setSampleFifo(deviceSink->getSampleFifo());
             }
             propagateSampleRateAndFrequency(settings.m_localDeviceIndex);
         }
         else
         {
             qWarning("LocalSource::applySettings: invalid local device for index %u", settings.m_localDeviceIndex);
         }
     }
     if ((settings.m_useReverseAPI) && (reverseAPIKeys.size() != 0))
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
calculateFrequencyOffset()
void LocalSource::calculateFrequencyOffset () private
Definition at line 405 of file localsource.cpp.
References HBFilterChainConverter::getShiftFactor(), m_deviceSampleRate, LocalSourceSettings::m_filterChainHash, m_frequencyOffset, LocalSourceSettings::m_log2Interp, and m_settings.
Referenced by handleMessage().
 {
     double shiftFactor = HBFilterChainConverter::getShiftFactor(m_settings.m_log2Interp, m_settings.m_filterChainHash);
     m_frequencyOffset = m_deviceSampleRate * shiftFactor;
 }
deserialize()
bool LocalSource::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 277 of file localsource.cpp.
References LocalSource::MsgConfigureLocalSource::create(), LocalSourceSettings::deserialize(), BasebandSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and LocalSourceSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     (void) data;
     if (m_settings.deserialize(data))
     {
         MsgConfigureLocalSource *msg = MsgConfigureLocalSource::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureLocalSource *msg = MsgConfigureLocalSource::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void LocalSource::destroy () inline virtual
Implements ChannelAPI.
Definition at line 108 of file localsource.h.
References handleMessage(), pull(), pullAudio(), start(), and stop().
 { delete this; }
getCenterFrequency()
virtual qint64 LocalSource::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 118 of file localsource.h.
References deserialize(), m_frequencyOffset, and serialize().
 { return m_frequencyOffset; }
getIdentifier()
virtual void LocalSource::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 116 of file localsource.h.
 { id = objectName(); }
getLocalDevice()
DeviceSampleSink * LocalSource::getLocalDevice (uint32_t index) private
Definition at line 311 of file localsource.cpp.
References ChannelAPI::getDeviceAPI(), DeviceSampleSink::getDeviceDescription(), DSPEngine::getDeviceSinkEngineByIndex(), DSPDeviceSinkEngine::getSink(), DSPDeviceSinkEngine::getUID(), and DSPEngine::instance().
Referenced by applySettings(), propagateSampleRateAndFrequency(), and start().
 {
     DSPEngine *dspEngine = DSPEngine::instance();
     if (index < dspEngine->getDeviceSinkEnginesNumber())
     {
         DSPDeviceSinkEngine *deviceSinkEngine = dspEngine->getDeviceSinkEngineByIndex(index);
         DeviceSampleSink *deviceSink = deviceSinkEngine->getSink();
         if (deviceSink->getDeviceDescription() == "LocalOutput")
         {
             if (!getDeviceAPI()) {
                 qDebug("LocalSource::getLocalDevice: the parent device is unset");
             } else if (getDeviceAPI()->getDeviceUID() == deviceSinkEngine->getUID()) {
                 qDebug("LocalSource::getLocalDevice: sink device at index %u is the parent device", index);
             } else {
                 return deviceSink;
             }
         }
         else
         {
             qDebug("LocalSource::getLocalDevice: sink device at index %u is not a Local Output source", index);
         }
     }
     else
     {
         qDebug("LocalSource::getLocalDevice: non existent sink device index: %u", index);
     }
     return nullptr;
 }
getLocalDevices()
void LocalSource::getLocalDevices (std::vector< uint32_t > & indexes)
Definition at line 295 of file localsource.cpp.
References DeviceSampleSink::getDeviceDescription(), DSPEngine::getDeviceSinkEngineByIndex(), DSPEngine::getDeviceSinkEnginesNumber(), DSPDeviceSinkEngine::getSink(), i, and DSPEngine::instance().
Referenced by setSampleRate(), and LocalSourceGUI::updateLocalDevices().
 {
     indexes.clear();
     DSPEngine *dspEngine = DSPEngine::instance();
     for (uint32_t i = 0; i < dspEngine->getDeviceSinkEnginesNumber(); i++)
     {
         DSPDeviceSinkEngine *deviceSinkEngine = dspEngine->getDeviceSinkEngineByIndex(i);
         DeviceSampleSink *deviceSink = deviceSinkEngine->getSink();
         if (deviceSink->getDeviceDescription() == "LocalOutput") {
             indexes.push_back(i);
         }
     }
 }
getNbSinkStreams()
virtual int LocalSource::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 123 of file localsource.h.
 { return 0; }
getNbSourceStreams()
virtual int LocalSource::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 124 of file localsource.h.
 { return 1; }
getStreamCenterFrequency()
virtual qint64 LocalSource::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 126 of file localsource.h.
References m_frequencyOffset, webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_frequencyOffset;
     }
getTitle()
virtual void LocalSource::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 117 of file localsource.h.
 { title = "Local Sink"; }
handleMessage()
bool LocalSource::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSource.
Definition at line 185 of file localsource.cpp.
References applySettings(), calculateFrequencyOffset(), LocalSource::MsgSampleRateNotification::create(), DSPSignalNotification::getCenterFrequency(), LocalSource::MsgConfigureChannelizer::getFilterChainHash(), LocalSource::MsgConfigureLocalSource::getForce(), UpChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSource::getInputMessageQueue(), LocalSource::MsgConfigureChannelizer::getLog2Interp(), UpChannelizer::MsgChannelizerNotification::getSampleRate(), DSPSignalNotification::getSampleRate(), LocalSource::MsgConfigureLocalSource::getSettings(), m_channelizer, m_chunkSize, m_deviceSampleRate, LocalSourceSettings::m_filterChainHash, BasebandSampleSource::m_guiMessageQueue, LocalSourceSettings::m_localDeviceIndex, m_localSamples, m_localSamplesIndex, m_localSamplesIndexOffset, m_localSampleSourceFifo, LocalSourceSettings::m_log2Interp, m_settings, m_settingsMutex, Message::match(), propagateSampleRateAndFrequency(), MessageQueue::push(), SampleSourceFifo::resize(), UpChannelizer::set(), setCenterFrequency(), and setSampleRate().
Referenced by destroy().
 {
     if (UpChannelizer::MsgChannelizerNotification::match(cmd))
     {
         UpChannelizer::MsgChannelizerNotification& notif = (UpChannelizer::MsgChannelizerNotification&) cmd;
         int sampleRate = notif.getSampleRate();
         qDebug() << "LocalSource::handleMessage: MsgChannelizerNotification:"
                 << " channelSampleRate: " << sampleRate
                 << " offsetFrequency: " << notif.getFrequencyOffset();
         if (sampleRate > 0)
         {
             if (m_localSampleSourceFifo)
             {
                 QMutexLocker mutexLocker(&m_settingsMutex);
                 m_localSampleSourceFifo->resize(sampleRate);
                 m_chunkSize = sampleRate / 8;
                 m_localSamplesIndex = 0;
                 m_localSamplesIndexOffset = 0;
                 m_localSamples.resize(2*m_chunkSize);
             }
             setSampleRate(sampleRate);
         }
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         DSPSignalNotification& notif = (DSPSignalNotification&) cmd;
         qDebug() << "LocalSource::handleMessage: DSPSignalNotification:"
                 << " inputSampleRate: " << notif.getSampleRate()
                 << " centerFrequency: " << notif.getCenterFrequency();
         setCenterFrequency(notif.getCenterFrequency());
         m_deviceSampleRate = notif.getSampleRate();
         calculateFrequencyOffset(); // This is when device sample rate changes
         propagateSampleRateAndFrequency(m_settings.m_localDeviceIndex);
         // Redo the channelizer stuff with the new sample rate to re-synchronize everything
         m_channelizer->set(m_channelizer->getInputMessageQueue(),
             m_settings.m_log2Interp,
             m_settings.m_filterChainHash);
         if (m_guiMessageQueue)
         {
             MsgSampleRateNotification *msg = MsgSampleRateNotification::create(notif.getSampleRate());
             m_guiMessageQueue->push(msg);
         }
         return true;
     }
     else if (MsgConfigureLocalSource::match(cmd))
     {
         MsgConfigureLocalSource& cfg = (MsgConfigureLocalSource&) cmd;
         qDebug() << "LocalSource::handleMessage: MsgConfigureLocalSink";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         m_settings.m_log2Interp = cfg.getLog2Interp();
         m_settings.m_filterChainHash =  cfg.getFilterChainHash();
         qDebug() << "LocalSource::handleMessage: MsgConfigureChannelizer:"
                 << " log2Interp: " << m_settings.m_log2Interp
                 << " filterChainHash: " << m_settings.m_filterChainHash;
         m_channelizer->set(m_channelizer->getInputMessageQueue(),
             m_settings.m_log2Interp,
             m_settings.m_filterChainHash);
         calculateFrequencyOffset(); // This is when decimation or filter chain changes
         propagateSampleRateAndFrequency(m_settings.m_localDeviceIndex);
         return true;
     }
     else
     {
         return false;
     }
 }
networkManagerFinished
void LocalSource::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 560 of file localsource.cpp.
Referenced by LocalSource(), and ~LocalSource().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "LocalSource::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("LocalSource::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
processSamples
void LocalSource::processSamples (int offset) private slot
Definition at line 114 of file localsource.cpp.
References m_chunkSize, m_localSamples, m_localSamplesIndexOffset, m_localSampleSourceFifo, and SampleSourceFifo::setIteratorFromOffset().
Referenced by start().
 {
     if (m_localSampleSourceFifo)
     {
         int destOffset = (m_localSamplesIndexOffset == 0 ? m_chunkSize : 0);
         SampleVector::iterator beginSource;
         SampleVector::iterator beginDestination = m_localSamples.begin() + destOffset;
         m_localSampleSourceFifo->setIteratorFromOffset(beginSource, offset);
         std::copy(beginSource, beginSource + m_chunkSize, beginDestination);
     }
 }
propagateSampleRateAndFrequency()
void LocalSource::propagateSampleRateAndFrequency (uint32_t index) private
Definition at line 343 of file localsource.cpp.
References getLocalDevice(), m_centerFrequency, m_deviceSampleRate, m_frequencyOffset, LocalSourceSettings::m_log2Interp, m_settings, DeviceSampleSink::setCenterFrequency(), and DeviceSampleSink::setSampleRate().
Referenced by applySettings(), and handleMessage().
 {
     DeviceSampleSink *deviceSink = getLocalDevice(index);
     if (deviceSink)
     {
         deviceSink->setSampleRate(m_deviceSampleRate / (1<<m_settings.m_log2Interp));
         deviceSink->setCenterFrequency(m_centerFrequency + m_frequencyOffset);
     }
 }
pull()
void LocalSource::pull (Sample & sample) virtual
Implements BasebandSampleSource.
Definition at line 84 of file localsource.cpp.
References m_chunkSize, m_localSamples, m_localSamplesIndex, m_localSamplesIndexOffset, m_localSampleSourceFifo, m_settingsMutex, and pullSamples().
Referenced by destroy().
 {
     if (m_localSampleSourceFifo)
     {
         QMutexLocker mutexLocker(&m_settingsMutex);
         sample = m_localSamples[m_localSamplesIndex + m_localSamplesIndexOffset];
         if (m_localSamplesIndex < m_chunkSize - 1)
         {
             m_localSamplesIndex++;
         }
         else
         {
             m_localSamplesIndex = 0;
             if (m_localSamplesIndexOffset == 0) {
                 m_localSamplesIndexOffset = m_chunkSize;
             } else {
                 m_localSamplesIndexOffset = 0;
             }
             emit pullSamples(m_chunkSize);
         }
     }
     else
     {
         sample = Sample{0, 0};
     }
 }
pullAudio()
void LocalSource::pullAudio (int nbSamples) virtual
Reimplemented from BasebandSampleSource.
Definition at line 126 of file localsource.cpp.
Referenced by destroy().
 {
     (void) nbSamples;
 }
pullSamples
void LocalSource::pullSamples (unsigned int count) signal
Referenced by pull(), and start().
serialize()
QByteArray LocalSource::serialize () const virtual
Implements ChannelAPI.
Definition at line 272 of file localsource.cpp.
References m_settings, and LocalSourceSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void LocalSource::setCenterFrequency (uint64_t centerFrequency) inline
Set center frequency given in Hz
Definition at line 144 of file localsource.h.
References m_centerFrequency.
Referenced by handleMessage().
 { m_centerFrequency = centerFrequency; }
setChannelizer()
void LocalSource::setChannelizer (unsigned int log2Interp, unsigned int filterChainHash)
Referenced by setSampleRate().
setSampleRate()
void LocalSource::setSampleRate (uint32_t sampleRate) inline
Set sample rate given in Hz
Definition at line 147 of file localsource.h.
References getLocalDevices(), m_sampleRate, and setChannelizer().
Referenced by handleMessage().
 { m_sampleRate = sampleRate; }
start()
void LocalSource::start () virtual
Implements BasebandSampleSource.
Definition at line 131 of file localsource.cpp.
References getLocalDevice(), DeviceSampleSink::getSampleFifo(), m_chunkSize, LocalSourceSettings::m_localDeviceIndex, m_localSamples, m_localSamplesIndex, m_localSampleSourceFifo, m_running, m_settings, m_sinkThread, processSamples(), pullSamples(), LocalSourceThread::setSampleFifo(), SampleSourceFifo::size(), LocalSourceThread::startStop(), and stop().
Referenced by destroy().
 {
     qDebug("LocalSource::start");
     if (m_running) {
         stop();
     }
     m_sinkThread = new LocalSourceThread();
     DeviceSampleSink *deviceSink = getLocalDevice(m_settings.m_localDeviceIndex);
     if (deviceSink)
     {
         m_localSampleSourceFifo = deviceSink->getSampleFifo();
         m_chunkSize = m_localSampleSourceFifo->size() / 16;
         m_localSamples.resize(2*m_chunkSize);
         m_localSamplesIndex = 0;
         m_sinkThread->setSampleFifo(m_localSampleSourceFifo);
     }
     else
     {
         m_localSampleSourceFifo = nullptr;
     }
     connect(this,
             SIGNAL(pullSamples(unsigned int)),
             m_sinkThread,
             SLOT(pullSamples(unsigned int)),
             Qt::QueuedConnection);
     connect(m_sinkThread,
             SIGNAL(samplesAvailable(int)),
             this,
             SLOT(processSamples(int)),
             Qt::QueuedConnection);
     m_sinkThread->startStop(true);
     m_running = true;
 }
stop()
void LocalSource::stop () virtual
Implements BasebandSampleSource.
Definition at line 171 of file localsource.cpp.
References m_running, m_sinkThread, and LocalSourceThread::startStop().
Referenced by destroy(), and start().
 {
     qDebug("LocalSource::stop");
     if (m_sinkThread != 0)
     {
         m_sinkThread->startStop(false);
         m_sinkThread->deleteLater();
         m_sinkThread = 0;
     }
     m_running = false;
 }
validateFilterChainHash()
void LocalSource::validateFilterChainHash (LocalSourceSettings & settings) private
Definition at line 394 of file localsource.cpp.
References i, LocalSourceSettings::m_filterChainHash, and LocalSourceSettings::m_log2Interp.
Referenced by webapiSettingsPutPatch().
 {
     unsigned int s = 1;
     for (unsigned int i = 0; i < settings.m_log2Interp; i++) {
         s *= 3;
     }
     settings.m_filterChainHash = settings.m_filterChainHash >= s ? s-1 : settings.m_filterChainHash;
 }
webapiFormatChannelSettings()
void LocalSource::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const LocalSourceSettings & settings) private
Definition at line 487 of file localsource.cpp.
References SWGSDRangel::SWGChannelSettings::getLocalSourceSettings(), SWGSDRangel::SWGLocalSourceSettings::getReverseApiAddress(), SWGSDRangel::SWGLocalSourceSettings::getTitle(), LocalSourceSettings::m_filterChainHash, LocalSourceSettings::m_localDeviceIndex, LocalSourceSettings::m_log2Interp, LocalSourceSettings::m_reverseAPIAddress, LocalSourceSettings::m_reverseAPIChannelIndex, LocalSourceSettings::m_reverseAPIDeviceIndex, LocalSourceSettings::m_reverseAPIPort, LocalSourceSettings::m_rgbColor, LocalSourceSettings::m_title, LocalSourceSettings::m_useReverseAPI, SWGSDRangel::SWGLocalSourceSettings::setFilterChainHash(), SWGSDRangel::SWGLocalSourceSettings::setLocalDeviceIndex(), SWGSDRangel::SWGLocalSourceSettings::setLog2Interp(), SWGSDRangel::SWGLocalSourceSettings::setReverseApiAddress(), SWGSDRangel::SWGLocalSourceSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGLocalSourceSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGLocalSourceSettings::setReverseApiPort(), SWGSDRangel::SWGLocalSourceSettings::setRgbColor(), SWGSDRangel::SWGLocalSourceSettings::setTitle(), and SWGSDRangel::SWGLocalSourceSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getLocalSourceSettings()->setLocalDeviceIndex(settings.m_localDeviceIndex);
     response.getLocalSourceSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getLocalSourceSettings()->getTitle()) {
         *response.getLocalSourceSettings()->getTitle() = settings.m_title;
     } else {
         response.getLocalSourceSettings()->setTitle(new QString(settings.m_title));
     }
     response.getLocalSourceSettings()->setLog2Interp(settings.m_log2Interp);
     response.getLocalSourceSettings()->setFilterChainHash(settings.m_filterChainHash);
     response.getLocalSourceSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getLocalSourceSettings()->getReverseApiAddress()) {
         *response.getLocalSourceSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getLocalSourceSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getLocalSourceSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getLocalSourceSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getLocalSourceSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReverseSendSettings()
void LocalSource::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const LocalSourceSettings & settings, bool force) private
Definition at line 513 of file localsource.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), SWGSDRangel::SWGChannelSettings::getLocalSourceSettings(), LocalSourceSettings::m_filterChainHash, LocalSourceSettings::m_localDeviceIndex, LocalSourceSettings::m_log2Interp, m_networkManager, m_networkRequest, LocalSourceSettings::m_reverseAPIAddress, LocalSourceSettings::m_reverseAPIChannelIndex, LocalSourceSettings::m_reverseAPIDeviceIndex, LocalSourceSettings::m_reverseAPIPort, LocalSourceSettings::m_rgbColor, LocalSourceSettings::m_title, SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGLocalSourceSettings::setFilterChainHash(), SWGSDRangel::SWGLocalSourceSettings::setLocalDeviceIndex(), SWGSDRangel::SWGChannelSettings::setLocalSourceSettings(), SWGSDRangel::SWGLocalSourceSettings::setLog2Interp(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGLocalSourceSettings::setRgbColor(), and SWGSDRangel::SWGLocalSourceSettings::setTitle().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("LocalSource"));
     swgChannelSettings->setLocalSourceSettings(new SWGSDRangel::SWGLocalSourceSettings());
     SWGSDRangel::SWGLocalSourceSettings *swgLocalSourceSettings = swgChannelSettings->getLocalSourceSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("localDeviceIndex") || force) {
         swgLocalSourceSettings->setLocalDeviceIndex(settings.m_localDeviceIndex);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgLocalSourceSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgLocalSourceSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("log2Interp") || force) {
         swgLocalSourceSettings->setLog2Interp(settings.m_log2Interp);
     }
     if (channelSettingsKeys.contains("filterChainHash") || force) {
         swgLocalSourceSettings->setFilterChainHash(settings.m_filterChainHash);
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int LocalSource::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 411 of file localsource.cpp.
References SWGSDRangel::SWGChannelSettings::getLocalSourceSettings(), SWGSDRangel::SWGLocalSourceSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setLocalSourceSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setLocalSourceSettings(new SWGSDRangel::SWGLocalSourceSettings());
     response.getLocalSourceSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int LocalSource::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 422 of file localsource.cpp.
References LocalSource::MsgConfigureLocalSource::create(), LocalSource::MsgConfigureChannelizer::create(), SWGSDRangel::SWGLocalSourceSettings::getFilterChainHash(), SWGSDRangel::SWGLocalSourceSettings::getLocalDeviceIndex(), SWGSDRangel::SWGChannelSettings::getLocalSourceSettings(), SWGSDRangel::SWGLocalSourceSettings::getLog2Interp(), SWGSDRangel::SWGLocalSourceSettings::getReverseApiAddress(), SWGSDRangel::SWGLocalSourceSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGLocalSourceSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGLocalSourceSettings::getReverseApiPort(), SWGSDRangel::SWGLocalSourceSettings::getRgbColor(), SWGSDRangel::SWGLocalSourceSettings::getTitle(), SWGSDRangel::SWGLocalSourceSettings::getUseReverseApi(), LocalSourceSettings::m_filterChainHash, BasebandSampleSource::m_guiMessageQueue, BasebandSampleSource::m_inputMessageQueue, LocalSourceSettings::m_localDeviceIndex, LocalSourceSettings::m_log2Interp, LocalSourceSettings::m_reverseAPIAddress, LocalSourceSettings::m_reverseAPIChannelIndex, LocalSourceSettings::m_reverseAPIDeviceIndex, LocalSourceSettings::m_reverseAPIPort, LocalSourceSettings::m_rgbColor, m_settings, LocalSourceSettings::m_title, LocalSourceSettings::m_useReverseAPI, MessageQueue::push(), validateFilterChainHash(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     LocalSourceSettings settings = m_settings;
     if (channelSettingsKeys.contains("localDeviceIndex")) {
         settings.m_localDeviceIndex = response.getLocalSourceSettings()->getLocalDeviceIndex();
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getLocalSourceSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getLocalSourceSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("log2Interp")) {
         settings.m_log2Interp = response.getLocalSourceSettings()->getLog2Interp();
     }
     if (channelSettingsKeys.contains("filterChainHash"))
     {
         settings.m_filterChainHash = response.getLocalSourceSettings()->getFilterChainHash();
         validateFilterChainHash(settings);
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getLocalSourceSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getLocalSourceSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getLocalSourceSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getLocalSourceSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getLocalSourceSettings()->getReverseApiChannelIndex();
     }
     MsgConfigureLocalSource *msg = MsgConfigureLocalSource::create(settings, force);
     m_inputMessageQueue.push(msg);
     if ((settings.m_log2Interp != m_settings.m_log2Interp) || (settings.m_filterChainHash != m_settings.m_filterChainHash) || force)
     {
         MsgConfigureChannelizer *msg = MsgConfigureChannelizer::create(settings.m_log2Interp, settings.m_filterChainHash);
         m_inputMessageQueue.push(msg);
     }
     qDebug("LocalSource::webapiSettingsPutPatch: forward to GUI: %p", m_guiMessageQueue);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureLocalSource *msgToGUI = MsgConfigureLocalSource::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_centerFrequency
uint64_t LocalSource::m_centerFrequency private
Definition at line 172 of file localsource.h.
Referenced by propagateSampleRateAndFrequency(), and setCenterFrequency().
m_channelId
const QString LocalSource::m_channelId = "LocalSource" static
Definition at line 153 of file localsource.h.
Referenced by LocalSourcePlugin::initPlugin(), and LocalSource().
m_channelIdURI
const QString LocalSource::m_channelIdURI = "sdrangel.channel.localsource" static
Definition at line 152 of file localsource.h.
Referenced by LocalSourcePlugin::initPlugin(), and LocalSourceGUI::LocalSourceGUI().
m_channelizer
UpChannelizer* LocalSource::m_channelizer private
Definition at line 161 of file localsource.h.
Referenced by handleMessage(), LocalSource(), and ~LocalSource().
m_chunkSize
int LocalSource::m_chunkSize private
Definition at line 167 of file localsource.h.
Referenced by handleMessage(), processSamples(), pull(), and start().
m_deviceAPI
DeviceAPI* LocalSource::m_deviceAPI private
Definition at line 159 of file localsource.h.
Referenced by LocalSource(), and ~LocalSource().
m_deviceSampleRate
uint32_t LocalSource::m_deviceSampleRate private
Definition at line 175 of file localsource.h.
Referenced by calculateFrequencyOffset(), handleMessage(), and propagateSampleRateAndFrequency().
m_frequencyOffset
int64_t LocalSource::m_frequencyOffset private
Definition at line 173 of file localsource.h.
Referenced by calculateFrequencyOffset(), getCenterFrequency(), getStreamCenterFrequency(), and propagateSampleRateAndFrequency().
m_localSamples
SampleVector LocalSource::m_localSamples private
Definition at line 168 of file localsource.h.
Referenced by handleMessage(), processSamples(), pull(), and start().
m_localSamplesIndex
int LocalSource::m_localSamplesIndex private
Definition at line 169 of file localsource.h.
Referenced by handleMessage(), pull(), and start().
m_localSamplesIndexOffset
int LocalSource::m_localSamplesIndexOffset private
Definition at line 170 of file localsource.h.
Referenced by handleMessage(), processSamples(), and pull().
m_localSampleSourceFifo
SampleSourceFifo* LocalSource::m_localSampleSourceFifo private
Definition at line 166 of file localsource.h.
Referenced by handleMessage(), processSamples(), pull(), and start().
m_networkManager
QNetworkAccessManager* LocalSource::m_networkManager private
Definition at line 177 of file localsource.h.
Referenced by LocalSource(), webapiReverseSendSettings(), and ~LocalSource().
m_networkRequest
QNetworkRequest LocalSource::m_networkRequest private
Definition at line 178 of file localsource.h.
Referenced by webapiReverseSendSettings().
m_running
bool LocalSource::m_running private
Definition at line 162 of file localsource.h.
Referenced by start(), and stop().
m_sampleRate
uint32_t LocalSource::m_sampleRate private
Definition at line 174 of file localsource.h.
Referenced by LocalSource::MsgSampleRateNotification::getSampleRate(), and setSampleRate().
m_settings
LocalSourceSettings LocalSource::m_settings private
Definition at line 164 of file localsource.h.
Referenced by applySettings(), calculateFrequencyOffset(), deserialize(), handleMessage(), propagateSampleRateAndFrequency(), serialize(), start(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex LocalSource::m_settingsMutex private
Definition at line 180 of file localsource.h.
Referenced by handleMessage(), and pull().
m_sinkThread
LocalSourceThread* LocalSource::m_sinkThread private
Definition at line 165 of file localsource.h.
Referenced by applySettings(), start(), and stop().
m_threadedChannelizer
ThreadedBasebandSampleSource* LocalSource::m_threadedChannelizer private
Definition at line 160 of file localsource.h.
Referenced by LocalSource(), and ~LocalSource().
The documentation for this class was generated from the following files:
plugins/channeltx/localsource/localsource.h
plugins/channeltx/localsource/localsource.cpp