SDRAngel: SWGSDRangel::SWGBladeRF2OutputReport Class Reference
SWGSDRangel::SWGBladeRF2OutputReport Class Reference
#include <SWGBladeRF2OutputReport.h>
Public Member Functions
SWGBladeRF2OutputReport ()
SWGBladeRF2OutputReport (QString *json)
virtual ~SWGBladeRF2OutputReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGBladeRF2OutputReport * fromJson (QString &jsonString) override
SWGFrequencyRange * getFrequencyRange ()
void setFrequencyRange (SWGFrequencyRange *frequency_range)
SWGRange * getSampleRateRange ()
void setSampleRateRange (SWGRange *sample_rate_range)
SWGRange * getBandwidthRange ()
void setBandwidthRange (SWGRange *bandwidth_range)
SWGRange * getGlobalGainRange ()
void setGlobalGainRange (SWGRange *global_gain_range)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
SWGFrequencyRange * frequency_range
bool m_frequency_range_isSet
SWGRange * sample_rate_range
bool m_sample_rate_range_isSet
SWGRange * bandwidth_range
bool m_bandwidth_range_isSet
SWGRange * global_gain_range
bool m_global_gain_range_isSet
Detailed Description
Definition at line 33 of file SWGBladeRF2OutputReport.h.
Constructor & Destructor Documentation
SWGBladeRF2OutputReport() [1/2]
SWGSDRangel::SWGBladeRF2OutputReport::SWGBladeRF2OutputReport ()
Definition at line 30 of file SWGBladeRF2OutputReport.cpp.
References bandwidth_range, frequency_range, global_gain_range, m_bandwidth_range_isSet, m_frequency_range_isSet, m_global_gain_range_isSet, m_sample_rate_range_isSet, and sample_rate_range.
{
     frequency_range = nullptr;
     m_frequency_range_isSet = false;
     sample_rate_range = nullptr;
     m_sample_rate_range_isSet = false;
     bandwidth_range = nullptr;
     m_bandwidth_range_isSet = false;
     global_gain_range = nullptr;
     m_global_gain_range_isSet = false;
 }
SWGBladeRF2OutputReport() [2/2]
SWGSDRangel::SWGBladeRF2OutputReport::SWGBladeRF2OutputReport (QString * json)
Definition at line 25 of file SWGBladeRF2OutputReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGBladeRF2OutputReport()
SWGSDRangel::SWGBladeRF2OutputReport::~SWGBladeRF2OutputReport () virtual
Definition at line 41 of file SWGBladeRF2OutputReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGBladeRF2OutputReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 95 of file SWGBladeRF2OutputReport.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGBladeRF2OutputReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 106 of file SWGBladeRF2OutputReport.cpp.
References bandwidth_range, frequency_range, global_gain_range, SWGSDRangel::SWGRange::isSet(), SWGSDRangel::SWGFrequencyRange::isSet(), sample_rate_range, and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if((frequency_range != nullptr) && (frequency_range->isSet())){
         toJsonValue(QString("frequencyRange"), frequency_range, obj, QString("SWGFrequencyRange"));
     }
     if((sample_rate_range != nullptr) && (sample_rate_range->isSet())){
         toJsonValue(QString("sampleRateRange"), sample_rate_range, obj, QString("SWGRange"));
     }
     if((bandwidth_range != nullptr) && (bandwidth_range->isSet())){
         toJsonValue(QString("bandwidthRange"), bandwidth_range, obj, QString("SWGRange"));
     }
     if((global_gain_range != nullptr) && (global_gain_range->isSet())){
         toJsonValue(QString("globalGainRange"), global_gain_range, obj, QString("SWGRange"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGBladeRF2OutputReport::cleanup ()
Definition at line 58 of file SWGBladeRF2OutputReport.cpp.
References bandwidth_range, frequency_range, global_gain_range, and sample_rate_range.
Referenced by ~SWGBladeRF2OutputReport().
{
     if(frequency_range != nullptr) {
         delete frequency_range;
     }
     if(sample_rate_range != nullptr) {
         delete sample_rate_range;
     }
     if(bandwidth_range != nullptr) {
         delete bandwidth_range;
     }
     if(global_gain_range != nullptr) {
         delete global_gain_range;
     }
 }
fromJson()
SWGBladeRF2OutputReport * SWGSDRangel::SWGBladeRF2OutputReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 74 of file SWGBladeRF2OutputReport.cpp.
References fromJsonObject().
Referenced by SWGBladeRF2OutputReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGBladeRF2OutputReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 83 of file SWGBladeRF2OutputReport.cpp.
References bandwidth_range, frequency_range, global_gain_range, sample_rate_range, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&frequency_range, pJson["frequencyRange"], "SWGFrequencyRange", "SWGFrequencyRange");
     ::SWGSDRangel::setValue(&sample_rate_range, pJson["sampleRateRange"], "SWGRange", "SWGRange");
     ::SWGSDRangel::setValue(&bandwidth_range, pJson["bandwidthRange"], "SWGRange", "SWGRange");
     ::SWGSDRangel::setValue(&global_gain_range, pJson["globalGainRange"], "SWGRange", "SWGRange");
 }
getBandwidthRange()
SWGRange * SWGSDRangel::SWGBladeRF2OutputReport::getBandwidthRange ()
Definition at line 145 of file SWGBladeRF2OutputReport.cpp.
References bandwidth_range.
Referenced by BladeRF2Output::webapiFormatDeviceReport().
{
     return bandwidth_range;
 }
getFrequencyRange()
SWGFrequencyRange * SWGSDRangel::SWGBladeRF2OutputReport::getFrequencyRange ()
Definition at line 125 of file SWGBladeRF2OutputReport.cpp.
References frequency_range.
Referenced by BladeRF2Output::webapiFormatDeviceReport().
{
     return frequency_range;
 }
getGlobalGainRange()
SWGRange * SWGSDRangel::SWGBladeRF2OutputReport::getGlobalGainRange ()
Definition at line 155 of file SWGBladeRF2OutputReport.cpp.
References global_gain_range.
Referenced by BladeRF2Output::webapiFormatDeviceReport().
{
     return global_gain_range;
 }
getSampleRateRange()
SWGRange * SWGSDRangel::SWGBladeRF2OutputReport::getSampleRateRange ()
Definition at line 135 of file SWGBladeRF2OutputReport.cpp.
References sample_rate_range.
Referenced by BladeRF2Output::webapiFormatDeviceReport().
{
     return sample_rate_range;
 }
init()
void SWGSDRangel::SWGBladeRF2OutputReport::init ()
Definition at line 46 of file SWGBladeRF2OutputReport.cpp.
References bandwidth_range, frequency_range, global_gain_range, m_bandwidth_range_isSet, m_frequency_range_isSet, m_global_gain_range_isSet, m_sample_rate_range_isSet, and sample_rate_range.
Referenced by SWGBladeRF2OutputReport(), and BladeRF2Output::webapiReportGet().
{
     frequency_range = new SWGFrequencyRange();
     m_frequency_range_isSet = false;
     sample_rate_range = new SWGRange();
     m_sample_rate_range_isSet = false;
     bandwidth_range = new SWGRange();
     m_bandwidth_range_isSet = false;
     global_gain_range = new SWGRange();
     m_global_gain_range_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGBladeRF2OutputReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 166 of file SWGBladeRF2OutputReport.cpp.
References bandwidth_range, frequency_range, global_gain_range, SWGSDRangel::SWGRange::isSet(), SWGSDRangel::SWGFrequencyRange::isSet(), and sample_rate_range.
Referenced by SWGSDRangel::SWGDeviceReport::asJsonObject(), and SWGSDRangel::SWGDeviceReport::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(frequency_range != nullptr && frequency_range->isSet()){ isObjectUpdated = true; break;}
         if(sample_rate_range != nullptr && sample_rate_range->isSet()){ isObjectUpdated = true; break;}
         if(bandwidth_range != nullptr && bandwidth_range->isSet()){ isObjectUpdated = true; break;}
         if(global_gain_range != nullptr && global_gain_range->isSet()){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setBandwidthRange()
void SWGSDRangel::SWGBladeRF2OutputReport::setBandwidthRange (SWGRange * bandwidth_range)
Definition at line 149 of file SWGBladeRF2OutputReport.cpp.
References bandwidth_range, and m_bandwidth_range_isSet.
Referenced by BladeRF2Output::webapiFormatDeviceReport().
{
     this->bandwidth_range = bandwidth_range;
     this->m_bandwidth_range_isSet = true;
 }
setFrequencyRange()
void SWGSDRangel::SWGBladeRF2OutputReport::setFrequencyRange (SWGFrequencyRange * frequency_range)
Definition at line 129 of file SWGBladeRF2OutputReport.cpp.
References frequency_range, and m_frequency_range_isSet.
Referenced by BladeRF2Output::webapiFormatDeviceReport().
{
     this->frequency_range = frequency_range;
     this->m_frequency_range_isSet = true;
 }
setGlobalGainRange()
void SWGSDRangel::SWGBladeRF2OutputReport::setGlobalGainRange (SWGRange * global_gain_range)
Definition at line 159 of file SWGBladeRF2OutputReport.cpp.
References global_gain_range, and m_global_gain_range_isSet.
Referenced by BladeRF2Output::webapiFormatDeviceReport().
{
     this->global_gain_range = global_gain_range;
     this->m_global_gain_range_isSet = true;
 }
setSampleRateRange()
void SWGSDRangel::SWGBladeRF2OutputReport::setSampleRateRange (SWGRange * sample_rate_range)
Definition at line 139 of file SWGBladeRF2OutputReport.cpp.
References m_sample_rate_range_isSet, and sample_rate_range.
Referenced by BladeRF2Output::webapiFormatDeviceReport().
{
     this->sample_rate_range = sample_rate_range;
     this->m_sample_rate_range_isSet = true;
 }
Member Data Documentation
bandwidth_range
SWGRange* SWGSDRangel::SWGBladeRF2OutputReport::bandwidth_range private
Definition at line 68 of file SWGBladeRF2OutputReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getBandwidthRange(), init(), isSet(), setBandwidthRange(), and SWGBladeRF2OutputReport().
frequency_range
SWGFrequencyRange* SWGSDRangel::SWGBladeRF2OutputReport::frequency_range private
Definition at line 62 of file SWGBladeRF2OutputReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFrequencyRange(), init(), isSet(), setFrequencyRange(), and SWGBladeRF2OutputReport().
global_gain_range
SWGRange* SWGSDRangel::SWGBladeRF2OutputReport::global_gain_range private
Definition at line 71 of file SWGBladeRF2OutputReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getGlobalGainRange(), init(), isSet(), setGlobalGainRange(), and SWGBladeRF2OutputReport().
m_bandwidth_range_isSet
bool SWGSDRangel::SWGBladeRF2OutputReport::m_bandwidth_range_isSet private
Definition at line 69 of file SWGBladeRF2OutputReport.h.
Referenced by init(), setBandwidthRange(), and SWGBladeRF2OutputReport().
m_frequency_range_isSet
bool SWGSDRangel::SWGBladeRF2OutputReport::m_frequency_range_isSet private
Definition at line 63 of file SWGBladeRF2OutputReport.h.
Referenced by init(), setFrequencyRange(), and SWGBladeRF2OutputReport().
m_global_gain_range_isSet
bool SWGSDRangel::SWGBladeRF2OutputReport::m_global_gain_range_isSet private
Definition at line 72 of file SWGBladeRF2OutputReport.h.
Referenced by init(), setGlobalGainRange(), and SWGBladeRF2OutputReport().
m_sample_rate_range_isSet
bool SWGSDRangel::SWGBladeRF2OutputReport::m_sample_rate_range_isSet private
Definition at line 66 of file SWGBladeRF2OutputReport.h.
Referenced by init(), setSampleRateRange(), and SWGBladeRF2OutputReport().
sample_rate_range
SWGRange* SWGSDRangel::SWGBladeRF2OutputReport::sample_rate_range private
Definition at line 65 of file SWGBladeRF2OutputReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSampleRateRange(), init(), isSet(), setSampleRateRange(), and SWGBladeRF2OutputReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGBladeRF2OutputReport.h
swagger/sdrangel/code/qt5/client/SWGBladeRF2OutputReport.cpp