SDRAngel: SamplingDeviceControl Class Reference
SamplingDeviceControl Class Reference
#include <samplingdevicecontrol.h>
Inherits QWidget.
Signals
void changed ()
Public Member Functions
SamplingDeviceControl (int tabIndex, int deviceType, QWidget *parent=0)
~SamplingDeviceControl ()
int getSelectedDeviceIndex () const
void setSelectedDeviceIndex (int index)
void removeSelectedDeviceIndex ()
void setPluginManager (PluginManager *pluginManager)
QComboBox * getChannelSelector ()
QPushButton * getAddChannelButton ()
Private Slots
void on_deviceChange_clicked ()
void on_deviceReload_clicked ()
Private Attributes
Ui::SamplingDeviceControl * ui
PluginManager * m_pluginManager
int m_deviceTabIndex
int m_deviceType
int m_selectedDeviceIndex
Detailed Description
Definition at line 35 of file samplingdevicecontrol.h.
Constructor & Destructor Documentation
SamplingDeviceControl()
SamplingDeviceControl::SamplingDeviceControl (int tabIndex, int deviceType, QWidget * parent = 0) explicit
Definition at line 25 of file samplingdevicecontrol.cpp.
References ui.
                                                                                           :
     QWidget(parent),
     ui(new Ui::SamplingDeviceControl),
     m_pluginManager(0),
     m_deviceTabIndex(tabIndex),
     m_deviceType(deviceType),
     m_selectedDeviceIndex(-1)
 {
     ui->setupUi(this);
     ui->deviceSelectedText->setText("None");
 }
~SamplingDeviceControl()
SamplingDeviceControl::~SamplingDeviceControl ()
Definition at line 37 of file samplingdevicecontrol.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
changed
void SamplingDeviceControl::changed () signal
Referenced by on_deviceChange_clicked(), and on_deviceReload_clicked().
getAddChannelButton()
QPushButton * SamplingDeviceControl::getAddChannelButton ()
Definition at line 107 of file samplingdevicecontrol.cpp.
References ui.
 {
     return ui->addChannel;
 }
getChannelSelector()
QComboBox * SamplingDeviceControl::getChannelSelector ()
Definition at line 102 of file samplingdevicecontrol.cpp.
References ui.
Referenced by MainWindow::channelAddClicked(), and MainWindow::handleMessage().
 {
     return ui->channelSelect;
 }
getSelectedDeviceIndex()
int SamplingDeviceControl::getSelectedDeviceIndex () const inline
Definition at line 42 of file samplingdevicecontrol.h.
Referenced by MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { return m_selectedDeviceIndex; }
on_deviceChange_clicked
void SamplingDeviceControl::on_deviceChange_clicked () private slot
Definition at line 42 of file samplingdevicecontrol.cpp.
References changed(), SamplingDeviceDialog::getSelectedDeviceIndex(), m_deviceTabIndex, m_deviceType, m_selectedDeviceIndex, and setSelectedDeviceIndex().
 {
     SamplingDeviceDialog dialog(m_deviceType, m_deviceTabIndex, this);
     dialog.exec();
     if (dialog.getSelectedDeviceIndex() >= 0)
     {
         m_selectedDeviceIndex = dialog.getSelectedDeviceIndex();
         setSelectedDeviceIndex(m_selectedDeviceIndex);
         emit changed();
     }
 }
on_deviceReload_clicked
void SamplingDeviceControl::on_deviceReload_clicked () private slot
Definition at line 55 of file samplingdevicecontrol.cpp.
References changed(), and m_selectedDeviceIndex.
 {
     if (m_selectedDeviceIndex >= 0) {
         emit changed();
     }
 }
removeSelectedDeviceIndex()
void SamplingDeviceControl::removeSelectedDeviceIndex ()
Definition at line 86 of file samplingdevicecontrol.cpp.
References DeviceEnumerator::instance(), m_deviceTabIndex, m_deviceType, m_selectedDeviceIndex, DeviceEnumerator::removeRxSelection(), DeviceEnumerator::removeTxSelection(), and ui.
 {
     if (m_deviceType == 0) // Single Rx
     {
         DeviceEnumerator::instance()->removeRxSelection(m_deviceTabIndex);
         ui->deviceSelectedText->setText("None");
     }
     else if (m_deviceType == 1) // Single Tx
     {
         DeviceEnumerator::instance()->removeTxSelection(m_deviceTabIndex);
         ui->deviceSelectedText->setText("None");
     }
     m_selectedDeviceIndex = -1;
 }
setPluginManager()
void SamplingDeviceControl::setPluginManager (PluginManager * pluginManager) inline
Definition at line 46 of file samplingdevicecontrol.h.
 { m_pluginManager = pluginManager; }
setSelectedDeviceIndex()
void SamplingDeviceControl::setSelectedDeviceIndex (int index)
Definition at line 62 of file samplingdevicecontrol.cpp.
References DeviceEnumerator::changeMIMOSelection(), DeviceEnumerator::changeRxSelection(), DeviceEnumerator::changeTxSelection(), PluginInterface::SamplingDevice::displayedName, DeviceEnumerator::getMIMOSamplingDevice(), DeviceEnumerator::getRxSamplingDevice(), DeviceEnumerator::getTxSamplingDevice(), DeviceEnumerator::instance(), m_deviceTabIndex, m_deviceType, m_selectedDeviceIndex, and ui.
Referenced by MainWindow::handleMessage(), and on_deviceChange_clicked().
 {
     if (m_deviceType == 0) // Single Rx
     {
         const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getRxSamplingDevice(index);
         DeviceEnumerator::instance()->changeRxSelection(m_deviceTabIndex, index);
         ui->deviceSelectedText->setText(samplingDevice->displayedName);
     }
     else if (m_deviceType == 1) // Single Tx
     {
         const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getTxSamplingDevice(index);
         DeviceEnumerator::instance()->changeTxSelection(m_deviceTabIndex, index);
         ui->deviceSelectedText->setText(samplingDevice->displayedName);
     }
     else if (m_deviceType == 2) // MIMO
     {
         const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getMIMOSamplingDevice(index);
         DeviceEnumerator::instance()->changeMIMOSelection(m_deviceTabIndex, index);
         ui->deviceSelectedText->setText(samplingDevice->displayedName);
     }
     m_selectedDeviceIndex = index;
 }
Member Data Documentation
m_deviceTabIndex
int SamplingDeviceControl::m_deviceTabIndex private
Definition at line 57 of file samplingdevicecontrol.h.
Referenced by on_deviceChange_clicked(), removeSelectedDeviceIndex(), and setSelectedDeviceIndex().
m_deviceType
int SamplingDeviceControl::m_deviceType private
Definition at line 58 of file samplingdevicecontrol.h.
Referenced by on_deviceChange_clicked(), removeSelectedDeviceIndex(), and setSelectedDeviceIndex().
m_pluginManager
PluginManager* SamplingDeviceControl::m_pluginManager private
Definition at line 56 of file samplingdevicecontrol.h.
m_selectedDeviceIndex
int SamplingDeviceControl::m_selectedDeviceIndex private
Definition at line 59 of file samplingdevicecontrol.h.
Referenced by on_deviceChange_clicked(), on_deviceReload_clicked(), removeSelectedDeviceIndex(), and setSelectedDeviceIndex().
ui
Ui::SamplingDeviceControl* SamplingDeviceControl::ui private
Definition at line 55 of file samplingdevicecontrol.h.
Referenced by getAddChannelButton(), getChannelSelector(), removeSelectedDeviceIndex(), SamplingDeviceControl(), setSelectedDeviceIndex(), and ~SamplingDeviceControl().
The documentation for this class was generated from the following files:
sdrgui/gui/samplingdevicecontrol.h
sdrgui/gui/samplingdevicecontrol.cpp