SDRAngel: TransverterButton Class Reference
TransverterButton Class Reference
#include <transverterbutton.h>
Inherits QPushButton.
Public Member Functions
TransverterButton (QWidget *parent=0)
qint64 getDeltaFrequency () const
bool getDeltaFrequencyAcive () const
void setDeltaFrequency (qint64 deltaFrequency)
void setDeltaFrequencyActive (bool active)
Private Slots
void onClicked ()
Private Member Functions
void updateState ()
Private Attributes
qint64 m_deltaFrequency
bool m_deltaFrequencyActive
Detailed Description
Definition at line 29 of file transverterbutton.h.
Constructor & Destructor Documentation
TransverterButton()
TransverterButton::TransverterButton (QWidget * parent = 0)
Definition at line 25 of file transverterbutton.cpp.
References onClicked().
                                                     :
     QPushButton(parent),
     m_deltaFrequency(0),
     m_deltaFrequencyActive(false)
 {
     setObjectName("TransverterButton");
     connect(this, SIGNAL(clicked()), this, SLOT(onClicked()));
 }
Member Function Documentation
getDeltaFrequency()
qint64 TransverterButton::getDeltaFrequency () const inline
Definition at line 34 of file transverterbutton.h.
 { return m_deltaFrequency; }
getDeltaFrequencyAcive()
bool TransverterButton::getDeltaFrequencyAcive () const inline
Definition at line 35 of file transverterbutton.h.
 { return m_deltaFrequencyActive; }
onClicked
void TransverterButton::onClicked () private slot
Definition at line 34 of file transverterbutton.cpp.
References m_deltaFrequency, m_deltaFrequencyActive, and updateState().
Referenced by TransverterButton().
 {
     TransverterDialog transverterDialog(m_deltaFrequency, m_deltaFrequencyActive, this);
     transverterDialog.exec();
     updateState();
 }
setDeltaFrequency()
void TransverterButton::setDeltaFrequency (qint64 deltaFrequency) inline
Definition at line 37 of file transverterbutton.h.
     {
         m_deltaFrequency = deltaFrequency;
         updateState();
     }
setDeltaFrequencyActive()
void TransverterButton::setDeltaFrequencyActive (bool active) inline
Definition at line 43 of file transverterbutton.h.
     {
         m_deltaFrequencyActive = active;
         updateState();
     }
updateState()
void TransverterButton::updateState () private
Definition at line 41 of file transverterbutton.cpp.
References arg(), m_deltaFrequency, and m_deltaFrequencyActive.
Referenced by onClicked().
 {
     setToolTip(tr("Transverter frequency translation dialog. Delta frequency %1 MHz %2")
             .arg(m_deltaFrequency/1000000.0)
             .arg(m_deltaFrequencyActive ? "enabled" : "disabled"));
     if(m_deltaFrequencyActive)
     {
         setStyleSheet("TransverterButton { background:rgb(128, 70, 0); }");
     }
     else
     {
         setStyleSheet("TransverterButton { background:rgb(48, 48, 48); }");
     }
 }
Member Data Documentation
m_deltaFrequency
qint64 TransverterButton::m_deltaFrequency private
Definition at line 53 of file transverterbutton.h.
Referenced by onClicked(), and updateState().
m_deltaFrequencyActive
bool TransverterButton::m_deltaFrequencyActive private
Definition at line 54 of file transverterbutton.h.
Referenced by onClicked(), and updateState().
The documentation for this class was generated from the following files:
sdrgui/gui/transverterbutton.h
sdrgui/gui/transverterbutton.cpp