SDRAngel: WebAPIAdapterBase Class Reference
WebAPIAdapterBase Class Reference
#include <webapiadapterbase.h>
Static Public Member Functions
static void webapiFormatPreferences (SWGSDRangel::SWGPreferences *apiPreferences, const Preferences &preferences)
static void webapiFormatPreset (SWGSDRangel::SWGPreset *apiPreset, const Preset &preset)
Detailed Description
Adapter between API and objects in sdrbase library
Definition at line 31 of file webapiadapterbase.h.
Member Function Documentation
webapiFormatPreferences()
void WebAPIAdapterBase::webapiFormatPreferences (SWGSDRangel::SWGPreferences * apiPreferences, const Preferences & preferences) static
Definition at line 21 of file webapiadapterbase.cpp.
References SWGSDRangel::SWGPreferences::init(), Preferences::m_audioDevice, Preferences::m_audioType, Preferences::m_consoleMinLogLevel, Preferences::m_fileMinLogLevel, Preferences::m_latitude, Preferences::m_logFileName, Preferences::m_longitude, Preferences::m_sourceDevice, Preferences::m_sourceIndex, Preferences::m_useLogFile, SWGSDRangel::SWGPreferences::setAudioDevice(), SWGSDRangel::SWGPreferences::setAudioType(), SWGSDRangel::SWGPreferences::setConsoleMinLogLevel(), SWGSDRangel::SWGPreferences::setFileMinLogLevel(), SWGSDRangel::SWGPreferences::setLatitude(), SWGSDRangel::SWGPreferences::setLogFileName(), SWGSDRangel::SWGPreferences::setLongitude(), SWGSDRangel::SWGPreferences::setSourceDevice(), SWGSDRangel::SWGPreferences::setSourceIndex(), and SWGSDRangel::SWGPreferences::setUseLogFile().
Referenced by WebAPIAdapterGUI::instanceConfigGet(), and WebAPIAdapterSrv::instanceConfigGet().
 {
     apiPreferences->init();
     apiPreferences->setSourceDevice(new QString(preferences.m_sourceDevice));
     apiPreferences->setSourceIndex(preferences.m_sourceIndex);
     apiPreferences->setAudioType(new QString(preferences.m_audioType));
     apiPreferences->setAudioDevice(new QString(preferences.m_audioDevice));
     apiPreferences->setLatitude(preferences.m_latitude);
     apiPreferences->setLongitude(preferences.m_longitude);
     apiPreferences->setConsoleMinLogLevel((int) preferences.m_consoleMinLogLevel);
     apiPreferences->setUseLogFile(preferences.m_useLogFile ? 1 : 0);
     apiPreferences->setLogFileName(new QString(preferences.m_logFileName));
     apiPreferences->setFileMinLogLevel((int) preferences.m_fileMinLogLevel);
 }
webapiFormatPreset()
void WebAPIAdapterBase::webapiFormatPreset (SWGSDRangel::SWGPreset * apiPreset, const Preset & preset) static
Definition at line 39 of file webapiadapterbase.cpp.
References SWGSDRangel::SWGPreset::getMSpectrumConfig(), SWGSDRangel::SWGGLSpectrum::init(), SWGSDRangel::SWGPreset::init(), Preset::m_centerFrequency, Preset::m_dcOffsetCorrection, Preset::m_description, Preset::m_group, Preset::m_iqImbalanceCorrection, Preset::m_sourcePreset, SWGSDRangel::SWGPreset::setCenterFrequency(), SWGSDRangel::SWGPreset::setDcOffsetCorrection(), SWGSDRangel::SWGPreset::setDescription(), SWGSDRangel::SWGPreset::setGroup(), SWGSDRangel::SWGPreset::setIqImbalanceCorrection(), and SWGSDRangel::SWGPreset::setSourcePreset().
Referenced by WebAPIAdapterGUI::instanceConfigGet(), and WebAPIAdapterSrv::instanceConfigGet().
 {
     apiPreset->init();
     apiPreset->setSourcePreset(preset.m_sourcePreset ? 1 : 0);
     apiPreset->setGroup(new QString(preset.m_group));
     apiPreset->setDescription(new QString(preset.m_description));
     apiPreset->setCenterFrequency(preset.m_centerFrequency);
     apiPreset->getMSpectrumConfig()->init(); // TODO when spectrum config is extracted to sdrbase
     apiPreset->setDcOffsetCorrection(preset.m_dcOffsetCorrection ? 1 : 0);
     apiPreset->setIqImbalanceCorrection(preset.m_iqImbalanceCorrection ? 1 : 0);
     // TODO: channel configs
     // TODO: device configs
 }
The documentation for this class was generated from the following files:
sdrbase/webapi/webapiadapterbase.h
sdrbase/webapi/webapiadapterbase.cpp