SDRAngel: qrtplib::RTPInternalSourceData Class Reference
qrtplib::RTPInternalSourceData Class Reference
#include <rtpinternalsourcedata.h>
Public Member Functions
RTPInternalSourceData (uint32_t ssrc)
~RTPInternalSourceData ()
int ProcessRTPPacket (RTPPacket *rtppack, const RTPTime &receivetime, bool *stored, RTPSources *sources)
void ProcessSenderInfo (const RTPNTPTime &ntptime, uint32_t rtptime, uint32_t packetcount, uint32_t octetcount, const RTPTime &receivetime)
void ProcessReportBlock (uint8_t fractionlost, int32_t lostpackets, uint32_t exthighseqnr, uint32_t jitter, uint32_t lsr, uint32_t dlsr, const RTPTime &receivetime)
void UpdateMessageTime (const RTPTime &receivetime)
int ProcessSDESItem (uint8_t sdesid, const uint8_t *data, std::size_t itemlen, const RTPTime &receivetime, bool *cnamecollis)
int ProcessPrivateSDESItem (const uint8_t *prefix, std::size_t prefixlen, const uint8_t *value, std::size_t valuelen, const RTPTime &receivetime)
int ProcessBYEPacket (const uint8_t *reason, std::size_t reasonlen, const RTPTime &receivetime)
int SetRTPDataAddress (const RTPAddress *a)
int SetRTCPDataAddress (const RTPAddress *a)
void ClearSenderFlag ()
void SentRTPPacket ()
void SetOwnSSRC ()
void SetCSRC ()
void ClearNote ()
Public Member Functions inherited from qrtplib::RTPSourceData
RTPPacket * GetNextPacket ()
void FlushPackets ()
bool HasData () const
uint32_t GetSSRC () const
bool IsOwnSSRC () const
bool IsCSRC () const
bool IsSender () const
bool IsValidated () const
bool IsActive () const
void SetProcessedInRTCP (bool v)
bool IsProcessedInRTCP () const
bool IsRTPAddressSet () const
bool IsRTCPAddressSet () const
const RTPAddress * GetRTPDataAddress () const
const RTPAddress * GetRTCPDataAddress () const
bool ReceivedBYE () const
uint8_t * GetBYEReason (std::size_t *len) const
RTPTime GetBYETime () const
void SetTimestampUnit (double tsu)
double GetTimestampUnit () const
bool SR_HasInfo () const
RTPNTPTime SR_GetNTPTimestamp () const
uint32_t SR_GetRTPTimestamp () const
uint32_t SR_GetPacketCount () const
uint32_t SR_GetByteCount () const
RTPTime SR_GetReceiveTime () const
bool SR_Prev_HasInfo () const
RTPNTPTime SR_Prev_GetNTPTimestamp () const
uint32_t SR_Prev_GetRTPTimestamp () const
uint32_t SR_Prev_GetPacketCount () const
uint32_t SR_Prev_GetByteCount () const
RTPTime SR_Prev_GetReceiveTime () const
bool RR_HasInfo () const
double RR_GetFractionLost () const
int32_t RR_GetPacketsLost () const
uint32_t RR_GetExtendedHighestSequenceNumber () const
uint32_t RR_GetJitter () const
uint32_t RR_GetLastSRTimestamp () const
uint32_t RR_GetDelaySinceLastSR () const
RTPTime RR_GetReceiveTime () const
bool RR_Prev_HasInfo () const
double RR_Prev_GetFractionLost () const
int32_t RR_Prev_GetPacketsLost () const
uint32_t RR_Prev_GetExtendedHighestSequenceNumber () const
uint32_t RR_Prev_GetJitter () const
uint32_t RR_Prev_GetLastSRTimestamp () const
uint32_t RR_Prev_GetDelaySinceLastSR () const
RTPTime RR_Prev_GetReceiveTime () const
bool INF_HasSentData () const
int32_t INF_GetNumPacketsReceived () const
uint32_t INF_GetBaseSequenceNumber () const
uint32_t INF_GetExtendedHighestSequenceNumber () const
uint32_t INF_GetJitter () const
RTPTime INF_GetLastMessageTime () const
RTPTime INF_GetLastRTPPacketTime () const
double INF_GetEstimatedTimestampUnit () const
uint32_t INF_GetNumPacketsReceivedInInterval () const
uint32_t INF_GetSavedExtendedSequenceNumber () const
void INF_StartNewInterval ()
RTPTime INF_GetRoundtripTime () const
RTPTime INF_GetLastSDESNoteTime () const
uint8_t * SDES_GetCNAME (std::size_t *len) const
uint8_t * SDES_GetName (std::size_t *len) const
uint8_t * SDES_GetEMail (std::size_t *len) const
uint8_t * SDES_GetPhone (std::size_t *len) const
uint8_t * SDES_GetLocation (std::size_t *len) const
uint8_t * SDES_GetTool (std::size_t *len) const
uint8_t * SDES_GetNote (std::size_t *len) const
void SDES_GotoFirstPrivateValue ()
bool SDES_GetNextPrivateValue (uint8_t **prefix, std::size_t *prefixlen, uint8_t **value, std::size_t *valuelen)
bool SDES_GetPrivateValue (uint8_t *prefix, std::size_t prefixlen, uint8_t **value, std::size_t *valuelen) const
Additional Inherited Members
Protected Member Functions inherited from qrtplib::RTPSourceData
RTPSourceData (uint32_t ssrc)
virtual ~RTPSourceData ()
Protected Attributes inherited from qrtplib::RTPSourceData
std::list< RTPPacket * > packetlist
uint32_t ssrc
bool ownssrc
bool iscsrc
double timestampunit
bool receivedbye
bool validated
bool processedinrtcp
bool issender
RTCPSenderReportInfo SRinf
RTCPSenderReportInfo SRprevinf
RTCPReceiverReportInfo RRinf
RTCPReceiverReportInfo RRprevinf
RTPSourceStats stats
RTCPSDESInfo SDESinf
bool isrtpaddrset
bool isrtcpaddrset
RTPAddress * rtpaddr
RTPAddress * rtcpaddr
RTPTime byetime
uint8_t * byereason
std::size_t byereasonlen
Detailed Description
Definition at line 52 of file rtpinternalsourcedata.h.
Constructor & Destructor Documentation
RTPInternalSourceData()
qrtplib::RTPInternalSourceData::RTPInternalSourceData (uint32_t ssrc)
Definition at line 42 of file rtpinternalsourcedata.cpp.
                                                           :
         RTPSourceData(ssrc)
 {
 }
~RTPInternalSourceData()
qrtplib::RTPInternalSourceData::~RTPInternalSourceData ()
Definition at line 47 of file rtpinternalsourcedata.cpp.
 {
 }
Member Function Documentation
ClearNote()
void qrtplib::RTPInternalSourceData::ClearNote () inline
Definition at line 107 of file rtpinternalsourcedata.h.
Referenced by qrtplib::RTPSources::MultipleTimeouts(), and qrtplib::RTPSources::NoteTimeout().
     {
         SDESinf.SetNote(0, 0);
     }
ClearSenderFlag()
void qrtplib::RTPInternalSourceData::ClearSenderFlag () inline
Definition at line 84 of file rtpinternalsourcedata.h.
Referenced by qrtplib::RTPSources::MultipleTimeouts(), and qrtplib::RTPSources::SenderTimeout().
     {
         issender = false;
     }
ProcessBYEPacket()
int qrtplib::RTPInternalSourceData::ProcessBYEPacket (const uint8_t * reason, std::size_t reasonlen, const RTPTime & receivetime)
Definition at line 236 of file rtpinternalsourcedata.cpp.
References qrtplib::RTPSourceData::byereason, qrtplib::RTPSourceData::byereasonlen, qrtplib::RTPSourceData::byetime, qrtplib::RTPSourceData::receivedbye, qrtplib::RTPSourceStats::SetLastMessageTime(), and qrtplib::RTPSourceData::stats.
Referenced by qrtplib::RTPSources::ProcessBYE().
 {
     if (byereason)
     {
         delete[] byereason;
         byereason = 0;
         byereasonlen = 0;
     }
     byetime = receivetime;
     byereason = new uint8_t[reasonlen];
     memcpy(byereason, reason, reasonlen);
     byereasonlen = reasonlen;
     receivedbye = true;
     stats.SetLastMessageTime(receivetime);
     return 0;
 }
ProcessPrivateSDESItem()
int qrtplib::RTPInternalSourceData::ProcessPrivateSDESItem (const uint8_t * prefix, std::size_t prefixlen, const uint8_t * value, std::size_t valuelen, const RTPTime & receivetime)
Definition at line 223 of file rtpinternalsourcedata.cpp.
References ERR_RTP_SDES_MAXPRIVITEMS, qrtplib::RTPSourceData::SDESinf, qrtplib::RTPSourceStats::SetLastMessageTime(), qrtplib::RTCPSDESInfo::SetPrivateValue(), and qrtplib::RTPSourceData::stats.
Referenced by qrtplib::RTPSources::ProcessSDESPrivateItem().
 {
     int status;
     stats.SetLastMessageTime(receivetime);
     status = SDESinf.SetPrivateValue(prefix, prefixlen, value, valuelen);
     if (status == ERR_RTP_SDES_MAXPRIVITEMS)
         return 0; // don't stop processing just because the number of items is full
     return status;
 }
ProcessReportBlock()
void qrtplib::RTPInternalSourceData::ProcessReportBlock (uint8_t fractionlost, int32_t lostpackets, uint32_t exthighseqnr, uint32_t jitter, uint32_t lsr, uint32_t dlsr, const RTPTime & receivetime) inline
Definition at line 65 of file rtpinternalsourcedata.h.
Referenced by qrtplib::RTPSources::ProcessRTCPReportBlock().
     {
         RRprevinf = RRinf;
         RRinf.Set(fractionlost, lostpackets, exthighseqnr, jitter, lsr, dlsr, receivetime);
         stats.SetLastMessageTime(receivetime);
     }
ProcessRTPPacket()
int qrtplib::RTPInternalSourceData::ProcessRTPPacket (RTPPacket * rtppack, const RTPTime & receivetime, bool * stored, RTPSources * sources)
Definition at line 52 of file rtpinternalsourcedata.cpp.
References qrtplib::RTPPacket::GetExtendedSequenceNumber(), qrtplib::RTPSourceData::INF_GetEstimatedTimestampUnit(), qrtplib::RTPSourceData::issender, qrtplib::RTPSources::OnValidatedRTPPacket(), qrtplib::RTPSourceData::ownssrc, qrtplib::RTPSourceData::packetlist, qrtplib::RTPSourceStats::ProcessPacket(), RTPINTERNALSOURCEDATA_MAXPROBATIONPACKETS, qrtplib::RTPSourceData::stats, qrtplib::RTPSourceData::timestampunit, and qrtplib::RTPSourceData::validated.
Referenced by qrtplib::RTPSources::ProcessRTPPacket().
 {
     bool accept;
     double tsunit;
     *stored = false;
     if (timestampunit < 0)
         tsunit = INF_GetEstimatedTimestampUnit();
     else
         tsunit = timestampunit;
     stats.ProcessPacket(rtppack, receivetime, tsunit, ownssrc, &accept);
     if (!accept)
         return 0;
     validated = true;
     if (validated && !ownssrc) // for own ssrc these variables depend on the outgoing packets, not on the incoming
         issender = true;
     bool isonprobation = !validated;
     bool ispackethandled = false;
     sources->OnValidatedRTPPacket(this, rtppack, isonprobation, &ispackethandled);
     if (ispackethandled) // Packet is already handled in the callback, no need to store it in the list
     {
         // Set 'stored' to true to avoid the packet being deallocated
         *stored = true;
         return 0;
     }
     // Now, we can place the packet in the queue
     if (packetlist.empty())
     {
         *stored = true;
         packetlist.push_back(rtppack);
         return 0;
     }
     if (!validated) // still on probation
     {
         // Make sure that we don't buffer too much packets to avoid wasting memory
         // on a bad source. Delete the packet in the queue with the lowest sequence
         // number.
         if (packetlist.size() == RTPINTERNALSOURCEDATA_MAXPROBATIONPACKETS)
         {
             RTPPacket *p = *(packetlist.begin());
             packetlist.pop_front();
             delete p;
         }
     }
     // find the right position to insert the packet
     std::list<RTPPacket*>::iterator it, start;
     bool done = false;
     uint32_t newseqnr = rtppack->GetExtendedSequenceNumber();
     it = packetlist.end();
     --it;
     start = packetlist.begin();
     while (!done)
     {
         RTPPacket *p;
         uint32_t seqnr;
         p = *it;
         seqnr = p->GetExtendedSequenceNumber();
         if (seqnr > newseqnr)
         {
             if (it != start)
                 --it;
             else // we're at the start of the list
             {
                 *stored = true;
                 done = true;
                 packetlist.push_front(rtppack);
             }
         }
         else if (seqnr < newseqnr) // insert after this packet
         {
             ++it;
             packetlist.insert(it, rtppack);
             done = true;
             *stored = true;
         }
         else // they're equal !! Drop packet
         {
             done = true;
         }
     }
     return 0;
 }
ProcessSDESItem()
int qrtplib::RTPInternalSourceData::ProcessSDESItem (uint8_t sdesid, const uint8_t * data, std::size_t itemlen, const RTPTime & receivetime, bool * cnamecollis)
Definition at line 150 of file rtpinternalsourcedata.cpp.
References qrtplib::RTCPSDESInfo::GetCNAME(), qrtplib::RTCPSDESInfo::GetEMail(), qrtplib::RTCPSDESInfo::GetName(), qrtplib::RTCPSDESInfo::GetTool(), RTCP_SDES_ID_CNAME, RTCP_SDES_ID_EMAIL, RTCP_SDES_ID_LOCATION, RTCP_SDES_ID_NAME, RTCP_SDES_ID_NOTE, RTCP_SDES_ID_PHONE, RTCP_SDES_ID_TOOL, qrtplib::RTPSourceData::SDESinf, qrtplib::RTCPSDESInfo::SetCNAME(), qrtplib::RTCPSDESInfo::SetEMail(), qrtplib::RTPSourceStats::SetLastMessageTime(), qrtplib::RTPSourceStats::SetLastNoteTime(), qrtplib::RTCPSDESInfo::SetLocation(), qrtplib::RTCPSDESInfo::SetName(), qrtplib::RTCPSDESInfo::SetNote(), qrtplib::RTCPSDESInfo::SetPhone(), qrtplib::RTCPSDESInfo::SetTool(), qrtplib::RTPSourceData::stats, and qrtplib::RTPSourceData::validated.
Referenced by qrtplib::RTPSources::ProcessSDESNormalItem().
 {
     *cnamecollis = false;
     stats.SetLastMessageTime(receivetime);
     switch (sdesid)
     {
     case RTCP_SDES_ID_CNAME:
     {
         std::size_t curlen;
         uint8_t *oldcname;
         // NOTE: we're going to make sure that the CNAME is only set once.
         oldcname = SDESinf.GetCNAME(&curlen);
         if (curlen == 0)
         {
             // if CNAME is set, the source is validated
             SDESinf.SetCNAME(data, itemlen);
             validated = true;
         }
         else // check if this CNAME is equal to the one that is already present
         {
             if (curlen != itemlen)
                 *cnamecollis = true;
             else
             {
                 if (memcmp(data, oldcname, itemlen) != 0)
                     *cnamecollis = true;
             }
         }
     }
         break;
     case RTCP_SDES_ID_NAME:
     {
         std::size_t oldlen;
         SDESinf.GetName(&oldlen);
         if (oldlen == 0) // Name not set
             return SDESinf.SetName(data, itemlen);
     }
         break;
     case RTCP_SDES_ID_EMAIL:
     {
         std::size_t oldlen;
         SDESinf.GetEMail(&oldlen);
         if (oldlen == 0)
             return SDESinf.SetEMail(data, itemlen);
     }
         break;
     case RTCP_SDES_ID_PHONE:
         return SDESinf.SetPhone(data, itemlen);
     case RTCP_SDES_ID_LOCATION:
         return SDESinf.SetLocation(data, itemlen);
     case RTCP_SDES_ID_TOOL:
     {
         std::size_t oldlen;
         SDESinf.GetTool(&oldlen);
         if (oldlen == 0)
             return SDESinf.SetTool(data, itemlen);
     }
         break;
     case RTCP_SDES_ID_NOTE:
         stats.SetLastNoteTime(receivetime);
         return SDESinf.SetNote(data, itemlen);
     }
     return 0;
 }
ProcessSenderInfo()
void qrtplib::RTPInternalSourceData::ProcessSenderInfo (const RTPNTPTime & ntptime, uint32_t rtptime, uint32_t packetcount, uint32_t octetcount, const RTPTime & receivetime) inline
Definition at line 59 of file rtpinternalsourcedata.h.
Referenced by qrtplib::RTPSources::ProcessRTCPSenderInfo().
     {
         SRprevinf = SRinf;
         SRinf.Set(ntptime, rtptime, packetcount, octetcount, receivetime);
         stats.SetLastMessageTime(receivetime);
     }
SentRTPPacket()
void qrtplib::RTPInternalSourceData::SentRTPPacket () inline
Definition at line 88 of file rtpinternalsourcedata.h.
References qrtplib::RTPTime::CurrentTime().
Referenced by qrtplib::RTPSources::SentRTPPacket().
     {
         if (!ownssrc)
             return;
         RTPTime t = RTPTime::CurrentTime();
         issender = true;
         stats.SetLastRTPPacketTime(t);
         stats.SetLastMessageTime(t);
     }
SetCSRC()
void qrtplib::RTPInternalSourceData::SetCSRC () inline
Definition at line 102 of file rtpinternalsourcedata.h.
Referenced by qrtplib::RTPSources::ProcessRTPPacket().
     {
         validated = true;
         iscsrc = true;
     }
SetOwnSSRC()
void qrtplib::RTPInternalSourceData::SetOwnSSRC () inline
Definition at line 97 of file rtpinternalsourcedata.h.
Referenced by qrtplib::RTPSources::CreateOwnSSRC().
     {
         ownssrc = true;
         validated = true;
     }
SetRTCPDataAddress()
int qrtplib::RTPInternalSourceData::SetRTCPDataAddress (const RTPAddress * a) inline
Definition at line 138 of file rtpinternalsourcedata.h.
References qrtplib::RTPAddress::CreateCopy(), and ERR_RTP_OUTOFMEM.
Referenced by qrtplib::RTPSources::CheckCollision(), qrtplib::RTPSources::CreateOwnSSRC(), and qrtplib::RTPSources::GetRTCPSourceData().
 {
     if (a == 0)
     {
         if (rtcpaddr)
         {
             delete rtcpaddr;
             rtcpaddr = 0;
         }
     }
     else
     {
         RTPAddress *newaddr = a->CreateCopy();
         if (newaddr == 0)
             return ERR_RTP_OUTOFMEM;
         if (rtcpaddr && a != rtcpaddr)
             delete rtcpaddr;
         rtcpaddr = newaddr;
     }
     isrtcpaddrset = true;
     return 0;
 }
SetRTPDataAddress()
int qrtplib::RTPInternalSourceData::SetRTPDataAddress (const RTPAddress * a) inline
Definition at line 114 of file rtpinternalsourcedata.h.
References qrtplib::RTPAddress::CreateCopy(), and ERR_RTP_OUTOFMEM.
Referenced by qrtplib::RTPSources::CheckCollision(), qrtplib::RTPSources::CreateOwnSSRC(), and qrtplib::RTPSources::ProcessRTPPacket().
 {
     if (a == 0)
     {
         if (rtpaddr)
         {
             delete rtpaddr;
             rtpaddr = 0;
         }
     }
     else
     {
         RTPAddress *newaddr = a->CreateCopy();
         if (newaddr == 0)
             return ERR_RTP_OUTOFMEM;
         if (rtpaddr && a != rtpaddr)
             delete rtpaddr;
         rtpaddr = newaddr;
     }
     isrtpaddrset = true;
     return 0;
 }
UpdateMessageTime()
void qrtplib::RTPInternalSourceData::UpdateMessageTime (const RTPTime & receivetime) inline
Definition at line 71 of file rtpinternalsourcedata.h.
Referenced by qrtplib::RTPSources::UpdateReceiveTime().
     {
         stats.SetLastMessageTime(receivetime);
     }
The documentation for this class was generated from the following files:
qrtplib/rtpinternalsourcedata.h
qrtplib/rtpinternalsourcedata.cpp