SDRAngel: qrtplib::RTPRandom Class Reference
qrtplib::RTPRandom Class Reference abstract
#include <rtprandom.h>
Public Member Functions
RTPRandom ()
virtual ~RTPRandom ()
virtual uint8_t GetRandom8 ()=0
virtual uint16_t GetRandom16 ()=0
virtual uint32_t GetRandom32 ()=0
virtual double GetRandomDouble ()=0
uint32_t PickSeed ()
Static Public Member Functions
static RTPRandom * CreateDefaultRandomNumberGenerator ()
Detailed Description
Interface for generating random numbers.
Definition at line 53 of file rtprandom.h.
Constructor & Destructor Documentation
RTPRandom()
qrtplib::RTPRandom::RTPRandom () inline
Definition at line 56 of file rtprandom.h.
     {
     }
~RTPRandom()
virtual qrtplib::RTPRandom::~RTPRandom () inline virtual
Definition at line 59 of file rtprandom.h.
     {
     }
Member Function Documentation
CreateDefaultRandomNumberGenerator()
RTPRandom * qrtplib::RTPRandom::CreateDefaultRandomNumberGenerator () static
Allocate a default random number generator based on your platform.
Definition at line 73 of file rtprandom.cpp.
References qrtplib::RTPRandomURandom::Init().
Referenced by qrtplib::RTPSession::GetRandomNumberGenerator().
 {
     RTPRandomURandom *r = new RTPRandomURandom();
     RTPRandom *rRet = r;
     if (r->Init() < 0) // fall back to rand48
     {
         delete r;
         rRet = new RTPRandomRand48();
     }
     return rRet;
 }
GetRandom16()
virtual uint16_t qrtplib::RTPRandom::GetRandom16 () pure virtual
Returns a random sixteen bit value.
Implemented in qrtplib::RTPRandomRandS, qrtplib::RTPRandomURandom, and qrtplib::RTPRandomRand48.
Referenced by qrtplib::RTPPacketBuilder::CreateNewSSRC().
GetRandom32()
virtual uint32_t qrtplib::RTPRandom::GetRandom32 () pure virtual
Returns a random thirty-two bit value.
Implemented in qrtplib::RTPRandomRandS, qrtplib::RTPRandomURandom, and qrtplib::RTPRandomRand48.
Referenced by qrtplib::RTPPacketBuilder::CreateNewSSRC().
GetRandom8()
virtual uint8_t qrtplib::RTPRandom::GetRandom8 () pure virtual
Returns a random eight bit value.
Implemented in qrtplib::RTPRandomRandS, qrtplib::RTPRandomURandom, and qrtplib::RTPRandomRand48.
GetRandomDouble()
virtual double qrtplib::RTPRandom::GetRandomDouble () pure virtual
Returns a random number between $0.0$ and $1.0$.
Implemented in qrtplib::RTPRandomRandS, qrtplib::RTPRandomURandom, and qrtplib::RTPRandomRand48.
Referenced by qrtplib::RTCPScheduler::CalculateBYETransmissionInterval(), and qrtplib::RTCPScheduler::CalculateTransmissionInterval().
PickSeed()
uint32_t qrtplib::RTPRandom::PickSeed ()
Can be used by subclasses to generate a seed for a random number generator.
Definition at line 54 of file rtprandom.cpp.
Referenced by qrtplib::RTPRandomRand48::RTPRandomRand48().
 {
     uint32_t x;
 #ifdef _MSC_VER
     x = GetCurrentProcessId();
 #else
     x = (uint32_t) getpid();
 #endif
     QDateTime currentDateTime = QDateTime::currentDateTime();
     x += currentDateTime.toTime_t();
 #if defined(WIN32)
     x += QDateTime::currentMSecsSinceEpoch() % 1000;
 #else
     x += (uint32_t)clock();
 #endif
     x ^= (uint32_t)((uint8_t *)this - (uint8_t *)0);
     return x;
 }
The documentation for this class was generated from the following files:
qrtplib/rtprandom.h
qrtplib/rtprandom.cpp