SDRAngel: PerseusThread Class Reference
PerseusThread Class Reference
#include <perseusthread.h>
Inherits QThread.
Public Member Functions
PerseusThread (perseus_descr *dev, SampleSinkFifo *sampleFifo, QObject *parent=0)
~PerseusThread ()
void startWork ()
void stopWork ()
void setLog2Decimation (unsigned int log2_decim)
Private Member Functions
void run ()
void callback (const uint8_t *buf, qint32 len)
Static Private Member Functions
static int rx_callback (void *buf, int buf_size, void *extra)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
volatile bool m_running
perseus_descr * m_dev
qint32 m_buf [2 *PERSEUS_NBSAMPLES]
SampleVector m_convertBuffer
SampleSinkFifo * m_sampleFifo
unsigned int m_log2Decim
Decimators< qint32, TripleByteLE< qint32 >, SDR_RX_SAMP_SZ, 24 > m_decimators32
Decimators< qint32, TripleByteLE< qint64 >, SDR_RX_SAMP_SZ, 24 > m_decimators64
Static Private Attributes
static PerseusThread * m_this = 0
Detailed Description
Definition at line 32 of file perseusthread.h.
Constructor & Destructor Documentation
PerseusThread()
PerseusThread::PerseusThread (perseus_descr * dev, SampleSinkFifo * sampleFifo, QObject * parent = 0)
Definition at line 24 of file perseusthread.cpp.
References m_buf, m_this, and PERSEUS_NBSAMPLES.
                                                                                             :
     QThread(parent),
     m_running(false),
     m_dev(dev),
     m_convertBuffer(PERSEUS_NBSAMPLES),
     m_sampleFifo(sampleFifo),
     m_log2Decim(0)
 {
     m_this = this;
     std::fill(m_buf, m_buf + 2*PERSEUS_NBSAMPLES, 0);
 }
~PerseusThread()
PerseusThread::~PerseusThread ()
Definition at line 36 of file perseusthread.cpp.
References m_this, and stopWork().
 {
     stopWork();
     m_this = 0;
 }
Member Function Documentation
callback()
void PerseusThread::callback (const uint8_t * buf, qint32 len) private
Definition at line 93 of file perseusthread.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), m_convertBuffer, m_decimators32, m_decimators64, m_log2Decim, m_sampleFifo, and SampleSinkFifo::write().
Referenced by rx_callback().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     switch (m_log2Decim)
     {
     case 0:
         m_decimators32.decimate1(&it, (TripleByteLE<qint32>*) buf, len);
         break;
     case 1:
         m_decimators64.decimate2_cen(&it, (TripleByteLE<qint64>*) buf, len);
         break;
     case 2:
         m_decimators64.decimate4_cen(&it, (TripleByteLE<qint64>*) buf, len);
         break;
     default:
         break;
     }
     m_sampleFifo->write(m_convertBuffer.begin(), it);
 }
run()
void PerseusThread::run () private
Definition at line 64 of file perseusthread.cpp.
References m_dev, m_running, m_startWaiter, PERSEUS_BLOCKSIZE, and rx_callback().
 {
     m_running = true;
     m_startWaiter.wakeAll();
     int rc = perseus_start_async_input(m_dev, PERSEUS_BLOCKSIZE, rx_callback, 0);
     if (rc < 0) {
         qCritical("PerseusThread::run: failed to start Perseus Rx: %s", perseus_errorstr());
     }
     else
     {
         qDebug("PerseusThread::run: start Perseus Rx");
         while (m_running) {
             sleep(1);
         }
     }
     rc = perseus_stop_async_input(m_dev);
     if (rc < 0) {
         qCritical("PerseusThread::run: failed to stop Perseus Rx: %s", perseus_errorstr());
     } else {
         qDebug("PerseusThread::run: stopped Perseus Rx");
     }
     m_running = false;
 }
rx_callback()
int PerseusThread::rx_callback (void * buf, int buf_size, void * extra) static private
Definition at line 115 of file perseusthread.cpp.
References callback(), and m_this.
Referenced by run().
 {
     (void) extra;
     qint32 nbIAndQ = buf_size / 3; // 3 bytes per I or Q
     m_this->callback((uint8_t*) buf, nbIAndQ);
     return 0;
 }
setLog2Decimation()
void PerseusThread::setLog2Decimation (unsigned int log2_decim)
Definition at line 59 of file perseusthread.cpp.
References m_log2Decim.
Referenced by PerseusInput::applySettings(), and PerseusInput::start().
 {
     m_log2Decim = log2_decim;
 }
startWork()
void PerseusThread::startWork ()
Definition at line 42 of file perseusthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by PerseusInput::start().
 {
     qDebug("PerseusThread::startWork");
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void PerseusThread::stopWork ()
Definition at line 52 of file perseusthread.cpp.
References m_running.
Referenced by PerseusInput::stop(), and ~PerseusThread().
 {
     qDebug("PerseusThread::stopWork");
     m_running = false;
     wait();
 }
Member Data Documentation
m_buf
qint32 PerseusThread::m_buf[2 *PERSEUS_NBSAMPLES] private
Definition at line 49 of file perseusthread.h.
Referenced by PerseusThread().
m_convertBuffer
SampleVector PerseusThread::m_convertBuffer private
Definition at line 50 of file perseusthread.h.
Referenced by callback().
m_decimators32
Decimators<qint32, TripleByteLE<qint32>, SDR_RX_SAMP_SZ, 24> PerseusThread::m_decimators32 private
Definition at line 56 of file perseusthread.h.
Referenced by callback().
m_decimators64
Decimators<qint32, TripleByteLE<qint64>, SDR_RX_SAMP_SZ, 24> PerseusThread::m_decimators64 private
Definition at line 57 of file perseusthread.h.
Referenced by callback().
m_dev
perseus_descr* PerseusThread::m_dev private
Definition at line 48 of file perseusthread.h.
Referenced by run().
m_log2Decim
unsigned int PerseusThread::m_log2Decim private
Definition at line 53 of file perseusthread.h.
Referenced by callback(), and setLog2Decimation().
m_running
volatile bool PerseusThread::m_running private
Definition at line 46 of file perseusthread.h.
Referenced by run(), startWork(), and stopWork().
m_sampleFifo
SampleSinkFifo* PerseusThread::m_sampleFifo private
Definition at line 51 of file perseusthread.h.
Referenced by callback().
m_startWaiter
QWaitCondition PerseusThread::m_startWaiter private
Definition at line 45 of file perseusthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex PerseusThread::m_startWaitMutex private
Definition at line 44 of file perseusthread.h.
Referenced by startWork().
m_this
PerseusThread * PerseusThread::m_this = 0 static private
Definition at line 54 of file perseusthread.h.
Referenced by PerseusThread(), rx_callback(), and ~PerseusThread().
The documentation for this class was generated from the following files:
plugins/samplesource/perseus/perseusthread.h
plugins/samplesource/perseus/perseusthread.cpp