SDRAngel: XTRXOutputThread Class Reference
XTRXOutputThread Class Reference
#include <xtrxoutputthread.h>
Classes
struct Channel
Public Member Functions
XTRXOutputThread (struct xtrx_dev *dev, unsigned int nbChannels, unsigned int uniqueChannelIndex=0, QObject *parent=0)
~XTRXOutputThread ()
virtual void startWork ()
virtual void stopWork ()
virtual bool isRunning ()
unsigned int getNbChannels () const
void setLog2Interpolation (unsigned int channel, unsigned int log2_interp)
unsigned int getLog2Interpolation (unsigned int channel) const
void setFifo (unsigned int channel, SampleSourceFifo *sampleFifo)
SampleSourceFifo * getFifo (unsigned int channel)
Private Member Functions
void run ()
unsigned int getNbFifos ()
void callback (qint16 *buf, qint32 len)
void callbackSO (qint16 *buf, qint32 len)
void callbackMO (qint16 *buf0, qint16 *buf1, qint32 len)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
struct xtrx_dev * m_dev
Channel * m_channels
Array of channels dynamically allocated for the given number of Rx channels.
unsigned int m_nbChannels
unsigned int m_uniqueChannelIndex
Detailed Description
Definition at line 33 of file xtrxoutputthread.h.
Constructor & Destructor Documentation
XTRXOutputThread()
XTRXOutputThread::XTRXOutputThread (struct xtrx_dev * dev, unsigned int nbChannels, unsigned int uniqueChannelIndex = 0, QObject * parent = 0)
Definition at line 27 of file xtrxoutputthread.cpp.
References m_channels.
                                                                                                                                   :
     QThread(parent),
     m_running(false),
     m_dev(dev),
     m_nbChannels(nbChannels),
     m_uniqueChannelIndex(uniqueChannelIndex)
 {
     qDebug("XTRXOutputThread::XTRXOutputThread: nbChannels: %u uniqueChannelIndex: %u", nbChannels, uniqueChannelIndex);
     m_channels = new Channel[2];
 }
~XTRXOutputThread()
XTRXOutputThread::~XTRXOutputThread ()
Definition at line 38 of file xtrxoutputthread.cpp.
References m_channels, m_running, and stopWork().
 {
     qDebug("XTRXOutputThread::~XTRXOutputThread");
     if (m_running) {
         stopWork();
     }
     delete[] m_channels;
 }
Member Function Documentation
callback()
void XTRXOutputThread::callback (qint16 * buf, qint32 len) private
Definition at line 225 of file xtrxoutputthread.cpp.
References SampleSourceFifo::getRWBalance(), Interpolators< T, SdrBits, OutputBits >::interpolate1(), Interpolators< T, SdrBits, OutputBits >::interpolate16_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate2_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate32_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate4_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate64_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate8_cen(), m_channels, XTRXOutputThread::Channel::m_interpolators, XTRXOutputThread::Channel::m_sampleFifo, m_uniqueChannelIndex, and SampleSourceFifo::readAdvance().
 {
     if (m_channels[m_uniqueChannelIndex].m_sampleFifo)
     {
         float bal = m_channels[m_uniqueChannelIndex].m_sampleFifo->getRWBalance();
         if (bal < -0.25) {
             qDebug("XTRXOutputThread::callbackSO: read lags: %f", bal);
         } else if (bal > 0.25) {
             qDebug("XTRXOutputThread::callbackSO: read leads: %f", bal);
         }
         SampleVector::iterator beginRead;
         m_channels[m_uniqueChannelIndex].m_sampleFifo->readAdvance(beginRead, len/(1<<m_channels[m_uniqueChannelIndex].m_log2Interp));
         beginRead -= len;
         if (m_channels[m_uniqueChannelIndex].m_log2Interp == 0)
         {
             m_channels[m_uniqueChannelIndex].m_interpolators.interpolate1(&beginRead, buf, len*2);
         }
         else
         {
             switch (m_channels[m_uniqueChannelIndex].m_log2Interp)
             {
             case 1:
                 m_channels[m_uniqueChannelIndex].m_interpolators.interpolate2_cen(&beginRead, buf, len*2);
                 break;
             case 2:
                 m_channels[m_uniqueChannelIndex].m_interpolators.interpolate4_cen(&beginRead, buf, len*2);
                 break;
             case 3:
                 m_channels[m_uniqueChannelIndex].m_interpolators.interpolate8_cen(&beginRead, buf, len*2);
                 break;
             case 4:
                 m_channels[m_uniqueChannelIndex].m_interpolators.interpolate16_cen(&beginRead, buf, len*2);
                 break;
             case 5:
                 m_channels[m_uniqueChannelIndex].m_interpolators.interpolate32_cen(&beginRead, buf, len*2);
                 break;
             case 6:
                 m_channels[m_uniqueChannelIndex].m_interpolators.interpolate64_cen(&beginRead, buf, len*2);
                 break;
             default:
                 break;
             }
         }
     }
     else
     {
         std::fill(buf, buf+2*len, 0);
     }
 }
callbackMO()
void XTRXOutputThread::callbackMO (qint16 * buf0, qint16 * buf1, qint32 len) private
Definition at line 331 of file xtrxoutputthread.cpp.
References callbackSO(), and m_uniqueChannelIndex.
 {
     unsigned int uniqueChannelIndex = m_uniqueChannelIndex;
     // channel 0
     m_uniqueChannelIndex = 0;
     callbackSO(buf0, len);
     // channel 1
     m_uniqueChannelIndex = 1;
     callbackSO(buf1, len);
     m_uniqueChannelIndex = uniqueChannelIndex;
 }
callbackSO()
void XTRXOutputThread::callbackSO (qint16 * buf, qint32 len) private
Definition at line 278 of file xtrxoutputthread.cpp.
References SampleSourceFifo::getRWBalance(), Interpolators< T, SdrBits, OutputBits >::interpolate1(), Interpolators< T, SdrBits, OutputBits >::interpolate16_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate2_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate32_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate4_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate64_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate8_cen(), m_channels, XTRXOutputThread::Channel::m_interpolators, XTRXOutputThread::Channel::m_sampleFifo, m_uniqueChannelIndex, and SampleSourceFifo::readAdvance().
Referenced by callbackMO(), and run().
 {
     if (m_channels[m_uniqueChannelIndex].m_sampleFifo)
     {
         float bal = m_channels[m_uniqueChannelIndex].m_sampleFifo->getRWBalance();
         if (bal < -0.25) {
             qDebug("XTRXOutputThread::callbackSO: read lags: %f", bal);
         } else if (bal > 0.25) {
             qDebug("XTRXOutputThread::callbackSO: read leads: %f", bal);
         }
         SampleVector::iterator beginRead;
         m_channels[m_uniqueChannelIndex].m_sampleFifo->readAdvance(beginRead, len/(1<<m_channels[m_uniqueChannelIndex].m_log2Interp));
         beginRead -= len;
         if (m_channels[m_uniqueChannelIndex].m_log2Interp == 0)
         {
             m_channels[m_uniqueChannelIndex].m_interpolators.interpolate1(&beginRead, buf, len*2);
         }
         else
         {
             switch (m_channels[m_uniqueChannelIndex].m_log2Interp)
             {
             case 1:
                 m_channels[m_uniqueChannelIndex].m_interpolators.interpolate2_cen(&beginRead, buf, len*2);
                 break;
             case 2:
                 m_channels[m_uniqueChannelIndex].m_interpolators.interpolate4_cen(&beginRead, buf, len*2);
                 break;
             case 3:
                 m_channels[m_uniqueChannelIndex].m_interpolators.interpolate8_cen(&beginRead, buf, len*2);
                 break;
             case 4:
                 m_channels[m_uniqueChannelIndex].m_interpolators.interpolate16_cen(&beginRead, buf, len*2);
                 break;
             case 5:
                 m_channels[m_uniqueChannelIndex].m_interpolators.interpolate32_cen(&beginRead, buf, len*2);
                 break;
             case 6:
                 m_channels[m_uniqueChannelIndex].m_interpolators.interpolate64_cen(&beginRead, buf, len*2);
                 break;
             default:
                 break;
             }
         }
     }
     else
     {
         std::fill(buf, buf+2*len, 0);
     }
 }
getFifo()
SampleSourceFifo * XTRXOutputThread::getFifo (unsigned int channel)
Definition at line 104 of file xtrxoutputthread.cpp.
References m_channels, and XTRXOutputThread::Channel::m_sampleFifo.
Referenced by getNbChannels(), and XTRXOutput::start().
 {
     if (channel < 2) {
         return m_channels[channel].m_sampleFifo;
     } else {
         return 0;
     }
 }
getLog2Interpolation()
unsigned int XTRXOutputThread::getLog2Interpolation (unsigned int channel) const
Definition at line 88 of file xtrxoutputthread.cpp.
References m_channels, and XTRXOutputThread::Channel::m_log2Interp.
Referenced by getNbChannels(), and XTRXOutput::start().
 {
     if (channel < 2) {
         return m_channels[channel].m_log2Interp;
     } else {
         return 0;
     }
 }
getNbChannels()
unsigned int XTRXOutputThread::getNbChannels () const inline
Definition at line 44 of file xtrxoutputthread.h.
References getFifo(), getLog2Interpolation(), m_nbChannels, setFifo(), and setLog2Interpolation().
Referenced by XTRXOutput::start(), and XTRXOutput::stop().
 { return m_nbChannels; }
getNbFifos()
unsigned int XTRXOutputThread::getNbFifos () private
Definition at line 67 of file xtrxoutputthread.cpp.
References i, and m_channels.
Referenced by run().
 {
     unsigned int fifoCount = 0;
     for (unsigned int i = 0; i < 2; i++)
     {
         if (m_channels[i].m_sampleFifo) {
             fifoCount++;
         }
     }
     return fifoCount;
 }
isRunning()
virtual bool XTRXOutputThread::isRunning () inline virtual
Implements DeviceXTRXShared::ThreadInterface.
Definition at line 43 of file xtrxoutputthread.h.
References m_running.
Referenced by XTRXOutput::applySettings().
 { return m_running; }
run()
void XTRXOutputThread::run () private
Definition at line 113 of file xtrxoutputthread.cpp.
References DeviceXTRX::blockSize, callbackSO(), getNbFifos(), i, m_dev, m_nbChannels, m_running, m_startWaiter, and m_uniqueChannelIndex.
 {
     int res;
     m_running = true;
     m_startWaiter.wakeAll();
     unsigned int nbFifos = getNbFifos();
     if ((m_nbChannels != 0) && (nbFifos != 0))
     {
         xtrx_run_params params;
         xtrx_run_params_init(&params);
         params.dir = XTRX_TX;
         params.tx_repeat_buf = 0;
         params.tx.paketsize = 2*DeviceXTRX::blockSize;
         params.tx.chs = XTRX_CH_AB;
         params.tx.wfmt = XTRX_WF_16;
         params.tx.hfmt = XTRX_IQ_INT16;
         params.tx.flags |= XTRX_RSP_SWAP_IQ;
         if (m_nbChannels == 1)
         {
             qDebug("XTRXOutputThread::run: SO mode for channel #%u", m_uniqueChannelIndex);
             params.tx.flags |= XTRX_RSP_SISO_MODE;
             if (m_uniqueChannelIndex == 1) {
                 params.tx.flags |= XTRX_RSP_SWAP_AB;
             }
         }
         res = xtrx_run_ex(m_dev, &params);
         if (res != 0)
         {
             qCritical("XTRXOutputThread::run: could not start stream err:%d", res);
             m_running = false;
         }
         else
         {
             std::this_thread::sleep_for(std::chrono::milliseconds(50));
             qDebug("XTRXOutputThread::run: stream started");
         }
         const unsigned int elemSize = 4; // XTRX uses 4 byte I+Q samples
         std::vector<std::vector<char>> buffMem(m_nbChannels, std::vector<char>(elemSize*DeviceXTRX::blockSize));
         std::vector<void *> buffs(m_nbChannels);
         master_ts ts = 4096*1024;
         for (std::size_t i = 0; i < m_nbChannels; i++) {
             buffs[i] = buffMem[i].data();
         }
         xtrx_send_ex_info_t nfo;
         nfo.samples = DeviceXTRX::blockSize;
         nfo.buffer_count = m_nbChannels;
         nfo.buffers = (void* const*) buffs.data();
         nfo.flags = XTRX_TX_DONT_BUFFER; // | XTRX_TX_SEND_ZEROS;
         nfo.timeout = 0;
         nfo.out_txlatets = 0;
         nfo.ts = ts;
         while (m_running)
         {
 //            if (m_nbChannels > 1) {
 //                callbackMO((qint16*) buffs[0], (qint16*) buffs[1], nfo.samples);
 //            } else {
 //                callbackSO((qint16*) buffs[0], nfo.samples);
 //            }
             callbackSO((qint16*) buffs[0], nfo.samples);
             res = xtrx_send_sync_ex(m_dev, &nfo);
             if (res < 0)
             {
                 qCritical("XTRXOutputThread::run send error: %d", res);
                 qDebug("XTRXOutputThread::run: out_samples: %u out_flags: %u", nfo.out_samples, nfo.out_flags);
                 break;
             }
             if (nfo.out_flags & XTRX_TX_DISCARDED_TO) {
                 qDebug("XTRXOutputThread::run: underrun");
             }
             if (nfo.out_txlatets) {
                 qDebug("XTRXOutputThread::run: out_txlatets: %lu", nfo.out_txlatets);
             }
             nfo.ts += DeviceXTRX::blockSize;
         }
         res = xtrx_stop(m_dev, XTRX_TX);
         if (res != 0)
         {
             qCritical("XTRXOutputThread::run: could not stop stream");
         }
         else
         {
             std::this_thread::sleep_for(std::chrono::milliseconds(50));
             qDebug("XTRXOutputThread::run: stream stopped");
         }
     }
     else
     {
         qWarning("XTRXOutputThread::run: no channels or FIFO allocated. Aborting");
     }
     m_running = false;
 }
setFifo()
void XTRXOutputThread::setFifo (unsigned int channel, SampleSourceFifo * sampleFifo)
Definition at line 97 of file xtrxoutputthread.cpp.
References m_channels, and XTRXOutputThread::Channel::m_sampleFifo.
Referenced by getNbChannels(), XTRXOutput::start(), and XTRXOutput::stop().
 {
     if (channel < 2) {
         m_channels[channel].m_sampleFifo = sampleFifo;
     }
 }
setLog2Interpolation()
void XTRXOutputThread::setLog2Interpolation (unsigned int channel, unsigned int log2_interp)
Definition at line 81 of file xtrxoutputthread.cpp.
References m_channels, and XTRXOutputThread::Channel::m_log2Interp.
Referenced by XTRXOutput::applySettings(), getNbChannels(), XTRXOutput::start(), and XTRXOutput::stop().
 {
     if (channel < 2) {
         m_channels[channel].m_log2Interp = log2_interp;
     }
 }
startWork()
void XTRXOutputThread::startWork () virtual
Implements DeviceXTRXShared::ThreadInterface.
Definition at line 49 of file xtrxoutputthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by XTRXOutput::applySettings(), XTRXOutput::start(), and XTRXOutput::stop().
 {
     m_startWaitMutex.lock();
     start();
     while(!m_running) {
         m_startWaiter.wait(&m_startWaitMutex, 100);
     }
     m_startWaitMutex.unlock();
 }
stopWork()
void XTRXOutputThread::stopWork () virtual
Implements DeviceXTRXShared::ThreadInterface.
Definition at line 61 of file xtrxoutputthread.cpp.
References m_running.
Referenced by XTRXOutput::applySettings(), XTRXOutput::start(), XTRXOutput::stop(), and ~XTRXOutputThread().
 {
     m_running = false;
     wait();
 }
Member Data Documentation
m_channels
Channel* XTRXOutputThread::m_channels private
Array of channels dynamically allocated for the given number of Rx channels.
Definition at line 71 of file xtrxoutputthread.h.
Referenced by callback(), callbackSO(), getFifo(), getLog2Interpolation(), getNbFifos(), setFifo(), setLog2Interpolation(), XTRXOutputThread(), and ~XTRXOutputThread().
m_dev
struct xtrx_dev* XTRXOutputThread::m_dev private
Definition at line 69 of file xtrxoutputthread.h.
Referenced by run().
m_nbChannels
unsigned int XTRXOutputThread::m_nbChannels private
Definition at line 72 of file xtrxoutputthread.h.
Referenced by getNbChannels(), and run().
m_running
bool XTRXOutputThread::m_running private
Definition at line 68 of file xtrxoutputthread.h.
Referenced by isRunning(), run(), startWork(), stopWork(), and ~XTRXOutputThread().
m_startWaiter
QWaitCondition XTRXOutputThread::m_startWaiter private
Definition at line 67 of file xtrxoutputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex XTRXOutputThread::m_startWaitMutex private
Definition at line 66 of file xtrxoutputthread.h.
Referenced by startWork().
m_uniqueChannelIndex
unsigned int XTRXOutputThread::m_uniqueChannelIndex private
Definition at line 73 of file xtrxoutputthread.h.
Referenced by callback(), callbackMO(), callbackSO(), and run().
The documentation for this class was generated from the following files:
plugins/samplesink/xtrxoutput/xtrxoutputthread.h
plugins/samplesink/xtrxoutput/xtrxoutputthread.cpp