SDRAngel: MainWindow::MsgLoadPreset Class Reference
MainWindow::MsgLoadPreset Class Reference
Public Member Functions
const Preset * getPreset () const
int getDeviceSetIndex () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgLoadPreset * create (const Preset *preset, int deviceSetIndex)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgLoadPreset (const Preset *preset, int deviceSetIndex)
Private Attributes
const Preset * m_preset
int m_deviceSetIndex
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 90 of file mainwindow.h.
Constructor & Destructor Documentation
MsgLoadPreset()
MainWindow::MsgLoadPreset::MsgLoadPreset (const Preset * preset, int deviceSetIndex) inline private
Definition at line 106 of file mainwindow.h.
                                                                 :
             Message(),
             m_preset(preset),
             m_deviceSetIndex(deviceSetIndex)
         { }
Member Function Documentation
create()
static MsgLoadPreset* MainWindow::MsgLoadPreset::create (const Preset * preset, int deviceSetIndex) inline static
Definition at line 97 of file mainwindow.h.
Referenced by WebAPIAdapterGUI::instancePresetPatch().
         {
             return new MsgLoadPreset(preset, deviceSetIndex);
         }
getDeviceSetIndex()
int MainWindow::MsgLoadPreset::getDeviceSetIndex () const inline
Definition at line 95 of file mainwindow.h.
Referenced by MainWindow::handleMessage().
 { return m_deviceSetIndex; }
getPreset()
const Preset* MainWindow::MsgLoadPreset::getPreset () const inline
Definition at line 94 of file mainwindow.h.
Referenced by MainWindow::handleMessage().
 { return m_preset; }
Member Data Documentation
m_deviceSetIndex
int MainWindow::MsgLoadPreset::m_deviceSetIndex private
Definition at line 104 of file mainwindow.h.
m_preset
const Preset* MainWindow::MsgLoadPreset::m_preset private
Definition at line 103 of file mainwindow.h.
The documentation for this class was generated from the following file:
sdrgui/mainwindow.h