SDRAngel: RemoteSource::MsgReportStreamData Class Reference
RemoteSource::MsgReportStreamData Class Reference
#include <remotesource.h>
Public Member Functions
uint32_t get_tv_sec () const
uint32_t get_tv_usec () const
uint32_t get_queueSize () const
uint32_t get_queueLength () const
uint32_t get_readSamplesCount () const
uint32_t get_nbCorrectableErrors () const
uint32_t get_nbUncorrectableErrors () const
uint32_t get_nbOriginalBlocks () const
uint32_t get_nbFECBlocks () const
uint32_t get_centerFreq () const
uint32_t get_sampleRate () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportStreamData * create (uint32_t tv_sec, uint32_t tv_usec, uint32_t queueSize, uint32_t queueLength, uint32_t readSamplesCount, uint32_t nbCorrectableErrors, uint32_t nbUncorrectableErrors, uint32_t nbOriginalBlocks, uint32_t nbFECBlocks, uint32_t centerFreq, uint32_t sampleRate)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportStreamData (uint32_t tv_sec, uint32_t tv_usec, uint32_t queueSize, uint32_t queueLength, uint32_t readSamplesCount, uint32_t nbCorrectableErrors, uint32_t nbUncorrectableErrors, uint32_t nbOriginalBlocks, uint32_t nbFECBlocks, uint32_t centerFreq, uint32_t sampleRate)
Protected Attributes
uint32_t m_tv_sec
uint32_t m_tv_usec
uint32_t m_queueSize
uint32_t m_queueLength
uint32_t m_readSamplesCount
uint32_t m_nbCorrectableErrors
uint32_t m_nbUncorrectableErrors
uint32_t m_nbOriginalBlocks
uint32_t m_nbFECBlocks
uint32_t m_centerFreq
uint32_t m_sampleRate
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 101 of file remotesource.h.
Constructor & Destructor Documentation
MsgReportStreamData()
RemoteSource::MsgReportStreamData::MsgReportStreamData (uint32_t tv_sec, uint32_t tv_usec, uint32_t queueSize, uint32_t queueLength, uint32_t readSamplesCount, uint32_t nbCorrectableErrors, uint32_t nbUncorrectableErrors, uint32_t nbOriginalBlocks, uint32_t nbFECBlocks, uint32_t centerFreq, uint32_t sampleRate) inline protected
Definition at line 157 of file remotesource.h.
References RemoteSource::RemoteSource(), and RemoteSource::~RemoteSource().
                                      :
             Message(),
             m_tv_sec(tv_sec),
             m_tv_usec(tv_usec),
             m_queueSize(queueSize),
             m_queueLength(queueLength),
             m_readSamplesCount(readSamplesCount),
             m_nbCorrectableErrors(nbCorrectableErrors),
             m_nbUncorrectableErrors(nbUncorrectableErrors),
             m_nbOriginalBlocks(nbOriginalBlocks),
             m_nbFECBlocks(nbFECBlocks),
             m_centerFreq(centerFreq),
             m_sampleRate(sampleRate)
         { }
Member Function Documentation
create()
static MsgReportStreamData* RemoteSource::MsgReportStreamData::create (uint32_t tv_sec, uint32_t tv_usec, uint32_t queueSize, uint32_t queueLength, uint32_t readSamplesCount, uint32_t nbCorrectableErrors, uint32_t nbUncorrectableErrors, uint32_t nbOriginalBlocks, uint32_t nbFECBlocks, uint32_t centerFreq, uint32_t sampleRate) inline static
Definition at line 117 of file remotesource.h.
Referenced by RemoteSource::handleMessage().
         {
             return new MsgReportStreamData(
                     tv_sec,
                     tv_usec,
                     queueSize,
                     queueLength,
                     readSamplesCount,
                     nbCorrectableErrors,
                     nbUncorrectableErrors,
                     nbOriginalBlocks,
                     nbFECBlocks,
                     centerFreq,
                     sampleRate);
         }
get_centerFreq()
uint32_t RemoteSource::MsgReportStreamData::get_centerFreq () const inline
Definition at line 114 of file remotesource.h.
 { return m_centerFreq; }
get_nbCorrectableErrors()
uint32_t RemoteSource::MsgReportStreamData::get_nbCorrectableErrors () const inline
Definition at line 110 of file remotesource.h.
References RemoteSource::m_nbCorrectableErrors.
Referenced by RemoteSourceGUI::handleMessage().
 { return m_nbCorrectableErrors; }
get_nbFECBlocks()
uint32_t RemoteSource::MsgReportStreamData::get_nbFECBlocks () const inline
Definition at line 113 of file remotesource.h.
Referenced by RemoteSourceGUI::handleMessage().
 { return m_nbFECBlocks; }
get_nbOriginalBlocks()
uint32_t RemoteSource::MsgReportStreamData::get_nbOriginalBlocks () const inline
Definition at line 112 of file remotesource.h.
Referenced by RemoteSourceGUI::handleMessage().
 { return m_nbOriginalBlocks; }
get_nbUncorrectableErrors()
uint32_t RemoteSource::MsgReportStreamData::get_nbUncorrectableErrors () const inline
Definition at line 111 of file remotesource.h.
References RemoteSource::m_nbUncorrectableErrors.
Referenced by RemoteSourceGUI::handleMessage().
 { return m_nbUncorrectableErrors; }
get_queueLength()
uint32_t RemoteSource::MsgReportStreamData::get_queueLength () const inline
Definition at line 108 of file remotesource.h.
Referenced by RemoteSourceGUI::handleMessage().
 { return m_queueLength; }
get_queueSize()
uint32_t RemoteSource::MsgReportStreamData::get_queueSize () const inline
Definition at line 107 of file remotesource.h.
Referenced by RemoteSourceGUI::handleMessage().
 { return m_queueSize; }
get_readSamplesCount()
uint32_t RemoteSource::MsgReportStreamData::get_readSamplesCount () const inline
Definition at line 109 of file remotesource.h.
Referenced by RemoteSourceGUI::handleMessage().
 { return m_readSamplesCount; }
get_sampleRate()
uint32_t RemoteSource::MsgReportStreamData::get_sampleRate () const inline
Definition at line 115 of file remotesource.h.
Referenced by RemoteSourceGUI::handleMessage().
 { return m_sampleRate; }
get_tv_sec()
uint32_t RemoteSource::MsgReportStreamData::get_tv_sec () const inline
Definition at line 105 of file remotesource.h.
Referenced by RemoteSourceGUI::handleMessage().
 { return m_tv_sec; }
get_tv_usec()
uint32_t RemoteSource::MsgReportStreamData::get_tv_usec () const inline
Definition at line 106 of file remotesource.h.
Referenced by RemoteSourceGUI::handleMessage().
 { return m_tv_usec; }
Member Data Documentation
m_centerFreq
uint32_t RemoteSource::MsgReportStreamData::m_centerFreq protected
Definition at line 154 of file remotesource.h.
m_nbCorrectableErrors
uint32_t RemoteSource::MsgReportStreamData::m_nbCorrectableErrors protected
Definition at line 150 of file remotesource.h.
m_nbFECBlocks
uint32_t RemoteSource::MsgReportStreamData::m_nbFECBlocks protected
Definition at line 153 of file remotesource.h.
m_nbOriginalBlocks
uint32_t RemoteSource::MsgReportStreamData::m_nbOriginalBlocks protected
Definition at line 152 of file remotesource.h.
m_nbUncorrectableErrors
uint32_t RemoteSource::MsgReportStreamData::m_nbUncorrectableErrors protected
Definition at line 151 of file remotesource.h.
m_queueLength
uint32_t RemoteSource::MsgReportStreamData::m_queueLength protected
Definition at line 148 of file remotesource.h.
m_queueSize
uint32_t RemoteSource::MsgReportStreamData::m_queueSize protected
Definition at line 147 of file remotesource.h.
m_readSamplesCount
uint32_t RemoteSource::MsgReportStreamData::m_readSamplesCount protected
Definition at line 149 of file remotesource.h.
m_sampleRate
uint32_t RemoteSource::MsgReportStreamData::m_sampleRate protected
Definition at line 155 of file remotesource.h.
m_tv_sec
uint32_t RemoteSource::MsgReportStreamData::m_tv_sec protected
Definition at line 145 of file remotesource.h.
m_tv_usec
uint32_t RemoteSource::MsgReportStreamData::m_tv_usec protected
Definition at line 146 of file remotesource.h.
The documentation for this class was generated from the following file:
plugins/channeltx/remotesource/remotesource.h