SDRAngel: DSPEngine Class Reference
DSPEngine Class Reference
#include <dspengine.h>
Inherits QObject.
Public Member Functions
DSPEngine ()
~DSPEngine ()
unsigned int getDefaultAudioSampleRate () const
DSPDeviceSourceEngine * addDeviceSourceEngine ()
void removeLastDeviceSourceEngine ()
DSPDeviceSinkEngine * addDeviceSinkEngine ()
void removeLastDeviceSinkEngine ()
DSPDeviceMIMOEngine * addDeviceMIMOEngine ()
void removeLastDeviceMIMOEngine ()
AudioDeviceManager * getAudioDeviceManager ()
AMBEEngine * getAMBEEngine ()
uint32_t getDeviceSourceEnginesNumber () const
DSPDeviceSourceEngine * getDeviceSourceEngineByIndex (uint deviceIndex)
DSPDeviceSourceEngine * getDeviceSourceEngineByUID (uint uid)
uint32_t getDeviceSinkEnginesNumber () const
DSPDeviceSinkEngine * getDeviceSinkEngineByIndex (uint deviceIndex)
DSPDeviceSinkEngine * getDeviceSinkEngineByUID (uint uid)
uint32_t getDeviceMIMOEnginesNumber () const
DSPDeviceMIMOEngine * getDeviceMIMOEngineByIndex (uint deviceIndex)
DSPDeviceMIMOEngine * getDeviceMIMOEngineByUID (uint uid)
bool hasDVSerialSupport ()
void setDVSerialSupport (bool support)
void getDVSerialNames (std::vector< std::string > &deviceNames)
void pushMbeFrame (const unsigned char *mbeFrame, int mbeRateIndex, int mbeVolumeIndex, unsigned char channels, bool useHP, int upsampling, AudioFifo *audioFifo)
const QTimer & getMasterTimer () const
void setMIMOSupport (bool mimoSupport)
bool getMIMOSupport () const
Static Public Member Functions
static DSPEngine * instance ()
Private Attributes
std::vector< DSPDeviceSourceEngine * > m_deviceSourceEngines
uint m_deviceSourceEnginesUIDSequence
std::vector< DSPDeviceSinkEngine * > m_deviceSinkEngines
uint m_deviceSinkEnginesUIDSequence
std::vector< DSPDeviceMIMOEngine * > m_deviceMIMOEngines
uint m_deviceMIMOEnginesUIDSequence
AudioDeviceManager m_audioDeviceManager
int m_audioInputDeviceIndex
int m_audioOutputDeviceIndex
QTimer m_masterTimer
bool m_dvSerialSupport
bool m_mimoSupport
AMBEEngine m_ambeEngine
Detailed Description
Definition at line 36 of file dspengine.h.
Constructor & Destructor Documentation
DSPEngine()
DSPEngine::DSPEngine ()
Definition at line 27 of file dspengine.cpp.
References m_dvSerialSupport, m_masterTimer, and m_mimoSupport.
                      :
     m_deviceSourceEnginesUIDSequence(0),
     m_deviceSinkEnginesUIDSequence(0),
     m_deviceMIMOEnginesUIDSequence(0),
     m_audioInputDeviceIndex(-1),    // default device
     m_audioOutputDeviceIndex(-1)    // default device
 {
     m_dvSerialSupport = false;
     m_mimoSupport = false;
     m_masterTimer.start(50);
 }
~DSPEngine()
DSPEngine::~DSPEngine ()
Definition at line 39 of file dspengine.cpp.
References m_deviceSourceEngines.
 {
     std::vector<DSPDeviceSourceEngine*>::iterator it = m_deviceSourceEngines.begin();
     while (it != m_deviceSourceEngines.end())
     {
         delete *it;
         ++it;
     }
 }
Member Function Documentation
addDeviceMIMOEngine()
DSPDeviceMIMOEngine * DSPEngine::addDeviceMIMOEngine ()
Definition at line 92 of file dspengine.cpp.
References m_deviceMIMOEngines, and m_deviceMIMOEnginesUIDSequence.
Referenced by MainWindow::addMIMODevice().
 {
     m_deviceMIMOEngines.push_back(new DSPDeviceMIMOEngine(m_deviceMIMOEnginesUIDSequence));
     m_deviceMIMOEnginesUIDSequence++;
     return m_deviceMIMOEngines.back();
 }
addDeviceSinkEngine()
DSPDeviceSinkEngine * DSPEngine::addDeviceSinkEngine ()
Definition at line 74 of file dspengine.cpp.
References m_deviceSinkEngines, and m_deviceSinkEnginesUIDSequence.
Referenced by MainCore::addSinkDevice(), and MainWindow::addSinkDevice().
 {
     m_deviceSinkEngines.push_back(new DSPDeviceSinkEngine(m_deviceSinkEnginesUIDSequence));
     m_deviceSinkEnginesUIDSequence++;
     return m_deviceSinkEngines.back();
 }
addDeviceSourceEngine()
DSPDeviceSourceEngine * DSPEngine::addDeviceSourceEngine ()
Definition at line 56 of file dspengine.cpp.
References m_deviceSourceEngines, and m_deviceSourceEnginesUIDSequence.
Referenced by MainCore::addSourceDevice(), and MainWindow::addSourceDevice().
 {
     m_deviceSourceEngines.push_back(new DSPDeviceSourceEngine(m_deviceSourceEnginesUIDSequence));
     m_deviceSourceEnginesUIDSequence++;
     return m_deviceSourceEngines.back();
 }
getAMBEEngine()
AMBEEngine* DSPEngine::getAMBEEngine () inline
Definition at line 56 of file dspengine.h.
Referenced by WebAPIAdapterGUI::instanceAMBEDevicesDelete(), WebAPIAdapterSrv::instanceAMBEDevicesDelete(), WebAPIAdapterSrv::instanceAMBEDevicesPatch(), WebAPIAdapterGUI::instanceAMBEDevicesPatch(), WebAPIAdapterGUI::instanceAMBEDevicesPut(), WebAPIAdapterSrv::instanceAMBEDevicesPut(), WebAPIAdapterGUI::instanceAMBESerialGet(), WebAPIAdapterSrv::instanceAMBESerialGet(), MainCore::MainCore(), MainWindow::MainWindow(), and MainWindow::on_action_AMBE_triggered().
 { return &m_ambeEngine; }
getAudioDeviceManager()
AudioDeviceManager* DSPEngine::getAudioDeviceManager () inline
Definition at line 55 of file dspengine.h.
Referenced by AMDemod::AMDemod(), AMMod::AMMod(), WFMDemod::applySettings(), AMDemod::applySettings(), UDPSink::applySettings(), NFMDemod::applySettings(), DSDDemod::applySettings(), BFMDemod::applySettings(), WFMMod::applySettings(), AMMod::applySettings(), NFMMod::applySettings(), SSBDemod::applySettings(), FreeDVMod::applySettings(), SSBMod::applySettings(), FreeDVDemod::applySettings(), DATVDemod::applySettings(), BFMDemod::BFMDemod(), DATVDemod::DATVDemod(), DSDDemod::DSDDemod(), FreeDVDemod::FreeDVDemod(), FreeDVMod::FreeDVMod(), WebAPIAdapterGUI::instanceAudioGet(), WebAPIAdapterSrv::instanceAudioGet(), WebAPIAdapterGUI::instanceAudioInputCleanupPatch(), WebAPIAdapterSrv::instanceAudioInputCleanupPatch(), WebAPIAdapterGUI::instanceAudioInputDelete(), WebAPIAdapterSrv::instanceAudioInputDelete(), WebAPIAdapterGUI::instanceAudioInputPatch(), WebAPIAdapterSrv::instanceAudioInputPatch(), WebAPIAdapterGUI::instanceAudioOutputCleanupPatch(), WebAPIAdapterSrv::instanceAudioOutputCleanupPatch(), WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterGUI::instanceAudioOutputPatch(), WebAPIAdapterSrv::instanceAudioOutputPatch(), MainCore::MainCore(), MainWindow::MainWindow(), NFMDemod::NFMDemod(), NFMMod::NFMMod(), MainWindow::on_action_Audio_triggered(), FCDProPlusInput::openFCDAudio(), FCDProInput::openFCDAudio(), SSBDemod::SSBDemod(), SSBMod::SSBMod(), WFMDemod::WFMDemod(), WFMMod::WFMMod(), AMDemod::~AMDemod(), AMMod::~AMMod(), BFMDemod::~BFMDemod(), DATVDemod::~DATVDemod(), DSDDemod::~DSDDemod(), FreeDVDemod::~FreeDVDemod(), FreeDVMod::~FreeDVMod(), NFMDemod::~NFMDemod(), NFMMod::~NFMMod(), SSBDemod::~SSBDemod(), SSBMod::~SSBMod(), UDPSink::~UDPSink(), WFMDemod::~WFMDemod(), and WFMMod::~WFMMod().
 { return &m_audioDeviceManager; }
getDefaultAudioSampleRate()
unsigned int DSPEngine::getDefaultAudioSampleRate () const inline
Definition at line 44 of file dspengine.h.
References AudioDeviceManager::m_defaultAudioSampleRate.
 { return AudioDeviceManager::m_defaultAudioSampleRate; }
getDeviceMIMOEngineByIndex()
DSPDeviceMIMOEngine* DSPEngine::getDeviceMIMOEngineByIndex (uint deviceIndex) inline
Definition at line 67 of file dspengine.h.
 { return m_deviceMIMOEngines[deviceIndex]; }
getDeviceMIMOEngineByUID()
DSPDeviceMIMOEngine * DSPEngine::getDeviceMIMOEngineByUID (uint uid)
Definition at line 142 of file dspengine.cpp.
References m_deviceMIMOEngines.
 {
     std::vector<DSPDeviceMIMOEngine*>::iterator it = m_deviceMIMOEngines.begin();
     while (it != m_deviceMIMOEngines.end())
     {
         if ((*it)->getUID() == uid) {
             return *it;
         }
         ++it;
     }
     return nullptr;
 }
getDeviceMIMOEnginesNumber()
uint32_t DSPEngine::getDeviceMIMOEnginesNumber () const inline
Definition at line 66 of file dspengine.h.
 { return m_deviceMIMOEngines.size(); }
getDeviceSinkEngineByIndex()
DSPDeviceSinkEngine* DSPEngine::getDeviceSinkEngineByIndex (uint deviceIndex) inline
Definition at line 63 of file dspengine.h.
Referenced by LocalSource::getLocalDevice(), and LocalSource::getLocalDevices().
 { return m_deviceSinkEngines[deviceIndex]; }
getDeviceSinkEngineByUID()
DSPDeviceSinkEngine * DSPEngine::getDeviceSinkEngineByUID (uint uid)
Definition at line 126 of file dspengine.cpp.
References m_deviceSinkEngines.
 {
     std::vector<DSPDeviceSinkEngine*>::iterator it = m_deviceSinkEngines.begin();
     while (it != m_deviceSinkEngines.end())
     {
         if ((*it)->getUID() == uid) {
             return *it;
         }
         ++it;
     }
     return nullptr;
 }
getDeviceSinkEnginesNumber()
uint32_t DSPEngine::getDeviceSinkEnginesNumber () const inline
Definition at line 62 of file dspengine.h.
Referenced by LocalSource::getLocalDevices().
 { return m_deviceSinkEngines.size(); }
getDeviceSourceEngineByIndex()
DSPDeviceSourceEngine* DSPEngine::getDeviceSourceEngineByIndex (uint deviceIndex) inline
Definition at line 59 of file dspengine.h.
Referenced by LocalSink::getLocalDevice(), and LocalSink::getLocalDevices().
 { return m_deviceSourceEngines[deviceIndex]; }
getDeviceSourceEngineByUID()
DSPDeviceSourceEngine * DSPEngine::getDeviceSourceEngineByUID (uint uid)
Definition at line 110 of file dspengine.cpp.
References m_deviceSourceEngines.
 {
     std::vector<DSPDeviceSourceEngine*>::iterator it = m_deviceSourceEngines.begin();
     while (it != m_deviceSourceEngines.end())
     {
         if ((*it)->getUID() == uid) {
             return *it;
         }
         ++it;
     }
     return nullptr;
 }
getDeviceSourceEnginesNumber()
uint32_t DSPEngine::getDeviceSourceEnginesNumber () const inline
Definition at line 58 of file dspengine.h.
Referenced by LocalSink::getLocalDevices().
 { return m_deviceSourceEngines.size(); }
getDVSerialNames()
void DSPEngine::getDVSerialNames (std::vector< std::string > & deviceNames)
Definition at line 166 of file dspengine.cpp.
References AMBEEngine::getDeviceRefs(), and m_ambeEngine.
Referenced by WebAPIAdapterGUI::instanceAMBEDevicesGet(), WebAPIAdapterSrv::instanceAMBEDevicesGet(), WebAPIAdapterSrv::instanceDVSerialGet(), WebAPIAdapterGUI::instanceDVSerialGet(), WebAPIAdapterGUI::instanceDVSerialPatch(), and WebAPIAdapterSrv::instanceDVSerialPatch().
 {
     std::vector<QString> qDeviceRefs;
     m_ambeEngine.getDeviceRefs(qDeviceRefs);
     deviceNames.clear();
     for (std::vector<QString>::const_iterator it = qDeviceRefs.begin(); it != qDeviceRefs.end(); ++it) {
         deviceNames.push_back(it->toStdString());
     }
 }
getMasterTimer()
const QTimer& DSPEngine::getMasterTimer () const inline
Definition at line 84 of file dspengine.h.
Referenced by FreqTracker::FreqTracker().
 { return m_masterTimer; }
getMIMOSupport()
bool DSPEngine::getMIMOSupport () const inline
Definition at line 86 of file dspengine.h.
Referenced by MainWindow::on_action_addMIMODevice_triggered().
 { return m_mimoSupport; }
hasDVSerialSupport()
bool DSPEngine::hasDVSerialSupport ()
Definition at line 158 of file dspengine.cpp.
References AMBEEngine::getNbDevices(), and m_ambeEngine.
 {
     return m_ambeEngine.getNbDevices() > 0;
 }
instance()
DSPEngine * DSPEngine::instance () static
Definition at line 51 of file dspengine.cpp.
Referenced by AMDemod::AMDemod(), AMMod::AMMod(), WFMDemod::applySettings(), AMDemod::applySettings(), UDPSink::applySettings(), NFMDemod::applySettings(), DSDDemod::applySettings(), BFMDemod::applySettings(), WFMMod::applySettings(), AMMod::applySettings(), NFMMod::applySettings(), SSBDemod::applySettings(), FreeDVMod::applySettings(), SSBMod::applySettings(), FreeDVDemod::applySettings(), DATVDemod::applySettings(), AMModGUI::audioFeedbackSelect(), NFMModGUI::audioFeedbackSelect(), SSBModGUI::audioFeedbackSelect(), DATVDemodGUI::audioSelect(), WFMDemodGUI::audioSelect(), NFMDemodGUI::audioSelect(), AMDemodGUI::audioSelect(), SSBDemodGUI::audioSelect(), FreeDVDemodGUI::audioSelect(), BFMDemodGUI::audioSelect(), AMModGUI::audioSelect(), FreeDVModGUI::audioSelect(), NFMModGUI::audioSelect(), WFMModGUI::audioSelect(), SSBModGUI::audioSelect(), DSDDemodGUI::audioSelect(), BFMDemod::BFMDemod(), DATVDemod::DATVDemod(), DSDDemod::DSDDemod(), DSDDemod::feed(), FreeDVDemod::FreeDVDemod(), FreeDVMod::FreeDVMod(), FreqTracker::FreqTracker(), LocalSink::getLocalDevice(), LocalSource::getLocalDevice(), LocalSink::getLocalDevices(), LocalSource::getLocalDevices(), NFMDemod::NFMDemod(), NFMMod::NFMMod(), FCDProPlusInput::openFCDAudio(), FCDProInput::openFCDAudio(), SSBDemod::SSBDemod(), SSBMod::SSBMod(), WFMDemod::WFMDemod(), WFMMod::WFMMod(), AMDemod::~AMDemod(), AMMod::~AMMod(), BFMDemod::~BFMDemod(), DATVDemod::~DATVDemod(), DSDDemod::~DSDDemod(), FreeDVDemod::~FreeDVDemod(), FreeDVMod::~FreeDVMod(), NFMDemod::~NFMDemod(), NFMMod::~NFMMod(), SSBDemod::~SSBDemod(), SSBMod::~SSBMod(), UDPSink::~UDPSink(), WFMDemod::~WFMDemod(), and WFMMod::~WFMMod().
 {
     return dspEngine;
 }
pushMbeFrame()
void DSPEngine::pushMbeFrame (const unsigned char * mbeFrame, int mbeRateIndex, int mbeVolumeIndex, unsigned char channels, bool useHP, int upsampling, AudioFifo * audioFifo)
Definition at line 177 of file dspengine.cpp.
References m_ambeEngine, and AMBEEngine::pushMbeFrame().
Referenced by DSDDemod::feed().
 {
     m_ambeEngine.pushMbeFrame(mbeFrame, mbeRateIndex, mbeVolumeIndex, channels, useHP, upsampling, audioFifo);
 }
removeLastDeviceMIMOEngine()
void DSPEngine::removeLastDeviceMIMOEngine ()
Definition at line 99 of file dspengine.cpp.
References m_deviceMIMOEngines, and m_deviceMIMOEnginesUIDSequence.
Referenced by MainWindow::removeLastDevice().
 {
     if (m_deviceMIMOEngines.size() > 0)
     {
         DSPDeviceMIMOEngine *lastDeviceEngine = m_deviceMIMOEngines.back();
         delete lastDeviceEngine;
         m_deviceMIMOEngines.pop_back();
         m_deviceMIMOEnginesUIDSequence--;
     }
 }
removeLastDeviceSinkEngine()
void DSPEngine::removeLastDeviceSinkEngine ()
Definition at line 81 of file dspengine.cpp.
References m_deviceSinkEngines, and m_deviceSinkEnginesUIDSequence.
Referenced by MainCore::removeLastDevice(), and MainWindow::removeLastDevice().
 {
     if (m_deviceSinkEngines.size() > 0)
     {
         DSPDeviceSinkEngine *lastDeviceEngine = m_deviceSinkEngines.back();
         delete lastDeviceEngine;
         m_deviceSinkEngines.pop_back();
         m_deviceSinkEnginesUIDSequence--;
     }
 }
removeLastDeviceSourceEngine()
void DSPEngine::removeLastDeviceSourceEngine ()
Definition at line 63 of file dspengine.cpp.
References m_deviceSourceEngines, and m_deviceSourceEnginesUIDSequence.
Referenced by MainCore::removeLastDevice(), and MainWindow::removeLastDevice().
 {
     if (m_deviceSourceEngines.size() > 0)
     {
         DSPDeviceSourceEngine *lastDeviceEngine = m_deviceSourceEngines.back();
         delete lastDeviceEngine;
         m_deviceSourceEngines.pop_back();
         m_deviceSourceEnginesUIDSequence--;
     }
 }
setDVSerialSupport()
void DSPEngine::setDVSerialSupport (bool support)
Definition at line 163 of file dspengine.cpp.
Referenced by WebAPIAdapterGUI::instanceDVSerialPatch(), and WebAPIAdapterSrv::instanceDVSerialPatch().
 { (void) support; }
setMIMOSupport()
void DSPEngine::setMIMOSupport (bool mimoSupport) inline
Definition at line 85 of file dspengine.h.
Referenced by MainCore::MainCore(), and MainWindow::MainWindow().
 { m_mimoSupport = mimoSupport; }
Member Data Documentation
m_ambeEngine
AMBEEngine DSPEngine::m_ambeEngine private
Definition at line 101 of file dspengine.h.
Referenced by getDVSerialNames(), hasDVSerialSupport(), and pushMbeFrame().
m_audioDeviceManager
AudioDeviceManager DSPEngine::m_audioDeviceManager private
Definition at line 95 of file dspengine.h.
m_audioInputDeviceIndex
int DSPEngine::m_audioInputDeviceIndex private
Definition at line 96 of file dspengine.h.
m_audioOutputDeviceIndex
int DSPEngine::m_audioOutputDeviceIndex private
Definition at line 97 of file dspengine.h.
m_deviceMIMOEngines
std::vector<DSPDeviceMIMOEngine*> DSPEngine::m_deviceMIMOEngines private
Definition at line 93 of file dspengine.h.
Referenced by addDeviceMIMOEngine(), getDeviceMIMOEngineByUID(), and removeLastDeviceMIMOEngine().
m_deviceMIMOEnginesUIDSequence
uint DSPEngine::m_deviceMIMOEnginesUIDSequence private
Definition at line 94 of file dspengine.h.
Referenced by addDeviceMIMOEngine(), and removeLastDeviceMIMOEngine().
m_deviceSinkEngines
std::vector<DSPDeviceSinkEngine*> DSPEngine::m_deviceSinkEngines private
Definition at line 91 of file dspengine.h.
Referenced by addDeviceSinkEngine(), getDeviceSinkEngineByUID(), and removeLastDeviceSinkEngine().
m_deviceSinkEnginesUIDSequence
uint DSPEngine::m_deviceSinkEnginesUIDSequence private
Definition at line 92 of file dspengine.h.
Referenced by addDeviceSinkEngine(), and removeLastDeviceSinkEngine().
m_deviceSourceEngines
std::vector<DSPDeviceSourceEngine*> DSPEngine::m_deviceSourceEngines private
Definition at line 89 of file dspengine.h.
Referenced by addDeviceSourceEngine(), getDeviceSourceEngineByUID(), removeLastDeviceSourceEngine(), and ~DSPEngine().
m_deviceSourceEnginesUIDSequence
uint DSPEngine::m_deviceSourceEnginesUIDSequence private
Definition at line 90 of file dspengine.h.
Referenced by addDeviceSourceEngine(), and removeLastDeviceSourceEngine().
m_dvSerialSupport
bool DSPEngine::m_dvSerialSupport private
Definition at line 99 of file dspengine.h.
Referenced by DSPEngine().
m_masterTimer
QTimer DSPEngine::m_masterTimer private
Definition at line 98 of file dspengine.h.
Referenced by DSPEngine().
m_mimoSupport
bool DSPEngine::m_mimoSupport private
Definition at line 100 of file dspengine.h.
Referenced by DSPEngine().
The documentation for this class was generated from the following files:
sdrbase/dsp/dspengine.h
sdrbase/dsp/dspengine.cpp