SDRAngel: Serializable Class Reference
Serializable Class Reference abstract
#include <serializable.h>
Public Member Functions
virtual ~Serializable ()
virtual QByteArray serialize () const =0
virtual bool deserialize (const QByteArray &data)=0
Detailed Description
Definition at line 21 of file serializable.h.
Constructor & Destructor Documentation
~Serializable()
virtual Serializable::~Serializable () inline virtual
Definition at line 24 of file serializable.h.
References deserialize(), and serialize().
 {}
Member Function Documentation
deserialize()
virtual bool Serializable::deserialize (const QByteArray & data) pure virtual
Implemented in ChannelMarker, GLScopeGUI, CWKeyerGUI, and GLSpectrumGUI.
Referenced by LoRaDemodSettings::deserialize(), WFMDemodSettings::deserialize(), BFMDemodSettings::deserialize(), AMDemodSettings::deserialize(), SSBDemodSettings::deserialize(), NFMDemodSettings::deserialize(), ChannelAnalyzerSettings::deserialize(), FreqTrackerSettings::deserialize(), FreeDVDemodSettings::deserialize(), DSDDemodSettings::deserialize(), AMModSettings::deserialize(), WFMModSettings::deserialize(), NFMModSettings::deserialize(), UDPSourceSettings::deserialize(), FreeDVModSettings::deserialize(), SSBModSettings::deserialize(), UDPSinkSettings::deserialize(), ATVModSettings::deserialize(), DATVDemodSettings::deserialize(), ChannelMarker::getStreamIndex(), and ~Serializable().
serialize()
virtual QByteArray Serializable::serialize () const pure virtual
Implemented in ChannelMarker, GLScopeGUI, CWKeyerGUI, and GLSpectrumGUI.
Referenced by ChannelMarker::getStreamIndex(), LoRaDemodSettings::serialize(), WFMDemodSettings::serialize(), BFMDemodSettings::serialize(), AMDemodSettings::serialize(), NFMDemodSettings::serialize(), SSBDemodSettings::serialize(), ChannelAnalyzerSettings::serialize(), FreqTrackerSettings::serialize(), FreeDVDemodSettings::serialize(), DSDDemodSettings::serialize(), AMModSettings::serialize(), WFMModSettings::serialize(), NFMModSettings::serialize(), UDPSourceSettings::serialize(), FreeDVModSettings::serialize(), SSBModSettings::serialize(), UDPSinkSettings::serialize(), ATVModSettings::serialize(), ATVDemodSettings::serialize(), DATVDemodSettings::serialize(), and ~Serializable().
The documentation for this class was generated from the following file:
sdrbase/settings/serializable.h