SDRAngel: Bladerf1Output::MsgConfigureBladerf1 Class Reference
Bladerf1Output::MsgConfigureBladerf1 Class Reference
#include <bladerf1output.h>
Public Member Functions
const BladeRF1OutputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureBladerf1 * create (const BladeRF1OutputSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureBladerf1 (const BladeRF1OutputSettings &settings, bool force)
Private Attributes
BladeRF1OutputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 38 of file bladerf1output.h.
Constructor & Destructor Documentation
MsgConfigureBladerf1()
Bladerf1Output::MsgConfigureBladerf1::MsgConfigureBladerf1 (const BladeRF1OutputSettings & settings, bool force) inline private
Definition at line 54 of file bladerf1output.h.
Referenced by create().
                                                                                  :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureBladerf1* Bladerf1Output::MsgConfigureBladerf1::create (const BladeRF1OutputSettings & settings, bool force) inline static
Definition at line 45 of file bladerf1output.h.
References MsgConfigureBladerf1().
Referenced by Bladerf1Output::deserialize(), Bladerf1Output::setCenterFrequency(), Bladerf1OutputGui::updateHardware(), and Bladerf1Output::webapiSettingsPutPatch().
         {
             return new MsgConfigureBladerf1(settings, force);
         }
getForce()
bool Bladerf1Output::MsgConfigureBladerf1::getForce () const inline
Definition at line 43 of file bladerf1output.h.
References m_force.
Referenced by Bladerf1Output::handleMessage().
 { return m_force; }
getSettings()
const BladeRF1OutputSettings& Bladerf1Output::MsgConfigureBladerf1::getSettings () const inline
Definition at line 42 of file bladerf1output.h.
References m_settings.
Referenced by Bladerf1OutputGui::handleMessage(), and Bladerf1Output::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool Bladerf1Output::MsgConfigureBladerf1::m_force private
Definition at line 52 of file bladerf1output.h.
Referenced by getForce().
m_settings
BladeRF1OutputSettings Bladerf1Output::MsgConfigureBladerf1::m_settings private
Definition at line 51 of file bladerf1output.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesink/bladerf1output/bladerf1output.h