SDRAngel: ScopeVis::MsgScopeVisNGMoveTrace Class Reference
ScopeVis::MsgScopeVisNGMoveTrace Class Reference
Public Member Functions
uint32_t getTraceIndex () const
bool getMoveUp () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgScopeVisNGMoveTrace * create (uint32_t traceIndex, bool moveUpElseDown)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgScopeVisNGMoveTrace (uint32_t traceIndex, bool moveUpElseDown)
Private Attributes
uint32_t m_traceIndex
bool m_moveUpElseDown
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 471 of file scopevis.h.
Constructor & Destructor Documentation
MsgScopeVisNGMoveTrace()
ScopeVis::MsgScopeVisNGMoveTrace::MsgScopeVisNGMoveTrace (uint32_t traceIndex, bool moveUpElseDown) inline private
Definition at line 489 of file scopevis.h.
                                                                          :
             m_traceIndex(traceIndex),
             m_moveUpElseDown(moveUpElseDown)
         {}
Member Function Documentation
create()
static MsgScopeVisNGMoveTrace* ScopeVis::MsgScopeVisNGMoveTrace::create (uint32_t traceIndex, bool moveUpElseDown) inline static
Definition at line 475 of file scopevis.h.
Referenced by ScopeVis::moveTrace().
         {
             return new MsgScopeVisNGMoveTrace(traceIndex, moveUpElseDown);
         }
getMoveUp()
bool ScopeVis::MsgScopeVisNGMoveTrace::getMoveUp () const inline
Definition at line 483 of file scopevis.h.
Referenced by ScopeVis::handleMessage().
 { return m_moveUpElseDown; }
getTraceIndex()
uint32_t ScopeVis::MsgScopeVisNGMoveTrace::getTraceIndex () const inline
Definition at line 482 of file scopevis.h.
Referenced by ScopeVis::handleMessage().
 { return m_traceIndex; }
Member Data Documentation
m_moveUpElseDown
bool ScopeVis::MsgScopeVisNGMoveTrace::m_moveUpElseDown private
Definition at line 487 of file scopevis.h.
m_traceIndex
uint32_t ScopeVis::MsgScopeVisNGMoveTrace::m_traceIndex private
Definition at line 486 of file scopevis.h.
The documentation for this class was generated from the following file:
sdrgui/dsp/scopevis.h