SDRAngel: SDRPlayPlugin Class Reference
SDRPlayPlugin Class Reference
#include <sdrplayplugin.h>
Public Member Functions
SDRPlayPlugin (QObject *parent=NULL)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "SDRplay1"
static const QString m_deviceTypeID = SDRPLAY_DEVICE_TYPE_ID
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 28 of file sdrplayplugin.h.
Constructor & Destructor Documentation
SDRPlayPlugin()
SDRPlayPlugin::SDRPlayPlugin (QObject * parent = NULL) explicit
Definition at line 42 of file sdrplayplugin.cpp.
                                             :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSourcePluginInstance()
DeviceSampleSource * SDRPlayPlugin::createSampleSourcePluginInstance (const QString & sourceId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 124 of file sdrplayplugin.cpp.
References m_deviceTypeID.
 {
     if (sourceId == m_deviceTypeID)
     {
         SDRPlayInput* input = new SDRPlayInput(deviceAPI);
         return input;
     }
     else
     {
         return 0;
     }
 }
createSampleSourcePluginInstanceGUI()
PluginInstanceGUI * SDRPlayPlugin::createSampleSourcePluginInstanceGUI (const QString & sourceId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 106 of file sdrplayplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSources().
 {
     if(sourceId == m_deviceTypeID)
     {
         SDRPlayGui* gui = new SDRPlayGui(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSources()
PluginInterface::SamplingDevices SDRPlayPlugin::enumSampleSources () virtual
Reimplemented from PluginInterface.
Definition at line 57 of file sdrplayplugin.cpp.
References arg(), createSampleSourcePluginInstanceGUI(), i, m_deviceTypeID, m_hardwareID, PluginInterface::SamplingDevice::PhysicalDevice, and PluginInterface::SamplingDevice::StreamSingleRx.
 {
     SamplingDevices result;
     int count = mirisdr_get_device_count();
     char vendor[256];
     char product[256];
     char serial[256];
     for(int i = 0; i < count; i++)
     {
         vendor[0] = '\0';
         product[0] = '\0';
         serial[0] = '\0';
         if (mirisdr_get_device_usb_strings((uint32_t)i, vendor, product, serial) != 0)
         {
             continue;
         }
         qDebug("SDRPlayPlugin::enumSampleSources: found %s:%s (%s)", vendor, product, serial);
         QString displayedName(QString("SDRPlay[%1] %2").arg(i).arg(serial));
         result.append(SamplingDevice(displayedName,
                 m_hardwareID,
                 m_deviceTypeID,
                 QString(serial),
                 i,
                 PluginInterface::SamplingDevice::PhysicalDevice,
                 PluginInterface::SamplingDevice::StreamSingleRx,
                 1,
                 0));
     }
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & SDRPlayPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 47 of file sdrplayplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void SDRPlayPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 52 of file sdrplayplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSource().
 {
     pluginAPI->registerSampleSource(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString SDRPlayPlugin::m_deviceTypeID = SDRPLAY_DEVICE_TYPE_ID static
Definition at line 47 of file sdrplayplugin.h.
Referenced by createSampleSourcePluginInstance(), createSampleSourcePluginInstanceGUI(), enumSampleSources(), and initPlugin().
m_hardwareID
const QString SDRPlayPlugin::m_hardwareID = "SDRplay1" static
Definition at line 46 of file sdrplayplugin.h.
Referenced by enumSampleSources().
m_pluginDescriptor
const PluginDescriptor SDRPlayPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("SDRPlay RSP1 Input"),
    QString("4.5.2"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 50 of file sdrplayplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesource/sdrplay/sdrplayplugin.h
plugins/samplesource/sdrplay/sdrplayplugin.cpp