SDRAngel: LocalInput::MsgReportSampleRateAndFrequency Class Reference
LocalInput::MsgReportSampleRateAndFrequency Class Reference
#include <localinput.h>
Public Member Functions
int getSampleRate () const
int getCenterFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportSampleRateAndFrequency * create (int sampleRate, qint64 centerFrequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportSampleRateAndFrequency (int sampleRate, qint64 centerFrequency)
Protected Attributes
int m_sampleRate
qint64 m_centerFrequency
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 103 of file localinput.h.
Constructor & Destructor Documentation
MsgReportSampleRateAndFrequency()
LocalInput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency (int sampleRate, qint64 centerFrequency) inline protected
Definition at line 118 of file localinput.h.
References LocalInput::deserialize(), LocalInput::destroy(), LocalInput::getCenterFrequency(), LocalInput::getDeviceDescription(), LocalInput::getSampleRate(), LocalInput::handleMessage(), LocalInput::init(), LocalInput::LocalInput(), LocalInput::serialize(), LocalInput::setCenterFrequency(), LocalInput::setMessageQueueToGUI(), LocalInput::setSampleRate(), LocalInput::start(), LocalInput::stop(), LocalInput::webapiReportGet(), LocalInput::webapiRun(), LocalInput::webapiRunGet(), LocalInput::webapiSettingsGet(), LocalInput::webapiSettingsPutPatch(), and LocalInput::~LocalInput().
                                                                                 :
             Message(),
             m_sampleRate(sampleRate),
             m_centerFrequency(centerFrequency)
         { }
Member Function Documentation
create()
static MsgReportSampleRateAndFrequency* LocalInput::MsgReportSampleRateAndFrequency::create (int sampleRate, qint64 centerFrequency) inline static
Definition at line 110 of file localinput.h.
Referenced by LocalInput::setCenterFrequency(), and LocalInput::setSampleRate().
{
             return new MsgReportSampleRateAndFrequency(sampleRate, centerFrequency);
         }
getCenterFrequency()
int LocalInput::MsgReportSampleRateAndFrequency::getCenterFrequency () const inline
Definition at line 108 of file localinput.h.
References LocalInput::m_centerFrequency.
Referenced by LocalInputGui::handleMessage().
 { return m_centerFrequency; }
getSampleRate()
int LocalInput::MsgReportSampleRateAndFrequency::getSampleRate () const inline
Definition at line 107 of file localinput.h.
References LocalInput::m_sampleRate.
Referenced by LocalInputGui::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_centerFrequency
qint64 LocalInput::MsgReportSampleRateAndFrequency::m_centerFrequency protected
Definition at line 116 of file localinput.h.
m_sampleRate
int LocalInput::MsgReportSampleRateAndFrequency::m_sampleRate protected
Definition at line 115 of file localinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/localinput/localinput.h