SDRAngel: MainCore::MsgSavePreset Class Reference
MainCore::MsgSavePreset Class Reference
Public Member Functions
Preset * getPreset () const
int getDeviceSetIndex () const
bool isNewPreset () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgSavePreset * create (Preset *preset, int deviceSetIndex, bool newPreset)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgSavePreset (Preset *preset, int deviceSetIndex, bool newPreset)
Private Attributes
Preset * m_preset
int m_deviceSetIndex
bool m_newPreset
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 98 of file maincore.h.
Constructor & Destructor Documentation
MsgSavePreset()
MainCore::MsgSavePreset::MsgSavePreset (Preset * preset, int deviceSetIndex, bool newPreset) inline private
Definition at line 116 of file maincore.h.
                                                                           :
             Message(),
             m_preset(preset),
             m_deviceSetIndex(deviceSetIndex),
             m_newPreset(newPreset)
         { }
Member Function Documentation
create()
static MsgSavePreset* MainCore::MsgSavePreset::create (Preset * preset, int deviceSetIndex, bool newPreset) inline static
Definition at line 106 of file maincore.h.
Referenced by WebAPIAdapterSrv::instancePresetPost(), and WebAPIAdapterSrv::instancePresetPut().
         {
             return new MsgSavePreset(preset, deviceSetIndex, newPreset);
         }
getDeviceSetIndex()
int MainCore::MsgSavePreset::getDeviceSetIndex () const inline
Definition at line 103 of file maincore.h.
Referenced by MainCore::handleMessage().
 { return m_deviceSetIndex; }
getPreset()
Preset* MainCore::MsgSavePreset::getPreset () const inline
Definition at line 102 of file maincore.h.
Referenced by MainCore::handleMessage().
 { return m_preset; }
isNewPreset()
bool MainCore::MsgSavePreset::isNewPreset () const inline
Definition at line 104 of file maincore.h.
 { return m_newPreset; }
Member Data Documentation
m_deviceSetIndex
int MainCore::MsgSavePreset::m_deviceSetIndex private
Definition at line 113 of file maincore.h.
m_newPreset
bool MainCore::MsgSavePreset::m_newPreset private
Definition at line 114 of file maincore.h.
m_preset
Preset* MainCore::MsgSavePreset::m_preset private
Definition at line 112 of file maincore.h.
The documentation for this class was generated from the following file:
sdrsrv/maincore.h