SDRAngel: LocalOutputPlugin Class Reference
LocalOutputPlugin Class Reference
#include <localoutputplugin.h>
Public Member Functions
LocalOutputPlugin (QObject *parent=nullptr)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "LocalOutput"
static const QString m_deviceTypeID = LOCALOUTPUT_DEVICE_TYPE_ID
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 28 of file localoutputplugin.h.
Constructor & Destructor Documentation
LocalOutputPlugin()
LocalOutputPlugin::LocalOutputPlugin (QObject * parent = nullptr) explicit
Definition at line 42 of file localoutputplugin.cpp.
                                                     :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSinkPluginInstance()
DeviceSampleSink * LocalOutputPlugin::createSampleSinkPluginInstance (const QString & sinkId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 105 of file localoutputplugin.cpp.
References m_deviceTypeID.
 {
     if (sinkId == m_deviceTypeID)
     {
         LocalOutput* output = new LocalOutput(deviceAPI);
         return output;
     }
     else
     {
         return 0;
     }
 }
createSampleSinkPluginInstanceGUI()
PluginInstanceGUI * LocalOutputPlugin::createSampleSinkPluginInstanceGUI (const QString & sinkId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 87 of file localoutputplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSinks().
 {
     if(sinkId == m_deviceTypeID)
     {
         LocalOutputGui* gui = new LocalOutputGui(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSinks()
PluginInterface::SamplingDevices LocalOutputPlugin::enumSampleSinks () virtual
Reimplemented from PluginInterface.
Definition at line 57 of file localoutputplugin.cpp.
References PluginInterface::SamplingDevice::BuiltInDevice, createSampleSinkPluginInstanceGUI(), m_deviceTypeID, m_hardwareID, and PluginInterface::SamplingDevice::StreamSingleTx.
 {
     SamplingDevices result;
     result.append(SamplingDevice(
             "LocalOutput",
             m_hardwareID,
             m_deviceTypeID,
             QString::null,
             0,
             PluginInterface::SamplingDevice::BuiltInDevice,
             PluginInterface::SamplingDevice::StreamSingleTx,
             1,
             0));
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & LocalOutputPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 47 of file localoutputplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void LocalOutputPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 52 of file localoutputplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSink().
 {
     pluginAPI->registerSampleSink(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString LocalOutputPlugin::m_deviceTypeID = LOCALOUTPUT_DEVICE_TYPE_ID static
Definition at line 47 of file localoutputplugin.h.
Referenced by createSampleSinkPluginInstance(), createSampleSinkPluginInstanceGUI(), enumSampleSinks(), and initPlugin().
m_hardwareID
const QString LocalOutputPlugin::m_hardwareID = "LocalOutput" static
Definition at line 46 of file localoutputplugin.h.
Referenced by enumSampleSinks().
m_pluginDescriptor
const PluginDescriptor LocalOutputPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("Local device output"),
    QString("4.8.0"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 50 of file localoutputplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesink/localoutput/localoutputplugin.h
plugins/samplesink/localoutput/localoutputplugin.cpp