SDRAngel: UDPSinkFEC Class Reference
UDPSinkFEC Class Reference
#include <udpsinkfec.h>
Inherits QObject.
Public Member Functions
UDPSinkFEC ()
~UDPSinkFEC ()
void start ()
void stop ()
void write (const SampleVector::iterator &begin, uint32_t sampleChunkSize)
std::string error ()
void setSampleRate (uint32_t sampleRate)
void setNbBlocksFEC (uint32_t nbBlocksFEC)
void setTxDelay (float txDelayRatio)
void setRemoteAddress (const QString &address, uint16_t port)
operator bool () const
Static Public Attributes
static const uint32_t m_udpSize = 512
Size of UDP block in number of bytes.
static const uint32_t m_nbOriginalBlocks = 128
Number of original blocks in a protected block sequence.
Private Attributes
std::string m_error
uint32_t m_sampleRate
sample rate in Hz
uint32_t m_nbSamples
total number of samples sent int the last frame
QHostAddress m_ownAddress
CRC64 m_crc64
uint8_t * m_bufMeta
uint8_t * m_buf
RemoteMetaDataFEC m_currentMetaFEC
Meta data for current frame.
uint32_t m_nbBlocksFEC
Variable number of FEC blocks.
float m_txDelayRatio
Delay in ratio of nominal frame period.
uint32_t m_txDelay
Delay in microseconds (usleep) between each sending of an UDP datagram.
RemoteSuperBlock m_txBlocks [4][256]
UDP blocks to send with original data + FEC.
RemoteSuperBlock m_superBlock
current super block being built
int m_txBlockIndex
Current index in blocks to transmit in the Tx row.
int m_txBlocksIndex
Current index of Tx blocks row.
uint16_t m_frameCount
transmission frame count
int m_sampleIndex
Current sample index in protected block data.
UDPSinkFECWorker * m_udpWorker
QString m_remoteAddress
uint16_t m_remotePort
Detailed Description
Definition at line 34 of file udpsinkfec.h.
Constructor & Destructor Documentation
UDPSinkFEC()
UDPSinkFEC::UDPSinkFEC ()
Construct UDP sink
Definition at line 30 of file udpsinkfec.cpp.
References RemoteMetaDataFEC::init(), m_buf, m_bufMeta, m_currentMetaFEC, m_superBlock, m_txBlocks, and m_udpSize.
                        :
     m_sampleRate(48000),
     m_nbSamples(0),
     m_nbBlocksFEC(0),
     m_txDelayRatio(0.0),
     m_txDelay(0),
     m_txBlockIndex(0),
     m_txBlocksIndex(0),
     m_frameCount(0),
     m_sampleIndex(0),
     m_udpWorker(0),
     m_remoteAddress("127.0.0.1"),
     m_remotePort(9090)
 {
     memset((char *) m_txBlocks, 0, 4*256*sizeof(RemoteSuperBlock));
     memset((char *) &m_superBlock, 0, sizeof(RemoteSuperBlock));
     m_currentMetaFEC.init();
     m_bufMeta = new uint8_t[m_udpSize];
     m_buf = new uint8_t[m_udpSize];
 }
~UDPSinkFEC()
UDPSinkFEC::~UDPSinkFEC ()
Destroy UDP sink
Definition at line 51 of file udpsinkfec.cpp.
References m_buf, and m_bufMeta.
 {
     delete[] m_buf;
     delete[] m_bufMeta;
 }
Member Function Documentation
error()
std::string UDPSinkFEC::error () inline
Return the last error, or return an empty string if there is no error.
Definition at line 58 of file udpsinkfec.h.
References m_error, setNbBlocksFEC(), setRemoteAddress(), setSampleRate(), and setTxDelay().
     {
         std::string ret(m_error);
         m_error.clear();
         return ret;
     }
operator bool()
UDPSinkFEC::operator bool () const inline
Return true if the stream is OK, return false if there is an error.
Definition at line 73 of file udpsinkfec.h.
References m_error.
     {
         return m_error.empty();
     }
setNbBlocksFEC()
void UDPSinkFEC::setNbBlocksFEC (uint32_t nbBlocksFEC)
Definition at line 87 of file udpsinkfec.cpp.
References m_nbBlocksFEC, m_txDelayRatio, and setTxDelay().
Referenced by error(), and RemoteOutputThread::setNbBlocksFEC().
 {
     qDebug() << "UDPSinkFEC::setNbBlocksFEC: nbBlocksFEC: " << nbBlocksFEC;
     m_nbBlocksFEC = nbBlocksFEC;
     setTxDelay(m_txDelayRatio);
 }
setRemoteAddress()
void UDPSinkFEC::setRemoteAddress (const QString & address, uint16_t port)
Definition at line 101 of file udpsinkfec.cpp.
References m_remoteAddress, m_remotePort, m_udpWorker, and UDPSinkFECWorker::setRemoteAddress().
Referenced by error(), and RemoteOutputThread::setDataAddress().
 {
     qDebug() << "UDPSinkFEC::setRemoteAddress: address: " << address << " port: " << port;
     m_remoteAddress = address;
     m_remotePort = port;
     if (m_udpWorker) {
         m_udpWorker->setRemoteAddress(m_remoteAddress, m_remotePort);
     }
 }
setSampleRate()
void UDPSinkFEC::setSampleRate (uint32_t sampleRate)
Set sample rate given in S/s
Definition at line 94 of file udpsinkfec.cpp.
References m_sampleRate, m_txDelayRatio, and setTxDelay().
Referenced by error(), and RemoteOutputThread::setSamplerate().
 {
     qDebug() << "UDPSinkFEC::setSampleRate: sampleRate: " << sampleRate;
     m_sampleRate = sampleRate;
     setTxDelay(m_txDelayRatio);
 }
setTxDelay()
void UDPSinkFEC::setTxDelay (float txDelayRatio)
Definition at line 74 of file udpsinkfec.cpp.
References m_txDelayRatio.
Referenced by error(), setNbBlocksFEC(), setSampleRate(), and RemoteOutputThread::setTxDelay().
 {
     // delay is calculated from the fraction of the nominal UDP block process time
     // frame size: 127 * (126 or 63 samples depending on I or Q sample bytes of 2 or 4 bytes respectively)
     // divided by sample rate gives the frame process time
     // divided by the number of actual blocks including FEC blocks gives the block (i.e. UDP block) process time
     m_txDelayRatio = txDelayRatio;
     int samplesPerBlock = RemoteNbBytesPerBlock / (SDR_RX_SAMP_SZ <= 16 ? 4 : 8);
     double delay = ((127*samplesPerBlock*txDelayRatio) / m_sampleRate)/(128 + m_nbBlocksFEC);
     m_txDelay = delay * 1e6;
     qDebug() << "UDPSinkFEC::setTxDelay: txDelay: " << txDelayRatio << " m_txDelay: " << m_txDelay << " us";
 }
start()
void UDPSinkFEC::start ()
Definition at line 57 of file udpsinkfec.cpp.
References m_remoteAddress, m_remotePort, m_udpWorker, UDPSinkFECWorker::setRemoteAddress(), and UDPSinkFECWorker::startStop().
Referenced by RemoteOutputThread::startWork().
 {
     m_udpWorker = new UDPSinkFECWorker();
     m_udpWorker->setRemoteAddress(m_remoteAddress, m_remotePort);
     m_udpWorker->startStop(true);
 }
stop()
void UDPSinkFEC::stop ()
Definition at line 64 of file udpsinkfec.cpp.
References m_udpWorker, and UDPSinkFECWorker::startStop().
Referenced by RemoteOutputThread::stopWork().
 {
     if (m_udpWorker)
     {
         m_udpWorker->startStop(false);
         m_udpWorker->deleteLater();
         m_udpWorker = 0;
     }
 }
write()
void UDPSinkFEC::write (const SampleVector::iterator & begin, uint32_t sampleChunkSize)
Write IQ samples
Definition at line 112 of file udpsinkfec.cpp.
References leansdr::crc32(), RemoteMetaDataFEC::m_centerFrequency, RemoteMetaDataFEC::m_crc32, m_currentMetaFEC, m_frameCount, m_nbBlocksFEC, RemoteMetaDataFEC::m_nbFECBlocks, m_nbOriginalBlocks, RemoteMetaDataFEC::m_nbOriginalBlocks, RemoteMetaDataFEC::m_sampleBits, RemoteMetaDataFEC::m_sampleBytes, RemoteMetaDataFEC::m_sampleRate, m_sampleRate, m_superBlock, RemoteMetaDataFEC::m_tv_sec, RemoteMetaDataFEC::m_tv_usec, m_txBlockIndex, m_txBlocks, m_txBlocksIndex, TimeUtil::nowus(), and SDR_RX_SAMP_SZ.
Referenced by RemoteOutputThread::tick().
 {
     const SampleVector::iterator end = begin + sampleChunkSize;
     SampleVector::iterator it = begin;
     while (it != end)
     {
         int inRemainingSamples = end - it;
         if (m_txBlockIndex == 0) // Tx block index 0 is a block with only meta data
         {
             RemoteMetaDataFEC metaData;
             uint64_t ts_usecs = TimeUtil::nowus();
             metaData.m_centerFrequency = 0; // frequency not set by stream
             metaData.m_sampleRate = m_sampleRate;
             metaData.m_sampleBytes = (SDR_RX_SAMP_SZ <= 16 ? 2 : 4);
             metaData.m_sampleBits = SDR_RX_SAMP_SZ;
             metaData.m_nbOriginalBlocks = m_nbOriginalBlocks;
             metaData.m_nbFECBlocks = m_nbBlocksFEC;
             metaData.m_tv_sec = ts_usecs / 1000000UL;
             metaData.m_tv_usec = ts_usecs % 1000000UL;
             boost::crc_32_type crc32;
             crc32.process_bytes(&metaData, sizeof(RemoteMetaDataFEC)-4);
             metaData.m_crc32 = crc32.checksum();
             memset((char *) &m_superBlock, 0, sizeof(m_superBlock));
             m_superBlock.m_header.m_frameIndex = m_frameCount;
             m_superBlock.m_header.m_blockIndex = m_txBlockIndex;
             m_superBlock.m_header.m_sampleBytes = (SDR_RX_SAMP_SZ <= 16 ? 2 : 4);
             m_superBlock.m_header.m_sampleBits = SDR_RX_SAMP_SZ;
             RemoteMetaDataFEC *destMeta = (RemoteMetaDataFEC *) &m_superBlock.m_protectedBlock;
             *destMeta = metaData;
             if (!(metaData == m_currentMetaFEC))
             {
                 qDebug() << "UDPSinkFEC::write: meta: "
                         << "|" << metaData.m_centerFrequency
                         << ":" << metaData.m_sampleRate
                         << ":" << (int) (metaData.m_sampleBytes & 0xF)
                         << ":" << (int) metaData.m_sampleBits
                         << "|" << (int) metaData.m_nbOriginalBlocks
                         << ":" << (int) metaData.m_nbFECBlocks
                         << "|" << metaData.m_tv_sec
                         << ":" << metaData.m_tv_usec
                         << "|";
                 m_currentMetaFEC = metaData;
             }
             m_txBlocks[m_txBlocksIndex][0] = m_superBlock;
             m_txBlockIndex = 1; // next Tx block with data
         }
         int samplesPerBlock = RemoteNbBytesPerBlock / (SDR_RX_SAMP_SZ <= 16 ? 4 : 8); // two I or Q samples
         if (m_sampleIndex + inRemainingSamples < samplesPerBlock) // there is still room in the current super block
         {
             memcpy((char *) &m_superBlock.m_protectedBlock.buf[m_sampleIndex*sizeof(Sample)],
                     (const char *) &(*it),
                     inRemainingSamples * sizeof(Sample));
             m_sampleIndex += inRemainingSamples;
             it = end; // all input samples are consumed
         }
         else // complete super block and initiate the next if not end of frame
         {
             memcpy((char *) &m_superBlock.m_protectedBlock.buf[m_sampleIndex*sizeof(Sample)],
                     (const char *) &(*it),
                     (samplesPerBlock - m_sampleIndex) * sizeof(Sample));
             it += samplesPerBlock - m_sampleIndex;
             m_sampleIndex = 0;
             m_superBlock.m_header.m_frameIndex = m_frameCount;
             m_superBlock.m_header.m_blockIndex = m_txBlockIndex;
             m_superBlock.m_header.m_sampleBytes = (SDR_RX_SAMP_SZ <= 16 ? 2 : 4);
             m_superBlock.m_header.m_sampleBits = SDR_RX_SAMP_SZ;
             m_txBlocks[m_txBlocksIndex][m_txBlockIndex] =  m_superBlock;
             if (m_txBlockIndex == m_nbOriginalBlocks - 1) // frame complete
             {
                 int nbBlocksFEC = m_nbBlocksFEC;
                 int txDelay = m_txDelay;
                 if (m_udpWorker) {
                     m_udpWorker->pushTxFrame(m_txBlocks[m_txBlocksIndex], nbBlocksFEC, txDelay, m_frameCount);
                 }
                 m_txBlocksIndex = (m_txBlocksIndex + 1) % 4;
                 m_txBlockIndex = 0;
                 m_frameCount++;
             }
             else
             {
                 m_txBlockIndex++;
             }
         }
     }
 }
Member Data Documentation
m_buf
uint8_t* UDPSinkFEC::m_buf private
Definition at line 88 of file udpsinkfec.h.
Referenced by UDPSinkFEC(), and ~UDPSinkFEC().
m_bufMeta
uint8_t* UDPSinkFEC::m_bufMeta private
Definition at line 87 of file udpsinkfec.h.
Referenced by UDPSinkFEC(), and ~UDPSinkFEC().
m_crc64
CRC64 UDPSinkFEC::m_crc64 private
Definition at line 86 of file udpsinkfec.h.
m_currentMetaFEC
RemoteMetaDataFEC UDPSinkFEC::m_currentMetaFEC private
Meta data for current frame.
Definition at line 90 of file udpsinkfec.h.
Referenced by UDPSinkFEC(), and write().
m_error
std::string UDPSinkFEC::m_error private
Definition at line 79 of file udpsinkfec.h.
Referenced by error(), and operator bool().
m_frameCount
uint16_t UDPSinkFEC::m_frameCount private
transmission frame count
Definition at line 98 of file udpsinkfec.h.
Referenced by write().
m_nbBlocksFEC
uint32_t UDPSinkFEC::m_nbBlocksFEC private
Variable number of FEC blocks.
Definition at line 91 of file udpsinkfec.h.
Referenced by setNbBlocksFEC(), and write().
m_nbOriginalBlocks
const uint32_t UDPSinkFEC::m_nbOriginalBlocks = 128 static
Number of original blocks in a protected block sequence.
Definition at line 39 of file udpsinkfec.h.
Referenced by write().
m_nbSamples
uint32_t UDPSinkFEC::m_nbSamples private
total number of samples sent int the last frame
Definition at line 82 of file udpsinkfec.h.
m_ownAddress
QHostAddress UDPSinkFEC::m_ownAddress private
Definition at line 84 of file udpsinkfec.h.
m_remoteAddress
QString UDPSinkFEC::m_remoteAddress private
Definition at line 102 of file udpsinkfec.h.
Referenced by setRemoteAddress(), and start().
m_remotePort
uint16_t UDPSinkFEC::m_remotePort private
Definition at line 103 of file udpsinkfec.h.
Referenced by setRemoteAddress(), and start().
m_sampleIndex
int UDPSinkFEC::m_sampleIndex private
Current sample index in protected block data.
Definition at line 99 of file udpsinkfec.h.
m_sampleRate
uint32_t UDPSinkFEC::m_sampleRate private
sample rate in Hz
Definition at line 81 of file udpsinkfec.h.
Referenced by setSampleRate(), and write().
m_superBlock
RemoteSuperBlock UDPSinkFEC::m_superBlock private
current super block being built
Definition at line 95 of file udpsinkfec.h.
Referenced by UDPSinkFEC(), and write().
m_txBlockIndex
int UDPSinkFEC::m_txBlockIndex private
Current index in blocks to transmit in the Tx row.
Definition at line 96 of file udpsinkfec.h.
Referenced by write().
m_txBlocks
RemoteSuperBlock UDPSinkFEC::m_txBlocks[4][256] private
UDP blocks to send with original data + FEC.
Definition at line 94 of file udpsinkfec.h.
Referenced by UDPSinkFEC(), and write().
m_txBlocksIndex
int UDPSinkFEC::m_txBlocksIndex private
Current index of Tx blocks row.
Definition at line 97 of file udpsinkfec.h.
Referenced by write().
m_txDelay
uint32_t UDPSinkFEC::m_txDelay private
Delay in microseconds (usleep) between each sending of an UDP datagram.
Definition at line 93 of file udpsinkfec.h.
m_txDelayRatio
float UDPSinkFEC::m_txDelayRatio private
Delay in ratio of nominal frame period.
Definition at line 92 of file udpsinkfec.h.
Referenced by setNbBlocksFEC(), setSampleRate(), and setTxDelay().
m_udpSize
const uint32_t UDPSinkFEC::m_udpSize = 512 static
Size of UDP block in number of bytes.
Definition at line 38 of file udpsinkfec.h.
Referenced by UDPSinkFEC().
m_udpWorker
UDPSinkFECWorker* UDPSinkFEC::m_udpWorker private
Definition at line 101 of file udpsinkfec.h.
Referenced by setRemoteAddress(), start(), and stop().
The documentation for this class was generated from the following files:
plugins/samplesink/remoteoutput/udpsinkfec.h
plugins/samplesink/remoteoutput/udpsinkfec.cpp