SDRAngel: DeviceLimeSDRShared::MsgReportClockSourceChange Class Reference
DeviceLimeSDRShared::MsgReportClockSourceChange Class Reference
#include <devicelimesdrshared.h>
Public Member Functions
bool getExtClock () const
uint32_t getExtClockFeq () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportClockSourceChange * create (bool extClock, uint32_t m_extClockFreq)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportClockSourceChange (bool extClock, uint32_t m_extClockFreq)
Private Attributes
bool m_extClock
True if external clock source.
uint32_t m_extClockFreq
Frequency (Hz) of external clock source.
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 73 of file devicelimesdrshared.h.
Constructor & Destructor Documentation
MsgReportClockSourceChange()
DeviceLimeSDRShared::MsgReportClockSourceChange::MsgReportClockSourceChange (bool extClock, uint32_t m_extClockFreq) inline private
Definition at line 93 of file devicelimesdrshared.h.
                                          :
             Message(),
             m_extClock(extClock),
             m_extClockFreq(m_extClockFreq)
         { }
Member Function Documentation
create()
static MsgReportClockSourceChange* DeviceLimeSDRShared::MsgReportClockSourceChange::create (bool extClock, uint32_t m_extClockFreq) inline static
Definition at line 80 of file devicelimesdrshared.h.
Referenced by LimeSDROutput::applySettings(), LimeSDRInput::applySettings(), LimeSDROutput::handleMessage(), and LimeSDRInput::handleMessage().
         {
             return new MsgReportClockSourceChange(
                     extClock,
                     m_extClockFreq);
         }
getExtClock()
bool DeviceLimeSDRShared::MsgReportClockSourceChange::getExtClock () const inline
Definition at line 77 of file devicelimesdrshared.h.
Referenced by LimeSDRInputGUI::handleMessage(), LimeSDROutputGUI::handleMessage(), LimeSDROutput::handleMessage(), and LimeSDRInput::handleMessage().
 { return m_extClock; }
getExtClockFeq()
uint32_t DeviceLimeSDRShared::MsgReportClockSourceChange::getExtClockFeq () const inline
Definition at line 78 of file devicelimesdrshared.h.
Referenced by LimeSDRInputGUI::handleMessage(), LimeSDROutputGUI::handleMessage(), LimeSDROutput::handleMessage(), and LimeSDRInput::handleMessage().
 { return m_extClockFreq; }
Member Data Documentation
m_extClock
bool DeviceLimeSDRShared::MsgReportClockSourceChange::m_extClock private
True if external clock source.
Definition at line 90 of file devicelimesdrshared.h.
m_extClockFreq
uint32_t DeviceLimeSDRShared::MsgReportClockSourceChange::m_extClockFreq private
Frequency (Hz) of external clock source.
Definition at line 91 of file devicelimesdrshared.h.
The documentation for this class was generated from the following file:
devices/limesdr/devicelimesdrshared.h