SDRAngel: SoapySDRInput::MsgStartStop Class Reference
SoapySDRInput::MsgStartStop Class Reference
#include <soapysdrinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 96 of file soapysdrinput.h.
Constructor & Destructor Documentation
MsgStartStop()
SoapySDRInput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 109 of file soapysdrinput.h.
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* SoapySDRInput::MsgStartStop::create (bool startStop) inline static
Definition at line 102 of file soapysdrinput.h.
Referenced by SoapySDRInputGui::on_startStop_toggled(), and SoapySDRInput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool SoapySDRInput::MsgStartStop::getStartStop () const inline
Definition at line 100 of file soapysdrinput.h.
Referenced by SoapySDRInputGui::handleMessage(), and SoapySDRInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool SoapySDRInput::MsgStartStop::m_startStop protected
Definition at line 107 of file soapysdrinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/soapysdrinput/soapysdrinput.h