SDRAngel: ATVDemodSettings Struct Reference
ATVDemodSettings Struct Reference
#include <atvdemodsettings.h>
Public Types
enum ATVModulation {
ATV_FM1, ATV_FM2, ATV_FM3, ATV_AM,
ATV_USB, ATV_LSB
}
enum ATVStd {
ATVStdPAL625, ATVStdPAL525, ATVStd405, ATVStdShortInterleaved,
ATVStdShort, ATVStdHSkip
}
Public Member Functions
ATVDemodSettings ()
void resetToDefaults ()
void setChannelMarker (Serializable *channelMarker)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
int getEffectiveSampleRate ()
float getLineTime ()
int getLineTimeFactor ()
float getTopTime ()
int getTopTimeFactor ()
int getRFSliderDivisor ()
void convertFromUIValues ()
void convertToUIValues ()
Static Public Member Functions
static float getFps (int fpsIndex)
static int getNumberOfLines (int nbLinesIndex)
static int getFpsIndex (float fps)
static int getNumberOfLinesIndex (int nbLines)
static float getNominalLineTime (int nbLinesIndex, int fpsIndex)
Public Attributes
int m_lineTimeFactor
added: +/- 100 something
int m_topTimeFactor
added: +/- 30 something
int m_fpsIndex
added: FPS list index
bool m_halfImage
added: true => m_fltRatioOfRowsToDisplay = 0.5, false => m_fltRatioOfRowsToDisplay = 1.0
int m_RFBandwidthFactor
added: [1:100]
int m_OppBandwidthFactor
added: [0:100]
int m_nbLinesIndex
added: #lines list index
int m_intFrequencyOffset
ATVModulation m_enmModulation
float m_fltRFBandwidth
float m_fltRFOppBandwidth
bool m_blnFFTFiltering
bool m_blndecimatorEnable
float m_fltBFOFrequency
float m_fmDeviation
int m_intSampleRate
ATVStd m_enmATVStandard
int m_intNumberOfLines
float m_fltLineDuration
float m_fltTopDuration
float m_fltFramePerS
float m_fltRatioOfRowsToDisplay
float m_fltVoltLevelSynchroTop
float m_fltVoltLevelSynchroBlack
bool m_blnHSync
bool m_blnVSync
bool m_blnInvertVideo
int m_intVideoTabIndex
int m_intTVSampleRate
int m_intNumberSamplePerLine
quint32 m_rgbColor
QString m_title
QString m_udpAddress
uint16_t m_udpPort
Serializable * m_channelMarker
Private Member Functions
void lineTimeUpdate ()
void topTimeUpdate ()
Private Attributes
float m_fltLineTimeMultiplier
float m_fltTopTimeMultiplier
int m_rfSliderDivisor
Detailed Description
Definition at line 27 of file atvdemodsettings.h.
Member Enumeration Documentation
ATVModulation
enum ATVDemodSettings::ATVModulation
Enumerator
ATV_FM1
Classical frequency modulation with discriminator #1.
ATV_FM2
Classical frequency modulation with discriminator #2.
ATV_FM3
Classical frequency modulation with phase derivative discriminator.
ATV_AM
Classical amplitude modulation.
ATV_USB
AM with vestigial lower side band (main signal is in the upper side)
ATV_LSB
AM with vestigial upper side band (main signal is in the lower side)
Definition at line 29 of file atvdemodsettings.h.
{
         ATV_FM1,
         ATV_FM2,
         ATV_FM3,
         ATV_AM,
         ATV_USB,
         ATV_LSB
     };
ATVStd
enum ATVDemodSettings::ATVStd
Enumerator
ATVStdPAL625
ATVStdPAL525
ATVStd405
ATVStdShortInterleaved
ATVStdShort
ATVStdHSkip
Definition at line 38 of file atvdemodsettings.h.
     {
         ATVStdPAL625,
         ATVStdPAL525,
         ATVStd405,
         ATVStdShortInterleaved,
         ATVStdShort,
         ATVStdHSkip
     };
Constructor & Destructor Documentation
ATVDemodSettings()
ATVDemodSettings::ATVDemodSettings ()
Definition at line 25 of file atvdemodsettings.cpp.
References resetToDefaults().
                                    :
     m_channelMarker(0)
 {
     resetToDefaults();
 }
Member Function Documentation
convertFromUIValues()
void ATVDemodSettings::convertFromUIValues ()
Definition at line 366 of file atvdemodsettings.cpp.
References getFps(), getLineTime(), getNumberOfLines(), getRFSliderDivisor(), getTopTime(), lineTimeUpdate(), m_fltFramePerS, m_fltLineDuration, m_fltRFBandwidth, m_fltRFOppBandwidth, m_fltTopDuration, m_fpsIndex, m_intNumberOfLines, m_nbLinesIndex, m_OppBandwidthFactor, m_RFBandwidthFactor, and topTimeUpdate().
Referenced by setChannelMarker().
 {
     lineTimeUpdate();
     m_fltLineDuration = getLineTime();
     topTimeUpdate();
     m_fltTopDuration = getTopTime();
     m_fltRFBandwidth = m_RFBandwidthFactor * getRFSliderDivisor() * 1.0f;
     m_fltRFOppBandwidth = m_OppBandwidthFactor * getRFSliderDivisor() * 1.0f;
     m_fltFramePerS = getFps(m_fpsIndex);
     m_intNumberOfLines = getNumberOfLines(m_nbLinesIndex);
 }
convertToUIValues()
void ATVDemodSettings::convertToUIValues ()
Definition at line 378 of file atvdemodsettings.cpp.
References getFpsIndex(), getNumberOfLinesIndex(), getRFSliderDivisor(), getTopTimeFactor(), m_fltFramePerS, m_fltRFBandwidth, m_fltRFOppBandwidth, m_fpsIndex, m_intNumberOfLines, m_lineTimeFactor, m_nbLinesIndex, m_OppBandwidthFactor, m_RFBandwidthFactor, and m_topTimeFactor.
Referenced by setChannelMarker().
 {
     m_lineTimeFactor = getTopTimeFactor();
     m_topTimeFactor = getTopTimeFactor();
     m_RFBandwidthFactor = roundf(m_fltRFBandwidth / getRFSliderDivisor());
     m_RFBandwidthFactor = m_RFBandwidthFactor < 1 ? 1 : m_RFBandwidthFactor;
     m_OppBandwidthFactor = roundf(m_fltRFOppBandwidth / getRFSliderDivisor());
     m_fpsIndex = getFpsIndex(m_fltFramePerS);
     m_nbLinesIndex = getNumberOfLinesIndex(m_intNumberOfLines);
 }
deserialize()
bool ATVDemodSettings::deserialize (const QByteArray & data)
Definition at line 108 of file atvdemodsettings.cpp.
References SimpleDeserializer::getVersion(), SimpleDeserializer::isValid(), m_blnHSync, m_blnInvertVideo, m_blnVSync, m_enmATVStandard, m_enmModulation, m_fltBFOFrequency, m_fltVoltLevelSynchroBlack, m_fltVoltLevelSynchroTop, m_fmDeviation, m_fpsIndex, m_halfImage, m_intFrequencyOffset, m_lineTimeFactor, m_nbLinesIndex, m_OppBandwidthFactor, m_RFBandwidthFactor, m_topTimeFactor, SimpleDeserializer::readBool(), SimpleDeserializer::readS32(), and resetToDefaults().
Referenced by setChannelMarker().
 {
     SimpleDeserializer d(arrData);
     if (!d.isValid())
     {
         resetToDefaults();
         return false;
     }
     if (d.getVersion() == 1)
     {
         QByteArray bytetmp;
         int tmp;
         d.readS32(1, &m_intFrequencyOffset, 0);
         // TODO: rgb color
         d.readS32(3, &tmp, 100);
         m_fltVoltLevelSynchroTop = tmp / 1000.0f;
         d.readS32(4, &tmp, 310);
         m_fltVoltLevelSynchroBlack = tmp / 1000.0f;
         d.readS32(5, &m_lineTimeFactor, 0); // added UI
         d.readS32(6, &m_topTimeFactor, 0); // added UI
         d.readS32(7, &tmp, 0);
         m_enmModulation = static_cast<ATVModulation>(tmp);
         d.readS32(8, &m_fpsIndex, 1); // added UI
         d.readBool(9, &m_blnHSync, false);
         d.readBool(10, &m_blnVSync, false);
         d.readBool(11, &m_halfImage, false); // added UI
         d.readS32(12, &m_RFBandwidthFactor, 10); // added UI
         d.readS32(13, &m_OppBandwidthFactor, 10); // added UI
         d.readS32(14, &tmp, 10);
         m_fltBFOFrequency = static_cast<float>(tmp);
         d.readBool(15, &m_blnInvertVideo, false);
         d.readS32(16, &m_nbLinesIndex, 1); // added UI
         d.readS32(17, &tmp, 250);
         m_fmDeviation = tmp / 500.0f;
         d.readS32(18, &tmp, 1);
         m_enmATVStandard = static_cast<ATVStd>(tmp);
         // TODO: calculate values from UI values
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
getEffectiveSampleRate()
int ATVDemodSettings::getEffectiveSampleRate ()
Definition at line 159 of file atvdemodsettings.cpp.
References m_blndecimatorEnable, m_intSampleRate, and m_intTVSampleRate.
Referenced by getRFSliderDivisor(), lineTimeUpdate(), setChannelMarker(), and topTimeUpdate().
 {
     return m_blndecimatorEnable ? m_intTVSampleRate : m_intSampleRate;
 }
getFps()
float ATVDemodSettings::getFps (int fpsIndex) static
Definition at line 165 of file atvdemodsettings.cpp.
Referenced by convertFromUIValues(), getNominalLineTime(), and setChannelMarker().
 {
     switch(fpsIndex)
     {
     case 0:
         return 30.0f;
         break;
     case 2:
         return 20.0f;
         break;
     case 3:
         return 16.0f;
         break;
     case 4:
         return 12.0f;
         break;
     case 5:
         return 10.0f;
         break;
     case 6:
         return 8.0f;
         break;
     case 7:
         return 5.0f;
         break;
     case 8:
         return 2.0f;
         break;
     case 9:
         return 1.0f;
         break;
     case 1:
     default:
         return 25.0f;
         break;
     }
 }
getFpsIndex()
int ATVDemodSettings::getFpsIndex (float fps) static
Definition at line 203 of file atvdemodsettings.cpp.
Referenced by convertToUIValues(), and setChannelMarker().
 {
     int fpsi = roundf(fps);
     if (fpsi <= 1) {
         return 9;
     } else if (fps <= 2) {
         return 8;
     } else if (fps <= 5) {
         return 7;
     } else if (fps <= 8) {
         return 6;
     } else if (fps <= 10) {
         return 5;
     } else if (fps <= 12) {
         return 4;
     } else if (fps <= 16) {
         return 3;
     } else if (fps <= 20) {
         return 2;
     } else if (fps <= 25) {
         return 1;
     } else {
         return 0;
     }
 }
getLineTime()
float ATVDemodSettings::getLineTime ()
Definition at line 331 of file atvdemodsettings.cpp.
References getNominalLineTime(), m_fltLineTimeMultiplier, m_fpsIndex, m_lineTimeFactor, and m_nbLinesIndex.
Referenced by convertFromUIValues(), and setChannelMarker().
 {
     return getNominalLineTime(m_nbLinesIndex, m_fpsIndex) + m_fltLineTimeMultiplier * m_lineTimeFactor;
 }
getLineTimeFactor()
int ATVDemodSettings::getLineTimeFactor ()
Definition at line 336 of file atvdemodsettings.cpp.
References getNominalLineTime(), m_fltLineDuration, m_fltLineTimeMultiplier, m_fpsIndex, and m_nbLinesIndex.
Referenced by setChannelMarker().
 {
     return roundf((m_fltLineDuration - getNominalLineTime(m_nbLinesIndex, m_fpsIndex)) / m_fltLineTimeMultiplier);
 }
getNominalLineTime()
float ATVDemodSettings::getNominalLineTime (int nbLinesIndex, int fpsIndex) static
Definition at line 308 of file atvdemodsettings.cpp.
References getFps(), and getNumberOfLines().
Referenced by getLineTime(), getLineTimeFactor(), getTopTime(), getTopTimeFactor(), lineTimeUpdate(), setChannelMarker(), and topTimeUpdate().
 {
     float fps = getFps(fpsIndex);
     int   nbLines = getNumberOfLines(nbLinesIndex);
     return 1.0f / (nbLines * fps);
 }
getNumberOfLines()
int ATVDemodSettings::getNumberOfLines (int nbLinesIndex) static
Definition at line 230 of file atvdemodsettings.cpp.
Referenced by convertFromUIValues(), getNominalLineTime(), and setChannelMarker().
 {
     switch(nbLinesIndex)
     {
     case 0:
         return 640;
         break;
     case 2:
         return 525;
         break;
     case 3:
         return 480;
         break;
     case 4:
         return 405;
         break;
     case 5:
         return 360;
         break;
     case 6:
         return 343;
         break;
     case 7:
         return 240;
         break;
     case 8:
         return 180;
         break;
     case 9:
         return 120;
         break;
     case 10:
         return 90;
         break;
     case 11:
         return 60;
         break;
     case 12:
         return 32;
         break;
     case 1:
     default:
         return 625;
         break;
     }
 }
getNumberOfLinesIndex()
int ATVDemodSettings::getNumberOfLinesIndex (int nbLines) static
Definition at line 277 of file atvdemodsettings.cpp.
Referenced by convertToUIValues(), and setChannelMarker().
 {
     if (nbLines <= 32) {
         return 12;
     } else if (nbLines <= 60) {
         return 11;
     } else if (nbLines <= 90) {
         return 10;
     } else if (nbLines <= 120) {
         return 9;
     } else if (nbLines <= 180) {
         return 8;
     } else if (nbLines <= 240) {
         return 7;
     } else if (nbLines <= 343) {
         return 6;
     } else if (nbLines <= 360) {
         return 5;
     } else if (nbLines <= 405) {
         return 4;
     } else if (nbLines <= 480) {
         return 3;
     } else if (nbLines <= 525) {
         return 2;
     } else if (nbLines <= 625) {
         return 1;
     } else {
         return 0;
     }
 }
getRFSliderDivisor()
int ATVDemodSettings::getRFSliderDivisor ()
Definition at line 389 of file atvdemodsettings.cpp.
References getEffectiveSampleRate().
Referenced by convertFromUIValues(), convertToUIValues(), and setChannelMarker().
 {
     int sampleRate = getEffectiveSampleRate();
     int scaleFactor = (int) std::log10(sampleRate/2);
     return std::pow(10.0, scaleFactor-1);
 }
getTopTime()
float ATVDemodSettings::getTopTime ()
Definition at line 356 of file atvdemodsettings.cpp.
References getNominalLineTime(), m_fltTopTimeMultiplier, m_fpsIndex, m_nbLinesIndex, and m_topTimeFactor.
Referenced by convertFromUIValues(), and setChannelMarker().
 {
     return getNominalLineTime(m_nbLinesIndex, m_fpsIndex) * (4.7f / 64.0f) + m_fltTopTimeMultiplier * m_topTimeFactor;
 }
getTopTimeFactor()
int ATVDemodSettings::getTopTimeFactor ()
Definition at line 361 of file atvdemodsettings.cpp.
References getNominalLineTime(), m_fltLineTimeMultiplier, m_fltTopDuration, m_fpsIndex, and m_nbLinesIndex.
Referenced by convertToUIValues(), and setChannelMarker().
 {
     return roundf((m_fltTopDuration - getNominalLineTime(m_nbLinesIndex, m_fpsIndex) * (4.7f / 64.0f)) / m_fltLineTimeMultiplier);
 }
lineTimeUpdate()
void ATVDemodSettings::lineTimeUpdate () private
calculates m_fltLineTimeMultiplier
Definition at line 319 of file atvdemodsettings.cpp.
References getEffectiveSampleRate(), getNominalLineTime(), m_fltLineTimeMultiplier, m_fpsIndex, and m_nbLinesIndex.
Referenced by convertFromUIValues(), and setChannelMarker().
 {
     float nominalLineTime = getNominalLineTime(m_nbLinesIndex, m_fpsIndex);
     int lineTimeScaleFactor = (int) std::log10(nominalLineTime);
     if (getEffectiveSampleRate() == 0) {
         m_fltLineTimeMultiplier = std::pow(10.0, lineTimeScaleFactor-3);
     } else {
         m_fltLineTimeMultiplier = 1.0f / getEffectiveSampleRate();
     }
 }
resetToDefaults()
void ATVDemodSettings::resetToDefaults ()
Definition at line 31 of file atvdemodsettings.cpp.
References ATV_FM1, ATVStdPAL625, m_blndecimatorEnable, m_blnFFTFiltering, m_blnHSync, m_blnInvertVideo, m_blnVSync, m_enmATVStandard, m_enmModulation, m_fltBFOFrequency, m_fltFramePerS, m_fltLineDuration, m_fltLineTimeMultiplier, m_fltRatioOfRowsToDisplay, m_fltRFBandwidth, m_fltRFOppBandwidth, m_fltTopDuration, m_fltTopTimeMultiplier, m_fltVoltLevelSynchroBlack, m_fltVoltLevelSynchroTop, m_fmDeviation, m_fpsIndex, m_halfImage, m_intFrequencyOffset, m_intNumberOfLines, m_intNumberSamplePerLine, m_intSampleRate, m_intTVSampleRate, m_intVideoTabIndex, m_lineTimeFactor, m_nbLinesIndex, m_OppBandwidthFactor, m_RFBandwidthFactor, m_rfSliderDivisor, m_rgbColor, m_title, m_topTimeFactor, m_udpAddress, and m_udpPort.
Referenced by ATVDemodSettings(), and deserialize().
 {
     m_lineTimeFactor = 0;
     m_topTimeFactor = 0;
     m_fpsIndex = 1; // 25 FPS
     m_halfImage = false; // m_fltRatioOfRowsToDisplay = 1.0
     m_RFBandwidthFactor = 10;
     m_OppBandwidthFactor = 10;
     m_nbLinesIndex = 1; // 625 lines
     m_intFrequencyOffset = 0;
     m_enmModulation = ATV_FM1;
     m_fltRFBandwidth = 0;
     m_fltRFOppBandwidth = 0;
     m_blnFFTFiltering = false;
     m_blndecimatorEnable = false;
     m_fltBFOFrequency = 0.0f;
     m_fmDeviation = 0.5f;
     m_intSampleRate = 0;
     m_enmATVStandard = ATVStdPAL625;
     m_intNumberOfLines = 625;
     m_fltLineDuration = 0.0f;
     m_fltTopDuration = 0.0f;
     m_fltFramePerS = 25.0f;
     m_fltRatioOfRowsToDisplay = 1.0f;
     m_fltVoltLevelSynchroTop = 0.0f;
     m_fltVoltLevelSynchroBlack = 1.0f;
     m_blnHSync = false;
     m_blnVSync = false;
     m_blnInvertVideo = false;
     m_intVideoTabIndex = 0;
     m_fltLineTimeMultiplier = 1.0f;
     m_fltTopTimeMultiplier = 1.0f;
     m_rfSliderDivisor = 1;
     m_intTVSampleRate = 0;
     m_intNumberSamplePerLine = 0;
     m_rgbColor = QColor(255, 255, 255).rgb();
     m_title = "ATV Demodulator";
     m_udpAddress = "127.0.0.1";
     m_udpPort = 9999;
 }
serialize()
QByteArray ATVDemodSettings::serialize () const
Definition at line 76 of file atvdemodsettings.cpp.
References SimpleSerializer::final(), m_blnHSync, m_blnInvertVideo, m_blnVSync, m_channelMarker, m_enmATVStandard, m_enmModulation, m_fltBFOFrequency, m_fltVoltLevelSynchroBlack, m_fltVoltLevelSynchroTop, m_fmDeviation, m_fpsIndex, m_halfImage, m_intFrequencyOffset, m_lineTimeFactor, m_nbLinesIndex, m_OppBandwidthFactor, m_RFBandwidthFactor, m_rgbColor, m_title, m_topTimeFactor, Serializable::serialize(), SimpleSerializer::writeBlob(), SimpleSerializer::writeBool(), SimpleSerializer::writeS32(), SimpleSerializer::writeString(), and SimpleSerializer::writeU32().
Referenced by setChannelMarker().
 {
     SimpleSerializer s(1);
     s.writeS32(1, m_intFrequencyOffset);
     s.writeU32(2, m_rgbColor);
     s.writeS32(3, roundf(m_fltVoltLevelSynchroTop*1000.0));   // mV
     s.writeS32(4, roundf(m_fltVoltLevelSynchroBlack*1000.0)); // mV
     s.writeS32(5, m_lineTimeFactor);      // added UI
     s.writeS32(6, m_topTimeFactor);       // added UI
     s.writeS32(7, m_enmModulation);
     s.writeS32(8, m_fpsIndex);            // added UI
     s.writeBool(9, m_blnHSync);
     s.writeBool(10,m_blnVSync);
     s.writeBool(11, m_halfImage);         // added UI
     s.writeS32(12, m_RFBandwidthFactor);  // added UI
     s.writeS32(13, m_OppBandwidthFactor); // added UI
     s.writeS32(14, roundf(m_fltBFOFrequency));
     s.writeBool(15, m_blnInvertVideo);
     s.writeS32(16, m_nbLinesIndex);       // added UI
     s.writeS32(17, roundf(m_fmDeviation * 500.0));
     s.writeS32(18, m_enmATVStandard);
     if (m_channelMarker) {
         s.writeBlob(19, m_channelMarker->serialize());
     }
     s.writeString(20, m_title);
     return s.final();
 }
setChannelMarker()
void ATVDemodSettings::setChannelMarker (Serializable * channelMarker) inline
Definition at line 95 of file atvdemodsettings.h.
References convertFromUIValues(), convertToUIValues(), deserialize(), getEffectiveSampleRate(), getFps(), getFpsIndex(), getLineTime(), getLineTimeFactor(), getNominalLineTime(), getNumberOfLines(), getNumberOfLinesIndex(), getRFSliderDivisor(), getTopTime(), getTopTimeFactor(), lineTimeUpdate(), serialize(), and topTimeUpdate().
 { m_channelMarker = channelMarker; }
topTimeUpdate()
void ATVDemodSettings::topTimeUpdate () private
calculates m_fltTopTimeMultiplier
Definition at line 344 of file atvdemodsettings.cpp.
References getEffectiveSampleRate(), getNominalLineTime(), m_fltTopTimeMultiplier, m_fpsIndex, and m_nbLinesIndex.
Referenced by convertFromUIValues(), and setChannelMarker().
 {
     float nominalTopTime = getNominalLineTime(m_nbLinesIndex, m_fpsIndex) * (4.7f / 64.0f);
     int topTimeScaleFactor = (int) std::log10(nominalTopTime);
     if (getEffectiveSampleRate() == 0) {
         m_fltTopTimeMultiplier = std::pow(10.0, topTimeScaleFactor-3);
     } else {
         m_fltTopTimeMultiplier = 1.0f / getEffectiveSampleRate();
     }
 }
Member Data Documentation
m_blndecimatorEnable
bool ATVDemodSettings::m_blndecimatorEnable
Definition at line 63 of file atvdemodsettings.h.
Referenced by getEffectiveSampleRate(), and resetToDefaults().
m_blnFFTFiltering
bool ATVDemodSettings::m_blnFFTFiltering
Definition at line 62 of file atvdemodsettings.h.
Referenced by resetToDefaults().
m_blnHSync
bool ATVDemodSettings::m_blnHSync
Definition at line 77 of file atvdemodsettings.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_blnInvertVideo
bool ATVDemodSettings::m_blnInvertVideo
Definition at line 79 of file atvdemodsettings.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_blnVSync
bool ATVDemodSettings::m_blnVSync
Definition at line 78 of file atvdemodsettings.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_channelMarker
Serializable* ATVDemodSettings::m_channelMarker
Definition at line 91 of file atvdemodsettings.h.
Referenced by serialize().
m_enmATVStandard
ATVStd ATVDemodSettings::m_enmATVStandard
Definition at line 69 of file atvdemodsettings.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_enmModulation
ATVModulation ATVDemodSettings::m_enmModulation
Definition at line 59 of file atvdemodsettings.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_fltBFOFrequency
float ATVDemodSettings::m_fltBFOFrequency
Definition at line 64 of file atvdemodsettings.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_fltFramePerS
float ATVDemodSettings::m_fltFramePerS
Definition at line 73 of file atvdemodsettings.h.
Referenced by convertFromUIValues(), convertToUIValues(), and resetToDefaults().
m_fltLineDuration
float ATVDemodSettings::m_fltLineDuration
Definition at line 71 of file atvdemodsettings.h.
Referenced by convertFromUIValues(), getLineTimeFactor(), and resetToDefaults().
m_fltLineTimeMultiplier
float ATVDemodSettings::m_fltLineTimeMultiplier private
Definition at line 119 of file atvdemodsettings.h.
Referenced by getLineTime(), getLineTimeFactor(), getTopTimeFactor(), lineTimeUpdate(), and resetToDefaults().
m_fltRatioOfRowsToDisplay
float ATVDemodSettings::m_fltRatioOfRowsToDisplay
Definition at line 74 of file atvdemodsettings.h.
Referenced by resetToDefaults().
m_fltRFBandwidth
float ATVDemodSettings::m_fltRFBandwidth
Definition at line 60 of file atvdemodsettings.h.
Referenced by convertFromUIValues(), convertToUIValues(), and resetToDefaults().
m_fltRFOppBandwidth
float ATVDemodSettings::m_fltRFOppBandwidth
Definition at line 61 of file atvdemodsettings.h.
Referenced by convertFromUIValues(), convertToUIValues(), and resetToDefaults().
m_fltTopDuration
float ATVDemodSettings::m_fltTopDuration
Definition at line 72 of file atvdemodsettings.h.
Referenced by convertFromUIValues(), getTopTimeFactor(), and resetToDefaults().
m_fltTopTimeMultiplier
float ATVDemodSettings::m_fltTopTimeMultiplier private
Definition at line 120 of file atvdemodsettings.h.
Referenced by getTopTime(), resetToDefaults(), and topTimeUpdate().
m_fltVoltLevelSynchroBlack
float ATVDemodSettings::m_fltVoltLevelSynchroBlack
Definition at line 76 of file atvdemodsettings.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_fltVoltLevelSynchroTop
float ATVDemodSettings::m_fltVoltLevelSynchroTop
Definition at line 75 of file atvdemodsettings.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_fmDeviation
float ATVDemodSettings::m_fmDeviation
Definition at line 65 of file atvdemodsettings.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_fpsIndex
int ATVDemodSettings::m_fpsIndex
added: FPS list index
Definition at line 51 of file atvdemodsettings.h.
Referenced by convertFromUIValues(), convertToUIValues(), deserialize(), getLineTime(), getLineTimeFactor(), getTopTime(), getTopTimeFactor(), lineTimeUpdate(), resetToDefaults(), serialize(), and topTimeUpdate().
m_halfImage
bool ATVDemodSettings::m_halfImage
added: true => m_fltRatioOfRowsToDisplay = 0.5, false => m_fltRatioOfRowsToDisplay = 1.0
Definition at line 52 of file atvdemodsettings.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_intFrequencyOffset
int ATVDemodSettings::m_intFrequencyOffset
Definition at line 58 of file atvdemodsettings.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_intNumberOfLines
int ATVDemodSettings::m_intNumberOfLines
Definition at line 70 of file atvdemodsettings.h.
Referenced by convertFromUIValues(), convertToUIValues(), and resetToDefaults().
m_intNumberSamplePerLine
int ATVDemodSettings::m_intNumberSamplePerLine
Definition at line 84 of file atvdemodsettings.h.
Referenced by resetToDefaults().
m_intSampleRate
int ATVDemodSettings::m_intSampleRate
Definition at line 68 of file atvdemodsettings.h.
Referenced by getEffectiveSampleRate(), and resetToDefaults().
m_intTVSampleRate
int ATVDemodSettings::m_intTVSampleRate
Definition at line 83 of file atvdemodsettings.h.
Referenced by getEffectiveSampleRate(), and resetToDefaults().
m_intVideoTabIndex
int ATVDemodSettings::m_intVideoTabIndex
Definition at line 80 of file atvdemodsettings.h.
Referenced by resetToDefaults().
m_lineTimeFactor
int ATVDemodSettings::m_lineTimeFactor
added: +/- 100 something
Definition at line 49 of file atvdemodsettings.h.
Referenced by convertToUIValues(), deserialize(), getLineTime(), resetToDefaults(), and serialize().
m_nbLinesIndex
int ATVDemodSettings::m_nbLinesIndex
added: #lines list index
Definition at line 55 of file atvdemodsettings.h.
Referenced by convertFromUIValues(), convertToUIValues(), deserialize(), getLineTime(), getLineTimeFactor(), getTopTime(), getTopTimeFactor(), lineTimeUpdate(), resetToDefaults(), serialize(), and topTimeUpdate().
m_OppBandwidthFactor
int ATVDemodSettings::m_OppBandwidthFactor
added: [0:100]
Definition at line 54 of file atvdemodsettings.h.
Referenced by convertFromUIValues(), convertToUIValues(), deserialize(), resetToDefaults(), and serialize().
m_RFBandwidthFactor
int ATVDemodSettings::m_RFBandwidthFactor
added: [1:100]
Definition at line 53 of file atvdemodsettings.h.
Referenced by convertFromUIValues(), convertToUIValues(), deserialize(), resetToDefaults(), and serialize().
m_rfSliderDivisor
int ATVDemodSettings::m_rfSliderDivisor private
Definition at line 121 of file atvdemodsettings.h.
Referenced by resetToDefaults().
m_rgbColor
quint32 ATVDemodSettings::m_rgbColor
Definition at line 87 of file atvdemodsettings.h.
Referenced by resetToDefaults(), and serialize().
m_title
QString ATVDemodSettings::m_title
Definition at line 88 of file atvdemodsettings.h.
Referenced by resetToDefaults(), and serialize().
m_topTimeFactor
int ATVDemodSettings::m_topTimeFactor
added: +/- 30 something
Definition at line 50 of file atvdemodsettings.h.
Referenced by convertToUIValues(), deserialize(), getTopTime(), resetToDefaults(), and serialize().
m_udpAddress
QString ATVDemodSettings::m_udpAddress
Definition at line 89 of file atvdemodsettings.h.
Referenced by resetToDefaults().
m_udpPort
uint16_t ATVDemodSettings::m_udpPort
Definition at line 90 of file atvdemodsettings.h.
Referenced by resetToDefaults().
The documentation for this struct was generated from the following files:
plugins/channelrx/demodatv/atvdemodsettings.h
plugins/channelrx/demodatv/atvdemodsettings.cpp