SDRAngel: DeviceXTRX Class Reference
DeviceXTRX Class Reference
#include <devicextrx.h>
Public Member Functions
DeviceXTRX ()
~DeviceXTRX ()
bool open (const char *deviceStr)
void close ()
struct xtrx_dev * getDevice ()
double set_samplerate (double rate, double master, bool output)
double getMasterRate () const
double getClockGen () const
double getActualInputRate () const
double getActualOutputRate () const
Static Public Member Functions
static void getAutoGains (uint32_t autoGain, uint32_t &lnaGain, uint32_t &tiaGain, uint32_t &pgaGain)
Static Public Attributes
static const uint32_t m_nbGains = 74
static const unsigned int blockSize = (1<<13)
Private Attributes
struct xtrx_dev * m_dev
device handle
double m_inputRate
double m_outputRate
double m_masterRate
double m_clockGen
double m_actualInputRate
double m_actualOutputRate
Static Private Attributes
static const uint32_t m_lnaTbl [m_nbGains]
static const uint32_t m_pgaTbl [m_nbGains]
Detailed Description
Definition at line 27 of file devicextrx.h.
Constructor & Destructor Documentation
DeviceXTRX()
DeviceXTRX::DeviceXTRX ()
Definition at line 39 of file devicextrx.cpp.
                        :
     m_dev(0),
     m_inputRate(0),
     m_outputRate(0),
     m_masterRate(0),
     m_clockGen(0),
     m_actualInputRate(0),
     m_actualOutputRate(0)
 {}
~DeviceXTRX()
DeviceXTRX::~DeviceXTRX ()
Definition at line 49 of file devicextrx.cpp.
References close().
 {
     close();
 }
Member Function Documentation
close()
void DeviceXTRX::close ()
Definition at line 70 of file devicextrx.cpp.
References m_dev.
Referenced by XTRXOutput::closeDevice(), XTRXInput::closeDevice(), and ~DeviceXTRX().
 {
     if (m_dev)
     {
         xtrx_close(m_dev);
         m_dev = 0;
     }
 }
getActualInputRate()
double DeviceXTRX::getActualInputRate () const inline
Definition at line 39 of file devicextrx.h.
Referenced by XTRXInput::applySettings(), XTRXInput::getDevSampleRate(), XTRXInput::getLog2HardDecim(), XTRXInput::getSampleRate(), and XTRXInput::handleMessage().
 { return m_actualInputRate; }
getActualOutputRate()
double DeviceXTRX::getActualOutputRate () const inline
Definition at line 40 of file devicextrx.h.
Referenced by XTRXOutput::applySettings(), XTRXOutput::getDevSampleRate(), XTRXOutput::getLog2HardInterp(), XTRXOutput::getSampleRate(), and XTRXOutput::handleMessage().
 { return m_actualOutputRate; }
getAutoGains()
void DeviceXTRX::getAutoGains (uint32_t autoGain, uint32_t & lnaGain, uint32_t & tiaGain, uint32_t & pgaGain) static
Definition at line 79 of file devicextrx.cpp.
References m_lnaTbl, and m_pgaTbl.
Referenced by XTRXInput::apply_gain_auto().
 {
     uint32_t value = autoGain + 12 > 73 ? 73 : autoGain + 12;
     if (value > 51) {
         tiaGain = 2;
     } else if (value > 42) {
         tiaGain = 1;
     } else {
         tiaGain = 0;
     }
     lnaGain = m_lnaTbl[value];
     pgaGain = m_pgaTbl[value];
 }
getClockGen()
double DeviceXTRX::getClockGen () const inline
Definition at line 38 of file devicextrx.h.
Referenced by XTRXOutput::getClockGen(), XTRXInput::getClockGen(), XTRXInput::getLog2HardDecim(), XTRXOutput::getLog2HardInterp(), XTRXOutput::handleMessage(), and XTRXInput::handleMessage().
 { return m_clockGen; }
getDevice()
struct xtrx_dev* DeviceXTRX::getDevice () inline
Definition at line 35 of file devicextrx.h.
Referenced by XTRXInput::apply_gain_lna(), XTRXInput::apply_gain_pga(), XTRXInput::apply_gain_tia(), XTRXOutput::applySettings(), XTRXInput::applySettings(), DeviceXTRXShared::get_board_temperature(), DeviceXTRXShared::get_gps_status(), XTRXOutput::handleMessage(), XTRXInput::handleMessage(), XTRXOutput::start(), XTRXInput::start(), XTRXOutput::stop(), XTRXInput::stop(), XTRXOutput::webapiFormatDeviceReport(), and XTRXInput::webapiFormatDeviceReport().
 { return m_dev; }
getMasterRate()
double DeviceXTRX::getMasterRate () const inline
Definition at line 37 of file devicextrx.h.
 { return m_masterRate; }
open()
bool DeviceXTRX::open (const char * deviceStr)
Definition at line 54 of file devicextrx.cpp.
References m_dev.
Referenced by XTRXOutput::openDevice(), and XTRXInput::openDevice().
 {
     int res;
     qDebug("DeviceXTRX::open: serial: %s", (const char *) deviceStr);
     res = xtrx_open(deviceStr, XTRX_O_RESET | 4, &m_dev);
     if (res)
     {
         qCritical() << "DeviceXTRX::open: cannot open device " << deviceStr;
         return false;
     }
     return true;
 }
set_samplerate()
double DeviceXTRX::set_samplerate (double rate, double master, bool output)
Definition at line 95 of file devicextrx.cpp.
References m_actualInputRate, m_actualOutputRate, m_clockGen, m_dev, m_inputRate, m_masterRate, and m_outputRate.
Referenced by XTRXOutput::applySettings(), and XTRXInput::applySettings().
 {
     if (output)
     {
         m_outputRate = rate;
         if (master != 0.0) {
             m_masterRate = master;
         }
     }
     else
     {
         m_inputRate = rate;
         if (master != 0.0) {
             m_masterRate = master;
         }
     }
     int res = xtrx_set_samplerate(m_dev,
           m_masterRate,
           m_inputRate,
           m_outputRate,
           0,
           &m_clockGen,
           &m_actualInputRate,
           &m_actualOutputRate);
     if (res)
     {
         qCritical("DeviceXTRX::set_samplerate: Unable to set %s samplerate, m_masterRate: %f, m_inputRate: %f, m_outputRate: %f, error=%d\n",
                 output ? "output" : "input", m_masterRate, m_inputRate, m_outputRate, res);
         return 0;
     }
     else
     {
         qDebug() << "DeviceXTRX::set_samplerate: sample rate set: "
                 << "output: "<< output
                 << "m_masterRate: " << m_masterRate
                 << "m_inputRate: " << m_inputRate
                 << "m_outputRate: " << m_outputRate
                 << "m_clockGen: " << m_clockGen
                 << "m_actualInputRate: " << m_actualInputRate
                 << "m_actualOutputRate: " << m_actualOutputRate;
     }
     if (output) {
         return m_outputRate;
     }
     return m_inputRate;
 }
Member Data Documentation
blockSize
const unsigned int DeviceXTRX::blockSize = (1<<13) static
Definition at line 44 of file devicextrx.h.
Referenced by XTRXOutputThread::run(), XTRXInputThread::run(), and XTRXInputThread::XTRXInputThread().
m_actualInputRate
double DeviceXTRX::m_actualInputRate private
Definition at line 52 of file devicextrx.h.
Referenced by set_samplerate().
m_actualOutputRate
double DeviceXTRX::m_actualOutputRate private
Definition at line 53 of file devicextrx.h.
Referenced by set_samplerate().
m_clockGen
double DeviceXTRX::m_clockGen private
Definition at line 51 of file devicextrx.h.
Referenced by set_samplerate().
m_dev
struct xtrx_dev* DeviceXTRX::m_dev private
device handle
Definition at line 47 of file devicextrx.h.
Referenced by close(), open(), and set_samplerate().
m_inputRate
double DeviceXTRX::m_inputRate private
Definition at line 48 of file devicextrx.h.
Referenced by set_samplerate().
m_lnaTbl
const uint32_t DeviceXTRX::m_lnaTbl static private
Initial value:
= {
        0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,
        5,  5,  6,  6,  6,  7,  7,  7,  8,  9,  10, 11, 11, 11, 11, 11,
        11, 11, 11, 11, 11, 11, 11, 11, 12, 13, 14, 14, 14, 14, 14, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14
}
Definition at line 55 of file devicextrx.h.
Referenced by getAutoGains().
m_masterRate
double DeviceXTRX::m_masterRate private
Definition at line 50 of file devicextrx.h.
Referenced by set_samplerate().
m_nbGains
const uint32_t DeviceXTRX::m_nbGains = 74 static
Definition at line 43 of file devicextrx.h.
m_outputRate
double DeviceXTRX::m_outputRate private
Definition at line 49 of file devicextrx.h.
Referenced by set_samplerate().
m_pgaTbl
const uint32_t DeviceXTRX::m_pgaTbl static private
Initial value:
= {
        0,  1,  2,  0,  1,  2,  0,  1,  2,  0,  1,  2,  0,  1,  2,  0,
        1,  2,  0,  1,  2,  0,  1,  2,  0,  0,  0,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9,  10, 11, 12, 12, 12, 12, 4,  5,  6,  7,  8,
        9,  10, 11, 12, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24, 25, 26, 27, 28, 29, 30, 31
}
Definition at line 56 of file devicextrx.h.
Referenced by getAutoGains().
The documentation for this class was generated from the following files:
devices/xtrx/devicextrx.h
devices/xtrx/devicextrx.cpp