SDRAngel: DynamicArgSettingGUI Class Reference
DynamicArgSettingGUI Class Reference
#include <dynamicargsettinggui.h>
Inherits QObject.
Signals
void valueChanged (QString itemName, QVariant value)
Public Member Functions
DynamicArgSettingGUI (ArgInfoGUI *argSettingGUI, const QString &name, QObject *parent=0)
~DynamicArgSettingGUI ()
const QString & getName () const
QVariant getValue () const
void setValue (const QVariant &value)
Private Slots
void processValueChanged ()
Private Attributes
ArgInfoGUI * m_argSettingGUI
QString m_name
Detailed Description
Definition at line 28 of file dynamicargsettinggui.h.
Constructor & Destructor Documentation
DynamicArgSettingGUI()
DynamicArgSettingGUI::DynamicArgSettingGUI (ArgInfoGUI * argSettingGUI, const QString & name, QObject * parent = 0)
Definition at line 20 of file dynamicargsettinggui.cpp.
References m_argSettingGUI, processValueChanged(), and valueChanged().
                                                                                                           :
     QObject(parent),
     m_argSettingGUI(argSettingGUI),
     m_name(name)
 {
     connect(m_argSettingGUI, SIGNAL(valueChanged()), this, SLOT(processValueChanged()));
 }
~DynamicArgSettingGUI()
DynamicArgSettingGUI::~DynamicArgSettingGUI ()
Definition at line 28 of file dynamicargsettinggui.cpp.
References m_argSettingGUI, processValueChanged(), and valueChanged().
 {
     disconnect(m_argSettingGUI, SIGNAL(valueChanged()), this, SLOT(processValueChanged()));
 }
Member Function Documentation
getName()
const QString& DynamicArgSettingGUI::getName () const inline
Definition at line 35 of file dynamicargsettinggui.h.
References SWGSDRangel::setValue().
 { return m_name; }
getValue()
QVariant DynamicArgSettingGUI::getValue () const
Definition at line 46 of file dynamicargsettinggui.cpp.
References ArgInfoGUI::ArgInfoValueBool, ArgInfoGUI::ArgInfoValueFloat, ArgInfoGUI::ArgInfoValueInt, ArgInfoGUI::ArgInfoValueString, ArgInfoGUI::getBoolValue(), ArgInfoGUI::getFloatValue(), ArgInfoGUI::getIntValue(), ArgInfoGUI::getStringValue(), ArgInfoGUI::getValueType(), and m_argSettingGUI.
 {
     if (m_argSettingGUI->getValueType() == ArgInfoGUI::ArgInfoValueBool) {
         return QVariant(m_argSettingGUI->getBoolValue());
     } else if (m_argSettingGUI->getValueType() == ArgInfoGUI::ArgInfoValueInt) {
         return QVariant(m_argSettingGUI->getIntValue());
     } else if (m_argSettingGUI->getValueType() == ArgInfoGUI::ArgInfoValueFloat) {
         return QVariant(m_argSettingGUI->getFloatValue());
     } else if (m_argSettingGUI->getValueType() == ArgInfoGUI::ArgInfoValueString) {
         return QVariant(m_argSettingGUI->getStringValue());
     } else {
         return QVariant(false);
     }
 }
processValueChanged
void DynamicArgSettingGUI::processValueChanged () private slot
Definition at line 33 of file dynamicargsettinggui.cpp.
References ArgInfoGUI::ArgInfoValueBool, ArgInfoGUI::ArgInfoValueFloat, ArgInfoGUI::ArgInfoValueInt, ArgInfoGUI::ArgInfoValueString, ArgInfoGUI::getBoolValue(), ArgInfoGUI::getFloatValue(), ArgInfoGUI::getIntValue(), ArgInfoGUI::getStringValue(), ArgInfoGUI::getValueType(), m_argSettingGUI, m_name, and valueChanged().
Referenced by DynamicArgSettingGUI(), and ~DynamicArgSettingGUI().
 {
     if (m_argSettingGUI->getValueType() == ArgInfoGUI::ArgInfoValueBool) {
         emit valueChanged(m_name, QVariant(m_argSettingGUI->getBoolValue()));
     } else if (m_argSettingGUI->getValueType() == ArgInfoGUI::ArgInfoValueInt) {
         emit valueChanged(m_name, QVariant(m_argSettingGUI->getIntValue()));
     } else if (m_argSettingGUI->getValueType() == ArgInfoGUI::ArgInfoValueFloat) {
         emit valueChanged(m_name, QVariant(m_argSettingGUI->getFloatValue()));
     } else if (m_argSettingGUI->getValueType() == ArgInfoGUI::ArgInfoValueString) {
         emit valueChanged(m_name, QVariant(m_argSettingGUI->getStringValue()));
     }
 }
setValue()
void DynamicArgSettingGUI::setValue (const QVariant & value)
Definition at line 61 of file dynamicargsettinggui.cpp.
References m_argSettingGUI, ArgInfoGUI::setBoolValue(), ArgInfoGUI::setFloatValue(), ArgInfoGUI::setIntValue(), and ArgInfoGUI::setStringValue().
 {
     bool ok = false;
     if (value.type() == QVariant::Bool)
     {
         m_argSettingGUI->setBoolValue(value.toBool());
     }
     else if (value.type() == QVariant::Int)
     {
         int newValue = value.toInt(&ok);
         if (ok) {
             m_argSettingGUI->setIntValue(newValue);
         }
     }
     else if (value.type() == QVariant::Double)
     {
         double newValue = value.toDouble(&ok);
         if (ok) {
             m_argSettingGUI->setFloatValue(newValue);
         }
     }
     else if (value.type() == QVariant::String)
     {
         m_argSettingGUI->setStringValue(value.toString());
     }
 }
valueChanged
void DynamicArgSettingGUI::valueChanged (QString itemName, QVariant value) signal
Referenced by DynamicArgSettingGUI(), processValueChanged(), and ~DynamicArgSettingGUI().
Member Data Documentation
m_argSettingGUI
ArgInfoGUI* DynamicArgSettingGUI::m_argSettingGUI private
Definition at line 46 of file dynamicargsettinggui.h.
Referenced by DynamicArgSettingGUI(), getValue(), processValueChanged(), setValue(), and ~DynamicArgSettingGUI().
m_name
QString DynamicArgSettingGUI::m_name private
Definition at line 47 of file dynamicargsettinggui.h.
Referenced by processValueChanged().
The documentation for this class was generated from the following files:
sdrgui/soapygui/dynamicargsettinggui.h
sdrgui/soapygui/dynamicargsettinggui.cpp