SDRAngel: SWGSDRangel::SWGAirspyHFReport Class Reference
SWGSDRangel::SWGAirspyHFReport Class Reference
#include <SWGAirspyHFReport.h>
Public Member Functions
SWGAirspyHFReport ()
SWGAirspyHFReport (QString *json)
virtual ~SWGAirspyHFReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGAirspyHFReport * fromJson (QString &jsonString) override
QList< SWGSampleRate * > * getSampleRates ()
void setSampleRates (QList< SWGSampleRate *> *sample_rates)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QList< SWGSampleRate * > * sample_rates
bool m_sample_rates_isSet
Detailed Description
Definition at line 33 of file SWGAirspyHFReport.h.
Constructor & Destructor Documentation
SWGAirspyHFReport() [1/2]
SWGSDRangel::SWGAirspyHFReport::SWGAirspyHFReport ()
Definition at line 30 of file SWGAirspyHFReport.cpp.
References m_sample_rates_isSet, and sample_rates.
{
     sample_rates = nullptr;
     m_sample_rates_isSet = false;
 }
SWGAirspyHFReport() [2/2]
SWGSDRangel::SWGAirspyHFReport::SWGAirspyHFReport (QString * json)
Definition at line 25 of file SWGAirspyHFReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGAirspyHFReport()
SWGSDRangel::SWGAirspyHFReport::~SWGAirspyHFReport () virtual
Definition at line 35 of file SWGAirspyHFReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGAirspyHFReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 72 of file SWGAirspyHFReport.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGAirspyHFReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 83 of file SWGAirspyHFReport.cpp.
References sample_rates, and SWGSDRangel::toJsonArray().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(sample_rates->size() > 0){
         toJsonArray((QList<void*>*)sample_rates, obj, "sampleRates", "SWGSampleRate");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGAirspyHFReport::cleanup ()
Definition at line 46 of file SWGAirspyHFReport.cpp.
References sample_rates.
Referenced by ~SWGAirspyHFReport().
{
     if(sample_rates != nullptr) {
         auto arr = sample_rates;
         for(auto o: *arr) {
             delete o;
         }
         delete sample_rates;
     }
 }
fromJson()
SWGAirspyHFReport * SWGSDRangel::SWGAirspyHFReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 57 of file SWGAirspyHFReport.cpp.
References fromJsonObject().
Referenced by SWGAirspyHFReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGAirspyHFReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 66 of file SWGAirspyHFReport.cpp.
References sample_rates, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&sample_rates, pJson["sampleRates"], "QList", "SWGSampleRate");
 }
getSampleRates()
QList< SWGSampleRate * > * SWGSDRangel::SWGAirspyHFReport::getSampleRates ()
Definition at line 93 of file SWGAirspyHFReport.cpp.
References sample_rates.
Referenced by AirspyHFInput::webapiFormatDeviceReport().
{
     return sample_rates;
 }
init()
void SWGSDRangel::SWGAirspyHFReport::init ()
Definition at line 40 of file SWGAirspyHFReport.cpp.
References m_sample_rates_isSet, and sample_rates.
Referenced by SWGAirspyHFReport(), and AirspyHFInput::webapiReportGet().
{
     sample_rates = new QList<SWGSampleRate*>();
     m_sample_rates_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGAirspyHFReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 104 of file SWGAirspyHFReport.cpp.
References sample_rates.
Referenced by SWGSDRangel::SWGDeviceReport::asJsonObject(), and SWGSDRangel::SWGDeviceReport::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(sample_rates->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setSampleRates()
void SWGSDRangel::SWGAirspyHFReport::setSampleRates (QList< SWGSampleRate *> * sample_rates)
Definition at line 97 of file SWGAirspyHFReport.cpp.
References m_sample_rates_isSet, and sample_rates.
Referenced by AirspyHFInput::webapiFormatDeviceReport().
{
     this->sample_rates = sample_rates;
     this->m_sample_rates_isSet = true;
 }
Member Data Documentation
m_sample_rates_isSet
bool SWGSDRangel::SWGAirspyHFReport::m_sample_rates_isSet private
Definition at line 54 of file SWGAirspyHFReport.h.
Referenced by init(), setSampleRates(), and SWGAirspyHFReport().
sample_rates
QList<SWGSampleRate*>* SWGSDRangel::SWGAirspyHFReport::sample_rates private
Definition at line 53 of file SWGAirspyHFReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSampleRates(), init(), isSet(), setSampleRates(), and SWGAirspyHFReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGAirspyHFReport.h
swagger/sdrangel/code/qt5/client/SWGAirspyHFReport.cpp