SDRAngel: leansdr::s2_frame_transmitter< T > Struct Template Reference
leansdr::s2_frame_transmitter< T > Struct Template Reference
#include <dvbs2.h>
Public Member Functions
s2_frame_transmitter (scheduler *sch, pipebuf< plslot< hard_ss >> &_in, pipebuf< complex< T >> &_out)
void run ()
int run_frame (s2_pls *pls, const modcod_info *mcinfo, const plslot< hard_ss > *pin, int nslots, complex< T > *pout)
void scramble (const complex< T > *src, uint8_t r, complex< T > *dst)
Public Member Functions inherited from leansdr::runnable
runnable (scheduler *_sch, const char *name)
Public Member Functions inherited from leansdr::runnable_common
runnable_common (const char *_name)
virtual ~runnable_common ()
virtual void shutdown ()
Private Member Functions
void update_cstln (const modcod_info *mcinfo)
Private Attributes
pipereader< plslot< hard_ss > > in
pipewriter< complex< T > > out
cstln_lut< hard_ss, 256 > * cstln
complex< T > * csymbols
complex< T > qsymbols [4]
s2_sof< T > sof
s2_plscodes< T > plscodes
s2_scrambling scrambling
Additional Inherited Members
Public Attributes inherited from leansdr::runnable_common
const char * name
Protected Attributes inherited from leansdr::runnable
scheduler * sch
Detailed Description
template<typename T>
struct leansdr::s2_frame_transmitter< T >
Definition at line 298 of file dvbs2.h.
Constructor & Destructor Documentation
s2_frame_transmitter()
template<typename T > leansdr::s2_frame_transmitter< T >::s2_frame_transmitter (scheduler * sch, pipebuf< plslot< hard_ss >> & _in, pipebuf< complex< T >> & _out) inline
Definition at line 300 of file dvbs2.h.
References leansdr::cstln_amp.
         : runnable(sch, "S2 frame transmitter"),
           in(_in), out(_out, modcod_info::MAX_SYMBOLS_PER_FRAME)
     {
         float amp = cstln_amp / sqrtf(2);
         qsymbols[0].re = +amp;
         qsymbols[0].im = +amp;
         qsymbols[1].re = +amp;
         qsymbols[1].im = -amp;
         qsymbols[2].re = -amp;
         qsymbols[2].im = +amp;
         qsymbols[3].re = -amp;
         qsymbols[3].im = -amp;
     }
Member Function Documentation
run()
template<typename T > void leansdr::s2_frame_transmitter< T >::run () inline virtual
Reimplemented from leansdr::runnable_common.
Definition at line 316 of file dvbs2.h.
References leansdr::check_modcod(), leansdr::fail(), leansdr::plslot< SOFTSYMB >::is_pls, leansdr::s2_pls::modcod, leansdr::modcod_info::nslots_nf, leansdr::s2_pls::pilots, leansdr::plslot< SOFTSYMB >::pls, and leansdr::s2_pls::sf.
     {
         while (in.readable() >= 1)
         {
             plslot<hard_ss> *pin = in.rd();
             if (!pin->is_pls)
                 fail("Expected PLS pseudo-slot");
             s2_pls *pls = &pin->pls;
             const modcod_info *mcinfo = check_modcod(pls->modcod);
             int nslots = (pls->sf ? mcinfo->nslots_nf / 4 : mcinfo->nslots_nf);
             if (in.readable() < 1 + nslots)
                 break;
             // Require room for BBHEADER + slots + optional pilots.
             int nsymbols = ((1 + nslots) * plslot<hard_ss>::LENGTH +
                             (pls->pilots ? ((nslots - 1) / 16) * pilot_length : 0));
             if (out.writable() < nsymbols)
                 break;
             update_cstln(mcinfo);
             int nw = run_frame(pls, mcinfo, pin + 1, nslots, out.wr());
             if (nw != nsymbols)
                 fail("Bug: s2_frame_transmitter overflow");
             in.read(1 + nslots);
             out.written(nsymbols);
         }
     }
run_frame()
template<typename T > int leansdr::s2_frame_transmitter< T >::run_frame (s2_pls * pls, const modcod_info * mcinfo, const plslot< hard_ss > * pin, int nslots, complex< T > * pout) inline
Definition at line 341 of file dvbs2.h.
References leansdr::fail(), leansdr::s2_pls::modcod, leansdr::s2_pls::pilots, and leansdr::s2_pls::sf.
     {
         complex<T> *pout0 = pout; // For sanity check
         // PLHEADER: SOF AND PLSCODE
         // EN 302 307-1 section 5.5.2 PL signalling
         memcpy(pout, sof.symbols, sof.LENGTH * sizeof(*pout));
         pout += sof.LENGTH;
         int pls_index = (pls->modcod << 2) | (pls->sf << 1) | pls->pilots;
         memcpy(pout, plscodes.symbols[pls_index], plscodes.LENGTH * sizeof(*pout));
         pout += plscodes.LENGTH;
         // Slots and pilots
         int till_next_pilot = pls->pilots ? 16 : nslots;
         uint8_t *scr = &scrambling.Rn[0];
         for (int S = 0; S < nslots; ++S, ++pin, --till_next_pilot)
         {
             if (till_next_pilot == 0)
             {
                 // Send pilot
                 for (int s = 0; s < pilot_length; ++s, ++scr, ++pout)
                     scramble(&qsymbols[0], *scr, pout);
                 till_next_pilot = 16;
             }
             // Send slot
             if (pin->is_pls)
                 fail("s2_frame_transmitter: bad input sequence");
             const hard_ss *ps = pin->symbols;
             for (int s = 0; s < pin->LENGTH; ++s, ++ps, ++scr, ++pout)
                 scramble(&csymbols[*ps], *scr, pout);
         }
         return pout - pout0;
     }
scramble()
template<typename T > void leansdr::s2_frame_transmitter< T >::scramble (const complex< T > * src, uint8_t r, complex< T > * dst) inline
Definition at line 374 of file dvbs2.h.
References leansdr::complex< T >::im, and leansdr::complex< T >::re.
     {
         switch (r)
         {
         case 3:
             dst->re = src->im;
             dst->im = -src->re;
             break;
         case 2:
             dst->re = -src->re;
             dst->im = -src->im;
             break;
         case 1:
             dst->re = -src->im;
             dst->im = src->re;
             break;
         default:
             *dst = *src;
         }
     }
update_cstln()
template<typename T > void leansdr::s2_frame_transmitter< T >::update_cstln (const modcod_info * mcinfo) inline private
Definition at line 400 of file dvbs2.h.
References leansdr::modcod_info::c, leansdr::modcod_info::esn0_nf, leansdr::modcod_info::g1, leansdr::modcod_info::g2, leansdr::modcod_info::g3, leansdr::complex< T >::im, leansdr::modcod_info::nsymbols, leansdr::cstln_base::nsymbols, leansdr::complex< T >::re, and leansdr::cstln_base::symbols.
     {
         if (!cstln || cstln->nsymbols != mcinfo->nsymbols)
         {
             if (cstln)
             {
                 fprintf(stderr, "Warning: Variable MODCOD is inefficient\n");
                 delete cstln;
                 delete csymbols;
             }
             if (sch->debug)
                 fprintf(stderr, "Building constellation %d\n", mcinfo->nsymbols);
             // TBD Different Es/N0 for short frames ?
             cstln = new cstln_lut<hard_ss, 256>(mcinfo->c, mcinfo->esn0_nf,
                                                 mcinfo->g1, mcinfo->g2, mcinfo->g3);
             csymbols = new complex<T>[cstln->nsymbols];
             for (int s = 0; s < cstln->nsymbols; ++s)
             {
                 csymbols[s].re = cstln->symbols[s].re;
                 csymbols[s].im = cstln->symbols[s].im;
             }
         }
     }
Member Data Documentation
cstln
template<typename T > cstln_lut<hard_ss, 256>* leansdr::s2_frame_transmitter< T >::cstln private
Definition at line 398 of file dvbs2.h.
csymbols
template<typename T > complex<T>* leansdr::s2_frame_transmitter< T >::csymbols private
Definition at line 399 of file dvbs2.h.
in
template<typename T > pipereader<plslot<hard_ss> > leansdr::s2_frame_transmitter< T >::in private
Definition at line 396 of file dvbs2.h.
out
template<typename T > pipewriter<complex<T> > leansdr::s2_frame_transmitter< T >::out private
Definition at line 397 of file dvbs2.h.
plscodes
template<typename T > s2_plscodes<T> leansdr::s2_frame_transmitter< T >::plscodes private
Definition at line 425 of file dvbs2.h.
qsymbols
template<typename T > complex<T> leansdr::s2_frame_transmitter< T >::qsymbols[4] private
Definition at line 423 of file dvbs2.h.
scrambling
template<typename T > s2_scrambling leansdr::s2_frame_transmitter< T >::scrambling private
Definition at line 426 of file dvbs2.h.
sof
template<typename T > s2_sof<T> leansdr::s2_frame_transmitter< T >::sof private
Definition at line 424 of file dvbs2.h.
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/dvbs2.h