SDRAngel: LoRaDemod::MsgConfigureLoRaDemod Class Reference
LoRaDemod::MsgConfigureLoRaDemod Class Reference
#include <lorademod.h>
Public Member Functions
const LoRaDemodSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureLoRaDemod * create (const LoRaDemodSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureLoRaDemod (const LoRaDemodSettings &settings, bool force)
Private Attributes
LoRaDemodSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 46 of file lorademod.h.
Constructor & Destructor Documentation
MsgConfigureLoRaDemod()
LoRaDemod::MsgConfigureLoRaDemod::MsgConfigureLoRaDemod (const LoRaDemodSettings & settings, bool force) inline private
Definition at line 62 of file lorademod.h.
Referenced by create().
                                                                              :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureLoRaDemod* LoRaDemod::MsgConfigureLoRaDemod::create (const LoRaDemodSettings & settings, bool force) inline static
Definition at line 53 of file lorademod.h.
References MsgConfigureLoRaDemod().
Referenced by LoRaDemodGUI::applySettings(), and LoRaDemod::deserialize().
         {
             return new MsgConfigureLoRaDemod(settings, force);
         }
getForce()
bool LoRaDemod::MsgConfigureLoRaDemod::getForce () const inline
Definition at line 51 of file lorademod.h.
References m_force.
 { return m_force; }
getSettings()
const LoRaDemodSettings& LoRaDemod::MsgConfigureLoRaDemod::getSettings () const inline
Definition at line 50 of file lorademod.h.
References m_settings.
Referenced by LoRaDemod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool LoRaDemod::MsgConfigureLoRaDemod::m_force private
Definition at line 60 of file lorademod.h.
Referenced by getForce().
m_settings
LoRaDemodSettings LoRaDemod::MsgConfigureLoRaDemod::m_settings private
Definition at line 59 of file lorademod.h.
Referenced by getSettings(), and LoRaDemod::getTitle().
The documentation for this class was generated from the following file:
plugins/channelrx/demodlora/lorademod.h