SDRAngel: PhaseLockComplex Class Reference
PhaseLockComplex Class Reference
#include <phaselockcomplex.h>
Classes
class ExpAvg
Public Member Functions
PhaseLockComplex ()
void computeCoefficients (Real wn, Real zeta, Real K)
void setPskOrder (unsigned int order)
void setSampleRate (unsigned int sampleRate)
void reset ()
void feed (float re, float im)
const std::complex< float > & getComplex () const
float getReal () const
float getImag () const
bool locked () const
float getFreq () const
float getDeltaPhi () const
float getPhiHat () const
Static Private Member Functions
static float normalizeAngle (float angle)
Private Attributes
float m_a1
float m_a2
float m_b0
float m_b1
float m_b2
float m_v0
float m_v1
float m_v2
float m_deltaPhi
float m_phiHat
float m_phiHatPrev
std::complex< float > m_y
std::complex< float > m_p
float m_yRe
float m_yIm
float m_freq
float m_freqPrev
float m_freqTest
int m_lockCount
float m_lockFreq
unsigned int m_pskOrder
int m_lockTime
int m_lockTimeCount
ExpAvg m_expAvg
Detailed Description
General purpose Phase-locked loop using complex analytic signal input.
Definition at line 31 of file phaselockcomplex.h.
Constructor & Destructor Documentation
PhaseLockComplex()
PhaseLockComplex::PhaseLockComplex ()
Definition at line 29 of file phaselockcomplex.cpp.
                                    :
     m_a1(1.0),
     m_a2(1.0),
     m_b0(1.0),
     m_b1(1.0),
     m_b2(1.0),
     m_v0(0.0),
     m_v1(0.0),
     m_v2(0.0),
     m_deltaPhi(0.0),
     m_phiHat(0.0),
     m_phiHatPrev(0.0),
     m_y(1.0, 0.0),
     m_p(1.0, 0.0),
     m_yRe(1.0),
     m_yIm(0.0),
     m_freq(0.0),
     m_freqPrev(0.0),
     m_freqTest(0.0),
     m_lockCount(0),
     m_lockFreq(0.026f),
     m_pskOrder(1),
     m_lockTime(480),
     m_lockTimeCount(0)
 {
 }
Member Function Documentation
computeCoefficients()
void PhaseLockComplex::computeCoefficients (Real wn, Real zeta, Real K)
Compute loop filter parameters (active PI design)
Parameters
wn PLL bandwidth relative to Nyquist frequency
zeta PLL damping factor
K PLL loop gain
Definition at line 56 of file phaselockcomplex.cpp.
References b0, b1, b2, m_a1, m_a2, m_b0, m_b1, m_b2, and reset().
Referenced by AMDemod::AMDemod(), ChannelAnalyzer::ChannelAnalyzer(), and FreqTracker::FreqTracker().
 {
     double t1 = K/(wn*wn);          //
     double t2 = 2*zeta/wn - 1/K;   //
     double b0 = 2*K*(1.+t2/2.0f);
     double b1 = 2*K*2.;
     double b2 = 2*K*(1.-t2/2.0f);
     double a0 =  1 + t1/2.0f;
     double a1 = -t1;
     double a2 = -1 + t1/2.0f;
     qDebug("PhaseLockComplex::computeCoefficients: b_raw: %f %f %f", b0, b1, b2);
     qDebug("PhaseLockComplex::computeCoefficients: a_raw: %f %f %f", a0, a1, a2);
     m_b0 = b0 / a0;
     m_b1 = b1 / a0;
     m_b2 = b2 / a0;
     //    a0 =  1.0  is implied
     m_a1 = a1 / a0;
     m_a2 = a2 / a0;
     qDebug("PhaseLockComplex::computeCoefficients: b: %f %f %f", m_b0, m_b1, m_b2);
     qDebug("PhaseLockComplex::computeCoefficients: a: 1.0 %f %f", m_a1, m_a2);
     reset();
 }
feed()
void PhaseLockComplex::feed (float re, float im)
Feed PLL with a new signa sample
Definition at line 121 of file phaselockcomplex.cpp.
References arg(), cos(), PhaseLockComplex::ExpAvg::feed(), m_a1, m_a2, m_b0, m_b1, m_b2, m_deltaPhi, m_expAvg, m_freq, m_freqPrev, m_freqTest, m_lockCount, m_lockFreq, m_lockTime, m_lockTimeCount, m_phiHat, m_phiHatPrev, M_PI, m_pskOrder, m_v0, m_v1, m_v2, m_y, m_yIm, m_yRe, normalizeAngle(), and sin().
Referenced by ChannelAnalyzer::processOneSample(), AMDemod::processOneSample(), and FreqTracker::processOneSample().
 {
     m_yRe = cos(m_phiHat);
     m_yIm = sin(m_phiHat);
     m_y.real(m_yRe);
     m_y.imag(m_yIm);
     std::complex<float> x(re, im);
     m_deltaPhi = std::arg(x * std::conj(m_y));
     // bring phase 0 on any of the PSK symbols
     if (m_pskOrder > 1) {
         m_deltaPhi = normalizeAngle(m_pskOrder*m_deltaPhi);
     }
     // advance buffer
     m_v2 = m_v1;  // shift center register to upper register
     m_v1 = m_v0;  // shift lower register to center register
     // compute new lower register
     m_v0 = m_deltaPhi - m_v1*m_a1 - m_v2*m_a2;
     // compute new output
     m_phiHat = m_v0*m_b0 + m_v1*m_b1 + m_v2*m_b2;
     // prevent saturation
     if (m_phiHat > 2.0*M_PI)
     {
         m_v0 *= (m_phiHat - 2.0*M_PI) / m_phiHat;
         m_v1 *= (m_phiHat - 2.0*M_PI) / m_phiHat;
         m_v2 *= (m_phiHat - 2.0*M_PI) / m_phiHat;
         m_phiHat -= 2.0*M_PI;
     }
     if (m_phiHat < -2.0*M_PI)
     {
         m_v0 *= (m_phiHat + 2.0*M_PI) / m_phiHat;
         m_v1 *= (m_phiHat + 2.0*M_PI) / m_phiHat;
         m_v2 *= (m_phiHat + 2.0*M_PI) / m_phiHat;
         m_phiHat += 2.0*M_PI;
     }
     // lock and frequency estimation
     if (m_pskOrder > 1)
     {
         float dPhi = normalizeAngle(m_phiHat - m_phiHatPrev);
         m_freq = m_expAvg.feed(dPhi);
         if (m_lockTimeCount < m_lockTime-1)
         {
             m_lockTimeCount++;
         }
         else
         {
             float dF = m_freq - m_freqTest;
             if ((dF > -m_lockFreq) && (dF < m_lockFreq))
             {
                 if (m_lockCount < 20) {
                     m_lockCount++;
                 }
             }
             else
             {
                 if (m_lockCount > 0) {
                     m_lockCount--;
                 }
             }
             m_freqTest = m_freq;
             m_lockTimeCount = 0;
         }
         m_phiHatPrev = m_phiHat;
     }
     else
     {
         m_freqTest = normalizeAngle(m_phiHat - m_phiHatPrev);
         m_freq = m_expAvg.feed(m_freqTest);
         float dFreq = m_freqTest - m_freqPrev;
         if ((dFreq > -0.01) && (dFreq < 0.01))
         {
             if (m_lockCount < (m_lockTime-1)) { // [0..479]
                 m_lockCount++;
             }
         }
         else
         {
             m_lockCount = 0;
         }
         m_phiHatPrev = m_phiHat;
         m_freqPrev = m_freqTest;
     }
 }
getComplex()
const std::complex<float>& PhaseLockComplex::getComplex () const inline
Definition at line 50 of file phaselockcomplex.h.
Referenced by ChannelAnalyzer::processOneSample().
 { return m_y; }
getDeltaPhi()
float PhaseLockComplex::getDeltaPhi () const inline
Definition at line 55 of file phaselockcomplex.h.
Referenced by ChannelAnalyzer::getPllDeltaPhase().
 { return m_deltaPhi; }
getFreq()
float PhaseLockComplex::getFreq () const inline
Definition at line 54 of file phaselockcomplex.h.
Referenced by FreqTracker::getFrequency(), ChannelAnalyzer::getPllFrequency(), and AMDemod::getPllFrequency().
 { return m_freq; }
getImag()
float PhaseLockComplex::getImag () const inline
Definition at line 52 of file phaselockcomplex.h.
Referenced by AMDemod::processOneSample().
 { return m_yIm; }
getPhiHat()
float PhaseLockComplex::getPhiHat () const inline
Definition at line 56 of file phaselockcomplex.h.
Referenced by ChannelAnalyzer::getPllPhase().
 { return m_phiHat; }
getReal()
float PhaseLockComplex::getReal () const inline
Definition at line 51 of file phaselockcomplex.h.
Referenced by AMDemod::processOneSample().
 { return m_yRe; }
locked()
bool PhaseLockComplex::locked () const inline
Definition at line 53 of file phaselockcomplex.h.
Referenced by AMDemod::getPllLocked(), FreqTracker::getPllLocked(), and ChannelAnalyzer::isPllLocked().
 { return m_pskOrder > 1 ? m_lockCount > 10 : m_lockCount > m_lockTime-2; }
normalizeAngle()
float PhaseLockComplex::normalizeAngle (float angle) static private
Normalize angle in radians into the [-pi,+pi] region
Definition at line 218 of file phaselockcomplex.cpp.
References M_PI.
Referenced by feed().
 {
     while (angle <= -M_PI) {
         angle += 2.0*M_PI;
     }
     while (angle > M_PI) {
         angle -= 2.0*M_PI;
     }
     return angle;
 }
reset()
void PhaseLockComplex::reset ()
Definition at line 99 of file phaselockcomplex.cpp.
References m_deltaPhi, m_freq, m_freqPrev, m_freqTest, m_lockCount, m_lockTimeCount, m_p, m_phiHat, m_phiHatPrev, m_v0, m_v1, m_v2, m_y, m_yIm, and m_yRe.
Referenced by ChannelAnalyzer::applySettings(), FreqTracker::applySettings(), computeCoefficients(), setPskOrder(), and setSampleRate().
 {
     // reset filter accumulators and phase
     m_v0 = 0.0f;
     m_v1 = 0.0f;
     m_v2 = 0.0f;
     m_deltaPhi = 0.0f;
     m_phiHat = 0.0f;
     m_phiHatPrev = 0.0f;
     m_y.real(1.0);
     m_y.imag(0.0);
     m_p.real(1.0);
     m_p.imag(0.0);
     m_yRe = 1.0f;
     m_yIm = 0.0f;
     m_freq = 0.0f;
     m_freqPrev = 0.0f;
     m_freqTest = 0.0f;
     m_lockCount = 0;
     m_lockTimeCount = 0;
 }
setPskOrder()
void PhaseLockComplex::setPskOrder (unsigned int order)
Set the PSK order for the phase comparator
Parameters
order 0,1: no PSK (CW), 2: BPSK, 4: QPSK, 8: 8-PSK, ... use powers of two for real cases
Definition at line 86 of file phaselockcomplex.cpp.
References m_pskOrder, and reset().
Referenced by ChannelAnalyzer::applySettings(), and FreqTracker::applySettings().
 {
     m_pskOrder = order > 0 ? order : 1;
     reset();
 }
setSampleRate()
void PhaseLockComplex::setSampleRate (unsigned int sampleRate)
Set sample rate information only for frequency and lock condition calculation
Definition at line 92 of file phaselockcomplex.cpp.
References m_lockFreq, m_lockTime, M_PI, m_pskOrder, and reset().
Referenced by AMDemod::applyAudioSampleRate(), ChannelAnalyzer::applyChannelSettings(), ChannelAnalyzer::applySettings(), and FreqTracker::configureChannelizer().
 {
     m_lockTime = sampleRate / 100; // 10ms for order 1
     m_lockFreq = (2.0*M_PI*(m_pskOrder > 1 ? 6.0 : 1.0)) / sampleRate; // +/- 6 Hz frequency swing
     reset();
 }
Member Data Documentation
m_a1
float PhaseLockComplex::m_a1 private
Definition at line 85 of file phaselockcomplex.h.
Referenced by computeCoefficients(), and feed().
m_a2
float PhaseLockComplex::m_a2 private
Definition at line 86 of file phaselockcomplex.h.
Referenced by computeCoefficients(), and feed().
m_b0
float PhaseLockComplex::m_b0 private
Definition at line 87 of file phaselockcomplex.h.
Referenced by computeCoefficients(), and feed().
m_b1
float PhaseLockComplex::m_b1 private
Definition at line 88 of file phaselockcomplex.h.
Referenced by computeCoefficients(), and feed().
m_b2
float PhaseLockComplex::m_b2 private
Definition at line 89 of file phaselockcomplex.h.
Referenced by computeCoefficients(), and feed().
m_deltaPhi
float PhaseLockComplex::m_deltaPhi private
Definition at line 93 of file phaselockcomplex.h.
Referenced by feed(), and reset().
m_expAvg
ExpAvg PhaseLockComplex::m_expAvg private
Definition at line 108 of file phaselockcomplex.h.
Referenced by feed().
m_freq
float PhaseLockComplex::m_freq private
Definition at line 100 of file phaselockcomplex.h.
Referenced by feed(), and reset().
m_freqPrev
float PhaseLockComplex::m_freqPrev private
Definition at line 101 of file phaselockcomplex.h.
Referenced by feed(), and reset().
m_freqTest
float PhaseLockComplex::m_freqTest private
Definition at line 102 of file phaselockcomplex.h.
Referenced by feed(), and reset().
m_lockCount
int PhaseLockComplex::m_lockCount private
Definition at line 103 of file phaselockcomplex.h.
Referenced by feed(), and reset().
m_lockFreq
float PhaseLockComplex::m_lockFreq private
Definition at line 104 of file phaselockcomplex.h.
Referenced by feed(), and setSampleRate().
m_lockTime
int PhaseLockComplex::m_lockTime private
Definition at line 106 of file phaselockcomplex.h.
Referenced by feed(), and setSampleRate().
m_lockTimeCount
int PhaseLockComplex::m_lockTimeCount private
Definition at line 107 of file phaselockcomplex.h.
Referenced by feed(), and reset().
m_p
std::complex<float> PhaseLockComplex::m_p private
Definition at line 97 of file phaselockcomplex.h.
Referenced by reset().
m_phiHat
float PhaseLockComplex::m_phiHat private
Definition at line 94 of file phaselockcomplex.h.
Referenced by feed(), and reset().
m_phiHatPrev
float PhaseLockComplex::m_phiHatPrev private
Definition at line 95 of file phaselockcomplex.h.
Referenced by feed(), and reset().
m_pskOrder
unsigned int PhaseLockComplex::m_pskOrder private
Definition at line 105 of file phaselockcomplex.h.
Referenced by feed(), setPskOrder(), and setSampleRate().
m_v0
float PhaseLockComplex::m_v0 private
Definition at line 90 of file phaselockcomplex.h.
Referenced by feed(), and reset().
m_v1
float PhaseLockComplex::m_v1 private
Definition at line 91 of file phaselockcomplex.h.
Referenced by feed(), and reset().
m_v2
float PhaseLockComplex::m_v2 private
Definition at line 92 of file phaselockcomplex.h.
Referenced by feed(), and reset().
m_y
std::complex<float> PhaseLockComplex::m_y private
Definition at line 96 of file phaselockcomplex.h.
Referenced by feed(), and reset().
m_yIm
float PhaseLockComplex::m_yIm private
Definition at line 99 of file phaselockcomplex.h.
Referenced by feed(), and reset().
m_yRe
float PhaseLockComplex::m_yRe private
Definition at line 98 of file phaselockcomplex.h.
Referenced by feed(), and reset().
The documentation for this class was generated from the following files:
sdrbase/dsp/phaselockcomplex.h
sdrbase/dsp/phaselockcomplex.cpp