SDRAngel: BFMDemod::MsgConfigureChannelizer Class Reference
BFMDemod::MsgConfigureChannelizer Class Reference
#include <bfmdemod.h>
Public Member Functions
int getSampleRate () const
int getCenterFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (int sampleRate, int centerFrequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (int sampleRate, int centerFrequency)
Private Attributes
int m_sampleRate
int m_centerFrequency
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 81 of file bfmdemod.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
BFMDemod::MsgConfigureChannelizer::MsgConfigureChannelizer (int sampleRate, int centerFrequency) inline private
Definition at line 97 of file bfmdemod.h.
                                                                      :
             Message(),
             m_sampleRate(sampleRate),
             m_centerFrequency(centerFrequency)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* BFMDemod::MsgConfigureChannelizer::create (int sampleRate, int centerFrequency) inline static
Definition at line 88 of file bfmdemod.h.
Referenced by BFMDemodGUI::applySettings(), and BFMDemod::webapiSettingsPutPatch().
         {
             return new MsgConfigureChannelizer(sampleRate, centerFrequency);
         }
getCenterFrequency()
int BFMDemod::MsgConfigureChannelizer::getCenterFrequency () const inline
Definition at line 86 of file bfmdemod.h.
Referenced by BFMDemod::handleMessage().
 { return m_centerFrequency; }
getSampleRate()
int BFMDemod::MsgConfigureChannelizer::getSampleRate () const inline
Definition at line 85 of file bfmdemod.h.
Referenced by BFMDemod::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_centerFrequency
int BFMDemod::MsgConfigureChannelizer::m_centerFrequency private
Definition at line 95 of file bfmdemod.h.
m_sampleRate
int BFMDemod::MsgConfigureChannelizer::m_sampleRate private
Definition at line 94 of file bfmdemod.h.
The documentation for this class was generated from the following file:
plugins/channelrx/demodbfm/bfmdemod.h