SDRAngel: SyncMessenger Class Reference
SyncMessenger Class Reference
#include <syncmessenger.h>
Inherits QObject.
Signals
void messageSent ()
Public Member Functions
SyncMessenger ()
~SyncMessenger ()
int sendWait (Message &message, unsigned long msPollTime=100)
Send message and waits for its process completion.
Message * getMessage () const
void storeMessage (Message &message)
void done (int result=0)
Processing of the message is complete.
Protected Attributes
QWaitCondition m_waitCondition
QMutex m_mutex
QAtomicInt m_complete
Message * m_message
int m_result
Detailed Description
This class is responsible of managing the synchronous processing of a message across threads
Definition at line 33 of file syncmessenger.h.
Constructor & Destructor Documentation
SyncMessenger()
SyncMessenger::SyncMessenger ()
Definition at line 22 of file syncmessenger.cpp.
                              :
     m_complete(0),
     m_message(0),
     m_result(0)
 {
     qRegisterMetaType<Message>("Message");
 }
~SyncMessenger()
SyncMessenger::~SyncMessenger ()
Definition at line 30 of file syncmessenger.cpp.
 {}
Member Function Documentation
done()
void SyncMessenger::done (int result = 0)
Processing of the message is complete.
Definition at line 52 of file syncmessenger.cpp.
References m_complete, m_result, and m_waitCondition.
Referenced by DSPDeviceSinkEngine::handleSynchronousMessages(), DSPDeviceSourceEngine::handleSynchronousMessages(), and DSPDeviceMIMOEngine::handleSynchronousMessages().
 {
     m_result = result;
     m_complete.store(1);
     m_waitCondition.wakeAll();
 }
getMessage()
Message* SyncMessenger::getMessage () const inline
Definition at line 41 of file syncmessenger.h.
Referenced by DSPDeviceSinkEngine::handleSynchronousMessages(), DSPDeviceSourceEngine::handleSynchronousMessages(), and DSPDeviceMIMOEngine::handleSynchronousMessages().
 { return m_message; }
messageSent
void SyncMessenger::messageSent () signal
Referenced by sendWait().
sendWait()
int SyncMessenger::sendWait (Message & message, unsigned long msPollTime = 100)
Send message and waits for its process completion.
Definition at line 33 of file syncmessenger.cpp.
References m_complete, m_message, m_mutex, m_result, m_waitCondition, and messageSent().
Referenced by DSPDeviceMIMOEngine::addAncillarySink(), DSPDeviceMIMOEngine::addChannelSink(), DSPDeviceMIMOEngine::addChannelSource(), DSPDeviceSourceEngine::addSink(), DSPDeviceMIMOEngine::addSinkStream(), DSPDeviceMIMOEngine::addSourceStream(), DSPDeviceSinkEngine::addSpectrumSink(), DSPDeviceMIMOEngine::addSpectrumSink(), DSPDeviceSourceEngine::addThreadedSink(), DSPDeviceSinkEngine::addThreadedSource(), DSPDeviceMIMOEngine::deviceDescription(), DSPDeviceSourceEngine::errorMessage(), DSPDeviceSinkEngine::errorMessage(), DSPDeviceMIMOEngine::errorMessage(), DSPDeviceSourceEngine::initAcquisition(), DSPDeviceSinkEngine::initGeneration(), DSPDeviceMIMOEngine::initProcess(), DSPDeviceMIMOEngine::removeAncillarySink(), DSPDeviceMIMOEngine::removeChannelSink(), DSPDeviceMIMOEngine::removeChannelSource(), DSPDeviceMIMOEngine::removeLastSinkStream(), DSPDeviceMIMOEngine::removeLastSourceStream(), DSPDeviceSourceEngine::removeSink(), DSPDeviceSinkEngine::removeSpectrumSink(), DSPDeviceMIMOEngine::removeSpectrumSink(), DSPDeviceSourceEngine::removeThreadedSink(), DSPDeviceSinkEngine::removeThreadedSource(), DSPDeviceMIMOEngine::setMIMO(), DSPDeviceSinkEngine::setSink(), DSPDeviceSourceEngine::setSource(), DSPDeviceMIMOEngine::setSpectrumSinkInput(), DSPDeviceSinkEngine::sinkDeviceDescription(), DSPDeviceSourceEngine::sourceDeviceDescription(), DSPDeviceSourceEngine::startAcquisition(), DSPDeviceSinkEngine::startGeneration(), and DSPDeviceMIMOEngine::startProcess().
 {
     m_message = &message;
     m_mutex.lock();
     m_complete.store(0);
     emit messageSent();
     while (!m_complete.load())
     {
         m_waitCondition.wait(&m_mutex, msPollTime);
     }
     int result = m_result;
     m_mutex.unlock();
     return result;
 }
storeMessage()
void SyncMessenger::storeMessage (Message & message) inline
Definition at line 42 of file syncmessenger.h.
Referenced by DSPDeviceSourceEngine::stopAcquistion(), DSPDeviceSinkEngine::stopGeneration(), and DSPDeviceMIMOEngine::stopProcess().
 { m_message = &message; }
Member Data Documentation
m_complete
QAtomicInt SyncMessenger::m_complete protected
Definition at line 51 of file syncmessenger.h.
Referenced by done(), and sendWait().
m_message
Message* SyncMessenger::m_message protected
Definition at line 52 of file syncmessenger.h.
Referenced by sendWait().
m_mutex
QMutex SyncMessenger::m_mutex protected
Definition at line 50 of file syncmessenger.h.
Referenced by sendWait().
m_result
int SyncMessenger::m_result protected
Definition at line 53 of file syncmessenger.h.
Referenced by done(), and sendWait().
m_waitCondition
QWaitCondition SyncMessenger::m_waitCondition protected
Definition at line 49 of file syncmessenger.h.
Referenced by done(), and sendWait().
The documentation for this class was generated from the following files:
sdrbase/util/syncmessenger.h
sdrbase/util/syncmessenger.cpp