SDRAngel: DownChannelizer::FilterStage Struct Reference
DownChannelizer::FilterStage Struct Reference
#include <downchannelizer.h>
Public Types
enum Mode { ModeCenter, ModeLowerHalf, ModeUpperHalf }
typedef bool(IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::* WorkFunction) (Sample *s)
Public Member Functions
FilterStage (Mode mode)
~FilterStage ()
bool work (Sample *sample)
Public Attributes
IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER > * m_filter
WorkFunction m_workFunction
Mode m_mode
bool m_sse
Detailed Description
Definition at line 92 of file downchannelizer.h.
Member Typedef Documentation
WorkFunction
typedef bool(IntHalfbandFilterEO<qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER>::* DownChannelizer::FilterStage::WorkFunction) (Sample *s)
Definition at line 103 of file downchannelizer.h.
Member Enumeration Documentation
Mode
enum DownChannelizer::FilterStage::Mode
Enumerator
ModeCenter
ModeLowerHalf
ModeUpperHalf
Definition at line 93 of file downchannelizer.h.
                   {
             ModeCenter,
             ModeLowerHalf,
             ModeUpperHalf
         };
Constructor & Destructor Documentation
FilterStage()
DownChannelizer::FilterStage::FilterStage (Mode mode)
Definition at line 270 of file downchannelizer.cpp.
References m_workFunction, ModeCenter, ModeLowerHalf, and ModeUpperHalf.
Referenced by DownChannelizer::applySetting(), DownChannelizer::createFilterChain(), and DownChannelizer::setFilterChain().
                                                  :
     m_filter(new IntHalfbandFilterEO<qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER>),
     m_workFunction(0),
     m_mode(mode),
     m_sse(true)
 {
     switch(mode) {
         case ModeCenter:
             m_workFunction = &IntHalfbandFilterEO<qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER>::workDecimateCenter;
             break;
         case ModeLowerHalf:
             m_workFunction = &IntHalfbandFilterEO<qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER>::workDecimateLowerHalf;
             break;
         case ModeUpperHalf:
             m_workFunction = &IntHalfbandFilterEO<qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER>::workDecimateUpperHalf;
             break;
     }
 }
~FilterStage()
DownChannelizer::FilterStage::~FilterStage ()
Definition at line 292 of file downchannelizer.cpp.
References m_filter.
 {
     delete m_filter;
 }
Member Function Documentation
work()
bool DownChannelizer::FilterStage::work (Sample * sample) inline
Definition at line 114 of file downchannelizer.h.
         {
             return (m_filter->*m_workFunction)(sample);
         }
Member Data Documentation
m_filter
IntHalfbandFilterEO<qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER>* DownChannelizer::FilterStage::m_filter
Definition at line 104 of file downchannelizer.h.
Referenced by ~FilterStage().
m_mode
Mode DownChannelizer::FilterStage::m_mode
Definition at line 108 of file downchannelizer.h.
m_sse
bool DownChannelizer::FilterStage::m_sse
Definition at line 109 of file downchannelizer.h.
m_workFunction
WorkFunction DownChannelizer::FilterStage::m_workFunction
Definition at line 107 of file downchannelizer.h.
Referenced by FilterStage().
The documentation for this struct was generated from the following files:
sdrbase/dsp/downchannelizer.h
sdrbase/dsp/downchannelizer.cpp