SDRAngel: qrtplib::RTPTime Class Reference
qrtplib::RTPTime Class Reference
#include <rtptimeutilities.h>
Public Member Functions
RTPTime (double t)
RTPTime (RTPNTPTime ntptime)
RTPTime (int64_t seconds, uint32_t microseconds)
int64_t GetSeconds () const
uint32_t GetMicroSeconds () const
double GetDouble () const
RTPNTPTime GetNTPTime () const
RTPTime & operator-= (const RTPTime &t)
RTPTime & operator+= (const RTPTime &t)
bool operator< (const RTPTime &t) const
bool operator> (const RTPTime &t) const
bool operator<= (const RTPTime &t) const
bool operator>= (const RTPTime &t) const
bool IsZero () const
Static Public Member Functions
static RTPTime CurrentTime ()
static void Wait (const RTPTime &delay)
Private Attributes
double m_t
Detailed Description
This class is used to specify wallclock time, delay intervals etc. This class is used to specify wallclock time, delay intervals etc. It stores a number of seconds and a number of microseconds.
Definition at line 103 of file rtptimeutilities.h.
Constructor & Destructor Documentation
RTPTime() [1/3]
qrtplib::RTPTime::RTPTime (double t) inline
Creates an RTPTime instance representing t, which is expressed in units of seconds.
Definition at line 162 of file rtptimeutilities.h.
 {
     m_t = t;
 }
RTPTime() [2/3]
qrtplib::RTPTime::RTPTime (RTPNTPTime ntptime) inline
Creates an instance that corresponds to ntptime. Creates an instance that corresponds to ntptime. If the conversion cannot be made, both the seconds and the microseconds are set to zero.
Definition at line 182 of file rtptimeutilities.h.
References qrtplib::RTPNTPTime::GetLSW(), qrtplib::RTPNTPTime::GetMSW(), and RTP_NTPTIMEOFFSET.
 {
     if (ntptime.GetMSW() < RTP_NTPTIMEOFFSET)
     {
         m_t = 0;
     }
     else
     {
         uint32_t sec = ntptime.GetMSW() - RTP_NTPTIMEOFFSET;
         double x = (double) ntptime.GetLSW();
         x /= (65536.0 * 65536.0);
         x *= 1000000.0;
         uint32_t microsec = (uint32_t) x;
         m_t = (double) sec + 1e-6 * (double) microsec;
     }
 }
RTPTime() [3/3]
qrtplib::RTPTime::RTPTime (int64_t seconds, uint32_t microseconds) inline
Creates an instance corresponding to seconds and microseconds.
Definition at line 167 of file rtptimeutilities.h.
 {
     if (seconds >= 0)
     {
         m_t = (double) seconds + 1e-6 * (double) microseconds;
     }
     else
     {
         int64_t possec = -seconds;
         m_t = (double) possec + 1e-6 * (double) microseconds;
         m_t = -m_t;
     }
 }
Member Function Documentation
CurrentTime()
RTPTime qrtplib::RTPTime::CurrentTime () inline static
Returns an RTPTime instance representing the current wallclock time. Returns an RTPTime instance representing the current wallclock time. This is expressed as a number of seconds since 00:00:00 UTC, January 1, 1970.
Definition at line 293 of file rtptimeutilities.h.
References qrtplib::RTPTime_timespecToDouble().
Referenced by qrtplib::RTCPPacketBuilder::BuildBYEPacket(), qrtplib::RTCPPacketBuilder::BuildNextPacket(), qrtplib::RTPSession::BYEDestroy(), qrtplib::RTCPScheduler::CalculateNextRTCPTime(), GetMicroSeconds(), qrtplib::RTCPScheduler::GetTransmissionDelay(), qrtplib::RTCPScheduler::IsTime(), qrtplib::RTCPScheduler::PerformReverseReconsideration(), qrtplib::RTPPacketBuilder::PrivateBuildPacket(), qrtplib::RTPSession::ProcessPolledData(), qrtplib::RTPUDPTransmitter::readRTCPPendingDatagrams(), qrtplib::RTPUDPTransmitter::readRTPPendingDatagrams(), qrtplib::RTCPScheduler::ScheduleBYEPacket(), and qrtplib::RTPInternalSourceData::SentRTPPacket().
 {
     static bool s_initialized = false;
     static double s_startOffet = 0;
     if (!s_initialized)
     {
         s_initialized = true;
         // Get the corresponding times in system time and monotonic time
         struct timespec tpSys, tpMono;
         clock_gettime(CLOCK_REALTIME, &tpSys);
         clock_gettime(CLOCK_MONOTONIC, &tpMono);
         double tSys = RTPTime_timespecToDouble(tpSys);
         double tMono = RTPTime_timespecToDouble(tpMono);
         s_startOffet = tSys - tMono;
         return tSys;
     }
     struct timespec tpMono;
     clock_gettime(CLOCK_MONOTONIC, &tpMono);
     double tMono0 = RTPTime_timespecToDouble(tpMono);
     return tMono0 + s_startOffet;
 }
GetDouble()
double qrtplib::RTPTime::GetDouble () const inline
Returns the time stored in this instance, expressed in units of seconds.
Definition at line 135 of file rtptimeutilities.h.
Referenced by qrtplib::RTCPPacketBuilder::BuildBYEPacket(), qrtplib::RTCPPacketBuilder::BuildNextPacket(), qrtplib::RTCPScheduler::CalculateBYETransmissionInterval(), qrtplib::RTCPScheduler::CalculateDeterministicInterval(), qrtplib::RTCPScheduler::CalculateTransmissionInterval(), qrtplib::RTCPPacketBuilder::FillInReportBlocks(), qrtplib::RTPSourceData::INF_GetEstimatedTimestampUnit(), qrtplib::RTCPScheduler::PerformReverseReconsideration(), qrtplib::RTPSourceStats::ProcessPacket(), qrtplib::RTPSession::ProcessPolledData(), and qrtplib::RTCPSchedulerParams::SetMinimumTransmissionInterval().
     {
         return m_t;
     }
GetMicroSeconds()
uint32_t qrtplib::RTPTime::GetMicroSeconds () const inline
Returns the number of microseconds stored in this instance.
Definition at line 206 of file rtptimeutilities.h.
References C1000000, CEPOCH, CurrentTime(), m_t, and Wait().
 {
     uint32_t microsec;
     if (m_t >= 0)
     {
         int64_t sec = (int64_t) m_t;
         microsec = (uint32_t) (1e6 * (m_t - (double) sec) + 0.5);
     }
     else // m_t < 0
     {
         int64_t sec = (int64_t) (-m_t);
         microsec = (uint32_t) (1e6 * ((-m_t) - (double) sec) + 0.5);
     }
     if (microsec >= 1000000)
         return 999999;
     // Unsigned, it can never be less than 0
     // if (microsec < 0)
     //  return 0;
     return microsec;
 }
GetNTPTime()
RTPNTPTime qrtplib::RTPTime::GetNTPTime () const inline
Returns the NTP time corresponding to the time stored in this instance.
Definition at line 367 of file rtptimeutilities.h.
References RTP_NTPTIMEOFFSET.
Referenced by qrtplib::RTCPPacketBuilder::BuildBYEPacket(), qrtplib::RTCPPacketBuilder::BuildNextPacket(), and qrtplib::RTPSourceData::INF_GetRoundtripTime().
 {
     uint32_t sec = (uint32_t) m_t;
     uint32_t microsec = (uint32_t) ((m_t - (double) sec) * 1e6);
     uint32_t msw = sec + RTP_NTPTIMEOFFSET;
     uint32_t lsw;
     double x;
     x = microsec / 1000000.0;
     x *= (65536.0 * 65536.0);
     lsw = (uint32_t) x;
     return RTPNTPTime(msw, lsw);
 }
GetSeconds()
int64_t qrtplib::RTPTime::GetSeconds () const inline
Returns the number of seconds stored in this instance.
Definition at line 201 of file rtptimeutilities.h.
 {
     return (int64_t) m_t;
 }
IsZero()
bool qrtplib::RTPTime::IsZero () const inline
Definition at line 150 of file rtptimeutilities.h.
Referenced by qrtplib::RTPSourceData::INF_GetEstimatedTimestampUnit().
     {
         return m_t == 0.0;
     }
operator+=()
RTPTime & qrtplib::RTPTime::operator+= (const RTPTime & t) inline
Definition at line 361 of file rtptimeutilities.h.
References m_t.
 {
     m_t += t.m_t;
     return *this;
 }
operator-=()
RTPTime & qrtplib::RTPTime::operator-= (const RTPTime & t) inline
Definition at line 355 of file rtptimeutilities.h.
References m_t.
 {
     m_t -= t.m_t;
     return *this;
 }
operator<()
bool qrtplib::RTPTime::operator< (const RTPTime & t) const inline
Definition at line 383 of file rtptimeutilities.h.
References m_t.
 {
     return m_t < t.m_t;
 }
operator<=()
bool qrtplib::RTPTime::operator<= (const RTPTime & t) const inline
Definition at line 393 of file rtptimeutilities.h.
References m_t.
 {
     return m_t <= t.m_t;
 }
operator>()
bool qrtplib::RTPTime::operator> (const RTPTime & t) const inline
Definition at line 388 of file rtptimeutilities.h.
References m_t.
 {
     return m_t > t.m_t;
 }
operator>=()
bool qrtplib::RTPTime::operator>= (const RTPTime & t) const inline
Definition at line 398 of file rtptimeutilities.h.
References m_t.
 {
     return m_t >= t.m_t;
 }
Wait()
void qrtplib::RTPTime::Wait (const RTPTime & delay) inline static
This function waits the amount of time specified in delay.
Definition at line 333 of file rtptimeutilities.h.
References m_t.
Referenced by qrtplib::RTPSession::BYEDestroy(), and GetMicroSeconds().
 {
     if (delay.m_t <= 0)
         return;
     uint64_t sec = (uint64_t) delay.m_t;
     uint64_t nanosec = (uint32_t) (1e9 * (delay.m_t - (double) sec));
     struct timespec req, rem;
     int ret;
     req.tv_sec = (time_t) sec;
     req.tv_nsec = ((long) nanosec);
     do
     {
         ret = nanosleep(&req, &rem);
         req = rem;
     } while (ret == -1 && errno == EINTR);
 }
Member Data Documentation
m_t
double qrtplib::RTPTime::m_t private
Definition at line 159 of file rtptimeutilities.h.
Referenced by GetMicroSeconds(), operator+=(), operator-=(), operator<(), operator<=(), operator>(), operator>=(), and Wait().
The documentation for this class was generated from the following file:
qrtplib/rtptimeutilities.h