SDRAngel: leansdr::s2_fecenc Struct Reference
leansdr::s2_fecenc Struct Reference
#include <dvbs2.h>
Public Types
typedef ldpc_engine< bool, hard_sb, 8, uint16_t > s2_ldpc_engine
Public Member Functions
s2_fecenc (scheduler *sch, pipebuf< bbframe > &_in, pipebuf< fecframe< hard_sb >> &_out)
void run ()
Public Member Functions inherited from leansdr::runnable
runnable (scheduler *_sch, const char *name)
Public Member Functions inherited from leansdr::runnable_common
runnable_common (const char *_name)
virtual ~runnable_common ()
virtual void shutdown ()
Private Member Functions
void run_frame (const bbframe *pin, fecframe< hard_sb > *pout)
Private Attributes
pipereader< bbframe > in
pipewriter< fecframe< hard_sb > > out
s2_bbscrambling bbscrambling
s2_bch_engines s2bch
s2_ldpc_engines< bool, hard_sb > s2ldpc
Additional Inherited Members
Public Attributes inherited from leansdr::runnable_common
const char * name
Protected Attributes inherited from leansdr::runnable
scheduler * sch
Detailed Description
Definition at line 2034 of file dvbs2.h.
Member Typedef Documentation
s2_ldpc_engine
typedef ldpc_engine<bool, hard_sb, 8, uint16_t> leansdr::s2_fecenc::s2_ldpc_engine
Definition at line 2036 of file dvbs2.h.
Constructor & Destructor Documentation
s2_fecenc()
leansdr::s2_fecenc::s2_fecenc (scheduler * sch, pipebuf< bbframe > & _in, pipebuf< fecframe< hard_sb >> & _out) inline
Definition at line 2037 of file dvbs2.h.
References leansdr::scheduler::debug.
         : runnable(sch, "S2 fecenc"),
           in(_in), out(_out)
     {
         if (sch->debug)
             s2ldpc.print_node_stats();
     }
Member Function Documentation
run()
void leansdr::s2_fecenc::run () inline virtual
Reimplemented from leansdr::runnable_common.
Definition at line 2045 of file dvbs2.h.
References leansdr::pipereader< T >::rd(), leansdr::pipereader< T >::read(), leansdr::pipereader< T >::readable(), leansdr::pipewriter< T >::wr(), leansdr::pipewriter< T >::writable(), and leansdr::pipewriter< T >::written().
     {
         while (in.readable() >= 1 && out.writable() >= 1)
         {
             bbframe *pin = in.rd();
             fecframe<hard_sb> *pout = out.wr();
             run_frame(in.rd(), out.wr());
             in.read(1);
             out.written(1);
         }
     }
run_frame()
void leansdr::s2_fecenc::run_frame (const bbframe * pin, fecframe< hard_sb > * pout) inline private
Definition at line 2058 of file dvbs2.h.
References leansdr::fecframe< SOFTBYTE >::bytes, leansdr::bbframe::bytes, leansdr::check_modcod(), leansdr::bch_interface::encode(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::encode(), leansdr::s2_pls::framebits(), leansdr::s2_pls::modcod, leansdr::fecframe< SOFTBYTE >::pls, leansdr::bbframe::pls, leansdr::modcod_info::rate, and leansdr::s2_pls::sf.
     {
         const modcod_info *mcinfo = check_modcod(pin->pls.modcod);
         const fec_info *fi = &fec_infos[pin->pls.sf][mcinfo->rate];
         pout->pls = pin->pls;
         hard_sb *pbytes = pout->bytes;
         bbscrambling.transform(pin->bytes, fi->Kbch / 8, pbytes);
         { // BCH
             size_t msgbytes = fi->Kbch / 8;
             size_t cwbytes = fi->kldpc / 8;
             bch_interface *bch = s2bch.bchs[pin->pls.sf][mcinfo->rate];
             bch->encode(pbytes, msgbytes, pbytes + msgbytes);
         }
         { // LDPC
             size_t msgbits = fi->kldpc;
             size_t cwbits = pin->pls.framebits();
             s2_ldpc_engine *ldpc = s2ldpc.ldpcs[pin->pls.sf][mcinfo->rate];
             ldpc->encode(fi->ldpc, pbytes, msgbits, cwbits, pbytes + msgbits / 8);
         }
     }
Member Data Documentation
bbscrambling
s2_bbscrambling leansdr::s2_fecenc::bbscrambling private
Definition at line 2080 of file dvbs2.h.
in
pipereader<bbframe> leansdr::s2_fecenc::in private
Definition at line 2078 of file dvbs2.h.
out
pipewriter<fecframe<hard_sb> > leansdr::s2_fecenc::out private
Definition at line 2079 of file dvbs2.h.
s2bch
s2_bch_engines leansdr::s2_fecenc::s2bch private
Definition at line 2081 of file dvbs2.h.
s2ldpc
s2_ldpc_engines<bool, hard_sb> leansdr::s2_fecenc::s2ldpc private
Definition at line 2082 of file dvbs2.h.
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/dvbs2.h