SDRAngel: FreqTracker::MsgConfigureFreqTracker Class Reference
FreqTracker::MsgConfigureFreqTracker Class Reference
#include <freqtracker.h>
Public Member Functions
const FreqTrackerSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureFreqTracker * create (const FreqTrackerSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureFreqTracker (const FreqTrackerSettings &settings, bool force)
Private Attributes
FreqTrackerSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 52 of file freqtracker.h.
Constructor & Destructor Documentation
MsgConfigureFreqTracker()
FreqTracker::MsgConfigureFreqTracker::MsgConfigureFreqTracker (const FreqTrackerSettings & settings, bool force) inline private
Definition at line 68 of file freqtracker.h.
Referenced by create().
                                                                                  :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureFreqTracker* FreqTracker::MsgConfigureFreqTracker::create (const FreqTrackerSettings & settings, bool force) inline static
Definition at line 59 of file freqtracker.h.
References MsgConfigureFreqTracker().
Referenced by FreqTrackerGUI::applySettings(), FreqTracker::deserialize(), and FreqTracker::webapiSettingsPutPatch().
         {
             return new MsgConfigureFreqTracker(settings, force);
         }
getForce()
bool FreqTracker::MsgConfigureFreqTracker::getForce () const inline
Definition at line 57 of file freqtracker.h.
References m_force.
Referenced by FreqTracker::handleMessage().
 { return m_force; }
getSettings()
const FreqTrackerSettings& FreqTracker::MsgConfigureFreqTracker::getSettings () const inline
Definition at line 56 of file freqtracker.h.
References m_settings.
Referenced by FreqTrackerGUI::handleMessage(), and FreqTracker::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool FreqTracker::MsgConfigureFreqTracker::m_force private
Definition at line 66 of file freqtracker.h.
Referenced by getForce().
m_settings
FreqTrackerSettings FreqTracker::MsgConfigureFreqTracker::m_settings private
Definition at line 65 of file freqtracker.h.
Referenced by FreqTracker::getCenterFrequency(), FreqTracker::getPllLocked(), getSettings(), FreqTracker::getStreamCenterFrequency(), and FreqTracker::getTitle().
The documentation for this class was generated from the following file:
plugins/channelrx/freqtracker/freqtracker.h