SDRAngel: FSample Struct Reference
FSample Struct Reference
#include <dsptypes.h>
Public Member Functions
FSample ()
FSample (Real real)
FSample (Real real, Real imag)
FSample (const FSample &other)
FSample & operator= (const FSample &other)
FSample & operator+= (const FSample &other)
FSample & operator-= (const FSample &other)
FSample & operator/= (const Real &divisor)
void setReal (Real v)
void setImag (Real v)
Real real () const
Real imag () const
Public Attributes
Real m_real
Real m_imag
Detailed Description
Definition at line 68 of file dsptypes.h.
Constructor & Destructor Documentation
FSample() [1/4]
FSample::FSample () inline
Definition at line 70 of file dsptypes.h.
 : m_real(0), m_imag(0) {}
FSample() [2/4]
FSample::FSample (Real real) inline
Definition at line 71 of file dsptypes.h.
 : m_real(real), m_imag(0) {}
FSample() [3/4]
FSample::FSample (Real real, Real imag) inline
Definition at line 72 of file dsptypes.h.
 : m_real(real), m_imag(imag) {}
FSample() [4/4]
FSample::FSample (const FSample & other) inline
Definition at line 73 of file dsptypes.h.
 : m_real(other.m_real), m_imag(other.m_imag) {}
Member Function Documentation
imag()
Real FSample::imag () const inline
Definition at line 84 of file dsptypes.h.
References Sample::m_imag.
Referenced by IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::myDecimate(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::myInterpolateZeroStuffing(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workDecimateCenter(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalf(), and IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalfZeroStuffing().
 { return m_imag; }
operator+=()
FSample& FSample::operator+= (const FSample & other) inline
Definition at line 76 of file dsptypes.h.
References Sample::m_imag, m_imag, Sample::m_real, and m_real.
 { m_real += other.m_real; m_imag += other.m_imag; return *this; }
operator-=()
FSample& FSample::operator-= (const FSample & other) inline
Definition at line 77 of file dsptypes.h.
References Sample::m_imag, m_imag, Sample::m_real, and m_real.
 { m_real -= other.m_real; m_imag -= other.m_imag; return *this; }
operator/=()
FSample& FSample::operator/= (const Real & divisor) inline
Definition at line 78 of file dsptypes.h.
References Sample::m_imag, and Sample::m_real.
 { m_real /= divisor; m_imag /= divisor; return *this; }
operator=()
FSample& FSample::operator= (const FSample & other) inline
Definition at line 74 of file dsptypes.h.
References Sample::m_imag, m_imag, Sample::m_real, and m_real.
 { m_real = other.m_real; m_imag = other.m_imag; return *this; }
real()
Real FSample::real () const inline
Definition at line 83 of file dsptypes.h.
References Sample::m_real.
Referenced by IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::myDecimate(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::myInterpolateZeroStuffing(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workDecimateCenter(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalf(), and IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalfZeroStuffing().
 { return m_real; }
setImag()
void FSample::setImag (Real v) inline
Definition at line 81 of file dsptypes.h.
References Sample::m_imag.
Referenced by IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::doFIR(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::doInterpolateFIR(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalf(), and IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalfZeroStuffing().
 { m_imag = v; }
setReal()
void FSample::setReal (Real v) inline
Definition at line 80 of file dsptypes.h.
References Sample::m_real.
Referenced by IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::doFIR(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::doInterpolateFIR(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalf(), and IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalfZeroStuffing().
 { m_real = v; }
Member Data Documentation
m_imag
Real FSample::m_imag
Definition at line 87 of file dsptypes.h.
Referenced by operator+=(), operator-=(), and operator=().
m_real
Real FSample::m_real
Definition at line 86 of file dsptypes.h.
Referenced by operator+=(), operator-=(), and operator=().
The documentation for this struct was generated from the following file:
sdrbase/dsp/dsptypes.h