SDRAngel: SWGSDRangel::SWGRDSReport_altFrequencies Class Reference
SWGSDRangel::SWGRDSReport_altFrequencies Class Reference
#include <SWGRDSReport_altFrequencies.h>
Public Member Functions
SWGRDSReport_altFrequencies ()
SWGRDSReport_altFrequencies (QString *json)
virtual ~SWGRDSReport_altFrequencies ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGRDSReport_altFrequencies * fromJson (QString &jsonString) override
float getFrequency ()
void setFrequency (float frequency)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
float frequency
bool m_frequency_isSet
Detailed Description
Definition at line 31 of file SWGRDSReport_altFrequencies.h.
Constructor & Destructor Documentation
SWGRDSReport_altFrequencies() [1/2]
SWGSDRangel::SWGRDSReport_altFrequencies::SWGRDSReport_altFrequencies ()
Definition at line 30 of file SWGRDSReport_altFrequencies.cpp.
References frequency, and m_frequency_isSet.
{
     frequency = 0.0f;
     m_frequency_isSet = false;
 }
SWGRDSReport_altFrequencies() [2/2]
SWGSDRangel::SWGRDSReport_altFrequencies::SWGRDSReport_altFrequencies (QString * json)
Definition at line 25 of file SWGRDSReport_altFrequencies.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGRDSReport_altFrequencies()
SWGSDRangel::SWGRDSReport_altFrequencies::~SWGRDSReport_altFrequencies () virtual
Definition at line 35 of file SWGRDSReport_altFrequencies.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGRDSReport_altFrequencies::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 66 of file SWGRDSReport_altFrequencies.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGRDSReport_altFrequencies::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 77 of file SWGRDSReport_altFrequencies.cpp.
References frequency, and m_frequency_isSet.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_frequency_isSet){
         obj->insert("frequency", QJsonValue(frequency));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGRDSReport_altFrequencies::cleanup ()
Definition at line 46 of file SWGRDSReport_altFrequencies.cpp.
Referenced by ~SWGRDSReport_altFrequencies().
{
 }
fromJson()
SWGRDSReport_altFrequencies * SWGSDRangel::SWGRDSReport_altFrequencies::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 51 of file SWGRDSReport_altFrequencies.cpp.
References fromJsonObject().
Referenced by SWGRDSReport_altFrequencies().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGRDSReport_altFrequencies::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 60 of file SWGRDSReport_altFrequencies.cpp.
References frequency, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&frequency, pJson["frequency"], "float", "");
 }
getFrequency()
float SWGSDRangel::SWGRDSReport_altFrequencies::getFrequency ()
Definition at line 87 of file SWGRDSReport_altFrequencies.cpp.
References frequency.
{
     return frequency;
 }
init()
void SWGSDRangel::SWGRDSReport_altFrequencies::init ()
Definition at line 40 of file SWGRDSReport_altFrequencies.cpp.
References frequency, and m_frequency_isSet.
Referenced by SWGRDSReport_altFrequencies().
{
     frequency = 0.0f;
     m_frequency_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGRDSReport_altFrequencies::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 98 of file SWGRDSReport_altFrequencies.cpp.
References m_frequency_isSet.
{
     bool isObjectUpdated = false;
     do{
         if(m_frequency_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setFrequency()
void SWGSDRangel::SWGRDSReport_altFrequencies::setFrequency (float frequency)
Definition at line 91 of file SWGRDSReport_altFrequencies.cpp.
References frequency, and m_frequency_isSet.
{
     this->frequency = frequency;
     this->m_frequency_isSet = true;
 }
Member Data Documentation
frequency
float SWGSDRangel::SWGRDSReport_altFrequencies::frequency private
Definition at line 51 of file SWGRDSReport_altFrequencies.h.
Referenced by asJsonObject(), fromJsonObject(), getFrequency(), init(), setFrequency(), and SWGRDSReport_altFrequencies().
m_frequency_isSet
bool SWGSDRangel::SWGRDSReport_altFrequencies::m_frequency_isSet private
Definition at line 52 of file SWGRDSReport_altFrequencies.h.
Referenced by asJsonObject(), init(), isSet(), setFrequency(), and SWGRDSReport_altFrequencies().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGRDSReport_altFrequencies.h
swagger/sdrangel/code/qt5/client/SWGRDSReport_altFrequencies.cpp