SDRAngel: SWGSDRangel::SWGWFMModReport Class Reference
SWGSDRangel::SWGWFMModReport Class Reference
#include <SWGWFMModReport.h>
Public Member Functions
SWGWFMModReport ()
SWGWFMModReport (QString *json)
virtual ~SWGWFMModReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGWFMModReport * fromJson (QString &jsonString) override
float getChannelPowerDb ()
void setChannelPowerDb (float channel_power_db)
qint32 getAudioSampleRate ()
void setAudioSampleRate (qint32 audio_sample_rate)
qint32 getChannelSampleRate ()
void setChannelSampleRate (qint32 channel_sample_rate)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
float channel_power_db
bool m_channel_power_db_isSet
qint32 audio_sample_rate
bool m_audio_sample_rate_isSet
qint32 channel_sample_rate
bool m_channel_sample_rate_isSet
Detailed Description
Definition at line 31 of file SWGWFMModReport.h.
Constructor & Destructor Documentation
SWGWFMModReport() [1/2]
SWGSDRangel::SWGWFMModReport::SWGWFMModReport ()
Definition at line 30 of file SWGWFMModReport.cpp.
References audio_sample_rate, channel_power_db, channel_sample_rate, m_audio_sample_rate_isSet, m_channel_power_db_isSet, and m_channel_sample_rate_isSet.
{
     channel_power_db = 0.0f;
     m_channel_power_db_isSet = false;
     audio_sample_rate = 0;
     m_audio_sample_rate_isSet = false;
     channel_sample_rate = 0;
     m_channel_sample_rate_isSet = false;
 }
SWGWFMModReport() [2/2]
SWGSDRangel::SWGWFMModReport::SWGWFMModReport (QString * json)
Definition at line 25 of file SWGWFMModReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGWFMModReport()
SWGSDRangel::SWGWFMModReport::~SWGWFMModReport () virtual
Definition at line 39 of file SWGWFMModReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGWFMModReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 80 of file SWGWFMModReport.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGWFMModReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 91 of file SWGWFMModReport.cpp.
References audio_sample_rate, channel_power_db, channel_sample_rate, m_audio_sample_rate_isSet, m_channel_power_db_isSet, and m_channel_sample_rate_isSet.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_channel_power_db_isSet){
         obj->insert("channelPowerDB", QJsonValue(channel_power_db));
     }
     if(m_audio_sample_rate_isSet){
         obj->insert("audioSampleRate", QJsonValue(audio_sample_rate));
     }
     if(m_channel_sample_rate_isSet){
         obj->insert("channelSampleRate", QJsonValue(channel_sample_rate));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGWFMModReport::cleanup ()
Definition at line 54 of file SWGWFMModReport.cpp.
Referenced by ~SWGWFMModReport().
{
 }
fromJson()
SWGWFMModReport * SWGSDRangel::SWGWFMModReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 61 of file SWGWFMModReport.cpp.
References fromJsonObject().
Referenced by SWGWFMModReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGWFMModReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 70 of file SWGWFMModReport.cpp.
References audio_sample_rate, channel_power_db, channel_sample_rate, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&channel_power_db, pJson["channelPowerDB"], "float", "");
     ::SWGSDRangel::setValue(&audio_sample_rate, pJson["audioSampleRate"], "qint32", "");
     ::SWGSDRangel::setValue(&channel_sample_rate, pJson["channelSampleRate"], "qint32", "");
 }
getAudioSampleRate()
qint32 SWGSDRangel::SWGWFMModReport::getAudioSampleRate ()
Definition at line 117 of file SWGWFMModReport.cpp.
References audio_sample_rate.
{
     return audio_sample_rate;
 }
getChannelPowerDb()
float SWGSDRangel::SWGWFMModReport::getChannelPowerDb ()
Definition at line 107 of file SWGWFMModReport.cpp.
References channel_power_db.
{
     return channel_power_db;
 }
getChannelSampleRate()
qint32 SWGSDRangel::SWGWFMModReport::getChannelSampleRate ()
Definition at line 127 of file SWGWFMModReport.cpp.
References channel_sample_rate.
{
     return channel_sample_rate;
 }
init()
void SWGSDRangel::SWGWFMModReport::init ()
Definition at line 44 of file SWGWFMModReport.cpp.
References audio_sample_rate, channel_power_db, channel_sample_rate, m_audio_sample_rate_isSet, m_channel_power_db_isSet, and m_channel_sample_rate_isSet.
Referenced by SWGWFMModReport(), and WFMMod::webapiReportGet().
                       {
     channel_power_db = 0.0f;
     m_channel_power_db_isSet = false;
     audio_sample_rate = 0;
     m_audio_sample_rate_isSet = false;
     channel_sample_rate = 0;
     m_channel_sample_rate_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGWFMModReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 138 of file SWGWFMModReport.cpp.
References m_audio_sample_rate_isSet, m_channel_power_db_isSet, and m_channel_sample_rate_isSet.
Referenced by SWGSDRangel::SWGChannelReport::asJsonObject(), and SWGSDRangel::SWGChannelReport::isSet().
                       {
     bool isObjectUpdated = false;
     do{
         if(m_channel_power_db_isSet){ isObjectUpdated = true; break;}
         if(m_audio_sample_rate_isSet){ isObjectUpdated = true; break;}
         if(m_channel_sample_rate_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setAudioSampleRate()
void SWGSDRangel::SWGWFMModReport::setAudioSampleRate (qint32 audio_sample_rate)
Definition at line 121 of file SWGWFMModReport.cpp.
References audio_sample_rate, and m_audio_sample_rate_isSet.
Referenced by WFMMod::webapiFormatChannelReport().
{
     this->audio_sample_rate = audio_sample_rate;
     this->m_audio_sample_rate_isSet = true;
 }
setChannelPowerDb()
void SWGSDRangel::SWGWFMModReport::setChannelPowerDb (float channel_power_db)
Definition at line 111 of file SWGWFMModReport.cpp.
References channel_power_db, and m_channel_power_db_isSet.
Referenced by WFMMod::webapiFormatChannelReport().
{
     this->channel_power_db = channel_power_db;
     this->m_channel_power_db_isSet = true;
 }
setChannelSampleRate()
void SWGSDRangel::SWGWFMModReport::setChannelSampleRate (qint32 channel_sample_rate)
Definition at line 131 of file SWGWFMModReport.cpp.
References channel_sample_rate, and m_channel_sample_rate_isSet.
Referenced by WFMMod::webapiFormatChannelReport().
{
     this->channel_sample_rate = channel_sample_rate;
     this->m_channel_sample_rate_isSet = true;
 }
Member Data Documentation
audio_sample_rate
qint32 SWGSDRangel::SWGWFMModReport::audio_sample_rate private
Definition at line 60 of file SWGWFMModReport.h.
Referenced by asJsonObject(), fromJsonObject(), getAudioSampleRate(), init(), setAudioSampleRate(), and SWGWFMModReport().
channel_power_db
float SWGSDRangel::SWGWFMModReport::channel_power_db private
Definition at line 57 of file SWGWFMModReport.h.
Referenced by asJsonObject(), fromJsonObject(), getChannelPowerDb(), init(), setChannelPowerDb(), and SWGWFMModReport().
channel_sample_rate
qint32 SWGSDRangel::SWGWFMModReport::channel_sample_rate private
Definition at line 63 of file SWGWFMModReport.h.
Referenced by asJsonObject(), fromJsonObject(), getChannelSampleRate(), init(), setChannelSampleRate(), and SWGWFMModReport().
m_audio_sample_rate_isSet
bool SWGSDRangel::SWGWFMModReport::m_audio_sample_rate_isSet private
Definition at line 61 of file SWGWFMModReport.h.
Referenced by asJsonObject(), init(), isSet(), setAudioSampleRate(), and SWGWFMModReport().
m_channel_power_db_isSet
bool SWGSDRangel::SWGWFMModReport::m_channel_power_db_isSet private
Definition at line 58 of file SWGWFMModReport.h.
Referenced by asJsonObject(), init(), isSet(), setChannelPowerDb(), and SWGWFMModReport().
m_channel_sample_rate_isSet
bool SWGSDRangel::SWGWFMModReport::m_channel_sample_rate_isSet private
Definition at line 64 of file SWGWFMModReport.h.
Referenced by asJsonObject(), init(), isSet(), setChannelSampleRate(), and SWGWFMModReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGWFMModReport.h
swagger/sdrangel/code/qt5/client/SWGWFMModReport.cpp