SDRAngel: KiwiSDRInput::MsgSetStatus Class Reference
KiwiSDRInput::MsgSetStatus Class Reference
#include <kiwisdrinput.h>
Public Member Functions
int getStatus () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgSetStatus * create (int status)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgSetStatus (int status)
Protected Attributes
int m_status
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 101 of file kiwisdrinput.h.
Constructor & Destructor Documentation
MsgSetStatus()
KiwiSDRInput::MsgSetStatus::MsgSetStatus (int status) inline protected
Definition at line 114 of file kiwisdrinput.h.
References KiwiSDRInput::deserialize(), KiwiSDRInput::destroy(), KiwiSDRInput::init(), KiwiSDRInput::KiwiSDRInput(), KiwiSDRInput::serialize(), KiwiSDRInput::start(), KiwiSDRInput::stop(), and KiwiSDRInput::~KiwiSDRInput().
                                  :
             Message(),
             m_status(status)
         { }
Member Function Documentation
create()
static MsgSetStatus* KiwiSDRInput::MsgSetStatus::create (int status) inline static
Definition at line 107 of file kiwisdrinput.h.
Referenced by KiwiSDRInput::setWorkerStatus().
{
             return new MsgSetStatus(status);
         }
getStatus()
int KiwiSDRInput::MsgSetStatus::getStatus () const inline
Definition at line 105 of file kiwisdrinput.h.
Referenced by KiwiSDRGui::handleMessage().
 { return m_status; }
Member Data Documentation
m_status
int KiwiSDRInput::MsgSetStatus::m_status protected
Definition at line 112 of file kiwisdrinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/kiwisdr/kiwisdrinput.h