SDRAngel: FreqTrackerPlugin Class Reference
FreqTrackerPlugin Class Reference
#include <freqtrackerplugin.h>
Public Member Functions
FreqTrackerPlugin (QObject *parent=nullptr)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
Private Attributes
PluginAPI * m_pluginAPI
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Private Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Private Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Detailed Description
Definition at line 27 of file freqtrackerplugin.h.
Constructor & Destructor Documentation
FreqTrackerPlugin()
FreqTrackerPlugin::FreqTrackerPlugin (QObject * parent = nullptr) explicit
Definition at line 36 of file freqtrackerplugin.cpp.
                                                     :
     QObject(parent),
     m_pluginAPI(0)
 {
 }
Member Function Documentation
createRxChannelBS()
BasebandSampleSink * FreqTrackerPlugin::createRxChannelBS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 69 of file freqtrackerplugin.cpp.
 {
     return new FreqTracker(deviceAPI);
 }
createRxChannelCS()
ChannelAPI * FreqTrackerPlugin::createRxChannelCS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 74 of file freqtrackerplugin.cpp.
 {
     return new FreqTracker(deviceAPI);
 }
createRxChannelGUI()
PluginInstanceGUI * FreqTrackerPlugin::createRxChannelGUI (DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) virtual
Reimplemented from PluginInterface.
Definition at line 63 of file freqtrackerplugin.cpp.
References FreqTrackerGUI::create(), and m_pluginAPI.
Referenced by initPlugin().
 {
     return FreqTrackerGUI::create(m_pluginAPI, deviceUISet, rxChannel);
 }
getPluginDescriptor()
const PluginDescriptor & FreqTrackerPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 42 of file freqtrackerplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void FreqTrackerPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 47 of file freqtrackerplugin.cpp.
References createRxChannelGUI(), FreqTracker::m_channelId, FreqTracker::m_channelIdURI, m_pluginAPI, and PluginAPI::registerRxChannel().
 {
     m_pluginAPI = pluginAPI;
     // register AM demodulator
     m_pluginAPI->registerRxChannel(FreqTracker::m_channelIdURI, FreqTracker::m_channelId, this);
 }
Member Data Documentation
m_pluginAPI
PluginAPI* FreqTrackerPlugin::m_pluginAPI private
Definition at line 45 of file freqtrackerplugin.h.
Referenced by createRxChannelGUI(), and initPlugin().
m_pluginDescriptor
const PluginDescriptor FreqTrackerPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("Frequency Tracker"),
    QString("4.7.0"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 43 of file freqtrackerplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/channelrx/freqtracker/freqtrackerplugin.h
plugins/channelrx/freqtracker/freqtrackerplugin.cpp