SDRAngel: FCDProConstants Class Reference
FCDProConstants Class Reference
#include <fcdproconst.h>
Static Public Member Functions
static int fcdpro_lna_gain_nb_values ()
static int fcdpro_lna_enhance_nb_values ()
static int fcdpro_band_nb_values ()
static int fcdpro_rf_filter_nb_values ()
static int fcdpro_mixer_gain_nb_values ()
static int fcdpro_bias_current_nb_values ()
static int fcdpro_mixer_filter_nb_values ()
static int fcdpro_if_gain_mode_nb_values ()
static int fcdpro_if_rc_filter_nb_values ()
static int fcdpro_if_filter_nb_values ()
static int fcdpro_if_gain1_nb_values ()
static int fcdpro_if_gain2_nb_values ()
static int fcdpro_if_gain3_nb_values ()
static int fcdpro_if_gain4_nb_values ()
static int fcdpro_if_gain5_nb_values ()
static int fcdpro_if_gain6_nb_values ()
Static Public Attributes
static const fcdpro_lna_gain lna_gains []
static const fcdpro_lna_enhance lna_enhances []
static const fcdpro_band bands []
static const fcdpro_rf_filter rf_filters []
static const fcdpro_mixer_gain mixer_gains []
static const fcdpro_bias_current bias_currents []
static const fcdpro_mixer_filter mixer_filters []
static const fcdpro_if_gain_mode if_gain_modes []
static const fcdpro_if_rc_filter if_rc_filters []
static const fcdpro_if_filter if_filters []
static const fcdpro_if_gain1 if_gains1 []
static const fcdpro_if_gain2 if_gains2 []
static const fcdpro_if_gain3 if_gains3 []
static const fcdpro_if_gain4 if_gains4 []
static const fcdpro_if_gain5 if_gains5 []
static const fcdpro_if_gain6 if_gains6 []
Detailed Description
Definition at line 323 of file fcdproconst.h.
Member Function Documentation
fcdpro_band_nb_values()
int FCDProConstants::fcdpro_band_nb_values () static
Definition at line 51 of file fcdproconst.cpp.
References bands, FCDPRO_TRF_BPF1300MHZ, FCDPRO_TRF_BPF1320MHZ, FCDPRO_TRF_BPF1360MHZ, FCDPRO_TRF_BPF1410MHZ, FCDPRO_TRF_BPF1445MHZ, FCDPRO_TRF_BPF1460MHZ, FCDPRO_TRF_BPF1490MHZ, FCDPRO_TRF_BPF1530MHZ, FCDPRO_TRF_BPF1560MHZ, FCDPRO_TRF_BPF1590MHZ, FCDPRO_TRF_BPF1640MHZ, FCDPRO_TRF_BPF1660MHZ, FCDPRO_TRF_BPF1680MHZ, FCDPRO_TRF_BPF1700MHZ, FCDPRO_TRF_BPF1720MHZ, FCDPRO_TRF_BPF1750MHZ, FCDPRO_TRF_BPF360MHZ, FCDPRO_TRF_BPF380MHZ, FCDPRO_TRF_BPF405MHZ, FCDPRO_TRF_BPF425MHZ, FCDPRO_TRF_BPF450MHZ, FCDPRO_TRF_BPF475MHZ, FCDPRO_TRF_BPF505MHZ, FCDPRO_TRF_BPF540MHZ, FCDPRO_TRF_BPF575MHZ, FCDPRO_TRF_BPF615MHZ, FCDPRO_TRF_BPF670MHZ, FCDPRO_TRF_BPF720MHZ, FCDPRO_TRF_BPF760MHZ, FCDPRO_TRF_BPF840MHZ, FCDPRO_TRF_BPF890MHZ, FCDPRO_TRF_BPF970MHZ, FCDPRO_TRF_LPF268MHZ, FCDPRO_TRF_LPF299MHZ, FCDPRO_TRF_LPF509MHZ, FCDPRO_TRF_LPF656MHZ, and rf_filters.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_band().
 {
     return sizeof(bands) / sizeof(fcdpro_band);
 }
fcdpro_bias_current_nb_values()
int FCDProConstants::fcdpro_bias_current_nb_values () static
Definition at line 121 of file fcdproconst.cpp.
References bias_currents, FCDPRO_TMF_1_9MHZ, FCDPRO_TMF_27_0MHZ, FCDPRO_TMF_2_3MHZ, FCDPRO_TMF_2_7MHZ, FCDPRO_TMF_3_0MHZ, FCDPRO_TMF_3_4MHZ, FCDPRO_TMF_3_8MHZ, FCDPRO_TMF_4_2MHZ, FCDPRO_TMF_4_6MHZ, and mixer_filters.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_biasCurrent().
 {
     return sizeof(bias_currents) / sizeof(fcdpro_bias_current);
 }
fcdpro_if_filter_nb_values()
int FCDProConstants::fcdpro_if_filter_nb_values () static
Definition at line 257 of file fcdproconst.cpp.
References FCDPRO_TIG5_P12_0DB, FCDPRO_TIG5_P15_0DB, FCDPRO_TIG5_P3_0DB, FCDPRO_TIG5_P6_0DB, FCDPRO_TIG5_P9_0DB, if_filters, and if_gains5.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_ifFilter().
 {
     return sizeof(if_filters) / sizeof(fcdpro_if_filter);
 }
fcdpro_if_gain1_nb_values()
int FCDProConstants::fcdpro_if_gain1_nb_values () static
Definition at line 148 of file fcdproconst.cpp.
References FCDPRO_TIGM_LINEARITY, FCDPRO_TIGM_SENSITIVITY, if_gain_modes, and if_gains1.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_gain1().
 {
     return sizeof(if_gains1) / sizeof(fcdpro_if_gain1);
 }
fcdpro_if_gain2_nb_values()
int FCDProConstants::fcdpro_if_gain2_nb_values () static
Definition at line 194 of file fcdproconst.cpp.
References FCDPRO_TIG3_P0_0DB, FCDPRO_TIG3_P3_0DB, FCDPRO_TIG3_P6_0DB, FCDPRO_TIG3_P9_0DB, if_gains2, and if_gains3.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_gain2().
 {
     return sizeof(if_gains2) / sizeof(fcdpro_if_gain2);
 }
fcdpro_if_gain3_nb_values()
int FCDProConstants::fcdpro_if_gain3_nb_values () static
Definition at line 206 of file fcdproconst.cpp.
References FCDPRO_TIG4_P0_0DB, FCDPRO_TIG4_P1_0DB, FCDPRO_TIG4_P2_0DB, if_gains3, and if_gains4.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_gain3().
 {
     return sizeof(if_gains3) / sizeof(fcdpro_if_gain3);
 }
fcdpro_if_gain4_nb_values()
int FCDProConstants::fcdpro_if_gain4_nb_values () static
Definition at line 217 of file fcdproconst.cpp.
References FCDPRO_TIF_2_15MHZ, FCDPRO_TIF_2_20MHZ, FCDPRO_TIF_2_24MHZ, FCDPRO_TIF_2_28MHZ, FCDPRO_TIF_2_30MHZ, FCDPRO_TIF_2_40MHZ, FCDPRO_TIF_2_45MHZ, FCDPRO_TIF_2_50MHZ, FCDPRO_TIF_2_55MHZ, FCDPRO_TIF_2_60MHZ, FCDPRO_TIF_2_70MHZ, FCDPRO_TIF_2_75MHZ, FCDPRO_TIF_2_80MHZ, FCDPRO_TIF_2_90MHZ, FCDPRO_TIF_2_95MHZ, FCDPRO_TIF_3_00MHZ, FCDPRO_TIF_3_10MHZ, FCDPRO_TIF_3_20MHZ, FCDPRO_TIF_3_30MHZ, FCDPRO_TIF_3_40MHZ, FCDPRO_TIF_3_60MHZ, FCDPRO_TIF_3_70MHZ, FCDPRO_TIF_3_80MHZ, FCDPRO_TIF_3_90MHZ, FCDPRO_TIF_4_10MHZ, FCDPRO_TIF_4_30MHZ, FCDPRO_TIF_4_40MHZ, FCDPRO_TIF_4_60MHZ, FCDPRO_TIF_4_80MHZ, FCDPRO_TIF_5_00MHZ, FCDPRO_TIF_5_30MHZ, FCDPRO_TIF_5_50MHZ, if_filters, and if_gains4.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_gain4().
 {
     return sizeof(if_gains4) / sizeof(fcdpro_if_gain4);
 }
fcdpro_if_gain5_nb_values()
int FCDProConstants::fcdpro_if_gain5_nb_values () static
Definition at line 270 of file fcdproconst.cpp.
References FCDPRO_TIG6_P12_0DB, FCDPRO_TIG6_P15_0DB, FCDPRO_TIG6_P3_0DB, FCDPRO_TIG6_P6_0DB, FCDPRO_TIG6_P9_0DB, if_gains5, and if_gains6.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_gain5().
 {
     return sizeof(if_gains5) / sizeof(fcdpro_if_gain5);
 }
fcdpro_if_gain6_nb_values()
int FCDProConstants::fcdpro_if_gain6_nb_values () static
Definition at line 283 of file fcdproconst.cpp.
References if_gains6.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_gain6().
 {
     return sizeof(if_gains6) / sizeof(fcdpro_if_gain6);
 }
fcdpro_if_gain_mode_nb_values()
int FCDProConstants::fcdpro_if_gain_mode_nb_values () static
Definition at line 158 of file fcdproconst.cpp.
References FCDPRO_TIRF_10_6MHZ, FCDPRO_TIRF_12_4MHZ, FCDPRO_TIRF_14_7MHZ, FCDPRO_TIRF_17_6MHZ, FCDPRO_TIRF_1_0MHZ, FCDPRO_TIRF_1_2MHZ, FCDPRO_TIRF_1_8MHZ, FCDPRO_TIRF_21_0MHZ, FCDPRO_TIRF_21_4MHZ, FCDPRO_TIRF_2_6MHZ, FCDPRO_TIRF_3_4MHZ, FCDPRO_TIRF_4_4MHZ, FCDPRO_TIRF_5_3MHZ, FCDPRO_TIRF_6_4MHZ, FCDPRO_TIRF_7_7MHZ, FCDPRO_TIRF_9_0MHZ, if_gain_modes, and if_rc_filters.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_mode().
 {
     return sizeof(if_gain_modes) / sizeof(fcdpro_if_gain_mode);
 }
fcdpro_if_rc_filter_nb_values()
int FCDProConstants::fcdpro_if_rc_filter_nb_values () static
Definition at line 182 of file fcdproconst.cpp.
References FCDPRO_TIG2_P0_0DB, FCDPRO_TIG2_P3_0DB, FCDPRO_TIG2_P6_0DB, FCDPRO_TIG2_P9_0DB, if_gains2, and if_rc_filters.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_rcFilter().
 {
     return sizeof(if_rc_filters) / sizeof(fcdpro_if_rc_filter);
 }
fcdpro_lna_enhance_nb_values()
int FCDProConstants::fcdpro_lna_enhance_nb_values () static
Definition at line 39 of file fcdproconst.cpp.
References bands, FCDPRO_TB_LBAND, FCDPRO_TB_UHF, FCDPRO_TB_VHF2, FCDPRO_TB_VHF3, and lna_enhances.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_lnaEnhance().
 {
     return sizeof(lna_enhances) / sizeof(fcdpro_lna_enhance);
 }
fcdpro_lna_gain_nb_values()
int FCDProConstants::fcdpro_lna_gain_nb_values () static
Definition at line 26 of file fcdproconst.cpp.
References FCDPRO_TLE_0, FCDPRO_TLE_1, FCDPRO_TLE_2, FCDPRO_TLE_3, FCDPRO_TLE_OFF, lna_enhances, and lna_gains.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_lnaGain().
 {
     return sizeof(lna_gains) / sizeof(fcdpro_lna_gain);
 }
fcdpro_mixer_filter_nb_values()
int FCDProConstants::fcdpro_mixer_filter_nb_values () static
Definition at line 138 of file fcdproconst.cpp.
References FCDPRO_TIG1_N3_0DB, FCDPRO_TIG1_P6_0DB, if_gains1, and mixer_filters.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_mixerFilter().
 {
     return sizeof(mixer_filters) / sizeof(fcdpro_mixer_filter);
 }
fcdpro_mixer_gain_nb_values()
int FCDProConstants::fcdpro_mixer_gain_nb_values () static
Definition at line 109 of file fcdproconst.cpp.
References bias_currents, FCDPRO_TBC_1, FCDPRO_TBC_2, FCDPRO_TBC_LBAND, FCDPRO_TBC_VUBAND, and mixer_gains.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_mixerGain().
 {
     return sizeof(mixer_gains) / sizeof(fcdpro_mixer_gain);
 }
fcdpro_rf_filter_nb_values()
int FCDProConstants::fcdpro_rf_filter_nb_values () static
Definition at line 99 of file fcdproconst.cpp.
References FCDPRO_TMG_P12_0DB, FCDPRO_TMG_P4_0DB, mixer_gains, and rf_filters.
Referenced by FCDProGui::FCDProGui(), and FCDProInput::set_rfFilter().
 {
     return sizeof(rf_filters) / sizeof(fcdpro_rf_filter);
 }
Member Data Documentation
bands
const fcdpro_band FCDProConstants::bands static
Initial value:
= {
        {FCDPRO_TB_VHF2, "VHF2"},
        {FCDPRO_TB_VHF3, "VHF3"},
        {FCDPRO_TB_UHF, "UHF"},
        {FCDPRO_TB_LBAND, "L"}
}
Definition at line 328 of file fcdproconst.h.
Referenced by fcdpro_band_nb_values(), fcdpro_lna_enhance_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_band().
bias_currents
const fcdpro_bias_current FCDProConstants::bias_currents static
Initial value:
= {
        {FCDPRO_TBC_LBAND, "L"},
        {FCDPRO_TBC_1, "1"},
        {FCDPRO_TBC_2, "2"},
        {FCDPRO_TBC_VUBAND, "VU"}
}
Definition at line 331 of file fcdproconst.h.
Referenced by fcdpro_bias_current_nb_values(), fcdpro_mixer_gain_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_biasCurrent().
if_filters
const fcdpro_if_filter FCDProConstants::if_filters static
Definition at line 335 of file fcdproconst.h.
Referenced by fcdpro_if_filter_nb_values(), fcdpro_if_gain4_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_ifFilter().
if_gain_modes
const fcdpro_if_gain_mode FCDProConstants::if_gain_modes static
Initial value:
= {
        {FCDPRO_TIGM_LINEARITY, "Lin"},
        {FCDPRO_TIGM_SENSITIVITY, "Sens"}
}
Definition at line 333 of file fcdproconst.h.
Referenced by fcdpro_if_gain1_nb_values(), fcdpro_if_gain_mode_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_mode().
if_gains1
const fcdpro_if_gain1 FCDProConstants::if_gains1 static
Initial value:
= {
        {FCDPRO_TIG1_N3_0DB, "3dB"},
        {FCDPRO_TIG1_P6_0DB, "6dB"}
}
Definition at line 336 of file fcdproconst.h.
Referenced by fcdpro_if_gain1_nb_values(), fcdpro_mixer_filter_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_gain1().
if_gains2
const fcdpro_if_gain2 FCDProConstants::if_gains2 static
Initial value:
= {
        {FCDPRO_TIG2_P0_0DB, "0dB"},
        {FCDPRO_TIG2_P3_0DB, "3dB"},
        {FCDPRO_TIG2_P6_0DB, "6dB"},
        {FCDPRO_TIG2_P9_0DB, "9dB"}
}
Definition at line 337 of file fcdproconst.h.
Referenced by fcdpro_if_gain2_nb_values(), fcdpro_if_rc_filter_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_gain2().
if_gains3
const fcdpro_if_gain3 FCDProConstants::if_gains3 static
Initial value:
= {
        {FCDPRO_TIG3_P0_0DB, "0dB"},
        {FCDPRO_TIG3_P3_0DB, "3dB"},
        {FCDPRO_TIG3_P6_0DB, "6dB"},
        {FCDPRO_TIG3_P9_0DB, "9dB"}
}
Definition at line 338 of file fcdproconst.h.
Referenced by fcdpro_if_gain2_nb_values(), fcdpro_if_gain3_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_gain3().
if_gains4
const fcdpro_if_gain4 FCDProConstants::if_gains4 static
Initial value:
= {
        {FCDPRO_TIG4_P0_0DB, "0dB"},
        {FCDPRO_TIG4_P1_0DB, "1dB"},
        {FCDPRO_TIG4_P2_0DB, "2dB"},
}
Definition at line 339 of file fcdproconst.h.
Referenced by fcdpro_if_gain3_nb_values(), fcdpro_if_gain4_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_gain4().
if_gains5
const fcdpro_if_gain5 FCDProConstants::if_gains5 static
Initial value:
= {
        {FCDPRO_TIG5_P3_0DB, "3dB"},
        {FCDPRO_TIG5_P6_0DB, "6dB"},
        {FCDPRO_TIG5_P9_0DB, "9dB"},
        {FCDPRO_TIG5_P12_0DB, "12dB"},
        {FCDPRO_TIG5_P15_0DB, "15dB"}
}
Definition at line 340 of file fcdproconst.h.
Referenced by fcdpro_if_filter_nb_values(), fcdpro_if_gain5_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_gain5().
if_gains6
const fcdpro_if_gain6 FCDProConstants::if_gains6 static
Initial value:
= {
        {FCDPRO_TIG6_P3_0DB, "3dB"},
        {FCDPRO_TIG6_P6_0DB, "6dB"},
        {FCDPRO_TIG6_P9_0DB, "9dB"},
        {FCDPRO_TIG6_P12_0DB, "12dB"},
        {FCDPRO_TIG6_P15_0DB, "15dB"}
}
Definition at line 341 of file fcdproconst.h.
Referenced by fcdpro_if_gain5_nb_values(), fcdpro_if_gain6_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_gain6().
if_rc_filters
const fcdpro_if_rc_filter FCDProConstants::if_rc_filters static
Initial value:
= {
        {FCDPRO_TIRF_21_4MHZ, "21.4M"},
        {FCDPRO_TIRF_21_0MHZ, "21.0M"},
        {FCDPRO_TIRF_17_6MHZ, "17.6M"},
        {FCDPRO_TIRF_14_7MHZ, "14.7M"},
        {FCDPRO_TIRF_12_4MHZ, "12.4M"},
        {FCDPRO_TIRF_10_6MHZ, "18.6M"},
        {FCDPRO_TIRF_9_0MHZ, "9.0M"},
        {FCDPRO_TIRF_7_7MHZ, "7.7M"},
        {FCDPRO_TIRF_6_4MHZ, "6.4M"},
        {FCDPRO_TIRF_5_3MHZ, "5.3M"},
        {FCDPRO_TIRF_4_4MHZ, "4.4M"},
        {FCDPRO_TIRF_3_4MHZ, "3.4M"},
        {FCDPRO_TIRF_2_6MHZ, "2.6M"},
        {FCDPRO_TIRF_1_8MHZ, "1.8M"},
        {FCDPRO_TIRF_1_2MHZ, "1.2M"},
        {FCDPRO_TIRF_1_0MHZ, "1.0M"}
}
Definition at line 334 of file fcdproconst.h.
Referenced by fcdpro_if_gain_mode_nb_values(), fcdpro_if_rc_filter_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_rcFilter().
lna_enhances
const fcdpro_lna_enhance FCDProConstants::lna_enhances static
Initial value:
= {
        {FCDPRO_TLE_OFF, "Off"},
        {FCDPRO_TLE_0, "0"},
        {FCDPRO_TLE_1, "1"},
        {FCDPRO_TLE_2, "2"},
        {FCDPRO_TLE_3, "3"}
}
Definition at line 327 of file fcdproconst.h.
Referenced by fcdpro_lna_enhance_nb_values(), fcdpro_lna_gain_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_lnaEnhance().
lna_gains
const fcdpro_lna_gain FCDProConstants::lna_gains static
Initial value:
= {
        {FCDPRO_TLG_N5_0DB, "-5dB"},
        {FCDPRO_TLG_N2_5DB, "-2.5dB"},
        {FCDPRO_TLG_P0_0DB, "0dB"},
        {FCDPRO_TLG_P2_5DB, "2.5dB"},
        {FCDPRO_TLG_P5_0DB, "5dB"},
        {FCDPRO_TLG_P7_5DB, "7.5dB"},
        {FCDPRO_TLG_P10_0DB, "10dB"},
        {FCDPRO_TLG_P12_5DB, "12.5dB"},
        {FCDPRO_TLG_P15_0DB, "15dB"},
        {FCDPRO_TLG_P17_5DB, "17.5dB"},
        {FCDPRO_TLG_P20_0DB, "20dB"},
        {FCDPRO_TLG_P25_0DB, "25dB"},
        {FCDPRO_TLG_P30_0DB, "30dB"}
}
Definition at line 326 of file fcdproconst.h.
Referenced by fcdpro_lna_gain_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_lnaGain().
mixer_filters
const fcdpro_mixer_filter FCDProConstants::mixer_filters static
Initial value:
= {
        {FCDPRO_TMF_27_0MHZ, "27M"},
        {FCDPRO_TMF_4_6MHZ, "4.6M"},
        {FCDPRO_TMF_4_2MHZ, "4.2M"},
        {FCDPRO_TMF_3_8MHZ, "3.8M"},
        {FCDPRO_TMF_3_4MHZ, "3.4M"},
        {FCDPRO_TMF_3_0MHZ, "3.0M"},
        {FCDPRO_TMF_2_7MHZ, "2.7M"},
        {FCDPRO_TMF_2_3MHZ, "2.3M"},
        {FCDPRO_TMF_1_9MHZ, "1.9M"}
}
Definition at line 332 of file fcdproconst.h.
Referenced by fcdpro_bias_current_nb_values(), fcdpro_mixer_filter_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_mixerFilter().
mixer_gains
const fcdpro_mixer_gain FCDProConstants::mixer_gains static
Initial value:
= {
        {FCDPRO_TMG_P4_0DB, "0dB"},
        {FCDPRO_TMG_P12_0DB, "12dB"}
}
Definition at line 330 of file fcdproconst.h.
Referenced by fcdpro_mixer_gain_nb_values(), fcdpro_rf_filter_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_mixerGain().
rf_filters
const fcdpro_rf_filter FCDProConstants::rf_filters static
Definition at line 329 of file fcdproconst.h.
Referenced by fcdpro_band_nb_values(), fcdpro_rf_filter_nb_values(), FCDProGui::FCDProGui(), and FCDProInput::set_rfFilter().
The documentation for this class was generated from the following files:
fcdlib/fcdproconst.h
fcdlib/fcdproconst.cpp