SDRAngel: RemoteOutput::MsgConfigureRemoteOutput Class Reference
RemoteOutput::MsgConfigureRemoteOutput Class Reference
#include <remoteoutput.h>
Public Member Functions
const RemoteOutputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureRemoteOutput * create (const RemoteOutputSettings &settings, bool force=false)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureRemoteOutput (const RemoteOutputSettings &settings, bool force)
Private Attributes
RemoteOutputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 43 of file remoteoutput.h.
Constructor & Destructor Documentation
MsgConfigureRemoteOutput()
RemoteOutput::MsgConfigureRemoteOutput::MsgConfigureRemoteOutput (const RemoteOutputSettings & settings, bool force) inline private
Definition at line 59 of file remoteoutput.h.
Referenced by create().
                                                                                    :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureRemoteOutput* RemoteOutput::MsgConfigureRemoteOutput::create (const RemoteOutputSettings & settings, bool force = false) inline static
Definition at line 50 of file remoteoutput.h.
References MsgConfigureRemoteOutput().
Referenced by RemoteOutput::deserialize(), RemoteOutputSinkGui::updateHardware(), and RemoteOutput::webapiSettingsPutPatch().
         {
             return new MsgConfigureRemoteOutput(settings, force);
         }
getForce()
bool RemoteOutput::MsgConfigureRemoteOutput::getForce () const inline
Definition at line 48 of file remoteoutput.h.
References m_force.
Referenced by RemoteOutput::handleMessage().
 { return m_force; }
getSettings()
const RemoteOutputSettings& RemoteOutput::MsgConfigureRemoteOutput::getSettings () const inline
Definition at line 47 of file remoteoutput.h.
References m_settings.
Referenced by RemoteOutputSinkGui::handleMessage(), and RemoteOutput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool RemoteOutput::MsgConfigureRemoteOutput::m_force private
Definition at line 57 of file remoteoutput.h.
Referenced by getForce().
m_settings
RemoteOutputSettings RemoteOutput::MsgConfigureRemoteOutput::m_settings private
Definition at line 56 of file remoteoutput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesink/remoteoutput/remoteoutput.h