SDRAngel: AMModGUI Class Reference
AMModGUI Class Reference
#include <ammodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static AMModGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx)
Private Slots
void handleSourceMessages ()
void on_deltaFrequency_changed (qint64 value)
void on_rfBW_valueChanged (int value)
void on_modPercent_valueChanged (int value)
void on_volume_valueChanged (int value)
void on_channelMute_toggled (bool checked)
void on_tone_toggled (bool checked)
void on_toneFrequency_valueChanged (int value)
void on_mic_toggled (bool checked)
void on_play_toggled (bool checked)
void on_morseKeyer_toggled (bool checked)
void on_playLoop_toggled (bool checked)
void on_navTimeSlider_valueChanged (int value)
void on_showFileDialog_clicked (bool checked)
void on_feedbackEnable_toggled (bool checked)
void on_feedbackVolume_valueChanged (int value)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void configureFileName ()
void audioSelect ()
void audioFeedbackSelect ()
void tick ()
Private Member Functions
AMModGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx, QWidget *parent=0)
virtual ~AMModGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
void updateWithStreamData ()
void updateWithStreamTime ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::AMModGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
AMModSettings m_settings
bool m_doApplySettings
AMMod * m_amMod
MovingAverageUtil< double, double, 20 > m_channelPowerDbAvg
QString m_fileName
quint32 m_recordLength
int m_recordSampleRate
int m_samplesCount
std::size_t m_tickCount
bool m_enableNavTime
MessageQueue m_inputMessageQueue
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 40 of file ammodgui.h.
Constructor & Destructor Documentation
AMModGUI()
AMModGUI::AMModGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx, QWidget * parent = 0) explicit private
Definition at line 324 of file ammodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), arg(), audioFeedbackSelect(), audioSelect(), channelMarkerChangedByCursor(), displaySettings(), AMMod::getCWKeyer(), getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, handleSourceMessages(), m_amMod, AMMod::m_channelIdURI, m_channelMarker, m_deviceUISet, m_settings, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerTxChannelInstance(), ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), AMModSettings::setChannelMarker(), ChannelMarker::setColor(), AMModSettings::setCWKeyerGUI(), BasebandSampleSource::setMessageQueueToGUI(), ChannelMarker::setSourceOrSinkStream(), ChannelMarker::setTitle(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                    :
     RollupWidget(parent),
     ui(new Ui::AMModGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_doApplySettings(true),
     m_recordLength(0),
     m_recordSampleRate(48000),
     m_samplesCount(0),
     m_tickCount(0),
     m_enableNavTime(false)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_amMod = (AMMod*) channelTx; //new AMMod(m_deviceUISet->m_deviceSinkAPI);
     m_amMod->setMessageQueueToGUI(getInputMessageQueue());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     CRightClickEnabler *audioMuteRightClickEnabler = new CRightClickEnabler(ui->mic);
     connect(audioMuteRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioSelect()));
     CRightClickEnabler *feedbackRightClickEnabler = new CRightClickEnabler(ui->feedbackEnable);
     connect(feedbackRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioFeedbackSelect()));
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(Qt::yellow);
     m_channelMarker.setBandwidth(5000);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("AM Modulator");
     m_channelMarker.setSourceOrSinkStream(false);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     m_settings.setChannelMarker(&m_channelMarker);
     m_settings.setCWKeyerGUI(ui->cwKeyerGUI);
     m_deviceUISet->registerTxChannelInstance(AMMod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     ui->play->setEnabled(false);
     ui->play->setChecked(false);
     ui->tone->setChecked(false);
     ui->morseKeyer->setChecked(false);
     ui->mic->setChecked(false);
     ui->cwKeyerGUI->setCWKeyer(m_amMod->getCWKeyer());
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     connect(m_amMod, SIGNAL(levelChanged(qreal, qreal, int)), ui->volumeMeter, SLOT(levelChanged(qreal, qreal, int)));
     displaySettings();
     applySettings(true);
 }
~AMModGUI()
AMModGUI::~AMModGUI () private virtual
Definition at line 390 of file ammodgui.cpp.
References m_amMod, m_deviceUISet, DeviceUISet::removeTxChannelInstance(), and ui.
 {
     m_deviceUISet->removeTxChannelInstance(this);
     delete m_amMod; // TODO: check this: when the GUI closes it has to delete the modulator
     delete ui;
 }
Member Function Documentation
applySettings()
void AMModGUI::applySettings (bool force = false) private
Definition at line 402 of file ammodgui.cpp.
References AMMod::MsgConfigureAMMod::create(), AMMod::MsgConfigureChannelizer::create(), ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasebandSampleSource::getInputMessageQueue(), m_amMod, m_channelMarker, m_doApplySettings, m_settings, MessageQueue::push(), and RollupWidget::setTitleColor().
Referenced by AMModGUI(), audioFeedbackSelect(), audioSelect(), channelMarkerChangedByCursor(), deserialize(), on_channelMute_toggled(), on_deltaFrequency_changed(), on_feedbackEnable_toggled(), on_feedbackVolume_valueChanged(), on_mic_toggled(), on_modPercent_valueChanged(), on_morseKeyer_toggled(), on_play_toggled(), on_playLoop_toggled(), on_rfBW_valueChanged(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), and setCenterFrequency().
 {
     if (m_doApplySettings)
     {
         setTitleColor(m_channelMarker.getColor());
         AMMod::MsgConfigureChannelizer *msgConfigure = AMMod::MsgConfigureChannelizer::create(
                 48000, m_channelMarker.getCenterFrequency());
         m_amMod->getInputMessageQueue()->push(msgConfigure);
         AMMod::MsgConfigureAMMod* message = AMMod::MsgConfigureAMMod::create( m_settings, force);
         m_amMod->getInputMessageQueue()->push(message);
     }
 }
audioFeedbackSelect
void AMModGUI::audioFeedbackSelect () private slot
Definition at line 489 of file ammodgui.cpp.
References applySettings(), audioSelect(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, AMModSettings::m_audioDeviceName, AMModSettings::m_feedbackAudioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by AMModGUI().
 {
     qDebug("AMModGUI::audioFeedbackSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName, false); // false for output
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_feedbackAudioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
audioSelect
void AMModGUI::audioSelect () private slot
Definition at line 476 of file ammodgui.cpp.
References applySettings(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, AMModSettings::m_audioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by AMModGUI(), and audioFeedbackSelect().
 {
     qDebug("AMModGUI::audioSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName, true); // true for input
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_audioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
blockApplySettings()
void AMModGUI::blockApplySettings (bool block) private
Definition at line 397 of file ammodgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void AMModGUI::channelMarkerChangedByCursor () slot
Definition at line 132 of file ammodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, AMModSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by AMModGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
configureFileName
void AMModGUI::configureFileName () private slot
Definition at line 280 of file ammodgui.cpp.
References AMMod::MsgConfigureFileSourceName::create(), BasebandSampleSource::getInputMessageQueue(), m_amMod, m_fileName, and MessageQueue::push().
Referenced by on_showFileDialog_clicked().
 {
     qDebug() << "FileSourceGui::configureFileName: " << m_fileName.toStdString().c_str();
     AMMod::MsgConfigureFileSourceName* message = AMMod::MsgConfigureFileSourceName::create(m_fileName);
     m_amMod->getInputMessageQueue()->push(message);
 }
create()
AMModGUI * AMModGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx) static
Definition at line 39 of file ammodgui.cpp.
References AMModGUI().
Referenced by AMModPlugin::createTxChannelGUI().
 {
     AMModGUI* gui = new AMModGUI(pluginAPI, deviceUISet, channelTx);
     return gui;
 }
deserialize()
bool AMModGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 82 of file ammodgui.cpp.
References applySettings(), AMModSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void AMModGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 45 of file ammodgui.cpp.
 {
     delete this;
 }
displaySettings()
void AMModGUI::displaySettings () private
Definition at line 417 of file ammodgui.cpp.
References arg(), blockApplySettings(), ChannelMarker::getCenterFrequency(), ChannelMarker::getTitle(), m_channelMarker, AMModSettings::m_channelMute, AMModSettings::m_feedbackAudioEnable, AMModSettings::m_feedbackVolumeFactor, AMModSettings::m_inputFrequencyOffset, AMModSettings::m_modAFInput, AMModSettings::m_modFactor, AMModSettings::m_playLoop, AMModSettings::m_rfBandwidth, AMModSettings::m_rgbColor, m_settings, AMModSettings::m_title, AMModSettings::m_toneFrequency, AMModSettings::m_volumeFactor, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by AMModGUI(), deserialize(), handleMessage(), and resetToDefaults().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.setBandwidth(m_settings.m_rfBandwidth);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     ui->rfBW->setValue(roundf(m_settings.m_rfBandwidth / 100.0));
     ui->rfBWText->setText(QString("%1 kHz").arg(m_settings.m_rfBandwidth / 1000.0, 0, 'f', 1));
     int modPercent = roundf(m_settings.m_modFactor * 100.0);
     ui->modPercent->setValue(modPercent);
     ui->modPercentText->setText(QString("%1").arg(modPercent));
     ui->toneFrequency->setValue(roundf(m_settings.m_toneFrequency / 10.0));
     ui->toneFrequencyText->setText(QString("%1k").arg(m_settings.m_toneFrequency / 1000.0, 0, 'f', 2));
     ui->volume->setValue(roundf(m_settings.m_volumeFactor * 10.0));
     ui->volumeText->setText(QString("%1").arg(m_settings.m_volumeFactor, 0, 'f', 1));
     ui->channelMute->setChecked(m_settings.m_channelMute);
     ui->playLoop->setChecked(m_settings.m_playLoop);
     ui->tone->setEnabled((m_settings.m_modAFInput == AMModSettings::AMModInputAF::AMModInputTone) || (m_settings.m_modAFInput == AMModSettings::AMModInputAF::AMModInputNone));
     ui->mic->setEnabled((m_settings.m_modAFInput == AMModSettings::AMModInputAF::AMModInputAudio) || (m_settings.m_modAFInput == AMModSettings::AMModInputAF::AMModInputNone));
     ui->play->setEnabled((m_settings.m_modAFInput == AMModSettings::AMModInputAF::AMModInputFile) || (m_settings.m_modAFInput == AMModSettings::AMModInputAF::AMModInputNone));
     ui->morseKeyer->setEnabled((m_settings.m_modAFInput == AMModSettings::AMModInputAF::AMModInputCWTone) || (m_settings.m_modAFInput == AMModSettings::AMModInputAF::AMModInputNone));
     ui->tone->setChecked(m_settings.m_modAFInput == AMModSettings::AMModInputAF::AMModInputTone);
     ui->mic->setChecked(m_settings.m_modAFInput == AMModSettings::AMModInputAF::AMModInputAudio);
     ui->play->setChecked(m_settings.m_modAFInput == AMModSettings::AMModInputAF::AMModInputFile);
     ui->morseKeyer->setChecked(m_settings.m_modAFInput == AMModSettings::AMModInputAF::AMModInputCWTone);
     ui->feedbackEnable->setChecked(m_settings.m_feedbackAudioEnable);
     ui->feedbackVolume->setValue(roundf(m_settings.m_feedbackVolumeFactor * 100.0));
     ui->feedbackVolumeText->setText(QString("%1").arg(m_settings.m_feedbackVolumeFactor, 0, 'f', 2));
     blockApplySettings(false);
 }
enterEvent()
void AMModGUI::enterEvent (QEvent *) private
Definition at line 471 of file ammodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 AMModGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 60 of file ammodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
{
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* AMModGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 55 of file ammodgui.h.
Referenced by AMModGUI(), and handleSourceMessages().
 { return &m_inputMessageQueue; }
getName()
QString AMModGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 55 of file ammodgui.cpp.
 {
     return objectName();
 }
handleMessage()
bool AMModGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 94 of file ammodgui.cpp.
References blockApplySettings(), displaySettings(), AMMod::MsgConfigureAMMod::getSettings(), CWKeyer::MsgConfigureCWKeyer::getSettings(), m_recordLength, m_recordSampleRate, m_samplesCount, m_settings, Message::match(), ui, updateWithStreamData(), and updateWithStreamTime().
Referenced by handleSourceMessages().
 {
     if (AMMod::MsgReportFileSourceStreamData::match(message))
     {
         m_recordSampleRate = ((AMMod::MsgReportFileSourceStreamData&)message).getSampleRate();
         m_recordLength = ((AMMod::MsgReportFileSourceStreamData&)message).getRecordLength();
         m_samplesCount = 0;
         updateWithStreamData();
         return true;
     }
     else if (AMMod::MsgReportFileSourceStreamTiming::match(message))
     {
         m_samplesCount = ((AMMod::MsgReportFileSourceStreamTiming&)message).getSamplesCount();
         updateWithStreamTime();
         return true;
     }
     else if (AMMod::MsgConfigureAMMod::match(message))
     {
         const AMMod::MsgConfigureAMMod& cfg = (AMMod::MsgConfigureAMMod&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (CWKeyer::MsgConfigureCWKeyer::match(message))
     {
         const CWKeyer::MsgConfigureCWKeyer& cfg = (CWKeyer::MsgConfigureCWKeyer&) message;
         ui->cwKeyerGUI->setSettings(cfg.getSettings());
         ui->cwKeyerGUI->displaySettings();
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void AMModGUI::handleSourceMessages () private slot
Definition at line 139 of file ammodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by AMModGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void AMModGUI::leaveEvent (QEvent *) private
Definition at line 466 of file ammodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_channelMute_toggled
void AMModGUI::on_channelMute_toggled (bool checked) private slot
Definition at line 189 of file ammodgui.cpp.
References applySettings(), AMModSettings::m_channelMute, and m_settings.
 {
     m_settings.m_channelMute = checked;
     applySettings();
 }
on_deltaFrequency_changed
void AMModGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 152 of file ammodgui.cpp.
References applySettings(), m_channelMarker, AMModSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = value;
     applySettings();
 }
on_feedbackEnable_toggled
void AMModGUI::on_feedbackEnable_toggled (bool checked) private slot
Definition at line 239 of file ammodgui.cpp.
References applySettings(), AMModSettings::m_feedbackAudioEnable, and m_settings.
 {
     m_settings.m_feedbackAudioEnable = checked;
     applySettings();
 }
on_feedbackVolume_valueChanged
void AMModGUI::on_feedbackVolume_valueChanged (int value) private slot
Definition at line 245 of file ammodgui.cpp.
References applySettings(), arg(), AMModSettings::m_feedbackVolumeFactor, m_settings, and ui.
 {
     ui->feedbackVolumeText->setText(QString("%1").arg(value / 100.0, 0, 'f', 2));
     m_settings.m_feedbackVolumeFactor = value / 100.0;
     applySettings();
 }
on_mic_toggled
void AMModGUI::on_mic_toggled (bool checked) private slot
Definition at line 230 of file ammodgui.cpp.
References AMModSettings::AMModInputAudio, AMModSettings::AMModInputNone, applySettings(), AMModSettings::m_modAFInput, m_settings, and ui.
 {
     ui->play->setEnabled(!checked); // release other source inputs
     ui->morseKeyer->setEnabled(!checked);
     ui->tone->setEnabled(!checked); // release other source inputs
     m_settings.m_modAFInput = checked ? AMModSettings::AMModInputAudio : AMModSettings::AMModInputNone;
     applySettings();
 }
on_modPercent_valueChanged
void AMModGUI::on_modPercent_valueChanged (int value) private slot
Definition at line 167 of file ammodgui.cpp.
References applySettings(), arg(), AMModSettings::m_modFactor, m_settings, and ui.
 {
     ui->modPercentText->setText(QString("%1").arg(value));
     m_settings.m_modFactor = value / 100.0;
     applySettings();
 }
on_morseKeyer_toggled
void AMModGUI::on_morseKeyer_toggled (bool checked) private slot
Definition at line 221 of file ammodgui.cpp.
References AMModSettings::AMModInputCWTone, AMModSettings::AMModInputNone, applySettings(), AMModSettings::m_modAFInput, m_settings, and ui.
 {
     ui->play->setEnabled(!checked); // release other source inputs
     ui->tone->setEnabled(!checked); // release other source inputs
     ui->mic->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? AMModSettings::AMModInputCWTone : AMModSettings::AMModInputNone;
     applySettings();
 }
on_navTimeSlider_valueChanged
void AMModGUI::on_navTimeSlider_valueChanged (int value) private slot
Definition at line 252 of file ammodgui.cpp.
References AMMod::MsgConfigureFileSourceSeek::create(), BasebandSampleSource::getInputMessageQueue(), m_amMod, m_enableNavTime, m_recordLength, and MessageQueue::push().
 {
     if (m_enableNavTime && ((value >= 0) && (value <= 100)))
     {
         int t_sec = (m_recordLength * value) / 100;
         QTime t(0, 0, 0, 0);
         t = t.addSecs(t_sec);
         AMMod::MsgConfigureFileSourceSeek* message = AMMod::MsgConfigureFileSourceSeek::create(value);
         m_amMod->getInputMessageQueue()->push(message);
     }
 }
on_play_toggled
void AMModGUI::on_play_toggled (bool checked) private slot
Definition at line 201 of file ammodgui.cpp.
References AMModSettings::AMModInputFile, AMModSettings::AMModInputNone, applySettings(), m_enableNavTime, AMModSettings::m_modAFInput, m_settings, and ui.
 {
     ui->tone->setEnabled(!checked); // release other source inputs
     ui->morseKeyer->setEnabled(!checked);
     ui->mic->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? AMModSettings::AMModInputFile : AMModSettings::AMModInputNone;
     applySettings();
     ui->navTimeSlider->setEnabled(!checked);
     m_enableNavTime = !checked;
 }
on_playLoop_toggled
void AMModGUI::on_playLoop_toggled (bool checked) private slot
Definition at line 195 of file ammodgui.cpp.
References applySettings(), AMModSettings::m_playLoop, and m_settings.
 {
     m_settings.m_playLoop = checked;
     applySettings();
 }
on_rfBW_valueChanged
void AMModGUI::on_rfBW_valueChanged (int value) private slot
Definition at line 159 of file ammodgui.cpp.
References applySettings(), arg(), m_channelMarker, AMModSettings::m_rfBandwidth, m_settings, ChannelMarker::setBandwidth(), and ui.
 {
     ui->rfBWText->setText(QString("%1 kHz").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_rfBandwidth = value * 100.0;
     m_channelMarker.setBandwidth(value * 100);
     applySettings();
 }
on_showFileDialog_clicked
void AMModGUI::on_showFileDialog_clicked (bool checked) private slot
Definition at line 265 of file ammodgui.cpp.
References configureFileName(), m_fileName, and ui.
 {
     (void) checked;
     QString fileName = QFileDialog::getOpenFileName(this,
         tr("Open raw audio file"), ".", tr("Raw audio Files (*.raw)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "")
     {
         m_fileName = fileName;
         ui->recordFileText->setText(m_fileName);
         ui->play->setEnabled(true);
         configureFileName();
     }
 }
on_tone_toggled
void AMModGUI::on_tone_toggled (bool checked) private slot
Definition at line 212 of file ammodgui.cpp.
References AMModSettings::AMModInputNone, AMModSettings::AMModInputTone, applySettings(), AMModSettings::m_modAFInput, m_settings, and ui.
 {
     ui->play->setEnabled(!checked); // release other source inputs
     ui->morseKeyer->setEnabled(!checked);
     ui->mic->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? AMModSettings::AMModInputTone : AMModSettings::AMModInputNone;
     applySettings();
 }
on_toneFrequency_valueChanged
void AMModGUI::on_toneFrequency_valueChanged (int value) private slot
Definition at line 181 of file ammodgui.cpp.
References applySettings(), arg(), m_settings, AMModSettings::m_toneFrequency, and ui.
 {
     ui->toneFrequencyText->setText(QString("%1k").arg(value / 100.0, 0, 'f', 2));
     m_settings.m_toneFrequency = value * 10.0;
     applySettings();
 }
on_volume_valueChanged
void AMModGUI::on_volume_valueChanged (int value) private slot
Definition at line 174 of file ammodgui.cpp.
References applySettings(), arg(), m_settings, AMModSettings::m_volumeFactor, and ui.
 {
     ui->volumeText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_volumeFactor = value / 10.0;
     applySettings();
 }
onMenuDialogCalled
void AMModGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 293 of file ammodgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, AMModSettings::m_inputFrequencyOffset, AMModSettings::m_reverseAPIAddress, AMModSettings::m_reverseAPIChannelIndex, AMModSettings::m_reverseAPIDeviceIndex, AMModSettings::m_reverseAPIPort, AMModSettings::m_rgbColor, m_settings, AMModSettings::m_title, AMModSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by AMModGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void AMModGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 287 of file ammodgui.cpp.
Referenced by AMModGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void AMModGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 70 of file ammodgui.cpp.
References applySettings(), displaySettings(), m_settings, and AMModSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
serialize()
QByteArray AMModGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 77 of file ammodgui.cpp.
References m_settings, and AMModSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void AMModGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 64 of file ammodgui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     applySettings();
 }
setName()
void AMModGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 50 of file ammodgui.cpp.
 {
     setObjectName(name);
 }
tick
void AMModGUI::tick () private slot
Definition at line 502 of file ammodgui.cpp.
References AMModSettings::AMModInputFile, arg(), AMMod::MsgConfigureFileSourceStreamTiming::create(), CalcDb::dbPower(), BasebandSampleSource::getInputMessageQueue(), AMMod::getMagSq(), m_amMod, m_channelPowerDbAvg, AMModSettings::m_modAFInput, m_settings, m_tickCount, MessageQueue::push(), and ui.
Referenced by AMModGUI().
 {
     double powDb = CalcDb::dbPower(m_amMod->getMagSq());
     m_channelPowerDbAvg(powDb);
     ui->channelPower->setText(tr("%1 dB").arg(m_channelPowerDbAvg.asDouble(), 0, 'f', 1));
     if (((++m_tickCount & 0xf) == 0) && (m_settings.m_modAFInput == AMModSettings::AMModInputFile))
     {
         AMMod::MsgConfigureFileSourceStreamTiming* message = AMMod::MsgConfigureFileSourceStreamTiming::create();
         m_amMod->getInputMessageQueue()->push(message);
     }
 }
updateWithStreamData()
void AMModGUI::updateWithStreamData () private
Definition at line 515 of file ammodgui.cpp.
References m_recordLength, ui, and updateWithStreamTime().
Referenced by handleMessage().
 {
     QTime recordLength(0, 0, 0, 0);
     recordLength = recordLength.addSecs(m_recordLength);
     QString s_time = recordLength.toString("HH:mm:ss");
     ui->recordLengthText->setText(s_time);
     updateWithStreamTime();
 }
updateWithStreamTime()
void AMModGUI::updateWithStreamTime () private
Definition at line 524 of file ammodgui.cpp.
References m_enableNavTime, m_recordLength, m_recordSampleRate, m_samplesCount, and ui.
Referenced by handleMessage(), and updateWithStreamData().
 {
     int t_sec = 0;
     int t_msec = 0;
     if (m_recordSampleRate > 0)
     {
         t_msec = ((m_samplesCount * 1000) / m_recordSampleRate) % 1000;
         t_sec = m_samplesCount / m_recordSampleRate;
     }
     QTime t(0, 0, 0, 0);
     t = t.addSecs(t_sec);
     t = t.addMSecs(t_msec);
     QString s_timems = t.toString("HH:mm:ss.zzz");
     QString s_time = t.toString("HH:mm:ss");
     ui->relTimeText->setText(s_timems);
     if (!m_enableNavTime)
     {
         float posRatio = (float) t_sec / (float) m_recordLength;
         ui->navTimeSlider->setValue((int) (posRatio * 100.0));
     }
 }
Member Data Documentation
m_amMod
AMMod* AMModGUI::m_amMod private
Definition at line 69 of file ammodgui.h.
Referenced by AMModGUI(), applySettings(), configureFileName(), on_navTimeSlider_valueChanged(), tick(), and ~AMModGUI().
m_channelMarker
ChannelMarker AMModGUI::m_channelMarker private
Definition at line 65 of file ammodgui.h.
Referenced by AMModGUI(), applySettings(), channelMarkerChangedByCursor(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), on_rfBW_valueChanged(), onMenuDialogCalled(), and setCenterFrequency().
m_channelPowerDbAvg
MovingAverageUtil<double, double, 20> AMModGUI::m_channelPowerDbAvg private
Definition at line 70 of file ammodgui.h.
Referenced by tick().
m_deviceUISet
DeviceUISet* AMModGUI::m_deviceUISet private
Definition at line 64 of file ammodgui.h.
Referenced by AMModGUI(), and ~AMModGUI().
m_doApplySettings
bool AMModGUI::m_doApplySettings private
Definition at line 67 of file ammodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_enableNavTime
bool AMModGUI::m_enableNavTime private
Definition at line 77 of file ammodgui.h.
Referenced by on_navTimeSlider_valueChanged(), on_play_toggled(), and updateWithStreamTime().
m_fileName
QString AMModGUI::m_fileName private
Definition at line 72 of file ammodgui.h.
Referenced by configureFileName(), and on_showFileDialog_clicked().
m_inputMessageQueue
MessageQueue AMModGUI::m_inputMessageQueue private
Definition at line 78 of file ammodgui.h.
m_pluginAPI
PluginAPI* AMModGUI::m_pluginAPI private
Definition at line 63 of file ammodgui.h.
m_recordLength
quint32 AMModGUI::m_recordLength private
Definition at line 73 of file ammodgui.h.
Referenced by handleMessage(), on_navTimeSlider_valueChanged(), updateWithStreamData(), and updateWithStreamTime().
m_recordSampleRate
int AMModGUI::m_recordSampleRate private
Definition at line 74 of file ammodgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_samplesCount
int AMModGUI::m_samplesCount private
Definition at line 75 of file ammodgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_settings
AMModSettings AMModGUI::m_settings private
Definition at line 66 of file ammodgui.h.
Referenced by AMModGUI(), applySettings(), audioFeedbackSelect(), audioSelect(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), handleMessage(), on_channelMute_toggled(), on_deltaFrequency_changed(), on_feedbackEnable_toggled(), on_feedbackVolume_valueChanged(), on_mic_toggled(), on_modPercent_valueChanged(), on_morseKeyer_toggled(), on_play_toggled(), on_playLoop_toggled(), on_rfBW_valueChanged(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), serialize(), and tick().
m_tickCount
std::size_t AMModGUI::m_tickCount private
Definition at line 76 of file ammodgui.h.
Referenced by tick().
ui
Ui::AMModGUI* AMModGUI::ui private
Definition at line 62 of file ammodgui.h.
Referenced by AMModGUI(), channelMarkerChangedByCursor(), displaySettings(), handleMessage(), on_feedbackVolume_valueChanged(), on_mic_toggled(), on_modPercent_valueChanged(), on_morseKeyer_toggled(), on_play_toggled(), on_rfBW_valueChanged(), on_showFileDialog_clicked(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), tick(), updateWithStreamData(), updateWithStreamTime(), and ~AMModGUI().
The documentation for this class was generated from the following files:
plugins/channeltx/modam/ammodgui.h
plugins/channeltx/modam/ammodgui.cpp