SDRAngel: DeviceXTRXShared::MsgReportBuddyChange Class Reference
DeviceXTRXShared::MsgReportBuddyChange Class Reference
#include <devicextrxshared.h>
Public Member Functions
int getDevSampleRate () const
unsigned getLog2HardDecimInterp () const
uint64_t getCenterFrequency () const
bool getRxElseTx () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportBuddyChange * create (int devSampleRate, unsigned log2HardDecimInterp, uint64_t centerFrequency, bool rxElseTx)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportBuddyChange (int devSampleRate, unsigned log2HardDecimInterp, uint64_t centerFrequency, bool rxElseTx)
Private Attributes
int m_devSampleRate
device/host sample rate
unsigned m_log2HardDecimInterp
log2 of hardware decimation or interpolation
uint64_t m_centerFrequency
Center frequency.
bool m_rxElseTx
tells which side initiated the message
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 35 of file devicextrxshared.h.
Constructor & Destructor Documentation
MsgReportBuddyChange()
DeviceXTRXShared::MsgReportBuddyChange::MsgReportBuddyChange (int devSampleRate, unsigned log2HardDecimInterp, uint64_t centerFrequency, bool rxElseTx) inline private
Definition at line 63 of file devicextrxshared.h.
Referenced by create().
                                :
             Message(),
             m_devSampleRate(devSampleRate),
             m_log2HardDecimInterp(log2HardDecimInterp),
             m_centerFrequency(centerFrequency),
             m_rxElseTx(rxElseTx)
         { }
Member Function Documentation
create()
static MsgReportBuddyChange* DeviceXTRXShared::MsgReportBuddyChange::create (int devSampleRate, unsigned log2HardDecimInterp, uint64_t centerFrequency, bool rxElseTx) inline static
Definition at line 44 of file devicextrxshared.h.
References MsgReportBuddyChange().
Referenced by XTRXOutput::applySettings(), XTRXOutput::handleMessage(), and XTRXInput::handleMessage().
         {
             return new MsgReportBuddyChange(
                     devSampleRate,
                     log2HardDecimInterp,
                     centerFrequency,
                     rxElseTx);
         }
getCenterFrequency()
uint64_t DeviceXTRXShared::MsgReportBuddyChange::getCenterFrequency () const inline
Definition at line 41 of file devicextrxshared.h.
References m_centerFrequency.
Referenced by XTRXOutputGUI::handleMessage(), XTRXInputGUI::handleMessage(), XTRXOutput::handleMessage(), and XTRXInput::handleMessage().
 { return m_centerFrequency; }
getDevSampleRate()
int DeviceXTRXShared::MsgReportBuddyChange::getDevSampleRate () const inline
Definition at line 39 of file devicextrxshared.h.
References m_devSampleRate.
Referenced by XTRXOutputGUI::handleMessage(), XTRXInputGUI::handleMessage(), XTRXOutput::handleMessage(), and XTRXInput::handleMessage().
 { return m_devSampleRate; }
getLog2HardDecimInterp()
unsigned DeviceXTRXShared::MsgReportBuddyChange::getLog2HardDecimInterp () const inline
Definition at line 40 of file devicextrxshared.h.
References m_log2HardDecimInterp.
Referenced by XTRXOutputGUI::handleMessage(), XTRXInputGUI::handleMessage(), XTRXOutput::handleMessage(), and XTRXInput::handleMessage().
 { return m_log2HardDecimInterp; }
getRxElseTx()
bool DeviceXTRXShared::MsgReportBuddyChange::getRxElseTx () const inline
Definition at line 42 of file devicextrxshared.h.
References m_rxElseTx.
Referenced by XTRXOutputGUI::handleMessage(), XTRXInputGUI::handleMessage(), XTRXOutput::handleMessage(), and XTRXInput::handleMessage().
 { return m_rxElseTx; }
Member Data Documentation
m_centerFrequency
uint64_t DeviceXTRXShared::MsgReportBuddyChange::m_centerFrequency private
Center frequency.
Definition at line 60 of file devicextrxshared.h.
Referenced by getCenterFrequency().
m_devSampleRate
int DeviceXTRXShared::MsgReportBuddyChange::m_devSampleRate private
device/host sample rate
Definition at line 58 of file devicextrxshared.h.
Referenced by getDevSampleRate().
m_log2HardDecimInterp
unsigned DeviceXTRXShared::MsgReportBuddyChange::m_log2HardDecimInterp private
log2 of hardware decimation or interpolation
Definition at line 59 of file devicextrxshared.h.
Referenced by getLog2HardDecimInterp().
m_rxElseTx
bool DeviceXTRXShared::MsgReportBuddyChange::m_rxElseTx private
tells which side initiated the message
Definition at line 61 of file devicextrxshared.h.
Referenced by getRxElseTx().
The documentation for this class was generated from the following file:
devices/xtrx/devicextrxshared.h