SDRAngel: DSPDeviceSourceEngine Class Reference
DSPDeviceSourceEngine Class Reference
#include <dspdevicesourceengine.h>
Inherits QThread.
Public Types
enum State {
StNotStarted, StIdle, StReady, StRunning,
StError
}
Public Member Functions
DSPDeviceSourceEngine (uint uid, QObject *parent=NULL)
~DSPDeviceSourceEngine ()
uint getUID () const
MessageQueue * getInputMessageQueue ()
void start ()
This thread start.
void stop ()
This thread stop.
bool initAcquisition ()
Initialize acquisition sequence.
bool startAcquisition ()
Start acquisition sequence.
void stopAcquistion ()
Stop acquisition sequence.
void setSource (DeviceSampleSource *source)
Set the sample source type.
void setSourceSequence (int sequence)
Set the sample source sequence in type.
DeviceSampleSource * getSource ()
void addSink (BasebandSampleSink *sink)
Add a sample sink.
void removeSink (BasebandSampleSink *sink)
Remove a sample sink.
void addThreadedSink (ThreadedBasebandSampleSink *sink)
Add a sample sink that will run on its own thread.
void removeThreadedSink (ThreadedBasebandSampleSink *sink)
Remove a sample sink that runs on its own thread.
void configureCorrections (bool dcOffsetCorrection, bool iqImbalanceCorrection)
Configure DSP corrections.
State state () const
Return DSP engine current state.
QString errorMessage ()
Return the current error message.
QString sourceDeviceDescription ()
Return the source device description.
Private Types
typedef std::list< BasebandSampleSink * > BasebandSampleSinks
typedef std::list< ThreadedBasebandSampleSink * > ThreadedBasebandSampleSinks
Private Slots
void handleData ()
Handle data when samples from source FIFO are ready to be processed.
void handleInputMessages ()
Handle input message queue.
void handleSynchronousMessages ()
Handle synchronous messages with the thread.
Private Member Functions
void run ()
void iqCorrections (SampleVector::iterator begin, SampleVector::iterator end, bool imbalanceCorrection)
void dcOffset (SampleVector::iterator begin, SampleVector::iterator end)
void imbalance (SampleVector::iterator begin, SampleVector::iterator end)
void work ()
transfer samples from source to sinks if in running state
State gotoIdle ()
Go to the idle state.
State gotoInit ()
Go to the acquisition init state from idle.
State gotoRunning ()
Go to the running state from ready state.
State gotoError (const QString &errorMsg)
Go to an error state.
void handleSetSource (DeviceSampleSource *source)
Manage source setting.
Private Attributes
uint m_uid
unique ID
MessageQueue m_inputMessageQueue
SyncMessenger m_syncMessenger
Used to process messages synchronously with the thread.
State m_state
QString m_errorMessage
QString m_deviceDescription
DeviceSampleSource * m_deviceSampleSource
int m_sampleSourceSequence
BasebandSampleSinks m_basebandSampleSinks
sample sinks within main thread (usually spectrum, file output)
ThreadedBasebandSampleSinks m_threadedBasebandSampleSinks
sample sinks on their own threads (usually channels)
uint m_sampleRate
quint64 m_centerFrequency
bool m_dcOffsetCorrection
bool m_iqImbalanceCorrection
double m_iOffset
double m_qOffset
MovingAverageUtil< int32_t, int64_t, 1024 > m_iBeta
MovingAverageUtil< int32_t, int64_t, 1024 > m_qBeta
MovingAverageUtil< float, double, 128 > m_avgII
MovingAverageUtil< float, double, 128 > m_avgIQ
MovingAverageUtil< float, double, 128 > m_avgII2
MovingAverageUtil< float, double, 128 > m_avgQQ2
MovingAverageUtil< double, double, 128 > m_avgPhi
MovingAverageUtil< double, double, 128 > m_avgAmp
qint32 m_iRange
qint32 m_qRange
qint32 m_imbalance
Detailed Description
Definition at line 37 of file dspdevicesourceengine.h.
Member Typedef Documentation
BasebandSampleSinks
typedef std::list<BasebandSampleSink*> DSPDeviceSourceEngine::BasebandSampleSinks private
Definition at line 94 of file dspdevicesourceengine.h.
ThreadedBasebandSampleSinks
typedef std::list<ThreadedBasebandSampleSink*> DSPDeviceSourceEngine::ThreadedBasebandSampleSinks private
Definition at line 97 of file dspdevicesourceengine.h.
Member Enumeration Documentation
State
enum DSPDeviceSourceEngine::State
Enumerator
StNotStarted
engine is before initialization
StIdle
engine is idle
StReady
engine is ready to run
StRunning
engine is running
StError
engine is in error
Definition at line 41 of file dspdevicesourceengine.h.
                {
         StNotStarted,
         StIdle,
         StReady,
         StRunning,
         StError
     };
Constructor & Destructor Documentation
DSPDeviceSourceEngine()
DSPDeviceSourceEngine::DSPDeviceSourceEngine (uint uid, QObject * parent = NULL)
Definition at line 31 of file dspdevicesourceengine.cpp.
References handleInputMessages(), handleSynchronousMessages(), m_inputMessageQueue, and m_syncMessenger.
                                                                       :
     QThread(parent),
     m_uid(uid),
     m_state(StNotStarted),
     m_deviceSampleSource(nullptr),
     m_sampleSourceSequence(0),
     m_basebandSampleSinks(),
     m_sampleRate(0),
     m_centerFrequency(0),
     m_dcOffsetCorrection(false),
     m_iqImbalanceCorrection(false),
     m_iOffset(0),
     m_qOffset(0),
     m_iRange(1 << 16),
     m_qRange(1 << 16),
     m_imbalance(65536)
 {
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     connect(&m_syncMessenger, SIGNAL(messageSent()), this, SLOT(handleSynchronousMessages()), Qt::QueuedConnection);
     moveToThread(this);
 }
~DSPDeviceSourceEngine()
DSPDeviceSourceEngine::~DSPDeviceSourceEngine ()
Definition at line 54 of file dspdevicesourceengine.cpp.
References stop().
 {
     stop();
     wait();
 }
Member Function Documentation
addSink()
void DSPDeviceSourceEngine::addSink (BasebandSampleSink * sink)
Add a sample sink.
Definition at line 125 of file dspdevicesourceengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::addAncillarySink(), and MainWindow::addSourceDevice().
 {
     qDebug() << "DSPDeviceSourceEngine::addSink: " << sink->objectName().toStdString().c_str();
     DSPAddBasebandSampleSink cmd(sink);
     m_syncMessenger.sendWait(cmd);
 }
addThreadedSink()
void DSPDeviceSourceEngine::addThreadedSink (ThreadedBasebandSampleSink * sink)
Add a sample sink that will run on its own thread.
Definition at line 139 of file dspdevicesourceengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::addChannelSink().
 {
     qDebug() << "DSPDeviceSourceEngine::addThreadedSink: " << sink->objectName().toStdString().c_str();
     DSPAddThreadedBasebandSampleSink cmd(sink);
     m_syncMessenger.sendWait(cmd);
 }
configureCorrections()
void DSPDeviceSourceEngine::configureCorrections (bool dcOffsetCorrection, bool iqImbalanceCorrection)
Configure DSP corrections.
Definition at line 153 of file dspdevicesourceengine.cpp.
References m_inputMessageQueue, and MessageQueue::push().
Referenced by DeviceAPI::configureCorrections().
 {
     qDebug() << "DSPDeviceSourceEngine::configureCorrections";
     DSPConfigureCorrection* cmd = new DSPConfigureCorrection(dcOffsetCorrection, iqImbalanceCorrection);
     m_inputMessageQueue.push(cmd);
 }
dcOffset()
void DSPDeviceSourceEngine::dcOffset (SampleVector::iterator begin, SampleVector::iterator end) private
Definition at line 265 of file dspdevicesourceengine.cpp.
References m_iBeta, and m_qBeta.
 {
     // sum and correct in one pass
     for(SampleVector::iterator it = begin; it < end; it++)
     {
         m_iBeta(it->real());
         m_qBeta(it->imag());
         it->m_real -= (int32_t) m_iBeta;
         it->m_imag -= (int32_t) m_qBeta;
     }
 }
errorMessage()
QString DSPDeviceSourceEngine::errorMessage ()
Return the current error message.
Definition at line 160 of file dspdevicesourceengine.cpp.
References DSPGetErrorMessage::getErrorMessage(), m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::errorMessage(), and gotoError().
 {
     qDebug() << "DSPDeviceSourceEngine::errorMessage";
     DSPGetErrorMessage cmd;
     m_syncMessenger.sendWait(cmd);
     return cmd.getErrorMessage();
 }
getInputMessageQueue()
MessageQueue* DSPDeviceSourceEngine::getInputMessageQueue () inline
Definition at line 54 of file dspdevicesourceengine.h.
Referenced by DeviceAPI::getDeviceEngineInputMessageQueue().
 { return &m_inputMessageQueue; }
getSource()
DeviceSampleSource* DSPDeviceSourceEngine::getSource () inline
Definition at line 65 of file dspdevicesourceengine.h.
Referenced by WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), LocalSink::getLocalDevice(), LocalSink::getLocalDevices(), DeviceAPI::getSampleSource(), DeviceAPI::getSamplingDeviceGUIMessageQueue(), DeviceAPI::getSamplingDeviceInputMessageQueue(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), DeviceAPI::loadSamplingDeviceSettings(), and DeviceAPI::saveSamplingDeviceSettings().
 { return m_deviceSampleSource; }
getUID()
uint DSPDeviceSourceEngine::getUID () const inline
Definition at line 52 of file dspdevicesourceengine.h.
Referenced by MainCore::addSourceDevice(), MainWindow::addSourceDevice(), DeviceAPI::getDeviceUID(), and LocalSink::getLocalDevice().
 { return m_uid; }
gotoError()
DSPDeviceSourceEngine::State DSPDeviceSourceEngine::gotoError (const QString & errorMsg) private
Go to an error state.
Definition at line 568 of file dspdevicesourceengine.cpp.
References errorMessage(), m_deviceDescription, m_errorMessage, m_state, and StError.
Referenced by gotoInit(), and gotoRunning().
 {
     qDebug() << "DSPDeviceSourceEngine::gotoError: " << errorMessage;
     m_errorMessage = errorMessage;
     m_deviceDescription.clear();
     m_state = StError;
     return StError;
 }
gotoIdle()
DSPDeviceSourceEngine::State DSPDeviceSourceEngine::gotoIdle () private
Go to the idle state.
Definition at line 415 of file dspdevicesourceengine.cpp.
References m_basebandSampleSinks, m_deviceDescription, m_deviceSampleSource, m_sampleRate, m_state, m_threadedBasebandSampleSinks, StError, StIdle, StNotStarted, DeviceSampleSource::stop(), StReady, and StRunning.
Referenced by handleSetSource(), handleSynchronousMessages(), and stop().
 {
     qDebug() << "DSPDeviceSourceEngine::gotoIdle";
     switch(m_state) {
         case StNotStarted:
             return StNotStarted;
         case StIdle:
         case StError:
             return StIdle;
         case StReady:
         case StRunning:
             break;
     }
     if(m_deviceSampleSource == 0)
     {
         return StIdle;
     }
     // stop everything
     for(BasebandSampleSinks::const_iterator it = m_basebandSampleSinks.begin(); it != m_basebandSampleSinks.end(); it++)
     {
         (*it)->stop();
     }
     for(ThreadedBasebandSampleSinks::const_iterator it = m_threadedBasebandSampleSinks.begin(); it != m_threadedBasebandSampleSinks.end(); it++)
     {
         (*it)->stop();
     }
     m_deviceSampleSource->stop();
     m_deviceDescription.clear();
     m_sampleRate = 0;
     return StIdle;
 }
gotoInit()
DSPDeviceSourceEngine::State DSPDeviceSourceEngine::gotoInit () private
Go to the acquisition init state from idle.
Definition at line 456 of file dspdevicesourceengine.cpp.
References DeviceSampleSource::getCenterFrequency(), DeviceSampleSource::getDeviceDescription(), DeviceSampleSource::getMessageQueueToGUI(), DeviceSampleSource::getSampleRate(), gotoError(), m_basebandSampleSinks, m_centerFrequency, m_deviceDescription, m_deviceSampleSource, m_iOffset, m_iRange, m_qOffset, m_qRange, m_sampleRate, m_state, m_threadedBasebandSampleSinks, MessageQueue::push(), StError, StIdle, StNotStarted, StReady, and StRunning.
Referenced by handleSynchronousMessages().
 {
     switch(m_state) {
         case StNotStarted:
             return StNotStarted;
         case StRunning: // FIXME: assumes it goes first through idle state. Could we get back to init from running directly?
             return StRunning;
         case StReady:
             return StReady;
         case StIdle:
         case StError:
             break;
     }
     if (m_deviceSampleSource == 0)
     {
         return gotoError("No sample source configured");
     }
     // init: pass sample rate and center frequency to all sample rate and/or center frequency dependent sinks and wait for completion
     m_iOffset = 0;
     m_qOffset = 0;
     m_iRange = 1 << 16;
     m_qRange = 1 << 16;
     m_deviceDescription = m_deviceSampleSource->getDeviceDescription();
     m_centerFrequency = m_deviceSampleSource->getCenterFrequency();
     m_sampleRate = m_deviceSampleSource->getSampleRate();
     qDebug() << "DSPDeviceSourceEngine::gotoInit: "
             << " m_deviceDescription: " << m_deviceDescription.toStdString().c_str()
             << " sampleRate: " << m_sampleRate
             << " centerFrequency: " << m_centerFrequency;
     DSPSignalNotification notif(m_sampleRate, m_centerFrequency);
     for (BasebandSampleSinks::const_iterator it = m_basebandSampleSinks.begin(); it != m_basebandSampleSinks.end(); ++it)
     {
         qDebug() << "DSPDeviceSourceEngine::gotoInit: initializing " << (*it)->objectName().toStdString().c_str();
         (*it)->handleMessage(notif);
     }
     for (ThreadedBasebandSampleSinks::const_iterator it = m_threadedBasebandSampleSinks.begin(); it != m_threadedBasebandSampleSinks.end(); ++it)
     {
         qDebug() << "DSPDeviceSourceEngine::gotoInit: initializing ThreadedSampleSink(" << (*it)->getSampleSinkObjectName().toStdString().c_str() << ")";
         (*it)->handleSinkMessage(notif);
     }
     // pass data to listeners
     if (m_deviceSampleSource->getMessageQueueToGUI())
     {
         DSPSignalNotification* rep = new DSPSignalNotification(notif); // make a copy for the output queue
         m_deviceSampleSource->getMessageQueueToGUI()->push(rep);
     }
     return StReady;
 }
gotoRunning()
DSPDeviceSourceEngine::State DSPDeviceSourceEngine::gotoRunning () private
Go to the running state from ready state.
Definition at line 518 of file dspdevicesourceengine.cpp.
References gotoError(), m_basebandSampleSinks, m_deviceDescription, m_deviceSampleSource, m_inputMessageQueue, m_state, m_threadedBasebandSampleSinks, MessageQueue::size(), DeviceSampleSource::start(), StError, StIdle, StNotStarted, StReady, and StRunning.
Referenced by handleSynchronousMessages().
 {
     qDebug() << "DSPDeviceSourceEngine::gotoRunning";
     switch(m_state)
     {
         case StNotStarted:
             return StNotStarted;
         case StIdle:
             return StIdle;
         case StRunning:
             return StRunning;
         case StReady:
         case StError:
             break;
     }
     if(m_deviceSampleSource == NULL) {
         return gotoError("DSPDeviceSourceEngine::gotoRunning: No sample source configured");
     }
     qDebug() << "DSPDeviceSourceEngine::gotoRunning: " << m_deviceDescription.toStdString().c_str() << " started";
     // Start everything
     if(!m_deviceSampleSource->start())
     {
         return gotoError("Could not start sample source");
     }
     for(BasebandSampleSinks::const_iterator it = m_basebandSampleSinks.begin(); it != m_basebandSampleSinks.end(); it++)
     {
         qDebug() << "DSPDeviceSourceEngine::gotoRunning: starting " << (*it)->objectName().toStdString().c_str();
         (*it)->start();
     }
     for (ThreadedBasebandSampleSinks::const_iterator it = m_threadedBasebandSampleSinks.begin(); it != m_threadedBasebandSampleSinks.end(); ++it)
     {
         qDebug() << "DSPDeviceSourceEngine::gotoRunning: starting ThreadedSampleSink(" << (*it)->getSampleSinkObjectName().toStdString().c_str() << ")";
         (*it)->start();
     }
     qDebug() << "DSPDeviceSourceEngine::gotoRunning:input message queue pending: " << m_inputMessageQueue.size();
     return StRunning;
 }
handleData
void DSPDeviceSourceEngine::handleData () private slot
Handle data when samples from source FIFO are ready to be processed.
Definition at line 600 of file dspdevicesourceengine.cpp.
References m_state, StRunning, and work().
Referenced by handleSetSource().
 {
     if(m_state == StRunning)
     {
         work();
     }
 }
handleInputMessages
void DSPDeviceSourceEngine::handleInputMessages () private slot
Handle input message queue.
Definition at line 686 of file dspdevicesourceengine.cpp.
References DSPSignalNotification::getCenterFrequency(), DSPConfigureCorrection::getDCOffsetCorrection(), Message::getIdentifier(), DSPConfigureCorrection::getIQImbalanceCorrection(), DeviceSampleSource::getMessageQueueToGUI(), DSPSignalNotification::getSampleRate(), m_avgAmp, m_avgII, m_avgII2, m_avgIQ, m_avgPhi, m_avgQQ2, m_basebandSampleSinks, m_centerFrequency, m_dcOffsetCorrection, m_deviceSampleSource, m_iBeta, m_imbalance, m_inputMessageQueue, m_iOffset, m_iqImbalanceCorrection, m_iRange, m_qBeta, m_qOffset, m_qRange, m_sampleRate, m_threadedBasebandSampleSinks, Message::match(), MessageQueue::pop(), MessageQueue::push(), and MovingAverageUtil< T, Total, N >::reset().
Referenced by DSPDeviceSourceEngine().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("DSPDeviceSourceEngine::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPConfigureCorrection::match(*message))
         {
             DSPConfigureCorrection* conf = (DSPConfigureCorrection*) message;
             m_iqImbalanceCorrection = conf->getIQImbalanceCorrection();
             if(m_dcOffsetCorrection != conf->getDCOffsetCorrection())
             {
                 m_dcOffsetCorrection = conf->getDCOffsetCorrection();
                 m_iOffset = 0;
                 m_qOffset = 0;
             }
             if(m_iqImbalanceCorrection != conf->getIQImbalanceCorrection())
             {
                 m_iqImbalanceCorrection = conf->getIQImbalanceCorrection();
                 m_iRange = 1 << 16;
                 m_qRange = 1 << 16;
                 m_imbalance = 65536;
             }
             m_avgAmp.reset();
             m_avgII.reset();
             m_avgII2.reset();
             m_avgIQ.reset();
             m_avgPhi.reset();
             m_avgQQ2.reset();
             m_iBeta.reset();
             m_qBeta.reset();
             delete message;
         }
         else if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification *notif = (DSPSignalNotification *) message;
             // update DSP values
             m_sampleRate = notif->getSampleRate();
             m_centerFrequency = notif->getCenterFrequency();
             qDebug() << "DSPDeviceSourceEngine::handleInputMessages: DSPSignalNotification:"
                 << " m_sampleRate: " << m_sampleRate
                 << " m_centerFrequency: " << m_centerFrequency;
             // forward source changes to channel sinks with immediate execution (no queuing)
             for(BasebandSampleSinks::const_iterator it = m_basebandSampleSinks.begin(); it != m_basebandSampleSinks.end(); it++)
             {
                 qDebug() << "DSPDeviceSourceEngine::handleInputMessages: forward message to " << (*it)->objectName().toStdString().c_str();
                 (*it)->handleMessage(*message);
             }
             for (ThreadedBasebandSampleSinks::const_iterator it = m_threadedBasebandSampleSinks.begin(); it != m_threadedBasebandSampleSinks.end(); ++it)
             {
                 qDebug() << "DSPDeviceSourceEngine::handleSourceMessages: forward message to ThreadedSampleSink(" << (*it)->getSampleSinkObjectName().toStdString().c_str() << ")";
                 (*it)->handleSinkMessage(*message);
             }
             // forward changes to source GUI input queue
             MessageQueue *guiMessageQueue = m_deviceSampleSource->getMessageQueueToGUI();
             qDebug("DSPDeviceSourceEngine::handleInputMessages: DSPSignalNotification: guiMessageQueue: %p", guiMessageQueue);
             if (guiMessageQueue) {
                 DSPSignalNotification* rep = new DSPSignalNotification(*notif); // make a copy for the source GUI
                 guiMessageQueue->push(rep);
             }
             //m_outputMessageQueue.push(rep);
             delete message;
         }
     }
 }
handleSetSource()
void DSPDeviceSourceEngine::handleSetSource (DeviceSampleSource * source) private
Manage source setting.
Definition at line 578 of file dspdevicesourceengine.cpp.
References DeviceSampleSource::getDeviceDescription(), DeviceSampleSource::getSampleFifo(), gotoIdle(), handleData(), and m_deviceSampleSource.
Referenced by handleSynchronousMessages().
 {
     gotoIdle();
 //  if(m_sampleSource != 0)
 //  {
 //      disconnect(m_sampleSource->getSampleFifo(), SIGNAL(dataReady()), this, SLOT(handleData()));
 //  }
     m_deviceSampleSource = source;
     if(m_deviceSampleSource != 0)
     {
         qDebug("DSPDeviceSourceEngine::handleSetSource: set %s", qPrintable(source->getDeviceDescription()));
         connect(m_deviceSampleSource->getSampleFifo(), SIGNAL(dataReady()), this, SLOT(handleData()), Qt::QueuedConnection);
     }
     else
     {
         qDebug("DSPDeviceSourceEngine::handleSetSource: set none");
     }
 }
handleSynchronousMessages
void DSPDeviceSourceEngine::handleSynchronousMessages () private slot
Handle synchronous messages with the thread.
Definition at line 608 of file dspdevicesourceengine.cpp.
References SyncMessenger::done(), Message::getIdentifier(), SyncMessenger::getMessage(), gotoIdle(), gotoInit(), gotoRunning(), BasebandSampleSink::handleMessage(), handleSetSource(), ThreadedBasebandSampleSink::handleSinkMessage(), m_basebandSampleSinks, m_centerFrequency, m_deviceDescription, m_errorMessage, m_sampleRate, m_state, m_syncMessenger, m_threadedBasebandSampleSinks, Message::match(), BasebandSampleSink::start(), ThreadedBasebandSampleSink::start(), StIdle, BasebandSampleSink::stop(), ThreadedBasebandSampleSink::stop(), StReady, and StRunning.
Referenced by DSPDeviceSourceEngine(), and stopAcquistion().
 {
     Message *message = m_syncMessenger.getMessage();
     qDebug() << "DSPDeviceSourceEngine::handleSynchronousMessages: " << message->getIdentifier();
     if (DSPAcquisitionInit::match(*message))
     {
         m_state = gotoIdle();
         if(m_state == StIdle) {
             m_state = gotoInit(); // State goes ready if init is performed
         }
     }
     else if (DSPAcquisitionStart::match(*message))
     {
         if(m_state == StReady) {
             m_state = gotoRunning();
         }
     }
     else if (DSPAcquisitionStop::match(*message))
     {
         m_state = gotoIdle();
     }
     else if (DSPGetSourceDeviceDescription::match(*message))
     {
         ((DSPGetSourceDeviceDescription*) message)->setDeviceDescription(m_deviceDescription);
     }
     else if (DSPGetErrorMessage::match(*message))
     {
         ((DSPGetErrorMessage*) message)->setErrorMessage(m_errorMessage);
     }
     else if (DSPSetSource::match(*message)) {
         handleSetSource(((DSPSetSource*) message)->getSampleSource());
     }
     else if (DSPAddBasebandSampleSink::match(*message))
     {
         BasebandSampleSink* sink = ((DSPAddBasebandSampleSink*) message)->getSampleSink();
         m_basebandSampleSinks.push_back(sink);
         // initialize sample rate and center frequency in the sink:
         DSPSignalNotification msg(m_sampleRate, m_centerFrequency);
         sink->handleMessage(msg);
         // start the sink:
         if(m_state == StRunning) {
             sink->start();
         }
     }
     else if (DSPRemoveBasebandSampleSink::match(*message))
     {
         BasebandSampleSink* sink = ((DSPRemoveBasebandSampleSink*) message)->getSampleSink();
         if(m_state == StRunning) {
             sink->stop();
         }
         m_basebandSampleSinks.remove(sink);
     }
     else if (DSPAddThreadedBasebandSampleSink::match(*message))
     {
         ThreadedBasebandSampleSink *threadedSink = ((DSPAddThreadedBasebandSampleSink*) message)->getThreadedSampleSink();
         m_threadedBasebandSampleSinks.push_back(threadedSink);
         // initialize sample rate and center frequency in the sink:
         DSPSignalNotification msg(m_sampleRate, m_centerFrequency);
         threadedSink->handleSinkMessage(msg);
         // start the sink:
         if(m_state == StRunning) {
             threadedSink->start();
         }
     }
     else if (DSPRemoveThreadedBasebandSampleSink::match(*message))
     {
         ThreadedBasebandSampleSink* threadedSink = ((DSPRemoveThreadedBasebandSampleSink*) message)->getThreadedSampleSink();
         threadedSink->stop();
         m_threadedBasebandSampleSinks.remove(threadedSink);
     }
     m_syncMessenger.done(m_state);
 }
imbalance()
void DSPDeviceSourceEngine::imbalance (SampleVector::iterator begin, SampleVector::iterator end) private
Definition at line 277 of file dspdevicesourceengine.cpp.
References m_imbalance, m_iRange, m_qRange, and SDR_RX_SAMP_SZ.
 {
     int iMin = 0;
     int iMax = 0;
     int qMin = 0;
     int qMax = 0;
     // find value ranges for both I and Q
     // both intervals should be same same size (for a perfect circle)
     for (SampleVector::iterator it = begin; it < end; it++)
     {
         if (it != begin)
         {
             if (it->real() < iMin) {
                 iMin = it->real();
             } else if (it->real() > iMax) {
                 iMax = it->real();
             }
             if (it->imag() < qMin) {
                 qMin = it->imag();
             } else if (it->imag() > qMax) {
                 qMax = it->imag();
             }
         }
         else
         {
             iMin = it->real();
             iMax = it->real();
             qMin = it->imag();
             qMax = it->imag();
         }
     }
     // sliding average (el cheapo again)
     m_iRange = (m_iRange * 15 + (iMax - iMin)) >> 4;
     m_qRange = (m_qRange * 15 + (qMax - qMin)) >> 4;
     // calculate imbalance on 32 bit full scale
     if(m_qRange != 0) {
         m_imbalance = ((uint)m_iRange << (32-SDR_RX_SAMP_SZ)) / (uint)m_qRange;
     }
     // correct imbalance and convert back to sample size
     for(SampleVector::iterator it = begin; it < end; it++) {
         it->m_imag = (it->m_imag * m_imbalance) >> (32-SDR_RX_SAMP_SZ);
     }
 }
initAcquisition()
bool DSPDeviceSourceEngine::initAcquisition ()
Initialize acquisition sequence.
Definition at line 83 of file dspdevicesourceengine.cpp.
References m_syncMessenger, SyncMessenger::sendWait(), and StReady.
Referenced by DeviceAPI::initDeviceEngine().
 {
     qDebug() << "DSPDeviceSourceEngine::initAcquisition";
     DSPAcquisitionInit cmd;
     return m_syncMessenger.sendWait(cmd) == StReady;
 }
iqCorrections()
void DSPDeviceSourceEngine::iqCorrections (SampleVector::iterator begin, SampleVector::iterator end, bool imbalanceCorrection) private
Definition at line 176 of file dspdevicesourceengine.cpp.
References Fixed< IntType, IntBits >::as_internal(), MovingAverageUtil< T, Total, N >::asDouble(), m_avgAmp, m_avgII, m_avgII2, m_avgIQ, m_avgPhi, m_avgQQ2, m_iBeta, m_qBeta, SDR_RX_SCALEF, and sqrt().
Referenced by work().
 {
     for(SampleVector::iterator it = begin; it < end; it++)
     {
         m_iBeta(it->real());
         m_qBeta(it->imag());
         if (imbalanceCorrection)
         {
 #if IMBALANCE_INT
             // acquisition
             int64_t xi = (it->m_real - (int32_t) m_iBeta) << 5;
             int64_t xq = (it->m_imag - (int32_t) m_qBeta) << 5;
             // phase imbalance
             m_avgII((xi*xi)>>28); // <I", I">
             m_avgIQ((xi*xq)>>28); // <I", Q">
             if ((int64_t) m_avgII != 0)
             {
                 int64_t phi = (((int64_t) m_avgIQ)<<28) / (int64_t) m_avgII;
                 m_avgPhi(phi);
             }
             int64_t corrPhi = (((int64_t) m_avgPhi) * xq) >> 28;  //(m_avgPhi.asDouble()/16777216.0) * ((double) xq);
             int64_t yi = xi - corrPhi;
             int64_t yq = xq;
             // amplitude I/Q imbalance
             m_avgII2((yi*yi)>>28); // <I, I>
             m_avgQQ2((yq*yq)>>28); // <Q, Q>
             if ((int64_t) m_avgQQ2 != 0)
             {
                 int64_t a = (((int64_t) m_avgII2)<<28) / (int64_t) m_avgQQ2;
                 Fixed<int64_t, 28> fA(Fixed<int64_t, 28>::internal(), a);
                 Fixed<int64_t, 28> sqrtA = sqrt((Fixed<int64_t, 28>) fA);
                 m_avgAmp(sqrtA.as_internal());
             }
             int64_t zq = (((int64_t) m_avgAmp) * yq) >> 28;
             it->m_real = yi >> 5;
             it->m_imag = zq >> 5;
 #else
             // DC correction and conversion
             float xi = (it->m_real - (int32_t) m_iBeta) / SDR_RX_SCALEF;
             float xq = (it->m_imag - (int32_t) m_qBeta) / SDR_RX_SCALEF;
             // phase imbalance
             m_avgII(xi*xi); // <I", I">
             m_avgIQ(xi*xq); // <I", Q">
             if (m_avgII.asDouble() != 0) {
                 m_avgPhi(m_avgIQ.asDouble()/m_avgII.asDouble());
             }
             float& yi = xi; // the in phase remains the reference
             float yq = xq - m_avgPhi.asDouble()*xi;
             // amplitude I/Q imbalance
             m_avgII2(yi*yi); // <I, I>
             m_avgQQ2(yq*yq); // <Q, Q>
             if (m_avgQQ2.asDouble() != 0) {
                 m_avgAmp(sqrt(m_avgII2.asDouble() / m_avgQQ2.asDouble()));
             }
             // final correction
             float& zi = yi; // the in phase remains the reference
             float zq = m_avgAmp.asDouble() * yq;
             // convert and store
             it->m_real = zi * SDR_RX_SCALEF;
             it->m_imag = zq * SDR_RX_SCALEF;
 #endif
         }
         else
         {
             // DC correction only
             it->m_real -= (int32_t) m_iBeta;
             it->m_imag -= (int32_t) m_qBeta;
         }
     }
 }
removeSink()
void DSPDeviceSourceEngine::removeSink (BasebandSampleSink * sink)
Remove a sample sink.
Definition at line 132 of file dspdevicesourceengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::removeAncillarySink(), and MainWindow::removeLastDevice().
 {
     qDebug() << "DSPDeviceSourceEngine::removeSink: " << sink->objectName().toStdString().c_str();
     DSPRemoveBasebandSampleSink cmd(sink);
     m_syncMessenger.sendWait(cmd);
 }
removeThreadedSink()
void DSPDeviceSourceEngine::removeThreadedSink (ThreadedBasebandSampleSink * sink)
Remove a sample sink that runs on its own thread.
Definition at line 146 of file dspdevicesourceengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::removeChannelSink().
 {
     qDebug() << "DSPDeviceSourceEngine::removeThreadedSink: " << sink->objectName().toStdString().c_str();
     DSPRemoveThreadedBasebandSampleSink cmd(sink);
     m_syncMessenger.sendWait(cmd);
 }
run()
void DSPDeviceSourceEngine::run () private
Definition at line 60 of file dspdevicesourceengine.cpp.
References m_state, and StIdle.
 {
     qDebug() << "DSPDeviceSourceEngine::run";
     m_state = StIdle;
     exec();
 }
setSource()
void DSPDeviceSourceEngine::setSource (DeviceSampleSource * source)
Set the sample source type.
Definition at line 112 of file dspdevicesourceengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::setSampleSource().
 {
     qDebug() << "DSPDeviceSourceEngine::setSource";
     DSPSetSource cmd(source);
     m_syncMessenger.sendWait(cmd);
 }
setSourceSequence()
void DSPDeviceSourceEngine::setSourceSequence (int sequence)
Set the sample source sequence in type.
Definition at line 119 of file dspdevicesourceengine.cpp.
References m_sampleSourceSequence.
 {
     qDebug("DSPDeviceSourceEngine::setSourceSequence: seq: %d", sequence);
     m_sampleSourceSequence = sequence;
 }
sourceDeviceDescription()
QString DSPDeviceSourceEngine::sourceDeviceDescription ()
Return the source device description.
Definition at line 168 of file dspdevicesourceengine.cpp.
References DSPGetSourceDeviceDescription::getDeviceDescription(), m_syncMessenger, and SyncMessenger::sendWait().
 {
     qDebug() << "DSPDeviceSourceEngine::sourceDeviceDescription";
     DSPGetSourceDeviceDescription cmd;
     m_syncMessenger.sendWait(cmd);
     return cmd.getDeviceDescription();
 }
start()
void DSPDeviceSourceEngine::start ()
This thread start.
Definition at line 67 of file dspdevicesourceengine.cpp.
Referenced by MainCore::addSourceDevice(), and MainWindow::addSourceDevice().
 {
     qDebug() << "DSPDeviceSourceEngine::start";
     QThread::start();
 }
startAcquisition()
bool DSPDeviceSourceEngine::startAcquisition ()
Start acquisition sequence.
Definition at line 91 of file dspdevicesourceengine.cpp.
References m_syncMessenger, SyncMessenger::sendWait(), and StRunning.
Referenced by DeviceAPI::startDeviceEngine().
 {
     qDebug() << "DSPDeviceSourceEngine::startAcquisition";
     DSPAcquisitionStart cmd;
     return m_syncMessenger.sendWait(cmd) == StRunning;
 }
state()
State DSPDeviceSourceEngine::state () const inline
Return DSP engine current state.
Definition at line 75 of file dspdevicesourceengine.h.
Referenced by Bladerf1Output::applySettings(), DeviceAPI::getDeviceEngineStateStr(), and DeviceAPI::state().
stop()
void DSPDeviceSourceEngine::stop ()
This thread stop.
Definition at line 73 of file dspdevicesourceengine.cpp.
References gotoIdle(), m_state, and StNotStarted.
Referenced by MainCore::removeLastDevice(), MainWindow::removeLastDevice(), and ~DSPDeviceSourceEngine().
 {
     qDebug() << "DSPDeviceSourceEngine::stop";
     gotoIdle();
     m_state = StNotStarted;
     QThread::exit();
 //  DSPExit cmd;
 //  m_syncMessenger.sendWait(cmd);
 }
stopAcquistion()
void DSPDeviceSourceEngine::stopAcquistion ()
Stop acquisition sequence.
Definition at line 99 of file dspdevicesourceengine.cpp.
References handleSynchronousMessages(), m_dcOffsetCorrection, m_iOffset, m_qOffset, m_syncMessenger, and SyncMessenger::storeMessage().
Referenced by MainCore::removeLastDevice(), MainWindow::removeLastDevice(), and DeviceAPI::stopDeviceEngine().
 {
     qDebug() << "DSPDeviceSourceEngine::stopAcquistion";
     DSPAcquisitionStop cmd;
     m_syncMessenger.storeMessage(cmd);
     handleSynchronousMessages();
     if(m_dcOffsetCorrection)
     {
         qDebug("DC offset:%f,%f", m_iOffset, m_qOffset);
     }
 }
work()
void DSPDeviceSourceEngine::work () private
transfer samples from source to sinks if in running state
Definition at line 326 of file dspdevicesourceengine.cpp.
References SampleSinkFifo::fill(), DeviceSampleSource::getSampleFifo(), iqCorrections(), m_basebandSampleSinks, m_dcOffsetCorrection, m_deviceSampleSource, m_inputMessageQueue, m_iqImbalanceCorrection, m_sampleRate, m_threadedBasebandSampleSinks, SampleSinkFifo::readBegin(), SampleSinkFifo::readCommit(), and MessageQueue::size().
Referenced by handleData().
 {
     SampleSinkFifo* sampleFifo = m_deviceSampleSource->getSampleFifo();
     std::size_t samplesDone = 0;
     bool positiveOnly = false;
     while ((sampleFifo->fill() > 0) && (m_inputMessageQueue.size() == 0) && (samplesDone < m_sampleRate))
     {
         SampleVector::iterator part1begin;
         SampleVector::iterator part1end;
         SampleVector::iterator part2begin;
         SampleVector::iterator part2end;
         std::size_t count = sampleFifo->readBegin(sampleFifo->fill(), &part1begin, &part1end, &part2begin, &part2end);
         // first part of FIFO data
         if (part1begin != part1end)
         {
             // correct stuff
             if (m_dcOffsetCorrection)
             {
                 iqCorrections(part1begin, part1end, m_iqImbalanceCorrection);
             }
 //          if (m_dcOffsetCorrection)
 //          {
 //              dcOffset(part1begin, part1end);
 //          }
 //
 //          if (m_iqImbalanceCorrection)
 //          {
 //              imbalance(part1begin, part1end);
 //          }
             // feed data to direct sinks
             for (BasebandSampleSinks::const_iterator it = m_basebandSampleSinks.begin(); it != m_basebandSampleSinks.end(); ++it)
             {
                 (*it)->feed(part1begin, part1end, positiveOnly);
             }
             // feed data to threaded sinks
             for (ThreadedBasebandSampleSinks::const_iterator it = m_threadedBasebandSampleSinks.begin(); it != m_threadedBasebandSampleSinks.end(); ++it)
             {
                 (*it)->feed(part1begin, part1end, positiveOnly);
             }
         }
         // second part of FIFO data (used when block wraps around)
         if(part2begin != part2end)
         {
             // correct stuff
             if (m_dcOffsetCorrection)
             {
                 iqCorrections(part2begin, part2end, m_iqImbalanceCorrection);
             }
 //            if (m_dcOffsetCorrection)
 //          {
 //              dcOffset(part2begin, part2end);
 //          }
 //
 //          if (m_iqImbalanceCorrection)
 //          {
 //              imbalance(part2begin, part2end);
 //          }
             // feed data to direct sinks
             for (BasebandSampleSinks::const_iterator it = m_basebandSampleSinks.begin(); it != m_basebandSampleSinks.end(); it++)
             {
                 (*it)->feed(part2begin, part2end, positiveOnly);
             }
             // feed data to threaded sinks
             for (ThreadedBasebandSampleSinks::const_iterator it = m_threadedBasebandSampleSinks.begin(); it != m_threadedBasebandSampleSinks.end(); ++it)
             {
                 (*it)->feed(part2begin, part2end, positiveOnly);
             }
         }
         // adjust FIFO pointers
         sampleFifo->readCommit((unsigned int) count);
         samplesDone += count;
     }
 }
Member Data Documentation
m_avgAmp
MovingAverageUtil<double, double, 128> DSPDeviceSourceEngine::m_avgAmp private
Definition at line 126 of file dspdevicesourceengine.h.
Referenced by handleInputMessages(), and iqCorrections().
m_avgII
MovingAverageUtil<float, double, 128> DSPDeviceSourceEngine::m_avgII private
Definition at line 121 of file dspdevicesourceengine.h.
Referenced by handleInputMessages(), and iqCorrections().
m_avgII2
MovingAverageUtil<float, double, 128> DSPDeviceSourceEngine::m_avgII2 private
Definition at line 123 of file dspdevicesourceengine.h.
Referenced by handleInputMessages(), and iqCorrections().
m_avgIQ
MovingAverageUtil<float, double, 128> DSPDeviceSourceEngine::m_avgIQ private
Definition at line 122 of file dspdevicesourceengine.h.
Referenced by handleInputMessages(), and iqCorrections().
m_avgPhi
MovingAverageUtil<double, double, 128> DSPDeviceSourceEngine::m_avgPhi private
Definition at line 125 of file dspdevicesourceengine.h.
Referenced by handleInputMessages(), and iqCorrections().
m_avgQQ2
MovingAverageUtil<float, double, 128> DSPDeviceSourceEngine::m_avgQQ2 private
Definition at line 124 of file dspdevicesourceengine.h.
Referenced by handleInputMessages(), and iqCorrections().
m_basebandSampleSinks
BasebandSampleSinks DSPDeviceSourceEngine::m_basebandSampleSinks private
sample sinks within main thread (usually spectrum, file output)
Definition at line 95 of file dspdevicesourceengine.h.
Referenced by gotoIdle(), gotoInit(), gotoRunning(), handleInputMessages(), handleSynchronousMessages(), and work().
m_centerFrequency
quint64 DSPDeviceSourceEngine::m_centerFrequency private
Definition at line 101 of file dspdevicesourceengine.h.
Referenced by gotoInit(), handleInputMessages(), and handleSynchronousMessages().
m_dcOffsetCorrection
bool DSPDeviceSourceEngine::m_dcOffsetCorrection private
Definition at line 103 of file dspdevicesourceengine.h.
Referenced by handleInputMessages(), stopAcquistion(), and work().
m_deviceDescription
QString DSPDeviceSourceEngine::m_deviceDescription private
Definition at line 89 of file dspdevicesourceengine.h.
Referenced by gotoError(), gotoIdle(), gotoInit(), gotoRunning(), and handleSynchronousMessages().
m_deviceSampleSource
DeviceSampleSource* DSPDeviceSourceEngine::m_deviceSampleSource private
Definition at line 91 of file dspdevicesourceengine.h.
Referenced by gotoIdle(), gotoInit(), gotoRunning(), handleInputMessages(), handleSetSource(), and work().
m_errorMessage
QString DSPDeviceSourceEngine::m_errorMessage private
Definition at line 88 of file dspdevicesourceengine.h.
Referenced by gotoError(), and handleSynchronousMessages().
m_iBeta
MovingAverageUtil<int32_t, int64_t, 1024> DSPDeviceSourceEngine::m_iBeta private
Definition at line 107 of file dspdevicesourceengine.h.
Referenced by dcOffset(), handleInputMessages(), and iqCorrections().
m_imbalance
qint32 DSPDeviceSourceEngine::m_imbalance private
Definition at line 131 of file dspdevicesourceengine.h.
Referenced by handleInputMessages(), and imbalance().
m_inputMessageQueue
MessageQueue DSPDeviceSourceEngine::m_inputMessageQueue private
Definition at line 83 of file dspdevicesourceengine.h.
Referenced by configureCorrections(), DSPDeviceSourceEngine(), gotoRunning(), handleInputMessages(), and work().
m_iOffset
double DSPDeviceSourceEngine::m_iOffset private
Definition at line 105 of file dspdevicesourceengine.h.
Referenced by gotoInit(), handleInputMessages(), and stopAcquistion().
m_iqImbalanceCorrection
bool DSPDeviceSourceEngine::m_iqImbalanceCorrection private
Definition at line 104 of file dspdevicesourceengine.h.
Referenced by handleInputMessages(), and work().
m_iRange
qint32 DSPDeviceSourceEngine::m_iRange private
Definition at line 129 of file dspdevicesourceengine.h.
Referenced by gotoInit(), handleInputMessages(), and imbalance().
m_qBeta
MovingAverageUtil<int32_t, int64_t, 1024> DSPDeviceSourceEngine::m_qBeta private
Definition at line 108 of file dspdevicesourceengine.h.
Referenced by dcOffset(), handleInputMessages(), and iqCorrections().
m_qOffset
double DSPDeviceSourceEngine::m_qOffset private
Definition at line 105 of file dspdevicesourceengine.h.
Referenced by gotoInit(), handleInputMessages(), and stopAcquistion().
m_qRange
qint32 DSPDeviceSourceEngine::m_qRange private
Definition at line 130 of file dspdevicesourceengine.h.
Referenced by gotoInit(), handleInputMessages(), and imbalance().
m_sampleRate
uint DSPDeviceSourceEngine::m_sampleRate private
Definition at line 100 of file dspdevicesourceengine.h.
Referenced by gotoIdle(), gotoInit(), handleInputMessages(), handleSynchronousMessages(), and work().
m_sampleSourceSequence
int DSPDeviceSourceEngine::m_sampleSourceSequence private
Definition at line 92 of file dspdevicesourceengine.h.
Referenced by setSourceSequence().
m_state
State DSPDeviceSourceEngine::m_state private
Definition at line 86 of file dspdevicesourceengine.h.
Referenced by gotoError(), gotoIdle(), gotoInit(), gotoRunning(), handleData(), handleSynchronousMessages(), run(), and stop().
m_syncMessenger
SyncMessenger DSPDeviceSourceEngine::m_syncMessenger private
Used to process messages synchronously with the thread.
Definition at line 84 of file dspdevicesourceengine.h.
Referenced by addSink(), addThreadedSink(), DSPDeviceSourceEngine(), errorMessage(), handleSynchronousMessages(), initAcquisition(), removeSink(), removeThreadedSink(), setSource(), sourceDeviceDescription(), startAcquisition(), and stopAcquistion().
m_threadedBasebandSampleSinks
ThreadedBasebandSampleSinks DSPDeviceSourceEngine::m_threadedBasebandSampleSinks private
sample sinks on their own threads (usually channels)
Definition at line 98 of file dspdevicesourceengine.h.
Referenced by gotoIdle(), gotoInit(), gotoRunning(), handleInputMessages(), handleSynchronousMessages(), and work().
m_uid
uint DSPDeviceSourceEngine::m_uid private
unique ID
Definition at line 81 of file dspdevicesourceengine.h.
The documentation for this class was generated from the following files:
sdrbase/dsp/dspdevicesourceengine.h
sdrbase/dsp/dspdevicesourceengine.cpp