SDRAngel: SWGSDRangel::SWGPresets Class Reference
SWGSDRangel::SWGPresets Class Reference
#include <SWGPresets.h>
Public Member Functions
SWGPresets ()
SWGPresets (QString *json)
virtual ~SWGPresets ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGPresets * fromJson (QString &jsonString) override
qint32 getNbGroups ()
void setNbGroups (qint32 nb_groups)
QList< SWGPresetGroup * > * getGroups ()
void setGroups (QList< SWGPresetGroup *> *groups)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 nb_groups
bool m_nb_groups_isSet
QList< SWGPresetGroup * > * groups
bool m_groups_isSet
Detailed Description
Definition at line 33 of file SWGPresets.h.
Constructor & Destructor Documentation
SWGPresets() [1/2]
SWGSDRangel::SWGPresets::SWGPresets ()
Definition at line 30 of file SWGPresets.cpp.
References groups, m_groups_isSet, m_nb_groups_isSet, and nb_groups.
{
     nb_groups = 0;
     m_nb_groups_isSet = false;
     groups = nullptr;
     m_groups_isSet = false;
 }
SWGPresets() [2/2]
SWGSDRangel::SWGPresets::SWGPresets (QString * json)
Definition at line 25 of file SWGPresets.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGPresets()
SWGSDRangel::SWGPresets::~SWGPresets () virtual
Definition at line 37 of file SWGPresets.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGPresets::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 79 of file SWGPresets.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::instancePresetsService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGPresets::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 90 of file SWGPresets.cpp.
References groups, m_nb_groups_isSet, nb_groups, and SWGSDRangel::toJsonArray().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_nb_groups_isSet){
         obj->insert("nbGroups", QJsonValue(nb_groups));
     }
     if(groups->size() > 0){
         toJsonArray((QList<void*>*)groups, obj, "groups", "SWGPresetGroup");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGPresets::cleanup ()
Definition at line 50 of file SWGPresets.cpp.
References groups.
Referenced by ~SWGPresets().
                     {
     if(groups != nullptr) {
         auto arr = groups;
         for(auto o: *arr) {
             delete o;
         }
         delete groups;
     }
 }
fromJson()
SWGPresets * SWGSDRangel::SWGPresets::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 62 of file SWGPresets.cpp.
References fromJsonObject().
Referenced by SWGPresets().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGPresets::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 71 of file SWGPresets.cpp.
References groups, nb_groups, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&nb_groups, pJson["nbGroups"], "qint32", "");
     ::SWGSDRangel::setValue(&groups, pJson["groups"], "QList", "SWGPresetGroup");
 }
getGroups()
QList< SWGPresetGroup * > * SWGSDRangel::SWGPresets::getGroups ()
Definition at line 113 of file SWGPresets.cpp.
References groups.
Referenced by WebAPIAdapterGUI::instancePresetsGet(), and WebAPIAdapterSrv::instancePresetsGet().
                       {
     return groups;
 }
getNbGroups()
qint32 SWGSDRangel::SWGPresets::getNbGroups ()
Definition at line 103 of file SWGPresets.cpp.
References nb_groups.
{
     return nb_groups;
 }
init()
void SWGSDRangel::SWGPresets::init ()
Definition at line 42 of file SWGPresets.cpp.
References groups, m_groups_isSet, m_nb_groups_isSet, and nb_groups.
Referenced by WebAPIAdapterGUI::instancePresetsGet(), WebAPIAdapterSrv::instancePresetsGet(), and SWGPresets().
                  {
     nb_groups = 0;
     m_nb_groups_isSet = false;
     groups = new QList<SWGPresetGroup*>();
     m_groups_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGPresets::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 124 of file SWGPresets.cpp.
References groups, and m_nb_groups_isSet.
                  {
     bool isObjectUpdated = false;
     do{
         if(m_nb_groups_isSet){ isObjectUpdated = true; break;}
         if(groups->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setGroups()
void SWGSDRangel::SWGPresets::setGroups (QList< SWGPresetGroup *> * groups)
Definition at line 117 of file SWGPresets.cpp.
References groups, and m_groups_isSet.
{
     this->groups = groups;
     this->m_groups_isSet = true;
 }
setNbGroups()
void SWGSDRangel::SWGPresets::setNbGroups (qint32 nb_groups)
Definition at line 107 of file SWGPresets.cpp.
References m_nb_groups_isSet, and nb_groups.
Referenced by WebAPIAdapterGUI::instancePresetsGet(), and WebAPIAdapterSrv::instancePresetsGet().
{
     this->nb_groups = nb_groups;
     this->m_nb_groups_isSet = true;
 }
Member Data Documentation
groups
QList<SWGPresetGroup*>* SWGSDRangel::SWGPresets::groups private
Definition at line 59 of file SWGPresets.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getGroups(), init(), isSet(), setGroups(), and SWGPresets().
m_groups_isSet
bool SWGSDRangel::SWGPresets::m_groups_isSet private
Definition at line 60 of file SWGPresets.h.
Referenced by init(), setGroups(), and SWGPresets().
m_nb_groups_isSet
bool SWGSDRangel::SWGPresets::m_nb_groups_isSet private
Definition at line 57 of file SWGPresets.h.
Referenced by asJsonObject(), init(), isSet(), setNbGroups(), and SWGPresets().
nb_groups
qint32 SWGSDRangel::SWGPresets::nb_groups private
Definition at line 56 of file SWGPresets.h.
Referenced by asJsonObject(), fromJsonObject(), getNbGroups(), init(), setNbGroups(), and SWGPresets().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGPresets.h
swagger/sdrangel/code/qt5/client/SWGPresets.cpp