SDRAngel: FileRecord Class Reference
FileRecord Class Reference
#include <filerecord.h>
Classes
struct Header
Public Member Functions
FileRecord ()
FileRecord (const QString &filename)
virtual ~FileRecord ()
quint64 getByteCount () const
void setFileName (const QString &filename)
void genUniqueFileName (uint deviceUID, int istream=-1)
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool positiveOnly)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &message)
Processing of a message. Returns true if message has actually been processed.
void startRecording ()
void stopRecording ()
bool isRecording () const
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Static Public Member Functions
static bool readHeader (std::ifstream &samplefile, Header &header)
returns true if CRC checksum is correct else false
static void writeHeader (std::ofstream &samplefile, Header &header)
Private Member Functions
void handleConfigure (const QString &fileName)
void writeHeader ()
Private Attributes
QString m_fileName
quint32 m_sampleRate
quint64 m_centerFrequency
bool m_recordOn
bool m_recordStart
std::ofstream m_sampleFile
quint64 m_byteCount
Additional Inherited Members
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 31 of file filerecord.h.
Constructor & Destructor Documentation
FileRecord() [1/2]
FileRecord::FileRecord ()
Definition at line 30 of file filerecord.cpp.
                        :
     BasebandSampleSink(),
     m_fileName("test.sdriq"),
     m_sampleRate(0),
     m_centerFrequency(0),
     m_recordOn(false),
     m_recordStart(false),
     m_byteCount(0)
 {
     setObjectName("FileSink");
 }
FileRecord() [2/2]
FileRecord::FileRecord (const QString & filename)
Definition at line 42 of file filerecord.cpp.
                                               :
     BasebandSampleSink(),
     m_fileName(filename),
     m_sampleRate(0),
     m_centerFrequency(0),
     m_recordOn(false),
     m_recordStart(false),
     m_byteCount(0)
 {
     setObjectName("FileRecord");
 }
~FileRecord()
FileRecord::~FileRecord () virtual
Definition at line 54 of file filerecord.cpp.
References stopRecording().
 {
     stopRecording();
 }
Member Function Documentation
feed()
void FileRecord::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool positiveOnly) virtual
Implements BasebandSampleSink.
Definition at line 76 of file filerecord.cpp.
References m_byteCount, m_recordOn, m_recordStart, m_sampleFile, and writeHeader().
 {
     (void) positiveOnly;
     // if no recording is active, send the samples to /dev/null
     if(!m_recordOn)
         return;
     if (begin < end) // if there is something to put out
     {
         if (m_recordStart)
         {
             writeHeader();
             m_recordStart = false;
         }
         m_sampleFile.write(reinterpret_cast<const char*>(&*(begin)), (end - begin)*sizeof(Sample));
         m_byteCount += end - begin;
     }
 }
genUniqueFileName()
void FileRecord::genUniqueFileName (uint deviceUID, int istream = -1)
Definition at line 67 of file filerecord.cpp.
References arg(), and setFileName().
Referenced by TestSourceInput::handleMessage(), AirspyInput::handleMessage(), PerseusInput::handleMessage(), RTLSDRInput::handleMessage(), AirspyHFInput::handleMessage(), PlutoSDRInput::handleMessage(), Bladerf1Input::handleMessage(), FCDProInput::handleMessage(), FCDProPlusInput::handleMessage(), HackRFInput::handleMessage(), KiwiSDRInput::handleMessage(), LocalInput::handleMessage(), SDRPlayInput::handleMessage(), BladeRF2Input::handleMessage(), SoapySDRInput::handleMessage(), LimeSDRInput::handleMessage(), and RemoteInput::handleMessage().
 {
     if (istream < 0) {
         setFileName(QString("rec%1_%2.sdriq").arg(deviceUID).arg(QDateTime::currentDateTimeUtc().toString("yyyy-MM-ddTHH_mm_ss_zzz")));
     } else {
         setFileName(QString("rec%1_%2_%3.sdriq").arg(deviceUID).arg(istream).arg(QDateTime::currentDateTimeUtc().toString("yyyy-MM-ddTHH_mm_ss_zzz")));
     }
 }
getByteCount()
quint64 FileRecord::getByteCount () const inline
Definition at line 50 of file filerecord.h.
 { return m_byteCount; }
handleConfigure()
void FileRecord::handleConfigure (const QString & fileName) private
Definition at line 145 of file filerecord.cpp.
References m_fileName, and stopRecording().
 {
     if (fileName != m_fileName)
     {
         stopRecording();
     }
     m_fileName = fileName;
 }
handleMessage()
bool FileRecord::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 128 of file filerecord.cpp.
References DSPSignalNotification::getCenterFrequency(), DSPSignalNotification::getSampleRate(), m_centerFrequency, m_sampleRate, and Message::match().
Referenced by TestSourceInput::applySettings(), Bladerf1Input::applySettings(), PerseusInput::applySettings(), AirspyInput::applySettings(), AirspyHFInput::applySettings(), RTLSDRInput::applySettings(), PlutoSDRInput::applySettings(), HackRFInput::applySettings(), FCDProPlusInput::applySettings(), KiwiSDRInput::applySettings(), FCDProInput::applySettings(), SDRPlayInput::applySettings(), BladeRF2Input::applySettings(), SoapySDRInput::applySettings(), LimeSDRInput::applySettings(), HackRFInput::handleMessage(), LocalInput::handleMessage(), BladeRF2Input::handleMessage(), and RemoteInput::handleMessage().
 {
     if (DSPSignalNotification::match(message))
     {
         DSPSignalNotification& notif = (DSPSignalNotification&) message;
         m_sampleRate = notif.getSampleRate();
         m_centerFrequency = notif.getCenterFrequency();
         qDebug() << "FileRecord::handleMessage: DSPSignalNotification: m_inputSampleRate: " << m_sampleRate
                 << " m_centerFrequency: " << m_centerFrequency;
         return true;
     }
     else
     {
         return false;
     }
 }
isRecording()
bool FileRecord::isRecording () const inline
Definition at line 61 of file filerecord.h.
 { return m_recordOn; }
readHeader()
bool FileRecord::readHeader (std::ifstream & samplefile, Header & header) static
returns true if CRC checksum is correct else false
Definition at line 168 of file filerecord.cpp.
References leansdr::crc32().
Referenced by FileInput::openFileStream(), and FileSource::openFileStream().
 {
     sampleFile.read((char *) &header, sizeof(Header));
     boost::crc_32_type crc32;
     crc32.process_bytes(&header, 28);
     return header.crc32 == crc32.checksum();
 }
setFileName()
void FileRecord::setFileName (const QString & filename)
Definition at line 59 of file filerecord.cpp.
References m_fileName, and m_recordOn.
Referenced by genUniqueFileName(), TestSourceInput::handleMessage(), AirspyInput::handleMessage(), PerseusInput::handleMessage(), RTLSDRInput::handleMessage(), AirspyHFInput::handleMessage(), PlutoSDRInput::handleMessage(), Bladerf1Input::handleMessage(), FCDProInput::handleMessage(), FCDProPlusInput::handleMessage(), HackRFInput::handleMessage(), KiwiSDRInput::handleMessage(), LocalInput::handleMessage(), SDRPlayInput::handleMessage(), BladeRF2Input::handleMessage(), SoapySDRInput::handleMessage(), LimeSDRInput::handleMessage(), and RemoteInput::handleMessage().
 {
     if (!m_recordOn)
     {
         m_fileName = filename;
     }
 }
start()
void FileRecord::start () virtual
Implements BasebandSampleSink.
Definition at line 96 of file filerecord.cpp.
 {
 }
startRecording()
void FileRecord::startRecording ()
Definition at line 105 of file filerecord.cpp.
References m_byteCount, m_fileName, m_recordOn, m_recordStart, and m_sampleFile.
Referenced by TestSourceInput::handleMessage(), AirspyInput::handleMessage(), PerseusInput::handleMessage(), RTLSDRInput::handleMessage(), AirspyHFInput::handleMessage(), PlutoSDRInput::handleMessage(), Bladerf1Input::handleMessage(), FCDProInput::handleMessage(), FCDProPlusInput::handleMessage(), HackRFInput::handleMessage(), KiwiSDRInput::handleMessage(), LocalInput::handleMessage(), SDRPlayInput::handleMessage(), BladeRF2Input::handleMessage(), SoapySDRInput::handleMessage(), XTRXInput::handleMessage(), LimeSDRInput::handleMessage(), and RemoteInput::handleMessage().
 {
     if (!m_sampleFile.is_open())
     {
         qDebug() << "FileRecord::startRecording";
         m_sampleFile.open(m_fileName.toStdString().c_str(), std::ios::binary);
         m_recordOn = true;
         m_recordStart = true;
         m_byteCount = 0;
     }
 }
stop()
void FileRecord::stop () virtual
Implements BasebandSampleSink.
Definition at line 100 of file filerecord.cpp.
References stopRecording().
 {
     stopRecording();
 }
stopRecording()
void FileRecord::stopRecording ()
Definition at line 117 of file filerecord.cpp.
References m_recordOn, m_recordStart, and m_sampleFile.
Referenced by handleConfigure(), TestSourceInput::handleMessage(), PerseusInput::handleMessage(), AirspyInput::handleMessage(), RTLSDRInput::handleMessage(), AirspyHFInput::handleMessage(), PlutoSDRInput::handleMessage(), Bladerf1Input::handleMessage(), FCDProInput::handleMessage(), FCDProPlusInput::handleMessage(), HackRFInput::handleMessage(), KiwiSDRInput::handleMessage(), LocalInput::handleMessage(), SDRPlayInput::handleMessage(), BladeRF2Input::handleMessage(), SoapySDRInput::handleMessage(), XTRXInput::handleMessage(), LimeSDRInput::handleMessage(), RemoteInput::handleMessage(), stop(), and ~FileRecord().
 {
     if (m_sampleFile.is_open())
     {
         qDebug() << "FileRecord::stopRecording";
         m_sampleFile.close();
         m_recordOn = false;
         m_recordStart = false;
     }
 }
writeHeader() [1/2]
void FileRecord::writeHeader (std::ofstream & samplefile, Header & header) static
Definition at line 176 of file filerecord.cpp.
References FileRecord::Header::crc32, and leansdr::crc32().
 {
     boost::crc_32_type crc32;
     crc32.process_bytes(&header, 28);
     header.crc32 = crc32.checksum();
     sampleFile.write((const char *) &header, sizeof(Header));
 }
writeHeader() [2/2]
void FileRecord::writeHeader () private
Definition at line 155 of file filerecord.cpp.
References FileRecord::Header::centerFrequency, FileRecord::Header::filler, m_centerFrequency, m_sampleFile, m_sampleRate, FileRecord::Header::sampleRate, FileRecord::Header::sampleSize, SDR_RX_SAMP_SZ, and FileRecord::Header::startTimeStamp.
Referenced by feed(), and FileSinkOutput::openFileStream().
 {
     Header header;
     header.sampleRate = m_sampleRate;
     header.centerFrequency = m_centerFrequency;
     std::time_t ts = time(0);
     header.startTimeStamp = ts;
     header.sampleSize = SDR_RX_SAMP_SZ;
     header.filler = 0;
     writeHeader(m_sampleFile, header);
 }
Member Data Documentation
m_byteCount
quint64 FileRecord::m_byteCount private
Definition at line 72 of file filerecord.h.
Referenced by feed(), and startRecording().
m_centerFrequency
quint64 FileRecord::m_centerFrequency private
Definition at line 68 of file filerecord.h.
Referenced by handleMessage(), and writeHeader().
m_fileName
QString FileRecord::m_fileName private
Definition at line 66 of file filerecord.h.
Referenced by handleConfigure(), setFileName(), and startRecording().
m_recordOn
bool FileRecord::m_recordOn private
Definition at line 69 of file filerecord.h.
Referenced by feed(), setFileName(), startRecording(), and stopRecording().
m_recordStart
bool FileRecord::m_recordStart private
Definition at line 70 of file filerecord.h.
Referenced by feed(), startRecording(), and stopRecording().
m_sampleFile
std::ofstream FileRecord::m_sampleFile private
Definition at line 71 of file filerecord.h.
Referenced by feed(), startRecording(), stopRecording(), and writeHeader().
m_sampleRate
quint32 FileRecord::m_sampleRate private
Definition at line 67 of file filerecord.h.
Referenced by handleMessage(), and writeHeader().
The documentation for this class was generated from the following files:
sdrbase/dsp/filerecord.h
sdrbase/dsp/filerecord.cpp