SDRAngel: qrtplib::RTPRandomRand48 Class Reference
qrtplib::RTPRandomRand48 Class Reference
#include <rtprandomrand48.h>
Public Member Functions
RTPRandomRand48 ()
RTPRandomRand48 (uint32_t seed)
~RTPRandomRand48 ()
uint8_t GetRandom8 ()
uint16_t GetRandom16 ()
uint32_t GetRandom32 ()
double GetRandomDouble ()
Public Member Functions inherited from qrtplib::RTPRandom
RTPRandom ()
virtual ~RTPRandom ()
uint32_t PickSeed ()
Private Member Functions
void SetSeed (uint32_t seed)
Private Attributes
uint64_t state
Additional Inherited Members
Static Public Member Functions inherited from qrtplib::RTPRandom
static RTPRandom * CreateDefaultRandomNumberGenerator ()
Detailed Description
A random number generator using the algorithm of the rand48 set of functions.
Definition at line 51 of file rtprandomrand48.h.
Constructor & Destructor Documentation
RTPRandomRand48() [1/2]
qrtplib::RTPRandomRand48::RTPRandomRand48 ()
Definition at line 39 of file rtprandomrand48.cpp.
References qrtplib::RTPRandom::PickSeed(), and SetSeed().
 {
     SetSeed(PickSeed());
 }
RTPRandomRand48() [2/2]
qrtplib::RTPRandomRand48::RTPRandomRand48 (uint32_t seed)
Definition at line 44 of file rtprandomrand48.cpp.
References SetSeed().
 {
     SetSeed(seed);
 }
~RTPRandomRand48()
qrtplib::RTPRandomRand48::~RTPRandomRand48 ()
Definition at line 49 of file rtprandomrand48.cpp.
 {
 }
Member Function Documentation
GetRandom16()
uint16_t qrtplib::RTPRandomRand48::GetRandom16 () virtual
Returns a random sixteen bit value.
Implements qrtplib::RTPRandom.
Definition at line 65 of file rtprandomrand48.cpp.
References GetRandom32().
 {
     uint32_t x = ((GetRandom32() >> 16) & 0xffff);
     return (uint16_t) x;
 }
GetRandom32()
uint32_t qrtplib::RTPRandomRand48::GetRandom32 () virtual
Returns a random thirty-two bit value.
Implements qrtplib::RTPRandom.
Definition at line 72 of file rtprandomrand48.cpp.
References state.
Referenced by GetRandom16(), and GetRandom8().
 {
     state = ((0x5DEECE66DULL * state) + 0xBULL) & 0x0000ffffffffffffULL;
     uint32_t x = (uint32_t) ((state >> 16) & 0xffffffffULL);
     qDebug("RTPRandomRand48::GetRandom32: %u", x);
     return x;
 }
GetRandom8()
uint8_t qrtplib::RTPRandomRand48::GetRandom8 () virtual
Returns a random eight bit value.
Implements qrtplib::RTPRandom.
Definition at line 58 of file rtprandomrand48.cpp.
References GetRandom32().
 {
     uint32_t x = ((GetRandom32() >> 24) & 0xff);
     return (uint8_t) x;
 }
GetRandomDouble()
double qrtplib::RTPRandomRand48::GetRandomDouble () virtual
Returns a random number between $0.0$ and $1.0$.
Implements qrtplib::RTPRandom.
Definition at line 81 of file rtprandomrand48.cpp.
References state.
 {
     state = ((0x5DEECE66DULL * state) + 0xBULL) & 0x0000ffffffffffffULL;
     int64_t x = (int64_t) state;
     double y = 3.552713678800500929355621337890625e-15 * (double) x;
     return y;
 }
SetSeed()
void qrtplib::RTPRandomRand48::SetSeed (uint32_t seed) private
Definition at line 53 of file rtprandomrand48.cpp.
References state.
Referenced by RTPRandomRand48().
 {
     state = ((uint64_t) seed) << 16 | 0x330EULL;
 }
Member Data Documentation
state
uint64_t qrtplib::RTPRandomRand48::state private
Definition at line 65 of file rtprandomrand48.h.
Referenced by GetRandom32(), GetRandomDouble(), and SetSeed().
The documentation for this class was generated from the following files:
qrtplib/rtprandomrand48.h
qrtplib/rtprandomrand48.cpp