SDRAngel: LimeSDROutput::MsgConfigureLimeSDR Class Reference
LimeSDROutput::MsgConfigureLimeSDR Class Reference
#include <limesdroutput.h>
Public Member Functions
const LimeSDROutputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureLimeSDR * create (const LimeSDROutputSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureLimeSDR (const LimeSDROutputSettings &settings, bool force)
Private Attributes
LimeSDROutputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 40 of file limesdroutput.h.
Constructor & Destructor Documentation
MsgConfigureLimeSDR()
LimeSDROutput::MsgConfigureLimeSDR::MsgConfigureLimeSDR (const LimeSDROutputSettings & settings, bool force) inline private
Definition at line 56 of file limesdroutput.h.
Referenced by create().
                                                                                :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureLimeSDR* LimeSDROutput::MsgConfigureLimeSDR::create (const LimeSDROutputSettings & settings, bool force) inline static
Definition at line 47 of file limesdroutput.h.
References MsgConfigureLimeSDR().
Referenced by LimeSDROutput::deserialize(), LimeSDROutput::setCenterFrequency(), LimeSDROutputGUI::updateHardware(), and LimeSDROutput::webapiSettingsPutPatch().
         {
             return new MsgConfigureLimeSDR(settings, force);
         }
getForce()
bool LimeSDROutput::MsgConfigureLimeSDR::getForce () const inline
Definition at line 45 of file limesdroutput.h.
References m_force.
Referenced by LimeSDROutput::handleMessage().
 { return m_force; }
getSettings()
const LimeSDROutputSettings& LimeSDROutput::MsgConfigureLimeSDR::getSettings () const inline
Definition at line 44 of file limesdroutput.h.
References m_settings.
Referenced by LimeSDROutputGUI::handleInputMessages(), LimeSDROutputGUI::handleMessage(), and LimeSDROutput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool LimeSDROutput::MsgConfigureLimeSDR::m_force private
Definition at line 54 of file limesdroutput.h.
Referenced by getForce().
m_settings
LimeSDROutputSettings LimeSDROutput::MsgConfigureLimeSDR::m_settings private
Definition at line 53 of file limesdroutput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesink/limesdroutput/limesdroutput.h