SDRAngel: MainWindow::MsgAddChannel Class Reference
MainWindow::MsgAddChannel Class Reference
Public Member Functions
int getDeviceSetIndex () const
int getChannelRegistrationIndex () const
bool isTx () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgAddChannel * create (int deviceSetIndex, int channelRegistrationIndex, bool tx)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgAddChannel (int deviceSetIndex, int channelRegistrationIndex, bool tx)
Private Attributes
int m_deviceSetIndex
int m_channelRegistrationIndex
bool m_tx
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 220 of file mainwindow.h.
Constructor & Destructor Documentation
MsgAddChannel()
MainWindow::MsgAddChannel::MsgAddChannel (int deviceSetIndex, int channelRegistrationIndex, bool tx) inline private
Definition at line 238 of file mainwindow.h.
                                                                                  :
             Message(),
             m_deviceSetIndex(deviceSetIndex),
             m_channelRegistrationIndex(channelRegistrationIndex),
             m_tx(tx)
         { }
Member Function Documentation
create()
static MsgAddChannel* MainWindow::MsgAddChannel::create (int deviceSetIndex, int channelRegistrationIndex, bool tx) inline static
Definition at line 228 of file mainwindow.h.
Referenced by WebAPIAdapterGUI::devicesetChannelPost().
         {
             return new MsgAddChannel(deviceSetIndex, channelRegistrationIndex, tx);
         }
getChannelRegistrationIndex()
int MainWindow::MsgAddChannel::getChannelRegistrationIndex () const inline
Definition at line 225 of file mainwindow.h.
Referenced by MainWindow::handleMessage().
 { return m_channelRegistrationIndex; }
getDeviceSetIndex()
int MainWindow::MsgAddChannel::getDeviceSetIndex () const inline
Definition at line 224 of file mainwindow.h.
Referenced by MainWindow::handleMessage().
 { return m_deviceSetIndex; }
isTx()
bool MainWindow::MsgAddChannel::isTx () const inline
Definition at line 226 of file mainwindow.h.
 { return m_tx; }
Member Data Documentation
m_channelRegistrationIndex
int MainWindow::MsgAddChannel::m_channelRegistrationIndex private
Definition at line 235 of file mainwindow.h.
m_deviceSetIndex
int MainWindow::MsgAddChannel::m_deviceSetIndex private
Definition at line 234 of file mainwindow.h.
m_tx
bool MainWindow::MsgAddChannel::m_tx private
Definition at line 236 of file mainwindow.h.
The documentation for this class was generated from the following file:
sdrgui/mainwindow.h