SDRAngel: PluginManager Class Reference
PluginManager Class Reference
#include <pluginmanager.h>
Inherits QObject.
Classes
struct Plugin
struct SamplingDevice
Public Types
typedef QList< Plugin > Plugins
Public Member Functions
PluginManager (QObject *parent=0)
~PluginManager ()
PluginAPI * getPluginAPI ()
void loadPlugins (const QString &pluginsSubDir)
void loadPluginsPart (const QString &pluginsSubDir)
void loadPluginsFinal ()
const Plugins & getPlugins () const
void registerRxChannel (const QString &channelIdURI, const QString &channelId, PluginInterface *plugin)
void registerSampleSource (const QString &sourceName, PluginInterface *plugin)
void registerTxChannel (const QString &channelIdURI, const QString &channelId, PluginInterface *plugin)
void registerSampleSink (const QString &sinkName, PluginInterface *plugin)
void registerSampleMIMO (const QString &mimoName, PluginInterface *plugin)
PluginAPI::SamplingDeviceRegistrations & getSourceDeviceRegistrations ()
PluginAPI::SamplingDeviceRegistrations & getSinkDeviceRegistrations ()
PluginAPI::SamplingDeviceRegistrations & getMIMODeviceRegistrations ()
PluginAPI::ChannelRegistrations * getRxChannelRegistrations ()
PluginAPI::ChannelRegistrations * getTxChannelRegistrations ()
void createRxChannelInstance (int channelPluginIndex, DeviceUISet *deviceUISet, DeviceAPI *deviceAPI)
void listRxChannels (QList< QString > &list)
void createTxChannelInstance (int channelPluginIndex, DeviceUISet *deviceUISet, DeviceAPI *deviceAPI)
void listTxChannels (QList< QString > &list)
Static Public Member Functions
static const QString & getFileInputDeviceId ()
static const QString & getFileSinkDeviceId ()
static const QString & getTestMIMODeviceId ()
Private Types
typedef QList< SamplingDevice > SamplingDevices
Private Member Functions
void loadPluginsDir (const QDir &dir)
Private Attributes
PluginAPI m_pluginAPI
Plugins m_plugins
PluginAPI::ChannelRegistrations m_rxChannelRegistrations
Channel plugins register here.
PluginAPI::SamplingDeviceRegistrations m_sampleSourceRegistrations
Input source plugins (one per device kind) register here.
PluginAPI::ChannelRegistrations m_txChannelRegistrations
Channel plugins register here.
PluginAPI::SamplingDeviceRegistrations m_sampleSinkRegistrations
Output sink plugins (one per device kind) register here.
PluginAPI::SamplingDeviceRegistrations m_sampleMIMORegistrations
MIMO sink plugins (one per device kind) register here.
Static Private Attributes
static const QString m_localInputHardwareID = "LocalInput"
Local input hardware ID.
static const QString m_localInputDeviceTypeID = "sdrangel.samplesource.localinput"
Local input plugin ID.
static const QString m_remoteInputHardwareID = "RemoteInput"
Remote input hardware ID.
static const QString m_remoteInputDeviceTypeID = "sdrangel.samplesource.remoteinput"
Remote input plugin ID.
static const QString m_fileInputHardwareID = "FileInput"
File input hardware ID.
static const QString m_fileInputDeviceTypeID = "sdrangel.samplesource.fileinput"
File input plugin ID.
static const QString m_localOutputHardwareID = "LocalOutput"
Local output hardware ID.
static const QString m_localOutputDeviceTypeID = "sdrangel.samplesource.localoutput"
Local output plugin ID.
static const QString m_remoteOutputHardwareID = "RemoteOutput"
Remote output hardware ID.
static const QString m_remoteOutputDeviceTypeID = "sdrangel.samplesink.remoteoutput"
Remote output plugin ID.
static const QString m_fileSinkHardwareID = "FileSink"
FileSink sink hardware ID.
static const QString m_fileSinkDeviceTypeID = "sdrangel.samplesink.filesink"
FileSink sink plugin ID.
static const QString m_testMIMOHardwareID = "TestMI"
Test MIMO hardware ID.
static const QString m_testMIMODeviceTypeID = "sdrangel.samplemimo.testmi"
Test MIMO plugin ID.
Detailed Description
Definition at line 38 of file pluginmanager.h.
Member Typedef Documentation
Plugins
typedef QList<Plugin> PluginManager::Plugins
Definition at line 53 of file pluginmanager.h.
SamplingDevices
typedef QList<SamplingDevice> PluginManager::SamplingDevices private
Definition at line 111 of file pluginmanager.h.
Constructor & Destructor Documentation
PluginManager()
PluginManager::PluginManager (QObject * parent = 0) explicit
Definition at line 50 of file pluginmanager.cpp.
                                             :
     QObject(parent),
     m_pluginAPI(this)
 {
 }
~PluginManager()
PluginManager::~PluginManager ()
Definition at line 56 of file pluginmanager.cpp.
 {
   //  freeAll();
 }
Member Function Documentation
createRxChannelInstance()
void PluginManager::createRxChannelInstance (int channelPluginIndex, DeviceUISet * deviceUISet, DeviceAPI * deviceAPI)
Definition at line 221 of file pluginmanager.cpp.
References PluginInterface::createRxChannelBS(), PluginInterface::createRxChannelGUI(), and m_rxChannelRegistrations.
Referenced by MainWindow::channelAddClicked().
 {
     if (channelPluginIndex < m_rxChannelRegistrations.size())
     {
         PluginInterface *pluginInterface = m_rxChannelRegistrations[channelPluginIndex].m_plugin;
         BasebandSampleSink *rxChannel = pluginInterface->createRxChannelBS(deviceAPI);
         pluginInterface->createRxChannelGUI(deviceUISet, rxChannel);
     }
 }
createTxChannelInstance()
void PluginManager::createTxChannelInstance (int channelPluginIndex, DeviceUISet * deviceUISet, DeviceAPI * deviceAPI)
Definition at line 231 of file pluginmanager.cpp.
References PluginInterface::createTxChannelBS(), PluginInterface::createTxChannelGUI(), and m_txChannelRegistrations.
Referenced by MainWindow::channelAddClicked().
 {
     if (channelPluginIndex < m_txChannelRegistrations.size())
     {
         PluginInterface *pluginInterface = m_txChannelRegistrations[channelPluginIndex].m_plugin;
         BasebandSampleSource *txChannel = pluginInterface->createTxChannelBS(deviceAPI);
         pluginInterface->createTxChannelGUI(deviceUISet, txChannel);
     }
 }
getFileInputDeviceId()
static const QString& PluginManager::getFileInputDeviceId () inline static
Definition at line 83 of file pluginmanager.h.
Referenced by DeviceEnumerator::getFileInputDeviceIndex().
 { return m_fileInputDeviceTypeID; }
getFileSinkDeviceId()
static const QString& PluginManager::getFileSinkDeviceId () inline static
Definition at line 84 of file pluginmanager.h.
Referenced by DeviceEnumerator::getFileSinkDeviceIndex().
 { return m_fileSinkDeviceTypeID; }
getMIMODeviceRegistrations()
PluginAPI::SamplingDeviceRegistrations& PluginManager::getMIMODeviceRegistrations () inline
Definition at line 73 of file pluginmanager.h.
Referenced by DeviceEnumerator::enumerateMIMODevices().
 { return m_sampleMIMORegistrations; }
getPluginAPI()
PluginAPI* PluginManager::getPluginAPI () inline
Definition at line 58 of file pluginmanager.h.
Referenced by MainCore::addChannel(), MainCore::loadPresetSettings(), and MainWindow::loadPresetSettings().
 { return &m_pluginAPI; }
getPlugins()
const Plugins& PluginManager::getPlugins () const inline
Definition at line 62 of file pluginmanager.h.
Referenced by PluginsDialog::PluginsDialog().
 { return m_plugins; }
getRxChannelRegistrations()
PluginAPI::ChannelRegistrations* PluginManager::getRxChannelRegistrations () inline
Definition at line 74 of file pluginmanager.h.
Referenced by WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterSrv::devicesetChannelPost(), PluginAPI::getRxChannelRegistrations(), WebAPIAdapterSrv::instanceChannels(), and WebAPIAdapterGUI::instanceChannels().
 { return &m_rxChannelRegistrations; }
getSinkDeviceRegistrations()
PluginAPI::SamplingDeviceRegistrations& PluginManager::getSinkDeviceRegistrations () inline
Definition at line 72 of file pluginmanager.h.
Referenced by DeviceEnumerator::enumerateTxDevices().
 { return m_sampleSinkRegistrations; }
getSourceDeviceRegistrations()
PluginAPI::SamplingDeviceRegistrations& PluginManager::getSourceDeviceRegistrations () inline
Definition at line 71 of file pluginmanager.h.
Referenced by DeviceEnumerator::enumerateRxDevices().
 { return m_sampleSourceRegistrations; }
getTestMIMODeviceId()
static const QString& PluginManager::getTestMIMODeviceId () inline static
Definition at line 85 of file pluginmanager.h.
Referenced by DeviceEnumerator::getTestMIMODeviceIndex().
 { return m_testMIMODeviceTypeID; }
getTxChannelRegistrations()
PluginAPI::ChannelRegistrations* PluginManager::getTxChannelRegistrations () inline
Definition at line 75 of file pluginmanager.h.
Referenced by WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterSrv::devicesetChannelPost(), PluginAPI::getTxChannelRegistrations(), WebAPIAdapterSrv::instanceChannels(), and WebAPIAdapterGUI::instanceChannels().
 { return &m_txChannelRegistrations; }
listRxChannels()
void PluginManager::listRxChannels (QList< QString > & list)
Definition at line 210 of file pluginmanager.cpp.
References PluginDescriptor::displayedName, and m_rxChannelRegistrations.
Referenced by MainWindow::addMIMODevice(), and MainWindow::addSourceDevice().
 {
     list.clear();
     for(PluginAPI::ChannelRegistrations::iterator it = m_rxChannelRegistrations.begin(); it != m_rxChannelRegistrations.end(); ++it)
     {
         const PluginDescriptor& pluginDesciptor = it->m_plugin->getPluginDescriptor();
         list.append(pluginDesciptor.displayedName);
     }
 }
listTxChannels()
void PluginManager::listTxChannels (QList< QString > & list)
Definition at line 199 of file pluginmanager.cpp.
References PluginDescriptor::displayedName, and m_txChannelRegistrations.
Referenced by MainWindow::addMIMODevice(), and MainWindow::addSinkDevice().
 {
     list.clear();
     for(PluginAPI::ChannelRegistrations::iterator it = m_txChannelRegistrations.begin(); it != m_txChannelRegistrations.end(); ++it)
     {
         const PluginDescriptor& pluginDescipror = it->m_plugin->getPluginDescriptor();
         list.append(pluginDescipror.displayedName);
     }
 }
loadPlugins()
void PluginManager::loadPlugins (const QString & pluginsSubDir)
Definition at line 61 of file pluginmanager.cpp.
References loadPluginsFinal(), and loadPluginsPart().
Referenced by MainCore::MainCore(), and MainWindow::MainWindow().
 {
     loadPluginsPart(pluginsSubDir);
     loadPluginsFinal();
 }
loadPluginsDir()
void PluginManager::loadPluginsDir (const QDir & dir) private
Definition at line 165 of file pluginmanager.cpp.
References m_plugins.
Referenced by loadPluginsPart().
 {
     QDir pluginsDir(dir);
     foreach (QString fileName, pluginsDir.entryList(QDir::Files))
     {
         if (QLibrary::isLibrary(fileName))
         {
             qDebug("PluginManager::loadPluginsDir: fileName: %s", qPrintable(fileName));
             QPluginLoader* pluginLoader = new QPluginLoader(pluginsDir.absoluteFilePath(fileName));
             if (!pluginLoader->load())
             {
                 qWarning("PluginManager::loadPluginsDir: %s", qPrintable(pluginLoader->errorString()));
                 delete pluginLoader;
                 continue;
             }
             PluginInterface* instance = qobject_cast<PluginInterface*>(pluginLoader->instance());
             if (instance == nullptr)
             {
                 qWarning("PluginManager::loadPluginsDir: Unable to get main instance of plugin: %s", qPrintable(fileName) );
                 delete pluginLoader;
                 continue;
             }
             delete(pluginLoader);
             qInfo("PluginManager::loadPluginsDir: loaded plugin %s", qPrintable(fileName));
             m_plugins.append(Plugin(fileName, instance));
        }
     }
 }
loadPluginsFinal()
void PluginManager::loadPluginsFinal ()
Definition at line 106 of file pluginmanager.cpp.
References DeviceEnumerator::enumerateMIMODevices(), DeviceEnumerator::enumerateRxDevices(), DeviceEnumerator::enumerateTxDevices(), DeviceEnumerator::instance(), m_pluginAPI, and m_plugins.
Referenced by loadPlugins().
 {
     qSort(m_plugins);
     for (Plugins::const_iterator it = m_plugins.begin(); it != m_plugins.end(); ++it)
     {
         it->pluginInterface->initPlugin(&m_pluginAPI);
     }
     DeviceEnumerator::instance()->enumerateRxDevices(this);
     DeviceEnumerator::instance()->enumerateTxDevices(this);
     DeviceEnumerator::instance()->enumerateMIMODevices(this);
 }
loadPluginsPart()
void PluginManager::loadPluginsPart (const QString & pluginsSubDir)
Definition at line 67 of file pluginmanager.cpp.
References loadPluginsDir().
Referenced by loadPlugins().
 {
     QString applicationDirPath = QCoreApplication::instance()->applicationDirPath();
     QStringList PluginsPath;
     // NOTE: not the best solution but for now this is
     // on make install [PREFIX]/bin and [PREFIX]/lib/sdrangel
     PluginsPath << applicationDirPath + "/../lib/sdrangel/" + pluginsSubDir;
     // on build
     PluginsPath << applicationDirPath + "/lib/" + pluginsSubDir;
 #ifdef __APPLE__
     // on SDRAngel.app
     PluginsPath << applicationDirPath + "/../Resources/lib/" + pluginsSubDir;
 #elif defined(_WIN32) || defined(WIN32)
     PluginsPath << applicationDirPath + "/" + pluginsSubDir;
 #endif
     // NOTE: exit on the first folder found
     bool found = false;
     foreach (QString dir, PluginsPath)
     {
         QDir d(dir);
         if (d.entryList(QDir::Files).count() == 0) {
             qDebug("PluginManager::loadPluginsPart folder %s is empty", qPrintable(dir));
             continue;
         }
         found = true;
         loadPluginsDir(d);
         break;
     }
     if (!found)
     {
         qCritical("No plugins found. Exit immediately.");
         exit(EXIT_FAILURE);
     }
 }
registerRxChannel()
void PluginManager::registerRxChannel (const QString & channelIdURI, const QString & channelId, PluginInterface * plugin)
Definition at line 120 of file pluginmanager.cpp.
References PluginDescriptor::displayedName, PluginInterface::getPluginDescriptor(), and m_rxChannelRegistrations.
Referenced by PluginAPI::registerRxChannel().
 {
     qDebug() << "PluginManager::registerRxChannel "
             << plugin->getPluginDescriptor().displayedName.toStdString().c_str()
             << " with channel name " << channelIdURI;
     m_rxChannelRegistrations.append(PluginAPI::ChannelRegistration(channelIdURI, channelId, plugin));
 }
registerSampleMIMO()
void PluginManager::registerSampleMIMO (const QString & mimoName, PluginInterface * plugin)
Definition at line 156 of file pluginmanager.cpp.
References PluginDescriptor::displayedName, PluginInterface::getPluginDescriptor(), and m_sampleMIMORegistrations.
Referenced by PluginAPI::registerSampleMIMO().
 {
     qDebug() << "PluginManager::registerSampleMIMO "
             << plugin->getPluginDescriptor().displayedName.toStdString().c_str()
             << " with MIMO name " << mimoName.toStdString().c_str();
     m_sampleMIMORegistrations.append(PluginAPI::SamplingDeviceRegistration(mimoName, plugin));
 }
registerSampleSink()
void PluginManager::registerSampleSink (const QString & sinkName, PluginInterface * plugin)
Definition at line 147 of file pluginmanager.cpp.
References PluginDescriptor::displayedName, PluginInterface::getPluginDescriptor(), and m_sampleSinkRegistrations.
Referenced by PluginAPI::registerSampleSink().
 {
     qDebug() << "PluginManager::registerSampleSink "
             << plugin->getPluginDescriptor().displayedName.toStdString().c_str()
             << " with sink name " << sinkName.toStdString().c_str();
     m_sampleSinkRegistrations.append(PluginAPI::SamplingDeviceRegistration(sinkName, plugin));
 }
registerSampleSource()
void PluginManager::registerSampleSource (const QString & sourceName, PluginInterface * plugin)
Definition at line 138 of file pluginmanager.cpp.
References PluginDescriptor::displayedName, PluginInterface::getPluginDescriptor(), and m_sampleSourceRegistrations.
Referenced by PluginAPI::registerSampleSource().
 {
     qDebug() << "PluginManager::registerSampleSource "
             << plugin->getPluginDescriptor().displayedName.toStdString().c_str()
             << " with source name " << sourceName.toStdString().c_str();
     m_sampleSourceRegistrations.append(PluginAPI::SamplingDeviceRegistration(sourceName, plugin));
 }
registerTxChannel()
void PluginManager::registerTxChannel (const QString & channelIdURI, const QString & channelId, PluginInterface * plugin)
Definition at line 129 of file pluginmanager.cpp.
References PluginDescriptor::displayedName, PluginInterface::getPluginDescriptor(), and m_txChannelRegistrations.
Referenced by PluginAPI::registerTxChannel().
 {
     qDebug() << "PluginManager::registerTxChannel "
             << plugin->getPluginDescriptor().displayedName.toStdString().c_str()
             << " with channel name " << channelIdURI;
     m_txChannelRegistrations.append(PluginAPI::ChannelRegistration(channelIdURI, channelId, plugin));
 }
Member Data Documentation
m_fileInputDeviceTypeID
const QString PluginManager::m_fileInputDeviceTypeID = "sdrangel.samplesource.fileinput" static private
File input plugin ID.
Definition at line 130 of file pluginmanager.h.
m_fileInputHardwareID
const QString PluginManager::m_fileInputHardwareID = "FileInput" static private
File input hardware ID.
Definition at line 129 of file pluginmanager.h.
m_fileSinkDeviceTypeID
const QString PluginManager::m_fileSinkDeviceTypeID = "sdrangel.samplesink.filesink" static private
FileSink sink plugin ID.
Definition at line 138 of file pluginmanager.h.
m_fileSinkHardwareID
const QString PluginManager::m_fileSinkHardwareID = "FileSink" static private
FileSink sink hardware ID.
Definition at line 137 of file pluginmanager.h.
m_localInputDeviceTypeID
const QString PluginManager::m_localInputDeviceTypeID = "sdrangel.samplesource.localinput" static private
Local input plugin ID.
Definition at line 126 of file pluginmanager.h.
m_localInputHardwareID
const QString PluginManager::m_localInputHardwareID = "LocalInput" static private
Local input hardware ID.
Definition at line 125 of file pluginmanager.h.
m_localOutputDeviceTypeID
const QString PluginManager::m_localOutputDeviceTypeID = "sdrangel.samplesource.localoutput" static private
Local output plugin ID.
Definition at line 134 of file pluginmanager.h.
m_localOutputHardwareID
const QString PluginManager::m_localOutputHardwareID = "LocalOutput" static private
Local output hardware ID.
Definition at line 133 of file pluginmanager.h.
m_pluginAPI
PluginAPI PluginManager::m_pluginAPI private
Definition at line 113 of file pluginmanager.h.
Referenced by loadPluginsFinal().
m_plugins
Plugins PluginManager::m_plugins private
Definition at line 114 of file pluginmanager.h.
Referenced by loadPluginsDir(), and loadPluginsFinal().
m_remoteInputDeviceTypeID
const QString PluginManager::m_remoteInputDeviceTypeID = "sdrangel.samplesource.remoteinput" static private
Remote input plugin ID.
Definition at line 128 of file pluginmanager.h.
m_remoteInputHardwareID
const QString PluginManager::m_remoteInputHardwareID = "RemoteInput" static private
Remote input hardware ID.
Definition at line 127 of file pluginmanager.h.
m_remoteOutputDeviceTypeID
const QString PluginManager::m_remoteOutputDeviceTypeID = "sdrangel.samplesink.remoteoutput" static private
Remote output plugin ID.
Definition at line 136 of file pluginmanager.h.
m_remoteOutputHardwareID
const QString PluginManager::m_remoteOutputHardwareID = "RemoteOutput" static private
Remote output hardware ID.
Definition at line 135 of file pluginmanager.h.
m_rxChannelRegistrations
PluginAPI::ChannelRegistrations PluginManager::m_rxChannelRegistrations private
Channel plugins register here.
Definition at line 116 of file pluginmanager.h.
Referenced by createRxChannelInstance(), listRxChannels(), and registerRxChannel().
m_sampleMIMORegistrations
PluginAPI::SamplingDeviceRegistrations PluginManager::m_sampleMIMORegistrations private
MIMO sink plugins (one per device kind) register here.
Definition at line 122 of file pluginmanager.h.
Referenced by registerSampleMIMO().
m_sampleSinkRegistrations
PluginAPI::SamplingDeviceRegistrations PluginManager::m_sampleSinkRegistrations private
Output sink plugins (one per device kind) register here.
Definition at line 120 of file pluginmanager.h.
Referenced by registerSampleSink().
m_sampleSourceRegistrations
PluginAPI::SamplingDeviceRegistrations PluginManager::m_sampleSourceRegistrations private
Input source plugins (one per device kind) register here.
Definition at line 117 of file pluginmanager.h.
Referenced by registerSampleSource().
m_testMIMODeviceTypeID
const QString PluginManager::m_testMIMODeviceTypeID = "sdrangel.samplemimo.testmi" static private
Test MIMO plugin ID.
Definition at line 142 of file pluginmanager.h.
m_testMIMOHardwareID
const QString PluginManager::m_testMIMOHardwareID = "TestMI" static private
Test MIMO hardware ID.
Definition at line 141 of file pluginmanager.h.
m_txChannelRegistrations
PluginAPI::ChannelRegistrations PluginManager::m_txChannelRegistrations private
Channel plugins register here.
Definition at line 119 of file pluginmanager.h.
Referenced by createTxChannelInstance(), listTxChannels(), and registerTxChannel().
The documentation for this class was generated from the following files:
sdrbase/plugin/pluginmanager.h
sdrbase/plugin/pluginmanager.cpp