SDRAngel: AirspyInput::MsgStartStop Class Reference
AirspyInput::MsgStartStop Class Reference
#include <airspyinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 80 of file airspyinput.h.
Constructor & Destructor Documentation
MsgStartStop()
AirspyInput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 93 of file airspyinput.h.
References AirspyInput::AirspyInput(), AirspyInput::deserialize(), AirspyInput::destroy(), AirspyInput::init(), AirspyInput::serialize(), AirspyInput::start(), AirspyInput::stop(), and AirspyInput::~AirspyInput().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* AirspyInput::MsgStartStop::create (bool startStop) inline static
Definition at line 86 of file airspyinput.h.
Referenced by AirspyGui::on_startStop_toggled(), and AirspyInput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool AirspyInput::MsgStartStop::getStartStop () const inline
Definition at line 84 of file airspyinput.h.
Referenced by AirspyGui::handleMessage(), and AirspyInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool AirspyInput::MsgStartStop::m_startStop protected
Definition at line 91 of file airspyinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/airspy/airspyinput.h