SDRAngel: LocalInputGui Class Reference
LocalInputGui Class Reference
#include <localinputgui.h>
Public Member Functions
LocalInputGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~LocalInputGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void displayTime ()
void sendSettings ()
void updateSampleRateAndFrequency ()
Private Attributes
Ui::LocalInputGui * ui
DeviceUISet * m_deviceUISet
LocalInputSettings m_settings
current settings
LocalInput * m_sampleSource
bool m_acquisition
int m_streamSampleRate
Sample rate of received stream.
quint64 m_streamCenterFrequency
Center frequency of received stream.
QTimer m_updateTimer
QTimer m_statusTimer
int m_lastEngineState
MessageQueue m_inputMessageQueue
uint64_t m_startingTimeStampms
int m_framesDecodingStatus
bool m_allBlocksReceived
float m_bufferLengthInSecs
int32_t m_bufferGauge
int m_minNbBlocks
int m_minNbOriginalBlocks
int m_maxNbRecovery
float m_avgNbBlocks
float m_avgNbOriginalBlocks
float m_avgNbRecovery
int m_nbOriginalBlocks
int m_nbFECBlocks
int m_sampleBits
int m_sampleBytes
int m_samplesCount
std::size_t m_tickCount
bool m_addressEdited
bool m_dataPortEdited
uint32_t m_countUnrecoverable
uint32_t m_countRecovered
QTime m_eventsTime
bool m_doApplySettings
bool m_forceSettings
double m_txDelay
QPalette m_paletteGreenText
QPalette m_paletteWhiteText
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Detailed Description
Definition at line 39 of file localinputgui.h.
Constructor & Destructor Documentation
LocalInputGui()
LocalInputGui::LocalInputGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 47 of file localinputgui.cpp.
References displaySettings(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_eventsTime, m_forceSettings, m_inputMessageQueue, m_networkManager, m_paletteGreenText, m_paletteWhiteText, m_sampleSource, m_startingTimeStampms, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), sendSettings(), LocalInput::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                                       :
     QWidget(parent),
     ui(new Ui::LocalInputGui),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_sampleSource(0),
     m_acquisition(false),
     m_streamSampleRate(0),
     m_streamCenterFrequency(0),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_framesDecodingStatus(0),
     m_bufferLengthInSecs(0.0),
     m_bufferGauge(-50),
     m_nbOriginalBlocks(128),
     m_nbFECBlocks(0),
     m_sampleBits(16), // assume 16 bits to start with
     m_sampleBytes(2),
     m_samplesCount(0),
     m_tickCount(0),
     m_addressEdited(false),
     m_dataPortEdited(false),
     m_countUnrecoverable(0),
     m_countRecovered(0),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_txDelay(0.0)
 {
     m_paletteGreenText.setColor(QPalette::WindowText, Qt::green);
     m_paletteWhiteText.setColor(QPalette::WindowText, Qt::white);
     m_startingTimeStampms = 0;
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, 0, 9999999U);
     ui->centerFrequencyHz->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequencyHz->setValueRange(3, 0, 999U);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     m_sampleSource = (LocalInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     m_eventsTime.start();
     m_forceSettings = true;
     sendSettings();
 }
~LocalInputGui()
LocalInputGui::~LocalInputGui () virtual
Definition at line 109 of file localinputgui.cpp.
References m_networkManager, and ui.
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void LocalInputGui::blockApplySettings (bool block) private
Definition at line 116 of file localinputgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), handleMessage(), and updateSampleRateAndFrequency().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool LocalInputGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 149 of file localinputgui.cpp.
References LocalInputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, and sendSettings().
 {
     qDebug("LocalInputGui::deserialize");
     if (m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         return false;
     }
 }
destroy()
void LocalInputGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 121 of file localinputgui.cpp.
 {
     delete this;
 }
displaySettings()
void LocalInputGui::displaySettings () private
Definition at line 259 of file localinputgui.cpp.
References arg(), blockApplySettings(), LocalInputSettings::m_dcBlock, LocalInputSettings::m_iqCorrection, m_settings, m_streamCenterFrequency, m_streamSampleRate, and ui.
Referenced by deserialize(), handleMessage(), LocalInputGui(), and resetToDefaults().
 {
     blockApplySettings(true);
     ui->centerFrequency->setValue(m_streamCenterFrequency / 1000);
     ui->centerFrequencyHz->setValue(m_streamCenterFrequency % 1000);
     ui->deviceRateText->setText(tr("%1k").arg(m_streamSampleRate / 1000.0));
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqCorrection);
     blockApplySettings(false);
 }
displayTime()
void LocalInputGui::displayTime () private
getCenterFrequency()
qint64 LocalInputGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 167 of file localinputgui.cpp.
References m_streamCenterFrequency.
 {
     return m_streamCenterFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* LocalInputGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 55 of file localinputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString LocalInputGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 131 of file localinputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void LocalInputGui::handleInputMessages () private slot
Definition at line 212 of file localinputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), DeviceSampleSource::getInputMessageQueue(), DSPSignalNotification::getSampleRate(), handleMessage(), m_inputMessageQueue, m_sampleSource, m_streamCenterFrequency, m_streamSampleRate, Message::match(), MessageQueue::pop(), MessageQueue::push(), and updateSampleRateAndFrequency().
Referenced by LocalInputGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         //qDebug("LocalInputGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             if (notif->getSampleRate() != m_streamSampleRate) {
                 m_streamSampleRate = notif->getSampleRate();
             }
             m_streamCenterFrequency = notif->getCenterFrequency();
             qDebug("LocalInputGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             DSPSignalNotification *fwd = new DSPSignalNotification(*notif);
             m_sampleSource->getInputMessageQueue()->push(fwd);
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool LocalInputGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 177 of file localinputgui.cpp.
References blockApplySettings(), displaySettings(), LocalInput::MsgReportSampleRateAndFrequency::getCenterFrequency(), LocalInput::MsgReportSampleRateAndFrequency::getSampleRate(), LocalInput::MsgConfigureLocalInput::getSettings(), LocalInput::MsgStartStop::getStartStop(), m_settings, m_streamCenterFrequency, m_streamSampleRate, Message::match(), ui, and updateSampleRateAndFrequency().
Referenced by handleInputMessages().
 {
     if (LocalInput::MsgConfigureLocalInput::match(message))
     {
         const LocalInput::MsgConfigureLocalInput& cfg = (LocalInput::MsgConfigureLocalInput&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (LocalInput::MsgStartStop::match(message))
     {
         LocalInput::MsgStartStop& notif = (LocalInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else if (LocalInput::MsgReportSampleRateAndFrequency::match(message))
     {
         LocalInput::MsgReportSampleRateAndFrequency& notif = (LocalInput::MsgReportSampleRateAndFrequency&) message;
         m_streamSampleRate = notif.getSampleRate();
         m_streamCenterFrequency = notif.getCenterFrequency();
         updateSampleRateAndFrequency();
         return true;
     }
     else
     {
         return false;
     }
 }
on_dcOffset_toggled
void LocalInputGui::on_dcOffset_toggled (bool checked) private slot
Definition at line 279 of file localinputgui.cpp.
References LocalInputSettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_iqImbalance_toggled
void LocalInputGui::on_iqImbalance_toggled (bool checked) private slot
Definition at line 285 of file localinputgui.cpp.
References LocalInputSettings::m_iqCorrection, m_settings, and sendSettings().
 {
     m_settings.m_iqCorrection = checked;
     sendSettings();
 }
on_record_toggled
void LocalInputGui::on_record_toggled (bool checked) private slot
Definition at line 300 of file localinputgui.cpp.
References LocalInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     LocalInput::MsgFileRecord* message = LocalInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_startStop_toggled
void LocalInputGui::on_startStop_toggled (bool checked) private slot
Definition at line 291 of file localinputgui.cpp.
References LocalInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         LocalInput::MsgStartStop *message = LocalInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
openDeviceSettingsDialog
void LocalInputGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 354 of file localinputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), LocalInputSettings::m_reverseAPIAddress, LocalInputSettings::m_reverseAPIDeviceIndex, LocalInputSettings::m_reverseAPIPort, m_settings, LocalInputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by LocalInputGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void LocalInputGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 136 of file localinputgui.cpp.
References displaySettings(), m_forceSettings, m_settings, LocalInputSettings::resetToDefaults(), and sendSettings().
 {
     m_settings.resetToDefaults();
     displaySettings();
     m_forceSettings = true;
     sendSettings();
 }
sendSettings()
void LocalInputGui::sendSettings () private
Definition at line 273 of file localinputgui.cpp.
References m_updateTimer.
Referenced by deserialize(), LocalInputGui(), on_dcOffset_toggled(), on_iqImbalance_toggled(), openDeviceSettingsDialog(), and resetToDefaults().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray LocalInputGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 144 of file localinputgui.cpp.
References m_settings, and LocalInputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void LocalInputGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 172 of file localinputgui.cpp.
 {
     (void) centerFrequency;
 }
setName()
void LocalInputGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 126 of file localinputgui.cpp.
 {
     setObjectName(name);
 }
updateHardware
void LocalInputGui::updateHardware () private slot
Definition at line 312 of file localinputgui.cpp.
References LocalInput::MsgConfigureLocalInput::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by LocalInputGui().
 {
     if (m_doApplySettings)
     {
         qDebug() << "LocalInputGui::updateHardware";
         LocalInput::MsgConfigureLocalInput* message =
                 LocalInput::MsgConfigureLocalInput::create(m_settings, m_forceSettings);
         m_sampleSource->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void LocalInputGui::updateSampleRateAndFrequency () private
Definition at line 248 of file localinputgui.cpp.
References arg(), blockApplySettings(), DeviceUISet::getSpectrum(), m_deviceUISet, m_streamCenterFrequency, m_streamSampleRate, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages(), and handleMessage().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_streamSampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_streamCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg((float)m_streamSampleRate / 1000));
     blockApplySettings(true);
     ui->centerFrequency->setValue(m_streamCenterFrequency / 1000);
     ui->centerFrequencyHz->setValue(m_streamCenterFrequency % 1000);
     blockApplySettings(false);
 }
updateStatus
void LocalInputGui::updateStatus () private slot
Definition at line 325 of file localinputgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by LocalInputGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_acquisition
bool LocalInputGui::m_acquisition private
Definition at line 64 of file localinputgui.h.
m_addressEdited
bool LocalInputGui::m_addressEdited private
Definition at line 93 of file localinputgui.h.
m_allBlocksReceived
bool LocalInputGui::m_allBlocksReceived private
Definition at line 76 of file localinputgui.h.
m_avgNbBlocks
float LocalInputGui::m_avgNbBlocks private
Definition at line 82 of file localinputgui.h.
m_avgNbOriginalBlocks
float LocalInputGui::m_avgNbOriginalBlocks private
Definition at line 83 of file localinputgui.h.
m_avgNbRecovery
float LocalInputGui::m_avgNbRecovery private
Definition at line 84 of file localinputgui.h.
m_bufferGauge
int32_t LocalInputGui::m_bufferGauge private
Definition at line 78 of file localinputgui.h.
m_bufferLengthInSecs
float LocalInputGui::m_bufferLengthInSecs private
Definition at line 77 of file localinputgui.h.
m_countRecovered
uint32_t LocalInputGui::m_countRecovered private
Definition at line 97 of file localinputgui.h.
m_countUnrecoverable
uint32_t LocalInputGui::m_countUnrecoverable private
Definition at line 96 of file localinputgui.h.
m_dataPortEdited
bool LocalInputGui::m_dataPortEdited private
Definition at line 94 of file localinputgui.h.
m_deviceUISet
DeviceUISet* LocalInputGui::m_deviceUISet private
Definition at line 61 of file localinputgui.h.
Referenced by LocalInputGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool LocalInputGui::m_doApplySettings private
Definition at line 100 of file localinputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_eventsTime
QTime LocalInputGui::m_eventsTime private
Definition at line 98 of file localinputgui.h.
Referenced by LocalInputGui().
m_forceSettings
bool LocalInputGui::m_forceSettings private
Definition at line 101 of file localinputgui.h.
Referenced by deserialize(), LocalInputGui(), resetToDefaults(), and updateHardware().
m_framesDecodingStatus
int LocalInputGui::m_framesDecodingStatus private
Definition at line 75 of file localinputgui.h.
m_inputMessageQueue
MessageQueue LocalInputGui::m_inputMessageQueue private
Definition at line 70 of file localinputgui.h.
Referenced by handleInputMessages(), and LocalInputGui().
m_lastEngineState
int LocalInputGui::m_lastEngineState private
Definition at line 69 of file localinputgui.h.
Referenced by updateStatus().
m_maxNbRecovery
int LocalInputGui::m_maxNbRecovery private
Definition at line 81 of file localinputgui.h.
m_minNbBlocks
int LocalInputGui::m_minNbBlocks private
Definition at line 79 of file localinputgui.h.
m_minNbOriginalBlocks
int LocalInputGui::m_minNbOriginalBlocks private
Definition at line 80 of file localinputgui.h.
m_nbFECBlocks
int LocalInputGui::m_nbFECBlocks private
Definition at line 86 of file localinputgui.h.
m_nbOriginalBlocks
int LocalInputGui::m_nbOriginalBlocks private
Definition at line 85 of file localinputgui.h.
m_networkManager
QNetworkAccessManager* LocalInputGui::m_networkManager private
Definition at line 107 of file localinputgui.h.
Referenced by LocalInputGui(), and ~LocalInputGui().
m_networkRequest
QNetworkRequest LocalInputGui::m_networkRequest private
Definition at line 108 of file localinputgui.h.
m_paletteGreenText
QPalette LocalInputGui::m_paletteGreenText private
Definition at line 104 of file localinputgui.h.
Referenced by LocalInputGui().
m_paletteWhiteText
QPalette LocalInputGui::m_paletteWhiteText private
Definition at line 105 of file localinputgui.h.
Referenced by LocalInputGui().
m_sampleBits
int LocalInputGui::m_sampleBits private
Definition at line 87 of file localinputgui.h.
m_sampleBytes
int LocalInputGui::m_sampleBytes private
Definition at line 88 of file localinputgui.h.
m_samplesCount
int LocalInputGui::m_samplesCount private
Definition at line 90 of file localinputgui.h.
m_sampleSource
LocalInput* LocalInputGui::m_sampleSource private
Definition at line 63 of file localinputgui.h.
Referenced by handleInputMessages(), LocalInputGui(), on_record_toggled(), on_startStop_toggled(), and updateHardware().
m_settings
LocalInputSettings LocalInputGui::m_settings private
current settings
Definition at line 62 of file localinputgui.h.
Referenced by deserialize(), displaySettings(), handleMessage(), on_dcOffset_toggled(), on_iqImbalance_toggled(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), and updateHardware().
m_startingTimeStampms
uint64_t LocalInputGui::m_startingTimeStampms private
Definition at line 74 of file localinputgui.h.
Referenced by LocalInputGui().
m_statusTimer
QTimer LocalInputGui::m_statusTimer private
Definition at line 68 of file localinputgui.h.
Referenced by LocalInputGui().
m_streamCenterFrequency
quint64 LocalInputGui::m_streamCenterFrequency private
Center frequency of received stream.
Definition at line 66 of file localinputgui.h.
Referenced by displaySettings(), getCenterFrequency(), handleInputMessages(), handleMessage(), and updateSampleRateAndFrequency().
m_streamSampleRate
int LocalInputGui::m_streamSampleRate private
Sample rate of received stream.
Definition at line 65 of file localinputgui.h.
Referenced by displaySettings(), handleInputMessages(), handleMessage(), and updateSampleRateAndFrequency().
m_tickCount
std::size_t LocalInputGui::m_tickCount private
Definition at line 91 of file localinputgui.h.
m_txDelay
double LocalInputGui::m_txDelay private
Definition at line 102 of file localinputgui.h.
m_updateTimer
QTimer LocalInputGui::m_updateTimer private
Definition at line 67 of file localinputgui.h.
Referenced by LocalInputGui(), sendSettings(), and updateHardware().
ui
Ui::LocalInputGui* LocalInputGui::ui private
Definition at line 59 of file localinputgui.h.
Referenced by displaySettings(), handleMessage(), LocalInputGui(), on_record_toggled(), updateSampleRateAndFrequency(), updateStatus(), and ~LocalInputGui().
The documentation for this class was generated from the following files:
plugins/samplesource/localinput/localinputgui.h
plugins/samplesource/localinput/localinputgui.cpp