SDRAngel: RemoteOutputThread Class Reference
RemoteOutputThread Class Reference
#include <remoteoutputthread.h>
Inherits QThread.
Public Member Functions
RemoteOutputThread (SampleSourceFifo *sampleFifo, QObject *parent=0)
~RemoteOutputThread ()
void startWork ()
void stopWork ()
void setSamplerate (int samplerate)
void setNbBlocksFEC (uint32_t nbBlocksFEC)
void setTxDelay (float txDelay)
void setDataAddress (const QString &address, uint16_t port)
bool isRunning () const
uint32_t getSamplesCount (uint64_t &ts_usecs) const
void setSamplesCount (int samplesCount)
void setChunkCorrection (int chunkCorrection)
void connectTimer (const QTimer &timer)
Private Slots
void tick ()
Private Member Functions
void run ()
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
volatile bool m_running
int m_samplesChunkSize
SampleSourceFifo * m_sampleFifo
uint32_t m_samplesCount
int m_chunkCorrection
int m_samplerate
int m_throttlems
int m_maxThrottlems
QElapsedTimer m_elapsedTimer
bool m_throttleToggle
UDPSinkFEC m_udpSinkFEC
Detailed Description
Definition at line 42 of file remoteoutputthread.h.
Constructor & Destructor Documentation
RemoteOutputThread()
RemoteOutputThread::RemoteOutputThread (SampleSourceFifo * sampleFifo, QObject * parent = 0)
Definition at line 28 of file remoteoutputthread.cpp.
                                                                                     :
     QThread(parent),
     m_running(false),
     m_samplesChunkSize(0),
     m_sampleFifo(sampleFifo),
     m_samplesCount(0),
     m_chunkCorrection(0),
     m_samplerate(0),
     m_throttlems(REMOTEOUTPUT_THROTTLE_MS),
     m_maxThrottlems(50),
     m_throttleToggle(false)
 {
 }
~RemoteOutputThread()
RemoteOutputThread::~RemoteOutputThread ()
Definition at line 42 of file remoteoutputthread.cpp.
References m_running, and stopWork().
 {
     if (m_running) {
         stopWork();
     }
 }
Member Function Documentation
connectTimer()
void RemoteOutputThread::connectTimer (const QTimer & timer)
Definition at line 114 of file remoteoutputthread.cpp.
References tick().
Referenced by setChunkCorrection(), and RemoteOutput::start().
 {
     qDebug() << "RemoteOutputThread::connectTimer";
     connect(&timer, SIGNAL(timeout()), this, SLOT(tick()));
 }
getSamplesCount()
uint32_t RemoteOutputThread::getSamplesCount (uint64_t & ts_usecs) const
Definition at line 144 of file remoteoutputthread.cpp.
References m_samplesCount, and TimeUtil::nowus().
Referenced by RemoteOutput::analyzeApiReply(), isRunning(), and RemoteOutput::webapiFormatDeviceReport().
 {
     ts_usecs = TimeUtil::nowus();
     return m_samplesCount;
 }
isRunning()
bool RemoteOutputThread::isRunning () const inline
Definition at line 57 of file remoteoutputthread.h.
References getSamplesCount(), and m_running.
 { return m_running; }
run()
void RemoteOutputThread::run () private
Definition at line 101 of file remoteoutputthread.cpp.
References m_running, and m_startWaiter.
 {
     m_running = true;
     m_startWaiter.wakeAll();
     while(m_running) // actual work is in the tick() function
     {
         sleep(1);
     }
     m_running = false;
 }
setChunkCorrection()
void RemoteOutputThread::setChunkCorrection (int chunkCorrection) inline
Definition at line 61 of file remoteoutputthread.h.
References connectTimer(), and m_chunkCorrection.
Referenced by RemoteOutput::handleMessage().
 { m_chunkCorrection = chunkCorrection; }
setDataAddress()
void RemoteOutputThread::setDataAddress (const QString & address, uint16_t port) inline
Definition at line 55 of file remoteoutputthread.h.
References m_udpSinkFEC, and UDPSinkFEC::setRemoteAddress().
Referenced by RemoteOutput::applySettings(), and RemoteOutput::start().
 { m_udpSinkFEC.setRemoteAddress(address, port); }
setNbBlocksFEC()
void RemoteOutputThread::setNbBlocksFEC (uint32_t nbBlocksFEC) inline
Definition at line 53 of file remoteoutputthread.h.
References m_udpSinkFEC, and UDPSinkFEC::setNbBlocksFEC().
Referenced by RemoteOutput::applySettings(), and RemoteOutput::start().
 { m_udpSinkFEC.setNbBlocksFEC(nbBlocksFEC); };
setSamplerate()
void RemoteOutputThread::setSamplerate (int samplerate)
Definition at line 70 of file remoteoutputthread.cpp.
References m_running, m_sampleFifo, m_samplerate, m_samplesChunkSize, m_throttlems, m_udpSinkFEC, SampleSourceFifo::resize(), UDPSinkFEC::setSampleRate(), startWork(), and stopWork().
Referenced by RemoteOutput::applySettings(), and RemoteOutput::start().
 {
     if (samplerate != m_samplerate)
     {
         qDebug() << "RemoteOutputThread::setSamplerate:"
                 << " new:" << samplerate
                 << " old:" << m_samplerate;
         bool wasRunning = false;
         if (m_running)
         {
             stopWork();
             wasRunning = true;
         }
         // resize sample FIFO
         if (m_sampleFifo) {
             m_sampleFifo->resize(samplerate); // 1s buffer
         }
         m_samplerate = samplerate;
         m_samplesChunkSize = (m_samplerate * m_throttlems) / 1000;
         m_udpSinkFEC.setSampleRate(m_samplerate);
         if (wasRunning) {
             startWork();
         }
     }
 }
setSamplesCount()
void RemoteOutputThread::setSamplesCount (int samplesCount) inline
Definition at line 60 of file remoteoutputthread.h.
References m_samplesCount.
 { m_samplesCount = samplesCount; }
setTxDelay()
void RemoteOutputThread::setTxDelay (float txDelay) inline
Definition at line 54 of file remoteoutputthread.h.
References m_udpSinkFEC, and UDPSinkFEC::setTxDelay().
Referenced by RemoteOutput::applySettings(), and RemoteOutput::start().
 { m_udpSinkFEC.setTxDelay(txDelay); };
startWork()
void RemoteOutputThread::startWork ()
Definition at line 49 of file remoteoutputthread.cpp.
References m_elapsedTimer, m_maxThrottlems, m_running, m_startWaiter, m_startWaitMutex, m_udpSinkFEC, and UDPSinkFEC::start().
Referenced by RemoteOutput::handleMessage(), setSamplerate(), and RemoteOutput::start().
 {
     qDebug() << "RemoteOutputThread::startWork: ";
     m_udpSinkFEC.start();
     m_maxThrottlems = 0;
     m_startWaitMutex.lock();
     m_elapsedTimer.start();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void RemoteOutputThread::stopWork ()
Definition at line 62 of file remoteoutputthread.cpp.
References m_running, m_udpSinkFEC, and UDPSinkFEC::stop().
Referenced by RemoteOutput::handleMessage(), setSamplerate(), RemoteOutput::stop(), and ~RemoteOutputThread().
 {
     qDebug() << "RemoteOutputThread::stopWork";
     m_running = false;
     wait();
     m_udpSinkFEC.stop();
 }
tick
void RemoteOutputThread::tick () private slot
Definition at line 120 of file remoteoutputthread.cpp.
References m_chunkCorrection, m_elapsedTimer, m_running, m_sampleFifo, m_samplerate, m_samplesChunkSize, m_samplesCount, m_throttlems, m_throttleToggle, m_udpSinkFEC, SampleSourceFifo::readAdvance(), and UDPSinkFEC::write().
Referenced by connectTimer().
 {
     if (m_running)
     {
         qint64 throttlems = m_elapsedTimer.restart();
         if (throttlems != m_throttlems)
         {
             m_throttlems = throttlems;
             m_samplesChunkSize = (m_samplerate * (m_throttlems+(m_throttleToggle ? 1 : 0))) / 1000;
             m_samplesChunkSize = m_samplesChunkSize + m_chunkCorrection > 0 ? m_samplesChunkSize + m_chunkCorrection : m_samplesChunkSize;
             m_throttleToggle = !m_throttleToggle;
         }
         SampleVector::iterator readUntil;
         m_sampleFifo->readAdvance(readUntil, m_samplesChunkSize); // pull samples
         SampleVector::iterator beginRead = readUntil - m_samplesChunkSize;
         m_samplesCount += m_samplesChunkSize;
         m_udpSinkFEC.write(beginRead, m_samplesChunkSize);
     }
 }
Member Data Documentation
m_chunkCorrection
int RemoteOutputThread::m_chunkCorrection private
Definition at line 73 of file remoteoutputthread.h.
Referenced by setChunkCorrection(), and tick().
m_elapsedTimer
QElapsedTimer RemoteOutputThread::m_elapsedTimer private
Definition at line 78 of file remoteoutputthread.h.
Referenced by startWork(), and tick().
m_maxThrottlems
int RemoteOutputThread::m_maxThrottlems private
Definition at line 77 of file remoteoutputthread.h.
Referenced by startWork().
m_running
volatile bool RemoteOutputThread::m_running private
Definition at line 68 of file remoteoutputthread.h.
Referenced by isRunning(), run(), setSamplerate(), startWork(), stopWork(), tick(), and ~RemoteOutputThread().
m_sampleFifo
SampleSourceFifo* RemoteOutputThread::m_sampleFifo private
Definition at line 71 of file remoteoutputthread.h.
Referenced by setSamplerate(), and tick().
m_samplerate
int RemoteOutputThread::m_samplerate private
Definition at line 75 of file remoteoutputthread.h.
Referenced by setSamplerate(), and tick().
m_samplesChunkSize
int RemoteOutputThread::m_samplesChunkSize private
Definition at line 70 of file remoteoutputthread.h.
Referenced by setSamplerate(), and tick().
m_samplesCount
uint32_t RemoteOutputThread::m_samplesCount private
Definition at line 72 of file remoteoutputthread.h.
Referenced by getSamplesCount(), setSamplesCount(), and tick().
m_startWaiter
QWaitCondition RemoteOutputThread::m_startWaiter private
Definition at line 67 of file remoteoutputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex RemoteOutputThread::m_startWaitMutex private
Definition at line 66 of file remoteoutputthread.h.
Referenced by startWork().
m_throttlems
int RemoteOutputThread::m_throttlems private
Definition at line 76 of file remoteoutputthread.h.
Referenced by setSamplerate(), and tick().
m_throttleToggle
bool RemoteOutputThread::m_throttleToggle private
Definition at line 79 of file remoteoutputthread.h.
Referenced by tick().
m_udpSinkFEC
UDPSinkFEC RemoteOutputThread::m_udpSinkFEC private
Definition at line 81 of file remoteoutputthread.h.
Referenced by setDataAddress(), setNbBlocksFEC(), setSamplerate(), setTxDelay(), startWork(), stopWork(), and tick().
The documentation for this class was generated from the following files:
plugins/samplesink/remoteoutput/remoteoutputthread.h
plugins/samplesink/remoteoutput/remoteoutputthread.cpp