SDRAngel: FileInput::MsgStartStop Class Reference
FileInput::MsgStartStop Class Reference
#include <fileinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 161 of file fileinput.h.
Constructor & Destructor Documentation
MsgStartStop()
FileInput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 174 of file fileinput.h.
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* FileInput::MsgStartStop::create (bool startStop) inline static
Definition at line 167 of file fileinput.h.
Referenced by FileInputGUI::on_startStop_toggled(), and FileInput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool FileInput::MsgStartStop::getStartStop () const inline
Definition at line 165 of file fileinput.h.
Referenced by FileInputGUI::handleMessage(), and FileInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool FileInput::MsgStartStop::m_startStop protected
Definition at line 172 of file fileinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/fileinput/fileinput.h