SDRAngel: SWGSDRangel::SWGPresetTransfer Class Reference
SWGSDRangel::SWGPresetTransfer Class Reference
#include <SWGPresetTransfer.h>
Public Member Functions
SWGPresetTransfer ()
SWGPresetTransfer (QString *json)
virtual ~SWGPresetTransfer ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGPresetTransfer * fromJson (QString &jsonString) override
qint32 getDeviceSetIndex ()
void setDeviceSetIndex (qint32 device_set_index)
SWGPresetIdentifier * getPreset ()
void setPreset (SWGPresetIdentifier *preset)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 device_set_index
bool m_device_set_index_isSet
SWGPresetIdentifier * preset
bool m_preset_isSet
Detailed Description
Definition at line 32 of file SWGPresetTransfer.h.
Constructor & Destructor Documentation
SWGPresetTransfer() [1/2]
SWGSDRangel::SWGPresetTransfer::SWGPresetTransfer ()
Definition at line 30 of file SWGPresetTransfer.cpp.
References device_set_index, m_device_set_index_isSet, m_preset_isSet, and preset.
{
     device_set_index = 0;
     m_device_set_index_isSet = false;
     preset = nullptr;
     m_preset_isSet = false;
 }
SWGPresetTransfer() [2/2]
SWGSDRangel::SWGPresetTransfer::SWGPresetTransfer (QString * json)
Definition at line 25 of file SWGPresetTransfer.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGPresetTransfer()
SWGSDRangel::SWGPresetTransfer::~SWGPresetTransfer () virtual
Definition at line 37 of file SWGPresetTransfer.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGPresetTransfer::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 75 of file SWGPresetTransfer.cpp.
References asJsonObject().
Referenced by SWGSDRangel::SWGInstanceApi::instancePresetPatch(), SWGSDRangel::SWGInstanceApi::instancePresetPost(), and SWGSDRangel::SWGInstanceApi::instancePresetPut().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGPresetTransfer::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 86 of file SWGPresetTransfer.cpp.
References device_set_index, SWGSDRangel::SWGPresetIdentifier::isSet(), m_device_set_index_isSet, preset, and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_device_set_index_isSet){
         obj->insert("deviceSetIndex", QJsonValue(device_set_index));
     }
     if((preset != nullptr) && (preset->isSet())){
         toJsonValue(QString("preset"), preset, obj, QString("SWGPresetIdentifier"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGPresetTransfer::cleanup ()
Definition at line 50 of file SWGPresetTransfer.cpp.
References preset.
Referenced by ~SWGPresetTransfer().
{
     if(preset != nullptr) {
         delete preset;
     }
 }
fromJson()
SWGPresetTransfer * SWGSDRangel::SWGPresetTransfer::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 58 of file SWGPresetTransfer.cpp.
References fromJsonObject().
Referenced by WebAPIRequestMapper::instancePresetService(), and SWGPresetTransfer().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGPresetTransfer::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 67 of file SWGPresetTransfer.cpp.
References device_set_index, preset, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&device_set_index, pJson["deviceSetIndex"], "qint32", "");
     ::SWGSDRangel::setValue(&preset, pJson["preset"], "SWGPresetIdentifier", "SWGPresetIdentifier");
 }
getDeviceSetIndex()
qint32 SWGSDRangel::SWGPresetTransfer::getDeviceSetIndex ()
Definition at line 99 of file SWGPresetTransfer.cpp.
References device_set_index.
Referenced by WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), and WebAPIAdapterSrv::instancePresetPut().
{
     return device_set_index;
 }
getPreset()
SWGPresetIdentifier * SWGSDRangel::SWGPresetTransfer::getPreset ()
Definition at line 109 of file SWGPresetTransfer.cpp.
References preset.
Referenced by WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), and WebAPIRequestMapper::validatePresetTransfer().
{
     return preset;
 }
init()
void SWGSDRangel::SWGPresetTransfer::init ()
Definition at line 42 of file SWGPresetTransfer.cpp.
References device_set_index, m_device_set_index_isSet, m_preset_isSet, and preset.
Referenced by SWGPresetTransfer().
{
     device_set_index = 0;
     m_device_set_index_isSet = false;
     preset = new SWGPresetIdentifier();
     m_preset_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGPresetTransfer::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 120 of file SWGPresetTransfer.cpp.
References SWGSDRangel::SWGPresetIdentifier::isSet(), m_device_set_index_isSet, and preset.
{
     bool isObjectUpdated = false;
     do{
         if(m_device_set_index_isSet){ isObjectUpdated = true; break;}
         if(preset != nullptr && preset->isSet()){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setDeviceSetIndex()
void SWGSDRangel::SWGPresetTransfer::setDeviceSetIndex (qint32 device_set_index)
Definition at line 103 of file SWGPresetTransfer.cpp.
References device_set_index, and m_device_set_index_isSet.
{
     this->device_set_index = device_set_index;
     this->m_device_set_index_isSet = true;
 }
setPreset()
void SWGSDRangel::SWGPresetTransfer::setPreset (SWGPresetIdentifier * preset)
Definition at line 113 of file SWGPresetTransfer.cpp.
References m_preset_isSet, and preset.
{
     this->preset = preset;
     this->m_preset_isSet = true;
 }
Member Data Documentation
device_set_index
qint32 SWGSDRangel::SWGPresetTransfer::device_set_index private
Definition at line 55 of file SWGPresetTransfer.h.
Referenced by asJsonObject(), fromJsonObject(), getDeviceSetIndex(), init(), setDeviceSetIndex(), and SWGPresetTransfer().
m_device_set_index_isSet
bool SWGSDRangel::SWGPresetTransfer::m_device_set_index_isSet private
Definition at line 56 of file SWGPresetTransfer.h.
Referenced by asJsonObject(), init(), isSet(), setDeviceSetIndex(), and SWGPresetTransfer().
m_preset_isSet
bool SWGSDRangel::SWGPresetTransfer::m_preset_isSet private
Definition at line 59 of file SWGPresetTransfer.h.
Referenced by init(), setPreset(), and SWGPresetTransfer().
preset
SWGPresetIdentifier* SWGSDRangel::SWGPresetTransfer::preset private
Definition at line 58 of file SWGPresetTransfer.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getPreset(), init(), isSet(), setPreset(), and SWGPresetTransfer().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGPresetTransfer.h
swagger/sdrangel/code/qt5/client/SWGPresetTransfer.cpp