SDRAngel: DeviceStreamSelectionDialog Class Reference
DeviceStreamSelectionDialog Class Reference
#include <devicestreamselectiondialog.h>
Inherits QDialog.
Public Member Functions
DeviceStreamSelectionDialog (QWidget *parent=nullptr)
~DeviceStreamSelectionDialog ()
bool hasChanged () const
void setNumberOfStreams (int nbStreams)
void setStreamIndex (int index)
int getSelectedStreamIndex () const
Private Slots
void accept ()
Private Attributes
Ui::DeviceStreamSelectionDialog * ui
bool m_hasChanged
int m_streamIndex
Detailed Description
Definition at line 30 of file devicestreamselectiondialog.h.
Constructor & Destructor Documentation
DeviceStreamSelectionDialog()
DeviceStreamSelectionDialog::DeviceStreamSelectionDialog (QWidget * parent = nullptr) explicit
Definition at line 22 of file devicestreamselectiondialog.cpp.
References setStreamIndex(), and ui.
                                                                         :
     QDialog(parent),
     ui(new Ui::DeviceStreamSelectionDialog),
     m_hasChanged(false)
 {
     ui->setupUi(this);
     setStreamIndex(0);
 }
~DeviceStreamSelectionDialog()
DeviceStreamSelectionDialog::~DeviceStreamSelectionDialog ()
Definition at line 31 of file devicestreamselectiondialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
accept
void DeviceStreamSelectionDialog::accept () private slot
Definition at line 51 of file devicestreamselectiondialog.cpp.
References m_hasChanged, m_streamIndex, and ui.
 {
     m_streamIndex = ui->deviceStream->currentIndex();
     m_hasChanged = true;
      QDialog::accept();
 }
getSelectedStreamIndex()
int DeviceStreamSelectionDialog::getSelectedStreamIndex () const inline
Definition at line 39 of file devicestreamselectiondialog.h.
Referenced by AMDemodGUI::onMenuDialogCalled().
 { return m_streamIndex; };
hasChanged()
bool DeviceStreamSelectionDialog::hasChanged () const inline
Definition at line 36 of file devicestreamselectiondialog.h.
 { return m_hasChanged; }
setNumberOfStreams()
void DeviceStreamSelectionDialog::setNumberOfStreams (int nbStreams)
Definition at line 36 of file devicestreamselectiondialog.cpp.
References arg(), i, and ui.
Referenced by AMDemodGUI::onMenuDialogCalled().
 {
     ui->deviceStream->clear();
     for (int i = 0; i < nbStreams; i++) {
         ui->deviceStream->addItem(tr("%1").arg(i));
     }
 }
setStreamIndex()
void DeviceStreamSelectionDialog::setStreamIndex (int index)
Definition at line 45 of file devicestreamselectiondialog.cpp.
References m_streamIndex, and ui.
Referenced by DeviceStreamSelectionDialog(), and AMDemodGUI::onMenuDialogCalled().
 {
     ui->deviceStream->setCurrentIndex(index);
     m_streamIndex = ui->deviceStream->currentIndex();
 }
Member Data Documentation
m_hasChanged
bool DeviceStreamSelectionDialog::m_hasChanged private
Definition at line 46 of file devicestreamselectiondialog.h.
Referenced by accept().
m_streamIndex
int DeviceStreamSelectionDialog::m_streamIndex private
Definition at line 47 of file devicestreamselectiondialog.h.
Referenced by accept(), and setStreamIndex().
ui
Ui::DeviceStreamSelectionDialog* DeviceStreamSelectionDialog::ui private
Definition at line 45 of file devicestreamselectiondialog.h.
Referenced by accept(), DeviceStreamSelectionDialog(), setNumberOfStreams(), setStreamIndex(), and ~DeviceStreamSelectionDialog().
The documentation for this class was generated from the following files:
sdrgui/gui/devicestreamselectiondialog.h
sdrgui/gui/devicestreamselectiondialog.cpp