SDRAngel: IntHalfbandFilterST< HBFilterOrder > Class Template Reference
IntHalfbandFilterST< HBFilterOrder > Class Template Reference
#include <inthalfbandfilterst.h>
Public Member Functions
IntHalfbandFilterST ()
bool workDecimateCenter (Sample *sample)
bool workInterpolateCenter (Sample *sampleIn, Sample *SampleOut)
bool workDecimateCenter (int32_t *x, int32_t *y)
bool workDecimateLowerHalf (Sample *sample)
bool workInterpolateLowerHalf (Sample *sampleIn, Sample *sampleOut)
bool workDecimateUpperHalf (Sample *sample)
bool workInterpolateUpperHalf (Sample *sampleIn, Sample *sampleOut)
void myDecimate (const Sample *sample1, Sample *sample2)
void myDecimate (int32_t x1, int32_t y1, int32_t *x2, int32_t *y2)
void myInterpolate (Sample *sample1, Sample *sample2)
void myInterpolate (int32_t *x1, int32_t *y1, int32_t *x2, int32_t *y2)
Protected Member Functions
int32_t m_samplesAligned [HBFilterOrder][2] __attribute__ ((aligned(16)))
void storeSample (const FixReal &sampleI, const FixReal &sampleQ)
void storeSample (int32_t x, int32_t y)
void advancePointer ()
void doFIR (Sample *sample)
void doFIR (int32_t *x, int32_t *y)
Protected Attributes
int32_t m_samplesDB [2 *HBFilterOrder][2]
int m_ptr
int m_size
int m_state
int32_t m_iEvenAcc
int32_t m_qEvenAcc
int32_t m_iOddAcc
int32_t m_qOddAcc
Detailed Description
template<uint32_t HBFilterOrder>
class IntHalfbandFilterST< HBFilterOrder >
Definition at line 32 of file inthalfbandfilterst.h.
Constructor & Destructor Documentation
IntHalfbandFilterST()
template<uint32_t HBFilterOrder> IntHalfbandFilterST< HBFilterOrder >::IntHalfbandFilterST ()
Definition at line 561 of file inthalfbandfilterst.h.
References i.
 {
     m_size = HBFIRFilterTraits<HBFilterOrder>::hbOrder;
     for (int i = 0; i < m_size; i++)
     {
         m_samplesDB[i][0] = 0;
         m_samplesDB[i][1] = 0;
     }
     m_ptr = 0;
     m_state = 0;
     m_iEvenAcc = 0;
     m_qEvenAcc = 0;
     m_iOddAcc = 0;
     m_qOddAcc = 0;
 }
Member Function Documentation
__attribute__()
template<uint32_t HBFilterOrder> int32_t m_samplesAligned [HBFilterOrder][2] IntHalfbandFilterST< HBFilterOrder >::__attribute__ ((aligned(16))) protected
advancePointer()
template<uint32_t HBFilterOrder> void IntHalfbandFilterST< HBFilterOrder >::advancePointer () inline protected
Definition at line 457 of file inthalfbandfilterst.h.
     {
         m_ptr = m_ptr + 1 < m_size ? m_ptr + 1: 0;
     }
doFIR() [1/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterST< HBFilterOrder >::doFIR (Sample * sample) inline protected
Definition at line 462 of file inthalfbandfilterst.h.
References i, Sample::setImag(), Sample::setReal(), and IntHalfbandFilterSTIntrinsics< HBFilterOrder >::workNA().
     {
         // calculate on odd values
         if ((m_ptr % 2) == 1)
         {
             m_iEvenAcc = 0;
             m_qEvenAcc = 0;
             m_iOddAcc = 0;
             m_qOddAcc = 0;
 #ifdef USE_SSE4_1
 //            memcpy((void *) m_samplesAligned, (const void *) &(m_samplesDB[ m_ptr + 1][0]), HBFilterOrder*2*sizeof(int32_t));
             IntHalfbandFilterSTIntrinsics<HBFilterOrder>::workNA(
                     m_ptr + 1,
                     m_samplesDB,
                     m_iEvenAcc,
                     m_qEvenAcc,
                     m_iOddAcc,
                     m_qOddAcc);
 #else
             int a = m_ptr + m_size; // tip pointer - odd
             int b = m_ptr + 1; // tail pointer - aven
             for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
             {
                 m_iEvenAcc += (m_samplesDB[a-1][0] + m_samplesDB[b][0])   * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 m_iOddAcc  += (m_samplesDB[a][0]   + m_samplesDB[b+1][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 m_qEvenAcc += (m_samplesDB[a-1][1] + m_samplesDB[b][1])   * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 m_qOddAcc  += (m_samplesDB[a][1]   + m_samplesDB[b+1][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 a -= 2;
                 b += 2;
             }
 #endif
             m_iEvenAcc += ((int32_t)m_samplesDB[m_ptr + m_size/2][0]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             m_qEvenAcc += ((int32_t)m_samplesDB[m_ptr + m_size/2][1]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             m_iOddAcc += ((int32_t)m_samplesDB[m_ptr + m_size/2 + 1][0]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             m_qOddAcc += ((int32_t)m_samplesDB[m_ptr + m_size/2 + 1][1]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             sample->setReal(m_iEvenAcc >> HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
             sample->setImag(m_qEvenAcc >> HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
         }
         else
         {
             sample->setReal(m_iOddAcc >> HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
             sample->setImag(m_qOddAcc >> HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
         }
     }
doFIR() [2/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterST< HBFilterOrder >::doFIR (int32_t * x, int32_t * y) inline protected
Definition at line 510 of file inthalfbandfilterst.h.
References i, and IntHalfbandFilterSTIntrinsics< HBFilterOrder >::workNA().
     {
         // calculate on odd values
         if ((m_ptr % 2) == 1)
         {
             m_iEvenAcc = 0;
             m_qEvenAcc = 0;
             m_iOddAcc = 0;
             m_qOddAcc = 0;
 #ifdef USE_SSE4_1
 //            memcpy((void *) m_samplesAligned, (const void *) &(m_samplesDB[ m_ptr + 1][0]), HBFilterOrder*2*sizeof(int32_t));
             IntHalfbandFilterSTIntrinsics<HBFilterOrder>::workNA(
                     m_ptr + 1,
                     m_samplesDB,
                     m_iEvenAcc,
                     m_qEvenAcc,
                     m_iOddAcc,
                     m_qOddAcc);
 #else
             int a = m_ptr + m_size; // tip pointer - odd
             int b = m_ptr + 1; // tail pointer - aven
             for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
             {
                 m_iEvenAcc += (m_samplesDB[a-1][0] + m_samplesDB[b][0])   * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 m_iOddAcc  += (m_samplesDB[a][0]   + m_samplesDB[b+1][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 m_qEvenAcc += (m_samplesDB[a-1][1] + m_samplesDB[b][1])   * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 m_qOddAcc  += (m_samplesDB[a][1]   + m_samplesDB[b+1][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 a -= 2;
                 b += 2;
             }
 #endif
             m_iEvenAcc += ((int32_t)m_samplesDB[m_ptr + m_size/2][0]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             m_qEvenAcc += ((int32_t)m_samplesDB[m_ptr + m_size/2][1]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             m_iOddAcc += ((int32_t)m_samplesDB[m_ptr + m_size/2 + 1][0]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             m_qOddAcc += ((int32_t)m_samplesDB[m_ptr + m_size/2 + 1][1]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             *x = m_iEvenAcc >> HBFIRFilterTraits<HBFilterOrder>::hbShift -1;
             *y = m_qEvenAcc >> HBFIRFilterTraits<HBFilterOrder>::hbShift -1;
         }
         else
         {
             *x = m_iOddAcc >> HBFIRFilterTraits<HBFilterOrder>::hbShift -1;
             *y = m_qOddAcc >> HBFIRFilterTraits<HBFilterOrder>::hbShift -1;
         }
     }
myDecimate() [1/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterST< HBFilterOrder >::myDecimate (const Sample * sample1, Sample * sample2) inline
Definition at line 387 of file inthalfbandfilterst.h.
References Sample::imag(), and Sample::real().
     {
         storeSample((FixReal) sample1->real(), (FixReal) sample1->imag());
         advancePointer();
         storeSample((FixReal) sample2->real(), (FixReal) sample2->imag());
         doFIR(sample2);
         advancePointer();
     }
myDecimate() [2/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterST< HBFilterOrder >::myDecimate (int32_t x1, int32_t y1, int32_t * x2, int32_t * y2) inline
Definition at line 397 of file inthalfbandfilterst.h.
     {
         storeSample(x1, y1);
         advancePointer();
         storeSample(*x2, *y2);
         doFIR(x2, y2);
         advancePointer();
     }
myInterpolate() [1/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterST< HBFilterOrder >::myInterpolate (Sample * sample1, Sample * sample2) inline
Definition at line 407 of file inthalfbandfilterst.h.
References Sample::imag(), and Sample::real().
     {
         storeSample((FixReal) sample1->real(), (FixReal) sample1->imag());
         doFIR(sample1);
         advancePointer();
         storeSample(0, 0);
         doFIR(sample2);
         advancePointer();
     }
myInterpolate() [2/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterST< HBFilterOrder >::myInterpolate (int32_t * x1, int32_t * y1, int32_t * x2, int32_t * y2) inline
Definition at line 418 of file inthalfbandfilterst.h.
     {
         storeSample(*x1, *y1);
         doFIR(x1, y1);
         advancePointer();
         storeSample(0, 0);
         doFIR(x2, y2);
         advancePointer();
     }
storeSample() [1/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterST< HBFilterOrder >::storeSample (const FixReal & sampleI, const FixReal & sampleQ) inline protected
Definition at line 441 of file inthalfbandfilterst.h.
     {
         m_samplesDB[m_ptr][0] = sampleI;
         m_samplesDB[m_ptr][1] = sampleQ;
         m_samplesDB[m_ptr + m_size][0] = sampleI;
         m_samplesDB[m_ptr + m_size][1] = sampleQ;
     }
storeSample() [2/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterST< HBFilterOrder >::storeSample (int32_t x, int32_t y) inline protected
Definition at line 449 of file inthalfbandfilterst.h.
     {
         m_samplesDB[m_ptr][0] = x;
         m_samplesDB[m_ptr][1] = y;
         m_samplesDB[m_ptr + m_size][0] = x;
         m_samplesDB[m_ptr + m_size][1] = y;
     }
workDecimateCenter() [1/2]
template<uint32_t HBFilterOrder> bool IntHalfbandFilterST< HBFilterOrder >::workDecimateCenter (Sample * sample) inline
Definition at line 37 of file inthalfbandfilterst.h.
References Sample::imag(), and Sample::real().
     {
         // insert sample into ring-buffer
         storeSample((FixReal) sample->real(), (FixReal) sample->imag());
         switch(m_state)
         {
             case 0:
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workDecimateCenter() [2/2]
template<uint32_t HBFilterOrder> bool IntHalfbandFilterST< HBFilterOrder >::workDecimateCenter (int32_t * x, int32_t * y) inline
Definition at line 96 of file inthalfbandfilterst.h.
     {
         // insert sample into ring-buffer
         storeSample(*x, *y);
         switch(m_state)
         {
             case 0:
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // save result
                 doFIR(x, y);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workDecimateLowerHalf()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterST< HBFilterOrder >::workDecimateLowerHalf (Sample * sample) inline
Definition at line 124 of file inthalfbandfilterst.h.
References Sample::imag(), and Sample::real().
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSample((FixReal) -sample->imag(), (FixReal) sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             case 1:
                 // insert sample into ring-buffer
                 storeSample((FixReal) -sample->real(), (FixReal) -sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 2;
                 // tell caller we have a new sample
                 return true;
             case 2:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sample->imag(), (FixReal) -sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 3;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sample->real(), (FixReal) sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workDecimateUpperHalf()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterST< HBFilterOrder >::workDecimateUpperHalf (Sample * sample) inline
Definition at line 256 of file inthalfbandfilterst.h.
References Sample::imag(), and Sample::real().
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sample->imag(), (FixReal) -sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             case 1:
                 // insert sample into ring-buffer
                 storeSample((FixReal) -sample->real(), (FixReal) -sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 2;
                 // tell caller we have a new sample
                 return true;
             case 2:
                 // insert sample into ring-buffer
                 storeSample((FixReal) -sample->imag(), (FixReal) sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 3;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sample->real(), (FixReal) sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workInterpolateCenter()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterST< HBFilterOrder >::workInterpolateCenter (Sample * sampleIn, Sample * SampleOut) inline
Definition at line 66 of file inthalfbandfilterst.h.
References Sample::imag(), and Sample::real().
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSample(0, 0);
                 // save result
                 doFIR(SampleOut);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we didn't consume the sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
                 // save result
                 doFIR(SampleOut);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we consumed the sample
                 return true;
         }
     }
workInterpolateLowerHalf()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterST< HBFilterOrder >::workInterpolateLowerHalf (Sample * sampleIn, Sample * sampleOut) inline
Definition at line 175 of file inthalfbandfilterst.h.
References Sample::imag(), Sample::real(), Sample::setImag(), and Sample::setReal().
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // insert sample into ring-buffer
             storeSample(0, 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(s.imag());
             sampleOut->setImag(-s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 1;
             // tell caller we didn't consume the sample
             return false;
         case 1:
             // insert sample into ring-buffer
             storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 2;
             // tell caller we consumed the sample
             return true;
         case 2:
             // insert sample into ring-buffer
             storeSample(0, 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.imag());
             sampleOut->setImag(s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 3;
             // tell caller we didn't consume the sample
             return false;
         default:
             // insert sample into ring-buffer
             storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 0;
             // tell caller we consumed the sample
             return true;
         }
     }
workInterpolateUpperHalf()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterST< HBFilterOrder >::workInterpolateUpperHalf (Sample * sampleIn, Sample * sampleOut) inline
Definition at line 307 of file inthalfbandfilterst.h.
References Sample::imag(), Sample::real(), Sample::setImag(), and Sample::setReal().
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // insert sample into ring-buffer
             storeSample(0, 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.imag());
             sampleOut->setImag(s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 1;
             // tell caller we didn't consume the sample
             return false;
         case 1:
             // insert sample into ring-buffer
             storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 2;
             // tell caller we consumed the sample
             return true;
         case 2:
             // insert sample into ring-buffer
             storeSample(0, 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(s.imag());
             sampleOut->setImag(-s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 3;
             // tell caller we didn't consume the sample
             return false;
         default:
             // insert sample into ring-buffer
             storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 0;
             // tell caller we consumed the sample
             return true;
         }
     }
Member Data Documentation
m_iEvenAcc
template<uint32_t HBFilterOrder> int32_t IntHalfbandFilterST< HBFilterOrder >::m_iEvenAcc protected
Definition at line 435 of file inthalfbandfilterst.h.
m_iOddAcc
template<uint32_t HBFilterOrder> int32_t IntHalfbandFilterST< HBFilterOrder >::m_iOddAcc protected
Definition at line 437 of file inthalfbandfilterst.h.
m_ptr
template<uint32_t HBFilterOrder> int IntHalfbandFilterST< HBFilterOrder >::m_ptr protected
Definition at line 432 of file inthalfbandfilterst.h.
m_qEvenAcc
template<uint32_t HBFilterOrder> int32_t IntHalfbandFilterST< HBFilterOrder >::m_qEvenAcc protected
Definition at line 436 of file inthalfbandfilterst.h.
m_qOddAcc
template<uint32_t HBFilterOrder> int32_t IntHalfbandFilterST< HBFilterOrder >::m_qOddAcc protected
Definition at line 438 of file inthalfbandfilterst.h.
m_samplesDB
template<uint32_t HBFilterOrder> int32_t IntHalfbandFilterST< HBFilterOrder >::m_samplesDB[2 *HBFilterOrder][2] protected
Definition at line 430 of file inthalfbandfilterst.h.
m_size
template<uint32_t HBFilterOrder> int IntHalfbandFilterST< HBFilterOrder >::m_size protected
Definition at line 433 of file inthalfbandfilterst.h.
m_state
template<uint32_t HBFilterOrder> int IntHalfbandFilterST< HBFilterOrder >::m_state protected
Definition at line 434 of file inthalfbandfilterst.h.
The documentation for this class was generated from the following file:
sdrbase/dsp/inthalfbandfilterst.h