SDRAngel: BladerfBandwidths Class Reference
BladerfBandwidths Class Reference
#include <devicebladerf1.h>
Static Public Member Functions
static unsigned int getBandwidth (unsigned int bandwidth_index)
static unsigned int getBandwidthIndex (unsigned int bandwidth)
static unsigned int getNbBandwidths ()
Static Private Attributes
static const unsigned int m_nb_halfbw = 16
static const unsigned int m_halfbw []
Detailed Description
Definition at line 34 of file devicebladerf1.h.
Member Function Documentation
getBandwidth()
unsigned int BladerfBandwidths::getBandwidth (unsigned int bandwidth_index) static
Definition at line 110 of file devicebladerf1.cpp.
Referenced by Bladerf1InputGui::Bladerf1InputGui(), Bladerf1OutputGui::Bladerf1OutputGui(), Bladerf1OutputGui::on_bandwidth_currentIndexChanged(), and Bladerf1InputGui::on_bandwidth_currentIndexChanged().
 {
     if (bandwidth_index < m_nb_halfbw)
     {
         return m_halfbw[bandwidth_index] * 2;
     }
     else
     {
         return m_halfbw[0] * 2;
     }
 }
getBandwidthIndex()
unsigned int BladerfBandwidths::getBandwidthIndex (unsigned int bandwidth) static
Definition at line 122 of file devicebladerf1.cpp.
References i.
Referenced by Bladerf1InputGui::displaySettings(), and Bladerf1OutputGui::displaySettings().
 {
     for (unsigned int i=0; i < m_nb_halfbw; i++)
     {
         if (bandwidth/2000 == m_halfbw[i])
         {
             return i;
         }
     }
     return 0;
 }
getNbBandwidths()
unsigned int BladerfBandwidths::getNbBandwidths () static
Definition at line 135 of file devicebladerf1.cpp.
References m_nb_halfbw.
Referenced by Bladerf1InputGui::Bladerf1InputGui(), and Bladerf1OutputGui::Bladerf1OutputGui().
 {
     return BladerfBandwidths::m_nb_halfbw;
 }
Member Data Documentation
m_halfbw
const unsigned int BladerfBandwidths::m_halfbw static private
Initial value:
= {
        750,
        875,
       1250,
       1375,
       1500,
       1920,
       2500,
       2750,
       3000,
       3500,
       4375,
       5000,
       6000,
       7000,
      10000,
      14000}
Definition at line 41 of file devicebladerf1.h.
Referenced by DeviceBladeRF1::open_bladerf_from_serial().
m_nb_halfbw
const unsigned int BladerfBandwidths::m_nb_halfbw = 16 static private
Definition at line 40 of file devicebladerf1.h.
Referenced by getNbBandwidths(), and DeviceBladeRF1::open_bladerf_from_serial().
The documentation for this class was generated from the following files:
devices/bladerf1/devicebladerf1.h
devices/bladerf1/devicebladerf1.cpp