SDRAngel: AudioResampler Class Reference
AudioResampler Class Reference
#include <audioresampler.h>
Public Member Functions
AudioResampler ()
~AudioResampler ()
void setDecimation (uint32_t decimation)
uint32_t getDecimation () const
void setAudioFilters (int srHigh, int srLow, int fcLow, int fcHigh, float gain=1.0f)
bool downSample (qint16 sampleIn, qint16 &sampleOut)
bool upSample (qint16 sampleIn, qint16 &sampleOut)
Private Attributes
AudioFilter m_audioFilter
uint32_t m_decimation
uint32_t m_decimationCount
Detailed Description
Definition at line 25 of file audioresampler.h.
Constructor & Destructor Documentation
AudioResampler()
AudioResampler::AudioResampler ()
Definition at line 21 of file audioresampler.cpp.
                                :
     m_decimation(1),
     m_decimationCount(0)
 {}
~AudioResampler()
AudioResampler::~AudioResampler ()
Definition at line 26 of file audioresampler.cpp.
 {}
Member Function Documentation
downSample()
bool AudioResampler::downSample (qint16 sampleIn, qint16 & sampleOut)
Definition at line 47 of file audioresampler.cpp.
References m_audioFilter, m_decimation, m_decimationCount, and AudioFilter::run().
Referenced by getDecimation(), and FreeDVMod::pullAF().
 {
     if (m_decimation == 1)
     {
         sampleOut = sampleIn;
         return true;
     }
     if (m_decimationCount >= m_decimation - 1)
     {
         float lpSample = m_audioFilter.run(sampleIn / 32768.0f);
         sampleOut = lpSample * 32768.0f;
         m_decimationCount = 0;
         return true;
     }
     else
     {
         m_decimationCount++;
         return false;
     }
 }
getDecimation()
uint32_t AudioResampler::getDecimation () const inline
Definition at line 32 of file audioresampler.h.
References downSample(), m_decimation, setAudioFilters(), and upSample().
Referenced by FreeDVDemod::pushSampleToDV().
 { return m_decimation; }
setAudioFilters()
void AudioResampler::setAudioFilters (int srHigh, int srLow, int fcLow, int fcHigh, float gain = 1.0f)
Definition at line 34 of file audioresampler.cpp.
References m_audioFilter, and AudioFilter::setDecimFilters().
Referenced by FreeDVMod::applyAudioSampleRate(), FreeDVDemod::applyAudioSampleRate(), and getDecimation().
 {
     srHigh = (srHigh <= 100 ? 100 : srHigh);
     srLow = (srLow <= 0 ? 1 : srLow);
     srLow = srLow > srHigh - 50 ? srHigh - 50 : srLow;
     fcLow = fcLow < 0 ? 0 : fcLow;
     fcHigh = fcHigh < 100 ? 100 : fcHigh;
     fcLow = fcLow > fcHigh - 100 ? fcHigh - 100 : fcLow;
     m_audioFilter.setDecimFilters(srHigh, srLow, fcHigh, fcLow, gain);
 }
setDecimation()
void AudioResampler::setDecimation (uint32_t decimation)
Definition at line 29 of file audioresampler.cpp.
References decimation(), and m_decimation.
Referenced by FreeDVMod::applyAudioSampleRate(), and FreeDVDemod::applyAudioSampleRate().
 {
     m_decimation = decimation == 0 ? 1 : decimation;
 }
upSample()
bool AudioResampler::upSample (qint16 sampleIn, qint16 & sampleOut)
Definition at line 69 of file audioresampler.cpp.
References m_audioFilter, m_decimation, m_decimationCount, and AudioFilter::run().
Referenced by getDecimation(), and FreeDVDemod::pushSampleToDV().
 {
     float lpSample;
     if (m_decimation == 1)
     {
         sampleOut = sampleIn;
         return true;
     }
     if (m_decimationCount >= m_decimation - 1)
     {
         m_decimationCount = 0;
         lpSample = m_audioFilter.run(sampleIn / 32768.0f);
         sampleOut = lpSample * 32768.0f;
         return true;
     }
     else
     {
         m_decimationCount++;
         lpSample = m_audioFilter.run(0.0f);
         sampleOut = lpSample * 32768.0f;
         return false;
     }
 }
Member Data Documentation
m_audioFilter
AudioFilter AudioResampler::m_audioFilter private
Definition at line 38 of file audioresampler.h.
Referenced by downSample(), setAudioFilters(), and upSample().
m_decimation
uint32_t AudioResampler::m_decimation private
Definition at line 39 of file audioresampler.h.
Referenced by downSample(), getDecimation(), setDecimation(), and upSample().
m_decimationCount
uint32_t AudioResampler::m_decimationCount private
Definition at line 40 of file audioresampler.h.
Referenced by downSample(), and upSample().
The documentation for this class was generated from the following files:
sdrbase/audio/audioresampler.h
sdrbase/audio/audioresampler.cpp