SDRAngel: SoapySDRInputGui Class Reference
SoapySDRInputGui Class Reference
#include <soapysdrinputgui.h>
Public Member Functions
SoapySDRInputGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~SoapySDRInputGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void antennasChanged ()
void sampleRateChanged (double sampleRate)
void bandwidthChanged (double bandwidth)
void tunableElementChanged (QString name, double value)
void globalGainChanged (double gain)
void autoGainChanged (bool set)
void individualGainChanged (QString name, double value)
void autoDCCorrectionChanged (bool set)
void autoIQCorrectionChanged (bool set)
void dcCorrectionModuleChanged (double value)
void dcCorrectionArgumentChanged (double value)
void iqCorrectionModuleChanged (double value)
void iqCorrectionArgumentChanged (double value)
void streamArgChanged (QString itemName, QVariant value)
void deviceArgChanged (QString itemName, QVariant value)
void on_centerFrequency_changed (quint64 value)
void on_LOppm_valueChanged (int value)
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_decim_currentIndexChanged (int index)
void on_fcPos_currentIndexChanged (int index)
void on_transverter_clicked ()
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void createRangesControl (ItemSettingGUI **settingGUI, const SoapySDR::RangeList &rangeList, const QString &text, const QString &unit)
void createAntennasControl (const std::vector< std::string > &antennaList)
void createTunableElementsControl (const std::vector< DeviceSoapySDRParams::FrequencySetting > &tunableElementsList)
void createGlobalGainControl ()
void createIndividualGainsControl (const std::vector< DeviceSoapySDRParams::GainSetting > &individualGainsList)
void createCorrectionsControl ()
void createArgumentsControl (const SoapySDR::ArgInfoList &argInfoList, bool deviceArguments)
void displaySettings ()
void displayTunableElementsControlSettings ()
void displayIndividualGainsControlSettings ()
void displayCorrectionsSettings ()
void displayStreamArgsSettings ()
void displayDeviceArgsSettings ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void updateFrequencyLimits ()
void setCenterFrequencySetting (uint64_t kHzValue)
void blockApplySettings (bool block)
Private Attributes
Ui::SoapySDRInputGui * ui
DeviceUISet * m_deviceUISet
bool m_forceSettings
bool m_doApplySettings
SoapySDRInputSettings m_settings
QTimer m_updateTimer
QTimer m_statusTimer
SoapySDRInput * m_sampleSource
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
StringRangeGUI * m_antennas
ItemSettingGUI * m_sampleRateGUI
ItemSettingGUI * m_bandwidthGUI
std::vector< DynamicItemSettingGUI * > m_tunableElementsGUIs
IntervalSliderGUI * m_gainSliderGUI
std::vector< DynamicItemSettingGUI * > m_individualGainsGUIs
QCheckBox * m_autoGain
ComplexFactorGUI * m_dcCorrectionGUI
ComplexFactorGUI * m_iqCorrectionGUI
QCheckBox * m_autoDCCorrection
QCheckBox * m_autoIQCorrection
std::vector< DynamicArgSettingGUI * > m_streamArgsGUIs
std::vector< DynamicArgSettingGUI * > m_deviceArgsGUIs
Detailed Description
Definition at line 42 of file soapysdrinputgui.h.
Constructor & Destructor Documentation
SoapySDRInputGui()
SoapySDRInputGui::SoapySDRInputGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 41 of file soapysdrinputgui.cpp.
References bandwidthChanged(), createAntennasControl(), createArgumentsControl(), createCorrectionsControl(), createGlobalGainControl(), createIndividualGainsControl(), createRangesControl(), createTunableElementsControl(), displaySettings(), SoapySDRInput::getAntennas(), SoapySDRInput::getBandwidthRanges(), SoapySDRInput::getDeviceArgInfoList(), SoapySDRInput::getFrequencyRange(), SoapySDRInput::getIndividualGainsRanges(), SoapySDRInput::getRateRanges(), DeviceAPI::getSampleSource(), SoapySDRInput::getStreamArgInfoList(), SoapySDRInput::getTunableElements(), ColorMapper::GrayGold, handleInputMessages(), SoapySDRInput::initDeviceArgSettings(), SoapySDRInput::initGainSettings(), SoapySDRInput::initStreamArgSettings(), SoapySDRInput::initTunableElementsSettings(), m_bandwidthGUI, DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_sampleRateGUI, m_sampleSource, m_settings, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), sampleRateChanged(), sendSettings(), SoapySDRInput::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                                             :
     QWidget(parent),
     ui(new Ui::SoapySDRInputGui),
     m_deviceUISet(deviceUISet),
     m_forceSettings(true),
     m_doApplySettings(true),
     m_sampleSource(0),
     m_sampleRate(0),
     m_deviceCenterFrequency(0),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_antennas(0),
     m_sampleRateGUI(0),
     m_bandwidthGUI(0),
     m_gainSliderGUI(0),
     m_autoGain(0),
     m_dcCorrectionGUI(0),
     m_iqCorrectionGUI(0),
     m_autoDCCorrection(0),
     m_autoIQCorrection(0)
 {
     m_sampleSource = (SoapySDRInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     uint64_t f_min, f_max;
     m_sampleSource->getFrequencyRange(f_min, f_max);
     ui->centerFrequency->setValueRange(7, f_min/1000, f_max/1000);
     createCorrectionsControl();
     createAntennasControl(m_sampleSource->getAntennas());
     createRangesControl(&m_sampleRateGUI, m_sampleSource->getRateRanges(), "SR", "S/s");
     createRangesControl(&m_bandwidthGUI, m_sampleSource->getBandwidthRanges(), "BW", "Hz");
     createTunableElementsControl(m_sampleSource->getTunableElements());
     createGlobalGainControl();
     createIndividualGainsControl(m_sampleSource->getIndividualGainsRanges());
     createArgumentsControl(m_sampleSource->getDeviceArgInfoList(), true);
     createArgumentsControl(m_sampleSource->getStreamArgInfoList(), false);
     m_sampleSource->initGainSettings(m_settings);
     m_sampleSource->initTunableElementsSettings(m_settings);
     m_sampleSource->initStreamArgSettings(m_settings);
     m_sampleSource->initDeviceArgSettings(m_settings);
     if (m_sampleRateGUI) {
         connect(m_sampleRateGUI, SIGNAL(valueChanged(double)), this, SLOT(sampleRateChanged(double)));
     }
     if (m_bandwidthGUI) {
         connect(m_bandwidthGUI,  SIGNAL(valueChanged(double)), this, SLOT(bandwidthChanged(double)));
     }
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
     sendSettings();
 }
~SoapySDRInputGui()
SoapySDRInputGui::~SoapySDRInputGui () virtual
Definition at line 105 of file soapysdrinputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
antennasChanged
void SoapySDRInputGui::antennasChanged () private slot
Definition at line 549 of file soapysdrinputgui.cpp.
References StringRangeGUI::getCurrentValue(), SoapySDRInputSettings::m_antenna, m_antennas, m_settings, and sendSettings().
Referenced by createAntennasControl().
 {
     const std::string& antennaStr = m_antennas->getCurrentValue();
     m_settings.m_antenna = QString(antennaStr.c_str());
     sendSettings();
 }
autoDCCorrectionChanged
void SoapySDRInputGui::autoDCCorrectionChanged (bool set) private slot
Definition at line 593 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::m_autoDCCorrection, m_settings, and sendSettings().
Referenced by createCorrectionsControl().
 {
     m_settings.m_autoDCCorrection = set;
     sendSettings();
 }
autoGainChanged
void SoapySDRInputGui::autoGainChanged (bool set) private slot
Definition at line 581 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::m_autoGain, m_settings, and sendSettings().
Referenced by createGlobalGainControl().
 {
     m_settings.m_autoGain = set;
     sendSettings();
 }
autoIQCorrectionChanged
void SoapySDRInputGui::autoIQCorrectionChanged (bool set) private slot
Definition at line 599 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::m_autoIQCorrection, m_settings, and sendSettings().
Referenced by createCorrectionsControl().
 {
     m_settings.m_autoIQCorrection = set;
     sendSettings();
 }
bandwidthChanged
void SoapySDRInputGui::bandwidthChanged (double bandwidth) private slot
Definition at line 563 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::m_bandwidth, m_settings, and sendSettings().
Referenced by SoapySDRInputGui().
 {
     m_settings.m_bandwidth = round(bandwidth);
     sendSettings();
 }
blockApplySettings()
void SoapySDRInputGui::blockApplySettings (bool block) private
Definition at line 889 of file soapysdrinputgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
createAntennasControl()
void SoapySDRInputGui::createAntennasControl (const std::vector< std::string > & antennaList) private
Definition at line 169 of file soapysdrinputgui.cpp.
References StringRangeGUI::addItem(), antennasChanged(), m_antennas, StringRangeGUI::setLabel(), StringRangeGUI::setUnits(), and ui.
Referenced by SoapySDRInputGui().
 {
     if (antennaList.size() == 0) { // return early if the antenna list is empty
         return;
     }
     m_antennas = new StringRangeGUI(this);
     m_antennas->setLabel(QString("RF in"));
     m_antennas->setUnits(QString("Port"));
     for (const auto &it : antennaList) {
         m_antennas->addItem(QString(it.c_str()), it);
     }
     QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
     layout->addWidget(m_antennas);
     connect(m_antennas, SIGNAL(valueChanged()), this, SLOT(antennasChanged()));
 }
createArgumentsControl()
void SoapySDRInputGui::createArgumentsControl (const SoapySDR::ArgInfoList & argInfoList, bool deviceArguments) private
Definition at line 325 of file soapysdrinputgui.cpp.
References ArgInfoGUI::addFloatValue(), ArgInfoGUI::addIntValue(), ArgInfoGUI::addStringValue(), ArgInfoGUI::ArgInfoBinary, ArgInfoGUI::ArgInfoContinuous, ArgInfoGUI::ArgInfoDiscrete, ArgInfoGUI::ArgInfoValueBool, ArgInfoGUI::ArgInfoValueFloat, ArgInfoGUI::ArgInfoValueInt, ArgInfoGUI::ArgInfoValueString, deviceArgChanged(), i, m_deviceArgsGUIs, m_streamArgsGUIs, ArgInfoGUI::setLabel(), ArgInfoGUI::setRange(), ArgInfoGUI::setToolTip(), ArgInfoGUI::setUnits(), streamArgChanged(), and ui.
Referenced by SoapySDRInputGui().
 {
     if (argInfoList.size() == 0) { // return early if list is empty
         return;
     }
     QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
     QFrame *line = new QFrame(this);
     line->setFrameShape(QFrame::HLine);
     line->setFrameShadow(QFrame::Sunken);
     layout->addWidget(line);
     std::vector<SoapySDR::ArgInfo>::const_iterator it = argInfoList.begin();
     for (; it != argInfoList.end(); ++it)
     {
         ArgInfoGUI::ArgInfoValueType valueType;
         ArgInfoGUI *argGUI;
         if (it->type == SoapySDR::ArgInfo::BOOL) {
             valueType = ArgInfoGUI::ArgInfoValueBool;
         } else if (it->type == SoapySDR::ArgInfo::INT) {
             valueType = ArgInfoGUI::ArgInfoValueInt;
         } else if (it->type == SoapySDR::ArgInfo::FLOAT) {
             valueType = ArgInfoGUI::ArgInfoValueFloat;
         } else if (it->type == SoapySDR::ArgInfo::STRING) {
             valueType = ArgInfoGUI::ArgInfoValueString;
         } else {
             continue;
         }
         if (valueType == ArgInfoGUI::ArgInfoValueBool)
         {
             argGUI = new ArgInfoGUI(ArgInfoGUI::ArgInfoBinary, ArgInfoGUI::ArgInfoValueBool, this);
         }
         else if (it->options.size() == 0)
         {
             argGUI = new ArgInfoGUI(ArgInfoGUI::ArgInfoContinuous, valueType, this);
         }
         else
         {
             argGUI = new ArgInfoGUI(ArgInfoGUI::ArgInfoDiscrete, valueType, this);
             std::vector<std::string>::const_iterator optionIt = it->options.begin();
             std::vector<std::string>::const_iterator optionNameIt = it->optionNames.begin();
             for (int i = 0; optionIt != it->options.end(); ++optionIt, i++)
             {
                 QString name(optionNameIt == it->optionNames.end() ? optionIt->c_str() : optionNameIt->c_str());
                 if (optionNameIt != it->optionNames.end()) {
                     ++optionNameIt;
                 }
                 if (valueType == ArgInfoGUI::ArgInfoValueInt) {
                     argGUI->addIntValue(name, atoi(optionIt->c_str()));
                 } else if (valueType == ArgInfoGUI::ArgInfoValueFloat) {
                     argGUI->addFloatValue(name, atof(optionIt->c_str()));
                 } else if (valueType == ArgInfoGUI::ArgInfoValueString) {
                     argGUI->addStringValue(name, QString(optionIt->c_str()));
                 }
             }
         }
         if ((it->range.minimum() != 0) || (it->range.maximum() != 0)) {
             argGUI->setRange(it->range.minimum(), it->range.maximum());
         }
         argGUI->setLabel(QString(it->name.size() == 0 ? it->key.c_str() : it->name.c_str()));
         argGUI->setUnits(QString(it->units.c_str()));
         if (it->description.size() != 0) {
             argGUI->setToolTip(QString(it->description.c_str()));
         }
         layout->addWidget(argGUI);
         DynamicArgSettingGUI *gui = new DynamicArgSettingGUI(argGUI, QString(it->key.c_str()));
         // This could be made more elegant but let's make it more simple
         if (deviceArguments)
         {
             m_deviceArgsGUIs.push_back(gui);
             connect(gui, SIGNAL(valueChanged(QString, QVariant)), this, SLOT(deviceArgChanged(QString, QVariant)));
         }
         else
         {
             m_streamArgsGUIs.push_back(gui);
             connect(gui, SIGNAL(valueChanged(QString, QVariant)), this, SLOT(streamArgChanged(QString, QVariant)));
         }
     }
 }
createCorrectionsControl()
void SoapySDRInputGui::createCorrectionsControl () private
Definition at line 268 of file soapysdrinputgui.cpp.
References autoDCCorrectionChanged(), autoIQCorrectionChanged(), dcCorrectionArgumentChanged(), dcCorrectionModuleChanged(), SoapySDRInput::hasDCAutoCorrection(), SoapySDRInput::hasDCCorrectionValue(), SoapySDRInput::hasIQAutoCorrection(), SoapySDRInput::hasIQCorrectionValue(), iqCorrectionArgumentChanged(), iqCorrectionModuleChanged(), m_autoDCCorrection, m_autoIQCorrection, m_dcCorrectionGUI, m_iqCorrectionGUI, m_sampleSource, ComplexFactorGUI::setAutomaticEnable(), ComplexFactorGUI::setLabel(), ComplexFactorGUI::setToolTip(), and ui.
Referenced by SoapySDRInputGui().
 {
     QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
     if (m_sampleSource->hasDCCorrectionValue()) // complex GUI
     {
         m_dcCorrectionGUI = new ComplexFactorGUI(this);
         m_dcCorrectionGUI->setLabel(QString("DC corr"));
         m_dcCorrectionGUI->setToolTip(QString("Hardware DC offset correction"));
         m_dcCorrectionGUI->setAutomaticEnable(m_sampleSource->hasDCAutoCorrection());
         layout->addWidget(m_dcCorrectionGUI);
         connect(m_dcCorrectionGUI, SIGNAL(moduleChanged(double)), this, SLOT(dcCorrectionModuleChanged(double)));
         connect(m_dcCorrectionGUI, SIGNAL(argumentChanged(double)), this, SLOT(dcCorrectionArgumentChanged(double)));
         if (m_sampleSource->hasDCAutoCorrection()) {
             connect(m_dcCorrectionGUI, SIGNAL(automaticChanged(bool)), this, SLOT(autoDCCorrectionChanged(bool)));
         }
     }
     else if (m_sampleSource->hasDCAutoCorrection()) // simple checkbox
     {
         m_autoDCCorrection = new QCheckBox(this);
         m_autoDCCorrection->setText(QString("Auto DC corr"));
         m_autoDCCorrection->setToolTip(QString("Automatic hardware DC offset correction"));
         m_autoDCCorrection->setStyleSheet("QCheckBox::indicator::unchecked {background: rgb(79,79,79);} QCheckBox::indicator::checked {background: rgb(255, 157, 38);}");
         layout->addWidget(m_autoDCCorrection);
         connect(m_autoDCCorrection, SIGNAL(toggled(bool)), this, SLOT(autoDCCorrectionChanged(bool)));
     }
     if (m_sampleSource->hasIQCorrectionValue()) // complex GUI
     {
         m_iqCorrectionGUI = new ComplexFactorGUI(this);
         m_iqCorrectionGUI->setLabel(QString("IQ corr"));
         m_iqCorrectionGUI->setToolTip(QString("Hardware IQ imbalance correction"));
         m_iqCorrectionGUI->setAutomaticEnable(m_sampleSource->hasIQAutoCorrection());
         layout->addWidget(m_iqCorrectionGUI);
         connect(m_iqCorrectionGUI, SIGNAL(moduleChanged(double)), this, SLOT(iqCorrectionModuleChanged(double)));
         connect(m_iqCorrectionGUI, SIGNAL(argumentChanged(double)), this, SLOT(iqCorrectionArgumentChanged(double)));
         if (m_sampleSource->hasIQAutoCorrection()) {
             connect(m_iqCorrectionGUI, SIGNAL(automaticChanged(bool)), this, SLOT(autoIQCorrectionChanged(bool)));
         }
     }
     else if (m_sampleSource->hasIQAutoCorrection()) // simple checkbox
     {
         m_autoIQCorrection = new QCheckBox(this);
         m_autoIQCorrection->setText(QString("Auto IQ corr"));
         m_autoIQCorrection->setToolTip(QString("Automatic hardware IQ imbalance correction"));
         m_autoIQCorrection->setStyleSheet("QCheckBox::indicator::unchecked {background: rgb(79,79,79);} QCheckBox::indicator::checked {background: rgb(255, 157, 38);}");
         layout->addWidget(m_autoIQCorrection);
         connect(m_autoIQCorrection, SIGNAL(toggled(bool)), this, SLOT(autoIQCorrectionChanged(bool)));
     }
 }
createGlobalGainControl()
void SoapySDRInputGui::createGlobalGainControl () private
Definition at line 215 of file soapysdrinputgui.cpp.
References autoGainChanged(), SoapySDRInput::getGlobalGainRange(), globalGainChanged(), SoapySDRInput::isAGCSupported(), m_autoGain, m_gainSliderGUI, m_sampleSource, leansdr::max(), leansdr::min(), IntervalSliderGUI::setInterval(), IntervalSliderGUI::setLabel(), IntervalSliderGUI::setUnits(), and ui.
Referenced by SoapySDRInputGui().
 {
     m_gainSliderGUI = new IntervalSliderGUI(this);
     int min, max;
     m_sampleSource->getGlobalGainRange(min, max);
     m_gainSliderGUI->setInterval(min, max);
     m_gainSliderGUI->setLabel(QString("Global gain"));
     m_gainSliderGUI->setUnits(QString(""));
     QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
     QFrame *line = new QFrame(this);
     line->setFrameShape(QFrame::HLine);
     line->setFrameShadow(QFrame::Sunken);
     layout->addWidget(line);
     if (m_sampleSource->isAGCSupported())
     {
         m_autoGain = new QCheckBox(this);
         m_autoGain->setText(QString("AGC"));
         m_autoGain->setStyleSheet("QCheckBox::indicator::unchecked {background: rgb(79,79,79);} QCheckBox::indicator::checked {background: rgb(255, 157, 38);}");
         layout->addWidget(m_autoGain);
         connect(m_autoGain, SIGNAL(toggled(bool)), this, SLOT(autoGainChanged(bool)));
     }
     layout->addWidget(m_gainSliderGUI);
     connect(m_gainSliderGUI, SIGNAL(valueChanged(double)), this, SLOT(globalGainChanged(double)));
 }
createIndividualGainsControl()
void SoapySDRInputGui::createIndividualGainsControl (const std::vector< DeviceSoapySDRParams::GainSetting > & individualGainsList) private
Definition at line 246 of file soapysdrinputgui.cpp.
References arg(), i, individualGainChanged(), m_individualGainsGUIs, IntervalSliderGUI::setInterval(), IntervalSliderGUI::setLabel(), IntervalSliderGUI::setUnits(), and ui.
Referenced by SoapySDRInputGui().
 {
     if (individualGainsList.size() == 0) { // Leave early if list of individual gains is empty
         return;
     }
     QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
     std::vector<DeviceSoapySDRParams::GainSetting>::const_iterator it = individualGainsList.begin();
     for (int i = 0; it != individualGainsList.end(); ++it, i++)
     {
         IntervalSliderGUI *gainGUI = new IntervalSliderGUI(this);
         gainGUI->setInterval(it->m_range.minimum(), it->m_range.maximum());
         gainGUI->setLabel(QString("%1 gain").arg(it->m_name.c_str()));
         gainGUI->setUnits(QString(""));
         DynamicItemSettingGUI *gui = new DynamicItemSettingGUI(gainGUI, QString(it->m_name.c_str()));
         layout->addWidget(gainGUI);
         m_individualGainsGUIs.push_back(gui);
         connect(m_individualGainsGUIs.back(), SIGNAL(valueChanged(QString, double)), this, SLOT(individualGainChanged(QString, double)));
     }
 }
createRangesControl()
void SoapySDRInputGui::createRangesControl (ItemSettingGUI ** settingGUI, const SoapySDR::RangeList & rangeList, const QString & text, const QString & unit) private
Definition at line 115 of file soapysdrinputgui.cpp.
References IntervalRangeGUI::addInterval(), DiscreteRangeGUI::addItem(), arg(), IntervalRangeGUI::reset(), DiscreteRangeGUI::setLabel(), IntervalRangeGUI::setLabel(), DiscreteRangeGUI::setUnits(), IntervalRangeGUI::setUnits(), and ui.
Referenced by createTunableElementsControl(), and SoapySDRInputGui().
 {
     if (rangeList.size() == 0) { // return early if the range list is empty
         return;
     }
     bool rangeDiscrete = true; // discretes values
     bool rangeInterval = true; // intervals
     for (const auto &it : rangeList)
     {
         if (it.minimum() != it.maximum()) {
             rangeDiscrete = false;
         } else {
             rangeInterval = false;
         }
     }
     if (rangeDiscrete)
     {
         DiscreteRangeGUI *rangeGUI = new DiscreteRangeGUI(this);
         rangeGUI->setLabel(text);
         rangeGUI->setUnits(QString("k%1").arg(unit));
         for (const auto &it : rangeList) {
             rangeGUI->addItem(QString("%1").arg(QString::number(it.minimum()/1000.0, 'f', 0)), it.minimum());
         }
         *settingGUI = rangeGUI;
         QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
         layout->addWidget(rangeGUI);
     }
     else if (rangeInterval)
     {
         IntervalRangeGUI *rangeGUI = new IntervalRangeGUI(ui->scrollAreaWidgetContents);
         rangeGUI->setLabel(text);
         rangeGUI->setUnits(unit);
         for (const auto &it : rangeList) {
             rangeGUI->addInterval(it.minimum(), it.maximum());
         }
         rangeGUI->reset();
         *settingGUI = rangeGUI;
         QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
         layout->addWidget(rangeGUI);
     }
 }
createTunableElementsControl()
void SoapySDRInputGui::createTunableElementsControl (const std::vector< DeviceSoapySDRParams::FrequencySetting > & tunableElementsList) private
Definition at line 189 of file soapysdrinputgui.cpp.
References arg(), createRangesControl(), i, m_tunableElementsGUIs, and tunableElementChanged().
Referenced by SoapySDRInputGui().
 {
     if (tunableElementsList.size() <= 1) { // This list is created for other elements than the main one (RF) which is always at index 0
         return;
     }
     std::vector<DeviceSoapySDRParams::FrequencySetting>::const_iterator it = tunableElementsList.begin() + 1;
     for (int i = 0; it != tunableElementsList.end(); ++it, i++)
     {
         if (it->m_ranges.size() == 0) { // skip empty ranges lists
             continue;
         }
         ItemSettingGUI *rangeGUI;
         createRangesControl(
                 &rangeGUI,
                 it->m_ranges,
                 QString("%1 freq").arg(it->m_name.c_str()),
                 QString((it->m_name == "CORR") ? "ppm" : "Hz"));
         DynamicItemSettingGUI *gui = new DynamicItemSettingGUI(rangeGUI, QString(it->m_name.c_str()));
         m_tunableElementsGUIs.push_back(gui);
         connect(m_tunableElementsGUIs.back(), SIGNAL(valueChanged(QString, double)), this, SLOT(tunableElementChanged(QString, double)));
     }
 }
dcCorrectionArgumentChanged
void SoapySDRInputGui::dcCorrectionArgumentChanged (double value) private slot
Definition at line 612 of file soapysdrinputgui.cpp.
References abs(), SoapySDRInputSettings::m_dcCorrection, M_PI, m_settings, and sendSettings().
Referenced by createCorrectionsControl().
 {
     double angleInRadians = (value / 180.0) * M_PI;
     std::complex<double> dcCorrection = std::polar<double>(abs(m_settings.m_dcCorrection), angleInRadians);
     m_settings.m_dcCorrection = dcCorrection;
     sendSettings();
 }
dcCorrectionModuleChanged
void SoapySDRInputGui::dcCorrectionModuleChanged (double value) private slot
Definition at line 605 of file soapysdrinputgui.cpp.
References arg(), SoapySDRInputSettings::m_dcCorrection, m_settings, and sendSettings().
Referenced by createCorrectionsControl().
 {
     std::complex<double> dcCorrection = std::polar<double>(value, arg(m_settings.m_dcCorrection));
     m_settings.m_dcCorrection = dcCorrection;
     sendSettings();
 }
deserialize()
bool SoapySDRInputGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 452 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if (m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void SoapySDRInputGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 110 of file soapysdrinputgui.cpp.
 {
     delete this;
 }
deviceArgChanged
void SoapySDRInputGui::deviceArgChanged (QString itemName, QVariant value) private slot
Definition at line 641 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::m_deviceArgSettings, m_settings, and sendSettings().
Referenced by createArgumentsControl().
 {
     m_settings.m_deviceArgSettings[itemName] = value;
     sendSettings();
 }
displayCorrectionsSettings()
void SoapySDRInputGui::displayCorrectionsSettings () private
Definition at line 797 of file soapysdrinputgui.cpp.
References abs(), arg(), SoapySDRInputSettings::m_autoDCCorrection, m_autoDCCorrection, SoapySDRInputSettings::m_autoIQCorrection, m_autoIQCorrection, SoapySDRInputSettings::m_dcCorrection, m_dcCorrectionGUI, SoapySDRInputSettings::m_iqCorrection, m_iqCorrectionGUI, M_PI, m_settings, ComplexFactorGUI::setArgument(), ComplexFactorGUI::setAutomatic(), and ComplexFactorGUI::setModule().
Referenced by displaySettings().
 {
     if (m_dcCorrectionGUI)
     {
         m_dcCorrectionGUI->setAutomatic(m_settings.m_autoDCCorrection);
         m_dcCorrectionGUI->setModule(abs(m_settings.m_dcCorrection));
         m_dcCorrectionGUI->setArgument(arg(m_settings.m_dcCorrection)*(180.0/M_PI));
     }
     if (m_iqCorrectionGUI)
     {
         m_iqCorrectionGUI->setAutomatic(m_settings.m_autoIQCorrection);
         m_iqCorrectionGUI->setModule(abs(m_settings.m_iqCorrection));
         m_iqCorrectionGUI->setArgument(arg(m_settings.m_iqCorrection)*(180.0/M_PI));
     }
     if (m_autoDCCorrection) {
         m_autoDCCorrection->setChecked(m_settings.m_autoDCCorrection);
     }
     if (m_autoIQCorrection) {
         m_autoIQCorrection->setChecked(m_settings.m_autoIQCorrection);
     }
 }
displayDeviceArgsSettings()
void SoapySDRInputGui::displayDeviceArgsSettings () private
Definition at line 836 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::m_deviceArgSettings, m_deviceArgsGUIs, and m_settings.
Referenced by displaySettings(), and handleMessage().
 {
     for (const auto &it : m_deviceArgsGUIs)
     {
         QMap<QString, QVariant>::iterator elIt = m_settings.m_deviceArgSettings.find(it->getName());
         if (elIt != m_settings.m_deviceArgSettings.end())
         {
             it->setValue(elIt.value());
             *elIt = it->getValue();
         }
     }
 }
displayIndividualGainsControlSettings()
void SoapySDRInputGui::displayIndividualGainsControlSettings () private
Definition at line 783 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::m_individualGains, m_individualGainsGUIs, and m_settings.
Referenced by displaySettings().
 {
     for (const auto &it : m_individualGainsGUIs)
     {
         QMap<QString, double>::iterator elIt = m_settings.m_individualGains.find(it->getName());
         if (elIt != m_settings.m_individualGains.end())
         {
             it->setValue(*elIt);
             *elIt = it->getValue();
         }
     }
 }
displaySettings()
void SoapySDRInputGui::displaySettings () private
Definition at line 725 of file soapysdrinputgui.cpp.
References arg(), blockApplySettings(), displayCorrectionsSettings(), displayDeviceArgsSettings(), displayIndividualGainsControlSettings(), displayStreamArgsSettings(), displayTunableElementsControlSettings(), ItemSettingGUI::getCurrentValue(), IntervalSliderGUI::getCurrentValue(), SoapySDRInputSettings::m_antenna, m_antennas, SoapySDRInputSettings::m_autoGain, m_autoGain, SoapySDRInputSettings::m_bandwidth, m_bandwidthGUI, SoapySDRInputSettings::m_centerFrequency, SoapySDRInputSettings::m_devSampleRate, SoapySDRInputSettings::m_fcPos, m_gainSliderGUI, SoapySDRInputSettings::m_globalGain, SoapySDRInputSettings::m_log2Decim, SoapySDRInputSettings::m_LOppmTenths, m_sampleRateGUI, m_settings, SoapySDRInputSettings::m_softDCCorrection, SoapySDRInputSettings::m_softIQCorrection, ItemSettingGUI::setValue(), StringRangeGUI::setValue(), IntervalSliderGUI::setValue(), and ui.
Referenced by deserialize(), handleMessage(), resetToDefaults(), setCenterFrequency(), and SoapySDRInputGui().
 {
     blockApplySettings(true);
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     if (m_antennas) {
         m_antennas->setValue(m_settings.m_antenna.toStdString());
     }
     if (m_sampleRateGUI)
     {
         m_sampleRateGUI->setValue(m_settings.m_devSampleRate);
         m_settings.m_devSampleRate = m_sampleRateGUI->getCurrentValue();
     }
     if (m_bandwidthGUI)
     {
         m_bandwidthGUI->setValue(m_settings.m_bandwidth);
         m_settings.m_bandwidth = m_bandwidthGUI->getCurrentValue();
     }
     if (m_gainSliderGUI)
     {
         m_gainSliderGUI->setValue(m_settings.m_globalGain);
         m_settings.m_globalGain = m_gainSliderGUI->getCurrentValue();
     }
     if (m_autoGain) {
         m_autoGain->setChecked(m_settings.m_autoGain);
     }
     ui->dcOffset->setChecked(m_settings.m_softDCCorrection);
     ui->iqImbalance->setChecked(m_settings.m_softIQCorrection);
     ui->decim->setCurrentIndex(m_settings.m_log2Decim);
     ui->fcPos->setCurrentIndex((int) m_settings.m_fcPos);
     ui->LOppm->setValue(m_settings.m_LOppmTenths);
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     displayTunableElementsControlSettings();
     displayIndividualGainsControlSettings();
     displayCorrectionsSettings();
     displayStreamArgsSettings();
     displayDeviceArgsSettings();
     blockApplySettings(false);
 }
displayStreamArgsSettings()
void SoapySDRInputGui::displayStreamArgsSettings () private
Definition at line 822 of file soapysdrinputgui.cpp.
References m_settings, SoapySDRInputSettings::m_streamArgSettings, and m_streamArgsGUIs.
Referenced by displaySettings().
 {
     for (const auto &it : m_streamArgsGUIs)
     {
         QMap<QString, QVariant>::iterator elIt = m_settings.m_streamArgSettings.find(it->getName());
         if (elIt != m_settings.m_streamArgSettings.end())
         {
             it->setValue(elIt.value());
             *elIt = it->getValue();
         }
     }
 }
displayTunableElementsControlSettings()
void SoapySDRInputGui::displayTunableElementsControlSettings () private
Definition at line 771 of file soapysdrinputgui.cpp.
References m_settings, SoapySDRInputSettings::m_tunableElements, and m_tunableElementsGUIs.
Referenced by displaySettings().
 {
     for (const auto &it : m_tunableElementsGUIs)
     {
         QMap<QString, double>::const_iterator elIt = m_settings.m_tunableElements.find(it->getName());
         if (elIt != m_settings.m_tunableElements.end()) {
             it->setValue(*elIt);
         }
     }
 }
getCenterFrequency()
qint64 SoapySDRInputGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 435 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* SoapySDRInputGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 58 of file soapysdrinputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString SoapySDRInputGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 423 of file soapysdrinputgui.cpp.
 {
     return objectName();
 }
globalGainChanged
void SoapySDRInputGui::globalGainChanged (double gain) private slot
Definition at line 575 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::m_globalGain, m_settings, and sendSettings().
Referenced by createGlobalGainControl().
 {
     m_settings.m_globalGain = round(gain);
     sendSettings();
 }
handleInputMessages
void SoapySDRInputGui::handleInputMessages () private slot
Definition at line 521 of file soapysdrinputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by SoapySDRInputGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("SoapySDRInputGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("SoapySDRInputGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool SoapySDRInputGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 468 of file soapysdrinputgui.cpp.
References blockApplySettings(), displayDeviceArgsSettings(), displaySettings(), DeviceSoapySDRShared::MsgReportDeviceArgsChange::getDeviceArgSettings(), SoapySDRInput::MsgReportGainChange::getGlobalGain(), SoapySDRInput::MsgReportGainChange::getIndividualGains(), SoapySDRInput::MsgConfigureSoapySDRInput::getSettings(), SoapySDRInput::MsgReportGainChange::getSettings(), SoapySDRInput::MsgStartStop::getStartStop(), SoapySDRInputSettings::m_deviceArgSettings, SoapySDRInputSettings::m_globalGain, SoapySDRInputSettings::m_individualGains, m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (SoapySDRInput::MsgConfigureSoapySDRInput::match(message))
     {
         const SoapySDRInput::MsgConfigureSoapySDRInput& cfg = (SoapySDRInput::MsgConfigureSoapySDRInput&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (SoapySDRInput::MsgReportGainChange::match(message))
     {
         const SoapySDRInput::MsgReportGainChange& report = (SoapySDRInput::MsgReportGainChange&) message;
         const SoapySDRInputSettings& gainSettings = report.getSettings();
         if (report.getGlobalGain()) {
             m_settings.m_globalGain = gainSettings.m_globalGain;
         }
         if (report.getIndividualGains()) {
             m_settings.m_individualGains = gainSettings.m_individualGains;
         }
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (DeviceSoapySDRShared::MsgReportDeviceArgsChange::match(message))
     {
         DeviceSoapySDRShared::MsgReportDeviceArgsChange& notif = (DeviceSoapySDRShared::MsgReportDeviceArgsChange&) message;
         m_settings.m_deviceArgSettings = notif.getDeviceArgSettings();
         displayDeviceArgsSettings();
         return true;
     }
     else if (SoapySDRInput::MsgStartStop::match(message))
     {
         SoapySDRInput::MsgStartStop& notif = (SoapySDRInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
individualGainChanged
void SoapySDRInputGui::individualGainChanged (QString name, double value) private slot
Definition at line 587 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::m_individualGains, m_settings, and sendSettings().
Referenced by createIndividualGainsControl().
 {
     m_settings.m_individualGains[name] = value;
     sendSettings();
 }
iqCorrectionArgumentChanged
void SoapySDRInputGui::iqCorrectionArgumentChanged (double value) private slot
Definition at line 627 of file soapysdrinputgui.cpp.
References abs(), SoapySDRInputSettings::m_iqCorrection, M_PI, m_settings, and sendSettings().
Referenced by createCorrectionsControl().
 {
     double angleInRadians = (value / 180.0) * M_PI;
     std::complex<double> iqCorrection = std::polar<double>(abs(m_settings.m_iqCorrection), angleInRadians);
     m_settings.m_iqCorrection = iqCorrection;
     sendSettings();
 }
iqCorrectionModuleChanged
void SoapySDRInputGui::iqCorrectionModuleChanged (double value) private slot
Definition at line 620 of file soapysdrinputgui.cpp.
References arg(), SoapySDRInputSettings::m_iqCorrection, m_settings, and sendSettings().
Referenced by createCorrectionsControl().
 {
     std::complex<double> iqCorrection = std::polar<double>(value, arg(m_settings.m_iqCorrection));
     m_settings.m_iqCorrection = iqCorrection;
     sendSettings();
 }
on_centerFrequency_changed
void SoapySDRInputGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 647 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_dcOffset_toggled
void SoapySDRInputGui::on_dcOffset_toggled (bool checked) private slot
Definition at line 653 of file soapysdrinputgui.cpp.
References m_settings, SoapySDRInputSettings::m_softDCCorrection, and sendSettings().
 {
     m_settings.m_softDCCorrection = checked;
     sendSettings();
 }
on_decim_currentIndexChanged
void SoapySDRInputGui::on_decim_currentIndexChanged (int index) private slot
Definition at line 665 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::m_log2Decim, m_settings, and sendSettings().
 {
     if ((index <0) || (index > 6))
         return;
     m_settings.m_log2Decim = index;
     sendSettings();
 }
on_fcPos_currentIndexChanged
void SoapySDRInputGui::on_fcPos_currentIndexChanged (int index) private slot
Definition at line 673 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::FC_POS_CENTER, SoapySDRInputSettings::FC_POS_INFRA, SoapySDRInputSettings::FC_POS_SUPRA, SoapySDRInputSettings::m_fcPos, m_settings, and sendSettings().
 {
     if (index == 0) {
         m_settings.m_fcPos = SoapySDRInputSettings::FC_POS_INFRA;
         sendSettings();
     } else if (index == 1) {
         m_settings.m_fcPos = SoapySDRInputSettings::FC_POS_SUPRA;
         sendSettings();
     } else if (index == 2) {
         m_settings.m_fcPos = SoapySDRInputSettings::FC_POS_CENTER;
         sendSettings();
     }
 }
on_iqImbalance_toggled
void SoapySDRInputGui::on_iqImbalance_toggled (bool checked) private slot
Definition at line 659 of file soapysdrinputgui.cpp.
References m_settings, SoapySDRInputSettings::m_softIQCorrection, and sendSettings().
 {
     m_settings.m_softIQCorrection = checked;
     sendSettings();
 }
on_LOppm_valueChanged
void SoapySDRInputGui::on_LOppm_valueChanged (int value) private slot
Definition at line 697 of file soapysdrinputgui.cpp.
References arg(), SoapySDRInputSettings::m_LOppmTenths, m_settings, sendSettings(), and ui.
 {
     ui->LOppmText->setText(QString("%1").arg(QString::number(value/10.0, 'f', 1)));
     m_settings.m_LOppmTenths = value;
     sendSettings();
 }
on_record_toggled
void SoapySDRInputGui::on_record_toggled (bool checked) private slot
Definition at line 713 of file soapysdrinputgui.cpp.
References SoapySDRInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     SoapySDRInput::MsgFileRecord* message = SoapySDRInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_startStop_toggled
void SoapySDRInputGui::on_startStop_toggled (bool checked) private slot
Definition at line 704 of file soapysdrinputgui.cpp.
References SoapySDRInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         SoapySDRInput::MsgStartStop *message = SoapySDRInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
on_transverter_clicked
void SoapySDRInputGui::on_transverter_clicked () private slot
Definition at line 687 of file soapysdrinputgui.cpp.
References m_settings, SoapySDRInputSettings::m_transverterDeltaFrequency, SoapySDRInputSettings::m_transverterMode, sendSettings(), setCenterFrequencySetting(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("SoapySDRInputGui::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     setCenterFrequencySetting(ui->centerFrequency->getValueNew());
     sendSettings();
 }
openDeviceSettingsDialog
void SoapySDRInputGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 935 of file soapysdrinputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), SoapySDRInputSettings::m_reverseAPIAddress, SoapySDRInputSettings::m_reverseAPIDeviceIndex, SoapySDRInputSettings::m_reverseAPIPort, m_settings, SoapySDRInputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by SoapySDRInputGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void SoapySDRInputGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 428 of file soapysdrinputgui.cpp.
References displaySettings(), m_settings, SoapySDRInputSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sampleRateChanged
void SoapySDRInputGui::sampleRateChanged (double sampleRate) private slot
Definition at line 557 of file soapysdrinputgui.cpp.
References SoapySDRInputSettings::m_devSampleRate, m_settings, and sendSettings().
Referenced by SoapySDRInputGui().
 {
     m_settings.m_devSampleRate = round(sampleRate);
     sendSettings();
 }
sendSettings()
void SoapySDRInputGui::sendSettings () private
Definition at line 850 of file soapysdrinputgui.cpp.
References m_updateTimer.
Referenced by antennasChanged(), autoDCCorrectionChanged(), autoGainChanged(), autoIQCorrectionChanged(), bandwidthChanged(), dcCorrectionArgumentChanged(), dcCorrectionModuleChanged(), deserialize(), deviceArgChanged(), globalGainChanged(), individualGainChanged(), iqCorrectionArgumentChanged(), iqCorrectionModuleChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_iqImbalance_toggled(), on_LOppm_valueChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), sampleRateChanged(), setCenterFrequency(), SoapySDRInputGui(), streamArgChanged(), and tunableElementChanged().
 {
     if (!m_updateTimer.isActive()) {
         m_updateTimer.start(100);
     }
 }
serialize()
QByteArray SoapySDRInputGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 447 of file soapysdrinputgui.cpp.
References m_settings, and SoapySDRInputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void SoapySDRInputGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 440 of file soapysdrinputgui.cpp.
References displaySettings(), SoapySDRInputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setCenterFrequencySetting()
void SoapySDRInputGui::setCenterFrequencySetting (uint64_t kHzValue) private
Definition at line 881 of file soapysdrinputgui.cpp.
References arg(), SoapySDRInputSettings::m_centerFrequency, m_settings, and ui.
Referenced by on_transverter_clicked().
 {
     int64_t centerFrequency = kHzValue*1000;
     m_settings.m_centerFrequency = centerFrequency < 0 ? 0 : (uint64_t) centerFrequency;
     ui->centerFrequency->setToolTip(QString("Main center frequency in kHz (LO: %1 kHz)").arg(centerFrequency/1000));
 }
setName()
void SoapySDRInputGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 418 of file soapysdrinputgui.cpp.
 {
     setObjectName(name);
 }
streamArgChanged
void SoapySDRInputGui::streamArgChanged (QString itemName, QVariant value) private slot
Definition at line 635 of file soapysdrinputgui.cpp.
References m_settings, SoapySDRInputSettings::m_streamArgSettings, and sendSettings().
Referenced by createArgumentsControl().
 {
     m_settings.m_streamArgSettings[itemName] = value;
     sendSettings();
 }
tunableElementChanged
void SoapySDRInputGui::tunableElementChanged (QString name, double value) private slot
Definition at line 569 of file soapysdrinputgui.cpp.
References m_settings, SoapySDRInputSettings::m_tunableElements, and sendSettings().
Referenced by createTunableElementsControl().
 {
     m_settings.m_tunableElements[name] = value;
     sendSettings();
 }
updateFrequencyLimits()
void SoapySDRInputGui::updateFrequencyLimits () private
Definition at line 864 of file soapysdrinputgui.cpp.
References SoapySDRInput::getFrequencyRange(), m_sampleSource, m_settings, SoapySDRInputSettings::m_transverterDeltaFrequency, SoapySDRInputSettings::m_transverterMode, and ui.
Referenced by on_transverter_clicked().
 {
     // values in kHz
     uint64_t f_min, f_max;
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     m_sampleSource->getFrequencyRange(f_min, f_max);
     qint64 minLimit = f_min/1000 + deltaFrequency;
     qint64 maxLimit = f_max/1000 + deltaFrequency;
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("SoapySDRInputGui::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void SoapySDRInputGui::updateHardware () private slot
Definition at line 894 of file soapysdrinputgui.cpp.
References SoapySDRInput::MsgConfigureSoapySDRInput::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by SoapySDRInputGui().
 {
     if (m_doApplySettings)
     {
         qDebug() << "SoapySDRInputGui::updateHardware";
         SoapySDRInput::MsgConfigureSoapySDRInput* message = SoapySDRInput::MsgConfigureSoapySDRInput::create(m_settings, m_forceSettings);
         m_sampleSource->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void SoapySDRInputGui::updateSampleRateAndFrequency () private
Definition at line 857 of file soapysdrinputgui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_sampleRate / 1000.0f, 'g', 5)));
 }
updateStatus
void SoapySDRInputGui::updateStatus () private slot
Definition at line 906 of file soapysdrinputgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by SoapySDRInputGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_antennas
StringRangeGUI* SoapySDRInputGui::m_antennas private
Definition at line 88 of file soapysdrinputgui.h.
Referenced by antennasChanged(), createAntennasControl(), and displaySettings().
m_autoDCCorrection
QCheckBox* SoapySDRInputGui::m_autoDCCorrection private
Definition at line 97 of file soapysdrinputgui.h.
Referenced by createCorrectionsControl(), and displayCorrectionsSettings().
m_autoGain
QCheckBox* SoapySDRInputGui::m_autoGain private
Definition at line 94 of file soapysdrinputgui.h.
Referenced by createGlobalGainControl(), and displaySettings().
m_autoIQCorrection
QCheckBox* SoapySDRInputGui::m_autoIQCorrection private
Definition at line 98 of file soapysdrinputgui.h.
Referenced by createCorrectionsControl(), and displayCorrectionsSettings().
m_bandwidthGUI
ItemSettingGUI* SoapySDRInputGui::m_bandwidthGUI private
Definition at line 90 of file soapysdrinputgui.h.
Referenced by displaySettings(), and SoapySDRInputGui().
m_dcCorrectionGUI
ComplexFactorGUI* SoapySDRInputGui::m_dcCorrectionGUI private
Definition at line 95 of file soapysdrinputgui.h.
Referenced by createCorrectionsControl(), and displayCorrectionsSettings().
m_deviceArgsGUIs
std::vector<DynamicArgSettingGUI*> SoapySDRInputGui::m_deviceArgsGUIs private
Definition at line 100 of file soapysdrinputgui.h.
Referenced by createArgumentsControl(), and displayDeviceArgsSettings().
m_deviceCenterFrequency
quint64 SoapySDRInputGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 84 of file soapysdrinputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* SoapySDRInputGui::m_deviceUISet private
Definition at line 76 of file soapysdrinputgui.h.
Referenced by SoapySDRInputGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool SoapySDRInputGui::m_doApplySettings private
Definition at line 78 of file soapysdrinputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_forceSettings
bool SoapySDRInputGui::m_forceSettings private
Definition at line 77 of file soapysdrinputgui.h.
Referenced by deserialize(), and updateHardware().
m_gainSliderGUI
IntervalSliderGUI* SoapySDRInputGui::m_gainSliderGUI private
Definition at line 92 of file soapysdrinputgui.h.
Referenced by createGlobalGainControl(), and displaySettings().
m_individualGainsGUIs
std::vector<DynamicItemSettingGUI*> SoapySDRInputGui::m_individualGainsGUIs private
Definition at line 93 of file soapysdrinputgui.h.
Referenced by createIndividualGainsControl(), and displayIndividualGainsControlSettings().
m_inputMessageQueue
MessageQueue SoapySDRInputGui::m_inputMessageQueue private
Definition at line 86 of file soapysdrinputgui.h.
Referenced by handleInputMessages(), and SoapySDRInputGui().
m_iqCorrectionGUI
ComplexFactorGUI* SoapySDRInputGui::m_iqCorrectionGUI private
Definition at line 96 of file soapysdrinputgui.h.
Referenced by createCorrectionsControl(), and displayCorrectionsSettings().
m_lastEngineState
int SoapySDRInputGui::m_lastEngineState private
Definition at line 85 of file soapysdrinputgui.h.
Referenced by updateStatus().
m_sampleRate
int SoapySDRInputGui::m_sampleRate private
Definition at line 83 of file soapysdrinputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateGUI
ItemSettingGUI* SoapySDRInputGui::m_sampleRateGUI private
Definition at line 89 of file soapysdrinputgui.h.
Referenced by displaySettings(), and SoapySDRInputGui().
m_sampleSource
SoapySDRInput* SoapySDRInputGui::m_sampleSource private
Definition at line 82 of file soapysdrinputgui.h.
Referenced by createCorrectionsControl(), createGlobalGainControl(), on_record_toggled(), on_startStop_toggled(), SoapySDRInputGui(), updateFrequencyLimits(), and updateHardware().
m_settings
SoapySDRInputSettings SoapySDRInputGui::m_settings private
Definition at line 79 of file soapysdrinputgui.h.
Referenced by antennasChanged(), autoDCCorrectionChanged(), autoGainChanged(), autoIQCorrectionChanged(), bandwidthChanged(), dcCorrectionArgumentChanged(), dcCorrectionModuleChanged(), deserialize(), deviceArgChanged(), displayCorrectionsSettings(), displayDeviceArgsSettings(), displayIndividualGainsControlSettings(), displaySettings(), displayStreamArgsSettings(), displayTunableElementsControlSettings(), getCenterFrequency(), globalGainChanged(), handleMessage(), individualGainChanged(), iqCorrectionArgumentChanged(), iqCorrectionModuleChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_iqImbalance_toggled(), on_LOppm_valueChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), sampleRateChanged(), serialize(), setCenterFrequency(), setCenterFrequencySetting(), SoapySDRInputGui(), streamArgChanged(), tunableElementChanged(), updateFrequencyLimits(), and updateHardware().
m_statusTimer
QTimer SoapySDRInputGui::m_statusTimer private
Definition at line 81 of file soapysdrinputgui.h.
Referenced by SoapySDRInputGui().
m_streamArgsGUIs
std::vector<DynamicArgSettingGUI*> SoapySDRInputGui::m_streamArgsGUIs private
Definition at line 99 of file soapysdrinputgui.h.
Referenced by createArgumentsControl(), and displayStreamArgsSettings().
m_tunableElementsGUIs
std::vector<DynamicItemSettingGUI*> SoapySDRInputGui::m_tunableElementsGUIs private
Definition at line 91 of file soapysdrinputgui.h.
Referenced by createTunableElementsControl(), and displayTunableElementsControlSettings().
m_updateTimer
QTimer SoapySDRInputGui::m_updateTimer private
Definition at line 80 of file soapysdrinputgui.h.
Referenced by sendSettings(), SoapySDRInputGui(), and updateHardware().
ui
Ui::SoapySDRInputGui* SoapySDRInputGui::ui private
Definition at line 74 of file soapysdrinputgui.h.
Referenced by createAntennasControl(), createArgumentsControl(), createCorrectionsControl(), createGlobalGainControl(), createIndividualGainsControl(), createRangesControl(), displaySettings(), handleMessage(), on_LOppm_valueChanged(), on_record_toggled(), on_transverter_clicked(), setCenterFrequencySetting(), SoapySDRInputGui(), updateFrequencyLimits(), updateSampleRateAndFrequency(), updateStatus(), and ~SoapySDRInputGui().
The documentation for this class was generated from the following files:
plugins/samplesource/soapysdrinput/soapysdrinputgui.h
plugins/samplesource/soapysdrinput/soapysdrinputgui.cpp