SDRAngel: SWGSDRangel::SWGNamedEnum Class Reference
SWGSDRangel::SWGNamedEnum Class Reference
#include <SWGNamedEnum.h>
Public Member Functions
SWGNamedEnum ()
SWGNamedEnum (QString *json)
virtual ~SWGNamedEnum ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGNamedEnum * fromJson (QString &jsonString) override
QString * getName ()
void setName (QString *name)
qint32 getValue ()
void setValue (qint32 value)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * name
bool m_name_isSet
qint32 value
bool m_value_isSet
Detailed Description
Definition at line 32 of file SWGNamedEnum.h.
Constructor & Destructor Documentation
SWGNamedEnum() [1/2]
SWGSDRangel::SWGNamedEnum::SWGNamedEnum ()
Definition at line 30 of file SWGNamedEnum.cpp.
References m_name_isSet, m_value_isSet, name, and value.
{
     name = nullptr;
     m_name_isSet = false;
     value = 0;
     m_value_isSet = false;
 }
SWGNamedEnum() [2/2]
SWGSDRangel::SWGNamedEnum::SWGNamedEnum (QString * json)
Definition at line 25 of file SWGNamedEnum.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGNamedEnum()
SWGSDRangel::SWGNamedEnum::~SWGNamedEnum () virtual
Definition at line 37 of file SWGNamedEnum.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGNamedEnum::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 75 of file SWGNamedEnum.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGNamedEnum::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 86 of file SWGNamedEnum.cpp.
References m_value_isSet, name, SWGSDRangel::toJsonValue(), and value.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(name != nullptr && *name != QString("")){
         toJsonValue(QString("name"), name, obj, QString("QString"));
     }
     if(m_value_isSet){
         obj->insert("value", QJsonValue(value));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGNamedEnum::cleanup ()
Definition at line 50 of file SWGNamedEnum.cpp.
References name.
Referenced by ~SWGNamedEnum().
                       {
     if(name != nullptr) {
         delete name;
     }
 }
fromJson()
SWGNamedEnum * SWGSDRangel::SWGNamedEnum::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 58 of file SWGNamedEnum.cpp.
References fromJsonObject().
Referenced by SWGNamedEnum().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGNamedEnum::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 67 of file SWGNamedEnum.cpp.
References name, SWGSDRangel::setValue(), and value.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&name, pJson["name"], "QString", "QString");
     ::SWGSDRangel::setValue(&value, pJson["value"], "qint32", "");
 }
getName()
QString * SWGSDRangel::SWGNamedEnum::getName ()
Definition at line 99 of file SWGNamedEnum.cpp.
References name.
                       {
     return name;
 }
getValue()
qint32 SWGSDRangel::SWGNamedEnum::getValue ()
Definition at line 109 of file SWGNamedEnum.cpp.
References value.
{
     return value;
 }
init()
void SWGSDRangel::SWGNamedEnum::init ()
Definition at line 42 of file SWGNamedEnum.cpp.
References m_name_isSet, m_value_isSet, name, and value.
Referenced by SWGNamedEnum().
                    {
     name = new QString("");
     m_name_isSet = false;
     value = 0;
     m_value_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGNamedEnum::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 120 of file SWGNamedEnum.cpp.
References m_value_isSet, and name.
                    {
     bool isObjectUpdated = false;
     do{
         if(name != nullptr && *name != QString("")){ isObjectUpdated = true; break;}
         if(m_value_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setName()
void SWGSDRangel::SWGNamedEnum::setName (QString * name)
Definition at line 103 of file SWGNamedEnum.cpp.
References m_name_isSet, and name.
{
     this->name = name;
     this->m_name_isSet = true;
 }
setValue()
void SWGSDRangel::SWGNamedEnum::setValue (qint32 value)
Definition at line 113 of file SWGNamedEnum.cpp.
References m_value_isSet, and value.
{
     this->value = value;
     this->m_value_isSet = true;
 }
Member Data Documentation
m_name_isSet
bool SWGSDRangel::SWGNamedEnum::m_name_isSet private
Definition at line 56 of file SWGNamedEnum.h.
Referenced by init(), setName(), and SWGNamedEnum().
m_value_isSet
bool SWGSDRangel::SWGNamedEnum::m_value_isSet private
Definition at line 59 of file SWGNamedEnum.h.
Referenced by asJsonObject(), init(), isSet(), setValue(), and SWGNamedEnum().
name
QString* SWGSDRangel::SWGNamedEnum::name private
Definition at line 55 of file SWGNamedEnum.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getName(), init(), isSet(), setName(), and SWGNamedEnum().
value
qint32 SWGSDRangel::SWGNamedEnum::value private
Definition at line 58 of file SWGNamedEnum.h.
Referenced by asJsonObject(), fromJsonObject(), getValue(), init(), setValue(), and SWGNamedEnum().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGNamedEnum.h
swagger/sdrangel/code/qt5/client/SWGNamedEnum.cpp