SDRAngel: AMBEEngine Class Reference
AMBEEngine Class Reference
#include <ambeengine.h>
Inherits QObject.
Classes
struct AMBEController
Public Member Functions
AMBEEngine ()
~AMBEEngine ()
void scan (std::vector< QString > &ambeDevices)
void releaseAll ()
int getNbDevices () const
number of devices used
void getDeviceRefs (std::vector< QString > &devicesRefs)
reference of the devices used (device path or url)
bool registerController (const std::string &deviceRef)
create a new controller for the device in reference
void releaseController (const std::string &deviceRef)
release controller resources for the device in reference
void pushMbeFrame (const unsigned char *mbeFrame, int mbeRateIndex, int mbeVolumeIndex, unsigned char channels, bool useHP, int upsampling, AudioFifo *audioFifo)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
Private Member Functions
void getComList ()
Static Private Member Functions
static std::string get_driver (const std::string &tty)
static void register_comport (std::vector< std::string > &comList, std::vector< std::string > &comList8250, const std::string &dir)
static void probe_serial8250_comports (std::vector< std::string > &comList, std::vector< std::string > comList8250)
Private Attributes
std::vector< AMBEController > m_controllers
std::vector< std::string > m_comList
std::vector< std::string > m_comList8250
QMutex m_mutex
Detailed Description
Definition at line 36 of file ambeengine.h.
Constructor & Destructor Documentation
AMBEEngine()
AMBEEngine::AMBEEngine ()
Definition at line 46 of file ambeengine.cpp.
 {}
~AMBEEngine()
AMBEEngine::~AMBEEngine ()
Definition at line 49 of file ambeengine.cpp.
References getComList(), i, m_comList, m_comList8250, m_controllers, and scan().
 {
     qDebug("AMBEEngine::~AMBEEngine: %lu controllers", m_controllers.size());
 }
Member Function Documentation
deserialize()
bool AMBEEngine::deserialize (const QByteArray & data)
Definition at line 355 of file ambeengine.cpp.
References i, registerController(), and releaseAll().
Referenced by MainSettings::load().
 {
     if (data.size() <= 0)
     {
         qDebug("AMBEEngine::deserialize: invalid or no data");
         return false;
     }
     QStringList qDeviceList;
     QDataStream *stream = new QDataStream(data);
     (*stream) >> qDeviceList;
     delete stream;
     releaseAll();
     for (int i = 0; i < qDeviceList.size(); ++i)
     {
         qDebug(" AMBEEngine::deserialize: %s", qDeviceList.at(i).toStdString().c_str());
         registerController(qDeviceList.at(i).toStdString());
     }
     return true;
 }
get_driver()
std::string AMBEEngine::get_driver (const std::string & tty) static private
Definition at line 168 of file ambeengine.cpp.
Referenced by register_comport().
 {
     struct stat st;
     std::string devicedir = tty;
     // Append '/device' to the tty-path
     devicedir += "/device";
     // Stat the devicedir and handle it if it is a symlink
     if (lstat(devicedir.c_str(), &st) == 0 && S_ISLNK(st.st_mode))
     {
         char buffer[1024];
         memset(buffer, 0, sizeof(buffer));
         // Append '/driver' and return basename of the target
         devicedir += "/driver";
         if (readlink(devicedir.c_str(), buffer, sizeof(buffer)) > 0) {
             return basename(buffer);
         }
     }
     return "";
 }
getComList()
void AMBEEngine::getComList () private
Definition at line 74 of file ambeengine.cpp.
References m_comList, m_comList8250, probe_serial8250_comports(), and register_comport().
Referenced by scan(), and ~AMBEEngine().
 {
     int n;
     struct dirent **namelist;
     m_comList.clear();
     m_comList8250.clear();
     const char* sysdir = "/sys/class/tty/";
     // Scan through /sys/class/tty - it contains all tty-devices in the system
     n = scandir(sysdir, &namelist, NULL, alphasort);
     if (n < 0)
     {
         perror("scandir");
     }
     else
     {
         while (n--)
         {
             if (strcmp(namelist[n]->d_name, "..") && strcmp(namelist[n]->d_name, "."))
             {
                 // Construct full absolute file path
                 std::string devicedir = sysdir;
                 devicedir += namelist[n]->d_name;
                 // Register the device
                 register_comport(m_comList, m_comList8250, devicedir);
             }
             free(namelist[n]);
         }
         free(namelist);
     }
     // Only non-serial8250 has been added to comList without any further testing
     // serial8250-devices must be probe to check for validity
     probe_serial8250_comports(m_comList, m_comList8250);
 }
getDeviceRefs()
void AMBEEngine::getDeviceRefs (std::vector< QString > & devicesRefs)
reference of the devices used (device path or url)
Definition at line 279 of file ambeengine.cpp.
References m_controllers.
Referenced by DSPEngine::getDVSerialNames(), and AMBEDevicesDialog::refreshInUseList().
 {
     std::vector<AMBEController>::const_iterator it = m_controllers.begin();
     while (it != m_controllers.end())
     {
         deviceNames.push_back(QString(it->device.c_str()));
         ++it;
     }
 }
getNbDevices()
int AMBEEngine::getNbDevices () const inline
number of devices used
Definition at line 46 of file ambeengine.h.
Referenced by DSPEngine::hasDVSerialSupport().
probe_serial8250_comports()
void AMBEEngine::probe_serial8250_comports (std::vector< std::string > & comList, std::vector< std::string > comList8250) static private
Definition at line 137 of file ambeengine.cpp.
Referenced by getComList().
 {
     struct serial_struct serinfo;
     std::vector<std::string>::iterator it = comList8250.begin();
     // Iterate over all serial8250-devices
     while (it != comList8250.end())
     {
         // Try to open the device
         int fd = open((*it).c_str(), O_RDWR | O_NONBLOCK | O_NOCTTY);
         if (fd >= 0)
         {
             // Get serial_info
             if (ioctl(fd, TIOCGSERIAL, &serinfo) == 0)
             {
                 // If device type is no PORT_UNKNOWN we accept the port
                 if (serinfo.type != PORT_UNKNOWN) {
                     comList.push_back(*it);
                 }
             }
             close(fd);
         }
         it++;
     }
 }
pushMbeFrame()
void AMBEEngine::pushMbeFrame (const unsigned char * mbeFrame, int mbeRateIndex, int mbeVolumeIndex, unsigned char channels, bool useHP, int upsampling, AudioFifo * audioFifo)
Definition at line 290 of file ambeengine.cpp.
References m_controllers, and m_mutex.
Referenced by DSPEngine::pushMbeFrame().
 {
     std::vector<AMBEController>::iterator it = m_controllers.begin();
     std::vector<AMBEController>::iterator itAvail = m_controllers.end();
     bool done = false;
     QMutexLocker locker(&m_mutex);
     while (it != m_controllers.end())
     {
         if (it->worker->hasFifo(audioFifo))
         {
             it->worker->pushMbeFrame(mbeFrame, mbeRateIndex, mbeVolumeIndex, channels, useLP, upsampling, audioFifo);
             done = true;
         }
         else if (it->worker->isAvailable())
         {
             itAvail = it;
         }
         ++it;
     }
     if (!done)
     {
         if (itAvail != m_controllers.end())
         {
             int wNum = itAvail - m_controllers.begin();
             qDebug("AMBEEngine::pushMbeFrame: push %p on empty queue %d", audioFifo, wNum);
             itAvail->worker->pushMbeFrame(mbeFrame, mbeRateIndex, mbeVolumeIndex, channels, useLP, upsampling, audioFifo);
         }
         else
         {
             qDebug("AMBEEngine::pushMbeFrame: no DV device available. MBE frame dropped");
         }
     }
 }
register_comport()
void AMBEEngine::register_comport (std::vector< std::string > & comList, std::vector< std::string > & comList8250, const std::string & dir) static private
Definition at line 114 of file ambeengine.cpp.
References get_driver().
Referenced by getComList().
 {
     // Get the driver the device is using
     std::string driver = get_driver(dir);
     // Skip devices without a driver
     if (driver.size() > 0)
     {
         //std::cerr << "register_comport: dir: "<< dir << " driver: " << driver << std::endl;
         std::string devfile = std::string("/dev/") + basename((char *) dir.c_str());
         // Put serial8250-devices in a seperate list
         if (driver == "serial8250") {
             comList8250.push_back(devfile);
         } else {
             comList.push_back(devfile);
         }
     }
 }
registerController()
bool AMBEEngine::registerController (const std::string & deviceRef)
create a new controller for the device in reference
Definition at line 214 of file ambeengine.cpp.
References m_controllers, and AMBEWorker::open().
Referenced by deserialize(), WebAPIAdapterSrv::instanceAMBEDevicesPatch(), WebAPIAdapterGUI::instanceAMBEDevicesPatch(), WebAPIAdapterGUI::instanceAMBEDevicesPut(), WebAPIAdapterSrv::instanceAMBEDevicesPut(), AMBEDevicesDialog::on_importAddress_clicked(), AMBEDevicesDialog::on_importAllSerial_clicked(), and AMBEDevicesDialog::on_importSerial_clicked().
 {
     AMBEWorker *worker = new AMBEWorker();
     if (worker->open(deviceRef))
     {
         m_controllers.push_back(AMBEController());
         m_controllers.back().worker = worker;
         m_controllers.back().thread = new QThread();
         m_controllers.back().device = deviceRef;
         m_controllers.back().worker->moveToThread(m_controllers.back().thread);
         connect(m_controllers.back().worker, SIGNAL(finished()), m_controllers.back().thread, SLOT(quit()));
         connect(m_controllers.back().worker, SIGNAL(finished()), m_controllers.back().worker, SLOT(deleteLater()));
         connect(m_controllers.back().thread, SIGNAL(finished()), m_controllers.back().thread, SLOT(deleteLater()));
         connect(&m_controllers.back().worker->m_inputMessageQueue, SIGNAL(messageEnqueued()), m_controllers.back().worker, SLOT(handleInputMessages()));
         std::this_thread::sleep_for(std::chrono::seconds(1));
         m_controllers.back().thread->start();
         return true;
     }
     return false;
 }
releaseAll()
void AMBEEngine::releaseAll ()
Definition at line 261 of file ambeengine.cpp.
References m_controllers.
Referenced by deserialize(), WebAPIAdapterSrv::instanceAMBEDevicesDelete(), WebAPIAdapterGUI::instanceAMBEDevicesDelete(), WebAPIAdapterSrv::instanceAMBEDevicesPut(), WebAPIAdapterGUI::instanceAMBEDevicesPut(), and AMBEDevicesDialog::on_clearAmbeList_clicked().
 {
     std::vector<AMBEController>::iterator it = m_controllers.begin();
     while (it != m_controllers.end())
     {
         disconnect(&it->worker->m_inputMessageQueue, SIGNAL(messageEnqueued()), it->worker, SLOT(handleInputMessages()));
         it->worker->stop();
         it->thread->wait(100);
         it->worker->m_inputMessageQueue.clear();
         it->worker->close();
         qDebug() << "AMBEEngine::release: closed device at: " << it->device.c_str();
         ++it;
     }
     m_controllers.clear();
 }
releaseController()
void AMBEEngine::releaseController (const std::string & deviceRef)
release controller resources for the device in reference
Definition at line 239 of file ambeengine.cpp.
References m_controllers.
Referenced by WebAPIAdapterGUI::instanceAMBEDevicesPatch(), WebAPIAdapterSrv::instanceAMBEDevicesPatch(), and AMBEDevicesDialog::on_removeAmbeDevice_clicked().
 {
     std::vector<AMBEController>::iterator it = m_controllers.begin();
     while (it != m_controllers.end())
     {
         if (it->device == deviceRef)
         {
             disconnect(&it->worker->m_inputMessageQueue, SIGNAL(messageEnqueued()), it->worker, SLOT(handleInputMessages()));
             it->worker->stop();
             it->thread->wait(100);
             it->worker->m_inputMessageQueue.clear();
             it->worker->close();
             qDebug() << "AMBEEngine::releaseController: closed device at: " << it->device.c_str();
             m_controllers.erase(it);
             break;
         }
         ++it;
     }
 }
scan()
void AMBEEngine::scan (std::vector< QString > & ambeDevices)
Definition at line 191 of file ambeengine.cpp.
References AMBEWorker::close(), getComList(), m_comList, and AMBEWorker::open().
Referenced by WebAPIAdapterGUI::instanceAMBESerialGet(), WebAPIAdapterSrv::instanceAMBESerialGet(), AMBEDevicesDialog::populateSerialList(), MainBench::testAMBE(), and ~AMBEEngine().
 {
     getComList();
     std::vector<std::string>::const_iterator it = m_comList.begin();
     ambeDevices.clear();
     while (it != m_comList.end())
     {
         AMBEWorker *worker = new AMBEWorker();
         qDebug("AMBEEngine::scan: com: %s", it->c_str());
         if (worker->open(*it))
         {
             ambeDevices.push_back(QString(it->c_str()));
             worker->close();
         }
         delete worker;
         ++it;
     }
 }
serialize()
QByteArray AMBEEngine::serialize () const
Definition at line 335 of file ambeengine.cpp.
References m_controllers.
Referenced by MainSettings::save().
 {
     QStringList qDeviceList;
     std::vector<AMBEController>::const_iterator it = m_controllers.begin();
     while (it != m_controllers.end())
     {
         qDebug("AMBEEngine::serialize: %s", it->device.c_str());
         qDeviceList << QString(it->device.c_str());
         ++it;
     }
     QByteArray data;
     QDataStream *stream = new QDataStream(&data, QIODevice::WriteOnly);
     (*stream) << qDeviceList;
     delete stream;
     return data;
 }
Member Data Documentation
m_comList
std::vector<std::string> AMBEEngine::m_comList private
Definition at line 84 of file ambeengine.h.
Referenced by getComList(), scan(), and ~AMBEEngine().
m_comList8250
std::vector<std::string> AMBEEngine::m_comList8250 private
Definition at line 85 of file ambeengine.h.
Referenced by getComList(), and ~AMBEEngine().
m_controllers
std::vector<AMBEController> AMBEEngine::m_controllers private
Definition at line 83 of file ambeengine.h.
Referenced by getDeviceRefs(), pushMbeFrame(), registerController(), releaseAll(), releaseController(), serialize(), and ~AMBEEngine().
m_mutex
QMutex AMBEEngine::m_mutex private
Definition at line 86 of file ambeengine.h.
Referenced by pushMbeFrame().
The documentation for this class was generated from the following files:
sdrbase/ambe/ambeengine.h
sdrbase/ambe/ambeengine.cpp