SDRAngel: SoapySDROutputGui Class Reference
SoapySDROutputGui Class Reference
#include <soapysdroutputgui.h>
Public Member Functions
SoapySDROutputGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~SoapySDROutputGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void antennasChanged ()
void sampleRateChanged (double sampleRate)
void bandwidthChanged (double bandwidth)
void tunableElementChanged (QString name, double value)
void globalGainChanged (double gain)
void autoGainChanged (bool set)
void individualGainChanged (QString name, double value)
void autoDCCorrectionChanged (bool set)
void autoIQCorrectionChanged (bool set)
void dcCorrectionModuleChanged (double value)
void dcCorrectionArgumentChanged (double value)
void iqCorrectionModuleChanged (double value)
void iqCorrectionArgumentChanged (double value)
void streamArgChanged (QString itemName, QVariant value)
void deviceArgChanged (QString itemName, QVariant value)
void on_centerFrequency_changed (quint64 value)
void on_LOppm_valueChanged (int value)
void on_interp_currentIndexChanged (int index)
void on_transverter_clicked ()
void on_startStop_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void createRangesControl (ItemSettingGUI **settingGUI, const SoapySDR::RangeList &rangeList, const QString &text, const QString &unit)
void createAntennasControl (const std::vector< std::string > &antennaList)
void createTunableElementsControl (const std::vector< DeviceSoapySDRParams::FrequencySetting > &tunableElementsList)
void createGlobalGainControl ()
void createIndividualGainsControl (const std::vector< DeviceSoapySDRParams::GainSetting > &individualGainsList)
void createCorrectionsControl ()
void createArgumentsControl (const SoapySDR::ArgInfoList &argInfoList, bool deviceArguments)
void blockApplySettings (bool block)
void displaySettings ()
void displayTunableElementsControlSettings ()
void displayIndividualGainsControlSettings ()
void displayCorrectionsSettings ()
void displayStreamArgsSettings ()
void displayDeviceArgsSettings ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void updateFrequencyLimits ()
void setCenterFrequencySetting (uint64_t kHzValue)
Private Attributes
Ui::SoapySDROutputGui * ui
DeviceUISet * m_deviceUISet
bool m_forceSettings
bool m_doApplySettings
SoapySDROutputSettings m_settings
QTimer m_updateTimer
QTimer m_statusTimer
SoapySDROutput * m_sampleSink
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
StringRangeGUI * m_antennas
ItemSettingGUI * m_sampleRateGUI
ItemSettingGUI * m_bandwidthGUI
std::vector< DynamicItemSettingGUI * > m_tunableElementsGUIs
IntervalSliderGUI * m_gainSliderGUI
std::vector< DynamicItemSettingGUI * > m_individualGainsGUIs
QCheckBox * m_autoGain
ComplexFactorGUI * m_dcCorrectionGUI
ComplexFactorGUI * m_iqCorrectionGUI
QCheckBox * m_autoDCCorrection
QCheckBox * m_autoIQCorrection
std::vector< DynamicArgSettingGUI * > m_streamArgsGUIs
std::vector< DynamicArgSettingGUI * > m_deviceArgsGUIs
Detailed Description
Definition at line 44 of file soapysdroutputgui.h.
Constructor & Destructor Documentation
SoapySDROutputGui()
SoapySDROutputGui::SoapySDROutputGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 41 of file soapysdroutputgui.cpp.
References bandwidthChanged(), createAntennasControl(), createArgumentsControl(), createCorrectionsControl(), createGlobalGainControl(), createIndividualGainsControl(), createRangesControl(), createTunableElementsControl(), displaySettings(), SoapySDROutput::getAntennas(), SoapySDROutput::getBandwidthRanges(), SoapySDROutput::getDeviceArgInfoList(), SoapySDROutput::getFrequencyRange(), SoapySDROutput::getIndividualGainsRanges(), SoapySDROutput::getRateRanges(), DeviceAPI::getSampleSink(), SoapySDROutput::getStreamArgInfoList(), SoapySDROutput::getTunableElements(), ColorMapper::GrayGold, handleInputMessages(), SoapySDROutput::initDeviceArgSettings(), SoapySDROutput::initGainSettings(), SoapySDROutput::initStreamArgSettings(), SoapySDROutput::initTunableElementsSettings(), m_bandwidthGUI, DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_sampleRateGUI, m_sampleSink, m_settings, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), sampleRateChanged(), sendSettings(), SoapySDROutput::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                                               :
     QWidget(parent),
     ui(new Ui::SoapySDROutputGui),
     m_deviceUISet(deviceUISet),
     m_forceSettings(true),
     m_doApplySettings(true),
     m_sampleSink(0),
     m_sampleRate(0),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_antennas(0),
     m_sampleRateGUI(0),
     m_bandwidthGUI(0),
     m_gainSliderGUI(0),
     m_autoGain(0),
     m_dcCorrectionGUI(0),
     m_iqCorrectionGUI(0),
     m_autoDCCorrection(0),
     m_autoIQCorrection(0)
 {
     m_sampleSink = (SoapySDROutput*) m_deviceUISet->m_deviceAPI->getSampleSink();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     uint64_t f_min, f_max;
     m_sampleSink->getFrequencyRange(f_min, f_max);
     ui->centerFrequency->setValueRange(7, f_min/1000, f_max/1000);
     createCorrectionsControl();
     createAntennasControl(m_sampleSink->getAntennas());
     createRangesControl(&m_sampleRateGUI, m_sampleSink->getRateRanges(), "SR", "S/s");
     createRangesControl(&m_bandwidthGUI, m_sampleSink->getBandwidthRanges(), "BW", "Hz");
     createTunableElementsControl(m_sampleSink->getTunableElements());
     createGlobalGainControl();
     createIndividualGainsControl(m_sampleSink->getIndividualGainsRanges());
     createArgumentsControl(m_sampleSink->getDeviceArgInfoList(), true);
     createArgumentsControl(m_sampleSink->getStreamArgInfoList(), false);
     m_sampleSink->initGainSettings(m_settings);
     m_sampleSink->initTunableElementsSettings(m_settings);
     m_sampleSink->initStreamArgSettings(m_settings);
     m_sampleSink->initDeviceArgSettings(m_settings);
     if (m_sampleRateGUI) {
         connect(m_sampleRateGUI, SIGNAL(valueChanged(double)), this, SLOT(sampleRateChanged(double)));
     }
     if (m_bandwidthGUI) {
         connect(m_bandwidthGUI, SIGNAL(valueChanged(double)), this, SLOT(bandwidthChanged(double)));
     }
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSink->setMessageQueueToGUI(&m_inputMessageQueue);
     sendSettings();
 }
~SoapySDROutputGui()
SoapySDROutputGui::~SoapySDROutputGui () virtual
Definition at line 104 of file soapysdroutputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
antennasChanged
void SoapySDROutputGui::antennasChanged () private slot
Definition at line 553 of file soapysdroutputgui.cpp.
References StringRangeGUI::getCurrentValue(), SoapySDROutputSettings::m_antenna, m_antennas, m_settings, and sendSettings().
Referenced by createAntennasControl().
 {
     const std::string& antennaStr = m_antennas->getCurrentValue();
     m_settings.m_antenna = QString(antennaStr.c_str());
     sendSettings();
 }
autoDCCorrectionChanged
void SoapySDROutputGui::autoDCCorrectionChanged (bool set) private slot
Definition at line 590 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::m_autoDCCorrection, m_settings, and sendSettings().
Referenced by createCorrectionsControl().
 {
     m_settings.m_autoDCCorrection = set;
     sendSettings();
 }
autoGainChanged
void SoapySDROutputGui::autoGainChanged (bool set) private slot
Definition at line 578 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::m_autoGain, m_settings, and sendSettings().
Referenced by createGlobalGainControl().
 {
     m_settings.m_autoGain = set;
     sendSettings();
 }
autoIQCorrectionChanged
void SoapySDROutputGui::autoIQCorrectionChanged (bool set) private slot
Definition at line 596 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::m_autoIQCorrection, m_settings, and sendSettings().
Referenced by createCorrectionsControl().
 {
     m_settings.m_autoIQCorrection = set;
     sendSettings();
 }
bandwidthChanged
void SoapySDROutputGui::bandwidthChanged (double bandwidth) private slot
Definition at line 560 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::m_bandwidth, m_settings, and sendSettings().
Referenced by SoapySDROutputGui().
 {
     m_settings.m_bandwidth = round(bandwidth);
     sendSettings();
 }
blockApplySettings()
void SoapySDROutputGui::blockApplySettings (bool block) inline private
Definition at line 104 of file soapysdroutputgui.h.
Referenced by displaySettings(), and handleMessage().
 { m_doApplySettings = !block; }
createAntennasControl()
void SoapySDROutputGui::createAntennasControl (const std::vector< std::string > & antennaList) private
Definition at line 168 of file soapysdroutputgui.cpp.
References StringRangeGUI::addItem(), antennasChanged(), m_antennas, StringRangeGUI::setLabel(), StringRangeGUI::setUnits(), and ui.
Referenced by SoapySDROutputGui().
 {
     if (antennaList.size() == 0) { // return early if the antenna list is empty
         return;
     }
     m_antennas = new StringRangeGUI(this);
     m_antennas->setLabel(QString("RF out"));
     m_antennas->setUnits(QString("Port"));
     for (const auto &it : antennaList) {
         m_antennas->addItem(QString(it.c_str()), it);
     }
     QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
     layout->addWidget(m_antennas);
     connect(m_antennas, SIGNAL(valueChanged()), this, SLOT(antennasChanged()));
 }
createArgumentsControl()
void SoapySDROutputGui::createArgumentsControl (const SoapySDR::ArgInfoList & argInfoList, bool deviceArguments) private
Definition at line 322 of file soapysdroutputgui.cpp.
References ArgInfoGUI::addFloatValue(), ArgInfoGUI::addIntValue(), ArgInfoGUI::addStringValue(), ArgInfoGUI::ArgInfoBinary, ArgInfoGUI::ArgInfoContinuous, ArgInfoGUI::ArgInfoDiscrete, ArgInfoGUI::ArgInfoValueBool, ArgInfoGUI::ArgInfoValueFloat, ArgInfoGUI::ArgInfoValueInt, ArgInfoGUI::ArgInfoValueString, deviceArgChanged(), i, m_deviceArgsGUIs, m_streamArgsGUIs, ArgInfoGUI::setLabel(), ArgInfoGUI::setRange(), ArgInfoGUI::setToolTip(), ArgInfoGUI::setUnits(), streamArgChanged(), and ui.
Referenced by SoapySDROutputGui().
 {
     if (argInfoList.size() == 0) { // return early if list is empty
         return;
     }
     QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
     QFrame *line = new QFrame(this);
     line->setFrameShape(QFrame::HLine);
     line->setFrameShadow(QFrame::Sunken);
     layout->addWidget(line);
     std::vector<SoapySDR::ArgInfo>::const_iterator it = argInfoList.begin();
     for (; it != argInfoList.end(); ++it)
     {
         ArgInfoGUI::ArgInfoValueType valueType;
         ArgInfoGUI *argGUI;
         if (it->type == SoapySDR::ArgInfo::BOOL) {
             valueType = ArgInfoGUI::ArgInfoValueBool;
         } else if (it->type == SoapySDR::ArgInfo::INT) {
             valueType = ArgInfoGUI::ArgInfoValueInt;
         } else if (it->type == SoapySDR::ArgInfo::FLOAT) {
             valueType = ArgInfoGUI::ArgInfoValueFloat;
         } else if (it->type == SoapySDR::ArgInfo::STRING) {
             valueType = ArgInfoGUI::ArgInfoValueString;
         } else {
             continue;
         }
         if (valueType == ArgInfoGUI::ArgInfoValueBool)
         {
             argGUI = new ArgInfoGUI(ArgInfoGUI::ArgInfoBinary, ArgInfoGUI::ArgInfoValueBool, this);
         }
         else if (it->options.size() == 0)
         {
             argGUI = new ArgInfoGUI(ArgInfoGUI::ArgInfoContinuous, valueType, this);
         }
         else
         {
             argGUI = new ArgInfoGUI(ArgInfoGUI::ArgInfoDiscrete, valueType, this);
             std::vector<std::string>::const_iterator optionIt = it->options.begin();
             std::vector<std::string>::const_iterator optionNameIt = it->optionNames.begin();
             for (int i = 0; optionIt != it->options.end(); ++optionIt, i++)
             {
                 QString name(optionNameIt == it->optionNames.end() ? optionIt->c_str() : optionNameIt->c_str());
                 if (optionNameIt != it->optionNames.end()) {
                     ++optionNameIt;
                 }
                 if (valueType == ArgInfoGUI::ArgInfoValueInt) {
                     argGUI->addIntValue(name, atoi(optionIt->c_str()));
                 } else if (valueType == ArgInfoGUI::ArgInfoValueFloat) {
                     argGUI->addFloatValue(name, atof(optionIt->c_str()));
                 } else if (valueType == ArgInfoGUI::ArgInfoValueString) {
                     argGUI->addStringValue(name, QString(optionIt->c_str()));
                 }
             }
         }
         if ((it->range.minimum() != 0) || (it->range.maximum() != 0)) {
             argGUI->setRange(it->range.minimum(), it->range.maximum());
         }
         argGUI->setLabel(QString(it->name.size() == 0 ? it->key.c_str() : it->name.c_str()));
         argGUI->setUnits(QString(it->units.c_str()));
         if (it->description.size() != 0) {
             argGUI->setToolTip(QString(it->description.c_str()));
         }
         layout->addWidget(argGUI);
         DynamicArgSettingGUI *gui = new DynamicArgSettingGUI(argGUI, QString(it->key.c_str()));
         // This could be made more elegant but let's make it more simple
         if (deviceArguments)
         {
             m_deviceArgsGUIs.push_back(gui);
             connect(gui, SIGNAL(valueChanged(QString, QVariant)), this, SLOT(deviceArgChanged(QString, QVariant)));
         }
         else
         {
             m_streamArgsGUIs.push_back(gui);
             connect(gui, SIGNAL(valueChanged(QString, QVariant)), this, SLOT(streamArgChanged(QString, QVariant)));
         }
     }
 }
createCorrectionsControl()
void SoapySDROutputGui::createCorrectionsControl () private
Definition at line 267 of file soapysdroutputgui.cpp.
References autoDCCorrectionChanged(), autoIQCorrectionChanged(), dcCorrectionArgumentChanged(), dcCorrectionModuleChanged(), SoapySDROutput::hasDCAutoCorrection(), SoapySDROutput::hasDCCorrectionValue(), SoapySDROutput::hasIQAutoCorrection(), SoapySDROutput::hasIQCorrectionValue(), iqCorrectionArgumentChanged(), iqCorrectionModuleChanged(), m_autoDCCorrection, m_autoIQCorrection, m_dcCorrectionGUI, m_iqCorrectionGUI, m_sampleSink, ComplexFactorGUI::setAutomaticEnable(), ComplexFactorGUI::setLabel(), and ui.
Referenced by SoapySDROutputGui().
 {
     QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
     if (m_sampleSink->hasDCCorrectionValue()) // complex GUI
     {
         m_dcCorrectionGUI = new ComplexFactorGUI(this);
         m_dcCorrectionGUI->setLabel(QString("DC"));
         m_dcCorrectionGUI->setAutomaticEnable(m_sampleSink->hasDCAutoCorrection());
         layout->addWidget(m_dcCorrectionGUI);
         connect(m_dcCorrectionGUI, SIGNAL(moduleChanged(double)), this, SLOT(dcCorrectionModuleChanged(double)));
         connect(m_dcCorrectionGUI, SIGNAL(argumentChanged(double)), this, SLOT(dcCorrectionArgumentChanged(double)));
         if (m_sampleSink->hasDCAutoCorrection()) {
             connect(m_dcCorrectionGUI, SIGNAL(automaticChanged(bool)), this, SLOT(autoDCCorrectionChanged(bool)));
         }
     }
     else if (m_sampleSink->hasDCAutoCorrection()) // simple checkbox
     {
         m_autoDCCorrection = new QCheckBox(this);
         m_autoDCCorrection->setText(QString("Auto DC corr"));
         m_autoDCCorrection->setToolTip(QString("Automatic hardware DC offset correction"));
         m_autoDCCorrection->setStyleSheet("QCheckBox::indicator::unchecked {background: rgb(79,79,79);} QCheckBox::indicator::checked {background: rgb(255, 157, 38);}");
         layout->addWidget(m_autoDCCorrection);
         connect(m_autoDCCorrection, SIGNAL(toggled(bool)), this, SLOT(autoDCCorrectionChanged(bool)));
     }
     if (m_sampleSink->hasIQCorrectionValue()) // complex GUI
     {
         m_iqCorrectionGUI = new ComplexFactorGUI(this);
         m_iqCorrectionGUI->setLabel(QString("IQ"));
         m_iqCorrectionGUI->setAutomaticEnable(m_sampleSink->hasIQAutoCorrection());
         layout->addWidget(m_iqCorrectionGUI);
         connect(m_iqCorrectionGUI, SIGNAL(moduleChanged(double)), this, SLOT(iqCorrectionModuleChanged(double)));
         connect(m_iqCorrectionGUI, SIGNAL(argumentChanged(double)), this, SLOT(iqCorrectionArgumentChanged(double)));
         if (m_sampleSink->hasIQAutoCorrection()) {
             connect(m_iqCorrectionGUI, SIGNAL(automaticChanged(bool)), this, SLOT(autoIQCorrectionChanged(bool)));
         }
     }
     else if (m_sampleSink->hasIQAutoCorrection()) // simple checkbox
     {
         m_autoIQCorrection = new QCheckBox(this);
         m_autoIQCorrection->setText(QString("Auto IQ corr"));
         m_autoIQCorrection->setToolTip(QString("Automatic hardware IQ imbalance correction"));
         m_autoIQCorrection->setStyleSheet("QCheckBox::indicator::unchecked {background: rgb(79,79,79);} QCheckBox::indicator::checked {background: rgb(255, 157, 38);}");
         layout->addWidget(m_autoIQCorrection);
         connect(m_autoIQCorrection, SIGNAL(toggled(bool)), this, SLOT(autoIQCorrectionChanged(bool)));
     }
 }
createGlobalGainControl()
void SoapySDROutputGui::createGlobalGainControl () private
Definition at line 214 of file soapysdroutputgui.cpp.
References autoGainChanged(), SoapySDROutput::getGlobalGainRange(), globalGainChanged(), SoapySDROutput::isAGCSupported(), m_autoGain, m_gainSliderGUI, m_sampleSink, leansdr::max(), leansdr::min(), IntervalSliderGUI::setInterval(), IntervalSliderGUI::setLabel(), IntervalSliderGUI::setUnits(), and ui.
Referenced by SoapySDROutputGui().
 {
     m_gainSliderGUI = new IntervalSliderGUI(this);
     int min, max;
     m_sampleSink->getGlobalGainRange(min, max);
     m_gainSliderGUI->setInterval(min, max);
     m_gainSliderGUI->setLabel(QString("Global gain"));
     m_gainSliderGUI->setUnits(QString(""));
     QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
     QFrame *line = new QFrame(this);
     line->setFrameShape(QFrame::HLine);
     line->setFrameShadow(QFrame::Sunken);
     layout->addWidget(line);
     if (m_sampleSink->isAGCSupported())
     {
         m_autoGain = new QCheckBox(this);
         m_autoGain->setText(QString("AGC"));
         m_autoGain->setStyleSheet("QCheckBox::indicator::unchecked {background: rgb(79,79,79);} QCheckBox::indicator::checked {background: rgb(255, 157, 38);}");
         layout->addWidget(m_autoGain);
         connect(m_autoGain, SIGNAL(toggled(bool)), this, SLOT(autoGainChanged(bool)));
     }
     layout->addWidget(m_gainSliderGUI);
     connect(m_gainSliderGUI, SIGNAL(valueChanged(double)), this, SLOT(globalGainChanged(double)));
 }
createIndividualGainsControl()
void SoapySDROutputGui::createIndividualGainsControl (const std::vector< DeviceSoapySDRParams::GainSetting > & individualGainsList) private
Definition at line 245 of file soapysdroutputgui.cpp.
References arg(), i, individualGainChanged(), m_individualGainsGUIs, IntervalSliderGUI::setInterval(), IntervalSliderGUI::setLabel(), IntervalSliderGUI::setUnits(), and ui.
Referenced by SoapySDROutputGui().
 {
     if (individualGainsList.size() == 0) { // Leave early if list of individual gains is empty
         return;
     }
     QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
     std::vector<DeviceSoapySDRParams::GainSetting>::const_iterator it = individualGainsList.begin();
     for (int i = 0; it != individualGainsList.end(); ++it, i++)
     {
         IntervalSliderGUI *gainGUI = new IntervalSliderGUI(this);
         gainGUI->setInterval(it->m_range.minimum(), it->m_range.maximum());
         gainGUI->setLabel(QString("%1 gain").arg(it->m_name.c_str()));
         gainGUI->setUnits(QString(""));
         DynamicItemSettingGUI *gui = new DynamicItemSettingGUI(gainGUI, QString(it->m_name.c_str()));
         layout->addWidget(gainGUI);
         m_individualGainsGUIs.push_back(gui);
         connect(m_individualGainsGUIs.back(), SIGNAL(valueChanged(QString, double)), this, SLOT(individualGainChanged(QString, double)));
     }
 }
createRangesControl()
void SoapySDROutputGui::createRangesControl (ItemSettingGUI ** settingGUI, const SoapySDR::RangeList & rangeList, const QString & text, const QString & unit) private
Definition at line 114 of file soapysdroutputgui.cpp.
References IntervalRangeGUI::addInterval(), DiscreteRangeGUI::addItem(), arg(), IntervalRangeGUI::reset(), DiscreteRangeGUI::setLabel(), IntervalRangeGUI::setLabel(), DiscreteRangeGUI::setUnits(), IntervalRangeGUI::setUnits(), and ui.
Referenced by createTunableElementsControl(), and SoapySDROutputGui().
 {
     if (rangeList.size() == 0) { // return early if the range list is empty
         return;
     }
     bool rangeDiscrete = true; // discretes values
     bool rangeInterval = true; // intervals
     for (const auto &it : rangeList)
     {
         if (it.minimum() != it.maximum()) {
             rangeDiscrete = false;
         } else {
             rangeInterval = false;
         }
     }
     if (rangeDiscrete)
     {
         DiscreteRangeGUI *rangeGUI = new DiscreteRangeGUI(this);
         rangeGUI->setLabel(text);
         rangeGUI->setUnits(QString("k%1").arg(unit));
         for (const auto &it : rangeList) {
             rangeGUI->addItem(QString("%1").arg(QString::number(it.minimum()/1000.0, 'f', 0)), it.minimum());
         }
         *settingGUI = rangeGUI;
         QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
         layout->addWidget(rangeGUI);
     }
     else if (rangeInterval)
     {
         IntervalRangeGUI *rangeGUI = new IntervalRangeGUI(this);
         rangeGUI->setLabel(text);
         rangeGUI->setUnits(unit);
         for (const auto &it : rangeList) {
             rangeGUI->addInterval(it.minimum(), it.maximum());
         }
         rangeGUI->reset();
         *settingGUI = rangeGUI;
         QVBoxLayout *layout = (QVBoxLayout *) ui->scrollAreaWidgetContents->layout();
         layout->addWidget(rangeGUI);
     }
 }
createTunableElementsControl()
void SoapySDROutputGui::createTunableElementsControl (const std::vector< DeviceSoapySDRParams::FrequencySetting > & tunableElementsList) private
Definition at line 188 of file soapysdroutputgui.cpp.
References arg(), createRangesControl(), i, m_tunableElementsGUIs, and tunableElementChanged().
Referenced by SoapySDROutputGui().
 {
     if (tunableElementsList.size() <= 1) { // This list is created for other elements than the main one (RF) which is always at index 0
         return;
     }
     std::vector<DeviceSoapySDRParams::FrequencySetting>::const_iterator it = tunableElementsList.begin() + 1;
     for (int i = 0; it != tunableElementsList.end(); ++it, i++)
     {
         if (it->m_ranges.size() == 0) { // skip empty ranges lists
             continue;
         }
         ItemSettingGUI *rangeGUI;
         createRangesControl(
                 &rangeGUI,
                 it->m_ranges,
                 QString("%1 freq").arg(it->m_name.c_str()),
                 QString((it->m_name == "CORR") ? "ppm" : "Hz"));
         DynamicItemSettingGUI *gui = new DynamicItemSettingGUI(rangeGUI, QString(it->m_name.c_str()));
         m_tunableElementsGUIs.push_back(gui);
         connect(m_tunableElementsGUIs.back(), SIGNAL(valueChanged(QString, double)), this, SLOT(tunableElementChanged(QString, double)));
     }
 }
dcCorrectionArgumentChanged
void SoapySDROutputGui::dcCorrectionArgumentChanged (double value) private slot
Definition at line 609 of file soapysdroutputgui.cpp.
References abs(), SoapySDROutputSettings::m_dcCorrection, M_PI, m_settings, and sendSettings().
Referenced by createCorrectionsControl().
 {
     double angleInRadians = (value / 180.0) * M_PI;
     std::complex<double> dcCorrection = std::polar<double>(abs(m_settings.m_dcCorrection), angleInRadians);
     m_settings.m_dcCorrection = dcCorrection;
     sendSettings();
 }
dcCorrectionModuleChanged
void SoapySDROutputGui::dcCorrectionModuleChanged (double value) private slot
Definition at line 602 of file soapysdroutputgui.cpp.
References arg(), SoapySDROutputSettings::m_dcCorrection, m_settings, and sendSettings().
Referenced by createCorrectionsControl().
 {
     std::complex<double> dcCorrection = std::polar<double>(value, arg(m_settings.m_dcCorrection));
     m_settings.m_dcCorrection = dcCorrection;
     sendSettings();
 }
deserialize()
bool SoapySDROutputGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 449 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void SoapySDROutputGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 109 of file soapysdroutputgui.cpp.
 {
     delete this;
 }
deviceArgChanged
void SoapySDROutputGui::deviceArgChanged (QString itemName, QVariant value) private slot
Definition at line 638 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::m_deviceArgSettings, m_settings, and sendSettings().
Referenced by createArgumentsControl().
 {
     m_settings.m_deviceArgSettings[itemName] = value;
     sendSettings();
 }
displayCorrectionsSettings()
void SoapySDROutputGui::displayCorrectionsSettings () private
Definition at line 752 of file soapysdroutputgui.cpp.
References abs(), arg(), SoapySDROutputSettings::m_autoDCCorrection, m_autoDCCorrection, SoapySDROutputSettings::m_autoIQCorrection, m_autoIQCorrection, SoapySDROutputSettings::m_dcCorrection, m_dcCorrectionGUI, SoapySDROutputSettings::m_iqCorrection, m_iqCorrectionGUI, M_PI, m_settings, ComplexFactorGUI::setArgument(), ComplexFactorGUI::setAutomatic(), and ComplexFactorGUI::setModule().
Referenced by displaySettings().
 {
     if (m_dcCorrectionGUI)
     {
         m_dcCorrectionGUI->setAutomatic(m_settings.m_autoDCCorrection);
         m_dcCorrectionGUI->setModule(abs(m_settings.m_dcCorrection));
         m_dcCorrectionGUI->setArgument(arg(m_settings.m_dcCorrection)*(180.0/M_PI));
     }
     if (m_iqCorrectionGUI)
     {
         m_iqCorrectionGUI->setAutomatic(m_settings.m_autoIQCorrection);
         m_iqCorrectionGUI->setModule(abs(m_settings.m_iqCorrection));
         m_iqCorrectionGUI->setArgument(arg(m_settings.m_iqCorrection)*(180.0/M_PI));
     }
     if (m_autoDCCorrection) {
         m_autoDCCorrection->setChecked(m_settings.m_autoDCCorrection);
     }
     if (m_autoIQCorrection) {
         m_autoIQCorrection->setChecked(m_settings.m_autoIQCorrection);
     }
 }
displayDeviceArgsSettings()
void SoapySDROutputGui::displayDeviceArgsSettings () private
Definition at line 791 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::m_deviceArgSettings, m_deviceArgsGUIs, and m_settings.
Referenced by displaySettings(), and handleMessage().
 {
     for (const auto &it : m_deviceArgsGUIs)
     {
         QMap<QString, QVariant>::iterator elIt = m_settings.m_deviceArgSettings.find(it->getName());
         if (elIt != m_settings.m_deviceArgSettings.end())
         {
             it->setValue(elIt.value());
             *elIt = it->getValue();
         }
     }
 }
displayIndividualGainsControlSettings()
void SoapySDROutputGui::displayIndividualGainsControlSettings () private
Definition at line 738 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::m_individualGains, m_individualGainsGUIs, and m_settings.
Referenced by displaySettings().
 {
     for (const auto &it : m_individualGainsGUIs)
     {
         QMap<QString, double>::iterator elIt = m_settings.m_individualGains.find(it->getName());
         if (elIt != m_settings.m_individualGains.end())
         {
             it->setValue(*elIt);
             *elIt = it->getValue();
         }
     }
 }
displaySettings()
void SoapySDROutputGui::displaySettings () private
Definition at line 684 of file soapysdroutputgui.cpp.
References arg(), blockApplySettings(), displayCorrectionsSettings(), displayDeviceArgsSettings(), displayIndividualGainsControlSettings(), displayStreamArgsSettings(), displayTunableElementsControlSettings(), ItemSettingGUI::getCurrentValue(), IntervalSliderGUI::getCurrentValue(), SoapySDROutputSettings::m_antenna, m_antennas, SoapySDROutputSettings::m_autoGain, m_autoGain, SoapySDROutputSettings::m_bandwidth, m_bandwidthGUI, SoapySDROutputSettings::m_centerFrequency, SoapySDROutputSettings::m_devSampleRate, m_gainSliderGUI, SoapySDROutputSettings::m_globalGain, SoapySDROutputSettings::m_log2Interp, SoapySDROutputSettings::m_LOppmTenths, m_sampleRateGUI, m_settings, ItemSettingGUI::setValue(), StringRangeGUI::setValue(), IntervalSliderGUI::setValue(), and ui.
Referenced by deserialize(), handleMessage(), resetToDefaults(), setCenterFrequency(), and SoapySDROutputGui().
 {
     blockApplySettings(true);
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     if (m_antennas) {
         m_antennas->setValue(m_settings.m_antenna.toStdString());
     }
     if (m_sampleRateGUI)
     {
         m_sampleRateGUI->setValue(m_settings.m_devSampleRate);
         m_settings.m_devSampleRate = m_sampleRateGUI->getCurrentValue();
     }
     if (m_bandwidthGUI)
     {
         m_bandwidthGUI->setValue(m_settings.m_bandwidth);
         m_settings.m_bandwidth = m_bandwidthGUI->getCurrentValue();
     }
     if (m_gainSliderGUI)
     {
         m_gainSliderGUI->setValue(m_settings.m_globalGain);
         m_settings.m_globalGain = m_gainSliderGUI->getCurrentValue();
     }
     if (m_autoGain) {
         m_autoGain->setChecked(m_settings.m_autoGain);
     }
     ui->interp->setCurrentIndex(m_settings.m_log2Interp);
     ui->LOppm->setValue(m_settings.m_LOppmTenths);
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     displayTunableElementsControlSettings();
     displayIndividualGainsControlSettings();
     displayCorrectionsSettings();
     displayStreamArgsSettings();
     displayDeviceArgsSettings();
     blockApplySettings(false);
 }
displayStreamArgsSettings()
void SoapySDROutputGui::displayStreamArgsSettings () private
Definition at line 777 of file soapysdroutputgui.cpp.
References m_settings, SoapySDROutputSettings::m_streamArgSettings, and m_streamArgsGUIs.
Referenced by displaySettings().
 {
     for (const auto &it : m_streamArgsGUIs)
     {
         QMap<QString, QVariant>::iterator elIt = m_settings.m_streamArgSettings.find(it->getName());
         if (elIt != m_settings.m_streamArgSettings.end())
         {
             it->setValue(elIt.value());
             *elIt = it->getValue();
         }
     }
 }
displayTunableElementsControlSettings()
void SoapySDROutputGui::displayTunableElementsControlSettings () private
Definition at line 726 of file soapysdroutputgui.cpp.
References m_settings, SoapySDROutputSettings::m_tunableElements, and m_tunableElementsGUIs.
Referenced by displaySettings().
 {
     for (const auto &it : m_tunableElementsGUIs)
     {
         QMap<QString, double>::const_iterator elIt = m_settings.m_tunableElements.find(it->getName());
         if (elIt != m_settings.m_tunableElements.end()) {
             it->setValue(*elIt);
         }
     }
 }
getCenterFrequency()
qint64 SoapySDROutputGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 432 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* SoapySDROutputGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 60 of file soapysdroutputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString SoapySDROutputGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 420 of file soapysdroutputgui.cpp.
 {
     return objectName();
 }
globalGainChanged
void SoapySDROutputGui::globalGainChanged (double gain) private slot
Definition at line 572 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::m_globalGain, m_settings, and sendSettings().
Referenced by createGlobalGainControl().
 {
     m_settings.m_globalGain = round(gain);
     sendSettings();
 }
handleInputMessages
void SoapySDROutputGui::handleInputMessages () private slot
Definition at line 519 of file soapysdroutputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by SoapySDROutputGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("SoapySDROutputGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("SoapySDROutputGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool SoapySDROutputGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 466 of file soapysdroutputgui.cpp.
References blockApplySettings(), displayDeviceArgsSettings(), displaySettings(), DeviceSoapySDRShared::MsgReportDeviceArgsChange::getDeviceArgSettings(), SoapySDROutput::MsgReportGainChange::getGlobalGain(), SoapySDROutput::MsgReportGainChange::getIndividualGains(), SoapySDROutput::MsgConfigureSoapySDROutput::getSettings(), SoapySDROutput::MsgReportGainChange::getSettings(), SoapySDROutput::MsgStartStop::getStartStop(), SoapySDROutputSettings::m_deviceArgSettings, SoapySDROutputSettings::m_globalGain, SoapySDROutputSettings::m_individualGains, m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (SoapySDROutput::MsgConfigureSoapySDROutput::match(message))
     {
         const SoapySDROutput::MsgConfigureSoapySDROutput& cfg = (SoapySDROutput::MsgConfigureSoapySDROutput&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (SoapySDROutput::MsgReportGainChange::match(message))
     {
         const SoapySDROutput::MsgReportGainChange& report = (SoapySDROutput::MsgReportGainChange&) message;
         const SoapySDROutputSettings& gainSettings = report.getSettings();
         if (report.getGlobalGain()) {
             m_settings.m_globalGain = gainSettings.m_globalGain;
         }
         if (report.getIndividualGains()) {
             m_settings.m_individualGains = gainSettings.m_individualGains;
         }
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (DeviceSoapySDRShared::MsgReportDeviceArgsChange::match(message))
     {
         DeviceSoapySDRShared::MsgReportDeviceArgsChange& notif = (DeviceSoapySDRShared::MsgReportDeviceArgsChange&) message;
         m_settings.m_deviceArgSettings = notif.getDeviceArgSettings();
         displayDeviceArgsSettings();
         return true;
     }
     else if (SoapySDROutput::MsgStartStop::match(message))
     {
         SoapySDROutput::MsgStartStop& notif = (SoapySDROutput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
individualGainChanged
void SoapySDROutputGui::individualGainChanged (QString name, double value) private slot
Definition at line 584 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::m_individualGains, m_settings, and sendSettings().
Referenced by createIndividualGainsControl().
 {
     m_settings.m_individualGains[name] = value;
     sendSettings();
 }
iqCorrectionArgumentChanged
void SoapySDROutputGui::iqCorrectionArgumentChanged (double value) private slot
Definition at line 624 of file soapysdroutputgui.cpp.
References abs(), SoapySDROutputSettings::m_iqCorrection, M_PI, m_settings, and sendSettings().
Referenced by createCorrectionsControl().
 {
     double angleInRadians = (value / 180.0) * M_PI;
     std::complex<double> iqCorrection = std::polar<double>(abs(m_settings.m_iqCorrection), angleInRadians);
     m_settings.m_iqCorrection = iqCorrection;
     sendSettings();
 }
iqCorrectionModuleChanged
void SoapySDROutputGui::iqCorrectionModuleChanged (double value) private slot
Definition at line 617 of file soapysdroutputgui.cpp.
References arg(), SoapySDROutputSettings::m_iqCorrection, m_settings, and sendSettings().
Referenced by createCorrectionsControl().
 {
     std::complex<double> iqCorrection = std::polar<double>(value, arg(m_settings.m_iqCorrection));
     m_settings.m_iqCorrection = iqCorrection;
     sendSettings();
 }
on_centerFrequency_changed
void SoapySDROutputGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 644 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_interp_currentIndexChanged
void SoapySDROutputGui::on_interp_currentIndexChanged (int index) private slot
Definition at line 650 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::m_log2Interp, m_settings, and sendSettings().
 {
     if ((index <0) || (index > 6))
         return;
     m_settings.m_log2Interp = index;
     sendSettings();
 }
on_LOppm_valueChanged
void SoapySDROutputGui::on_LOppm_valueChanged (int value) private slot
Definition at line 668 of file soapysdroutputgui.cpp.
References arg(), SoapySDROutputSettings::m_LOppmTenths, m_settings, sendSettings(), and ui.
 {
     ui->LOppmText->setText(QString("%1").arg(QString::number(value/10.0, 'f', 1)));
     m_settings.m_LOppmTenths = value;
     sendSettings();
 }
on_startStop_toggled
void SoapySDROutputGui::on_startStop_toggled (bool checked) private slot
Definition at line 675 of file soapysdroutputgui.cpp.
References SoapySDROutput::MsgStartStop::create(), DeviceSampleSink::getInputMessageQueue(), m_doApplySettings, m_sampleSink, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         SoapySDROutput::MsgStartStop *message = SoapySDROutput::MsgStartStop::create(checked);
         m_sampleSink->getInputMessageQueue()->push(message);
     }
 }
on_transverter_clicked
void SoapySDROutputGui::on_transverter_clicked () private slot
Definition at line 658 of file soapysdroutputgui.cpp.
References m_settings, SoapySDROutputSettings::m_transverterDeltaFrequency, SoapySDROutputSettings::m_transverterMode, sendSettings(), setCenterFrequencySetting(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("SoapySDROutputGui::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     setCenterFrequencySetting(ui->centerFrequency->getValueNew());
     sendSettings();
 }
openDeviceSettingsDialog
void SoapySDROutputGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 885 of file soapysdroutputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), SoapySDROutputSettings::m_reverseAPIAddress, SoapySDROutputSettings::m_reverseAPIDeviceIndex, SoapySDROutputSettings::m_reverseAPIPort, m_settings, SoapySDROutputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by SoapySDROutputGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void SoapySDROutputGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 425 of file soapysdroutputgui.cpp.
References displaySettings(), m_settings, SoapySDROutputSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sampleRateChanged
void SoapySDROutputGui::sampleRateChanged (double sampleRate) private slot
Definition at line 547 of file soapysdroutputgui.cpp.
References SoapySDROutputSettings::m_devSampleRate, m_settings, and sendSettings().
Referenced by SoapySDROutputGui().
 {
     m_settings.m_devSampleRate = round(sampleRate);
     sendSettings();
 }
sendSettings()
void SoapySDROutputGui::sendSettings () private
Definition at line 805 of file soapysdroutputgui.cpp.
References m_updateTimer.
Referenced by antennasChanged(), autoDCCorrectionChanged(), autoGainChanged(), autoIQCorrectionChanged(), bandwidthChanged(), dcCorrectionArgumentChanged(), dcCorrectionModuleChanged(), deserialize(), deviceArgChanged(), globalGainChanged(), individualGainChanged(), iqCorrectionArgumentChanged(), iqCorrectionModuleChanged(), on_centerFrequency_changed(), on_interp_currentIndexChanged(), on_LOppm_valueChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), sampleRateChanged(), setCenterFrequency(), SoapySDROutputGui(), streamArgChanged(), and tunableElementChanged().
 {
     if (!m_updateTimer.isActive()) {
         m_updateTimer.start(100);
     }
 }
serialize()
QByteArray SoapySDROutputGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 444 of file soapysdroutputgui.cpp.
References m_settings, and SoapySDROutputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void SoapySDROutputGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 437 of file soapysdroutputgui.cpp.
References displaySettings(), SoapySDROutputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setCenterFrequencySetting()
void SoapySDROutputGui::setCenterFrequencySetting (uint64_t kHzValue) private
Definition at line 836 of file soapysdroutputgui.cpp.
References arg(), SoapySDROutputSettings::m_centerFrequency, m_settings, and ui.
Referenced by on_transverter_clicked().
 {
     int64_t centerFrequency = kHzValue*1000;
     m_settings.m_centerFrequency = centerFrequency < 0 ? 0 : (uint64_t) centerFrequency;
     ui->centerFrequency->setToolTip(QString("Main center frequency in kHz (LO: %1 kHz)").arg(centerFrequency/1000));
 }
setName()
void SoapySDROutputGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 415 of file soapysdroutputgui.cpp.
 {
     setObjectName(name);
 }
streamArgChanged
void SoapySDROutputGui::streamArgChanged (QString itemName, QVariant value) private slot
Definition at line 632 of file soapysdroutputgui.cpp.
References m_settings, SoapySDROutputSettings::m_streamArgSettings, and sendSettings().
Referenced by createArgumentsControl().
 {
     m_settings.m_streamArgSettings[itemName] = value;
     sendSettings();
 }
tunableElementChanged
void SoapySDROutputGui::tunableElementChanged (QString name, double value) private slot
Definition at line 566 of file soapysdroutputgui.cpp.
References m_settings, SoapySDROutputSettings::m_tunableElements, and sendSettings().
Referenced by createTunableElementsControl().
 {
     m_settings.m_tunableElements[name] = value;
     sendSettings();
 }
updateFrequencyLimits()
void SoapySDROutputGui::updateFrequencyLimits () private
Definition at line 819 of file soapysdroutputgui.cpp.
References SoapySDROutput::getFrequencyRange(), m_sampleSink, m_settings, SoapySDROutputSettings::m_transverterDeltaFrequency, SoapySDROutputSettings::m_transverterMode, and ui.
Referenced by on_transverter_clicked().
 {
     // values in kHz
     uint64_t f_min, f_max;
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     m_sampleSink->getFrequencyRange(f_min, f_max);
     qint64 minLimit = f_min/1000 + deltaFrequency;
     qint64 maxLimit = f_max/1000 + deltaFrequency;
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("SoapySDRInputGui::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void SoapySDROutputGui::updateHardware () private slot
Definition at line 844 of file soapysdroutputgui.cpp.
References SoapySDROutput::MsgConfigureSoapySDROutput::create(), DeviceSampleSink::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSink, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by SoapySDROutputGui().
 {
     if (m_doApplySettings)
     {
         qDebug() << "SoapySDROutputGui::updateHardware";
         SoapySDROutput::MsgConfigureSoapySDROutput* message = SoapySDROutput::MsgConfigureSoapySDROutput::create(m_settings, m_forceSettings);
         m_sampleSink->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void SoapySDROutputGui::updateSampleRateAndFrequency () private
Definition at line 812 of file soapysdroutputgui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_sampleRate / 1000.0f, 'g', 5)));
 }
updateStatus
void SoapySDROutputGui::updateStatus () private slot
Definition at line 856 of file soapysdroutputgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by SoapySDROutputGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_antennas
StringRangeGUI* SoapySDROutputGui::m_antennas private
Definition at line 90 of file soapysdroutputgui.h.
Referenced by antennasChanged(), createAntennasControl(), and displaySettings().
m_autoDCCorrection
QCheckBox* SoapySDROutputGui::m_autoDCCorrection private
Definition at line 99 of file soapysdroutputgui.h.
Referenced by createCorrectionsControl(), and displayCorrectionsSettings().
m_autoGain
QCheckBox* SoapySDROutputGui::m_autoGain private
Definition at line 96 of file soapysdroutputgui.h.
Referenced by createGlobalGainControl(), and displaySettings().
m_autoIQCorrection
QCheckBox* SoapySDROutputGui::m_autoIQCorrection private
Definition at line 100 of file soapysdroutputgui.h.
Referenced by createCorrectionsControl(), and displayCorrectionsSettings().
m_bandwidthGUI
ItemSettingGUI* SoapySDROutputGui::m_bandwidthGUI private
Definition at line 92 of file soapysdroutputgui.h.
Referenced by displaySettings(), and SoapySDROutputGui().
m_dcCorrectionGUI
ComplexFactorGUI* SoapySDROutputGui::m_dcCorrectionGUI private
Definition at line 97 of file soapysdroutputgui.h.
Referenced by createCorrectionsControl(), and displayCorrectionsSettings().
m_deviceArgsGUIs
std::vector<DynamicArgSettingGUI*> SoapySDROutputGui::m_deviceArgsGUIs private
Definition at line 102 of file soapysdroutputgui.h.
Referenced by createArgumentsControl(), and displayDeviceArgsSettings().
m_deviceCenterFrequency
quint64 SoapySDROutputGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 86 of file soapysdroutputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* SoapySDROutputGui::m_deviceUISet private
Definition at line 78 of file soapysdroutputgui.h.
Referenced by SoapySDROutputGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool SoapySDROutputGui::m_doApplySettings private
Definition at line 80 of file soapysdroutputgui.h.
Referenced by on_startStop_toggled(), and updateHardware().
m_forceSettings
bool SoapySDROutputGui::m_forceSettings private
Definition at line 79 of file soapysdroutputgui.h.
Referenced by deserialize(), and updateHardware().
m_gainSliderGUI
IntervalSliderGUI* SoapySDROutputGui::m_gainSliderGUI private
Definition at line 94 of file soapysdroutputgui.h.
Referenced by createGlobalGainControl(), and displaySettings().
m_individualGainsGUIs
std::vector<DynamicItemSettingGUI*> SoapySDROutputGui::m_individualGainsGUIs private
Definition at line 95 of file soapysdroutputgui.h.
Referenced by createIndividualGainsControl(), and displayIndividualGainsControlSettings().
m_inputMessageQueue
MessageQueue SoapySDROutputGui::m_inputMessageQueue private
Definition at line 88 of file soapysdroutputgui.h.
Referenced by handleInputMessages(), and SoapySDROutputGui().
m_iqCorrectionGUI
ComplexFactorGUI* SoapySDROutputGui::m_iqCorrectionGUI private
Definition at line 98 of file soapysdroutputgui.h.
Referenced by createCorrectionsControl(), and displayCorrectionsSettings().
m_lastEngineState
int SoapySDROutputGui::m_lastEngineState private
Definition at line 87 of file soapysdroutputgui.h.
Referenced by updateStatus().
m_sampleRate
int SoapySDROutputGui::m_sampleRate private
Definition at line 85 of file soapysdroutputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateGUI
ItemSettingGUI* SoapySDROutputGui::m_sampleRateGUI private
Definition at line 91 of file soapysdroutputgui.h.
Referenced by displaySettings(), and SoapySDROutputGui().
m_sampleSink
SoapySDROutput* SoapySDROutputGui::m_sampleSink private
Definition at line 84 of file soapysdroutputgui.h.
Referenced by createCorrectionsControl(), createGlobalGainControl(), on_startStop_toggled(), SoapySDROutputGui(), updateFrequencyLimits(), and updateHardware().
m_settings
SoapySDROutputSettings SoapySDROutputGui::m_settings private
Definition at line 81 of file soapysdroutputgui.h.
Referenced by antennasChanged(), autoDCCorrectionChanged(), autoGainChanged(), autoIQCorrectionChanged(), bandwidthChanged(), dcCorrectionArgumentChanged(), dcCorrectionModuleChanged(), deserialize(), deviceArgChanged(), displayCorrectionsSettings(), displayDeviceArgsSettings(), displayIndividualGainsControlSettings(), displaySettings(), displayStreamArgsSettings(), displayTunableElementsControlSettings(), getCenterFrequency(), globalGainChanged(), handleMessage(), individualGainChanged(), iqCorrectionArgumentChanged(), iqCorrectionModuleChanged(), on_centerFrequency_changed(), on_interp_currentIndexChanged(), on_LOppm_valueChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), sampleRateChanged(), serialize(), setCenterFrequency(), setCenterFrequencySetting(), SoapySDROutputGui(), streamArgChanged(), tunableElementChanged(), updateFrequencyLimits(), and updateHardware().
m_statusTimer
QTimer SoapySDROutputGui::m_statusTimer private
Definition at line 83 of file soapysdroutputgui.h.
Referenced by SoapySDROutputGui().
m_streamArgsGUIs
std::vector<DynamicArgSettingGUI*> SoapySDROutputGui::m_streamArgsGUIs private
Definition at line 101 of file soapysdroutputgui.h.
Referenced by createArgumentsControl(), and displayStreamArgsSettings().
m_tunableElementsGUIs
std::vector<DynamicItemSettingGUI*> SoapySDROutputGui::m_tunableElementsGUIs private
Definition at line 93 of file soapysdroutputgui.h.
Referenced by createTunableElementsControl(), and displayTunableElementsControlSettings().
m_updateTimer
QTimer SoapySDROutputGui::m_updateTimer private
Definition at line 82 of file soapysdroutputgui.h.
Referenced by sendSettings(), SoapySDROutputGui(), and updateHardware().
ui
Ui::SoapySDROutputGui* SoapySDROutputGui::ui private
Definition at line 76 of file soapysdroutputgui.h.
Referenced by createAntennasControl(), createArgumentsControl(), createCorrectionsControl(), createGlobalGainControl(), createIndividualGainsControl(), createRangesControl(), displaySettings(), handleMessage(), on_LOppm_valueChanged(), on_transverter_clicked(), setCenterFrequencySetting(), SoapySDROutputGui(), updateFrequencyLimits(), updateSampleRateAndFrequency(), updateStatus(), and ~SoapySDROutputGui().
The documentation for this class was generated from the following files:
plugins/samplesink/soapysdroutput/soapysdroutputgui.h
plugins/samplesink/soapysdroutput/soapysdroutputgui.cpp