SDRAngel: IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder > Class Template Reference
IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder > Class Template Reference
#include <inthalfbandfiltereo.h>
Public Member Functions
IntHalfbandFilterEO ()
bool workDecimateCenter (Sample *sample)
bool workInterpolateCenterZeroStuffing (Sample *sampleIn, Sample *SampleOut)
bool workInterpolateCenter (Sample *sampleIn, Sample *SampleOut)
bool workDecimateCenter (int32_t *x, int32_t *y)
bool workDecimateLowerHalf (Sample *sample)
bool workInterpolateLowerHalfZeroStuffing (Sample *sampleIn, Sample *sampleOut)
bool workInterpolateLowerHalf (Sample *sampleIn, Sample *sampleOut)
bool workDecimateUpperHalf (Sample *sample)
bool workInterpolateUpperHalfZeroStuffing (Sample *sampleIn, Sample *sampleOut)
bool workInterpolateUpperHalf (Sample *sampleIn, Sample *sampleOut)
void myDecimate (const Sample *sample1, Sample *sample2)
void myDecimate (int32_t x1, int32_t y1, int32_t *x2, int32_t *y2)
void myDecimateCen (int32_t x1, int32_t y1, int32_t *x2, int32_t *y2, int32_t x3, int32_t y3, int32_t *x4, int32_t *y4)
void myDecimateCen (int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3, int32_t x4, int32_t y4, int32_t *out)
void myDecimateCen (int32_t *in, int32_t *out)
void myDecimateInf (int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3, int32_t x4, int32_t y4, int32_t *out)
void myDecimateInf (int32_t *in, int32_t *out)
void myDecimateSup (int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3, int32_t x4, int32_t y4, int32_t *out)
void myDecimateSup (int32_t *in, int32_t *out)
void myInterpolateZeroStuffing (Sample *sample1, Sample *sample2)
void myInterpolateZeroStuffing (int32_t *x1, int32_t *y1, int32_t *x2, int32_t *y2)
void myInterpolate (qint32 *x1, qint32 *y1, qint32 *x2, qint32 *y2)
void myInterpolateInf (qint32 *x1, qint32 *y1, qint32 *x2, qint32 *y2, qint32 *x3, qint32 *y3, qint32 *x4, qint32 *y4)
void myInterpolateSup (qint32 *x1, qint32 *y1, qint32 *x2, qint32 *y2, qint32 *x3, qint32 *y3, qint32 *x4, qint32 *y4)
Protected Member Functions
void storeSample (const FixReal &sampleI, const FixReal &sampleQ)
void storeSample32 (int32_t x, int32_t y)
void advancePointer ()
void doFIR (Sample *sample)
void doFIR (int32_t *x, int32_t *y)
void doInterpolateFIR (Sample *sample)
void doInterpolateFIR (qint32 *x, qint32 *y)
Protected Attributes
EOStorageType m_even [2][HBFIRFilterTraits< HBFilterOrder >::hbOrder]
EOStorageType m_odd [2][HBFIRFilterTraits< HBFilterOrder >::hbOrder]
EOStorageType m_samples [HBFIRFilterTraits< HBFilterOrder >::hbOrder][2]
int m_ptr
int m_size
int m_state
Detailed Description
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder>
class IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >
Definition at line 32 of file inthalfbandfiltereo.h.
Constructor & Destructor Documentation
IntHalfbandFilterEO()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::IntHalfbandFilterEO () inline
Definition at line 34 of file inthalfbandfiltereo.h.
     {
         m_size = HBFIRFilterTraits<HBFilterOrder>::hbOrder/2;
         for (int i = 0; i < 2*m_size; i++)
         {
             m_even[0][i] = 0;
             m_even[1][i] = 0;
             m_odd[0][i] = 0;
             m_odd[1][i] = 0;
             m_samples[i][0] = 0;
             m_samples[i][1] = 0;
         }
         m_ptr = 0;
         m_state = 0;
     }
Member Function Documentation
advancePointer()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::advancePointer () inline protected
Definition at line 835 of file inthalfbandfiltereo.h.
Referenced by IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimate(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimateCen(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimateInf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimateSup(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myInterpolateZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateLowerHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateUpperHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), and IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing().
     {
         m_ptr = m_ptr + 1 < 2*m_size ? m_ptr + 1: 0;
     }
doFIR() [1/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::doFIR (Sample * sample) inline protected
Definition at line 840 of file inthalfbandfiltereo.h.
Referenced by IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimate(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimateCen(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimateInf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimateSup(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myInterpolateZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateLowerHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateUpperHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), and IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing().
     {
         AccuType iAcc = 0;
         AccuType qAcc = 0;
         int a = m_ptr/2 + m_size; // tip pointer
         int b = m_ptr/2 + 1; // tail pointer
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             if ((m_ptr % 2) == 0)
             {
                 iAcc += ((EOStorageType)(m_even[0][a] + m_even[0][b])) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 qAcc += ((EOStorageType)(m_even[1][a] + m_even[1][b])) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             }
             else
             {
                 iAcc += ((EOStorageType)(m_odd[0][a] + m_odd[0][b])) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 qAcc += ((EOStorageType)(m_odd[1][a] + m_odd[1][b])) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             }
             a -= 1;
             b += 1;
         }
         if ((m_ptr % 2) == 0)
         {
             iAcc += m_odd[0][m_ptr/2 + m_size/2] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             qAcc += m_odd[1][m_ptr/2 + m_size/2] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         }
         else
         {
             iAcc += m_even[0][m_ptr/2 + m_size/2 + 1] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             qAcc += m_even[1][m_ptr/2 + m_size/2 + 1] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         }
         sample->setReal(iAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1));
         sample->setImag(qAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1));
     }
doFIR() [2/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::doFIR (int32_t * x, int32_t * y) inline protected
Definition at line 880 of file inthalfbandfiltereo.h.
     {
         AccuType iAcc = 0;
         AccuType qAcc = 0;
         int a = m_ptr/2 + m_size; // tip pointer
         int b = m_ptr/2 + 1; // tail pointer
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             if ((m_ptr % 2) == 0)
             {
                 iAcc += ((EOStorageType)(m_even[0][a] + m_even[0][b])) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 qAcc += ((EOStorageType)(m_even[1][a] + m_even[1][b])) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             }
             else
             {
                 iAcc += ((EOStorageType)(m_odd[0][a] + m_odd[0][b])) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 qAcc += ((EOStorageType)(m_odd[1][a] + m_odd[1][b])) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             }
             a -= 1;
             b += 1;
         }
         if ((m_ptr % 2) == 0)
         {
             iAcc += m_odd[0][m_ptr/2 + m_size/2] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             qAcc += m_odd[1][m_ptr/2 + m_size/2] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         }
         else
         {
             iAcc += m_even[0][m_ptr/2 + m_size/2 + 1] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             qAcc += m_even[1][m_ptr/2 + m_size/2 + 1] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         }
         *x = iAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1); // HB_SHIFT incorrect do not loose the gained bit
         *y = qAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
     }
doInterpolateFIR() [1/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::doInterpolateFIR (Sample * sample) inline protected
Definition at line 920 of file inthalfbandfiltereo.h.
Referenced by IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myInterpolate(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), and IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf().
     {
         AccuType iAcc = 0;
         AccuType qAcc = 0;
         qint16 a = m_ptr;
         qint16 b = m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder / 2) - 1;
         // go through samples in buffer
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += ((EOStorageType)(m_samples[a][0] + m_samples[b][0])) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             qAcc += ((EOStorageType)(m_samples[a][1] + m_samples[b][1])) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             a++;
             b--;
         }
         sample->setReal(iAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1));
         sample->setImag(qAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1));
     }
doInterpolateFIR() [2/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::doInterpolateFIR (qint32 * x, qint32 * y) inline protected
Definition at line 941 of file inthalfbandfiltereo.h.
     {
         AccuType iAcc = 0;
         AccuType qAcc = 0;
         qint16 a = m_ptr;
         qint16 b = m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder / 2) - 1;
         // go through samples in buffer
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += ((EOStorageType)(m_samples[a][0] + m_samples[b][0])) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             qAcc += ((EOStorageType)(m_samples[a][1] + m_samples[b][1])) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             a++;
             b--;
         }
         *x = iAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
         *y = qAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
     }
myDecimate() [1/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myDecimate (const Sample * sample1, Sample * sample2) inline
Definition at line 571 of file inthalfbandfiltereo.h.
     {
         storeSample((FixReal) sample1->real(), (FixReal) sample1->imag());
         advancePointer();
         storeSample((FixReal) sample2->real(), (FixReal) sample2->imag());
         doFIR(sample2);
         advancePointer();
     }
myDecimate() [2/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myDecimate (int32_t x1, int32_t y1, int32_t * x2, int32_t * y2) inline
Definition at line 581 of file inthalfbandfiltereo.h.
     {
         storeSample32(x1, y1);
         advancePointer();
         storeSample32(*x2, *y2);
         doFIR(x2, y2);
         advancePointer();
     }
myDecimateCen() [1/3]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myDecimateCen (int32_t x1, int32_t y1, int32_t * x2, int32_t * y2, int32_t x3, int32_t y3, int32_t * x4, int32_t * y4) inline
Definition at line 591 of file inthalfbandfiltereo.h.
     {
         storeSample32(x1, y1);
         advancePointer();
         storeSample32(*x2, *y2);
         doFIR(x2, y2);
         advancePointer();
         storeSample32(x3, y3);
         advancePointer();
         storeSample32(*x4, *y4);
         doFIR(x4, y4);
         advancePointer();
     }
myDecimateCen() [2/3]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myDecimateCen (int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3, int32_t x4, int32_t y4, int32_t * out) inline
Definition at line 608 of file inthalfbandfiltereo.h.
     {
         storeSample32(x1, y1);
         advancePointer();
         storeSample32(x2, y2);
         doFIR(&out[0], &out[1]);
         advancePointer();
         storeSample32(x3, y3);
         advancePointer();
         storeSample32(x4, y4);
         doFIR(&out[2], &out[3]);
         advancePointer();
     }
myDecimateCen() [3/3]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myDecimateCen (int32_t * in, int32_t * out) inline
Definition at line 625 of file inthalfbandfiltereo.h.
     {
         storeSample32(in[0], in[1]);
         advancePointer();
         storeSample32(in[2], in[3]);
         doFIR(&out[0], &out[1]);
         advancePointer();
         storeSample32(in[4], in[5]);
         advancePointer();
         storeSample32(in[6], in[7]);
         doFIR(&out[2], &out[3]);
         advancePointer();
     }
myDecimateInf() [1/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myDecimateInf (int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3, int32_t x4, int32_t y4, int32_t * out) inline
Definition at line 642 of file inthalfbandfiltereo.h.
     {
         storeSample32(-y1, x1);
         advancePointer();
         storeSample32(-x2, -y2);
         doFIR(&out[0], &out[1]);
         advancePointer();
         storeSample32(y3, -x3);
         advancePointer();
         storeSample32(x4, y4);
         doFIR(&out[2], &out[3]);
         advancePointer();
     }
myDecimateInf() [2/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myDecimateInf (int32_t * in, int32_t * out) inline
Definition at line 659 of file inthalfbandfiltereo.h.
     {
         storeSample32(-in[1], in[0]);
         advancePointer();
         storeSample32(-in[2], -in[3]);
         doFIR(&out[0], &out[1]);
         advancePointer();
         storeSample32(in[5], -in[4]);
         advancePointer();
         storeSample32(in[6], in[7]);
         doFIR(&out[2], &out[3]);
         advancePointer();
     }
myDecimateSup() [1/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myDecimateSup (int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3, int32_t x4, int32_t y4, int32_t * out) inline
Definition at line 676 of file inthalfbandfiltereo.h.
     {
         storeSample32(y1, -x1);
         advancePointer();
         storeSample32(-x2, -y2);
         doFIR(&out[0], &out[1]);
         advancePointer();
         storeSample32(-y3, x3);
         advancePointer();
         storeSample32(x4, y4);
         doFIR(&out[2], &out[3]);
         advancePointer();
     }
myDecimateSup() [2/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myDecimateSup (int32_t * in, int32_t * out) inline
Definition at line 693 of file inthalfbandfiltereo.h.
     {
         storeSample32(in[1], -in[0]);
         advancePointer();
         storeSample32(-in[2], -in[3]);
         doFIR(&out[0], &out[1]);
         advancePointer();
         storeSample32(-in[5], in[4]);
         advancePointer();
         storeSample32(in[6], in[7]);
         doFIR(&out[2], &out[3]);
         advancePointer();
     }
myInterpolate()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myInterpolate (qint32 * x1, qint32 * y1, qint32 * x2, qint32 * y2) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 735 of file inthalfbandfiltereo.h.
Referenced by IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myInterpolateInf(), and IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myInterpolateSup().
     {
         // insert sample into ring double buffer
         m_samples[m_ptr][0] = *x1;
         m_samples[m_ptr][1] = *y1;
         m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = *x1;
         m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = *y1;
         // advance pointer
         if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
             m_ptr++;
         } else {
             m_ptr = 0;
         }
         // first output sample calculated with the middle peak
         *x1 = m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0];
         *y1 = m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1];
         // second sample calculated with the filter
         doInterpolateFIR(x2, y2);
     }
myInterpolateInf()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myInterpolateInf (qint32 * x1, qint32 * y1, qint32 * x2, qint32 * y2, qint32 * x3, qint32 * y3, qint32 * x4, qint32 * y4) inline
Definition at line 758 of file inthalfbandfiltereo.h.
     {
         myInterpolate(x1, y1, x2, y2);
         myInterpolate(x3, y3, x4, y4);
         // rotation
         qint32 x;
         x = *x1;
         *x1 = *y1;
         *y1 = -x;
         *x2 = -*x2;
         *y2 = -*y2;
         x = *x3;
         *x3 = -*y3;
         *y3 = x;
     }
myInterpolateSup()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myInterpolateSup (qint32 * x1, qint32 * y1, qint32 * x2, qint32 * y2, qint32 * x3, qint32 * y3, qint32 * x4, qint32 * y4) inline
Definition at line 774 of file inthalfbandfiltereo.h.
     {
         myInterpolate(x1, y1, x2, y2);
         myInterpolate(x3, y3, x4, y4);
         // rotation
         qint32 x;
         x = *x1;
         *x1 = -*y1;
         *y1 = x;
         *x2 = -*x2;
         *y2 = -*y2;
         x = *x3;
         *x3 = *y3;
         *y3 = -x;
     }
myInterpolateZeroStuffing() [1/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myInterpolateZeroStuffing (Sample * sample1, Sample * sample2) inline
Simple zero stuffing and filter
Definition at line 711 of file inthalfbandfiltereo.h.
     {
         storeSample((FixReal) sample1->real(), (FixReal) sample1->imag());
         doFIR(sample1);
         advancePointer();
         storeSample((FixReal) 0, (FixReal) 0);
         doFIR(sample2);
         advancePointer();
     }
myInterpolateZeroStuffing() [2/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::myInterpolateZeroStuffing (int32_t * x1, int32_t * y1, int32_t * x2, int32_t * y2) inline
Simple zero stuffing and filter
Definition at line 723 of file inthalfbandfiltereo.h.
     {
         storeSample32(*x1, *y1);
         doFIR(x1, y1);
         advancePointer();
         storeSample32(0, 0);
         doFIR(x2, y2);
         advancePointer();
     }
storeSample()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::storeSample (const FixReal & sampleI, const FixReal & sampleQ) inline protected
Definition at line 799 of file inthalfbandfiltereo.h.
Referenced by IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimate(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myInterpolateZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateLowerHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateUpperHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), and IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing().
     {
         if ((m_ptr % 2) == 0)
         {
             m_even[0][m_ptr/2] = sampleI;
             m_even[1][m_ptr/2] = sampleQ;
             m_even[0][m_ptr/2 + m_size] = sampleI;
             m_even[1][m_ptr/2 + m_size] = sampleQ;
         }
         else
         {
             m_odd[0][m_ptr/2] = sampleI;
             m_odd[1][m_ptr/2] = sampleQ;
             m_odd[0][m_ptr/2 + m_size] = sampleI;
             m_odd[1][m_ptr/2 + m_size] = sampleQ;
         }
     }
storeSample32()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> void IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::storeSample32 (int32_t x, int32_t y) inline protected
Definition at line 817 of file inthalfbandfiltereo.h.
Referenced by IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimate(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimateCen(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimateInf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimateSup(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myInterpolateZeroStuffing(), and IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateCenter().
     {
         if ((m_ptr % 2) == 0)
         {
             m_even[0][m_ptr/2] = x;
             m_even[1][m_ptr/2] = y;
             m_even[0][m_ptr/2 + m_size] = x;
             m_even[1][m_ptr/2 + m_size] = y;
         }
         else
         {
             m_odd[0][m_ptr/2] = x;
             m_odd[1][m_ptr/2] = y;
             m_odd[0][m_ptr/2 + m_size] = x;
             m_odd[1][m_ptr/2 + m_size] = y;
         }
     }
workDecimateCenter() [1/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::workDecimateCenter (Sample * sample) inline
Definition at line 53 of file inthalfbandfiltereo.h.
     {
         // insert sample into ring-buffer
         storeSample((FixReal) sample->real(), (FixReal) sample->imag());
         switch(m_state)
         {
             case 0:
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workDecimateCenter() [2/2]
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::workDecimateCenter (int32_t * x, int32_t * y) inline
Definition at line 146 of file inthalfbandfiltereo.h.
     {
         // insert sample into ring-buffer
         storeSample32(*x, *y);
         switch(m_state)
         {
             case 0:
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // save result
                 doFIR(x, y);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workDecimateLowerHalf()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::workDecimateLowerHalf (Sample * sample) inline
Definition at line 174 of file inthalfbandfiltereo.h.
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSample((FixReal) -sample->imag(), (FixReal) sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             case 1:
                 // insert sample into ring-buffer
                 storeSample((FixReal) -sample->real(), (FixReal) -sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 2;
                 // tell caller we have a new sample
                 return true;
             case 2:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sample->imag(), (FixReal) -sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 3;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sample->real(), (FixReal) sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workDecimateUpperHalf()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::workDecimateUpperHalf (Sample * sample) inline
Definition at line 373 of file inthalfbandfiltereo.h.
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sample->imag(), (FixReal) -sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             case 1:
                 // insert sample into ring-buffer
                 storeSample((FixReal) -sample->real(), (FixReal) -sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 2;
                 // tell caller we have a new sample
                 return true;
             case 2:
                 // insert sample into ring-buffer
                 storeSample((FixReal) -sample->imag(), (FixReal) sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 3;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sample->real(), (FixReal) sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workInterpolateCenter()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::workInterpolateCenter (Sample * sampleIn, Sample * SampleOut) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 113 of file inthalfbandfiltereo.h.
     {
         switch(m_state)
         {
         case 0:
             // return the middle peak
             SampleOut->setReal(m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]);
             SampleOut->setImag(m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);
             m_state = 1;  // next state
             return false; // tell caller we didn't consume the sample
         default:
             // calculate with non null samples
             doInterpolateFIR(SampleOut);
             // insert sample into ring double buffer
             m_samples[m_ptr][0] = sampleIn->real();
             m_samples[m_ptr][1] = sampleIn->imag();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 0; // next state
             return true; // tell caller we consumed the sample
         }
     }
workInterpolateCenterZeroStuffing()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::workInterpolateCenterZeroStuffing (Sample * sampleIn, Sample * SampleOut) inline
Definition at line 82 of file inthalfbandfiltereo.h.
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSample((FixReal) 0, (FixReal) 0);
                 // save result
                 doFIR(SampleOut);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we didn't consume the sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
                 // save result
                 doFIR(SampleOut);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we consumed the sample
                 return true;
         }
     }
workInterpolateLowerHalf()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::workInterpolateLowerHalf (Sample * sampleIn, Sample * sampleOut) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 306 of file inthalfbandfiltereo.h.
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // return the middle peak
             sampleOut->setReal(m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);  // imag
             sampleOut->setImag(-m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]); // - real
             m_state = 1;  // next state
             return false; // tell caller we didn't consume the sample
         case 1:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // insert sample into ring double buffer
             m_samples[m_ptr][0] = sampleIn->real();
             m_samples[m_ptr][1] = sampleIn->imag();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 2; // next state
             return true; // tell caller we consumed the sample
         case 2:
             // return the middle peak
             sampleOut->setReal(-m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);  // - imag
             sampleOut->setImag(m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]); // real
             m_state = 3;  // next state
             return false; // tell caller we didn't consume the sample
         default:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // insert sample into ring double buffer
             m_samples[m_ptr][0] = sampleIn->real();
             m_samples[m_ptr][1] = sampleIn->imag();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 0; // next state
             return true; // tell caller we consumed the sample
         }
     }
workInterpolateLowerHalfZeroStuffing()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::workInterpolateLowerHalfZeroStuffing (Sample * sampleIn, Sample * sampleOut) inline
Definition at line 225 of file inthalfbandfiltereo.h.
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // insert sample into ring-buffer
             storeSample((FixReal) 0, (FixReal) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(s.imag());
             sampleOut->setImag(-s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 1;
             // tell caller we didn't consume the sample
             return false;
         case 1:
             // insert sample into ring-buffer
             storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 2;
             // tell caller we consumed the sample
             return true;
         case 2:
             // insert sample into ring-buffer
             storeSample((FixReal) 0, (FixReal) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.imag());
             sampleOut->setImag(s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 3;
             // tell caller we didn't consume the sample
             return false;
         default:
             // insert sample into ring-buffer
             storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 0;
             // tell caller we consumed the sample
             return true;
         }
     }
workInterpolateUpperHalf()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::workInterpolateUpperHalf (Sample * sampleIn, Sample * sampleOut) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 505 of file inthalfbandfiltereo.h.
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // return the middle peak
             sampleOut->setReal(-m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]); // - imag
             sampleOut->setImag(m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]); // + real
             m_state = 1;  // next state
             return false; // tell caller we didn't consume the sample
         case 1:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // insert sample into ring double buffer
             m_samples[m_ptr][0] = sampleIn->real();
             m_samples[m_ptr][1] = sampleIn->imag();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 2; // next state
             return true; // tell caller we consumed the sample
         case 2:
             // return the middle peak
             sampleOut->setReal(m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);  // + imag
             sampleOut->setImag(-m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]);   // - real
             m_state = 3;  // next state
             return false; // tell caller we didn't consume the sample
         default:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // insert sample into ring double buffer
             m_samples[m_ptr][0] = sampleIn->real();
             m_samples[m_ptr][1] = sampleIn->imag();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 0; // next state
             return true; // tell caller we consumed the sample
         }
     }
workInterpolateUpperHalfZeroStuffing()
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> bool IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::workInterpolateUpperHalfZeroStuffing (Sample * sampleIn, Sample * sampleOut) inline
Definition at line 424 of file inthalfbandfiltereo.h.
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // insert sample into ring-buffer
             storeSample((FixReal) 0, (FixReal) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.imag());
             sampleOut->setImag(s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 1;
             // tell caller we didn't consume the sample
             return false;
         case 1:
             // insert sample into ring-buffer
             storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 2;
             // tell caller we consumed the sample
             return true;
         case 2:
             // insert sample into ring-buffer
             storeSample((FixReal) 0, (FixReal) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(s.imag());
             sampleOut->setImag(-s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 3;
             // tell caller we didn't consume the sample
             return false;
         default:
             // insert sample into ring-buffer
             storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 0;
             // tell caller we consumed the sample
             return true;
         }
     }
Member Data Documentation
m_even
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> EOStorageType IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::m_even[2][HBFIRFilterTraits< HBFilterOrder >::hbOrder] protected
Definition at line 791 of file inthalfbandfiltereo.h.
Referenced by IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::IntHalfbandFilterEO().
m_odd
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> EOStorageType IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::m_odd[2][HBFIRFilterTraits< HBFilterOrder >::hbOrder] protected
Definition at line 792 of file inthalfbandfiltereo.h.
Referenced by IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::IntHalfbandFilterEO().
m_ptr
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> int IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::m_ptr protected
Definition at line 795 of file inthalfbandfiltereo.h.
Referenced by IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::doInterpolateFIR(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::IntHalfbandFilterEO(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myInterpolate(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), and IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf().
m_samples
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> EOStorageType IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::m_samples[HBFIRFilterTraits< HBFilterOrder >::hbOrder][2] protected
Definition at line 793 of file inthalfbandfiltereo.h.
Referenced by IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::IntHalfbandFilterEO(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myInterpolate(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), and IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf().
m_size
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> int IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::m_size protected
Definition at line 796 of file inthalfbandfiltereo.h.
Referenced by IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::doFIR(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::IntHalfbandFilterEO(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::storeSample(), and IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::storeSample32().
m_state
template<typename EOStorageType, typename AccuType, uint32_t HBFilterOrder> int IntHalfbandFilterEO< EOStorageType, AccuType, HBFilterOrder >::m_state protected
Definition at line 797 of file inthalfbandfiltereo.h.
Referenced by IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::IntHalfbandFilterEO(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateLowerHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateUpperHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf(), and IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing().
The documentation for this class was generated from the following file:
sdrbase/dsp/inthalfbandfiltereo.h