SDRAngel: SWGSDRangel::SWGAudioDevices Class Reference
SWGSDRangel::SWGAudioDevices Class Reference
#include <SWGAudioDevices.h>
Public Member Functions
SWGAudioDevices ()
SWGAudioDevices (QString *json)
virtual ~SWGAudioDevices ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGAudioDevices * fromJson (QString &jsonString) override
qint32 getNbInputDevices ()
void setNbInputDevices (qint32 nb_input_devices)
QList< SWGAudioInputDevice * > * getInputDevices ()
void setInputDevices (QList< SWGAudioInputDevice *> *input_devices)
qint32 getNbOutputDevices ()
void setNbOutputDevices (qint32 nb_output_devices)
QList< SWGAudioOutputDevice * > * getOutputDevices ()
void setOutputDevices (QList< SWGAudioOutputDevice *> *output_devices)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 nb_input_devices
bool m_nb_input_devices_isSet
QList< SWGAudioInputDevice * > * input_devices
bool m_input_devices_isSet
qint32 nb_output_devices
bool m_nb_output_devices_isSet
QList< SWGAudioOutputDevice * > * output_devices
bool m_output_devices_isSet
Detailed Description
Definition at line 34 of file SWGAudioDevices.h.
Constructor & Destructor Documentation
SWGAudioDevices() [1/2]
SWGSDRangel::SWGAudioDevices::SWGAudioDevices ()
Definition at line 30 of file SWGAudioDevices.cpp.
References input_devices, m_input_devices_isSet, m_nb_input_devices_isSet, m_nb_output_devices_isSet, m_output_devices_isSet, nb_input_devices, nb_output_devices, and output_devices.
{
     nb_input_devices = 0;
     m_nb_input_devices_isSet = false;
     input_devices = nullptr;
     m_input_devices_isSet = false;
     nb_output_devices = 0;
     m_nb_output_devices_isSet = false;
     output_devices = nullptr;
     m_output_devices_isSet = false;
 }
SWGAudioDevices() [2/2]
SWGSDRangel::SWGAudioDevices::SWGAudioDevices (QString * json)
Definition at line 25 of file SWGAudioDevices.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGAudioDevices()
SWGSDRangel::SWGAudioDevices::~SWGAudioDevices () virtual
Definition at line 41 of file SWGAudioDevices.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGAudioDevices::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 99 of file SWGAudioDevices.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::instanceAudioService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGAudioDevices::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 110 of file SWGAudioDevices.cpp.
References input_devices, m_nb_input_devices_isSet, m_nb_output_devices_isSet, nb_input_devices, nb_output_devices, output_devices, and SWGSDRangel::toJsonArray().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_nb_input_devices_isSet){
         obj->insert("nbInputDevices", QJsonValue(nb_input_devices));
     }
     if(input_devices->size() > 0){
         toJsonArray((QList<void*>*)input_devices, obj, "inputDevices", "SWGAudioInputDevice");
     }
     if(m_nb_output_devices_isSet){
         obj->insert("nbOutputDevices", QJsonValue(nb_output_devices));
     }
     if(output_devices->size() > 0){
         toJsonArray((QList<void*>*)output_devices, obj, "outputDevices", "SWGAudioOutputDevice");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGAudioDevices::cleanup ()
Definition at line 58 of file SWGAudioDevices.cpp.
References input_devices, and output_devices.
Referenced by ~SWGAudioDevices().
{
     if(input_devices != nullptr) {
         auto arr = input_devices;
         for(auto o: *arr) {
             delete o;
         }
         delete input_devices;
     }
     if(output_devices != nullptr) {
         auto arr = output_devices;
         for(auto o: *arr) {
             delete o;
         }
         delete output_devices;
     }
 }
fromJson()
SWGAudioDevices * SWGSDRangel::SWGAudioDevices::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 78 of file SWGAudioDevices.cpp.
References fromJsonObject().
Referenced by SWGAudioDevices().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGAudioDevices::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 87 of file SWGAudioDevices.cpp.
References input_devices, nb_input_devices, nb_output_devices, output_devices, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&nb_input_devices, pJson["nbInputDevices"], "qint32", "");
     ::SWGSDRangel::setValue(&input_devices, pJson["inputDevices"], "QList", "SWGAudioInputDevice");
     ::SWGSDRangel::setValue(&nb_output_devices, pJson["nbOutputDevices"], "qint32", "");
     ::SWGSDRangel::setValue(&output_devices, pJson["outputDevices"], "QList", "SWGAudioOutputDevice");
 }
getInputDevices()
QList< SWGAudioInputDevice * > * SWGSDRangel::SWGAudioDevices::getInputDevices ()
Definition at line 139 of file SWGAudioDevices.cpp.
References input_devices.
Referenced by WebAPIAdapterGUI::instanceAudioGet(), and WebAPIAdapterSrv::instanceAudioGet().
{
     return input_devices;
 }
getNbInputDevices()
qint32 SWGSDRangel::SWGAudioDevices::getNbInputDevices ()
Definition at line 129 of file SWGAudioDevices.cpp.
References nb_input_devices.
{
     return nb_input_devices;
 }
getNbOutputDevices()
qint32 SWGSDRangel::SWGAudioDevices::getNbOutputDevices ()
Definition at line 149 of file SWGAudioDevices.cpp.
References nb_output_devices.
{
     return nb_output_devices;
 }
getOutputDevices()
QList< SWGAudioOutputDevice * > * SWGSDRangel::SWGAudioDevices::getOutputDevices ()
Definition at line 159 of file SWGAudioDevices.cpp.
References output_devices.
Referenced by WebAPIAdapterGUI::instanceAudioGet(), and WebAPIAdapterSrv::instanceAudioGet().
{
     return output_devices;
 }
init()
void SWGSDRangel::SWGAudioDevices::init ()
Definition at line 46 of file SWGAudioDevices.cpp.
References input_devices, m_input_devices_isSet, m_nb_input_devices_isSet, m_nb_output_devices_isSet, m_output_devices_isSet, nb_input_devices, nb_output_devices, and output_devices.
Referenced by WebAPIAdapterGUI::instanceAudioGet(), WebAPIAdapterSrv::instanceAudioGet(), and SWGAudioDevices().
                       {
     nb_input_devices = 0;
     m_nb_input_devices_isSet = false;
     input_devices = new QList<SWGAudioInputDevice*>();
     m_input_devices_isSet = false;
     nb_output_devices = 0;
     m_nb_output_devices_isSet = false;
     output_devices = new QList<SWGAudioOutputDevice*>();
     m_output_devices_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGAudioDevices::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 170 of file SWGAudioDevices.cpp.
References input_devices, m_nb_input_devices_isSet, m_nb_output_devices_isSet, and output_devices.
                       {
     bool isObjectUpdated = false;
     do{
         if(m_nb_input_devices_isSet){ isObjectUpdated = true; break;}
         if(input_devices->size() > 0){ isObjectUpdated = true; break;}
         if(m_nb_output_devices_isSet){ isObjectUpdated = true; break;}
         if(output_devices->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setInputDevices()
void SWGSDRangel::SWGAudioDevices::setInputDevices (QList< SWGAudioInputDevice *> * input_devices)
Definition at line 143 of file SWGAudioDevices.cpp.
References input_devices, and m_input_devices_isSet.
{
     this->input_devices = input_devices;
     this->m_input_devices_isSet = true;
 }
setNbInputDevices()
void SWGSDRangel::SWGAudioDevices::setNbInputDevices (qint32 nb_input_devices)
Definition at line 133 of file SWGAudioDevices.cpp.
References m_nb_input_devices_isSet, and nb_input_devices.
Referenced by WebAPIAdapterGUI::instanceAudioGet(), and WebAPIAdapterSrv::instanceAudioGet().
{
     this->nb_input_devices = nb_input_devices;
     this->m_nb_input_devices_isSet = true;
 }
setNbOutputDevices()
void SWGSDRangel::SWGAudioDevices::setNbOutputDevices (qint32 nb_output_devices)
Definition at line 153 of file SWGAudioDevices.cpp.
References m_nb_output_devices_isSet, and nb_output_devices.
Referenced by WebAPIAdapterGUI::instanceAudioGet(), and WebAPIAdapterSrv::instanceAudioGet().
{
     this->nb_output_devices = nb_output_devices;
     this->m_nb_output_devices_isSet = true;
 }
setOutputDevices()
void SWGSDRangel::SWGAudioDevices::setOutputDevices (QList< SWGAudioOutputDevice *> * output_devices)
Definition at line 163 of file SWGAudioDevices.cpp.
References m_output_devices_isSet, and output_devices.
{
     this->output_devices = output_devices;
     this->m_output_devices_isSet = true;
 }
Member Data Documentation
input_devices
QList<SWGAudioInputDevice*>* SWGSDRangel::SWGAudioDevices::input_devices private
Definition at line 66 of file SWGAudioDevices.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getInputDevices(), init(), isSet(), setInputDevices(), and SWGAudioDevices().
m_input_devices_isSet
bool SWGSDRangel::SWGAudioDevices::m_input_devices_isSet private
Definition at line 67 of file SWGAudioDevices.h.
Referenced by init(), setInputDevices(), and SWGAudioDevices().
m_nb_input_devices_isSet
bool SWGSDRangel::SWGAudioDevices::m_nb_input_devices_isSet private
Definition at line 64 of file SWGAudioDevices.h.
Referenced by asJsonObject(), init(), isSet(), setNbInputDevices(), and SWGAudioDevices().
m_nb_output_devices_isSet
bool SWGSDRangel::SWGAudioDevices::m_nb_output_devices_isSet private
Definition at line 70 of file SWGAudioDevices.h.
Referenced by asJsonObject(), init(), isSet(), setNbOutputDevices(), and SWGAudioDevices().
m_output_devices_isSet
bool SWGSDRangel::SWGAudioDevices::m_output_devices_isSet private
Definition at line 73 of file SWGAudioDevices.h.
Referenced by init(), setOutputDevices(), and SWGAudioDevices().
nb_input_devices
qint32 SWGSDRangel::SWGAudioDevices::nb_input_devices private
Definition at line 63 of file SWGAudioDevices.h.
Referenced by asJsonObject(), fromJsonObject(), getNbInputDevices(), init(), setNbInputDevices(), and SWGAudioDevices().
nb_output_devices
qint32 SWGSDRangel::SWGAudioDevices::nb_output_devices private
Definition at line 69 of file SWGAudioDevices.h.
Referenced by asJsonObject(), fromJsonObject(), getNbOutputDevices(), init(), setNbOutputDevices(), and SWGAudioDevices().
output_devices
QList<SWGAudioOutputDevice*>* SWGSDRangel::SWGAudioDevices::output_devices private
Definition at line 72 of file SWGAudioDevices.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getOutputDevices(), init(), isSet(), setOutputDevices(), and SWGAudioDevices().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGAudioDevices.h
swagger/sdrangel/code/qt5/client/SWGAudioDevices.cpp