SDRAngel: PlutoSDROutput::MsgStartStop Class Reference
PlutoSDROutput::MsgStartStop Class Reference
#include <plutosdroutput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 62 of file plutosdroutput.h.
Constructor & Destructor Documentation
MsgStartStop()
PlutoSDROutput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 75 of file plutosdroutput.h.
References PlutoSDROutput::deserialize(), PlutoSDROutput::destroy(), PlutoSDROutput::init(), PlutoSDROutput::PlutoSDROutput(), PlutoSDROutput::serialize(), PlutoSDROutput::start(), PlutoSDROutput::stop(), and PlutoSDROutput::~PlutoSDROutput().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* PlutoSDROutput::MsgStartStop::create (bool startStop) inline static
Definition at line 68 of file plutosdroutput.h.
Referenced by PlutoSDROutputGUI::on_startStop_toggled(), and PlutoSDROutput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool PlutoSDROutput::MsgStartStop::getStartStop () const inline
Definition at line 66 of file plutosdroutput.h.
Referenced by PlutoSDROutputGUI::handleMessage(), and PlutoSDROutput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool PlutoSDROutput::MsgStartStop::m_startStop protected
Definition at line 73 of file plutosdroutput.h.
The documentation for this class was generated from the following file:
plugins/samplesink/plutosdroutput/plutosdroutput.h