SDRAngel: leansdr::s2_fecdec< SOFTBIT, SOFTBYTE > Struct Template Reference
leansdr::s2_fecdec< SOFTBIT, SOFTBYTE > Struct Template Reference
#include <dvbs2.h>
Public Member Functions
s2_fecdec (scheduler *sch, pipebuf< fecframe< SOFTBYTE >> &_in, pipebuf< bbframe > &_out, pipebuf< int > *_bitcount=NULL, pipebuf< int > *_errcount=NULL)
void run ()
Public Member Functions inherited from leansdr::runnable
runnable (scheduler *_sch, const char *name)
Public Member Functions inherited from leansdr::runnable_common
runnable_common (const char *_name)
virtual ~runnable_common ()
virtual void shutdown ()
Public Attributes
int bitflips
Public Attributes inherited from leansdr::runnable_common
const char * name
Private Attributes
s2_ldpc_engines< SOFTBIT, SOFTBYTE > s2ldpc
uint8_t bch_buf [64800/8]
s2_bch_engines s2bch
s2_bbscrambling bbscrambling
pipereader< fecframe< SOFTBYTE > > in
pipewriter< bbframe > out
pipewriter< int > * bitcount
pipewriter< int > * errcount
Additional Inherited Members
Protected Attributes inherited from leansdr::runnable
scheduler * sch
Detailed Description
template<typename SOFTBIT, typename SOFTBYTE>
struct leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >
Definition at line 2090 of file dvbs2.h.
Constructor & Destructor Documentation
s2_fecdec()
template<typename SOFTBIT, typename SOFTBYTE> leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::s2_fecdec (scheduler * sch, pipebuf< fecframe< SOFTBYTE >> & _in, pipebuf< bbframe > & _out, pipebuf< int > * _bitcount = NULL, pipebuf< int > * _errcount = NULL) inline
Definition at line 2093 of file dvbs2.h.
References leansdr::scheduler::debug.
         : runnable(sch, "S2 fecdec"),
           bitflips(0),
           in(_in), out(_out),
           bitcount(opt_writer(_bitcount, 1)),
           errcount(opt_writer(_errcount, 1))
     {
         if (sch->debug)
             s2ldpc.print_node_stats();
     }
Member Function Documentation
run()
template<typename SOFTBIT, typename SOFTBYTE> void leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::run () inline virtual
Reimplemented from leansdr::runnable_common.
Definition at line 2106 of file dvbs2.h.
References leansdr::fecframe< SOFTBYTE >::bytes, leansdr::bbframe::bytes, leansdr::check_modcod(), leansdr::bch_interface::decode(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::decode_bitflip(), leansdr::opt_writable(), leansdr::opt_write(), leansdr::fecframe< SOFTBYTE >::pls, leansdr::bbframe::pls, leansdr::modcod_info::rate, leansdr::pipereader< T >::rd(), leansdr::pipereader< T >::read(), leansdr::pipereader< T >::readable(), leansdr::softbytes_harden(), leansdr::pipewriter< T >::wr(), leansdr::pipewriter< T >::writable(), and leansdr::pipewriter< T >::written().
     {
         while (in.readable() >= 1 && out.writable() >= 1 &&
                opt_writable(bitcount, 1) && opt_writable(errcount, 1))
         {
             fecframe<SOFTBYTE> *pin = in.rd();
             const modcod_info *mcinfo = check_modcod(pin->pls.modcod);
             const fec_info *fi = &fec_infos[pin->pls.sf][mcinfo->rate];
             bool corrupted = false;
             bool residual_errors;
             if (true)
             {
                 // LDPC decode
                 size_t cwbits = pin->pls.framebits();
                 size_t msgbits = fi->kldpc;
                 size_t chkbits = cwbits - msgbits;
                 s2_ldpc_engine *ldpc = s2ldpc.ldpcs[pin->pls.sf][mcinfo->rate];
                 int ncorr = ldpc->decode_bitflip(fi->ldpc, pin->bytes, msgbits, cwbits, bitflips);
                 if (sch->debug2)
                     fprintf(stderr, "LDPCCORR = %d\n", ncorr);
             }
             uint8_t *hardbytes = softbytes_harden(pin->bytes, fi->kldpc / 8, bch_buf);
             if (true)
             {
                 // BCH decode
                 size_t cwbytes = fi->kldpc / 8;
                 size_t msgbytes = fi->Kbch / 8;
                 size_t chkbytes = cwbytes - msgbytes;
                 // Decode with suitable BCH decoder for this MODCOD
                 bch_interface *bch = s2bch.bchs[pin->pls.sf][mcinfo->rate];
                 int ncorr = bch->decode(hardbytes, cwbytes);
                 if (sch->debug2)
                     fprintf(stderr, "BCHCORR = %d\n", ncorr);
                 corrupted = (ncorr < 0);
                 residual_errors = (ncorr != 0);
                 // Report VER
                 opt_write(bitcount, fi->Kbch);
                 opt_write(errcount, (ncorr >= 0) ? ncorr : fi->Kbch);
             }
             int bbsize = fi->Kbch / 8;
             // TBD Some decoders want the bad packets.
 #if 0
     if ( corrupted ) {
       fprintf(stderr, "Passing bad frame\n");
       corrupted = false;
     }
 #endif
             if (!corrupted)
             {
                 // Descramble and output
                 bbframe *pout = out.wr();
                 pout->pls = pin->pls;
                 bbscrambling.transform(hardbytes, bbsize, pout->bytes);
                 out.written(1);
             }
             if (sch->debug)
                 fprintf(stderr, "%c", corrupted ? ':' : residual_errors ? '.' : '_');
             in.read(1);
         }
     }
Member Data Documentation
bbscrambling
template<typename SOFTBIT, typename SOFTBYTE> s2_bbscrambling leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::bbscrambling private
Definition at line 2171 of file dvbs2.h.
bch_buf
template<typename SOFTBIT, typename SOFTBYTE> uint8_t leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::bch_buf[64800/8] private
Definition at line 2169 of file dvbs2.h.
bitcount
template<typename SOFTBIT, typename SOFTBYTE> pipewriter<int>* leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::bitcount private
Definition at line 2174 of file dvbs2.h.
bitflips
template<typename SOFTBIT, typename SOFTBYTE> int leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::bitflips
Definition at line 2092 of file dvbs2.h.
errcount
template<typename SOFTBIT, typename SOFTBYTE> pipewriter<int> * leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::errcount private
Definition at line 2174 of file dvbs2.h.
in
template<typename SOFTBIT, typename SOFTBYTE> pipereader<fecframe<SOFTBYTE> > leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::in private
Definition at line 2172 of file dvbs2.h.
out
template<typename SOFTBIT, typename SOFTBYTE> pipewriter<bbframe> leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::out private
Definition at line 2173 of file dvbs2.h.
s2bch
template<typename SOFTBIT, typename SOFTBYTE> s2_bch_engines leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::s2bch private
Definition at line 2170 of file dvbs2.h.
s2ldpc
template<typename SOFTBIT, typename SOFTBYTE> s2_ldpc_engines<SOFTBIT, SOFTBYTE> leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::s2ldpc private
Definition at line 2168 of file dvbs2.h.
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/dvbs2.h