SDRAngel: XTRXInputPlugin Class Reference
XTRXInputPlugin Class Reference
#include <xtrxinputplugin.h>
Public Member Functions
XTRXInputPlugin (QObject *parent=0)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "XTRX"
static const QString m_deviceTypeID = XTRX_DEVICE_TYPE_ID
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 29 of file xtrxinputplugin.h.
Constructor & Destructor Documentation
XTRXInputPlugin()
XTRXInputPlugin::XTRXInputPlugin (QObject * parent = 0) explicit
Definition at line 48 of file xtrxinputplugin.cpp.
                                                 :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSourcePluginInstance()
DeviceSampleSource * XTRXInputPlugin::createSampleSourcePluginInstance (const QString & sourceId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 119 of file xtrxinputplugin.cpp.
References m_deviceTypeID.
 {
     if (sourceId == m_deviceTypeID)
     {
         XTRXInput* input = new XTRXInput(deviceAPI);
         return input;
     }
     else
     {
         return 0;
     }
 }
createSampleSourcePluginInstanceGUI()
PluginInstanceGUI * XTRXInputPlugin::createSampleSourcePluginInstanceGUI (const QString & sourceId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 101 of file xtrxinputplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSources().
 {
     if(sourceId == m_deviceTypeID)
     {
         XTRXInputGUI* gui = new XTRXInputGUI(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSources()
PluginInterface::SamplingDevices XTRXInputPlugin::enumSampleSources () virtual
Reimplemented from PluginInterface.
Definition at line 63 of file xtrxinputplugin.cpp.
References arg(), createSampleSourcePluginInstanceGUI(), i, m_deviceTypeID, m_hardwareID, DeviceXTRXParams::m_nbRxChannels, PluginInterface::SamplingDevice::PhysicalDevice, and PluginInterface::SamplingDevice::StreamSingleRx.
 {
     SamplingDevices result;
     xtrx_device_info_t devs[32];
     int res = xtrx_discovery(devs, 32);
     int i;
     for (i = 0; i < res; i++) {
         DeviceXTRXParams XTRXParams;
         for (unsigned int j = 0; j < XTRXParams.m_nbRxChannels; j++)
         {
             qDebug("XTRXInputPlugin::enumSampleSources: device #%d channel %u: %s", i, j, devs[i].uniqname);
             QString displayedName(QString("XTRX[%1:%2] %3").arg(i).arg(j).arg(devs[i].uniqname));
             result.append(SamplingDevice(displayedName,
                                          m_hardwareID,
                                          m_deviceTypeID,
                                          QString(devs[i].uniqname),
                                          i,
                                          PluginInterface::SamplingDevice::PhysicalDevice,
                                          PluginInterface::SamplingDevice::StreamSingleRx,
                                          XTRXParams.m_nbRxChannels,
                                          j));
         }
     }
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & XTRXInputPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 53 of file xtrxinputplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void XTRXInputPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 58 of file xtrxinputplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSource().
 {
     pluginAPI->registerSampleSource(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString XTRXInputPlugin::m_deviceTypeID = XTRX_DEVICE_TYPE_ID static
Definition at line 48 of file xtrxinputplugin.h.
Referenced by createSampleSourcePluginInstance(), createSampleSourcePluginInstanceGUI(), enumSampleSources(), and initPlugin().
m_hardwareID
const QString XTRXInputPlugin::m_hardwareID = "XTRX" static
Definition at line 47 of file xtrxinputplugin.h.
Referenced by enumSampleSources().
m_pluginDescriptor
const PluginDescriptor XTRXInputPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("XTRX Input"),
    QString("4.5.4"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 51 of file xtrxinputplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesource/xtrxinput/xtrxinputplugin.h
plugins/samplesource/xtrxinput/xtrxinputplugin.cpp