SDRAngel: sdrbase/dsp/misc.h File Reference
misc.h File Reference
#include <math.h>
Macros
#define M_PI 3.14159265358979323846
Functions
float sinc (float x)
float cosc (float x)
float clamp (float x, float min, float max)
float decayavg (float average, float input, int weight)
This is always called with an int weight.
float blackman (float x)
float hamming (float x)
float hanning (float x)
float rcos (float t, float T, float alpha=1.0)
Macro Definition Documentation
M_PI
#define M_PI 3.14159265358979323846
Definition at line 30 of file misc.h.
Referenced by blackman(), cosc(), hamming(), hanning(), rcos(), and sinc().
Function Documentation
blackman()
float blackman (float x) inline
Definition at line 55 of file misc.h.
References cos(), and M_PI.
 {
     return (0.42 - 0.50 * cos(2 * M_PI * x) + 0.08 * cos(4 * M_PI * x));
 }
clamp()
float clamp (float x, float min, float max) inline
Definition at line 42 of file misc.h.
References leansdr::max(), and leansdr::min().
 {
     return (x < min) ? min : ((x > max) ? max : x);
 }
cosc()
float cosc (float x) inline
Definition at line 37 of file misc.h.
References cos(), and M_PI.
 {
     return (fabs(x) < 1e-10) ? 0.0 : ((1.0 - cos(M_PI * x)) / (M_PI * x));
 }
decayavg()
float decayavg (float average, float input, int weight) inline
This is always called with an int weight.
Definition at line 48 of file misc.h.
 {
     if (weight <= 1) return input;
     return ( ( input - average ) / (float)weight ) + average ;
 }
hamming()
float hamming (float x) inline
Definition at line 60 of file misc.h.
References cos(), and M_PI.
 {
     return 0.54 - 0.46 * cos(2 * M_PI * x);
 }
hanning()
float hanning (float x) inline
Definition at line 65 of file misc.h.
References cos(), and M_PI.
 {
     return 0.5 - 0.5 * cos(2 * M_PI * x);
 }
rcos()
float rcos (float t, float T, float alpha = 1.0) inline
Definition at line 70 of file misc.h.
References cos(), M_PI, and sin().
 {
     if( t == 0 ) return 1.0;
     float taT = T / (2.0 * alpha);
     if( fabs(t) == taT ) return ((alpha/2.0) * sin(M_PI/(2.0*alpha)));
     return (sin(M_PI*t/T)/(M_PI*t/T))*cos(alpha*M_PI*t/T)/(1.0-(t/taT)*(t/taT));
 }
sinc()
float sinc (float x) inline
Definition at line 32 of file misc.h.
References M_PI, and sin().
Referenced by leansdr::filtergen::lowpass().
 {
     return (fabs(x) < 1e-10) ? 1.0 : (sin(M_PI * x) / (M_PI * x));
 }