SDRAngel: leansdr::etr192_descrambler Struct Reference
leansdr::etr192_descrambler Struct Reference
#include <iess.h>
Public Member Functions
etr192_descrambler (scheduler *sch, pipebuf< u8 > &_in, pipebuf< u8 > &_out)
void run ()
Public Member Functions inherited from leansdr::runnable
runnable (scheduler *_sch, const char *name)
Public Member Functions inherited from leansdr::runnable_common
runnable_common (const char *_name)
virtual ~runnable_common ()
virtual void shutdown ()
Private Attributes
pipereader< u8 > in
pipewriter< u8 > out
u32 shiftreg
u8 counter
Additional Inherited Members
Public Attributes inherited from leansdr::runnable_common
const char * name
Protected Attributes inherited from leansdr::runnable
scheduler * sch
Detailed Description
Definition at line 29 of file iess.h.
Constructor & Destructor Documentation
etr192_descrambler()
leansdr::etr192_descrambler::etr192_descrambler (scheduler * sch, pipebuf< u8 > & _in, pipebuf< u8 > & _out) inline
Definition at line 31 of file iess.h.
         : runnable(sch, "etr192_dec"),
           in(_in), out(_out),
           shiftreg(0), counter(0)
     {
     }
Member Function Documentation
run()
void leansdr::etr192_descrambler::run () inline virtual
Reimplemented from leansdr::runnable_common.
Definition at line 40 of file iess.h.
References counter, in, leansdr::min(), out, leansdr::pipereader< T >::rd(), leansdr::pipereader< T >::read(), leansdr::pipereader< T >::readable(), shiftreg, leansdr::pipewriter< T >::wr(), leansdr::pipewriter< T >::writable(), and leansdr::pipewriter< T >::written().
     {
         int count = min(in.readable(), out.writable());
         for (u8 *pin = in.rd(), *pend = pin + count, *pout = out.wr();
              pin < pend; ++pin, ++pout)
         {
             u8 byte_in = *pin, byte_out = 0;
             for (int b = 8; b--; byte_in <<= 1)
             {
                 // Levels before clock transition
                 int bit_in = (byte_in & 128) ? 1 : 0;
                 int reset_counter = (shiftreg ^ (shiftreg >> 8)) & 1;
                 int counter_overflow = (counter == 31) ? 1 : 0;
                 int taps = (shiftreg >> 2) ^ (shiftreg >> 19);
                 int bit_out = (taps ^ counter_overflow ^ bit_in ^ 1) & 1;
                 // Execute clock transition
 #if 1 // Descramble
                 shiftreg = (shiftreg << 1) | bit_in;
 #else // Scramble
                 shiftreg = (shiftreg << 1) | bit_out;
 #endif
                 counter = reset_counter ? 0 : (counter + 1) & 31;
                 byte_out = (byte_out << 1) | bit_out;
             }
             *pout = byte_out;
         }
         in.read(count);
         out.written(count);
     }
Member Data Documentation
counter
u8 leansdr::etr192_descrambler::counter private
Definition at line 74 of file iess.h.
Referenced by run().
in
pipereader<u8> leansdr::etr192_descrambler::in private
Definition at line 71 of file iess.h.
Referenced by run().
out
pipewriter<u8> leansdr::etr192_descrambler::out private
Definition at line 72 of file iess.h.
Referenced by run().
shiftreg
u32 leansdr::etr192_descrambler::shiftreg private
Definition at line 73 of file iess.h.
Referenced by run().
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/iess.h