SDRAngel: NFMModGUI Class Reference
NFMModGUI Class Reference
#include <nfmmodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static NFMModGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx)
Private Slots
void handleSourceMessages ()
void on_deltaFrequency_changed (qint64 value)
void on_rfBW_currentIndexChanged (int index)
void on_afBW_valueChanged (int value)
void on_fmDev_valueChanged (int value)
void on_toneFrequency_valueChanged (int value)
void on_volume_valueChanged (int value)
void on_channelMute_toggled (bool checked)
void on_tone_toggled (bool checked)
void on_morseKeyer_toggled (bool checked)
void on_mic_toggled (bool checked)
void on_play_toggled (bool checked)
void on_playLoop_toggled (bool checked)
void on_navTimeSlider_valueChanged (int value)
void on_showFileDialog_clicked (bool checked)
void on_ctcss_currentIndexChanged (int index)
void on_ctcssOn_toggled (bool checked)
void on_feedbackEnable_toggled (bool checked)
void on_feedbackVolume_valueChanged (int value)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void configureFileName ()
void audioSelect ()
void audioFeedbackSelect ()
void tick ()
Private Member Functions
NFMModGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx, QWidget *parent=0)
virtual ~NFMModGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
void updateWithStreamData ()
void updateWithStreamTime ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::NFMModGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
NFMModSettings m_settings
bool m_doApplySettings
NFMMod * m_nfmMod
MovingAverageUtil< double, double, 20 > m_channelPowerDbAvg
QString m_fileName
quint32 m_recordLength
int m_recordSampleRate
int m_samplesCount
std::size_t m_tickCount
bool m_enableNavTime
NFMModSettings::NFMModInputAF m_modAFInput
MessageQueue m_inputMessageQueue
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 38 of file nfmmodgui.h.
Constructor & Destructor Documentation
NFMModGUI()
NFMModGUI::NFMModGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx, QWidget * parent = 0) explicit private
Definition at line 341 of file nfmmodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), arg(), audioFeedbackSelect(), audioSelect(), blockApplySettings(), channelMarkerChangedByCursor(), displaySettings(), NFMModSettings::getCTCSSFreq(), NFMMod::getCWKeyer(), getInputMessageQueue(), MainWindow::getInstance(), NFMModSettings::getRFBW(), ColorMapper::GrayGold, handleSourceMessages(), i, NFMMod::m_channelIdURI, m_channelMarker, m_deviceUISet, NFMModSettings::m_nbCTCSSFreqs, NFMModSettings::m_nbRfBW, m_nfmMod, m_settings, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerTxChannelInstance(), ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), NFMModSettings::setChannelMarker(), ChannelMarker::setColor(), NFMModSettings::setCWKeyerGUI(), BasebandSampleSource::setMessageQueueToGUI(), ChannelMarker::setSourceOrSinkStream(), ChannelMarker::setTitle(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                      :
     RollupWidget(parent),
     ui(new Ui::NFMModGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_doApplySettings(true),
     m_recordLength(0),
     m_recordSampleRate(48000),
     m_samplesCount(0),
     m_tickCount(0),
     m_enableNavTime(false)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     blockApplySettings(true);
     ui->rfBW->clear();
     for (int i = 0; i < NFMModSettings::m_nbRfBW; i++) {
         ui->rfBW->addItem(QString("%1").arg(NFMModSettings::getRFBW(i) / 1000.0, 0, 'f', 2));
     }
     ui->rfBW->setCurrentIndex(6);
     blockApplySettings(false);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_nfmMod = (NFMMod*) channelTx; //new NFMMod(m_deviceUISet->m_deviceSinkAPI);
     m_nfmMod->setMessageQueueToGUI(getInputMessageQueue());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     CRightClickEnabler *audioMuteRightClickEnabler = new CRightClickEnabler(ui->mic);
     connect(audioMuteRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioSelect()));
     CRightClickEnabler *feedbackRightClickEnabler = new CRightClickEnabler(ui->feedbackEnable);
     connect(feedbackRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioFeedbackSelect()));
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(Qt::red);
     m_channelMarker.setBandwidth(12500);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("NFM Modulator");
     m_channelMarker.setSourceOrSinkStream(false);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     m_deviceUISet->registerTxChannelInstance(NFMMod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     ui->play->setEnabled(false);
     ui->play->setChecked(false);
     ui->tone->setChecked(false);
     ui->mic->setChecked(false);
     for (int i=0; i< NFMModSettings::m_nbCTCSSFreqs; i++)
     {
         ui->ctcss->addItem(QString("%1").arg((double) NFMModSettings::getCTCSSFreq(i), 0, 'f', 1));
     }
     ui->cwKeyerGUI->setCWKeyer(m_nfmMod->getCWKeyer());
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     connect(m_nfmMod, SIGNAL(levelChanged(qreal, qreal, int)), ui->volumeMeter, SLOT(levelChanged(qreal, qreal, int)));
     m_settings.setChannelMarker(&m_channelMarker);
     m_settings.setCWKeyerGUI(ui->cwKeyerGUI);
     displaySettings();
     applySettings();
 }
~NFMModGUI()
NFMModGUI::~NFMModGUI () private virtual
Definition at line 422 of file nfmmodgui.cpp.
References m_deviceUISet, m_nfmMod, DeviceUISet::removeTxChannelInstance(), and ui.
 {
     m_deviceUISet->removeTxChannelInstance(this);
     delete m_nfmMod; // TODO: check this: when the GUI closes it has to delete the modulator
     delete ui;
 }
Member Function Documentation
applySettings()
void NFMModGUI::applySettings (bool force = false) private
Definition at line 434 of file nfmmodgui.cpp.
References NFMMod::MsgConfigureNFMMod::create(), NFMMod::MsgConfigureChannelizer::create(), ChannelMarker::getCenterFrequency(), BasebandSampleSource::getInputMessageQueue(), m_channelMarker, m_doApplySettings, m_nfmMod, m_settings, and MessageQueue::push().
Referenced by audioFeedbackSelect(), audioSelect(), channelMarkerChangedByCursor(), deserialize(), NFMModGUI(), on_afBW_valueChanged(), on_channelMute_toggled(), on_ctcss_currentIndexChanged(), on_ctcssOn_toggled(), on_deltaFrequency_changed(), on_feedbackEnable_toggled(), on_feedbackVolume_valueChanged(), on_fmDev_valueChanged(), on_mic_toggled(), on_morseKeyer_toggled(), on_play_toggled(), on_playLoop_toggled(), on_rfBW_currentIndexChanged(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), and setCenterFrequency().
 {
     if (m_doApplySettings)
     {
         NFMMod::MsgConfigureChannelizer *msgChan = NFMMod::MsgConfigureChannelizer::create(
                 48000, m_channelMarker.getCenterFrequency());
         m_nfmMod->getInputMessageQueue()->push(msgChan);
         NFMMod::MsgConfigureNFMMod *msg = NFMMod::MsgConfigureNFMMod::create(m_settings, force);
         m_nfmMod->getInputMessageQueue()->push(msg);
     }
 }
audioFeedbackSelect
void NFMModGUI::audioFeedbackSelect () private slot
Definition at line 524 of file nfmmodgui.cpp.
References applySettings(), audioSelect(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, NFMModSettings::m_audioDeviceName, NFMModSettings::m_feedbackAudioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by NFMModGUI().
 {
     qDebug("NFMModGUI::audioFeedbackSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName, false); // false for output
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_feedbackAudioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
audioSelect
void NFMModGUI::audioSelect () private slot
Definition at line 511 of file nfmmodgui.cpp.
References applySettings(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, NFMModSettings::m_audioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by audioFeedbackSelect(), and NFMModGUI().
 {
     qDebug("NFMModGUI::audioSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName, true); // true for input
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_audioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
blockApplySettings()
void NFMModGUI::blockApplySettings (bool block) private
Definition at line 429 of file nfmmodgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), handleMessage(), and NFMModGUI().
 {
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void NFMModGUI::channelMarkerChangedByCursor () slot
Definition at line 131 of file nfmmodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, NFMModSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by NFMModGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
configureFileName
void NFMModGUI::configureFileName () private slot
Definition at line 297 of file nfmmodgui.cpp.
References NFMMod::MsgConfigureFileSourceName::create(), BasebandSampleSource::getInputMessageQueue(), m_fileName, m_nfmMod, and MessageQueue::push().
Referenced by on_showFileDialog_clicked().
 {
     qDebug() << "FileSourceGui::configureFileName: " << m_fileName.toStdString().c_str();
     NFMMod::MsgConfigureFileSourceName* message = NFMMod::MsgConfigureFileSourceName::create(m_fileName);
     m_nfmMod->getInputMessageQueue()->push(message);
 }
create()
NFMModGUI * NFMModGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx) static
Definition at line 38 of file nfmmodgui.cpp.
References NFMModGUI().
Referenced by NFMModPlugin::createTxChannelGUI().
 {
     NFMModGUI* gui = new NFMModGUI(pluginAPI, deviceUISet, channelTx);
     return gui;
 }
deserialize()
bool NFMModGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 81 of file nfmmodgui.cpp.
References applySettings(), NFMModSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void NFMModGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 44 of file nfmmodgui.cpp.
 {
     delete this;
 }
displaySettings()
void NFMModGUI::displaySettings () private
Definition at line 447 of file nfmmodgui.cpp.
References arg(), blockApplySettings(), ChannelMarker::getCenterFrequency(), NFMModSettings::getRFBWIndex(), ChannelMarker::getTitle(), NFMModSettings::m_afBandwidth, m_channelMarker, NFMModSettings::m_channelMute, NFMModSettings::m_ctcssIndex, NFMModSettings::m_ctcssOn, NFMModSettings::m_feedbackAudioEnable, NFMModSettings::m_feedbackVolumeFactor, NFMModSettings::m_fmDeviation, NFMModSettings::m_inputFrequencyOffset, NFMModSettings::m_modAFInput, NFMModSettings::m_playLoop, NFMModSettings::m_rfBandwidth, NFMModSettings::m_rgbColor, m_settings, NFMModSettings::m_title, NFMModSettings::m_toneFrequency, NFMModSettings::m_volumeFactor, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by deserialize(), handleMessage(), NFMModGUI(), and resetToDefaults().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.setBandwidth(m_settings.m_rfBandwidth);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     ui->rfBW->setCurrentIndex(NFMModSettings::getRFBWIndex(m_settings.m_rfBandwidth));
     ui->afBWText->setText(QString("%1k").arg(m_settings.m_afBandwidth / 1000.0));
     ui->afBW->setValue(m_settings.m_afBandwidth / 1000.0);
     ui->fmDevText->setText(QString("%1k").arg(m_settings.m_fmDeviation / 1000.0, 0, 'f', 1));
     ui->fmDev->setValue(m_settings.m_fmDeviation / 100.0);
     ui->volumeText->setText(QString("%1").arg(m_settings.m_volumeFactor, 0, 'f', 1));
     ui->volume->setValue(m_settings.m_volumeFactor * 10.0);
     ui->toneFrequencyText->setText(QString("%1k").arg(m_settings.m_toneFrequency / 1000.0, 0, 'f', 2));
     ui->toneFrequency->setValue(m_settings.m_toneFrequency / 10.0);
     ui->ctcssOn->setChecked(m_settings.m_ctcssOn);
     ui->ctcss->setCurrentIndex(m_settings.m_ctcssIndex);
     ui->channelMute->setChecked(m_settings.m_channelMute);
     ui->playLoop->setChecked(m_settings.m_playLoop);
     ui->tone->setEnabled((m_settings.m_modAFInput == NFMModSettings::NFMModInputAF::NFMModInputTone) || (m_settings.m_modAFInput == NFMModSettings::NFMModInputAF::NFMModInputNone));
     ui->mic->setEnabled((m_settings.m_modAFInput == NFMModSettings::NFMModInputAF::NFMModInputAudio) || (m_settings.m_modAFInput == NFMModSettings::NFMModInputAF::NFMModInputNone));
     ui->play->setEnabled((m_settings.m_modAFInput == NFMModSettings::NFMModInputAF::NFMModInputFile) || (m_settings.m_modAFInput == NFMModSettings::NFMModInputAF::NFMModInputNone));
     ui->morseKeyer->setEnabled((m_settings.m_modAFInput == NFMModSettings::NFMModInputAF::NFMModInputCWTone) || (m_settings.m_modAFInput == NFMModSettings::NFMModInputAF::NFMModInputNone));
     ui->tone->setChecked(m_settings.m_modAFInput == NFMModSettings::NFMModInputAF::NFMModInputTone);
     ui->mic->setChecked(m_settings.m_modAFInput == NFMModSettings::NFMModInputAF::NFMModInputAudio);
     ui->play->setChecked(m_settings.m_modAFInput == NFMModSettings::NFMModInputAF::NFMModInputFile);
     ui->morseKeyer->setChecked(m_settings.m_modAFInput == NFMModSettings::NFMModInputAF::NFMModInputCWTone);
     ui->feedbackEnable->setChecked(m_settings.m_feedbackAudioEnable);
     ui->feedbackVolume->setValue(roundf(m_settings.m_feedbackVolumeFactor * 100.0));
     ui->feedbackVolumeText->setText(QString("%1").arg(m_settings.m_feedbackVolumeFactor, 0, 'f', 2));
     blockApplySettings(false);
 }
enterEvent()
void NFMModGUI::enterEvent (QEvent *) private
Definition at line 506 of file nfmmodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 NFMModGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 59 of file nfmmodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
{
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* NFMModGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 53 of file nfmmodgui.h.
Referenced by handleSourceMessages(), and NFMModGUI().
 { return &m_inputMessageQueue; }
getName()
QString NFMModGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 54 of file nfmmodgui.cpp.
 {
     return objectName();
 }
handleMessage()
bool NFMModGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 93 of file nfmmodgui.cpp.
References blockApplySettings(), displaySettings(), NFMMod::MsgConfigureNFMMod::getSettings(), CWKeyer::MsgConfigureCWKeyer::getSettings(), m_recordLength, m_recordSampleRate, m_samplesCount, m_settings, Message::match(), ui, updateWithStreamData(), and updateWithStreamTime().
Referenced by handleSourceMessages().
 {
     if (NFMMod::MsgReportFileSourceStreamData::match(message))
     {
         m_recordSampleRate = ((NFMMod::MsgReportFileSourceStreamData&)message).getSampleRate();
         m_recordLength = ((NFMMod::MsgReportFileSourceStreamData&)message).getRecordLength();
         m_samplesCount = 0;
         updateWithStreamData();
         return true;
     }
     else if (NFMMod::MsgReportFileSourceStreamTiming::match(message))
     {
         m_samplesCount = ((NFMMod::MsgReportFileSourceStreamTiming&)message).getSamplesCount();
         updateWithStreamTime();
         return true;
     }
     else if (NFMMod::MsgConfigureNFMMod::match(message))
     {
         const NFMMod::MsgConfigureNFMMod& cfg = (NFMMod::MsgConfigureNFMMod&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (CWKeyer::MsgConfigureCWKeyer::match(message))
     {
         const CWKeyer::MsgConfigureCWKeyer& cfg = (CWKeyer::MsgConfigureCWKeyer&) message;
         ui->cwKeyerGUI->setSettings(cfg.getSettings());
         ui->cwKeyerGUI->displaySettings();
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void NFMModGUI::handleSourceMessages () private slot
Definition at line 138 of file nfmmodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by NFMModGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void NFMModGUI::leaveEvent (QEvent *) private
Definition at line 501 of file nfmmodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_afBW_valueChanged
void NFMModGUI::on_afBW_valueChanged (int value) private slot
Definition at line 165 of file nfmmodgui.cpp.
References applySettings(), arg(), NFMModSettings::m_afBandwidth, m_settings, and ui.
 {
     ui->afBWText->setText(QString("%1k").arg(value));
     m_settings.m_afBandwidth = value * 1000.0;
     applySettings();
 }
on_channelMute_toggled
void NFMModGUI::on_channelMute_toggled (bool checked) private slot
Definition at line 193 of file nfmmodgui.cpp.
References applySettings(), NFMModSettings::m_channelMute, and m_settings.
 {
     m_settings.m_channelMute = checked;
     applySettings();
 }
on_ctcss_currentIndexChanged
void NFMModGUI::on_ctcss_currentIndexChanged (int index) private slot
Definition at line 284 of file nfmmodgui.cpp.
References applySettings(), NFMModSettings::m_ctcssIndex, and m_settings.
 {
     m_settings.m_ctcssIndex = index;
     applySettings();
 }
on_ctcssOn_toggled
void NFMModGUI::on_ctcssOn_toggled (bool checked) private slot
Definition at line 290 of file nfmmodgui.cpp.
References applySettings(), NFMModSettings::m_ctcssOn, and m_settings.
 {
     m_settings.m_ctcssOn = checked;
     applySettings();
 }
on_deltaFrequency_changed
void NFMModGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 151 of file nfmmodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, NFMModSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_feedbackEnable_toggled
void NFMModGUI::on_feedbackEnable_toggled (bool checked) private slot
Definition at line 243 of file nfmmodgui.cpp.
References applySettings(), NFMModSettings::m_feedbackAudioEnable, and m_settings.
 {
     m_settings.m_feedbackAudioEnable = checked;
     applySettings();
 }
on_feedbackVolume_valueChanged
void NFMModGUI::on_feedbackVolume_valueChanged (int value) private slot
Definition at line 249 of file nfmmodgui.cpp.
References applySettings(), arg(), NFMModSettings::m_feedbackVolumeFactor, m_settings, and ui.
 {
     ui->feedbackVolumeText->setText(QString("%1").arg(value / 100.0, 0, 'f', 2));
     m_settings.m_feedbackVolumeFactor = value / 100.0;
     applySettings();
 }
on_fmDev_valueChanged
void NFMModGUI::on_fmDev_valueChanged (int value) private slot
Definition at line 172 of file nfmmodgui.cpp.
References applySettings(), arg(), NFMModSettings::m_fmDeviation, m_settings, and ui.
 {
     ui->fmDevText->setText(QString("%1k").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_fmDeviation = value * 100.0;
     applySettings();
 }
on_mic_toggled
void NFMModGUI::on_mic_toggled (bool checked) private slot
Definition at line 234 of file nfmmodgui.cpp.
References applySettings(), NFMModSettings::m_modAFInput, m_settings, NFMModSettings::NFMModInputAudio, NFMModSettings::NFMModInputNone, and ui.
 {
     ui->play->setEnabled(!checked); // release other source inputs
     ui->tone->setEnabled(!checked); // release other source inputs
     ui->morseKeyer->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? NFMModSettings::NFMModInputAudio : NFMModSettings::NFMModInputNone;
     applySettings();
 }
on_morseKeyer_toggled
void NFMModGUI::on_morseKeyer_toggled (bool checked) private slot
Definition at line 225 of file nfmmodgui.cpp.
References applySettings(), NFMModSettings::m_modAFInput, m_settings, NFMModSettings::NFMModInputCWTone, NFMModSettings::NFMModInputNone, and ui.
 {
     ui->tone->setEnabled(!checked); // release other source inputs
     ui->mic->setEnabled(!checked);
     ui->play->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? NFMModSettings::NFMModInputCWTone : NFMModSettings::NFMModInputNone;
     applySettings();
 }
on_navTimeSlider_valueChanged
void NFMModGUI::on_navTimeSlider_valueChanged (int value) private slot
Definition at line 256 of file nfmmodgui.cpp.
References NFMMod::MsgConfigureFileSourceSeek::create(), BasebandSampleSource::getInputMessageQueue(), m_enableNavTime, m_nfmMod, m_recordLength, and MessageQueue::push().
 {
     if (m_enableNavTime && ((value >= 0) && (value <= 100)))
     {
         int t_sec = (m_recordLength * value) / 100;
         QTime t(0, 0, 0, 0);
         t = t.addSecs(t_sec);
         NFMMod::MsgConfigureFileSourceSeek* message = NFMMod::MsgConfigureFileSourceSeek::create(value);
         m_nfmMod->getInputMessageQueue()->push(message);
     }
 }
on_play_toggled
void NFMModGUI::on_play_toggled (bool checked) private slot
Definition at line 205 of file nfmmodgui.cpp.
References applySettings(), m_enableNavTime, NFMModSettings::m_modAFInput, m_settings, NFMModSettings::NFMModInputFile, NFMModSettings::NFMModInputNone, and ui.
 {
     ui->tone->setEnabled(!checked); // release other source inputs
     ui->mic->setEnabled(!checked);
     ui->morseKeyer->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? NFMModSettings::NFMModInputFile : NFMModSettings::NFMModInputNone;
     applySettings();
     ui->navTimeSlider->setEnabled(!checked);
     m_enableNavTime = !checked;
 }
on_playLoop_toggled
void NFMModGUI::on_playLoop_toggled (bool checked) private slot
Definition at line 199 of file nfmmodgui.cpp.
References applySettings(), NFMModSettings::m_playLoop, and m_settings.
 {
     m_settings.m_playLoop = checked;
     applySettings();
 }
on_rfBW_currentIndexChanged
void NFMModGUI::on_rfBW_currentIndexChanged (int index) private slot
Definition at line 158 of file nfmmodgui.cpp.
References applySettings(), NFMModSettings::getRFBW(), m_channelMarker, NFMModSettings::m_rfBandwidth, m_settings, and ChannelMarker::setBandwidth().
 {
     m_channelMarker.setBandwidth(NFMModSettings::getRFBW(index));
     m_settings.m_rfBandwidth = NFMModSettings::getRFBW(index);
     applySettings();
 }
on_showFileDialog_clicked
void NFMModGUI::on_showFileDialog_clicked (bool checked) private slot
Definition at line 269 of file nfmmodgui.cpp.
References configureFileName(), m_fileName, and ui.
 {
     (void) checked;
     QString fileName = QFileDialog::getOpenFileName(this,
         tr("Open raw audio file"), ".", tr("Raw audio Files (*.raw)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "")
     {
         m_fileName = fileName;
         ui->recordFileText->setText(m_fileName);
         ui->play->setEnabled(true);
         configureFileName();
     }
 }
on_tone_toggled
void NFMModGUI::on_tone_toggled (bool checked) private slot
Definition at line 216 of file nfmmodgui.cpp.
References applySettings(), NFMModSettings::m_modAFInput, m_settings, NFMModSettings::NFMModInputNone, NFMModSettings::NFMModInputTone, and ui.
 {
     ui->play->setEnabled(!checked); // release other source inputs
     ui->mic->setEnabled(!checked);
     ui->morseKeyer->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? NFMModSettings::NFMModInputTone : NFMModSettings::NFMModInputNone;
     applySettings();
 }
on_toneFrequency_valueChanged
void NFMModGUI::on_toneFrequency_valueChanged (int value) private slot
Definition at line 186 of file nfmmodgui.cpp.
References applySettings(), arg(), m_settings, NFMModSettings::m_toneFrequency, and ui.
 {
     ui->toneFrequencyText->setText(QString("%1k").arg(value / 100.0, 0, 'f', 2));
     m_settings.m_toneFrequency = value * 10.0;
     applySettings();
 }
on_volume_valueChanged
void NFMModGUI::on_volume_valueChanged (int value) private slot
Definition at line 179 of file nfmmodgui.cpp.
References applySettings(), arg(), m_settings, NFMModSettings::m_volumeFactor, and ui.
 {
     ui->volumeText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_volumeFactor = value / 10.0;
     applySettings();
 }
onMenuDialogCalled
void NFMModGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 310 of file nfmmodgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, NFMModSettings::m_inputFrequencyOffset, NFMModSettings::m_reverseAPIAddress, NFMModSettings::m_reverseAPIChannelIndex, NFMModSettings::m_reverseAPIDeviceIndex, NFMModSettings::m_reverseAPIPort, NFMModSettings::m_rgbColor, m_settings, NFMModSettings::m_title, NFMModSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by NFMModGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void NFMModGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 304 of file nfmmodgui.cpp.
Referenced by NFMModGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void NFMModGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 69 of file nfmmodgui.cpp.
References applySettings(), displaySettings(), m_settings, and NFMModSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
serialize()
QByteArray NFMModGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 76 of file nfmmodgui.cpp.
References m_settings, and NFMModSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void NFMModGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 63 of file nfmmodgui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     applySettings();
 }
setName()
void NFMModGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 49 of file nfmmodgui.cpp.
 {
     setObjectName(name);
 }
tick
void NFMModGUI::tick () private slot
Definition at line 537 of file nfmmodgui.cpp.
References arg(), NFMMod::MsgConfigureFileSourceStreamTiming::create(), CalcDb::dbPower(), BasebandSampleSource::getInputMessageQueue(), NFMMod::getMagSq(), m_channelPowerDbAvg, NFMModSettings::m_modAFInput, m_nfmMod, m_settings, m_tickCount, NFMModSettings::NFMModInputFile, MessageQueue::push(), and ui.
Referenced by NFMModGUI().
 {
     double powDb = CalcDb::dbPower(m_nfmMod->getMagSq());
     m_channelPowerDbAvg(powDb);
     ui->channelPower->setText(tr("%1 dB").arg(m_channelPowerDbAvg.asDouble(), 0, 'f', 1));
     if (((++m_tickCount & 0xf) == 0) && (m_settings.m_modAFInput == NFMModSettings::NFMModInputFile))
     {
         NFMMod::MsgConfigureFileSourceStreamTiming* message = NFMMod::MsgConfigureFileSourceStreamTiming::create();
         m_nfmMod->getInputMessageQueue()->push(message);
     }
 }
updateWithStreamData()
void NFMModGUI::updateWithStreamData () private
Definition at line 550 of file nfmmodgui.cpp.
References m_recordLength, ui, and updateWithStreamTime().
Referenced by handleMessage().
 {
     QTime recordLength(0, 0, 0, 0);
     recordLength = recordLength.addSecs(m_recordLength);
     QString s_time = recordLength.toString("HH:mm:ss");
     ui->recordLengthText->setText(s_time);
     updateWithStreamTime();
 }
updateWithStreamTime()
void NFMModGUI::updateWithStreamTime () private
Definition at line 559 of file nfmmodgui.cpp.
References m_enableNavTime, m_recordLength, m_recordSampleRate, m_samplesCount, and ui.
Referenced by handleMessage(), and updateWithStreamData().
 {
     int t_sec = 0;
     int t_msec = 0;
     if (m_recordSampleRate > 0)
     {
         t_msec = ((m_samplesCount * 1000) / m_recordSampleRate) % 1000;
         t_sec = m_samplesCount / m_recordSampleRate;
     }
     QTime t(0, 0, 0, 0);
     t = t.addSecs(t_sec);
     t = t.addMSecs(t_msec);
     QString s_timems = t.toString("HH:mm:ss.zzz");
     QString s_time = t.toString("HH:mm:ss");
     ui->relTimeText->setText(s_timems);
     if (!m_enableNavTime)
     {
         float posRatio = (float) t_sec / (float) m_recordLength;
         ui->navTimeSlider->setValue((int) (posRatio * 100.0));
     }
 }
Member Data Documentation
m_channelMarker
ChannelMarker NFMModGUI::m_channelMarker private
Definition at line 63 of file nfmmodgui.h.
Referenced by applySettings(), channelMarkerChangedByCursor(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), NFMModGUI(), on_deltaFrequency_changed(), on_rfBW_currentIndexChanged(), onMenuDialogCalled(), and setCenterFrequency().
m_channelPowerDbAvg
MovingAverageUtil<double, double, 20> NFMModGUI::m_channelPowerDbAvg private
Definition at line 68 of file nfmmodgui.h.
Referenced by tick().
m_deviceUISet
DeviceUISet* NFMModGUI::m_deviceUISet private
Definition at line 62 of file nfmmodgui.h.
Referenced by NFMModGUI(), and ~NFMModGUI().
m_doApplySettings
bool NFMModGUI::m_doApplySettings private
Definition at line 65 of file nfmmodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_enableNavTime
bool NFMModGUI::m_enableNavTime private
Definition at line 75 of file nfmmodgui.h.
Referenced by on_navTimeSlider_valueChanged(), on_play_toggled(), and updateWithStreamTime().
m_fileName
QString NFMModGUI::m_fileName private
Definition at line 70 of file nfmmodgui.h.
Referenced by configureFileName(), and on_showFileDialog_clicked().
m_inputMessageQueue
MessageQueue NFMModGUI::m_inputMessageQueue private
Definition at line 77 of file nfmmodgui.h.
m_modAFInput
NFMModSettings::NFMModInputAF NFMModGUI::m_modAFInput private
Definition at line 76 of file nfmmodgui.h.
m_nfmMod
NFMMod* NFMModGUI::m_nfmMod private
Definition at line 67 of file nfmmodgui.h.
Referenced by applySettings(), configureFileName(), NFMModGUI(), on_navTimeSlider_valueChanged(), tick(), and ~NFMModGUI().
m_pluginAPI
PluginAPI* NFMModGUI::m_pluginAPI private
Definition at line 61 of file nfmmodgui.h.
m_recordLength
quint32 NFMModGUI::m_recordLength private
Definition at line 71 of file nfmmodgui.h.
Referenced by handleMessage(), on_navTimeSlider_valueChanged(), updateWithStreamData(), and updateWithStreamTime().
m_recordSampleRate
int NFMModGUI::m_recordSampleRate private
Definition at line 72 of file nfmmodgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_samplesCount
int NFMModGUI::m_samplesCount private
Definition at line 73 of file nfmmodgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_settings
NFMModSettings NFMModGUI::m_settings private
Definition at line 64 of file nfmmodgui.h.
Referenced by applySettings(), audioFeedbackSelect(), audioSelect(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), handleMessage(), NFMModGUI(), on_afBW_valueChanged(), on_channelMute_toggled(), on_ctcss_currentIndexChanged(), on_ctcssOn_toggled(), on_deltaFrequency_changed(), on_feedbackEnable_toggled(), on_feedbackVolume_valueChanged(), on_fmDev_valueChanged(), on_mic_toggled(), on_morseKeyer_toggled(), on_play_toggled(), on_playLoop_toggled(), on_rfBW_currentIndexChanged(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), serialize(), and tick().
m_tickCount
std::size_t NFMModGUI::m_tickCount private
Definition at line 74 of file nfmmodgui.h.
Referenced by tick().
ui
Ui::NFMModGUI* NFMModGUI::ui private
Definition at line 60 of file nfmmodgui.h.
Referenced by channelMarkerChangedByCursor(), displaySettings(), handleMessage(), NFMModGUI(), on_afBW_valueChanged(), on_feedbackVolume_valueChanged(), on_fmDev_valueChanged(), on_mic_toggled(), on_morseKeyer_toggled(), on_play_toggled(), on_showFileDialog_clicked(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), tick(), updateWithStreamData(), updateWithStreamTime(), and ~NFMModGUI().
The documentation for this class was generated from the following files:
plugins/channeltx/modnfm/nfmmodgui.h
plugins/channeltx/modnfm/nfmmodgui.cpp