SDRAngel: leansdr::s2_deframer Struct Reference
leansdr::s2_deframer Struct Reference
#include <dvbs2.h>
Public Member Functions
s2_deframer (scheduler *sch, pipebuf< bbframe > &_in, pipebuf< tspacket > &_out, pipebuf< int > *_state_out=NULL, pipebuf< unsigned long > *_locktime_out=NULL)
void run ()
Public Member Functions inherited from leansdr::runnable
runnable (scheduler *_sch, const char *name)
Public Member Functions inherited from leansdr::runnable_common
runnable_common (const char *_name)
virtual ~runnable_common ()
virtual void shutdown ()
Private Member Functions
void run_bbframe (bbframe *pin)
void info_unlocked ()
void info_good_packet ()
void info_is_locked (bool newstate)
Private Attributes
crc8_engine crc8
int missing
uint8_t leftover [188]
bool locked
pipereader< bbframe > in
pipewriter< tspacket > out
int current_state
pipewriter< int > * state_out
bool report_state
unsigned long locktime
pipewriter< unsigned long > * locktime_out
Static Private Attributes
static const int MAX_TS_PER_BBFRAME = fec_info::KBCH_MAX / 8 / 188 + 1
Additional Inherited Members
Public Attributes inherited from leansdr::runnable_common
const char * name
Protected Attributes inherited from leansdr::runnable
scheduler * sch
Detailed Description
Definition at line 2514 of file dvbs2.h.
Constructor & Destructor Documentation
s2_deframer()
leansdr::s2_deframer::s2_deframer (scheduler * sch, pipebuf< bbframe > & _in, pipebuf< tspacket > & _out, pipebuf< int > * _state_out = NULL, pipebuf< unsigned long > * _locktime_out = NULL) inline
Definition at line 2516 of file dvbs2.h.
         : runnable(sch, "S2 deframer"),
           missing(-1),
           in(_in), out(_out, MAX_TS_PER_BBFRAME),
           current_state(false),
           state_out(opt_writer(_state_out, 2)),
           report_state(true),
           locktime(0),
           locktime_out(opt_writer(_locktime_out, MAX_TS_PER_BBFRAME))
     {
     }
Member Function Documentation
info_good_packet()
void leansdr::s2_deframer::info_good_packet () inline private
Definition at line 2632 of file dvbs2.h.
References leansdr::opt_write().
     {
         info_is_locked(true);
         ++locktime;
         opt_write(locktime_out, locktime);
     }
info_is_locked()
void leansdr::s2_deframer::info_is_locked (bool newstate) inline private
Definition at line 2638 of file dvbs2.h.
References leansdr::opt_write().
     {
         if (newstate != current_state)
         {
             opt_write(state_out, newstate ? 1 : 0);
             current_state = newstate;
         }
     }
info_unlocked()
void leansdr::s2_deframer::info_unlocked () inline private
Definition at line 2627 of file dvbs2.h.
     {
         info_is_locked(false);
         locktime = 0;
     }
run()
void leansdr::s2_deframer::run () inline virtual
Reimplemented from leansdr::runnable_common.
Definition at line 2529 of file dvbs2.h.
References leansdr::opt_writable(), leansdr::opt_write(), leansdr::pipereader< T >::rd(), leansdr::pipereader< T >::read(), leansdr::pipereader< T >::readable(), and leansdr::pipewriter< T >::writable().
     {
         while (in.readable() >= 1 && out.writable() >= MAX_TS_PER_BBFRAME &&
                opt_writable(state_out, 2) &&
                opt_writable(locktime_out, MAX_TS_PER_BBFRAME))
         {
             if (report_state)
             {
                 // Report unlocked state on first invocation.
                 opt_write(state_out, 0);
                 report_state = false;
             }
             run_bbframe(in.rd());
             in.read(1);
         }
     }
run_bbframe()
void leansdr::s2_deframer::run_bbframe (bbframe * pin) inline private
Definition at line 2547 of file dvbs2.h.
References leansdr::bbframe::bytes, leansdr::tspacket::data, leansdr::pipewriter< T >::wr(), and leansdr::pipewriter< T >::written().
     {
         uint8_t *bbh = pin->bytes;
         uint16_t upl = (bbh[2] << 8) | bbh[3];
         uint16_t dfl = (bbh[4] << 8) | bbh[5];
         uint8_t sync = bbh[6];
         uint16_t syncd = (bbh[7] << 8) | bbh[8];
         uint8_t crcexp = crc8.compute(bbh, 9);
         uint8_t crc = bbh[9];
         uint8_t *data = bbh + 10;
         int ro_code = bbh[0] & 3;
         if (sch->debug2)
         {
             static float ro_values[] = {0.35, 0.25, 0.20, 0};
             fprintf(stderr, "BBH: crc %02x/%02x %s ma=%02x%02x ro=%.2f"
                             " upl=%d dfl=%d sync=%02x syncd=%d\n",
                     crc, crcexp, (crc == crcexp) ? "OK" : "KO",
                     bbh[0], bbh[1], ro_values[ro_code], upl, dfl, sync, syncd);
         }
         if (crc != crcexp || upl != 188 * 8 || sync != 0x47 || dfl > fec_info::KBCH_MAX ||
             syncd > dfl || (dfl & 7) || (syncd & 7))
         {
             // Note: Maybe accept syncd=65535
             fprintf(stderr, "Bad bbframe\n");
             missing = -1;
             info_unlocked();
             return;
         }
         // TBD Handle packets as payload+finalCRC and do crc8 before pout
         int pos; // Start of useful data in this bbframe
         if (missing < 0)
         {
             // Skip unusable data at beginning of bbframe
             pos = syncd / 8;
             fprintf(stderr, "Start TS at %d\n", pos);
             missing = 0;
         }
         else
         {
             // Sanity check
             if (syncd / 8 != missing)
             {
                 fprintf(stderr, "Lost a bbframe ?\n");
                 missing = -1;
                 info_unlocked();
                 return;
             }
             pos = 0;
         }
         if (missing)
         {
             // Complete and output the partial TS packet in leftover[].
             tspacket *pout = out.wr();
             memcpy(pout->data, leftover, 188 - missing);
             memcpy(pout->data + (188 - missing), data + pos, missing);
             out.written(1);
             info_good_packet();
             ++pout;
             // Skip to beginning of next TS packet
             pos += missing;
             missing = 0;
         }
         while (pos + 188 <= dfl / 8)
         {
             tspacket *pout = out.wr();
             memcpy(pout->data, data + pos, 188);
             pout->data[0] = sync; // Replace CRC
             out.written(1);
             info_good_packet();
             pos += 188;
         }
         int remain = dfl / 8 - pos;
         if (remain)
         {
             memcpy(leftover, data + pos, remain);
             leftover[0] = sync; // Replace CRC
             missing = 188 - remain;
         }
     }
Member Data Documentation
crc8
crc8_engine leansdr::s2_deframer::crc8 private
Definition at line 2647 of file dvbs2.h.
current_state
int leansdr::s2_deframer::current_state private
Definition at line 2656 of file dvbs2.h.
in
pipereader<bbframe> leansdr::s2_deframer::in private
Definition at line 2654 of file dvbs2.h.
leftover
uint8_t leansdr::s2_deframer::leftover[188] private
Definition at line 2651 of file dvbs2.h.
locked
bool leansdr::s2_deframer::locked private
Definition at line 2653 of file dvbs2.h.
locktime
unsigned long leansdr::s2_deframer::locktime private
Definition at line 2659 of file dvbs2.h.
locktime_out
pipewriter<unsigned long>* leansdr::s2_deframer::locktime_out private
Definition at line 2660 of file dvbs2.h.
MAX_TS_PER_BBFRAME
const int leansdr::s2_deframer::MAX_TS_PER_BBFRAME = fec_info::KBCH_MAX / 8 / 188 + 1 static private
Definition at line 2652 of file dvbs2.h.
missing
int leansdr::s2_deframer::missing private
Definition at line 2648 of file dvbs2.h.
out
pipewriter<tspacket> leansdr::s2_deframer::out private
Definition at line 2655 of file dvbs2.h.
report_state
bool leansdr::s2_deframer::report_state private
Definition at line 2658 of file dvbs2.h.
state_out
pipewriter<int>* leansdr::s2_deframer::state_out private
Definition at line 2657 of file dvbs2.h.
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/dvbs2.h