SDRAngel: AudioCompressorSnd Class Reference
AudioCompressorSnd Class Reference
#include <audiocompressorsnd.h>
Classes
struct CompressorState
Public Member Functions
AudioCompressorSnd ()
~AudioCompressorSnd ()
void initDefault (int rate)
void initSimple (int rate, float pregain, float threshold, float knee, float ratio, float attack, float release)
void initState ()
float compress (float sample)
Public Attributes
float m_rate
float m_pregain
float m_threshold
float m_knee
float m_ratio
float m_attack
float m_release
float m_predelay
float m_releasezone1
float m_releasezone2
float m_releasezone3
float m_releasezone4
float m_postgain
float m_wet
Static Private Member Functions
static float db2lin (float db)
static float lin2db (float lin)
static float kneecurve (float x, float k, float linearthreshold)
static float kneeslope (float x, float k, float linearthreshold)
static float compcurve (float x, float k, float slope, float linearthreshold, float linearthresholdknee, float threshold, float knee, float kneedboffset)
static float adaptivereleasecurve (float x, float a, float b, float c, float d)
static float clampf (float v, float min, float max)
static float absf (float v)
static float fixf (float v, float def)
static void sf_compressor_process (CompressorState *state, int size, float *input, float *output)
Private Attributes
CompressorState m_compressorState
float m_storageBuffer [AUDIOCOMPRESSORSND_SF_COMPRESSOR_CHUNKSIZE]
float m_processedBuffer [AUDIOCOMPRESSORSND_SF_COMPRESSOR_CHUNKSIZE]
int m_sampleIndex
Detailed Description
Definition at line 46 of file audiocompressorsnd.h.
Constructor & Destructor Documentation
AudioCompressorSnd()
AudioCompressorSnd::AudioCompressorSnd ()
Definition at line 29 of file audiocompressorsnd.cpp.
References AUDIOCOMPRESSORSND_SF_COMPRESSOR_CHUNKSIZE, m_processedBuffer, and m_sampleIndex.
 {
     m_sampleIndex = 0;
     std::fill(m_processedBuffer, m_processedBuffer+AUDIOCOMPRESSORSND_SF_COMPRESSOR_CHUNKSIZE, 0.0f);
 }
~AudioCompressorSnd()
AudioCompressorSnd::~AudioCompressorSnd ()
Definition at line 35 of file audiocompressorsnd.cpp.
 {}
Member Function Documentation
absf()
static float AudioCompressorSnd::absf (float v) inline static private
Definition at line 158 of file audiocompressorsnd.h.
Referenced by sf_compressor_process().
{
         return v < 0.0f ? -v : v;
     }
adaptivereleasecurve()
static float AudioCompressorSnd::adaptivereleasecurve (float x, float a, float b, float c, float d) inline static private
Definition at line 148 of file audiocompressorsnd.h.
Referenced by sf_compressor_process().
{
         // a*x^3 + b*x^2 + c*x + d
         float x2 = x * x;
         return a * x2 * x + b * x2 + c * x + d;
     }
clampf()
static float AudioCompressorSnd::clampf (float v, float min, float max) inline static private
Definition at line 154 of file audiocompressorsnd.h.
References leansdr::max().
Referenced by sf_compressor_process().
{
         return v < min ? min : (v > max ? max : v);
     }
compcurve()
static float AudioCompressorSnd::compcurve (float x, float k, float slope, float linearthreshold, float linearthresholdknee, float threshold, float knee, float kneedboffset) inline static private
Definition at line 135 of file audiocompressorsnd.h.
Referenced by AudioCompressorSnd::CompressorState::sf_advancecomp(), and sf_compressor_process().
{
         if (x < linearthreshold)
             return x;
         if (knee <= 0.0f) // no knee in curve
             return db2lin(threshold + slope * (lin2db(x) - threshold));
         if (x < linearthresholdknee)
             return kneecurve(x, k, linearthreshold);
         return db2lin(kneedboffset + slope * (lin2db(x) - threshold - knee));
     }
compress()
float AudioCompressorSnd::compress (float sample)
Definition at line 58 of file audiocompressorsnd.cpp.
References AUDIOCOMPRESSORSND_SF_COMPRESSOR_CHUNKSIZE, m_compressorState, m_processedBuffer, m_sampleIndex, m_storageBuffer, and sf_compressor_process().
Referenced by SSBMod::pullAF().
 {
     float compressedSample;
     if (m_sampleIndex >= AUDIOCOMPRESSORSND_SF_COMPRESSOR_CHUNKSIZE)
     {
         sf_compressor_process(&m_compressorState, AUDIOCOMPRESSORSND_SF_COMPRESSOR_CHUNKSIZE, m_storageBuffer, m_processedBuffer);
         m_sampleIndex = 0;
     }
     compressedSample = m_processedBuffer[m_sampleIndex];
     m_storageBuffer[m_sampleIndex] = sample;
     m_sampleIndex++;
     return compressedSample;
 }
db2lin()
static float AudioCompressorSnd::db2lin (float db) inline static private
Definition at line 117 of file audiocompressorsnd.h.
Referenced by AudioCompressorSnd::CompressorState::sf_advancecomp(), and sf_compressor_process().
                                         { // dB to linear
         return powf(10.0f, 0.05f * db);
     }
fixf()
static float AudioCompressorSnd::fixf (float v, float def) inline static private
Definition at line 162 of file audiocompressorsnd.h.
Referenced by sf_compressor_process().
{
         // fix NaN and infinity values that sneak in... not sure why this is needed, but it is
         if (isnan(v) || isinf(v))
             return def;
         return v;
     }
initDefault()
void AudioCompressorSnd::initDefault (int rate) inline
Definition at line 52 of file audiocompressorsnd.h.
     {
         m_rate = rate;
         m_pregain = 0.000f;
         m_threshold = -24.000f;
         m_knee = 30.000f;
         m_ratio = 12.000f;
         m_attack = 0.003f;
         m_release = 0.250f;
         m_predelay = 0.006f;
         m_releasezone1 = 0.090f;
         m_releasezone2 = 0.160f;
         m_releasezone3 = 0.420f;
         m_releasezone4 = 0.980f;
         m_postgain = 0.000f;
         m_wet = 1.000f;
         initState();
     }
initSimple()
void AudioCompressorSnd::initSimple (int rate, float pregain, float threshold, float knee, float ratio, float attack, float release) inline
Definition at line 71 of file audiocompressorsnd.h.
Referenced by SSBMod::SSBMod().
     {
         m_rate = rate;
         m_pregain = pregain;
         m_threshold = threshold;
         m_knee = knee;
         m_ratio = ratio;
         m_attack = attack;
         m_release = release;
         m_predelay = 0.006f;
         m_releasezone1 = 0.090f;
         m_releasezone2 = 0.160f;
         m_releasezone3 = 0.420f;
         m_releasezone4 = 0.980f;
         m_postgain = 0.000f;
         m_wet = 1.000f;
         initState();
     }
initState()
void AudioCompressorSnd::initState ()
Definition at line 38 of file audiocompressorsnd.cpp.
References m_attack, m_compressorState, m_knee, m_postgain, m_predelay, m_pregain, m_rate, m_ratio, m_release, m_releasezone1, m_releasezone2, m_releasezone3, m_releasezone4, m_threshold, m_wet, and AudioCompressorSnd::CompressorState::sf_advancecomp().
Referenced by SSBMod::applyAudioSampleRate().
 {
     m_compressorState.sf_advancecomp(
         m_rate,
         m_pregain,
         m_threshold,
         m_knee,
         m_ratio,
         m_attack,
         m_release,
         m_predelay,
         m_releasezone1,
         m_releasezone2,
         m_releasezone3,
         m_releasezone4,
         m_postgain,
         m_wet
     );
 }
kneecurve()
static float AudioCompressorSnd::kneecurve (float x, float k, float linearthreshold) inline static private
Definition at line 127 of file audiocompressorsnd.h.
Referenced by AudioCompressorSnd::CompressorState::sf_advancecomp().
{
         return linearthreshold + (1.0f - expf(-k * (x - linearthreshold))) / k;
     }
kneeslope()
static float AudioCompressorSnd::kneeslope (float x, float k, float linearthreshold) inline static private
Definition at line 131 of file audiocompressorsnd.h.
Referenced by AudioCompressorSnd::CompressorState::sf_advancecomp().
{
         return k * x / ((k * linearthreshold + 1.0f) * expf(k * (x - linearthreshold)) - 1);
     }
lin2db()
static float AudioCompressorSnd::lin2db (float lin) inline static private
Definition at line 121 of file audiocompressorsnd.h.
Referenced by AudioCompressorSnd::CompressorState::sf_advancecomp(), and sf_compressor_process().
                                          { // linear to dB
         return 20.0f * log10f(lin);
     }
sf_compressor_process()
void AudioCompressorSnd::sf_compressor_process (AudioCompressorSnd::CompressorState * state, int size, float * input, float * output) static private
Definition at line 188 of file audiocompressorsnd.cpp.
References AudioCompressorSnd::CompressorState::a, absf(), adaptivereleasecurve(), AudioCompressorSnd::CompressorState::attacksamplesinv, AUDIOCOMPRESSORSND_SF_COMPRESSOR_SPACINGDB, AUDIOCOMPRESSORSND_SF_COMPRESSOR_SPU, AudioCompressorSnd::CompressorState::b, AudioCompressorSnd::CompressorState::c, clampf(), compcurve(), AudioCompressorSnd::CompressorState::compgain, AudioCompressorSnd::CompressorState::d, db2lin(), AudioCompressorSnd::CompressorState::delaybuf, AudioCompressorSnd::CompressorState::delaybufsize, AudioCompressorSnd::CompressorState::delayreadpos, AudioCompressorSnd::CompressorState::delaywritepos, AudioCompressorSnd::CompressorState::detectoravg, AudioCompressorSnd::CompressorState::dry, fixf(), AudioCompressorSnd::CompressorState::k, AudioCompressorSnd::CompressorState::knee, AudioCompressorSnd::CompressorState::kneedboffset, lin2db(), AudioCompressorSnd::CompressorState::linearpregain, AudioCompressorSnd::CompressorState::linearthreshold, AudioCompressorSnd::CompressorState::linearthresholdknee, M_PI, AudioCompressorSnd::CompressorState::mastergain, AudioCompressorSnd::CompressorState::maxcompdiffdb, AudioCompressorSnd::CompressorState::metergain, AudioCompressorSnd::CompressorState::meterrelease, AudioCompressorSnd::CompressorState::satreleasesamplesinv, AudioCompressorSnd::CompressorState::slope, AudioCompressorSnd::CompressorState::threshold, and AudioCompressorSnd::CompressorState::wet.
Referenced by compress().
 {
     // pull out the state into local variables
     float metergain            = state->metergain;
     float meterrelease         = state->meterrelease;
     float threshold            = state->threshold;
     float knee                 = state->knee;
     float linearpregain        = state->linearpregain;
     float linearthreshold      = state->linearthreshold;
     float slope                = state->slope;
     float attacksamplesinv     = state->attacksamplesinv;
     float satreleasesamplesinv = state->satreleasesamplesinv;
     float wet                  = state->wet;
     float dry                  = state->dry;
     float k                    = state->k;
     float kneedboffset         = state->kneedboffset;
     float linearthresholdknee  = state->linearthresholdknee;
     float mastergain           = state->mastergain;
     float a                    = state->a;
     float b                    = state->b;
     float c                    = state->c;
     float d                    = state->d;
     float detectoravg          = state->detectoravg;
     float compgain             = state->compgain;
     float maxcompdiffdb        = state->maxcompdiffdb;
     int delaybufsize           = state->delaybufsize;
     int delaywritepos          = state->delaywritepos;
     int delayreadpos           = state->delayreadpos;
     float *delaybuf            = state->delaybuf;
     int samplesperchunk = AUDIOCOMPRESSORSND_SF_COMPRESSOR_SPU;
     int chunks = size / samplesperchunk;
     float ang90 = (float)M_PI * 0.5f;
     float ang90inv = 2.0f / (float)M_PI;
     int samplepos = 0;
     float spacingdb = AUDIOCOMPRESSORSND_SF_COMPRESSOR_SPACINGDB;
     for (int ch = 0; ch < chunks; ch++)
     {
         detectoravg = fixf(detectoravg, 1.0f);
         float desiredgain = detectoravg;
         float scaleddesiredgain = asinf(desiredgain) * ang90inv;
         float compdiffdb = lin2db(compgain / scaleddesiredgain);
         // calculate envelope rate based on whether we're attacking or releasing
         float enveloperate;
         if (compdiffdb < 0.0f)
         { // compgain < scaleddesiredgain, so we're releasing
             compdiffdb = fixf(compdiffdb, -1.0f);
             maxcompdiffdb = -1; // reset for a future attack mode
             // apply the adaptive release curve
             // scale compdiffdb between 0-3
             float x = (clampf(compdiffdb, -12.0f, 0.0f) + 12.0f) * 0.25f;
             float releasesamples = adaptivereleasecurve(x, a, b, c, d);
             enveloperate = db2lin(spacingdb / releasesamples);
         }
         else
         { // compresorgain > scaleddesiredgain, so we're attacking
             compdiffdb = fixf(compdiffdb, 1.0f);
             if (maxcompdiffdb == -1 || maxcompdiffdb < compdiffdb)
                 maxcompdiffdb = compdiffdb;
             float attenuate = maxcompdiffdb;
             if (attenuate < 0.5f)
                 attenuate = 0.5f;
             enveloperate = 1.0f - powf(0.25f / attenuate, attacksamplesinv);
         }
         // process the chunk
         for (int chi = 0; chi < samplesperchunk; chi++, samplepos++,
             delayreadpos = (delayreadpos + 1) % delaybufsize,
             delaywritepos = (delaywritepos + 1) % delaybufsize)
         {
             float inputL = input[samplepos] * linearpregain;
             delaybuf[delaywritepos] = inputL;
             inputL = absf(inputL);
             float inputmax = inputL;
             float attenuation;
             if (inputmax < 0.0001f)
                 attenuation = 1.0f;
             else
             {
                 float inputcomp = compcurve(inputmax, k, slope, linearthreshold,
                     linearthresholdknee, threshold, knee, kneedboffset);
                 attenuation = inputcomp / inputmax;
             }
             float rate;
             if (attenuation > detectoravg)
             { // if releasing
                 float attenuationdb = -lin2db(attenuation);
                 if (attenuationdb < 2.0f)
                     attenuationdb = 2.0f;
                 float dbpersample = attenuationdb * satreleasesamplesinv;
                 rate = db2lin(dbpersample) - 1.0f;
             }
             else
                 rate = 1.0f;
             detectoravg += (attenuation - detectoravg) * rate;
             if (detectoravg > 1.0f)
                 detectoravg = 1.0f;
             detectoravg = fixf(detectoravg, 1.0f);
             if (enveloperate < 1) // attack, reduce gain
                 compgain += (scaleddesiredgain - compgain) * enveloperate;
             else
             { // release, increase gain
                 compgain *= enveloperate;
                 if (compgain > 1.0f)
                     compgain = 1.0f;
             }
             // the final gain value!
             float premixgain = sinf(ang90 * compgain);
             float gain = dry + wet * mastergain * premixgain;
             // calculate metering (not used in core algo, but used to output a meter if desired)
             float premixgaindb = lin2db(premixgain);
             if (premixgaindb < metergain)
                 metergain = premixgaindb; // spike immediately
             else
                 metergain += (premixgaindb - metergain) * meterrelease; // fall slowly
             // apply the gain
             output[samplepos] = delaybuf[delayreadpos] * gain;
         }
     }
     state->metergain     = metergain;
     state->detectoravg   = detectoravg;
     state->compgain      = compgain;
     state->maxcompdiffdb = maxcompdiffdb;
     state->delaywritepos = delaywritepos;
     state->delayreadpos  = delayreadpos;
 }
Member Data Documentation
m_attack
float AudioCompressorSnd::m_attack
Definition at line 106 of file audiocompressorsnd.h.
Referenced by initState().
m_compressorState
CompressorState AudioCompressorSnd::m_compressorState private
Definition at line 221 of file audiocompressorsnd.h.
Referenced by compress(), and initState().
m_knee
float AudioCompressorSnd::m_knee
Definition at line 104 of file audiocompressorsnd.h.
Referenced by initState().
m_postgain
float AudioCompressorSnd::m_postgain
Definition at line 113 of file audiocompressorsnd.h.
Referenced by initState().
m_predelay
float AudioCompressorSnd::m_predelay
Definition at line 108 of file audiocompressorsnd.h.
Referenced by initState().
m_pregain
float AudioCompressorSnd::m_pregain
Definition at line 102 of file audiocompressorsnd.h.
Referenced by initState().
m_processedBuffer
float AudioCompressorSnd::m_processedBuffer[AUDIOCOMPRESSORSND_SF_COMPRESSOR_CHUNKSIZE] private
Definition at line 223 of file audiocompressorsnd.h.
Referenced by AudioCompressorSnd(), and compress().
m_rate
float AudioCompressorSnd::m_rate
Definition at line 101 of file audiocompressorsnd.h.
Referenced by SSBMod::applyAudioSampleRate(), and initState().
m_ratio
float AudioCompressorSnd::m_ratio
Definition at line 105 of file audiocompressorsnd.h.
Referenced by initState().
m_release
float AudioCompressorSnd::m_release
Definition at line 107 of file audiocompressorsnd.h.
Referenced by initState().
m_releasezone1
float AudioCompressorSnd::m_releasezone1
Definition at line 109 of file audiocompressorsnd.h.
Referenced by initState().
m_releasezone2
float AudioCompressorSnd::m_releasezone2
Definition at line 110 of file audiocompressorsnd.h.
Referenced by initState().
m_releasezone3
float AudioCompressorSnd::m_releasezone3
Definition at line 111 of file audiocompressorsnd.h.
Referenced by initState().
m_releasezone4
float AudioCompressorSnd::m_releasezone4
Definition at line 112 of file audiocompressorsnd.h.
Referenced by initState().
m_sampleIndex
int AudioCompressorSnd::m_sampleIndex private
Definition at line 224 of file audiocompressorsnd.h.
Referenced by AudioCompressorSnd(), and compress().
m_storageBuffer
float AudioCompressorSnd::m_storageBuffer[AUDIOCOMPRESSORSND_SF_COMPRESSOR_CHUNKSIZE] private
Definition at line 222 of file audiocompressorsnd.h.
Referenced by compress().
m_threshold
float AudioCompressorSnd::m_threshold
Definition at line 103 of file audiocompressorsnd.h.
Referenced by initState().
m_wet
float AudioCompressorSnd::m_wet
Definition at line 114 of file audiocompressorsnd.h.
Referenced by initState().
The documentation for this class was generated from the following files:
sdrbase/audio/audiocompressorsnd.h
sdrbase/audio/audiocompressorsnd.cpp