SDRAngel: NCOF Class Reference
NCOF Class Reference
#include <ncof.h>
Public Member Functions
NCOF ()
void setFreq (Real freq, Real sampleRate)
void setPhase (Real phase)
int nextPhase ()
Real next ()
Return next real sample.
Complex nextIQ ()
Return next complex sample.
Complex nextIQ (float imbalance)
Return next complex sample with an imbalance factor on I.
Complex nextQI ()
Return next complex sample (reversed)
Real get ()
Return current real sample (no phase increment)
Complex getIQ ()
Return current complex sample (no phase increment)
void getIQ (Complex &c)
Sets to the current complex sample (no phase increment)
Complex getQI ()
Return current complex sample (no phase increment, reversed)
void getQI (Complex &c)
Sets to the current complex sample (no phase increment, reversed)
Private Types
enum { TableSize = (1 << 12) }
Static Private Member Functions
static void initTable ()
Private Attributes
Real m_phaseIncrement
Real m_phase
Static Private Attributes
static Real m_table [TableSize+1]
static bool m_tableInitialized = false
static float m_tableSizeLimit = (float) NCOF::TableSize
Detailed Description
Definition at line 24 of file ncof.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
TableSize
Definition at line 26 of file ncof.h.
          {
         TableSize = (1 << 12),
     };
Constructor & Destructor Documentation
NCOF()
NCOF::NCOF ()
Definition at line 44 of file ncof.cpp.
References initTable(), m_phase, and m_phaseIncrement.
 {
     initTable();
     m_phase = 0.0f;
     m_phaseIncrement = 0.0f;
 }
Member Function Documentation
get()
float NCOF::get ()
Return current real sample (no phase increment)
Definition at line 83 of file ncof.cpp.
References m_phase, and m_table.
 {
     return m_table[(int) m_phase];
 }
getIQ() [1/2]
Complex NCOF::getIQ ()
Return current complex sample (no phase increment)
Definition at line 88 of file ncof.cpp.
References m_phase, m_table, and TableSize.
 {
     return Complex(m_table[(int) m_phase], -m_table[((int) m_phase + TableSize / 4) % TableSize]);
 }
getIQ() [2/2]
void NCOF::getIQ (Complex & c)
Sets to the current complex sample (no phase increment)
Definition at line 93 of file ncof.cpp.
References m_phase, m_table, and TableSize.
 {
     c.real(m_table[(int) m_phase]);
     c.imag(-m_table[((int) m_phase + TableSize / 4) % TableSize]);
 }
getQI() [1/2]
Complex NCOF::getQI ()
Return current complex sample (no phase increment, reversed)
Definition at line 99 of file ncof.cpp.
References m_phase, m_table, and TableSize.
 {
     return Complex(-m_table[((int) m_phase + TableSize / 4) % TableSize], m_table[(int) m_phase]);
 }
getQI() [2/2]
void NCOF::getQI (Complex & c)
Sets to the current complex sample (no phase increment, reversed)
Definition at line 104 of file ncof.cpp.
References m_phase, m_table, and TableSize.
 {
     c.imag(m_table[(int) m_phase]);
     c.real(-m_table[((int) m_phase + TableSize / 4) % TableSize]);
 }
initTable()
void NCOF::initTable () static private
Definition at line 31 of file ncof.cpp.
References cos(), i, M_PI, m_table, m_tableInitialized, and TableSize.
Referenced by NCOF().
 {
     if(m_tableInitialized) {
         return;
     }
     for(int i = 0; i <= TableSize; i++) {
         m_table[i] = cos((2.0 * M_PI * i) / TableSize);
     }
     m_tableInitialized = true;
 }
next()
float NCOF::next ()
Return next real sample.
Definition at line 57 of file ncof.cpp.
References m_table, and nextPhase().
Referenced by NFMMod::modulateSample(), TestMIThread::pullAF(), TestSourceThread::pullAF(), WFMMod::pullAF(), AMMod::pullAF(), NFMMod::pullAF(), FreeDVMod::pullAF(), and SSBMod::pullAF().
 {
     int phase = nextPhase();
     return m_table[phase];
 }
nextIQ() [1/2]
Complex NCOF::nextIQ ()
Return next complex sample.
Definition at line 63 of file ncof.cpp.
References m_table, nextPhase(), and TableSize.
Referenced by SSBDemod::feed(), FreqTracker::feed(), FreeDVDemod::feed(), ChannelAnalyzer::feed(), TestMIThread::generate(), TestSourceThread::generate(), SSBMod::pull(), FreeDVMod::pull(), and SSBMod::pullAF().
 {
     int phase = nextPhase();
     return Complex(m_table[phase], -m_table[(phase + TableSize / 4) % TableSize]);
 }
nextIQ() [2/2]
Complex NCOF::nextIQ (float imbalance)
Return next complex sample with an imbalance factor on I.
Definition at line 69 of file ncof.cpp.
References m_table, nextPhase(), and TableSize.
 {
     int phase = nextPhase();
     int phaseQ = imbalance < 0.0 ? phase + (int) (imbalance*TableSize) : phase;
     int phaseI = imbalance < 0.0 ? phase : phase + (int) (imbalance*TableSize);
     return Complex(m_table[phaseI % TableSize], -m_table[(phaseQ + TableSize / 4) % TableSize]);
 }
nextPhase()
int NCOF::nextPhase () inline
Definition at line 44 of file ncof.h.
Referenced by next(), nextIQ(), and nextQI().
     {
         m_phase += m_phaseIncrement;
         while(m_phase >= m_tableSizeLimit) {
             m_phase -= TableSize;
         }
         while(m_phase < 0.0) {
             m_phase += TableSize;
         }
         return (int) m_phase;
     }
nextQI()
Complex NCOF::nextQI ()
Return next complex sample (reversed)
Definition at line 77 of file ncof.cpp.
References m_table, nextPhase(), and TableSize.
Referenced by SSBMod::pullAF().
 {
     int phase = nextPhase();
     return Complex(-m_table[(phase + TableSize / 4) % TableSize], m_table[phase]);
 }
setFreq()
void NCOF::setFreq (Real freq, Real sampleRate)
Definition at line 51 of file ncof.cpp.
References m_phaseIncrement, and TableSize.
Referenced by AMMod::AMMod(), AMMod::applyAudioSampleRate(), NFMMod::applyAudioSampleRate(), SSBMod::applyAudioSampleRate(), ChannelAnalyzer::applyChannelSettings(), FreqTracker::applyChannelSettings(), WFMMod::applyChannelSettings(), SSBDemod::applyChannelSettings(), FreeDVMod::applyChannelSettings(), SSBMod::applyChannelSettings(), FreeDVDemod::applyChannelSettings(), WFMMod::applySettings(), AMMod::applySettings(), NFMMod::applySettings(), FreeDVMod::applySettings(), SSBMod::applySettings(), FreeDVMod::FreeDVMod(), NFMMod::NFMMod(), TestMIThread::setFrequencyShift(), TestSourceThread::setFrequencyShift(), TestMIThread::setSamplerate(), TestSourceThread::setSamplerate(), TestMIThread::setToneFrequency(), TestSourceThread::setToneFrequency(), SSBMod::SSBMod(), and WFMMod::WFMMod().
 {
     m_phaseIncrement = (freq * TableSize) / sampleRate;
     qDebug("NCOF::setFreq: freq: %f m_phaseIncrement: %f", freq, m_phaseIncrement);
 }
setPhase()
void NCOF::setPhase (Real phase) inline
Definition at line 42 of file ncof.h.
Referenced by WFMMod::pullAF(), AMMod::pullAF(), NFMMod::pullAF(), FreeDVMod::pullAF(), and SSBMod::pullAF().
 { m_phase = phase; }
Member Data Documentation
m_phase
Real NCOF::m_phase private
Definition at line 36 of file ncof.h.
Referenced by get(), getIQ(), getQI(), and NCOF().
m_phaseIncrement
Real NCOF::m_phaseIncrement private
Definition at line 35 of file ncof.h.
Referenced by NCOF(), and setFreq().
m_table
Real NCOF::m_table static private
Definition at line 29 of file ncof.h.
Referenced by get(), getIQ(), getQI(), initTable(), next(), nextIQ(), and nextQI().
m_tableInitialized
bool NCOF::m_tableInitialized = false static private
Definition at line 30 of file ncof.h.
Referenced by initTable().
m_tableSizeLimit
float NCOF::m_tableSizeLimit = (float) NCOF::TableSize static private
Definition at line 31 of file ncof.h.
The documentation for this class was generated from the following files:
sdrbase/dsp/ncof.h
sdrbase/dsp/ncof.cpp