SDRAngel: Message Class Reference
Message Class Reference
#include <message.h>
Public Member Functions
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static bool match (const Message *message)
Protected Attributes
void * m_destination
Static Protected Attributes
static const char * m_identifier = 0
Detailed Description
Definition at line 25 of file message.h.
Constructor & Destructor Documentation
Message()
Message::Message ()
Definition at line 26 of file message.cpp.
                  :
     m_destination(0)
 {
 }
~Message()
Message::~Message () virtual
Definition at line 31 of file message.cpp.
 {
 }
Member Function Documentation
getDestination()
void* Message::getDestination () const inline
Definition at line 34 of file message.h.
 { return m_destination; }
getIdentifier()
const char * Message::getIdentifier () const virtual
Definition at line 35 of file message.cpp.
References m_identifier.
Referenced by FCDProGui::handleInputMessages(), Bladerf1OutputGui::handleInputMessages(), SDRPlayGui::handleInputMessages(), BladeRF2OutputGui::handleInputMessages(), Bladerf1InputGui::handleInputMessages(), BladeRF2InputGui::handleInputMessages(), RTLSDRGui::handleInputMessages(), LimeSDROutputGUI::handleInputMessages(), HackRFInputGui::handleInputMessages(), HackRFOutputGui::handleInputMessages(), PerseusGui::handleInputMessages(), PlutoSDROutputGUI::handleInputMessages(), AirspyGui::handleInputMessages(), AirspyHFGui::handleInputMessages(), GLSpectrumGUI::handleInputMessages(), PlutoSDRInputGui::handleInputMessages(), ChannelAnalyzerGUI::handleInputMessages(), SoapySDRInputGui::handleInputMessages(), SoapySDROutputGui::handleInputMessages(), DSPDeviceSinkEngine::handleInputMessages(), UDPSinkFECWorker::handleInputMessages(), DSPDeviceSourceEngine::handleInputMessages(), DSPDeviceMIMOEngine::handleInputMessages(), DownChannelizer::handleMessage(), UpChannelizer::handleMessage(), LocalOutput::handleMessage(), BFMDemod::handleMessage(), LocalInput::handleMessage(), RemoteOutput::handleMessage(), ScopeVis::handleMessage(), RemoteInput::handleMessage(), MainCore::handleMessages(), MainWindow::handleMessages(), DSPDeviceSinkEngine::handleSynchronousMessages(), DSPDeviceSourceEngine::handleSynchronousMessages(), DSPDeviceMIMOEngine::handleSynchronousMessages(), and MessageQueue::~MessageQueue().
 {
     return m_identifier;
 }
match()
bool Message::match (const Message * message) static
Definition at line 45 of file message.cpp.
References m_identifier, and matchIdentifier().
Referenced by LocalSinkThread::handleInputMessages(), FCDProPlusGui::handleInputMessages(), FCDProGui::handleInputMessages(), LocalSourceThread::handleInputMessages(), SDRPlayGui::handleInputMessages(), Bladerf1OutputGui::handleInputMessages(), BladeRF2OutputGui::handleInputMessages(), Bladerf1InputGui::handleInputMessages(), KiwiSDRGui::handleInputMessages(), TestSourceGui::handleInputMessages(), BladeRF2InputGui::handleInputMessages(), RTLSDRGui::handleInputMessages(), XTRXOutputGUI::handleInputMessages(), XTRXInputGUI::handleInputMessages(), TestMIGui::handleInputMessages(), LimeSDRInputGUI::handleInputMessages(), LimeSDROutputGUI::handleInputMessages(), FileSinkGui::handleInputMessages(), HackRFInputGui::handleInputMessages(), HackRFOutputGui::handleInputMessages(), LocalOutputGui::handleInputMessages(), FileInputGUI::handleInputMessages(), RemoteSinkThread::handleInputMessages(), PerseusGui::handleInputMessages(), PlutoSDROutputGUI::handleInputMessages(), AirspyGui::handleInputMessages(), AirspyHFGui::handleInputMessages(), RemoteSourceThread::handleInputMessages(), PlutoSDRInputGui::handleInputMessages(), SoapySDRInputGui::handleInputMessages(), SoapySDROutputGui::handleInputMessages(), LocalInputGui::handleInputMessages(), RemoteInputGui::handleInputMessages(), DSPDeviceSinkEngine::handleInputMessages(), UDPSinkFECWorker::handleInputMessages(), AMBEWorker::handleInputMessages(), RemoteOutputSinkGui::handleInputMessages(), DSPDeviceSourceEngine::handleInputMessages(), DSPDeviceMIMOEngine::handleInputMessages(), TestMIThread::handleInputMessages(), TestSourceThread::handleInputMessages(), WFMDemodGUI::handleMessage(), NFMDemodGUI::handleMessage(), AMDemodGUI::handleMessage(), SSBDemodGUI::handleMessage(), XTRXOutputGUI::handleMessage(), AirspyGui::handleMessage(), Bladerf1InputGui::handleMessage(), BladeRF2InputGui::handleMessage(), FCDProPlusGui::handleMessage(), LimeSDRInputGUI::handleMessage(), PerseusGui::handleMessage(), XTRXInputGUI::handleMessage(), RTLSDRGui::handleMessage(), TestSourceGui::handleMessage(), LimeSDROutputGUI::handleMessage(), AirspyHFGui::handleMessage(), FCDProGui::handleMessage(), FileInputGUI::handleMessage(), TestMIGui::handleMessage(), Bladerf1OutputGui::handleMessage(), BladeRF2OutputGui::handleMessage(), SDRPlayGui::handleMessage(), PlutoSDROutputGUI::handleMessage(), NFMModGUI::handleMessage(), KiwiSDRGui::handleMessage(), PlutoSDRInputGui::handleMessage(), FileSinkGui::handleMessage(), FileSourceGUI::handleMessage(), ATVModGUI::handleMessage(), RemoteSourceGUI::handleMessage(), RemoteInputGui::handleMessage(), LocalOutputGui::handleMessage(), AMModGUI::handleMessage(), BFMDemodGUI::handleMessage(), FreqTrackerGUI::handleMessage(), ATVDemodGUI::handleMessage(), WFMModGUI::handleMessage(), UDPSourceGUI::handleMessage(), LocalInputGui::handleMessage(), LocalSourceGUI::handleMessage(), FreeDVModGUI::handleMessage(), SSBModGUI::handleMessage(), LocalSinkGUI::handleMessage(), RemoteSinkGUI::handleMessage(), UDPSinkGUI::handleMessage(), FileRecord::handleMessage(), ChannelAnalyzerGUI::handleMessage(), FreeDVDemodGUI::handleMessage(), SoapySDRInputGui::handleMessage(), DATVDemodGUI::handleMessage(), SoapySDROutputGui::handleMessage(), DSDDemodGUI::handleMessage(), HackRFInputGui::handleMessage(), HackRFOutputGui::handleMessage(), GLSpectrumGUI::handleMessage(), SpectrumVis::handleMessage(), RemoteOutputSinkGui::handleMessage(), DownChannelizer::handleMessage(), UpChannelizer::handleMessage(), UDPSourceUDPHandler::handleMessage(), PlutoSDROutput::handleMessage(), LoRaDemod::handleMessage(), UDPSource::handleMessage(), WFMDemod::handleMessage(), AMDemod::handleMessage(), DSDDemod::handleMessage(), UDPSink::handleMessage(), LocalSink::handleMessage(), LocalSource::handleMessage(), Bladerf1Output::handleMessage(), HackRFOutput::handleMessage(), TestSourceInput::handleMessage(), RTLSDRInput::handleMessage(), AirspyInput::handleMessage(), PerseusInput::handleMessage(), AirspyHFInput::handleMessage(), RemoteSink::handleMessage(), Bladerf1Input::handleMessage(), PlutoSDRInput::handleMessage(), SSBDemod::handleMessage(), LocalOutput::handleMessage(), NFMDemod::handleMessage(), TestMI::handleMessage(), FCDProInput::handleMessage(), FreqTracker::handleMessage(), FCDProPlusInput::handleMessage(), BladeRF2Output::handleMessage(), BFMDemod::handleMessage(), FreeDVDemod::handleMessage(), HackRFInput::handleMessage(), KiwiSDRInput::handleMessage(), ChannelAnalyzer::handleMessage(), SoapySDROutput::handleMessage(), LocalInput::handleMessage(), RemoteOutput::handleMessage(), DATVDemod::handleMessage(), SDRPlayInput::handleMessage(), BladeRF2Input::handleMessage(), SoapySDRInput::handleMessage(), FileSinkOutput::handleMessage(), RemoteSource::handleMessage(), XTRXOutput::handleMessage(), LimeSDROutput::handleMessage(), AMMod::handleMessage(), WFMMod::handleMessage(), NFMMod::handleMessage(), SSBMod::handleMessage(), XTRXInput::handleMessage(), FreeDVMod::handleMessage(), LimeSDRInput::handleMessage(), ATVDemod::handleMessage(), ScopeVis::handleMessage(), RemoteInput::handleMessage(), MainCore::handleMessage(), FileInput::handleMessage(), FileSource::handleMessage(), MainWindow::handleMessage(), ATVMod::handleMessage(), DSPDeviceSinkEngine::handleSynchronousMessages(), DSPDeviceSourceEngine::handleSynchronousMessages(), and DSPDeviceMIMOEngine::handleSynchronousMessages().
 {
     return message->matchIdentifier(m_identifier);
 }
matchIdentifier()
bool Message::matchIdentifier (const char * identifier) const virtual
Definition at line 40 of file message.cpp.
References m_identifier.
Referenced by match().
 {
     return m_identifier == identifier;
 }
setDestination()
void Message::setDestination (void * destination) inline
Definition at line 35 of file message.h.
 { m_destination = destination; }
Member Data Documentation
m_destination
void* Message::m_destination protected
Definition at line 40 of file message.h.
m_identifier
const char * Message::m_identifier = 0 static protected
Definition at line 39 of file message.h.
Referenced by getIdentifier(), match(), and matchIdentifier().
The documentation for this class was generated from the following files:
sdrbase/util/message.h
sdrbase/util/message.cpp