SDRAngel: XTRXInput::MsgConfigureXTRX Class Reference
XTRXInput::MsgConfigureXTRX Class Reference
#include <xtrxinput.h>
Public Member Functions
const XTRXInputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureXTRX * create (const XTRXInputSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureXTRX (const XTRXInputSettings &settings, bool force)
Private Attributes
XTRXInputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 42 of file xtrxinput.h.
Constructor & Destructor Documentation
MsgConfigureXTRX()
XTRXInput::MsgConfigureXTRX::MsgConfigureXTRX (const XTRXInputSettings & settings, bool force) inline private
Definition at line 58 of file xtrxinput.h.
Referenced by create().
                                                                         :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureXTRX* XTRXInput::MsgConfigureXTRX::create (const XTRXInputSettings & settings, bool force) inline static
Definition at line 49 of file xtrxinput.h.
References MsgConfigureXTRX().
Referenced by XTRXInput::deserialize(), XTRXInput::setCenterFrequency(), XTRXInputGUI::updateHardware(), and XTRXInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureXTRX(settings, force);
         }
getForce()
bool XTRXInput::MsgConfigureXTRX::getForce () const inline
Definition at line 47 of file xtrxinput.h.
References m_force.
Referenced by XTRXInput::handleMessage().
 { return m_force; }
getSettings()
const XTRXInputSettings& XTRXInput::MsgConfigureXTRX::getSettings () const inline
Definition at line 46 of file xtrxinput.h.
References m_settings.
Referenced by XTRXInputGUI::handleInputMessages(), and XTRXInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool XTRXInput::MsgConfigureXTRX::m_force private
Definition at line 56 of file xtrxinput.h.
Referenced by getForce().
m_settings
XTRXInputSettings XTRXInput::MsgConfigureXTRX::m_settings private
Definition at line 55 of file xtrxinput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/xtrxinput/xtrxinput.h