SDRAngel: PhaseDiscriminators Class Reference
PhaseDiscriminators Class Reference
#include <phasediscri.h>
Public Member Functions
void reset ()
void setFMScaling (Real fmScaling)
Real phaseDiscriminator (const Complex &sample)
Real phaseDiscriminatorDelta (const Complex &sample, double &magsq, Real &fmDev)
Real phaseDiscriminator2 (const Complex &sample)
Real phaseDiscriminator3 (const Complex &sample, long double &magsq, Real &fltVal)
Private Member Functions
float atan2_approximation1 (float y, float x)
float atan2_approximation2 (float y, float x)
Private Attributes
Complex m_m1Sample
Complex m_m2Sample
Real m_fmScaling
Real m_fltPreviousI
Real m_fltPreviousQ
Real m_fltPreviousI2
Real m_fltPreviousQ2
Real m_prevArg
Detailed Description
Definition at line 27 of file phasediscri.h.
Member Function Documentation
atan2_approximation1()
float PhaseDiscriminators::atan2_approximation1 (float y, float x) inline private
Definition at line 142 of file phasediscri.h.
References M_PI.
     {
         //http://pubs.opengroup.org/onlinepubs/009695399/functions/atan2.html
         //Volkan SALMA
         const float ONEQTR_PI = M_PI / 4.0;
         const float THRQTR_PI = 3.0 * M_PI / 4.0;
         float r, angle;
         float abs_y = std::fabs(y) + 1e-10f;      // kludge to prevent 0/0 condition
         if ( x < 0.0f )
         {
             r = (x + abs_y) / (abs_y - x);
             angle = THRQTR_PI;
         }
         else
         {
             r = (x - abs_y) / (x + abs_y);
             angle = ONEQTR_PI;
         }
         angle += (0.1963f * r * r - 0.9817f) * r;
         if ( y < 0.0f )
             return( -angle );     // negate if in quad III or IV
         else
             return( angle );
     }
atan2_approximation2()
float PhaseDiscriminators::atan2_approximation2 (float y, float x) inline private
Definition at line 173 of file phasediscri.h.
References PI_FLOAT, and PIBY2_FLOAT.
Referenced by phaseDiscriminatorDelta().
     {
         if ( x == 0.0f )
         {
             if ( y > 0.0f ) return PIBY2_FLOAT;
             if ( y == 0.0f ) return 0.0f;
             return -PIBY2_FLOAT;
         }
         float atan;
         float z = y/x;
         if ( std::fabs( z ) < 1.0f )
         {
             atan = z/(1.0f + 0.28f*z*z);
             if ( x < 0.0f )
             {
                 if ( y < 0.0f ) return atan - PI_FLOAT;
                 return atan + PI_FLOAT;
             }
         }
         else
         {
             atan = PIBY2_FLOAT - z/(z*z + 0.28f);
             if ( y < 0.0f ) return atan - PI_FLOAT;
         }
         return atan;
     }
phaseDiscriminator()
Real PhaseDiscriminators::phaseDiscriminator (const Complex & sample) inline
Standard discriminator using atan2. On modern processors this is as efficient as the non atan2 one. This is better for high fidelity.
Definition at line 51 of file phasediscri.h.
References m_fmScaling, m_m1Sample, and M_PI.
Referenced by DSDDemod::feed(), UDPSink::feed(), and BFMDemod::feed().
     {
         Complex d(std::conj(m_m1Sample) * sample);
         m_m1Sample = sample;
         return (std::atan2(d.imag(), d.real()) / M_PI) * m_fmScaling;
     }
phaseDiscriminator2()
Real PhaseDiscriminators::phaseDiscriminator2 (const Complex & sample) inline
Alternative without atan at the expense of a slight distorsion on very wideband signals http://www.embedded.com/design/configurable-systems/4212086/DSP-Tricks&ndash;Frequency-demodulation-algorithms- in addition it needs scaling by instantaneous magnitude squared and volume (0..10) adjustment factor
Definition at line 86 of file phasediscri.h.
References m_fmScaling, m_m1Sample, and m_m2Sample.
     {
         Real ip = sample.real() - m_m2Sample.real();
         Real qp = sample.imag() - m_m2Sample.imag();
         Real h1 = m_m1Sample.real() * qp;
         Real h2 = m_m1Sample.imag() * ip;
         m_m2Sample = m_m1Sample;
         m_m1Sample = sample;
         //return ((h1 - h2) / M_PI_2) * m_fmScaling;
         return (h1 - h2) * m_fmScaling;
     }
phaseDiscriminator3()
Real PhaseDiscriminators::phaseDiscriminator3 (const Complex & sample, long double & magsq, Real & fltVal) inline
Second alternative
Definition at line 103 of file phasediscri.h.
References m_fltPreviousI, m_fltPreviousI2, m_fltPreviousQ, m_fltPreviousQ2, m_fmScaling, and sqrt().
     {
         Real fltI = sample.real();
         Real fltQ = sample.imag();
         double fltNorm;
         Real fltNormI;
         Real fltNormQ;
         //Real fltVal;
         magsq = fltI*fltI + fltQ*fltQ;
         fltNorm = std::sqrt(magsq);
         fltNormI= fltI/fltNorm;
         fltNormQ= fltQ/fltNorm;
         fltVal = m_fltPreviousI*(fltNormQ - m_fltPreviousQ2);
         fltVal -= m_fltPreviousQ*(fltNormI - m_fltPreviousI2);
         fltVal += 2.0f;
         fltVal /= 4.0f; // normally it is /4
         m_fltPreviousQ2 = m_fltPreviousQ;
         m_fltPreviousI2 = m_fltPreviousI;
         m_fltPreviousQ = fltNormQ;
         m_fltPreviousI = fltNormI;
         return fltVal * m_fmScaling;
     }
phaseDiscriminatorDelta()
Real PhaseDiscriminators::phaseDiscriminatorDelta (const Complex & sample, double & magsq, Real & fmDev) inline
Discriminator with phase detection using atan2 and frequency by derivation. This yields a precise deviation to sample rate ratio: Sample rate => +/-1.0
Definition at line 62 of file phasediscri.h.
References atan2_approximation2(), m_fmScaling, M_PI, and m_prevArg.
Referenced by ATVDemod::demod(), WFMDemod::feed(), and NFMDemod::processOneSample().
     {
         Real fltI = sample.real();
         Real fltQ = sample.imag();
         magsq = fltI*fltI + fltQ*fltQ;
         Real curArg = atan2_approximation2((float) fltQ, (float) fltI);
         fmDev = (curArg - m_prevArg) / M_PI;
         m_prevArg = curArg;
         if (fmDev < -1.0f) {
             fmDev += 2.0f;
         } else if (fmDev > 1.0f) {
             fmDev -= 2.0f;
         }
         return fmDev * m_fmScaling;
     }
reset()
void PhaseDiscriminators::reset () inline
Reset stored values
Definition at line 33 of file phasediscri.h.
References m_m1Sample, and m_m2Sample.
Referenced by WFMDemod::start(), DSDDemod::start(), UDPSink::start(), NFMDemod::start(), and BFMDemod::start().
     {
         m_m1Sample = 0;
         m_m2Sample = 0;
     }
setFMScaling()
void PhaseDiscriminators::setFMScaling (Real fmScaling) inline
Scaling factor so that resulting excursion maps to [-1,+1]
Definition at line 42 of file phasediscri.h.
References m_fmScaling.
Referenced by WFMDemod::applyChannelSettings(), BFMDemod::applyChannelSettings(), WFMDemod::applySettings(), UDPSink::applySettings(), NFMDemod::applySettings(), DSDDemod::applySettings(), BFMDemod::applySettings(), ATVDemod::applySettings(), ATVDemod::ATVDemod(), BFMDemod::BFMDemod(), UDPSink::UDPSink(), and WFMDemod::WFMDemod().
     {
         m_fmScaling = fmScaling;
     }
Member Data Documentation
m_fltPreviousI
Real PhaseDiscriminators::m_fltPreviousI private
Definition at line 136 of file phasediscri.h.
Referenced by phaseDiscriminator3().
m_fltPreviousI2
Real PhaseDiscriminators::m_fltPreviousI2 private
Definition at line 138 of file phasediscri.h.
Referenced by phaseDiscriminator3().
m_fltPreviousQ
Real PhaseDiscriminators::m_fltPreviousQ private
Definition at line 137 of file phasediscri.h.
Referenced by phaseDiscriminator3().
m_fltPreviousQ2
Real PhaseDiscriminators::m_fltPreviousQ2 private
Definition at line 139 of file phasediscri.h.
Referenced by phaseDiscriminator3().
m_fmScaling
Real PhaseDiscriminators::m_fmScaling private
Definition at line 135 of file phasediscri.h.
Referenced by phaseDiscriminator(), phaseDiscriminator2(), phaseDiscriminator3(), phaseDiscriminatorDelta(), and setFMScaling().
m_m1Sample
Complex PhaseDiscriminators::m_m1Sample private
Definition at line 133 of file phasediscri.h.
Referenced by phaseDiscriminator(), phaseDiscriminator2(), and reset().
m_m2Sample
Complex PhaseDiscriminators::m_m2Sample private
Definition at line 134 of file phasediscri.h.
Referenced by phaseDiscriminator2(), and reset().
m_prevArg
Real PhaseDiscriminators::m_prevArg private
Definition at line 140 of file phasediscri.h.
Referenced by phaseDiscriminatorDelta().
The documentation for this class was generated from the following file:
sdrbase/dsp/phasediscri.h