SDRAngel: LimeSDRInput::MsgConfigureLimeSDR Class Reference
LimeSDRInput::MsgConfigureLimeSDR Class Reference
#include <limesdrinput.h>
Public Member Functions
const LimeSDRInputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureLimeSDR * create (const LimeSDRInputSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureLimeSDR (const LimeSDRInputSettings &settings, bool force)
Private Attributes
LimeSDRInputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 41 of file limesdrinput.h.
Constructor & Destructor Documentation
MsgConfigureLimeSDR()
LimeSDRInput::MsgConfigureLimeSDR::MsgConfigureLimeSDR (const LimeSDRInputSettings & settings, bool force) inline private
Definition at line 57 of file limesdrinput.h.
Referenced by create().
                                                                               :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureLimeSDR* LimeSDRInput::MsgConfigureLimeSDR::create (const LimeSDRInputSettings & settings, bool force) inline static
Definition at line 48 of file limesdrinput.h.
References MsgConfigureLimeSDR().
Referenced by LimeSDRInput::deserialize(), LimeSDRInput::setCenterFrequency(), LimeSDRInputGUI::updateHardware(), and LimeSDRInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureLimeSDR(settings, force);
         }
getForce()
bool LimeSDRInput::MsgConfigureLimeSDR::getForce () const inline
Definition at line 46 of file limesdrinput.h.
References m_force.
Referenced by LimeSDRInput::handleMessage().
 { return m_force; }
getSettings()
const LimeSDRInputSettings& LimeSDRInput::MsgConfigureLimeSDR::getSettings () const inline
Definition at line 45 of file limesdrinput.h.
References m_settings.
Referenced by LimeSDRInputGUI::handleInputMessages(), LimeSDRInputGUI::handleMessage(), and LimeSDRInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool LimeSDRInput::MsgConfigureLimeSDR::m_force private
Definition at line 55 of file limesdrinput.h.
Referenced by getForce().
m_settings
LimeSDRInputSettings LimeSDRInput::MsgConfigureLimeSDR::m_settings private
Definition at line 54 of file limesdrinput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/limesdrinput/limesdrinput.h