SDRAngel: PerseusInput::MsgStartStop Class Reference
PerseusInput::MsgStartStop Class Reference
#include <perseusinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 81 of file perseusinput.h.
Constructor & Destructor Documentation
MsgStartStop()
PerseusInput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 94 of file perseusinput.h.
References PerseusInput::deserialize(), PerseusInput::destroy(), PerseusInput::init(), PerseusInput::PerseusInput(), PerseusInput::serialize(), PerseusInput::start(), PerseusInput::stop(), and PerseusInput::~PerseusInput().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* PerseusInput::MsgStartStop::create (bool startStop) inline static
Definition at line 87 of file perseusinput.h.
Referenced by PerseusGui::on_startStop_toggled(), and PerseusInput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool PerseusInput::MsgStartStop::getStartStop () const inline
Definition at line 85 of file perseusinput.h.
Referenced by PerseusGui::handleMessage(), and PerseusInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool PerseusInput::MsgStartStop::m_startStop protected
Definition at line 92 of file perseusinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/perseus/perseusinput.h