SDRAngel: PluginInterface Class Reference
PluginInterface Class Reference abstract
#include <plugininterface.h>
Classes
struct SamplingDevice
Public Types
typedef QList< SamplingDevice > SamplingDevices
Public Member Functions
virtual ~PluginInterface ()
virtual const PluginDescriptor & getPluginDescriptor () const =0
virtual void initPlugin (PluginAPI *pluginAPI)=0
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Detailed Description
Definition at line 31 of file plugininterface.h.
Member Typedef Documentation
SamplingDevices
typedef QList<SamplingDevice> PluginInterface::SamplingDevices
Definition at line 80 of file plugininterface.h.
Constructor & Destructor Documentation
~PluginInterface()
virtual PluginInterface::~PluginInterface () inline virtual
Definition at line 82 of file plugininterface.h.
 { }
Member Function Documentation
createRxChannelBS()
virtual BasebandSampleSink* PluginInterface::createRxChannelBS (DeviceAPI * deviceAPI) inline virtual
Reimplemented in DATVDemodPlugin, ATVDemodPlugin, ChannelAnalyzerPlugin, DSDDemodPlugin, LocalSinkPlugin, RemoteSinkPlugin, UDPSinkPlugin, AMDemodPlugin, BFMPlugin, FreeDVPlugin, FreqTrackerPlugin, LoRaPlugin, NFMPlugin, SSBPlugin, and WFMPlugin.
Definition at line 98 of file plugininterface.h.
Referenced by PluginManager::createRxChannelInstance().
     {
         (void) deviceAPI;
         return nullptr;
     }
createRxChannelCS()
virtual ChannelAPI* PluginInterface::createRxChannelCS (DeviceAPI * deviceAPI) inline virtual
Reimplemented in DATVDemodPlugin, ATVDemodPlugin, ChannelAnalyzerPlugin, DSDDemodPlugin, LocalSinkPlugin, RemoteSinkPlugin, UDPSinkPlugin, AMDemodPlugin, BFMPlugin, FreeDVPlugin, FreqTrackerPlugin, LoRaPlugin, NFMPlugin, SSBPlugin, and WFMPlugin.
Definition at line 105 of file plugininterface.h.
     {
         (void) deviceAPI;
         return nullptr;
     }
createRxChannelGUI()
virtual PluginInstanceGUI* PluginInterface::createRxChannelGUI (DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) inline virtual
Reimplemented in DATVDemodPlugin, ATVDemodPlugin, ChannelAnalyzerPlugin, DSDDemodPlugin, LocalSinkPlugin, RemoteSinkPlugin, UDPSinkPlugin, AMDemodPlugin, BFMPlugin, FreeDVPlugin, FreqTrackerPlugin, LoRaPlugin, NFMPlugin, SSBPlugin, and WFMPlugin.
Definition at line 89 of file plugininterface.h.
Referenced by PluginManager::createRxChannelInstance().
     {
         (void) deviceUISet;
         (void) rxChannel;
         return nullptr;
     }
createSampleMIMOPluginInstance()
virtual DeviceSampleMIMO* PluginInterface::createSampleMIMOPluginInstance (const QString & mimoId, DeviceAPI * deviceAPI) inline virtual
Reimplemented in TestMIPlugin.
Definition at line 205 of file plugininterface.h.
References Q_DECLARE_INTERFACE().
Referenced by MainWindow::sampleMIMOChanged().
     {
         (void) mimoId;
         (void) deviceAPI;
         return nullptr;
     }
createSampleMIMOPluginInstanceGUI()
virtual PluginInstanceGUI* PluginInterface::createSampleMIMOPluginInstanceGUI (const QString & mimoId, QWidget ** widget, DeviceUISet * deviceUISet) inline virtual
Reimplemented in TestMIPlugin.
Definition at line 194 of file plugininterface.h.
Referenced by MainWindow::sampleMIMOChanged().
     {
         (void) mimoId;
         (void) widget;
         (void) deviceUISet;
         return nullptr;
     }
createSampleSinkPluginInstance()
virtual DeviceSampleSink* PluginInterface::createSampleSinkPluginInstance (const QString & sinkId, DeviceAPI * deviceAPI) inline virtual
Reimplemented in Bladerf1OutputPlugin, BladeRF2OutputPlugin, SoapySDROutputPlugin, FileSinkPlugin, RemoteOutputPlugin, HackRFOutputPlugin, LimeSDROutputPlugin, LocalOutputPlugin, PlutoSDROutputPlugin, and XTRXOutputPlugin.
Definition at line 178 of file plugininterface.h.
Referenced by MainCore::changeSampleSink(), and MainWindow::sampleSinkChanged().
     {
         (void) sinkId;
         (void) deviceAPI;
         return nullptr;
     }
createSampleSinkPluginInstanceGUI()
virtual PluginInstanceGUI* PluginInterface::createSampleSinkPluginInstanceGUI (const QString & sinkId, QWidget ** widget, DeviceUISet * deviceUISet) inline virtual
Reimplemented in Bladerf1OutputPlugin, BladeRF2OutputPlugin, FileSinkPlugin, RemoteOutputPlugin, SoapySDROutputPlugin, HackRFOutputPlugin, LimeSDROutputPlugin, LocalOutputPlugin, PlutoSDROutputPlugin, and XTRXOutputPlugin.
Definition at line 167 of file plugininterface.h.
Referenced by MainWindow::sampleSinkChanged().
     {
         (void) sinkId;
         (void) widget;
         (void) deviceUISet;
         return nullptr;
     }
createSampleSourcePluginInstance()
virtual DeviceSampleSource* PluginInterface::createSampleSourcePluginInstance (const QString & sourceId, DeviceAPI * deviceAPI) inline virtual
Reimplemented in Blderf1InputPlugin, Blderf2InputPlugin, SoapySDRInputPlugin, KiwiSDRPlugin, XTRXInputPlugin, AirspyPlugin, AirspyHFPlugin, FileInputPlugin, HackRFInputPlugin, LimeSDRInputPlugin, LocalInputPlugin, PerseusPlugin, PlutoSDRInputPlugin, RemoteInputPlugin, SDRPlayPlugin, TestSourcePlugin, FCDProPlugin, FCDProPlusPlugin, and RTLSDRPlugin.
Definition at line 152 of file plugininterface.h.
Referenced by MainCore::changeSampleSource(), and MainWindow::sampleSourceChanged().
     {
         (void) sourceId;
         (void) deviceAPI;
         return nullptr;
     }
createSampleSourcePluginInstanceGUI()
virtual PluginInstanceGUI* PluginInterface::createSampleSourcePluginInstanceGUI (const QString & sourceId, QWidget ** widget, DeviceUISet * deviceUISet) inline virtual
Reimplemented in Blderf1InputPlugin, Blderf2InputPlugin, SoapySDRInputPlugin, KiwiSDRPlugin, XTRXInputPlugin, AirspyPlugin, AirspyHFPlugin, FileInputPlugin, HackRFInputPlugin, LimeSDRInputPlugin, LocalInputPlugin, PerseusPlugin, PlutoSDRInputPlugin, RemoteInputPlugin, SDRPlayPlugin, TestSourcePlugin, FCDProPlugin, FCDProPlusPlugin, and RTLSDRPlugin.
Definition at line 141 of file plugininterface.h.
Referenced by MainWindow::sampleSourceChanged().
     {
         (void) sourceId;
         (void) widget;
         (void) deviceUISet;
         return nullptr;
     }
createTxChannelBS()
virtual BasebandSampleSource* PluginInterface::createTxChannelBS (DeviceAPI * deviceAPI) inline virtual
Reimplemented in LocalSourcePlugin, UDPSourcePlugin, FileSourcePlugin, AMModPlugin, ATVModPlugin, FreeDVModPlugin, NFMModPlugin, SSBModPlugin, RemoteSourcePlugin, and WFMModPlugin.
Definition at line 123 of file plugininterface.h.
Referenced by PluginManager::createTxChannelInstance().
     {
         (void) deviceAPI;
         return nullptr;
     }
createTxChannelCS()
virtual ChannelAPI* PluginInterface::createTxChannelCS (DeviceAPI * deviceAPI) inline virtual
Reimplemented in LocalSourcePlugin, UDPSourcePlugin, FileSourcePlugin, AMModPlugin, ATVModPlugin, FreeDVModPlugin, NFMModPlugin, SSBModPlugin, RemoteSourcePlugin, and WFMModPlugin.
Definition at line 130 of file plugininterface.h.
     {
         (void) deviceAPI;
         return nullptr;
     }
createTxChannelGUI()
virtual PluginInstanceGUI* PluginInterface::createTxChannelGUI (DeviceUISet * deviceUISet, BasebandSampleSource * txChannel) inline virtual
Reimplemented in LocalSourcePlugin, UDPSourcePlugin, FileSourcePlugin, AMModPlugin, ATVModPlugin, FreeDVModPlugin, NFMModPlugin, SSBModPlugin, RemoteSourcePlugin, and WFMModPlugin.
Definition at line 114 of file plugininterface.h.
Referenced by PluginManager::createTxChannelInstance().
     {
         (void) deviceUISet;
         (void) txChannel;
         return nullptr;
     }
deleteSampleMIMOPluginInstanceGUI()
void PluginInterface::deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI * ui) virtual
Definition at line 28 of file plugininterface.cpp.
References PluginInstanceGUI::destroy().
Referenced by MainWindow::sampleMIMOChanged().
 {
     if (ui) { ui->destroy(); }
 }
deleteSampleMIMOPluginInstanceMIMO()
void PluginInterface::deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO * mimo) virtual
Definition at line 33 of file plugininterface.cpp.
References DeviceSampleMIMO::destroy().
Referenced by MainWindow::sampleMIMOChanged().
 {
     if (mimo) { mimo->destroy(); }
 }
deleteSampleSinkPluginInstanceGUI()
void PluginInterface::deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI * ui) virtual
Definition at line 18 of file plugininterface.cpp.
References PluginInstanceGUI::destroy().
 {
     if (ui) { ui->destroy(); }
 }
deleteSampleSinkPluginInstanceOutput()
void PluginInterface::deleteSampleSinkPluginInstanceOutput (DeviceSampleSink * sink) virtual
Definition at line 23 of file plugininterface.cpp.
References DeviceSampleSink::destroy().
Referenced by MainCore::changeSampleSink(), and MainWindow::sampleSinkChanged().
 {
     if (sink) { sink->destroy(); }
 }
deleteSampleSourcePluginInstanceGUI()
void PluginInterface::deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI * ui) virtual
Definition at line 8 of file plugininterface.cpp.
References PluginInstanceGUI::destroy().
Referenced by MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 {
     if (ui) { ui->destroy(); }
 }
deleteSampleSourcePluginInstanceInput()
void PluginInterface::deleteSampleSourcePluginInstanceInput (DeviceSampleSource * source) virtual
Definition at line 13 of file plugininterface.cpp.
References DeviceSampleSource::destroy().
Referenced by MainCore::changeSampleSource(), and MainWindow::sampleSourceChanged().
 {
     if (source) { source->destroy(); }
 }
enumSampleMIMO()
virtual SamplingDevices PluginInterface::enumSampleMIMO () inline virtual
Reimplemented in TestMIPlugin.
Definition at line 192 of file plugininterface.h.
 { return SamplingDevices(); }
enumSampleSinks()
virtual SamplingDevices PluginInterface::enumSampleSinks () inline virtual
Reimplemented in FileSinkPlugin, RemoteOutputPlugin, Bladerf1OutputPlugin, BladeRF2OutputPlugin, HackRFOutputPlugin, LimeSDROutputPlugin, LocalOutputPlugin, PlutoSDROutputPlugin, SoapySDROutputPlugin, and XTRXOutputPlugin.
Definition at line 165 of file plugininterface.h.
 { return SamplingDevices(); }
enumSampleSources()
virtual SamplingDevices PluginInterface::enumSampleSources () inline virtual
Reimplemented in Blderf1InputPlugin, Blderf2InputPlugin, SoapySDRInputPlugin, KiwiSDRPlugin, XTRXInputPlugin, AirspyPlugin, AirspyHFPlugin, FileInputPlugin, HackRFInputPlugin, LimeSDRInputPlugin, LocalInputPlugin, PerseusPlugin, PlutoSDRInputPlugin, RemoteInputPlugin, SDRPlayPlugin, TestSourcePlugin, FCDProPlugin, FCDProPlusPlugin, and RTLSDRPlugin.
Definition at line 139 of file plugininterface.h.
 { return SamplingDevices(); }
getPluginDescriptor()
virtual const PluginDescriptor& PluginInterface::getPluginDescriptor () const pure virtual
Implemented in DATVDemodPlugin, Blderf1InputPlugin, Blderf2InputPlugin, SoapySDRInputPlugin, ATVDemodPlugin, FileSinkPlugin, RemoteOutputPlugin, KiwiSDRPlugin, XTRXInputPlugin, ChannelAnalyzerPlugin, DSDDemodPlugin, LocalSinkPlugin, RemoteSinkPlugin, UDPSinkPlugin, LocalSourcePlugin, UDPSourcePlugin, TestMIPlugin, Bladerf1OutputPlugin, BladeRF2OutputPlugin, HackRFOutputPlugin, LimeSDROutputPlugin, LocalOutputPlugin, PlutoSDROutputPlugin, SoapySDROutputPlugin, XTRXOutputPlugin, AirspyPlugin, AirspyHFPlugin, FileInputPlugin, HackRFInputPlugin, LimeSDRInputPlugin, LocalInputPlugin, PerseusPlugin, PlutoSDRInputPlugin, RemoteInputPlugin, SDRPlayPlugin, TestSourcePlugin, AMDemodPlugin, BFMPlugin, FreeDVPlugin, FreqTrackerPlugin, FileSourcePlugin, AMModPlugin, ATVModPlugin, FreeDVModPlugin, NFMModPlugin, SSBModPlugin, RemoteSourcePlugin, WFMModPlugin, FCDProPlugin, FCDProPlusPlugin, RTLSDRPlugin, LoRaPlugin, NFMPlugin, SSBPlugin, and WFMPlugin.
Referenced by WebAPIAdapterGUI::instanceChannels(), WebAPIAdapterSrv::instanceChannels(), PluginManager::registerRxChannel(), PluginManager::registerSampleMIMO(), PluginManager::registerSampleSink(), PluginManager::registerSampleSource(), and PluginManager::registerTxChannel().
initPlugin()
virtual void PluginInterface::initPlugin (PluginAPI * pluginAPI) pure virtual
Implemented in DATVDemodPlugin, Blderf1InputPlugin, Blderf2InputPlugin, SoapySDRInputPlugin, ATVDemodPlugin, FileSinkPlugin, RemoteOutputPlugin, KiwiSDRPlugin, XTRXInputPlugin, ChannelAnalyzerPlugin, DSDDemodPlugin, LocalSinkPlugin, RemoteSinkPlugin, UDPSinkPlugin, LocalSourcePlugin, UDPSourcePlugin, TestMIPlugin, Bladerf1OutputPlugin, BladeRF2OutputPlugin, HackRFOutputPlugin, LimeSDROutputPlugin, LocalOutputPlugin, PlutoSDROutputPlugin, SoapySDROutputPlugin, XTRXOutputPlugin, AirspyPlugin, AirspyHFPlugin, FileInputPlugin, HackRFInputPlugin, LimeSDRInputPlugin, LocalInputPlugin, PerseusPlugin, PlutoSDRInputPlugin, RemoteInputPlugin, SDRPlayPlugin, TestSourcePlugin, AMDemodPlugin, BFMPlugin, FreeDVPlugin, FreqTrackerPlugin, FileSourcePlugin, AMModPlugin, ATVModPlugin, FreeDVModPlugin, NFMModPlugin, SSBModPlugin, RemoteSourcePlugin, WFMModPlugin, FCDProPlugin, FCDProPlusPlugin, RTLSDRPlugin, LoRaPlugin, NFMPlugin, SSBPlugin, and WFMPlugin.
The documentation for this class was generated from the following files:
sdrbase/plugin/plugininterface.h
sdrbase/plugin/plugininterface.cpp