SDRAngel: RTLSDRInput Class Reference
RTLSDRInput Class Reference
#include <rtlsdrinput.h>
Classes
class MsgConfigureRTLSDR
class MsgFileRecord
class MsgStartStop
Public Member Functions
RTLSDRInput (DeviceAPI *deviceAPI)
virtual ~RTLSDRInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
const std::vector< int > & getGains () const
void set_ds_mode (int on)
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Static Public Attributes
static const quint64 frequencyLowRangeMin = 0UL
static const quint64 frequencyLowRangeMax = 275000UL
static const quint64 frequencyHighRangeMin = 24000UL
static const quint64 frequencyHighRangeMax = 1900000UL
static const int sampleRateLowRangeMin = 230000U
static const int sampleRateLowRangeMax = 300000U
static const int sampleRateHighRangeMin = 950000U
static const int sampleRateHighRangeMax = 2400000U
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
bool applySettings (const RTLSDRSettings &settings, bool force)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const RTLSDRSettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const RTLSDRSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
FileRecord * m_fileSink
File sink to record device I/Q output.
QMutex m_mutex
RTLSDRSettings m_settings
rtlsdr_dev_t * m_dev
RTLSDRThread * m_rtlSDRThread
QString m_deviceDescription
std::vector< int > m_gains
bool m_running
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 36 of file rtlsdrinput.h.
Constructor & Destructor Documentation
RTLSDRInput()
RTLSDRInput::RTLSDRInput (DeviceAPI * deviceAPI)
Definition at line 52 of file rtlsdrinput.cpp.
References DeviceAPI::addAncillarySink(), arg(), DeviceAPI::getDeviceUID(), m_deviceAPI, m_fileSink, m_networkManager, networkManagerFinished(), openDevice(), and DeviceAPI::setNbSourceStreams().
Referenced by RTLSDRInput::MsgStartStop::MsgStartStop().
                                              :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_dev(0),
     m_rtlSDRThread(0),
     m_deviceDescription(),
     m_running(false)
 {
     openDevice();
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~RTLSDRInput()
RTLSDRInput::~RTLSDRInput () virtual
Definition at line 70 of file rtlsdrinput.cpp.
References closeDevice(), m_deviceAPI, m_fileSink, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::removeAncillarySink(), and stop().
Referenced by RTLSDRInput::MsgStartStop::MsgStartStop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
     closeDevice();
 }
Member Function Documentation
applySettings()
bool RTLSDRInput::applySettings (const RTLSDRSettings & settings, bool force) private
Definition at line 369 of file rtlsdrinput.cpp.
References DeviceSampleSource::calculateDeviceCenterFrequency(), DeviceAPI::configureCorrections(), DeviceAPI::getDeviceEngineInputMessageQueue(), FileRecord::handleMessage(), RTLSDRSettings::m_agc, RTLSDRSettings::m_centerFrequency, RTLSDRSettings::m_dcBlock, m_dev, m_deviceAPI, RTLSDRSettings::m_devSampleRate, RTLSDRSettings::m_fcPos, m_fileSink, RTLSDRSettings::m_gain, RTLSDRSettings::m_iqImbalance, RTLSDRSettings::m_log2Decim, RTLSDRSettings::m_loPpmCorrection, RTLSDRSettings::m_lowSampleRate, RTLSDRSettings::m_noModMode, RTLSDRSettings::m_offsetTuning, RTLSDRSettings::m_reverseAPIAddress, RTLSDRSettings::m_reverseAPIDeviceIndex, RTLSDRSettings::m_reverseAPIPort, RTLSDRSettings::m_rfBandwidth, m_rtlSDRThread, m_settings, RTLSDRSettings::m_transverterDeltaFrequency, RTLSDRSettings::m_transverterMode, RTLSDRSettings::m_useReverseAPI, MessageQueue::push(), set_ds_mode(), RTLSDRThread::setFcPos(), RTLSDRThread::setLog2Decimation(), RTLSDRThread::setSamplerate(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     bool forwardChange = false;
     QList<QString> reverseAPIKeys;
     if ((m_settings.m_agc != settings.m_agc) || force)
     {
         reverseAPIKeys.append("agc");
         if (rtlsdr_set_agc_mode(m_dev, settings.m_agc ? 1 : 0) < 0) {
             qCritical("RTLSDRInput::applySettings: could not set AGC mode %s", settings.m_agc ? "on" : "off");
         } else {
             qDebug("RTLSDRInput::applySettings: AGC mode %s", settings.m_agc ? "on" : "off");
         }
     }
     if ((m_settings.m_dcBlock != settings.m_dcBlock) || (m_settings.m_iqImbalance != settings.m_iqImbalance) || force)
     {
         reverseAPIKeys.append("dcBlock");
         reverseAPIKeys.append("iqImbalance");
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqImbalance);
         qDebug("RTLSDRInput::applySettings: corrections: DC block: %s IQ imbalance: %s",
                 settings.m_dcBlock ? "true" : "false",
                 settings.m_iqImbalance ? "true" : "false");
     }
     if ((m_settings.m_loPpmCorrection != settings.m_loPpmCorrection) || force)
     {
         reverseAPIKeys.append("loPpmCorrection");
         if (m_dev != 0)
         {
             if (rtlsdr_set_freq_correction(m_dev, settings.m_loPpmCorrection) < 0) {
                 qCritical("RTLSDRInput::applySettings: could not set LO ppm correction: %d", settings.m_loPpmCorrection);
             } else {
                 qDebug("RTLSDRInput::applySettings: LO ppm correction set to: %d", settings.m_loPpmCorrection);
             }
         }
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || force)
     {
         reverseAPIKeys.append("devSampleRate");
         forwardChange = true;
         if(m_dev != 0)
         {
             if( rtlsdr_set_sample_rate(m_dev, settings.m_devSampleRate) < 0)
             {
                 qCritical("RTLSDRInput::applySettings: could not set sample rate: %d", settings.m_devSampleRate);
             }
             else
             {
                 if (m_rtlSDRThread) {
                     m_rtlSDRThread->setSamplerate(settings.m_devSampleRate);
                 }
                 qDebug("RTLSDRInput::applySettings: sample rate set to %d", settings.m_devSampleRate);
             }
         }
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         reverseAPIKeys.append("log2Decim");
         forwardChange = true;
         if (m_rtlSDRThread != 0) {
             m_rtlSDRThread->setLog2Decimation(settings.m_log2Decim);
         }
         qDebug("RTLSDRInput::applySettings: log2decim set to %d", settings.m_log2Decim);
     }
     if ((m_settings.m_fcPos != settings.m_fcPos) || force)
     {
         reverseAPIKeys.append("fcPos");
         if (m_rtlSDRThread != 0) {
             m_rtlSDRThread->setFcPos((int) settings.m_fcPos);
         }
         qDebug() << "RTLSDRInput::applySettings: set fc pos (enum) to " << (int) settings.m_fcPos;
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency) || force) {
         reverseAPIKeys.append("centerFrequency");
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || force) {
         reverseAPIKeys.append("devSampleRate");
     }
     if ((m_settings.m_transverterMode != settings.m_transverterMode) || force) {
         reverseAPIKeys.append("transverterMode");
     }
     if ((m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency) || force) {
         reverseAPIKeys.append("transverterDeltaFrequency");
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency)
         || (m_settings.m_fcPos != settings.m_fcPos)
         || (m_settings.m_log2Decim != settings.m_log2Decim)
         || (m_settings.m_devSampleRate != settings.m_devSampleRate)
         || (m_settings.m_transverterMode != settings.m_transverterMode)
         || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency) || force)
     {
         qint64 deviceCenterFrequency = DeviceSampleSource::calculateDeviceCenterFrequency(
                 settings.m_centerFrequency,
                 settings.m_transverterDeltaFrequency,
                 settings.m_log2Decim,
                 (DeviceSampleSource::fcPos_t) settings.m_fcPos,
                 settings.m_devSampleRate,
                 DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD,
                 settings.m_transverterMode);
         forwardChange = true;
         if (m_dev != 0)
         {
             if (rtlsdr_set_center_freq(m_dev, deviceCenterFrequency) != 0) {
                 qWarning("RTLSDRInput::applySettings: rtlsdr_set_center_freq(%lld) failed", deviceCenterFrequency);
             } else {
                 qDebug("RTLSDRInput::applySettings: rtlsdr_set_center_freq(%lld)", deviceCenterFrequency);
             }
         }
     }
     if ((m_settings.m_noModMode != settings.m_noModMode) || force)
     {
         reverseAPIKeys.append("noModMode");
         qDebug() << "RTLSDRInput::applySettings: set noModMode to " << settings.m_noModMode;
         // Direct Modes: 0: off, 1: I, 2: Q, 3: NoMod.
         if (settings.m_noModMode) {
             set_ds_mode(3);
         } else {
             set_ds_mode(0);
         }
     }
     if ((m_settings.m_lowSampleRate != settings.m_lowSampleRate) || force) {
         reverseAPIKeys.append("lowSampleRate");
     }
     if ((m_settings.m_rfBandwidth != settings.m_rfBandwidth) || force)
     {
         reverseAPIKeys.append("rfBandwidth");
         m_settings.m_rfBandwidth = settings.m_rfBandwidth;
         if (m_dev != 0)
         {
             if (rtlsdr_set_tuner_bandwidth( m_dev, m_settings.m_rfBandwidth) != 0) {
                 qCritical("RTLSDRInput::applySettings: could not set RF bandwidth to %u", m_settings.m_rfBandwidth);
             } else {
                 qDebug() << "RTLSDRInput::applySettings: set RF bandwidth to " << m_settings.m_rfBandwidth;
             }
         }
     }
     if ((m_settings.m_offsetTuning != settings.m_offsetTuning) || force)
     {
         reverseAPIKeys.append("offsetTuning");
         if (m_dev != 0)
         {
             if (rtlsdr_set_offset_tuning(m_dev, m_settings.m_offsetTuning ? 0 : 1) != 0) {
                 qCritical("RTLSDRInput::applySettings: could not set offset tuning to %s", settings.m_offsetTuning ? "on" : "off");
             } else {
                 qDebug("RTLSDRInput::applySettings: offset tuning set to %s", settings.m_offsetTuning ? "on" : "off");
             }
         }
     }
     if ((m_settings.m_gain != settings.m_gain) || force)
     {
         reverseAPIKeys.append("gain");
         if(m_dev != 0)
         {
             if (rtlsdr_set_tuner_gain(m_dev, settings.m_gain) != 0) {
                 qCritical("RTLSDRInput::applySettings: rtlsdr_set_tuner_gain() failed");
             } else {
                 qDebug("RTLSDRInput::applySettings: rtlsdr_set_tuner_gain() to %d", settings.m_gain);
             }
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     if (forwardChange)
     {
         int sampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Decim);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, m_settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     return true;
 }
closeDevice()
void RTLSDRInput::closeDevice () private
Definition at line 220 of file rtlsdrinput.cpp.
References m_dev, and m_deviceDescription.
Referenced by openDevice(), and ~RTLSDRInput().
 {
     if (m_dev != 0)
     {
         rtlsdr_close(m_dev);
         m_dev = 0;
     }
     m_deviceDescription.clear();
 }
deserialize()
bool RTLSDRInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 250 of file rtlsdrinput.cpp.
References RTLSDRInput::MsgConfigureRTLSDR::create(), RTLSDRSettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and RTLSDRSettings::resetToDefaults().
Referenced by RTLSDRInput::MsgStartStop::MsgStartStop().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureRTLSDR* message = MsgConfigureRTLSDR::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureRTLSDR* messageToGUI = MsgConfigureRTLSDR::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void RTLSDRInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 85 of file rtlsdrinput.cpp.
Referenced by RTLSDRInput::MsgStartStop::MsgStartStop().
 {
     delete this;
 }
getCenterFrequency()
quint64 RTLSDRInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 283 of file rtlsdrinput.cpp.
References RTLSDRSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & RTLSDRInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 272 of file rtlsdrinput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getGains()
const std::vector<int>& RTLSDRInput::getGains () const inline
Definition at line 143 of file rtlsdrinput.h.
References m_gains, and set_ds_mode().
Referenced by RTLSDRGui::RTLSDRGui(), and webapiFormatDeviceReport().
 { return m_gains; }
getSampleRate()
int RTLSDRInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 277 of file rtlsdrinput.cpp.
References RTLSDRSettings::m_devSampleRate, RTLSDRSettings::m_log2Decim, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     int rate = m_settings.m_devSampleRate;
     return (rate / (1<<m_settings.m_log2Decim));
 }
handleMessage()
bool RTLSDRInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 303 of file rtlsdrinput.cpp.
References applySettings(), FileRecord::genUniqueFileName(), DeviceAPI::getDeviceUID(), RTLSDRInput::MsgConfigureRTLSDR::getForce(), RTLSDRInput::MsgConfigureRTLSDR::getSettings(), RTLSDRInput::MsgFileRecord::getStartStop(), RTLSDRInput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), m_deviceAPI, RTLSDRSettings::m_fileRecordName, m_fileSink, m_settings, RTLSDRSettings::m_useReverseAPI, Message::match(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (MsgConfigureRTLSDR::match(message))
     {
         MsgConfigureRTLSDR& conf = (MsgConfigureRTLSDR&) message;
         qDebug() << "RTLSDRInput::handleMessage: MsgConfigureRTLSDR";
         bool success = applySettings(conf.getSettings(), conf.getForce());
         if (!success)
         {
             qDebug("RTLSDRInput::handleMessage: config error");
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "RTLSDRInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "RTLSDRInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine()) {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void RTLSDRInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 190 of file rtlsdrinput.cpp.
References applySettings(), and m_settings.
Referenced by RTLSDRInput::MsgStartStop::MsgStartStop().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void RTLSDRInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 869 of file rtlsdrinput.cpp.
Referenced by RTLSDRInput(), and ~RTLSDRInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "TestSourceInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("RTLSDRInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openDevice()
bool RTLSDRInput::openDevice () private
Definition at line 90 of file rtlsdrinput.cpp.
References closeDevice(), DeviceAPI::getSamplingDeviceSerial(), m_dev, m_deviceAPI, m_deviceDescription, m_gains, DeviceSampleSource::m_sampleFifo, SampleSinkFifo::setSize(), and stop().
Referenced by RTLSDRInput().
 {
     if (m_dev != 0)
     {
         closeDevice();
     }
     char vendor[256];
     char product[256];
     char serial[256];
     int res;
     int numberOfGains;
     if (!m_sampleFifo.setSize(96000 * 4))
     {
         qCritical("RTLSDRInput::openDevice: Could not allocate SampleFifo");
         return false;
     }
     int device;
     if ((device = rtlsdr_get_index_by_serial(qPrintable(m_deviceAPI->getSamplingDeviceSerial()))) < 0)
     {
         qCritical("RTLSDRInput::openDevice: could not get RTLSDR serial number");
         return false;
     }
     if ((res = rtlsdr_open(&m_dev, device)) < 0)
     {
         qCritical("RTLSDRInput::openDevice: could not open RTLSDR #%d: %s", device, strerror(errno));
         return false;
     }
     vendor[0] = '\0';
     product[0] = '\0';
     serial[0] = '\0';
     if ((res = rtlsdr_get_usb_strings(m_dev, vendor, product, serial)) < 0)
     {
         qCritical("RTLSDRInput::openDevice: error accessing USB device");
         stop();
         return false;
     }
     qInfo("RTLSDRInput::openDevice: open: %s %s, SN: %s", vendor, product, serial);
     m_deviceDescription = QString("%1 (SN %2)").arg(product).arg(serial);
     if ((res = rtlsdr_set_sample_rate(m_dev, 1152000)) < 0)
     {
         qCritical("RTLSDRInput::openDevice: could not set sample rate: 1024k S/s");
         stop();
         return false;
     }
     if ((res = rtlsdr_set_tuner_gain_mode(m_dev, 1)) < 0)
     {
         qCritical("RTLSDRInput::openDevice: error setting tuner gain mode");
         stop();
         return false;
     }
     if ((res = rtlsdr_set_agc_mode(m_dev, 0)) < 0)
     {
         qCritical("RTLSDRInput::openDevice: error setting agc mode");
         stop();
         return false;
     }
     numberOfGains = rtlsdr_get_tuner_gains(m_dev, NULL);
     if (numberOfGains < 0)
     {
         qCritical("RTLSDRInput::openDevice: error getting number of gain values supported");
         stop();
         return false;
     }
     m_gains.resize(numberOfGains);
     if (rtlsdr_get_tuner_gains(m_dev, &m_gains[0]) < 0)
     {
         qCritical("RTLSDRInput::openDevice: error getting gain values");
         stop();
         return false;
     }
     else
     {
         qDebug() << "RTLSDRInput::openDevice: " << m_gains.size() << "gains";
     }
     if ((res = rtlsdr_reset_buffer(m_dev)) < 0)
     {
         qCritical("RTLSDRInput::openDevice: could not reset USB EP buffers: %s", strerror(errno));
         stop();
         return false;
     }
     return true;
 }
serialize()
QByteArray RTLSDRInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 245 of file rtlsdrinput.cpp.
References m_settings, and RTLSDRSettings::serialize().
Referenced by RTLSDRInput::MsgStartStop::MsgStartStop().
 {
     return m_settings.serialize();
 }
set_ds_mode()
void RTLSDRInput::set_ds_mode (int on)
Definition at line 577 of file rtlsdrinput.cpp.
References m_dev.
Referenced by applySettings(), and getGains().
 {
     rtlsdr_set_direct_sampling(m_dev, on);
 }
setCenterFrequency()
void RTLSDRInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 288 of file rtlsdrinput.cpp.
References RTLSDRInput::MsgConfigureRTLSDR::create(), RTLSDRSettings::m_centerFrequency, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     RTLSDRSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureRTLSDR* message = MsgConfigureRTLSDR::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureRTLSDR* messageToGUI = MsgConfigureRTLSDR::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setMessageQueueToGUI()
virtual void RTLSDRInput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 111 of file rtlsdrinput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSource::m_guiMessageQueue.
Referenced by RTLSDRGui::RTLSDRGui().
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void RTLSDRInput::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 114 of file rtlsdrinput.h.
References getCenterFrequency(), handleMessage(), setCenterFrequency(), webapiReportGet(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
start()
bool RTLSDRInput::start () virtual
Implements DeviceSampleSource.
Definition at line 195 of file rtlsdrinput.cpp.
References applySettings(), m_dev, RTLSDRSettings::m_devSampleRate, RTLSDRSettings::m_fcPos, RTLSDRSettings::m_log2Decim, m_mutex, m_rtlSDRThread, m_running, DeviceSampleSource::m_sampleFifo, m_settings, RTLSDRThread::setFcPos(), RTLSDRThread::setLog2Decimation(), RTLSDRThread::setSamplerate(), RTLSDRThread::startWork(), and stop().
Referenced by RTLSDRInput::MsgStartStop::MsgStartStop().
 {
     QMutexLocker mutexLocker(&m_mutex);
     if (!m_dev) {
         return false;
     }
     if (m_running) stop();
     m_rtlSDRThread = new RTLSDRThread(m_dev, &m_sampleFifo);
     m_rtlSDRThread->setSamplerate(m_settings.m_devSampleRate);
     m_rtlSDRThread->setLog2Decimation(m_settings.m_log2Decim);
     m_rtlSDRThread->setFcPos((int) m_settings.m_fcPos);
     m_rtlSDRThread->startWork();
     mutexLocker.unlock();
     applySettings(m_settings, true);
     m_running = true;
     return true;
 }
stop()
void RTLSDRInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 231 of file rtlsdrinput.cpp.
References m_mutex, m_rtlSDRThread, m_running, and RTLSDRThread::stopWork().
Referenced by RTLSDRInput::MsgStartStop::MsgStartStop(), openDevice(), start(), and ~RTLSDRInput().
 {
     QMutexLocker mutexLocker(&m_mutex);
     if (m_rtlSDRThread != 0)
     {
         m_rtlSDRThread->stopWork();
         delete m_rtlSDRThread;
         m_rtlSDRThread = 0;
     }
     m_running = false;
 }
webapiFormatDeviceReport()
void RTLSDRInput::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 752 of file rtlsdrinput.cpp.
References SWGSDRangel::SWGRtlSdrReport::getGains(), getGains(), SWGSDRangel::SWGDeviceReport::getRtlSdrReport(), and SWGSDRangel::SWGRtlSdrReport::setGains().
Referenced by webapiReportGet().
 {
     response.getRtlSdrReport()->setGains(new QList<SWGSDRangel::SWGGain*>);
     for (std::vector<int>::const_iterator it = getGains().begin(); it != getGains().end(); ++it)
     {
         response.getRtlSdrReport()->getGains()->append(new SWGSDRangel::SWGGain);
         response.getRtlSdrReport()->getGains()->back()->setGainCb(*it);
     }
 }
webapiFormatDeviceSettings()
void RTLSDRInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const RTLSDRSettings & settings) private
Definition at line 676 of file rtlsdrinput.cpp.
References SWGSDRangel::SWGRtlSdrSettings::getFileRecordName(), SWGSDRangel::SWGRtlSdrSettings::getReverseApiAddress(), SWGSDRangel::SWGDeviceSettings::getRtlSdrSettings(), RTLSDRSettings::m_agc, RTLSDRSettings::m_centerFrequency, RTLSDRSettings::m_dcBlock, RTLSDRSettings::m_devSampleRate, RTLSDRSettings::m_fcPos, RTLSDRSettings::m_fileRecordName, RTLSDRSettings::m_gain, RTLSDRSettings::m_iqImbalance, RTLSDRSettings::m_log2Decim, RTLSDRSettings::m_loPpmCorrection, RTLSDRSettings::m_lowSampleRate, RTLSDRSettings::m_noModMode, RTLSDRSettings::m_offsetTuning, RTLSDRSettings::m_reverseAPIAddress, RTLSDRSettings::m_reverseAPIDeviceIndex, RTLSDRSettings::m_reverseAPIPort, RTLSDRSettings::m_rfBandwidth, RTLSDRSettings::m_transverterDeltaFrequency, RTLSDRSettings::m_transverterMode, RTLSDRSettings::m_useReverseAPI, SWGSDRangel::SWGRtlSdrSettings::setAgc(), SWGSDRangel::SWGRtlSdrSettings::setCenterFrequency(), SWGSDRangel::SWGRtlSdrSettings::setDcBlock(), SWGSDRangel::SWGRtlSdrSettings::setDevSampleRate(), SWGSDRangel::SWGRtlSdrSettings::setFcPos(), SWGSDRangel::SWGRtlSdrSettings::setFileRecordName(), SWGSDRangel::SWGRtlSdrSettings::setGain(), SWGSDRangel::SWGRtlSdrSettings::setIqImbalance(), SWGSDRangel::SWGRtlSdrSettings::setLog2Decim(), SWGSDRangel::SWGRtlSdrSettings::setLoPpmCorrection(), SWGSDRangel::SWGRtlSdrSettings::setLowSampleRate(), SWGSDRangel::SWGRtlSdrSettings::setNoModMode(), SWGSDRangel::SWGRtlSdrSettings::setOffsetTuning(), SWGSDRangel::SWGRtlSdrSettings::setReverseApiAddress(), SWGSDRangel::SWGRtlSdrSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGRtlSdrSettings::setReverseApiPort(), SWGSDRangel::SWGRtlSdrSettings::setRfBandwidth(), SWGSDRangel::SWGRtlSdrSettings::setTransverterDeltaFrequency(), SWGSDRangel::SWGRtlSdrSettings::setTransverterMode(), and SWGSDRangel::SWGRtlSdrSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     qDebug("RTLSDRInput::webapiFormatDeviceSettings: m_lowSampleRate: %s", settings.m_lowSampleRate ? "true" : "false");
     response.getRtlSdrSettings()->setAgc(settings.m_agc ? 1 : 0);
     response.getRtlSdrSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getRtlSdrSettings()->setDcBlock(settings.m_dcBlock ? 1 : 0);
     response.getRtlSdrSettings()->setDevSampleRate(settings.m_devSampleRate);
     response.getRtlSdrSettings()->setFcPos((int) settings.m_fcPos);
     response.getRtlSdrSettings()->setGain(settings.m_gain);
     response.getRtlSdrSettings()->setIqImbalance(settings.m_iqImbalance ? 1 : 0);
     response.getRtlSdrSettings()->setLoPpmCorrection(settings.m_loPpmCorrection);
     response.getRtlSdrSettings()->setLog2Decim(settings.m_log2Decim);
     response.getRtlSdrSettings()->setLowSampleRate(settings.m_lowSampleRate ? 1 : 0);
     response.getRtlSdrSettings()->setNoModMode(settings.m_noModMode ? 1 : 0);
     response.getRtlSdrSettings()->setOffsetTuning(settings.m_offsetTuning ? 1 : 0);
     response.getRtlSdrSettings()->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     response.getRtlSdrSettings()->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     response.getRtlSdrSettings()->setRfBandwidth(settings.m_rfBandwidth);
     if (response.getRtlSdrSettings()->getFileRecordName()) {
         *response.getRtlSdrSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getRtlSdrSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getRtlSdrSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getRtlSdrSettings()->getReverseApiAddress()) {
         *response.getRtlSdrSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getRtlSdrSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getRtlSdrSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getRtlSdrSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int RTLSDRInput::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 741 of file rtlsdrinput.cpp.
References SWGSDRangel::SWGDeviceReport::getRtlSdrReport(), SWGSDRangel::SWGRtlSdrReport::init(), SWGSDRangel::SWGDeviceReport::setRtlSdrReport(), and webapiFormatDeviceReport().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setRtlSdrReport(new SWGSDRangel::SWGRtlSdrReport());
     response.getRtlSdrReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void RTLSDRInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const RTLSDRSettings & settings, bool force) private
Definition at line 763 of file rtlsdrinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getRtlSdrSettings(), RTLSDRSettings::m_agc, RTLSDRSettings::m_centerFrequency, RTLSDRSettings::m_dcBlock, m_deviceAPI, RTLSDRSettings::m_devSampleRate, RTLSDRSettings::m_fcPos, RTLSDRSettings::m_fileRecordName, RTLSDRSettings::m_gain, RTLSDRSettings::m_iqImbalance, RTLSDRSettings::m_log2Decim, RTLSDRSettings::m_loPpmCorrection, RTLSDRSettings::m_lowSampleRate, m_networkManager, m_networkRequest, RTLSDRSettings::m_noModMode, RTLSDRSettings::m_offsetTuning, RTLSDRSettings::m_reverseAPIAddress, RTLSDRSettings::m_reverseAPIDeviceIndex, RTLSDRSettings::m_reverseAPIPort, RTLSDRSettings::m_rfBandwidth, RTLSDRSettings::m_transverterDeltaFrequency, RTLSDRSettings::m_transverterMode, SWGSDRangel::SWGRtlSdrSettings::setAgc(), SWGSDRangel::SWGRtlSdrSettings::setCenterFrequency(), SWGSDRangel::SWGRtlSdrSettings::setDcBlock(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGRtlSdrSettings::setDevSampleRate(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGRtlSdrSettings::setFcPos(), SWGSDRangel::SWGRtlSdrSettings::setFileRecordName(), SWGSDRangel::SWGRtlSdrSettings::setGain(), SWGSDRangel::SWGRtlSdrSettings::setIqImbalance(), SWGSDRangel::SWGRtlSdrSettings::setLog2Decim(), SWGSDRangel::SWGRtlSdrSettings::setLoPpmCorrection(), SWGSDRangel::SWGRtlSdrSettings::setLowSampleRate(), SWGSDRangel::SWGRtlSdrSettings::setNoModMode(), SWGSDRangel::SWGRtlSdrSettings::setOffsetTuning(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGRtlSdrSettings::setRfBandwidth(), SWGSDRangel::SWGDeviceSettings::setRtlSdrSettings(), SWGSDRangel::SWGRtlSdrSettings::setTransverterDeltaFrequency(), and SWGSDRangel::SWGRtlSdrSettings::setTransverterMode().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setDeviceHwType(new QString("RTLSDR"));
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setRtlSdrSettings(new SWGSDRangel::SWGRtlSdrSettings());
     SWGSDRangel::SWGRtlSdrSettings *swgRtlSdrSettings = swgDeviceSettings->getRtlSdrSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("agc") || force) {
         swgRtlSdrSettings->setAgc(settings.m_agc ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgRtlSdrSettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("dcBlock") || force) {
         swgRtlSdrSettings->setDcBlock(settings.m_dcBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("devSampleRate") || force) {
         swgRtlSdrSettings->setDevSampleRate(settings.m_devSampleRate);
     }
     if (deviceSettingsKeys.contains("fcPos") || force) {
         swgRtlSdrSettings->setFcPos(settings.m_fcPos);
     }
     if (deviceSettingsKeys.contains("gain") || force) {
         swgRtlSdrSettings->setGain(settings.m_gain);
     }
     if (deviceSettingsKeys.contains("iqImbalance") || force) {
         swgRtlSdrSettings->setIqImbalance(settings.m_iqImbalance ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("loPpmCorrection") || force) {
         swgRtlSdrSettings->setLoPpmCorrection(settings.m_loPpmCorrection);
     }
     if (deviceSettingsKeys.contains("log2Decim") || force) {
         swgRtlSdrSettings->setLog2Decim(settings.m_log2Decim);
     }
     if (deviceSettingsKeys.contains("lowSampleRate") || force) {
         swgRtlSdrSettings->setLowSampleRate(settings.m_lowSampleRate);
     }
     if (deviceSettingsKeys.contains("noModMode") || force) {
         swgRtlSdrSettings->setNoModMode(settings.m_noModMode ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("offsetTuning") || force) {
         swgRtlSdrSettings->setOffsetTuning(settings.m_offsetTuning ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency") || force) {
         swgRtlSdrSettings->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     }
     if (deviceSettingsKeys.contains("transverterMode") || force) {
         swgRtlSdrSettings->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("rfBandwidth") || force) {
         swgRtlSdrSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgRtlSdrSettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void RTLSDRInput::webapiReverseSendStartStop (bool start) private
Definition at line 841 of file rtlsdrinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, RTLSDRSettings::m_reverseAPIAddress, RTLSDRSettings::m_reverseAPIDeviceIndex, RTLSDRSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setDeviceHwType(new QString("RTLSDR"));
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int RTLSDRInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 722 of file rtlsdrinput.cpp.
References RTLSDRInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int RTLSDRInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 713 of file rtlsdrinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int RTLSDRInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 582 of file rtlsdrinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getRtlSdrSettings(), SWGSDRangel::SWGRtlSdrSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setRtlSdrSettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setRtlSdrSettings(new SWGSDRangel::SWGRtlSdrSettings());
     response.getRtlSdrSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int RTLSDRInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 593 of file rtlsdrinput.cpp.
References RTLSDRInput::MsgConfigureRTLSDR::create(), SWGSDRangel::SWGRtlSdrSettings::getAgc(), SWGSDRangel::SWGRtlSdrSettings::getCenterFrequency(), SWGSDRangel::SWGRtlSdrSettings::getDcBlock(), SWGSDRangel::SWGRtlSdrSettings::getDevSampleRate(), SWGSDRangel::SWGRtlSdrSettings::getFcPos(), SWGSDRangel::SWGRtlSdrSettings::getFileRecordName(), SWGSDRangel::SWGRtlSdrSettings::getGain(), SWGSDRangel::SWGRtlSdrSettings::getIqImbalance(), SWGSDRangel::SWGRtlSdrSettings::getLog2Decim(), SWGSDRangel::SWGRtlSdrSettings::getLoPpmCorrection(), SWGSDRangel::SWGRtlSdrSettings::getLowSampleRate(), SWGSDRangel::SWGRtlSdrSettings::getNoModMode(), SWGSDRangel::SWGRtlSdrSettings::getOffsetTuning(), SWGSDRangel::SWGRtlSdrSettings::getReverseApiAddress(), SWGSDRangel::SWGRtlSdrSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGRtlSdrSettings::getReverseApiPort(), SWGSDRangel::SWGRtlSdrSettings::getRfBandwidth(), SWGSDRangel::SWGDeviceSettings::getRtlSdrSettings(), SWGSDRangel::SWGRtlSdrSettings::getTransverterDeltaFrequency(), SWGSDRangel::SWGRtlSdrSettings::getTransverterMode(), SWGSDRangel::SWGRtlSdrSettings::getUseReverseApi(), RTLSDRSettings::m_agc, RTLSDRSettings::m_centerFrequency, RTLSDRSettings::m_dcBlock, RTLSDRSettings::m_devSampleRate, RTLSDRSettings::m_fcPos, RTLSDRSettings::m_fileRecordName, RTLSDRSettings::m_gain, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, RTLSDRSettings::m_iqImbalance, RTLSDRSettings::m_log2Decim, RTLSDRSettings::m_loPpmCorrection, RTLSDRSettings::m_lowSampleRate, RTLSDRSettings::m_noModMode, RTLSDRSettings::m_offsetTuning, RTLSDRSettings::m_reverseAPIAddress, RTLSDRSettings::m_reverseAPIDeviceIndex, RTLSDRSettings::m_reverseAPIPort, RTLSDRSettings::m_rfBandwidth, m_settings, RTLSDRSettings::m_transverterDeltaFrequency, RTLSDRSettings::m_transverterMode, RTLSDRSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     RTLSDRSettings settings = m_settings;
     if (deviceSettingsKeys.contains("agc")) {
         settings.m_agc = response.getRtlSdrSettings()->getAgc() != 0;
     }
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getRtlSdrSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("dcBlock")) {
         settings.m_dcBlock = response.getRtlSdrSettings()->getDcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("devSampleRate")) {
         settings.m_devSampleRate = response.getRtlSdrSettings()->getDevSampleRate();
     }
     if (deviceSettingsKeys.contains("fcPos")) {
         settings.m_fcPos = (RTLSDRSettings::fcPos_t) response.getRtlSdrSettings()->getFcPos();
     }
     if (deviceSettingsKeys.contains("gain")) {
         settings.m_gain = response.getRtlSdrSettings()->getGain();
     }
     if (deviceSettingsKeys.contains("iqImbalance")) {
         settings.m_iqImbalance = response.getRtlSdrSettings()->getIqImbalance() != 0;
     }
     if (deviceSettingsKeys.contains("loPpmCorrection")) {
         settings.m_loPpmCorrection = response.getRtlSdrSettings()->getLoPpmCorrection();
     }
     if (deviceSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getRtlSdrSettings()->getLog2Decim();
     }
     if (deviceSettingsKeys.contains("lowSampleRate")) {
         settings.m_lowSampleRate = response.getRtlSdrSettings()->getLowSampleRate() != 0;
     }
     if (deviceSettingsKeys.contains("noModMode")) {
         settings.m_noModMode = response.getRtlSdrSettings()->getNoModMode() != 0;
     }
     if (deviceSettingsKeys.contains("offsetTuning")) {
         settings.m_offsetTuning = response.getRtlSdrSettings()->getOffsetTuning() != 0;
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency")) {
         settings.m_transverterDeltaFrequency = response.getRtlSdrSettings()->getTransverterDeltaFrequency();
     }
     if (deviceSettingsKeys.contains("transverterMode")) {
         settings.m_transverterMode = response.getRtlSdrSettings()->getTransverterMode() != 0;
     }
     if (deviceSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getRtlSdrSettings()->getRfBandwidth();
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getRtlSdrSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getRtlSdrSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getRtlSdrSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getRtlSdrSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getRtlSdrSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureRTLSDR *msg = MsgConfigureRTLSDR::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureRTLSDR *msgToGUI = MsgConfigureRTLSDR::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
frequencyHighRangeMax
const quint64 RTLSDRInput::frequencyHighRangeMax = 1900000UL static
Definition at line 149 of file rtlsdrinput.h.
Referenced by RTLSDRGui::updateFrequencyLimits().
frequencyHighRangeMin
const quint64 RTLSDRInput::frequencyHighRangeMin = 24000UL static
Definition at line 148 of file rtlsdrinput.h.
Referenced by RTLSDRGui::updateFrequencyLimits().
frequencyLowRangeMax
const quint64 RTLSDRInput::frequencyLowRangeMax = 275000UL static
Definition at line 147 of file rtlsdrinput.h.
Referenced by RTLSDRGui::updateFrequencyLimits().
frequencyLowRangeMin
const quint64 RTLSDRInput::frequencyLowRangeMin = 0UL static
Definition at line 146 of file rtlsdrinput.h.
Referenced by RTLSDRGui::updateFrequencyLimits().
m_dev
rtlsdr_dev_t* RTLSDRInput::m_dev private
Definition at line 160 of file rtlsdrinput.h.
Referenced by applySettings(), closeDevice(), openDevice(), set_ds_mode(), and start().
m_deviceAPI
DeviceAPI* RTLSDRInput::m_deviceAPI private
Definition at line 156 of file rtlsdrinput.h.
Referenced by applySettings(), handleMessage(), openDevice(), RTLSDRInput(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~RTLSDRInput().
m_deviceDescription
QString RTLSDRInput::m_deviceDescription private
Definition at line 162 of file rtlsdrinput.h.
Referenced by closeDevice(), getDeviceDescription(), and openDevice().
m_fileSink
FileRecord* RTLSDRInput::m_fileSink private
File sink to record device I/Q output.
Definition at line 157 of file rtlsdrinput.h.
Referenced by applySettings(), handleMessage(), RTLSDRInput(), and ~RTLSDRInput().
m_gains
std::vector<int> RTLSDRInput::m_gains private
Definition at line 163 of file rtlsdrinput.h.
Referenced by getGains(), and openDevice().
m_mutex
QMutex RTLSDRInput::m_mutex private
Definition at line 158 of file rtlsdrinput.h.
Referenced by start(), and stop().
m_networkManager
QNetworkAccessManager* RTLSDRInput::m_networkManager private
Definition at line 165 of file rtlsdrinput.h.
Referenced by RTLSDRInput(), webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~RTLSDRInput().
m_networkRequest
QNetworkRequest RTLSDRInput::m_networkRequest private
Definition at line 166 of file rtlsdrinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_rtlSDRThread
RTLSDRThread* RTLSDRInput::m_rtlSDRThread private
Definition at line 161 of file rtlsdrinput.h.
Referenced by applySettings(), start(), and stop().
m_running
bool RTLSDRInput::m_running private
Definition at line 164 of file rtlsdrinput.h.
Referenced by start(), stop(), and ~RTLSDRInput().
m_settings
RTLSDRSettings RTLSDRInput::m_settings private
Definition at line 159 of file rtlsdrinput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), serialize(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
sampleRateHighRangeMax
const int RTLSDRInput::sampleRateHighRangeMax = 2400000U static
Definition at line 153 of file rtlsdrinput.h.
Referenced by RTLSDRGui::displaySampleRate().
sampleRateHighRangeMin
const int RTLSDRInput::sampleRateHighRangeMin = 950000U static
Definition at line 152 of file rtlsdrinput.h.
Referenced by RTLSDRGui::displaySampleRate().
sampleRateLowRangeMax
const int RTLSDRInput::sampleRateLowRangeMax = 300000U static
Definition at line 151 of file rtlsdrinput.h.
Referenced by RTLSDRGui::displaySampleRate().
sampleRateLowRangeMin
const int RTLSDRInput::sampleRateLowRangeMin = 230000U static
Definition at line 150 of file rtlsdrinput.h.
Referenced by RTLSDRGui::displaySampleRate().
The documentation for this class was generated from the following files:
plugins/samplesource/rtlsdr/rtlsdrinput.h
plugins/samplesource/rtlsdr/rtlsdrinput.cpp