SDRAngel: CWSmoother Class Reference
CWSmoother Class Reference
#include <cwkeyer.h>
Public Member Functions
CWSmoother ()
~CWSmoother ()
void setNbFadeSamples (unsigned int nbFadeSamples)
bool getFadeSample (bool on, float &sample)
Private Attributes
QMutex m_mutex
unsigned int m_fadeInCounter
unsigned int m_fadeOutCounter
unsigned int m_nbFadeSamples
float * m_fadeInSamples
float * m_fadeOutSamples
Detailed Description
Ancillary class to smooth out CW transitions with a sine shape
Definition at line 34 of file cwkeyer.h.
Constructor & Destructor Documentation
CWSmoother()
CWSmoother::CWSmoother ()
Definition at line 443 of file cwkeyer.cpp.
References setNbFadeSamples().
                        :
         m_fadeInCounter(0),
         m_fadeOutCounter(0),
         m_nbFadeSamples(0),
         m_fadeInSamples(0),
         m_fadeOutSamples(0)
 {
     setNbFadeSamples(192); // default is 4 ms at 48 kHz sample rate
 }
~CWSmoother()
CWSmoother::~CWSmoother ()
Definition at line 453 of file cwkeyer.cpp.
References m_fadeInSamples, and m_fadeOutSamples.
 {
     delete[] m_fadeInSamples;
     delete[] m_fadeOutSamples;
 }
Member Function Documentation
getFadeSample()
bool CWSmoother::getFadeSample (bool on, float & sample)
Definition at line 487 of file cwkeyer.cpp.
References m_fadeInCounter, m_fadeInSamples, m_fadeOutCounter, m_fadeOutSamples, m_mutex, and m_nbFadeSamples.
Referenced by WFMMod::pullAF(), AMMod::pullAF(), NFMMod::pullAF(), FreeDVMod::pullAF(), and SSBMod::pullAF().
 {
     QMutexLocker mutexLocker(&m_mutex);
     if (on)
     {
         m_fadeOutCounter = 0;
         if (m_fadeInCounter < m_nbFadeSamples)
         {
             sample = m_fadeInSamples[m_fadeInCounter];
             m_fadeInCounter++;
             return true;
         }
         else
         {
             sample = 1.0f;
             return false;
         }
     }
     else
     {
         m_fadeInCounter = 0;
         if (m_fadeOutCounter < m_nbFadeSamples)
         {
             sample = m_fadeOutSamples[m_fadeOutCounter];
             m_fadeOutCounter++;
             return true;
         }
         else
         {
             sample = 0.0f;
             return false;
         }
     }
 }
setNbFadeSamples()
void CWSmoother::setNbFadeSamples (unsigned int nbFadeSamples)
Definition at line 459 of file cwkeyer.cpp.
References i, m_fadeInCounter, m_fadeInSamples, m_fadeOutCounter, m_fadeOutSamples, m_mutex, m_nbFadeSamples, and StepFunctions::smootherstep().
Referenced by CWSmoother().
 {
     if (nbFadeSamples != m_nbFadeSamples)
     {
         QMutexLocker mutexLocker(&m_mutex);
         m_nbFadeSamples = nbFadeSamples;
         if (m_fadeInSamples) delete[] m_fadeInSamples;
         if (m_fadeOutSamples) delete[] m_fadeOutSamples;
         m_fadeInSamples = new float[m_nbFadeSamples];
         m_fadeOutSamples = new float[m_nbFadeSamples];
         for (unsigned int i = 0; i < m_nbFadeSamples; i++)
         {
             float x = i/ (float) m_nbFadeSamples;
             float y = 1.0f -x;
             m_fadeInSamples[i] = StepFunctions::smootherstep(x);
             m_fadeOutSamples[i] = StepFunctions::smootherstep(y);
         }
         m_fadeInCounter = 0;
         m_fadeOutCounter = 0;
     }
 }
Member Data Documentation
m_fadeInCounter
unsigned int CWSmoother::m_fadeInCounter private
Definition at line 45 of file cwkeyer.h.
Referenced by getFadeSample(), and setNbFadeSamples().
m_fadeInSamples
float* CWSmoother::m_fadeInSamples private
Definition at line 48 of file cwkeyer.h.
Referenced by getFadeSample(), setNbFadeSamples(), and ~CWSmoother().
m_fadeOutCounter
unsigned int CWSmoother::m_fadeOutCounter private
Definition at line 46 of file cwkeyer.h.
Referenced by getFadeSample(), and setNbFadeSamples().
m_fadeOutSamples
float* CWSmoother::m_fadeOutSamples private
Definition at line 49 of file cwkeyer.h.
Referenced by getFadeSample(), setNbFadeSamples(), and ~CWSmoother().
m_mutex
QMutex CWSmoother::m_mutex private
Definition at line 44 of file cwkeyer.h.
Referenced by CWKeyer::applySettings(), getFadeSample(), and setNbFadeSamples().
m_nbFadeSamples
unsigned int CWSmoother::m_nbFadeSamples private
Definition at line 47 of file cwkeyer.h.
Referenced by getFadeSample(), and setNbFadeSamples().
The documentation for this class was generated from the following files:
sdrbase/dsp/cwkeyer.h
sdrbase/dsp/cwkeyer.cpp