SDRAngel: AirspyHFGui Class Reference
AirspyHFGui Class Reference
#include <airspyhfgui.h>
Public Member Functions
AirspyHFGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~AirspyHFGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
uint32_t getDevSampleRate (unsigned int index)
int getDevSampleRateIndex (uint32_t sampleRate)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void on_centerFrequency_changed (quint64 value)
void on_LOppm_valueChanged (int value)
void on_resetLOppm_clicked ()
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_sampleRate_currentIndexChanged (int index)
void on_decim_currentIndexChanged (int index)
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void on_transverter_clicked ()
void on_band_currentIndexChanged (int index)
void on_dsp_toggled (bool checked)
void on_lna_toggled (bool checked)
void on_agc_currentIndexChanged (int index)
void on_att_currentIndexChanged (int index)
void updateHardware ()
void updateStatus ()
void handleInputMessages ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void displaySampleRates ()
void displayAGC ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void updateFrequencyLimits ()
Private Attributes
Ui::AirspyHFGui * ui
DeviceUISet * m_deviceUISet
bool m_doApplySettings
bool m_forceSettings
AirspyHFSettings m_settings
QTimer m_updateTimer
QTimer m_statusTimer
std::vector< uint32_t > m_rates
DeviceSampleSource * m_sampleSource
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 36 of file airspyhfgui.h.
Constructor & Destructor Documentation
AirspyHFGui()
AirspyHFGui::AirspyHFGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 36 of file airspyhfgui.cpp.
References displaySampleRates(), displaySettings(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_rates, m_sampleSource, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), sendSettings(), DeviceSampleSource::setMessageQueueToGUI(), ui, updateFrequencyLimits(), updateHardware(), and updateStatus().
                                                                   :
     QWidget(parent),
     ui(new Ui::AirspyHFGui),
     m_deviceUISet(deviceUISet),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_settings(),
     m_sampleSource(0),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     m_sampleSource = (AirspyHFInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     updateFrequencyLimits();
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     m_rates = ((AirspyHFInput*) m_sampleSource)->getSampleRates();
     displaySampleRates();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
     sendSettings();
 }
~AirspyHFGui()
AirspyHFGui::~AirspyHFGui () virtual
Definition at line 69 of file airspyhfgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void AirspyHFGui::blockApplySettings (bool block) inline private
Definition at line 73 of file airspyhfgui.h.
Referenced by displaySettings(), and handleMessage().
 { m_doApplySettings = !block; }
deserialize()
bool AirspyHFGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 113 of file airspyhfgui.cpp.
References AirspyHFSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void AirspyHFGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 74 of file airspyhfgui.cpp.
 {
     delete this;
 }
displayAGC()
void AirspyHFGui::displayAGC () private
Definition at line 268 of file airspyhfgui.cpp.
References AirspyHFSettings::m_agcHigh, m_settings, AirspyHFSettings::m_useAGC, and ui.
Referenced by displaySettings().
 {
     if (m_settings.m_useAGC)
     {
         if (m_settings.m_agcHigh) {
             ui->agc->setCurrentIndex(2);
         } else {
             ui->agc->setCurrentIndex(1);
         }
     }
     else
     {
         ui->agc->setCurrentIndex(0);
     }
 }
displaySampleRates()
void AirspyHFGui::displaySampleRates () private
Definition at line 240 of file airspyhfgui.cpp.
References arg(), i, AirspyHFSettings::m_devSampleRateIndex, m_rates, m_settings, and ui.
Referenced by AirspyHFGui().
 {
     unsigned int savedIndex = m_settings.m_devSampleRateIndex;
     ui->sampleRate->blockSignals(true);
     if (m_rates.size() > 0)
     {
         ui->sampleRate->clear();
         for (unsigned int i = 0; i < m_rates.size(); i++)
         {
             int sampleRate = m_rates[i]/1000;
             ui->sampleRate->addItem(QString("%1").arg(QString("%1").arg(sampleRate, 5, 10, QChar(' '))));
         }
     }
     ui->sampleRate->blockSignals(false);
     if (savedIndex < m_rates.size())
     {
         ui->sampleRate->setCurrentIndex(savedIndex);
     }
     else
     {
         ui->sampleRate->setCurrentIndex((int) m_rates.size()-1);
     }
 }
displaySettings()
void AirspyHFGui::displaySettings () private
Definition at line 216 of file airspyhfgui.cpp.
References arg(), blockApplySettings(), displayAGC(), AirspyHFSettings::m_attenuatorSteps, AirspyHFSettings::m_bandIndex, AirspyHFSettings::m_centerFrequency, AirspyHFSettings::m_dcBlock, AirspyHFSettings::m_devSampleRateIndex, AirspyHFSettings::m_iqCorrection, AirspyHFSettings::m_log2Decim, AirspyHFSettings::m_LOppmTenths, m_settings, AirspyHFSettings::m_transverterDeltaFrequency, AirspyHFSettings::m_transverterMode, AirspyHFSettings::m_useDSP, AirspyHFSettings::m_useLNA, ui, and updateFrequencyLimits().
Referenced by AirspyHFGui(), deserialize(), handleMessage(), resetToDefaults(), and setCenterFrequency().
 {
     blockApplySettings(true);
     ui->band->blockSignals(true);
     m_settings.m_bandIndex = m_settings.m_centerFrequency <= 31000000UL ? 0 : 1; // override
     ui->band->setCurrentIndex(m_settings.m_bandIndex);
     updateFrequencyLimits();
     ui->transverter->setDeltaFrequency(m_settings.m_transverterDeltaFrequency);
     ui->transverter->setDeltaFrequencyActive(m_settings.m_transverterMode);
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     ui->LOppm->setValue(m_settings.m_LOppmTenths);
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     ui->sampleRate->setCurrentIndex(m_settings.m_devSampleRateIndex);
     ui->decim->setCurrentIndex(m_settings.m_log2Decim);
     ui->band->blockSignals(false);
     ui->dsp->setChecked(m_settings.m_useDSP);
     ui->lna->setChecked(m_settings.m_useLNA);
     ui->att->setCurrentIndex(m_settings.m_attenuatorSteps);
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqCorrection);
     displayAGC();
     blockApplySettings(false);
 }
getCenterFrequency()
qint64 AirspyHFGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 96 of file airspyhfgui.cpp.
References AirspyHFSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getDevSampleRate()
uint32_t AirspyHFGui::getDevSampleRate (unsigned int index)
Definition at line 458 of file airspyhfgui.cpp.
References m_rates.
 {
     if (rate_index < m_rates.size())
     {
         return m_rates[rate_index];
     }
     else
     {
         return m_rates[0];
     }
 }
getDevSampleRateIndex()
int AirspyHFGui::getDevSampleRateIndex (uint32_t sampleRate)
Definition at line 470 of file airspyhfgui.cpp.
References i, and m_rates.
 {
     for (unsigned int i=0; i < m_rates.size(); i++)
     {
         if (sampeRate == m_rates[i])
         {
             return i;
         }
     }
     return -1;
 }
getInputMessageQueue()
virtual MessageQueue* AirspyHFGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 52 of file airspyhfgui.h.
 { return &m_inputMessageQueue; }
getName()
QString AirspyHFGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 84 of file airspyhfgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void AirspyHFGui::handleInputMessages () private slot
Definition at line 152 of file airspyhfgui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by AirspyHFGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("AirspyHFGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("AirspyGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool AirspyHFGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 126 of file airspyhfgui.cpp.
References blockApplySettings(), displaySettings(), AirspyHFInput::MsgConfigureAirspyHF::getSettings(), AirspyHFInput::MsgStartStop::getStartStop(), m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (AirspyHFInput::MsgConfigureAirspyHF::match(message))
     {
         const AirspyHFInput::MsgConfigureAirspyHF& cfg = (AirspyHFInput::MsgConfigureAirspyHF&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (AirspyHFInput::MsgStartStop::match(message))
     {
         AirspyHFInput::MsgStartStop& notif = (AirspyHFInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_agc_currentIndexChanged
void AirspyHFGui::on_agc_currentIndexChanged (int index) private slot
Definition at line 378 of file airspyhfgui.cpp.
References AirspyHFSettings::m_agcHigh, m_settings, AirspyHFSettings::m_useAGC, and sendSettings().
 {
     if (index == 0)
     {
         m_settings.m_useAGC = false;
         sendSettings();
     }
     else if (index <= 2)
     {
         m_settings.m_useAGC = true;
         if (index == 1) {
             m_settings.m_agcHigh = false;
         } else {
             m_settings.m_agcHigh = true;
         }
         sendSettings();
     }
 }
on_att_currentIndexChanged
void AirspyHFGui::on_att_currentIndexChanged (int index) private slot
Definition at line 399 of file airspyhfgui.cpp.
References AirspyHFSettings::m_attenuatorSteps, m_settings, and sendSettings().
 {
     if ((index >= 0) && (index <= 8))
     {
         m_settings.m_attenuatorSteps = index;
         sendSettings();
     }
 }
on_band_currentIndexChanged
void AirspyHFGui::on_band_currentIndexChanged (int index) private slot
Definition at line 353 of file airspyhfgui.cpp.
References AirspyHFSettings::m_bandIndex, AirspyHFSettings::m_centerFrequency, m_settings, sendSettings(), ui, and updateFrequencyLimits().
 {
     if ((index < 0) || (index > 1)) {
         return;
     }
     m_settings.m_bandIndex = index;
     updateFrequencyLimits();
     qDebug("AirspyHFGui::on_band_currentIndexChanged: freq: %llu", ui->centerFrequency->getValueNew() * 1000);
     m_settings.m_centerFrequency = ui->centerFrequency->getValueNew() * 1000;
     sendSettings();
 }
on_centerFrequency_changed
void AirspyHFGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 290 of file airspyhfgui.cpp.
References AirspyHFSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_dcOffset_toggled
void AirspyHFGui::on_dcOffset_toggled (bool checked) private slot
Definition at line 408 of file airspyhfgui.cpp.
References AirspyHFSettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_decim_currentIndexChanged
void AirspyHFGui::on_decim_currentIndexChanged (int index) private slot
Definition at line 314 of file airspyhfgui.cpp.
References AirspyHFSettings::m_log2Decim, m_settings, and sendSettings().
 {
     if ((index < 0) || (index > 6))
         return;
     m_settings.m_log2Decim = index;
     sendSettings();
 }
on_dsp_toggled
void AirspyHFGui::on_dsp_toggled (bool checked) private slot
Definition at line 366 of file airspyhfgui.cpp.
References m_settings, AirspyHFSettings::m_useDSP, and sendSettings().
 {
     m_settings.m_useDSP = checked;
     sendSettings();
 }
on_iqImbalance_toggled
void AirspyHFGui::on_iqImbalance_toggled (bool checked) private slot
Definition at line 414 of file airspyhfgui.cpp.
References AirspyHFSettings::m_iqCorrection, m_settings, and sendSettings().
 {
     m_settings.m_iqCorrection = checked;
     sendSettings();
 }
on_lna_toggled
void AirspyHFGui::on_lna_toggled (bool checked) private slot
Definition at line 372 of file airspyhfgui.cpp.
References m_settings, AirspyHFSettings::m_useLNA, and sendSettings().
 {
     m_settings.m_useLNA = checked;
     sendSettings();
 }
on_LOppm_valueChanged
void AirspyHFGui::on_LOppm_valueChanged (int value) private slot
Definition at line 296 of file airspyhfgui.cpp.
References arg(), AirspyHFSettings::m_LOppmTenths, m_settings, sendSettings(), and ui.
 {
     m_settings.m_LOppmTenths = value;
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     sendSettings();
 }
on_record_toggled
void AirspyHFGui::on_record_toggled (bool checked) private slot
Definition at line 331 of file airspyhfgui.cpp.
References AirspyHFInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     AirspyHFInput::MsgFileRecord* message = AirspyHFInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_resetLOppm_clicked
void AirspyHFGui::on_resetLOppm_clicked () private slot
Definition at line 303 of file airspyhfgui.cpp.
References ui.
 {
     ui->LOppm->setValue(0);
 }
on_sampleRate_currentIndexChanged
void AirspyHFGui::on_sampleRate_currentIndexChanged (int index) private slot
Definition at line 308 of file airspyhfgui.cpp.
References AirspyHFSettings::m_devSampleRateIndex, m_settings, and sendSettings().
 {
     m_settings.m_devSampleRateIndex = index;
     sendSettings();
 }
on_startStop_toggled
void AirspyHFGui::on_startStop_toggled (bool checked) private slot
Definition at line 322 of file airspyhfgui.cpp.
References AirspyHFInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         AirspyHFInput::MsgStartStop *message = AirspyHFInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
on_transverter_clicked
void AirspyHFGui::on_transverter_clicked () private slot
Definition at line 343 of file airspyhfgui.cpp.
References AirspyHFSettings::m_centerFrequency, m_settings, AirspyHFSettings::m_transverterDeltaFrequency, AirspyHFSettings::m_transverterMode, sendSettings(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("AirspyHFGui::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     m_settings.m_centerFrequency = ui->centerFrequency->getValueNew()*1000;
     sendSettings();
 }
openDeviceSettingsDialog
void AirspyHFGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 483 of file airspyhfgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), AirspyHFSettings::m_reverseAPIAddress, AirspyHFSettings::m_reverseAPIDeviceIndex, AirspyHFSettings::m_reverseAPIPort, m_settings, AirspyHFSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by AirspyHFGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void AirspyHFGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 89 of file airspyhfgui.cpp.
References displaySettings(), m_settings, AirspyHFSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void AirspyHFGui::sendSettings () private
Definition at line 284 of file airspyhfgui.cpp.
References m_updateTimer.
Referenced by AirspyHFGui(), deserialize(), on_agc_currentIndexChanged(), on_att_currentIndexChanged(), on_band_currentIndexChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_dsp_toggled(), on_iqImbalance_toggled(), on_lna_toggled(), on_LOppm_valueChanged(), on_sampleRate_currentIndexChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray AirspyHFGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 108 of file airspyhfgui.cpp.
References m_settings, and AirspyHFSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void AirspyHFGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 101 of file airspyhfgui.cpp.
References displaySettings(), AirspyHFSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void AirspyHFGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 79 of file airspyhfgui.cpp.
 {
     setObjectName(name);
 }
updateFrequencyLimits()
void AirspyHFGui::updateFrequencyLimits () private
Definition at line 187 of file airspyhfgui.cpp.
References AirspyHFInput::loHighLimitFreqHF, AirspyHFInput::loHighLimitFreqVHF, AirspyHFInput::loLowLimitFreqHF, AirspyHFInput::loLowLimitFreqVHF, AirspyHFSettings::m_bandIndex, m_settings, AirspyHFSettings::m_transverterDeltaFrequency, AirspyHFSettings::m_transverterMode, and ui.
Referenced by AirspyHFGui(), displaySettings(), on_band_currentIndexChanged(), and on_transverter_clicked().
 {
     // values in kHz
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     qint64 minLimit;
     qint64 maxLimit;
     switch(m_settings.m_bandIndex)
     {
     case 1:
         minLimit = AirspyHFInput::loLowLimitFreqVHF/1000 + deltaFrequency;
         maxLimit = AirspyHFInput::loHighLimitFreqVHF/1000 + deltaFrequency;
         break;
     case 0:
     default:
         minLimit = AirspyHFInput::loLowLimitFreqHF/1000 + deltaFrequency;
         maxLimit = AirspyHFInput::loHighLimitFreqHF/1000 + deltaFrequency;
         break;
     }
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("AirspyHFGui::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void AirspyHFGui::updateHardware () private slot
Definition at line 420 of file airspyhfgui.cpp.
References AirspyHFInput::MsgConfigureAirspyHF::create(), DeviceSampleSource::getInputMessageQueue(), m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by AirspyHFGui().
 {
     qDebug() << "AirspyHFGui::updateHardware";
     AirspyHFInput::MsgConfigureAirspyHF* message = AirspyHFInput::MsgConfigureAirspyHF::create(m_settings, m_forceSettings);
     m_sampleSource->getInputMessageQueue()->push(message);
     m_forceSettings = false;
     m_updateTimer.stop();
 }
updateSampleRateAndFrequency()
void AirspyHFGui::updateSampleRateAndFrequency () private
Definition at line 180 of file airspyhfgui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg((float)m_sampleRate / 1000));
 }
updateStatus
void AirspyHFGui::updateStatus () private slot
Definition at line 429 of file airspyhfgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by AirspyHFGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 AirspyHFGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 69 of file airspyhfgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* AirspyHFGui::m_deviceUISet private
Definition at line 60 of file airspyhfgui.h.
Referenced by AirspyHFGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool AirspyHFGui::m_doApplySettings private
Definition at line 61 of file airspyhfgui.h.
Referenced by on_startStop_toggled().
m_forceSettings
bool AirspyHFGui::m_forceSettings private
Definition at line 62 of file airspyhfgui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue AirspyHFGui::m_inputMessageQueue private
Definition at line 71 of file airspyhfgui.h.
Referenced by AirspyHFGui(), and handleInputMessages().
m_lastEngineState
int AirspyHFGui::m_lastEngineState private
Definition at line 70 of file airspyhfgui.h.
Referenced by updateStatus().
m_rates
std::vector<uint32_t> AirspyHFGui::m_rates private
Definition at line 66 of file airspyhfgui.h.
Referenced by AirspyHFGui(), displaySampleRates(), getDevSampleRate(), and getDevSampleRateIndex().
m_sampleRate
int AirspyHFGui::m_sampleRate private
Definition at line 68 of file airspyhfgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleSource
DeviceSampleSource* AirspyHFGui::m_sampleSource private
Definition at line 67 of file airspyhfgui.h.
Referenced by AirspyHFGui(), on_record_toggled(), on_startStop_toggled(), and updateHardware().
m_settings
AirspyHFSettings AirspyHFGui::m_settings private
Definition at line 63 of file airspyhfgui.h.
Referenced by deserialize(), displayAGC(), displaySampleRates(), displaySettings(), getCenterFrequency(), handleMessage(), on_agc_currentIndexChanged(), on_att_currentIndexChanged(), on_band_currentIndexChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_dsp_toggled(), on_iqImbalance_toggled(), on_lna_toggled(), on_LOppm_valueChanged(), on_sampleRate_currentIndexChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), updateFrequencyLimits(), and updateHardware().
m_statusTimer
QTimer AirspyHFGui::m_statusTimer private
Definition at line 65 of file airspyhfgui.h.
Referenced by AirspyHFGui().
m_updateTimer
QTimer AirspyHFGui::m_updateTimer private
Definition at line 64 of file airspyhfgui.h.
Referenced by AirspyHFGui(), sendSettings(), and updateHardware().
ui
Ui::AirspyHFGui* AirspyHFGui::ui private
Definition at line 58 of file airspyhfgui.h.
Referenced by AirspyHFGui(), displayAGC(), displaySampleRates(), displaySettings(), handleMessage(), on_band_currentIndexChanged(), on_LOppm_valueChanged(), on_record_toggled(), on_resetLOppm_clicked(), on_transverter_clicked(), updateFrequencyLimits(), updateSampleRateAndFrequency(), updateStatus(), and ~AirspyHFGui().
The documentation for this class was generated from the following files:
plugins/samplesource/airspyhf/airspyhfgui.h
plugins/samplesource/airspyhf/airspyhfgui.cpp