SDRAngel: IntervalSliderGUI Class Reference
IntervalSliderGUI Class Reference
#include <intervalslidergui.h>
Public Member Functions
IntervalSliderGUI (QWidget *parent=0)
virtual ~IntervalSliderGUI ()
void setLabel (const QString &text)
void setUnits (const QString &units)
void setInterval (double minimum, double maximum)
virtual double getCurrentValue ()
virtual void setValue (double value)
Public Member Functions inherited from ItemSettingGUI
ItemSettingGUI (QWidget *parent=0)
virtual ~ItemSettingGUI ()
Private Slots
void on_intervalSlider_valueChanged (int value)
Private Attributes
Ui::IntervalSliderGUI * ui
double m_minimum
double m_maximum
Additional Inherited Members
Signals inherited from ItemSettingGUI
void valueChanged (double value)
Detailed Description
Definition at line 31 of file intervalslidergui.h.
Constructor & Destructor Documentation
IntervalSliderGUI()
IntervalSliderGUI::IntervalSliderGUI (QWidget * parent = 0) explicit
Definition at line 23 of file intervalslidergui.cpp.
References ui.
                                                     :
     ItemSettingGUI(parent),
     ui(new Ui::IntervalSliderGUI),
     m_minimum(0),
     m_maximum(0)
 {
     ui->setupUi(this);
 }
~IntervalSliderGUI()
IntervalSliderGUI::~IntervalSliderGUI () virtual
Definition at line 32 of file intervalslidergui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
getCurrentValue()
double IntervalSliderGUI::getCurrentValue () virtual
Implements ItemSettingGUI.
Definition at line 57 of file intervalslidergui.cpp.
References ui.
Referenced by SoapySDRInputGui::displaySettings(), and SoapySDROutputGui::displaySettings().
 {
     return ui->intervalSlider->value();
 }
on_intervalSlider_valueChanged
void IntervalSliderGUI::on_intervalSlider_valueChanged (int value) private slot
Definition at line 68 of file intervalslidergui.cpp.
References arg(), ui, and ItemSettingGUI::valueChanged().
 {
     ui->valueText->setText(QString("%1").arg(value));
     emit ItemSettingGUI::valueChanged(value);
 }
setInterval()
void IntervalSliderGUI::setInterval (double minimum, double maximum)
Definition at line 47 of file intervalslidergui.cpp.
References m_maximum, m_minimum, and ui.
Referenced by SoapySDRInputGui::createGlobalGainControl(), SoapySDROutputGui::createGlobalGainControl(), SoapySDRInputGui::createIndividualGainsControl(), and SoapySDROutputGui::createIndividualGainsControl().
 {
     ui->intervalSlider->blockSignals(true);
     ui->intervalSlider->setMinimum(minimum);
     ui->intervalSlider->setMaximum(maximum);
     ui->intervalSlider->blockSignals(false);
     m_minimum = minimum;
     m_maximum = maximum;
 }
setLabel()
void IntervalSliderGUI::setLabel (const QString & text)
Definition at line 37 of file intervalslidergui.cpp.
References ui.
Referenced by SoapySDRInputGui::createGlobalGainControl(), SoapySDROutputGui::createGlobalGainControl(), SoapySDRInputGui::createIndividualGainsControl(), and SoapySDROutputGui::createIndividualGainsControl().
 {
     ui->intervalLabel->setText(text);
 }
setUnits()
void IntervalSliderGUI::setUnits (const QString & units)
Definition at line 42 of file intervalslidergui.cpp.
References ui.
Referenced by SoapySDRInputGui::createGlobalGainControl(), SoapySDROutputGui::createGlobalGainControl(), SoapySDRInputGui::createIndividualGainsControl(), and SoapySDROutputGui::createIndividualGainsControl().
 {
     ui->intervalUnits->setText(units);
 }
setValue()
void IntervalSliderGUI::setValue (double value) virtual
Implements ItemSettingGUI.
Definition at line 62 of file intervalslidergui.cpp.
References arg(), and ui.
Referenced by SoapySDRInputGui::displaySettings(), and SoapySDROutputGui::displaySettings().
 {
     ui->intervalSlider->setValue(value);
     ui->valueText->setText(QString("%1").arg(ui->intervalSlider->value()));
 }
Member Data Documentation
m_maximum
double IntervalSliderGUI::m_maximum private
Definition at line 50 of file intervalslidergui.h.
Referenced by setInterval().
m_minimum
double IntervalSliderGUI::m_minimum private
Definition at line 49 of file intervalslidergui.h.
Referenced by setInterval().
ui
Ui::IntervalSliderGUI* IntervalSliderGUI::ui private
Definition at line 48 of file intervalslidergui.h.
Referenced by getCurrentValue(), IntervalSliderGUI(), on_intervalSlider_valueChanged(), setInterval(), setLabel(), setUnits(), setValue(), and ~IntervalSliderGUI().
The documentation for this class was generated from the following files:
sdrgui/soapygui/intervalslidergui.h
sdrgui/soapygui/intervalslidergui.cpp