SDRAngel: HackRFOutput::MsgConfigureHackRF Class Reference
HackRFOutput::MsgConfigureHackRF Class Reference
#include <hackrfoutput.h>
Public Member Functions
const HackRFOutputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureHackRF * create (const HackRFOutputSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureHackRF (const HackRFOutputSettings &settings, bool force)
Private Attributes
HackRFOutputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 39 of file hackrfoutput.h.
Constructor & Destructor Documentation
MsgConfigureHackRF()
HackRFOutput::MsgConfigureHackRF::MsgConfigureHackRF (const HackRFOutputSettings & settings, bool force) inline private
Definition at line 55 of file hackrfoutput.h.
Referenced by create().
                                                                              :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureHackRF* HackRFOutput::MsgConfigureHackRF::create (const HackRFOutputSettings & settings, bool force) inline static
Definition at line 46 of file hackrfoutput.h.
References MsgConfigureHackRF().
Referenced by HackRFOutput::deserialize(), HackRFOutput::handleMessage(), HackRFOutput::setCenterFrequency(), HackRFOutputGui::updateHardware(), and HackRFOutput::webapiSettingsPutPatch().
         {
             return new MsgConfigureHackRF(settings, force);
         }
getForce()
bool HackRFOutput::MsgConfigureHackRF::getForce () const inline
Definition at line 44 of file hackrfoutput.h.
References m_force.
Referenced by HackRFOutput::handleMessage().
 { return m_force; }
getSettings()
const HackRFOutputSettings& HackRFOutput::MsgConfigureHackRF::getSettings () const inline
Definition at line 43 of file hackrfoutput.h.
References m_settings.
Referenced by HackRFOutputGui::handleMessage(), and HackRFOutput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool HackRFOutput::MsgConfigureHackRF::m_force private
Definition at line 53 of file hackrfoutput.h.
Referenced by getForce().
m_settings
HackRFOutputSettings HackRFOutput::MsgConfigureHackRF::m_settings private
Definition at line 52 of file hackrfoutput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesink/hackrfoutput/hackrfoutput.h