SDRAngel: SoapySDROutput::MsgReportGainChange Class Reference
SoapySDROutput::MsgReportGainChange Class Reference
#include <soapysdroutput.h>
Public Member Functions
const SoapySDROutputSettings & getSettings () const
bool getGlobalGain () const
bool getIndividualGains () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportGainChange * create (const SoapySDROutputSettings &settings, bool globalGain, bool individualGains)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportGainChange (const SoapySDROutputSettings &settings, bool globalGain, bool individualGains)
Private Attributes
SoapySDROutputSettings m_settings
bool m_globalGain
bool m_individualGains
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 75 of file soapysdroutput.h.
Constructor & Destructor Documentation
MsgReportGainChange()
SoapySDROutput::MsgReportGainChange::MsgReportGainChange (const SoapySDROutputSettings & settings, bool globalGain, bool individualGains) inline private
Definition at line 93 of file soapysdroutput.h.
                                                                                                            :
             Message(),
             m_settings(settings),
             m_globalGain(globalGain),
             m_individualGains(individualGains)
         { }
Member Function Documentation
create()
static MsgReportGainChange* SoapySDROutput::MsgReportGainChange::create (const SoapySDROutputSettings & settings, bool globalGain, bool individualGains) inline static
Definition at line 83 of file soapysdroutput.h.
Referenced by SoapySDROutput::applySettings().
         {
             return new MsgReportGainChange(settings, globalGain, individualGains);
         }
getGlobalGain()
bool SoapySDROutput::MsgReportGainChange::getGlobalGain () const inline
Definition at line 80 of file soapysdroutput.h.
Referenced by SoapySDROutputGui::handleMessage().
 { return m_globalGain; }
getIndividualGains()
bool SoapySDROutput::MsgReportGainChange::getIndividualGains () const inline
Definition at line 81 of file soapysdroutput.h.
Referenced by SoapySDROutputGui::handleMessage().
 { return m_individualGains; }
getSettings()
const SoapySDROutputSettings& SoapySDROutput::MsgReportGainChange::getSettings () const inline
Definition at line 79 of file soapysdroutput.h.
Referenced by SoapySDROutputGui::handleMessage().
 { return m_settings; }
Member Data Documentation
m_globalGain
bool SoapySDROutput::MsgReportGainChange::m_globalGain private
Definition at line 90 of file soapysdroutput.h.
m_individualGains
bool SoapySDROutput::MsgReportGainChange::m_individualGains private
Definition at line 91 of file soapysdroutput.h.
m_settings
SoapySDROutputSettings SoapySDROutput::MsgReportGainChange::m_settings private
Definition at line 89 of file soapysdroutput.h.
The documentation for this class was generated from the following file:
plugins/samplesink/soapysdroutput/soapysdroutput.h