SDRAngel: DeviceHackRF Class Reference
DeviceHackRF Class Reference
#include <devicehackrf.h>
Static Public Member Functions
static DeviceHackRF & instance ()
static hackrf_device * open_hackrf (int sequence)
static hackrf_device * open_hackrf (const char *const serial)
Protected Member Functions
DeviceHackRF ()
DeviceHackRF (const DeviceHackRF &)
DeviceHackRF & operator= (const DeviceHackRF &other)
~DeviceHackRF ()
Static Private Member Functions
static hackrf_device * open_hackrf_from_sequence (int sequence)
Detailed Description
Definition at line 25 of file devicehackrf.h.
Constructor & Destructor Documentation
DeviceHackRF() [1/2]
DeviceHackRF::DeviceHackRF () protected
Definition at line 22 of file devicehackrf.cpp.
 {
     hackrf_error rc = (hackrf_error) hackrf_init();
     if (rc != HACKRF_SUCCESS) {
         qCritical("DeviceHackRF::open_hackrf: failed to initiate HackRF library %s", hackrf_error_name(rc));
     }
 }
DeviceHackRF() [2/2]
DeviceHackRF::DeviceHackRF (const DeviceHackRF &) inline protected
Definition at line 33 of file devicehackrf.h.
 {}
~DeviceHackRF()
DeviceHackRF::~DeviceHackRF () protected
Definition at line 31 of file devicehackrf.cpp.
 {
     hackrf_exit();
 }
Member Function Documentation
instance()
DeviceHackRF & DeviceHackRF::instance () static
Definition at line 36 of file devicehackrf.cpp.
Referenced by HackRFInputPlugin::enumSampleSources(), open_hackrf(), and open_hackrf_from_sequence().
 {
     static DeviceHackRF inst;
     return inst;
 }
open_hackrf() [1/2]
hackrf_device * DeviceHackRF::open_hackrf (int sequence) static
Definition at line 42 of file devicehackrf.cpp.
References instance(), and open_hackrf_from_sequence().
Referenced by HackRFOutput::openDevice(), and HackRFInput::openDevice().
 {
     instance();
     return open_hackrf_from_sequence(sequence);
 }
open_hackrf() [2/2]
hackrf_device * DeviceHackRF::open_hackrf (const char *const serial) static
Definition at line 49 of file devicehackrf.cpp.
References instance().
 {
     hackrf_error rc;
     hackrf_device *hackrf_ptr;
     instance();
     rc = (hackrf_error) hackrf_open_by_serial(serial, &hackrf_ptr);
     if (rc == HACKRF_SUCCESS)
     {
         return hackrf_ptr;
     }
     else
     {
         qCritical("DeviceHackRF::open_hackrf: error #%d: %s", (int) rc, hackrf_error_name(rc));
         return 0;
     }
 }
open_hackrf_from_sequence()
hackrf_device * DeviceHackRF::open_hackrf_from_sequence (int sequence) static private
Definition at line 69 of file devicehackrf.cpp.
References instance().
Referenced by open_hackrf().
 {
     hackrf_device_list_t *hackrf_devices = hackrf_device_list();
     hackrf_device *hackrf_ptr;
     hackrf_error rc;
     instance();
     rc = (hackrf_error) hackrf_device_list_open(hackrf_devices, sequence, &hackrf_ptr);
     if (rc == HACKRF_SUCCESS)
     {
         return hackrf_ptr;
     }
     else
     {
         qCritical("DeviceHackRF::open_hackrf_from_sequence: error #%d: %s", (int) rc, hackrf_error_name(rc));
         return 0;
     }
 }
operator=()
DeviceHackRF& DeviceHackRF::operator= (const DeviceHackRF & other) inline protected
Definition at line 34 of file devicehackrf.h.
 { (void) other; return *this; }
The documentation for this class was generated from the following files:
devices/hackrf/devicehackrf.h
devices/hackrf/devicehackrf.cpp