SDRAngel: ATVMod Class Reference
ATVMod Class Reference
#include <atvmod.h>
Classes
struct ATVCamera
class MsgConfigureATVMod
class MsgConfigureCameraData
class MsgConfigureCameraIndex
class MsgConfigureChannelizer
class MsgConfigureImageFileName
class MsgConfigureVideoFileName
class MsgConfigureVideoFileSourceSeek
class MsgConfigureVideoFileSourceStreamTiming
class MsgReportCameraData
class MsgReportEffectiveSampleRate
class MsgReportVideoFileSourceStreamData
class MsgReportVideoFileSourceStreamTiming
Signals
void levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples)
Public Member Functions
ATVMod (DeviceAPI *deviceAPI)
~ATVMod ()
virtual void destroy ()
virtual void pull (Sample &sample)
virtual void pullAudio (int nbSamples)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
int getEffectiveSampleRate () const
double getMagSq () const
void getCameraNumbers (std::vector< int > &numbers)
Public Member Functions inherited from BasebandSampleSource
BasebandSampleSource ()
virtual ~BasebandSampleSource ()
void feed (SampleSourceFifo *sampleFifo, int nbSamples)
SampleSourceFifo & getSampleSourceFifo ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
void setDeviceSampleSourceFifo (SampleSourceFifo *deviceSampleFifo)
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Member Functions
static void getBaseValues (int outputSampleRate, int linesPerSecond, int &sampleRateUnits, uint32_t &nbPointsPerRateUnit)
static float getRFBandwidthDivisor (ATVModSettings::ATVModulation modulation)
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channeltx.modatv"
static const QString m_channelId = "ATVMod"
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applyChannelSettings (int outputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const ATVModSettings &settings, bool force=false)
void pullFinalize (Complex &ci, Sample &sample)
void pullVideo (Real &sample)
void calculateLevel (Real &sample)
void modulateSample ()
Complex & modulateSSB (Real &sample)
Complex & modulateVestigialSSB (Real &sample)
void applyStandard ()
void openImage (const QString &fileName)
void openVideo (const QString &fileName)
void resizeImage ()
void calculateVideoSizes ()
void resizeVideo ()
void seekVideoFileStream (int seekPercentage)
void scanCameras ()
void releaseCameras ()
void calculateCamerasSizes ()
void resizeCameras ()
void resizeCamera ()
void mixImageAndText (cv::Mat &image)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const ATVModSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const ATVModSettings &settings, bool force)
void pullImageLine (Real &sample, bool noHSync=false)
void pullVSyncLineLongPulses (Real &sample)
void pullVSyncLineEqualizingPulses (Real &sample)
void pullVSyncLineEqualizingThenLongPulses (Real &sample)
void pullVSyncLineLongThenEqualizingPulses (Real &sample)
void pullVSyncLine (Real &sample)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSource * m_threadedChannelizer
UpChannelizer * m_channelizer
int m_outputSampleRate
int m_inputFrequencyOffset
ATVModSettings m_settings
NCO m_carrierNco
Complex m_modSample
float m_modPhasor
For FM modulation.
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
int m_tvSampleRate
sample rate for generating signal
uint32_t m_pointsPerLine
Number of points per full line.
int m_pointsPerSync
number of line points for the horizontal sync
int m_pointsPerBP
number of line points for the back porch
int m_pointsPerImgLine
number of line points for the image line
uint32_t m_pointsPerFP
number of line points for the front porch
int m_pointsPerFSync
number of line points for the field first sync
uint32_t m_pointsPerHBar
number of line points for a bar of the bar chart
uint32_t m_linesPerVBar
number of lines for a bar of the bar chart
uint32_t m_pointsPerTU
number of line points per time unit
int m_nbLines
number of lines per complete frame
int m_nbLines2
same number as above (non interlaced) or half the number above (interlaced)
uint32_t m_nbImageLines
number of image lines excluding synchronization lines
uint32_t m_nbImageLines2
same number as above (non interlaced) or half the number above (interlaced)
int m_nbHorizPoints
number of line points per horizontal line
int m_nbSyncLinesHeadE
number of header sync lines on even frame
int m_nbSyncLinesHeadO
number of header sync lines on odd frame
int m_nbSyncLinesBottom
number of sync lines at bottom
int m_nbLongSyncLines
number of whole long sync lines for vertical synchronization
int m_nbHalfLongSync
number of half long sync / equalization lines
int m_nbWholeEqLines
number of whole equalizing lines
bool m_singleLongSync
single or double long sync per long sync line
int m_nbBlankLines
number of lines in a frame (full or half) that are blanked (black) at the top of the image
float m_blankLineLvel
video level of blank lines
float m_hBarIncrement
video level increment at each horizontal bar increment
float m_vBarIncrement
video level increment at each vertical bar increment
bool m_interleaved
true if image is interlaced (2 half frames per frame)
bool m_evenImage
in interlaced mode true if this is an even image
QMutex m_settingsMutex
int m_horizontalCount
current point index on line
int m_lineCount
current line index in frame
float m_fps
resulting frames per second
MovingAverageUtil< double, double, 16 > m_movingAverage
quint32 m_levelCalcCount
Real m_peakLevel
Real m_levelSum
cv::Mat m_imageFromFile
original image not resized not overlaid by text
cv::Mat m_imageOriginal
original not resized image
cv::Mat m_image
resized image for transmission at given rate
bool m_imageOK
cv::VideoCapture m_video
current video capture
cv::Mat m_videoframeOriginal
current frame from video
cv::Mat m_videoFrame
current displayable video frame
float m_videoFPS
current video FPS rate
int m_videoWidth
current video frame width
int m_videoHeight
current video frame height
float m_videoFx
current video horizontal scaling factor
float m_videoFy
current video vertictal scaling factor
float m_videoFPSq
current video FPS sacaling factor
float m_videoFPSCount
current video FPS fractional counter
int m_videoPrevFPSCount
current video FPS previous integer counter
int m_videoLength
current video length in frames
bool m_videoEOF
current video has reached end of file
bool m_videoOK
std::vector< ATVCamera > m_cameras
vector of available cameras
int m_cameraIndex
curent camera index in list of available cameras
std::string m_overlayText
QString m_imageFileName
QString m_videoFileName
fftfilt * m_SSBFilter
Complex * m_SSBFilterBuffer
int m_SSBFilterBufferIndex
fftfilt * m_DSBFilter
Complex * m_DSBFilterBuffer
int m_DSBFilterBufferIndex
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Static Private Attributes
static const int m_ssbFftLen = 1024
static const float m_blackLevel = 0.3f
static const float m_spanLevel = 0.7f
static const int m_levelNbSamples = 10000
static const int m_nbBars = 6
number of bars in bar or chessboard patterns
static const int m_cameraFPSTestNbFrames = 100
number of frames for camera FPS test
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSource
void handleInputMessages ()
void handleWriteToFifo (int nbSamples)
void handleWriteToDeviceFifo (int nbSamples)
Protected Member Functions inherited from BasebandSampleSource
void handleWriteToFifo (SampleSourceFifo *sampleFifo, int nbSamples)
Protected Attributes inherited from BasebandSampleSource
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
SampleSourceFifo m_sampleFifo
Internal FIFO for multi-channel processing.
SampleSourceFifo * m_deviceSampleFifo
Reference to the device FIFO for single channel processing.
Detailed Description
Definition at line 49 of file atvmod.h.
Constructor & Destructor Documentation
ATVMod()
ATVMod::ATVMod (DeviceAPI * deviceAPI)
Definition at line 61 of file atvmod.cpp.
References DeviceAPI::addChannelSource(), DeviceAPI::addChannelSourceAPI(), applyChannelSettings(), applySettings(), m_channelId, m_channelizer, m_deviceAPI, m_DSBFilter, m_DSBFilterBuffer, m_inputFrequencyOffset, m_interpolatorDistance, m_interpolatorDistanceRemain, m_networkManager, m_outputSampleRate, ATVModSettings::m_rfBandwidth, m_settings, m_ssbFftLen, m_SSBFilter, m_SSBFilterBuffer, m_threadedChannelizer, networkManagerFinished(), and scanCameras().
Referenced by ATVMod::MsgReportEffectiveSampleRate::MsgReportEffectiveSampleRate().
                                    :
     ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSource),
     m_deviceAPI(deviceAPI),
     m_outputSampleRate(1000000),
     m_inputFrequencyOffset(0),
     m_modPhasor(0.0f),
     m_tvSampleRate(1000000),
     m_evenImage(true),
     m_settingsMutex(QMutex::Recursive),
     m_horizontalCount(0),
     m_lineCount(0),
     m_imageOK(false),
     m_videoFPSq(1.0f),
     m_videoFPSCount(0.0f),
     m_videoPrevFPSCount(0),
     m_videoEOF(false),
     m_videoOK(false),
     m_cameraIndex(-1),
     //m_showOverlayText(false),
     m_SSBFilter(0),
     m_SSBFilterBuffer(0),
     m_SSBFilterBufferIndex(0),
     m_DSBFilter(0),
     m_DSBFilterBuffer(0),
     m_DSBFilterBufferIndex(0)
 {
     setObjectName(m_channelId);
     scanCameras();
     m_SSBFilter = new fftfilt(0, m_settings.m_rfBandwidth / m_outputSampleRate, m_ssbFftLen);
     m_SSBFilterBuffer = new Complex[m_ssbFftLen>>1]; // filter returns data exactly half of its size
     memset(m_SSBFilterBuffer, 0, sizeof(Complex)*(m_ssbFftLen>>1));
     m_DSBFilter = new fftfilt((2.0f * m_settings.m_rfBandwidth) / m_outputSampleRate, 2 * m_ssbFftLen);
     m_DSBFilterBuffer = new Complex[m_ssbFftLen];
     memset(m_DSBFilterBuffer, 0, sizeof(Complex)*(m_ssbFftLen));
     m_interpolatorDistanceRemain = 0.0f;
     m_interpolatorDistance = 1.0f;
     applyChannelSettings(m_outputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true); // does applyStandard() too;
     m_channelizer = new UpChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSource(m_channelizer, this);
     m_deviceAPI->addChannelSource(m_threadedChannelizer);
     m_deviceAPI->addChannelSourceAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~ATVMod()
ATVMod::~ATVMod ()
Definition at line 113 of file atvmod.cpp.
References m_channelizer, m_deviceAPI, m_DSBFilter, m_DSBFilterBuffer, m_networkManager, m_SSBFilter, m_SSBFilterBuffer, m_threadedChannelizer, m_video, networkManagerFinished(), releaseCameras(), DeviceAPI::removeChannelSource(), and DeviceAPI::removeChannelSourceAPI().
Referenced by ATVMod::MsgReportEffectiveSampleRate::MsgReportEffectiveSampleRate().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_video.isOpened()) {
         m_video.release();
     }
     releaseCameras();
     m_deviceAPI->removeChannelSourceAPI(this);
     m_deviceAPI->removeChannelSource(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete m_SSBFilter;
     delete m_DSBFilter;
     delete[] m_SSBFilterBuffer;
     delete[] m_DSBFilterBuffer;
 }
Member Function Documentation
applyChannelSettings()
void ATVMod::applyChannelSettings (int outputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 1033 of file atvmod.cpp.
References applyStandard(), Interpolator::create(), ATVMod::MsgReportEffectiveSampleRate::create(), fftfilt::create_filter(), getBaseValues(), BasebandSampleSource::getMessageQueueToGUI(), getRFBandwidthDivisor(), ATVModSettings::m_atvModulation, m_carrierNco, ATVModSettings::m_fps, m_inputFrequencyOffset, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, ATVModSettings::m_nbLines, m_outputSampleRate, m_pointsPerLine, ATVModSettings::m_rfBandwidth, m_settings, m_settingsMutex, m_ssbFftLen, m_SSBFilter, m_SSBFilterBuffer, m_SSBFilterBufferIndex, m_tvSampleRate, MessageQueue::push(), and NCO::setFreq().
Referenced by ATVMod(), handleMessage(), and start().
 {
     qDebug() << "AMMod::applyChannelSettings:"
             << " outputSampleRate: " << outputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if ((inputFrequencyOffset != m_inputFrequencyOffset) ||
         (outputSampleRate != m_outputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_carrierNco.setFreq(inputFrequencyOffset, outputSampleRate);
         m_settingsMutex.unlock();
     }
     if ((outputSampleRate != m_outputSampleRate) || force)
     {
         getBaseValues(outputSampleRate, m_settings.m_nbLines * m_settings.m_fps, m_tvSampleRate, m_pointsPerLine);
         m_settingsMutex.lock();
         if (m_tvSampleRate > 0)
         {
             m_interpolatorDistanceRemain = 0;
             m_interpolatorDistance = (Real) m_tvSampleRate / (Real) outputSampleRate;
             m_interpolator.create(32,
                     m_tvSampleRate,
                     m_settings.m_rfBandwidth / getRFBandwidthDivisor(m_settings.m_atvModulation),
                     3.0);
         }
         else
         {
             m_tvSampleRate = outputSampleRate;
         }
         m_SSBFilter->create_filter(0, m_settings.m_rfBandwidth / m_tvSampleRate);
         memset(m_SSBFilterBuffer, 0, sizeof(Complex)*(m_ssbFftLen>>1));
         m_SSBFilterBufferIndex = 0;
         applyStandard(); // set all timings
         m_settingsMutex.unlock();
         if (getMessageQueueToGUI())
         {
             MsgReportEffectiveSampleRate *report;
             report = MsgReportEffectiveSampleRate::create(m_tvSampleRate, m_pointsPerLine);
             getMessageQueueToGUI()->push(report);
         }
     }
     m_outputSampleRate = outputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applySettings()
void ATVMod::applySettings (const ATVModSettings & settings, bool force = false) private
Definition at line 1086 of file atvmod.cpp.
References applyStandard(), Interpolator::create(), ATVMod::MsgReportEffectiveSampleRate::create(), fftfilt::create_asym_filter(), fftfilt::create_filter(), getBaseValues(), BasebandSampleSource::getMessageQueueToGUI(), getRFBandwidthDivisor(), ATVModSettings::m_atvModInput, ATVModSettings::m_atvModulation, ATVModSettings::m_atvStd, ATVModSettings::m_cameraPlay, ATVModSettings::m_channelMute, m_DSBFilter, m_DSBFilterBuffer, m_DSBFilterBufferIndex, ATVModSettings::m_fmExcursion, ATVModSettings::m_forceDecimator, ATVModSettings::m_fps, m_imageFromFile, m_imageOriginal, ATVModSettings::m_inputFrequencyOffset, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, ATVModSettings::m_invertedVideo, ATVModSettings::m_nbLines, m_outputSampleRate, ATVModSettings::m_overlayText, m_pointsPerLine, ATVModSettings::m_reverseAPIAddress, ATVModSettings::m_reverseAPIChannelIndex, ATVModSettings::m_reverseAPIDeviceIndex, ATVModSettings::m_reverseAPIPort, ATVModSettings::m_rfBandwidth, ATVModSettings::m_rfOppBandwidth, ATVModSettings::m_rfScalingFactor, m_settings, m_settingsMutex, ATVModSettings::m_showOverlayText, m_ssbFftLen, m_SSBFilter, m_SSBFilterBuffer, m_SSBFilterBufferIndex, m_tvSampleRate, ATVModSettings::m_uniformLevel, ATVModSettings::m_useReverseAPI, ATVModSettings::m_videoPlay, ATVModSettings::m_videoPlayLoop, mixImageAndText(), MessageQueue::push(), resizeImage(), and webapiReverseSendSettings().
Referenced by ATVMod(), and handleMessage().
 {
     qDebug() << "ATVMod::applySettings:"
             << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
             << " m_rfBandwidth: " << settings.m_rfBandwidth
             << " m_rfOppBandwidth: " << settings.m_rfOppBandwidth
             << " m_atvStd: " << (int) settings.m_atvStd
             << " m_nbLines: " << settings.m_nbLines
             << " m_fps: " << settings.m_fps
             << " m_atvModInput: " << (int) settings.m_atvModInput
             << " m_uniformLevel: " << settings.m_uniformLevel
             << " m_atvModulation: " << (int) settings.m_atvModulation
             << " m_videoPlayLoop: " << settings.m_videoPlayLoop
             << " m_videoPlay: " << settings.m_videoPlay
             << " m_cameraPlay: " << settings.m_cameraPlay
             << " m_channelMute: " << settings.m_channelMute
             << " m_invertedVideo: " << settings.m_invertedVideo
             << " m_rfScalingFactor: " << settings.m_rfScalingFactor
             << " m_fmExcursion: " << settings.m_fmExcursion
             << " m_forceDecimator: " << settings.m_forceDecimator
             << " m_showOverlayText: " << settings.m_showOverlayText
             << " m_overlayText: " << settings.m_overlayText
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if ((settings.m_inputFrequencyOffset != m_settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if ((settings.m_rfBandwidth != m_settings.m_rfBandwidth) || force) {
         reverseAPIKeys.append("rfBandwidth");
     }
     if ((settings.m_rfOppBandwidth != m_settings.m_rfOppBandwidth) || force) {
         reverseAPIKeys.append("rfOppBandwidth");
     }
     if ((settings.m_atvStd != m_settings.m_atvStd) || force) {
         reverseAPIKeys.append("atvStd");
     }
     if ((settings.m_nbLines != m_settings.m_nbLines) || force) {
         reverseAPIKeys.append("nbLines");
     }
     if ((settings.m_fps != m_settings.m_fps) || force) {
         reverseAPIKeys.append("fps");
     }
     if ((settings.m_atvModInput != m_settings.m_atvModInput) || force) {
         reverseAPIKeys.append("atvModInput");
     }
     if ((settings.m_uniformLevel != m_settings.m_uniformLevel) || force) {
         reverseAPIKeys.append("uniformLevel");
     }
     if ((settings.m_uniformLevel != m_settings.m_uniformLevel) || force) {
         reverseAPIKeys.append("uniformLevel");
     }
     if ((settings.m_atvModulation != m_settings.m_atvModulation) || force) {
         reverseAPIKeys.append("atvModulation");
     }
     if ((settings.m_videoPlayLoop != m_settings.m_videoPlayLoop) || force) {
         reverseAPIKeys.append("videoPlayLoop");
     }
     if ((settings.m_videoPlay != m_settings.m_videoPlay) || force) {
         reverseAPIKeys.append("videoPlay");
     }
     if ((settings.m_cameraPlay != m_settings.m_cameraPlay) || force) {
         reverseAPIKeys.append("cameraPlay");
     }
     if ((settings.m_channelMute != m_settings.m_channelMute) || force) {
         reverseAPIKeys.append("channelMute");
     }
     if ((settings.m_invertedVideo != m_settings.m_invertedVideo) || force) {
         reverseAPIKeys.append("invertedVideo");
     }
     if ((settings.m_rfScalingFactor != m_settings.m_rfScalingFactor) || force) {
         reverseAPIKeys.append("rfScalingFactor");
     }
     if ((settings.m_fmExcursion != m_settings.m_fmExcursion) || force) {
         reverseAPIKeys.append("fmExcursion");
     }
     if ((settings.m_forceDecimator != m_settings.m_forceDecimator) || force) {
         reverseAPIKeys.append("forceDecimator");
     }
     if ((settings.m_showOverlayText != m_settings.m_showOverlayText) || force) {
         reverseAPIKeys.append("showOverlayText");
     }
     if ((settings.m_overlayText != m_settings.m_overlayText) || force) {
         reverseAPIKeys.append("overlayText");
     }
     if ((settings.m_atvStd != m_settings.m_atvStd)
         || (settings.m_nbLines != m_settings.m_nbLines)
         || (settings.m_fps != m_settings.m_fps)
         || (settings.m_rfBandwidth != m_settings.m_rfBandwidth)
         || (settings.m_atvModulation != m_settings.m_atvModulation) || force)
     {
         getBaseValues(m_outputSampleRate, settings.m_nbLines * settings.m_fps, m_tvSampleRate, m_pointsPerLine);
         m_settingsMutex.lock();
         if (m_tvSampleRate > 0)
         {
             m_interpolatorDistanceRemain = 0;
             m_interpolatorDistance = (Real) m_tvSampleRate / (Real) m_outputSampleRate;
             m_interpolator.create(32,
                     m_tvSampleRate,
                     settings.m_rfBandwidth / getRFBandwidthDivisor(settings.m_atvModulation),
                     3.0);
         }
         m_SSBFilter->create_filter(0, settings.m_rfBandwidth / m_tvSampleRate);
         memset(m_SSBFilterBuffer, 0, sizeof(Complex)*(m_ssbFftLen>>1));
         m_SSBFilterBufferIndex = 0;
         applyStandard(); // set all timings
         m_settingsMutex.unlock();
         if (getMessageQueueToGUI())
         {
             MsgReportEffectiveSampleRate *report;
             report = MsgReportEffectiveSampleRate::create(m_tvSampleRate, m_pointsPerLine);
             getMessageQueueToGUI()->push(report);
         }
     }
     if ((settings.m_rfOppBandwidth != m_settings.m_rfOppBandwidth)
         || (settings.m_rfBandwidth != m_settings.m_rfBandwidth)
         || (settings.m_nbLines != m_settings.m_nbLines) // difference in line period may have changed TV sample rate
         || (settings.m_fps != m_settings.m_fps)         //
         || force)
     {
         m_settingsMutex.lock();
         m_DSBFilter->create_asym_filter(settings.m_rfOppBandwidth / m_tvSampleRate, settings.m_rfBandwidth / m_tvSampleRate);
         memset(m_DSBFilterBuffer, 0, sizeof(Complex)*(m_ssbFftLen));
         m_DSBFilterBufferIndex = 0;
         m_settingsMutex.unlock();
     }
     if ((settings.m_showOverlayText != m_settings.m_showOverlayText) || force)
     {
         if (!m_imageFromFile.empty())
         {
             m_imageFromFile.copyTo(m_imageOriginal);
             if (settings.m_showOverlayText) {
                 qDebug("ATVMod::applySettings: set overlay text");
                 mixImageAndText(m_imageOriginal);
             } else{
                 qDebug("ATVMod::applySettings: clear overlay text");
             }
             resizeImage();
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
applyStandard()
void ATVMod::applyStandard () private
Definition at line 676 of file atvmod.cpp.
References ATVModSettings::ATVStd405, ATVModSettings::ATVStdHSkip, ATVModSettings::ATVStdPAL525, ATVModSettings::ATVStdPAL625, ATVModSettings::ATVStdShort, ATVModSettings::ATVStdShortInterleaved, calculateCamerasSizes(), calculateVideoSizes(), ATVModSettings::m_atvStd, m_blackLevel, m_blankLineLvel, ATVModSettings::m_fps, m_fps, m_hBarIncrement, m_imageOK, m_interleaved, m_linesPerVBar, m_nbBars, m_nbBlankLines, m_nbHalfLongSync, m_nbHorizPoints, m_nbImageLines, m_nbImageLines2, ATVModSettings::m_nbLines, m_nbLines, m_nbLines2, m_nbLongSyncLines, m_nbSyncLinesBottom, m_nbSyncLinesHeadE, m_nbSyncLinesHeadO, m_nbWholeEqLines, m_pointsPerBP, m_pointsPerFP, m_pointsPerFSync, m_pointsPerHBar, m_pointsPerImgLine, m_pointsPerLine, m_pointsPerSync, m_settings, m_singleLongSync, m_spanLevel, m_vBarIncrement, m_videoOK, resizeImage(), and resizeVideo().
Referenced by applyChannelSettings(), and applySettings().
 {
     m_pointsPerSync  = (uint32_t) ((4.7f / 64.0f) * m_pointsPerLine);
     m_pointsPerBP    = (uint32_t) ((4.7f / 64.0f) * m_pointsPerLine);
     m_pointsPerFP    = (uint32_t) ((2.6f / 64.0f) * m_pointsPerLine);
     m_pointsPerFSync = (uint32_t) ((2.3f / 64.0f) * m_pointsPerLine);
     m_pointsPerImgLine = m_pointsPerLine - m_pointsPerSync - m_pointsPerBP - m_pointsPerFP;
     m_nbHorizPoints    = m_pointsPerLine;
     m_pointsPerHBar    = m_pointsPerImgLine / m_nbBars;
     m_hBarIncrement    = m_spanLevel / (float) m_nbBars;
     m_vBarIncrement    = m_spanLevel / (float) m_nbBars;
     m_nbLines          = m_settings.m_nbLines;
     m_nbLines2         = m_nbLines / 2;
     m_fps              = m_settings.m_fps * 1.0f;
 //    qDebug() << "ATVMod::applyStandard: "
 //            << " m_nbLines: " << m_config.m_nbLines
 //            << " m_fps: " << m_config.m_fps
 //            << " rateUnits: " << rateUnits
 //            << " nbPointsPerRateUnit: " << nbPointsPerRateUnit
 //            << " m_tvSampleRate: " << m_tvSampleRate
 //            << " m_pointsPerTU: " << m_pointsPerTU;
     switch(m_settings.m_atvStd)
     {
     case ATVModSettings::ATVStdHSkip:
         m_nbImageLines     = m_nbLines; // lines less the total number of sync lines
         m_nbImageLines2    = m_nbImageLines; // force non interleaved for vbars
         m_interleaved       = false;
         m_nbSyncLinesHeadE = 0; // number of sync lines on the top of a frame even
         m_nbSyncLinesHeadO = 0; // number of sync lines on the top of a frame odd
         m_nbSyncLinesBottom = -1; // force no vsync in even block
         m_nbLongSyncLines  = 0;
         m_nbHalfLongSync   = 0;
         m_nbWholeEqLines   = 0;
         m_singleLongSync   = true;
         m_nbBlankLines     = 0;
         m_blankLineLvel    = 0.7f;
         m_nbLines2         = m_nbLines - 1;
         break;
     case ATVModSettings::ATVStdShort:
         m_nbImageLines     = m_nbLines - 2; // lines less the total number of sync lines
         m_nbImageLines2    = m_nbImageLines; // force non interleaved for vbars
         m_interleaved       = false;
         m_nbSyncLinesHeadE = 1; // number of sync lines on the top of a frame even
         m_nbSyncLinesHeadO = 1; // number of sync lines on the top of a frame odd
         m_nbSyncLinesBottom = 0;
         m_nbLongSyncLines  = 1;
         m_nbHalfLongSync   = 0;
         m_nbWholeEqLines   = 0;
         m_singleLongSync   = true;
         m_nbBlankLines     = 1;
         m_blankLineLvel    = 0.7f;
         m_nbLines2         = m_nbLines; // force non interleaved => treated as even for all lines
         break;
     case ATVModSettings::ATVStdShortInterleaved:
         m_nbImageLines     = m_nbLines - 2; // lines less the total number of sync lines
         m_nbImageLines2    = m_nbImageLines / 2;
         m_interleaved       = true;
         m_nbSyncLinesHeadE = 1; // number of sync lines on the top of a frame even
         m_nbSyncLinesHeadO = 1; // number of sync lines on the top of a frame odd
         m_nbSyncLinesBottom = 0;
         m_nbLongSyncLines  = 1;
         m_nbHalfLongSync   = 0;
         m_nbWholeEqLines   = 0;
         m_singleLongSync   = true;
         m_nbBlankLines     = 1;
         m_blankLineLvel    = 0.7f;
         break;
     case ATVModSettings::ATVStd405: // Follows loosely the 405 lines standard
         m_nbImageLines     = m_nbLines - 15; // lines less the total number of sync lines
         m_nbImageLines2    = m_nbImageLines / 2;
         m_interleaved       = true;
         m_nbSyncLinesHeadE = 5; // number of sync lines on the top of a frame even
         m_nbSyncLinesHeadO = 4; // number of sync lines on the top of a frame odd
         m_nbSyncLinesBottom = 3;
         m_nbLongSyncLines  = 2;
         m_nbHalfLongSync   = 1;
         m_nbWholeEqLines   = 2;
         m_singleLongSync   = false;
         m_nbBlankLines     = 7; // yields 376 lines (195 - 7) * 2
         m_blankLineLvel    = m_blackLevel;
         break;
     case ATVModSettings::ATVStdPAL525: // Follows PAL-M standard
         m_nbImageLines     = m_nbLines - 15;
         m_nbImageLines2    = m_nbImageLines / 2;
         m_interleaved       = true;
         m_nbSyncLinesHeadE = 5;
         m_nbSyncLinesHeadO = 4; // number of sync lines on the top of a frame odd
         m_nbSyncLinesBottom = 3;
         m_nbLongSyncLines  = 2;
         m_nbHalfLongSync   = 1;
         m_nbWholeEqLines   = 2;
         m_singleLongSync   = false;
         m_nbBlankLines     = 15; // yields 480 lines (255 - 15) * 2
         m_blankLineLvel    = m_blackLevel;
         break;
     case ATVModSettings::ATVStdPAL625: // Follows PAL-B/G/H standard
     default:
         m_nbImageLines     = m_nbLines - 15;
         m_nbImageLines2    = m_nbImageLines / 2;
         m_interleaved       = true;
         m_nbSyncLinesHeadE = 5;
         m_nbSyncLinesHeadO = 4; // number of sync lines on the top of a frame odd
         m_nbSyncLinesBottom = 3;
         m_nbLongSyncLines  = 2;
         m_nbHalfLongSync   = 1;
         m_nbWholeEqLines   = 2;
         m_singleLongSync   = false;
         m_nbBlankLines     = 17; // yields 576 lines (305 - 17) * 2
         m_blankLineLvel    = m_blackLevel;
     }
     m_linesPerVBar = m_nbImageLines2  / m_nbBars;
     if (m_imageOK)
     {
         resizeImage();
     }
     if (m_videoOK)
     {
         calculateVideoSizes();
         resizeVideo();
     }
     calculateCamerasSizes();
 }
calculateCamerasSizes()
void ATVMod::calculateCamerasSizes () private
Definition at line 898 of file atvmod.cpp.
References m_cameras, m_fps, m_nbBlankLines, m_nbImageLines, and m_pointsPerImgLine.
Referenced by applyStandard(), and scanCameras().
 {
     for (std::vector<ATVCamera>::iterator it = m_cameras.begin(); it != m_cameras.end(); ++it)
     {
         it->m_videoFy = (m_nbImageLines - 2*m_nbBlankLines) / (float) it->m_videoHeight;
         it->m_videoFx = m_pointsPerImgLine / (float) it->m_videoWidth;
         it->m_videoFPSq = it->m_videoFPS / m_fps;
         it->m_videoFPSqManual = it->m_videoFPSManual / m_fps;
         it->m_videoFPSCount = 0; //it->m_videoFPSq;
         it->m_videoPrevFPSCount = 0;
         qDebug("ATVMod::calculateCamerasSizes: [%d] factors: %f x %f FPSq: %f", (int) (it - m_cameras.begin()),  it->m_videoFx, it->m_videoFy, it->m_videoFPSq);
     }
 }
calculateLevel()
void ATVMod::calculateLevel (Real & sample) private
Definition at line 490 of file atvmod.cpp.
References levelChanged(), m_levelCalcCount, m_levelNbSamples, m_levelSum, m_peakLevel, leansdr::max(), and sqrt().
Referenced by modulateSample().
 {
     if (m_levelCalcCount < m_levelNbSamples)
     {
         m_peakLevel = std::max(std::fabs(m_peakLevel), sample);
         m_levelSum += sample * sample;
         m_levelCalcCount++;
     }
     else
     {
         qreal rmsLevel = std::sqrt(m_levelSum / m_levelNbSamples);
         //qDebug("NFMMod::calculateLevel: %f %f", rmsLevel, m_peakLevel);
         emit levelChanged(rmsLevel, m_peakLevel, m_levelNbSamples);
         m_peakLevel = 0.0f;
         m_levelSum = 0.0f;
         m_levelCalcCount = 0;
     }
 }
calculateVideoSizes()
void ATVMod::calculateVideoSizes () private
Definition at line 880 of file atvmod.cpp.
References m_fps, m_nbBlankLines, m_nbImageLines, m_pointsPerImgLine, m_videoFPS, m_videoFPSCount, m_videoFPSq, m_videoFx, m_videoFy, m_videoHeight, m_videoPrevFPSCount, and m_videoWidth.
Referenced by applyStandard(), and openVideo().
 {
     m_videoFy = (m_nbImageLines - 2*m_nbBlankLines) / (float) m_videoHeight;
     m_videoFx = m_pointsPerImgLine / (float) m_videoWidth;
     m_videoFPSq = m_videoFPS / m_fps;
     m_videoFPSCount = m_videoFPSq;
     m_videoPrevFPSCount = 0;
     qDebug("ATVMod::calculateVideoSizes: factors: %f x %f FPSq: %f", m_videoFx, m_videoFy, m_videoFPSq);
 }
deserialize()
bool ATVMod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 1258 of file atvmod.cpp.
References ATVMod::MsgConfigureATVMod::create(), ATVModSettings::deserialize(), BasebandSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and ATVModSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureATVMod *msg = MsgConfigureATVMod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureATVMod *msg = MsgConfigureATVMod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void ATVMod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 360 of file atvmod.h.
References handleMessage(), pull(), pullAudio(), start(), and stop().
 { delete this; }
getBaseValues()
void ATVMod::getBaseValues (int outputSampleRate, int linesPerSecond, int & sampleRateUnits, uint32_t & nbPointsPerRateUnit) static
Definition at line 644 of file atvmod.cpp.
References i.
Referenced by applyChannelSettings(), applySettings(), and getMagSq().
 {
     int maxPoints = outputSampleRate / linesPerSecond;
     int i = maxPoints;
     for (; i > 0; i--)
     {
         if ((i * linesPerSecond) % 10 == 0)
             break;
     }
     nbPointsPerRateUnit = i == 0 ? maxPoints : i;
     sampleRateUnits = nbPointsPerRateUnit * linesPerSecond;
 }
getCameraNumbers()
void ATVMod::getCameraNumbers (std::vector< int > & numbers)
Definition at line 990 of file atvmod.cpp.
References ATVMod::MsgReportCameraData::create(), BasebandSampleSource::getMessageQueueToGUI(), m_cameraIndex, m_cameras, m_videoFPS, m_videoHeight, m_videoWidth, and MessageQueue::push().
Referenced by ATVModGUI::ATVModGUI(), and getMagSq().
 {
     for (std::vector<ATVCamera>::iterator it = m_cameras.begin(); it != m_cameras.end(); ++it) {
         numbers.push_back(it->m_cameraNumber);
     }
     if (m_cameras.size() > 0)
     {
         m_cameraIndex = 0;
         if (getMessageQueueToGUI())
         {
             MsgReportCameraData *report;
             report = MsgReportCameraData::create(
                     m_cameras[0].m_cameraNumber,
                     m_cameras[0].m_videoFPS,
                     m_cameras[0].m_videoFPSManual,
                     m_cameras[0].m_videoFPSManualEnable,
                     m_cameras[0].m_videoWidth,
                     m_cameras[0].m_videoHeight,
                     0);
             getMessageQueueToGUI()->push(report);
         }
     }
 }
getCenterFrequency()
virtual qint64 ATVMod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 370 of file atvmod.h.
References deserialize(), ATVModSettings::m_inputFrequencyOffset, ATVMod::MsgConfigureATVMod::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getEffectiveSampleRate()
int ATVMod::getEffectiveSampleRate () const inline
Definition at line 399 of file atvmod.h.
References m_tvSampleRate.
Referenced by ATVModGUI::displaySettings(), and ATVModGUI::on_modulation_currentIndexChanged().
 { return m_tvSampleRate; };
getIdentifier()
virtual void ATVMod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 368 of file atvmod.h.
 { id = objectName(); }
getMagSq()
double ATVMod::getMagSq () const inline
Definition at line 400 of file atvmod.h.
References MovingAverageUtil< T, Total, N >::asDouble(), getBaseValues(), getCameraNumbers(), getRFBandwidthDivisor(), and m_movingAverage.
Referenced by ATVModGUI::tick(), and webapiFormatChannelReport().
 { return m_movingAverage.asDouble(); }
getNbSinkStreams()
virtual int ATVMod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 375 of file atvmod.h.
 { return 1; }
getNbSourceStreams()
virtual int ATVMod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 376 of file atvmod.h.
 { return 0; }
getRFBandwidthDivisor()
float ATVMod::getRFBandwidthDivisor (ATVModSettings::ATVModulation modulation) static
Definition at line 659 of file atvmod.cpp.
References ATVModSettings::ATVModulationAM, ATVModSettings::ATVModulationFM, ATVModSettings::ATVModulationLSB, ATVModSettings::ATVModulationUSB, ATVModSettings::ATVModulationVestigialLSB, and ATVModSettings::ATVModulationVestigialUSB.
Referenced by applyChannelSettings(), applySettings(), and getMagSq().
 {
     switch(modulation)
     {
     case ATVModSettings::ATVModulationLSB:
     case ATVModSettings::ATVModulationUSB:
     case ATVModSettings::ATVModulationVestigialLSB:
     case ATVModSettings::ATVModulationVestigialUSB:
         return 1.05f;
         break;
     case ATVModSettings::ATVModulationAM:
     case ATVModSettings::ATVModulationFM:
     default:
         return 2.2f;
     }
 }
getStreamCenterFrequency()
virtual qint64 ATVMod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 378 of file atvmod.h.
References ATVModSettings::m_inputFrequencyOffset, ATVMod::MsgConfigureATVMod::m_settings, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void ATVMod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 369 of file atvmod.h.
References ATVMod::MsgConfigureATVMod::m_settings, and ATVModSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool ATVMod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSource.
Definition at line 520 of file atvmod.cpp.
References applyChannelSettings(), applySettings(), UpChannelizer::configure(), ATVMod::MsgReportVideoFileSourceStreamTiming::create(), ATVMod::MsgReportCameraData::create(), ATVMod::MsgConfigureChannelizer::getCenterFrequency(), ATVMod::MsgConfigureImageFileName::getFileName(), ATVMod::MsgConfigureVideoFileName::getFileName(), ATVMod::MsgConfigureATVMod::getForce(), UpChannelizer::MsgChannelizerNotification::getFrequencyOffset(), ATVMod::MsgConfigureCameraIndex::getIndex(), ATVMod::MsgConfigureCameraData::getIndex(), BasebandSampleSource::getInputMessageQueue(), ATVMod::MsgConfigureCameraData::getManualFPS(), ATVMod::MsgConfigureCameraData::getManualFPSEnable(), BasebandSampleSource::getMessageQueueToGUI(), UpChannelizer::getOutputSampleRate(), ATVMod::MsgConfigureVideoFileSourceSeek::getPercentage(), UpChannelizer::MsgChannelizerNotification::getSampleRate(), ATVMod::MsgConfigureATVMod::getSettings(), m_cameraIndex, m_cameras, m_channelizer, m_video, m_videoFPS, m_videoHeight, m_videoOK, m_videoWidth, Message::match(), openImage(), openVideo(), MessageQueue::push(), and seekVideoFileStream().
Referenced by destroy().
 {
     if (UpChannelizer::MsgChannelizerNotification::match(cmd))
     {
         UpChannelizer::MsgChannelizerNotification& notif = (UpChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "ATVMod::handleMessage: MsgChannelizerNotification:"
                 << " outputSampleRate: " << notif.getSampleRate()
                 << " inputFrequencyOffset: " << notif.getFrequencyOffset();
         applyChannelSettings(notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "SSBMod::handleMessage: MsgConfigureChannelizer: sampleRate: " << m_channelizer->getOutputSampleRate()
                 << " centerFrequency: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
                 m_channelizer->getOutputSampleRate(),
                 cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureATVMod::match(cmd))
     {
         MsgConfigureATVMod& cfg = (MsgConfigureATVMod&) cmd;
         qDebug() << "ATVMod::handleMessage: MsgConfigureATVMod";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgConfigureImageFileName::match(cmd))
     {
         MsgConfigureImageFileName& conf = (MsgConfigureImageFileName&) cmd;
         openImage(conf.getFileName());
         return true;
     }
     else if (MsgConfigureVideoFileName::match(cmd))
     {
         MsgConfigureVideoFileName& conf = (MsgConfigureVideoFileName&) cmd;
         openVideo(conf.getFileName());
         return true;
     }
     else if (MsgConfigureVideoFileSourceSeek::match(cmd))
     {
         MsgConfigureVideoFileSourceSeek& conf = (MsgConfigureVideoFileSourceSeek&) cmd;
         int seekPercentage = conf.getPercentage();
         seekVideoFileStream(seekPercentage);
         return true;
     }
     else if (MsgConfigureVideoFileSourceStreamTiming::match(cmd))
     {
         int framesCount;
         if (m_videoOK && m_video.isOpened())
         {
             framesCount = m_video.get(CV_CAP_PROP_POS_FRAMES);;
         } else {
             framesCount = 0;
         }
         if (getMessageQueueToGUI())
         {
             MsgReportVideoFileSourceStreamTiming *report;
             report = MsgReportVideoFileSourceStreamTiming::create(framesCount);
             getMessageQueueToGUI()->push(report);
         }
         return true;
     }
     else if (MsgConfigureCameraIndex::match(cmd))
     {
         MsgConfigureCameraIndex& cfg = (MsgConfigureCameraIndex&) cmd;
         uint32_t index = cfg.getIndex() & 0x7FFFFFF;
         if (index < m_cameras.size())
         {
             m_cameraIndex = index;
             if (getMessageQueueToGUI())
             {
                 MsgReportCameraData *report;
                 report = MsgReportCameraData::create(
                         m_cameras[m_cameraIndex].m_cameraNumber,
                         m_cameras[m_cameraIndex].m_videoFPS,
                         m_cameras[m_cameraIndex].m_videoFPSManual,
                         m_cameras[m_cameraIndex].m_videoFPSManualEnable,
                         m_cameras[m_cameraIndex].m_videoWidth,
                         m_cameras[m_cameraIndex].m_videoHeight,
                         0);
                 getMessageQueueToGUI()->push(report);
             }
         }
         return true;
     }
     else if (MsgConfigureCameraData::match(cmd))
     {
         MsgConfigureCameraData& cfg = (MsgConfigureCameraData&) cmd;
         uint32_t index = cfg.getIndex() & 0x7FFFFFF;
         float mnaualFPS = cfg.getManualFPS();
         bool manualFPSEnable = cfg.getManualFPSEnable();
         if (index < m_cameras.size())
         {
             m_cameras[index].m_videoFPSManual = mnaualFPS;
             m_cameras[index].m_videoFPSManualEnable = manualFPSEnable;
         }
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         return false;
     }
 }
levelChanged
void ATVMod::levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples) signal
Level changed
Parameters
rmsLevel RMS level in range 0.0 - 1.0
peakLevel Peak level in range 0.0 - 1.0
numSamples Number of audio samples analyzed
Referenced by calculateLevel().
mixImageAndText()
void ATVMod::mixImageAndText (cv::Mat & image) private
Definition at line 1016 of file atvmod.cpp.
References ATVModSettings::m_overlayText, m_settings, and ATVModSettings::m_uniformLevel.
Referenced by applySettings(), openImage(), and pullVideo().
 {
     int fontFace = cv::FONT_HERSHEY_PLAIN;
     double fontScale = image.rows / 100.0;
     int thickness = image.cols / 160;
     int baseline=0;
     fontScale = fontScale < 4.0f ? 4.0f : fontScale; // minimum size
     cv::Size textSize = cv::getTextSize(m_settings.m_overlayText.toStdString(), fontFace, fontScale, thickness, &baseline);
     baseline += thickness;
     // position the text in the top left corner
     cv::Point textOrg(6, textSize.height+10);
     // then put the text itself
     cv::putText(image, m_settings.m_overlayText.toStdString(), textOrg, fontFace, fontScale, cv::Scalar::all(255*m_settings.m_uniformLevel), thickness, CV_AA);
 }
modulateSample()
void ATVMod::modulateSample () private
Definition at line 194 of file atvmod.cpp.
References ATVModSettings::ATVModulationAM, ATVModSettings::ATVModulationFM, ATVModSettings::ATVModulationLSB, ATVModSettings::ATVModulationUSB, ATVModSettings::ATVModulationVestigialLSB, ATVModSettings::ATVModulationVestigialUSB, calculateLevel(), cos(), ATVModSettings::m_atvModulation, ATVModSettings::m_fmExcursion, ATVModSettings::m_invertedVideo, m_modPhasor, m_modSample, M_PI, ATVModSettings::m_rfScalingFactor, m_settings, modulateSSB(), modulateVestigialSSB(), pullVideo(), and sin().
Referenced by pull().
 {
     Real t;
     pullVideo(t);
     calculateLevel(t);
     t = m_settings.m_invertedVideo ? 1.0f - t : t;
     switch (m_settings.m_atvModulation)
     {
     case ATVModSettings::ATVModulationFM: // FM half bandwidth deviation
         m_modPhasor += (t - 0.5f) * m_settings.m_fmExcursion * 2.0f * M_PI;
         if (m_modPhasor > 2.0f * M_PI) m_modPhasor -= 2.0f * M_PI; // limit growth
         if (m_modPhasor < 2.0f * M_PI) m_modPhasor += 2.0f * M_PI; // limit growth
         m_modSample.real(cos(m_modPhasor) * m_settings.m_rfScalingFactor); // -1 dB
         m_modSample.imag(sin(m_modPhasor) * m_settings.m_rfScalingFactor);
         break;
     case ATVModSettings::ATVModulationLSB:
     case ATVModSettings::ATVModulationUSB:
         m_modSample = modulateSSB(t);
         m_modSample *= m_settings.m_rfScalingFactor;
         break;
     case ATVModSettings::ATVModulationVestigialLSB:
     case ATVModSettings::ATVModulationVestigialUSB:
         m_modSample = modulateVestigialSSB(t);
         m_modSample *= m_settings.m_rfScalingFactor;
         break;
     case ATVModSettings::ATVModulationAM: // AM 90%
     default:
         m_modSample.real((t*1.8f + 0.1f) * (m_settings.m_rfScalingFactor/2.0f)); // modulate and scale zero frequency carrier
         m_modSample.imag(0.0f);
     }
 }
modulateSSB()
Complex & ATVMod::modulateSSB (Real & sample) private
Definition at line 229 of file atvmod.cpp.
References ATVModSettings::ATVModulationUSB, ATVModSettings::m_atvModulation, m_settings, m_SSBFilter, m_SSBFilterBuffer, m_SSBFilterBufferIndex, and fftfilt::runSSB().
Referenced by modulateSample().
 {
     int n_out;
     Complex ci(sample, 0.0f);
     fftfilt::cmplx *filtered;
     n_out = m_SSBFilter->runSSB(ci, &filtered, m_settings.m_atvModulation == ATVModSettings::ATVModulationUSB);
     if (n_out > 0)
     {
         memcpy((void *) m_SSBFilterBuffer, (const void *) filtered, n_out*sizeof(Complex));
         m_SSBFilterBufferIndex = 0;
     }
     m_SSBFilterBufferIndex++;
     return m_SSBFilterBuffer[m_SSBFilterBufferIndex-1];
 }
modulateVestigialSSB()
Complex & ATVMod::modulateVestigialSSB (Real & sample) private
Definition at line 248 of file atvmod.cpp.
References ATVModSettings::ATVModulationVestigialUSB, ATVModSettings::m_atvModulation, m_DSBFilter, m_DSBFilterBuffer, m_DSBFilterBufferIndex, m_settings, and fftfilt::runAsym().
Referenced by modulateSample().
 {
     int n_out;
     Complex ci(sample, 0.0f);
     fftfilt::cmplx *filtered;
     n_out = m_DSBFilter->runAsym(ci, &filtered, m_settings.m_atvModulation == ATVModSettings::ATVModulationVestigialUSB);
     if (n_out > 0)
     {
         memcpy((void *) m_DSBFilterBuffer, (const void *) filtered, n_out*sizeof(Complex));
         m_DSBFilterBufferIndex = 0;
     }
     m_DSBFilterBufferIndex++;
     return m_DSBFilterBuffer[m_DSBFilterBufferIndex-1];
 }
networkManagerFinished
void ATVMod::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 1597 of file atvmod.cpp.
Referenced by ATVMod(), and ~ATVMod().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "ATVMod::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("ATVMod::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openImage()
void ATVMod::openImage (const QString & fileName) private
Definition at line 808 of file atvmod.cpp.
References m_imageFileName, m_imageFromFile, m_imageOK, m_imageOriginal, m_settings, ATVModSettings::m_showOverlayText, mixImageAndText(), and resizeImage().
Referenced by handleMessage().
 {
     m_imageFromFile = cv::imread(qPrintable(fileName), CV_LOAD_IMAGE_GRAYSCALE);
     m_imageOK = m_imageFromFile.data != 0;
     if (m_imageOK)
     {
         m_imageFileName = fileName;
         m_imageFromFile.copyTo(m_imageOriginal);
         if (m_settings.m_showOverlayText) {
             mixImageAndText(m_imageOriginal);
         }
         resizeImage();
     }
     else
     {
         m_imageFileName.clear();
         qDebug("ATVMod::openImage: cannot open image file %s", qPrintable(fileName));
     }
 }
openVideo()
void ATVMod::openVideo (const QString & fileName) private
Definition at line 831 of file atvmod.cpp.
References calculateVideoSizes(), ATVMod::MsgReportVideoFileSourceStreamData::create(), BasebandSampleSource::getMessageQueueToGUI(), m_video, m_videoEOF, m_videoFileName, m_videoFPS, m_videoHeight, m_videoLength, m_videoOK, m_videoWidth, and MessageQueue::push().
Referenced by handleMessage().
 {
     //if (m_videoOK && m_video.isOpened()) m_video.release(); should be done by OpenCV in open method
     m_videoOK = m_video.open(qPrintable(fileName));
     if (m_videoOK)
     {
         m_videoFileName = fileName;
         m_videoFPS = m_video.get(CV_CAP_PROP_FPS);
         m_videoWidth = (int) m_video.get(CV_CAP_PROP_FRAME_WIDTH);
         m_videoHeight = (int) m_video.get(CV_CAP_PROP_FRAME_HEIGHT);
         m_videoLength = (int) m_video.get(CV_CAP_PROP_FRAME_COUNT);
         int ex = static_cast<int>(m_video.get(CV_CAP_PROP_FOURCC));
         char ext[] = {(char)(ex & 0XFF),(char)((ex & 0XFF00) >> 8),(char)((ex & 0XFF0000) >> 16),(char)((ex & 0XFF000000) >> 24),0};
         qDebug("ATVMod::openVideo: %s FPS: %f size: %d x %d #frames: %d codec: %s",
                 m_video.isOpened() ? "OK" : "KO",
                 m_videoFPS,
                 m_videoWidth,
                 m_videoHeight,
                 m_videoLength,
                 ext);
         calculateVideoSizes();
         m_videoEOF = false;
         if (getMessageQueueToGUI())
         {
             MsgReportVideoFileSourceStreamData *report;
             report = MsgReportVideoFileSourceStreamData::create(m_videoFPS, m_videoLength);
             getMessageQueueToGUI()->push(report);
         }
     }
     else
     {
         m_videoFileName.clear();
         qDebug("ATVMod::openVideo: cannot open video file %s", qPrintable(fileName));
     }
 }
pull()
void ATVMod::pull (Sample & sample) virtual
Implements BasebandSampleSource.
Definition at line 138 of file atvmod.cpp.
References Interpolator::decimate(), Interpolator::interpolate(), ATVModSettings::m_channelMute, ATVModSettings::m_forceDecimator, Sample::m_imag, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_modSample, m_outputSampleRate, Sample::m_real, m_settings, m_settingsMutex, m_tvSampleRate, modulateSample(), and pullFinalize().
Referenced by destroy().
 {
     if (m_settings.m_channelMute)
     {
         sample.m_real = 0.0f;
         sample.m_imag = 0.0f;
         return;
     }
     Complex ci;
     m_settingsMutex.lock();
     if ((m_tvSampleRate == m_outputSampleRate) && (!m_settings.m_forceDecimator)) // no interpolation nor decimation
     {
         modulateSample();
         pullFinalize(m_modSample, sample);
     }
     else
     {
         if (m_interpolatorDistance > 1.0f) // decimate
         {
             modulateSample();
             while (!m_interpolator.decimate(&m_interpolatorDistanceRemain, m_modSample, &ci))
             {
                 modulateSample();
             }
         }
         else
         {
             if (m_interpolator.interpolate(&m_interpolatorDistanceRemain, m_modSample, &ci))
             {
                 modulateSample();
             }
         }
         m_interpolatorDistanceRemain += m_interpolatorDistance;
         pullFinalize(ci, sample);
     }
 }
pullAudio()
void ATVMod::pullAudio (int nbSamples) virtual
Reimplemented from BasebandSampleSource.
Definition at line 133 of file atvmod.cpp.
Referenced by destroy().
 {
     (void) nbSamples;
 }
pullFinalize()
void ATVMod::pullFinalize (Complex & ci, Sample & sample) private
Definition at line 180 of file atvmod.cpp.
References m_carrierNco, Sample::m_imag, m_movingAverage, Sample::m_real, m_settingsMutex, NCO::nextIQ(), and SDR_TX_SCALED.
Referenced by pull().
 {
     ci *= m_carrierNco.nextIQ(); // shift to carrier frequency
     m_settingsMutex.unlock();
     double magsq = ci.real() * ci.real() + ci.imag() * ci.imag();
     magsq /= (SDR_TX_SCALED*SDR_TX_SCALED);
     m_movingAverage(magsq);
     sample.m_real = (FixReal) ci.real();
     sample.m_imag = (FixReal) ci.imag();
 }
pullImageLine()
void ATVMod::pullImageLine (Real & sample, bool noHSync = false) inline private
Definition at line 581 of file atvmod.h.
References ATVModSettings::ATVModInputCamera, ATVModSettings::ATVModInputChessboard, ATVModSettings::ATVModInputHBars, ATVModSettings::ATVModInputHGradient, ATVModSettings::ATVModInputImage, ATVModSettings::ATVModInputUniform, ATVModSettings::ATVModInputVBars, ATVModSettings::ATVModInputVGradient, ATVModSettings::ATVModInputVideo, ATVModSettings::m_atvModInput, m_blackLevel, m_cameraIndex, m_lineCount, m_linesPerVBar, m_nbImageLines2, m_nbSyncLinesHeadE, m_nbSyncLinesHeadO, m_pointsPerBP, m_pointsPerHBar, ATVModSettings::m_uniformLevel, and ATVMod::ATVCamera::m_videoFrame.
Referenced by pullVideo().
     {
         if (m_horizontalCount < m_pointsPerSync) // sync pulse
         {
             sample = noHSync ? m_blackLevel : 0.0f; // ultra-black
         }
         else if (m_horizontalCount < m_pointsPerSync + m_pointsPerBP) // back porch
         {
             sample = m_blackLevel; // black
         }
         else if (m_horizontalCount < m_pointsPerSync + m_pointsPerBP + m_pointsPerImgLine)
         {
             int pointIndex = m_horizontalCount - (m_pointsPerSync + m_pointsPerBP);
             int oddity = m_lineCount < m_nbLines2 + 1 ? 0 : 1;
             int iLine = oddity == 0 ? m_lineCount :  m_lineCount - m_nbLines2 - 1;
             int iLineImage = iLine - m_nbBlankLines - (oddity == 0 ? m_nbSyncLinesHeadE : m_nbSyncLinesHeadO);
             switch(m_settings.m_atvModInput)
             {
             case ATVModSettings::ATVModInputHBars:
                 sample = (((float)pointIndex) / m_pointsPerHBar) * m_hBarIncrement + m_blackLevel;
                 break;
             case ATVModSettings::ATVModInputVBars:
                 sample = (((float)iLine) / m_linesPerVBar) * m_vBarIncrement + m_blackLevel;
                 break;
             case ATVModSettings::ATVModInputChessboard:
                 sample = (((iLine / m_linesPerVBar)*5 + (pointIndex / m_pointsPerHBar)) % 2) * m_spanLevel * m_settings.m_uniformLevel + m_blackLevel;
                 break;
             case ATVModSettings::ATVModInputHGradient:
                 sample = (pointIndex / (float) m_pointsPerImgLine) * m_spanLevel + m_blackLevel;
                 break;
             case ATVModSettings::ATVModInputVGradient:
                 sample = ((iLine -5) / (float) m_nbImageLines2) * m_spanLevel + m_blackLevel;
                 break;
             case ATVModSettings::ATVModInputImage:
                 if (!m_imageOK || (iLineImage < -oddity) || m_image.empty())
                 {
                     sample = m_spanLevel * m_settings.m_uniformLevel + m_blackLevel;
                 }
                 else
                 {
                     unsigned char pixv;
                     if (m_interleaved) {
                         pixv = m_image.at<unsigned char>(2*iLineImage + oddity, pointIndex); // row (y), col (x)
                     } else {
                         pixv = m_image.at<unsigned char>(iLineImage, pointIndex); // row (y), col (x)
                     }
                     sample = (pixv / 256.0f) * m_spanLevel + m_blackLevel;
                 }
                 break;
             case ATVModSettings::ATVModInputVideo:
                 if (!m_videoOK || (iLineImage < -oddity) || m_videoFrame.empty())
                 {
                     sample = m_spanLevel * m_settings.m_uniformLevel + m_blackLevel;
                 }
                 else
                 {
                     unsigned char pixv;
                     if (m_interleaved) {
                         pixv = m_videoFrame.at<unsigned char>(2*iLineImage + oddity, pointIndex); // row (y), col (x)
                     } else {
                         pixv = m_videoFrame.at<unsigned char>(iLineImage, pointIndex); // row (y), col (x)
                     }
                     sample = (pixv / 256.0f) * m_spanLevel + m_blackLevel;
                 }
                 break;
             case ATVModSettings::ATVModInputCamera:
                 if ((iLineImage < -oddity) || (m_cameraIndex < 0))
                 {
                     sample = m_spanLevel * m_settings.m_uniformLevel + m_blackLevel;
                 }
                 else
                 {
                     ATVCamera& camera = m_cameras[m_cameraIndex];
                     if (camera.m_videoFrame.empty())
                     {
                         sample = m_spanLevel * m_settings.m_uniformLevel + m_blackLevel;
                     }
                     else
                     {
                         unsigned char pixv;
                         if (m_interleaved) {
                             pixv = camera.m_videoFrame.at<unsigned char>(2*iLineImage + oddity, pointIndex); // row (y), col (x)
                         } else {
                             pixv = camera.m_videoFrame.at<unsigned char>(iLineImage, pointIndex); // row (y), col (x)
                         }
                         sample = (pixv / 256.0f) * m_spanLevel + m_blackLevel;
                     }
                 }
                 break;
             case ATVModSettings::ATVModInputUniform:
             default:
                 sample = m_spanLevel * m_settings.m_uniformLevel + m_blackLevel;
             }
         }
         else // front porch
         {
             sample = m_blackLevel; // black
         }
     }
pullVideo()
void ATVMod::pullVideo (Real & sample) private
Definition at line 267 of file atvmod.cpp.
References ATVModSettings::ATVModInputCamera, ATVModSettings::ATVModInputVideo, ATVModSettings::ATVStdHSkip, ATVMod::MsgReportCameraData::create(), BasebandSampleSource::getMessageQueueToGUI(), i, ATVModSettings::m_atvModInput, ATVModSettings::m_atvStd, ATVMod::ATVCamera::m_camera, m_cameraFPSTestNbFrames, m_cameraIndex, ATVMod::ATVCamera::m_cameraNumber, ATVModSettings::m_cameraPlay, m_cameras, m_evenImage, m_fps, m_horizontalCount, m_lineCount, m_nbBlankLines, m_nbHorizPoints, m_nbLines, m_nbLines2, m_nbSyncLinesBottom, m_nbSyncLinesHeadE, m_nbSyncLinesHeadO, m_settings, ATVModSettings::m_showOverlayText, m_video, m_videoEOF, ATVMod::ATVCamera::m_videoFPS, m_videoFPS, ATVMod::ATVCamera::m_videoFPSCount, m_videoFPSCount, ATVMod::ATVCamera::m_videoFPSManual, ATVMod::ATVCamera::m_videoFPSManualEnable, ATVMod::ATVCamera::m_videoFPSq, m_videoFPSq, ATVMod::ATVCamera::m_videoFPSqManual, ATVMod::ATVCamera::m_videoframeOriginal, m_videoframeOriginal, ATVMod::ATVCamera::m_videoHeight, m_videoOK, ATVModSettings::m_videoPlay, ATVModSettings::m_videoPlayLoop, ATVMod::ATVCamera::m_videoPrevFPSCount, m_videoPrevFPSCount, ATVMod::ATVCamera::m_videoWidth, mixImageAndText(), pullImageLine(), pullVSyncLine(), MessageQueue::push(), resizeCamera(), resizeVideo(), seekVideoFileStream(), and start().
Referenced by modulateSample().
 {
     if ((m_settings.m_atvStd == ATVModSettings::ATVStdHSkip) && (m_lineCount == m_nbLines2)) // last line in skip mode
     {
         pullImageLine(sample, true); // pull image line without sync
     }
     else if (m_lineCount < m_nbLines2 + 1) // even image or non interlaced
     {
         int iLine = m_lineCount;
         if (iLine < m_nbSyncLinesHeadE + m_nbBlankLines)
         {
             pullVSyncLine(sample);
         }
         else if (iLine > m_nbLines2 - m_nbSyncLinesBottom)
         {
             pullVSyncLine(sample);
         }
         else
         {
             pullImageLine(sample);
         }
     }
     else // odd image
     {
         int iLine = m_lineCount - m_nbLines2 - 1;
         if (iLine < m_nbSyncLinesHeadO + m_nbBlankLines)
         {
             pullVSyncLine(sample);
         }
         else if (iLine > m_nbLines2 - 1 - m_nbSyncLinesBottom)
         {
             pullVSyncLine(sample);
         }
         else
         {
             pullImageLine(sample);
         }
     }
     if (m_horizontalCount < m_nbHorizPoints - 1)
     {
         m_horizontalCount++;
     }
     else
     {
         if (m_lineCount < m_nbLines - 1)
         {
             m_lineCount++;
             if (m_lineCount > (m_nbLines/2)) m_evenImage = !m_evenImage;
         }
         else // new image
         {
             m_lineCount = 0;
             m_evenImage = !m_evenImage;
             if ((m_settings.m_atvModInput == ATVModSettings::ATVModInputVideo) && m_videoOK && (m_settings.m_videoPlay) && !m_videoEOF)
             {
                 int grabOK = 0;
                 int fpsIncrement = (int) m_videoFPSCount - m_videoPrevFPSCount;
                 // move a number of frames according to increment
                 // use grab to test for EOF then retrieve to preserve last valid frame as the current original frame
                 // TODO: handle pause (no move)
                 for (int i = 0; i < fpsIncrement; i++)
                 {
                     grabOK = m_video.grab();
                     if (!grabOK) break;
                 }
                 if (grabOK)
                 {
                     cv::Mat colorFrame;
                     m_video.retrieve(colorFrame);
                     if (!colorFrame.empty()) // some frames may not come out properly
                     {
                         if (m_settings.m_showOverlayText) {
                             mixImageAndText(colorFrame);
                         }
                         cv::cvtColor(colorFrame, m_videoframeOriginal, CV_BGR2GRAY);
                         resizeVideo();
                     }
                 }
                 else
                 {
                     if (m_settings.m_videoPlayLoop) { // play loop
                         seekVideoFileStream(0);
                     } else { // stops
                         m_videoEOF = true;
                     }
                 }
                 if (m_videoFPSCount < m_videoFPS)
                 {
                     m_videoPrevFPSCount = (int) m_videoFPSCount;
                     m_videoFPSCount += m_videoFPSq;
                 }
                 else
                 {
                     m_videoPrevFPSCount = 0;
                     m_videoFPSCount = m_videoFPSq;
                 }
             }
             else if ((m_settings.m_atvModInput == ATVModSettings::ATVModInputCamera) && (m_settings.m_cameraPlay))
             {
                 ATVCamera& camera = m_cameras[m_cameraIndex]; // currently selected canera
                 if (camera.m_videoFPS < 0.0f) // default frame rate when it could not be obtained via get
                 {
                     time_t start, end;
                     cv::Mat frame;
                     if (getMessageQueueToGUI())
                     {
                         MsgReportCameraData *report;
                         report = MsgReportCameraData::create(
                                 camera.m_cameraNumber,
                                 0.0f,
                                 camera.m_videoFPSManual,
                                 camera.m_videoFPSManualEnable,
                                 camera.m_videoWidth,
                                 camera.m_videoHeight,
                                 1); // open splash screen on GUI side
                         getMessageQueueToGUI()->push(report);
                     }
                     int nbFrames = 0;
                     time(&start);
                     for (int i = 0; i < m_cameraFPSTestNbFrames; i++)
                     {
                         camera.m_camera >> frame;
                         if (!frame.empty()) nbFrames++;
                     }
                     time(&end);
                     double seconds = difftime (end, start);
                     // take a 10% guard and divide bandwidth between all cameras as a hideous hack
                     camera.m_videoFPS = ((nbFrames / seconds) * 0.9) / m_cameras.size();
                     camera.m_videoFPSq = camera.m_videoFPS / m_fps;
                     camera.m_videoFPSCount = camera.m_videoFPSq;
                     camera.m_videoPrevFPSCount = 0;
                     if (getMessageQueueToGUI())
                     {
                         MsgReportCameraData *report;
                         report = MsgReportCameraData::create(
                                 camera.m_cameraNumber,
                                 camera.m_videoFPS,
                                 camera.m_videoFPSManual,
                                 camera.m_videoFPSManualEnable,
                                 camera.m_videoWidth,
                                 camera.m_videoHeight,
                                 2); // close splash screen on GUI side
                         getMessageQueueToGUI()->push(report);
                     }
                 }
                 else if (camera.m_videoFPS == 0.0f) // Hideous hack for windows
                 {
                     camera.m_videoFPS = 5.0f;
                     camera.m_videoFPSq = camera.m_videoFPS / m_fps;
                     camera.m_videoFPSCount = camera.m_videoFPSq;
                     camera.m_videoPrevFPSCount = 0;
                     if (getMessageQueueToGUI())
                     {
                         MsgReportCameraData *report;
                         report = MsgReportCameraData::create(
                                 camera.m_cameraNumber,
                                 camera.m_videoFPS,
                                 camera.m_videoFPSManual,
                                 camera.m_videoFPSManualEnable,
                                 camera.m_videoWidth,
                                 camera.m_videoHeight,
                                 0);
                         getMessageQueueToGUI()->push(report);
                     }
                 }
                 int fpsIncrement = (int) camera.m_videoFPSCount - camera.m_videoPrevFPSCount;
                 // move a number of frames according to increment
                 // use grab to test for EOF then retrieve to preserve last valid frame as the current original frame
                 cv::Mat colorFrame;
                 for (int i = 0; i < fpsIncrement; i++)
                 {
                     camera.m_camera >> colorFrame;
                     if (colorFrame.empty()) break;
                 }
                 if (!colorFrame.empty()) // some frames may not come out properly
                 {
                     if (m_settings.m_showOverlayText) {
                         mixImageAndText(colorFrame);
                     }
                     cv::cvtColor(colorFrame, camera.m_videoframeOriginal, CV_BGR2GRAY);
                     resizeCamera();
                 }
                 if (camera.m_videoFPSCount < (camera.m_videoFPSManualEnable ? camera.m_videoFPSManual : camera.m_videoFPS))
                 {
                     camera.m_videoPrevFPSCount = (int) camera.m_videoFPSCount;
                     camera.m_videoFPSCount += (camera.m_videoFPSManualEnable ? camera.m_videoFPSqManual : camera.m_videoFPSq);
                 }
                 else
                 {
                     camera.m_videoPrevFPSCount = 0;
                     camera.m_videoFPSCount = (camera.m_videoFPSManualEnable ? camera.m_videoFPSqManual : camera.m_videoFPSq);
                 }
             }
         }
         m_horizontalCount = 0;
     }
 }
pullVSyncLine()
void ATVMod::pullVSyncLine (Real & sample) inline private
Definition at line 767 of file atvmod.h.
References m_blankLineLvel, m_lineCount, pullVSyncLineEqualizingPulses(), pullVSyncLineEqualizingThenLongPulses(), pullVSyncLineLongPulses(), and pullVSyncLineLongThenEqualizingPulses().
Referenced by pullVideo().
     {
         if (m_lineCount < m_nbLines2 + 1) // even
         {
             int fieldLine = m_lineCount;
             if (fieldLine < m_nbLongSyncLines) // 0,1: Whole line "long" pulses
             {
                 pullVSyncLineLongPulses(sample);
             }
             else if (fieldLine < m_nbLongSyncLines + m_nbHalfLongSync) // long pulse then equalizing pulse
             {
                 pullVSyncLineLongThenEqualizingPulses(sample);
             }
             else if (fieldLine < m_nbLongSyncLines + m_nbHalfLongSync + m_nbWholeEqLines) // Whole line equalizing pulses
             {
                 pullVSyncLineEqualizingPulses(sample);
             }
             else if (fieldLine > m_nbLines2 - m_nbHalfLongSync) // equalizing pulse then long pulse
             {
                 pullVSyncLineEqualizingThenLongPulses(sample);
             }
             else if (fieldLine > m_nbLines2 - m_nbHalfLongSync - m_nbWholeEqLines) // Whole line equalizing pulses
             {
                 pullVSyncLineEqualizingPulses(sample);
             }
             else // black images
             {
                 if (m_horizontalCount < m_pointsPerSync)
                 {
                     sample = 0.0f;
                 }
                 else
                 {
                     sample = m_blankLineLvel;
                 }
             }
         }
         else // odd
         {
             int fieldLine = m_lineCount - m_nbLines2 - 1;
             if (fieldLine < m_nbLongSyncLines) // 0,1: Whole line "long" pulses
             {
                 pullVSyncLineLongPulses(sample);
             }
             else if (fieldLine < m_nbLongSyncLines + m_nbWholeEqLines) // Whole line equalizing pulses
             {
                 pullVSyncLineEqualizingPulses(sample);
             }
             else if (fieldLine > m_nbLines2 - 1 - m_nbWholeEqLines - m_nbHalfLongSync) // Whole line equalizing pulses
             {
                 pullVSyncLineEqualizingPulses(sample);
             }
             else // black images
             {
                 if (m_horizontalCount < m_pointsPerSync)
                 {
                     sample = 0.0f;
                 }
                 else
                 {
                     sample = m_blankLineLvel;
                 }
             }
         }
     }
pullVSyncLineEqualizingPulses()
void ATVMod::pullVSyncLineEqualizingPulses (Real & sample) inline private
Definition at line 707 of file atvmod.h.
References m_blackLevel.
Referenced by pullVSyncLine().
     {
         if (m_horizontalCount < m_pointsPerSync)
         {
             sample = 0.0f; // ultra-black
         }
         else if (m_horizontalCount < (m_nbHorizPoints/2))
         {
             sample = m_blackLevel; // black
         }
         else if (m_horizontalCount < (m_nbHorizPoints/2) + m_pointsPerFSync)
         {
             sample = 0.0f; // ultra-black
         }
         else
         {
             sample = m_blackLevel; // black
         }
     }
pullVSyncLineEqualizingThenLongPulses()
void ATVMod::pullVSyncLineEqualizingThenLongPulses (Real & sample) inline private
Definition at line 727 of file atvmod.h.
References m_blackLevel.
Referenced by pullVSyncLine().
     {
         if (m_horizontalCount < m_pointsPerSync)
         {
             sample = 0.0f; // ultra-black
         }
         else if (m_horizontalCount < (m_nbHorizPoints/2))
         {
             sample = m_blackLevel; // black
         }
         else if (m_horizontalCount < m_nbHorizPoints - m_pointsPerSync)
         {
             sample = 0.0f; // ultra-black
         }
         else
         {
             sample = m_blackLevel; // black
         }
     }
pullVSyncLineLongPulses()
void ATVMod::pullVSyncLineLongPulses (Real & sample) inline private
Definition at line 689 of file atvmod.h.
References m_blackLevel, and m_pointsPerSync.
Referenced by pullVSyncLine().
     {
         int halfIndex = m_horizontalCount % (m_nbHorizPoints/2);
         if (halfIndex < (m_nbHorizPoints/2) - m_pointsPerSync) // ultra-black
         {
             sample = 0.0f;
         }
         else // black
         {
             if (m_singleLongSync && (m_horizontalCount < m_nbHorizPoints/2)) {
                 sample = 0.0f;
             } else {
                 sample = m_blackLevel;
             }
         }
     }
pullVSyncLineLongThenEqualizingPulses()
void ATVMod::pullVSyncLineLongThenEqualizingPulses (Real & sample) inline private
Definition at line 747 of file atvmod.h.
References m_blackLevel.
Referenced by pullVSyncLine().
     {
         if (m_horizontalCount < (m_nbHorizPoints/2) - m_pointsPerSync)
         {
             sample = 0.0f; // ultra-black
         }
         else if (m_horizontalCount < (m_nbHorizPoints/2))
         {
             sample = m_blackLevel; // black
         }
         else if (m_horizontalCount < (m_nbHorizPoints/2) + m_pointsPerFSync)
         {
             sample = 0.0f; // ultra-black
         }
         else
         {
             sample = m_blackLevel; // black
         }
     }
releaseCameras()
void ATVMod::releaseCameras () private
Definition at line 982 of file atvmod.cpp.
References m_cameras.
Referenced by ~ATVMod().
 {
     for (std::vector<ATVCamera>::iterator it = m_cameras.begin(); it != m_cameras.end(); ++it)
     {
         if (it->m_camera.isOpened()) it->m_camera.release();
     }
 }
resizeCamera()
void ATVMod::resizeCamera () private
Definition at line 923 of file atvmod.cpp.
References m_cameraIndex, m_cameras, ATVMod::ATVCamera::m_videoFrame, ATVMod::ATVCamera::m_videoframeOriginal, ATVMod::ATVCamera::m_videoFx, and ATVMod::ATVCamera::m_videoFy.
Referenced by pullVideo().
 {
     ATVCamera& camera = m_cameras[m_cameraIndex];
     if (!camera.m_videoframeOriginal.empty()) {
         cv::resize(camera.m_videoframeOriginal, camera.m_videoFrame, cv::Size(), camera.m_videoFx, camera.m_videoFy); // resize current frame
     }
 }
resizeCameras()
void ATVMod::resizeCameras () private
Definition at line 913 of file atvmod.cpp.
References m_cameras.
 {
     for (std::vector<ATVCamera>::iterator it = m_cameras.begin(); it != m_cameras.end(); ++it)
     {
         if (!it->m_videoframeOriginal.empty()) {
             cv::resize(it->m_videoframeOriginal, it->m_videoFrame, cv::Size(), it->m_videoFx, it->m_videoFy); // resize current frame
         }
     }
 }
resizeImage()
void ATVMod::resizeImage () private
Definition at line 872 of file atvmod.cpp.
References m_image, m_imageOriginal, m_nbBlankLines, m_nbImageLines, and m_pointsPerImgLine.
Referenced by applySettings(), applyStandard(), and openImage().
 {
     float fy = (m_nbImageLines - 2*m_nbBlankLines) / (float) m_imageOriginal.rows;
     float fx = m_pointsPerImgLine / (float) m_imageOriginal.cols;
     cv::resize(m_imageOriginal, m_image, cv::Size(), fx, fy);
     qDebug("ATVMod::resizeImage: %d x %d -> %d x %d", m_imageOriginal.cols, m_imageOriginal.rows, m_image.cols, m_image.rows);
 }
resizeVideo()
void ATVMod::resizeVideo () private
Definition at line 891 of file atvmod.cpp.
References m_videoFrame, m_videoframeOriginal, m_videoFx, and m_videoFy.
Referenced by applyStandard(), and pullVideo().
 {
     if (!m_videoframeOriginal.empty()) {
         cv::resize(m_videoframeOriginal, m_videoFrame, cv::Size(), m_videoFx, m_videoFy); // resize current frame
     }
 }
scanCameras()
void ATVMod::scanCameras () private
Definition at line 946 of file atvmod.cpp.
References calculateCamerasSizes(), i, m_cameraIndex, and m_cameras.
Referenced by ATVMod().
 {
     for (int i = 0; i < 4; i++)
     {
         ATVCamera newCamera;
         m_cameras.push_back(newCamera);
         m_cameras.back().m_cameraNumber = i;
         m_cameras.back().m_camera.open(i);
         if (m_cameras.back().m_camera.isOpened())
         {
             m_cameras.back().m_videoFPS = m_cameras.back().m_camera.get(CV_CAP_PROP_FPS);
             m_cameras.back().m_videoWidth = (int) m_cameras.back().m_camera.get(CV_CAP_PROP_FRAME_WIDTH);
             m_cameras.back().m_videoHeight = (int) m_cameras.back().m_camera.get(CV_CAP_PROP_FRAME_HEIGHT);
             //m_cameras.back().m_videoFPS = m_cameras.back().m_videoFPS < 0 ? 16.3f : m_cameras.back().m_videoFPS;
             qDebug("ATVMod::scanCameras: [%d] FPS: %f %dx%d",
                     i,
                     m_cameras.back().m_videoFPS,
                     m_cameras.back().m_videoWidth ,
                     m_cameras.back().m_videoHeight);
         }
         else
         {
             m_cameras.pop_back();
         }
     }
     if (m_cameras.size() > 0)
     {
         calculateCamerasSizes();
         m_cameraIndex = 0;
     }
 }
seekVideoFileStream()
void ATVMod::seekVideoFileStream (int seekPercentage) private
Definition at line 932 of file atvmod.cpp.
References m_settingsMutex, m_video, m_videoEOF, m_videoFPSCount, m_videoFPSq, m_videoLength, m_videoOK, and m_videoPrevFPSCount.
Referenced by handleMessage(), and pullVideo().
 {
     QMutexLocker mutexLocker(&m_settingsMutex);
     if ((m_videoOK) && m_video.isOpened())
     {
         int seekPoint = ((m_videoLength * seekPercentage) / 100);
         m_video.set(CV_CAP_PROP_POS_FRAMES, seekPoint);
         m_videoFPSCount = m_videoFPSq;
         m_videoPrevFPSCount = 0;
         m_videoEOF = false;
     }
 }
serialize()
QByteArray ATVMod::serialize () const virtual
Implements ChannelAPI.
Definition at line 1253 of file atvmod.cpp.
References m_settings, and ATVModSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
start()
void ATVMod::start () virtual
Implements BasebandSampleSource.
Definition at line 509 of file atvmod.cpp.
References applyChannelSettings(), ATVModSettings::m_inputFrequencyOffset, m_inputFrequencyOffset, m_outputSampleRate, and m_settings.
Referenced by destroy(), and pullVideo().
 {
     qDebug() << "ATVMod::start: m_outputSampleRate: " << m_outputSampleRate
             << " m_inputFrequencyOffset: " << m_settings.m_inputFrequencyOffset;
     applyChannelSettings(m_outputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void ATVMod::stop () virtual
Implements BasebandSampleSource.
Definition at line 516 of file atvmod.cpp.
Referenced by destroy().
 {
 }
webapiFormatChannelReport()
void ATVMod::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 1496 of file atvmod.cpp.
References CalcDb::dbPower(), SWGSDRangel::SWGChannelReport::getAtvModReport(), getMagSq(), m_outputSampleRate, SWGSDRangel::SWGATVModReport::setChannelPowerDb(), and SWGSDRangel::SWGATVModReport::setChannelSampleRate().
Referenced by webapiReportGet().
 {
     response.getAtvModReport()->setChannelPowerDb(CalcDb::dbPower(getMagSq()));
     response.getAtvModReport()->setChannelSampleRate(m_outputSampleRate);
 }
webapiFormatChannelSettings()
void ATVMod::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const ATVModSettings & settings) private
Definition at line 1436 of file atvmod.cpp.
References SWGSDRangel::SWGChannelSettings::getAtvModSettings(), SWGSDRangel::SWGATVModSettings::getImageFileName(), SWGSDRangel::SWGATVModSettings::getOverlayText(), SWGSDRangel::SWGATVModSettings::getReverseApiAddress(), SWGSDRangel::SWGATVModSettings::getTitle(), SWGSDRangel::SWGATVModSettings::getVideoFileName(), ATVModSettings::m_atvModInput, ATVModSettings::m_atvModulation, ATVModSettings::m_atvStd, ATVModSettings::m_cameraPlay, ATVModSettings::m_channelMute, ATVModSettings::m_fmExcursion, ATVModSettings::m_forceDecimator, ATVModSettings::m_fps, m_imageFileName, ATVModSettings::m_inputFrequencyOffset, ATVModSettings::m_invertedVideo, ATVModSettings::m_nbLines, ATVModSettings::m_overlayText, ATVModSettings::m_reverseAPIAddress, ATVModSettings::m_reverseAPIChannelIndex, ATVModSettings::m_reverseAPIDeviceIndex, ATVModSettings::m_reverseAPIPort, ATVModSettings::m_rfBandwidth, ATVModSettings::m_rfOppBandwidth, ATVModSettings::m_rfScalingFactor, ATVModSettings::m_rgbColor, ATVModSettings::m_showOverlayText, ATVModSettings::m_title, ATVModSettings::m_uniformLevel, ATVModSettings::m_useReverseAPI, m_videoFileName, ATVModSettings::m_videoPlay, ATVModSettings::m_videoPlayLoop, SWGSDRangel::SWGATVModSettings::setAtvModInput(), SWGSDRangel::SWGATVModSettings::setAtvModulation(), SWGSDRangel::SWGATVModSettings::setAtvStd(), SWGSDRangel::SWGATVModSettings::setCameraPlay(), SWGSDRangel::SWGATVModSettings::setChannelMute(), SWGSDRangel::SWGATVModSettings::setFmExcursion(), SWGSDRangel::SWGATVModSettings::setForceDecimator(), SWGSDRangel::SWGATVModSettings::setFps(), SWGSDRangel::SWGATVModSettings::setImageFileName(), SWGSDRangel::SWGATVModSettings::setInputFrequencyOffset(), SWGSDRangel::SWGATVModSettings::setInvertedVideo(), SWGSDRangel::SWGATVModSettings::setNbLines(), SWGSDRangel::SWGATVModSettings::setOverlayText(), SWGSDRangel::SWGATVModSettings::setReverseApiAddress(), SWGSDRangel::SWGATVModSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGATVModSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGATVModSettings::setReverseApiPort(), SWGSDRangel::SWGATVModSettings::setRfBandwidth(), SWGSDRangel::SWGATVModSettings::setRfOppBandwidth(), SWGSDRangel::SWGATVModSettings::setRfScalingFactor(), SWGSDRangel::SWGATVModSettings::setRgbColor(), SWGSDRangel::SWGATVModSettings::setShowOverlayText(), SWGSDRangel::SWGATVModSettings::setTitle(), SWGSDRangel::SWGATVModSettings::setUniformLevel(), SWGSDRangel::SWGATVModSettings::setUseReverseApi(), SWGSDRangel::SWGATVModSettings::setVideoFileName(), SWGSDRangel::SWGATVModSettings::setVideoPlay(), and SWGSDRangel::SWGATVModSettings::setVideoPlayLoop().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getAtvModSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getAtvModSettings()->setRfBandwidth(settings.m_rfBandwidth);
     response.getAtvModSettings()->setRfOppBandwidth(settings.m_rfOppBandwidth);
     response.getAtvModSettings()->setAtvStd(settings.m_atvStd);
     response.getAtvModSettings()->setNbLines(settings.m_nbLines);
     response.getAtvModSettings()->setFps(settings.m_fps);
     response.getAtvModSettings()->setAtvModInput(settings.m_atvModInput);
     response.getAtvModSettings()->setUniformLevel(settings.m_uniformLevel);
     response.getAtvModSettings()->setAtvModulation(settings.m_atvModulation);
     response.getAtvModSettings()->setVideoPlayLoop(settings.m_videoPlayLoop ? 1 : 0);
     response.getAtvModSettings()->setVideoPlay(settings.m_videoPlay ? 1 : 0);
     response.getAtvModSettings()->setCameraPlay(settings.m_cameraPlay ? 1 : 0);
     response.getAtvModSettings()->setChannelMute(settings.m_channelMute ? 1 : 0);
     response.getAtvModSettings()->setInvertedVideo(settings.m_invertedVideo ? 1 : 0);
     response.getAtvModSettings()->setRfScalingFactor(settings.m_rfScalingFactor);
     response.getAtvModSettings()->setFmExcursion(settings.m_fmExcursion);
     response.getAtvModSettings()->setForceDecimator(settings.m_forceDecimator ? 1 : 0);
     response.getAtvModSettings()->setShowOverlayText(settings.m_showOverlayText ? 1 : 0);
     if (response.getAtvModSettings()->getOverlayText()) {
         *response.getAtvModSettings()->getOverlayText() = settings.m_overlayText;
     } else {
         response.getAtvModSettings()->setOverlayText(new QString(settings.m_overlayText));
     }
     response.getAtvModSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getAtvModSettings()->getTitle()) {
         *response.getAtvModSettings()->getTitle() = settings.m_title;
     } else {
         response.getAtvModSettings()->setTitle(new QString(settings.m_title));
     }
     if (response.getAtvModSettings()->getImageFileName()) {
         *response.getAtvModSettings()->getImageFileName() = m_imageFileName;
     } else {
         response.getAtvModSettings()->setImageFileName(new QString(m_imageFileName));
     }
     if (response.getAtvModSettings()->getVideoFileName()) {
         *response.getAtvModSettings()->getVideoFileName() = m_videoFileName;
     } else {
         response.getAtvModSettings()->setVideoFileName(new QString(m_videoFileName));
     }
     response.getAtvModSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getAtvModSettings()->getReverseApiAddress()) {
         *response.getAtvModSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getAtvModSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getAtvModSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getAtvModSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getAtvModSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int ATVMod::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 1425 of file atvmod.cpp.
References SWGSDRangel::SWGChannelReport::getAtvModReport(), SWGSDRangel::SWGATVModReport::init(), SWGSDRangel::SWGChannelReport::setAtvModReport(), and webapiFormatChannelReport().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setAtvModReport(new SWGSDRangel::SWGATVModReport());
     response.getAtvModReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendSettings()
void ATVMod::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const ATVModSettings & settings, bool force) private
Definition at line 1502 of file atvmod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), SWGSDRangel::SWGChannelSettings::getAtvModSettings(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), ATVModSettings::m_atvModInput, ATVModSettings::m_atvModulation, ATVModSettings::m_atvStd, ATVModSettings::m_cameraPlay, ATVModSettings::m_channelMute, ATVModSettings::m_fmExcursion, ATVModSettings::m_forceDecimator, ATVModSettings::m_fps, ATVModSettings::m_inputFrequencyOffset, ATVModSettings::m_invertedVideo, ATVModSettings::m_nbLines, m_networkManager, m_networkRequest, ATVModSettings::m_overlayText, ATVModSettings::m_reverseAPIAddress, ATVModSettings::m_reverseAPIChannelIndex, ATVModSettings::m_reverseAPIDeviceIndex, ATVModSettings::m_reverseAPIPort, ATVModSettings::m_rfBandwidth, ATVModSettings::m_rfOppBandwidth, ATVModSettings::m_rfScalingFactor, ATVModSettings::m_rgbColor, ATVModSettings::m_showOverlayText, ATVModSettings::m_title, ATVModSettings::m_uniformLevel, ATVModSettings::m_videoPlay, ATVModSettings::m_videoPlayLoop, SWGSDRangel::SWGATVModSettings::setAtvModInput(), SWGSDRangel::SWGChannelSettings::setAtvModSettings(), SWGSDRangel::SWGATVModSettings::setAtvModulation(), SWGSDRangel::SWGATVModSettings::setAtvStd(), SWGSDRangel::SWGATVModSettings::setCameraPlay(), SWGSDRangel::SWGATVModSettings::setChannelMute(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGATVModSettings::setFmExcursion(), SWGSDRangel::SWGATVModSettings::setForceDecimator(), SWGSDRangel::SWGATVModSettings::setFps(), SWGSDRangel::SWGATVModSettings::setInputFrequencyOffset(), SWGSDRangel::SWGATVModSettings::setInvertedVideo(), SWGSDRangel::SWGATVModSettings::setNbLines(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGATVModSettings::setOverlayText(), SWGSDRangel::SWGATVModSettings::setRfBandwidth(), SWGSDRangel::SWGATVModSettings::setRfOppBandwidth(), SWGSDRangel::SWGATVModSettings::setRfScalingFactor(), SWGSDRangel::SWGATVModSettings::setRgbColor(), SWGSDRangel::SWGATVModSettings::setShowOverlayText(), SWGSDRangel::SWGATVModSettings::setTitle(), SWGSDRangel::SWGATVModSettings::setUniformLevel(), SWGSDRangel::SWGATVModSettings::setVideoPlay(), and SWGSDRangel::SWGATVModSettings::setVideoPlayLoop().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("ATVMod"));
     swgChannelSettings->setAtvModSettings(new SWGSDRangel::SWGATVModSettings());
     SWGSDRangel::SWGATVModSettings *swgATVModSettings = swgChannelSettings->getAtvModSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgATVModSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("rfBandwidth") || force) {
         swgATVModSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (channelSettingsKeys.contains("rfOppBandwidth") || force) {
         swgATVModSettings->setRfOppBandwidth(settings.m_rfOppBandwidth);
     }
     if (channelSettingsKeys.contains("atvStd") || force) {
         swgATVModSettings->setAtvStd((int) settings.m_atvStd);
     }
     if (channelSettingsKeys.contains("nbLines") || force) {
         swgATVModSettings->setNbLines(settings.m_nbLines);
     }
     if (channelSettingsKeys.contains("fps") || force) {
         swgATVModSettings->setFps(settings.m_fps);
     }
     if (channelSettingsKeys.contains("atvModInput") || force) {
         swgATVModSettings->setAtvModInput((int) settings.m_atvModInput);
     }
     if (channelSettingsKeys.contains("uniformLevel") || force) {
         swgATVModSettings->setUniformLevel(settings.m_uniformLevel);
     }
     if (channelSettingsKeys.contains("atvModulation") || force) {
         swgATVModSettings->setAtvModulation((int) settings.m_atvModulation);
     }
     if (channelSettingsKeys.contains("videoPlayLoop") || force) {
         swgATVModSettings->setVideoPlayLoop(settings.m_videoPlayLoop ? 1 : 0);
     }
     if (channelSettingsKeys.contains("videoPlay") || force) {
         swgATVModSettings->setVideoPlay(settings.m_videoPlay ? 1 : 0);
     }
     if (channelSettingsKeys.contains("cameraPlay") || force) {
         swgATVModSettings->setCameraPlay(settings.m_cameraPlay ? 1 : 0);
     }
     if (channelSettingsKeys.contains("channelMute") || force) {
         swgATVModSettings->setChannelMute(settings.m_channelMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("invertedVideo") || force) {
         swgATVModSettings->setInvertedVideo(settings.m_invertedVideo ? 1 : 0);
     }
     if (channelSettingsKeys.contains("rfScalingFactor") || force) {
         swgATVModSettings->setRfScalingFactor(settings.m_rfScalingFactor);
     }
     if (channelSettingsKeys.contains("fmExcursion") || force) {
         swgATVModSettings->setFmExcursion(settings.m_fmExcursion);
     }
     if (channelSettingsKeys.contains("forceDecimator") || force) {
         swgATVModSettings->setForceDecimator(settings.m_forceDecimator ? 1 : 0);
     }
     if (channelSettingsKeys.contains("showOverlayText") || force) {
         swgATVModSettings->setShowOverlayText(settings.m_showOverlayText ? 1 : 0);
     }
     if (channelSettingsKeys.contains("overlayText") || force) {
         swgATVModSettings->setOverlayText(new QString(settings.m_overlayText));
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgATVModSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgATVModSettings->setTitle(new QString(settings.m_title));
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int ATVMod::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 1275 of file atvmod.cpp.
References SWGSDRangel::SWGChannelSettings::getAtvModSettings(), SWGSDRangel::SWGATVModSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setAtvModSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setAtvModSettings(new SWGSDRangel::SWGATVModSettings());
     response.getAtvModSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int ATVMod::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 1286 of file atvmod.cpp.
References ATVMod::MsgConfigureATVMod::create(), ATVMod::MsgConfigureChannelizer::create(), ATVMod::MsgConfigureImageFileName::create(), ATVMod::MsgConfigureVideoFileName::create(), SWGSDRangel::SWGATVModSettings::getAtvModInput(), SWGSDRangel::SWGChannelSettings::getAtvModSettings(), SWGSDRangel::SWGATVModSettings::getAtvModulation(), SWGSDRangel::SWGATVModSettings::getAtvStd(), SWGSDRangel::SWGATVModSettings::getCameraPlay(), SWGSDRangel::SWGATVModSettings::getChannelMute(), SWGSDRangel::SWGATVModSettings::getFmExcursion(), SWGSDRangel::SWGATVModSettings::getForceDecimator(), SWGSDRangel::SWGATVModSettings::getFps(), SWGSDRangel::SWGATVModSettings::getImageFileName(), SWGSDRangel::SWGATVModSettings::getInputFrequencyOffset(), SWGSDRangel::SWGATVModSettings::getInvertedVideo(), SWGSDRangel::SWGATVModSettings::getNbLines(), SWGSDRangel::SWGATVModSettings::getOverlayText(), SWGSDRangel::SWGATVModSettings::getReverseApiAddress(), SWGSDRangel::SWGATVModSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGATVModSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGATVModSettings::getReverseApiPort(), SWGSDRangel::SWGATVModSettings::getRfBandwidth(), SWGSDRangel::SWGATVModSettings::getRfOppBandwidth(), SWGSDRangel::SWGATVModSettings::getRfScalingFactor(), SWGSDRangel::SWGATVModSettings::getRgbColor(), SWGSDRangel::SWGATVModSettings::getShowOverlayText(), SWGSDRangel::SWGATVModSettings::getTitle(), SWGSDRangel::SWGATVModSettings::getUniformLevel(), SWGSDRangel::SWGATVModSettings::getUseReverseApi(), SWGSDRangel::SWGATVModSettings::getVideoFileName(), SWGSDRangel::SWGATVModSettings::getVideoPlay(), SWGSDRangel::SWGATVModSettings::getVideoPlayLoop(), ATVModSettings::m_atvModInput, ATVModSettings::m_atvModulation, ATVModSettings::m_atvStd, ATVModSettings::m_cameraPlay, ATVModSettings::m_channelMute, ATVModSettings::m_fmExcursion, ATVModSettings::m_forceDecimator, ATVModSettings::m_fps, BasebandSampleSource::m_guiMessageQueue, ATVModSettings::m_inputFrequencyOffset, BasebandSampleSource::m_inputMessageQueue, ATVModSettings::m_invertedVideo, ATVModSettings::m_nbLines, ATVModSettings::m_overlayText, ATVModSettings::m_reverseAPIAddress, ATVModSettings::m_reverseAPIChannelIndex, ATVModSettings::m_reverseAPIDeviceIndex, ATVModSettings::m_reverseAPIPort, ATVModSettings::m_rfBandwidth, ATVModSettings::m_rfOppBandwidth, ATVModSettings::m_rfScalingFactor, ATVModSettings::m_rgbColor, m_settings, ATVModSettings::m_showOverlayText, ATVModSettings::m_title, ATVModSettings::m_uniformLevel, ATVModSettings::m_useReverseAPI, ATVModSettings::m_videoPlay, ATVModSettings::m_videoPlayLoop, MessageQueue::push(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     ATVModSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getAtvModSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getAtvModSettings()->getRfBandwidth();
     }
     if (channelSettingsKeys.contains("rfOppBandwidth")) {
         settings.m_rfOppBandwidth = response.getAtvModSettings()->getRfOppBandwidth();
     }
     if (channelSettingsKeys.contains("atvStd")) {
         settings.m_atvStd = (ATVModSettings::ATVStd) response.getAtvModSettings()->getAtvStd();
     }
     if (channelSettingsKeys.contains("nbLines")) {
         settings.m_nbLines = response.getAtvModSettings()->getNbLines();
     }
     if (channelSettingsKeys.contains("fps")) {
         settings.m_fps = response.getAtvModSettings()->getFps();
     }
     if (channelSettingsKeys.contains("atvModInput")) {
         settings.m_atvModInput = (ATVModSettings::ATVModInput) response.getAtvModSettings()->getAtvModInput();
     }
     if (channelSettingsKeys.contains("uniformLevel")) {
         settings.m_uniformLevel = response.getAtvModSettings()->getUniformLevel();
     }
     if (channelSettingsKeys.contains("atvModulation")) {
         settings.m_atvModulation = (ATVModSettings::ATVModulation) response.getAtvModSettings()->getAtvModulation();
     }
     if (channelSettingsKeys.contains("videoPlayLoop")) {
         settings.m_videoPlayLoop = response.getAtvModSettings()->getVideoPlayLoop() != 0;
     }
     if (channelSettingsKeys.contains("videoPlay")) {
         settings.m_videoPlay = response.getAtvModSettings()->getVideoPlay() != 0;
     }
     if (channelSettingsKeys.contains("cameraPlay")) {
         settings.m_cameraPlay = response.getAtvModSettings()->getCameraPlay() != 0;
     }
     if (channelSettingsKeys.contains("channelMute")) {
         settings.m_channelMute = response.getAtvModSettings()->getChannelMute() != 0;
     }
     if (channelSettingsKeys.contains("invertedVideo")) {
         settings.m_invertedVideo = response.getAtvModSettings()->getInvertedVideo() != 0;
     }
     if (channelSettingsKeys.contains("rfScalingFactor")) {
         settings.m_rfScalingFactor = response.getAtvModSettings()->getRfScalingFactor();
     }
     if (channelSettingsKeys.contains("fmExcursion")) {
         settings.m_fmExcursion = response.getAtvModSettings()->getFmExcursion();
     }
     if (channelSettingsKeys.contains("forceDecimator")) {
         settings.m_forceDecimator = response.getAtvModSettings()->getForceDecimator() != 0;
     }
     if (channelSettingsKeys.contains("showOverlayText")) {
         settings.m_showOverlayText = response.getAtvModSettings()->getShowOverlayText() != 0;
     }
     if (channelSettingsKeys.contains("overlayText")) {
         settings.m_overlayText = *response.getAtvModSettings()->getOverlayText();
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getAtvModSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getAtvModSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getAtvModSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getAtvModSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getAtvModSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getAtvModSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getAtvModSettings()->getReverseApiChannelIndex();
     }
     if (frequencyOffsetChanged)
     {
         ATVMod::MsgConfigureChannelizer *msgChan = ATVMod::MsgConfigureChannelizer::create(
                 settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(msgChan);
     }
     MsgConfigureATVMod *msg = MsgConfigureATVMod::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureATVMod *msgToGUI = MsgConfigureATVMod::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     if (channelSettingsKeys.contains("imageFileName"))
     {
         MsgConfigureImageFileName *msg = MsgConfigureImageFileName::create(
                 *response.getAtvModSettings()->getImageFileName());
         m_inputMessageQueue.push(msg);
         if (m_guiMessageQueue) // forward to GUI if any
         {
             MsgConfigureImageFileName *msgToGUI = MsgConfigureImageFileName::create(
                     *response.getAtvModSettings()->getImageFileName());
             m_guiMessageQueue->push(msgToGUI);
         }
     }
     if (channelSettingsKeys.contains("videoFileName"))
     {
         MsgConfigureVideoFileName *msg = MsgConfigureVideoFileName::create(
                 *response.getAtvModSettings()->getVideoFileName());
         m_inputMessageQueue.push(msg);
         if (m_guiMessageQueue) // forward to GUI if any
         {
             MsgConfigureVideoFileName *msgToGUI = MsgConfigureVideoFileName::create(
                     *response.getAtvModSettings()->getVideoFileName());
             m_guiMessageQueue->push(msgToGUI);
         }
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_blackLevel
const float ATVMod::m_blackLevel = 0.3f static private
Definition at line 549 of file atvmod.h.
Referenced by applyStandard(), pullImageLine(), pullVSyncLineEqualizingPulses(), pullVSyncLineEqualizingThenLongPulses(), pullVSyncLineLongPulses(), and pullVSyncLineLongThenEqualizingPulses().
m_blankLineLvel
float ATVMod::m_blankLineLvel private
video level of blank lines
Definition at line 493 of file atvmod.h.
Referenced by applyStandard(), and pullVSyncLine().
m_cameraFPSTestNbFrames
const int ATVMod::m_cameraFPSTestNbFrames = 100 static private
number of frames for camera FPS test
Definition at line 553 of file atvmod.h.
Referenced by pullVideo().
m_cameraIndex
int ATVMod::m_cameraIndex private
curent camera index in list of available cameras
Definition at line 529 of file atvmod.h.
Referenced by getCameraNumbers(), handleMessage(), pullImageLine(), pullVideo(), resizeCamera(), and scanCameras().
m_cameras
std::vector<ATVCamera> ATVMod::m_cameras private
vector of available cameras
Definition at line 528 of file atvmod.h.
Referenced by calculateCamerasSizes(), getCameraNumbers(), handleMessage(), pullVideo(), releaseCameras(), resizeCamera(), resizeCameras(), and scanCameras().
m_carrierNco
NCO ATVMod::m_carrierNco private
Definition at line 464 of file atvmod.h.
Referenced by applyChannelSettings(), and pullFinalize().
m_channelId
const QString ATVMod::m_channelId = "ATVMod" static
Definition at line 407 of file atvmod.h.
Referenced by ATVMod(), and ATVModPlugin::initPlugin().
m_channelIdURI
const QString ATVMod::m_channelIdURI = "sdrangel.channeltx.modatv" static
Definition at line 406 of file atvmod.h.
Referenced by ATVModGUI::ATVModGUI(), and ATVModPlugin::initPlugin().
m_channelizer
UpChannelizer* ATVMod::m_channelizer private
Definition at line 458 of file atvmod.h.
Referenced by ATVMod(), handleMessage(), and ~ATVMod().
m_deviceAPI
DeviceAPI* ATVMod::m_deviceAPI private
Definition at line 456 of file atvmod.h.
Referenced by ATVMod(), and ~ATVMod().
m_DSBFilter
fftfilt* ATVMod::m_DSBFilter private
Definition at line 541 of file atvmod.h.
Referenced by applySettings(), ATVMod(), modulateVestigialSSB(), and ~ATVMod().
m_DSBFilterBuffer
Complex* ATVMod::m_DSBFilterBuffer private
Definition at line 542 of file atvmod.h.
Referenced by applySettings(), ATVMod(), modulateVestigialSSB(), and ~ATVMod().
m_DSBFilterBufferIndex
int ATVMod::m_DSBFilterBufferIndex private
Definition at line 543 of file atvmod.h.
Referenced by applySettings(), and modulateVestigialSSB().
m_evenImage
bool ATVMod::m_evenImage private
in interlaced mode true if this is an even image
Definition at line 497 of file atvmod.h.
Referenced by pullVideo().
m_fps
float ATVMod::m_fps private
resulting frames per second
Definition at line 501 of file atvmod.h.
Referenced by applyStandard(), calculateCamerasSizes(), calculateVideoSizes(), ATVMod::MsgReportCameraData::getFPS(), and pullVideo().
m_hBarIncrement
float ATVMod::m_hBarIncrement private
video level increment at each horizontal bar increment
Definition at line 494 of file atvmod.h.
Referenced by applyStandard().
m_horizontalCount
int ATVMod::m_horizontalCount private
current point index on line
Definition at line 499 of file atvmod.h.
Referenced by pullVideo().
m_image
cv::Mat ATVMod::m_image private
resized image for transmission at given rate
Definition at line 510 of file atvmod.h.
Referenced by resizeImage().
m_imageFileName
QString ATVMod::m_imageFileName private
Definition at line 532 of file atvmod.h.
Referenced by openImage(), and webapiFormatChannelSettings().
m_imageFromFile
cv::Mat ATVMod::m_imageFromFile private
original image not resized not overlaid by text
Definition at line 508 of file atvmod.h.
Referenced by applySettings(), and openImage().
m_imageOK
bool ATVMod::m_imageOK private
Definition at line 511 of file atvmod.h.
Referenced by applyStandard(), and openImage().
m_imageOriginal
cv::Mat ATVMod::m_imageOriginal private
original not resized image
Definition at line 509 of file atvmod.h.
Referenced by applySettings(), openImage(), and resizeImage().
m_inputFrequencyOffset
int ATVMod::m_inputFrequencyOffset private
Definition at line 461 of file atvmod.h.
Referenced by applyChannelSettings(), ATVMod(), and start().
m_interleaved
bool ATVMod::m_interleaved private
true if image is interlaced (2 half frames per frame)
Definition at line 496 of file atvmod.h.
Referenced by applyStandard().
m_interpolator
Interpolator ATVMod::m_interpolator private
Definition at line 467 of file atvmod.h.
Referenced by applyChannelSettings(), applySettings(), and pull().
m_interpolatorDistance
Real ATVMod::m_interpolatorDistance private
Definition at line 468 of file atvmod.h.
Referenced by applyChannelSettings(), applySettings(), ATVMod(), and pull().
m_interpolatorDistanceRemain
Real ATVMod::m_interpolatorDistanceRemain private
Definition at line 469 of file atvmod.h.
Referenced by applyChannelSettings(), applySettings(), ATVMod(), and pull().
m_levelCalcCount
quint32 ATVMod::m_levelCalcCount private
Definition at line 504 of file atvmod.h.
Referenced by calculateLevel().
m_levelNbSamples
const int ATVMod::m_levelNbSamples = 10000 static private
Definition at line 551 of file atvmod.h.
Referenced by calculateLevel().
m_levelSum
Real ATVMod::m_levelSum private
Definition at line 506 of file atvmod.h.
Referenced by calculateLevel().
m_lineCount
int ATVMod::m_lineCount private
current line index in frame
Definition at line 500 of file atvmod.h.
Referenced by pullImageLine(), pullVideo(), and pullVSyncLine().
m_linesPerVBar
uint32_t ATVMod::m_linesPerVBar private
number of lines for a bar of the bar chart
Definition at line 478 of file atvmod.h.
Referenced by applyStandard(), and pullImageLine().
m_modPhasor
float ATVMod::m_modPhasor private
For FM modulation.
Definition at line 466 of file atvmod.h.
Referenced by modulateSample().
m_modSample
Complex ATVMod::m_modSample private
Definition at line 465 of file atvmod.h.
Referenced by modulateSample(), and pull().
m_movingAverage
MovingAverageUtil<double, double, 16> ATVMod::m_movingAverage private
Definition at line 503 of file atvmod.h.
Referenced by getMagSq(), and pullFinalize().
m_nbBars
const int ATVMod::m_nbBars = 6 static private
number of bars in bar or chessboard patterns
Definition at line 552 of file atvmod.h.
Referenced by applyStandard().
m_nbBlankLines
int ATVMod::m_nbBlankLines private
number of lines in a frame (full or half) that are blanked (black) at the top of the image
Definition at line 492 of file atvmod.h.
Referenced by applyStandard(), calculateCamerasSizes(), calculateVideoSizes(), pullVideo(), and resizeImage().
m_nbHalfLongSync
int ATVMod::m_nbHalfLongSync private
number of half long sync / equalization lines
Definition at line 489 of file atvmod.h.
Referenced by applyStandard().
m_nbHorizPoints
int ATVMod::m_nbHorizPoints private
number of line points per horizontal line
Definition at line 484 of file atvmod.h.
Referenced by applyStandard(), and pullVideo().
m_nbImageLines
uint32_t ATVMod::m_nbImageLines private
number of image lines excluding synchronization lines
Definition at line 482 of file atvmod.h.
Referenced by applyStandard(), calculateCamerasSizes(), calculateVideoSizes(), and resizeImage().
m_nbImageLines2
uint32_t ATVMod::m_nbImageLines2 private
same number as above (non interlaced) or half the number above (interlaced)
Definition at line 483 of file atvmod.h.
Referenced by applyStandard(), and pullImageLine().
m_nbLines
int ATVMod::m_nbLines private
number of lines per complete frame
Definition at line 480 of file atvmod.h.
Referenced by applyStandard(), and pullVideo().
m_nbLines2
int ATVMod::m_nbLines2 private
same number as above (non interlaced) or half the number above (interlaced)
Definition at line 481 of file atvmod.h.
Referenced by applyStandard(), and pullVideo().
m_nbLongSyncLines
int ATVMod::m_nbLongSyncLines private
number of whole long sync lines for vertical synchronization
Definition at line 488 of file atvmod.h.
Referenced by applyStandard().
m_nbSyncLinesBottom
int ATVMod::m_nbSyncLinesBottom private
number of sync lines at bottom
Definition at line 487 of file atvmod.h.
Referenced by applyStandard(), and pullVideo().
m_nbSyncLinesHeadE
int ATVMod::m_nbSyncLinesHeadE private
number of header sync lines on even frame
Definition at line 485 of file atvmod.h.
Referenced by applyStandard(), pullImageLine(), and pullVideo().
m_nbSyncLinesHeadO
int ATVMod::m_nbSyncLinesHeadO private
number of header sync lines on odd frame
Definition at line 486 of file atvmod.h.
Referenced by applyStandard(), pullImageLine(), and pullVideo().
m_nbWholeEqLines
int ATVMod::m_nbWholeEqLines private
number of whole equalizing lines
Definition at line 490 of file atvmod.h.
Referenced by applyStandard().
m_networkManager
QNetworkAccessManager* ATVMod::m_networkManager private
Definition at line 545 of file atvmod.h.
Referenced by ATVMod(), webapiReverseSendSettings(), and ~ATVMod().
m_networkRequest
QNetworkRequest ATVMod::m_networkRequest private
Definition at line 546 of file atvmod.h.
Referenced by webapiReverseSendSettings().
m_outputSampleRate
int ATVMod::m_outputSampleRate private
Definition at line 460 of file atvmod.h.
Referenced by applyChannelSettings(), applySettings(), ATVMod(), pull(), start(), and webapiFormatChannelReport().
m_overlayText
std::string ATVMod::m_overlayText private
Definition at line 531 of file atvmod.h.
m_peakLevel
Real ATVMod::m_peakLevel private
Definition at line 505 of file atvmod.h.
Referenced by calculateLevel().
m_pointsPerBP
int ATVMod::m_pointsPerBP private
number of line points for the back porch
Definition at line 473 of file atvmod.h.
Referenced by applyStandard(), and pullImageLine().
m_pointsPerFP
uint32_t ATVMod::m_pointsPerFP private
number of line points for the front porch
Definition at line 475 of file atvmod.h.
Referenced by applyStandard().
m_pointsPerFSync
int ATVMod::m_pointsPerFSync private
number of line points for the field first sync
Definition at line 476 of file atvmod.h.
Referenced by applyStandard().
m_pointsPerHBar
uint32_t ATVMod::m_pointsPerHBar private
number of line points for a bar of the bar chart
Definition at line 477 of file atvmod.h.
Referenced by applyStandard(), and pullImageLine().
m_pointsPerImgLine
int ATVMod::m_pointsPerImgLine private
number of line points for the image line
Definition at line 474 of file atvmod.h.
Referenced by applyStandard(), calculateCamerasSizes(), calculateVideoSizes(), and resizeImage().
m_pointsPerLine
uint32_t ATVMod::m_pointsPerLine private
Number of points per full line.
Definition at line 471 of file atvmod.h.
Referenced by applyChannelSettings(), applySettings(), and applyStandard().
m_pointsPerSync
int ATVMod::m_pointsPerSync private
number of line points for the horizontal sync
Definition at line 472 of file atvmod.h.
Referenced by applyStandard(), and pullVSyncLineLongPulses().
m_pointsPerTU
uint32_t ATVMod::m_pointsPerTU private
number of line points per time unit
Definition at line 479 of file atvmod.h.
m_settings
ATVModSettings ATVMod::m_settings private
Definition at line 462 of file atvmod.h.
Referenced by applyChannelSettings(), applySettings(), applyStandard(), ATVMod(), deserialize(), mixImageAndText(), modulateSample(), modulateSSB(), modulateVestigialSSB(), openImage(), pull(), pullVideo(), serialize(), start(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex ATVMod::m_settingsMutex private
Definition at line 498 of file atvmod.h.
Referenced by applyChannelSettings(), applySettings(), pull(), pullFinalize(), and seekVideoFileStream().
m_singleLongSync
bool ATVMod::m_singleLongSync private
single or double long sync per long sync line
Definition at line 491 of file atvmod.h.
Referenced by applyStandard().
m_spanLevel
const float ATVMod::m_spanLevel = 0.7f static private
Definition at line 550 of file atvmod.h.
Referenced by applyStandard().
m_ssbFftLen
const int ATVMod::m_ssbFftLen = 1024 static private
Definition at line 548 of file atvmod.h.
Referenced by applyChannelSettings(), applySettings(), and ATVMod().
m_SSBFilter
fftfilt* ATVMod::m_SSBFilter private
Definition at line 536 of file atvmod.h.
Referenced by applyChannelSettings(), applySettings(), ATVMod(), modulateSSB(), and ~ATVMod().
m_SSBFilterBuffer
Complex* ATVMod::m_SSBFilterBuffer private
Definition at line 537 of file atvmod.h.
Referenced by applyChannelSettings(), applySettings(), ATVMod(), modulateSSB(), and ~ATVMod().
m_SSBFilterBufferIndex
int ATVMod::m_SSBFilterBufferIndex private
Definition at line 538 of file atvmod.h.
Referenced by applyChannelSettings(), applySettings(), and modulateSSB().
m_threadedChannelizer
ThreadedBasebandSampleSource* ATVMod::m_threadedChannelizer private
Definition at line 457 of file atvmod.h.
Referenced by ATVMod(), and ~ATVMod().
m_tvSampleRate
int ATVMod::m_tvSampleRate private
sample rate for generating signal
Definition at line 470 of file atvmod.h.
Referenced by applyChannelSettings(), applySettings(), getEffectiveSampleRate(), and pull().
m_vBarIncrement
float ATVMod::m_vBarIncrement private
video level increment at each vertical bar increment
Definition at line 495 of file atvmod.h.
Referenced by applyStandard().
m_video
cv::VideoCapture ATVMod::m_video private
current video capture
Definition at line 513 of file atvmod.h.
Referenced by handleMessage(), openVideo(), pullVideo(), seekVideoFileStream(), and ~ATVMod().
m_videoEOF
bool ATVMod::m_videoEOF private
current video has reached end of file
Definition at line 525 of file atvmod.h.
Referenced by openVideo(), pullVideo(), and seekVideoFileStream().
m_videoFileName
QString ATVMod::m_videoFileName private
Definition at line 533 of file atvmod.h.
Referenced by openVideo(), and webapiFormatChannelSettings().
m_videoFPS
float ATVMod::m_videoFPS private
current video FPS rate
Definition at line 516 of file atvmod.h.
Referenced by calculateVideoSizes(), getCameraNumbers(), handleMessage(), openVideo(), and pullVideo().
m_videoFPSCount
float ATVMod::m_videoFPSCount private
current video FPS fractional counter
Definition at line 522 of file atvmod.h.
Referenced by calculateVideoSizes(), pullVideo(), and seekVideoFileStream().
m_videoFPSq
float ATVMod::m_videoFPSq private
current video FPS sacaling factor
Definition at line 521 of file atvmod.h.
Referenced by calculateVideoSizes(), pullVideo(), and seekVideoFileStream().
m_videoFrame
cv::Mat ATVMod::m_videoFrame private
current displayable video frame
Definition at line 515 of file atvmod.h.
Referenced by resizeVideo().
m_videoframeOriginal
cv::Mat ATVMod::m_videoframeOriginal private
current frame from video
Definition at line 514 of file atvmod.h.
Referenced by pullVideo(), and resizeVideo().
m_videoFx
float ATVMod::m_videoFx private
current video horizontal scaling factor
Definition at line 519 of file atvmod.h.
Referenced by calculateVideoSizes(), and resizeVideo().
m_videoFy
float ATVMod::m_videoFy private
current video vertictal scaling factor
Definition at line 520 of file atvmod.h.
Referenced by calculateVideoSizes(), and resizeVideo().
m_videoHeight
int ATVMod::m_videoHeight private
current video frame height
Definition at line 518 of file atvmod.h.
Referenced by calculateVideoSizes(), getCameraNumbers(), handleMessage(), and openVideo().
m_videoLength
int ATVMod::m_videoLength private
current video length in frames
Definition at line 524 of file atvmod.h.
Referenced by ATVMod::MsgReportVideoFileSourceStreamData::getVideoLength(), openVideo(), and seekVideoFileStream().
m_videoOK
bool ATVMod::m_videoOK private
Definition at line 526 of file atvmod.h.
Referenced by applyStandard(), handleMessage(), openVideo(), pullVideo(), and seekVideoFileStream().
m_videoPrevFPSCount
int ATVMod::m_videoPrevFPSCount private
current video FPS previous integer counter
Definition at line 523 of file atvmod.h.
Referenced by calculateVideoSizes(), pullVideo(), and seekVideoFileStream().
m_videoWidth
int ATVMod::m_videoWidth private
current video frame width
Definition at line 517 of file atvmod.h.
Referenced by calculateVideoSizes(), getCameraNumbers(), handleMessage(), and openVideo().
The documentation for this class was generated from the following files:
plugins/channeltx/modatv/atvmod.h
plugins/channeltx/modatv/atvmod.cpp