SDRAngel: DeviceSoapySDRParams Class Reference
DeviceSoapySDRParams Class Reference
#include <devicesoapysdrparams.h>
Classes
struct ChannelSettings
struct FrequencySetting
struct GainSetting
Public Member Functions
DeviceSoapySDRParams (SoapySDR::Device *device)
~DeviceSoapySDRParams ()
const SoapySDR::ArgInfoList & getDeviceArgs () const
const ChannelSettings * getRxChannelSettings (uint32_t index)
const ChannelSettings * getTxChannelSettings (uint32_t index)
std::string getRxChannelMainTunableElementName (uint32_t index)
std::string getTxChannelMainTunableElementName (uint32_t index)
Private Member Functions
void fillParams ()
void fillChannelParams (std::vector< ChannelSettings > &channelSettings, int direction, unsigned int ichan)
void printParams ()
void printChannelParams (const ChannelSettings &channelSetting)
std::string argInfoToString (const SoapySDR::ArgInfo &argInfo, const std::string indent=" ")
std::string argInfoListToString (const SoapySDR::ArgInfoList &argInfos)
std::string rangeToString (const SoapySDR::Range &range)
std::string rangeListToString (const SoapySDR::RangeList &range, const double scale)
template<typename Type >
std::string vectorToString (const std::vector< Type > &options)
Private Attributes
SoapySDR::Device * m_device
SoapySDR::ArgInfoList m_deviceSettingsArgs
list (vector) of device settings arguments
uint32_t m_nbRx
number of Rx channels
uint32_t m_nbTx
number of Tx channels
std::vector< ChannelSettings > m_RxChannelsSettings
std::vector< ChannelSettings > m_TxChannelsSettings
Detailed Description
This structure refers to one physical device shared among parties (logical devices represented by the DeviceAPI with single Rx or Tx stream type). It allows storing information on the common resources in one place and is shared among participants. There is only one copy that is constructed by the first participant and destroyed by the last. A participant knows it is the first or last by checking the lists of buddies (Rx + Tx).
Definition at line 37 of file devicesoapysdrparams.h.
Constructor & Destructor Documentation
DeviceSoapySDRParams()
DeviceSoapySDRParams::DeviceSoapySDRParams (SoapySDR::Device * device)
Definition at line 25 of file devicesoapysdrparams.cpp.
References fillParams(), and printParams().
                                                                  :
     m_device(device)
 {
     fillParams();
     printParams();
 }
~DeviceSoapySDRParams()
DeviceSoapySDRParams::~DeviceSoapySDRParams ()
Definition at line 32 of file devicesoapysdrparams.cpp.
 {}
Member Function Documentation
argInfoListToString()
std::string DeviceSoapySDRParams::argInfoListToString (const SoapySDR::ArgInfoList & argInfos) private
Definition at line 248 of file devicesoapysdrparams.cpp.
References argInfoToString(), and i.
Referenced by printChannelParams(), and printParams().
 {
     std::stringstream ss;
     for (std::size_t i = 0; i < argInfos.size(); i++) {
         ss << argInfoToString(argInfos[i]) << std::endl;
     }
     return ss.str();
 }
argInfoToString()
std::string DeviceSoapySDRParams::argInfoToString (const SoapySDR::ArgInfo & argInfo, const std::string indent = " ") private
Definition at line 185 of file devicesoapysdrparams.cpp.
References rangeToString(), and vectorToString().
Referenced by argInfoListToString().
 {
     std::stringstream ss;
     //name, or use key if missing
     std::string name = argInfo.name;
     if (argInfo.name.empty()) name = argInfo.key;
     ss << indent << " * " << name;
     //optional description
     std::string desc = argInfo.description;
     const std::string replace("\n"+indent+"   ");
     for (std::size_t pos = 0; (pos=desc.find("\n", pos)) != std::string::npos; pos+=replace.size()) {
         desc.replace(pos, 1, replace);
     }
     if (not desc.empty()) {
         ss << " - " << desc << std::endl << indent << "  ";
     }
     //other fields
     ss << " [key=" << argInfo.key;
     if (not argInfo.units.empty()) {
         ss << ", units=" << argInfo.units;
     }
     if (not argInfo.value.empty()) {
         ss << ", default=" << argInfo.value;
     }
     //type
     switch (argInfo.type)
     {
     case SoapySDR::ArgInfo::BOOL:
         ss << ", type=bool";
         break;
     case SoapySDR::ArgInfo::INT:
         ss << ", type=int";
         break;
     case SoapySDR::ArgInfo::FLOAT:
         ss << ", type=float";
         break;
     case SoapySDR::ArgInfo::STRING:
         ss << ", type=string";
         break;
     }
     //optional range/enumeration
     if (argInfo.range.minimum() < argInfo.range.maximum()) {
         ss << ", range=" << rangeToString(argInfo.range);
     }
     if (not argInfo.options.empty()) {
         ss << ", options=(" << vectorToString(argInfo.options) << ")";
     }
     ss << "]";
     return ss.str();
 }
fillChannelParams()
void DeviceSoapySDRParams::fillChannelParams (std::vector< ChannelSettings > & channelSettings, int direction, unsigned int ichan) private
Definition at line 86 of file devicesoapysdrparams.cpp.
References m_device.
Referenced by fillParams().
 {
     channelSettings.push_back(ChannelSettings());
     channelSettings.back().m_streamSettingsArgs = m_device->getStreamArgsInfo(direction, ichan);
     channelSettings.back().m_antennas = m_device->listAntennas(direction, ichan);
     channelSettings.back().m_hasDCAutoCorrection = m_device->hasDCOffsetMode(direction, ichan);
     channelSettings.back().m_hasDCOffsetValue = m_device->hasDCOffset(direction, ichan);
     channelSettings.back().m_hasIQBalanceValue = m_device->hasIQBalance(direction, ichan);
     channelSettings.back().m_hasFrequencyCorrectionValue = m_device->hasFrequencyCorrection(direction, ichan);
     // gains
     channelSettings.back().m_hasAGC = m_device->hasGainMode(direction, ichan);
     channelSettings.back().m_gainRange = m_device->getGainRange(direction, ichan);
     std::vector<std::string> gainsList = m_device->listGains(direction, ichan);
     for (const auto &it : gainsList)
     {
         channelSettings.back().m_gainSettings.push_back(GainSetting());
         channelSettings.back().m_gainSettings.back().m_name = it;
         channelSettings.back().m_gainSettings.back().m_range = m_device->getGainRange(direction, ichan, it);
     }
     // frequencies
     std::vector<std::string> freqsList = m_device->listFrequencies(direction, ichan);
     for (const auto &it : freqsList)
     {
         channelSettings.back().m_frequencySettings.push_back(FrequencySetting());
         channelSettings.back().m_frequencySettings.back().m_name = it;
         channelSettings.back().m_frequencySettings.back().m_ranges = m_device->getFrequencyRange(direction, ichan, it);
     }
     channelSettings.back().m_frequencySettingsArgs = m_device->getFrequencyArgsInfo(direction, ichan);
     // sample rates
     channelSettings.back().m_ratesRanges = m_device->getSampleRateRange(direction, ichan);
     // bandwidths
     channelSettings.back().m_bandwidthsRanges = m_device->getBandwidthRange(direction, ichan);
 }
fillParams()
void DeviceSoapySDRParams::fillParams () private
Definition at line 71 of file devicesoapysdrparams.cpp.
References fillChannelParams(), m_device, m_deviceSettingsArgs, m_nbRx, m_nbTx, m_RxChannelsSettings, and m_TxChannelsSettings.
Referenced by DeviceSoapySDRParams().
 {
     m_deviceSettingsArgs = m_device->getSettingInfo();
     m_nbRx = m_device->getNumChannels(SOAPY_SDR_RX);
     m_nbTx = m_device->getNumChannels(SOAPY_SDR_TX);
     for (unsigned int ichan = 0; ichan < m_nbRx; ichan++) {
         fillChannelParams(m_RxChannelsSettings, SOAPY_SDR_RX, ichan);
     }
     for (unsigned int ichan = 0; ichan < m_nbTx; ichan++) {
         fillChannelParams(m_TxChannelsSettings, SOAPY_SDR_TX, ichan);
     }
 }
getDeviceArgs()
const SoapySDR::ArgInfoList& DeviceSoapySDRParams::getDeviceArgs () const inline
Definition at line 72 of file devicesoapysdrparams.h.
Referenced by SoapySDROutput::getDeviceArgInfoList(), SoapySDRInput::getDeviceArgInfoList(), SoapySDROutput::initDeviceArgSettings(), SoapySDRInput::initDeviceArgSettings(), SoapySDROutput::webapiFormatDeviceReport(), and SoapySDRInput::webapiFormatDeviceReport().
 { return m_deviceSettingsArgs; }
getRxChannelMainTunableElementName()
std::string DeviceSoapySDRParams::getRxChannelMainTunableElementName (uint32_t index)
Definition at line 35 of file devicesoapysdrparams.cpp.
References DeviceSoapySDRParams::ChannelSettings::m_frequencySettings, m_nbRx, and m_RxChannelsSettings.
Referenced by SoapySDRInput::handleMessage(), and SoapySDRInput::setDeviceCenterFrequency().
 {
     if (index < m_nbRx)
     {
         return std::string("RF");
     }
     else
     {
         const ChannelSettings& channelSettings = m_RxChannelsSettings[index];
         if (channelSettings.m_frequencySettings.size() > 0) {
             return channelSettings.m_frequencySettings.front().m_name;
         } else {
             return std::string("RF");
         }
     }
 }
getRxChannelSettings()
const ChannelSettings* DeviceSoapySDRParams::getRxChannelSettings (uint32_t index) inline
Definition at line 74 of file devicesoapysdrparams.h.
Referenced by SoapySDRInput::getAntennas(), SoapySDRInput::getBandwidthRanges(), SoapySDRInput::getFrequencyRange(), SoapySDRInput::getGlobalGainRange(), SoapySDRInput::getIndividualGainsRanges(), SoapySDRInput::getRateRanges(), SoapySDRInput::getStreamArgInfoList(), SoapySDRInput::getTunableElements(), SoapySDRInput::hasDCAutoCorrection(), SoapySDRInput::hasDCCorrectionValue(), SoapySDRInput::hasIQCorrectionValue(), SoapySDRInput::initGainSettings(), SoapySDRInput::initStreamArgSettings(), SoapySDRInput::initTunableElementsSettings(), SoapySDRInput::isAGCSupported(), and SoapySDRInput::webapiFormatDeviceReport().
     {
         if (index < m_nbRx) {
             return &m_RxChannelsSettings[index];
         } else {
             return 0;
         }
     }
getTxChannelMainTunableElementName()
std::string DeviceSoapySDRParams::getTxChannelMainTunableElementName (uint32_t index)
Definition at line 53 of file devicesoapysdrparams.cpp.
References DeviceSoapySDRParams::ChannelSettings::m_frequencySettings, m_nbRx, and m_RxChannelsSettings.
Referenced by SoapySDROutput::handleMessage(), and SoapySDROutput::setDeviceCenterFrequency().
 {
     if (index < m_nbRx)
     {
         return std::string("RF");
     }
     else
     {
         const ChannelSettings& channelSettings = m_RxChannelsSettings[index];
         if (channelSettings.m_frequencySettings.size() > 0) {
             return channelSettings.m_frequencySettings.front().m_name;
         } else {
             return std::string("RF");
         }
     }
 }
getTxChannelSettings()
const ChannelSettings* DeviceSoapySDRParams::getTxChannelSettings (uint32_t index) inline
Definition at line 83 of file devicesoapysdrparams.h.
Referenced by SoapySDROutput::getAntennas(), SoapySDROutput::getBandwidthRanges(), SoapySDROutput::getFrequencyRange(), SoapySDROutput::getGlobalGainRange(), SoapySDROutput::getIndividualGainsRanges(), SoapySDROutput::getRateRanges(), SoapySDROutput::getStreamArgInfoList(), SoapySDROutput::getTunableElements(), SoapySDROutput::hasDCAutoCorrection(), SoapySDROutput::hasDCCorrectionValue(), SoapySDROutput::hasIQCorrectionValue(), SoapySDROutput::initGainSettings(), SoapySDROutput::initStreamArgSettings(), SoapySDROutput::initTunableElementsSettings(), SoapySDROutput::isAGCSupported(), and SoapySDROutput::webapiFormatDeviceReport().
     {
         if (index < m_nbTx) {
             return &m_TxChannelsSettings[index];
         } else {
             return 0;
         }
     }
printChannelParams()
void DeviceSoapySDRParams::printChannelParams (const ChannelSettings & channelSetting) private
Definition at line 152 of file devicesoapysdrparams.cpp.
References argInfoListToString(), DeviceSoapySDRParams::ChannelSettings::m_antennas, DeviceSoapySDRParams::ChannelSettings::m_bandwidthsRanges, DeviceSoapySDRParams::ChannelSettings::m_frequencySettings, DeviceSoapySDRParams::ChannelSettings::m_frequencySettingsArgs, DeviceSoapySDRParams::ChannelSettings::m_gainRange, DeviceSoapySDRParams::ChannelSettings::m_gainSettings, DeviceSoapySDRParams::ChannelSettings::m_hasAGC, DeviceSoapySDRParams::ChannelSettings::m_hasDCAutoCorrection, DeviceSoapySDRParams::ChannelSettings::m_hasDCOffsetValue, DeviceSoapySDRParams::ChannelSettings::m_hasFrequencyCorrectionValue, DeviceSoapySDRParams::ChannelSettings::m_hasIQBalanceValue, DeviceSoapySDRParams::ChannelSettings::m_ratesRanges, DeviceSoapySDRParams::ChannelSettings::m_streamSettingsArgs, rangeListToString(), rangeToString(), and vectorToString().
Referenced by printParams().
 {
     qDebug() << "DeviceSoapySDRParams::printParams: m_streamSettingsArgs:\n" << argInfoListToString(channelSetting.m_streamSettingsArgs).c_str();
     qDebug() << "DeviceSoapySDRParams::printParams:"
             << " m_hasDCAutoCorrection: " << channelSetting.m_hasDCAutoCorrection
             << " m_hasDCOffsetValue: " << channelSetting.m_hasDCOffsetValue
             << " m_hasIQBalanceValue: " << channelSetting.m_hasIQBalanceValue
             << " m_hasFrequencyCorrectionValue: " << channelSetting.m_hasFrequencyCorrectionValue
             << " m_hasAGC: " << channelSetting.m_hasAGC;
     qDebug() << "DeviceSoapySDRParams::printParams: m_antennas: " << vectorToString(channelSetting.m_antennas).c_str();
     qDebug() << "DeviceSoapySDRParams::printParams: m_gainRange: " << rangeToString(channelSetting.m_gainRange).c_str();
     qDebug() << "DeviceSoapySDRParams::printParams: individual gains...";
     for (const auto &gainIt : channelSetting.m_gainSettings)
     {
         qDebug() << "DeviceSoapySDRParams::printParams: m_name: " << gainIt.m_name.c_str();
         qDebug() << "DeviceSoapySDRParams::printParams: m_range: " << rangeToString(gainIt.m_range).c_str();
     }
     qDebug() << "DeviceSoapySDRParams::printParams: tunable elements...";
     for (const auto &freqIt : channelSetting.m_frequencySettings)
     {
         qDebug() << "DeviceSoapySDRParams::printParams: m_name: " << freqIt.m_name.c_str();
         qDebug() << "DeviceSoapySDRParams::printParams: m_range (kHz): " << rangeListToString(freqIt.m_ranges, 1e3).c_str();
     }
     qDebug() << "DeviceSoapySDRParams::printParams: m_frequencySettingsArgs:\n" << argInfoListToString(channelSetting.m_frequencySettingsArgs).c_str();
     qDebug() << "DeviceSoapySDRParams::printParams: m_ratesRanges (kHz): " << rangeListToString(channelSetting.m_ratesRanges, 1e3).c_str();
     qDebug() << "DeviceSoapySDRParams::printParams: m_bandwidthsRanges (kHz): " << rangeListToString(channelSetting.m_bandwidthsRanges, 1e3).c_str();
 }
printParams()
void DeviceSoapySDRParams::printParams () private
Definition at line 130 of file devicesoapysdrparams.cpp.
References argInfoListToString(), m_deviceSettingsArgs, m_RxChannelsSettings, m_TxChannelsSettings, and printChannelParams().
Referenced by DeviceSoapySDRParams().
 {
     qDebug() << "DeviceSoapySDRParams::printParams: m_deviceSettingsArgs:\n" << argInfoListToString(m_deviceSettingsArgs).c_str();
     int ichan = 0;
     for (const auto &it : m_RxChannelsSettings)
     {
         qDebug() << "DeviceSoapySDRParams::printParams: Rx channel " << ichan;
         printChannelParams(it);
         ichan++;
     }
     ichan = 0;
     for (const auto &it : m_TxChannelsSettings)
     {
         qDebug() << "DeviceSoapySDRParams::printParams: Tx channel " << ichan;
         printChannelParams(it);
         ichan++;
     }
 }
rangeListToString()
std::string DeviceSoapySDRParams::rangeListToString (const SoapySDR::RangeList & range, const double scale) private
Definition at line 272 of file devicesoapysdrparams.cpp.
References i.
Referenced by printChannelParams().
 {
     std::stringstream ss;
     for (std::size_t i = 0; i < range.size(); i++)
     {
         if (not ss.str().empty()) {
             ss << ", ";
         }
         if (range[i].minimum() == range[i].maximum())
         {
             ss << (range[i].minimum()/scale);
         }
         else
         {
             ss << "[" << (range[i].minimum()/scale) << ", " << (range[i].maximum()/scale);
             if (range[i].step() != 0.0) {
                 ss << ", " << (range[i].step()/scale);
             }
             ss << "]";
         }
     }
     return ss.str();
 }
rangeToString()
std::string DeviceSoapySDRParams::rangeToString (const SoapySDR::Range & range) private
Definition at line 259 of file devicesoapysdrparams.cpp.
Referenced by argInfoToString(), and printChannelParams().
 {
     std::stringstream ss;
     ss << "[" << range.minimum() << ", " << range.maximum();
     if (range.step() != 0.0) {
         ss << ", " << range.step();
     }
     ss << "]";
     return ss.str();
 }
vectorToString()
template<typename Type > std::string DeviceSoapySDRParams::vectorToString (const std::vector< Type > & options) inline private
Definition at line 108 of file devicesoapysdrparams.h.
References i.
Referenced by argInfoToString(), and printChannelParams().
     {
         std::stringstream ss;
         if (options.empty()) {
             return "";
         }
         for (std::size_t i = 0; i < options.size(); i++)
         {
             if (not ss.str().empty()) {
                 ss << ", ";
             }
             ss << options[i];
         }
         return ss.str();
     }
Member Data Documentation
m_device
SoapySDR::Device* DeviceSoapySDRParams::m_device private
Definition at line 128 of file devicesoapysdrparams.h.
Referenced by fillChannelParams(), and fillParams().
m_deviceSettingsArgs
SoapySDR::ArgInfoList DeviceSoapySDRParams::m_deviceSettingsArgs private
list (vector) of device settings arguments
Definition at line 129 of file devicesoapysdrparams.h.
Referenced by fillParams(), and printParams().
m_nbRx
uint32_t DeviceSoapySDRParams::m_nbRx private
number of Rx channels
Definition at line 130 of file devicesoapysdrparams.h.
Referenced by fillParams(), getRxChannelMainTunableElementName(), and getTxChannelMainTunableElementName().
m_nbTx
uint32_t DeviceSoapySDRParams::m_nbTx private
number of Tx channels
Definition at line 131 of file devicesoapysdrparams.h.
Referenced by fillParams().
m_RxChannelsSettings
std::vector<ChannelSettings> DeviceSoapySDRParams::m_RxChannelsSettings private
Definition at line 132 of file devicesoapysdrparams.h.
Referenced by fillParams(), getRxChannelMainTunableElementName(), getTxChannelMainTunableElementName(), and printParams().
m_TxChannelsSettings
std::vector<ChannelSettings> DeviceSoapySDRParams::m_TxChannelsSettings private
Definition at line 133 of file devicesoapysdrparams.h.
Referenced by fillParams(), and printParams().
The documentation for this class was generated from the following files:
devices/soapysdr/devicesoapysdrparams.h
devices/soapysdr/devicesoapysdrparams.cpp