SDRAngel: WebAPIAdapterSrv Class Reference
WebAPIAdapterSrv Class Reference
#include <webapiadaptersrv.h>
Public Member Functions
WebAPIAdapterSrv (MainCore &mainCore)
virtual ~WebAPIAdapterSrv ()
virtual int instanceSummary (SWGSDRangel::SWGInstanceSummaryResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceDelete (SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceConfigGet (SWGSDRangel::SWGInstanceConfigResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceDevices (int direction, SWGSDRangel::SWGInstanceDevicesResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceChannels (int direction, SWGSDRangel::SWGInstanceChannelsResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceLoggingGet (SWGSDRangel::SWGLoggingInfo &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceLoggingPut (SWGSDRangel::SWGLoggingInfo &query, SWGSDRangel::SWGLoggingInfo &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioGet (SWGSDRangel::SWGAudioDevices &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioInputPatch (SWGSDRangel::SWGAudioInputDevice &response, const QStringList &audioInputKeys, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioOutputPatch (SWGSDRangel::SWGAudioOutputDevice &response, const QStringList &audioOutputKeys, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioInputDelete (SWGSDRangel::SWGAudioInputDevice &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioOutputDelete (SWGSDRangel::SWGAudioOutputDevice &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioInputCleanupPatch (SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAudioOutputCleanupPatch (SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceLocationGet (SWGSDRangel::SWGLocationInformation &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceLocationPut (SWGSDRangel::SWGLocationInformation &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceDVSerialGet (SWGSDRangel::SWGDVSerialDevices &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceDVSerialPatch (bool dvserial, SWGSDRangel::SWGDVSerialDevices &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAMBESerialGet (SWGSDRangel::SWGDVSerialDevices &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAMBEDevicesGet (SWGSDRangel::SWGAMBEDevices &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAMBEDevicesPut (SWGSDRangel::SWGAMBEDevices &query, SWGSDRangel::SWGAMBEDevices &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAMBEDevicesPatch (SWGSDRangel::SWGAMBEDevices &query, SWGSDRangel::SWGAMBEDevices &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceAMBEDevicesDelete (SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetFilePut (SWGSDRangel::SWGPresetImport &query, SWGSDRangel::SWGPresetIdentifier &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetFilePost (SWGSDRangel::SWGPresetExport &query, SWGSDRangel::SWGPresetIdentifier &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetsGet (SWGSDRangel::SWGPresets &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetPatch (SWGSDRangel::SWGPresetTransfer &query, SWGSDRangel::SWGPresetIdentifier &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetPut (SWGSDRangel::SWGPresetTransfer &query, SWGSDRangel::SWGPresetIdentifier &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetPost (SWGSDRangel::SWGPresetTransfer &query, SWGSDRangel::SWGPresetIdentifier &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instancePresetDelete (SWGSDRangel::SWGPresetIdentifier &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceDeviceSetsGet (SWGSDRangel::SWGDeviceSetList &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceDeviceSetPost (int direction, SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int instanceDeviceSetDelete (SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetGet (int deviceSetIndex, SWGSDRangel::SWGDeviceSet &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetFocusPatch (int deviceSetIndex, SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDevicePut (int deviceSetIndex, SWGSDRangel::SWGDeviceListItem &query, SWGSDRangel::SWGDeviceListItem &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDeviceSettingsGet (int deviceSetIndex, SWGSDRangel::SWGDeviceSettings &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDeviceSettingsPutPatch (int deviceSetIndex, bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDeviceRunGet (int deviceSetIndex, SWGSDRangel::SWGDeviceState &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDeviceRunPost (int deviceSetIndex, SWGSDRangel::SWGDeviceState &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDeviceRunDelete (int deviceSetIndex, SWGSDRangel::SWGDeviceState &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetDeviceReportGet (int deviceSetIndex, SWGSDRangel::SWGDeviceReport &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetChannelsReportGet (int deviceSetIndex, SWGSDRangel::SWGChannelsDetail &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetChannelPost (int deviceSetIndex, SWGSDRangel::SWGChannelSettings &query, SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetChannelDelete (int deviceSetIndex, int channelIndex, SWGSDRangel::SWGSuccessResponse &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetChannelSettingsGet (int deviceSetIndex, int channelIndex, SWGSDRangel::SWGChannelSettings &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetChannelSettingsPutPatch (int deviceSetIndex, int channelIndex, bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, SWGSDRangel::SWGErrorResponse &error)
virtual int devicesetChannelReportGet (int deviceSetIndex, int channelIndex, SWGSDRangel::SWGChannelReport &response, SWGSDRangel::SWGErrorResponse &error)
Public Member Functions inherited from WebAPIAdapterInterface
virtual ~WebAPIAdapterInterface ()
Private Member Functions
void getDeviceSetList (SWGSDRangel::SWGDeviceSetList *deviceSetList)
void getDeviceSet (SWGSDRangel::SWGDeviceSet *swgDeviceSet, const DeviceSet *deviceSet, int deviceUISetIndex)
void getChannelsDetail (SWGSDRangel::SWGChannelsDetail *channelsDetail, const DeviceSet *deviceSet)
Static Private Member Functions
static QtMsgType getMsgTypeFromString (const QString &msgTypeString)
static void getMsgTypeString (const QtMsgType &msgType, QString &level)
Private Attributes
MainCore & m_mainCore
Additional Inherited Members
Static Public Attributes inherited from WebAPIAdapterInterface
static QString instanceSummaryURL = "/sdrangel"
static QString instanceConfigURL = "/sdrangel/config"
static QString instanceDevicesURL = "/sdrangel/devices"
static QString instanceChannelsURL = "/sdrangel/channels"
static QString instanceLoggingURL = "/sdrangel/logging"
static QString instanceAudioURL = "/sdrangel/audio"
static QString instanceAudioInputParametersURL = "/sdrangel/audio/input/parameters"
static QString instanceAudioOutputParametersURL = "/sdrangel/audio/output/parameters"
static QString instanceAudioInputCleanupURL = "/sdrangel/audio/input/cleanup"
static QString instanceAudioOutputCleanupURL = "/sdrangel/audio/output/cleanup"
static QString instanceLocationURL = "/sdrangel/location"
static QString instanceAMBESerialURL = "/sdrangel/ambe/serial"
static QString instanceAMBEDevicesURL = "/sdrangel/ambe/devices"
static QString instancePresetsURL = "/sdrangel/presets"
static QString instancePresetURL = "/sdrangel/preset"
static QString instancePresetFileURL = "/sdrangel/preset/file"
static QString instanceDeviceSetsURL = "/sdrangel/devicesets"
static QString instanceDeviceSetURL = "/sdrangel/deviceset"
static std::regex devicesetURLRe
static std::regex devicesetFocusURLRe
static std::regex devicesetDeviceURLRe
static std::regex devicesetDeviceSettingsURLRe
static std::regex devicesetDeviceRunURLRe
static std::regex devicesetDeviceReportURLRe
static std::regex devicesetChannelURLRe
static std::regex devicesetChannelIndexURLRe
static std::regex devicesetChannelSettingsURLRe
static std::regex devicesetChannelReportURLRe
static std::regex devicesetChannelsReportURLRe
Detailed Description
Definition at line 30 of file webapiadaptersrv.h.
Constructor & Destructor Documentation
WebAPIAdapterSrv()
WebAPIAdapterSrv::WebAPIAdapterSrv (MainCore & mainCore)
Definition at line 63 of file webapiadaptersrv.cpp.
                                                      :
     m_mainCore(mainCore)
 {
 }
~WebAPIAdapterSrv()
WebAPIAdapterSrv::~WebAPIAdapterSrv () virtual
Definition at line 68 of file webapiadaptersrv.cpp.
 {
 }
Member Function Documentation
devicesetChannelDelete()
int WebAPIAdapterSrv::devicesetChannelDelete (int deviceSetIndex, int channelIndex, SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex} (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1667 of file webapiadaptersrv.cpp.
References MainCore::MsgDeleteChannel::create(), SWGSDRangel::SWGSuccessResponse::getMessage(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGErrorResponse::init(), SWGSDRangel::SWGSuccessResponse::init(), MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, MainCore::m_inputMessageQueue, m_mainCore, and MessageQueue::push().
 {
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine) // Rx
         {
             if (channelIndex < deviceSet->getNumberOfRxChannels())
             {
                 MainCore::MsgDeleteChannel *msg = MainCore::MsgDeleteChannel::create(deviceSetIndex, channelIndex, false);
                 m_mainCore.m_inputMessageQueue.push(msg);
                 response.init();
                 *response.getMessage() = QString("Message to delete a channel (MsgDeleteChannel) was submitted successfully");
                 return 202;
             }
             else
             {
                 error.init();
                 *error.getMessage() = QString("There is no channel at index %1. There are %2 Rx channels")
                         .arg(channelIndex)
                         .arg(channelIndex < deviceSet->getNumberOfRxChannels());
                 return 400;
             }
         }
         else if (deviceSet->m_deviceSinkEngine) // Tx
         {
             if (channelIndex < deviceSet->getNumberOfTxChannels())
             {
                 MainCore::MsgDeleteChannel *msg = MainCore::MsgDeleteChannel::create(deviceSetIndex, channelIndex, true);
                 m_mainCore.m_inputMessageQueue.push(msg);
                 response.init();
                 *response.getMessage() = QString("Message to delete a channel (MsgDeleteChannel) was submitted successfully");
                 return 202;
             }
             else
             {
                 error.init();
                 *error.getMessage() = QString("There is no channel at index %1. There are %2 Tx channels")
                         .arg(channelIndex)
                         .arg(channelIndex < deviceSet->getNumberOfRxChannels());
                 return 400;
             }
         }
         else
         {
             error.init();
             *error.getMessage() = QString("DeviceSet error");
             return 500;
         }
     }
     else
     {
         error.init();
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
devicesetChannelPost()
int WebAPIAdapterSrv::devicesetChannelPost (int deviceSetIndex, SWGSDRangel::SWGChannelSettings & query, SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{deviceSetIndex}/channel (POST) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1570 of file webapiadaptersrv.cpp.
References MainCore::MsgAddChannel::create(), SWGSDRangel::SWGChannelSettings::getChannelType(), SWGSDRangel::SWGChannelSettings::getDirection(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGSuccessResponse::getMessage(), PluginManager::getRxChannelRegistrations(), PluginManager::getTxChannelRegistrations(), SWGSDRangel::SWGErrorResponse::init(), SWGSDRangel::SWGSuccessResponse::init(), MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, MainCore::m_inputMessageQueue, m_mainCore, MainCore::m_pluginManager, and MessageQueue::push().
 {
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         if (query.getDirection() == 0) // Single Rx
         {
             if (deviceSet->m_deviceSourceEngine == 0)
             {
                 error.init();
                 *error.getMessage() = QString("Device set at %1 is not a receive device set").arg(deviceSetIndex);
                 return 400;
             }
             PluginAPI::ChannelRegistrations *channelRegistrations = m_mainCore.m_pluginManager->getRxChannelRegistrations();
             int nbRegistrations = channelRegistrations->size();
             int index = 0;
             for (; index < nbRegistrations; index++)
             {
                 if (channelRegistrations->at(index).m_channelId == *query.getChannelType()) {
                     break;
                 }
             }
             if (index < nbRegistrations)
             {
                 MainCore::MsgAddChannel *msg = MainCore::MsgAddChannel::create(deviceSetIndex, index, false);
                 m_mainCore.m_inputMessageQueue.push(msg);
                 response.init();
                 *response.getMessage() = QString("Message to add a channel (MsgAddChannel) was submitted successfully");
                 return 202;
             }
             else
             {
                 error.init();
                 *error.getMessage() = QString("There is no receive channel with id %1").arg(*query.getChannelType());
                 return 404;
             }
         }
         else if (query.getDirection() == 1) // single Tx
         {
             if (deviceSet->m_deviceSinkEngine == 0)
             {
                 error.init();
                 *error.getMessage() = QString("Device set at %1 is not a transmit device set").arg(deviceSetIndex);
                 return 400;
             }
             PluginAPI::ChannelRegistrations *channelRegistrations = m_mainCore.m_pluginManager->getTxChannelRegistrations();
             int nbRegistrations = channelRegistrations->size();
             int index = 0;
             for (; index < nbRegistrations; index++)
             {
                 if (channelRegistrations->at(index).m_channelId == *query.getChannelType()) {
                     break;
                 }
             }
             if (index < nbRegistrations)
             {
                 MainCore::MsgAddChannel *msg = MainCore::MsgAddChannel::create(deviceSetIndex, index, true);
                 m_mainCore.m_inputMessageQueue.push(msg);
                 response.init();
                 *response.getMessage() = QString("Message to add a channel (MsgAddChannel) was submitted successfully");
                 return 202;
             }
             else
             {
                 error.init();
                 *error.getMessage() = QString("There is no transmit channel with id %1").arg(*query.getChannelType());
                 return 404;
             }
         }
         else
         {
             error.init();
             *error.getMessage() = QString("This type of device is not implemented yet");
             return 400;
         }
     }
     else
     {
         error.init();
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
devicesetChannelReportGet()
int WebAPIAdapterSrv::devicesetChannelReportGet (int deviceSetIndex, int channelIndex, SWGSDRangel::SWGChannelReport & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex}/settings (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1793 of file webapiadaptersrv.cpp.
References DeviceAPI::getChanelSinkAPIAt(), DeviceAPI::getChanelSourceAPIAt(), SWGSDRangel::SWGChannelReport::getChannelType(), ChannelAPI::getIdentifier(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGErrorResponse::init(), DeviceSet::m_deviceAPI, MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, m_mainCore, SWGSDRangel::SWGChannelReport::setChannelType(), SWGSDRangel::SWGChannelReport::setDirection(), and ChannelAPI::webapiReportGet().
 {
     error.init();
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine) // Single Rx
         {
             ChannelAPI *channelAPI = deviceSet->m_deviceAPI->getChanelSinkAPIAt(channelIndex);
             if (channelAPI == 0)
             {
                 *error.getMessage() = QString("There is no channel with index %1").arg(channelIndex);
                 return 404;
             }
             else
             {
                 response.setChannelType(new QString());
                 channelAPI->getIdentifier(*response.getChannelType());
                 response.setDirection(0);
                 return channelAPI->webapiReportGet(response, *error.getMessage());
             }
         }
         else if (deviceSet->m_deviceSinkEngine) // Single Tx
         {
             ChannelAPI *channelAPI = deviceSet->m_deviceAPI->getChanelSourceAPIAt(channelIndex);
             if (channelAPI == 0)
             {
                 *error.getMessage() = QString("There is no channel with index %1").arg(channelIndex);
                 return 404;
             }
             else
             {
                 response.setChannelType(new QString());
                 channelAPI->getIdentifier(*response.getChannelType());
                 response.setDirection(1);
                 return channelAPI->webapiReportGet(response, *error.getMessage());
             }
         }
         else
         {
             *error.getMessage() = QString("DeviceSet error");
             return 500;
         }
     }
     else
     {
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
devicesetChannelSettingsGet()
int WebAPIAdapterSrv::devicesetChannelSettingsGet (int deviceSetIndex, int channelIndex, SWGSDRangel::SWGChannelSettings & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex}/settings (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1734 of file webapiadaptersrv.cpp.
References DeviceAPI::getChanelSinkAPIAt(), DeviceAPI::getChanelSourceAPIAt(), SWGSDRangel::SWGChannelSettings::getChannelType(), ChannelAPI::getIdentifier(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGErrorResponse::init(), DeviceSet::m_deviceAPI, MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, m_mainCore, SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), and ChannelAPI::webapiSettingsGet().
 {
     error.init();
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine) // Single Rx
         {
             ChannelAPI *channelAPI = deviceSet->m_deviceAPI->getChanelSinkAPIAt(channelIndex);
             if (channelAPI == 0)
             {
                 *error.getMessage() = QString("There is no channel with index %1").arg(channelIndex);
                 return 404;
             }
             else
             {
                 response.setChannelType(new QString());
                 channelAPI->getIdentifier(*response.getChannelType());
                 response.setDirection(0);
                 return channelAPI->webapiSettingsGet(response, *error.getMessage());
             }
         }
         else if (deviceSet->m_deviceSinkEngine) // Single Tx
         {
             ChannelAPI *channelAPI = deviceSet->m_deviceAPI->getChanelSourceAPIAt(channelIndex);
             if (channelAPI == 0)
             {
                 *error.getMessage() = QString("There is no channel with index %1").arg(channelIndex);
                 return 404;
             }
             else
             {
                 response.setChannelType(new QString());
                 channelAPI->getIdentifier(*response.getChannelType());
                 response.setDirection(1);
                 return channelAPI->webapiSettingsGet(response, *error.getMessage());
             }
         }
         else
         {
             *error.getMessage() = QString("DeviceSet error");
             return 500;
         }
     }
     else
     {
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
devicesetChannelSettingsPutPatch()
int WebAPIAdapterSrv::devicesetChannelSettingsPutPatch (int deviceSetIndex, int channelIndex, bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{deviceSetIndex}/channel/{channelIndex}/settings (PUT, PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1852 of file webapiadaptersrv.cpp.
References arg(), DeviceAPI::getChanelSinkAPIAt(), DeviceAPI::getChanelSourceAPIAt(), SWGSDRangel::SWGChannelSettings::getChannelType(), ChannelAPI::getIdentifier(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGErrorResponse::init(), DeviceSet::m_deviceAPI, MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, m_mainCore, and ChannelAPI::webapiSettingsPutPatch().
 {
     error.init();
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine) // Rx
         {
             ChannelAPI *channelAPI = deviceSet->m_deviceAPI->getChanelSinkAPIAt(channelIndex);
             if (channelAPI == 0)
             {
                 *error.getMessage() = QString("There is no channel with index %1").arg(channelIndex);
                 return 404;
             }
             else
             {
                 QString channelType;
                 channelAPI->getIdentifier(channelType);
                 if (channelType == *response.getChannelType())
                 {
                     return channelAPI->webapiSettingsPutPatch(force, channelSettingsKeys, response, *error.getMessage());
                 }
                 else
                 {
                     *error.getMessage() = QString("There is no channel type %1 at index %2. Found %3.")
                             .arg(*response.getChannelType())
                             .arg(channelIndex)
                             .arg(channelType);
                     return 404;
                 }
             }
         }
         else if (deviceSet->m_deviceSinkEngine) // Tx
         {
             ChannelAPI *channelAPI = deviceSet->m_deviceAPI->getChanelSourceAPIAt(channelIndex);
             if (channelAPI == 0)
             {
                 *error.getMessage() = QString("There is no channel with index %1").arg(channelIndex);
                 return 404;
             }
             else
             {
                 QString channelType;
                 channelAPI->getIdentifier(channelType);
                 if (channelType == *response.getChannelType())
                 {
                     return channelAPI->webapiSettingsPutPatch(force, channelSettingsKeys, response, *error.getMessage());
                 }
                 else
                 {
                     *error.getMessage() = QString("There is no channel type %1 at index %2. Found %3.")
                             .arg(*response.getChannelType())
                             .arg(channelIndex)
                             .arg(channelType);
                     return 404;
                 }
             }
         }
         else
         {
             *error.getMessage() = QString("DeviceSet error");
             return 500;
         }
     }
     else
     {
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
devicesetChannelsReportGet()
int WebAPIAdapterSrv::devicesetChannelsReportGet (int deviceSetIndex, SWGSDRangel::SWGChannelsDetail & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/channels/report (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1549 of file webapiadaptersrv.cpp.
References getChannelsDetail(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGErrorResponse::init(), MainCore::m_deviceSets, and m_mainCore.
 {
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         const DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         getChannelsDetail(&response, deviceSet);
         return 200;
     }
     else
     {
         error.init();
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
devicesetDevicePut()
int WebAPIAdapterSrv::devicesetDevicePut (int deviceSetIndex, SWGSDRangel::SWGDeviceListItem & query, SWGSDRangel::SWGDeviceListItem & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1199 of file webapiadaptersrv.cpp.
References MainCore::MsgSetDevice::create(), PluginInterface::SamplingDevice::deviceItemIndex, PluginInterface::SamplingDevice::deviceNbItems, PluginInterface::SamplingDevice::displayedName, SWGSDRangel::SWGDeviceListItem::getDeviceStreamIndex(), SWGSDRangel::SWGDeviceListItem::getDirection(), SWGSDRangel::SWGDeviceListItem::getDisplayedName(), SWGSDRangel::SWGDeviceListItem::getHwType(), SWGSDRangel::SWGErrorResponse::getMessage(), DeviceEnumerator::getNbRxSamplingDevices(), DeviceEnumerator::getNbTxSamplingDevices(), DeviceEnumerator::getRxSamplingDevice(), SWGSDRangel::SWGDeviceListItem::getSequence(), SWGSDRangel::SWGDeviceListItem::getSerial(), DeviceEnumerator::getTxSamplingDevice(), PluginInterface::SamplingDevice::hardwareId, i, SWGSDRangel::SWGErrorResponse::init(), SWGSDRangel::SWGDeviceListItem::init(), DeviceEnumerator::instance(), MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, MainCore::m_inputMessageQueue, m_mainCore, MessageQueue::push(), PluginInterface::SamplingDevice::sequence, PluginInterface::SamplingDevice::serial, SWGSDRangel::SWGDeviceListItem::setDeviceNbStreams(), SWGSDRangel::SWGDeviceListItem::setDeviceSetIndex(), SWGSDRangel::SWGDeviceListItem::setDeviceStreamIndex(), SWGSDRangel::SWGDeviceListItem::setDirection(), SWGSDRangel::SWGDeviceListItem::setIndex(), and SWGSDRangel::SWGDeviceListItem::setSequence().
 {
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         if ((query.getDirection() != 1) && (deviceSet->m_deviceSinkEngine))
         {
             error.init();
             *error.getMessage() = QString("Device type and device set type (Tx) mismatch");
             return 404;
         }
         if ((query.getDirection() != 0) && (deviceSet->m_deviceSourceEngine))
         {
             error.init();
             *error.getMessage() = QString("Device type and device set type (Rx) mismatch");
             return 404;
         }
         int nbSamplingDevices;
         if (query.getDirection() == 0) {
             nbSamplingDevices = DeviceEnumerator::instance()->getNbRxSamplingDevices();
         } else if (query.getDirection() == 1) {
             nbSamplingDevices = DeviceEnumerator::instance()->getNbTxSamplingDevices();
         } else {
             nbSamplingDevices = 0; // TODO: not implemented yet
         }
         for (int i = 0; i < nbSamplingDevices; i++)
         {
             int direction;
             const PluginInterface::SamplingDevice *samplingDevice;
             if (query.getDirection() == 0)
             {
                 direction = 0;
                 samplingDevice = DeviceEnumerator::instance()->getRxSamplingDevice(i);
             }
             else if (query.getDirection() == 1)
             {
                 direction = 1;
                 samplingDevice = DeviceEnumerator::instance()->getTxSamplingDevice(i);
             }
             else
             {
                 continue; // TODO: any device (2) not supported yet
             }
             if (query.getDisplayedName() && (*query.getDisplayedName() != samplingDevice->displayedName)) {
                 continue;
             }
             if (query.getHwType() && (*query.getHwType() != samplingDevice->hardwareId)) {
                 continue;
             }
             if ((query.getSequence() >= 0) && (query.getSequence() != samplingDevice->sequence)) {
                 continue;
             }
             if (query.getSerial() && (*query.getSerial() != samplingDevice->serial)) {
                 continue;
             }
             if ((query.getDeviceStreamIndex() >= 0) && (query.getDeviceStreamIndex() != samplingDevice->deviceItemIndex)) {
                 continue;
             }
             MainCore::MsgSetDevice *msg = MainCore::MsgSetDevice::create(deviceSetIndex, i, query.getDirection());
             m_mainCore.m_inputMessageQueue.push(msg);
             response.init();
             *response.getDisplayedName() = samplingDevice->displayedName;
             *response.getHwType() = samplingDevice->hardwareId;
             *response.getSerial() = samplingDevice->serial;
             response.setSequence(samplingDevice->sequence);
             response.setDirection(direction);
             response.setDeviceNbStreams(samplingDevice->deviceNbItems);
             response.setDeviceStreamIndex(samplingDevice->deviceItemIndex);
             response.setDeviceSetIndex(deviceSetIndex);
             response.setIndex(i);
             return 202;
         }
         error.init();
         *error.getMessage() = QString("Device not found");
         return 404;
     }
     else
     {
         error.init();
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
devicesetDeviceReportGet()
int WebAPIAdapterSrv::devicesetDeviceReportGet (int deviceSetIndex, SWGSDRangel::SWGDeviceReport & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device/report (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1511 of file webapiadaptersrv.cpp.
References DeviceAPI::getHardwareId(), SWGSDRangel::SWGErrorResponse::getMessage(), DeviceAPI::getSampleSink(), DeviceAPI::getSampleSource(), SWGSDRangel::SWGErrorResponse::init(), DeviceSet::m_deviceAPI, MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, m_mainCore, SWGSDRangel::SWGDeviceReport::setDeviceHwType(), SWGSDRangel::SWGDeviceReport::setDirection(), DeviceSampleSink::webapiReportGet(), and DeviceSampleSource::webapiReportGet().
 {
     error.init();
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine) // Single Rx
         {
             response.setDeviceHwType(new QString(deviceSet->m_deviceAPI->getHardwareId()));
             response.setDirection(0);
             DeviceSampleSource *source = deviceSet->m_deviceAPI->getSampleSource();
             return source->webapiReportGet(response, *error.getMessage());
         }
         else if (deviceSet->m_deviceSinkEngine) // Single Tx
         {
             response.setDeviceHwType(new QString(deviceSet->m_deviceAPI->getHardwareId()));
             response.setDirection(1);
             DeviceSampleSink *sink = deviceSet->m_deviceAPI->getSampleSink();
             return sink->webapiReportGet(response, *error.getMessage());
         }
         else
         {
             *error.getMessage() = QString("DeviceSet error");
             return 500;
         }
     }
     else
     {
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
devicesetDeviceRunDelete()
int WebAPIAdapterSrv::devicesetDeviceRunDelete (int deviceSetIndex, SWGSDRangel::SWGDeviceState & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device/run (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1475 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGErrorResponse::getMessage(), DeviceAPI::getSampleSink(), DeviceAPI::getSampleSource(), SWGSDRangel::SWGErrorResponse::init(), SWGSDRangel::SWGDeviceState::init(), DeviceSet::m_deviceAPI, MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, m_mainCore, DeviceSampleSink::webapiRun(), and DeviceSampleSource::webapiRun().
 {
     error.init();
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine) // Rx
         {
             DeviceSampleSource *source = deviceSet->m_deviceAPI->getSampleSource();
             response.init();
             return source->webapiRun(false, response, *error.getMessage());
        }
         else if (deviceSet->m_deviceSinkEngine) // Tx
         {
             DeviceSampleSink *sink = deviceSet->m_deviceAPI->getSampleSink();
             response.init();
             return sink->webapiRun(false, response, *error.getMessage());
         }
         else
         {
             *error.getMessage() = QString("DeviceSet error");
             return 500;
         }
     }
     else
     {
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
devicesetDeviceRunGet()
int WebAPIAdapterSrv::devicesetDeviceRunGet (int deviceSetIndex, SWGSDRangel::SWGDeviceState & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device/run (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1403 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGErrorResponse::getMessage(), DeviceAPI::getSampleSink(), DeviceAPI::getSampleSource(), SWGSDRangel::SWGErrorResponse::init(), SWGSDRangel::SWGDeviceState::init(), DeviceSet::m_deviceAPI, MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, m_mainCore, DeviceSampleSink::webapiRunGet(), and DeviceSampleSource::webapiRunGet().
 {
     error.init();
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine) // Rx
         {
             DeviceSampleSource *source = deviceSet->m_deviceAPI->getSampleSource();
             response.init();
             return source->webapiRunGet(response, *error.getMessage());
         }
         else if (deviceSet->m_deviceSinkEngine) // Tx
         {
             DeviceSampleSink *sink = deviceSet->m_deviceAPI->getSampleSink();
             response.init();
             return sink->webapiRunGet(response, *error.getMessage());
         }
         else
         {
             *error.getMessage() = QString("DeviceSet error");
             return 500;
         }
     }
     else
     {
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
devicesetDeviceRunPost()
int WebAPIAdapterSrv::devicesetDeviceRunPost (int deviceSetIndex, SWGSDRangel::SWGDeviceState & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device/run (POST) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1439 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGErrorResponse::getMessage(), DeviceAPI::getSampleSink(), DeviceAPI::getSampleSource(), SWGSDRangel::SWGErrorResponse::init(), SWGSDRangel::SWGDeviceState::init(), DeviceSet::m_deviceAPI, MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, m_mainCore, DeviceSampleSink::webapiRun(), and DeviceSampleSource::webapiRun().
 {
     error.init();
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine) // Rx
         {
             DeviceSampleSource *source = deviceSet->m_deviceAPI->getSampleSource();
             response.init();
             return source->webapiRun(true, response, *error.getMessage());
         }
         else if (deviceSet->m_deviceSinkEngine) // Tx
         {
             DeviceSampleSink *sink = deviceSet->m_deviceAPI->getSampleSink();
             response.init();
             return sink->webapiRun(true, response, *error.getMessage());
         }
         else
         {
             *error.getMessage() = QString("DeviceSet error");
             return 500;
         }
     }
     else
     {
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
devicesetDeviceSettingsGet()
int WebAPIAdapterSrv::devicesetDeviceSettingsGet (int deviceSetIndex, SWGSDRangel::SWGDeviceSettings & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device/settings (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1303 of file webapiadaptersrv.cpp.
References DeviceAPI::getHardwareId(), SWGSDRangel::SWGErrorResponse::getMessage(), DeviceAPI::getSampleSink(), DeviceAPI::getSampleSource(), SWGSDRangel::SWGErrorResponse::init(), DeviceSet::m_deviceAPI, MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, m_mainCore, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), DeviceSampleSink::webapiSettingsGet(), and DeviceSampleSource::webapiSettingsGet().
 {
     error.init();
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine) // Single Rx
         {
             response.setDeviceHwType(new QString(deviceSet->m_deviceAPI->getHardwareId()));
             response.setDirection(0);
             DeviceSampleSource *source = deviceSet->m_deviceAPI->getSampleSource();
             return source->webapiSettingsGet(response, *error.getMessage());
         }
         else if (deviceSet->m_deviceSinkEngine) // Single Tx
         {
             response.setDeviceHwType(new QString(deviceSet->m_deviceAPI->getHardwareId()));
             response.setDirection(1);
             DeviceSampleSink *sink = deviceSet->m_deviceAPI->getSampleSink();
             return sink->webapiSettingsGet(response, *error.getMessage());
         }
         else
         {
             *error.getMessage() = QString("DeviceSet error");
             return 500;
         }
     }
     else
     {
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
devicesetDeviceSettingsPutPatch()
int WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch (int deviceSetIndex, bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/device/settings (PUT, PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1341 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGDeviceSettings::getDeviceHwType(), SWGSDRangel::SWGDeviceSettings::getDirection(), DeviceAPI::getHardwareId(), SWGSDRangel::SWGErrorResponse::getMessage(), DeviceAPI::getSampleSink(), DeviceAPI::getSampleSource(), SWGSDRangel::SWGErrorResponse::init(), DeviceSet::m_deviceAPI, MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, m_mainCore, DeviceSampleSink::webapiSettingsPutPatch(), and DeviceSampleSource::webapiSettingsPutPatch().
 {
     error.init();
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine) // Single Rx
         {
             if (response.getDirection() != 0)
             {
                 *error.getMessage() = QString("Single Rx device found but other type of device requested");
                 return 400;
             }
             if (deviceSet->m_deviceAPI->getHardwareId() != *response.getDeviceHwType())
             {
                 *error.getMessage() = QString("Device mismatch. Found %1 input").arg(deviceSet->m_deviceAPI->getHardwareId());
                 return 400;
             }
             else
             {
                 DeviceSampleSource *source = deviceSet->m_deviceAPI->getSampleSource();
                 return source->webapiSettingsPutPatch(force, deviceSettingsKeys, response, *error.getMessage());
             }
         }
         else if (deviceSet->m_deviceSinkEngine) // Single Tx
         {
             if (response.getDirection() != 1)
             {
                 *error.getMessage() = QString("Single Tx device found but other type of device requested");
                 return 400;
             }
             else if (deviceSet->m_deviceAPI->getHardwareId() != *response.getDeviceHwType())
             {
                 *error.getMessage() = QString("Device mismatch. Found %1 output").arg(deviceSet->m_deviceAPI->getHardwareId());
                 return 400;
             }
             else
             {
                 DeviceSampleSink *sink = deviceSet->m_deviceAPI->getSampleSink();
                 return sink->webapiSettingsPutPatch(force, deviceSettingsKeys, response, *error.getMessage());
             }
         }
         else
         {
             *error.getMessage() = QString("DeviceSet error");
             return 500;
         }
     }
     else
     {
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
devicesetFocusPatch()
int WebAPIAdapterSrv::devicesetFocusPatch (int deviceSetIndex, SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{devicesetIndex}/focus (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1190 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGErrorResponse::getMessage().
 {
     *error.getMessage() = QString("Not supported in server instance");
     return 400;
 }
devicesetGet()
int WebAPIAdapterSrv::devicesetGet (int deviceSetIndex, SWGSDRangel::SWGDeviceSet & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset/{devicesetIndex} (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1169 of file webapiadaptersrv.cpp.
References getDeviceSet(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGErrorResponse::init(), MainCore::m_deviceSets, and m_mainCore.
 {
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_mainCore.m_deviceSets.size()))
     {
         const DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         getDeviceSet(&response, deviceSet, deviceSetIndex);
         return 200;
     }
     else
     {
         error.init();
         *error.getMessage() = QString("There is no device set with index %1").arg(deviceSetIndex);
         return 404;
     }
 }
getChannelsDetail()
void WebAPIAdapterSrv::getChannelsDetail (SWGSDRangel::SWGChannelsDetail * channelsDetail, const DeviceSet * deviceSet) private
Definition at line 2023 of file webapiadaptersrv.cpp.
References ChannelAPI::getCenterFrequency(), DeviceAPI::getChanelSinkAPIAt(), DeviceAPI::getChanelSourceAPIAt(), SWGSDRangel::SWGChannelsDetail::getChannelcount(), SWGSDRangel::SWGChannelsDetail::getChannels(), ChannelAPI::getIdentifier(), ChannelAPI::getIndexInDeviceSet(), DeviceAPI::getNbSinkChannels(), DeviceAPI::getNbSourceChannels(), ChannelAPI::getTitle(), ChannelAPI::getUID(), i, SWGSDRangel::SWGChannelsDetail::init(), DeviceSet::m_deviceAPI, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, SWGSDRangel::SWGChannelsDetail::setChannelcount(), and ChannelAPI::webapiReportGet().
Referenced by devicesetChannelsReportGet().
 {
     channelsDetail->init();
     SWGSDRangel::SWGChannelReport *channelReport;
     QString channelReportError;
     if (deviceSet->m_deviceSinkEngine) // Tx data
     {
         channelsDetail->setChannelcount(deviceSet->m_deviceAPI->getNbSourceChannels());
         QList<SWGSDRangel::SWGChannel*> *channels = channelsDetail->getChannels();
         for (int i = 0; i <  channelsDetail->getChannelcount(); i++)
         {
             channels->append(new SWGSDRangel::SWGChannel);
             channels->back()->init();
             ChannelAPI *channel = deviceSet->m_deviceAPI->getChanelSourceAPIAt(i);
             channels->back()->setDeltaFrequency(channel->getCenterFrequency());
             channels->back()->setIndex(channel->getIndexInDeviceSet());
             channels->back()->setUid(channel->getUID());
             channel->getIdentifier(*channels->back()->getId());
             channel->getTitle(*channels->back()->getTitle());
             channelReport = new SWGSDRangel::SWGChannelReport();
             if (channel->webapiReportGet(*channelReport, channelReportError) != 501) {
                 channels->back()->setReport(channelReport);
             } else {
                 delete channelReport;
             }
         }
     }
     if (deviceSet->m_deviceSourceEngine) // Rx data
     {
         channelsDetail->setChannelcount(deviceSet->m_deviceAPI->getNbSinkChannels());
         QList<SWGSDRangel::SWGChannel*> *channels = channelsDetail->getChannels();
         for (int i = 0; i <  channelsDetail->getChannelcount(); i++)
         {
             channels->append(new SWGSDRangel::SWGChannel);
             channels->back()->init();
             ChannelAPI *channel = deviceSet->m_deviceAPI->getChanelSinkAPIAt(i);
             channels->back()->setDeltaFrequency(channel->getCenterFrequency());
             channels->back()->setIndex(channel->getIndexInDeviceSet());
             channels->back()->setUid(channel->getUID());
             channel->getIdentifier(*channels->back()->getId());
             channel->getTitle(*channels->back()->getTitle());
             channelReport = new SWGSDRangel::SWGChannelReport();
             if (channel->webapiReportGet(*channelReport, channelReportError) != 501) {
                 channels->back()->setReport(channelReport);
             } else {
                 delete channelReport;
             }
         }
     }
 }
getDeviceSet()
void WebAPIAdapterSrv::getDeviceSet (SWGSDRangel::SWGDeviceSet * swgDeviceSet, const DeviceSet * deviceSet, int deviceUISetIndex) private
Definition at line 1951 of file webapiadaptersrv.cpp.
References ChannelAPI::getCenterFrequency(), DeviceSampleSink::getCenterFrequency(), DeviceSampleSource::getCenterFrequency(), DeviceAPI::getChanelSinkAPIAt(), DeviceAPI::getChanelSourceAPIAt(), SWGSDRangel::SWGDeviceSet::getChannelcount(), SWGSDRangel::SWGDeviceSet::getChannels(), DeviceAPI::getDeviceEngineStateStr(), DeviceAPI::getDeviceItemIndex(), DeviceAPI::getDeviceNbItems(), DeviceAPI::getHardwareId(), SWGSDRangel::SWGSamplingDevice::getHwType(), ChannelAPI::getIdentifier(), ChannelAPI::getIndexInDeviceSet(), DeviceAPI::getNbSinkChannels(), DeviceAPI::getNbSourceChannels(), DeviceSampleSink::getSampleRate(), DeviceSampleSource::getSampleRate(), SWGSDRangel::SWGDeviceSet::getSamplingDevice(), DeviceAPI::getSamplingDeviceSequence(), DeviceAPI::getSamplingDeviceSerial(), SWGSDRangel::SWGSamplingDevice::getSerial(), DSPDeviceSinkEngine::getSink(), DSPDeviceSourceEngine::getSource(), SWGSDRangel::SWGSamplingDevice::getState(), ChannelAPI::getTitle(), ChannelAPI::getUID(), i, SWGSDRangel::SWGSamplingDevice::init(), SWGSDRangel::SWGDeviceSet::init(), DeviceSet::m_deviceAPI, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, SWGSDRangel::SWGSamplingDevice::setBandwidth(), SWGSDRangel::SWGSamplingDevice::setCenterFrequency(), SWGSDRangel::SWGDeviceSet::setChannelcount(), SWGSDRangel::SWGSamplingDevice::setDeviceNbStreams(), SWGSDRangel::SWGSamplingDevice::setDeviceStreamIndex(), SWGSDRangel::SWGSamplingDevice::setDirection(), SWGSDRangel::SWGSamplingDevice::setIndex(), and SWGSDRangel::SWGSamplingDevice::setSequence().
Referenced by devicesetGet(), and getDeviceSetList().
 {
     swgDeviceSet->init();
     SWGSDRangel::SWGSamplingDevice *samplingDevice = swgDeviceSet->getSamplingDevice();
     samplingDevice->init();
     samplingDevice->setIndex(deviceUISetIndex);
     if (deviceSet->m_deviceSinkEngine) // Single Tx data
     {
         samplingDevice->setDirection(1);
         *samplingDevice->getHwType() = deviceSet->m_deviceAPI->getHardwareId();
         *samplingDevice->getSerial() = deviceSet->m_deviceAPI->getSamplingDeviceSerial();
         samplingDevice->setSequence(deviceSet->m_deviceAPI->getSamplingDeviceSequence());
         samplingDevice->setDeviceNbStreams(deviceSet->m_deviceAPI->getDeviceNbItems());
         samplingDevice->setDeviceStreamIndex(deviceSet->m_deviceAPI->getDeviceItemIndex());
         deviceSet->m_deviceAPI->getDeviceEngineStateStr(*samplingDevice->getState());
         DeviceSampleSink *sampleSink = deviceSet->m_deviceSinkEngine->getSink();
         if (sampleSink) {
             samplingDevice->setCenterFrequency(sampleSink->getCenterFrequency());
             samplingDevice->setBandwidth(sampleSink->getSampleRate());
         }
         swgDeviceSet->setChannelcount(deviceSet->m_deviceAPI->getNbSourceChannels());
         QList<SWGSDRangel::SWGChannel*> *channels = swgDeviceSet->getChannels();
         for (int i = 0; i <  swgDeviceSet->getChannelcount(); i++)
         {
             channels->append(new SWGSDRangel::SWGChannel);
             channels->back()->init();
             ChannelAPI *channel = deviceSet->m_deviceAPI->getChanelSourceAPIAt(i);
             channels->back()->setDeltaFrequency(channel->getCenterFrequency());
             channels->back()->setIndex(channel->getIndexInDeviceSet());
             channels->back()->setUid(channel->getUID());
             channel->getIdentifier(*channels->back()->getId());
             channel->getTitle(*channels->back()->getTitle());
         }
     }
     if (deviceSet->m_deviceSourceEngine) // Single Rx data
     {
         samplingDevice->setDirection(0);
         *samplingDevice->getHwType() = deviceSet->m_deviceAPI->getHardwareId();
         *samplingDevice->getSerial() = deviceSet->m_deviceAPI->getSamplingDeviceSerial();
         samplingDevice->setSequence(deviceSet->m_deviceAPI->getSamplingDeviceSequence());
         samplingDevice->setDeviceNbStreams(deviceSet->m_deviceAPI->getDeviceNbItems());
         samplingDevice->setDeviceStreamIndex(deviceSet->m_deviceAPI->getDeviceItemIndex());
         deviceSet->m_deviceAPI->getDeviceEngineStateStr(*samplingDevice->getState());
         DeviceSampleSource *sampleSource = deviceSet->m_deviceSourceEngine->getSource();
         if (sampleSource) {
             samplingDevice->setCenterFrequency(sampleSource->getCenterFrequency());
             samplingDevice->setBandwidth(sampleSource->getSampleRate());
         }
         swgDeviceSet->setChannelcount(deviceSet->m_deviceAPI->getNbSinkChannels());
         QList<SWGSDRangel::SWGChannel*> *channels = swgDeviceSet->getChannels();
         for (int i = 0; i <  swgDeviceSet->getChannelcount(); i++)
         {
             channels->append(new SWGSDRangel::SWGChannel);
             channels->back()->init();
             ChannelAPI *channel = deviceSet->m_deviceAPI->getChanelSinkAPIAt(i);
             channels->back()->setDeltaFrequency(channel->getCenterFrequency());
             channels->back()->setIndex(channel->getIndexInDeviceSet());
             channels->back()->setUid(channel->getUID());
             channel->getIdentifier(*channels->back()->getId());
             channel->getTitle(*channels->back()->getTitle());
         }
     }
 }
getDeviceSetList()
void WebAPIAdapterSrv::getDeviceSetList (SWGSDRangel::SWGDeviceSetList * deviceSetList) private
Definition at line 1935 of file webapiadaptersrv.cpp.
References getDeviceSet(), SWGSDRangel::SWGDeviceSetList::getDeviceSets(), i, SWGSDRangel::SWGDeviceSetList::init(), MainCore::m_deviceSets, m_mainCore, and SWGSDRangel::SWGDeviceSetList::setDevicesetcount().
Referenced by instanceDeviceSetsGet(), and instanceSummary().
 {
     deviceSetList->init();
     deviceSetList->setDevicesetcount((int) m_mainCore.m_deviceSets.size());
     std::vector<DeviceSet*>::const_iterator it = m_mainCore.m_deviceSets.begin();
     for (int i = 0; it != m_mainCore.m_deviceSets.end(); ++it, i++)
     {
         QList<SWGSDRangel::SWGDeviceSet*> *deviceSets = deviceSetList->getDeviceSets();
         deviceSets->append(new SWGSDRangel::SWGDeviceSet());
         getDeviceSet(deviceSets->back(), *it, i);
     }
 }
getMsgTypeFromString()
QtMsgType WebAPIAdapterSrv::getMsgTypeFromString (const QString & msgTypeString) static private
Definition at line 2082 of file webapiadaptersrv.cpp.
Referenced by instanceLoggingPut().
 {
     if (msgTypeString == "debug") {
         return QtDebugMsg;
     } else if (msgTypeString == "info") {
         return QtInfoMsg;
     } else if (msgTypeString == "warning") {
         return QtWarningMsg;
     } else if (msgTypeString == "error") {
         return QtCriticalMsg;
     } else {
         return QtDebugMsg;
     }
 }
getMsgTypeString()
void WebAPIAdapterSrv::getMsgTypeString (const QtMsgType & msgType, QString & level) static private
Definition at line 2097 of file webapiadaptersrv.cpp.
Referenced by instanceLoggingPut().
 {
     switch (msgType)
     {
     case QtDebugMsg:
         levelStr = "debug";
         break;
     case QtInfoMsg:
         levelStr = "info";
         break;
     case QtWarningMsg:
         levelStr = "warning";
         break;
     case QtCriticalMsg:
     case QtFatalMsg:
         levelStr = "error";
         break;
     default:
         levelStr = "debug";
         break;
     }
 }
instanceAMBEDevicesDelete()
int WebAPIAdapterSrv::instanceAMBEDevicesDelete (SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/ambe/devices (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 695 of file webapiadaptersrv.cpp.
References DSPEngine::getAMBEEngine(), SWGSDRangel::SWGSuccessResponse::getMessage(), SWGSDRangel::SWGSuccessResponse::init(), MainCore::m_dspEngine, m_mainCore, and AMBEEngine::releaseAll().
 {
     (void) error;
     m_mainCore.m_dspEngine->getAMBEEngine()->releaseAll();
     response.init();
     *response.getMessage() = QString("All AMBE devices released");
     return 200;
 }
instanceAMBEDevicesGet()
int WebAPIAdapterSrv::instanceAMBEDevicesGet (SWGSDRangel::SWGAMBEDevices & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/ambe/devices (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 669 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGAMBEDevices::getAmbeDevices(), DSPEngine::getDVSerialNames(), SWGSDRangel::SWGAMBEDevices::init(), MainCore::m_dspEngine, m_mainCore, and SWGSDRangel::SWGAMBEDevices::setNbDevices().
Referenced by instanceAMBEDevicesPatch(), and instanceAMBEDevicesPut().
 {
     (void) error;
     response.init();
     std::vector<std::string> deviceNames;
     m_mainCore.m_dspEngine->getDVSerialNames(deviceNames);
     response.setNbDevices((int) deviceNames.size());
     QList<SWGSDRangel::SWGAMBEDevice*> *deviceNamesList = response.getAmbeDevices();
     std::vector<std::string>::iterator it = deviceNames.begin();
     while (it != deviceNames.end())
     {
         deviceNamesList->append(new SWGSDRangel::SWGAMBEDevice);
         deviceNamesList->back()->init();
         *deviceNamesList->back()->getDeviceRef() = QString::fromStdString(*it);
         deviceNamesList->back()->setDelete(0);
         ++it;
     }
     return 200;
 }
instanceAMBEDevicesPatch()
int WebAPIAdapterSrv::instanceAMBEDevicesPatch (SWGSDRangel::SWGAMBEDevices & query, SWGSDRangel::SWGAMBEDevices & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/ambe/devices (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 725 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGAMBEDevices::getAmbeDevices(), DSPEngine::getAMBEEngine(), instanceAMBEDevicesGet(), MainCore::m_dspEngine, m_mainCore, AMBEEngine::registerController(), and AMBEEngine::releaseController().
 {
     QList<SWGSDRangel::SWGAMBEDevice *> *ambeList = query.getAmbeDevices();
     for (QList<SWGSDRangel::SWGAMBEDevice *>::const_iterator it = ambeList->begin(); it != ambeList->end(); ++it)
     {
         if ((*it)->getDelete()) {
             m_mainCore.m_dspEngine->getAMBEEngine()->releaseController((*it)->getDeviceRef()->toStdString());
         } else {
             m_mainCore.m_dspEngine->getAMBEEngine()->registerController((*it)->getDeviceRef()->toStdString());
         }
     }
     instanceAMBEDevicesGet(response, error);
     return 200;
 }
instanceAMBEDevicesPut()
int WebAPIAdapterSrv::instanceAMBEDevicesPut (SWGSDRangel::SWGAMBEDevices & query, SWGSDRangel::SWGAMBEDevices & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/ambe/devices (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 708 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGAMBEDevices::getAmbeDevices(), DSPEngine::getAMBEEngine(), instanceAMBEDevicesGet(), MainCore::m_dspEngine, m_mainCore, AMBEEngine::registerController(), and AMBEEngine::releaseAll().
 {
     m_mainCore.m_dspEngine->getAMBEEngine()->releaseAll();
     QList<SWGSDRangel::SWGAMBEDevice *> *ambeList = query.getAmbeDevices();
     for (QList<SWGSDRangel::SWGAMBEDevice *>::const_iterator it = ambeList->begin(); it != ambeList->end(); ++it) {
         m_mainCore.m_dspEngine->getAMBEEngine()->registerController((*it)->getDeviceRef()->toStdString());
     }
     instanceAMBEDevicesGet(response, error);
     return 200;
 }
instanceAMBESerialGet()
int WebAPIAdapterSrv::instanceAMBESerialGet (SWGSDRangel::SWGDVSerialDevices & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/ambe/serial (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 638 of file webapiadaptersrv.cpp.
References DSPEngine::getAMBEEngine(), SWGSDRangel::SWGDVSerialDevices::getDvSerialDevices(), SWGSDRangel::SWGDVSerialDevices::init(), MainCore::m_dspEngine, m_mainCore, AMBEEngine::scan(), and SWGSDRangel::SWGDVSerialDevices::setNbDevices().
 {
     (void) error;
     response.init();
     std::vector<std::string> deviceNames;
     std::vector<QString> qDeviceNames;
     m_mainCore.m_dspEngine->getAMBEEngine()->scan(qDeviceNames);
     for (std::vector<QString>::const_iterator it = qDeviceNames.begin(); it != qDeviceNames.end(); ++it) {
         deviceNames.push_back(it->toStdString());
     }
     response.setNbDevices((int) deviceNames.size());
     QList<SWGSDRangel::SWGDVSerialDevice*> *deviceNamesList = response.getDvSerialDevices();
     std::vector<std::string>::iterator it = deviceNames.begin();
     while (it != deviceNames.end())
     {
         deviceNamesList->append(new SWGSDRangel::SWGDVSerialDevice);
         deviceNamesList->back()->init();
         *deviceNamesList->back()->getDeviceName() = QString::fromStdString(*it);
         ++it;
     }
     return 200;
 }
instanceAudioGet()
int WebAPIAdapterSrv::instanceAudioGet (SWGSDRangel::SWGAudioDevices & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/audio (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 289 of file webapiadaptersrv.cpp.
References AudioDeviceManager::OutputDeviceInfo::copyToUDP, DSPEngine::getAudioDeviceManager(), AudioDeviceManager::getInputDeviceInfo(), SWGSDRangel::SWGAudioDevices::getInputDevices(), AudioDeviceManager::getInputDevices(), AudioDeviceManager::getOutputDeviceInfo(), SWGSDRangel::SWGAudioDevices::getOutputDevices(), AudioDeviceManager::getOutputDevices(), i, SWGSDRangel::SWGAudioDevices::init(), AudioDeviceManager::m_defaultDeviceName, MainCore::m_dspEngine, m_mainCore, AudioDeviceManager::InputDeviceInfo::resetToDefaults(), AudioDeviceManager::OutputDeviceInfo::resetToDefaults(), AudioDeviceManager::InputDeviceInfo::sampleRate, AudioDeviceManager::OutputDeviceInfo::sampleRate, SWGSDRangel::SWGAudioDevices::setNbInputDevices(), SWGSDRangel::SWGAudioDevices::setNbOutputDevices(), AudioDeviceManager::OutputDeviceInfo::udpAddress, AudioDeviceManager::OutputDeviceInfo::udpChannelCodec, AudioDeviceManager::OutputDeviceInfo::udpChannelMode, AudioDeviceManager::OutputDeviceInfo::udpDecimationFactor, AudioDeviceManager::OutputDeviceInfo::udpPort, AudioDeviceManager::OutputDeviceInfo::udpUseRTP, and AudioDeviceManager::InputDeviceInfo::volume.
 {
     const QList<QAudioDeviceInfo>& audioInputDevices = m_mainCore.m_dspEngine->getAudioDeviceManager()->getInputDevices();
     const QList<QAudioDeviceInfo>& audioOutputDevices = m_mainCore.m_dspEngine->getAudioDeviceManager()->getOutputDevices();
     int nbInputDevices = audioInputDevices.size();
     int nbOutputDevices = audioOutputDevices.size();
     response.init();
     response.setNbInputDevices(nbInputDevices);
     response.setNbOutputDevices(nbOutputDevices);
     QList<SWGSDRangel::SWGAudioInputDevice*> *inputDevices = response.getInputDevices();
     QList<SWGSDRangel::SWGAudioOutputDevice*> *outputDevices = response.getOutputDevices();
     AudioDeviceManager::InputDeviceInfo inputDeviceInfo;
     AudioDeviceManager::OutputDeviceInfo outputDeviceInfo;
     // system default input device
     inputDevices->append(new SWGSDRangel::SWGAudioInputDevice);
     inputDevices->back()->init();
     bool found = m_mainCore.m_dspEngine->getAudioDeviceManager()->getInputDeviceInfo(AudioDeviceManager::m_defaultDeviceName, inputDeviceInfo);
     *inputDevices->back()->getName() = AudioDeviceManager::m_defaultDeviceName;
     inputDevices->back()->setIndex(-1);
     inputDevices->back()->setSampleRate(inputDeviceInfo.sampleRate);
     inputDevices->back()->setIsSystemDefault(0);
     inputDevices->back()->setDefaultUnregistered(found ? 0 : 1);
     inputDevices->back()->setVolume(inputDeviceInfo.volume);
     // real input devices
     for (int i = 0; i < nbInputDevices; i++)
     {
         inputDevices->append(new SWGSDRangel::SWGAudioInputDevice);
         inputDevices->back()->init();
         inputDeviceInfo.resetToDefaults();
         found = m_mainCore.m_dspEngine->getAudioDeviceManager()->getInputDeviceInfo(audioInputDevices.at(i).deviceName(), inputDeviceInfo);
         *inputDevices->back()->getName() = audioInputDevices.at(i).deviceName();
         inputDevices->back()->setIndex(i);
         inputDevices->back()->setSampleRate(inputDeviceInfo.sampleRate);
         inputDevices->back()->setIsSystemDefault(audioInputDevices.at(i).deviceName() == QAudioDeviceInfo::defaultInputDevice().deviceName() ? 1 : 0);
         inputDevices->back()->setDefaultUnregistered(found ? 0 : 1);
         inputDevices->back()->setVolume(inputDeviceInfo.volume);
     }
     // system default output device
     outputDevices->append(new SWGSDRangel::SWGAudioOutputDevice);
     outputDevices->back()->init();
     found = m_mainCore.m_dspEngine->getAudioDeviceManager()->getOutputDeviceInfo(AudioDeviceManager::m_defaultDeviceName, outputDeviceInfo);
     *outputDevices->back()->getName() = AudioDeviceManager::m_defaultDeviceName;
     outputDevices->back()->setIndex(-1);
     outputDevices->back()->setSampleRate(outputDeviceInfo.sampleRate);
     inputDevices->back()->setIsSystemDefault(0);
     outputDevices->back()->setDefaultUnregistered(found ? 0 : 1);
     outputDevices->back()->setCopyToUdp(outputDeviceInfo.copyToUDP ? 1 : 0);
     outputDevices->back()->setUdpUsesRtp(outputDeviceInfo.udpUseRTP ? 1 : 0);
     outputDevices->back()->setUdpChannelMode((int) outputDeviceInfo.udpChannelMode);
     outputDevices->back()->setUdpChannelCodec((int) outputDeviceInfo.udpChannelCodec);
     outputDevices->back()->setUdpDecimationFactor(outputDeviceInfo.udpDecimationFactor);
     *outputDevices->back()->getUdpAddress() = outputDeviceInfo.udpAddress;
     outputDevices->back()->setUdpPort(outputDeviceInfo.udpPort);
     // real output devices
     for (int i = 0; i < nbOutputDevices; i++)
     {
         outputDevices->append(new SWGSDRangel::SWGAudioOutputDevice);
         outputDevices->back()->init();
         outputDeviceInfo.resetToDefaults();
         found = m_mainCore.m_dspEngine->getAudioDeviceManager()->getOutputDeviceInfo(audioOutputDevices.at(i).deviceName(), outputDeviceInfo);
         *outputDevices->back()->getName() = audioOutputDevices.at(i).deviceName();
         outputDevices->back()->setIndex(i);
         outputDevices->back()->setSampleRate(outputDeviceInfo.sampleRate);
         outputDevices->back()->setIsSystemDefault(audioOutputDevices.at(i).deviceName() == QAudioDeviceInfo::defaultOutputDevice().deviceName() ? 1 : 0);
         outputDevices->back()->setDefaultUnregistered(found ? 0 : 1);
         outputDevices->back()->setCopyToUdp(outputDeviceInfo.copyToUDP ? 1 : 0);
         outputDevices->back()->setUdpUsesRtp(outputDeviceInfo.udpUseRTP ? 1 : 0);
         outputDevices->back()->setUdpChannelMode((int) outputDeviceInfo.udpChannelMode);
         outputDevices->back()->setUdpChannelCodec((int) outputDeviceInfo.udpChannelCodec);
         outputDevices->back()->setUdpDecimationFactor(outputDeviceInfo.udpDecimationFactor);
         *outputDevices->back()->getUdpAddress() = outputDeviceInfo.udpAddress;
         outputDevices->back()->setUdpPort(outputDeviceInfo.udpPort);
     }
     return 200;
 }
instanceAudioInputCleanupPatch()
int WebAPIAdapterSrv::instanceAudioInputCleanupPatch (SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/audio/input/cleanup (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 526 of file webapiadaptersrv.cpp.
References DSPEngine::getAudioDeviceManager(), SWGSDRangel::SWGSuccessResponse::getMessage(), SWGSDRangel::SWGSuccessResponse::init(), AudioDeviceManager::inputInfosCleanup(), MainCore::m_dspEngine, and m_mainCore.
 {
     m_mainCore.m_dspEngine->getAudioDeviceManager()->inputInfosCleanup();
     response.init();
     *response.getMessage() = QString("Unregistered parameters for devices not in list of available input devices for this instance");
     return 200;
 }
instanceAudioInputDelete()
int WebAPIAdapterSrv::instanceAudioInputDelete (SWGSDRangel::SWGAudioInputDevice & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/audio/input/parameters (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 466 of file webapiadaptersrv.cpp.
References DSPEngine::getAudioDeviceManager(), SWGSDRangel::SWGAudioInputDevice::getIndex(), AudioDeviceManager::getInputDeviceInfo(), AudioDeviceManager::getInputDeviceName(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGErrorResponse::init(), MainCore::m_dspEngine, m_mainCore, AudioDeviceManager::InputDeviceInfo::sampleRate, SWGSDRangel::SWGAudioInputDevice::setSampleRate(), SWGSDRangel::SWGAudioInputDevice::setVolume(), AudioDeviceManager::unsetInputDeviceInfo(), and AudioDeviceManager::InputDeviceInfo::volume.
 {
     AudioDeviceManager::InputDeviceInfo inputDeviceInfo;
     QString deviceName;
     int deviceIndex = response.getIndex();
     if (!m_mainCore.m_dspEngine->getAudioDeviceManager()->getInputDeviceName(deviceIndex, deviceName))
     {
         error.init();
         *error.getMessage() = QString("There is no audio input device at index %1").arg(deviceIndex);
         return 404;
     }
     m_mainCore.m_dspEngine->getAudioDeviceManager()->unsetInputDeviceInfo(deviceIndex);
     m_mainCore.m_dspEngine->getAudioDeviceManager()->getInputDeviceInfo(deviceName, inputDeviceInfo);
     response.setSampleRate(inputDeviceInfo.sampleRate);
     response.setVolume(inputDeviceInfo.volume);
     return 200;
 }
instanceAudioInputPatch()
int WebAPIAdapterSrv::instanceAudioInputPatch (SWGSDRangel::SWGAudioInputDevice & response, const QStringList & audioInputKeys, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/audio/input/parameters (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 373 of file webapiadaptersrv.cpp.
References DSPEngine::getAudioDeviceManager(), SWGSDRangel::SWGAudioInputDevice::getIndex(), AudioDeviceManager::getInputDeviceInfo(), AudioDeviceManager::getInputDeviceName(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGAudioInputDevice::getSampleRate(), SWGSDRangel::SWGAudioInputDevice::getVolume(), SWGSDRangel::SWGErrorResponse::init(), MainCore::m_dspEngine, m_mainCore, AudioDeviceManager::InputDeviceInfo::sampleRate, AudioDeviceManager::setInputDeviceInfo(), SWGSDRangel::SWGAudioInputDevice::setSampleRate(), SWGSDRangel::SWGAudioInputDevice::setVolume(), and AudioDeviceManager::InputDeviceInfo::volume.
 {
     // TODO
     AudioDeviceManager::InputDeviceInfo inputDeviceInfo;
     QString deviceName;
     int deviceIndex = response.getIndex();
     if (!m_mainCore.m_dspEngine->getAudioDeviceManager()->getInputDeviceName(deviceIndex, deviceName))
     {
         error.init();
         *error.getMessage() = QString("There is no input audio device at index %1").arg(deviceIndex);
         return 404;
     }
     m_mainCore.m_dspEngine->getAudioDeviceManager()->getInputDeviceInfo(deviceName, inputDeviceInfo);
     if (audioInputKeys.contains("sampleRate")) {
         inputDeviceInfo.sampleRate = response.getSampleRate();
     }
     if (audioInputKeys.contains("volume")) {
         inputDeviceInfo.volume = response.getVolume();
     }
     m_mainCore.m_dspEngine->getAudioDeviceManager()->setInputDeviceInfo(deviceIndex, inputDeviceInfo);
     m_mainCore.m_dspEngine->getAudioDeviceManager()->getInputDeviceInfo(deviceName, inputDeviceInfo);
     response.setSampleRate(inputDeviceInfo.sampleRate);
     response.setVolume(inputDeviceInfo.volume);
     return 200;
 }
instanceAudioOutputCleanupPatch()
int WebAPIAdapterSrv::instanceAudioOutputCleanupPatch (SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/audio/output/cleanup (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 538 of file webapiadaptersrv.cpp.
References DSPEngine::getAudioDeviceManager(), SWGSDRangel::SWGSuccessResponse::getMessage(), SWGSDRangel::SWGSuccessResponse::init(), MainCore::m_dspEngine, m_mainCore, and AudioDeviceManager::outputInfosCleanup().
 {
     m_mainCore.m_dspEngine->getAudioDeviceManager()->outputInfosCleanup();
     response.init();
     *response.getMessage() = QString("Unregistered parameters for devices not in list of available output devices for this instance");
     return 200;
 }
instanceAudioOutputDelete()
int WebAPIAdapterSrv::instanceAudioOutputDelete (SWGSDRangel::SWGAudioOutputDevice & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/audio/output/paramaters (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 490 of file webapiadaptersrv.cpp.
References AudioDeviceManager::OutputDeviceInfo::copyToUDP, DSPEngine::getAudioDeviceManager(), SWGSDRangel::SWGAudioOutputDevice::getIndex(), SWGSDRangel::SWGErrorResponse::getMessage(), AudioDeviceManager::getOutputDeviceInfo(), AudioDeviceManager::getOutputDeviceName(), SWGSDRangel::SWGAudioOutputDevice::getUdpAddress(), SWGSDRangel::SWGErrorResponse::init(), MainCore::m_dspEngine, m_mainCore, AudioDeviceManager::OutputDeviceInfo::sampleRate, SWGSDRangel::SWGAudioOutputDevice::setCopyToUdp(), SWGSDRangel::SWGAudioOutputDevice::setSampleRate(), SWGSDRangel::SWGAudioOutputDevice::setUdpAddress(), SWGSDRangel::SWGAudioOutputDevice::setUdpChannelCodec(), SWGSDRangel::SWGAudioOutputDevice::setUdpChannelMode(), SWGSDRangel::SWGAudioOutputDevice::setUdpDecimationFactor(), SWGSDRangel::SWGAudioOutputDevice::setUdpPort(), SWGSDRangel::SWGAudioOutputDevice::setUdpUsesRtp(), AudioDeviceManager::OutputDeviceInfo::udpAddress, AudioDeviceManager::OutputDeviceInfo::udpChannelCodec, AudioDeviceManager::OutputDeviceInfo::udpChannelMode, AudioDeviceManager::OutputDeviceInfo::udpDecimationFactor, AudioDeviceManager::OutputDeviceInfo::udpPort, AudioDeviceManager::OutputDeviceInfo::udpUseRTP, and AudioDeviceManager::unsetInputDeviceInfo().
 {
     AudioDeviceManager::OutputDeviceInfo outputDeviceInfo;
     QString deviceName;
     int deviceIndex = response.getIndex();
     if (!m_mainCore.m_dspEngine->getAudioDeviceManager()->getOutputDeviceName(deviceIndex, deviceName))
     {
         error.init();
         *error.getMessage() = QString("There is no audio output device at index %1").arg(deviceIndex);
         return 404;
     }
     m_mainCore.m_dspEngine->getAudioDeviceManager()->unsetInputDeviceInfo(deviceIndex);
     m_mainCore.m_dspEngine->getAudioDeviceManager()->getOutputDeviceInfo(deviceName, outputDeviceInfo);
     response.setSampleRate(outputDeviceInfo.sampleRate);
     response.setCopyToUdp(outputDeviceInfo.copyToUDP == 0 ? 0 : 1);
     response.setUdpUsesRtp(outputDeviceInfo.udpUseRTP == 0 ? 0 : 1);
     response.setUdpChannelMode(outputDeviceInfo.udpChannelMode);
     response.setUdpChannelCodec(outputDeviceInfo.udpChannelCodec);
     response.setUdpDecimationFactor(outputDeviceInfo.udpDecimationFactor);
     if (response.getUdpAddress()) {
         *response.getUdpAddress() = outputDeviceInfo.udpAddress;
     } else {
         response.setUdpAddress(new QString(outputDeviceInfo.udpAddress));
     }
     response.setUdpPort(outputDeviceInfo.udpPort % (1<<16));
     return 200;
 }
instanceAudioOutputPatch()
int WebAPIAdapterSrv::instanceAudioOutputPatch (SWGSDRangel::SWGAudioOutputDevice & response, const QStringList & audioOutputKeys, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/audio/output/parameters (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 408 of file webapiadaptersrv.cpp.
References AudioDeviceManager::OutputDeviceInfo::copyToUDP, DSPEngine::getAudioDeviceManager(), SWGSDRangel::SWGAudioOutputDevice::getCopyToUdp(), SWGSDRangel::SWGAudioOutputDevice::getIndex(), SWGSDRangel::SWGErrorResponse::getMessage(), AudioDeviceManager::getOutputDeviceInfo(), AudioDeviceManager::getOutputDeviceName(), SWGSDRangel::SWGAudioOutputDevice::getSampleRate(), SWGSDRangel::SWGAudioOutputDevice::getUdpAddress(), SWGSDRangel::SWGAudioOutputDevice::getUdpChannelMode(), SWGSDRangel::SWGAudioOutputDevice::getUdpPort(), SWGSDRangel::SWGAudioOutputDevice::getUdpUsesRtp(), SWGSDRangel::SWGErrorResponse::init(), MainCore::m_dspEngine, m_mainCore, AudioDeviceManager::OutputDeviceInfo::sampleRate, SWGSDRangel::SWGAudioOutputDevice::setCopyToUdp(), AudioDeviceManager::setOutputDeviceInfo(), SWGSDRangel::SWGAudioOutputDevice::setSampleRate(), SWGSDRangel::SWGAudioOutputDevice::setUdpAddress(), SWGSDRangel::SWGAudioOutputDevice::setUdpChannelCodec(), SWGSDRangel::SWGAudioOutputDevice::setUdpChannelMode(), SWGSDRangel::SWGAudioOutputDevice::setUdpDecimationFactor(), SWGSDRangel::SWGAudioOutputDevice::setUdpPort(), SWGSDRangel::SWGAudioOutputDevice::setUdpUsesRtp(), AudioDeviceManager::OutputDeviceInfo::udpAddress, AudioDeviceManager::OutputDeviceInfo::udpChannelCodec, AudioDeviceManager::OutputDeviceInfo::udpChannelMode, AudioDeviceManager::OutputDeviceInfo::udpDecimationFactor, AudioDeviceManager::OutputDeviceInfo::udpPort, and AudioDeviceManager::OutputDeviceInfo::udpUseRTP.
 {
     AudioDeviceManager::OutputDeviceInfo outputDeviceInfo;
     QString deviceName;
     int deviceIndex = response.getIndex();
     if (!m_mainCore.m_dspEngine->getAudioDeviceManager()->getOutputDeviceName(deviceIndex, deviceName))
     {
         error.init();
         *error.getMessage() = QString("There is no output audio device at index %1").arg(deviceIndex);
         return 404;
     }
     m_mainCore.m_dspEngine->getAudioDeviceManager()->getOutputDeviceInfo(deviceName, outputDeviceInfo);
     if (audioOutputKeys.contains("sampleRate")) {
         outputDeviceInfo.sampleRate = response.getSampleRate();
     }
     if (audioOutputKeys.contains("copyToUDP")) {
         outputDeviceInfo.copyToUDP = response.getCopyToUdp() == 0 ? 0 : 1;
     }
     if (audioOutputKeys.contains("udpUsesRTP")) {
         outputDeviceInfo.udpUseRTP = response.getUdpUsesRtp() == 0 ? 0 : 1;
     }
     if (audioOutputKeys.contains("udpChannelMode")) {
         outputDeviceInfo.udpChannelMode = static_cast<AudioOutput::UDPChannelMode>(response.getUdpChannelMode() % 4);
     }
     if (audioOutputKeys.contains("udpAddress")) {
         outputDeviceInfo.udpAddress = *response.getUdpAddress();
     }
     if (audioOutputKeys.contains("udpPort")) {
         outputDeviceInfo.udpPort = response.getUdpPort() % (1<<16);
     }
     m_mainCore.m_dspEngine->getAudioDeviceManager()->setOutputDeviceInfo(deviceIndex, outputDeviceInfo);
     m_mainCore.m_dspEngine->getAudioDeviceManager()->getOutputDeviceInfo(deviceName, outputDeviceInfo);
     response.setSampleRate(outputDeviceInfo.sampleRate);
     response.setCopyToUdp(outputDeviceInfo.copyToUDP == 0 ? 0 : 1);
     response.setUdpUsesRtp(outputDeviceInfo.udpUseRTP == 0 ? 0 : 1);
     response.setUdpChannelMode(outputDeviceInfo.udpChannelMode);
     response.setUdpChannelCodec(outputDeviceInfo.udpChannelCodec);
     response.setUdpDecimationFactor(outputDeviceInfo.udpDecimationFactor);
     if (response.getUdpAddress()) {
         *response.getUdpAddress() = outputDeviceInfo.udpAddress;
     } else {
         response.setUdpAddress(new QString(outputDeviceInfo.udpAddress));
     }
     response.setUdpPort(outputDeviceInfo.udpPort % (1<<16));
     return 200;
 }
instanceChannels()
int WebAPIAdapterSrv::instanceChannels (int direction, SWGSDRangel::SWGInstanceChannelsResponse & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/channels (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 189 of file webapiadaptersrv.cpp.
References PluginDescriptor::displayedName, SWGSDRangel::SWGInstanceChannelsResponse::getChannels(), PluginInterface::getPluginDescriptor(), PluginManager::getRxChannelRegistrations(), PluginManager::getTxChannelRegistrations(), i, SWGSDRangel::SWGInstanceChannelsResponse::init(), m_mainCore, MainCore::m_pluginManager, SWGSDRangel::SWGInstanceChannelsResponse::setChannelcount(), and PluginDescriptor::version.
 {
     response.init();
     PluginAPI::ChannelRegistrations *channelRegistrations;
     int nbChannelDevices;
     if (direction == 0) // Single sink (Rx) channel
     {
         channelRegistrations = m_mainCore.m_pluginManager->getRxChannelRegistrations();
         nbChannelDevices = channelRegistrations->size();
     }
     else if (direction == 1) // Single source (Tx) channel
     {
         channelRegistrations = m_mainCore.m_pluginManager->getTxChannelRegistrations();
         nbChannelDevices = channelRegistrations->size();
     }
     else // not supported
     {
         channelRegistrations = nullptr;
         nbChannelDevices = 0;
     }
     response.setChannelcount(nbChannelDevices);
     QList<SWGSDRangel::SWGChannelListItem*> *channels = response.getChannels();
     for (int i = 0; i < nbChannelDevices; i++)
     {
         channels->append(new SWGSDRangel::SWGChannelListItem);
         channels->back()->init();
         PluginInterface *channelInterface = channelRegistrations->at(i).m_plugin;
         const PluginDescriptor& pluginDescriptor = channelInterface->getPluginDescriptor();
         *channels->back()->getVersion() = pluginDescriptor.version;
         *channels->back()->getName() = pluginDescriptor.displayedName;
         channels->back()->setDirection(direction);
         *channels->back()->getIdUri() = channelRegistrations->at(i).m_channelIdURI;
         *channels->back()->getId() = channelRegistrations->at(i).m_channelId;
         channels->back()->setIndex(i);
     }
     return 200;
 }
instanceConfigGet()
int WebAPIAdapterSrv::instanceConfigGet (SWGSDRangel::SWGInstanceConfigResponse & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/config (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceSummary returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 118 of file webapiadaptersrv.cpp.
References MainCore::getMainSettings(), MainSettings::getPreferences(), SWGSDRangel::SWGInstanceConfigResponse::getPreferences(), MainSettings::getPreset(), MainSettings::getPresetCount(), SWGSDRangel::SWGInstanceConfigResponse::getPresets(), SWGSDRangel::SWGInstanceConfigResponse::getWorkingPreset(), MainSettings::getWorkingPresetConst(), i, SWGSDRangel::SWGInstanceConfigResponse::init(), m_mainCore, MainCore::m_settings, WebAPIAdapterBase::webapiFormatPreferences(), and WebAPIAdapterBase::webapiFormatPreset().
 {
     response.init();
     SWGSDRangel::SWGPreferences *preferences = response.getPreferences();
     WebAPIAdapterBase::webapiFormatPreferences(preferences, m_mainCore.getMainSettings().getPreferences());
     SWGSDRangel::SWGPreset *workingPreset = response.getWorkingPreset();
     WebAPIAdapterBase::webapiFormatPreset(workingPreset, m_mainCore.getMainSettings().getWorkingPresetConst());
     int nbPresets = m_mainCore.m_settings.getPresetCount();
     QList<SWGSDRangel::SWGPreset*> *swgPresets = response.getPresets();
     for (int i = 0; i < nbPresets; i++)
     {
         const Preset *preset = m_mainCore.m_settings.getPreset(i);
         swgPresets->append(new SWGSDRangel::SWGPreset);
         WebAPIAdapterBase::webapiFormatPreset(swgPresets->back(), *preset);
     }
     return 200;
 }
instanceDelete()
int WebAPIAdapterSrv::instanceDelete (SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceSummary returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 105 of file webapiadaptersrv.cpp.
References MainCore::MsgDeleteInstance::create(), MainCore::getInputMessageQueue(), SWGSDRangel::SWGSuccessResponse::getMessage(), SWGSDRangel::SWGSuccessResponse::init(), m_mainCore, and MessageQueue::push().
 {
     MainCore::MsgDeleteInstance *msg = MainCore::MsgDeleteInstance::create();
     m_mainCore.getInputMessageQueue()->push(msg);
     response.init();
     *response.getMessage() = QString("Message to stop the SDRangel instance (MsgDeleteInstance) was submitted successfully");
     return 202;
 }
instanceDevices()
int WebAPIAdapterSrv::instanceDevices (int direction, SWGSDRangel::SWGInstanceDevicesResponse & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/devices (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceDevices returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 141 of file webapiadaptersrv.cpp.
References PluginInterface::SamplingDevice::claimed, PluginInterface::SamplingDevice::deviceNbItems, PluginInterface::SamplingDevice::displayedName, SWGSDRangel::SWGInstanceDevicesResponse::getDevices(), DeviceEnumerator::getNbRxSamplingDevices(), DeviceEnumerator::getNbTxSamplingDevices(), DeviceEnumerator::getRxSamplingDevice(), DeviceEnumerator::getTxSamplingDevice(), PluginInterface::SamplingDevice::hardwareId, i, SWGSDRangel::SWGInstanceDevicesResponse::init(), DeviceEnumerator::instance(), PluginInterface::SamplingDevice::sequence, PluginInterface::SamplingDevice::serial, SWGSDRangel::SWGInstanceDevicesResponse::setDevicecount(), and PluginInterface::SamplingDevice::streamType.
 {
     response.init();
     int nbSamplingDevices;
     if (direction == 0) { // Single Rx stream device
         nbSamplingDevices = DeviceEnumerator::instance()->getNbRxSamplingDevices();
     } else if (direction == 1) { // Single Tx stream device
         nbSamplingDevices = DeviceEnumerator::instance()->getNbTxSamplingDevices();
     } else { // not supported
         nbSamplingDevices = 0;
     }
     response.setDevicecount(nbSamplingDevices);
     QList<SWGSDRangel::SWGDeviceListItem*> *devices = response.getDevices();
     for (int i = 0; i < nbSamplingDevices; i++)
     {
         const PluginInterface::SamplingDevice *samplingDevice = nullptr;
         if (direction == 0) {
             samplingDevice = DeviceEnumerator::instance()->getRxSamplingDevice(i);
         } else if (direction == 1) {
             samplingDevice = DeviceEnumerator::instance()->getTxSamplingDevice(i);
         } else {
             continue;
         }
         devices->append(new SWGSDRangel::SWGDeviceListItem);
         devices->back()->init();
         *devices->back()->getDisplayedName() = samplingDevice->displayedName;
         *devices->back()->getHwType() = samplingDevice->hardwareId;
         *devices->back()->getSerial() = samplingDevice->serial;
         devices->back()->setSequence(samplingDevice->sequence);
         devices->back()->setDirection((int) samplingDevice->streamType);
         devices->back()->setDeviceNbStreams(samplingDevice->deviceNbItems);
         devices->back()->setDeviceSetIndex(samplingDevice->claimed);
         devices->back()->setIndex(i);
     }
     return 200;
 }
instanceDeviceSetDelete()
int WebAPIAdapterSrv::instanceDeviceSetDelete (SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1146 of file webapiadaptersrv.cpp.
References MainCore::MsgRemoveLastDeviceSet::create(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGSuccessResponse::getMessage(), SWGSDRangel::SWGErrorResponse::init(), SWGSDRangel::SWGSuccessResponse::init(), MainCore::m_deviceSets, MainCore::m_inputMessageQueue, m_mainCore, and MessageQueue::push().
 {
     if (m_mainCore.m_deviceSets.size() > 0)
     {
         MainCore::MsgRemoveLastDeviceSet *msg = MainCore::MsgRemoveLastDeviceSet::create();
         m_mainCore.m_inputMessageQueue.push(msg);
         response.init();
         *response.getMessage() = QString("Message to remove last device set (MsgRemoveLastDeviceSet) was submitted successfully");
         return 202;
     }
     else
     {
         error.init();
         *error.getMessage() = "No more device sets to be removed";
         return 404;
     }
 }
instanceDeviceSetPost()
int WebAPIAdapterSrv::instanceDeviceSetPost (int direction, SWGSDRangel::SWGSuccessResponse & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/deviceset (POST) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1132 of file webapiadaptersrv.cpp.
References MainCore::MsgAddDeviceSet::create(), SWGSDRangel::SWGSuccessResponse::getMessage(), SWGSDRangel::SWGSuccessResponse::init(), MainCore::m_inputMessageQueue, m_mainCore, and MessageQueue::push().
 {
     MainCore::MsgAddDeviceSet *msg = MainCore::MsgAddDeviceSet::create(direction);
     m_mainCore.m_inputMessageQueue.push(msg);
     response.init();
     *response.getMessage() = QString("Message to add a new device set (MsgAddDeviceSet) was submitted successfully");
     return 202;
 }
instanceDeviceSetsGet()
int WebAPIAdapterSrv::instanceDeviceSetsGet (SWGSDRangel::SWGDeviceSetList & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/devicesets (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1124 of file webapiadaptersrv.cpp.
References getDeviceSetList().
 {
     getDeviceSetList(&response);
     return 200;
 }
instanceDVSerialGet()
int WebAPIAdapterSrv::instanceDVSerialGet (SWGSDRangel::SWGDVSerialDevices & response, SWGSDRangel::SWGErrorResponse & error) virtual
Definition at line 580 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGDVSerialDevices::getDvSerialDevices(), DSPEngine::getDVSerialNames(), SWGSDRangel::SWGDVSerialDevices::init(), MainCore::m_dspEngine, m_mainCore, and SWGSDRangel::SWGDVSerialDevices::setNbDevices().
 {
     response.init();
     std::vector<std::string> deviceNames;
     m_mainCore.m_dspEngine->getDVSerialNames(deviceNames);
     response.setNbDevices((int) deviceNames.size());
     QList<SWGSDRangel::SWGDVSerialDevice*> *deviceNamesList = response.getDvSerialDevices();
     std::vector<std::string>::iterator it = deviceNames.begin();
     while (it != deviceNames.end())
     {
         deviceNamesList->append(new SWGSDRangel::SWGDVSerialDevice);
         deviceNamesList->back()->init();
         *deviceNamesList->back()->getDeviceName() = QString::fromStdString(*it);
         ++it;
     }
     return 200;
 }
instanceDVSerialPatch()
int WebAPIAdapterSrv::instanceDVSerialPatch (bool dvserial, SWGSDRangel::SWGDVSerialDevices & response, SWGSDRangel::SWGErrorResponse & error) virtual
Definition at line 604 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGDVSerialDevices::getDvSerialDevices(), DSPEngine::getDVSerialNames(), SWGSDRangel::SWGDVSerialDevices::init(), MainCore::m_dspEngine, m_mainCore, DSPEngine::setDVSerialSupport(), and SWGSDRangel::SWGDVSerialDevices::setNbDevices().
 {
     m_mainCore.m_dspEngine->setDVSerialSupport(dvserial);
     response.init();
     if (dvserial)
     {
         std::vector<std::string> deviceNames;
         m_mainCore.m_dspEngine->getDVSerialNames(deviceNames);
         response.setNbDevices((int) deviceNames.size());
         QList<SWGSDRangel::SWGDVSerialDevice*> *deviceNamesList = response.getDvSerialDevices();
         std::vector<std::string>::iterator it = deviceNames.begin();
         std::string deviceNamesStr = "DV Serial devices found: ";
         while (it != deviceNames.end())
         {
             deviceNamesList->append(new SWGSDRangel::SWGDVSerialDevice);
             deviceNamesList->back()->init();
             *deviceNamesList->back()->getDeviceName() = QString::fromStdString(*it);
             ++it;
         }
     }
     else
     {
         response.setNbDevices(0);
     }
     return 200;
 }
instanceLocationGet()
int WebAPIAdapterSrv::instanceLocationGet (SWGSDRangel::SWGLocationInformation & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/location (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 550 of file webapiadaptersrv.cpp.
References MainSettings::getLatitude(), MainSettings::getLongitude(), SWGSDRangel::SWGLocationInformation::init(), m_mainCore, MainCore::m_settings, SWGSDRangel::SWGLocationInformation::setLatitude(), and SWGSDRangel::SWGLocationInformation::setLongitude().
 {
     response.init();
     response.setLatitude(m_mainCore.m_settings.getLatitude());
     response.setLongitude(m_mainCore.m_settings.getLongitude());
     return 200;
 }
instanceLocationPut()
int WebAPIAdapterSrv::instanceLocationPut (SWGSDRangel::SWGLocationInformation & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/location (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 561 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGLocationInformation::getLatitude(), MainSettings::getLatitude(), SWGSDRangel::SWGLocationInformation::getLongitude(), MainSettings::getLongitude(), m_mainCore, MainCore::m_settings, SWGSDRangel::SWGLocationInformation::setLatitude(), MainSettings::setLatitude(), SWGSDRangel::SWGLocationInformation::setLongitude(), and MainSettings::setLongitude().
 {
     float latitude = response.getLatitude();
     float longitude = response.getLongitude();
     latitude = latitude < -90.0 ? -90.0 : latitude > 90.0 ? 90.0 : latitude;
     longitude = longitude < -180.0 ? -180.0 : longitude > 180.0 ? 180.0 : longitude;
     m_mainCore.m_settings.setLatitude(latitude);
     m_mainCore.m_settings.setLongitude(longitude);
     response.setLatitude(m_mainCore.m_settings.getLatitude());
     response.setLongitude(m_mainCore.m_settings.getLongitude());
     return 200;
 }
instanceLoggingGet()
int WebAPIAdapterSrv::instanceLoggingGet (SWGSDRangel::SWGLoggingInfo & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/logging (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 234 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGLoggingInfo::getConsoleLevel(), qtwebapp::LoggerWithFile::getConsoleMinMessageLevelStr(), SWGSDRangel::SWGLoggingInfo::getDumpToFile(), SWGSDRangel::SWGLoggingInfo::getFileLevel(), qtwebapp::LoggerWithFile::getFileMinMessageLevelStr(), SWGSDRangel::SWGLoggingInfo::getFileName(), qtwebapp::LoggerWithFile::getLogFileName(), qtwebapp::LoggerWithFile::getUseFileLogger(), SWGSDRangel::SWGLoggingInfo::init(), MainCore::m_logger, m_mainCore, and SWGSDRangel::SWGLoggingInfo::setDumpToFile().
 {
     response.init();
     response.setDumpToFile(m_mainCore.m_logger->getUseFileLogger() ? 1 : 0);
     if (response.getDumpToFile()) {
         m_mainCore.m_logger->getLogFileName(*response.getFileName());
         m_mainCore.m_logger->getFileMinMessageLevelStr(*response.getFileLevel());
     }
     m_mainCore.m_logger->getConsoleMinMessageLevelStr(*response.getConsoleLevel());
     return 200;
 }
instanceLoggingPut()
int WebAPIAdapterSrv::instanceLoggingPut (SWGSDRangel::SWGLoggingInfo & query, SWGSDRangel::SWGLoggingInfo & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/logging (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 251 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGLoggingInfo::getConsoleLevel(), MainSettings::getConsoleMinLogLevel(), SWGSDRangel::SWGLoggingInfo::getDumpToFile(), SWGSDRangel::SWGLoggingInfo::getFileLevel(), MainSettings::getFileMinLogLevel(), SWGSDRangel::SWGLoggingInfo::getFileName(), MainSettings::getLogFileName(), getMsgTypeFromString(), getMsgTypeString(), MainSettings::getUseLogFile(), SWGSDRangel::SWGLoggingInfo::init(), m_mainCore, MainCore::m_settings, MainSettings::setConsoleMinLogLevel(), SWGSDRangel::SWGLoggingInfo::setDumpToFile(), MainSettings::setFileMinLogLevel(), MainSettings::setLogFileName(), MainCore::setLoggingOptions(), and MainSettings::setUseLogFile().
 {
     // response input is the query actually
     bool dumpToFile = (query.getDumpToFile() != 0);
     QString* consoleLevel = query.getConsoleLevel();
     QString* fileLevel = query.getFileLevel();
     QString* fileName = query.getFileName();
     // perform actions
     if (consoleLevel) {
         m_mainCore.m_settings.setConsoleMinLogLevel(getMsgTypeFromString(*consoleLevel));
     }
     if (fileLevel) {
         m_mainCore.m_settings.setFileMinLogLevel(getMsgTypeFromString(*fileLevel));
     }
     m_mainCore.m_settings.setUseLogFile(dumpToFile);
     if (fileName) {
         m_mainCore.m_settings.setLogFileName(*fileName);
     }
     m_mainCore.setLoggingOptions();
     // build response
     response.init();
     getMsgTypeString(m_mainCore.m_settings.getConsoleMinLogLevel(), *response.getConsoleLevel());
     response.setDumpToFile(m_mainCore.m_settings.getUseLogFile() ? 1 : 0);
     getMsgTypeString(m_mainCore.m_settings.getFileMinLogLevel(), *response.getFileLevel());
     *response.getFileName() = m_mainCore.m_settings.getLogFileName();
     return 200;
 }
instancePresetDelete()
int WebAPIAdapterSrv::instancePresetDelete (SWGSDRangel::SWGPresetIdentifier & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/preset (DELETE) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1093 of file webapiadaptersrv.cpp.
References arg(), MainCore::MsgDeletePreset::create(), SWGSDRangel::SWGPresetIdentifier::getCenterFrequency(), Preset::getCenterFrequency(), Preset::getDescription(), Preset::getGroup(), SWGSDRangel::SWGPresetIdentifier::getGroupName(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGPresetIdentifier::getName(), MainSettings::getPreset(), SWGSDRangel::SWGPresetIdentifier::getType(), SWGSDRangel::SWGErrorResponse::init(), Preset::isSourcePreset(), MainCore::m_inputMessageQueue, m_mainCore, MainCore::m_settings, MessageQueue::push(), and SWGSDRangel::SWGPresetIdentifier::setCenterFrequency().
 {
     const Preset *selectedPreset = m_mainCore.m_settings.getPreset(*response.getGroupName(),
             response.getCenterFrequency(),
             *response.getName(),
             *response.getType());
     if (selectedPreset == 0)
     {
         error.init();
         *error.getMessage() = QString("There is no preset [%1, %2, %3 %4]")
                 .arg(*response.getGroupName())
                 .arg(response.getCenterFrequency())
                 .arg(*response.getName())
                 .arg(*response.getType());
         return 404;
     }
     response.setCenterFrequency(selectedPreset->getCenterFrequency());
     *response.getGroupName() = selectedPreset->getGroup();
     *response.getType() = selectedPreset->isSourcePreset() ? "R" : "T";
     *response.getName() = selectedPreset->getDescription();
     MainCore::MsgDeletePreset *msg = MainCore::MsgDeletePreset::create(const_cast<Preset*>(selectedPreset));
     m_mainCore.m_inputMessageQueue.push(msg);
     return 202;
 }
instancePresetFilePost()
int WebAPIAdapterSrv::instancePresetFilePost (SWGSDRangel::SWGPresetExport & query, SWGSDRangel::SWGPresetIdentifier & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/preset/file (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 797 of file webapiadaptersrv.cpp.
References arg(), SWGSDRangel::SWGPresetIdentifier::getCenterFrequency(), Preset::getCenterFrequency(), Preset::getDescription(), SWGSDRangel::SWGPresetExport::getFilePath(), Preset::getGroup(), SWGSDRangel::SWGPresetIdentifier::getGroupName(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGPresetIdentifier::getName(), MainSettings::getPreset(), SWGSDRangel::SWGPresetExport::getPreset(), SWGSDRangel::SWGPresetIdentifier::getType(), SWGSDRangel::SWGErrorResponse::init(), SWGSDRangel::SWGPresetIdentifier::init(), Preset::isSourcePreset(), m_mainCore, MainCore::m_settings, Preset::serialize(), and SWGSDRangel::SWGPresetIdentifier::setCenterFrequency().
 {
     QString filePath = *query.getFilePath();
     SWGSDRangel::SWGPresetIdentifier *presetIdentifier = query.getPreset();
     const Preset *selectedPreset = m_mainCore.m_settings.getPreset(*presetIdentifier->getGroupName(),
             presetIdentifier->getCenterFrequency(),
             *presetIdentifier->getName(),
             *presetIdentifier->getType());
     if (selectedPreset == 0)
     {
         error.init();
         *error.getMessage() = QString("There is no preset [%1, %2, %3, %4]")
                 .arg(*presetIdentifier->getGroupName())
                 .arg(presetIdentifier->getCenterFrequency())
                 .arg(*presetIdentifier->getName())
                 .arg(*presetIdentifier->getType());
         return 404;
     }
     QString base64Str = selectedPreset->serialize().toBase64();
     if (filePath != "")
     {
         QFileInfo fileInfo(filePath);
         if (fileInfo.suffix() != "prex") {
             filePath += ".prex";
         }
         QFile exportFile(filePath);
         if (exportFile.open(QIODevice::WriteOnly | QIODevice::Text))
         {
             QTextStream outstream(&exportFile);
             outstream << base64Str;
             exportFile.close();
             response.init();
             response.setCenterFrequency(selectedPreset->getCenterFrequency());
             *response.getGroupName() = selectedPreset->getGroup();
             *response.getType() = selectedPreset->isSourcePreset() ? "R" : "T";
             *response.getName() = selectedPreset->getDescription();
             return 200;
         }
         else
         {
             error.init();
             *error.getMessage() = QString("File %1 cannot be written").arg(filePath);
             return 404;
         }
     }
     else
     {
         error.init();
         *error.getMessage() = QString("Empty file path");
         return 404;
     }
 }
instancePresetFilePut()
int WebAPIAdapterSrv::instancePresetFilePut (SWGSDRangel::SWGPresetImport & query, SWGSDRangel::SWGPresetIdentifier & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/preset/file (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 745 of file webapiadaptersrv.cpp.
References Preset::deserialize(), Preset::getCenterFrequency(), SWGSDRangel::SWGPresetImport::getDescription(), Preset::getDescription(), SWGSDRangel::SWGPresetImport::getFilePath(), Preset::getGroup(), SWGSDRangel::SWGPresetImport::getGroupName(), SWGSDRangel::SWGPresetIdentifier::getGroupName(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGPresetIdentifier::getName(), SWGSDRangel::SWGPresetIdentifier::getType(), SWGSDRangel::SWGErrorResponse::init(), SWGSDRangel::SWGPresetIdentifier::init(), Preset::isSourcePreset(), m_mainCore, MainCore::m_settings, MainSettings::newPreset(), SWGSDRangel::SWGPresetIdentifier::setCenterFrequency(), Preset::setDescription(), and Preset::setGroup().
 {
     const QString& fileName = *query.getFilePath();
     if (fileName != "")
     {
         QFile exportFile(fileName);
         if (exportFile.open(QIODevice::ReadOnly | QIODevice::Text))
         {
             QByteArray base64Str;
             QTextStream instream(&exportFile);
             instream >> base64Str;
             exportFile.close();
             Preset* preset = m_mainCore.m_settings.newPreset("", "");
             preset->deserialize(QByteArray::fromBase64(base64Str));
             if (query.getGroupName() && (query.getGroupName()->size() > 0)) {
                 preset->setGroup(*query.getGroupName());
             }
             if (query.getDescription() && (query.getDescription()->size() > 0)) {
                 preset->setDescription(*query.getDescription());
             }
             response.init();
             response.setCenterFrequency(preset->getCenterFrequency());
             *response.getGroupName() = preset->getGroup();
             *response.getType() = preset->isSourcePreset() ? "R" : "T";
             *response.getName() = preset->getDescription();
             return 200;
         }
         else
         {
             error.init();
             *error.getMessage() = QString("File %1 not found or not readable").arg(fileName);
             return 404;
         }
     }
     else
     {
         error.init();
         *error.getMessage() = QString("Empty file path");
         return 404;
     }
 }
instancePresetPatch()
int WebAPIAdapterSrv::instancePresetPatch (SWGSDRangel::SWGPresetTransfer & query, SWGSDRangel::SWGPresetIdentifier & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/preset (PATCH) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 907 of file webapiadaptersrv.cpp.
References arg(), MainCore::MsgLoadPreset::create(), SWGSDRangel::SWGPresetIdentifier::getCenterFrequency(), Preset::getCenterFrequency(), Preset::getDescription(), SWGSDRangel::SWGPresetTransfer::getDeviceSetIndex(), Preset::getGroup(), SWGSDRangel::SWGPresetIdentifier::getGroupName(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGPresetIdentifier::getName(), MainSettings::getPreset(), SWGSDRangel::SWGPresetTransfer::getPreset(), SWGSDRangel::SWGPresetIdentifier::getType(), SWGSDRangel::SWGErrorResponse::init(), SWGSDRangel::SWGPresetIdentifier::init(), Preset::isSourcePreset(), MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, MainCore::m_inputMessageQueue, m_mainCore, MainCore::m_settings, MessageQueue::push(), and SWGSDRangel::SWGPresetIdentifier::setCenterFrequency().
 {
     int deviceSetIndex = query.getDeviceSetIndex();
     SWGSDRangel::SWGPresetIdentifier *presetIdentifier = query.getPreset();
     int nbDeviceSets = m_mainCore.m_deviceSets.size();
     if (deviceSetIndex >= nbDeviceSets)
     {
         error.init();
         *error.getMessage() = QString("There is no device set at index %1. Number of device sets is %2").arg(deviceSetIndex).arg(nbDeviceSets);
         return 404;
     }
     const Preset *selectedPreset = m_mainCore.m_settings.getPreset(*presetIdentifier->getGroupName(),
             presetIdentifier->getCenterFrequency(),
             *presetIdentifier->getName(),
             *presetIdentifier->getType());
     if (selectedPreset == 0)
     {
         error.init();
         *error.getMessage() = QString("There is no preset [%1, %2, %3 %4]")
                 .arg(*presetIdentifier->getGroupName())
                 .arg(presetIdentifier->getCenterFrequency())
                 .arg(*presetIdentifier->getName())
                 .arg(*presetIdentifier->getType());
         return 404;
     }
     DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
     if (deviceSet->m_deviceSourceEngine && !selectedPreset->isSourcePreset())
     {
         error.init();
         *error.getMessage() = QString("Preset type (T) and device set type (Rx) mismatch");
         return 404;
     }
     if (deviceSet->m_deviceSinkEngine && selectedPreset->isSourcePreset())
     {
         error.init();
         *error.getMessage() = QString("Preset type (R) and device set type (Tx) mismatch");
         return 404;
     }
     MainCore::MsgLoadPreset *msg = MainCore::MsgLoadPreset::create(selectedPreset, deviceSetIndex);
     m_mainCore.m_inputMessageQueue.push(msg);
     response.init();
     response.setCenterFrequency(selectedPreset->getCenterFrequency());
     *response.getGroupName() = selectedPreset->getGroup();
     *response.getType() = selectedPreset->isSourcePreset() ? "R" : "T";
     *response.getName() = selectedPreset->getDescription();
     return 202;
 }
instancePresetPost()
int WebAPIAdapterSrv::instancePresetPost (SWGSDRangel::SWGPresetTransfer & query, SWGSDRangel::SWGPresetIdentifier & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/preset (POST) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 1029 of file webapiadaptersrv.cpp.
References arg(), MainCore::MsgSavePreset::create(), DeviceSampleSink::getCenterFrequency(), DeviceSampleSource::getCenterFrequency(), Preset::getDescription(), SWGSDRangel::SWGPresetTransfer::getDeviceSetIndex(), Preset::getGroup(), SWGSDRangel::SWGPresetIdentifier::getGroupName(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGPresetIdentifier::getName(), MainSettings::getPreset(), SWGSDRangel::SWGPresetTransfer::getPreset(), DSPDeviceSinkEngine::getSink(), DSPDeviceSourceEngine::getSource(), SWGSDRangel::SWGPresetIdentifier::getType(), SWGSDRangel::SWGErrorResponse::init(), SWGSDRangel::SWGPresetIdentifier::init(), MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, MainCore::m_inputMessageQueue, m_mainCore, MainCore::m_settings, MainSettings::newPreset(), MessageQueue::push(), and SWGSDRangel::SWGPresetIdentifier::setCenterFrequency().
 {
     int deviceSetIndex = query.getDeviceSetIndex();
     SWGSDRangel::SWGPresetIdentifier *presetIdentifier = query.getPreset();
     int nbDeviceSets = m_mainCore.m_deviceSets.size();
     if (deviceSetIndex >= nbDeviceSets)
     {
         error.init();
         *error.getMessage() = QString("There is no device set at index %1. Number of device sets is %2").arg(deviceSetIndex).arg(nbDeviceSets);
         return 404;
     }
     DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
     int deviceCenterFrequency = 0;
     bool isSourcePreset;
     if (deviceSet->m_deviceSourceEngine) { // Rx
         deviceCenterFrequency = deviceSet->m_deviceSourceEngine->getSource()->getCenterFrequency();
         isSourcePreset = true;
     } else if (deviceSet->m_deviceSinkEngine) { // Tx
         deviceCenterFrequency = deviceSet->m_deviceSinkEngine->getSink()->getCenterFrequency();
         isSourcePreset = false;
     } else {
         error.init();
         *error.getMessage() = QString("Device set error");
         return 500;
     }
     const Preset *selectedPreset = m_mainCore.m_settings.getPreset(*presetIdentifier->getGroupName(),
             deviceCenterFrequency,
             *presetIdentifier->getName(),
             *presetIdentifier->getType());
     if (selectedPreset == 0) // save on a new preset
     {
         selectedPreset = m_mainCore.m_settings.newPreset(*presetIdentifier->getGroupName(), *presetIdentifier->getName());
     }
     else
     {
         error.init();
         *error.getMessage() = QString("Preset already exists [%1, %2, %3 %4]")
                 .arg(*presetIdentifier->getGroupName())
                 .arg(deviceCenterFrequency)
                 .arg(*presetIdentifier->getName())
                 .arg(*presetIdentifier->getType());
         return 409;
     }
     MainCore::MsgSavePreset *msg = MainCore::MsgSavePreset::create(const_cast<Preset*>(selectedPreset), deviceSetIndex, true);
     m_mainCore.m_inputMessageQueue.push(msg);
     response.init();
     response.setCenterFrequency(deviceCenterFrequency);
     *response.getGroupName() = selectedPreset->getGroup();
     *response.getType() = isSourcePreset ? "R" : "T";
     *response.getName() = selectedPreset->getDescription();
     return 202;
 }
instancePresetPut()
int WebAPIAdapterSrv::instancePresetPut (SWGSDRangel::SWGPresetTransfer & query, SWGSDRangel::SWGPresetIdentifier & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/preset (PUT) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 967 of file webapiadaptersrv.cpp.
References arg(), MainCore::MsgSavePreset::create(), SWGSDRangel::SWGPresetIdentifier::getCenterFrequency(), Preset::getCenterFrequency(), Preset::getDescription(), SWGSDRangel::SWGPresetTransfer::getDeviceSetIndex(), Preset::getGroup(), SWGSDRangel::SWGPresetIdentifier::getGroupName(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGPresetIdentifier::getName(), MainSettings::getPreset(), SWGSDRangel::SWGPresetTransfer::getPreset(), SWGSDRangel::SWGPresetIdentifier::getType(), SWGSDRangel::SWGErrorResponse::init(), SWGSDRangel::SWGPresetIdentifier::init(), Preset::isSourcePreset(), MainCore::m_deviceSets, DeviceSet::m_deviceSinkEngine, DeviceSet::m_deviceSourceEngine, MainCore::m_inputMessageQueue, m_mainCore, MainCore::m_settings, MessageQueue::push(), and SWGSDRangel::SWGPresetIdentifier::setCenterFrequency().
 {
     int deviceSetIndex = query.getDeviceSetIndex();
     SWGSDRangel::SWGPresetIdentifier *presetIdentifier = query.getPreset();
     int nbDeviceSets = m_mainCore.m_deviceSets.size();
     if (deviceSetIndex >= nbDeviceSets)
     {
         error.init();
         *error.getMessage() = QString("There is no device set at index %1. Number of device sets is %2").arg(deviceSetIndex).arg(nbDeviceSets);
         return 404;
     }
     const Preset *selectedPreset = m_mainCore.m_settings.getPreset(*presetIdentifier->getGroupName(),
             presetIdentifier->getCenterFrequency(),
             *presetIdentifier->getName(),
             *presetIdentifier->getType());
     if (selectedPreset == 0)
     {
         error.init();
         *error.getMessage() = QString("There is no preset [%1, %2, %3 %4]")
                 .arg(*presetIdentifier->getGroupName())
                 .arg(presetIdentifier->getCenterFrequency())
                 .arg(*presetIdentifier->getName())
                 .arg(*presetIdentifier->getType());
         return 404;
     }
     else // update existing preset
     {
         DeviceSet *deviceSet = m_mainCore.m_deviceSets[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine && !selectedPreset->isSourcePreset())
         {
             error.init();
             *error.getMessage() = QString("Preset type (T) and device set type (Rx) mismatch");
             return 404;
         }
         if (deviceSet->m_deviceSinkEngine && selectedPreset->isSourcePreset())
         {
             error.init();
             *error.getMessage() = QString("Preset type (R) and device set type (Tx) mismatch");
             return 404;
         }
     }
     MainCore::MsgSavePreset *msg = MainCore::MsgSavePreset::create(const_cast<Preset*>(selectedPreset), deviceSetIndex, false);
     m_mainCore.m_inputMessageQueue.push(msg);
     response.init();
     response.setCenterFrequency(selectedPreset->getCenterFrequency());
     *response.getGroupName() = selectedPreset->getGroup();
     *response.getType() = selectedPreset->isSourcePreset() ? "R" : "T";
     *response.getName() = selectedPreset->getDescription();
     return 202;
 }
instancePresetsGet()
int WebAPIAdapterSrv::instancePresetsGet (SWGSDRangel::SWGPresets & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel/presets (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceChannels returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 862 of file webapiadaptersrv.cpp.
References Preset::getCenterFrequency(), Preset::getDescription(), Preset::getGroup(), SWGSDRangel::SWGPresets::getGroups(), MainSettings::getPreset(), MainSettings::getPresetCount(), i, SWGSDRangel::SWGPresets::init(), Preset::isSourcePreset(), m_mainCore, MainCore::m_settings, and SWGSDRangel::SWGPresets::setNbGroups().
 {
     int nbPresets = m_mainCore.m_settings.getPresetCount();
     int nbGroups = 0;
     int nbPresetsThisGroup = 0;
     QString groupName;
     response.init();
     QList<SWGSDRangel::SWGPresetGroup*> *groups = response.getGroups();
     QList<SWGSDRangel::SWGPresetItem*> *swgPresets = 0;
     int i = 0;
     // Presets are sorted by group first
     for (; i < nbPresets; i++)
     {
         const Preset *preset = m_mainCore.m_settings.getPreset(i);
         if ((i == 0) || (groupName != preset->getGroup())) // new group
         {
             if (i > 0) { groups->back()->setNbPresets(nbPresetsThisGroup); }
             groups->append(new SWGSDRangel::SWGPresetGroup);
             groups->back()->init();
             groupName = preset->getGroup();
             *groups->back()->getGroupName() = groupName;
             swgPresets = groups->back()->getPresets();
             nbGroups++;
             nbPresetsThisGroup = 0;
         }
         swgPresets->append(new SWGSDRangel::SWGPresetItem);
         swgPresets->back()->init();
         swgPresets->back()->setCenterFrequency(preset->getCenterFrequency());
         *swgPresets->back()->getType() = preset->isSourcePreset() ? "R" : "T";
         *swgPresets->back()->getName() = preset->getDescription();
         nbPresetsThisGroup++;
     }
     if (i > 0) { groups->back()->setNbPresets(nbPresetsThisGroup); }
     response.setNbGroups(nbGroups);
     return 200;
 }
instanceSummary()
int WebAPIAdapterSrv::instanceSummary (SWGSDRangel::SWGInstanceSummaryResponse & response, SWGSDRangel::SWGErrorResponse & error) virtual
Handler of /sdrangel (GET) swagger/sdrangel/code/html2/index.html#api-Default-instanceSummary returns the Http status code (default 501: not implemented)
Reimplemented from WebAPIAdapterInterface.
Definition at line 72 of file webapiadaptersrv.cpp.
References SWGSDRangel::SWGInstanceSummaryResponse::getAppname(), SWGSDRangel::SWGInstanceSummaryResponse::getArchitecture(), SWGSDRangel::SWGLoggingInfo::getConsoleLevel(), qtwebapp::LoggerWithFile::getConsoleMinMessageLevelStr(), SWGSDRangel::SWGInstanceSummaryResponse::getDevicesetlist(), getDeviceSetList(), SWGSDRangel::SWGLoggingInfo::getDumpToFile(), SWGSDRangel::SWGLoggingInfo::getFileLevel(), qtwebapp::LoggerWithFile::getFileMinMessageLevelStr(), SWGSDRangel::SWGLoggingInfo::getFileName(), qtwebapp::LoggerWithFile::getLogFileName(), SWGSDRangel::SWGInstanceSummaryResponse::getLogging(), SWGSDRangel::SWGInstanceSummaryResponse::getOs(), SWGSDRangel::SWGInstanceSummaryResponse::getQtVersion(), qtwebapp::LoggerWithFile::getUseFileLogger(), SWGSDRangel::SWGInstanceSummaryResponse::getVersion(), SWGSDRangel::SWGLoggingInfo::init(), SWGSDRangel::SWGInstanceSummaryResponse::init(), MainCore::m_logger, m_mainCore, SDR_RX_SAMP_SZ, SDR_TX_SAMP_SZ, SWGSDRangel::SWGInstanceSummaryResponse::setDspRxBits(), SWGSDRangel::SWGInstanceSummaryResponse::setDspTxBits(), SWGSDRangel::SWGLoggingInfo::setDumpToFile(), and SWGSDRangel::SWGInstanceSummaryResponse::setPid().
 {
     response.init();
     *response.getAppname() = QCoreApplication::applicationName();
     *response.getVersion() = QCoreApplication::applicationVersion();
     *response.getQtVersion() = QString(QT_VERSION_STR);
     response.setDspRxBits(SDR_RX_SAMP_SZ);
     response.setDspTxBits(SDR_TX_SAMP_SZ);
     response.setPid(QCoreApplication::applicationPid());
 #if QT_VERSION >= 0x050400
     *response.getArchitecture() = QString(QSysInfo::currentCpuArchitecture());
     *response.getOs() = QString(QSysInfo::prettyProductName());
 #endif
     SWGSDRangel::SWGLoggingInfo *logging = response.getLogging();
     logging->init();
     logging->setDumpToFile(m_mainCore.m_logger->getUseFileLogger() ? 1 : 0);
     if (logging->getDumpToFile()) {
         m_mainCore.m_logger->getLogFileName(*logging->getFileName());
         m_mainCore.m_logger->getFileMinMessageLevelStr(*logging->getFileLevel());
     }
     m_mainCore.m_logger->getConsoleMinMessageLevelStr(*logging->getConsoleLevel());
     SWGSDRangel::SWGDeviceSetList *deviceSetList = response.getDevicesetlist();
     getDeviceSetList(deviceSetList);
     return 200;
 }
Member Data Documentation
m_mainCore
MainCore& WebAPIAdapterSrv::m_mainCore private
Definition at line 268 of file webapiadaptersrv.h.
Referenced by devicesetChannelDelete(), devicesetChannelPost(), devicesetChannelReportGet(), devicesetChannelSettingsGet(), devicesetChannelSettingsPutPatch(), devicesetChannelsReportGet(), devicesetDevicePut(), devicesetDeviceReportGet(), devicesetDeviceRunDelete(), devicesetDeviceRunGet(), devicesetDeviceRunPost(), devicesetDeviceSettingsGet(), devicesetDeviceSettingsPutPatch(), devicesetGet(), getDeviceSetList(), instanceAMBEDevicesDelete(), instanceAMBEDevicesGet(), instanceAMBEDevicesPatch(), instanceAMBEDevicesPut(), instanceAMBESerialGet(), instanceAudioGet(), instanceAudioInputCleanupPatch(), instanceAudioInputDelete(), instanceAudioInputPatch(), instanceAudioOutputCleanupPatch(), instanceAudioOutputDelete(), instanceAudioOutputPatch(), instanceChannels(), instanceConfigGet(), instanceDelete(), instanceDeviceSetDelete(), instanceDeviceSetPost(), instanceDVSerialGet(), instanceDVSerialPatch(), instanceLocationGet(), instanceLocationPut(), instanceLoggingGet(), instanceLoggingPut(), instancePresetDelete(), instancePresetFilePost(), instancePresetFilePut(), instancePresetPatch(), instancePresetPost(), instancePresetPut(), instancePresetsGet(), and instanceSummary().
The documentation for this class was generated from the following files:
sdrsrv/webapi/webapiadaptersrv.h
sdrsrv/webapi/webapiadaptersrv.cpp