SDRAngel: AudioFifo Class Reference
AudioFifo Class Reference
#include <audiofifo.h>
Inherits QObject.
Public Member Functions
AudioFifo ()
AudioFifo (uint32_t numSamples)
~AudioFifo ()
bool setSize (uint32_t numSamples)
uint32_t write (const quint8 *data, uint32_t numSamples)
uint32_t read (quint8 *data, uint32_t numSamples)
uint32_t drain (uint32_t numSamples)
void clear ()
uint32_t flush ()
uint32_t fill () const
bool isEmpty () const
bool isFull () const
uint32_t size () const
Private Member Functions
bool create (uint32_t numSamples)
Private Attributes
QMutex m_mutex
qint8 * m_fifo
const uint32_t m_sampleSize
uint32_t m_size
uint32_t m_fill
uint32_t m_head
uint32_t m_tail
Detailed Description
Definition at line 29 of file audiofifo.h.
Constructor & Destructor Documentation
AudioFifo() [1/2]
AudioFifo::AudioFifo ()
Definition at line 27 of file audiofifo.cpp.
References m_fill, m_head, m_size, and m_tail.
                      :
     m_fifo(0),
     m_sampleSize(sizeof(AudioSample))
 {
     m_size = 0;
     m_fill = 0;
     m_head = 0;
     m_tail = 0;
 }
AudioFifo() [2/2]
AudioFifo::AudioFifo (uint32_t numSamples)
Definition at line 37 of file audiofifo.cpp.
References create(), and m_mutex.
                                         :
     m_fifo(0),
     m_sampleSize(sizeof(AudioSample))
 {
     QMutexLocker mutexLocker(&m_mutex);
     create(numSamples);
 }
~AudioFifo()
AudioFifo::~AudioFifo ()
Definition at line 46 of file audiofifo.cpp.
References m_fifo, m_mutex, and m_size.
 {
     QMutexLocker mutexLocker(&m_mutex);
     if (m_fifo != 0)
     {
         delete[] m_fifo;
         m_fifo = 0;
     }
     m_size = 0;
 }
Member Function Documentation
clear()
void AudioFifo::clear ()
Definition at line 156 of file audiofifo.cpp.
References m_fill, m_head, m_mutex, and m_tail.
Referenced by AMDemod::processOneSample(), AMMod::processOneSample(), NFMMod::processOneSample(), SSBMod::processOneSample(), AMDemod::start(), WFMDemod::start(), DSDDemod::start(), NFMDemod::start(), BFMDemod::start(), DATVDemod::start(), AMMod::start(), WFMMod::start(), NFMMod::start(), SSBMod::start(), and FreeDVMod::start().
 {
     QMutexLocker mutexLocker(&m_mutex);
     m_fill = 0;
     m_head = 0;
     m_tail = 0;
 }
create()
bool AudioFifo::create (uint32_t numSamples) private
Definition at line 165 of file audiofifo.cpp.
References m_fifo, m_fill, m_head, m_sampleSize, m_size, and m_tail.
Referenced by AudioFifo(), and setSize().
 {
     if(m_fifo != 0)
     {
         delete[] m_fifo;
         m_fifo = 0;
     }
     m_fill = 0;
     m_head = 0;
     m_tail = 0;
     m_fifo = new qint8[numSamples * m_sampleSize];
     m_size = numSamples;
     return true;
 }
drain()
uint AudioFifo::drain (uint32_t numSamples)
Definition at line 141 of file audiofifo.cpp.
References m_fill, m_head, m_mutex, and m_size.
 {
     QMutexLocker mutexLocker(&m_mutex);
     if(numSamples > m_fill)
     {
         numSamples = m_fill;
     }
     m_head = (m_head + numSamples) % m_size;
     m_fill -= numSamples;
     return numSamples;
 }
fill()
uint32_t AudioFifo::fill () const inline
Definition at line 45 of file audiofifo.h.
 { return m_fill; }
flush()
uint32_t AudioFifo::flush () inline
Definition at line 44 of file audiofifo.h.
 { return drain(m_fill); }
isEmpty()
bool AudioFifo::isEmpty () const inline
Definition at line 46 of file audiofifo.h.
Referenced by read().
 { return m_fill == 0; }
isFull()
bool AudioFifo::isFull () const inline
Definition at line 47 of file audiofifo.h.
Referenced by write().
 { return m_fill == m_size; }
read()
uint AudioFifo::read (quint8 * data, uint32_t numSamples)
Definition at line 103 of file audiofifo.cpp.
References isEmpty(), m_fifo, m_fill, m_head, m_mutex, m_sampleSize, m_size, and MIN.
Referenced by AMMod::pullAudio(), WFMMod::pullAudio(), NFMMod::pullAudio(), SSBMod::pullAudio(), FreeDVMod::pullAudio(), FCDProThread::work(), and FCDProPlusThread::work().
 {
     uint32_t total;
     uint32_t remaining;
     uint32_t copyLen;
     if (m_fifo == 0) {
         return 0;
     }
     m_mutex.lock();
     total = MIN(numSamples, m_fill);
     remaining = total;
     while (remaining != 0)
     {
         if (isEmpty())
         {
             m_mutex.unlock();
             return total - remaining; // read so far
         }
         copyLen = MIN(remaining, m_fill);
         copyLen = MIN(copyLen, m_size - m_head);
         memcpy(data, m_fifo + (m_head * m_sampleSize), copyLen * m_sampleSize);
         m_head += copyLen;
         m_head %= m_size;
         m_fill -= copyLen;
         data += copyLen * m_sampleSize;
         remaining -= copyLen;
     }
     m_mutex.unlock();
     return total;
 }
setSize()
bool AudioFifo::setSize (uint32_t numSamples)
Definition at line 59 of file audiofifo.cpp.
References create(), and m_mutex.
Referenced by AMDemod::applyAudioSampleRate(), SSBDemod::applyAudioSampleRate(), and FreeDVDemod::applyAudioSampleRate().
 {
     QMutexLocker mutexLocker(&m_mutex);
     return create(numSamples);
 }
size()
uint32_t AudioFifo::size () const inline
Definition at line 48 of file audiofifo.h.
 { return m_size; }
write()
uint AudioFifo::write (const quint8 * data, uint32_t numSamples)
Definition at line 66 of file audiofifo.cpp.
References isFull(), m_fifo, m_fill, m_mutex, m_sampleSize, m_size, m_tail, and MIN.
Referenced by UDPSink::audioReadyRead(), AMDemod::feed(), WFMDemod::feed(), DSDDemod::feed(), BFMDemod::feed(), FreeDVDemod::feed(), AMBEWorker::handleInputMessages(), AMDemod::processOneSample(), NFMDemod::processOneSample(), AMMod::processOneSample(), NFMMod::processOneSample(), SSBDemod::processOneSample(), SSBMod::processOneSample(), FreeDVDemod::pushSampleToAudio(), and DATVideoRender::RenderStream().
 {
     uint32_t total;
     uint32_t remaining;
     uint32_t copyLen;
     if (m_fifo == 0) {
         return 0;
     }
     m_mutex.lock();
     total = MIN(numSamples, m_size - m_fill);
     remaining = total;
     while (remaining != 0)
     {
         if (isFull())
         {
             m_mutex.unlock();
             return total - remaining; // written so far
         }
         copyLen = MIN(remaining, m_size - m_fill);
         copyLen = MIN(copyLen, m_size - m_tail);
         memcpy(m_fifo + (m_tail * m_sampleSize), data, copyLen * m_sampleSize);
         m_tail += copyLen;
         m_tail %= m_size;
         m_fill += copyLen;
         data += copyLen * m_sampleSize;
         remaining -= copyLen;
     }
     m_mutex.unlock();
     return total;
 }
Member Data Documentation
m_fifo
qint8* AudioFifo::m_fifo private
Definition at line 53 of file audiofifo.h.
Referenced by create(), read(), write(), and ~AudioFifo().
m_fill
uint32_t AudioFifo::m_fill private
Definition at line 58 of file audiofifo.h.
Referenced by AudioFifo(), clear(), create(), drain(), read(), and write().
m_head
uint32_t AudioFifo::m_head private
Definition at line 59 of file audiofifo.h.
Referenced by AudioFifo(), clear(), create(), drain(), and read().
m_mutex
QMutex AudioFifo::m_mutex private
Definition at line 51 of file audiofifo.h.
Referenced by AudioFifo(), clear(), drain(), read(), setSize(), write(), and ~AudioFifo().
m_sampleSize
const uint32_t AudioFifo::m_sampleSize private
Definition at line 55 of file audiofifo.h.
Referenced by create(), read(), and write().
m_size
uint32_t AudioFifo::m_size private
Definition at line 57 of file audiofifo.h.
Referenced by AudioFifo(), create(), drain(), read(), write(), and ~AudioFifo().
m_tail
uint32_t AudioFifo::m_tail private
Definition at line 60 of file audiofifo.h.
Referenced by AudioFifo(), clear(), create(), and write().
The documentation for this class was generated from the following files:
sdrbase/audio/audiofifo.h
sdrbase/audio/audiofifo.cpp