SDRAngel: FileInputThread Class Reference
FileInputThread Class Reference
#include <fileinputthread.h>
Inherits QThread.
Classes
class MsgReportEOF
Public Member Functions
FileInputThread (std::ifstream *samplesStream, SampleSinkFifo *sampleFifo, const QTimer &timer, MessageQueue *fileInputMessageQueue, QObject *parent=NULL)
~FileInputThread ()
void startWork ()
void stopWork ()
void setSampleRateAndSize (int samplerate, quint32 samplesize)
void setBuffers (std::size_t chunksize)
bool isRunning () const
quint64 getSamplesCount () const
void setSamplesCount (quint64 samplesCount)
Private Slots
void tick ()
Private Member Functions
void run ()
void writeToSampleFifo (const quint8 *buf, qint32 nbBytes)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
volatile bool m_running
std::ifstream * m_ifstream
quint8 * m_fileBuf
quint8 * m_convertBuf
std::size_t m_bufsize
qint64 m_chunksize
SampleSinkFifo * m_sampleFifo
quint64 m_samplesCount
const QTimer & m_timer
MessageQueue * m_fileInputMessageQueue
int m_samplerate
File I/Q stream original sample rate.
quint64 m_samplesize
File effective sample size in bits (I or Q). Ex: 16, 24.
quint64 m_samplebytes
Number of bytes used to store a I or Q sample. Ex: 2. 4.
qint64 m_throttlems
QElapsedTimer m_elapsedTimer
bool m_throttleToggle
Detailed Description
Definition at line 38 of file fileinputthread.h.
Constructor & Destructor Documentation
FileInputThread()
FileInputThread::FileInputThread (std::ifstream * samplesStream, SampleSinkFifo * sampleFifo, const QTimer & timer, MessageQueue * fileInputMessageQueue, QObject * parent = NULL)
Definition at line 30 of file fileinputthread.cpp.
Referenced by FileInputThread::MsgReportEOF::MsgReportEOF().
                          :
     QThread(parent),
     m_running(false),
     m_ifstream(samplesStream),
     m_fileBuf(0),
     m_convertBuf(0),
     m_bufsize(0),
     m_chunksize(0),
     m_sampleFifo(sampleFifo),
     m_samplesCount(0),
     m_timer(timer),
     m_fileInputMessageQueue(fileInputMessageQueue),
     m_samplerate(0),
     m_samplesize(0),
     m_samplebytes(0),
     m_throttlems(FILESOURCE_THROTTLE_MS),
     m_throttleToggle(false)
 {
     assert(m_ifstream != 0);
 }
~FileInputThread()
FileInputThread::~FileInputThread ()
Definition at line 55 of file fileinputthread.cpp.
References m_convertBuf, m_fileBuf, m_running, and stopWork().
Referenced by FileInputThread::MsgReportEOF::MsgReportEOF().
 {
     if (m_running) {
         stopWork();
     }
     if (m_fileBuf != 0) {
         free(m_fileBuf);
     }
     if (m_convertBuf != 0) {
         free(m_convertBuf);
     }
 }
Member Function Documentation
getSamplesCount()
quint64 FileInputThread::getSamplesCount () const inline
Definition at line 68 of file fileinputthread.h.
References m_samplesCount.
Referenced by FileInput::handleMessage(), and FileInput::webapiFormatDeviceReport().
 { return m_samplesCount; }
isRunning()
bool FileInputThread::isRunning () const inline
Definition at line 67 of file fileinputthread.h.
References m_running.
Referenced by FileInput::seekFileStream().
 { return m_running; }
run()
void FileInputThread::run () private
Definition at line 162 of file fileinputthread.cpp.
References m_running, and m_startWaiter.
 {
     m_running = true;
     m_startWaiter.wakeAll();
     while(m_running) // actual work is in the tick() function
     {
         sleep(1);
     }
     m_running = false;
 }
setBuffers()
void FileInputThread::setBuffers (std::size_t chunksize)
Definition at line 124 of file fileinputthread.cpp.
References m_bufsize, m_convertBuf, m_fileBuf, and m_samplebytes.
Referenced by FileInputThread::MsgReportEOF::MsgReportEOF(), setSampleRateAndSize(), and tick().
 {
     if (chunksize > m_bufsize)
     {
         m_bufsize = chunksize;
         int nbSamples = m_bufsize/(2 * m_samplebytes);
         if (m_fileBuf == 0)
         {
             qDebug() << "FileInputThread::setBuffers: Allocate file buffer";
             m_fileBuf = (quint8*) malloc(m_bufsize);
         }
         else
         {
             qDebug() << "FileInputThread::setBuffers: Re-allocate file buffer";
             quint8 *buf = m_fileBuf;
             m_fileBuf = (quint8*) realloc((void*) m_fileBuf, m_bufsize);
             if (!m_fileBuf) free(buf);
         }
         if (m_convertBuf == 0)
         {
             qDebug() << "FileInputThread::setBuffers: Allocate conversion buffer";
             m_convertBuf = (quint8*) malloc(nbSamples*sizeof(Sample));
         }
         else
         {
             qDebug() << "FileInputThread::setBuffers: Re-allocate conversion buffer";
             quint8 *buf = m_convertBuf;
             m_convertBuf = (quint8*) realloc((void*) m_convertBuf, nbSamples*sizeof(Sample));
             if (!m_convertBuf) free(buf);
         }
         qDebug() << "FileInputThread::setBuffers: size: " << m_bufsize
                 << " #samples: " << nbSamples;
     }
 }
setSampleRateAndSize()
void FileInputThread::setSampleRateAndSize (int samplerate, quint32 samplesize)
Definition at line 99 of file fileinputthread.cpp.
References m_chunksize, m_running, m_samplebytes, m_samplerate, m_samplesize, m_throttlems, setBuffers(), and stopWork().
Referenced by FileInput::applySettings(), FileInputThread::MsgReportEOF::MsgReportEOF(), and FileInput::start().
 {
     qDebug() << "FileInputThread::setSampleRateAndSize:"
             << " new rate:" << samplerate
             << " new size:" << samplesize
             << " old rate:" << m_samplerate
             << " old size:" << m_samplesize;
     if ((samplerate != m_samplerate) || (samplesize != m_samplesize))
     {
         if (m_running) {
             stopWork();
         }
         m_samplerate = samplerate;
         m_samplesize = samplesize;
         m_samplebytes = m_samplesize > 16 ? sizeof(int32_t) : sizeof(int16_t);
         m_chunksize = (m_samplerate * 2 * m_samplebytes * m_throttlems) / 1000;
         setBuffers(m_chunksize);
     }
     //m_samplerate = samplerate;
 }
setSamplesCount()
void FileInputThread::setSamplesCount (quint64 samplesCount) inline
Definition at line 69 of file fileinputthread.h.
References m_samplesCount.
Referenced by FileInput::seekFileStream().
 { m_samplesCount = samplesCount; }
startWork()
void FileInputThread::startWork ()
Definition at line 70 of file fileinputthread.cpp.
References m_elapsedTimer, m_ifstream, m_running, m_startWaiter, m_startWaitMutex, m_timer, and tick().
Referenced by FileInput::handleMessage(), FileInputThread::MsgReportEOF::MsgReportEOF(), and FileInput::start().
 {
     qDebug() << "FileInputThread::startWork: ";
     if (m_ifstream->is_open())
     {
         qDebug() << "FileInputThread::startWork: file stream open, starting...";
         m_startWaitMutex.lock();
         m_elapsedTimer.start();
         start();
         while(!m_running)
             m_startWaiter.wait(&m_startWaitMutex, 100);
         m_startWaitMutex.unlock();
         connect(&m_timer, SIGNAL(timeout()), this, SLOT(tick()));
     }
     else
     {
         qDebug() << "FileInputThread::startWork: file stream closed, not starting.";
     }
 }
stopWork()
void FileInputThread::stopWork ()
Definition at line 91 of file fileinputthread.cpp.
References m_running, m_timer, and tick().
Referenced by FileInput::handleMessage(), FileInputThread::MsgReportEOF::MsgReportEOF(), setSampleRateAndSize(), FileInput::stop(), and ~FileInputThread().
 {
     qDebug() << "FileInputThread::stopWork";
     disconnect(&m_timer, SIGNAL(timeout()), this, SLOT(tick()));
     m_running = false;
     wait();
 }
tick
void FileInputThread::tick () private slot
Definition at line 175 of file fileinputthread.cpp.
References FileInputThread::MsgReportEOF::create(), m_chunksize, m_elapsedTimer, m_fileBuf, m_fileInputMessageQueue, m_ifstream, m_running, m_samplebytes, m_samplerate, m_samplesCount, m_throttlems, m_throttleToggle, MessageQueue::push(), setBuffers(), and writeToSampleFifo().
Referenced by startWork(), and stopWork().
 {
     if (m_running)
     {
         qint64 throttlems = m_elapsedTimer.restart();
         if (throttlems != m_throttlems)
         {
             m_throttlems = throttlems;
             m_chunksize = 2 * m_samplebytes * ((m_samplerate * (m_throttlems+(m_throttleToggle ? 1 : 0))) / 1000);
             m_throttleToggle = !m_throttleToggle;
             setBuffers(m_chunksize);
         }
         // read samples directly feeding the SampleFifo (no callback)
         m_ifstream->read(reinterpret_cast<char*>(m_fileBuf), m_chunksize);
         if (m_ifstream->eof())
         {
             writeToSampleFifo(m_fileBuf, (qint32) m_ifstream->gcount());
             MsgReportEOF *message = MsgReportEOF::create();
             m_fileInputMessageQueue->push(message);
         }
         else
         {
             writeToSampleFifo(m_fileBuf, (qint32) m_chunksize);
             m_samplesCount += m_chunksize / (2 * m_samplebytes);
         }
     }
 }
writeToSampleFifo()
void FileInputThread::writeToSampleFifo (const quint8 * buf, qint32 nbBytes) private
Definition at line 206 of file fileinputthread.cpp.
References m_convertBuf, m_samplebytes, m_sampleFifo, m_samplesize, SDR_RX_SAMP_SZ, and SampleSinkFifo::write().
Referenced by tick().
 {
     if (m_samplesize == 16)
     {
         if (SDR_RX_SAMP_SZ == 16)
         {
             m_sampleFifo->write(buf, nbBytes);
         }
         else if (SDR_RX_SAMP_SZ == 24)
         {
             FixReal *convertBuf = (FixReal *) m_convertBuf;
             const int16_t *fileBuf = (int16_t *) buf;
             int nbSamples = nbBytes / (2 * m_samplebytes);
             for (int is = 0; is < nbSamples; is++)
             {
                 convertBuf[2*is]   = fileBuf[2*is] << 8;
                 convertBuf[2*is+1] = fileBuf[2*is+1] << 8;
             }
             m_sampleFifo->write((quint8*) convertBuf, nbSamples*sizeof(Sample));
         }
     }
     else if (m_samplesize == 24)
     {
         if (SDR_RX_SAMP_SZ == 24)
         {
             m_sampleFifo->write(buf, nbBytes);
         }
         else if (SDR_RX_SAMP_SZ == 16)
         {
             FixReal *convertBuf = (FixReal *) m_convertBuf;
             const int32_t *fileBuf = (int32_t *) buf;
             int nbSamples = nbBytes / (2 * m_samplebytes);
             for (int is = 0; is < nbSamples; is++)
             {
                 convertBuf[2*is]   = fileBuf[2*is] >> 8;
                 convertBuf[2*is+1] = fileBuf[2*is+1] >> 8;
             }
             m_sampleFifo->write((quint8*) convertBuf, nbSamples*sizeof(Sample));
         }
     }
 }
Member Data Documentation
m_bufsize
std::size_t FileInputThread::m_bufsize private
Definition at line 79 of file fileinputthread.h.
Referenced by setBuffers().
m_chunksize
qint64 FileInputThread::m_chunksize private
Definition at line 80 of file fileinputthread.h.
Referenced by setSampleRateAndSize(), and tick().
m_convertBuf
quint8* FileInputThread::m_convertBuf private
Definition at line 78 of file fileinputthread.h.
Referenced by setBuffers(), writeToSampleFifo(), and ~FileInputThread().
m_elapsedTimer
QElapsedTimer FileInputThread::m_elapsedTimer private
Definition at line 90 of file fileinputthread.h.
Referenced by startWork(), and tick().
m_fileBuf
quint8* FileInputThread::m_fileBuf private
Definition at line 77 of file fileinputthread.h.
Referenced by setBuffers(), tick(), and ~FileInputThread().
m_fileInputMessageQueue
MessageQueue* FileInputThread::m_fileInputMessageQueue private
Definition at line 84 of file fileinputthread.h.
Referenced by tick().
m_ifstream
std::ifstream* FileInputThread::m_ifstream private
Definition at line 76 of file fileinputthread.h.
Referenced by startWork(), and tick().
m_running
volatile bool FileInputThread::m_running private
Definition at line 74 of file fileinputthread.h.
Referenced by isRunning(), run(), setSampleRateAndSize(), startWork(), stopWork(), tick(), and ~FileInputThread().
m_samplebytes
quint64 FileInputThread::m_samplebytes private
Number of bytes used to store a I or Q sample. Ex: 2. 4.
Definition at line 88 of file fileinputthread.h.
Referenced by setBuffers(), setSampleRateAndSize(), tick(), and writeToSampleFifo().
m_sampleFifo
SampleSinkFifo* FileInputThread::m_sampleFifo private
Definition at line 81 of file fileinputthread.h.
Referenced by writeToSampleFifo().
m_samplerate
int FileInputThread::m_samplerate private
File I/Q stream original sample rate.
Definition at line 86 of file fileinputthread.h.
Referenced by setSampleRateAndSize(), and tick().
m_samplesCount
quint64 FileInputThread::m_samplesCount private
Definition at line 82 of file fileinputthread.h.
Referenced by getSamplesCount(), setSamplesCount(), and tick().
m_samplesize
quint64 FileInputThread::m_samplesize private
File effective sample size in bits (I or Q). Ex: 16, 24.
Definition at line 87 of file fileinputthread.h.
Referenced by setSampleRateAndSize(), and writeToSampleFifo().
m_startWaiter
QWaitCondition FileInputThread::m_startWaiter private
Definition at line 73 of file fileinputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex FileInputThread::m_startWaitMutex private
Definition at line 72 of file fileinputthread.h.
Referenced by startWork().
m_throttlems
qint64 FileInputThread::m_throttlems private
Definition at line 89 of file fileinputthread.h.
Referenced by setSampleRateAndSize(), and tick().
m_throttleToggle
bool FileInputThread::m_throttleToggle private
Definition at line 91 of file fileinputthread.h.
Referenced by tick().
m_timer
const QTimer& FileInputThread::m_timer private
Definition at line 83 of file fileinputthread.h.
Referenced by startWork(), and stopWork().
The documentation for this class was generated from the following files:
plugins/samplesource/fileinput/fileinputthread.h
plugins/samplesource/fileinput/fileinputthread.cpp