SDRAngel: MovingAverageUtil< T, Total, N > Class Template Reference
MovingAverageUtil< T, Total, N > Class Template Reference
#include <movingaverage.h>
Public Member Functions
MovingAverageUtil ()
void reset ()
void operator() (T sample)
double asDouble () const
float asFloat () const
operator T () const
T instantAverage () const
Private Attributes
T m_samples [N]
int m_num_samples
unsigned int m_index
Total m_total
Detailed Description
template<typename T, typename Total, int N>
class MovingAverageUtil< T, Total, N >
Definition at line 27 of file movingaverage.h.
Constructor & Destructor Documentation
MovingAverageUtil()
template<typename T, typename Total, int N> MovingAverageUtil< T, Total, N >::MovingAverageUtil () inline
Definition at line 30 of file movingaverage.h.
       : m_num_samples(0), m_index(0), m_total(0)
     { }
Member Function Documentation
asDouble()
template<typename T, typename Total, int N> double MovingAverageUtil< T, Total, N >::asDouble () const inline
Definition at line 57 of file movingaverage.h.
Referenced by DSDDemod::feed(), WFMDemod::getMagSq(), ATVMod::getMagSq(), DSPDeviceSourceEngine::iqCorrections(), AutoCorrector< T >::process(), AMDemod::processOneSample(), FreqTracker::processOneSample(), AMMod::pull(), WFMMod::pull(), NFMMod::pull(), SSBMod::pull(), FreeDVMod::pull(), FileSource::pull(), and UDPSourceGUI::tick().
 { return ((double)m_total) / N; }
asFloat()
template<typename T, typename Total, int N> float MovingAverageUtil< T, Total, N >::asFloat () const inline
Definition at line 58 of file movingaverage.h.
 { return ((float)m_total) / N; }
instantAverage()
template<typename T, typename Total, int N> T MovingAverageUtil< T, Total, N >::instantAverage () const inline
Definition at line 60 of file movingaverage.h.
 { return m_total / (m_num_samples == 0 ? 1 : m_num_samples); }
operator T()
template<typename T, typename Total, int N> MovingAverageUtil< T, Total, N >::operator T () const inline
Definition at line 59 of file movingaverage.h.
References MovingAverageUtil< T, Total, N >::m_total.
 { return  m_total / N; }
operator()()
template<typename T, typename Total, int N> void MovingAverageUtil< T, Total, N >::operator() (T sample) inline
Definition at line 41 of file movingaverage.h.
     {
         if (m_num_samples < N) // fill up
         {
             m_samples[m_num_samples++] = sample;
             m_total += sample;
         }
         else // roll
         {
             T& oldest = m_samples[m_index];
             m_total += sample - oldest;
             oldest = sample;
             m_index = (m_index + 1) % N;
         }
     }
reset()
template<typename T, typename Total, int N> void MovingAverageUtil< T, Total, N >::reset () inline
Definition at line 34 of file movingaverage.h.
Referenced by NFMDemod::applySettings(), DSPDeviceSourceEngine::handleInputMessages(), MovingAverageUtilVar< T, Total >::resize(), and DSPDeviceMIMOEngine::SourceCorrection::SourceCorrection().
     {
         m_num_samples = 0;
         m_index = 0;
         m_total = 0;
     }
Member Data Documentation
m_index
template<typename T, typename Total, int N> unsigned int MovingAverageUtil< T, Total, N >::m_index private
Definition at line 65 of file movingaverage.h.
Referenced by MovingAverageUtil< int, int, 10 >::operator()(), MovingAverageUtilVar< T, Total >::operator()(), MovingAverageUtil< int, int, 10 >::reset(), and MovingAverageUtilVar< T, Total >::reset().
m_num_samples
template<typename T, typename Total, int N> int MovingAverageUtil< T, Total, N >::m_num_samples private
Definition at line 64 of file movingaverage.h.
Referenced by MovingAverageUtil< int, int, 10 >::instantAverage(), MovingAverageUtil< int, int, 10 >::operator()(), MovingAverageUtilVar< T, Total >::operator()(), MovingAverageUtil< int, int, 10 >::reset(), and MovingAverageUtilVar< T, Total >::reset().
m_samples
template<typename T, typename Total, int N> T MovingAverageUtil< T, Total, N >::m_samples[N] private
Definition at line 63 of file movingaverage.h.
Referenced by MovingAverageUtilVar< T, Total >::asDouble(), MovingAverageUtilVar< T, Total >::asFloat(), MovingAverageUtilVar< T, Total >::MovingAverageUtilVar(), MovingAverageUtilVar< T, Total >::operator T(), MovingAverageUtil< int, int, 10 >::operator()(), MovingAverageUtilVar< T, Total >::operator()(), MovingAverageUtilVar< T, Total >::resize(), and MovingAverageUtilVar< T, Total >::size().
m_total
template<typename T, typename Total, int N> Total MovingAverageUtil< T, Total, N >::m_total private
Definition at line 66 of file movingaverage.h.
Referenced by MovingAverageUtil< int, int, 10 >::asDouble(), MovingAverageUtilVar< T, Total >::asDouble(), MovingAverageUtil< int, int, 10 >::asFloat(), MovingAverageUtilVar< T, Total >::asFloat(), MovingAverageUtil< int, int, 10 >::instantAverage(), MovingAverageUtil< T, Total, N >::operator T(), MovingAverageUtilVar< T, Total >::operator T(), MovingAverageUtil< int, int, 10 >::operator()(), MovingAverageUtilVar< T, Total >::operator()(), MovingAverageUtil< int, int, 10 >::reset(), and MovingAverageUtilVar< T, Total >::reset().
The documentation for this class was generated from the following file:
sdrbase/util/movingaverage.h