SDRAngel: SWGSDRangel::SWGAMBEDevices Class Reference
SWGSDRangel::SWGAMBEDevices Class Reference
#include <SWGAMBEDevices.h>
Public Member Functions
SWGAMBEDevices ()
SWGAMBEDevices (QString *json)
virtual ~SWGAMBEDevices ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGAMBEDevices * fromJson (QString &jsonString) override
qint32 getNbDevices ()
void setNbDevices (qint32 nb_devices)
QList< SWGAMBEDevice * > * getAmbeDevices ()
void setAmbeDevices (QList< SWGAMBEDevice *> *ambe_devices)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 nb_devices
bool m_nb_devices_isSet
QList< SWGAMBEDevice * > * ambe_devices
bool m_ambe_devices_isSet
Detailed Description
Definition at line 33 of file SWGAMBEDevices.h.
Constructor & Destructor Documentation
SWGAMBEDevices() [1/2]
SWGSDRangel::SWGAMBEDevices::SWGAMBEDevices ()
Definition at line 30 of file SWGAMBEDevices.cpp.
References ambe_devices, m_ambe_devices_isSet, m_nb_devices_isSet, and nb_devices.
{
     nb_devices = 0;
     m_nb_devices_isSet = false;
     ambe_devices = nullptr;
     m_ambe_devices_isSet = false;
 }
SWGAMBEDevices() [2/2]
SWGSDRangel::SWGAMBEDevices::SWGAMBEDevices (QString * json)
Definition at line 25 of file SWGAMBEDevices.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGAMBEDevices()
SWGSDRangel::SWGAMBEDevices::~SWGAMBEDevices () virtual
Definition at line 37 of file SWGAMBEDevices.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGAMBEDevices::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 79 of file SWGAMBEDevices.cpp.
References asJsonObject().
Referenced by SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPatch(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPut(), and WebAPIRequestMapper::instanceAMBEDevicesService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGAMBEDevices::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 90 of file SWGAMBEDevices.cpp.
References ambe_devices, m_nb_devices_isSet, nb_devices, and SWGSDRangel::toJsonArray().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_nb_devices_isSet){
         obj->insert("nbDevices", QJsonValue(nb_devices));
     }
     if(ambe_devices->size() > 0){
         toJsonArray((QList<void*>*)ambe_devices, obj, "ambeDevices", "SWGAMBEDevice");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGAMBEDevices::cleanup ()
Definition at line 50 of file SWGAMBEDevices.cpp.
References ambe_devices.
Referenced by ~SWGAMBEDevices().
{
     if(ambe_devices != nullptr) {
         auto arr = ambe_devices;
         for(auto o: *arr) {
             delete o;
         }
         delete ambe_devices;
     }
 }
fromJson()
SWGAMBEDevices * SWGSDRangel::SWGAMBEDevices::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 62 of file SWGAMBEDevices.cpp.
References fromJsonObject().
Referenced by SWGAMBEDevices().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGAMBEDevices::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 71 of file SWGAMBEDevices.cpp.
References ambe_devices, nb_devices, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&nb_devices, pJson["nbDevices"], "qint32", "");
     ::SWGSDRangel::setValue(&ambe_devices, pJson["ambeDevices"], "QList", "SWGAMBEDevice");
 }
getAmbeDevices()
QList< SWGAMBEDevice * > * SWGSDRangel::SWGAMBEDevices::getAmbeDevices ()
Definition at line 113 of file SWGAMBEDevices.cpp.
References ambe_devices.
Referenced by WebAPIAdapterGUI::instanceAMBEDevicesGet(), WebAPIAdapterSrv::instanceAMBEDevicesGet(), WebAPIAdapterGUI::instanceAMBEDevicesPatch(), WebAPIAdapterSrv::instanceAMBEDevicesPatch(), WebAPIAdapterSrv::instanceAMBEDevicesPut(), WebAPIAdapterGUI::instanceAMBEDevicesPut(), and WebAPIRequestMapper::validateAMBEDevices().
{
     return ambe_devices;
 }
getNbDevices()
qint32 SWGSDRangel::SWGAMBEDevices::getNbDevices ()
Definition at line 103 of file SWGAMBEDevices.cpp.
References nb_devices.
{
     return nb_devices;
 }
init()
void SWGSDRangel::SWGAMBEDevices::init ()
Definition at line 42 of file SWGAMBEDevices.cpp.
References ambe_devices, m_ambe_devices_isSet, m_nb_devices_isSet, and nb_devices.
Referenced by WebAPIAdapterGUI::instanceAMBEDevicesGet(), WebAPIAdapterSrv::instanceAMBEDevicesGet(), SWGAMBEDevices(), and WebAPIRequestMapper::validateAMBEDevices().
                      {
     nb_devices = 0;
     m_nb_devices_isSet = false;
     ambe_devices = new QList<SWGAMBEDevice*>();
     m_ambe_devices_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGAMBEDevices::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 124 of file SWGAMBEDevices.cpp.
References ambe_devices, and m_nb_devices_isSet.
                      {
     bool isObjectUpdated = false;
     do{
         if(m_nb_devices_isSet){ isObjectUpdated = true; break;}
         if(ambe_devices->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setAmbeDevices()
void SWGSDRangel::SWGAMBEDevices::setAmbeDevices (QList< SWGAMBEDevice *> * ambe_devices)
Definition at line 117 of file SWGAMBEDevices.cpp.
References ambe_devices, and m_ambe_devices_isSet.
{
     this->ambe_devices = ambe_devices;
     this->m_ambe_devices_isSet = true;
 }
setNbDevices()
void SWGSDRangel::SWGAMBEDevices::setNbDevices (qint32 nb_devices)
Definition at line 107 of file SWGAMBEDevices.cpp.
References m_nb_devices_isSet, and nb_devices.
Referenced by WebAPIAdapterGUI::instanceAMBEDevicesGet(), WebAPIAdapterSrv::instanceAMBEDevicesGet(), and WebAPIRequestMapper::validateAMBEDevices().
{
     this->nb_devices = nb_devices;
     this->m_nb_devices_isSet = true;
 }
Member Data Documentation
ambe_devices
QList<SWGAMBEDevice*>* SWGSDRangel::SWGAMBEDevices::ambe_devices private
Definition at line 59 of file SWGAMBEDevices.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getAmbeDevices(), init(), isSet(), setAmbeDevices(), and SWGAMBEDevices().
m_ambe_devices_isSet
bool SWGSDRangel::SWGAMBEDevices::m_ambe_devices_isSet private
Definition at line 60 of file SWGAMBEDevices.h.
Referenced by init(), setAmbeDevices(), and SWGAMBEDevices().
m_nb_devices_isSet
bool SWGSDRangel::SWGAMBEDevices::m_nb_devices_isSet private
Definition at line 57 of file SWGAMBEDevices.h.
Referenced by asJsonObject(), init(), isSet(), setNbDevices(), and SWGAMBEDevices().
nb_devices
qint32 SWGSDRangel::SWGAMBEDevices::nb_devices private
Definition at line 56 of file SWGAMBEDevices.h.
Referenced by asJsonObject(), fromJsonObject(), getNbDevices(), init(), setNbDevices(), and SWGAMBEDevices().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGAMBEDevices.h
swagger/sdrangel/code/qt5/client/SWGAMBEDevices.cpp