SDRAngel: BladeRF2Input::MsgConfigureBladeRF2 Class Reference
BladeRF2Input::MsgConfigureBladeRF2 Class Reference
#include <bladerf2input.h>
Public Member Functions
const BladeRF2InputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureBladeRF2 * create (const BladeRF2InputSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureBladeRF2 (const BladeRF2InputSettings &settings, bool force)
Private Attributes
BladeRF2InputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 42 of file bladerf2input.h.
Constructor & Destructor Documentation
MsgConfigureBladeRF2()
BladeRF2Input::MsgConfigureBladeRF2::MsgConfigureBladeRF2 (const BladeRF2InputSettings & settings, bool force) inline private
Definition at line 58 of file bladerf2input.h.
Referenced by create().
                                                                                 :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureBladeRF2* BladeRF2Input::MsgConfigureBladeRF2::create (const BladeRF2InputSettings & settings, bool force) inline static
Definition at line 49 of file bladerf2input.h.
References MsgConfigureBladeRF2().
Referenced by BladeRF2Input::deserialize(), BladeRF2Input::handleMessage(), BladeRF2Input::setCenterFrequency(), BladeRF2InputGui::updateHardware(), and BladeRF2Input::webapiSettingsPutPatch().
         {
             return new MsgConfigureBladeRF2(settings, force);
         }
getForce()
bool BladeRF2Input::MsgConfigureBladeRF2::getForce () const inline
Definition at line 47 of file bladerf2input.h.
References m_force.
Referenced by BladeRF2Input::handleMessage().
 { return m_force; }
getSettings()
const BladeRF2InputSettings& BladeRF2Input::MsgConfigureBladeRF2::getSettings () const inline
Definition at line 46 of file bladerf2input.h.
References m_settings.
Referenced by BladeRF2InputGui::handleMessage(), and BladeRF2Input::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool BladeRF2Input::MsgConfigureBladeRF2::m_force private
Definition at line 56 of file bladerf2input.h.
Referenced by getForce().
m_settings
BladeRF2InputSettings BladeRF2Input::MsgConfigureBladeRF2::m_settings private
Definition at line 55 of file bladerf2input.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/bladerf2input/bladerf2input.h