SDRAngel: RemoteDataQueue Class Reference
RemoteDataQueue Class Reference
#include <remotedataqueue.h>
Inherits QObject.
Signals
void dataBlockEnqueued ()
Public Member Functions
RemoteDataQueue (QObject *parent=NULL)
~RemoteDataQueue ()
void push (RemoteDataBlock *dataBlock, bool emitSignal=true)
Push daa block onto queue.
RemoteDataBlock * pop ()
Pop message from queue.
int size ()
Returns queue size.
void clear ()
Empty queue.
Private Attributes
QMutex m_lock
QQueue< RemoteDataBlock * > m_queue
Detailed Description
Definition at line 36 of file remotedataqueue.h.
Constructor & Destructor Documentation
RemoteDataQueue()
RemoteDataQueue::RemoteDataQueue (QObject * parent = NULL)
Definition at line 30 of file remotedataqueue.cpp.
                                                 :
     QObject(parent),
     m_lock(QMutex::Recursive),
     m_queue()
 {
 }
~RemoteDataQueue()
RemoteDataQueue::~RemoteDataQueue ()
Definition at line 37 of file remotedataqueue.cpp.
References pop().
 {
     RemoteDataBlock* data;
     while ((data = pop()) != 0)
     {
         qDebug() << "RemoteDataQueue::~RemoteDataQueue: data block was still in queue";
         delete data;
     }
 }
Member Function Documentation
clear()
void RemoteDataQueue::clear ()
Empty queue.
Definition at line 84 of file remotedataqueue.cpp.
References m_lock, and m_queue.
 {
     QMutexLocker locker(&m_lock);
     m_queue.clear();
 }
dataBlockEnqueued
void RemoteDataQueue::dataBlockEnqueued () signal
Referenced by push().
pop()
RemoteDataBlock * RemoteDataQueue::pop ()
Pop message from queue.
Definition at line 63 of file remotedataqueue.cpp.
References m_lock, and m_queue.
Referenced by RemoteSource::handleData(), and ~RemoteDataQueue().
 {
     QMutexLocker locker(&m_lock);
     if (m_queue.isEmpty())
     {
         return 0;
     }
     else
     {
         return m_queue.takeFirst();
     }
 }
push()
void RemoteDataQueue::push (RemoteDataBlock * dataBlock, bool emitSignal = true)
Push daa block onto queue.
Definition at line 48 of file remotedataqueue.cpp.
References dataBlockEnqueued(), m_lock, and m_queue.
Referenced by RemoteSourceThread::readPendingDatagrams().
 {
     if (data)
     {
         m_lock.lock();
         m_queue.append(data);
         m_lock.unlock();
     }
     if (emitSignal)
     {
         emit dataBlockEnqueued();
     }
 }
size()
int RemoteDataQueue::size ()
Returns queue size.
Definition at line 77 of file remotedataqueue.cpp.
References m_lock, and m_queue.
 {
     QMutexLocker locker(&m_lock);
     return m_queue.size();
 }
Member Data Documentation
m_lock
QMutex RemoteDataQueue::m_lock private
Definition at line 53 of file remotedataqueue.h.
Referenced by clear(), pop(), push(), and size().
m_queue
QQueue<RemoteDataBlock*> RemoteDataQueue::m_queue private
Definition at line 54 of file remotedataqueue.h.
Referenced by clear(), pop(), push(), and size().
The documentation for this class was generated from the following files:
sdrbase/channel/remotedataqueue.h
sdrbase/channel/remotedataqueue.cpp