SDRAngel: RemoteSink::MsgConfigureChannelizer Class Reference
RemoteSink::MsgConfigureChannelizer Class Reference
#include <remotesink.h>
Public Member Functions
int getLog2Decim () const
int getFilterChainHash () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (int sampleRate, int centerFrequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (unsigned int log2Decim, int filterChainHash)
Private Attributes
unsigned int m_log2Decim
unsigned int m_filterChainHash
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 89 of file remotesink.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
RemoteSink::MsgConfigureChannelizer::MsgConfigureChannelizer (unsigned int log2Decim, int filterChainHash) inline private
Definition at line 105 of file remotesink.h.
References RemoteSink::RemoteSink(), and RemoteSink::~RemoteSink().
                                                                              :
             Message(),
             m_log2Decim(log2Decim),
             m_filterChainHash(filterChainHash)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* RemoteSink::MsgConfigureChannelizer::create (int sampleRate, int centerFrequency) inline static
Definition at line 96 of file remotesink.h.
Referenced by RemoteSinkGUI::applyChannelSettings(), and RemoteSink::webapiSettingsPutPatch().
         {
             return new MsgConfigureChannelizer(sampleRate, centerFrequency);
         }
getFilterChainHash()
int RemoteSink::MsgConfigureChannelizer::getFilterChainHash () const inline
Definition at line 94 of file remotesink.h.
Referenced by RemoteSink::handleMessage().
 { return m_filterChainHash; }
getLog2Decim()
int RemoteSink::MsgConfigureChannelizer::getLog2Decim () const inline
Definition at line 93 of file remotesink.h.
Referenced by RemoteSink::handleMessage().
 { return m_log2Decim; }
Member Data Documentation
m_filterChainHash
unsigned int RemoteSink::MsgConfigureChannelizer::m_filterChainHash private
Definition at line 103 of file remotesink.h.
m_log2Decim
unsigned int RemoteSink::MsgConfigureChannelizer::m_log2Decim private
Definition at line 102 of file remotesink.h.
The documentation for this class was generated from the following file:
plugins/channelrx/remotesink/remotesink.h