SDRAngel: LoRaDemodSettings Struct Reference
LoRaDemodSettings Struct Reference
#include <lorademodsettings.h>
Public Member Functions
LoRaDemodSettings ()
void resetToDefaults ()
void setChannelMarker (Serializable *channelMarker)
void setSpectrumGUI (Serializable *spectrumGUI)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
Public Attributes
int m_centerFrequency
int m_bandwidthIndex
int m_spread
uint32_t m_rgbColor
QString m_title
Serializable * m_channelMarker
Serializable * m_spectrumGUI
Static Public Attributes
static const int bandwidths [] = {7813,15625,20833,31250,62500}
static const int nb_bandwidths = 5
Detailed Description
Definition at line 12 of file lorademodsettings.h.
Constructor & Destructor Documentation
LoRaDemodSettings()
LoRaDemodSettings::LoRaDemodSettings ()
Definition at line 13 of file lorademodsettings.cpp.
References resetToDefaults().
                                      :
     m_centerFrequency(0),
     m_channelMarker(0),
     m_spectrumGUI(0)
 {
     resetToDefaults();
 }
Member Function Documentation
deserialize()
bool LoRaDemodSettings::deserialize (const QByteArray & data)
Definition at line 49 of file lorademodsettings.cpp.
References Serializable::deserialize(), SimpleDeserializer::getVersion(), SimpleDeserializer::isValid(), m_bandwidthIndex, m_centerFrequency, m_channelMarker, m_spectrumGUI, m_spread, m_title, SimpleDeserializer::readBlob(), SimpleDeserializer::readS32(), SimpleDeserializer::readString(), and resetToDefaults().
Referenced by LoRaDemodGUI::deserialize(), LoRaDemod::deserialize(), and setSpectrumGUI().
 {
     SimpleDeserializer d(data);
     if(!d.isValid())
     {
         resetToDefaults();
         return false;
     }
     if(d.getVersion() == 1)
     {
         QByteArray bytetmp;
         d.readS32(1, &m_centerFrequency, 0);
         d.readS32(2, &m_bandwidthIndex, 0);
         d.readS32(3, &m_spread, 0);
         if (m_spectrumGUI) {
             d.readBlob(4, &bytetmp);
             m_spectrumGUI->deserialize(bytetmp);
         }
         if (m_channelMarker) {
             d.readBlob(5, &bytetmp);
             m_channelMarker->deserialize(bytetmp);
         }
         d.readString(6, &m_title, "LoRa Demodulator");
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
resetToDefaults()
void LoRaDemodSettings::resetToDefaults ()
Definition at line 21 of file lorademodsettings.cpp.
References m_bandwidthIndex, m_rgbColor, m_spread, and m_title.
Referenced by deserialize(), LoRaDemod::deserialize(), LoRaDemodSettings(), and LoRaDemodGUI::resetToDefaults().
 {
     m_bandwidthIndex = 0;
     m_spread = 0;
     m_rgbColor = QColor(255, 0, 255).rgb();
     m_title = "LoRa Demodulator";
 }
serialize()
QByteArray LoRaDemodSettings::serialize () const
Definition at line 29 of file lorademodsettings.cpp.
References SimpleSerializer::final(), m_bandwidthIndex, m_centerFrequency, m_channelMarker, m_spectrumGUI, m_spread, m_title, Serializable::serialize(), SimpleSerializer::writeBlob(), SimpleSerializer::writeS32(), and SimpleSerializer::writeString().
Referenced by LoRaDemodGUI::serialize(), LoRaDemod::serialize(), and setSpectrumGUI().
 {
     SimpleSerializer s(1);
     s.writeS32(1, m_centerFrequency);
     s.writeS32(2, m_bandwidthIndex);
     s.writeS32(3, m_spread);
     if (m_spectrumGUI) {
         s.writeBlob(4, m_spectrumGUI->serialize());
     }
     if (m_channelMarker) {
         s.writeBlob(5, m_channelMarker->serialize());
     }
     s.writeString(6, m_title);
     return s.final();
 }
setChannelMarker()
void LoRaDemodSettings::setChannelMarker (Serializable * channelMarker) inline
Definition at line 28 of file lorademodsettings.h.
Referenced by LoRaDemodGUI::LoRaDemodGUI().
 { m_channelMarker = channelMarker; }
setSpectrumGUI()
void LoRaDemodSettings::setSpectrumGUI (Serializable * spectrumGUI) inline
Definition at line 29 of file lorademodsettings.h.
References deserialize(), and serialize().
Referenced by LoRaDemodGUI::LoRaDemodGUI().
 { m_spectrumGUI = spectrumGUI; }
Member Data Documentation
bandwidths
const int LoRaDemodSettings::bandwidths = {7813,15625,20833,31250,62500} static
Definition at line 23 of file lorademodsettings.h.
Referenced by LoRaDemodGUI::applySettings(), LoRaDemodGUI::displaySettings(), LoRaDemod::handleMessage(), LoRaDemod::LoRaDemod(), and LoRaDemodGUI::on_BW_valueChanged().
m_bandwidthIndex
int LoRaDemodSettings::m_bandwidthIndex
Definition at line 15 of file lorademodsettings.h.
Referenced by LoRaDemodGUI::applySettings(), deserialize(), LoRaDemodGUI::displaySettings(), LoRaDemod::handleMessage(), LoRaDemodGUI::on_BW_valueChanged(), resetToDefaults(), and serialize().
m_centerFrequency
int LoRaDemodSettings::m_centerFrequency
Definition at line 14 of file lorademodsettings.h.
Referenced by deserialize(), and serialize().
m_channelMarker
Serializable* LoRaDemodSettings::m_channelMarker
Definition at line 20 of file lorademodsettings.h.
Referenced by deserialize(), and serialize().
m_rgbColor
uint32_t LoRaDemodSettings::m_rgbColor
Definition at line 17 of file lorademodsettings.h.
Referenced by LoRaDemodGUI::displaySettings(), and resetToDefaults().
m_spectrumGUI
Serializable* LoRaDemodSettings::m_spectrumGUI
Definition at line 21 of file lorademodsettings.h.
Referenced by deserialize(), and serialize().
m_spread
int LoRaDemodSettings::m_spread
Definition at line 16 of file lorademodsettings.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_title
QString LoRaDemodSettings::m_title
Definition at line 18 of file lorademodsettings.h.
Referenced by deserialize(), LoRaDemod::getTitle(), resetToDefaults(), and serialize().
nb_bandwidths
const int LoRaDemodSettings::nb_bandwidths = 5 static
Definition at line 24 of file lorademodsettings.h.
Referenced by LoRaDemodGUI::on_BW_valueChanged().
The documentation for this struct was generated from the following files:
plugins/channelrx/demodlora/lorademodsettings.h
plugins/channelrx/demodlora/lorademodsettings.cpp