SDRAngel: PlutoSDROutputGUI Class Reference
PlutoSDROutputGUI Class Reference
#include <plutosdroutputgui.h>
Public Member Functions
PlutoSDROutputGUI (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~PlutoSDROutputGUI ()
virtual void destroy ()
virtual void setName (const QString &name)
virtual QString getName () const
virtual void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void on_startStop_toggled (bool checked)
void on_centerFrequency_changed (quint64 value)
void on_loPPM_valueChanged (int value)
void on_swInterp_currentIndexChanged (int index)
void on_sampleRate_changed (quint64 value)
void on_lpf_changed (quint64 value)
void on_lpFIREnable_toggled (bool checked)
void on_lpFIR_changed (quint64 value)
void on_lpFIRInterpolation_currentIndexChanged (int index)
void on_lpFIRGain_currentIndexChanged (int index)
void on_att_valueChanged (int value)
void on_antenna_currentIndexChanged (int index)
void on_transverter_clicked ()
void on_sampleRateMode_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void handleInputMessages ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void displaySettings ()
void displaySampleRate ()
void sendSettings (bool forceSettings=false)
void blockApplySettings (bool block)
void updateSampleRateAndFrequency ()
void setFIRBWLimits ()
void setSampleRateLimits ()
void updateFrequencyLimits ()
Private Attributes
Ui::PlutoSDROutputGUI * ui
DeviceUISet * m_deviceUISet
PlutoSDROutputSettings m_settings
bool m_sampleRateMode
true: device, false: base band sample rate update mode
bool m_forceSettings
QTimer m_updateTimer
QTimer m_statusTimer
DeviceSampleSink * m_sampleSink
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
bool m_doApplySettings
uint32_t m_statusCounter
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 38 of file plutosdroutputgui.h.
Constructor & Destructor Documentation
PlutoSDROutputGUI()
PlutoSDROutputGUI::PlutoSDROutputGUI (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 34 of file plutosdroutputgui.cpp.
References blockApplySettings(), displaySettings(), DeviceAPI::getSampleSink(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, ColorMapper::GrayYellow, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_sampleSink, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), DevicePlutoSDR::srHighLimitFreq, DevicePlutoSDR::srLowLimitFreq, ui, updateFrequencyLimits(), updateHardware(), and updateStatus().
                                                                               :
     QWidget(parent),
     ui(new Ui::PlutoSDROutputGUI),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_sampleRateMode(true),
     m_forceSettings(true),
     m_sampleSink(0),
     m_sampleRate(0),
     m_deviceCenterFrequency(0),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_doApplySettings(true),
     m_statusCounter(0)
 {
     m_sampleSink = (PlutoSDROutput*) m_deviceUISet->m_deviceAPI->getSampleSink();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     updateFrequencyLimits();
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(8, DevicePlutoSDR::srLowLimitFreq, DevicePlutoSDR::srHighLimitFreq);
     ui->lpf->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     quint32 minLimit, maxLimit;
     ((PlutoSDROutput *) m_sampleSink)->getbbLPRange(minLimit, maxLimit);
     ui->lpf->setValueRange(5, minLimit/1000, maxLimit/1000);
     ui->lpFIR->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     ui->lpFIR->setValueRange(5, 1U, 56000U); // will be dynamically recalculated
     ui->swInterpLabel->setText(QString::fromUtf8("S\u2191"));
     ui->lpFIRInterpolationLabel->setText(QString::fromUtf8("\u2191"));
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     blockApplySettings(true);
     displaySettings();
     blockApplySettings(false);
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
 }
~PlutoSDROutputGUI()
PlutoSDROutputGUI::~PlutoSDROutputGUI () virtual
Definition at line 83 of file plutosdroutputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void PlutoSDROutputGUI::blockApplySettings (bool block) private
Definition at line 368 of file plutosdroutputgui.cpp.
References m_doApplySettings.
Referenced by deserialize(), handleMessage(), and PlutoSDROutputGUI().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool PlutoSDROutputGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 125 of file plutosdroutputgui.cpp.
References blockApplySettings(), PlutoSDROutputSettings::deserialize(), displaySettings(), m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data))
     {
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         sendSettings(true);
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void PlutoSDROutputGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 88 of file plutosdroutputgui.cpp.
 {
     delete this;
 }
displaySampleRate()
void PlutoSDROutputGUI::displaySampleRate () private
Definition at line 290 of file plutosdroutputgui.cpp.
References arg(), PlutoSDROutputSettings::m_devSampleRate, PlutoSDROutputSettings::m_log2Interp, m_sampleRateMode, m_settings, DevicePlutoSDR::srHighLimitFreq, DevicePlutoSDR::srLowLimitFreq, and ui.
Referenced by displaySettings(), on_sampleRateMode_toggled(), on_swInterp_currentIndexChanged(), and updateSampleRateAndFrequency().
 {
     ui->sampleRate->blockSignals(true);
     if (m_sampleRateMode)
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(60,60,60); }");
         ui->sampleRateMode->setText("SR");
         ui->sampleRate->setValueRange(8, DevicePlutoSDR::srLowLimitFreq, DevicePlutoSDR::srHighLimitFreq);
         ui->sampleRate->setValue(m_settings.m_devSampleRate);
         ui->sampleRate->setToolTip("Host to device sample rate (S/s)");
         ui->deviceRateText->setToolTip("Baseband sample rate (S/s)");
         uint32_t basebandSampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Interp);
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(basebandSampleRate / 1000.0f, 'g', 5)));
     }
     else
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(50,50,50); }");
         ui->sampleRateMode->setText("BB");
         ui->sampleRate->setValueRange(8, DevicePlutoSDR::srLowLimitFreq/(1<<m_settings.m_log2Interp), DevicePlutoSDR::srHighLimitFreq/(1<<m_settings.m_log2Interp));
         ui->sampleRate->setValue(m_settings.m_devSampleRate/(1<<m_settings.m_log2Interp));
         ui->sampleRate->setToolTip("Baseband sample rate (S/s)");
         ui->deviceRateText->setToolTip("Host to device sample rate (S/s)");
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_settings.m_devSampleRate / 1000.0f, 'g', 5)));
     }
     ui->sampleRate->blockSignals(false);
 }
displaySettings()
void PlutoSDROutputGUI::displaySettings () private
Definition at line 319 of file plutosdroutputgui.cpp.
References arg(), displaySampleRate(), PlutoSDROutputSettings::m_antennaPath, PlutoSDROutputSettings::m_att, PlutoSDROutputSettings::m_centerFrequency, PlutoSDROutputSettings::m_log2Interp, PlutoSDROutputSettings::m_LOppmTenths, PlutoSDROutputSettings::m_lpfBW, PlutoSDROutputSettings::m_lpfFIRBW, PlutoSDROutputSettings::m_lpfFIREnable, PlutoSDROutputSettings::m_lpfFIRGain, PlutoSDROutputSettings::m_lpfFIRlog2Interp, m_settings, PlutoSDROutputSettings::m_transverterDeltaFrequency, PlutoSDROutputSettings::m_transverterMode, setFIRBWLimits(), setSampleRateLimits(), ui, and updateFrequencyLimits().
Referenced by deserialize(), handleMessage(), PlutoSDROutputGUI(), and setCenterFrequency().
 {
     ui->transverter->setDeltaFrequency(m_settings.m_transverterDeltaFrequency);
     ui->transverter->setDeltaFrequencyActive(m_settings.m_transverterMode);
     updateFrequencyLimits();
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     displaySampleRate();
     ui->loPPM->setValue(m_settings.m_LOppmTenths);
     ui->loPPMText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     ui->swInterp->setCurrentIndex(m_settings.m_log2Interp);
     ui->lpf->setValue(m_settings.m_lpfBW / 1000);
     ui->lpFIREnable->setChecked(m_settings.m_lpfFIREnable);
     ui->lpFIR->setValue(m_settings.m_lpfFIRBW / 1000);
     ui->lpFIRInterpolation->setCurrentIndex(m_settings.m_lpfFIRlog2Interp);
     ui->lpFIRGain->setCurrentIndex((m_settings.m_lpfFIRGain + 6)/6);
     ui->lpFIRInterpolation->setEnabled(m_settings.m_lpfFIREnable);
     ui->lpFIRGain->setEnabled(m_settings.m_lpfFIREnable);
     ui->att->setValue(m_settings.m_att);
     ui->attText->setText(QString("%1 dB").arg(QString::number(m_settings.m_att*0.25, 'f', 2)));
     ui->antenna->setCurrentIndex((int) m_settings.m_antennaPath);
     setFIRBWLimits();
     setSampleRateLimits();
 }
getCenterFrequency()
qint64 PlutoSDROutputGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 108 of file plutosdroutputgui.cpp.
References PlutoSDROutputSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* PlutoSDROutputGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 53 of file plutosdroutputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString PlutoSDROutputGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 98 of file plutosdroutputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void PlutoSDROutputGUI::handleInputMessages () private slot
Definition at line 464 of file plutosdroutputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), setFIRBWLimits(), and updateSampleRateAndFrequency().
Referenced by PlutoSDROutputGUI().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("PlutoSDROutputGUI::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("PlutoSDROutputGUI::handleInputMessages: DSPSignalNotification: SampleRate: %d, CenterFrequency: %llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             setFIRBWLimits();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool PlutoSDROutputGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 142 of file plutosdroutputgui.cpp.
References blockApplySettings(), displaySettings(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getDevSampleRate(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getLoPPMTenths(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getLpfFirbw(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getLpfFiRlog2IntDec(), PlutoSDROutput::MsgConfigurePlutoSDR::getSettings(), PlutoSDROutput::MsgStartStop::getStartStop(), DevicePlutoSDRShared::MsgCrossReportToBuddy::isLpfFirEnable(), PlutoSDROutputSettings::m_devSampleRate, PlutoSDROutputSettings::m_LOppmTenths, PlutoSDROutputSettings::m_lpfFIRBW, PlutoSDROutputSettings::m_lpfFIREnable, PlutoSDROutputSettings::m_lpfFIRlog2Interp, m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     (void) message;
     if (PlutoSDROutput::MsgConfigurePlutoSDR::match(message))
     {
         const PlutoSDROutput::MsgConfigurePlutoSDR& cfg = (PlutoSDROutput::MsgConfigurePlutoSDR&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (DevicePlutoSDRShared::MsgCrossReportToBuddy::match(message)) // message from buddy
     {
         DevicePlutoSDRShared::MsgCrossReportToBuddy& conf = (DevicePlutoSDRShared::MsgCrossReportToBuddy&) message;
         m_settings.m_devSampleRate = conf.getDevSampleRate();
         m_settings.m_lpfFIRlog2Interp = conf.getLpfFiRlog2IntDec();
         m_settings.m_lpfFIRBW = conf.getLpfFirbw();
         m_settings.m_LOppmTenths = conf.getLoPPMTenths();
         m_settings.m_lpfFIREnable = conf.isLpfFirEnable();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (PlutoSDROutput::MsgStartStop::match(message))
     {
         PlutoSDROutput::MsgStartStop& notif = (PlutoSDROutput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_antenna_currentIndexChanged
void PlutoSDROutputGUI::on_antenna_currentIndexChanged (int index) private slot
Definition at line 268 of file plutosdroutputgui.cpp.
References PlutoSDROutputSettings::m_antennaPath, m_settings, PlutoSDROutputSettings::RFPATH_END, and sendSettings().
 {
     m_settings.m_antennaPath = (PlutoSDROutputSettings::RFPath) (index < PlutoSDROutputSettings::RFPATH_END ? index : 0);
     sendSettings();
 }
on_att_valueChanged
void PlutoSDROutputGUI::on_att_valueChanged (int value) private slot
Definition at line 261 of file plutosdroutputgui.cpp.
References arg(), PlutoSDROutputSettings::m_att, m_settings, sendSettings(), and ui.
 {
     ui->attText->setText(QString("%1 dB").arg(QString::number(value*0.25, 'f', 2)));
     m_settings.m_att = value;
     sendSettings();
 }
on_centerFrequency_changed
void PlutoSDROutputGUI::on_centerFrequency_changed (quint64 value) private slot
Definition at line 191 of file plutosdroutputgui.cpp.
References PlutoSDROutputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_loPPM_valueChanged
void PlutoSDROutputGUI::on_loPPM_valueChanged (int value) private slot
Definition at line 197 of file plutosdroutputgui.cpp.
References arg(), PlutoSDROutputSettings::m_LOppmTenths, m_settings, sendSettings(), and ui.
 {
     ui->loPPMText->setText(QString("%1").arg(QString::number(value/10.0, 'f', 1)));
     m_settings.m_LOppmTenths = value;
     sendSettings();
 }
on_lpf_changed
void PlutoSDROutputGUI::on_lpf_changed (quint64 value) private slot
Definition at line 228 of file plutosdroutputgui.cpp.
References PlutoSDROutputSettings::m_lpfBW, m_settings, and sendSettings().
 {
     m_settings.m_lpfBW = value * 1000;
     sendSettings();
 }
on_lpFIR_changed
void PlutoSDROutputGUI::on_lpFIR_changed (quint64 value) private slot
Definition at line 242 of file plutosdroutputgui.cpp.
References PlutoSDROutputSettings::m_lpfFIRBW, m_settings, and sendSettings().
 {
     m_settings.m_lpfFIRBW = value * 1000;
     sendSettings();
 }
on_lpFIREnable_toggled
void PlutoSDROutputGUI::on_lpFIREnable_toggled (bool checked) private slot
Definition at line 234 of file plutosdroutputgui.cpp.
References PlutoSDROutputSettings::m_lpfFIREnable, m_settings, sendSettings(), and ui.
 {
     m_settings.m_lpfFIREnable = checked;
     ui->lpFIRInterpolation->setEnabled(checked);
     ui->lpFIRGain->setEnabled(checked);
     sendSettings();
 }
on_lpFIRGain_currentIndexChanged
void PlutoSDROutputGUI::on_lpFIRGain_currentIndexChanged (int index) private slot
Definition at line 255 of file plutosdroutputgui.cpp.
References PlutoSDROutputSettings::m_lpfFIRGain, m_settings, and sendSettings().
 {
     m_settings.m_lpfFIRGain = 6*(index > 1 ? 1 : index) - 6;
     sendSettings();
 }
on_lpFIRInterpolation_currentIndexChanged
void PlutoSDROutputGUI::on_lpFIRInterpolation_currentIndexChanged (int index) private slot
Definition at line 248 of file plutosdroutputgui.cpp.
References PlutoSDROutputSettings::m_lpfFIRlog2Interp, m_settings, sendSettings(), and setSampleRateLimits().
 {
     m_settings.m_lpfFIRlog2Interp = index > 2 ? 2 : index;
     setSampleRateLimits();
     sendSettings();
 }
on_sampleRate_changed
void PlutoSDROutputGUI::on_sampleRate_changed (quint64 value) private slot
Definition at line 217 of file plutosdroutputgui.cpp.
References PlutoSDROutputSettings::m_devSampleRate, PlutoSDROutputSettings::m_log2Interp, m_sampleRateMode, m_settings, and sendSettings().
 {
     m_settings.m_devSampleRate = value;
     if (!m_sampleRateMode) {
         m_settings.m_devSampleRate <<= m_settings.m_log2Interp;
     }
     sendSettings();
 }
on_sampleRateMode_toggled
void PlutoSDROutputGUI::on_sampleRateMode_toggled (bool checked) private slot
Definition at line 284 of file plutosdroutputgui.cpp.
References displaySampleRate(), and m_sampleRateMode.
 {
     m_sampleRateMode = checked;
     displaySampleRate();
 }
on_startStop_toggled
void PlutoSDROutputGUI::on_startStop_toggled (bool checked) private slot
Definition at line 182 of file plutosdroutputgui.cpp.
References PlutoSDROutput::MsgStartStop::create(), DeviceSampleSink::getInputMessageQueue(), m_doApplySettings, m_sampleSink, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         PlutoSDROutput::MsgStartStop *message = PlutoSDROutput::MsgStartStop::create(checked);
         m_sampleSink->getInputMessageQueue()->push(message);
     }
 }
on_swInterp_currentIndexChanged
void PlutoSDROutputGUI::on_swInterp_currentIndexChanged (int index) private slot
Definition at line 204 of file plutosdroutputgui.cpp.
References displaySampleRate(), PlutoSDROutputSettings::m_devSampleRate, PlutoSDROutputSettings::m_log2Interp, m_sampleRateMode, m_settings, sendSettings(), and ui.
 {
     m_settings.m_log2Interp = index > 5 ? 5 : index;
     displaySampleRate();
     m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     if (!m_sampleRateMode) {
         m_settings.m_devSampleRate <<= m_settings.m_log2Interp;
     }
     sendSettings();
 }
on_transverter_clicked
void PlutoSDROutputGUI::on_transverter_clicked () private slot
Definition at line 274 of file plutosdroutputgui.cpp.
References PlutoSDROutputSettings::m_centerFrequency, m_settings, PlutoSDROutputSettings::m_transverterDeltaFrequency, PlutoSDROutputSettings::m_transverterMode, sendSettings(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("PlutoSDROutputGUI::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     m_settings.m_centerFrequency = ui->centerFrequency->getValueNew()*1000;
     sendSettings();
 }
openDeviceSettingsDialog
void PlutoSDROutputGUI::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 500 of file plutosdroutputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), PlutoSDROutputSettings::m_reverseAPIAddress, PlutoSDROutputSettings::m_reverseAPIDeviceIndex, PlutoSDROutputSettings::m_reverseAPIPort, m_settings, PlutoSDROutputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by PlutoSDROutputGUI().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void PlutoSDROutputGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 103 of file plutosdroutputgui.cpp.
Referenced by deserialize().
 {
 }
sendSettings()
void PlutoSDROutputGUI::sendSettings (bool forceSettings = false) private
Definition at line 350 of file plutosdroutputgui.cpp.
References m_forceSettings, and m_updateTimer.
Referenced by deserialize(), on_antenna_currentIndexChanged(), on_att_valueChanged(), on_centerFrequency_changed(), on_loPPM_valueChanged(), on_lpf_changed(), on_lpFIR_changed(), on_lpFIREnable_toggled(), on_lpFIRGain_currentIndexChanged(), on_lpFIRInterpolation_currentIndexChanged(), on_sampleRate_changed(), on_swInterp_currentIndexChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), and setCenterFrequency().
 {
     m_forceSettings = forceSettings;
     if(!m_updateTimer.isActive()) { m_updateTimer.start(100); }
 }
serialize()
QByteArray PlutoSDROutputGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 120 of file plutosdroutputgui.cpp.
References m_settings, and PlutoSDROutputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void PlutoSDROutputGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 113 of file plutosdroutputgui.cpp.
References displaySettings(), PlutoSDROutputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setFIRBWLimits()
void PlutoSDROutputGUI::setFIRBWLimits () private
Definition at line 431 of file plutosdroutputgui.cpp.
References DevicePlutoSDR::firBWHighLimitFactor, DevicePlutoSDR::firBWLowLimitFactor, PlutoSDROutputSettings::m_lpfFIRBW, m_sampleSink, m_settings, and ui.
Referenced by displaySettings(), and handleInputMessages().
 {
     float high = DevicePlutoSDR::firBWHighLimitFactor * ((PlutoSDROutput *) m_sampleSink)->getFIRSampleRate();
     float low = DevicePlutoSDR::firBWLowLimitFactor * ((PlutoSDROutput *) m_sampleSink)->getFIRSampleRate();
     ui->lpFIR->setValueRange(5, (int(low)/1000)+1, (int(high)/1000)+1);
     ui->lpFIR->setValue(m_settings.m_lpfFIRBW/1000);
 }
setName()
void PlutoSDROutputGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 93 of file plutosdroutputgui.cpp.
 {
     setObjectName(name);
 }
setSampleRateLimits()
void PlutoSDROutputGUI::setSampleRateLimits () private
Definition at line 439 of file plutosdroutputgui.cpp.
References PlutoSDROutputSettings::m_devSampleRate, m_settings, DevicePlutoSDR::srHighLimitFreq, DevicePlutoSDR::srLowLimitFreq, and ui.
Referenced by displaySettings(), and on_lpFIRInterpolation_currentIndexChanged().
 {
     uint32_t low = ui->lpFIREnable->isChecked() ? DevicePlutoSDR::srLowLimitFreq / (1<<ui->lpFIRInterpolation->currentIndex()) : DevicePlutoSDR::srLowLimitFreq;
     ui->sampleRate->setValueRange(8, low, DevicePlutoSDR::srHighLimitFreq);
     ui->sampleRate->setValue(m_settings.m_devSampleRate);
 }
updateFrequencyLimits()
void PlutoSDROutputGUI::updateFrequencyLimits () private
Definition at line 446 of file plutosdroutputgui.cpp.
References m_sampleSink, m_settings, PlutoSDROutputSettings::m_transverterDeltaFrequency, PlutoSDROutputSettings::m_transverterMode, and ui.
Referenced by displaySettings(), on_transverter_clicked(), and PlutoSDROutputGUI().
 {
     qint64 minLimit, maxLimit;
     // values in kHz
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     ((PlutoSDROutput *) m_sampleSink)->getLORange(minLimit, maxLimit);
     minLimit = minLimit/1000 + deltaFrequency;
     maxLimit = maxLimit/1000 + deltaFrequency;
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("PlutoSDRInputGui::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void PlutoSDROutputGUI::updateHardware () private slot
Definition at line 356 of file plutosdroutputgui.cpp.
References PlutoSDROutput::MsgConfigurePlutoSDR::create(), DeviceSampleSink::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSink, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by PlutoSDROutputGUI().
 {
     if (m_doApplySettings)
     {
         qDebug() << "PlutoSDROutputGUI::updateHardware";
         PlutoSDROutput::MsgConfigurePlutoSDR* message = PlutoSDROutput::MsgConfigurePlutoSDR::create(m_settings, m_forceSettings);
         m_sampleSink->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void PlutoSDROutputGUI::updateSampleRateAndFrequency () private
Definition at line 493 of file plutosdroutputgui.cpp.
References displaySampleRate(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), and GLSpectrum::setSampleRate().
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     displaySampleRate();
 }
updateStatus
void PlutoSDROutputGUI::updateStatus () private slot
Definition at line 373 of file plutosdroutputgui.cpp.
References arg(), DeviceAPI::errorMessage(), DeviceAPI::isBuddyLeader(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, m_sampleSink, m_statusCounter, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by PlutoSDROutputGUI().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
     if (m_statusCounter % 2 == 0) // 1s
     {
         uint32_t dacRate = ((PlutoSDROutput *) m_sampleSink)->getDACSampleRate();
         if (dacRate < 100000000) {
             ui->dacRateLabel->setText(tr("%1k").arg(QString::number(dacRate / 1000.0f, 'g', 5)));
         } else {
             ui->dacRateLabel->setText(tr("%1M").arg(QString::number(dacRate / 1000000.0f, 'g', 5)));
         }
     }
     if (m_statusCounter % 4 == 0) // 2s
     {
         std::string rssiStr;
         ((PlutoSDROutput *) m_sampleSink)->getRSSI(rssiStr);
         ui->rssiText->setText(tr("-%1").arg(QString::fromStdString(rssiStr)));
     }
     if (m_statusCounter % 10 == 0) // 5s
     {
         if (m_deviceUISet->m_deviceAPI->isBuddyLeader()) {
             ((PlutoSDROutput *) m_sampleSink)->fetchTemperature();
         }
         ui->temperatureText->setText(tr("%1C").arg(QString::number(((PlutoSDROutput *) m_sampleSink)->getTemperature(), 'f', 0)));
     }
     m_statusCounter++;
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 PlutoSDROutputGUI::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 66 of file plutosdroutputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* PlutoSDROutputGUI::m_deviceUISet private
Definition at line 58 of file plutosdroutputgui.h.
Referenced by PlutoSDROutputGUI(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool PlutoSDROutputGUI::m_doApplySettings private
Definition at line 68 of file plutosdroutputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_forceSettings
bool PlutoSDROutputGUI::m_forceSettings private
Definition at line 61 of file plutosdroutputgui.h.
Referenced by sendSettings(), and updateHardware().
m_inputMessageQueue
MessageQueue PlutoSDROutputGUI::m_inputMessageQueue private
Definition at line 70 of file plutosdroutputgui.h.
Referenced by handleInputMessages(), and PlutoSDROutputGUI().
m_lastEngineState
int PlutoSDROutputGUI::m_lastEngineState private
Definition at line 67 of file plutosdroutputgui.h.
Referenced by updateStatus().
m_sampleRate
int PlutoSDROutputGUI::m_sampleRate private
Definition at line 65 of file plutosdroutputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateMode
bool PlutoSDROutputGUI::m_sampleRateMode private
true: device, false: base band sample rate update mode
Definition at line 60 of file plutosdroutputgui.h.
Referenced by displaySampleRate(), on_sampleRate_changed(), on_sampleRateMode_toggled(), and on_swInterp_currentIndexChanged().
m_sampleSink
DeviceSampleSink* PlutoSDROutputGUI::m_sampleSink private
Definition at line 64 of file plutosdroutputgui.h.
Referenced by on_startStop_toggled(), PlutoSDROutputGUI(), setFIRBWLimits(), updateFrequencyLimits(), updateHardware(), and updateStatus().
m_settings
PlutoSDROutputSettings PlutoSDROutputGUI::m_settings private
Definition at line 59 of file plutosdroutputgui.h.
Referenced by deserialize(), displaySampleRate(), displaySettings(), getCenterFrequency(), handleMessage(), on_antenna_currentIndexChanged(), on_att_valueChanged(), on_centerFrequency_changed(), on_loPPM_valueChanged(), on_lpf_changed(), on_lpFIR_changed(), on_lpFIREnable_toggled(), on_lpFIRGain_currentIndexChanged(), on_lpFIRInterpolation_currentIndexChanged(), on_sampleRate_changed(), on_swInterp_currentIndexChanged(), on_transverter_clicked(), openDeviceSettingsDialog(), serialize(), setCenterFrequency(), setFIRBWLimits(), setSampleRateLimits(), updateFrequencyLimits(), and updateHardware().
m_statusCounter
uint32_t PlutoSDROutputGUI::m_statusCounter private
Definition at line 69 of file plutosdroutputgui.h.
Referenced by updateStatus().
m_statusTimer
QTimer PlutoSDROutputGUI::m_statusTimer private
Definition at line 63 of file plutosdroutputgui.h.
Referenced by PlutoSDROutputGUI().
m_updateTimer
QTimer PlutoSDROutputGUI::m_updateTimer private
Definition at line 62 of file plutosdroutputgui.h.
Referenced by PlutoSDROutputGUI(), sendSettings(), and updateHardware().
ui
Ui::PlutoSDROutputGUI* PlutoSDROutputGUI::ui private
Definition at line 57 of file plutosdroutputgui.h.
Referenced by displaySampleRate(), displaySettings(), handleMessage(), on_att_valueChanged(), on_loPPM_valueChanged(), on_lpFIREnable_toggled(), on_swInterp_currentIndexChanged(), on_transverter_clicked(), PlutoSDROutputGUI(), setFIRBWLimits(), setSampleRateLimits(), updateFrequencyLimits(), updateStatus(), and ~PlutoSDROutputGUI().
The documentation for this class was generated from the following files:
plugins/samplesink/plutosdroutput/plutosdroutputgui.h
plugins/samplesink/plutosdroutput/plutosdroutputgui.cpp