SDRAngel: BladeRF2OutputPlugin Class Reference
BladeRF2OutputPlugin Class Reference
#include <bladerf2outputplugin.h>
Public Member Functions
BladeRF2OutputPlugin (QObject *parent=0)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "BladeRF2"
static const QString m_deviceTypeID = BLADERF2OUTPUT_DEVICE_TYPE_ID
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 28 of file bladerf2outputplugin.h.
Constructor & Destructor Documentation
BladeRF2OutputPlugin()
BladeRF2OutputPlugin::BladeRF2OutputPlugin (QObject * parent = 0) explicit
Definition at line 43 of file bladerf2outputplugin.cpp.
                                                           :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSinkPluginInstance()
DeviceSampleSink * BladeRF2OutputPlugin::createSampleSinkPluginInstance (const QString & sinkId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 145 of file bladerf2outputplugin.cpp.
References m_deviceTypeID.
 {
     if(sinkId == m_deviceTypeID)
     {
         BladeRF2Output* output = new BladeRF2Output(deviceAPI);
         return output;
     }
     else
     {
         return 0;
     }
 }
createSampleSinkPluginInstanceGUI()
PluginInstanceGUI * BladeRF2OutputPlugin::createSampleSinkPluginInstanceGUI (const QString & sinkId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 127 of file bladerf2outputplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSinks().
 {
     if(sinkId == m_deviceTypeID)
     {
         BladeRF2OutputGui* gui = new BladeRF2OutputGui(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSinks()
PluginInterface::SamplingDevices BladeRF2OutputPlugin::enumSampleSinks () virtual
Reimplemented from PluginInterface.
Definition at line 58 of file bladerf2outputplugin.cpp.
References arg(), createSampleSinkPluginInstanceGUI(), i, m_deviceTypeID, m_hardwareID, PluginInterface::SamplingDevice::PhysicalDevice, and PluginInterface::SamplingDevice::StreamSingleTx.
 {
     SamplingDevices result;
     struct bladerf_devinfo *devinfo = 0;
     int count = bladerf_get_device_list(&devinfo);
     if (devinfo)
     {
         for(int i = 0; i < count; i++)
         {
             struct bladerf *dev;
             int status = bladerf_open_with_devinfo(&dev, &devinfo[i]);
             if (status == BLADERF_ERR_NODEV)
             {
                 qCritical("Bladerf2OutputPlugin::enumSampleSinks: No device at index %d", i);
                 continue;
             }
             else if (status != 0)
             {
                 qCritical("Bladerf2OutputPlugin::enumSampleSinks: Failed to open device at index %d", i);
                 continue;
             }
             const char *boardName = bladerf_get_board_name(dev);
             if (strcmp(boardName, "bladerf2") == 0)
             {
                 unsigned int nbTxChannels = bladerf_get_channel_count(dev, BLADERF_TX);
                 for (unsigned int j = 0; j < nbTxChannels; j++)
                 {
                     qDebug("Blderf2InputPlugin::enumSampleSinks: device #%d (%s) channel %u", i, devinfo[i].serial, j);
                     QString displayedName(QString("BladeRF2[%1:%2] %3").arg(devinfo[i].instance).arg(j).arg(devinfo[i].serial));
                     result.append(SamplingDevice(displayedName,
                             m_hardwareID,
                             m_deviceTypeID,
                             QString(devinfo[i].serial),
                             i,
                             PluginInterface::SamplingDevice::PhysicalDevice,
                             PluginInterface::SamplingDevice::StreamSingleTx,
                             nbTxChannels,
                             j));
                 }
             }
             bladerf_close(dev);
         }
         bladerf_free_device_list(devinfo); // Valgrind memcheck
     }
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & BladeRF2OutputPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 48 of file bladerf2outputplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void BladeRF2OutputPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 53 of file bladerf2outputplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSink().
 {
     pluginAPI->registerSampleSink(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString BladeRF2OutputPlugin::m_deviceTypeID = BLADERF2OUTPUT_DEVICE_TYPE_ID static
Definition at line 49 of file bladerf2outputplugin.h.
Referenced by createSampleSinkPluginInstance(), createSampleSinkPluginInstanceGUI(), enumSampleSinks(), and initPlugin().
m_hardwareID
const QString BladeRF2OutputPlugin::m_hardwareID = "BladeRF2" static
Definition at line 48 of file bladerf2outputplugin.h.
Referenced by enumSampleSinks().
m_pluginDescriptor
const PluginDescriptor BladeRF2OutputPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("BladeRF2 Output"),
    QString("4.5.4"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 52 of file bladerf2outputplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesink/bladerf2output/bladerf2outputplugin.h
plugins/samplesink/bladerf2output/bladerf2outputplugin.cpp