SDRAngel: SWGSDRangel::SWGArgValue Class Reference
SWGSDRangel::SWGArgValue Class Reference
#include <SWGArgValue.h>
Public Member Functions
SWGArgValue ()
SWGArgValue (QString *json)
virtual ~SWGArgValue ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGArgValue * fromJson (QString &jsonString) override
QString * getKey ()
void setKey (QString *key)
QString * getValueType ()
void setValueType (QString *value_type)
QString * getValueString ()
void setValueString (QString *value_string)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * key
bool m_key_isSet
QString * value_type
bool m_value_type_isSet
QString * value_string
bool m_value_string_isSet
Detailed Description
Definition at line 32 of file SWGArgValue.h.
Constructor & Destructor Documentation
SWGArgValue() [1/2]
SWGSDRangel::SWGArgValue::SWGArgValue ()
Definition at line 30 of file SWGArgValue.cpp.
References key, m_key_isSet, m_value_string_isSet, m_value_type_isSet, value_string, and value_type.
{
     key = nullptr;
     m_key_isSet = false;
     value_type = nullptr;
     m_value_type_isSet = false;
     value_string = nullptr;
     m_value_string_isSet = false;
 }
SWGArgValue() [2/2]
SWGSDRangel::SWGArgValue::SWGArgValue (QString * json)
Definition at line 25 of file SWGArgValue.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGArgValue()
SWGSDRangel::SWGArgValue::~SWGArgValue () virtual
Definition at line 39 of file SWGArgValue.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGArgValue::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 86 of file SWGArgValue.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGArgValue::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 97 of file SWGArgValue.cpp.
References key, SWGSDRangel::toJsonValue(), value_string, and value_type.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(key != nullptr && *key != QString("")){
         toJsonValue(QString("key"), key, obj, QString("QString"));
     }
     if(value_type != nullptr && *value_type != QString("")){
         toJsonValue(QString("valueType"), value_type, obj, QString("QString"));
     }
     if(value_string != nullptr && *value_string != QString("")){
         toJsonValue(QString("valueString"), value_string, obj, QString("QString"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGArgValue::cleanup ()
Definition at line 54 of file SWGArgValue.cpp.
References key, value_string, and value_type.
Referenced by ~SWGArgValue().
                      {
     if(key != nullptr) {
         delete key;
     }
     if(value_type != nullptr) {
         delete value_type;
     }
     if(value_string != nullptr) {
         delete value_string;
     }
 }
fromJson()
SWGArgValue * SWGSDRangel::SWGArgValue::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 67 of file SWGArgValue.cpp.
References fromJsonObject().
Referenced by SWGArgValue().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGArgValue::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 76 of file SWGArgValue.cpp.
References key, SWGSDRangel::setValue(), value_string, and value_type.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&key, pJson["key"], "QString", "QString");
     ::SWGSDRangel::setValue(&value_type, pJson["valueType"], "QString", "QString");
     ::SWGSDRangel::setValue(&value_string, pJson["valueString"], "QString", "QString");
 }
getKey()
QString * SWGSDRangel::SWGArgValue::getKey ()
Definition at line 113 of file SWGArgValue.cpp.
References key.
                     {
     return key;
 }
getValueString()
QString * SWGSDRangel::SWGArgValue::getValueString ()
Definition at line 133 of file SWGArgValue.cpp.
References value_string.
Referenced by SoapySDROutput::webapiVariantFromArgValue(), and SoapySDRInput::webapiVariantFromArgValue().
{
     return value_string;
 }
getValueType()
QString * SWGSDRangel::SWGArgValue::getValueType ()
Definition at line 123 of file SWGArgValue.cpp.
References value_type.
Referenced by SoapySDROutput::webapiVariantFromArgValue(), and SoapySDRInput::webapiVariantFromArgValue().
{
     return value_type;
 }
init()
void SWGSDRangel::SWGArgValue::init ()
Definition at line 44 of file SWGArgValue.cpp.
References key, m_key_isSet, m_value_string_isSet, m_value_type_isSet, value_string, and value_type.
Referenced by SWGArgValue().
                   {
     key = new QString("");
     m_key_isSet = false;
     value_type = new QString("");
     m_value_type_isSet = false;
     value_string = new QString("");
     m_value_string_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGArgValue::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 144 of file SWGArgValue.cpp.
References key, value_string, and value_type.
                   {
     bool isObjectUpdated = false;
     do{
         if(key != nullptr && *key != QString("")){ isObjectUpdated = true; break;}
         if(value_type != nullptr && *value_type != QString("")){ isObjectUpdated = true; break;}
         if(value_string != nullptr && *value_string != QString("")){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setKey()
void SWGSDRangel::SWGArgValue::setKey (QString * key)
Definition at line 117 of file SWGArgValue.cpp.
References key, and m_key_isSet.
{
     this->key = key;
     this->m_key_isSet = true;
 }
setValueString()
void SWGSDRangel::SWGArgValue::setValueString (QString * value_string)
Definition at line 137 of file SWGArgValue.cpp.
References m_value_string_isSet, and value_string.
Referenced by SoapySDROutput::webapiFormatArgValue(), and SoapySDRInput::webapiFormatArgValue().
{
     this->value_string = value_string;
     this->m_value_string_isSet = true;
 }
setValueType()
void SWGSDRangel::SWGArgValue::setValueType (QString * value_type)
Definition at line 127 of file SWGArgValue.cpp.
References m_value_type_isSet, and value_type.
Referenced by SoapySDROutput::webapiFormatArgValue(), and SoapySDRInput::webapiFormatArgValue().
{
     this->value_type = value_type;
     this->m_value_type_isSet = true;
 }
Member Data Documentation
key
QString* SWGSDRangel::SWGArgValue::key private
Definition at line 58 of file SWGArgValue.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getKey(), init(), isSet(), setKey(), and SWGArgValue().
m_key_isSet
bool SWGSDRangel::SWGArgValue::m_key_isSet private
Definition at line 59 of file SWGArgValue.h.
Referenced by init(), setKey(), and SWGArgValue().
m_value_string_isSet
bool SWGSDRangel::SWGArgValue::m_value_string_isSet private
Definition at line 65 of file SWGArgValue.h.
Referenced by init(), setValueString(), and SWGArgValue().
m_value_type_isSet
bool SWGSDRangel::SWGArgValue::m_value_type_isSet private
Definition at line 62 of file SWGArgValue.h.
Referenced by init(), setValueType(), and SWGArgValue().
value_string
QString* SWGSDRangel::SWGArgValue::value_string private
Definition at line 64 of file SWGArgValue.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getValueString(), init(), isSet(), setValueString(), and SWGArgValue().
value_type
QString* SWGSDRangel::SWGArgValue::value_type private
Definition at line 61 of file SWGArgValue.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getValueType(), init(), isSet(), setValueType(), and SWGArgValue().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGArgValue.h
swagger/sdrangel/code/qt5/client/SWGArgValue.cpp