SDRAngel: BasebandSampleSink::MsgThreadedSink Class Reference
BasebandSampleSink::MsgThreadedSink Class Reference
#include <basebandsamplesink.h>
Public Member Functions
const QThread * getThread () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgThreadedSink * create (const QThread *thread)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgThreadedSink (const QThread *thread)
Private Attributes
const QThread * m_thread
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Used to notify on which thread the sample sink is now running (with ThreadedSampleSink)
Definition at line 34 of file basebandsamplesink.h.
Constructor & Destructor Documentation
MsgThreadedSink()
BasebandSampleSink::MsgThreadedSink::MsgThreadedSink (const QThread * thread) inline private
Definition at line 48 of file basebandsamplesink.h.
                                                :
             Message(),
             m_thread(thread)
         { }
Member Function Documentation
create()
static MsgThreadedSink* BasebandSampleSink::MsgThreadedSink::create (const QThread * thread) inline static
Definition at line 40 of file basebandsamplesink.h.
Referenced by ThreadedBasebandSampleSink::ThreadedBasebandSampleSink().
         {
             return new MsgThreadedSink(thread);
         }
getThread()
const QThread* BasebandSampleSink::MsgThreadedSink::getThread () const inline
Definition at line 38 of file basebandsamplesink.h.
Referenced by AMDemod::handleMessage(), WFMDemod::handleMessage(), SSBDemod::handleMessage(), NFMDemod::handleMessage(), and FreeDVDemod::handleMessage().
 { return m_thread; }
Member Data Documentation
m_thread
const QThread* BasebandSampleSink::MsgThreadedSink::m_thread private
Definition at line 46 of file basebandsamplesink.h.
The documentation for this class was generated from the following file:
sdrbase/dsp/basebandsamplesink.h