SDRAngel: leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS > Struct Template Reference
leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS > Struct Template Reference
#include <convolutional.h>
Public Types
typedef u8 hardsymbol
typedef u8 decoded_byte
Public Member Functions
u8 SYMVAL (const hardsymbol *s)
u8 SYMVAL (const softsymbol *s)
deconvol_poly ()
int run (const Tin *pin, const u8 remap[], decoded_byte *pout, int nb)
Private Attributes
Thist hist
Detailed Description
template<typename Tin, typename Thist, Thist POLY_DECONVOL, Thist POLY_ERRORS>
struct leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS >
Definition at line 36 of file convolutional.h.
Member Typedef Documentation
decoded_byte
template<typename Tin , typename Thist , Thist POLY_DECONVOL, Thist POLY_ERRORS> typedef u8 leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS >::decoded_byte
Definition at line 44 of file convolutional.h.
hardsymbol
template<typename Tin , typename Thist , Thist POLY_DECONVOL, Thist POLY_ERRORS> typedef u8 leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS >::hardsymbol
Definition at line 38 of file convolutional.h.
Constructor & Destructor Documentation
deconvol_poly()
template<typename Tin , typename Thist , Thist POLY_DECONVOL, Thist POLY_ERRORS> leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS >::deconvol_poly () inline
Definition at line 46 of file convolutional.h.
 : hist(0) {}
Member Function Documentation
run()
template<typename Tin , typename Thist , Thist POLY_DECONVOL, Thist POLY_ERRORS> int leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS >::run (const Tin * pin, const u8 remap[], decoded_byte * pout, int nb) inline
Definition at line 51 of file convolutional.h.
References leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS >::hist, leansdr::parity(), and leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS >::SYMVAL().
     {
         int nerrors = 0;
         int halfway = nb / 2;
         for (; nb--; ++pout)
         {
             decoded_byte byte = 0;
             for (int bit = 8; bit--; ++pin)
             {
                 hist = (hist << 2) | remap[SYMVAL(pin)];
                 byte = (byte << 1) | parity(hist & POLY_DECONVOL);
                 if (nb < halfway)
                     nerrors += parity(hist & POLY_ERRORS);
             }
             *pout = byte;
         }
         return nerrors;
     }
SYMVAL() [1/2]
template<typename Tin , typename Thist , Thist POLY_DECONVOL, Thist POLY_ERRORS> u8 leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS >::SYMVAL (const hardsymbol * s) inline
Definition at line 41 of file convolutional.h.
Referenced by leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS >::run(), and leansdr::deconvol_poly2< Tin, uint32_t, uint64_t, 0x3ba, 0x38f70 >::run().
 { return *s; }
SYMVAL() [2/2]
template<typename Tin , typename Thist , Thist POLY_DECONVOL, Thist POLY_ERRORS> u8 leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS >::SYMVAL (const softsymbol * s) inline
Definition at line 42 of file convolutional.h.
References leansdr::softsymbol::symbol.
 { return s->symbol; }
Member Data Documentation
hist
template<typename Tin , typename Thist , Thist POLY_DECONVOL, Thist POLY_ERRORS> Thist leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS >::hist private
Definition at line 75 of file convolutional.h.
Referenced by leansdr::convol_multipoly< uint16_t, 16 >::encode(), leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS >::run(), and leansdr::convol_poly2< Thist, POLY1, POLY2 >::run().
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/convolutional.h