SDRAngel: DSDDemod Class Reference
DSDDemod Class Reference
#include <dsddemod.h>
Classes
struct MagSqLevelsStore
class MsgConfigureChannelizer
class MsgConfigureDSDDemod
class MsgConfigureMyPosition
Public Member Functions
DSDDemod (DeviceAPI *deviceAPI)
~DSDDemod ()
virtual void destroy ()
void setScopeXYSink (BasebandSampleSink *sampleSink)
void configureMyPosition (MessageQueue *messageQueue, float myLatitude, float myLongitude)
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool po)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
double getMagSq ()
bool getSquelchOpen () const
const DSDDecoder & getDecoder () const
void getMagSqLevels (double &avg, double &peak, int &nbSamples)
const char * updateAndGetStatusText ()
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.dsddemod"
static const QString m_channelId = "DSDDemod"
Private Types
enum SignalFormat {
signalFormatNone, signalFormatDMR, signalFormatDStar, signalFormatDPMR,
signalFormatYSF, signalFormatNXDN
}
enum RateState { RSInitialFill, RSRunning }
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applyAudioSampleRate (int sampleRate)
void applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const DSDDemodSettings &settings, bool force=false)
void formatStatusText ()
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const DSDDemodSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const DSDDemodSettings &settings, bool force)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
int m_inputSampleRate
int m_inputFrequencyOffset
DSDDemodSettings m_settings
quint32 m_audioSampleRate
NCO m_nco
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
int m_sampleCount
int m_squelchCount
int m_squelchGate
double m_squelchLevel
bool m_squelchOpen
DoubleBufferFIFO< Real > m_squelchDelayLine
MovingAverageUtil< Real, double, 16 > m_movingAverage
double m_magsq
double m_magsqSum
double m_magsqPeak
int m_magsqCount
MagSqLevelsStore m_magSqLevelStore
SampleVector m_scopeSampleBuffer
AudioVector m_audioBuffer
uint m_audioBufferFill
FixReal * m_sampleBuffer
samples ring buffer
int m_sampleBufferIndex
int m_scaleFromShort
AudioFifo m_audioFifo1
AudioFifo m_audioFifo2
BasebandSampleSink * m_scopeXY
bool m_scopeEnabled
DSDDecoder m_dsdDecoder
char m_formatStatusText [82+1]
Fixed signal format dependent status text.
SignalFormat m_signalFormat
Used to keep formatting during successive calls for the same standard type.
PhaseDiscriminators m_phaseDiscri
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
QMutex m_settingsMutex
Static Private Attributes
static const int m_udpBlockSize = 512
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 50 of file dsddemod.h.
Member Enumeration Documentation
RateState
enum DSDDemod::RateState private
Enumerator
RSInitialFill
RSRunning
Definition at line 213 of file dsddemod.h.
                    {
         RSInitialFill,
         RSRunning
     };
SignalFormat
enum DSDDemod::SignalFormat private
Enumerator
signalFormatNone
signalFormatDMR
signalFormatDStar
signalFormatDPMR
signalFormatYSF
signalFormatNXDN
Definition at line 181 of file dsddemod.h.
     {
         signalFormatNone,
         signalFormatDMR,
         signalFormatDStar,
         signalFormatDPMR,
         signalFormatYSF,
         signalFormatNXDN
     } SignalFormat;
Constructor & Destructor Documentation
DSDDemod()
DSDDemod::DSDDemod (DeviceAPI * deviceAPI)
Definition at line 54 of file dsddemod.cpp.
References AudioDeviceManager::addAudioSink(), DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), applyChannelSettings(), applySettings(), DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), m_audioBuffer, m_audioBufferFill, m_audioFifo1, m_audioFifo2, m_audioSampleRate, m_channelId, m_channelizer, m_deviceAPI, m_inputFrequencyOffset, m_inputSampleRate, m_magsq, m_magsqCount, m_magsqPeak, m_magsqSum, m_networkManager, m_sampleBuffer, m_sampleBufferIndex, m_scaleFromShort, m_settings, m_threadedChannelizer, networkManagerFinished(), and SDR_RX_SAMP_SZ.
Referenced by DSDDemod::MsgConfigureChannelizer::MsgConfigureChannelizer().
                                        :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(deviceAPI),
         m_inputSampleRate(48000),
         m_inputFrequencyOffset(0),
         m_interpolatorDistance(0.0f),
         m_interpolatorDistanceRemain(0.0f),
         m_sampleCount(0),
         m_squelchCount(0),
         m_squelchGate(0),
         m_squelchLevel(1e-4),
         m_squelchOpen(false),
         m_squelchDelayLine(24000),
         m_audioFifo1(48000),
         m_audioFifo2(48000),
         m_scopeXY(0),
         m_scopeEnabled(true),
         m_dsdDecoder(),
         m_signalFormat(signalFormatNone),
         m_settingsMutex(QMutex::Recursive)
 {
     setObjectName(m_channelId);
     m_audioBuffer.resize(1<<14);
     m_audioBufferFill = 0;
     m_sampleBuffer = new FixReal[1<<17]; // 128 kS
     m_sampleBufferIndex = 0;
     m_scaleFromShort = SDR_RX_SAMP_SZ < sizeof(short)*8 ? 1 : 1<<(SDR_RX_SAMP_SZ - sizeof(short)*8);
     m_magsq = 0.0f;
     m_magsqSum = 0.0f;
     m_magsqPeak = 0.0f;
     m_magsqCount = 0;
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSink(&m_audioFifo1, getInputMessageQueue());
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSink(&m_audioFifo2, getInputMessageQueue());
     m_audioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getOutputSampleRate();
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~DSDDemod()
DSDDemod::~DSDDemod ()
Definition at line 105 of file dsddemod.cpp.
References DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo1, m_audioFifo2, m_channelizer, m_deviceAPI, m_networkManager, m_sampleBuffer, m_threadedChannelizer, networkManagerFinished(), AudioDeviceManager::removeAudioSink(), DeviceAPI::removeChannelSink(), and DeviceAPI::removeChannelSinkAPI().
Referenced by DSDDemod::MsgConfigureChannelizer::MsgConfigureChannelizer().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     delete[] m_sampleBuffer;
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_audioFifo1);
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_audioFifo2);
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
 }
Member Function Documentation
applyAudioSampleRate()
void DSDDemod::applyAudioSampleRate (int sampleRate) private
Definition at line 433 of file dsddemod.cpp.
References m_audioSampleRate, m_dsdDecoder, and DSDDecoder::setUpsampling().
Referenced by applySettings(), and handleMessage().
 {
     int upsampling = sampleRate / 8000;
     qDebug("DSDDemod::applyAudioSampleRate: audio rate: %d upsample by %d", sampleRate, upsampling);
     if (sampleRate % 8000 != 0) {
         qDebug("DSDDemod::applyAudioSampleRate: audio will sound best with sample rates that are integer multiples of 8 kS/s");
     }
     m_dsdDecoder.setUpsampling(upsampling);
     m_audioSampleRate = sampleRate;
 }
applyChannelSettings()
void DSDDemod::applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 447 of file dsddemod.cpp.
References Interpolator::create(), m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_nco, DSDDemodSettings::m_rfBandwidth, m_settings, m_settingsMutex, and NCO::setFreq().
Referenced by DSDDemod(), handleMessage(), and start().
 {
     qDebug() << "DSDDemod::applyChannelSettings:"
             << " inputSampleRate: " << inputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if ((inputFrequencyOffset != m_inputFrequencyOffset) ||
         (inputSampleRate != m_inputSampleRate) || force)
     {
         m_nco.setFreq(-inputFrequencyOffset, inputSampleRate);
     }
     if ((inputSampleRate != m_inputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_interpolator.create(16, inputSampleRate, (m_settings.m_rfBandwidth) / 2.2);
         m_interpolatorDistanceRemain = 0;
         m_interpolatorDistance =  (Real) inputSampleRate / (Real) 48000;
         m_settingsMutex.unlock();
     }
     m_inputSampleRate = inputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applySettings()
void DSDDemod::applySettings (const DSDDemodSettings & settings, bool force = false) private
Definition at line 472 of file dsddemod.cpp.
References AudioDeviceManager::addAudioSink(), applyAudioSampleRate(), Interpolator::create(), DSDDecoder::enableCosineFiltering(), DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputDeviceIndex(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), DSDDemodSettings::m_audioDeviceName, m_audioFifo1, m_audioFifo2, DSDDemodSettings::m_audioMute, m_audioSampleRate, DSDDemodSettings::m_baudRate, DSDDemodSettings::m_demodGain, m_dsdDecoder, DSDDemodSettings::m_enableCosineFiltering, DSDDemodSettings::m_fmDeviation, DSDDemodSettings::m_highPassFilter, DSDDemodSettings::m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_phaseDiscri, DSDDemodSettings::m_pllLock, DSDDemodSettings::m_reverseAPIAddress, DSDDemodSettings::m_reverseAPIChannelIndex, DSDDemodSettings::m_reverseAPIDeviceIndex, DSDDemodSettings::m_reverseAPIPort, DSDDemodSettings::m_rfBandwidth, m_settings, m_settingsMutex, DSDDemodSettings::m_slot1On, DSDDemodSettings::m_slot2On, DSDDemodSettings::m_squelch, m_squelchCount, DSDDemodSettings::m_squelchGate, m_squelchGate, m_squelchLevel, DSDDemodSettings::m_syncOrConstellation, DSDDemodSettings::m_tdmaStereo, DSDDemodSettings::m_traceDecay, DSDDemodSettings::m_traceLengthMutliplier, DSDDemodSettings::m_traceStroke, DSDDemodSettings::m_useReverseAPI, DSDDemodSettings::m_volume, DSDDecoder::setAudioGain(), DSDDecoder::setBaudRate(), PhaseDiscriminators::setFMScaling(), DSDDecoder::setSymbolPLLLock(), DSDDecoder::setTDMAStereo(), DSDDecoder::useHPMbelib(), and webapiReverseSendSettings().
Referenced by DSDDemod(), and handleMessage().
 {
     qDebug() << "DSDDemod::applySettings: "
             << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
             << " m_rfBandwidth: " << settings.m_rfBandwidth
             << " m_fmDeviation: " << settings.m_fmDeviation
             << " m_demodGain: " << settings.m_demodGain
             << " m_volume: " << settings.m_volume
             << " m_baudRate: " << settings.m_baudRate
             << " m_squelchGate" << settings.m_squelchGate
             << " m_squelch: " << settings.m_squelch
             << " m_audioMute: " << settings.m_audioMute
             << " m_enableCosineFiltering: " << settings.m_enableCosineFiltering
             << " m_syncOrConstellation: " << settings.m_syncOrConstellation
             << " m_slot1On: " << settings.m_slot1On
             << " m_slot2On: " << settings.m_slot2On
             << " m_tdmaStereo: " << settings.m_tdmaStereo
             << " m_pllLock: " << settings.m_pllLock
             << " m_highPassFilter: "<< settings.m_highPassFilter
             << " m_audioDeviceName: " << settings.m_audioDeviceName
             << " m_traceLengthMutliplier: " << settings.m_traceLengthMutliplier
             << " m_traceStroke: " << settings.m_traceStroke
             << " m_traceDecay: " << settings.m_traceDecay
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if ((settings.m_inputFrequencyOffset != m_settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if ((settings.m_demodGain != m_settings.m_demodGain) || force) {
         reverseAPIKeys.append("demodGain");
     }
     if ((settings.m_audioMute != m_settings.m_audioMute) || force) {
         reverseAPIKeys.append("audioMute");
     }
     if ((settings.m_syncOrConstellation != m_settings.m_syncOrConstellation) || force) {
         reverseAPIKeys.append("syncOrConstellation");
     }
     if ((settings.m_slot1On != m_settings.m_slot1On) || force) {
         reverseAPIKeys.append("slot1On");
     }
     if ((settings.m_slot2On != m_settings.m_slot2On) || force) {
         reverseAPIKeys.append("slot2On");
     }
     if ((settings.m_demodGain != m_settings.m_demodGain) || force) {
         reverseAPIKeys.append("demodGain");
     }
     if ((settings.m_traceLengthMutliplier != m_settings.m_traceLengthMutliplier) || force) {
         reverseAPIKeys.append("traceLengthMutliplier");
     }
     if ((settings.m_rfBandwidth != m_settings.m_rfBandwidth) || force)
     {
         reverseAPIKeys.append("rfBandwidth");
         m_settingsMutex.lock();
         m_interpolator.create(16, m_inputSampleRate, (settings.m_rfBandwidth) / 2.2);
         m_interpolatorDistanceRemain = 0;
         m_interpolatorDistance =  (Real) m_inputSampleRate / (Real) 48000;
         //m_phaseDiscri.setFMScaling((float) settings.m_rfBandwidth / (float) settings.m_fmDeviation);
         m_settingsMutex.unlock();
     }
     if ((settings.m_fmDeviation != m_settings.m_fmDeviation) || force)
     {
         reverseAPIKeys.append("fmDeviation");
         m_phaseDiscri.setFMScaling(48000.0f / (2.0f*settings.m_fmDeviation));
     }
     if ((settings.m_squelchGate != m_settings.m_squelchGate) || force)
     {
         reverseAPIKeys.append("squelchGate");
         m_squelchGate = 480 * settings.m_squelchGate; // gate is given in 10s of ms at 48000 Hz audio sample rate
         m_squelchCount = 0; // reset squelch open counter
     }
     if ((settings.m_squelch != m_settings.m_squelch) || force)
     {
         reverseAPIKeys.append("squelch");
         // input is a value in dB
         m_squelchLevel = std::pow(10.0, settings.m_squelch / 10.0);
     }
     if ((settings.m_volume != m_settings.m_volume) || force)
     {
         reverseAPIKeys.append("volume");
         m_dsdDecoder.setAudioGain(settings.m_volume);
     }
     if ((settings.m_baudRate != m_settings.m_baudRate) || force)
     {
         reverseAPIKeys.append("baudRate");
         m_dsdDecoder.setBaudRate(settings.m_baudRate);
     }
     if ((settings.m_enableCosineFiltering != m_settings.m_enableCosineFiltering) || force)
     {
         reverseAPIKeys.append("enableCosineFiltering");
         m_dsdDecoder.enableCosineFiltering(settings.m_enableCosineFiltering);
     }
     if ((settings.m_tdmaStereo != m_settings.m_tdmaStereo) || force)
     {
         reverseAPIKeys.append("tdmaStereo");
         m_dsdDecoder.setTDMAStereo(settings.m_tdmaStereo);
     }
     if ((settings.m_pllLock != m_settings.m_pllLock) || force)
     {
         reverseAPIKeys.append("pllLock");
         m_dsdDecoder.setSymbolPLLLock(settings.m_pllLock);
     }
     if ((settings.m_highPassFilter != m_settings.m_highPassFilter) || force)
     {
         reverseAPIKeys.append("highPassFilter");
         m_dsdDecoder.useHPMbelib(settings.m_highPassFilter);
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force)
     {
         reverseAPIKeys.append("audioDeviceName");
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getOutputDeviceIndex(settings.m_audioDeviceName);
         //qDebug("AMDemod::applySettings: audioDeviceName: %s audioDeviceIndex: %d", qPrintable(settings.m_audioDeviceName), audioDeviceIndex);
         audioDeviceManager->addAudioSink(&m_audioFifo1, getInputMessageQueue(), audioDeviceIndex);
         audioDeviceManager->addAudioSink(&m_audioFifo2, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getOutputSampleRate(audioDeviceIndex);
         if (m_audioSampleRate != audioSampleRate) {
             applyAudioSampleRate(audioSampleRate);
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
configureMyPosition()
void DSDDemod::configureMyPosition (MessageQueue * messageQueue, float myLatitude, float myLongitude)
Definition at line 119 of file dsddemod.cpp.
References DSDDemod::MsgConfigureMyPosition::create(), and MessageQueue::push().
Referenced by setScopeXYSink(), and DSDDemodGUI::updateMyPosition().
 {
     Message* cmd = MsgConfigureMyPosition::create(myLatitude, myLongitude);
     messageQueue->push(cmd);
 }
deserialize()
bool DSDDemod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 624 of file dsddemod.cpp.
References DSDDemod::MsgConfigureDSDDemod::create(), DSDDemodSettings::deserialize(), BasebandSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and DSDDemodSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureDSDDemod *msg = MsgConfigureDSDDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureDSDDemod *msg = MsgConfigureDSDDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void DSDDemod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 101 of file dsddemod.h.
 { delete this; }
feed()
void DSDDemod::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool po) virtual
Implements BasebandSampleSink.
Definition at line 125 of file dsddemod.cpp.
References MovingAverageUtil< T, Total, N >::asDouble(), Interpolator::decimate(), DSDDecoder::enableMbelib(), BasebandSampleSink::feed(), DSDDecoder::getAudio1(), DSDDecoder::getAudio2(), DSDDecoder::getFilteredSample(), DSDDecoder::getMbeDVFrame1(), DSDDecoder::getMbeDVFrame2(), DSDDecoder::getMbeRateIndex(), DSDDecoder::getSamplesPerSymbol(), DSDDecoder::getSymbolSyncSample(), DSPEngine::instance(), m_audioFifo1, m_audioFifo2, DSDDemodSettings::m_audioMute, m_audioSampleRate, DSDDemodSettings::m_demodGain, m_dsdDecoder, DSDDemodSettings::m_enableCosineFiltering, DSDDemodSettings::m_highPassFilter, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_magsqCount, m_magsqPeak, m_magsqSum, m_movingAverage, m_nco, m_phaseDiscri, m_sampleBuffer, m_sampleBufferIndex, m_sampleCount, m_scaleFromShort, m_scopeEnabled, m_scopeSampleBuffer, m_scopeXY, m_settings, m_settingsMutex, DSDDemodSettings::m_slot1On, DSDDemodSettings::m_slot2On, m_squelchCount, m_squelchDelayLine, m_squelchGate, m_squelchLevel, m_squelchOpen, DSDDemodSettings::m_syncOrConstellation, DSDDemodSettings::m_tdmaStereo, DSDDemodSettings::m_volume, DSDDecoder::mbeDVReady1(), DSDDecoder::mbeDVReady2(), NCO::nextIQ(), PhaseDiscriminators::phaseDiscriminator(), DSPEngine::pushMbeFrame(), DSDDecoder::pushSample(), DoubleBufferFIFO< T >::readBack(), DSDDecoder::resetAudio1(), DSDDecoder::resetAudio2(), DSDDecoder::resetMbeDV1(), DSDDecoder::resetMbeDV2(), SDR_RX_SCALED, SDR_RX_SCALEF, AudioFifo::write(), and DoubleBufferFIFO< T >::write().
Referenced by setScopeXYSink().
 {
     (void) firstOfBurst;
     Complex ci;
     int samplesPerSymbol = m_dsdDecoder.getSamplesPerSymbol();
     m_settingsMutex.lock();
     m_scopeSampleBuffer.clear();
     m_dsdDecoder.enableMbelib(!DSPEngine::instance()->hasDVSerialSupport()); // disable mbelib if DV serial support is present and activated else enable it
     for (SampleVector::const_iterator it = begin; it != end; ++it)
     {
         Complex c(it->real(), it->imag());
         c *= m_nco.nextIQ();
         if (m_interpolator.decimate(&m_interpolatorDistanceRemain, c, &ci))
         {
             FixReal sample, delayedSample;
             qint16 sampleDSD;
             Real re = ci.real() / SDR_RX_SCALED;
             Real im = ci.imag() / SDR_RX_SCALED;
             Real magsq = re*re + im*im;
             m_movingAverage(magsq);
             m_magsqSum += magsq;
             if (magsq > m_magsqPeak)
             {
                 m_magsqPeak = magsq;
             }
             m_magsqCount++;
             Real demod = m_phaseDiscri.phaseDiscriminator(ci) * m_settings.m_demodGain; // [-1.0:1.0]
             m_sampleCount++;
             // AF processing
             if (m_movingAverage.asDouble() > m_squelchLevel)
             {
                 if (m_squelchGate > 0)
                 {
                     if (m_squelchCount < m_squelchGate*2) {
                         m_squelchCount++;
                     }
                     m_squelchDelayLine.write(demod);
                     m_squelchOpen = m_squelchCount > m_squelchGate;
                 }
                 else
                 {
                     m_squelchOpen = true;
                 }
             }
             else
             {
                 if (m_squelchGate > 0)
                 {
                     if (m_squelchCount > 0) {
                         m_squelchCount--;
                     }
                     m_squelchDelayLine.write(0);
                     m_squelchOpen = m_squelchCount > m_squelchGate;
                 }
                 else
                 {
                     m_squelchOpen = false;
                 }
             }
             if (m_squelchOpen)
             {
                 if (m_squelchGate > 0)
                 {
                     sampleDSD = m_squelchDelayLine.readBack(m_squelchGate) * 32768.0f;   // DSD decoder takes int16 samples
                     sample = m_squelchDelayLine.readBack(m_squelchGate) * SDR_RX_SCALEF; // scale to sample size
                 }
                 else
                 {
                     sampleDSD = demod * 32768.0f;   // DSD decoder takes int16 samples
                     sample = demod * SDR_RX_SCALEF; // scale to sample size
                 }
             }
             else
             {
                 sampleDSD = 0;
                 sample = 0;
             }
             m_dsdDecoder.pushSample(sampleDSD);
             if (m_settings.m_enableCosineFiltering) { // show actual input to FSK demod
                 sample = m_dsdDecoder.getFilteredSample() * m_scaleFromShort;
             }
             if (m_sampleBufferIndex < (1<<17)-1) {
                 m_sampleBufferIndex++;
             } else {
                 m_sampleBufferIndex = 0;
             }
             m_sampleBuffer[m_sampleBufferIndex] = sample;
             if (m_sampleBufferIndex < samplesPerSymbol) {
                 delayedSample = m_sampleBuffer[(1<<17) - samplesPerSymbol + m_sampleBufferIndex]; // wrap
             } else {
                 delayedSample = m_sampleBuffer[m_sampleBufferIndex - samplesPerSymbol];
             }
             if (m_settings.m_syncOrConstellation)
             {
                 Sample s(sample, m_dsdDecoder.getSymbolSyncSample() * m_scaleFromShort * 0.84);
                 m_scopeSampleBuffer.push_back(s);
             }
             else
             {
                 Sample s(sample, delayedSample); // I=signal, Q=signal delayed by 20 samples (2400 baud: lowest rate)
                 m_scopeSampleBuffer.push_back(s);
             }
             if (DSPEngine::instance()->hasDVSerialSupport())
             {
                 if ((m_settings.m_slot1On) && m_dsdDecoder.mbeDVReady1())
                 {
                     if (!m_settings.m_audioMute)
                     {
                         DSPEngine::instance()->pushMbeFrame(
                                 m_dsdDecoder.getMbeDVFrame1(),
                                 m_dsdDecoder.getMbeRateIndex(),
                                 m_settings.m_volume * 10.0,
                                 m_settings.m_tdmaStereo ? 1 : 3, // left or both channels
                                 m_settings.m_highPassFilter,
                                 m_audioSampleRate/8000, // upsample from native 8k
                                 &m_audioFifo1);
                     }
                     m_dsdDecoder.resetMbeDV1();
                 }
                 if ((m_settings.m_slot2On) && m_dsdDecoder.mbeDVReady2())
                 {
                     if (!m_settings.m_audioMute)
                     {
                         DSPEngine::instance()->pushMbeFrame(
                                 m_dsdDecoder.getMbeDVFrame2(),
                                 m_dsdDecoder.getMbeRateIndex(),
                                 m_settings.m_volume * 10.0,
                                 m_settings.m_tdmaStereo ? 2 : 3, // right or both channels
                                 m_settings.m_highPassFilter,
                                 m_audioSampleRate/8000, // upsample from native 8k
                                 &m_audioFifo2);
                     }
                     m_dsdDecoder.resetMbeDV2();
                 }
             }
 //            if (DSPEngine::instance()->hasDVSerialSupport() && m_dsdDecoder.mbeDVReady1())
 //            {
 //                if (!m_settings.m_audioMute)
 //                {
 //                    DSPEngine::instance()->pushMbeFrame(m_dsdDecoder.getMbeDVFrame1(), m_dsdDecoder.getMbeRateIndex(), m_settings.m_volume, &m_audioFifo1);
 //                }
 //
 //                m_dsdDecoder.resetMbeDV1();
 //            }
             m_interpolatorDistanceRemain += m_interpolatorDistance;
         }
     }
     if (!DSPEngine::instance()->hasDVSerialSupport())
     {
         if (m_settings.m_slot1On)
         {
             int nbAudioSamples;
             short *dsdAudio = m_dsdDecoder.getAudio1(nbAudioSamples);
             if (nbAudioSamples > 0)
             {
                 if (!m_settings.m_audioMute) {
                     m_audioFifo1.write((const quint8*) dsdAudio, nbAudioSamples);
                 }
                 m_dsdDecoder.resetAudio1();
             }
         }
         if (m_settings.m_slot2On)
         {
             int nbAudioSamples;
             short *dsdAudio = m_dsdDecoder.getAudio2(nbAudioSamples);
             if (nbAudioSamples > 0)
             {
                 if (!m_settings.m_audioMute) {
                     m_audioFifo2.write((const quint8*) dsdAudio, nbAudioSamples);
                 }
                 m_dsdDecoder.resetAudio2();
             }
         }
 //      int nbAudioSamples;
 //      short *dsdAudio = m_dsdDecoder.getAudio1(nbAudioSamples);
 //
 //      if (nbAudioSamples > 0)
 //      {
 //          if (!m_settings.m_audioMute) {
 //              uint res = m_audioFifo1.write((const quint8*) dsdAudio, nbAudioSamples, 10);
 //          }
 //
 //          m_dsdDecoder.resetAudio1();
 //      }
     }
     if ((m_scopeXY != 0) && (m_scopeEnabled))
     {
         m_scopeXY->feed(m_scopeSampleBuffer.begin(), m_scopeSampleBuffer.end(), true); // true = real samples for what it's worth
     }
     m_settingsMutex.unlock();
 }
formatStatusText()
void DSDDemod::formatStatusText () private
Definition at line 647 of file dsddemod.cpp.
References getDecoder(), DSDDecoder::getDStarDecoder(), m_formatStatusText, m_signalFormat, signalFormatDMR, signalFormatDPMR, signalFormatDStar, signalFormatNone, signalFormatNXDN, and signalFormatYSF.
Referenced by updateAndGetStatusText().
 {
     switch (getDecoder().getSyncType())
     {
     case DSDcc::DSDDecoder::DSDSyncDMRDataMS:
     case DSDcc::DSDDecoder::DSDSyncDMRDataP:
     case DSDcc::DSDDecoder::DSDSyncDMRVoiceMS:
     case DSDcc::DSDDecoder::DSDSyncDMRVoiceP:
         if (m_signalFormat != signalFormatDMR)
         {
             strcpy(m_formatStatusText, "Sta: __ S1: __________________________ S2: __________________________");
         }
         switch (getDecoder().getStationType())
         {
         case DSDcc::DSDDecoder::DSDBaseStation:
             memcpy(&m_formatStatusText[5], "BS ", 3);
             break;
         case DSDcc::DSDDecoder::DSDMobileStation:
             memcpy(&m_formatStatusText[5], "MS ", 3);
             break;
         default:
             memcpy(&m_formatStatusText[5], "NA ", 3);
             break;
         }
         memcpy(&m_formatStatusText[12], getDecoder().getDMRDecoder().getSlot0Text(), 26);
         memcpy(&m_formatStatusText[43], getDecoder().getDMRDecoder().getSlot1Text(), 26);
         m_signalFormat = signalFormatDMR;
         break;
     case DSDcc::DSDDecoder::DSDSyncDStarHeaderN:
     case DSDcc::DSDDecoder::DSDSyncDStarHeaderP:
     case DSDcc::DSDDecoder::DSDSyncDStarN:
     case DSDcc::DSDDecoder::DSDSyncDStarP:
         if (m_signalFormat != signalFormatDStar)
         {
                                      //           1    1    2    2    3    3    4    4    5    5    6    6    7    7    8
                                      // 0....5....0....5....0....5....0....5....0....5....0....5....0....5....0....5....0..
             strcpy(m_formatStatusText, "________/____>________|________>________|____________________|______:___/_____._");
                                      // MY            UR       RPT1     RPT2     Info                 Loc    Target
         }
         {
             const std::string& rpt1 = getDecoder().getDStarDecoder().getRpt1();
             const std::string& rpt2 = getDecoder().getDStarDecoder().getRpt2();
             const std::string& mySign = getDecoder().getDStarDecoder().getMySign();
             const std::string& yrSign = getDecoder().getDStarDecoder().getYourSign();
             if (rpt1.length() > 0) { // 0 or 8
                 memcpy(&m_formatStatusText[23], rpt1.c_str(), 8);
             }
             if (rpt2.length() > 0) { // 0 or 8
                 memcpy(&m_formatStatusText[32], rpt2.c_str(), 8);
             }
             if (yrSign.length() > 0) { // 0 or 8
                 memcpy(&m_formatStatusText[14], yrSign.c_str(), 8);
             }
             if (mySign.length() > 0) { // 0 or 13
                 memcpy(&m_formatStatusText[0], mySign.c_str(), 13);
             }
             memcpy(&m_formatStatusText[41], getDecoder().getDStarDecoder().getInfoText(), 20);
             memcpy(&m_formatStatusText[62], getDecoder().getDStarDecoder().getLocator(), 6);
             snprintf(&m_formatStatusText[69], 82-69, "%03d/%07.1f",
                     getDecoder().getDStarDecoder().getBearing(),
                     getDecoder().getDStarDecoder().getDistance());
         }
         m_formatStatusText[82] = '\0';
         m_signalFormat = signalFormatDStar;
         break;
     case DSDcc::DSDDecoder::DSDSyncDPMR:
         snprintf(m_formatStatusText, 82, "%s CC: %04d OI: %08d CI: %08d",
                 DSDcc::DSDdPMR::dpmrFrameTypes[(int) getDecoder().getDPMRDecoder().getFrameType()],
                 getDecoder().getDPMRDecoder().getColorCode(),
                 getDecoder().getDPMRDecoder().getOwnId(),
                 getDecoder().getDPMRDecoder().getCalledId());
         m_signalFormat = signalFormatDPMR;
         break;
     case DSDcc::DSDDecoder::DSDSyncNXDNP:
     case DSDcc::DSDDecoder::DSDSyncNXDNN:
         if (getDecoder().getNXDNDecoder().getRFChannel() == DSDcc::DSDNXDN::NXDNRCCH)
         {
             //           1    1    2    2    3    3    4    4    5    5    6    6    7    7    8
             // 0....5....0....5....0....5....0....5....0....5....0....5....0....5....0....5....0..
             // RC r cc mm llllll ssss
             snprintf(m_formatStatusText, 82, "RC %s %02d %02X %06X %02X",
                     getDecoder().getNXDNDecoder().isFullRate() ? "F" : "H",
                     getDecoder().getNXDNDecoder().getRAN(),
                     getDecoder().getNXDNDecoder().getMessageType(),
                     getDecoder().getNXDNDecoder().getLocationId(),
                     getDecoder().getNXDNDecoder().getServicesFlag());
         }
         else if ((getDecoder().getNXDNDecoder().getRFChannel() == DSDcc::DSDNXDN::NXDNRTCH)
             || (getDecoder().getNXDNDecoder().getRFChannel() == DSDcc::DSDNXDN::NXDNRDCH))
         {
             if (getDecoder().getNXDNDecoder().isIdle()) {
                 snprintf(m_formatStatusText, 82, "%s IDLE", getDecoder().getNXDNDecoder().getRFChannelStr());
             }
             else
             {
                 //           1    1    2    2    3    3    4    4    5    5    6    6    7    7    8
                 // 0....5....0....5....0....5....0....5....0....5....0....5....0....5....0....5....0..
                 // Rx r cc mm sssss>gddddd
                 snprintf(m_formatStatusText, 82, "%s %s %02d %02X %05d>%c%05d",
                         getDecoder().getNXDNDecoder().getRFChannelStr(),
                         getDecoder().getNXDNDecoder().isFullRate() ? "F" : "H",
                         getDecoder().getNXDNDecoder().getRAN(),
                         getDecoder().getNXDNDecoder().getMessageType(),
                         getDecoder().getNXDNDecoder().getSourceId(),
                         getDecoder().getNXDNDecoder().isGroupCall() ? 'G' : 'I',
                         getDecoder().getNXDNDecoder().getDestinationId());
             }
         }
         else
         {
             //           1    1    2    2    3    3    4    4    5    5    6    6    7    7    8
             // 0....5....0....5....0....5....0....5....0....5....0....5....0....5....0....5....0..
             // RU
             snprintf(m_formatStatusText, 82, "RU");
         }
         m_signalFormat = signalFormatNXDN;
         break;
     case DSDcc::DSDDecoder::DSDSyncYSF:
         //           1    1    2    2    3    3    4    4    5    5    6    6    7    7    8
         // 0....5....0....5....0....5....0....5....0....5....0....5....0....5....0....5....0..
         // C V2 RI 0:7 WL000|ssssssssss>dddddddddd |UUUUUUUUUU>DDDDDDDDDD|44444
         if (getDecoder().getYSFDecoder().getFICHError() == DSDcc::DSDYSF::FICHNoError)
         {
             snprintf(m_formatStatusText, 82, "%s ", DSDcc::DSDYSF::ysfChannelTypeText[(int) getDecoder().getYSFDecoder().getFICH().getFrameInformation()]);
         }
         else
         {
             snprintf(m_formatStatusText, 82, "%d ", (int) getDecoder().getYSFDecoder().getFICHError());
         }
         snprintf(&m_formatStatusText[2], 80, "%s %s %d:%d %c%c",
                 DSDcc::DSDYSF::ysfDataTypeText[(int) getDecoder().getYSFDecoder().getFICH().getDataType()],
                 DSDcc::DSDYSF::ysfCallModeText[(int) getDecoder().getYSFDecoder().getFICH().getCallMode()],
                 getDecoder().getYSFDecoder().getFICH().getBlockTotal(),
                 getDecoder().getYSFDecoder().getFICH().getFrameTotal(),
                 (getDecoder().getYSFDecoder().getFICH().isNarrowMode() ? 'N' : 'W'),
                 (getDecoder().getYSFDecoder().getFICH().isInternetPath() ? 'I' : 'L'));
         if (getDecoder().getYSFDecoder().getFICH().isSquelchCodeEnabled())
         {
             snprintf(&m_formatStatusText[14], 82-14, "%03d", getDecoder().getYSFDecoder().getFICH().getSquelchCode());
         }
         else
         {
             strncpy(&m_formatStatusText[14], "---", 82-14);
         }
         char dest[13];
         if (getDecoder().getYSFDecoder().radioIdMode())
         {
             snprintf(dest, 12, "%-5s:%-5s",
                     getDecoder().getYSFDecoder().getDestId(),
                     getDecoder().getYSFDecoder().getSrcId());
         }
         else
         {
             snprintf(dest, 11, "%-10s", getDecoder().getYSFDecoder().getDest());
         }
         snprintf(&m_formatStatusText[17], 82-17, "|%-10s>%s|%-10s>%-10s|%-5s",
                 getDecoder().getYSFDecoder().getSrc(),
                 dest,
                 getDecoder().getYSFDecoder().getUplink(),
                 getDecoder().getYSFDecoder().getDownlink(),
                 getDecoder().getYSFDecoder().getRem4());
         m_signalFormat = signalFormatYSF;
         break;
     default:
         m_signalFormat = signalFormatNone;
         m_formatStatusText[0] = '\0';
         break;
     }
     m_formatStatusText[82] = '\0'; // guard
 }
getCenterFrequency()
virtual qint64 DSDDemod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 113 of file dsddemod.h.
References deserialize(), DSDDemodSettings::m_inputFrequencyOffset, DSDDemod::MsgConfigureDSDDemod::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getDecoder()
const DSDDecoder& DSDDemod::getDecoder () const inline
Definition at line 131 of file dsddemod.h.
References m_dsdDecoder.
Referenced by formatStatusText(), DSDDemodGUI::tick(), and webapiFormatChannelReport().
 { return m_dsdDecoder; }
getIdentifier()
virtual void DSDDemod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 111 of file dsddemod.h.
 { id = objectName(); }
getMagSq()
double DSDDemod::getMagSq () inline
Definition at line 128 of file dsddemod.h.
References m_magsq.
 { return m_magsq; }
getMagSqLevels()
void DSDDemod::getMagSqLevels (double & avg, double & peak, int & nbSamples) inline
Definition at line 133 of file dsddemod.h.
References DSDDemod::MagSqLevelsStore::m_magsq, m_magsq, m_magsqCount, m_magSqLevelStore, DSDDemod::MagSqLevelsStore::m_magsqPeak, m_magsqPeak, m_magsqSum, updateAndGetStatusText(), webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
Referenced by DSDDemodGUI::tick(), and webapiFormatChannelReport().
     {
         if (m_magsqCount > 0)
         {
             m_magsq = m_magsqSum / m_magsqCount;
             m_magSqLevelStore.m_magsq = m_magsq;
             m_magSqLevelStore.m_magsqPeak = m_magsqPeak;
         }
         avg = m_magSqLevelStore.m_magsq;
         peak = m_magSqLevelStore.m_magsqPeak;
         nbSamples = m_magsqCount == 0 ? 1 : m_magsqCount;
         m_magsqSum = 0.0f;
         m_magsqPeak = 0.0f;
         m_magsqCount = 0;
     }
getNbSinkStreams()
virtual int DSDDemod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 118 of file dsddemod.h.
 { return 1; }
getNbSourceStreams()
virtual int DSDDemod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 119 of file dsddemod.h.
 { return 0; }
getSquelchOpen()
bool DSDDemod::getSquelchOpen () const inline
Definition at line 129 of file dsddemod.h.
References m_squelchOpen.
Referenced by DSDDemodGUI::tick().
 { return m_squelchOpen; }
getStreamCenterFrequency()
virtual qint64 DSDDemod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 121 of file dsddemod.h.
References DSDDemodSettings::m_inputFrequencyOffset, and DSDDemod::MsgConfigureDSDDemod::m_settings.
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void DSDDemod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 112 of file dsddemod.h.
References DSDDemod::MsgConfigureDSDDemod::m_settings, and DSDDemodSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool DSDDemod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 365 of file dsddemod.cpp.
References applyAudioSampleRate(), applyChannelSettings(), applySettings(), DownChannelizer::configure(), DSDDemod::MsgConfigureChannelizer::getCenterFrequency(), DSDDemod::MsgConfigureDSDDemod::getForce(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSink::getInputMessageQueue(), DSDDemod::MsgConfigureMyPosition::getMyLatitude(), DSDDemod::MsgConfigureMyPosition::getMyLongitude(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), DSDDemod::MsgConfigureChannelizer::getSampleRate(), DSPConfigureAudio::getSampleRate(), DSDDemod::MsgConfigureDSDDemod::getSettings(), m_audioSampleRate, m_channelizer, m_dsdDecoder, Message::match(), and DSDDecoder::setMyPoint().
Referenced by setScopeXYSink().
 {
     qDebug() << "DSDDemod::handleMessage";
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& notif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "DSDDemod::handleMessage: MsgChannelizerNotification: inputSampleRate: " << notif.getSampleRate()
                 << " inputFrequencyOffset: " << notif.getFrequencyOffset();
         applyChannelSettings(notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug("DSDDemod::handleMessage: MsgConfigureChannelizer");
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureDSDDemod::match(cmd))
     {
         MsgConfigureDSDDemod& cfg = (MsgConfigureDSDDemod&) cmd;
         qDebug("DSDDemod::handleMessage: MsgConfigureDSDDemod: m_rfBandwidth");
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgConfigureMyPosition::match(cmd))
     {
         MsgConfigureMyPosition& cfg = (MsgConfigureMyPosition&) cmd;
         m_dsdDecoder.setMyPoint(cfg.getMyLatitude(), cfg.getMyLongitude());
         return true;
     }
     else if (DSPConfigureAudio::match(cmd))
     {
         DSPConfigureAudio& cfg = (DSPConfigureAudio&) cmd;
         uint32_t sampleRate = cfg.getSampleRate();
         qDebug() << "DSDDemod::handleMessage: DSPConfigureAudio:"
                 << " sampleRate: " << sampleRate;
         if (sampleRate != m_audioSampleRate) {
             applyAudioSampleRate(sampleRate);
         }
         return true;
     }
     else if (BasebandSampleSink::MsgThreadedSink::match(cmd))
     {
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         return false;
     }
 }
networkManagerFinished
void DSDDemod::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 1136 of file dsddemod.cpp.
Referenced by DSDDemod(), and ~DSDDemod().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "DSDDemod::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("DSDDemod::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
serialize()
QByteArray DSDDemod::serialize () const virtual
Implements ChannelAPI.
Definition at line 619 of file dsddemod.cpp.
References m_settings, and DSDDemodSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
setScopeXYSink()
void DSDDemod::setScopeXYSink (BasebandSampleSink * sampleSink) inline
Definition at line 102 of file dsddemod.h.
References configureMyPosition(), feed(), handleMessage(), m_scopeXY, start(), and stop().
Referenced by DSDDemodGUI::DSDDemodGUI().
 { m_scopeXY = sampleSink; }
start()
void DSDDemod::start () virtual
Implements BasebandSampleSink.
Definition at line 353 of file dsddemod.cpp.
References applyChannelSettings(), AudioFifo::clear(), m_audioFifo1, m_audioFifo2, m_inputFrequencyOffset, m_inputSampleRate, m_phaseDiscri, and PhaseDiscriminators::reset().
Referenced by setScopeXYSink().
 {
     m_audioFifo1.clear();
     m_audioFifo2.clear();
     m_phaseDiscri.reset();
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void DSDDemod::stop () virtual
Implements BasebandSampleSink.
Definition at line 361 of file dsddemod.cpp.
Referenced by setScopeXYSink().
 {
 }
updateAndGetStatusText()
const char * DSDDemod::updateAndGetStatusText ()
Definition at line 641 of file dsddemod.cpp.
References formatStatusText(), and m_formatStatusText.
Referenced by getMagSqLevels(), DSDDemodGUI::tick(), and webapiFormatChannelReport().
 {
     formatStatusText();
     return m_formatStatusText;
 }
webapiFormatChannelReport()
void DSDDemod::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 1017 of file dsddemod.cpp.
References CalcDb::dbPower(), getDecoder(), SWGSDRangel::SWGChannelReport::getDsdDemodReport(), getMagSqLevels(), m_audioSampleRate, m_inputSampleRate, m_squelchOpen, SWGSDRangel::SWGDSDDemodReport::setAudioSampleRate(), SWGSDRangel::SWGDSDDemodReport::setCarierPosition(), SWGSDRangel::SWGDSDDemodReport::setChannelPowerDb(), SWGSDRangel::SWGDSDDemodReport::setChannelSampleRate(), SWGSDRangel::SWGDSDDemodReport::setInLevel(), SWGSDRangel::SWGDSDDemodReport::setPllLocked(), SWGSDRangel::SWGDSDDemodReport::setSlot1On(), SWGSDRangel::SWGDSDDemodReport::setSlot2On(), SWGSDRangel::SWGDSDDemodReport::setSquelch(), SWGSDRangel::SWGDSDDemodReport::setStatusText(), SWGSDRangel::SWGDSDDemodReport::setSyncRate(), SWGSDRangel::SWGDSDDemodReport::setSyncType(), SWGSDRangel::SWGDSDDemodReport::setZeroCrossingPosition(), and updateAndGetStatusText().
Referenced by webapiReportGet().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     response.getDsdDemodReport()->setChannelPowerDb(CalcDb::dbPower(magsqAvg));
     response.getDsdDemodReport()->setAudioSampleRate(m_audioSampleRate);
     response.getDsdDemodReport()->setChannelSampleRate(m_inputSampleRate);
     response.getDsdDemodReport()->setSquelch(m_squelchOpen ? 1 : 0);
     response.getDsdDemodReport()->setPllLocked(getDecoder().getSymbolPLLLocked() ? 1 : 0);
     response.getDsdDemodReport()->setSlot1On(getDecoder().getVoice1On() ? 1 : 0);
     response.getDsdDemodReport()->setSlot2On(getDecoder().getVoice2On() ? 1 : 0);
     response.getDsdDemodReport()->setSyncType(new QString(getDecoder().getFrameTypeText()));
     response.getDsdDemodReport()->setInLevel(getDecoder().getInLevel());
     response.getDsdDemodReport()->setCarierPosition(getDecoder().getCarrierPos());
     response.getDsdDemodReport()->setZeroCrossingPosition(getDecoder().getZeroCrossingPos());
     response.getDsdDemodReport()->setSyncRate(getDecoder().getSymbolSyncQuality());
     response.getDsdDemodReport()->setStatusText(new QString(updateAndGetStatusText()));
 }
webapiFormatChannelSettings()
void DSDDemod::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const DSDDemodSettings & settings) private
Definition at line 968 of file dsddemod.cpp.
References SWGSDRangel::SWGDSDDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGChannelSettings::getDsdDemodSettings(), SWGSDRangel::SWGDSDDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGDSDDemodSettings::getTitle(), DSDDemodSettings::m_audioDeviceName, DSDDemodSettings::m_audioMute, DSDDemodSettings::m_baudRate, DSDDemodSettings::m_demodGain, DSDDemodSettings::m_enableCosineFiltering, DSDDemodSettings::m_fmDeviation, DSDDemodSettings::m_highPassFilter, DSDDemodSettings::m_inputFrequencyOffset, DSDDemodSettings::m_pllLock, DSDDemodSettings::m_reverseAPIAddress, DSDDemodSettings::m_reverseAPIChannelIndex, DSDDemodSettings::m_reverseAPIDeviceIndex, DSDDemodSettings::m_reverseAPIPort, DSDDemodSettings::m_rfBandwidth, DSDDemodSettings::m_rgbColor, DSDDemodSettings::m_slot1On, DSDDemodSettings::m_slot2On, DSDDemodSettings::m_squelch, DSDDemodSettings::m_squelchGate, DSDDemodSettings::m_syncOrConstellation, DSDDemodSettings::m_tdmaStereo, DSDDemodSettings::m_title, DSDDemodSettings::m_traceDecay, DSDDemodSettings::m_traceLengthMutliplier, DSDDemodSettings::m_traceStroke, DSDDemodSettings::m_useReverseAPI, DSDDemodSettings::m_volume, SWGSDRangel::SWGDSDDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGDSDDemodSettings::setAudioMute(), SWGSDRangel::SWGDSDDemodSettings::setBaudRate(), SWGSDRangel::SWGDSDDemodSettings::setDemodGain(), SWGSDRangel::SWGDSDDemodSettings::setEnableCosineFiltering(), SWGSDRangel::SWGDSDDemodSettings::setFmDeviation(), SWGSDRangel::SWGDSDDemodSettings::setHighPassFilter(), SWGSDRangel::SWGDSDDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGDSDDemodSettings::setPllLock(), SWGSDRangel::SWGDSDDemodSettings::setReverseApiAddress(), SWGSDRangel::SWGDSDDemodSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGDSDDemodSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGDSDDemodSettings::setReverseApiPort(), SWGSDRangel::SWGDSDDemodSettings::setRfBandwidth(), SWGSDRangel::SWGDSDDemodSettings::setRgbColor(), SWGSDRangel::SWGDSDDemodSettings::setSlot1On(), SWGSDRangel::SWGDSDDemodSettings::setSlot2On(), SWGSDRangel::SWGDSDDemodSettings::setSquelch(), SWGSDRangel::SWGDSDDemodSettings::setSquelchGate(), SWGSDRangel::SWGDSDDemodSettings::setSyncOrConstellation(), SWGSDRangel::SWGDSDDemodSettings::setTdmaStereo(), SWGSDRangel::SWGDSDDemodSettings::setTitle(), SWGSDRangel::SWGDSDDemodSettings::setTraceDecay(), SWGSDRangel::SWGDSDDemodSettings::setTraceLengthMutliplier(), SWGSDRangel::SWGDSDDemodSettings::setTraceStroke(), SWGSDRangel::SWGDSDDemodSettings::setUseReverseApi(), and SWGSDRangel::SWGDSDDemodSettings::setVolume().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getDsdDemodSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getDsdDemodSettings()->setRfBandwidth(settings.m_rfBandwidth);
     response.getDsdDemodSettings()->setFmDeviation(settings.m_fmDeviation);
     response.getDsdDemodSettings()->setDemodGain(settings.m_demodGain);
     response.getDsdDemodSettings()->setVolume(settings.m_volume);
     response.getDsdDemodSettings()->setBaudRate(settings.m_baudRate);
     response.getDsdDemodSettings()->setSquelchGate(settings.m_squelchGate);
     response.getDsdDemodSettings()->setSquelch(settings.m_squelch);
     response.getDsdDemodSettings()->setAudioMute(settings.m_audioMute ? 1 : 0);
     response.getDsdDemodSettings()->setEnableCosineFiltering(settings.m_enableCosineFiltering ? 1 : 0);
     response.getDsdDemodSettings()->setSyncOrConstellation(settings.m_syncOrConstellation ? 1 : 0);
     response.getDsdDemodSettings()->setSlot1On(settings.m_slot1On ? 1 : 0);
     response.getDsdDemodSettings()->setSlot2On(settings.m_slot2On ? 1 : 0);
     response.getDsdDemodSettings()->setTdmaStereo(settings.m_tdmaStereo ? 1 : 0);
     response.getDsdDemodSettings()->setPllLock(settings.m_pllLock ? 1 : 0);
     response.getDsdDemodSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getDsdDemodSettings()->getTitle()) {
         *response.getDsdDemodSettings()->getTitle() = settings.m_title;
     } else {
         response.getDsdDemodSettings()->setTitle(new QString(settings.m_title));
     }
     if (response.getDsdDemodSettings()->getAudioDeviceName()) {
         *response.getDsdDemodSettings()->getAudioDeviceName() = settings.m_audioDeviceName;
     } else {
         response.getDsdDemodSettings()->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     response.getDsdDemodSettings()->setHighPassFilter(settings.m_highPassFilter ? 1 : 0);
     response.getDsdDemodSettings()->setTraceLengthMutliplier(settings.m_traceLengthMutliplier);
     response.getDsdDemodSettings()->setTraceStroke(settings.m_traceStroke);
     response.getDsdDemodSettings()->setTraceDecay(settings.m_traceDecay);
     response.getDsdDemodSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getDsdDemodSettings()->getReverseApiAddress()) {
         *response.getDsdDemodSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getDsdDemodSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getDsdDemodSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getDsdDemodSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getDsdDemodSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int DSDDemod::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 957 of file dsddemod.cpp.
References SWGSDRangel::SWGChannelReport::getDsdDemodReport(), SWGSDRangel::SWGDSDDemodReport::init(), SWGSDRangel::SWGChannelReport::setDsdDemodReport(), and webapiFormatChannelReport().
Referenced by getMagSqLevels().
 {
     (void) errorMessage;
     response.setDsdDemodReport(new SWGSDRangel::SWGDSDDemodReport());
     response.getDsdDemodReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendSettings()
void DSDDemod::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const DSDDemodSettings & settings, bool force) private
Definition at line 1038 of file dsddemod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), ChannelAPI::getDeviceSetIndex(), SWGSDRangel::SWGChannelSettings::getDsdDemodSettings(), ChannelAPI::getIndexInDeviceSet(), DSDDemodSettings::m_audioDeviceName, DSDDemodSettings::m_audioMute, DSDDemodSettings::m_baudRate, DSDDemodSettings::m_demodGain, DSDDemodSettings::m_enableCosineFiltering, DSDDemodSettings::m_fmDeviation, DSDDemodSettings::m_highPassFilter, DSDDemodSettings::m_inputFrequencyOffset, m_networkManager, m_networkRequest, DSDDemodSettings::m_pllLock, DSDDemodSettings::m_reverseAPIAddress, DSDDemodSettings::m_reverseAPIChannelIndex, DSDDemodSettings::m_reverseAPIDeviceIndex, DSDDemodSettings::m_reverseAPIPort, DSDDemodSettings::m_rfBandwidth, DSDDemodSettings::m_rgbColor, DSDDemodSettings::m_slot1On, DSDDemodSettings::m_slot2On, DSDDemodSettings::m_squelch, DSDDemodSettings::m_squelchGate, DSDDemodSettings::m_syncOrConstellation, DSDDemodSettings::m_tdmaStereo, DSDDemodSettings::m_title, DSDDemodSettings::m_traceDecay, DSDDemodSettings::m_traceLengthMutliplier, DSDDemodSettings::m_traceStroke, DSDDemodSettings::m_volume, SWGSDRangel::SWGDSDDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGDSDDemodSettings::setAudioMute(), SWGSDRangel::SWGDSDDemodSettings::setBaudRate(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGDSDDemodSettings::setDemodGain(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGChannelSettings::setDsdDemodSettings(), SWGSDRangel::SWGDSDDemodSettings::setEnableCosineFiltering(), SWGSDRangel::SWGDSDDemodSettings::setFmDeviation(), SWGSDRangel::SWGDSDDemodSettings::setHighPassFilter(), SWGSDRangel::SWGDSDDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGDSDDemodSettings::setPllLock(), SWGSDRangel::SWGDSDDemodSettings::setRfBandwidth(), SWGSDRangel::SWGDSDDemodSettings::setRgbColor(), SWGSDRangel::SWGDSDDemodSettings::setSlot1On(), SWGSDRangel::SWGDSDDemodSettings::setSlot2On(), SWGSDRangel::SWGDSDDemodSettings::setSquelch(), SWGSDRangel::SWGDSDDemodSettings::setSquelchGate(), SWGSDRangel::SWGDSDDemodSettings::setSyncOrConstellation(), SWGSDRangel::SWGDSDDemodSettings::setTdmaStereo(), SWGSDRangel::SWGDSDDemodSettings::setTitle(), SWGSDRangel::SWGDSDDemodSettings::setTraceDecay(), SWGSDRangel::SWGDSDDemodSettings::setTraceLengthMutliplier(), SWGSDRangel::SWGDSDDemodSettings::setTraceStroke(), and SWGSDRangel::SWGDSDDemodSettings::setVolume().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(0); // single sink (Rx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("DSDDemod"));
     swgChannelSettings->setDsdDemodSettings(new SWGSDRangel::SWGDSDDemodSettings());
     SWGSDRangel::SWGDSDDemodSettings *swgDSDDemodSettings = swgChannelSettings->getDsdDemodSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgDSDDemodSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("rfBandwidth") || force) {
         swgDSDDemodSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (channelSettingsKeys.contains("fmDeviation") || force) {
         swgDSDDemodSettings->setFmDeviation(settings.m_fmDeviation);
     }
     if (channelSettingsKeys.contains("demodGain") || force) {
         swgDSDDemodSettings->setDemodGain(settings.m_demodGain);
     }
     if (channelSettingsKeys.contains("volume") || force) {
         swgDSDDemodSettings->setVolume(settings.m_volume);
     }
     if (channelSettingsKeys.contains("baudRate") || force) {
         swgDSDDemodSettings->setBaudRate(settings.m_baudRate);
     }
     if (channelSettingsKeys.contains("squelchGate") || force) {
         swgDSDDemodSettings->setSquelchGate(settings.m_squelchGate);
     }
     if (channelSettingsKeys.contains("squelch") || force) {
         swgDSDDemodSettings->setSquelch(settings.m_squelch);
     }
     if (channelSettingsKeys.contains("audioMute") || force) {
         swgDSDDemodSettings->setAudioMute(settings.m_audioMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("enableCosineFiltering") || force) {
         swgDSDDemodSettings->setEnableCosineFiltering(settings.m_enableCosineFiltering ? 1 : 0);
     }
     if (channelSettingsKeys.contains("syncOrConstellation") || force) {
         swgDSDDemodSettings->setSyncOrConstellation(settings.m_syncOrConstellation ? 1 : 0);
     }
     if (channelSettingsKeys.contains("slot1On") || force) {
         swgDSDDemodSettings->setSlot1On(settings.m_slot1On ? 1 : 0);
     }
     if (channelSettingsKeys.contains("slot2On") || force) {
         swgDSDDemodSettings->setSlot2On(settings.m_slot2On ? 1 : 0);
     }
     if (channelSettingsKeys.contains("tdmaStereo") || force) {
         swgDSDDemodSettings->setTdmaStereo(settings.m_tdmaStereo ? 1 : 0);
     }
     if (channelSettingsKeys.contains("pllLock") || force) {
         swgDSDDemodSettings->setPllLock(settings.m_pllLock ? 1 : 0);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgDSDDemodSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgDSDDemodSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("audioDeviceName") || force) {
         swgDSDDemodSettings->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     if (channelSettingsKeys.contains("highPassFilter") || force) {
         swgDSDDemodSettings->setHighPassFilter(settings.m_highPassFilter ? 1 : 0);
     }
     if (channelSettingsKeys.contains("traceLengthMutliplier") || force) {
         swgDSDDemodSettings->setTraceLengthMutliplier(settings.m_traceLengthMutliplier);
     }
     if (channelSettingsKeys.contains("traceStroke") || force) {
         swgDSDDemodSettings->setTraceStroke(settings.m_traceStroke);
     }
     if (channelSettingsKeys.contains("traceDecay") || force) {
         swgDSDDemodSettings->setTraceDecay(settings.m_traceDecay);
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int DSDDemod::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 830 of file dsddemod.cpp.
References SWGSDRangel::SWGChannelSettings::getDsdDemodSettings(), SWGSDRangel::SWGDSDDemodSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setDsdDemodSettings(), and webapiFormatChannelSettings().
Referenced by getMagSqLevels().
 {
     (void) errorMessage;
     response.setDsdDemodSettings(new SWGSDRangel::SWGDSDDemodSettings());
     response.getDsdDemodSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int DSDDemod::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 841 of file dsddemod.cpp.
References DSDDemod::MsgConfigureDSDDemod::create(), DSDDemod::MsgConfigureChannelizer::create(), SWGSDRangel::SWGDSDDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGDSDDemodSettings::getAudioMute(), SWGSDRangel::SWGDSDDemodSettings::getBaudRate(), SWGSDRangel::SWGDSDDemodSettings::getDemodGain(), SWGSDRangel::SWGChannelSettings::getDsdDemodSettings(), SWGSDRangel::SWGDSDDemodSettings::getEnableCosineFiltering(), SWGSDRangel::SWGDSDDemodSettings::getFmDeviation(), SWGSDRangel::SWGDSDDemodSettings::getHighPassFilter(), SWGSDRangel::SWGDSDDemodSettings::getInputFrequencyOffset(), SWGSDRangel::SWGDSDDemodSettings::getPllLock(), SWGSDRangel::SWGDSDDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGDSDDemodSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGDSDDemodSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGDSDDemodSettings::getReverseApiPort(), SWGSDRangel::SWGDSDDemodSettings::getRfBandwidth(), SWGSDRangel::SWGDSDDemodSettings::getRgbColor(), SWGSDRangel::SWGDSDDemodSettings::getSlot1On(), SWGSDRangel::SWGDSDDemodSettings::getSlot2On(), SWGSDRangel::SWGDSDDemodSettings::getSquelch(), SWGSDRangel::SWGDSDDemodSettings::getSquelchGate(), SWGSDRangel::SWGDSDDemodSettings::getSyncOrConstellation(), SWGSDRangel::SWGDSDDemodSettings::getTdmaStereo(), SWGSDRangel::SWGDSDDemodSettings::getTitle(), SWGSDRangel::SWGDSDDemodSettings::getTraceDecay(), SWGSDRangel::SWGDSDDemodSettings::getTraceLengthMutliplier(), SWGSDRangel::SWGDSDDemodSettings::getTraceStroke(), SWGSDRangel::SWGDSDDemodSettings::getUseReverseApi(), SWGSDRangel::SWGDSDDemodSettings::getVolume(), DSDDemodSettings::m_audioDeviceName, DSDDemodSettings::m_audioMute, m_audioSampleRate, DSDDemodSettings::m_baudRate, DSDDemodSettings::m_demodGain, DSDDemodSettings::m_enableCosineFiltering, DSDDemodSettings::m_fmDeviation, BasebandSampleSink::m_guiMessageQueue, DSDDemodSettings::m_highPassFilter, DSDDemodSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, DSDDemodSettings::m_pllLock, DSDDemodSettings::m_reverseAPIAddress, DSDDemodSettings::m_reverseAPIChannelIndex, DSDDemodSettings::m_reverseAPIDeviceIndex, DSDDemodSettings::m_reverseAPIPort, DSDDemodSettings::m_rfBandwidth, DSDDemodSettings::m_rgbColor, m_settings, DSDDemodSettings::m_slot1On, DSDDemodSettings::m_slot2On, DSDDemodSettings::m_squelch, DSDDemodSettings::m_squelchGate, DSDDemodSettings::m_syncOrConstellation, DSDDemodSettings::m_tdmaStereo, DSDDemodSettings::m_title, DSDDemodSettings::m_traceDecay, DSDDemodSettings::m_traceLengthMutliplier, DSDDemodSettings::m_traceStroke, DSDDemodSettings::m_useReverseAPI, DSDDemodSettings::m_volume, MessageQueue::push(), and webapiFormatChannelSettings().
Referenced by getMagSqLevels().
 {
     (void) errorMessage;
     DSDDemodSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getDsdDemodSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getDsdDemodSettings()->getRfBandwidth();
     }
     if (channelSettingsKeys.contains("fmDeviation")) {
         settings.m_fmDeviation = response.getDsdDemodSettings()->getFmDeviation();
     }
     if (channelSettingsKeys.contains("demodGain")) {
         settings.m_demodGain = response.getDsdDemodSettings()->getDemodGain();
     }
     if (channelSettingsKeys.contains("volume")) {
         settings.m_volume = response.getDsdDemodSettings()->getVolume();
     }
     if (channelSettingsKeys.contains("baudRate")) {
         settings.m_baudRate = response.getDsdDemodSettings()->getBaudRate();
     }
     if (channelSettingsKeys.contains("squelchGate")) {
         settings.m_squelchGate = response.getDsdDemodSettings()->getSquelchGate();
     }
     if (channelSettingsKeys.contains("squelch")) {
         settings.m_squelch = response.getDsdDemodSettings()->getSquelch();
     }
     if (channelSettingsKeys.contains("audioMute")) {
         settings.m_audioMute = response.getDsdDemodSettings()->getAudioMute() != 0;
     }
     if (channelSettingsKeys.contains("enableCosineFiltering")) {
         settings.m_enableCosineFiltering = response.getDsdDemodSettings()->getEnableCosineFiltering() != 0;
     }
     if (channelSettingsKeys.contains("syncOrConstellation")) {
         settings.m_syncOrConstellation = response.getDsdDemodSettings()->getSyncOrConstellation() != 0;
     }
     if (channelSettingsKeys.contains("slot1On")) {
         settings.m_slot1On = response.getDsdDemodSettings()->getSlot1On() != 0;
     }
     if (channelSettingsKeys.contains("slot2On")) {
         settings.m_slot2On = response.getDsdDemodSettings()->getSlot2On() != 0;
     }
     if (channelSettingsKeys.contains("tdmaStereo")) {
         settings.m_tdmaStereo = response.getDsdDemodSettings()->getTdmaStereo() != 0;
     }
     if (channelSettingsKeys.contains("pllLock")) {
         settings.m_pllLock = response.getDsdDemodSettings()->getPllLock() != 0;
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getDsdDemodSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getDsdDemodSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("audioDeviceName")) {
         settings.m_audioDeviceName = *response.getDsdDemodSettings()->getAudioDeviceName();
     }
     if (channelSettingsKeys.contains("highPassFilter")) {
         settings.m_highPassFilter = response.getDsdDemodSettings()->getHighPassFilter() != 0;
     }
     if (channelSettingsKeys.contains("traceLengthMutliplier")) {
         settings.m_traceLengthMutliplier = response.getDsdDemodSettings()->getTraceLengthMutliplier();
     }
     if (channelSettingsKeys.contains("traceStroke")) {
         settings.m_traceStroke = response.getDsdDemodSettings()->getTraceStroke();
     }
     if (channelSettingsKeys.contains("traceDecay")) {
         settings.m_traceDecay = response.getDsdDemodSettings()->getTraceDecay();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getDsdDemodSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getDsdDemodSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getDsdDemodSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getDsdDemodSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getDsdDemodSettings()->getReverseApiChannelIndex();
     }
     if (frequencyOffsetChanged)
     {
         MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
                 m_audioSampleRate, settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(channelConfigMsg);
     }
     MsgConfigureDSDDemod *msg = MsgConfigureDSDDemod::create(settings, force);
     m_inputMessageQueue.push(msg);
     qDebug("DSDDemod::webapiSettingsPutPatch: forward to GUI: %p", m_guiMessageQueue);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureDSDDemod *msgToGUI = MsgConfigureDSDDemod::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_audioBuffer
AudioVector DSDDemod::m_audioBuffer private
Definition at line 246 of file dsddemod.h.
Referenced by DSDDemod().
m_audioBufferFill
uint DSDDemod::m_audioBufferFill private
Definition at line 247 of file dsddemod.h.
Referenced by DSDDemod().
m_audioFifo1
AudioFifo DSDDemod::m_audioFifo1 private
Definition at line 252 of file dsddemod.h.
Referenced by applySettings(), DSDDemod(), feed(), start(), and ~DSDDemod().
m_audioFifo2
AudioFifo DSDDemod::m_audioFifo2 private
Definition at line 253 of file dsddemod.h.
Referenced by applySettings(), DSDDemod(), feed(), start(), and ~DSDDemod().
m_audioSampleRate
quint32 DSDDemod::m_audioSampleRate private
Definition at line 225 of file dsddemod.h.
Referenced by applyAudioSampleRate(), applySettings(), DSDDemod(), feed(), handleMessage(), webapiFormatChannelReport(), and webapiSettingsPutPatch().
m_channelId
const QString DSDDemod::m_channelId = "DSDDemod" static
Definition at line 168 of file dsddemod.h.
Referenced by DSDDemod(), and DSDDemodPlugin::initPlugin().
m_channelIdURI
const QString DSDDemod::m_channelIdURI = "sdrangel.channel.dsddemod" static
Definition at line 167 of file dsddemod.h.
Referenced by DSDDemodGUI::DSDDemodGUI(), and DSDDemodPlugin::initPlugin().
m_channelizer
DownChannelizer* DSDDemod::m_channelizer private
Definition at line 220 of file dsddemod.h.
Referenced by DSDDemod(), handleMessage(), and ~DSDDemod().
m_deviceAPI
DeviceAPI* DSDDemod::m_deviceAPI private
Definition at line 218 of file dsddemod.h.
Referenced by DSDDemod(), and ~DSDDemod().
m_dsdDecoder
DSDDecoder DSDDemod::m_dsdDecoder private
Definition at line 257 of file dsddemod.h.
Referenced by applyAudioSampleRate(), applySettings(), feed(), getDecoder(), and handleMessage().
m_formatStatusText
char DSDDemod::m_formatStatusText[82+1] private
Fixed signal format dependent status text.
Definition at line 259 of file dsddemod.h.
Referenced by formatStatusText(), and updateAndGetStatusText().
m_inputFrequencyOffset
int DSDDemod::m_inputFrequencyOffset private
Definition at line 223 of file dsddemod.h.
Referenced by applyChannelSettings(), DSDDemod(), and start().
m_inputSampleRate
int DSDDemod::m_inputSampleRate private
Definition at line 222 of file dsddemod.h.
Referenced by applyChannelSettings(), applySettings(), DSDDemod(), start(), and webapiFormatChannelReport().
m_interpolator
Interpolator DSDDemod::m_interpolator private
Definition at line 228 of file dsddemod.h.
Referenced by applyChannelSettings(), applySettings(), and feed().
m_interpolatorDistance
Real DSDDemod::m_interpolatorDistance private
Definition at line 229 of file dsddemod.h.
Referenced by applyChannelSettings(), applySettings(), and feed().
m_interpolatorDistanceRemain
Real DSDDemod::m_interpolatorDistanceRemain private
Definition at line 230 of file dsddemod.h.
Referenced by applyChannelSettings(), applySettings(), and feed().
m_magsq
double DSDDemod::m_magsq private
Definition at line 239 of file dsddemod.h.
Referenced by DSDDemod(), getMagSq(), and getMagSqLevels().
m_magsqCount
int DSDDemod::m_magsqCount private
Definition at line 242 of file dsddemod.h.
Referenced by DSDDemod(), feed(), and getMagSqLevels().
m_magSqLevelStore
MagSqLevelsStore DSDDemod::m_magSqLevelStore private
Definition at line 243 of file dsddemod.h.
Referenced by getMagSqLevels().
m_magsqPeak
double DSDDemod::m_magsqPeak private
Definition at line 241 of file dsddemod.h.
Referenced by DSDDemod(), feed(), and getMagSqLevels().
m_magsqSum
double DSDDemod::m_magsqSum private
Definition at line 240 of file dsddemod.h.
Referenced by DSDDemod(), feed(), and getMagSqLevels().
m_movingAverage
MovingAverageUtil<Real, double, 16> DSDDemod::m_movingAverage private
Definition at line 238 of file dsddemod.h.
Referenced by feed().
m_nco
NCO DSDDemod::m_nco private
Definition at line 227 of file dsddemod.h.
Referenced by applyChannelSettings(), and feed().
m_networkManager
QNetworkAccessManager* DSDDemod::m_networkManager private
Definition at line 263 of file dsddemod.h.
Referenced by DSDDemod(), webapiReverseSendSettings(), and ~DSDDemod().
m_networkRequest
QNetworkRequest DSDDemod::m_networkRequest private
Definition at line 264 of file dsddemod.h.
Referenced by webapiReverseSendSettings().
m_phaseDiscri
PhaseDiscriminators DSDDemod::m_phaseDiscri private
Definition at line 261 of file dsddemod.h.
Referenced by applySettings(), feed(), and start().
m_sampleBuffer
FixReal* DSDDemod::m_sampleBuffer private
samples ring buffer
Definition at line 248 of file dsddemod.h.
Referenced by DSDDemod(), feed(), and ~DSDDemod().
m_sampleBufferIndex
int DSDDemod::m_sampleBufferIndex private
Definition at line 249 of file dsddemod.h.
Referenced by DSDDemod(), and feed().
m_sampleCount
int DSDDemod::m_sampleCount private
Definition at line 231 of file dsddemod.h.
Referenced by feed().
m_scaleFromShort
int DSDDemod::m_scaleFromShort private
Definition at line 250 of file dsddemod.h.
Referenced by DSDDemod(), and feed().
m_scopeEnabled
bool DSDDemod::m_scopeEnabled private
Definition at line 255 of file dsddemod.h.
Referenced by feed().
m_scopeSampleBuffer
SampleVector DSDDemod::m_scopeSampleBuffer private
Definition at line 245 of file dsddemod.h.
Referenced by feed().
m_scopeXY
BasebandSampleSink* DSDDemod::m_scopeXY private
Definition at line 254 of file dsddemod.h.
Referenced by feed(), and setScopeXYSink().
m_settings
DSDDemodSettings DSDDemod::m_settings private
Definition at line 224 of file dsddemod.h.
Referenced by applyChannelSettings(), applySettings(), deserialize(), DSDDemod(), feed(), serialize(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex DSDDemod::m_settingsMutex private
Definition at line 266 of file dsddemod.h.
Referenced by applyChannelSettings(), applySettings(), and feed().
m_signalFormat
SignalFormat DSDDemod::m_signalFormat private
Used to keep formatting during successive calls for the same standard type.
Definition at line 260 of file dsddemod.h.
Referenced by formatStatusText().
m_squelchCount
int DSDDemod::m_squelchCount private
Definition at line 232 of file dsddemod.h.
Referenced by applySettings(), and feed().
m_squelchDelayLine
DoubleBufferFIFO<Real> DSDDemod::m_squelchDelayLine private
Definition at line 236 of file dsddemod.h.
Referenced by feed().
m_squelchGate
int DSDDemod::m_squelchGate private
Definition at line 233 of file dsddemod.h.
Referenced by applySettings(), and feed().
m_squelchLevel
double DSDDemod::m_squelchLevel private
Definition at line 234 of file dsddemod.h.
Referenced by applySettings(), and feed().
m_squelchOpen
bool DSDDemod::m_squelchOpen private
Definition at line 235 of file dsddemod.h.
Referenced by feed(), getSquelchOpen(), and webapiFormatChannelReport().
m_threadedChannelizer
ThreadedBasebandSampleSink* DSDDemod::m_threadedChannelizer private
Definition at line 219 of file dsddemod.h.
Referenced by DSDDemod(), and ~DSDDemod().
m_udpBlockSize
const int DSDDemod::m_udpBlockSize = 512 static private
Definition at line 268 of file dsddemod.h.
The documentation for this class was generated from the following files:
plugins/channelrx/demoddsd/dsddemod.h
plugins/channelrx/demoddsd/dsddemod.cpp