SDRAngel: HackRFInputGui Class Reference
HackRFInputGui Class Reference
#include <hackrfinputgui.h>
Public Types
enum HackRFImgRejValue { HACKRF_IMGREJ_BYPASS = 0, HACKRF_IMGREJ_LOWPASS, HACKRF_IMGREJ_HIGHPASS, HACKRF_IMGREJ_NB }
Public Member Functions
HackRFInputGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~HackRFInputGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_centerFrequency_changed (quint64 value)
void on_sampleRate_changed (quint64 value)
void on_LOppm_valueChanged (int value)
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_biasT_stateChanged (int state)
void on_decim_currentIndexChanged (int index)
void on_fcPos_currentIndexChanged (int index)
void on_lnaExt_stateChanged (int state)
void on_lna_valueChanged (int value)
void on_bbFilter_currentIndexChanged (int index)
void on_vga_valueChanged (int value)
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void on_sampleRateMode_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void displaySettings ()
void displaySampleRate ()
void displayFcTooltip ()
void displayBandwidths ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void blockApplySettings (bool block)
Private Attributes
Ui::HackRFInputGui * ui
DeviceUISet * m_deviceUISet
HackRFInputSettings m_settings
bool m_sampleRateMode
true: device, false: base band sample rate update mode
bool m_forceSettings
bool m_doApplySettings
QTimer m_updateTimer
QTimer m_statusTimer
DeviceSampleSource * m_sampleSource
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 37 of file hackrfinputgui.h.
Member Enumeration Documentation
HackRFImgRejValue
enum HackRFInputGui::HackRFImgRejValue
Enumerator
HACKRF_IMGREJ_BYPASS
HACKRF_IMGREJ_LOWPASS
HACKRF_IMGREJ_HIGHPASS
HACKRF_IMGREJ_NB
Definition at line 41 of file hackrfinputgui.h.
     {
         HACKRF_IMGREJ_BYPASS = 0,
         HACKRF_IMGREJ_LOWPASS,
         HACKRF_IMGREJ_HIGHPASS,
         HACKRF_IMGREJ_NB
     } HackRFImgRejValue;
Constructor & Destructor Documentation
HackRFInputGui()
HackRFInputGui::HackRFInputGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 37 of file hackrfinputgui.cpp.
References displayBandwidths(), displaySettings(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_sampleSource, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), sendSettings(), DeviceSampleSource::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                                         :
     QWidget(parent),
     ui(new Ui::HackRFInputGui),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_sampleRateMode(true),
     m_forceSettings(true),
     m_doApplySettings(true),
     m_sampleSource(NULL),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     m_sampleSource = (HackRFInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, 0U, 7250000U);
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(8, 1000000U, 20000000U);
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     displayBandwidths();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
     sendSettings();
 }
~HackRFInputGui()
HackRFInputGui::~HackRFInputGui () virtual
Definition at line 73 of file hackrfinputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void HackRFInputGui::blockApplySettings (bool block) private
Definition at line 441 of file hackrfinputgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool HackRFInputGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 117 of file hackrfinputgui.cpp.
References HackRFInputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void HackRFInputGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 78 of file hackrfinputgui.cpp.
 {
     delete this;
 }
displayBandwidths()
void HackRFInputGui::displayBandwidths () private
Definition at line 273 of file hackrfinputgui.cpp.
References arg(), HackRFBandwidths::getBandwidthIndex(), i, HackRFInputSettings::m_bandwidth, HackRFBandwidths::m_bw_k, HackRFBandwidths::m_nb_bw, m_settings, and ui.
Referenced by HackRFInputGui().
 {
     unsigned int savedIndex = HackRFBandwidths::getBandwidthIndex(m_settings.m_bandwidth/1000);
     ui->bbFilter->blockSignals(true);
     ui->bbFilter->clear();
     for (unsigned int i = 0; i < HackRFBandwidths::m_nb_bw; i++)
     {
         ui->bbFilter->addItem(QString("%1M").arg(QString::number(HackRFBandwidths::m_bw_k[i]/1000.0, 'f', 2)));
     }
     ui->bbFilter->blockSignals(false);
     if (savedIndex < HackRFBandwidths::m_nb_bw)
     {
         ui->bbFilter->setCurrentIndex(savedIndex);
     }
     else
     {
         ui->bbFilter->setCurrentIndex((int) HackRFBandwidths::m_nb_bw-1);
     }
 }
displayFcTooltip()
void HackRFInputGui::displayFcTooltip () private
Definition at line 229 of file hackrfinputgui.cpp.
References arg(), DeviceSampleSource::calculateFrequencyShift(), HackRFInputSettings::m_devSampleRate, HackRFInputSettings::m_fcPos, HackRFInputSettings::m_log2Decim, m_settings, and ui.
Referenced by displaySampleRate(), on_fcPos_currentIndexChanged(), and on_sampleRate_changed().
 {
     int32_t fShift = DeviceSampleSource::calculateFrequencyShift(
         m_settings.m_log2Decim,
         (DeviceSampleSource::fcPos_t) m_settings.m_fcPos,
         m_settings.m_devSampleRate,
         DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD
     );
     ui->fcPos->setToolTip(tr("Relative position of device center frequency: %1 kHz").arg(QString::number(fShift / 1000.0f, 'g', 5)));
 }
displaySampleRate()
void HackRFInputGui::displaySampleRate () private
Definition at line 199 of file hackrfinputgui.cpp.
References arg(), displayFcTooltip(), HackRFInputSettings::m_devSampleRate, HackRFInputSettings::m_log2Decim, m_sampleRateMode, m_settings, and ui.
Referenced by displaySettings(), on_decim_currentIndexChanged(), on_sampleRateMode_toggled(), and updateSampleRateAndFrequency().
 {
     ui->sampleRate->blockSignals(true);
     displayFcTooltip();
     if (m_sampleRateMode)
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(60,60,60); }");
         ui->sampleRateMode->setText("SR");
         ui->sampleRate->setValueRange(8, 1000000U, 20000000U);
         ui->sampleRate->setValue(m_settings.m_devSampleRate);
         ui->sampleRate->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setToolTip("Baseband sample rate (S/s)");
         uint32_t basebandSampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Decim);
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(basebandSampleRate / 1000.0f, 'g', 5)));
     }
     else
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(50,50,50); }");
         ui->sampleRateMode->setText("BB");
         ui->sampleRate->setValueRange(8, 1000000U/(1<<m_settings.m_log2Decim), 20000000U/(1<<m_settings.m_log2Decim));
         ui->sampleRate->setValue(m_settings.m_devSampleRate/(1<<m_settings.m_log2Decim));
         ui->sampleRate->setToolTip("Baseband sample rate (S/s)");
         ui->deviceRateText->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_settings.m_devSampleRate / 1000.0f, 'g', 5)));
     }
     ui->sampleRate->blockSignals(false);
 }
displaySettings()
void HackRFInputGui::displaySettings () private
Definition at line 240 of file hackrfinputgui.cpp.
References arg(), blockApplySettings(), displaySampleRate(), HackRFBandwidths::getBandwidthIndex(), HackRFInputSettings::m_bandwidth, HackRFInputSettings::m_biasT, HackRFInputSettings::m_centerFrequency, HackRFInputSettings::m_dcBlock, HackRFInputSettings::m_fcPos, HackRFInputSettings::m_iqCorrection, HackRFInputSettings::m_lnaExt, HackRFInputSettings::m_lnaGain, HackRFInputSettings::m_log2Decim, HackRFInputSettings::m_LOppmTenths, m_settings, HackRFInputSettings::m_vgaGain, and ui.
Referenced by deserialize(), HackRFInputGui(), handleMessage(), resetToDefaults(), and setCenterFrequency().
 {
     blockApplySettings(true);
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     ui->LOppm->setValue(m_settings.m_LOppmTenths);
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqCorrection);
     displaySampleRate();
     ui->biasT->setChecked(m_settings.m_biasT);
     ui->decim->setCurrentIndex(m_settings.m_log2Decim);
     ui->fcPos->setCurrentIndex((int) m_settings.m_fcPos);
     ui->lnaExt->setChecked(m_settings.m_lnaExt);
     ui->lnaGainText->setText(tr("%1dB").arg(m_settings.m_lnaGain));
     ui->lna->setValue(m_settings.m_lnaGain);
     unsigned int bandwidthIndex = HackRFBandwidths::getBandwidthIndex(m_settings.m_bandwidth/1000);
     ui->bbFilter->setCurrentIndex(bandwidthIndex);
     ui->vgaText->setText(tr("%1dB").arg(m_settings.m_vgaGain));
     ui->vga->setValue(m_settings.m_vgaGain);
     blockApplySettings(false);
 }
getCenterFrequency()
qint64 HackRFInputGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 100 of file hackrfinputgui.cpp.
References HackRFInputSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* HackRFInputGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 61 of file hackrfinputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString HackRFInputGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 88 of file hackrfinputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void HackRFInputGui::handleInputMessages () private slot
Definition at line 164 of file hackrfinputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by HackRFInputGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("HackRFGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("HackRFGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool HackRFInputGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 133 of file hackrfinputgui.cpp.
References blockApplySettings(), displaySettings(), HackRFInput::MsgConfigureHackRF::getSettings(), HackRFInput::MsgStartStop::getStartStop(), m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (HackRFInput::MsgConfigureHackRF::match(message))
     {
         const HackRFInput::MsgConfigureHackRF& cfg = (HackRFInput::MsgConfigureHackRF&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (HackRFInput::MsgReportHackRF::match(message))
     {
         displaySettings();
         return true;
     }
     else if (HackRFInput::MsgStartStop::match(message))
     {
         HackRFInput::MsgStartStop& notif = (HackRFInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_bbFilter_currentIndexChanged
void HackRFInputGui::on_bbFilter_currentIndexChanged (int index) private slot
Definition at line 321 of file hackrfinputgui.cpp.
References HackRFBandwidths::getBandwidth(), HackRFInputSettings::m_bandwidth, m_settings, and sendSettings().
 {
     int newBandwidth = HackRFBandwidths::getBandwidth(index);
     m_settings.m_bandwidth = newBandwidth * 1000;
     sendSettings();
 }
on_biasT_stateChanged
void HackRFInputGui::on_biasT_stateChanged (int state) private slot
Definition at line 328 of file hackrfinputgui.cpp.
References HackRFInputSettings::m_biasT, m_settings, and sendSettings().
 {
     m_settings.m_biasT = (state == Qt::Checked);
     sendSettings();
 }
on_centerFrequency_changed
void HackRFInputGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 340 of file hackrfinputgui.cpp.
References HackRFInputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_dcOffset_toggled
void HackRFInputGui::on_dcOffset_toggled (bool checked) private slot
Definition at line 309 of file hackrfinputgui.cpp.
References HackRFInputSettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_decim_currentIndexChanged
void HackRFInputGui::on_decim_currentIndexChanged (int index) private slot
Definition at line 358 of file hackrfinputgui.cpp.
References displaySampleRate(), HackRFInputSettings::m_devSampleRate, HackRFInputSettings::m_log2Decim, m_sampleRateMode, m_settings, sendSettings(), and ui.
 {
     if ((index <0) || (index > 6)) {
         return;
     }
     m_settings.m_log2Decim = index;
     displaySampleRate();
     m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     if (!m_sampleRateMode) {
         m_settings.m_devSampleRate <<= m_settings.m_log2Decim;
     }
     sendSettings();
 }
on_fcPos_currentIndexChanged
void HackRFInputGui::on_fcPos_currentIndexChanged (int index) private slot
Definition at line 375 of file hackrfinputgui.cpp.
References displayFcTooltip(), HackRFInputSettings::m_fcPos, m_settings, and sendSettings().
 {
     m_settings.m_fcPos = (HackRFInputSettings::fcPos_t) (index < 0 ? 0 : index > 2 ? 2 : index);
     displayFcTooltip();
     sendSettings();
 }
on_iqImbalance_toggled
void HackRFInputGui::on_iqImbalance_toggled (bool checked) private slot
Definition at line 315 of file hackrfinputgui.cpp.
References HackRFInputSettings::m_iqCorrection, m_settings, and sendSettings().
 {
     m_settings.m_iqCorrection = checked;
     sendSettings();
 }
on_lna_valueChanged
void HackRFInputGui::on_lna_valueChanged (int value) private slot
Definition at line 382 of file hackrfinputgui.cpp.
References arg(), HackRFInputSettings::m_lnaGain, m_settings, sendSettings(), and ui.
 {
     if ((value < 0) || (value > 40))
         return;
     ui->lnaGainText->setText(tr("%1dB").arg(value));
     m_settings.m_lnaGain = value;
     sendSettings();
 }
on_lnaExt_stateChanged
void HackRFInputGui::on_lnaExt_stateChanged (int state) private slot
Definition at line 334 of file hackrfinputgui.cpp.
References HackRFInputSettings::m_lnaExt, m_settings, and sendSettings().
 {
     m_settings.m_lnaExt = (state == Qt::Checked);
     sendSettings();
 }
on_LOppm_valueChanged
void HackRFInputGui::on_LOppm_valueChanged (int value) private slot
Definition at line 302 of file hackrfinputgui.cpp.
References arg(), HackRFInputSettings::m_LOppmTenths, m_settings, sendSettings(), and ui.
 {
     m_settings.m_LOppmTenths = value;
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     sendSettings();
 }
on_record_toggled
void HackRFInputGui::on_record_toggled (bool checked) private slot
Definition at line 411 of file hackrfinputgui.cpp.
References HackRFInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     HackRFInput::MsgFileRecord* message = HackRFInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_sampleRate_changed
void HackRFInputGui::on_sampleRate_changed (quint64 value) private slot
Definition at line 346 of file hackrfinputgui.cpp.
References displayFcTooltip(), HackRFInputSettings::m_devSampleRate, HackRFInputSettings::m_log2Decim, m_sampleRateMode, m_settings, and sendSettings().
 {
     m_settings.m_devSampleRate = value;
     if (!m_sampleRateMode) {
         m_settings.m_devSampleRate <<= m_settings.m_log2Decim;
     }
     displayFcTooltip();
     sendSettings();
 }
on_sampleRateMode_toggled
void HackRFInputGui::on_sampleRateMode_toggled (bool checked) private slot
Definition at line 423 of file hackrfinputgui.cpp.
References displaySampleRate(), and m_sampleRateMode.
 {
     m_sampleRateMode = checked;
     displaySampleRate();
 }
on_startStop_toggled
void HackRFInputGui::on_startStop_toggled (bool checked) private slot
Definition at line 402 of file hackrfinputgui.cpp.
References HackRFInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         HackRFInput::MsgStartStop *message = HackRFInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
on_vga_valueChanged
void HackRFInputGui::on_vga_valueChanged (int value) private slot
Definition at line 392 of file hackrfinputgui.cpp.
References arg(), m_settings, HackRFInputSettings::m_vgaGain, sendSettings(), and ui.
 {
     if ((value < 0) || (value > 62))
         return;
     ui->vgaText->setText(tr("%1dB").arg(value));
     m_settings.m_vgaGain = value;
     sendSettings();
 }
openDeviceSettingsDialog
void HackRFInputGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 476 of file hackrfinputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), HackRFInputSettings::m_reverseAPIAddress, HackRFInputSettings::m_reverseAPIDeviceIndex, HackRFInputSettings::m_reverseAPIPort, m_settings, HackRFInputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by HackRFInputGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void HackRFInputGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 93 of file hackrfinputgui.cpp.
References displaySettings(), m_settings, HackRFInputSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void HackRFInputGui::sendSettings () private
Definition at line 296 of file hackrfinputgui.cpp.
References m_updateTimer.
Referenced by deserialize(), HackRFInputGui(), on_bbFilter_currentIndexChanged(), on_biasT_stateChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_iqImbalance_toggled(), on_lna_valueChanged(), on_lnaExt_stateChanged(), on_LOppm_valueChanged(), on_sampleRate_changed(), on_vga_valueChanged(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray HackRFInputGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 112 of file hackrfinputgui.cpp.
References m_settings, and HackRFInputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void HackRFInputGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 105 of file hackrfinputgui.cpp.
References displaySettings(), HackRFInputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void HackRFInputGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 83 of file hackrfinputgui.cpp.
 {
     setObjectName(name);
 }
updateHardware
void HackRFInputGui::updateHardware () private slot
Definition at line 429 of file hackrfinputgui.cpp.
References HackRFInput::MsgConfigureHackRF::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by HackRFInputGui().
 {
     if (m_doApplySettings)
     {
         qDebug() << "HackRFGui::updateHardware";
         HackRFInput::MsgConfigureHackRF* message = HackRFInput::MsgConfigureHackRF::create(m_settings, m_forceSettings);
         m_sampleSource->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void HackRFInputGui::updateSampleRateAndFrequency () private
Definition at line 192 of file hackrfinputgui.cpp.
References displaySampleRate(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), and GLSpectrum::setSampleRate().
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     displaySampleRate();
 }
updateStatus
void HackRFInputGui::updateStatus () private slot
Definition at line 446 of file hackrfinputgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by HackRFInputGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 ui->startStop->setChecked(false);
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 HackRFInputGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 76 of file hackrfinputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* HackRFInputGui::m_deviceUISet private
Definition at line 67 of file hackrfinputgui.h.
Referenced by HackRFInputGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool HackRFInputGui::m_doApplySettings private
Definition at line 71 of file hackrfinputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_forceSettings
bool HackRFInputGui::m_forceSettings private
Definition at line 70 of file hackrfinputgui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue HackRFInputGui::m_inputMessageQueue private
Definition at line 78 of file hackrfinputgui.h.
Referenced by HackRFInputGui(), and handleInputMessages().
m_lastEngineState
int HackRFInputGui::m_lastEngineState private
Definition at line 77 of file hackrfinputgui.h.
Referenced by updateStatus().
m_sampleRate
int HackRFInputGui::m_sampleRate private
Definition at line 75 of file hackrfinputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateMode
bool HackRFInputGui::m_sampleRateMode private
true: device, false: base band sample rate update mode
Definition at line 69 of file hackrfinputgui.h.
Referenced by displaySampleRate(), on_decim_currentIndexChanged(), on_sampleRate_changed(), and on_sampleRateMode_toggled().
m_sampleSource
DeviceSampleSource* HackRFInputGui::m_sampleSource private
Definition at line 74 of file hackrfinputgui.h.
Referenced by HackRFInputGui(), on_record_toggled(), on_startStop_toggled(), and updateHardware().
m_settings
HackRFInputSettings HackRFInputGui::m_settings private
Definition at line 68 of file hackrfinputgui.h.
Referenced by deserialize(), displayBandwidths(), displayFcTooltip(), displaySampleRate(), displaySettings(), getCenterFrequency(), handleMessage(), on_bbFilter_currentIndexChanged(), on_biasT_stateChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_iqImbalance_toggled(), on_lna_valueChanged(), on_lnaExt_stateChanged(), on_LOppm_valueChanged(), on_sampleRate_changed(), on_vga_valueChanged(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), and updateHardware().
m_statusTimer
QTimer HackRFInputGui::m_statusTimer private
Definition at line 73 of file hackrfinputgui.h.
Referenced by HackRFInputGui().
m_updateTimer
QTimer HackRFInputGui::m_updateTimer private
Definition at line 72 of file hackrfinputgui.h.
Referenced by HackRFInputGui(), sendSettings(), and updateHardware().
ui
Ui::HackRFInputGui* HackRFInputGui::ui private
Definition at line 65 of file hackrfinputgui.h.
Referenced by displayBandwidths(), displayFcTooltip(), displaySampleRate(), displaySettings(), HackRFInputGui(), handleMessage(), on_decim_currentIndexChanged(), on_lna_valueChanged(), on_LOppm_valueChanged(), on_record_toggled(), on_vga_valueChanged(), updateStatus(), and ~HackRFInputGui().
The documentation for this class was generated from the following files:
plugins/samplesource/hackrfinput/hackrfinputgui.h
plugins/samplesource/hackrfinput/hackrfinputgui.cpp