SDRAngel: RTLSDRThread Class Reference
RTLSDRThread Class Reference
#include <rtlsdrthread.h>
Inherits QThread.
Public Member Functions
RTLSDRThread (rtlsdr_dev_t *dev, SampleSinkFifo *sampleFifo, QObject *parent=NULL)
~RTLSDRThread ()
void startWork ()
void stopWork ()
void setSamplerate (int samplerate)
void setLog2Decimation (unsigned int log2_decim)
void setFcPos (int fcPos)
Private Member Functions
void run ()
void callback (const quint8 *buf, qint32 len)
Static Private Member Functions
static void callbackHelper (unsigned char *buf, uint32_t len, void *ctx)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
rtlsdr_dev_t * m_dev
SampleVector m_convertBuffer
SampleSinkFifo * m_sampleFifo
int m_samplerate
unsigned int m_log2Decim
int m_fcPos
DecimatorsU< qint32, quint8, SDR_RX_SAMP_SZ, 8, 127 > m_decimators
Detailed Description
Definition at line 30 of file rtlsdrthread.h.
Constructor & Destructor Documentation
RTLSDRThread()
RTLSDRThread::RTLSDRThread (rtlsdr_dev_t * dev, SampleSinkFifo * sampleFifo, QObject * parent = NULL)
Definition at line 27 of file rtlsdrthread.cpp.
                                                                                          :
     QThread(parent),
     m_running(false),
     m_dev(dev),
     m_convertBuffer(FCD_BLOCKSIZE),
     m_sampleFifo(sampleFifo),
     m_samplerate(288000),
     m_log2Decim(4),
     m_fcPos(0)
 {
 }
~RTLSDRThread()
RTLSDRThread::~RTLSDRThread ()
Definition at line 39 of file rtlsdrthread.cpp.
References stopWork().
 {
     stopWork();
 }
Member Function Documentation
callback()
void RTLSDRThread::callback (const quint8 * buf, qint32 len) private
Definition at line 92 of file rtlsdrthread.cpp.
References DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate1(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate16_cen(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate16_inf(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate16_sup(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate2_cen(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate2_inf(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate2_sup(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate32_cen(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate32_inf(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate32_sup(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate4_cen(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate4_inf(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate4_sup(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate64_cen(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate64_inf(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate64_sup(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate8_cen(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate8_inf(), DecimatorsU< StorageType, T, SdrBits, InputBits, Shift >::decimate8_sup(), m_convertBuffer, m_decimators, m_dev, m_fcPos, m_log2Decim, m_running, m_sampleFifo, and SampleSinkFifo::write().
Referenced by callbackHelper().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     if (m_log2Decim == 0)
     {
         m_decimators.decimate1(&it, buf, len);
     }
     else
     {
         if (m_fcPos == 0) // Infradyne
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_inf(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_inf(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_inf(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_inf(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_inf(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_inf(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 1) // Supradyne
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_sup(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_sup(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_sup(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_sup(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_sup(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_sup(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else // Centered
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_cen(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_cen(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_cen(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_cen(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_cen(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_cen(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
     }
     m_sampleFifo->write(m_convertBuffer.begin(), it);
     if(!m_running)
         rtlsdr_cancel_async(m_dev);
 }
callbackHelper()
void RTLSDRThread::callbackHelper (unsigned char * buf, uint32_t len, void * ctx) static private
Definition at line 188 of file rtlsdrthread.cpp.
References callback().
Referenced by run().
 {
     RTLSDRThread* thread = (RTLSDRThread*)ctx;
     thread->callback(buf, len);
 }
run()
void RTLSDRThread::run () private
Definition at line 74 of file rtlsdrthread.cpp.
References callbackHelper(), FCD_BLOCKSIZE, m_dev, m_running, and m_startWaiter.
 {
     int res;
     m_running = true;
     m_startWaiter.wakeAll();
     while(m_running) {
         if((res = rtlsdr_read_async(m_dev, &RTLSDRThread::callbackHelper, this, 32, FCD_BLOCKSIZE)) < 0) {
             qCritical("RTLSDRThread: async error: %s", strerror(errno));
             break;
         }
     }
     m_running = false;
 }
setFcPos()
void RTLSDRThread::setFcPos (int fcPos)
Definition at line 69 of file rtlsdrthread.cpp.
References m_fcPos.
Referenced by RTLSDRInput::applySettings(), and RTLSDRInput::start().
 {
     m_fcPos = fcPos;
 }
setLog2Decimation()
void RTLSDRThread::setLog2Decimation (unsigned int log2_decim)
Definition at line 64 of file rtlsdrthread.cpp.
References m_log2Decim.
Referenced by RTLSDRInput::applySettings(), and RTLSDRInput::start().
 {
     m_log2Decim = log2_decim;
 }
setSamplerate()
void RTLSDRThread::setSamplerate (int samplerate)
Definition at line 59 of file rtlsdrthread.cpp.
References m_samplerate.
Referenced by RTLSDRInput::applySettings(), and RTLSDRInput::start().
 {
     m_samplerate = samplerate;
 }
startWork()
void RTLSDRThread::startWork ()
Definition at line 44 of file rtlsdrthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by RTLSDRInput::start().
 {
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void RTLSDRThread::stopWork ()
Definition at line 53 of file rtlsdrthread.cpp.
References m_running.
Referenced by RTLSDRInput::stop(), and ~RTLSDRThread().
 {
     m_running = false;
     wait();
 }
Member Data Documentation
m_convertBuffer
SampleVector RTLSDRThread::m_convertBuffer private
Definition at line 49 of file rtlsdrthread.h.
Referenced by callback().
m_decimators
DecimatorsU<qint32, quint8, SDR_RX_SAMP_SZ, 8, 127> RTLSDRThread::m_decimators private
Definition at line 56 of file rtlsdrthread.h.
Referenced by callback().
m_dev
rtlsdr_dev_t* RTLSDRThread::m_dev private
Definition at line 48 of file rtlsdrthread.h.
Referenced by callback(), and run().
m_fcPos
int RTLSDRThread::m_fcPos private
Definition at line 54 of file rtlsdrthread.h.
Referenced by callback(), and setFcPos().
m_log2Decim
unsigned int RTLSDRThread::m_log2Decim private
Definition at line 53 of file rtlsdrthread.h.
Referenced by callback(), and setLog2Decimation().
m_running
bool RTLSDRThread::m_running private
Definition at line 46 of file rtlsdrthread.h.
Referenced by callback(), run(), startWork(), and stopWork().
m_sampleFifo
SampleSinkFifo* RTLSDRThread::m_sampleFifo private
Definition at line 50 of file rtlsdrthread.h.
Referenced by callback().
m_samplerate
int RTLSDRThread::m_samplerate private
Definition at line 52 of file rtlsdrthread.h.
Referenced by setSamplerate().
m_startWaiter
QWaitCondition RTLSDRThread::m_startWaiter private
Definition at line 45 of file rtlsdrthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex RTLSDRThread::m_startWaitMutex private
Definition at line 44 of file rtlsdrthread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/samplesource/rtlsdr/rtlsdrthread.h
plugins/samplesource/rtlsdr/rtlsdrthread.cpp