SDRAngel: SWGSDRangel::SWGSDRPlayReport Class Reference
SWGSDRangel::SWGSDRPlayReport Class Reference
#include <SWGSDRPlayReport.h>
Public Member Functions
SWGSDRPlayReport ()
SWGSDRPlayReport (QString *json)
virtual ~SWGSDRPlayReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGSDRPlayReport * fromJson (QString &jsonString) override
QList< SWGSampleRate * > * getSampleRates ()
void setSampleRates (QList< SWGSampleRate *> *sample_rates)
QList< SWGBandwidth * > * getBandwidths ()
void setBandwidths (QList< SWGBandwidth *> *bandwidths)
QList< SWGFrequency * > * getIntermediateFrequencies ()
void setIntermediateFrequencies (QList< SWGFrequency *> *intermediate_frequencies)
QList< SWGFrequencyBand * > * getFrequencyBands ()
void setFrequencyBands (QList< SWGFrequencyBand *> *frequency_bands)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QList< SWGSampleRate * > * sample_rates
bool m_sample_rates_isSet
QList< SWGBandwidth * > * bandwidths
bool m_bandwidths_isSet
QList< SWGFrequency * > * intermediate_frequencies
bool m_intermediate_frequencies_isSet
QList< SWGFrequencyBand * > * frequency_bands
bool m_frequency_bands_isSet
Detailed Description
Definition at line 36 of file SWGSDRPlayReport.h.
Constructor & Destructor Documentation
SWGSDRPlayReport() [1/2]
SWGSDRangel::SWGSDRPlayReport::SWGSDRPlayReport ()
Definition at line 30 of file SWGSDRPlayReport.cpp.
References bandwidths, frequency_bands, intermediate_frequencies, m_bandwidths_isSet, m_frequency_bands_isSet, m_intermediate_frequencies_isSet, m_sample_rates_isSet, and sample_rates.
{
     sample_rates = nullptr;
     m_sample_rates_isSet = false;
     bandwidths = nullptr;
     m_bandwidths_isSet = false;
     intermediate_frequencies = nullptr;
     m_intermediate_frequencies_isSet = false;
     frequency_bands = nullptr;
     m_frequency_bands_isSet = false;
 }
SWGSDRPlayReport() [2/2]
SWGSDRangel::SWGSDRPlayReport::SWGSDRPlayReport (QString * json)
Definition at line 25 of file SWGSDRPlayReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGSDRPlayReport()
SWGSDRangel::SWGSDRPlayReport::~SWGSDRPlayReport () virtual
Definition at line 41 of file SWGSDRPlayReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGSDRPlayReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 111 of file SWGSDRPlayReport.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGSDRPlayReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 122 of file SWGSDRPlayReport.cpp.
References bandwidths, frequency_bands, intermediate_frequencies, sample_rates, and SWGSDRangel::toJsonArray().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(sample_rates->size() > 0){
         toJsonArray((QList<void*>*)sample_rates, obj, "sampleRates", "SWGSampleRate");
     }
     if(bandwidths->size() > 0){
         toJsonArray((QList<void*>*)bandwidths, obj, "bandwidths", "SWGBandwidth");
     }
     if(intermediate_frequencies->size() > 0){
         toJsonArray((QList<void*>*)intermediate_frequencies, obj, "intermediateFrequencies", "SWGFrequency");
     }
     if(frequency_bands->size() > 0){
         toJsonArray((QList<void*>*)frequency_bands, obj, "frequencyBands", "SWGFrequencyBand");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGSDRPlayReport::cleanup ()
Definition at line 58 of file SWGSDRPlayReport.cpp.
References bandwidths, frequency_bands, intermediate_frequencies, and sample_rates.
Referenced by ~SWGSDRPlayReport().
{
     if(sample_rates != nullptr) {
         auto arr = sample_rates;
         for(auto o: *arr) {
             delete o;
         }
         delete sample_rates;
     }
     if(bandwidths != nullptr) {
         auto arr = bandwidths;
         for(auto o: *arr) {
             delete o;
         }
         delete bandwidths;
     }
     if(intermediate_frequencies != nullptr) {
         auto arr = intermediate_frequencies;
         for(auto o: *arr) {
             delete o;
         }
         delete intermediate_frequencies;
     }
     if(frequency_bands != nullptr) {
         auto arr = frequency_bands;
         for(auto o: *arr) {
             delete o;
         }
         delete frequency_bands;
     }
 }
fromJson()
SWGSDRPlayReport * SWGSDRangel::SWGSDRPlayReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 90 of file SWGSDRPlayReport.cpp.
References fromJsonObject().
Referenced by SWGSDRPlayReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGSDRPlayReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 99 of file SWGSDRPlayReport.cpp.
References bandwidths, frequency_bands, intermediate_frequencies, sample_rates, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&sample_rates, pJson["sampleRates"], "QList", "SWGSampleRate");
     ::SWGSDRangel::setValue(&bandwidths, pJson["bandwidths"], "QList", "SWGBandwidth");
     ::SWGSDRangel::setValue(&intermediate_frequencies, pJson["intermediateFrequencies"], "QList", "SWGFrequency");
     ::SWGSDRangel::setValue(&frequency_bands, pJson["frequencyBands"], "QList", "SWGFrequencyBand");
 }
getBandwidths()
QList< SWGBandwidth * > * SWGSDRangel::SWGSDRPlayReport::getBandwidths ()
Definition at line 151 of file SWGSDRPlayReport.cpp.
References bandwidths.
Referenced by SDRPlayInput::webapiFormatDeviceReport().
{
     return bandwidths;
 }
getFrequencyBands()
QList< SWGFrequencyBand * > * SWGSDRangel::SWGSDRPlayReport::getFrequencyBands ()
Definition at line 171 of file SWGSDRPlayReport.cpp.
References frequency_bands.
Referenced by SDRPlayInput::webapiFormatDeviceReport().
{
     return frequency_bands;
 }
getIntermediateFrequencies()
QList< SWGFrequency * > * SWGSDRangel::SWGSDRPlayReport::getIntermediateFrequencies ()
Definition at line 161 of file SWGSDRPlayReport.cpp.
References intermediate_frequencies.
Referenced by SDRPlayInput::webapiFormatDeviceReport().
{
     return intermediate_frequencies;
 }
getSampleRates()
QList< SWGSampleRate * > * SWGSDRangel::SWGSDRPlayReport::getSampleRates ()
Definition at line 141 of file SWGSDRPlayReport.cpp.
References sample_rates.
Referenced by SDRPlayInput::webapiFormatDeviceReport().
{
     return sample_rates;
 }
init()
void SWGSDRangel::SWGSDRPlayReport::init ()
Definition at line 46 of file SWGSDRPlayReport.cpp.
References bandwidths, frequency_bands, intermediate_frequencies, m_bandwidths_isSet, m_frequency_bands_isSet, m_intermediate_frequencies_isSet, m_sample_rates_isSet, and sample_rates.
Referenced by SWGSDRPlayReport(), and SDRPlayInput::webapiReportGet().
{
     sample_rates = new QList<SWGSampleRate*>();
     m_sample_rates_isSet = false;
     bandwidths = new QList<SWGBandwidth*>();
     m_bandwidths_isSet = false;
     intermediate_frequencies = new QList<SWGFrequency*>();
     m_intermediate_frequencies_isSet = false;
     frequency_bands = new QList<SWGFrequencyBand*>();
     m_frequency_bands_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGSDRPlayReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 182 of file SWGSDRPlayReport.cpp.
References bandwidths, frequency_bands, intermediate_frequencies, and sample_rates.
Referenced by SWGSDRangel::SWGDeviceReport::asJsonObject(), and SWGSDRangel::SWGDeviceReport::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(sample_rates->size() > 0){ isObjectUpdated = true; break;}
         if(bandwidths->size() > 0){ isObjectUpdated = true; break;}
         if(intermediate_frequencies->size() > 0){ isObjectUpdated = true; break;}
         if(frequency_bands->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setBandwidths()
void SWGSDRangel::SWGSDRPlayReport::setBandwidths (QList< SWGBandwidth *> * bandwidths)
Definition at line 155 of file SWGSDRPlayReport.cpp.
References bandwidths, and m_bandwidths_isSet.
Referenced by SDRPlayInput::webapiFormatDeviceReport().
{
     this->bandwidths = bandwidths;
     this->m_bandwidths_isSet = true;
 }
setFrequencyBands()
void SWGSDRangel::SWGSDRPlayReport::setFrequencyBands (QList< SWGFrequencyBand *> * frequency_bands)
Definition at line 175 of file SWGSDRPlayReport.cpp.
References frequency_bands, and m_frequency_bands_isSet.
Referenced by SDRPlayInput::webapiFormatDeviceReport().
{
     this->frequency_bands = frequency_bands;
     this->m_frequency_bands_isSet = true;
 }
setIntermediateFrequencies()
void SWGSDRangel::SWGSDRPlayReport::setIntermediateFrequencies (QList< SWGFrequency *> * intermediate_frequencies)
Definition at line 165 of file SWGSDRPlayReport.cpp.
References intermediate_frequencies, and m_intermediate_frequencies_isSet.
Referenced by SDRPlayInput::webapiFormatDeviceReport().
{
     this->intermediate_frequencies = intermediate_frequencies;
     this->m_intermediate_frequencies_isSet = true;
 }
setSampleRates()
void SWGSDRangel::SWGSDRPlayReport::setSampleRates (QList< SWGSampleRate *> * sample_rates)
Definition at line 145 of file SWGSDRPlayReport.cpp.
References m_sample_rates_isSet, and sample_rates.
Referenced by SDRPlayInput::webapiFormatDeviceReport().
{
     this->sample_rates = sample_rates;
     this->m_sample_rates_isSet = true;
 }
Member Data Documentation
bandwidths
QList<SWGBandwidth*>* SWGSDRangel::SWGSDRPlayReport::bandwidths private
Definition at line 68 of file SWGSDRPlayReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getBandwidths(), init(), isSet(), setBandwidths(), and SWGSDRPlayReport().
frequency_bands
QList<SWGFrequencyBand*>* SWGSDRangel::SWGSDRPlayReport::frequency_bands private
Definition at line 74 of file SWGSDRPlayReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFrequencyBands(), init(), isSet(), setFrequencyBands(), and SWGSDRPlayReport().
intermediate_frequencies
QList<SWGFrequency*>* SWGSDRangel::SWGSDRPlayReport::intermediate_frequencies private
Definition at line 71 of file SWGSDRPlayReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getIntermediateFrequencies(), init(), isSet(), setIntermediateFrequencies(), and SWGSDRPlayReport().
m_bandwidths_isSet
bool SWGSDRangel::SWGSDRPlayReport::m_bandwidths_isSet private
Definition at line 69 of file SWGSDRPlayReport.h.
Referenced by init(), setBandwidths(), and SWGSDRPlayReport().
m_frequency_bands_isSet
bool SWGSDRangel::SWGSDRPlayReport::m_frequency_bands_isSet private
Definition at line 75 of file SWGSDRPlayReport.h.
Referenced by init(), setFrequencyBands(), and SWGSDRPlayReport().
m_intermediate_frequencies_isSet
bool SWGSDRangel::SWGSDRPlayReport::m_intermediate_frequencies_isSet private
Definition at line 72 of file SWGSDRPlayReport.h.
Referenced by init(), setIntermediateFrequencies(), and SWGSDRPlayReport().
m_sample_rates_isSet
bool SWGSDRangel::SWGSDRPlayReport::m_sample_rates_isSet private
Definition at line 66 of file SWGSDRPlayReport.h.
Referenced by init(), setSampleRates(), and SWGSDRPlayReport().
sample_rates
QList<SWGSampleRate*>* SWGSDRangel::SWGSDRPlayReport::sample_rates private
Definition at line 65 of file SWGSDRPlayReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSampleRates(), init(), isSet(), setSampleRates(), and SWGSDRPlayReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGSDRPlayReport.h
swagger/sdrangel/code/qt5/client/SWGSDRPlayReport.cpp