SDRAngel: leansdr::pipereader< T > Struct Template Reference
leansdr::pipereader< T > Struct Template Reference
#include <framework.h>
Public Member Functions
pipereader (pipebuf< T > &_buf)
long readable ()
T * rd ()
void read (unsigned long n)
Public Attributes
pipebuf< T > & buf
int id
Detailed Description
template<typename T>
struct leansdr::pipereader< T >
Definition at line 348 of file framework.h.
Constructor & Destructor Documentation
pipereader()
template<typename T> leansdr::pipereader< T >::pipereader (pipebuf< T > & _buf) inline
Definition at line 353 of file framework.h.
                                  : buf(_buf), id(_buf.add_reader())
     {
     }
Member Function Documentation
rd()
template<typename T> T* leansdr::pipereader< T >::rd () inline
Definition at line 362 of file framework.h.
Referenced by leansdr::etr192_descrambler::run(), leansdr::datvconstellation< leansdr::f32 >::run(), leansdr::datvdvbs2constellation< leansdr::f32 >::run(), leansdr::simple_agc< T >::run(), leansdr::s2_interleaver::run(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::run(), leansdr::viterbi_sync::run(), leansdr::s2_fecenc::run(), leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::run(), leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::run(), leansdr::s2_framer::run(), and leansdr::s2_deframer::run().
     {
         return buf.rds[id];
     }
read()
template<typename T> void leansdr::pipereader< T >::read (unsigned long n) inline
Definition at line 367 of file framework.h.
Referenced by leansdr::etr192_descrambler::run(), leansdr::datvconstellation< leansdr::f32 >::run(), leansdr::datvdvbs2constellation< leansdr::f32 >::run(), leansdr::simple_agc< T >::run(), leansdr::s2_interleaver::run(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::run(), leansdr::viterbi_sync::run(), leansdr::s2_fecenc::run(), leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::run(), leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::run(), leansdr::s2_framer::run(), and leansdr::s2_deframer::run().
     {
         if (buf.rds[id] + n > buf.wr)
         {
             fprintf(stderr, "Bug: underflow from %s\n", buf.name);
         }
         buf.rds[id] += n;
         buf.total_read += n;
     }
readable()
template<typename T> long leansdr::pipereader< T >::readable () inline
Definition at line 357 of file framework.h.
Referenced by leansdr::etr192_descrambler::run(), leansdr::datvconstellation< leansdr::f32 >::run(), leansdr::datvdvbs2constellation< leansdr::f32 >::run(), leansdr::simple_agc< T >::run(), leansdr::s2_interleaver::run(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::run(), leansdr::viterbi_sync::run(), leansdr::s2_fecenc::run(), leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::run(), leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::run(), leansdr::s2_framer::run(), and leansdr::s2_deframer::run().
     {
         return buf.wr - buf.rds[id];
     }
Member Data Documentation
buf
template<typename T> pipebuf<T>& leansdr::pipereader< T >::buf
Definition at line 350 of file framework.h.
id
template<typename T> int leansdr::pipereader< T >::id
Definition at line 351 of file framework.h.
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/framework.h