SDRAngel: DeviceXTRXShared::MsgReportDeviceInfo Class Reference
DeviceXTRXShared::MsgReportDeviceInfo Class Reference
#include <devicextrxshared.h>
Public Member Functions
float getTemperature () const
bool getGPSLocked () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportDeviceInfo * create (float temperature, bool gpsLocked)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportDeviceInfo (float temperature, bool gpsLocked)
Private Attributes
float m_temperature
bool m_gpsLocked
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 105 of file devicextrxshared.h.
Constructor & Destructor Documentation
MsgReportDeviceInfo()
DeviceXTRXShared::MsgReportDeviceInfo::MsgReportDeviceInfo (float temperature, bool gpsLocked) inline private
Definition at line 121 of file devicextrxshared.h.
                                                                :
             Message(),
             m_temperature(temperature),
             m_gpsLocked(gpsLocked)
         { }
Member Function Documentation
create()
static MsgReportDeviceInfo* DeviceXTRXShared::MsgReportDeviceInfo::create (float temperature, bool gpsLocked) inline static
Definition at line 112 of file devicextrxshared.h.
Referenced by XTRXOutput::handleMessage(), and XTRXInput::handleMessage().
         {
             return new MsgReportDeviceInfo(temperature, gpsLocked);
         }
getGPSLocked()
bool DeviceXTRXShared::MsgReportDeviceInfo::getGPSLocked () const inline
Definition at line 110 of file devicextrxshared.h.
Referenced by XTRXOutputGUI::handleMessage(), and XTRXInputGUI::handleMessage().
 { return m_gpsLocked; }
getTemperature()
float DeviceXTRXShared::MsgReportDeviceInfo::getTemperature () const inline
Definition at line 109 of file devicextrxshared.h.
Referenced by XTRXOutputGUI::handleMessage(), and XTRXInputGUI::handleMessage().
 { return m_temperature; }
Member Data Documentation
m_gpsLocked
bool DeviceXTRXShared::MsgReportDeviceInfo::m_gpsLocked private
Definition at line 119 of file devicextrxshared.h.
m_temperature
float DeviceXTRXShared::MsgReportDeviceInfo::m_temperature private
Definition at line 118 of file devicextrxshared.h.
The documentation for this class was generated from the following file:
devices/xtrx/devicextrxshared.h