SDRAngel: RemoteInput::MsgConfigureRemoteInput Class Reference
RemoteInput::MsgConfigureRemoteInput Class Reference
#include <remoteinput.h>
Public Member Functions
const RemoteInputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureRemoteInput * create (const RemoteInputSettings &settings, bool force=false)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureRemoteInput (const RemoteInputSettings &settings, bool force)
Private Attributes
RemoteInputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 43 of file remoteinput.h.
Constructor & Destructor Documentation
MsgConfigureRemoteInput()
RemoteInput::MsgConfigureRemoteInput::MsgConfigureRemoteInput (const RemoteInputSettings & settings, bool force) inline private
Definition at line 59 of file remoteinput.h.
Referenced by create().
                                                                                  :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureRemoteInput* RemoteInput::MsgConfigureRemoteInput::create (const RemoteInputSettings & settings, bool force = false) inline static
Definition at line 50 of file remoteinput.h.
References MsgConfigureRemoteInput().
Referenced by RemoteInput::deserialize(), RemoteInputGui::updateHardware(), and RemoteInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureRemoteInput(settings, force);
         }
getForce()
bool RemoteInput::MsgConfigureRemoteInput::getForce () const inline
Definition at line 48 of file remoteinput.h.
References m_force.
Referenced by RemoteInput::handleMessage().
 { return m_force; }
getSettings()
const RemoteInputSettings& RemoteInput::MsgConfigureRemoteInput::getSettings () const inline
Definition at line 47 of file remoteinput.h.
References m_settings.
Referenced by RemoteInputGui::handleMessage(), and RemoteInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool RemoteInput::MsgConfigureRemoteInput::m_force private
Definition at line 57 of file remoteinput.h.
Referenced by getForce().
m_settings
RemoteInputSettings RemoteInput::MsgConfigureRemoteInput::m_settings private
Definition at line 56 of file remoteinput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/remoteinput/remoteinput.h