SDRAngel: qrtplib::RTCPCompoundPacketBuilder::Report Class Reference
qrtplib::RTCPCompoundPacketBuilder::Report Class Reference
Public Member Functions
Report ()
~Report ()
void Clear ()
std::size_t NeededBytes ()
std::size_t NeededBytesWithExtraReportBlock ()
Public Attributes
bool isSR
uint8_t * headerdata
uint32_t headerdata32 [(sizeof(uint32_t)+sizeof(RTCPSenderReport))/sizeof(uint32_t)]
std::size_t headerlength
std::list< Buffer > reportblocks
Detailed Description
Definition at line 150 of file rtcpcompoundpacketbuilder.h.
Constructor & Destructor Documentation
Report()
qrtplib::RTCPCompoundPacketBuilder::Report::Report () inline
Definition at line 153 of file rtcpcompoundpacketbuilder.h.
         {
             headerdata = (uint8_t *) headerdata32;
             std::fill(&headerdata32[0], &headerdata32[0] + ((sizeof(uint32_t) + sizeof(RTCPSenderReport)) / sizeof(uint32_t)), 0U);
             isSR = false;
             headerlength = 0;
         }
~Report()
qrtplib::RTCPCompoundPacketBuilder::Report::~Report () inline
Definition at line 160 of file rtcpcompoundpacketbuilder.h.
         {
             Clear();
         }
Member Function Documentation
Clear()
void qrtplib::RTCPCompoundPacketBuilder::Report::Clear () inline
Definition at line 165 of file rtcpcompoundpacketbuilder.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::ClearBuildBuffers().
         {
             std::list<Buffer>::const_iterator it;
             for (it = reportblocks.begin(); it != reportblocks.end(); it++)
             {
                 if ((*it).packetdata)
                     delete[] (*it).packetdata;
             }
             reportblocks.clear();
             isSR = false;
             headerlength = 0;
         }
NeededBytes()
std::size_t qrtplib::RTCPCompoundPacketBuilder::Report::NeededBytes () inline
Definition at line 178 of file rtcpcompoundpacketbuilder.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::AddAPPPacket(), qrtplib::RTCPCompoundPacketBuilder::AddBYEPacket(), qrtplib::RTCPCompoundPacketBuilder::AddSDESNormalItem(), qrtplib::RTCPCompoundPacketBuilder::AddSDESPrivateItem(), qrtplib::RTCPCompoundPacketBuilder::AddSDESSource(), and qrtplib::RTCPCompoundPacketBuilder::EndBuild().
         {
             std::size_t x, n, d, r;
             n = reportblocks.size();
             if (n == 0)
             {
                 if (headerlength == 0)
                     return 0;
                 x = sizeof(RTCPCommonHeader) + headerlength;
             }
             else
             {
                 x = n * sizeof(RTCPReceiverReport);
                 d = n / 31; // max 31 reportblocks per report
                 r = n % 31;
                 if (r != 0)
                     d++;
                 x += d * (sizeof(RTCPCommonHeader) + sizeof(uint32_t)); /* header and SSRC */
                 if (isSR)
                     x += sizeof(RTCPSenderReport);
             }
             return x;
         }
NeededBytesWithExtraReportBlock()
std::size_t qrtplib::RTCPCompoundPacketBuilder::Report::NeededBytesWithExtraReportBlock () inline
Definition at line 202 of file rtcpcompoundpacketbuilder.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::AddReportBlock().
         {
             std::size_t x, n, d, r;
             n = reportblocks.size() + 1; // +1 for the extra block
             x = n * sizeof(RTCPReceiverReport);
             d = n / 31; // max 31 reportblocks per report
             r = n % 31;
             if (r != 0)
                 d++;
             x += d * (sizeof(RTCPCommonHeader) + sizeof(uint32_t)); /* header and SSRC */
             if (isSR)
                 x += sizeof(RTCPSenderReport);
             return x;
         }
Member Data Documentation
headerdata
uint8_t* qrtplib::RTCPCompoundPacketBuilder::Report::headerdata
Definition at line 219 of file rtcpcompoundpacketbuilder.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::EndBuild(), qrtplib::RTCPCompoundPacketBuilder::StartReceiverReport(), and qrtplib::RTCPCompoundPacketBuilder::StartSenderReport().
headerdata32
uint32_t qrtplib::RTCPCompoundPacketBuilder::Report::headerdata32[(sizeof(uint32_t)+sizeof(RTCPSenderReport))/sizeof(uint32_t)]
Definition at line 220 of file rtcpcompoundpacketbuilder.h.
headerlength
std::size_t qrtplib::RTCPCompoundPacketBuilder::Report::headerlength
Definition at line 221 of file rtcpcompoundpacketbuilder.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::AddReportBlock(), qrtplib::RTCPCompoundPacketBuilder::EndBuild(), qrtplib::RTCPCompoundPacketBuilder::StartReceiverReport(), and qrtplib::RTCPCompoundPacketBuilder::StartSenderReport().
isSR
bool qrtplib::RTCPCompoundPacketBuilder::Report::isSR
Definition at line 217 of file rtcpcompoundpacketbuilder.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::EndBuild(), qrtplib::RTCPCompoundPacketBuilder::StartReceiverReport(), and qrtplib::RTCPCompoundPacketBuilder::StartSenderReport().
reportblocks
std::list<Buffer> qrtplib::RTCPCompoundPacketBuilder::Report::reportblocks
Definition at line 222 of file rtcpcompoundpacketbuilder.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::AddReportBlock(), and qrtplib::RTCPCompoundPacketBuilder::EndBuild().
The documentation for this class was generated from the following file:
qrtplib/rtcpcompoundpacketbuilder.h