SDRAngel: IntervalRangeGUI Class Reference
IntervalRangeGUI Class Reference
#include <intervalrangegui.h>
Public Member Functions
IntervalRangeGUI (QWidget *parent=0)
virtual ~IntervalRangeGUI ()
void setLabel (const QString &text)
void setUnits (const QString &units)
void addInterval (double minimum, double maximum)
void reset ()
virtual double getCurrentValue ()
virtual void setValue (double value)
Public Member Functions inherited from ItemSettingGUI
ItemSettingGUI (QWidget *parent=0)
virtual ~ItemSettingGUI ()
Private Slots
void on_value_changed (qint64 value)
void on_rangeInterval_currentIndexChanged (int index)
Private Attributes
Ui::IntervalRangeGUI * ui
std::vector< double > m_minima
std::vector< double > m_maxima
int m_nbDigits
Additional Inherited Members
Signals inherited from ItemSettingGUI
void valueChanged (double value)
Detailed Description
Definition at line 32 of file intervalrangegui.h.
Constructor & Destructor Documentation
IntervalRangeGUI()
IntervalRangeGUI::IntervalRangeGUI (QWidget * parent = 0) explicit
Definition at line 23 of file intervalrangegui.cpp.
References ColorMapper::GrayGreenYellow, and ui.
                                                   :
     ItemSettingGUI(parent),
     ui(new Ui::IntervalRangeGUI),
     m_nbDigits(7)
 {
     ui->setupUi(this);
     ui->value->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
 }
~IntervalRangeGUI()
IntervalRangeGUI::~IntervalRangeGUI () virtual
Definition at line 32 of file intervalrangegui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
addInterval()
void IntervalRangeGUI::addInterval (double minimum, double maximum)
Definition at line 47 of file intervalrangegui.cpp.
References arg(), m_maxima, m_minima, and ui.
Referenced by SoapySDRInputGui::createRangesControl(), and SoapySDROutputGui::createRangesControl().
 {
     ui->rangeInterval->blockSignals(true);
     ui->rangeInterval->addItem(QString("%1").arg(m_minima.size()));
     ui->rangeInterval->blockSignals(false);
     m_minima.push_back(minimum);
     m_maxima.push_back(maximum);
 }
getCurrentValue()
double IntervalRangeGUI::getCurrentValue () virtual
Implements ItemSettingGUI.
Definition at line 82 of file intervalrangegui.cpp.
References ui.
 {
     return ui->value->getValueNew();
 }
on_rangeInterval_currentIndexChanged
void IntervalRangeGUI::on_rangeInterval_currentIndexChanged (int index) private slot
Definition at line 97 of file intervalrangegui.cpp.
References m_maxima, m_minima, m_nbDigits, ui, and ItemSettingGUI::valueChanged().
 {
     ui->value->setValueRange(m_minima[index] >= 0, m_nbDigits, m_minima[index], m_maxima[index]);
     emit ItemSettingGUI::valueChanged(ui->value->getValueNew());
 }
on_value_changed
void IntervalRangeGUI::on_value_changed (qint64 value) private slot
Definition at line 92 of file intervalrangegui.cpp.
References ItemSettingGUI::valueChanged().
 {
     emit ItemSettingGUI::valueChanged(value);
 }
reset()
void IntervalRangeGUI::reset ()
Definition at line 56 of file intervalrangegui.cpp.
References m_maxima, m_minima, m_nbDigits, and ui.
Referenced by SoapySDRInputGui::createRangesControl(), and SoapySDROutputGui::createRangesControl().
 {
     if (m_minima.size() > 0)
     {
         double maxLog = 0.0;
         for (const auto &it : m_maxima)
         {
             if (log10(it) > maxLog) {
                 maxLog = log10(it);
             }
         }
         m_nbDigits = maxLog;
         m_nbDigits++;
         ui->rangeInterval->blockSignals(true);
         ui->rangeInterval->setCurrentIndex(0);
         ui->rangeInterval->blockSignals(false);
         ui->value->setValueRange(m_minima[0] >= 0, m_nbDigits, m_minima[0], m_maxima[0]);
     }
     if (m_minima.size() == 1) {
         ui->rangeInterval->setDisabled(true);
     }
 }
setLabel()
void IntervalRangeGUI::setLabel (const QString & text)
Definition at line 37 of file intervalrangegui.cpp.
References ui.
Referenced by SoapySDRInputGui::createRangesControl(), and SoapySDROutputGui::createRangesControl().
 {
     ui->rangeLabel->setText(text);
 }
setUnits()
void IntervalRangeGUI::setUnits (const QString & units)
Definition at line 42 of file intervalrangegui.cpp.
References ui.
Referenced by SoapySDRInputGui::createRangesControl(), and SoapySDROutputGui::createRangesControl().
 {
     ui->rangeUnits->setText(units);
 }
setValue()
void IntervalRangeGUI::setValue (double value) virtual
Implements ItemSettingGUI.
Definition at line 87 of file intervalrangegui.cpp.
References ui.
 {
     ui->value->setValue(value);
 }
Member Data Documentation
m_maxima
std::vector<double> IntervalRangeGUI::m_maxima private
Definition at line 53 of file intervalrangegui.h.
Referenced by addInterval(), on_rangeInterval_currentIndexChanged(), and reset().
m_minima
std::vector<double> IntervalRangeGUI::m_minima private
Definition at line 52 of file intervalrangegui.h.
Referenced by addInterval(), on_rangeInterval_currentIndexChanged(), and reset().
m_nbDigits
int IntervalRangeGUI::m_nbDigits private
Definition at line 54 of file intervalrangegui.h.
Referenced by on_rangeInterval_currentIndexChanged(), and reset().
ui
Ui::IntervalRangeGUI* IntervalRangeGUI::ui private
Definition at line 51 of file intervalrangegui.h.
Referenced by addInterval(), getCurrentValue(), IntervalRangeGUI(), on_rangeInterval_currentIndexChanged(), reset(), setLabel(), setUnits(), setValue(), and ~IntervalRangeGUI().
The documentation for this class was generated from the following files:
sdrgui/soapygui/intervalrangegui.h
sdrgui/soapygui/intervalrangegui.cpp