SDRAngel: SDRPlayInput Class Reference
SDRPlayInput Class Reference
#include <sdrplayinput.h>
Classes
class MsgConfigureSDRPlay
class MsgFileRecord
class MsgReportSDRPlayGains
class MsgStartStop
Public Types
enum SDRPlayVariant { SDRPlayUndef, SDRPlayRSP1, SDRPlayRSP1A, SDRPlayRSP2 }
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Public Member Functions
SDRPlayInput (DeviceAPI *deviceAPI)
virtual ~SDRPlayInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
SDRPlayVariant getVariant () const
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
bool applySettings (const SDRPlaySettings &settings, bool forwardChange, bool force)
bool setDeviceCenterFrequency (quint64 freq)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const SDRPlaySettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const SDRPlaySettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
SDRPlayVariant m_variant
SDRPlaySettings m_settings
mirisdr_dev_t * m_dev
SDRPlayThread * m_sdrPlayThread
QString m_deviceDescription
int m_devNumber
bool m_running
FileRecord * m_fileSink
File sink to record device I/Q output.
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 37 of file sdrplayinput.h.
Member Enumeration Documentation
SDRPlayVariant
enum SDRPlayInput::SDRPlayVariant
Enumerator
SDRPlayUndef
SDRPlayRSP1
SDRPlayRSP1A
SDRPlayRSP2
Definition at line 40 of file sdrplayinput.h.
     {
         SDRPlayUndef,
         SDRPlayRSP1,
         SDRPlayRSP1A,
         SDRPlayRSP2
     };
Constructor & Destructor Documentation
SDRPlayInput()
SDRPlayInput::SDRPlayInput (DeviceAPI * deviceAPI)
Definition at line 45 of file sdrplayinput.cpp.
References arg().
Referenced by SDRPlayInput::MsgStartStop::MsgStartStop().
                                                :
     m_deviceAPI(deviceAPI),
     m_variant(SDRPlayUndef),
     m_settings(),
     m_dev(0),
     m_sdrPlayThread(0),
     m_deviceDescription("SDRPlay"),
     m_devNumber(0),
     m_running(false)
 {
     openDevice();
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~SDRPlayInput()
SDRPlayInput::~SDRPlayInput () virtual
Definition at line 64 of file sdrplayinput.cpp.
References closeDevice(), m_deviceAPI, m_fileSink, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::removeAncillarySink(), and stop().
Referenced by SDRPlayInput::MsgStartStop::MsgStartStop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
     closeDevice();
 }
Member Function Documentation
applySettings()
bool SDRPlayInput::applySettings (const SDRPlaySettings & settings, bool forwardChange, bool force) private
Definition at line 363 of file sdrplayinput.cpp.
References DeviceSampleSource::calculateDeviceCenterFrequency(), DeviceAPI::configureCorrections(), SDRPlayInput::MsgReportSDRPlayGains::create(), SDRPlayBandwidths::getBandwidth(), DeviceAPI::getDeviceEngineInputMessageQueue(), SDRPlayIF::getIF(), DeviceSampleSource::getMessageQueueToGUI(), SDRPlaySampleRates::getRate(), getSampleRate(), FileRecord::handleMessage(), SDRPlaySettings::m_bandwidthIndex, SDRPlaySettings::m_basebandGain, SDRPlaySettings::m_centerFrequency, SDRPlaySettings::m_dcBlock, m_dev, m_deviceAPI, SDRPlaySettings::m_devSampleRateIndex, SDRPlaySettings::m_fcPos, m_fileSink, SDRPlaySettings::m_frequencyBandIndex, SDRPlaySettings::m_ifFrequencyIndex, SDRPlaySettings::m_iqCorrection, SDRPlaySettings::m_lnaOn, SDRPlaySettings::m_log2Decim, SDRPlaySettings::m_LOppmTenths, SDRPlaySettings::m_mixerAmpOn, m_mutex, SDRPlaySettings::m_reverseAPIAddress, SDRPlaySettings::m_reverseAPIDeviceIndex, SDRPlaySettings::m_reverseAPIPort, m_sdrPlayThread, m_settings, SDRPlaySettings::m_tunerGain, SDRPlaySettings::m_tunerGainMode, SDRPlaySettings::m_useReverseAPI, MessageQueue::push(), setDeviceCenterFrequency(), SDRPlayThread::setFcPos(), SDRPlayThread::setLog2Decimation(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     bool forceGainSetting = false;
     QList<QString> reverseAPIKeys;
     QMutexLocker mutexLocker(&m_mutex);
     if ((m_settings.m_dcBlock != settings.m_dcBlock) || force)
     {
         reverseAPIKeys.append("dcBlock");
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqCorrection);
     }
     if ((m_settings.m_iqCorrection != settings.m_iqCorrection) || force)
     {
         reverseAPIKeys.append("iqCorrection");
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqCorrection);
     }
     // gains processing
     if ((m_settings.m_tunerGainMode != settings.m_tunerGainMode) || force)
     {
         reverseAPIKeys.append("tunerGainMode");
         forceGainSetting = true;
     }
     if ((m_settings.m_tunerGain != settings.m_tunerGain) || force) {
         reverseAPIKeys.append("tunerGain");
     }
     if ((m_settings.m_lnaOn != settings.m_lnaOn) || force) {
         reverseAPIKeys.append("lnaOn");
     }
     if (settings.m_tunerGainMode) // auto
     {
         if ((m_settings.m_tunerGain != settings.m_tunerGain) || forceGainSetting)
         {
             if(m_dev != 0)
             {
                 int r = mirisdr_set_tuner_gain(m_dev, settings.m_tunerGain);
                 if (r < 0)
                 {
                     qDebug("SDRPlayInput::applySettings: could not set tuner gain");
                 }
                 else
                 {
                     int lnaGain;
                     if (settings.m_frequencyBandIndex < 3) // bands using AM mode
                     {
                         lnaGain = mirisdr_get_mixbuffer_gain(m_dev);
                     }
                     else
                     {
                         lnaGain = mirisdr_get_lna_gain(m_dev);
                     }
                     MsgReportSDRPlayGains *message = MsgReportSDRPlayGains::create(
                             lnaGain,
                             mirisdr_get_mixer_gain(m_dev),
                             mirisdr_get_baseband_gain(m_dev),
                             mirisdr_get_tuner_gain(m_dev)
                     );
                     if (getMessageQueueToGUI()) {
                         getMessageQueueToGUI()->push(message);
                     }
                 }
             }
         }
     }
     else // manual
     {
         bool anyChange = false;
         if ((m_settings.m_lnaOn != settings.m_lnaOn) || forceGainSetting)
         {
             if (m_dev != 0)
             {
                 if (settings.m_frequencyBandIndex < 3) // bands using AM mode
                 {
                     int r = mirisdr_set_mixbuffer_gain(m_dev, settings.m_lnaOn ? 0 : 1); // mirisdr_set_mixbuffer_gain takes gain reduction
                     if (r != 0) {
                         qDebug("SDRPlayInput::applySettings: could not set mixer buffer gain");
                     } else {
                         anyChange = true;
                     }
                 }
                 else
                 {
                     int r = mirisdr_set_lna_gain(m_dev, settings.m_lnaOn ? 0 : 1); // mirisdr_set_lna_gain takes gain reduction
                     if (r != 0) {
                         qDebug("SDRPlayInput::applySettings: could not set LNA gain");
                     } else {
                         anyChange = true;
                     }
                 }
             }
         }
         if ((m_settings.m_mixerAmpOn != settings.m_mixerAmpOn) || forceGainSetting)
         {
             reverseAPIKeys.append("mixerAmpOn");
             if (m_dev != 0)
             {
                 int r = mirisdr_set_mixer_gain(m_dev, settings.m_mixerAmpOn ? 0 : 1); // mirisdr_set_lna_gain takes gain reduction
                 if (r != 0) {
                     qDebug("SDRPlayInput::applySettings: could not set mixer gain");
                 } else {
                     anyChange = true;
                 }
             }
         }
         if ((m_settings.m_basebandGain != settings.m_basebandGain) || forceGainSetting)
         {
             reverseAPIKeys.append("basebandGain");
             if (m_dev != 0)
             {
                 int r = mirisdr_set_baseband_gain(m_dev, settings.m_basebandGain);
                 if (r != 0) {
                     qDebug("SDRPlayInput::applySettings: could not set mixer gain");
                 } else {
                     anyChange = true;
                 }
             }
         }
         if (anyChange)
         {
             int lnaGain;
             if (settings.m_frequencyBandIndex < 3) { // bands using AM mode
                 lnaGain = mirisdr_get_mixbuffer_gain(m_dev);
             } else {
                 lnaGain = mirisdr_get_lna_gain(m_dev);
             }
             MsgReportSDRPlayGains *message = MsgReportSDRPlayGains::create(
                     lnaGain,
                     mirisdr_get_mixer_gain(m_dev),
                     mirisdr_get_baseband_gain(m_dev),
                     mirisdr_get_tuner_gain(m_dev)
             );
             if (getMessageQueueToGUI()) {
                 getMessageQueueToGUI()->push(message);
             }
         }
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         reverseAPIKeys.append("log2Decim");
         if (m_sdrPlayThread != 0)
         {
             m_sdrPlayThread->setLog2Decimation(settings.m_log2Decim);
             qDebug() << "SDRPlayInput::applySettings: set decimation to " << (1<<settings.m_log2Decim);
         }
     }
     if ((m_settings.m_fcPos != settings.m_fcPos) || force)
     {
         reverseAPIKeys.append("fcPos");
         if (m_sdrPlayThread != 0)
         {
             m_sdrPlayThread->setFcPos((int) settings.m_fcPos);
             qDebug() << "SDRPlayInput: set fc pos (enum) to " << (int) settings.m_fcPos;
         }
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency) || force) {
         reverseAPIKeys.append("centerFrequency");
     }
     if ((m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force) {
         reverseAPIKeys.append("LOppmTenths");
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency)
         || (m_settings.m_LOppmTenths != settings.m_LOppmTenths)
         || (m_settings.m_fcPos != settings.m_fcPos)
         || (m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         qint64 deviceCenterFrequency = DeviceSampleSource::calculateDeviceCenterFrequency(
                 settings.m_centerFrequency,
                 0,
                 settings.m_log2Decim,
                 (DeviceSampleSource::fcPos_t) settings.m_fcPos,
                 SDRPlaySampleRates::getRate(settings.m_devSampleRateIndex),
                 DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD,
                 false);
         forwardChange = true;
         if(m_dev != 0)
         {
             if (setDeviceCenterFrequency(deviceCenterFrequency)) {
                 qDebug() << "SDRPlayInput::applySettings: center freq: " << settings.m_centerFrequency << " Hz";
             }
         }
     }
     if ((m_settings.m_bandwidthIndex != settings.m_bandwidthIndex) || force)
     {
         reverseAPIKeys.append("bandwidthIndex");
         int bandwidth = SDRPlayBandwidths::getBandwidth(settings.m_bandwidthIndex);
         int r = mirisdr_set_bandwidth(m_dev, bandwidth);
         if (r < 0) {
             qCritical("SDRPlayInput::applySettings: set bandwidth %d failed: rc: %d", bandwidth, r);
         } else {
             qDebug("SDRPlayInput::applySettings: bandwidth set to %d", bandwidth);
         }
     }
     if ((m_settings.m_ifFrequencyIndex != settings.m_ifFrequencyIndex) || force)
     {
         reverseAPIKeys.append("ifFrequencyIndex");
         int iFFrequency = SDRPlayIF::getIF(settings.m_ifFrequencyIndex);
         int r = mirisdr_set_if_freq(m_dev, iFFrequency);
         if (r < 0) {
             qCritical("SDRPlayInput::applySettings: set IF frequency to %d failed: rc: %d", iFFrequency, r);
         } else {
             qDebug("SDRPlayInput::applySettings: IF frequency set to %d", iFFrequency);
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     if (forwardChange)
     {
         int sampleRate = getSampleRate();
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, m_settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     return true;
 }
closeDevice()
void SDRPlayInput::closeDevice () private
Definition at line 197 of file sdrplayinput.cpp.
References m_dev, and m_deviceDescription.
Referenced by openDevice(), and ~SDRPlayInput().
 {
     if (m_dev != 0)
     {
         mirisdr_close(m_dev);
         m_dev = 0;
     }
     m_deviceDescription.clear();
 }
deserialize()
bool SDRPlayInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 232 of file sdrplayinput.cpp.
References SDRPlayInput::MsgConfigureSDRPlay::create(), SDRPlaySettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and SDRPlaySettings::resetToDefaults().
Referenced by SDRPlayInput::MsgStartStop::MsgStartStop().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureSDRPlay* message = MsgConfigureSDRPlay::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureSDRPlay* messageToGUI = MsgConfigureSDRPlay::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void SDRPlayInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 78 of file sdrplayinput.cpp.
Referenced by SDRPlayInput::MsgStartStop::MsgStartStop().
 {
     delete this;
 }
getCenterFrequency()
quint64 SDRPlayInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 265 of file sdrplayinput.cpp.
References SDRPlaySettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & SDRPlayInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 254 of file sdrplayinput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getSampleRate()
int SDRPlayInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 259 of file sdrplayinput.cpp.
References SDRPlaySampleRates::getRate(), SDRPlaySettings::m_devSampleRateIndex, SDRPlaySettings::m_log2Decim, and m_settings.
Referenced by applySettings(), and setMessageQueueToGUI().
 {
     int rate = SDRPlaySampleRates::getRate(m_settings.m_devSampleRateIndex);
     return rate / (1<<m_settings.m_log2Decim);
 }
getVariant()
SDRPlayVariant SDRPlayInput::getVariant () const inline
Definition at line 181 of file sdrplayinput.h.
References m_variant.
 { return m_variant; }
handleMessage()
bool SDRPlayInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 285 of file sdrplayinput.cpp.
References applySettings(), FileRecord::genUniqueFileName(), DeviceAPI::getDeviceUID(), SDRPlayInput::MsgConfigureSDRPlay::getForce(), SDRPlayInput::MsgConfigureSDRPlay::getSettings(), SDRPlayInput::MsgFileRecord::getStartStop(), SDRPlayInput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), m_dev, m_deviceAPI, SDRPlaySettings::m_devSampleRateIndex, SDRPlaySettings::m_fileRecordName, m_fileSink, m_settings, SDRPlaySettings::m_useReverseAPI, Message::match(), FileRecord::setFileName(), start(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), stop(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (MsgConfigureSDRPlay::match(message))
     {
         MsgConfigureSDRPlay& conf = (MsgConfigureSDRPlay&) message;
         qDebug() << "SDRPlayInput::handleMessage: MsgConfigureSDRPlay";
         const SDRPlaySettings& settings = conf.getSettings();
         // change of sample rate needs full stop / start sequence that includes the standard apply settings
         // only if in started state (iff m_dev != 0)
         if ((m_dev != 0) && (m_settings.m_devSampleRateIndex != settings.m_devSampleRateIndex))
         {
             m_settings = settings;
             stop();
             start();
         }
         // standard changes
         else
         {
             if (!applySettings(settings, false, conf.getForce()))
             {
                 qDebug("SDRPlayInput::handleMessage: config error");
             }
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "SDRPlayInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "SDRPlayInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void SDRPlayInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 208 of file sdrplayinput.cpp.
References applySettings(), and m_settings.
Referenced by SDRPlayInput::MsgStartStop::MsgStartStop().
 {
     applySettings(m_settings, true, true);
 }
networkManagerFinished
void SDRPlayInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 956 of file sdrplayinput.cpp.
References SDRPlaySampleRates::m_rates.
Referenced by ~SDRPlayInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "SDRPlayInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("SDRPlayInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openDevice()
bool SDRPlayInput::openDevice () private
Definition at line 83 of file sdrplayinput.cpp.
References closeDevice(), DeviceAPI::getSamplingDeviceSequence(), m_dev, m_deviceAPI, m_deviceDescription, m_devNumber, DeviceSampleSource::m_sampleFifo, m_variant, SDRPlayRSP1, SDRPlayRSP1A, SDRPlayRSP2, SampleSinkFifo::setSize(), and stop().
 {
     m_devNumber = m_deviceAPI->getSamplingDeviceSequence();
     if (m_dev != 0)
     {
         closeDevice();
     }
     int res;
     //int numberOfGains;
     if (!m_sampleFifo.setSize(96000 * 4))
     {
         qCritical("SDRPlayInput::openDevice: could not allocate SampleFifo");
         return false;
     }
     if ((res = mirisdr_open(&m_dev, MIRISDR_HW_SDRPLAY, m_devNumber)) < 0)
     {
         qCritical("SDRPlayInput::openDevice: could not open SDRPlay #%d: %s", m_devNumber, strerror(errno));
         return false;
     }
     char vendor[256];
     char product[256];
     char serial[256];
     vendor[0] = '\0';
     product[0] = '\0';
     serial[0] = '\0';
     if ((res = mirisdr_get_device_usb_strings(m_devNumber, vendor, product, serial)) < 0)
     {
         qCritical("SDRPlayInput::openDevice: error accessing USB device");
         stop();
         return false;
     }
     qWarning("SDRPlayInput::openDevice: %s %s, SN: %s", vendor, product, serial);
     m_deviceDescription = QString("%1 (SN %2)").arg(product).arg(serial);
     if (QString(product) == "RSP1A") {
         m_variant = SDRPlayRSP1A;
     } else if (QString(product) == "RSP2") {
         m_variant = SDRPlayRSP2;
     } else {
         m_variant = SDRPlayRSP1;
     }
     qDebug("SDRPlayInput::openDevice: m_variant: %d", (int) m_variant);
     return true;
 }
serialize()
QByteArray SDRPlayInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 227 of file sdrplayinput.cpp.
References m_settings, and SDRPlaySettings::serialize().
Referenced by SDRPlayInput::MsgStartStop::MsgStartStop().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void SDRPlayInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 270 of file sdrplayinput.cpp.
References SDRPlayInput::MsgConfigureSDRPlay::create(), SDRPlaySettings::m_centerFrequency, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     SDRPlaySettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureSDRPlay* message = MsgConfigureSDRPlay::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureSDRPlay* messageToGUI = MsgConfigureSDRPlay::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setDeviceCenterFrequency()
bool SDRPlayInput::setDeviceCenterFrequency (quint64 freq) private
Definition at line 622 of file sdrplayinput.cpp.
References m_dev, SDRPlaySettings::m_LOppmTenths, and m_settings.
Referenced by applySettings().
 {
     qint64 df = ((qint64)freq_hz * m_settings.m_LOppmTenths) / 10000000LL;
     freq_hz += df;
     int r = mirisdr_set_center_freq(m_dev, static_cast<uint32_t>(freq_hz));
     if (r != 0)
     {
         qWarning("SDRPlayInput::setDeviceCenterFrequency: could not frequency to %llu Hz", freq_hz);
         return false;
     }
     else
     {
         qWarning("SDRPlayInput::setDeviceCenterFrequency: frequency set to %llu Hz", freq_hz);
         return true;
     }
 }
setMessageQueueToGUI()
virtual void SDRPlayInput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 149 of file sdrplayinput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSource::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void SDRPlayInput::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 152 of file sdrplayinput.h.
References getCenterFrequency(), handleMessage(), setCenterFrequency(), webapiReportGet(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
start()
bool SDRPlayInput::start () virtual
Implements DeviceSampleSource.
Definition at line 138 of file sdrplayinput.cpp.
References applySettings(), SDRPlaySampleRates::getRate(), m_dev, SDRPlaySettings::m_devSampleRateIndex, SDRPlaySettings::m_fcPos, SDRPlaySettings::m_log2Decim, m_running, DeviceSampleSource::m_sampleFifo, m_sdrPlayThread, m_settings, SDRPlayThread::setFcPos(), SDRPlayThread::setLog2Decimation(), SDRPlayThread::startWork(), and stop().
Referenced by handleMessage(), and SDRPlayInput::MsgStartStop::MsgStartStop().
 {
 //    QMutexLocker mutexLocker(&m_mutex);
     int res;
     if (!m_dev) {
         return false;
     }
     if (m_running) stop();
     char s12FormatString[] = "336_S16";
     if ((res = mirisdr_set_sample_format(m_dev, s12FormatString))) // sample format S12
     {
         qCritical("SDRPlayInput::start: could not set sample format: rc: %d", res);
         stop();
         return false;
     }
     int sampleRate = SDRPlaySampleRates::getRate(m_settings.m_devSampleRateIndex);
     if ((res = mirisdr_set_sample_rate(m_dev, sampleRate)))
     {
         qCritical("SDRPlayInput::start: could not set sample rate to %d: rc: %d", sampleRate, res);
         stop();
         return false;
     }
     char bulkFormatString[] = "BULK";
     if ((res = mirisdr_set_transfer(m_dev, bulkFormatString)) < 0)
     {
         qCritical("SDRPlayInput::start: could not set USB Bulk mode: rc: %d", res);
         stop();
         return false;
     }
     if ((res = mirisdr_reset_buffer(m_dev)) < 0)
     {
         qCritical("SDRPlayInput::start: could not reset USB EP buffers: %s", strerror(errno));
         stop();
         return false;
     }
     m_sdrPlayThread = new SDRPlayThread(m_dev, &m_sampleFifo);
     m_sdrPlayThread->setLog2Decimation(m_settings.m_log2Decim);
     m_sdrPlayThread->setFcPos((int) m_settings.m_fcPos);
     m_sdrPlayThread->startWork();
 //  mutexLocker.unlock();
     applySettings(m_settings, true, true);
     m_running = true;
     return true;
 }
stop()
void SDRPlayInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 213 of file sdrplayinput.cpp.
References m_running, m_sdrPlayThread, and SDRPlayThread::stopWork().
Referenced by handleMessage(), SDRPlayInput::MsgStartStop::MsgStartStop(), openDevice(), start(), and ~SDRPlayInput().
 {
 //    QMutexLocker mutexLocker(&m_mutex);
     if(m_sdrPlayThread != 0)
     {
         m_sdrPlayThread->stopWork();
         delete m_sdrPlayThread;
         m_sdrPlayThread = 0;
     }
     m_running = false;
 }
webapiFormatDeviceReport()
void SDRPlayInput::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 813 of file sdrplayinput.cpp.
References SDRPlayBands::getBandHigh(), SDRPlayBands::getBandLow(), SDRPlayBands::getBandName(), SDRPlayBandwidths::getBandwidth(), SWGSDRangel::SWGSDRPlayReport::getBandwidths(), SWGSDRangel::SWGSDRPlayReport::getFrequencyBands(), SDRPlayIF::getIF(), SWGSDRangel::SWGSDRPlayReport::getIntermediateFrequencies(), SDRPlayBands::getNbBands(), SDRPlayBandwidths::getNbBandwidths(), SDRPlayIF::getNbIFs(), SDRPlaySampleRates::getNbRates(), SDRPlaySampleRates::getRate(), SWGSDRangel::SWGSDRPlayReport::getSampleRates(), SWGSDRangel::SWGDeviceReport::getSdrPlayReport(), i, SWGSDRangel::SWGSDRPlayReport::setBandwidths(), SWGSDRangel::SWGSDRPlayReport::setFrequencyBands(), SWGSDRangel::SWGSDRPlayReport::setIntermediateFrequencies(), and SWGSDRangel::SWGSDRPlayReport::setSampleRates().
Referenced by webapiReportGet().
 {
     response.getSdrPlayReport()->setSampleRates(new QList<SWGSDRangel::SWGSampleRate*>);
     for (unsigned int i = 0; i < SDRPlaySampleRates::getNbRates(); i++)
     {
         response.getSdrPlayReport()->getSampleRates()->append(new SWGSDRangel::SWGSampleRate);
         response.getSdrPlayReport()->getSampleRates()->back()->setRate(SDRPlaySampleRates::getRate(i));
     }
     response.getSdrPlayReport()->setIntermediateFrequencies(new QList<SWGSDRangel::SWGFrequency*>);
     for (unsigned int i = 0; i < SDRPlayIF::getNbIFs(); i++)
     {
         response.getSdrPlayReport()->getIntermediateFrequencies()->append(new SWGSDRangel::SWGFrequency);
         response.getSdrPlayReport()->getIntermediateFrequencies()->back()->setFrequency(SDRPlayIF::getIF(i));
     }
     response.getSdrPlayReport()->setBandwidths(new QList<SWGSDRangel::SWGBandwidth*>);
     for (unsigned int i = 0; i < SDRPlayBandwidths::getNbBandwidths(); i++)
     {
         response.getSdrPlayReport()->getBandwidths()->append(new SWGSDRangel::SWGBandwidth);
         response.getSdrPlayReport()->getBandwidths()->back()->setBandwidth(SDRPlayBandwidths::getBandwidth(i));
     }
     response.getSdrPlayReport()->setFrequencyBands(new QList<SWGSDRangel::SWGFrequencyBand*>);
     for (unsigned int i = 0; i < SDRPlayBands::getNbBands(); i++)
     {
         response.getSdrPlayReport()->getFrequencyBands()->append(new SWGSDRangel::SWGFrequencyBand);
         response.getSdrPlayReport()->getFrequencyBands()->back()->setName(new QString(SDRPlayBands::getBandName(i)));
         response.getSdrPlayReport()->getFrequencyBands()->back()->setLowerBound(SDRPlayBands::getBandLow(i));
         response.getSdrPlayReport()->getFrequencyBands()->back()->setHigherBound(SDRPlayBands::getBandHigh(i));
     }
 }
webapiFormatDeviceSettings()
void SDRPlayInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const SDRPlaySettings & settings) private
Definition at line 766 of file sdrplayinput.cpp.
References SWGSDRangel::SWGSDRPlaySettings::getFileRecordName(), SWGSDRangel::SWGSDRPlaySettings::getReverseApiAddress(), SWGSDRangel::SWGDeviceSettings::getSdrPlaySettings(), SDRPlaySettings::m_bandwidthIndex, SDRPlaySettings::m_basebandGain, SDRPlaySettings::m_centerFrequency, SDRPlaySettings::m_dcBlock, SDRPlaySettings::m_devSampleRateIndex, SDRPlaySettings::m_fcPos, SDRPlaySettings::m_fileRecordName, SDRPlaySettings::m_frequencyBandIndex, SDRPlaySettings::m_ifFrequencyIndex, SDRPlaySettings::m_iqCorrection, SDRPlaySettings::m_lnaOn, SDRPlaySettings::m_log2Decim, SDRPlaySettings::m_LOppmTenths, SDRPlaySettings::m_mixerAmpOn, SDRPlaySettings::m_reverseAPIAddress, SDRPlaySettings::m_reverseAPIDeviceIndex, SDRPlaySettings::m_reverseAPIPort, SDRPlaySettings::m_tunerGain, SDRPlaySettings::m_tunerGainMode, SDRPlaySettings::m_useReverseAPI, SWGSDRangel::SWGSDRPlaySettings::setBandwidthIndex(), SWGSDRangel::SWGSDRPlaySettings::setBasebandGain(), SWGSDRangel::SWGSDRPlaySettings::setCenterFrequency(), SWGSDRangel::SWGSDRPlaySettings::setDcBlock(), SWGSDRangel::SWGSDRPlaySettings::setDevSampleRateIndex(), SWGSDRangel::SWGSDRPlaySettings::setFcPos(), SWGSDRangel::SWGSDRPlaySettings::setFileRecordName(), SWGSDRangel::SWGSDRPlaySettings::setFrequencyBandIndex(), SWGSDRangel::SWGSDRPlaySettings::setIfFrequencyIndex(), SWGSDRangel::SWGSDRPlaySettings::setIqCorrection(), SWGSDRangel::SWGSDRPlaySettings::setLnaOn(), SWGSDRangel::SWGSDRPlaySettings::setLog2Decim(), SWGSDRangel::SWGSDRPlaySettings::setLOppmTenths(), SWGSDRangel::SWGSDRPlaySettings::setMixerAmpOn(), SWGSDRangel::SWGSDRPlaySettings::setReverseApiAddress(), SWGSDRangel::SWGSDRPlaySettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGSDRPlaySettings::setReverseApiPort(), SWGSDRangel::SWGSDRPlaySettings::setTunerGain(), SWGSDRangel::SWGSDRPlaySettings::setTunerGainMode(), and SWGSDRangel::SWGSDRPlaySettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getSdrPlaySettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getSdrPlaySettings()->setTunerGain(settings.m_tunerGain);
     response.getSdrPlaySettings()->setLOppmTenths(settings.m_LOppmTenths);
     response.getSdrPlaySettings()->setFrequencyBandIndex(settings.m_frequencyBandIndex);
     response.getSdrPlaySettings()->setIfFrequencyIndex(settings.m_ifFrequencyIndex);
     response.getSdrPlaySettings()->setBandwidthIndex(settings.m_bandwidthIndex);
     response.getSdrPlaySettings()->setDevSampleRateIndex(settings.m_devSampleRateIndex);
     response.getSdrPlaySettings()->setLog2Decim(settings.m_log2Decim);
     response.getSdrPlaySettings()->setFcPos((int) settings.m_fcPos);
     response.getSdrPlaySettings()->setDcBlock(settings.m_dcBlock ? 1 : 0);
     response.getSdrPlaySettings()->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     response.getSdrPlaySettings()->setTunerGainMode((int) settings.m_tunerGainMode);
     response.getSdrPlaySettings()->setLnaOn(settings.m_lnaOn ? 1 : 0);
     response.getSdrPlaySettings()->setMixerAmpOn(settings.m_mixerAmpOn ? 1 : 0);
     response.getSdrPlaySettings()->setBasebandGain(settings.m_basebandGain);
     if (response.getSdrPlaySettings()->getFileRecordName()) {
         *response.getSdrPlaySettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getSdrPlaySettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getSdrPlaySettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getSdrPlaySettings()->getReverseApiAddress()) {
         *response.getSdrPlaySettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getSdrPlaySettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getSdrPlaySettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getSdrPlaySettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int SDRPlayInput::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 802 of file sdrplayinput.cpp.
References SWGSDRangel::SWGDeviceReport::getSdrPlayReport(), SWGSDRangel::SWGSDRPlayReport::init(), SWGSDRangel::SWGDeviceReport::setSdrPlayReport(), and webapiFormatDeviceReport().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setSdrPlayReport(new SWGSDRangel::SWGSDRPlayReport());
     response.getSdrPlayReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void SDRPlayInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const SDRPlaySettings & settings, bool force) private
Definition at line 850 of file sdrplayinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getSdrPlaySettings(), SDRPlaySettings::m_bandwidthIndex, SDRPlaySettings::m_basebandGain, SDRPlaySettings::m_centerFrequency, SDRPlaySettings::m_dcBlock, m_deviceAPI, SDRPlaySettings::m_devSampleRateIndex, SDRPlaySettings::m_fcPos, SDRPlaySettings::m_fileRecordName, SDRPlaySettings::m_frequencyBandIndex, SDRPlaySettings::m_ifFrequencyIndex, SDRPlaySettings::m_iqCorrection, SDRPlaySettings::m_lnaOn, SDRPlaySettings::m_log2Decim, SDRPlaySettings::m_LOppmTenths, SDRPlaySettings::m_mixerAmpOn, m_networkManager, m_networkRequest, SDRPlaySettings::m_reverseAPIAddress, SDRPlaySettings::m_reverseAPIDeviceIndex, SDRPlaySettings::m_reverseAPIPort, SDRPlaySettings::m_tunerGain, SDRPlaySettings::m_tunerGainMode, SWGSDRangel::SWGSDRPlaySettings::setBandwidthIndex(), SWGSDRangel::SWGSDRPlaySettings::setBasebandGain(), SWGSDRangel::SWGSDRPlaySettings::setCenterFrequency(), SWGSDRangel::SWGSDRPlaySettings::setDcBlock(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGSDRPlaySettings::setDevSampleRateIndex(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGSDRPlaySettings::setFcPos(), SWGSDRangel::SWGSDRPlaySettings::setFileRecordName(), SWGSDRangel::SWGSDRPlaySettings::setFrequencyBandIndex(), SWGSDRangel::SWGSDRPlaySettings::setIfFrequencyIndex(), SWGSDRangel::SWGSDRPlaySettings::setIqCorrection(), SWGSDRangel::SWGSDRPlaySettings::setLnaOn(), SWGSDRangel::SWGSDRPlaySettings::setLog2Decim(), SWGSDRangel::SWGSDRPlaySettings::setLOppmTenths(), SWGSDRangel::SWGSDRPlaySettings::setMixerAmpOn(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGDeviceSettings::setSdrPlaySettings(), SWGSDRangel::SWGSDRPlaySettings::setTunerGain(), and SWGSDRangel::SWGSDRPlaySettings::setTunerGainMode().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("SDRplay1"));
     swgDeviceSettings->setSdrPlaySettings(new SWGSDRangel::SWGSDRPlaySettings());
     SWGSDRangel::SWGSDRPlaySettings *swgSDRPlaySettings = swgDeviceSettings->getSdrPlaySettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgSDRPlaySettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("tunerGain") || force) {
         swgSDRPlaySettings->setTunerGain(settings.m_tunerGain);
     }
     if (deviceSettingsKeys.contains("LOppmTenths") || force) {
         swgSDRPlaySettings->setLOppmTenths(settings.m_LOppmTenths);
     }
     if (deviceSettingsKeys.contains("frequencyBandIndex") || force) {
         swgSDRPlaySettings->setFrequencyBandIndex(settings.m_frequencyBandIndex);
     }
     if (deviceSettingsKeys.contains("ifFrequencyIndex") || force) {
         swgSDRPlaySettings->setIfFrequencyIndex(settings.m_ifFrequencyIndex);
     }
     if (deviceSettingsKeys.contains("bandwidthIndex") || force) {
         swgSDRPlaySettings->setBandwidthIndex(settings.m_bandwidthIndex);
     }
     if (deviceSettingsKeys.contains("devSampleRateIndex") || force) {
         swgSDRPlaySettings->setDevSampleRateIndex(settings.m_devSampleRateIndex);
     }
     if (deviceSettingsKeys.contains("log2Decim") || force) {
         swgSDRPlaySettings->setLog2Decim(settings.m_log2Decim);
     }
     if (deviceSettingsKeys.contains("fcPos") || force) {
         swgSDRPlaySettings->setFcPos((int) settings.m_fcPos);
     }
     if (deviceSettingsKeys.contains("dcBlock") || force) {
         swgSDRPlaySettings->setDcBlock(settings.m_dcBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("iqCorrection") || force) {
         swgSDRPlaySettings->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("tunerGainMode") || force) {
         swgSDRPlaySettings->setTunerGainMode(settings.m_tunerGainMode ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("lnaOn") || force) {
         swgSDRPlaySettings->setLnaOn(settings.m_lnaOn ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("mixerAmpOn") || force) {
         swgSDRPlaySettings->setMixerAmpOn(settings.m_mixerAmpOn ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("basebandGain") || force) {
         swgSDRPlaySettings->setBasebandGain(settings.m_basebandGain);
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgSDRPlaySettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void SDRPlayInput::webapiReverseSendStartStop (bool start) private
Definition at line 928 of file sdrplayinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, SDRPlaySettings::m_reverseAPIAddress, SDRPlaySettings::m_reverseAPIDeviceIndex, SDRPlaySettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("SDRplay1"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int SDRPlayInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 650 of file sdrplayinput.cpp.
References SDRPlayInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int SDRPlayInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 641 of file sdrplayinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int SDRPlayInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 669 of file sdrplayinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getSdrPlaySettings(), SWGSDRangel::SWGSDRPlaySettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setSdrPlaySettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setSdrPlaySettings(new SWGSDRangel::SWGSDRPlaySettings());
     response.getSdrPlaySettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int SDRPlayInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 680 of file sdrplayinput.cpp.
References SDRPlayInput::MsgConfigureSDRPlay::create(), SWGSDRangel::SWGSDRPlaySettings::getBandwidthIndex(), SWGSDRangel::SWGSDRPlaySettings::getBasebandGain(), SWGSDRangel::SWGSDRPlaySettings::getCenterFrequency(), SWGSDRangel::SWGSDRPlaySettings::getDcBlock(), SWGSDRangel::SWGSDRPlaySettings::getDevSampleRateIndex(), SWGSDRangel::SWGSDRPlaySettings::getFcPos(), SWGSDRangel::SWGSDRPlaySettings::getFileRecordName(), SWGSDRangel::SWGSDRPlaySettings::getFrequencyBandIndex(), SWGSDRangel::SWGSDRPlaySettings::getIfFrequencyIndex(), SWGSDRangel::SWGSDRPlaySettings::getIqCorrection(), SWGSDRangel::SWGSDRPlaySettings::getLnaOn(), SWGSDRangel::SWGSDRPlaySettings::getLog2Decim(), SWGSDRangel::SWGSDRPlaySettings::getLOppmTenths(), SWGSDRangel::SWGSDRPlaySettings::getMixerAmpOn(), SWGSDRangel::SWGSDRPlaySettings::getReverseApiAddress(), SWGSDRangel::SWGSDRPlaySettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGSDRPlaySettings::getReverseApiPort(), SWGSDRangel::SWGDeviceSettings::getSdrPlaySettings(), SWGSDRangel::SWGSDRPlaySettings::getTunerGain(), SWGSDRangel::SWGSDRPlaySettings::getTunerGainMode(), SWGSDRangel::SWGSDRPlaySettings::getUseReverseApi(), SDRPlaySettings::m_bandwidthIndex, SDRPlaySettings::m_basebandGain, SDRPlaySettings::m_centerFrequency, SDRPlaySettings::m_dcBlock, SDRPlaySettings::m_devSampleRateIndex, SDRPlaySettings::m_fcPos, SDRPlaySettings::m_fileRecordName, SDRPlaySettings::m_frequencyBandIndex, DeviceSampleSource::m_guiMessageQueue, SDRPlaySettings::m_ifFrequencyIndex, DeviceSampleSource::m_inputMessageQueue, SDRPlaySettings::m_iqCorrection, SDRPlaySettings::m_lnaOn, SDRPlaySettings::m_log2Decim, SDRPlaySettings::m_LOppmTenths, SDRPlaySettings::m_mixerAmpOn, SDRPlaySettings::m_reverseAPIAddress, SDRPlaySettings::m_reverseAPIDeviceIndex, SDRPlaySettings::m_reverseAPIPort, m_settings, SDRPlaySettings::m_tunerGain, SDRPlaySettings::m_tunerGainMode, SDRPlaySettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     SDRPlaySettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getSdrPlaySettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("tunerGain")) {
         settings.m_tunerGain = response.getSdrPlaySettings()->getTunerGain();
     }
     if (deviceSettingsKeys.contains("LOppmTenths")) {
         settings.m_LOppmTenths = response.getSdrPlaySettings()->getLOppmTenths();
     }
     if (deviceSettingsKeys.contains("frequencyBandIndex")) {
         settings.m_frequencyBandIndex = response.getSdrPlaySettings()->getFrequencyBandIndex();
     }
     if (deviceSettingsKeys.contains("ifFrequencyIndex")) {
         settings.m_ifFrequencyIndex = response.getSdrPlaySettings()->getIfFrequencyIndex();
     }
     if (deviceSettingsKeys.contains("bandwidthIndex")) {
         settings.m_bandwidthIndex = response.getSdrPlaySettings()->getBandwidthIndex();
     }
     if (deviceSettingsKeys.contains("devSampleRateIndex")) {
         settings.m_devSampleRateIndex = response.getSdrPlaySettings()->getDevSampleRateIndex();
     }
     if (deviceSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getSdrPlaySettings()->getLog2Decim();
     }
     if (deviceSettingsKeys.contains("fcPos"))
     {
         int fcPos = response.getSdrPlaySettings()->getFcPos();
         fcPos = fcPos < 0 ? 0 : fcPos > 2 ? 2 : fcPos;
         settings.m_fcPos = (SDRPlaySettings::fcPos_t) fcPos;
     }
     if (deviceSettingsKeys.contains("dcBlock")) {
         settings.m_dcBlock = response.getSdrPlaySettings()->getDcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("iqCorrection")) {
         settings.m_iqCorrection = response.getSdrPlaySettings()->getIqCorrection() != 0;
     }
     if (deviceSettingsKeys.contains("tunerGainMode")) {
         settings.m_tunerGainMode = response.getSdrPlaySettings()->getTunerGainMode() != 0;
     }
     if (deviceSettingsKeys.contains("lnaOn")) {
         settings.m_lnaOn = response.getSdrPlaySettings()->getLnaOn() != 0;
     }
     if (deviceSettingsKeys.contains("mixerAmpOn")) {
         settings.m_mixerAmpOn = response.getSdrPlaySettings()->getMixerAmpOn() != 0;
     }
     if (deviceSettingsKeys.contains("basebandGain")) {
         settings.m_basebandGain = response.getSdrPlaySettings()->getBasebandGain();
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getSdrPlaySettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getSdrPlaySettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getSdrPlaySettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getSdrPlaySettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getSdrPlaySettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureSDRPlay *msg = MsgConfigureSDRPlay::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureSDRPlay *msgToGUI = MsgConfigureSDRPlay::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_dev
mirisdr_dev_t* SDRPlayInput::m_dev private
Definition at line 188 of file sdrplayinput.h.
Referenced by applySettings(), closeDevice(), handleMessage(), openDevice(), setDeviceCenterFrequency(), and start().
m_deviceAPI
DeviceAPI* SDRPlayInput::m_deviceAPI private
Definition at line 184 of file sdrplayinput.h.
Referenced by applySettings(), handleMessage(), openDevice(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~SDRPlayInput().
m_deviceDescription
QString SDRPlayInput::m_deviceDescription private
Definition at line 190 of file sdrplayinput.h.
Referenced by closeDevice(), getDeviceDescription(), and openDevice().
m_devNumber
int SDRPlayInput::m_devNumber private
Definition at line 191 of file sdrplayinput.h.
Referenced by openDevice().
m_fileSink
FileRecord* SDRPlayInput::m_fileSink private
File sink to record device I/Q output.
Definition at line 193 of file sdrplayinput.h.
Referenced by applySettings(), handleMessage(), and ~SDRPlayInput().
m_mutex
QMutex SDRPlayInput::m_mutex private
Definition at line 185 of file sdrplayinput.h.
Referenced by applySettings().
m_networkManager
QNetworkAccessManager* SDRPlayInput::m_networkManager private
Definition at line 194 of file sdrplayinput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~SDRPlayInput().
m_networkRequest
QNetworkRequest SDRPlayInput::m_networkRequest private
Definition at line 195 of file sdrplayinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool SDRPlayInput::m_running private
Definition at line 192 of file sdrplayinput.h.
Referenced by start(), stop(), and ~SDRPlayInput().
m_sdrPlayThread
SDRPlayThread* SDRPlayInput::m_sdrPlayThread private
Definition at line 189 of file sdrplayinput.h.
Referenced by applySettings(), start(), and stop().
m_settings
SDRPlaySettings SDRPlayInput::m_settings private
Definition at line 187 of file sdrplayinput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), serialize(), setCenterFrequency(), setDeviceCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_variant
SDRPlayVariant SDRPlayInput::m_variant private
Definition at line 186 of file sdrplayinput.h.
Referenced by getVariant(), and openDevice().
The documentation for this class was generated from the following files:
plugins/samplesource/sdrplay/sdrplayinput.h
plugins/samplesource/sdrplay/sdrplayinput.cpp