SDRAngel: ButtonSwitch Class Reference
ButtonSwitch Class Reference
#include <buttonswitch.h>
Inherits QToolButton.
Public Member Functions
ButtonSwitch (QWidget *parent=NULL)
void doToggle (bool checked)
Private Slots
void onToggled (bool checked)
Private Attributes
QPalette m_originalPalette
Detailed Description
Definition at line 8 of file buttonswitch.h.
Constructor & Destructor Documentation
ButtonSwitch()
ButtonSwitch::ButtonSwitch (QWidget * parent = NULL)
Definition at line 4 of file buttonswitch.cpp.
References m_originalPalette, and onToggled().
                                           :
     QToolButton(parent)
 {
     setCheckable(true);
     m_originalPalette = palette();
     connect(this, SIGNAL(toggled(bool)), this, SLOT(onToggled(bool)));
 }
Member Function Documentation
doToggle()
void ButtonSwitch::doToggle (bool checked)
Definition at line 23 of file buttonswitch.cpp.
References onToggled().
 {
     onToggled(checked);
 }
onToggled
void ButtonSwitch::onToggled (bool checked) private slot
Definition at line 12 of file buttonswitch.cpp.
References m_originalPalette.
Referenced by ButtonSwitch(), and doToggle().
 {
     if(checked) {
         QPalette p = m_originalPalette;
         p.setColor(QPalette::Button, QColor(0x80, 0x46, 0x00));
         setPalette(p);
     } else {
         setPalette(m_originalPalette);
     }
 }
Member Data Documentation
m_originalPalette
QPalette ButtonSwitch::m_originalPalette private
Definition at line 19 of file buttonswitch.h.
Referenced by ButtonSwitch(), and onToggled().
The documentation for this class was generated from the following files:
sdrgui/gui/buttonswitch.h
sdrgui/gui/buttonswitch.cpp