SDRAngel: FileSource Class Reference
FileSource Class Reference
#include <filesource.h>
Classes
struct MagSqLevelsStore
class MsgConfigureChannelizer
class MsgConfigureFileSource
class MsgConfigureFileSourceName
class MsgConfigureFileSourceSeek
class MsgConfigureFileSourceStreamTiming
class MsgConfigureFileSourceWork
class MsgPlayPause
class MsgReportFileSourceAcquisition
class MsgReportFileSourceStreamData
class MsgReportFileSourceStreamTiming
class MsgReportHeaderCRC
class MsgSampleRateNotification
Public Member Functions
FileSource (DeviceAPI *deviceAPI)
~FileSource ()
virtual void destroy ()
virtual void pull (Sample &sample)
virtual void pullAudio (int nbSamples)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
void setCenterFrequency (uint64_t centerFrequency)
void setSampleRate (uint32_t sampleRate)
quint64 getSamplesCount () const
double getMagSq () const
void getMagSqLevels (double &avg, double &peak, int &nbSamples)
Public Member Functions inherited from BasebandSampleSource
BasebandSampleSource ()
virtual ~BasebandSampleSource ()
void feed (SampleSourceFifo *sampleFifo, int nbSamples)
SampleSourceFifo & getSampleSourceFifo ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
void setDeviceSampleSourceFifo (SampleSourceFifo *deviceSampleFifo)
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channeltx.filesource"
static const QString m_channelId ="FileSource"
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void openFileStream ()
void seekFileStream (int seekMillis)
void handleEOF ()
void applySettings (const FileSourceSettings &settings, bool force=false)
void validateFilterChainHash (FileSourceSettings &settings)
void calculateFrequencyOffset ()
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const FileSourceSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const FileSourceSettings &settings, bool force)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
ThreadedBasebandSampleSource * m_threadedChannelizer
UpChannelizer * m_channelizer
FileSourceSettings m_settings
std::ifstream m_ifstream
QString m_fileName
quint32 m_sampleSize
quint64 m_centerFrequency
int64_t m_frequencyOffset
uint32_t m_fileSampleRate
quint64 m_samplesCount
uint32_t m_sampleRate
uint32_t m_deviceSampleRate
quint64 m_recordLength
record length in seconds computed from file size
quint64 m_startingTimeStamp
QTimer m_masterTimer
bool m_running
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
double m_linearGain
double m_magsq
double m_magsqSum
double m_magsqPeak
int m_magsqCount
MagSqLevelsStore m_magSqLevelStore
MovingAverageUtil< Real, double, 16 > m_movingAverage
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSource
void handleInputMessages ()
void handleWriteToFifo (int nbSamples)
void handleWriteToDeviceFifo (int nbSamples)
Protected Member Functions inherited from BasebandSampleSource
void handleWriteToFifo (SampleSourceFifo *sampleFifo, int nbSamples)
Protected Attributes inherited from BasebandSampleSource
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
SampleSourceFifo m_sampleFifo
Internal FIFO for multi-channel processing.
SampleSourceFifo * m_deviceSampleFifo
Reference to the device FIFO for single channel processing.
Detailed Description
Definition at line 44 of file filesource.h.
Constructor & Destructor Documentation
FileSource()
FileSource::FileSource (DeviceAPI * deviceAPI)
Definition at line 62 of file filesource.cpp.
References DeviceAPI::addChannelSource(), DeviceAPI::addChannelSourceAPI(), m_channelId, m_channelizer, m_deviceAPI, m_linearGain, m_magsq, m_magsqCount, m_magsqPeak, m_magsqSum, m_networkManager, m_threadedChannelizer, and networkManagerFinished().
Referenced by FileSource::MsgReportHeaderCRC::MsgReportHeaderCRC().
                                            :
     ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSource),
     m_deviceAPI(deviceAPI),
     m_fileName("..."),
     m_sampleSize(0),
     m_centerFrequency(0),
     m_frequencyOffset(0),
     m_fileSampleRate(0),
     m_samplesCount(0),
     m_sampleRate(0),
     m_deviceSampleRate(0),
     m_recordLength(0),
     m_startingTimeStamp(0),
     m_running(false)
 {
     setObjectName(m_channelId);
     m_channelizer = new UpChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSource(m_channelizer, this);
     m_deviceAPI->addChannelSource(m_threadedChannelizer);
     m_deviceAPI->addChannelSourceAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     m_linearGain = 1.0f;
     m_magsq = 0.0f;
     m_magsqSum = 0.0f;
     m_magsqPeak = 0.0f;
     m_magsqCount = 0;
 }
~FileSource()
FileSource::~FileSource ()
Definition at line 94 of file filesource.cpp.
References m_channelizer, m_deviceAPI, m_networkManager, m_threadedChannelizer, networkManagerFinished(), DeviceAPI::removeChannelSource(), and DeviceAPI::removeChannelSourceAPI().
Referenced by FileSource::MsgReportHeaderCRC::MsgReportHeaderCRC().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     m_deviceAPI->removeChannelSourceAPI(this);
     m_deviceAPI->removeChannelSource(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
 }
Member Function Documentation
applySettings()
void FileSource::applySettings (const FileSourceSettings & settings, bool force = false) private
Definition at line 465 of file filesource.cpp.
References FileSourceSettings::m_fileName, FileSourceSettings::m_gainDB, m_linearGain, FileSourceSettings::m_loop, FileSourceSettings::m_reverseAPIAddress, FileSourceSettings::m_reverseAPIChannelIndex, FileSourceSettings::m_reverseAPIDeviceIndex, FileSourceSettings::m_reverseAPIPort, m_settings, FileSourceSettings::m_useReverseAPI, CalcDb::powerFromdB(), and webapiReverseSendSettings().
Referenced by handleMessage().
 {
     qDebug() << "FileSource::applySettings:"
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if ((m_settings.m_loop != settings.m_loop) || force) {
         reverseAPIKeys.append("loop");
     }
     if ((m_settings.m_fileName != settings.m_fileName) || force) {
         reverseAPIKeys.append("fileName");
     }
     if ((m_settings.m_gainDB != settings.m_gainDB) || force)
     {
         m_linearGain = CalcDb::powerFromdB(settings.m_gainDB);
         reverseAPIKeys.append("gainDB");
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
calculateFrequencyOffset()
void FileSource::calculateFrequencyOffset () private
Definition at line 509 of file filesource.cpp.
References HBFilterChainConverter::getShiftFactor(), m_deviceSampleRate, FileSourceSettings::m_filterChainHash, m_frequencyOffset, FileSourceSettings::m_log2Interp, and m_settings.
Referenced by handleMessage().
 {
     double shiftFactor = HBFilterChainConverter::getShiftFactor(m_settings.m_log2Interp, m_settings.m_filterChainHash);
     m_frequencyOffset = m_deviceSampleRate * shiftFactor;
 }
deserialize()
bool FileSource::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 337 of file filesource.cpp.
References FileSource::MsgConfigureFileSource::create(), FileSourceSettings::deserialize(), BasebandSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and FileSourceSettings::resetToDefaults().
Referenced by getStreamCenterFrequency().
 {
     (void) data;
     if (m_settings.deserialize(data))
     {
         MsgConfigureFileSource *msg = MsgConfigureFileSource::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureFileSource *msg = MsgConfigureFileSource::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void FileSource::destroy () inline virtual
Implements ChannelAPI.
Definition at line 311 of file filesource.h.
References handleMessage(), pull(), pullAudio(), start(), and stop().
 { delete this; }
getCenterFrequency()
virtual qint64 FileSource::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 321 of file filesource.h.
 { return 0; }
getIdentifier()
virtual void FileSource::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 319 of file filesource.h.
 { id = objectName(); }
getMagSq()
double FileSource::getMagSq () const inline
Definition at line 357 of file filesource.h.
References m_magsq.
Referenced by webapiFormatChannelReport().
 { return m_magsq; }
getMagSqLevels()
void FileSource::getMagSqLevels (double & avg, double & peak, int & nbSamples) inline
Definition at line 359 of file filesource.h.
References FileSource::MagSqLevelsStore::m_magsq, m_magsq, m_magsqCount, m_magSqLevelStore, FileSource::MagSqLevelsStore::m_magsqPeak, m_magsqPeak, and m_magsqSum.
Referenced by FileSourceGUI::tick().
     {
         if (m_magsqCount > 0)
         {
             m_magsq = m_magsqSum / m_magsqCount;
             m_magSqLevelStore.m_magsq = m_magsq;
             m_magSqLevelStore.m_magsqPeak = m_magsqPeak;
         }
         avg = m_magSqLevelStore.m_magsq;
         peak = m_magSqLevelStore.m_magsqPeak;
         nbSamples = m_magsqCount == 0 ? 1 : m_magsqCount;
         m_magsqSum = 0.0f;
         m_magsqPeak = 0.0f;
         m_magsqCount = 0;
     }
getNbSinkStreams()
virtual int FileSource::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 323 of file filesource.h.
 { return 0; }
getNbSourceStreams()
virtual int FileSource::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 324 of file filesource.h.
 { return 1; }
getSamplesCount()
quint64 FileSource::getSamplesCount () const inline
Definition at line 356 of file filesource.h.
References m_samplesCount.
Referenced by handleEOF(), handleMessage(), and webapiFormatChannelReport().
 { return m_samplesCount; }
getStreamCenterFrequency()
virtual qint64 FileSource::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 326 of file filesource.h.
References deserialize(), serialize(), webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return 0;
     }
getTitle()
virtual void FileSource::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 320 of file filesource.h.
References m_settings, and FileSourceSettings::m_title.
 { title = m_settings.m_title; }
handleEOF()
void FileSource::handleEOF () private
Definition at line 439 of file filesource.cpp.
References FileSource::MsgPlayPause::create(), FileSource::MsgReportFileSourceStreamTiming::create(), BasebandSampleSource::getMessageQueueToGUI(), getSamplesCount(), FileSourceSettings::m_loop, m_settings, MessageQueue::push(), seekFileStream(), start(), and stop().
Referenced by pull().
 {
     if (getMessageQueueToGUI())
     {
         MsgReportFileSourceStreamTiming *report = MsgReportFileSourceStreamTiming::create(getSamplesCount());
         getMessageQueueToGUI()->push(report);
     }
     if (m_settings.m_loop)
     {
         stop();
         seekFileStream(0);
         start();
     }
     else
     {
         stop();
         if (getMessageQueueToGUI())
         {
             MsgPlayPause *report = MsgPlayPause::create(false);
             getMessageQueueToGUI()->push(report);
         }
     }
 }
handleMessage()
bool FileSource::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSource.
Definition at line 220 of file filesource.cpp.
References applySettings(), calculateFrequencyOffset(), FileSource::MsgSampleRateNotification::create(), FileSource::MsgReportFileSourceStreamTiming::create(), DSPSignalNotification::getCenterFrequency(), FileSource::MsgConfigureFileSourceName::getFileName(), FileSource::MsgConfigureChannelizer::getFilterChainHash(), FileSource::MsgConfigureFileSource::getForce(), UpChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSource::getInputMessageQueue(), FileSource::MsgConfigureChannelizer::getLog2Interp(), BasebandSampleSource::getMessageQueueToGUI(), FileSource::MsgConfigureFileSourceSeek::getMillis(), UpChannelizer::MsgChannelizerNotification::getSampleRate(), DSPSignalNotification::getSampleRate(), getSamplesCount(), FileSource::MsgConfigureFileSource::getSettings(), FileSource::MsgConfigureFileSourceWork::isWorking(), m_channelizer, m_deviceSampleRate, m_fileName, FileSourceSettings::m_filterChainHash, BasebandSampleSource::m_guiMessageQueue, FileSourceSettings::m_log2Interp, m_settings, Message::match(), openFileStream(), MessageQueue::push(), seekFileStream(), UpChannelizer::set(), setCenterFrequency(), setSampleRate(), start(), and stop().
Referenced by destroy().
 {
     if (UpChannelizer::MsgChannelizerNotification::match(cmd))
     {
         UpChannelizer::MsgChannelizerNotification& notif = (UpChannelizer::MsgChannelizerNotification&) cmd;
         int sampleRate = notif.getSampleRate();
         qDebug() << "FileSource::handleMessage: MsgChannelizerNotification:"
                 << " channelSampleRate: " << sampleRate
                 << " offsetFrequency: " << notif.getFrequencyOffset();
         if (sampleRate > 0) {
             setSampleRate(sampleRate);
         }
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         DSPSignalNotification& notif = (DSPSignalNotification&) cmd;
         qDebug() << "FileSource::handleMessage: DSPSignalNotification:"
                 << " inputSampleRate: " << notif.getSampleRate()
                 << " centerFrequency: " << notif.getCenterFrequency();
         setCenterFrequency(notif.getCenterFrequency());
         m_deviceSampleRate = notif.getSampleRate();
         calculateFrequencyOffset(); // This is when device sample rate changes
         // Redo the channelizer stuff with the new sample rate to re-synchronize everything
         m_channelizer->set(m_channelizer->getInputMessageQueue(),
             m_settings.m_log2Interp,
             m_settings.m_filterChainHash);
         if (m_guiMessageQueue)
         {
             MsgSampleRateNotification *msg = MsgSampleRateNotification::create(notif.getSampleRate());
             m_guiMessageQueue->push(msg);
         }
         return true;
     }
     else if (MsgConfigureFileSource::match(cmd))
     {
         MsgConfigureFileSource& cfg = (MsgConfigureFileSource&) cmd;
         qDebug() << "FileSource::handleMessage: MsgConfigureFileSource";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         m_settings.m_log2Interp = cfg.getLog2Interp();
         m_settings.m_filterChainHash =  cfg.getFilterChainHash();
         qDebug() << "FileSource::handleMessage: MsgConfigureChannelizer:"
                 << " log2Interp: " << m_settings.m_log2Interp
                 << " filterChainHash: " << m_settings.m_filterChainHash;
         m_channelizer->set(m_channelizer->getInputMessageQueue(),
             m_settings.m_log2Interp,
             m_settings.m_filterChainHash);
         calculateFrequencyOffset(); // This is when decimation or filter chain changes
         return true;
     }
     else if (MsgConfigureFileSourceName::match(cmd))
     {
         MsgConfigureFileSourceName& conf = (MsgConfigureFileSourceName&) cmd;
         m_fileName = conf.getFileName();
         openFileStream();
         return true;
     }
     else if (MsgConfigureFileSourceWork::match(cmd))
     {
         MsgConfigureFileSourceWork& conf = (MsgConfigureFileSourceWork&) cmd;
         if (conf.isWorking()) {
             start();
         } else {
             stop();
         }
         return true;
     }
     else if (MsgConfigureFileSourceSeek::match(cmd))
     {
         MsgConfigureFileSourceSeek& conf = (MsgConfigureFileSourceSeek&) cmd;
         int seekMillis = conf.getMillis();
         seekFileStream(seekMillis);
         return true;
     }
     else if (MsgConfigureFileSourceStreamTiming::match(cmd))
     {
         MsgReportFileSourceStreamTiming *report;
         if (getMessageQueueToGUI())
         {
             report = MsgReportFileSourceStreamTiming::create(getSamplesCount());
             getMessageQueueToGUI()->push(report);
         }
         return true;
     }
     else
     {
         return false;
     }
 }
networkManagerFinished
void FileSource::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 703 of file filesource.cpp.
Referenced by FileSource(), and ~FileSource().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "FileSource::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("FileSource::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openFileStream()
void FileSource::openFileStream () private
Definition at line 355 of file filesource.cpp.
References FileRecord::Header::centerFrequency, FileRecord::Header::crc32, FileSource::MsgReportFileSourceStreamData::create(), FileSource::MsgReportHeaderCRC::create(), BasebandSampleSource::getMessageQueueToGUI(), m_centerFrequency, m_fileName, m_fileSampleRate, m_ifstream, m_recordLength, m_samplesCount, m_sampleSize, m_startingTimeStamp, MessageQueue::push(), FileRecord::readHeader(), FileRecord::Header::sampleRate, FileRecord::Header::sampleSize, and FileRecord::Header::startTimeStamp.
Referenced by handleMessage().
 {
     //stop();
     if (m_ifstream.is_open()) {
         m_ifstream.close();
     }
 #ifdef Q_OS_WIN
     m_ifstream.open(m_fileName.toStdWString().c_str(), std::ios::binary | std::ios::ate);
 #else
     m_ifstream.open(m_fileName.toStdString().c_str(), std::ios::binary | std::ios::ate);
 #endif
     quint64 fileSize = m_ifstream.tellg();
     m_samplesCount = 0;
     if (fileSize > sizeof(FileRecord::Header))
     {
         FileRecord::Header header;
         m_ifstream.seekg(0,std::ios_base::beg);
         bool crcOK = FileRecord::readHeader(m_ifstream, header);
         m_fileSampleRate = header.sampleRate;
         m_centerFrequency = header.centerFrequency;
         m_startingTimeStamp = header.startTimeStamp;
         m_sampleSize = header.sampleSize;
         QString crcHex = QString("%1").arg(header.crc32 , 0, 16);
         if (crcOK)
         {
             qDebug("FileSource::openFileStream: CRC32 OK for header: %s", qPrintable(crcHex));
             m_recordLength = (fileSize - sizeof(FileRecord::Header)) / ((m_sampleSize == 24 ? 8 : 4) * m_fileSampleRate);
         }
         else
         {
             qCritical("FileSource::openFileStream: bad CRC32 for header: %s", qPrintable(crcHex));
             m_recordLength = 0;
         }
         if (getMessageQueueToGUI()) {
             MsgReportHeaderCRC *report = MsgReportHeaderCRC::create(crcOK);
             getMessageQueueToGUI()->push(report);
         }
     }
     else
     {
         m_recordLength = 0;
     }
     qDebug() << "FileSource::openFileStream: " << m_fileName.toStdString().c_str()
             << " fileSize: " << fileSize << " bytes"
             << " length: " << m_recordLength << " seconds"
             << " sample rate: " << m_fileSampleRate << " S/s"
             << " center frequency: " << m_centerFrequency << " Hz"
             << " sample size: " << m_sampleSize << " bits"
             << " starting TS: " << m_startingTimeStamp << "s";
     if (getMessageQueueToGUI()) {
         MsgReportFileSourceStreamData *report = MsgReportFileSourceStreamData::create(m_fileSampleRate,
                 m_sampleSize,
                 m_centerFrequency,
                 m_startingTimeStamp,
                 m_recordLength); // file stream data
         getMessageQueueToGUI()->push(report);
     }
     if (m_recordLength == 0) {
         m_ifstream.close();
     }
 }
pull()
void FileSource::pull (Sample & sample) virtual
Implements BasebandSampleSource.
Definition at line 104 of file filesource.cpp.
References MovingAverageUtil< T, Total, N >::asDouble(), handleEOF(), m_ifstream, m_linearGain, m_magsq, m_magsqCount, m_magsqPeak, m_magsqSum, m_movingAverage, m_running, m_samplesCount, m_sampleSize, SDR_TX_SAMP_SZ, Sample::setImag(), and Sample::setReal().
Referenced by destroy().
 {
     Real re;
     Real im;
     struct Sample16
     {
         int16_t real;
         int16_t imag;
     };
     struct Sample24
     {
         int32_t real;
         int32_t imag;
     };
     if (!m_running)
     {
         re = 0;
         im = 0;
     }
     else if (m_sampleSize == 16)
     {
         Sample16 sample16;
         m_ifstream.read(reinterpret_cast<char*>(&sample16), sizeof(Sample16));
         if (m_ifstream.eof()) {
             handleEOF();
         } else {
             m_samplesCount++;
         }
         // scale to +/-1.0
         re = (sample16.real * m_linearGain) / 32760.0f;
         im = (sample16.imag * m_linearGain) / 32760.0f;
     }
     else if (m_sampleSize == 24)
     {
         Sample24 sample24;
         m_ifstream.read(reinterpret_cast<char*>(&sample24), sizeof(Sample24));
         if (m_ifstream.eof()) {
             handleEOF();
         } else {
             m_samplesCount++;
         }
         // scale to +/-1.0
         re = (sample24.real * m_linearGain) / 8388608.0f;
         im = (sample24.imag * m_linearGain) / 8388608.0f;
     }
     else
     {
         re = 0;
         im = 0;
     }
     if (SDR_TX_SAMP_SZ == 16)
     {
         sample.setReal(re * 32768.0f);
         sample.setImag(im * 32768.0f);
     }
     else if (SDR_TX_SAMP_SZ == 24)
     {
         sample.setReal(re * 8388608.0f);
         sample.setImag(im * 8388608.0f);
     }
     else
     {
         sample.setReal(0);
         sample.setImag(0);
     }
     Real magsq = re*re + im*im;
     m_movingAverage(magsq);
     m_magsq = m_movingAverage.asDouble();
     m_magsqSum += magsq;
     if (magsq > m_magsqPeak) {
         m_magsqPeak = magsq;
     }
     m_magsqCount++;
 }
pullAudio()
void FileSource::pullAudio (int nbSamples) virtual
Reimplemented from BasebandSampleSource.
Definition at line 191 of file filesource.cpp.
Referenced by destroy().
 {
     (void) nbSamples;
 }
seekFileStream()
void FileSource::seekFileStream (int seekMillis) private
Definition at line 425 of file filesource.cpp.
References m_fileSampleRate, m_ifstream, m_mutex, m_recordLength, m_running, m_samplesCount, and m_sampleSize.
Referenced by handleEOF(), and handleMessage().
 {
     QMutexLocker mutexLocker(&m_mutex);
     if ((m_ifstream.is_open()) && !m_running)
     {
         quint64 seekPoint = ((m_recordLength * seekMillis) / 1000) * m_fileSampleRate;
         m_samplesCount = seekPoint;
         seekPoint *= (m_sampleSize == 24 ? 8 : 4); // + sizeof(FileSink::Header)
         m_ifstream.clear();
         m_ifstream.seekg(seekPoint + sizeof(FileRecord::Header), std::ios::beg);
     }
 }
serialize()
QByteArray FileSource::serialize () const virtual
Implements ChannelAPI.
Definition at line 332 of file filesource.cpp.
References m_settings, and FileSourceSettings::serialize().
Referenced by getStreamCenterFrequency().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void FileSource::setCenterFrequency (uint64_t centerFrequency) inline
Set center frequency given in Hz
Definition at line 351 of file filesource.h.
References m_centerFrequency.
Referenced by handleMessage().
 { m_centerFrequency = centerFrequency; }
setSampleRate()
void FileSource::setSampleRate (uint32_t sampleRate) inline
Set sample rate given in Hz
Definition at line 354 of file filesource.h.
References m_sampleRate.
Referenced by handleMessage().
 { m_sampleRate = sampleRate; }
start()
void FileSource::start () virtual
Implements BasebandSampleSource.
Definition at line 196 of file filesource.cpp.
References FileSource::MsgReportFileSourceAcquisition::create(), BasebandSampleSource::getMessageQueueToGUI(), m_running, and MessageQueue::push().
Referenced by destroy(), handleEOF(), and handleMessage().
 {
     qDebug("FileSource::start");
     m_running = true;
     if (getMessageQueueToGUI())
     {
         MsgReportFileSourceAcquisition *report = MsgReportFileSourceAcquisition::create(true); // acquisition on
         getMessageQueueToGUI()->push(report);
     }
 }
stop()
void FileSource::stop () virtual
Implements BasebandSampleSource.
Definition at line 208 of file filesource.cpp.
References FileSource::MsgReportFileSourceAcquisition::create(), BasebandSampleSource::getMessageQueueToGUI(), m_running, and MessageQueue::push().
Referenced by destroy(), handleEOF(), and handleMessage().
 {
     qDebug("FileSource::stop");
     m_running = false;
     if (getMessageQueueToGUI())
     {
         MsgReportFileSourceAcquisition *report = MsgReportFileSourceAcquisition::create(false); // acquisition off
         getMessageQueueToGUI()->push(report);
     }
 }
validateFilterChainHash()
void FileSource::validateFilterChainHash (FileSourceSettings & settings) private
Definition at line 498 of file filesource.cpp.
References i, FileSourceSettings::m_filterChainHash, and FileSourceSettings::m_log2Interp.
Referenced by webapiSettingsPutPatch().
 {
     unsigned int s = 1;
     for (unsigned int i = 0; i < settings.m_log2Interp; i++) {
         s *= 3;
     }
     settings.m_filterChainHash = settings.m_filterChainHash >= s ? s-1 : settings.m_filterChainHash;
 }
webapiFormatChannelReport()
void FileSource::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 622 of file filesource.cpp.
References CalcDb::dbPower(), SWGSDRangel::SWGChannelReport::getFileSourceReport(), getMagSq(), getSamplesCount(), FileSourceSettings::m_fileName, m_fileSampleRate, m_recordLength, m_sampleRate, m_sampleSize, m_settings, m_startingTimeStamp, SWGSDRangel::SWGFileSourceReport::setAbsoluteTime(), SWGSDRangel::SWGFileSourceReport::setChannelPowerDb(), SWGSDRangel::SWGFileSourceReport::setDurationTime(), SWGSDRangel::SWGFileSourceReport::setElapsedTime(), SWGSDRangel::SWGFileSourceReport::setFileName(), SWGSDRangel::SWGFileSourceReport::setFileSampleRate(), SWGSDRangel::SWGFileSourceReport::setFileSampleSize(), and SWGSDRangel::SWGFileSourceReport::setSampleRate().
Referenced by webapiReportGet().
 {
     qint64 t_sec = 0;
     qint64 t_msec = 0;
     quint64 samplesCount = getSamplesCount();
     if (m_fileSampleRate > 0)
     {
         t_sec = samplesCount / m_fileSampleRate;
         t_msec = (samplesCount - (t_sec * m_fileSampleRate)) * 1000 / m_fileSampleRate;
     }
     QTime t(0, 0, 0, 0);
     t = t.addSecs(t_sec);
     t = t.addMSecs(t_msec);
     response.getFileSourceReport()->setElapsedTime(new QString(t.toString("HH:mm:ss.zzz")));
     qint64 startingTimeStampMsec = m_startingTimeStamp * 1000LL;
     QDateTime dt = QDateTime::fromMSecsSinceEpoch(startingTimeStampMsec);
     dt = dt.addSecs(t_sec);
     dt = dt.addMSecs(t_msec);
     response.getFileSourceReport()->setAbsoluteTime(new QString(dt.toString("yyyy-MM-dd HH:mm:ss.zzz")));
     QTime recordLength(0, 0, 0, 0);
     recordLength = recordLength.addSecs(m_recordLength);
     response.getFileSourceReport()->setDurationTime(new QString(recordLength.toString("HH:mm:ss")));
     response.getFileSourceReport()->setFileName(new QString(m_settings.m_fileName));
     response.getFileSourceReport()->setFileSampleRate(m_fileSampleRate);
     response.getFileSourceReport()->setFileSampleSize(m_sampleSize);
     response.getFileSourceReport()->setSampleRate(m_sampleRate);
     response.getFileSourceReport()->setChannelPowerDb(CalcDb::dbPower(getMagSq()));
 }
webapiFormatChannelSettings()
void FileSource::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const FileSourceSettings & settings) private
Definition at line 596 of file filesource.cpp.
References SWGSDRangel::SWGChannelSettings::getFileSourceSettings(), SWGSDRangel::SWGFileSourceSettings::getReverseApiAddress(), SWGSDRangel::SWGFileSourceSettings::getTitle(), FileSourceSettings::m_filterChainHash, FileSourceSettings::m_gainDB, FileSourceSettings::m_log2Interp, FileSourceSettings::m_reverseAPIAddress, FileSourceSettings::m_reverseAPIChannelIndex, FileSourceSettings::m_reverseAPIDeviceIndex, FileSourceSettings::m_reverseAPIPort, FileSourceSettings::m_rgbColor, FileSourceSettings::m_title, FileSourceSettings::m_useReverseAPI, SWGSDRangel::SWGFileSourceSettings::setFilterChainHash(), SWGSDRangel::SWGFileSourceSettings::setGainDb(), SWGSDRangel::SWGFileSourceSettings::setLog2Interp(), SWGSDRangel::SWGFileSourceSettings::setReverseApiAddress(), SWGSDRangel::SWGFileSourceSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGFileSourceSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGFileSourceSettings::setReverseApiPort(), SWGSDRangel::SWGFileSourceSettings::setRgbColor(), SWGSDRangel::SWGFileSourceSettings::setTitle(), and SWGSDRangel::SWGFileSourceSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getFileSourceSettings()->setLog2Interp(settings.m_log2Interp);
     response.getFileSourceSettings()->setFilterChainHash(settings.m_filterChainHash);
     response.getFileSourceSettings()->setGainDb(settings.m_gainDB);
     response.getFileSourceSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getFileSourceSettings()->getTitle()) {
         *response.getFileSourceSettings()->getTitle() = settings.m_title;
     } else {
         response.getFileSourceSettings()->setTitle(new QString(settings.m_title));
     }
     response.getFileSourceSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getFileSourceSettings()->getReverseApiAddress()) {
         *response.getFileSourceSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getFileSourceSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getFileSourceSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getFileSourceSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getFileSourceSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int FileSource::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 585 of file filesource.cpp.
References SWGSDRangel::SWGChannelReport::getFileSourceReport(), SWGSDRangel::SWGFileSourceReport::init(), SWGSDRangel::SWGChannelReport::setFileSourceReport(), and webapiFormatChannelReport().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setFileSourceReport(new SWGSDRangel::SWGFileSourceReport());
     response.getFileSourceReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendSettings()
void FileSource::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const FileSourceSettings & settings, bool force) private
Definition at line 656 of file filesource.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), ChannelAPI::getDeviceSetIndex(), SWGSDRangel::SWGChannelSettings::getFileSourceSettings(), ChannelAPI::getIndexInDeviceSet(), FileSourceSettings::m_filterChainHash, FileSourceSettings::m_gainDB, FileSourceSettings::m_log2Interp, m_networkManager, m_networkRequest, FileSourceSettings::m_reverseAPIAddress, FileSourceSettings::m_reverseAPIChannelIndex, FileSourceSettings::m_reverseAPIDeviceIndex, FileSourceSettings::m_reverseAPIPort, FileSourceSettings::m_rgbColor, FileSourceSettings::m_title, SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGChannelSettings::setFileSourceSettings(), SWGSDRangel::SWGFileSourceSettings::setFilterChainHash(), SWGSDRangel::SWGFileSourceSettings::setGainDb(), SWGSDRangel::SWGFileSourceSettings::setLog2Interp(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGFileSourceSettings::setRgbColor(), and SWGSDRangel::SWGFileSourceSettings::setTitle().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("FileSource"));
     swgChannelSettings->setFileSourceSettings(new SWGSDRangel::SWGFileSourceSettings());
     SWGSDRangel::SWGFileSourceSettings *swgFileSourceSettings = swgChannelSettings->getFileSourceSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("log2Interp") || force) {
         swgFileSourceSettings->setLog2Interp(settings.m_log2Interp);
     }
     if (channelSettingsKeys.contains("filterChainHash") || force) {
         swgFileSourceSettings->setFilterChainHash(settings.m_filterChainHash);
     }
     if (channelSettingsKeys.contains("gainDB") || force) {
         swgFileSourceSettings->setGainDb(settings.m_gainDB);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgFileSourceSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgFileSourceSettings->setTitle(new QString(settings.m_title));
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int FileSource::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 515 of file filesource.cpp.
References SWGSDRangel::SWGChannelSettings::getFileSourceSettings(), SWGSDRangel::SWGFileSourceSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setFileSourceSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setFileSourceSettings(new SWGSDRangel::SWGFileSourceSettings());
     response.getFileSourceSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int FileSource::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 526 of file filesource.cpp.
References FileSource::MsgConfigureFileSource::create(), SWGSDRangel::SWGChannelSettings::getFileSourceSettings(), SWGSDRangel::SWGFileSourceSettings::getFilterChainHash(), SWGSDRangel::SWGFileSourceSettings::getGainDb(), SWGSDRangel::SWGFileSourceSettings::getLog2Interp(), SWGSDRangel::SWGFileSourceSettings::getReverseApiAddress(), SWGSDRangel::SWGFileSourceSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGFileSourceSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGFileSourceSettings::getReverseApiPort(), SWGSDRangel::SWGFileSourceSettings::getRgbColor(), SWGSDRangel::SWGFileSourceSettings::getTitle(), SWGSDRangel::SWGFileSourceSettings::getUseReverseApi(), FileSourceSettings::m_filterChainHash, FileSourceSettings::m_gainDB, BasebandSampleSource::m_guiMessageQueue, BasebandSampleSource::m_inputMessageQueue, FileSourceSettings::m_log2Interp, FileSourceSettings::m_reverseAPIAddress, FileSourceSettings::m_reverseAPIChannelIndex, FileSourceSettings::m_reverseAPIDeviceIndex, FileSourceSettings::m_reverseAPIPort, FileSourceSettings::m_rgbColor, m_settings, FileSourceSettings::m_title, FileSourceSettings::m_useReverseAPI, MessageQueue::push(), validateFilterChainHash(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     FileSourceSettings settings = m_settings;
     if (channelSettingsKeys.contains("log2Interp")) {
         settings.m_log2Interp = response.getFileSourceSettings()->getLog2Interp();
     }
     if (channelSettingsKeys.contains("filterChainHash"))
     {
         settings.m_filterChainHash = response.getFileSourceSettings()->getFilterChainHash();
         validateFilterChainHash(settings);
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getFileSourceSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getFileSourceSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("gainDB")) {
         settings.m_gainDB = response.getFileSourceSettings()->getGainDb();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getFileSourceSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getFileSourceSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getFileSourceSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getFileSourceSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getFileSourceSettings()->getReverseApiChannelIndex();
     }
     MsgConfigureFileSource *msg = MsgConfigureFileSource::create(settings, force);
     m_inputMessageQueue.push(msg);
     qDebug("FileSource::webapiSettingsPutPatch: forward to GUI: %p", m_guiMessageQueue);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureFileSource *msgToGUI = MsgConfigureFileSource::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_centerFrequency
quint64 FileSource::m_centerFrequency private
Definition at line 399 of file filesource.h.
Referenced by FileSource::MsgReportFileSourceStreamData::getCenterFrequency(), openFileStream(), and setCenterFrequency().
m_channelId
const QString FileSource::m_channelId ="FileSource" static
Definition at line 378 of file filesource.h.
Referenced by FileSource(), and FileSourcePlugin::initPlugin().
m_channelIdURI
const QString FileSource::m_channelIdURI = "sdrangel.channeltx.filesource" static
Definition at line 377 of file filesource.h.
Referenced by FileSourceGUI::FileSourceGUI(), and FileSourcePlugin::initPlugin().
m_channelizer
UpChannelizer* FileSource::m_channelizer private
Definition at line 394 of file filesource.h.
Referenced by FileSource(), handleMessage(), and ~FileSource().
m_deviceAPI
DeviceAPI* FileSource::m_deviceAPI private
Definition at line 391 of file filesource.h.
Referenced by FileSource(), and ~FileSource().
m_deviceSampleRate
uint32_t FileSource::m_deviceSampleRate private
Definition at line 404 of file filesource.h.
Referenced by calculateFrequencyOffset(), and handleMessage().
m_fileName
QString FileSource::m_fileName private
Definition at line 397 of file filesource.h.
Referenced by FileSource::MsgConfigureFileSourceName::getFileName(), handleMessage(), and openFileStream().
m_fileSampleRate
uint32_t FileSource::m_fileSampleRate private
Definition at line 401 of file filesource.h.
Referenced by openFileStream(), seekFileStream(), and webapiFormatChannelReport().
m_frequencyOffset
int64_t FileSource::m_frequencyOffset private
Definition at line 400 of file filesource.h.
Referenced by calculateFrequencyOffset().
m_ifstream
std::ifstream FileSource::m_ifstream private
Definition at line 396 of file filesource.h.
Referenced by openFileStream(), pull(), and seekFileStream().
m_linearGain
double FileSource::m_linearGain private
Definition at line 412 of file filesource.h.
Referenced by applySettings(), FileSource(), and pull().
m_magsq
double FileSource::m_magsq private
Definition at line 413 of file filesource.h.
Referenced by FileSource(), getMagSq(), getMagSqLevels(), and pull().
m_magsqCount
int FileSource::m_magsqCount private
Definition at line 416 of file filesource.h.
Referenced by FileSource(), getMagSqLevels(), and pull().
m_magSqLevelStore
MagSqLevelsStore FileSource::m_magSqLevelStore private
Definition at line 417 of file filesource.h.
Referenced by getMagSqLevels().
m_magsqPeak
double FileSource::m_magsqPeak private
Definition at line 415 of file filesource.h.
Referenced by FileSource(), getMagSqLevels(), and pull().
m_magsqSum
double FileSource::m_magsqSum private
Definition at line 414 of file filesource.h.
Referenced by FileSource(), getMagSqLevels(), and pull().
m_masterTimer
QTimer FileSource::m_masterTimer private
Definition at line 407 of file filesource.h.
m_movingAverage
MovingAverageUtil<Real, double, 16> FileSource::m_movingAverage private
Definition at line 418 of file filesource.h.
Referenced by pull().
m_mutex
QMutex FileSource::m_mutex private
Definition at line 392 of file filesource.h.
Referenced by seekFileStream().
m_networkManager
QNetworkAccessManager* FileSource::m_networkManager private
Definition at line 409 of file filesource.h.
Referenced by FileSource(), webapiReverseSendSettings(), and ~FileSource().
m_networkRequest
QNetworkRequest FileSource::m_networkRequest private
Definition at line 410 of file filesource.h.
Referenced by webapiReverseSendSettings().
m_recordLength
quint64 FileSource::m_recordLength private
record length in seconds computed from file size
Definition at line 405 of file filesource.h.
Referenced by FileSource::MsgReportFileSourceStreamData::getRecordLength(), openFileStream(), seekFileStream(), and webapiFormatChannelReport().
m_running
bool FileSource::m_running private
Definition at line 408 of file filesource.h.
Referenced by pull(), seekFileStream(), start(), and stop().
m_sampleRate
uint32_t FileSource::m_sampleRate private
Definition at line 403 of file filesource.h.
Referenced by FileSource::MsgSampleRateNotification::getSampleRate(), FileSource::MsgReportFileSourceStreamData::getSampleRate(), setSampleRate(), and webapiFormatChannelReport().
m_samplesCount
quint64 FileSource::m_samplesCount private
Definition at line 402 of file filesource.h.
Referenced by FileSource::MsgReportFileSourceStreamTiming::getSamplesCount(), getSamplesCount(), openFileStream(), pull(), and seekFileStream().
m_sampleSize
quint32 FileSource::m_sampleSize private
Definition at line 398 of file filesource.h.
Referenced by FileSource::MsgReportFileSourceStreamData::getSampleSize(), openFileStream(), pull(), seekFileStream(), and webapiFormatChannelReport().
m_settings
FileSourceSettings FileSource::m_settings private
Definition at line 395 of file filesource.h.
Referenced by applySettings(), calculateFrequencyOffset(), deserialize(), FileSource::MsgConfigureFileSource::getSettings(), getTitle(), handleEOF(), handleMessage(), serialize(), webapiFormatChannelReport(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_startingTimeStamp
quint64 FileSource::m_startingTimeStamp private
Definition at line 406 of file filesource.h.
Referenced by FileSource::MsgReportFileSourceStreamData::getStartingTimeStamp(), openFileStream(), and webapiFormatChannelReport().
m_threadedChannelizer
ThreadedBasebandSampleSource* FileSource::m_threadedChannelizer private
Definition at line 393 of file filesource.h.
Referenced by FileSource(), and ~FileSource().
The documentation for this class was generated from the following files:
plugins/channeltx/filesource/filesource.h
plugins/channeltx/filesource/filesource.cpp