SDRAngel: FileSinkSettings Struct Reference
FileSinkSettings Struct Reference
#include <filesinksettings.h>
Public Member Functions
FileSinkSettings ()
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
Public Attributes
quint64 m_centerFrequency
quint64 m_sampleRate
quint32 m_log2Interp
Detailed Description
Definition at line 23 of file filesinksettings.h.
Constructor & Destructor Documentation
FileSinkSettings()
FileSinkSettings::FileSinkSettings ()
Definition at line 21 of file filesinksettings.cpp.
References resetToDefaults().
 {
     resetToDefaults();
 }
Member Function Documentation
deserialize()
bool FileSinkSettings::deserialize (const QByteArray & data)
Definition at line 43 of file filesinksettings.cpp.
References SimpleDeserializer::getVersion(), SimpleDeserializer::isValid(), m_log2Interp, m_sampleRate, SimpleDeserializer::readU32(), SimpleDeserializer::readU64(), and resetToDefaults().
Referenced by FileSinkGui::deserialize(), and FileSinkOutput::deserialize().
 {
     SimpleDeserializer d(data);
     if (!d.isValid())
     {
         resetToDefaults();
         return false;
     }
     if (d.getVersion() == 1)
     {
         d.readU64(1, &m_sampleRate, 48000);
         d.readU32(2, &m_log2Interp, 0);
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
resetToDefaults()
void FileSinkSettings::resetToDefaults ()
Definition at line 26 of file filesinksettings.cpp.
References m_centerFrequency, m_log2Interp, and m_sampleRate.
Referenced by deserialize(), FileSinkOutput::deserialize(), FileSinkSettings(), and FileSinkGui::resetToDefaults().
 {
     m_centerFrequency = 435000*1000;
     m_sampleRate = 48000;
     m_log2Interp = 0;
 }
serialize()
QByteArray FileSinkSettings::serialize () const
Definition at line 33 of file filesinksettings.cpp.
References SimpleSerializer::final(), m_log2Interp, m_sampleRate, SimpleSerializer::writeU32(), and SimpleSerializer::writeU64().
Referenced by FileSinkGui::serialize(), and FileSinkOutput::serialize().
 {
     SimpleSerializer s(1);
     s.writeU64(1, m_sampleRate);
     s.writeU32(2, m_log2Interp);
     return s.final();
 }
Member Data Documentation
m_centerFrequency
quint64 FileSinkSettings::m_centerFrequency
Definition at line 24 of file filesinksettings.h.
Referenced by FileSinkOutput::applySettings(), FileSinkGui::displaySettings(), FileSinkGui::getCenterFrequency(), FileSinkOutput::getCenterFrequency(), FileSinkGui::on_centerFrequency_changed(), FileSinkOutput::openFileStream(), resetToDefaults(), FileSinkGui::setCenterFrequency(), and FileSinkOutput::setCenterFrequency().
m_log2Interp
quint32 FileSinkSettings::m_log2Interp
Definition at line 26 of file filesinksettings.h.
Referenced by FileSinkOutput::applySettings(), deserialize(), FileSinkGui::on_interp_currentIndexChanged(), FileSinkOutput::openFileStream(), resetToDefaults(), serialize(), FileSinkOutput::start(), and FileSinkGui::updateSampleRateAndFrequency().
m_sampleRate
quint64 FileSinkSettings::m_sampleRate
Definition at line 25 of file filesinksettings.h.
Referenced by FileSinkOutput::applySettings(), deserialize(), FileSinkGui::displaySettings(), FileSinkOutput::getSampleRate(), FileSinkGui::on_sampleRate_changed(), FileSinkOutput::openFileStream(), resetToDefaults(), serialize(), FileSinkOutput::start(), and FileSinkGui::updateWithStreamTime().
The documentation for this struct was generated from the following files:
plugins/samplesink/filesink/filesinksettings.h
plugins/samplesink/filesink/filesinksettings.cpp