SDRAngel: RemoteSourceThread::MsgDataBind Class Reference
RemoteSourceThread::MsgDataBind Class Reference
#include <remotesourcethread.h>
Public Member Functions
QHostAddress getAddress () const
uint16_t getPort () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgDataBind * create (const QString &address, uint16_t port)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgDataBind (const QString &address, uint16_t port)
Protected Attributes
QHostAddress m_address
uint16_t m_port
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 55 of file remotesourcethread.h.
Constructor & Destructor Documentation
MsgDataBind()
RemoteSourceThread::MsgDataBind::MsgDataBind (const QString & address, uint16_t port) inline protected
Definition at line 70 of file remotesourcethread.h.
References RemoteSourceThread::dataBind(), RemoteSourceThread::RemoteSourceThread(), RemoteSourceThread::startStop(), and RemoteSourceThread::~RemoteSourceThread().
                                                            :
             Message(),
             m_port(port)
         {
             m_address.setAddress(address);
         }
Member Function Documentation
create()
static MsgDataBind* RemoteSourceThread::MsgDataBind::create (const QString & address, uint16_t port) inline static
Definition at line 62 of file remotesourcethread.h.
Referenced by RemoteSourceThread::dataBind().
{
             return new MsgDataBind(address, port);
         }
getAddress()
QHostAddress RemoteSourceThread::MsgDataBind::getAddress () const inline
Definition at line 59 of file remotesourcethread.h.
References RemoteSourceThread::m_address.
Referenced by RemoteSourceThread::handleInputMessages().
 { return m_address; }
getPort()
uint16_t RemoteSourceThread::MsgDataBind::getPort () const inline
Definition at line 60 of file remotesourcethread.h.
Referenced by RemoteSourceThread::handleInputMessages().
 { return m_port; }
Member Data Documentation
m_address
QHostAddress RemoteSourceThread::MsgDataBind::m_address protected
Definition at line 67 of file remotesourcethread.h.
m_port
uint16_t RemoteSourceThread::MsgDataBind::m_port protected
Definition at line 68 of file remotesourcethread.h.
The documentation for this class was generated from the following file:
plugins/channeltx/remotesource/remotesourcethread.h