SDRAngel: XTRXInput::MsgStartStop Class Reference
XTRXInput::MsgStartStop Class Reference
#include <xtrxinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 155 of file xtrxinput.h.
Constructor & Destructor Documentation
MsgStartStop()
XTRXInput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 168 of file xtrxinput.h.
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* XTRXInput::MsgStartStop::create (bool startStop) inline static
Definition at line 161 of file xtrxinput.h.
Referenced by XTRXInputGUI::on_startStop_toggled(), and XTRXInput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool XTRXInput::MsgStartStop::getStartStop () const inline
Definition at line 159 of file xtrxinput.h.
Referenced by XTRXInputGUI::handleMessage(), and XTRXInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool XTRXInput::MsgStartStop::m_startStop protected
Definition at line 166 of file xtrxinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/xtrxinput/xtrxinput.h