SDRAngel: DeviceSet Class Reference
DeviceSet Class Reference
#include <deviceset.h>
Classes
struct ChannelInstanceRegistration
Public Member Functions
DeviceSet (int tabIndex)
~DeviceSet ()
int getNumberOfRxChannels () const
int getNumberOfTxChannels () const
void addRxChannel (int selectedChannelIndex, PluginAPI *pluginAPI)
void addTxChannel (int selectedChannelIndex, PluginAPI *pluginAPI)
void deleteRxChannel (int channelIndex)
void deleteTxChannel (int channelIndex)
void registerRxChannelInstance (const QString &channelName, ChannelAPI *channelAPI)
void registerTxChannelInstance (const QString &channelName, ChannelAPI *channelAPI)
void removeRxChannelInstance (ChannelAPI *channelAPI)
void removeTxChannelInstance (ChannelAPI *channelAPI)
void freeRxChannels ()
void freeTxChannels ()
void loadRxChannelSettings (const Preset *preset, PluginAPI *pluginAPI)
void saveRxChannelSettings (Preset *preset)
void loadTxChannelSettings (const Preset *preset, PluginAPI *pluginAPI)
void saveTxChannelSettings (Preset *preset)
Public Attributes
DeviceAPI * m_deviceAPI
DSPDeviceSourceEngine * m_deviceSourceEngine
DSPDeviceSinkEngine * m_deviceSinkEngine
DSPDeviceMIMOEngine * m_deviceMIMOEngine
Private Types
typedef QList< ChannelInstanceRegistration > ChannelInstanceRegistrations
Private Member Functions
void renameRxChannelInstances ()
void renameTxChannelInstances ()
bool compareRxChannelURIs (const QString &registerdChannelURI, const QString &xChannelURI)
Private Attributes
ChannelInstanceRegistrations m_rxChannelInstanceRegistrations
ChannelInstanceRegistrations m_txChannelInstanceRegistrations
int m_deviceTabIndex
Detailed Description
Definition at line 31 of file deviceset.h.
Member Typedef Documentation
ChannelInstanceRegistrations
typedef QList<ChannelInstanceRegistration> DeviceSet::ChannelInstanceRegistrations private
Definition at line 77 of file deviceset.h.
Constructor & Destructor Documentation
DeviceSet()
DeviceSet::DeviceSet (int tabIndex)
Definition at line 51 of file deviceset.cpp.
References m_deviceAPI, m_deviceMIMOEngine, m_deviceSinkEngine, m_deviceSourceEngine, and m_deviceTabIndex.
 {
     m_deviceAPI = nullptr;
     m_deviceSourceEngine = nullptr;
     m_deviceSinkEngine = nullptr;
     m_deviceMIMOEngine = nullptr;
     m_deviceTabIndex = tabIndex;
 }
~DeviceSet()
DeviceSet::~DeviceSet ()
Definition at line 60 of file deviceset.cpp.
 {
 }
Member Function Documentation
addRxChannel()
void DeviceSet::addRxChannel (int selectedChannelIndex, PluginAPI * pluginAPI)
Definition at line 142 of file deviceset.cpp.
References DeviceSet::ChannelInstanceRegistration::ChannelInstanceRegistration(), ChannelAPI::getName(), PluginAPI::getRxChannelRegistrations(), m_deviceAPI, and m_rxChannelInstanceRegistrations.
Referenced by MainCore::addChannel(), and getNumberOfTxChannels().
 {
     PluginAPI::ChannelRegistrations *channelRegistrations = pluginAPI->getRxChannelRegistrations(); // Available channel plugins
     ChannelAPI *rxChannel =(*channelRegistrations)[selectedChannelIndex].m_plugin->createRxChannelCS(m_deviceAPI);
     ChannelInstanceRegistration reg = ChannelInstanceRegistration(rxChannel->getName(), rxChannel);
     m_rxChannelInstanceRegistrations.append(reg);
     qDebug("DeviceSet::addRxChannel: %s", qPrintable(rxChannel->getName()));
 }
addTxChannel()
void DeviceSet::addTxChannel (int selectedChannelIndex, PluginAPI * pluginAPI)
Definition at line 151 of file deviceset.cpp.
References DeviceSet::ChannelInstanceRegistration::ChannelInstanceRegistration(), ChannelAPI::getName(), PluginAPI::getTxChannelRegistrations(), m_deviceAPI, and m_txChannelInstanceRegistrations.
Referenced by MainCore::addChannel(), and getNumberOfTxChannels().
 {
     PluginAPI::ChannelRegistrations *channelRegistrations = pluginAPI->getTxChannelRegistrations(); // Available channel plugins
     ChannelAPI *txChannel = (*channelRegistrations)[selectedChannelIndex].m_plugin->createTxChannelCS(m_deviceAPI);
     ChannelInstanceRegistration reg = ChannelInstanceRegistration(txChannel->getName(), txChannel);
     m_txChannelInstanceRegistrations.append(reg);
     qDebug("DeviceSet::addTxChannel: %s", qPrintable(txChannel->getName()));
 }
compareRxChannelURIs()
bool DeviceSet::compareRxChannelURIs (const QString & registerdChannelURI, const QString & xChannelURI) private
Use this function to support possible older identifiers in presets
Definition at line 395 of file deviceset.cpp.
Referenced by loadRxChannelSettings().
 {
     if ((xChannelURI == "sdrangel.channel.chanalyzerng") || (xChannelURI == "sdrangel.channel.chanalyzer")) { // renamed ChanalyzerNG to Chanalyzer in 4.0.0
         return registerdChannelURI == "sdrangel.channel.chanalyzer";
     } else  if ((xChannelURI == "de.maintech.sdrangelove.channel.am") || (xChannelURI == "sdrangel.channel.amdemod")) {
         return registerdChannelURI == "sdrangel.channel.amdemod";
     } else  if ((xChannelURI == "de.maintech.sdrangelove.channel.nfm") || (xChannelURI == "sdrangel.channel.nfmdemod")) {
         return registerdChannelURI == "sdrangel.channel.nfmdemod";
     } else  if ((xChannelURI == "de.maintech.sdrangelove.channel.ssb") || (xChannelURI == "sdrangel.channel.ssbdemod")) {
         return registerdChannelURI == "sdrangel.channel.ssbdemod";
     } else  if ((xChannelURI == "de.maintech.sdrangelove.channel.wfm") || (xChannelURI == "sdrangel.channel.wfmdemod")) {
         return registerdChannelURI == "sdrangel.channel.wfmdemod";
     } else {
         return registerdChannelURI == xChannelURI;
     }
 }
deleteRxChannel()
void DeviceSet::deleteRxChannel (int channelIndex)
Definition at line 122 of file deviceset.cpp.
References m_rxChannelInstanceRegistrations, and renameRxChannelInstances().
Referenced by MainCore::deleteChannel(), and getNumberOfTxChannels().
 {
     if (channelIndex < m_rxChannelInstanceRegistrations.count())
     {
         m_rxChannelInstanceRegistrations[channelIndex].m_channelSinkAPI->destroy();
         m_rxChannelInstanceRegistrations.removeAt(channelIndex);
         renameRxChannelInstances();
     }
 }
deleteTxChannel()
void DeviceSet::deleteTxChannel (int channelIndex)
Definition at line 132 of file deviceset.cpp.
References m_txChannelInstanceRegistrations, and renameTxChannelInstances().
Referenced by MainCore::deleteChannel(), and getNumberOfTxChannels().
 {
     if (channelIndex < m_txChannelInstanceRegistrations.count())
     {
         m_txChannelInstanceRegistrations[channelIndex].m_channelSourceAPI->destroy();
         m_txChannelInstanceRegistrations.removeAt(channelIndex);
         renameTxChannelInstances();
     }
 }
freeRxChannels()
void DeviceSet::freeRxChannels ()
Definition at line 104 of file deviceset.cpp.
References i, DeviceSet::ChannelInstanceRegistration::m_channelName, and m_rxChannelInstanceRegistrations.
Referenced by getNumberOfTxChannels().
 {
     for(int i = 0; i < m_rxChannelInstanceRegistrations.count(); i++)
     {
         qDebug("DeviceSet::freeAll: destroying channel [%s]", qPrintable(m_rxChannelInstanceRegistrations[i].m_channelName));
         m_rxChannelInstanceRegistrations[i].m_channelSinkAPI->destroy();
     }
 }
freeTxChannels()
void DeviceSet::freeTxChannels ()
Definition at line 113 of file deviceset.cpp.
References i, DeviceSet::ChannelInstanceRegistration::m_channelName, and m_txChannelInstanceRegistrations.
Referenced by getNumberOfTxChannels().
 {
     for(int i = 0; i < m_txChannelInstanceRegistrations.count(); i++)
     {
         qDebug("DeviceSet::freeAll: destroying channel [%s]", qPrintable(m_txChannelInstanceRegistrations[i].m_channelName));
         m_txChannelInstanceRegistrations[i].m_channelSourceAPI->destroy();
     }
 }
getNumberOfRxChannels()
int DeviceSet::getNumberOfRxChannels () const inline
Definition at line 42 of file deviceset.h.
References m_rxChannelInstanceRegistrations.
 { return m_rxChannelInstanceRegistrations.size(); }
getNumberOfTxChannels()
int DeviceSet::getNumberOfTxChannels () const inline
Definition at line 43 of file deviceset.h.
References addRxChannel(), addTxChannel(), deleteRxChannel(), deleteTxChannel(), freeRxChannels(), freeTxChannels(), loadRxChannelSettings(), loadTxChannelSettings(), m_txChannelInstanceRegistrations, registerRxChannelInstance(), registerTxChannelInstance(), removeRxChannelInstance(), removeTxChannelInstance(), saveRxChannelSettings(), and saveTxChannelSettings().
 { return m_txChannelInstanceRegistrations.size(); }
loadRxChannelSettings()
void DeviceSet::loadRxChannelSettings (const Preset * preset, PluginAPI * pluginAPI)
Definition at line 160 of file deviceset.cpp.
References DeviceSet::ChannelInstanceRegistration::ChannelInstanceRegistration(), compareRxChannelURIs(), ChannelAPI::deserialize(), Preset::getChannelConfig(), Preset::getChannelCount(), Preset::getDescription(), Preset::getGroup(), PluginAPI::getRxChannelRegistrations(), i, Preset::isSourcePreset(), Preset::ChannelConfig::m_channelIdURI, DeviceSet::ChannelInstanceRegistration::m_channelName, DeviceSet::ChannelInstanceRegistration::m_channelSinkAPI, Preset::ChannelConfig::m_config, m_deviceAPI, m_rxChannelInstanceRegistrations, and renameRxChannelInstances().
Referenced by getNumberOfTxChannels(), and MainCore::loadPresetSettings().
 {
     if (preset->isSourcePreset())
     {
         qDebug("DeviceSet::loadChannelSettings: Loading preset [%s | %s]", qPrintable(preset->getGroup()), qPrintable(preset->getDescription()));
         // Available channel plugins
         PluginAPI::ChannelRegistrations *channelRegistrations = pluginAPI->getRxChannelRegistrations();
         // copy currently open channels and clear list
         ChannelInstanceRegistrations openChannels = m_rxChannelInstanceRegistrations;
         m_rxChannelInstanceRegistrations.clear();
         qDebug("DeviceSet::loadChannelSettings: %d channel(s) in preset", preset->getChannelCount());
         for (int i = 0; i < preset->getChannelCount(); i++)
         {
             const Preset::ChannelConfig& channelConfig = preset->getChannelConfig(i);
             ChannelInstanceRegistration reg;
             // if we have one instance available already, use it
             for (int i = 0; i < openChannels.count(); i++)
             {
                 qDebug("DeviceSet::loadChannelSettings: channels compare [%s] vs [%s]", qPrintable(openChannels[i].m_channelName), qPrintable(channelConfig.m_channelIdURI));
                 //if(openChannels[i].m_channelName == channelConfig.m_channelIdURI)
                 if (compareRxChannelURIs(openChannels[i].m_channelName, channelConfig.m_channelIdURI))
                 {
                     qDebug("DeviceSet::loadChannelSettings: channel [%s] found", qPrintable(openChannels[i].m_channelName));
                     reg = openChannels.takeAt(i);
                     m_rxChannelInstanceRegistrations.append(reg);
                     break;
                 }
             }
             // if we haven't one already, create one
             if (reg.m_channelSinkAPI == 0)
             {
                 for (int i = 0; i < channelRegistrations->count(); i++)
                 {
                     //if((*channelRegistrations)[i].m_channelIdURI == channelConfig.m_channelIdURI)
                     if (compareRxChannelURIs((*channelRegistrations)[i].m_channelIdURI, channelConfig.m_channelIdURI))
                     {
                         qDebug("DeviceSet::loadChannelSettings: creating new channel [%s] from config [%s]",
                                 qPrintable((*channelRegistrations)[i].m_channelIdURI),
                                 qPrintable(channelConfig.m_channelIdURI));
                         ChannelAPI *rxChannel = (*channelRegistrations)[i].m_plugin->createRxChannelCS(m_deviceAPI);
                         reg = ChannelInstanceRegistration(channelConfig.m_channelIdURI, rxChannel);
                         m_rxChannelInstanceRegistrations.append(reg);
                         break;
                     }
                 }
             }
             if (reg.m_channelSinkAPI != 0)
             {
                 qDebug("DeviceSet::loadChannelSettings: deserializing channel [%s]", qPrintable(channelConfig.m_channelIdURI));
                 reg.m_channelSinkAPI->deserialize(channelConfig.m_config);
             }
         }
         // everything, that is still "available" is not needed anymore
         for (int i = 0; i < openChannels.count(); i++)
         {
             qDebug("DeviceSet::loadChannelSettings: destroying spare channel [%s]", qPrintable(openChannels[i].m_channelName));
             openChannels[i].m_channelSinkAPI->destroy();
         }
         renameRxChannelInstances();
     }
     else
     {
         qDebug("DeviceSet::loadChannelSettings: Loading preset [%s | %s] not a source preset", qPrintable(preset->getGroup()), qPrintable(preset->getDescription()));
     }
 }
loadTxChannelSettings()
void DeviceSet::loadTxChannelSettings (const Preset * preset, PluginAPI * pluginAPI)
Definition at line 256 of file deviceset.cpp.
References DeviceSet::ChannelInstanceRegistration::ChannelInstanceRegistration(), ChannelAPI::deserialize(), Preset::getChannelConfig(), Preset::getChannelCount(), Preset::getDescription(), Preset::getGroup(), PluginAPI::getTxChannelRegistrations(), i, Preset::isSourcePreset(), Preset::ChannelConfig::m_channelIdURI, DeviceSet::ChannelInstanceRegistration::m_channelName, DeviceSet::ChannelInstanceRegistration::m_channelSourceAPI, Preset::ChannelConfig::m_config, m_deviceAPI, m_txChannelInstanceRegistrations, and renameTxChannelInstances().
Referenced by getNumberOfTxChannels(), and MainCore::loadPresetSettings().
 {
     if (preset->isSourcePreset())
     {
         qDebug("DeviceSet::loadChannelSettings: Loading preset [%s | %s] not a sink preset", qPrintable(preset->getGroup()), qPrintable(preset->getDescription()));
     }
     else
     {
         qDebug("DeviceSet::loadChannelSettings: Loading preset [%s | %s]", qPrintable(preset->getGroup()), qPrintable(preset->getDescription()));
         // Available channel plugins
         PluginAPI::ChannelRegistrations *channelRegistrations = pluginAPI->getTxChannelRegistrations();
         // copy currently open channels and clear list
         ChannelInstanceRegistrations openChannels = m_txChannelInstanceRegistrations;
         m_txChannelInstanceRegistrations.clear();
         qDebug("DeviceSet::loadChannelSettings: %d channel(s) in preset", preset->getChannelCount());
         for(int i = 0; i < preset->getChannelCount(); i++)
         {
             const Preset::ChannelConfig& channelConfig = preset->getChannelConfig(i);
             ChannelInstanceRegistration reg;
             // if we have one instance available already, use it
             for(int i = 0; i < openChannels.count(); i++)
             {
                 qDebug("DeviceSet::loadChannelSettings: channels compare [%s] vs [%s]", qPrintable(openChannels[i].m_channelName), qPrintable(channelConfig.m_channelIdURI));
                 if(openChannels[i].m_channelName == channelConfig.m_channelIdURI)
                 {
                     qDebug("DeviceSet::loadChannelSettings: channel [%s] found", qPrintable(openChannels[i].m_channelName));
                     reg = openChannels.takeAt(i);
                     m_txChannelInstanceRegistrations.append(reg);
                     break;
                 }
             }
             // if we haven't one already, create one
             if(reg.m_channelSourceAPI == 0)
             {
                 for(int i = 0; i < channelRegistrations->count(); i++)
                 {
                     if((*channelRegistrations)[i].m_channelIdURI == channelConfig.m_channelIdURI)
                     {
                         qDebug("DeviceSet::loadChannelSettings: creating new channel [%s]", qPrintable(channelConfig.m_channelIdURI));
                         ChannelAPI *txChannel = (*channelRegistrations)[i].m_plugin->createTxChannelCS(m_deviceAPI);
                         reg = ChannelInstanceRegistration(channelConfig.m_channelIdURI, txChannel);
                         m_txChannelInstanceRegistrations.append(reg);
                         break;
                     }
                 }
             }
             if(reg.m_channelSourceAPI != 0)
             {
                 qDebug("DeviceSet::loadChannelSettings: deserializing channel [%s]", qPrintable(channelConfig.m_channelIdURI));
                 reg.m_channelSourceAPI->deserialize(channelConfig.m_config);
             }
         }
         // everything, that is still "available" is not needed anymore
         for(int i = 0; i < openChannels.count(); i++)
         {
             qDebug("DeviceSet::loadChannelSettings: destroying spare channel [%s]", qPrintable(openChannels[i].m_channelName));
             openChannels[i].m_channelSourceAPI->destroy();
         }
         renameTxChannelInstances();
     }
 }
registerRxChannelInstance()
void DeviceSet::registerRxChannelInstance (const QString & channelName, ChannelAPI * channelAPI)
Definition at line 64 of file deviceset.cpp.
References DeviceSet::ChannelInstanceRegistration::ChannelInstanceRegistration(), m_rxChannelInstanceRegistrations, and renameRxChannelInstances().
Referenced by getNumberOfTxChannels().
 {
     m_rxChannelInstanceRegistrations.append(ChannelInstanceRegistration(channelName, channelAPI));
     renameRxChannelInstances();
 }
registerTxChannelInstance()
void DeviceSet::registerTxChannelInstance (const QString & channelName, ChannelAPI * channelAPI)
Definition at line 70 of file deviceset.cpp.
References DeviceSet::ChannelInstanceRegistration::ChannelInstanceRegistration(), m_txChannelInstanceRegistrations, and renameTxChannelInstances().
Referenced by getNumberOfTxChannels().
 {
     m_txChannelInstanceRegistrations.append(ChannelInstanceRegistration(channelName, channelAPI));
     renameTxChannelInstances();
 }
removeRxChannelInstance()
void DeviceSet::removeRxChannelInstance (ChannelAPI * channelAPI)
Definition at line 76 of file deviceset.cpp.
References m_rxChannelInstanceRegistrations, and renameRxChannelInstances().
Referenced by getNumberOfTxChannels().
 {
     for(ChannelInstanceRegistrations::iterator it = m_rxChannelInstanceRegistrations.begin(); it != m_rxChannelInstanceRegistrations.end(); ++it)
     {
         if(it->m_channelSinkAPI == channelAPI)
         {
             m_rxChannelInstanceRegistrations.erase(it);
             break;
         }
     }
     renameRxChannelInstances();
 }
removeTxChannelInstance()
void DeviceSet::removeTxChannelInstance (ChannelAPI * channelAPI)
Definition at line 90 of file deviceset.cpp.
References m_txChannelInstanceRegistrations, and renameTxChannelInstances().
Referenced by getNumberOfTxChannels().
 {
     for(ChannelInstanceRegistrations::iterator it = m_txChannelInstanceRegistrations.begin(); it != m_txChannelInstanceRegistrations.end(); ++it)
     {
         if(it->m_channelSourceAPI == channelAPI)
         {
             m_txChannelInstanceRegistrations.erase(it);
             break;
         }
     }
     renameTxChannelInstances();
 }
renameRxChannelInstances()
void DeviceSet::renameRxChannelInstances () private
Definition at line 348 of file deviceset.cpp.
References arg(), i, DeviceSet::ChannelInstanceRegistration::m_channelName, and m_rxChannelInstanceRegistrations.
Referenced by deleteRxChannel(), loadRxChannelSettings(), registerRxChannelInstance(), and removeRxChannelInstance().
 {
     for(int i = 0; i < m_rxChannelInstanceRegistrations.count(); i++)
     {
         m_rxChannelInstanceRegistrations[i].m_channelSinkAPI->setName(QString("%1:%2").arg(m_rxChannelInstanceRegistrations[i].m_channelName).arg(i));
     }
 }
renameTxChannelInstances()
void DeviceSet::renameTxChannelInstances () private
Definition at line 356 of file deviceset.cpp.
References arg(), i, DeviceSet::ChannelInstanceRegistration::m_channelName, and m_txChannelInstanceRegistrations.
Referenced by deleteTxChannel(), loadTxChannelSettings(), registerTxChannelInstance(), and removeTxChannelInstance().
 {
     for(int i = 0; i < m_txChannelInstanceRegistrations.count(); i++)
     {
         m_txChannelInstanceRegistrations[i].m_channelSourceAPI->setName(QString("%1:%2").arg(m_txChannelInstanceRegistrations[i].m_channelName).arg(i));
     }
 }
saveRxChannelSettings()
void DeviceSet::saveRxChannelSettings (Preset * preset)
Definition at line 238 of file deviceset.cpp.
References Preset::addChannel(), i, Preset::isSourcePreset(), DeviceSet::ChannelInstanceRegistration::m_channelName, DeviceSet::ChannelInstanceRegistration::m_channelSinkAPI, m_rxChannelInstanceRegistrations, and ChannelAPI::serialize().
Referenced by getNumberOfTxChannels(), and MainCore::savePresetSettings().
 {
     if (preset->isSourcePreset())
     {
         qSort(m_rxChannelInstanceRegistrations.begin(), m_rxChannelInstanceRegistrations.end()); // sort by increasing delta frequency and type
         for(int i = 0; i < m_rxChannelInstanceRegistrations.count(); i++)
         {
             qDebug("DeviceSet::saveChannelSettings: channel [%s] saved", qPrintable(m_rxChannelInstanceRegistrations[i].m_channelName));
             preset->addChannel(m_rxChannelInstanceRegistrations[i].m_channelName, m_rxChannelInstanceRegistrations[i].m_channelSinkAPI->serialize());
         }
     }
     else
     {
         qDebug("DeviceSet::saveChannelSettings: not a source preset");
     }
 }
saveTxChannelSettings()
void DeviceSet::saveTxChannelSettings (Preset * preset)
Definition at line 330 of file deviceset.cpp.
References Preset::addChannel(), i, Preset::isSourcePreset(), DeviceSet::ChannelInstanceRegistration::m_channelName, DeviceSet::ChannelInstanceRegistration::m_channelSourceAPI, m_txChannelInstanceRegistrations, and ChannelAPI::serialize().
Referenced by getNumberOfTxChannels(), and MainCore::savePresetSettings().
 {
     if (preset->isSourcePreset())
     {
         qDebug("DeviceSet::saveChannelSettings: not a sink preset");
     }
     else
     {
         qSort(m_txChannelInstanceRegistrations.begin(), m_txChannelInstanceRegistrations.end()); // sort by increasing delta frequency and type
         for(int i = 0; i < m_txChannelInstanceRegistrations.count(); i++)
         {
             qDebug("DeviceSet::saveChannelSettings: channel [%s] saved", qPrintable(m_txChannelInstanceRegistrations[i].m_channelName));
             preset->addChannel(m_txChannelInstanceRegistrations[i].m_channelName, m_txChannelInstanceRegistrations[i].m_channelSourceAPI->serialize());
         }
     }
 }
Member Data Documentation
m_deviceAPI
DeviceAPI* DeviceSet::m_deviceAPI
Definition at line 34 of file deviceset.h.
Referenced by addRxChannel(), addTxChannel(), MainCore::changeSampleSink(), MainCore::changeSampleSource(), DeviceSet(), WebAPIAdapterSrv::devicesetChannelReportGet(), WebAPIAdapterSrv::devicesetChannelSettingsGet(), WebAPIAdapterSrv::devicesetChannelSettingsPutPatch(), WebAPIAdapterSrv::devicesetDeviceReportGet(), WebAPIAdapterSrv::devicesetDeviceRunDelete(), WebAPIAdapterSrv::devicesetDeviceRunGet(), WebAPIAdapterSrv::devicesetDeviceRunPost(), WebAPIAdapterSrv::devicesetDeviceSettingsGet(), WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch(), WebAPIAdapterSrv::getChannelsDetail(), WebAPIAdapterSrv::getDeviceSet(), MainCore::loadPresetSettings(), loadRxChannelSettings(), loadTxChannelSettings(), and MainCore::savePresetSettings().
m_deviceMIMOEngine
DSPDeviceMIMOEngine* DeviceSet::m_deviceMIMOEngine
Definition at line 37 of file deviceset.h.
Referenced by DeviceSet().
m_deviceSinkEngine
DSPDeviceSinkEngine* DeviceSet::m_deviceSinkEngine
Definition at line 36 of file deviceset.h.
Referenced by MainCore::addChannel(), MainCore::deleteChannel(), DeviceSet(), WebAPIAdapterSrv::devicesetChannelDelete(), WebAPIAdapterSrv::devicesetChannelPost(), WebAPIAdapterSrv::devicesetChannelReportGet(), WebAPIAdapterSrv::devicesetChannelSettingsGet(), WebAPIAdapterSrv::devicesetChannelSettingsPutPatch(), WebAPIAdapterSrv::devicesetDevicePut(), WebAPIAdapterSrv::devicesetDeviceReportGet(), WebAPIAdapterSrv::devicesetDeviceRunDelete(), WebAPIAdapterSrv::devicesetDeviceRunGet(), WebAPIAdapterSrv::devicesetDeviceRunPost(), WebAPIAdapterSrv::devicesetDeviceSettingsGet(), WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch(), WebAPIAdapterSrv::getChannelsDetail(), WebAPIAdapterSrv::getDeviceSet(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterSrv::instancePresetPut(), MainCore::loadPresetSettings(), and MainCore::savePresetSettings().
m_deviceSourceEngine
DSPDeviceSourceEngine* DeviceSet::m_deviceSourceEngine
Definition at line 35 of file deviceset.h.
Referenced by MainCore::addChannel(), MainCore::deleteChannel(), DeviceSet(), WebAPIAdapterSrv::devicesetChannelDelete(), WebAPIAdapterSrv::devicesetChannelPost(), WebAPIAdapterSrv::devicesetChannelReportGet(), WebAPIAdapterSrv::devicesetChannelSettingsGet(), WebAPIAdapterSrv::devicesetChannelSettingsPutPatch(), WebAPIAdapterSrv::devicesetDevicePut(), WebAPIAdapterSrv::devicesetDeviceReportGet(), WebAPIAdapterSrv::devicesetDeviceRunDelete(), WebAPIAdapterSrv::devicesetDeviceRunGet(), WebAPIAdapterSrv::devicesetDeviceRunPost(), WebAPIAdapterSrv::devicesetDeviceSettingsGet(), WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch(), WebAPIAdapterSrv::getChannelsDetail(), WebAPIAdapterSrv::getDeviceSet(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterSrv::instancePresetPut(), MainCore::loadPresetSettings(), and MainCore::savePresetSettings().
m_deviceTabIndex
int DeviceSet::m_deviceTabIndex private
Definition at line 81 of file deviceset.h.
Referenced by DeviceSet().
m_rxChannelInstanceRegistrations
ChannelInstanceRegistrations DeviceSet::m_rxChannelInstanceRegistrations private
Definition at line 79 of file deviceset.h.
Referenced by addRxChannel(), deleteRxChannel(), freeRxChannels(), getNumberOfRxChannels(), loadRxChannelSettings(), registerRxChannelInstance(), removeRxChannelInstance(), renameRxChannelInstances(), and saveRxChannelSettings().
m_txChannelInstanceRegistrations
ChannelInstanceRegistrations DeviceSet::m_txChannelInstanceRegistrations private
Definition at line 80 of file deviceset.h.
Referenced by addTxChannel(), deleteTxChannel(), freeTxChannels(), getNumberOfTxChannels(), loadTxChannelSettings(), registerTxChannelInstance(), removeTxChannelInstance(), renameTxChannelInstances(), and saveTxChannelSettings().
The documentation for this class was generated from the following files:
sdrsrv/device/deviceset.h
sdrsrv/device/deviceset.cpp