SDRAngel: DiscreteRangeGUI Class Reference
DiscreteRangeGUI Class Reference
#include <discreterangegui.h>
Public Member Functions
DiscreteRangeGUI (QWidget *parent=0)
virtual ~DiscreteRangeGUI ()
void setLabel (const QString &text)
void setUnits (const QString &units)
void addItem (const QString &itemStr, double itemValue)
virtual double getCurrentValue ()
virtual void setValue (double value)
Public Member Functions inherited from ItemSettingGUI
ItemSettingGUI (QWidget *parent=0)
virtual ~ItemSettingGUI ()
Private Slots
void on_rangeCombo_currentIndexChanged (int index)
Private Attributes
Ui::DiscreteRangeGUI * ui
std::vector< double > itemValues
Additional Inherited Members
Signals inherited from ItemSettingGUI
void valueChanged (double value)
Detailed Description
Definition at line 31 of file discreterangegui.h.
Constructor & Destructor Documentation
DiscreteRangeGUI()
DiscreteRangeGUI::DiscreteRangeGUI (QWidget * parent = 0) explicit
Definition at line 21 of file discreterangegui.cpp.
References ui.
                                                   :
     ItemSettingGUI(parent),
     ui(new Ui::DiscreteRangeGUI)
 {
     ui->setupUi(this);
 }
~DiscreteRangeGUI()
DiscreteRangeGUI::~DiscreteRangeGUI () virtual
Definition at line 28 of file discreterangegui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
addItem()
void DiscreteRangeGUI::addItem (const QString & itemStr, double itemValue)
Definition at line 43 of file discreterangegui.cpp.
References itemValues, and ui.
Referenced by SoapySDRInputGui::createRangesControl(), and SoapySDROutputGui::createRangesControl().
 {
     ui->rangeCombo->blockSignals(true);
     ui->rangeCombo->addItem(itemStr);
     itemValues.push_back(itemValue);
     ui->rangeCombo->blockSignals(false);
 }
getCurrentValue()
double DiscreteRangeGUI::getCurrentValue () virtual
Implements ItemSettingGUI.
Definition at line 51 of file discreterangegui.cpp.
References itemValues, and ui.
 {
     return itemValues[ui->rangeCombo->currentIndex()];
 }
on_rangeCombo_currentIndexChanged
void DiscreteRangeGUI::on_rangeCombo_currentIndexChanged (int index) private slot
Definition at line 74 of file discreterangegui.cpp.
References itemValues, and ItemSettingGUI::valueChanged().
 {
     double newRange = itemValues[index];
     emit ItemSettingGUI::valueChanged(newRange);
 }
setLabel()
void DiscreteRangeGUI::setLabel (const QString & text)
Definition at line 33 of file discreterangegui.cpp.
References ui.
Referenced by SoapySDRInputGui::createRangesControl(), and SoapySDROutputGui::createRangesControl().
 {
     ui->rangeLabel->setText(text);
 }
setUnits()
void DiscreteRangeGUI::setUnits (const QString & units)
Definition at line 38 of file discreterangegui.cpp.
References ui.
Referenced by SoapySDRInputGui::createRangesControl(), and SoapySDROutputGui::createRangesControl().
 {
     ui->rangeUnits->setText(units);
 }
setValue()
void DiscreteRangeGUI::setValue (double value) virtual
Implements ItemSettingGUI.
Definition at line 56 of file discreterangegui.cpp.
References itemValues, and ui.
 {
     int index = 0;
     for (const auto &it : itemValues)
     {
         if (it >= value)
         {
             ui->rangeCombo->blockSignals(true);
             ui->rangeCombo->setCurrentIndex(index);
             ui->rangeCombo->blockSignals(false);
             break;
         }
         index++;
     }
 }
Member Data Documentation
itemValues
std::vector<double> DiscreteRangeGUI::itemValues private
Definition at line 49 of file discreterangegui.h.
Referenced by addItem(), getCurrentValue(), on_rangeCombo_currentIndexChanged(), and setValue().
ui
Ui::DiscreteRangeGUI* DiscreteRangeGUI::ui private
Definition at line 48 of file discreterangegui.h.
Referenced by addItem(), DiscreteRangeGUI(), getCurrentValue(), setLabel(), setUnits(), setValue(), and ~DiscreteRangeGUI().
The documentation for this class was generated from the following files:
sdrgui/soapygui/discreterangegui.h
sdrgui/soapygui/discreterangegui.cpp