SDRAngel: RemoteInputPlugin Class Reference
RemoteInputPlugin Class Reference
#include <remoteinputplugin.h>
Public Member Functions
RemoteInputPlugin (QObject *parent=NULL)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "RemoteInput"
static const QString m_deviceTypeID = REMOTEINPUT_DEVICE_TYPE_ID
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 28 of file remoteinputplugin.h.
Constructor & Destructor Documentation
RemoteInputPlugin()
RemoteInputPlugin::RemoteInputPlugin (QObject * parent = NULL) explicit
Definition at line 42 of file remoteinputplugin.cpp.
                                                     :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSourcePluginInstance()
DeviceSampleSource * RemoteInputPlugin::createSampleSourcePluginInstance (const QString & sourceId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 105 of file remoteinputplugin.cpp.
References m_deviceTypeID.
 {
     if (sourceId == m_deviceTypeID)
     {
         RemoteInput* input = new RemoteInput(deviceAPI);
         return input;
     }
     else
     {
         return 0;
     }
 }
createSampleSourcePluginInstanceGUI()
PluginInstanceGUI * RemoteInputPlugin::createSampleSourcePluginInstanceGUI (const QString & sourceId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 87 of file remoteinputplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSources().
 {
     if(sourceId == m_deviceTypeID)
     {
         RemoteInputGui* gui = new RemoteInputGui(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSources()
PluginInterface::SamplingDevices RemoteInputPlugin::enumSampleSources () virtual
Reimplemented from PluginInterface.
Definition at line 57 of file remoteinputplugin.cpp.
References PluginInterface::SamplingDevice::BuiltInDevice, createSampleSourcePluginInstanceGUI(), m_deviceTypeID, m_hardwareID, and PluginInterface::SamplingDevice::StreamSingleRx.
 {
     SamplingDevices result;
     result.append(SamplingDevice(
             "RemoteInput",
             m_hardwareID,
             m_deviceTypeID,
             QString::null,
             0,
             PluginInterface::SamplingDevice::BuiltInDevice,
             PluginInterface::SamplingDevice::StreamSingleRx,
             1,
             0));
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & RemoteInputPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 47 of file remoteinputplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void RemoteInputPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 52 of file remoteinputplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSource().
 {
     pluginAPI->registerSampleSource(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString RemoteInputPlugin::m_deviceTypeID = REMOTEINPUT_DEVICE_TYPE_ID static
Definition at line 47 of file remoteinputplugin.h.
Referenced by createSampleSourcePluginInstance(), createSampleSourcePluginInstanceGUI(), enumSampleSources(), and initPlugin().
m_hardwareID
const QString RemoteInputPlugin::m_hardwareID = "RemoteInput" static
Definition at line 46 of file remoteinputplugin.h.
Referenced by enumSampleSources().
m_pluginDescriptor
const PluginDescriptor RemoteInputPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("Remote device input"),
    QString("4.5.6"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 50 of file remoteinputplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesource/remoteinput/remoteinputplugin.h
plugins/samplesource/remoteinput/remoteinputplugin.cpp