SDRAngel: DeviceBladeRF2 Class Reference
DeviceBladeRF2 Class Reference
#include <devicebladerf2.h>
Public Member Functions
DeviceBladeRF2 ()
~DeviceBladeRF2 ()
bool open (const char *serial)
void close ()
bladerf * getDev ()
bool openRx (int channel)
bool openTx (int channel)
void closeRx (int channel)
void closeTx (int channel)
void getFrequencyRangeRx (uint64_t &min, uint64_t &max, int &step)
void getFrequencyRangeTx (uint64_t &min, uint64_t &max, int &step)
void getSampleRateRangeRx (int &min, int &max, int &step)
void getSampleRateRangeTx (int &min, int &max, int &step)
void getBandwidthRangeRx (int &min, int &max, int &step)
void getBandwidthRangeTx (int &min, int &max, int &step)
void getGlobalGainRangeRx (int &min, int &max, int &step)
void getGlobalGainRangeTx (int &min, int &max, int &step)
int getGainModesRx (const bladerf_gain_modes **)
void setBiasTeeRx (bool enable)
void setBiasTeeTx (bool enable)
Static Public Attributes
static const unsigned int blockSize = (1<<14)
Static Private Member Functions
static struct bladerf * open_bladerf_from_serial (const char *serial)
Private Attributes
bladerf * m_dev
int m_nbRxChannels
int m_nbTxChannels
bool * m_rxOpen
bool * m_txOpen
Detailed Description
Definition at line 26 of file devicebladerf2.h.
Constructor & Destructor Documentation
DeviceBladeRF2()
DeviceBladeRF2::DeviceBladeRF2 ()
Definition at line 26 of file devicebladerf2.cpp.
                                :
     m_dev(0),
     m_nbRxChannels(0),
     m_nbTxChannels(0),
     m_rxOpen(0),
     m_txOpen(0)
 {}
~DeviceBladeRF2()
DeviceBladeRF2::~DeviceBladeRF2 ()
Definition at line 34 of file devicebladerf2.cpp.
References m_dev, m_rxOpen, and m_txOpen.
 {
     if (m_dev)
     {
         bladerf_close(m_dev);
         m_dev = 0;
     }
     if (m_rxOpen) {
         delete[] m_rxOpen;
     }
     if (m_txOpen) {
         delete[] m_txOpen;
     }
 }
Member Function Documentation
close()
void DeviceBladeRF2::close ()
Definition at line 86 of file devicebladerf2.cpp.
References m_dev.
Referenced by BladeRF2Output::closeDevice(), and BladeRF2Input::closeDevice().
 {
     if (m_dev)
     {
         bladerf_close(m_dev);
         m_dev = 0;
     }
 }
closeRx()
void DeviceBladeRF2::closeRx (int channel)
Definition at line 210 of file devicebladerf2.cpp.
References m_dev, m_nbRxChannels, and m_rxOpen.
Referenced by BladeRF2Input::stop().
 {
     if (!m_dev) {
         return;
     }
     if ((channel < 0) || (channel >= m_nbRxChannels))
     {
         qCritical("DeviceBladeRF2::closeRx: invalid Rx channel index %d", channel);
         return;
     }
     if (m_rxOpen[channel])
     {
         int status = bladerf_enable_module(m_dev, BLADERF_CHANNEL_RX(channel), false);
         m_rxOpen[channel] = false;
         if (status < 0) {
             qCritical("DeviceBladeRF2::closeRx: failed to disable Rx channel %d: %s", channel, bladerf_strerror(status));
         } else {
             qDebug("DeviceBladeRF2::closeRx: Rx channel %d disabled", channel);
         }
     }
     else
     {
         qDebug("DeviceBladeRF2::closeRx: Rx channel %d already closed", channel);
     }
 }
closeTx()
void DeviceBladeRF2::closeTx (int channel)
Definition at line 239 of file devicebladerf2.cpp.
References m_dev, m_nbTxChannels, and m_txOpen.
Referenced by BladeRF2Output::start(), and BladeRF2Output::stop().
 {
     if (!m_dev) {
         return;
     }
     if ((channel < 0) || (channel >= m_nbTxChannels))
     {
         qCritical("DeviceBladeRF2::closeTx: invalid Tx channel index %d", channel);
         return;
     }
     if (m_txOpen[channel])
     {
         int status = bladerf_enable_module(m_dev, BLADERF_CHANNEL_TX(channel), false);
         m_txOpen[channel] = false;
         if (status < 0) {
             qCritical("DeviceBladeRF2::closeTx: failed to disable Tx channel %d: %s", channel, bladerf_strerror(status));
         } else {
             qDebug("DeviceBladeRF2::closeTx: Tx channel %d disabled", channel);
         }
     }
     else
     {
         qDebug("DeviceBladeRF2::closeTx: Rx channel %d already closed", channel);
     }
 }
getBandwidthRangeRx()
void DeviceBladeRF2::getBandwidthRangeRx (int & min, int & max, int & step)
Definition at line 361 of file devicebladerf2.cpp.
References m_dev.
Referenced by BladeRF2Input::getBandwidthRange(), and BladeRF2Input::webapiFormatDeviceReport().
 {
     if (m_dev)
     {
         const struct bladerf_range *range;
         int status;
         status = bladerf_get_bandwidth_range(m_dev, BLADERF_CHANNEL_RX(0), &range);
         if (status < 0)
         {
             qCritical("DeviceBladeRF2::getBandwidthRangeRx: Failed to get Rx bandwidth range: %s",
                     bladerf_strerror(status));
         }
         else
         {
             min = range->min;
             max = range->max;
             step = range->step;
         }
     }
 }
getBandwidthRangeTx()
void DeviceBladeRF2::getBandwidthRangeTx (int & min, int & max, int & step)
Definition at line 384 of file devicebladerf2.cpp.
References m_dev.
Referenced by BladeRF2Output::getBandwidthRange(), and BladeRF2Output::webapiFormatDeviceReport().
 {
     if (m_dev)
     {
         const struct bladerf_range *range;
         int status;
         status = bladerf_get_bandwidth_range(m_dev, BLADERF_CHANNEL_TX(0), &range);
         if (status < 0)
         {
             qCritical("DeviceBladeRF2::getBandwidthRangeTx: Failed to get Tx bandwidth range: %s",
                     bladerf_strerror(status));
         }
         else
         {
             min = range->min;
             max = range->max;
             step = range->step;
         }
     }
 }
getDev()
bladerf* DeviceBladeRF2::getDev () inline
Definition at line 35 of file devicebladerf2.h.
References leansdr::max(), and leansdr::min().
Referenced by BladeRF2Output::applySettings(), BladeRF2Input::applySettings(), BladeRF2Output::handleMessage(), BladeRF2Input::handleMessage(), BladeRF2Output::start(), BladeRF2Input::start(), BladeRF2Output::stop(), and BladeRF2Input::stop().
 { return m_dev; }
getFrequencyRangeRx()
void DeviceBladeRF2::getFrequencyRangeRx (uint64_t & min, uint64_t & max, int & step)
Definition at line 268 of file devicebladerf2.cpp.
References m_dev.
Referenced by BladeRF2Input::getFrequencyRange(), and BladeRF2Input::webapiFormatDeviceReport().
 {
     if (m_dev)
     {
         const struct bladerf_range *range;
         int status;
         status = bladerf_get_frequency_range(m_dev, BLADERF_CHANNEL_RX(0), &range);
         if (status < 0)
         {
             qCritical("DeviceBladeRF2::getFrequencyRangeRx: Failed to get Rx frequency range: %s",
                     bladerf_strerror(status));
         }
         else
         {
             min = range->min;
             max = range->max;
             step = range->step;
         }
     }
 }
getFrequencyRangeTx()
void DeviceBladeRF2::getFrequencyRangeTx (uint64_t & min, uint64_t & max, int & step)
Definition at line 291 of file devicebladerf2.cpp.
References m_dev.
Referenced by BladeRF2Output::getFrequencyRange(), and BladeRF2Output::webapiFormatDeviceReport().
 {
     if (m_dev)
     {
         const struct bladerf_range *range;
         int status;
         status = bladerf_get_frequency_range(m_dev, BLADERF_CHANNEL_TX(0), &range);
         if (status < 0)
         {
             qCritical("DeviceBladeRF2::getFrequencyRangeTx: Failed to get Tx frequency range: %s",
                     bladerf_strerror(status));
         }
         else
         {
             min = range->min;
             max = range->max;
             step = range->step;
         }
     }
 }
getGainModesRx()
int DeviceBladeRF2::getGainModesRx (const bladerf_gain_modes ** modes)
Definition at line 453 of file devicebladerf2.cpp.
References m_dev.
 {
     if (m_dev)
     {
         int n = bladerf_get_gain_modes(m_dev, BLADERF_CHANNEL_RX(0), 0);
         if (n < 0)
         {
             qCritical("DeviceBladeRF2::getGainModesRx: Failed to get the number of Rx gain modes: %s", bladerf_strerror(n));
             return 0;
         }
         int status = bladerf_get_gain_modes(m_dev, BLADERF_CHANNEL_RX(0), modes);
         if (status < 0)
         {
             qCritical("DeviceBladeRF2::getGainModesRx: Failed to get Rx gain modes: %s", bladerf_strerror(status));
             return 0;
         }
         else
         {
             return n;
         }
     }
     else
     {
         return 0;
     }
 }
getGlobalGainRangeRx()
void DeviceBladeRF2::getGlobalGainRangeRx (int & min, int & max, int & step)
Definition at line 407 of file devicebladerf2.cpp.
References m_dev.
Referenced by BladeRF2Input::getGlobalGainRange(), and BladeRF2Input::webapiFormatDeviceReport().
 {
     if (m_dev)
     {
         const struct bladerf_range *range;
         int status;
         status = bladerf_get_gain_range(m_dev, BLADERF_CHANNEL_RX(0), &range);
         if (status < 0)
         {
             qCritical("DeviceBladeRF2::getGlobalGainRangeRx: Failed to get Rx global gain range: %s",
                     bladerf_strerror(status));
         }
         else
         {
             min = range->min;
             max = range->max;
             step = range->step;
         }
     }
 }
getGlobalGainRangeTx()
void DeviceBladeRF2::getGlobalGainRangeTx (int & min, int & max, int & step)
Definition at line 430 of file devicebladerf2.cpp.
References m_dev.
Referenced by BladeRF2Output::getGlobalGainRange(), and BladeRF2Output::webapiFormatDeviceReport().
 {
     if (m_dev)
     {
         const struct bladerf_range *range;
         int status;
         status = bladerf_get_gain_range(m_dev, BLADERF_CHANNEL_TX(0), &range);
         if (status < 0)
         {
             qCritical("DeviceBladeRF2::getGlobalGainRangeTx: Failed to get Tx global gain range: %s",
                     bladerf_strerror(status));
         }
         else
         {
             min = range->min;
             max = range->max;
             step = range->step;
         }
     }
 }
getSampleRateRangeRx()
void DeviceBladeRF2::getSampleRateRangeRx (int & min, int & max, int & step)
Definition at line 314 of file devicebladerf2.cpp.
References m_dev.
Referenced by BladeRF2Input::getSampleRateRange(), and BladeRF2Input::webapiFormatDeviceReport().
 {
     if (m_dev)
     {
         const struct bladerf_range *range;
         int status;
         status = bladerf_get_sample_rate_range(m_dev, BLADERF_CHANNEL_RX(0), &range);
         if (status < 0)
         {
             qCritical("DeviceBladeRF2::getSampleRateRangeRx: Failed to get Rx sample rate range: %s",
                     bladerf_strerror(status));
         }
         else
         {
             min = range->min;
             max = range->max;
             step = range->step;
         }
     }
 }
getSampleRateRangeTx()
void DeviceBladeRF2::getSampleRateRangeTx (int & min, int & max, int & step)
Definition at line 337 of file devicebladerf2.cpp.
References m_dev.
Referenced by BladeRF2Output::getSampleRateRange(), and BladeRF2Output::webapiFormatDeviceReport().
 {
     if (m_dev)
     {
         const struct bladerf_range *range;
         int status;
         status = bladerf_get_sample_rate_range(m_dev, BLADERF_CHANNEL_TX(0), &range);
         if (status < 0)
         {
             qCritical("DeviceBladeRF2::getSampleRateRangeTx: Failed to get Tx sample rate range: %s",
                     bladerf_strerror(status));
         }
         else
         {
             min = range->min;
             max = range->max;
             step = range->step;
         }
     }
 }
open()
bool DeviceBladeRF2::open (const char * serial)
Definition at line 51 of file devicebladerf2.cpp.
References m_dev, m_nbRxChannels, m_nbTxChannels, m_rxOpen, m_txOpen, and open_bladerf_from_serial().
Referenced by BladeRF2Output::openDevice(), and BladeRF2Input::openDevice().
 {
     int fpga_loaded;
     if ((m_dev = open_bladerf_from_serial(serial)) == 0)
     {
         qCritical("DeviceBladeRF2::open: could not open BladeRF");
         return false;
     }
     fpga_loaded = bladerf_is_fpga_configured(m_dev);
     if (fpga_loaded < 0)
     {
         qCritical("DeviceBladeRF2::open: failed to check FPGA state: %s",
                 bladerf_strerror(fpga_loaded));
         return false;
     }
     else if (fpga_loaded == 0)
     {
         qCritical("DeviceBladeRF2::open: the device's FPGA is not loaded.");
         return false;
     }
     m_nbRxChannels = bladerf_get_channel_count(m_dev, BLADERF_RX);
     m_nbTxChannels = bladerf_get_channel_count(m_dev, BLADERF_TX);
     m_rxOpen = new bool[m_nbRxChannels];
     m_txOpen = new bool[m_nbTxChannels];
     std::fill(m_rxOpen, m_rxOpen + m_nbRxChannels, false);
     std::fill(m_txOpen, m_txOpen + m_nbTxChannels, false);
     return true;
 }
open_bladerf_from_serial()
struct bladerf * DeviceBladeRF2::open_bladerf_from_serial (const char * serial) static private
Definition at line 95 of file devicebladerf2.cpp.
Referenced by open().
 {
     int status;
     struct bladerf *dev;
     struct bladerf_devinfo info;
     /* Initialize all fields to "don't care" wildcard values.
      *
      * Immediately passing this to bladerf_open_with_devinfo() would cause
      * libbladeRF to open any device on any available backend. */
     bladerf_init_devinfo(&info);
     /* Specify the desired device's serial number, while leaving all other
      * fields in the info structure wildcard values */
     if (serial != 0)
     {
         strncpy(info.serial, serial, BLADERF_SERIAL_LENGTH - 1);
         info.serial[BLADERF_SERIAL_LENGTH - 1] = '\0';
     }
     status = bladerf_open_with_devinfo(&dev, &info);
     if (status == BLADERF_ERR_NODEV)
     {
         qCritical("DeviceBladeRF2::open_bladerf_from_serial: No devices available with serial %s", serial);
         return 0;
     }
     else if (status != 0)
     {
         qCritical("DeviceBladeRF2::open_bladerf_from_serial: Failed to open device with serial %s (%s)",
                 serial, bladerf_strerror(status));
         return 0;
     }
     else
     {
         return dev;
     }
 }
openRx()
bool DeviceBladeRF2::openRx (int channel)
Definition at line 134 of file devicebladerf2.cpp.
References m_dev, m_nbRxChannels, and m_rxOpen.
Referenced by BladeRF2Input::start().
 {
     if (!m_dev) {
         return false;
     }
     if ((channel < 0) || (channel >= m_nbRxChannels))
     {
         qCritical("DeviceBladeRF2::openRx: invalid Rx channel index %d", channel);
         return false;
     }
     int status;
     if (!m_rxOpen[channel])
     {
         status = bladerf_enable_module(m_dev, BLADERF_CHANNEL_RX(channel), true);
         if (status < 0)
         {
             qCritical("DeviceBladeRF2::openRx: failed to enable Rx channel %d: %s",
                     channel, bladerf_strerror(status));
             return false;
         }
         else
         {
             qDebug("DeviceBladeRF2::openRx: Rx channel %d enabled", channel);
             m_rxOpen[channel] = true;
             return true;
         }
     }
     else
     {
         qDebug("DeviceBladeRF2::openRx: Rx channel %d already opened", channel);
         return true;
     }
 }
openTx()
bool DeviceBladeRF2::openTx (int channel)
Definition at line 172 of file devicebladerf2.cpp.
References m_dev, m_nbTxChannels, and m_txOpen.
Referenced by BladeRF2Output::start(), and BladeRF2Output::stop().
 {
     if (!m_dev) {
         return false;
     }
     if ((channel < 0) || (channel >= m_nbTxChannels))
     {
         qCritical("DeviceBladeRF2::openTx: invalid Tx channel index %d", channel);
         return false;
     }
     int status;
     if (!m_txOpen[channel])
     {
         status = bladerf_enable_module(m_dev, BLADERF_CHANNEL_TX(channel), true);
         if (status < 0)
         {
             qCritical("DeviceBladeRF2::openTx: Failed to enable Tx channel %d: %s",
                     channel, bladerf_strerror(status));
             return false;
         }
         else
         {
             qDebug("DeviceBladeRF2::openTx: Tx channel %d enabled", channel);
             m_txOpen[channel] = true;
             return true;
         }
     }
     else
     {
         qDebug("DeviceBladeRF2::openTx: Tx channel %d already opened", channel);
         return true;
     }
 }
setBiasTeeRx()
void DeviceBladeRF2::setBiasTeeRx (bool enable)
Definition at line 483 of file devicebladerf2.cpp.
References m_dev.
Referenced by BladeRF2Input::applySettings().
 {
     if (m_dev)
     {
         int status = bladerf_set_bias_tee(m_dev, BLADERF_CHANNEL_RX(0), enable);
         if (status < 0) {
             qCritical("DeviceBladeRF2::setBiasTeeRx: Failed to set Rx bias tee: %s", bladerf_strerror(status));
         }
     }
 }
setBiasTeeTx()
void DeviceBladeRF2::setBiasTeeTx (bool enable)
Definition at line 495 of file devicebladerf2.cpp.
References m_dev.
Referenced by BladeRF2Output::applySettings().
 {
     if (m_dev)
     {
         int status = bladerf_set_bias_tee(m_dev, BLADERF_CHANNEL_TX(0), enable);
         if (status < 0) {
             qCritical("DeviceBladeRF2::setBiasTeeTx: Failed to set Tx bias tee: %s", bladerf_strerror(status));
         }
     }
 }
Member Data Documentation
blockSize
const unsigned int DeviceBladeRF2::blockSize = (1<<14) static
Definition at line 54 of file devicebladerf2.h.
Referenced by BladeRF2InputThread::BladeRF2InputThread(), BladeRF2OutputThread::BladeRF2OutputThread(), BladeRF2OutputThread::run(), and BladeRF2InputThread::run().
m_dev
bladerf* DeviceBladeRF2::m_dev private
Definition at line 57 of file devicebladerf2.h.
Referenced by close(), closeRx(), closeTx(), getBandwidthRangeRx(), getBandwidthRangeTx(), getFrequencyRangeRx(), getFrequencyRangeTx(), getGainModesRx(), getGlobalGainRangeRx(), getGlobalGainRangeTx(), getSampleRateRangeRx(), getSampleRateRangeTx(), open(), openRx(), openTx(), setBiasTeeRx(), setBiasTeeTx(), and ~DeviceBladeRF2().
m_nbRxChannels
int DeviceBladeRF2::m_nbRxChannels private
Definition at line 58 of file devicebladerf2.h.
Referenced by closeRx(), open(), and openRx().
m_nbTxChannels
int DeviceBladeRF2::m_nbTxChannels private
Definition at line 59 of file devicebladerf2.h.
Referenced by closeTx(), open(), and openTx().
m_rxOpen
bool* DeviceBladeRF2::m_rxOpen private
Definition at line 60 of file devicebladerf2.h.
Referenced by closeRx(), open(), openRx(), and ~DeviceBladeRF2().
m_txOpen
bool* DeviceBladeRF2::m_txOpen private
Definition at line 61 of file devicebladerf2.h.
Referenced by closeTx(), open(), openTx(), and ~DeviceBladeRF2().
The documentation for this class was generated from the following files:
devices/bladerf2/devicebladerf2.h
devices/bladerf2/devicebladerf2.cpp