SDRAngel: FreqLockComplex Class Reference
FreqLockComplex Class Reference
#include <freqlockcomplex.h>
Public Member Functions
FreqLockComplex ()
~FreqLockComplex ()
void reset ()
void setSampleRate (unsigned int sampleRate)
void feed (float re, float im)
const std::complex< float > & getComplex () const
float getReal () const
float getImag () const
float getFreq () const
Static Private Member Functions
static float normalizeAngle (float angle)
Private Attributes
float m_a0
float m_a1
std::complex< float > m_y
float m_yRe
float m_yIm
float m_freq
float m_phi
float m_phiX0
float m_phiX1
float m_y1
Detailed Description
General purpose Phase-locked loop using complex analytic signal input.
Definition at line 31 of file freqlockcomplex.h.
Constructor & Destructor Documentation
FreqLockComplex()
FreqLockComplex::FreqLockComplex ()
Definition at line 28 of file freqlockcomplex.cpp.
                                  :
     m_a0(0.998),
     m_a1(0.002),
     m_y(1.0, 0.0),
     m_yRe(1.0),
     m_yIm(0.0),
     m_freq(0.0),
     m_phi(0.0),
     m_phiX0(0.0),
     m_phiX1(0.0),
     m_y1(0.0f)
 {
 }
~FreqLockComplex()
FreqLockComplex::~FreqLockComplex ()
Definition at line 42 of file freqlockcomplex.cpp.
 {
 }
Member Function Documentation
feed()
void FreqLockComplex::feed (float re, float im)
Feed PLL with a new signa sample
Definition at line 66 of file freqlockcomplex.cpp.
References arg(), cos(), m_a0, m_a1, m_freq, m_phi, m_phiX0, m_phiX1, m_y, m_y1, m_yIm, m_yRe, normalizeAngle(), and sin().
Referenced by ChannelAnalyzer::processOneSample(), and FreqTracker::processOneSample().
 {
     m_yRe = cos(m_phi);
     m_yIm = sin(m_phi);
     m_y.real(m_yRe);
     m_y.imag(m_yIm);
     std::complex<float> x(re, im);
     m_phiX0 = std::arg(x);
     float eF = normalizeAngle(m_phiX0 - m_phiX1);
     float fHat = m_a1*eF + m_a0*m_y1;
     m_y1 = fHat;
     m_freq = fHat; // correct instantaneous frequency
     m_phi += fHat; // advance phase with instantaneous frequency
     m_phiX1 = m_phiX0;
 }
getComplex()
const std::complex<float>& FreqLockComplex::getComplex () const inline
Definition at line 41 of file freqlockcomplex.h.
Referenced by ChannelAnalyzer::processOneSample().
 { return m_y; }
getFreq()
float FreqLockComplex::getFreq () const inline
Definition at line 44 of file freqlockcomplex.h.
Referenced by FreqTracker::getFrequency(), and ChannelAnalyzer::getPllFrequency().
 { return m_freq; }
getImag()
float FreqLockComplex::getImag () const inline
Definition at line 43 of file freqlockcomplex.h.
 { return m_yIm; }
getReal()
float FreqLockComplex::getReal () const inline
Definition at line 42 of file freqlockcomplex.h.
 { return m_yRe; }
normalizeAngle()
float FreqLockComplex::normalizeAngle (float angle) static private
Normalize angle in radians into the [-pi,+pi] region
Definition at line 84 of file freqlockcomplex.cpp.
References M_PI.
Referenced by feed().
 {
     while (angle <= -M_PI) {
         angle += 2.0*M_PI;
     }
     while (angle > M_PI) {
         angle -= 2.0*M_PI;
     }
     return angle;
 }
reset()
void FreqLockComplex::reset ()
Definition at line 46 of file freqlockcomplex.cpp.
References m_freq, m_phi, m_phiX0, m_phiX1, m_y, m_y1, m_yIm, and m_yRe.
Referenced by ChannelAnalyzer::applySettings(), FreqTracker::applySettings(), and setSampleRate().
 {
     m_y.real(1.0);
     m_y.imag(0.0);
     m_yRe = 1.0f;
     m_yIm = 0.0f;
     m_freq = 0.0f;
     m_phi = 0.0f;
     m_phiX0 = 0.0f;
     m_phiX1 = 0.0f;
     m_y1 = 0.0f;
 }
setSampleRate()
void FreqLockComplex::setSampleRate (unsigned int sampleRate)
Definition at line 59 of file freqlockcomplex.cpp.
References m_a0, m_a1, and reset().
Referenced by ChannelAnalyzer::applyChannelSettings(), ChannelAnalyzer::applySettings(), and FreqTracker::configureChannelizer().
 {
     m_a1 = 10.0f / sampleRate; // 1 - alpha
     m_a0 = 1.0f - m_a1; // alpha
     reset();
 }
Member Data Documentation
m_a0
float FreqLockComplex::m_a0 private
Definition at line 50 of file freqlockcomplex.h.
Referenced by feed(), and setSampleRate().
m_a1
float FreqLockComplex::m_a1 private
Definition at line 51 of file freqlockcomplex.h.
Referenced by feed(), and setSampleRate().
m_freq
float FreqLockComplex::m_freq private
Definition at line 55 of file freqlockcomplex.h.
Referenced by feed(), and reset().
m_phi
float FreqLockComplex::m_phi private
Definition at line 56 of file freqlockcomplex.h.
Referenced by feed(), and reset().
m_phiX0
float FreqLockComplex::m_phiX0 private
Definition at line 57 of file freqlockcomplex.h.
Referenced by feed(), and reset().
m_phiX1
float FreqLockComplex::m_phiX1 private
Definition at line 58 of file freqlockcomplex.h.
Referenced by feed(), and reset().
m_y
std::complex<float> FreqLockComplex::m_y private
Definition at line 52 of file freqlockcomplex.h.
Referenced by feed(), and reset().
m_y1
float FreqLockComplex::m_y1 private
Definition at line 59 of file freqlockcomplex.h.
Referenced by feed(), and reset().
m_yIm
float FreqLockComplex::m_yIm private
Definition at line 54 of file freqlockcomplex.h.
Referenced by feed(), and reset().
m_yRe
float FreqLockComplex::m_yRe private
Definition at line 53 of file freqlockcomplex.h.
Referenced by feed(), and reset().
The documentation for this class was generated from the following files:
sdrbase/dsp/freqlockcomplex.h
sdrbase/dsp/freqlockcomplex.cpp