SDRAngel: CSocket Class Reference
CSocket Class Reference
#include <UDPSocket.h>
Public Types
enum SocketType { TcpSocket = SOCK_STREAM, UdpSocket = SOCK_DGRAM, UnknownSocketType =-1 }
enum NetworkLayerProtocol { IPv4Protocol = AF_INET, IPv6Protocol = AF_INET6, UnknownNetworkLayerProtocol = -1 }
enum ReadResult { DATA_ARRIVED = 0, DATA_TIMED_OUT = ETIMEDOUT, DATA_EXCEPTION = 255 }
Public Member Functions
virtual ~CSocket ()
string GetLocalAddress ()
unsigned short GetLocalPort ()
void BindLocalPort (unsigned short localPort)
void BindLocalAddressAndPort (const string &localAddress, unsigned short localPort=0)
unsigned long int GetReadBufferSize ()
void SetReadBufferSize (unsigned int nSize)
void SetNonBlocking (bool bBlocking)
void ConnectToHost (const string &foreignAddress, unsigned short foreignPort)
void Send (const void *buffer, int bufferLen)
int Recv (void *buffer, int bufferLen)
string GetPeerAddress ()
unsigned short GetPeerPort ()
CSocket & operator<< (const string &sStr)
CSocket & operator>> (string &sStr)
virtual int OnDataRead (unsigned long timeToWait=ULONG_MAX)
void SetBindToDevice (const string &sInterface)
Protected Member Functions
CSocket (SocketType type, NetworkLayerProtocol protocol)
CSocket (int sockDesc)
Static Protected Member Functions
static void FillAddr (const string &localAddress, unsigned short localPort, sockaddr_in &localAddr)
Protected Attributes
int m_sockDesc
Private Member Functions
CSocket (const CSocket &sock)
void operator= (const CSocket &sock)
Detailed Description
Base class representing basic communication endpoint.
Definition at line 77 of file UDPSocket.h.
Member Enumeration Documentation
NetworkLayerProtocol
enum CSocket::NetworkLayerProtocol
Enum to represent type network layer protocol used for socket
Enumerator
IPv4Protocol
IPv6Protocol
UnknownNetworkLayerProtocol
Definition at line 95 of file UDPSocket.h.
     {
         IPv4Protocol = AF_INET,
         IPv6Protocol = AF_INET6,
         UnknownNetworkLayerProtocol = -1
     };
ReadResult
enum CSocket::ReadResult
Enum to represent Wait Result when reading data from a socket
Enumerator
DATA_ARRIVED
DATA_TIMED_OUT
DATA_EXCEPTION
Definition at line 105 of file UDPSocket.h.
     {
        DATA_ARRIVED   = 0,
        DATA_TIMED_OUT = ETIMEDOUT,
        DATA_EXCEPTION = 255
     };
SocketType
enum CSocket::SocketType
Enum to represent type of socket(UDP or TCP)
Enumerator
TcpSocket
UdpSocket
UnknownSocketType
Definition at line 85 of file UDPSocket.h.
     {
         TcpSocket = SOCK_STREAM,
         UdpSocket = SOCK_DGRAM,
         UnknownSocketType =-1
     };
Constructor & Destructor Documentation
~CSocket()
CSocket::~CSocket () virtual
Definition at line 47 of file UDPSocket.cpp.
 {
     ::close(m_sockDesc);
     m_sockDesc = -1;
 }
CSocket() [1/3]
CSocket::CSocket (SocketType type, NetworkLayerProtocol protocol) protected
Definition at line 53 of file UDPSocket.cpp.
References m_sockDesc.
                                                                 :m_sockDesc(-1)
 {
     m_sockDesc = socket(protocol, type, 0);
     if (m_sockDesc < 0)
     {
         throw CSocketException("Socket creation failed (socket())", true);
     }
 }
CSocket() [2/3]
CSocket::CSocket (int sockDesc) protected
Definition at line 62 of file UDPSocket.cpp.
References m_sockDesc.
 {
     m_sockDesc = sockDesc;
 }
CSocket() [3/3]
CSocket::CSocket (const CSocket & sock) private
Definition at line 67 of file UDPSocket.cpp.
References m_sockDesc.
 {
     m_sockDesc = sock.m_sockDesc;
 }
Member Function Documentation
BindLocalAddressAndPort()
void CSocket::BindLocalAddressAndPort (const string & localAddress, unsigned short localPort = 0)
Set the local port to the specified port and the local address to the specified address. If you omit the port, a random port will be selected.
Parameters
localAddress local address
localPort local port
Exceptions
CSocketException thrown if setting local port or address fails
Definition at line 113 of file UDPSocket.cpp.
References FillAddr(), and m_sockDesc.
Referenced by UDPSocket::UDPSocket().
 {
     // Get the address of the requested host
     sockaddr_in localAddr;
     FillAddr(localAddress, localPort, localAddr);
     if (bind(m_sockDesc, (sockaddr *) &localAddr, sizeof(sockaddr_in)) < 0) {
         throw CSocketException("Set of local address and port failed (bind())", true);
     }
 }
BindLocalPort()
void CSocket::BindLocalPort (unsigned short localPort)
Set the local port to the specified port and the local address to any interface
Parameters
localPort local port
Exceptions
CSocketException thrown if setting local port fails
Definition at line 99 of file UDPSocket.cpp.
References m_sockDesc.
Referenced by UDPSocket::UDPSocket().
 {
     // Bind the socket to its port
     sockaddr_in localAddr;
     memset(&localAddr, 0, sizeof(localAddr));
     localAddr.sin_family = AF_INET;
     localAddr.sin_addr.s_addr = htonl(INADDR_ANY);
     localAddr.sin_port = htons(localPort);
     if (bind(m_sockDesc, (sockaddr *) &localAddr, sizeof(sockaddr_in)) < 0) {
         throw CSocketException("Set of local port failed (bind())", true);
     }
 }
ConnectToHost()
void CSocket::ConnectToHost (const string & foreignAddress, unsigned short foreignPort)
Establish a socket connection with the given foreign address and port
Parameters
foreignAddress foreign address (IP address or name)
foreignPort foreign port
Exceptions
SocketException thrown if unable to establish connection
Definition at line 176 of file UDPSocket.cpp.
References FillAddr(), and m_sockDesc.
 {
     // Get the address of the requested host
     sockaddr_in destAddr;
     FillAddr(foreignAddress, foreignPort, destAddr);
     // Try to connect to the given port
     if (::connect(m_sockDesc, (sockaddr *) &destAddr, sizeof(destAddr)) < 0) {
         throw CSocketException("Connect failed (connect())", true);
     }
 }
FillAddr()
void CSocket::FillAddr (const string & localAddress, unsigned short localPort, sockaddr_in & localAddr) static protected
Definition at line 124 of file UDPSocket.cpp.
Referenced by BindLocalAddressAndPort(), ConnectToHost(), and UDPSocket::SendDataGram().
 {
     memset(&localAddr, 0, sizeof(localAddr));  // Zero out address structure
     localAddr.sin_family = AF_INET;       // Internet address
     hostent *host;  // Resolve name
     if ((host = gethostbyname(localAddress.c_str())) == NULL) {
         // strerror() will not work for gethostbyname() and hstrerror()
         // is supposedly obsolete
         throw CSocketException("Failed to resolve name (gethostbyname())");
     }
     localAddr.sin_addr.s_addr = *((unsigned long *) host->h_addr_list[0]);
     localAddr.sin_port = htons(localPort);     // Assign port in network byte order
 }
GetLocalAddress()
std::string CSocket::GetLocalAddress ()
Get the local address
Returns
local address of socket
Exceptions
CSocketException thrown if fetch fails
Definition at line 77 of file UDPSocket.cpp.
References m_sockDesc.
 {
     sockaddr_in addr;
     unsigned int addr_len = sizeof(addr);
     if (getsockname(m_sockDesc, (sockaddr *) &addr, (socklen_t *) &addr_len) < 0) {
         throw CSocketException("Fetch of local address failed (getsockname())", true);
     }
     return inet_ntoa(addr.sin_addr);
 }
GetLocalPort()
unsigned short CSocket::GetLocalPort ()
Get the local port
Returns
local port of socket
Exceptions
CSocketException thrown if fetch fails
Definition at line 88 of file UDPSocket.cpp.
References m_sockDesc.
 {
     sockaddr_in addr;
     unsigned int addr_len = sizeof(addr);
     if (getsockname(m_sockDesc, (sockaddr *) &addr, (socklen_t *) &addr_len) < 0) {
         throw CSocketException("Fetch of local port failed (getsockname())", true);
     }
     return ntohs(addr.sin_port);
 }
GetPeerAddress()
std::string CSocket::GetPeerAddress ()
Get the foreign address. Call connect() before calling recv()
Returns
foreign address
Exceptions
SocketException thrown if unable to fetch foreign address
Definition at line 206 of file UDPSocket.cpp.
References m_sockDesc.
 {
     sockaddr_in addr;
     unsigned int addr_len = sizeof(addr);
     if (getpeername(m_sockDesc, (sockaddr *) &addr,(socklen_t *) &addr_len) < 0) {
         throw CSocketException("Fetch of foreign address failed (getpeername())", true);
     }
     return inet_ntoa(addr.sin_addr);
 }
GetPeerPort()
unsigned short CSocket::GetPeerPort ()
Get the foreign port. Call connect() before calling recv()
Returns
foreign port
Exceptions
SocketException thrown if unable to fetch foreign port
Definition at line 217 of file UDPSocket.cpp.
References m_sockDesc.
 {
     sockaddr_in addr;
     unsigned int addr_len = sizeof(addr);
     if (getpeername(m_sockDesc, (sockaddr *) &addr, (socklen_t *) &addr_len) < 0) {
         throw CSocketException("Fetch of foreign port failed (getpeername())", true);
     }
     return ntohs(addr.sin_port);
 }
GetReadBufferSize()
unsigned long int CSocket::GetReadBufferSize ()
Returns the size of the internal read buffer. This limits the amount of data that the client can receive before you call
Definition at line 140 of file UDPSocket.cpp.
References m_sockDesc.
Referenced by operator>>().
 {
     unsigned long int nSize;
     socklen_t n = sizeof(nSize);
     getsockopt(m_sockDesc,SOL_SOCKET,SO_RCVBUF,(void *)&nSize, (&n));
     // now the variable nSize will have the socket size
     return nSize;
 }
OnDataRead()
int CSocket::OnDataRead (unsigned long timeToWait = ULONG_MAX) virtual
Blocking function to check whether data arrived in socket for reading.
Parameters
timeToWait waits for 'timeToWait' seconds.
Definition at line 243 of file UDPSocket.cpp.
References DATA_ARRIVED, DATA_EXCEPTION, DATA_TIMED_OUT, and m_sockDesc.
 {
     /* master file descriptor list */
     fd_set master;
     /* temp file descriptor list for select() */
     fd_set read_fds;
     /* maximum file descriptor number */
     int fdmax;
     /* clear the master and temp sets */
     FD_ZERO(&master);
     FD_ZERO(&read_fds);
     /* add the listener to the master set */
     FD_SET(m_sockDesc, &master);
     /* keep track of the biggest file descriptor */
     fdmax = m_sockDesc; /* so far, it's this one*/
     /* copy it */
     read_fds = master;
     int nRet;
     if (timeToWait == ULONG_MAX)
     {
         nRet  = select(fdmax+1, &read_fds, NULL, NULL, NULL);
         if (nRet == -1)
             nRet = DATA_EXCEPTION;
         else if (nRet > 0)
             nRet = DATA_ARRIVED;
     }
     else
     {
         struct timeval       timeout;
         timeout.tv_sec  = timeToWait;
         timeout.tv_usec = 0;
         nRet = select(fdmax+1, &read_fds, NULL, NULL, &timeout);
         if (nRet == -1)
             nRet = DATA_EXCEPTION;
         else if (nRet > 0)
             nRet = DATA_ARRIVED;
         else if(nRet == 0)
             nRet = DATA_TIMED_OUT;
     }
     return nRet;
 }
operator<<()
CSocket & CSocket::operator<< (const string & sStr)
Writing sStr to socket
Definition at line 228 of file UDPSocket.cpp.
References Send().
 {
      Send(sStr.c_str(), sStr.length());
      return *this;
 }
operator=()
void CSocket::operator= (const CSocket & sock) private
Definition at line 72 of file UDPSocket.cpp.
References m_sockDesc.
 {
     m_sockDesc = sock.m_sockDesc;
 }
operator>>()
CSocket & CSocket::operator>> (string & sStr)
Reading data to sStr from socket
Definition at line 234 of file UDPSocket.cpp.
References GetReadBufferSize(), and Recv().
 {
     char *buff = new char[GetReadBufferSize()];
     Recv(buff, GetReadBufferSize());
     sStr.append(buff);
     delete [] buff;
     return *this;
 }
Recv()
int CSocket::Recv (void * buffer, int bufferLen)
Read into the given buffer up to bufferLen bytes data from this socket. Call connect() before calling recv()
Parameters
buffer buffer to receive the data
bufferLen maximum number of bytes to read into buffer
Returns
number of bytes read, 0 for EOF, and -1 for error
Exceptions
SocketException thrown if unable to receive data
Definition at line 195 of file UDPSocket.cpp.
References m_sockDesc.
Referenced by operator>>().
 {
     int nBytes;
     if ((nBytes = ::recv(m_sockDesc, (void *) buffer, bufferLen, 0)) < 0) {
         throw CSocketException("Received failed (recv())", true);
     }
     char* sData = static_cast<char *>(buffer);
     sData[nBytes] = '\0';
     return nBytes;
 }
Send()
void CSocket::Send (const void * buffer, int bufferLen)
Write the given buffer to this socket. Call connect() before calling send()
Parameters
buffer buffer to be written
bufferLen number of bytes from buffer to be written
Exceptions
SocketException thrown if unable to send data
Definition at line 188 of file UDPSocket.cpp.
References m_sockDesc.
Referenced by operator<<().
 {
     if (::send(m_sockDesc, (void *) buffer, bufferLen, 0) < 0) {
         throw CSocketException("Send failed (send())", true);
     }
 }
SetBindToDevice()
void CSocket::SetBindToDevice (const string & sInterface)
To Bind socket to a symbolic device name like eth0
Parameters
sInterface NIC device name
Definition at line 292 of file UDPSocket.cpp.
 {
     struct ifreq ifr;
     memset(&ifr, 0, sizeof(ifr));
     snprintf(ifr.ifr_name, sizeof(ifr.ifr_name), "%s", sInterface.c_str());
 }
SetNonBlocking()
void CSocket::SetNonBlocking (bool bBlocking)
Sets the socket to Blocking/Non blocking state.
Parameters
Bool flag for Non blocking status.
Definition at line 157 of file UDPSocket.cpp.
References m_sockDesc.
 {
     int opts;
     opts = fcntl ( m_sockDesc, F_GETFL );
     if ( opts < 0 )
     {
         return;
     }
     if ( bBlocking )
         opts = ( opts | O_NONBLOCK );
     else
         opts = ( opts & ~O_NONBLOCK );
     fcntl ( m_sockDesc, F_SETFL,opts );
 }
SetReadBufferSize()
void CSocket::SetReadBufferSize (unsigned int nSize)
Sets the read buffer size of the socket.
Parameters
Size of the buffer.
Definition at line 149 of file UDPSocket.cpp.
References m_sockDesc.
 {
     if (setsockopt(m_sockDesc, SOL_SOCKET, SO_RCVBUF, &nSize, sizeof(nSize)) == -1)
     {
         throw CSocketException("Error in setting socket buffer size ", true);
     }
 }
Member Data Documentation
m_sockDesc
int CSocket::m_sockDesc protected
Internal Socket descriptor
Definition at line 235 of file UDPSocket.h.
Referenced by BindLocalAddressAndPort(), BindLocalPort(), ConnectToHost(), CSocket(), UDPSocket::DisconnectFromHost(), GetLocalAddress(), GetLocalPort(), GetPeerAddress(), GetPeerPort(), GetReadBufferSize(), UDPSocket::JoinGroup(), UDPSocket::LeaveGroup(), OnDataRead(), operator=(), Recv(), UDPSocket::RecvDataGram(), Send(), UDPSocket::SendDataGram(), UDPSocket::SetBroadcast(), UDPSocket::SetMulticastTTL(), SetNonBlocking(), and SetReadBufferSize().
The documentation for this class was generated from the following files:
plugins/samplesink/remoteoutput/UDPSocket.h
plugins/samplesink/remoteoutput/UDPSocket.cpp