SDRAngel: LocalOutput::MsgReportSampleRateAndFrequency Class Reference
LocalOutput::MsgReportSampleRateAndFrequency Class Reference
#include <localoutput.h>
Public Member Functions
int getSampleRate () const
int getCenterFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportSampleRateAndFrequency * create (int sampleRate, qint64 centerFrequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportSampleRateAndFrequency (int sampleRate, qint64 centerFrequency)
Protected Attributes
int m_sampleRate
qint64 m_centerFrequency
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 84 of file localoutput.h.
Constructor & Destructor Documentation
MsgReportSampleRateAndFrequency()
LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency (int sampleRate, qint64 centerFrequency) inline protected
Definition at line 99 of file localoutput.h.
References LocalOutput::deserialize(), LocalOutput::destroy(), LocalOutput::getCenterFrequency(), LocalOutput::getDeviceDescription(), LocalOutput::getSampleRate(), LocalOutput::getStartingTimeStamp(), LocalOutput::handleMessage(), LocalOutput::init(), LocalOutput::LocalOutput(), LocalOutput::serialize(), LocalOutput::setCenterFrequency(), LocalOutput::setMessageQueueToGUI(), LocalOutput::setSampleRate(), LocalOutput::start(), LocalOutput::stop(), LocalOutput::webapiReportGet(), LocalOutput::webapiRun(), LocalOutput::webapiRunGet(), LocalOutput::webapiSettingsGet(), LocalOutput::webapiSettingsPutPatch(), and LocalOutput::~LocalOutput().
                                                                                 :
             Message(),
             m_sampleRate(sampleRate),
             m_centerFrequency(centerFrequency)
         { }
Member Function Documentation
create()
static MsgReportSampleRateAndFrequency* LocalOutput::MsgReportSampleRateAndFrequency::create (int sampleRate, qint64 centerFrequency) inline static
Definition at line 91 of file localoutput.h.
Referenced by LocalOutput::setCenterFrequency(), and LocalOutput::setSampleRate().
{
             return new MsgReportSampleRateAndFrequency(sampleRate, centerFrequency);
         }
getCenterFrequency()
int LocalOutput::MsgReportSampleRateAndFrequency::getCenterFrequency () const inline
Definition at line 89 of file localoutput.h.
References LocalOutput::m_centerFrequency.
Referenced by LocalOutputGui::handleMessage().
 { return m_centerFrequency; }
getSampleRate()
int LocalOutput::MsgReportSampleRateAndFrequency::getSampleRate () const inline
Definition at line 88 of file localoutput.h.
References LocalOutput::m_sampleRate.
Referenced by LocalOutputGui::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_centerFrequency
qint64 LocalOutput::MsgReportSampleRateAndFrequency::m_centerFrequency protected
Definition at line 97 of file localoutput.h.
m_sampleRate
int LocalOutput::MsgReportSampleRateAndFrequency::m_sampleRate protected
Definition at line 96 of file localoutput.h.
The documentation for this class was generated from the following file:
plugins/samplesink/localoutput/localoutput.h