SDRAngel: UDPSourceMessages::MsgSampleRateCorrection Class Reference
UDPSourceMessages::MsgSampleRateCorrection Class Reference
#include <udpsourcemsg.h>
Public Member Functions
float getCorrectionFactor () const
float getRawDeltaRatio () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgSampleRateCorrection * create (float correctionFactor, float rawDeltaRatio)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgSampleRateCorrection (float correctionFactor, float rawDeltaRatio)
Private Attributes
float m_correctionFactor
float m_rawDeltaRatio
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 29 of file udpsourcemsg.h.
Constructor & Destructor Documentation
MsgSampleRateCorrection()
UDPSourceMessages::MsgSampleRateCorrection::MsgSampleRateCorrection (float correctionFactor, float rawDeltaRatio) inline private
Definition at line 45 of file udpsourcemsg.h.
Referenced by create().
                                                                              :
             Message(),
             m_correctionFactor(correctionFactor),
             m_rawDeltaRatio(rawDeltaRatio)
         { }
Member Function Documentation
create()
static MsgSampleRateCorrection* UDPSourceMessages::MsgSampleRateCorrection::create (float correctionFactor, float rawDeltaRatio) inline static
Definition at line 36 of file udpsourcemsg.h.
References MsgSampleRateCorrection().
Referenced by UDPSourceUDPHandler::advanceReadPointer().
         {
             return new MsgSampleRateCorrection(correctionFactor, rawDeltaRatio);
         }
getCorrectionFactor()
float UDPSourceMessages::MsgSampleRateCorrection::getCorrectionFactor () const inline
Definition at line 33 of file udpsourcemsg.h.
References m_correctionFactor.
Referenced by UDPSource::handleMessage().
 { return m_correctionFactor; }
getRawDeltaRatio()
float UDPSourceMessages::MsgSampleRateCorrection::getRawDeltaRatio () const inline
Definition at line 34 of file udpsourcemsg.h.
References m_rawDeltaRatio.
Referenced by UDPSource::handleMessage().
 { return m_rawDeltaRatio; }
Member Data Documentation
m_correctionFactor
float UDPSourceMessages::MsgSampleRateCorrection::m_correctionFactor private
Definition at line 42 of file udpsourcemsg.h.
Referenced by getCorrectionFactor().
m_rawDeltaRatio
float UDPSourceMessages::MsgSampleRateCorrection::m_rawDeltaRatio private
Definition at line 43 of file udpsourcemsg.h.
Referenced by getRawDeltaRatio().
The documentation for this class was generated from the following file:
plugins/channeltx/udpsource/udpsourcemsg.h