SDRAngel: RemoteSourceThread Class Reference
RemoteSourceThread Class Reference
#include <remotesourcethread.h>
Inherits QThread.
Classes
class MsgDataBind
class MsgStartStop
Public Member Functions
RemoteSourceThread (RemoteDataQueue *dataQueue, QObject *parent=0)
~RemoteSourceThread ()
void startStop (bool start)
void dataBind (const QString &address, uint16_t port)
Private Slots
void handleInputMessages ()
void readPendingDatagrams ()
Private Member Functions
void startWork ()
void stopWork ()
void run ()
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
volatile bool m_running
MessageQueue m_inputMessageQueue
RemoteDataQueue * m_dataQueue
QHostAddress m_address
QUdpSocket * m_socket
RemoteDataBlock * m_dataBlocks [m_nbDataBlocks]
ring buffer of data blocks indexed by frame affinity
Static Private Attributes
static const uint32_t m_nbDataBlocks = 4
number of data blocks in the ring buffer
Detailed Description
Definition at line 33 of file remotesourcethread.h.
Constructor & Destructor Documentation
RemoteSourceThread()
RemoteSourceThread::RemoteSourceThread (RemoteDataQueue * dataQueue, QObject * parent = 0)
Definition at line 32 of file remotesourcethread.cpp.
Referenced by RemoteSourceThread::MsgDataBind::MsgDataBind().
                                                                                   :
     QThread(parent),
     m_running(false),
     m_dataQueue(dataQueue),
     m_address(QHostAddress::LocalHost),
     m_socket(0)
 {
     std::fill(m_dataBlocks, m_dataBlocks+4, (RemoteDataBlock *) 0);
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
 }
~RemoteSourceThread()
RemoteSourceThread::~RemoteSourceThread ()
Definition at line 43 of file remotesourcethread.cpp.
Referenced by RemoteSourceThread::MsgDataBind::MsgDataBind().
 {
     qDebug("RemoteSourceThread::~RemoteSourceThread");
 }
Member Function Documentation
dataBind()
void RemoteSourceThread::dataBind (const QString & address, uint16_t port)
Definition at line 54 of file remotesourcethread.cpp.
References RemoteSourceThread::MsgDataBind::create(), m_inputMessageQueue, and MessageQueue::push().
Referenced by RemoteSource::applySettings(), RemoteSourceThread::MsgDataBind::MsgDataBind(), and RemoteSource::start().
 {
     MsgDataBind *msg = MsgDataBind::create(address, port);
     m_inputMessageQueue.push(msg);
 }
handleInputMessages
void RemoteSourceThread::handleInputMessages () private slot
Definition at line 96 of file remotesourcethread.cpp.
References RemoteSourceThread::MsgDataBind::getAddress(), RemoteSourceThread::MsgDataBind::getPort(), RemoteSourceThread::MsgStartStop::getStartStop(), m_inputMessageQueue, m_socket, Message::match(), MessageQueue::pop(), readPendingDatagrams(), startWork(), and stopWork().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (MsgStartStop::match(*message))
         {
             MsgStartStop* notif = (MsgStartStop*) message;
             qDebug("RemoteSourceThread::handleInputMessages: MsgStartStop: %s", notif->getStartStop() ? "start" : "stop");
             if (notif->getStartStop()) {
                 startWork();
             } else {
                 stopWork();
             }
             delete message;
         }
         else if (MsgDataBind::match(*message))
         {
             MsgDataBind* notif = (MsgDataBind*) message;
             qDebug("RemoteSourceThread::handleInputMessages: MsgDataBind: %s:%d", qPrintable(notif->getAddress().toString()), notif->getPort());
             if (m_socket)
             {
                 disconnect(m_socket, SIGNAL(readyRead()), this, SLOT(readPendingDatagrams()));
                 m_socket->bind(notif->getAddress(), notif->getPort());
                 connect(m_socket, SIGNAL(readyRead()), this, SLOT(readPendingDatagrams()));
             }
         }
     }
 }
readPendingDatagrams
void RemoteSourceThread::readPendingDatagrams () private slot
Definition at line 130 of file remotesourcethread.cpp.
References m_dataBlocks, m_dataQueue, RemoteRxControlBlock::m_frameIndex, RemoteRxControlBlock::m_metaRetrieved, m_nbDataBlocks, RemoteDataBlock::m_rxControlBlock, m_socket, RemoteDataBlock::m_superBlocks, and RemoteDataQueue::push().
Referenced by handleInputMessages().
 {
     RemoteSuperBlock superBlock;
     qint64 size;
     while (m_socket->hasPendingDatagrams())
     {
         QHostAddress sender;
         quint16 senderPort = 0;
         //qint64 pendingDataSize = m_socket->pendingDatagramSize();
         size = m_socket->readDatagram((char *) &superBlock, (long long int) sizeof(RemoteSuperBlock), &sender, &senderPort);
         if (size == sizeof(RemoteSuperBlock))
         {
             unsigned int dataBlockIndex = superBlock.m_header.m_frameIndex % m_nbDataBlocks;
             // create the first block for this index
             if (m_dataBlocks[dataBlockIndex] == 0) {
                 m_dataBlocks[dataBlockIndex] = new RemoteDataBlock();
             }
             if (m_dataBlocks[dataBlockIndex]->m_rxControlBlock.m_frameIndex < 0)
             {
                 // initialize virgin block with the frame index
                 m_dataBlocks[dataBlockIndex]->m_rxControlBlock.m_frameIndex = superBlock.m_header.m_frameIndex;
             }
             else
             {
                 // if the frame index is not the same for the same slot it means we are starting a new frame
                 uint32_t frameIndex = m_dataBlocks[dataBlockIndex]->m_rxControlBlock.m_frameIndex;
                 if (superBlock.m_header.m_frameIndex != frameIndex)
                 {
                     //qDebug("RemoteSourceThread::readPendingDatagrams: push frame %u", frameIndex);
                     m_dataQueue->push(m_dataBlocks[dataBlockIndex]);
                     m_dataBlocks[dataBlockIndex] = new RemoteDataBlock();
                     m_dataBlocks[dataBlockIndex]->m_rxControlBlock.m_frameIndex = superBlock.m_header.m_frameIndex;
                 }
             }
             m_dataBlocks[dataBlockIndex]->m_superBlocks[superBlock.m_header.m_blockIndex] = superBlock;
             if (superBlock.m_header.m_blockIndex == 0) {
                 m_dataBlocks[dataBlockIndex]->m_rxControlBlock.m_metaRetrieved = true;
             }
             if (superBlock.m_header.m_blockIndex < RemoteNbOrginalBlocks) {
                 m_dataBlocks[dataBlockIndex]->m_rxControlBlock.m_originalCount++;
             } else {
                 m_dataBlocks[dataBlockIndex]->m_rxControlBlock.m_recoveryCount++;
             }
             m_dataBlocks[dataBlockIndex]->m_rxControlBlock.m_blockCount++;
         }
         else
         {
             qWarning("RemoteSourceThread::readPendingDatagrams: wrong super block size not processing");
         }
     }
 }
run()
void RemoteSourceThread::run () private
Definition at line 80 of file remotesourcethread.cpp.
References m_running, and m_startWaiter.
 {
     qDebug("RemoteSourceThread::run: begin");
     m_running = true;
     m_startWaiter.wakeAll();
     while (m_running)
     {
         sleep(1); // Do nothing as everything is in the data handler (dequeuer)
     }
     m_running = false;
     qDebug("RemoteSourceThread::run: end");
 }
startStop()
void RemoteSourceThread::startStop (bool start)
Definition at line 48 of file remotesourcethread.cpp.
References RemoteSourceThread::MsgStartStop::create(), m_inputMessageQueue, and MessageQueue::push().
Referenced by RemoteSourceThread::MsgDataBind::MsgDataBind(), RemoteSource::start(), and RemoteSource::stop().
 {
     MsgStartStop *msg = MsgStartStop::create(start);
     m_inputMessageQueue.push(msg);
 }
startWork()
void RemoteSourceThread::startWork () private
Definition at line 60 of file remotesourcethread.cpp.
References m_running, m_socket, m_startWaiter, and m_startWaitMutex.
Referenced by handleInputMessages().
 {
     qDebug("RemoteSourceThread::startWork");
     m_startWaitMutex.lock();
     m_socket = new QUdpSocket(this);
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void RemoteSourceThread::stopWork () private
Definition at line 71 of file remotesourcethread.cpp.
References m_running, and m_socket.
Referenced by handleInputMessages().
 {
     qDebug("RemoteSourceThread::stopWork");
     delete m_socket;
     m_socket = 0;
     m_running = false;
     wait();
 }
Member Data Documentation
m_address
QHostAddress RemoteSourceThread::m_address private
Definition at line 92 of file remotesourcethread.h.
Referenced by RemoteSourceThread::MsgDataBind::getAddress().
m_dataBlocks
RemoteDataBlock* RemoteSourceThread::m_dataBlocks[m_nbDataBlocks] private
ring buffer of data blocks indexed by frame affinity
Definition at line 96 of file remotesourcethread.h.
Referenced by readPendingDatagrams().
m_dataQueue
RemoteDataQueue* RemoteSourceThread::m_dataQueue private
Definition at line 90 of file remotesourcethread.h.
Referenced by readPendingDatagrams().
m_inputMessageQueue
MessageQueue RemoteSourceThread::m_inputMessageQueue private
Definition at line 89 of file remotesourcethread.h.
Referenced by dataBind(), handleInputMessages(), and startStop().
m_nbDataBlocks
const uint32_t RemoteSourceThread::m_nbDataBlocks = 4 static private
number of data blocks in the ring buffer
Definition at line 95 of file remotesourcethread.h.
Referenced by readPendingDatagrams().
m_running
volatile bool RemoteSourceThread::m_running private
Definition at line 87 of file remotesourcethread.h.
Referenced by run(), startWork(), and stopWork().
m_socket
QUdpSocket* RemoteSourceThread::m_socket private
Definition at line 93 of file remotesourcethread.h.
Referenced by handleInputMessages(), readPendingDatagrams(), startWork(), and stopWork().
m_startWaiter
QWaitCondition RemoteSourceThread::m_startWaiter private
Definition at line 86 of file remotesourcethread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex RemoteSourceThread::m_startWaitMutex private
Definition at line 85 of file remotesourcethread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/channeltx/remotesource/remotesourcethread.h
plugins/channeltx/remotesource/remotesourcethread.cpp