SDRAngel: qrtplib::RTCPSDESPacket Class Reference
qrtplib::RTCPSDESPacket Class Reference
#include <rtcpsdespacket.h>
Public Types
enum ItemType {
None, CNAME, NAME, EMAIL,
PHONE, LOC, TOOL, NOTE,
PRIV, Unknown
}
Public Types inherited from qrtplib::RTCPPacket
enum PacketType {
SR, RR, SDES, BYE,
APP, Unknown
}
Public Member Functions
RTCPSDESPacket (uint8_t *data, std::size_t datalen)
~RTCPSDESPacket ()
int GetChunkCount () const
bool GotoFirstChunk ()
bool GotoNextChunk ()
uint32_t GetChunkSSRC () const
bool GotoFirstItem ()
bool GotoNextItem ()
ItemType GetItemType () const
std::size_t GetItemLength () const
uint8_t * GetItemData ()
std::size_t GetPRIVPrefixLength () const
uint8_t * GetPRIVPrefixData ()
std::size_t GetPRIVValueLength () const
uint8_t * GetPRIVValueData ()
Public Member Functions inherited from qrtplib::RTCPPacket
virtual ~RTCPPacket ()
bool IsKnownFormat () const
PacketType GetPacketType () const
uint8_t * GetPacketData ()
std::size_t GetPacketLength () const
Private Attributes
RTPEndian m_endian
uint8_t * currentchunk
int curchunknum
std::size_t itemoffset
Additional Inherited Members
Protected Member Functions inherited from qrtplib::RTCPPacket
RTCPPacket (PacketType t, uint8_t *d, std::size_t dlen)
Protected Attributes inherited from qrtplib::RTCPPacket
uint8_t * data
std::size_t datalen
bool knownformat
Detailed Description
Describes an RTCP source description packet.
Definition at line 55 of file rtcpsdespacket.h.
Member Enumeration Documentation
ItemType
enum qrtplib::RTCPSDESPacket::ItemType
Identifies the type of an SDES item.
Enumerator
None
Used when the iteration over the items has finished.
CNAME
Used for a CNAME (canonical name) item.
NAME
Used for a NAME item.
EMAIL
Used for an EMAIL item.
PHONE
Used for a PHONE item.
LOC
Used for a LOC (location) item.
TOOL
Used for a TOOL item.
NOTE
Used for a NOTE item.
PRIV
Used for a PRIV item.
Unknown
Used when there is an item present, but the type is not recognized.
Definition at line 59 of file rtcpsdespacket.h.
     {
         None,
         CNAME,
         NAME,
         EMAIL,
         PHONE,
         LOC,
         TOOL,
         NOTE,
         PRIV,
         Unknown
     };
Constructor & Destructor Documentation
RTCPSDESPacket()
qrtplib::RTCPSDESPacket::RTCPSDESPacket (uint8_t * data, std::size_t datalen)
Creates an instance based on the data in data with length datalen. Creates an instance based on the data in data with length datalen. Since the data pointer is referenced inside the class (no copy of the data is made) one must make sure that the memory it points to is valid as long as the class instance exists.
Definition at line 38 of file rtcpsdespacket.cpp.
References qrtplib::RTCPCommonHeader::count, curchunknum, currentchunk, itemoffset, qrtplib::RTCPPacket::knownformat, qrtplib::RTCPSDESHeader::length, qrtplib::RTCPCommonHeader::padding, and qrtplib::RTCPSDESHeader::sdesid.
                                                                   :
         RTCPPacket(SDES, data, datalength)
 {
     knownformat = false;
     currentchunk = 0;
     itemoffset = 0;
     curchunknum = 0;
     RTCPCommonHeader *hdr = (RTCPCommonHeader *) data;
     std::size_t len = datalength;
     if (hdr->padding)
     {
         uint8_t padcount = data[datalength - 1];
         if ((padcount & 0x03) != 0) // not a multiple of four! (see rfc 3550 p 37)
             return;
         if (((std::size_t) padcount) >= len)
             return;
         len -= (std::size_t) padcount;
     }
     if (hdr->count == 0)
     {
         if (len != sizeof(RTCPCommonHeader))
             return;
     }
     else
     {
         int ssrccount = (int) (hdr->count);
         uint8_t *chunk;
         int chunkoffset;
         if (len < sizeof(RTCPCommonHeader))
             return;
         len -= sizeof(RTCPCommonHeader);
         chunk = data + sizeof(RTCPCommonHeader);
         while ((ssrccount > 0) && (len > 0))
         {
             if (len < (sizeof(uint32_t) * 2)) // chunk must contain at least a SSRC identifier
                 return;                  // and a (possibly empty) item
             len -= sizeof(uint32_t);
             chunkoffset = sizeof(uint32_t);
             bool done = false;
             while (!done)
             {
                 if (len < 1) // at least a zero byte (end of item list) should be there
                     return;
                 RTCPSDESHeader *sdeshdr = (RTCPSDESHeader *) (chunk + chunkoffset);
                 if (sdeshdr->sdesid == 0) // end of item list
                 {
                     len--;
                     chunkoffset++;
                     std::size_t r = (chunkoffset & 0x03);
                     if (r != 0)
                     {
                         std::size_t addoffset = 4 - r;
                         if (addoffset > len)
                             return;
                         len -= addoffset;
                         chunkoffset += addoffset;
                     }
                     done = true;
                 }
                 else
                 {
                     if (len < sizeof(RTCPSDESHeader))
                         return;
                     len -= sizeof(RTCPSDESHeader);
                     chunkoffset += sizeof(RTCPSDESHeader);
                     std::size_t itemlen = (std::size_t)(sdeshdr->length);
                     if (itemlen > len)
                         return;
                     len -= itemlen;
                     chunkoffset += itemlen;
                 }
             }
             ssrccount--;
             chunk += chunkoffset;
         }
         // check for remaining bytes
         if (len > 0)
             return;
         if (ssrccount > 0)
             return;
     }
     knownformat = true;
 }
~RTCPSDESPacket()
qrtplib::RTCPSDESPacket::~RTCPSDESPacket () inline
Definition at line 79 of file rtcpsdespacket.h.
     {
     }
Member Function Documentation
GetChunkCount()
int qrtplib::RTCPSDESPacket::GetChunkCount () const inline
Returns the number of SDES chunks in the SDES packet. Returns the number of SDES chunks in the SDES packet. Each chunk has its own SSRC identifier.
Definition at line 154 of file rtcpsdespacket.h.
References qrtplib::RTCPCommonHeader::count.
 {
     if (!knownformat)
         return 0;
     RTCPCommonHeader *hdr = (RTCPCommonHeader *) data;
     return ((int) hdr->count);
 }
GetChunkSSRC()
uint32_t qrtplib::RTCPSDESPacket::GetChunkSSRC () const inline
Returns the SSRC identifier of the current chunk.
Definition at line 202 of file rtcpsdespacket.h.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     if (currentchunk == 0)
         return 0;
     uint32_t *ssrc = (uint32_t *) currentchunk;
     return m_endian.qToHost(*ssrc);
 }
GetItemData()
uint8_t * qrtplib::RTCPSDESPacket::GetItemData () inline
Returns the item data of the current item in the current chunk.
Definition at line 291 of file rtcpsdespacket.h.
References qrtplib::RTCPSDESHeader::sdesid.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     if (currentchunk == 0)
         return 0;
     RTCPSDESHeader *sdeshdr = (RTCPSDESHeader *) (currentchunk + itemoffset);
     if (sdeshdr->sdesid == 0)
         return 0;
     return (currentchunk + itemoffset + sizeof(RTCPSDESHeader));
 }
GetItemLength()
std::size_t qrtplib::RTCPSDESPacket::GetItemLength () const inline
Returns the item length of the current item in the current chunk.
Definition at line 279 of file rtcpsdespacket.h.
References qrtplib::RTCPSDESHeader::length, Unit::None, and qrtplib::RTCPSDESHeader::sdesid.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return None;
     if (currentchunk == 0)
         return None;
     RTCPSDESHeader *sdeshdr = (RTCPSDESHeader *) (currentchunk + itemoffset);
     if (sdeshdr->sdesid == 0)
         return 0;
     return (std::size_t)(sdeshdr->length);
 }
GetItemType()
RTCPSDESPacket::ItemType qrtplib::RTCPSDESPacket::GetItemType () const inline
Returns the SDES item type of the current item in the current chunk.
Definition at line 246 of file rtcpsdespacket.h.
References Unit::None, RTCP_SDES_ID_CNAME, RTCP_SDES_ID_EMAIL, RTCP_SDES_ID_LOCATION, RTCP_SDES_ID_NAME, RTCP_SDES_ID_NOTE, RTCP_SDES_ID_PHONE, RTCP_SDES_ID_PRIVATE, RTCP_SDES_ID_TOOL, and qrtplib::RTCPSDESHeader::sdesid.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return None;
     if (currentchunk == 0)
         return None;
     RTCPSDESHeader *sdeshdr = (RTCPSDESHeader *) (currentchunk + itemoffset);
     switch (sdeshdr->sdesid)
     {
     case 0:
         return None;
     case RTCP_SDES_ID_CNAME:
         return CNAME;
     case RTCP_SDES_ID_NAME:
         return NAME;
     case RTCP_SDES_ID_EMAIL:
         return EMAIL;
     case RTCP_SDES_ID_PHONE:
         return PHONE;
     case RTCP_SDES_ID_LOCATION:
         return LOC;
     case RTCP_SDES_ID_TOOL:
         return TOOL;
     case RTCP_SDES_ID_NOTE:
         return NOTE;
     case RTCP_SDES_ID_PRIVATE:
         return PRIV;
     default:
         return Unknown;
     }
     return Unknown;
 }
GetPRIVPrefixData()
uint8_t * qrtplib::RTCPSDESPacket::GetPRIVPrefixData () inline
If the current item is an SDES PRIV item, this function returns actual data of the prefix string.
Definition at line 322 of file rtcpsdespacket.h.
References qrtplib::RTCPSDESHeader::length, RTCP_SDES_ID_PRIVATE, and qrtplib::RTCPSDESHeader::sdesid.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     if (currentchunk == 0)
         return 0;
     RTCPSDESHeader *sdeshdr = (RTCPSDESHeader *) (currentchunk + itemoffset);
     if (sdeshdr->sdesid != RTCP_SDES_ID_PRIVATE)
         return 0;
     if (sdeshdr->length == 0)
         return 0;
     uint8_t *preflen = currentchunk + itemoffset + sizeof(RTCPSDESHeader);
     std::size_t prefixlength = (std::size_t)(*preflen);
     if (prefixlength > (std::size_t)((sdeshdr->length) - 1))
         return 0;
     if (prefixlength == 0)
         return 0;
     return (currentchunk + itemoffset + sizeof(RTCPSDESHeader) + 1);
 }
GetPRIVPrefixLength()
std::size_t qrtplib::RTCPSDESPacket::GetPRIVPrefixLength () const inline
If the current item is an SDES PRIV item, this function returns the length of the prefix string of the private item.
Definition at line 304 of file rtcpsdespacket.h.
References qrtplib::RTCPSDESHeader::length, RTCP_SDES_ID_PRIVATE, and qrtplib::RTCPSDESHeader::sdesid.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     if (currentchunk == 0)
         return 0;
     RTCPSDESHeader *sdeshdr = (RTCPSDESHeader *) (currentchunk + itemoffset);
     if (sdeshdr->sdesid != RTCP_SDES_ID_PRIVATE)
         return 0;
     if (sdeshdr->length == 0)
         return 0;
     uint8_t *preflen = currentchunk + itemoffset + sizeof(RTCPSDESHeader);
     std::size_t prefixlength = (std::size_t)(*preflen);
     if (prefixlength > (std::size_t)((sdeshdr->length) - 1))
         return 0;
     return prefixlength;
 }
GetPRIVValueData()
uint8_t * qrtplib::RTCPSDESPacket::GetPRIVValueData () inline
If the current item is an SDES PRIV item, this function returns actual value data of the private item.
Definition at line 360 of file rtcpsdespacket.h.
References qrtplib::RTCPSDESHeader::length, RTCP_SDES_ID_PRIVATE, and qrtplib::RTCPSDESHeader::sdesid.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     if (currentchunk == 0)
         return 0;
     RTCPSDESHeader *sdeshdr = (RTCPSDESHeader *) (currentchunk + itemoffset);
     if (sdeshdr->sdesid != RTCP_SDES_ID_PRIVATE)
         return 0;
     if (sdeshdr->length == 0)
         return 0;
     uint8_t *preflen = currentchunk + itemoffset + sizeof(RTCPSDESHeader);
     std::size_t prefixlength = (std::size_t)(*preflen);
     if (prefixlength > (std::size_t)((sdeshdr->length) - 1))
         return 0;
     std::size_t valuelen = ((std::size_t)(sdeshdr->length)) - prefixlength - 1;
     if (valuelen == 0)
         return 0;
     return (currentchunk + itemoffset + sizeof(RTCPSDESHeader) + 1 + prefixlength);
 }
GetPRIVValueLength()
std::size_t qrtplib::RTCPSDESPacket::GetPRIVValueLength () const inline
If the current item is an SDES PRIV item, this function returns the length of the value string of the private item.
Definition at line 342 of file rtcpsdespacket.h.
References qrtplib::RTCPSDESHeader::length, RTCP_SDES_ID_PRIVATE, and qrtplib::RTCPSDESHeader::sdesid.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     if (currentchunk == 0)
         return 0;
     RTCPSDESHeader *sdeshdr = (RTCPSDESHeader *) (currentchunk + itemoffset);
     if (sdeshdr->sdesid != RTCP_SDES_ID_PRIVATE)
         return 0;
     if (sdeshdr->length == 0)
         return 0;
     uint8_t *preflen = currentchunk + itemoffset + sizeof(RTCPSDESHeader);
     std::size_t prefixlength = (std::size_t)(*preflen);
     if (prefixlength > (std::size_t)((sdeshdr->length) - 1))
         return 0;
     return ((std::size_t)(sdeshdr->length)) - prefixlength - 1;
 }
GotoFirstChunk()
bool qrtplib::RTCPSDESPacket::GotoFirstChunk () inline
Starts the iteration over the chunks. Starts the iteration. If no SDES chunks are present, the function returns false. Otherwise, it returns true and sets the current chunk to be the first chunk.
Definition at line 162 of file rtcpsdespacket.h.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (GetChunkCount() == 0)
     {
         currentchunk = 0;
         return false;
     }
     currentchunk = data + sizeof(RTCPCommonHeader);
     curchunknum = 1;
     itemoffset = sizeof(uint32_t);
     return true;
 }
GotoFirstItem()
bool qrtplib::RTCPSDESPacket::GotoFirstItem () inline
Starts the iteration over the SDES items in the current chunk. Starts the iteration over the SDES items in the current chunk. If no SDES items are present, the function returns false. Otherwise, the function sets the current item to be the first one and returns true.
Definition at line 212 of file rtcpsdespacket.h.
References qrtplib::RTCPSDESHeader::sdesid.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return false;
     if (currentchunk == 0)
         return false;
     itemoffset = sizeof(uint32_t);
     RTCPSDESHeader *sdeshdr = (RTCPSDESHeader *) (currentchunk + itemoffset);
     if (sdeshdr->sdesid == 0)
         return false;
     return true;
 }
GotoNextChunk()
bool qrtplib::RTCPSDESPacket::GotoNextChunk () inline
Sets the current chunk to the next available chunk. Sets the current chunk to the next available chunk. If no next chunk is present, this function returns false, otherwise it returns true.
Definition at line 175 of file rtcpsdespacket.h.
References qrtplib::RTCPSDESHeader::length, and qrtplib::RTCPSDESHeader::sdesid.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return false;
     if (currentchunk == 0)
         return false;
     if (curchunknum == GetChunkCount())
         return false;
     std::size_t offset = sizeof(uint32_t);
     RTCPSDESHeader *sdeshdr = (RTCPSDESHeader *) (currentchunk + sizeof(uint32_t));
     while (sdeshdr->sdesid != 0)
     {
         offset += sizeof(RTCPSDESHeader);
         offset += (std::size_t)(sdeshdr->length);
         sdeshdr = (RTCPSDESHeader *) (currentchunk + offset);
     }
     offset++; // for the zero byte
     if ((offset & 0x03) != 0)
         offset += (4 - (offset & 0x03));
     currentchunk += offset;
     curchunknum++;
     itemoffset = sizeof(uint32_t);
     return true;
 }
GotoNextItem()
bool qrtplib::RTCPSDESPacket::GotoNextItem () inline
Advances the iteration to the next item in the current chunk. If there's another item in the chunk, the current item is set to be the next one and the function returns true. Otherwise, the function returns false.
Definition at line 225 of file rtcpsdespacket.h.
References qrtplib::RTCPSDESHeader::length, and qrtplib::RTCPSDESHeader::sdesid.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return false;
     if (currentchunk == 0)
         return false;
     RTCPSDESHeader *sdeshdr = (RTCPSDESHeader *) (currentchunk + itemoffset);
     if (sdeshdr->sdesid == 0)
         return false;
     std::size_t offset = itemoffset;
     offset += sizeof(RTCPSDESHeader);
     offset += (std::size_t)(sdeshdr->length);
     sdeshdr = (RTCPSDESHeader *) (currentchunk + offset);
     if (sdeshdr->sdesid == 0)
         return false;
     itemoffset = offset;
     return true;
 }
Member Data Documentation
curchunknum
int qrtplib::RTCPSDESPacket::curchunknum private
Definition at line 150 of file rtcpsdespacket.h.
Referenced by RTCPSDESPacket().
currentchunk
uint8_t* qrtplib::RTCPSDESPacket::currentchunk private
Definition at line 149 of file rtcpsdespacket.h.
Referenced by RTCPSDESPacket().
itemoffset
std::size_t qrtplib::RTCPSDESPacket::itemoffset private
Definition at line 151 of file rtcpsdespacket.h.
Referenced by RTCPSDESPacket().
m_endian
RTPEndian qrtplib::RTCPSDESPacket::m_endian private
Definition at line 148 of file rtcpsdespacket.h.
The documentation for this class was generated from the following files:
qrtplib/rtcpsdespacket.h
qrtplib/rtcpsdespacket.cpp