SDRAngel: AudioG722 Class Reference
AudioG722 Class Reference
#include <audiog722.h>
Classes
struct g722_encode_state
Public Member Functions
AudioG722 ()
~AudioG722 ()
void init (int rate, int options)
int encode (uint8_t g722_data[], const int16_t amp[], int len)
Private Member Functions
int16_t saturate (int32_t amp)
void block4 (int band, int d)
Private Attributes
g722_encode_state state
Static Private Attributes
static const int q6 [32]
static const int iln [32]
static const int ilp [32]
static const int wl [8]
static const int rl42 [16]
static const int ilb [32]
static const int qm4 [16]
static const int qm2 [4]
static const int qmf_coeffs [12]
static const int ihn [3] = {0, 1, 0}
static const int ihp [3] = {0, 3, 2}
static const int wh [3] = {0, -214, 798}
static const int rh2 [4] = {2, 1, 2, 1}
Detailed Description
Definition at line 25 of file audiog722.h.
Constructor & Destructor Documentation
AudioG722()
AudioG722::AudioG722 ()
Definition at line 125 of file audiog722.cpp.
 {}
~AudioG722()
AudioG722::~AudioG722 ()
Definition at line 128 of file audiog722.cpp.
 {}
Member Function Documentation
block4()
void AudioG722::block4 (int band, int d) private
Definition at line 136 of file audiog722.cpp.
References AudioG722::g722_encode_state::a, AudioG722::g722_encode_state::ap, AudioG722::g722_encode_state::b, AudioG722::g722_encode_state::band, AudioG722::g722_encode_state::bp, AudioG722::g722_encode_state::d, i, AudioG722::g722_encode_state::p, AudioG722::g722_encode_state::r, AudioG722::g722_encode_state::s, saturate(), AudioG722::g722_encode_state::sg, AudioG722::g722_encode_state::sp, state, and AudioG722::g722_encode_state::sz.
Referenced by encode().
 {
     int wd1;
     int wd2;
     int wd3;
     int i;
     /* Block 4, RECONS */
     state.band[band].d[0] = d;
     state.band[band].r[0] = saturate(state.band[band].s + d);
     /* Block 4, PARREC */
     state.band[band].p[0] = saturate(state.band[band].sz + d);
     /* Block 4, UPPOL2 */
     for (i = 0;  i < 3;  i++) {
         state.band[band].sg[i] = state.band[band].p[i] >> 15;
     }
     wd1 = saturate(state.band[band].a[1] << 2);
     wd2 = (state.band[band].sg[0] == state.band[band].sg[1])  ?  -wd1  :  wd1;
     if (wd2 > 32767) {
         wd2 = 32767;
     }
     wd3 = (wd2 >> 7) + ((state.band[band].sg[0] == state.band[band].sg[2])  ?  128  :  -128);
     wd3 += (state.band[band].a[2]*32512) >> 15;
     if (wd3 > 12288) {
         wd3 = 12288;
     } else if (wd3 < -12288) {
         wd3 = -12288;
     }
     state.band[band].ap[2] = wd3;
     /* Block 4, UPPOL1 */
     state.band[band].sg[0] = state.band[band].p[0] >> 15;
     state.band[band].sg[1] = state.band[band].p[1] >> 15;
     wd1 = (state.band[band].sg[0] == state.band[band].sg[1])  ?  192  :  -192;
     wd2 = (state.band[band].a[1]*32640) >> 15;
     state.band[band].ap[1] = saturate(wd1 + wd2);
     wd3 = saturate(15360 - state.band[band].ap[2]);
     if (state.band[band].ap[1] > wd3) {
         state.band[band].ap[1] = wd3;
     } else if (state.band[band].ap[1] < -wd3) {
         state.band[band].ap[1] = -wd3;
     }
     /* Block 4, UPZERO */
     wd1 = (d == 0)  ?  0  :  128;
     state.band[band].sg[0] = d >> 15;
     for (i = 1;  i < 7;  i++)
     {
         state.band[band].sg[i] = state.band[band].d[i] >> 15;
         wd2 = (state.band[band].sg[i] == state.band[band].sg[0])  ?  wd1  :  -wd1;
         wd3 = (state.band[band].b[i]*32640) >> 15;
         state.band[band].bp[i] = saturate(wd2 + wd3);
     }
     /* Block 4, DELAYA */
     for (i = 6;  i > 0;  i--)
     {
         state.band[band].d[i] = state.band[band].d[i - 1];
         state.band[band].b[i] = state.band[band].bp[i];
     }
     for (i = 2;  i > 0;  i--)
     {
         state.band[band].r[i] = state.band[band].r[i - 1];
         state.band[band].p[i] = state.band[band].p[i - 1];
         state.band[band].a[i] = state.band[band].ap[i];
     }
     /* Block 4, FILTEP */
     wd1 = saturate(state.band[band].r[1] + state.band[band].r[1]);
     wd1 = (state.band[band].a[1]*wd1) >> 15;
     wd2 = saturate(state.band[band].r[2] + state.band[band].r[2]);
     wd2 = (state.band[band].a[2]*wd2) >> 15;
     state.band[band].sp = saturate(wd1 + wd2);
     /* Block 4, FILTEZ */
     state.band[band].sz = 0;
     for (i = 6;  i > 0;  i--)
     {
         wd1 = saturate(state.band[band].d[i] + state.band[band].d[i]);
         state.band[band].sz += (state.band[band].b[i]*wd1) >> 15;
     }
     state.band[band].sz = saturate(state.band[band].sz);
     /* Block 4, PREDIC */
     state.band[band].s = saturate(state.band[band].sp + state.band[band].sz);
 }
encode()
int AudioG722::encode (uint8_t g722_data[], const int16_t amp[], int len)
Definition at line 236 of file audiog722.cpp.
References AudioG722::g722_encode_state::band, AudioG722::g722_encode_state::bits_per_sample, block4(), AudioG722::g722_encode_state::det, AudioG722::g722_encode_state::eight_k, i, ihn, ihp, ilb, iln, ilp, AudioG722::g722_encode_state::itu_test_mode, AudioG722::g722_encode_state::nb, AudioG722::g722_encode_state::out_bits, AudioG722::g722_encode_state::out_buffer, AudioG722::g722_encode_state::packed, q6, qm2, qm4, qmf_coeffs, rh2, rl42, AudioG722::g722_encode_state::s, saturate(), state, wh, wl, and AudioG722::g722_encode_state::x.
Referenced by AudioNetSink::write().
 {
     int dlow;
     int dhigh;
     int el;
     int wd;
     int wd1;
     int ril;
     int wd2;
     int il4;
     int ih2;
     int wd3;
     int eh;
     int mih;
     int i;
     int j;
     /* Low and high band PCM from the QMF */
     int xlow;
     int xhigh;
     int g722_bytes;
     /* Even and odd tap accumulators */
     int sumeven;
     int sumodd;
     int ihigh;
     int ilow;
     int code;
     g722_bytes = 0;
     xhigh = 0;
     for (j = 0;  j < len;  )
     {
         if (state.itu_test_mode)
         {
             xhigh = amp[j++] >> 1;
             xlow = xhigh;
         }
         else
         {
             if (state.eight_k)
             {
                 xlow = amp[j++] >> 1;
             }
             else
             {
                 /* Apply the transmit QMF */
                 /* Shuffle the buffer down */
                 for (i = 0;  i < 22;  i++) {
                     state.x[i] = state.x[i + 2];
                 }
                 state.x[22] = amp[j++];
                 state.x[23] = amp[j++];
                 /* Discard every other QMF output */
                 sumeven = 0;
                 sumodd = 0;
                 for (i = 0;  i < 12;  i++)
                 {
                     sumodd += state.x[2*i]*qmf_coeffs[i];
                     sumeven += state.x[2*i + 1]*qmf_coeffs[11 - i];
                 }
                 xlow = (sumeven + sumodd) >> 14;
                 xhigh = (sumeven - sumodd) >> 14;
             }
         }
         /* Block 1L, SUBTRA */
         el = saturate(xlow - state.band[0].s);
         /* Block 1L, QUANTL */
         wd = (el >= 0)  ?  el  :  -(el + 1);
         for (i = 1;  i < 30;  i++)
         {
             wd1 = (q6[i]*state.band[0].det) >> 12;
             if (wd < wd1) {
                 break;
             }
         }
         ilow = (el < 0)  ?  iln[i]  :  ilp[i];
         /* Block 2L, INVQAL */
         ril = ilow >> 2;
         wd2 = qm4[ril];
         dlow = (state.band[0].det*wd2) >> 15;
         /* Block 3L, LOGSCL */
         il4 = rl42[ril];
         wd = (state.band[0].nb*127) >> 7;
         state.band[0].nb = wd + wl[il4];
         if (state.band[0].nb < 0) {
             state.band[0].nb = 0;
         } else if (state.band[0].nb > 18432) {
             state.band[0].nb = 18432;
         }
         /* Block 3L, SCALEL */
         wd1 = (state.band[0].nb >> 6) & 31;
         wd2 = 8 - (state.band[0].nb >> 11);
         wd3 = (wd2 < 0)  ?  (ilb[wd1] << -wd2)  :  (ilb[wd1] >> wd2);
         state.band[0].det = wd3 << 2;
         block4(0, dlow);
         if (state.eight_k)
         {
             /* Just leave the high bits as zero */
             code = (0xC0 | ilow) >> (8 - state.bits_per_sample);
         }
         else
         {
             /* Block 1H, SUBTRA */
             eh = saturate(xhigh - state.band[1].s);
             /* Block 1H, QUANTH */
             wd = (eh >= 0)  ?  eh  :  -(eh + 1);
             wd1 = (564*state.band[1].det) >> 12;
             mih = (wd >= wd1)  ?  2  :  1;
             ihigh = (eh < 0)  ?  ihn[mih]  :  ihp[mih];
             /* Block 2H, INVQAH */
             wd2 = qm2[ihigh];
             dhigh = (state.band[1].det*wd2) >> 15;
             /* Block 3H, LOGSCH */
             ih2 = rh2[ihigh];
             wd = (state.band[1].nb*127) >> 7;
             state.band[1].nb = wd + wh[ih2];
             if (state.band[1].nb < 0) {
                 state.band[1].nb = 0;
             } else if (state.band[1].nb > 22528) {
                 state.band[1].nb = 22528;
             }
             /* Block 3H, SCALEH */
             wd1 = (state.band[1].nb >> 6) & 31;
             wd2 = 10 - (state.band[1].nb >> 11);
             wd3 = (wd2 < 0)  ?  (ilb[wd1] << -wd2)  :  (ilb[wd1] >> wd2);
             state.band[1].det = wd3 << 2;
             block4(1, dhigh);
             code = ((ihigh << 6) | ilow) >> (8 - state.bits_per_sample);
         }
         if (state.packed)
         {
             /* Pack the code bits */
             state.out_buffer |= (code << state.out_bits);
             state.out_bits += state.bits_per_sample;
             if (state.out_bits >= 8)
             {
                 g722_data[g722_bytes++] = (uint8_t) (state.out_buffer & 0xFF);
                 state.out_bits -= 8;
                 state.out_buffer >>= 8;
             }
         }
         else
         {
             g722_data[g722_bytes++] = (uint8_t) code;
         }
     }
     return g722_bytes;
 }
init()
void AudioG722::init (int rate, int options)
Definition at line 131 of file audiog722.cpp.
References AudioG722::g722_encode_state::init(), and state.
 {
     state.init(rate, options);
 }
saturate()
int16_t AudioG722::saturate (int32_t amp) inline private
Definition at line 75 of file audiog722.h.
Referenced by block4(), and encode().
     {
         int16_t amp16;
         /* Hopefully this is optimized for the common case - not clipping */
         amp16 = (int16_t) amp;
         if (amp == amp16) {
             return amp16;
         }
         if (amp > INT16_MAX) {
             return  INT16_MAX;
         }
         return  INT16_MIN;
     }
Member Data Documentation
ihn
const int AudioG722::ihn = {0, 1, 0} static private
Definition at line 105 of file audiog722.h.
Referenced by encode().
ihp
const int AudioG722::ihp = {0, 3, 2} static private
Definition at line 106 of file audiog722.h.
Referenced by encode().
ilb
const int AudioG722::ilb static private
Initial value:
=
{
    2048, 2093, 2139, 2186, 2233, 2282, 2332,
    2383, 2435, 2489, 2543, 2599, 2656, 2714,
    2774, 2834, 2896, 2960, 3025, 3091, 3158,
    3228, 3298, 3371, 3444, 3520, 3597, 3676,
    3756, 3838, 3922, 4008
}
Definition at line 101 of file audiog722.h.
Referenced by encode().
iln
const int AudioG722::iln static private
Initial value:
=
{
     0, 63, 62, 31, 30, 29, 28, 27,
    26, 25, 24, 23, 22, 21, 20, 19,
    18, 17, 16, 15, 14, 13, 12, 11,
    10,  9,  8,  7,  6,  5,  4,  0
}
Definition at line 97 of file audiog722.h.
Referenced by encode().
ilp
const int AudioG722::ilp static private
Initial value:
=
{
     0, 61, 60, 59, 58, 57, 56, 55,
    54, 53, 52, 51, 50, 49, 48, 47,
    46, 45, 44, 43, 42, 41, 40, 39,
    38, 37, 36, 35, 34, 33, 32,  0
}
Definition at line 98 of file audiog722.h.
Referenced by encode().
q6
const int AudioG722::q6 static private
Initial value:
=
{
       0,   35,   72,  110,  150,  190,  233,  276,
     323,  370,  422,  473,  530,  587,  650,  714,
     786,  858,  940, 1023, 1121, 1219, 1339, 1458,
    1612, 1765, 1980, 2195, 2557, 2919,    0,    0
}
Definition at line 96 of file audiog722.h.
Referenced by encode().
qm2
const int AudioG722::qm2 static private
Initial value:
=
{
    -7408,  -1616,   7408,   1616
}
Definition at line 103 of file audiog722.h.
Referenced by encode().
qm4
const int AudioG722::qm4 static private
Initial value:
=
{
         0, -20456, -12896, -8968,
     -6288,  -4240,  -2584, -1200,
     20456,  12896,   8968,  6288,
      4240,   2584,   1200,     0
}
Definition at line 102 of file audiog722.h.
Referenced by encode().
qmf_coeffs
const int AudioG722::qmf_coeffs static private
Initial value:
=
{
       3,  -11,   12,   32, -210,  951, 3876, -805,  362, -156,   53,  -11,
}
Definition at line 104 of file audiog722.h.
Referenced by encode().
rh2
const int AudioG722::rh2 = {2, 1, 2, 1} static private
Definition at line 108 of file audiog722.h.
Referenced by encode().
rl42
const int AudioG722::rl42 static private
Initial value:
=
{
    0, 7, 6, 5, 4, 3, 2, 1, 7, 6, 5, 4, 3, 2, 1, 0
}
Definition at line 100 of file audiog722.h.
Referenced by encode().
state
g722_encode_state AudioG722::state private
Definition at line 94 of file audiog722.h.
Referenced by block4(), encode(), and init().
wh
const int AudioG722::wh = {0, -214, 798} static private
Definition at line 107 of file audiog722.h.
Referenced by encode().
wl
const int AudioG722::wl static private
Initial value:
=
{
    -60, -30, 58, 172, 334, 538, 1198, 3042
}
Definition at line 99 of file audiog722.h.
Referenced by encode().
The documentation for this class was generated from the following files:
sdrbase/audio/audiog722.h
sdrbase/audio/audiog722.cpp