SDRAngel: ScopeVis::MsgScopeVisNGChangeTrace Class Reference
ScopeVis::MsgScopeVisNGChangeTrace Class Reference
Public Member Functions
const TraceData & getTraceData () const
uint32_t getTraceIndex () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgScopeVisNGChangeTrace * create (const TraceData &traceData, uint32_t traceIndex)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgScopeVisNGChangeTrace (TraceData traceData, uint32_t traceIndex)
Private Attributes
TraceData m_traceData
uint32_t m_traceIndex
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 426 of file scopevis.h.
Constructor & Destructor Documentation
MsgScopeVisNGChangeTrace()
ScopeVis::MsgScopeVisNGChangeTrace::MsgScopeVisNGChangeTrace (TraceData traceData, uint32_t traceIndex) inline private
Definition at line 443 of file scopevis.h.
                                                                            :
             m_traceData(traceData),
             m_traceIndex(traceIndex)
         {}
Member Function Documentation
create()
static MsgScopeVisNGChangeTrace* ScopeVis::MsgScopeVisNGChangeTrace::create (const TraceData & traceData, uint32_t traceIndex) inline static
Definition at line 430 of file scopevis.h.
Referenced by ScopeVis::changeTrace().
         {
             return new MsgScopeVisNGChangeTrace(traceData, traceIndex);
         }
getTraceData()
const TraceData& ScopeVis::MsgScopeVisNGChangeTrace::getTraceData () const inline
Definition at line 436 of file scopevis.h.
Referenced by ScopeVis::handleMessage().
 { return m_traceData; }
getTraceIndex()
uint32_t ScopeVis::MsgScopeVisNGChangeTrace::getTraceIndex () const inline
Definition at line 437 of file scopevis.h.
Referenced by ScopeVis::handleMessage().
 { return m_traceIndex; }
Member Data Documentation
m_traceData
TraceData ScopeVis::MsgScopeVisNGChangeTrace::m_traceData private
Definition at line 440 of file scopevis.h.
m_traceIndex
uint32_t ScopeVis::MsgScopeVisNGChangeTrace::m_traceIndex private
Definition at line 441 of file scopevis.h.
The documentation for this class was generated from the following file:
sdrgui/dsp/scopevis.h