SDRAngel: LocalOutput::MsgConfigureLocalOutput Class Reference
LocalOutput::MsgConfigureLocalOutput Class Reference
#include <localoutput.h>
Public Member Functions
const LocalOutputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureLocalOutput * create (const LocalOutputSettings &settings, bool force=false)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureLocalOutput (const LocalOutputSettings &settings, bool force)
Private Attributes
LocalOutputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 42 of file localoutput.h.
Constructor & Destructor Documentation
MsgConfigureLocalOutput()
LocalOutput::MsgConfigureLocalOutput::MsgConfigureLocalOutput (const LocalOutputSettings & settings, bool force) inline private
Definition at line 58 of file localoutput.h.
Referenced by create().
                                                                                  :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureLocalOutput* LocalOutput::MsgConfigureLocalOutput::create (const LocalOutputSettings & settings, bool force = false) inline static
Definition at line 49 of file localoutput.h.
References MsgConfigureLocalOutput().
Referenced by LocalOutput::deserialize(), LocalOutputGui::updateHardware(), and LocalOutput::webapiSettingsPutPatch().
         {
             return new MsgConfigureLocalOutput(settings, force);
         }
getForce()
bool LocalOutput::MsgConfigureLocalOutput::getForce () const inline
Definition at line 47 of file localoutput.h.
References m_force.
Referenced by LocalOutput::handleMessage().
 { return m_force; }
getSettings()
const LocalOutputSettings& LocalOutput::MsgConfigureLocalOutput::getSettings () const inline
Definition at line 46 of file localoutput.h.
References m_settings.
Referenced by LocalOutputGui::handleMessage(), and LocalOutput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool LocalOutput::MsgConfigureLocalOutput::m_force private
Definition at line 56 of file localoutput.h.
Referenced by getForce().
m_settings
LocalOutputSettings LocalOutput::MsgConfigureLocalOutput::m_settings private
Definition at line 55 of file localoutput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesink/localoutput/localoutput.h