SDRAngel: DSDDemod::MsgConfigureMyPosition Class Reference
DSDDemod::MsgConfigureMyPosition Class Reference
Public Member Functions
float getMyLatitude () const
float getMyLongitude () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureMyPosition * create (float myLatitude, float myLongitude)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureMyPosition (float myLatitude, float myLongitude)
Private Attributes
float m_myLatitude
float m_myLongitude
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 191 of file dsddemod.h.
Constructor & Destructor Documentation
MsgConfigureMyPosition()
DSDDemod::MsgConfigureMyPosition::MsgConfigureMyPosition (float myLatitude, float myLongitude) inline private
Definition at line 207 of file dsddemod.h.
                                                                     :
             m_myLatitude(myLatitude),
             m_myLongitude(myLongitude)
         {}
Member Function Documentation
create()
static MsgConfigureMyPosition* DSDDemod::MsgConfigureMyPosition::create (float myLatitude, float myLongitude) inline static
Definition at line 198 of file dsddemod.h.
Referenced by DSDDemod::configureMyPosition().
         {
             return new MsgConfigureMyPosition(myLatitude, myLongitude);
         }
getMyLatitude()
float DSDDemod::MsgConfigureMyPosition::getMyLatitude () const inline
Definition at line 195 of file dsddemod.h.
Referenced by DSDDemod::handleMessage().
 { return m_myLatitude; }
getMyLongitude()
float DSDDemod::MsgConfigureMyPosition::getMyLongitude () const inline
Definition at line 196 of file dsddemod.h.
Referenced by DSDDemod::handleMessage().
 { return m_myLongitude; }
Member Data Documentation
m_myLatitude
float DSDDemod::MsgConfigureMyPosition::m_myLatitude private
Definition at line 204 of file dsddemod.h.
m_myLongitude
float DSDDemod::MsgConfigureMyPosition::m_myLongitude private
Definition at line 205 of file dsddemod.h.
The documentation for this class was generated from the following file:
plugins/channelrx/demoddsd/dsddemod.h