SDRAngel: KiwiSDRWorker Class Reference
KiwiSDRWorker Class Reference
#include <kiwisdrworker.h>
Inherits QObject.
Public Slots
void onCenterFrequencyChanged (quint64 centerFrequency)
void onServerAddressChanged (QString serverAddress)
void onGainChanged (quint32 gain, bool useAGC)
Signals
void updateStatus (int status)
Public Member Functions
KiwiSDRWorker (SampleSinkFifo *sampleFifo)
int getStatus () const
Private Slots
void onConnected ()
void onDisconnected ()
void onBinaryMessageReceived (const QByteArray &message)
void onSocketError (QAbstractSocket::SocketError error)
void tick ()
Private Member Functions
void sendCenterFrequency ()
void sendGain ()
Private Attributes
QTimer m_timer
QWebSocket m_webSocket
SampleVector m_samplesBuf
SampleSinkFifo * m_sampleFifo
QString m_serverAddress
uint64_t m_centerFrequency
uint32_t m_gain
bool m_useAGC
int m_status
See GUI for status number detail.
Detailed Description
Definition at line 26 of file kiwisdrworker.h.
Constructor & Destructor Documentation
KiwiSDRWorker()
KiwiSDRWorker::KiwiSDRWorker (SampleSinkFifo * sampleFifo)
Definition at line 21 of file kiwisdrworker.cpp.
References m_timer, m_webSocket, onBinaryMessageReceived(), onConnected(), onDisconnected(), onSocketError(), and tick().
     : QObject(),
     m_timer(this),
     m_sampleFifo(sampleFifo),
     m_samplesBuf(),
     m_centerFrequency(1450000),
     m_gain(20),
     m_useAGC(true),
     m_status(0)
 {
     connect(&m_timer, SIGNAL(timeout()), this, SLOT(tick()));
     m_webSocket.setParent(this);
     connect(&m_webSocket, &QWebSocket::connected,
         this, &KiwiSDRWorker::onConnected);
     connect(&m_webSocket, &QWebSocket::binaryMessageReceived,
         this, &KiwiSDRWorker::onBinaryMessageReceived);
     connect(&m_webSocket, QOverload<QAbstractSocket::SocketError>::of(&QWebSocket::error),
         this, &KiwiSDRWorker::onSocketError);
     connect(&m_webSocket, &QWebSocket::disconnected,
         this, &KiwiSDRWorker::onDisconnected);
 }
Member Function Documentation
getStatus()
int KiwiSDRWorker::getStatus () const inline
Definition at line 31 of file kiwisdrworker.h.
References m_status.
Referenced by KiwiSDRInput::getStatus().
 { return m_status; }
onBinaryMessageReceived
void KiwiSDRWorker::onBinaryMessageReceived (const QByteArray & message) private slot
Definition at line 84 of file kiwisdrworker.cpp.
References i, m_sampleFifo, m_samplesBuf, m_status, m_timer, m_webSocket, SDR_RX_SAMP_SZ, sendCenterFrequency(), sendGain(), updateStatus(), and SampleSinkFifo::write().
Referenced by KiwiSDRWorker().
 {
     if (message[0] == 'M' && message[1] == 'S' && message[2] == 'G')
     {
         QStringList al = QString::fromUtf8(message).split(' ');
         if (al[1] == "audio_init=0" &&
             al[2] == "audio_rate=12000")
         {
             m_webSocket.sendTextMessage("SET AR OK in=12000 out=48000");
             m_webSocket.sendTextMessage("SERVER DE CLIENT KiwiAngel SND");
             sendGain();
             sendCenterFrequency();
             m_timer.start(5000);
             m_status = 2;
             emit updateStatus(2);
         }
     }
     else if (message[0] == 'S' && message[1] == 'N' && message[2] == 'D')
     {
         int dataOffset = 20;
         int sampleCount = 512;
         const int16_t* messageSamples = (const int16_t*)(message.constData() + dataOffset);
         m_samplesBuf.clear();
         for (int i = 0; i < sampleCount; i++)
         {
             m_samplesBuf.push_back(Sample(
                 boost::endian::endian_reverse(messageSamples[i * 2]) << (SDR_RX_SAMP_SZ - 16),
                 boost::endian::endian_reverse(messageSamples[i * 2 + 1]) << (SDR_RX_SAMP_SZ - 16)
             ));
         }
         m_sampleFifo->write(m_samplesBuf.begin(), m_samplesBuf.end());
     }
 }
onCenterFrequencyChanged
void KiwiSDRWorker::onCenterFrequencyChanged (quint64 centerFrequency) slot
Definition at line 120 of file kiwisdrworker.cpp.
References m_centerFrequency, and sendCenterFrequency().
Referenced by KiwiSDRInput::start().
 {
     if (m_centerFrequency == centerFrequency)
         return;
     m_centerFrequency = centerFrequency;
     sendCenterFrequency();
 }
onConnected
void KiwiSDRWorker::onConnected () private slot
Definition at line 44 of file kiwisdrworker.cpp.
References m_webSocket.
Referenced by KiwiSDRWorker().
 {
     m_webSocket.sendTextMessage("SET auth t=kiwi p=#");
 }
onDisconnected
void KiwiSDRWorker::onDisconnected () private slot
Definition at line 49 of file kiwisdrworker.cpp.
References m_status, and updateStatus().
Referenced by KiwiSDRWorker().
 {
     qDebug("KiwiSDRWorker::onDisconnected");
     m_status = 4;
     emit updateStatus(4);
 }
onGainChanged
void KiwiSDRWorker::onGainChanged (quint32 gain, bool useAGC) slot
Definition at line 129 of file kiwisdrworker.cpp.
References m_gain, m_useAGC, and sendGain().
Referenced by KiwiSDRInput::start().
 {
     if (m_gain == gain && m_useAGC == useAGC)
         return;
     m_gain = gain;
     m_useAGC = useAGC;
     sendGain();
 }
onServerAddressChanged
void KiwiSDRWorker::onServerAddressChanged (QString serverAddress) slot
Definition at line 140 of file kiwisdrworker.cpp.
References m_serverAddress, m_status, m_webSocket, and updateStatus().
Referenced by KiwiSDRInput::start().
 {
     if (m_serverAddress == serverAddress)
         return;
     m_serverAddress = serverAddress;
     m_status = 1;
     emit updateStatus(1);
     QString url("ws://");
     url.append(m_serverAddress);
     url.append("/kiwi/");
     url.append(QString::number(QDateTime::currentMSecsSinceEpoch()));
     url.append("/SND");
     m_webSocket.open(QUrl(url));
 }
onSocketError
void KiwiSDRWorker::onSocketError (QAbstractSocket::SocketError error) private slot
Definition at line 56 of file kiwisdrworker.cpp.
References m_status, and updateStatus().
Referenced by KiwiSDRWorker().
 {
     m_status = 3;
     emit updateStatus(3);
 }
sendCenterFrequency()
void KiwiSDRWorker::sendCenterFrequency () private
Definition at line 62 of file kiwisdrworker.cpp.
References m_centerFrequency, and m_webSocket.
Referenced by onBinaryMessageReceived(), and onCenterFrequencyChanged().
 {
     if (!m_webSocket.isValid())
         return;
     QString freq = QString::number(m_centerFrequency / 1000.0, 'f', 3);
     QString msg = "SET mod=iq low_cut=-5980 high_cut=5980 freq=" + freq;
     m_webSocket.sendTextMessage(msg);
 }
sendGain()
void KiwiSDRWorker::sendGain () private
Definition at line 72 of file kiwisdrworker.cpp.
References m_gain, m_useAGC, and m_webSocket.
Referenced by onBinaryMessageReceived(), and onGainChanged().
 {
     if (!m_webSocket.isValid())
         return;
     QString msg("SET agc=");
     msg.append(m_useAGC ? "1" : "0");
     msg.append(" hang=0 thresh=-130 slope=6 decay=1000 manGain=");
     msg.append(QString::number(m_gain));
     m_webSocket.sendTextMessage(msg);
 }
tick
void KiwiSDRWorker::tick () private slot
Definition at line 157 of file kiwisdrworker.cpp.
References m_webSocket.
Referenced by KiwiSDRWorker().
 {
     m_webSocket.sendTextMessage("SET keepalive");
 }
updateStatus
void KiwiSDRWorker::updateStatus (int status) signal
Referenced by onBinaryMessageReceived(), onDisconnected(), onServerAddressChanged(), onSocketError(), and KiwiSDRInput::start().
Member Data Documentation
m_centerFrequency
uint64_t KiwiSDRWorker::m_centerFrequency private
Definition at line 41 of file kiwisdrworker.h.
Referenced by onCenterFrequencyChanged(), and sendCenterFrequency().
m_gain
uint32_t KiwiSDRWorker::m_gain private
Definition at line 43 of file kiwisdrworker.h.
Referenced by onGainChanged(), and sendGain().
m_sampleFifo
SampleSinkFifo* KiwiSDRWorker::m_sampleFifo private
Definition at line 38 of file kiwisdrworker.h.
Referenced by onBinaryMessageReceived().
m_samplesBuf
SampleVector KiwiSDRWorker::m_samplesBuf private
Definition at line 37 of file kiwisdrworker.h.
Referenced by onBinaryMessageReceived().
m_serverAddress
QString KiwiSDRWorker::m_serverAddress private
Definition at line 40 of file kiwisdrworker.h.
Referenced by onServerAddressChanged().
m_status
int KiwiSDRWorker::m_status private
See GUI for status number detail.
Definition at line 46 of file kiwisdrworker.h.
Referenced by getStatus(), onBinaryMessageReceived(), onDisconnected(), onServerAddressChanged(), and onSocketError().
m_timer
QTimer KiwiSDRWorker::m_timer private
Definition at line 34 of file kiwisdrworker.h.
Referenced by KiwiSDRWorker(), and onBinaryMessageReceived().
m_useAGC
bool KiwiSDRWorker::m_useAGC private
Definition at line 44 of file kiwisdrworker.h.
Referenced by onGainChanged(), and sendGain().
m_webSocket
QWebSocket KiwiSDRWorker::m_webSocket private
Definition at line 35 of file kiwisdrworker.h.
Referenced by KiwiSDRWorker(), onBinaryMessageReceived(), onConnected(), onServerAddressChanged(), sendCenterFrequency(), sendGain(), and tick().
The documentation for this class was generated from the following files:
plugins/samplesource/kiwisdr/kiwisdrworker.h
plugins/samplesource/kiwisdr/kiwisdrworker.cpp