SDRAngel: TestSourceThread::MsgStartStop Class Reference
TestSourceThread::MsgStartStop Class Reference
#include <testsourcethread.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 44 of file testsourcethread.h.
Constructor & Destructor Documentation
MsgStartStop()
TestSourceThread::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 57 of file testsourcethread.h.
References TestSourceThread::setAMModulation(), TestSourceThread::setAmplitudeBits(), TestSourceThread::setBitSize(), TestSourceThread::setDCFactor(), TestSourceThread::setFcPos(), TestSourceThread::setFMDeviation(), TestSourceThread::setFrequencyShift(), TestSourceThread::setIFactor(), TestSourceThread::setLog2Decimation(), TestSourceThread::setModulation(), TestSourceThread::setPattern0(), TestSourceThread::setPattern1(), TestSourceThread::setPattern2(), TestSourceThread::setPhaseImbalance(), TestSourceThread::setQFactor(), TestSourceThread::setSamplerate(), TestSourceThread::setToneFrequency(), TestSourceThread::startStop(), TestSourceThread::TestSourceThread(), and TestSourceThread::~TestSourceThread().
Referenced by create().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* TestSourceThread::MsgStartStop::create (bool startStop) inline static
Definition at line 50 of file testsourcethread.h.
References MsgStartStop().
Referenced by TestSourceThread::startStop().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool TestSourceThread::MsgStartStop::getStartStop () const inline
Definition at line 48 of file testsourcethread.h.
References m_startStop.
Referenced by TestSourceThread::handleInputMessages().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool TestSourceThread::MsgStartStop::m_startStop protected
Definition at line 55 of file testsourcethread.h.
Referenced by getStartStop().
The documentation for this class was generated from the following file:
plugins/samplesource/testsource/testsourcethread.h