SDRAngel: AudioDialogX Class Reference
AudioDialogX Class Reference
#include <audiodialog.h>
Inherits QDialog.
Public Member Functions
AudioDialogX (AudioDeviceManager *audioDeviceManager, QWidget *parent=0)
~AudioDialogX ()
Public Attributes
int m_inIndex
int m_outIndex
Private Slots
void accept ()
void reject ()
void check ()
void on_audioInTree_currentItemChanged (QTreeWidgetItem *currentItem, QTreeWidgetItem *previousItem)
void on_audioOutTree_currentItemChanged (QTreeWidgetItem *currentItem, QTreeWidgetItem *previousItem)
void on_inputVolume_valueChanged (int value)
void on_inputReset_clicked (bool checked)
void on_inputCleanup_clicked (bool checked)
void on_outputUDPPort_editingFinished ()
void on_outputReset_clicked (bool checked)
void on_outputCleanup_clicked (bool checked)
void on_outputSampleRate_valueChanged (int value)
void on_decimationFactor_currentIndexChanged (int index)
void on_outputUDPChannelCodec_currentIndexChanged (int index)
void on_outputUDPChannelMode_currentIndexChanged (int index)
Private Member Functions
void updateInputDisplay ()
void updateOutputDisplay ()
void updateInputDeviceInfo ()
void updateOutputDeviceInfo ()
void updateOutputSDPString ()
Private Attributes
Ui::AudioDialog * ui
AudioDeviceManager * m_audioDeviceManager
AudioDeviceManager::InputDeviceInfo m_inputDeviceInfo
AudioDeviceManager::OutputDeviceInfo m_outputDeviceInfo
quint16 m_outputUDPPort
Detailed Description
Definition at line 15 of file audiodialog.h.
Constructor & Destructor Documentation
AudioDialogX()
AudioDialogX::AudioDialogX (AudioDeviceManager * audioDeviceManager, QWidget * parent = 0) explicit
Definition at line 28 of file audiodialog.cpp.
References AudioDeviceManager::getInputDeviceInfo(), AudioDeviceManager::getInputDevices(), AudioDeviceManager::getOutputDeviceInfo(), AudioDeviceManager::getOutputDevices(), m_audioDeviceManager, AudioDeviceManager::m_defaultDeviceName, m_inIndex, m_outIndex, m_outputUDPPort, and ui.
                                                                                   :
     QDialog(parent),
     ui(new Ui::AudioDialog),
     m_audioDeviceManager(audioDeviceManager)
 {
     ui->setupUi(this);
     QTreeWidgetItem* treeItem;
     // out panel
     AudioDeviceManager::OutputDeviceInfo outDeviceInfo;
     QAudioDeviceInfo defaultOutputDeviceInfo = QAudioDeviceInfo::defaultOutputDevice();
     treeItem = new QTreeWidgetItem(ui->audioOutTree);
     treeItem->setText(1, AudioDeviceManager::m_defaultDeviceName);
     bool found = m_audioDeviceManager->getOutputDeviceInfo(AudioDeviceManager::m_defaultDeviceName, outDeviceInfo);
     treeItem->setText(0, found ? "__" : "_D");
     ui->audioOutTree->setCurrentItem(treeItem);
     const QList<QAudioDeviceInfo>& outputDevices = m_audioDeviceManager->getOutputDevices();
     for(QList<QAudioDeviceInfo>::const_iterator it = outputDevices.begin(); it != outputDevices.end(); ++it)
     {
         treeItem = new QTreeWidgetItem(ui->audioOutTree);
         treeItem->setText(1, it->deviceName());
         bool systemDefault = it->deviceName() == defaultOutputDeviceInfo.deviceName();
         found = m_audioDeviceManager->getOutputDeviceInfo(it->deviceName(), outDeviceInfo);
         treeItem->setText(0, QString(systemDefault ? "S" : "_") + QString(found ? "_" : "D"));
         if (systemDefault) {
             treeItem->setBackground(1, QBrush(qRgb(96,96,96)));
         }
     }
     ui->audioOutTree->resizeColumnToContents(0);
     ui->audioOutTree->resizeColumnToContents(1);
     // in panel
     AudioDeviceManager::InputDeviceInfo inDeviceInfo;
     QAudioDeviceInfo defaultInputDeviceInfo = QAudioDeviceInfo::defaultInputDevice();
     treeItem = new QTreeWidgetItem(ui->audioInTree);
     treeItem->setText(1, AudioDeviceManager::m_defaultDeviceName);
     found = m_audioDeviceManager->getInputDeviceInfo(AudioDeviceManager::m_defaultDeviceName, inDeviceInfo);
     treeItem->setText(0, found ? "__" : "_D");
     ui->audioInTree->setCurrentItem(treeItem);
     const QList<QAudioDeviceInfo>& inputDevices = m_audioDeviceManager->getInputDevices();
     for(QList<QAudioDeviceInfo>::const_iterator it = inputDevices.begin(); it != inputDevices.end(); ++it)
     {
         treeItem = new QTreeWidgetItem(ui->audioInTree);
         treeItem->setText(1, it->deviceName());
         bool systemDefault = it->deviceName() == defaultInputDeviceInfo.deviceName();
         found = m_audioDeviceManager->getInputDeviceInfo(it->deviceName(), inDeviceInfo);
         treeItem->setText(0, QString(systemDefault ? "S" : "_") + QString(found ? "_" : "D"));
         if (systemDefault) {
             treeItem->setBackground(1, QBrush(qRgb(96,96,96)));
         }
     }
     ui->audioInTree->resizeColumnToContents(0);
     ui->audioInTree->resizeColumnToContents(1);
     m_outputUDPPort = 9998;
     m_outIndex = -1;
     m_inIndex = -1;
     ui->tabWidget->setCurrentIndex(0);
 }
~AudioDialogX()
AudioDialogX::~AudioDialogX ()
Definition at line 99 of file audiodialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
accept
void AudioDialogX::accept () private slot
Definition at line 104 of file audiodialog.cpp.
References m_audioDeviceManager, m_inIndex, m_inputDeviceInfo, m_outIndex, m_outputDeviceInfo, AudioDeviceManager::setInputDeviceInfo(), AudioDeviceManager::setOutputDeviceInfo(), ui, AudioDeviceManager::unsetInputDeviceInfo(), AudioDeviceManager::unsetOutputDeviceInfo(), updateInputDeviceInfo(), and updateOutputDeviceInfo().
 {
     m_inIndex = ui->audioInTree->indexOfTopLevelItem(ui->audioInTree->currentItem());
     m_outIndex = ui->audioOutTree->indexOfTopLevelItem(ui->audioOutTree->currentItem());
     if (ui->tabWidget->currentIndex() == 0) // output
     {
         updateOutputDeviceInfo();
         if (ui->outputResetKey->isChecked()) {
             m_audioDeviceManager->unsetOutputDeviceInfo(m_outIndex-1);
         } else {
             m_audioDeviceManager->setOutputDeviceInfo(m_outIndex-1, m_outputDeviceInfo);
         }
     }
     else if (ui->tabWidget->currentIndex() == 1) // input
     {
         updateInputDeviceInfo();
         if (ui->inputResetKey->isChecked()) {
             m_audioDeviceManager->unsetInputDeviceInfo(m_inIndex-1);
         } else {
             m_audioDeviceManager->setInputDeviceInfo(m_inIndex-1, m_inputDeviceInfo);
         }
     }
     QDialog::accept();
 }
check
void AudioDialogX::check () private slot
Definition at line 333 of file audiodialog.cpp.
References m_outputDeviceInfo, AudioDeviceManager::OutputDeviceInfo::sampleRate, AudioDeviceManager::OutputDeviceInfo::udpChannelCodec, AudioDeviceManager::OutputDeviceInfo::udpChannelMode, AudioOutput::UDPChannelStereo, AudioOutput::UDPCodecALaw, AudioOutput::UDPCodecG722, AudioOutput::UDPCodecOpus, AudioOutput::UDPCodecULaw, and AudioDeviceManager::OutputDeviceInfo::udpDecimationFactor.
Referenced by on_decimationFactor_currentIndexChanged(), on_outputSampleRate_valueChanged(), on_outputUDPChannelCodec_currentIndexChanged(), and on_outputUDPChannelMode_currentIndexChanged().
 {
     int nChannels = m_outputDeviceInfo.udpChannelMode == AudioOutput::UDPChannelStereo ? 2 : 1;
     uint32_t decimationFactor = m_outputDeviceInfo.udpDecimationFactor == 0 ? 1 : m_outputDeviceInfo.udpDecimationFactor;
     if (m_outputDeviceInfo.udpChannelCodec == AudioOutput::UDPCodecALaw)
     {
         if ((nChannels != 1) || (m_outputDeviceInfo.sampleRate/decimationFactor != 8000)) {
             QMessageBox::information(this, tr("Message"), tr("PCMA must be 8000 Hz single channel"));
         }
     }
     else if (m_outputDeviceInfo.udpChannelCodec == AudioOutput::UDPCodecULaw)
     {
         if ((nChannels != 1) || (m_outputDeviceInfo.sampleRate/decimationFactor != 8000)) {
             QMessageBox::information(this, tr("Message"), tr("PCMU must be 8000 Hz single channel"));
         }
     }
     else if (m_outputDeviceInfo.udpChannelCodec == AudioOutput::UDPCodecG722)
     {
         if ((nChannels != 1) || (m_outputDeviceInfo.sampleRate/decimationFactor != 16000)) {
             QMessageBox::information(this, tr("Message"), tr("G722 must be 16000 Hz single channel"));
         }
     }
     else if (m_outputDeviceInfo.udpChannelCodec == AudioOutput::UDPCodecOpus)
     {
         int effectiveSampleRate = m_outputDeviceInfo.sampleRate/decimationFactor;
         if ((effectiveSampleRate != 48000) && (effectiveSampleRate != 24000) && (effectiveSampleRate != 16000) && (effectiveSampleRate != 12000)) {
             QMessageBox::information(this, tr("Message"), tr("Opus takes only 48, 24, 16 or 12 kHz sample rates"));
         }
     }
 }
on_audioInTree_currentItemChanged
void AudioDialogX::on_audioInTree_currentItemChanged (QTreeWidgetItem * currentItem, QTreeWidgetItem * previousItem) private slot
Definition at line 138 of file audiodialog.cpp.
References AudioDeviceManager::getInputDeviceInfo(), m_audioDeviceManager, m_inputDeviceInfo, ui, and updateInputDisplay().
 {
     AudioDeviceManager::InputDeviceInfo inDeviceInfo;
     QString inDeviceName = currentItem->text(1);
     int newIndex = ui->audioInTree->indexOfTopLevelItem(currentItem);
     int oldIndex = ui->audioInTree->indexOfTopLevelItem(previousItem);
     if (newIndex != oldIndex) {
         ui->inputResetKey->setChecked(false);
     }
     m_audioDeviceManager->getInputDeviceInfo(inDeviceName, inDeviceInfo);
     m_inputDeviceInfo = inDeviceInfo;
     updateInputDisplay();
 }
on_audioOutTree_currentItemChanged
void AudioDialogX::on_audioOutTree_currentItemChanged (QTreeWidgetItem * currentItem, QTreeWidgetItem * previousItem) private slot
Definition at line 157 of file audiodialog.cpp.
References AudioDeviceManager::getOutputDeviceInfo(), m_audioDeviceManager, m_outputDeviceInfo, ui, and updateOutputDisplay().
 {
     AudioDeviceManager::OutputDeviceInfo outDeviceInfo;
     QString outDeviceName = currentItem->text(1);
     int newIndex = ui->audioOutTree->indexOfTopLevelItem(currentItem);
     int oldIndex = ui->audioOutTree->indexOfTopLevelItem(previousItem);
     if (newIndex != oldIndex) {
         ui->outputResetKey->setChecked(false);
     }
     m_audioDeviceManager->getOutputDeviceInfo(outDeviceName, outDeviceInfo);
     m_outputDeviceInfo = outDeviceInfo;
     updateOutputDisplay();
 }
on_decimationFactor_currentIndexChanged
void AudioDialogX::on_decimationFactor_currentIndexChanged (int index) private slot
Definition at line 241 of file audiodialog.cpp.
References check(), m_outputDeviceInfo, AudioDeviceManager::OutputDeviceInfo::udpDecimationFactor, and updateOutputSDPString().
 {
     m_outputDeviceInfo.udpDecimationFactor = index + 1;
     updateOutputSDPString();
     check();
 }
on_inputCleanup_clicked
void AudioDialogX::on_inputCleanup_clicked (bool checked) private slot
Definition at line 189 of file audiodialog.cpp.
References AudioDeviceManager::inputInfosCleanup(), and m_audioDeviceManager.
 {
     (void) checked;
     m_audioDeviceManager->inputInfosCleanup();
 }
on_inputReset_clicked
void AudioDialogX::on_inputReset_clicked (bool checked) private slot
Definition at line 182 of file audiodialog.cpp.
References m_inputDeviceInfo, AudioDeviceManager::InputDeviceInfo::resetToDefaults(), and updateInputDisplay().
 {
     (void) checked;
     m_inputDeviceInfo.resetToDefaults();
     updateInputDisplay();
 }
on_inputVolume_valueChanged
void AudioDialogX::on_inputVolume_valueChanged (int value) private slot
Definition at line 176 of file audiodialog.cpp.
References arg(), and ui.
 {
     float volume = value / 100.0f;
     ui->inputVolumeText->setText(QString("%1").arg(volume, 0, 'f', 2));
 }
on_outputCleanup_clicked
void AudioDialogX::on_outputCleanup_clicked (bool checked) private slot
Definition at line 228 of file audiodialog.cpp.
References m_audioDeviceManager, and AudioDeviceManager::outputInfosCleanup().
 {
     (void) checked;
     m_audioDeviceManager->outputInfosCleanup();
 }
on_outputReset_clicked
void AudioDialogX::on_outputReset_clicked (bool checked) private slot
Definition at line 221 of file audiodialog.cpp.
References m_outputDeviceInfo, AudioDeviceManager::OutputDeviceInfo::resetToDefaults(), and updateOutputDisplay().
 {
     (void) checked;
     m_outputDeviceInfo.resetToDefaults();
     updateOutputDisplay();
 }
on_outputSampleRate_valueChanged
void AudioDialogX::on_outputSampleRate_valueChanged (int value) private slot
Definition at line 234 of file audiodialog.cpp.
References check(), m_outputDeviceInfo, AudioDeviceManager::OutputDeviceInfo::sampleRate, and updateOutputSDPString().
 {
     m_outputDeviceInfo.sampleRate = value;
     updateOutputSDPString();
     check();
 }
on_outputUDPChannelCodec_currentIndexChanged
void AudioDialogX::on_outputUDPChannelCodec_currentIndexChanged (int index) private slot
Definition at line 248 of file audiodialog.cpp.
References check(), m_outputDeviceInfo, AudioDeviceManager::OutputDeviceInfo::udpChannelCodec, and updateOutputSDPString().
 {
     m_outputDeviceInfo.udpChannelCodec = (AudioOutput::UDPChannelCodec) index;
     updateOutputSDPString();
     check();
 }
on_outputUDPChannelMode_currentIndexChanged
void AudioDialogX::on_outputUDPChannelMode_currentIndexChanged (int index) private slot
Definition at line 255 of file audiodialog.cpp.
References check(), m_outputDeviceInfo, AudioDeviceManager::OutputDeviceInfo::udpChannelMode, and updateOutputSDPString().
 {
     m_outputDeviceInfo.udpChannelMode = (AudioOutput::UDPChannelMode) index;
     updateOutputSDPString();
     check();
 }
on_outputUDPPort_editingFinished
void AudioDialogX::on_outputUDPPort_editingFinished () private slot
Definition at line 208 of file audiodialog.cpp.
References arg(), m_outputDeviceInfo, m_outputUDPPort, AudioDeviceManager::OutputDeviceInfo::udpPort, and ui.
 {
     bool ok;
     quint16 udpPort = ui->outputUDPPort->text().toInt(&ok);
     if((!ok) || (udpPort < 1024)) {
         udpPort = 9999;
     }
     m_outputUDPPort = udpPort;
     ui->outputUDPPort->setText(tr("%1").arg(m_outputDeviceInfo.udpPort));
 }
reject
void AudioDialogX::reject () private slot
Definition at line 133 of file audiodialog.cpp.
 {
     QDialog::reject();
 }
updateInputDeviceInfo()
void AudioDialogX::updateInputDeviceInfo () private
Definition at line 202 of file audiodialog.cpp.
References m_inputDeviceInfo, AudioDeviceManager::InputDeviceInfo::sampleRate, ui, and AudioDeviceManager::InputDeviceInfo::volume.
Referenced by accept().
 {
     m_inputDeviceInfo.sampleRate = ui->inputSampleRate->value();
     m_inputDeviceInfo.volume = ui->inputVolume->value() / 100.0f;
 }
updateInputDisplay()
void AudioDialogX::updateInputDisplay () private
Definition at line 195 of file audiodialog.cpp.
References arg(), m_inputDeviceInfo, AudioDeviceManager::InputDeviceInfo::sampleRate, ui, and AudioDeviceManager::InputDeviceInfo::volume.
Referenced by on_audioInTree_currentItemChanged(), and on_inputReset_clicked().
 {
     ui->inputSampleRate->setValue(m_inputDeviceInfo.sampleRate);
     ui->inputVolume->setValue(round(m_inputDeviceInfo.volume * 100.0f));
     ui->inputVolumeText->setText(QString("%1").arg(m_inputDeviceInfo.volume, 0, 'f', 2));
 }
updateOutputDeviceInfo()
void AudioDialogX::updateOutputDeviceInfo () private
Definition at line 286 of file audiodialog.cpp.
References AudioDeviceManager::OutputDeviceInfo::copyToUDP, m_outputDeviceInfo, m_outputUDPPort, AudioDeviceManager::OutputDeviceInfo::sampleRate, AudioDeviceManager::OutputDeviceInfo::udpAddress, AudioDeviceManager::OutputDeviceInfo::udpChannelCodec, AudioDeviceManager::OutputDeviceInfo::udpChannelMode, AudioDeviceManager::OutputDeviceInfo::udpDecimationFactor, AudioDeviceManager::OutputDeviceInfo::udpPort, AudioDeviceManager::OutputDeviceInfo::udpUseRTP, and ui.
Referenced by accept().
 {
     m_outputDeviceInfo.sampleRate = ui->outputSampleRate->value();
     m_outputDeviceInfo.udpAddress = ui->outputUDPAddress->text();
     m_outputDeviceInfo.udpPort = m_outputUDPPort;
     m_outputDeviceInfo.copyToUDP = ui->outputUDPCopy->isChecked();
     m_outputDeviceInfo.udpUseRTP = ui->outputUDPUseRTP->isChecked();
     m_outputDeviceInfo.udpChannelMode = (AudioOutput::UDPChannelMode) ui->outputUDPChannelMode->currentIndex();
     m_outputDeviceInfo.udpChannelCodec = (AudioOutput::UDPChannelCodec) ui->outputUDPChannelCodec->currentIndex();
     m_outputDeviceInfo.udpDecimationFactor = ui->decimationFactor->currentIndex() + 1;
 }
updateOutputDisplay()
void AudioDialogX::updateOutputDisplay () private
Definition at line 262 of file audiodialog.cpp.
References arg(), AudioDeviceManager::OutputDeviceInfo::copyToUDP, m_outputDeviceInfo, AudioDeviceManager::OutputDeviceInfo::sampleRate, AudioDeviceManager::OutputDeviceInfo::udpAddress, AudioDeviceManager::OutputDeviceInfo::udpChannelCodec, AudioDeviceManager::OutputDeviceInfo::udpChannelMode, AudioDeviceManager::OutputDeviceInfo::udpDecimationFactor, AudioDeviceManager::OutputDeviceInfo::udpPort, AudioDeviceManager::OutputDeviceInfo::udpUseRTP, ui, and updateOutputSDPString().
Referenced by on_audioOutTree_currentItemChanged(), and on_outputReset_clicked().
 {
     ui->outputSampleRate->blockSignals(true);
     ui->outputUDPChannelMode->blockSignals(true);
     ui->outputUDPChannelCodec->blockSignals(true);
     ui->decimationFactor->blockSignals(true);
     ui->outputSampleRate->setValue(m_outputDeviceInfo.sampleRate);
     ui->outputUDPAddress->setText(m_outputDeviceInfo.udpAddress);
     ui->outputUDPPort->setText(tr("%1").arg(m_outputDeviceInfo.udpPort));
     ui->outputUDPCopy->setChecked(m_outputDeviceInfo.copyToUDP);
     ui->outputUDPUseRTP->setChecked(m_outputDeviceInfo.udpUseRTP);
     ui->outputUDPChannelMode->setCurrentIndex((int) m_outputDeviceInfo.udpChannelMode);
     ui->outputUDPChannelCodec->setCurrentIndex((int) m_outputDeviceInfo.udpChannelCodec);
     ui->decimationFactor->setCurrentIndex(m_outputDeviceInfo.udpDecimationFactor == 0 ? 0 : m_outputDeviceInfo.udpDecimationFactor - 1);
     updateOutputSDPString();
     ui->outputSampleRate->blockSignals(false);
     ui->outputUDPChannelMode->blockSignals(false);
     ui->outputUDPChannelCodec->blockSignals(false);
     ui->decimationFactor->blockSignals(false);
 }
updateOutputSDPString()
void AudioDialogX::updateOutputSDPString () private
Definition at line 298 of file audiodialog.cpp.
References arg(), m_outputDeviceInfo, AudioDeviceManager::OutputDeviceInfo::sampleRate, AudioDeviceManager::OutputDeviceInfo::udpChannelCodec, AudioDeviceManager::OutputDeviceInfo::udpChannelMode, AudioOutput::UDPChannelStereo, AudioOutput::UDPCodecALaw, AudioOutput::UDPCodecG722, AudioOutput::UDPCodecL16, AudioOutput::UDPCodecL8, AudioOutput::UDPCodecOpus, AudioOutput::UDPCodecULaw, AudioDeviceManager::OutputDeviceInfo::udpDecimationFactor, and ui.
Referenced by on_decimationFactor_currentIndexChanged(), on_outputSampleRate_valueChanged(), on_outputUDPChannelCodec_currentIndexChanged(), on_outputUDPChannelMode_currentIndexChanged(), and updateOutputDisplay().
 {
     QString format;
     int nChannels = m_outputDeviceInfo.udpChannelMode == AudioOutput::UDPChannelStereo ? 2 : 1;
     uint32_t effectiveSampleRate = m_outputDeviceInfo.sampleRate / (m_outputDeviceInfo.udpDecimationFactor == 0 ? 1 : m_outputDeviceInfo.udpDecimationFactor);
     switch (m_outputDeviceInfo.udpChannelCodec)
     {
     case AudioOutput::UDPCodecALaw:
         format = "PCMA";
         break;
     case AudioOutput::UDPCodecULaw:
         format = "PCMU";
         break;
     case AudioOutput::UDPCodecG722:
         format = "G722";
         effectiveSampleRate /= 2; // codec does a decimation by 2
         break;
     case AudioOutput::UDPCodecL8:
         format = "L8";
         break;
     case AudioOutput::UDPCodecOpus:
         format = "opus";
         nChannels = 2; // always 2 even for mono
         effectiveSampleRate = 48000; // always 48000 regardless of input rate
         break;
     case AudioOutput::UDPCodecL16:
     default:
         format = "L16";
         break;
     }
     ui->outputSDPText->setText(tr("%1/%2/%3").arg(format).arg(effectiveSampleRate).arg(nChannels));
 }
Member Data Documentation
m_audioDeviceManager
AudioDeviceManager* AudioDialogX::m_audioDeviceManager private
Definition at line 34 of file audiodialog.h.
Referenced by accept(), AudioDialogX(), on_audioInTree_currentItemChanged(), on_audioOutTree_currentItemChanged(), on_inputCleanup_clicked(), and on_outputCleanup_clicked().
m_inIndex
int AudioDialogX::m_inIndex
Definition at line 22 of file audiodialog.h.
Referenced by accept(), and AudioDialogX().
m_inputDeviceInfo
AudioDeviceManager::InputDeviceInfo AudioDialogX::m_inputDeviceInfo private
Definition at line 35 of file audiodialog.h.
Referenced by accept(), on_audioInTree_currentItemChanged(), on_inputReset_clicked(), updateInputDeviceInfo(), and updateInputDisplay().
m_outIndex
int AudioDialogX::m_outIndex
Definition at line 23 of file audiodialog.h.
Referenced by accept(), and AudioDialogX().
m_outputDeviceInfo
AudioDeviceManager::OutputDeviceInfo AudioDialogX::m_outputDeviceInfo private
Definition at line 36 of file audiodialog.h.
Referenced by accept(), check(), on_audioOutTree_currentItemChanged(), on_decimationFactor_currentIndexChanged(), on_outputReset_clicked(), on_outputSampleRate_valueChanged(), on_outputUDPChannelCodec_currentIndexChanged(), on_outputUDPChannelMode_currentIndexChanged(), on_outputUDPPort_editingFinished(), updateOutputDeviceInfo(), updateOutputDisplay(), and updateOutputSDPString().
m_outputUDPPort
quint16 AudioDialogX::m_outputUDPPort private
Definition at line 37 of file audiodialog.h.
Referenced by AudioDialogX(), on_outputUDPPort_editingFinished(), and updateOutputDeviceInfo().
ui
Ui::AudioDialog* AudioDialogX::ui private
Definition at line 32 of file audiodialog.h.
Referenced by accept(), AudioDialogX(), on_audioInTree_currentItemChanged(), on_audioOutTree_currentItemChanged(), on_inputVolume_valueChanged(), on_outputUDPPort_editingFinished(), updateInputDeviceInfo(), updateInputDisplay(), updateOutputDeviceInfo(), updateOutputDisplay(), updateOutputSDPString(), and ~AudioDialogX().
The documentation for this class was generated from the following files:
sdrgui/gui/audiodialog.h
sdrgui/gui/audiodialog.cpp