SDRAngel: MyPositionDialog Class Reference
MyPositionDialog Class Reference
#include <mypositiondialog.h>
Inherits QDialog.
Public Member Functions
MyPositionDialog (MainSettings &mainSettings, QWidget *parent=0)
~MyPositionDialog ()
Private Slots
void accept ()
Private Attributes
Ui::MyPositionDialog * ui
MainSettings & m_mainSettings
Detailed Description
Definition at line 33 of file mypositiondialog.h.
Constructor & Destructor Documentation
MyPositionDialog()
MyPositionDialog::MyPositionDialog (MainSettings & mainSettings, QWidget * parent = 0) explicit
Definition at line 26 of file mypositiondialog.cpp.
References MainSettings::getLatitude(), MainSettings::getLongitude(), m_mainSettings, and ui.
                                                                               :
     QDialog(parent),
     ui(new Ui::MyPositionDialog),
     m_mainSettings(mainSettings)
 {
     ui->setupUi(this);
     ui->latitudeSpinBox->setValue(m_mainSettings.getLatitude());
     ui->longitudeSpinBox->setValue(m_mainSettings.getLongitude());
 }
~MyPositionDialog()
MyPositionDialog::~MyPositionDialog ()
Definition at line 36 of file mypositiondialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
accept
void MyPositionDialog::accept () private slot
Definition at line 41 of file mypositiondialog.cpp.
References m_mainSettings, MainSettings::setLatitude(), MainSettings::setLongitude(), and ui.
 {
     m_mainSettings.setLatitude(ui->latitudeSpinBox->value());
     m_mainSettings.setLongitude(ui->longitudeSpinBox->value());
     QDialog::accept();
 }
Member Data Documentation
m_mainSettings
MainSettings& MyPositionDialog::m_mainSettings private
Definition at line 42 of file mypositiondialog.h.
Referenced by accept(), and MyPositionDialog().
ui
Ui::MyPositionDialog* MyPositionDialog::ui private
Definition at line 41 of file mypositiondialog.h.
Referenced by accept(), MyPositionDialog(), and ~MyPositionDialog().
The documentation for this class was generated from the following files:
sdrgui/gui/mypositiondialog.h
sdrgui/gui/mypositiondialog.cpp