SDRAngel: LocalSink Class Reference
LocalSink Class Reference
#include <localsink.h>
Classes
class MsgConfigureChannelizer
class MsgConfigureLocalSink
class MsgSampleRateNotification
Signals
void samplesAvailable (const quint8 *data, uint count)
Public Member Functions
LocalSink (DeviceAPI *deviceAPI)
virtual ~LocalSink ()
virtual void destroy ()
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool po)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
void setCenterFrequency (uint64_t centerFrequency)
void setSampleRate (uint32_t sampleRate)
void setChannelizer (unsigned int log2Decim, unsigned int filterChainHash)
void getLocalDevices (std::vector< uint32_t > &indexes)
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.localsink"
static const QString m_channelId = "LocalSink"
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applySettings (const LocalSinkSettings &settings, bool force=false)
DeviceSampleSource * getLocalDevice (uint32_t index)
void propagateSampleRateAndFrequency (uint32_t index)
void validateFilterChainHash (LocalSinkSettings &settings)
void calculateFrequencyOffset ()
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const LocalSinkSettings &settings)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const LocalSinkSettings &settings, bool force)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
bool m_running
LocalSinkSettings m_settings
LocalSinkThread * m_sinkThread
uint64_t m_centerFrequency
int64_t m_frequencyOffset
uint32_t m_sampleRate
uint32_t m_deviceSampleRate
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 37 of file localsink.h.
Constructor & Destructor Documentation
LocalSink()
LocalSink::LocalSink (DeviceAPI * deviceAPI)
Definition at line 48 of file localsink.cpp.
References DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), m_channelId, m_channelizer, m_deviceAPI, m_networkManager, m_threadedChannelizer, and networkManagerFinished().
Referenced by LocalSink::MsgConfigureChannelizer::MsgConfigureChannelizer().
                                          :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(deviceAPI),
         m_running(false),
         m_sinkThread(0),
         m_centerFrequency(0),
         m_frequencyOffset(0),
         m_sampleRate(48000),
         m_deviceSampleRate(48000)
 {
     setObjectName(m_channelId);
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~LocalSink()
LocalSink::~LocalSink () virtual
Definition at line 69 of file localsink.cpp.
References m_channelizer, m_deviceAPI, m_networkManager, m_threadedChannelizer, networkManagerFinished(), DeviceAPI::removeChannelSink(), and DeviceAPI::removeChannelSinkAPI().
Referenced by LocalSink::MsgConfigureChannelizer::MsgConfigureChannelizer().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
 }
Member Function Documentation
applySettings()
void LocalSink::applySettings (const LocalSinkSettings & settings, bool force = false) private
Definition at line 282 of file localsink.cpp.
References getLocalDevice(), DeviceSampleSource::getSampleFifo(), LocalSinkSettings::m_localDeviceIndex, LocalSinkSettings::m_reverseAPIAddress, LocalSinkSettings::m_reverseAPIChannelIndex, LocalSinkSettings::m_reverseAPIDeviceIndex, LocalSinkSettings::m_reverseAPIPort, m_settings, m_sinkThread, LocalSinkSettings::m_useReverseAPI, propagateSampleRateAndFrequency(), LocalSinkThread::setSampleFifo(), and webapiReverseSendSettings().
Referenced by handleMessage().
 {
     qDebug() << "LocalSink::applySettings:"
             << " m_localDeviceIndex: " << settings.m_localDeviceIndex
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if ((settings.m_localDeviceIndex != m_settings.m_localDeviceIndex) || force)
     {
         reverseAPIKeys.append("localDeviceIndex");
         DeviceSampleSource *deviceSource = getLocalDevice(settings.m_localDeviceIndex);
         if (deviceSource)
         {
             if (m_sinkThread) {
                 m_sinkThread->setSampleFifo(deviceSource->getSampleFifo());
             }
             propagateSampleRateAndFrequency(settings.m_localDeviceIndex);
         }
         else
         {
             qWarning("LocalSink::applySettings: invalid local device for index %u", settings.m_localDeviceIndex);
         }
     }
     if ((settings.m_useReverseAPI) && (reverseAPIKeys.size() != 0))
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
calculateFrequencyOffset()
void LocalSink::calculateFrequencyOffset () private
Definition at line 333 of file localsink.cpp.
References HBFilterChainConverter::getShiftFactor(), m_deviceSampleRate, LocalSinkSettings::m_filterChainHash, m_frequencyOffset, LocalSinkSettings::m_log2Decim, and m_settings.
Referenced by handleMessage().
 {
     double shiftFactor = HBFilterChainConverter::getShiftFactor(m_settings.m_log2Decim, m_settings.m_filterChainHash);
     m_frequencyOffset = m_deviceSampleRate * shiftFactor;
 }
deserialize()
bool LocalSink::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 205 of file localsink.cpp.
References LocalSink::MsgConfigureLocalSink::create(), LocalSinkSettings::deserialize(), BasebandSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and LocalSinkSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     (void) data;
     if (m_settings.deserialize(data))
     {
         MsgConfigureLocalSink *msg = MsgConfigureLocalSink::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureLocalSink *msg = MsgConfigureLocalSink::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void LocalSink::destroy () inline virtual
Implements ChannelAPI.
Definition at line 107 of file localsink.h.
References feed(), handleMessage(), start(), and stop().
 { delete this; }
feed()
void LocalSink::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool po) virtual
Implements BasebandSampleSink.
Definition at line 79 of file localsink.cpp.
References samplesAvailable().
Referenced by destroy().
 {
     (void) firstOfBurst;
     emit samplesAvailable((const quint8*) &(*begin), (end-begin)*sizeof(Sample));
 }
getCenterFrequency()
virtual qint64 LocalSink::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 116 of file localsink.h.
References deserialize(), m_frequencyOffset, and serialize().
 { return m_frequencyOffset; }
getIdentifier()
virtual void LocalSink::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 114 of file localsink.h.
 { id = objectName(); }
getLocalDevice()
DeviceSampleSource * LocalSink::getLocalDevice (uint32_t index) private
Definition at line 239 of file localsink.cpp.
References ChannelAPI::getDeviceAPI(), DeviceSampleSource::getDeviceDescription(), DSPEngine::getDeviceSourceEngineByIndex(), DSPDeviceSourceEngine::getSource(), DSPDeviceSourceEngine::getUID(), and DSPEngine::instance().
Referenced by applySettings(), propagateSampleRateAndFrequency(), and start().
 {
     DSPEngine *dspEngine = DSPEngine::instance();
     if (index < dspEngine->getDeviceSourceEnginesNumber())
     {
         DSPDeviceSourceEngine *deviceSourceEngine = dspEngine->getDeviceSourceEngineByIndex(index);
         DeviceSampleSource *deviceSource = deviceSourceEngine->getSource();
         if (deviceSource->getDeviceDescription() == "LocalInput")
         {
             if (!getDeviceAPI()) {
                 qDebug("LocalSink::getLocalDevice: the parent device is unset");
             } else if (getDeviceAPI()->getDeviceUID() == deviceSourceEngine->getUID()) {
                 qDebug("LocalSink::getLocalDevice: source device at index %u is the parent device", index);
             } else {
                 return deviceSource;
             }
         }
         else
         {
             qDebug("LocalSink::getLocalDevice: source device at index %u is not a Local Input source", index);
         }
     }
     else
     {
         qDebug("LocalSink::getLocalDevice: non existent source device index: %u", index);
     }
     return nullptr;
 }
getLocalDevices()
void LocalSink::getLocalDevices (std::vector< uint32_t > & indexes)
Definition at line 223 of file localsink.cpp.
References DeviceSampleSource::getDeviceDescription(), DSPEngine::getDeviceSourceEngineByIndex(), DSPEngine::getDeviceSourceEnginesNumber(), DSPDeviceSourceEngine::getSource(), i, and DSPEngine::instance().
Referenced by setSampleRate(), and LocalSinkGUI::updateLocalDevices().
 {
     indexes.clear();
     DSPEngine *dspEngine = DSPEngine::instance();
     for (uint32_t i = 0; i < dspEngine->getDeviceSourceEnginesNumber(); i++)
     {
         DSPDeviceSourceEngine *deviceSourceEngine = dspEngine->getDeviceSourceEngineByIndex(i);
         DeviceSampleSource *deviceSource = deviceSourceEngine->getSource();
         if (deviceSource->getDeviceDescription() == "LocalInput") {
             indexes.push_back(i);
         }
     }
 }
getNbSinkStreams()
virtual int LocalSink::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 121 of file localsink.h.
 { return 1; }
getNbSourceStreams()
virtual int LocalSink::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 122 of file localsink.h.
 { return 0; }
getStreamCenterFrequency()
virtual qint64 LocalSink::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 124 of file localsink.h.
References m_frequencyOffset, webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_frequencyOffset;
     }
getTitle()
virtual void LocalSink::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 115 of file localsink.h.
 { title = "Local Sink"; }
handleMessage()
bool LocalSink::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 124 of file localsink.cpp.
References applySettings(), calculateFrequencyOffset(), LocalSink::MsgSampleRateNotification::create(), DSPSignalNotification::getCenterFrequency(), LocalSink::MsgConfigureChannelizer::getFilterChainHash(), LocalSink::MsgConfigureLocalSink::getForce(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSink::getInputMessageQueue(), LocalSink::MsgConfigureChannelizer::getLog2Decim(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), DSPSignalNotification::getSampleRate(), LocalSink::MsgConfigureLocalSink::getSettings(), m_channelizer, m_deviceSampleRate, LocalSinkSettings::m_filterChainHash, BasebandSampleSink::m_guiMessageQueue, LocalSinkSettings::m_localDeviceIndex, LocalSinkSettings::m_log2Decim, m_settings, Message::match(), propagateSampleRateAndFrequency(), MessageQueue::push(), DownChannelizer::set(), setCenterFrequency(), and setSampleRate().
Referenced by destroy().
 {
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& notif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "LocalSink::handleMessage: MsgChannelizerNotification:"
                 << " channelSampleRate: " << notif.getSampleRate()
                 << " offsetFrequency: " << notif.getFrequencyOffset();
         if (notif.getSampleRate() > 0)
         {
             setSampleRate(notif.getSampleRate());
         }
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         DSPSignalNotification& notif = (DSPSignalNotification&) cmd;
         qDebug() << "LocalSink::handleMessage: DSPSignalNotification:"
                 << " inputSampleRate: " << notif.getSampleRate()
                 << " centerFrequency: " << notif.getCenterFrequency();
         setCenterFrequency(notif.getCenterFrequency());
         m_deviceSampleRate = notif.getSampleRate();
         calculateFrequencyOffset(); // This is when device sample rate changes
         propagateSampleRateAndFrequency(m_settings.m_localDeviceIndex);
         // Redo the channelizer stuff with the new sample rate to re-synchronize everything
         m_channelizer->set(m_channelizer->getInputMessageQueue(),
             m_settings.m_log2Decim,
             m_settings.m_filterChainHash);
         if (m_guiMessageQueue)
         {
             MsgSampleRateNotification *msg = MsgSampleRateNotification::create(notif.getSampleRate());
             m_guiMessageQueue->push(msg);
         }
         return true;
     }
     else if (MsgConfigureLocalSink::match(cmd))
     {
         MsgConfigureLocalSink& cfg = (MsgConfigureLocalSink&) cmd;
         qDebug() << "LocalSink::handleMessage: MsgConfigureLocalSink";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         m_settings.m_log2Decim = cfg.getLog2Decim();
         m_settings.m_filterChainHash =  cfg.getFilterChainHash();
         qDebug() << "LocalSink::handleMessage: MsgConfigureChannelizer:"
                 << " log2Decim: " << m_settings.m_log2Decim
                 << " filterChainHash: " << m_settings.m_filterChainHash;
         m_channelizer->set(m_channelizer->getInputMessageQueue(),
             m_settings.m_log2Decim,
             m_settings.m_filterChainHash);
         calculateFrequencyOffset(); // This is when decimation or filter chain changes
         propagateSampleRateAndFrequency(m_settings.m_localDeviceIndex);
         return true;
     }
     else
     {
         return false;
     }
 }
networkManagerFinished
void LocalSink::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 488 of file localsink.cpp.
Referenced by LocalSink(), and ~LocalSink().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "LocalSink::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("LocalSink::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
propagateSampleRateAndFrequency()
void LocalSink::propagateSampleRateAndFrequency (uint32_t index) private
Definition at line 271 of file localsink.cpp.
References getLocalDevice(), m_centerFrequency, m_deviceSampleRate, m_frequencyOffset, LocalSinkSettings::m_log2Decim, m_settings, DeviceSampleSource::setCenterFrequency(), and DeviceSampleSource::setSampleRate().
Referenced by applySettings(), and handleMessage().
 {
     DeviceSampleSource *deviceSource = getLocalDevice(index);
     if (deviceSource)
     {
         deviceSource->setSampleRate(m_deviceSampleRate / (1<<m_settings.m_log2Decim));
         deviceSource->setCenterFrequency(m_centerFrequency + m_frequencyOffset);
     }
 }
samplesAvailable
void LocalSink::samplesAvailable (const quint8 * data, uint count) signal
Referenced by feed(), and start().
serialize()
QByteArray LocalSink::serialize () const virtual
Implements ChannelAPI.
Definition at line 200 of file localsink.cpp.
References m_settings, and LocalSinkSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void LocalSink::setCenterFrequency (uint64_t centerFrequency) inline
Set center frequency given in Hz
Definition at line 142 of file localsink.h.
References m_centerFrequency.
Referenced by handleMessage().
 { m_centerFrequency = centerFrequency; }
setChannelizer()
void LocalSink::setChannelizer (unsigned int log2Decim, unsigned int filterChainHash)
Referenced by setSampleRate().
setSampleRate()
void LocalSink::setSampleRate (uint32_t sampleRate) inline
Set sample rate given in Hz
Definition at line 145 of file localsink.h.
References getLocalDevices(), m_sampleRate, and setChannelizer().
Referenced by handleMessage().
 { m_sampleRate = sampleRate; }
start()
void LocalSink::start () virtual
Implements BasebandSampleSink.
Definition at line 85 of file localsink.cpp.
References getLocalDevice(), DeviceSampleSource::getSampleFifo(), LocalSinkSettings::m_localDeviceIndex, m_running, m_settings, m_sinkThread, samplesAvailable(), LocalSinkThread::setSampleFifo(), LocalSinkThread::startStop(), and stop().
Referenced by destroy().
 {
     qDebug("LocalSink::start");
     if (m_running) {
         stop();
     }
     m_sinkThread = new LocalSinkThread();
     DeviceSampleSource *deviceSource = getLocalDevice(m_settings.m_localDeviceIndex);
     if (deviceSource) {
         m_sinkThread->setSampleFifo(deviceSource->getSampleFifo());
     }
     connect(this,
             SIGNAL(samplesAvailable(const quint8*, uint)),
             m_sinkThread,
             SLOT(processSamples(const quint8*, uint)),
             Qt::QueuedConnection);
     m_sinkThread->startStop(true);
     m_running = true;
 }
stop()
void LocalSink::stop () virtual
Implements BasebandSampleSink.
Definition at line 110 of file localsink.cpp.
References m_running, m_sinkThread, and LocalSinkThread::startStop().
Referenced by destroy(), and start().
 {
     qDebug("LocalSink::stop");
     if (m_sinkThread != 0)
     {
         m_sinkThread->startStop(false);
         m_sinkThread->deleteLater();
         m_sinkThread = 0;
     }
     m_running = false;
 }
validateFilterChainHash()
void LocalSink::validateFilterChainHash (LocalSinkSettings & settings) private
Definition at line 322 of file localsink.cpp.
References i, LocalSinkSettings::m_filterChainHash, and LocalSinkSettings::m_log2Decim.
Referenced by webapiSettingsPutPatch().
 {
     unsigned int s = 1;
     for (unsigned int i = 0; i < settings.m_log2Decim; i++) {
         s *= 3;
     }
     settings.m_filterChainHash = settings.m_filterChainHash >= s ? s-1 : settings.m_filterChainHash;
 }
webapiFormatChannelSettings()
void LocalSink::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const LocalSinkSettings & settings) private
Definition at line 415 of file localsink.cpp.
References SWGSDRangel::SWGChannelSettings::getLocalSinkSettings(), SWGSDRangel::SWGLocalSinkSettings::getReverseApiAddress(), SWGSDRangel::SWGLocalSinkSettings::getTitle(), LocalSinkSettings::m_filterChainHash, LocalSinkSettings::m_localDeviceIndex, LocalSinkSettings::m_log2Decim, LocalSinkSettings::m_reverseAPIAddress, LocalSinkSettings::m_reverseAPIChannelIndex, LocalSinkSettings::m_reverseAPIDeviceIndex, LocalSinkSettings::m_reverseAPIPort, LocalSinkSettings::m_rgbColor, LocalSinkSettings::m_title, LocalSinkSettings::m_useReverseAPI, SWGSDRangel::SWGLocalSinkSettings::setFilterChainHash(), SWGSDRangel::SWGLocalSinkSettings::setLocalDeviceIndex(), SWGSDRangel::SWGLocalSinkSettings::setLog2Decim(), SWGSDRangel::SWGLocalSinkSettings::setReverseApiAddress(), SWGSDRangel::SWGLocalSinkSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGLocalSinkSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGLocalSinkSettings::setReverseApiPort(), SWGSDRangel::SWGLocalSinkSettings::setRgbColor(), SWGSDRangel::SWGLocalSinkSettings::setTitle(), and SWGSDRangel::SWGLocalSinkSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getLocalSinkSettings()->setLocalDeviceIndex(settings.m_localDeviceIndex);
     response.getLocalSinkSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getLocalSinkSettings()->getTitle()) {
         *response.getLocalSinkSettings()->getTitle() = settings.m_title;
     } else {
         response.getLocalSinkSettings()->setTitle(new QString(settings.m_title));
     }
     response.getLocalSinkSettings()->setLog2Decim(settings.m_log2Decim);
     response.getLocalSinkSettings()->setFilterChainHash(settings.m_filterChainHash);
     response.getLocalSinkSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getLocalSinkSettings()->getReverseApiAddress()) {
         *response.getLocalSinkSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getLocalSinkSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getLocalSinkSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getLocalSinkSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getLocalSinkSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReverseSendSettings()
void LocalSink::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const LocalSinkSettings & settings, bool force) private
Definition at line 441 of file localsink.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), SWGSDRangel::SWGChannelSettings::getLocalSinkSettings(), LocalSinkSettings::m_filterChainHash, LocalSinkSettings::m_localDeviceIndex, LocalSinkSettings::m_log2Decim, m_networkManager, m_networkRequest, LocalSinkSettings::m_reverseAPIAddress, LocalSinkSettings::m_reverseAPIChannelIndex, LocalSinkSettings::m_reverseAPIDeviceIndex, LocalSinkSettings::m_reverseAPIPort, LocalSinkSettings::m_rgbColor, LocalSinkSettings::m_title, SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGLocalSinkSettings::setFilterChainHash(), SWGSDRangel::SWGLocalSinkSettings::setLocalDeviceIndex(), SWGSDRangel::SWGChannelSettings::setLocalSinkSettings(), SWGSDRangel::SWGLocalSinkSettings::setLog2Decim(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGLocalSinkSettings::setRgbColor(), and SWGSDRangel::SWGLocalSinkSettings::setTitle().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(0); // single sink (Rx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("LocalSink"));
     swgChannelSettings->setLocalSinkSettings(new SWGSDRangel::SWGLocalSinkSettings());
     SWGSDRangel::SWGLocalSinkSettings *swgLocalSinkSettings = swgChannelSettings->getLocalSinkSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("localDeviceIndex") || force) {
         swgLocalSinkSettings->setLocalDeviceIndex(settings.m_localDeviceIndex);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgLocalSinkSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgLocalSinkSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("log2Decim") || force) {
         swgLocalSinkSettings->setLog2Decim(settings.m_log2Decim);
     }
     if (channelSettingsKeys.contains("filterChainHash") || force) {
         swgLocalSinkSettings->setFilterChainHash(settings.m_filterChainHash);
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int LocalSink::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 339 of file localsink.cpp.
References SWGSDRangel::SWGChannelSettings::getLocalSinkSettings(), SWGSDRangel::SWGLocalSinkSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setLocalSinkSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setLocalSinkSettings(new SWGSDRangel::SWGLocalSinkSettings());
     response.getLocalSinkSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int LocalSink::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 350 of file localsink.cpp.
References LocalSink::MsgConfigureLocalSink::create(), LocalSink::MsgConfigureChannelizer::create(), SWGSDRangel::SWGLocalSinkSettings::getFilterChainHash(), SWGSDRangel::SWGLocalSinkSettings::getLocalDeviceIndex(), SWGSDRangel::SWGChannelSettings::getLocalSinkSettings(), SWGSDRangel::SWGLocalSinkSettings::getLog2Decim(), SWGSDRangel::SWGLocalSinkSettings::getReverseApiAddress(), SWGSDRangel::SWGLocalSinkSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGLocalSinkSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGLocalSinkSettings::getReverseApiPort(), SWGSDRangel::SWGLocalSinkSettings::getRgbColor(), SWGSDRangel::SWGLocalSinkSettings::getTitle(), SWGSDRangel::SWGLocalSinkSettings::getUseReverseApi(), LocalSinkSettings::m_filterChainHash, BasebandSampleSink::m_guiMessageQueue, BasebandSampleSink::m_inputMessageQueue, LocalSinkSettings::m_localDeviceIndex, LocalSinkSettings::m_log2Decim, LocalSinkSettings::m_reverseAPIAddress, LocalSinkSettings::m_reverseAPIChannelIndex, LocalSinkSettings::m_reverseAPIDeviceIndex, LocalSinkSettings::m_reverseAPIPort, LocalSinkSettings::m_rgbColor, m_settings, LocalSinkSettings::m_title, LocalSinkSettings::m_useReverseAPI, MessageQueue::push(), validateFilterChainHash(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     LocalSinkSettings settings = m_settings;
     if (channelSettingsKeys.contains("localDeviceIndex")) {
         settings.m_localDeviceIndex = response.getLocalSinkSettings()->getLocalDeviceIndex();
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getLocalSinkSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getLocalSinkSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getLocalSinkSettings()->getLog2Decim();
     }
     if (channelSettingsKeys.contains("filterChainHash"))
     {
         settings.m_filterChainHash = response.getLocalSinkSettings()->getFilterChainHash();
         validateFilterChainHash(settings);
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getLocalSinkSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getLocalSinkSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getLocalSinkSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getLocalSinkSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getLocalSinkSettings()->getReverseApiChannelIndex();
     }
     MsgConfigureLocalSink *msg = MsgConfigureLocalSink::create(settings, force);
     m_inputMessageQueue.push(msg);
     if ((settings.m_log2Decim != m_settings.m_log2Decim) || (settings.m_filterChainHash != m_settings.m_filterChainHash) || force)
     {
         MsgConfigureChannelizer *msg = MsgConfigureChannelizer::create(settings.m_log2Decim, settings.m_filterChainHash);
         m_inputMessageQueue.push(msg);
     }
     qDebug("LocalSink::webapiSettingsPutPatch: forward to GUI: %p", m_guiMessageQueue);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureLocalSink *msgToGUI = MsgConfigureLocalSink::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_centerFrequency
uint64_t LocalSink::m_centerFrequency private
Definition at line 165 of file localsink.h.
Referenced by propagateSampleRateAndFrequency(), and setCenterFrequency().
m_channelId
const QString LocalSink::m_channelId = "LocalSink" static
Definition at line 151 of file localsink.h.
Referenced by LocalSinkPlugin::initPlugin(), and LocalSink().
m_channelIdURI
const QString LocalSink::m_channelIdURI = "sdrangel.channel.localsink" static
Definition at line 150 of file localsink.h.
Referenced by LocalSinkPlugin::initPlugin(), and LocalSinkGUI::LocalSinkGUI().
m_channelizer
DownChannelizer* LocalSink::m_channelizer private
Definition at line 159 of file localsink.h.
Referenced by handleMessage(), LocalSink(), and ~LocalSink().
m_deviceAPI
DeviceAPI* LocalSink::m_deviceAPI private
Definition at line 157 of file localsink.h.
Referenced by LocalSink(), and ~LocalSink().
m_deviceSampleRate
uint32_t LocalSink::m_deviceSampleRate private
Definition at line 168 of file localsink.h.
Referenced by calculateFrequencyOffset(), handleMessage(), and propagateSampleRateAndFrequency().
m_frequencyOffset
int64_t LocalSink::m_frequencyOffset private
Definition at line 166 of file localsink.h.
Referenced by calculateFrequencyOffset(), getCenterFrequency(), getStreamCenterFrequency(), and propagateSampleRateAndFrequency().
m_networkManager
QNetworkAccessManager* LocalSink::m_networkManager private
Definition at line 170 of file localsink.h.
Referenced by LocalSink(), webapiReverseSendSettings(), and ~LocalSink().
m_networkRequest
QNetworkRequest LocalSink::m_networkRequest private
Definition at line 171 of file localsink.h.
Referenced by webapiReverseSendSettings().
m_running
bool LocalSink::m_running private
Definition at line 160 of file localsink.h.
Referenced by start(), and stop().
m_sampleRate
uint32_t LocalSink::m_sampleRate private
Definition at line 167 of file localsink.h.
Referenced by LocalSink::MsgSampleRateNotification::getSampleRate(), and setSampleRate().
m_settings
LocalSinkSettings LocalSink::m_settings private
Definition at line 162 of file localsink.h.
Referenced by applySettings(), calculateFrequencyOffset(), deserialize(), handleMessage(), propagateSampleRateAndFrequency(), serialize(), start(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_sinkThread
LocalSinkThread* LocalSink::m_sinkThread private
Definition at line 163 of file localsink.h.
Referenced by applySettings(), start(), and stop().
m_threadedChannelizer
ThreadedBasebandSampleSink* LocalSink::m_threadedChannelizer private
Definition at line 158 of file localsink.h.
Referenced by LocalSink(), and ~LocalSink().
The documentation for this class was generated from the following files:
plugins/channelrx/localsink/localsink.h
plugins/channelrx/localsink/localsink.cpp