SDRAngel: qrtplib Namespace Reference
qrtplib Namespace Reference
Classes
class RTCPAPPPacket
class RTCPBYEPacket
struct RTCPCommonHeader
class RTCPCompoundPacket
class RTCPCompoundPacketBuilder
class RTCPPacket
class RTCPPacketBuilder
struct RTCPReceiverReport
class RTCPReceiverReportInfo
class RTCPRRPacket
class RTCPScheduler
class RTCPSchedulerParams
struct RTCPSDESHeader
class RTCPSDESInfo
class RTCPSDESPacket
struct RTCPSenderReport
class RTCPSenderReportInfo
class RTCPSRPacket
class RTCPUnknownPacket
class RTPAddress
class RTPCollisionList
class RTPEndian
struct RTPErrorInfo
struct RTPExtensionHeader
struct RTPHeader
class RTPInternalSourceData
class RTPKeyHashTable
class RTPNTPTime
class RTPPacket
class RTPPacketBuilder
class RTPRandom
class RTPRandomRand48
class RTPRandomRandS
class RTPRandomURandom
class RTPRawPacket
class RTPSession
class RTPSessionParams
class RTPSessionSources
class RTPSourceData
struct RTPSourceIdentifier
class RTPSources
class RTPSources_GetHashIndex
class RTPSourceStats
class RTPTime
class RTPTimeInitializerObject
class RTPTransmissionInfo
class RTPTransmissionParams
class RTPTransmitter
class RTPUDPTransmissionInfo
class RTPUDPTransmissionParams
class RTPUDPTransmitter
Typedefs
typedef int SocketType
Functions
std::string RTPGetErrorString (int errcode)
double RTPTime_timespecToDouble (struct timespec &ts)
Variables
RTPTimeInitializerObject timeinit
Typedef Documentation
SocketType
typedef int qrtplib::SocketType
Definition at line 51 of file rtpsocketutil.h.
Function Documentation
RTPGetErrorString()
QRTPLIB_API std::string qrtplib::RTPGetErrorString (int errcode)
Returns a string describing the error code errcode.
Definition at line 248 of file rtperrors.cpp.
References qrtplib::RTPErrorInfo::code, qrtplib::RTPErrorInfo::description, i, and RTP_SNPRINTF.
Referenced by RTPSink::addDestination(), RTPSink::deleteDestination(), RTPSink::RTPSink(), RTPSink::setDestination(), RTPSink::setPayloadInformation(), and RTPSink::write().
 {
     int i;
     if (errcode >= 0)
         return std::string("No error");
     i = 0;
     while (ErrorDescriptions[i].code != 0)
     {
         if (ErrorDescriptions[i].code == errcode)
             return std::string(ErrorDescriptions[i].description);
         i++;
     }
     char str[16];
     RTP_SNPRINTF(str, 16, "(%d)", errcode);
     return std::string("Unknown error code") + std::string(str);
 }
RTPTime_timespecToDouble()
double qrtplib::RTPTime_timespecToDouble (struct timespec & ts) inline
Definition at line 288 of file rtptimeutilities.h.
Referenced by qrtplib::RTPTime::CurrentTime().
 {
     return (double) ts.tv_sec + 1e-9 * (double) ts.tv_nsec;
 }
Variable Documentation
timeinit
QRTPLIB_API RTPTimeInitializerObject qrtplib::timeinit
Definition at line 44 of file rtptimeutilities.cpp.
Referenced by qrtplib::RTCPPacketBuilder::RTCPPacketBuilder(), qrtplib::RTCPSchedulerParams::RTCPSchedulerParams(), qrtplib::RTPCollisionList::RTPCollisionList(), qrtplib::RTPPacketBuilder::RTPPacketBuilder(), qrtplib::RTPSession::RTPSession(), and qrtplib::RTPTransmitter::RTPTransmitter().