SDRAngel: TestMI::MsgStartStop Class Reference
TestMI::MsgStartStop Class Reference
#include <testmi.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 83 of file testmi.h.
Constructor & Destructor Documentation
MsgStartStop()
TestMI::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 96 of file testmi.h.
References TestMI::deserialize(), TestMI::destroy(), TestMI::init(), TestMI::serialize(), TestMI::start(), TestMI::stop(), TestMI::TestMI(), and TestMI::~TestMI().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* TestMI::MsgStartStop::create (bool startStop) inline static
Definition at line 89 of file testmi.h.
Referenced by TestMIGui::on_startStop_toggled(), and TestMI::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool TestMI::MsgStartStop::getStartStop () const inline
Definition at line 87 of file testmi.h.
Referenced by TestMIGui::handleMessage(), and TestMI::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool TestMI::MsgStartStop::m_startStop protected
Definition at line 94 of file testmi.h.
The documentation for this class was generated from the following file:
plugins/samplemimo/testmi/testmi.h