SDRAngel: HackRFInput Class Reference
HackRFInput Class Reference
#include <hackrfinput.h>
Classes
class MsgConfigureHackRF
class MsgFileRecord
class MsgReportHackRF
class MsgStartStop
Public Member Functions
HackRFInput (DeviceAPI *deviceAPI)
virtual ~HackRFInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
bool applySettings (const HackRFInputSettings &settings, bool force)
void setDeviceCenterFrequency (quint64 freq, qint32 LOppmTenths)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const HackRFInputSettings &settings)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const HackRFInputSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
HackRFInputSettings m_settings
struct hackrf_device * m_dev
HackRFInputThread * m_hackRFThread
QString m_deviceDescription
DeviceHackRFParams m_sharedParams
bool m_running
FileRecord * m_fileSink
File sink to record device I/Q output.
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 37 of file hackrfinput.h.
Constructor & Destructor Documentation
HackRFInput()
HackRFInput::HackRFInput (DeviceAPI * deviceAPI)
Definition at line 44 of file hackrfinput.cpp.
References arg().
Referenced by HackRFInput::MsgFileRecord::MsgFileRecord().
                                              :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_dev(0),
     m_hackRFThread(0),
     m_deviceDescription("HackRF"),
     m_running(false)
 {
     openDevice();
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     m_deviceAPI->setBuddySharedPtr(&m_sharedParams);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~HackRFInput()
HackRFInput::~HackRFInput () virtual
Definition at line 64 of file hackrfinput.cpp.
References closeDevice(), m_deviceAPI, m_fileSink, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::removeAncillarySink(), DeviceAPI::setBuddySharedPtr(), and stop().
Referenced by HackRFInput::MsgFileRecord::MsgFileRecord().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
     closeDevice();
     m_deviceAPI->setBuddySharedPtr(0);
 }
Member Function Documentation
applySettings()
bool HackRFInput::applySettings (const HackRFInputSettings & settings, bool force) private
Definition at line 365 of file hackrfinput.cpp.
References DeviceSampleSource::calculateDeviceCenterFrequency(), DeviceAPI::configureCorrections(), DeviceHackRFShared::MsgSynchronizeFrequency::create(), DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceAPI::getSamplingDeviceInputMessageQueue(), DeviceAPI::getSinkBuddies(), FileRecord::handleMessage(), HackRFInputSettings::m_bandwidth, HackRFInputSettings::m_biasT, HackRFInputSettings::m_centerFrequency, HackRFInputSettings::m_dcBlock, m_dev, m_deviceAPI, HackRFInputSettings::m_devSampleRate, HackRFInputSettings::m_fcPos, m_fileSink, m_hackRFThread, HackRFInputSettings::m_iqCorrection, HackRFInputSettings::m_lnaExt, HackRFInputSettings::m_lnaGain, HackRFInputSettings::m_log2Decim, HackRFInputSettings::m_LOppmTenths, HackRFInputSettings::m_reverseAPIAddress, HackRFInputSettings::m_reverseAPIDeviceIndex, HackRFInputSettings::m_reverseAPIPort, m_settings, HackRFInputSettings::m_useReverseAPI, HackRFInputSettings::m_vgaGain, MessageQueue::push(), setDeviceCenterFrequency(), HackRFInputThread::setFcPos(), HackRFInputThread::setLog2Decimation(), HackRFInputThread::setSamplerate(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
 //  QMutexLocker mutexLocker(&m_mutex);
     bool forwardChange = false;
     hackrf_error rc;
     QList<QString> reverseAPIKeys;
     qDebug() << "HackRFInput::applySettings";
     if ((m_settings.m_dcBlock != settings.m_dcBlock) || force) {
         reverseAPIKeys.append("dcBlock");
     }
     if ((m_settings.m_iqCorrection != settings.m_iqCorrection) || force) {
         reverseAPIKeys.append("iqCorrection");
     }
     if ((m_settings.m_dcBlock != settings.m_dcBlock) ||
         (m_settings.m_iqCorrection != settings.m_iqCorrection) || force)
     {
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqCorrection);
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || force)
     {
         reverseAPIKeys.append("devSampleRate");
         forwardChange = true;
         if (m_dev != 0)
         {
             rc = (hackrf_error) hackrf_set_sample_rate_manual(m_dev, settings.m_devSampleRate, 1);
             if (rc != HACKRF_SUCCESS)
             {
                 qCritical("HackRFInput::applySettings: could not set sample rate TO %llu S/s: %s", settings.m_devSampleRate, hackrf_error_name(rc));
             }
             else
             {
                 if (m_hackRFThread != 0)
                 {
                     qDebug("HackRFInput::applySettings: sample rate set to %llu S/s", settings.m_devSampleRate);
                     m_hackRFThread->setSamplerate(settings.m_devSampleRate);
                 }
             }
         }
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         reverseAPIKeys.append("log2Decim");
         forwardChange = true;
         if (m_hackRFThread != 0)
         {
             m_hackRFThread->setLog2Decimation(settings.m_log2Decim);
             qDebug() << "HackRFInput: set decimation to " << (1<<settings.m_log2Decim);
         }
     }
     if (force || (m_settings.m_centerFrequency != settings.m_centerFrequency)) {
         reverseAPIKeys.append("centerFrequency");
     }
     if ((m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force) {
         reverseAPIKeys.append("LOppmTenths");
     }
     if ((m_settings.m_fcPos != settings.m_fcPos) || force) {
         reverseAPIKeys.append("fcPos");
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency) ||
         (m_settings.m_devSampleRate != settings.m_devSampleRate) ||
         (m_settings.m_LOppmTenths != settings.m_LOppmTenths) ||
         (m_settings.m_log2Decim != settings.m_log2Decim) ||
         (m_settings.m_fcPos != settings.m_fcPos) || force)
     {
         qint64 deviceCenterFrequency = DeviceSampleSource::calculateDeviceCenterFrequency(
                 settings.m_centerFrequency,
                 0,
                 settings.m_log2Decim,
                 (DeviceSampleSource::fcPos_t) settings.m_fcPos,
                 settings.m_devSampleRate,
                 DeviceSampleSource::FrequencyShiftScheme::FSHIFT_TXSYNC,
                 false);
         setDeviceCenterFrequency(deviceCenterFrequency, settings.m_LOppmTenths);
         if (m_deviceAPI->getSinkBuddies().size() > 0) // forward to buddy if necessary
         {
             DeviceAPI *buddy = m_deviceAPI->getSinkBuddies()[0];
             DeviceHackRFShared::MsgSynchronizeFrequency *freqMsg = DeviceHackRFShared::MsgSynchronizeFrequency::create(deviceCenterFrequency);
             buddy->getSamplingDeviceInputMessageQueue()->push(freqMsg);
         }
         forwardChange = true;
     }
     if ((m_settings.m_fcPos != settings.m_fcPos) || force)
     {
         if (m_hackRFThread != 0)
         {
             m_hackRFThread->setFcPos((int) settings.m_fcPos);
             qDebug() << "HackRFInput: set fc pos (enum) to " << (int) settings.m_fcPos;
         }
     }
     if ((m_settings.m_lnaGain != settings.m_lnaGain) || force)
     {
         reverseAPIKeys.append("lnaGain");
         if (m_dev != 0)
         {
             rc = (hackrf_error) hackrf_set_lna_gain(m_dev, settings.m_lnaGain);
             if (rc != HACKRF_SUCCESS) {
                 qDebug("HackRFInput::applySettings: airspy_set_lna_gain failed: %s", hackrf_error_name(rc));
             } else {
                 qDebug() << "HackRFInput:applySettings: LNA gain set to " << settings.m_lnaGain;
             }
         }
     }
     if ((m_settings.m_vgaGain != settings.m_vgaGain) || force)
     {
         reverseAPIKeys.append("vgaGain");
         if (m_dev != 0)
         {
             rc = (hackrf_error) hackrf_set_vga_gain(m_dev, settings.m_vgaGain);
             if (rc != HACKRF_SUCCESS) {
                 qDebug("HackRFInput::applySettings: hackrf_set_vga_gain failed: %s", hackrf_error_name(rc));
             } else {
                 qDebug() << "HackRFInput:applySettings: VGA gain set to " << settings.m_vgaGain;
             }
         }
     }
     if ((m_settings.m_bandwidth != settings.m_bandwidth) || force)
     {
         reverseAPIKeys.append("bandwidth");
         if (m_dev != 0)
         {
             uint32_t bw_index = hackrf_compute_baseband_filter_bw_round_down_lt(settings.m_bandwidth + 1); // +1 so the round down to lower than yields desired bandwidth
             rc = (hackrf_error) hackrf_set_baseband_filter_bandwidth(m_dev, bw_index);
             if (rc != HACKRF_SUCCESS) {
                 qDebug("HackRFInput::applySettings: hackrf_set_baseband_filter_bandwidth failed: %s", hackrf_error_name(rc));
             } else {
                 qDebug() << "HackRFInput:applySettings: Baseband BW filter set to " << settings.m_bandwidth << " Hz";
             }
         }
     }
     if ((m_settings.m_biasT != settings.m_biasT) || force)
     {
         reverseAPIKeys.append("biasT");
         if (m_dev != 0)
         {
             rc = (hackrf_error) hackrf_set_antenna_enable(m_dev, (settings.m_biasT ? 1 : 0));
             if (rc != HACKRF_SUCCESS) {
                 qDebug("HackRFInput::applySettings: hackrf_set_antenna_enable failed: %s", hackrf_error_name(rc));
             } else {
                 qDebug() << "HackRFInput:applySettings: bias tee set to " << settings.m_biasT;
             }
         }
     }
     if ((m_settings.m_lnaExt != settings.m_lnaExt) || force)
     {
         reverseAPIKeys.append("lnaExt");
         if (m_dev != 0)
         {
             rc = (hackrf_error) hackrf_set_amp_enable(m_dev, (settings.m_lnaExt ? 1 : 0));
             if (rc != HACKRF_SUCCESS) {
                 qDebug("HackRFInput::applySettings: hackrf_set_amp_enable failed: %s", hackrf_error_name(rc));
             } else {
                 qDebug() << "HackRFInput:applySettings: extra LNA set to " << settings.m_lnaExt;
             }
         }
     }
     if (forwardChange)
     {
         int sampleRate = settings.m_devSampleRate/(1<<settings.m_log2Decim);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     qDebug() << "HackRFInput::applySettings: "
             << " m_centerFrequency: " << m_settings.m_centerFrequency << " Hz"
             << " m_LOppmTenths: " << m_settings.m_LOppmTenths
             << " m_bandwidth: " << m_settings.m_bandwidth
             << " m_lnaGain: " << m_settings.m_lnaGain
             << " m_vgaGain: " << m_settings.m_vgaGain
             << " m_log2Decim: " << m_settings.m_log2Decim
             << " m_fcPos: " << m_settings.m_fcPos
             << " m_devSampleRate: " << m_settings.m_devSampleRate
             << " m_biasT: " << m_settings.m_biasT
             << " m_lnaExt: " << m_settings.m_lnaExt
             << " m_dcBlock: " << m_settings.m_dcBlock;
     return true;
 }
closeDevice()
void HackRFInput::closeDevice () private
Definition at line 165 of file hackrfinput.cpp.
References DeviceAPI::getSinkBuddies(), DeviceHackRFParams::m_dev, m_dev, m_deviceAPI, and m_sharedParams.
Referenced by openDevice(), and ~HackRFInput().
 {
     if (m_deviceAPI->getSinkBuddies().size() == 0)
     {
         qDebug("HackRFInput::closeDevice: closing device since Tx side is not open");
         if(m_dev != 0) // close BladeRF
         {
             hackrf_close(m_dev);
             //hackrf_exit(); // TODO: this may not work if several HackRF Devices are running concurrently. It should be handled globally in the application
         }
     }
     m_sharedParams.m_dev = 0;
     m_dev = 0;
 }
deserialize()
bool HackRFInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 202 of file hackrfinput.cpp.
References HackRFInput::MsgConfigureHackRF::create(), HackRFInputSettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and HackRFInputSettings::resetToDefaults().
Referenced by HackRFInput::MsgFileRecord::MsgFileRecord().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureHackRF* message = MsgConfigureHackRF::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureHackRF* messageToGUI = MsgConfigureHackRF::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void HackRFInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 79 of file hackrfinput.cpp.
Referenced by HackRFInput::MsgFileRecord::MsgFileRecord().
 {
     delete this;
 }
getCenterFrequency()
quint64 HackRFInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 234 of file hackrfinput.cpp.
References HackRFInputSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & HackRFInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 224 of file hackrfinput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getSampleRate()
int HackRFInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 229 of file hackrfinput.cpp.
References HackRFInputSettings::m_devSampleRate, HackRFInputSettings::m_log2Decim, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     return (m_settings.m_devSampleRate / (1<<m_settings.m_log2Decim));
 }
handleMessage()
bool HackRFInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 254 of file hackrfinput.cpp.
References applySettings(), DeviceSampleSource::calculateCenterFrequency(), HackRFInput::MsgConfigureHackRF::create(), DeviceSampleSource::FSHIFT_TXSYNC, FileRecord::genUniqueFileName(), DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceAPI::getDeviceUID(), HackRFInput::MsgConfigureHackRF::getForce(), DeviceHackRFShared::MsgSynchronizeFrequency::getFrequency(), HackRFInput::MsgConfigureHackRF::getSettings(), HackRFInput::MsgStartStop::getStartStop(), HackRFInput::MsgFileRecord::getStartStop(), FileRecord::handleMessage(), DeviceAPI::initDeviceEngine(), HackRFInputSettings::m_centerFrequency, m_deviceAPI, HackRFInputSettings::m_devSampleRate, HackRFInputSettings::m_fcPos, HackRFInputSettings::m_fileRecordName, m_fileSink, DeviceSampleSource::m_guiMessageQueue, HackRFInputSettings::m_log2Decim, m_settings, HackRFInputSettings::m_useReverseAPI, Message::match(), MessageQueue::push(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (MsgConfigureHackRF::match(message))
     {
         MsgConfigureHackRF& conf = (MsgConfigureHackRF&) message;
         qDebug() << "HackRFInput::handleMessage: MsgConfigureHackRF";
         bool success = applySettings(conf.getSettings(), conf.getForce());
         if (!success)
         {
             qDebug("HackRFInput::handleMessage: config error");
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "HackRFInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "HackRFInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else if (DeviceHackRFShared::MsgSynchronizeFrequency::match(message))
     {
         DeviceHackRFShared::MsgSynchronizeFrequency& freqMsg = (DeviceHackRFShared::MsgSynchronizeFrequency&) message;
         qint64 centerFrequency = DeviceSampleSource::calculateCenterFrequency(
             freqMsg.getFrequency(),
             0,
             m_settings.m_log2Decim,
             (DeviceSampleSource::fcPos_t) m_settings.m_fcPos,
             m_settings.m_devSampleRate,
             DeviceSampleSource::FSHIFT_TXSYNC);
         qDebug("HackRFInput::handleMessage: MsgSynchronizeFrequency: centerFrequency: %lld Hz", centerFrequency);
         HackRFInputSettings settings = m_settings;
         settings.m_centerFrequency = centerFrequency;
         if (m_guiMessageQueue)
         {
             MsgConfigureHackRF* messageToGUI = MsgConfigureHackRF::create(settings, false);
             m_guiMessageQueue->push(messageToGUI);
         }
         m_settings.m_centerFrequency = settings.m_centerFrequency;
         int sampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Decim);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, m_settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void HackRFInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 131 of file hackrfinput.cpp.
References applySettings(), and m_settings.
Referenced by HackRFInput::MsgFileRecord::MsgFileRecord().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void HackRFInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 832 of file hackrfinput.cpp.
Referenced by ~HackRFInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "HackRFInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("HackRFInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openDevice()
bool HackRFInput::openDevice () private
Definition at line 84 of file hackrfinput.cpp.
References closeDevice(), DeviceAPI::getBuddySharedPtr(), DeviceAPI::getSamplingDeviceSerial(), DeviceAPI::getSinkBuddies(), DeviceHackRFParams::m_dev, m_dev, m_deviceAPI, DeviceSampleSource::m_sampleFifo, m_sharedParams, DeviceHackRF::open_hackrf(), and SampleSinkFifo::setSize().
 {
     if (m_dev != 0)
     {
         closeDevice();
     }
     if (!m_sampleFifo.setSize(1<<19))
     {
         qCritical("HackRFInput::start: could not allocate SampleFifo");
         return false;
     }
     if (m_deviceAPI->getSinkBuddies().size() > 0)
     {
         DeviceAPI *buddy = m_deviceAPI->getSinkBuddies()[0];
         DeviceHackRFParams *buddySharedParams = (DeviceHackRFParams *) buddy->getBuddySharedPtr();
         if (buddySharedParams == 0)
         {
             qCritical("HackRFInput::openDevice: could not get shared parameters from buddy");
             return false;
         }
         if (buddySharedParams->m_dev == 0) // device is not opened by buddy
         {
             qCritical("HackRFInput::openDevice: could not get HackRF handle from buddy");
             return false;
         }
         m_sharedParams = *(buddySharedParams); // copy parameters from buddy
         m_dev = m_sharedParams.m_dev;          // get HackRF handle
     }
     else
     {
         if ((m_dev = DeviceHackRF::open_hackrf(qPrintable(m_deviceAPI->getSamplingDeviceSerial()))) == 0)
         {
             qCritical("HackRFInput::openDevice: could not open HackRF %s", qPrintable(m_deviceAPI->getSamplingDeviceSerial()));
             return false;
         }
         m_sharedParams.m_dev = m_dev;
     }
     return true;
 }
serialize()
QByteArray HackRFInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 197 of file hackrfinput.cpp.
References m_settings, and HackRFInputSettings::serialize().
Referenced by HackRFInput::MsgFileRecord::MsgFileRecord().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void HackRFInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 239 of file hackrfinput.cpp.
References HackRFInput::MsgConfigureHackRF::create(), HackRFInputSettings::m_centerFrequency, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     HackRFInputSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureHackRF* message = MsgConfigureHackRF::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureHackRF* messageToGUI = MsgConfigureHackRF::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setDeviceCenterFrequency()
void HackRFInput::setDeviceCenterFrequency (quint64 freq, qint32 LOppmTenths) private
Definition at line 349 of file hackrfinput.cpp.
References m_dev.
Referenced by applySettings().
 {
     if (!m_dev) {
         return;
     }
     qint64 df = ((qint64)freq_hz * LOppmTenths) / 10000000LL;
     hackrf_error rc = (hackrf_error) hackrf_set_freq(m_dev, static_cast<uint64_t>(freq_hz + df));
     if (rc != HACKRF_SUCCESS) {
         qWarning("HackRFInput::setDeviceCenterFrequency: could not frequency to %llu Hz", freq_hz + df);
     } else {
         qDebug("HackRFInput::setDeviceCenterFrequency: frequency set to %llu Hz", freq_hz + df);
     }
 }
setMessageQueueToGUI()
virtual void HackRFInput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 130 of file hackrfinput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSource::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void HackRFInput::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 133 of file hackrfinput.h.
References getCenterFrequency(), handleMessage(), setCenterFrequency(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
start()
bool HackRFInput::start () virtual
Implements DeviceSampleSource.
Definition at line 136 of file hackrfinput.cpp.
References applySettings(), m_dev, HackRFInputSettings::m_devSampleRate, HackRFInputSettings::m_fcPos, m_hackRFThread, HackRFInputSettings::m_log2Decim, m_running, DeviceSampleSource::m_sampleFifo, m_settings, HackRFInputThread::setFcPos(), HackRFInputThread::setLog2Decimation(), HackRFInputThread::setSamplerate(), HackRFInputThread::startWork(), and stop().
Referenced by HackRFInput::MsgFileRecord::MsgFileRecord().
 {
 //  QMutexLocker mutexLocker(&m_mutex);
     if (!m_dev) {
         return false;
     }
     if (m_running) {
         stop();
     }
     m_hackRFThread = new HackRFInputThread(m_dev, &m_sampleFifo);
 //  mutexLocker.unlock();
     applySettings(m_settings, true);
     m_hackRFThread->setSamplerate(m_settings.m_devSampleRate);
     m_hackRFThread->setLog2Decimation(m_settings.m_log2Decim);
     m_hackRFThread->setFcPos((int) m_settings.m_fcPos);
     m_hackRFThread->startWork();
     qDebug("HackRFInput::startInput: started");
     m_running = true;
     return true;
 }
stop()
void HackRFInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 182 of file hackrfinput.cpp.
References m_hackRFThread, m_running, and HackRFInputThread::stopWork().
Referenced by HackRFInput::MsgFileRecord::MsgFileRecord(), start(), and ~HackRFInput().
 {
     qDebug("HackRFInput::stop");
 //  QMutexLocker mutexLocker(&m_mutex);
     if (m_hackRFThread != 0)
     {
         m_hackRFThread->stopWork();
         delete m_hackRFThread;
         m_hackRFThread = 0;
     }
     m_running = false;
 }
webapiFormatDeviceSettings()
void HackRFInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const HackRFInputSettings & settings) private
Definition at line 674 of file hackrfinput.cpp.
References SWGSDRangel::SWGHackRFInputSettings::getFileRecordName(), SWGSDRangel::SWGDeviceSettings::getHackRfInputSettings(), SWGSDRangel::SWGHackRFInputSettings::getReverseApiAddress(), HackRFInputSettings::m_bandwidth, HackRFInputSettings::m_biasT, HackRFInputSettings::m_centerFrequency, HackRFInputSettings::m_dcBlock, HackRFInputSettings::m_devSampleRate, HackRFInputSettings::m_fcPos, HackRFInputSettings::m_fileRecordName, HackRFInputSettings::m_iqCorrection, HackRFInputSettings::m_lnaExt, HackRFInputSettings::m_lnaGain, HackRFInputSettings::m_log2Decim, HackRFInputSettings::m_LOppmTenths, HackRFInputSettings::m_reverseAPIAddress, HackRFInputSettings::m_reverseAPIDeviceIndex, HackRFInputSettings::m_reverseAPIPort, HackRFInputSettings::m_useReverseAPI, HackRFInputSettings::m_vgaGain, SWGSDRangel::SWGHackRFInputSettings::setBandwidth(), SWGSDRangel::SWGHackRFInputSettings::setBiasT(), SWGSDRangel::SWGHackRFInputSettings::setCenterFrequency(), SWGSDRangel::SWGHackRFInputSettings::setDcBlock(), SWGSDRangel::SWGHackRFInputSettings::setDevSampleRate(), SWGSDRangel::SWGHackRFInputSettings::setFcPos(), SWGSDRangel::SWGHackRFInputSettings::setFileRecordName(), SWGSDRangel::SWGHackRFInputSettings::setIqCorrection(), SWGSDRangel::SWGHackRFInputSettings::setLnaExt(), SWGSDRangel::SWGHackRFInputSettings::setLnaGain(), SWGSDRangel::SWGHackRFInputSettings::setLog2Decim(), SWGSDRangel::SWGHackRFInputSettings::setLOppmTenths(), SWGSDRangel::SWGHackRFInputSettings::setReverseApiAddress(), SWGSDRangel::SWGHackRFInputSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGHackRFInputSettings::setReverseApiPort(), SWGSDRangel::SWGHackRFInputSettings::setUseReverseApi(), and SWGSDRangel::SWGHackRFInputSettings::setVgaGain().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getHackRfInputSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getHackRfInputSettings()->setLOppmTenths(settings.m_LOppmTenths);
     response.getHackRfInputSettings()->setBandwidth(settings.m_bandwidth);
     response.getHackRfInputSettings()->setLnaGain(settings.m_lnaGain);
     response.getHackRfInputSettings()->setVgaGain(settings.m_vgaGain);
     response.getHackRfInputSettings()->setLog2Decim(settings.m_log2Decim);
     response.getHackRfInputSettings()->setFcPos(settings.m_fcPos);
     response.getHackRfInputSettings()->setDevSampleRate(settings.m_devSampleRate);
     response.getHackRfInputSettings()->setBiasT(settings.m_biasT ? 1 : 0);
     response.getHackRfInputSettings()->setLnaExt(settings.m_lnaExt ? 1 : 0);
     response.getHackRfInputSettings()->setDcBlock(settings.m_dcBlock ? 1 : 0);
     response.getHackRfInputSettings()->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     if (response.getHackRfInputSettings()->getFileRecordName()) {
         *response.getHackRfInputSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getHackRfInputSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getHackRfInputSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getHackRfInputSettings()->getReverseApiAddress()) {
         *response.getHackRfInputSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getHackRfInputSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getHackRfInputSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getHackRfInputSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReverseSendSettings()
void HackRFInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const HackRFInputSettings & settings, bool force) private
Definition at line 735 of file hackrfinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getHackRfInputSettings(), HackRFInputSettings::m_bandwidth, HackRFInputSettings::m_biasT, HackRFInputSettings::m_centerFrequency, HackRFInputSettings::m_dcBlock, m_deviceAPI, HackRFInputSettings::m_devSampleRate, HackRFInputSettings::m_fcPos, HackRFInputSettings::m_fileRecordName, HackRFInputSettings::m_iqCorrection, HackRFInputSettings::m_lnaExt, HackRFInputSettings::m_lnaGain, HackRFInputSettings::m_log2Decim, HackRFInputSettings::m_LOppmTenths, m_networkManager, m_networkRequest, HackRFInputSettings::m_reverseAPIAddress, HackRFInputSettings::m_reverseAPIDeviceIndex, HackRFInputSettings::m_reverseAPIPort, HackRFInputSettings::m_vgaGain, SWGSDRangel::SWGHackRFInputSettings::setBandwidth(), SWGSDRangel::SWGHackRFInputSettings::setBiasT(), SWGSDRangel::SWGHackRFInputSettings::setCenterFrequency(), SWGSDRangel::SWGHackRFInputSettings::setDcBlock(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGHackRFInputSettings::setDevSampleRate(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGHackRFInputSettings::setFcPos(), SWGSDRangel::SWGHackRFInputSettings::setFileRecordName(), SWGSDRangel::SWGDeviceSettings::setHackRfInputSettings(), SWGSDRangel::SWGHackRFInputSettings::setIqCorrection(), SWGSDRangel::SWGHackRFInputSettings::setLnaExt(), SWGSDRangel::SWGHackRFInputSettings::setLnaGain(), SWGSDRangel::SWGHackRFInputSettings::setLog2Decim(), SWGSDRangel::SWGHackRFInputSettings::setLOppmTenths(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), and SWGSDRangel::SWGHackRFInputSettings::setVgaGain().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("HackRF"));
     swgDeviceSettings->setHackRfInputSettings(new SWGSDRangel::SWGHackRFInputSettings());
     SWGSDRangel::SWGHackRFInputSettings *swgHackRFInputSettings = swgDeviceSettings->getHackRfInputSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgHackRFInputSettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("LOppmTenths") || force) {
         swgHackRFInputSettings->setLOppmTenths(settings.m_LOppmTenths);
     }
     if (deviceSettingsKeys.contains("bandwidth") || force) {
         swgHackRFInputSettings->setBandwidth(settings.m_bandwidth);
     }
     if (deviceSettingsKeys.contains("lnaGain") || force) {
         swgHackRFInputSettings->setLnaGain(settings.m_lnaGain);
     }
     if (deviceSettingsKeys.contains("vgaGain") || force) {
         swgHackRFInputSettings->setVgaGain(settings.m_vgaGain);
     }
     if (deviceSettingsKeys.contains("log2Decim") || force) {
         swgHackRFInputSettings->setLog2Decim(settings.m_log2Decim);
     }
     if (deviceSettingsKeys.contains("fcPos") || force) {
         swgHackRFInputSettings->setFcPos((int) settings.m_fcPos);
     }
     if (deviceSettingsKeys.contains("devSampleRate") || force) {
         swgHackRFInputSettings->setDevSampleRate(settings.m_devSampleRate);
     }
     if (deviceSettingsKeys.contains("biasT") || force) {
         swgHackRFInputSettings->setBiasT(settings.m_biasT ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("lnaExt") || force) {
         swgHackRFInputSettings->setLnaExt(settings.m_lnaExt ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("dcBlock") || force) {
         swgHackRFInputSettings->setDcBlock(settings.m_dcBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("iqCorrection") || force) {
         swgHackRFInputSettings->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgHackRFInputSettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void HackRFInput::webapiReverseSendStartStop (bool start) private
Definition at line 804 of file hackrfinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, HackRFInputSettings::m_reverseAPIAddress, HackRFInputSettings::m_reverseAPIDeviceIndex, HackRFInputSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("HackRF"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int HackRFInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 716 of file hackrfinput.cpp.
References HackRFInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int HackRFInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 707 of file hackrfinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int HackRFInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 586 of file hackrfinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getHackRfInputSettings(), SWGSDRangel::SWGHackRFInputSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setHackRfInputSettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setHackRfInputSettings(new SWGSDRangel::SWGHackRFInputSettings());
     response.getHackRfInputSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int HackRFInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 597 of file hackrfinput.cpp.
References HackRFInput::MsgConfigureHackRF::create(), SWGSDRangel::SWGHackRFInputSettings::getBandwidth(), SWGSDRangel::SWGHackRFInputSettings::getBiasT(), SWGSDRangel::SWGHackRFInputSettings::getCenterFrequency(), SWGSDRangel::SWGHackRFInputSettings::getDcBlock(), SWGSDRangel::SWGHackRFInputSettings::getDevSampleRate(), SWGSDRangel::SWGHackRFInputSettings::getFcPos(), SWGSDRangel::SWGHackRFInputSettings::getFileRecordName(), SWGSDRangel::SWGDeviceSettings::getHackRfInputSettings(), SWGSDRangel::SWGHackRFInputSettings::getIqCorrection(), SWGSDRangel::SWGHackRFInputSettings::getLnaExt(), SWGSDRangel::SWGHackRFInputSettings::getLnaGain(), SWGSDRangel::SWGHackRFInputSettings::getLog2Decim(), SWGSDRangel::SWGHackRFInputSettings::getLOppmTenths(), SWGSDRangel::SWGHackRFInputSettings::getReverseApiAddress(), SWGSDRangel::SWGHackRFInputSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGHackRFInputSettings::getReverseApiPort(), SWGSDRangel::SWGHackRFInputSettings::getUseReverseApi(), SWGSDRangel::SWGHackRFInputSettings::getVgaGain(), HackRFInputSettings::m_bandwidth, HackRFInputSettings::m_biasT, HackRFInputSettings::m_centerFrequency, HackRFInputSettings::m_dcBlock, HackRFInputSettings::m_devSampleRate, HackRFInputSettings::m_fcPos, HackRFInputSettings::m_fileRecordName, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, HackRFInputSettings::m_iqCorrection, HackRFInputSettings::m_lnaExt, HackRFInputSettings::m_lnaGain, HackRFInputSettings::m_log2Decim, HackRFInputSettings::m_LOppmTenths, HackRFInputSettings::m_reverseAPIAddress, HackRFInputSettings::m_reverseAPIDeviceIndex, HackRFInputSettings::m_reverseAPIPort, m_settings, HackRFInputSettings::m_useReverseAPI, HackRFInputSettings::m_vgaGain, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     HackRFInputSettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getHackRfInputSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("LOppmTenths")) {
         settings.m_LOppmTenths = response.getHackRfInputSettings()->getLOppmTenths();
     }
     if (deviceSettingsKeys.contains("bandwidth")) {
         settings.m_bandwidth = response.getHackRfInputSettings()->getBandwidth();
     }
     if (deviceSettingsKeys.contains("lnaGain")) {
         settings.m_lnaGain = response.getHackRfInputSettings()->getLnaGain();
     }
     if (deviceSettingsKeys.contains("vgaGain")) {
         settings.m_vgaGain = response.getHackRfInputSettings()->getVgaGain();
     }
     if (deviceSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getHackRfInputSettings()->getLog2Decim();
     }
     if (deviceSettingsKeys.contains("fcPos"))
     {
         int fcPos = response.getHackRfInputSettings()->getFcPos();
         fcPos = fcPos < 0 ? 0 : fcPos > 2 ? 2 : fcPos;
         settings.m_fcPos = (HackRFInputSettings::fcPos_t) fcPos;
     }
     if (deviceSettingsKeys.contains("devSampleRate")) {
         settings.m_devSampleRate = response.getHackRfInputSettings()->getDevSampleRate();
     }
     if (deviceSettingsKeys.contains("biasT")) {
         settings.m_biasT = response.getHackRfInputSettings()->getBiasT() != 0;
     }
     if (deviceSettingsKeys.contains("lnaExt")) {
         settings.m_lnaExt = response.getHackRfInputSettings()->getLnaExt() != 0;
     }
     if (deviceSettingsKeys.contains("dcBlock")) {
         settings.m_dcBlock = response.getHackRfInputSettings()->getDcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("iqCorrection")) {
         settings.m_iqCorrection = response.getHackRfInputSettings()->getIqCorrection() != 0;
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getHackRfInputSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getHackRfInputSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getHackRfInputSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getHackRfInputSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getHackRfInputSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureHackRF *msg = MsgConfigureHackRF::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureHackRF *msgToGUI = MsgConfigureHackRF::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_dev
struct hackrf_device* HackRFInput::m_dev private
Definition at line 163 of file hackrfinput.h.
Referenced by applySettings(), closeDevice(), openDevice(), setDeviceCenterFrequency(), and start().
m_deviceAPI
DeviceAPI* HackRFInput::m_deviceAPI private
Definition at line 160 of file hackrfinput.h.
Referenced by applySettings(), closeDevice(), handleMessage(), openDevice(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~HackRFInput().
m_deviceDescription
QString HackRFInput::m_deviceDescription private
Definition at line 165 of file hackrfinput.h.
Referenced by getDeviceDescription().
m_fileSink
FileRecord* HackRFInput::m_fileSink private
File sink to record device I/Q output.
Definition at line 168 of file hackrfinput.h.
Referenced by applySettings(), handleMessage(), and ~HackRFInput().
m_hackRFThread
HackRFInputThread* HackRFInput::m_hackRFThread private
Definition at line 164 of file hackrfinput.h.
Referenced by applySettings(), start(), and stop().
m_mutex
QMutex HackRFInput::m_mutex private
Definition at line 161 of file hackrfinput.h.
m_networkManager
QNetworkAccessManager* HackRFInput::m_networkManager private
Definition at line 169 of file hackrfinput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~HackRFInput().
m_networkRequest
QNetworkRequest HackRFInput::m_networkRequest private
Definition at line 170 of file hackrfinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool HackRFInput::m_running private
Definition at line 167 of file hackrfinput.h.
Referenced by start(), stop(), and ~HackRFInput().
m_settings
HackRFInputSettings HackRFInput::m_settings private
Definition at line 162 of file hackrfinput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), serialize(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_sharedParams
DeviceHackRFParams HackRFInput::m_sharedParams private
Definition at line 166 of file hackrfinput.h.
Referenced by closeDevice(), and openDevice().
The documentation for this class was generated from the following files:
plugins/samplesource/hackrfinput/hackrfinput.h
plugins/samplesource/hackrfinput/hackrfinput.cpp