SDRAngel: FreeDVMod::MsgConfigureChannelizer Class Reference
FreeDVMod::MsgConfigureChannelizer Class Reference
#include <freedvmod.h>
Public Member Functions
int getSampleRate () const
int getCenterFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (int sampleRate, int centerFrequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (int sampleRate, int centerFrequency)
Private Attributes
int m_sampleRate
int m_centerFrequency
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 78 of file freedvmod.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
FreeDVMod::MsgConfigureChannelizer::MsgConfigureChannelizer (int sampleRate, int centerFrequency) inline private
Definition at line 94 of file freedvmod.h.
                                                                      :
             Message(),
             m_sampleRate(sampleRate),
             m_centerFrequency(centerFrequency)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* FreeDVMod::MsgConfigureChannelizer::create (int sampleRate, int centerFrequency) inline static
Definition at line 85 of file freedvmod.h.
Referenced by FreeDVMod::applyFreeDVMode(), FreeDVModGUI::applySettings(), and FreeDVMod::webapiSettingsPutPatch().
         {
             return new MsgConfigureChannelizer(sampleRate, centerFrequency);
         }
getCenterFrequency()
int FreeDVMod::MsgConfigureChannelizer::getCenterFrequency () const inline
Definition at line 83 of file freedvmod.h.
Referenced by FreeDVMod::handleMessage().
 { return m_centerFrequency; }
getSampleRate()
int FreeDVMod::MsgConfigureChannelizer::getSampleRate () const inline
Definition at line 82 of file freedvmod.h.
Referenced by FreeDVMod::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_centerFrequency
int FreeDVMod::MsgConfigureChannelizer::m_centerFrequency private
Definition at line 92 of file freedvmod.h.
m_sampleRate
int FreeDVMod::MsgConfigureChannelizer::m_sampleRate private
Definition at line 91 of file freedvmod.h.
The documentation for this class was generated from the following file:
plugins/channeltx/modfreedv/freedvmod.h