SDRAngel: qrtplib::RTCPSenderReportInfo Class Reference
qrtplib::RTCPSenderReportInfo Class Reference
#include <rtpsourcedata.h>
Public Member Functions
RTCPSenderReportInfo ()
void Set (const RTPNTPTime &ntptime, uint32_t rtptime, uint32_t pcount, uint32_t bcount, const RTPTime &rcvtime)
bool HasInfo () const
RTPNTPTime GetNTPTimestamp () const
uint32_t GetRTPTimestamp () const
uint32_t GetPacketCount () const
uint32_t GetByteCount () const
RTPTime GetReceiveTime () const
Private Attributes
bool hasinfo
RTPNTPTime ntptimestamp
uint32_t rtptimestamp
uint32_t packetcount
uint32_t bytecount
RTPTime receivetime
Detailed Description
Definition at line 56 of file rtpsourcedata.h.
Constructor & Destructor Documentation
RTCPSenderReportInfo()
qrtplib::RTCPSenderReportInfo::RTCPSenderReportInfo () inline
Definition at line 59 of file rtpsourcedata.h.
                            :
             ntptimestamp(0, 0), receivetime(0, 0)
     {
         hasinfo = false;
         rtptimestamp = 0;
         packetcount = 0;
         bytecount = 0;
     }
Member Function Documentation
GetByteCount()
uint32_t qrtplib::RTCPSenderReportInfo::GetByteCount () const inline
Definition at line 93 of file rtpsourcedata.h.
     {
         return bytecount;
     }
GetNTPTimestamp()
RTPNTPTime qrtplib::RTCPSenderReportInfo::GetNTPTimestamp () const inline
Definition at line 81 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSourceData::INF_GetEstimatedTimestampUnit().
     {
         return ntptimestamp;
     }
GetPacketCount()
uint32_t qrtplib::RTCPSenderReportInfo::GetPacketCount () const inline
Definition at line 89 of file rtpsourcedata.h.
     {
         return packetcount;
     }
GetReceiveTime()
RTPTime qrtplib::RTCPSenderReportInfo::GetReceiveTime () const inline
Definition at line 97 of file rtpsourcedata.h.
     {
         return receivetime;
     }
GetRTPTimestamp()
uint32_t qrtplib::RTCPSenderReportInfo::GetRTPTimestamp () const inline
Definition at line 85 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSourceData::INF_GetEstimatedTimestampUnit().
     {
         return rtptimestamp;
     }
HasInfo()
bool qrtplib::RTCPSenderReportInfo::HasInfo () const inline
Definition at line 77 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSourceData::INF_GetEstimatedTimestampUnit().
     {
         return hasinfo;
     }
Set()
void qrtplib::RTCPSenderReportInfo::Set (const RTPNTPTime & ntptime, uint32_t rtptime, uint32_t pcount, uint32_t bcount, const RTPTime & rcvtime) inline
Definition at line 67 of file rtpsourcedata.h.
     {
         ntptimestamp = ntptime;
         rtptimestamp = rtptime;
         packetcount = pcount;
         bytecount = bcount;
         receivetime = rcvtime;
         hasinfo = true;
     }
Member Data Documentation
bytecount
uint32_t qrtplib::RTCPSenderReportInfo::bytecount private
Definition at line 106 of file rtpsourcedata.h.
hasinfo
bool qrtplib::RTCPSenderReportInfo::hasinfo private
Definition at line 102 of file rtpsourcedata.h.
ntptimestamp
RTPNTPTime qrtplib::RTCPSenderReportInfo::ntptimestamp private
Definition at line 103 of file rtpsourcedata.h.
packetcount
uint32_t qrtplib::RTCPSenderReportInfo::packetcount private
Definition at line 105 of file rtpsourcedata.h.
receivetime
RTPTime qrtplib::RTCPSenderReportInfo::receivetime private
Definition at line 107 of file rtpsourcedata.h.
rtptimestamp
uint32_t qrtplib::RTCPSenderReportInfo::rtptimestamp private
Definition at line 104 of file rtpsourcedata.h.
The documentation for this class was generated from the following file:
qrtplib/rtpsourcedata.h