SDRAngel: DATVideostream Class Reference
DATVideostream Class Reference
#include <datvideostream.h>
Inherits QIODevice.
Signals
void onDataAvailable ()
void onDataPackets (int *intDataPackets, int *intDataBytes, int *intPercentBuffer, qint64 *intTotalReceived)
Public Member Functions
DATVideostream ()
~DATVideostream ()
int pushData (const char *chrData, int intSize)
bool setMemoryLimit (int intMemoryLimit)
virtual bool isSequential () const
virtual qint64 bytesAvailable () const
virtual void close ()
virtual bool open (OpenMode mode)
Public Attributes
bool MultiThreaded
int ThreadTimeOut
QQueue< QByteArray > m_objFIFO
Protected Member Functions
virtual qint64 readData (char *data, qint64 len)
virtual qint64 writeData (const char *data, qint64 len)
virtual qint64 readLineData (char *data, qint64 maxSize)
Private Member Functions
void cleanUp ()
Private Attributes
QEventLoop m_objeventLoop
QMutex m_objMutex
int m_intMemoryLimit
int m_intBytesAvailable
int m_intBytesWaiting
int m_intQueueWaiting
int m_intPercentBuffer
qint64 m_intTotalReceived
qint64 m_intPacketReceived
Detailed Description
Definition at line 32 of file datvideostream.h.
Constructor & Destructor Documentation
DATVideostream()
DATVideostream::DATVideostream ()
Definition at line 22 of file datvideostream.cpp.
References cleanUp(), DefaultMemoryLimit, m_intMemoryLimit, m_intPacketReceived, m_intTotalReceived, m_objeventLoop, MultiThreaded, onDataAvailable(), and ThreadTimeOut.
                               :
     m_objMutex(QMutex::NonRecursive)
 {
     cleanUp();
     m_intTotalReceived = 0;
     m_intPacketReceived = 0;
     m_intMemoryLimit = DefaultMemoryLimit;
     MultiThreaded = false;
     ThreadTimeOut = -1;
     m_objeventLoop.connect(this,SIGNAL(onDataAvailable()), &m_objeventLoop, SLOT(quit()),Qt::QueuedConnection);
 }
~DATVideostream()
DATVideostream::~DATVideostream ()
Definition at line 35 of file datvideostream.cpp.
References cleanUp(), m_objeventLoop, and onDataAvailable().
 {
     m_objeventLoop.disconnect(this,SIGNAL(onDataAvailable()), &m_objeventLoop, SLOT(quit()));
     cleanUp();
 }
Member Function Documentation
bytesAvailable()
qint64 DATVideostream::bytesAvailable () const virtual
Definition at line 115 of file datvideostream.cpp.
References m_intBytesAvailable.
Referenced by DATVideoRender::OpenStream(), and DATVDemod::PlayVideo().
 {
     return m_intBytesAvailable;
 }
cleanUp()
void DATVideostream::cleanUp () private
Definition at line 41 of file datvideostream.cpp.
References m_intBytesAvailable, m_intBytesWaiting, m_intPercentBuffer, m_intQueueWaiting, m_objeventLoop, and m_objFIFO.
Referenced by close(), DATVideostream(), and ~DATVideostream().
 {
     if (m_objFIFO.size() > 0) {
         m_objFIFO.clear();
     }
     if (m_objeventLoop.isRunning()) {
         m_objeventLoop.exit();
     }
     m_intBytesAvailable = 0;
     m_intBytesWaiting = 0;
     m_intQueueWaiting = 0;
     m_intPercentBuffer = 0;
 }
close()
void DATVideostream::close () virtual
Definition at line 120 of file datvideostream.cpp.
References cleanUp().
 {
     QIODevice::close();
     cleanUp();
 }
isSequential()
bool DATVideostream::isSequential () const virtual
Definition at line 110 of file datvideostream.cpp.
 {
     return true;
 }
onDataAvailable
void DATVideostream::onDataAvailable () signal
Referenced by DATVideostream(), pushData(), and ~DATVideostream().
onDataPackets
void DATVideostream::onDataPackets (int * intDataPackets, int * intDataBytes, int * intPercentBuffer, qint64 * intTotalReceived) signal
Referenced by DATVDemodGUI::DATVDemodGUI(), pushData(), and readData().
open()
bool DATVideostream::open (OpenMode mode) virtual
Definition at line 126 of file datvideostream.cpp.
Referenced by DATVideoRender::OpenStream().
 {
     //cleanUp();
     return QIODevice::open(mode);
 }
pushData()
int DATVideostream::pushData (const char * chrData, int intSize)
Definition at line 68 of file datvideostream.cpp.
References m_intBytesAvailable, m_intBytesWaiting, m_intMemoryLimit, m_intPacketReceived, m_intPercentBuffer, m_intQueueWaiting, m_intTotalReceived, m_objeventLoop, m_objFIFO, m_objMutex, MinStackSize, onDataAvailable(), and onDataPackets().
Referenced by leansdr::datvvideoplayer< leansdr::tspacket >::run().
 {
     if (intSize <= 0) {
         return 0;
     }
     m_objMutex.lock();
     m_intPacketReceived++;
     m_intBytesWaiting += intSize;
     if (m_intBytesWaiting > m_intMemoryLimit) {
         m_intBytesWaiting -= m_objFIFO.dequeue().size();
     }
     m_objFIFO.enqueue(QByteArray(chrData,intSize));
     m_intBytesAvailable = m_objFIFO.head().size();
     m_intTotalReceived += intSize;
     m_intQueueWaiting=m_objFIFO.count();
     m_objMutex.unlock();
     if ((m_objeventLoop.isRunning())
         && (m_intQueueWaiting >= MinStackSize))
     {
         emit onDataAvailable();
     }
     if (m_intPacketReceived % MinStackSize == 1)
     {
         m_intPercentBuffer = (100*m_intBytesWaiting)/m_intMemoryLimit;
         if (m_intPercentBuffer > 100) {
             m_intPercentBuffer = 100;
         }
         emit onDataPackets(&m_intQueueWaiting, &m_intBytesWaiting, &m_intPercentBuffer, &m_intTotalReceived);
     }
     return intSize;
 }
readData()
qint64 DATVideostream::readData (char * data, qint64 len) protected virtual
Definition at line 134 of file datvideostream.cpp.
References m_intBytesAvailable, m_intBytesWaiting, m_intMemoryLimit, m_intPercentBuffer, m_intQueueWaiting, m_intTotalReceived, m_objeventLoop, m_objFIFO, m_objMutex, MinStackSize, MultiThreaded, onDataPackets(), and ThreadTimeOut.
 {
     QByteArray objCurrentArray;
     int intEffectiveLen = 0;
     int intExpectedLen = 0;
     int intThreadLoop = 0;
     intExpectedLen = (int) len;
     if (intExpectedLen <= 0) {
         return 0;
     }
     if (m_objeventLoop.isRunning()) {
         return 0;
     }
     m_objMutex.lock();
     //DATA in FIFO ? -> Waiting for DATA
     if ((m_objFIFO.isEmpty()) || (m_objFIFO.count()<MinStackSize))
     {
         m_objMutex.unlock();
         if (MultiThreaded == true)
         {
             intThreadLoop=0;
             while ((m_objFIFO.isEmpty()) || (m_objFIFO.count() < MinStackSize))
             {
                 QThread::msleep(5);
                 intThreadLoop++;
                 if (ThreadTimeOut >= 0)
                 {
                     if (intThreadLoop*5 > ThreadTimeOut) {
                         return -1;
                     }
                 }
             }
         }
         else
         {
             m_objeventLoop.exec();
         }
         m_objMutex.lock();
     }
     //Read DATA
     intEffectiveLen=m_objFIFO.head().size();
     if (intExpectedLen < intEffectiveLen)
     {
         //Partial Read
         objCurrentArray = m_objFIFO.head();
         memcpy((void *)data,objCurrentArray.constData(),intExpectedLen);
         m_objFIFO.head().remove(0,intExpectedLen);
         intEffectiveLen = intExpectedLen;
         m_intBytesWaiting -= intExpectedLen;
     }
     else
     {
         //Complete Read
         objCurrentArray = m_objFIFO.dequeue();
         memcpy((void *)data,objCurrentArray.constData(),intEffectiveLen);
         m_intBytesWaiting -= intEffectiveLen;
     }
     m_intQueueWaiting = m_objFIFO.count();
     m_intPercentBuffer = (100*m_intBytesWaiting) / m_intMemoryLimit;
     emit onDataPackets(&m_intQueueWaiting, &m_intBytesWaiting, &m_intPercentBuffer, &m_intTotalReceived);
     //Next available DATA
     m_intBytesAvailable = m_objFIFO.head().size();
     m_objMutex.unlock();
     return (qint64)intEffectiveLen;
 }
readLineData()
qint64 DATVideostream::readLineData (char * data, qint64 maxSize) protected virtual
Definition at line 223 of file datvideostream.cpp.
 {
     (void) data;
     (void) maxSize;
     return 0;
 }
setMemoryLimit()
bool DATVideostream::setMemoryLimit (int intMemoryLimit)
Definition at line 57 of file datvideostream.cpp.
References m_intMemoryLimit.
 {
     if (intMemoryLimit <= 0) {
         return false;
     }
     m_intMemoryLimit = intMemoryLimit;
     return true;
 }
writeData()
qint64 DATVideostream::writeData (const char * data, qint64 len) protected virtual
Definition at line 216 of file datvideostream.cpp.
 {
     (void) data;
     (void) len;
     return 0;
 }
Member Data Documentation
m_intBytesAvailable
int DATVideostream::m_intBytesAvailable private
Definition at line 69 of file datvideostream.h.
Referenced by bytesAvailable(), cleanUp(), pushData(), and readData().
m_intBytesWaiting
int DATVideostream::m_intBytesWaiting private
Definition at line 70 of file datvideostream.h.
Referenced by cleanUp(), pushData(), and readData().
m_intMemoryLimit
int DATVideostream::m_intMemoryLimit private
Definition at line 68 of file datvideostream.h.
Referenced by DATVideostream(), pushData(), readData(), and setMemoryLimit().
m_intPacketReceived
qint64 DATVideostream::m_intPacketReceived private
Definition at line 74 of file datvideostream.h.
Referenced by DATVideostream(), and pushData().
m_intPercentBuffer
int DATVideostream::m_intPercentBuffer private
Definition at line 72 of file datvideostream.h.
Referenced by cleanUp(), pushData(), and readData().
m_intQueueWaiting
int DATVideostream::m_intQueueWaiting private
Definition at line 71 of file datvideostream.h.
Referenced by cleanUp(), pushData(), and readData().
m_intTotalReceived
qint64 DATVideostream::m_intTotalReceived private
Definition at line 73 of file datvideostream.h.
Referenced by DATVideostream(), pushData(), and readData().
m_objeventLoop
QEventLoop DATVideostream::m_objeventLoop private
Definition at line 66 of file datvideostream.h.
Referenced by cleanUp(), DATVideostream(), pushData(), readData(), and ~DATVideostream().
m_objFIFO
QQueue<QByteArray> DATVideostream::m_objFIFO
Definition at line 51 of file datvideostream.h.
Referenced by cleanUp(), pushData(), and readData().
m_objMutex
QMutex DATVideostream::m_objMutex private
Definition at line 67 of file datvideostream.h.
Referenced by pushData(), and readData().
MultiThreaded
bool DATVideostream::MultiThreaded
Definition at line 40 of file datvideostream.h.
Referenced by DATVideostream(), DATVDemod::PlayVideo(), and readData().
ThreadTimeOut
int DATVideostream::ThreadTimeOut
Definition at line 41 of file datvideostream.h.
Referenced by DATVideostream(), DATVDemod::PlayVideo(), readData(), and DATVDemod::~DATVDemod().
The documentation for this class was generated from the following files:
plugins/channelrx/demoddatv/datvideostream.h
plugins/channelrx/demoddatv/datvideostream.cpp