SDRAngel: DSDDemod::MsgConfigureChannelizer Class Reference
DSDDemod::MsgConfigureChannelizer Class Reference
#include <dsddemod.h>
Public Member Functions
int getSampleRate () const
int getCenterFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (int sampleRate, int centerFrequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (int sampleRate, int centerFrequency)
Private Attributes
int m_sampleRate
int m_centerFrequency
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 76 of file dsddemod.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
DSDDemod::MsgConfigureChannelizer::MsgConfigureChannelizer (int sampleRate, int centerFrequency) inline private
Definition at line 92 of file dsddemod.h.
References DSDDemod::DSDDemod(), and DSDDemod::~DSDDemod().
                                                                      :
             Message(),
             m_sampleRate(sampleRate),
             m_centerFrequency(centerFrequency)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* DSDDemod::MsgConfigureChannelizer::create (int sampleRate, int centerFrequency) inline static
Definition at line 83 of file dsddemod.h.
Referenced by DSDDemodGUI::applySettings(), and DSDDemod::webapiSettingsPutPatch().
         {
             return new MsgConfigureChannelizer(sampleRate, centerFrequency);
         }
getCenterFrequency()
int DSDDemod::MsgConfigureChannelizer::getCenterFrequency () const inline
Definition at line 81 of file dsddemod.h.
Referenced by DSDDemod::handleMessage().
 { return m_centerFrequency; }
getSampleRate()
int DSDDemod::MsgConfigureChannelizer::getSampleRate () const inline
Definition at line 80 of file dsddemod.h.
Referenced by DSDDemod::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_centerFrequency
int DSDDemod::MsgConfigureChannelizer::m_centerFrequency private
Definition at line 90 of file dsddemod.h.
m_sampleRate
int DSDDemod::MsgConfigureChannelizer::m_sampleRate private
Definition at line 89 of file dsddemod.h.
The documentation for this class was generated from the following file:
plugins/channelrx/demoddsd/dsddemod.h