SDRAngel: RDSTMC Class Reference
RDSTMC Class Reference
#include <rdstmc.h>
Static Public Member Functions
static std::string get_tmc_events (unsigned int i, unsigned int j)
static int get_tmc_event_code_index (unsigned int i, unsigned int j)
Detailed Description
Definition at line 24 of file rdstmc.h.
Member Function Documentation
get_tmc_event_code_index()
int RDSTMC::get_tmc_event_code_index (unsigned int i, unsigned int j) static
Definition at line 3703 of file rdstmc.cpp.
Referenced by RDSParser::decode_type8(), and BFMDemodGUI::rdsUpdate().
 {
     return tmc_event_code_index[i][j];
 }
get_tmc_events()
std::string RDSTMC::get_tmc_events (unsigned int i, unsigned int j) static
Definition at line 3698 of file rdstmc.cpp.
Referenced by RDSParser::decode_type8(), and BFMDemodGUI::rdsUpdate().
 {
     return tmc_events[i][j];
 }
The documentation for this class was generated from the following files:
plugins/channelrx/demodbfm/rdstmc.h
plugins/channelrx/demodbfm/rdstmc.cpp