SDRAngel: ThreadedBasebandSampleSource Class Reference
ThreadedBasebandSampleSource Class Reference
#include <threadedbasebandsamplesource.h>
Inherits QObject.
Public Member Functions
ThreadedBasebandSampleSource (BasebandSampleSource *sampleSource, QObject *parent=0)
~ThreadedBasebandSampleSource ()
const BasebandSampleSource * getSource () const
void start ()
this thread start()
void stop ()
this thread exit() and wait()
bool handleSourceMessage (const Message &cmd)
Send message to source synchronously.
void pull (Sample &sample)
Pull one sample from source.
void pullAudio (int nbSamples)
void feed (SampleSourceFifo *sampleFifo, int nbSamples)
SampleSourceFifo & getSampleSourceFifo ()
void setDeviceSampleSourceFifo (SampleSourceFifo *deviceSampleFifo)
QString getSampleSourceObjectName () const
Protected Attributes
QThread * m_thread
The thead object.
BasebandSampleSource * m_basebandSampleSource
Detailed Description
This class is a wrapper for BasebandSampleSource that runs the BasebandSampleSource object in its own thread
Definition at line 34 of file threadedbasebandsamplesource.h.
Constructor & Destructor Documentation
ThreadedBasebandSampleSource()
ThreadedBasebandSampleSource::ThreadedBasebandSampleSource (BasebandSampleSource * sampleSource, QObject * parent = 0)
Definition at line 24 of file threadedbasebandsamplesource.cpp.
References m_basebandSampleSource, and m_thread.
                                                                                                               :
         m_basebandSampleSource(sampleSource)
 {
     QString name = "ThreadedBasebandSampleSource(" + m_basebandSampleSource->objectName() + ")";
     setObjectName(name);
     qDebug() << "ThreadedBasebandSampleSource::ThreadedBasebandSampleSource: " << name;
     m_thread = new QThread(parent);
     m_basebandSampleSource->moveToThread(m_thread);
     qDebug() << "ThreadedBasebandSampleSource::ThreadedBasebandSampleSource: thread: " << thread() << " m_thread: " << m_thread;
 }
~ThreadedBasebandSampleSource()
ThreadedBasebandSampleSource::~ThreadedBasebandSampleSource ()
Definition at line 38 of file threadedbasebandsamplesource.cpp.
References m_thread, and stop().
 {
     if (m_thread->isRunning()) {
         stop();
     }
     delete m_thread;
 }
Member Function Documentation
feed()
void ThreadedBasebandSampleSource::feed (SampleSourceFifo * sampleFifo, int nbSamples)
direct feeding of sample source FIFO
Definition at line 67 of file threadedbasebandsamplesource.cpp.
References BasebandSampleSource::feed(), and m_basebandSampleSource.
 {
     m_basebandSampleSource->feed(sampleFifo, nbSamples);
 }
getSampleSourceFifo()
SampleSourceFifo& ThreadedBasebandSampleSource::getSampleSourceFifo () inline
Definition at line 54 of file threadedbasebandsamplesource.h.
 { return m_basebandSampleSource->getSampleSourceFifo(); }
getSampleSourceObjectName()
QString ThreadedBasebandSampleSource::getSampleSourceObjectName () const
Definition at line 78 of file threadedbasebandsamplesource.cpp.
References m_basebandSampleSource.
 {
     return m_basebandSampleSource->objectName();
 }
getSource()
const BasebandSampleSource* ThreadedBasebandSampleSource::getSource () const inline
Definition at line 41 of file threadedbasebandsamplesource.h.
 { return m_basebandSampleSource; }
handleSourceMessage()
bool ThreadedBasebandSampleSource::handleSourceMessage (const Message & cmd)
Send message to source synchronously.
Definition at line 73 of file threadedbasebandsamplesource.cpp.
References BasebandSampleSource::handleMessage(), and m_basebandSampleSource.
Referenced by DSPDeviceSinkEngine::handleSynchronousMessages(), and DSPDeviceMIMOEngine::handleSynchronousMessages().
 {
     return m_basebandSampleSource->handleMessage(cmd);
 }
pull()
void ThreadedBasebandSampleSource::pull (Sample & sample)
Pull one sample from source.
Definition at line 62 of file threadedbasebandsamplesource.cpp.
References m_basebandSampleSource, and BasebandSampleSource::pull().
 {
     m_basebandSampleSource->pull(sample);
 }
pullAudio()
void ThreadedBasebandSampleSource::pullAudio (int nbSamples) inline
Definition at line 48 of file threadedbasebandsamplesource.h.
 { if (m_basebandSampleSource) m_basebandSampleSource->pullAudio(nbSamples); }
setDeviceSampleSourceFifo()
void ThreadedBasebandSampleSource::setDeviceSampleSourceFifo (SampleSourceFifo * deviceSampleFifo) inline
Definition at line 55 of file threadedbasebandsamplesource.h.
 { m_basebandSampleSource->setDeviceSampleSourceFifo(deviceSampleFifo); }
start()
void ThreadedBasebandSampleSource::start ()
this thread start()
Definition at line 47 of file threadedbasebandsamplesource.cpp.
References m_basebandSampleSource, m_thread, and BasebandSampleSource::start().
Referenced by DSPDeviceSinkEngine::handleSynchronousMessages(), and DSPDeviceMIMOEngine::handleSynchronousMessages().
 {
     qDebug() << "ThreadedBasebandSampleSource::start";
     m_thread->start();
     m_basebandSampleSource->start();
 }
stop()
void ThreadedBasebandSampleSource::stop ()
this thread exit() and wait()
Definition at line 54 of file threadedbasebandsamplesource.cpp.
References m_basebandSampleSource, m_thread, and BasebandSampleSource::stop().
Referenced by DSPDeviceSinkEngine::handleSynchronousMessages(), DSPDeviceMIMOEngine::handleSynchronousMessages(), and ~ThreadedBasebandSampleSource().
 {
     qDebug() << "ThreadedBasebandSampleSource::stop";
     m_basebandSampleSource->stop();
     m_thread->exit();
     m_thread->wait();
 }
Member Data Documentation
m_basebandSampleSource
BasebandSampleSource* ThreadedBasebandSampleSource::m_basebandSampleSource protected
Definition at line 61 of file threadedbasebandsamplesource.h.
Referenced by feed(), getSampleSourceObjectName(), handleSourceMessage(), pull(), start(), stop(), and ThreadedBasebandSampleSource().
m_thread
QThread* ThreadedBasebandSampleSource::m_thread protected
The thead object.
Definition at line 60 of file threadedbasebandsamplesource.h.
Referenced by start(), stop(), ThreadedBasebandSampleSource(), and ~ThreadedBasebandSampleSource().
The documentation for this class was generated from the following files:
sdrbase/dsp/threadedbasebandsamplesource.h
sdrbase/dsp/threadedbasebandsamplesource.cpp