SDRAngel: DeviceSet::ChannelInstanceRegistration Struct Reference
DeviceSet::ChannelInstanceRegistration Struct Reference
Public Member Functions
ChannelInstanceRegistration ()
ChannelInstanceRegistration (const QString &channelName, ChannelAPI *channelAPI)
bool operator< (const ChannelInstanceRegistration &other) const
Public Attributes
QString m_channelName
ChannelAPI * m_channelSinkAPI
ChannelAPI * m_channelSourceAPI
Detailed Description
Definition at line 60 of file deviceset.h.
Constructor & Destructor Documentation
ChannelInstanceRegistration() [1/2]
DeviceSet::ChannelInstanceRegistration::ChannelInstanceRegistration () inline
Definition at line 66 of file deviceset.h.
References operator<().
Referenced by DeviceSet::addRxChannel(), DeviceSet::addTxChannel(), DeviceSet::loadRxChannelSettings(), DeviceSet::loadTxChannelSettings(), DeviceSet::registerRxChannelInstance(), and DeviceSet::registerTxChannelInstance().
                                       :
             m_channelName(),
             m_channelSinkAPI(nullptr),
             m_channelSourceAPI(nullptr)
         { }
ChannelInstanceRegistration() [2/2]
DeviceSet::ChannelInstanceRegistration::ChannelInstanceRegistration (const QString & channelName, ChannelAPI * channelAPI)
Definition at line 29 of file deviceset.cpp.
References ChannelAPI::getStreamType(), m_channelSinkAPI, m_channelSourceAPI, ChannelAPI::StreamSingleSink, and ChannelAPI::StreamSingleSource.
                                                                                                                     :
     m_channelName(channelName),
     m_channelSinkAPI(channelAPI),
     m_channelSourceAPI(0)
 {
     if (channelAPI->getStreamType() == ChannelAPI::StreamSingleSink)
     {
         m_channelSinkAPI = channelAPI;
         m_channelSourceAPI = nullptr;
     }
     else if (channelAPI->getStreamType() == ChannelAPI::StreamSingleSource)
     {
         m_channelSinkAPI = nullptr;
         m_channelSourceAPI = channelAPI;
     }
     else
     {
         m_channelSinkAPI = nullptr;
         m_channelSourceAPI = nullptr;
     }
 }
Member Function Documentation
operator<()
bool DeviceSet::ChannelInstanceRegistration::operator< (const ChannelInstanceRegistration & other) const
Definition at line 365 of file deviceset.cpp.
References ChannelAPI::getCenterFrequency(), ChannelAPI::getName(), m_channelSinkAPI, and m_channelSourceAPI.
Referenced by ChannelInstanceRegistration().
 {
     if (m_channelSinkAPI && other.m_channelSinkAPI)
     {
         if (m_channelSinkAPI->getCenterFrequency() == other.m_channelSinkAPI->getCenterFrequency())
         {
             return m_channelSinkAPI->getName() < other.m_channelSinkAPI->getName();
         }
         else
         {
             return m_channelSinkAPI->getCenterFrequency() < other.m_channelSinkAPI->getCenterFrequency();
         }
     }
     else if (m_channelSourceAPI && other.m_channelSourceAPI)
     {
         if (m_channelSourceAPI->getCenterFrequency() == other.m_channelSourceAPI->getCenterFrequency())
         {
             return m_channelSourceAPI->getName() < other.m_channelSourceAPI->getName();
         }
         else
         {
             return m_channelSourceAPI->getCenterFrequency() < other.m_channelSourceAPI->getCenterFrequency();
         }
     }
     else
     {
         return false;
     }
 }
Member Data Documentation
m_channelName
QString DeviceSet::ChannelInstanceRegistration::m_channelName
Definition at line 62 of file deviceset.h.
Referenced by DeviceSet::freeRxChannels(), DeviceSet::freeTxChannels(), DeviceSet::loadRxChannelSettings(), DeviceSet::loadTxChannelSettings(), DeviceSet::renameRxChannelInstances(), DeviceSet::renameTxChannelInstances(), DeviceSet::saveRxChannelSettings(), and DeviceSet::saveTxChannelSettings().
m_channelSinkAPI
ChannelAPI* DeviceSet::ChannelInstanceRegistration::m_channelSinkAPI
Definition at line 63 of file deviceset.h.
Referenced by ChannelInstanceRegistration(), DeviceSet::loadRxChannelSettings(), operator<(), and DeviceSet::saveRxChannelSettings().
m_channelSourceAPI
ChannelAPI* DeviceSet::ChannelInstanceRegistration::m_channelSourceAPI
Definition at line 64 of file deviceset.h.
Referenced by ChannelInstanceRegistration(), DeviceSet::loadTxChannelSettings(), operator<(), and DeviceSet::saveTxChannelSettings().
The documentation for this struct was generated from the following files:
sdrsrv/device/deviceset.h
sdrsrv/device/deviceset.cpp