SDRAngel: BladeRF2Output::MsgConfigureBladeRF2 Class Reference
BladeRF2Output::MsgConfigureBladeRF2 Class Reference
#include <bladerf2output.h>
Public Member Functions
const BladeRF2OutputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureBladeRF2 * create (const BladeRF2OutputSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureBladeRF2 (const BladeRF2OutputSettings &settings, bool force)
Private Attributes
BladeRF2OutputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 39 of file bladerf2output.h.
Constructor & Destructor Documentation
MsgConfigureBladeRF2()
BladeRF2Output::MsgConfigureBladeRF2::MsgConfigureBladeRF2 (const BladeRF2OutputSettings & settings, bool force) inline private
Definition at line 55 of file bladerf2output.h.
Referenced by create().
                                                                                  :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureBladeRF2* BladeRF2Output::MsgConfigureBladeRF2::create (const BladeRF2OutputSettings & settings, bool force) inline static
Definition at line 46 of file bladerf2output.h.
References MsgConfigureBladeRF2().
Referenced by BladeRF2Output::deserialize(), BladeRF2Output::handleMessage(), BladeRF2Output::setCenterFrequency(), BladeRF2OutputGui::updateHardware(), and BladeRF2Output::webapiSettingsPutPatch().
         {
             return new MsgConfigureBladeRF2(settings, force);
         }
getForce()
bool BladeRF2Output::MsgConfigureBladeRF2::getForce () const inline
Definition at line 44 of file bladerf2output.h.
References m_force.
Referenced by BladeRF2Output::handleMessage().
 { return m_force; }
getSettings()
const BladeRF2OutputSettings& BladeRF2Output::MsgConfigureBladeRF2::getSettings () const inline
Definition at line 43 of file bladerf2output.h.
References m_settings.
Referenced by BladeRF2OutputGui::handleMessage(), and BladeRF2Output::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool BladeRF2Output::MsgConfigureBladeRF2::m_force private
Definition at line 53 of file bladerf2output.h.
Referenced by getForce().
m_settings
BladeRF2OutputSettings BladeRF2Output::MsgConfigureBladeRF2::m_settings private
Definition at line 52 of file bladerf2output.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesink/bladerf2output/bladerf2output.h