SDRAngel: MainWindow Class Reference
MainWindow Class Reference
#include <mainwindow.h>
Inherits QMainWindow.
Classes
struct DeviceWidgetTabData
class MsgAddChannel
class MsgAddDeviceSet
class MsgDeleteChannel
class MsgDeletePreset
class MsgDeviceSetFocus
class MsgLoadPreset
class MsgRemoveLastDeviceSet
class MsgSavePreset
class MsgSetDevice
Public Member Functions
MainWindow (qtwebapp::LoggerWithFile *logger, const MainParser &parser, QWidget *parent=0)
~MainWindow ()
MessageQueue * getInputMessageQueue ()
void addViewAction (QAction *action)
void addChannelRollup (int deviceTabIndex, QWidget *widget)
void setDeviceGUI (int deviceTabIndex, QWidget *gui, const QString &deviceDisplayName, int deviceType=0)
const QTimer & getMasterTimer () const
const MainSettings & getMainSettings () const
void commandKeysConnect (QObject *object, const char *slot)
void commandKeysDisconnect (QObject *object, const char *slot)
Static Public Member Functions
static MainWindow * getInstance ()
Private Types
enum { PGroup, PItem }
Private Slots
void handleMessages ()
void updateStatus ()
void on_action_View_Fullscreen_toggled (bool checked)
void on_presetSave_clicked ()
void on_presetUpdate_clicked ()
void on_presetEdit_clicked ()
void on_presetExport_clicked ()
void on_presetImport_clicked ()
void on_settingsSave_clicked ()
void on_presetLoad_clicked ()
void on_presetDelete_clicked ()
void on_presetTree_currentItemChanged (QTreeWidgetItem *current, QTreeWidgetItem *previous)
void on_presetTree_itemActivated (QTreeWidgetItem *item, int column)
void on_commandNew_clicked ()
void on_commandDuplicate_clicked ()
void on_commandEdit_clicked ()
void on_commandDelete_clicked ()
void on_commandRun_clicked ()
void on_commandOutput_clicked ()
void on_commandsSave_clicked ()
void on_commandKeyboardConnect_toggled (bool checked)
void on_action_Audio_triggered ()
void on_action_Logging_triggered ()
void on_action_AMBE_triggered ()
void on_action_My_Position_triggered ()
void on_action_DeviceUserArguments_triggered ()
void sampleSourceChanged ()
void sampleSinkChanged ()
void sampleMIMOChanged ()
void channelAddClicked (bool checked)
void on_action_Loaded_Plugins_triggered ()
void on_action_About_triggered ()
void on_action_addSourceDevice_triggered ()
void on_action_addSinkDevice_triggered ()
void on_action_addMIMODevice_triggered ()
void on_action_removeLastDevice_triggered ()
void tabInputViewIndexChanged ()
void commandKeyPressed (Qt::Key key, Qt::KeyboardModifiers keyModifiers, bool release)
Private Member Functions
void loadSettings ()
void loadPresetSettings (const Preset *preset, int tabIndex)
void savePresetSettings (Preset *preset, int tabIndex)
void saveCommandSettings ()
void createStatusBar ()
void closeEvent (QCloseEvent *)
void updatePresetControls ()
QTreeWidgetItem * addPresetToTree (const Preset *preset)
QTreeWidgetItem * addCommandToTree (const Command *command)
void applySettings ()
void addSourceDevice (int deviceIndex)
void addSinkDevice ()
void addMIMODevice ()
void removeLastDevice ()
void deleteChannel (int deviceSetIndex, int channelIndex)
void setLoggingOptions ()
bool handleMessage (const Message &cmd)
Private Attributes
Ui::MainWindow * ui
MessageQueue m_inputMessageQueue
MainSettings m_settings
std::vector< DeviceUISet * > m_deviceUIs
QList< DeviceWidgetTabData > m_deviceWidgetTabs
int m_masterTabIndex
DSPEngine * m_dspEngine
PluginManager * m_pluginManager
QTimer m_masterTimer
QTimer m_statusTimer
int m_lastEngineState
QLabel * m_dateTimeWidget
QLabel * m_showSystemWidget
QWidget * m_inputGUI
int m_sampleRate
quint64 m_centerFrequency
std::string m_sampleFileName
qtwebapp::LoggerWithFile * m_logger
WebAPIRequestMapper * m_requestMapper
WebAPIServer * m_apiServer
WebAPIAdapterGUI * m_apiAdapter
QString m_apiHost
int m_apiPort
CommandKeyReceiver * m_commandKeyReceiver
Static Private Attributes
static MainWindow * m_instance = 0
Friends
class WebAPIAdapterGUI
Detailed Description
Definition at line 67 of file mainwindow.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
PGroup
PItem
Definition at line 272 of file mainwindow.h.
          {
         PGroup,
         PItem
     };
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (qtwebapp::LoggerWithFile * logger, const MainParser & parser, QWidget * parent = 0) explicit
Definition at line 95 of file mainwindow.cpp.
References addSourceDevice(), applySettings(), createStatusBar(), DSPEngine::getAMBEEngine(), DSPEngine::getAudioDeviceManager(), MainParser::getMIMOSupport(), DeviceEnumerator::getRxSamplingDeviceIndex(), MainParser::getServerAddress(), MainParser::getServerPort(), MainSettings::getSourceDeviceId(), MainSettings::getSourceIndex(), MainSettings::getWorkingPreset(), handleMessages(), DeviceEnumerator::instance(), PluginManager::loadPlugins(), loadPresetSettings(), loadSettings(), m_apiAdapter, m_apiHost, m_apiPort, m_apiServer, m_commandKeyReceiver, m_deviceUIs, m_dspEngine, m_inputMessageQueue, m_instance, m_masterTimer, m_pluginManager, m_requestMapper, m_settings, m_statusTimer, WebAPIRequestMapper::setAdapter(), MainSettings::setAMBEEngine(), MainSettings::setAudioDeviceManager(), SDRangelSplash::setMessageRect(), DSPEngine::setMIMOSupport(), CommandKeyReceiver::setRelease(), SDRangelSplash::showStatusMessage(), WebAPIServer::start(), tabInputViewIndexChanged(), ui, updatePresetControls(), updateStatus(), and WebAPIAdapterGUI.
                                                                                                 :
     QMainWindow(parent),
     ui(new Ui::MainWindow),
     m_settings(),
     m_masterTabIndex(0),
     m_dspEngine(DSPEngine::instance()),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_inputGUI(0),
     m_sampleRate(0),
     m_centerFrequency(0),
     m_sampleFileName(std::string("./test.sdriq")),
     m_logger(logger)
 {
     qDebug() << "MainWindow::MainWindow: start";
     m_instance = this;
     QFontDatabase::addApplicationFont(":/LiberationSans-Regular.ttf");
     QFontDatabase::addApplicationFont(":/LiberationMono-Regular.ttf");
     QFont font("Liberation Sans");
     font.setPointSize(9);
     qApp->setFont(font);
     QPixmap logoPixmap(":/sdrangel_logo.png");
     SDRangelSplash *splash = new SDRangelSplash(logoPixmap);
     splash->setMessageRect(QRect(10, 80, 350, 16));
     splash->show();
     splash->showStatusMessage("starting...", Qt::white);
     m_settings.setAudioDeviceManager(m_dspEngine->getAudioDeviceManager());
     m_settings.setAMBEEngine(m_dspEngine->getAMBEEngine());
     ui->setupUi(this);
     createStatusBar();
     setCorner(Qt::TopLeftCorner, Qt::LeftDockWidgetArea);
     setCorner(Qt::BottomLeftCorner, Qt::LeftDockWidgetArea);
     setCorner(Qt::TopRightCorner, Qt::RightDockWidgetArea);
     setCorner(Qt::BottomRightCorner, Qt::RightDockWidgetArea);
     // work around broken Qt dock widget ordering
     removeDockWidget(ui->inputViewDock);
     removeDockWidget(ui->inputSelectDock);
     removeDockWidget(ui->spectraDisplayDock);
     removeDockWidget(ui->presetDock);
     removeDockWidget(ui->commandsDock);
     removeDockWidget(ui->channelDock);
     addDockWidget(Qt::LeftDockWidgetArea, ui->inputViewDock);
     addDockWidget(Qt::LeftDockWidgetArea, ui->inputSelectDock);
     addDockWidget(Qt::LeftDockWidgetArea, ui->spectraDisplayDock);
     addDockWidget(Qt::LeftDockWidgetArea, ui->presetDock);
     addDockWidget(Qt::LeftDockWidgetArea, ui->commandsDock);
     tabifyDockWidget(ui->presetDock, ui->commandsDock);
     addDockWidget(Qt::RightDockWidgetArea, ui->channelDock);
     ui->inputViewDock->show();
     ui->inputSelectDock->show();
     ui->spectraDisplayDock->show();
     ui->presetDock->show();
     ui->commandsDock->show();
     ui->channelDock->show();
     ui->menu_Window->addAction(ui->inputViewDock->toggleViewAction());
     ui->menu_Window->addAction(ui->inputSelectDock->toggleViewAction());
     ui->menu_Window->addAction(ui->spectraDisplayDock->toggleViewAction());
     ui->menu_Window->addAction(ui->presetDock->toggleViewAction());
     ui->menu_Window->addAction(ui->commandsDock->toggleViewAction());
     ui->menu_Window->addAction(ui->channelDock->toggleViewAction());
     ui->tabInputsView->setStyleSheet("QWidget { background: rgb(50,50,50); } "
             "QToolButton::checked { background: rgb(128,70,0); } "
             "QComboBox::item:selected { color: rgb(255,140,0); } "
             "QTabWidget::pane { border: 1px solid #C06900; } "
             "QTabBar::tab:selected { background: rgb(128,70,0); }");
     ui->tabInputsSelect->setStyleSheet("QWidget { background: rgb(50,50,50); } "
             "QToolButton::checked { background: rgb(128,70,0); } "
             "QComboBox::item:selected { color: rgb(255,140,0); } "
             "QTabWidget::pane { border: 1px solid #808080; } "
             "QTabBar::tab:selected { background: rgb(100,100,100); }");
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleMessages()), Qt::QueuedConnection);
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(1000);
     m_masterTimer.setTimerType(Qt::PreciseTimer);
     m_masterTimer.start(50);
     splash->showStatusMessage("load settings...", Qt::white);
     qDebug() << "MainWindow::MainWindow: load settings...";
     loadSettings();
     splash->showStatusMessage("load plugins...", Qt::white);
     qDebug() << "MainWindow::MainWindow: load plugins...";
     m_pluginManager = new PluginManager(this);
     m_pluginManager->loadPlugins(QString("plugins"));
     splash->showStatusMessage("load file input...", Qt::white);
     qDebug() << "MainWindow::MainWindow: select SampleSource from settings or default (file input)...";
     int deviceIndex = DeviceEnumerator::instance()->getRxSamplingDeviceIndex(m_settings.getSourceDeviceId(), m_settings.getSourceIndex());
     addSourceDevice(deviceIndex);  // add the first device set with file input device as default if device in settings is not enumerated
     m_deviceUIs.back()->m_deviceAPI->setBuddyLeader(true); // the first device is always the leader
     splash->showStatusMessage("load current preset settings...", Qt::white);
     qDebug() << "MainWindow::MainWindow: load current preset settings...";
     loadPresetSettings(m_settings.getWorkingPreset(), 0);
     splash->showStatusMessage("apply settings...", Qt::white);
     qDebug() << "MainWindow::MainWindow: apply settings...";
     applySettings();
     splash->showStatusMessage("update preset controls...", Qt::white);
     qDebug() << "MainWindow::MainWindow: update preset controls...";
     updatePresetControls();
     splash->showStatusMessage("finishing...", Qt::white);
     connect(ui->tabInputsView, SIGNAL(currentChanged(int)), this, SLOT(tabInputViewIndexChanged()));
     QString applicationDirPath = qApp->applicationDirPath();
 #ifdef _MSC_VER
     if (QResource::registerResource(applicationDirPath + "/sdrbase.rcc")) {
         qDebug("MainWindow::MainWindow: registered resource file %s/%s", qPrintable(applicationDirPath), "sdrbase.rcc");
     } else {
         qWarning("MainWindow::MainWindow: could not register resource file %s/%s", qPrintable(applicationDirPath), "sdrbase.rcc");
     }
 #endif
     m_apiAdapter = new WebAPIAdapterGUI(*this);
     m_requestMapper = new WebAPIRequestMapper(this);
     m_requestMapper->setAdapter(m_apiAdapter);
     m_apiHost = parser.getServerAddress();
     m_apiPort = parser.getServerPort();
     m_apiServer = new WebAPIServer(m_apiHost, m_apiPort, m_requestMapper);
     m_apiServer->start();
     m_commandKeyReceiver = new CommandKeyReceiver();
     m_commandKeyReceiver->setRelease(true);
     this->installEventFilter(m_commandKeyReceiver);
     m_dspEngine->setMIMOSupport(parser.getMIMOSupport());
     delete splash;
     qDebug() << "MainWindow::MainWindow: end";
 }
~MainWindow()
MainWindow::~MainWindow ()
Definition at line 249 of file mainwindow.cpp.
References m_apiAdapter, m_apiServer, m_commandKeyReceiver, m_dateTimeWidget, m_logger, m_pluginManager, m_requestMapper, m_showSystemWidget, WebAPIServer::stop(), and ui.
 {
     m_apiServer->stop();
     delete m_apiServer;
     delete m_requestMapper;
     delete m_apiAdapter;
     delete m_pluginManager;
     delete m_dateTimeWidget;
     delete m_showSystemWidget;
     delete ui;
     qDebug() << "MainWindow::~MainWindow: end";
     delete m_logger;
     delete m_commandKeyReceiver;
 }
Member Function Documentation
addChannelRollup()
void MainWindow::addChannelRollup (int deviceTabIndex, QWidget * widget)
Definition at line 660 of file mainwindow.cpp.
References ChannelWindow::addRollupWidget(), DeviceUISet::m_channelWindow, m_deviceUIs, and ui.
 {
     if (deviceTabIndex < ui->tabInputsView->count())
     {
         DeviceUISet *deviceUI = m_deviceUIs[deviceTabIndex];
         deviceUI->m_channelWindow->addRollupWidget(widget);
         ui->channelDock->show();
         ui->channelDock->raise();
     }
 }
addCommandToTree()
QTreeWidgetItem * MainWindow::addCommandToTree (const Command * command) private
Definition at line 883 of file mainwindow.cpp.
References arg(), Command::getAssociateKey(), Command::getDescription(), Command::getGroup(), Command::getKeyLabel(), Command::getRelease(), i, PGroup, PItem, and ui.
Referenced by loadSettings(), on_commandDelete_clicked(), on_commandDuplicate_clicked(), on_commandEdit_clicked(), and on_commandNew_clicked().
 {
     QTreeWidgetItem* group = 0;
     for(int i = 0; i < ui->commandTree->topLevelItemCount(); i++)
     {
         if(ui->commandTree->topLevelItem(i)->text(0) == command->getGroup())
         {
             group = ui->commandTree->topLevelItem(i);
             break;
         }
     }
     if(group == 0)
     {
         QStringList sl;
         sl.append(command->getGroup());
         group = new QTreeWidgetItem(ui->commandTree, sl, PGroup);
         group->setFirstColumnSpanned(true);
         group->setExpanded(true);
         ui->commandTree->sortByColumn(0, Qt::AscendingOrder);
     }
     QStringList sl;
     sl.append(QString("%1").arg(command->getDescription())); // Descriptions column
     sl.append(QString("%1").arg(command->getAssociateKey() ? command->getRelease() ? "R" : "P" : "-")); // key press/release column
     sl.append(QString("%1").arg(command->getKeyLabel()));   // key column
     CommandItem* item = new CommandItem(group, sl, command->getDescription(), PItem);
     item->setData(0, Qt::UserRole, qVariantFromValue(command));
     item->setTextAlignment(0, Qt::AlignLeft);
     ui->commandTree->resizeColumnToContents(0); // Resize description column to minimum
     ui->commandTree->resizeColumnToContents(1); // Resize key column to minimum
     ui->commandTree->resizeColumnToContents(2); // Resize key press/release column to minimum
     //updatePresetControls();
     return item;
 }
addMIMODevice()
void MainWindow::addMIMODevice () private
Definition at line 425 of file mainwindow.cpp.
References DSPEngine::addDeviceMIMOEngine(), DSPDeviceMIMOEngine::addSpectrumSink(), channelAddClicked(), PluginInterface::SamplingDevice::deviceItemIndex, PluginInterface::SamplingDevice::deviceNbItems, PluginInterface::SamplingDevice::displayedName, DeviceUserArgs::findUserArgs(), MainSettings::getDeviceUserArgs(), PluginInstanceGUI::getInputMessageQueue(), DeviceEnumerator::getMIMOSamplingDevice(), DeviceEnumerator::getTestMIMODeviceIndex(), DSPDeviceMIMOEngine::getUID(), PluginInterface::SamplingDevice::hardwareId, PluginInterface::SamplingDevice::id, DeviceEnumerator::instance(), PluginManager::listRxChannels(), PluginManager::listTxChannels(), m_deviceUIs, m_dspEngine, m_masterTimer, m_pluginManager, m_settings, sampleMIMOChanged(), PluginInterface::SamplingDevice::sequence, PluginInterface::SamplingDevice::serial, setDeviceGUI(), DSPDeviceMIMOEngine::start(), DeviceAPI::StreamMIMO, and ui.
Referenced by handleMessage(), and on_action_addMIMODevice_triggered().
 {
     DSPDeviceMIMOEngine *dspDeviceMIMOEngine = m_dspEngine->addDeviceMIMOEngine();
     dspDeviceMIMOEngine->start();
     uint dspDeviceMIMOEngineUID =  dspDeviceMIMOEngine->getUID();
     char uidCStr[16];
     sprintf(uidCStr, "UID:%d", dspDeviceMIMOEngineUID);
     int deviceTabIndex = m_deviceUIs.size();
     m_deviceUIs.push_back(new DeviceUISet(deviceTabIndex, 2, m_masterTimer));
     m_deviceUIs.back()->m_deviceSourceEngine = nullptr;
     m_deviceUIs.back()->m_deviceSinkEngine = nullptr;
     m_deviceUIs.back()->m_deviceMIMOEngine = dspDeviceMIMOEngine;
     char tabNameCStr[16];
     sprintf(tabNameCStr, "M%d", deviceTabIndex);
     DeviceAPI *deviceAPI = new DeviceAPI(DeviceAPI::StreamMIMO, deviceTabIndex, nullptr, nullptr, dspDeviceMIMOEngine);
     m_deviceUIs.back()->m_deviceAPI = deviceAPI;
     m_deviceUIs.back()->m_samplingDeviceControl->setPluginManager(m_pluginManager);
     QComboBox *channelSelector = m_deviceUIs.back()->m_samplingDeviceControl->getChannelSelector();
     // Add Rx channels
     QList<QString> rxChannelNames;
     m_pluginManager->listRxChannels(rxChannelNames);
     QStringList rxChannelNamesList(rxChannelNames);
     channelSelector->addItems(rxChannelNamesList);
     m_deviceUIs.back()->setNumberOfAvailableRxChannels(rxChannelNamesList.size());
     // Add Tx channels
     QList<QString> txChannelNames;
     m_pluginManager->listTxChannels(txChannelNames);
     QStringList txChannelNamesList(txChannelNames);
     channelSelector->addItems(txChannelNamesList);
     m_deviceUIs.back()->setNumberOfAvailableTxChannels(txChannelNamesList.size());
     // TODO: add MIMO channels
     connect(m_deviceUIs.back()->m_samplingDeviceControl->getAddChannelButton(), SIGNAL(clicked(bool)), this, SLOT(channelAddClicked(bool)));
     dspDeviceMIMOEngine->addSpectrumSink(m_deviceUIs.back()->m_spectrumVis);
     ui->tabSpectra->addTab(m_deviceUIs.back()->m_spectrum, tabNameCStr);
     ui->tabSpectraGUI->addTab(m_deviceUIs.back()->m_spectrumGUI, tabNameCStr);
     ui->tabChannels->addTab(m_deviceUIs.back()->m_channelWindow, tabNameCStr);
     connect(m_deviceUIs.back()->m_samplingDeviceControl, SIGNAL(changed()), this, SLOT(sampleMIMOChanged()));
     ui->tabInputsSelect->addTab(m_deviceUIs.back()->m_samplingDeviceControl, tabNameCStr);
     ui->tabInputsSelect->setTabToolTip(deviceTabIndex, QString(uidCStr));
     // create a test MIMO by default
     int testMIMODeviceIndex = DeviceEnumerator::instance()->getTestMIMODeviceIndex();
     const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getMIMOSamplingDevice(testMIMODeviceIndex);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDeviceSequence(samplingDevice->sequence);
     m_deviceUIs.back()->m_deviceAPI->setDeviceNbItems(samplingDevice->deviceNbItems);
     m_deviceUIs.back()->m_deviceAPI->setDeviceItemIndex(samplingDevice->deviceItemIndex);
     m_deviceUIs.back()->m_deviceAPI->setHardwareId(samplingDevice->hardwareId);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDeviceId(samplingDevice->id);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDeviceSerial(samplingDevice->serial);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDeviceDisplayName(samplingDevice->displayedName);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDevicePluginInterface(DeviceEnumerator::instance()->getMIMOPluginInterface(testMIMODeviceIndex));
     QString userArgs = m_settings.getDeviceUserArgs().findUserArgs(samplingDevice->hardwareId, samplingDevice->sequence);
     if (userArgs.size() > 0) {
         m_deviceUIs.back()->m_deviceAPI->setHardwareUserArguments(userArgs);
     }
     m_deviceUIs.back()->m_samplingDeviceControl->setSelectedDeviceIndex(testMIMODeviceIndex);
     // delete previous plugin GUI if it exists
     m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->deleteSampleSourcePluginInstanceGUI(
             m_deviceUIs.back()->m_deviceAPI->getSamplingDevicePluginInstanceGUI());
     DeviceSampleMIMO *mimo = m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->createSampleMIMOPluginInstance(
             m_deviceUIs.back()->m_deviceAPI->getSamplingDeviceId(), m_deviceUIs.back()->m_deviceAPI);
     m_deviceUIs.back()->m_deviceAPI->setSampleMIMO(mimo);
     QWidget *gui;
     PluginInstanceGUI *pluginUI = m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->createSampleMIMOPluginInstanceGUI(
             m_deviceUIs.back()->m_deviceAPI->getSamplingDeviceId(),
             &gui,
             m_deviceUIs.back());
     m_deviceUIs.back()->m_deviceAPI->getSampleMIMO()->setMessageQueueToGUI(pluginUI->getInputMessageQueue());
     m_deviceUIs.back()->m_deviceAPI->setSamplingDevicePluginInstanceGUI(pluginUI);
     m_deviceUIs.back()->m_deviceAPI->getSampleMIMO()->init();
     setDeviceGUI(deviceTabIndex, gui, m_deviceUIs.back()->m_deviceAPI->getSamplingDeviceDisplayName(), 2);
 }
addPresetToTree()
QTreeWidgetItem * MainWindow::addPresetToTree (const Preset * preset) private
Definition at line 846 of file mainwindow.cpp.
References arg(), Preset::getCenterFrequency(), Preset::getDescription(), Preset::getGroup(), i, Preset::isSourcePreset(), PGroup, PItem, ui, and updatePresetControls().
Referenced by handleMessage(), loadSettings(), on_presetDelete_clicked(), on_presetEdit_clicked(), on_presetImport_clicked(), on_presetSave_clicked(), and on_presetUpdate_clicked().
 {
     QTreeWidgetItem* group = 0;
     for(int i = 0; i < ui->presetTree->topLevelItemCount(); i++)
     {
         if(ui->presetTree->topLevelItem(i)->text(0) == preset->getGroup())
         {
             group = ui->presetTree->topLevelItem(i);
             break;
         }
     }
     if(group == 0)
     {
         QStringList sl;
         sl.append(preset->getGroup());
         group = new QTreeWidgetItem(ui->presetTree, sl, PGroup);
         group->setFirstColumnSpanned(true);
         group->setExpanded(true);
         ui->presetTree->sortByColumn(0, Qt::AscendingOrder);
     }
     QStringList sl;
     sl.append(QString("%1").arg(preset->getCenterFrequency() / 1e6f, 0, 'f', 3)); // frequency column
     sl.append(QString("%1").arg(preset->isSourcePreset() ? 'R' : 'T'));           // mode column
     sl.append(preset->getDescription());                                          // description column
     PresetItem* item = new PresetItem(group, sl, preset->getCenterFrequency(), PItem);
     item->setTextAlignment(0, Qt::AlignRight);
     item->setData(0, Qt::UserRole, qVariantFromValue(preset));
     ui->presetTree->resizeColumnToContents(0); // Resize frequency column to minimum
     ui->presetTree->resizeColumnToContents(1); // Resize mode column to minimum
     updatePresetControls();
     return item;
 }
addSinkDevice()
void MainWindow::addSinkDevice () private
Definition at line 347 of file mainwindow.cpp.
References DSPEngine::addDeviceSinkEngine(), DSPDeviceSinkEngine::addSpectrumSink(), channelAddClicked(), PluginInterface::SamplingDevice::deviceItemIndex, PluginInterface::SamplingDevice::deviceNbItems, PluginInterface::SamplingDevice::displayedName, DeviceUserArgs::findUserArgs(), MainSettings::getDeviceUserArgs(), DeviceEnumerator::getFileSinkDeviceIndex(), PluginInstanceGUI::getInputMessageQueue(), DeviceEnumerator::getTxSamplingDevice(), DSPDeviceSinkEngine::getUID(), PluginInterface::SamplingDevice::hardwareId, PluginInterface::SamplingDevice::id, DeviceEnumerator::instance(), PluginManager::listTxChannels(), m_deviceUIs, m_dspEngine, m_masterTimer, m_pluginManager, m_settings, sampleSinkChanged(), PluginInterface::SamplingDevice::sequence, PluginInterface::SamplingDevice::serial, setDeviceGUI(), DSPDeviceSinkEngine::start(), DeviceAPI::StreamSingleTx, and ui.
Referenced by handleMessage(), and on_action_addSinkDevice_triggered().
 {
     DSPDeviceSinkEngine *dspDeviceSinkEngine = m_dspEngine->addDeviceSinkEngine();
     dspDeviceSinkEngine->start();
     uint dspDeviceSinkEngineUID =  dspDeviceSinkEngine->getUID();
     char uidCStr[16];
     sprintf(uidCStr, "UID:%d", dspDeviceSinkEngineUID);
     int deviceTabIndex = m_deviceUIs.size();
     m_deviceUIs.push_back(new DeviceUISet(deviceTabIndex, 1, m_masterTimer));
     m_deviceUIs.back()->m_deviceSourceEngine = 0;
     m_deviceUIs.back()->m_deviceSinkEngine = dspDeviceSinkEngine;
     char tabNameCStr[16];
     sprintf(tabNameCStr, "T%d", deviceTabIndex);
     DeviceAPI *deviceAPI = new DeviceAPI(DeviceAPI::StreamSingleTx, deviceTabIndex, nullptr, dspDeviceSinkEngine, nullptr);
     m_deviceUIs.back()->m_deviceAPI = deviceAPI;
     m_deviceUIs.back()->m_samplingDeviceControl->setPluginManager(m_pluginManager);
     QList<QString> channelNames;
     m_pluginManager->listTxChannels(channelNames);
     QStringList channelNamesList(channelNames);
     m_deviceUIs.back()->m_samplingDeviceControl->getChannelSelector()->addItems(channelNamesList);
     m_deviceUIs.back()->setNumberOfAvailableTxChannels(channelNamesList.size());
     connect(m_deviceUIs.back()->m_samplingDeviceControl->getAddChannelButton(), SIGNAL(clicked(bool)), this, SLOT(channelAddClicked(bool)));
     dspDeviceSinkEngine->addSpectrumSink(m_deviceUIs.back()->m_spectrumVis);
     m_deviceUIs.back()->m_spectrum->setDisplayedStream(false, 0);
     ui->tabSpectra->addTab(m_deviceUIs.back()->m_spectrum, tabNameCStr);
     ui->tabSpectraGUI->addTab(m_deviceUIs.back()->m_spectrumGUI, tabNameCStr);
     ui->tabChannels->addTab(m_deviceUIs.back()->m_channelWindow, tabNameCStr);
     connect(m_deviceUIs.back()->m_samplingDeviceControl, SIGNAL(changed()), this, SLOT(sampleSinkChanged()));
     ui->tabInputsSelect->addTab(m_deviceUIs.back()->m_samplingDeviceControl, tabNameCStr);
     ui->tabInputsSelect->setTabToolTip(deviceTabIndex, QString(uidCStr));
     // create a file sink by default
     int fileSinkDeviceIndex = DeviceEnumerator::instance()->getFileSinkDeviceIndex();
     const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getTxSamplingDevice(fileSinkDeviceIndex);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDeviceSequence(samplingDevice->sequence);
     m_deviceUIs.back()->m_deviceAPI->setDeviceNbItems(samplingDevice->deviceNbItems);
     m_deviceUIs.back()->m_deviceAPI->setDeviceItemIndex(samplingDevice->deviceItemIndex);
     m_deviceUIs.back()->m_deviceAPI->setHardwareId(samplingDevice->hardwareId);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDeviceId(samplingDevice->id);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDeviceSerial(samplingDevice->serial);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDeviceDisplayName(samplingDevice->displayedName);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDevicePluginInterface(DeviceEnumerator::instance()->getTxPluginInterface(fileSinkDeviceIndex));
     QString userArgs = m_settings.getDeviceUserArgs().findUserArgs(samplingDevice->hardwareId, samplingDevice->sequence);
     if (userArgs.size() > 0) {
         m_deviceUIs.back()->m_deviceAPI->setHardwareUserArguments(userArgs);
     }
     m_deviceUIs.back()->m_samplingDeviceControl->setSelectedDeviceIndex(fileSinkDeviceIndex);
     // delete previous plugin GUI if it exists
     m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->deleteSampleSourcePluginInstanceGUI(
             m_deviceUIs.back()->m_deviceAPI->getSamplingDevicePluginInstanceGUI());
     DeviceSampleSink *sink = m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->createSampleSinkPluginInstance(
             m_deviceUIs.back()->m_deviceAPI->getSamplingDeviceId(), m_deviceUIs.back()->m_deviceAPI);
     m_deviceUIs.back()->m_deviceAPI->setSampleSink(sink);
     QWidget *gui;
     PluginInstanceGUI *pluginUI = m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->createSampleSinkPluginInstanceGUI(
             m_deviceUIs.back()->m_deviceAPI->getSamplingDeviceId(),
             &gui,
             m_deviceUIs.back());
     m_deviceUIs.back()->m_deviceAPI->getSampleSink()->setMessageQueueToGUI(pluginUI->getInputMessageQueue());
     m_deviceUIs.back()->m_deviceAPI->setSamplingDevicePluginInstanceGUI(pluginUI);
     m_deviceUIs.back()->m_deviceAPI->getSampleSink()->init();
     setDeviceGUI(deviceTabIndex, gui, m_deviceUIs.back()->m_deviceAPI->getSamplingDeviceDisplayName(), 1);
 }
addSourceDevice()
void MainWindow::addSourceDevice (int deviceIndex) private
Definition at line 267 of file mainwindow.cpp.
References DSPEngine::addDeviceSourceEngine(), DSPDeviceSourceEngine::addSink(), channelAddClicked(), PluginInterface::SamplingDevice::deviceItemIndex, PluginInterface::SamplingDevice::deviceNbItems, PluginInterface::SamplingDevice::displayedName, DeviceUserArgs::findUserArgs(), MainSettings::getDeviceUserArgs(), DeviceEnumerator::getFileInputDeviceIndex(), PluginInstanceGUI::getInputMessageQueue(), DeviceEnumerator::getRxSamplingDevice(), DSPDeviceSourceEngine::getUID(), PluginInterface::SamplingDevice::hardwareId, PluginInterface::SamplingDevice::id, DeviceEnumerator::instance(), PluginManager::listRxChannels(), m_deviceUIs, m_dspEngine, m_masterTimer, m_pluginManager, m_settings, sampleSourceChanged(), PluginInterface::SamplingDevice::sequence, PluginInterface::SamplingDevice::serial, setDeviceGUI(), DSPDeviceSourceEngine::start(), DeviceAPI::StreamSingleRx, and ui.
Referenced by handleMessage(), MainWindow(), and on_action_addSourceDevice_triggered().
 {
     DSPDeviceSourceEngine *dspDeviceSourceEngine = m_dspEngine->addDeviceSourceEngine();
     dspDeviceSourceEngine->start();
     uint dspDeviceSourceEngineUID =  dspDeviceSourceEngine->getUID();
     char uidCStr[16];
     sprintf(uidCStr, "UID:%d", dspDeviceSourceEngineUID);
     int deviceTabIndex = m_deviceUIs.size();
     m_deviceUIs.push_back(new DeviceUISet(deviceTabIndex, 0, m_masterTimer));
     m_deviceUIs.back()->m_deviceSourceEngine = dspDeviceSourceEngine;
     char tabNameCStr[16];
     sprintf(tabNameCStr, "R%d", deviceTabIndex);
     DeviceAPI *deviceAPI = new DeviceAPI(DeviceAPI::StreamSingleRx, deviceTabIndex, dspDeviceSourceEngine, nullptr, nullptr);
     m_deviceUIs.back()->m_deviceAPI = deviceAPI;
     m_deviceUIs.back()->m_samplingDeviceControl->setPluginManager(m_pluginManager);
     QList<QString> channelNames;
     m_pluginManager->listRxChannels(channelNames);
     QStringList channelNamesList(channelNames);
     m_deviceUIs.back()->m_samplingDeviceControl->getChannelSelector()->addItems(channelNamesList);
     m_deviceUIs.back()->setNumberOfAvailableRxChannels(channelNamesList.size());
     connect(m_deviceUIs.back()->m_samplingDeviceControl->getAddChannelButton(), SIGNAL(clicked(bool)), this, SLOT(channelAddClicked(bool)));
     dspDeviceSourceEngine->addSink(m_deviceUIs.back()->m_spectrumVis);
     ui->tabSpectra->addTab(m_deviceUIs.back()->m_spectrum, tabNameCStr);
     ui->tabSpectraGUI->addTab(m_deviceUIs.back()->m_spectrumGUI, tabNameCStr);
     ui->tabChannels->addTab(m_deviceUIs.back()->m_channelWindow, tabNameCStr);
     connect(m_deviceUIs.back()->m_samplingDeviceControl, SIGNAL(changed()), this, SLOT(sampleSourceChanged()));
     ui->tabInputsSelect->addTab(m_deviceUIs.back()->m_samplingDeviceControl, tabNameCStr);
     ui->tabInputsSelect->setTabToolTip(deviceTabIndex, QString(uidCStr));
     // Create a file source instance by default if requested device was not enumerated (index = -1)
     if (deviceIndex < 0) {
         deviceIndex = DeviceEnumerator::instance()->getFileInputDeviceIndex();
     }
     const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getRxSamplingDevice(deviceIndex);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDeviceSequence(samplingDevice->sequence);
     m_deviceUIs.back()->m_deviceAPI->setDeviceNbItems(samplingDevice->deviceNbItems);
     m_deviceUIs.back()->m_deviceAPI->setDeviceItemIndex(samplingDevice->deviceItemIndex);
     m_deviceUIs.back()->m_deviceAPI->setHardwareId(samplingDevice->hardwareId);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDeviceId(samplingDevice->id);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDeviceSerial(samplingDevice->serial);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDeviceDisplayName(samplingDevice->displayedName);
     m_deviceUIs.back()->m_deviceAPI->setSamplingDevicePluginInterface(DeviceEnumerator::instance()->getRxPluginInterface(deviceIndex));
     QString userArgs = m_settings.getDeviceUserArgs().findUserArgs(samplingDevice->hardwareId, samplingDevice->sequence);
     if (userArgs.size() > 0) {
         m_deviceUIs.back()->m_deviceAPI->setHardwareUserArguments(userArgs);
     }
     m_deviceUIs.back()->m_samplingDeviceControl->setSelectedDeviceIndex(deviceIndex);
     // delete previous plugin GUI
     m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->deleteSampleSourcePluginInstanceGUI(
             m_deviceUIs.back()->m_deviceAPI->getSamplingDevicePluginInstanceGUI());
     DeviceSampleSource *source = m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->createSampleSourcePluginInstance(
             m_deviceUIs.back()->m_deviceAPI->getSamplingDeviceId(), m_deviceUIs.back()->m_deviceAPI);
     m_deviceUIs.back()->m_deviceAPI->setSampleSource(source);
     QWidget *gui;
     PluginInstanceGUI *pluginGUI = m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->createSampleSourcePluginInstanceGUI(
             m_deviceUIs.back()->m_deviceAPI->getSamplingDeviceId(),
             &gui,
             m_deviceUIs.back());
     m_deviceUIs.back()->m_deviceAPI->getSampleSource()->setMessageQueueToGUI(pluginGUI->getInputMessageQueue());
     m_deviceUIs.back()->m_deviceAPI->setSamplingDevicePluginInstanceGUI(pluginGUI);
     m_deviceUIs.back()->m_deviceAPI->getSampleSource()->init();
     setDeviceGUI(deviceTabIndex, gui, m_deviceUIs.back()->m_deviceAPI->getSamplingDeviceDisplayName());
 }
addViewAction()
void MainWindow::addViewAction (QAction * action)
Definition at line 671 of file mainwindow.cpp.
References ui.
 {
     ui->menu_Window->addAction(action);
 }
applySettings()
void MainWindow::applySettings () private
Definition at line 921 of file mainwindow.cpp.
Referenced by MainWindow(), and on_presetLoad_clicked().
 {
 }
channelAddClicked
void MainWindow::channelAddClicked (bool checked) private slot
Definition at line 1894 of file mainwindow.cpp.
References PluginManager::createRxChannelInstance(), PluginManager::createTxChannelInstance(), SamplingDeviceControl::getChannelSelector(), DeviceUISet::getNumberOfAvailableRxChannels(), DeviceUISet::getNumberOfAvailableTxChannels(), DeviceUISet::m_deviceAPI, DeviceUISet::m_deviceMIMOEngine, DeviceUISet::m_deviceSinkEngine, DeviceUISet::m_deviceSourceEngine, m_deviceUIs, m_pluginManager, DeviceUISet::m_samplingDeviceControl, and ui.
Referenced by addMIMODevice(), addSinkDevice(), addSourceDevice(), and handleMessage().
 {
     (void) checked;
     // Do it in the currently selected source tab
     int currentSourceTabIndex = ui->tabInputsSelect->currentIndex();
     if (currentSourceTabIndex >= 0)
     {
         DeviceUISet *deviceUI = m_deviceUIs[currentSourceTabIndex];
         if (deviceUI->m_deviceSourceEngine) // source device => Rx channels
         {
             m_pluginManager->createRxChannelInstance(
                 deviceUI->m_samplingDeviceControl->getChannelSelector()->currentIndex(), deviceUI, deviceUI->m_deviceAPI);
         }
         else if (deviceUI->m_deviceSinkEngine) // sink device => Tx channels
         {
             m_pluginManager->createTxChannelInstance(
                 deviceUI->m_samplingDeviceControl->getChannelSelector()->currentIndex(), deviceUI, deviceUI->m_deviceAPI);
         }
         else if (deviceUI->m_deviceMIMOEngine) // MIMO device => all possible channels. Depends on index range
         {
             int nbRxChannels = deviceUI->getNumberOfAvailableRxChannels();
             int nbTxChannels = deviceUI->getNumberOfAvailableTxChannels();
             int selectedIndex = deviceUI->m_samplingDeviceControl->getChannelSelector()->currentIndex();
             qDebug("MainWindow::channelAddClicked: MIMO: tab: %d nbRx: %d nbTx: %d selected: %d",
                 currentSourceTabIndex, nbRxChannels, nbTxChannels, selectedIndex);
             if (selectedIndex < nbRxChannels) {
                 m_pluginManager->createRxChannelInstance(
                     selectedIndex, deviceUI, deviceUI->m_deviceAPI);
             } else if (selectedIndex < nbRxChannels + nbTxChannels) {
                 m_pluginManager->createTxChannelInstance(
                     selectedIndex - nbRxChannels, deviceUI, deviceUI->m_deviceAPI);
             }
         }
     }
 }
closeEvent()
void MainWindow::closeEvent (QCloseEvent * closeEvent) private
Definition at line 815 of file mainwindow.cpp.
References MainSettings::getWorkingPreset(), m_deviceUIs, m_settings, removeLastDevice(), MainSettings::save(), and savePresetSettings().
 {
     qDebug("MainWindow::closeEvent");
     savePresetSettings(m_settings.getWorkingPreset(), 0);
     m_settings.save();
     while (m_deviceUIs.size() > 0)
     {
         removeLastDevice();
     }
     closeEvent->accept();
 }
commandKeyPressed
void MainWindow::commandKeyPressed (Qt::Key key, Qt::KeyboardModifiers keyModifiers, bool release) private slot
Definition at line 2039 of file mainwindow.cpp.
References Command::getAssociateKey(), MainSettings::getCommand(), MainSettings::getCommandCount(), WebAPIServer::getHost(), Command::getKey(), Command::getKeyModifiers(), WebAPIServer::getPort(), Command::getRelease(), i, m_apiServer, m_settings, Command::run(), and ui.
Referenced by on_commandKeyboardConnect_toggled().
 {
     //qDebug("MainWindow::commandKeyPressed: key: %x mod: %x %s", (int) key, (int) keyModifiers, release ? "release" : "press");
     int currentDeviceSetIndex = ui->tabInputsSelect->currentIndex();
     for (int i = 0; i < m_settings.getCommandCount(); ++i)
     {
         const Command* command = m_settings.getCommand(i);
         if (command->getAssociateKey()
                 && (command->getRelease() == release)
                 && (command->getKey() == key)
                 && (command->getKeyModifiers() == keyModifiers))
         {
             Command* command_mod = const_cast<Command*>(command);
             command_mod->run(m_apiServer->getHost(), m_apiServer->getPort(), currentDeviceSetIndex);
         }
     }
 }
commandKeysConnect()
void MainWindow::commandKeysConnect (QObject * object, const char * slot)
Definition at line 1276 of file mainwindow.cpp.
References m_commandKeyReceiver.
Referenced by on_commandKeyboardConnect_toggled(), and CWKeyerGUI::on_keyboardKeyer_toggled().
 {
     setFocus();
     connect(m_commandKeyReceiver, SIGNAL(capturedKey(Qt::Key, Qt::KeyboardModifiers, bool)),
             object, slot);
 }
commandKeysDisconnect()
void MainWindow::commandKeysDisconnect (QObject * object, const char * slot)
Definition at line 1283 of file mainwindow.cpp.
References m_commandKeyReceiver.
Referenced by on_commandKeyboardConnect_toggled(), and CWKeyerGUI::on_keyboardKeyer_toggled().
 {
     disconnect(m_commandKeyReceiver, SIGNAL(capturedKey(Qt::Key, Qt::KeyboardModifiers, bool)),
             object, slot);
 }
createStatusBar()
void MainWindow::createStatusBar () private
Definition at line 799 of file mainwindow.cpp.
References m_dateTimeWidget, and m_showSystemWidget.
Referenced by MainWindow().
 {
     QString qtVersionStr = QString("Qt %1 ").arg(QT_VERSION_STR);
 #if QT_VERSION >= 0x050400
     m_showSystemWidget = new QLabel("SDRangel " + qApp->applicationVersion() + " " + qtVersionStr
             + QSysInfo::currentCpuArchitecture() + " " + QSysInfo::prettyProductName(), this);
 #else
     m_showSystemWidget = new QLabel("SDRangel " + qApp->applicationVersion() + " " + qtVersionStr, this);
 #endif
     statusBar()->addPermanentWidget(m_showSystemWidget);
     m_dateTimeWidget = new QLabel(tr("Date"), this);
     m_dateTimeWidget->setToolTip(tr("Current date/time"));
     statusBar()->addPermanentWidget(m_dateTimeWidget);
 }
deleteChannel()
void MainWindow::deleteChannel (int deviceSetIndex, int channelIndex) private
Definition at line 643 of file mainwindow.cpp.
References DeviceUISet::deleteRxChannel(), DeviceUISet::deleteTxChannel(), DeviceUISet::m_deviceSinkEngine, DeviceUISet::m_deviceSourceEngine, and m_deviceUIs.
Referenced by handleMessage().
 {
     if ((deviceSetIndex >= 0) && (deviceSetIndex < (int) m_deviceUIs.size()))
     {
         DeviceUISet *deviceSet = m_deviceUIs[deviceSetIndex];
         if (deviceSet->m_deviceSourceEngine) // source device => Rx channels
         {
             deviceSet->deleteRxChannel(channelIndex);
         }
         else if (deviceSet->m_deviceSinkEngine) // sink device => Tx channels
         {
             deviceSet->deleteTxChannel(channelIndex);
         }
     }
 }
getInputMessageQueue()
MessageQueue* MainWindow::getInputMessageQueue () inline
Definition at line 75 of file mainwindow.h.
 { return &m_inputMessageQueue; }
getInstance()
static MainWindow* MainWindow::getInstance () inline static
Definition at line 73 of file mainwindow.h.
Referenced by AMDemodGUI::AMDemodGUI(), AMModGUI::AMModGUI(), ATVDemodGUI::ATVDemodGUI(), ATVModGUI::ATVModGUI(), BFMDemodGUI::BFMDemodGUI(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), DSDDemodGUI::DSDDemodGUI(), FreeDVDemodGUI::FreeDVDemodGUI(), FreeDVModGUI::FreeDVModGUI(), FreqTrackerGUI::FreqTrackerGUI(), NFMDemodGUI::NFMDemodGUI(), NFMModGUI::NFMModGUI(), CWKeyerGUI::on_keyboardKeyer_toggled(), SSBDemodGUI::SSBDemodGUI(), SSBModGUI::SSBModGUI(), UDPSinkGUI::UDPSinkGUI(), UDPSourceGUI::UDPSourceGUI(), DSDDemodGUI::updateMyPosition(), WFMDemodGUI::WFMDemodGUI(), and WFMModGUI::WFMModGUI().
 { return m_instance; } // Main Window is de facto a singleton so this just returns its reference
getMainSettings()
const MainSettings& MainWindow::getMainSettings () const inline
Definition at line 83 of file mainwindow.h.
Referenced by WebAPIAdapterGUI::instanceConfigGet(), and DSDDemodGUI::updateMyPosition().
 { return m_settings; }
getMasterTimer()
const QTimer& MainWindow::getMasterTimer () const inline
Definition at line 82 of file mainwindow.h.
 { return m_masterTimer; }
handleMessage()
bool MainWindow::handleMessage (const Message & cmd) private
Definition at line 925 of file mainwindow.cpp.
References addMIMODevice(), addPresetToTree(), addSinkDevice(), addSourceDevice(), channelAddClicked(), deleteChannel(), MainSettings::deletePreset(), Preset::getCenterFrequency(), MainWindow::MsgDeleteChannel::getChannelIndex(), MainWindow::MsgAddChannel::getChannelRegistrationIndex(), SamplingDeviceControl::getChannelSelector(), Preset::getDescription(), MainWindow::MsgSetDevice::getDeviceIndex(), MainWindow::MsgLoadPreset::getDeviceSetIndex(), MainWindow::MsgSavePreset::getDeviceSetIndex(), MainWindow::MsgSetDevice::getDeviceSetIndex(), MainWindow::MsgAddChannel::getDeviceSetIndex(), MainWindow::MsgDeleteChannel::getDeviceSetIndex(), MainWindow::MsgDeviceSetFocus::getDeviceSetIndex(), MainWindow::MsgSetDevice::getDeviceType(), MainWindow::MsgAddDeviceSet::getDirection(), Preset::getGroup(), MainWindow::MsgLoadPreset::getPreset(), MainWindow::MsgSavePreset::getPreset(), MainWindow::MsgDeletePreset::getPreset(), MainWindow::MsgSavePreset::isNewPreset(), Preset::isSourcePreset(), loadPresetSettings(), m_deviceUIs, DeviceUISet::m_samplingDeviceControl, m_settings, Message::match(), removeLastDevice(), sampleMIMOChanged(), sampleSinkChanged(), sampleSourceChanged(), MainSettings::save(), savePresetSettings(), SamplingDeviceControl::setSelectedDeviceIndex(), MainSettings::sortPresets(), and ui.
Referenced by handleMessages().
 {
     if (MsgLoadPreset::match(cmd))
     {
         MsgLoadPreset& notif = (MsgLoadPreset&) cmd;
         loadPresetSettings(notif.getPreset(), notif.getDeviceSetIndex());
         return true;
     }
     else if (MsgSavePreset::match(cmd))
     {
         MsgSavePreset& notif = (MsgSavePreset&) cmd;
         savePresetSettings(notif.getPreset(), notif.getDeviceSetIndex());
         if (notif.isNewPreset()) { ui->presetTree->setCurrentItem(addPresetToTree(notif.getPreset())); }
         m_settings.sortPresets();
         m_settings.save();
         return true;
     }
     else if (MsgDeletePreset::match(cmd))
     {
         MsgDeletePreset& notif = (MsgDeletePreset&) cmd;
         const Preset *presetToDelete = notif.getPreset();
         // remove preset from tree
         for (int ig = 0; ig < ui->presetTree->topLevelItemCount(); ig++)
         {
             QTreeWidgetItem *groupItem = ui->presetTree->topLevelItem(ig);
             if (groupItem->text(0) == presetToDelete->getGroup())
             {
                 for (int ip = 0; ip < groupItem->childCount(); ip++)
                 {
                     QTreeWidgetItem *presetItem = groupItem->child(ip);
                     const Preset* preset = qvariant_cast<const Preset*>(presetItem->data(0, Qt::UserRole));
                     if ((preset->getGroup() == presetToDelete->getGroup()) &&
                         (preset->getCenterFrequency() == presetToDelete->getCenterFrequency()) &&
                         (preset->getDescription() == presetToDelete->getDescription()) &&
                         (preset->isSourcePreset() == presetToDelete->isSourcePreset()))
                     {
                         groupItem->takeChild(ip);
                     }
                 }
             }
         }
         // remove preset from settings
         m_settings.deletePreset(presetToDelete);
         return true;
     }
     else if (MsgAddDeviceSet::match(cmd))
     {
         MsgAddDeviceSet& notif = (MsgAddDeviceSet&) cmd;
         int direction = notif.getDirection();
         if (direction == 1) { // Single stream Tx
             addSinkDevice();
         } else if (direction == 0) { // Single stream Rx
             addSourceDevice(-1); // create with file source device by default
         } else if (direction == 2) { // MIMO
             addMIMODevice();
         }
         return true;
     }
     else if (MsgRemoveLastDeviceSet::match(cmd))
     {
         if (m_deviceUIs.size() > 1) {
             removeLastDevice();
         }
         return true;
     }
     else if (MsgSetDevice::match(cmd))
     {
         MsgSetDevice& notif = (MsgSetDevice&) cmd;
         ui->tabInputsSelect->setCurrentIndex(notif.getDeviceSetIndex());
         DeviceUISet *deviceUI = m_deviceUIs[notif.getDeviceSetIndex()];
         deviceUI->m_samplingDeviceControl->setSelectedDeviceIndex(notif.getDeviceIndex());
         if (notif.getDeviceType() == 1) {
             sampleSinkChanged();
         } else if (notif.getDeviceType() == 0) {
             sampleSourceChanged();
         } else if (notif.getDeviceType() == 2) {
             sampleMIMOChanged();
         }
         return true;
     }
     else if (MsgAddChannel::match(cmd))
     {
         MsgAddChannel& notif = (MsgAddChannel&) cmd;
         ui->tabInputsSelect->setCurrentIndex(notif.getDeviceSetIndex());
         DeviceUISet *deviceUI = m_deviceUIs[notif.getDeviceSetIndex()];
         deviceUI->m_samplingDeviceControl->getChannelSelector()->setCurrentIndex(notif.getChannelRegistrationIndex());
         channelAddClicked(true);
         return true;
     }
     else if (MsgDeleteChannel::match(cmd))
     {
         MsgDeleteChannel& notif = (MsgDeleteChannel&) cmd;
         deleteChannel(notif.getDeviceSetIndex(), notif.getChannelIndex());
         return true;
     }
     else if (MsgDeviceSetFocus::match(cmd))
     {
         MsgDeviceSetFocus& notif = (MsgDeviceSetFocus&) cmd;
         int index = notif.getDeviceSetIndex();
         if ((index >= 0) && (index < (int) m_deviceUIs.size())) {
             ui->tabInputsView->setCurrentIndex(index);
         }
     }
     return false;
 }
handleMessages
void MainWindow::handleMessages () private slot
Definition at line 1041 of file mainwindow.cpp.
References Message::getIdentifier(), handleMessage(), m_inputMessageQueue, and MessageQueue::pop().
Referenced by MainWindow().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("MainWindow::handleMessages: message: %s", message->getIdentifier());
         handleMessage(*message);
         delete message;
     }
 }
loadPresetSettings()
void MainWindow::loadPresetSettings (const Preset * preset, int tabIndex) private
Definition at line 736 of file mainwindow.cpp.
References GLSpectrumGUI::deserialize(), Preset::getDescription(), Preset::getGroup(), Preset::getLayout(), PluginManager::getPluginAPI(), Preset::getSpectrumConfig(), DeviceUISet::loadRxChannelSettings(), DeviceAPI::loadSamplingDeviceSettings(), DeviceUISet::loadTxChannelSettings(), DeviceUISet::m_deviceAPI, DeviceUISet::m_deviceSinkEngine, DeviceUISet::m_deviceSourceEngine, m_deviceUIs, m_pluginManager, DeviceUISet::m_spectrumGUI, and ui.
Referenced by handleMessage(), MainWindow(), and on_presetLoad_clicked().
 {
     qDebug("MainWindow::loadPresetSettings: preset [%s | %s]",
         qPrintable(preset->getGroup()),
         qPrintable(preset->getDescription()));
     if (tabIndex >= 0)
     {
         DeviceUISet *deviceUI = m_deviceUIs[tabIndex];
         if (deviceUI->m_deviceSourceEngine) // source device
         {
             deviceUI->m_spectrumGUI->deserialize(preset->getSpectrumConfig());
             deviceUI->m_deviceAPI->loadSamplingDeviceSettings(preset);
             deviceUI->loadRxChannelSettings(preset, m_pluginManager->getPluginAPI());
         }
         else if (deviceUI->m_deviceSinkEngine) // sink device
         {
             deviceUI->m_spectrumGUI->deserialize(preset->getSpectrumConfig());
             deviceUI->m_deviceAPI->loadSamplingDeviceSettings(preset);
             deviceUI->loadTxChannelSettings(preset, m_pluginManager->getPluginAPI());
         }
     }
     // has to be last step
     restoreState(preset->getLayout());
     tabifyDockWidget(ui->presetDock, ui->commandsDock); // override this setting
     ui->presetDock->raise();
 }
loadSettings()
void MainWindow::loadSettings () private
Definition at line 708 of file mainwindow.cpp.
References addCommandToTree(), addPresetToTree(), MainSettings::getCommand(), MainSettings::getCommandCount(), MainSettings::getPreset(), MainSettings::getPresetCount(), i, MainSettings::load(), m_settings, setLoggingOptions(), MainSettings::sortCommands(), MainSettings::sortPresets(), and ui.
Referenced by MainWindow().
 {
     qDebug() << "MainWindow::loadSettings";
     m_settings.load();
     m_settings.sortPresets();
     int middleIndex = m_settings.getPresetCount() / 2;
     QTreeWidgetItem *treeItem;
     for (int i = 0; i < m_settings.getPresetCount(); ++i)
     {
         treeItem = addPresetToTree(m_settings.getPreset(i));
         if (i == middleIndex) {
             ui->presetTree->setCurrentItem(treeItem);
         }
     }
     m_settings.sortCommands();
     for (int i = 0; i < m_settings.getCommandCount(); ++i)
     {
         treeItem = addCommandToTree(m_settings.getCommand(i));
     }
     setLoggingOptions();
 }
on_action_About_triggered
void MainWindow::on_action_About_triggered () private slot
Definition at line 1933 of file mainwindow.cpp.
References m_apiHost, m_apiPort, and m_settings.
 {
     AboutDialog dlg(m_apiHost, m_apiPort, m_settings, this);
     dlg.exec();
 }
on_action_addMIMODevice_triggered
void MainWindow::on_action_addMIMODevice_triggered () private slot
Definition at line 1949 of file mainwindow.cpp.
References addMIMODevice(), DSPEngine::getMIMOSupport(), and m_dspEngine.
 {
     if (m_dspEngine->getMIMOSupport()) {
         addMIMODevice();
     } else {
         QMessageBox::information(this, tr("Message"), tr("MIMO operation not supported yet"));
     }
 }
on_action_addSinkDevice_triggered
void MainWindow::on_action_addSinkDevice_triggered () private slot
Definition at line 1944 of file mainwindow.cpp.
References addSinkDevice().
 {
     addSinkDevice();
 }
on_action_addSourceDevice_triggered
void MainWindow::on_action_addSourceDevice_triggered () private slot
Definition at line 1939 of file mainwindow.cpp.
References addSourceDevice().
 {
     addSourceDevice(-1); // create with file source device by default
 }
on_action_AMBE_triggered
void MainWindow::on_action_AMBE_triggered () private slot
Definition at line 1646 of file mainwindow.cpp.
References DSPEngine::getAMBEEngine(), and m_dspEngine.
 {
     qDebug("MainWindow::on_action_AMBE_triggered");
     AMBEDevicesDialog ambeDevicesDialog(m_dspEngine->getAMBEEngine(), this);
     ambeDevicesDialog.exec();
 }
on_action_Audio_triggered
void MainWindow::on_action_Audio_triggered () private slot
Definition at line 1620 of file mainwindow.cpp.
References DSPEngine::getAudioDeviceManager(), and m_dspEngine.
 {
     AudioDialogX audioDialog(m_dspEngine->getAudioDeviceManager(), this);
     audioDialog.exec();
 }
on_action_DeviceUserArguments_triggered
void MainWindow::on_action_DeviceUserArguments_triggered () private slot
Definition at line 1639 of file mainwindow.cpp.
References MainSettings::getDeviceUserArgs(), DeviceEnumerator::instance(), and m_settings.
 {
     qDebug("MainWindow::on_action_DeviceUserArguments_triggered");
     DeviceUserArgsDialog deviceUserArgsDialog(DeviceEnumerator::instance(), m_settings.getDeviceUserArgs(), this);
     deviceUserArgsDialog.exec();
 }
on_action_Loaded_Plugins_triggered
void MainWindow::on_action_Loaded_Plugins_triggered () private slot
Definition at line 1614 of file mainwindow.cpp.
References m_pluginManager.
 {
     PluginsDialog pluginsDialog(m_pluginManager, this);
     pluginsDialog.exec();
 }
on_action_Logging_triggered
void MainWindow::on_action_Logging_triggered () private slot
Definition at line 1626 of file mainwindow.cpp.
References m_settings, and setLoggingOptions().
 {
     LoggingDialog loggingDialog(m_settings, this);
     loggingDialog.exec();
     setLoggingOptions();
 }
on_action_My_Position_triggered
void MainWindow::on_action_My_Position_triggered () private slot
Definition at line 1633 of file mainwindow.cpp.
References m_settings.
 {
     MyPositionDialog myPositionDialog(m_settings, this);
     myPositionDialog.exec();
 }
on_action_removeLastDevice_triggered
void MainWindow::on_action_removeLastDevice_triggered () private slot
Definition at line 1958 of file mainwindow.cpp.
References m_deviceUIs, and removeLastDevice().
 {
     if (m_deviceUIs.size() > 1)
     {
         removeLastDevice();
     }
 }
on_action_View_Fullscreen_toggled
void MainWindow::on_action_View_Fullscreen_toggled (bool checked) private slot
Definition at line 1053 of file mainwindow.cpp.
 {
     if(checked) {
         showFullScreen();
     } else {
         showNormal();
     }
 }
on_commandDelete_clicked
void MainWindow::on_commandDelete_clicked () private slot
Definition at line 1186 of file mainwindow.cpp.
References addCommandToTree(), arg(), MainSettings::deleteCommand(), MainSettings::deleteCommandGroup(), MainSettings::getCommand(), MainSettings::getCommandCount(), Command::getDescription(), i, m_settings, PGroup, PItem, and ui.
 {
     QTreeWidgetItem* item = ui->commandTree->currentItem();
     if (item != 0)
     {
         if (item->type() == PItem) // delete individual command
         {
             const Command* command = qvariant_cast<const Command*>(item->data(0, Qt::UserRole));
             if(command)
             {
                 if (QMessageBox::question(this,
                         tr("Delete command"),
                         tr("Do you want to delete command '%1'?")
                             .arg(command->getDescription()), QMessageBox::No | QMessageBox::Yes, QMessageBox::No) == QMessageBox::Yes)
                 {
                     delete item;
                     m_settings.deleteCommand(command);
                 }
             }
         }
         else if (item->type() == PGroup) // delete all commands in this group
         {
             if (QMessageBox::question(this,
                     tr("Delete command group"),
                     tr("Do you want to delete command group '%1'?")
                         .arg(item->text(0)), QMessageBox::No | QMessageBox::Yes, QMessageBox::No) == QMessageBox::Yes)
             {
                 m_settings.deleteCommandGroup(item->text(0));
                 ui->commandTree->clear();
                 for (int i = 0; i < m_settings.getCommandCount(); ++i) {
                     addCommandToTree(m_settings.getCommand(i));
                 }
             }
         }
     }
 }
on_commandDuplicate_clicked
void MainWindow::on_commandDuplicate_clicked () private slot
Definition at line 1099 of file mainwindow.cpp.
References MainSettings::addCommand(), addCommandToTree(), m_settings, MainSettings::sortCommands(), and ui.
 {
     QTreeWidgetItem* item = ui->commandTree->currentItem();
     const Command* command = qvariant_cast<const Command*>(item->data(0, Qt::UserRole));
     Command *commandCopy = new Command(*command);
     m_settings.addCommand(commandCopy);
     ui->commandTree->setCurrentItem(addCommandToTree(commandCopy));
     m_settings.sortCommands();
 }
on_commandEdit_clicked
void MainWindow::on_commandEdit_clicked () private slot
Definition at line 1109 of file mainwindow.cpp.
References addCommandToTree(), EditCommandDialog::fromCommand(), MainSettings::getCommand(), MainSettings::getCommandCount(), Command::getGroup(), i, m_settings, PGroup, PItem, MainSettings::renameCommandGroup(), AddPresetDialog::showGroupOnly(), MainSettings::sortCommands(), and ui.
 {
     QTreeWidgetItem* item = ui->commandTree->currentItem();
     bool change = false;
     const Command *changedCommand = 0;
     QString newGroupName;
     QStringList groups;
     for(int i = 0; i < ui->commandTree->topLevelItemCount(); i++) {
         groups.append(ui->commandTree->topLevelItem(i)->text(0));
     }
     if(item != 0)
     {
         if (item->type() == PItem)
         {
             const Command* command = qvariant_cast<const Command*>(item->data(0, Qt::UserRole));
             if (command != 0)
             {
                 EditCommandDialog editCommandDialog(groups, command->getGroup(), this);
                 editCommandDialog.fromCommand(*command);
                 if (editCommandDialog.exec() == QDialog::Accepted)
                 {
                     Command* command_mod = const_cast<Command*>(command);
                     editCommandDialog.toCommand(*command_mod);
                     change = true;
                     changedCommand = command;
                 }
             }
         }
         else if (item->type() == PGroup)
         {
             AddPresetDialog dlg(groups, item->text(0), this);
             dlg.showGroupOnly();
             dlg.setDialogTitle("Edit command group");
             dlg.setDescriptionBoxTitle("Command details");
             if (dlg.exec() == QDialog::Accepted)
             {
                 m_settings.renameCommandGroup(item->text(0), dlg.group());
                 newGroupName = dlg.group();
                 change = true;
             }
         }
     }
     if (change)
     {
         m_settings.sortCommands();
         ui->commandTree->clear();
         for (int i = 0; i < m_settings.getCommandCount(); ++i)
         {
             QTreeWidgetItem *item_x = addCommandToTree(m_settings.getCommand(i));
             const Command* command_x = qvariant_cast<const Command*>(item_x->data(0, Qt::UserRole));
             if (changedCommand &&  (command_x == changedCommand)) { // set cursor on changed command
                 ui->commandTree->setCurrentItem(item_x);
             }
         }
         if (!changedCommand) // on group name change set cursor on the group that has been changed
         {
             for(int i = 0; i < ui->commandTree->topLevelItemCount(); i++)
             {
                 QTreeWidgetItem* item = ui->commandTree->topLevelItem(i);
                 if (item->text(0) == newGroupName) {
                     ui->commandTree->setCurrentItem(item);
                 }
             }
         }
     }
 }
on_commandKeyboardConnect_toggled
void MainWindow::on_commandKeyboardConnect_toggled (bool checked) private slot
Definition at line 1289 of file mainwindow.cpp.
References commandKeyPressed(), commandKeysConnect(), and commandKeysDisconnect().
 {
     qDebug("on_commandKeyboardConnect_toggled: %s", checked ? "true" : "false");
     if (checked)
     {
         commandKeysConnect(this, SLOT(commandKeyPressed(Qt::Key, Qt::KeyboardModifiers, bool)));
     }
     else
     {
         commandKeysDisconnect(this, SLOT(commandKeyPressed(Qt::Key, Qt::KeyboardModifiers, bool)));
     }
 }
on_commandNew_clicked
void MainWindow::on_commandNew_clicked () private slot
Definition at line 1062 of file mainwindow.cpp.
References MainSettings::addCommand(), addCommandToTree(), EditCommandDialog::fromCommand(), i, m_settings, PGroup, PItem, Command::setDescription(), Command::setGroup(), MainSettings::sortCommands(), EditCommandDialog::toCommand(), and ui.
 {
     QStringList groups;
     QString group = "";
     QString description = "";
     for(int i = 0; i < ui->commandTree->topLevelItemCount(); i++) {
         groups.append(ui->commandTree->topLevelItem(i)->text(0));
     }
     QTreeWidgetItem* item = ui->commandTree->currentItem();
     if(item != 0)
     {
         if(item->type() == PGroup) {
             group = item->text(0);
         } else if(item->type() == PItem) {
             group = item->parent()->text(0);
             description = item->text(0);
         }
     }
     Command *command = new Command();
     command->setGroup(group);
     command->setDescription(description);
     EditCommandDialog editCommandDialog(groups, group, this);
     editCommandDialog.fromCommand(*command);
     if (editCommandDialog.exec() == QDialog::Accepted)
     {
         editCommandDialog.toCommand(*command);
         m_settings.addCommand(command);
         ui->commandTree->setCurrentItem(addCommandToTree(command));
         m_settings.sortCommands();
     }
 }
on_commandOutput_clicked
void MainWindow::on_commandOutput_clicked () private slot
Definition at line 1257 of file mainwindow.cpp.
References PItem, and ui.
 {
     QTreeWidgetItem* item = ui->commandTree->currentItem();
     if ((item != 0) && (item->type() == PItem))
     {
         const Command* command = qvariant_cast<const Command*>(item->data(0, Qt::UserRole));
         Command* command_mod = const_cast<Command*>(command);
         CommandOutputDialog commandOutputDialog(*command_mod);
         commandOutputDialog.exec();
     }
 }
on_commandRun_clicked
void MainWindow::on_commandRun_clicked () private slot
Definition at line 1227 of file mainwindow.cpp.
References MainSettings::getCommand(), MainSettings::getCommandCount(), Command::getGroup(), WebAPIServer::getHost(), WebAPIServer::getPort(), i, m_apiServer, m_settings, PGroup, PItem, Command::run(), and ui.
 {
     QTreeWidgetItem* item = ui->commandTree->currentItem();
     if (item != 0)
     {
         int currentDeviceSetIndex = ui->tabInputsSelect->currentIndex();
         if (item->type() == PItem) // run individual command
         {
             const Command* command = qvariant_cast<const Command*>(item->data(0, Qt::UserRole));
             Command* command_mod = const_cast<Command*>(command);
             command_mod->run(m_apiServer->getHost(), m_apiServer->getPort(), currentDeviceSetIndex);
         }
         else if (item->type() == PGroup) // run all commands in this group
         {
             QString group = item->text(0);
             for (int i = 0; i < m_settings.getCommandCount(); ++i)
             {
                 Command *command_mod = const_cast<Command*>(m_settings.getCommand(i));
                 if (command_mod->getGroup() == group) {
                     command_mod->run(m_apiServer->getHost(), m_apiServer->getPort(), currentDeviceSetIndex);
                 }
             }
         }
     }
 }
on_commandsSave_clicked
void MainWindow::on_commandsSave_clicked () private slot
Definition at line 1270 of file mainwindow.cpp.
References m_settings, MainSettings::save(), and saveCommandSettings().
 {
     saveCommandSettings();
     m_settings.save();
 }
on_presetDelete_clicked
void MainWindow::on_presetDelete_clicked () private slot
Definition at line 1558 of file mainwindow.cpp.
References addPresetToTree(), arg(), MainSettings::deletePreset(), MainSettings::deletePresetGroup(), Preset::getDescription(), MainSettings::getPreset(), MainSettings::getPresetCount(), i, m_settings, PGroup, PItem, ui, and updatePresetControls().
 {
     QTreeWidgetItem* item = ui->presetTree->currentItem();
     if (item == 0)
     {
         updatePresetControls();
         return;
     }
     else
     {
         if (item->type() == PItem)
         {
             const Preset* preset = qvariant_cast<const Preset*>(item->data(0, Qt::UserRole));
             if (preset)
             {
                 if(QMessageBox::question(this, tr("Delete Preset"), tr("Do you want to delete preset '%1'?").arg(preset->getDescription()), QMessageBox::No | QMessageBox::Yes, QMessageBox::No) == QMessageBox::Yes) {
                     delete item;
                     m_settings.deletePreset(preset);
                 }
             }
         }
         else if (item->type() == PGroup)
         {
             if (QMessageBox::question(this,
                     tr("Delete preset group"),
                     tr("Do you want to delete preset group '%1'?")
                         .arg(item->text(0)), QMessageBox::No | QMessageBox::Yes, QMessageBox::No) == QMessageBox::Yes)
             {
                 m_settings.deletePresetGroup(item->text(0));
                 ui->presetTree->clear();
                 for (int i = 0; i < m_settings.getPresetCount(); ++i) {
                     addPresetToTree(m_settings.getPreset(i));
                 }
             }
         }
     }
 }
on_presetEdit_clicked
void MainWindow::on_presetEdit_clicked () private slot
Definition at line 1374 of file mainwindow.cpp.
References addPresetToTree(), Preset::getDescription(), Preset::getGroup(), MainSettings::getPreset(), MainSettings::getPresetCount(), i, m_settings, PGroup, PItem, MainSettings::renamePresetGroup(), AddPresetDialog::setDescription(), Preset::setDescription(), Preset::setGroup(), AddPresetDialog::showGroupOnly(), MainSettings::sortPresets(), and ui.
 {
     QTreeWidgetItem* item = ui->presetTree->currentItem();
     QStringList groups;
     bool change = false;
     const Preset *changedPreset = 0;
     QString newGroupName;
     for(int i = 0; i < ui->presetTree->topLevelItemCount(); i++) {
         groups.append(ui->presetTree->topLevelItem(i)->text(0));
     }
     if(item != 0)
     {
         if (item->type() == PItem)
         {
             const Preset* preset = qvariant_cast<const Preset*>(item->data(0, Qt::UserRole));
             AddPresetDialog dlg(groups, preset->getGroup(), this);
             dlg.setDescription(preset->getDescription());
             if (dlg.exec() == QDialog::Accepted)
             {
                 Preset* preset_mod = const_cast<Preset*>(preset);
                 preset_mod->setGroup(dlg.group());
                 preset_mod->setDescription(dlg.description());
                 change = true;
                 changedPreset = preset;
             }
         }
         else if (item->type() == PGroup)
         {
             AddPresetDialog dlg(groups, item->text(0), this);
             dlg.showGroupOnly();
             dlg.setDialogTitle("Edit preset group");
             if (dlg.exec() == QDialog::Accepted)
             {
                 m_settings.renamePresetGroup(item->text(0), dlg.group());
                 newGroupName = dlg.group();
                 change = true;
             }
         }
     }
     if (change)
     {
         m_settings.sortPresets();
         ui->presetTree->clear();
         for (int i = 0; i < m_settings.getPresetCount(); ++i)
         {
             QTreeWidgetItem *item_x = addPresetToTree(m_settings.getPreset(i));
             const Preset* preset_x = qvariant_cast<const Preset*>(item_x->data(0, Qt::UserRole));
             if (changedPreset &&  (preset_x == changedPreset)) { // set cursor on changed preset
                 ui->presetTree->setCurrentItem(item_x);
             }
         }
         if (!changedPreset) // on group name change set cursor on the group that has been changed
         {
             for(int i = 0; i < ui->presetTree->topLevelItemCount(); i++)
             {
                 QTreeWidgetItem* item = ui->presetTree->topLevelItem(i);
                 if (item->text(0) == newGroupName) {
                     ui->presetTree->setCurrentItem(item);
                 }
             }
         }
     }
 }
on_presetExport_clicked
void MainWindow::on_presetExport_clicked () private slot
Definition at line 1446 of file mainwindow.cpp.
References PItem, Preset::serialize(), and ui.
 {
     QTreeWidgetItem* item = ui->presetTree->currentItem();
     if(item != 0) {
         if(item->type() == PItem)
         {
             const Preset* preset = qvariant_cast<const Preset*>(item->data(0, Qt::UserRole));
             QString base64Str = preset->serialize().toBase64();
             QString fileName = QFileDialog::getSaveFileName(this,
                 tr("Open preset export file"), ".", tr("Preset export files (*.prex)"), 0, QFileDialog::DontUseNativeDialog);
             if (fileName != "")
             {
                 QFileInfo fileInfo(fileName);
                 if (fileInfo.suffix() != "prex") {
                     fileName += ".prex";
                 }
                 QFile exportFile(fileName);
                 if (exportFile.open(QIODevice::WriteOnly | QIODevice::Text))
                 {
                     QTextStream outstream(&exportFile);
                     outstream << base64Str;
                     exportFile.close();
                 }
                 else
                 {
                     QMessageBox::information(this, tr("Message"), tr("Cannot open file for writing"));
                 }
             }
         }
     }
 }
on_presetImport_clicked
void MainWindow::on_presetImport_clicked () private slot
Definition at line 1483 of file mainwindow.cpp.
References addPresetToTree(), Preset::deserialize(), m_settings, MainSettings::newPreset(), PGroup, PItem, Preset::setGroup(), and ui.
 {
     QTreeWidgetItem* item = ui->presetTree->currentItem();
     if(item != 0)
     {
         QString group;
         if (item->type() == PGroup) {
             group = item->text(0);
         } else if (item->type() == PItem) {
             group = item->parent()->text(0);
         } else {
             return;
         }
         QString fileName = QFileDialog::getOpenFileName(this,
             tr("Open preset export file"), ".", tr("Preset export files (*.prex)"), 0, QFileDialog::DontUseNativeDialog);
         if (fileName != "")
         {
             QFile exportFile(fileName);
             if (exportFile.open(QIODevice::ReadOnly | QIODevice::Text))
             {
                 QByteArray base64Str;
                 QTextStream instream(&exportFile);
                 instream >> base64Str;
                 exportFile.close();
                 Preset* preset = m_settings.newPreset("", "");
                 preset->deserialize(QByteArray::fromBase64(base64Str));
                 preset->setGroup(group); // override with current group
                 ui->presetTree->setCurrentItem(addPresetToTree(preset));
             }
             else
             {
                 QMessageBox::information(this, tr("Message"), tr("Cannot open file for reading"));
             }
         }
     }
 }
on_presetLoad_clicked
void MainWindow::on_presetLoad_clicked () private slot
Definition at line 1533 of file mainwindow.cpp.
References applySettings(), loadPresetSettings(), ui, and updatePresetControls().
Referenced by on_presetTree_itemActivated().
 {
     qDebug() << "MainWindow::on_presetLoad_clicked";
     QTreeWidgetItem* item = ui->presetTree->currentItem();
     if(item == 0)
     {
         qDebug("MainWindow::on_presetLoad_clicked: item null");
         updatePresetControls();
         return;
     }
     const Preset* preset = qvariant_cast<const Preset*>(item->data(0, Qt::UserRole));
     if(preset == 0)
     {
         qDebug("MainWindow::on_presetLoad_clicked: preset null");
         return;
     }
     loadPresetSettings(preset, ui->tabInputsView->currentIndex());
     applySettings();
 }
on_presetSave_clicked
void MainWindow::on_presetSave_clicked () private slot
Definition at line 1303 of file mainwindow.cpp.
References addPresetToTree(), AddPresetDialog::description(), AddPresetDialog::group(), i, m_settings, MainSettings::newPreset(), PGroup, PItem, savePresetSettings(), AddPresetDialog::setDescription(), MainSettings::sortPresets(), and ui.
 {
     QStringList groups;
     QString group;
     QString description = "";
     for(int i = 0; i < ui->presetTree->topLevelItemCount(); i++) {
         groups.append(ui->presetTree->topLevelItem(i)->text(0));
     }
     QTreeWidgetItem* item = ui->presetTree->currentItem();
     if(item != 0)
     {
         if(item->type() == PGroup) {
             group = item->text(0);
         } else if(item->type() == PItem) {
             group = item->parent()->text(0);
             description = item->text(0);
         }
     }
     AddPresetDialog dlg(groups, group, this);
     if (description.length() > 0) {
         dlg.setDescription(description);
     }
     if(dlg.exec() == QDialog::Accepted) {
         Preset* preset = m_settings.newPreset(dlg.group(), dlg.description());
         savePresetSettings(preset, ui->tabInputsView->currentIndex());
         ui->presetTree->setCurrentItem(addPresetToTree(preset));
     }
     m_settings.sortPresets();
 }
on_presetTree_currentItemChanged
void MainWindow::on_presetTree_currentItemChanged (QTreeWidgetItem * current, QTreeWidgetItem * previous) private slot
Definition at line 1600 of file mainwindow.cpp.
References updatePresetControls().
 {
     (void) current;
     (void) previous;
     updatePresetControls();
 }
on_presetTree_itemActivated
void MainWindow::on_presetTree_itemActivated (QTreeWidgetItem * item, int column) private slot
Definition at line 1607 of file mainwindow.cpp.
References on_presetLoad_clicked().
 {
     (void) item;
     (void) column;
     on_presetLoad_clicked();
 }
on_presetUpdate_clicked
void MainWindow::on_presetUpdate_clicked () private slot
Definition at line 1341 of file mainwindow.cpp.
References addPresetToTree(), MainSettings::getPreset(), MainSettings::getPresetCount(), i, m_settings, PItem, savePresetSettings(), MainSettings::sortPresets(), and ui.
 {
     QTreeWidgetItem* item = ui->presetTree->currentItem();
     const Preset* changedPreset = 0;
     if(item != 0)
     {
         if(item->type() == PItem)
         {
             const Preset* preset = qvariant_cast<const Preset*>(item->data(0, Qt::UserRole));
             if (preset != 0)
             {
                 Preset* preset_mod = const_cast<Preset*>(preset);
                 savePresetSettings(preset_mod, ui->tabInputsView->currentIndex());
                 changedPreset = preset;
             }
         }
     }
     m_settings.sortPresets();
     ui->presetTree->clear();
     for (int i = 0; i < m_settings.getPresetCount(); ++i)
     {
         QTreeWidgetItem *item_x = addPresetToTree(m_settings.getPreset(i));
         const Preset* preset_x = qvariant_cast<const Preset*>(item_x->data(0, Qt::UserRole));
         if (changedPreset &&  (preset_x == changedPreset)) { // set cursor on changed preset
             ui->presetTree->setCurrentItem(item_x);
         }
     }
 }
on_settingsSave_clicked
void MainWindow::on_settingsSave_clicked () private slot
Definition at line 1527 of file mainwindow.cpp.
References MainSettings::getWorkingPreset(), m_settings, MainSettings::save(), savePresetSettings(), and ui.
 {
     savePresetSettings(m_settings.getWorkingPreset(), ui->tabInputsView->currentIndex());
     m_settings.save();
 }
removeLastDevice()
void MainWindow::removeLastDevice () private
Definition at line 512 of file mainwindow.cpp.
References i, m_deviceUIs, m_deviceWidgetTabs, m_dspEngine, DSPEngine::removeLastDeviceMIMOEngine(), DSPEngine::removeLastDeviceSinkEngine(), DSPEngine::removeLastDeviceSourceEngine(), DSPDeviceSourceEngine::removeSink(), DSPDeviceSinkEngine::removeSpectrumSink(), DSPDeviceMIMOEngine::removeSpectrumSink(), DSPDeviceSourceEngine::stop(), DSPDeviceSinkEngine::stop(), DSPDeviceMIMOEngine::stop(), DSPDeviceSourceEngine::stopAcquistion(), DSPDeviceSinkEngine::stopGeneration(), DSPDeviceMIMOEngine::stopProcess(), and ui.
Referenced by closeEvent(), handleMessage(), and on_action_removeLastDevice_triggered().
 {
     if (m_deviceUIs.back()->m_deviceSourceEngine) // source tab
     {
         DSPDeviceSourceEngine *lastDeviceEngine = m_deviceUIs.back()->m_deviceSourceEngine;
         lastDeviceEngine->stopAcquistion();
         lastDeviceEngine->removeSink(m_deviceUIs.back()->m_spectrumVis);
         ui->tabSpectraGUI->removeTab(ui->tabSpectraGUI->count() - 1);
         ui->tabSpectra->removeTab(ui->tabSpectra->count() - 1);
         // deletes old UI and input object
         m_deviceUIs.back()->freeRxChannels();      // destroys the channel instances
         m_deviceUIs.back()->m_deviceAPI->getSampleSource()->setMessageQueueToGUI(0); // have source stop sending messages to the GUI
         m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->deleteSampleSourcePluginInstanceGUI(
                 m_deviceUIs.back()->m_deviceAPI->getSamplingDevicePluginInstanceGUI());
         m_deviceUIs.back()->m_deviceAPI->resetSamplingDeviceId();
         m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->deleteSampleSourcePluginInstanceInput(
                 m_deviceUIs.back()->m_deviceAPI->getSampleSource());
         m_deviceUIs.back()->m_deviceAPI->clearBuddiesLists(); // clear old API buddies lists
         m_deviceUIs.back()->m_samplingDeviceControl->removeSelectedDeviceIndex(); // This releases the device in the device list
         ui->tabChannels->removeTab(ui->tabChannels->count() - 1);
         ui->tabInputsSelect->removeTab(ui->tabInputsSelect->count() - 1);
         m_deviceWidgetTabs.removeLast();
         ui->tabInputsView->clear();
         for (int i = 0; i < m_deviceWidgetTabs.size(); i++)
         {
             qDebug("MainWindow::removeLastDevice: adding back tab for %s", m_deviceWidgetTabs[i].displayName.toStdString().c_str());
             ui->tabInputsView->addTab(m_deviceWidgetTabs[i].gui, m_deviceWidgetTabs[i].tabName);
             ui->tabInputsView->setTabToolTip(i, m_deviceWidgetTabs[i].displayName);
         }
         DeviceAPI *sourceAPI = m_deviceUIs.back()->m_deviceAPI;
         delete m_deviceUIs.back();
         lastDeviceEngine->stop();
         m_dspEngine->removeLastDeviceSourceEngine();
         delete sourceAPI;
     }
     else if (m_deviceUIs.back()->m_deviceSinkEngine) // sink tab
     {
         DSPDeviceSinkEngine *lastDeviceEngine = m_deviceUIs.back()->m_deviceSinkEngine;
         lastDeviceEngine->stopGeneration();
         lastDeviceEngine->removeSpectrumSink(m_deviceUIs.back()->m_spectrumVis);
         ui->tabSpectraGUI->removeTab(ui->tabSpectraGUI->count() - 1);
         ui->tabSpectra->removeTab(ui->tabSpectra->count() - 1);
         // deletes old UI and output object
         m_deviceUIs.back()->freeTxChannels();
         m_deviceUIs.back()->m_deviceAPI->getSampleSink()->setMessageQueueToGUI(0); // have sink stop sending messages to the GUI
         m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->deleteSampleSourcePluginInstanceGUI(
                 m_deviceUIs.back()->m_deviceAPI->getSamplingDevicePluginInstanceGUI());
         m_deviceUIs.back()->m_deviceAPI->resetSamplingDeviceId();
         m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->deleteSampleSinkPluginInstanceOutput(
                 m_deviceUIs.back()->m_deviceAPI->getSampleSink());
         m_deviceUIs.back()->m_deviceAPI->clearBuddiesLists(); // clear old API buddies lists
         m_deviceUIs.back()->m_samplingDeviceControl->removeSelectedDeviceIndex(); // This releases the device in the device list
         ui->tabChannels->removeTab(ui->tabChannels->count() - 1);
         ui->tabInputsSelect->removeTab(ui->tabInputsSelect->count() - 1);
         m_deviceWidgetTabs.removeLast();
         ui->tabInputsView->clear();
         for (int i = 0; i < m_deviceWidgetTabs.size(); i++)
         {
             qDebug("MainWindow::removeLastDevice: adding back tab for %s", m_deviceWidgetTabs[i].displayName.toStdString().c_str());
             ui->tabInputsView->addTab(m_deviceWidgetTabs[i].gui, m_deviceWidgetTabs[i].tabName);
             ui->tabInputsView->setTabToolTip(i, m_deviceWidgetTabs[i].displayName);
         }
         DeviceAPI *sinkAPI = m_deviceUIs.back()->m_deviceAPI;
         delete m_deviceUIs.back();
         lastDeviceEngine->stop();
         m_dspEngine->removeLastDeviceSinkEngine();
         delete sinkAPI;
     }
     else if (m_deviceUIs.back()->m_deviceMIMOEngine) // MIMO tab
     {
         DSPDeviceMIMOEngine *lastDeviceEngine = m_deviceUIs.back()->m_deviceMIMOEngine;
         lastDeviceEngine->stopProcess();
         lastDeviceEngine->removeSpectrumSink(m_deviceUIs.back()->m_spectrumVis);
         ui->tabSpectraGUI->removeTab(ui->tabSpectraGUI->count() - 1);
         ui->tabSpectra->removeTab(ui->tabSpectra->count() - 1);
         // deletes old UI and output object
         m_deviceUIs.back()->freeRxChannels();
         m_deviceUIs.back()->freeTxChannels();
         m_deviceUIs.back()->m_deviceAPI->getSampleMIMO()->setMessageQueueToGUI(nullptr); // have sink stop sending messages to the GUI
         m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->deleteSampleMIMOPluginInstanceGUI(
                 m_deviceUIs.back()->m_deviceAPI->getSamplingDevicePluginInstanceGUI());
         m_deviceUIs.back()->m_deviceAPI->resetSamplingDeviceId();
         m_deviceUIs.back()->m_deviceAPI->getPluginInterface()->deleteSampleMIMOPluginInstanceMIMO(
                 m_deviceUIs.back()->m_deviceAPI->getSampleMIMO());
         m_deviceUIs.back()->m_samplingDeviceControl->removeSelectedDeviceIndex(); // This releases the device in the device list
         ui->tabChannels->removeTab(ui->tabChannels->count() - 1);
         ui->tabInputsSelect->removeTab(ui->tabInputsSelect->count() - 1);
         m_deviceWidgetTabs.removeLast();
         ui->tabInputsView->clear();
         for (int i = 0; i < m_deviceWidgetTabs.size(); i++)
         {
             qDebug("MainWindow::removeLastDevice: adding back tab for %s", m_deviceWidgetTabs[i].displayName.toStdString().c_str());
             ui->tabInputsView->addTab(m_deviceWidgetTabs[i].gui, m_deviceWidgetTabs[i].tabName);
             ui->tabInputsView->setTabToolTip(i, m_deviceWidgetTabs[i].displayName);
         }
         DeviceAPI *mimoAPI = m_deviceUIs.back()->m_deviceAPI;
         delete m_deviceUIs.back();
         lastDeviceEngine->stop();
         m_dspEngine->removeLastDeviceMIMOEngine();
         delete mimoAPI;
     }
     m_deviceUIs.pop_back();
 }
sampleMIMOChanged
void MainWindow::sampleMIMOChanged () private slot
Definition at line 1838 of file mainwindow.cpp.
References PluginInterface::createSampleMIMOPluginInstance(), PluginInterface::createSampleMIMOPluginInstanceGUI(), PluginInterface::deleteSampleMIMOPluginInstanceGUI(), PluginInterface::deleteSampleMIMOPluginInstanceMIMO(), PluginInterface::SamplingDevice::deviceItemIndex, PluginInterface::SamplingDevice::deviceNbItems, PluginInterface::SamplingDevice::displayedName, DeviceUserArgs::findUserArgs(), MainSettings::getDeviceUserArgs(), PluginInstanceGUI::getInputMessageQueue(), DeviceEnumerator::getMIMOSamplingDevice(), DeviceAPI::getPluginInterface(), DeviceAPI::getSampleMIMO(), DeviceAPI::getSamplingDeviceDisplayName(), DeviceAPI::getSamplingDeviceId(), DeviceAPI::getSamplingDevicePluginInstanceGUI(), SamplingDeviceControl::getSelectedDeviceIndex(), MainSettings::getWorkingPreset(), PluginInterface::SamplingDevice::hardwareId, PluginInterface::SamplingDevice::id, DeviceEnumerator::instance(), DeviceAPI::loadSamplingDeviceSettings(), DeviceUISet::m_deviceAPI, m_deviceUIs, DeviceUISet::m_samplingDeviceControl, m_settings, DeviceAPI::resetSamplingDeviceId(), DeviceAPI::saveSamplingDeviceSettings(), PluginInterface::SamplingDevice::sequence, PluginInterface::SamplingDevice::serial, setDeviceGUI(), DeviceAPI::setDeviceItemIndex(), DeviceAPI::setDeviceNbItems(), DeviceAPI::setHardwareId(), DeviceAPI::setHardwareUserArguments(), DeviceSampleMIMO::setMessageQueueToGUI(), DeviceAPI::setSampleMIMO(), DeviceAPI::setSamplingDeviceDisplayName(), DeviceAPI::setSamplingDeviceId(), DeviceAPI::setSamplingDevicePluginInstanceGUI(), DeviceAPI::setSamplingDevicePluginInterface(), DeviceAPI::setSamplingDeviceSequence(), DeviceAPI::setSamplingDeviceSerial(), DeviceAPI::stopDeviceEngine(), and ui.
Referenced by addMIMODevice(), and handleMessage().
 {
     // Do it in the currently selected source tab
     int currentMIMOTabIndex = ui->tabInputsSelect->currentIndex();
     if (currentMIMOTabIndex >= 0)
     {
         qDebug("MainWindow::sampleMIMOChanged: tab at %d", currentMIMOTabIndex);
         DeviceUISet *deviceUI = m_deviceUIs[currentMIMOTabIndex];
         deviceUI->m_deviceAPI->saveSamplingDeviceSettings(m_settings.getWorkingPreset()); // save old API settings
         deviceUI->m_deviceAPI->stopDeviceEngine();
         // deletes old UI and output object
         deviceUI->m_deviceAPI->getSampleMIMO()->setMessageQueueToGUI(nullptr); // have sink stop sending messages to the GUI
         deviceUI->m_deviceAPI->getPluginInterface()->deleteSampleMIMOPluginInstanceGUI(
                 deviceUI->m_deviceAPI->getSamplingDevicePluginInstanceGUI());
         deviceUI->m_deviceAPI->resetSamplingDeviceId();
         deviceUI->m_deviceAPI->getPluginInterface()->deleteSampleMIMOPluginInstanceMIMO(
                 deviceUI->m_deviceAPI->getSampleMIMO());
         const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getMIMOSamplingDevice(
             deviceUI->m_samplingDeviceControl->getSelectedDeviceIndex());
         deviceUI->m_deviceAPI->setSamplingDeviceSequence(samplingDevice->sequence);
         deviceUI->m_deviceAPI->setDeviceNbItems(samplingDevice->deviceNbItems);
         deviceUI->m_deviceAPI->setDeviceItemIndex(samplingDevice->deviceItemIndex);
         deviceUI->m_deviceAPI->setHardwareId(samplingDevice->hardwareId);
         deviceUI->m_deviceAPI->setSamplingDeviceId(samplingDevice->id);
         deviceUI->m_deviceAPI->setSamplingDeviceSerial(samplingDevice->serial);
         deviceUI->m_deviceAPI->setSamplingDeviceDisplayName(samplingDevice->displayedName);
         deviceUI->m_deviceAPI->setSamplingDevicePluginInterface(
             DeviceEnumerator::instance()->getMIMOPluginInterface(deviceUI->m_samplingDeviceControl->getSelectedDeviceIndex()));
         QString userArgs = m_settings.getDeviceUserArgs().findUserArgs(samplingDevice->hardwareId, samplingDevice->sequence);
         if (userArgs.size() > 0) {
             deviceUI->m_deviceAPI->setHardwareUserArguments(userArgs);
         }
         // constructs new GUI and MIMO object
         DeviceSampleMIMO *mimo = deviceUI->m_deviceAPI->getPluginInterface()->createSampleMIMOPluginInstance(
                 deviceUI->m_deviceAPI->getSamplingDeviceId(), deviceUI->m_deviceAPI);
         deviceUI->m_deviceAPI->setSampleMIMO(mimo);
         QWidget *gui;
         PluginInstanceGUI *pluginUI = deviceUI->m_deviceAPI->getPluginInterface()->createSampleMIMOPluginInstanceGUI(
                 deviceUI->m_deviceAPI->getSamplingDeviceId(),
                 &gui,
                 deviceUI);
         deviceUI->m_deviceAPI->getSampleMIMO()->setMessageQueueToGUI(pluginUI->getInputMessageQueue());
         deviceUI->m_deviceAPI->setSamplingDevicePluginInstanceGUI(pluginUI);
         setDeviceGUI(currentMIMOTabIndex, gui, deviceUI->m_deviceAPI->getSamplingDeviceDisplayName(), 2);
         m_deviceUIs.back()->m_deviceAPI->getSampleMIMO()->init();
         deviceUI->m_deviceAPI->loadSamplingDeviceSettings(m_settings.getWorkingPreset()); // load new API settings
     }
 }
sampleSinkChanged
void MainWindow::sampleSinkChanged () private slot
Definition at line 1749 of file mainwindow.cpp.
References DeviceAPI::clearBuddiesLists(), PluginInterface::createSampleSinkPluginInstance(), PluginInterface::createSampleSinkPluginInstanceGUI(), PluginInterface::deleteSampleSinkPluginInstanceOutput(), PluginInterface::deleteSampleSourcePluginInstanceGUI(), PluginInterface::SamplingDevice::deviceItemIndex, PluginInterface::SamplingDevice::deviceNbItems, PluginInterface::SamplingDevice::displayedName, DeviceUserArgs::findUserArgs(), MainSettings::getDeviceUserArgs(), DeviceAPI::getHardwareId(), PluginInstanceGUI::getInputMessageQueue(), DeviceAPI::getPluginInterface(), DeviceAPI::getSampleSink(), DeviceAPI::getSamplingDeviceDisplayName(), DeviceAPI::getSamplingDeviceId(), DeviceAPI::getSamplingDevicePluginInstanceGUI(), DeviceAPI::getSamplingDeviceSerial(), SamplingDeviceControl::getSelectedDeviceIndex(), DeviceEnumerator::getTxSamplingDevice(), MainSettings::getWorkingPreset(), PluginInterface::SamplingDevice::hardwareId, PluginInterface::SamplingDevice::id, DeviceEnumerator::instance(), DeviceAPI::loadSamplingDeviceSettings(), DeviceUISet::m_deviceAPI, m_deviceUIs, DeviceUISet::m_samplingDeviceControl, m_settings, DeviceAPI::resetSamplingDeviceId(), DeviceAPI::saveSamplingDeviceSettings(), PluginInterface::SamplingDevice::sequence, PluginInterface::SamplingDevice::serial, DeviceAPI::setBuddyLeader(), setDeviceGUI(), DeviceAPI::setDeviceItemIndex(), DeviceAPI::setDeviceNbItems(), DeviceAPI::setHardwareId(), DeviceAPI::setHardwareUserArguments(), DeviceSampleSink::setMessageQueueToGUI(), DeviceAPI::setSampleSink(), DeviceAPI::setSamplingDeviceDisplayName(), DeviceAPI::setSamplingDeviceId(), DeviceAPI::setSamplingDevicePluginInstanceGUI(), DeviceAPI::setSamplingDevicePluginInterface(), DeviceAPI::setSamplingDeviceSequence(), DeviceAPI::setSamplingDeviceSerial(), DeviceAPI::stopDeviceEngine(), and ui.
Referenced by addSinkDevice(), and handleMessage().
 {
     // Do it in the currently selected source tab
     int currentSinkTabIndex = ui->tabInputsSelect->currentIndex();
     if (currentSinkTabIndex >= 0)
     {
         qDebug("MainWindow::sampleSinkChanged: tab at %d", currentSinkTabIndex);
         DeviceUISet *deviceUI = m_deviceUIs[currentSinkTabIndex];
         deviceUI->m_deviceAPI->saveSamplingDeviceSettings(m_settings.getWorkingPreset()); // save old API settings
         deviceUI->m_deviceAPI->stopDeviceEngine();
         // deletes old UI and output object
         deviceUI->m_deviceAPI->getSampleSink()->setMessageQueueToGUI(0); // have sink stop sending messages to the GUI
         deviceUI->m_deviceAPI->getPluginInterface()->deleteSampleSourcePluginInstanceGUI(
                 deviceUI->m_deviceAPI->getSamplingDevicePluginInstanceGUI());
         deviceUI->m_deviceAPI->resetSamplingDeviceId();
         deviceUI->m_deviceAPI->getPluginInterface()->deleteSampleSinkPluginInstanceOutput(
                 deviceUI->m_deviceAPI->getSampleSink());
         deviceUI->m_deviceAPI->clearBuddiesLists(); // clear old API buddies lists
         const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getTxSamplingDevice(deviceUI->m_samplingDeviceControl->getSelectedDeviceIndex());
         deviceUI->m_deviceAPI->setSamplingDeviceSequence(samplingDevice->sequence);
         deviceUI->m_deviceAPI->setDeviceNbItems(samplingDevice->deviceNbItems);
         deviceUI->m_deviceAPI->setDeviceItemIndex(samplingDevice->deviceItemIndex);
         deviceUI->m_deviceAPI->setHardwareId(samplingDevice->hardwareId);
         deviceUI->m_deviceAPI->setSamplingDeviceId(samplingDevice->id);
         deviceUI->m_deviceAPI->setSamplingDeviceSerial(samplingDevice->serial);
         deviceUI->m_deviceAPI->setSamplingDeviceDisplayName(samplingDevice->displayedName);
         deviceUI->m_deviceAPI->setSamplingDevicePluginInterface(DeviceEnumerator::instance()->getTxPluginInterface(deviceUI->m_samplingDeviceControl->getSelectedDeviceIndex()));
         QString userArgs = m_settings.getDeviceUserArgs().findUserArgs(samplingDevice->hardwareId, samplingDevice->sequence);
         if (userArgs.size() > 0) {
             deviceUI->m_deviceAPI->setHardwareUserArguments(userArgs);
         }
         // add to buddies list
         std::vector<DeviceUISet*>::iterator it = m_deviceUIs.begin();
         int nbOfBuddies = 0;
         for (; it != m_deviceUIs.end(); ++it)
         {
             if (*it != deviceUI) // do not add to itself
             {
                 if ((*it)->m_deviceSourceEngine) // it is a source device
                 {
                     if ((deviceUI->m_deviceAPI->getHardwareId() == (*it)->m_deviceAPI->getHardwareId()) &&
                         (deviceUI->m_deviceAPI->getSamplingDeviceSerial() == (*it)->m_deviceAPI->getSamplingDeviceSerial()))
                     {
                         (*it)->m_deviceAPI->addSinkBuddy(deviceUI->m_deviceAPI);
                         nbOfBuddies++;
                     }
                 }
                 if ((*it)->m_deviceSinkEngine) // it is a sink device
                 {
                     if ((deviceUI->m_deviceAPI->getHardwareId() == (*it)->m_deviceAPI->getHardwareId()) &&
                         (deviceUI->m_deviceAPI->getSamplingDeviceSerial() == (*it)->m_deviceAPI->getSamplingDeviceSerial()))
                     {
                         (*it)->m_deviceAPI->addSinkBuddy(deviceUI->m_deviceAPI);
                         nbOfBuddies++;
                     }
                 }
             }
         }
         if (nbOfBuddies == 0) {
             deviceUI->m_deviceAPI->setBuddyLeader(true);
         }
         // constructs new GUI and output object
         DeviceSampleSink *sink = deviceUI->m_deviceAPI->getPluginInterface()->createSampleSinkPluginInstance(
                 deviceUI->m_deviceAPI->getSamplingDeviceId(), deviceUI->m_deviceAPI);
         deviceUI->m_deviceAPI->setSampleSink(sink);
         QWidget *gui;
         PluginInstanceGUI *pluginUI = deviceUI->m_deviceAPI->getPluginInterface()->createSampleSinkPluginInstanceGUI(
                 deviceUI->m_deviceAPI->getSamplingDeviceId(),
                 &gui,
                 deviceUI);
         deviceUI->m_deviceAPI->getSampleSink()->setMessageQueueToGUI(pluginUI->getInputMessageQueue());
         deviceUI->m_deviceAPI->setSamplingDevicePluginInstanceGUI(pluginUI);
         setDeviceGUI(currentSinkTabIndex, gui, deviceUI->m_deviceAPI->getSamplingDeviceDisplayName(), 1);
         m_deviceUIs.back()->m_deviceAPI->getSampleSink()->init();
         deviceUI->m_deviceAPI->loadSamplingDeviceSettings(m_settings.getWorkingPreset()); // load new API settings
     }
 }
sampleSourceChanged
void MainWindow::sampleSourceChanged () private slot
Definition at line 1653 of file mainwindow.cpp.
References DeviceAPI::clearBuddiesLists(), PluginInterface::createSampleSourcePluginInstance(), PluginInterface::createSampleSourcePluginInstanceGUI(), PluginInterface::deleteSampleSourcePluginInstanceGUI(), PluginInterface::deleteSampleSourcePluginInstanceInput(), PluginInterface::SamplingDevice::deviceItemIndex, PluginInterface::SamplingDevice::deviceNbItems, PluginInterface::SamplingDevice::displayedName, DeviceUserArgs::findUserArgs(), MainSettings::getDeviceUserArgs(), DeviceAPI::getHardwareId(), PluginInstanceGUI::getInputMessageQueue(), DeviceAPI::getPluginInterface(), DeviceEnumerator::getRxSamplingDevice(), DeviceAPI::getSampleSource(), DeviceAPI::getSamplingDeviceDisplayName(), DeviceAPI::getSamplingDeviceId(), DeviceAPI::getSamplingDevicePluginInstanceGUI(), DeviceAPI::getSamplingDeviceSerial(), SamplingDeviceControl::getSelectedDeviceIndex(), MainSettings::getWorkingPreset(), PluginInterface::SamplingDevice::hardwareId, PluginInterface::SamplingDevice::id, DeviceSampleSource::init(), DeviceEnumerator::instance(), DeviceAPI::loadSamplingDeviceSettings(), DeviceUISet::m_deviceAPI, m_deviceUIs, DeviceUISet::m_samplingDeviceControl, m_settings, DeviceAPI::resetSamplingDeviceId(), DeviceAPI::saveSamplingDeviceSettings(), PluginInterface::SamplingDevice::sequence, PluginInterface::SamplingDevice::serial, DeviceAPI::setBuddyLeader(), setDeviceGUI(), DeviceAPI::setDeviceItemIndex(), DeviceAPI::setDeviceNbItems(), DeviceAPI::setHardwareId(), DeviceAPI::setHardwareUserArguments(), DeviceSampleSource::setMessageQueueToGUI(), DeviceAPI::setSampleSource(), DeviceAPI::setSamplingDeviceDisplayName(), DeviceAPI::setSamplingDeviceId(), DeviceAPI::setSamplingDevicePluginInstanceGUI(), DeviceAPI::setSamplingDevicePluginInterface(), DeviceAPI::setSamplingDeviceSequence(), DeviceAPI::setSamplingDeviceSerial(), MainSettings::setSourceDeviceId(), MainSettings::setSourceIndex(), DeviceAPI::stopDeviceEngine(), and ui.
Referenced by addSourceDevice(), and handleMessage().
 {
     // Do it in the currently selected source tab
     int currentSourceTabIndex = ui->tabInputsSelect->currentIndex();
     if (currentSourceTabIndex >= 0)
     {
         qDebug("MainWindow::sampleSourceChanged: tab at %d", currentSourceTabIndex);
         DeviceUISet *deviceUI = m_deviceUIs[currentSourceTabIndex];
         deviceUI->m_deviceAPI->saveSamplingDeviceSettings(m_settings.getWorkingPreset()); // save old API settings
         deviceUI->m_deviceAPI->stopDeviceEngine();
         // deletes old UI and input object
         deviceUI->m_deviceAPI->getSampleSource()->setMessageQueueToGUI(0); // have source stop sending messages to the GUI
         deviceUI->m_deviceAPI->getPluginInterface()->deleteSampleSourcePluginInstanceGUI(
                 deviceUI->m_deviceAPI->getSamplingDevicePluginInstanceGUI());
         deviceUI->m_deviceAPI->resetSamplingDeviceId();
         deviceUI->m_deviceAPI->getPluginInterface()->deleteSampleSourcePluginInstanceInput(
                 deviceUI->m_deviceAPI->getSampleSource());
         deviceUI->m_deviceAPI->clearBuddiesLists(); // clear old API buddies lists
         const PluginInterface::SamplingDevice *samplingDevice = DeviceEnumerator::instance()->getRxSamplingDevice(
             deviceUI->m_samplingDeviceControl->getSelectedDeviceIndex());
         deviceUI->m_deviceAPI->setSamplingDeviceSequence(samplingDevice->sequence);
         deviceUI->m_deviceAPI->setDeviceNbItems(samplingDevice->deviceNbItems);
         deviceUI->m_deviceAPI->setDeviceItemIndex(samplingDevice->deviceItemIndex);
         deviceUI->m_deviceAPI->setHardwareId(samplingDevice->hardwareId);
         deviceUI->m_deviceAPI->setSamplingDeviceId(samplingDevice->id);
         deviceUI->m_deviceAPI->setSamplingDeviceSerial(samplingDevice->serial);
         deviceUI->m_deviceAPI->setSamplingDeviceDisplayName(samplingDevice->displayedName);
         deviceUI->m_deviceAPI->setSamplingDevicePluginInterface(DeviceEnumerator::instance()->getRxPluginInterface(deviceUI->m_samplingDeviceControl->getSelectedDeviceIndex()));
         QString userArgs = m_settings.getDeviceUserArgs().findUserArgs(samplingDevice->hardwareId, samplingDevice->sequence);
         if (userArgs.size() > 0) {
             deviceUI->m_deviceAPI->setHardwareUserArguments(userArgs);
         }
         // add to buddies list
         std::vector<DeviceUISet*>::iterator it = m_deviceUIs.begin();
         int nbOfBuddies = 0;
         for (; it != m_deviceUIs.end(); ++it)
         {
             if (*it != deviceUI) // do not add to itself
             {
                 if ((*it)->m_deviceSourceEngine) // it is a source device
                 {
                     if ((deviceUI->m_deviceAPI->getHardwareId() == (*it)->m_deviceAPI->getHardwareId()) &&
                         (deviceUI->m_deviceAPI->getSamplingDeviceSerial() == (*it)->m_deviceAPI->getSamplingDeviceSerial()))
                     {
                         (*it)->m_deviceAPI->addSourceBuddy(deviceUI->m_deviceAPI);
                         nbOfBuddies++;
                     }
                 }
                 if ((*it)->m_deviceSinkEngine) // it is a sink device
                 {
                     if ((deviceUI->m_deviceAPI->getHardwareId() == (*it)->m_deviceAPI->getHardwareId()) &&
                         (deviceUI->m_deviceAPI->getSamplingDeviceSerial() == (*it)->m_deviceAPI->getSamplingDeviceSerial()))
                     {
                         (*it)->m_deviceAPI->addSourceBuddy(deviceUI->m_deviceAPI);
                         nbOfBuddies++;
                     }
                 }
             }
         }
         if (nbOfBuddies == 0) {
             deviceUI->m_deviceAPI->setBuddyLeader(true);
         }
         // constructs new GUI and input object
         DeviceSampleSource *source = deviceUI->m_deviceAPI->getPluginInterface()->createSampleSourcePluginInstance(
                 deviceUI->m_deviceAPI->getSamplingDeviceId(), deviceUI->m_deviceAPI);
         deviceUI->m_deviceAPI->setSampleSource(source);
         QWidget *gui;
         PluginInstanceGUI *pluginUI = deviceUI->m_deviceAPI->getPluginInterface()->createSampleSourcePluginInstanceGUI(
                 deviceUI->m_deviceAPI->getSamplingDeviceId(),
                 &gui,
                 deviceUI);
         deviceUI->m_deviceAPI->getSampleSource()->setMessageQueueToGUI(pluginUI->getInputMessageQueue());
         deviceUI->m_deviceAPI->setSamplingDevicePluginInstanceGUI(pluginUI);
         setDeviceGUI(currentSourceTabIndex, gui, deviceUI->m_deviceAPI->getSamplingDeviceDisplayName());
         deviceUI->m_deviceAPI->getSampleSource()->init();
         deviceUI->m_deviceAPI->loadSamplingDeviceSettings(m_settings.getWorkingPreset()); // load new API settings
         if (currentSourceTabIndex == 0) // save as default starting device
         {
             m_settings.setSourceIndex(samplingDevice->sequence);
             m_settings.setSourceDeviceId(samplingDevice->id);
         }
     }
 }
saveCommandSettings()
void MainWindow::saveCommandSettings () private
Definition at line 795 of file mainwindow.cpp.
Referenced by on_commandsSave_clicked().
 {
 }
savePresetSettings()
void MainWindow::savePresetSettings (Preset * preset, int tabIndex) private
Definition at line 766 of file mainwindow.cpp.
References Preset::clearChannels(), Preset::getDescription(), Preset::getGroup(), DeviceUISet::m_deviceAPI, DeviceUISet::m_deviceSinkEngine, DeviceUISet::m_deviceSourceEngine, m_deviceUIs, DeviceUISet::m_spectrumGUI, DeviceUISet::saveRxChannelSettings(), DeviceAPI::saveSamplingDeviceSettings(), DeviceUISet::saveTxChannelSettings(), GLSpectrumGUI::serialize(), Preset::setLayout(), Preset::setSourcePreset(), and Preset::setSpectrumConfig().
Referenced by closeEvent(), handleMessage(), on_presetSave_clicked(), on_presetUpdate_clicked(), and on_settingsSave_clicked().
 {
     qDebug("MainWindow::savePresetSettings: preset [%s | %s]",
         qPrintable(preset->getGroup()),
         qPrintable(preset->getDescription()));
     // Save from currently selected source tab
     //int currentSourceTabIndex = ui->tabInputsView->currentIndex();
     DeviceUISet *deviceUI = m_deviceUIs[tabIndex];
     if (deviceUI->m_deviceSourceEngine) // source device
     {
         preset->setSpectrumConfig(deviceUI->m_spectrumGUI->serialize());
         preset->clearChannels();
         deviceUI->saveRxChannelSettings(preset);
         deviceUI->m_deviceAPI->saveSamplingDeviceSettings(preset);
     }
     else if (deviceUI->m_deviceSinkEngine) // sink device
     {
         preset->setSpectrumConfig(deviceUI->m_spectrumGUI->serialize());
         preset->clearChannels();
         preset->setSourcePreset(false);
         deviceUI->saveTxChannelSettings(preset);
         deviceUI->m_deviceAPI->saveSamplingDeviceSettings(preset);
     }
     preset->setLayout(saveState());
 }
setDeviceGUI()
void MainWindow::setDeviceGUI (int deviceTabIndex, QWidget * gui, const QString & deviceDisplayName, int deviceType = 0)
Definition at line 676 of file mainwindow.cpp.
References i, m_deviceWidgetTabs, and ui.
Referenced by addMIMODevice(), addSinkDevice(), addSourceDevice(), sampleMIMOChanged(), sampleSinkChanged(), and sampleSourceChanged().
 {
     char tabNameCStr[16];
     if (deviceType == 0) {
         sprintf(tabNameCStr, "R%d", deviceTabIndex);
     } else if (deviceType == 1) {
         sprintf(tabNameCStr, "T%d", deviceTabIndex);
     } else if (deviceType == 2) {
         sprintf(tabNameCStr, "M%d", deviceTabIndex);
     }
     qDebug("MainWindow::setDeviceGUI: insert device type %d tab at %d", deviceType, deviceTabIndex);
     if (deviceTabIndex < m_deviceWidgetTabs.size()) {
         m_deviceWidgetTabs[deviceTabIndex] = {gui, deviceDisplayName, QString(tabNameCStr)};
     } else {
         m_deviceWidgetTabs.append({gui, deviceDisplayName, QString(tabNameCStr)});
     }
     ui->tabInputsView->clear();
     for (int i = 0; i < m_deviceWidgetTabs.size(); i++)
     {
         qDebug("MainWindow::setDeviceGUI: adding tab for %s", m_deviceWidgetTabs[i].displayName.toStdString().c_str());
         ui->tabInputsView->addTab(m_deviceWidgetTabs[i].gui, m_deviceWidgetTabs[i].tabName);
         ui->tabInputsView->setTabToolTip(i, m_deviceWidgetTabs[i].displayName);
     }
     ui->tabInputsView->setCurrentIndex(deviceTabIndex);
 }
setLoggingOptions()
void MainWindow::setLoggingOptions () private
Definition at line 1990 of file mainwindow.cpp.
References arg(), qtwebapp::LoggerWithFile::createOrSetFileLogger(), qtwebapp::FileLoggerSettings::fileName, MainSettings::getConsoleMinLogLevel(), qtwebapp::LoggerWithFile::getFileLoggerSettings(), MainSettings::getFileMinLogLevel(), MainSettings::getLogFileName(), MainSettings::getUseLogFile(), qtwebapp::LoggerWithFile::hasFileLogger(), qtwebapp::LoggerWithFile::logToFile(), m_logger, m_settings, SDR_RX_SAMP_SZ, SDR_TX_SAMP_SZ, qtwebapp::LoggerWithFile::setConsoleMinMessageLevel(), qtwebapp::LoggerWithFile::setFileMinMessageLevel(), and qtwebapp::LoggerWithFile::setUseFileLogger().
Referenced by WebAPIAdapterGUI::instanceLoggingPut(), loadSettings(), and on_action_Logging_triggered().
 {
     m_logger->setConsoleMinMessageLevel(m_settings.getConsoleMinLogLevel());
     if (m_settings.getUseLogFile())
     {
         qtwebapp::FileLoggerSettings fileLoggerSettings; // default values
         if (m_logger->hasFileLogger()) {
             fileLoggerSettings = m_logger->getFileLoggerSettings(); // values from file logger if it exists
         }
         fileLoggerSettings.fileName = m_settings.getLogFileName(); // put new values
         m_logger->createOrSetFileLogger(fileLoggerSettings, 2000); // create file logger if it does not exist and apply settings in any case
     }
     if (m_logger->hasFileLogger()) {
         m_logger->setFileMinMessageLevel(m_settings.getFileMinLogLevel());
     }
     m_logger->setUseFileLogger(m_settings.getUseLogFile());
     if (m_settings.getUseLogFile())
     {
 #if QT_VERSION >= 0x050400
         QString appInfoStr(tr("%1 %2 Qt %3 %4b %5 %6 DSP Rx:%7b Tx:%8b PID %9")
                 .arg(qApp->applicationName())
                 .arg(qApp->applicationVersion())
                 .arg(QT_VERSION_STR)
                 .arg(QT_POINTER_SIZE*8)
                 .arg(QSysInfo::currentCpuArchitecture())
                 .arg(QSysInfo::prettyProductName())
                 .arg(SDR_RX_SAMP_SZ)
                 .arg(SDR_TX_SAMP_SZ)
                 .arg(qApp->applicationPid()));
 #else
         QString appInfoStr(tr("%1 %2 Qt %3 %4b DSP Rx:%5b Tx:%6b PID %7")
                 .arg(qApp->applicationName())
                 .arg(qApp->applicationVersion())
                 .arg(QT_VERSION_STR)
                 .arg(QT_POINTER_SIZE*8)
                 .arg(SDR_RX_SAMP_SZ)
                 .arg(SDR_TX_SAMP_SZ)
                 .arg(qApp->applicationPid()));
  #endif
         m_logger->logToFile(QtInfoMsg, appInfoStr);
     }
 }
tabInputViewIndexChanged
void MainWindow::tabInputViewIndexChanged () private slot
Definition at line 1966 of file mainwindow.cpp.
References m_deviceUIs, DeviceUISet::m_mainWindowState, m_masterTabIndex, and ui.
Referenced by MainWindow().
 {
     int inputViewIndex = ui->tabInputsView->currentIndex();
     if ((inputViewIndex >= 0) && (m_masterTabIndex >= 0) && (inputViewIndex != m_masterTabIndex))
     {
         DeviceUISet *deviceUI = m_deviceUIs[inputViewIndex];
         DeviceUISet *lastdeviceUI = m_deviceUIs[m_masterTabIndex];
         lastdeviceUI->m_mainWindowState = saveState();
         restoreState(deviceUI->m_mainWindowState);
         m_masterTabIndex = inputViewIndex;
     }
     ui->tabSpectra->setCurrentIndex(inputViewIndex);
     ui->tabChannels->setCurrentIndex(inputViewIndex);
     ui->tabInputsSelect->setCurrentIndex(inputViewIndex);
     ui->tabSpectraGUI->setCurrentIndex(inputViewIndex);
 }
updatePresetControls()
void MainWindow::updatePresetControls () private
Definition at line 830 of file mainwindow.cpp.
References ui.
Referenced by addPresetToTree(), MainWindow(), on_presetDelete_clicked(), on_presetLoad_clicked(), and on_presetTree_currentItemChanged().
 {
     ui->presetTree->resizeColumnToContents(0);
     if(ui->presetTree->currentItem() != 0)
     {
         ui->presetDelete->setEnabled(true);
         ui->presetLoad->setEnabled(true);
     }
     else
     {
         ui->presetDelete->setEnabled(false);
         ui->presetLoad->setEnabled(false);
     }
 }
updateStatus
void MainWindow::updateStatus () private slot
Definition at line 1985 of file mainwindow.cpp.
References m_dateTimeWidget.
Referenced by MainWindow().
 {
     m_dateTimeWidget->setText(QDateTime::currentDateTime().toString("yyyy-MM-dd HH:mm:ss t"));
 }
Friends And Related Function Documentation
WebAPIAdapterGUI
friend class WebAPIAdapterGUI friend
Definition at line 87 of file mainwindow.h.
Referenced by MainWindow().
Member Data Documentation
m_apiAdapter
WebAPIAdapterGUI* MainWindow::m_apiAdapter private
Definition at line 332 of file mainwindow.h.
Referenced by MainWindow(), and ~MainWindow().
m_apiHost
QString MainWindow::m_apiHost private
Definition at line 333 of file mainwindow.h.
Referenced by MainWindow(), and on_action_About_triggered().
m_apiPort
int MainWindow::m_apiPort private
Definition at line 334 of file mainwindow.h.
Referenced by MainWindow(), and on_action_About_triggered().
m_apiServer
WebAPIServer* MainWindow::m_apiServer private
Definition at line 331 of file mainwindow.h.
Referenced by commandKeyPressed(), MainWindow(), on_commandRun_clicked(), and ~MainWindow().
m_centerFrequency
quint64 MainWindow::m_centerFrequency private
Definition at line 325 of file mainwindow.h.
m_commandKeyReceiver
CommandKeyReceiver* MainWindow::m_commandKeyReceiver private
Definition at line 336 of file mainwindow.h.
Referenced by commandKeysConnect(), commandKeysDisconnect(), MainWindow(), and ~MainWindow().
m_dateTimeWidget
QLabel* MainWindow::m_dateTimeWidget private
Definition at line 319 of file mainwindow.h.
Referenced by createStatusBar(), updateStatus(), and ~MainWindow().
m_deviceUIs
std::vector<DeviceUISet*> MainWindow::m_deviceUIs private
Definition at line 308 of file mainwindow.h.
Referenced by addChannelRollup(), addMIMODevice(), addSinkDevice(), addSourceDevice(), channelAddClicked(), closeEvent(), deleteChannel(), WebAPIAdapterGUI::devicesetChannelDelete(), WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterGUI::devicesetChannelReportGet(), WebAPIAdapterGUI::devicesetChannelSettingsGet(), WebAPIAdapterGUI::devicesetChannelSettingsPutPatch(), WebAPIAdapterGUI::devicesetChannelsReportGet(), WebAPIAdapterGUI::devicesetDevicePut(), WebAPIAdapterGUI::devicesetDeviceReportGet(), WebAPIAdapterGUI::devicesetDeviceRunDelete(), WebAPIAdapterGUI::devicesetDeviceRunGet(), WebAPIAdapterGUI::devicesetDeviceRunPost(), WebAPIAdapterGUI::devicesetDeviceSettingsGet(), WebAPIAdapterGUI::devicesetDeviceSettingsPutPatch(), WebAPIAdapterGUI::devicesetFocusPatch(), WebAPIAdapterGUI::devicesetGet(), WebAPIAdapterGUI::getDeviceSetList(), handleMessage(), WebAPIAdapterGUI::instanceDeviceSetDelete(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), loadPresetSettings(), MainWindow(), on_action_removeLastDevice_triggered(), removeLastDevice(), sampleMIMOChanged(), sampleSinkChanged(), sampleSourceChanged(), savePresetSettings(), and tabInputViewIndexChanged().
m_deviceWidgetTabs
QList<DeviceWidgetTabData> MainWindow::m_deviceWidgetTabs private
Definition at line 309 of file mainwindow.h.
Referenced by removeLastDevice(), and setDeviceGUI().
m_dspEngine
DSPEngine* MainWindow::m_dspEngine private
Definition at line 312 of file mainwindow.h.
Referenced by addMIMODevice(), addSinkDevice(), addSourceDevice(), WebAPIAdapterGUI::instanceAMBEDevicesDelete(), WebAPIAdapterGUI::instanceAMBEDevicesGet(), WebAPIAdapterGUI::instanceAMBEDevicesPatch(), WebAPIAdapterGUI::instanceAMBEDevicesPut(), WebAPIAdapterGUI::instanceAMBESerialGet(), WebAPIAdapterGUI::instanceAudioGet(), WebAPIAdapterGUI::instanceAudioInputCleanupPatch(), WebAPIAdapterGUI::instanceAudioInputDelete(), WebAPIAdapterGUI::instanceAudioInputPatch(), WebAPIAdapterGUI::instanceAudioOutputCleanupPatch(), WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterGUI::instanceAudioOutputPatch(), WebAPIAdapterGUI::instanceDVSerialGet(), WebAPIAdapterGUI::instanceDVSerialPatch(), MainWindow(), on_action_addMIMODevice_triggered(), on_action_AMBE_triggered(), on_action_Audio_triggered(), and removeLastDevice().
m_inputGUI
QWidget* MainWindow::m_inputGUI private
Definition at line 322 of file mainwindow.h.
m_inputMessageQueue
MessageQueue MainWindow::m_inputMessageQueue private
Definition at line 306 of file mainwindow.h.
Referenced by WebAPIAdapterGUI::devicesetChannelDelete(), WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterGUI::devicesetDevicePut(), WebAPIAdapterGUI::devicesetFocusPatch(), handleMessages(), WebAPIAdapterGUI::instanceDeviceSetDelete(), WebAPIAdapterGUI::instanceDeviceSetPost(), WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), and MainWindow().
m_instance
MainWindow * MainWindow::m_instance = 0 static private
Definition at line 304 of file mainwindow.h.
Referenced by MainWindow().
m_lastEngineState
int MainWindow::m_lastEngineState private
Definition at line 317 of file mainwindow.h.
m_logger
qtwebapp::LoggerWithFile* MainWindow::m_logger private
Definition at line 328 of file mainwindow.h.
Referenced by WebAPIAdapterGUI::instanceLoggingGet(), WebAPIAdapterGUI::instanceSummary(), setLoggingOptions(), and ~MainWindow().
m_masterTabIndex
int MainWindow::m_masterTabIndex private
Definition at line 310 of file mainwindow.h.
Referenced by tabInputViewIndexChanged().
m_masterTimer
QTimer MainWindow::m_masterTimer private
Definition at line 315 of file mainwindow.h.
Referenced by addMIMODevice(), addSinkDevice(), addSourceDevice(), and MainWindow().
m_pluginManager
PluginManager* MainWindow::m_pluginManager private
Definition at line 313 of file mainwindow.h.
Referenced by addMIMODevice(), addSinkDevice(), addSourceDevice(), channelAddClicked(), WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterGUI::instanceChannels(), loadPresetSettings(), MainWindow(), on_action_Loaded_Plugins_triggered(), and ~MainWindow().
m_requestMapper
WebAPIRequestMapper* MainWindow::m_requestMapper private
Definition at line 330 of file mainwindow.h.
Referenced by MainWindow(), and ~MainWindow().
m_sampleFileName
std::string MainWindow::m_sampleFileName private
Definition at line 326 of file mainwindow.h.
m_sampleRate
int MainWindow::m_sampleRate private
Definition at line 324 of file mainwindow.h.
m_settings
MainSettings MainWindow::m_settings private
Definition at line 307 of file mainwindow.h.
Referenced by addMIMODevice(), addSinkDevice(), addSourceDevice(), closeEvent(), commandKeyPressed(), handleMessage(), WebAPIAdapterGUI::instanceConfigGet(), WebAPIAdapterGUI::instanceLocationGet(), WebAPIAdapterGUI::instanceLocationPut(), WebAPIAdapterGUI::instanceLoggingPut(), WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterGUI::instancePresetsGet(), loadSettings(), MainWindow(), on_action_About_triggered(), on_action_DeviceUserArguments_triggered(), on_action_Logging_triggered(), on_action_My_Position_triggered(), on_commandDelete_clicked(), on_commandDuplicate_clicked(), on_commandEdit_clicked(), on_commandNew_clicked(), on_commandRun_clicked(), on_commandsSave_clicked(), on_presetDelete_clicked(), on_presetEdit_clicked(), on_presetImport_clicked(), on_presetSave_clicked(), on_presetUpdate_clicked(), on_settingsSave_clicked(), sampleMIMOChanged(), sampleSinkChanged(), sampleSourceChanged(), and setLoggingOptions().
m_showSystemWidget
QLabel* MainWindow::m_showSystemWidget private
Definition at line 320 of file mainwindow.h.
Referenced by createStatusBar(), and ~MainWindow().
m_statusTimer
QTimer MainWindow::m_statusTimer private
Definition at line 316 of file mainwindow.h.
Referenced by MainWindow().
ui
Ui::MainWindow* MainWindow::ui private
Definition at line 305 of file mainwindow.h.
Referenced by addChannelRollup(), addCommandToTree(), addMIMODevice(), addPresetToTree(), addSinkDevice(), addSourceDevice(), addViewAction(), channelAddClicked(), commandKeyPressed(), WebAPIAdapterGUI::getDeviceSetList(), handleMessage(), WebAPIAdapterGUI::instanceDVSerialPatch(), loadPresetSettings(), loadSettings(), MainWindow(), on_commandDelete_clicked(), on_commandDuplicate_clicked(), on_commandEdit_clicked(), on_commandNew_clicked(), on_commandOutput_clicked(), on_commandRun_clicked(), on_presetDelete_clicked(), on_presetEdit_clicked(), on_presetExport_clicked(), on_presetImport_clicked(), on_presetLoad_clicked(), on_presetSave_clicked(), on_presetUpdate_clicked(), on_settingsSave_clicked(), removeLastDevice(), sampleMIMOChanged(), sampleSinkChanged(), sampleSourceChanged(), setDeviceGUI(), tabInputViewIndexChanged(), updatePresetControls(), and ~MainWindow().
The documentation for this class was generated from the following files:
sdrgui/mainwindow.h
sdrgui/mainwindow.cpp