SDRAngel: XTRXOutput::MsgStartStop Class Reference
XTRXOutput::MsgStartStop Class Reference
#include <xtrxoutput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 154 of file xtrxoutput.h.
Constructor & Destructor Documentation
MsgStartStop()
XTRXOutput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 167 of file xtrxoutput.h.
References XTRXOutput::destroy(), XTRXOutput::init(), XTRXOutput::start(), XTRXOutput::stop(), XTRXOutput::XTRXOutput(), and XTRXOutput::~XTRXOutput().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* XTRXOutput::MsgStartStop::create (bool startStop) inline static
Definition at line 160 of file xtrxoutput.h.
Referenced by XTRXOutputGUI::on_startStop_toggled(), and XTRXOutput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool XTRXOutput::MsgStartStop::getStartStop () const inline
Definition at line 158 of file xtrxoutput.h.
Referenced by XTRXOutputGUI::handleMessage(), and XTRXOutput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool XTRXOutput::MsgStartStop::m_startStop protected
Definition at line 165 of file xtrxoutput.h.
The documentation for this class was generated from the following file:
plugins/samplesink/xtrxoutput/xtrxoutput.h