SDRAngel: HackRFInputPlugin Class Reference
HackRFInputPlugin Class Reference
#include <hackrfinputplugin.h>
Public Member Functions
HackRFInputPlugin (QObject *parent=NULL)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "HackRF"
static const QString m_deviceTypeID = HACKRF_DEVICE_TYPE_ID
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 28 of file hackrfinputplugin.h.
Constructor & Destructor Documentation
HackRFInputPlugin()
HackRFInputPlugin::HackRFInputPlugin (QObject * parent = NULL) explicit
Definition at line 44 of file hackrfinputplugin.cpp.
                                                     :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSourcePluginInstance()
DeviceSampleSource * HackRFInputPlugin::createSampleSourcePluginInstance (const QString & sourceId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 156 of file hackrfinputplugin.cpp.
References m_deviceTypeID.
 {
     if (sourceId == m_deviceTypeID)
     {
         HackRFInput* input = new HackRFInput(deviceAPI);
         return input;
     }
     else
     {
         return 0;
     }
 }
createSampleSourcePluginInstanceGUI()
PluginInstanceGUI * HackRFInputPlugin::createSampleSourcePluginInstanceGUI (const QString & sourceId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 138 of file hackrfinputplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSources().
 {
     if(sourceId == m_deviceTypeID)
     {
         HackRFInputGui* gui = new HackRFInputGui(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSources()
PluginInterface::SamplingDevices HackRFInputPlugin::enumSampleSources () virtual
Reimplemented from PluginInterface.
Definition at line 59 of file hackrfinputplugin.cpp.
References arg(), createSampleSourcePluginInstanceGUI(), i, DeviceHackRF::instance(), m_deviceTypeID, m_hardwareID, PluginInterface::SamplingDevice::PhysicalDevice, and PluginInterface::SamplingDevice::StreamSingleRx.
 {
     DeviceHackRF::instance();
 //  hackrf_error rc = (hackrf_error) hackrf_init();
 //
 //  if (rc != HACKRF_SUCCESS)
 //  {
 //      qCritical("HackRFPlugin::SampleSourceDevices: failed to initiate HackRF library: %s", hackrf_error_name(rc));
 //  }
     SamplingDevices result;
     hackrf_device_list_t *hackrf_devices = hackrf_device_list();
     hackrf_device *hackrf_ptr;
     read_partid_serialno_t read_partid_serialno;
     int i;
     for (i=0; i < hackrf_devices->devicecount; i++)
     {
         hackrf_error rc = (hackrf_error) hackrf_device_list_open(hackrf_devices, i, &hackrf_ptr);
         if (rc == HACKRF_SUCCESS)
         {
             qDebug("HackRFPlugin::enumSampleSources: try to enumerate HackRF device #%d", i);
             rc = (hackrf_error) hackrf_board_partid_serialno_read(hackrf_ptr, &read_partid_serialno);
             if (rc != HACKRF_SUCCESS)
             {
                 qDebug("HackRFPlugin::enumSampleSources: failed to read serial no: %s", hackrf_error_name(rc));
                 hackrf_close(hackrf_ptr);
                 continue; // next
             }
             uint32_t serial_msb = read_partid_serialno.serial_no[2];
             uint32_t serial_lsb = read_partid_serialno.serial_no[3];
             QString serial_str = QString::number(serial_msb, 16) + QString::number(serial_lsb, 16);
             //uint64_t serial_num = (((uint64_t) serial_msb)<<32) + serial_lsb;
             QString displayedName(QString("HackRF[%1] %2").arg(i).arg(serial_str));
             result.append(SamplingDevice(displayedName,
                     m_hardwareID,
                     m_deviceTypeID,
                     serial_str,
                     i,
                     PluginInterface::SamplingDevice::PhysicalDevice,
                     PluginInterface::SamplingDevice::StreamSingleRx,
                     1,
                     0));
             qDebug("HackRFPlugin::enumSampleSources: enumerated HackRF device #%d", i);
             hackrf_close(hackrf_ptr);
         }
         else
         {
             qDebug("HackRFPlugin::enumSampleSources: failed to enumerate HackRF device #%d: %s", i, hackrf_error_name(rc));
         }
     }
     hackrf_device_list_free(hackrf_devices);
 //  rc = (hackrf_error) hackrf_exit();
 //  qDebug("HackRFPlugin::enumSampleSources: hackrf_exit: %s", hackrf_error_name(rc));
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & HackRFInputPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 49 of file hackrfinputplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void HackRFInputPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 54 of file hackrfinputplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSource().
 {
     pluginAPI->registerSampleSource(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString HackRFInputPlugin::m_deviceTypeID = HACKRF_DEVICE_TYPE_ID static
Definition at line 47 of file hackrfinputplugin.h.
Referenced by createSampleSourcePluginInstance(), createSampleSourcePluginInstanceGUI(), enumSampleSources(), and initPlugin().
m_hardwareID
const QString HackRFInputPlugin::m_hardwareID = "HackRF" static
Definition at line 46 of file hackrfinputplugin.h.
Referenced by enumSampleSources().
m_pluginDescriptor
const PluginDescriptor HackRFInputPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("HackRF Input"),
    QString("4.5.4"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 50 of file hackrfinputplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesource/hackrfinput/hackrfinputplugin.h
plugins/samplesource/hackrfinput/hackrfinputplugin.cpp