SDRAngel: FCDProPlusConstants Class Reference
FCDProPlusConstants Class Reference
#include <fcdproplusconst.h>
Static Public Member Functions
static int fcdproplus_rf_filter_nb_values ()
static int fcdproplus_if_filter_nb_values ()
Static Public Attributes
static const fcdproplus_rf_filter rf_filters []
static const fcdproplus_if_filter if_filters []
Detailed Description
Definition at line 52 of file fcdproplusconst.h.
Member Function Documentation
fcdproplus_if_filter_nb_values()
int FCDProPlusConstants::fcdproplus_if_filter_nb_values () static
Definition at line 40 of file fcdproplusconst.cpp.
References if_filters.
Referenced by FCDProPlusGui::FCDProPlusGui(), and FCDProPlusInput::set_if_filter().
 {
     return sizeof(if_filters) / sizeof(fcdproplus_if_filter);
 }
fcdproplus_rf_filter_nb_values()
int FCDProPlusConstants::fcdproplus_rf_filter_nb_values () static
Definition at line 24 of file fcdproplusconst.cpp.
References FCDPROPLUS_TIF_1536KHZ, FCDPROPLUS_TIF_200KHZ, FCDPROPLUS_TIF_300KHZ, FCDPROPLUS_TIF_5MHZ, FCDPROPLUS_TIF_600KHZ, FCDPROPLUS_TIF_6MHZ, FCDPROPLUS_TIF_7MHZ, FCDPROPLUS_TIF_8MHZ, if_filters, and rf_filters.
Referenced by FCDProPlusGui::FCDProPlusGui(), and FCDProPlusInput::set_rf_filter().
 {
     return sizeof(rf_filters) / sizeof(fcdproplus_rf_filter);
 }
Member Data Documentation
if_filters
const fcdproplus_if_filter FCDProPlusConstants::if_filters static
Initial value:
= {
        {FCDPROPLUS_TIF_200KHZ, "200k"},
        {FCDPROPLUS_TIF_300KHZ, "300k"},
        {FCDPROPLUS_TIF_600KHZ, "600k"},
        {FCDPROPLUS_TIF_1536KHZ, "1.5M"},
        {FCDPROPLUS_TIF_5MHZ, "5M"},
        {FCDPROPLUS_TIF_6MHZ, "6M"},
        {FCDPROPLUS_TIF_7MHZ, "7M"},
        {FCDPROPLUS_TIF_8MHZ, "8M"}
}
Definition at line 56 of file fcdproplusconst.h.
Referenced by fcdproplus_if_filter_nb_values(), fcdproplus_rf_filter_nb_values(), FCDProPlusGui::FCDProPlusGui(), and FCDProPlusInput::set_if_filter().
rf_filters
const fcdproplus_rf_filter FCDProPlusConstants::rf_filters static
Initial value:
= {
        {FCDPROPLUS_TRF_0_4, "0-4M"},
        {FCDPROPLUS_TRF_4_8, "4-8M"},
        {FCDPROPLUS_TRF_8_16, "8-16M"},
        {FCDPROPLUS_TRF_16_32, "16-32M"},
        {FCDPROPLUS_TRF_32_75, "32-75M"},
        {FCDPROPLUS_TRF_75_125, "75-125M"},
        {FCDPROPLUS_TRF_125_250, "125-250M"},
        {FCDPROPLUS_TRF_145, "145M"},
        {FCDPROPLUS_TRF_410_875, "410-875M"},
        {FCDPROPLUS_TRF_435, "435M"},
        {FCDPROPLUS_TRF_875_2000, "875M-2G"}
}
Definition at line 55 of file fcdproplusconst.h.
Referenced by fcdproplus_rf_filter_nb_values(), FCDProPlusGui::FCDProPlusGui(), and FCDProPlusInput::set_rf_filter().
The documentation for this class was generated from the following files:
fcdlib/fcdproplusconst.h
fcdlib/fcdproplusconst.cpp