SDRAngel: SWGSDRangel::SWGRtlSdrReport Class Reference
SWGSDRangel::SWGRtlSdrReport Class Reference
#include <SWGRtlSdrReport.h>
Public Member Functions
SWGRtlSdrReport ()
SWGRtlSdrReport (QString *json)
virtual ~SWGRtlSdrReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGRtlSdrReport * fromJson (QString &jsonString) override
QList< SWGGain * > * getGains ()
void setGains (QList< SWGGain *> *gains)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QList< SWGGain * > * gains
bool m_gains_isSet
Detailed Description
Definition at line 33 of file SWGRtlSdrReport.h.
Constructor & Destructor Documentation
SWGRtlSdrReport() [1/2]
SWGSDRangel::SWGRtlSdrReport::SWGRtlSdrReport ()
Definition at line 30 of file SWGRtlSdrReport.cpp.
References gains, and m_gains_isSet.
{
     gains = nullptr;
     m_gains_isSet = false;
 }
SWGRtlSdrReport() [2/2]
SWGSDRangel::SWGRtlSdrReport::SWGRtlSdrReport (QString * json)
Definition at line 25 of file SWGRtlSdrReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGRtlSdrReport()
SWGSDRangel::SWGRtlSdrReport::~SWGRtlSdrReport () virtual
Definition at line 35 of file SWGRtlSdrReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGRtlSdrReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 72 of file SWGRtlSdrReport.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGRtlSdrReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 83 of file SWGRtlSdrReport.cpp.
References gains, and SWGSDRangel::toJsonArray().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(gains->size() > 0){
         toJsonArray((QList<void*>*)gains, obj, "gains", "SWGGain");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGRtlSdrReport::cleanup ()
Definition at line 46 of file SWGRtlSdrReport.cpp.
References gains.
Referenced by ~SWGRtlSdrReport().
{
     if(gains != nullptr) {
         auto arr = gains;
         for(auto o: *arr) {
             delete o;
         }
         delete gains;
     }
 }
fromJson()
SWGRtlSdrReport * SWGSDRangel::SWGRtlSdrReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 57 of file SWGRtlSdrReport.cpp.
References fromJsonObject().
Referenced by SWGRtlSdrReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGRtlSdrReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 66 of file SWGRtlSdrReport.cpp.
References gains, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&gains, pJson["gains"], "QList", "SWGGain");
 }
getGains()
QList< SWGGain * > * SWGSDRangel::SWGRtlSdrReport::getGains ()
Definition at line 93 of file SWGRtlSdrReport.cpp.
References gains.
Referenced by RTLSDRInput::webapiFormatDeviceReport().
{
     return gains;
 }
init()
void SWGSDRangel::SWGRtlSdrReport::init ()
Definition at line 40 of file SWGRtlSdrReport.cpp.
References gains, and m_gains_isSet.
Referenced by SWGRtlSdrReport(), and RTLSDRInput::webapiReportGet().
                       {
     gains = new QList<SWGGain*>();
     m_gains_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGRtlSdrReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 104 of file SWGRtlSdrReport.cpp.
References gains.
Referenced by SWGSDRangel::SWGDeviceReport::asJsonObject(), and SWGSDRangel::SWGDeviceReport::isSet().
                       {
     bool isObjectUpdated = false;
     do{
         if(gains->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setGains()
void SWGSDRangel::SWGRtlSdrReport::setGains (QList< SWGGain *> * gains)
Definition at line 97 of file SWGRtlSdrReport.cpp.
References gains, and m_gains_isSet.
Referenced by RTLSDRInput::webapiFormatDeviceReport().
{
     this->gains = gains;
     this->m_gains_isSet = true;
 }
Member Data Documentation
gains
QList<SWGGain*>* SWGSDRangel::SWGRtlSdrReport::gains private
Definition at line 53 of file SWGRtlSdrReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getGains(), init(), isSet(), setGains(), and SWGRtlSdrReport().
m_gains_isSet
bool SWGSDRangel::SWGRtlSdrReport::m_gains_isSet private
Definition at line 54 of file SWGRtlSdrReport.h.
Referenced by init(), setGains(), and SWGRtlSdrReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGRtlSdrReport.h
swagger/sdrangel/code/qt5/client/SWGRtlSdrReport.cpp