SDRAngel: BFMDemod::MsgConfigureBFMDemod Class Reference
BFMDemod::MsgConfigureBFMDemod Class Reference
#include <bfmdemod.h>
Public Member Functions
const BFMDemodSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureBFMDemod * create (const BFMDemodSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureBFMDemod (const BFMDemodSettings &settings, bool force)
Private Attributes
BFMDemodSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 58 of file bfmdemod.h.
Constructor & Destructor Documentation
MsgConfigureBFMDemod()
BFMDemod::MsgConfigureBFMDemod::MsgConfigureBFMDemod (const BFMDemodSettings & settings, bool force) inline private
Definition at line 74 of file bfmdemod.h.
                                                                            :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureBFMDemod* BFMDemod::MsgConfigureBFMDemod::create (const BFMDemodSettings & settings, bool force) inline static
Definition at line 65 of file bfmdemod.h.
Referenced by BFMDemodGUI::applySettings(), BFMDemod::deserialize(), and BFMDemod::webapiSettingsPutPatch().
         {
             return new MsgConfigureBFMDemod(settings, force);
         }
getForce()
bool BFMDemod::MsgConfigureBFMDemod::getForce () const inline
Definition at line 63 of file bfmdemod.h.
Referenced by BFMDemod::handleMessage().
 { return m_force; }
getSettings()
const BFMDemodSettings& BFMDemod::MsgConfigureBFMDemod::getSettings () const inline
Definition at line 62 of file bfmdemod.h.
Referenced by BFMDemodGUI::handleMessage(), and BFMDemod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool BFMDemod::MsgConfigureBFMDemod::m_force private
Definition at line 72 of file bfmdemod.h.
m_settings
BFMDemodSettings BFMDemod::MsgConfigureBFMDemod::m_settings private
Definition at line 71 of file bfmdemod.h.
The documentation for this class was generated from the following file:
plugins/channelrx/demodbfm/bfmdemod.h