SDRAngel: GLSpectrumGUI Class Reference
GLSpectrumGUI Class Reference
#include <glspectrumgui.h>
Public Types
enum AveragingMode { AvgModeNone, AvgModeMoving, AvgModeFixed, AvgModeMax }
Public Member Functions
GLSpectrumGUI (QWidget *parent=NULL)
~GLSpectrumGUI ()
void setBuddies (MessageQueue *messageQueue, SpectrumVis *spectrumVis, GLSpectrum *glSpectrum)
void resetToDefaults ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Private Slots
void on_fftWindow_currentIndexChanged (int index)
void on_fftSize_currentIndexChanged (int index)
void on_refLevel_currentIndexChanged (int index)
void on_levelRange_currentIndexChanged (int index)
void on_decay_valueChanged (int index)
void on_decayDivisor_valueChanged (int index)
void on_stroke_valueChanged (int index)
void on_gridIntensity_valueChanged (int index)
void on_traceIntensity_valueChanged (int index)
void on_averagingMode_currentIndexChanged (int index)
void on_averaging_currentIndexChanged (int index)
void on_linscale_toggled (bool checked)
void on_waterfall_toggled (bool checked)
void on_histogram_toggled (bool checked)
void on_maxHold_toggled (bool checked)
void on_current_toggled (bool checked)
void on_invert_toggled (bool checked)
void on_grid_toggled (bool checked)
void on_clearSpectrum_clicked (bool checked)
void handleInputMessages ()
Private Member Functions
void applySettings ()
int getAveragingIndex (int averaging) const
int getAveragingValue (int averagingIndex) const
void setAveragingCombo ()
void setNumberStr (int n, QString &s)
void setNumberStr (float v, int decimalPlaces, QString &s)
void setAveragingToolitp ()
bool handleMessage (const Message &message)
Private Attributes
Ui::GLSpectrumGUI * ui
MessageQueue * m_messageQueueToVis
SpectrumVis * m_spectrumVis
GLSpectrum * m_glSpectrum
MessageQueue m_messageQueue
qint32 m_fftSize
qint32 m_fftOverlap
qint32 m_fftWindow
Real m_refLevel
Real m_powerRange
int m_decay
int m_decayDivisor
int m_histogramStroke
int m_displayGridIntensity
int m_displayTraceIntensity
bool m_displayWaterfall
bool m_invertedWaterfall
bool m_displayMaxHold
bool m_displayCurrent
bool m_displayHistogram
bool m_displayGrid
bool m_invert
AveragingMode m_averagingMode
int m_averagingIndex
int m_averagingMaxScale
Max power of 10 multiplier to 2,5,10 base ex: 2 -> 2,5,10,20,50,100,200,500,1000.
unsigned int m_averagingNb
bool m_linear
linear else logarithmic scale
Detailed Description
Definition at line 17 of file glspectrumgui.h.
Member Enumeration Documentation
AveragingMode
enum GLSpectrumGUI::AveragingMode
Enumerator
AvgModeNone
AvgModeMoving
AvgModeFixed
AvgModeMax
Definition at line 21 of file glspectrumgui.h.
     {
         AvgModeNone,
         AvgModeMoving,
         AvgModeFixed,
         AvgModeMax
     };
Constructor & Destructor Documentation
GLSpectrumGUI()
GLSpectrumGUI::GLSpectrumGUI (QWidget * parent = NULL) explicit
Definition at line 8 of file glspectrumgui.cpp.
References arg(), handleInputMessages(), m_messageQueue, on_linscale_toggled(), setAveragingCombo(), and ui.
                                             :
     QWidget(parent),
     ui(new Ui::GLSpectrumGUI),
     m_messageQueueToVis(0),
     m_spectrumVis(0),
     m_glSpectrum(0),
     m_fftSize(1024),
     m_fftOverlap(0),
     m_fftWindow(FFTWindow::Hamming),
     m_refLevel(0),
     m_powerRange(100),
     m_decay(1),
     m_decayDivisor(1),
     m_histogramStroke(30),
     m_displayGridIntensity(5),
     m_displayTraceIntensity(50),
     m_displayWaterfall(true),
     m_invertedWaterfall(false),
     m_displayMaxHold(false),
     m_displayCurrent(false),
     m_displayHistogram(false),
     m_displayGrid(false),
     m_invert(true),
     m_averagingMode(AvgModeNone),
     m_averagingIndex(0),
     m_averagingMaxScale(5),
     m_averagingNb(0)
 {
     ui->setupUi(this);
     on_linscale_toggled(false);
     ui->refLevel->clear();
     for(int ref = 0; ref >= -110; ref -= 5)
         ui->refLevel->addItem(QString("%1").arg(ref));
     ui->levelRange->clear();
     for(int range = 100; range >= 5; range -= 5)
         ui->levelRange->addItem(QString("%1").arg(range));
     setAveragingCombo();
     connect(&m_messageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
 }
~GLSpectrumGUI()
GLSpectrumGUI::~GLSpectrumGUI ()
Definition at line 48 of file glspectrumgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
applySettings()
void GLSpectrumGUI::applySettings () private
Definition at line 159 of file glspectrumgui.cpp.
References arg(), SpectrumVis::configure(), i, m_averagingIndex, m_averagingMode, m_averagingNb, m_decay, m_decayDivisor, m_displayCurrent, m_displayGrid, m_displayGridIntensity, m_displayHistogram, m_displayMaxHold, m_displayTraceIntensity, m_displayWaterfall, m_fftOverlap, m_fftSize, m_fftWindow, m_glSpectrum, m_histogramStroke, m_invert, m_invertedWaterfall, m_linear, m_messageQueueToVis, m_powerRange, m_refLevel, m_spectrumVis, setAveragingToolitp(), GLSpectrum::setDecay(), GLSpectrum::setDecayDivisor(), GLSpectrum::setDisplayCurrent(), GLSpectrum::setDisplayGrid(), GLSpectrum::setDisplayGridIntensity(), GLSpectrum::setDisplayHistogram(), GLSpectrum::setDisplayMaxHold(), GLSpectrum::setDisplayWaterfall(), GLSpectrum::setHistoStroke(), GLSpectrum::setInvertedWaterfall(), GLSpectrum::setLinear(), and ui.
Referenced by deserialize(), on_decayDivisor_valueChanged(), on_stroke_valueChanged(), resetToDefaults(), and setBuddies().
 {
     ui->fftWindow->setCurrentIndex(m_fftWindow);
     for(int i = 0; i < 6; i++) {
         if(m_fftSize == (1 << (i + 7))) {
             ui->fftSize->setCurrentIndex(i);
             break;
         }
     }
     ui->refLevel->setCurrentIndex(-m_refLevel / 5);
     ui->levelRange->setCurrentIndex((100 - m_powerRange) / 5);
     ui->averaging->setCurrentIndex(m_averagingIndex);
     ui->averagingMode->setCurrentIndex((int) m_averagingMode);
     ui->linscale->setChecked(m_linear);
     ui->decay->setSliderPosition(m_decay);
     ui->decayDivisor->setSliderPosition(m_decayDivisor);
     ui->stroke->setSliderPosition(m_histogramStroke);
     ui->waterfall->setChecked(m_displayWaterfall);
     ui->maxHold->setChecked(m_displayMaxHold);
     ui->current->setChecked(m_displayCurrent);
     ui->histogram->setChecked(m_displayHistogram);
     ui->invert->setChecked(m_invert);
     ui->grid->setChecked(m_displayGrid);
     ui->gridIntensity->setSliderPosition(m_displayGridIntensity);
     ui->decay->setToolTip(QString("Decay: %1").arg(m_decay));
     ui->decayDivisor->setToolTip(QString("Decay divisor: %1").arg(m_decayDivisor));
     ui->stroke->setToolTip(QString("Stroke: %1").arg(m_histogramStroke));
     ui->gridIntensity->setToolTip(QString("Grid intensity: %1").arg(m_displayGridIntensity));
     ui->traceIntensity->setToolTip(QString("Trace intensity: %1").arg(m_displayTraceIntensity));
     m_glSpectrum->setDisplayWaterfall(m_displayWaterfall);
     m_glSpectrum->setInvertedWaterfall(m_invertedWaterfall);
     m_glSpectrum->setDisplayMaxHold(m_displayMaxHold);
     m_glSpectrum->setDisplayCurrent(m_displayCurrent);
     m_glSpectrum->setDisplayHistogram(m_displayHistogram);
     m_glSpectrum->setDecay(m_decay);
     m_glSpectrum->setDecayDivisor(m_decayDivisor);
     m_glSpectrum->setHistoStroke(m_histogramStroke);
     m_glSpectrum->setInvertedWaterfall(m_invert);
     m_glSpectrum->setDisplayGrid(m_displayGrid);
     m_glSpectrum->setDisplayGridIntensity(m_displayGridIntensity);
     m_glSpectrum->setLinear(m_linear);
     if (m_spectrumVis) {
         m_spectrumVis->configure(m_messageQueueToVis,
                 m_fftSize,
                 m_fftOverlap,
                 m_averagingNb,
                 m_averagingMode,
                 (FFTWindow::Function)m_fftWindow,
                 m_linear);
     }
     setAveragingToolitp();
 }
deserialize()
bool GLSpectrumGUI::deserialize (const QByteArray & data) virtual
Implements Serializable.
Definition at line 112 of file glspectrumgui.cpp.
References applySettings(), AvgModeMax, getAveragingIndex(), getAveragingValue(), SimpleDeserializer::getVersion(), FFTWindow::Hamming, SimpleDeserializer::isValid(), m_averagingIndex, m_averagingMode, m_averagingNb, m_decay, m_decayDivisor, m_displayCurrent, m_displayGrid, m_displayGridIntensity, m_displayHistogram, m_displayMaxHold, m_displayTraceIntensity, m_displayWaterfall, m_fftOverlap, m_fftSize, m_fftWindow, m_glSpectrum, m_histogramStroke, m_invert, m_invertedWaterfall, m_linear, m_powerRange, m_refLevel, SimpleDeserializer::readBool(), SimpleDeserializer::readReal(), SimpleDeserializer::readS32(), resetToDefaults(), and GLSpectrum::setWaterfallShare().
Referenced by MainWindow::loadPresetSettings().
 {
     SimpleDeserializer d(data);
     if(!d.isValid()) {
         resetToDefaults();
         return false;
     }
     int tmp;
     if(d.getVersion() == 1) {
         d.readS32(1, &m_fftSize, 1024);
         d.readS32(2, &m_fftOverlap, 0);
         d.readS32(3, &m_fftWindow, FFTWindow::Hamming);
         d.readReal(4, &m_refLevel, 0);
         d.readReal(5, &m_powerRange, 100);
         d.readBool(6, &m_displayWaterfall, true);
         d.readBool(7, &m_invertedWaterfall, false);
         d.readBool(8, &m_displayMaxHold, false);
         d.readBool(9, &m_displayHistogram, false);
         d.readS32(10, &m_decay, 1);
         d.readBool(11, &m_displayGrid, false);
         d.readBool(12, &m_invert, true);
         d.readS32(13, &m_displayGridIntensity, 5);
         d.readS32(14, &m_decayDivisor, 1);
         d.readS32(15, &m_histogramStroke, 30);
         d.readBool(16, &m_displayCurrent, false);
         d.readS32(17, &m_displayTraceIntensity, 50);
         Real waterfallShare;
         d.readReal(18, &waterfallShare, 0.66);
         d.readS32(19, &tmp, 0);
         m_averagingMode = tmp < 0 ? AvgModeNone : tmp > 3 ? AvgModeMax : (AveragingMode) tmp;
         d.readS32(20, &tmp, 0);
         m_averagingIndex = getAveragingIndex(tmp);
         m_averagingNb = getAveragingValue(m_averagingIndex);
         d.readBool(21, &m_linear, false);
         m_glSpectrum->setWaterfallShare(waterfallShare);
         applySettings();
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
getAveragingIndex()
int GLSpectrumGUI::getAveragingIndex (int averaging) const private
Definition at line 462 of file glspectrumgui.cpp.
References i, and m_averagingMaxScale.
Referenced by deserialize().
 {
     if (averagingValue <= 1) {
         return 0;
     }
     int v = averagingValue;
     int j = 0;
     for (int i = 0; i <= m_averagingMaxScale; i++)
     {
         if (v < 20)
         {
             if (v < 2) {
                 j = 0;
             } else if (v < 5) {
                 j = 1;
             } else if (v < 10) {
                 j = 2;
             } else {
                 j = 3;
             }
             return 3*i + j;
         }
         v /= 10;
     }
     return 3*m_averagingMaxScale + 3;
 }
getAveragingValue()
int GLSpectrumGUI::getAveragingValue (int averagingIndex) const private
Definition at line 494 of file glspectrumgui.cpp.
References m_averagingMaxScale.
Referenced by deserialize(), on_averaging_currentIndexChanged(), and serialize().
 {
     if (averagingIndex <= 0) {
         return 1;
     }
     int v = averagingIndex - 1;
     int m = pow(10.0, v/3 > m_averagingMaxScale ? m_averagingMaxScale : v/3);
     int x = 1;
     if (v % 3 == 0) {
         x = 2;
     } else if (v % 3 == 1) {
         x = 5;
     } else if (v % 3 == 2) {
         x = 10;
     }
     return x * m;
 }
handleInputMessages
void GLSpectrumGUI::handleInputMessages () private slot
Definition at line 599 of file glspectrumgui.cpp.
References Message::getIdentifier(), handleMessage(), m_messageQueue, and MessageQueue::pop().
Referenced by GLSpectrumGUI().
 {
     Message* message;
     while ((message = m_messageQueue.pop()) != 0)
     {
         qDebug("GLSpectrumGUI::handleInputMessages: message: %s", message->getIdentifier());
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
bool GLSpectrumGUI::handleMessage (const Message & message) private
Definition at line 588 of file glspectrumgui.cpp.
References Message::match(), and setAveragingToolitp().
Referenced by handleInputMessages().
 {
     if (GLSpectrum::MsgReportSampleRate::match(message))
     {
         setAveragingToolitp();
         return true;
     }
     return false;
 }
on_averaging_currentIndexChanged
void GLSpectrumGUI::on_averaging_currentIndexChanged (int index) private slot
Definition at line 281 of file glspectrumgui.cpp.
References AvgModeFixed, AvgModeMax, SpectrumVis::configure(), getAveragingValue(), m_averagingIndex, m_averagingMode, m_averagingNb, m_fftOverlap, m_fftSize, m_fftWindow, m_glSpectrum, m_linear, m_messageQueueToVis, m_spectrumVis, setAveragingToolitp(), and GLSpectrum::setTimingRate().
 {
     m_averagingIndex = index;
     m_averagingNb = getAveragingValue(index);
     if(m_spectrumVis != 0) {
         m_spectrumVis->configure(m_messageQueueToVis,
                 m_fftSize,
                 m_fftOverlap,
                 m_averagingNb,
                 m_averagingMode,
                 (FFTWindow::Function)m_fftWindow,
                 m_linear);
     }
     if (m_glSpectrum != 0)
     {
         if ((m_averagingMode == AvgModeFixed) || (m_averagingMode == AvgModeMax)) {
             m_glSpectrum->setTimingRate(m_averagingNb == 0 ? 1 : m_averagingNb);
         } else {
             m_glSpectrum->setTimingRate(1);
         }
     }
     setAveragingToolitp();
 }
on_averagingMode_currentIndexChanged
void GLSpectrumGUI::on_averagingMode_currentIndexChanged (int index) private slot
Definition at line 245 of file glspectrumgui.cpp.
References AvgModeFixed, AvgModeMax, AvgModeMoving, SpectrumVis::configure(), m_averagingMaxScale, m_averagingMode, m_averagingNb, m_fftOverlap, m_fftSize, m_fftWindow, m_glSpectrum, m_linear, m_messageQueueToVis, m_spectrumVis, setAveragingCombo(), and GLSpectrum::setTimingRate().
 {
     m_averagingMode = index < 0 ? AvgModeNone : index > 3 ? AvgModeMax : (AveragingMode) index;
     if (m_averagingMode == AvgModeMoving)
     {
         m_averagingMaxScale = 2;
         setAveragingCombo();
         m_averagingNb = m_averagingNb > 1000 ? 1000 : m_averagingNb;
     }
     else
     {
         m_averagingMaxScale = 5;
         setAveragingCombo();
     }
     if(m_spectrumVis != 0) {
         m_spectrumVis->configure(m_messageQueueToVis,
                 m_fftSize,
                 m_fftOverlap,
                 m_averagingNb,
                 m_averagingMode,
                 (FFTWindow::Function)m_fftWindow,
                 m_linear);
     }
     if (m_glSpectrum != 0)
     {
         if ((m_averagingMode == AvgModeFixed) || (m_averagingMode == AvgModeMax)) {
             m_glSpectrum->setTimingRate(m_averagingNb == 0 ? 1 : m_averagingNb);
         } else {
             m_glSpectrum->setTimingRate(1);
         }
     }
 }
on_clearSpectrum_clicked
void GLSpectrumGUI::on_clearSpectrum_clicked (bool checked) private slot
Definition at line 454 of file glspectrumgui.cpp.
References GLSpectrum::clearSpectrumHistogram(), and m_glSpectrum.
 {
     (void) checked;
     if(m_glSpectrum != 0) {
         m_glSpectrum->clearSpectrumHistogram();
     }
 }
on_current_toggled
void GLSpectrumGUI::on_current_toggled (bool checked) private slot
Definition at line 412 of file glspectrumgui.cpp.
References m_displayCurrent, m_glSpectrum, and GLSpectrum::setDisplayCurrent().
 {
     m_displayCurrent = checked;
     if(m_glSpectrum != 0) {
         m_glSpectrum->setDisplayCurrent(m_displayCurrent);
     }
 }
on_decay_valueChanged
void GLSpectrumGUI::on_decay_valueChanged (int index) private slot
Definition at line 361 of file glspectrumgui.cpp.
References arg(), m_decay, m_glSpectrum, GLSpectrum::setDecay(), and ui.
 {
     m_decay = index;
     ui->decay->setToolTip(QString("Decay: %1").arg(m_decay));
     if(m_glSpectrum != 0) {
         m_glSpectrum->setDecay(m_decay);
     }
 }
on_decayDivisor_valueChanged
void GLSpectrumGUI::on_decayDivisor_valueChanged (int index) private slot
Definition at line 370 of file glspectrumgui.cpp.
References applySettings(), m_decayDivisor, and m_glSpectrum.
 {
     m_decayDivisor = index;
     //ui->decayDivisor->setToolTip(QString("Decay divisor: %1").arg(m_decayDivisor));
     if(m_glSpectrum != 0) {
         applySettings();
     }
 }
on_fftSize_currentIndexChanged
void GLSpectrumGUI::on_fftSize_currentIndexChanged (int index) private slot
Definition at line 230 of file glspectrumgui.cpp.
References SpectrumVis::configure(), m_averagingMode, m_averagingNb, m_fftOverlap, m_fftSize, m_fftWindow, m_linear, m_messageQueueToVis, m_spectrumVis, and setAveragingToolitp().
 {
     m_fftSize = 1 << (7 + index);
     if(m_spectrumVis != 0) {
         m_spectrumVis->configure(m_messageQueueToVis,
                 m_fftSize,
                 m_fftOverlap,
                 m_averagingNb,
                 m_averagingMode,
                 (FFTWindow::Function)m_fftWindow,
                 m_linear);
     }
     setAveragingToolitp();
 }
on_fftWindow_currentIndexChanged
void GLSpectrumGUI::on_fftWindow_currentIndexChanged (int index) private slot
Definition at line 216 of file glspectrumgui.cpp.
References SpectrumVis::configure(), m_averagingMode, m_averagingNb, m_fftOverlap, m_fftSize, m_fftWindow, m_linear, m_messageQueueToVis, and m_spectrumVis.
 {
     m_fftWindow = index;
     if(m_spectrumVis != 0) {
         m_spectrumVis->configure(m_messageQueueToVis,
                 m_fftSize,
                 m_fftOverlap,
                 m_averagingNb,
                 m_averagingMode,
                 (FFTWindow::Function)m_fftWindow,
                 m_linear);
     }
 }
on_grid_toggled
void GLSpectrumGUI::on_grid_toggled (bool checked) private slot
Definition at line 428 of file glspectrumgui.cpp.
References m_displayGrid, m_glSpectrum, and GLSpectrum::setDisplayGrid().
 {
     m_displayGrid = checked;
     if(m_glSpectrum != 0) {
         m_glSpectrum->setDisplayGrid(m_displayGrid);
     }
 }
on_gridIntensity_valueChanged
void GLSpectrumGUI::on_gridIntensity_valueChanged (int index) private slot
Definition at line 436 of file glspectrumgui.cpp.
References arg(), m_displayGridIntensity, m_glSpectrum, GLSpectrum::setDisplayGridIntensity(), and ui.
 {
     m_displayGridIntensity = index;
     ui->gridIntensity->setToolTip(QString("Grid intensity: %1").arg(m_displayGridIntensity));
     if(m_glSpectrum != 0) {
         m_glSpectrum->setDisplayGridIntensity(m_displayGridIntensity);
     }
 }
on_histogram_toggled
void GLSpectrumGUI::on_histogram_toggled (bool checked) private slot
Definition at line 396 of file glspectrumgui.cpp.
References m_displayHistogram, m_glSpectrum, and GLSpectrum::setDisplayHistogram().
 {
     m_displayHistogram = checked;
     if(m_glSpectrum != 0) {
         m_glSpectrum->setDisplayHistogram(m_displayHistogram);
     }
 }
on_invert_toggled
void GLSpectrumGUI::on_invert_toggled (bool checked) private slot
Definition at line 420 of file glspectrumgui.cpp.
References m_glSpectrum, m_invert, and GLSpectrum::setInvertedWaterfall().
 {
     m_invert = checked;
     if(m_glSpectrum != 0) {
         m_glSpectrum->setInvertedWaterfall(m_invert);
     }
 }
on_levelRange_currentIndexChanged
void GLSpectrumGUI::on_levelRange_currentIndexChanged (int index) private slot
Definition at line 347 of file glspectrumgui.cpp.
References m_glSpectrum, m_linear, m_powerRange, m_refLevel, GLSpectrum::setPowerRange(), and GLSpectrum::setReferenceLevel().
 {
     m_powerRange = 100 - index * 5;
     if(m_glSpectrum != 0)
     {
         Real refLevel = m_linear ? pow(10.0, m_refLevel/10.0) : m_refLevel;
         Real powerRange = m_linear ? pow(10.0, m_refLevel/10.0) :  m_powerRange;
         qDebug("GLSpectrumGUI::on_levelRange_currentIndexChanged: powerRange: %e", powerRange);
         m_glSpectrum->setReferenceLevel(refLevel);
         m_glSpectrum->setPowerRange(powerRange);
     }
 }
on_linscale_toggled
void GLSpectrumGUI::on_linscale_toggled (bool checked) private slot
Definition at line 308 of file glspectrumgui.cpp.
References SpectrumVis::configure(), m_averagingMode, m_averagingNb, m_fftOverlap, m_fftSize, m_fftWindow, m_glSpectrum, m_linear, m_messageQueueToVis, m_powerRange, m_refLevel, m_spectrumVis, GLSpectrum::setLinear(), GLSpectrum::setPowerRange(), and GLSpectrum::setReferenceLevel().
Referenced by GLSpectrumGUI().
 {
     m_linear = checked;
     if(m_spectrumVis != 0) {
         m_spectrumVis->configure(m_messageQueueToVis,
                 m_fftSize,
                 m_fftOverlap,
                 m_averagingNb,
                 m_averagingMode,
                 (FFTWindow::Function)m_fftWindow,
                 m_linear);
     }
     if(m_glSpectrum != 0)
     {
         Real refLevel = m_linear ? pow(10.0, m_refLevel/10.0) : m_refLevel;
         Real powerRange = m_linear ? pow(10.0, m_refLevel/10.0) :  m_powerRange;
         qDebug("GLSpectrumGUI::on_linscale_toggled: refLevel: %e powerRange: %e", refLevel, powerRange);
         m_glSpectrum->setReferenceLevel(refLevel);
         m_glSpectrum->setPowerRange(powerRange);
         m_glSpectrum->setLinear(m_linear);
     }
 }
on_maxHold_toggled
void GLSpectrumGUI::on_maxHold_toggled (bool checked) private slot
Definition at line 404 of file glspectrumgui.cpp.
References m_displayMaxHold, m_glSpectrum, and GLSpectrum::setDisplayMaxHold().
 {
     m_displayMaxHold = checked;
     if(m_glSpectrum != 0) {
         m_glSpectrum->setDisplayMaxHold(m_displayMaxHold);
     }
 }
on_refLevel_currentIndexChanged
void GLSpectrumGUI::on_refLevel_currentIndexChanged (int index) private slot
Definition at line 333 of file glspectrumgui.cpp.
References m_glSpectrum, m_linear, m_powerRange, m_refLevel, GLSpectrum::setPowerRange(), and GLSpectrum::setReferenceLevel().
 {
     m_refLevel = 0 - index * 5;
     if(m_glSpectrum != 0)
     {
         Real refLevel = m_linear ? pow(10.0, m_refLevel/10.0) : m_refLevel;
         Real powerRange = m_linear ? pow(10.0, m_refLevel/10.0) :  m_powerRange;
         qDebug("GLSpectrumGUI::on_refLevel_currentIndexChanged: refLevel: %e ", refLevel);
         m_glSpectrum->setReferenceLevel(refLevel);
         m_glSpectrum->setPowerRange(powerRange);
     }
 }
on_stroke_valueChanged
void GLSpectrumGUI::on_stroke_valueChanged (int index) private slot
Definition at line 379 of file glspectrumgui.cpp.
References applySettings(), m_glSpectrum, and m_histogramStroke.
 {
     m_histogramStroke = index;
     //ui->stroke->setToolTip(QString("Stroke: %1").arg(m_histogramStroke));
     if(m_glSpectrum != 0) {
         applySettings();
     }
 }
on_traceIntensity_valueChanged
void GLSpectrumGUI::on_traceIntensity_valueChanged (int index) private slot
Definition at line 445 of file glspectrumgui.cpp.
References arg(), m_displayTraceIntensity, m_glSpectrum, GLSpectrum::setDisplayTraceIntensity(), and ui.
 {
     m_displayTraceIntensity = index;
     ui->traceIntensity->setToolTip(QString("Trace intensity: %1").arg(m_displayTraceIntensity));
     if(m_glSpectrum != 0) {
         m_glSpectrum->setDisplayTraceIntensity(m_displayTraceIntensity);
     }
 }
on_waterfall_toggled
void GLSpectrumGUI::on_waterfall_toggled (bool checked) private slot
Definition at line 388 of file glspectrumgui.cpp.
References m_displayWaterfall, m_glSpectrum, and GLSpectrum::setDisplayWaterfall().
 {
     m_displayWaterfall = checked;
     if(m_glSpectrum != 0) {
         m_glSpectrum->setDisplayWaterfall(m_displayWaterfall);
     }
 }
resetToDefaults()
void GLSpectrumGUI::resetToDefaults ()
Definition at line 62 of file glspectrumgui.cpp.
References applySettings(), AvgModeNone, FFTWindow::Hamming, m_averagingIndex, m_averagingMode, m_decay, m_decayDivisor, m_displayGrid, m_displayGridIntensity, m_displayHistogram, m_displayMaxHold, m_displayWaterfall, m_fftOverlap, m_fftSize, m_fftWindow, m_histogramStroke, m_invert, m_invertedWaterfall, m_linear, m_powerRange, and m_refLevel.
Referenced by deserialize().
 {
     m_fftSize = 1024;
     m_fftOverlap = 0;
     m_fftWindow = FFTWindow::Hamming;
     m_refLevel = 0;
     m_powerRange = 100;
     m_decay = 1;
     m_decayDivisor = 1;
     m_histogramStroke = 30;
     m_displayGridIntensity = 5,
     m_displayWaterfall = true;
     m_invertedWaterfall = false;
     m_displayMaxHold = false;
     m_displayHistogram = false;
     m_displayGrid = false;
     m_invert = true;
     m_averagingMode = AvgModeNone;
     m_averagingIndex = 0;
     m_linear = false;
     applySettings();
 }
serialize()
QByteArray GLSpectrumGUI::serialize () const virtual
Implements Serializable.
Definition at line 85 of file glspectrumgui.cpp.
References SimpleSerializer::final(), getAveragingValue(), GLSpectrum::getWaterfallShare(), m_averagingIndex, m_averagingMode, m_decay, m_decayDivisor, m_displayCurrent, m_displayGrid, m_displayGridIntensity, m_displayHistogram, m_displayMaxHold, m_displayTraceIntensity, m_displayWaterfall, m_fftOverlap, m_fftSize, m_fftWindow, m_glSpectrum, m_histogramStroke, m_invert, m_invertedWaterfall, m_linear, m_powerRange, m_refLevel, SimpleSerializer::writeBool(), SimpleSerializer::writeReal(), and SimpleSerializer::writeS32().
Referenced by MainWindow::savePresetSettings().
 {
     SimpleSerializer s(1);
     s.writeS32(1, m_fftSize);
     s.writeS32(2, m_fftOverlap);
     s.writeS32(3, m_fftWindow);
     s.writeReal(4, m_refLevel);
     s.writeReal(5, m_powerRange);
     s.writeBool(6, m_displayWaterfall);
     s.writeBool(7, m_invertedWaterfall);
     s.writeBool(8, m_displayMaxHold);
     s.writeBool(9, m_displayHistogram);
     s.writeS32(10, m_decay);
     s.writeBool(11, m_displayGrid);
     s.writeBool(12, m_invert);
     s.writeS32(13, m_displayGridIntensity);
     s.writeS32(14, m_decayDivisor);
     s.writeS32(15, m_histogramStroke);
     s.writeBool(16, m_displayCurrent);
     s.writeS32(17, m_displayTraceIntensity);
     s.writeReal(18, m_glSpectrum->getWaterfallShare());
     s.writeS32(19, (int) m_averagingMode);
     s.writeS32(20, (qint32) getAveragingValue(m_averagingIndex));
     s.writeBool(21, m_linear);
     return s.final();
 }
setAveragingCombo()
void GLSpectrumGUI::setAveragingCombo () private
Definition at line 515 of file glspectrumgui.cpp.
References i, m_averagingMaxScale, setNumberStr(), and ui.
Referenced by GLSpectrumGUI(), and on_averagingMode_currentIndexChanged().
 {
     int index = ui->averaging->currentIndex();
     ui->averaging->clear();
     ui->averaging->addItem(QString("1"));
     for (int i = 0; i <= m_averagingMaxScale; i++)
     {
         QString s;
         int m = pow(10.0, i);
         int x = 2*m;
         setNumberStr(x, s);
         ui->averaging->addItem(s);
         x = 5*m;
         setNumberStr(x, s);
         ui->averaging->addItem(s);
         x = 10*m;
         setNumberStr(x, s);
         ui->averaging->addItem(s);
     }
     ui->averaging->setCurrentIndex(index >= ui->averaging->count() ? ui->averaging->count() - 1 : index);
 }
setAveragingToolitp()
void GLSpectrumGUI::setAveragingToolitp () private
Definition at line 573 of file glspectrumgui.cpp.
References arg(), GLSpectrum::getSampleRate(), m_averagingNb, m_fftSize, m_glSpectrum, setNumberStr(), and ui.
Referenced by applySettings(), handleMessage(), on_averaging_currentIndexChanged(), and on_fftSize_currentIndexChanged().
 {
     if (m_glSpectrum)
     {
         QString s;
         float averagingTime = (m_fftSize * (m_averagingNb == 0 ? 1 : m_averagingNb)) / (float) m_glSpectrum->getSampleRate();
         setNumberStr(averagingTime, 2, s);
         ui->averaging->setToolTip(QString("Number of averaging samples (avg time: %1s)").arg(s));
     }
     else
     {
         ui->averaging->setToolTip(QString("Number of averaging samples"));
     }
 }
setBuddies()
void GLSpectrumGUI::setBuddies (MessageQueue * messageQueue, SpectrumVis * spectrumVis, GLSpectrum * glSpectrum)
Definition at line 53 of file glspectrumgui.cpp.
References applySettings(), m_glSpectrum, m_messageQueue, m_messageQueueToVis, m_spectrumVis, and GLSpectrum::setMessageQueueToGUI().
Referenced by DeviceUISet::DeviceUISet().
 {
     m_messageQueueToVis = messageQueue;
     m_spectrumVis = spectrumVis;
     m_glSpectrum = glSpectrum;
     m_glSpectrum->setMessageQueueToGUI(&m_messageQueue);
     applySettings();
 }
setNumberStr() [1/2]
void GLSpectrumGUI::setNumberStr (int n, QString & s) private
Definition at line 539 of file glspectrumgui.cpp.
Referenced by setAveragingCombo(), and setAveragingToolitp().
 {
     if (n < 1000) {
         s = tr("%1").arg(n);
     } else if (n < 100000) {
         s = tr("%1k").arg(n/1000);
     } else if (n < 1000000) {
         s = tr("%1e5").arg(n/100000);
     } else if (n < 1000000000) {
         s = tr("%1M").arg(n/1000000);
     } else {
         s = tr("%1G").arg(n/1000000000);
     }
 }
setNumberStr() [2/2]
void GLSpectrumGUI::setNumberStr (float v, int decimalPlaces, QString & s) private
Definition at line 554 of file glspectrumgui.cpp.
 {
     if (v < 1e-6) {
         s = tr("%1n").arg(v*1e9, 0, 'f', decimalPlaces);
     } else if (v < 1e-3) {
         s = tr("%1").arg(v*1e6, 0, 'f', decimalPlaces);
     } else if (v < 1.0) {
         s = tr("%1m").arg(v*1e3, 0, 'f', decimalPlaces);
     } else if (v < 1e3) {
         s = tr("%1").arg(v, 0, 'f', decimalPlaces);
     } else if (v < 1e6) {
         s = tr("%1k").arg(v*1e-3, 0, 'f', decimalPlaces);
     } else if (v < 1e9) {
         s = tr("%1M").arg(v*1e-6, 0, 'f', decimalPlaces);
     } else {
         s = tr("%1G").arg(v*1e-9, 0, 'f', decimalPlaces);
     }
 }
Member Data Documentation
m_averagingIndex
int GLSpectrumGUI::m_averagingIndex private
Definition at line 64 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_averaging_currentIndexChanged(), resetToDefaults(), and serialize().
m_averagingMaxScale
int GLSpectrumGUI::m_averagingMaxScale private
Max power of 10 multiplier to 2,5,10 base ex: 2 -> 2,5,10,20,50,100,200,500,1000.
Definition at line 65 of file glspectrumgui.h.
Referenced by getAveragingIndex(), getAveragingValue(), on_averagingMode_currentIndexChanged(), and setAveragingCombo().
m_averagingMode
AveragingMode GLSpectrumGUI::m_averagingMode private
Definition at line 63 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_averaging_currentIndexChanged(), on_averagingMode_currentIndexChanged(), on_fftSize_currentIndexChanged(), on_fftWindow_currentIndexChanged(), on_linscale_toggled(), resetToDefaults(), and serialize().
m_averagingNb
unsigned int GLSpectrumGUI::m_averagingNb private
Definition at line 66 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_averaging_currentIndexChanged(), on_averagingMode_currentIndexChanged(), on_fftSize_currentIndexChanged(), on_fftWindow_currentIndexChanged(), on_linscale_toggled(), and setAveragingToolitp().
m_decay
int GLSpectrumGUI::m_decay private
Definition at line 51 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_decay_valueChanged(), resetToDefaults(), and serialize().
m_decayDivisor
int GLSpectrumGUI::m_decayDivisor private
Definition at line 52 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_decayDivisor_valueChanged(), resetToDefaults(), and serialize().
m_displayCurrent
bool GLSpectrumGUI::m_displayCurrent private
Definition at line 59 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_current_toggled(), and serialize().
m_displayGrid
bool GLSpectrumGUI::m_displayGrid private
Definition at line 61 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_grid_toggled(), resetToDefaults(), and serialize().
m_displayGridIntensity
int GLSpectrumGUI::m_displayGridIntensity private
Definition at line 54 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_gridIntensity_valueChanged(), resetToDefaults(), and serialize().
m_displayHistogram
bool GLSpectrumGUI::m_displayHistogram private
Definition at line 60 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_histogram_toggled(), resetToDefaults(), and serialize().
m_displayMaxHold
bool GLSpectrumGUI::m_displayMaxHold private
Definition at line 58 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_maxHold_toggled(), resetToDefaults(), and serialize().
m_displayTraceIntensity
int GLSpectrumGUI::m_displayTraceIntensity private
Definition at line 55 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_traceIntensity_valueChanged(), and serialize().
m_displayWaterfall
bool GLSpectrumGUI::m_displayWaterfall private
Definition at line 56 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_waterfall_toggled(), resetToDefaults(), and serialize().
m_fftOverlap
qint32 GLSpectrumGUI::m_fftOverlap private
Definition at line 47 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_averaging_currentIndexChanged(), on_averagingMode_currentIndexChanged(), on_fftSize_currentIndexChanged(), on_fftWindow_currentIndexChanged(), on_linscale_toggled(), resetToDefaults(), and serialize().
m_fftSize
qint32 GLSpectrumGUI::m_fftSize private
Definition at line 46 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_averaging_currentIndexChanged(), on_averagingMode_currentIndexChanged(), on_fftSize_currentIndexChanged(), on_fftWindow_currentIndexChanged(), on_linscale_toggled(), resetToDefaults(), serialize(), and setAveragingToolitp().
m_fftWindow
qint32 GLSpectrumGUI::m_fftWindow private
Definition at line 48 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_averaging_currentIndexChanged(), on_averagingMode_currentIndexChanged(), on_fftSize_currentIndexChanged(), on_fftWindow_currentIndexChanged(), on_linscale_toggled(), resetToDefaults(), and serialize().
m_glSpectrum
GLSpectrum* GLSpectrumGUI::m_glSpectrum private
Definition at line 43 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_averaging_currentIndexChanged(), on_averagingMode_currentIndexChanged(), on_clearSpectrum_clicked(), on_current_toggled(), on_decay_valueChanged(), on_decayDivisor_valueChanged(), on_grid_toggled(), on_gridIntensity_valueChanged(), on_histogram_toggled(), on_invert_toggled(), on_levelRange_currentIndexChanged(), on_linscale_toggled(), on_maxHold_toggled(), on_refLevel_currentIndexChanged(), on_stroke_valueChanged(), on_traceIntensity_valueChanged(), on_waterfall_toggled(), serialize(), setAveragingToolitp(), and setBuddies().
m_histogramStroke
int GLSpectrumGUI::m_histogramStroke private
Definition at line 53 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_stroke_valueChanged(), resetToDefaults(), and serialize().
m_invert
bool GLSpectrumGUI::m_invert private
Definition at line 62 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_invert_toggled(), resetToDefaults(), and serialize().
m_invertedWaterfall
bool GLSpectrumGUI::m_invertedWaterfall private
Definition at line 57 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), resetToDefaults(), and serialize().
m_linear
bool GLSpectrumGUI::m_linear private
linear else logarithmic scale
Definition at line 67 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_averaging_currentIndexChanged(), on_averagingMode_currentIndexChanged(), on_fftSize_currentIndexChanged(), on_fftWindow_currentIndexChanged(), on_levelRange_currentIndexChanged(), on_linscale_toggled(), on_refLevel_currentIndexChanged(), resetToDefaults(), and serialize().
m_messageQueue
MessageQueue GLSpectrumGUI::m_messageQueue private
Definition at line 44 of file glspectrumgui.h.
Referenced by GLSpectrumGUI(), handleInputMessages(), and setBuddies().
m_messageQueueToVis
MessageQueue* GLSpectrumGUI::m_messageQueueToVis private
Definition at line 41 of file glspectrumgui.h.
Referenced by applySettings(), on_averaging_currentIndexChanged(), on_averagingMode_currentIndexChanged(), on_fftSize_currentIndexChanged(), on_fftWindow_currentIndexChanged(), on_linscale_toggled(), and setBuddies().
m_powerRange
Real GLSpectrumGUI::m_powerRange private
Definition at line 50 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_levelRange_currentIndexChanged(), on_linscale_toggled(), on_refLevel_currentIndexChanged(), resetToDefaults(), and serialize().
m_refLevel
Real GLSpectrumGUI::m_refLevel private
Definition at line 49 of file glspectrumgui.h.
Referenced by applySettings(), deserialize(), on_levelRange_currentIndexChanged(), on_linscale_toggled(), on_refLevel_currentIndexChanged(), resetToDefaults(), and serialize().
m_spectrumVis
SpectrumVis* GLSpectrumGUI::m_spectrumVis private
Definition at line 42 of file glspectrumgui.h.
Referenced by applySettings(), on_averaging_currentIndexChanged(), on_averagingMode_currentIndexChanged(), on_fftSize_currentIndexChanged(), on_fftWindow_currentIndexChanged(), on_linscale_toggled(), and setBuddies().
ui
Ui::GLSpectrumGUI* GLSpectrumGUI::ui private
Definition at line 39 of file glspectrumgui.h.
Referenced by applySettings(), GLSpectrumGUI(), on_decay_valueChanged(), on_gridIntensity_valueChanged(), on_traceIntensity_valueChanged(), setAveragingCombo(), setAveragingToolitp(), and ~GLSpectrumGUI().
The documentation for this class was generated from the following files:
sdrgui/gui/glspectrumgui.h
sdrgui/gui/glspectrumgui.cpp