SDRAngel: PlutoSDRInput::MsgConfigurePlutoSDR Class Reference
PlutoSDRInput::MsgConfigurePlutoSDR Class Reference
#include <plutosdrinput.h>
Public Member Functions
const PlutoSDRInputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigurePlutoSDR * create (const PlutoSDRInputSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigurePlutoSDR (const PlutoSDRInputSettings &settings, bool force)
Private Attributes
PlutoSDRInputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 41 of file plutosdrinput.h.
Constructor & Destructor Documentation
MsgConfigurePlutoSDR()
PlutoSDRInput::MsgConfigurePlutoSDR::MsgConfigurePlutoSDR (const PlutoSDRInputSettings & settings, bool force) inline private
Definition at line 57 of file plutosdrinput.h.
Referenced by create().
                                                                                 :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigurePlutoSDR* PlutoSDRInput::MsgConfigurePlutoSDR::create (const PlutoSDRInputSettings & settings, bool force) inline static
Definition at line 48 of file plutosdrinput.h.
References MsgConfigurePlutoSDR().
Referenced by PlutoSDRInput::deserialize(), PlutoSDRInput::setCenterFrequency(), PlutoSDRInputGui::updateHardware(), and PlutoSDRInput::webapiSettingsPutPatch().
         {
             return new MsgConfigurePlutoSDR(settings, force);
         }
getForce()
bool PlutoSDRInput::MsgConfigurePlutoSDR::getForce () const inline
Definition at line 46 of file plutosdrinput.h.
References m_force.
Referenced by PlutoSDRInput::handleMessage().
 { return m_force; }
getSettings()
const PlutoSDRInputSettings& PlutoSDRInput::MsgConfigurePlutoSDR::getSettings () const inline
Definition at line 45 of file plutosdrinput.h.
References m_settings.
Referenced by PlutoSDRInputGui::handleMessage(), and PlutoSDRInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool PlutoSDRInput::MsgConfigurePlutoSDR::m_force private
Definition at line 55 of file plutosdrinput.h.
Referenced by getForce().
m_settings
PlutoSDRInputSettings PlutoSDRInput::MsgConfigurePlutoSDR::m_settings private
Definition at line 54 of file plutosdrinput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/plutosdrinput/plutosdrinput.h