SDRAngel: leansdr::bitvect< T, N > Struct Template Reference
leansdr::bitvect< T, N > Struct Template Reference
#include <discrmath.h>
Public Member Functions
bitvect ()
bitvect (T val)
template<int M>
bitvect< T, N > & copy (const bitvect< T, M > &a)
bool operator[] (unsigned int i) const
template<int M>
bitvect< T, N > & operator+= (const bitvect< T, M > &a)
bitvect< T, N > & operator<<= (unsigned int n)
Public Attributes
T v [NW]
Static Public Attributes
static const size_t WSIZE = sizeof(T) * 8
static const size_t NW = (N + WSIZE - 1) / WSIZE
Private Member Functions
void truncate_to_N ()
Detailed Description
template<typename T, int N>
struct leansdr::bitvect< T, N >
Definition at line 33 of file discrmath.h.
Constructor & Destructor Documentation
bitvect() [1/2]
template<typename T, int N> leansdr::bitvect< T, N >::bitvect () inline
Definition at line 39 of file discrmath.h.
 {}
bitvect() [2/2]
template<typename T, int N> leansdr::bitvect< T, N >::bitvect (T val) inline
Definition at line 40 of file discrmath.h.
     {
         v[0] = val;
         for (int i = 1; i < NW; ++i)
             v[i] = 0;
     }
Member Function Documentation
copy()
template<typename T, int N> template<int M> bitvect<T, N>& leansdr::bitvect< T, N >::copy (const bitvect< T, M > & a) inline
Definition at line 49 of file discrmath.h.
     {
         int nw = (a.NW < NW) ? a.NW : NW;
         for (int i = 0; i < nw; ++i)
             v[i] = a.v[i];
         if (M < N)
             for (int i = a.NW; i < NW; ++i)
                 v[i] = 0;
         if (M > N)
             truncate_to_N();
         return *this;
     }
operator+=()
template<typename T, int N> template<int M> bitvect<T, N>& leansdr::bitvect< T, N >::operator+= (const bitvect< T, M > & a) inline
Definition at line 70 of file discrmath.h.
     {
         int nw = (a.NW < NW) ? a.NW : NW;
         for (int i = 0; i < nw; ++i)
             v[i] ^= a.v[i];
         if (M > N)
             truncate_to_N();
         return *this;
     }
operator<<=()
template<typename T, int N> bitvect<T, N>& leansdr::bitvect< T, N >::operator<<= (unsigned int n) inline
Definition at line 82 of file discrmath.h.
     {
         if (n >= WSIZE)
             fail("shift exceeds word width");
         T mask = ~(((T)-1) << n);
         for (int i = NW - 1; i > 0; --i)
             v[i] = (v[i] << n) | ((v[i - 1] >> (WSIZE - n)) & mask);
         v[0] <<= n;
         if (N != NW * WSIZE)
             truncate_to_N();
         return *this;
     }
operator[]()
template<typename T, int N> bool leansdr::bitvect< T, N >::operator[] (unsigned int i) const inline
Definition at line 62 of file discrmath.h.
     {
         return v[i / WSIZE] & ((T)1 << (i & (WSIZE - 1)));
     }
truncate_to_N()
template<typename T, int N> void leansdr::bitvect< T, N >::truncate_to_N () inline private
Definition at line 97 of file discrmath.h.
Referenced by leansdr::bitvect< T, DP >::copy(), leansdr::bitvect< T, DP >::operator+=(), and leansdr::bitvect< T, DP >::operator<<=().
     {
         v[NW - 1] &= ((T)-1) >> (NW * WSIZE - N);
     }
Member Data Documentation
NW
template<typename T, int N> const size_t leansdr::bitvect< T, N >::NW = (N + WSIZE - 1) / WSIZE static
Definition at line 36 of file discrmath.h.
Referenced by leansdr::bitvect< T, DP >::bitvect(), leansdr::bitvect< T, DP >::copy(), leansdr::operator+(), leansdr::bitvect< T, DP >::operator+=(), leansdr::operator==(), and leansdr::shiftdivmod().
v
template<typename T, int N> T leansdr::bitvect< T, N >::v[NW]
Definition at line 37 of file discrmath.h.
Referenced by leansdr::bitvect< T, DP >::copy(), leansdr::crc8_engine::crc8_engine(), leansdr::divmod(), leansdr::bch_engine< T, N, NP, DP, TGF, GFTRUNCGEN >::encode(), leansdr::operator+(), leansdr::bitvect< T, DP >::operator+=(), leansdr::operator==(), and leansdr::shiftdivmod().
WSIZE
template<typename T, int N> const size_t leansdr::bitvect< T, N >::WSIZE = sizeof(T) * 8 static
Definition at line 35 of file discrmath.h.
Referenced by leansdr::bitvect< T, DP >::operator[]().
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/discrmath.h