SDRAngel: UDPSourcePlugin Class Reference
UDPSourcePlugin Class Reference
#include <udpsourceplugin.h>
Public Member Functions
UDPSourcePlugin (QObject *parent=0)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
Private Attributes
PluginAPI * m_pluginAPI
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Private Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Private Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Detailed Description
Definition at line 28 of file udpsourceplugin.h.
Constructor & Destructor Documentation
UDPSourcePlugin()
UDPSourcePlugin::UDPSourcePlugin (QObject * parent = 0) explicit
Definition at line 38 of file udpsourceplugin.cpp.
                                                 :
     QObject(parent),
     m_pluginAPI(0)
 {
 }
Member Function Documentation
createTxChannelBS()
BasebandSampleSource * UDPSourcePlugin::createTxChannelBS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 71 of file udpsourceplugin.cpp.
 {
     return new UDPSource(deviceAPI);
 }
createTxChannelCS()
ChannelAPI * UDPSourcePlugin::createTxChannelCS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 76 of file udpsourceplugin.cpp.
 {
     return new UDPSource(deviceAPI);
 }
createTxChannelGUI()
PluginInstanceGUI * UDPSourcePlugin::createTxChannelGUI (DeviceUISet * deviceUISet, BasebandSampleSource * txChannel) virtual
Reimplemented from PluginInterface.
Definition at line 65 of file udpsourceplugin.cpp.
References UDPSourceGUI::create(), and m_pluginAPI.
Referenced by initPlugin().
 {
     return UDPSourceGUI::create(m_pluginAPI, deviceUISet, txChannel);
 }
getPluginDescriptor()
const PluginDescriptor & UDPSourcePlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 44 of file udpsourceplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void UDPSourcePlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 49 of file udpsourceplugin.cpp.
References createTxChannelGUI(), UDPSource::m_channelId, UDPSource::m_channelIdURI, m_pluginAPI, and PluginAPI::registerTxChannel().
 {
     m_pluginAPI = pluginAPI;
     // register TCP Channel Source
     m_pluginAPI->registerTxChannel(UDPSource::m_channelIdURI, UDPSource::m_channelId, this);
 }
Member Data Documentation
m_pluginAPI
PluginAPI* UDPSourcePlugin::m_pluginAPI private
Definition at line 46 of file udpsourceplugin.h.
Referenced by createTxChannelGUI(), and initPlugin().
m_pluginDescriptor
const PluginDescriptor UDPSourcePlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("UDP Channel Source"),
    QString("4.5.2"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 44 of file udpsourceplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/channeltx/udpsource/udpsourceplugin.h
plugins/channeltx/udpsource/udpsourceplugin.cpp