SDRAngel: TestSourceInput::MsgConfigureTestSource Class Reference
TestSourceInput::MsgConfigureTestSource Class Reference
#include <testsourceinput.h>
Public Member Functions
const TestSourceSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureTestSource * create (const TestSourceSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureTestSource (const TestSourceSettings &settings, bool force)
Private Attributes
TestSourceSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 38 of file testsourceinput.h.
Constructor & Destructor Documentation
MsgConfigureTestSource()
TestSourceInput::MsgConfigureTestSource::MsgConfigureTestSource (const TestSourceSettings & settings, bool force) inline private
Definition at line 54 of file testsourceinput.h.
Referenced by create().
                                                                                :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureTestSource* TestSourceInput::MsgConfigureTestSource::create (const TestSourceSettings & settings, bool force) inline static
Definition at line 45 of file testsourceinput.h.
References MsgConfigureTestSource().
Referenced by TestSourceInput::deserialize(), TestSourceInput::setCenterFrequency(), TestSourceGui::updateHardware(), and TestSourceInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureTestSource(settings, force);
         }
getForce()
bool TestSourceInput::MsgConfigureTestSource::getForce () const inline
Definition at line 43 of file testsourceinput.h.
References m_force.
Referenced by TestSourceInput::handleMessage().
 { return m_force; }
getSettings()
const TestSourceSettings& TestSourceInput::MsgConfigureTestSource::getSettings () const inline
Definition at line 42 of file testsourceinput.h.
References m_settings.
Referenced by TestSourceGui::handleMessage(), and TestSourceInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool TestSourceInput::MsgConfigureTestSource::m_force private
Definition at line 52 of file testsourceinput.h.
Referenced by getForce().
m_settings
TestSourceSettings TestSourceInput::MsgConfigureTestSource::m_settings private
Definition at line 51 of file testsourceinput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/testsource/testsourceinput.h