SDRAngel: NFMMod Class Reference
NFMMod Class Reference
#include <nfmmod.h>
Classes
class MsgConfigureChannelizer
class MsgConfigureFileSourceName
class MsgConfigureFileSourceSeek
class MsgConfigureFileSourceStreamTiming
class MsgConfigureNFMMod
class MsgReportFileSourceStreamData
class MsgReportFileSourceStreamTiming
Signals
void levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples)
Public Member Functions
NFMMod (DeviceAPI *deviceAPI)
~NFMMod ()
virtual void destroy ()
virtual void pull (Sample &sample)
virtual void pullAudio (int nbSamples)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
double getMagSq () const
CWKeyer * getCWKeyer ()
Public Member Functions inherited from BasebandSampleSource
BasebandSampleSource ()
virtual ~BasebandSampleSource ()
void feed (SampleSourceFifo *sampleFifo, int nbSamples)
SampleSourceFifo & getSampleSourceFifo ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
void setDeviceSampleSourceFifo (SampleSourceFifo *deviceSampleFifo)
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channeltx.modnfm"
static const QString m_channelId = "NFMMod"
Private Types
enum RateState { RSInitialFill, RSRunning }
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applyAudioSampleRate (int sampleRate)
void applyFeedbackAudioSampleRate (unsigned int sampleRate)
void processOneSample (Complex &ci)
void applyChannelSettings (int basebandSampleRate, int outputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const NFMModSettings &settings, bool force=false)
void pullAF (Real &sample)
void pushFeedback (Real sample)
void calculateLevel (Real &sample)
void modulateSample ()
void openFileStream ()
void seekFileStream (int seekPercentage)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const NFMModSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const NFMModSettings &settings, bool force)
void webapiReverseSendCWSettings (const CWKeyerSettings &settings)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSource * m_threadedChannelizer
UpChannelizer * m_channelizer
int m_basebandSampleRate
int m_outputSampleRate
int m_inputFrequencyOffset
NFMModSettings m_settings
NCO m_carrierNco
NCOF m_toneNco
NCOF m_ctcssNco
float m_modPhasor
baseband modulator phasor
Complex m_modSample
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
bool m_interpolatorConsumed
Interpolator m_feedbackInterpolator
Real m_feedbackInterpolatorDistance
Real m_feedbackInterpolatorDistanceRemain
bool m_feedbackInterpolatorConsumed
Lowpass< Real > m_lowpass
Bandpass< Real > m_bandpass
double m_magsq
MovingAverageUtil< double, double, 16 > m_movingAverage
quint32 m_audioSampleRate
AudioVector m_audioBuffer
uint m_audioBufferFill
AudioFifo m_audioFifo
quint32 m_feedbackAudioSampleRate
AudioVector m_feedbackAudioBuffer
uint m_feedbackAudioBufferFill
AudioFifo m_feedbackAudioFifo
SampleVector m_sampleBuffer
QMutex m_settingsMutex
std::ifstream m_ifstream
QString m_fileName
quint64 m_fileSize
raw file size (bytes)
quint32 m_recordLength
record length in seconds computed from file size
int m_sampleRate
NFMModSettings::NFMModInputAF m_afInput
quint32 m_levelCalcCount
Real m_peakLevel
Real m_levelSum
CWKeyer m_cwKeyer
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Static Private Attributes
static const int m_levelNbSamples = 480
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSource
void handleInputMessages ()
void handleWriteToFifo (int nbSamples)
void handleWriteToDeviceFifo (int nbSamples)
Protected Member Functions inherited from BasebandSampleSource
void handleWriteToFifo (SampleSourceFifo *sampleFifo, int nbSamples)
Protected Attributes inherited from BasebandSampleSource
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
SampleSourceFifo m_sampleFifo
Internal FIFO for multi-channel processing.
SampleSourceFifo * m_deviceSampleFifo
Reference to the device FIFO for single channel processing.
Detailed Description
Definition at line 49 of file nfmmod.h.
Member Enumeration Documentation
RateState
enum NFMMod::RateState private
Enumerator
RSInitialFill
RSRunning
Definition at line 265 of file nfmmod.h.
                    {
         RSInitialFill,
         RSRunning
     };
Constructor & Destructor Documentation
NFMMod()
NFMMod::NFMMod (DeviceAPI * deviceAPI)
Definition at line 55 of file nfmmod.cpp.
References AudioDeviceManager::addAudioSink(), AudioDeviceManager::addAudioSource(), DeviceAPI::addChannelSource(), DeviceAPI::addChannelSourceAPI(), applyChannelSettings(), applyFeedbackAudioSampleRate(), applySettings(), Lowpass< Type >::create(), DSPEngine::getAudioDeviceManager(), BasebandSampleSource::getInputMessageQueue(), AudioDeviceManager::getInputSampleRate(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_basebandSampleRate, m_channelId, m_channelizer, m_ctcssNco, m_cwKeyer, m_deviceAPI, m_feedbackAudioBuffer, m_feedbackAudioBufferFill, m_feedbackAudioFifo, m_feedbackAudioSampleRate, m_inputFrequencyOffset, m_lowpass, m_magsq, m_networkManager, m_outputSampleRate, m_settings, m_threadedChannelizer, m_toneNco, networkManagerFinished(), CWKeyer::reset(), NCOF::setFreq(), and CWKeyer::setSampleRate().
Referenced by NFMMod::MsgReportFileSourceStreamData::MsgReportFileSourceStreamData().
                                    :
     ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSource),
     m_deviceAPI(deviceAPI),
     m_basebandSampleRate(48000),
     m_outputSampleRate(48000),
     m_inputFrequencyOffset(0),
     m_modPhasor(0.0f),
     m_audioFifo(4800),
     m_feedbackAudioFifo(48000),
     m_settingsMutex(QMutex::Recursive),
     m_fileSize(0),
     m_recordLength(0),
     m_sampleRate(48000),
     m_levelCalcCount(0),
     m_peakLevel(0.0f),
     m_levelSum(0.0f)
 {
     setObjectName(m_channelId);
     m_audioBuffer.resize(1<<14);
     m_audioBufferFill = 0;
     m_feedbackAudioBuffer.resize(1<<14);
     m_feedbackAudioBufferFill = 0;
     m_magsq = 0.0;
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSource(&m_audioFifo, getInputMessageQueue());
     m_audioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getInputSampleRate();
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSink(&m_feedbackAudioFifo, getInputMessageQueue());
     m_feedbackAudioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getOutputSampleRate();
     applyFeedbackAudioSampleRate(m_feedbackAudioSampleRate);
     m_lowpass.create(301, m_audioSampleRate, 250.0);
     m_toneNco.setFreq(1000.0, m_audioSampleRate);
     m_ctcssNco.setFreq(88.5, m_audioSampleRate);
     m_cwKeyer.setSampleRate(m_audioSampleRate);
     m_cwKeyer.reset();
     applyChannelSettings(m_basebandSampleRate, m_outputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new UpChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSource(m_channelizer, this);
     m_deviceAPI->addChannelSource(m_threadedChannelizer);
     m_deviceAPI->addChannelSourceAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~NFMMod()
NFMMod::~NFMMod ()
Definition at line 107 of file nfmmod.cpp.
References DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo, m_channelizer, m_deviceAPI, m_feedbackAudioFifo, m_networkManager, m_threadedChannelizer, networkManagerFinished(), AudioDeviceManager::removeAudioSink(), AudioDeviceManager::removeAudioSource(), DeviceAPI::removeChannelSource(), and DeviceAPI::removeChannelSourceAPI().
Referenced by NFMMod::MsgReportFileSourceStreamData::MsgReportFileSourceStreamData().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_feedbackAudioFifo);
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSource(&m_audioFifo);
     m_deviceAPI->removeChannelSourceAPI(this);
     m_deviceAPI->removeChannelSource(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
 }
Member Function Documentation
applyAudioSampleRate()
void NFMMod::applyAudioSampleRate (int sampleRate) private
Definition at line 495 of file nfmmod.cpp.
References applyFeedbackAudioSampleRate(), Bandpass< Type >::create(), Lowpass< Type >::create(), Interpolator::create(), NFMMod::MsgConfigureChannelizer::create(), NFMModSettings::getCTCSSFreq(), NFMModSettings::m_afBandwidth, m_audioSampleRate, m_bandpass, NFMModSettings::m_ctcssIndex, m_ctcssNco, m_cwKeyer, m_feedbackAudioSampleRate, NFMModSettings::m_inputFrequencyOffset, BasebandSampleSource::m_inputMessageQueue, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, m_lowpass, m_outputSampleRate, NFMModSettings::m_rfBandwidth, m_settings, m_settingsMutex, NFMModSettings::m_toneFrequency, m_toneNco, MessageQueue::push(), NCOF::setFreq(), and CWKeyer::setSampleRate().
Referenced by applySettings(), and handleMessage().
 {
     qDebug("NFMMod::applyAudioSampleRate: %d", sampleRate);
     MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
             sampleRate, m_settings.m_inputFrequencyOffset);
     m_inputMessageQueue.push(channelConfigMsg);
     m_settingsMutex.lock();
     m_interpolatorDistanceRemain = 0;
     m_interpolatorConsumed = false;
     m_interpolatorDistance = (Real) sampleRate / (Real) m_outputSampleRate;
     m_interpolator.create(48, sampleRate, m_settings.m_rfBandwidth / 2.2, 3.0);
     m_lowpass.create(301, sampleRate, 250.0);
     m_bandpass.create(301, sampleRate, 300.0, m_settings.m_afBandwidth);
     m_toneNco.setFreq(m_settings.m_toneFrequency, sampleRate);
     m_ctcssNco.setFreq(NFMModSettings::getCTCSSFreq(m_settings.m_ctcssIndex), sampleRate);
     m_cwKeyer.setSampleRate(sampleRate);
     m_settingsMutex.unlock();
     m_audioSampleRate = sampleRate;
     applyFeedbackAudioSampleRate(m_feedbackAudioSampleRate);
 }
applyChannelSettings()
void NFMMod::applyChannelSettings (int basebandSampleRate, int outputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 538 of file nfmmod.cpp.
References Interpolator::create(), m_audioSampleRate, m_basebandSampleRate, m_carrierNco, m_inputFrequencyOffset, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, m_outputSampleRate, NFMModSettings::m_rfBandwidth, m_settings, m_settingsMutex, and NCO::setFreq().
Referenced by handleMessage(), NFMMod(), and start().
 {
     qDebug() << "NFMMod::applyChannelSettings:"
             << " basebandSampleRate: " << basebandSampleRate
             << " outputSampleRate: " << outputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if ((inputFrequencyOffset != m_inputFrequencyOffset) ||
         (outputSampleRate != m_outputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_carrierNco.setFreq(inputFrequencyOffset, outputSampleRate);
         m_settingsMutex.unlock();
     }
     if ((outputSampleRate != m_outputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_interpolatorDistanceRemain = 0;
         m_interpolatorConsumed = false;
         m_interpolatorDistance = (Real) m_audioSampleRate / (Real) outputSampleRate;
         m_interpolator.create(48, m_audioSampleRate, m_settings.m_rfBandwidth / 2.2, 3.0);
         m_settingsMutex.unlock();
     }
     m_basebandSampleRate = basebandSampleRate;
     m_outputSampleRate = outputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applyFeedbackAudioSampleRate()
void NFMMod::applyFeedbackAudioSampleRate (unsigned int sampleRate) private
Definition at line 521 of file nfmmod.cpp.
References Interpolator::create(), m_audioSampleRate, m_feedbackAudioSampleRate, m_feedbackInterpolator, m_feedbackInterpolatorConsumed, m_feedbackInterpolatorDistance, m_feedbackInterpolatorDistanceRemain, m_settingsMutex, and leansdr::min().
Referenced by applyAudioSampleRate(), applySettings(), handleMessage(), and NFMMod().
 {
     qDebug("NFMMod::applyFeedbackAudioSampleRate: %u", sampleRate);
     m_settingsMutex.lock();
     m_feedbackInterpolatorDistanceRemain = 0;
     m_feedbackInterpolatorConsumed = false;
     m_feedbackInterpolatorDistance = (Real) sampleRate / (Real) m_audioSampleRate;
     Real cutoff = std::min(sampleRate, m_audioSampleRate) / 2.2f;
     m_feedbackInterpolator.create(48, sampleRate, cutoff, 3.0);
     m_settingsMutex.unlock();
     m_feedbackAudioSampleRate = sampleRate;
 }
applySettings()
void NFMMod::applySettings (const NFMModSettings & settings, bool force = false) private
Definition at line 568 of file nfmmod.cpp.
References AudioDeviceManager::addAudioSink(), AudioDeviceManager::addAudioSource(), applyAudioSampleRate(), applyFeedbackAudioSampleRate(), Lowpass< Type >::create(), Bandpass< Type >::create(), Interpolator::create(), DSPEngine::getAudioDeviceManager(), NFMModSettings::getCTCSSFreq(), AudioDeviceManager::getInputDeviceIndex(), BasebandSampleSource::getInputMessageQueue(), AudioDeviceManager::getInputSampleRate(), AudioDeviceManager::getOutputDeviceIndex(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), NFMModSettings::m_afBandwidth, NFMModSettings::m_audioDeviceName, m_audioFifo, m_audioSampleRate, m_bandpass, NFMModSettings::m_channelMute, NFMModSettings::m_ctcssIndex, m_ctcssNco, NFMModSettings::m_ctcssOn, NFMModSettings::m_feedbackAudioDeviceName, m_feedbackAudioFifo, m_feedbackAudioSampleRate, NFMModSettings::m_fmDeviation, NFMModSettings::m_inputFrequencyOffset, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, m_lowpass, NFMModSettings::m_modAFInput, m_outputSampleRate, NFMModSettings::m_playLoop, NFMModSettings::m_reverseAPIAddress, NFMModSettings::m_reverseAPIChannelIndex, NFMModSettings::m_reverseAPIDeviceIndex, NFMModSettings::m_reverseAPIPort, NFMModSettings::m_rfBandwidth, m_settings, m_settingsMutex, NFMModSettings::m_toneFrequency, m_toneNco, NFMModSettings::m_useReverseAPI, NFMModSettings::m_volumeFactor, NCOF::setFreq(), and webapiReverseSendSettings().
Referenced by handleMessage(), and NFMMod().
 {
     qDebug() << "NFMMod::applySettings:"
             << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
             << " m_rfBandwidth: " << settings.m_rfBandwidth
             << " m_afBandwidth: " << settings.m_afBandwidth
             << " m_fmDeviation: " << settings.m_fmDeviation
             << " m_volumeFactor: " << settings.m_volumeFactor
             << " m_toneFrequency: " << settings.m_toneFrequency
             << " m_ctcssIndex: " << settings.m_ctcssIndex
             << " m_ctcssOn: " << settings.m_ctcssOn
             << " m_channelMute: " << settings.m_channelMute
             << " m_playLoop: " << settings.m_playLoop
             << " m_modAFInput " << settings.m_modAFInput
             << " m_audioDeviceName: " << settings.m_audioDeviceName
             << " m_useReverseAPI: " << settings.m_useReverseAPI
             << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
             << " m_reverseAPIAddress: " << settings.m_reverseAPIPort
             << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex
             << " m_reverseAPIChannelIndex: " << settings.m_reverseAPIChannelIndex
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if ((settings.m_inputFrequencyOffset != m_settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if ((settings.m_fmDeviation != m_settings.m_fmDeviation) || force) {
         reverseAPIKeys.append("fmDeviation");
     }
     if ((settings.m_volumeFactor != m_settings.m_volumeFactor) || force) {
         reverseAPIKeys.append("volumeFactor");
     }
     if ((settings.m_ctcssOn != m_settings.m_ctcssOn) || force) {
         reverseAPIKeys.append("ctcssOn");
     }
     if ((settings.m_channelMute != m_settings.m_channelMute) || force) {
         reverseAPIKeys.append("channelMute");
     }
     if ((settings.m_playLoop != m_settings.m_playLoop) || force) {
         reverseAPIKeys.append("playLoop");
     }
     if ((settings.m_modAFInput != m_settings.m_modAFInput) || force) {
         reverseAPIKeys.append("modAFInput");
     }
     if((settings.m_rfBandwidth != m_settings.m_rfBandwidth) || force)
     {
         reverseAPIKeys.append("rfBandwidth");
         m_settingsMutex.lock();
         m_interpolatorDistanceRemain = 0;
         m_interpolatorConsumed = false;
         m_interpolatorDistance = (Real) m_audioSampleRate / (Real) m_outputSampleRate;
         m_interpolator.create(48, m_audioSampleRate, settings.m_rfBandwidth / 2.2, 3.0);
         m_settingsMutex.unlock();
     }
     if ((settings.m_afBandwidth != m_settings.m_afBandwidth) || force)
     {
         reverseAPIKeys.append("afBandwidth");
         m_settingsMutex.lock();
         m_lowpass.create(301, m_audioSampleRate, 250.0);
         m_bandpass.create(301, m_audioSampleRate, 300.0, settings.m_afBandwidth);
         m_settingsMutex.unlock();
     }
     if ((settings.m_toneFrequency != m_settings.m_toneFrequency) || force)
     {
         reverseAPIKeys.append("toneFrequency");
         m_settingsMutex.lock();
         m_toneNco.setFreq(settings.m_toneFrequency, m_audioSampleRate);
         m_settingsMutex.unlock();
     }
     if ((settings.m_ctcssIndex != m_settings.m_ctcssIndex) || force)
     {
         reverseAPIKeys.append("ctcssIndex");
         m_settingsMutex.lock();
         m_ctcssNco.setFreq(NFMModSettings::getCTCSSFreq(settings.m_ctcssIndex), m_audioSampleRate);
         m_settingsMutex.unlock();
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force)
     {
         reverseAPIKeys.append("audioDeviceName");
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getInputDeviceIndex(settings.m_audioDeviceName);
         audioDeviceManager->addAudioSource(&m_audioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getInputSampleRate(audioDeviceIndex);
         if (m_audioSampleRate != audioSampleRate) {
             reverseAPIKeys.append("audioSampleRate");
             applyAudioSampleRate(audioSampleRate);
         }
     }
     if ((settings.m_feedbackAudioDeviceName != m_settings.m_feedbackAudioDeviceName) || force)
     {
         reverseAPIKeys.append("feedbackAudioDeviceName");
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getOutputDeviceIndex(settings.m_feedbackAudioDeviceName);
         audioDeviceManager->addAudioSink(&m_feedbackAudioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getOutputSampleRate(audioDeviceIndex);
         if (m_feedbackAudioSampleRate != audioSampleRate) {
             reverseAPIKeys.append("feedbackAudioSampleRate");
             applyFeedbackAudioSampleRate(audioSampleRate);
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
calculateLevel()
void NFMMod::calculateLevel (Real & sample) private
Definition at line 315 of file nfmmod.cpp.
References levelChanged(), m_levelCalcCount, m_levelNbSamples, m_levelSum, m_peakLevel, leansdr::max(), and sqrt().
Referenced by modulateSample().
 {
     if (m_levelCalcCount < m_levelNbSamples)
     {
         m_peakLevel = std::max(std::fabs(m_peakLevel), sample);
         m_levelSum += sample * sample;
         m_levelCalcCount++;
     }
     else
     {
         qreal rmsLevel = sqrt(m_levelSum / m_levelNbSamples);
         //qDebug("NFMMod::calculateLevel: %f %f", rmsLevel, m_peakLevel);
         emit levelChanged(rmsLevel, m_peakLevel, m_levelNbSamples);
         m_peakLevel = 0.0f;
         m_levelSum = 0.0f;
         m_levelCalcCount = 0;
     }
 }
deserialize()
bool NFMMod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 702 of file nfmmod.cpp.
References NFMMod::MsgConfigureNFMMod::create(), NFMMod::MsgConfigureChannelizer::create(), NFMModSettings::deserialize(), NFMModSettings::m_inputFrequencyOffset, BasebandSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and NFMModSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureChannelizer *msgChan = MsgConfigureChannelizer::create(
             48000, m_settings.m_inputFrequencyOffset);
     m_inputMessageQueue.push(msgChan);
     MsgConfigureNFMMod *msg = MsgConfigureNFMMod::create(m_settings, true);
     m_inputMessageQueue.push(msg);
     return success;
 }
destroy()
virtual void NFMMod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 208 of file nfmmod.h.
References handleMessage(), pull(), pullAudio(), start(), and stop().
 { delete this; }
getCenterFrequency()
virtual qint64 NFMMod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 218 of file nfmmod.h.
References deserialize(), NFMModSettings::m_inputFrequencyOffset, NFMMod::MsgConfigureNFMMod::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getCWKeyer()
CWKeyer* NFMMod::getCWKeyer () inline
Definition at line 249 of file nfmmod.h.
References m_cwKeyer.
Referenced by NFMModGUI::NFMModGUI().
 { return &m_cwKeyer; }
getIdentifier()
virtual void NFMMod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 216 of file nfmmod.h.
 { id = objectName(); }
getMagSq()
double NFMMod::getMagSq () const inline
Definition at line 247 of file nfmmod.h.
References m_magsq.
Referenced by NFMModGUI::tick(), and webapiFormatChannelReport().
 { return m_magsq; }
getNbSinkStreams()
virtual int NFMMod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 223 of file nfmmod.h.
 { return 1; }
getNbSourceStreams()
virtual int NFMMod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 224 of file nfmmod.h.
 { return 0; }
getStreamCenterFrequency()
virtual qint64 NFMMod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 226 of file nfmmod.h.
References NFMModSettings::m_inputFrequencyOffset, NFMMod::MsgConfigureNFMMod::m_settings, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void NFMMod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 217 of file nfmmod.h.
References NFMMod::MsgConfigureNFMMod::m_settings, and NFMModSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool NFMMod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSource.
Definition at line 347 of file nfmmod.cpp.
References applyAudioSampleRate(), applyChannelSettings(), applyFeedbackAudioSampleRate(), applySettings(), DSPConfigureAudio::AudioInput, DSPConfigureAudio::AudioOutput, UpChannelizer::configure(), NFMMod::MsgReportFileSourceStreamTiming::create(), DSPConfigureAudio::getAudioType(), UpChannelizer::MsgChannelizerNotification::getBasebandSampleRate(), NFMMod::MsgConfigureChannelizer::getCenterFrequency(), NFMMod::MsgConfigureFileSourceName::getFileName(), NFMMod::MsgConfigureNFMMod::getForce(), UpChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSource::getInputMessageQueue(), BasebandSampleSource::getMessageQueueToGUI(), NFMMod::MsgConfigureFileSourceSeek::getPercentage(), UpChannelizer::MsgChannelizerNotification::getSampleRate(), NFMMod::MsgConfigureChannelizer::getSampleRate(), DSPConfigureAudio::getSampleRate(), NFMMod::MsgConfigureNFMMod::getSettings(), CWKeyer::MsgConfigureCWKeyer::getSettings(), m_audioSampleRate, m_channelizer, m_fileName, m_fileSize, m_ifstream, m_settings, NFMModSettings::m_useReverseAPI, Message::match(), openFileStream(), MessageQueue::push(), seekFileStream(), and webapiReverseSendCWSettings().
Referenced by destroy().
 {
     if (UpChannelizer::MsgChannelizerNotification::match(cmd))
     {
         UpChannelizer::MsgChannelizerNotification& notif = (UpChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "NFMMod::handleMessage: UpChannelizer::MsgChannelizerNotification";
         applyChannelSettings(notif.getBasebandSampleRate(), notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "NFMMod::handleMessage: MsgConfigureChannelizer:"
                 << " getSampleRate: " << cfg.getSampleRate()
                 << " getCenterFrequency: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureNFMMod::match(cmd))
     {
         MsgConfigureNFMMod& cfg = (MsgConfigureNFMMod&) cmd;
         qDebug() << "NFMMod::handleMessage: MsgConfigureNFMMod";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgConfigureFileSourceName::match(cmd))
     {
         MsgConfigureFileSourceName& conf = (MsgConfigureFileSourceName&) cmd;
         m_fileName = conf.getFileName();
         openFileStream();
         qDebug() << "NFMMod::handleMessage: MsgConfigureFileSourceName:"
                  << " m_fileName: " << m_fileName;
         return true;
     }
     else if (MsgConfigureFileSourceSeek::match(cmd))
     {
         MsgConfigureFileSourceSeek& conf = (MsgConfigureFileSourceSeek&) cmd;
         int seekPercentage = conf.getPercentage();
         seekFileStream(seekPercentage);
         qDebug() << "NFMMod::handleMessage: MsgConfigureFileSourceSeek:"
                  << " seekPercentage: " << seekPercentage;
         return true;
     }
     else if (MsgConfigureFileSourceStreamTiming::match(cmd))
     {
         std::size_t samplesCount;
         if (m_ifstream.eof()) {
             samplesCount = m_fileSize / sizeof(Real);
         } else {
             samplesCount = m_ifstream.tellg() / sizeof(Real);
         }
         MsgReportFileSourceStreamTiming *report;
         report = MsgReportFileSourceStreamTiming::create(samplesCount);
         getMessageQueueToGUI()->push(report);
         return true;
     }
     else if (CWKeyer::MsgConfigureCWKeyer::match(cmd))
     {
         const CWKeyer::MsgConfigureCWKeyer& cfg = (CWKeyer::MsgConfigureCWKeyer&) cmd;
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendCWSettings(cfg.getSettings());
         }
         return true;
     }
     else if (DSPConfigureAudio::match(cmd))
     {
         DSPConfigureAudio& cfg = (DSPConfigureAudio&) cmd;
         uint32_t sampleRate = cfg.getSampleRate();
         DSPConfigureAudio::AudioType audioType = cfg.getAudioType();
         qDebug() << "NFMMod::handleMessage: DSPConfigureAudio:"
                 << " sampleRate: " << sampleRate
                 << " audioType: " << audioType;
         if (audioType == DSPConfigureAudio::AudioInput)
         {
             if (sampleRate != m_audioSampleRate) {
                 applyAudioSampleRate(sampleRate);
             }
         }
         else if (audioType == DSPConfigureAudio::AudioOutput)
         {
             if (sampleRate != m_audioSampleRate) {
                 applyFeedbackAudioSampleRate(sampleRate);
             }
         }
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         return false;
     }
 }
levelChanged
void NFMMod::levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples) signal
Level changed
Parameters
rmsLevel RMS level in range 0.0 - 1.0
peakLevel Peak level in range 0.0 - 1.0
numSamples Number of audio samples analyzed
Referenced by calculateLevel().
modulateSample()
void NFMMod::modulateSample () private
Definition at line 177 of file nfmmod.cpp.
References calculateLevel(), cos(), Bandpass< Type >::filter(), m_audioBufferFill, m_audioSampleRate, m_bandpass, m_ctcssNco, NFMModSettings::m_ctcssOn, NFMModSettings::m_feedbackAudioEnable, NFMModSettings::m_feedbackVolumeFactor, NFMModSettings::m_fmDeviation, m_modPhasor, m_modSample, M_PI, m_settings, NCOF::next(), pullAF(), pushFeedback(), SDR_TX_SCALEF, and sin().
Referenced by pull().
 {
     Real t;
     pullAF(t);
     if (m_settings.m_feedbackAudioEnable) {
         pushFeedback(t * m_settings.m_feedbackVolumeFactor * 16384.0f);
     }
     calculateLevel(t);
     m_audioBufferFill++;
     if (m_settings.m_ctcssOn)
     {
         m_modPhasor += (m_settings.m_fmDeviation / (float) m_audioSampleRate) * (0.85f * m_bandpass.filter(t) + 0.15f * 378.0f * m_ctcssNco.next()) * (M_PI / 378.0f);
     }
     else
     {
         // 378 = 302 * 1.25; 302 = number of filter taps (established experimentally)
         m_modPhasor += (m_settings.m_fmDeviation / (float) m_audioSampleRate) * m_bandpass.filter(t) * (M_PI / 378.0f);
     }
     m_modSample.real(cos(m_modPhasor) * 0.891235351562f * SDR_TX_SCALEF); // -1 dB
     m_modSample.imag(sin(m_modPhasor) * 0.891235351562f * SDR_TX_SCALEF);
 }
networkManagerFinished
void NFMMod::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 1023 of file nfmmod.cpp.
Referenced by NFMMod(), and ~NFMMod().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "NFMMod::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("NFMMod::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openFileStream()
void NFMMod::openFileStream () private
Definition at line 460 of file nfmmod.cpp.
References NFMMod::MsgReportFileSourceStreamData::create(), BasebandSampleSource::getMessageQueueToGUI(), m_fileName, m_fileSize, m_ifstream, m_recordLength, m_sampleRate, and MessageQueue::push().
Referenced by handleMessage().
 {
     if (m_ifstream.is_open()) {
         m_ifstream.close();
     }
     m_ifstream.open(m_fileName.toStdString().c_str(), std::ios::binary | std::ios::ate);
     m_fileSize = m_ifstream.tellg();
     m_ifstream.seekg(0,std::ios_base::beg);
     m_sampleRate = 48000; // fixed rate
     m_recordLength = m_fileSize / (sizeof(Real) * m_sampleRate);
     qDebug() << "NFMMod::openFileStream: " << m_fileName.toStdString().c_str()
             << " fileSize: " << m_fileSize << "bytes"
             << " length: " << m_recordLength << " seconds";
     MsgReportFileSourceStreamData *report;
     report = MsgReportFileSourceStreamData::create(m_sampleRate, m_recordLength);
     getMessageQueueToGUI()->push(report);
 }
processOneSample()
void NFMMod::processOneSample (Complex & ci) private
Definition at line 294 of file nfmmod.cpp.
References AudioFifo::clear(), m_feedbackAudioBuffer, m_feedbackAudioBufferFill, m_feedbackAudioFifo, m_feedbackInterpolatorDistance, and AudioFifo::write().
Referenced by pushFeedback().
 {
     m_feedbackAudioBuffer[m_feedbackAudioBufferFill].l = ci.real();
     m_feedbackAudioBuffer[m_feedbackAudioBufferFill].r = ci.imag();
     ++m_feedbackAudioBufferFill;
     if (m_feedbackAudioBufferFill >= m_feedbackAudioBuffer.size())
     {
         uint res = m_feedbackAudioFifo.write((const quint8*)&m_feedbackAudioBuffer[0], m_feedbackAudioBufferFill);
         if (res != m_feedbackAudioBufferFill)
         {
             qDebug("AMDemod::pushFeedback: %u/%u audio samples written m_feedbackInterpolatorDistance: %f",
                 res, m_feedbackAudioBufferFill, m_feedbackInterpolatorDistance);
             m_feedbackAudioFifo.clear();
         }
         m_feedbackAudioBufferFill = 0;
     }
 }
pull()
void NFMMod::pull (Sample & sample) virtual
Implements BasebandSampleSource.
Definition at line 119 of file nfmmod.cpp.
References MovingAverageUtil< T, Total, N >::asDouble(), Interpolator::decimate(), Interpolator::interpolate(), m_carrierNco, NFMModSettings::m_channelMute, Sample::m_imag, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_magsq, m_modSample, m_movingAverage, Sample::m_real, m_settings, m_settingsMutex, modulateSample(), NCO::nextIQ(), and SDR_TX_SCALED.
Referenced by destroy().
 {
     if (m_settings.m_channelMute)
     {
         sample.m_real = 0.0f;
         sample.m_imag = 0.0f;
         return;
     }
     Complex ci;
     m_settingsMutex.lock();
     if (m_interpolatorDistance > 1.0f) // decimate
     {
         modulateSample();
         while (!m_interpolator.decimate(&m_interpolatorDistanceRemain, m_modSample, &ci))
         {
             modulateSample();
         }
     }
     else
     {
         if (m_interpolator.interpolate(&m_interpolatorDistanceRemain, m_modSample, &ci))
         {
             modulateSample();
         }
     }
     m_interpolatorDistanceRemain += m_interpolatorDistance;
     ci *= m_carrierNco.nextIQ(); // shift to carrier frequency
     m_settingsMutex.unlock();
     double magsq = ci.real() * ci.real() + ci.imag() * ci.imag();
     magsq /= (SDR_TX_SCALED*SDR_TX_SCALED);
     m_movingAverage(magsq);
     m_magsq = m_movingAverage.asDouble();
     sample.m_real = (FixReal) ci.real();
     sample.m_imag = (FixReal) ci.imag();
 }
pullAF()
void NFMMod::pullAF (Real & sample) private
Definition at line 204 of file nfmmod.cpp.
References CWKeyer::getCWSmoother(), CWSmoother::getFadeSample(), CWKeyer::getSample(), m_audioBuffer, m_audioBufferFill, m_cwKeyer, m_ifstream, NFMModSettings::m_modAFInput, NFMModSettings::m_playLoop, m_settings, m_toneNco, NFMModSettings::m_volumeFactor, NCOF::next(), NFMModSettings::NFMModInputAudio, NFMModSettings::NFMModInputCWTone, NFMModSettings::NFMModInputFile, NFMModSettings::NFMModInputNone, NFMModSettings::NFMModInputTone, and NCOF::setPhase().
Referenced by modulateSample().
 {
     switch (m_settings.m_modAFInput)
     {
     case NFMModSettings::NFMModInputTone:
         sample = m_toneNco.next();
         break;
     case NFMModSettings::NFMModInputFile:
         // sox f4exb_call.wav --encoding float --endian little f4exb_call.raw
         // ffplay -f f32le -ar 48k -ac 1 f4exb_call.raw
         if (m_ifstream.is_open())
         {
             if (m_ifstream.eof())
             {
                 if (m_settings.m_playLoop)
                 {
                     m_ifstream.clear();
                     m_ifstream.seekg(0, std::ios::beg);
                 }
             }
             if (m_ifstream.eof())
             {
                 sample = 0.0f;
             }
             else
             {
                 m_ifstream.read(reinterpret_cast<char*>(&sample), sizeof(Real));
                 sample *= m_settings.m_volumeFactor;
             }
         }
         else
         {
             sample = 0.0f;
         }
         break;
     case NFMModSettings::NFMModInputAudio:
         sample = ((m_audioBuffer[m_audioBufferFill].l + m_audioBuffer[m_audioBufferFill].r) / 65536.0f) * m_settings.m_volumeFactor;
         break;
     case NFMModSettings::NFMModInputCWTone:
         Real fadeFactor;
         if (m_cwKeyer.getSample())
         {
             m_cwKeyer.getCWSmoother().getFadeSample(true, fadeFactor);
             sample = m_toneNco.next() * fadeFactor;
         }
         else
         {
             if (m_cwKeyer.getCWSmoother().getFadeSample(false, fadeFactor))
             {
                 sample = m_toneNco.next() * fadeFactor;
             }
             else
             {
                 sample = 0.0f;
                 m_toneNco.setPhase(0);
             }
         }
         break;
     case NFMModSettings::NFMModInputNone:
     default:
         sample = 0.0f;
         break;
     }
 }
pullAudio()
void NFMMod::pullAudio (int nbSamples) virtual
Reimplemented from BasebandSampleSource.
Definition at line 164 of file nfmmod.cpp.
References m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_basebandSampleRate, and AudioFifo::read().
Referenced by destroy().
 {
     unsigned int nbSamplesAudio = nbSamples * ((Real) m_audioSampleRate / (Real) m_basebandSampleRate);
     if (nbSamplesAudio > m_audioBuffer.size())
     {
         m_audioBuffer.resize(nbSamplesAudio);
     }
     m_audioFifo.read(reinterpret_cast<quint8*>(&m_audioBuffer[0]), nbSamplesAudio);
     m_audioBufferFill = 0;
 }
pushFeedback()
void NFMMod::pushFeedback (Real sample) private
Definition at line 271 of file nfmmod.cpp.
References Interpolator::decimate(), Interpolator::interpolate(), m_feedbackInterpolator, m_feedbackInterpolatorDistance, m_feedbackInterpolatorDistanceRemain, and processOneSample().
Referenced by modulateSample().
 {
     Complex c(sample, sample);
     Complex ci;
     if (m_feedbackInterpolatorDistance < 1.0f) // interpolate
     {
         while (!m_feedbackInterpolator.interpolate(&m_feedbackInterpolatorDistanceRemain, c, &ci))
         {
             processOneSample(ci);
             m_feedbackInterpolatorDistanceRemain += m_feedbackInterpolatorDistance;
         }
     }
     else // decimate
     {
         if (m_feedbackInterpolator.decimate(&m_feedbackInterpolatorDistanceRemain, c, &ci))
         {
             processOneSample(ci);
             m_feedbackInterpolatorDistanceRemain += m_feedbackInterpolatorDistance;
         }
     }
 }
seekFileStream()
void NFMMod::seekFileStream (int seekPercentage) private
Definition at line 482 of file nfmmod.cpp.
References m_ifstream, m_recordLength, m_sampleRate, and m_settingsMutex.
Referenced by handleMessage().
 {
     QMutexLocker mutexLocker(&m_settingsMutex);
     if (m_ifstream.is_open())
     {
         int seekPoint = ((m_recordLength * seekPercentage) / 100) * m_sampleRate;
         seekPoint *= sizeof(Real);
         m_ifstream.clear();
         m_ifstream.seekg(seekPoint, std::ios::beg);
     }
 }
serialize()
QByteArray NFMMod::serialize () const virtual
Implements ChannelAPI.
Definition at line 697 of file nfmmod.cpp.
References m_settings, and NFMModSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
start()
void NFMMod::start () virtual
Implements BasebandSampleSource.
Definition at line 334 of file nfmmod.cpp.
References applyChannelSettings(), AudioFifo::clear(), m_audioFifo, m_basebandSampleRate, m_inputFrequencyOffset, and m_outputSampleRate.
Referenced by destroy().
 {
     qDebug() << "NFMMod::start: m_outputSampleRate: " << m_outputSampleRate
             << " m_inputFrequencyOffset: " << m_inputFrequencyOffset;
     m_audioFifo.clear();
     applyChannelSettings(m_basebandSampleRate, m_outputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void NFMMod::stop () virtual
Implements BasebandSampleSource.
Definition at line 343 of file nfmmod.cpp.
Referenced by destroy().
 {
 }
webapiFormatChannelReport()
void NFMMod::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 903 of file nfmmod.cpp.
References CalcDb::dbPower(), getMagSq(), SWGSDRangel::SWGChannelReport::getNfmModReport(), m_audioSampleRate, m_outputSampleRate, SWGSDRangel::SWGNFMModReport::setAudioSampleRate(), SWGSDRangel::SWGNFMModReport::setChannelPowerDb(), and SWGSDRangel::SWGNFMModReport::setChannelSampleRate().
Referenced by webapiReportGet().
 {
     response.getNfmModReport()->setChannelPowerDb(CalcDb::dbPower(getMagSq()));
     response.getNfmModReport()->setAudioSampleRate(m_audioSampleRate);
     response.getNfmModReport()->setChannelSampleRate(m_outputSampleRate);
 }
webapiFormatChannelSettings()
void NFMMod::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const NFMModSettings & settings) private
Definition at line 852 of file nfmmod.cpp.
References SWGSDRangel::SWGNFMModSettings::getAudioDeviceName(), SWGSDRangel::SWGNFMModSettings::getCwKeyer(), SWGSDRangel::SWGChannelSettings::getNfmModSettings(), SWGSDRangel::SWGNFMModSettings::getReverseApiAddress(), CWKeyer::getSettings(), SWGSDRangel::SWGNFMModSettings::getTitle(), NFMModSettings::m_afBandwidth, NFMModSettings::m_audioDeviceName, NFMModSettings::m_channelMute, NFMModSettings::m_ctcssIndex, NFMModSettings::m_ctcssOn, m_cwKeyer, NFMModSettings::m_fmDeviation, NFMModSettings::m_inputFrequencyOffset, NFMModSettings::m_modAFInput, NFMModSettings::m_playLoop, NFMModSettings::m_reverseAPIAddress, NFMModSettings::m_reverseAPIChannelIndex, NFMModSettings::m_reverseAPIDeviceIndex, NFMModSettings::m_reverseAPIPort, NFMModSettings::m_rfBandwidth, NFMModSettings::m_rgbColor, NFMModSettings::m_title, NFMModSettings::m_toneFrequency, NFMModSettings::m_useReverseAPI, NFMModSettings::m_volumeFactor, CWKeyerSettings::m_wpm, SWGSDRangel::SWGNFMModSettings::setAfBandwidth(), SWGSDRangel::SWGNFMModSettings::setAudioDeviceName(), SWGSDRangel::SWGNFMModSettings::setChannelMute(), SWGSDRangel::SWGNFMModSettings::setCtcssIndex(), SWGSDRangel::SWGNFMModSettings::setCtcssOn(), SWGSDRangel::SWGNFMModSettings::setCwKeyer(), SWGSDRangel::SWGNFMModSettings::setFmDeviation(), SWGSDRangel::SWGNFMModSettings::setInputFrequencyOffset(), SWGSDRangel::SWGNFMModSettings::setModAfInput(), SWGSDRangel::SWGNFMModSettings::setPlayLoop(), SWGSDRangel::SWGNFMModSettings::setReverseApiAddress(), SWGSDRangel::SWGNFMModSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGNFMModSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGNFMModSettings::setReverseApiPort(), SWGSDRangel::SWGNFMModSettings::setRfBandwidth(), SWGSDRangel::SWGNFMModSettings::setRgbColor(), SWGSDRangel::SWGNFMModSettings::setTitle(), SWGSDRangel::SWGNFMModSettings::setToneFrequency(), SWGSDRangel::SWGNFMModSettings::setUseReverseApi(), SWGSDRangel::SWGNFMModSettings::setVolumeFactor(), SWGSDRangel::SWGCWKeyerSettings::setWpm(), and CWKeyer::webapiFormatChannelSettings().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getNfmModSettings()->setAfBandwidth(settings.m_afBandwidth);
     response.getNfmModSettings()->setChannelMute(settings.m_channelMute ? 1 : 0);
     response.getNfmModSettings()->setCtcssIndex(settings.m_ctcssIndex);
     response.getNfmModSettings()->setCtcssOn(settings.m_ctcssOn ? 1 : 0);
     response.getNfmModSettings()->setFmDeviation(settings.m_fmDeviation);
     response.getNfmModSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getNfmModSettings()->setModAfInput((int) settings.m_modAFInput);
     response.getNfmModSettings()->setPlayLoop(settings.m_playLoop ? 1 : 0);
     response.getNfmModSettings()->setRfBandwidth(settings.m_rfBandwidth);
     response.getNfmModSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getNfmModSettings()->getTitle()) {
         *response.getNfmModSettings()->getTitle() = settings.m_title;
     } else {
         response.getNfmModSettings()->setTitle(new QString(settings.m_title));
     }
     response.getNfmModSettings()->setToneFrequency(settings.m_toneFrequency);
     response.getNfmModSettings()->setVolumeFactor(settings.m_volumeFactor);
     if (!response.getNfmModSettings()->getCwKeyer()) {
         response.getNfmModSettings()->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings);
     }
     SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = response.getNfmModSettings()->getCwKeyer();
     const CWKeyerSettings& cwKeyerSettings = m_cwKeyer.getSettings();
     m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     if (response.getNfmModSettings()->getAudioDeviceName()) {
         *response.getNfmModSettings()->getAudioDeviceName() = settings.m_audioDeviceName;
     } else {
         response.getNfmModSettings()->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     apiCwKeyerSettings->setWpm(cwKeyerSettings.m_wpm);
     response.getNfmModSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getNfmModSettings()->getReverseApiAddress()) {
         *response.getNfmModSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getNfmModSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getNfmModSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getNfmModSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getNfmModSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int NFMMod::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 841 of file nfmmod.cpp.
References SWGSDRangel::SWGChannelReport::getNfmModReport(), SWGSDRangel::SWGNFMModReport::init(), SWGSDRangel::SWGChannelReport::setNfmModReport(), and webapiFormatChannelReport().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setNfmModReport(new SWGSDRangel::SWGNFMModReport());
     response.getNfmModReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendCWSettings()
void NFMMod::webapiReverseSendCWSettings (const CWKeyerSettings & settings) private
Definition at line 992 of file nfmmod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), SWGSDRangel::SWGNFMModSettings::getCwKeyer(), SWGSDRangel::SWGChannelSettings::getNfmModSettings(), m_cwKeyer, m_networkManager, m_networkRequest, NFMModSettings::m_reverseAPIAddress, NFMModSettings::m_reverseAPIChannelIndex, NFMModSettings::m_reverseAPIDeviceIndex, NFMModSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGNFMModSettings::setCwKeyer(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGChannelSettings::setNfmModSettings(), and CWKeyer::webapiFormatChannelSettings().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setChannelType(new QString("NFMMod"));
     swgChannelSettings->setNfmModSettings(new SWGSDRangel::SWGNFMModSettings());
     SWGSDRangel::SWGNFMModSettings *swgNFModSettings = swgChannelSettings->getNfmModSettings();
     swgNFModSettings->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings());
     SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = swgNFModSettings->getCwKeyer();
     m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex)
             .arg(m_settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiReverseSendSettings()
void NFMMod::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const NFMModSettings & settings, bool force) private
Definition at line 910 of file nfmmod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), SWGSDRangel::SWGNFMModSettings::getCwKeyer(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), SWGSDRangel::SWGChannelSettings::getNfmModSettings(), CWKeyer::getSettings(), NFMModSettings::m_afBandwidth, NFMModSettings::m_audioDeviceName, NFMModSettings::m_channelMute, NFMModSettings::m_ctcssIndex, NFMModSettings::m_ctcssOn, m_cwKeyer, NFMModSettings::m_fmDeviation, NFMModSettings::m_inputFrequencyOffset, NFMModSettings::m_modAFInput, m_networkManager, m_networkRequest, NFMModSettings::m_playLoop, NFMModSettings::m_reverseAPIAddress, NFMModSettings::m_reverseAPIChannelIndex, NFMModSettings::m_reverseAPIDeviceIndex, NFMModSettings::m_reverseAPIPort, NFMModSettings::m_rfBandwidth, NFMModSettings::m_rgbColor, NFMModSettings::m_title, NFMModSettings::m_toneFrequency, NFMModSettings::m_volumeFactor, SWGSDRangel::SWGNFMModSettings::setAfBandwidth(), SWGSDRangel::SWGNFMModSettings::setAudioDeviceName(), SWGSDRangel::SWGNFMModSettings::setChannelMute(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGNFMModSettings::setCtcssIndex(), SWGSDRangel::SWGNFMModSettings::setCtcssOn(), SWGSDRangel::SWGNFMModSettings::setCwKeyer(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGNFMModSettings::setFmDeviation(), SWGSDRangel::SWGNFMModSettings::setInputFrequencyOffset(), SWGSDRangel::SWGNFMModSettings::setModAfInput(), SWGSDRangel::SWGChannelSettings::setNfmModSettings(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGNFMModSettings::setPlayLoop(), SWGSDRangel::SWGNFMModSettings::setRfBandwidth(), SWGSDRangel::SWGNFMModSettings::setRgbColor(), SWGSDRangel::SWGNFMModSettings::setTitle(), SWGSDRangel::SWGNFMModSettings::setToneFrequency(), SWGSDRangel::SWGNFMModSettings::setVolumeFactor(), and CWKeyer::webapiFormatChannelSettings().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("NFMMod"));
     swgChannelSettings->setNfmModSettings(new SWGSDRangel::SWGNFMModSettings());
     SWGSDRangel::SWGNFMModSettings *swgNFMModSettings = swgChannelSettings->getNfmModSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("channelMute") || force) {
         swgNFMModSettings->setChannelMute(settings.m_channelMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgNFMModSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("modAFInput") || force) {
         swgNFMModSettings->setModAfInput((int) settings.m_modAFInput);
     }
     if (channelSettingsKeys.contains("audioDeviceName") || force) {
         swgNFMModSettings->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     if (channelSettingsKeys.contains("playLoop") || force) {
         swgNFMModSettings->setPlayLoop(settings.m_playLoop ? 1 : 0);
     }
     if (channelSettingsKeys.contains("afBandwidth") || force) {
         swgNFMModSettings->setAfBandwidth(settings.m_afBandwidth);
     }
     if (channelSettingsKeys.contains("fmDeviation") || force) {
         swgNFMModSettings->setFmDeviation(settings.m_fmDeviation);
     }
     if (channelSettingsKeys.contains("rfBandwidth") || force) {
         swgNFMModSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgNFMModSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgNFMModSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("toneFrequency") || force) {
         swgNFMModSettings->setToneFrequency(settings.m_toneFrequency);
     }
     if (channelSettingsKeys.contains("volumeFactor") || force) {
         swgNFMModSettings->setVolumeFactor(settings.m_volumeFactor);
     }
     if (channelSettingsKeys.contains("ctcssOn") || force) {
         swgNFMModSettings->setCtcssOn(settings.m_ctcssOn ? 1 : 0);
     }
     if (channelSettingsKeys.contains("ctcssIndex") || force) {
         swgNFMModSettings->setCtcssIndex(settings.m_ctcssIndex);
     }
     if (force)
     {
         const CWKeyerSettings& cwKeyerSettings = m_cwKeyer.getSettings();
         swgNFMModSettings->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings());
         SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = swgNFMModSettings->getCwKeyer();
         m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int NFMMod::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 722 of file nfmmod.cpp.
References SWGSDRangel::SWGChannelSettings::getNfmModSettings(), SWGSDRangel::SWGNFMModSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setNfmModSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setNfmModSettings(new SWGSDRangel::SWGNFMModSettings());
     response.getNfmModSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int NFMMod::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 733 of file nfmmod.cpp.
References NFMMod::MsgConfigureNFMMod::create(), CWKeyer::MsgConfigureCWKeyer::create(), NFMMod::MsgConfigureChannelizer::create(), SWGSDRangel::SWGNFMModSettings::getAfBandwidth(), SWGSDRangel::SWGNFMModSettings::getChannelMute(), SWGSDRangel::SWGNFMModSettings::getCtcssIndex(), SWGSDRangel::SWGNFMModSettings::getCtcssOn(), SWGSDRangel::SWGNFMModSettings::getCwKeyer(), SWGSDRangel::SWGNFMModSettings::getFmDeviation(), SWGSDRangel::SWGNFMModSettings::getInputFrequencyOffset(), CWKeyer::getInputMessageQueue(), SWGSDRangel::SWGNFMModSettings::getModAfInput(), SWGSDRangel::SWGChannelSettings::getNfmModSettings(), SWGSDRangel::SWGNFMModSettings::getPlayLoop(), SWGSDRangel::SWGNFMModSettings::getReverseApiAddress(), SWGSDRangel::SWGNFMModSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGNFMModSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGNFMModSettings::getReverseApiPort(), SWGSDRangel::SWGNFMModSettings::getRfBandwidth(), SWGSDRangel::SWGNFMModSettings::getRgbColor(), CWKeyer::getSettings(), SWGSDRangel::SWGNFMModSettings::getTitle(), SWGSDRangel::SWGNFMModSettings::getToneFrequency(), SWGSDRangel::SWGNFMModSettings::getUseReverseApi(), SWGSDRangel::SWGNFMModSettings::getVolumeFactor(), NFMModSettings::m_afBandwidth, m_audioSampleRate, NFMModSettings::m_channelMute, NFMModSettings::m_ctcssIndex, NFMModSettings::m_ctcssOn, m_cwKeyer, NFMModSettings::m_fmDeviation, BasebandSampleSource::m_guiMessageQueue, NFMModSettings::m_inputFrequencyOffset, BasebandSampleSource::m_inputMessageQueue, NFMModSettings::m_modAFInput, NFMModSettings::m_playLoop, NFMModSettings::m_reverseAPIAddress, NFMModSettings::m_reverseAPIChannelIndex, NFMModSettings::m_reverseAPIDeviceIndex, NFMModSettings::m_reverseAPIPort, NFMModSettings::m_rfBandwidth, NFMModSettings::m_rgbColor, m_settings, NFMModSettings::m_title, NFMModSettings::m_toneFrequency, NFMModSettings::m_useReverseAPI, NFMModSettings::m_volumeFactor, MessageQueue::push(), webapiFormatChannelSettings(), and CWKeyer::webapiSettingsPutPatch().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     NFMModSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
 //    for (int i = 0; i < channelSettingsKeys.size(); i++) {
 //        qDebug("NFMMod::webapiSettingsPutPatch: settingKey: %s", qPrintable(channelSettingsKeys.at(i)));
 //    }
     if (channelSettingsKeys.contains("afBandwidth")) {
         settings.m_afBandwidth = response.getNfmModSettings()->getAfBandwidth();
     }
     if (channelSettingsKeys.contains("channelMute")) {
         settings.m_channelMute = response.getNfmModSettings()->getChannelMute() != 0;
     }
     if (channelSettingsKeys.contains("ctcssIndex")) {
         settings.m_ctcssIndex = response.getNfmModSettings()->getCtcssIndex();
     }
     if (channelSettingsKeys.contains("ctcssOn")) {
         settings.m_ctcssOn = response.getNfmModSettings()->getCtcssOn() != 0;
     }
     if (channelSettingsKeys.contains("fmDeviation")) {
         settings.m_fmDeviation = response.getNfmModSettings()->getFmDeviation();
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getNfmModSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("modAFInput")) {
         settings.m_modAFInput = (NFMModSettings::NFMModInputAF) response.getNfmModSettings()->getModAfInput();
     }
     if (channelSettingsKeys.contains("playLoop")) {
         settings.m_playLoop = response.getNfmModSettings()->getPlayLoop() != 0;
     }
     if (channelSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getNfmModSettings()->getRfBandwidth();
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getNfmModSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getNfmModSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("toneFrequency")) {
         settings.m_toneFrequency = response.getNfmModSettings()->getToneFrequency();
     }
     if (channelSettingsKeys.contains("volumeFactor")) {
         settings.m_volumeFactor = response.getNfmModSettings()->getVolumeFactor();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getNfmModSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getNfmModSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getNfmModSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getNfmModSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getNfmModSettings()->getReverseApiChannelIndex();
     }
     if (channelSettingsKeys.contains("cwKeyer"))
     {
         SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = response.getNfmModSettings()->getCwKeyer();
         CWKeyerSettings cwKeyerSettings = m_cwKeyer.getSettings();
         m_cwKeyer.webapiSettingsPutPatch(channelSettingsKeys, cwKeyerSettings, apiCwKeyerSettings);
         CWKeyer::MsgConfigureCWKeyer *msgCwKeyer = CWKeyer::MsgConfigureCWKeyer::create(cwKeyerSettings, force);
         m_cwKeyer.getInputMessageQueue()->push(msgCwKeyer);
         if (m_guiMessageQueue) // forward to GUI if any
         {
             CWKeyer::MsgConfigureCWKeyer *msgCwKeyerToGUI = CWKeyer::MsgConfigureCWKeyer::create(cwKeyerSettings, force);
             m_guiMessageQueue->push(msgCwKeyerToGUI);
         }
     }
     if (frequencyOffsetChanged)
     {
         NFMMod::MsgConfigureChannelizer *msgChan = NFMMod::MsgConfigureChannelizer::create(
                 m_audioSampleRate, settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(msgChan);
     }
     MsgConfigureNFMMod *msg = MsgConfigureNFMMod::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureNFMMod *msgToGUI = MsgConfigureNFMMod::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_afInput
NFMModSettings::NFMModInputAF NFMMod::m_afInput private
Definition at line 320 of file nfmmod.h.
m_audioBuffer
AudioVector NFMMod::m_audioBuffer private
Definition at line 302 of file nfmmod.h.
Referenced by NFMMod(), pullAF(), and pullAudio().
m_audioBufferFill
uint NFMMod::m_audioBufferFill private
Definition at line 303 of file nfmmod.h.
Referenced by modulateSample(), NFMMod(), pullAF(), and pullAudio().
m_audioFifo
AudioFifo NFMMod::m_audioFifo private
Definition at line 304 of file nfmmod.h.
Referenced by applySettings(), NFMMod(), pullAudio(), start(), and ~NFMMod().
m_audioSampleRate
quint32 NFMMod::m_audioSampleRate private
Definition at line 301 of file nfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applyFeedbackAudioSampleRate(), applySettings(), handleMessage(), modulateSample(), NFMMod(), pullAudio(), webapiFormatChannelReport(), and webapiSettingsPutPatch().
m_bandpass
Bandpass<Real> NFMMod::m_bandpass private
Definition at line 296 of file nfmmod.h.
Referenced by applyAudioSampleRate(), applySettings(), and modulateSample().
m_basebandSampleRate
int NFMMod::m_basebandSampleRate private
Definition at line 274 of file nfmmod.h.
Referenced by applyChannelSettings(), NFMMod(), pullAudio(), and start().
m_carrierNco
NCO NFMMod::m_carrierNco private
Definition at line 279 of file nfmmod.h.
Referenced by applyChannelSettings(), and pull().
m_channelId
const QString NFMMod::m_channelId = "NFMMod" static
Definition at line 252 of file nfmmod.h.
Referenced by NFMModPlugin::initPlugin(), and NFMMod().
m_channelIdURI
const QString NFMMod::m_channelIdURI = "sdrangel.channeltx.modnfm" static
Definition at line 251 of file nfmmod.h.
Referenced by NFMModPlugin::initPlugin(), and NFMModGUI::NFMModGUI().
m_channelizer
UpChannelizer* NFMMod::m_channelizer private
Definition at line 272 of file nfmmod.h.
Referenced by handleMessage(), NFMMod(), and ~NFMMod().
m_ctcssNco
NCOF NFMMod::m_ctcssNco private
Definition at line 281 of file nfmmod.h.
Referenced by applyAudioSampleRate(), applySettings(), modulateSample(), and NFMMod().
m_cwKeyer
CWKeyer NFMMod::m_cwKeyer private
Definition at line 324 of file nfmmod.h.
Referenced by applyAudioSampleRate(), getCWKeyer(), NFMMod(), pullAF(), webapiFormatChannelSettings(), webapiReverseSendCWSettings(), webapiReverseSendSettings(), and webapiSettingsPutPatch().
m_deviceAPI
DeviceAPI* NFMMod::m_deviceAPI private
Definition at line 270 of file nfmmod.h.
Referenced by NFMMod(), and ~NFMMod().
m_feedbackAudioBuffer
AudioVector NFMMod::m_feedbackAudioBuffer private
Definition at line 307 of file nfmmod.h.
Referenced by NFMMod(), and processOneSample().
m_feedbackAudioBufferFill
uint NFMMod::m_feedbackAudioBufferFill private
Definition at line 308 of file nfmmod.h.
Referenced by NFMMod(), and processOneSample().
m_feedbackAudioFifo
AudioFifo NFMMod::m_feedbackAudioFifo private
Definition at line 309 of file nfmmod.h.
Referenced by applySettings(), NFMMod(), processOneSample(), and ~NFMMod().
m_feedbackAudioSampleRate
quint32 NFMMod::m_feedbackAudioSampleRate private
Definition at line 306 of file nfmmod.h.
Referenced by applyAudioSampleRate(), applyFeedbackAudioSampleRate(), applySettings(), and NFMMod().
m_feedbackInterpolator
Interpolator NFMMod::m_feedbackInterpolator private
Definition at line 290 of file nfmmod.h.
Referenced by applyFeedbackAudioSampleRate(), and pushFeedback().
m_feedbackInterpolatorConsumed
bool NFMMod::m_feedbackInterpolatorConsumed private
Definition at line 293 of file nfmmod.h.
Referenced by applyFeedbackAudioSampleRate().
m_feedbackInterpolatorDistance
Real NFMMod::m_feedbackInterpolatorDistance private
Definition at line 291 of file nfmmod.h.
Referenced by applyFeedbackAudioSampleRate(), processOneSample(), and pushFeedback().
m_feedbackInterpolatorDistanceRemain
Real NFMMod::m_feedbackInterpolatorDistanceRemain private
Definition at line 292 of file nfmmod.h.
Referenced by applyFeedbackAudioSampleRate(), and pushFeedback().
m_fileName
QString NFMMod::m_fileName private
Definition at line 315 of file nfmmod.h.
Referenced by NFMMod::MsgConfigureFileSourceName::getFileName(), handleMessage(), and openFileStream().
m_fileSize
quint64 NFMMod::m_fileSize private
raw file size (bytes)
Definition at line 316 of file nfmmod.h.
Referenced by handleMessage(), and openFileStream().
m_ifstream
std::ifstream NFMMod::m_ifstream private
Definition at line 314 of file nfmmod.h.
Referenced by handleMessage(), openFileStream(), pullAF(), and seekFileStream().
m_inputFrequencyOffset
int NFMMod::m_inputFrequencyOffset private
Definition at line 276 of file nfmmod.h.
Referenced by applyChannelSettings(), NFMMod(), and start().
m_interpolator
Interpolator NFMMod::m_interpolator private
Definition at line 285 of file nfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and pull().
m_interpolatorConsumed
bool NFMMod::m_interpolatorConsumed private
Definition at line 288 of file nfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), and applySettings().
m_interpolatorDistance
Real NFMMod::m_interpolatorDistance private
Definition at line 286 of file nfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and pull().
m_interpolatorDistanceRemain
Real NFMMod::m_interpolatorDistanceRemain private
Definition at line 287 of file nfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and pull().
m_levelCalcCount
quint32 NFMMod::m_levelCalcCount private
Definition at line 321 of file nfmmod.h.
Referenced by calculateLevel().
m_levelNbSamples
const int NFMMod::m_levelNbSamples = 480 static private
Definition at line 329 of file nfmmod.h.
Referenced by calculateLevel().
m_levelSum
Real NFMMod::m_levelSum private
Definition at line 323 of file nfmmod.h.
Referenced by calculateLevel().
m_lowpass
Lowpass<Real> NFMMod::m_lowpass private
Definition at line 295 of file nfmmod.h.
Referenced by applyAudioSampleRate(), applySettings(), and NFMMod().
m_magsq
double NFMMod::m_magsq private
Definition at line 298 of file nfmmod.h.
Referenced by getMagSq(), NFMMod(), and pull().
m_modPhasor
float NFMMod::m_modPhasor private
baseband modulator phasor
Definition at line 282 of file nfmmod.h.
Referenced by modulateSample().
m_modSample
Complex NFMMod::m_modSample private
Definition at line 283 of file nfmmod.h.
Referenced by modulateSample(), and pull().
m_movingAverage
MovingAverageUtil<double, double, 16> NFMMod::m_movingAverage private
Definition at line 299 of file nfmmod.h.
Referenced by pull().
m_networkManager
QNetworkAccessManager* NFMMod::m_networkManager private
Definition at line 326 of file nfmmod.h.
Referenced by NFMMod(), webapiReverseSendCWSettings(), webapiReverseSendSettings(), and ~NFMMod().
m_networkRequest
QNetworkRequest NFMMod::m_networkRequest private
Definition at line 327 of file nfmmod.h.
Referenced by webapiReverseSendCWSettings(), and webapiReverseSendSettings().
m_outputSampleRate
int NFMMod::m_outputSampleRate private
Definition at line 275 of file nfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), NFMMod(), start(), and webapiFormatChannelReport().
m_peakLevel
Real NFMMod::m_peakLevel private
Definition at line 322 of file nfmmod.h.
Referenced by calculateLevel().
m_recordLength
quint32 NFMMod::m_recordLength private
record length in seconds computed from file size
Definition at line 317 of file nfmmod.h.
Referenced by NFMMod::MsgReportFileSourceStreamData::getRecordLength(), openFileStream(), and seekFileStream().
m_sampleBuffer
SampleVector NFMMod::m_sampleBuffer private
Definition at line 311 of file nfmmod.h.
m_sampleRate
int NFMMod::m_sampleRate private
Definition at line 318 of file nfmmod.h.
Referenced by NFMMod::MsgConfigureChannelizer::getSampleRate(), NFMMod::MsgReportFileSourceStreamData::getSampleRate(), openFileStream(), and seekFileStream().
m_settings
NFMModSettings NFMMod::m_settings private
Definition at line 277 of file nfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), deserialize(), handleMessage(), modulateSample(), NFMMod(), pull(), pullAF(), serialize(), webapiReverseSendCWSettings(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex NFMMod::m_settingsMutex private
Definition at line 312 of file nfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applyFeedbackAudioSampleRate(), applySettings(), pull(), and seekFileStream().
m_threadedChannelizer
ThreadedBasebandSampleSource* NFMMod::m_threadedChannelizer private
Definition at line 271 of file nfmmod.h.
Referenced by NFMMod(), and ~NFMMod().
m_toneNco
NCOF NFMMod::m_toneNco private
Definition at line 280 of file nfmmod.h.
Referenced by applyAudioSampleRate(), applySettings(), NFMMod(), and pullAF().
The documentation for this class was generated from the following files:
plugins/channeltx/modnfm/nfmmod.h
plugins/channeltx/modnfm/nfmmod.cpp