SDRAngel: TestMIThread::MsgStartStop Class Reference
TestMIThread::MsgStartStop Class Reference
#include <testmithread.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 42 of file testmithread.h.
Constructor & Destructor Documentation
MsgStartStop()
TestMIThread::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 55 of file testmithread.h.
References TestMIThread::setAMModulation(), TestMIThread::setAmplitudeBits(), TestMIThread::setBitSize(), TestMIThread::setDCFactor(), TestMIThread::setFcPos(), TestMIThread::setFMDeviation(), TestMIThread::setFrequencyShift(), TestMIThread::setIFactor(), TestMIThread::setLog2Decimation(), TestMIThread::setModulation(), TestMIThread::setPattern0(), TestMIThread::setPattern1(), TestMIThread::setPattern2(), TestMIThread::setPhaseImbalance(), TestMIThread::setQFactor(), TestMIThread::setSamplerate(), TestMIThread::setToneFrequency(), TestMIThread::startStop(), TestMIThread::TestMIThread(), and TestMIThread::~TestMIThread().
Referenced by create().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* TestMIThread::MsgStartStop::create (bool startStop) inline static
Definition at line 48 of file testmithread.h.
References MsgStartStop().
Referenced by TestMIThread::startStop().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool TestMIThread::MsgStartStop::getStartStop () const inline
Definition at line 46 of file testmithread.h.
References m_startStop.
Referenced by TestMIThread::handleInputMessages().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool TestMIThread::MsgStartStop::m_startStop protected
Definition at line 53 of file testmithread.h.
Referenced by getStartStop().
The documentation for this class was generated from the following file:
plugins/samplemimo/testmi/testmithread.h