SDRAngel: SWGSDRangel::SWGAudioInputDevice Class Reference
SWGSDRangel::SWGAudioInputDevice Class Reference
#include <SWGAudioInputDevice.h>
Public Member Functions
SWGAudioInputDevice ()
SWGAudioInputDevice (QString *json)
virtual ~SWGAudioInputDevice ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGAudioInputDevice * fromJson (QString &jsonString) override
QString * getName ()
void setName (QString *name)
qint32 getIndex ()
void setIndex (qint32 index)
qint32 getSampleRate ()
void setSampleRate (qint32 sample_rate)
qint32 getIsSystemDefault ()
void setIsSystemDefault (qint32 is_system_default)
qint32 getDefaultUnregistered ()
void setDefaultUnregistered (qint32 default_unregistered)
float getVolume ()
void setVolume (float volume)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * name
bool m_name_isSet
qint32 index
bool m_index_isSet
qint32 sample_rate
bool m_sample_rate_isSet
qint32 is_system_default
bool m_is_system_default_isSet
qint32 default_unregistered
bool m_default_unregistered_isSet
float volume
bool m_volume_isSet
Detailed Description
Definition at line 32 of file SWGAudioInputDevice.h.
Constructor & Destructor Documentation
SWGAudioInputDevice() [1/2]
SWGSDRangel::SWGAudioInputDevice::SWGAudioInputDevice ()
Definition at line 30 of file SWGAudioInputDevice.cpp.
References default_unregistered, index, is_system_default, m_default_unregistered_isSet, m_index_isSet, m_is_system_default_isSet, m_name_isSet, m_sample_rate_isSet, m_volume_isSet, name, sample_rate, and volume.
{
     name = nullptr;
     m_name_isSet = false;
     index = 0;
     m_index_isSet = false;
     sample_rate = 0;
     m_sample_rate_isSet = false;
     is_system_default = 0;
     m_is_system_default_isSet = false;
     default_unregistered = 0;
     m_default_unregistered_isSet = false;
     volume = 0.0f;
     m_volume_isSet = false;
 }
SWGAudioInputDevice() [2/2]
SWGSDRangel::SWGAudioInputDevice::SWGAudioInputDevice (QString * json)
Definition at line 25 of file SWGAudioInputDevice.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGAudioInputDevice()
SWGSDRangel::SWGAudioInputDevice::~SWGAudioInputDevice () virtual
Definition at line 45 of file SWGAudioInputDevice.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGAudioInputDevice::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 103 of file SWGAudioInputDevice.cpp.
References asJsonObject().
Referenced by SWGSDRangel::SWGInstanceApi::instanceAudioInputDelete(), WebAPIRequestMapper::instanceAudioInputParametersService(), and SWGSDRangel::SWGInstanceApi::instanceAudioInputPatch().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGAudioInputDevice::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 114 of file SWGAudioInputDevice.cpp.
References default_unregistered, index, is_system_default, m_default_unregistered_isSet, m_index_isSet, m_is_system_default_isSet, m_sample_rate_isSet, m_volume_isSet, name, sample_rate, SWGSDRangel::toJsonValue(), and volume.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(name != nullptr && *name != QString("")){
         toJsonValue(QString("name"), name, obj, QString("QString"));
     }
     if(m_index_isSet){
         obj->insert("index", QJsonValue(index));
     }
     if(m_sample_rate_isSet){
         obj->insert("sampleRate", QJsonValue(sample_rate));
     }
     if(m_is_system_default_isSet){
         obj->insert("isSystemDefault", QJsonValue(is_system_default));
     }
     if(m_default_unregistered_isSet){
         obj->insert("defaultUnregistered", QJsonValue(default_unregistered));
     }
     if(m_volume_isSet){
         obj->insert("volume", QJsonValue(volume));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGAudioInputDevice::cleanup ()
Definition at line 66 of file SWGAudioInputDevice.cpp.
References name.
Referenced by WebAPIRequestMapper::resetAudioInputDevice(), and ~SWGAudioInputDevice().
{
     if(name != nullptr) {
         delete name;
     }
 }
fromJson()
SWGAudioInputDevice * SWGSDRangel::SWGAudioInputDevice::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 78 of file SWGAudioInputDevice.cpp.
References fromJsonObject().
Referenced by SWGAudioInputDevice().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGAudioInputDevice::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 87 of file SWGAudioInputDevice.cpp.
References default_unregistered, index, is_system_default, name, sample_rate, SWGSDRangel::setValue(), and volume.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&name, pJson["name"], "QString", "QString");
     ::SWGSDRangel::setValue(&index, pJson["index"], "qint32", "");
     ::SWGSDRangel::setValue(&sample_rate, pJson["sampleRate"], "qint32", "");
     ::SWGSDRangel::setValue(&is_system_default, pJson["isSystemDefault"], "qint32", "");
     ::SWGSDRangel::setValue(&default_unregistered, pJson["defaultUnregistered"], "qint32", "");
     ::SWGSDRangel::setValue(&volume, pJson["volume"], "float", "");
 }
getDefaultUnregistered()
qint32 SWGSDRangel::SWGAudioInputDevice::getDefaultUnregistered ()
Definition at line 179 of file SWGAudioInputDevice.cpp.
References default_unregistered.
{
     return default_unregistered;
 }
getIndex()
qint32 SWGSDRangel::SWGAudioInputDevice::getIndex ()
Definition at line 149 of file SWGAudioInputDevice.cpp.
References index.
Referenced by WebAPIAdapterGUI::instanceAudioInputDelete(), WebAPIAdapterSrv::instanceAudioInputDelete(), WebAPIAdapterSrv::instanceAudioInputPatch(), and WebAPIAdapterGUI::instanceAudioInputPatch().
{
     return index;
 }
getIsSystemDefault()
qint32 SWGSDRangel::SWGAudioInputDevice::getIsSystemDefault ()
Definition at line 169 of file SWGAudioInputDevice.cpp.
References is_system_default.
{
     return is_system_default;
 }
getName()
QString * SWGSDRangel::SWGAudioInputDevice::getName ()
Definition at line 139 of file SWGAudioInputDevice.cpp.
References name.
{
     return name;
 }
getSampleRate()
qint32 SWGSDRangel::SWGAudioInputDevice::getSampleRate ()
Definition at line 159 of file SWGAudioInputDevice.cpp.
References sample_rate.
Referenced by WebAPIAdapterGUI::instanceAudioInputPatch(), and WebAPIAdapterSrv::instanceAudioInputPatch().
{
     return sample_rate;
 }
getVolume()
float SWGSDRangel::SWGAudioInputDevice::getVolume ()
Definition at line 189 of file SWGAudioInputDevice.cpp.
References volume.
Referenced by WebAPIAdapterGUI::instanceAudioInputPatch(), and WebAPIAdapterSrv::instanceAudioInputPatch().
{
     return volume;
 }
init()
void SWGSDRangel::SWGAudioInputDevice::init ()
Definition at line 50 of file SWGAudioInputDevice.cpp.
References default_unregistered, index, is_system_default, m_default_unregistered_isSet, m_index_isSet, m_is_system_default_isSet, m_name_isSet, m_sample_rate_isSet, m_volume_isSet, name, sample_rate, and volume.
Referenced by SWGAudioInputDevice().
{
     name = new QString("");
     m_name_isSet = false;
     index = 0;
     m_index_isSet = false;
     sample_rate = 0;
     m_sample_rate_isSet = false;
     is_system_default = 0;
     m_is_system_default_isSet = false;
     default_unregistered = 0;
     m_default_unregistered_isSet = false;
     volume = 0.0f;
     m_volume_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGAudioInputDevice::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 200 of file SWGAudioInputDevice.cpp.
References m_default_unregistered_isSet, m_index_isSet, m_is_system_default_isSet, m_sample_rate_isSet, m_volume_isSet, and name.
{
     bool isObjectUpdated = false;
     do{
         if(name != nullptr && *name != QString("")){ isObjectUpdated = true; break;}
         if(m_index_isSet){ isObjectUpdated = true; break;}
         if(m_sample_rate_isSet){ isObjectUpdated = true; break;}
         if(m_is_system_default_isSet){ isObjectUpdated = true; break;}
         if(m_default_unregistered_isSet){ isObjectUpdated = true; break;}
         if(m_volume_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setDefaultUnregistered()
void SWGSDRangel::SWGAudioInputDevice::setDefaultUnregistered (qint32 default_unregistered)
Definition at line 183 of file SWGAudioInputDevice.cpp.
References default_unregistered, and m_default_unregistered_isSet.
{
     this->default_unregistered = default_unregistered;
     this->m_default_unregistered_isSet = true;
 }
setIndex()
void SWGSDRangel::SWGAudioInputDevice::setIndex (qint32 index)
Definition at line 153 of file SWGAudioInputDevice.cpp.
References index, and m_index_isSet.
Referenced by WebAPIRequestMapper::validateAudioInputDevice().
{
     this->index = index;
     this->m_index_isSet = true;
 }
setIsSystemDefault()
void SWGSDRangel::SWGAudioInputDevice::setIsSystemDefault (qint32 is_system_default)
Definition at line 173 of file SWGAudioInputDevice.cpp.
References is_system_default, and m_is_system_default_isSet.
{
     this->is_system_default = is_system_default;
     this->m_is_system_default_isSet = true;
 }
setName()
void SWGSDRangel::SWGAudioInputDevice::setName (QString * name)
Definition at line 143 of file SWGAudioInputDevice.cpp.
References m_name_isSet, and name.
Referenced by WebAPIRequestMapper::resetAudioInputDevice().
{
     this->name = name;
     this->m_name_isSet = true;
 }
setSampleRate()
void SWGSDRangel::SWGAudioInputDevice::setSampleRate (qint32 sample_rate)
Definition at line 163 of file SWGAudioInputDevice.cpp.
References m_sample_rate_isSet, and sample_rate.
Referenced by WebAPIAdapterGUI::instanceAudioInputDelete(), WebAPIAdapterSrv::instanceAudioInputDelete(), WebAPIAdapterSrv::instanceAudioInputPatch(), WebAPIAdapterGUI::instanceAudioInputPatch(), and WebAPIRequestMapper::validateAudioInputDevice().
{
     this->sample_rate = sample_rate;
     this->m_sample_rate_isSet = true;
 }
setVolume()
void SWGSDRangel::SWGAudioInputDevice::setVolume (float volume)
Definition at line 193 of file SWGAudioInputDevice.cpp.
References m_volume_isSet, and volume.
Referenced by WebAPIAdapterGUI::instanceAudioInputDelete(), WebAPIAdapterSrv::instanceAudioInputDelete(), WebAPIAdapterSrv::instanceAudioInputPatch(), WebAPIAdapterGUI::instanceAudioInputPatch(), and WebAPIRequestMapper::validateAudioInputDevice().
{
     this->volume = volume;
     this->m_volume_isSet = true;
 }
Member Data Documentation
default_unregistered
qint32 SWGSDRangel::SWGAudioInputDevice::default_unregistered private
Definition at line 79 of file SWGAudioInputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getDefaultUnregistered(), init(), setDefaultUnregistered(), and SWGAudioInputDevice().
index
qint32 SWGSDRangel::SWGAudioInputDevice::index private
Definition at line 70 of file SWGAudioInputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getIndex(), init(), setIndex(), and SWGAudioInputDevice().
is_system_default
qint32 SWGSDRangel::SWGAudioInputDevice::is_system_default private
Definition at line 76 of file SWGAudioInputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getIsSystemDefault(), init(), setIsSystemDefault(), and SWGAudioInputDevice().
m_default_unregistered_isSet
bool SWGSDRangel::SWGAudioInputDevice::m_default_unregistered_isSet private
Definition at line 80 of file SWGAudioInputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setDefaultUnregistered(), and SWGAudioInputDevice().
m_index_isSet
bool SWGSDRangel::SWGAudioInputDevice::m_index_isSet private
Definition at line 71 of file SWGAudioInputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setIndex(), and SWGAudioInputDevice().
m_is_system_default_isSet
bool SWGSDRangel::SWGAudioInputDevice::m_is_system_default_isSet private
Definition at line 77 of file SWGAudioInputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setIsSystemDefault(), and SWGAudioInputDevice().
m_name_isSet
bool SWGSDRangel::SWGAudioInputDevice::m_name_isSet private
Definition at line 68 of file SWGAudioInputDevice.h.
Referenced by init(), setName(), and SWGAudioInputDevice().
m_sample_rate_isSet
bool SWGSDRangel::SWGAudioInputDevice::m_sample_rate_isSet private
Definition at line 74 of file SWGAudioInputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setSampleRate(), and SWGAudioInputDevice().
m_volume_isSet
bool SWGSDRangel::SWGAudioInputDevice::m_volume_isSet private
Definition at line 83 of file SWGAudioInputDevice.h.
Referenced by asJsonObject(), init(), isSet(), setVolume(), and SWGAudioInputDevice().
name
QString* SWGSDRangel::SWGAudioInputDevice::name private
Definition at line 67 of file SWGAudioInputDevice.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getName(), init(), isSet(), setName(), and SWGAudioInputDevice().
sample_rate
qint32 SWGSDRangel::SWGAudioInputDevice::sample_rate private
Definition at line 73 of file SWGAudioInputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getSampleRate(), init(), setSampleRate(), and SWGAudioInputDevice().
volume
float SWGSDRangel::SWGAudioInputDevice::volume private
Definition at line 82 of file SWGAudioInputDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getVolume(), init(), setVolume(), and SWGAudioInputDevice().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGAudioInputDevice.h
swagger/sdrangel/code/qt5/client/SWGAudioInputDevice.cpp