SDRAngel: qrtplib::RTPCollisionList Class Reference
qrtplib::RTPCollisionList Class Reference
#include <rtpcollisionlist.h>
Classes
class AddressAndTime
Public Member Functions
RTPCollisionList ()
~RTPCollisionList ()
void Clear ()
int UpdateAddress (const RTPAddress *addr, const RTPTime &receivetime, bool *created)
bool HasAddress (const RTPAddress *addr) const
void Timeout (const RTPTime &currenttime, const RTPTime &timeoutdelay)
Private Attributes
std::list< AddressAndTime > addresslist
Detailed Description
This class represents a list of addresses from which SSRC collisions were detected.
Definition at line 54 of file rtpcollisionlist.h.
Constructor & Destructor Documentation
RTPCollisionList()
qrtplib::RTPCollisionList::RTPCollisionList ()
Constructs an instance, optionally installing a memory manager.
Definition at line 39 of file rtpcollisionlist.cpp.
References qrtplib::RTPTimeInitializerObject::Dummy(), and qrtplib::timeinit.
 {
     timeinit.Dummy();
 }
~RTPCollisionList()
qrtplib::RTPCollisionList::~RTPCollisionList () inline
Definition at line 59 of file rtpcollisionlist.h.
     {
         Clear();
     }
Member Function Documentation
Clear()
void qrtplib::RTPCollisionList::Clear ()
Clears the list of addresses.
Definition at line 44 of file rtpcollisionlist.cpp.
References addresslist.
Referenced by qrtplib::RTPSession::BYEDestroy(), and qrtplib::RTPSession::Destroy().
 {
     std::list<AddressAndTime>::iterator it;
     for (it = addresslist.begin(); it != addresslist.end(); it++)
         delete (*it).addr;
     addresslist.clear();
 }
HasAddress()
bool qrtplib::RTPCollisionList::HasAddress (const RTPAddress * addr) const
Returns true} if the address addr appears in the list.
Definition at line 79 of file rtpcollisionlist.cpp.
References addresslist.
 {
     std::list<AddressAndTime>::const_iterator it;
     for (it = addresslist.begin(); it != addresslist.end(); it++)
     {
         if (((*it).addr)->IsSameAddress(addr))
             return true;
     }
     return false;
 }
Timeout()
void qrtplib::RTPCollisionList::Timeout (const RTPTime & currenttime, const RTPTime & timeoutdelay)
Assuming that the current time is given by currenttime, this function times out entries which haven't been updated in the previous time interval specified by timeoutdelay.
Definition at line 92 of file rtpcollisionlist.cpp.
References addresslist.
Referenced by qrtplib::RTPSession::ProcessPolledData().
 {
     std::list<AddressAndTime>::iterator it;
     RTPTime checktime = currenttime;
     checktime -= timeoutdelay;
     it = addresslist.begin();
     while (it != addresslist.end())
     {
         if ((*it).recvtime < checktime) // timeout
         {
             delete (*it).addr;
             it = addresslist.erase(it);
         }
         else
             it++;
     }
 }
UpdateAddress()
int qrtplib::RTPCollisionList::UpdateAddress (const RTPAddress * addr, const RTPTime & receivetime, bool * created)
Updates the entry for address addr to indicate that a collision was detected at time receivetime. Updates the entry for address addr to indicate that a collision was detected at time receivetime. If the entry did not exist yet, the flag created is set to true, otherwise it is set to false.
Definition at line 53 of file rtpcollisionlist.cpp.
References addresslist, qrtplib::RTPAddress::CreateCopy(), ERR_RTP_COLLISIONLIST_BADADDRESS, and ERR_RTP_OUTOFMEM.
Referenced by qrtplib::RTPSession::ProcessPolledData().
 {
     if (addr == 0)
         return ERR_RTP_COLLISIONLIST_BADADDRESS;
     std::list<AddressAndTime>::iterator it;
     for (it = addresslist.begin(); it != addresslist.end(); it++)
     {
         if (((*it).addr)->IsSameAddress(addr))
         {
             (*it).recvtime = receivetime;
             *created = false;
             return 0;
         }
     }
     RTPAddress *newaddr = addr->CreateCopy();
     if (newaddr == 0)
         return ERR_RTP_OUTOFMEM;
     addresslist.push_back(AddressAndTime(newaddr, receivetime));
     *created = true;
     return 0;
 }
Member Data Documentation
addresslist
std::list<AddressAndTime> qrtplib::RTPCollisionList::addresslist private
Definition at line 94 of file rtpcollisionlist.h.
Referenced by Clear(), HasAddress(), Timeout(), and UpdateAddress().
The documentation for this class was generated from the following files:
qrtplib/rtpcollisionlist.h
qrtplib/rtpcollisionlist.cpp