SDRAngel: RemoteSink::MsgConfigureRemoteSink Class Reference
RemoteSink::MsgConfigureRemoteSink Class Reference
#include <remotesink.h>
Public Member Functions
const RemoteSinkSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureRemoteSink * create (const RemoteSinkSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureRemoteSink (const RemoteSinkSettings &settings, bool force)
Private Attributes
RemoteSinkSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 46 of file remotesink.h.
Constructor & Destructor Documentation
MsgConfigureRemoteSink()
RemoteSink::MsgConfigureRemoteSink::MsgConfigureRemoteSink (const RemoteSinkSettings & settings, bool force) inline private
Definition at line 62 of file remotesink.h.
Referenced by create().
                                                                                :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureRemoteSink* RemoteSink::MsgConfigureRemoteSink::create (const RemoteSinkSettings & settings, bool force) inline static
Definition at line 53 of file remotesink.h.
References MsgConfigureRemoteSink().
Referenced by RemoteSinkGUI::applySettings(), RemoteSink::deserialize(), and RemoteSink::webapiSettingsPutPatch().
         {
             return new MsgConfigureRemoteSink(settings, force);
         }
getForce()
bool RemoteSink::MsgConfigureRemoteSink::getForce () const inline
Definition at line 51 of file remotesink.h.
References m_force.
Referenced by RemoteSink::handleMessage().
 { return m_force; }
getSettings()
const RemoteSinkSettings& RemoteSink::MsgConfigureRemoteSink::getSettings () const inline
Definition at line 50 of file remotesink.h.
References m_settings.
Referenced by RemoteSinkGUI::handleMessage(), and RemoteSink::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool RemoteSink::MsgConfigureRemoteSink::m_force private
Definition at line 60 of file remotesink.h.
Referenced by getForce().
m_settings
RemoteSinkSettings RemoteSink::MsgConfigureRemoteSink::m_settings private
Definition at line 59 of file remotesink.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/channelrx/remotesink/remotesink.h