SDRAngel: TestMIGui Class Reference
TestMIGui Class Reference
#include <testmigui.h>
Public Member Functions
TestMIGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~TestMIGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_startStop_toggled (bool checked)
void on_streamIndex_currentIndexChanged (int index)
void on_spectrumSource_currentIndexChanged (int index)
void on_streamLock_toggled (bool checked)
void on_centerFrequency_changed (quint64 value)
void on_autoCorr_currentIndexChanged (int index)
void on_frequencyShift_changed (qint64 value)
void on_decimation_currentIndexChanged (int index)
void on_fcPos_currentIndexChanged (int index)
void on_sampleRate_changed (quint64 value)
void on_sampleSize_currentIndexChanged (int index)
void on_amplitudeCoarse_valueChanged (int value)
void on_amplitudeFine_valueChanged (int value)
void on_modulation_currentIndexChanged (int index)
void on_modulationFrequency_valueChanged (int value)
void on_amModulation_valueChanged (int value)
void on_fmDeviation_valueChanged (int value)
void on_dcBias_valueChanged (int value)
void on_iBias_valueChanged (int value)
void on_qBias_valueChanged (int value)
void on_phaseImbalance_valueChanged (int value)
void on_record_toggled (bool checked)
void openDeviceSettingsDialog (const QPoint &p)
void updateStatus ()
void updateHardware ()
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void displayAmplitude ()
void updateAmpCoarseLimit ()
void updateAmpFineLimit ()
void updateFrequencyShiftLimit ()
void updateFileRecordStatus ()
Private Attributes
Ui::TestMIGui * ui
DeviceUISet * m_deviceUISet
TestMISettings m_settings
int m_streamIndex
Current stream index being dealt with.
int m_spectrumStreamIndex
Index of the stream displayed on main spectrum.
QTimer m_updateTimer
QTimer m_statusTimer
bool m_doApplySettings
bool m_forceSettings
DeviceSampleMIMO * m_sampleMIMO
std::size_t m_tickCount
std::vector< int > m_deviceSampleRates
std::vector< quint64 > m_deviceCenterFrequencies
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 36 of file testmigui.h.
Constructor & Destructor Documentation
TestMIGui()
TestMIGui::TestMIGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 42 of file testmigui.cpp.
References arg(), displaySettings(), DeviceAPI::getSampleMIMO(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceCenterFrequencies, m_deviceSampleRates, m_deviceUISet, m_inputMessageQueue, m_sampleMIMO, m_settings, m_statusTimer, m_streamIndex, TestMISettings::m_streams, m_updateTimer, openDeviceSettingsDialog(), DeviceSampleMIMO::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                               :
     QWidget(parent),
     ui(new Ui::TestMIGui),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_sampleMIMO(nullptr),
     m_tickCount(0),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     qDebug("TestMIGui::TestMIGui");
     m_sampleMIMO = m_deviceUISet->m_deviceAPI->getSampleMIMO();
     m_streamIndex = 0;
     m_deviceCenterFrequencies.push_back(m_settings.m_streams[0].m_centerFrequency);
     m_deviceCenterFrequencies.push_back(m_settings.m_streams[1].m_centerFrequency);
     m_deviceSampleRates.push_back(m_settings.m_streams[0].m_sampleRate / (1<<m_settings.m_streams[0].m_log2Decim));
     m_deviceSampleRates.push_back(m_settings.m_streams[1].m_sampleRate / (1<<m_settings.m_streams[1].m_log2Decim));
     ui->setupUi(this);
     ui->spectrumSource->addItem("0");
     ui->spectrumSource->addItem("1");
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, 0, 9999999);
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(7, 48000, 9999999);
     ui->frequencyShift->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->frequencyShift->setValueRange(false, 7, -9999999, 9999999);
     ui->frequencyShiftLabel->setText(QString("%1").arg(QChar(0x94, 0x03)));
     displaySettings();
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleMIMO->setMessageQueueToGUI(&m_inputMessageQueue);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
 }
~TestMIGui()
TestMIGui::~TestMIGui () virtual
Definition at line 85 of file testmigui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void TestMIGui::blockApplySettings (bool block) inline private
Definition at line 73 of file testmigui.h.
Referenced by displaySettings(), and handleMessage().
 { m_doApplySettings = !block; }
deserialize()
bool TestMIGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 129 of file testmigui.cpp.
References TestMISettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void TestMIGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 90 of file testmigui.cpp.
 {
     delete this;
 }
displayAmplitude()
void TestMIGui::displayAmplitude () private
Definition at line 346 of file testmigui.cpp.
References arg(), CalcDb::dbPower(), and ui.
Referenced by displaySettings(), on_amplitudeCoarse_valueChanged(), on_amplitudeFine_valueChanged(), and on_sampleSize_currentIndexChanged().
 {
     int amplitudeInt = ui->amplitudeCoarse->value() * 100 + ui->amplitudeFine->value();
     double power;
     switch (ui->sampleSize->currentIndex())
     {
     case 0: // 8 bits: 128
         power = (double) amplitudeInt*amplitudeInt / (double) (1<<14);
         break;
     case 1: // 12 bits 2048
         power = (double) amplitudeInt*amplitudeInt / (double) (1<<22);
         break;
     case 2: // 16 bits 32768
     default:
         power = (double) amplitudeInt*amplitudeInt / (double) (1<<30);
         break;
     }
     ui->amplitudeBits->setText(QString(tr("%1 b").arg(amplitudeInt)));
     double powerDb = CalcDb::dbPower(power);
     ui->power->setText(QString(tr("%1 dB").arg(QString::number(powerDb, 'f', 1))));
 }
displaySettings()
void TestMIGui::displaySettings () private
Definition at line 432 of file testmigui.cpp.
References arg(), blockApplySettings(), displayAmplitude(), m_settings, m_streamIndex, TestMISettings::m_streams, ui, updateAmpCoarseLimit(), updateAmpFineLimit(), and updateFrequencyShiftLimit().
Referenced by deserialize(), handleMessage(), on_spectrumSource_currentIndexChanged(), on_streamIndex_currentIndexChanged(), resetToDefaults(), setCenterFrequency(), and TestMIGui().
 {
     blockApplySettings(true);
     ui->sampleSize->blockSignals(true);
     ui->streamIndex->setCurrentIndex(m_streamIndex);
     ui->centerFrequency->setValue(m_settings.m_streams[m_streamIndex].m_centerFrequency / 1000);
     ui->decimation->setCurrentIndex(m_settings.m_streams[m_streamIndex].m_log2Decim);
     ui->fcPos->setCurrentIndex((int) m_settings.m_streams[m_streamIndex].m_fcPos);
     ui->sampleRate->setValue(m_settings.m_streams[m_streamIndex].m_sampleRate);
     updateFrequencyShiftLimit();
     ui->frequencyShift->setValue(m_settings.m_streams[m_streamIndex].m_frequencyShift);
     ui->sampleSize->setCurrentIndex(m_settings.m_streams[m_streamIndex].m_sampleSizeIndex);
     updateAmpCoarseLimit();
     int amplitudeBits = m_settings.m_streams[m_streamIndex].m_amplitudeBits;
     ui->amplitudeCoarse->setValue(amplitudeBits/100);
     updateAmpFineLimit();
     ui->amplitudeFine->setValue(amplitudeBits%100);
     displayAmplitude();
     int dcBiasPercent = roundf(m_settings.m_streams[m_streamIndex].m_dcFactor * 100.0f);
     ui->dcBias->setValue((int) dcBiasPercent);
     ui->dcBiasText->setText(QString(tr("%1 %").arg(dcBiasPercent)));
     int iBiasPercent = roundf(m_settings.m_streams[m_streamIndex].m_iFactor * 100.0f);
     ui->iBias->setValue((int) iBiasPercent);
     ui->iBiasText->setText(QString(tr("%1 %").arg(iBiasPercent)));
     int qBiasPercent = roundf(m_settings.m_streams[m_streamIndex].m_qFactor * 100.0f);
     ui->qBias->setValue((int) qBiasPercent);
     ui->qBiasText->setText(QString(tr("%1 %").arg(qBiasPercent)));
     int phaseImbalancePercent = roundf(m_settings.m_streams[m_streamIndex].m_phaseImbalance * 100.0f);
     ui->phaseImbalance->setValue((int) phaseImbalancePercent);
     ui->phaseImbalanceText->setText(QString(tr("%1 %").arg(phaseImbalancePercent)));
     ui->autoCorr->setCurrentIndex(m_settings.m_streams[m_streamIndex].m_autoCorrOptions);
     ui->sampleSize->blockSignals(false);
     ui->modulation->setCurrentIndex((int) m_settings.m_streams[m_streamIndex].m_modulation);
     ui->modulationFrequency->setValue(m_settings.m_streams[m_streamIndex].m_modulationTone);
     ui->modulationFrequencyText->setText(QString("%1").arg(m_settings.m_streams[m_streamIndex].m_modulationTone / 100.0, 0, 'f', 2));
     ui->amModulation->setValue(m_settings.m_streams[m_streamIndex].m_amModulation);
     ui->amModulationText->setText(QString("%1").arg(m_settings.m_streams[m_streamIndex].m_amModulation));
     ui->fmDeviation->setValue(m_settings.m_streams[m_streamIndex].m_fmDeviation);
     ui->fmDeviationText->setText(QString("%1").arg(m_settings.m_streams[m_streamIndex].m_fmDeviation / 10.0, 0, 'f', 1));
     blockApplySettings(false);
 }
getCenterFrequency()
qint64 TestMIGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 112 of file testmigui.cpp.
References m_settings, m_streamIndex, and TestMISettings::m_streams.
 {
     return m_settings.m_streams[m_streamIndex].m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* TestMIGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 52 of file testmigui.h.
 { return &m_inputMessageQueue; }
getName()
QString TestMIGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 100 of file testmigui.cpp.
 {
     return objectName();
 }
handleInputMessages
void TestMIGui::handleInputMessages () private slot
Definition at line 548 of file testmigui.cpp.
References DSPMIMOSignalNotification::getCenterFrequency(), DSPMIMOSignalNotification::getIndex(), DSPMIMOSignalNotification::getSampleRate(), DSPMIMOSignalNotification::getSourceOrSink(), handleMessage(), m_deviceCenterFrequencies, m_deviceSampleRates, m_inputMessageQueue, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by TestMIGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (DSPMIMOSignalNotification::match(*message))
         {
             DSPMIMOSignalNotification* notif = (DSPMIMOSignalNotification*) message;
             int istream = notif->getIndex();
             bool sourceOrSink = notif->getSourceOrSink();
             m_deviceSampleRates[istream] = notif->getSampleRate();
             m_deviceCenterFrequencies[istream] = notif->getCenterFrequency();
             // Do not consider multiple sources at this time
             qDebug("TestMIGui::handleInputMessages: DSPMIMOSignalNotification: %s stream: %d SampleRate:%d, CenterFrequency:%llu",
                     sourceOrSink ? "source" : "sink",
                     istream,
                     notif->getSampleRate(),
                     notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool TestMIGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 522 of file testmigui.cpp.
References blockApplySettings(), displaySettings(), TestMI::MsgConfigureTestSource::getSettings(), TestMI::MsgStartStop::getStartStop(), m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (TestMI::MsgConfigureTestSource::match(message))
     {
         qDebug("TestMIGui::handleMessage: MsgConfigureTestSource");
         const TestMI::MsgConfigureTestSource& cfg = (TestMI::MsgConfigureTestSource&) message;
         m_settings = cfg.getSettings();
         displaySettings();
         return true;
     }
     else if (TestMI::MsgStartStop::match(message))
     {
         qDebug("TestMIGui::handleMessage: MsgStartStop");
         TestMI::MsgStartStop& notif = (TestMI::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_amModulation_valueChanged
void TestMIGui::on_amModulation_valueChanged (int value) private slot
Definition at line 292 of file testmigui.cpp.
References arg(), m_settings, m_streamIndex, TestMISettings::m_streams, sendSettings(), and ui.
 {
     m_settings.m_streams[m_streamIndex].m_amModulation = value;
     ui->amModulationText->setText(QString("%1").arg(m_settings.m_streams[m_streamIndex].m_amModulation));
     sendSettings();
 }
on_amplitudeCoarse_valueChanged
void TestMIGui::on_amplitudeCoarse_valueChanged (int value) private slot
Definition at line 258 of file testmigui.cpp.
References displayAmplitude(), m_settings, m_streamIndex, TestMISettings::m_streams, sendSettings(), ui, and updateAmpFineLimit().
 {
     (void) value;
     updateAmpFineLimit();
     displayAmplitude();
     m_settings.m_streams[m_streamIndex].m_amplitudeBits = ui->amplitudeCoarse->value() * 100 + ui->amplitudeFine->value();
     sendSettings();
 }
on_amplitudeFine_valueChanged
void TestMIGui::on_amplitudeFine_valueChanged (int value) private slot
Definition at line 267 of file testmigui.cpp.
References displayAmplitude(), m_settings, m_streamIndex, TestMISettings::m_streams, sendSettings(), and ui.
 {
     (void) value;
     displayAmplitude();
     m_settings.m_streams[m_streamIndex].m_amplitudeBits = ui->amplitudeCoarse->value() * 100 + ui->amplitudeFine->value();
     sendSettings();
 }
on_autoCorr_currentIndexChanged
void TestMIGui::on_autoCorr_currentIndexChanged (int index) private slot
Definition at line 200 of file testmigui.cpp.
References TestMIStreamSettings::AutoCorrLast, m_settings, m_streamIndex, TestMISettings::m_streams, and sendSettings().
 {
     if ((index < 0) || (index > TestMIStreamSettings::AutoCorrLast)) {
         return;
     }
     m_settings.m_streams[m_streamIndex].m_autoCorrOptions = (TestMIStreamSettings::AutoCorrOptions) index;
     sendSettings();
 }
on_centerFrequency_changed
void TestMIGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 194 of file testmigui.cpp.
References m_settings, m_streamIndex, TestMISettings::m_streams, and sendSettings().
 {
     m_settings.m_streams[m_streamIndex].m_centerFrequency = value * 1000;
     sendSettings();
 }
on_dcBias_valueChanged
void TestMIGui::on_dcBias_valueChanged (int value) private slot
Definition at line 306 of file testmigui.cpp.
References arg(), m_settings, m_streamIndex, TestMISettings::m_streams, sendSettings(), and ui.
 {
     ui->dcBiasText->setText(QString(tr("%1 %").arg(value)));
     m_settings.m_streams[m_streamIndex].m_dcFactor = value / 100.0f;
     sendSettings();
 }
on_decimation_currentIndexChanged
void TestMIGui::on_decimation_currentIndexChanged (int index) private slot
Definition at line 216 of file testmigui.cpp.
References m_settings, m_streamIndex, TestMISettings::m_streams, and sendSettings().
 {
     if ((index < 0) || (index > 6)) {
         return;
     }
     m_settings.m_streams[m_streamIndex].m_log2Decim = index;
     sendSettings();
 }
on_fcPos_currentIndexChanged
void TestMIGui::on_fcPos_currentIndexChanged (int index) private slot
Definition at line 226 of file testmigui.cpp.
References m_settings, m_streamIndex, TestMISettings::m_streams, and sendSettings().
 {
     if ((index < 0) || (index > 2)) {
         return;
     }
     m_settings.m_streams[m_streamIndex].m_fcPos = (TestMIStreamSettings::fcPos_t) index;
     sendSettings();
 }
on_fmDeviation_valueChanged
void TestMIGui::on_fmDeviation_valueChanged (int value) private slot
Definition at line 299 of file testmigui.cpp.
References arg(), m_settings, m_streamIndex, TestMISettings::m_streams, sendSettings(), and ui.
 {
     m_settings.m_streams[m_streamIndex].m_fmDeviation = value;
     ui->fmDeviationText->setText(QString("%1").arg(m_settings.m_streams[m_streamIndex].m_fmDeviation / 10.0, 0, 'f', 1));
     sendSettings();
 }
on_frequencyShift_changed
void TestMIGui::on_frequencyShift_changed (qint64 value) private slot
Definition at line 210 of file testmigui.cpp.
References m_settings, m_streamIndex, TestMISettings::m_streams, and sendSettings().
 {
     m_settings.m_streams[m_streamIndex].m_frequencyShift = value;
     sendSettings();
 }
on_iBias_valueChanged
void TestMIGui::on_iBias_valueChanged (int value) private slot
Definition at line 313 of file testmigui.cpp.
References arg(), m_settings, m_streamIndex, TestMISettings::m_streams, sendSettings(), and ui.
 {
     ui->iBiasText->setText(QString(tr("%1 %").arg(value)));
     m_settings.m_streams[m_streamIndex].m_iFactor = value / 100.0f;
     sendSettings();
 }
on_modulation_currentIndexChanged
void TestMIGui::on_modulation_currentIndexChanged (int index) private slot
Definition at line 275 of file testmigui.cpp.
References m_settings, m_streamIndex, TestMISettings::m_streams, TestMIStreamSettings::ModulationLast, and sendSettings().
 {
     if ((index < 0) || (index > TestMIStreamSettings::ModulationLast)) {
         return;
     }
     m_settings.m_streams[m_streamIndex].m_modulation = (TestMIStreamSettings::Modulation) index;
     sendSettings();
 }
on_modulationFrequency_valueChanged
void TestMIGui::on_modulationFrequency_valueChanged (int value) private slot
Definition at line 285 of file testmigui.cpp.
References arg(), m_settings, m_streamIndex, TestMISettings::m_streams, sendSettings(), and ui.
 {
     m_settings.m_streams[m_streamIndex].m_modulationTone = value;
     ui->modulationFrequencyText->setText(QString("%1").arg(m_settings.m_streams[m_streamIndex].m_modulationTone / 100.0, 0, 'f', 2));
     sendSettings();
 }
on_phaseImbalance_valueChanged
void TestMIGui::on_phaseImbalance_valueChanged (int value) private slot
Definition at line 327 of file testmigui.cpp.
References arg(), m_settings, m_streamIndex, TestMISettings::m_streams, sendSettings(), and ui.
 {
     ui->phaseImbalanceText->setText(QString(tr("%1 %").arg(value)));
     m_settings.m_streams[m_streamIndex].m_phaseImbalance = value / 100.0f;
     sendSettings();
 }
on_qBias_valueChanged
void TestMIGui::on_qBias_valueChanged (int value) private slot
Definition at line 320 of file testmigui.cpp.
References arg(), m_settings, m_streamIndex, TestMISettings::m_streams, sendSettings(), and ui.
 {
     ui->qBiasText->setText(QString(tr("%1 %").arg(value)));
     m_settings.m_streams[m_streamIndex].m_qFactor = value / 100.0f;
     sendSettings();
 }
on_record_toggled
void TestMIGui::on_record_toggled (bool checked) private slot
Definition at line 334 of file testmigui.cpp.
References TestMI::MsgFileRecord::create(), DeviceSampleMIMO::getInputMessageQueue(), m_sampleMIMO, m_streamIndex, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     TestMI::MsgFileRecord* message = TestMI::MsgFileRecord::create(checked, m_streamIndex);
     m_sampleMIMO->getInputMessageQueue()->push(message);
 }
on_sampleRate_changed
void TestMIGui::on_sampleRate_changed (quint64 value) private slot
Definition at line 236 of file testmigui.cpp.
References m_settings, m_streamIndex, TestMISettings::m_streams, sendSettings(), ui, and updateFrequencyShiftLimit().
 {
     updateFrequencyShiftLimit();
     m_settings.m_streams[m_streamIndex].m_frequencyShift = ui->frequencyShift->getValueNew();
     m_settings.m_streams[m_streamIndex].m_sampleRate = value;
     sendSettings();
 }
on_sampleSize_currentIndexChanged
void TestMIGui::on_sampleSize_currentIndexChanged (int index) private slot
Definition at line 244 of file testmigui.cpp.
References displayAmplitude(), m_settings, m_streamIndex, TestMISettings::m_streams, sendSettings(), ui, updateAmpCoarseLimit(), and updateAmpFineLimit().
 {
     if ((index < 0) || (index > 2)) {
         return;
     }
     updateAmpCoarseLimit();
     updateAmpFineLimit();
     displayAmplitude();
     m_settings.m_streams[m_streamIndex].m_amplitudeBits = ui->amplitudeCoarse->value() * 100 + ui->amplitudeFine->value();
     m_settings.m_streams[m_streamIndex].m_sampleSizeIndex = index;
     sendSettings();
 }
on_spectrumSource_currentIndexChanged
void TestMIGui::on_spectrumSource_currentIndexChanged (int index) private slot
Definition at line 169 of file testmigui.cpp.
References displaySettings(), DeviceUISet::m_deviceAPI, m_deviceUISet, DeviceUISet::m_spectrum, m_spectrumStreamIndex, m_streamIndex, GLSpectrum::setDisplayedStream(), DeviceAPI::setSpectrumSinkInput(), ui, updateFileRecordStatus(), and updateSampleRateAndFrequency().
 {
     m_spectrumStreamIndex = index;
     m_deviceUISet->m_spectrum->setDisplayedStream(true, index);
     m_deviceUISet->m_deviceAPI->setSpectrumSinkInput(true, m_spectrumStreamIndex);
     updateSampleRateAndFrequency();
     if (ui->streamLock->isChecked())
     {
         ui->streamIndex->blockSignals(true);
         ui->streamIndex->setCurrentIndex(index);
         ui->streamIndex->blockSignals(false);
         m_streamIndex = index;
         updateFileRecordStatus();
         displaySettings();
     }
 }
on_startStop_toggled
void TestMIGui::on_startStop_toggled (bool checked) private slot
Definition at line 142 of file testmigui.cpp.
References TestMI::MsgStartStop::create(), DeviceSampleMIMO::getInputMessageQueue(), m_doApplySettings, m_sampleMIMO, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         TestMI::MsgStartStop *message = TestMI::MsgStartStop::create(checked);
         m_sampleMIMO->getInputMessageQueue()->push(message);
     }
 }
on_streamIndex_currentIndexChanged
void TestMIGui::on_streamIndex_currentIndexChanged (int index) private slot
Definition at line 151 of file testmigui.cpp.
References displaySettings(), DeviceUISet::m_deviceAPI, m_deviceUISet, DeviceUISet::m_spectrum, m_spectrumStreamIndex, m_streamIndex, GLSpectrum::setDisplayedStream(), DeviceAPI::setSpectrumSinkInput(), ui, updateFileRecordStatus(), and updateSampleRateAndFrequency().
 {
     if (ui->streamLock->isChecked())
     {
         m_spectrumStreamIndex = index;
         m_deviceUISet->m_spectrum->setDisplayedStream(true, index);
         m_deviceUISet->m_deviceAPI->setSpectrumSinkInput(true, m_spectrumStreamIndex);
         ui->spectrumSource->blockSignals(true);
         ui->spectrumSource->setCurrentIndex(index);
         ui->spectrumSource->blockSignals(false);
     }
     m_streamIndex = index;
     updateFileRecordStatus();
     updateSampleRateAndFrequency();
     displaySettings();
 }
on_streamLock_toggled
void TestMIGui::on_streamLock_toggled (bool checked) private slot
Definition at line 187 of file testmigui.cpp.
References ui.
 {
     if (checked && (ui->streamIndex->currentIndex() != ui->spectrumSource->currentIndex())) {
         ui->spectrumSource->setCurrentIndex(ui->streamIndex->currentIndex());
     }
 }
openDeviceSettingsDialog
void TestMIGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 588 of file testmigui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), TestMISettings::m_reverseAPIAddress, TestMISettings::m_reverseAPIDeviceIndex, TestMISettings::m_reverseAPIPort, m_settings, TestMISettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by TestMIGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void TestMIGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 105 of file testmigui.cpp.
References displaySettings(), m_settings, TestMISettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void TestMIGui::sendSettings () private
Definition at line 475 of file testmigui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_amModulation_valueChanged(), on_amplitudeCoarse_valueChanged(), on_amplitudeFine_valueChanged(), on_autoCorr_currentIndexChanged(), on_centerFrequency_changed(), on_dcBias_valueChanged(), on_decimation_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_fmDeviation_valueChanged(), on_frequencyShift_changed(), on_iBias_valueChanged(), on_modulation_currentIndexChanged(), on_modulationFrequency_valueChanged(), on_phaseImbalance_valueChanged(), on_qBias_valueChanged(), on_sampleRate_changed(), on_sampleSize_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive()) {
         m_updateTimer.start(100);
     }
 }
serialize()
QByteArray TestMIGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 124 of file testmigui.cpp.
References m_settings, and TestMISettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void TestMIGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 117 of file testmigui.cpp.
References displaySettings(), m_settings, m_streamIndex, TestMISettings::m_streams, and sendSettings().
 {
     m_settings.m_streams[m_streamIndex].m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void TestMIGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 95 of file testmigui.cpp.
 {
     setObjectName(name);
 }
updateAmpCoarseLimit()
void TestMIGui::updateAmpCoarseLimit () private
Definition at line 370 of file testmigui.cpp.
References ui.
Referenced by displaySettings(), and on_sampleSize_currentIndexChanged().
 {
     switch (ui->sampleSize->currentIndex())
     {
     case 0: // 8 bits: 128
         ui->amplitudeCoarse->setMaximum(1);
         break;
     case 1: // 12 bits 2048
         ui->amplitudeCoarse->setMaximum(20);
         break;
     case 2: // 16 bits 32768
     default:
         ui->amplitudeCoarse->setMaximum(327);
         break;
     }
 }
updateAmpFineLimit()
void TestMIGui::updateAmpFineLimit () private
Definition at line 387 of file testmigui.cpp.
References ui.
Referenced by displaySettings(), on_amplitudeCoarse_valueChanged(), and on_sampleSize_currentIndexChanged().
 {
     switch (ui->sampleSize->currentIndex())
     {
     case 0: // 8 bits: 128
         if (ui->amplitudeCoarse->value() == 1) {
             ui->amplitudeFine->setMaximum(27);
         } else {
             ui->amplitudeFine->setMaximum(99);
         }
         break;
     case 1: // 12 bits 2048
         if (ui->amplitudeCoarse->value() == 20) {
             ui->amplitudeFine->setMaximum(47);
         } else {
             ui->amplitudeFine->setMaximum(99);
         }
         break;
     case 2: // 16 bits 32768
     default:
         if (ui->amplitudeCoarse->value() == 327) {
             ui->amplitudeFine->setMaximum(67);
         } else {
             ui->amplitudeFine->setMaximum(99);
         }
         break;
     }
 }
updateFileRecordStatus()
void TestMIGui::updateFileRecordStatus () private
Definition at line 423 of file testmigui.cpp.
References m_sampleMIMO, m_streamIndex, and ui.
Referenced by on_spectrumSource_currentIndexChanged(), and on_streamIndex_currentIndexChanged().
 {
     if (((TestMI*) m_sampleMIMO)->isRecording(m_streamIndex)) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
 }
updateFrequencyShiftLimit()
void TestMIGui::updateFrequencyShiftLimit () private
Definition at line 416 of file testmigui.cpp.
References m_settings, m_streamIndex, TestMISettings::m_streams, and ui.
Referenced by displaySettings(), and on_sampleRate_changed().
 {
     qint64 sampleRate = ui->sampleRate->getValueNew();
     ui->frequencyShift->setValueRange(false, 7, -sampleRate, sampleRate);
     ui->frequencyShift->setValue(m_settings.m_streams[m_streamIndex].m_frequencyShift);
 }
updateHardware
void TestMIGui::updateHardware () private slot
Definition at line 482 of file testmigui.cpp.
References TestMI::MsgConfigureTestSource::create(), DeviceSampleMIMO::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleMIMO, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by TestMIGui().
 {
     if (m_doApplySettings)
     {
         TestMI::MsgConfigureTestSource* message = TestMI::MsgConfigureTestSource::create(m_settings, m_forceSettings);
         m_sampleMIMO->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void TestMIGui::updateSampleRateAndFrequency () private
Definition at line 581 of file testmigui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceCenterFrequencies, m_deviceSampleRates, m_deviceUISet, m_spectrumStreamIndex, m_streamIndex, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages(), on_spectrumSource_currentIndexChanged(), and on_streamIndex_currentIndexChanged().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_deviceSampleRates[m_spectrumStreamIndex]);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequencies[m_spectrumStreamIndex]);
     ui->deviceRateText->setText(tr("%1k").arg((float) m_deviceSampleRates[m_streamIndex] / 1000));
 }
updateStatus
void TestMIGui::updateStatus () private slot
Definition at line 493 of file testmigui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by TestMIGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequencies
std::vector<quint64> TestMIGui::m_deviceCenterFrequencies private
Center frequency in device.
Definition at line 69 of file testmigui.h.
Referenced by handleInputMessages(), TestMIGui(), and updateSampleRateAndFrequency().
m_deviceSampleRates
std::vector<int> TestMIGui::m_deviceSampleRates private
Definition at line 68 of file testmigui.h.
Referenced by handleInputMessages(), TestMIGui(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* TestMIGui::m_deviceUISet private
Definition at line 58 of file testmigui.h.
Referenced by on_spectrumSource_currentIndexChanged(), on_streamIndex_currentIndexChanged(), TestMIGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool TestMIGui::m_doApplySettings private
Definition at line 64 of file testmigui.h.
Referenced by on_startStop_toggled(), and updateHardware().
m_forceSettings
bool TestMIGui::m_forceSettings private
Definition at line 65 of file testmigui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue TestMIGui::m_inputMessageQueue private
Definition at line 71 of file testmigui.h.
Referenced by handleInputMessages(), and TestMIGui().
m_lastEngineState
int TestMIGui::m_lastEngineState private
Definition at line 70 of file testmigui.h.
Referenced by updateStatus().
m_sampleMIMO
DeviceSampleMIMO* TestMIGui::m_sampleMIMO private
Definition at line 66 of file testmigui.h.
Referenced by on_record_toggled(), on_startStop_toggled(), TestMIGui(), updateFileRecordStatus(), and updateHardware().
m_settings
TestMISettings TestMIGui::m_settings private
Definition at line 59 of file testmigui.h.
Referenced by deserialize(), displaySettings(), getCenterFrequency(), handleMessage(), on_amModulation_valueChanged(), on_amplitudeCoarse_valueChanged(), on_amplitudeFine_valueChanged(), on_autoCorr_currentIndexChanged(), on_centerFrequency_changed(), on_dcBias_valueChanged(), on_decimation_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_fmDeviation_valueChanged(), on_frequencyShift_changed(), on_iBias_valueChanged(), on_modulation_currentIndexChanged(), on_modulationFrequency_valueChanged(), on_phaseImbalance_valueChanged(), on_qBias_valueChanged(), on_sampleRate_changed(), on_sampleSize_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), TestMIGui(), updateFrequencyShiftLimit(), and updateHardware().
m_spectrumStreamIndex
int TestMIGui::m_spectrumStreamIndex private
Index of the stream displayed on main spectrum.
Definition at line 61 of file testmigui.h.
Referenced by on_spectrumSource_currentIndexChanged(), on_streamIndex_currentIndexChanged(), and updateSampleRateAndFrequency().
m_statusTimer
QTimer TestMIGui::m_statusTimer private
Definition at line 63 of file testmigui.h.
Referenced by TestMIGui().
m_streamIndex
int TestMIGui::m_streamIndex private
Current stream index being dealt with.
Definition at line 60 of file testmigui.h.
Referenced by displaySettings(), getCenterFrequency(), on_amModulation_valueChanged(), on_amplitudeCoarse_valueChanged(), on_amplitudeFine_valueChanged(), on_autoCorr_currentIndexChanged(), on_centerFrequency_changed(), on_dcBias_valueChanged(), on_decimation_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_fmDeviation_valueChanged(), on_frequencyShift_changed(), on_iBias_valueChanged(), on_modulation_currentIndexChanged(), on_modulationFrequency_valueChanged(), on_phaseImbalance_valueChanged(), on_qBias_valueChanged(), on_record_toggled(), on_sampleRate_changed(), on_sampleSize_currentIndexChanged(), on_spectrumSource_currentIndexChanged(), on_streamIndex_currentIndexChanged(), setCenterFrequency(), TestMIGui(), updateFileRecordStatus(), updateFrequencyShiftLimit(), and updateSampleRateAndFrequency().
m_tickCount
std::size_t TestMIGui::m_tickCount private
Definition at line 67 of file testmigui.h.
m_updateTimer
QTimer TestMIGui::m_updateTimer private
Definition at line 62 of file testmigui.h.
Referenced by sendSettings(), TestMIGui(), and updateHardware().
ui
Ui::TestMIGui* TestMIGui::ui private
Definition at line 56 of file testmigui.h.
Referenced by displayAmplitude(), displaySettings(), handleMessage(), on_amModulation_valueChanged(), on_amplitudeCoarse_valueChanged(), on_amplitudeFine_valueChanged(), on_dcBias_valueChanged(), on_fmDeviation_valueChanged(), on_iBias_valueChanged(), on_modulationFrequency_valueChanged(), on_phaseImbalance_valueChanged(), on_qBias_valueChanged(), on_record_toggled(), on_sampleRate_changed(), on_sampleSize_currentIndexChanged(), on_spectrumSource_currentIndexChanged(), on_streamIndex_currentIndexChanged(), on_streamLock_toggled(), TestMIGui(), updateAmpCoarseLimit(), updateAmpFineLimit(), updateFileRecordStatus(), updateFrequencyShiftLimit(), updateSampleRateAndFrequency(), updateStatus(), and ~TestMIGui().
The documentation for this class was generated from the following files:
plugins/samplemimo/testmi/testmigui.h
plugins/samplemimo/testmi/testmigui.cpp