SDRAngel: SSBModGUI Class Reference
SSBModGUI Class Reference
#include <ssbmodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static SSBModGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx)
Private Slots
void handleSourceMessages ()
void on_deltaFrequency_changed (qint64 value)
void on_flipSidebands_clicked (bool checked)
void on_dsb_toggled (bool checked)
void on_audioBinaural_toggled (bool checked)
void on_audioFlipChannels_toggled (bool checked)
void on_spanLog2_valueChanged (int value)
void on_BW_valueChanged (int value)
void on_lowCut_valueChanged (int value)
void on_volume_valueChanged (int value)
void on_audioMute_toggled (bool checked)
void on_tone_toggled (bool checked)
void on_toneFrequency_valueChanged (int value)
void on_mic_toggled (bool checked)
void on_agc_toggled (bool checked)
void on_play_toggled (bool checked)
void on_playLoop_toggled (bool checked)
void on_morseKeyer_toggled (bool checked)
void on_navTimeSlider_valueChanged (int value)
void on_showFileDialog_clicked (bool checked)
void on_feedbackEnable_toggled (bool checked)
void on_feedbackVolume_valueChanged (int value)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void configureFileName ()
void audioSelect ()
void audioFeedbackSelect ()
void tick ()
Private Member Functions
SSBModGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx, QWidget *parent=0)
virtual ~SSBModGUI ()
bool blockApplySettings (bool block)
void applySettings (bool force=false)
void applyBandwidths (int spanLog2, bool force=false)
void displaySettings ()
void updateWithStreamData ()
void updateWithStreamTime ()
void channelMarkerUpdate ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::SSBModGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
SSBModSettings m_settings
bool m_doApplySettings
int m_spectrumRate
SpectrumVis * m_spectrumVis
SSBMod * m_ssbMod
MovingAverageUtil< double, double, 20 > m_channelPowerDbAvg
QString m_fileName
quint32 m_recordLength
int m_recordSampleRate
int m_samplesCount
std::size_t m_tickCount
bool m_enableNavTime
MessageQueue m_inputMessageQueue
QIcon m_iconDSBUSB
QIcon m_iconDSBLSB
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 41 of file ssbmodgui.h.
Constructor & Destructor Documentation
SSBModGUI()
SSBModGUI::SSBModGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx, QWidget * parent = 0) explicit private
Definition at line 387 of file ssbmodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applyBandwidths(), arg(), audioFeedbackSelect(), audioSelect(), channelMarkerChangedByCursor(), displaySettings(), ChannelMarker::getColor(), SSBMod::getCWKeyer(), getInputMessageQueue(), BasebandSampleSink::getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, handleSourceMessages(), SSBMod::m_channelIdURI, m_channelMarker, m_deviceUISet, m_iconDSBLSB, m_iconDSBUSB, m_settings, m_spectrumRate, m_spectrumVis, m_ssbMod, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerTxChannelInstance(), resetToDefaults(), SDR_TX_SCALEF, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), SSBModSettings::setChannelMarker(), ChannelMarker::setColor(), SSBModSettings::setCWKeyerGUI(), BasebandSampleSource::setMessageQueueToGUI(), ChannelMarker::setSidebands(), ChannelMarker::setSourceOrSinkStream(), SSBModSettings::setSpectrumGUI(), SSBMod::setSpectrumSampleSink(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ChannelMarker::setVisible(), tick(), ui, ChannelMarker::usb, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                      :
     RollupWidget(parent),
     ui(new Ui::SSBModGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_doApplySettings(true),
     m_spectrumRate(6000),
     m_recordLength(0),
     m_recordSampleRate(48000),
     m_samplesCount(0),
     m_tickCount(0),
     m_enableNavTime(false)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_spectrumVis = new SpectrumVis(SDR_TX_SCALEF, ui->glSpectrum);
     m_ssbMod = (SSBMod*) channelTx; //new SSBMod(m_deviceUISet->m_deviceSinkAPI);
     m_ssbMod->setSpectrumSampleSink(m_spectrumVis);
     m_ssbMod->setMessageQueueToGUI(getInputMessageQueue());
     resetToDefaults();
     ui->glSpectrum->setCenterFrequency(m_spectrumRate/2);
     ui->glSpectrum->setSampleRate(m_spectrumRate);
     ui->glSpectrum->setDisplayWaterfall(true);
     ui->glSpectrum->setDisplayMaxHold(true);
     ui->glSpectrum->setSsbSpectrum(true);
     ui->glSpectrum->connectTimer(MainWindow::getInstance()->getMasterTimer());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     CRightClickEnabler *audioMuteRightClickEnabler = new CRightClickEnabler(ui->mic);
     connect(audioMuteRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioSelect()));
     CRightClickEnabler *feedbackRightClickEnabler = new CRightClickEnabler(ui->feedbackEnable);
     connect(feedbackRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioFeedbackSelect()));
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(Qt::green);
     m_channelMarker.setBandwidth(m_spectrumRate);
     m_channelMarker.setSidebands(ChannelMarker::usb);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("SSB Modulator");
     m_channelMarker.setSourceOrSinkStream(false);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true);
     setTitleColor(m_channelMarker.getColor());
     m_deviceUISet->registerTxChannelInstance(SSBMod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     ui->cwKeyerGUI->setCWKeyer(m_ssbMod->getCWKeyer());
     ui->spectrumGUI->setBuddies(m_spectrumVis->getInputMessageQueue(), m_spectrumVis, ui->glSpectrum);
     m_settings.setChannelMarker(&m_channelMarker);
     m_settings.setSpectrumGUI(ui->spectrumGUI);
     m_settings.setCWKeyerGUI(ui->cwKeyerGUI);
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     connect(m_ssbMod, SIGNAL(levelChanged(qreal, qreal, int)), ui->volumeMeter, SLOT(levelChanged(qreal, qreal, int)));
     m_iconDSBUSB.addPixmap(QPixmap("://dsb.png"), QIcon::Normal, QIcon::On);
     m_iconDSBUSB.addPixmap(QPixmap("://usb.png"), QIcon::Normal, QIcon::Off);
     m_iconDSBLSB.addPixmap(QPixmap("://dsb.png"), QIcon::Normal, QIcon::On);
     m_iconDSBLSB.addPixmap(QPixmap("://lsb.png"), QIcon::Normal, QIcon::Off);
     displaySettings();
     applyBandwidths(5 - ui->spanLog2->value(), true); // does applySettings(true)
 }
~SSBModGUI()
SSBModGUI::~SSBModGUI () private virtual
Definition at line 469 of file ssbmodgui.cpp.
References m_deviceUISet, m_spectrumVis, m_ssbMod, DeviceUISet::removeTxChannelInstance(), and ui.
 {
     m_deviceUISet->removeTxChannelInstance(this);
     delete m_ssbMod; // TODO: check this: when the GUI closes it has to delete the modulator
     delete m_spectrumVis;
     delete ui;
 }
Member Function Documentation
applyBandwidths()
void SSBModGUI::applyBandwidths (int spanLog2, bool force = false) private
Definition at line 507 of file ssbmodgui.cpp.
References applySettings(), arg(), blockApplySettings(), ChannelMarker::dsb, SSBMod::getAudioSampleRate(), ChannelMarker::lsb, SSBModSettings::m_bandwidth, m_channelMarker, SSBModSettings::m_dsb, m_iconDSBLSB, m_iconDSBUSB, SSBModSettings::m_lowCutoff, m_settings, SSBModSettings::m_spanLog2, m_spectrumRate, m_ssbMod, ChannelMarker::setBandwidth(), ChannelMarker::setLowCutoff(), ChannelMarker::setSidebands(), ui, and ChannelMarker::usb.
Referenced by deserialize(), handleMessage(), on_BW_valueChanged(), on_dsb_toggled(), on_lowCut_valueChanged(), on_spanLog2_valueChanged(), and SSBModGUI().
 {
     bool dsb = ui->dsb->isChecked();
     m_spectrumRate = m_ssbMod->getAudioSampleRate() / (1<<spanLog2);
     int bw = ui->BW->value();
     int lw = ui->lowCut->value();
     int bwMax = m_ssbMod->getAudioSampleRate() / (100*(1<<spanLog2));
     int tickInterval = m_spectrumRate / 1200;
     tickInterval = tickInterval == 0 ? 1 : tickInterval;
     qDebug() << "SSBModGUI::applyBandwidths:"
             << " dsb: " << dsb
             << " spanLog2: " << spanLog2
             << " m_spectrumRate: " << m_spectrumRate
             << " bw: " << bw
             << " lw: " << lw
             << " bwMax: " << bwMax
             << " tickInterval: " << tickInterval;
     ui->BW->setTickInterval(tickInterval);
     ui->lowCut->setTickInterval(tickInterval);
     bw = bw < -bwMax ? -bwMax : bw > bwMax ? bwMax : bw;
     if (bw < 0) {
         lw = lw < bw+1 ? bw+1 : lw < 0 ? lw : 0;
     } else if (bw > 0) {
         lw = lw > bw-1 ? bw-1 : lw < 0 ? 0 : lw;
     } else {
         lw = 0;
     }
     if (dsb)
     {
         bw = bw < 0 ? -bw : bw;
         lw = 0;
     }
     QString spanStr = QString::number(bwMax/10.0, 'f', 1);
     QString bwStr   = QString::number(bw/10.0, 'f', 1);
     QString lwStr   = QString::number(lw/10.0, 'f', 1);
     if (dsb)
     {
         ui->BWText->setText(tr("%1%2k").arg(QChar(0xB1, 0x00)).arg(bwStr));
         ui->spanText->setText(tr("%1%2k").arg(QChar(0xB1, 0x00)).arg(spanStr));
         ui->scaleMinus->setText("0");
         ui->scaleCenter->setText("");
         ui->scalePlus->setText(tr("%1").arg(QChar(0xB1, 0x00)));
         ui->lsbLabel->setText("");
         ui->usbLabel->setText("");
         ui->glSpectrum->setCenterFrequency(0);
         ui->glSpectrum->setSampleRate(2*m_spectrumRate);
         ui->glSpectrum->setSsbSpectrum(false);
         ui->glSpectrum->setLsbDisplay(false);
     }
     else
     {
         ui->BWText->setText(tr("%1k").arg(bwStr));
         ui->spanText->setText(tr("%1k").arg(spanStr));
         ui->scaleMinus->setText("-");
         ui->scaleCenter->setText("0");
         ui->scalePlus->setText("+");
         ui->lsbLabel->setText("LSB");
         ui->usbLabel->setText("USB");
         ui->glSpectrum->setCenterFrequency(m_spectrumRate/2);
         ui->glSpectrum->setSampleRate(m_spectrumRate);
         ui->glSpectrum->setSsbSpectrum(true);
         ui->glSpectrum->setLsbDisplay(bw < 0);
     }
     ui->lowCutText->setText(tr("%1k").arg(lwStr));
     ui->BW->blockSignals(true);
     ui->lowCut->blockSignals(true);
     ui->BW->setMaximum(bwMax);
     ui->BW->setMinimum(dsb ? 0 : -bwMax);
     ui->BW->setValue(bw);
     ui->lowCut->setMaximum(dsb ? 0 :  bwMax);
     ui->lowCut->setMinimum(dsb ? 0 : -bwMax);
     ui->lowCut->setValue(lw);
     ui->lowCut->blockSignals(false);
     ui->BW->blockSignals(false);
     m_settings.m_dsb = dsb;
     m_settings.m_spanLog2 = spanLog2;
     m_settings.m_bandwidth = bw * 100;
     m_settings.m_lowCutoff = lw * 100;
     applySettings(force);
     bool applySettingsWereBlocked = blockApplySettings(true);
     m_channelMarker.setBandwidth(bw * 200);
     m_channelMarker.setSidebands(dsb ? ChannelMarker::dsb : bw < 0 ? ChannelMarker::lsb : ChannelMarker::usb);
     ui->dsb->setIcon(bw < 0 ? m_iconDSBLSB : m_iconDSBUSB);
     if (!dsb) { m_channelMarker.setLowCutoff(lw * 100); }
     blockApplySettings(applySettingsWereBlocked);
 }
applySettings()
void SSBModGUI::applySettings (bool force = false) private
Definition at line 484 of file ssbmodgui.cpp.
References SSBMod::MsgConfigureSSBMod::create(), SSBMod::MsgConfigureChannelizer::create(), BasebandSampleSource::getInputMessageQueue(), SSBModSettings::m_bandwidth, m_doApplySettings, SSBModSettings::m_inputFrequencyOffset, SSBModSettings::m_lowCutoff, m_settings, m_ssbMod, SSBModSettings::m_usb, and MessageQueue::push().
Referenced by applyBandwidths(), audioFeedbackSelect(), audioSelect(), channelMarkerChangedByCursor(), channelMarkerUpdate(), on_agc_toggled(), on_audioBinaural_toggled(), on_audioFlipChannels_toggled(), on_audioMute_toggled(), on_deltaFrequency_changed(), on_feedbackEnable_toggled(), on_feedbackVolume_valueChanged(), on_mic_toggled(), on_morseKeyer_toggled(), on_play_toggled(), on_playLoop_toggled(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), and setCenterFrequency().
 {
     if (m_doApplySettings)
     {
         SSBMod::MsgConfigureChannelizer *msgChan = SSBMod::MsgConfigureChannelizer::create(
                 48000, m_settings.m_inputFrequencyOffset);
         m_ssbMod->getInputMessageQueue()->push(msgChan);
         SSBModSettings mod_settings; // different USB/LSB convention between modulator and GUI
         mod_settings = m_settings;
         if (mod_settings.m_bandwidth > 0) {
             mod_settings.m_usb = true;
         } else {
             mod_settings.m_bandwidth = -mod_settings.m_bandwidth;
             mod_settings.m_lowCutoff = -mod_settings.m_lowCutoff;
             mod_settings.m_usb = false;
         }
         SSBMod::MsgConfigureSSBMod *msg = SSBMod::MsgConfigureSSBMod::create(mod_settings, force);
         m_ssbMod->getInputMessageQueue()->push(msg);
     }
 }
audioFeedbackSelect
void SSBModGUI::audioFeedbackSelect () private slot
Definition at line 728 of file ssbmodgui.cpp.
References applySettings(), audioSelect(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, SSBModSettings::m_audioDeviceName, SSBModSettings::m_feedbackAudioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by SSBModGUI().
 {
     qDebug("SSBModGUI::audioFeedbackSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName, false); // false for output
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_feedbackAudioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
audioSelect
void SSBModGUI::audioSelect () private slot
Definition at line 715 of file ssbmodgui.cpp.
References applySettings(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, SSBModSettings::m_audioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by audioFeedbackSelect(), and SSBModGUI().
 {
     qDebug("SSBModGUI::audioSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName, true); // true for input
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_audioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
blockApplySettings()
bool SSBModGUI::blockApplySettings (bool block) private
Definition at line 477 of file ssbmodgui.cpp.
References m_doApplySettings.
Referenced by applyBandwidths(), displaySettings(), and handleMessage().
 {
     bool ret = !m_doApplySettings;
     m_doApplySettings = !block;
     return ret;
 }
channelMarkerChangedByCursor
void SSBModGUI::channelMarkerChangedByCursor () slot
Definition at line 149 of file ssbmodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, SSBModSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by SSBModGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
channelMarkerUpdate()
void SSBModGUI::channelMarkerUpdate () private
Definition at line 156 of file ssbmodgui.cpp.
References applySettings(), displaySettings(), ChannelMarker::getColor(), m_channelMarker, SSBModSettings::m_rgbColor, and m_settings.
 {
     m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
     displaySettings();
     applySettings();
 }
configureFileName
void SSBModGUI::configureFileName () private slot
Definition at line 342 of file ssbmodgui.cpp.
References SSBMod::MsgConfigureFileSourceName::create(), BasebandSampleSource::getInputMessageQueue(), m_fileName, m_ssbMod, and MessageQueue::push().
Referenced by on_showFileDialog_clicked().
 {
     qDebug() << "FileSourceGui::configureFileName: " << m_fileName.toStdString().c_str();
     SSBMod::MsgConfigureFileSourceName* message = SSBMod::MsgConfigureFileSourceName::create(m_fileName);
     m_ssbMod->getInputMessageQueue()->push(message);
 }
create()
SSBModGUI * SSBModGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx) static
Definition at line 39 of file ssbmodgui.cpp.
References SSBModGUI().
Referenced by SSBModPlugin::createTxChannelGUI().
 {
     SSBModGUI* gui = new SSBModGUI(pluginAPI, deviceUISet, channelTx);
     return gui;
 }
deserialize()
bool SSBModGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 81 of file ssbmodgui.cpp.
References applyBandwidths(), SSBModSettings::deserialize(), displaySettings(), m_settings, SSBModSettings::resetToDefaults(), and ui.
 {
     if(m_settings.deserialize(data))
     {
         qDebug("SSBModGUI::deserialize");
         displaySettings();
         applyBandwidths(5 - ui->spanLog2->value(), true); // does applySettings(true)
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         displaySettings();
         applyBandwidths(5 - ui->spanLog2->value(), true); // does applySettings(true)
         return false;
     }
 }
destroy()
void SSBModGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 45 of file ssbmodgui.cpp.
 {
     delete this;
 }
displaySettings()
void SSBModGUI::displaySettings () private
Definition at line 611 of file ssbmodgui.cpp.
References arg(), blockApplySettings(), ChannelMarker::dsb, ChannelMarker::getTitle(), ChannelMarker::lsb, SSBModSettings::m_agc, SSBModSettings::m_audioBinaural, SSBModSettings::m_audioFlipChannels, SSBModSettings::m_audioMute, SSBModSettings::m_bandwidth, m_channelMarker, SSBModSettings::m_dsb, SSBModSettings::m_feedbackAudioEnable, SSBModSettings::m_feedbackVolumeFactor, m_iconDSBLSB, m_iconDSBUSB, SSBModSettings::m_inputFrequencyOffset, SSBModSettings::m_lowCutoff, SSBModSettings::m_modAFInput, SSBModSettings::m_playLoop, SSBModSettings::m_rgbColor, m_settings, SSBModSettings::m_spanLog2, SSBModSettings::m_title, SSBModSettings::m_toneFrequency, SSBModSettings::m_volumeFactor, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setLowCutoff(), ChannelMarker::setSidebands(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ui, and ChannelMarker::usb.
Referenced by channelMarkerUpdate(), deserialize(), handleMessage(), and SSBModGUI().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.setBandwidth(m_settings.m_bandwidth * 2);
     m_channelMarker.setLowCutoff(m_settings.m_lowCutoff);
     ui->flipSidebands->setEnabled(!m_settings.m_dsb);
     if (m_settings.m_dsb) {
         m_channelMarker.setSidebands(ChannelMarker::dsb);
     } else {
         if (m_settings.m_bandwidth < 0) {
             m_channelMarker.setSidebands(ChannelMarker::lsb);
             ui->dsb->setIcon(m_iconDSBLSB);
         } else {
             m_channelMarker.setSidebands(ChannelMarker::usb);
             ui->dsb->setIcon(m_iconDSBUSB);
         }
     }
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->agc->setChecked(m_settings.m_agc);
     ui->audioBinaural->setChecked(m_settings.m_audioBinaural);
     ui->audioFlipChannels->setChecked(m_settings.m_audioFlipChannels);
     ui->audioMute->setChecked(m_settings.m_audioMute);
     ui->playLoop->setChecked(m_settings.m_playLoop);
     // Prevent uncontrolled triggering of applyBandwidths
     ui->spanLog2->blockSignals(true);
     ui->dsb->blockSignals(true);
     ui->BW->blockSignals(true);
     ui->dsb->setChecked(m_settings.m_dsb);
     ui->spanLog2->setValue(5 - m_settings.m_spanLog2);
     ui->BW->setValue(roundf(m_settings.m_bandwidth/100.0));
     QString s = QString::number(m_settings.m_bandwidth/1000.0, 'f', 1);
     if (m_settings.m_dsb)
     {
         ui->BWText->setText(tr("%1%2k").arg(QChar(0xB1, 0x00)).arg(s));
     }
     else
     {
         ui->BWText->setText(tr("%1k").arg(s));
     }
     ui->spanLog2->blockSignals(false);
     ui->dsb->blockSignals(false);
     ui->BW->blockSignals(false);
     // The only one of the four signals triggering applyBandwidths will trigger it once only with all other values
     // set correctly and therefore validate the settings and apply them to dependent widgets
     ui->lowCut->setValue(m_settings.m_lowCutoff / 100.0);
     ui->lowCutText->setText(tr("%1k").arg(m_settings.m_lowCutoff / 1000.0));
     ui->deltaFrequency->setValue(m_settings.m_inputFrequencyOffset);
     ui->toneFrequency->setValue(roundf(m_settings.m_toneFrequency / 10.0));
     ui->toneFrequencyText->setText(QString("%1k").arg(m_settings.m_toneFrequency / 1000.0, 0, 'f', 2));
     ui->volume->setValue(m_settings.m_volumeFactor * 10.0);
     ui->volumeText->setText(QString("%1").arg(m_settings.m_volumeFactor, 0, 'f', 1));
     ui->tone->setEnabled((m_settings.m_modAFInput == SSBModSettings::SSBModInputAF::SSBModInputTone)
             || (m_settings.m_modAFInput == SSBModSettings::SSBModInputAF::SSBModInputNone));
     ui->mic->setEnabled((m_settings.m_modAFInput == SSBModSettings::SSBModInputAF::SSBModInputAudio)
             || (m_settings.m_modAFInput == SSBModSettings::SSBModInputAF::SSBModInputNone));
     ui->play->setEnabled((m_settings.m_modAFInput == SSBModSettings::SSBModInputAF::SSBModInputFile)
             || (m_settings.m_modAFInput == SSBModSettings::SSBModInputAF::SSBModInputNone));
     ui->morseKeyer->setEnabled((m_settings.m_modAFInput == SSBModSettings::SSBModInputAF::SSBModInputCWTone)
             || (m_settings.m_modAFInput == SSBModSettings::SSBModInputAF::SSBModInputNone));
     ui->tone->setChecked(m_settings.m_modAFInput == SSBModSettings::SSBModInputAF::SSBModInputTone);
     ui->mic->setChecked(m_settings.m_modAFInput == SSBModSettings::SSBModInputAF::SSBModInputAudio);
     ui->play->setChecked(m_settings.m_modAFInput == SSBModSettings::SSBModInputAF::SSBModInputFile);
     ui->morseKeyer->setChecked(m_settings.m_modAFInput == SSBModSettings::SSBModInputAF::SSBModInputCWTone);
     ui->feedbackEnable->setChecked(m_settings.m_feedbackAudioEnable);
     ui->feedbackVolume->setValue(roundf(m_settings.m_feedbackVolumeFactor * 100.0));
     ui->feedbackVolumeText->setText(QString("%1").arg(m_settings.m_feedbackVolumeFactor, 0, 'f', 2));
     blockApplySettings(false);
 }
enterEvent()
void SSBModGUI::enterEvent (QEvent *) private
Definition at line 710 of file ssbmodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 SSBModGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 60 of file ssbmodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
{
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* SSBModGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 56 of file ssbmodgui.h.
Referenced by handleSourceMessages(), and SSBModGUI().
 { return &m_inputMessageQueue; }
getName()
QString SSBModGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 55 of file ssbmodgui.cpp.
 {
     return objectName();
 }
handleMessage()
bool SSBModGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 99 of file ssbmodgui.cpp.
References applyBandwidths(), blockApplySettings(), displaySettings(), SSBMod::getAudioSampleRate(), SSBMod::MsgConfigureSSBMod::getSettings(), CWKeyer::MsgConfigureCWKeyer::getSettings(), SSBModSettings::m_bandwidth, SSBModSettings::m_lowCutoff, m_recordLength, m_recordSampleRate, m_samplesCount, m_settings, m_ssbMod, SSBModSettings::m_usb, Message::match(), ui, updateWithStreamData(), and updateWithStreamTime().
Referenced by handleSourceMessages().
 {
     if (SSBMod::MsgReportFileSourceStreamData::match(message))
     {
         m_recordSampleRate = ((SSBMod::MsgReportFileSourceStreamData&)message).getSampleRate();
         m_recordLength = ((SSBMod::MsgReportFileSourceStreamData&)message).getRecordLength();
         m_samplesCount = 0;
         updateWithStreamData();
         return true;
     }
     else if (SSBMod::MsgReportFileSourceStreamTiming::match(message))
     {
         m_samplesCount = ((SSBMod::MsgReportFileSourceStreamTiming&)message).getSamplesCount();
         updateWithStreamTime();
         return true;
     }
     else if (DSPConfigureAudio::match(message))
     {
         qDebug("SSBModGUI::handleMessage: DSPConfigureAudio: %d", m_ssbMod->getAudioSampleRate());
         applyBandwidths(5 - ui->spanLog2->value()); // will update spectrum details with new sample rate
         return true;
     }
     else if (SSBMod::MsgConfigureSSBMod::match(message))
     {
         SSBModSettings mod_settings; // different USB/LSB convention between modulator and GUI
         const SSBMod::MsgConfigureSSBMod& cfg = (SSBMod::MsgConfigureSSBMod&) message;
         mod_settings = cfg.getSettings();
         if (mod_settings.m_usb == false) {
             mod_settings.m_bandwidth = -mod_settings.m_bandwidth;
             mod_settings.m_lowCutoff = -mod_settings.m_lowCutoff;
         }
         m_settings = mod_settings;
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (CWKeyer::MsgConfigureCWKeyer::match(message))
     {
         const CWKeyer::MsgConfigureCWKeyer& cfg = (CWKeyer::MsgConfigureCWKeyer&) message;
         ui->cwKeyerGUI->setSettings(cfg.getSettings());
         ui->cwKeyerGUI->displaySettings();
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void SSBModGUI::handleSourceMessages () private slot
Definition at line 163 of file ssbmodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by SSBModGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void SSBModGUI::leaveEvent (QEvent *) private
Definition at line 705 of file ssbmodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_agc_toggled
void SSBModGUI::on_agc_toggled (bool checked) private slot
Definition at line 308 of file ssbmodgui.cpp.
References applySettings(), SSBModSettings::m_agc, and m_settings.
 {
     m_settings.m_agc = checked;
     applySettings();
 }
on_audioBinaural_toggled
void SSBModGUI::on_audioBinaural_toggled (bool checked) private slot
Definition at line 198 of file ssbmodgui.cpp.
References applySettings(), SSBModSettings::m_audioBinaural, and m_settings.
 {
     m_settings.m_audioBinaural = checked;
     applySettings();
 }
on_audioFlipChannels_toggled
void SSBModGUI::on_audioFlipChannels_toggled (bool checked) private slot
Definition at line 204 of file ssbmodgui.cpp.
References applySettings(), SSBModSettings::m_audioFlipChannels, and m_settings.
 {
     m_settings.m_audioFlipChannels = checked;
     applySettings();
 }
on_audioMute_toggled
void SSBModGUI::on_audioMute_toggled (bool checked) private slot
Definition at line 245 of file ssbmodgui.cpp.
References applySettings(), SSBModSettings::m_audioMute, and m_settings.
 {
     m_settings.m_audioMute = checked;
     applySettings();
 }
on_BW_valueChanged
void SSBModGUI::on_BW_valueChanged (int value) private slot
Definition at line 219 of file ssbmodgui.cpp.
References applyBandwidths(), and ui.
 {
     (void) value;
     applyBandwidths(5 - ui->spanLog2->value());
 }
on_deltaFrequency_changed
void SSBModGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 176 of file ssbmodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, SSBModSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_dsb_toggled
void SSBModGUI::on_dsb_toggled (bool checked) private slot
Definition at line 192 of file ssbmodgui.cpp.
References applyBandwidths(), and ui.
 {
     ui->flipSidebands->setEnabled(!dsb);
     applyBandwidths(5 - ui->spanLog2->value());
 }
on_feedbackEnable_toggled
void SSBModGUI::on_feedbackEnable_toggled (bool checked) private slot
Definition at line 295 of file ssbmodgui.cpp.
References applySettings(), SSBModSettings::m_feedbackAudioEnable, and m_settings.
 {
     m_settings.m_feedbackAudioEnable = checked;
     applySettings();
 }
on_feedbackVolume_valueChanged
void SSBModGUI::on_feedbackVolume_valueChanged (int value) private slot
Definition at line 301 of file ssbmodgui.cpp.
References applySettings(), arg(), SSBModSettings::m_feedbackVolumeFactor, m_settings, and ui.
 {
     ui->feedbackVolumeText->setText(QString("%1").arg(value / 100.0, 0, 'f', 2));
     m_settings.m_feedbackVolumeFactor = value / 100.0;
     applySettings();
 }
on_flipSidebands_clicked
void SSBModGUI::on_flipSidebands_clicked (bool checked) private slot
Definition at line 183 of file ssbmodgui.cpp.
References ui.
 {
     (void) checked;
     int bwValue = ui->BW->value();
     int lcValue = ui->lowCut->value();
     ui->BW->setValue(-bwValue);
     ui->lowCut->setValue(-lcValue);
 }
on_lowCut_valueChanged
void SSBModGUI::on_lowCut_valueChanged (int value) private slot
Definition at line 225 of file ssbmodgui.cpp.
References applyBandwidths(), and ui.
 {
     (void) value;
     applyBandwidths(5 - ui->spanLog2->value());
 }
on_mic_toggled
void SSBModGUI::on_mic_toggled (bool checked) private slot
Definition at line 286 of file ssbmodgui.cpp.
References applySettings(), SSBModSettings::m_modAFInput, m_settings, SSBModSettings::SSBModInputAudio, SSBModSettings::SSBModInputNone, and ui.
 {
     ui->play->setEnabled(!checked); // release other source inputs
     ui->morseKeyer->setEnabled(!checked);
     ui->tone->setEnabled(!checked); // release other source inputs
     m_settings.m_modAFInput = checked ? SSBModSettings::SSBModInputAudio : SSBModSettings::SSBModInputNone;
     applySettings();
 }
on_morseKeyer_toggled
void SSBModGUI::on_morseKeyer_toggled (bool checked) private slot
Definition at line 277 of file ssbmodgui.cpp.
References applySettings(), SSBModSettings::m_modAFInput, m_settings, SSBModSettings::SSBModInputCWTone, SSBModSettings::SSBModInputNone, and ui.
 {
     ui->play->setEnabled(!checked); // release other source inputs
     ui->tone->setEnabled(!checked); // release other source inputs
     ui->mic->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? SSBModSettings::SSBModInputCWTone : SSBModSettings::SSBModInputNone;
     applySettings();
 }
on_navTimeSlider_valueChanged
void SSBModGUI::on_navTimeSlider_valueChanged (int value) private slot
Definition at line 314 of file ssbmodgui.cpp.
References SSBMod::MsgConfigureFileSourceSeek::create(), BasebandSampleSource::getInputMessageQueue(), m_enableNavTime, m_recordLength, m_ssbMod, and MessageQueue::push().
 {
     if (m_enableNavTime && ((value >= 0) && (value <= 100)))
     {
         int t_sec = (m_recordLength * value) / 100;
         QTime t(0, 0, 0, 0);
         t = t.addSecs(t_sec);
         SSBMod::MsgConfigureFileSourceSeek* message = SSBMod::MsgConfigureFileSourceSeek::create(value);
         m_ssbMod->getInputMessageQueue()->push(message);
     }
 }
on_play_toggled
void SSBModGUI::on_play_toggled (bool checked) private slot
Definition at line 257 of file ssbmodgui.cpp.
References applySettings(), m_enableNavTime, SSBModSettings::m_modAFInput, m_settings, SSBModSettings::SSBModInputFile, SSBModSettings::SSBModInputNone, and ui.
 {
     ui->tone->setEnabled(!checked); // release other source inputs
     ui->morseKeyer->setEnabled(!checked);
     ui->mic->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? SSBModSettings::SSBModInputFile : SSBModSettings::SSBModInputNone;
     applySettings();
     ui->navTimeSlider->setEnabled(!checked);
     m_enableNavTime = !checked;
 }
on_playLoop_toggled
void SSBModGUI::on_playLoop_toggled (bool checked) private slot
Definition at line 251 of file ssbmodgui.cpp.
References applySettings(), SSBModSettings::m_playLoop, and m_settings.
 {
     m_settings.m_playLoop = checked;
     applySettings();
 }
on_showFileDialog_clicked
void SSBModGUI::on_showFileDialog_clicked (bool checked) private slot
Definition at line 327 of file ssbmodgui.cpp.
References configureFileName(), m_fileName, and ui.
 {
     (void) checked;
     QString fileName = QFileDialog::getOpenFileName(this,
         tr("Open raw audio file"), ".", tr("Raw audio Files (*.raw)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "")
     {
         m_fileName = fileName;
         ui->recordFileText->setText(m_fileName);
         ui->play->setEnabled(true);
         configureFileName();
     }
 }
on_spanLog2_valueChanged
void SSBModGUI::on_spanLog2_valueChanged (int value) private slot
Definition at line 210 of file ssbmodgui.cpp.
References applyBandwidths().
 {
     if ((value < 0) || (value > 4)) {
         return;
     }
     applyBandwidths(5 - value);
 }
on_tone_toggled
void SSBModGUI::on_tone_toggled (bool checked) private slot
Definition at line 268 of file ssbmodgui.cpp.
References applySettings(), SSBModSettings::m_modAFInput, m_settings, SSBModSettings::SSBModInputNone, SSBModSettings::SSBModInputTone, and ui.
 {
     ui->play->setEnabled(!checked); // release other source inputs
     ui->morseKeyer->setEnabled(!checked);
     ui->mic->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? SSBModSettings::SSBModInputTone : SSBModSettings::SSBModInputNone;
     applySettings();
 }
on_toneFrequency_valueChanged
void SSBModGUI::on_toneFrequency_valueChanged (int value) private slot
Definition at line 231 of file ssbmodgui.cpp.
References applySettings(), arg(), m_settings, SSBModSettings::m_toneFrequency, and ui.
 {
     ui->toneFrequencyText->setText(QString("%1k").arg(value / 100.0, 0, 'f', 2));
     m_settings.m_toneFrequency = value * 10.0;
     applySettings();
 }
on_volume_valueChanged
void SSBModGUI::on_volume_valueChanged (int value) private slot
Definition at line 238 of file ssbmodgui.cpp.
References applySettings(), arg(), m_settings, SSBModSettings::m_volumeFactor, and ui.
 {
     ui->volumeText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_volumeFactor = value / 10.0;
     applySettings();
 }
onMenuDialogCalled
void SSBModGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 355 of file ssbmodgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, SSBModSettings::m_inputFrequencyOffset, SSBModSettings::m_reverseAPIAddress, SSBModSettings::m_reverseAPIChannelIndex, SSBModSettings::m_reverseAPIDeviceIndex, SSBModSettings::m_reverseAPIPort, SSBModSettings::m_rgbColor, m_settings, SSBModSettings::m_title, SSBModSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by SSBModGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void SSBModGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 349 of file ssbmodgui.cpp.
Referenced by SSBModGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void SSBModGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 71 of file ssbmodgui.cpp.
References m_settings, and SSBModSettings::resetToDefaults().
Referenced by SSBModGUI().
 {
     m_settings.resetToDefaults();
 }
serialize()
QByteArray SSBModGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 76 of file ssbmodgui.cpp.
References m_settings, and SSBModSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void SSBModGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 64 of file ssbmodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, SSBModSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
setName()
void SSBModGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 50 of file ssbmodgui.cpp.
 {
     setObjectName(name);
 }
tick
void SSBModGUI::tick () private slot
Definition at line 741 of file ssbmodgui.cpp.
References arg(), SSBMod::MsgConfigureFileSourceStreamTiming::create(), CalcDb::dbPower(), BasebandSampleSource::getInputMessageQueue(), SSBMod::getMagSq(), m_channelPowerDbAvg, SSBModSettings::m_modAFInput, m_settings, m_ssbMod, m_tickCount, MessageQueue::push(), SSBModSettings::SSBModInputFile, and ui.
Referenced by SSBModGUI().
 {
     double powDb = CalcDb::dbPower(m_ssbMod->getMagSq());
     m_channelPowerDbAvg(powDb);
     ui->channelPower->setText(tr("%1 dB").arg(m_channelPowerDbAvg.asDouble(), 0, 'f', 1));
     if (((++m_tickCount & 0xf) == 0) && (m_settings.m_modAFInput == SSBModSettings::SSBModInputFile))
     {
         SSBMod::MsgConfigureFileSourceStreamTiming* message = SSBMod::MsgConfigureFileSourceStreamTiming::create();
         m_ssbMod->getInputMessageQueue()->push(message);
     }
 }
updateWithStreamData()
void SSBModGUI::updateWithStreamData () private
Definition at line 754 of file ssbmodgui.cpp.
References m_recordLength, ui, and updateWithStreamTime().
Referenced by handleMessage().
 {
     QTime recordLength(0, 0, 0, 0);
     recordLength = recordLength.addSecs(m_recordLength);
     QString s_time = recordLength.toString("HH:mm:ss");
     ui->recordLengthText->setText(s_time);
     updateWithStreamTime();
 }
updateWithStreamTime()
void SSBModGUI::updateWithStreamTime () private
Definition at line 763 of file ssbmodgui.cpp.
References m_enableNavTime, m_recordLength, m_recordSampleRate, m_samplesCount, and ui.
Referenced by handleMessage(), and updateWithStreamData().
 {
     int t_sec = 0;
     int t_msec = 0;
     if (m_recordSampleRate > 0)
     {
         t_msec = ((m_samplesCount * 1000) / m_recordSampleRate) % 1000;
         t_sec = m_samplesCount / m_recordSampleRate;
     }
     QTime t(0, 0, 0, 0);
     t = t.addSecs(t_sec);
     t = t.addMSecs(t_msec);
     QString s_timems = t.toString("HH:mm:ss.zzz");
     QString s_time = t.toString("HH:mm:ss");
     ui->relTimeText->setText(s_timems);
     if (!m_enableNavTime)
     {
         float posRatio = (float) t_sec / (float) m_recordLength;
         ui->navTimeSlider->setValue((int) (posRatio * 100.0));
     }
 }
Member Data Documentation
m_channelMarker
ChannelMarker SSBModGUI::m_channelMarker private
Definition at line 66 of file ssbmodgui.h.
Referenced by applyBandwidths(), channelMarkerChangedByCursor(), channelMarkerUpdate(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), onMenuDialogCalled(), setCenterFrequency(), and SSBModGUI().
m_channelPowerDbAvg
MovingAverageUtil<double, double, 20> SSBModGUI::m_channelPowerDbAvg private
Definition at line 73 of file ssbmodgui.h.
Referenced by tick().
m_deviceUISet
DeviceUISet* SSBModGUI::m_deviceUISet private
Definition at line 65 of file ssbmodgui.h.
Referenced by SSBModGUI(), and ~SSBModGUI().
m_doApplySettings
bool SSBModGUI::m_doApplySettings private
Definition at line 68 of file ssbmodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_enableNavTime
bool SSBModGUI::m_enableNavTime private
Definition at line 80 of file ssbmodgui.h.
Referenced by on_navTimeSlider_valueChanged(), on_play_toggled(), and updateWithStreamTime().
m_fileName
QString SSBModGUI::m_fileName private
Definition at line 75 of file ssbmodgui.h.
Referenced by configureFileName(), and on_showFileDialog_clicked().
m_iconDSBLSB
QIcon SSBModGUI::m_iconDSBLSB private
Definition at line 84 of file ssbmodgui.h.
Referenced by applyBandwidths(), displaySettings(), and SSBModGUI().
m_iconDSBUSB
QIcon SSBModGUI::m_iconDSBUSB private
Definition at line 83 of file ssbmodgui.h.
Referenced by applyBandwidths(), displaySettings(), and SSBModGUI().
m_inputMessageQueue
MessageQueue SSBModGUI::m_inputMessageQueue private
Definition at line 81 of file ssbmodgui.h.
m_pluginAPI
PluginAPI* SSBModGUI::m_pluginAPI private
Definition at line 64 of file ssbmodgui.h.
m_recordLength
quint32 SSBModGUI::m_recordLength private
Definition at line 76 of file ssbmodgui.h.
Referenced by handleMessage(), on_navTimeSlider_valueChanged(), updateWithStreamData(), and updateWithStreamTime().
m_recordSampleRate
int SSBModGUI::m_recordSampleRate private
Definition at line 77 of file ssbmodgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_samplesCount
int SSBModGUI::m_samplesCount private
Definition at line 78 of file ssbmodgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_settings
SSBModSettings SSBModGUI::m_settings private
Definition at line 67 of file ssbmodgui.h.
Referenced by applyBandwidths(), applySettings(), audioFeedbackSelect(), audioSelect(), channelMarkerChangedByCursor(), channelMarkerUpdate(), deserialize(), displaySettings(), handleMessage(), on_agc_toggled(), on_audioBinaural_toggled(), on_audioFlipChannels_toggled(), on_audioMute_toggled(), on_deltaFrequency_changed(), on_feedbackEnable_toggled(), on_feedbackVolume_valueChanged(), on_mic_toggled(), on_morseKeyer_toggled(), on_play_toggled(), on_playLoop_toggled(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), serialize(), setCenterFrequency(), SSBModGUI(), and tick().
m_spectrumRate
int SSBModGUI::m_spectrumRate private
Definition at line 69 of file ssbmodgui.h.
Referenced by applyBandwidths(), and SSBModGUI().
m_spectrumVis
SpectrumVis* SSBModGUI::m_spectrumVis private
Definition at line 71 of file ssbmodgui.h.
Referenced by SSBModGUI(), and ~SSBModGUI().
m_ssbMod
SSBMod* SSBModGUI::m_ssbMod private
Definition at line 72 of file ssbmodgui.h.
Referenced by applyBandwidths(), applySettings(), configureFileName(), handleMessage(), on_navTimeSlider_valueChanged(), SSBModGUI(), tick(), and ~SSBModGUI().
m_tickCount
std::size_t SSBModGUI::m_tickCount private
Definition at line 79 of file ssbmodgui.h.
Referenced by tick().
ui
Ui::SSBModGUI* SSBModGUI::ui private
Definition at line 63 of file ssbmodgui.h.
Referenced by applyBandwidths(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), handleMessage(), on_BW_valueChanged(), on_dsb_toggled(), on_feedbackVolume_valueChanged(), on_flipSidebands_clicked(), on_lowCut_valueChanged(), on_mic_toggled(), on_morseKeyer_toggled(), on_play_toggled(), on_showFileDialog_clicked(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), SSBModGUI(), tick(), updateWithStreamData(), updateWithStreamTime(), and ~SSBModGUI().
The documentation for this class was generated from the following files:
plugins/channeltx/modssb/ssbmodgui.h
plugins/channeltx/modssb/ssbmodgui.cpp