SDRAngel: WFMMod Class Reference
WFMMod Class Reference
#include <wfmmod.h>
Classes
class MsgConfigureChannelizer
class MsgConfigureFileSourceName
class MsgConfigureFileSourceSeek
class MsgConfigureFileSourceStreamTiming
class MsgConfigureWFMMod
class MsgReportFileSourceStreamData
class MsgReportFileSourceStreamTiming
Signals
void levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples)
Public Member Functions
WFMMod (DeviceAPI *deviceAPI)
~WFMMod ()
virtual void destroy ()
virtual void pull (Sample &sample)
virtual void pullAudio (int nbSamples)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
double getMagSq () const
CWKeyer * getCWKeyer ()
Public Member Functions inherited from BasebandSampleSource
BasebandSampleSource ()
virtual ~BasebandSampleSource ()
void feed (SampleSourceFifo *sampleFifo, int nbSamples)
SampleSourceFifo & getSampleSourceFifo ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
void setDeviceSampleSourceFifo (SampleSourceFifo *deviceSampleFifo)
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channeltx.modwfm"
static const QString m_channelId = "WFMMod"
Private Types
enum RateState { RSInitialFill, RSRunning }
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applyAudioSampleRate (int sampleRate)
void applyChannelSettings (int basebandSampleRate, int outputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const WFMModSettings &settings, bool force=false)
void pullAF (Complex &sample)
void calculateLevel (const Real &sample)
void openFileStream ()
void seekFileStream (int seekPercentage)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const WFMModSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const WFMModSettings &settings, bool force)
void webapiReverseSendCWSettings (const CWKeyerSettings &settings)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSource * m_threadedChannelizer
UpChannelizer * m_channelizer
int m_basebandSampleRate
int m_outputSampleRate
int m_inputFrequencyOffset
WFMModSettings m_settings
NCO m_carrierNco
NCOF m_toneNcoRF
float m_modPhasor
baseband modulator phasor
Complex m_modSample
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
bool m_interpolatorConsumed
fftfilt * m_rfFilter
fftfilt::cmplx * m_rfFilterBuffer
int m_rfFilterBufferIndex
double m_magsq
MovingAverageUtil< double, double, 16 > m_movingAverage
quint32 m_audioSampleRate
AudioVector m_audioBuffer
uint m_audioBufferFill
AudioFifo m_audioFifo
SampleVector m_sampleBuffer
QMutex m_settingsMutex
std::ifstream m_ifstream
QString m_fileName
quint64 m_fileSize
raw file size (bytes)
quint32 m_recordLength
record length in seconds computed from file size
int m_sampleRate
quint32 m_levelCalcCount
Real m_peakLevel
Real m_levelSum
CWKeyer m_cwKeyer
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Static Private Attributes
static const int m_rfFilterFFTLength = 1024
static const int m_levelNbSamples = 480
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSource
void handleInputMessages ()
void handleWriteToFifo (int nbSamples)
void handleWriteToDeviceFifo (int nbSamples)
Protected Member Functions inherited from BasebandSampleSource
void handleWriteToFifo (SampleSourceFifo *sampleFifo, int nbSamples)
Protected Attributes inherited from BasebandSampleSource
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
SampleSourceFifo m_sampleFifo
Internal FIFO for multi-channel processing.
SampleSourceFifo * m_deviceSampleFifo
Reference to the device FIFO for single channel processing.
Detailed Description
Definition at line 48 of file wfmmod.h.
Member Enumeration Documentation
RateState
enum WFMMod::RateState private
Enumerator
RSInitialFill
RSRunning
Definition at line 264 of file wfmmod.h.
                    {
         RSInitialFill,
         RSRunning
     };
Constructor & Destructor Documentation
WFMMod()
WFMMod::WFMMod (DeviceAPI * deviceAPI)
Definition at line 55 of file wfmmod.cpp.
References AudioDeviceManager::addAudioSource(), DeviceAPI::addChannelSource(), DeviceAPI::addChannelSourceAPI(), applyChannelSettings(), applySettings(), DSPEngine::getAudioDeviceManager(), BasebandSampleSource::getInputMessageQueue(), AudioDeviceManager::getInputSampleRate(), DSPEngine::instance(), m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_basebandSampleRate, m_channelId, m_channelizer, m_cwKeyer, m_deviceAPI, m_inputFrequencyOffset, m_magsq, m_networkManager, m_outputSampleRate, m_rfFilter, m_rfFilterBuffer, m_rfFilterBufferIndex, m_rfFilterFFTLength, m_settings, m_threadedChannelizer, m_toneNcoRF, networkManagerFinished(), CWKeyer::reset(), NCOF::setFreq(), and CWKeyer::setSampleRate().
Referenced by WFMMod::MsgReportFileSourceStreamData::MsgReportFileSourceStreamData().
                                    :
     ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSource),
     m_deviceAPI(deviceAPI),
     m_basebandSampleRate(384000),
     m_outputSampleRate(384000),
     m_inputFrequencyOffset(0),
     m_modPhasor(0.0f),
     m_audioFifo(4800),
     m_settingsMutex(QMutex::Recursive),
     m_fileSize(0),
     m_recordLength(0),
     m_sampleRate(48000),
     m_levelCalcCount(0),
     m_peakLevel(0.0f),
     m_levelSum(0.0f)
 {
     setObjectName(m_channelId);
     m_rfFilter = new fftfilt(-62500.0 / 384000.0, 62500.0 / 384000.0, m_rfFilterFFTLength);
     m_rfFilterBuffer = new Complex[m_rfFilterFFTLength];
     std::fill(m_rfFilterBuffer, m_rfFilterBuffer+m_rfFilterFFTLength, Complex{0,0});
     //memset(m_rfFilterBuffer, 0, sizeof(Complex)*(m_rfFilterFFTLength));
     m_rfFilterBufferIndex = 0;
     m_audioBuffer.resize(1<<14);
     m_audioBufferFill = 0;
     m_magsq = 0.0;
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSource(&m_audioFifo, getInputMessageQueue());
     m_audioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getInputSampleRate();
     m_toneNcoRF.setFreq(1000.0, m_outputSampleRate);
     m_cwKeyer.setSampleRate(m_outputSampleRate);
     m_cwKeyer.reset();
     applyChannelSettings(m_basebandSampleRate, m_outputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new UpChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSource(m_channelizer, this);
     m_deviceAPI->addChannelSource(m_threadedChannelizer);
     m_deviceAPI->addChannelSourceAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~WFMMod()
WFMMod::~WFMMod ()
Definition at line 103 of file wfmmod.cpp.
References DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo, m_channelizer, m_deviceAPI, m_networkManager, m_rfFilter, m_rfFilterBuffer, m_threadedChannelizer, networkManagerFinished(), AudioDeviceManager::removeAudioSource(), DeviceAPI::removeChannelSource(), and DeviceAPI::removeChannelSourceAPI().
Referenced by WFMMod::MsgReportFileSourceStreamData::MsgReportFileSourceStreamData().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSource(&m_audioFifo);
     m_deviceAPI->removeChannelSourceAPI(this);
     m_deviceAPI->removeChannelSource(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete m_rfFilter;
     delete[] m_rfFilterBuffer;
 }
Member Function Documentation
applyAudioSampleRate()
void WFMMod::applyAudioSampleRate (int sampleRate) private
Definition at line 435 of file wfmmod.cpp.
References Interpolator::create(), m_audioSampleRate, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, m_outputSampleRate, WFMModSettings::m_rfBandwidth, m_settings, and m_settingsMutex.
Referenced by applySettings(), and handleMessage().
 {
     qDebug("WFMMod::applyAudioSampleRate: %d", sampleRate);
     m_settingsMutex.lock();
     m_interpolatorDistanceRemain = 0;
     m_interpolatorConsumed = false;
     m_interpolatorDistance = (Real) sampleRate / (Real) m_outputSampleRate;
     m_interpolator.create(48, sampleRate, m_settings.m_rfBandwidth / 2.2, 3.0);
     m_settingsMutex.unlock();
     m_audioSampleRate = sampleRate;
 }
applyChannelSettings()
void WFMMod::applyChannelSettings (int basebandSampleRate, int outputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 449 of file wfmmod.cpp.
References Interpolator::create(), fftfilt::create_filter(), m_audioSampleRate, m_basebandSampleRate, m_carrierNco, m_cwKeyer, m_inputFrequencyOffset, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, m_outputSampleRate, WFMModSettings::m_rfBandwidth, m_rfFilter, m_settings, m_settingsMutex, WFMModSettings::m_toneFrequency, m_toneNcoRF, CWKeyer::reset(), NCO::setFreq(), NCOF::setFreq(), and CWKeyer::setSampleRate().
Referenced by handleMessage(), start(), and WFMMod().
 {
     qDebug() << "WFMMod::applyChannelSettings:"
             << " basebandSampleRate: " << basebandSampleRate
             << " outputSampleRate: " << outputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if ((inputFrequencyOffset != m_inputFrequencyOffset) ||
         (outputSampleRate != m_outputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_carrierNco.setFreq(inputFrequencyOffset, outputSampleRate);
         m_settingsMutex.unlock();
     }
     if ((outputSampleRate != m_outputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_interpolatorDistanceRemain = 0;
         m_interpolatorConsumed = false;
         m_interpolatorDistance = (Real) m_audioSampleRate / (Real) outputSampleRate;
         m_interpolator.create(48, m_audioSampleRate, m_settings.m_rfBandwidth / 2.2, 3.0);
         Real lowCut = -(m_settings.m_rfBandwidth / 2.0) / outputSampleRate;
         Real hiCut  = (m_settings.m_rfBandwidth / 2.0) / outputSampleRate;
         m_rfFilter->create_filter(lowCut, hiCut);
         m_toneNcoRF.setFreq(m_settings.m_toneFrequency, outputSampleRate);
         m_cwKeyer.setSampleRate(outputSampleRate);
         m_cwKeyer.reset();
         m_settingsMutex.unlock();
     }
     m_basebandSampleRate = basebandSampleRate;
     m_outputSampleRate = outputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applySettings()
void WFMMod::applySettings (const WFMModSettings & settings, bool force = false) private
Definition at line 485 of file wfmmod.cpp.
References AudioDeviceManager::addAudioSource(), applyAudioSampleRate(), Interpolator::create(), fftfilt::create_filter(), DSPEngine::getAudioDeviceManager(), AudioDeviceManager::getInputDeviceIndex(), BasebandSampleSource::getInputMessageQueue(), AudioDeviceManager::getInputSampleRate(), DSPEngine::instance(), WFMModSettings::m_afBandwidth, WFMModSettings::m_audioDeviceName, m_audioFifo, m_audioSampleRate, WFMModSettings::m_channelMute, WFMModSettings::m_fmDeviation, WFMModSettings::m_inputFrequencyOffset, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, WFMModSettings::m_modAFInput, m_outputSampleRate, WFMModSettings::m_playLoop, WFMModSettings::m_reverseAPIAddress, WFMModSettings::m_reverseAPIChannelIndex, WFMModSettings::m_reverseAPIDeviceIndex, WFMModSettings::m_reverseAPIPort, WFMModSettings::m_rfBandwidth, m_rfFilter, m_settings, m_settingsMutex, WFMModSettings::m_toneFrequency, m_toneNcoRF, WFMModSettings::m_useReverseAPI, WFMModSettings::m_volumeFactor, NCOF::setFreq(), and webapiReverseSendSettings().
Referenced by handleMessage(), and WFMMod().
 {
     qDebug() << "WFMMod::applySettings:"
             << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
             << " m_rfBandwidth: " << settings.m_rfBandwidth
             << " m_afBandwidth: " << settings.m_afBandwidth
             << " m_fmDeviation: " << settings.m_fmDeviation
             << " m_volumeFactor: " << settings.m_volumeFactor
             << " m_toneFrequency: " << settings.m_toneFrequency
             << " m_channelMute: " << settings.m_channelMute
             << " m_playLoop: " << settings.m_playLoop
             << " m_modAFInput: " << settings.m_modAFInput
             << " m_audioDeviceName: " << settings.m_audioDeviceName
             << " m_useReverseAPI: " << settings.m_useReverseAPI
             << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
             << " m_reverseAPIPort: " << settings.m_reverseAPIPort
             << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex
             << " m_reverseAPIChannelIndex: " << settings.m_reverseAPIChannelIndex
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if ((settings.m_inputFrequencyOffset != m_settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if ((settings.m_fmDeviation != m_settings.m_fmDeviation) || force) {
         reverseAPIKeys.append("fmDeviation");
     }
     if ((settings.m_volumeFactor != m_settings.m_volumeFactor) || force) {
         reverseAPIKeys.append("volumeFactor");
     }
     if ((settings.m_channelMute != m_settings.m_channelMute) || force) {
         reverseAPIKeys.append("channelMute");
     }
     if ((settings.m_playLoop != m_settings.m_playLoop) || force) {
         reverseAPIKeys.append("playLoop");
     }
     if ((settings.m_modAFInput != m_settings.m_modAFInput) || force) {
         reverseAPIKeys.append("modAFInput");
     }
     if ((settings.m_afBandwidth != m_settings.m_afBandwidth) || force)
     {
         reverseAPIKeys.append("afBandwidth");
         m_settingsMutex.lock();
         m_interpolatorDistanceRemain = 0;
         m_interpolatorConsumed = false;
         m_interpolatorDistance = (Real) m_audioSampleRate / (Real) m_outputSampleRate;
         m_interpolator.create(48, m_audioSampleRate, settings.m_rfBandwidth / 2.2, 3.0);
         m_settingsMutex.unlock();
     }
     if ((settings.m_rfBandwidth != m_settings.m_rfBandwidth) || force)
     {
         reverseAPIKeys.append("rfBandwidth");
         m_settingsMutex.lock();
         Real lowCut = -(settings.m_rfBandwidth / 2.0) / m_outputSampleRate;
         Real hiCut  = (settings.m_rfBandwidth / 2.0) / m_outputSampleRate;
         m_rfFilter->create_filter(lowCut, hiCut);
         m_settingsMutex.unlock();
     }
     if ((settings.m_toneFrequency != m_settings.m_toneFrequency) || force)
     {
         reverseAPIKeys.append("toneFrequency");
         m_settingsMutex.lock();
         m_toneNcoRF.setFreq(settings.m_toneFrequency, m_outputSampleRate);
         m_settingsMutex.unlock();
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force)
     {
         reverseAPIKeys.append("audioDeviceName");
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getInputDeviceIndex(settings.m_audioDeviceName);
         audioDeviceManager->addAudioSource(&m_audioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getInputSampleRate(audioDeviceIndex);
         if (m_audioSampleRate != audioSampleRate) {
             applyAudioSampleRate(audioSampleRate);
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
calculateLevel()
void WFMMod::calculateLevel (const Real & sample) private
Definition at line 268 of file wfmmod.cpp.
References levelChanged(), m_levelCalcCount, m_levelNbSamples, m_levelSum, m_peakLevel, leansdr::max(), and sqrt().
Referenced by pull().
 {
     if (m_levelCalcCount < m_levelNbSamples)
     {
         m_peakLevel = std::max(std::fabs(m_peakLevel), sample);
         m_levelSum += sample * sample;
         m_levelCalcCount++;
     }
     else
     {
         qreal rmsLevel = sqrt(m_levelSum / m_levelNbSamples);
         //qDebug("WFMMod::calculateLevel: %f %f", rmsLevel, m_peakLevel);
         emit levelChanged(rmsLevel, m_peakLevel, m_levelNbSamples);
         m_peakLevel = 0.0f;
         m_levelSum = 0.0f;
         m_levelCalcCount = 0;
     }
 }
deserialize()
bool WFMMod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 586 of file wfmmod.cpp.
References WFMMod::MsgConfigureWFMMod::create(), WFMModSettings::deserialize(), BasebandSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and WFMModSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureWFMMod *msg = MsgConfigureWFMMod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureWFMMod *msg = MsgConfigureWFMMod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void WFMMod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 207 of file wfmmod.h.
References handleMessage(), pull(), pullAudio(), start(), and stop().
 { delete this; }
getCenterFrequency()
virtual qint64 WFMMod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 217 of file wfmmod.h.
References deserialize(), WFMModSettings::m_inputFrequencyOffset, WFMMod::MsgConfigureWFMMod::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getCWKeyer()
CWKeyer* WFMMod::getCWKeyer () inline
Definition at line 248 of file wfmmod.h.
References m_cwKeyer.
Referenced by WFMModGUI::WFMModGUI().
 { return &m_cwKeyer; }
getIdentifier()
virtual void WFMMod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 215 of file wfmmod.h.
 { id = objectName(); }
getMagSq()
double WFMMod::getMagSq () const inline
Definition at line 246 of file wfmmod.h.
References m_magsq.
Referenced by WFMModGUI::tick(), and webapiFormatChannelReport().
 { return m_magsq; }
getNbSinkStreams()
virtual int WFMMod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 222 of file wfmmod.h.
 { return 1; }
getNbSourceStreams()
virtual int WFMMod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 223 of file wfmmod.h.
 { return 0; }
getStreamCenterFrequency()
virtual qint64 WFMMod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 225 of file wfmmod.h.
References WFMModSettings::m_inputFrequencyOffset, WFMMod::MsgConfigureWFMMod::m_settings, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void WFMMod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 216 of file wfmmod.h.
References WFMMod::MsgConfigureWFMMod::m_settings, and WFMModSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool WFMMod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSource.
Definition at line 300 of file wfmmod.cpp.
References applyAudioSampleRate(), applyChannelSettings(), applySettings(), UpChannelizer::configure(), WFMMod::MsgReportFileSourceStreamTiming::create(), UpChannelizer::MsgChannelizerNotification::getBasebandSampleRate(), WFMMod::MsgConfigureChannelizer::getCenterFrequency(), WFMMod::MsgConfigureFileSourceName::getFileName(), WFMMod::MsgConfigureWFMMod::getForce(), UpChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSource::getInputMessageQueue(), BasebandSampleSource::getMessageQueueToGUI(), WFMMod::MsgConfigureFileSourceSeek::getPercentage(), UpChannelizer::MsgChannelizerNotification::getSampleRate(), WFMMod::MsgConfigureChannelizer::getSampleRate(), DSPConfigureAudio::getSampleRate(), WFMMod::MsgConfigureWFMMod::getSettings(), CWKeyer::MsgConfigureCWKeyer::getSettings(), m_audioSampleRate, m_channelizer, m_fileName, m_fileSize, m_ifstream, m_settings, WFMModSettings::m_useReverseAPI, Message::match(), openFileStream(), MessageQueue::push(), seekFileStream(), and webapiReverseSendCWSettings().
Referenced by destroy().
 {
     if (UpChannelizer::MsgChannelizerNotification::match(cmd))
     {
         UpChannelizer::MsgChannelizerNotification& notif = (UpChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "WFMMod::handleMessage: MsgChannelizerNotification";
         applyChannelSettings(notif.getBasebandSampleRate(), notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "WFMMod::handleMessage: MsgConfigureChannelizer:"
                 << " getSampleRate: " << cfg.getSampleRate()
                 << " getCenterFrequency: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureWFMMod::match(cmd))
     {
         MsgConfigureWFMMod& cfg = (MsgConfigureWFMMod&) cmd;
         qDebug() << "NFWFMMod::handleMessage: MsgConfigureWFMMod";
         WFMModSettings settings = cfg.getSettings();
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgConfigureFileSourceName::match(cmd))
     {
         MsgConfigureFileSourceName& conf = (MsgConfigureFileSourceName&) cmd;
         m_fileName = conf.getFileName();
         openFileStream();
         return true;
     }
     else if (MsgConfigureFileSourceSeek::match(cmd))
     {
         MsgConfigureFileSourceSeek& conf = (MsgConfigureFileSourceSeek&) cmd;
         int seekPercentage = conf.getPercentage();
         seekFileStream(seekPercentage);
         return true;
     }
     else if (MsgConfigureFileSourceStreamTiming::match(cmd))
     {
         std::size_t samplesCount;
         if (m_ifstream.eof()) {
             samplesCount = m_fileSize / sizeof(Real);
         } else {
             samplesCount = m_ifstream.tellg() / sizeof(Real);
         }
         MsgReportFileSourceStreamTiming *report;
         report = MsgReportFileSourceStreamTiming::create(samplesCount);
         getMessageQueueToGUI()->push(report);
         return true;
     }
     else if (CWKeyer::MsgConfigureCWKeyer::match(cmd))
     {
         const CWKeyer::MsgConfigureCWKeyer& cfg = (CWKeyer::MsgConfigureCWKeyer&) cmd;
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendCWSettings(cfg.getSettings());
         }
         return true;
     }
     else if (DSPConfigureAudio::match(cmd))
     {
         DSPConfigureAudio& cfg = (DSPConfigureAudio&) cmd;
         uint32_t sampleRate = cfg.getSampleRate();
         qDebug() << "WFMMod::handleMessage: DSPConfigureAudio:"
                 << " sampleRate: " << sampleRate;
         if (sampleRate != m_audioSampleRate) {
             applyAudioSampleRate(sampleRate);
         }
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         return false;
     }
 }
levelChanged
void WFMMod::levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples) signal
Level changed
Parameters
rmsLevel RMS level in range 0.0 - 1.0
peakLevel Peak level in range 0.0 - 1.0
numSamples Number of audio samples analyzed
Referenced by calculateLevel().
networkManagerFinished
void WFMMod::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 885 of file wfmmod.cpp.
Referenced by WFMMod(), and ~WFMMod().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "WFMMod::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("WFMMod::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openFileStream()
void WFMMod::openFileStream () private
Definition at line 400 of file wfmmod.cpp.
References WFMMod::MsgReportFileSourceStreamData::create(), BasebandSampleSource::getMessageQueueToGUI(), m_fileName, m_fileSize, m_ifstream, m_recordLength, m_sampleRate, and MessageQueue::push().
Referenced by handleMessage().
 {
     if (m_ifstream.is_open()) {
         m_ifstream.close();
     }
     m_ifstream.open(m_fileName.toStdString().c_str(), std::ios::binary | std::ios::ate);
     m_fileSize = m_ifstream.tellg();
     m_ifstream.seekg(0,std::ios_base::beg);
     m_sampleRate = 48000; // fixed rate
     m_recordLength = m_fileSize / (sizeof(Real) * m_sampleRate);
     qDebug() << "WFMMod::openFileStream: " << m_fileName.toStdString().c_str()
             << " fileSize: " << m_fileSize << "bytes"
             << " length: " << m_recordLength << " seconds";
     MsgReportFileSourceStreamData *report;
     report = MsgReportFileSourceStreamData::create(m_sampleRate, m_recordLength);
     getMessageQueueToGUI()->push(report);
 }
pull()
void WFMMod::pull (Sample & sample) virtual
Implements BasebandSampleSource.
Definition at line 116 of file wfmmod.cpp.
References MovingAverageUtil< T, Total, N >::asDouble(), calculateLevel(), cos(), Interpolator::interpolate(), m_audioBufferFill, m_carrierNco, WFMModSettings::m_channelMute, WFMModSettings::m_fmDeviation, Sample::m_imag, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_magsq, WFMModSettings::m_modAFInput, m_modPhasor, m_modSample, m_movingAverage, m_outputSampleRate, M_PI, Sample::m_real, m_rfFilter, m_rfFilterBuffer, m_rfFilterBufferIndex, m_settings, m_settingsMutex, NCO::nextIQ(), pullAF(), fftfilt::runFilt(), SDR_TX_SCALED, SDR_TX_SCALEF, sin(), WFMModSettings::WFMModInputAudio, and WFMModSettings::WFMModInputFile.
Referenced by destroy().
 {
     if (m_settings.m_channelMute)
     {
         sample.m_real = 0.0f;
         sample.m_imag = 0.0f;
         return;
     }
     Complex ci, ri;
     fftfilt::cmplx *rf;
     int rf_out;
     m_settingsMutex.lock();
     if ((m_settings.m_modAFInput == WFMModSettings::WFMModInputFile)
        || (m_settings.m_modAFInput == WFMModSettings::WFMModInputAudio))
     {
         if (m_interpolator.interpolate(&m_interpolatorDistanceRemain, m_modSample, &ri))
         {
             pullAF(m_modSample);
             calculateLevel(m_modSample.real());
             m_audioBufferFill++;
         }
         m_interpolatorDistanceRemain += m_interpolatorDistance;
     }
     else
     {
         pullAF(ri);
     }
     m_modPhasor += (m_settings.m_fmDeviation / (float) m_outputSampleRate) * ri.real() * M_PI * 2.0f;
     ci.real(cos(m_modPhasor) * 0.891235351562f * SDR_TX_SCALEF); // -1 dB
     ci.imag(sin(m_modPhasor) * 0.891235351562f * SDR_TX_SCALEF);
     // RF filtering
     rf_out = m_rfFilter->runFilt(ci, &rf);
     if (rf_out > 0)
     {
         memcpy((void *) m_rfFilterBuffer, (const void *) rf, rf_out*sizeof(Complex));
         m_rfFilterBufferIndex = 0;
     }
     ci = m_rfFilterBuffer[m_rfFilterBufferIndex] * m_carrierNco.nextIQ(); // shift to carrier frequency
     m_rfFilterBufferIndex++;
     m_settingsMutex.unlock();
     double magsq = ci.real() * ci.real() + ci.imag() * ci.imag();
     magsq /= (SDR_TX_SCALED*SDR_TX_SCALED);
     m_movingAverage(magsq);
     m_magsq = m_movingAverage.asDouble();
     sample.m_real = (FixReal) ci.real();
     sample.m_imag = (FixReal) ci.imag();
 }
pullAF()
void WFMMod::pullAF (Complex & sample) private
Definition at line 189 of file wfmmod.cpp.
References CWKeyer::getCWSmoother(), CWSmoother::getFadeSample(), CWKeyer::getSample(), m_audioBuffer, m_audioBufferFill, m_cwKeyer, m_ifstream, WFMModSettings::m_modAFInput, WFMModSettings::m_playLoop, m_settings, m_toneNcoRF, WFMModSettings::m_volumeFactor, NCOF::next(), NCOF::setPhase(), WFMModSettings::WFMModInputAudio, WFMModSettings::WFMModInputCWTone, WFMModSettings::WFMModInputFile, WFMModSettings::WFMModInputNone, and WFMModSettings::WFMModInputTone.
Referenced by pull().
 {
     switch (m_settings.m_modAFInput)
     {
     case WFMModSettings::WFMModInputTone:
         sample.real(m_toneNcoRF.next() * m_settings.m_volumeFactor);
         sample.imag(0.0f);
         break;
     case WFMModSettings::WFMModInputFile:
         // sox f4exb_call.wav --encoding float --endian little f4exb_call.raw
         // ffplay -f f32le -ar 48k -ac 1 f4exb_call.raw
         if (m_ifstream.is_open())
         {
             if (m_ifstream.eof())
             {
                 if (m_settings.m_playLoop)
                 {
                     m_ifstream.clear();
                     m_ifstream.seekg(0, std::ios::beg);
                 }
             }
             if (m_ifstream.eof())
             {
                 sample.real(0.0f);
                 sample.imag(0.0f);
             }
             else
             {
                 Real s;
                 m_ifstream.read(reinterpret_cast<char*>(&s), sizeof(Real));
                 sample.real(s * m_settings.m_volumeFactor);
                 sample.imag(0.0f);
             }
         }
         else
         {
             sample.real(0.0f);
             sample.imag(0.0f);
         }
         break;
     case WFMModSettings::WFMModInputAudio:
         {
             sample.real(((m_audioBuffer[m_audioBufferFill].l + m_audioBuffer[m_audioBufferFill].r) / 65536.0f) * m_settings.m_volumeFactor);
             sample.imag(0.0f);
         }
         break;
     case WFMModSettings::WFMModInputCWTone:
         Real fadeFactor;
         if (m_cwKeyer.getSample())
         {
             m_cwKeyer.getCWSmoother().getFadeSample(true, fadeFactor);
             sample.real(m_toneNcoRF.next() * m_settings.m_volumeFactor * fadeFactor);
             sample.imag(0.0f);
         }
         else
         {
             if (m_cwKeyer.getCWSmoother().getFadeSample(false, fadeFactor))
             {
                 sample.real(m_toneNcoRF.next() * m_settings.m_volumeFactor * fadeFactor);
                 sample.imag(0.0f);
             }
             else
             {
                 sample.real(0.0f);
                 sample.imag(0.0f);
                 m_toneNcoRF.setPhase(0);
             }
         }
         break;
     case WFMModSettings::WFMModInputNone:
     default:
         sample.real(0.0f);
         sample.imag(0.0f);
         break;
     }
 }
pullAudio()
void WFMMod::pullAudio (int nbSamples) virtual
Reimplemented from BasebandSampleSource.
Definition at line 176 of file wfmmod.cpp.
References m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_basebandSampleRate, and AudioFifo::read().
Referenced by destroy().
 {
     unsigned int nbSamplesAudio = nbSamples * ((Real) m_audioSampleRate / (Real) m_basebandSampleRate);
     if (nbSamplesAudio > m_audioBuffer.size())
     {
         m_audioBuffer.resize(nbSamplesAudio);
     }
     m_audioFifo.read(reinterpret_cast<quint8*>(&m_audioBuffer[0]), nbSamplesAudio);
     m_audioBufferFill = 0;
 }
seekFileStream()
void WFMMod::seekFileStream (int seekPercentage) private
Definition at line 422 of file wfmmod.cpp.
References m_ifstream, m_recordLength, m_sampleRate, and m_settingsMutex.
Referenced by handleMessage().
 {
     QMutexLocker mutexLocker(&m_settingsMutex);
     if (m_ifstream.is_open())
     {
         int seekPoint = ((m_recordLength * seekPercentage) / 100) * m_sampleRate;
         seekPoint *= sizeof(Real);
         m_ifstream.clear();
         m_ifstream.seekg(seekPoint, std::ios::beg);
     }
 }
serialize()
QByteArray WFMMod::serialize () const virtual
Implements ChannelAPI.
Definition at line 581 of file wfmmod.cpp.
References m_settings, and WFMModSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
start()
void WFMMod::start () virtual
Implements BasebandSampleSource.
Definition at line 287 of file wfmmod.cpp.
References applyChannelSettings(), AudioFifo::clear(), m_audioFifo, m_basebandSampleRate, m_inputFrequencyOffset, and m_outputSampleRate.
Referenced by destroy().
 {
     qDebug() << "WFMMod::start: m_outputSampleRate: " << m_outputSampleRate
             << " m_inputFrequencyOffset: " << m_inputFrequencyOffset;
     m_audioFifo.clear();
     applyChannelSettings(m_basebandSampleRate, m_outputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void WFMMod::stop () virtual
Implements BasebandSampleSource.
Definition at line 296 of file wfmmod.cpp.
Referenced by destroy().
 {
 }
webapiFormatChannelReport()
void WFMMod::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 771 of file wfmmod.cpp.
References CalcDb::dbPower(), getMagSq(), SWGSDRangel::SWGChannelReport::getWfmModReport(), m_audioSampleRate, m_outputSampleRate, SWGSDRangel::SWGWFMModReport::setAudioSampleRate(), SWGSDRangel::SWGWFMModReport::setChannelPowerDb(), and SWGSDRangel::SWGWFMModReport::setChannelSampleRate().
Referenced by webapiReportGet().
 {
     response.getWfmModReport()->setChannelPowerDb(CalcDb::dbPower(getMagSq()));
     response.getWfmModReport()->setAudioSampleRate(m_audioSampleRate);
     response.getWfmModReport()->setChannelSampleRate(m_outputSampleRate);
 }
webapiFormatChannelSettings()
void WFMMod::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const WFMModSettings & settings) private
Definition at line 724 of file wfmmod.cpp.
References SWGSDRangel::SWGWFMModSettings::getAudioDeviceName(), SWGSDRangel::SWGWFMModSettings::getCwKeyer(), SWGSDRangel::SWGWFMModSettings::getReverseApiAddress(), CWKeyer::getSettings(), SWGSDRangel::SWGWFMModSettings::getTitle(), SWGSDRangel::SWGChannelSettings::getWfmModSettings(), WFMModSettings::m_afBandwidth, WFMModSettings::m_audioDeviceName, WFMModSettings::m_channelMute, m_cwKeyer, WFMModSettings::m_fmDeviation, WFMModSettings::m_inputFrequencyOffset, WFMModSettings::m_modAFInput, WFMModSettings::m_playLoop, WFMModSettings::m_reverseAPIAddress, WFMModSettings::m_reverseAPIChannelIndex, WFMModSettings::m_reverseAPIDeviceIndex, WFMModSettings::m_reverseAPIPort, WFMModSettings::m_rfBandwidth, WFMModSettings::m_rgbColor, WFMModSettings::m_title, WFMModSettings::m_toneFrequency, WFMModSettings::m_useReverseAPI, WFMModSettings::m_volumeFactor, SWGSDRangel::SWGWFMModSettings::setAfBandwidth(), SWGSDRangel::SWGWFMModSettings::setAudioDeviceName(), SWGSDRangel::SWGWFMModSettings::setChannelMute(), SWGSDRangel::SWGWFMModSettings::setCwKeyer(), SWGSDRangel::SWGWFMModSettings::setFmDeviation(), SWGSDRangel::SWGWFMModSettings::setInputFrequencyOffset(), SWGSDRangel::SWGWFMModSettings::setModAfInput(), SWGSDRangel::SWGWFMModSettings::setPlayLoop(), SWGSDRangel::SWGWFMModSettings::setReverseApiAddress(), SWGSDRangel::SWGWFMModSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGWFMModSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGWFMModSettings::setReverseApiPort(), SWGSDRangel::SWGWFMModSettings::setRfBandwidth(), SWGSDRangel::SWGWFMModSettings::setRgbColor(), SWGSDRangel::SWGWFMModSettings::setTitle(), SWGSDRangel::SWGWFMModSettings::setToneFrequency(), SWGSDRangel::SWGWFMModSettings::setUseReverseApi(), SWGSDRangel::SWGWFMModSettings::setVolumeFactor(), and CWKeyer::webapiFormatChannelSettings().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getWfmModSettings()->setChannelMute(settings.m_channelMute ? 1 : 0);
     response.getWfmModSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getWfmModSettings()->setModAfInput((int) settings.m_modAFInput);
     response.getWfmModSettings()->setPlayLoop(settings.m_playLoop ? 1 : 0);
     response.getWfmModSettings()->setRfBandwidth(settings.m_rfBandwidth);
     response.getWfmModSettings()->setAfBandwidth(settings.m_afBandwidth);
     response.getWfmModSettings()->setFmDeviation(settings.m_fmDeviation);
     response.getWfmModSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getWfmModSettings()->getTitle()) {
         *response.getWfmModSettings()->getTitle() = settings.m_title;
     } else {
         response.getWfmModSettings()->setTitle(new QString(settings.m_title));
     }
     response.getWfmModSettings()->setToneFrequency(settings.m_toneFrequency);
     response.getWfmModSettings()->setVolumeFactor(settings.m_volumeFactor);
     if (!response.getWfmModSettings()->getCwKeyer()) {
         response.getWfmModSettings()->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings);
     }
     SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = response.getWfmModSettings()->getCwKeyer();
     const CWKeyerSettings& cwKeyerSettings = m_cwKeyer.getSettings();
     m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     if (response.getWfmModSettings()->getAudioDeviceName()) {
         *response.getWfmModSettings()->getAudioDeviceName() = settings.m_audioDeviceName;
     } else {
         response.getWfmModSettings()->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     response.getWfmModSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getWfmModSettings()->getReverseApiAddress()) {
         *response.getWfmModSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getWfmModSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getWfmModSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getWfmModSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getWfmModSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int WFMMod::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 713 of file wfmmod.cpp.
References SWGSDRangel::SWGChannelReport::getWfmModReport(), SWGSDRangel::SWGWFMModReport::init(), SWGSDRangel::SWGChannelReport::setWfmModReport(), and webapiFormatChannelReport().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setWfmModReport(new SWGSDRangel::SWGWFMModReport());
     response.getWfmModReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendCWSettings()
void WFMMod::webapiReverseSendCWSettings (const CWKeyerSettings & settings) private
Definition at line 854 of file wfmmod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), SWGSDRangel::SWGWFMModSettings::getCwKeyer(), SWGSDRangel::SWGChannelSettings::getWfmModSettings(), m_cwKeyer, m_networkManager, m_networkRequest, WFMModSettings::m_reverseAPIAddress, WFMModSettings::m_reverseAPIChannelIndex, WFMModSettings::m_reverseAPIDeviceIndex, WFMModSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGWFMModSettings::setCwKeyer(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGChannelSettings::setWfmModSettings(), and CWKeyer::webapiFormatChannelSettings().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setChannelType(new QString("WFMMod"));
     swgChannelSettings->setWfmModSettings(new SWGSDRangel::SWGWFMModSettings());
     SWGSDRangel::SWGWFMModSettings *swgWFMModSettings = swgChannelSettings->getWfmModSettings();
     swgWFMModSettings->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings());
     SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = swgWFMModSettings->getCwKeyer();
     m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex)
             .arg(m_settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiReverseSendSettings()
void WFMMod::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const WFMModSettings & settings, bool force) private
Definition at line 778 of file wfmmod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), SWGSDRangel::SWGWFMModSettings::getCwKeyer(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), CWKeyer::getSettings(), SWGSDRangel::SWGChannelSettings::getWfmModSettings(), WFMModSettings::m_afBandwidth, WFMModSettings::m_audioDeviceName, WFMModSettings::m_channelMute, m_cwKeyer, WFMModSettings::m_fmDeviation, WFMModSettings::m_inputFrequencyOffset, WFMModSettings::m_modAFInput, m_networkManager, m_networkRequest, WFMModSettings::m_playLoop, WFMModSettings::m_reverseAPIAddress, WFMModSettings::m_reverseAPIChannelIndex, WFMModSettings::m_reverseAPIDeviceIndex, WFMModSettings::m_reverseAPIPort, WFMModSettings::m_rfBandwidth, WFMModSettings::m_rgbColor, WFMModSettings::m_title, WFMModSettings::m_toneFrequency, WFMModSettings::m_volumeFactor, SWGSDRangel::SWGWFMModSettings::setAfBandwidth(), SWGSDRangel::SWGWFMModSettings::setAudioDeviceName(), SWGSDRangel::SWGWFMModSettings::setChannelMute(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGWFMModSettings::setCwKeyer(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGWFMModSettings::setFmDeviation(), SWGSDRangel::SWGWFMModSettings::setInputFrequencyOffset(), SWGSDRangel::SWGWFMModSettings::setModAfInput(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGWFMModSettings::setPlayLoop(), SWGSDRangel::SWGWFMModSettings::setRfBandwidth(), SWGSDRangel::SWGWFMModSettings::setRgbColor(), SWGSDRangel::SWGWFMModSettings::setTitle(), SWGSDRangel::SWGWFMModSettings::setToneFrequency(), SWGSDRangel::SWGWFMModSettings::setVolumeFactor(), SWGSDRangel::SWGChannelSettings::setWfmModSettings(), and CWKeyer::webapiFormatChannelSettings().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("WFMMod"));
     swgChannelSettings->setWfmModSettings(new SWGSDRangel::SWGWFMModSettings());
     SWGSDRangel::SWGWFMModSettings *swgWFMModSettings = swgChannelSettings->getWfmModSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("channelMute") || force) {
         swgWFMModSettings->setChannelMute(settings.m_channelMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgWFMModSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("modAFInput") || force) {
         swgWFMModSettings->setModAfInput((int) settings.m_modAFInput);
     }
     if (channelSettingsKeys.contains("playLoop") || force) {
         swgWFMModSettings->setPlayLoop(settings.m_playLoop ? 1 : 0);
     }
     if (channelSettingsKeys.contains("rfBandwidth") || force) {
         swgWFMModSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (channelSettingsKeys.contains("afBandwidth") || force) {
         swgWFMModSettings->setAfBandwidth(settings.m_afBandwidth);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgWFMModSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgWFMModSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("toneFrequency") || force) {
         swgWFMModSettings->setToneFrequency(settings.m_toneFrequency);
     }
     if (channelSettingsKeys.contains("volumeFactor") || force) {
         swgWFMModSettings->setVolumeFactor(settings.m_volumeFactor);
     }
     if (channelSettingsKeys.contains("fmDeviation")) {
         swgWFMModSettings->setFmDeviation(settings.m_fmDeviation);
     }
     if (channelSettingsKeys.contains("audioDeviceName") || force) {
         swgWFMModSettings->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     if (force)
     {
         const CWKeyerSettings& cwKeyerSettings = m_cwKeyer.getSettings();
         swgWFMModSettings->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings());
         SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = swgWFMModSettings->getCwKeyer();
         m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int WFMMod::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 603 of file wfmmod.cpp.
References SWGSDRangel::SWGChannelSettings::getWfmModSettings(), SWGSDRangel::SWGWFMModSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setWfmModSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setWfmModSettings(new SWGSDRangel::SWGWFMModSettings());
     response.getWfmModSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int WFMMod::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 614 of file wfmmod.cpp.
References WFMMod::MsgConfigureWFMMod::create(), CWKeyer::MsgConfigureCWKeyer::create(), WFMMod::MsgConfigureChannelizer::create(), SWGSDRangel::SWGWFMModSettings::getAfBandwidth(), SWGSDRangel::SWGWFMModSettings::getChannelMute(), SWGSDRangel::SWGWFMModSettings::getCwKeyer(), SWGSDRangel::SWGWFMModSettings::getFmDeviation(), SWGSDRangel::SWGWFMModSettings::getInputFrequencyOffset(), CWKeyer::getInputMessageQueue(), SWGSDRangel::SWGWFMModSettings::getModAfInput(), SWGSDRangel::SWGWFMModSettings::getPlayLoop(), SWGSDRangel::SWGWFMModSettings::getReverseApiAddress(), SWGSDRangel::SWGWFMModSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGWFMModSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGWFMModSettings::getReverseApiPort(), SWGSDRangel::SWGWFMModSettings::getRfBandwidth(), SWGSDRangel::SWGWFMModSettings::getRgbColor(), CWKeyer::getSettings(), SWGSDRangel::SWGWFMModSettings::getTitle(), SWGSDRangel::SWGWFMModSettings::getToneFrequency(), SWGSDRangel::SWGWFMModSettings::getUseReverseApi(), SWGSDRangel::SWGWFMModSettings::getVolumeFactor(), SWGSDRangel::SWGChannelSettings::getWfmModSettings(), WFMModSettings::m_afBandwidth, WFMModSettings::m_channelMute, m_cwKeyer, WFMModSettings::m_fmDeviation, BasebandSampleSource::m_guiMessageQueue, WFMModSettings::m_inputFrequencyOffset, BasebandSampleSource::m_inputMessageQueue, WFMModSettings::m_modAFInput, WFMModSettings::m_playLoop, WFMModSettings::m_reverseAPIAddress, WFMModSettings::m_reverseAPIChannelIndex, WFMModSettings::m_reverseAPIDeviceIndex, WFMModSettings::m_reverseAPIPort, WFMModSettings::m_rfBandwidth, WFMModSettings::m_rgbColor, m_settings, WFMModSettings::m_title, WFMModSettings::m_toneFrequency, WFMModSettings::m_useReverseAPI, WFMModSettings::m_volumeFactor, MessageQueue::push(), webapiFormatChannelSettings(), and CWKeyer::webapiSettingsPutPatch().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     WFMModSettings settings = m_settings;
     bool channelizerChange = false;
     if (channelSettingsKeys.contains("channelMute")) {
         settings.m_channelMute = response.getWfmModSettings()->getChannelMute() != 0;
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getWfmModSettings()->getInputFrequencyOffset();
         channelizerChange = true;
     }
     if (channelSettingsKeys.contains("modAFInput")) {
         settings.m_modAFInput = (WFMModSettings::WFMModInputAF) response.getWfmModSettings()->getModAfInput();
     }
     if (channelSettingsKeys.contains("playLoop")) {
         settings.m_playLoop = response.getWfmModSettings()->getPlayLoop() != 0;
     }
     if (channelSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getWfmModSettings()->getRfBandwidth();
         channelizerChange = true;
     }
     if (channelSettingsKeys.contains("afBandwidth")) {
         settings.m_afBandwidth = response.getWfmModSettings()->getAfBandwidth();
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getWfmModSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getWfmModSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("toneFrequency")) {
         settings.m_toneFrequency = response.getWfmModSettings()->getToneFrequency();
     }
     if (channelSettingsKeys.contains("volumeFactor")) {
         settings.m_volumeFactor = response.getWfmModSettings()->getVolumeFactor();
     }
     if (channelSettingsKeys.contains("fmDeviation")) {
         settings.m_fmDeviation = response.getWfmModSettings()->getFmDeviation();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getWfmModSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getWfmModSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getWfmModSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getWfmModSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getWfmModSettings()->getReverseApiChannelIndex();
     }
     if (channelSettingsKeys.contains("cwKeyer"))
     {
         SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = response.getWfmModSettings()->getCwKeyer();
         CWKeyerSettings cwKeyerSettings = m_cwKeyer.getSettings();
         m_cwKeyer.webapiSettingsPutPatch(channelSettingsKeys, cwKeyerSettings, apiCwKeyerSettings);
         CWKeyer::MsgConfigureCWKeyer *msgCwKeyer = CWKeyer::MsgConfigureCWKeyer::create(cwKeyerSettings, force);
         m_cwKeyer.getInputMessageQueue()->push(msgCwKeyer);
         if (m_guiMessageQueue) // forward to GUI if any
         {
             CWKeyer::MsgConfigureCWKeyer *msgCwKeyerToGUI = CWKeyer::MsgConfigureCWKeyer::create(cwKeyerSettings, force);
             m_guiMessageQueue->push(msgCwKeyerToGUI);
         }
     }
     if (channelizerChange)
     {
         WFMMod::MsgConfigureChannelizer *msgChan = WFMMod::MsgConfigureChannelizer::create(
                 settings.m_rfBandwidth, settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(msgChan);
     }
     MsgConfigureWFMMod *msg = MsgConfigureWFMMod::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureWFMMod *msgToGUI = MsgConfigureWFMMod::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_audioBuffer
AudioVector WFMMod::m_audioBuffer private
Definition at line 296 of file wfmmod.h.
Referenced by pullAF(), pullAudio(), and WFMMod().
m_audioBufferFill
uint WFMMod::m_audioBufferFill private
Definition at line 297 of file wfmmod.h.
Referenced by pull(), pullAF(), pullAudio(), and WFMMod().
m_audioFifo
AudioFifo WFMMod::m_audioFifo private
Definition at line 298 of file wfmmod.h.
Referenced by applySettings(), pullAudio(), start(), WFMMod(), and ~WFMMod().
m_audioSampleRate
quint32 WFMMod::m_audioSampleRate private
Definition at line 295 of file wfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), handleMessage(), pullAudio(), webapiFormatChannelReport(), and WFMMod().
m_basebandSampleRate
int WFMMod::m_basebandSampleRate private
Definition at line 273 of file wfmmod.h.
Referenced by applyChannelSettings(), pullAudio(), start(), and WFMMod().
m_carrierNco
NCO WFMMod::m_carrierNco private
Definition at line 278 of file wfmmod.h.
Referenced by applyChannelSettings(), and pull().
m_channelId
const QString WFMMod::m_channelId = "WFMMod" static
Definition at line 251 of file wfmmod.h.
Referenced by WFMModPlugin::initPlugin(), and WFMMod().
m_channelIdURI
const QString WFMMod::m_channelIdURI = "sdrangel.channeltx.modwfm" static
Definition at line 250 of file wfmmod.h.
Referenced by WFMModPlugin::initPlugin(), and WFMModGUI::WFMModGUI().
m_channelizer
UpChannelizer* WFMMod::m_channelizer private
Definition at line 271 of file wfmmod.h.
Referenced by handleMessage(), WFMMod(), and ~WFMMod().
m_cwKeyer
CWKeyer WFMMod::m_cwKeyer private
Definition at line 312 of file wfmmod.h.
Referenced by applyChannelSettings(), getCWKeyer(), pullAF(), webapiFormatChannelSettings(), webapiReverseSendCWSettings(), webapiReverseSendSettings(), webapiSettingsPutPatch(), and WFMMod().
m_deviceAPI
DeviceAPI* WFMMod::m_deviceAPI private
Definition at line 269 of file wfmmod.h.
Referenced by WFMMod(), and ~WFMMod().
m_fileName
QString WFMMod::m_fileName private
Definition at line 304 of file wfmmod.h.
Referenced by WFMMod::MsgConfigureFileSourceName::getFileName(), handleMessage(), and openFileStream().
m_fileSize
quint64 WFMMod::m_fileSize private
raw file size (bytes)
Definition at line 305 of file wfmmod.h.
Referenced by handleMessage(), and openFileStream().
m_ifstream
std::ifstream WFMMod::m_ifstream private
Definition at line 303 of file wfmmod.h.
Referenced by handleMessage(), openFileStream(), pullAF(), and seekFileStream().
m_inputFrequencyOffset
int WFMMod::m_inputFrequencyOffset private
Definition at line 275 of file wfmmod.h.
Referenced by applyChannelSettings(), start(), and WFMMod().
m_interpolator
Interpolator WFMMod::m_interpolator private
Definition at line 282 of file wfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and pull().
m_interpolatorConsumed
bool WFMMod::m_interpolatorConsumed private
Definition at line 285 of file wfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), and applySettings().
m_interpolatorDistance
Real WFMMod::m_interpolatorDistance private
Definition at line 283 of file wfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and pull().
m_interpolatorDistanceRemain
Real WFMMod::m_interpolatorDistanceRemain private
Definition at line 284 of file wfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and pull().
m_levelCalcCount
quint32 WFMMod::m_levelCalcCount private
Definition at line 309 of file wfmmod.h.
Referenced by calculateLevel().
m_levelNbSamples
const int WFMMod::m_levelNbSamples = 480 static private
Definition at line 317 of file wfmmod.h.
Referenced by calculateLevel().
m_levelSum
Real WFMMod::m_levelSum private
Definition at line 311 of file wfmmod.h.
Referenced by calculateLevel().
m_magsq
double WFMMod::m_magsq private
Definition at line 292 of file wfmmod.h.
Referenced by getMagSq(), pull(), and WFMMod().
m_modPhasor
float WFMMod::m_modPhasor private
baseband modulator phasor
Definition at line 280 of file wfmmod.h.
Referenced by pull().
m_modSample
Complex WFMMod::m_modSample private
Definition at line 281 of file wfmmod.h.
Referenced by pull().
m_movingAverage
MovingAverageUtil<double, double, 16> WFMMod::m_movingAverage private
Definition at line 293 of file wfmmod.h.
Referenced by pull().
m_networkManager
QNetworkAccessManager* WFMMod::m_networkManager private
Definition at line 314 of file wfmmod.h.
Referenced by webapiReverseSendCWSettings(), webapiReverseSendSettings(), WFMMod(), and ~WFMMod().
m_networkRequest
QNetworkRequest WFMMod::m_networkRequest private
Definition at line 315 of file wfmmod.h.
Referenced by webapiReverseSendCWSettings(), and webapiReverseSendSettings().
m_outputSampleRate
int WFMMod::m_outputSampleRate private
Definition at line 274 of file wfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), pull(), start(), webapiFormatChannelReport(), and WFMMod().
m_peakLevel
Real WFMMod::m_peakLevel private
Definition at line 310 of file wfmmod.h.
Referenced by calculateLevel().
m_recordLength
quint32 WFMMod::m_recordLength private
record length in seconds computed from file size
Definition at line 306 of file wfmmod.h.
Referenced by WFMMod::MsgReportFileSourceStreamData::getRecordLength(), openFileStream(), and seekFileStream().
m_rfFilter
fftfilt* WFMMod::m_rfFilter private
Definition at line 287 of file wfmmod.h.
Referenced by applyChannelSettings(), applySettings(), pull(), WFMMod(), and ~WFMMod().
m_rfFilterBuffer
fftfilt::cmplx* WFMMod::m_rfFilterBuffer private
Definition at line 289 of file wfmmod.h.
Referenced by pull(), WFMMod(), and ~WFMMod().
m_rfFilterBufferIndex
int WFMMod::m_rfFilterBufferIndex private
Definition at line 290 of file wfmmod.h.
Referenced by pull(), and WFMMod().
m_rfFilterFFTLength
const int WFMMod::m_rfFilterFFTLength = 1024 static private
Definition at line 288 of file wfmmod.h.
Referenced by WFMMod().
m_sampleBuffer
SampleVector WFMMod::m_sampleBuffer private
Definition at line 300 of file wfmmod.h.
m_sampleRate
int WFMMod::m_sampleRate private
Definition at line 307 of file wfmmod.h.
Referenced by WFMMod::MsgConfigureChannelizer::getSampleRate(), WFMMod::MsgReportFileSourceStreamData::getSampleRate(), openFileStream(), and seekFileStream().
m_settings
WFMModSettings WFMMod::m_settings private
Definition at line 276 of file wfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), deserialize(), handleMessage(), pull(), pullAF(), serialize(), webapiReverseSendCWSettings(), webapiSettingsGet(), webapiSettingsPutPatch(), and WFMMod().
m_settingsMutex
QMutex WFMMod::m_settingsMutex private
Definition at line 301 of file wfmmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), pull(), and seekFileStream().
m_threadedChannelizer
ThreadedBasebandSampleSource* WFMMod::m_threadedChannelizer private
Definition at line 270 of file wfmmod.h.
Referenced by WFMMod(), and ~WFMMod().
m_toneNcoRF
NCOF WFMMod::m_toneNcoRF private
Definition at line 279 of file wfmmod.h.
Referenced by applyChannelSettings(), applySettings(), pullAF(), and WFMMod().
The documentation for this class was generated from the following files:
plugins/channeltx/modwfm/wfmmod.h
plugins/channeltx/modwfm/wfmmod.cpp