SDRAngel: FileSourceGUI Class Reference
FileSourceGUI Class Reference
#include <filesourcegui.h>
Public Slots
void channelMarkerChangedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static FileSourceGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx)
Private Slots
void handleSourceMessages ()
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void on_interpolationFactor_currentIndexChanged (int index)
void on_position_valueChanged (int value)
void on_gain_valueChanged (int value)
void on_showFileDialog_clicked (bool checked)
void on_playLoop_toggled (bool checked)
void on_play_toggled (bool checked)
void on_navTime_valueChanged (int value)
void tick ()
Private Member Functions
FileSourceGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx, QWidget *parent=nullptr)
virtual ~FileSourceGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void applyChannelSettings ()
void configureFileName ()
void updateWithAcquisition ()
void updateWithStreamData ()
void updateWithStreamTime ()
void displaySettings ()
void displayRateAndShift ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
void applyInterpolation ()
void applyPosition ()
Private Attributes
Ui::FileSourceGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
FileSourceSettings m_settings
int m_sampleRate
double m_shiftFrequencyFactor
Channel frequency shift factor.
QString m_fileName
int m_fileSampleRate
quint32 m_fileSampleSize
quint64 m_recordLength
quint64 m_startingTimeStamp
quint64 m_samplesCount
bool m_acquisition
bool m_enableNavTime
bool m_doApplySettings
FileSource * m_fileSource
MessageQueue m_inputMessageQueue
QTime m_time
uint32_t m_tickCount
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 39 of file filesourcegui.h.
Constructor & Destructor Documentation
FileSourceGUI()
FileSourceGUI::FileSourceGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx, QWidget * parent = nullptr) explicit private
Definition at line 156 of file filesourcegui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), channelMarkerChangedByCursor(), LevelMeterSignalDB::ColorGreenAndBlue, displaySettings(), getInputMessageQueue(), DeviceAPI::getMasterTimer(), handleSourceMessages(), FileSource::m_channelIdURI, m_channelMarker, DeviceUISet::m_deviceAPI, m_deviceUISet, m_fileSource, FileSourceSettings::m_rgbColor, m_settings, m_time, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerTxChannelInstance(), ChannelMarker::setCenterFrequency(), FileSourceSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSource::setMessageQueueToGUI(), ChannelMarker::setMovable(), ChannelMarker::setSourceOrSinkStream(), ChannelMarker::setTitle(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                              :
         RollupWidget(parent),
         ui(new Ui::FileSourceGUI),
         m_pluginAPI(pluginAPI),
         m_deviceUISet(deviceUISet),
         m_sampleRate(0),
         m_shiftFrequencyFactor(0.0),
         m_fileSampleRate(0),
         m_fileSampleSize(0),
         m_recordLength(0),
         m_startingTimeStamp(0),
         m_samplesCount(0),
         m_acquisition(false),
         m_enableNavTime(false),
         m_doApplySettings(true),
         m_tickCount(0)
 {
     (void) channelTx;
     ui->setupUi(this);
     ui->channelPowerMeter->setColorTheme(LevelMeterSignalDB::ColorGreenAndBlue);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_fileSource = (FileSource*) channelTx;
     m_fileSource->setMessageQueueToGUI(getInputMessageQueue());
     connect(&(m_deviceUISet->m_deviceAPI->getMasterTimer()), SIGNAL(timeout()), this, SLOT(tick()));
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("File source");
     m_channelMarker.setMovable(false); // do not let user move the center arbitrarily
     m_channelMarker.setSourceOrSinkStream(false);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     m_settings.setChannelMarker(&m_channelMarker);
     m_deviceUISet->registerTxChannelInstance(FileSource::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     m_time.start();
     displaySettings();
     applySettings(true);
 }
~FileSourceGUI()
FileSourceGUI::~FileSourceGUI () private virtual
Definition at line 211 of file filesourcegui.cpp.
References m_deviceUISet, m_fileSource, DeviceUISet::removeTxChannelInstance(), and ui.
 {
     m_deviceUISet->removeTxChannelInstance(this);
     delete m_fileSource;
     delete ui;
 }
Member Function Documentation
applyChannelSettings()
void FileSourceGUI::applyChannelSettings () private
Definition at line 234 of file filesourcegui.cpp.
References FileSource::MsgConfigureChannelizer::create(), BasebandSampleSource::getInputMessageQueue(), m_doApplySettings, m_fileSource, FileSourceSettings::m_filterChainHash, FileSourceSettings::m_log2Interp, m_settings, and MessageQueue::push().
Referenced by applyPosition().
 {
     if (m_doApplySettings)
     {
         FileSource::MsgConfigureChannelizer *msgChan = FileSource::MsgConfigureChannelizer::create(
                 m_settings.m_log2Interp,
                 m_settings.m_filterChainHash);
         m_fileSource->getInputMessageQueue()->push(msgChan);
     }
 }
applyInterpolation()
void FileSourceGUI::applyInterpolation () private
Definition at line 454 of file filesourcegui.cpp.
References applyPosition(), i, FileSourceSettings::m_filterChainHash, FileSourceSettings::m_log2Interp, m_settings, and ui.
Referenced by displaySettings(), and on_interpolationFactor_currentIndexChanged().
 {
     uint32_t maxHash = 1;
     for (uint32_t i = 0; i < m_settings.m_log2Interp; i++) {
         maxHash *= 3;
     }
     ui->position->setMaximum(maxHash-1);
     ui->position->setValue(m_settings.m_filterChainHash);
     m_settings.m_filterChainHash = ui->position->value();
     applyPosition();
 }
applyPosition()
void FileSourceGUI::applyPosition () private
Definition at line 468 of file filesourcegui.cpp.
References applyChannelSettings(), arg(), HBFilterChainConverter::convertToString(), displayRateAndShift(), FileSourceSettings::m_filterChainHash, FileSourceSettings::m_log2Interp, m_settings, m_shiftFrequencyFactor, and ui.
Referenced by applyInterpolation(), and on_position_valueChanged().
 {
     ui->filterChainIndex->setText(tr("%1").arg(m_settings.m_filterChainHash));
     QString s;
     m_shiftFrequencyFactor = HBFilterChainConverter::convertToString(m_settings.m_log2Interp, m_settings.m_filterChainHash, s);
     ui->filterChainText->setText(s);
     displayRateAndShift();
     applyChannelSettings();
 }
applySettings()
void FileSourceGUI::applySettings (bool force = false) private
Definition at line 223 of file filesourcegui.cpp.
References FileSource::MsgConfigureFileSource::create(), ChannelMarker::getColor(), BasebandSampleSource::getInputMessageQueue(), m_channelMarker, m_doApplySettings, m_fileSource, m_settings, MessageQueue::push(), and RollupWidget::setTitleColor().
Referenced by deserialize(), FileSourceGUI(), on_gain_valueChanged(), onMenuDialogCalled(), and resetToDefaults().
 {
     if (m_doApplySettings)
     {
         setTitleColor(m_channelMarker.getColor());
         FileSource::MsgConfigureFileSource* message = FileSource::MsgConfigureFileSource::create(m_settings, force);
         m_fileSource->getInputMessageQueue()->push(message);
     }
 }
blockApplySettings()
void FileSourceGUI::blockApplySettings (bool block) private
Definition at line 218 of file filesourcegui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void FileSourceGUI::channelMarkerChangedByCursor () slot
Definition at line 504 of file filesourcegui.cpp.
Referenced by FileSourceGUI().
 {
 }
configureFileName()
void FileSourceGUI::configureFileName () private
Definition at line 245 of file filesourcegui.cpp.
References FileSource::MsgConfigureFileSourceName::create(), BasebandSampleSource::getInputMessageQueue(), m_fileName, m_fileSource, and MessageQueue::push().
Referenced by on_showFileDialog_clicked().
 {
     qDebug() << "FileSourceGui::configureFileName: " << m_fileName.toStdString().c_str();
     FileSource::MsgConfigureFileSourceName* message = FileSource::MsgConfigureFileSourceName::create(m_fileName);
     m_fileSource->getInputMessageQueue()->push(message);
 }
create()
FileSourceGUI * FileSourceGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx) static
Definition at line 35 of file filesourcegui.cpp.
References FileSourceGUI().
Referenced by FileSourcePlugin::createTxChannelGUI().
 {
     FileSourceGUI* gui = new FileSourceGUI(pluginAPI, deviceUISet, channelTx);
     return gui;
 }
deserialize()
bool FileSourceGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 77 of file filesourcegui.cpp.
References applySettings(), FileSourceSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void FileSourceGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 41 of file filesourcegui.cpp.
 {
     delete this;
 }
displayRateAndShift()
void FileSourceGUI::displayRateAndShift () private
Definition at line 322 of file filesourcegui.cpp.
References arg(), m_channelMarker, FileSourceSettings::m_log2Interp, m_sampleRate, m_settings, m_shiftFrequencyFactor, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), and ui.
Referenced by applyPosition(), and handleMessage().
 {
     int shift = m_shiftFrequencyFactor * m_sampleRate;
     double channelSampleRate = ((double) m_sampleRate) / (1<<m_settings.m_log2Interp);
     QLocale loc;
     ui->offsetFrequencyText->setText(tr("%1 Hz").arg(loc.toString(shift)));
     ui->channelRateText->setText(tr("%1k").arg(QString::number(channelSampleRate / 1000.0, 'g', 5)));
     m_channelMarker.setCenterFrequency(shift);
     m_channelMarker.setBandwidth(channelSampleRate);
 }
displaySettings()
void FileSourceGUI::displaySettings () private
Definition at line 302 of file filesourcegui.cpp.
References applyInterpolation(), arg(), blockApplySettings(), ChannelMarker::getTitle(), m_channelMarker, FileSourceSettings::m_gainDB, FileSourceSettings::m_log2Interp, FileSourceSettings::m_rgbColor, m_sampleRate, m_settings, FileSourceSettings::m_title, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by deserialize(), FileSourceGUI(), handleMessage(), and resetToDefaults().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.setBandwidth(m_sampleRate);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->gain->setValue(m_settings.m_gainDB);
     ui->gainText->setText(tr("%1 dB").arg(m_settings.m_gainDB));
     ui->interpolationFactor->setCurrentIndex(m_settings.m_log2Interp);
     applyInterpolation();
     blockApplySettings(false);
 }
enterEvent()
void FileSourceGUI::enterEvent (QEvent *) private
Definition at line 338 of file filesourcegui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 FileSourceGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 56 of file filesourcegui.cpp.
{
     return 0;
 }
getInputMessageQueue()
virtual MessageQueue* FileSourceGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 54 of file filesourcegui.h.
Referenced by FileSourceGUI(), and handleSourceMessages().
 { return &m_inputMessageQueue; }
getName()
QString FileSourceGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 51 of file filesourcegui.cpp.
 {
     return objectName();
 }
handleMessage()
bool FileSourceGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 89 of file filesourcegui.cpp.
References blockApplySettings(), displayRateAndShift(), displaySettings(), FileSource::MsgPlayPause::getPlayPause(), FileSource::MsgSampleRateNotification::getSampleRate(), FileSource::MsgConfigureFileSource::getSettings(), FileSource::MsgReportHeaderCRC::isOK(), m_acquisition, m_enableNavTime, m_fileSampleRate, m_fileSampleSize, m_recordLength, m_sampleRate, m_samplesCount, m_settings, m_startingTimeStamp, Message::match(), ui, updateWithAcquisition(), updateWithStreamData(), and updateWithStreamTime().
Referenced by handleSourceMessages().
 {
     if (FileSource::MsgSampleRateNotification::match(message))
     {
         FileSource::MsgSampleRateNotification& notif = (FileSource::MsgSampleRateNotification&) message;
         m_sampleRate = notif.getSampleRate();
         displayRateAndShift();
         return true;
     }
     else if (FileSource::MsgConfigureFileSource::match(message))
     {
         const FileSource::MsgConfigureFileSource& cfg = (FileSource::MsgConfigureFileSource&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (FileSource::MsgReportFileSourceAcquisition::match(message))
     {
         m_acquisition = ((FileSource::MsgReportFileSourceAcquisition&)message).getAcquisition();
         updateWithAcquisition();
         return true;
     }
     else if (FileSource::MsgReportFileSourceStreamData::match(message))
     {
         m_fileSampleRate = ((FileSource::MsgReportFileSourceStreamData&)message).getSampleRate();
         m_fileSampleSize = ((FileSource::MsgReportFileSourceStreamData&)message).getSampleSize();
         m_startingTimeStamp = ((FileSource::MsgReportFileSourceStreamData&)message).getStartingTimeStamp();
         m_recordLength = ((FileSource::MsgReportFileSourceStreamData&)message).getRecordLength();
         updateWithStreamData();
         return true;
     }
     else if (FileSource::MsgReportFileSourceStreamTiming::match(message))
     {
         m_samplesCount = ((FileSource::MsgReportFileSourceStreamTiming&)message).getSamplesCount();
         updateWithStreamTime();
         return true;
     }
     else if (FileSource::MsgPlayPause::match(message))
     {
         FileSource::MsgPlayPause& notif = (FileSource::MsgPlayPause&) message;
         bool checked = notif.getPlayPause();
         ui->play->setChecked(checked);
         ui->navTime->setEnabled(!checked);
         m_enableNavTime = !checked;
         return true;
     }
     else if (FileSource::MsgReportHeaderCRC::match(message))
     {
         FileSource::MsgReportHeaderCRC& notif = (FileSource::MsgReportHeaderCRC&) message;
         if (notif.isOK()) {
             ui->crcLabel->setStyleSheet("QLabel { background-color : green; }");
         } else {
             ui->crcLabel->setStyleSheet("QLabel { background-color : red; }");
         }
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void FileSourceGUI::handleSourceMessages () private slot
Definition at line 343 of file filesourcegui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by FileSourceGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void FileSourceGUI::leaveEvent (QEvent *) private
Definition at line 333 of file filesourcegui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_gain_valueChanged
void FileSourceGUI::on_gain_valueChanged (int value) private slot
Definition at line 405 of file filesourcegui.cpp.
References applySettings(), arg(), FileSourceSettings::m_gainDB, m_settings, and ui.
 {
     ui->gainText->setText(tr("%1 dB").arg(value));
     m_settings.m_gainDB = value;
     applySettings();
 }
on_interpolationFactor_currentIndexChanged
void FileSourceGUI::on_interpolationFactor_currentIndexChanged (int index) private slot
Definition at line 393 of file filesourcegui.cpp.
References applyInterpolation(), FileSourceSettings::m_log2Interp, and m_settings.
 {
     m_settings.m_log2Interp = index;
     applyInterpolation();
 }
on_navTime_valueChanged
void FileSourceGUI::on_navTime_valueChanged (int value) private slot
Definition at line 445 of file filesourcegui.cpp.
References FileSource::MsgConfigureFileSourceSeek::create(), BasebandSampleSource::getInputMessageQueue(), m_enableNavTime, m_fileSource, and MessageQueue::push().
 {
     if (m_enableNavTime && ((value >= 0) && (value <= 1000)))
     {
         FileSource::MsgConfigureFileSourceSeek* message = FileSource::MsgConfigureFileSourceSeek::create(value);
         m_fileSource->getInputMessageQueue()->push(message);
     }
 }
on_play_toggled
void FileSourceGUI::on_play_toggled (bool checked) private slot
Definition at line 437 of file filesourcegui.cpp.
References FileSource::MsgConfigureFileSourceWork::create(), BasebandSampleSource::getInputMessageQueue(), m_enableNavTime, m_fileSource, MessageQueue::push(), and ui.
 {
     FileSource::MsgConfigureFileSourceWork* message = FileSource::MsgConfigureFileSourceWork::create(checked);
     m_fileSource->getInputMessageQueue()->push(message);
     ui->navTime->setEnabled(!checked);
     m_enableNavTime = !checked;
 }
on_playLoop_toggled
void FileSourceGUI::on_playLoop_toggled (bool checked) private slot
Definition at line 427 of file filesourcegui.cpp.
References FileSource::MsgConfigureFileSource::create(), BasebandSampleSource::getInputMessageQueue(), m_doApplySettings, m_fileSource, FileSourceSettings::m_loop, m_settings, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         m_settings.m_loop = checked;
         FileSource::MsgConfigureFileSource *message = FileSource::MsgConfigureFileSource::create(m_settings, false);
         m_fileSource->getInputMessageQueue()->push(message);
     }
 }
on_position_valueChanged
void FileSourceGUI::on_position_valueChanged (int value) private slot
Definition at line 399 of file filesourcegui.cpp.
References applyPosition(), FileSourceSettings::m_filterChainHash, and m_settings.
 {
     m_settings.m_filterChainHash = value;
     applyPosition();
 }
on_showFileDialog_clicked
void FileSourceGUI::on_showFileDialog_clicked (bool checked) private slot
Definition at line 412 of file filesourcegui.cpp.
References configureFileName(), m_fileName, and ui.
 {
     (void) checked;
     QString fileName = QFileDialog::getOpenFileName(this,
         tr("Open I/Q record file"), ".", tr("SDR I/Q Files (*.sdriq)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "")
     {
         m_fileName = fileName;
         ui->fileNameText->setText(m_fileName);
         ui->crcLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
         configureFileName();
     }
 }
onMenuDialogCalled
void FileSourceGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 362 of file filesourcegui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, FileSourceSettings::m_reverseAPIAddress, FileSourceSettings::m_reverseAPIChannelIndex, FileSourceSettings::m_reverseAPIDeviceIndex, FileSourceSettings::m_reverseAPIPort, FileSourceSettings::m_rgbColor, m_settings, FileSourceSettings::m_title, FileSourceSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by FileSourceGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void FileSourceGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 356 of file filesourcegui.cpp.
Referenced by FileSourceGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void FileSourceGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 65 of file filesourcegui.cpp.
References applySettings(), displaySettings(), m_settings, and FileSourceSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
serialize()
QByteArray FileSourceGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 72 of file filesourcegui.cpp.
References m_settings, and FileSourceSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void FileSourceGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 60 of file filesourcegui.cpp.
 {
     (void) centerFrequency;
 }
setName()
void FileSourceGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 46 of file filesourcegui.cpp.
 {
     setObjectName(name);
 }
tick
void FileSourceGUI::tick () private slot
Definition at line 479 of file filesourcegui.cpp.
References FileSource::MsgConfigureFileSourceStreamTiming::create(), CalcDb::dbPower(), BasebandSampleSource::getInputMessageQueue(), FileSource::getMagSqLevels(), m_fileSource, m_tickCount, MessageQueue::push(), and ui.
Referenced by FileSourceGUI().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     m_fileSource->getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     double powDbAvg = CalcDb::dbPower(magsqAvg);
     double powDbPeak = CalcDb::dbPower(magsqPeak);
     ui->channelPowerMeter->levelChanged(
             (100.0f + powDbAvg) / 100.0f,
             (100.0f + powDbPeak) / 100.0f,
             nbMagsqSamples);
     if (m_tickCount % 4 == 0) {
         ui->channelPower->setText(QString::number(powDbAvg, 'f', 1));
     }
     if (++m_tickCount == 20) // once per second
     {
         FileSource::MsgConfigureFileSourceStreamTiming* message = FileSource::MsgConfigureFileSourceStreamTiming::create();
         m_fileSource->getInputMessageQueue()->push(message);
         m_tickCount = 0;
     }
 }
updateWithAcquisition()
void FileSourceGUI::updateWithAcquisition () private
Definition at line 252 of file filesourcegui.cpp.
References m_acquisition, and ui.
Referenced by handleMessage().
 {
     ui->play->blockSignals(true);
     ui->play->setChecked(m_acquisition);
     ui->play->blockSignals(false);
     ui->showFileDialog->setEnabled(!m_acquisition);
 }
updateWithStreamData()
void FileSourceGUI::updateWithStreamData () private
Definition at line 260 of file filesourcegui.cpp.
References arg(), m_fileSampleRate, m_fileSampleSize, m_recordLength, ui, and updateWithStreamTime().
Referenced by handleMessage().
 {
     ui->sampleRateText->setText(tr("%1k").arg((float) m_fileSampleRate / 1000));
     ui->sampleSizeText->setText(tr("%1b").arg(m_fileSampleSize));
     QTime recordLength(0, 0, 0, 0);
     recordLength = recordLength.addSecs(m_recordLength);
     QString s_time = recordLength.toString("HH:mm:ss");
     ui->recordLengthText->setText(s_time);
     updateWithStreamTime();
 }
updateWithStreamTime()
void FileSourceGUI::updateWithStreamTime () private
Definition at line 271 of file filesourcegui.cpp.
References m_enableNavTime, m_fileSampleRate, m_recordLength, m_samplesCount, m_startingTimeStamp, and ui.
Referenced by handleMessage(), and updateWithStreamData().
 {
     qint64 t_sec = 0;
     qint64 t_msec = 0;
     if (m_fileSampleRate > 0)
     {
         t_sec = m_samplesCount / m_fileSampleRate;
         t_msec = (m_samplesCount - (t_sec * m_fileSampleRate)) * 1000LL / m_fileSampleRate;
     }
     QTime t(0, 0, 0, 0);
     t = t.addSecs(t_sec);
     t = t.addMSecs(t_msec);
     QString s_timems = t.toString("HH:mm:ss.zzz");
     ui->relTimeText->setText(s_timems);
     qint64 startingTimeStampMsec = m_startingTimeStamp * 1000LL;
     QDateTime dt = QDateTime::fromMSecsSinceEpoch(startingTimeStampMsec);
     dt = dt.addSecs(t_sec);
     dt = dt.addMSecs(t_msec);
     QString s_date = dt.toString("yyyy-MM-dd HH:mm:ss.zzz");
     ui->absTimeText->setText(s_date);
     if (!m_enableNavTime)
     {
         float posRatio = (float) t_sec / (float) m_recordLength;
         ui->navTime->setValue((int) (posRatio * 1000.0));
     }
 }
Member Data Documentation
m_acquisition
bool FileSourceGUI::m_acquisition private
Definition at line 74 of file filesourcegui.h.
Referenced by handleMessage(), and updateWithAcquisition().
m_channelMarker
ChannelMarker FileSourceGUI::m_channelMarker private
Definition at line 64 of file filesourcegui.h.
Referenced by applySettings(), displayRateAndShift(), displaySettings(), enterEvent(), FileSourceGUI(), leaveEvent(), and onMenuDialogCalled().
m_deviceUISet
DeviceUISet* FileSourceGUI::m_deviceUISet private
Definition at line 63 of file filesourcegui.h.
Referenced by FileSourceGUI(), and ~FileSourceGUI().
m_doApplySettings
bool FileSourceGUI::m_doApplySettings private
Definition at line 76 of file filesourcegui.h.
Referenced by applyChannelSettings(), applySettings(), blockApplySettings(), and on_playLoop_toggled().
m_enableNavTime
bool FileSourceGUI::m_enableNavTime private
Definition at line 75 of file filesourcegui.h.
Referenced by handleMessage(), on_navTime_valueChanged(), on_play_toggled(), and updateWithStreamTime().
m_fileName
QString FileSourceGUI::m_fileName private
Definition at line 68 of file filesourcegui.h.
Referenced by configureFileName(), and on_showFileDialog_clicked().
m_fileSampleRate
int FileSourceGUI::m_fileSampleRate private
Definition at line 69 of file filesourcegui.h.
Referenced by handleMessage(), updateWithStreamData(), and updateWithStreamTime().
m_fileSampleSize
quint32 FileSourceGUI::m_fileSampleSize private
Definition at line 70 of file filesourcegui.h.
Referenced by handleMessage(), and updateWithStreamData().
m_fileSource
FileSource* FileSourceGUI::m_fileSource private
Definition at line 78 of file filesourcegui.h.
Referenced by applyChannelSettings(), applySettings(), configureFileName(), FileSourceGUI(), on_navTime_valueChanged(), on_play_toggled(), on_playLoop_toggled(), tick(), and ~FileSourceGUI().
m_inputMessageQueue
MessageQueue FileSourceGUI::m_inputMessageQueue private
Definition at line 79 of file filesourcegui.h.
m_pluginAPI
PluginAPI* FileSourceGUI::m_pluginAPI private
Definition at line 62 of file filesourcegui.h.
m_recordLength
quint64 FileSourceGUI::m_recordLength private
Definition at line 71 of file filesourcegui.h.
Referenced by handleMessage(), updateWithStreamData(), and updateWithStreamTime().
m_sampleRate
int FileSourceGUI::m_sampleRate private
Definition at line 66 of file filesourcegui.h.
Referenced by displayRateAndShift(), displaySettings(), and handleMessage().
m_samplesCount
quint64 FileSourceGUI::m_samplesCount private
Definition at line 73 of file filesourcegui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_settings
FileSourceSettings FileSourceGUI::m_settings private
Definition at line 65 of file filesourcegui.h.
Referenced by applyChannelSettings(), applyInterpolation(), applyPosition(), applySettings(), deserialize(), displayRateAndShift(), displaySettings(), FileSourceGUI(), handleMessage(), on_gain_valueChanged(), on_interpolationFactor_currentIndexChanged(), on_playLoop_toggled(), on_position_valueChanged(), onMenuDialogCalled(), resetToDefaults(), and serialize().
m_shiftFrequencyFactor
double FileSourceGUI::m_shiftFrequencyFactor private
Channel frequency shift factor.
Definition at line 67 of file filesourcegui.h.
Referenced by applyPosition(), and displayRateAndShift().
m_startingTimeStamp
quint64 FileSourceGUI::m_startingTimeStamp private
Definition at line 72 of file filesourcegui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_tickCount
uint32_t FileSourceGUI::m_tickCount private
Definition at line 82 of file filesourcegui.h.
Referenced by tick().
m_time
QTime FileSourceGUI::m_time private
Definition at line 81 of file filesourcegui.h.
Referenced by FileSourceGUI().
ui
Ui::FileSourceGUI* FileSourceGUI::ui private
Definition at line 61 of file filesourcegui.h.
Referenced by applyInterpolation(), applyPosition(), displayRateAndShift(), displaySettings(), FileSourceGUI(), handleMessage(), on_gain_valueChanged(), on_play_toggled(), on_showFileDialog_clicked(), tick(), updateWithAcquisition(), updateWithStreamData(), updateWithStreamTime(), and ~FileSourceGUI().
The documentation for this class was generated from the following files:
plugins/channeltx/filesource/filesourcegui.h
plugins/channeltx/filesource/filesourcegui.cpp