SDRAngel: HackRFOutputGui Class Reference
HackRFOutputGui Class Reference
#include <hackrfoutputgui.h>
Public Types
enum HackRFImgRejValue { HACKRF_IMGREJ_BYPASS = 0, HACKRF_IMGREJ_LOWPASS, HACKRF_IMGREJ_HIGHPASS, HACKRF_IMGREJ_NB }
Public Member Functions
HackRFOutputGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~HackRFOutputGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_centerFrequency_changed (quint64 value)
void on_sampleRate_changed (quint64 value)
void on_LOppm_valueChanged (int value)
void on_biasT_stateChanged (int state)
void on_interp_currentIndexChanged (int index)
void on_fcPos_currentIndexChanged (int index)
void on_lnaExt_stateChanged (int state)
void on_bbFilter_currentIndexChanged (int index)
void on_txvga_valueChanged (int value)
void on_startStop_toggled (bool checked)
void on_sampleRateMode_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void displaySettings ()
void displaySampleRate ()
void displayFcTooltip ()
void displayBandwidths ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void blockApplySettings (bool block)
Private Attributes
Ui::HackRFOutputGui * ui
DeviceUISet * m_deviceUISet
bool m_forceSettings
HackRFOutputSettings m_settings
bool m_sampleRateMode
true: device, false: base band sample rate update mode
QTimer m_updateTimer
QTimer m_statusTimer
DeviceSampleSink * m_deviceSampleSink
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
bool m_doApplySettings
Detailed Description
Definition at line 38 of file hackrfoutputgui.h.
Member Enumeration Documentation
HackRFImgRejValue
enum HackRFOutputGui::HackRFImgRejValue
Enumerator
HACKRF_IMGREJ_BYPASS
HACKRF_IMGREJ_LOWPASS
HACKRF_IMGREJ_HIGHPASS
HACKRF_IMGREJ_NB
Definition at line 42 of file hackrfoutputgui.h.
     {
         HACKRF_IMGREJ_BYPASS = 0,
         HACKRF_IMGREJ_LOWPASS,
         HACKRF_IMGREJ_HIGHPASS,
         HACKRF_IMGREJ_NB
     } HackRFImgRejValue;
Constructor & Destructor Documentation
HackRFOutputGui()
HackRFOutputGui::HackRFOutputGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 37 of file hackrfoutputgui.cpp.
References displayBandwidths(), displaySettings(), DeviceAPI::getSampleSink(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceSampleSink, m_deviceUISet, m_inputMessageQueue, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), sendSettings(), ui, updateHardware(), and updateStatus().
                                                                           :
     QWidget(parent),
     ui(new Ui::HackRFOutputGui),
     m_deviceUISet(deviceUISet),
     m_forceSettings(true),
     m_settings(),
     m_sampleRateMode(true),
     m_deviceSampleSink(0),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_doApplySettings(true)
 {
     m_deviceSampleSink = (HackRFOutput*) m_deviceUISet->m_deviceAPI->getSampleSink();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, 0U, 7250000U);
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(8, 1000000U, 20000000U);
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     displayBandwidths();
     sendSettings();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
 }
~HackRFOutputGui()
HackRFOutputGui::~HackRFOutputGui () virtual
Definition at line 71 of file hackrfoutputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void HackRFOutputGui::blockApplySettings (bool block) private
Definition at line 131 of file hackrfoutputgui.cpp.
References m_doApplySettings.
Referenced by displayBandwidths(), displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool HackRFOutputGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 115 of file hackrfoutputgui.cpp.
References HackRFOutputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void HackRFOutputGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 76 of file hackrfoutputgui.cpp.
 {
     delete this;
 }
displayBandwidths()
void HackRFOutputGui::displayBandwidths () private
Definition at line 265 of file hackrfoutputgui.cpp.
References arg(), blockApplySettings(), HackRFBandwidths::getBandwidthIndex(), i, HackRFOutputSettings::m_bandwidth, HackRFBandwidths::m_bw_k, HackRFBandwidths::m_nb_bw, m_settings, and ui.
Referenced by HackRFOutputGui().
 {
     blockApplySettings(true);
     unsigned int savedIndex = HackRFBandwidths::getBandwidthIndex(m_settings.m_bandwidth/1000);
     ui->bbFilter->blockSignals(true);
     ui->bbFilter->clear();
     for (unsigned int i = 0; i < HackRFBandwidths::m_nb_bw; i++)
     {
         ui->bbFilter->addItem(QString("%1M").arg(QString::number(HackRFBandwidths::m_bw_k[i]/1000.0, 'f', 2)));
     }
     ui->bbFilter->blockSignals(false);
     if (savedIndex < HackRFBandwidths::m_nb_bw)
     {
         ui->bbFilter->setCurrentIndex(savedIndex);
     }
     else
     {
         ui->bbFilter->setCurrentIndex((int) HackRFBandwidths::m_nb_bw-1);
     }
     blockApplySettings(false);
 }
displayFcTooltip()
void HackRFOutputGui::displayFcTooltip () private
Definition at line 232 of file hackrfoutputgui.cpp.
References arg(), DeviceSampleSink::calculateFrequencyShift(), HackRFOutputSettings::m_devSampleRate, HackRFOutputSettings::m_fcPos, HackRFOutputSettings::m_log2Interp, m_settings, and ui.
Referenced by displaySampleRate(), on_fcPos_currentIndexChanged(), and on_sampleRate_changed().
 {
     int32_t fShift = DeviceSampleSink::calculateFrequencyShift(
         m_settings.m_log2Interp,
         (DeviceSampleSink::fcPos_t) m_settings.m_fcPos,
         m_settings.m_devSampleRate);
     ui->fcPos->setToolTip(tr("Relative position of device center frequency: %1 kHz").arg(QString::number(fShift / 1000.0f, 'g', 5)));
 }
displaySampleRate()
void HackRFOutputGui::displaySampleRate () private
Definition at line 202 of file hackrfoutputgui.cpp.
References arg(), displayFcTooltip(), HackRFOutputSettings::m_devSampleRate, HackRFOutputSettings::m_log2Interp, m_sampleRateMode, m_settings, and ui.
Referenced by displaySettings(), on_interp_currentIndexChanged(), on_sampleRateMode_toggled(), and updateSampleRateAndFrequency().
 {
     ui->sampleRate->blockSignals(true);
     displayFcTooltip();
     if (m_sampleRateMode)
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(60,60,60); }");
         ui->sampleRateMode->setText("SR");
         ui->sampleRate->setValueRange(8, 1000000U, 20000000U);
         ui->sampleRate->setValue(m_settings.m_devSampleRate);
         ui->sampleRate->setToolTip("Host to device sample rate (S/s)");
         ui->deviceRateText->setToolTip("Baseband sample rate (S/s)");
         uint32_t basebandSampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Interp);
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(basebandSampleRate / 1000.0f, 'g', 5)));
     }
     else
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(50,50,50); }");
         ui->sampleRateMode->setText("BB");
         ui->sampleRate->setValueRange(8, 1000000U/(1<<m_settings.m_log2Interp), 20000000U/(1<<m_settings.m_log2Interp));
         ui->sampleRate->setValue(m_settings.m_devSampleRate/(1<<m_settings.m_log2Interp));
         ui->sampleRate->setToolTip("Baseband sample rate (S/s)");
         ui->deviceRateText->setToolTip("Host to device sample rate (S/s)");
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_settings.m_devSampleRate / 1000.0f, 'g', 5)));
     }
     ui->sampleRate->blockSignals(false);
 }
displaySettings()
void HackRFOutputGui::displaySettings () private
Definition at line 241 of file hackrfoutputgui.cpp.
References arg(), blockApplySettings(), displaySampleRate(), HackRFBandwidths::getBandwidthIndex(), HackRFOutputSettings::m_bandwidth, HackRFOutputSettings::m_biasT, HackRFOutputSettings::m_centerFrequency, HackRFOutputSettings::m_fcPos, HackRFOutputSettings::m_lnaExt, HackRFOutputSettings::m_log2Interp, HackRFOutputSettings::m_LOppmTenths, m_settings, HackRFOutputSettings::m_vgaGain, and ui.
Referenced by deserialize(), HackRFOutputGui(), handleMessage(), resetToDefaults(), and setCenterFrequency().
 {
     blockApplySettings(true);
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     ui->LOppm->setValue(m_settings.m_LOppmTenths);
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     ui->biasT->setChecked(m_settings.m_biasT);
     displaySampleRate();
     ui->interp->setCurrentIndex(m_settings.m_log2Interp);
     ui->fcPos->setCurrentIndex((int) m_settings.m_fcPos);
     ui->lnaExt->setChecked(m_settings.m_lnaExt);
     ui->txvgaGainText->setText(tr("%1dB").arg(m_settings.m_vgaGain));
     ui->txvga->setValue(m_settings.m_vgaGain);
     unsigned int bandwidthIndex = HackRFBandwidths::getBandwidthIndex(m_settings.m_bandwidth/1000);
     ui->bbFilter->setCurrentIndex(bandwidthIndex);
     blockApplySettings(false);
 }
getCenterFrequency()
qint64 HackRFOutputGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 98 of file hackrfoutputgui.cpp.
References HackRFOutputSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* HackRFOutputGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 62 of file hackrfoutputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString HackRFOutputGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 86 of file hackrfoutputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void HackRFOutputGui::handleInputMessages () private slot
Definition at line 167 of file hackrfoutputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by HackRFOutputGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("HackRFOutputGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("HackRFOutputGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool HackRFOutputGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 137 of file hackrfoutputgui.cpp.
References blockApplySettings(), displaySettings(), HackRFOutput::MsgConfigureHackRF::getSettings(), HackRFOutput::MsgStartStop::getStartStop(), m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (HackRFOutput::MsgConfigureHackRF::match(message))
     {
         const HackRFOutput::MsgConfigureHackRF& cfg = (HackRFOutput::MsgConfigureHackRF&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (HackRFOutput::MsgReportHackRF::match(message))
     {
         displaySettings();
         return true;
     }
     else if (HackRFOutput::MsgStartStop::match(message))
     {
         HackRFOutput::MsgStartStop& notif = (HackRFOutput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_bbFilter_currentIndexChanged
void HackRFOutputGui::on_bbFilter_currentIndexChanged (int index) private slot
Definition at line 321 of file hackrfoutputgui.cpp.
References HackRFBandwidths::getBandwidth(), HackRFOutputSettings::m_bandwidth, m_settings, and sendSettings().
 {
     int newBandwidth = HackRFBandwidths::getBandwidth(index);
     m_settings.m_bandwidth = newBandwidth * 1000;
     sendSettings();
 }
on_biasT_stateChanged
void HackRFOutputGui::on_biasT_stateChanged (int state) private slot
Definition at line 328 of file hackrfoutputgui.cpp.
References HackRFOutputSettings::m_biasT, m_settings, and sendSettings().
 {
     m_settings.m_biasT = (state == Qt::Checked);
     sendSettings();
 }
on_centerFrequency_changed
void HackRFOutputGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 296 of file hackrfoutputgui.cpp.
References HackRFOutputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_fcPos_currentIndexChanged
void HackRFOutputGui::on_fcPos_currentIndexChanged (int index) private slot
Definition at line 357 of file hackrfoutputgui.cpp.
References displayFcTooltip(), HackRFOutputSettings::m_fcPos, m_settings, and sendSettings().
 {
     m_settings.m_fcPos = (HackRFOutputSettings::fcPos_t) (index < 0 ? 0 : index > 2 ? 2 : index);
     displayFcTooltip();
     sendSettings();
 }
on_interp_currentIndexChanged
void HackRFOutputGui::on_interp_currentIndexChanged (int index) private slot
Definition at line 340 of file hackrfoutputgui.cpp.
References displaySampleRate(), HackRFOutputSettings::m_devSampleRate, HackRFOutputSettings::m_log2Interp, m_sampleRateMode, m_settings, sendSettings(), and ui.
 {
     if ((index <0) || (index > 6)) {
         return;
     }
     m_settings.m_log2Interp = index;
     displaySampleRate();
     m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     if (!m_sampleRateMode) {
         m_settings.m_devSampleRate <<= m_settings.m_log2Interp;
     }
     sendSettings();
 }
on_lnaExt_stateChanged
void HackRFOutputGui::on_lnaExt_stateChanged (int state) private slot
Definition at line 334 of file hackrfoutputgui.cpp.
References HackRFOutputSettings::m_lnaExt, m_settings, and sendSettings().
 {
     m_settings.m_lnaExt = (state == Qt::Checked);
     sendSettings();
 }
on_LOppm_valueChanged
void HackRFOutputGui::on_LOppm_valueChanged (int value) private slot
Definition at line 314 of file hackrfoutputgui.cpp.
References arg(), HackRFOutputSettings::m_LOppmTenths, m_settings, sendSettings(), and ui.
 {
     m_settings.m_LOppmTenths = value;
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     sendSettings();
 }
on_sampleRate_changed
void HackRFOutputGui::on_sampleRate_changed (quint64 value) private slot
Definition at line 302 of file hackrfoutputgui.cpp.
References displayFcTooltip(), HackRFOutputSettings::m_devSampleRate, HackRFOutputSettings::m_log2Interp, m_sampleRateMode, m_settings, and sendSettings().
 {
     m_settings.m_devSampleRate = value;
     if (!m_sampleRateMode) {
         m_settings.m_devSampleRate <<= m_settings.m_log2Interp;
     }
     displayFcTooltip();
     sendSettings();
 }
on_sampleRateMode_toggled
void HackRFOutputGui::on_sampleRateMode_toggled (bool checked) private slot
Definition at line 383 of file hackrfoutputgui.cpp.
References displaySampleRate(), and m_sampleRateMode.
 {
     m_sampleRateMode = checked;
     displaySampleRate();
 }
on_startStop_toggled
void HackRFOutputGui::on_startStop_toggled (bool checked) private slot
Definition at line 374 of file hackrfoutputgui.cpp.
References HackRFOutput::MsgStartStop::create(), DeviceSampleSink::getInputMessageQueue(), m_deviceSampleSink, m_doApplySettings, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         HackRFOutput::MsgStartStop *message = HackRFOutput::MsgStartStop::create(checked);
         m_deviceSampleSink->getInputMessageQueue()->push(message);
     }
 }
on_txvga_valueChanged
void HackRFOutputGui::on_txvga_valueChanged (int value) private slot
Definition at line 364 of file hackrfoutputgui.cpp.
References arg(), m_settings, HackRFOutputSettings::m_vgaGain, sendSettings(), and ui.
 {
     if ((value < 0) || (value > 47))
         return;
     ui->txvgaGainText->setText(tr("%1dB").arg(value));
     m_settings.m_vgaGain = value;
     sendSettings();
 }
openDeviceSettingsDialog
void HackRFOutputGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 431 of file hackrfoutputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), HackRFOutputSettings::m_reverseAPIAddress, HackRFOutputSettings::m_reverseAPIDeviceIndex, HackRFOutputSettings::m_reverseAPIPort, m_settings, HackRFOutputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by HackRFOutputGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void HackRFOutputGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 91 of file hackrfoutputgui.cpp.
References displaySettings(), m_settings, HackRFOutputSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void HackRFOutputGui::sendSettings () private
Definition at line 290 of file hackrfoutputgui.cpp.
References m_updateTimer.
Referenced by deserialize(), HackRFOutputGui(), on_bbFilter_currentIndexChanged(), on_biasT_stateChanged(), on_centerFrequency_changed(), on_fcPos_currentIndexChanged(), on_interp_currentIndexChanged(), on_lnaExt_stateChanged(), on_LOppm_valueChanged(), on_sampleRate_changed(), on_txvga_valueChanged(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray HackRFOutputGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 110 of file hackrfoutputgui.cpp.
References m_settings, and HackRFOutputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void HackRFOutputGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 103 of file hackrfoutputgui.cpp.
References displaySettings(), HackRFOutputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void HackRFOutputGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 81 of file hackrfoutputgui.cpp.
 {
     setObjectName(name);
 }
updateHardware
void HackRFOutputGui::updateHardware () private slot
Definition at line 389 of file hackrfoutputgui.cpp.
References HackRFOutput::MsgConfigureHackRF::create(), DeviceSampleSink::getInputMessageQueue(), m_deviceSampleSink, m_doApplySettings, m_forceSettings, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by HackRFOutputGui().
 {
     if (m_doApplySettings)
     {
         qDebug() << "HackRFOutputGui::updateHardware";
         HackRFOutput::MsgConfigureHackRF* message = HackRFOutput::MsgConfigureHackRF::create(m_settings, m_forceSettings);
         m_deviceSampleSink->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void HackRFOutputGui::updateSampleRateAndFrequency () private
Definition at line 195 of file hackrfoutputgui.cpp.
References displaySampleRate(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), and GLSpectrum::setSampleRate().
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     displaySampleRate();
 }
updateStatus
void HackRFOutputGui::updateStatus () private slot
Definition at line 401 of file hackrfoutputgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by HackRFOutputGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 ui->startStop->setChecked(false);
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 HackRFOutputGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 76 of file hackrfoutputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceSampleSink
DeviceSampleSink* HackRFOutputGui::m_deviceSampleSink private
Definition at line 74 of file hackrfoutputgui.h.
Referenced by HackRFOutputGui(), on_startStop_toggled(), and updateHardware().
m_deviceUISet
DeviceUISet* HackRFOutputGui::m_deviceUISet private
Definition at line 68 of file hackrfoutputgui.h.
Referenced by HackRFOutputGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool HackRFOutputGui::m_doApplySettings private
Definition at line 79 of file hackrfoutputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_forceSettings
bool HackRFOutputGui::m_forceSettings private
Definition at line 69 of file hackrfoutputgui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue HackRFOutputGui::m_inputMessageQueue private
Definition at line 78 of file hackrfoutputgui.h.
Referenced by HackRFOutputGui(), and handleInputMessages().
m_lastEngineState
int HackRFOutputGui::m_lastEngineState private
Definition at line 77 of file hackrfoutputgui.h.
Referenced by updateStatus().
m_sampleRate
int HackRFOutputGui::m_sampleRate private
Definition at line 75 of file hackrfoutputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateMode
bool HackRFOutputGui::m_sampleRateMode private
true: device, false: base band sample rate update mode
Definition at line 71 of file hackrfoutputgui.h.
Referenced by displaySampleRate(), on_interp_currentIndexChanged(), on_sampleRate_changed(), and on_sampleRateMode_toggled().
m_settings
HackRFOutputSettings HackRFOutputGui::m_settings private
Definition at line 70 of file hackrfoutputgui.h.
Referenced by deserialize(), displayBandwidths(), displayFcTooltip(), displaySampleRate(), displaySettings(), getCenterFrequency(), handleMessage(), on_bbFilter_currentIndexChanged(), on_biasT_stateChanged(), on_centerFrequency_changed(), on_fcPos_currentIndexChanged(), on_interp_currentIndexChanged(), on_lnaExt_stateChanged(), on_LOppm_valueChanged(), on_sampleRate_changed(), on_txvga_valueChanged(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), and updateHardware().
m_statusTimer
QTimer HackRFOutputGui::m_statusTimer private
Definition at line 73 of file hackrfoutputgui.h.
Referenced by HackRFOutputGui().
m_updateTimer
QTimer HackRFOutputGui::m_updateTimer private
Definition at line 72 of file hackrfoutputgui.h.
Referenced by HackRFOutputGui(), sendSettings(), and updateHardware().
ui
Ui::HackRFOutputGui* HackRFOutputGui::ui private
Definition at line 66 of file hackrfoutputgui.h.
Referenced by displayBandwidths(), displayFcTooltip(), displaySampleRate(), displaySettings(), HackRFOutputGui(), handleMessage(), on_interp_currentIndexChanged(), on_LOppm_valueChanged(), on_txvga_valueChanged(), updateStatus(), and ~HackRFOutputGui().
The documentation for this class was generated from the following files:
plugins/samplesink/hackrfoutput/hackrfoutputgui.h
plugins/samplesink/hackrfoutput/hackrfoutputgui.cpp