SDRAngel: SoapySDROutput::MsgStartStop Class Reference
SoapySDROutput::MsgStartStop Class Reference
#include <soapysdroutput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 101 of file soapysdroutput.h.
Constructor & Destructor Documentation
MsgStartStop()
SoapySDROutput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 114 of file soapysdroutput.h.
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* SoapySDROutput::MsgStartStop::create (bool startStop) inline static
Definition at line 107 of file soapysdroutput.h.
Referenced by SoapySDROutputGui::on_startStop_toggled(), and SoapySDROutput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool SoapySDROutput::MsgStartStop::getStartStop () const inline
Definition at line 105 of file soapysdroutput.h.
Referenced by SoapySDROutputGui::handleMessage(), and SoapySDROutput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool SoapySDROutput::MsgStartStop::m_startStop protected
Definition at line 112 of file soapysdroutput.h.
The documentation for this class was generated from the following file:
plugins/samplesink/soapysdroutput/soapysdroutput.h