SDRAngel: SWGSDRangel::SWGFrequency Class Reference
SWGSDRangel::SWGFrequency Class Reference
#include <SWGFrequency.h>
Public Member Functions
SWGFrequency ()
SWGFrequency (QString *json)
virtual ~SWGFrequency ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGFrequency * fromJson (QString &jsonString) override
qint32 getFrequency ()
void setFrequency (qint32 frequency)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 frequency
bool m_frequency_isSet
Detailed Description
Definition at line 31 of file SWGFrequency.h.
Constructor & Destructor Documentation
SWGFrequency() [1/2]
SWGSDRangel::SWGFrequency::SWGFrequency ()
Definition at line 30 of file SWGFrequency.cpp.
References frequency, and m_frequency_isSet.
{
     frequency = 0;
     m_frequency_isSet = false;
 }
SWGFrequency() [2/2]
SWGSDRangel::SWGFrequency::SWGFrequency (QString * json)
Definition at line 25 of file SWGFrequency.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGFrequency()
SWGSDRangel::SWGFrequency::~SWGFrequency () virtual
Definition at line 35 of file SWGFrequency.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGFrequency::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 66 of file SWGFrequency.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGFrequency::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 77 of file SWGFrequency.cpp.
References frequency, and m_frequency_isSet.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_frequency_isSet){
         obj->insert("frequency", QJsonValue(frequency));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGFrequency::cleanup ()
Definition at line 46 of file SWGFrequency.cpp.
Referenced by ~SWGFrequency().
                       {
 }
fromJson()
SWGFrequency * SWGSDRangel::SWGFrequency::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 51 of file SWGFrequency.cpp.
References fromJsonObject().
Referenced by SWGFrequency().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGFrequency::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 60 of file SWGFrequency.cpp.
References frequency, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&frequency, pJson["frequency"], "qint32", "");
 }
getFrequency()
qint32 SWGSDRangel::SWGFrequency::getFrequency ()
Definition at line 87 of file SWGFrequency.cpp.
References frequency.
{
     return frequency;
 }
init()
void SWGSDRangel::SWGFrequency::init ()
Definition at line 40 of file SWGFrequency.cpp.
References frequency, and m_frequency_isSet.
Referenced by SWGFrequency().
                    {
     frequency = 0;
     m_frequency_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGFrequency::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 98 of file SWGFrequency.cpp.
References m_frequency_isSet.
                    {
     bool isObjectUpdated = false;
     do{
         if(m_frequency_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setFrequency()
void SWGSDRangel::SWGFrequency::setFrequency (qint32 frequency)
Definition at line 91 of file SWGFrequency.cpp.
References frequency, and m_frequency_isSet.
{
     this->frequency = frequency;
     this->m_frequency_isSet = true;
 }
Member Data Documentation
frequency
qint32 SWGSDRangel::SWGFrequency::frequency private
Definition at line 51 of file SWGFrequency.h.
Referenced by asJsonObject(), fromJsonObject(), getFrequency(), init(), setFrequency(), and SWGFrequency().
m_frequency_isSet
bool SWGSDRangel::SWGFrequency::m_frequency_isSet private
Definition at line 52 of file SWGFrequency.h.
Referenced by asJsonObject(), init(), isSet(), setFrequency(), and SWGFrequency().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGFrequency.h
swagger/sdrangel/code/qt5/client/SWGFrequency.cpp