SDRAngel: HackRFOutput Class Reference
HackRFOutput Class Reference
#include <hackrfoutput.h>
Classes
class MsgConfigureHackRF
class MsgReportHackRF
class MsgStartStop
Public Member Functions
HackRFOutput (DeviceAPI *deviceAPI)
virtual ~HackRFOutput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the sink.
virtual void setSampleRate (int sampleRate)
For when the sink sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the sink.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSink
DeviceSampleSink ()
virtual ~DeviceSampleSink ()
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSourceFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
bool applySettings (const HackRFOutputSettings &settings, bool force)
void setDeviceCenterFrequency (quint64 freq_hz, qint32 LOppmTenths)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const HackRFOutputSettings &settings)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const HackRFOutputSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
HackRFOutputSettings m_settings
struct hackrf_device * m_dev
HackRFOutputThread * m_hackRFThread
QString m_deviceDescription
DeviceHackRFParams m_sharedParams
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
bool m_running
Additional Inherited Members
Public Types inherited from DeviceSampleSink
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
Static Public Member Functions inherited from DeviceSampleSink
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Interp, fcPos_t fcPos, quint32 devSampleRate)
Protected Slots inherited from DeviceSampleSink
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSink
SampleSourceFifo m_sampleSourceFifo
MessageQueue m_inputMessageQueue
Input queue to the sink.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 35 of file hackrfoutput.h.
Constructor & Destructor Documentation
HackRFOutput()
HackRFOutput::HackRFOutput (DeviceAPI * deviceAPI)
Definition at line 40 of file hackrfoutput.cpp.
Referenced by HackRFOutput::MsgReportHackRF::MsgReportHackRF().
                                                :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_dev(0),
     m_hackRFThread(0),
     m_deviceDescription("HackRFOutput"),
     m_running(false)
 {
     openDevice();
     m_deviceAPI->setNbSinkStreams(1);
     m_deviceAPI->setBuddySharedPtr(&m_sharedParams);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~HackRFOutput()
HackRFOutput::~HackRFOutput () virtual
Definition at line 55 of file hackrfoutput.cpp.
References closeDevice(), m_deviceAPI, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::setBuddySharedPtr(), and stop().
Referenced by HackRFOutput::MsgReportHackRF::MsgReportHackRF().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     closeDevice();
     m_deviceAPI->setBuddySharedPtr(0);
 }
Member Function Documentation
applySettings()
bool HackRFOutput::applySettings (const HackRFOutputSettings & settings, bool force) private
Definition at line 325 of file hackrfoutput.cpp.
References DeviceSampleSink::calculateDeviceCenterFrequency(), DeviceHackRFShared::MsgSynchronizeFrequency::create(), DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceAPI::getSamplingDeviceInputMessageQueue(), DeviceAPI::getSourceBuddies(), HackRFOutputSettings::m_bandwidth, HackRFOutputSettings::m_biasT, HackRFOutputSettings::m_centerFrequency, m_dev, m_deviceAPI, HackRFOutputSettings::m_devSampleRate, HackRFOutputSettings::m_fcPos, m_hackRFThread, HackRFOutputSettings::m_lnaExt, HackRFOutputSettings::m_log2Interp, HackRFOutputSettings::m_LOppmTenths, HackRFOutputSettings::m_reverseAPIAddress, HackRFOutputSettings::m_reverseAPIDeviceIndex, HackRFOutputSettings::m_reverseAPIPort, DeviceHackRFShared::m_sampleFifoLengthInSeconds, DeviceHackRFShared::m_sampleFifoMinSize, DeviceSampleSink::m_sampleSourceFifo, m_settings, HackRFOutputSettings::m_useReverseAPI, HackRFOutputSettings::m_vgaGain, leansdr::max(), MessageQueue::push(), SampleSourceFifo::resize(), setDeviceCenterFrequency(), HackRFOutputThread::setFcPos(), HackRFOutputThread::setLog2Interpolation(), HackRFOutputThread::startWork(), HackRFOutputThread::stopWork(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
 //  QMutexLocker mutexLocker(&m_mutex);
     bool forwardChange    = false;
     bool suspendThread    = false;
     bool threadWasRunning = false;
     hackrf_error rc;
     QList<QString> reverseAPIKeys;
     qDebug() << "HackRFOutput::applySettings"
         << " m_centerFrequency: " << settings.m_centerFrequency
         << " m_LOppmTenths: " << settings.m_LOppmTenths
         << " m_bandwidth: " << settings.m_bandwidth
         << " m_devSampleRate: " << settings.m_devSampleRate
         << " m_log2Interp: " << settings.m_log2Interp
         << " m_fcPos: " << settings.m_fcPos
         << " m_biasT: " << settings.m_biasT
         << " m_lnaExt: " << settings.m_lnaExt
         << " m_vgaGain: " << settings.m_vgaGain
         << " m_useReverseAPI: " << settings.m_useReverseAPI
         << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
         << " m_reverseAPIPort: " << settings.m_reverseAPIPort
         << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex
         << " force: " << force;
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || force) {
         reverseAPIKeys.append("devSampleRate");
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) ||
         (m_settings.m_log2Interp != settings.m_log2Interp) || force)
     {
         suspendThread = true;
     }
     if (suspendThread)
     {
         if (m_hackRFThread)
         {
             if (m_hackRFThread->isRunning())
             {
                 m_hackRFThread->stopWork();
                 threadWasRunning = true;
             }
         }
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || (m_settings.m_log2Interp != settings.m_log2Interp) || force)
     {
         forwardChange = true;
         int fifoSize = std::max(
                 (int) ((settings.m_devSampleRate/(1<<settings.m_log2Interp)) * DeviceHackRFShared::m_sampleFifoLengthInSeconds),
                 DeviceHackRFShared::m_sampleFifoMinSize);
         m_sampleSourceFifo.resize(fifoSize);
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || force)
     {
         if (m_dev != 0)
         {
             rc = (hackrf_error) hackrf_set_sample_rate_manual(m_dev, settings.m_devSampleRate, 1);
             if (rc != HACKRF_SUCCESS)
             {
                 qCritical("HackRFOutput::applySettings: could not set sample rate to %llu S/s: %s",
                         settings.m_devSampleRate,
                         hackrf_error_name(rc));
             }
             else
             {
                 qDebug("HackRFOutput::applySettings: sample rate set to %llu S/s",
                                             settings.m_devSampleRate);
             }
         }
     }
     if ((m_settings.m_log2Interp != settings.m_log2Interp) || force)
     {
         reverseAPIKeys.append("log2Interp");
         if (m_hackRFThread != 0)
         {
             m_hackRFThread->setLog2Interpolation(settings.m_log2Interp);
             qDebug() << "HackRFOutput: set interpolation to " << (1<<settings.m_log2Interp);
         }
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency) || force) {
         reverseAPIKeys.append("centerFrequency");
     }
     if ((m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force) {
         reverseAPIKeys.append("LOppmTenths");
     }
     if ((m_settings.m_fcPos != settings.m_fcPos) || force) {
         reverseAPIKeys.append("fcPos");
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency) ||
         (m_settings.m_devSampleRate != settings.m_devSampleRate) ||
         (m_settings.m_LOppmTenths != settings.m_LOppmTenths) ||
         (m_settings.m_log2Interp != settings.m_log2Interp) ||
         (m_settings.m_fcPos != settings.m_fcPos) || force)
     {
         qint64 deviceCenterFrequency = DeviceSampleSink::calculateDeviceCenterFrequency(
                 settings.m_centerFrequency,
                 0,
                 settings.m_log2Interp,
                 (DeviceSampleSink::fcPos_t) settings.m_fcPos,
                 settings.m_devSampleRate);
         setDeviceCenterFrequency(deviceCenterFrequency, settings.m_LOppmTenths);
         if (m_deviceAPI->getSourceBuddies().size() > 0)
         {
             DeviceAPI *buddy = m_deviceAPI->getSourceBuddies()[0];
             DeviceHackRFShared::MsgSynchronizeFrequency *freqMsg = DeviceHackRFShared::MsgSynchronizeFrequency::create(deviceCenterFrequency);
             buddy->getSamplingDeviceInputMessageQueue()->push(freqMsg);
         }
         forwardChange = true;
     }
     if ((m_settings.m_fcPos != settings.m_fcPos) || force)
     {
         if (m_hackRFThread != 0) {
             m_hackRFThread->setFcPos((int) settings.m_fcPos);
         }
     }
     if ((m_settings.m_vgaGain != settings.m_vgaGain) || force)
     {
         reverseAPIKeys.append("vgaGain");
         if (m_dev != 0)
         {
             rc = (hackrf_error) hackrf_set_txvga_gain(m_dev, settings.m_vgaGain);
             if (rc != HACKRF_SUCCESS) {
                 qDebug("HackRFOutput::applySettings: hackrf_set_txvga_gain failed: %s", hackrf_error_name(rc));
             } else {
                 qDebug() << "HackRFOutput:applySettings: TxVGA gain set to " << settings.m_vgaGain;
             }
         }
     }
     if ((m_settings.m_bandwidth != settings.m_bandwidth) || force)
     {
         reverseAPIKeys.append("bandwidth");
         if (m_dev != 0)
         {
             uint32_t bw_index = hackrf_compute_baseband_filter_bw_round_down_lt(settings.m_bandwidth + 1); // +1 so the round down to lower than yields desired bandwidth
             rc = (hackrf_error) hackrf_set_baseband_filter_bandwidth(m_dev, bw_index);
             if (rc != HACKRF_SUCCESS) {
                 qDebug("HackRFInput::applySettings: hackrf_set_baseband_filter_bandwidth failed: %s", hackrf_error_name(rc));
             } else {
                 qDebug() << "HackRFInput:applySettings: Baseband BW filter set to " << settings.m_bandwidth << " Hz";
             }
         }
     }
     if ((m_settings.m_biasT != settings.m_biasT) || force)
     {
         reverseAPIKeys.append("biasT");
         if (m_dev != 0)
         {
             rc = (hackrf_error) hackrf_set_antenna_enable(m_dev, (settings.m_biasT ? 1 : 0));
             if (rc != HACKRF_SUCCESS) {
                 qDebug("HackRFInput::applySettings: hackrf_set_antenna_enable failed: %s", hackrf_error_name(rc));
             } else {
                 qDebug() << "HackRFInput:applySettings: bias tee set to " << settings.m_biasT;
             }
         }
     }
     if ((m_settings.m_lnaExt != settings.m_lnaExt) || force)
     {
         reverseAPIKeys.append("lnaExt");
         if (m_dev != 0)
         {
             rc = (hackrf_error) hackrf_set_amp_enable(m_dev, (settings.m_lnaExt ? 1 : 0));
             if (rc != HACKRF_SUCCESS) {
                 qDebug("HackRFInput::applySettings: hackrf_set_amp_enable failed: %s", hackrf_error_name(rc));
             } else {
                 qDebug() << "HackRFInput:applySettings: extra LNA set to " << settings.m_lnaExt;
             }
         }
     }
     if (threadWasRunning)
     {
         m_hackRFThread->startWork();
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     if (forwardChange)
     {
         int sampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Interp);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, m_settings.m_centerFrequency);
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     return true;
 }
closeDevice()
void HackRFOutput::closeDevice () private
Definition at line 148 of file hackrfoutput.cpp.
References DeviceAPI::getSourceBuddies(), DeviceHackRFParams::m_dev, m_dev, m_deviceAPI, and m_sharedParams.
Referenced by openDevice(), and ~HackRFOutput().
 {
     if (m_deviceAPI->getSourceBuddies().size() == 0)
     {
         qDebug("HackRFOutput::closeDevice: closing device since Rx side is not open");
         if(m_dev != 0) // close HackRF
         {
             hackrf_close(m_dev);
             //hackrf_exit(); // TODO: this may not work if several HackRF Devices are running concurrently. It should be handled globally in the application
         }
     }
     m_sharedParams.m_dev = 0;
     m_dev = 0;
 }
deserialize()
bool HackRFOutput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSink.
Definition at line 185 of file hackrfoutput.cpp.
References HackRFOutput::MsgConfigureHackRF::create(), HackRFOutputSettings::deserialize(), DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and HackRFOutputSettings::resetToDefaults().
Referenced by HackRFOutput::MsgReportHackRF::MsgReportHackRF().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureHackRF* message = MsgConfigureHackRF::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureHackRF* messageToGUI = MsgConfigureHackRF::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void HackRFOutput::destroy () virtual
Implements DeviceSampleSink.
Definition at line 68 of file hackrfoutput.cpp.
Referenced by HackRFOutput::MsgReportHackRF::MsgReportHackRF().
 {
     delete this;
 }
getCenterFrequency()
quint64 HackRFOutput::getCenterFrequency () const virtual
Center frequency exposed by the sink.
Implements DeviceSampleSink.
Definition at line 218 of file hackrfoutput.cpp.
References HackRFOutputSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & HackRFOutput::getDeviceDescription () const virtual
Implements DeviceSampleSink.
Definition at line 207 of file hackrfoutput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getSampleRate()
int HackRFOutput::getSampleRate () const virtual
Sample rate exposed by the sink.
Implements DeviceSampleSink.
Definition at line 212 of file hackrfoutput.cpp.
References HackRFOutputSettings::m_devSampleRate, HackRFOutputSettings::m_log2Interp, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     int rate = m_settings.m_devSampleRate;
     return (rate / (1<<m_settings.m_log2Interp));
 }
handleMessage()
bool HackRFOutput::handleMessage (const Message & message) virtual
Implements DeviceSampleSink.
Definition at line 238 of file hackrfoutput.cpp.
References applySettings(), DeviceSampleSink::calculateCenterFrequency(), HackRFOutput::MsgConfigureHackRF::create(), DeviceAPI::getDeviceEngineInputMessageQueue(), HackRFOutput::MsgConfigureHackRF::getForce(), DeviceHackRFShared::MsgSynchronizeFrequency::getFrequency(), HackRFOutput::MsgConfigureHackRF::getSettings(), HackRFOutput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), HackRFOutputSettings::m_centerFrequency, m_deviceAPI, HackRFOutputSettings::m_devSampleRate, HackRFOutputSettings::m_fcPos, DeviceSampleSink::m_guiMessageQueue, HackRFOutputSettings::m_log2Interp, m_settings, HackRFOutputSettings::m_useReverseAPI, Message::match(), MessageQueue::push(), DeviceAPI::startDeviceEngine(), DeviceAPI::stopDeviceEngine(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (MsgConfigureHackRF::match(message))
     {
         MsgConfigureHackRF& conf = (MsgConfigureHackRF&) message;
         qDebug() << "HackRFOutput::handleMessage: MsgConfigureHackRF";
         bool success = applySettings(conf.getSettings(), conf.getForce());
         if (!success)
         {
             qDebug("HackRFOutput::handleMessage: MsgConfigureHackRF: config error");
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "HackRFOutput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else if (DeviceHackRFShared::MsgSynchronizeFrequency::match(message))
     {
         DeviceHackRFShared::MsgSynchronizeFrequency& freqMsg = (DeviceHackRFShared::MsgSynchronizeFrequency&) message;
         qint64 centerFrequency = DeviceSampleSink::calculateCenterFrequency(
             freqMsg.getFrequency(),
             0,
             m_settings.m_log2Interp,
             (DeviceSampleSink::fcPos_t) m_settings.m_fcPos,
             m_settings.m_devSampleRate);
         qDebug("HackRFOutput::handleMessage: MsgSynchronizeFrequency: centerFrequency: %lld Hz", centerFrequency);
         HackRFOutputSettings settings = m_settings;
         settings.m_centerFrequency = centerFrequency;
         if (m_guiMessageQueue)
         {
             MsgConfigureHackRF* messageToGUI = MsgConfigureHackRF::create(settings, false);
             m_guiMessageQueue->push(messageToGUI);
         }
         m_settings.m_centerFrequency = settings.m_centerFrequency;
         int sampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Interp);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, m_settings.m_centerFrequency);
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void HackRFOutput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSink.
Definition at line 116 of file hackrfoutput.cpp.
References applySettings(), and m_settings.
Referenced by HackRFOutput::MsgReportHackRF::MsgReportHackRF().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void HackRFOutput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 758 of file hackrfoutput.cpp.
Referenced by ~HackRFOutput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "HackRFOutput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("HackRFOutput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openDevice()
bool HackRFOutput::openDevice () private
Definition at line 73 of file hackrfoutput.cpp.
References closeDevice(), DeviceAPI::getBuddySharedPtr(), DeviceAPI::getSamplingDeviceSerial(), DeviceAPI::getSourceBuddies(), DeviceHackRFParams::m_dev, m_dev, m_deviceAPI, HackRFOutputSettings::m_devSampleRate, HackRFOutputSettings::m_log2Interp, DeviceSampleSink::m_sampleSourceFifo, m_settings, m_sharedParams, DeviceHackRF::open_hackrf(), and SampleSourceFifo::resize().
 {
     if (m_dev != 0)
     {
         closeDevice();
     }
     m_sampleSourceFifo.resize(m_settings.m_devSampleRate/(1<<(m_settings.m_log2Interp <= 4 ? m_settings.m_log2Interp : 4)));
     if (m_deviceAPI->getSourceBuddies().size() > 0)
     {
         DeviceAPI *buddy = m_deviceAPI->getSourceBuddies()[0];
         DeviceHackRFParams *buddySharedParams = (DeviceHackRFParams *) buddy->getBuddySharedPtr();
         if (buddySharedParams == 0)
         {
             qCritical("HackRFOutput::openDevice: could not get shared parameters from buddy");
             return false;
         }
         if ((m_dev = buddySharedParams->m_dev) == 0) // device is not opened by buddy
         {
             qCritical("HackRFOutput::openDevice: could not get HackRF handle from buddy");
             return false;
         }
         m_sharedParams = *(buddySharedParams); // copy parameters from buddy
         m_sharedParams.m_dev = m_dev;
     }
     else
     {
         if ((m_dev = DeviceHackRF::open_hackrf(qPrintable(m_deviceAPI->getSamplingDeviceSerial()))) == 0)
         {
             qCritical("HackRFOutput::openDevice: could not open HackRF %s", qPrintable(m_deviceAPI->getSamplingDeviceSerial()));
             return false;
         }
         m_sharedParams.m_dev = m_dev;
     }
     return true;
 }
serialize()
QByteArray HackRFOutput::serialize () const virtual
Implements DeviceSampleSink.
Definition at line 180 of file hackrfoutput.cpp.
References m_settings, and HackRFOutputSettings::serialize().
Referenced by HackRFOutput::MsgReportHackRF::MsgReportHackRF().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void HackRFOutput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSink.
Definition at line 223 of file hackrfoutput.cpp.
References HackRFOutput::MsgConfigureHackRF::create(), HackRFOutputSettings::m_centerFrequency, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     HackRFOutputSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureHackRF* message = MsgConfigureHackRF::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureHackRF* messageToGUI = MsgConfigureHackRF::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setDeviceCenterFrequency()
void HackRFOutput::setDeviceCenterFrequency (quint64 freq_hz, qint32 LOppmTenths) private
Definition at line 309 of file hackrfoutput.cpp.
References m_dev.
Referenced by applySettings().
 {
     if (!m_dev) {
         return;
     }
     qint64 df = ((qint64)freq_hz * LOppmTenths) / 10000000LL;
     hackrf_error rc = (hackrf_error) hackrf_set_freq(m_dev, static_cast<uint64_t>(freq_hz + df));
     if (rc != HACKRF_SUCCESS) {
         qWarning("HackRFOutput::setDeviceCenterFrequency: could not frequency to %llu Hz", freq_hz + df);
     } else {
         qDebug("HackRFOutput::setDeviceCenterFrequency: frequency set to %llu Hz", freq_hz + df);
     }
 }
setMessageQueueToGUI()
virtual void HackRFOutput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSink.
Definition at line 109 of file hackrfoutput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSink::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void HackRFOutput::setSampleRate (int sampleRate) inline virtual
For when the sink sample rate is set externally.
Implements DeviceSampleSink.
Definition at line 112 of file hackrfoutput.h.
References getCenterFrequency(), handleMessage(), setCenterFrequency(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
start()
bool HackRFOutput::start () virtual
Implements DeviceSampleSink.
Definition at line 121 of file hackrfoutput.cpp.
References applySettings(), m_dev, HackRFOutputSettings::m_fcPos, m_hackRFThread, HackRFOutputSettings::m_log2Interp, m_running, DeviceSampleSink::m_sampleSourceFifo, m_settings, HackRFOutputThread::setFcPos(), HackRFOutputThread::setLog2Interpolation(), HackRFOutputThread::startWork(), and stop().
Referenced by HackRFOutput::MsgReportHackRF::MsgReportHackRF().
 {
     if (!m_dev) {
         return false;
     }
     if (m_running) {
         stop();
     }
     m_hackRFThread = new HackRFOutputThread(m_dev, &m_sampleSourceFifo);
 //  mutexLocker.unlock();
     applySettings(m_settings, true);
     m_hackRFThread->setLog2Interpolation(m_settings.m_log2Interp);
     m_hackRFThread->setFcPos((int) m_settings.m_fcPos);
     m_hackRFThread->startWork();
     qDebug("HackRFOutput::start: started");
     m_running = true;
     return true;
 }
stop()
void HackRFOutput::stop () virtual
Implements DeviceSampleSink.
Definition at line 165 of file hackrfoutput.cpp.
References m_hackRFThread, m_running, and HackRFOutputThread::stopWork().
Referenced by HackRFOutput::MsgReportHackRF::MsgReportHackRF(), start(), and ~HackRFOutput().
 {
     qDebug("HackRFOutput::stop");
 //  QMutexLocker mutexLocker(&m_mutex);
     if(m_hackRFThread != 0)
     {
         m_hackRFThread->stopWork();
         delete m_hackRFThread;
         m_hackRFThread = 0;
     }
     m_running = false;
 }
webapiFormatDeviceSettings()
void HackRFOutput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const HackRFOutputSettings & settings) private
Definition at line 621 of file hackrfoutput.cpp.
References SWGSDRangel::SWGDeviceSettings::getHackRfOutputSettings(), SWGSDRangel::SWGHackRFOutputSettings::getReverseApiAddress(), HackRFOutputSettings::m_bandwidth, HackRFOutputSettings::m_biasT, HackRFOutputSettings::m_centerFrequency, HackRFOutputSettings::m_devSampleRate, HackRFOutputSettings::m_fcPos, HackRFOutputSettings::m_lnaExt, HackRFOutputSettings::m_log2Interp, HackRFOutputSettings::m_LOppmTenths, HackRFOutputSettings::m_reverseAPIAddress, HackRFOutputSettings::m_reverseAPIDeviceIndex, HackRFOutputSettings::m_reverseAPIPort, HackRFOutputSettings::m_useReverseAPI, HackRFOutputSettings::m_vgaGain, SWGSDRangel::SWGHackRFOutputSettings::setBandwidth(), SWGSDRangel::SWGHackRFOutputSettings::setBiasT(), SWGSDRangel::SWGHackRFOutputSettings::setCenterFrequency(), SWGSDRangel::SWGHackRFOutputSettings::setDevSampleRate(), SWGSDRangel::SWGHackRFOutputSettings::setFcPos(), SWGSDRangel::SWGHackRFOutputSettings::setLnaExt(), SWGSDRangel::SWGHackRFOutputSettings::setLog2Interp(), SWGSDRangel::SWGHackRFOutputSettings::setLOppmTenths(), SWGSDRangel::SWGHackRFOutputSettings::setReverseApiAddress(), SWGSDRangel::SWGHackRFOutputSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGHackRFOutputSettings::setReverseApiPort(), SWGSDRangel::SWGHackRFOutputSettings::setUseReverseApi(), and SWGSDRangel::SWGHackRFOutputSettings::setVgaGain().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getHackRfOutputSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getHackRfOutputSettings()->setLOppmTenths(settings.m_LOppmTenths);
     response.getHackRfOutputSettings()->setBandwidth(settings.m_bandwidth);
     response.getHackRfOutputSettings()->setVgaGain(settings.m_vgaGain);
     response.getHackRfOutputSettings()->setLog2Interp(settings.m_log2Interp);
     response.getHackRfOutputSettings()->setFcPos(settings.m_fcPos);
     response.getHackRfOutputSettings()->setDevSampleRate(settings.m_devSampleRate);
     response.getHackRfOutputSettings()->setBiasT(settings.m_biasT ? 1 : 0);
     response.getHackRfOutputSettings()->setLnaExt(settings.m_lnaExt ? 1 : 0);
     response.getHackRfOutputSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getHackRfOutputSettings()->getReverseApiAddress()) {
         *response.getHackRfOutputSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getHackRfOutputSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getHackRfOutputSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getHackRfOutputSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReverseSendSettings()
void HackRFOutput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const HackRFOutputSettings & settings, bool force) private
Definition at line 673 of file hackrfoutput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getHackRfOutputSettings(), HackRFOutputSettings::m_bandwidth, HackRFOutputSettings::m_biasT, HackRFOutputSettings::m_centerFrequency, m_deviceAPI, HackRFOutputSettings::m_devSampleRate, HackRFOutputSettings::m_fcPos, HackRFOutputSettings::m_lnaExt, HackRFOutputSettings::m_log2Interp, HackRFOutputSettings::m_LOppmTenths, m_networkManager, m_networkRequest, HackRFOutputSettings::m_reverseAPIAddress, HackRFOutputSettings::m_reverseAPIDeviceIndex, HackRFOutputSettings::m_reverseAPIPort, HackRFOutputSettings::m_vgaGain, SWGSDRangel::SWGHackRFOutputSettings::setBandwidth(), SWGSDRangel::SWGHackRFOutputSettings::setBiasT(), SWGSDRangel::SWGHackRFOutputSettings::setCenterFrequency(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGHackRFOutputSettings::setDevSampleRate(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGHackRFOutputSettings::setFcPos(), SWGSDRangel::SWGDeviceSettings::setHackRfOutputSettings(), SWGSDRangel::SWGHackRFOutputSettings::setLnaExt(), SWGSDRangel::SWGHackRFOutputSettings::setLog2Interp(), SWGSDRangel::SWGHackRFOutputSettings::setLOppmTenths(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), and SWGSDRangel::SWGHackRFOutputSettings::setVgaGain().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(1); // single Tx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("HackRF"));
     swgDeviceSettings->setHackRfOutputSettings(new SWGSDRangel::SWGHackRFOutputSettings());
     SWGSDRangel::SWGHackRFOutputSettings *swgHackRFOutputSettings = swgDeviceSettings->getHackRfOutputSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgHackRFOutputSettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("LOppmTenths") || force) {
         swgHackRFOutputSettings->setLOppmTenths(settings.m_LOppmTenths);
     }
     if (deviceSettingsKeys.contains("bandwidth") || force) {
         swgHackRFOutputSettings->setBandwidth(settings.m_bandwidth);
     }
     if (deviceSettingsKeys.contains("vgaGain") || force) {
         swgHackRFOutputSettings->setVgaGain(settings.m_vgaGain);
     }
     if (deviceSettingsKeys.contains("log2Interp") || force) {
         swgHackRFOutputSettings->setLog2Interp(settings.m_log2Interp);
     }
     if (deviceSettingsKeys.contains("fcPos") || force) {
         swgHackRFOutputSettings->setFcPos((int) settings.m_fcPos);
     }
     if (deviceSettingsKeys.contains("devSampleRate") || force) {
         swgHackRFOutputSettings->setDevSampleRate(settings.m_devSampleRate);
     }
     if (deviceSettingsKeys.contains("biasT") || force) {
         swgHackRFOutputSettings->setBiasT(settings.m_biasT ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("lnaExt") || force) {
         swgHackRFOutputSettings->setLnaExt(settings.m_lnaExt ? 1 : 0);
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void HackRFOutput::webapiReverseSendStartStop (bool start) private
Definition at line 730 of file hackrfoutput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, HackRFOutputSettings::m_reverseAPIAddress, HackRFOutputSettings::m_reverseAPIDeviceIndex, HackRFOutputSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(1); // single Tx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("HackRF"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int HackRFOutput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 654 of file hackrfoutput.cpp.
References HackRFOutput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgStartStop *messagetoGui = MsgStartStop::create(run);
         m_guiMessageQueue->push(messagetoGui);
     }
     return 200;
 }
webapiRunGet()
int HackRFOutput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 645 of file hackrfoutput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int HackRFOutput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 545 of file hackrfoutput.cpp.
References SWGSDRangel::SWGDeviceSettings::getHackRfOutputSettings(), SWGSDRangel::SWGHackRFOutputSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setHackRfOutputSettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setHackRfOutputSettings(new SWGSDRangel::SWGHackRFOutputSettings());
     response.getHackRfOutputSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int HackRFOutput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 556 of file hackrfoutput.cpp.
References HackRFOutput::MsgConfigureHackRF::create(), SWGSDRangel::SWGHackRFOutputSettings::getBandwidth(), SWGSDRangel::SWGHackRFOutputSettings::getBiasT(), SWGSDRangel::SWGHackRFOutputSettings::getCenterFrequency(), SWGSDRangel::SWGHackRFOutputSettings::getDevSampleRate(), SWGSDRangel::SWGHackRFOutputSettings::getFcPos(), SWGSDRangel::SWGDeviceSettings::getHackRfOutputSettings(), SWGSDRangel::SWGHackRFOutputSettings::getLnaExt(), SWGSDRangel::SWGHackRFOutputSettings::getLog2Interp(), SWGSDRangel::SWGHackRFOutputSettings::getLOppmTenths(), SWGSDRangel::SWGHackRFOutputSettings::getReverseApiAddress(), SWGSDRangel::SWGHackRFOutputSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGHackRFOutputSettings::getReverseApiPort(), SWGSDRangel::SWGHackRFOutputSettings::getUseReverseApi(), SWGSDRangel::SWGHackRFOutputSettings::getVgaGain(), HackRFOutputSettings::m_bandwidth, HackRFOutputSettings::m_biasT, HackRFOutputSettings::m_centerFrequency, HackRFOutputSettings::m_devSampleRate, HackRFOutputSettings::m_fcPos, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, HackRFOutputSettings::m_lnaExt, HackRFOutputSettings::m_log2Interp, HackRFOutputSettings::m_LOppmTenths, HackRFOutputSettings::m_reverseAPIAddress, HackRFOutputSettings::m_reverseAPIDeviceIndex, HackRFOutputSettings::m_reverseAPIPort, m_settings, HackRFOutputSettings::m_useReverseAPI, HackRFOutputSettings::m_vgaGain, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     HackRFOutputSettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getHackRfOutputSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("LOppmTenths")) {
         settings.m_LOppmTenths = response.getHackRfOutputSettings()->getLOppmTenths();
     }
     if (deviceSettingsKeys.contains("bandwidth")) {
         settings.m_bandwidth = response.getHackRfOutputSettings()->getBandwidth();
     }
     if (deviceSettingsKeys.contains("vgaGain")) {
         settings.m_vgaGain = response.getHackRfOutputSettings()->getVgaGain();
     }
     if (deviceSettingsKeys.contains("log2Interp")) {
         settings.m_log2Interp = response.getHackRfOutputSettings()->getLog2Interp();
     }
     if (deviceSettingsKeys.contains("fcPos"))
     {
         int fcPos = response.getHackRfOutputSettings()->getFcPos();
         fcPos = fcPos < 0 ? 0 : fcPos > 2 ? 2 : fcPos;
         settings.m_fcPos = (HackRFOutputSettings::fcPos_t) fcPos;
     }
     if (deviceSettingsKeys.contains("devSampleRate")) {
         settings.m_devSampleRate = response.getHackRfOutputSettings()->getDevSampleRate();
     }
     if (deviceSettingsKeys.contains("biasT")) {
         settings.m_biasT = response.getHackRfOutputSettings()->getBiasT() != 0;
     }
     if (deviceSettingsKeys.contains("lnaExt")) {
         settings.m_lnaExt = response.getHackRfOutputSettings()->getLnaExt() != 0;
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getHackRfOutputSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getHackRfOutputSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getHackRfOutputSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getHackRfOutputSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureHackRF *msg = MsgConfigureHackRF::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureHackRF *msgToGUI = MsgConfigureHackRF::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_dev
struct hackrf_device* HackRFOutput::m_dev private
Definition at line 141 of file hackrfoutput.h.
Referenced by applySettings(), closeDevice(), openDevice(), setDeviceCenterFrequency(), and start().
m_deviceAPI
DeviceAPI* HackRFOutput::m_deviceAPI private
Definition at line 138 of file hackrfoutput.h.
Referenced by applySettings(), closeDevice(), handleMessage(), openDevice(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~HackRFOutput().
m_deviceDescription
QString HackRFOutput::m_deviceDescription private
Definition at line 143 of file hackrfoutput.h.
Referenced by getDeviceDescription().
m_hackRFThread
HackRFOutputThread* HackRFOutput::m_hackRFThread private
Definition at line 142 of file hackrfoutput.h.
Referenced by applySettings(), start(), and stop().
m_mutex
QMutex HackRFOutput::m_mutex private
Definition at line 139 of file hackrfoutput.h.
m_networkManager
QNetworkAccessManager* HackRFOutput::m_networkManager private
Definition at line 145 of file hackrfoutput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~HackRFOutput().
m_networkRequest
QNetworkRequest HackRFOutput::m_networkRequest private
Definition at line 146 of file hackrfoutput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool HackRFOutput::m_running private
Definition at line 147 of file hackrfoutput.h.
Referenced by start(), stop(), and ~HackRFOutput().
m_settings
HackRFOutputSettings HackRFOutput::m_settings private
Definition at line 140 of file hackrfoutput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), openDevice(), serialize(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_sharedParams
DeviceHackRFParams HackRFOutput::m_sharedParams private
Definition at line 144 of file hackrfoutput.h.
Referenced by closeDevice(), and openDevice().
The documentation for this class was generated from the following files:
plugins/samplesink/hackrfoutput/hackrfoutput.h
plugins/samplesink/hackrfoutput/hackrfoutput.cpp