SDRAngel: RemoteSourcePlugin Class Reference
RemoteSourcePlugin Class Reference
#include <remotesourceplugin.h>
Public Member Functions
RemoteSourcePlugin (QObject *parent=0)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
Private Attributes
PluginAPI * m_pluginAPI
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Private Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Private Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Detailed Description
Definition at line 27 of file remotesourceplugin.h.
Constructor & Destructor Documentation
RemoteSourcePlugin()
RemoteSourcePlugin::RemoteSourcePlugin (QObject * parent = 0) explicit
Definition at line 36 of file remotesourceplugin.cpp.
                                                       :
     QObject(parent),
     m_pluginAPI(0)
 {
 }
Member Function Documentation
createTxChannelBS()
BasebandSampleSource * RemoteSourcePlugin::createTxChannelBS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 69 of file remotesourceplugin.cpp.
 {
     return new RemoteSource(deviceAPI);
 }
createTxChannelCS()
ChannelAPI * RemoteSourcePlugin::createTxChannelCS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 74 of file remotesourceplugin.cpp.
 {
     return new RemoteSource(deviceAPI);
 }
createTxChannelGUI()
PluginInstanceGUI * RemoteSourcePlugin::createTxChannelGUI (DeviceUISet * deviceUISet, BasebandSampleSource * txChannel) virtual
Reimplemented from PluginInterface.
Definition at line 63 of file remotesourceplugin.cpp.
References RemoteSourceGUI::create(), and m_pluginAPI.
Referenced by initPlugin().
 {
     return RemoteSourceGUI::create(m_pluginAPI, deviceUISet, txChannel);
 }
getPluginDescriptor()
const PluginDescriptor & RemoteSourcePlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 42 of file remotesourceplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void RemoteSourcePlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 47 of file remotesourceplugin.cpp.
References createTxChannelGUI(), RemoteSource::m_channelId, RemoteSource::m_channelIdURI, m_pluginAPI, and PluginAPI::registerTxChannel().
 {
     m_pluginAPI = pluginAPI;
     // register source
     m_pluginAPI->registerTxChannel(RemoteSource::m_channelIdURI, RemoteSource::m_channelId, this);
 }
Member Data Documentation
m_pluginAPI
PluginAPI* RemoteSourcePlugin::m_pluginAPI private
Definition at line 45 of file remotesourceplugin.h.
Referenced by createTxChannelGUI(), and initPlugin().
m_pluginDescriptor
const PluginDescriptor RemoteSourcePlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("Remote channel source"),
    QString("4.5.2"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 43 of file remotesourceplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/channeltx/remotesource/remotesourceplugin.h
plugins/channeltx/remotesource/remotesourceplugin.cpp