SDRAngel: NCO Class Reference
NCO Class Reference
#include <nco.h>
Public Member Functions
NCO ()
void setFreq (Real freq, Real sampleRate)
void setPhase (int phase)
void nextPhase ()
Real next ()
Return next real sample.
Complex nextIQ ()
Return next complex sample.
Complex nextQI ()
Return next complex sample (reversed)
void nextIQMul (Real &i, Real &q)
multiply I,Q separately with next sample
Real get ()
Return current real sample (no phase increment)
Complex getIQ ()
Return current complex sample (no phase increment)
void getIQ (Complex &c)
Sets to the current complex sample (no phase increment)
Complex getQI ()
Return current complex sample (no phase increment, reversed)
void getQI (Complex &c)
Sets to the current complex sample (no phase increment, reversed)
Private Types
enum { TableSize = (1 << 12) }
Static Private Member Functions
static void initTable ()
Private Attributes
int m_phaseIncrement
int m_phase
Static Private Attributes
static Real m_table [TableSize]
static bool m_tableInitialized = false
Detailed Description
Definition at line 25 of file nco.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
TableSize
Definition at line 27 of file nco.h.
          {
         TableSize = (1 << 12),
     };
Constructor & Destructor Documentation
NCO()
NCO::NCO ()
Definition at line 42 of file nco.cpp.
References initTable(), m_phase, and m_phaseIncrement.
 {
     initTable();
     m_phase = 0;
     m_phaseIncrement = 0;
 }
Member Function Documentation
get()
float NCO::get ()
Return current real sample (no phase increment)
Definition at line 84 of file nco.cpp.
References m_phase, and m_table.
 {
     return m_table[m_phase];
 }
getIQ() [1/2]
Complex NCO::getIQ ()
Return current complex sample (no phase increment)
Definition at line 89 of file nco.cpp.
References m_phase, m_table, and TableSize.
 {
     return Complex(m_table[m_phase], -m_table[(m_phase + TableSize / 4) % TableSize]);
 }
getIQ() [2/2]
void NCO::getIQ (Complex & c)
Sets to the current complex sample (no phase increment)
Definition at line 94 of file nco.cpp.
References m_phase, m_table, and TableSize.
 {
     c.real(m_table[m_phase]);
     c.imag(-m_table[(m_phase + TableSize / 4) % TableSize]);
 }
getQI() [1/2]
Complex NCO::getQI ()
Return current complex sample (no phase increment, reversed)
Definition at line 100 of file nco.cpp.
References m_phase, m_table, and TableSize.
 {
     return Complex(-m_table[(m_phase + TableSize / 4) % TableSize], m_table[m_phase]);
 }
getQI() [2/2]
void NCO::getQI (Complex & c)
Sets to the current complex sample (no phase increment, reversed)
Definition at line 105 of file nco.cpp.
References m_phase, m_table, and TableSize.
 {
     c.imag(m_table[m_phase]);
     c.real(-m_table[(m_phase + TableSize / 4) % TableSize]);
 }
initTable()
void NCO::initTable () static private
Definition at line 31 of file nco.cpp.
References cos(), i, M_PI, m_table, m_tableInitialized, and TableSize.
Referenced by NCO().
 {
     if(m_tableInitialized)
         return;
     for(int i = 0; i < TableSize; i++)
         m_table[i] = cos((2.0 * M_PI * i) / TableSize);
     m_tableInitialized = true;
 }
next()
float NCO::next ()
Return next real sample.
Definition at line 55 of file nco.cpp.
References m_phase, m_table, and nextPhase().
 {
     nextPhase();
     return m_table[m_phase];
 }
nextIQ()
Complex NCO::nextIQ ()
Return next complex sample.
Definition at line 61 of file nco.cpp.
References m_phase, m_table, nextPhase(), and TableSize.
Referenced by LoRaDemod::feed(), WFMDemod::feed(), AMDemod::feed(), DSDDemod::feed(), UDPSink::feed(), NFMDemod::feed(), BFMDemod::feed(), DATVDemod::feed(), ATVDemod::feed(), UDPSource::pull(), AMMod::pull(), WFMMod::pull(), NFMMod::pull(), and ATVMod::pullFinalize().
 {
     nextPhase();
     return Complex(m_table[m_phase], -m_table[(m_phase + TableSize / 4) % TableSize]);
 }
nextIQMul()
void NCO::nextIQMul (Real & i, Real & q)
multiply I,Q separately with next sample
Definition at line 73 of file nco.cpp.
References i, m_phase, m_table, nextPhase(), and TableSize.
 {
     nextPhase();
     Real x = i;
     Real y = q;
     const Real& u = m_table[m_phase];
     const Real& v = -m_table[(m_phase + TableSize / 4) % TableSize];
     i = x*u - y*v;
     q = x*v + y*u;
 }
nextPhase()
void NCO::nextPhase () inline
Definition at line 44 of file nco.h.
References i.
Referenced by next(), nextIQ(), nextIQMul(), and nextQI().
     {
         m_phase += m_phaseIncrement;
         while(m_phase >= TableSize)
             m_phase -= TableSize;
         while(m_phase < 0)
             m_phase += TableSize;
     }
nextQI()
Complex NCO::nextQI ()
Return next complex sample (reversed)
Definition at line 67 of file nco.cpp.
References m_phase, m_table, nextPhase(), and TableSize.
 {
     nextPhase();
     return Complex(-m_table[(m_phase + TableSize / 4) % TableSize], m_table[m_phase]);
 }
setFreq()
void NCO::setFreq (Real freq, Real sampleRate)
Definition at line 49 of file nco.cpp.
References m_phaseIncrement, and TableSize.
Referenced by WFMDemod::applyChannelSettings(), AMDemod::applyChannelSettings(), UDPSink::applyChannelSettings(), UDPSource::applyChannelSettings(), NFMDemod::applyChannelSettings(), DSDDemod::applyChannelSettings(), BFMDemod::applyChannelSettings(), WFMMod::applyChannelSettings(), AMMod::applyChannelSettings(), NFMMod::applyChannelSettings(), DATVDemod::applyChannelSettings(), ATVMod::applyChannelSettings(), DATVDemod::applySettings(), ATVDemod::applySettings(), LoRaDemod::handleMessage(), LoRaDemod::LoRaDemod(), and UDPSink::UDPSink().
 {
     m_phaseIncrement = (freq * TableSize) / sampleRate;
     qDebug("NCO freq: %f phase inc %d", freq, m_phaseIncrement);
 }
setPhase()
void NCO::setPhase (int phase) inline
Definition at line 42 of file nco.h.
 { m_phase = phase; }
Member Data Documentation
m_phase
int NCO::m_phase private
Definition at line 36 of file nco.h.
Referenced by get(), getIQ(), getQI(), NCO(), next(), nextIQ(), nextIQMul(), and nextQI().
m_phaseIncrement
int NCO::m_phaseIncrement private
Definition at line 35 of file nco.h.
Referenced by NCO(), and setFreq().
m_table
Real NCO::m_table static private
Definition at line 30 of file nco.h.
Referenced by get(), getIQ(), getQI(), initTable(), next(), nextIQ(), nextIQMul(), and nextQI().
m_tableInitialized
bool NCO::m_tableInitialized = false static private
Definition at line 31 of file nco.h.
Referenced by initTable().
The documentation for this class was generated from the following files:
sdrbase/dsp/nco.h
sdrbase/dsp/nco.cpp