SDRAngel: FileInputThread::MsgReportEOF Class Reference
FileInputThread::MsgReportEOF Class Reference
#include <fileinputthread.h>
Static Public Member Functions
static MsgReportEOF * create ()
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportEOF ()
Additional Inherited Members
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 42 of file fileinputthread.h.
Constructor & Destructor Documentation
MsgReportEOF()
FileInputThread::MsgReportEOF::MsgReportEOF () inline private
Definition at line 51 of file fileinputthread.h.
References FileInputThread::FileInputThread(), FileInputThread::setBuffers(), FileInputThread::setSampleRateAndSize(), FileInputThread::startWork(), FileInputThread::stopWork(), and FileInputThread::~FileInputThread().
Referenced by create().
                        :
             Message()
         { }
Member Function Documentation
create()
static MsgReportEOF* FileInputThread::MsgReportEOF::create () inline static
Definition at line 46 of file fileinputthread.h.
References MsgReportEOF().
Referenced by FileInputThread::tick().
{
             return new MsgReportEOF();
         }
The documentation for this class was generated from the following file:
plugins/samplesource/fileinput/fileinputthread.h