SDRAngel: XTRXOutputGUI Class Reference
XTRXOutputGUI Class Reference
#include <xtrxoutputgui.h>
Public Member Functions
XTRXOutputGUI (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~XTRXOutputGUI ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_startStop_toggled (bool checked)
void on_centerFrequency_changed (quint64 value)
void on_ncoFrequency_changed (qint64 value)
void on_ncoEnable_toggled (bool checked)
void on_sampleRate_changed (quint64 value)
void on_hwInterp_currentIndexChanged (int index)
void on_swInterp_currentIndexChanged (int index)
void on_lpf_changed (quint64 value)
void on_gain_valueChanged (int value)
void on_antenna_currentIndexChanged (int index)
void on_extClock_clicked ()
void on_pwrmode_currentIndexChanged (int index)
void on_sampleRateMode_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void displaySettings ()
void displaySampleRate ()
void setNCODisplay ()
void setCenterFrequencyDisplay ()
void setCenterFrequencySetting (uint64_t kHzValue)
void sendSettings ()
void updateSampleRateAndFrequency ()
void updateDACRate ()
void blockApplySettings (bool block)
Private Attributes
Ui::XTRXOutputGUI * ui
DeviceUISet * m_deviceUISet
XTRXOutput * m_XTRXOutput
Same object as above but gives easy access to XTRXInput methods and attributes that are used intensively.
XTRXOutputSettings m_settings
bool m_sampleRateMode
true: device, false: base band sample rate update mode
QTimer m_updateTimer
QTimer m_statusTimer
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
bool m_doApplySettings
bool m_forceSettings
int m_statusCounter
int m_deviceStatusCounter
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 35 of file xtrxoutputgui.h.
Constructor & Destructor Documentation
XTRXOutputGUI()
XTRXOutputGUI::XTRXOutputGUI (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 34 of file xtrxoutputgui.cpp.
References arg(), displaySettings(), XTRXOutput::getChannelIndex(), XTRXOutput::getLORange(), XTRXOutput::getLPRange(), DeviceAPI::getSampleSink(), XTRXOutput::getSRRange(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, ColorMapper::GrayYellow, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_statusTimer, m_updateTimer, m_XTRXOutput, openDeviceSettingsDialog(), ui, updateHardware(), and updateStatus().
                                                                       :
     QWidget(parent),
     ui(new Ui::XTRXOutputGUI),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_sampleRateMode(true),
     m_sampleRate(0),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_statusCounter(0),
     m_deviceStatusCounter(0)
 {
     m_XTRXOutput = (XTRXOutput*) m_deviceUISet->m_deviceAPI->getSampleSink();
     ui->setupUi(this);
     float minF, maxF, stepF;
     m_XTRXOutput->getLORange(minF, maxF, stepF);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, ((uint32_t) minF)/1000, ((uint32_t) maxF)/1000); // frequency dial is in kHz
     m_XTRXOutput->getSRRange(minF, maxF, stepF);
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(8, (uint32_t) minF, (uint32_t) maxF);
     m_XTRXOutput->getLPRange(minF, maxF, stepF);
     ui->lpf->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     ui->lpf->setValueRange(6, (minF/1000)+1, maxF/1000);
     ui->ncoFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->channelNumberText->setText(tr("#%1").arg(m_XTRXOutput->getChannelIndex()));
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
 }
~XTRXOutputGUI()
XTRXOutputGUI::~XTRXOutputGUI () virtual
Definition at line 81 of file xtrxoutputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void XTRXOutputGUI::blockApplySettings (bool block) private
Definition at line 455 of file xtrxoutputgui.cpp.
References m_doApplySettings.
Referenced by handleMessage().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool XTRXOutputGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 125 of file xtrxoutputgui.cpp.
References XTRXOutputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if (m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void XTRXOutputGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 86 of file xtrxoutputgui.cpp.
 {
     delete this;
 }
displaySampleRate()
void XTRXOutputGUI::displaySampleRate () private
Definition at line 283 of file xtrxoutputgui.cpp.
References arg(), XTRXOutput::getSRRange(), XTRXOutputSettings::m_devSampleRate, XTRXOutputSettings::m_log2SoftInterp, m_sampleRateMode, m_settings, m_XTRXOutput, and ui.
Referenced by displaySettings(), on_sampleRateMode_toggled(), on_swInterp_currentIndexChanged(), and updateSampleRateAndFrequency().
 {
     float minF, maxF, stepF;
     m_XTRXOutput->getSRRange(minF, maxF, stepF);
     ui->sampleRate->blockSignals(true);
     if (m_sampleRateMode)
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(60,60,60); }");
         ui->sampleRateMode->setText("SR");
         ui->sampleRate->setValueRange(8, (uint32_t) minF, (uint32_t) maxF);
         ui->sampleRate->setValue(m_settings.m_devSampleRate);
         ui->sampleRate->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setToolTip("Baseband sample rate (S/s)");
         uint32_t basebandSampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2SoftInterp);
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(basebandSampleRate / 1000.0f, 'g', 5)));
     }
     else
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(50,50,50); }");
         ui->sampleRateMode->setText("BB");
         ui->sampleRate->setValueRange(8, (uint32_t) minF/(1<<m_settings.m_log2SoftInterp), (uint32_t) maxF/(1<<m_settings.m_log2SoftInterp));
         ui->sampleRate->setValue(m_settings.m_devSampleRate/(1<<m_settings.m_log2SoftInterp));
         ui->sampleRate->setToolTip("Baseband sample rate (S/s)");
         ui->deviceRateText->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_settings.m_devSampleRate / 1000.0f, 'g', 5)));
     }
     ui->sampleRate->blockSignals(false);
 }
displaySettings()
void XTRXOutputGUI::displaySettings () private
Definition at line 315 of file xtrxoutputgui.cpp.
References arg(), displaySampleRate(), XTRXOutputSettings::m_antennaPath, XTRXOutputSettings::m_extClock, XTRXOutputSettings::m_extClockFreq, XTRXOutputSettings::m_gain, XTRXOutputSettings::m_log2HardInterp, XTRXOutputSettings::m_log2SoftInterp, XTRXOutputSettings::m_lpfBW, XTRXOutputSettings::m_ncoEnable, XTRXOutputSettings::m_pwrmode, m_settings, setCenterFrequencyDisplay(), setNCODisplay(), ui, and updateDACRate().
Referenced by deserialize(), handleInputMessages(), handleMessage(), resetToDefaults(), setCenterFrequency(), and XTRXOutputGUI().
 {
     ui->extClock->setExternalClockFrequency(m_settings.m_extClockFreq);
     ui->extClock->setExternalClockActive(m_settings.m_extClock);
     setCenterFrequencyDisplay();
     displaySampleRate();
     ui->hwInterp->setCurrentIndex(m_settings.m_log2HardInterp);
     ui->swInterp->setCurrentIndex(m_settings.m_log2SoftInterp);
     updateDACRate();
     ui->lpf->setValue(m_settings.m_lpfBW / 1000);
     ui->pwrmode->setCurrentIndex(m_settings.m_pwrmode);
     ui->gain->setValue(m_settings.m_gain);
     ui->gainText->setText(tr("%1").arg(m_settings.m_gain));
     ui->antenna->setCurrentIndex((int) m_settings.m_antennaPath - (int) XTRX_TX_H);
     setNCODisplay();
     ui->ncoEnable->setChecked(m_settings.m_ncoEnable);
 }
getCenterFrequency()
qint64 XTRXOutputGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 108 of file xtrxoutputgui.cpp.
References XTRXOutputSettings::m_centerFrequency, XTRXOutputSettings::m_ncoEnable, XTRXOutputSettings::m_ncoFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency + (m_settings.m_ncoEnable ? m_settings.m_ncoFrequency : 0);
 }
getInputMessageQueue()
virtual MessageQueue* XTRXOutputGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 51 of file xtrxoutputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString XTRXOutputGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 96 of file xtrxoutputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void XTRXOutputGUI::handleInputMessages () private slot
Definition at line 231 of file xtrxoutputgui.cpp.
References displaySettings(), DSPSignalNotification::getCenterFrequency(), DSPSignalNotification::getSampleRate(), XTRXOutput::MsgConfigureXTRX::getSettings(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, m_settings, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by XTRXOutputGUI().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("XTRXOutputGUI::handleInputMessages: DSPSignalNotification: SampleRate: %d, CenterFrequency: %llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else if (XTRXOutput::MsgConfigureXTRX::match(*message))
         {
             qDebug("XTRXOutputGUI::handleInputMessages: MsgConfigureXTRX");
             const XTRXOutput::MsgConfigureXTRX& cfg = (XTRXOutput::MsgConfigureXTRX&) *message;
             m_settings = cfg.getSettings();
             displaySettings();
             delete message;
         }
         else
         {
             if (handleMessage(*message)) {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool XTRXOutputGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 141 of file xtrxoutputgui.cpp.
References arg(), blockApplySettings(), displaySettings(), XTRXOutput::MsgReportStreamInfo::getActive(), DeviceXTRXShared::MsgReportBuddyChange::getCenterFrequency(), DeviceXTRXShared::MsgReportBuddyChange::getDevSampleRate(), XTRXOutput::getDevSampleRate(), DeviceXTRXShared::MsgReportClockSourceChange::getExtClock(), DeviceXTRXShared::MsgReportClockSourceChange::getExtClockFeq(), XTRXOutput::MsgReportStreamInfo::getFifoFilledCount(), XTRXOutput::MsgReportStreamInfo::getFifoSize(), DeviceXTRXShared::MsgReportDeviceInfo::getGPSLocked(), DeviceXTRXShared::MsgReportBuddyChange::getLog2HardDecimInterp(), DeviceXTRXShared::MsgReportBuddyChange::getRxElseTx(), XTRXOutput::MsgStartStop::getStartStop(), XTRXOutput::MsgReportStreamInfo::getSuccess(), DeviceXTRXShared::MsgReportDeviceInfo::getTemperature(), XTRXOutputSettings::m_centerFrequency, XTRXOutputSettings::m_devSampleRate, XTRXOutputSettings::m_extClock, XTRXOutputSettings::m_extClockFreq, XTRXOutputSettings::m_log2HardInterp, m_settings, m_XTRXOutput, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (DeviceXTRXShared::MsgReportBuddyChange::match(message))
     {
         DeviceXTRXShared::MsgReportBuddyChange& report = (DeviceXTRXShared::MsgReportBuddyChange&) message;
         m_settings.m_devSampleRate = report.getDevSampleRate();
         m_settings.m_log2HardInterp = report.getLog2HardDecimInterp();
         if (!report.getRxElseTx()) {
             m_settings.m_centerFrequency = report.getCenterFrequency();
         }
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (DeviceXTRXShared::MsgReportClockSourceChange::match(message))
     {
         DeviceXTRXShared::MsgReportClockSourceChange& report = (DeviceXTRXShared::MsgReportClockSourceChange&) message;
         m_settings.m_extClockFreq = report.getExtClockFeq();
         m_settings.m_extClock = report.getExtClock();
         blockApplySettings(true);
         ui->extClock->setExternalClockFrequency(m_settings.m_extClockFreq);
         ui->extClock->setExternalClockActive(m_settings.m_extClock);
         blockApplySettings(false);
         return true;
     }
     else if (XTRXOutput::MsgReportClockGenChange::match(message))
     {
         m_settings.m_devSampleRate = m_XTRXOutput->getDevSampleRate();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (XTRXOutput::MsgReportStreamInfo::match(message))
     {
         XTRXOutput::MsgReportStreamInfo& report = (XTRXOutput::MsgReportStreamInfo&) message;
         if (report.getSuccess())
         {
             if (report.getActive()) {
                 ui->streamStatusLabel->setStyleSheet("QLabel { background-color : green; }");
             } else {
                 ui->streamStatusLabel->setStyleSheet("QLabel { background-color : blue; }");
             }
             ui->fifoBar->setMaximum(report.getFifoSize());
             ui->fifoBar->setValue(report.getFifoFilledCount());
             ui->fifoBar->setToolTip(tr("FIFO fill %1/%2 samples").arg(QString::number(report.getFifoFilledCount())).arg(QString::number(report.getFifoSize())));
         }
         else
         {
             ui->streamStatusLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
         }
         return true;
     }
     else if (DeviceXTRXShared::MsgReportDeviceInfo::match(message))
     {
         DeviceXTRXShared::MsgReportDeviceInfo& report = (DeviceXTRXShared::MsgReportDeviceInfo&) message;
         ui->temperatureText->setText(tr("%1C").arg(QString::number(report.getTemperature(), 'f', 0)));
         if (report.getGPSLocked()) {
             ui->gpsStatusLabel->setStyleSheet("QLabel { background-color : green; }");
         } else {
             ui->gpsStatusLabel->setStyleSheet("QLabel { background:rgb(48,48,48); }");
         }
         return true;
     }
     else if (XTRXOutput::MsgStartStop::match(message))
     {
         XTRXOutput::MsgStartStop& notif = (XTRXOutput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     return false;
 }
on_antenna_currentIndexChanged
void XTRXOutputGUI::on_antenna_currentIndexChanged (int index) private slot
Definition at line 545 of file xtrxoutputgui.cpp.
References XTRXOutputSettings::m_antennaPath, m_settings, and sendSettings().
 {
     m_settings.m_antennaPath = (xtrx_antenna_t) (index + (int) XTRX_TX_H);
     sendSettings();
 }
on_centerFrequency_changed
void XTRXOutputGUI::on_centerFrequency_changed (quint64 value) private slot
Definition at line 469 of file xtrxoutputgui.cpp.
References sendSettings(), and setCenterFrequencySetting().
 {
     setCenterFrequencySetting(value);
     sendSettings();
 }
on_extClock_clicked
void XTRXOutputGUI::on_extClock_clicked () private slot
Definition at line 551 of file xtrxoutputgui.cpp.
References XTRXOutputSettings::m_extClock, XTRXOutputSettings::m_extClockFreq, m_settings, sendSettings(), and ui.
 {
     m_settings.m_extClock = ui->extClock->getExternalClockActive();
     m_settings.m_extClockFreq = ui->extClock->getExternalClockFrequency();
     qDebug("XTRXOutputGUI::on_extClock_clicked: %u Hz %s", m_settings.m_extClockFreq, m_settings.m_extClock ? "on" : "off");
     sendSettings();
 }
on_gain_valueChanged
void XTRXOutputGUI::on_gain_valueChanged (int value) private slot
Definition at line 538 of file xtrxoutputgui.cpp.
References arg(), XTRXOutputSettings::m_gain, m_settings, sendSettings(), and ui.
 {
     m_settings.m_gain = value;
     ui->gainText->setText(tr("%1").arg(m_settings.m_gain));
     sendSettings();
 }
on_hwInterp_currentIndexChanged
void XTRXOutputGUI::on_hwInterp_currentIndexChanged (int index) private slot
Definition at line 501 of file xtrxoutputgui.cpp.
References XTRXOutputSettings::m_log2HardInterp, m_settings, sendSettings(), setNCODisplay(), and updateDACRate().
 {
     if ((index <0) || (index > 5)) {
         return;
     }
     m_settings.m_log2HardInterp = index;
     updateDACRate();
     setNCODisplay();
     sendSettings();
 }
on_lpf_changed
void XTRXOutputGUI::on_lpf_changed (quint64 value) private slot
Definition at line 532 of file xtrxoutputgui.cpp.
References XTRXOutputSettings::m_lpfBW, m_settings, and sendSettings().
 {
     m_settings.m_lpfBW = value * 1000;
     sendSettings();
 }
on_ncoEnable_toggled
void XTRXOutputGUI::on_ncoEnable_toggled (bool checked) private slot
Definition at line 482 of file xtrxoutputgui.cpp.
References XTRXOutputSettings::m_ncoEnable, m_settings, sendSettings(), and setCenterFrequencyDisplay().
 {
     m_settings.m_ncoEnable = checked;
     setCenterFrequencyDisplay();
     sendSettings();
 }
on_ncoFrequency_changed
void XTRXOutputGUI::on_ncoFrequency_changed (qint64 value) private slot
Definition at line 475 of file xtrxoutputgui.cpp.
References XTRXOutputSettings::m_ncoFrequency, m_settings, sendSettings(), and setCenterFrequencyDisplay().
 {
     m_settings.m_ncoFrequency = value;
     setCenterFrequencyDisplay();
     sendSettings();
 }
on_pwrmode_currentIndexChanged
void XTRXOutputGUI::on_pwrmode_currentIndexChanged (int index) private slot
Definition at line 559 of file xtrxoutputgui.cpp.
References XTRXOutputSettings::m_pwrmode, m_settings, and sendSettings().
 {
     m_settings.m_pwrmode = index;
     sendSettings();
 }
on_sampleRate_changed
void XTRXOutputGUI::on_sampleRate_changed (quint64 value) private slot
Definition at line 489 of file xtrxoutputgui.cpp.
References XTRXOutputSettings::m_devSampleRate, XTRXOutputSettings::m_log2SoftInterp, m_sampleRateMode, m_settings, sendSettings(), setNCODisplay(), and updateDACRate().
 {
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = value;
     } else {
         m_settings.m_devSampleRate = value * (1 << m_settings.m_log2SoftInterp);
     }
     updateDACRate();
     setNCODisplay();
     sendSettings();}
on_sampleRateMode_toggled
void XTRXOutputGUI::on_sampleRateMode_toggled (bool checked) private slot
Definition at line 565 of file xtrxoutputgui.cpp.
References displaySampleRate(), and m_sampleRateMode.
 {
     m_sampleRateMode = checked;
     displaySampleRate();
 }
on_startStop_toggled
void XTRXOutputGUI::on_startStop_toggled (bool checked) private slot
Definition at line 460 of file xtrxoutputgui.cpp.
References XTRXOutput::MsgStartStop::create(), DeviceSampleSink::getInputMessageQueue(), m_doApplySettings, m_XTRXOutput, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         XTRXOutput::MsgStartStop *message = XTRXOutput::MsgStartStop::create(checked);
         m_XTRXOutput->getInputMessageQueue()->push(message);
     }
 }
on_swInterp_currentIndexChanged
void XTRXOutputGUI::on_swInterp_currentIndexChanged (int index) private slot
Definition at line 514 of file xtrxoutputgui.cpp.
References displaySampleRate(), XTRXOutputSettings::m_devSampleRate, XTRXOutputSettings::m_log2SoftInterp, m_sampleRateMode, m_settings, sendSettings(), and ui.
 {
     if ((index <0) || (index > 6)) {
         return;
     }
     m_settings.m_log2SoftInterp = index;
     displaySampleRate();
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     } else {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew() * (1 << m_settings.m_log2SoftInterp);
     }
     sendSettings();
 }
openDeviceSettingsDialog
void XTRXOutputGUI::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 571 of file xtrxoutputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), XTRXOutputSettings::m_reverseAPIAddress, XTRXOutputSettings::m_reverseAPIDeviceIndex, XTRXOutputSettings::m_reverseAPIPort, m_settings, XTRXOutputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by XTRXOutputGUI().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void XTRXOutputGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 101 of file xtrxoutputgui.cpp.
References displaySettings(), m_settings, XTRXOutputSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void XTRXOutputGUI::sendSettings () private
Definition at line 382 of file xtrxoutputgui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_antenna_currentIndexChanged(), on_centerFrequency_changed(), on_extClock_clicked(), on_gain_valueChanged(), on_hwInterp_currentIndexChanged(), on_lpf_changed(), on_ncoEnable_toggled(), on_ncoFrequency_changed(), on_pwrmode_currentIndexChanged(), on_sampleRate_changed(), on_swInterp_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray XTRXOutputGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 120 of file xtrxoutputgui.cpp.
References m_settings, and XTRXOutputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void XTRXOutputGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 113 of file xtrxoutputgui.cpp.
References displaySettings(), XTRXOutputSettings::m_centerFrequency, XTRXOutputSettings::m_ncoEnable, XTRXOutputSettings::m_ncoFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency - (m_settings.m_ncoEnable ? m_settings.m_ncoFrequency : 0);
     displaySettings();
     sendSettings();
 }
setCenterFrequencyDisplay()
void XTRXOutputGUI::setCenterFrequencyDisplay () private
Definition at line 356 of file xtrxoutputgui.cpp.
References arg(), XTRXOutputSettings::m_centerFrequency, XTRXOutputSettings::m_ncoEnable, XTRXOutputSettings::m_ncoFrequency, m_settings, and ui.
Referenced by displaySettings(), on_ncoEnable_toggled(), and on_ncoFrequency_changed().
 {
     int64_t centerFrequency = m_settings.m_centerFrequency;
     ui->centerFrequency->setToolTip(QString("Main center frequency in kHz (LO: %1 kHz)").arg(centerFrequency/1000));
     if (m_settings.m_ncoEnable) {
         centerFrequency += m_settings.m_ncoFrequency;
     }
     ui->centerFrequency->blockSignals(true);
     ui->centerFrequency->setValue(centerFrequency < 0 ? 0 : (uint64_t) centerFrequency/1000); // kHz
     ui->centerFrequency->blockSignals(false);
 }
setCenterFrequencySetting()
void XTRXOutputGUI::setCenterFrequencySetting (uint64_t kHzValue) private
Definition at line 370 of file xtrxoutputgui.cpp.
References arg(), XTRXOutputSettings::m_centerFrequency, XTRXOutputSettings::m_ncoEnable, XTRXOutputSettings::m_ncoFrequency, m_settings, and ui.
Referenced by on_centerFrequency_changed().
 {
     int64_t centerFrequency = kHzValue*1000;
     if (m_settings.m_ncoEnable) {
         centerFrequency -= m_settings.m_ncoFrequency;
     }
     m_settings.m_centerFrequency = centerFrequency < 0 ? 0 : (uint64_t) centerFrequency;
     ui->centerFrequency->setToolTip(QString("Main center frequency in kHz (LO: %1 kHz)").arg(centerFrequency/1000));
 }
setName()
void XTRXOutputGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 91 of file xtrxoutputgui.cpp.
 {
     setObjectName(name);
 }
setNCODisplay()
void XTRXOutputGUI::setNCODisplay () private
Definition at line 341 of file xtrxoutputgui.cpp.
References arg(), XTRXOutputSettings::m_devSampleRate, XTRXOutputSettings::m_log2HardInterp, XTRXOutputSettings::m_ncoFrequency, m_settings, and ui.
Referenced by displaySettings(), on_hwInterp_currentIndexChanged(), and on_sampleRate_changed().
 {
     int ncoHalfRange = (m_settings.m_devSampleRate * (1<<(m_settings.m_log2HardInterp)))/2;
     ui->ncoFrequency->setValueRange(
             false,
             8,
             -ncoHalfRange,
             ncoHalfRange);
     ui->ncoFrequency->blockSignals(true);
     ui->ncoFrequency->setToolTip(QString("NCO frequency shift in Hz (Range: +/- %1 kHz)").arg(ncoHalfRange/1000));
     ui->ncoFrequency->setValue(m_settings.m_ncoFrequency);
     ui->ncoFrequency->blockSignals(false);
 }
updateDACRate()
void XTRXOutputGUI::updateDACRate () private
Definition at line 265 of file xtrxoutputgui.cpp.
References arg(), XTRXOutput::getClockGen(), m_XTRXOutput, and ui.
Referenced by displaySettings(), on_hwInterp_currentIndexChanged(), and on_sampleRate_changed().
 {
     uint32_t dacRate = m_XTRXOutput->getClockGen() / 4;
     if (dacRate < 100000000) {
         ui->dacRateLabel->setText(tr("%1k").arg(QString::number(dacRate / 1000.0f, 'g', 5)));
     } else {
         ui->dacRateLabel->setText(tr("%1M").arg(QString::number(dacRate / 1000000.0f, 'g', 5)));
     }
 }
updateHardware
void XTRXOutputGUI::updateHardware () private slot
Definition at line 388 of file xtrxoutputgui.cpp.
References XTRXOutput::MsgConfigureXTRX::create(), DeviceSampleSink::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_settings, m_updateTimer, m_XTRXOutput, and MessageQueue::push().
Referenced by XTRXOutputGUI().
 {
     if (m_doApplySettings)
     {
         qDebug() << "XTRXOutputGUI::updateHardware";
         XTRXOutput::MsgConfigureXTRX* message = XTRXOutput::MsgConfigureXTRX::create(m_settings, m_forceSettings);
         m_XTRXOutput->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void XTRXOutputGUI::updateSampleRateAndFrequency () private
Definition at line 276 of file xtrxoutputgui.cpp.
References displaySampleRate(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), and GLSpectrum::setSampleRate().
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     displaySampleRate();
 }
updateStatus
void XTRXOutputGUI::updateStatus () private slot
Definition at line 400 of file xtrxoutputgui.cpp.
References XTRXOutput::MsgGetStreamInfo::create(), XTRXOutput::MsgGetDeviceInfo::create(), DeviceAPI::errorMessage(), DeviceSampleSink::getInputMessageQueue(), DeviceAPI::isBuddyLeader(), DeviceUISet::m_deviceAPI, m_deviceStatusCounter, m_deviceUISet, m_lastEngineState, m_statusCounter, m_XTRXOutput, MessageQueue::push(), DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by XTRXOutputGUI().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
         case DeviceAPI::StNotStarted:
             ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
             break;
         case DeviceAPI::StIdle:
             ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
             break;
         case DeviceAPI::StRunning:
             ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
             break;
         case DeviceAPI::StError:
             ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
             QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
             break;
         default:
             break;
         }
         m_lastEngineState = state;
     }
     if (m_statusCounter < 1)
     {
         m_statusCounter++;
     }
     else
     {
         XTRXOutput::MsgGetStreamInfo* message = XTRXOutput::MsgGetStreamInfo::create();
         m_XTRXOutput->getInputMessageQueue()->push(message);
         m_statusCounter = 0;
     }
     if (m_deviceStatusCounter < 10)
     {
         m_deviceStatusCounter++;
     }
     else
     {
         if (m_deviceUISet->m_deviceAPI->isBuddyLeader())
         {
             XTRXOutput::MsgGetDeviceInfo* message = XTRXOutput::MsgGetDeviceInfo::create();
             m_XTRXOutput->getInputMessageQueue()->push(message);
         }
         m_deviceStatusCounter = 0;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 XTRXOutputGUI::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 64 of file xtrxoutputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceStatusCounter
int XTRXOutputGUI::m_deviceStatusCounter private
Definition at line 69 of file xtrxoutputgui.h.
Referenced by updateStatus().
m_deviceUISet
DeviceUISet* XTRXOutputGUI::m_deviceUISet private
Definition at line 57 of file xtrxoutputgui.h.
Referenced by updateSampleRateAndFrequency(), updateStatus(), and XTRXOutputGUI().
m_doApplySettings
bool XTRXOutputGUI::m_doApplySettings private
Definition at line 66 of file xtrxoutputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_forceSettings
bool XTRXOutputGUI::m_forceSettings private
Definition at line 67 of file xtrxoutputgui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue XTRXOutputGUI::m_inputMessageQueue private
Definition at line 70 of file xtrxoutputgui.h.
Referenced by handleInputMessages(), and XTRXOutputGUI().
m_lastEngineState
int XTRXOutputGUI::m_lastEngineState private
Definition at line 65 of file xtrxoutputgui.h.
Referenced by updateStatus().
m_sampleRate
int XTRXOutputGUI::m_sampleRate private
Definition at line 63 of file xtrxoutputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateMode
bool XTRXOutputGUI::m_sampleRateMode private
true: device, false: base band sample rate update mode
Definition at line 60 of file xtrxoutputgui.h.
Referenced by displaySampleRate(), on_sampleRate_changed(), on_sampleRateMode_toggled(), and on_swInterp_currentIndexChanged().
m_settings
XTRXOutputSettings XTRXOutputGUI::m_settings private
Definition at line 59 of file xtrxoutputgui.h.
Referenced by deserialize(), displaySampleRate(), displaySettings(), getCenterFrequency(), handleInputMessages(), handleMessage(), on_antenna_currentIndexChanged(), on_extClock_clicked(), on_gain_valueChanged(), on_hwInterp_currentIndexChanged(), on_lpf_changed(), on_ncoEnable_toggled(), on_ncoFrequency_changed(), on_pwrmode_currentIndexChanged(), on_sampleRate_changed(), on_swInterp_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), setCenterFrequencyDisplay(), setCenterFrequencySetting(), setNCODisplay(), and updateHardware().
m_statusCounter
int XTRXOutputGUI::m_statusCounter private
Definition at line 68 of file xtrxoutputgui.h.
Referenced by updateStatus().
m_statusTimer
QTimer XTRXOutputGUI::m_statusTimer private
Definition at line 62 of file xtrxoutputgui.h.
Referenced by XTRXOutputGUI().
m_updateTimer
QTimer XTRXOutputGUI::m_updateTimer private
Definition at line 61 of file xtrxoutputgui.h.
Referenced by sendSettings(), updateHardware(), and XTRXOutputGUI().
m_XTRXOutput
XTRXOutput* XTRXOutputGUI::m_XTRXOutput private
Same object as above but gives easy access to XTRXInput methods and attributes that are used intensively.
Definition at line 58 of file xtrxoutputgui.h.
Referenced by displaySampleRate(), handleMessage(), on_startStop_toggled(), updateDACRate(), updateHardware(), updateStatus(), and XTRXOutputGUI().
ui
Ui::XTRXOutputGUI* XTRXOutputGUI::ui private
Definition at line 55 of file xtrxoutputgui.h.
Referenced by displaySampleRate(), displaySettings(), handleMessage(), on_extClock_clicked(), on_gain_valueChanged(), on_swInterp_currentIndexChanged(), setCenterFrequencyDisplay(), setCenterFrequencySetting(), setNCODisplay(), updateDACRate(), updateStatus(), XTRXOutputGUI(), and ~XTRXOutputGUI().
The documentation for this class was generated from the following files:
plugins/samplesink/xtrxoutput/xtrxoutputgui.h
plugins/samplesink/xtrxoutput/xtrxoutputgui.cpp