SDRAngel: UDPSinkFECWorker::MsgUDPFECEncodeAndSend Class Reference
UDPSinkFECWorker::MsgUDPFECEncodeAndSend Class Reference
#include <udpsinkfecworker.h>
Public Member Functions
RemoteSuperBlock * getTxBlocks () const
uint32_t getNbBlocsFEC () const
uint32_t getTxDelay () const
uint16_t getFrameIndex () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgUDPFECEncodeAndSend * create (RemoteSuperBlock *txBlocks, uint32_t nbBlocksFEC, uint32_t txDelay, uint16_t frameIndex)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgUDPFECEncodeAndSend (RemoteSuperBlock *txBlocks, uint32_t nbBlocksFEC, uint32_t txDelay, uint16_t frameIndex)
Private Attributes
RemoteSuperBlock * m_txBlockx
uint32_t m_nbBlocksFEC
uint32_t m_txDelay
uint16_t m_frameIndex
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 38 of file udpsinkfecworker.h.
Constructor & Destructor Documentation
MsgUDPFECEncodeAndSend()
UDPSinkFECWorker::MsgUDPFECEncodeAndSend::MsgUDPFECEncodeAndSend (RemoteSuperBlock * txBlocks, uint32_t nbBlocksFEC, uint32_t txDelay, uint16_t frameIndex) inline private
Definition at line 62 of file udpsinkfecworker.h.
Referenced by create().
                                      :
             m_txBlockx(txBlocks),
             m_nbBlocksFEC(nbBlocksFEC),
             m_txDelay(txDelay),
             m_frameIndex(frameIndex)
         {}
Member Function Documentation
create()
static MsgUDPFECEncodeAndSend* UDPSinkFECWorker::MsgUDPFECEncodeAndSend::create (RemoteSuperBlock * txBlocks, uint32_t nbBlocksFEC, uint32_t txDelay, uint16_t frameIndex) inline static
Definition at line 47 of file udpsinkfecworker.h.
References MsgUDPFECEncodeAndSend().
Referenced by UDPSinkFECWorker::pushTxFrame().
         {
             return new MsgUDPFECEncodeAndSend(txBlocks, nbBlocksFEC, txDelay, frameIndex);
         }
getFrameIndex()
uint16_t UDPSinkFECWorker::MsgUDPFECEncodeAndSend::getFrameIndex () const inline
Definition at line 45 of file udpsinkfecworker.h.
References m_frameIndex.
Referenced by UDPSinkFECWorker::handleInputMessages().
 { return m_frameIndex; }
getNbBlocsFEC()
uint32_t UDPSinkFECWorker::MsgUDPFECEncodeAndSend::getNbBlocsFEC () const inline
Definition at line 43 of file udpsinkfecworker.h.
References m_nbBlocksFEC.
Referenced by UDPSinkFECWorker::handleInputMessages().
 { return m_nbBlocksFEC; }
getTxBlocks()
RemoteSuperBlock* UDPSinkFECWorker::MsgUDPFECEncodeAndSend::getTxBlocks () const inline
Definition at line 42 of file udpsinkfecworker.h.
References m_txBlockx.
Referenced by UDPSinkFECWorker::handleInputMessages().
 { return m_txBlockx; }
getTxDelay()
uint32_t UDPSinkFECWorker::MsgUDPFECEncodeAndSend::getTxDelay () const inline
Definition at line 44 of file udpsinkfecworker.h.
References m_txDelay.
Referenced by UDPSinkFECWorker::handleInputMessages().
 { return m_txDelay; }
Member Data Documentation
m_frameIndex
uint16_t UDPSinkFECWorker::MsgUDPFECEncodeAndSend::m_frameIndex private
Definition at line 60 of file udpsinkfecworker.h.
Referenced by getFrameIndex().
m_nbBlocksFEC
uint32_t UDPSinkFECWorker::MsgUDPFECEncodeAndSend::m_nbBlocksFEC private
Definition at line 58 of file udpsinkfecworker.h.
Referenced by getNbBlocsFEC().
m_txBlockx
RemoteSuperBlock* UDPSinkFECWorker::MsgUDPFECEncodeAndSend::m_txBlockx private
Definition at line 57 of file udpsinkfecworker.h.
Referenced by getTxBlocks().
m_txDelay
uint32_t UDPSinkFECWorker::MsgUDPFECEncodeAndSend::m_txDelay private
Definition at line 59 of file udpsinkfecworker.h.
Referenced by getTxDelay().
The documentation for this class was generated from the following file:
plugins/samplesink/remoteoutput/udpsinkfecworker.h