SDRAngel: NFMMod::MsgConfigureChannelizer Class Reference
NFMMod::MsgConfigureChannelizer Class Reference
#include <nfmmod.h>
Public Member Functions
int getSampleRate () const
int getCenterFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (int sampleRate, int centerFrequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (int sampleRate, int centerFrequency)
Private Attributes
int m_sampleRate
int m_centerFrequency
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 76 of file nfmmod.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
NFMMod::MsgConfigureChannelizer::MsgConfigureChannelizer (int sampleRate, int centerFrequency) inline private
Definition at line 92 of file nfmmod.h.
                                                                      :
             Message(),
             m_sampleRate(sampleRate),
             m_centerFrequency(centerFrequency)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* NFMMod::MsgConfigureChannelizer::create (int sampleRate, int centerFrequency) inline static
Definition at line 83 of file nfmmod.h.
Referenced by NFMMod::applyAudioSampleRate(), NFMModGUI::applySettings(), NFMMod::deserialize(), and NFMMod::webapiSettingsPutPatch().
         {
             return new MsgConfigureChannelizer(sampleRate, centerFrequency);
         }
getCenterFrequency()
int NFMMod::MsgConfigureChannelizer::getCenterFrequency () const inline
Definition at line 81 of file nfmmod.h.
Referenced by NFMMod::handleMessage().
 { return m_centerFrequency; }
getSampleRate()
int NFMMod::MsgConfigureChannelizer::getSampleRate () const inline
Definition at line 80 of file nfmmod.h.
References NFMMod::m_sampleRate.
Referenced by NFMMod::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_centerFrequency
int NFMMod::MsgConfigureChannelizer::m_centerFrequency private
Definition at line 90 of file nfmmod.h.
m_sampleRate
int NFMMod::MsgConfigureChannelizer::m_sampleRate private
Definition at line 89 of file nfmmod.h.
The documentation for this class was generated from the following file:
plugins/channeltx/modnfm/nfmmod.h