SDRAngel: DSDDemodGUI Class Reference
DSDDemodGUI Class Reference
#include <dsddemodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
void channelMarkerHighlightedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static DSDDemodGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
Private Slots
void on_deltaFrequency_changed (qint64 value)
void on_rfBW_valueChanged (int index)
void on_demodGain_valueChanged (int value)
void on_volume_valueChanged (int value)
void on_baudRate_currentIndexChanged (int index)
void on_enableCosineFiltering_toggled (bool enable)
void on_syncOrConstellation_toggled (bool checked)
void on_traceLength_valueChanged (int value)
void on_traceStroke_valueChanged (int value)
void on_traceDecay_valueChanged (int value)
void on_slot1On_toggled (bool checked)
void on_slot2On_toggled (bool checked)
void on_tdmaStereoSplit_toggled (bool checked)
void on_fmDeviation_valueChanged (int value)
void on_squelchGate_valueChanged (int value)
void on_squelch_valueChanged (int value)
void on_highPassFilter_toggled (bool checked)
void on_audioMute_toggled (bool checked)
void on_symbolPLLLock_toggled (bool checked)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void on_viewStatusLog_clicked ()
void handleInputMessages ()
void audioSelect ()
void tick ()
Private Member Functions
DSDDemodGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *parent=0)
virtual ~DSDDemodGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
void updateMyPosition ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::DSDDemodGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
DSDDemodSettings m_settings
bool m_doApplySettings
ScopeVisXY * m_scopeVisXY
DSDDemod * m_dsdDemod
bool m_enableCosineFiltering
bool m_syncOrConstellation
bool m_slot1On
bool m_slot2On
bool m_tdmaStereo
bool m_audioMute
bool m_squelchOpen
uint32_t m_tickCount
float m_myLatitude
float m_myLongitude
MessageQueue m_inputMessageQueue
DSDStatusTextDialog m_dsdStatusTextDialog
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 45 of file dsddemodgui.h.
Constructor & Destructor Documentation
DSDDemodGUI()
DSDDemodGUI::DSDDemodGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * parent = 0) explicit private
Definition at line 311 of file dsddemodgui.cpp.
References DeviceUISet::addChannelMarker(), ScopeVisXY::addGraticulePoint(), DeviceUISet::addRollupWidget(), applySettings(), arg(), audioSelect(), ScopeVisXY::calculateGraticule(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), LevelMeterSignalDB::ColorGreenAndBlue, displaySettings(), getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, handleInputMessages(), DSDDemod::m_channelIdURI, m_channelMarker, m_deviceUISet, m_dsdDemod, m_scopeVisXY, m_settings, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), DSDDemodSettings::setChannelMarker(), ChannelMarker::setColor(), ScopeVisXY::setGridRGB(), BasebandSampleSink::setMessageQueueToGUI(), ScopeVisXY::setPixelsPerFrame(), ScopeVisXY::setPlotRGB(), ScopeVisXY::setScale(), DSDDemod::setScopeXYSink(), ChannelMarker::setTitle(), ChannelMarker::setVisible(), tick(), ui, updateMyPosition(), and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                        :
     RollupWidget(parent),
     ui(new Ui::DSDDemodGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_doApplySettings(true),
     m_enableCosineFiltering(false),
     m_syncOrConstellation(false),
     m_slot1On(false),
     m_slot2On(false),
     m_tdmaStereo(false),
     m_squelchOpen(false),
     m_tickCount(0),
     m_dsdStatusTextDialog(0)
 {
     ui->setupUi(this);
     ui->screenTV->setColor(true);
     ui->screenTV->resizeTVScreen(200,200);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
     CRightClickEnabler *audioMuteRightClickEnabler = new CRightClickEnabler(ui->audioMute);
     connect(audioMuteRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioSelect()));
     m_scopeVisXY = new ScopeVisXY(ui->screenTV);
     m_scopeVisXY->setScale(2.0);
     m_scopeVisXY->setPixelsPerFrame(4001);
     m_scopeVisXY->setPlotRGB(qRgb(0, 220, 250));
     m_scopeVisXY->setGridRGB(qRgb(255, 255, 128));
     for (float x = -0.84; x < 1.0; x += 0.56)
     {
         for (float y = -0.84; y < 1.0; y += 0.56)
         {
             m_scopeVisXY->addGraticulePoint(std::complex<float>(x, y));
         }
     }
     m_scopeVisXY->calculateGraticule(200,200);
     m_dsdDemod = (DSDDemod*) rxChannel; //new DSDDemod(m_deviceUISet->m_deviceSourceAPI);
     m_dsdDemod->setScopeXYSink(m_scopeVisXY);
     m_dsdDemod->setMessageQueueToGUI(getInputMessageQueue());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     ui->audioMute->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     ui->channelPowerMeter->setColorTheme(LevelMeterSignalDB::ColorGreenAndBlue);
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(Qt::cyan);
     m_channelMarker.setBandwidth(10000);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("DSD Demodulator");
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     m_deviceUISet->registerRxChannelInstance(DSDDemod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(&m_channelMarker, SIGNAL(highlightedByCursor()), this, SLOT(channelMarkerHighlightedByCursor()));
     m_settings.setChannelMarker(&m_channelMarker);
     updateMyPosition();
     displaySettings();
     applySettings(true);
 }
~DSDDemodGUI()
DSDDemodGUI::~DSDDemodGUI () private virtual
Definition at line 390 of file dsddemodgui.cpp.
References m_deviceUISet, m_dsdDemod, m_scopeVisXY, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_dsdDemod; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete m_scopeVisXY;
     delete ui;
 }
Member Function Documentation
applySettings()
void DSDDemodGUI::applySettings (bool force = false) private
Definition at line 471 of file dsddemodgui.cpp.
References DSDDemod::MsgConfigureDSDDemod::create(), DSDDemod::MsgConfigureChannelizer::create(), ChannelMarker::getCenterFrequency(), BasebandSampleSink::getInputMessageQueue(), m_channelMarker, m_doApplySettings, m_dsdDemod, m_settings, and MessageQueue::push().
Referenced by audioSelect(), channelMarkerChangedByCursor(), deserialize(), DSDDemodGUI(), on_audioMute_toggled(), on_baudRate_currentIndexChanged(), on_deltaFrequency_changed(), on_demodGain_valueChanged(), on_enableCosineFiltering_toggled(), on_fmDeviation_valueChanged(), on_highPassFilter_toggled(), on_rfBW_valueChanged(), on_slot1On_toggled(), on_slot2On_toggled(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_symbolPLLLock_toggled(), on_syncOrConstellation_toggled(), on_tdmaStereoSplit_toggled(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), and setCenterFrequency().
 {
     if (m_doApplySettings)
     {
         qDebug() << "DSDDemodGUI::applySettings";
         DSDDemod::MsgConfigureChannelizer* channelConfigMsg = DSDDemod::MsgConfigureChannelizer::create(
                 48000, m_channelMarker.getCenterFrequency());
         m_dsdDemod->getInputMessageQueue()->push(channelConfigMsg);
         DSDDemod::MsgConfigureDSDDemod* message = DSDDemod::MsgConfigureDSDDemod::create( m_settings, force);
         m_dsdDemod->getInputMessageQueue()->push(message);
     }
 }
audioSelect
void DSDDemodGUI::audioSelect () private slot
Definition at line 513 of file dsddemodgui.cpp.
References applySettings(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, DSDDemodSettings::m_audioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by DSDDemodGUI().
 {
     qDebug("DSDDemodGUI::audioSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName);
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_audioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
blockApplySettings()
void DSDDemodGUI::blockApplySettings (bool block) private
Definition at line 496 of file dsddemodgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), handleMessage(), and resetToDefaults().
 {
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void DSDDemodGUI::channelMarkerChangedByCursor () slot
Definition at line 501 of file dsddemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, DSDDemodSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by DSDDemodGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
channelMarkerHighlightedByCursor
void DSDDemodGUI::channelMarkerHighlightedByCursor () slot
Definition at line 508 of file dsddemodgui.cpp.
References ChannelMarker::getHighlighted(), m_channelMarker, and RollupWidget::setHighlighted().
Referenced by DSDDemodGUI().
 {
     setHighlighted(m_channelMarker.getHighlighted());
 }
create()
DSDDemodGUI * DSDDemodGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) static
Definition at line 45 of file dsddemodgui.cpp.
References DSDDemodGUI().
Referenced by DSDDemodPlugin::createRxChannelGUI().
 {
     DSDDemodGUI* gui = new DSDDemodGUI(pluginAPI, deviceUISet, rxChannel);
     return gui;
 }
deserialize()
bool DSDDemodGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 91 of file dsddemodgui.cpp.
References applySettings(), DSDDemodSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if (m_settings.deserialize(data))
     {
         displaySettings();
         applySettings(true);
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void DSDDemodGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 51 of file dsddemodgui.cpp.
 {
     delete this;
 }
displaySettings()
void DSDDemodGUI::displaySettings () private
Definition at line 411 of file dsddemodgui.cpp.
References arg(), blockApplySettings(), ChannelMarker::getCenterFrequency(), DSDDemodBaudRates::getRateIndex(), ChannelMarker::getTitle(), DSDDemodSettings::m_audioMute, DSDDemodSettings::m_baudRate, m_channelMarker, DSDDemodSettings::m_demodGain, DSDDemodSettings::m_enableCosineFiltering, DSDDemodSettings::m_fmDeviation, DSDDemodSettings::m_highPassFilter, DSDDemodSettings::m_inputFrequencyOffset, DSDDemodSettings::m_pllLock, DSDDemodSettings::m_rfBandwidth, DSDDemodSettings::m_rgbColor, m_scopeVisXY, m_settings, DSDDemodSettings::m_slot1On, DSDDemodSettings::m_slot2On, DSDDemodSettings::m_squelch, DSDDemodSettings::m_squelchGate, DSDDemodSettings::m_syncOrConstellation, DSDDemodSettings::m_tdmaStereo, DSDDemodSettings::m_title, DSDDemodSettings::m_traceDecay, DSDDemodSettings::m_traceLengthMutliplier, DSDDemodSettings::m_traceStroke, DSDDemodSettings::m_volume, ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ScopeVisXY::setDecay(), ScopeVisXY::setPixelsPerFrame(), ScopeVisXY::setStroke(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by deserialize(), DSDDemodGUI(), handleMessage(), and resetToDefaults().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.blockSignals(false);
     setTitleColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     ui->rfBW->setValue(m_settings.m_rfBandwidth / 100.0);
     ui->rfBWText->setText(QString("%1k").arg(ui->rfBW->value() / 10.0, 0, 'f', 1));
     ui->fmDeviation->setValue(m_settings.m_fmDeviation / 100.0);
     ui->fmDeviationText->setText(QString("%1%2k").arg(QChar(0xB1, 0x00)).arg(ui->fmDeviation->value() / 10.0, 0, 'f', 1));
     ui->squelch->setValue(m_settings.m_squelch);
     ui->squelchText->setText(QString("%1").arg(ui->squelch->value() / 1.0, 0, 'f', 0));
     ui->squelchGate->setValue(m_settings.m_squelchGate);
     ui->squelchGateText->setText(QString("%1").arg(ui->squelchGate->value() * 10.0, 0, 'f', 0));
     ui->demodGain->setValue(m_settings.m_demodGain * 100.0);
     ui->demodGainText->setText(QString("%1").arg(ui->demodGain->value() / 100.0, 0, 'f', 2));
     ui->volume->setValue(m_settings.m_volume * 10.0);
     ui->volumeText->setText(QString("%1").arg(ui->volume->value() / 10.0, 0, 'f', 1));
     ui->enableCosineFiltering->setChecked(m_settings.m_enableCosineFiltering);
     ui->syncOrConstellation->setChecked(m_settings.m_syncOrConstellation);
     ui->slot1On->setChecked(m_settings.m_slot1On);
     ui->slot2On->setChecked(m_settings.m_slot2On);
     ui->tdmaStereoSplit->setChecked(m_settings.m_tdmaStereo);
     ui->audioMute->setChecked(m_settings.m_audioMute);
     ui->symbolPLLLock->setChecked(m_settings.m_pllLock);
     ui->highPassFilter->setChecked(m_settings.m_highPassFilter);
     ui->baudRate->setCurrentIndex(DSDDemodBaudRates::getRateIndex(m_settings.m_baudRate));
     ui->traceLength->setValue(m_settings.m_traceLengthMutliplier);
     ui->traceLengthText->setText(QString("%1").arg(m_settings.m_traceLengthMutliplier*50));
     m_scopeVisXY->setPixelsPerFrame(m_settings.m_traceLengthMutliplier*960); // 48000 / 50. Chunks of 50 ms.
     ui->traceStroke->setValue(m_settings.m_traceStroke);
     ui->traceStrokeText->setText(QString("%1").arg(m_settings.m_traceStroke));
     m_scopeVisXY->setStroke(m_settings.m_traceStroke);
     ui->traceDecay->setValue(m_settings.m_traceDecay);
     ui->traceDecayText->setText(QString("%1").arg(m_settings.m_traceDecay));
     m_scopeVisXY->setDecay(m_settings.m_traceDecay);
     blockApplySettings(false);
 }
enterEvent()
void DSDDemodGUI::enterEvent (QEvent *) private
Definition at line 491 of file dsddemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 DSDDemodGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 66 of file dsddemodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
 {
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* DSDDemodGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 60 of file dsddemodgui.h.
Referenced by DSDDemodGUI(), and handleInputMessages().
 { return &m_inputMessageQueue; }
getName()
QString DSDDemodGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 61 of file dsddemodgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void DSDDemodGUI::handleInputMessages () private slot
Definition at line 124 of file dsddemodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by DSDDemodGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
bool DSDDemodGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 106 of file dsddemodgui.cpp.
References blockApplySettings(), displaySettings(), DSDDemod::MsgConfigureDSDDemod::getSettings(), m_settings, and Message::match().
Referenced by handleInputMessages().
 {
     if (DSDDemod::MsgConfigureDSDDemod::match(message))
     {
         qDebug("DSDDemodGUI::handleMessage: DSDDemod::MsgConfigureDSDDemod");
         const DSDDemod::MsgConfigureDSDDemod& cfg = (DSDDemod::MsgConfigureDSDDemod&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
leaveEvent()
void DSDDemodGUI::leaveEvent (QEvent *) private
Definition at line 486 of file dsddemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_audioMute_toggled
void DSDDemodGUI::on_audioMute_toggled (bool checked) private slot
Definition at line 244 of file dsddemodgui.cpp.
References applySettings(), DSDDemodSettings::m_audioMute, and m_settings.
 {
     m_settings.m_audioMute = checked;
     applySettings();
 }
on_baudRate_currentIndexChanged
void DSDDemodGUI::on_baudRate_currentIndexChanged (int index) private slot
Definition at line 173 of file dsddemodgui.cpp.
References applySettings(), DSDDemodBaudRates::getRate(), DSDDemodSettings::m_baudRate, and m_settings.
 {
     m_settings.m_baudRate = DSDDemodBaudRates::getRate(index);
     applySettings();
 }
on_deltaFrequency_changed
void DSDDemodGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 137 of file dsddemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, DSDDemodSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_demodGain_valueChanged
void DSDDemodGUI::on_demodGain_valueChanged (int value) private slot
Definition at line 152 of file dsddemodgui.cpp.
References applySettings(), arg(), DSDDemodSettings::m_demodGain, m_settings, and ui.
 {
     m_settings.m_demodGain = value / 100.0;
     ui->demodGainText->setText(QString("%1").arg(value / 100.0, 0, 'f', 2));
     applySettings();
 }
on_enableCosineFiltering_toggled
void DSDDemodGUI::on_enableCosineFiltering_toggled (bool enable) private slot
Definition at line 179 of file dsddemodgui.cpp.
References applySettings(), DSDDemodSettings::m_enableCosineFiltering, and m_settings.
 {
     m_settings.m_enableCosineFiltering = enable;
     applySettings();
 }
on_fmDeviation_valueChanged
void DSDDemodGUI::on_fmDeviation_valueChanged (int value) private slot
Definition at line 159 of file dsddemodgui.cpp.
References applySettings(), arg(), DSDDemodSettings::m_fmDeviation, m_settings, and ui.
 {
     m_settings.m_fmDeviation = value * 100.0;
     ui->fmDeviationText->setText(QString("%1%2k").arg(QChar(0xB1, 0x00)).arg(value / 10.0, 0, 'f', 1));
     applySettings();
 }
on_highPassFilter_toggled
void DSDDemodGUI::on_highPassFilter_toggled (bool checked) private slot
Definition at line 250 of file dsddemodgui.cpp.
References applySettings(), DSDDemodSettings::m_highPassFilter, and m_settings.
 {
     m_settings.m_highPassFilter = checked;
     applySettings();
 }
on_rfBW_valueChanged
void DSDDemodGUI::on_rfBW_valueChanged (int index) private slot
Definition at line 144 of file dsddemodgui.cpp.
References applySettings(), arg(), m_channelMarker, DSDDemodSettings::m_rfBandwidth, m_settings, ChannelMarker::setBandwidth(), and ui.
 {
     m_channelMarker.setBandwidth(value * 100);
     m_settings.m_rfBandwidth = value * 100.0;
     ui->rfBWText->setText(QString("%1k").arg(value / 10.0, 0, 'f', 1));
     applySettings();
 }
on_slot1On_toggled
void DSDDemodGUI::on_slot1On_toggled (bool checked) private slot
Definition at line 212 of file dsddemodgui.cpp.
References applySettings(), m_settings, and DSDDemodSettings::m_slot1On.
 {
     m_settings.m_slot1On = checked;
     applySettings();
 }
on_slot2On_toggled
void DSDDemodGUI::on_slot2On_toggled (bool checked) private slot
Definition at line 218 of file dsddemodgui.cpp.
References applySettings(), m_settings, and DSDDemodSettings::m_slot2On.
 {
     m_settings.m_slot2On = checked;
     applySettings();
 }
on_squelch_valueChanged
void DSDDemodGUI::on_squelch_valueChanged (int value) private slot
Definition at line 237 of file dsddemodgui.cpp.
References applySettings(), arg(), m_settings, DSDDemodSettings::m_squelch, and ui.
 {
     ui->squelchText->setText(QString("%1").arg(value / 1.0, 0, 'f', 0));
     m_settings.m_squelch = value;
     applySettings();
 }
on_squelchGate_valueChanged
void DSDDemodGUI::on_squelchGate_valueChanged (int value) private slot
Definition at line 230 of file dsddemodgui.cpp.
References applySettings(), arg(), m_settings, DSDDemodSettings::m_squelchGate, and ui.
 {
     m_settings.m_squelchGate = value;
     ui->squelchGateText->setText(QString("%1").arg(value * 10.0, 0, 'f', 0));
     applySettings();
 }
on_symbolPLLLock_toggled
void DSDDemodGUI::on_symbolPLLLock_toggled (bool checked) private slot
Definition at line 256 of file dsddemodgui.cpp.
References applySettings(), DSDDemodSettings::m_pllLock, m_settings, and ui.
 {
     if (checked) {
         ui->symbolPLLLock->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     } else {
         ui->symbolPLLLock->setStyleSheet("QToolButton { background:rgb(53,53,53); }");
     }
     m_settings.m_pllLock = checked;
     applySettings();
 }
on_syncOrConstellation_toggled
void DSDDemodGUI::on_syncOrConstellation_toggled (bool checked) private slot
Definition at line 185 of file dsddemodgui.cpp.
References applySettings(), m_settings, and DSDDemodSettings::m_syncOrConstellation.
 {
     m_settings.m_syncOrConstellation = checked;
     applySettings();
 }
on_tdmaStereoSplit_toggled
void DSDDemodGUI::on_tdmaStereoSplit_toggled (bool checked) private slot
Definition at line 224 of file dsddemodgui.cpp.
References applySettings(), m_settings, and DSDDemodSettings::m_tdmaStereo.
 {
     m_settings.m_tdmaStereo = checked;
     applySettings();
 }
on_traceDecay_valueChanged
void DSDDemodGUI::on_traceDecay_valueChanged (int value) private slot
Definition at line 205 of file dsddemodgui.cpp.
References arg(), m_scopeVisXY, m_settings, DSDDemodSettings::m_traceDecay, ScopeVisXY::setDecay(), and ui.
 {
     m_settings.m_traceDecay = value;
     ui->traceDecayText->setText(QString("%1").arg(m_settings.m_traceDecay));
     m_scopeVisXY->setDecay(m_settings.m_traceDecay);
 }
on_traceLength_valueChanged
void DSDDemodGUI::on_traceLength_valueChanged (int value) private slot
Definition at line 191 of file dsddemodgui.cpp.
References arg(), m_scopeVisXY, m_settings, DSDDemodSettings::m_traceLengthMutliplier, ScopeVisXY::setPixelsPerFrame(), and ui.
 {
     m_settings.m_traceLengthMutliplier = value;
     ui->traceLengthText->setText(QString("%1").arg(m_settings.m_traceLengthMutliplier*50));
     m_scopeVisXY->setPixelsPerFrame(m_settings.m_traceLengthMutliplier*960); // 48000 / 50. Chunks of 50 ms.
 }
on_traceStroke_valueChanged
void DSDDemodGUI::on_traceStroke_valueChanged (int value) private slot
Definition at line 198 of file dsddemodgui.cpp.
References arg(), m_scopeVisXY, m_settings, DSDDemodSettings::m_traceStroke, ScopeVisXY::setStroke(), and ui.
 {
     m_settings.m_traceStroke = value;
     ui->traceStrokeText->setText(QString("%1").arg(m_settings.m_traceStroke));
     m_scopeVisXY->setStroke(m_settings.m_traceStroke);
 }
on_viewStatusLog_clicked
void DSDDemodGUI::on_viewStatusLog_clicked () private slot
Definition at line 305 of file dsddemodgui.cpp.
References m_dsdStatusTextDialog.
 {
     qDebug("DSDDemodGUI::on_viewStatusLog_clicked");
     m_dsdStatusTextDialog.exec();
 }
on_volume_valueChanged
void DSDDemodGUI::on_volume_valueChanged (int value) private slot
Definition at line 166 of file dsddemodgui.cpp.
References applySettings(), arg(), m_settings, DSDDemodSettings::m_volume, and ui.
 {
     m_settings.m_volume= value / 10.0;
     ui->volumeText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     applySettings();
 }
onMenuDialogCalled
void DSDDemodGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 273 of file dsddemodgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, DSDDemodSettings::m_inputFrequencyOffset, DSDDemodSettings::m_reverseAPIAddress, DSDDemodSettings::m_reverseAPIChannelIndex, DSDDemodSettings::m_reverseAPIDeviceIndex, DSDDemodSettings::m_reverseAPIPort, DSDDemodSettings::m_rgbColor, m_settings, DSDDemodSettings::m_title, DSDDemodSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by DSDDemodGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void DSDDemodGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 267 of file dsddemodgui.cpp.
Referenced by DSDDemodGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void DSDDemodGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 77 of file dsddemodgui.cpp.
References applySettings(), blockApplySettings(), displaySettings(), m_settings, and DSDDemodSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     blockApplySettings(true);
     displaySettings();
     blockApplySettings(false);
     applySettings();
 }
serialize()
QByteArray DSDDemodGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 86 of file dsddemodgui.cpp.
References m_settings, and DSDDemodSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void DSDDemodGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 71 of file dsddemodgui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     applySettings();
 }
setName()
void DSDDemodGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 56 of file dsddemodgui.cpp.
 {
     setObjectName(name);
 }
tick
void DSDDemodGUI::tick () private slot
Definition at line 526 of file dsddemodgui.cpp.
References DSDStatusTextDialog::addLine(), arg(), CalcDb::dbPower(), DSDDecoder::getCarrierPos(), DSDDemod::getDecoder(), DSDDecoder::getFrameTypeText(), DSDDecoder::getInLevel(), DSDDemod::getMagSqLevels(), DSDDemod::getSquelchOpen(), DSDDecoder::getSymbolPLLLocked(), DSDDecoder::getSymbolSyncQuality(), DSDDecoder::getVoice1On(), DSDDecoder::getVoice2On(), DSDDecoder::getZeroCrossingPos(), m_dsdDemod, m_dsdStatusTextDialog, m_squelchOpen, m_tickCount, ui, and DSDDemod::updateAndGetStatusText().
Referenced by DSDDemodGUI().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     m_dsdDemod->getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     double powDbAvg = CalcDb::dbPower(magsqAvg);
     double powDbPeak = CalcDb::dbPower(magsqPeak);
     ui->channelPowerMeter->levelChanged(
             (100.0f + powDbAvg) / 100.0f,
             (100.0f + powDbPeak) / 100.0f,
             nbMagsqSamples);
     if (m_tickCount % 4 == 0) {
         ui->channelPower->setText(tr("%1 dB").arg(powDbAvg, 0, 'f', 1));
     }
     bool squelchOpen = m_dsdDemod->getSquelchOpen();
     if (squelchOpen != m_squelchOpen)
     {
         if (squelchOpen) {
             ui->audioMute->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->audioMute->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         }
         m_squelchOpen = squelchOpen;
     }
     // "slow" updates
     if (m_tickCount % 10 == 0)
     {
         ui->inLevelText->setText(QString::number(m_dsdDemod->getDecoder().getInLevel()));
         ui->inCarrierPosText->setText(QString::number(m_dsdDemod->getDecoder().getCarrierPos()));
         ui->zcPosText->setText(QString::number(m_dsdDemod->getDecoder().getZeroCrossingPos()));
         ui->symbolSyncQualityText->setText(QString::number(m_dsdDemod->getDecoder().getSymbolSyncQuality()));
         if (m_dsdDemod->getDecoder().getVoice1On()) {
             ui->slot1On->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->slot1On->setStyleSheet("QToolButton { background-color : rgb(79,79,79); }");
         }
         if (m_dsdDemod->getDecoder().getVoice2On()) {
             ui->slot2On->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->slot2On->setStyleSheet("QToolButton { background-color : rgb(79,79,79); }");
         }
         const char *frameTypeText = m_dsdDemod->getDecoder().getFrameTypeText();
         if (frameTypeText[0] == '\0') {
             ui->syncText->setStyleSheet("QLabel { background:rgb(53,53,53); }"); // turn off background
         } else {
             ui->syncText->setStyleSheet("QLabel { background:rgb(37,53,39); }"); // turn on background
         }
         ui->syncText->setText(QString(frameTypeText));
         const char *formatStatusText = m_dsdDemod->updateAndGetStatusText();
         ui->formatStatusText->setText(QString(formatStatusText));
         if (ui->activateStatusLog->isChecked()) {
             m_dsdStatusTextDialog.addLine(QString(formatStatusText));
         }
         if (formatStatusText[0] == '\0') {
             ui->formatStatusText->setStyleSheet("QLabel { background:rgb(53,53,53); }"); // turn off background
         } else {
             ui->formatStatusText->setStyleSheet("QLabel { background:rgb(37,53,39); }"); // turn on background
         }
         if (m_squelchOpen && ui->symbolPLLLock->isChecked() && m_dsdDemod->getDecoder().getSymbolPLLLocked()) {
             ui->symbolPLLLock->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->symbolPLLLock->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         }
     }
     m_tickCount++;
 }
updateMyPosition()
void DSDDemodGUI::updateMyPosition () private
Definition at line 398 of file dsddemodgui.cpp.
References DSDDemod::configureMyPosition(), BasebandSampleSink::getInputMessageQueue(), MainWindow::getInstance(), MainSettings::getLatitude(), MainSettings::getLongitude(), MainWindow::getMainSettings(), m_dsdDemod, m_myLatitude, and m_myLongitude.
Referenced by DSDDemodGUI().
 {
     float latitude = MainWindow::getInstance()->getMainSettings().getLatitude();
     float longitude = MainWindow::getInstance()->getMainSettings().getLongitude();
     if ((m_myLatitude != latitude) || (m_myLongitude != longitude))
     {
         m_dsdDemod->configureMyPosition(m_dsdDemod->getInputMessageQueue(), latitude, longitude);
         m_myLatitude = latitude;
         m_myLongitude = longitude;
     }
 }
Member Data Documentation
m_audioMute
bool DSDDemodGUI::m_audioMute private
Definition at line 92 of file dsddemodgui.h.
m_channelMarker
ChannelMarker DSDDemodGUI::m_channelMarker private
Definition at line 80 of file dsddemodgui.h.
Referenced by applySettings(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), displaySettings(), DSDDemodGUI(), enterEvent(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), on_rfBW_valueChanged(), onMenuDialogCalled(), and setCenterFrequency().
m_deviceUISet
DeviceUISet* DSDDemodGUI::m_deviceUISet private
Definition at line 79 of file dsddemodgui.h.
Referenced by DSDDemodGUI(), and ~DSDDemodGUI().
m_doApplySettings
bool DSDDemodGUI::m_doApplySettings private
Definition at line 82 of file dsddemodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_dsdDemod
DSDDemod* DSDDemodGUI::m_dsdDemod private
Definition at line 86 of file dsddemodgui.h.
Referenced by applySettings(), DSDDemodGUI(), tick(), updateMyPosition(), and ~DSDDemodGUI().
m_dsdStatusTextDialog
DSDStatusTextDialog DSDDemodGUI::m_dsdStatusTextDialog private
Definition at line 101 of file dsddemodgui.h.
Referenced by on_viewStatusLog_clicked(), and tick().
m_enableCosineFiltering
bool DSDDemodGUI::m_enableCosineFiltering private
Definition at line 87 of file dsddemodgui.h.
m_inputMessageQueue
MessageQueue DSDDemodGUI::m_inputMessageQueue private
Definition at line 99 of file dsddemodgui.h.
m_myLatitude
float DSDDemodGUI::m_myLatitude private
Definition at line 96 of file dsddemodgui.h.
Referenced by updateMyPosition().
m_myLongitude
float DSDDemodGUI::m_myLongitude private
Definition at line 97 of file dsddemodgui.h.
Referenced by updateMyPosition().
m_pluginAPI
PluginAPI* DSDDemodGUI::m_pluginAPI private
Definition at line 78 of file dsddemodgui.h.
m_scopeVisXY
ScopeVisXY* DSDDemodGUI::m_scopeVisXY private
Definition at line 84 of file dsddemodgui.h.
Referenced by displaySettings(), DSDDemodGUI(), on_traceDecay_valueChanged(), on_traceLength_valueChanged(), on_traceStroke_valueChanged(), and ~DSDDemodGUI().
m_settings
DSDDemodSettings DSDDemodGUI::m_settings private
Definition at line 81 of file dsddemodgui.h.
Referenced by applySettings(), audioSelect(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), DSDDemodGUI(), handleMessage(), on_audioMute_toggled(), on_baudRate_currentIndexChanged(), on_deltaFrequency_changed(), on_demodGain_valueChanged(), on_enableCosineFiltering_toggled(), on_fmDeviation_valueChanged(), on_highPassFilter_toggled(), on_rfBW_valueChanged(), on_slot1On_toggled(), on_slot2On_toggled(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_symbolPLLLock_toggled(), on_syncOrConstellation_toggled(), on_tdmaStereoSplit_toggled(), on_traceDecay_valueChanged(), on_traceLength_valueChanged(), on_traceStroke_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), and serialize().
m_slot1On
bool DSDDemodGUI::m_slot1On private
Definition at line 89 of file dsddemodgui.h.
m_slot2On
bool DSDDemodGUI::m_slot2On private
Definition at line 90 of file dsddemodgui.h.
m_squelchOpen
bool DSDDemodGUI::m_squelchOpen private
Definition at line 93 of file dsddemodgui.h.
Referenced by tick().
m_syncOrConstellation
bool DSDDemodGUI::m_syncOrConstellation private
Definition at line 88 of file dsddemodgui.h.
m_tdmaStereo
bool DSDDemodGUI::m_tdmaStereo private
Definition at line 91 of file dsddemodgui.h.
m_tickCount
uint32_t DSDDemodGUI::m_tickCount private
Definition at line 94 of file dsddemodgui.h.
Referenced by tick().
ui
Ui::DSDDemodGUI* DSDDemodGUI::ui private
Definition at line 77 of file dsddemodgui.h.
Referenced by channelMarkerChangedByCursor(), displaySettings(), DSDDemodGUI(), on_demodGain_valueChanged(), on_fmDeviation_valueChanged(), on_rfBW_valueChanged(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_symbolPLLLock_toggled(), on_traceDecay_valueChanged(), on_traceLength_valueChanged(), on_traceStroke_valueChanged(), on_volume_valueChanged(), tick(), and ~DSDDemodGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/demoddsd/dsddemodgui.h
plugins/channelrx/demoddsd/dsddemodgui.cpp