SDRAngel: SDRPlayInput::MsgReportSDRPlayGains Class Reference
SDRPlayInput::MsgReportSDRPlayGains Class Reference
#include <sdrplayinput.h>
Public Member Functions
int getLNAGain () const
int getMixerGain () const
int getBasebandGain () const
int getTunerGain () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportSDRPlayGains * create (int lnaGain, int mixerGain, int basebandGain, int tunerGain)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportSDRPlayGains (int lnaGain, int mixerGain, int basebandGain, int tunerGain)
Protected Attributes
int m_lnaGain
int m_mixerGain
int m_basebandGain
int m_tunerGain
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 71 of file sdrplayinput.h.
Constructor & Destructor Documentation
MsgReportSDRPlayGains()
SDRPlayInput::MsgReportSDRPlayGains::MsgReportSDRPlayGains (int lnaGain, int mixerGain, int basebandGain, int tunerGain) inline protected
Definition at line 91 of file sdrplayinput.h.
                                                                                            :
             Message(),
             m_lnaGain(lnaGain),
             m_mixerGain(mixerGain),
             m_basebandGain(basebandGain),
             m_tunerGain(tunerGain)
         { }
Member Function Documentation
create()
static MsgReportSDRPlayGains* SDRPlayInput::MsgReportSDRPlayGains::create (int lnaGain, int mixerGain, int basebandGain, int tunerGain) inline static
Definition at line 75 of file sdrplayinput.h.
Referenced by SDRPlayInput::applySettings().
         {
             return new MsgReportSDRPlayGains(lnaGain, mixerGain, basebandGain, tunerGain);
         }
getBasebandGain()
int SDRPlayInput::MsgReportSDRPlayGains::getBasebandGain () const inline
Definition at line 82 of file sdrplayinput.h.
Referenced by SDRPlayGui::handleMessage().
 { return m_basebandGain; }
getLNAGain()
int SDRPlayInput::MsgReportSDRPlayGains::getLNAGain () const inline
Definition at line 80 of file sdrplayinput.h.
Referenced by SDRPlayGui::handleMessage().
 { return m_lnaGain; }
getMixerGain()
int SDRPlayInput::MsgReportSDRPlayGains::getMixerGain () const inline
Definition at line 81 of file sdrplayinput.h.
Referenced by SDRPlayGui::handleMessage().
 { return m_mixerGain; }
getTunerGain()
int SDRPlayInput::MsgReportSDRPlayGains::getTunerGain () const inline
Definition at line 83 of file sdrplayinput.h.
Referenced by SDRPlayGui::handleMessage().
 { return m_tunerGain; }
Member Data Documentation
m_basebandGain
int SDRPlayInput::MsgReportSDRPlayGains::m_basebandGain protected
Definition at line 88 of file sdrplayinput.h.
m_lnaGain
int SDRPlayInput::MsgReportSDRPlayGains::m_lnaGain protected
Definition at line 86 of file sdrplayinput.h.
m_mixerGain
int SDRPlayInput::MsgReportSDRPlayGains::m_mixerGain protected
Definition at line 87 of file sdrplayinput.h.
m_tunerGain
int SDRPlayInput::MsgReportSDRPlayGains::m_tunerGain protected
Definition at line 89 of file sdrplayinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/sdrplay/sdrplayinput.h