SDRAngel: AddPresetDialog Class Reference
AddPresetDialog Class Reference
#include <addpresetdialog.h>
Inherits QDialog.
Public Member Functions
AddPresetDialog (const QStringList &groups, const QString &group, QWidget *parent=NULL)
~AddPresetDialog ()
QString group () const
QString description () const
void setGroup (const QString &group)
void setDescription (const QString &description)
void showGroupOnly ()
void setDialogTitle (const QString &title)
void setDescriptionBoxTitle (const QString &title)
Private Types
enum Audio { ATDefault, ATInterface, ATDevice }
Private Attributes
Ui::AddPresetDialog * ui
Detailed Description
Definition at line 12 of file addpresetdialog.h.
Member Enumeration Documentation
Audio
enum AddPresetDialog::Audio private
Enumerator
ATDefault
ATInterface
ATDevice
Definition at line 28 of file addpresetdialog.h.
                {
         ATDefault,
         ATInterface,
         ATDevice
     };
Constructor & Destructor Documentation
AddPresetDialog()
AddPresetDialog::AddPresetDialog (const QStringList & groups, const QString & group, QWidget * parent = NULL) explicit
Definition at line 4 of file addpresetdialog.cpp.
References ui.
                                                                                                  :
     QDialog(parent),
     ui(new Ui::AddPresetDialog)
 {
     ui->setupUi(this);
     ui->group->addItems(groups);
     ui->group->lineEdit()->setText(group);
 }
~AddPresetDialog()
AddPresetDialog::~AddPresetDialog ()
Definition at line 13 of file addpresetdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
description()
QString AddPresetDialog::description () const
Definition at line 23 of file addpresetdialog.cpp.
References ui.
Referenced by MainWindow::on_presetSave_clicked().
 {
     return ui->description->text();
 }
group()
QString AddPresetDialog::group () const
Definition at line 18 of file addpresetdialog.cpp.
References ui.
Referenced by MainWindow::on_presetSave_clicked().
 {
     return ui->group->lineEdit()->text();
 }
setDescription()
void AddPresetDialog::setDescription (const QString & description)
Definition at line 33 of file addpresetdialog.cpp.
References ui.
Referenced by MainWindow::on_presetEdit_clicked(), and MainWindow::on_presetSave_clicked().
 {
     ui->description->setText(description);
 }
setDescriptionBoxTitle()
void AddPresetDialog::setDescriptionBoxTitle (const QString & title)
Definition at line 49 of file addpresetdialog.cpp.
References ui.
 {
     ui->descriptionBox->setTitle(title);
 }
setDialogTitle()
void AddPresetDialog::setDialogTitle (const QString & title)
Definition at line 44 of file addpresetdialog.cpp.
 {
     setWindowTitle(title);
 }
setGroup()
void AddPresetDialog::setGroup (const QString & group)
Definition at line 28 of file addpresetdialog.cpp.
References ui.
 {
     ui->group->lineEdit()->setText(group);
 }
showGroupOnly()
void AddPresetDialog::showGroupOnly ()
Definition at line 38 of file addpresetdialog.cpp.
References ui.
Referenced by MainWindow::on_commandEdit_clicked(), and MainWindow::on_presetEdit_clicked().
 {
     ui->description->hide();
     ui->descriptionLabel->hide();
 }
Member Data Documentation
ui
Ui::AddPresetDialog* AddPresetDialog::ui private
Definition at line 34 of file addpresetdialog.h.
Referenced by AddPresetDialog(), description(), group(), setDescription(), setDescriptionBoxTitle(), setGroup(), showGroupOnly(), and ~AddPresetDialog().
The documentation for this class was generated from the following files:
sdrgui/gui/addpresetdialog.h
sdrgui/gui/addpresetdialog.cpp