SDRAngel: TimeUtil Class Reference
TimeUtil Class Reference
#include <timeutil.h>
Static Public Member Functions
static uint64_t nowms ()
returns the current epoch in milliseconds
static uint64_t nowus ()
returns the current epoch in microseconds
Detailed Description
Definition at line 23 of file timeutil.h.
Member Function Documentation
nowms()
uint64_t TimeUtil::nowms () static
returns the current epoch in milliseconds
Definition at line 20 of file timeutil.cpp.
Referenced by Command::processError(), Command::processFinished(), and Command::run().
 {
     auto now = std::chrono::system_clock::now();
     auto now_ms = std::chrono::time_point_cast<std::chrono::milliseconds>(now);
     auto epoch = now_ms.time_since_epoch();
     auto value = std::chrono::duration_cast<std::chrono::milliseconds>(epoch);
     return value.count();
 }
nowus()
uint64_t TimeUtil::nowus () static
returns the current epoch in microseconds
Definition at line 30 of file timeutil.cpp.
Referenced by RemoteOutputThread::getSamplesCount(), and UDPSinkFEC::write().
 {
     auto now = std::chrono::system_clock::now();
     auto now_ms = std::chrono::time_point_cast<std::chrono::microseconds>(now);
     auto epoch = now_ms.time_since_epoch();
     auto value = std::chrono::duration_cast<std::chrono::microseconds>(epoch);
     return value.count();
 }
The documentation for this class was generated from the following files:
sdrbase/util/timeutil.h
sdrbase/util/timeutil.cpp