SDRAngel: DynamicItemSettingGUI Class Reference
DynamicItemSettingGUI Class Reference
#include <dynamicitemsettinggui.h>
Inherits QObject.
Signals
void valueChanged (QString itemName, double value)
Public Member Functions
DynamicItemSettingGUI (ItemSettingGUI *itemSettingGUI, const QString &name, QObject *parent=0)
~DynamicItemSettingGUI ()
const QString & getName () const
double getValue () const
void setValue (double value)
Private Slots
void processValueChanged (double value)
Private Attributes
ItemSettingGUI * m_itemSettingGUI
QString m_name
Detailed Description
Definition at line 24 of file dynamicitemsettinggui.h.
Constructor & Destructor Documentation
DynamicItemSettingGUI()
DynamicItemSettingGUI::DynamicItemSettingGUI (ItemSettingGUI * itemSettingGUI, const QString & name, QObject * parent = 0)
Definition at line 20 of file dynamicitemsettinggui.cpp.
References m_itemSettingGUI, processValueChanged(), and valueChanged().
                                                                                                                  :
     QObject(parent),
     m_itemSettingGUI(itemSettingGUI),
     m_name(name)
 {
     connect(m_itemSettingGUI, SIGNAL(valueChanged(double)), this, SLOT(processValueChanged(double)));
 }
~DynamicItemSettingGUI()
DynamicItemSettingGUI::~DynamicItemSettingGUI ()
Definition at line 28 of file dynamicitemsettinggui.cpp.
References m_itemSettingGUI, processValueChanged(), and valueChanged().
 {
     disconnect(m_itemSettingGUI, SIGNAL(valueChanged(double)), this, SLOT(processValueChanged(double)));
 }
Member Function Documentation
getName()
const QString& DynamicItemSettingGUI::getName () const inline
Definition at line 31 of file dynamicitemsettinggui.h.
 { return m_name; }
getValue()
double DynamicItemSettingGUI::getValue () const inline
Definition at line 32 of file dynamicitemsettinggui.h.
 { return m_itemSettingGUI->getCurrentValue(); }
processValueChanged
void DynamicItemSettingGUI::processValueChanged (double value) private slot
Definition at line 33 of file dynamicitemsettinggui.cpp.
References m_name, and valueChanged().
Referenced by DynamicItemSettingGUI(), and ~DynamicItemSettingGUI().
{
     emit valueChanged(m_name, value);
 }
setValue()
void DynamicItemSettingGUI::setValue (double value) inline
Definition at line 33 of file dynamicitemsettinggui.h.
 { m_itemSettingGUI->setValue(value); }
valueChanged
void DynamicItemSettingGUI::valueChanged (QString itemName, double value) signal
Referenced by DynamicItemSettingGUI(), processValueChanged(), and ~DynamicItemSettingGUI().
Member Data Documentation
m_itemSettingGUI
ItemSettingGUI* DynamicItemSettingGUI::m_itemSettingGUI private
Definition at line 42 of file dynamicitemsettinggui.h.
Referenced by DynamicItemSettingGUI(), and ~DynamicItemSettingGUI().
m_name
QString DynamicItemSettingGUI::m_name private
Definition at line 43 of file dynamicitemsettinggui.h.
Referenced by processValueChanged().
The documentation for this class was generated from the following files:
sdrgui/soapygui/dynamicitemsettinggui.h
sdrgui/soapygui/dynamicitemsettinggui.cpp