SDRAngel: BladeRF2Output::MsgReportGainRange Class Reference
BladeRF2Output::MsgReportGainRange Class Reference
#include <bladerf2output.h>
Public Member Functions
int getMin () const
int getMax () const
int getStep () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportGainRange * create (int min, int max, int step)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportGainRange (int min, int max, int step)
Protected Attributes
int m_min
int m_max
int m_step
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 81 of file bladerf2output.h.
Constructor & Destructor Documentation
MsgReportGainRange()
BladeRF2Output::MsgReportGainRange::MsgReportGainRange (int min, int max, int step) inline protected
Definition at line 98 of file bladerf2output.h.
References BladeRF2Output::BladeRF2Output(), BladeRF2Output::destroy(), BladeRF2Output::init(), BladeRF2Output::start(), BladeRF2Output::stop(), and BladeRF2Output::~BladeRF2Output().
                                                        :
             Message(),
             m_min(min),
             m_max(max),
             m_step(step)
         {}
Member Function Documentation
create()
static MsgReportGainRange* BladeRF2Output::MsgReportGainRange::create (int min, int max, int step) inline static
Definition at line 89 of file bladerf2output.h.
Referenced by BladeRF2Output::applySettings().
{
             return new MsgReportGainRange(min, max, step);
         }
getMax()
int BladeRF2Output::MsgReportGainRange::getMax () const inline
Definition at line 86 of file bladerf2output.h.
Referenced by BladeRF2OutputGui::handleMessage().
 { return m_max; }
getMin()
int BladeRF2Output::MsgReportGainRange::getMin () const inline
Definition at line 85 of file bladerf2output.h.
Referenced by BladeRF2OutputGui::handleMessage().
 { return m_min; }
getStep()
int BladeRF2Output::MsgReportGainRange::getStep () const inline
Definition at line 87 of file bladerf2output.h.
 { return m_step; }
Member Data Documentation
m_max
int BladeRF2Output::MsgReportGainRange::m_max protected
Definition at line 95 of file bladerf2output.h.
m_min
int BladeRF2Output::MsgReportGainRange::m_min protected
Definition at line 94 of file bladerf2output.h.
m_step
int BladeRF2Output::MsgReportGainRange::m_step protected
Definition at line 96 of file bladerf2output.h.
The documentation for this class was generated from the following file:
plugins/samplesink/bladerf2output/bladerf2output.h