SDRAngel: ParserBench Class Reference
ParserBench Class Reference
#include <parserbench.h>
Public Types
enum TestType {
TestDecimatorsII, TestDecimatorsIF, TestDecimatorsFI, TestDecimatorsFF,
TestDecimatorsInfII, TestDecimatorsSupII, TestAMBE
}
Public Member Functions
ParserBench ()
~ParserBench ()
void parse (const QCoreApplication &app)
const QString & getTestStr () const
TestType getTestType () const
uint32_t getNbSamples () const
uint32_t getRepetition () const
uint32_t getLog2Factor () const
Private Attributes
QString m_testStr
uint32_t m_nbSamples
uint32_t m_repetition
uint32_t m_log2Factor
QCommandLineParser m_parser
QCommandLineOption m_testOption
QCommandLineOption m_nbSamplesOption
QCommandLineOption m_repetitionOption
QCommandLineOption m_log2FactorOption
Detailed Description
Definition at line 25 of file parserbench.h.
Member Enumeration Documentation
TestType
enum ParserBench::TestType
Enumerator
TestDecimatorsII
TestDecimatorsIF
TestDecimatorsFI
TestDecimatorsFF
TestDecimatorsInfII
TestDecimatorsSupII
TestAMBE
Definition at line 28 of file parserbench.h.
     {
         TestDecimatorsII,
         TestDecimatorsIF,
         TestDecimatorsFI,
         TestDecimatorsFF,
         TestDecimatorsInfII,
         TestDecimatorsSupII,
         TestAMBE
     } TestType;
Constructor & Destructor Documentation
ParserBench()
ParserBench::ParserBench ()
Definition at line 25 of file parserbench.cpp.
References m_log2Factor, m_log2FactorOption, m_nbSamples, m_nbSamplesOption, m_parser, m_repetition, m_repetitionOption, m_testOption, and m_testStr.
                          :
     m_testOption(QStringList() << "t" << "test",
         "Test type: decimateii, decimatefi, decimateff, decimateif, decimateinfii, decimatesupii, ambe",
         "test",
         "decimateii"),
     m_nbSamplesOption(QStringList() << "n" << "nb-samples",
         "Number of sample to deal with.",
         "samples",
         "1048576"),
     m_repetitionOption(QStringList() << "r" << "repeat",
         "Number of repetitions.",
         "repetition",
         "1"),
     m_log2FactorOption(QStringList() << "l" << "log2-factor",
         "Log2 factor for rate conversion.",
         "log2",
         "2")
 {
     m_testStr = "decimateii";
     m_nbSamples = 1048576;
     m_repetition = 1;
     m_log2Factor = 4;
     m_parser.setApplicationDescription("Software Defined Radio application benchmarks");
     m_parser.addHelpOption();
     m_parser.addVersionOption();
     m_parser.addOption(m_testOption);
     m_parser.addOption(m_nbSamplesOption);
     m_parser.addOption(m_repetitionOption);
     m_parser.addOption(m_log2FactorOption);
 }
~ParserBench()
ParserBench::~ParserBench ()
Definition at line 58 of file parserbench.cpp.
 { }
Member Function Documentation
getLog2Factor()
uint32_t ParserBench::getLog2Factor () const inline
Definition at line 48 of file parserbench.h.
References m_log2Factor.
Referenced by MainBench::decimateFF(), MainBench::decimateFI(), MainBench::decimateIF(), MainBench::decimateII(), MainBench::decimateInfII(), MainBench::decimateSupII(), MainBench::run(), MainBench::testDecimateFF(), MainBench::testDecimateFI(), MainBench::testDecimateIF(), and MainBench::testDecimateII().
 { return m_log2Factor; }
getNbSamples()
uint32_t ParserBench::getNbSamples () const inline
Definition at line 46 of file parserbench.h.
References m_nbSamples.
Referenced by MainBench::printResults(), MainBench::run(), MainBench::testDecimateFF(), MainBench::testDecimateFI(), MainBench::testDecimateIF(), and MainBench::testDecimateII().
 { return m_nbSamples; }
getRepetition()
uint32_t ParserBench::getRepetition () const inline
Definition at line 47 of file parserbench.h.
References m_repetition.
Referenced by MainBench::printResults(), MainBench::run(), MainBench::testDecimateFF(), MainBench::testDecimateFI(), MainBench::testDecimateIF(), and MainBench::testDecimateII().
 { return m_repetition; }
getTestStr()
const QString& ParserBench::getTestStr () const inline
Definition at line 44 of file parserbench.h.
References getTestType(), and m_testStr.
Referenced by MainBench::run().
 { return m_testStr; }
getTestType()
ParserBench::TestType ParserBench::getTestType () const
Definition at line 116 of file parserbench.cpp.
References m_testStr, TestAMBE, TestDecimatorsFF, TestDecimatorsFI, TestDecimatorsIF, TestDecimatorsII, TestDecimatorsInfII, and TestDecimatorsSupII.
Referenced by getTestStr(), and MainBench::run().
 {
     if (m_testStr == "decimatefi") {
         return TestDecimatorsFI;
     } else if (m_testStr == "decimateff") {
         return TestDecimatorsFF;
     } else if (m_testStr == "decimateif") {
         return TestDecimatorsIF;
     } else if (m_testStr == "decimateinfii") {
         return TestDecimatorsInfII;
     } else if (m_testStr == "decimatesupii") {
         return TestDecimatorsSupII;
     } else if (m_testStr == "ambe") {
         return TestAMBE;
     } else {
         return TestDecimatorsII;
     }
 }
parse()
void ParserBench::parse (const QCoreApplication & app)
Definition at line 61 of file parserbench.cpp.
References m_log2Factor, m_log2FactorOption, m_nbSamples, m_nbSamplesOption, m_parser, m_repetition, m_repetitionOption, m_testOption, and m_testStr.
 {
     m_parser.process(app);
     int pos;
     bool ok;
     // test switch
     QString test = m_parser.value(m_testOption);
     QString testStr = "([a-z]+)";
     QRegExp ipRegex ("^" + testStr + "$");
     QRegExpValidator ipValidator(ipRegex);
     if (ipValidator.validate(test, pos) == QValidator::Acceptable) {
         m_testStr = test;
     } else {
         qWarning() << "ParserBench::parse: test string invalid. Defaulting to " << m_testStr;
     }
     // number of samples
     QString nbSamplesStr = m_parser.value(m_nbSamplesOption);
     int nbSamples = nbSamplesStr.toInt(&ok);
     if (ok && (nbSamples > 1024) && (nbSamples < 1073741824)) {
         m_nbSamples = nbSamples;
     } else {
         qWarning() << "ParserBench::parse: number of samples invalid. Defaulting to " << m_nbSamples;
     }
     // repetition
     QString repetitionStr = m_parser.value(m_repetitionOption);
     int repetition = repetitionStr.toInt(&ok);
     if (ok && (repetition >= 0)) {
         m_repetition = repetition;
     } else {
         qWarning() << "ParserBench::parse: repetition invalid. Defaulting to " << m_repetition;
     }
     // log2 factor
     QString log2FactorStr = m_parser.value(m_log2FactorOption);
     int log2Factor = log2FactorStr.toInt(&ok);
     if (ok && (log2Factor >= 0) && (log2Factor <= 6)) {
         m_log2Factor = log2Factor;
     } else {
         qWarning() << "ParserBench::parse: repetilog2 factortion invalid. Defaulting to " << m_log2Factor;
     }
 }
Member Data Documentation
m_log2Factor
uint32_t ParserBench::m_log2Factor private
Definition at line 54 of file parserbench.h.
Referenced by getLog2Factor(), parse(), and ParserBench().
m_log2FactorOption
QCommandLineOption ParserBench::m_log2FactorOption private
Definition at line 60 of file parserbench.h.
Referenced by parse(), and ParserBench().
m_nbSamples
uint32_t ParserBench::m_nbSamples private
Definition at line 52 of file parserbench.h.
Referenced by getNbSamples(), parse(), and ParserBench().
m_nbSamplesOption
QCommandLineOption ParserBench::m_nbSamplesOption private
Definition at line 58 of file parserbench.h.
Referenced by parse(), and ParserBench().
m_parser
QCommandLineParser ParserBench::m_parser private
Definition at line 56 of file parserbench.h.
Referenced by parse(), and ParserBench().
m_repetition
uint32_t ParserBench::m_repetition private
Definition at line 53 of file parserbench.h.
Referenced by getRepetition(), parse(), and ParserBench().
m_repetitionOption
QCommandLineOption ParserBench::m_repetitionOption private
Definition at line 59 of file parserbench.h.
Referenced by parse(), and ParserBench().
m_testOption
QCommandLineOption ParserBench::m_testOption private
Definition at line 57 of file parserbench.h.
Referenced by parse(), and ParserBench().
m_testStr
QString ParserBench::m_testStr private
Definition at line 51 of file parserbench.h.
Referenced by getTestStr(), getTestType(), parse(), and ParserBench().
The documentation for this class was generated from the following files:
sdrbench/parserbench.h
sdrbench/parserbench.cpp