SDRAngel: SWGSDRangel::SWGDeviceSettings Class Reference
SWGSDRangel::SWGDeviceSettings Class Reference
#include <SWGDeviceSettings.h>
Public Member Functions
SWGDeviceSettings ()
SWGDeviceSettings (QString *json)
virtual ~SWGDeviceSettings ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGDeviceSettings * fromJson (QString &jsonString) override
QString * getDeviceHwType ()
void setDeviceHwType (QString *device_hw_type)
qint32 getDirection ()
void setDirection (qint32 direction)
qint32 getOriginatorIndex ()
void setOriginatorIndex (qint32 originator_index)
SWGAirspySettings * getAirspySettings ()
void setAirspySettings (SWGAirspySettings *airspy_settings)
SWGAirspyHFSettings * getAirspyHfSettings ()
void setAirspyHfSettings (SWGAirspyHFSettings *airspy_hf_settings)
SWGBladeRF1InputSettings * getBladeRf1InputSettings ()
void setBladeRf1InputSettings (SWGBladeRF1InputSettings *blade_rf1_input_settings)
SWGBladeRF2InputSettings * getBladeRf2InputSettings ()
void setBladeRf2InputSettings (SWGBladeRF2InputSettings *blade_rf2_input_settings)
SWGBladeRF1OutputSettings * getBladeRf1OutputSettings ()
void setBladeRf1OutputSettings (SWGBladeRF1OutputSettings *blade_rf1_output_settings)
SWGBladeRF2OutputSettings * getBladeRf2OutputSettings ()
void setBladeRf2OutputSettings (SWGBladeRF2OutputSettings *blade_rf2_output_settings)
SWGFCDProSettings * getFcdProSettings ()
void setFcdProSettings (SWGFCDProSettings *fcd_pro_settings)
SWGFCDProPlusSettings * getFcdProPlusSettings ()
void setFcdProPlusSettings (SWGFCDProPlusSettings *fcd_pro_plus_settings)
SWGFileInputSettings * getFileInputSettings ()
void setFileInputSettings (SWGFileInputSettings *file_input_settings)
SWGHackRFInputSettings * getHackRfInputSettings ()
void setHackRfInputSettings (SWGHackRFInputSettings *hack_rf_input_settings)
SWGHackRFOutputSettings * getHackRfOutputSettings ()
void setHackRfOutputSettings (SWGHackRFOutputSettings *hack_rf_output_settings)
SWGKiwiSDRSettings * getKiwiSdrSettings ()
void setKiwiSdrSettings (SWGKiwiSDRSettings *kiwi_sdr_settings)
SWGLimeSdrInputSettings * getLimeSdrInputSettings ()
void setLimeSdrInputSettings (SWGLimeSdrInputSettings *lime_sdr_input_settings)
SWGLimeSdrOutputSettings * getLimeSdrOutputSettings ()
void setLimeSdrOutputSettings (SWGLimeSdrOutputSettings *lime_sdr_output_settings)
SWGLocalInputSettings * getLocalInputSettings ()
void setLocalInputSettings (SWGLocalInputSettings *local_input_settings)
SWGLocalOutputSettings * getLocalOutputSettings ()
void setLocalOutputSettings (SWGLocalOutputSettings *local_output_settings)
SWGPerseusSettings * getPerseusSettings ()
void setPerseusSettings (SWGPerseusSettings *perseus_settings)
SWGPlutoSdrInputSettings * getPlutoSdrInputSettings ()
void setPlutoSdrInputSettings (SWGPlutoSdrInputSettings *pluto_sdr_input_settings)
SWGPlutoSdrOutputSettings * getPlutoSdrOutputSettings ()
void setPlutoSdrOutputSettings (SWGPlutoSdrOutputSettings *pluto_sdr_output_settings)
SWGRtlSdrSettings * getRtlSdrSettings ()
void setRtlSdrSettings (SWGRtlSdrSettings *rtl_sdr_settings)
SWGRemoteOutputSettings * getRemoteOutputSettings ()
void setRemoteOutputSettings (SWGRemoteOutputSettings *remote_output_settings)
SWGRemoteInputSettings * getRemoteInputSettings ()
void setRemoteInputSettings (SWGRemoteInputSettings *remote_input_settings)
SWGSDRPlaySettings * getSdrPlaySettings ()
void setSdrPlaySettings (SWGSDRPlaySettings *sdr_play_settings)
SWGSoapySDRInputSettings * getSoapySdrInputSettings ()
void setSoapySdrInputSettings (SWGSoapySDRInputSettings *soapy_sdr_input_settings)
SWGSoapySDROutputSettings * getSoapySdrOutputSettings ()
void setSoapySdrOutputSettings (SWGSoapySDROutputSettings *soapy_sdr_output_settings)
SWGTestSourceSettings * getTestSourceSettings ()
void setTestSourceSettings (SWGTestSourceSettings *test_source_settings)
SWGTestMISettings * getTestMiSettings ()
void setTestMiSettings (SWGTestMISettings *test_mi_settings)
SWGXtrxInputSettings * getXtrxInputSettings ()
void setXtrxInputSettings (SWGXtrxInputSettings *xtrx_input_settings)
SWGXtrxOutputSettings * getXtrxOutputSettings ()
void setXtrxOutputSettings (SWGXtrxOutputSettings *xtrx_output_settings)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * device_hw_type
bool m_device_hw_type_isSet
qint32 direction
bool m_direction_isSet
qint32 originator_index
bool m_originator_index_isSet
SWGAirspySettings * airspy_settings
bool m_airspy_settings_isSet
SWGAirspyHFSettings * airspy_hf_settings
bool m_airspy_hf_settings_isSet
SWGBladeRF1InputSettings * blade_rf1_input_settings
bool m_blade_rf1_input_settings_isSet
SWGBladeRF2InputSettings * blade_rf2_input_settings
bool m_blade_rf2_input_settings_isSet
SWGBladeRF1OutputSettings * blade_rf1_output_settings
bool m_blade_rf1_output_settings_isSet
SWGBladeRF2OutputSettings * blade_rf2_output_settings
bool m_blade_rf2_output_settings_isSet
SWGFCDProSettings * fcd_pro_settings
bool m_fcd_pro_settings_isSet
SWGFCDProPlusSettings * fcd_pro_plus_settings
bool m_fcd_pro_plus_settings_isSet
SWGFileInputSettings * file_input_settings
bool m_file_input_settings_isSet
SWGHackRFInputSettings * hack_rf_input_settings
bool m_hack_rf_input_settings_isSet
SWGHackRFOutputSettings * hack_rf_output_settings
bool m_hack_rf_output_settings_isSet
SWGKiwiSDRSettings * kiwi_sdr_settings
bool m_kiwi_sdr_settings_isSet
SWGLimeSdrInputSettings * lime_sdr_input_settings
bool m_lime_sdr_input_settings_isSet
SWGLimeSdrOutputSettings * lime_sdr_output_settings
bool m_lime_sdr_output_settings_isSet
SWGLocalInputSettings * local_input_settings
bool m_local_input_settings_isSet
SWGLocalOutputSettings * local_output_settings
bool m_local_output_settings_isSet
SWGPerseusSettings * perseus_settings
bool m_perseus_settings_isSet
SWGPlutoSdrInputSettings * pluto_sdr_input_settings
bool m_pluto_sdr_input_settings_isSet
SWGPlutoSdrOutputSettings * pluto_sdr_output_settings
bool m_pluto_sdr_output_settings_isSet
SWGRtlSdrSettings * rtl_sdr_settings
bool m_rtl_sdr_settings_isSet
SWGRemoteOutputSettings * remote_output_settings
bool m_remote_output_settings_isSet
SWGRemoteInputSettings * remote_input_settings
bool m_remote_input_settings_isSet
SWGSDRPlaySettings * sdr_play_settings
bool m_sdr_play_settings_isSet
SWGSoapySDRInputSettings * soapy_sdr_input_settings
bool m_soapy_sdr_input_settings_isSet
SWGSoapySDROutputSettings * soapy_sdr_output_settings
bool m_soapy_sdr_output_settings_isSet
SWGTestSourceSettings * test_source_settings
bool m_test_source_settings_isSet
SWGTestMISettings * test_mi_settings
bool m_test_mi_settings_isSet
SWGXtrxInputSettings * xtrx_input_settings
bool m_xtrx_input_settings_isSet
SWGXtrxOutputSettings * xtrx_output_settings
bool m_xtrx_output_settings_isSet
Detailed Description
Definition at line 61 of file SWGDeviceSettings.h.
Constructor & Destructor Documentation
SWGDeviceSettings() [1/2]
SWGSDRangel::SWGDeviceSettings::SWGDeviceSettings ()
Definition at line 30 of file SWGDeviceSettings.cpp.
References airspy_hf_settings, airspy_settings, blade_rf1_input_settings, blade_rf1_output_settings, blade_rf2_input_settings, blade_rf2_output_settings, device_hw_type, direction, fcd_pro_plus_settings, fcd_pro_settings, file_input_settings, hack_rf_input_settings, hack_rf_output_settings, kiwi_sdr_settings, lime_sdr_input_settings, lime_sdr_output_settings, local_input_settings, local_output_settings, m_airspy_hf_settings_isSet, m_airspy_settings_isSet, m_blade_rf1_input_settings_isSet, m_blade_rf1_output_settings_isSet, m_blade_rf2_input_settings_isSet, m_blade_rf2_output_settings_isSet, m_device_hw_type_isSet, m_direction_isSet, m_fcd_pro_plus_settings_isSet, m_fcd_pro_settings_isSet, m_file_input_settings_isSet, m_hack_rf_input_settings_isSet, m_hack_rf_output_settings_isSet, m_kiwi_sdr_settings_isSet, m_lime_sdr_input_settings_isSet, m_lime_sdr_output_settings_isSet, m_local_input_settings_isSet, m_local_output_settings_isSet, m_originator_index_isSet, m_perseus_settings_isSet, m_pluto_sdr_input_settings_isSet, m_pluto_sdr_output_settings_isSet, m_remote_input_settings_isSet, m_remote_output_settings_isSet, m_rtl_sdr_settings_isSet, m_sdr_play_settings_isSet, m_soapy_sdr_input_settings_isSet, m_soapy_sdr_output_settings_isSet, m_test_mi_settings_isSet, m_test_source_settings_isSet, m_xtrx_input_settings_isSet, m_xtrx_output_settings_isSet, originator_index, perseus_settings, pluto_sdr_input_settings, pluto_sdr_output_settings, remote_input_settings, remote_output_settings, rtl_sdr_settings, sdr_play_settings, soapy_sdr_input_settings, soapy_sdr_output_settings, test_mi_settings, test_source_settings, xtrx_input_settings, and xtrx_output_settings.
{
     device_hw_type = nullptr;
     m_device_hw_type_isSet = false;
     direction = 0;
     m_direction_isSet = false;
     originator_index = 0;
     m_originator_index_isSet = false;
     airspy_settings = nullptr;
     m_airspy_settings_isSet = false;
     airspy_hf_settings = nullptr;
     m_airspy_hf_settings_isSet = false;
     blade_rf1_input_settings = nullptr;
     m_blade_rf1_input_settings_isSet = false;
     blade_rf2_input_settings = nullptr;
     m_blade_rf2_input_settings_isSet = false;
     blade_rf1_output_settings = nullptr;
     m_blade_rf1_output_settings_isSet = false;
     blade_rf2_output_settings = nullptr;
     m_blade_rf2_output_settings_isSet = false;
     fcd_pro_settings = nullptr;
     m_fcd_pro_settings_isSet = false;
     fcd_pro_plus_settings = nullptr;
     m_fcd_pro_plus_settings_isSet = false;
     file_input_settings = nullptr;
     m_file_input_settings_isSet = false;
     hack_rf_input_settings = nullptr;
     m_hack_rf_input_settings_isSet = false;
     hack_rf_output_settings = nullptr;
     m_hack_rf_output_settings_isSet = false;
     kiwi_sdr_settings = nullptr;
     m_kiwi_sdr_settings_isSet = false;
     lime_sdr_input_settings = nullptr;
     m_lime_sdr_input_settings_isSet = false;
     lime_sdr_output_settings = nullptr;
     m_lime_sdr_output_settings_isSet = false;
     local_input_settings = nullptr;
     m_local_input_settings_isSet = false;
     local_output_settings = nullptr;
     m_local_output_settings_isSet = false;
     perseus_settings = nullptr;
     m_perseus_settings_isSet = false;
     pluto_sdr_input_settings = nullptr;
     m_pluto_sdr_input_settings_isSet = false;
     pluto_sdr_output_settings = nullptr;
     m_pluto_sdr_output_settings_isSet = false;
     rtl_sdr_settings = nullptr;
     m_rtl_sdr_settings_isSet = false;
     remote_output_settings = nullptr;
     m_remote_output_settings_isSet = false;
     remote_input_settings = nullptr;
     m_remote_input_settings_isSet = false;
     sdr_play_settings = nullptr;
     m_sdr_play_settings_isSet = false;
     soapy_sdr_input_settings = nullptr;
     m_soapy_sdr_input_settings_isSet = false;
     soapy_sdr_output_settings = nullptr;
     m_soapy_sdr_output_settings_isSet = false;
     test_source_settings = nullptr;
     m_test_source_settings_isSet = false;
     test_mi_settings = nullptr;
     m_test_mi_settings_isSet = false;
     xtrx_input_settings = nullptr;
     m_xtrx_input_settings_isSet = false;
     xtrx_output_settings = nullptr;
     m_xtrx_output_settings_isSet = false;
 }
SWGDeviceSettings() [2/2]
SWGSDRangel::SWGDeviceSettings::SWGDeviceSettings (QString * json)
Definition at line 25 of file SWGDeviceSettings.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGDeviceSettings()
SWGSDRangel::SWGDeviceSettings::~SWGDeviceSettings () virtual
Definition at line 97 of file SWGDeviceSettings.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGDeviceSettings::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 343 of file SWGDeviceSettings.cpp.
References asJsonObject().
Referenced by SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunDelete(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunPost(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPatch(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPut(), WebAPIRequestMapper::devicesetDeviceSettingsService(), TestSourceInput::webapiReverseSendSettings(), PlutoSDROutput::webapiReverseSendSettings(), Bladerf1Output::webapiReverseSendSettings(), HackRFOutput::webapiReverseSendSettings(), Bladerf1Input::webapiReverseSendSettings(), PerseusInput::webapiReverseSendSettings(), LocalOutput::webapiReverseSendSettings(), AirspyInput::webapiReverseSendSettings(), AirspyHFInput::webapiReverseSendSettings(), TestMI::webapiReverseSendSettings(), RTLSDRInput::webapiReverseSendSettings(), PlutoSDRInput::webapiReverseSendSettings(), FCDProPlusInput::webapiReverseSendSettings(), HackRFInput::webapiReverseSendSettings(), BladeRF2Output::webapiReverseSendSettings(), KiwiSDRInput::webapiReverseSendSettings(), LocalInput::webapiReverseSendSettings(), FCDProInput::webapiReverseSendSettings(), RemoteOutput::webapiReverseSendSettings(), SDRPlayInput::webapiReverseSendSettings(), BladeRF2Input::webapiReverseSendSettings(), SoapySDROutput::webapiReverseSendSettings(), SoapySDRInput::webapiReverseSendSettings(), XTRXOutput::webapiReverseSendSettings(), LimeSDROutput::webapiReverseSendSettings(), XTRXInput::webapiReverseSendSettings(), LimeSDRInput::webapiReverseSendSettings(), RemoteInput::webapiReverseSendSettings(), FileInput::webapiReverseSendSettings(), Bladerf1Output::webapiReverseSendStartStop(), TestSourceInput::webapiReverseSendStartStop(), PlutoSDROutput::webapiReverseSendStartStop(), HackRFOutput::webapiReverseSendStartStop(), Bladerf1Input::webapiReverseSendStartStop(), PerseusInput::webapiReverseSendStartStop(), LocalOutput::webapiReverseSendStartStop(), AirspyInput::webapiReverseSendStartStop(), TestMI::webapiReverseSendStartStop(), AirspyHFInput::webapiReverseSendStartStop(), RTLSDRInput::webapiReverseSendStartStop(), PlutoSDRInput::webapiReverseSendStartStop(), FCDProPlusInput::webapiReverseSendStartStop(), HackRFInput::webapiReverseSendStartStop(), BladeRF2Output::webapiReverseSendStartStop(), KiwiSDRInput::webapiReverseSendStartStop(), LocalInput::webapiReverseSendStartStop(), FCDProInput::webapiReverseSendStartStop(), RemoteOutput::webapiReverseSendStartStop(), SDRPlayInput::webapiReverseSendStartStop(), BladeRF2Input::webapiReverseSendStartStop(), SoapySDROutput::webapiReverseSendStartStop(), SoapySDRInput::webapiReverseSendStartStop(), XTRXOutput::webapiReverseSendStartStop(), LimeSDROutput::webapiReverseSendStartStop(), XTRXInput::webapiReverseSendStartStop(), LimeSDRInput::webapiReverseSendStartStop(), RemoteInput::webapiReverseSendStartStop(), and FileInput::webapiReverseSendStartStop().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGDeviceSettings::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 354 of file SWGDeviceSettings.cpp.
References airspy_hf_settings, airspy_settings, blade_rf1_input_settings, blade_rf1_output_settings, blade_rf2_input_settings, blade_rf2_output_settings, device_hw_type, direction, fcd_pro_plus_settings, fcd_pro_settings, file_input_settings, hack_rf_input_settings, hack_rf_output_settings, SWGSDRangel::SWGLocalOutputSettings::isSet(), SWGSDRangel::SWGTestMISettings::isSet(), SWGSDRangel::SWGLocalInputSettings::isSet(), SWGSDRangel::SWGFileInputSettings::isSet(), SWGSDRangel::SWGKiwiSDRSettings::isSet(), SWGSDRangel::SWGRemoteInputSettings::isSet(), SWGSDRangel::SWGBladeRF1OutputSettings::isSet(), SWGSDRangel::SWGBladeRF2OutputSettings::isSet(), SWGSDRangel::SWGHackRFOutputSettings::isSet(), SWGSDRangel::SWGRemoteOutputSettings::isSet(), SWGSDRangel::SWGPerseusSettings::isSet(), SWGSDRangel::SWGXtrxOutputSettings::isSet(), SWGSDRangel::SWGPlutoSdrOutputSettings::isSet(), SWGSDRangel::SWGHackRFInputSettings::isSet(), SWGSDRangel::SWGBladeRF1InputSettings::isSet(), SWGSDRangel::SWGBladeRF2InputSettings::isSet(), SWGSDRangel::SWGAirspyHFSettings::isSet(), SWGSDRangel::SWGRtlSdrSettings::isSet(), SWGSDRangel::SWGSDRPlaySettings::isSet(), SWGSDRangel::SWGAirspySettings::isSet(), SWGSDRangel::SWGFCDProPlusSettings::isSet(), SWGSDRangel::SWGLimeSdrOutputSettings::isSet(), SWGSDRangel::SWGTestSourceSettings::isSet(), SWGSDRangel::SWGSoapySDROutputSettings::isSet(), SWGSDRangel::SWGXtrxInputSettings::isSet(), SWGSDRangel::SWGPlutoSdrInputSettings::isSet(), SWGSDRangel::SWGSoapySDRInputSettings::isSet(), SWGSDRangel::SWGLimeSdrInputSettings::isSet(), SWGSDRangel::SWGFCDProSettings::isSet(), kiwi_sdr_settings, lime_sdr_input_settings, lime_sdr_output_settings, local_input_settings, local_output_settings, m_direction_isSet, m_originator_index_isSet, originator_index, perseus_settings, pluto_sdr_input_settings, pluto_sdr_output_settings, remote_input_settings, remote_output_settings, rtl_sdr_settings, sdr_play_settings, soapy_sdr_input_settings, soapy_sdr_output_settings, test_mi_settings, test_source_settings, SWGSDRangel::toJsonValue(), xtrx_input_settings, and xtrx_output_settings.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(device_hw_type != nullptr && *device_hw_type != QString("")){
         toJsonValue(QString("deviceHwType"), device_hw_type, obj, QString("QString"));
     }
     if(m_direction_isSet){
         obj->insert("direction", QJsonValue(direction));
     }
     if(m_originator_index_isSet){
         obj->insert("originatorIndex", QJsonValue(originator_index));
     }
     if((airspy_settings != nullptr) && (airspy_settings->isSet())){
         toJsonValue(QString("airspySettings"), airspy_settings, obj, QString("SWGAirspySettings"));
     }
     if((airspy_hf_settings != nullptr) && (airspy_hf_settings->isSet())){
         toJsonValue(QString("airspyHFSettings"), airspy_hf_settings, obj, QString("SWGAirspyHFSettings"));
     }
     if((blade_rf1_input_settings != nullptr) && (blade_rf1_input_settings->isSet())){
         toJsonValue(QString("bladeRF1InputSettings"), blade_rf1_input_settings, obj, QString("SWGBladeRF1InputSettings"));
     }
     if((blade_rf2_input_settings != nullptr) && (blade_rf2_input_settings->isSet())){
         toJsonValue(QString("bladeRF2InputSettings"), blade_rf2_input_settings, obj, QString("SWGBladeRF2InputSettings"));
     }
     if((blade_rf1_output_settings != nullptr) && (blade_rf1_output_settings->isSet())){
         toJsonValue(QString("bladeRF1OutputSettings"), blade_rf1_output_settings, obj, QString("SWGBladeRF1OutputSettings"));
     }
     if((blade_rf2_output_settings != nullptr) && (blade_rf2_output_settings->isSet())){
         toJsonValue(QString("bladeRF2OutputSettings"), blade_rf2_output_settings, obj, QString("SWGBladeRF2OutputSettings"));
     }
     if((fcd_pro_settings != nullptr) && (fcd_pro_settings->isSet())){
         toJsonValue(QString("fcdProSettings"), fcd_pro_settings, obj, QString("SWGFCDProSettings"));
     }
     if((fcd_pro_plus_settings != nullptr) && (fcd_pro_plus_settings->isSet())){
         toJsonValue(QString("fcdProPlusSettings"), fcd_pro_plus_settings, obj, QString("SWGFCDProPlusSettings"));
     }
     if((file_input_settings != nullptr) && (file_input_settings->isSet())){
         toJsonValue(QString("fileInputSettings"), file_input_settings, obj, QString("SWGFileInputSettings"));
     }
     if((hack_rf_input_settings != nullptr) && (hack_rf_input_settings->isSet())){
         toJsonValue(QString("hackRFInputSettings"), hack_rf_input_settings, obj, QString("SWGHackRFInputSettings"));
     }
     if((hack_rf_output_settings != nullptr) && (hack_rf_output_settings->isSet())){
         toJsonValue(QString("hackRFOutputSettings"), hack_rf_output_settings, obj, QString("SWGHackRFOutputSettings"));
     }
     if((kiwi_sdr_settings != nullptr) && (kiwi_sdr_settings->isSet())){
         toJsonValue(QString("kiwiSDRSettings"), kiwi_sdr_settings, obj, QString("SWGKiwiSDRSettings"));
     }
     if((lime_sdr_input_settings != nullptr) && (lime_sdr_input_settings->isSet())){
         toJsonValue(QString("limeSdrInputSettings"), lime_sdr_input_settings, obj, QString("SWGLimeSdrInputSettings"));
     }
     if((lime_sdr_output_settings != nullptr) && (lime_sdr_output_settings->isSet())){
         toJsonValue(QString("limeSdrOutputSettings"), lime_sdr_output_settings, obj, QString("SWGLimeSdrOutputSettings"));
     }
     if((local_input_settings != nullptr) && (local_input_settings->isSet())){
         toJsonValue(QString("localInputSettings"), local_input_settings, obj, QString("SWGLocalInputSettings"));
     }
     if((local_output_settings != nullptr) && (local_output_settings->isSet())){
         toJsonValue(QString("localOutputSettings"), local_output_settings, obj, QString("SWGLocalOutputSettings"));
     }
     if((perseus_settings != nullptr) && (perseus_settings->isSet())){
         toJsonValue(QString("perseusSettings"), perseus_settings, obj, QString("SWGPerseusSettings"));
     }
     if((pluto_sdr_input_settings != nullptr) && (pluto_sdr_input_settings->isSet())){
         toJsonValue(QString("plutoSdrInputSettings"), pluto_sdr_input_settings, obj, QString("SWGPlutoSdrInputSettings"));
     }
     if((pluto_sdr_output_settings != nullptr) && (pluto_sdr_output_settings->isSet())){
         toJsonValue(QString("plutoSdrOutputSettings"), pluto_sdr_output_settings, obj, QString("SWGPlutoSdrOutputSettings"));
     }
     if((rtl_sdr_settings != nullptr) && (rtl_sdr_settings->isSet())){
         toJsonValue(QString("rtlSdrSettings"), rtl_sdr_settings, obj, QString("SWGRtlSdrSettings"));
     }
     if((remote_output_settings != nullptr) && (remote_output_settings->isSet())){
         toJsonValue(QString("remoteOutputSettings"), remote_output_settings, obj, QString("SWGRemoteOutputSettings"));
     }
     if((remote_input_settings != nullptr) && (remote_input_settings->isSet())){
         toJsonValue(QString("remoteInputSettings"), remote_input_settings, obj, QString("SWGRemoteInputSettings"));
     }
     if((sdr_play_settings != nullptr) && (sdr_play_settings->isSet())){
         toJsonValue(QString("sdrPlaySettings"), sdr_play_settings, obj, QString("SWGSDRPlaySettings"));
     }
     if((soapy_sdr_input_settings != nullptr) && (soapy_sdr_input_settings->isSet())){
         toJsonValue(QString("soapySDRInputSettings"), soapy_sdr_input_settings, obj, QString("SWGSoapySDRInputSettings"));
     }
     if((soapy_sdr_output_settings != nullptr) && (soapy_sdr_output_settings->isSet())){
         toJsonValue(QString("soapySDROutputSettings"), soapy_sdr_output_settings, obj, QString("SWGSoapySDROutputSettings"));
     }
     if((test_source_settings != nullptr) && (test_source_settings->isSet())){
         toJsonValue(QString("testSourceSettings"), test_source_settings, obj, QString("SWGTestSourceSettings"));
     }
     if((test_mi_settings != nullptr) && (test_mi_settings->isSet())){
         toJsonValue(QString("testMISettings"), test_mi_settings, obj, QString("SWGTestMISettings"));
     }
     if((xtrx_input_settings != nullptr) && (xtrx_input_settings->isSet())){
         toJsonValue(QString("xtrxInputSettings"), xtrx_input_settings, obj, QString("SWGXtrxInputSettings"));
     }
     if((xtrx_output_settings != nullptr) && (xtrx_output_settings->isSet())){
         toJsonValue(QString("xtrxOutputSettings"), xtrx_output_settings, obj, QString("SWGXtrxOutputSettings"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGDeviceSettings::cleanup ()
Definition at line 170 of file SWGDeviceSettings.cpp.
References airspy_hf_settings, airspy_settings, blade_rf1_input_settings, blade_rf1_output_settings, blade_rf2_input_settings, blade_rf2_output_settings, device_hw_type, fcd_pro_plus_settings, fcd_pro_settings, file_input_settings, hack_rf_input_settings, hack_rf_output_settings, kiwi_sdr_settings, lime_sdr_input_settings, lime_sdr_output_settings, local_input_settings, local_output_settings, perseus_settings, pluto_sdr_input_settings, pluto_sdr_output_settings, remote_input_settings, remote_output_settings, rtl_sdr_settings, sdr_play_settings, soapy_sdr_input_settings, soapy_sdr_output_settings, test_mi_settings, test_source_settings, xtrx_input_settings, and xtrx_output_settings.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), and ~SWGDeviceSettings().
{
     if(device_hw_type != nullptr) {
         delete device_hw_type;
     }
     if(airspy_settings != nullptr) {
         delete airspy_settings;
     }
     if(airspy_hf_settings != nullptr) {
         delete airspy_hf_settings;
     }
     if(blade_rf1_input_settings != nullptr) {
         delete blade_rf1_input_settings;
     }
     if(blade_rf2_input_settings != nullptr) {
         delete blade_rf2_input_settings;
     }
     if(blade_rf1_output_settings != nullptr) {
         delete blade_rf1_output_settings;
     }
     if(blade_rf2_output_settings != nullptr) {
         delete blade_rf2_output_settings;
     }
     if(fcd_pro_settings != nullptr) {
         delete fcd_pro_settings;
     }
     if(fcd_pro_plus_settings != nullptr) {
         delete fcd_pro_plus_settings;
     }
     if(file_input_settings != nullptr) {
         delete file_input_settings;
     }
     if(hack_rf_input_settings != nullptr) {
         delete hack_rf_input_settings;
     }
     if(hack_rf_output_settings != nullptr) {
         delete hack_rf_output_settings;
     }
     if(kiwi_sdr_settings != nullptr) {
         delete kiwi_sdr_settings;
     }
     if(lime_sdr_input_settings != nullptr) {
         delete lime_sdr_input_settings;
     }
     if(lime_sdr_output_settings != nullptr) {
         delete lime_sdr_output_settings;
     }
     if(local_input_settings != nullptr) {
         delete local_input_settings;
     }
     if(local_output_settings != nullptr) {
         delete local_output_settings;
     }
     if(perseus_settings != nullptr) {
         delete perseus_settings;
     }
     if(pluto_sdr_input_settings != nullptr) {
         delete pluto_sdr_input_settings;
     }
     if(pluto_sdr_output_settings != nullptr) {
         delete pluto_sdr_output_settings;
     }
     if(rtl_sdr_settings != nullptr) {
         delete rtl_sdr_settings;
     }
     if(remote_output_settings != nullptr) {
         delete remote_output_settings;
     }
     if(remote_input_settings != nullptr) {
         delete remote_input_settings;
     }
     if(sdr_play_settings != nullptr) {
         delete sdr_play_settings;
     }
     if(soapy_sdr_input_settings != nullptr) {
         delete soapy_sdr_input_settings;
     }
     if(soapy_sdr_output_settings != nullptr) {
         delete soapy_sdr_output_settings;
     }
     if(test_source_settings != nullptr) {
         delete test_source_settings;
     }
     if(test_mi_settings != nullptr) {
         delete test_mi_settings;
     }
     if(xtrx_input_settings != nullptr) {
         delete xtrx_input_settings;
     }
     if(xtrx_output_settings != nullptr) {
         delete xtrx_output_settings;
     }
 }
fromJson()
SWGDeviceSettings * SWGSDRangel::SWGDeviceSettings::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 266 of file SWGDeviceSettings.cpp.
References fromJsonObject().
Referenced by SWGDeviceSettings().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGDeviceSettings::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 275 of file SWGDeviceSettings.cpp.
References airspy_hf_settings, airspy_settings, blade_rf1_input_settings, blade_rf1_output_settings, blade_rf2_input_settings, blade_rf2_output_settings, device_hw_type, direction, fcd_pro_plus_settings, fcd_pro_settings, file_input_settings, hack_rf_input_settings, hack_rf_output_settings, kiwi_sdr_settings, lime_sdr_input_settings, lime_sdr_output_settings, local_input_settings, local_output_settings, originator_index, perseus_settings, pluto_sdr_input_settings, pluto_sdr_output_settings, remote_input_settings, remote_output_settings, rtl_sdr_settings, sdr_play_settings, SWGSDRangel::setValue(), soapy_sdr_input_settings, soapy_sdr_output_settings, test_mi_settings, test_source_settings, xtrx_input_settings, and xtrx_output_settings.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&device_hw_type, pJson["deviceHwType"], "QString", "QString");
     ::SWGSDRangel::setValue(&direction, pJson["direction"], "qint32", "");
     ::SWGSDRangel::setValue(&originator_index, pJson["originatorIndex"], "qint32", "");
     ::SWGSDRangel::setValue(&airspy_settings, pJson["airspySettings"], "SWGAirspySettings", "SWGAirspySettings");
     ::SWGSDRangel::setValue(&airspy_hf_settings, pJson["airspyHFSettings"], "SWGAirspyHFSettings", "SWGAirspyHFSettings");
     ::SWGSDRangel::setValue(&blade_rf1_input_settings, pJson["bladeRF1InputSettings"], "SWGBladeRF1InputSettings", "SWGBladeRF1InputSettings");
     ::SWGSDRangel::setValue(&blade_rf2_input_settings, pJson["bladeRF2InputSettings"], "SWGBladeRF2InputSettings", "SWGBladeRF2InputSettings");
     ::SWGSDRangel::setValue(&blade_rf1_output_settings, pJson["bladeRF1OutputSettings"], "SWGBladeRF1OutputSettings", "SWGBladeRF1OutputSettings");
     ::SWGSDRangel::setValue(&blade_rf2_output_settings, pJson["bladeRF2OutputSettings"], "SWGBladeRF2OutputSettings", "SWGBladeRF2OutputSettings");
     ::SWGSDRangel::setValue(&fcd_pro_settings, pJson["fcdProSettings"], "SWGFCDProSettings", "SWGFCDProSettings");
     ::SWGSDRangel::setValue(&fcd_pro_plus_settings, pJson["fcdProPlusSettings"], "SWGFCDProPlusSettings", "SWGFCDProPlusSettings");
     ::SWGSDRangel::setValue(&file_input_settings, pJson["fileInputSettings"], "SWGFileInputSettings", "SWGFileInputSettings");
     ::SWGSDRangel::setValue(&hack_rf_input_settings, pJson["hackRFInputSettings"], "SWGHackRFInputSettings", "SWGHackRFInputSettings");
     ::SWGSDRangel::setValue(&hack_rf_output_settings, pJson["hackRFOutputSettings"], "SWGHackRFOutputSettings", "SWGHackRFOutputSettings");
     ::SWGSDRangel::setValue(&kiwi_sdr_settings, pJson["kiwiSDRSettings"], "SWGKiwiSDRSettings", "SWGKiwiSDRSettings");
     ::SWGSDRangel::setValue(&lime_sdr_input_settings, pJson["limeSdrInputSettings"], "SWGLimeSdrInputSettings", "SWGLimeSdrInputSettings");
     ::SWGSDRangel::setValue(&lime_sdr_output_settings, pJson["limeSdrOutputSettings"], "SWGLimeSdrOutputSettings", "SWGLimeSdrOutputSettings");
     ::SWGSDRangel::setValue(&local_input_settings, pJson["localInputSettings"], "SWGLocalInputSettings", "SWGLocalInputSettings");
     ::SWGSDRangel::setValue(&local_output_settings, pJson["localOutputSettings"], "SWGLocalOutputSettings", "SWGLocalOutputSettings");
     ::SWGSDRangel::setValue(&perseus_settings, pJson["perseusSettings"], "SWGPerseusSettings", "SWGPerseusSettings");
     ::SWGSDRangel::setValue(&pluto_sdr_input_settings, pJson["plutoSdrInputSettings"], "SWGPlutoSdrInputSettings", "SWGPlutoSdrInputSettings");
     ::SWGSDRangel::setValue(&pluto_sdr_output_settings, pJson["plutoSdrOutputSettings"], "SWGPlutoSdrOutputSettings", "SWGPlutoSdrOutputSettings");
     ::SWGSDRangel::setValue(&rtl_sdr_settings, pJson["rtlSdrSettings"], "SWGRtlSdrSettings", "SWGRtlSdrSettings");
     ::SWGSDRangel::setValue(&remote_output_settings, pJson["remoteOutputSettings"], "SWGRemoteOutputSettings", "SWGRemoteOutputSettings");
     ::SWGSDRangel::setValue(&remote_input_settings, pJson["remoteInputSettings"], "SWGRemoteInputSettings", "SWGRemoteInputSettings");
     ::SWGSDRangel::setValue(&sdr_play_settings, pJson["sdrPlaySettings"], "SWGSDRPlaySettings", "SWGSDRPlaySettings");
     ::SWGSDRangel::setValue(&soapy_sdr_input_settings, pJson["soapySDRInputSettings"], "SWGSoapySDRInputSettings", "SWGSoapySDRInputSettings");
     ::SWGSDRangel::setValue(&soapy_sdr_output_settings, pJson["soapySDROutputSettings"], "SWGSoapySDROutputSettings", "SWGSoapySDROutputSettings");
     ::SWGSDRangel::setValue(&test_source_settings, pJson["testSourceSettings"], "SWGTestSourceSettings", "SWGTestSourceSettings");
     ::SWGSDRangel::setValue(&test_mi_settings, pJson["testMISettings"], "SWGTestMISettings", "SWGTestMISettings");
     ::SWGSDRangel::setValue(&xtrx_input_settings, pJson["xtrxInputSettings"], "SWGXtrxInputSettings", "SWGXtrxInputSettings");
     ::SWGSDRangel::setValue(&xtrx_output_settings, pJson["xtrxOutputSettings"], "SWGXtrxOutputSettings", "SWGXtrxOutputSettings");
 }
getAirspyHfSettings()
SWGAirspyHFSettings * SWGSDRangel::SWGDeviceSettings::getAirspyHfSettings ()
Definition at line 497 of file SWGDeviceSettings.cpp.
References airspy_hf_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), AirspyHFInput::webapiFormatDeviceSettings(), AirspyHFInput::webapiReverseSendSettings(), AirspyHFInput::webapiSettingsGet(), and AirspyHFInput::webapiSettingsPutPatch().
{
     return airspy_hf_settings;
 }
getAirspySettings()
SWGAirspySettings * SWGSDRangel::SWGDeviceSettings::getAirspySettings ()
Definition at line 487 of file SWGDeviceSettings.cpp.
References airspy_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), AirspyInput::webapiFormatDeviceSettings(), AirspyInput::webapiReverseSendSettings(), AirspyInput::webapiSettingsGet(), and AirspyInput::webapiSettingsPutPatch().
{
     return airspy_settings;
 }
getBladeRf1InputSettings()
SWGBladeRF1InputSettings * SWGSDRangel::SWGDeviceSettings::getBladeRf1InputSettings ()
Definition at line 507 of file SWGDeviceSettings.cpp.
References blade_rf1_input_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), Bladerf1Input::webapiFormatDeviceSettings(), Bladerf1Input::webapiReverseSendSettings(), Bladerf1Input::webapiSettingsGet(), and Bladerf1Input::webapiSettingsPutPatch().
{
     return blade_rf1_input_settings;
 }
getBladeRf1OutputSettings()
SWGBladeRF1OutputSettings * SWGSDRangel::SWGDeviceSettings::getBladeRf1OutputSettings ()
Definition at line 527 of file SWGDeviceSettings.cpp.
References blade_rf1_output_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), Bladerf1Output::webapiFormatDeviceSettings(), Bladerf1Output::webapiReverseSendSettings(), Bladerf1Output::webapiSettingsGet(), and Bladerf1Output::webapiSettingsPutPatch().
{
     return blade_rf1_output_settings;
 }
getBladeRf2InputSettings()
SWGBladeRF2InputSettings * SWGSDRangel::SWGDeviceSettings::getBladeRf2InputSettings ()
Definition at line 517 of file SWGDeviceSettings.cpp.
References blade_rf2_input_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), BladeRF2Input::webapiFormatDeviceSettings(), BladeRF2Input::webapiReverseSendSettings(), BladeRF2Input::webapiSettingsGet(), and BladeRF2Input::webapiSettingsPutPatch().
{
     return blade_rf2_input_settings;
 }
getBladeRf2OutputSettings()
SWGBladeRF2OutputSettings * SWGSDRangel::SWGDeviceSettings::getBladeRf2OutputSettings ()
Definition at line 537 of file SWGDeviceSettings.cpp.
References blade_rf2_output_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), BladeRF2Output::webapiFormatDeviceSettings(), BladeRF2Output::webapiReverseSendSettings(), BladeRF2Output::webapiSettingsGet(), and BladeRF2Output::webapiSettingsPutPatch().
{
     return blade_rf2_output_settings;
 }
getDeviceHwType()
QString * SWGSDRangel::SWGDeviceSettings::getDeviceHwType ()
Definition at line 457 of file SWGDeviceSettings.cpp.
References device_hw_type.
Referenced by WebAPIAdapterGUI::devicesetDeviceSettingsPutPatch(), WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch(), and WebAPIRequestMapper::validateDeviceSettings().
{
     return device_hw_type;
 }
getDirection()
qint32 SWGSDRangel::SWGDeviceSettings::getDirection ()
Definition at line 467 of file SWGDeviceSettings.cpp.
References direction.
Referenced by WebAPIAdapterGUI::devicesetDeviceSettingsPutPatch(), WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch(), and WebAPIRequestMapper::validateDeviceSettings().
{
     return direction;
 }
getFcdProPlusSettings()
SWGFCDProPlusSettings * SWGSDRangel::SWGDeviceSettings::getFcdProPlusSettings ()
Definition at line 557 of file SWGDeviceSettings.cpp.
References fcd_pro_plus_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), FCDProPlusInput::webapiFormatDeviceSettings(), FCDProPlusInput::webapiReverseSendSettings(), FCDProPlusInput::webapiSettingsGet(), and FCDProPlusInput::webapiSettingsPutPatch().
{
     return fcd_pro_plus_settings;
 }
getFcdProSettings()
SWGFCDProSettings * SWGSDRangel::SWGDeviceSettings::getFcdProSettings ()
Definition at line 547 of file SWGDeviceSettings.cpp.
References fcd_pro_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), FCDProInput::webapiFormatDeviceSettings(), FCDProInput::webapiReverseSendSettings(), FCDProInput::webapiSettingsGet(), and FCDProInput::webapiSettingsPutPatch().
{
     return fcd_pro_settings;
 }
getFileInputSettings()
SWGFileInputSettings * SWGSDRangel::SWGDeviceSettings::getFileInputSettings ()
Definition at line 567 of file SWGDeviceSettings.cpp.
References file_input_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), FileInput::webapiFormatDeviceSettings(), FileInput::webapiReverseSendSettings(), FileInput::webapiSettingsGet(), and FileInput::webapiSettingsPutPatch().
{
     return file_input_settings;
 }
getHackRfInputSettings()
SWGHackRFInputSettings * SWGSDRangel::SWGDeviceSettings::getHackRfInputSettings ()
Definition at line 577 of file SWGDeviceSettings.cpp.
References hack_rf_input_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), HackRFInput::webapiFormatDeviceSettings(), HackRFInput::webapiReverseSendSettings(), HackRFInput::webapiSettingsGet(), and HackRFInput::webapiSettingsPutPatch().
{
     return hack_rf_input_settings;
 }
getHackRfOutputSettings()
SWGHackRFOutputSettings * SWGSDRangel::SWGDeviceSettings::getHackRfOutputSettings ()
Definition at line 587 of file SWGDeviceSettings.cpp.
References hack_rf_output_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), HackRFOutput::webapiFormatDeviceSettings(), HackRFOutput::webapiReverseSendSettings(), HackRFOutput::webapiSettingsGet(), and HackRFOutput::webapiSettingsPutPatch().
{
     return hack_rf_output_settings;
 }
getKiwiSdrSettings()
SWGKiwiSDRSettings * SWGSDRangel::SWGDeviceSettings::getKiwiSdrSettings ()
Definition at line 597 of file SWGDeviceSettings.cpp.
References kiwi_sdr_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), KiwiSDRInput::webapiFormatDeviceSettings(), KiwiSDRInput::webapiReverseSendSettings(), KiwiSDRInput::webapiSettingsGet(), and KiwiSDRInput::webapiSettingsPutPatch().
{
     return kiwi_sdr_settings;
 }
getLimeSdrInputSettings()
SWGLimeSdrInputSettings * SWGSDRangel::SWGDeviceSettings::getLimeSdrInputSettings ()
Definition at line 607 of file SWGDeviceSettings.cpp.
References lime_sdr_input_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), LimeSDRInput::webapiFormatDeviceSettings(), LimeSDRInput::webapiReverseSendSettings(), LimeSDRInput::webapiSettingsGet(), and LimeSDRInput::webapiSettingsPutPatch().
{
     return lime_sdr_input_settings;
 }
getLimeSdrOutputSettings()
SWGLimeSdrOutputSettings * SWGSDRangel::SWGDeviceSettings::getLimeSdrOutputSettings ()
Definition at line 617 of file SWGDeviceSettings.cpp.
References lime_sdr_output_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), LimeSDROutput::webapiFormatDeviceSettings(), LimeSDROutput::webapiReverseSendSettings(), LimeSDROutput::webapiSettingsGet(), and LimeSDROutput::webapiSettingsPutPatch().
{
     return lime_sdr_output_settings;
 }
getLocalInputSettings()
SWGLocalInputSettings * SWGSDRangel::SWGDeviceSettings::getLocalInputSettings ()
Definition at line 627 of file SWGDeviceSettings.cpp.
References local_input_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), LocalInput::webapiFormatDeviceSettings(), LocalInput::webapiReverseSendSettings(), LocalInput::webapiSettingsGet(), and LocalInput::webapiSettingsPutPatch().
{
     return local_input_settings;
 }
getLocalOutputSettings()
SWGLocalOutputSettings * SWGSDRangel::SWGDeviceSettings::getLocalOutputSettings ()
Definition at line 637 of file SWGDeviceSettings.cpp.
References local_output_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), LocalOutput::webapiFormatDeviceSettings(), LocalOutput::webapiSettingsGet(), and LocalOutput::webapiSettingsPutPatch().
{
     return local_output_settings;
 }
getOriginatorIndex()
qint32 SWGSDRangel::SWGDeviceSettings::getOriginatorIndex ()
Definition at line 477 of file SWGDeviceSettings.cpp.
References originator_index.
{
     return originator_index;
 }
getPerseusSettings()
SWGPerseusSettings * SWGSDRangel::SWGDeviceSettings::getPerseusSettings ()
Definition at line 647 of file SWGDeviceSettings.cpp.
References perseus_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), PerseusInput::webapiFormatDeviceSettings(), PerseusInput::webapiReverseSendSettings(), PerseusInput::webapiSettingsGet(), and PerseusInput::webapiSettingsPutPatch().
{
     return perseus_settings;
 }
getPlutoSdrInputSettings()
SWGPlutoSdrInputSettings * SWGSDRangel::SWGDeviceSettings::getPlutoSdrInputSettings ()
Definition at line 657 of file SWGDeviceSettings.cpp.
References pluto_sdr_input_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), PlutoSDRInput::webapiFormatDeviceSettings(), PlutoSDRInput::webapiReverseSendSettings(), PlutoSDRInput::webapiSettingsGet(), and PlutoSDRInput::webapiSettingsPutPatch().
{
     return pluto_sdr_input_settings;
 }
getPlutoSdrOutputSettings()
SWGPlutoSdrOutputSettings * SWGSDRangel::SWGDeviceSettings::getPlutoSdrOutputSettings ()
Definition at line 667 of file SWGDeviceSettings.cpp.
References pluto_sdr_output_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), PlutoSDROutput::webapiFormatDeviceSettings(), PlutoSDROutput::webapiReverseSendSettings(), PlutoSDROutput::webapiSettingsGet(), and PlutoSDROutput::webapiSettingsPutPatch().
{
     return pluto_sdr_output_settings;
 }
getRemoteInputSettings()
SWGRemoteInputSettings * SWGSDRangel::SWGDeviceSettings::getRemoteInputSettings ()
Definition at line 697 of file SWGDeviceSettings.cpp.
References remote_input_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), RemoteInput::webapiFormatDeviceSettings(), RemoteInput::webapiReverseSendSettings(), RemoteInput::webapiSettingsGet(), and RemoteInput::webapiSettingsPutPatch().
{
     return remote_input_settings;
 }
getRemoteOutputSettings()
SWGRemoteOutputSettings * SWGSDRangel::SWGDeviceSettings::getRemoteOutputSettings ()
Definition at line 687 of file SWGDeviceSettings.cpp.
References remote_output_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), RemoteOutput::webapiFormatDeviceSettings(), RemoteOutput::webapiReverseSendSettings(), RemoteOutput::webapiSettingsGet(), and RemoteOutput::webapiSettingsPutPatch().
{
     return remote_output_settings;
 }
getRtlSdrSettings()
SWGRtlSdrSettings * SWGSDRangel::SWGDeviceSettings::getRtlSdrSettings ()
Definition at line 677 of file SWGDeviceSettings.cpp.
References rtl_sdr_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), RTLSDRInput::webapiFormatDeviceSettings(), RTLSDRInput::webapiReverseSendSettings(), RTLSDRInput::webapiSettingsGet(), and RTLSDRInput::webapiSettingsPutPatch().
{
     return rtl_sdr_settings;
 }
getSdrPlaySettings()
SWGSDRPlaySettings * SWGSDRangel::SWGDeviceSettings::getSdrPlaySettings ()
Definition at line 707 of file SWGDeviceSettings.cpp.
References sdr_play_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), SDRPlayInput::webapiFormatDeviceSettings(), SDRPlayInput::webapiReverseSendSettings(), SDRPlayInput::webapiSettingsGet(), and SDRPlayInput::webapiSettingsPutPatch().
{
     return sdr_play_settings;
 }
getSoapySdrInputSettings()
SWGSoapySDRInputSettings * SWGSDRangel::SWGDeviceSettings::getSoapySdrInputSettings ()
Definition at line 717 of file SWGDeviceSettings.cpp.
References soapy_sdr_input_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), SoapySDRInput::webapiFormatDeviceSettings(), SoapySDRInput::webapiReverseSendSettings(), SoapySDRInput::webapiSettingsGet(), and SoapySDRInput::webapiSettingsPutPatch().
{
     return soapy_sdr_input_settings;
 }
getSoapySdrOutputSettings()
SWGSoapySDROutputSettings * SWGSDRangel::SWGDeviceSettings::getSoapySdrOutputSettings ()
Definition at line 727 of file SWGDeviceSettings.cpp.
References soapy_sdr_output_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), SoapySDROutput::webapiFormatDeviceSettings(), SoapySDROutput::webapiReverseSendSettings(), SoapySDROutput::webapiSettingsGet(), and SoapySDROutput::webapiSettingsPutPatch().
{
     return soapy_sdr_output_settings;
 }
getTestMiSettings()
SWGTestMISettings * SWGSDRangel::SWGDeviceSettings::getTestMiSettings ()
Definition at line 747 of file SWGDeviceSettings.cpp.
References test_mi_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), TestMI::webapiFormatDeviceSettings(), TestMI::webapiReverseSendSettings(), TestMI::webapiSettingsGet(), and TestMI::webapiSettingsPutPatch().
{
     return test_mi_settings;
 }
getTestSourceSettings()
SWGTestSourceSettings * SWGSDRangel::SWGDeviceSettings::getTestSourceSettings ()
Definition at line 737 of file SWGDeviceSettings.cpp.
References test_source_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), TestSourceInput::webapiFormatDeviceSettings(), TestSourceInput::webapiReverseSendSettings(), TestSourceInput::webapiSettingsGet(), and TestSourceInput::webapiSettingsPutPatch().
{
     return test_source_settings;
 }
getXtrxInputSettings()
SWGXtrxInputSettings * SWGSDRangel::SWGDeviceSettings::getXtrxInputSettings ()
Definition at line 757 of file SWGDeviceSettings.cpp.
References xtrx_input_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), XTRXInput::webapiFormatDeviceSettings(), XTRXInput::webapiReverseSendSettings(), XTRXInput::webapiSettingsGet(), and XTRXInput::webapiSettingsPutPatch().
{
     return xtrx_input_settings;
 }
getXtrxOutputSettings()
SWGXtrxOutputSettings * SWGSDRangel::SWGDeviceSettings::getXtrxOutputSettings ()
Definition at line 767 of file SWGDeviceSettings.cpp.
References xtrx_output_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), XTRXOutput::webapiFormatDeviceSettings(), XTRXOutput::webapiReverseSendSettings(), XTRXOutput::webapiSettingsGet(), and XTRXOutput::webapiSettingsPutPatch().
{
     return xtrx_output_settings;
 }
init()
void SWGSDRangel::SWGDeviceSettings::init ()
Definition at line 102 of file SWGDeviceSettings.cpp.
References airspy_hf_settings, airspy_settings, blade_rf1_input_settings, blade_rf1_output_settings, blade_rf2_input_settings, blade_rf2_output_settings, device_hw_type, direction, fcd_pro_plus_settings, fcd_pro_settings, file_input_settings, hack_rf_input_settings, hack_rf_output_settings, kiwi_sdr_settings, lime_sdr_input_settings, lime_sdr_output_settings, local_input_settings, local_output_settings, m_airspy_hf_settings_isSet, m_airspy_settings_isSet, m_blade_rf1_input_settings_isSet, m_blade_rf1_output_settings_isSet, m_blade_rf2_input_settings_isSet, m_blade_rf2_output_settings_isSet, m_device_hw_type_isSet, m_direction_isSet, m_fcd_pro_plus_settings_isSet, m_fcd_pro_settings_isSet, m_file_input_settings_isSet, m_hack_rf_input_settings_isSet, m_hack_rf_output_settings_isSet, m_kiwi_sdr_settings_isSet, m_lime_sdr_input_settings_isSet, m_lime_sdr_output_settings_isSet, m_local_input_settings_isSet, m_local_output_settings_isSet, m_originator_index_isSet, m_perseus_settings_isSet, m_pluto_sdr_input_settings_isSet, m_pluto_sdr_output_settings_isSet, m_remote_input_settings_isSet, m_remote_output_settings_isSet, m_rtl_sdr_settings_isSet, m_sdr_play_settings_isSet, m_soapy_sdr_input_settings_isSet, m_soapy_sdr_output_settings_isSet, m_test_mi_settings_isSet, m_test_source_settings_isSet, m_xtrx_input_settings_isSet, m_xtrx_output_settings_isSet, originator_index, perseus_settings, pluto_sdr_input_settings, pluto_sdr_output_settings, remote_input_settings, remote_output_settings, rtl_sdr_settings, sdr_play_settings, soapy_sdr_input_settings, soapy_sdr_output_settings, test_mi_settings, test_source_settings, xtrx_input_settings, and xtrx_output_settings.
Referenced by SWGDeviceSettings().
{
     device_hw_type = new QString("");
     m_device_hw_type_isSet = false;
     direction = 0;
     m_direction_isSet = false;
     originator_index = 0;
     m_originator_index_isSet = false;
     airspy_settings = new SWGAirspySettings();
     m_airspy_settings_isSet = false;
     airspy_hf_settings = new SWGAirspyHFSettings();
     m_airspy_hf_settings_isSet = false;
     blade_rf1_input_settings = new SWGBladeRF1InputSettings();
     m_blade_rf1_input_settings_isSet = false;
     blade_rf2_input_settings = new SWGBladeRF2InputSettings();
     m_blade_rf2_input_settings_isSet = false;
     blade_rf1_output_settings = new SWGBladeRF1OutputSettings();
     m_blade_rf1_output_settings_isSet = false;
     blade_rf2_output_settings = new SWGBladeRF2OutputSettings();
     m_blade_rf2_output_settings_isSet = false;
     fcd_pro_settings = new SWGFCDProSettings();
     m_fcd_pro_settings_isSet = false;
     fcd_pro_plus_settings = new SWGFCDProPlusSettings();
     m_fcd_pro_plus_settings_isSet = false;
     file_input_settings = new SWGFileInputSettings();
     m_file_input_settings_isSet = false;
     hack_rf_input_settings = new SWGHackRFInputSettings();
     m_hack_rf_input_settings_isSet = false;
     hack_rf_output_settings = new SWGHackRFOutputSettings();
     m_hack_rf_output_settings_isSet = false;
     kiwi_sdr_settings = new SWGKiwiSDRSettings();
     m_kiwi_sdr_settings_isSet = false;
     lime_sdr_input_settings = new SWGLimeSdrInputSettings();
     m_lime_sdr_input_settings_isSet = false;
     lime_sdr_output_settings = new SWGLimeSdrOutputSettings();
     m_lime_sdr_output_settings_isSet = false;
     local_input_settings = new SWGLocalInputSettings();
     m_local_input_settings_isSet = false;
     local_output_settings = new SWGLocalOutputSettings();
     m_local_output_settings_isSet = false;
     perseus_settings = new SWGPerseusSettings();
     m_perseus_settings_isSet = false;
     pluto_sdr_input_settings = new SWGPlutoSdrInputSettings();
     m_pluto_sdr_input_settings_isSet = false;
     pluto_sdr_output_settings = new SWGPlutoSdrOutputSettings();
     m_pluto_sdr_output_settings_isSet = false;
     rtl_sdr_settings = new SWGRtlSdrSettings();
     m_rtl_sdr_settings_isSet = false;
     remote_output_settings = new SWGRemoteOutputSettings();
     m_remote_output_settings_isSet = false;
     remote_input_settings = new SWGRemoteInputSettings();
     m_remote_input_settings_isSet = false;
     sdr_play_settings = new SWGSDRPlaySettings();
     m_sdr_play_settings_isSet = false;
     soapy_sdr_input_settings = new SWGSoapySDRInputSettings();
     m_soapy_sdr_input_settings_isSet = false;
     soapy_sdr_output_settings = new SWGSoapySDROutputSettings();
     m_soapy_sdr_output_settings_isSet = false;
     test_source_settings = new SWGTestSourceSettings();
     m_test_source_settings_isSet = false;
     test_mi_settings = new SWGTestMISettings();
     m_test_mi_settings_isSet = false;
     xtrx_input_settings = new SWGXtrxInputSettings();
     m_xtrx_input_settings_isSet = false;
     xtrx_output_settings = new SWGXtrxOutputSettings();
     m_xtrx_output_settings_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGDeviceSettings::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 778 of file SWGDeviceSettings.cpp.
References airspy_hf_settings, airspy_settings, blade_rf1_input_settings, blade_rf1_output_settings, blade_rf2_input_settings, blade_rf2_output_settings, device_hw_type, fcd_pro_plus_settings, fcd_pro_settings, file_input_settings, hack_rf_input_settings, hack_rf_output_settings, SWGSDRangel::SWGLocalOutputSettings::isSet(), SWGSDRangel::SWGTestMISettings::isSet(), SWGSDRangel::SWGLocalInputSettings::isSet(), SWGSDRangel::SWGFileInputSettings::isSet(), SWGSDRangel::SWGKiwiSDRSettings::isSet(), SWGSDRangel::SWGRemoteInputSettings::isSet(), SWGSDRangel::SWGHackRFOutputSettings::isSet(), SWGSDRangel::SWGBladeRF1OutputSettings::isSet(), SWGSDRangel::SWGBladeRF2OutputSettings::isSet(), SWGSDRangel::SWGRemoteOutputSettings::isSet(), SWGSDRangel::SWGPerseusSettings::isSet(), SWGSDRangel::SWGXtrxOutputSettings::isSet(), SWGSDRangel::SWGPlutoSdrOutputSettings::isSet(), SWGSDRangel::SWGHackRFInputSettings::isSet(), SWGSDRangel::SWGBladeRF1InputSettings::isSet(), SWGSDRangel::SWGBladeRF2InputSettings::isSet(), SWGSDRangel::SWGAirspyHFSettings::isSet(), SWGSDRangel::SWGFCDProPlusSettings::isSet(), SWGSDRangel::SWGAirspySettings::isSet(), SWGSDRangel::SWGRtlSdrSettings::isSet(), SWGSDRangel::SWGSDRPlaySettings::isSet(), SWGSDRangel::SWGTestSourceSettings::isSet(), SWGSDRangel::SWGLimeSdrOutputSettings::isSet(), SWGSDRangel::SWGSoapySDROutputSettings::isSet(), SWGSDRangel::SWGXtrxInputSettings::isSet(), SWGSDRangel::SWGPlutoSdrInputSettings::isSet(), SWGSDRangel::SWGSoapySDRInputSettings::isSet(), SWGSDRangel::SWGLimeSdrInputSettings::isSet(), SWGSDRangel::SWGFCDProSettings::isSet(), kiwi_sdr_settings, lime_sdr_input_settings, lime_sdr_output_settings, local_input_settings, local_output_settings, m_direction_isSet, m_originator_index_isSet, perseus_settings, pluto_sdr_input_settings, pluto_sdr_output_settings, remote_input_settings, remote_output_settings, rtl_sdr_settings, sdr_play_settings, soapy_sdr_input_settings, soapy_sdr_output_settings, test_mi_settings, test_source_settings, xtrx_input_settings, and xtrx_output_settings.
{
     bool isObjectUpdated = false;
     do{
         if(device_hw_type != nullptr && *device_hw_type != QString("")){ isObjectUpdated = true; break;}
         if(m_direction_isSet){ isObjectUpdated = true; break;}
         if(m_originator_index_isSet){ isObjectUpdated = true; break;}
         if(airspy_settings != nullptr && airspy_settings->isSet()){ isObjectUpdated = true; break;}
         if(airspy_hf_settings != nullptr && airspy_hf_settings->isSet()){ isObjectUpdated = true; break;}
         if(blade_rf1_input_settings != nullptr && blade_rf1_input_settings->isSet()){ isObjectUpdated = true; break;}
         if(blade_rf2_input_settings != nullptr && blade_rf2_input_settings->isSet()){ isObjectUpdated = true; break;}
         if(blade_rf1_output_settings != nullptr && blade_rf1_output_settings->isSet()){ isObjectUpdated = true; break;}
         if(blade_rf2_output_settings != nullptr && blade_rf2_output_settings->isSet()){ isObjectUpdated = true; break;}
         if(fcd_pro_settings != nullptr && fcd_pro_settings->isSet()){ isObjectUpdated = true; break;}
         if(fcd_pro_plus_settings != nullptr && fcd_pro_plus_settings->isSet()){ isObjectUpdated = true; break;}
         if(file_input_settings != nullptr && file_input_settings->isSet()){ isObjectUpdated = true; break;}
         if(hack_rf_input_settings != nullptr && hack_rf_input_settings->isSet()){ isObjectUpdated = true; break;}
         if(hack_rf_output_settings != nullptr && hack_rf_output_settings->isSet()){ isObjectUpdated = true; break;}
         if(kiwi_sdr_settings != nullptr && kiwi_sdr_settings->isSet()){ isObjectUpdated = true; break;}
         if(lime_sdr_input_settings != nullptr && lime_sdr_input_settings->isSet()){ isObjectUpdated = true; break;}
         if(lime_sdr_output_settings != nullptr && lime_sdr_output_settings->isSet()){ isObjectUpdated = true; break;}
         if(local_input_settings != nullptr && local_input_settings->isSet()){ isObjectUpdated = true; break;}
         if(local_output_settings != nullptr && local_output_settings->isSet()){ isObjectUpdated = true; break;}
         if(perseus_settings != nullptr && perseus_settings->isSet()){ isObjectUpdated = true; break;}
         if(pluto_sdr_input_settings != nullptr && pluto_sdr_input_settings->isSet()){ isObjectUpdated = true; break;}
         if(pluto_sdr_output_settings != nullptr && pluto_sdr_output_settings->isSet()){ isObjectUpdated = true; break;}
         if(rtl_sdr_settings != nullptr && rtl_sdr_settings->isSet()){ isObjectUpdated = true; break;}
         if(remote_output_settings != nullptr && remote_output_settings->isSet()){ isObjectUpdated = true; break;}
         if(remote_input_settings != nullptr && remote_input_settings->isSet()){ isObjectUpdated = true; break;}
         if(sdr_play_settings != nullptr && sdr_play_settings->isSet()){ isObjectUpdated = true; break;}
         if(soapy_sdr_input_settings != nullptr && soapy_sdr_input_settings->isSet()){ isObjectUpdated = true; break;}
         if(soapy_sdr_output_settings != nullptr && soapy_sdr_output_settings->isSet()){ isObjectUpdated = true; break;}
         if(test_source_settings != nullptr && test_source_settings->isSet()){ isObjectUpdated = true; break;}
         if(test_mi_settings != nullptr && test_mi_settings->isSet()){ isObjectUpdated = true; break;}
         if(xtrx_input_settings != nullptr && xtrx_input_settings->isSet()){ isObjectUpdated = true; break;}
         if(xtrx_output_settings != nullptr && xtrx_output_settings->isSet()){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setAirspyHfSettings()
void SWGSDRangel::SWGDeviceSettings::setAirspyHfSettings (SWGAirspyHFSettings * airspy_hf_settings)
Definition at line 501 of file SWGDeviceSettings.cpp.
References airspy_hf_settings, and m_airspy_hf_settings_isSet.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), AirspyHFInput::webapiReverseSendSettings(), and AirspyHFInput::webapiSettingsGet().
{
     this->airspy_hf_settings = airspy_hf_settings;
     this->m_airspy_hf_settings_isSet = true;
 }
setAirspySettings()
void SWGSDRangel::SWGDeviceSettings::setAirspySettings (SWGAirspySettings * airspy_settings)
Definition at line 491 of file SWGDeviceSettings.cpp.
References airspy_settings, and m_airspy_settings_isSet.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), AirspyInput::webapiReverseSendSettings(), and AirspyInput::webapiSettingsGet().
{
     this->airspy_settings = airspy_settings;
     this->m_airspy_settings_isSet = true;
 }
setBladeRf1InputSettings()
void SWGSDRangel::SWGDeviceSettings::setBladeRf1InputSettings (SWGBladeRF1InputSettings * blade_rf1_input_settings)
Definition at line 511 of file SWGDeviceSettings.cpp.
References blade_rf1_input_settings, and m_blade_rf1_input_settings_isSet.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), Bladerf1Input::webapiReverseSendSettings(), and Bladerf1Input::webapiSettingsGet().
{
     this->blade_rf1_input_settings = blade_rf1_input_settings;
     this->m_blade_rf1_input_settings_isSet = true;
 }
setBladeRf1OutputSettings()
void SWGSDRangel::SWGDeviceSettings::setBladeRf1OutputSettings (SWGBladeRF1OutputSettings * blade_rf1_output_settings)
Definition at line 531 of file SWGDeviceSettings.cpp.
References blade_rf1_output_settings, and m_blade_rf1_output_settings_isSet.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), Bladerf1Output::webapiReverseSendSettings(), and Bladerf1Output::webapiSettingsGet().
{
     this->blade_rf1_output_settings = blade_rf1_output_settings;
     this->m_blade_rf1_output_settings_isSet = true;
 }
setBladeRf2InputSettings()
void SWGSDRangel::SWGDeviceSettings::setBladeRf2InputSettings (SWGBladeRF2InputSettings * blade_rf2_input_settings)
Definition at line 521 of file SWGDeviceSettings.cpp.
References blade_rf2_input_settings, and m_blade_rf2_input_settings_isSet.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), BladeRF2Input::webapiReverseSendSettings(), and BladeRF2Input::webapiSettingsGet().
{
     this->blade_rf2_input_settings = blade_rf2_input_settings;
     this->m_blade_rf2_input_settings_isSet = true;
 }
setBladeRf2OutputSettings()
void SWGSDRangel::SWGDeviceSettings::setBladeRf2OutputSettings (SWGBladeRF2OutputSettings * blade_rf2_output_settings)
Definition at line 541 of file SWGDeviceSettings.cpp.
References blade_rf2_output_settings, and m_blade_rf2_output_settings_isSet.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), BladeRF2Output::webapiReverseSendSettings(), and BladeRF2Output::webapiSettingsGet().
{
     this->blade_rf2_output_settings = blade_rf2_output_settings;
     this->m_blade_rf2_output_settings_isSet = true;
 }
setDeviceHwType()
void SWGSDRangel::SWGDeviceSettings::setDeviceHwType (QString * device_hw_type)
Definition at line 461 of file SWGDeviceSettings.cpp.
References device_hw_type, and m_device_hw_type_isSet.
Referenced by WebAPIAdapterGUI::devicesetDeviceSettingsGet(), WebAPIAdapterSrv::devicesetDeviceSettingsGet(), WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), TestSourceInput::webapiReverseSendSettings(), PlutoSDROutput::webapiReverseSendSettings(), Bladerf1Output::webapiReverseSendSettings(), HackRFOutput::webapiReverseSendSettings(), Bladerf1Input::webapiReverseSendSettings(), PerseusInput::webapiReverseSendSettings(), LocalOutput::webapiReverseSendSettings(), AirspyInput::webapiReverseSendSettings(), AirspyHFInput::webapiReverseSendSettings(), TestMI::webapiReverseSendSettings(), RTLSDRInput::webapiReverseSendSettings(), PlutoSDRInput::webapiReverseSendSettings(), FCDProPlusInput::webapiReverseSendSettings(), HackRFInput::webapiReverseSendSettings(), BladeRF2Output::webapiReverseSendSettings(), KiwiSDRInput::webapiReverseSendSettings(), LocalInput::webapiReverseSendSettings(), FCDProInput::webapiReverseSendSettings(), RemoteOutput::webapiReverseSendSettings(), SDRPlayInput::webapiReverseSendSettings(), BladeRF2Input::webapiReverseSendSettings(), SoapySDROutput::webapiReverseSendSettings(), SoapySDRInput::webapiReverseSendSettings(), XTRXOutput::webapiReverseSendSettings(), LimeSDROutput::webapiReverseSendSettings(), XTRXInput::webapiReverseSendSettings(), LimeSDRInput::webapiReverseSendSettings(), RemoteInput::webapiReverseSendSettings(), FileInput::webapiReverseSendSettings(), Bladerf1Output::webapiReverseSendStartStop(), TestSourceInput::webapiReverseSendStartStop(), PlutoSDROutput::webapiReverseSendStartStop(), HackRFOutput::webapiReverseSendStartStop(), Bladerf1Input::webapiReverseSendStartStop(), PerseusInput::webapiReverseSendStartStop(), LocalOutput::webapiReverseSendStartStop(), AirspyInput::webapiReverseSendStartStop(), TestMI::webapiReverseSendStartStop(), AirspyHFInput::webapiReverseSendStartStop(), RTLSDRInput::webapiReverseSendStartStop(), PlutoSDRInput::webapiReverseSendStartStop(), FCDProPlusInput::webapiReverseSendStartStop(), HackRFInput::webapiReverseSendStartStop(), BladeRF2Output::webapiReverseSendStartStop(), KiwiSDRInput::webapiReverseSendStartStop(), LocalInput::webapiReverseSendStartStop(), FCDProInput::webapiReverseSendStartStop(), RemoteOutput::webapiReverseSendStartStop(), SDRPlayInput::webapiReverseSendStartStop(), BladeRF2Input::webapiReverseSendStartStop(), SoapySDROutput::webapiReverseSendStartStop(), SoapySDRInput::webapiReverseSendStartStop(), XTRXOutput::webapiReverseSendStartStop(), LimeSDROutput::webapiReverseSendStartStop(), XTRXInput::webapiReverseSendStartStop(), LimeSDRInput::webapiReverseSendStartStop(), RemoteInput::webapiReverseSendStartStop(), and FileInput::webapiReverseSendStartStop().
{
     this->device_hw_type = device_hw_type;
     this->m_device_hw_type_isSet = true;
 }
setDirection()
void SWGSDRangel::SWGDeviceSettings::setDirection (qint32 direction)
Definition at line 471 of file SWGDeviceSettings.cpp.
References direction, and m_direction_isSet.
Referenced by WebAPIAdapterGUI::devicesetDeviceSettingsGet(), WebAPIAdapterSrv::devicesetDeviceSettingsGet(), WebAPIRequestMapper::validateDeviceSettings(), TestSourceInput::webapiReverseSendSettings(), Bladerf1Output::webapiReverseSendSettings(), PlutoSDROutput::webapiReverseSendSettings(), HackRFOutput::webapiReverseSendSettings(), Bladerf1Input::webapiReverseSendSettings(), PerseusInput::webapiReverseSendSettings(), LocalOutput::webapiReverseSendSettings(), AirspyInput::webapiReverseSendSettings(), AirspyHFInput::webapiReverseSendSettings(), TestMI::webapiReverseSendSettings(), RTLSDRInput::webapiReverseSendSettings(), PlutoSDRInput::webapiReverseSendSettings(), FCDProPlusInput::webapiReverseSendSettings(), HackRFInput::webapiReverseSendSettings(), BladeRF2Output::webapiReverseSendSettings(), KiwiSDRInput::webapiReverseSendSettings(), LocalInput::webapiReverseSendSettings(), FCDProInput::webapiReverseSendSettings(), RemoteOutput::webapiReverseSendSettings(), SDRPlayInput::webapiReverseSendSettings(), BladeRF2Input::webapiReverseSendSettings(), SoapySDROutput::webapiReverseSendSettings(), SoapySDRInput::webapiReverseSendSettings(), XTRXOutput::webapiReverseSendSettings(), LimeSDROutput::webapiReverseSendSettings(), XTRXInput::webapiReverseSendSettings(), LimeSDRInput::webapiReverseSendSettings(), RemoteInput::webapiReverseSendSettings(), FileInput::webapiReverseSendSettings(), Bladerf1Output::webapiReverseSendStartStop(), TestSourceInput::webapiReverseSendStartStop(), PlutoSDROutput::webapiReverseSendStartStop(), HackRFOutput::webapiReverseSendStartStop(), Bladerf1Input::webapiReverseSendStartStop(), PerseusInput::webapiReverseSendStartStop(), LocalOutput::webapiReverseSendStartStop(), AirspyInput::webapiReverseSendStartStop(), TestMI::webapiReverseSendStartStop(), AirspyHFInput::webapiReverseSendStartStop(), RTLSDRInput::webapiReverseSendStartStop(), PlutoSDRInput::webapiReverseSendStartStop(), FCDProPlusInput::webapiReverseSendStartStop(), HackRFInput::webapiReverseSendStartStop(), BladeRF2Output::webapiReverseSendStartStop(), KiwiSDRInput::webapiReverseSendStartStop(), LocalInput::webapiReverseSendStartStop(), FCDProInput::webapiReverseSendStartStop(), RemoteOutput::webapiReverseSendStartStop(), SDRPlayInput::webapiReverseSendStartStop(), BladeRF2Input::webapiReverseSendStartStop(), SoapySDROutput::webapiReverseSendStartStop(), SoapySDRInput::webapiReverseSendStartStop(), XTRXOutput::webapiReverseSendStartStop(), LimeSDROutput::webapiReverseSendStartStop(), XTRXInput::webapiReverseSendStartStop(), LimeSDRInput::webapiReverseSendStartStop(), RemoteInput::webapiReverseSendStartStop(), and FileInput::webapiReverseSendStartStop().
{
     this->direction = direction;
     this->m_direction_isSet = true;
 }
setFcdProPlusSettings()
void SWGSDRangel::SWGDeviceSettings::setFcdProPlusSettings (SWGFCDProPlusSettings * fcd_pro_plus_settings)
Definition at line 561 of file SWGDeviceSettings.cpp.
References fcd_pro_plus_settings, and m_fcd_pro_plus_settings_isSet.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), FCDProPlusInput::webapiReverseSendSettings(), and FCDProPlusInput::webapiSettingsGet().
{
     this->fcd_pro_plus_settings = fcd_pro_plus_settings;
     this->m_fcd_pro_plus_settings_isSet = true;
 }
setFcdProSettings()
void SWGSDRangel::SWGDeviceSettings::setFcdProSettings (SWGFCDProSettings * fcd_pro_settings)
Definition at line 551 of file SWGDeviceSettings.cpp.
References fcd_pro_settings, and m_fcd_pro_settings_isSet.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), FCDProInput::webapiReverseSendSettings(), and FCDProInput::webapiSettingsGet().
{
     this->fcd_pro_settings = fcd_pro_settings;
     this->m_fcd_pro_settings_isSet = true;
 }
setFileInputSettings()
void SWGSDRangel::SWGDeviceSettings::setFileInputSettings (SWGFileInputSettings * file_input_settings)
Definition at line 571 of file SWGDeviceSettings.cpp.
References file_input_settings, and m_file_input_settings_isSet.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), FileInput::webapiReverseSendSettings(), and FileInput::webapiSettingsGet().
{
     this->file_input_settings = file_input_settings;
     this->m_file_input_settings_isSet = true;
 }
setHackRfInputSettings()
void SWGSDRangel::SWGDeviceSettings::setHackRfInputSettings (SWGHackRFInputSettings * hack_rf_input_settings)
Definition at line 581 of file SWGDeviceSettings.cpp.
References hack_rf_input_settings, and m_hack_rf_input_settings_isSet.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), HackRFInput::webapiReverseSendSettings(), and HackRFInput::webapiSettingsGet().
{
     this->hack_rf_input_settings = hack_rf_input_settings;
     this->m_hack_rf_input_settings_isSet = true;
 }
setHackRfOutputSettings()
void SWGSDRangel::SWGDeviceSettings::setHackRfOutputSettings (SWGHackRFOutputSettings * hack_rf_output_settings)
Definition at line 591 of file SWGDeviceSettings.cpp.
References hack_rf_output_settings, and m_hack_rf_output_settings_isSet.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), HackRFOutput::webapiReverseSendSettings(), and HackRFOutput::webapiSettingsGet().
{
     this->hack_rf_output_settings = hack_rf_output_settings;
     this->m_hack_rf_output_settings_isSet = true;
 }
setKiwiSdrSettings()
void SWGSDRangel::SWGDeviceSettings::setKiwiSdrSettings (SWGKiwiSDRSettings * kiwi_sdr_settings)
Definition at line 601 of file SWGDeviceSettings.cpp.
References kiwi_sdr_settings, and m_kiwi_sdr_settings_isSet.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), KiwiSDRInput::webapiReverseSendSettings(), and KiwiSDRInput::webapiSettingsGet().
{
     this->kiwi_sdr_settings = kiwi_sdr_settings;
     this->m_kiwi_sdr_settings_isSet = true;
 }
setLimeSdrInputSettings()
void SWGSDRangel::SWGDeviceSettings::setLimeSdrInputSettings (SWGLimeSdrInputSettings * lime_sdr_input_settings)
Definition at line 611 of file SWGDeviceSettings.cpp.
References lime_sdr_input_settings, and m_lime_sdr_input_settings_isSet.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), LimeSDRInput::webapiReverseSendSettings(), and LimeSDRInput::webapiSettingsGet().
{
     this->lime_sdr_input_settings = lime_sdr_input_settings;
     this->m_lime_sdr_input_settings_isSet = true;
 }
setLimeSdrOutputSettings()
void SWGSDRangel::SWGDeviceSettings::setLimeSdrOutputSettings (SWGLimeSdrOutputSettings * lime_sdr_output_settings)
Definition at line 621 of file SWGDeviceSettings.cpp.
References lime_sdr_output_settings, and m_lime_sdr_output_settings_isSet.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), LimeSDROutput::webapiReverseSendSettings(), and LimeSDROutput::webapiSettingsGet().
{
     this->lime_sdr_output_settings = lime_sdr_output_settings;
     this->m_lime_sdr_output_settings_isSet = true;
 }
setLocalInputSettings()
void SWGSDRangel::SWGDeviceSettings::setLocalInputSettings (SWGLocalInputSettings * local_input_settings)
Definition at line 631 of file SWGDeviceSettings.cpp.
References local_input_settings, and m_local_input_settings_isSet.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), LocalInput::webapiReverseSendSettings(), and LocalInput::webapiSettingsGet().
{
     this->local_input_settings = local_input_settings;
     this->m_local_input_settings_isSet = true;
 }
setLocalOutputSettings()
void SWGSDRangel::SWGDeviceSettings::setLocalOutputSettings (SWGLocalOutputSettings * local_output_settings)
Definition at line 641 of file SWGDeviceSettings.cpp.
References local_output_settings, and m_local_output_settings_isSet.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), LocalOutput::webapiReverseSendSettings(), and LocalOutput::webapiSettingsGet().
{
     this->local_output_settings = local_output_settings;
     this->m_local_output_settings_isSet = true;
 }
setOriginatorIndex()
void SWGSDRangel::SWGDeviceSettings::setOriginatorIndex (qint32 originator_index)
Definition at line 481 of file SWGDeviceSettings.cpp.
References m_originator_index_isSet, and originator_index.
Referenced by Bladerf1Output::webapiReverseSendSettings(), PlutoSDROutput::webapiReverseSendSettings(), TestSourceInput::webapiReverseSendSettings(), HackRFOutput::webapiReverseSendSettings(), Bladerf1Input::webapiReverseSendSettings(), PerseusInput::webapiReverseSendSettings(), LocalOutput::webapiReverseSendSettings(), AirspyInput::webapiReverseSendSettings(), AirspyHFInput::webapiReverseSendSettings(), TestMI::webapiReverseSendSettings(), RTLSDRInput::webapiReverseSendSettings(), PlutoSDRInput::webapiReverseSendSettings(), FCDProPlusInput::webapiReverseSendSettings(), HackRFInput::webapiReverseSendSettings(), BladeRF2Output::webapiReverseSendSettings(), KiwiSDRInput::webapiReverseSendSettings(), LocalInput::webapiReverseSendSettings(), FCDProInput::webapiReverseSendSettings(), RemoteOutput::webapiReverseSendSettings(), SDRPlayInput::webapiReverseSendSettings(), BladeRF2Input::webapiReverseSendSettings(), SoapySDROutput::webapiReverseSendSettings(), SoapySDRInput::webapiReverseSendSettings(), XTRXOutput::webapiReverseSendSettings(), LimeSDROutput::webapiReverseSendSettings(), XTRXInput::webapiReverseSendSettings(), LimeSDRInput::webapiReverseSendSettings(), RemoteInput::webapiReverseSendSettings(), FileInput::webapiReverseSendSettings(), Bladerf1Output::webapiReverseSendStartStop(), TestSourceInput::webapiReverseSendStartStop(), PlutoSDROutput::webapiReverseSendStartStop(), HackRFOutput::webapiReverseSendStartStop(), Bladerf1Input::webapiReverseSendStartStop(), PerseusInput::webapiReverseSendStartStop(), LocalOutput::webapiReverseSendStartStop(), AirspyInput::webapiReverseSendStartStop(), TestMI::webapiReverseSendStartStop(), AirspyHFInput::webapiReverseSendStartStop(), RTLSDRInput::webapiReverseSendStartStop(), PlutoSDRInput::webapiReverseSendStartStop(), FCDProPlusInput::webapiReverseSendStartStop(), HackRFInput::webapiReverseSendStartStop(), BladeRF2Output::webapiReverseSendStartStop(), KiwiSDRInput::webapiReverseSendStartStop(), LocalInput::webapiReverseSendStartStop(), FCDProInput::webapiReverseSendStartStop(), RemoteOutput::webapiReverseSendStartStop(), SDRPlayInput::webapiReverseSendStartStop(), BladeRF2Input::webapiReverseSendStartStop(), SoapySDROutput::webapiReverseSendStartStop(), SoapySDRInput::webapiReverseSendStartStop(), XTRXOutput::webapiReverseSendStartStop(), LimeSDROutput::webapiReverseSendStartStop(), XTRXInput::webapiReverseSendStartStop(), LimeSDRInput::webapiReverseSendStartStop(), RemoteInput::webapiReverseSendStartStop(), and FileInput::webapiReverseSendStartStop().
{
     this->originator_index = originator_index;
     this->m_originator_index_isSet = true;
 }
setPerseusSettings()
void SWGSDRangel::SWGDeviceSettings::setPerseusSettings (SWGPerseusSettings * perseus_settings)
Definition at line 651 of file SWGDeviceSettings.cpp.
References m_perseus_settings_isSet, and perseus_settings.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), PerseusInput::webapiReverseSendSettings(), and PerseusInput::webapiSettingsGet().
{
     this->perseus_settings = perseus_settings;
     this->m_perseus_settings_isSet = true;
 }
setPlutoSdrInputSettings()
void SWGSDRangel::SWGDeviceSettings::setPlutoSdrInputSettings (SWGPlutoSdrInputSettings * pluto_sdr_input_settings)
Definition at line 661 of file SWGDeviceSettings.cpp.
References m_pluto_sdr_input_settings_isSet, and pluto_sdr_input_settings.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), PlutoSDRInput::webapiReverseSendSettings(), and PlutoSDRInput::webapiSettingsGet().
{
     this->pluto_sdr_input_settings = pluto_sdr_input_settings;
     this->m_pluto_sdr_input_settings_isSet = true;
 }
setPlutoSdrOutputSettings()
void SWGSDRangel::SWGDeviceSettings::setPlutoSdrOutputSettings (SWGPlutoSdrOutputSettings * pluto_sdr_output_settings)
Definition at line 671 of file SWGDeviceSettings.cpp.
References m_pluto_sdr_output_settings_isSet, and pluto_sdr_output_settings.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), PlutoSDROutput::webapiReverseSendSettings(), and PlutoSDROutput::webapiSettingsGet().
{
     this->pluto_sdr_output_settings = pluto_sdr_output_settings;
     this->m_pluto_sdr_output_settings_isSet = true;
 }
setRemoteInputSettings()
void SWGSDRangel::SWGDeviceSettings::setRemoteInputSettings (SWGRemoteInputSettings * remote_input_settings)
Definition at line 701 of file SWGDeviceSettings.cpp.
References m_remote_input_settings_isSet, and remote_input_settings.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), RemoteInput::webapiReverseSendSettings(), and RemoteInput::webapiSettingsGet().
{
     this->remote_input_settings = remote_input_settings;
     this->m_remote_input_settings_isSet = true;
 }
setRemoteOutputSettings()
void SWGSDRangel::SWGDeviceSettings::setRemoteOutputSettings (SWGRemoteOutputSettings * remote_output_settings)
Definition at line 691 of file SWGDeviceSettings.cpp.
References m_remote_output_settings_isSet, and remote_output_settings.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), RemoteOutput::webapiReverseSendSettings(), and RemoteOutput::webapiSettingsGet().
{
     this->remote_output_settings = remote_output_settings;
     this->m_remote_output_settings_isSet = true;
 }
setRtlSdrSettings()
void SWGSDRangel::SWGDeviceSettings::setRtlSdrSettings (SWGRtlSdrSettings * rtl_sdr_settings)
Definition at line 681 of file SWGDeviceSettings.cpp.
References m_rtl_sdr_settings_isSet, and rtl_sdr_settings.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), RTLSDRInput::webapiReverseSendSettings(), and RTLSDRInput::webapiSettingsGet().
{
     this->rtl_sdr_settings = rtl_sdr_settings;
     this->m_rtl_sdr_settings_isSet = true;
 }
setSdrPlaySettings()
void SWGSDRangel::SWGDeviceSettings::setSdrPlaySettings (SWGSDRPlaySettings * sdr_play_settings)
Definition at line 711 of file SWGDeviceSettings.cpp.
References m_sdr_play_settings_isSet, and sdr_play_settings.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), SDRPlayInput::webapiReverseSendSettings(), and SDRPlayInput::webapiSettingsGet().
{
     this->sdr_play_settings = sdr_play_settings;
     this->m_sdr_play_settings_isSet = true;
 }
setSoapySdrInputSettings()
void SWGSDRangel::SWGDeviceSettings::setSoapySdrInputSettings (SWGSoapySDRInputSettings * soapy_sdr_input_settings)
Definition at line 721 of file SWGDeviceSettings.cpp.
References m_soapy_sdr_input_settings_isSet, and soapy_sdr_input_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), SoapySDRInput::webapiReverseSendSettings(), and SoapySDRInput::webapiSettingsGet().
{
     this->soapy_sdr_input_settings = soapy_sdr_input_settings;
     this->m_soapy_sdr_input_settings_isSet = true;
 }
setSoapySdrOutputSettings()
void SWGSDRangel::SWGDeviceSettings::setSoapySdrOutputSettings (SWGSoapySDROutputSettings * soapy_sdr_output_settings)
Definition at line 731 of file SWGDeviceSettings.cpp.
References m_soapy_sdr_output_settings_isSet, and soapy_sdr_output_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), SoapySDROutput::webapiReverseSendSettings(), and SoapySDROutput::webapiSettingsGet().
{
     this->soapy_sdr_output_settings = soapy_sdr_output_settings;
     this->m_soapy_sdr_output_settings_isSet = true;
 }
setTestMiSettings()
void SWGSDRangel::SWGDeviceSettings::setTestMiSettings (SWGTestMISettings * test_mi_settings)
Definition at line 751 of file SWGDeviceSettings.cpp.
References m_test_mi_settings_isSet, and test_mi_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), TestMI::webapiReverseSendSettings(), and TestMI::webapiSettingsGet().
{
     this->test_mi_settings = test_mi_settings;
     this->m_test_mi_settings_isSet = true;
 }
setTestSourceSettings()
void SWGSDRangel::SWGDeviceSettings::setTestSourceSettings (SWGTestSourceSettings * test_source_settings)
Definition at line 741 of file SWGDeviceSettings.cpp.
References m_test_source_settings_isSet, and test_source_settings.
Referenced by WebAPIRequestMapper::resetDeviceSettings(), WebAPIRequestMapper::validateDeviceSettings(), TestSourceInput::webapiReverseSendSettings(), and TestSourceInput::webapiSettingsGet().
{
     this->test_source_settings = test_source_settings;
     this->m_test_source_settings_isSet = true;
 }
setXtrxInputSettings()
void SWGSDRangel::SWGDeviceSettings::setXtrxInputSettings (SWGXtrxInputSettings * xtrx_input_settings)
Definition at line 761 of file SWGDeviceSettings.cpp.
References m_xtrx_input_settings_isSet, and xtrx_input_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), XTRXInput::webapiReverseSendSettings(), and XTRXInput::webapiSettingsGet().
{
     this->xtrx_input_settings = xtrx_input_settings;
     this->m_xtrx_input_settings_isSet = true;
 }
setXtrxOutputSettings()
void SWGSDRangel::SWGDeviceSettings::setXtrxOutputSettings (SWGXtrxOutputSettings * xtrx_output_settings)
Definition at line 771 of file SWGDeviceSettings.cpp.
References m_xtrx_output_settings_isSet, and xtrx_output_settings.
Referenced by WebAPIRequestMapper::validateDeviceSettings(), XTRXOutput::webapiReverseSendSettings(), and XTRXOutput::webapiSettingsGet().
{
     this->xtrx_output_settings = xtrx_output_settings;
     this->m_xtrx_output_settings_isSet = true;
 }
Member Data Documentation
airspy_hf_settings
SWGAirspyHFSettings* SWGSDRangel::SWGDeviceSettings::airspy_hf_settings private
Definition at line 186 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getAirspyHfSettings(), init(), isSet(), setAirspyHfSettings(), and SWGDeviceSettings().
airspy_settings
SWGAirspySettings* SWGSDRangel::SWGDeviceSettings::airspy_settings private
Definition at line 183 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getAirspySettings(), init(), isSet(), setAirspySettings(), and SWGDeviceSettings().
blade_rf1_input_settings
SWGBladeRF1InputSettings* SWGSDRangel::SWGDeviceSettings::blade_rf1_input_settings private
Definition at line 189 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getBladeRf1InputSettings(), init(), isSet(), setBladeRf1InputSettings(), and SWGDeviceSettings().
blade_rf1_output_settings
SWGBladeRF1OutputSettings* SWGSDRangel::SWGDeviceSettings::blade_rf1_output_settings private
Definition at line 195 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getBladeRf1OutputSettings(), init(), isSet(), setBladeRf1OutputSettings(), and SWGDeviceSettings().
blade_rf2_input_settings
SWGBladeRF2InputSettings* SWGSDRangel::SWGDeviceSettings::blade_rf2_input_settings private
Definition at line 192 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getBladeRf2InputSettings(), init(), isSet(), setBladeRf2InputSettings(), and SWGDeviceSettings().
blade_rf2_output_settings
SWGBladeRF2OutputSettings* SWGSDRangel::SWGDeviceSettings::blade_rf2_output_settings private
Definition at line 198 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getBladeRf2OutputSettings(), init(), isSet(), setBladeRf2OutputSettings(), and SWGDeviceSettings().
device_hw_type
QString* SWGSDRangel::SWGDeviceSettings::device_hw_type private
Definition at line 174 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getDeviceHwType(), init(), isSet(), setDeviceHwType(), and SWGDeviceSettings().
direction
qint32 SWGSDRangel::SWGDeviceSettings::direction private
Definition at line 177 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), fromJsonObject(), getDirection(), init(), setDirection(), and SWGDeviceSettings().
fcd_pro_plus_settings
SWGFCDProPlusSettings* SWGSDRangel::SWGDeviceSettings::fcd_pro_plus_settings private
Definition at line 204 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFcdProPlusSettings(), init(), isSet(), setFcdProPlusSettings(), and SWGDeviceSettings().
fcd_pro_settings
SWGFCDProSettings* SWGSDRangel::SWGDeviceSettings::fcd_pro_settings private
Definition at line 201 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFcdProSettings(), init(), isSet(), setFcdProSettings(), and SWGDeviceSettings().
file_input_settings
SWGFileInputSettings* SWGSDRangel::SWGDeviceSettings::file_input_settings private
Definition at line 207 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFileInputSettings(), init(), isSet(), setFileInputSettings(), and SWGDeviceSettings().
hack_rf_input_settings
SWGHackRFInputSettings* SWGSDRangel::SWGDeviceSettings::hack_rf_input_settings private
Definition at line 210 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getHackRfInputSettings(), init(), isSet(), setHackRfInputSettings(), and SWGDeviceSettings().
hack_rf_output_settings
SWGHackRFOutputSettings* SWGSDRangel::SWGDeviceSettings::hack_rf_output_settings private
Definition at line 213 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getHackRfOutputSettings(), init(), isSet(), setHackRfOutputSettings(), and SWGDeviceSettings().
kiwi_sdr_settings
SWGKiwiSDRSettings* SWGSDRangel::SWGDeviceSettings::kiwi_sdr_settings private
Definition at line 216 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getKiwiSdrSettings(), init(), isSet(), setKiwiSdrSettings(), and SWGDeviceSettings().
lime_sdr_input_settings
SWGLimeSdrInputSettings* SWGSDRangel::SWGDeviceSettings::lime_sdr_input_settings private
Definition at line 219 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getLimeSdrInputSettings(), init(), isSet(), setLimeSdrInputSettings(), and SWGDeviceSettings().
lime_sdr_output_settings
SWGLimeSdrOutputSettings* SWGSDRangel::SWGDeviceSettings::lime_sdr_output_settings private
Definition at line 222 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getLimeSdrOutputSettings(), init(), isSet(), setLimeSdrOutputSettings(), and SWGDeviceSettings().
local_input_settings
SWGLocalInputSettings* SWGSDRangel::SWGDeviceSettings::local_input_settings private
Definition at line 225 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getLocalInputSettings(), init(), isSet(), setLocalInputSettings(), and SWGDeviceSettings().
local_output_settings
SWGLocalOutputSettings* SWGSDRangel::SWGDeviceSettings::local_output_settings private
Definition at line 228 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getLocalOutputSettings(), init(), isSet(), setLocalOutputSettings(), and SWGDeviceSettings().
m_airspy_hf_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_airspy_hf_settings_isSet private
Definition at line 187 of file SWGDeviceSettings.h.
Referenced by init(), setAirspyHfSettings(), and SWGDeviceSettings().
m_airspy_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_airspy_settings_isSet private
Definition at line 184 of file SWGDeviceSettings.h.
Referenced by init(), setAirspySettings(), and SWGDeviceSettings().
m_blade_rf1_input_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_blade_rf1_input_settings_isSet private
Definition at line 190 of file SWGDeviceSettings.h.
Referenced by init(), setBladeRf1InputSettings(), and SWGDeviceSettings().
m_blade_rf1_output_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_blade_rf1_output_settings_isSet private
Definition at line 196 of file SWGDeviceSettings.h.
Referenced by init(), setBladeRf1OutputSettings(), and SWGDeviceSettings().
m_blade_rf2_input_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_blade_rf2_input_settings_isSet private
Definition at line 193 of file SWGDeviceSettings.h.
Referenced by init(), setBladeRf2InputSettings(), and SWGDeviceSettings().
m_blade_rf2_output_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_blade_rf2_output_settings_isSet private
Definition at line 199 of file SWGDeviceSettings.h.
Referenced by init(), setBladeRf2OutputSettings(), and SWGDeviceSettings().
m_device_hw_type_isSet
bool SWGSDRangel::SWGDeviceSettings::m_device_hw_type_isSet private
Definition at line 175 of file SWGDeviceSettings.h.
Referenced by init(), setDeviceHwType(), and SWGDeviceSettings().
m_direction_isSet
bool SWGSDRangel::SWGDeviceSettings::m_direction_isSet private
Definition at line 178 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), init(), isSet(), setDirection(), and SWGDeviceSettings().
m_fcd_pro_plus_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_fcd_pro_plus_settings_isSet private
Definition at line 205 of file SWGDeviceSettings.h.
Referenced by init(), setFcdProPlusSettings(), and SWGDeviceSettings().
m_fcd_pro_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_fcd_pro_settings_isSet private
Definition at line 202 of file SWGDeviceSettings.h.
Referenced by init(), setFcdProSettings(), and SWGDeviceSettings().
m_file_input_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_file_input_settings_isSet private
Definition at line 208 of file SWGDeviceSettings.h.
Referenced by init(), setFileInputSettings(), and SWGDeviceSettings().
m_hack_rf_input_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_hack_rf_input_settings_isSet private
Definition at line 211 of file SWGDeviceSettings.h.
Referenced by init(), setHackRfInputSettings(), and SWGDeviceSettings().
m_hack_rf_output_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_hack_rf_output_settings_isSet private
Definition at line 214 of file SWGDeviceSettings.h.
Referenced by init(), setHackRfOutputSettings(), and SWGDeviceSettings().
m_kiwi_sdr_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_kiwi_sdr_settings_isSet private
Definition at line 217 of file SWGDeviceSettings.h.
Referenced by init(), setKiwiSdrSettings(), and SWGDeviceSettings().
m_lime_sdr_input_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_lime_sdr_input_settings_isSet private
Definition at line 220 of file SWGDeviceSettings.h.
Referenced by init(), setLimeSdrInputSettings(), and SWGDeviceSettings().
m_lime_sdr_output_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_lime_sdr_output_settings_isSet private
Definition at line 223 of file SWGDeviceSettings.h.
Referenced by init(), setLimeSdrOutputSettings(), and SWGDeviceSettings().
m_local_input_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_local_input_settings_isSet private
Definition at line 226 of file SWGDeviceSettings.h.
Referenced by init(), setLocalInputSettings(), and SWGDeviceSettings().
m_local_output_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_local_output_settings_isSet private
Definition at line 229 of file SWGDeviceSettings.h.
Referenced by init(), setLocalOutputSettings(), and SWGDeviceSettings().
m_originator_index_isSet
bool SWGSDRangel::SWGDeviceSettings::m_originator_index_isSet private
Definition at line 181 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), init(), isSet(), setOriginatorIndex(), and SWGDeviceSettings().
m_perseus_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_perseus_settings_isSet private
Definition at line 232 of file SWGDeviceSettings.h.
Referenced by init(), setPerseusSettings(), and SWGDeviceSettings().
m_pluto_sdr_input_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_pluto_sdr_input_settings_isSet private
Definition at line 235 of file SWGDeviceSettings.h.
Referenced by init(), setPlutoSdrInputSettings(), and SWGDeviceSettings().
m_pluto_sdr_output_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_pluto_sdr_output_settings_isSet private
Definition at line 238 of file SWGDeviceSettings.h.
Referenced by init(), setPlutoSdrOutputSettings(), and SWGDeviceSettings().
m_remote_input_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_remote_input_settings_isSet private
Definition at line 247 of file SWGDeviceSettings.h.
Referenced by init(), setRemoteInputSettings(), and SWGDeviceSettings().
m_remote_output_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_remote_output_settings_isSet private
Definition at line 244 of file SWGDeviceSettings.h.
Referenced by init(), setRemoteOutputSettings(), and SWGDeviceSettings().
m_rtl_sdr_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_rtl_sdr_settings_isSet private
Definition at line 241 of file SWGDeviceSettings.h.
Referenced by init(), setRtlSdrSettings(), and SWGDeviceSettings().
m_sdr_play_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_sdr_play_settings_isSet private
Definition at line 250 of file SWGDeviceSettings.h.
Referenced by init(), setSdrPlaySettings(), and SWGDeviceSettings().
m_soapy_sdr_input_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_soapy_sdr_input_settings_isSet private
Definition at line 253 of file SWGDeviceSettings.h.
Referenced by init(), setSoapySdrInputSettings(), and SWGDeviceSettings().
m_soapy_sdr_output_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_soapy_sdr_output_settings_isSet private
Definition at line 256 of file SWGDeviceSettings.h.
Referenced by init(), setSoapySdrOutputSettings(), and SWGDeviceSettings().
m_test_mi_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_test_mi_settings_isSet private
Definition at line 262 of file SWGDeviceSettings.h.
Referenced by init(), setTestMiSettings(), and SWGDeviceSettings().
m_test_source_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_test_source_settings_isSet private
Definition at line 259 of file SWGDeviceSettings.h.
Referenced by init(), setTestSourceSettings(), and SWGDeviceSettings().
m_xtrx_input_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_xtrx_input_settings_isSet private
Definition at line 265 of file SWGDeviceSettings.h.
Referenced by init(), setXtrxInputSettings(), and SWGDeviceSettings().
m_xtrx_output_settings_isSet
bool SWGSDRangel::SWGDeviceSettings::m_xtrx_output_settings_isSet private
Definition at line 268 of file SWGDeviceSettings.h.
Referenced by init(), setXtrxOutputSettings(), and SWGDeviceSettings().
originator_index
qint32 SWGSDRangel::SWGDeviceSettings::originator_index private
Definition at line 180 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), fromJsonObject(), getOriginatorIndex(), init(), setOriginatorIndex(), and SWGDeviceSettings().
perseus_settings
SWGPerseusSettings* SWGSDRangel::SWGDeviceSettings::perseus_settings private
Definition at line 231 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getPerseusSettings(), init(), isSet(), setPerseusSettings(), and SWGDeviceSettings().
pluto_sdr_input_settings
SWGPlutoSdrInputSettings* SWGSDRangel::SWGDeviceSettings::pluto_sdr_input_settings private
Definition at line 234 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getPlutoSdrInputSettings(), init(), isSet(), setPlutoSdrInputSettings(), and SWGDeviceSettings().
pluto_sdr_output_settings
SWGPlutoSdrOutputSettings* SWGSDRangel::SWGDeviceSettings::pluto_sdr_output_settings private
Definition at line 237 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getPlutoSdrOutputSettings(), init(), isSet(), setPlutoSdrOutputSettings(), and SWGDeviceSettings().
remote_input_settings
SWGRemoteInputSettings* SWGSDRangel::SWGDeviceSettings::remote_input_settings private
Definition at line 246 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getRemoteInputSettings(), init(), isSet(), setRemoteInputSettings(), and SWGDeviceSettings().
remote_output_settings
SWGRemoteOutputSettings* SWGSDRangel::SWGDeviceSettings::remote_output_settings private
Definition at line 243 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getRemoteOutputSettings(), init(), isSet(), setRemoteOutputSettings(), and SWGDeviceSettings().
rtl_sdr_settings
SWGRtlSdrSettings* SWGSDRangel::SWGDeviceSettings::rtl_sdr_settings private
Definition at line 240 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getRtlSdrSettings(), init(), isSet(), setRtlSdrSettings(), and SWGDeviceSettings().
sdr_play_settings
SWGSDRPlaySettings* SWGSDRangel::SWGDeviceSettings::sdr_play_settings private
Definition at line 249 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSdrPlaySettings(), init(), isSet(), setSdrPlaySettings(), and SWGDeviceSettings().
soapy_sdr_input_settings
SWGSoapySDRInputSettings* SWGSDRangel::SWGDeviceSettings::soapy_sdr_input_settings private
Definition at line 252 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSoapySdrInputSettings(), init(), isSet(), setSoapySdrInputSettings(), and SWGDeviceSettings().
soapy_sdr_output_settings
SWGSoapySDROutputSettings* SWGSDRangel::SWGDeviceSettings::soapy_sdr_output_settings private
Definition at line 255 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSoapySdrOutputSettings(), init(), isSet(), setSoapySdrOutputSettings(), and SWGDeviceSettings().
test_mi_settings
SWGTestMISettings* SWGSDRangel::SWGDeviceSettings::test_mi_settings private
Definition at line 261 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getTestMiSettings(), init(), isSet(), setTestMiSettings(), and SWGDeviceSettings().
test_source_settings
SWGTestSourceSettings* SWGSDRangel::SWGDeviceSettings::test_source_settings private
Definition at line 258 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getTestSourceSettings(), init(), isSet(), setTestSourceSettings(), and SWGDeviceSettings().
xtrx_input_settings
SWGXtrxInputSettings* SWGSDRangel::SWGDeviceSettings::xtrx_input_settings private
Definition at line 264 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getXtrxInputSettings(), init(), isSet(), setXtrxInputSettings(), and SWGDeviceSettings().
xtrx_output_settings
SWGXtrxOutputSettings* SWGSDRangel::SWGDeviceSettings::xtrx_output_settings private
Definition at line 267 of file SWGDeviceSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getXtrxOutputSettings(), init(), isSet(), setXtrxOutputSettings(), and SWGDeviceSettings().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGDeviceSettings.h
swagger/sdrangel/code/qt5/client/SWGDeviceSettings.cpp