SDRAngel: leansdr::s2_framer Struct Reference
leansdr::s2_framer Struct Reference
#include <dvbs2.h>
Public Member Functions
s2_framer (scheduler *sch, pipebuf< tspacket > &_in, pipebuf< bbframe > &_out)
void run ()
Public Member Functions inherited from leansdr::runnable
runnable (scheduler *_sch, const char *name)
Public Member Functions inherited from leansdr::runnable_common
runnable_common (const char *_name)
virtual ~runnable_common ()
virtual void shutdown ()
Public Attributes
uint8_t rolloff_code
s2_pls pls
Public Attributes inherited from leansdr::runnable_common
const char * name
Private Attributes
pipereader< tspacket > in
pipewriter< bbframe > out
crc8_engine crc8
int nremain
uint8_t rembuf [tspacket::SIZE]
uint8_t remcrc
Additional Inherited Members
Protected Attributes inherited from leansdr::runnable
scheduler * sch
Detailed Description
Definition at line 2430 of file dvbs2.h.
Constructor & Destructor Documentation
s2_framer()
leansdr::s2_framer::s2_framer (scheduler * sch, pipebuf< tspacket > & _in, pipebuf< bbframe > & _out) inline
Definition at line 2434 of file dvbs2.h.
References leansdr::s2_pls::modcod, leansdr::s2_pls::pilots, and leansdr::s2_pls::sf.
         : runnable(sch, "S2 framer"),
           in(_in), out(_out)
     {
         pls.modcod = 4;
         pls.sf = false;
         pls.pilots = true;
         nremain = 0;
         remcrc = 0; // CRC for nonexistent previous packet
     }
Member Function Documentation
run()
void leansdr::s2_framer::run () inline virtual
Reimplemented from leansdr::runnable_common.
Definition at line 2444 of file dvbs2.h.
References leansdr::bbframe::bytes, leansdr::check_modcod(), leansdr::tspacket::data, leansdr::fail(), leansdr::s2_pls::modcod, leansdr::bbframe::pls, leansdr::modcod_info::rate, leansdr::pipereader< T >::rd(), leansdr::pipereader< T >::read(), leansdr::pipereader< T >::readable(), leansdr::s2_pls::sf, leansdr::tspacket::SIZE, leansdr::pipewriter< T >::wr(), leansdr::pipewriter< T >::writable(), and leansdr::pipewriter< T >::written().
     {
         while (out.writable() >= 1)
         {
             const modcod_info *mcinfo = check_modcod(pls.modcod);
             const fec_info *fi = &fec_infos[pls.sf][mcinfo->rate];
             int framebytes = fi->Kbch / 8;
             if (!framebytes)
                 fail("MODCOD/framesize combination not allowed");
             if (10 + nremain + 188 * in.readable() < framebytes)
                 break; // Not enough data to fill a frame
             bbframe *pout = out.wr();
             pout->pls = pls;
             uint8_t *buf = pout->bytes;
             uint8_t *end = buf + framebytes;
             // EN 302 307-1 section 5.1.6 Base-Band Header insertion
             uint8_t *bbheader = buf;
             *buf++ = 0x30 | rolloff_code; // MATYPE-1: SIS, CCM
             *buf++ = 0;                   // MATYPE-2
             uint16_t upl = 188 * 8;
             *buf++ = upl >> 8; // UPL MSB
             *buf++ = upl;      // UPL LSB
             uint16_t dfl = (framebytes - 10) * 8;
             *buf++ = dfl >> 8; // DFL MSB
             *buf++ = dfl;      // DFL LSB
             *buf++ = 0x47;     // SYNC
             uint16_t syncd = nremain * 8;
             *buf++ = syncd >> 8; // SYNCD MSB
             *buf++ = syncd;      // SYNCD LSB
             *buf++ = crc8.compute(bbheader, 9);
             // Data field
             memcpy(buf, rembuf, nremain); // Leftover from previous runs
             buf += nremain;
             while (buf < end)
             {
                 tspacket *tsp = in.rd();
                 if (tsp->data[0] != MPEG_SYNC)
                     fail("Invalid TS");
                 *buf++ = remcrc; // Replace SYNC with CRC of previous.
                 remcrc = crc8.compute(tsp->data + 1, tspacket::SIZE - 1);
                 int nused = end - buf;
                 if (nused > tspacket::SIZE - 1)
                     nused = tspacket::SIZE - 1;
                 memcpy(buf, tsp->data + 1, nused);
                 buf += nused;
                 if (buf == end)
                 {
                     nremain = (tspacket::SIZE - 1) - nused;
                     memcpy(rembuf, tsp->data + 1 + nused, nremain);
                 }
                 in.read(1);
             }
             if (buf != end)
                 fail("Bug: s2_framer");
             out.written(1);
         }
     }
Member Data Documentation
crc8
crc8_engine leansdr::s2_framer::crc8 private
Definition at line 2505 of file dvbs2.h.
in
pipereader<tspacket> leansdr::s2_framer::in private
Definition at line 2503 of file dvbs2.h.
nremain
int leansdr::s2_framer::nremain private
Definition at line 2506 of file dvbs2.h.
out
pipewriter<bbframe> leansdr::s2_framer::out private
Definition at line 2504 of file dvbs2.h.
pls
s2_pls leansdr::s2_framer::pls
Definition at line 2433 of file dvbs2.h.
rembuf
uint8_t leansdr::s2_framer::rembuf[tspacket::SIZE] private
Definition at line 2507 of file dvbs2.h.
remcrc
uint8_t leansdr::s2_framer::remcrc private
Definition at line 2508 of file dvbs2.h.
rolloff_code
uint8_t leansdr::s2_framer::rolloff_code
Definition at line 2432 of file dvbs2.h.
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/dvbs2.h