SDRAngel: AMBEWorker::MsgMbeDecode Class Reference
AMBEWorker::MsgMbeDecode Class Reference
#include <ambeworker.h>
Public Member Functions
const unsigned char * getMbeFrame () const
SerialDV::DVRate getMbeRate () const
int getVolumeIndex () const
unsigned char getChannels () const
bool getUseHP () const
int getUpsampling () const
AudioFifo * getAudioFifo ()
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgMbeDecode * create (const unsigned char *mbeFrame, int mbeRateIndex, int volumeIndex, unsigned char channels, bool useHP, int upsampling, AudioFifo *audioFifo)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgMbeDecode (const unsigned char *mbeFrame, SerialDV::DVRate mbeRate, int volumeIndex, unsigned char channels, bool useHP, int upsampling, AudioFifo *audioFifo)
Private Attributes
unsigned char m_mbeFrame [SerialDV::MBE_FRAME_MAX_LENGTH_BYTES]
SerialDV::DVRate m_mbeRate
int m_volumeIndex
unsigned char m_channels
bool m_useHP
int m_upsampling
AudioFifo * m_audioFifo
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 49 of file ambeworker.h.
Constructor & Destructor Documentation
MsgMbeDecode()
AMBEWorker::MsgMbeDecode::MsgMbeDecode (const unsigned char * mbeFrame, SerialDV::DVRate mbeRate, int volumeIndex, unsigned char channels, bool useHP, int upsampling, AudioFifo * audioFifo) inline private
Definition at line 82 of file ambeworker.h.
                                       :
             Message(),
             m_mbeRate(mbeRate),
             m_volumeIndex(volumeIndex),
             m_channels(channels),
             m_useHP(useHP),
             m_upsampling(upsampling),
             m_audioFifo(audioFifo)
         {
             memcpy((void *) m_mbeFrame, (const void *) mbeFrame, SerialDV::DVController::getNbMbeBytes(m_mbeRate));
         }
Member Function Documentation
create()
static MsgMbeDecode* AMBEWorker::MsgMbeDecode::create (const unsigned char * mbeFrame, int mbeRateIndex, int volumeIndex, unsigned char channels, bool useHP, int upsampling, AudioFifo * audioFifo) inline static
Definition at line 61 of file ambeworker.h.
Referenced by AMBEWorker::pushMbeFrame().
         {
             return new MsgMbeDecode(mbeFrame, (SerialDV::DVRate) mbeRateIndex, volumeIndex, channels, useHP, upsampling, audioFifo);
         }
getAudioFifo()
AudioFifo* AMBEWorker::MsgMbeDecode::getAudioFifo () inline
Definition at line 59 of file ambeworker.h.
Referenced by AMBEWorker::handleInputMessages().
 { return m_audioFifo; }
getChannels()
unsigned char AMBEWorker::MsgMbeDecode::getChannels () const inline
Definition at line 56 of file ambeworker.h.
Referenced by AMBEWorker::handleInputMessages().
 { return m_channels % 4; }
getMbeFrame()
const unsigned char* AMBEWorker::MsgMbeDecode::getMbeFrame () const inline
Definition at line 53 of file ambeworker.h.
Referenced by AMBEWorker::handleInputMessages().
 { return m_mbeFrame; }
getMbeRate()
SerialDV::DVRate AMBEWorker::MsgMbeDecode::getMbeRate () const inline
Definition at line 54 of file ambeworker.h.
Referenced by AMBEWorker::handleInputMessages().
 { return m_mbeRate; }
getUpsampling()
int AMBEWorker::MsgMbeDecode::getUpsampling () const inline
Definition at line 58 of file ambeworker.h.
Referenced by AMBEWorker::handleInputMessages().
 { return m_upsampling; }
getUseHP()
bool AMBEWorker::MsgMbeDecode::getUseHP () const inline
Definition at line 57 of file ambeworker.h.
Referenced by AMBEWorker::handleInputMessages().
 { return m_useHP; }
getVolumeIndex()
int AMBEWorker::MsgMbeDecode::getVolumeIndex () const inline
Definition at line 55 of file ambeworker.h.
Referenced by AMBEWorker::handleInputMessages().
 { return m_volumeIndex; }
Member Data Documentation
m_audioFifo
AudioFifo* AMBEWorker::MsgMbeDecode::m_audioFifo private
Definition at line 80 of file ambeworker.h.
m_channels
unsigned char AMBEWorker::MsgMbeDecode::m_channels private
Definition at line 77 of file ambeworker.h.
m_mbeFrame
unsigned char AMBEWorker::MsgMbeDecode::m_mbeFrame[SerialDV::MBE_FRAME_MAX_LENGTH_BYTES] private
Definition at line 74 of file ambeworker.h.
m_mbeRate
SerialDV::DVRate AMBEWorker::MsgMbeDecode::m_mbeRate private
Definition at line 75 of file ambeworker.h.
m_upsampling
int AMBEWorker::MsgMbeDecode::m_upsampling private
Definition at line 79 of file ambeworker.h.
m_useHP
bool AMBEWorker::MsgMbeDecode::m_useHP private
Definition at line 78 of file ambeworker.h.
m_volumeIndex
int AMBEWorker::MsgMbeDecode::m_volumeIndex private
Definition at line 76 of file ambeworker.h.
The documentation for this class was generated from the following file:
sdrbase/ambe/ambeworker.h