SDRAngel: DSPDeviceMIMOEngine Class Reference
DSPDeviceMIMOEngine Class Reference
#include <dspdevicemimoengine.h>
Inherits QThread.
Classes
class AddBasebandSampleSink
class AddSinkStream
class AddSourceStream
class AddSpectrumSink
class AddThreadedBasebandSampleSink
class AddThreadedBasebandSampleSource
class ConfigureCorrection
class GetErrorMessage
class GetMIMODeviceDescription
class RemoveBasebandSampleSink
class RemoveLastSinkStream
class RemoveLastSourceStream
class RemoveSpectrumSink
class RemoveThreadedBasebandSampleSink
class RemoveThreadedBasebandSampleSource
class SetSampleMIMO
class SetSpectrumSinkInput
struct SourceCorrection
Public Types
enum State {
StNotStarted, StIdle, StReady, StRunning,
StError
}
Public Member Functions
DSPDeviceMIMOEngine (uint32_t uid, QObject *parent=nullptr)
~DSPDeviceMIMOEngine ()
MessageQueue * getInputMessageQueue ()
void start ()
This thread start.
void stop ()
This thread stop.
bool initProcess ()
Initialize process sequence.
bool startProcess ()
Start process sequence.
void stopProcess ()
Stop process sequence.
void setMIMO (DeviceSampleMIMO *mimo)
Set the sample MIMO type.
DeviceSampleMIMO * getMIMO ()
void setMIMOSequence (int sequence)
Set the sample MIMO sequence in type.
uint getUID () const
void addSourceStream (bool connect)
void removeLastSourceStream ()
void addSinkStream (bool connect)
void removeLastSinkStream ()
void addChannelSource (ThreadedBasebandSampleSource *source, int index=0)
Add a channel source that will run on its own thread.
void removeChannelSource (ThreadedBasebandSampleSource *source, int index=0)
Remove a channel source that runs on its own thread.
void addChannelSink (ThreadedBasebandSampleSink *sink, int index=0)
Add a channel sink that will run on its own thread.
void removeChannelSink (ThreadedBasebandSampleSink *sink, int index=0)
Remove a channel sink that runs on its own thread.
void addAncillarySink (BasebandSampleSink *sink, int index=0)
Add an ancillary sink like a I/Q recorder.
void removeAncillarySink (BasebandSampleSink *sink, int index=0)
Remove an ancillary sample sink.
void addSpectrumSink (BasebandSampleSink *spectrumSink)
Add a spectrum vis baseband sample sink.
void removeSpectrumSink (BasebandSampleSink *spectrumSink)
Add a spectrum vis baseband sample sink.
void setSpectrumSinkInput (bool sourceElseSink, int index)
State state () const
Return DSP engine current state.
QString errorMessage ()
Return the current error message.
QString deviceDescription ()
Return the device description.
void configureCorrections (bool dcOffsetCorrection, bool iqImbalanceCorrection, int isource)
Configure source DSP corrections.
Private Types
typedef std::list< BasebandSampleSink * > BasebandSampleSinks
typedef std::list< ThreadedBasebandSampleSink * > ThreadedBasebandSampleSinks
typedef std::list< ThreadedBasebandSampleSource * > ThreadedBasebandSampleSources
Private Slots
void handleData ()
Handle data when samples have to be processed.
void workSampleSink (unsigned int sinkIndex)
void handleSynchronousMessages ()
Handle synchronous messages with the thread.
void handleInputMessages ()
Handle input message queue.
void handleForwardToSpectrumSink (int nbSamples)
Private Member Functions
void run ()
void work (int nbWriteSamples)
transfer samples if in running state
State gotoIdle ()
Go to the idle state.
State gotoInit ()
Go to the acquisition init state from idle.
State gotoRunning ()
Go to the running state from ready state.
State gotoError (const QString &errorMsg)
Go to an error state.
void handleSetMIMO (DeviceSampleMIMO *mimo)
Manage MIMO device setting.
void iqCorrections (SampleVector::iterator begin, SampleVector::iterator end, int isource, bool imbalanceCorrection)
Private Attributes
uint32_t m_uid
unique ID
State m_state
QString m_errorMessage
QString m_deviceDescription
DeviceSampleMIMO * m_deviceSampleMIMO
int m_sampleMIMOSequence
MessageQueue m_inputMessageQueue
SyncMessenger m_syncMessenger
Used to process messages synchronously with the thread.
std::vector< BasebandSampleSinks > m_basebandSampleSinks
ancillary sample sinks on main thread (per input stream)
std::vector< ThreadedBasebandSampleSinks > m_threadedBasebandSampleSinks
channel sample sinks on their own thread (per input stream)
std::vector< int > m_sampleSinkConnectionIndexes
std::vector< ThreadedBasebandSampleSources > m_threadedBasebandSampleSources
channel sample sources on their own threads (per output stream)
std::vector< int > m_sampleSourceConnectionIndexes
std::vector< SourceCorrection > m_sourcesCorrections
BasebandSampleSink * m_spectrumSink
The spectrum sink.
bool m_spectrumInputSourceElseSink
Source else sink stream to be used as spectrum sink input.
unsigned int m_spectrumInputIndex
Index of the stream to be used as spectrum sink input.
Detailed Description
Definition at line 36 of file dspdevicemimoengine.h.
Member Typedef Documentation
BasebandSampleSinks
typedef std::list<BasebandSampleSink*> DSPDeviceMIMOEngine::BasebandSampleSinks private
Definition at line 346 of file dspdevicemimoengine.h.
ThreadedBasebandSampleSinks
typedef std::list<ThreadedBasebandSampleSink*> DSPDeviceMIMOEngine::ThreadedBasebandSampleSinks private
Definition at line 349 of file dspdevicemimoengine.h.
ThreadedBasebandSampleSources
typedef std::list<ThreadedBasebandSampleSource*> DSPDeviceMIMOEngine::ThreadedBasebandSampleSources private
Definition at line 353 of file dspdevicemimoengine.h.
Member Enumeration Documentation
State
enum DSPDeviceMIMOEngine::State
Enumerator
StNotStarted
engine is before initialization
StIdle
engine is idle
StReady
engine is ready to run
StRunning
engine is running
StError
engine is in error
Definition at line 234 of file dspdevicemimoengine.h.
                {
         StNotStarted,
         StIdle,
         StReady,
         StRunning,
         StError
     };
Constructor & Destructor Documentation
DSPDeviceMIMOEngine()
DSPDeviceMIMOEngine::DSPDeviceMIMOEngine (uint32_t uid, QObject * parent = nullptr)
Definition at line 46 of file dspdevicemimoengine.cpp.
                                                                       :
     QThread(parent),
     m_uid(uid),
     m_state(StNotStarted),
     m_deviceSampleMIMO(nullptr),
     m_spectrumInputSourceElseSink(true),
     m_spectrumInputIndex(0)
 {
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     connect(&m_syncMessenger, SIGNAL(messageSent()), this, SLOT(handleSynchronousMessages()), Qt::QueuedConnection);
     moveToThread(this);
 }
~DSPDeviceMIMOEngine()
DSPDeviceMIMOEngine::~DSPDeviceMIMOEngine ()
Definition at line 60 of file dspdevicemimoengine.cpp.
References stop().
 {
     stop();
     wait();
 }
Member Function Documentation
addAncillarySink()
void DSPDeviceMIMOEngine::addAncillarySink (BasebandSampleSink * sink, int index = 0)
Add an ancillary sink like a I/Q recorder.
Definition at line 192 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::addAncillarySink().
 {
     qDebug() << "DSPDeviceMIMOEngine::addSink: "
         << sink->objectName().toStdString().c_str()
         << " at: "
         << index;
     AddBasebandSampleSink cmd(sink, index);
     m_syncMessenger.sendWait(cmd);
 }
addChannelSink()
void DSPDeviceMIMOEngine::addChannelSink (ThreadedBasebandSampleSink * sink, int index = 0)
Add a channel sink that will run on its own thread.
Definition at line 172 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::addChannelSink().
 {
     qDebug() << "DSPDeviceMIMOEngine::addThreadedSink: "
         << sink->objectName().toStdString().c_str()
         << " at: "
         << index;
     AddThreadedBasebandSampleSink cmd(sink, index);
     m_syncMessenger.sendWait(cmd);
 }
addChannelSource()
void DSPDeviceMIMOEngine::addChannelSource (ThreadedBasebandSampleSource * source, int index = 0)
Add a channel source that will run on its own thread.
Definition at line 152 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
 {
     qDebug() << "DSPDeviceMIMOEngine::addThreadedSource: "
         << source->objectName().toStdString().c_str()
         << " at: "
         << index;
     AddThreadedBasebandSampleSource cmd(source, index);
     m_syncMessenger.sendWait(cmd);
 }
addSinkStream()
void DSPDeviceMIMOEngine::addSinkStream (bool connect)
Definition at line 138 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::addSinkStream().
 {
     qDebug("DSPDeviceMIMOEngine::addSinkStream");
     AddSinkStream cmd(connect);
     m_syncMessenger.sendWait(cmd);
 }
addSourceStream()
void DSPDeviceMIMOEngine::addSourceStream (bool connect)
Definition at line 124 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::addSourceStream().
 {
     qDebug("DSPDeviceMIMOEngine::addSourceStream");
     AddSourceStream cmd(connect);
     m_syncMessenger.sendWait(cmd);
 }
addSpectrumSink()
void DSPDeviceMIMOEngine::addSpectrumSink (BasebandSampleSink * spectrumSink)
Add a spectrum vis baseband sample sink.
Definition at line 212 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by MainWindow::addMIMODevice().
 {
     qDebug() << "DSPDeviceMIMOEngine::addSpectrumSink: " << spectrumSink->objectName().toStdString().c_str();
     AddSpectrumSink cmd(spectrumSink);
     m_syncMessenger.sendWait(cmd);
 }
configureCorrections()
void DSPDeviceMIMOEngine::configureCorrections (bool dcOffsetCorrection, bool iqImbalanceCorrection, int isource)
Configure source DSP corrections.
Definition at line 1038 of file dspdevicemimoengine.cpp.
References m_inputMessageQueue, and MessageQueue::push().
Referenced by DeviceAPI::configureCorrections().
 {
     qDebug() << "DSPDeviceMIMOEngine::configureCorrections";
     ConfigureCorrection* cmd = new ConfigureCorrection(dcOffsetCorrection, iqImbalanceCorrection, isource);
     m_inputMessageQueue.push(cmd);
 }
deviceDescription()
QString DSPDeviceMIMOEngine::deviceDescription ()
Return the device description.
Definition at line 243 of file dspdevicemimoengine.cpp.
References DSPDeviceMIMOEngine::GetMIMODeviceDescription::getDeviceDescription(), m_syncMessenger, and SyncMessenger::sendWait().
 {
     qDebug() << "DSPDeviceMIMOEngine::deviceDescription";
     GetMIMODeviceDescription cmd;
     m_syncMessenger.sendWait(cmd);
     return cmd.getDeviceDescription();
 }
errorMessage()
QString DSPDeviceMIMOEngine::errorMessage ()
Return the current error message.
Definition at line 235 of file dspdevicemimoengine.cpp.
References DSPDeviceMIMOEngine::GetErrorMessage::getErrorMessage(), m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::errorMessage(), and gotoError().
 {
     qDebug() << "DSPDeviceMIMOEngine::errorMessage";
     GetErrorMessage cmd;
     m_syncMessenger.sendWait(cmd);
     return cmd.getErrorMessage();
 }
getInputMessageQueue()
MessageQueue* DSPDeviceMIMOEngine::getInputMessageQueue () inline
Definition at line 245 of file dspdevicemimoengine.h.
Referenced by DeviceAPI::getDeviceEngineInputMessageQueue().
 { return &m_inputMessageQueue; }
getMIMO()
DeviceSampleMIMO* DSPDeviceMIMOEngine::getMIMO () inline
Definition at line 255 of file dspdevicemimoengine.h.
Referenced by DeviceAPI::getSampleMIMO(), DeviceAPI::getSamplingDeviceGUIMessageQueue(), and DeviceAPI::getSamplingDeviceInputMessageQueue().
 { return m_deviceSampleMIMO; }
getUID()
uint DSPDeviceMIMOEngine::getUID () const inline
Definition at line 257 of file dspdevicemimoengine.h.
Referenced by MainWindow::addMIMODevice(), and DeviceAPI::getDeviceUID().
 { return m_uid; }
gotoError()
DSPDeviceMIMOEngine::State DSPDeviceMIMOEngine::gotoError (const QString & errorMsg) private
Go to an error state.
Definition at line 615 of file dspdevicemimoengine.cpp.
References errorMessage(), m_deviceDescription, m_errorMessage, m_state, and StError.
Referenced by gotoInit(), and gotoRunning().
 {
     qDebug() << "DSPDeviceMIMOEngine::gotoError: " << errorMessage;
     m_errorMessage = errorMessage;
     m_deviceDescription.clear();
     m_state = StError;
     return StError;
 }
gotoIdle()
DSPDeviceMIMOEngine::State DSPDeviceMIMOEngine::gotoIdle () private
Go to the idle state.
Definition at line 422 of file dspdevicemimoengine.cpp.
References m_basebandSampleSinks, m_deviceDescription, m_deviceSampleMIMO, m_state, m_threadedBasebandSampleSinks, StError, StIdle, StNotStarted, DeviceSampleMIMO::stop(), StReady, and StRunning.
Referenced by handleSynchronousMessages(), and stop().
 {
     qDebug() << "DSPDeviceMIMOEngine::gotoIdle";
     switch(m_state) {
         case StNotStarted:
             return StNotStarted;
         case StIdle:
         case StError:
             return StIdle;
         case StReady:
         case StRunning:
             break;
     }
     if (!m_deviceSampleMIMO) {
         return StIdle;
     }
     // stop everything
     std::vector<BasebandSampleSinks>::const_iterator vbit = m_basebandSampleSinks.begin();
     for (; vbit != m_basebandSampleSinks.end(); ++vbit)
     {
         for (BasebandSampleSinks::const_iterator it = vbit->begin(); it != vbit->end(); ++it) {
             (*it)->stop();
         }
     }
     std::vector<ThreadedBasebandSampleSinks>::const_iterator vtit = m_threadedBasebandSampleSinks.begin();
     for (; vtit != m_threadedBasebandSampleSinks.end(); vtit++)
     {
         for (ThreadedBasebandSampleSinks::const_iterator it = vtit->begin(); it != vtit->end(); ++it) {
             (*it)->stop();
         }
     }
     m_deviceSampleMIMO->stop();
     m_deviceDescription.clear();
     return StIdle;
 }
gotoInit()
DSPDeviceMIMOEngine::State DSPDeviceMIMOEngine::gotoInit () private
Go to the acquisition init state from idle.
Definition at line 469 of file dspdevicemimoengine.cpp.
References DeviceSampleMIMO::getDeviceDescription(), DeviceSampleMIMO::getNbSinkFifos(), DeviceSampleMIMO::getSourceCenterFrequency(), DeviceSampleMIMO::getSourceSampleRate(), gotoError(), m_basebandSampleSinks, m_deviceDescription, m_deviceSampleMIMO, m_sourcesCorrections, m_state, m_threadedBasebandSampleSinks, StError, StIdle, StNotStarted, StReady, and StRunning.
Referenced by handleSynchronousMessages().
 {
     switch(m_state) {
         case StNotStarted:
             return StNotStarted;
         case StRunning: // FIXME: assumes it goes first through idle state. Could we get back to init from running directly?
             return StRunning;
         case StReady:
             return StReady;
         case StIdle:
         case StError:
             break;
     }
     if (!m_deviceSampleMIMO) {
         return gotoError("No sample MIMO configured");
     }
     // init: pass sample rate and center frequency to all sample rate and/or center frequency dependent sinks and wait for completion
     m_deviceDescription = m_deviceSampleMIMO->getDeviceDescription();
     qDebug() << "DSPDeviceMIMOEngine::gotoInit: "
             << " m_deviceDescription: " << m_deviceDescription.toStdString().c_str();
     // Rx
     for (unsigned int isource = 0; isource < m_deviceSampleMIMO->getNbSinkFifos(); isource++)
     {
         if (isource < m_sourcesCorrections.size())
         {
             m_sourcesCorrections[isource].m_iOffset = 0;
             m_sourcesCorrections[isource].m_qOffset = 0;
             m_sourcesCorrections[isource].m_iRange = 1 << 16;
             m_sourcesCorrections[isource].m_qRange = 1 << 16;
         }
         quint64 sourceCenterFrequency = m_deviceSampleMIMO->getSourceCenterFrequency(isource);
         int sourceStreamSampleRate = m_deviceSampleMIMO->getSourceSampleRate(isource);
         qDebug("DSPDeviceMIMOEngine::gotoInit: m_sourceCenterFrequencies[%d] = %llu", isource,  sourceCenterFrequency);
         qDebug("DSPDeviceMIMOEngine::gotoInit: m_sourceStreamSampleRates[%d] = %d", isource,  sourceStreamSampleRate);
         DSPSignalNotification notif(sourceStreamSampleRate, sourceCenterFrequency);
         if (isource < m_basebandSampleSinks.size())
         {
             for (BasebandSampleSinks::const_iterator it = m_basebandSampleSinks[isource].begin(); it != m_basebandSampleSinks[isource].end(); ++it)
             {
                 qDebug() << "DSPDeviceMIMOEngine::gotoInit: initializing " << (*it)->objectName().toStdString().c_str();
                 (*it)->handleMessage(notif);
             }
         }
         if (isource < m_threadedBasebandSampleSinks.size())
         {
             for (ThreadedBasebandSampleSinks::const_iterator it = m_threadedBasebandSampleSinks[isource].begin(); it != m_threadedBasebandSampleSinks[isource].end(); ++it)
             {
                 qDebug() << "DSPDeviceMIMOEngine::gotoInit: initializing ThreadedSampleSink(" << (*it)->getSampleSinkObjectName().toStdString().c_str() << ")";
                 (*it)->handleSinkMessage(notif);
             }
         }
         // Probably not necessary
         // // possibly forward to spectrum sink
         // if ((m_spectrumSink) && (m_spectrumInputSourceElseSink) && (isource == m_spectrumInputIndex)) {
         //     m_spectrumSink->handleMessage(notif);
         // }
         // // forward changes to MIMO GUI input queue
         // MessageQueue *guiMessageQueue = m_deviceSampleMIMO->getMessageQueueToGUI();
         // if (guiMessageQueue) {
         //     DSPMIMOSignalNotification* rep = new DSPMIMOSignalNotification(sourceStreamSampleRate, sourceCenterFrequency, true, isource); // make a copy for the MIMO GUI
         //     guiMessageQueue->push(rep);
         // }
     }
     //TODO: Tx
     return StReady;
 }
gotoRunning()
DSPDeviceMIMOEngine::State DSPDeviceMIMOEngine::gotoRunning () private
Go to the running state from ready state.
Definition at line 556 of file dspdevicemimoengine.cpp.
References gotoError(), m_basebandSampleSinks, m_deviceDescription, m_deviceSampleMIMO, m_inputMessageQueue, m_state, m_threadedBasebandSampleSinks, MessageQueue::size(), DeviceSampleMIMO::start(), StError, StIdle, StNotStarted, StReady, and StRunning.
Referenced by handleSynchronousMessages().
 {
     qDebug() << "DSPDeviceMIMOEngine::gotoRunning";
     switch(m_state)
     {
         case StNotStarted:
             return StNotStarted;
         case StIdle:
             return StIdle;
         case StRunning:
             return StRunning;
         case StReady:
         case StError:
             break;
     }
     if (!m_deviceSampleMIMO) {
         return gotoError("DSPDeviceMIMOEngine::gotoRunning: No sample source configured");
     }
     qDebug() << "DSPDeviceMIMOEngine::gotoRunning: " << m_deviceDescription.toStdString().c_str() << " started";
     // Start everything
     if (!m_deviceSampleMIMO->start()) {
         return gotoError("Could not start sample source");
     }
     std::vector<BasebandSampleSinks>::const_iterator vbit = m_basebandSampleSinks.begin();
     for (; vbit != m_basebandSampleSinks.end(); ++vbit)
     {
         for (BasebandSampleSinks::const_iterator it = vbit->begin(); it != vbit->end(); ++it)
         {
             qDebug() << "DSPDeviceMIMOEngine::gotoRunning: starting " << (*it)->objectName().toStdString().c_str();
             (*it)->start();
         }
     }
     std::vector<ThreadedBasebandSampleSinks>::const_iterator vtit = m_threadedBasebandSampleSinks.begin();
     for (; vtit != m_threadedBasebandSampleSinks.end(); vtit++)
     {
         for (ThreadedBasebandSampleSinks::const_iterator it = vtit->begin(); it != vtit->end(); ++it)
         {
             qDebug() << "DSPDeviceMIMOEngine::gotoRunning: starting ThreadedSampleSink(" << (*it)->getSampleSinkObjectName().toStdString().c_str() << ")";
             (*it)->start();
         }
     }
     qDebug() << "DSPDeviceMIMOEngine::gotoRunning:input message queue pending: " << m_inputMessageQueue.size();
     return StRunning;
 }
handleData
void DSPDeviceMIMOEngine::handleData () private slot
Handle data when samples have to be processed.
Definition at line 625 of file dspdevicemimoengine.cpp.
References m_state, StRunning, and work().
Referenced by handleSetMIMO().
 {
     if (m_state == StRunning)
     {
         work(0); // TODO: implement Tx side
     }
 }
handleForwardToSpectrumSink
void DSPDeviceMIMOEngine::handleForwardToSpectrumSink (int nbSamples) private slot
Definition at line 1046 of file dspdevicemimoengine.cpp.
References BasebandSampleSink::feed(), SampleSourceFifo::getReadIterator(), DeviceSampleMIMO::getSampleSourceFifo(), m_deviceSampleMIMO, m_spectrumInputIndex, and m_spectrumSink.
Referenced by handleSynchronousMessages().
 {
     if ((m_spectrumSink) && (m_spectrumInputIndex < m_deviceSampleMIMO->getNbSinkStreams()))
     {
         SampleSourceFifo* sampleFifo = m_deviceSampleMIMO->getSampleSourceFifo(m_spectrumInputIndex);
         SampleVector::iterator readUntil;
         sampleFifo->getReadIterator(readUntil);
         m_spectrumSink->feed(readUntil - nbSamples, readUntil, false);
     }
 }
handleInputMessages
void DSPDeviceMIMOEngine::handleInputMessages () private slot
Handle input message queue.
Definition at line 894 of file dspdevicemimoengine.cpp.
References DSPMIMOSignalNotification::getCenterFrequency(), DSPDeviceMIMOEngine::ConfigureCorrection::getDCOffsetCorrection(), Message::getIdentifier(), DSPDeviceMIMOEngine::ConfigureCorrection::getIndex(), DSPMIMOSignalNotification::getIndex(), DSPDeviceMIMOEngine::ConfigureCorrection::getIQImbalanceCorrection(), DeviceSampleMIMO::getMessageQueueToGUI(), DSPMIMOSignalNotification::getSampleRate(), DSPMIMOSignalNotification::getSourceOrSink(), BasebandSampleSink::handleMessage(), m_basebandSampleSinks, m_deviceSampleMIMO, m_inputMessageQueue, m_sourcesCorrections, m_spectrumInputIndex, m_spectrumInputSourceElseSink, m_spectrumSink, m_threadedBasebandSampleSinks, m_threadedBasebandSampleSources, Message::match(), MessageQueue::pop(), and MessageQueue::push().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("DSPDeviceMIMOEngine::handleInputMessages: message: %s", message->getIdentifier());
         if (ConfigureCorrection::match(*message))
         {
             ConfigureCorrection* conf = (ConfigureCorrection*) message;
             unsigned int isource = conf->getIndex();
             if (isource < m_sourcesCorrections.size())
             {
                 m_sourcesCorrections[isource].m_iqImbalanceCorrection = conf->getIQImbalanceCorrection();
                 if (m_sourcesCorrections[isource].m_dcOffsetCorrection != conf->getDCOffsetCorrection())
                 {
                     m_sourcesCorrections[isource].m_dcOffsetCorrection = conf->getDCOffsetCorrection();
                     m_sourcesCorrections[isource].m_iOffset = 0;
                     m_sourcesCorrections[isource].m_qOffset = 0;
                     if (m_sourcesCorrections[isource].m_iqImbalanceCorrection != conf->getIQImbalanceCorrection())
                     {
                         m_sourcesCorrections[isource].m_iqImbalanceCorrection = conf->getIQImbalanceCorrection();
                         m_sourcesCorrections[isource].m_iRange = 1 << 16;
                         m_sourcesCorrections[isource].m_qRange = 1 << 16;
                         m_sourcesCorrections[isource].m_imbalance = 65536;
                     }
                 }
                 m_sourcesCorrections[isource].m_iBeta.reset();
                 m_sourcesCorrections[isource].m_qBeta.reset();
                 m_sourcesCorrections[isource].m_avgAmp.reset();
                 m_sourcesCorrections[isource].m_avgII.reset();
                 m_sourcesCorrections[isource].m_avgII2.reset();
                 m_sourcesCorrections[isource].m_avgIQ.reset();
                 m_sourcesCorrections[isource].m_avgPhi.reset();
                 m_sourcesCorrections[isource].m_avgQQ2.reset();
                 m_sourcesCorrections[isource].m_iBeta.reset();
                 m_sourcesCorrections[isource].m_qBeta.reset();
             }
             delete message;
         }
         else if (DSPMIMOSignalNotification::match(*message))
         {
             DSPMIMOSignalNotification *notif = (DSPMIMOSignalNotification *) message;
             // update DSP values
             bool sourceElseSink = notif->getSourceOrSink();
             unsigned int istream = notif->getIndex();
             int sampleRate = notif->getSampleRate();
             qint64 centerFrequency = notif->getCenterFrequency();
             qDebug() << "DeviceMIMOEngine::handleInputMessages: DSPMIMOSignalNotification:"
                 << " sourceElseSink: " << sourceElseSink
                 << " istream: " << istream
                 << " sampleRate: " << sampleRate
                 << " centerFrequency: " << centerFrequency;
             if (sourceElseSink)
             {
                 if ((istream < m_deviceSampleMIMO->getNbSourceStreams()))
                 {
                     DSPSignalNotification *message = new DSPSignalNotification(sampleRate, centerFrequency);
                     // forward source changes to ancillary sinks with immediate execution (no queuing)
                     if (istream < m_basebandSampleSinks.size())
                     {
                         for (BasebandSampleSinks::const_iterator it = m_basebandSampleSinks[istream].begin(); it != m_basebandSampleSinks[istream].end(); ++it)
{
                             qDebug() << "DSPDeviceMIMOEngine::gotoRunning: starting " << (*it)->objectName().toStdString().c_str();
                             (*it)->handleMessage(*message);
                         }
                     }
                     // forward source changes to channel sinks with immediate execution (no queuing)
                     if (istream < m_threadedBasebandSampleSinks.size())
                     {
                         for (ThreadedBasebandSampleSinks::const_iterator it = m_threadedBasebandSampleSinks[istream].begin(); it != m_threadedBasebandSampleSinks[istream].end(); ++it)
{
                             qDebug() << "DSPDeviceMIMOEngine::handleSourceMessages: forward message to ThreadedSampleSink(" << (*it)->getSampleSinkObjectName().toStdString().c_str() << ")";
                             (*it)->handleSinkMessage(*message);
                         }
                     }
                     // forward changes to MIMO GUI input queue
                     MessageQueue *guiMessageQueue = m_deviceSampleMIMO->getMessageQueueToGUI();
                     qDebug("DeviceMIMOEngine::handleInputMessages: DSPMIMOSignalNotification: guiMessageQueue: %p", guiMessageQueue);
                     if (guiMessageQueue) {
                         DSPMIMOSignalNotification* rep = new DSPMIMOSignalNotification(*notif); // make a copy for the MIMO GUI
                         guiMessageQueue->push(rep);
                     }
                     // forward changes to spectrum sink if currently active
                     if (m_spectrumSink && m_spectrumInputSourceElseSink && (m_spectrumInputIndex == istream))
                     {
                         DSPSignalNotification spectrumNotif(sampleRate, centerFrequency);
                         m_spectrumSink->handleMessage(spectrumNotif);
                     }
                 }
             }
             else
             {
                 if ((istream < m_deviceSampleMIMO->getNbSinkStreams()))
                 {
                     DSPSignalNotification *message = new DSPSignalNotification(sampleRate, centerFrequency);
                     // forward source changes to channel sources with immediate execution (no queuing)
                     if (istream < m_threadedBasebandSampleSources.size())
                     {
                         for (ThreadedBasebandSampleSources::const_iterator it = m_threadedBasebandSampleSources[istream].begin(); it != m_threadedBasebandSampleSources[istream].end(); ++it)
{
                             qDebug() << "DSPDeviceMIMOEngine::handleSinkMessages: forward message to ThreadedSampleSource(" << (*it)->getSampleSourceObjectName().toStdString().c_str() << ")";
                             (*it)->handleSourceMessage(*message);
                         }
                     }
                     // forward changes to MIMO GUI input queue
                     MessageQueue *guiMessageQueue = m_deviceSampleMIMO->getMessageQueueToGUI();
                     qDebug("DSPDeviceMIMOEngine::handleInputMessages: DSPSignalNotification: guiMessageQueue: %p", guiMessageQueue);
                     if (guiMessageQueue) {
                         DSPMIMOSignalNotification* rep = new DSPMIMOSignalNotification(*notif); // make a copy for the source GUI
                         guiMessageQueue->push(rep);
                     }
                     // forward changes to spectrum sink if currently active
                     if (m_spectrumSink && !m_spectrumInputSourceElseSink && (m_spectrumInputIndex == istream))
                     {
                         DSPSignalNotification spectrumNotif(sampleRate, centerFrequency);
                         m_spectrumSink->handleMessage(spectrumNotif);
                     }
                 }
             }
             delete message;
         }
     }
 }
handleSetMIMO()
void DSPDeviceMIMOEngine::handleSetMIMO (DeviceSampleMIMO * mimo) private
Manage MIMO device setting.
Definition at line 633 of file dspdevicemimoengine.cpp.
References SampleSinkFifo::dataReady(), DeviceSampleMIMO::getDeviceDescription(), DeviceSampleMIMO::getSampleSinkFifo(), handleData(), m_deviceSampleMIMO, m_sampleSinkConnectionIndexes, m_sampleSourceConnectionIndexes, and workSampleSink().
Referenced by handleSynchronousMessages().
 {
     m_deviceSampleMIMO = mimo;
     if (mimo)
     {
         if ((m_sampleSinkConnectionIndexes.size() == 1) && (m_sampleSourceConnectionIndexes.size() == 0)) // true MIMO (synchronous FIFOs)
         {
             qDebug("DSPDeviceMIMOEngine::handleSetMIMO: synchronous set %s", qPrintable(mimo->getDeviceDescription()));
             // connect(m_deviceSampleMIMO->getSampleSinkFifo(m_sampleSinkConnectionIndexes[0]), SIGNAL(dataReady()), this, SLOT(handleData()), Qt::QueuedConnection);
             QObject::connect(
                 m_deviceSampleMIMO->getSampleSinkFifo(m_sampleSinkConnectionIndexes[0]),
                 &SampleSinkFifo::dataReady,
                 this,
                 [=](){ this->handleData(); }, // lambda function is not strictly needed here
                 Qt::QueuedConnection
             );
         }
         else if (m_sampleSinkConnectionIndexes.size() != 0) // asynchronous FIFOs
         {
             for (unsigned int isink = 0; isink < m_sampleSinkConnectionIndexes.size(); isink++)
             {
                 qDebug("DSPDeviceMIMOEngine::handleSetMIMO: asynchronous sources set %s channel %u",
                     qPrintable(mimo->getDeviceDescription()), isink);
                 QObject::connect(
                     m_deviceSampleMIMO->getSampleSinkFifo(m_sampleSinkConnectionIndexes[isink]),
                     &SampleSinkFifo::dataReady,
                     this,
                     [=](){ this->workSampleSink(isink); },
                     Qt::QueuedConnection
                 );
             }
         }
     }
     // TODO: Tx
 }
handleSynchronousMessages
void DSPDeviceMIMOEngine::handleSynchronousMessages () private slot
Handle synchronous messages with the thread.
Definition at line 671 of file dspdevicemimoengine.cpp.
References SyncMessenger::done(), Message::getIdentifier(), DSPDeviceMIMOEngine::AddThreadedBasebandSampleSource::getIndex(), DSPDeviceMIMOEngine::RemoveThreadedBasebandSampleSource::getIndex(), DSPDeviceMIMOEngine::AddThreadedBasebandSampleSink::getIndex(), DSPDeviceMIMOEngine::RemoveThreadedBasebandSampleSink::getIndex(), DSPDeviceMIMOEngine::AddBasebandSampleSink::getIndex(), DSPDeviceMIMOEngine::RemoveBasebandSampleSink::getIndex(), DSPDeviceMIMOEngine::SetSpectrumSinkInput::getIndex(), SyncMessenger::getMessage(), DSPDeviceMIMOEngine::AddBasebandSampleSink::getSampleSink(), DeviceSampleMIMO::getSampleSourceFifo(), DeviceSampleMIMO::getSinkCenterFrequency(), DeviceSampleMIMO::getSinkSampleRate(), DeviceSampleMIMO::getSourceCenterFrequency(), DSPDeviceMIMOEngine::SetSpectrumSinkInput::getSourceElseSink(), DeviceSampleMIMO::getSourceSampleRate(), DSPDeviceMIMOEngine::AddThreadedBasebandSampleSink::getThreadedSampleSink(), DSPDeviceMIMOEngine::RemoveThreadedBasebandSampleSink::getThreadedSampleSink(), DSPDeviceMIMOEngine::AddThreadedBasebandSampleSource::getThreadedSampleSource(), DSPDeviceMIMOEngine::RemoveThreadedBasebandSampleSource::getThreadedSampleSource(), gotoIdle(), gotoInit(), gotoRunning(), handleForwardToSpectrumSink(), BasebandSampleSink::handleMessage(), handleSetMIMO(), ThreadedBasebandSampleSink::handleSinkMessage(), ThreadedBasebandSampleSource::handleSourceMessage(), m_basebandSampleSinks, m_deviceDescription, m_deviceSampleMIMO, m_errorMessage, m_sampleSinkConnectionIndexes, m_sampleSourceConnectionIndexes, m_sourcesCorrections, m_spectrumInputIndex, m_spectrumInputSourceElseSink, m_spectrumSink, m_state, m_syncMessenger, m_threadedBasebandSampleSinks, m_threadedBasebandSampleSources, Message::match(), ThreadedBasebandSampleSource::start(), BasebandSampleSink::start(), ThreadedBasebandSampleSink::start(), StIdle, ThreadedBasebandSampleSource::stop(), BasebandSampleSink::stop(), ThreadedBasebandSampleSink::stop(), StReady, and StRunning.
Referenced by stopProcess().
 {
     Message *message = m_syncMessenger.getMessage();
     qDebug() << "DSPDeviceMIMOEngine::handleSynchronousMessages: " << message->getIdentifier();
     if (DSPGenerationInit::match(*message))
     {
         m_state = gotoIdle();
         if(m_state == StIdle) {
             m_state = gotoInit(); // State goes ready if init is performed
         }
     }
     else if (DSPGenerationStart::match(*message))
     {
         if(m_state == StReady) {
             m_state = gotoRunning();
         }
     }
     else if (DSPGenerationStop::match(*message))
     {
         m_state = gotoIdle();
     }
     else if (GetMIMODeviceDescription::match(*message))
     {
         ((GetMIMODeviceDescription*) message)->setDeviceDescription(m_deviceDescription);
     }
     else if (DSPGetErrorMessage::match(*message))
     {
         ((DSPGetErrorMessage*) message)->setErrorMessage(m_errorMessage);
     }
     else if (SetSampleMIMO::match(*message)) {
         handleSetMIMO(((SetSampleMIMO*) message)->getSampleMIMO());
     }
     else if (AddSourceStream::match(*message))
     {
         m_basebandSampleSinks.push_back(BasebandSampleSinks());
         int currentIndex = m_threadedBasebandSampleSinks.size();
         m_threadedBasebandSampleSinks.push_back(ThreadedBasebandSampleSinks());
         m_sourcesCorrections.push_back(SourceCorrection());
         if (((AddSourceStream *) message)->getConnect()) {
             m_sampleSinkConnectionIndexes.push_back(currentIndex);
         }
     }
     else if (RemoveLastSourceStream::match(*message))
     {
         m_basebandSampleSinks.pop_back();
         m_threadedBasebandSampleSinks.pop_back();
     }
     else if (AddSinkStream::match(*message))
     {
         int currentIndex = m_threadedBasebandSampleSources.size();
         m_threadedBasebandSampleSources.push_back(ThreadedBasebandSampleSources());
         if (((AddSinkStream *) message)->getConnect()) {
             m_sampleSourceConnectionIndexes.push_back(currentIndex);
         }
     }
     else if (RemoveLastSinkStream::match(*message))
     {
         m_threadedBasebandSampleSources.pop_back();
     }
     else if (AddBasebandSampleSink::match(*message))
     {
         const AddBasebandSampleSink *msg = (AddBasebandSampleSink *) message;
         BasebandSampleSink* sink = msg->getSampleSink();
         unsigned int isource = msg->getIndex();
         if (isource < m_basebandSampleSinks.size())
         {
             m_basebandSampleSinks[isource].push_back(sink);
             // initialize sample rate and center frequency in the sink:
             int sourceStreamSampleRate = m_deviceSampleMIMO->getSourceSampleRate(isource);
             quint64 sourceCenterFrequency = m_deviceSampleMIMO->getSourceCenterFrequency(isource);
             DSPSignalNotification msg(sourceStreamSampleRate, sourceCenterFrequency);
             sink->handleMessage(msg);
             // start the sink:
             if(m_state == StRunning) {
                 sink->start();
             }
         }
     }
     else if (RemoveBasebandSampleSink::match(*message))
     {
         const RemoveBasebandSampleSink *msg = (RemoveBasebandSampleSink *) message;
         BasebandSampleSink* sink = ((DSPRemoveBasebandSampleSink*) message)->getSampleSink();
         unsigned int isource = msg->getIndex();
         if (isource < m_basebandSampleSinks.size())
         {
             if(m_state == StRunning) {
                 sink->stop();
             }
             m_basebandSampleSinks[isource].remove(sink);
         }
     }
     else if (AddThreadedBasebandSampleSink::match(*message))
     {
         const AddThreadedBasebandSampleSink *msg = (AddThreadedBasebandSampleSink *) message;
         ThreadedBasebandSampleSink *threadedSink = msg->getThreadedSampleSink();
         unsigned int isource = msg->getIndex();
         if (isource < m_threadedBasebandSampleSinks.size())
         {
             m_threadedBasebandSampleSinks[isource].push_back(threadedSink);
             // initialize sample rate and center frequency in the sink:
             int sourceStreamSampleRate = m_deviceSampleMIMO->getSourceSampleRate(isource);
             quint64 sourceCenterFrequency = m_deviceSampleMIMO->getSourceCenterFrequency(isource);
             DSPSignalNotification msg(sourceStreamSampleRate, sourceCenterFrequency);
             threadedSink->handleSinkMessage(msg);
             // start the sink:
             if(m_state == StRunning) {
                 threadedSink->start();
             }
         }
     }
     else if (RemoveThreadedBasebandSampleSink::match(*message))
     {
         const RemoveThreadedBasebandSampleSink *msg = (RemoveThreadedBasebandSampleSink *) message;
         ThreadedBasebandSampleSink* threadedSink = msg->getThreadedSampleSink();
         unsigned int isource = msg->getIndex();
         if (isource < m_threadedBasebandSampleSinks.size())
         {
             threadedSink->stop();
             m_threadedBasebandSampleSinks[isource].remove(threadedSink);
         }
     }
     else if (AddThreadedBasebandSampleSource::match(*message))
     {
         const AddThreadedBasebandSampleSource *msg = (AddThreadedBasebandSampleSource *) message;
         ThreadedBasebandSampleSource *threadedSource = msg->getThreadedSampleSource();
         unsigned int isink = msg->getIndex();
         if (isink < m_threadedBasebandSampleSources.size())
         {
             m_threadedBasebandSampleSources[isink].push_back(threadedSource);
             // initialize sample rate and center frequency in the sink:
             int sinkStreamSampleRate = m_deviceSampleMIMO->getSinkSampleRate(isink);
             quint64 sinkCenterFrequency = m_deviceSampleMIMO->getSinkCenterFrequency(isink);
             DSPSignalNotification msg(sinkStreamSampleRate, sinkCenterFrequency);
             threadedSource->handleSourceMessage(msg);
             // start the sink:
             if(m_state == StRunning) {
                 threadedSource->start();
             }
         }
     }
     else if (RemoveThreadedBasebandSampleSource::match(*message))
     {
         const RemoveThreadedBasebandSampleSource *msg = (RemoveThreadedBasebandSampleSource *) message;
         ThreadedBasebandSampleSource* threadedSource = msg->getThreadedSampleSource();
         unsigned int isink = msg->getIndex();
         if (isink < m_threadedBasebandSampleSources.size())
         {
             threadedSource->stop();
             m_threadedBasebandSampleSources[isink].remove(threadedSource);
         }
     }
     else if (AddSpectrumSink::match(*message))
     {
         m_spectrumSink = ((AddSpectrumSink*) message)->getSampleSink();
     }
     else if (RemoveSpectrumSink::match(*message))
     {
         BasebandSampleSink* spectrumSink = ((DSPRemoveSpectrumSink*) message)->getSampleSink();
         spectrumSink->stop();
         if (!m_spectrumInputSourceElseSink && m_deviceSampleMIMO && (m_spectrumInputIndex <  m_deviceSampleMIMO->getNbSinkStreams()))
         {
             SampleSourceFifo *inputFIFO = m_deviceSampleMIMO->getSampleSourceFifo(m_spectrumInputIndex);
             disconnect(inputFIFO, SIGNAL(dataRead(int)), this, SLOT(handleForwardToSpectrumSink(int)));
         }
         m_spectrumSink = nullptr;
     }
     else if (SetSpectrumSinkInput::match(*message))
     {
         const SetSpectrumSinkInput *msg = (SetSpectrumSinkInput *) message;
         bool spectrumInputSourceElseSink = msg->getSourceElseSink();
         unsigned int spectrumInputIndex = msg->getIndex();
         if ((spectrumInputSourceElseSink != m_spectrumInputSourceElseSink) || (spectrumInputIndex != m_spectrumInputIndex))
         {
             if (!m_spectrumInputSourceElseSink) // remove the source listener
             {
                 SampleSourceFifo *inputFIFO = m_deviceSampleMIMO->getSampleSourceFifo(m_spectrumInputIndex);
                 disconnect(inputFIFO, SIGNAL(dataRead(int)), this, SLOT(handleForwardToSpectrumSink(int)));
             }
             if ((!spectrumInputSourceElseSink) && (spectrumInputIndex <  m_deviceSampleMIMO->getNbSinkStreams())) // add the source listener
             {
                 SampleSourceFifo *inputFIFO = m_deviceSampleMIMO->getSampleSourceFifo(spectrumInputIndex);
                 connect(inputFIFO, SIGNAL(dataRead(int)), this, SLOT(handleForwardToSpectrumSink(int)));
                 if (m_spectrumSink)
                 {
                     DSPSignalNotification notif(
                         m_deviceSampleMIMO->getSinkSampleRate(spectrumInputIndex),
                         m_deviceSampleMIMO->getSinkCenterFrequency(spectrumInputIndex));
                     m_spectrumSink->handleMessage(notif);
                 }
             }
             if (m_spectrumSink && (spectrumInputSourceElseSink) && (spectrumInputIndex <  m_deviceSampleMIMO->getNbSinkFifos()))
             {
                 DSPSignalNotification notif(
                     m_deviceSampleMIMO->getSourceSampleRate(spectrumInputIndex),
                     m_deviceSampleMIMO->getSourceCenterFrequency(spectrumInputIndex));
                 m_spectrumSink->handleMessage(notif);
             }
             m_spectrumInputSourceElseSink = spectrumInputSourceElseSink;
             m_spectrumInputIndex = spectrumInputIndex;
         }
     }
     m_syncMessenger.done(m_state);
 }
initProcess()
bool DSPDeviceMIMOEngine::initProcess ()
Initialize process sequence.
Definition at line 87 of file dspdevicemimoengine.cpp.
References m_syncMessenger, SyncMessenger::sendWait(), and StReady.
Referenced by DeviceAPI::initDeviceEngine().
 {
     qDebug() << "DSPDeviceMIMOEngine::initGeneration";
     DSPGenerationInit cmd;
     return m_syncMessenger.sendWait(cmd) == StReady;
 }
iqCorrections()
void DSPDeviceMIMOEngine::iqCorrections (SampleVector::iterator begin, SampleVector::iterator end, int isource, bool imbalanceCorrection) private
Definition at line 1057 of file dspdevicemimoengine.cpp.
References Fixed< IntType, IntBits >::as_internal(), m_sourcesCorrections, SDR_RX_SCALEF, and sqrt().
Referenced by workSampleSink().
 {
     for(SampleVector::iterator it = begin; it < end; it++)
     {
         m_sourcesCorrections[isource].m_iBeta(it->real());
         m_sourcesCorrections[isource].m_qBeta(it->imag());
         if (imbalanceCorrection)
         {
 #if IMBALANCE_INT
             // acquisition
             int64_t xi = (it->m_real - (int32_t) m_sourcesCorrections[isource].m_iBeta) << 5;
             int64_t xq = (it->m_imag - (int32_t) m_sourcesCorrections[isource].m_qBeta) << 5;
             // phase imbalance
             m_sourcesCorrections[isource].m_avgII((xi*xi)>>28); // <I", I">
             m_sourcesCorrections[isource].m_avgIQ((xi*xq)>>28); // <I", Q">
             if ((int64_t) m_sourcesCorrections[isource].m_avgII != 0)
             {
                 int64_t phi = (((int64_t) m_sourcesCorrections[isource].m_avgIQ)<<28) / (int64_t) m_sourcesCorrections[isource].m_avgII;
                 m_sourcesCorrections[isource].m_avgPhi(phi);
             }
             int64_t corrPhi = (((int64_t) m_sourcesCorrections[isource].m_avgPhi) * xq) >> 28;  //(m_avgPhi.asDouble()/16777216.0) * ((double) xq);
             int64_t yi = xi - corrPhi;
             int64_t yq = xq;
             // amplitude I/Q imbalance
             m_sourcesCorrections[isource].m_avgII2((yi*yi)>>28); // <I, I>
             m_sourcesCorrections[isource].m_avgQQ2((yq*yq)>>28); // <Q, Q>
             if ((int64_t) m_sourcesCorrections[isource].m_avgQQ2 != 0)
             {
                 int64_t a = (((int64_t) m_sourcesCorrections[isource].m_avgII2)<<28) / (int64_t) m_sourcesCorrections[isource].m_avgQQ2;
                 Fixed<int64_t, 28> fA(Fixed<int64_t, 28>::internal(), a);
                 Fixed<int64_t, 28> sqrtA = sqrt((Fixed<int64_t, 28>) fA);
                 m_sourcesCorrections[isource].m_avgAmp(sqrtA.as_internal());
             }
             int64_t zq = (((int64_t) m_sourcesCorrections[isource].m_avgAmp) * yq) >> 28;
             it->m_real = yi >> 5;
             it->m_imag = zq >> 5;
 #else
             // DC correction and conversion
             float xi = (it->m_real - (int32_t) m_sourcesCorrections[isource].m_iBeta) / SDR_RX_SCALEF;
             float xq = (it->m_imag - (int32_t) m_sourcesCorrections[isource].m_qBeta) / SDR_RX_SCALEF;
             // phase imbalance
             m_sourcesCorrections[isource].m_avgII(xi*xi); // <I", I">
             m_sourcesCorrections[isource].m_avgIQ(xi*xq); // <I", Q">
             if (m_sourcesCorrections[isource].m_avgII.asDouble() != 0) {
                 m_sourcesCorrections[isource].m_avgPhi(m_sourcesCorrections[isource].m_avgIQ.asDouble()/m_sourcesCorrections[isource].m_avgII.asDouble());
             }
             float& yi = xi; // the in phase remains the reference
             float yq = xq - m_sourcesCorrections[isource].m_avgPhi.asDouble()*xi;
             // amplitude I/Q imbalance
             m_sourcesCorrections[isource].m_avgII2(yi*yi); // <I, I>
             m_sourcesCorrections[isource].m_avgQQ2(yq*yq); // <Q, Q>
             if (m_sourcesCorrections[isource].m_avgQQ2.asDouble() != 0) {
                 m_sourcesCorrections[isource].m_avgAmp(sqrt(m_sourcesCorrections[isource].m_avgII2.asDouble() / m_sourcesCorrections[isource].m_avgQQ2.asDouble()));
             }
             // final correction
             float& zi = yi; // the in phase remains the reference
             float zq = m_sourcesCorrections[isource].m_avgAmp.asDouble() * yq;
             // convert and store
             it->m_real = zi * SDR_RX_SCALEF;
             it->m_imag = zq * SDR_RX_SCALEF;
 #endif
         }
         else
         {
             // DC correction only
             it->m_real -= (int32_t) m_sourcesCorrections[isource].m_iBeta;
             it->m_imag -= (int32_t) m_sourcesCorrections[isource].m_qBeta;
         }
     }
 }
removeAncillarySink()
void DSPDeviceMIMOEngine::removeAncillarySink (BasebandSampleSink * sink, int index = 0)
Remove an ancillary sample sink.
Definition at line 202 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::removeAncillarySink().
 {
     qDebug() << "DSPDeviceMIMOEngine::removeSink: "
         << sink->objectName().toStdString().c_str()
         << " at: "
         << index;
     RemoveBasebandSampleSink cmd(sink, index);
     m_syncMessenger.sendWait(cmd);
 }
removeChannelSink()
void DSPDeviceMIMOEngine::removeChannelSink (ThreadedBasebandSampleSink * sink, int index = 0)
Remove a channel sink that runs on its own thread.
Definition at line 182 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::removeChannelSink().
 {
     qDebug() << "DSPDeviceMIMOEngine::removeThreadedSink: "
         << sink->objectName().toStdString().c_str()
         << " at: "
         << index;
     RemoveThreadedBasebandSampleSink cmd(sink, index);
     m_syncMessenger.sendWait(cmd);
 }
removeChannelSource()
void DSPDeviceMIMOEngine::removeChannelSource (ThreadedBasebandSampleSource * source, int index = 0)
Remove a channel source that runs on its own thread.
Definition at line 162 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
 {
     qDebug() << "DSPDeviceMIMOEngine::removeThreadedSource: "
         << source->objectName().toStdString().c_str()
         << " at: "
         << index;
     RemoveThreadedBasebandSampleSource cmd(source, index);
     m_syncMessenger.sendWait(cmd);
 }
removeLastSinkStream()
void DSPDeviceMIMOEngine::removeLastSinkStream ()
Definition at line 145 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::removeLastSinkStream().
 {
     qDebug("DSPDeviceMIMOEngine::removeLastSinkStream");
     RemoveLastSourceStream cmd;
     m_syncMessenger.sendWait(cmd);
 }
removeLastSourceStream()
void DSPDeviceMIMOEngine::removeLastSourceStream ()
Definition at line 131 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::removeLastSourceStream().
 {
     qDebug("DSPDeviceMIMOEngine::removeLastSourceStream");
     RemoveLastSourceStream cmd;
     m_syncMessenger.sendWait(cmd);
 }
removeSpectrumSink()
void DSPDeviceMIMOEngine::removeSpectrumSink (BasebandSampleSink * spectrumSink)
Add a spectrum vis baseband sample sink.
Definition at line 219 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by MainWindow::removeLastDevice().
 {
     qDebug() << "DSPDeviceSinkEngine::removeSpectrumSink: " << spectrumSink->objectName().toStdString().c_str();
     DSPRemoveSpectrumSink cmd(spectrumSink);
     m_syncMessenger.sendWait(cmd);
 }
run()
void DSPDeviceMIMOEngine::run () private
Definition at line 66 of file dspdevicemimoengine.cpp.
References m_state, and StIdle.
 {
     qDebug() << "DSPDeviceMIMOEngine::run";
     m_state = StIdle;
     exec();
 }
setMIMO()
void DSPDeviceMIMOEngine::setMIMO (DeviceSampleMIMO * mimo)
Set the sample MIMO type.
Definition at line 111 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::setSampleMIMO().
 {
     qDebug() << "DSPDeviceMIMOEngine::setMIMO";
     SetSampleMIMO cmd(mimo);
     m_syncMessenger.sendWait(cmd);
 }
setMIMOSequence()
void DSPDeviceMIMOEngine::setMIMOSequence (int sequence)
Set the sample MIMO sequence in type.
Definition at line 118 of file dspdevicemimoengine.cpp.
References m_sampleMIMOSequence.
 {
     qDebug("DSPDeviceMIMOEngine::setSinkSequence: seq: %d", sequence);
     m_sampleMIMOSequence = sequence;
 }
setSpectrumSinkInput()
void DSPDeviceMIMOEngine::setSpectrumSinkInput (bool sourceElseSink, int index)
Definition at line 226 of file dspdevicemimoengine.cpp.
References m_syncMessenger, and SyncMessenger::sendWait().
Referenced by DeviceAPI::setSpectrumSinkInput().
 {
     qDebug() << "DSPDeviceSinkEngine::setSpectrumSinkInput: "
         << " sourceElseSink: " << sourceElseSink
         << " index: " << index;
     SetSpectrumSinkInput cmd(sourceElseSink, index);
     m_syncMessenger.sendWait(cmd);
 }
start()
void DSPDeviceMIMOEngine::start ()
This thread start.
Definition at line 73 of file dspdevicemimoengine.cpp.
Referenced by MainWindow::addMIMODevice().
 {
     qDebug() << "DSPDeviceMIMOEngine::start";
     QThread::start();
 }
startProcess()
bool DSPDeviceMIMOEngine::startProcess ()
Start process sequence.
Definition at line 95 of file dspdevicemimoengine.cpp.
References m_syncMessenger, SyncMessenger::sendWait(), and StRunning.
Referenced by DeviceAPI::startDeviceEngine().
 {
     qDebug() << "DSPDeviceMIMOEngine::startGeneration";
     DSPGenerationStart cmd;
     return m_syncMessenger.sendWait(cmd) == StRunning;
 }
state()
State DSPDeviceMIMOEngine::state () const inline
Return DSP engine current state.
Definition at line 276 of file dspdevicemimoengine.h.
Referenced by DeviceAPI::state().
stop()
void DSPDeviceMIMOEngine::stop ()
This thread stop.
Definition at line 79 of file dspdevicemimoengine.cpp.
References gotoIdle(), m_state, and StNotStarted.
Referenced by MainWindow::removeLastDevice(), and ~DSPDeviceMIMOEngine().
 {
     qDebug() << "DSPDeviceMIMOEngine::stop";
     gotoIdle();
     m_state = StNotStarted;
     QThread::exit();
 }
stopProcess()
void DSPDeviceMIMOEngine::stopProcess ()
Stop process sequence.
Definition at line 103 of file dspdevicemimoengine.cpp.
References handleSynchronousMessages(), m_syncMessenger, and SyncMessenger::storeMessage().
Referenced by MainWindow::removeLastDevice(), and DeviceAPI::stopDeviceEngine().
 {
     qDebug() << "DSPDeviceMIMOEngine::stopGeneration";
     DSPGenerationStop cmd;
     m_syncMessenger.storeMessage(cmd);
     handleSynchronousMessages();
 }
work()
void DSPDeviceMIMOEngine::work (int nbWriteSamples) private
transfer samples if in running state
Routes samples from device source FIFO to sink channels that are registered for the FIFO Routes samples from source channels registered for the FIFO to the device sink FIFO
Definition at line 255 of file dspdevicemimoengine.cpp.
References BasebandSampleSink::feed(), SampleSinkFifo::fill(), DeviceSampleMIMO::getNbSourceStreams(), DeviceSampleMIMO::getSampleSinkFifo(), m_basebandSampleSinks, m_deviceSampleMIMO, m_inputMessageQueue, m_spectrumInputIndex, m_spectrumInputSourceElseSink, m_spectrumSink, m_threadedBasebandSampleSinks, SampleSinkFifo::readBegin(), SampleSinkFifo::readCommit(), and MessageQueue::size().
Referenced by handleData().
 {
     (void) nbWriteSamples;
     // Sources
     for (unsigned int isource = 0; isource < m_deviceSampleMIMO->getNbSourceStreams(); isource++)
     {
         SampleSinkFifo* sampleFifo = m_deviceSampleMIMO->getSampleSinkFifo(isource); // sink FIFO is for Rx
         int samplesDone = 0;
         bool positiveOnly = false;
         while ((sampleFifo->fill() > 0) && (m_inputMessageQueue.size() == 0) && (samplesDone < m_deviceSampleMIMO->getSourceSampleRate(isource)))
         {
             SampleVector::iterator part1begin;
             SampleVector::iterator part1end;
             SampleVector::iterator part2begin;
             SampleVector::iterator part2end;
             std::size_t count = sampleFifo->readBegin(sampleFifo->fill(), &part1begin, &part1end, &part2begin, &part2end);
             // first part of FIFO data
             if (part1begin != part1end)
             {
                 // TODO: DC and IQ corrections
                 // feed data to direct sinks
                 if (isource < m_basebandSampleSinks.size())
                 {
                     for (BasebandSampleSinks::const_iterator it = m_basebandSampleSinks[isource].begin(); it != m_basebandSampleSinks[isource].end(); ++it) {
                         (*it)->feed(part1begin, part1end, positiveOnly);
                     }
                 }
                 // possibly feed data to spectrum sink
                 if ((m_spectrumSink) && (m_spectrumInputSourceElseSink) && (isource == m_spectrumInputIndex)) {
                     m_spectrumSink->feed(part1begin, part1end, positiveOnly);
                 }
                 // feed data to threaded sinks
                 if (isource < m_threadedBasebandSampleSinks.size())
                 {
                     for (ThreadedBasebandSampleSinks::const_iterator it = m_threadedBasebandSampleSinks[isource].begin(); it != m_threadedBasebandSampleSinks[isource].end(); ++it) {
                         (*it)->feed(part1begin, part1end, positiveOnly);
                     }
                 }
             }
             // second part of FIFO data (used when block wraps around)
             if(part2begin != part2end)
             {
                 // TODO: DC and IQ corrections
                 // feed data to direct sinks
                 if (isource < m_basebandSampleSinks.size())
                 {
                     for (BasebandSampleSinks::const_iterator it = m_basebandSampleSinks[isource].begin(); it != m_basebandSampleSinks[isource].end(); ++it) {
                         (*it)->feed(part2begin, part2end, positiveOnly);
                     }
                 }
                 // possibly feed data to spectrum sink
                 if ((m_spectrumSink) && (m_spectrumInputSourceElseSink) && (isource == m_spectrumInputIndex)) {
                     m_spectrumSink->feed(part2begin, part2end, positiveOnly);
                 }
                 // feed data to threaded sinks
                 if (isource < m_threadedBasebandSampleSinks.size())
                 {
                     for (ThreadedBasebandSampleSinks::const_iterator it = m_threadedBasebandSampleSinks[isource].begin(); it != m_threadedBasebandSampleSinks[isource].end(); ++it) {
                         (*it)->feed(part2begin, part2end, positiveOnly);
                     }
                 }
             }
             // adjust FIFO pointers
             sampleFifo->readCommit((unsigned int) count);
             samplesDone += count;
         } // while stream FIFO
     } // for stream source
     // TODO: sinks
 }
workSampleSink
void DSPDeviceMIMOEngine::workSampleSink (unsigned int sinkIndex) private slot
Definition at line 337 of file dspdevicemimoengine.cpp.
References BasebandSampleSink::feed(), SampleSinkFifo::fill(), DeviceSampleMIMO::getSampleSinkFifo(), iqCorrections(), m_basebandSampleSinks, m_deviceSampleMIMO, m_inputMessageQueue, m_sourcesCorrections, m_spectrumInputIndex, m_spectrumInputSourceElseSink, m_spectrumSink, m_state, m_threadedBasebandSampleSinks, SampleSinkFifo::readBegin(), SampleSinkFifo::readCommit(), MessageQueue::size(), and StRunning.
Referenced by handleSetMIMO().
 {
     if (m_state != StRunning) {
         return;
     }
     SampleSinkFifo* sampleFifo = m_deviceSampleMIMO->getSampleSinkFifo(sinkIndex);
     int samplesDone = 0;
     bool positiveOnly = false;
     while ((sampleFifo->fill() > 0) && (m_inputMessageQueue.size() == 0) && (samplesDone < m_deviceSampleMIMO->getSourceSampleRate(sinkIndex)))
     {
         SampleVector::iterator part1begin;
         SampleVector::iterator part1end;
         SampleVector::iterator part2begin;
         SampleVector::iterator part2end;
         std::size_t count = sampleFifo->readBegin(sampleFifo->fill(), &part1begin, &part1end, &part2begin, &part2end);
         // first part of FIFO data
         if (part1begin != part1end)
         {
             // DC and IQ corrections
             if (m_sourcesCorrections[sinkIndex].m_dcOffsetCorrection) {
                 iqCorrections(part1begin, part1end, sinkIndex, m_sourcesCorrections[sinkIndex].m_iqImbalanceCorrection);
             }
             // feed data to direct sinks
             if (sinkIndex < m_basebandSampleSinks.size())
             {
                 for (BasebandSampleSinks::const_iterator it = m_basebandSampleSinks[sinkIndex].begin(); it != m_basebandSampleSinks[sinkIndex].end(); ++it) {
                     (*it)->feed(part1begin, part1end, positiveOnly);
                 }
             }
             // possibly feed data to spectrum sink
             if ((m_spectrumSink) && (m_spectrumInputSourceElseSink) && (sinkIndex == m_spectrumInputIndex)) {
                 m_spectrumSink->feed(part1begin, part1end, positiveOnly);
             }
             // feed data to threaded sinks
             for (ThreadedBasebandSampleSinks::const_iterator it = m_threadedBasebandSampleSinks[sinkIndex].begin(); it != m_threadedBasebandSampleSinks[sinkIndex].end(); ++it)
             {
                 (*it)->feed(part1begin, part1end, positiveOnly);
             }
         }
         // second part of FIFO data (used when block wraps around)
         if(part2begin != part2end)
         {
             // DC and IQ corrections
             if (m_sourcesCorrections[sinkIndex].m_dcOffsetCorrection) {
                 iqCorrections(part2begin, part2end, sinkIndex, m_sourcesCorrections[sinkIndex].m_iqImbalanceCorrection);
             }
             // feed data to direct sinks
             if (sinkIndex < m_basebandSampleSinks.size())
             {
                 for (BasebandSampleSinks::const_iterator it = m_basebandSampleSinks[sinkIndex].begin(); it != m_basebandSampleSinks[sinkIndex].end(); ++it) {
                     (*it)->feed(part2begin, part2end, positiveOnly);
                 }
             }
             // possibly feed data to spectrum sink
             if ((m_spectrumSink) && (m_spectrumInputSourceElseSink) && (sinkIndex == m_spectrumInputIndex)) {
                 m_spectrumSink->feed(part2begin, part2end, positiveOnly);
             }
             // feed data to threaded sinks
             for (ThreadedBasebandSampleSinks::const_iterator it = m_threadedBasebandSampleSinks[sinkIndex].begin(); it != m_threadedBasebandSampleSinks[sinkIndex].end(); ++it)
             {
                 (*it)->feed(part2begin, part2end, positiveOnly);
             }
         }
         // adjust FIFO pointers
         sampleFifo->readCommit((unsigned int) count);
         samplesDone += count;
     }
 }
Member Data Documentation
m_basebandSampleSinks
std::vector<BasebandSampleSinks> DSPDeviceMIMOEngine::m_basebandSampleSinks private
ancillary sample sinks on main thread (per input stream)
Definition at line 347 of file dspdevicemimoengine.h.
Referenced by gotoIdle(), gotoInit(), gotoRunning(), handleInputMessages(), handleSynchronousMessages(), work(), and workSampleSink().
m_deviceDescription
QString DSPDeviceMIMOEngine::m_deviceDescription private
Definition at line 338 of file dspdevicemimoengine.h.
Referenced by gotoError(), gotoIdle(), gotoInit(), gotoRunning(), and handleSynchronousMessages().
m_deviceSampleMIMO
DeviceSampleMIMO* DSPDeviceMIMOEngine::m_deviceSampleMIMO private
Definition at line 340 of file dspdevicemimoengine.h.
Referenced by gotoIdle(), gotoInit(), gotoRunning(), handleForwardToSpectrumSink(), handleInputMessages(), handleSetMIMO(), handleSynchronousMessages(), work(), and workSampleSink().
m_errorMessage
QString DSPDeviceMIMOEngine::m_errorMessage private
Definition at line 337 of file dspdevicemimoengine.h.
Referenced by gotoError(), and handleSynchronousMessages().
m_inputMessageQueue
MessageQueue DSPDeviceMIMOEngine::m_inputMessageQueue private
Definition at line 343 of file dspdevicemimoengine.h.
Referenced by configureCorrections(), gotoRunning(), handleInputMessages(), work(), and workSampleSink().
m_sampleMIMOSequence
int DSPDeviceMIMOEngine::m_sampleMIMOSequence private
Definition at line 341 of file dspdevicemimoengine.h.
Referenced by setMIMOSequence().
m_sampleSinkConnectionIndexes
std::vector<int> DSPDeviceMIMOEngine::m_sampleSinkConnectionIndexes private
Definition at line 351 of file dspdevicemimoengine.h.
Referenced by handleSetMIMO(), and handleSynchronousMessages().
m_sampleSourceConnectionIndexes
std::vector<int> DSPDeviceMIMOEngine::m_sampleSourceConnectionIndexes private
Definition at line 355 of file dspdevicemimoengine.h.
Referenced by handleSetMIMO(), and handleSynchronousMessages().
m_sourcesCorrections
std::vector<SourceCorrection> DSPDeviceMIMOEngine::m_sourcesCorrections private
Definition at line 357 of file dspdevicemimoengine.h.
Referenced by gotoInit(), handleInputMessages(), handleSynchronousMessages(), iqCorrections(), and workSampleSink().
m_spectrumInputIndex
unsigned int DSPDeviceMIMOEngine::m_spectrumInputIndex private
Index of the stream to be used as spectrum sink input.
Definition at line 361 of file dspdevicemimoengine.h.
Referenced by handleForwardToSpectrumSink(), handleInputMessages(), handleSynchronousMessages(), work(), and workSampleSink().
m_spectrumInputSourceElseSink
bool DSPDeviceMIMOEngine::m_spectrumInputSourceElseSink private
Source else sink stream to be used as spectrum sink input.
Definition at line 360 of file dspdevicemimoengine.h.
Referenced by handleInputMessages(), handleSynchronousMessages(), work(), and workSampleSink().
m_spectrumSink
BasebandSampleSink* DSPDeviceMIMOEngine::m_spectrumSink private
The spectrum sink.
Definition at line 359 of file dspdevicemimoengine.h.
Referenced by handleForwardToSpectrumSink(), handleInputMessages(), handleSynchronousMessages(), work(), and workSampleSink().
m_state
State DSPDeviceMIMOEngine::m_state private
Definition at line 335 of file dspdevicemimoengine.h.
Referenced by gotoError(), gotoIdle(), gotoInit(), gotoRunning(), handleData(), handleSynchronousMessages(), run(), stop(), and workSampleSink().
m_syncMessenger
SyncMessenger DSPDeviceMIMOEngine::m_syncMessenger private
Used to process messages synchronously with the thread.
Definition at line 344 of file dspdevicemimoengine.h.
Referenced by addAncillarySink(), addChannelSink(), addChannelSource(), addSinkStream(), addSourceStream(), addSpectrumSink(), deviceDescription(), errorMessage(), handleSynchronousMessages(), initProcess(), removeAncillarySink(), removeChannelSink(), removeChannelSource(), removeLastSinkStream(), removeLastSourceStream(), removeSpectrumSink(), setMIMO(), setSpectrumSinkInput(), startProcess(), and stopProcess().
m_threadedBasebandSampleSinks
std::vector<ThreadedBasebandSampleSinks> DSPDeviceMIMOEngine::m_threadedBasebandSampleSinks private
channel sample sinks on their own thread (per input stream)
Definition at line 350 of file dspdevicemimoengine.h.
Referenced by gotoIdle(), gotoInit(), gotoRunning(), handleInputMessages(), handleSynchronousMessages(), work(), and workSampleSink().
m_threadedBasebandSampleSources
std::vector<ThreadedBasebandSampleSources> DSPDeviceMIMOEngine::m_threadedBasebandSampleSources private
channel sample sources on their own threads (per output stream)
Definition at line 354 of file dspdevicemimoengine.h.
Referenced by handleInputMessages(), and handleSynchronousMessages().
m_uid
uint32_t DSPDeviceMIMOEngine::m_uid private
unique ID
Definition at line 334 of file dspdevicemimoengine.h.
The documentation for this class was generated from the following files:
sdrbase/dsp/dspdevicemimoengine.h
sdrbase/dsp/dspdevicemimoengine.cpp