SDRAngel: DeviceLimeSDRShared::MsgReportGPIOChange Class Reference
DeviceLimeSDRShared::MsgReportGPIOChange Class Reference
#include <devicelimesdrshared.h>
Public Member Functions
uint8_t getGPIODir () const
uint8_t getGPIOPins () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportGPIOChange * create (uint8_t gpioDir, uint8_t gpioPins)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportGPIOChange (uint8_t gpioDir, uint8_t gpioPins)
Private Attributes
uint8_t m_gpioDir
uint8_t m_gpioPins
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 125 of file devicelimesdrshared.h.
Constructor & Destructor Documentation
MsgReportGPIOChange()
DeviceLimeSDRShared::MsgReportGPIOChange::MsgReportGPIOChange (uint8_t gpioDir, uint8_t gpioPins) inline private
Definition at line 141 of file devicelimesdrshared.h.
                                                                :
             m_gpioDir(gpioDir),
             m_gpioPins(gpioPins)
         {}
Member Function Documentation
create()
static MsgReportGPIOChange* DeviceLimeSDRShared::MsgReportGPIOChange::create (uint8_t gpioDir, uint8_t gpioPins) inline static
Definition at line 132 of file devicelimesdrshared.h.
Referenced by LimeSDROutput::applySettings().
         {
             return new MsgReportGPIOChange(gpioDir, gpioPins);
         }
getGPIODir()
uint8_t DeviceLimeSDRShared::MsgReportGPIOChange::getGPIODir () const inline
Definition at line 129 of file devicelimesdrshared.h.
Referenced by LimeSDROutput::handleMessage(), and LimeSDRInput::handleMessage().
 { return m_gpioDir; }
getGPIOPins()
uint8_t DeviceLimeSDRShared::MsgReportGPIOChange::getGPIOPins () const inline
Definition at line 130 of file devicelimesdrshared.h.
Referenced by LimeSDROutput::handleMessage(), and LimeSDRInput::handleMessage().
 { return m_gpioPins; }
Member Data Documentation
m_gpioDir
uint8_t DeviceLimeSDRShared::MsgReportGPIOChange::m_gpioDir private
Definition at line 138 of file devicelimesdrshared.h.
m_gpioPins
uint8_t DeviceLimeSDRShared::MsgReportGPIOChange::m_gpioPins private
Definition at line 139 of file devicelimesdrshared.h.
The documentation for this class was generated from the following file:
devices/limesdr/devicelimesdrshared.h