SDRAngel: AirspyInput Class Reference
AirspyInput Class Reference
#include <airspyinput.h>
Classes
class MsgConfigureAirspy
class MsgFileRecord
class MsgStartStop
Public Member Functions
AirspyInput (DeviceAPI *deviceAPI)
virtual ~AirspyInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
const std::vector< uint32_t > & getSampleRates () const
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Static Public Attributes
static const qint64 loLowLimitFreq = 24000000L
static const qint64 loHighLimitFreq = 1900000000L
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
bool applySettings (const AirspySettings &settings, bool force)
struct airspy_device * open_airspy_from_sequence (int sequence)
void setDeviceCenterFrequency (quint64 freq)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const AirspySettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const AirspySettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
AirspySettings m_settings
struct airspy_device * m_dev
AirspyThread * m_airspyThread
QString m_deviceDescription
std::vector< uint32_t > m_sampleRates
bool m_running
FileRecord * m_fileSink
File sink to record device I/Q output.
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 35 of file airspyinput.h.
Constructor & Destructor Documentation
AirspyInput()
AirspyInput::AirspyInput (DeviceAPI * deviceAPI)
Definition at line 48 of file airspyinput.cpp.
References DeviceAPI::addAncillarySink(), arg(), DeviceAPI::getDeviceUID(), m_deviceAPI, m_fileSink, m_networkManager, networkManagerFinished(), openDevice(), and DeviceAPI::setNbSourceStreams().
Referenced by AirspyInput::MsgStartStop::MsgStartStop().
                                              :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_dev(0),
     m_airspyThread(0),
     m_deviceDescription("Airspy"),
     m_running(false)
 {
     openDevice();
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~AirspyInput()
AirspyInput::~AirspyInput () virtual
Definition at line 65 of file airspyinput.cpp.
References closeDevice(), m_deviceAPI, m_fileSink, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::removeAncillarySink(), and stop().
Referenced by AirspyInput::MsgStartStop::MsgStartStop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
     closeDevice();
 }
Member Function Documentation
applySettings()
bool AirspyInput::applySettings (const AirspySettings & settings, bool force) private
Definition at line 366 of file airspyinput.cpp.
References DeviceSampleSource::calculateDeviceCenterFrequency(), DeviceAPI::configureCorrections(), DeviceAPI::getDeviceEngineInputMessageQueue(), FileRecord::handleMessage(), m_airspyThread, AirspySettings::m_biasT, AirspySettings::m_centerFrequency, AirspySettings::m_dcBlock, m_dev, m_deviceAPI, AirspySettings::m_devSampleRateIndex, AirspySettings::m_fcPos, m_fileSink, AirspySettings::m_iqCorrection, AirspySettings::m_lnaAGC, AirspySettings::m_lnaGain, AirspySettings::m_log2Decim, AirspySettings::m_LOppmTenths, AirspySettings::m_mixerAGC, AirspySettings::m_mixerGain, m_mutex, AirspySettings::m_reverseAPIAddress, AirspySettings::m_reverseAPIDeviceIndex, AirspySettings::m_reverseAPIPort, m_sampleRates, m_settings, AirspySettings::m_transverterDeltaFrequency, AirspySettings::m_transverterMode, AirspySettings::m_useReverseAPI, AirspySettings::m_vgaGain, MessageQueue::push(), setDeviceCenterFrequency(), AirspyThread::setFcPos(), AirspyThread::setLog2Decimation(), AirspyThread::setSamplerate(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     QMutexLocker mutexLocker(&m_mutex);
     bool forwardChange = false;
     airspy_error rc = AIRSPY_ERROR_OTHER;
     QList<QString> reverseAPIKeys;
     qDebug() << "AirspyInput::applySettings";
     if ((m_settings.m_dcBlock != settings.m_dcBlock) || force) {
         reverseAPIKeys.append("dcBlock");
     }
     if ((m_settings.m_iqCorrection != settings.m_iqCorrection) || force) {
         reverseAPIKeys.append("iqCorrection");
     }
     if ((m_settings.m_dcBlock != settings.m_dcBlock) ||
         (m_settings.m_iqCorrection != settings.m_iqCorrection) || force)
     {
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqCorrection);
     }
     if ((m_settings.m_devSampleRateIndex != settings.m_devSampleRateIndex) || force)
     {
         reverseAPIKeys.append("devSampleRateIndex");
         forwardChange = true;
         if (m_dev != 0)
         {
             rc = (airspy_error) airspy_set_samplerate(m_dev, static_cast<airspy_samplerate_t>(settings.m_devSampleRateIndex));
             if (rc != AIRSPY_SUCCESS)
             {
                 qCritical("AirspyInput::applySettings: could not set sample rate index %u (%d S/s): %s", settings.m_devSampleRateIndex, m_sampleRates[settings.m_devSampleRateIndex], airspy_error_name(rc));
             }
             else if (m_airspyThread != 0)
             {
                 qDebug("AirspyInput::applySettings: sample rate set to index: %u (%d S/s)", settings.m_devSampleRateIndex, m_sampleRates[settings.m_devSampleRateIndex]);
                 m_airspyThread->setSamplerate(m_sampleRates[settings.m_devSampleRateIndex]);
             }
         }
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         reverseAPIKeys.append("log2Decim");
         forwardChange = true;
         if (m_airspyThread != 0)
         {
             m_airspyThread->setLog2Decimation(settings.m_log2Decim);
             qDebug() << "AirspyInput: set decimation to " << (1<<settings.m_log2Decim);
         }
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency) || force) {
         reverseAPIKeys.append("centerFrequency");
     }
     if ((m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force) {
         reverseAPIKeys.append("LOppmTenths");
     }
     if ((m_settings.m_fcPos != settings.m_fcPos) || force) {
         reverseAPIKeys.append("fcPos");
     }
     if ((m_settings.m_transverterMode != settings.m_transverterMode) || force) {
         reverseAPIKeys.append("transverterMode");
     }
     if ((m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency) || force) {
         reverseAPIKeys.append("transverterDeltaFrequency");
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency)
         || (m_settings.m_LOppmTenths != settings.m_LOppmTenths)
         || (m_settings.m_fcPos != settings.m_fcPos)
         || (m_settings.m_log2Decim != settings.m_log2Decim)
         || (m_settings.m_transverterMode != settings.m_transverterMode)
         || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency) || force)
     {
         qint64 deviceCenterFrequency = DeviceSampleSource::calculateDeviceCenterFrequency(
                 settings.m_centerFrequency,
                 settings.m_transverterDeltaFrequency,
                 settings.m_log2Decim,
                 (DeviceSampleSource::fcPos_t) settings.m_fcPos,
                 m_sampleRates[settings.m_devSampleRateIndex],
                 DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD,
                 settings.m_transverterMode);
         if (m_dev != 0) {
             setDeviceCenterFrequency(deviceCenterFrequency);
         }
         forwardChange = true;
     }
     if ((m_settings.m_fcPos != settings.m_fcPos) || force)
     {
         if (m_airspyThread != 0)
         {
             m_airspyThread->setFcPos((int) settings.m_fcPos);
             qDebug() << "AirspyInput: set fc pos (enum) to " << (int) settings.m_fcPos;
         }
     }
     if ((m_settings.m_lnaGain != settings.m_lnaGain) || force)
     {
         reverseAPIKeys.append("lnaGain");
         if (m_dev != 0)
         {
             rc = (airspy_error) airspy_set_lna_gain(m_dev, settings.m_lnaGain);
             if (rc != AIRSPY_SUCCESS) {
                 qDebug("AirspyInput::applySettings: airspy_set_lna_gain failed: %s", airspy_error_name(rc));
             } else {
                 qDebug() << "AirspyInput:applySettings: LNA gain set to " << settings.m_lnaGain;
             }
         }
     }
     if ((m_settings.m_lnaAGC != settings.m_lnaAGC) || force)
     {
         reverseAPIKeys.append("lnaAGC");
         if (m_dev != 0) {
             rc = (airspy_error) airspy_set_lna_agc(m_dev, (settings.m_lnaAGC ? 1 : 0));
         }
         if (rc != AIRSPY_SUCCESS) {
             qDebug("AirspyInput::applySettings: airspy_set_lna_agc failed: %s", airspy_error_name(rc));
         } else {
             qDebug() << "AirspyInput:applySettings: LNA AGC set to " << settings.m_lnaAGC;
         }
     }
     if ((m_settings.m_mixerGain != settings.m_mixerGain) || force)
     {
         reverseAPIKeys.append("mixerGain");
         if (m_dev != 0)
         {
             rc = (airspy_error) airspy_set_mixer_gain(m_dev, settings.m_mixerGain);
             if (rc != AIRSPY_SUCCESS) {
                 qDebug("AirspyInput::applySettings: airspy_set_mixer_gain failed: %s", airspy_error_name(rc));
             } else {
                 qDebug() << "AirspyInput:applySettings: mixer gain set to " << settings.m_mixerGain;
             }
         }
     }
     if ((m_settings.m_mixerAGC != settings.m_mixerAGC) || force)
     {
         reverseAPIKeys.append("mixerAGC");
         if (m_dev != 0) {
             rc = (airspy_error) airspy_set_mixer_agc(m_dev, (settings.m_mixerAGC ? 1 : 0));
         }
         if (rc != AIRSPY_SUCCESS) {
             qDebug("AirspyInput::applySettings: airspy_set_mixer_agc failed: %s", airspy_error_name(rc));
         } else {
             qDebug() << "AirspyInput:applySettings: Mixer AGC set to " << settings.m_mixerAGC;
         }
     }
     if ((m_settings.m_vgaGain != settings.m_vgaGain) || force)
     {
         reverseAPIKeys.append("vgaGain");
         if (m_dev != 0)
         {
             rc = (airspy_error) airspy_set_vga_gain(m_dev, settings.m_vgaGain);
             if (rc != AIRSPY_SUCCESS) {
                 qDebug("AirspyInput::applySettings: airspy_set_vga_gain failed: %s", airspy_error_name(rc));
             } else {
                 qDebug() << "AirspyInput:applySettings: VGA gain set to " << settings.m_vgaGain;
             }
         }
     }
     if ((m_settings.m_biasT != settings.m_biasT) || force)
     {
         reverseAPIKeys.append("biasT");
         if (m_dev != 0)
         {
             rc = (airspy_error) airspy_set_rf_bias(m_dev, (settings.m_biasT ? 1 : 0));
             if (rc != AIRSPY_SUCCESS) {
                 qDebug("AirspyInput::applySettings: airspy_set_rf_bias failed: %s", airspy_error_name(rc));
             } else {
                 qDebug() << "AirspyInput:applySettings: bias tee set to " << settings.m_biasT;
             }
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     if (forwardChange)
     {
         int sampleRate = m_sampleRates[m_settings.m_devSampleRateIndex]/(1<<m_settings.m_log2Decim);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, m_settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     return true;
 }
closeDevice()
void AirspyInput::closeDevice () private
Definition at line 196 of file airspyinput.cpp.
References m_dev, and m_deviceDescription.
Referenced by openDevice(), and ~AirspyInput().
 {
     if (m_dev != 0)
     {
         airspy_stop_rx(m_dev);
         airspy_close(m_dev);
         m_dev = 0;
     }
     m_deviceDescription.clear();
     airspy_exit();
 }
deserialize()
bool AirspyInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 229 of file airspyinput.cpp.
References AirspyInput::MsgConfigureAirspy::create(), AirspySettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and AirspySettings::resetToDefaults().
Referenced by AirspyInput::MsgStartStop::MsgStartStop().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureAirspy* message = MsgConfigureAirspy::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureAirspy* messageToGUI = MsgConfigureAirspy::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void AirspyInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 79 of file airspyinput.cpp.
Referenced by AirspyInput::MsgStartStop::MsgStartStop().
 {
     delete this;
 }
getCenterFrequency()
quint64 AirspyInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 262 of file airspyinput.cpp.
References AirspySettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & AirspyInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 251 of file airspyinput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getSampleRate()
int AirspyInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 256 of file airspyinput.cpp.
References AirspySettings::m_devSampleRateIndex, AirspySettings::m_log2Decim, m_sampleRates, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     int rate = m_sampleRates[m_settings.m_devSampleRateIndex];
     return (rate / (1<<m_settings.m_log2Decim));
 }
getSampleRates()
const std::vector<uint32_t>& AirspyInput::getSampleRates () const inline
Definition at line 116 of file airspyinput.h.
References handleMessage(), m_sampleRates, webapiReportGet(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
Referenced by webapiFormatDeviceReport().
 { return m_sampleRates; }
handleMessage()
bool AirspyInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 282 of file airspyinput.cpp.
References applySettings(), FileRecord::genUniqueFileName(), DeviceAPI::getDeviceUID(), AirspyInput::MsgConfigureAirspy::getForce(), AirspyInput::MsgConfigureAirspy::getSettings(), AirspyInput::MsgFileRecord::getStartStop(), AirspyInput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), m_deviceAPI, AirspySettings::m_fileRecordName, m_fileSink, m_settings, AirspySettings::m_useReverseAPI, Message::match(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
Referenced by getSampleRates().
 {
     if (MsgConfigureAirspy::match(message))
     {
         MsgConfigureAirspy& conf = (MsgConfigureAirspy&) message;
         qDebug() << "AirspyInput::handleMessage: MsgConfigureAirspy";
         bool success = applySettings(conf.getSettings(), conf.getForce());
         if (!success)
         {
             qDebug("AirspyInput::handleMessage: Airspy config error");
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "AirspyInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "AirspyInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void AirspyInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 164 of file airspyinput.cpp.
References applySettings(), and m_settings.
Referenced by AirspyInput::MsgStartStop::MsgStartStop().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void AirspyInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 900 of file airspyinput.cpp.
Referenced by AirspyInput(), and ~AirspyInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "AirspyInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("AirspyInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
open_airspy_from_sequence()
struct airspy_device * AirspyInput::open_airspy_from_sequence (int sequence) private
Definition at line 586 of file airspyinput.cpp.
References i, and AirspyPlugin::m_maxDevices.
Referenced by openDevice().
 {
     struct airspy_device *devinfo;
     airspy_error rc = AIRSPY_ERROR_OTHER;
     for (int i = 0; i < AirspyPlugin::m_maxDevices; i++)
     {
         rc = (airspy_error) airspy_open(&devinfo);
         if (rc == AIRSPY_SUCCESS)
         {
             if (i == sequence) {
                 return devinfo;
             } else {
                 airspy_close(devinfo);
             }
         }
         else
         {
             break;
         }
     }
     return 0;
 }
openDevice()
bool AirspyInput::openDevice () private
Definition at line 84 of file airspyinput.cpp.
References closeDevice(), DeviceAPI::getSamplingDeviceSequence(), i, m_dev, m_deviceAPI, DeviceSampleSource::m_sampleFifo, m_sampleRates, open_airspy_from_sequence(), and SampleSinkFifo::setSize().
Referenced by AirspyInput().
 {
     if (m_dev != 0)
     {
         closeDevice();
     }
     airspy_error rc;
     rc = (airspy_error) airspy_init();
     if (rc != AIRSPY_SUCCESS)
     {
         qCritical("AirspyInput::start: failed to initiate Airspy library %s", airspy_error_name(rc));
     }
     if (!m_sampleFifo.setSize(1<<19))
     {
         qCritical("AirspyInput::start: could not allocate SampleFifo");
         return false;
     }
     int device = m_deviceAPI->getSamplingDeviceSequence();
     if ((m_dev = open_airspy_from_sequence(device)) == 0)
     {
         qCritical("AirspyInput::start: could not open Airspy #%d", device);
         return false;
     }
 #ifdef LIBAIRSPY_DEFAULT_RATES
     qDebug("AirspyInput::start: detault rates");
     m_sampleRates.clear();
     m_sampleRates.push_back(10000000);
     m_sampleRates.push_back(2500000);
 #else
     uint32_t nbSampleRates;
     uint32_t *sampleRates;
     airspy_get_samplerates(m_dev, &nbSampleRates, 0);
     sampleRates = new uint32_t[nbSampleRates];
     airspy_get_samplerates(m_dev, sampleRates, nbSampleRates);
     if (nbSampleRates == 0)
     {
         qCritical("AirspyInput::start: could not obtain Airspy sample rates");
         return false;
     }
     else
     {
         qDebug("AirspyInput::start: %d sample rates", nbSampleRates);
     }
     m_sampleRates.clear();
     for (unsigned int i=0; i<nbSampleRates; i++)
     {
         m_sampleRates.push_back(sampleRates[i]);
         qDebug("AirspyInput::start: sampleRates[%d] = %u Hz", i, sampleRates[i]);
     }
     delete[] sampleRates;
 #endif
 //    MsgReportAirspy *message = MsgReportAirspy::create(m_sampleRates);
 //    getOutputMessageQueueToGUI()->push(message);
     rc = (airspy_error) airspy_set_sample_type(m_dev, AIRSPY_SAMPLE_INT16_IQ);
     if (rc != AIRSPY_SUCCESS)
     {
         qCritical("AirspyInput::start: could not set sample type to INT16_IQ");
         return false;
     }
     return true;
 }
serialize()
QByteArray AirspyInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 224 of file airspyinput.cpp.
References m_settings, and AirspySettings::serialize().
Referenced by AirspyInput::MsgStartStop::MsgStartStop().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void AirspyInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 267 of file airspyinput.cpp.
References AirspyInput::MsgConfigureAirspy::create(), AirspySettings::m_centerFrequency, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     AirspySettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureAirspy* message = MsgConfigureAirspy::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureAirspy* messageToGUI = MsgConfigureAirspy::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setDeviceCenterFrequency()
void AirspyInput::setDeviceCenterFrequency (quint64 freq) private
Definition at line 349 of file airspyinput.cpp.
References m_dev, AirspySettings::m_LOppmTenths, and m_settings.
Referenced by applySettings().
 {
     qint64 df = ((qint64)freq_hz * m_settings.m_LOppmTenths) / 10000000LL;
     freq_hz += df;
     airspy_error rc = (airspy_error) airspy_set_freq(m_dev, static_cast<uint32_t>(freq_hz));
     if (rc != AIRSPY_SUCCESS)
     {
         qWarning("AirspyInput::setDeviceCenterFrequency: could not frequency to %llu Hz", freq_hz);
     }
     else
     {
         qDebug("AirspyInput::setDeviceCenterFrequency: frequency set to %llu Hz", freq_hz);
     }
 }
setMessageQueueToGUI()
virtual void AirspyInput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 110 of file airspyinput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSource::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void AirspyInput::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 113 of file airspyinput.h.
References getCenterFrequency(), and setCenterFrequency().
 { (void) sampleRate; }
start()
bool AirspyInput::start () virtual
Implements DeviceSampleSource.
Definition at line 169 of file airspyinput.cpp.
References applySettings(), m_airspyThread, m_dev, AirspySettings::m_devSampleRateIndex, AirspySettings::m_fcPos, AirspySettings::m_log2Decim, m_mutex, m_running, DeviceSampleSource::m_sampleFifo, m_sampleRates, m_settings, AirspyThread::setFcPos(), AirspyThread::setLog2Decimation(), AirspyThread::setSamplerate(), AirspyThread::startWork(), and stop().
Referenced by AirspyInput::MsgStartStop::MsgStartStop().
 {
     QMutexLocker mutexLocker(&m_mutex);
     if (!m_dev) {
         return false;
     }
     if (m_running) { stop(); }
     m_airspyThread = new AirspyThread(m_dev, &m_sampleFifo);
     m_airspyThread->setSamplerate(m_sampleRates[m_settings.m_devSampleRateIndex]);
     m_airspyThread->setLog2Decimation(m_settings.m_log2Decim);
     m_airspyThread->setFcPos((int) m_settings.m_fcPos);
     m_airspyThread->startWork();
     mutexLocker.unlock();
     applySettings(m_settings, true);
     qDebug("AirspyInput::startInput: started");
     m_running = true;
     return true;
 }
stop()
void AirspyInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 209 of file airspyinput.cpp.
References m_airspyThread, m_mutex, m_running, and AirspyThread::stopWork().
Referenced by AirspyInput::MsgStartStop::MsgStartStop(), start(), and ~AirspyInput().
 {
     qDebug("AirspyInput::stop");
     QMutexLocker mutexLocker(&m_mutex);
     if (m_airspyThread != 0)
     {
         m_airspyThread->stopWork();
         delete m_airspyThread;
         m_airspyThread = 0;
     }
     m_running = false;
 }
webapiFormatDeviceReport()
void AirspyInput::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 783 of file airspyinput.cpp.
References SWGSDRangel::SWGDeviceReport::getAirspyReport(), SWGSDRangel::SWGAirspyReport::getSampleRates(), getSampleRates(), and SWGSDRangel::SWGAirspyReport::setSampleRates().
Referenced by webapiReportGet().
 {
     response.getAirspyReport()->setSampleRates(new QList<SWGSDRangel::SWGSampleRate*>);
     for (std::vector<uint32_t>::const_iterator it = getSampleRates().begin(); it != getSampleRates().end(); ++it)
     {
         response.getAirspyReport()->getSampleRates()->append(new SWGSDRangel::SWGSampleRate);
         response.getAirspyReport()->getSampleRates()->back()->setRate(*it);
     }
 }
webapiFormatDeviceSettings()
void AirspyInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const AirspySettings & settings) private
Definition at line 747 of file airspyinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getAirspySettings(), SWGSDRangel::SWGAirspySettings::getFileRecordName(), SWGSDRangel::SWGAirspySettings::getReverseApiAddress(), AirspySettings::m_biasT, AirspySettings::m_centerFrequency, AirspySettings::m_dcBlock, AirspySettings::m_devSampleRateIndex, AirspySettings::m_fcPos, AirspySettings::m_fileRecordName, AirspySettings::m_iqCorrection, AirspySettings::m_lnaAGC, AirspySettings::m_lnaGain, AirspySettings::m_log2Decim, AirspySettings::m_LOppmTenths, AirspySettings::m_mixerAGC, AirspySettings::m_mixerGain, AirspySettings::m_reverseAPIAddress, AirspySettings::m_reverseAPIDeviceIndex, AirspySettings::m_reverseAPIPort, AirspySettings::m_transverterDeltaFrequency, AirspySettings::m_transverterMode, AirspySettings::m_useReverseAPI, AirspySettings::m_vgaGain, SWGSDRangel::SWGAirspySettings::setBiasT(), SWGSDRangel::SWGAirspySettings::setCenterFrequency(), SWGSDRangel::SWGAirspySettings::setDcBlock(), SWGSDRangel::SWGAirspySettings::setDevSampleRateIndex(), SWGSDRangel::SWGAirspySettings::setFcPos(), SWGSDRangel::SWGAirspySettings::setFileRecordName(), SWGSDRangel::SWGAirspySettings::setIqCorrection(), SWGSDRangel::SWGAirspySettings::setLnaAgc(), SWGSDRangel::SWGAirspySettings::setLnaGain(), SWGSDRangel::SWGAirspySettings::setLog2Decim(), SWGSDRangel::SWGAirspySettings::setLOppmTenths(), SWGSDRangel::SWGAirspySettings::setMixerAgc(), SWGSDRangel::SWGAirspySettings::setMixerGain(), SWGSDRangel::SWGAirspySettings::setReverseApiAddress(), SWGSDRangel::SWGAirspySettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGAirspySettings::setReverseApiPort(), SWGSDRangel::SWGAirspySettings::setTransverterDeltaFrequency(), SWGSDRangel::SWGAirspySettings::setTransverterMode(), SWGSDRangel::SWGAirspySettings::setUseReverseApi(), and SWGSDRangel::SWGAirspySettings::setVgaGain().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getAirspySettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getAirspySettings()->setLOppmTenths(settings.m_LOppmTenths);
     response.getAirspySettings()->setDevSampleRateIndex(settings.m_devSampleRateIndex);
     response.getAirspySettings()->setLnaGain(settings.m_lnaGain);
     response.getAirspySettings()->setMixerGain(settings.m_mixerGain);
     response.getAirspySettings()->setVgaGain(settings.m_vgaGain);
     response.getAirspySettings()->setLnaAgc(settings.m_lnaAGC ? 1 : 0);
     response.getAirspySettings()->setMixerAgc(settings.m_mixerAGC ? 1 : 0);
     response.getAirspySettings()->setLog2Decim(settings.m_log2Decim);
     response.getAirspySettings()->setFcPos((int) settings.m_fcPos);
     response.getAirspySettings()->setBiasT(settings.m_biasT ? 1 : 0);
     response.getAirspySettings()->setDcBlock(settings.m_dcBlock ? 1 : 0);
     response.getAirspySettings()->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     response.getAirspySettings()->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     response.getAirspySettings()->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     if (response.getAirspySettings()->getFileRecordName()) {
         *response.getAirspySettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getAirspySettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getAirspySettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getAirspySettings()->getReverseApiAddress()) {
         *response.getAirspySettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getAirspySettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getAirspySettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getAirspySettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int AirspyInput::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 736 of file airspyinput.cpp.
References SWGSDRangel::SWGDeviceReport::getAirspyReport(), SWGSDRangel::SWGAirspyReport::init(), SWGSDRangel::SWGDeviceReport::setAirspyReport(), and webapiFormatDeviceReport().
Referenced by getSampleRates().
 {
     (void) errorMessage;
     response.setAirspyReport(new SWGSDRangel::SWGAirspyReport());
     response.getAirspyReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void AirspyInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const AirspySettings & settings, bool force) private
Definition at line 794 of file airspyinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), SWGSDRangel::SWGDeviceSettings::getAirspySettings(), DeviceAPI::getDeviceSetIndex(), AirspySettings::m_biasT, AirspySettings::m_centerFrequency, AirspySettings::m_dcBlock, m_deviceAPI, AirspySettings::m_devSampleRateIndex, AirspySettings::m_fcPos, AirspySettings::m_fileRecordName, AirspySettings::m_iqCorrection, AirspySettings::m_lnaAGC, AirspySettings::m_lnaGain, AirspySettings::m_log2Decim, AirspySettings::m_LOppmTenths, AirspySettings::m_mixerAGC, AirspySettings::m_mixerGain, m_networkManager, m_networkRequest, AirspySettings::m_reverseAPIAddress, AirspySettings::m_reverseAPIDeviceIndex, AirspySettings::m_reverseAPIPort, AirspySettings::m_transverterDeltaFrequency, AirspySettings::m_transverterMode, AirspySettings::m_vgaGain, SWGSDRangel::SWGDeviceSettings::setAirspySettings(), SWGSDRangel::SWGAirspySettings::setBiasT(), SWGSDRangel::SWGAirspySettings::setCenterFrequency(), SWGSDRangel::SWGAirspySettings::setDcBlock(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGAirspySettings::setDevSampleRateIndex(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGAirspySettings::setFcPos(), SWGSDRangel::SWGAirspySettings::setFileRecordName(), SWGSDRangel::SWGAirspySettings::setIqCorrection(), SWGSDRangel::SWGAirspySettings::setLnaAgc(), SWGSDRangel::SWGAirspySettings::setLnaGain(), SWGSDRangel::SWGAirspySettings::setLog2Decim(), SWGSDRangel::SWGAirspySettings::setLOppmTenths(), SWGSDRangel::SWGAirspySettings::setMixerAgc(), SWGSDRangel::SWGAirspySettings::setMixerGain(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGAirspySettings::setTransverterDeltaFrequency(), SWGSDRangel::SWGAirspySettings::setTransverterMode(), and SWGSDRangel::SWGAirspySettings::setVgaGain().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("Airspy"));
     swgDeviceSettings->setAirspySettings(new SWGSDRangel::SWGAirspySettings());
     SWGSDRangel::SWGAirspySettings *swgAirspySettings = swgDeviceSettings->getAirspySettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgAirspySettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("LOppmTenths") || force) {
         swgAirspySettings->setLOppmTenths(settings.m_LOppmTenths);
     }
     if (deviceSettingsKeys.contains("devSampleRateIndex") || force) {
         swgAirspySettings->setDevSampleRateIndex(settings.m_devSampleRateIndex);
     }
     if (deviceSettingsKeys.contains("lnaGain") || force) {
         swgAirspySettings->setLnaGain(settings.m_lnaGain);
     }
     if (deviceSettingsKeys.contains("mixerGain") || force) {
         swgAirspySettings->setMixerGain(settings.m_mixerGain);
     }
     if (deviceSettingsKeys.contains("vgaGain") || force) {
         swgAirspySettings->setVgaGain(settings.m_vgaGain);
     }
     if (deviceSettingsKeys.contains("lnaAGC") || force) {
         swgAirspySettings->setLnaAgc(settings.m_lnaAGC ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("mixerAGC") || force) {
         swgAirspySettings->setMixerAgc(settings.m_mixerAGC ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("log2Decim") || force) {
         swgAirspySettings->setLog2Decim(settings.m_log2Decim);
     }
     if (deviceSettingsKeys.contains("fcPos") || force) {
         swgAirspySettings->setFcPos((int) settings.m_fcPos);
     }
     if (deviceSettingsKeys.contains("biasT") || force) {
         swgAirspySettings->setBiasT(settings.m_biasT ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("dcBlock") || force) {
         swgAirspySettings->setDcBlock(settings.m_dcBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("iqCorrection") || force) {
         swgAirspySettings->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency") || force) {
         swgAirspySettings->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     }
     if (deviceSettingsKeys.contains("transverterMode") || force) {
         swgAirspySettings->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgAirspySettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void AirspyInput::webapiReverseSendStartStop (bool start) private
Definition at line 872 of file airspyinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, AirspySettings::m_reverseAPIAddress, AirspySettings::m_reverseAPIDeviceIndex, AirspySettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("Airspy"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int AirspyInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 621 of file airspyinput.cpp.
References AirspyInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by getSampleRates().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int AirspyInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 612 of file airspyinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by getSampleRates().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int AirspyInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 640 of file airspyinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getAirspySettings(), SWGSDRangel::SWGAirspySettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setAirspySettings(), and webapiFormatDeviceSettings().
Referenced by getSampleRates().
 {
     (void) errorMessage;
     response.setAirspySettings(new SWGSDRangel::SWGAirspySettings());
     response.getAirspySettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int AirspyInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 651 of file airspyinput.cpp.
References AirspyInput::MsgConfigureAirspy::create(), SWGSDRangel::SWGDeviceSettings::getAirspySettings(), SWGSDRangel::SWGAirspySettings::getBiasT(), SWGSDRangel::SWGAirspySettings::getCenterFrequency(), SWGSDRangel::SWGAirspySettings::getDcBlock(), SWGSDRangel::SWGAirspySettings::getDevSampleRateIndex(), SWGSDRangel::SWGAirspySettings::getFcPos(), SWGSDRangel::SWGAirspySettings::getFileRecordName(), SWGSDRangel::SWGAirspySettings::getIqCorrection(), SWGSDRangel::SWGAirspySettings::getLnaAgc(), SWGSDRangel::SWGAirspySettings::getLnaGain(), SWGSDRangel::SWGAirspySettings::getLog2Decim(), SWGSDRangel::SWGAirspySettings::getLOppmTenths(), SWGSDRangel::SWGAirspySettings::getMixerAgc(), SWGSDRangel::SWGAirspySettings::getMixerGain(), SWGSDRangel::SWGAirspySettings::getReverseApiAddress(), SWGSDRangel::SWGAirspySettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGAirspySettings::getReverseApiPort(), SWGSDRangel::SWGAirspySettings::getTransverterDeltaFrequency(), SWGSDRangel::SWGAirspySettings::getTransverterMode(), SWGSDRangel::SWGAirspySettings::getUseReverseApi(), SWGSDRangel::SWGAirspySettings::getVgaGain(), AirspySettings::m_biasT, AirspySettings::m_centerFrequency, AirspySettings::m_dcBlock, AirspySettings::m_devSampleRateIndex, AirspySettings::m_fcPos, AirspySettings::m_fileRecordName, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, AirspySettings::m_iqCorrection, AirspySettings::m_lnaAGC, AirspySettings::m_lnaGain, AirspySettings::m_log2Decim, AirspySettings::m_LOppmTenths, AirspySettings::m_mixerAGC, AirspySettings::m_mixerGain, AirspySettings::m_reverseAPIAddress, AirspySettings::m_reverseAPIDeviceIndex, AirspySettings::m_reverseAPIPort, m_settings, AirspySettings::m_transverterDeltaFrequency, AirspySettings::m_transverterMode, AirspySettings::m_useReverseAPI, AirspySettings::m_vgaGain, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by getSampleRates().
 {
     (void) errorMessage;
     AirspySettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getAirspySettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("LOppmTenths")) {
         settings.m_LOppmTenths = response.getAirspySettings()->getLOppmTenths();
     }
     if (deviceSettingsKeys.contains("devSampleRateIndex")) {
         settings.m_devSampleRateIndex = response.getAirspySettings()->getDevSampleRateIndex();
     }
     if (deviceSettingsKeys.contains("lnaGain")) {
         settings.m_lnaGain = response.getAirspySettings()->getLnaGain();
     }
     if (deviceSettingsKeys.contains("mixerGain")) {
         settings.m_mixerGain = response.getAirspySettings()->getMixerGain();
     }
     if (deviceSettingsKeys.contains("vgaGain")) {
         settings.m_vgaGain = response.getAirspySettings()->getVgaGain();
     }
     if (deviceSettingsKeys.contains("lnaAGC")) {
         settings.m_lnaAGC = response.getAirspySettings()->getLnaAgc() != 0;
     }
     if (deviceSettingsKeys.contains("mixerAGC")) {
         settings.m_mixerAGC = response.getAirspySettings()->getMixerAgc() != 0;
     }
     if (deviceSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getAirspySettings()->getLog2Decim();
     }
     if (deviceSettingsKeys.contains("fcPos")) {
         int fcPos = response.getAirspySettings()->getFcPos();
         fcPos = fcPos < 0 ? 0 : fcPos > 2 ? 2 : fcPos;
         settings.m_fcPos = (AirspySettings::fcPos_t) fcPos;
     }
     if (deviceSettingsKeys.contains("biasT")) {
         settings.m_biasT = response.getAirspySettings()->getBiasT() != 0;
     }
     if (deviceSettingsKeys.contains("dcBlock")) {
         settings.m_dcBlock = response.getAirspySettings()->getDcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("iqCorrection")) {
         settings.m_iqCorrection = response.getAirspySettings()->getIqCorrection() != 0;
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency")) {
         settings.m_transverterDeltaFrequency = response.getAirspySettings()->getTransverterDeltaFrequency();
     }
     if (deviceSettingsKeys.contains("transverterMode")) {
         settings.m_transverterMode = response.getAirspySettings()->getTransverterMode() != 0;
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getAirspySettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getAirspySettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getAirspySettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getAirspySettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getAirspySettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureAirspy *msg = MsgConfigureAirspy::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureAirspy *msgToGUI = MsgConfigureAirspy::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
loHighLimitFreq
const qint64 AirspyInput::loHighLimitFreq = 1900000000L static
Definition at line 144 of file airspyinput.h.
Referenced by AirspyGui::updateFrequencyLimits().
loLowLimitFreq
const qint64 AirspyInput::loLowLimitFreq = 24000000L static
Definition at line 143 of file airspyinput.h.
Referenced by AirspyGui::updateFrequencyLimits().
m_airspyThread
AirspyThread* AirspyInput::m_airspyThread private
Definition at line 151 of file airspyinput.h.
Referenced by applySettings(), start(), and stop().
m_dev
struct airspy_device* AirspyInput::m_dev private
Definition at line 150 of file airspyinput.h.
Referenced by applySettings(), closeDevice(), openDevice(), setDeviceCenterFrequency(), and start().
m_deviceAPI
DeviceAPI* AirspyInput::m_deviceAPI private
Definition at line 147 of file airspyinput.h.
Referenced by AirspyInput(), applySettings(), handleMessage(), openDevice(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~AirspyInput().
m_deviceDescription
QString AirspyInput::m_deviceDescription private
Definition at line 152 of file airspyinput.h.
Referenced by closeDevice(), and getDeviceDescription().
m_fileSink
FileRecord* AirspyInput::m_fileSink private
File sink to record device I/Q output.
Definition at line 155 of file airspyinput.h.
Referenced by AirspyInput(), applySettings(), handleMessage(), and ~AirspyInput().
m_mutex
QMutex AirspyInput::m_mutex private
Definition at line 148 of file airspyinput.h.
Referenced by applySettings(), start(), and stop().
m_networkManager
QNetworkAccessManager* AirspyInput::m_networkManager private
Definition at line 156 of file airspyinput.h.
Referenced by AirspyInput(), webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~AirspyInput().
m_networkRequest
QNetworkRequest AirspyInput::m_networkRequest private
Definition at line 157 of file airspyinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool AirspyInput::m_running private
Definition at line 154 of file airspyinput.h.
Referenced by start(), stop(), and ~AirspyInput().
m_sampleRates
std::vector<uint32_t> AirspyInput::m_sampleRates private
Definition at line 153 of file airspyinput.h.
Referenced by applySettings(), getSampleRate(), getSampleRates(), openDevice(), and start().
m_settings
AirspySettings AirspyInput::m_settings private
Definition at line 149 of file airspyinput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), serialize(), setCenterFrequency(), setDeviceCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
The documentation for this class was generated from the following files:
plugins/samplesource/airspy/airspyinput.h
plugins/samplesource/airspy/airspyinput.cpp