SDRAngel: AMDemodPlugin Class Reference
AMDemodPlugin Class Reference
#include <amdemodplugin.h>
Public Member Functions
AMDemodPlugin (QObject *parent=NULL)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
Private Attributes
PluginAPI * m_pluginAPI
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Private Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Private Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Detailed Description
Definition at line 27 of file amdemodplugin.h.
Constructor & Destructor Documentation
AMDemodPlugin()
AMDemodPlugin::AMDemodPlugin (QObject * parent = NULL) explicit
Definition at line 19 of file amdemodplugin.cpp.
                                             :
     QObject(parent),
     m_pluginAPI(0)
 {
 }
Member Function Documentation
createRxChannelBS()
BasebandSampleSink * AMDemodPlugin::createRxChannelBS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 52 of file amdemodplugin.cpp.
 {
     return new AMDemod(deviceAPI);
 }
createRxChannelCS()
ChannelAPI * AMDemodPlugin::createRxChannelCS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 57 of file amdemodplugin.cpp.
 {
     return new AMDemod(deviceAPI);
 }
createRxChannelGUI()
PluginInstanceGUI * AMDemodPlugin::createRxChannelGUI (DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) virtual
Reimplemented from PluginInterface.
Definition at line 46 of file amdemodplugin.cpp.
References AMDemodGUI::create(), and m_pluginAPI.
Referenced by initPlugin().
 {
     return AMDemodGUI::create(m_pluginAPI, deviceUISet, rxChannel);
 }
getPluginDescriptor()
const PluginDescriptor & AMDemodPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 25 of file amdemodplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void AMDemodPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 30 of file amdemodplugin.cpp.
References createRxChannelGUI(), AMDemod::m_channelId, AMDemod::m_channelIdURI, m_pluginAPI, and PluginAPI::registerRxChannel().
 {
     m_pluginAPI = pluginAPI;
     // register AM demodulator
     m_pluginAPI->registerRxChannel(AMDemod::m_channelIdURI, AMDemod::m_channelId, this);
 }
Member Data Documentation
m_pluginAPI
PluginAPI* AMDemodPlugin::m_pluginAPI private
Definition at line 45 of file amdemodplugin.h.
Referenced by createRxChannelGUI(), and initPlugin().
m_pluginDescriptor
const PluginDescriptor AMDemodPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("AM Demodulator"),
    QString("4.5.2"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 43 of file amdemodplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/channelrx/demodam/amdemodplugin.h
plugins/channelrx/demodam/amdemodplugin.cpp