SDRAngel: DevicePerseus Class Reference
DevicePerseus Class Reference
#include <deviceperseus.h>
Public Member Functions
void scan ()
void getSerials (std::vector< std::string > &serials) const
int getSequenceFromSerial (const std::string &serial) const
Static Public Member Functions
static DevicePerseus & instance ()
Protected Member Functions
DevicePerseus ()
DevicePerseus (const DevicePerseus &)
DevicePerseus & operator= (const DevicePerseus &other)
~DevicePerseus ()
Private Member Functions
bool internal_scan ()
Private Attributes
int m_nbDevices
DevicePerseusScan m_scan
Detailed Description
Definition at line 25 of file deviceperseus.h.
Constructor & Destructor Documentation
DevicePerseus() [1/2]
DevicePerseus::DevicePerseus () protected
Definition at line 21 of file deviceperseus.cpp.
References m_nbDevices.
 {
     m_nbDevices = perseus_init();
 }
DevicePerseus() [2/2]
DevicePerseus::DevicePerseus (const DevicePerseus &) inline protected
Definition at line 35 of file deviceperseus.h.
 : m_nbDevices(0) {}
~DevicePerseus()
DevicePerseus::~DevicePerseus () protected
Definition at line 26 of file deviceperseus.cpp.
 {
     perseus_exit();
 }
Member Function Documentation
getSequenceFromSerial()
int DevicePerseus::getSequenceFromSerial (const std::string & serial) const inline
Definition at line 31 of file deviceperseus.h.
Referenced by PerseusInput::openDevice().
 { return m_scan.getSequenceFromSerial(serial); }
getSerials()
void DevicePerseus::getSerials (std::vector< std::string > & serials) const inline
Definition at line 30 of file deviceperseus.h.
Referenced by PerseusPlugin::enumSampleSources().
 { m_scan.getSerials(serials); }
instance()
DevicePerseus & DevicePerseus::instance () static
Definition at line 31 of file deviceperseus.cpp.
Referenced by PerseusPlugin::enumSampleSources(), and PerseusInput::openDevice().
 {
     static DevicePerseus inst;
     return inst;
 }
internal_scan()
bool DevicePerseus::internal_scan () private
Definition at line 51 of file deviceperseus.cpp.
References m_nbDevices, m_scan, and DevicePerseusScan::scan().
Referenced by scan().
 {
     return m_scan.scan(m_nbDevices);
 }
operator=()
DevicePerseus& DevicePerseus::operator= (const DevicePerseus & other) inline protected
Definition at line 36 of file deviceperseus.h.
 { (void) other; return *this; }
scan()
void DevicePerseus::scan ()
Definition at line 37 of file deviceperseus.cpp.
References DevicePerseusScan::clear(), internal_scan(), m_nbDevices, and m_scan.
Referenced by PerseusPlugin::enumSampleSources().
 {
     // If some firmware was not downloaded at time of enumeration interface will break later
     // so in this case we re initialize the library, clear the scan results and scan again
     if (!internal_scan())
     {
         qDebug("DevicePerseus::scan: re-init library and scan again");
         m_scan.clear();
         perseus_exit();
         m_nbDevices = perseus_init();
         internal_scan();
     }
 }
Member Data Documentation
m_nbDevices
int DevicePerseus::m_nbDevices private
Definition at line 41 of file deviceperseus.h.
Referenced by DevicePerseus(), internal_scan(), and scan().
m_scan
DevicePerseusScan DevicePerseus::m_scan private
Definition at line 42 of file deviceperseus.h.
Referenced by internal_scan(), and scan().
The documentation for this class was generated from the following files:
devices/perseus/deviceperseus.h
devices/perseus/deviceperseus.cpp