SDRAngel: FreqTracker Class Reference
FreqTracker Class Reference
#include <freqtracker.h>
Classes
struct MagSqLevelsStore
class MsgConfigureChannelizer
class MsgConfigureFreqTracker
class MsgSampleRateNotification
Public Member Functions
FreqTracker (DeviceAPI *deviceAPI)
~FreqTracker ()
virtual void destroy ()
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool po)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
uint32_t getSampleRate () const
double getMagSq () const
bool getSquelchOpen () const
bool getPllLocked () const
Real getFrequency () const
Real getAvgDeltaFreq () const
void getMagSqLevels (double &avg, double &peak, int &nbSamples)
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.freqtracker"
static const QString m_channelId = "FreqTracker"
Private Types
enum RateState { RSInitialFill, RSRunning }
Private Slots
void networkManagerFinished (QNetworkReply *reply)
void tick ()
Private Member Functions
void applySettings (const FreqTrackerSettings &settings, bool force=false)
void applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force=false)
void setInterpolator ()
void configureChannelizer ()
void connectTimer ()
void disconnectTimer ()
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const FreqTrackerSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const FreqTrackerSettings &settings, bool force)
void processOneSample (Complex &ci)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
FreqTrackerSettings m_settings
uint32_t m_deviceSampleRate
int m_inputSampleRate
int m_inputFrequencyOffset
uint32_t m_channelSampleRate
bool m_running
NCOF m_nco
PhaseLockComplex m_pll
FreqLockComplex m_fll
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
fftfilt * m_rrcFilter
Real m_squelchLevel
uint32_t m_squelchCount
bool m_squelchOpen
uint32_t m_squelchGate
Squelch gate in samples.
double m_magsq
double m_magsqSum
double m_magsqPeak
int m_magsqCount
MagSqLevelsStore m_magSqLevelStore
MovingAverageUtil< Real, double, 16 > m_movingAverage
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
const QTimer * m_timer
bool m_timerConnected
uint32_t m_tickCount
int m_lastCorrAbs
Real m_avgDeltaFreq
QMutex m_settingsMutex
Static Private Attributes
static const int m_udpBlockSize = 512
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 49 of file freqtracker.h.
Member Enumeration Documentation
RateState
enum FreqTracker::RateState private
Enumerator
RSInitialFill
RSRunning
Definition at line 199 of file freqtracker.h.
                    {
         RSInitialFill,
         RSRunning
     };
Constructor & Destructor Documentation
FreqTracker()
FreqTracker::FreqTracker (DeviceAPI * deviceAPI)
Definition at line 53 of file freqtracker.cpp.
References DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), applyChannelSettings(), PhaseLockComplex::computeCoefficients(), DSPEngine::getMasterTimer(), DSPEngine::instance(), m_channelId, m_channelizer, m_channelSampleRate, m_deviceAPI, m_inputFrequencyOffset, m_inputSampleRate, m_magsq, m_networkManager, m_pll, FreqTrackerSettings::m_rfBandwidth, m_rrcFilter, m_settings, m_threadedChannelizer, m_timer, and networkManagerFinished().
                                              :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(deviceAPI),
         m_deviceSampleRate(48000),
         m_inputSampleRate(48000),
         m_inputFrequencyOffset(0),
         m_channelSampleRate(48000),
         m_running(false),
         m_squelchOpen(false),
         m_squelchGate(0),
         m_magsqSum(0.0f),
         m_magsqPeak(0.0f),
         m_magsqCount(0),
         m_timerConnected(false),
         m_tickCount(0),
         m_lastCorrAbs(0),
         m_avgDeltaFreq(0.0),
         m_settingsMutex(QMutex::Recursive)
 {
     setObjectName(m_channelId);
 #ifdef USE_INTERNAL_TIMER
 #warning "Uses internal timer"
     m_timer = new QTimer();
     m_timer->start(50);
 #else
     m_timer = &DSPEngine::instance()->getMasterTimer();
 #endif
     m_magsq = 0.0;
     m_rrcFilter = new fftfilt(m_settings.m_rfBandwidth / m_channelSampleRate, 2*1024);
     m_pll.computeCoefficients(0.002f, 0.5f, 10.0f); // bandwidth, damping factor, loop gain
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~FreqTracker()
FreqTracker::~FreqTracker ()
Definition at line 96 of file freqtracker.cpp.
References disconnectTimer(), m_channelizer, m_deviceAPI, m_networkManager, m_rrcFilter, m_threadedChannelizer, m_timer, networkManagerFinished(), DeviceAPI::removeChannelSink(), and DeviceAPI::removeChannelSinkAPI().
 {
     disconnectTimer();
 #ifdef USE_INTERNAL_TIMER
     m_timer->stop();
     delete m_timer;
 #endif
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete m_rrcFilter;
 }
Member Function Documentation
applyChannelSettings()
void FreqTracker::applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 297 of file freqtracker.cpp.
References m_inputFrequencyOffset, m_inputSampleRate, m_nco, m_settings, FreqTrackerSettings::m_tracking, NCOF::setFreq(), and setInterpolator().
Referenced by FreqTracker(), handleMessage(), and start().
 {
     if (!m_settings.m_tracking) {
         qDebug() << "FreqTracker::applyChannelSettings:"
                 << " inputSampleRate: " << inputSampleRate
                 << " inputFrequencyOffset: " << inputFrequencyOffset;
     }
     if ((m_inputFrequencyOffset != inputFrequencyOffset) ||
         (m_inputSampleRate != inputSampleRate) || force)
     {
         m_nco.setFreq(-inputFrequencyOffset, inputSampleRate);
     }
     if ((m_inputSampleRate != inputSampleRate) || force) {
         setInterpolator();
     }
     m_inputSampleRate = inputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applySettings()
void FreqTracker::applySettings (const FreqTrackerSettings & settings, bool force = false) private
Definition at line 319 of file freqtracker.cpp.
References configureChannelizer(), connectTimer(), disconnectTimer(), FreqTrackerSettings::m_alphaEMA, m_avgDeltaFreq, m_fll, FreqTrackerSettings::m_inputFrequencyOffset, m_lastCorrAbs, FreqTrackerSettings::m_log2Decim, m_pll, FreqTrackerSettings::m_pllPskOrder, FreqTrackerSettings::m_reverseAPIAddress, FreqTrackerSettings::m_reverseAPIChannelIndex, FreqTrackerSettings::m_reverseAPIDeviceIndex, FreqTrackerSettings::m_reverseAPIPort, FreqTrackerSettings::m_rfBandwidth, FreqTrackerSettings::m_rgbColor, FreqTrackerSettings::m_rrc, FreqTrackerSettings::m_rrcRolloff, m_settings, FreqTrackerSettings::m_squelch, FreqTrackerSettings::m_squelchGate, m_squelchLevel, FreqTrackerSettings::m_title, FreqTrackerSettings::m_trackerType, FreqTrackerSettings::m_tracking, FreqTrackerSettings::m_useReverseAPI, CalcDb::powerFromdB(), FreqLockComplex::reset(), PhaseLockComplex::reset(), setInterpolator(), PhaseLockComplex::setPskOrder(), FreqTrackerSettings::TrackerFLL, FreqTrackerSettings::TrackerNone, FreqTrackerSettings::TrackerPLL, and webapiReverseSendSettings().
Referenced by handleMessage(), and tick().
 {
     if (!settings.m_tracking)
     {
         qDebug() << "FreqTracker::applySettings:"
                 << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
                 << " m_rfBandwidth: " << settings.m_rfBandwidth
                 << " m_log2Decim: " << settings.m_log2Decim
                 << " m_squelch: " << settings.m_squelch
                 << " m_rgbColor: " << settings.m_rgbColor
                 << " m_title: " << settings.m_title
                 << " m_alphaEMA: " << settings.m_alphaEMA
                 << " m_tracking: " << settings.m_tracking
                 << " m_trackerType: " << settings.m_trackerType
                 << " m_pllPskOrder: " << settings.m_pllPskOrder
                 << " m_rrc: " << settings.m_rrc
                 << " m_rrcRolloff: " << settings.m_rrcRolloff
                 << " m_useReverseAPI: " << settings.m_useReverseAPI
                 << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
                 << " m_reverseAPIPort: " << settings.m_reverseAPIPort
                 << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex
                 << " m_reverseAPIChannelIndex: " << settings.m_reverseAPIChannelIndex
                 << " force: " << force;
     }
     QList<QString> reverseAPIKeys;
     bool updateChannelizer = false;
     bool updateInterpolator = false;
     if ((m_settings.m_inputFrequencyOffset != settings.m_inputFrequencyOffset) || force)
     {
         reverseAPIKeys.append("inputFrequencyOffset");
         updateChannelizer = true;
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         reverseAPIKeys.append("log2Decim");
         updateChannelizer = true;
     }
     if ((m_settings.m_rfBandwidth != settings.m_rfBandwidth) || force)
     {
         updateInterpolator = true;
         reverseAPIKeys.append("rfBandwidth");
     }
     if ((m_settings.m_squelch != settings.m_squelch) || force)
     {
         m_squelchLevel = CalcDb::powerFromdB(settings.m_squelch);
         reverseAPIKeys.append("squelch");
     }
     if ((m_settings.m_rgbColor != settings.m_rgbColor) || force) {
         reverseAPIKeys.append("rgbColor");
     }
     if ((m_settings.m_title != settings.m_title) || force) {
         reverseAPIKeys.append("title");
     }
     if ((m_settings.m_alphaEMA != settings.m_alphaEMA) || force) {
         reverseAPIKeys.append("alphaEMA");
     }
     if ((m_settings.m_tracking != settings.m_tracking) || force)
     {
         reverseAPIKeys.append("tracking");
         m_avgDeltaFreq = 0.0;
         m_lastCorrAbs = 0;
         if (settings.m_tracking)
         {
             m_pll.reset();
             m_fll.reset();
         }
     }
     if ((m_settings.m_trackerType != settings.m_trackerType) || force)
     {
         reverseAPIKeys.append("trackerType");
         m_lastCorrAbs = 0;
         m_avgDeltaFreq = 0.0;
         if (settings.m_trackerType == FreqTrackerSettings::TrackerFLL) {
             m_fll.reset();
         } else if (settings.m_trackerType == FreqTrackerSettings::TrackerPLL) {
             m_pll.reset();
         }
         if (settings.m_trackerType == FreqTrackerSettings::TrackerNone) {
             disconnectTimer();
         } else {
             connectTimer();
         }
     }
     if ((m_settings.m_pllPskOrder != settings.m_pllPskOrder) || force)
     {
         reverseAPIKeys.append("pllPskOrder");
         if (settings.m_pllPskOrder < 32) {
             m_pll.setPskOrder(settings.m_pllPskOrder);
         }
     }
     if ((m_settings.m_rrc != settings.m_rrc) || force) {
         reverseAPIKeys.append("rrc");
     }
     if ((m_settings.m_rrcRolloff != settings.m_rrcRolloff) || force)
     {
         reverseAPIKeys.append("rrcRolloff");
         updateInterpolator = true;
     }
     if ((m_settings.m_squelchGate != settings.m_squelchGate) || force)
     {
         reverseAPIKeys.append("squelchGate");
         updateInterpolator = true;
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     if (updateChannelizer) {
         configureChannelizer();
     } else if (updateInterpolator) {
         setInterpolator();
     }
 }
configureChannelizer()
void FreqTracker::configureChannelizer () private
Definition at line 467 of file freqtracker.cpp.
References DownChannelizer::configure(), FreqTracker::MsgSampleRateNotification::create(), BasebandSampleSink::getInputMessageQueue(), m_channelizer, m_channelSampleRate, m_deviceSampleRate, m_fll, BasebandSampleSink::m_guiMessageQueue, FreqTrackerSettings::m_inputFrequencyOffset, FreqTrackerSettings::m_log2Decim, m_pll, m_settings, FreqTrackerSettings::m_tracking, MessageQueue::push(), FreqLockComplex::setSampleRate(), and PhaseLockComplex::setSampleRate().
Referenced by applySettings(), and handleMessage().
 {
     if (m_channelSampleRate != m_deviceSampleRate / (1<<m_settings.m_log2Decim))
     {
         m_channelSampleRate = m_deviceSampleRate / (1<<m_settings.m_log2Decim);
         m_pll.setSampleRate(m_channelSampleRate);
         m_fll.setSampleRate(m_channelSampleRate);
     }
     if (!m_settings.m_tracking) {
         qDebug() << "FreqTracker::configureChannelizer:"
                 << " sampleRate: " << m_channelSampleRate
                 << " inputFrequencyOffset: " << m_settings.m_inputFrequencyOffset;
     }
     m_channelizer->configure(m_channelizer->getInputMessageQueue(),
         m_channelSampleRate,
         m_settings.m_inputFrequencyOffset);
     if (m_guiMessageQueue)
     {
         MsgSampleRateNotification *msg = MsgSampleRateNotification::create(
             m_deviceSampleRate / (1<<m_settings.m_log2Decim),
             m_settings.m_inputFrequencyOffset);
         m_guiMessageQueue->push(msg);
     }
 }
connectTimer()
void FreqTracker::connectTimer () private
Definition at line 495 of file freqtracker.cpp.
References m_tickCount, m_timer, m_timerConnected, and tick().
Referenced by applySettings().
 {
     if (!m_timerConnected)
     {
         m_tickCount = 0;
         connect(m_timer, SIGNAL(timeout()), this, SLOT(tick()));
         m_timerConnected = true;
     }
 }
deserialize()
bool FreqTracker::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 519 of file freqtracker.cpp.
References FreqTracker::MsgConfigureFreqTracker::create(), FreqTrackerSettings::deserialize(), BasebandSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and FreqTrackerSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureFreqTracker *msg = MsgConfigureFreqTracker::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureFreqTracker *msg = MsgConfigureFreqTracker::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void FreqTracker::destroy () inline virtual
Implements ChannelAPI.
Definition at line 122 of file freqtracker.h.
References feed(), handleMessage(), start(), and stop().
 { delete this; }
disconnectTimer()
void FreqTracker::disconnectTimer () private
Definition at line 505 of file freqtracker.cpp.
References m_timer, m_timerConnected, and tick().
Referenced by applySettings(), and ~FreqTracker().
 {
     if (m_timerConnected)
     {
         disconnect(m_timer, SIGNAL(timeout()), this, SLOT(tick()));
         m_timerConnected = false;
     }
 }
feed()
void FreqTracker::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool po) virtual
Implements BasebandSampleSink.
Definition at line 112 of file freqtracker.cpp.
References Interpolator::decimate(), Interpolator::interpolate(), m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_nco, m_running, m_settingsMutex, NCOF::nextIQ(), and processOneSample().
Referenced by destroy().
 {
     (void) firstOfBurst;
     Complex ci;
     if (!m_running) {
         return;
     }
     m_settingsMutex.lock();
     for (SampleVector::const_iterator it = begin; it != end; ++it)
     {
         Complex c(it->real(), it->imag());
         c *= m_nco.nextIQ();
         if (m_interpolatorDistance < 1.0f) // interpolate
         {
             processOneSample(ci);
             while (m_interpolator.interpolate(&m_interpolatorDistanceRemain, c, &ci))
             {
                 processOneSample(ci);
             }
             m_interpolatorDistanceRemain += m_interpolatorDistance;
         }
         else // decimate
         {
             if (m_interpolator.decimate(&m_interpolatorDistanceRemain, c, &ci))
             {
                 processOneSample(ci);
                 m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
         }
     }
     m_settingsMutex.unlock();
 }
getAvgDeltaFreq()
Real FreqTracker::getAvgDeltaFreq () const inline
Definition at line 165 of file freqtracker.h.
References m_avgDeltaFreq.
Referenced by FreqTrackerGUI::tick().
 { return m_avgDeltaFreq; }
getCenterFrequency()
virtual qint64 FreqTracker::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 131 of file freqtracker.h.
References deserialize(), FreqTrackerSettings::m_inputFrequencyOffset, FreqTracker::MsgConfigureFreqTracker::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getFrequency()
Real FreqTracker::getFrequency () const
Definition at line 242 of file freqtracker.cpp.
References FreqLockComplex::getFreq(), PhaseLockComplex::getFreq(), m_channelSampleRate, m_fll, M_PI, m_pll, m_settings, FreqTrackerSettings::m_trackerType, FreqTrackerSettings::TrackerFLL, and FreqTrackerSettings::TrackerPLL.
Referenced by getPllLocked(), and tick().
 {
     if (m_settings.m_trackerType == FreqTrackerSettings::TrackerPLL) {
         return (m_pll.getFreq() * m_channelSampleRate) / (2.0 * M_PI);
     } else if (m_settings.m_trackerType == FreqTrackerSettings::TrackerFLL) {
         return (m_fll.getFreq() * m_channelSampleRate) / (2.0 * M_PI);
     } else {
         return 0;
     }
 }
getIdentifier()
virtual void FreqTracker::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 129 of file freqtracker.h.
 { id = objectName(); }
getMagSq()
double FreqTracker::getMagSq () const inline
Definition at line 161 of file freqtracker.h.
References m_magsq.
 { return m_magsq; }
getMagSqLevels()
void FreqTracker::getMagSqLevels (double & avg, double & peak, int & nbSamples) inline
Definition at line 167 of file freqtracker.h.
References FreqTracker::MagSqLevelsStore::m_magsq, m_magsq, m_magsqCount, m_magSqLevelStore, FreqTracker::MagSqLevelsStore::m_magsqPeak, m_magsqPeak, and m_magsqSum.
Referenced by FreqTrackerGUI::tick(), and webapiFormatChannelReport().
     {
         if (m_magsqCount > 0)
         {
             m_magsq = m_magsqSum / m_magsqCount;
             m_magSqLevelStore.m_magsq = m_magsq;
             m_magSqLevelStore.m_magsqPeak = m_magsqPeak;
         }
         avg = m_magSqLevelStore.m_magsq;
         peak = m_magSqLevelStore.m_magsqPeak;
         nbSamples = m_magsqCount == 0 ? 1 : m_magsqCount;
         m_magsqSum = 0.0f;
         m_magsqPeak = 0.0f;
         m_magsqCount = 0;
     }
getNbSinkStreams()
virtual int FreqTracker::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 136 of file freqtracker.h.
 { return 1; }
getNbSourceStreams()
virtual int FreqTracker::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 137 of file freqtracker.h.
 { return 0; }
getPllLocked()
bool FreqTracker::getPllLocked () const inline
Definition at line 163 of file freqtracker.h.
References getFrequency(), PhaseLockComplex::locked(), m_pll, FreqTracker::MsgConfigureFreqTracker::m_settings, FreqTrackerSettings::m_trackerType, and FreqTrackerSettings::TrackerPLL.
Referenced by FreqTrackerGUI::tick().
 { return (m_settings.m_trackerType == FreqTrackerSettings::TrackerPLL) && m_pll.locked(); }
getSampleRate()
uint32_t FreqTracker::getSampleRate () const inline
Definition at line 160 of file freqtracker.h.
References m_channelSampleRate.
 { return m_channelSampleRate; }
getSquelchOpen()
bool FreqTracker::getSquelchOpen () const inline
Definition at line 162 of file freqtracker.h.
References m_squelchOpen.
Referenced by FreqTrackerGUI::tick(), and tick().
 { return m_squelchOpen; }
getStreamCenterFrequency()
virtual qint64 FreqTracker::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 139 of file freqtracker.h.
References FreqTrackerSettings::m_inputFrequencyOffset, FreqTracker::MsgConfigureFreqTracker::m_settings, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void FreqTracker::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 130 of file freqtracker.h.
References FreqTracker::MsgConfigureFreqTracker::m_settings, and FreqTrackerSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool FreqTracker::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 253 of file freqtracker.cpp.
References applyChannelSettings(), applySettings(), configureChannelizer(), DSPSignalNotification::getCenterFrequency(), FreqTracker::MsgConfigureFreqTracker::getForce(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), DSPSignalNotification::getSampleRate(), FreqTracker::MsgConfigureFreqTracker::getSettings(), m_deviceSampleRate, m_settings, FreqTrackerSettings::m_tracking, Message::match(), and setInterpolator().
Referenced by destroy().
 {
     if (DSPSignalNotification::match(cmd))
     {
         DSPSignalNotification& notif = (DSPSignalNotification&) cmd;
         m_deviceSampleRate = notif.getSampleRate();
         qDebug() << "FreqTracker::handleMessage: DSPSignalNotification:"
                 << " m_deviceSampleRate: " << m_deviceSampleRate
                 << " centerFrequency: " << notif.getCenterFrequency();
         configureChannelizer();
         return true;
     }
     else if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& notif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         if (!m_settings.m_tracking) {
             qDebug() << "FreqTracker::handleMessage: MsgChannelizerNotification:"
                     << " inputSampleRate: " << notif.getSampleRate()
                     << " inputFrequencyOffset: " << notif.getFrequencyOffset();
         }
         applyChannelSettings(notif.getSampleRate(), notif.getFrequencyOffset());
         setInterpolator();
         return true;
     }
     else if (MsgConfigureFreqTracker::match(cmd))
     {
         MsgConfigureFreqTracker& cfg = (MsgConfigureFreqTracker&) cmd;
         qDebug() << "FreqTracker::handleMessage: MsgConfigureFreqTracker";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else
     {
         return false;
     }
 }
networkManagerFinished
void FreqTracker::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 738 of file freqtracker.cpp.
Referenced by FreqTracker(), and ~FreqTracker().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "FreqTracker::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("FreqTracker::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
processOneSample()
void FreqTracker::processOneSample (Complex & ci) private
Definition at line 152 of file freqtracker.cpp.
References MovingAverageUtil< T, Total, N >::asDouble(), FreqLockComplex::feed(), PhaseLockComplex::feed(), i, m_fll, m_magsq, m_magsqCount, m_magsqPeak, m_magsqSum, m_movingAverage, m_pll, FreqTrackerSettings::m_rrc, m_rrcFilter, m_settings, m_squelchCount, m_squelchGate, m_squelchLevel, m_squelchOpen, FreqTrackerSettings::m_trackerType, fftfilt::runFilt(), SDR_RX_SCALEF, FreqTrackerSettings::TrackerFLL, and FreqTrackerSettings::TrackerPLL.
Referenced by feed().
 {
     fftfilt::cmplx *sideband;
     int n_out;
     if (m_settings.m_rrc)
     {
         n_out = m_rrcFilter->runFilt(ci, &sideband);
     }
     else
     {
         n_out = 1;
         sideband = &ci;
     }
     for (int i = 0; i < n_out; i++)
     {
         Real re = sideband[i].real() / SDR_RX_SCALEF;
         Real im = sideband[i].imag() / SDR_RX_SCALEF;
         Real magsq = re*re + im*im;
         m_movingAverage(magsq);
         m_magsq = m_movingAverage.asDouble();
         m_magsqSum += magsq;
         if (magsq > m_magsqPeak)
         {
             m_magsqPeak = magsq;
         }
         m_magsqCount++;
         if (m_magsq < m_squelchLevel)
         {
             if (m_squelchGate > 0)
             {
                 if (m_squelchCount > 0) {
                     m_squelchCount--;
                 }
                 m_squelchOpen = m_squelchCount >= m_squelchGate;
             }
             else
             {
                 m_squelchOpen = false;
             }
         }
         else
         {
             if (m_squelchGate > 0)
             {
                 if (m_squelchCount < 2*m_squelchGate) {
                     m_squelchCount++;
                 }
                 m_squelchOpen = m_squelchCount >= m_squelchGate;
             }
             else
             {
                 m_squelchOpen = true;
             }
         }
         if (m_squelchOpen)
         {
             if (m_settings.m_trackerType == FreqTrackerSettings::TrackerFLL)
             {
                 m_fll.feed(re, im);
             }
             else if (m_settings.m_trackerType == FreqTrackerSettings::TrackerPLL)
             {
                 m_pll.feed(re, im);
             }
         }
     }
 }
serialize()
QByteArray FreqTracker::serialize () const virtual
Implements ChannelAPI.
Definition at line 514 of file freqtracker.cpp.
References m_settings, and FreqTrackerSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
setInterpolator()
void FreqTracker::setInterpolator () private
Definition at line 456 of file freqtracker.cpp.
References Interpolator::create(), fftfilt::create_rrc_filter(), m_channelSampleRate, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, FreqTrackerSettings::m_rfBandwidth, m_rrcFilter, FreqTrackerSettings::m_rrcRolloff, m_settings, m_settingsMutex, FreqTrackerSettings::m_squelchGate, and m_squelchGate.
Referenced by applyChannelSettings(), applySettings(), and handleMessage().
 {
     m_settingsMutex.lock();
     m_interpolator.create(16, m_inputSampleRate, m_settings.m_rfBandwidth / 2.2f);
     m_interpolatorDistanceRemain = 0;
     m_interpolatorDistance = (Real) m_inputSampleRate / (Real) m_channelSampleRate;
     m_rrcFilter->create_rrc_filter(m_settings.m_rfBandwidth / m_channelSampleRate, m_settings.m_rrcRolloff / 100.0);
     m_squelchGate = (m_channelSampleRate / 100) * m_settings.m_squelchGate; // gate is given in 10s of ms at channel sample rate
     m_settingsMutex.unlock();
 }
start()
void FreqTracker::start () virtual
Implements BasebandSampleSink.
Definition at line 228 of file freqtracker.cpp.
References applyChannelSettings(), m_inputFrequencyOffset, m_inputSampleRate, m_running, and m_squelchCount.
Referenced by destroy().
 {
     qDebug("FreqTracker::start");
     m_squelchCount = 0;
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
     m_running = true;
 }
stop()
void FreqTracker::stop () virtual
Implements BasebandSampleSink.
Definition at line 236 of file freqtracker.cpp.
References m_running.
Referenced by destroy().
 {
     qDebug("FreqTracker::stop");
     m_running = false;
 }
tick
void FreqTracker::tick () private slot
Definition at line 756 of file freqtracker.cpp.
References applySettings(), getFrequency(), getSquelchOpen(), FreqTrackerSettings::m_alphaEMA, m_avgDeltaFreq, m_channelSampleRate, FreqTrackerSettings::m_inputFrequencyOffset, m_lastCorrAbs, m_settings, m_tickCount, and FreqTrackerSettings::m_tracking.
Referenced by connectTimer(), and disconnectTimer().
 {
     if (getSquelchOpen()) {
         m_avgDeltaFreq = m_settings.m_alphaEMA*getFrequency() + (1.0 - m_settings.m_alphaEMA)*m_avgDeltaFreq;
     }
     if (m_tickCount < 9)
     {
         m_tickCount++;
     }
     else
     {
         if ((m_settings.m_tracking) && getSquelchOpen())
         {
             uint32_t decayDivider = 200.0 * m_settings.m_alphaEMA;
             int decayAmount = m_channelSampleRate < decayDivider ? 1 : m_channelSampleRate / decayDivider;
             int trim = m_channelSampleRate / 1000;
             if (m_lastCorrAbs < decayAmount)
             {
                 m_lastCorrAbs = m_avgDeltaFreq < 0 ? -m_avgDeltaFreq : m_avgDeltaFreq;
                 if (m_lastCorrAbs > trim)
                 {
                     FreqTrackerSettings settings = m_settings;
                     settings.m_inputFrequencyOffset += m_avgDeltaFreq;
                     applySettings(settings);
                 }
             }
             else
             {
                 m_lastCorrAbs -= decayAmount;
             }
         }
         m_tickCount = 0;
     }
 }
webapiFormatChannelReport()
void FreqTracker::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 676 of file freqtracker.cpp.
References CalcDb::dbPower(), SWGSDRangel::SWGChannelReport::getFreqTrackerReport(), getMagSqLevels(), m_channelSampleRate, m_inputSampleRate, m_squelchOpen, SWGSDRangel::SWGFreqTrackerReport::setChannelPowerDb(), SWGSDRangel::SWGFreqTrackerReport::setChannelSampleRate(), SWGSDRangel::SWGFreqTrackerReport::setSampleRate(), and SWGSDRangel::SWGFreqTrackerReport::setSquelch().
Referenced by webapiReportGet().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     response.getFreqTrackerReport()->setChannelPowerDb(CalcDb::dbPower(magsqAvg));
     response.getFreqTrackerReport()->setSquelch(m_squelchOpen ? 1 : 0);
     response.getFreqTrackerReport()->setSampleRate(m_channelSampleRate);
     response.getFreqTrackerReport()->setChannelSampleRate(m_inputSampleRate);
 }
webapiFormatChannelSettings()
void FreqTracker::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const FreqTrackerSettings & settings) private
Definition at line 642 of file freqtracker.cpp.
References SWGSDRangel::SWGChannelSettings::getFreqTrackerSettings(), SWGSDRangel::SWGFreqTrackerSettings::getReverseApiAddress(), SWGSDRangel::SWGFreqTrackerSettings::getTitle(), FreqTrackerSettings::m_alphaEMA, FreqTrackerSettings::m_inputFrequencyOffset, FreqTrackerSettings::m_log2Decim, FreqTrackerSettings::m_pllPskOrder, FreqTrackerSettings::m_reverseAPIAddress, FreqTrackerSettings::m_reverseAPIChannelIndex, FreqTrackerSettings::m_reverseAPIDeviceIndex, FreqTrackerSettings::m_reverseAPIPort, FreqTrackerSettings::m_rfBandwidth, FreqTrackerSettings::m_rgbColor, FreqTrackerSettings::m_rrc, FreqTrackerSettings::m_rrcRolloff, m_settings, FreqTrackerSettings::m_squelch, FreqTrackerSettings::m_squelchGate, FreqTrackerSettings::m_title, FreqTrackerSettings::m_trackerType, FreqTrackerSettings::m_tracking, FreqTrackerSettings::m_useReverseAPI, SWGSDRangel::SWGFreqTrackerSettings::setAlphaEma(), SWGSDRangel::SWGFreqTrackerSettings::setInputFrequencyOffset(), SWGSDRangel::SWGFreqTrackerSettings::setLog2Decim(), SWGSDRangel::SWGFreqTrackerSettings::setPllPskOrder(), SWGSDRangel::SWGFreqTrackerSettings::setReverseApiAddress(), SWGSDRangel::SWGFreqTrackerSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGFreqTrackerSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGFreqTrackerSettings::setReverseApiPort(), SWGSDRangel::SWGFreqTrackerSettings::setRfBandwidth(), SWGSDRangel::SWGFreqTrackerSettings::setRgbColor(), SWGSDRangel::SWGFreqTrackerSettings::setRrc(), SWGSDRangel::SWGFreqTrackerSettings::setRrcRolloff(), SWGSDRangel::SWGFreqTrackerSettings::setSquelch(), SWGSDRangel::SWGFreqTrackerSettings::setSquelchGate(), SWGSDRangel::SWGFreqTrackerSettings::setTitle(), SWGSDRangel::SWGFreqTrackerSettings::setTrackerType(), SWGSDRangel::SWGFreqTrackerSettings::setTracking(), and SWGSDRangel::SWGFreqTrackerSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getFreqTrackerSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getFreqTrackerSettings()->setRfBandwidth(settings.m_rfBandwidth);
     response.getFreqTrackerSettings()->setLog2Decim(settings.m_log2Decim);
     response.getFreqTrackerSettings()->setSquelch(settings.m_squelch);
     response.getFreqTrackerSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getFreqTrackerSettings()->getTitle()) {
         *response.getFreqTrackerSettings()->getTitle() = settings.m_title;
     } else {
         response.getFreqTrackerSettings()->setTitle(new QString(settings.m_title));
     }
     response.getFreqTrackerSettings()->setAlphaEma(m_settings.m_alphaEMA);
     response.getFreqTrackerSettings()->setTracking(m_settings.m_tracking ? 1 : 0);
     response.getFreqTrackerSettings()->setTrackerType((int) m_settings.m_trackerType);
     response.getFreqTrackerSettings()->setPllPskOrder(m_settings.m_pllPskOrder);
     response.getFreqTrackerSettings()->setRrc(m_settings.m_rrc ? 1 : 0);
     response.getFreqTrackerSettings()->setRrcRolloff(m_settings.m_rrcRolloff);
     response.getFreqTrackerSettings()->setSquelchGate(m_settings.m_squelchGate);
     response.getFreqTrackerSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getFreqTrackerSettings()->getReverseApiAddress()) {
         *response.getFreqTrackerSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getFreqTrackerSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getFreqTrackerSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getFreqTrackerSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getFreqTrackerSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int FreqTracker::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 631 of file freqtracker.cpp.
References SWGSDRangel::SWGChannelReport::getFreqTrackerReport(), SWGSDRangel::SWGFreqTrackerReport::init(), SWGSDRangel::SWGChannelReport::setFreqTrackerReport(), and webapiFormatChannelReport().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setFreqTrackerReport(new SWGSDRangel::SWGFreqTrackerReport());
     response.getFreqTrackerReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendSettings()
void FreqTracker::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const FreqTrackerSettings & settings, bool force) private
Definition at line 688 of file freqtracker.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), ChannelAPI::getDeviceSetIndex(), SWGSDRangel::SWGChannelSettings::getFreqTrackerSettings(), ChannelAPI::getIndexInDeviceSet(), FreqTrackerSettings::m_inputFrequencyOffset, m_networkManager, m_networkRequest, FreqTrackerSettings::m_reverseAPIAddress, FreqTrackerSettings::m_reverseAPIChannelIndex, FreqTrackerSettings::m_reverseAPIDeviceIndex, FreqTrackerSettings::m_reverseAPIPort, FreqTrackerSettings::m_rfBandwidth, FreqTrackerSettings::m_rgbColor, FreqTrackerSettings::m_squelch, FreqTrackerSettings::m_title, FreqTrackerSettings::m_trackerType, SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGChannelSettings::setFreqTrackerSettings(), SWGSDRangel::SWGFreqTrackerSettings::setInputFrequencyOffset(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGFreqTrackerSettings::setRfBandwidth(), SWGSDRangel::SWGFreqTrackerSettings::setRgbColor(), SWGSDRangel::SWGFreqTrackerSettings::setSquelch(), SWGSDRangel::SWGFreqTrackerSettings::setTitle(), and SWGSDRangel::SWGFreqTrackerSettings::setTrackerType().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(0); // single sink (Rx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("FreqTracker"));
     swgChannelSettings->setFreqTrackerSettings(new SWGSDRangel::SWGFreqTrackerSettings());
     SWGSDRangel::SWGFreqTrackerSettings *swgFreqTrackerSettings = swgChannelSettings->getFreqTrackerSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgFreqTrackerSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("rfBandwidth") || force) {
         swgFreqTrackerSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgFreqTrackerSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("squelch") || force) {
         swgFreqTrackerSettings->setSquelch(settings.m_squelch);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgFreqTrackerSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("trackerType") || force) {
         swgFreqTrackerSettings->setTrackerType((int) settings.m_trackerType);
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int FreqTracker::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 536 of file freqtracker.cpp.
References SWGSDRangel::SWGChannelSettings::getFreqTrackerSettings(), SWGSDRangel::SWGFreqTrackerSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setFreqTrackerSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setFreqTrackerSettings(new SWGSDRangel::SWGFreqTrackerSettings());
     response.getFreqTrackerSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int FreqTracker::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 547 of file freqtracker.cpp.
References FreqTracker::MsgConfigureFreqTracker::create(), SWGSDRangel::SWGFreqTrackerSettings::getAlphaEma(), SWGSDRangel::SWGChannelSettings::getAmDemodSettings(), SWGSDRangel::SWGChannelSettings::getFreqTrackerSettings(), SWGSDRangel::SWGFreqTrackerSettings::getInputFrequencyOffset(), SWGSDRangel::SWGFreqTrackerSettings::getLog2Decim(), SWGSDRangel::SWGFreqTrackerSettings::getPllPskOrder(), SWGSDRangel::SWGAMDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGAMDemodSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGAMDemodSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGAMDemodSettings::getReverseApiPort(), SWGSDRangel::SWGFreqTrackerSettings::getRfBandwidth(), SWGSDRangel::SWGFreqTrackerSettings::getRgbColor(), SWGSDRangel::SWGFreqTrackerSettings::getRrc(), SWGSDRangel::SWGFreqTrackerSettings::getRrcRolloff(), SWGSDRangel::SWGFreqTrackerSettings::getSquelch(), SWGSDRangel::SWGFreqTrackerSettings::getSquelchGate(), SWGSDRangel::SWGFreqTrackerSettings::getTitle(), SWGSDRangel::SWGFreqTrackerSettings::getTrackerType(), SWGSDRangel::SWGFreqTrackerSettings::getTracking(), SWGSDRangel::SWGAMDemodSettings::getUseReverseApi(), FreqTrackerSettings::m_alphaEMA, BasebandSampleSink::m_guiMessageQueue, FreqTrackerSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, FreqTrackerSettings::m_log2Decim, FreqTrackerSettings::m_pllPskOrder, FreqTrackerSettings::m_reverseAPIAddress, FreqTrackerSettings::m_reverseAPIChannelIndex, FreqTrackerSettings::m_reverseAPIDeviceIndex, FreqTrackerSettings::m_reverseAPIPort, FreqTrackerSettings::m_rfBandwidth, FreqTrackerSettings::m_rgbColor, FreqTrackerSettings::m_rrc, FreqTrackerSettings::m_rrcRolloff, m_settings, FreqTrackerSettings::m_squelch, FreqTrackerSettings::m_squelchGate, FreqTrackerSettings::m_title, FreqTrackerSettings::m_trackerType, FreqTrackerSettings::m_tracking, FreqTrackerSettings::m_useReverseAPI, MessageQueue::push(), FreqTrackerSettings::TrackerFLL, FreqTrackerSettings::TrackerPLL, and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     FreqTrackerSettings settings = m_settings;
     if (channelSettingsKeys.contains("inputFrequencyOffset")) {
         settings.m_inputFrequencyOffset = response.getFreqTrackerSettings()->getInputFrequencyOffset();
     }
     if (channelSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getFreqTrackerSettings()->getRfBandwidth();
     }
     if (channelSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getFreqTrackerSettings()->getLog2Decim();
     }
     if (channelSettingsKeys.contains("squelch")) {
         settings.m_squelch = response.getFreqTrackerSettings()->getSquelch();
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getFreqTrackerSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getFreqTrackerSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("alphaEMA")) {
         float alphaEMA =  response.getFreqTrackerSettings()->getAlphaEma();
         settings.m_alphaEMA = alphaEMA < 0.01 ? 0.01 : alphaEMA > 1.0 ? 1.0 : alphaEMA;
     }
     if (channelSettingsKeys.contains("tracking")) {
         settings.m_tracking = response.getFreqTrackerSettings()->getTracking() ? 1 : 0;
     }
     if (channelSettingsKeys.contains("trackerType"))
     {
         int32_t trackerTypeCode = response.getFreqTrackerSettings()->getTrackerType();
         settings.m_trackerType = trackerTypeCode < 0 ?
             FreqTrackerSettings::TrackerFLL : trackerTypeCode > 1 ?
                 FreqTrackerSettings::TrackerPLL : (FreqTrackerSettings::TrackerType) trackerTypeCode;
     }
     if (channelSettingsKeys.contains("pllPskOrder")) {
         settings.m_pllPskOrder = response.getFreqTrackerSettings()->getPllPskOrder();
     }
     if (channelSettingsKeys.contains("rrc")) {
         settings.m_rrc = response.getFreqTrackerSettings()->getRrc() ? 1 : 0;
     }
     if (channelSettingsKeys.contains("rrcRolloff")) {
         settings.m_rrcRolloff = response.getFreqTrackerSettings()->getRrcRolloff();
     }
     if (channelSettingsKeys.contains("squelchGate")) {
         settings.m_squelchGate = response.getFreqTrackerSettings()->getSquelchGate();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getAmDemodSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getAmDemodSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getAmDemodSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getAmDemodSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getAmDemodSettings()->getReverseApiChannelIndex();
     }
     MsgConfigureFreqTracker *msg = MsgConfigureFreqTracker::create(settings, force);
     m_inputMessageQueue.push(msg);
     qDebug("FreqTracker::webapiSettingsPutPatch: forward to GUI: %p", m_guiMessageQueue);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureFreqTracker *msgToGUI = MsgConfigureFreqTracker::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_avgDeltaFreq
Real FreqTracker::m_avgDeltaFreq private
Definition at line 244 of file freqtracker.h.
Referenced by applySettings(), getAvgDeltaFreq(), and tick().
m_channelId
const QString FreqTracker::m_channelId = "FreqTracker" static
Definition at line 186 of file freqtracker.h.
Referenced by FreqTracker(), and FreqTrackerPlugin::initPlugin().
m_channelIdURI
const QString FreqTracker::m_channelIdURI = "sdrangel.channel.freqtracker" static
Definition at line 185 of file freqtracker.h.
Referenced by FreqTrackerGUI::FreqTrackerGUI(), and FreqTrackerPlugin::initPlugin().
m_channelizer
DownChannelizer* FreqTracker::m_channelizer private
Definition at line 206 of file freqtracker.h.
Referenced by configureChannelizer(), FreqTracker(), and ~FreqTracker().
m_channelSampleRate
uint32_t FreqTracker::m_channelSampleRate private
Definition at line 212 of file freqtracker.h.
Referenced by configureChannelizer(), FreqTracker(), getFrequency(), getSampleRate(), setInterpolator(), tick(), and webapiFormatChannelReport().
m_deviceAPI
DeviceAPI* FreqTracker::m_deviceAPI private
Definition at line 204 of file freqtracker.h.
Referenced by FreqTracker(), and ~FreqTracker().
m_deviceSampleRate
uint32_t FreqTracker::m_deviceSampleRate private
Definition at line 209 of file freqtracker.h.
Referenced by configureChannelizer(), and handleMessage().
m_fll
FreqLockComplex FreqTracker::m_fll private
Definition at line 217 of file freqtracker.h.
Referenced by applySettings(), configureChannelizer(), getFrequency(), and processOneSample().
m_inputFrequencyOffset
int FreqTracker::m_inputFrequencyOffset private
Definition at line 211 of file freqtracker.h.
Referenced by applyChannelSettings(), FreqTracker(), and start().
m_inputSampleRate
int FreqTracker::m_inputSampleRate private
Definition at line 210 of file freqtracker.h.
Referenced by applyChannelSettings(), FreqTracker(), setInterpolator(), start(), and webapiFormatChannelReport().
m_interpolator
Interpolator FreqTracker::m_interpolator private
Definition at line 218 of file freqtracker.h.
Referenced by feed(), and setInterpolator().
m_interpolatorDistance
Real FreqTracker::m_interpolatorDistance private
Definition at line 219 of file freqtracker.h.
Referenced by feed(), and setInterpolator().
m_interpolatorDistanceRemain
Real FreqTracker::m_interpolatorDistanceRemain private
Definition at line 220 of file freqtracker.h.
Referenced by feed(), and setInterpolator().
m_lastCorrAbs
int FreqTracker::m_lastCorrAbs private
Definition at line 243 of file freqtracker.h.
Referenced by applySettings(), and tick().
m_magsq
double FreqTracker::m_magsq private
Definition at line 228 of file freqtracker.h.
Referenced by FreqTracker(), getMagSq(), getMagSqLevels(), and processOneSample().
m_magsqCount
int FreqTracker::m_magsqCount private
Definition at line 231 of file freqtracker.h.
Referenced by getMagSqLevels(), and processOneSample().
m_magSqLevelStore
MagSqLevelsStore FreqTracker::m_magSqLevelStore private
Definition at line 232 of file freqtracker.h.
Referenced by getMagSqLevels().
m_magsqPeak
double FreqTracker::m_magsqPeak private
Definition at line 230 of file freqtracker.h.
Referenced by getMagSqLevels(), and processOneSample().
m_magsqSum
double FreqTracker::m_magsqSum private
Definition at line 229 of file freqtracker.h.
Referenced by getMagSqLevels(), and processOneSample().
m_movingAverage
MovingAverageUtil<Real, double, 16> FreqTracker::m_movingAverage private
Definition at line 234 of file freqtracker.h.
Referenced by processOneSample().
m_nco
NCOF FreqTracker::m_nco private
Definition at line 215 of file freqtracker.h.
Referenced by applyChannelSettings(), and feed().
m_networkManager
QNetworkAccessManager* FreqTracker::m_networkManager private
Definition at line 237 of file freqtracker.h.
Referenced by FreqTracker(), webapiReverseSendSettings(), and ~FreqTracker().
m_networkRequest
QNetworkRequest FreqTracker::m_networkRequest private
Definition at line 238 of file freqtracker.h.
Referenced by webapiReverseSendSettings().
m_pll
PhaseLockComplex FreqTracker::m_pll private
Definition at line 216 of file freqtracker.h.
Referenced by applySettings(), configureChannelizer(), FreqTracker(), getFrequency(), getPllLocked(), and processOneSample().
m_rrcFilter
fftfilt* FreqTracker::m_rrcFilter private
Definition at line 222 of file freqtracker.h.
Referenced by FreqTracker(), processOneSample(), setInterpolator(), and ~FreqTracker().
m_running
bool FreqTracker::m_running private
Definition at line 213 of file freqtracker.h.
Referenced by feed(), start(), and stop().
m_settings
FreqTrackerSettings FreqTracker::m_settings private
Definition at line 207 of file freqtracker.h.
Referenced by applyChannelSettings(), applySettings(), configureChannelizer(), deserialize(), FreqTracker(), getFrequency(), handleMessage(), processOneSample(), serialize(), setInterpolator(), tick(), webapiFormatChannelSettings(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex FreqTracker::m_settingsMutex private
Definition at line 245 of file freqtracker.h.
Referenced by feed(), and setInterpolator().
m_squelchCount
uint32_t FreqTracker::m_squelchCount private
Definition at line 225 of file freqtracker.h.
Referenced by processOneSample(), and start().
m_squelchGate
uint32_t FreqTracker::m_squelchGate private
Squelch gate in samples.
Definition at line 227 of file freqtracker.h.
Referenced by processOneSample(), and setInterpolator().
m_squelchLevel
Real FreqTracker::m_squelchLevel private
Definition at line 224 of file freqtracker.h.
Referenced by applySettings(), and processOneSample().
m_squelchOpen
bool FreqTracker::m_squelchOpen private
Definition at line 226 of file freqtracker.h.
Referenced by getSquelchOpen(), processOneSample(), and webapiFormatChannelReport().
m_threadedChannelizer
ThreadedBasebandSampleSink* FreqTracker::m_threadedChannelizer private
Definition at line 205 of file freqtracker.h.
Referenced by FreqTracker(), and ~FreqTracker().
m_tickCount
uint32_t FreqTracker::m_tickCount private
Definition at line 242 of file freqtracker.h.
Referenced by connectTimer(), and tick().
m_timer
const QTimer* FreqTracker::m_timer private
Definition at line 240 of file freqtracker.h.
Referenced by connectTimer(), disconnectTimer(), FreqTracker(), and ~FreqTracker().
m_timerConnected
bool FreqTracker::m_timerConnected private
Definition at line 241 of file freqtracker.h.
Referenced by connectTimer(), and disconnectTimer().
m_udpBlockSize
const int FreqTracker::m_udpBlockSize = 512 static private
Definition at line 236 of file freqtracker.h.
The documentation for this class was generated from the following files:
plugins/channelrx/freqtracker/freqtracker.h
plugins/channelrx/freqtracker/freqtracker.cpp