SDRAngel: SoapySDRInput::MsgConfigureSoapySDRInput Class Reference
SoapySDRInput::MsgConfigureSoapySDRInput Class Reference
#include <soapysdrinput.h>
Public Member Functions
const SoapySDRInputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureSoapySDRInput * create (const SoapySDRInputSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureSoapySDRInput (const SoapySDRInputSettings &settings, bool force)
Private Attributes
SoapySDRInputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 54 of file soapysdrinput.h.
Constructor & Destructor Documentation
MsgConfigureSoapySDRInput()
SoapySDRInput::MsgConfigureSoapySDRInput::MsgConfigureSoapySDRInput (const SoapySDRInputSettings & settings, bool force) inline private
Definition at line 70 of file soapysdrinput.h.
                                                                                      :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureSoapySDRInput* SoapySDRInput::MsgConfigureSoapySDRInput::create (const SoapySDRInputSettings & settings, bool force) inline static
Definition at line 61 of file soapysdrinput.h.
Referenced by SoapySDRInput::handleMessage(), SoapySDRInput::setCenterFrequency(), SoapySDRInputGui::updateHardware(), and SoapySDRInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureSoapySDRInput(settings, force);
         }
getForce()
bool SoapySDRInput::MsgConfigureSoapySDRInput::getForce () const inline
Definition at line 59 of file soapysdrinput.h.
Referenced by SoapySDRInput::handleMessage().
 { return m_force; }
getSettings()
const SoapySDRInputSettings& SoapySDRInput::MsgConfigureSoapySDRInput::getSettings () const inline
Definition at line 58 of file soapysdrinput.h.
Referenced by SoapySDRInputGui::handleMessage(), and SoapySDRInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool SoapySDRInput::MsgConfigureSoapySDRInput::m_force private
Definition at line 68 of file soapysdrinput.h.
m_settings
SoapySDRInputSettings SoapySDRInput::MsgConfigureSoapySDRInput::m_settings private
Definition at line 67 of file soapysdrinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/soapysdrinput/soapysdrinput.h