SDRAngel: DSPConfigureAudio Class Reference
DSPConfigureAudio Class Reference
#include <dspcommands.h>
Public Types
enum AudioType { AudioInput, AudioOutput }
Public Member Functions
DSPConfigureAudio (int sampleRate, AudioType audioType)
int getSampleRate () const
AudioType getAudioType () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Private Attributes
int m_sampleRate
AudioType m_autioType
Additional Inherited Members
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 375 of file dspcommands.h.
Member Enumeration Documentation
AudioType
enum DSPConfigureAudio::AudioType
Enumerator
AudioInput
AudioOutput
Definition at line 379 of file dspcommands.h.
     {
         AudioInput,
         AudioOutput
     };
Constructor & Destructor Documentation
DSPConfigureAudio()
DSPConfigureAudio::DSPConfigureAudio (int sampleRate, AudioType audioType) inline
Definition at line 385 of file dspcommands.h.
                                                            :
         m_sampleRate(sampleRate),
         m_autioType(audioType)
     { }
Member Function Documentation
getAudioType()
AudioType DSPConfigureAudio::getAudioType () const inline
Definition at line 391 of file dspcommands.h.
Referenced by AMMod::handleMessage(), NFMMod::handleMessage(), and SSBMod::handleMessage().
 { return m_autioType; }
getSampleRate()
int DSPConfigureAudio::getSampleRate () const inline
Definition at line 390 of file dspcommands.h.
Referenced by AMDemod::handleMessage(), WFMDemod::handleMessage(), DSDDemod::handleMessage(), SSBDemod::handleMessage(), NFMDemod::handleMessage(), BFMDemod::handleMessage(), FreeDVDemod::handleMessage(), AMMod::handleMessage(), WFMMod::handleMessage(), NFMMod::handleMessage(), SSBMod::handleMessage(), and FreeDVMod::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_autioType
AudioType DSPConfigureAudio::m_autioType private
Definition at line 395 of file dspcommands.h.
m_sampleRate
int DSPConfigureAudio::m_sampleRate private
Definition at line 394 of file dspcommands.h.
The documentation for this class was generated from the following file:
sdrbase/dsp/dspcommands.h