SDRAngel: DoubleBufferFIFO< T > Class Template Reference
DoubleBufferFIFO< T > Class Template Reference
#include <doublebufferfifo.h>
Public Member Functions
DoubleBufferFIFO (int size)
~DoubleBufferFIFO ()
void resize (int size)
void write (const T &element)
T & readBack (int delay)
void zeroBack (int delay)
Private Attributes
int m_size
T * m_data
int m_writeIndex
int m_currentIndex
Detailed Description
template<typename T>
class DoubleBufferFIFO< T >
Definition at line 23 of file doublebufferfifo.h.
Constructor & Destructor Documentation
DoubleBufferFIFO()
template<typename T> DoubleBufferFIFO< T >::DoubleBufferFIFO (int size) inline
Definition at line 26 of file doublebufferfifo.h.
                                : m_size(size), m_writeIndex(0), m_currentIndex(0)
     {
         m_data = new T[2*m_size];
     }
~DoubleBufferFIFO()
template<typename T> DoubleBufferFIFO< T >::~DoubleBufferFIFO () inline
Definition at line 31 of file doublebufferfifo.h.
     {
         delete[] m_data;
     }
Member Function Documentation
readBack()
template<typename T> T& DoubleBufferFIFO< T >::readBack (int delay) inline
Definition at line 58 of file doublebufferfifo.h.
Referenced by DSDDemod::feed(), AMDemod::processOneSample(), NFMDemod::processOneSample(), and SSBDemod::processOneSample().
     {
         if (delay > m_size) {
             delay = m_size;
         }
         return m_data[m_currentIndex + m_size - delay];
     }
resize()
template<typename T> void DoubleBufferFIFO< T >::resize (int size) inline
Definition at line 36 of file doublebufferfifo.h.
Referenced by AMDemod::applyAudioSampleRate().
     {
         delete[] m_data;
         m_size = size;
         m_data = new T[2*m_size];
         m_writeIndex = 0;
         m_currentIndex = 0;
     }
write()
template<typename T> void DoubleBufferFIFO< T >::write (const T & element) inline
Definition at line 45 of file doublebufferfifo.h.
Referenced by DSDDemod::feed(), AMDemod::processOneSample(), NFMDemod::processOneSample(), and SSBDemod::processOneSample().
     {
         m_data[m_writeIndex] = element;
         m_data[m_writeIndex+m_size] = element;
         m_currentIndex = m_writeIndex;
         if (m_writeIndex < m_size - 1) {
             m_writeIndex++;
         } else {
             m_writeIndex = 0;
         }
     }
zeroBack()
template<typename T> void DoubleBufferFIFO< T >::zeroBack (int delay) inline
Definition at line 67 of file doublebufferfifo.h.
Referenced by NFMDemod::processOneSample().
     {
         if (delay > m_size) {
             delay = m_size;
         }
         for (int i = 0; i < delay; i++) {
             m_data[m_currentIndex + m_size - i] = 0;
         }
     }
Member Data Documentation
m_currentIndex
template<typename T> int DoubleBufferFIFO< T >::m_currentIndex private
Definition at line 82 of file doublebufferfifo.h.
Referenced by DoubleBufferFIFO< Real >::readBack(), DoubleBufferFIFO< Real >::resize(), DoubleBufferFIFO< Real >::write(), and DoubleBufferFIFO< Real >::zeroBack().
m_data
template<typename T> T* DoubleBufferFIFO< T >::m_data private
Definition at line 80 of file doublebufferfifo.h.
Referenced by DoubleBufferFIFO< Real >::DoubleBufferFIFO(), DoubleBufferFIFO< Real >::readBack(), DoubleBufferFIFO< Real >::resize(), DoubleBufferFIFO< Real >::write(), DoubleBufferFIFO< Real >::zeroBack(), and DoubleBufferFIFO< Real >::~DoubleBufferFIFO().
m_size
template<typename T> int DoubleBufferFIFO< T >::m_size private
Definition at line 79 of file doublebufferfifo.h.
Referenced by DoubleBufferFIFO< Real >::DoubleBufferFIFO(), DoubleBufferFIFO< Real >::readBack(), DoubleBufferFIFO< Real >::resize(), DoubleBufferFIFO< Real >::write(), and DoubleBufferFIFO< Real >::zeroBack().
m_writeIndex
template<typename T> int DoubleBufferFIFO< T >::m_writeIndex private
Definition at line 81 of file doublebufferfifo.h.
Referenced by DoubleBufferFIFO< Real >::resize(), and DoubleBufferFIFO< Real >::write().
The documentation for this class was generated from the following file:
sdrbase/util/doublebufferfifo.h