SDRAngel: EditCommandDialog Class Reference
EditCommandDialog Class Reference
#include <editcommanddialog.h>
Inherits QDialog.
Public Member Functions
EditCommandDialog (const QStringList &groups, const QString &group, QWidget *parent=0)
~EditCommandDialog ()
QString getGroup () const
void setGroup (const QString &group)
QString getDescription () const
void setDescription (const QString &description)
QString getCommand () const
void setCommand (const QString &command)
QString getArguments () const
void setArguments (const QString &arguments)
Qt::Key getKey () const
Qt::KeyboardModifiers getKeyModifiers () const
void setKey (Qt::Key key, Qt::KeyboardModifiers modifiers)
bool getAssociateKey () const
void setAssociateKey (bool associate)
bool getRelease () const
void setRelease (bool release)
void toCommand (Command &command) const
void fromCommand (const Command &command)
Private Slots
void on_showFileDialog_clicked (bool checked)
void on_keyCapture_toggled (bool checked)
void commandKeyPressed (Qt::Key key, Qt::KeyboardModifiers keyModifiers, bool release)
Private Member Functions
void setKeyLabel ()
void setKeyAssociate ()
Private Attributes
Ui::EditCommandDialog * ui
Qt::Key m_key
Qt::KeyboardModifiers m_keyModifiers
CommandKeyReceiver * m_commandKeyReceiver
Detailed Description
Definition at line 33 of file editcommanddialog.h.
Constructor & Destructor Documentation
EditCommandDialog()
EditCommandDialog::EditCommandDialog (const QStringList & groups, const QString & group, QWidget * parent = 0) explicit
Definition at line 27 of file editcommanddialog.cpp.
References m_commandKeyReceiver, setKeyAssociate(), setKeyLabel(), and ui.
                                                                                                      :
     QDialog(parent),
     ui(new Ui::EditCommandDialog),
     m_key(static_cast<Qt::Key>(0))
 {
     ui->setupUi(this);
     ui->group->addItems(groups);
     ui->group->lineEdit()->setText(group);
     setKeyAssociate();
     setKeyLabel();
     m_commandKeyReceiver = new CommandKeyReceiver();
     this->installEventFilter(m_commandKeyReceiver);
 }
~EditCommandDialog()
EditCommandDialog::~EditCommandDialog ()
Definition at line 42 of file editcommanddialog.cpp.
References m_commandKeyReceiver, and ui.
 {
     m_commandKeyReceiver->deleteLater();
     delete ui;
 }
Member Function Documentation
commandKeyPressed
void EditCommandDialog::commandKeyPressed (Qt::Key key, Qt::KeyboardModifiers keyModifiers, bool release) private slot
Definition at line 229 of file editcommanddialog.cpp.
References m_key, m_keyModifiers, setKeyAssociate(), setKeyLabel(), and ui.
Referenced by on_keyCapture_toggled().
 {
     (void) release;
 //    qDebug("EditCommandDialog::commandKeyPressed: key: %x", m_key);
 //    qDebug("EditCommandDialog::commandKeyPressed: has modifiers: %x", QFlags<Qt::KeyboardModifier>::Int(keyModifiers));
     m_key = key;
     m_keyModifiers = keyModifiers;
     setKeyAssociate();
     setKeyLabel();
     ui->keyCapture->setChecked(false);
 }
fromCommand()
void EditCommandDialog::fromCommand (const Command & command)
Definition at line 184 of file editcommanddialog.cpp.
References Command::getArgString(), Command::getAssociateKey(), Command::getCommand(), Command::getDescription(), Command::getGroup(), Command::getKey(), Command::getKeyModifiers(), Command::getRelease(), m_key, m_keyModifiers, setKeyAssociate(), setKeyLabel(), and ui.
Referenced by MainWindow::on_commandEdit_clicked(), and MainWindow::on_commandNew_clicked().
 {
     ui->group->lineEdit()->setText(command.getGroup());
     ui->description->setText(command.getDescription());
     ui->command->setText(command.getCommand());
     ui->args->setText(command.getArgString());
     ui->keyAssociate->setChecked(command.getAssociateKey());
     m_key = command.getKey();
     m_keyModifiers = command.getKeyModifiers();
     setKeyAssociate();
     setKeyLabel();
     ui->keyRelease->setChecked(command.getRelease());
 }
getArguments()
QString EditCommandDialog::getArguments () const
Definition at line 78 of file editcommanddialog.cpp.
References ui.
 {
     return ui->args->text();
 }
getAssociateKey()
bool EditCommandDialog::getAssociateKey () const
Definition at line 106 of file editcommanddialog.cpp.
References ui.
 {
     return ui->keyAssociate->isChecked();
 }
getCommand()
QString EditCommandDialog::getCommand () const
Definition at line 68 of file editcommanddialog.cpp.
References ui.
 {
     return ui->command->text();
 }
getDescription()
QString EditCommandDialog::getDescription () const
Definition at line 53 of file editcommanddialog.cpp.
References ui.
 {
     return ui->description->text();
 }
getGroup()
QString EditCommandDialog::getGroup () const
Definition at line 48 of file editcommanddialog.cpp.
References ui.
 {
     return ui->group->lineEdit()->text();
 }
getKey()
Qt::Key EditCommandDialog::getKey () const
Definition at line 88 of file editcommanddialog.cpp.
References m_key.
 {
     return m_key;
 }
getKeyModifiers()
Qt::KeyboardModifiers EditCommandDialog::getKeyModifiers () const
Definition at line 93 of file editcommanddialog.cpp.
References m_keyModifiers.
 {
     return m_keyModifiers;
 }
getRelease()
bool EditCommandDialog::getRelease () const
Definition at line 116 of file editcommanddialog.cpp.
References ui.
 {
     return ui->keyRelease->isChecked();
 }
on_keyCapture_toggled
void EditCommandDialog::on_keyCapture_toggled (bool checked) private slot
Definition at line 154 of file editcommanddialog.cpp.
References commandKeyPressed(), and m_commandKeyReceiver.
 {
     if (checked)
     {
         setFocus();
         setFocusPolicy(Qt::StrongFocus);
         connect(m_commandKeyReceiver, SIGNAL(capturedKey(Qt::Key, Qt::KeyboardModifiers, bool)),
                         this, SLOT(commandKeyPressed(Qt::Key, Qt::KeyboardModifiers, bool)));
     }
     else
     {
         disconnect(m_commandKeyReceiver, SIGNAL(capturedKey(Qt::Key, Qt::KeyboardModifiers, bool)),
                         this, SLOT(commandKeyPressed(Qt::Key, Qt::KeyboardModifiers, bool)));
         setFocusPolicy(Qt::NoFocus);
         clearFocus();
     }
 }
on_showFileDialog_clicked
void EditCommandDialog::on_showFileDialog_clicked (bool checked) private slot
Definition at line 126 of file editcommanddialog.cpp.
References ui.
 {
     (void) checked;
     QString commandFileName = ui->command->text();
     QFileInfo commandFileInfo(commandFileName);
     QString commandFolderName = commandFileInfo.baseName();
     QFileInfo commandDirInfo(commandFolderName);
     QString dirStr;
     if (commandFileInfo.exists()) {
         dirStr = commandFileName;
     } else if (commandDirInfo.exists()) {
         dirStr = commandFolderName;
     } else {
         dirStr = ".";
     }
     QString fileName = QFileDialog::getOpenFileName(
             this,
             tr("Select command"),
             dirStr,
             tr("All (*);;Python (*.py);;Shell (*.sh *.bat);;Binary (*.bin *.exe)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "") {
         ui->command->setText(fileName);
     }
 }
setArguments()
void EditCommandDialog::setArguments (const QString & arguments)
Definition at line 83 of file editcommanddialog.cpp.
References ui.
 {
     ui->args->setText(arguments);
 }
setAssociateKey()
void EditCommandDialog::setAssociateKey (bool associate)
Definition at line 111 of file editcommanddialog.cpp.
References ui.
 {
     ui->keyAssociate->setChecked(release);
 }
setCommand()
void EditCommandDialog::setCommand (const QString & command)
Definition at line 73 of file editcommanddialog.cpp.
References ui.
 {
     ui->command->setText(command);
 }
setDescription()
void EditCommandDialog::setDescription (const QString & description)
Definition at line 63 of file editcommanddialog.cpp.
References ui.
 {
     ui->description->setText(description);
 }
setGroup()
void EditCommandDialog::setGroup (const QString & group)
Definition at line 58 of file editcommanddialog.cpp.
References ui.
 {
     ui->group->lineEdit()->setText(group);
 }
setKey()
void EditCommandDialog::setKey (Qt::Key key, Qt::KeyboardModifiers modifiers)
Definition at line 98 of file editcommanddialog.cpp.
References m_key, m_keyModifiers, setKeyAssociate(), and setKeyLabel().
 {
     m_key = key;
     m_keyModifiers = modifiers;
     setKeyAssociate();
     setKeyLabel();
 }
setKeyAssociate()
void EditCommandDialog::setKeyAssociate () private
Definition at line 216 of file editcommanddialog.cpp.
References m_key, and ui.
Referenced by commandKeyPressed(), EditCommandDialog(), fromCommand(), and setKey().
 {
     if (m_key == 0)
     {
         ui->keyAssociate->setChecked(false);
         ui->keyAssociate->setEnabled(false);
     }
     else
     {
         ui->keyAssociate->setEnabled(true);
     }
 }
setKeyLabel()
void EditCommandDialog::setKeyLabel () private
Definition at line 198 of file editcommanddialog.cpp.
References m_key, m_keyModifiers, and ui.
Referenced by commandKeyPressed(), EditCommandDialog(), fromCommand(), and setKey().
 {
     if (m_key == 0)
     {
         ui->keyLabel->setText("");
     }
     else if (m_keyModifiers != Qt::NoModifier)
     {
         QString altGrStr = m_keyModifiers & Qt::GroupSwitchModifier ? "Gr " : "";
         int maskedModifiers = (m_keyModifiers & 0x3FFFFFFF) + ((m_keyModifiers & 0x40000000)>>3);
         ui->keyLabel->setText(altGrStr + QKeySequence(maskedModifiers, m_key).toString());
     }
     else
     {
         ui->keyLabel->setText(QKeySequence(m_key).toString());
     }
 }
setRelease()
void EditCommandDialog::setRelease (bool release)
Definition at line 121 of file editcommanddialog.cpp.
References ui.
 {
     ui->keyRelease->setChecked(release);
 }
toCommand()
void EditCommandDialog::toCommand (Command & command) const
Definition at line 172 of file editcommanddialog.cpp.
References m_key, m_keyModifiers, Command::setArgString(), Command::setAssociateKey(), Command::setCommand(), Command::setDescription(), Command::setGroup(), Command::setKey(), Command::setKeyModifiers(), Command::setRelease(), and ui.
Referenced by MainWindow::on_commandNew_clicked().
 {
     command.setGroup(ui->group->currentText());
     command.setDescription(ui->description->text());
     command.setCommand(ui->command->text());
     command.setArgString(ui->args->text());
     command.setAssociateKey(ui->keyAssociate->isChecked());
     command.setKey(m_key);
     command.setKeyModifiers(m_keyModifiers);
     command.setRelease(ui->keyRelease->isChecked());
 }
Member Data Documentation
m_commandKeyReceiver
CommandKeyReceiver* EditCommandDialog::m_commandKeyReceiver private
Definition at line 63 of file editcommanddialog.h.
Referenced by EditCommandDialog(), on_keyCapture_toggled(), and ~EditCommandDialog().
m_key
Qt::Key EditCommandDialog::m_key private
Definition at line 61 of file editcommanddialog.h.
Referenced by commandKeyPressed(), fromCommand(), getKey(), setKey(), setKeyAssociate(), setKeyLabel(), and toCommand().
m_keyModifiers
Qt::KeyboardModifiers EditCommandDialog::m_keyModifiers private
Definition at line 62 of file editcommanddialog.h.
Referenced by commandKeyPressed(), fromCommand(), getKeyModifiers(), setKey(), setKeyLabel(), and toCommand().
ui
Ui::EditCommandDialog* EditCommandDialog::ui private
Definition at line 60 of file editcommanddialog.h.
Referenced by commandKeyPressed(), EditCommandDialog(), fromCommand(), getArguments(), getAssociateKey(), getCommand(), getDescription(), getGroup(), getRelease(), on_showFileDialog_clicked(), setArguments(), setAssociateKey(), setCommand(), setDescription(), setGroup(), setKeyAssociate(), setKeyLabel(), setRelease(), toCommand(), and ~EditCommandDialog().
The documentation for this class was generated from the following files:
sdrgui/gui/editcommanddialog.h
sdrgui/gui/editcommanddialog.cpp