SDRAngel: PluginAPI Class Reference
PluginAPI Class Reference
#include <pluginapi.h>
Inherits QObject.
Classes
struct ChannelRegistration
struct SamplingDeviceRegistration
< This is the device registration
Public Types
typedef QList< SamplingDeviceRegistration > SamplingDeviceRegistrations
typedef QList< ChannelRegistration > ChannelRegistrations
Public Member Functions
void registerRxChannel (const QString &channelIdURI, const QString &channelId, PluginInterface *plugin)
ChannelRegistrations * getRxChannelRegistrations ()
void registerTxChannel (const QString &channelIdURI, const QString &channelId, PluginInterface *plugin)
ChannelRegistrations * getTxChannelRegistrations ()
void registerSampleSource (const QString &sourceName, PluginInterface *plugin)
void registerSampleSink (const QString &sinkName, PluginInterface *plugin)
void registerSampleMIMO (const QString &sinkName, PluginInterface *plugin)
Protected Member Functions
PluginAPI (PluginManager *pluginManager)
~PluginAPI ()
Protected Attributes
PluginManager * m_pluginManager
Friends
class PluginManager
Detailed Description
Definition at line 16 of file pluginapi.h.
Member Typedef Documentation
ChannelRegistrations
typedef QList<ChannelRegistration> PluginAPI::ChannelRegistrations
Definition at line 44 of file pluginapi.h.
SamplingDeviceRegistrations
typedef QList<SamplingDeviceRegistration> PluginAPI::SamplingDeviceRegistrations
Definition at line 30 of file pluginapi.h.
Constructor & Destructor Documentation
PluginAPI()
PluginAPI::PluginAPI (PluginManager * pluginManager) protected
Definition at line 39 of file pluginapi.cpp.
                                                  :
     m_pluginManager(pluginManager)
 {
 }
~PluginAPI()
PluginAPI::~PluginAPI () protected
Definition at line 44 of file pluginapi.cpp.
 {
 }
Member Function Documentation
getRxChannelRegistrations()
PluginAPI::ChannelRegistrations * PluginAPI::getRxChannelRegistrations ()
Definition at line 14 of file pluginapi.cpp.
References PluginManager::getRxChannelRegistrations(), and m_pluginManager.
Referenced by DeviceSet::addRxChannel(), DeviceSet::loadRxChannelSettings(), and DeviceUISet::loadRxChannelSettings().
 {
     return m_pluginManager->getRxChannelRegistrations();
 }
getTxChannelRegistrations()
PluginAPI::ChannelRegistrations * PluginAPI::getTxChannelRegistrations ()
Definition at line 34 of file pluginapi.cpp.
References PluginManager::getTxChannelRegistrations(), and m_pluginManager.
Referenced by DeviceSet::addTxChannel(), DeviceSet::loadTxChannelSettings(), and DeviceUISet::loadTxChannelSettings().
 {
     return m_pluginManager->getTxChannelRegistrations();
 }
registerRxChannel()
void PluginAPI::registerRxChannel (const QString & channelIdURI, const QString & channelId, PluginInterface * plugin)
Definition at line 4 of file pluginapi.cpp.
References m_pluginManager, and PluginManager::registerRxChannel().
Referenced by LoRaPlugin::initPlugin(), NFMPlugin::initPlugin(), SSBPlugin::initPlugin(), WFMPlugin::initPlugin(), AMDemodPlugin::initPlugin(), BFMPlugin::initPlugin(), FreeDVPlugin::initPlugin(), FreqTrackerPlugin::initPlugin(), UDPSinkPlugin::initPlugin(), DSDDemodPlugin::initPlugin(), ChannelAnalyzerPlugin::initPlugin(), RemoteSinkPlugin::initPlugin(), LocalSinkPlugin::initPlugin(), ATVDemodPlugin::initPlugin(), and DATVDemodPlugin::initPlugin().
 {
     m_pluginManager->registerRxChannel(channelIdURI, channelId, plugin);
 }
registerSampleMIMO()
void PluginAPI::registerSampleMIMO (const QString & sinkName, PluginInterface * plugin)
Definition at line 29 of file pluginapi.cpp.
References m_pluginManager, and PluginManager::registerSampleMIMO().
Referenced by TestMIPlugin::initPlugin().
 {
     m_pluginManager->registerSampleMIMO(mimoName, plugin);
 }
registerSampleSink()
void PluginAPI::registerSampleSink (const QString & sinkName, PluginInterface * plugin)
Definition at line 24 of file pluginapi.cpp.
References m_pluginManager, and PluginManager::registerSampleSink().
Referenced by Bladerf1OutputPlugin::initPlugin(), XTRXOutputPlugin::initPlugin(), SoapySDROutputPlugin::initPlugin(), BladeRF2OutputPlugin::initPlugin(), PlutoSDROutputPlugin::initPlugin(), HackRFOutputPlugin::initPlugin(), LimeSDROutputPlugin::initPlugin(), LocalOutputPlugin::initPlugin(), RemoteOutputPlugin::initPlugin(), and FileSinkPlugin::initPlugin().
 {
     m_pluginManager->registerSampleSink(sinkName, plugin);
 }
registerSampleSource()
void PluginAPI::registerSampleSource (const QString & sourceName, PluginInterface * plugin)
Definition at line 9 of file pluginapi.cpp.
References m_pluginManager, and PluginManager::registerSampleSource().
Referenced by FCDProPlugin::initPlugin(), FCDProPlusPlugin::initPlugin(), RTLSDRPlugin::initPlugin(), AirspyPlugin::initPlugin(), HackRFInputPlugin::initPlugin(), FileInputPlugin::initPlugin(), SDRPlayPlugin::initPlugin(), TestSourcePlugin::initPlugin(), AirspyHFPlugin::initPlugin(), LimeSDRInputPlugin::initPlugin(), LocalInputPlugin::initPlugin(), PerseusPlugin::initPlugin(), PlutoSDRInputPlugin::initPlugin(), RemoteInputPlugin::initPlugin(), XTRXInputPlugin::initPlugin(), KiwiSDRPlugin::initPlugin(), Blderf1InputPlugin::initPlugin(), SoapySDRInputPlugin::initPlugin(), and Blderf2InputPlugin::initPlugin().
 {
     m_pluginManager->registerSampleSource(sourceName, plugin);
 }
registerTxChannel()
void PluginAPI::registerTxChannel (const QString & channelIdURI, const QString & channelId, PluginInterface * plugin)
Definition at line 19 of file pluginapi.cpp.
References m_pluginManager, and PluginManager::registerTxChannel().
Referenced by WFMModPlugin::initPlugin(), FileSourcePlugin::initPlugin(), ATVModPlugin::initPlugin(), RemoteSourcePlugin::initPlugin(), SSBModPlugin::initPlugin(), NFMModPlugin::initPlugin(), FreeDVModPlugin::initPlugin(), AMModPlugin::initPlugin(), UDPSourcePlugin::initPlugin(), and LocalSourcePlugin::initPlugin().
 {
     m_pluginManager->registerTxChannel(channelIdURI, channelId, plugin);
 }
Friends And Related Function Documentation
PluginManager
friend class PluginManager friend
Definition at line 69 of file pluginapi.h.
Member Data Documentation
m_pluginManager
PluginManager* PluginAPI::m_pluginManager protected
Definition at line 64 of file pluginapi.h.
Referenced by getRxChannelRegistrations(), getTxChannelRegistrations(), registerRxChannel(), registerSampleMIMO(), registerSampleSink(), registerSampleSource(), and registerTxChannel().
The documentation for this class was generated from the following files:
sdrbase/plugin/pluginapi.h
sdrbase/plugin/pluginapi.cpp