SDRAngel: DownChannelizer::MsgChannelizerNotification Class Reference
DownChannelizer::MsgChannelizerNotification Class Reference
#include <downchannelizer.h>
Public Member Functions
MsgChannelizerNotification (int samplerate, qint64 frequencyOffset)
int getSampleRate () const
qint64 getFrequencyOffset () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgChannelizerNotification * create (int samplerate, qint64 frequencyOffset)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Attributes
int m_sampleRate
qint64 m_frequencyOffset
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 37 of file downchannelizer.h.
Constructor & Destructor Documentation
MsgChannelizerNotification()
DownChannelizer::MsgChannelizerNotification::MsgChannelizerNotification (int samplerate, qint64 frequencyOffset) inline
Definition at line 41 of file downchannelizer.h.
                                                                            :
             Message(),
             m_sampleRate(samplerate),
             m_frequencyOffset(frequencyOffset)
         { }
Member Function Documentation
create()
static MsgChannelizerNotification* DownChannelizer::MsgChannelizerNotification::create (int samplerate, qint64 frequencyOffset) inline static
Definition at line 50 of file downchannelizer.h.
Referenced by DownChannelizer::applyConfiguration(), and DownChannelizer::applySetting().
         {
             return new MsgChannelizerNotification(samplerate, frequencyOffset);
         }
getFrequencyOffset()
qint64 DownChannelizer::MsgChannelizerNotification::getFrequencyOffset () const inline
Definition at line 48 of file downchannelizer.h.
Referenced by LoRaDemod::handleMessage(), AMDemod::handleMessage(), WFMDemod::handleMessage(), DSDDemod::handleMessage(), LocalSink::handleMessage(), UDPSink::handleMessage(), RemoteSink::handleMessage(), SSBDemod::handleMessage(), NFMDemod::handleMessage(), FreqTracker::handleMessage(), BFMDemod::handleMessage(), FreeDVDemod::handleMessage(), ChannelAnalyzer::handleMessage(), DATVDemod::handleMessage(), and ATVDemod::handleMessage().
 { return m_frequencyOffset; }
getSampleRate()
int DownChannelizer::MsgChannelizerNotification::getSampleRate () const inline
Definition at line 47 of file downchannelizer.h.
Referenced by LoRaDemod::handleMessage(), AMDemod::handleMessage(), WFMDemod::handleMessage(), DSDDemod::handleMessage(), LocalSink::handleMessage(), UDPSink::handleMessage(), RemoteSink::handleMessage(), SSBDemod::handleMessage(), NFMDemod::handleMessage(), FreqTracker::handleMessage(), BFMDemod::handleMessage(), FreeDVDemod::handleMessage(), ChannelAnalyzer::handleMessage(), DATVDemod::handleMessage(), and ATVDemod::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_frequencyOffset
qint64 DownChannelizer::MsgChannelizerNotification::m_frequencyOffset private
Definition at line 57 of file downchannelizer.h.
m_sampleRate
int DownChannelizer::MsgChannelizerNotification::m_sampleRate private
Definition at line 56 of file downchannelizer.h.
The documentation for this class was generated from the following file:
sdrbase/dsp/downchannelizer.h