SDRAngel: LimeSDROutput::MsgReportStreamInfo Class Reference
LimeSDROutput::MsgReportStreamInfo Class Reference
#include <limesdroutput.h>
Public Member Functions
bool getSuccess () const
bool getActive () const
uint32_t getFifoFilledCount () const
uint32_t getFifoSize () const
uint32_t getUnderrun () const
uint32_t getOverrun () const
uint32_t getDroppedPackets () const
float getLinkRate () const
uint64_t getTimestamp () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportStreamInfo * create (bool success, bool active, uint32_t fifoFilledCount, uint32_t fifoSize, uint32_t underrun, uint32_t overrun, uint32_t droppedPackets, float linkRate, uint64_t timestamp)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportStreamInfo (bool success, bool active, uint32_t fifoFilledCount, uint32_t fifoSize, uint32_t underrun, uint32_t overrun, uint32_t droppedPackets, float linkRate, uint64_t timestamp)
Private Attributes
bool m_success
bool m_active
Indicates whether the stream is currently active.
uint32_t m_fifoFilledCount
Number of samples in FIFO buffer.
uint32_t m_fifoSize
Size of FIFO buffer.
uint32_t m_underrun
FIFO underrun count.
uint32_t m_overrun
FIFO overrun count.
uint32_t m_droppedPackets
Number of dropped packets by HW.
float m_linkRate
Combined data rate of all stream of the same direction (TX or RX)
uint64_t m_timestamp
Current HW timestamp.
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 112 of file limesdroutput.h.
Constructor & Destructor Documentation
MsgReportStreamInfo()
LimeSDROutput::MsgReportStreamInfo::MsgReportStreamInfo (bool success, bool active, uint32_t fifoFilledCount, uint32_t fifoSize, uint32_t underrun, uint32_t overrun, uint32_t droppedPackets, float linkRate, uint64_t timestamp) inline private
Definition at line 163 of file limesdroutput.h.
References LimeSDROutput::deserialize(), LimeSDROutput::destroy(), LimeSDROutput::init(), LimeSDROutput::LimeSDROutput(), LimeSDROutput::serialize(), LimeSDROutput::start(), LimeSDROutput::stop(), and LimeSDROutput::~LimeSDROutput().
                   :
             Message(),
             m_success(success),
             m_active(active),
             m_fifoFilledCount(fifoFilledCount),
             m_fifoSize(fifoSize),
             m_underrun(underrun),
             m_overrun(overrun),
             m_droppedPackets(droppedPackets),
             m_linkRate(linkRate),
             m_timestamp(timestamp)
         { }
Member Function Documentation
create()
static MsgReportStreamInfo* LimeSDROutput::MsgReportStreamInfo::create (bool success, bool active, uint32_t fifoFilledCount, uint32_t fifoSize, uint32_t underrun, uint32_t overrun, uint32_t droppedPackets, float linkRate, uint64_t timestamp) inline static
Definition at line 126 of file limesdroutput.h.
Referenced by LimeSDROutput::handleMessage().
         {
             return new MsgReportStreamInfo(
                     success,
                     active,
                     fifoFilledCount,
                     fifoSize,
                     underrun,
                     overrun,
                     droppedPackets,
                     linkRate,
                     timestamp
                     );
         }
getActive()
bool LimeSDROutput::MsgReportStreamInfo::getActive () const inline
Definition at line 117 of file limesdroutput.h.
Referenced by LimeSDROutputGUI::handleMessage().
 { return m_active; }
getDroppedPackets()
uint32_t LimeSDROutput::MsgReportStreamInfo::getDroppedPackets () const inline
Definition at line 122 of file limesdroutput.h.
Referenced by LimeSDROutputGUI::handleMessage().
 { return m_droppedPackets; }
getFifoFilledCount()
uint32_t LimeSDROutput::MsgReportStreamInfo::getFifoFilledCount () const inline
Definition at line 118 of file limesdroutput.h.
Referenced by LimeSDROutputGUI::handleMessage().
 { return m_fifoFilledCount; }
getFifoSize()
uint32_t LimeSDROutput::MsgReportStreamInfo::getFifoSize () const inline
Definition at line 119 of file limesdroutput.h.
Referenced by LimeSDROutputGUI::handleMessage().
 { return m_fifoSize; }
getLinkRate()
float LimeSDROutput::MsgReportStreamInfo::getLinkRate () const inline
Definition at line 123 of file limesdroutput.h.
Referenced by LimeSDROutputGUI::handleMessage().
 { return m_linkRate; }
getOverrun()
uint32_t LimeSDROutput::MsgReportStreamInfo::getOverrun () const inline
Definition at line 121 of file limesdroutput.h.
Referenced by LimeSDROutputGUI::handleMessage().
 { return m_overrun; }
getSuccess()
bool LimeSDROutput::MsgReportStreamInfo::getSuccess () const inline
Definition at line 116 of file limesdroutput.h.
Referenced by LimeSDROutputGUI::handleMessage().
 { return m_success; }
getTimestamp()
uint64_t LimeSDROutput::MsgReportStreamInfo::getTimestamp () const inline
Definition at line 124 of file limesdroutput.h.
 { return m_timestamp; }
getUnderrun()
uint32_t LimeSDROutput::MsgReportStreamInfo::getUnderrun () const inline
Definition at line 120 of file limesdroutput.h.
Referenced by LimeSDROutputGUI::handleMessage().
 { return m_underrun; }
Member Data Documentation
m_active
bool LimeSDROutput::MsgReportStreamInfo::m_active private
Indicates whether the stream is currently active.
Definition at line 154 of file limesdroutput.h.
m_droppedPackets
uint32_t LimeSDROutput::MsgReportStreamInfo::m_droppedPackets private
Number of dropped packets by HW.
Definition at line 159 of file limesdroutput.h.
m_fifoFilledCount
uint32_t LimeSDROutput::MsgReportStreamInfo::m_fifoFilledCount private
Number of samples in FIFO buffer.
Definition at line 155 of file limesdroutput.h.
m_fifoSize
uint32_t LimeSDROutput::MsgReportStreamInfo::m_fifoSize private
Size of FIFO buffer.
Definition at line 156 of file limesdroutput.h.
m_linkRate
float LimeSDROutput::MsgReportStreamInfo::m_linkRate private
Combined data rate of all stream of the same direction (TX or RX)
Definition at line 160 of file limesdroutput.h.
m_overrun
uint32_t LimeSDROutput::MsgReportStreamInfo::m_overrun private
FIFO overrun count.
Definition at line 158 of file limesdroutput.h.
m_success
bool LimeSDROutput::MsgReportStreamInfo::m_success private
Definition at line 152 of file limesdroutput.h.
m_timestamp
uint64_t LimeSDROutput::MsgReportStreamInfo::m_timestamp private
Current HW timestamp.
Definition at line 161 of file limesdroutput.h.
m_underrun
uint32_t LimeSDROutput::MsgReportStreamInfo::m_underrun private
FIFO underrun count.
Definition at line 157 of file limesdroutput.h.
The documentation for this class was generated from the following file:
plugins/samplesink/limesdroutput/limesdroutput.h