SDRAngel: SoapySDRInputThread Class Reference
SoapySDRInputThread Class Reference
#include <soapysdrinputthread.h>
Inherits QThread.
Classes
struct Channel
Public Member Functions
SoapySDRInputThread (SoapySDR::Device *dev, unsigned int nbRxChannels, QObject *parent=0)
~SoapySDRInputThread ()
void startWork ()
void stopWork ()
bool isRunning () const
unsigned int getNbChannels () const
void setLog2Decimation (unsigned int channel, unsigned int log2_decim)
unsigned int getLog2Decimation (unsigned int channel) const
void setSampleRate (unsigned int sampleRate)
unsigned int getSampleRate () const
void setFcPos (unsigned int channel, int fcPos)
int getFcPos (unsigned int channel) const
void setFifo (unsigned int channel, SampleSinkFifo *sampleFifo)
SampleSinkFifo * getFifo (unsigned int channel)
Private Types
enum DecimatorType { Decimator8, Decimator12, Decimator16, DecimatorFloat }
Private Member Functions
void run ()
unsigned int getNbFifos ()
void callbackSI8 (const qint8 *buf, qint32 len, unsigned int channel=0)
void callbackSI12 (const qint16 *buf, qint32 len, unsigned int channel=0)
void callbackSI16 (const qint16 *buf, qint32 len, unsigned int channel=0)
void callbackSIF (const float *buf, qint32 len, unsigned int channel=0)
void callbackMI (std::vector< void *> &buffs, qint32 samplesPerChannel)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
SoapySDR::Device * m_dev
Channel * m_channels
Array of channels dynamically allocated for the given number of Rx channels.
unsigned int m_sampleRate
unsigned int m_nbChannels
DecimatorType m_decimatorType
Detailed Description
Definition at line 37 of file soapysdrinputthread.h.
Member Enumeration Documentation
DecimatorType
enum SoapySDRInputThread::DecimatorType private
Enumerator
Decimator8
Decimator12
Decimator16
DecimatorFloat
Definition at line 79 of file soapysdrinputthread.h.
     {
         Decimator8,
         Decimator12,
         Decimator16,
         DecimatorFloat
     };
Constructor & Destructor Documentation
SoapySDRInputThread()
SoapySDRInputThread::SoapySDRInputThread (SoapySDR::Device * dev, unsigned int nbRxChannels, QObject * parent = 0)
Definition at line 29 of file soapysdrinputthread.cpp.
References m_channels.
                                                                                                         :
     QThread(parent),
     m_running(false),
     m_dev(dev),
     m_sampleRate(0),
     m_nbChannels(nbRxChannels),
     m_decimatorType(DecimatorFloat)
 {
     qDebug("SoapySDRInputThread::SoapySDRInputThread");
     m_channels = new Channel[nbRxChannels];
 }
~SoapySDRInputThread()
SoapySDRInputThread::~SoapySDRInputThread ()
Definition at line 41 of file soapysdrinputthread.cpp.
References m_channels, m_running, and stopWork().
 {
     qDebug("SoapySDRInputThread::~SoapySDRInputThread");
     if (m_running) {
         stopWork();
     }
     delete[] m_channels;
 }
Member Function Documentation
callbackMI()
void SoapySDRInputThread::callbackMI (std::vector< void *> & buffs, qint32 samplesPerChannel) private
Definition at line 256 of file soapysdrinputthread.cpp.
References callbackSI12(), callbackSI16(), callbackSI8(), callbackSIF(), Decimator12, Decimator16, Decimator8, DecimatorFloat, m_decimatorType, and m_nbChannels.
Referenced by run().
 {
     for(unsigned int ichan = 0; ichan < m_nbChannels; ichan++)
     {
         switch (m_decimatorType)
         {
         case Decimator8:
             callbackSI8((const qint8*) buffs[ichan], samplesPerChannel, ichan);
             break;
         case Decimator12:
             callbackSI12((const qint16*) buffs[ichan], samplesPerChannel, ichan);
             break;
         case Decimator16:
             callbackSI16((const qint16*) buffs[ichan], samplesPerChannel, ichan);
             break;
         case DecimatorFloat:
         default:
             callbackSIF((const float*) buffs[ichan], samplesPerChannel, ichan);
         }
     }
 }
callbackSI12()
void SoapySDRInputThread::callbackSI12 (const qint16 * buf, qint32 len, unsigned int channel = 0) private
Definition at line 371 of file soapysdrinputthread.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup(), m_channels, SoapySDRInputThread::Channel::m_convertBuffer, SoapySDRInputThread::Channel::m_decimators12, SoapySDRInputThread::Channel::m_sampleFifo, and SampleSinkFifo::write().
Referenced by callbackMI(), and run().
 {
     SampleVector::iterator it = m_channels[channel].m_convertBuffer.begin();
     if (m_channels[channel].m_log2Decim == 0)
     {
         m_channels[channel].m_decimators12.decimate1(&it, buf, len);
     }
     else
     {
         if (m_channels[channel].m_fcPos == 0) // Infra
         {
             switch (m_channels[channel].m_log2Decim)
             {
             case 1:
                 m_channels[channel].m_decimators12.decimate2_inf(&it, buf, len);
                 break;
             case 2:
                 m_channels[channel].m_decimators12.decimate4_inf(&it, buf, len);
                 break;
             case 3:
                 m_channels[channel].m_decimators12.decimate8_inf(&it, buf, len);
                 break;
             case 4:
                 m_channels[channel].m_decimators12.decimate16_inf(&it, buf, len);
                 break;
             case 5:
                 m_channels[channel].m_decimators12.decimate32_inf(&it, buf, len);
                 break;
             case 6:
                 m_channels[channel].m_decimators12.decimate64_inf(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_channels[channel].m_fcPos == 1) // Supra
         {
             switch (m_channels[channel].m_log2Decim)
             {
             case 1:
                 m_channels[channel].m_decimators12.decimate2_sup(&it, buf, len);
                 break;
             case 2:
                 m_channels[channel].m_decimators12.decimate4_sup(&it, buf, len);
                 break;
             case 3:
                 m_channels[channel].m_decimators12.decimate8_sup(&it, buf, len);
                 break;
             case 4:
                 m_channels[channel].m_decimators12.decimate16_sup(&it, buf, len);
                 break;
             case 5:
                 m_channels[channel].m_decimators12.decimate32_sup(&it, buf, len);
                 break;
             case 6:
                 m_channels[channel].m_decimators12.decimate64_sup(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_channels[channel].m_fcPos == 2) // Center
         {
             switch (m_channels[channel].m_log2Decim)
             {
             case 1:
                 m_channels[channel].m_decimators12.decimate2_cen(&it, buf, len);
                 break;
             case 2:
                 m_channels[channel].m_decimators12.decimate4_cen(&it, buf, len);
                 break;
             case 3:
                 m_channels[channel].m_decimators12.decimate8_cen(&it, buf, len);
                 break;
             case 4:
                 m_channels[channel].m_decimators12.decimate16_cen(&it, buf, len);
                 break;
             case 5:
                 m_channels[channel].m_decimators12.decimate32_cen(&it, buf, len);
                 break;
             case 6:
                 m_channels[channel].m_decimators12.decimate64_cen(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
     }
     m_channels[channel].m_sampleFifo->write(m_channels[channel].m_convertBuffer.begin(), it);
 }
callbackSI16()
void SoapySDRInputThread::callbackSI16 (const qint16 * buf, qint32 len, unsigned int channel = 0) private
Definition at line 464 of file soapysdrinputthread.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup(), m_channels, SoapySDRInputThread::Channel::m_convertBuffer, SoapySDRInputThread::Channel::m_decimators16, SoapySDRInputThread::Channel::m_sampleFifo, and SampleSinkFifo::write().
Referenced by callbackMI(), and run().
 {
     SampleVector::iterator it = m_channels[channel].m_convertBuffer.begin();
     if (m_channels[channel].m_log2Decim == 0)
     {
         m_channels[channel].m_decimators16.decimate1(&it, buf, len);
     }
     else
     {
         if (m_channels[channel].m_fcPos == 0) // Infra
         {
             switch (m_channels[channel].m_log2Decim)
             {
             case 1:
                 m_channels[channel].m_decimators16.decimate2_inf(&it, buf, len);
                 break;
             case 2:
                 m_channels[channel].m_decimators16.decimate4_inf(&it, buf, len);
                 break;
             case 3:
                 m_channels[channel].m_decimators16.decimate8_inf(&it, buf, len);
                 break;
             case 4:
                 m_channels[channel].m_decimators16.decimate16_inf(&it, buf, len);
                 break;
             case 5:
                 m_channels[channel].m_decimators16.decimate32_inf(&it, buf, len);
                 break;
             case 6:
                 m_channels[channel].m_decimators16.decimate64_inf(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_channels[channel].m_fcPos == 1) // Supra
         {
             switch (m_channels[channel].m_log2Decim)
             {
             case 1:
                 m_channels[channel].m_decimators16.decimate2_sup(&it, buf, len);
                 break;
             case 2:
                 m_channels[channel].m_decimators16.decimate4_sup(&it, buf, len);
                 break;
             case 3:
                 m_channels[channel].m_decimators16.decimate8_sup(&it, buf, len);
                 break;
             case 4:
                 m_channels[channel].m_decimators16.decimate16_sup(&it, buf, len);
                 break;
             case 5:
                 m_channels[channel].m_decimators16.decimate32_sup(&it, buf, len);
                 break;
             case 6:
                 m_channels[channel].m_decimators16.decimate64_sup(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_channels[channel].m_fcPos == 2) // Center
         {
             switch (m_channels[channel].m_log2Decim)
             {
             case 1:
                 m_channels[channel].m_decimators16.decimate2_cen(&it, buf, len);
                 break;
             case 2:
                 m_channels[channel].m_decimators16.decimate4_cen(&it, buf, len);
                 break;
             case 3:
                 m_channels[channel].m_decimators16.decimate8_cen(&it, buf, len);
                 break;
             case 4:
                 m_channels[channel].m_decimators16.decimate16_cen(&it, buf, len);
                 break;
             case 5:
                 m_channels[channel].m_decimators16.decimate32_cen(&it, buf, len);
                 break;
             case 6:
                 m_channels[channel].m_decimators16.decimate64_cen(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
     }
     m_channels[channel].m_sampleFifo->write(m_channels[channel].m_convertBuffer.begin(), it);
 }
callbackSI8()
void SoapySDRInputThread::callbackSI8 (const qint8 * buf, qint32 len, unsigned int channel = 0) private
Definition at line 278 of file soapysdrinputthread.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup(), m_channels, SoapySDRInputThread::Channel::m_convertBuffer, SoapySDRInputThread::Channel::m_decimators8, SoapySDRInputThread::Channel::m_sampleFifo, and SampleSinkFifo::write().
Referenced by callbackMI(), and run().
 {
     SampleVector::iterator it = m_channels[channel].m_convertBuffer.begin();
     if (m_channels[channel].m_log2Decim == 0)
     {
         m_channels[channel].m_decimators8.decimate1(&it, buf, len);
     }
     else
     {
         if (m_channels[channel].m_fcPos == 0) // Infra
         {
             switch (m_channels[channel].m_log2Decim)
             {
             case 1:
                 m_channels[channel].m_decimators8.decimate2_inf(&it, buf, len);
                 break;
             case 2:
                 m_channels[channel].m_decimators8.decimate4_inf(&it, buf, len);
                 break;
             case 3:
                 m_channels[channel].m_decimators8.decimate8_inf(&it, buf, len);
                 break;
             case 4:
                 m_channels[channel].m_decimators8.decimate16_inf(&it, buf, len);
                 break;
             case 5:
                 m_channels[channel].m_decimators8.decimate32_inf(&it, buf, len);
                 break;
             case 6:
                 m_channels[channel].m_decimators8.decimate64_inf(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_channels[channel].m_fcPos == 1) // Supra
         {
             switch (m_channels[channel].m_log2Decim)
             {
             case 1:
                 m_channels[channel].m_decimators8.decimate2_sup(&it, buf, len);
                 break;
             case 2:
                 m_channels[channel].m_decimators8.decimate4_sup(&it, buf, len);
                 break;
             case 3:
                 m_channels[channel].m_decimators8.decimate8_sup(&it, buf, len);
                 break;
             case 4:
                 m_channels[channel].m_decimators8.decimate16_sup(&it, buf, len);
                 break;
             case 5:
                 m_channels[channel].m_decimators8.decimate32_sup(&it, buf, len);
                 break;
             case 6:
                 m_channels[channel].m_decimators8.decimate64_sup(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_channels[channel].m_fcPos == 2) // Center
         {
             switch (m_channels[channel].m_log2Decim)
             {
             case 1:
                 m_channels[channel].m_decimators8.decimate2_cen(&it, buf, len);
                 break;
             case 2:
                 m_channels[channel].m_decimators8.decimate4_cen(&it, buf, len);
                 break;
             case 3:
                 m_channels[channel].m_decimators8.decimate8_cen(&it, buf, len);
                 break;
             case 4:
                 m_channels[channel].m_decimators8.decimate16_cen(&it, buf, len);
                 break;
             case 5:
                 m_channels[channel].m_decimators8.decimate32_cen(&it, buf, len);
                 break;
             case 6:
                 m_channels[channel].m_decimators8.decimate64_cen(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
     }
     m_channels[channel].m_sampleFifo->write(m_channels[channel].m_convertBuffer.begin(), it);
 }
callbackSIF()
void SoapySDRInputThread::callbackSIF (const float * buf, qint32 len, unsigned int channel = 0) private
Definition at line 557 of file soapysdrinputthread.cpp.
References DecimatorsFI::decimate1(), DecimatorsFI::decimate16_cen(), DecimatorsFI::decimate16_inf(), DecimatorsFI::decimate16_sup(), DecimatorsFI::decimate2_cen(), DecimatorsFI::decimate2_inf(), DecimatorsFI::decimate2_sup(), DecimatorsFI::decimate32_cen(), DecimatorsFI::decimate32_inf(), DecimatorsFI::decimate32_sup(), DecimatorsFI::decimate4_cen(), DecimatorsFI::decimate4_inf(), DecimatorsFI::decimate4_sup(), DecimatorsFI::decimate64_cen(), DecimatorsFI::decimate64_inf(), DecimatorsFI::decimate64_sup(), DecimatorsFI::decimate8_cen(), DecimatorsFI::decimate8_inf(), DecimatorsFI::decimate8_sup(), m_channels, SoapySDRInputThread::Channel::m_convertBuffer, SoapySDRInputThread::Channel::m_decimatorsFloat, SoapySDRInputThread::Channel::m_sampleFifo, and SampleSinkFifo::write().
Referenced by callbackMI(), and run().
 {
     SampleVector::iterator it = m_channels[channel].m_convertBuffer.begin();
     if (m_channels[channel].m_log2Decim == 0)
     {
         m_channels[channel].m_decimatorsFloat.decimate1(&it, buf, len);
     }
     else
     {
         if (m_channels[channel].m_fcPos == 0) // Infra
         {
             switch (m_channels[channel].m_log2Decim)
             {
             case 1:
                 m_channels[channel].m_decimatorsFloat.decimate2_inf(&it, buf, len);
                 break;
             case 2:
                 m_channels[channel].m_decimatorsFloat.decimate4_inf(&it, buf, len);
                 break;
             case 3:
                 m_channels[channel].m_decimatorsFloat.decimate8_inf(&it, buf, len);
                 break;
             case 4:
                 m_channels[channel].m_decimatorsFloat.decimate16_inf(&it, buf, len);
                 break;
             case 5:
                 m_channels[channel].m_decimatorsFloat.decimate32_inf(&it, buf, len);
                 break;
             case 6:
                 m_channels[channel].m_decimatorsFloat.decimate64_inf(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_channels[channel].m_fcPos == 1) // Supra
         {
             switch (m_channels[channel].m_log2Decim)
             {
             case 1:
                 m_channels[channel].m_decimatorsFloat.decimate2_sup(&it, buf, len);
                 break;
             case 2:
                 m_channels[channel].m_decimatorsFloat.decimate4_sup(&it, buf, len);
                 break;
             case 3:
                 m_channels[channel].m_decimatorsFloat.decimate8_sup(&it, buf, len);
                 break;
             case 4:
                 m_channels[channel].m_decimatorsFloat.decimate16_sup(&it, buf, len);
                 break;
             case 5:
                 m_channels[channel].m_decimatorsFloat.decimate32_sup(&it, buf, len);
                 break;
             case 6:
                 m_channels[channel].m_decimatorsFloat.decimate64_sup(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_channels[channel].m_fcPos == 2) // Center
         {
             switch (m_channels[channel].m_log2Decim)
             {
             case 1:
                 m_channels[channel].m_decimatorsFloat.decimate2_cen(&it, buf, len);
                 break;
             case 2:
                 m_channels[channel].m_decimatorsFloat.decimate4_cen(&it, buf, len);
                 break;
             case 3:
                 m_channels[channel].m_decimatorsFloat.decimate8_cen(&it, buf, len);
                 break;
             case 4:
                 m_channels[channel].m_decimatorsFloat.decimate16_cen(&it, buf, len);
                 break;
             case 5:
                 m_channels[channel].m_decimatorsFloat.decimate32_cen(&it, buf, len);
                 break;
             case 6:
                 m_channels[channel].m_decimatorsFloat.decimate64_cen(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
     }
     m_channels[channel].m_sampleFifo->write(m_channels[channel].m_convertBuffer.begin(), it);
 }
getFcPos()
int SoapySDRInputThread::getFcPos (unsigned int channel) const
Definition at line 231 of file soapysdrinputthread.cpp.
References m_channels, SoapySDRInputThread::Channel::m_fcPos, and m_nbChannels.
Referenced by getSampleRate(), SoapySDRInput::start(), and SoapySDRInput::stop().
 {
     if (channel < m_nbChannels) {
         return m_channels[channel].m_fcPos;
     } else {
         return 0;
     }
 }
getFifo()
SampleSinkFifo * SoapySDRInputThread::getFifo (unsigned int channel)
Definition at line 247 of file soapysdrinputthread.cpp.
References m_channels, m_nbChannels, and SoapySDRInputThread::Channel::m_sampleFifo.
Referenced by getSampleRate(), SoapySDRInput::start(), and SoapySDRInput::stop().
 {
     if (channel < m_nbChannels) {
         return m_channels[channel].m_sampleFifo;
     } else {
         return 0;
     }
 }
getLog2Decimation()
unsigned int SoapySDRInputThread::getLog2Decimation (unsigned int channel) const
Definition at line 215 of file soapysdrinputthread.cpp.
References m_channels, SoapySDRInputThread::Channel::m_log2Decim, and m_nbChannels.
Referenced by getNbChannels(), SoapySDRInput::start(), and SoapySDRInput::stop().
 {
     if (channel < m_nbChannels) {
         return m_channels[channel].m_log2Decim;
     } else {
         return 0;
     }
 }
getNbChannels()
unsigned int SoapySDRInputThread::getNbChannels () const inline
Definition at line 47 of file soapysdrinputthread.h.
References getLog2Decimation(), m_nbChannels, and setLog2Decimation().
Referenced by SoapySDRInput::start(), and SoapySDRInput::stop().
 { return m_nbChannels; }
getNbFifos()
unsigned int SoapySDRInputThread::getNbFifos () private
Definition at line 194 of file soapysdrinputthread.cpp.
References i, m_channels, and m_nbChannels.
Referenced by run().
 {
     unsigned int fifoCount = 0;
     for (unsigned int i = 0; i < m_nbChannels; i++)
     {
         if (m_channels[i].m_sampleFifo) {
             fifoCount++;
         }
     }
     return fifoCount;
 }
getSampleRate()
unsigned int SoapySDRInputThread::getSampleRate () const inline
Definition at line 51 of file soapysdrinputthread.h.
References getFcPos(), getFifo(), m_sampleRate, setFcPos(), and setFifo().
 { return m_sampleRate; }
isRunning()
bool SoapySDRInputThread::isRunning () const inline
Definition at line 46 of file soapysdrinputthread.h.
References m_running.
Referenced by SoapySDRInput::applySettings().
 { return m_running; }
run()
void SoapySDRInputThread::run () private
Definition at line 78 of file soapysdrinputthread.cpp.
References callbackMI(), callbackSI12(), callbackSI16(), callbackSI8(), callbackSIF(), Decimator12, Decimator16, Decimator8, DecimatorFloat, getNbFifos(), i, m_channels, SoapySDRInputThread::Channel::m_convertBuffer, m_decimatorType, m_dev, m_nbChannels, m_running, m_sampleRate, and m_startWaiter.
 {
     m_running = true;
     m_startWaiter.wakeAll();
     unsigned int nbFifos = getNbFifos();
     if ((m_nbChannels > 0) && (nbFifos > 0))
     {
         // build channels list
         std::vector<std::size_t> channels(m_nbChannels);
         std::iota(channels.begin(), channels.end(), 0); // Fill with 0, 1, ..., m_nbChannels-1.
         //initialize the sample rate for all channels
         for (const auto &it : channels) {
             m_dev->setSampleRate(SOAPY_SDR_RX, it, m_sampleRate);
         }
         // Determine sample format to be used
         double fullScale(0.0);
         std::string format = m_dev->getNativeStreamFormat(SOAPY_SDR_RX, channels.front(), fullScale);
         qDebug("SoapySDRInputThread::run: format: %s fullScale: %f", format.c_str(), fullScale);
         if ((format == "CS8") && (fullScale == 128.0)) { // 8 bit signed - native
             m_decimatorType = Decimator8;
         } else if ((format == "CS16") && (fullScale == 2048.0)) { // 12 bit signed - native
             m_decimatorType = Decimator12;
         } else if ((format == "CS16") && (fullScale == 32768.0)) { // 16 bit signed - native
             m_decimatorType = Decimator16;
         } else { // for other types make a conversion to float
             m_decimatorType = DecimatorFloat;
             format = "CF32";
         }
         unsigned int elemSize = SoapySDR::formatToSize(format); // sample (I+Q) size in bytes
         SoapySDR::Stream *stream = m_dev->setupStream(SOAPY_SDR_RX, format, channels);
         //allocate buffers for the stream read/write
         const unsigned int numElems = m_dev->getStreamMTU(stream); // number of samples (I+Q)
         std::vector<std::vector<char>> buffMem(m_nbChannels, std::vector<char>(elemSize*numElems));
         std::vector<void *> buffs(m_nbChannels);
         for (std::size_t i = 0; i < m_nbChannels; i++) {
             buffs[i] = buffMem[i].data();
         }
         for (unsigned int i = 0; i < m_nbChannels; i++) {
             m_channels[i].m_convertBuffer.resize(numElems, Sample{0,0});
         }
         m_dev->activateStream(stream);
         int flags(0);
         long long timeNs(0);
         float blockTime = ((float) numElems) / (m_sampleRate <= 0 ? 1024000 : m_sampleRate);
         long initialTtimeoutUs = 10000000 * blockTime; // 10 times the block time
         long timeoutUs = initialTtimeoutUs < 250000 ? 250000 : initialTtimeoutUs; // 250ms minimum
         qDebug("SoapySDRInputThread::run: numElems: %u elemSize: %u initialTtimeoutUs: %ld timeoutUs: %ld",
                 numElems, elemSize, initialTtimeoutUs, timeoutUs);
         qDebug("SoapySDRInputThread::run: start running loop");
         while (m_running)
         {
             int ret = m_dev->readStream(stream, buffs.data(), numElems, flags, timeNs, timeoutUs);
             if (ret == SOAPY_SDR_TIMEOUT)
             {
                 qWarning("SoapySDRInputThread::run: timeout: flags: %d timeNs: %lld timeoutUs: %ld", flags, timeNs, timeoutUs);
             }
             else if (ret == SOAPY_SDR_OVERFLOW)
             {
                 qWarning("SoapySDRInputThread::run: overflow: flags: %d timeNs: %lld timeoutUs: %ld", flags, timeNs, timeoutUs);
             }
             else if (ret < 0)
             {
                 qCritical("SoapySDRInputThread::run: Unexpected read stream error: %s", SoapySDR::errToStr(ret));
                 break;
             }
             if (m_nbChannels > 1)
             {
                 callbackMI(buffs, numElems*2); // size given in number of I or Q samples (2 items per sample)
             }
             else
             {
                 switch (m_decimatorType)
                 {
                 case Decimator8:
                     callbackSI8((const qint8*) buffs[0], numElems*2);
                     break;
                 case Decimator12:
                     callbackSI12((const qint16*) buffs[0], numElems*2);
                     break;
                 case Decimator16:
                     callbackSI16((const qint16*) buffs[0], numElems*2);
                     break;
                 case DecimatorFloat:
                 default:
                     callbackSIF((const float*) buffs[0], numElems*2);
                 }
             }
         }
         qDebug("SoapySDRInputThread::run: stop running loop");
         m_dev->deactivateStream(stream);
         m_dev->closeStream(stream);
     }
     else
     {
         qWarning("SoapySDRInputThread::run: no channels or FIFO allocated. Aborting");
     }
     m_running = false;
 }
setFcPos()
void SoapySDRInputThread::setFcPos (unsigned int channel, int fcPos)
Definition at line 224 of file soapysdrinputthread.cpp.
References m_channels, SoapySDRInputThread::Channel::m_fcPos, and m_nbChannels.
Referenced by SoapySDRInput::applySettings(), getSampleRate(), SoapySDRInput::start(), and SoapySDRInput::stop().
 {
     if (channel < m_nbChannels) {
         m_channels[channel].m_fcPos = fcPos;
     }
 }
setFifo()
void SoapySDRInputThread::setFifo (unsigned int channel, SampleSinkFifo * sampleFifo)
Definition at line 240 of file soapysdrinputthread.cpp.
References m_channels, m_nbChannels, and SoapySDRInputThread::Channel::m_sampleFifo.
Referenced by getSampleRate(), SoapySDRInput::start(), and SoapySDRInput::stop().
 {
     if (channel < m_nbChannels) {
         m_channels[channel].m_sampleFifo = sampleFifo;
     }
 }
setLog2Decimation()
void SoapySDRInputThread::setLog2Decimation (unsigned int channel, unsigned int log2_decim)
Definition at line 208 of file soapysdrinputthread.cpp.
References m_channels, SoapySDRInputThread::Channel::m_log2Decim, and m_nbChannels.
Referenced by SoapySDRInput::applySettings(), getNbChannels(), SoapySDRInput::start(), and SoapySDRInput::stop().
 {
     if (channel < m_nbChannels) {
         m_channels[channel].m_log2Decim = log2_decim;
     }
 }
setSampleRate()
void SoapySDRInputThread::setSampleRate (unsigned int sampleRate) inline
Definition at line 50 of file soapysdrinputthread.h.
References m_sampleRate.
Referenced by SoapySDRInput::applySettings(), and SoapySDRInput::start().
 { m_sampleRate = sampleRate; }
startWork()
void SoapySDRInputThread::startWork ()
Definition at line 52 of file soapysdrinputthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by SoapySDRInput::applySettings(), SoapySDRInput::start(), and SoapySDRInput::stop().
 {
     if (m_running) {
         return;
     }
     m_startWaitMutex.lock();
     start();
     while(!m_running) {
         m_startWaiter.wait(&m_startWaitMutex, 100);
     }
     m_startWaitMutex.unlock();
 }
stopWork()
void SoapySDRInputThread::stopWork ()
Definition at line 68 of file soapysdrinputthread.cpp.
References m_running.
Referenced by SoapySDRInput::applySettings(), SoapySDRInput::start(), SoapySDRInput::stop(), and ~SoapySDRInputThread().
 {
     if (!m_running) {
         return;
     }
     m_running = false;
     wait();
 }
Member Data Documentation
m_channels
Channel* SoapySDRInputThread::m_channels private
Array of channels dynamically allocated for the given number of Rx channels.
Definition at line 92 of file soapysdrinputthread.h.
Referenced by callbackSI12(), callbackSI16(), callbackSI8(), callbackSIF(), getFcPos(), getFifo(), getLog2Decimation(), getNbFifos(), run(), setFcPos(), setFifo(), setLog2Decimation(), SoapySDRInputThread(), and ~SoapySDRInputThread().
m_decimatorType
DecimatorType SoapySDRInputThread::m_decimatorType private
Definition at line 95 of file soapysdrinputthread.h.
Referenced by callbackMI(), and run().
m_dev
SoapySDR::Device* SoapySDRInputThread::m_dev private
Definition at line 90 of file soapysdrinputthread.h.
Referenced by run().
m_nbChannels
unsigned int SoapySDRInputThread::m_nbChannels private
Definition at line 94 of file soapysdrinputthread.h.
Referenced by callbackMI(), getFcPos(), getFifo(), getLog2Decimation(), getNbChannels(), getNbFifos(), run(), setFcPos(), setFifo(), and setLog2Decimation().
m_running
bool SoapySDRInputThread::m_running private
Definition at line 89 of file soapysdrinputthread.h.
Referenced by isRunning(), run(), startWork(), stopWork(), and ~SoapySDRInputThread().
m_sampleRate
unsigned int SoapySDRInputThread::m_sampleRate private
Definition at line 93 of file soapysdrinputthread.h.
Referenced by getSampleRate(), run(), and setSampleRate().
m_startWaiter
QWaitCondition SoapySDRInputThread::m_startWaiter private
Definition at line 88 of file soapysdrinputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex SoapySDRInputThread::m_startWaitMutex private
Definition at line 87 of file soapysdrinputthread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/samplesource/soapysdrinput/soapysdrinputthread.h
plugins/samplesource/soapysdrinput/soapysdrinputthread.cpp