SDRAngel: qtwebapp::HttpRequest Class Reference
qtwebapp::HttpRequest Class Reference
#include <httprequest.h>
Public Types
enum RequestStatus {
waitForRequest, waitForHeader, waitForBody, complete,
abort
}
Public Member Functions
HttpRequest (QSettings *settings)
HttpRequest (const HttpListenerSettings *settings)
virtual ~HttpRequest ()
void readFromSocket (QTcpSocket *socket)
RequestStatus getStatus () const
QByteArray getMethod () const
QByteArray getPath () const
const QByteArray & getRawPath () const
QByteArray getVersion () const
QByteArray getHeader (const QByteArray &name) const
QList< QByteArray > getHeaders (const QByteArray &name) const
QMultiMap< QByteArray, QByteArray > getHeaderMap () const
QByteArray getParameter (const QByteArray &name) const
QList< QByteArray > getParameters (const QByteArray &name) const
QMultiMap< QByteArray, QByteArray > getParameterMap () const
QByteArray getBody () const
QTemporaryFile * getUploadedFile (const QByteArray fieldName) const
QByteArray getCookie (const QByteArray &name) const
QMap< QByteArray, QByteArray > & getCookieMap ()
QHostAddress getPeerAddress () const
Static Public Member Functions
static QByteArray urlDecode (const QByteArray source)
Private Member Functions
void parseMultiPartFile ()
void readRequest (QTcpSocket *socket)
void readHeader (QTcpSocket *socket)
void readBody (QTcpSocket *socket)
void decodeRequestParams ()
void extractCookies ()
Private Attributes
QMultiMap< QByteArray, QByteArray > headers
QMultiMap< QByteArray, QByteArray > parameters
QMap< QByteArray, QTemporaryFile * > uploadedFiles
QMap< QByteArray, QByteArray > cookies
QByteArray bodyData
QByteArray method
QByteArray path
QByteArray version
RequestStatus status
QHostAddress peerAddress
int maxSize
int maxMultiPartSize
int currentSize
int expectedBodySize
QByteArray currentHeader
QByteArray boundary
QTemporaryFile * tempFile
QByteArray lineBuffer
bool useQtSettings
Friends
class HttpSessionStore
Detailed Description
This object represents a single HTTP request. It reads the request from a TCP socket and provides getters for the individual parts of the request.
The follwing config settings are required:
maxRequestSize=16000
maxMultiPartSize=1000000
MaxRequestSize is the maximum size of a HTTP request. In case of multipart/form-data requests (also known as file-upload), the maximum size of the body must not exceed maxMultiPartSize. The body is always a little larger than the file itself.
Definition at line 41 of file httprequest.h.
Member Enumeration Documentation
RequestStatus
enum qtwebapp::HttpRequest::RequestStatus
Values for getStatus()
Enumerator
waitForRequest
waitForHeader
waitForBody
complete
abort
Definition at line 48 of file httprequest.h.
 {waitForRequest, waitForHeader, waitForBody, complete, abort};
Constructor & Destructor Documentation
HttpRequest() [1/2]
HttpRequest::HttpRequest (QSettings * settings)
Constructor.
Parameters
settings Configuration settings
Definition at line 15 of file httprequest.cpp.
References currentSize, expectedBodySize, maxMultiPartSize, maxSize, status, tempFile, and waitForRequest.
                                             :
         useQtSettings(true)
 {
     Q_ASSERT(settings != 0);
     status=waitForRequest;
     currentSize=0;
     expectedBodySize=0;
     maxSize=settings->value("maxRequestSize","16000").toInt();
     maxMultiPartSize=settings->value("maxMultiPartSize","1000000").toInt();
     tempFile=0;
 }
HttpRequest() [2/2]
HttpRequest::HttpRequest (const HttpListenerSettings * settings)
Constructor.
Parameters
settings Configuration settings as a structure
Definition at line 27 of file httprequest.cpp.
References currentSize, expectedBodySize, qtwebapp::HttpListenerSettings::maxMultiPartSize, maxMultiPartSize, qtwebapp::HttpListenerSettings::maxRequestSize, maxSize, status, tempFile, and waitForRequest.
                                                              :
         useQtSettings(false)
 {
     Q_ASSERT(settings != 0);
     status=waitForRequest;
     currentSize=0;
     expectedBodySize=0;
     maxSize=settings->maxRequestSize;
     maxMultiPartSize=settings->maxMultiPartSize;
     tempFile=0;
 }
~HttpRequest()
HttpRequest::~HttpRequest () virtual
Destructor.
Definition at line 542 of file httprequest.cpp.
References tempFile, and uploadedFiles.
 {
     foreach(QByteArray key, uploadedFiles.keys())
     {
         QTemporaryFile* file=uploadedFiles.value(key);
         if (file->isOpen())
         {
             file->close();
         }
         delete file;
     }
     if (tempFile != NULL)
     {
         if (tempFile->isOpen())
         {
             tempFile->close();
         }
         delete tempFile;
     }
 }
Member Function Documentation
decodeRequestParams()
void HttpRequest::decodeRequestParams () private
Sub-procedure of readFromSocket(), extract and decode request parameters.
Definition at line 228 of file httprequest.cpp.
References bodyData, headers, parameters, path, and urlDecode().
Referenced by readFromSocket().
 {
     #ifdef SUPERVERBOSE
         qDebug("HttpRequest::decodeRequestParams: extract and decode request parameters");
     #endif
     // Get URL parameters
     QByteArray rawParameters;
     int questionMark=path.indexOf('?');
     if (questionMark>=0)
     {
         rawParameters=path.mid(questionMark+1);
         path=path.left(questionMark);
     }
     // Get request body parameters
     QByteArray contentType=headers.value("content-type");
     if (!bodyData.isEmpty() && (contentType.isEmpty() || contentType.startsWith("application/x-www-form-urlencoded")))
     {
         if (!rawParameters.isEmpty())
         {
             rawParameters.append('&');
             rawParameters.append(bodyData);
         }
         else
         {
             rawParameters=bodyData;
         }
     }
     // Split the parameters into pairs of value and name
     QList<QByteArray> list=rawParameters.split('&');
     foreach (QByteArray part, list)
     {
         int equalsChar=part.indexOf('=');
         if (equalsChar>=0)
         {
             QByteArray name=part.left(equalsChar).trimmed();
             QByteArray value=part.mid(equalsChar+1).trimmed();
             parameters.insert(urlDecode(name),urlDecode(value));
         }
         else if (!part.isEmpty())
         {
             // Name without value
             parameters.insert(urlDecode(part),"");
         }
     }
 }
extractCookies()
void HttpRequest::extractCookies () private
Sub-procedure of readFromSocket(), extract cookies from headers
Definition at line 274 of file httprequest.cpp.
References cookies, headers, and qtwebapp::HttpCookie::splitCSV().
Referenced by readFromSocket().
 {
     #ifdef SUPERVERBOSE
         qDebug("HttpRequest::extractCookies");
     #endif
     foreach(QByteArray cookieStr, headers.values("cookie"))
     {
         QList<QByteArray> list=HttpCookie::splitCSV(cookieStr);
         foreach(QByteArray part, list)
         {
             #ifdef SUPERVERBOSE
                 qDebug("HttpRequest::extractCookies: found cookie %s",part.data());
             #endif                // Split the part into name and value
             QByteArray name;
             QByteArray value;
             int posi=part.indexOf('=');
             if (posi)
             {
                 name=part.left(posi).trimmed();
                 value=part.mid(posi+1).trimmed();
             }
             else
             {
                 name=part.trimmed();
                 value="";
             }
             cookies.insert(name,value);
         }
     }
     headers.remove("cookie");
 }
getBody()
QByteArray HttpRequest::getBody () const
Get the HTTP request body.
Definition at line 396 of file httprequest.cpp.
References bodyData.
Referenced by WebAPIRequestMapper::devicesetChannelService(), WebAPIRequestMapper::devicesetChannelSettingsService(), WebAPIRequestMapper::devicesetDeviceService(), WebAPIRequestMapper::devicesetDeviceSettingsService(), WebAPIRequestMapper::instanceAMBEDevicesService(), WebAPIRequestMapper::instanceAudioInputParametersService(), WebAPIRequestMapper::instanceAudioOutputParametersService(), WebAPIRequestMapper::instanceLocationService(), WebAPIRequestMapper::instanceLoggingService(), WebAPIRequestMapper::instancePresetFileService(), and WebAPIRequestMapper::instancePresetService().
 {
     return bodyData;
 }
getCookie()
QByteArray HttpRequest::getCookie (const QByteArray & name) const
Get the value of a cookie.
Parameters
name Name of the cookie
Definition at line 568 of file httprequest.cpp.
References cookies.
Referenced by qtwebapp::HttpSessionStore::getSessionId().
 {
     return cookies.value(name);
 }
getCookieMap()
QMap< QByteArray, QByteArray > & HttpRequest::getCookieMap ()
Get all cookies.
Get the map of cookies
Definition at line 574 of file httprequest.cpp.
References cookies.
 {
     return cookies;
 }
getHeader()
QByteArray HttpRequest::getHeader (const QByteArray & name) const
Get the value of a HTTP request header.
Parameters
name Name of the header, not case-senitive.
Returns
If the header occurs multiple times, only the last one is returned.
Definition at line 366 of file httprequest.cpp.
References headers.
Referenced by qtwebapp::HttpConnectionHandler::read().
 {
     return headers.value(name.toLower());
 }
getHeaderMap()
QMultiMap< QByteArray, QByteArray > HttpRequest::getHeaderMap () const
Get all HTTP request headers. Note that the header names are returned in lower-case.
Definition at line 376 of file httprequest.cpp.
References headers.
 {
     return headers;
 }
getHeaders()
QList< QByteArray > HttpRequest::getHeaders (const QByteArray & name) const
Get the values of a HTTP request header.
Parameters
name Name of the header, not case-senitive.
Definition at line 371 of file httprequest.cpp.
References headers.
 {
     return headers.values(name.toLower());
 }
getMethod()
QByteArray HttpRequest::getMethod () const
Get the method of the HTTP request (e.g. "GET")
Definition at line 342 of file httprequest.cpp.
References method.
Referenced by WebAPIRequestMapper::devicesetChannelIndexService(), WebAPIRequestMapper::devicesetChannelReportService(), WebAPIRequestMapper::devicesetChannelService(), WebAPIRequestMapper::devicesetChannelSettingsService(), WebAPIRequestMapper::devicesetChannelsReportService(), WebAPIRequestMapper::devicesetDeviceReportService(), WebAPIRequestMapper::devicesetDeviceRunService(), WebAPIRequestMapper::devicesetDeviceService(), WebAPIRequestMapper::devicesetDeviceSettingsService(), WebAPIRequestMapper::devicesetFocusService(), WebAPIRequestMapper::devicesetService(), WebAPIRequestMapper::instanceAMBEDevicesService(), WebAPIRequestMapper::instanceAMBESerialService(), WebAPIRequestMapper::instanceAudioInputCleanupService(), WebAPIRequestMapper::instanceAudioInputParametersService(), WebAPIRequestMapper::instanceAudioOutputCleanupService(), WebAPIRequestMapper::instanceAudioOutputParametersService(), WebAPIRequestMapper::instanceAudioService(), WebAPIRequestMapper::instanceChannelsService(), WebAPIRequestMapper::instanceConfigService(), WebAPIRequestMapper::instanceDeviceSetService(), WebAPIRequestMapper::instanceDeviceSetsService(), WebAPIRequestMapper::instanceDevicesService(), WebAPIRequestMapper::instanceLocationService(), WebAPIRequestMapper::instanceLoggingService(), WebAPIRequestMapper::instancePresetFileService(), WebAPIRequestMapper::instancePresetService(), WebAPIRequestMapper::instancePresetsService(), WebAPIRequestMapper::instanceSummaryService(), qtwebapp::HttpConnectionHandler::read(), WebAPIRequestMapper::service(), and qtwebapp::HttpRequestHandler::service().
 {
     return method;
 }
getParameter()
QByteArray HttpRequest::getParameter (const QByteArray & name) const
Get the value of a HTTP request parameter.
Parameters
name Name of the parameter, case-sensitive.
Returns
If the parameter occurs multiple times, only the last one is returned.
Definition at line 381 of file httprequest.cpp.
References parameters.
Referenced by WebAPIRequestMapper::instanceChannelsService(), WebAPIRequestMapper::instanceDeviceSetService(), and WebAPIRequestMapper::instanceDevicesService().
 {
     return parameters.value(name);
 }
getParameterMap()
QMultiMap< QByteArray, QByteArray > HttpRequest::getParameterMap () const
Get all HTTP request parameters.
Definition at line 391 of file httprequest.cpp.
References parameters.
 {
     return parameters;
 }
getParameters()
QList< QByteArray > HttpRequest::getParameters (const QByteArray & name) const
Get the values of a HTTP request parameter.
Parameters
name Name of the parameter, case-sensitive.
Definition at line 386 of file httprequest.cpp.
References parameters.
 {
     return parameters.values(name);
 }
getPath()
QByteArray HttpRequest::getPath () const
Get the decoded path of the HTPP request (e.g. "/index.html")
Definition at line 348 of file httprequest.cpp.
References path, and urlDecode().
Referenced by qtwebapp::HttpConnectionHandler::read(), WebAPIRequestMapper::service(), qtwebapp::HttpRequestHandler::service(), and qtwebapp::StaticFileController::service().
 {
     return urlDecode(path);
 }
getPeerAddress()
QHostAddress HttpRequest::getPeerAddress () const
Get the address of the connected client. Note that multiple clients may have the same IP address, if they share an internet connection (which is very common).
Definition at line 584 of file httprequest.cpp.
References peerAddress.
Referenced by qtwebapp::HttpConnectionHandler::read().
 {
     return peerAddress;
 }
getRawPath()
const QByteArray & HttpRequest::getRawPath () const
Get the raw path of the HTTP request (e.g. "/file%20with%20spaces.html")
Definition at line 354 of file httprequest.cpp.
References path.
 {
     return path;
 }
getStatus()
HttpRequest::RequestStatus HttpRequest::getStatus () const
Get the status of this reqeust.
See also
RequestStatus
Definition at line 336 of file httprequest.cpp.
References status.
Referenced by qtwebapp::HttpConnectionHandler::read().
 {
     return status;
 }
getUploadedFile()
QTemporaryFile * HttpRequest::getUploadedFile (const QByteArray fieldName) const
Get an uploaded file. The file is already open. It will be closed and deleted by the destructor of this HttpRequest object (after processing the request).
For uploaded files, the method getParameters() returns the original fileName as provided by the calling web browser.
Definition at line 563 of file httprequest.cpp.
References uploadedFiles.
 {
     return uploadedFiles.value(fieldName);
 }
getVersion()
QByteArray HttpRequest::getVersion () const
Get the version of the HTPP request (e.g. "HTTP/1.1")
Definition at line 360 of file httprequest.cpp.
References version.
Referenced by qtwebapp::HttpConnectionHandler::read(), and qtwebapp::HttpRequestHandler::service().
 {
     return version;
 }
parseMultiPartFile()
void HttpRequest::parseMultiPartFile () private
Parse the multipart body, that has been stored in the temp file.
Definition at line 420 of file httprequest.cpp.
References boundary, currentSize, parameters, tempFile, and uploadedFiles.
Referenced by readBody().
 {
     qDebug("HttpRequest::parseMultiPartFile: parsing multipart temp file");
     tempFile->seek(0);
     bool finished=false;
     while (!tempFile->atEnd() && !finished && !tempFile->error())
     {
         #ifdef SUPERVERBOSE
             qDebug("HttpRequest::parseMultiPartFile: reading multpart headers");
         #endif
         QByteArray fieldName;
         QByteArray fileName;
         while (!tempFile->atEnd() && !finished && !tempFile->error())
         {
             QByteArray line=tempFile->readLine(65536).trimmed();
             if (line.startsWith("Content-Disposition:"))
             {
                 if (line.contains("form-data"))
                 {
                     int start=line.indexOf(" name=\"");
                     int end=line.indexOf("\"",start+7);
                     if (start>=0 && end>=start)
                     {
                         fieldName=line.mid(start+7,end-start-7);
                     }
                     start=line.indexOf(" filename=\"");
                     end=line.indexOf("\"",start+11);
                     if (start>=0 && end>=start)
                     {
                         fileName=line.mid(start+11,end-start-11);
                     }
                     #ifdef SUPERVERBOSE
                         qDebug("HttpRequest::parseMultiPartFile: multipart field=%s, filename=%s",fieldName.data(),fileName.data());
                     #endif
                 }
                 else
                 {
                     qDebug("HttpRequest::parseMultiPartFile: ignoring unsupported content part %s",line.data());
                 }
             }
             else if (line.isEmpty())
             {
                 break;
             }
         }
         #ifdef SUPERVERBOSE
             qDebug("HttpRequest::parseMultiPartFile: reading multpart data");
         #endif
         QTemporaryFile* uploadedFile=0;
         QByteArray fieldValue;
         while (!tempFile->atEnd() && !finished && !tempFile->error())
         {
             QByteArray line=tempFile->readLine(65536);
             if (line.startsWith("--"+boundary))
             {
                 // Boundary found. Until now we have collected 2 bytes too much,
                 // so remove them from the last result
                 if (fileName.isEmpty() && !fieldName.isEmpty())
                 {
                     // last field was a form field
                     fieldValue.remove(fieldValue.size()-2,2);
                     parameters.insert(fieldName,fieldValue);
                     qDebug("HttpRequest: set parameter %s=%s",fieldName.data(),fieldValue.data());
                 }
                 else if (!fileName.isEmpty() && !fieldName.isEmpty())
                 {
                     // last field was a file
                     #ifdef SUPERVERBOSE
                         qDebug("HttpRequest::parseMultiPartFile: finishing writing to uploaded file");
                     #endif
                     parameters.insert(fieldName,fileName);
                     if (uploadedFile)
                     {
                         uploadedFile->resize(uploadedFile->size()-2);
                         uploadedFile->flush();
                         uploadedFile->seek(0);
                         qDebug("HttpRequest::parseMultiPartFile: set parameter %s=%s",fieldName.data(),fileName.data());
                         uploadedFiles.insert(fieldName,uploadedFile);
                         qDebug("HttpRequest::parseMultiPartFile: uploaded file size is %i",(int) uploadedFile->size());
                     }
                 }
                 if (line.contains(boundary+"--"))
                 {
                     finished=true;
                 }
                 break;
             }
             else
             {
                 if (fileName.isEmpty() && !fieldName.isEmpty())
                 {
                     // this is a form field.
                     currentSize+=line.size();
                     fieldValue.append(line);
                 }
                 else if (!fileName.isEmpty() && !fieldName.isEmpty())
                 {
                     // this is a file
                     if (!uploadedFile)
                     {
                         uploadedFile=new QTemporaryFile();
                         uploadedFile->open();
                     }
                     uploadedFile->write(line);
                     if (uploadedFile->error())
                     {
                         qCritical("HttpRequest::parseMultiPartFile: error writing temp file, %s",qPrintable(uploadedFile->errorString()));
                     }
                 }
             }
         }
     }
     if (tempFile->error())
     {
         qCritical("HttpRequest::parseMultiPartFile: cannot read temp file, %s",qPrintable(tempFile->errorString()));
     }
     #ifdef SUPERVERBOSE
         qDebug("HttpRequest::parseMultiPartFile: finished parsing multipart temp file");
     #endif
 }
readBody()
void HttpRequest::readBody (QTcpSocket * socket) private
Sub-procedure of readFromSocket(), read the request body.
Definition at line 165 of file httprequest.cpp.
References abort, bodyData, boundary, complete, currentSize, expectedBodySize, maxMultiPartSize, parseMultiPartFile(), status, and tempFile.
Referenced by readFromSocket().
 {
     Q_ASSERT(expectedBodySize!=0);
     if (boundary.isEmpty())
     {
         // normal body, no multipart
         #ifdef SUPERVERBOSE
             qDebug("HttpRequest::readBody: receive body");
         #endif
         int toRead=expectedBodySize-bodyData.size();
         QByteArray newData=socket->read(toRead);
         currentSize+=newData.size();
         bodyData.append(newData);
         if (bodyData.size()>=expectedBodySize)
         {
             status=complete;
         }
     }
     else
     {
         // multipart body, store into temp file
         #ifdef SUPERVERBOSE
             qDebug("HttpRequest::readBody: receiving multipart body");
         #endif
         // Create an object for the temporary file, if not already present
         if (tempFile == NULL)
         {
             tempFile = new QTemporaryFile;
         }
         if (!tempFile->isOpen())
         {
             tempFile->open();
         }
         // Transfer data in 64kb blocks
         int fileSize=tempFile->size();
         int toRead=expectedBodySize-fileSize;
         if (toRead>65536)
         {
             toRead=65536;
         }
         fileSize+=tempFile->write(socket->read(toRead));
         if (fileSize>=maxMultiPartSize)
         {
             qWarning("HttpRequest::readBody: received too many multipart bytes");
             status=abort;
         }
         else if (fileSize>=expectedBodySize)
         {
         #ifdef SUPERVERBOSE
             qDebug("HttpRequest::readBody: received whole multipart body");
         #endif
             tempFile->flush();
             if (tempFile->error())
             {
                 qCritical("HttpRequest::readBody: Error writing temp file for multipart body");
             }
             parseMultiPartFile();
             tempFile->close();
             status=complete;
         }
     }
 }
readFromSocket()
void HttpRequest::readFromSocket (QTcpSocket * socket)
Read the HTTP request from a socket. This method is called by the connection handler repeatedly until the status is RequestStatus::complete or RequestStatus::abort.
Parameters
socket Source of the data
Definition at line 306 of file httprequest.cpp.
References abort, boundary, complete, currentSize, decodeRequestParams(), extractCookies(), maxMultiPartSize, maxSize, readBody(), readHeader(), readRequest(), status, waitForBody, waitForHeader, and waitForRequest.
Referenced by qtwebapp::HttpConnectionHandler::read().
 {
     Q_ASSERT(status!=complete);
     if (status==waitForRequest)
     {
         readRequest(socket);
     }
     else if (status==waitForHeader)
     {
         readHeader(socket);
     }
     else if (status==waitForBody)
     {
         readBody(socket);
     }
     if ((boundary.isEmpty() && currentSize>maxSize) || (!boundary.isEmpty() && currentSize>maxMultiPartSize))
     {
         qWarning("HttpRequest::readFromSocket: received too many bytes");
         status=abort;
     }
     if (status==complete)
     {
         // Extract and decode request parameters from url and body
         decodeRequestParams();
         // Extract cookies from headers
         extractCookies();
     }
 }
readHeader()
void HttpRequest::readHeader (QTcpSocket * socket) private
Sub-procedure of readFromSocket(), read header lines.
Definition at line 75 of file httprequest.cpp.
References abort, boundary, complete, currentHeader, currentSize, expectedBodySize, headers, lineBuffer, maxMultiPartSize, maxSize, status, and waitForBody.
Referenced by readFromSocket().
 {
     #ifdef SUPERVERBOSE
         qDebug("HttpRequest::readHeader");
     #endif
     int toRead=maxSize-currentSize+1; // allow one byte more to be able to detect overflow
     lineBuffer.append(socket->readLine(toRead));
     currentSize+=lineBuffer.size();
     if (!lineBuffer.contains('\r') && !lineBuffer.contains('\n'))
     {
         #ifdef SUPERVERBOSE
             qDebug("HttpRequest::readHeader: collecting more parts until line break");
         #endif
         return;
     }
     QByteArray newData=lineBuffer.trimmed();
     lineBuffer.clear();
     int colon=newData.indexOf(':');
     if (colon>0)
     {
         // Received a line with a colon - a header
         currentHeader=newData.left(colon).toLower();
         QByteArray value=newData.mid(colon+1).trimmed();
         headers.insert(currentHeader,value);
         #ifdef SUPERVERBOSE
             qDebug("HttpRequest::readHeader: received header %s: %s",currentHeader.data(),value.data());
         #endif
     }
     else if (!newData.isEmpty())
     {
         // received another line - belongs to the previous header
         #ifdef SUPERVERBOSE
             qDebug("HttpRequest::readHeader: read additional line of header");
         #endif
         // Received additional line of previous header
         if (headers.contains(currentHeader)) {
             headers.insert(currentHeader,headers.value(currentHeader)+" "+newData);
         }
     }
     else
     {
         // received an empty line - end of headers reached
         #ifdef SUPERVERBOSE
             qDebug("HttpRequest::readHeader: headers completed");
         #endif
         // Empty line received, that means all headers have been received
         // Check for multipart/form-data
         QByteArray contentType=headers.value("content-type");
         if (contentType.startsWith("multipart/form-data"))
         {
             int posi=contentType.indexOf("boundary=");
             if (posi>=0) {
                 boundary=contentType.mid(posi+9);
                 if  (boundary.startsWith('"') && boundary.endsWith('"'))
                 {
                    boundary = boundary.mid(1,boundary.length()-2);
                 }
             }
         }
         QByteArray contentLength=headers.value("content-length");
         if (!contentLength.isEmpty())
         {
             expectedBodySize=contentLength.toInt();
         }
         if (expectedBodySize==0)
         {
             #ifdef SUPERVERBOSE
                 qDebug("HttpRequest::readHeader: expect no body");
             #endif
             status=complete;
         }
         else if (boundary.isEmpty() && expectedBodySize+currentSize>maxSize)
         {
             qWarning("HttpRequest::readHeader: expected body is too large");
             status=abort;
         }
         else if (!boundary.isEmpty() && expectedBodySize>maxMultiPartSize)
         {
             qWarning("HttpRequest::readHeader: expected multipart body is too large");
             status=abort;
         }
         else {
             #ifdef SUPERVERBOSE
                 qDebug("HttpRequest::readHeader: expect %i bytes body",expectedBodySize);
             #endif
             status=waitForBody;
         }
     }
 }
readRequest()
void HttpRequest::readRequest (QTcpSocket * socket) private
Sub-procedure of readFromSocket(), read the first line of a request.
Definition at line 40 of file httprequest.cpp.
References abort, currentSize, lineBuffer, maxSize, method, path, peerAddress, status, version, and waitForHeader.
Referenced by readFromSocket().
 {
     #ifdef SUPERVERBOSE
         qDebug("HttpRequest::readRequest: read request");
     #endif
     int toRead=maxSize-currentSize+1; // allow one byte more to be able to detect overflow
     lineBuffer.append(socket->readLine(toRead));
     currentSize+=lineBuffer.size();
     if (!lineBuffer.contains('\r') && !lineBuffer.contains('\n'))
     {
         #ifdef SUPERVERBOSE
             qDebug("HttpRequest::readRequest: collecting more parts until line break");
         #endif
         return;
     }
     QByteArray newData=lineBuffer.trimmed();
     lineBuffer.clear();
     if (!newData.isEmpty())
     {
         QList<QByteArray> list=newData.split(' ');
         if (list.count()!=3 || !list.at(2).contains("HTTP"))
         {
             qWarning("HttpRequest::readRequest: received broken HTTP request, invalid first line");
             status=abort;
         }
         else {
             method=list.at(0).trimmed();
             path=list.at(1);
             version=list.at(2);
             peerAddress = socket->peerAddress();
             status=waitForHeader;
         }
     }
 }
urlDecode()
QByteArray HttpRequest::urlDecode (const QByteArray source) static
Decode an URL parameter. E.g. replace "%23" by '#' and replace '+' by ' '.
Parameters
source The url encoded strings
See also
QUrl::toPercentEncoding for the reverse direction
Definition at line 401 of file httprequest.cpp.
Referenced by decodeRequestParams(), and getPath().
 {
     QByteArray buffer(source);
     buffer.replace('+',' ');
     int percentChar=buffer.indexOf('%');
     while (percentChar>=0)
     {
         bool ok;
         char byte=buffer.mid(percentChar+1,2).toInt(&ok,16);
         if (ok)
         {
             buffer.replace(percentChar,3,(char*)&byte,1);
         }
         percentChar=buffer.indexOf('%',percentChar+1);
     }
     return buffer;
 }
Friends And Related Function Documentation
HttpSessionStore
friend class HttpSessionStore friend
Definition at line 43 of file httprequest.h.
Member Data Documentation
bodyData
QByteArray qtwebapp::HttpRequest::bodyData private
Storage for raw body data
Definition at line 182 of file httprequest.h.
Referenced by decodeRequestParams(), getBody(), and readBody().
boundary
QByteArray qtwebapp::HttpRequest::boundary private
Boundary of multipart/form-data body. Empty if there is no such header
Definition at line 218 of file httprequest.h.
Referenced by parseMultiPartFile(), readBody(), readFromSocket(), and readHeader().
cookies
QMap<QByteArray,QByteArray> qtwebapp::HttpRequest::cookies private
Received cookies
Definition at line 179 of file httprequest.h.
Referenced by extractCookies(), getCookie(), and getCookieMap().
currentHeader
QByteArray qtwebapp::HttpRequest::currentHeader private
Name of the current header, or empty if no header is being processed
Definition at line 215 of file httprequest.h.
Referenced by readHeader().
currentSize
int qtwebapp::HttpRequest::currentSize private
Current size
Definition at line 209 of file httprequest.h.
Referenced by HttpRequest(), parseMultiPartFile(), readBody(), readFromSocket(), readHeader(), and readRequest().
expectedBodySize
int qtwebapp::HttpRequest::expectedBodySize private
Expected size of body
Definition at line 212 of file httprequest.h.
Referenced by HttpRequest(), readBody(), and readHeader().
headers
QMultiMap<QByteArray,QByteArray> qtwebapp::HttpRequest::headers private
Request headers
Definition at line 170 of file httprequest.h.
Referenced by decodeRequestParams(), extractCookies(), getHeader(), getHeaderMap(), getHeaders(), and readHeader().
lineBuffer
QByteArray qtwebapp::HttpRequest::lineBuffer private
Buffer for collecting characters of request and header lines
Definition at line 242 of file httprequest.h.
Referenced by readHeader(), and readRequest().
maxMultiPartSize
int qtwebapp::HttpRequest::maxMultiPartSize private
Maximum allowed size of multipart forms in bytes.
Definition at line 206 of file httprequest.h.
Referenced by HttpRequest(), readBody(), readFromSocket(), and readHeader().
maxSize
int qtwebapp::HttpRequest::maxSize private
Maximum size of requests in bytes.
Definition at line 203 of file httprequest.h.
Referenced by HttpRequest(), readFromSocket(), readHeader(), and readRequest().
method
QByteArray qtwebapp::HttpRequest::method private
Request method
Definition at line 185 of file httprequest.h.
Referenced by getMethod(), and readRequest().
parameters
QMultiMap<QByteArray,QByteArray> qtwebapp::HttpRequest::parameters private
Parameters of the request
Definition at line 173 of file httprequest.h.
Referenced by decodeRequestParams(), getParameter(), getParameterMap(), getParameters(), and parseMultiPartFile().
path
QByteArray qtwebapp::HttpRequest::path private
Request path (in raw encoded format)
Definition at line 188 of file httprequest.h.
Referenced by decodeRequestParams(), getPath(), getRawPath(), and readRequest().
peerAddress
QHostAddress qtwebapp::HttpRequest::peerAddress private
Address of the connected peer.
Definition at line 200 of file httprequest.h.
Referenced by getPeerAddress(), and readRequest().
status
RequestStatus qtwebapp::HttpRequest::status private
Status of this request. For the state engine.
See also
RequestStatus
Definition at line 197 of file httprequest.h.
Referenced by getStatus(), HttpRequest(), readBody(), readFromSocket(), readHeader(), and readRequest().
tempFile
QTemporaryFile* qtwebapp::HttpRequest::tempFile private
Temp file, that is used to store the multipart/form-data body
Definition at line 221 of file httprequest.h.
Referenced by HttpRequest(), parseMultiPartFile(), readBody(), and ~HttpRequest().
uploadedFiles
QMap<QByteArray,QTemporaryFile*> qtwebapp::HttpRequest::uploadedFiles private
Uploaded files of the request, key is the field name.
Definition at line 176 of file httprequest.h.
Referenced by getUploadedFile(), parseMultiPartFile(), and ~HttpRequest().
useQtSettings
bool qtwebapp::HttpRequest::useQtSettings private
Settings flag
Definition at line 245 of file httprequest.h.
version
QByteArray qtwebapp::HttpRequest::version private
Request protocol version
Definition at line 191 of file httprequest.h.
Referenced by getVersion(), and readRequest().
The documentation for this class was generated from the following files:
httpserver/httprequest.h
httpserver/httprequest.cpp