SDRAngel: LocalInput::MsgConfigureLocalInput Class Reference
LocalInput::MsgConfigureLocalInput Class Reference
#include <localinput.h>
Public Member Functions
const LocalInputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureLocalInput * create (const LocalInputSettings &settings, bool force=false)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureLocalInput (const LocalInputSettings &settings, bool force)
Private Attributes
LocalInputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 42 of file localinput.h.
Constructor & Destructor Documentation
MsgConfigureLocalInput()
LocalInput::MsgConfigureLocalInput::MsgConfigureLocalInput (const LocalInputSettings & settings, bool force) inline private
Definition at line 58 of file localinput.h.
Referenced by create().
                                                                                :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureLocalInput* LocalInput::MsgConfigureLocalInput::create (const LocalInputSettings & settings, bool force = false) inline static
Definition at line 49 of file localinput.h.
References MsgConfigureLocalInput().
Referenced by LocalInput::deserialize(), LocalInputGui::updateHardware(), and LocalInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureLocalInput(settings, force);
         }
getForce()
bool LocalInput::MsgConfigureLocalInput::getForce () const inline
Definition at line 47 of file localinput.h.
References m_force.
Referenced by LocalInput::handleMessage().
 { return m_force; }
getSettings()
const LocalInputSettings& LocalInput::MsgConfigureLocalInput::getSettings () const inline
Definition at line 46 of file localinput.h.
References m_settings.
Referenced by LocalInputGui::handleMessage(), and LocalInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool LocalInput::MsgConfigureLocalInput::m_force private
Definition at line 56 of file localinput.h.
Referenced by getForce().
m_settings
LocalInputSettings LocalInput::MsgConfigureLocalInput::m_settings private
Definition at line 55 of file localinput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/localinput/localinput.h