SDRAngel: RTLSDRInput::MsgConfigureRTLSDR Class Reference
RTLSDRInput::MsgConfigureRTLSDR Class Reference
#include <rtlsdrinput.h>
Public Member Functions
const RTLSDRSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureRTLSDR * create (const RTLSDRSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureRTLSDR (const RTLSDRSettings &settings, bool force)
Private Attributes
RTLSDRSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 39 of file rtlsdrinput.h.
Constructor & Destructor Documentation
MsgConfigureRTLSDR()
RTLSDRInput::MsgConfigureRTLSDR::MsgConfigureRTLSDR (const RTLSDRSettings & settings, bool force) inline private
Definition at line 55 of file rtlsdrinput.h.
Referenced by create().
                                                                        :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureRTLSDR* RTLSDRInput::MsgConfigureRTLSDR::create (const RTLSDRSettings & settings, bool force) inline static
Definition at line 46 of file rtlsdrinput.h.
References MsgConfigureRTLSDR().
Referenced by RTLSDRInput::deserialize(), RTLSDRInput::setCenterFrequency(), RTLSDRGui::updateHardware(), and RTLSDRInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureRTLSDR(settings, force);
         }
getForce()
bool RTLSDRInput::MsgConfigureRTLSDR::getForce () const inline
Definition at line 44 of file rtlsdrinput.h.
References m_force.
Referenced by RTLSDRInput::handleMessage().
 { return m_force; }
getSettings()
const RTLSDRSettings& RTLSDRInput::MsgConfigureRTLSDR::getSettings () const inline
Definition at line 43 of file rtlsdrinput.h.
References m_settings.
Referenced by RTLSDRGui::handleMessage(), and RTLSDRInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool RTLSDRInput::MsgConfigureRTLSDR::m_force private
Definition at line 53 of file rtlsdrinput.h.
Referenced by getForce().
m_settings
RTLSDRSettings RTLSDRInput::MsgConfigureRTLSDR::m_settings private
Definition at line 52 of file rtlsdrinput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/rtlsdr/rtlsdrinput.h