SDRAngel: Sample Struct Reference
Sample Struct Reference
#include <dsptypes.h>
Public Member Functions
Sample ()
Sample (FixReal real)
Sample (FixReal real, FixReal imag)
Sample (const Sample &other)
Sample & operator= (const Sample &other)
Sample & operator+= (const Sample &other)
Sample & operator-= (const Sample &other)
Sample & operator/= (const unsigned int &divisor)
void setReal (FixReal v)
void setImag (FixReal v)
FixReal real () const
FixReal imag () const
Public Attributes
FixReal m_real
FixReal m_imag
Detailed Description
Definition at line 46 of file dsptypes.h.
Constructor & Destructor Documentation
Sample() [1/4]
Sample::Sample () inline
Definition at line 48 of file dsptypes.h.
 : m_real(0), m_imag(0) {}
Sample() [2/4]
Sample::Sample (FixReal real) inline
Definition at line 49 of file dsptypes.h.
 : m_real(real), m_imag(0) {}
Sample() [3/4]
Sample::Sample (FixReal real, FixReal imag) inline
Definition at line 50 of file dsptypes.h.
 : m_real(real), m_imag(imag) {}
Sample() [4/4]
Sample::Sample (const Sample & other) inline
Definition at line 51 of file dsptypes.h.
 : m_real(other.m_real), m_imag(other.m_imag) {}
Member Function Documentation
imag()
FixReal Sample::imag () const inline
Definition at line 62 of file dsptypes.h.
References m_imag.
Referenced by IntHalfbandFilterST< HBFilterOrder >::myDecimate(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::myDecimate(), IntHalfbandFilterEO2< HBFilterOrder >::myDecimate(), IntHalfbandFilterEO1< HBFilterOrder >::myDecimate(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myDecimate(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimate(), IntHalfbandFilter< qint32, 32 >::myDecimate(), IntHalfbandFilterST< HBFilterOrder >::myInterpolate(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::myInterpolateZeroStuffing(), IntHalfbandFilterEO2< HBFilterOrder >::myInterpolateZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::myInterpolateZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myInterpolateZeroStuffing(), IntHalfbandFilter< qint32, 32 >::myInterpolateZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myInterpolateZeroStuffing(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workDecimateCenter(), IntHalfbandFilterST< HBFilterOrder >::workDecimateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateCenter(), IntHalfbandFilterEO2< HBFilterOrder >::workDecimateCenter(), IntHalfbandFilter< qint32, 32 >::workDecimateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateCenter(), IntHalfbandFilterST< HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateLowerHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateLowerHalf(), IntHalfbandFilter< qint32, 32 >::workDecimateLowerHalf(), IntHalfbandFilterST< HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateUpperHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateUpperHalf(), IntHalfbandFilter< qint32, 32 >::workDecimateUpperHalf(), IntHalfbandFilterST< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilter< qint32, 32 >::workInterpolateCenter(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenterZeroStuffing(), IntHalfbandFilter< qint32, 32 >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterST< HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), IntHalfbandFilter< qint32, 32 >::workInterpolateLowerHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilter< qint32, 32 >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterST< HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf(), IntHalfbandFilter< qint32, 32 >::workInterpolateUpperHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing(), and IntHalfbandFilter< qint32, 32 >::workInterpolateUpperHalfZeroStuffing().
 { return m_imag; }
operator+=()
Sample& Sample::operator+= (const Sample & other) inline
Definition at line 54 of file dsptypes.h.
References m_imag, and m_real.
 { m_real += other.m_real; m_imag += other.m_imag; return *this; }
operator-=()
Sample& Sample::operator-= (const Sample & other) inline
Definition at line 55 of file dsptypes.h.
References m_imag, and m_real.
 { m_real -= other.m_real; m_imag -= other.m_imag; return *this; }
operator/=()
Sample& Sample::operator/= (const unsigned int & divisor) inline
Definition at line 56 of file dsptypes.h.
References m_imag, and m_real.
 { m_real /= divisor; m_imag /= divisor; return *this; }
operator=()
Sample& Sample::operator= (const Sample & other) inline
Definition at line 52 of file dsptypes.h.
References m_imag, and m_real.
 { m_real = other.m_real; m_imag = other.m_imag; return *this; }
real()
FixReal Sample::real () const inline
Definition at line 61 of file dsptypes.h.
References m_real.
Referenced by IntHalfbandFilterST< HBFilterOrder >::myDecimate(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::myDecimate(), IntHalfbandFilterEO2< HBFilterOrder >::myDecimate(), IntHalfbandFilterEO1< HBFilterOrder >::myDecimate(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myDecimate(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myDecimate(), IntHalfbandFilter< qint32, 32 >::myDecimate(), IntHalfbandFilterST< HBFilterOrder >::myInterpolate(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::myInterpolateZeroStuffing(), IntHalfbandFilterEO2< HBFilterOrder >::myInterpolateZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::myInterpolateZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::myInterpolateZeroStuffing(), IntHalfbandFilter< qint32, 32 >::myInterpolateZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::myInterpolateZeroStuffing(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workDecimateCenter(), IntHalfbandFilterST< HBFilterOrder >::workDecimateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateCenter(), IntHalfbandFilterEO2< HBFilterOrder >::workDecimateCenter(), IntHalfbandFilter< qint32, 32 >::workDecimateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateCenter(), IntHalfbandFilterST< HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateLowerHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateLowerHalf(), IntHalfbandFilter< qint32, 32 >::workDecimateLowerHalf(), IntHalfbandFilterST< HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workDecimateUpperHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workDecimateUpperHalf(), IntHalfbandFilter< qint32, 32 >::workDecimateUpperHalf(), IntHalfbandFilterST< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilter< qint32, 32 >::workInterpolateCenter(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenterZeroStuffing(), IntHalfbandFilter< qint32, 32 >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterST< HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), IntHalfbandFilter< qint32, 32 >::workInterpolateLowerHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilter< qint32, 32 >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterST< HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf(), IntHalfbandFilter< qint32, 32 >::workInterpolateUpperHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing(), and IntHalfbandFilter< qint32, 32 >::workInterpolateUpperHalfZeroStuffing().
 { return m_real; }
setImag()
void Sample::setImag (FixReal v) inline
Definition at line 59 of file dsptypes.h.
References m_imag.
Referenced by RemoteDataReadQueue::convertDataToSample(), IntHalfbandFilterST< HBFilterOrder >::doFIR(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::doFIR(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::doFIR(), IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), IntHalfbandFilterEO2< HBFilterOrder >::doFIR(), IntHalfbandFilter< qint32, 32 >::doFIR(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::doFIR(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::doInterpolateFIR(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::doInterpolateFIR(), IntHalfbandFilterEO1< HBFilterOrder >::doInterpolateFIR(), IntHalfbandFilterEO2< HBFilterOrder >::doInterpolateFIR(), IntHalfbandFilter< qint32, 32 >::doInterpolateFIR(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::doInterpolateFIR(), FileSource::pull(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilter< qint32, 32 >::workInterpolateCenter(), IntHalfbandFilterST< HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), IntHalfbandFilter< qint32, 32 >::workInterpolateLowerHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilter< qint32, 32 >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterST< HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf(), IntHalfbandFilter< qint32, 32 >::workInterpolateUpperHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing(), and IntHalfbandFilter< qint32, 32 >::workInterpolateUpperHalfZeroStuffing().
 { m_imag = v; }
setReal()
void Sample::setReal (FixReal v) inline
Definition at line 58 of file dsptypes.h.
References m_real.
Referenced by RemoteDataReadQueue::convertDataToSample(), IntHalfbandFilterST< HBFilterOrder >::doFIR(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::doFIR(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::doFIR(), IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), IntHalfbandFilterEO2< HBFilterOrder >::doFIR(), IntHalfbandFilter< qint32, 32 >::doFIR(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::doFIR(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::doInterpolateFIR(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::doInterpolateFIR(), IntHalfbandFilterEO1< HBFilterOrder >::doInterpolateFIR(), IntHalfbandFilterEO2< HBFilterOrder >::doInterpolateFIR(), IntHalfbandFilter< qint32, 32 >::doInterpolateFIR(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::doInterpolateFIR(), FileSource::pull(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateCenter(), IntHalfbandFilter< qint32, 32 >::workInterpolateCenter(), IntHalfbandFilterST< HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalf(), IntHalfbandFilter< qint32, 32 >::workInterpolateLowerHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilter< qint32, 32 >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterST< HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalf(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalf(), IntHalfbandFilter< qint32, 32 >::workInterpolateUpperHalf(), IntHalfbandFilterEO2< HBFilterOrder >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterEO< qint32, qint32, DOWNCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterDBFI< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalfZeroStuffing(), IntHalfbandFilterDB< qint32, UPCHANNELIZER_HB_FILTER_ORDER >::workInterpolateUpperHalfZeroStuffing(), and IntHalfbandFilter< qint32, 32 >::workInterpolateUpperHalfZeroStuffing().
 { m_real = v; }
Member Data Documentation
m_imag
FixReal Sample::m_imag
Definition at line 65 of file dsptypes.h.
Referenced by DownChannelizer::feed(), imag(), FSample::imag(), UDPSource::modulateSample(), operator+=(), FSample::operator+=(), operator-=(), FSample::operator-=(), operator/=(), FSample::operator/=(), operator=(), FSample::operator=(), UDPSource::pull(), AMMod::pull(), WFMMod::pull(), NFMMod::pull(), SSBMod::pull(), FreeDVMod::pull(), ATVMod::pull(), ATVMod::pullFinalize(), UDPSourceUDPHandler::readSample(), SymbolSynchronizer::run(), Projector::run(), SymbolSynchronizer::runZ(), setImag(), and FSample::setImag().
m_real
FixReal Sample::m_real
Definition at line 64 of file dsptypes.h.
Referenced by DownChannelizer::feed(), UDPSource::modulateSample(), operator+=(), FSample::operator+=(), operator-=(), FSample::operator-=(), operator/=(), FSample::operator/=(), operator=(), FSample::operator=(), UDPSource::pull(), AMMod::pull(), WFMMod::pull(), NFMMod::pull(), SSBMod::pull(), FreeDVMod::pull(), ATVMod::pull(), ATVMod::pullFinalize(), UDPSourceUDPHandler::readSample(), real(), FSample::real(), SymbolSynchronizer::run(), Projector::run(), SymbolSynchronizer::runZ(), setReal(), and FSample::setReal().
The documentation for this struct was generated from the following file:
sdrbase/dsp/dsptypes.h