SDRAngel: DSDDecoder Class Reference
DSDDecoder Class Reference
#include <dsddecoder.h>
Public Member Functions
DSDDecoder ()
~DSDDecoder ()
void pushSample (short sample)
short getFilteredSample () const
short getSymbolSyncSample () const
short * getAudio1 (int &nbSamples)
void resetAudio1 ()
short * getAudio2 (int &nbSamples)
void resetAudio2 ()
void enableMbelib (bool enable)
bool mbeDVReady1 () const
void resetMbeDV1 ()
bool mbeDVReady2 () const
void resetMbeDV2 ()
const unsigned char * getMbeDVFrame1 () const
const unsigned char * getMbeDVFrame2 () const
bool getVoice1On () const
bool getVoice2On () const
void setTDMAStereo (bool tdmaStereo)
bool getSymbolPLLLocked () const
int getMbeRateIndex () const
int getInLevel () const
int getCarrierPos () const
int getZeroCrossingPos () const
int getSymbolSyncQuality () const
int getSamplesPerSymbol () const
void enableCosineFiltering (bool on)
DSDcc::DSDDecoder::DSDSyncType getSyncType () const
DSDcc::DSDDecoder::DSDStationType getStationType () const
const char * getFrameTypeText () const
const DSDcc::DSDDMR & getDMRDecoder () const
const DSDcc::DSDDstar & getDStarDecoder () const
const DSDcc::DSDdPMR & getDPMRDecoder () const
const DSDcc::DSDYSF & getYSFDecoder () const
const DSDcc::DSDNXDN & getNXDNDecoder () const
void setMyPoint (float lat, float lon)
void setAudioGain (float gain)
void setBaudRate (int baudRate)
void setSymbolPLLLock (bool pllLock)
void useHPMbelib (bool useHP)
void set48k (bool to48k)
void setUpsampling (int upsampling)
Private Attributes
DSDcc::DSDDecoder m_decoder
Detailed Description
Definition at line 26 of file dsddecoder.h.
Constructor & Destructor Documentation
DSDDecoder()
DSDDecoder::DSDDecoder ()
Definition at line 25 of file dsddecoder.cpp.
References m_decoder.
 {
     m_decoder.setQuiet();
     m_decoder.setUpsampling(6); // force upsampling of audio to 48k
     m_decoder.setStereo(true);  // force copy to L+R channels
     m_decoder.setDecodeMode(DSDcc::DSDDecoder::DSDDecodeAuto, true); // Initialize with auto-detect
     m_decoder.setUvQuality(3); // This is gr-dsd default
     m_decoder.enableCosineFiltering(false);
     m_decoder.setDataRate(DSDcc::DSDDecoder::DSDRate4800);
 }
~DSDDecoder()
DSDDecoder::~DSDDecoder ()
Definition at line 36 of file dsddecoder.cpp.
 {
 }
Member Function Documentation
enableCosineFiltering()
void DSDDecoder::enableCosineFiltering (bool on) inline
Definition at line 61 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::applySettings().
 { m_decoder.enableCosineFiltering(on); }
enableMbelib()
void DSDDecoder::enableMbelib (bool enable) inline
Definition at line 41 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { m_decoder.enableMbelib(enable); }
getAudio1()
short* DSDDecoder::getAudio1 (int & nbSamples) inline
Definition at line 36 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { return m_decoder.getAudio1(nbSamples); }
getAudio2()
short* DSDDecoder::getAudio2 (int & nbSamples) inline
Definition at line 38 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { return m_decoder.getAudio2(nbSamples); }
getCarrierPos()
int DSDDecoder::getCarrierPos () const inline
Definition at line 57 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemodGUI::tick().
 { return m_decoder.getCarrierPos(); }
getDMRDecoder()
const DSDcc::DSDDMR& DSDDecoder::getDMRDecoder () const inline
Definition at line 65 of file dsddecoder.h.
References m_decoder.
 { return m_decoder.getDMRDecoder(); }
getDPMRDecoder()
const DSDcc::DSDdPMR& DSDDecoder::getDPMRDecoder () const inline
Definition at line 67 of file dsddecoder.h.
References m_decoder.
 { return m_decoder.getDPMRDecoder(); }
getDStarDecoder()
const DSDcc::DSDDstar& DSDDecoder::getDStarDecoder () const inline
Definition at line 66 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::formatStatusText().
 { return m_decoder.getDStarDecoder(); }
getFilteredSample()
short DSDDecoder::getFilteredSample () const inline
Definition at line 33 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { return m_decoder.getFilteredSample(); }
getFrameTypeText()
const char* DSDDecoder::getFrameTypeText () const inline
Definition at line 64 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemodGUI::tick().
 { return m_decoder.getFrameTypeText(); }
getInLevel()
int DSDDecoder::getInLevel () const inline
Definition at line 56 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemodGUI::tick().
 { return m_decoder.getInLevel(); }
getMbeDVFrame1()
const unsigned char* DSDDecoder::getMbeDVFrame1 () const inline
Definition at line 47 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { return m_decoder.getMbeDVFrame1(); }
getMbeDVFrame2()
const unsigned char* DSDDecoder::getMbeDVFrame2 () const inline
Definition at line 48 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { return m_decoder.getMbeDVFrame2(); }
getMbeRateIndex()
int DSDDecoder::getMbeRateIndex () const inline
Definition at line 54 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { return (int) m_decoder.getMbeRate(); }
getNXDNDecoder()
const DSDcc::DSDNXDN& DSDDecoder::getNXDNDecoder () const inline
Definition at line 69 of file dsddecoder.h.
References m_decoder.
 { return m_decoder.getNXDNDecoder(); }
getSamplesPerSymbol()
int DSDDecoder::getSamplesPerSymbol () const inline
Definition at line 60 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { return m_decoder.getSamplesPerSymbol(); }
getStationType()
DSDcc::DSDDecoder::DSDStationType DSDDecoder::getStationType () const inline
Definition at line 63 of file dsddecoder.h.
References m_decoder.
 { return m_decoder.getStationType(); }
getSymbolPLLLocked()
bool DSDDecoder::getSymbolPLLLocked () const inline
Definition at line 52 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemodGUI::tick().
 { return m_decoder.getSymbolPLLLocked(); }
getSymbolSyncQuality()
int DSDDecoder::getSymbolSyncQuality () const inline
Definition at line 59 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemodGUI::tick().
 { return m_decoder.getSymbolSyncQuality(); }
getSymbolSyncSample()
short DSDDecoder::getSymbolSyncSample () const inline
Definition at line 34 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { return m_decoder.getSymbolSyncSample(); }
getSyncType()
DSDcc::DSDDecoder::DSDSyncType DSDDecoder::getSyncType () const inline
Definition at line 62 of file dsddecoder.h.
References m_decoder.
 { return m_decoder.getSyncType(); }
getVoice1On()
bool DSDDecoder::getVoice1On () const inline
Definition at line 49 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemodGUI::tick().
 { return m_decoder.getVoice1On(); }
getVoice2On()
bool DSDDecoder::getVoice2On () const inline
Definition at line 50 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemodGUI::tick().
 { return m_decoder.getVoice2On(); }
getYSFDecoder()
const DSDcc::DSDYSF& DSDDecoder::getYSFDecoder () const inline
Definition at line 68 of file dsddecoder.h.
References m_decoder.
 { return m_decoder.getYSFDecoder(); }
getZeroCrossingPos()
int DSDDecoder::getZeroCrossingPos () const inline
Definition at line 58 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemodGUI::tick().
 { return m_decoder.getZeroCrossingPos(); }
mbeDVReady1()
bool DSDDecoder::mbeDVReady1 () const inline
Definition at line 43 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { return m_decoder.mbeDVReady1(); }
mbeDVReady2()
bool DSDDecoder::mbeDVReady2 () const inline
Definition at line 45 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { return m_decoder.mbeDVReady2(); }
pushSample()
void DSDDecoder::pushSample (short sample) inline
Definition at line 32 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { m_decoder.run(sample); }
resetAudio1()
void DSDDecoder::resetAudio1 () inline
Definition at line 37 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { m_decoder.resetAudio1(); }
resetAudio2()
void DSDDecoder::resetAudio2 () inline
Definition at line 39 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { m_decoder.resetAudio2(); }
resetMbeDV1()
void DSDDecoder::resetMbeDV1 () inline
Definition at line 44 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { m_decoder.resetMbeDV1(); }
resetMbeDV2()
void DSDDecoder::resetMbeDV2 () inline
Definition at line 46 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::feed().
 { m_decoder.resetMbeDV2(); }
set48k()
void DSDDecoder::set48k (bool to48k)
Definition at line 40 of file dsddecoder.cpp.
References m_decoder.
Referenced by useHPMbelib().
 {
     m_decoder.setUpsampling(to48k ? 6 : 0);
 }
setAudioGain()
void DSDDecoder::setAudioGain (float gain) inline
Definition at line 72 of file dsddecoder.h.
References m_decoder, and setBaudRate().
Referenced by DSDDemod::applySettings().
 { m_decoder.setAudioGain(gain); }
setBaudRate()
void DSDDecoder::setBaudRate (int baudRate)
Definition at line 50 of file dsddecoder.cpp.
References m_decoder.
Referenced by DSDDemod::applySettings(), and setAudioGain().
 {
     if (baudRate == 2400)
     {
         m_decoder.setDataRate(DSDcc::DSDDecoder::DSDRate2400);
     }
     else if (baudRate == 4800)
     {
         m_decoder.setDataRate(DSDcc::DSDDecoder::DSDRate4800);
     }
     else if (baudRate == 9600)
     {
         m_decoder.setDataRate(DSDcc::DSDDecoder::DSDRate9600);
     }
     else // default 4800 bauds
     {
         m_decoder.setDataRate(DSDcc::DSDDecoder::DSDRate4800);
     }
     // when setting baud rate activate detection of all possible modes for this rate
     // because on the other hand when a mode is selected then the baud rate is automatically changed
     m_decoder.setDecodeMode(DSDcc::DSDDecoder::DSDDecodeAuto, true);
 }
setMyPoint()
void DSDDecoder::setMyPoint (float lat, float lon) inline
Definition at line 71 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::handleMessage().
 { m_decoder.setMyPoint(lat, lon); }
setSymbolPLLLock()
void DSDDecoder::setSymbolPLLLock (bool pllLock) inline
Definition at line 74 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::applySettings().
 { m_decoder.setSymbolPLLLock(pllLock); }
setTDMAStereo()
void DSDDecoder::setTDMAStereo (bool tdmaStereo) inline
Definition at line 51 of file dsddecoder.h.
References m_decoder.
Referenced by DSDDemod::applySettings().
 { m_decoder.setTDMAStereo(tdmaStereo); }
setUpsampling()
void DSDDecoder::setUpsampling (int upsampling)
Definition at line 45 of file dsddecoder.cpp.
References m_decoder.
Referenced by DSDDemod::applyAudioSampleRate(), and useHPMbelib().
 {
     m_decoder.setUpsampling(upsampling);
 }
useHPMbelib()
void DSDDecoder::useHPMbelib (bool useHP) inline
Definition at line 75 of file dsddecoder.h.
References m_decoder, set48k(), and setUpsampling().
Referenced by DSDDemod::applySettings().
 { m_decoder.useHPMbelib(useHP); }
Member Data Documentation
m_decoder
DSDcc::DSDDecoder DSDDecoder::m_decoder private
Definition at line 80 of file dsddecoder.h.
Referenced by DSDDecoder(), enableCosineFiltering(), enableMbelib(), getAudio1(), getAudio2(), getCarrierPos(), getDMRDecoder(), getDPMRDecoder(), getDStarDecoder(), getFilteredSample(), getFrameTypeText(), getInLevel(), getMbeDVFrame1(), getMbeDVFrame2(), getMbeRateIndex(), getNXDNDecoder(), getSamplesPerSymbol(), getStationType(), getSymbolPLLLocked(), getSymbolSyncQuality(), getSymbolSyncSample(), getSyncType(), getVoice1On(), getVoice2On(), getYSFDecoder(), getZeroCrossingPos(), mbeDVReady1(), mbeDVReady2(), pushSample(), resetAudio1(), resetAudio2(), resetMbeDV1(), resetMbeDV2(), set48k(), setAudioGain(), setBaudRate(), setMyPoint(), setSymbolPLLLock(), setTDMAStereo(), setUpsampling(), and useHPMbelib().
The documentation for this class was generated from the following files:
plugins/channelrx/demoddsd/dsddecoder.h
plugins/channelrx/demoddsd/dsddecoder.cpp