SDRAngel: FCDProThread Class Reference
FCDProThread Class Reference
#include <fcdprothread.h>
Inherits QThread.
Public Member Functions
FCDProThread (SampleSinkFifo *sampleFifo, AudioFifo *fcdFIFO, QObject *parent=nullptr)
~FCDProThread ()
void startWork ()
void stopWork ()
void setLog2Decimation (unsigned int log2_decim)
void setFcPos (int fcPos)
Private Member Functions
void run ()
void work (unsigned int n_items)
Private Attributes
AudioFifo * m_fcdFIFO
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
unsigned int m_log2Decim
int m_fcPos
qint16 m_buf [fcd_traits< Pro >::convBufSize *2]
SampleVector m_convertBuffer
SampleSinkFifo * m_sampleFifo
Decimators< qint32, qint16, SDR_RX_SAMP_SZ, 16 > m_decimators
Detailed Description
Definition at line 31 of file fcdprothread.h.
Constructor & Destructor Documentation
FCDProThread()
FCDProThread::FCDProThread (SampleSinkFifo * sampleFifo, AudioFifo * fcdFIFO, QObject * parent = nullptr)
Definition at line 30 of file fcdprothread.cpp.
                                                                                           :
     QThread(parent),
     m_fcdFIFO(fcdFIFO),
     m_running(false),
     m_log2Decim(0),
     m_fcPos(2),
     m_convertBuffer(fcd_traits<Pro>::convBufSize), // nb samples
     m_sampleFifo(sampleFifo)
 {
     start();
 }
~FCDProThread()
FCDProThread::~FCDProThread ()
Definition at line 42 of file fcdprothread.cpp.
 {
 }
Member Function Documentation
run()
void FCDProThread::run () private
Definition at line 76 of file fcdprothread.cpp.
References m_running, and work().
 {
     m_running = true;
     qDebug("FCDProThread::run: start running loop");
     while (m_running)
     {
         work(fcd_traits<Pro>::convBufSize);
         std::this_thread::sleep_for(std::chrono::microseconds(200));
     }
     qDebug("FCDProThread::run: running loop stopped");
     m_running = false;
 }
setFcPos()
void FCDProThread::setFcPos (int fcPos)
Definition at line 71 of file fcdprothread.cpp.
References m_fcPos.
Referenced by FCDProInput::applySettings().
 {
     m_fcPos = fcPos;
 }
setLog2Decimation()
void FCDProThread::setLog2Decimation (unsigned int log2_decim)
Definition at line 66 of file fcdprothread.cpp.
References m_log2Decim.
Referenced by FCDProInput::applySettings().
 {
     m_log2Decim = log2_decim;
 }
startWork()
void FCDProThread::startWork ()
Definition at line 46 of file fcdprothread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by FCDProInput::start().
 {
     m_startWaitMutex.lock();
     start();
     while(!m_running)
     {
         m_startWaiter.wait(&m_startWaitMutex, 100);
     }
     m_startWaitMutex.unlock();
 }
stopWork()
void FCDProThread::stopWork ()
Definition at line 60 of file fcdprothread.cpp.
References m_running.
Referenced by FCDProInput::stop().
 {
     m_running = false;
     wait();
 }
work()
void FCDProThread::work (unsigned int n_items) private
Definition at line 91 of file fcdprothread.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup(), m_buf, m_convertBuffer, m_decimators, m_fcdFIFO, m_fcPos, m_log2Decim, m_sampleFifo, AudioFifo::read(), and SampleSinkFifo::write().
Referenced by run().
 {
     uint32_t nbRead = m_fcdFIFO->read((unsigned char *) m_buf, n_items); // number of samples
     SampleVector::iterator it = m_convertBuffer.begin();
     if (m_log2Decim == 0)
     {
         m_decimators.decimate1(&it, m_buf, 2*nbRead);
     }
     else
     {
         if (m_fcPos == 0) // Infradyne
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_inf(&it, m_buf, 2*nbRead);
                 break;
             case 2:
                 m_decimators.decimate4_inf(&it, m_buf, 2*nbRead);
                 break;
             case 3:
                 m_decimators.decimate8_inf(&it, m_buf, 2*nbRead);
                 break;
             case 4:
                 m_decimators.decimate16_inf(&it, m_buf, 2*nbRead);
                 break;
             case 5:
                 m_decimators.decimate32_inf(&it, m_buf, 2*nbRead);
                 break;
             case 6:
                 m_decimators.decimate64_inf(&it, m_buf, 2*nbRead);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 1) // Supradyne
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_sup(&it, m_buf, 2*nbRead);
                 break;
             case 2:
                 m_decimators.decimate4_sup(&it, m_buf, 2*nbRead);
                 break;
             case 3:
                 m_decimators.decimate8_sup(&it, m_buf, 2*nbRead);
                 break;
             case 4:
                 m_decimators.decimate16_sup(&it, m_buf, 2*nbRead);
                 break;
             case 5:
                 m_decimators.decimate32_sup(&it, m_buf, 2*nbRead);
                 break;
             case 6:
                 m_decimators.decimate64_sup(&it, m_buf, 2*nbRead);
                 break;
             default:
                 break;
             }
         }
         else // Centered
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_cen(&it, m_buf, 2*nbRead);
                 break;
             case 2:
                 m_decimators.decimate4_cen(&it, m_buf, 2*nbRead);
                 break;
             case 3:
                 m_decimators.decimate8_cen(&it, m_buf, 2*nbRead);
                 break;
             case 4:
                 m_decimators.decimate16_cen(&it, m_buf, 2*nbRead);
                 break;
             case 5:
                 m_decimators.decimate32_cen(&it, m_buf, 2*nbRead);
                 break;
             case 6:
                 m_decimators.decimate64_cen(&it, m_buf, 2*nbRead);
                 break;
             default:
                 break;
             }
         }
     }
     m_sampleFifo->write(m_convertBuffer.begin(), it);
 }
Member Data Documentation
m_buf
qint16 FCDProThread::m_buf[fcd_traits< Pro >::convBufSize *2] private
Definition at line 52 of file fcdprothread.h.
Referenced by work().
m_convertBuffer
SampleVector FCDProThread::m_convertBuffer private
Definition at line 53 of file fcdprothread.h.
Referenced by work().
m_decimators
Decimators<qint32, qint16, SDR_RX_SAMP_SZ, 16> FCDProThread::m_decimators private
Definition at line 55 of file fcdprothread.h.
Referenced by work().
m_fcdFIFO
AudioFifo* FCDProThread::m_fcdFIFO private
Definition at line 44 of file fcdprothread.h.
Referenced by work().
m_fcPos
int FCDProThread::m_fcPos private
Definition at line 50 of file fcdprothread.h.
Referenced by setFcPos(), and work().
m_log2Decim
unsigned int FCDProThread::m_log2Decim private
Definition at line 49 of file fcdprothread.h.
Referenced by setLog2Decimation(), and work().
m_running
bool FCDProThread::m_running private
Definition at line 48 of file fcdprothread.h.
Referenced by run(), startWork(), and stopWork().
m_sampleFifo
SampleSinkFifo* FCDProThread::m_sampleFifo private
Definition at line 54 of file fcdprothread.h.
Referenced by work().
m_startWaiter
QWaitCondition FCDProThread::m_startWaiter private
Definition at line 47 of file fcdprothread.h.
Referenced by startWork().
m_startWaitMutex
QMutex FCDProThread::m_startWaitMutex private
Definition at line 46 of file fcdprothread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/samplesource/fcdpro/fcdprothread.h
plugins/samplesource/fcdpro/fcdprothread.cpp