SDRAngel: RemoteOutput Class Reference
RemoteOutput Class Reference
#include <remoteoutput.h>
Classes
class MsgConfigureRemoteOutput
class MsgConfigureRemoteOutputChunkCorrection
class MsgConfigureRemoteOutputWork
class MsgStartStop
Public Member Functions
RemoteOutput (DeviceAPI *deviceAPI)
virtual ~RemoteOutput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the sink.
virtual void setSampleRate (int sampleRate)
For when the sink sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the sink.
virtual void setCenterFrequency (qint64 centerFrequency)
std::time_t getStartingTimeStamp () const
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSink
DeviceSampleSink ()
virtual ~DeviceSampleSink ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSourceFifo * getSampleFifo ()
Private Slots
void tick ()
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applySettings (const RemoteOutputSettings &settings, bool force=false)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const RemoteOutputSettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void analyzeApiReply (const QJsonObject &jsonObject, const QString &answer)
void sampleRateCorrection (double remoteTimeDeltaUs, double timeDeltaUs, uint32_t remoteSampleCount, uint32_t sampleCount)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const RemoteOutputSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
RemoteOutputSettings m_settings
uint64_t m_centerFrequency
RemoteOutputThread * m_remoteOutputThread
QString m_deviceDescription
std::time_t m_startingTimeStamp
const QTimer & m_masterTimer
uint32_t m_tickCount
uint32_t m_tickMultiplier
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
uint32_t m_lastRemoteSampleCount
uint32_t m_lastSampleCount
uint64_t m_lastRemoteTimestampRateCorrection
uint64_t m_lastTimestampRateCorrection
int m_lastQueueLength
uint32_t m_nbRemoteSamplesSinceRateCorrection
uint32_t m_nbSamplesSinceRateCorrection
int m_chunkSizeCorrection
Static Private Attributes
static const uint32_t NbSamplesForRateCorrection = 5000000
Additional Inherited Members
Public Types inherited from DeviceSampleSink
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
Static Public Member Functions inherited from DeviceSampleSink
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Interp, fcPos_t fcPos, quint32 devSampleRate)
Protected Slots inherited from DeviceSampleSink
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSink
SampleSourceFifo m_sampleSourceFifo
MessageQueue m_inputMessageQueue
Input queue to the sink.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 40 of file remoteoutput.h.
Constructor & Destructor Documentation
RemoteOutput()
RemoteOutput::RemoteOutput (DeviceAPI * deviceAPI)
Definition at line 48 of file remoteoutput.cpp.
References m_deviceAPI, m_masterTimer, m_networkManager, networkManagerFinished(), DeviceAPI::setNbSinkStreams(), and tick().
Referenced by RemoteOutput::MsgConfigureRemoteOutputChunkCorrection::MsgConfigureRemoteOutputChunkCorrection().
                                                :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_centerFrequency(0),
     m_remoteOutputThread(0),
     m_deviceDescription("RemoteOutput"),
     m_startingTimeStamp(0),
     m_masterTimer(deviceAPI->getMasterTimer()),
     m_tickCount(0),
     m_tickMultiplier(20),
     m_lastRemoteSampleCount(0),
     m_lastSampleCount(0),
     m_lastRemoteTimestampRateCorrection(0),
     m_lastTimestampRateCorrection(0),
     m_lastQueueLength(-2),
     m_nbRemoteSamplesSinceRateCorrection(0),
     m_nbSamplesSinceRateCorrection(0),
     m_chunkSizeCorrection(0)
 {
     m_deviceAPI->setNbSinkStreams(1);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     connect(&m_masterTimer, SIGNAL(timeout()), this, SLOT(tick()));
 }
~RemoteOutput()
RemoteOutput::~RemoteOutput () virtual
Definition at line 73 of file remoteoutput.cpp.
References m_networkManager, networkManagerFinished(), and stop().
Referenced by RemoteOutput::MsgConfigureRemoteOutputChunkCorrection::MsgConfigureRemoteOutputChunkCorrection().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     stop();
     delete m_networkManager;
 }
Member Function Documentation
analyzeApiReply()
void RemoteOutput::analyzeApiReply (const QJsonObject & jsonObject, const QString & answer) private
Definition at line 536 of file remoteoutput.cpp.
References RemoteOutputThread::getSamplesCount(), m_centerFrequency, m_lastQueueLength, m_lastRemoteSampleCount, m_lastRemoteTimestampRateCorrection, m_lastSampleCount, m_lastTimestampRateCorrection, m_nbRemoteSamplesSinceRateCorrection, m_nbSamplesSinceRateCorrection, m_remoteOutputThread, NbSamplesForRateCorrection, and sampleRateCorrection().
Referenced by networkManagerFinished().
 {
     if (jsonObject.contains("RemoteSourceReport"))
     {
         QJsonObject report = jsonObject["RemoteSourceReport"].toObject();
         m_centerFrequency = report["deviceCenterFreq"].toInt() * 1000;
         if (!m_remoteOutputThread) {
             return;
         }
         int queueSize = report["queueSize"].toInt();
         queueSize = queueSize == 0 ? 10 : queueSize;
         int queueLength = report["queueLength"].toInt();
         int queueLengthPercent = (queueLength*100)/queueSize;
         uint64_t remoteTimestampUs = report["tvSec"].toInt()*1000000ULL + report["tvUSec"].toInt();
         uint32_t remoteSampleCountDelta, remoteSampleCount;
         remoteSampleCount = report["samplesCount"].toInt();
         if (remoteSampleCount < m_lastRemoteSampleCount) {
             remoteSampleCountDelta = (0xFFFFFFFFU - m_lastRemoteSampleCount) + remoteSampleCount + 1;
         } else {
             remoteSampleCountDelta = remoteSampleCount - m_lastRemoteSampleCount;
         }
         uint32_t sampleCountDelta, sampleCount;
         uint64_t timestampUs;
         sampleCount = m_remoteOutputThread->getSamplesCount(timestampUs);
         if (sampleCount < m_lastSampleCount) {
             sampleCountDelta = (0xFFFFFFFFU - m_lastSampleCount) + sampleCount + 1;
         } else {
             sampleCountDelta = sampleCount - m_lastSampleCount;
         }
         // on initial state wait for queue stabilization
         if ((m_lastRemoteTimestampRateCorrection == 0) && (queueLength >= m_lastQueueLength-1) && (queueLength <= m_lastQueueLength+1))
         {
             m_lastRemoteTimestampRateCorrection = remoteTimestampUs;
             m_lastTimestampRateCorrection = timestampUs;
             m_nbRemoteSamplesSinceRateCorrection = 0;
             m_nbSamplesSinceRateCorrection = 0;
         }
         else
         {
             m_nbRemoteSamplesSinceRateCorrection += remoteSampleCountDelta;
             m_nbSamplesSinceRateCorrection += sampleCountDelta;
             qDebug("RemoteOutput::analyzeApiReply: queueLengthPercent: %d m_nbSamplesSinceRateCorrection: %u",
                 queueLengthPercent,
                 m_nbRemoteSamplesSinceRateCorrection);
             if (m_nbRemoteSamplesSinceRateCorrection > NbSamplesForRateCorrection)
             {
                 sampleRateCorrection(remoteTimestampUs - m_lastRemoteTimestampRateCorrection,
                         timestampUs - m_lastTimestampRateCorrection,
                         m_nbRemoteSamplesSinceRateCorrection,
                         m_nbSamplesSinceRateCorrection);
                 m_lastRemoteTimestampRateCorrection = remoteTimestampUs;
                 m_lastTimestampRateCorrection = timestampUs;
                 m_nbRemoteSamplesSinceRateCorrection = 0;
                 m_nbSamplesSinceRateCorrection = 0;
             }
         }
         m_lastRemoteSampleCount = remoteSampleCount;
         m_lastSampleCount = sampleCount;
         m_lastQueueLength = queueLength;
     }
     else if (jsonObject.contains("remoteOutputSettings"))
     {
         qDebug("RemoteOutput::analyzeApiReply: reply:\n%s", answer.toStdString().c_str());
     }
 }
applySettings()
void RemoteOutput::applySettings (const RemoteOutputSettings & settings, bool force = false) private
Definition at line 246 of file remoteoutput.cpp.
References DeviceAPI::getDeviceEngineInputMessageQueue(), RemoteOutputSettings::m_apiAddress, RemoteOutputSettings::m_apiPort, m_centerFrequency, RemoteOutputSettings::m_dataAddress, RemoteOutputSettings::m_dataPort, m_deviceAPI, m_mutex, RemoteOutputSettings::m_nbFECBlocks, m_remoteOutputThread, RemoteOutputSettings::m_reverseAPIAddress, RemoteOutputSettings::m_reverseAPIDeviceIndex, RemoteOutputSettings::m_reverseAPIPort, RemoteOutputSettings::m_sampleRate, m_settings, m_tickMultiplier, RemoteOutputSettings::m_txDelay, RemoteOutputSettings::m_useReverseAPI, NbSamplesForRateCorrection, MessageQueue::push(), RemoteOutputThread::setDataAddress(), RemoteOutputThread::setNbBlocksFEC(), RemoteOutputThread::setSamplerate(), RemoteOutputThread::setTxDelay(), and webapiReverseSendSettings().
Referenced by handleMessage(), and init().
 {
     QMutexLocker mutexLocker(&m_mutex);
     bool forwardChange = false;
     bool changeTxDelay = false;
     QList<QString> reverseAPIKeys;
     if ((m_settings.m_dataAddress != settings.m_dataAddress) || force) {
         reverseAPIKeys.append("dataAddress");
     }
     if ((m_settings.m_dataPort != settings.m_dataPort) || force) {
         reverseAPIKeys.append("dataPort");
     }
     if ((m_settings.m_apiAddress != settings.m_apiAddress) || force) {
         reverseAPIKeys.append("apiAddress");
     }
     if ((m_settings.m_apiPort != settings.m_apiPort) || force) {
         reverseAPIKeys.append("apiPort");
     }
     if (force || (m_settings.m_dataAddress != settings.m_dataAddress) || (m_settings.m_dataPort != settings.m_dataPort))
     {
         if (m_remoteOutputThread != 0) {
             m_remoteOutputThread->setDataAddress(settings.m_dataAddress, settings.m_dataPort);
         }
     }
     if (force || (m_settings.m_sampleRate != settings.m_sampleRate))
     {
         reverseAPIKeys.append("sampleRate");
         if (m_remoteOutputThread != 0) {
             m_remoteOutputThread->setSamplerate(settings.m_sampleRate);
         }
         m_tickMultiplier = (21*NbSamplesForRateCorrection) / (2*settings.m_sampleRate); // two times per sample filling period plus small extension
         m_tickMultiplier = m_tickMultiplier < 20 ? 20 : m_tickMultiplier; // not below half a second
         forwardChange = true;
         changeTxDelay = true;
     }
     if (force || (m_settings.m_nbFECBlocks != settings.m_nbFECBlocks))
     {
         reverseAPIKeys.append("nbFECBlocks");
         if (m_remoteOutputThread != 0) {
             m_remoteOutputThread->setNbBlocksFEC(settings.m_nbFECBlocks);
         }
         changeTxDelay = true;
     }
     if (force || (m_settings.m_txDelay != settings.m_txDelay))
     {
         reverseAPIKeys.append("txDelay");
         changeTxDelay = true;
     }
     if (changeTxDelay)
     {
         if (m_remoteOutputThread != 0) {
             m_remoteOutputThread->setTxDelay(settings.m_txDelay);
         }
     }
     mutexLocker.unlock();
     qDebug() << "RemoteOutput::applySettings:"
             << " m_sampleRate: " << settings.m_sampleRate
             << " m_txDelay: " << settings.m_txDelay
             << " m_nbFECBlocks: " << settings.m_nbFECBlocks
             << " m_apiAddress: " << settings.m_apiAddress
             << " m_apiPort: " << settings.m_apiPort
             << " m_dataAddress: " << settings.m_dataAddress
             << " m_dataPort: " << settings.m_dataPort;
     if (forwardChange)
     {
         DSPSignalNotification *notif = new DSPSignalNotification(settings.m_sampleRate, m_centerFrequency);
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
deserialize()
bool RemoteOutput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSink.
Definition at line 135 of file remoteoutput.cpp.
References RemoteOutput::MsgConfigureRemoteOutput::create(), RemoteOutputSettings::deserialize(), DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and RemoteOutputSettings::resetToDefaults().
Referenced by RemoteOutput::MsgConfigureRemoteOutputChunkCorrection::MsgConfigureRemoteOutputChunkCorrection().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureRemoteOutput* message = MsgConfigureRemoteOutput::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureRemoteOutput* messageToGUI = MsgConfigureRemoteOutput::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void RemoteOutput::destroy () virtual
Implements DeviceSampleSink.
Definition at line 80 of file remoteoutput.cpp.
Referenced by RemoteOutput::MsgConfigureRemoteOutputChunkCorrection::MsgConfigureRemoteOutputChunkCorrection().
 {
     delete this;
 }
getCenterFrequency()
quint64 RemoteOutput::getCenterFrequency () const virtual
Center frequency exposed by the sink.
Implements DeviceSampleSink.
Definition at line 167 of file remoteoutput.cpp.
References m_centerFrequency.
Referenced by setSampleRate().
 {
     return m_centerFrequency;
 }
getDeviceDescription()
const QString & RemoteOutput::getDeviceDescription () const virtual
Implements DeviceSampleSink.
Definition at line 157 of file remoteoutput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getSampleRate()
int RemoteOutput::getSampleRate () const virtual
Sample rate exposed by the sink.
Implements DeviceSampleSink.
Definition at line 162 of file remoteoutput.cpp.
References RemoteOutputSettings::m_sampleRate, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     return m_settings.m_sampleRate;
 }
getStartingTimeStamp()
std::time_t RemoteOutput::getStartingTimeStamp () const
Definition at line 172 of file remoteoutput.cpp.
References m_startingTimeStamp.
Referenced by setCenterFrequency().
 {
     return m_startingTimeStamp;
 }
handleMessage()
bool RemoteOutput::handleMessage (const Message & message) virtual
Implements DeviceSampleSink.
Definition at line 177 of file remoteoutput.cpp.
References applySettings(), RemoteOutput::MsgConfigureRemoteOutputChunkCorrection::getChunkCorrection(), RemoteOutput::MsgConfigureRemoteOutput::getForce(), Message::getIdentifier(), RemoteOutput::MsgConfigureRemoteOutput::getSettings(), RemoteOutput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), RemoteOutput::MsgConfigureRemoteOutputWork::isWorking(), m_deviceAPI, m_remoteOutputThread, m_settings, RemoteOutputSettings::m_useReverseAPI, Message::match(), RemoteOutputThread::setChunkCorrection(), DeviceAPI::startDeviceEngine(), RemoteOutputThread::startWork(), DeviceAPI::stopDeviceEngine(), RemoteOutputThread::stopWork(), and webapiReverseSendStartStop().
Referenced by setCenterFrequency().
 {
     if (MsgConfigureRemoteOutput::match(message))
     {
         qDebug() << "RemoteOutput::handleMessage:" << message.getIdentifier();
         MsgConfigureRemoteOutput& conf = (MsgConfigureRemoteOutput&) message;
         applySettings(conf.getSettings(), conf.getForce());
         return true;
     }
     else if (MsgConfigureRemoteOutputWork::match(message))
     {
         MsgConfigureRemoteOutputWork& conf = (MsgConfigureRemoteOutputWork&) message;
         bool working = conf.isWorking();
         if (m_remoteOutputThread != 0)
         {
             if (working)
             {
                 m_remoteOutputThread->startWork();
             }
             else
             {
                 m_remoteOutputThread->stopWork();
             }
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "RemoteOutput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else if (MsgConfigureRemoteOutputChunkCorrection::match(message))
     {
         MsgConfigureRemoteOutputChunkCorrection& conf = (MsgConfigureRemoteOutputChunkCorrection&) message;
         if (m_remoteOutputThread != 0)
         {
             m_remoteOutputThread->setChunkCorrection(conf.getChunkCorrection());
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void RemoteOutput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSink.
Definition at line 112 of file remoteoutput.cpp.
References applySettings(), and m_settings.
Referenced by RemoteOutput::MsgConfigureRemoteOutputChunkCorrection::MsgConfigureRemoteOutputChunkCorrection().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void RemoteOutput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 503 of file remoteoutput.cpp.
References analyzeApiReply().
Referenced by RemoteOutput(), and ~RemoteOutput().
 {
     if (reply->error())
     {
         qInfo("RemoteOutput::networkManagerFinished: error: %s", qPrintable(reply->errorString()));
         return;
     }
     QString answer = reply->readAll();
     try
     {
         QByteArray jsonBytes(answer.toStdString().c_str());
         QJsonParseError error;
         QJsonDocument doc = QJsonDocument::fromJson(jsonBytes, &error);
         if (error.error == QJsonParseError::NoError)
         {
             analyzeApiReply(doc.object(), answer);
         }
         else
         {
             QString errorMsg = QString("Reply JSON error: ") + error.errorString() + QString(" at offset ") + QString::number(error.offset);
             qInfo().noquote() << "RemoteOutput::networkManagerFinished" << errorMsg;
         }
     }
     catch (const std::exception& ex)
     {
         QString errorMsg = QString("Error parsing request: ") + ex.what();
         qInfo().noquote() << "RemoteOutput::networkManagerFinished" << errorMsg;
     }
 }
sampleRateCorrection()
void RemoteOutput::sampleRateCorrection (double remoteTimeDeltaUs, double timeDeltaUs, uint32_t remoteSampleCount, uint32_t sampleCount) private
Definition at line 612 of file remoteoutput.cpp.
References RemoteOutput::MsgConfigureRemoteOutputChunkCorrection::create(), DeviceSampleSink::getInputMessageQueue(), m_chunkSizeCorrection, and MessageQueue::push().
Referenced by analyzeApiReply().
 {
     double deltaSR = (remoteSampleCount/remoteTimeDeltaUs) - (sampleCount/timeDeltaUs);
     double chunkCorr = 50000 * deltaSR; // for 50ms chunk intervals (50000us)
     m_chunkSizeCorrection += roundf(chunkCorr);
     qDebug("RemoteOutput::sampleRateCorrection: %d (%f) samples", m_chunkSizeCorrection, chunkCorr);
     MsgConfigureRemoteOutputChunkCorrection* message = MsgConfigureRemoteOutputChunkCorrection::create(m_chunkSizeCorrection);
     getInputMessageQueue()->push(message);
 }
serialize()
QByteArray RemoteOutput::serialize () const virtual
Implements DeviceSampleSink.
Definition at line 130 of file remoteoutput.cpp.
References m_settings, and RemoteOutputSettings::serialize().
Referenced by RemoteOutput::MsgConfigureRemoteOutputChunkCorrection::MsgConfigureRemoteOutputChunkCorrection().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
virtual void RemoteOutput::setCenterFrequency (qint64 centerFrequency) inline virtual
Implements DeviceSampleSink.
Definition at line 141 of file remoteoutput.h.
References getStartingTimeStamp(), handleMessage(), webapiReportGet(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) centerFrequency; }
setMessageQueueToGUI()
virtual void RemoteOutput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSink.
Definition at line 136 of file remoteoutput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSink::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void RemoteOutput::setSampleRate (int sampleRate) inline virtual
For when the sink sample rate is set externally.
Implements DeviceSampleSink.
Definition at line 139 of file remoteoutput.h.
References getCenterFrequency().
 { (void) sampleRate; }
start()
bool RemoteOutput::start () virtual
Implements DeviceSampleSink.
Definition at line 85 of file remoteoutput.cpp.
References RemoteOutputThread::connectTimer(), m_chunkSizeCorrection, RemoteOutputSettings::m_dataAddress, RemoteOutputSettings::m_dataPort, m_lastQueueLength, m_lastRemoteTimestampRateCorrection, m_lastTimestampRateCorrection, m_masterTimer, m_mutex, RemoteOutputSettings::m_nbFECBlocks, m_remoteOutputThread, RemoteOutputSettings::m_sampleRate, DeviceSampleSink::m_sampleSourceFifo, m_settings, RemoteOutputSettings::m_txDelay, RemoteOutputThread::setDataAddress(), RemoteOutputThread::setNbBlocksFEC(), RemoteOutputThread::setSamplerate(), RemoteOutputThread::setTxDelay(), and RemoteOutputThread::startWork().
Referenced by RemoteOutput::MsgConfigureRemoteOutputChunkCorrection::MsgConfigureRemoteOutputChunkCorrection().
 {
     QMutexLocker mutexLocker(&m_mutex);
     qDebug() << "RemoteOutput::start";
     m_remoteOutputThread = new RemoteOutputThread(&m_sampleSourceFifo);
     m_remoteOutputThread->setDataAddress(m_settings.m_dataAddress, m_settings.m_dataPort);
     m_remoteOutputThread->setSamplerate(m_settings.m_sampleRate);
     m_remoteOutputThread->setNbBlocksFEC(m_settings.m_nbFECBlocks);
     m_remoteOutputThread->connectTimer(m_masterTimer);
     m_remoteOutputThread->startWork();
     // restart auto rate correction
     m_lastRemoteTimestampRateCorrection = 0;
     m_lastTimestampRateCorrection = 0;
     m_lastQueueLength = -2; // set first value out of bounds
     m_chunkSizeCorrection = 0;
     m_remoteOutputThread->setTxDelay(m_settings.m_txDelay);
     mutexLocker.unlock();
     //applySettings(m_generalSettings, m_settings, true);
     qDebug("RemoteOutput::start: started");
     return true;
 }
stop()
void RemoteOutput::stop () virtual
Implements DeviceSampleSink.
Definition at line 117 of file remoteoutput.cpp.
References m_mutex, m_remoteOutputThread, and RemoteOutputThread::stopWork().
Referenced by RemoteOutput::MsgConfigureRemoteOutputChunkCorrection::MsgConfigureRemoteOutputChunkCorrection(), and ~RemoteOutput().
 {
     qDebug() << "RemoteOutput::stop";
     QMutexLocker mutexLocker(&m_mutex);
     if(m_remoteOutputThread != 0)
     {
         m_remoteOutputThread->stopWork();
         delete m_remoteOutputThread;
         m_remoteOutputThread = 0;
     }
 }
tick
void RemoteOutput::tick () private slot
Definition at line 484 of file remoteoutput.cpp.
References RemoteOutputSettings::m_apiAddress, RemoteOutputSettings::m_apiPort, RemoteOutputSettings::m_channelIndex, RemoteOutputSettings::m_deviceIndex, m_networkManager, m_networkRequest, m_settings, m_tickCount, and m_tickMultiplier.
Referenced by RemoteOutput().
 {
     if (++m_tickCount == m_tickMultiplier)
     {
         QString reportURL;
         reportURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/report")
                 .arg(m_settings.m_apiAddress)
                 .arg(m_settings.m_apiPort)
                 .arg(m_settings.m_deviceIndex)
                 .arg(m_settings.m_channelIndex);
         m_networkRequest.setUrl(QUrl(reportURL));
         m_networkManager->get(m_networkRequest);
         m_tickCount = 0;
     }
 }
webapiFormatDeviceReport()
void RemoteOutput::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 477 of file remoteoutput.cpp.
References SWGSDRangel::SWGDeviceReport::getRemoteOutputReport(), SampleSourceFifo::getRWBalance(), RemoteOutputThread::getSamplesCount(), m_remoteOutputThread, DeviceSampleSink::m_sampleSourceFifo, SWGSDRangel::SWGRemoteOutputReport::setBufferRwBalance(), and SWGSDRangel::SWGRemoteOutputReport::setSampleCount().
Referenced by webapiReportGet().
 {
     uint64_t ts_usecs;
     response.getRemoteOutputReport()->setBufferRwBalance(m_sampleSourceFifo.getRWBalance());
     response.getRemoteOutputReport()->setSampleCount(m_remoteOutputThread ? (int) m_remoteOutputThread->getSamplesCount(ts_usecs) : 0);
 }
webapiFormatDeviceSettings()
void RemoteOutput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const RemoteOutputSettings & settings) private
Definition at line 453 of file remoteoutput.cpp.
References SWGSDRangel::SWGDeviceSettings::getRemoteOutputSettings(), SWGSDRangel::SWGRemoteOutputSettings::getReverseApiAddress(), RemoteOutputSettings::m_apiAddress, RemoteOutputSettings::m_apiPort, m_centerFrequency, RemoteOutputSettings::m_channelIndex, RemoteOutputSettings::m_dataAddress, RemoteOutputSettings::m_dataPort, RemoteOutputSettings::m_deviceIndex, RemoteOutputSettings::m_nbFECBlocks, RemoteOutputSettings::m_reverseAPIAddress, RemoteOutputSettings::m_reverseAPIDeviceIndex, RemoteOutputSettings::m_reverseAPIPort, RemoteOutputSettings::m_sampleRate, RemoteOutputSettings::m_txDelay, RemoteOutputSettings::m_useReverseAPI, SWGSDRangel::SWGRemoteOutputSettings::setApiAddress(), SWGSDRangel::SWGRemoteOutputSettings::setApiPort(), SWGSDRangel::SWGRemoteOutputSettings::setCenterFrequency(), SWGSDRangel::SWGRemoteOutputSettings::setChannelIndex(), SWGSDRangel::SWGRemoteOutputSettings::setDataAddress(), SWGSDRangel::SWGRemoteOutputSettings::setDataPort(), SWGSDRangel::SWGRemoteOutputSettings::setDeviceIndex(), SWGSDRangel::SWGRemoteOutputSettings::setNbFecBlocks(), SWGSDRangel::SWGRemoteOutputSettings::setReverseApiAddress(), SWGSDRangel::SWGRemoteOutputSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGRemoteOutputSettings::setReverseApiPort(), SWGSDRangel::SWGRemoteOutputSettings::setSampleRate(), SWGSDRangel::SWGRemoteOutputSettings::setTxDelay(), and SWGSDRangel::SWGRemoteOutputSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getRemoteOutputSettings()->setCenterFrequency(m_centerFrequency);
     response.getRemoteOutputSettings()->setSampleRate(settings.m_sampleRate);
     response.getRemoteOutputSettings()->setTxDelay(settings.m_txDelay);
     response.getRemoteOutputSettings()->setNbFecBlocks(settings.m_nbFECBlocks);
     response.getRemoteOutputSettings()->setApiAddress(new QString(settings.m_apiAddress));
     response.getRemoteOutputSettings()->setApiPort(settings.m_apiPort);
     response.getRemoteOutputSettings()->setDataAddress(new QString(settings.m_dataAddress));
     response.getRemoteOutputSettings()->setDataPort(settings.m_dataPort);
     response.getRemoteOutputSettings()->setDeviceIndex(settings.m_deviceIndex);
     response.getRemoteOutputSettings()->setChannelIndex(settings.m_channelIndex);
     response.getRemoteOutputSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getRemoteOutputSettings()->getReverseApiAddress()) {
         *response.getRemoteOutputSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getRemoteOutputSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getRemoteOutputSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getRemoteOutputSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int RemoteOutput::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 442 of file remoteoutput.cpp.
References SWGSDRangel::SWGDeviceReport::getRemoteOutputReport(), SWGSDRangel::SWGRemoteOutputReport::init(), SWGSDRangel::SWGDeviceReport::setRemoteOutputReport(), and webapiFormatDeviceReport().
Referenced by setCenterFrequency().
 {
     (void) errorMessage;
     response.setRemoteOutputReport(new SWGSDRangel::SWGRemoteOutputReport());
     response.getRemoteOutputReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void RemoteOutput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const RemoteOutputSettings & settings, bool force) private
Definition at line 624 of file remoteoutput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getRemoteOutputSettings(), RemoteOutputSettings::m_apiAddress, RemoteOutputSettings::m_apiPort, RemoteOutputSettings::m_channelIndex, RemoteOutputSettings::m_dataAddress, RemoteOutputSettings::m_dataPort, m_deviceAPI, RemoteOutputSettings::m_deviceIndex, RemoteOutputSettings::m_nbFECBlocks, m_networkManager, m_networkRequest, RemoteOutputSettings::m_reverseAPIAddress, RemoteOutputSettings::m_reverseAPIDeviceIndex, RemoteOutputSettings::m_reverseAPIPort, RemoteOutputSettings::m_sampleRate, RemoteOutputSettings::m_txDelay, SWGSDRangel::SWGRemoteOutputSettings::setApiAddress(), SWGSDRangel::SWGRemoteOutputSettings::setApiPort(), SWGSDRangel::SWGRemoteOutputSettings::setChannelIndex(), SWGSDRangel::SWGRemoteOutputSettings::setDataAddress(), SWGSDRangel::SWGRemoteOutputSettings::setDataPort(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGRemoteOutputSettings::setDeviceIndex(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGRemoteOutputSettings::setNbFecBlocks(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGDeviceSettings::setRemoteOutputSettings(), SWGSDRangel::SWGRemoteOutputSettings::setSampleRate(), and SWGSDRangel::SWGRemoteOutputSettings::setTxDelay().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(1); // single Tx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("RemoteOutput"));
     swgDeviceSettings->setRemoteOutputSettings(new SWGSDRangel::SWGRemoteOutputSettings());
     SWGSDRangel::SWGRemoteOutputSettings *swgRemoteOutputSettings = swgDeviceSettings->getRemoteOutputSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("sampleRate") || force) {
         swgRemoteOutputSettings->setSampleRate(settings.m_sampleRate);
     }
     if (deviceSettingsKeys.contains("txDelay") || force) {
         swgRemoteOutputSettings->setTxDelay(settings.m_txDelay);
     }
     if (deviceSettingsKeys.contains("nbFECBlocks") || force) {
         swgRemoteOutputSettings->setNbFecBlocks(settings.m_nbFECBlocks);
     }
     if (deviceSettingsKeys.contains("apiAddress") || force) {
         swgRemoteOutputSettings->setApiAddress(new QString(settings.m_apiAddress));
     }
     if (deviceSettingsKeys.contains("apiPort") || force) {
         swgRemoteOutputSettings->setApiPort(settings.m_apiPort);
     }
     if (deviceSettingsKeys.contains("dataAddress") || force) {
         swgRemoteOutputSettings->setDataAddress(new QString(settings.m_dataAddress));
     }
     if (deviceSettingsKeys.contains("dataPort") || force) {
         swgRemoteOutputSettings->setDataPort(settings.m_dataPort);
     }
     if (deviceSettingsKeys.contains("deviceIndex") || force) {
         swgRemoteOutputSettings->setDeviceIndex(settings.m_deviceIndex);
     }
     if (deviceSettingsKeys.contains("channelIndex") || force) {
         swgRemoteOutputSettings->setChannelIndex(settings.m_channelIndex);
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void RemoteOutput::webapiReverseSendStartStop (bool start) private
Definition at line 681 of file remoteoutput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, RemoteOutputSettings::m_reverseAPIAddress, RemoteOutputSettings::m_reverseAPIDeviceIndex, RemoteOutputSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(1); // single Tx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("RemoteOutput"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int RemoteOutput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 350 of file remoteoutput.cpp.
References RemoteOutput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, and MessageQueue::push().
Referenced by setCenterFrequency().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgStartStop *messagetoGui = MsgStartStop::create(run);
         m_guiMessageQueue->push(messagetoGui);
     }
     return 200;
 }
webapiRunGet()
int RemoteOutput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 341 of file remoteoutput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setCenterFrequency().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int RemoteOutput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 369 of file remoteoutput.cpp.
References SWGSDRangel::SWGDeviceSettings::getRemoteOutputSettings(), SWGSDRangel::SWGRemoteOutputSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setRemoteOutputSettings(), and webapiFormatDeviceSettings().
Referenced by setCenterFrequency().
 {
     (void) errorMessage;
     response.setRemoteOutputSettings(new SWGSDRangel::SWGRemoteOutputSettings());
     response.getRemoteOutputSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int RemoteOutput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 380 of file remoteoutput.cpp.
References RemoteOutput::MsgConfigureRemoteOutput::create(), SWGSDRangel::SWGRemoteOutputSettings::getApiAddress(), SWGSDRangel::SWGRemoteOutputSettings::getApiPort(), SWGSDRangel::SWGRemoteOutputSettings::getChannelIndex(), SWGSDRangel::SWGRemoteOutputSettings::getDataAddress(), SWGSDRangel::SWGRemoteOutputSettings::getDataPort(), SWGSDRangel::SWGRemoteOutputSettings::getDeviceIndex(), SWGSDRangel::SWGRemoteOutputSettings::getNbFecBlocks(), SWGSDRangel::SWGDeviceSettings::getRemoteOutputSettings(), SWGSDRangel::SWGRemoteOutputSettings::getReverseApiAddress(), SWGSDRangel::SWGRemoteOutputSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGRemoteOutputSettings::getReverseApiPort(), SWGSDRangel::SWGRemoteOutputSettings::getSampleRate(), SWGSDRangel::SWGRemoteOutputSettings::getTxDelay(), SWGSDRangel::SWGRemoteOutputSettings::getUseReverseApi(), RemoteOutputSettings::m_apiAddress, RemoteOutputSettings::m_apiPort, RemoteOutputSettings::m_channelIndex, RemoteOutputSettings::m_dataAddress, RemoteOutputSettings::m_dataPort, RemoteOutputSettings::m_deviceIndex, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, RemoteOutputSettings::m_nbFECBlocks, RemoteOutputSettings::m_reverseAPIAddress, RemoteOutputSettings::m_reverseAPIDeviceIndex, RemoteOutputSettings::m_reverseAPIPort, RemoteOutputSettings::m_sampleRate, m_settings, RemoteOutputSettings::m_txDelay, RemoteOutputSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setCenterFrequency().
 {
     (void) errorMessage;
     RemoteOutputSettings settings = m_settings;
     if (deviceSettingsKeys.contains("sampleRate")) {
         settings.m_sampleRate = response.getRemoteOutputSettings()->getSampleRate();
     }
     if (deviceSettingsKeys.contains("txDelay")) {
         settings.m_txDelay = response.getRemoteOutputSettings()->getTxDelay();
     }
     if (deviceSettingsKeys.contains("nbFECBlocks")) {
         settings.m_nbFECBlocks = response.getRemoteOutputSettings()->getNbFecBlocks();
     }
     if (deviceSettingsKeys.contains("apiAddress")) {
         settings.m_apiAddress = *response.getRemoteOutputSettings()->getApiAddress();
     }
     if (deviceSettingsKeys.contains("apiPort")) {
         settings.m_apiPort = response.getRemoteOutputSettings()->getApiPort();
     }
     if (deviceSettingsKeys.contains("dataAddress")) {
         settings.m_dataAddress = *response.getRemoteOutputSettings()->getDataAddress();
     }
     if (deviceSettingsKeys.contains("dataPort")) {
         settings.m_dataPort = response.getRemoteOutputSettings()->getDataPort();
     }
     if (deviceSettingsKeys.contains("deviceIndex")) {
         settings.m_deviceIndex = response.getRemoteOutputSettings()->getDeviceIndex();
     }
     if (deviceSettingsKeys.contains("channelIndex")) {
         settings.m_channelIndex = response.getRemoteOutputSettings()->getChannelIndex();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getRemoteOutputSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getRemoteOutputSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getRemoteOutputSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getRemoteOutputSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureRemoteOutput *msg = MsgConfigureRemoteOutput::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureRemoteOutput *msgToGUI = MsgConfigureRemoteOutput::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_centerFrequency
uint64_t RemoteOutput::m_centerFrequency private
Definition at line 173 of file remoteoutput.h.
Referenced by analyzeApiReply(), applySettings(), getCenterFrequency(), and webapiFormatDeviceSettings().
m_chunkSizeCorrection
int RemoteOutput::m_chunkSizeCorrection private
Definition at line 191 of file remoteoutput.h.
Referenced by sampleRateCorrection(), and start().
m_deviceAPI
DeviceAPI* RemoteOutput::m_deviceAPI private
Definition at line 170 of file remoteoutput.h.
Referenced by applySettings(), handleMessage(), RemoteOutput(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), and webapiRunGet().
m_deviceDescription
QString RemoteOutput::m_deviceDescription private
Definition at line 175 of file remoteoutput.h.
Referenced by getDeviceDescription().
m_lastQueueLength
int RemoteOutput::m_lastQueueLength private
Definition at line 188 of file remoteoutput.h.
Referenced by analyzeApiReply(), and start().
m_lastRemoteSampleCount
uint32_t RemoteOutput::m_lastRemoteSampleCount private
Definition at line 184 of file remoteoutput.h.
Referenced by analyzeApiReply().
m_lastRemoteTimestampRateCorrection
uint64_t RemoteOutput::m_lastRemoteTimestampRateCorrection private
Definition at line 186 of file remoteoutput.h.
Referenced by analyzeApiReply(), and start().
m_lastSampleCount
uint32_t RemoteOutput::m_lastSampleCount private
Definition at line 185 of file remoteoutput.h.
Referenced by analyzeApiReply().
m_lastTimestampRateCorrection
uint64_t RemoteOutput::m_lastTimestampRateCorrection private
Definition at line 187 of file remoteoutput.h.
Referenced by analyzeApiReply(), and start().
m_masterTimer
const QTimer& RemoteOutput::m_masterTimer private
Definition at line 177 of file remoteoutput.h.
Referenced by RemoteOutput(), and start().
m_mutex
QMutex RemoteOutput::m_mutex private
Definition at line 171 of file remoteoutput.h.
Referenced by applySettings(), start(), and stop().
m_nbRemoteSamplesSinceRateCorrection
uint32_t RemoteOutput::m_nbRemoteSamplesSinceRateCorrection private
Definition at line 189 of file remoteoutput.h.
Referenced by analyzeApiReply().
m_nbSamplesSinceRateCorrection
uint32_t RemoteOutput::m_nbSamplesSinceRateCorrection private
Definition at line 190 of file remoteoutput.h.
Referenced by analyzeApiReply().
m_networkManager
QNetworkAccessManager* RemoteOutput::m_networkManager private
Definition at line 181 of file remoteoutput.h.
Referenced by RemoteOutput(), tick(), webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~RemoteOutput().
m_networkRequest
QNetworkRequest RemoteOutput::m_networkRequest private
Definition at line 182 of file remoteoutput.h.
Referenced by tick(), webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_remoteOutputThread
RemoteOutputThread* RemoteOutput::m_remoteOutputThread private
Definition at line 174 of file remoteoutput.h.
Referenced by analyzeApiReply(), applySettings(), handleMessage(), start(), stop(), and webapiFormatDeviceReport().
m_settings
RemoteOutputSettings RemoteOutput::m_settings private
Definition at line 172 of file remoteoutput.h.
Referenced by applySettings(), deserialize(), getSampleRate(), handleMessage(), init(), serialize(), start(), tick(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_startingTimeStamp
std::time_t RemoteOutput::m_startingTimeStamp private
Definition at line 176 of file remoteoutput.h.
Referenced by getStartingTimeStamp().
m_tickCount
uint32_t RemoteOutput::m_tickCount private
Definition at line 178 of file remoteoutput.h.
Referenced by tick().
m_tickMultiplier
uint32_t RemoteOutput::m_tickMultiplier private
Definition at line 179 of file remoteoutput.h.
Referenced by applySettings(), and tick().
NbSamplesForRateCorrection
const uint32_t RemoteOutput::NbSamplesForRateCorrection = 5000000 static private
Definition at line 192 of file remoteoutput.h.
Referenced by analyzeApiReply(), and applySettings().
The documentation for this class was generated from the following files:
plugins/samplesink/remoteoutput/remoteoutput.h
plugins/samplesink/remoteoutput/remoteoutput.cpp