SDRAngel: SWGSDRangel Namespace Reference
SWGSDRangel Namespace Reference
Classes
class SWGAirspyHFReport
class SWGAirspyHFSettings
class SWGAirspyReport
class SWGAirspySettings
class SWGAMBEDevice
class SWGAMBEDevices
class SWGAMDemodReport
class SWGAMDemodSettings
class SWGAMModReport
class SWGAMModSettings
class SWGArgInfo
class SWGArgValue
class SWGATVModReport
class SWGATVModSettings
class SWGAudioDevices
class SWGAudioInputDevice
class SWGAudioOutputDevice
class SWGBandwidth
class SWGBFMDemodReport
class SWGBFMDemodSettings
class SWGBladeRF1InputSettings
class SWGBladeRF1OutputSettings
class SWGBladeRF2InputReport
class SWGBladeRF2InputSettings
class SWGBladeRF2OutputReport
class SWGBladeRF2OutputSettings
class SWGChannel
class SWGChannelConfig
class SWGChannelListItem
class SWGChannelReport
class SWGChannelsDetail
class SWGChannelSettings
class SWGChannelSettings_2
class SWGCommand
class SWGComplex
class SWGCWKeyerSettings
class SWGDeviceConfig
class SWGDeviceListItem
class SWGDeviceReport
class SWGDeviceSet
class SWGDeviceSetApi
class SWGDeviceSetList
class SWGDeviceSettings
class SWGDeviceSettings_2
class SWGDeviceState
class SWGDSDDemodReport
class SWGDSDDemodSettings
class SWGDVSerialDevice
class SWGDVSerialDevices
class SWGErrorResponse
class SWGFCDProPlusSettings
class SWGFCDProSettings
class SWGFileInputReport
class SWGFileInputSettings
class SWGFileSourceReport
class SWGFileSourceSettings
class SWGFreeDVDemodReport
class SWGFreeDVDemodSettings
class SWGFreeDVModReport
class SWGFreeDVModSettings
class SWGFreqTrackerReport
class SWGFreqTrackerSettings
class SWGFrequency
class SWGFrequencyBand
class SWGFrequencyRange
class SWGGain
class SWGGLSpectrum
class SWGHackRFInputSettings
class SWGHackRFOutputSettings
class SWGHttpRequestInput
class SWGHttpRequestInputFileElement
class SWGHttpRequestWorker
class SWGInstanceApi
class SWGInstanceChannelsResponse
class SWGInstanceConfigResponse
class SWGInstanceDevicesResponse
class SWGInstanceSummaryResponse
class SWGKiwiSDRReport
class SWGKiwiSDRSettings
class SWGLimeSdrInputReport
class SWGLimeSdrInputSettings
class SWGLimeSdrOutputReport
class SWGLimeSdrOutputSettings
class SWGLocalInputReport
class SWGLocalInputSettings
class SWGLocalOutputReport
class SWGLocalOutputSettings
class SWGLocalSinkSettings
class SWGLocalSourceSettings
class SWGLocationInformation
class SWGLoggingInfo
class SWGNamedEnum
class SWGNFMDemodReport
class SWGNFMDemodSettings
class SWGNFMModReport
class SWGNFMModSettings
class SWGObject
class SWGPerseusReport
class SWGPerseusSettings
class SWGPlutoSdrInputReport
class SWGPlutoSdrInputSettings
class SWGPlutoSdrOutputReport
class SWGPlutoSdrOutputSettings
class SWGPreferences
class SWGPreset
class SWGPresetExport
class SWGPresetGroup
class SWGPresetIdentifier
class SWGPresetImport
class SWGPresetItem
class SWGPresets
class SWGPresetTransfer
class SWGRange
class SWGRangeFloat
class SWGRDSReport
class SWGRDSReport_altFrequencies
class SWGRemoteInputReport
class SWGRemoteInputSettings
class SWGRemoteOutputReport
class SWGRemoteOutputSettings
class SWGRemoteSinkSettings
class SWGRemoteSourceReport
class SWGRemoteSourceSettings
class SWGRtlSdrReport
class SWGRtlSdrSettings
class SWGSampleRate
class SWGSamplingDevice
class SWGSDRPlayReport
class SWGSDRPlaySettings
class SWGSoapySDRFrequencySetting
class SWGSoapySDRGainSetting
class SWGSoapySDRInputSettings
class SWGSoapySDROutputSettings
class SWGSoapySDRReport
class SWGSSBDemodReport
class SWGSSBDemodSettings
class SWGSSBModReport
class SWGSSBModSettings
class SWGSuccessResponse
class SWGTestMISettings
class SWGTestMiStreamSettings
class SWGTestSourceSettings
class SWGUDPSinkReport
class SWGUDPSinkSettings
class SWGUDPSourceReport
class SWGUDPSourceSettings
class SWGWFMDemodReport
class SWGWFMDemodSettings
class SWGWFMModReport
class SWGWFMModSettings
class SWGXtrxInputReport
class SWGXtrxInputSettings
class SWGXtrxOutputReport
class SWGXtrxOutputSettings
Enumerations
enum SWGHttpRequestVarLayout { NOT_SET, ADDRESS, URL_ENCODED, MULTIPART }
Functions
void setValue (void *value, QJsonValue obj, QString type, QString complexType)
void toJsonValue (QString name, void *value, QJsonObject *output, QString type)
void toJsonArray (QList< void *> *value, QJsonObject *output, QString innerName, QString innerType)
void toJsonMap (QMap< QString, void *> *value, QJsonObject *output, QString innerName, QString innerType)
QString stringValue (QString *value)
QString stringValue (qint32 value)
QString stringValue (qint64 value)
QString stringValue (bool value)
bool isCompatibleJsonValue (QString type)
void * create (QString type)
void * create (QString json, QString type)
Detailed Description
SDRangel This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube — Limitations and specifcities: * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method. * Preset import and export from/to file is a server only feature. * Device set focus is a GUI only feature. * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time —
OpenAPI spec version: 4.11.6 Contact: f4exb.nosp@m.06@g.nosp@m.mail..nosp@m.com
NOTE: This class is auto generated by the swagger code generator program. https://github.com/swagger-api/swagger-codegen.git Do not edit the class manually.
SDRangel This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube — Limitations and specifcities: * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method. * Preset import and export from/to file is a server only feature. * Device set focus is a GUI only feature. * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time —
OpenAPI spec version: 4.11.3 Contact: f4exb.nosp@m.06@g.nosp@m.mail..nosp@m.com
NOTE: This class is auto generated by the swagger code generator program. https://github.com/swagger-api/swagger-codegen.git Do not edit the class manually.
SDRangel This is the web REST/JSON API of SDRangel SDR software. SDRangel is an Open Source Qt5/OpenGL 3.0+ (4.3+ in Windows) GUI and server Software Defined Radio and signal analyzer in software. It supports Airspy, BladeRF, HackRF, LimeSDR, PlutoSDR, RTL-SDR, SDRplay RSP1 and FunCube — Limitations and specifcities: * In SDRangel GUI the first Rx device set cannot be deleted. Conversely the server starts with no device sets and its number of device sets can be reduced to zero by as many calls as necessary to /sdrangel/deviceset with DELETE method. * Preset import and export from/to file is a server only feature. * Device set focus is a GUI only feature. * The following channels are not implemented (status 501 is returned): ATV and DATV demodulators, Channel Analyzer NG, LoRa demodulator * The device settings and report structures contains only the sub-structure corresponding to the device type. The DeviceSettings and DeviceReport structures documented here shows all of them but only one will be or should be present at a time * The channel settings and report structures contains only the sub-structure corresponding to the channel type. The ChannelSettings and ChannelReport structures documented here shows all of them but only one will be or should be present at a time —
OpenAPI spec version: 4.11.6 Contact: f4exb.nosp@m.06@g.nosp@m.mail..nosp@m.com
NOTE: This class is auto generated by the swagger code generator program. https://github.com/swagger-api/swagger-codegen.git Do not edit the class manually. Based on http://www.creativepulse.gr/en/blog/2014/restful-api-requests-using-qt-cpp-for-linux-mac-osx-ms-windows By Alex Stylianos
Enumeration Type Documentation
SWGHttpRequestVarLayout
enum SWGSDRangel::SWGHttpRequestVarLayout
Enumerator
NOT_SET
ADDRESS
URL_ENCODED
MULTIPART
Definition at line 32 of file SWGHttpRequest.h.
 {NOT_SET, ADDRESS, URL_ENCODED, MULTIPART};
Function Documentation
create() [1/2]
void* SWGSDRangel::create (QString type) inline
Definition at line 166 of file SWGModelFactory.h.
Referenced by create(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelDeleteCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelPostCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelReportGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPatchCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPutCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelsReportGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDevicePutCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceReportGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunDeleteCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunPostCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsGetCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPatchCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPutCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetFocusPatchCallback(), SWGSDRangel::SWGDeviceSetApi::devicesetGetCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesGetCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBEDevicesPutCallback(), SWGSDRangel::SWGInstanceApi::instanceAMBESerialGetCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioGetCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioInputCleanupPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioInputDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioInputPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputCleanupPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceAudioOutputPatchCallback(), SWGSDRangel::SWGInstanceApi::instanceChannelsCallback(), SWGSDRangel::SWGInstanceApi::instanceConfigCallback(), SWGSDRangel::SWGInstanceApi::instanceDeleteCallback(), SWGSDRangel::SWGInstanceApi::instanceDevicesCallback(), SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetDeleteCallback(), SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetPostCallback(), SWGSDRangel::SWGInstanceApi::instanceDeviceSetsGetCallback(), SWGSDRangel::SWGInstanceApi::instanceLocationGetCallback(), SWGSDRangel::SWGInstanceApi::instanceLocationPutCallback(), SWGSDRangel::SWGInstanceApi::instanceLoggingGetCallback(), SWGSDRangel::SWGInstanceApi::instanceLoggingPutCallback(), SWGSDRangel::SWGInstanceApi::instancePresetDeleteCallback(), SWGSDRangel::SWGInstanceApi::instancePresetFilePostCallback(), SWGSDRangel::SWGInstanceApi::instancePresetFilePutCallback(), SWGSDRangel::SWGInstanceApi::instancePresetGetCallback(), SWGSDRangel::SWGInstanceApi::instancePresetPatchCallback(), SWGSDRangel::SWGInstanceApi::instancePresetPostCallback(), SWGSDRangel::SWGInstanceApi::instancePresetPutCallback(), SWGSDRangel::SWGInstanceApi::instanceSummaryCallback(), AMBEWorker::postTest(), and setValue().
{
     if(QString("SWGAMBEDevice").compare(type) == 0) {
       return new SWGAMBEDevice();
     }
     if(QString("SWGAMBEDevices").compare(type) == 0) {
       return new SWGAMBEDevices();
     }
     if(QString("SWGAMDemodReport").compare(type) == 0) {
       return new SWGAMDemodReport();
     }
     if(QString("SWGAMDemodSettings").compare(type) == 0) {
       return new SWGAMDemodSettings();
     }
     if(QString("SWGAMModReport").compare(type) == 0) {
       return new SWGAMModReport();
     }
     if(QString("SWGAMModSettings").compare(type) == 0) {
       return new SWGAMModSettings();
     }
     if(QString("SWGATVModReport").compare(type) == 0) {
       return new SWGATVModReport();
     }
     if(QString("SWGATVModSettings").compare(type) == 0) {
       return new SWGATVModSettings();
     }
     if(QString("SWGAirspyHFReport").compare(type) == 0) {
       return new SWGAirspyHFReport();
     }
     if(QString("SWGAirspyHFSettings").compare(type) == 0) {
       return new SWGAirspyHFSettings();
     }
     if(QString("SWGAirspyReport").compare(type) == 0) {
       return new SWGAirspyReport();
     }
     if(QString("SWGAirspySettings").compare(type) == 0) {
       return new SWGAirspySettings();
     }
     if(QString("SWGArgInfo").compare(type) == 0) {
       return new SWGArgInfo();
     }
     if(QString("SWGArgValue").compare(type) == 0) {
       return new SWGArgValue();
     }
     if(QString("SWGAudioDevices").compare(type) == 0) {
       return new SWGAudioDevices();
     }
     if(QString("SWGAudioInputDevice").compare(type) == 0) {
       return new SWGAudioInputDevice();
     }
     if(QString("SWGAudioOutputDevice").compare(type) == 0) {
       return new SWGAudioOutputDevice();
     }
     if(QString("SWGBFMDemodReport").compare(type) == 0) {
       return new SWGBFMDemodReport();
     }
     if(QString("SWGBFMDemodSettings").compare(type) == 0) {
       return new SWGBFMDemodSettings();
     }
     if(QString("SWGBandwidth").compare(type) == 0) {
       return new SWGBandwidth();
     }
     if(QString("SWGBladeRF1InputSettings").compare(type) == 0) {
       return new SWGBladeRF1InputSettings();
     }
     if(QString("SWGBladeRF1OutputSettings").compare(type) == 0) {
       return new SWGBladeRF1OutputSettings();
     }
     if(QString("SWGBladeRF2InputReport").compare(type) == 0) {
       return new SWGBladeRF2InputReport();
     }
     if(QString("SWGBladeRF2InputSettings").compare(type) == 0) {
       return new SWGBladeRF2InputSettings();
     }
     if(QString("SWGBladeRF2OutputReport").compare(type) == 0) {
       return new SWGBladeRF2OutputReport();
     }
     if(QString("SWGBladeRF2OutputSettings").compare(type) == 0) {
       return new SWGBladeRF2OutputSettings();
     }
     if(QString("SWGCWKeyerSettings").compare(type) == 0) {
       return new SWGCWKeyerSettings();
     }
     if(QString("SWGChannel").compare(type) == 0) {
       return new SWGChannel();
     }
     if(QString("SWGChannelConfig").compare(type) == 0) {
       return new SWGChannelConfig();
     }
     if(QString("SWGChannelListItem").compare(type) == 0) {
       return new SWGChannelListItem();
     }
     if(QString("SWGChannelReport").compare(type) == 0) {
       return new SWGChannelReport();
     }
     if(QString("SWGChannelSettings").compare(type) == 0) {
       return new SWGChannelSettings();
     }
     if(QString("SWGChannelsDetail").compare(type) == 0) {
       return new SWGChannelsDetail();
     }
     if(QString("SWGCommand").compare(type) == 0) {
       return new SWGCommand();
     }
     if(QString("SWGComplex").compare(type) == 0) {
       return new SWGComplex();
     }
     if(QString("SWGDSDDemodReport").compare(type) == 0) {
       return new SWGDSDDemodReport();
     }
     if(QString("SWGDSDDemodSettings").compare(type) == 0) {
       return new SWGDSDDemodSettings();
     }
     if(QString("SWGDVSerialDevice").compare(type) == 0) {
       return new SWGDVSerialDevice();
     }
     if(QString("SWGDVSerialDevices").compare(type) == 0) {
       return new SWGDVSerialDevices();
     }
     if(QString("SWGDeviceConfig").compare(type) == 0) {
       return new SWGDeviceConfig();
     }
     if(QString("SWGDeviceListItem").compare(type) == 0) {
       return new SWGDeviceListItem();
     }
     if(QString("SWGDeviceReport").compare(type) == 0) {
       return new SWGDeviceReport();
     }
     if(QString("SWGDeviceSet").compare(type) == 0) {
       return new SWGDeviceSet();
     }
     if(QString("SWGDeviceSetList").compare(type) == 0) {
       return new SWGDeviceSetList();
     }
     if(QString("SWGDeviceSettings").compare(type) == 0) {
       return new SWGDeviceSettings();
     }
     if(QString("SWGDeviceState").compare(type) == 0) {
       return new SWGDeviceState();
     }
     if(QString("SWGErrorResponse").compare(type) == 0) {
       return new SWGErrorResponse();
     }
     if(QString("SWGFCDProPlusSettings").compare(type) == 0) {
       return new SWGFCDProPlusSettings();
     }
     if(QString("SWGFCDProSettings").compare(type) == 0) {
       return new SWGFCDProSettings();
     }
     if(QString("SWGFileInputReport").compare(type) == 0) {
       return new SWGFileInputReport();
     }
     if(QString("SWGFileInputSettings").compare(type) == 0) {
       return new SWGFileInputSettings();
     }
     if(QString("SWGFileSourceReport").compare(type) == 0) {
       return new SWGFileSourceReport();
     }
     if(QString("SWGFileSourceSettings").compare(type) == 0) {
       return new SWGFileSourceSettings();
     }
     if(QString("SWGFreeDVDemodReport").compare(type) == 0) {
       return new SWGFreeDVDemodReport();
     }
     if(QString("SWGFreeDVDemodSettings").compare(type) == 0) {
       return new SWGFreeDVDemodSettings();
     }
     if(QString("SWGFreeDVModReport").compare(type) == 0) {
       return new SWGFreeDVModReport();
     }
     if(QString("SWGFreeDVModSettings").compare(type) == 0) {
       return new SWGFreeDVModSettings();
     }
     if(QString("SWGFreqTrackerReport").compare(type) == 0) {
       return new SWGFreqTrackerReport();
     }
     if(QString("SWGFreqTrackerSettings").compare(type) == 0) {
       return new SWGFreqTrackerSettings();
     }
     if(QString("SWGFrequency").compare(type) == 0) {
       return new SWGFrequency();
     }
     if(QString("SWGFrequencyBand").compare(type) == 0) {
       return new SWGFrequencyBand();
     }
     if(QString("SWGFrequencyRange").compare(type) == 0) {
       return new SWGFrequencyRange();
     }
     if(QString("SWGGLSpectrum").compare(type) == 0) {
       return new SWGGLSpectrum();
     }
     if(QString("SWGGain").compare(type) == 0) {
       return new SWGGain();
     }
     if(QString("SWGHackRFInputSettings").compare(type) == 0) {
       return new SWGHackRFInputSettings();
     }
     if(QString("SWGHackRFOutputSettings").compare(type) == 0) {
       return new SWGHackRFOutputSettings();
     }
     if(QString("SWGInstanceChannelsResponse").compare(type) == 0) {
       return new SWGInstanceChannelsResponse();
     }
     if(QString("SWGInstanceConfigResponse").compare(type) == 0) {
       return new SWGInstanceConfigResponse();
     }
     if(QString("SWGInstanceDevicesResponse").compare(type) == 0) {
       return new SWGInstanceDevicesResponse();
     }
     if(QString("SWGInstanceSummaryResponse").compare(type) == 0) {
       return new SWGInstanceSummaryResponse();
     }
     if(QString("SWGKiwiSDRReport").compare(type) == 0) {
       return new SWGKiwiSDRReport();
     }
     if(QString("SWGKiwiSDRSettings").compare(type) == 0) {
       return new SWGKiwiSDRSettings();
     }
     if(QString("SWGLimeSdrInputReport").compare(type) == 0) {
       return new SWGLimeSdrInputReport();
     }
     if(QString("SWGLimeSdrInputSettings").compare(type) == 0) {
       return new SWGLimeSdrInputSettings();
     }
     if(QString("SWGLimeSdrOutputReport").compare(type) == 0) {
       return new SWGLimeSdrOutputReport();
     }
     if(QString("SWGLimeSdrOutputSettings").compare(type) == 0) {
       return new SWGLimeSdrOutputSettings();
     }
     if(QString("SWGLocalInputReport").compare(type) == 0) {
       return new SWGLocalInputReport();
     }
     if(QString("SWGLocalInputSettings").compare(type) == 0) {
       return new SWGLocalInputSettings();
     }
     if(QString("SWGLocalOutputReport").compare(type) == 0) {
       return new SWGLocalOutputReport();
     }
     if(QString("SWGLocalOutputSettings").compare(type) == 0) {
       return new SWGLocalOutputSettings();
     }
     if(QString("SWGLocalSinkSettings").compare(type) == 0) {
       return new SWGLocalSinkSettings();
     }
     if(QString("SWGLocalSourceSettings").compare(type) == 0) {
       return new SWGLocalSourceSettings();
     }
     if(QString("SWGLocationInformation").compare(type) == 0) {
       return new SWGLocationInformation();
     }
     if(QString("SWGLoggingInfo").compare(type) == 0) {
       return new SWGLoggingInfo();
     }
     if(QString("SWGNFMDemodReport").compare(type) == 0) {
       return new SWGNFMDemodReport();
     }
     if(QString("SWGNFMDemodSettings").compare(type) == 0) {
       return new SWGNFMDemodSettings();
     }
     if(QString("SWGNFMModReport").compare(type) == 0) {
       return new SWGNFMModReport();
     }
     if(QString("SWGNFMModSettings").compare(type) == 0) {
       return new SWGNFMModSettings();
     }
     if(QString("SWGNamedEnum").compare(type) == 0) {
       return new SWGNamedEnum();
     }
     if(QString("SWGPerseusReport").compare(type) == 0) {
       return new SWGPerseusReport();
     }
     if(QString("SWGPerseusSettings").compare(type) == 0) {
       return new SWGPerseusSettings();
     }
     if(QString("SWGPlutoSdrInputReport").compare(type) == 0) {
       return new SWGPlutoSdrInputReport();
     }
     if(QString("SWGPlutoSdrInputSettings").compare(type) == 0) {
       return new SWGPlutoSdrInputSettings();
     }
     if(QString("SWGPlutoSdrOutputReport").compare(type) == 0) {
       return new SWGPlutoSdrOutputReport();
     }
     if(QString("SWGPlutoSdrOutputSettings").compare(type) == 0) {
       return new SWGPlutoSdrOutputSettings();
     }
     if(QString("SWGPreferences").compare(type) == 0) {
       return new SWGPreferences();
     }
     if(QString("SWGPreset").compare(type) == 0) {
       return new SWGPreset();
     }
     if(QString("SWGPresetExport").compare(type) == 0) {
       return new SWGPresetExport();
     }
     if(QString("SWGPresetGroup").compare(type) == 0) {
       return new SWGPresetGroup();
     }
     if(QString("SWGPresetIdentifier").compare(type) == 0) {
       return new SWGPresetIdentifier();
     }
     if(QString("SWGPresetImport").compare(type) == 0) {
       return new SWGPresetImport();
     }
     if(QString("SWGPresetItem").compare(type) == 0) {
       return new SWGPresetItem();
     }
     if(QString("SWGPresetTransfer").compare(type) == 0) {
       return new SWGPresetTransfer();
     }
     if(QString("SWGPresets").compare(type) == 0) {
       return new SWGPresets();
     }
     if(QString("SWGRDSReport").compare(type) == 0) {
       return new SWGRDSReport();
     }
     if(QString("SWGRDSReport_altFrequencies").compare(type) == 0) {
       return new SWGRDSReport_altFrequencies();
     }
     if(QString("SWGRange").compare(type) == 0) {
       return new SWGRange();
     }
     if(QString("SWGRangeFloat").compare(type) == 0) {
       return new SWGRangeFloat();
     }
     if(QString("SWGRemoteInputReport").compare(type) == 0) {
       return new SWGRemoteInputReport();
     }
     if(QString("SWGRemoteInputSettings").compare(type) == 0) {
       return new SWGRemoteInputSettings();
     }
     if(QString("SWGRemoteOutputReport").compare(type) == 0) {
       return new SWGRemoteOutputReport();
     }
     if(QString("SWGRemoteOutputSettings").compare(type) == 0) {
       return new SWGRemoteOutputSettings();
     }
     if(QString("SWGRemoteSinkSettings").compare(type) == 0) {
       return new SWGRemoteSinkSettings();
     }
     if(QString("SWGRemoteSourceReport").compare(type) == 0) {
       return new SWGRemoteSourceReport();
     }
     if(QString("SWGRemoteSourceSettings").compare(type) == 0) {
       return new SWGRemoteSourceSettings();
     }
     if(QString("SWGRtlSdrReport").compare(type) == 0) {
       return new SWGRtlSdrReport();
     }
     if(QString("SWGRtlSdrSettings").compare(type) == 0) {
       return new SWGRtlSdrSettings();
     }
     if(QString("SWGSDRPlayReport").compare(type) == 0) {
       return new SWGSDRPlayReport();
     }
     if(QString("SWGSDRPlaySettings").compare(type) == 0) {
       return new SWGSDRPlaySettings();
     }
     if(QString("SWGSSBDemodReport").compare(type) == 0) {
       return new SWGSSBDemodReport();
     }
     if(QString("SWGSSBDemodSettings").compare(type) == 0) {
       return new SWGSSBDemodSettings();
     }
     if(QString("SWGSSBModReport").compare(type) == 0) {
       return new SWGSSBModReport();
     }
     if(QString("SWGSSBModSettings").compare(type) == 0) {
       return new SWGSSBModSettings();
     }
     if(QString("SWGSampleRate").compare(type) == 0) {
       return new SWGSampleRate();
     }
     if(QString("SWGSamplingDevice").compare(type) == 0) {
       return new SWGSamplingDevice();
     }
     if(QString("SWGSoapySDRFrequencySetting").compare(type) == 0) {
       return new SWGSoapySDRFrequencySetting();
     }
     if(QString("SWGSoapySDRGainSetting").compare(type) == 0) {
       return new SWGSoapySDRGainSetting();
     }
     if(QString("SWGSoapySDRInputSettings").compare(type) == 0) {
       return new SWGSoapySDRInputSettings();
     }
     if(QString("SWGSoapySDROutputSettings").compare(type) == 0) {
       return new SWGSoapySDROutputSettings();
     }
     if(QString("SWGSoapySDRReport").compare(type) == 0) {
       return new SWGSoapySDRReport();
     }
     if(QString("SWGSuccessResponse").compare(type) == 0) {
       return new SWGSuccessResponse();
     }
     if(QString("SWGTestMISettings").compare(type) == 0) {
       return new SWGTestMISettings();
     }
     if(QString("SWGTestMiStreamSettings").compare(type) == 0) {
       return new SWGTestMiStreamSettings();
     }
     if(QString("SWGTestSourceSettings").compare(type) == 0) {
       return new SWGTestSourceSettings();
     }
     if(QString("SWGUDPSinkReport").compare(type) == 0) {
       return new SWGUDPSinkReport();
     }
     if(QString("SWGUDPSinkSettings").compare(type) == 0) {
       return new SWGUDPSinkSettings();
     }
     if(QString("SWGUDPSourceReport").compare(type) == 0) {
       return new SWGUDPSourceReport();
     }
     if(QString("SWGUDPSourceSettings").compare(type) == 0) {
       return new SWGUDPSourceSettings();
     }
     if(QString("SWGWFMDemodReport").compare(type) == 0) {
       return new SWGWFMDemodReport();
     }
     if(QString("SWGWFMDemodSettings").compare(type) == 0) {
       return new SWGWFMDemodSettings();
     }
     if(QString("SWGWFMModReport").compare(type) == 0) {
       return new SWGWFMModReport();
     }
     if(QString("SWGWFMModSettings").compare(type) == 0) {
       return new SWGWFMModSettings();
     }
     if(QString("SWGXtrxInputReport").compare(type) == 0) {
       return new SWGXtrxInputReport();
     }
     if(QString("SWGXtrxInputSettings").compare(type) == 0) {
       return new SWGXtrxInputSettings();
     }
     if(QString("SWGXtrxOutputReport").compare(type) == 0) {
       return new SWGXtrxOutputReport();
     }
     if(QString("SWGXtrxOutputSettings").compare(type) == 0) {
       return new SWGXtrxOutputSettings();
     }
     return nullptr;
   }
create() [2/2]
void* SWGSDRangel::create (QString json, QString type) inline
Definition at line 609 of file SWGModelFactory.h.
References create(), and SWGSDRangel::SWGObject::fromJson().
{
     void* val = create(type);
     if(val != nullptr) {
       SWGObject* obj = static_cast<SWGObject*>(val);
       return obj->fromJson(json);
     }
     if(type.startsWith("QString")) {
       return new QString();
     }
     return nullptr;
   }
isCompatibleJsonValue()
bool SWGSDRangel::isCompatibleJsonValue (QString type)
setValue()
void SWGSDRangel::setValue (void * value, QJsonValue obj, QString type, QString complexType)
Definition at line 25 of file SWGHelpers.cpp.
References create(), and SWGSDRangel::SWGObject::fromJsonObject().
Referenced by SWGSDRangel::SWGAMDemodReport::fromJsonObject(), SWGSDRangel::SWGAMModReport::fromJsonObject(), SWGSDRangel::SWGComplex::fromJsonObject(), SWGSDRangel::SWGFrequency::fromJsonObject(), SWGSDRangel::SWGFrequencyRange::fromJsonObject(), SWGSDRangel::SWGSSBDemodReport::fromJsonObject(), SWGSDRangel::SWGGain::fromJsonObject(), SWGSDRangel::SWGSSBModReport::fromJsonObject(), SWGSDRangel::SWGGLSpectrum::fromJsonObject(), SWGSDRangel::SWGTestMiStreamSettings::fromJsonObject(), SWGSDRangel::SWGUDPSinkReport::fromJsonObject(), SWGSDRangel::SWGUDPSourceReport::fromJsonObject(), SWGSDRangel::SWGWFMDemodReport::fromJsonObject(), SWGSDRangel::SWGKiwiSDRReport::fromJsonObject(), SWGSDRangel::SWGWFMModReport::fromJsonObject(), SWGSDRangel::SWGXtrxInputReport::fromJsonObject(), SWGSDRangel::SWGXtrxOutputReport::fromJsonObject(), SWGSDRangel::SWGLimeSdrInputReport::fromJsonObject(), SWGSDRangel::SWGLimeSdrOutputReport::fromJsonObject(), SWGSDRangel::SWGBandwidth::fromJsonObject(), SWGSDRangel::SWGLocalInputReport::fromJsonObject(), SWGSDRangel::SWGLocalOutputReport::fromJsonObject(), SWGSDRangel::SWGLocationInformation::fromJsonObject(), SWGSDRangel::SWGNFMDemodReport::fromJsonObject(), SWGSDRangel::SWGNFMModReport::fromJsonObject(), SWGSDRangel::SWGATVModReport::fromJsonObject(), SWGSDRangel::SWGRange::fromJsonObject(), SWGSDRangel::SWGRangeFloat::fromJsonObject(), SWGSDRangel::SWGFreeDVDemodReport::fromJsonObject(), SWGSDRangel::SWGRDSReport_altFrequencies::fromJsonObject(), SWGSDRangel::SWGRemoteOutputReport::fromJsonObject(), SWGSDRangel::SWGRemoteSourceReport::fromJsonObject(), SWGSDRangel::SWGFreeDVModReport::fromJsonObject(), SWGSDRangel::SWGSampleRate::fromJsonObject(), SWGSDRangel::SWGFreqTrackerReport::fromJsonObject(), SWGSDRangel::SWGXtrxOutputSettings::fromJsonObject(), SWGSDRangel::SWGFileSourceSettings::fromJsonObject(), SWGSDRangel::SWGRemoteInputSettings::fromJsonObject(), SWGSDRangel::SWGXtrxInputSettings::fromJsonObject(), SWGSDRangel::SWGSSBDemodSettings::fromJsonObject(), SWGSDRangel::SWGFrequencyBand::fromJsonObject(), SWGSDRangel::SWGFileInputSettings::fromJsonObject(), SWGSDRangel::SWGPresetTransfer::fromJsonObject(), SWGSDRangel::SWGHackRFInputSettings::fromJsonObject(), SWGSDRangel::SWGTestSourceSettings::fromJsonObject(), SWGSDRangel::SWGPresetItem::fromJsonObject(), SWGSDRangel::SWGHackRFOutputSettings::fromJsonObject(), SWGSDRangel::SWGUDPSinkSettings::fromJsonObject(), SWGSDRangel::SWGUDPSourceSettings::fromJsonObject(), SWGSDRangel::SWGSuccessResponse::fromJsonObject(), SWGSDRangel::SWGWFMDemodSettings::fromJsonObject(), SWGSDRangel::SWGATVModSettings::fromJsonObject(), SWGSDRangel::SWGPlutoSdrOutputSettings::fromJsonObject(), SWGSDRangel::SWGAudioInputDevice::fromJsonObject(), SWGSDRangel::SWGPlutoSdrInputSettings::fromJsonObject(), SWGSDRangel::SWGCommand::fromJsonObject(), SWGSDRangel::SWGPerseusSettings::fromJsonObject(), SWGSDRangel::SWGAudioOutputDevice::fromJsonObject(), SWGSDRangel::SWGKiwiSDRSettings::fromJsonObject(), SWGSDRangel::SWGCWKeyerSettings::fromJsonObject(), SWGSDRangel::SWGNFMDemodSettings::fromJsonObject(), SWGSDRangel::SWGLimeSdrInputSettings::fromJsonObject(), SWGSDRangel::SWGDeviceListItem::fromJsonObject(), SWGSDRangel::SWGLimeSdrOutputSettings::fromJsonObject(), SWGSDRangel::SWGLocalSourceSettings::fromJsonObject(), SWGSDRangel::SWGAirspyHFSettings::fromJsonObject(), SWGSDRangel::SWGLocalInputSettings::fromJsonObject(), SWGSDRangel::SWGLocalOutputSettings::fromJsonObject(), SWGSDRangel::SWGLocalSinkSettings::fromJsonObject(), SWGSDRangel::SWGBFMDemodReport::fromJsonObject(), SWGSDRangel::SWGAMDemodSettings::fromJsonObject(), SWGSDRangel::SWGLoggingInfo::fromJsonObject(), SWGSDRangel::SWGNamedEnum::fromJsonObject(), SWGSDRangel::SWGBFMDemodSettings::fromJsonObject(), SWGSDRangel::SWGBladeRF1InputSettings::fromJsonObject(), SWGSDRangel::SWGDeviceState::fromJsonObject(), SWGSDRangel::SWGDSDDemodReport::fromJsonObject(), SWGSDRangel::SWGRemoteSinkSettings::fromJsonObject(), SWGSDRangel::SWGSDRPlaySettings::fromJsonObject(), SWGSDRangel::SWGDSDDemodSettings::fromJsonObject(), SWGSDRangel::SWGDVSerialDevice::fromJsonObject(), SWGSDRangel::SWGPlutoSdrInputReport::fromJsonObject(), SWGSDRangel::SWGPlutoSdrOutputReport::fromJsonObject(), SWGSDRangel::SWGErrorResponse::fromJsonObject(), SWGSDRangel::SWGPreferences::fromJsonObject(), SWGSDRangel::SWGFCDProPlusSettings::fromJsonObject(), SWGSDRangel::SWGPresetIdentifier::fromJsonObject(), SWGSDRangel::SWGPresetImport::fromJsonObject(), SWGSDRangel::SWGFreqTrackerSettings::fromJsonObject(), SWGSDRangel::SWGFCDProSettings::fromJsonObject(), SWGSDRangel::SWGAMBEDevice::fromJsonObject(), SWGSDRangel::SWGBladeRF1OutputSettings::fromJsonObject(), SWGSDRangel::SWGArgValue::fromJsonObject(), SWGSDRangel::SWGRemoteOutputSettings::fromJsonObject(), SWGSDRangel::SWGAirspySettings::fromJsonObject(), SWGSDRangel::SWGRemoteInputReport::fromJsonObject(), SWGSDRangel::SWGFileInputReport::fromJsonObject(), SWGSDRangel::SWGBladeRF2InputSettings::fromJsonObject(), SWGSDRangel::SWGFreeDVDemodSettings::fromJsonObject(), SWGSDRangel::SWGBladeRF2OutputSettings::fromJsonObject(), SWGSDRangel::SWGFileSourceReport::fromJsonObject(), SWGSDRangel::SWGSamplingDevice::fromJsonObject(), SWGSDRangel::SWGRemoteSourceSettings::fromJsonObject(), SWGSDRangel::SWGRtlSdrSettings::fromJsonObject(), SWGSDRangel::SWGChannelListItem::fromJsonObject(), SWGSDRangel::SWGChannel::fromJsonObject(), SWGSDRangel::SWGInstanceDevicesResponse::fromJsonObject(), SWGSDRangel::SWGAirspyHFReport::fromJsonObject(), SWGSDRangel::SWGSoapySDRGainSetting::fromJsonObject(), SWGSDRangel::SWGSSBModSettings::fromJsonObject(), SWGSDRangel::SWGPresets::fromJsonObject(), SWGSDRangel::SWGFreeDVModSettings::fromJsonObject(), SWGSDRangel::SWGDeviceConfig::fromJsonObject(), SWGSDRangel::SWGAMModSettings::fromJsonObject(), SWGSDRangel::SWGBladeRF2OutputReport::fromJsonObject(), SWGSDRangel::SWGNFMModSettings::fromJsonObject(), SWGSDRangel::SWGPresetExport::fromJsonObject(), SWGSDRangel::SWGWFMModSettings::fromJsonObject(), SWGSDRangel::SWGPerseusReport::fromJsonObject(), SWGSDRangel::SWGChannelsDetail::fromJsonObject(), SWGSDRangel::SWGAirspyReport::fromJsonObject(), SWGSDRangel::SWGDeviceSetList::fromJsonObject(), SWGSDRangel::SWGInstanceChannelsResponse::fromJsonObject(), SWGSDRangel::SWGDVSerialDevices::fromJsonObject(), SWGSDRangel::SWGChannelConfig::fromJsonObject(), SWGSDRangel::SWGAMBEDevices::fromJsonObject(), SWGSDRangel::SWGRtlSdrReport::fromJsonObject(), SWGSDRangel::SWGSoapySDRFrequencySetting::fromJsonObject(), SWGSDRangel::SWGDeviceSet::fromJsonObject(), SWGSDRangel::SWGArgInfo::fromJsonObject(), SWGSDRangel::SWGTestMISettings::fromJsonObject(), SWGSDRangel::SWGAudioDevices::fromJsonObject(), SWGSDRangel::SWGRDSReport::fromJsonObject(), SWGSDRangel::SWGInstanceSummaryResponse::fromJsonObject(), SWGSDRangel::SWGPresetGroup::fromJsonObject(), SWGSDRangel::SWGBladeRF2InputReport::fromJsonObject(), SWGSDRangel::SWGSoapySDROutputSettings::fromJsonObject(), SWGSDRangel::SWGInstanceConfigResponse::fromJsonObject(), SWGSDRangel::SWGSoapySDRInputSettings::fromJsonObject(), SWGSDRangel::SWGSDRPlayReport::fromJsonObject(), SWGSDRangel::SWGPreset::fromJsonObject(), SWGSDRangel::SWGSoapySDRReport::fromJsonObject(), SWGSDRangel::SWGChannelReport::fromJsonObject(), SWGSDRangel::SWGDeviceReport::fromJsonObject(), SWGSDRangel::SWGChannelSettings_2::fromJsonObject(), SWGSDRangel::SWGChannelSettings::fromJsonObject(), SWGSDRangel::SWGDeviceSettings_2::fromJsonObject(), SWGSDRangel::SWGDeviceSettings::fromJsonObject(), DynamicArgSettingGUI::getName(), and ItemSettingGUI::~ItemSettingGUI().
{
     if(value == nullptr) {
         // can't set value with a null pointer
         return;
     }
     if(QStringLiteral("bool").compare(type) == 0) {
         bool * val = static_cast<bool*>(value);
         *val = obj.toBool();
     }
     else if(QStringLiteral("qint32").compare(type) == 0) {
         qint32 *val = static_cast<qint32*>(value);
         *val = obj.toInt();
     }
     else if(QStringLiteral("qint64").compare(type) == 0) {
         qint64 *val = static_cast<qint64*>(value);
         *val = obj.toVariant().toLongLong();
     }
     else if(QStringLiteral("float").compare(type) == 0) {
         float *val = static_cast<float*>(value);
         *val = obj.toDouble();
     }
     else if(QStringLiteral("double").compare(type) == 0) {
         double *val = static_cast<double*>(value);
         *val = obj.toDouble();
     }
     else if (QStringLiteral("QString").compare(type) == 0) {
         QString **val = static_cast<QString**>(value);
         if(val != nullptr) {
             if(!obj.isNull()) {
                 // create a new value and return
                 if(*val != nullptr) delete *val;
                 *val = new QString(obj.toString());
                 return;
             }
             else {
                 // set target to nullptr
                 if(*val != nullptr) delete *val;
                 *val = nullptr;
             }
         }
         else {
             qDebug() << "Can't set value because the target pointer is nullptr";
         }
     }
     else if (QStringLiteral("QDateTime").compare(type) == 0) {
         QDateTime **val = static_cast<QDateTime**>(value);
         if(val != nullptr) {
             if(!obj.isNull()) {
                 // create a new value and return
                 if(*val != nullptr) delete *val;
                 *val = new QDateTime(QDateTime::fromString(obj.toString(), Qt::ISODate));
                 return;
             }
             else {
                 // set target to nullptr
                 if(*val != nullptr) delete *val;
                 *val = nullptr;
             }
         }
         else {
             qDebug() << "Can't set value because the target pointer is nullptr";
         }
     }
     else if (QStringLiteral("QDate").compare(type) == 0) {
         QDate **val = static_cast<QDate**>(value);
         if(val != nullptr) {
             if(!obj.isNull()) {
                 // create a new value and return
                 if(*val != nullptr) delete *val;
                 *val = new QDate(QDate::fromString(obj.toString(), Qt::ISODate));
                 return;
             }
             else {
                 // set target to nullptr
                 if(*val != nullptr) delete *val;
                 *val = nullptr;
             }
         }
         else {
             qDebug() << "Can't set value because the target pointer is nullptr";
         }
     }
     else if (QStringLiteral("QByteArray").compare(type) == 0) {
         QByteArray **val = static_cast<QByteArray**>(value);
         if(val != nullptr) {
             if(!obj.isNull()) {
                 // create a new value and return
                 if(*val != nullptr) delete *val;
                 *val = new QByteArray(QByteArray::fromBase64(QByteArray::fromStdString(obj.toString().toStdString())));
                 return;
             }
             else {
                 // set target to nullptr
                 if(*val != nullptr) delete *val;
                 *val = nullptr;
             }
         }
         else {
             qDebug() << "Can't set value because the target pointer is nullptr";
         }
     }
     else if(type.startsWith("SWG") && obj.isObject()) {
         // complex type
         QJsonObject jsonObj = obj.toObject();
         SWGObject * so = (SWGObject*)::SWGSDRangel::create(complexType);
         if(so != nullptr) {
             so->fromJsonObject(jsonObj);
             SWGObject **val = static_cast<SWGObject**>(value);
             if(*val != nullptr) delete *val;
             *val = so;
         }
     }
     else if(type.startsWith("QList") && QString("").compare(complexType) != 0 && obj.isArray()) {
         // list of values
         if(complexType.startsWith("SWG")) {
             auto output = reinterpret_cast<QList<SWGObject *> **> (value);
             for (auto item : **output) {
                 if(item != nullptr) delete item;
             }
             (*output)->clear();
             QJsonArray arr = obj.toArray();
             for (const QJsonValue & jval : arr) {
                 // it's an object
                 SWGObject * val = (SWGObject*)::SWGSDRangel::create(complexType);
                 QJsonObject t = jval.toObject();
                 val->fromJsonObject(t);
                 (*output)->append(val);
             }
         }
         else if(QStringLiteral("qint32").compare(complexType) == 0) {
             auto output = reinterpret_cast<QList<qint32> **> (value);
             (*output)->clear();
             QJsonArray arr = obj.toArray();
             for (const QJsonValue & jval : arr){
                 qint32 val;
                 ::SWGSDRangel::setValue(&val, jval, QStringLiteral("qint32"), QStringLiteral(""));
                 (*output)->push_back(val);
             }
         }
         else if(QStringLiteral("qint64").compare(complexType) == 0) {
             auto output = reinterpret_cast<QList<qint64> **> (value);
             (*output)->clear();
             QJsonArray arr = obj.toArray();
             for (const QJsonValue & jval : arr){
                 qint64 val;
                 ::SWGSDRangel::setValue(&val, jval, QStringLiteral("qint64"), QStringLiteral(""));
                 (*output)->push_back(val);
             }
         }
         else if(QStringLiteral("bool").compare(complexType) == 0) {
             auto output = reinterpret_cast<QList<bool> **> (value);
             (*output)->clear();
             QJsonArray arr = obj.toArray();
             for (const QJsonValue & jval : arr){
                 bool val;
                 ::SWGSDRangel::setValue(&val, jval, QStringLiteral("bool"), QStringLiteral(""));
                 (*output)->push_back(val);
             }
         }
         else if(QStringLiteral("float").compare(complexType) == 0) {
             auto output = reinterpret_cast<QList<float> **> (value);
             (*output)->clear();
             QJsonArray arr = obj.toArray();
             for (const QJsonValue & jval : arr){
                 float val;
                 ::SWGSDRangel::setValue(&val, jval, QStringLiteral("float"), QStringLiteral(""));
                 (*output)->push_back(val);
             }
         }
         else if(QStringLiteral("double").compare(complexType) == 0) {
             auto output = reinterpret_cast<QList<double> **> (value);
             (*output)->clear();
             QJsonArray arr = obj.toArray();
             for (const QJsonValue & jval : arr){
                 double val;
                 ::SWGSDRangel::setValue(&val, jval, QStringLiteral("double"), QStringLiteral(""));
                 (*output)->push_back(val);
             }
         }
         else if(QStringLiteral("QString").compare(complexType) == 0) {
             auto output = reinterpret_cast<QList<QString*> **> (value);
             for (auto item : **output) {
                 if(item != nullptr) delete item;
             }
             (*output)->clear();
             QJsonArray arr = obj.toArray();
             for (const QJsonValue & jval : arr){
                 QString * val = new QString();
                 ::SWGSDRangel::setValue(&val, jval, QStringLiteral("QString"), QStringLiteral(""));
                 (*output)->push_back(val);
             }
         }
         else if(QStringLiteral("QDate").compare(complexType) == 0) {
             auto output = reinterpret_cast<QList<QDate*> **> (value);
             for (auto item : **output) {
                 if(item != nullptr) delete item;
             }
             (*output)->clear();
             QJsonArray arr = obj.toArray();
             for (const QJsonValue & jval : arr){
                 QDate * val = new QDate();
                 ::SWGSDRangel::setValue(&val, jval, QStringLiteral("QDate"), QStringLiteral(""));
                 (*output)->push_back(val);
             }
         }
         else if(QStringLiteral("QDateTime").compare(complexType) == 0) {
             auto output = reinterpret_cast<QList<QDateTime*> **> (value);
             for (auto item : **output) {
                 if(item != nullptr) delete item;
             }
             (*output)->clear();
             QJsonArray arr = obj.toArray();
             for (const QJsonValue & jval : arr){
                 QDateTime * val = new QDateTime();
                 ::SWGSDRangel::setValue(&val, jval, QStringLiteral("QDateTime"), QStringLiteral(""));
                 (*output)->push_back(val);
             }
         }
     }
     else if(type.startsWith("QMap") && QString("").compare(complexType) != 0 && obj.isObject()) {
         // list of values
         if(complexType.startsWith("SWG")) {
             auto output = reinterpret_cast<QMap<QString, SWGObject*> **> (value);
             for (auto item : **output) {
                 if(item != nullptr) delete item;
             }
             (*output)->clear();
             auto varmap = obj.toObject().toVariantMap();
             if(varmap.count() > 0){
                 for(auto itemkey : varmap.keys() ){
                     auto  val = (SWGObject*)::SWGSDRangel::create(complexType);
                     auto  jsonval = QJsonValue::fromVariant(varmap.value(itemkey));
                     ::SWGSDRangel::setValue(&val, jsonval, complexType, complexType);
                     (*output)->insert(itemkey, val);
                 }
             }
         }
         else if(QStringLiteral("qint32").compare(complexType) == 0) {
             auto output = reinterpret_cast<QMap<QString, qint32> **> (value);
             (*output)->clear();
             auto varmap = obj.toObject().toVariantMap();
             if(varmap.count() > 0){
                 for(auto itemkey : varmap.keys() ){
                     qint32 val;
                     auto  jsonval = QJsonValue::fromVariant(varmap.value(itemkey));
                     ::SWGSDRangel::setValue(&val, jsonval, QStringLiteral("qint32"), QStringLiteral(""));
                     (*output)->insert( itemkey, val);
                 }
             }
         }
         else if(QStringLiteral("qint64").compare(complexType) == 0) {
             auto output = reinterpret_cast<QMap<QString, qint64> **> (value);
             (*output)->clear();
             auto varmap = obj.toObject().toVariantMap();
             if(varmap.count() > 0){
                 for(auto itemkey : varmap.keys() ){
                     qint64 val;
                     auto  jsonval = QJsonValue::fromVariant(varmap.value(itemkey));
                     ::SWGSDRangel::setValue(&val, jsonval, QStringLiteral("qint64"), QStringLiteral(""));
                     (*output)->insert( itemkey, val);
                 }
             }
         }
         else if(QStringLiteral("bool").compare(complexType) == 0) {
             auto output = reinterpret_cast<QMap<QString, bool> **> (value);
             (*output)->clear();
             auto varmap = obj.toObject().toVariantMap();
             if(varmap.count() > 0){
                 for(auto itemkey : varmap.keys() ){
                     bool val;
                     auto  jsonval = QJsonValue::fromVariant(varmap.value(itemkey));
                     ::SWGSDRangel::setValue(&val, jsonval, QStringLiteral("bool"), QStringLiteral(""));
                     (*output)->insert( itemkey, val);
                 }
             }
         }
         else if(QStringLiteral("float").compare(complexType) == 0) {
             auto output = reinterpret_cast<QMap<QString, float> **> (value);
             (*output)->clear();
             auto varmap = obj.toObject().toVariantMap();
             if(varmap.count() > 0){
                 for(auto itemkey : varmap.keys() ){
                     float val;
                     auto  jsonval = QJsonValue::fromVariant(varmap.value(itemkey));
                     ::SWGSDRangel::setValue(&val, jsonval, QStringLiteral("float"), QStringLiteral(""));
                     (*output)->insert( itemkey, val);
                 }
             }
         }
         else if(QStringLiteral("double").compare(complexType) == 0) {
             auto output = reinterpret_cast<QMap<QString, double> **> (value);
             (*output)->clear();
             auto varmap = obj.toObject().toVariantMap();
             if(varmap.count() > 0){
                 for(auto itemkey : varmap.keys() ){
                     double val;
                     auto  jsonval = QJsonValue::fromVariant(varmap.value(itemkey));
                     ::SWGSDRangel::setValue(&val, jsonval, QStringLiteral("double"), QStringLiteral(""));
                     (*output)->insert( itemkey, val);
                 }
             }
         }
         else if(QStringLiteral("QString").compare(complexType) == 0) {
             auto output = reinterpret_cast<QMap<QString, QString*> **> (value);
             for (auto item : **output) {
                 if(item != nullptr) delete item;
             }
             (*output)->clear();
             auto varmap = obj.toObject().toVariantMap();
             if(varmap.count() > 0){
                 for(auto itemkey : varmap.keys() ){
                     QString * val = new QString();
                     auto  jsonval = QJsonValue::fromVariant(varmap.value(itemkey));
                     ::SWGSDRangel::setValue(&val, jsonval, QStringLiteral("QString"), QStringLiteral(""));
                     (*output)->insert( itemkey, val);
                 }
             }
         }
         else if(QStringLiteral("QDate").compare(complexType) == 0) {
             auto output = reinterpret_cast<QMap<QString, QDate*> **> (value);
             for (auto item : **output) {
                 if(item != nullptr) delete item;
             }
             (*output)->clear();
             auto varmap = obj.toObject().toVariantMap();
             if(varmap.count() > 0){
                 for(auto itemkey : varmap.keys() ){
                     QDate * val = new QDate();
                     auto  jsonval = QJsonValue::fromVariant(varmap.value(itemkey));
                     ::SWGSDRangel::setValue(&val, jsonval, QStringLiteral("QDate"), QStringLiteral(""));
                     (*output)->insert( itemkey, val);
                 }
             }
         }
          else if(QStringLiteral("QDateTime").compare(complexType) == 0) {
             auto output = reinterpret_cast<QMap<QString, QDateTime*> **> (value);
             for (auto item : **output) {
                 if(item != nullptr) delete item;
             }
             (*output)->clear();
             auto varmap = obj.toObject().toVariantMap();
             if(varmap.count() > 0){
                 for(auto itemkey : varmap.keys() ){
                     QDateTime * val = new QDateTime();
                     auto  jsonval = QJsonValue::fromVariant(varmap.value(itemkey));
                     ::SWGSDRangel::setValue(&val, jsonval, QStringLiteral("QDateTime"), QStringLiteral(""));
                     (*output)->insert( itemkey, val);
                 }
             }
         }
     }
 }
stringValue() [1/4]
QString SWGSDRangel::stringValue (QString * value)
Definition at line 578 of file SWGHelpers.cpp.
Referenced by SWGSDRangel::SWGDeviceSetApi::devicesetChannelDelete(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelPost(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelReportGet(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsGet(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPatch(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPut(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelsReportGet(), SWGSDRangel::SWGDeviceSetApi::devicesetDevicePut(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceReportGet(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunDelete(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunGet(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceRunPost(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsGet(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPatch(), SWGSDRangel::SWGDeviceSetApi::devicesetDeviceSettingsPut(), SWGSDRangel::SWGDeviceSetApi::devicesetFocusPatch(), SWGSDRangel::SWGDeviceSetApi::devicesetGet(), SWGSDRangel::SWGInstanceApi::instanceChannels(), SWGSDRangel::SWGInstanceApi::instanceDevices(), and SWGSDRangel::SWGDeviceSetApi::instanceDeviceSetPost().
{
     QString* str = static_cast<QString*>(value);
     return QString(*str);
 }
stringValue() [2/4]
QString SWGSDRangel::stringValue (qint32 value)
Definition at line 584 of file SWGHelpers.cpp.
{
     return QString::number(value);
 }
stringValue() [3/4]
QString SWGSDRangel::stringValue (qint64 value)
Definition at line 589 of file SWGHelpers.cpp.
{
     return QString::number(value);
 }
stringValue() [4/4]
QString SWGSDRangel::stringValue (bool value)
Definition at line 594 of file SWGHelpers.cpp.
{
     return QString(value ? "true" : "false");
 }
toJsonArray()
void SWGSDRangel::toJsonArray (QList< void *> * value, QJsonObject * output, QString innerName, QString innerType)
Definition at line 445 of file SWGHelpers.cpp.
References SWGSDRangel::SWGObject::asJsonObject().
Referenced by SWGSDRangel::SWGAirspyHFReport::asJsonObject(), SWGSDRangel::SWGAirspyReport::asJsonObject(), SWGSDRangel::SWGDeviceSetList::asJsonObject(), SWGSDRangel::SWGPresets::asJsonObject(), SWGSDRangel::SWGRtlSdrReport::asJsonObject(), SWGSDRangel::SWGDVSerialDevices::asJsonObject(), SWGSDRangel::SWGInstanceChannelsResponse::asJsonObject(), SWGSDRangel::SWGAMBEDevices::asJsonObject(), SWGSDRangel::SWGInstanceDevicesResponse::asJsonObject(), SWGSDRangel::SWGChannelsDetail::asJsonObject(), SWGSDRangel::SWGPerseusReport::asJsonObject(), SWGSDRangel::SWGPresetGroup::asJsonObject(), SWGSDRangel::SWGDeviceSet::asJsonObject(), SWGSDRangel::SWGRDSReport::asJsonObject(), SWGSDRangel::SWGSoapySDRFrequencySetting::asJsonObject(), SWGSDRangel::SWGAudioDevices::asJsonObject(), SWGSDRangel::SWGArgInfo::asJsonObject(), SWGSDRangel::SWGTestMISettings::asJsonObject(), SWGSDRangel::SWGSoapySDRInputSettings::asJsonObject(), SWGSDRangel::SWGInstanceConfigResponse::asJsonObject(), SWGSDRangel::SWGBladeRF2InputReport::asJsonObject(), SWGSDRangel::SWGSoapySDROutputSettings::asJsonObject(), SWGSDRangel::SWGSDRPlayReport::asJsonObject(), SWGSDRangel::SWGPreset::asJsonObject(), and SWGSDRangel::SWGSoapySDRReport::asJsonObject().
{
     if((value == nullptr) || (output == nullptr)) {
         return;
     }
     QJsonArray outputarray;
     if(innerType.startsWith("SWG")){
         for(void* obj : *value) {
             SWGObject *SWGobject = reinterpret_cast<SWGObject *>(obj);
             if(SWGobject != nullptr)
             {
                 QJsonObject* o = SWGobject->asJsonObject();
                 outputarray.append(*o);
                 delete o;
             }
         }
     }
     else if(QStringLiteral("QString").compare(innerType) == 0) {
         for(QString* obj : *(reinterpret_cast<QList<QString*>*>(value))){
             outputarray.append(QJsonValue(*obj));
         }
     }
     else if(QStringLiteral("QDate").compare(innerType) == 0) {
         for(QDate* obj : *(reinterpret_cast<QList<QDate*>*>(value))){
             outputarray.append(QJsonValue(obj->toString(Qt::ISODate)));
         }
     }
     else if(QStringLiteral("QDateTime").compare(innerType) == 0) {
         for(QDateTime* obj : *(reinterpret_cast<QList<QDateTime*>*>(value))){
             outputarray.append(QJsonValue(obj->toString(Qt::ISODate)));        }
     }
     else if(QStringLiteral("QByteArray").compare(innerType) == 0) {
         for(QByteArray* obj : *(reinterpret_cast<QList<QByteArray*>*>(value))){
             outputarray.append(QJsonValue(QString(obj->toBase64())));
         }
     }
     else if(QStringLiteral("qint32").compare(innerType) == 0) {
         for(qint32 obj : *(reinterpret_cast<QList<qint32>*>(value)))
             outputarray.append(QJsonValue(obj));
     }
     else if(QStringLiteral("qint64").compare(innerType) == 0) {
         for(qint64 obj : *(reinterpret_cast<QList<qint64>*>(value)))
             outputarray.append(QJsonValue(obj));
     }
     else if(QStringLiteral("bool").compare(innerType) == 0) {
         for(bool obj : *(reinterpret_cast<QList<bool>*>(value)))
             outputarray.append(QJsonValue(obj));
     }
     else if(QStringLiteral("float").compare(innerType) == 0) {
         for(float obj : *(reinterpret_cast<QList<float>*>(value)))
             outputarray.append(QJsonValue(obj));
     }
     else if(QStringLiteral("double").compare(innerType) == 0) {
         for(double obj : *(reinterpret_cast<QList<double>*>(value)))
             outputarray.append(QJsonValue(obj));
     }
     output->insert(innerName, outputarray);
 }
toJsonMap()
void SWGSDRangel::toJsonMap (QMap< QString, void *> * value, QJsonObject * output, QString innerName, QString innerType)
Definition at line 504 of file SWGHelpers.cpp.
References toJsonValue().
{
     if((value == nullptr) || (output == nullptr)) {
         return;
     }
     QJsonObject mapobj;
     if(innerType.startsWith("SWG")){
         auto items = reinterpret_cast< QMap<QString, SWGObject*> *>(value);
         for(auto itemkey: items->keys()) {
             ::SWGSDRangel::toJsonValue(itemkey, items->value(itemkey), &mapobj, innerType);
         }
     }
     else if(QStringLiteral("QString").compare(innerType) == 0) {
         auto items = reinterpret_cast< QMap<QString, QString*> *>(value);
         for(auto itemkey: items->keys()) {
             ::SWGSDRangel::toJsonValue(itemkey, items->value(itemkey), &mapobj, innerType);
         }
     }
     else if(QStringLiteral("QDate").compare(innerType) == 0) {
         auto items = reinterpret_cast< QMap<QString, QDate*> *>(value);
         for(auto itemkey: items->keys()) {
             ::SWGSDRangel::toJsonValue(itemkey, items->value(itemkey), &mapobj, innerType);
         }
     }
     else if(QStringLiteral("QDateTime").compare(innerType) == 0) {
         auto items = reinterpret_cast< QMap<QString, QDateTime*> *>(value);
         for(auto itemkey: items->keys()) {
             ::SWGSDRangel::toJsonValue(itemkey, items->value(itemkey), &mapobj, innerType);
         }
     }
     else if(QStringLiteral("QByteArray").compare(innerType) == 0) {
         auto items = reinterpret_cast< QMap<QString, QByteArray*> *>(value);
         for(auto itemkey: items->keys()) {
             ::SWGSDRangel::toJsonValue(itemkey, items->value(itemkey), &mapobj, innerType);
         }
     }
     else if(QStringLiteral("qint32").compare(innerType) == 0) {
         auto items = reinterpret_cast< QMap<QString, qint32> *>(value);
         for(auto itemkey: items->keys()) {
             auto val = items->value(itemkey);
             ::SWGSDRangel::toJsonValue(itemkey, &val, &mapobj, innerType);
         }
     }
     else if(QStringLiteral("qint64").compare(innerType) == 0) {
         auto items = reinterpret_cast< QMap<QString, qint64> *>(value);
         for(auto itemkey: items->keys()) {
             auto val = items->value(itemkey);
             ::SWGSDRangel::toJsonValue(itemkey, &val, &mapobj, innerType);
         }
     }
     else if(QStringLiteral("bool").compare(innerType) == 0) {
         auto items = reinterpret_cast< QMap<QString, bool> *>(value);
         for(auto itemkey: items->keys()) {
             auto val = items->value(itemkey);
             ::SWGSDRangel::toJsonValue(itemkey, &val, &mapobj, innerType);
         }
     }
     else if(QStringLiteral("float").compare(innerType) == 0) {
         auto items = reinterpret_cast< QMap<QString, float> *>(value);
         for(auto itemkey: items->keys()) {
             auto val = items->value(itemkey);
             ::SWGSDRangel::toJsonValue(itemkey, &val, &mapobj, innerType);
         }
     }
     else if(QStringLiteral("double").compare(innerType) == 0) {
         auto items = reinterpret_cast< QMap<QString, double> *>(value);
         for(auto itemkey: items->keys() ) {
             auto val = items->value(itemkey);
             ::SWGSDRangel::toJsonValue(itemkey, &val, &mapobj, innerType);
         }
     }
     output->insert(innerName, mapobj);
 }
toJsonValue()
void SWGSDRangel::toJsonValue (QString name, void * value, QJsonObject * output, QString type)
Definition at line 383 of file SWGHelpers.cpp.
References SWGSDRangel::SWGObject::asJsonObject().
Referenced by SWGSDRangel::SWGAirspyHFSettings::asJsonObject(), SWGSDRangel::SWGAirspySettings::asJsonObject(), SWGSDRangel::SWGAMDemodSettings::asJsonObject(), SWGSDRangel::SWGATVModSettings::asJsonObject(), SWGSDRangel::SWGWFMDemodSettings::asJsonObject(), SWGSDRangel::SWGUDPSourceSettings::asJsonObject(), SWGSDRangel::SWGBladeRF2InputSettings::asJsonObject(), SWGSDRangel::SWGTestSourceSettings::asJsonObject(), SWGSDRangel::SWGPerseusSettings::asJsonObject(), SWGSDRangel::SWGPlutoSdrInputReport::asJsonObject(), SWGSDRangel::SWGDeviceState::asJsonObject(), SWGSDRangel::SWGPlutoSdrInputSettings::asJsonObject(), SWGSDRangel::SWGPlutoSdrOutputReport::asJsonObject(), SWGSDRangel::SWGDSDDemodReport::asJsonObject(), SWGSDRangel::SWGPlutoSdrOutputSettings::asJsonObject(), SWGSDRangel::SWGPreferences::asJsonObject(), SWGSDRangel::SWGDSDDemodSettings::asJsonObject(), SWGSDRangel::SWGSDRPlaySettings::asJsonObject(), SWGSDRangel::SWGAudioInputDevice::asJsonObject(), SWGSDRangel::SWGRtlSdrSettings::asJsonObject(), SWGSDRangel::SWGRemoteSourceSettings::asJsonObject(), SWGSDRangel::SWGRemoteSinkSettings::asJsonObject(), SWGSDRangel::SWGBladeRF2OutputSettings::asJsonObject(), SWGSDRangel::SWGRemoteInputSettings::asJsonObject(), SWGSDRangel::SWGRemoteInputReport::asJsonObject(), SWGSDRangel::SWGDVSerialDevice::asJsonObject(), SWGSDRangel::SWGPresetIdentifier::asJsonObject(), SWGSDRangel::SWGErrorResponse::asJsonObject(), SWGSDRangel::SWGPresetImport::asJsonObject(), SWGSDRangel::SWGPresetItem::asJsonObject(), SWGSDRangel::SWGFCDProPlusSettings::asJsonObject(), SWGSDRangel::SWGPresetTransfer::asJsonObject(), SWGSDRangel::SWGFCDProSettings::asJsonObject(), SWGSDRangel::SWGAudioOutputDevice::asJsonObject(), SWGSDRangel::SWGChannelListItem::asJsonObject(), SWGSDRangel::SWGFileInputReport::asJsonObject(), SWGSDRangel::SWGRemoteOutputSettings::asJsonObject(), SWGSDRangel::SWGFileInputSettings::asJsonObject(), SWGSDRangel::SWGFileSourceReport::asJsonObject(), SWGSDRangel::SWGSamplingDevice::asJsonObject(), SWGSDRangel::SWGFileSourceSettings::asJsonObject(), SWGSDRangel::SWGBFMDemodReport::asJsonObject(), SWGSDRangel::SWGFreeDVDemodSettings::asJsonObject(), SWGSDRangel::SWGLocalSourceSettings::asJsonObject(), SWGSDRangel::SWGSSBDemodSettings::asJsonObject(), SWGSDRangel::SWGLocalOutputSettings::asJsonObject(), SWGSDRangel::SWGLocalInputSettings::asJsonObject(), SWGSDRangel::SWGLimeSdrOutputSettings::asJsonObject(), SWGSDRangel::SWGFreqTrackerSettings::asJsonObject(), SWGSDRangel::SWGKiwiSDRSettings::asJsonObject(), SWGSDRangel::SWGSuccessResponse::asJsonObject(), SWGSDRangel::SWGFrequencyBand::asJsonObject(), SWGSDRangel::SWGXtrxOutputSettings::asJsonObject(), SWGSDRangel::SWGHackRFOutputSettings::asJsonObject(), SWGSDRangel::SWGUDPSinkSettings::asJsonObject(), SWGSDRangel::SWGAMBEDevice::asJsonObject(), SWGSDRangel::SWGBFMDemodSettings::asJsonObject(), SWGSDRangel::SWGCommand::asJsonObject(), SWGSDRangel::SWGHackRFInputSettings::asJsonObject(), SWGSDRangel::SWGXtrxInputSettings::asJsonObject(), SWGSDRangel::SWGBladeRF1InputSettings::asJsonObject(), SWGSDRangel::SWGCWKeyerSettings::asJsonObject(), SWGSDRangel::SWGLimeSdrInputSettings::asJsonObject(), SWGSDRangel::SWGArgValue::asJsonObject(), SWGSDRangel::SWGBladeRF1OutputSettings::asJsonObject(), SWGSDRangel::SWGDeviceListItem::asJsonObject(), SWGSDRangel::SWGLocalSinkSettings::asJsonObject(), SWGSDRangel::SWGLoggingInfo::asJsonObject(), SWGSDRangel::SWGNamedEnum::asJsonObject(), SWGSDRangel::SWGNFMDemodSettings::asJsonObject(), SWGSDRangel::SWGSSBModSettings::asJsonObject(), SWGSDRangel::SWGWFMModSettings::asJsonObject(), SWGSDRangel::SWGFreeDVModSettings::asJsonObject(), SWGSDRangel::SWGBladeRF2OutputReport::asJsonObject(), SWGSDRangel::SWGChannel::asJsonObject(), SWGSDRangel::SWGSoapySDRGainSetting::asJsonObject(), SWGSDRangel::SWGChannelConfig::asJsonObject(), SWGSDRangel::SWGDeviceConfig::asJsonObject(), SWGSDRangel::SWGNFMModSettings::asJsonObject(), SWGSDRangel::SWGPresetExport::asJsonObject(), SWGSDRangel::SWGAMModSettings::asJsonObject(), SWGSDRangel::SWGPresetGroup::asJsonObject(), SWGSDRangel::SWGArgInfo::asJsonObject(), SWGSDRangel::SWGRDSReport::asJsonObject(), SWGSDRangel::SWGInstanceSummaryResponse::asJsonObject(), SWGSDRangel::SWGDeviceSet::asJsonObject(), SWGSDRangel::SWGSoapySDRFrequencySetting::asJsonObject(), SWGSDRangel::SWGTestMISettings::asJsonObject(), SWGSDRangel::SWGInstanceConfigResponse::asJsonObject(), SWGSDRangel::SWGSoapySDROutputSettings::asJsonObject(), SWGSDRangel::SWGBladeRF2InputReport::asJsonObject(), SWGSDRangel::SWGSoapySDRInputSettings::asJsonObject(), SWGSDRangel::SWGPreset::asJsonObject(), SWGSDRangel::SWGSoapySDRReport::asJsonObject(), SWGSDRangel::SWGChannelReport::asJsonObject(), SWGSDRangel::SWGDeviceReport::asJsonObject(), SWGSDRangel::SWGChannelSettings_2::asJsonObject(), SWGSDRangel::SWGChannelSettings::asJsonObject(), SWGSDRangel::SWGDeviceSettings_2::asJsonObject(), SWGSDRangel::SWGDeviceSettings::asJsonObject(), and toJsonMap().
{
     if(value == nullptr) {
         return;
     }
     if(type.startsWith("SWG")) {
         SWGObject *SWGobject = reinterpret_cast<SWGObject *>(value);
         if(SWGobject != nullptr) {
             QJsonObject* o = (*SWGobject).asJsonObject();
             if (o != nullptr)
             {
                 if(name != nullptr) {
                     output->insert(name, *o);
                     if(o != nullptr) delete o;
                 }
                 else {
                     output->empty();
                     for(QString key : o->keys()) {
                         output->insert(key, o->value(key));
                     }
                 }
             }
         }
     }
     else if(QStringLiteral("QString").compare(type) == 0) {
         QString* str = static_cast<QString*>(value);
         output->insert(name, QJsonValue(*str));
     }
     else if(QStringLiteral("qint32").compare(type) == 0) {
         qint32* str = static_cast<qint32*>(value);
         output->insert(name, QJsonValue(*str));
     }
     else if(QStringLiteral("qint64").compare(type) == 0) {
         qint64* str = static_cast<qint64*>(value);
         output->insert(name, QJsonValue(*str));
     }
     else if(QStringLiteral("bool").compare(type) == 0) {
         bool* str = static_cast<bool*>(value);
         output->insert(name, QJsonValue(*str));
     }
     else if(QStringLiteral("float").compare(type) == 0) {
         float* str = static_cast<float*>(value);
         output->insert(name, QJsonValue((double)*str));
     }
     else if(QStringLiteral("double").compare(type) == 0) {
         double* str = static_cast<double*>(value);
         output->insert(name, QJsonValue(*str));
     }
     else if(QStringLiteral("QDate").compare(type) == 0) {
         QDate* date = static_cast<QDate*>(value);
         output->insert(name, QJsonValue(date->toString(Qt::ISODate)));
     }
     else if(QStringLiteral("QDateTime").compare(type) == 0) {
         QDateTime* datetime = static_cast<QDateTime*>(value);
         output->insert(name, QJsonValue(datetime->toString(Qt::ISODate)));
     }
     else if(QStringLiteral("QByteArray").compare(type) == 0) {
         QByteArray* byteArray = static_cast<QByteArray*>(value);
         output->insert(name, QJsonValue(QString(byteArray->toBase64())));
     }
 }