SDRAngel: RemoteSourceThread::MsgStartStop Class Reference
RemoteSourceThread::MsgStartStop Class Reference
#include <remotesourcethread.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 36 of file remotesourcethread.h.
Constructor & Destructor Documentation
MsgStartStop()
RemoteSourceThread::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 49 of file remotesourcethread.h.
Referenced by create().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* RemoteSourceThread::MsgStartStop::create (bool startStop) inline static
Definition at line 42 of file remotesourcethread.h.
References MsgStartStop().
Referenced by RemoteSourceThread::startStop().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool RemoteSourceThread::MsgStartStop::getStartStop () const inline
Definition at line 40 of file remotesourcethread.h.
References m_startStop.
Referenced by RemoteSourceThread::handleInputMessages().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool RemoteSourceThread::MsgStartStop::m_startStop protected
Definition at line 47 of file remotesourcethread.h.
Referenced by getStartStop().
The documentation for this class was generated from the following file:
plugins/channeltx/remotesource/remotesourcethread.h