SDRAngel: SDRPlayBandwidths Class Reference
SDRPlayBandwidths Class Reference
#include <sdrplayinput.h>
Static Public Member Functions
static unsigned int getBandwidth (unsigned int bandwidth_index)
static unsigned int getBandwidthIndex (unsigned int bandwidth)
static unsigned int getNbBandwidths ()
Static Private Attributes
static const unsigned int m_nb_bw = 8
static unsigned int m_bw [m_nb_bw]
Detailed Description
Definition at line 222 of file sdrplayinput.h.
Member Function Documentation
getBandwidth()
unsigned int SDRPlayBandwidths::getBandwidth (unsigned int bandwidth_index) static
Definition at line 1040 of file sdrplayinput.cpp.
Referenced by SDRPlayInput::applySettings(), SDRPlayGui::SDRPlayGui(), and SDRPlayInput::webapiFormatDeviceReport().
 {
     if (bandwidth_index < m_nb_bw)
     {
         return m_bw[bandwidth_index];
     }
     else
     {
         return m_bw[0];
     }
 }
getBandwidthIndex()
unsigned int SDRPlayBandwidths::getBandwidthIndex (unsigned int bandwidth) static
Definition at line 1052 of file sdrplayinput.cpp.
References i.
 {
     for (unsigned int i=0; i < m_nb_bw; i++)
     {
         if (bandwidth == m_bw[i])
         {
             return i;
         }
     }
     return 0;
 }
getNbBandwidths()
unsigned int SDRPlayBandwidths::getNbBandwidths () static
Definition at line 1065 of file sdrplayinput.cpp.
References SDRPlayIF::m_if, and m_nb_bw.
Referenced by SDRPlayGui::SDRPlayGui(), and SDRPlayInput::webapiFormatDeviceReport().
 {
     return SDRPlayBandwidths::m_nb_bw;
 }
Member Data Documentation
m_bw
unsigned int SDRPlayBandwidths::m_bw static private
Initial value:
= {
        200000,
        300000,
        600000,
        1536000,
        5000000,
        6000000,
        7000000,
        8000000,
}
Definition at line 229 of file sdrplayinput.h.
Referenced by SDRPlaySampleRates::getNbRates().
m_nb_bw
const unsigned int SDRPlayBandwidths::m_nb_bw = 8 static private
Definition at line 228 of file sdrplayinput.h.
Referenced by getNbBandwidths().
The documentation for this class was generated from the following files:
plugins/samplesource/sdrplay/sdrplayinput.h
plugins/samplesource/sdrplay/sdrplayinput.cpp