SDRAngel: ScopeVis::TraceBackBuffer Struct Reference
ScopeVis::TraceBackBuffer Struct Reference
Public Member Functions
TraceBackBuffer ()
void resize (uint32_t size)
void reset ()
void write (const SampleVector::const_iterator begin, const SampleVector::const_iterator end)
unsigned int absoluteFill () const
SampleVector::iterator current ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
Public Attributes
TraceBuffer m_traceBuffer
SampleVector::iterator m_endPoint
Detailed Description
Definition at line 633 of file scopevis.h.
Constructor & Destructor Documentation
TraceBackBuffer()
ScopeVis::TraceBackBuffer::TraceBackBuffer () inline
Definition at line 638 of file scopevis.h.
References DoubleBufferSimple< T >::getCurrent().
         {
             m_endPoint = m_traceBuffer.getCurrent();
         }
Member Function Documentation
absoluteFill()
unsigned int ScopeVis::TraceBackBuffer::absoluteFill () const inline
Definition at line 658 of file scopevis.h.
References DoubleBufferSimple< T >::absoluteFill().
{
             return m_traceBuffer.absoluteFill();
         }
current()
SampleVector::iterator ScopeVis::TraceBackBuffer::current () inline
Definition at line 662 of file scopevis.h.
References DoubleBufferSimple< T >::getCurrent().
Referenced by ScopeVis::processTrace().
 { return m_traceBuffer.getCurrent(); }
deserialize()
bool ScopeVis::TraceBackBuffer::deserialize (const QByteArray & data) inline
Definition at line 676 of file scopevis.h.
References DoubleBufferSimple< T >::begin(), DoubleBufferSimple< T >::deserialize(), SimpleDeserializer::getVersion(), SimpleDeserializer::isValid(), SimpleDeserializer::readBlob(), and SimpleDeserializer::readU32().
         {
             SimpleDeserializer d(data);
             if(!d.isValid()) {
                 return false;
             }
             if (d.getVersion() == 1)
             {
                 unsigned int tmpUInt;
                 QByteArray buf;
                 d.readU32(1, &tmpUInt, 0);
                 d.readBlob(2, &buf);
                 m_traceBuffer.deserialize(buf);
                 m_endPoint = m_traceBuffer.begin() + tmpUInt;
                 return true;
             }
             else
             {
                 return false;
             }
         }
reset()
void ScopeVis::TraceBackBuffer::reset () inline
Definition at line 648 of file scopevis.h.
References DoubleBufferSimple< T >::reset().
Referenced by ScopeVis::TraceBackDiscreteMemory::store().
         {
             m_traceBuffer.reset();
         }
resize()
void ScopeVis::TraceBackBuffer::resize (uint32_t size) inline
Definition at line 643 of file scopevis.h.
References DoubleBufferSimple< T >::resize().
         {
             m_traceBuffer.resize(size);
         }
serialize()
QByteArray ScopeVis::TraceBackBuffer::serialize () const inline
Definition at line 664 of file scopevis.h.
References DoubleBufferSimple< T >::begin(), SimpleSerializer::final(), DoubleBufferSimple< T >::serialize(), SimpleSerializer::writeBlob(), and SimpleSerializer::writeU32().
         {
             SimpleSerializer s(1);
             QByteArray buffer = m_traceBuffer.serialize();
             unsigned int endDelta = m_endPoint - m_traceBuffer.begin();
             s.writeU32(1, endDelta);
             s.writeBlob(2, buffer);
             return s.final();
         }
write()
void ScopeVis::TraceBackBuffer::write (const SampleVector::const_iterator begin, const SampleVector::const_iterator end) inline
Definition at line 653 of file scopevis.h.
References DoubleBufferSimple< T >::write().
Referenced by ScopeVis::processTrace().
         {
             m_traceBuffer.write(begin, end);
         }
Member Data Documentation
m_endPoint
SampleVector::iterator ScopeVis::TraceBackBuffer::m_endPoint
Definition at line 636 of file scopevis.h.
Referenced by ScopeVis::processMemoryTrace(), and ScopeVis::processTrace().
m_traceBuffer
TraceBuffer ScopeVis::TraceBackBuffer::m_traceBuffer
Definition at line 635 of file scopevis.h.
The documentation for this struct was generated from the following file:
sdrgui/dsp/scopevis.h