SDRAngel: SWGSDRangel::SWGGain Class Reference
SWGSDRangel::SWGGain Class Reference
#include <SWGGain.h>
Public Member Functions
SWGGain ()
SWGGain (QString *json)
virtual ~SWGGain ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGGain * fromJson (QString &jsonString) override
qint32 getGainCb ()
void setGainCb (qint32 gain_cb)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 gain_cb
bool m_gain_cb_isSet
Detailed Description
Definition at line 31 of file SWGGain.h.
Constructor & Destructor Documentation
SWGGain() [1/2]
SWGSDRangel::SWGGain::SWGGain ()
Definition at line 30 of file SWGGain.cpp.
References gain_cb, and m_gain_cb_isSet.
                  {
     gain_cb = 0;
     m_gain_cb_isSet = false;
 }
SWGGain() [2/2]
SWGSDRangel::SWGGain::SWGGain (QString * json)
Definition at line 25 of file SWGGain.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGGain()
SWGSDRangel::SWGGain::~SWGGain () virtual
Definition at line 35 of file SWGGain.cpp.
References cleanup().
                   {
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGGain::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 66 of file SWGGain.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGGain::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 77 of file SWGGain.cpp.
References gain_cb, and m_gain_cb_isSet.
Referenced by asJson().
                       {
     QJsonObject* obj = new QJsonObject();
     if(m_gain_cb_isSet){
         obj->insert("gainCB", QJsonValue(gain_cb));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGGain::cleanup ()
Definition at line 46 of file SWGGain.cpp.
Referenced by ~SWGGain().
                  {
 }
fromJson()
SWGGain * SWGSDRangel::SWGGain::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 51 of file SWGGain.cpp.
References fromJsonObject().
Referenced by SWGGain().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGGain::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 60 of file SWGGain.cpp.
References gain_cb, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&gain_cb, pJson["gainCB"], "qint32", "");
 }
getGainCb()
qint32 SWGSDRangel::SWGGain::getGainCb ()
Definition at line 87 of file SWGGain.cpp.
References gain_cb.
                    {
     return gain_cb;
 }
init()
void SWGSDRangel::SWGGain::init ()
Definition at line 40 of file SWGGain.cpp.
References gain_cb, and m_gain_cb_isSet.
Referenced by SWGGain().
               {
     gain_cb = 0;
     m_gain_cb_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGGain::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 98 of file SWGGain.cpp.
References m_gain_cb_isSet.
               {
     bool isObjectUpdated = false;
     do{
         if(m_gain_cb_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setGainCb()
void SWGSDRangel::SWGGain::setGainCb (qint32 gain_cb)
Definition at line 91 of file SWGGain.cpp.
References gain_cb, and m_gain_cb_isSet.
{
     this->gain_cb = gain_cb;
     this->m_gain_cb_isSet = true;
 }
Member Data Documentation
gain_cb
qint32 SWGSDRangel::SWGGain::gain_cb private
Definition at line 51 of file SWGGain.h.
Referenced by asJsonObject(), fromJsonObject(), getGainCb(), init(), setGainCb(), and SWGGain().
m_gain_cb_isSet
bool SWGSDRangel::SWGGain::m_gain_cb_isSet private
Definition at line 52 of file SWGGain.h.
Referenced by asJsonObject(), init(), isSet(), setGainCb(), and SWGGain().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGGain.h
swagger/sdrangel/code/qt5/client/SWGGain.cpp