SDRAngel: qrtplib::RTCPCompoundPacketBuilder::SDES Class Reference
qrtplib::RTCPCompoundPacketBuilder::SDES Class Reference
Public Member Functions
SDES ()
~SDES ()
void Clear ()
int AddSSRC (uint32_t ssrc)
int AddItem (uint8_t *buf, std::size_t len)
std::size_t NeededBytes ()
std::size_t NeededBytesWithExtraItem (uint8_t itemdatalength)
std::size_t NeededBytesWithExtraSource ()
Public Attributes
std::list< SDESSource * > sdessources
Private Attributes
std::list< SDESSource * >::const_iterator sdesit
Detailed Description
Definition at line 278 of file rtcpcompoundpacketbuilder.h.
Constructor & Destructor Documentation
SDES()
qrtplib::RTCPCompoundPacketBuilder::SDES::SDES () inline
Definition at line 281 of file rtcpcompoundpacketbuilder.h.
         {
             sdesit = sdessources.end();
         }
~SDES()
qrtplib::RTCPCompoundPacketBuilder::SDES::~SDES () inline
Definition at line 285 of file rtcpcompoundpacketbuilder.h.
         {
             Clear();
         }
Member Function Documentation
AddItem()
int qrtplib::RTCPCompoundPacketBuilder::SDES::AddItem (uint8_t * buf, std::size_t len) inline
Definition at line 308 of file rtcpcompoundpacketbuilder.h.
References ERR_RTP_RTCPCOMPPACKBUILDER_NOCURRENTSOURCE.
Referenced by qrtplib::RTCPCompoundPacketBuilder::AddSDESNormalItem(), and qrtplib::RTCPCompoundPacketBuilder::AddSDESPrivateItem().
         {
             if (sdessources.empty())
                 return ERR_RTP_RTCPCOMPPACKBUILDER_NOCURRENTSOURCE;
             (*sdesit)->AddItem(buf, len);
             return 0;
         }
AddSSRC()
int qrtplib::RTCPCompoundPacketBuilder::SDES::AddSSRC (uint32_t ssrc) inline
Definition at line 299 of file rtcpcompoundpacketbuilder.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::AddSDESSource().
         {
             SDESSource *s = new SDESSource(ssrc);
             sdessources.push_back(s);
             sdesit = sdessources.end();
             sdesit--;
             return 0;
         }
Clear()
void qrtplib::RTCPCompoundPacketBuilder::SDES::Clear () inline
Definition at line 290 of file rtcpcompoundpacketbuilder.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::ClearBuildBuffers().
         {
             std::list<SDESSource *>::const_iterator it;
             for (it = sdessources.begin(); it != sdessources.end(); it++)
                 delete *it;
             sdessources.clear();
         }
NeededBytes()
std::size_t qrtplib::RTCPCompoundPacketBuilder::SDES::NeededBytes () inline
Definition at line 316 of file rtcpcompoundpacketbuilder.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::AddAPPPacket(), qrtplib::RTCPCompoundPacketBuilder::AddBYEPacket(), qrtplib::RTCPCompoundPacketBuilder::AddReportBlock(), qrtplib::RTCPCompoundPacketBuilder::EndBuild(), qrtplib::RTCPCompoundPacketBuilder::StartReceiverReport(), and qrtplib::RTCPCompoundPacketBuilder::StartSenderReport().
         {
             std::list<SDESSource *>::const_iterator it;
             std::size_t x = 0;
             std::size_t n, d, r;
             if (sdessources.empty())
                 return 0;
             for (it = sdessources.begin(); it != sdessources.end(); it++)
                 x += (*it)->NeededBytes();
             n = sdessources.size();
             d = n / 31;
             r = n % 31;
             if (r != 0)
                 d++;
             x += d * sizeof(RTCPCommonHeader);
             return x;
         }
NeededBytesWithExtraItem()
std::size_t qrtplib::RTCPCompoundPacketBuilder::SDES::NeededBytesWithExtraItem (uint8_t itemdatalength) inline
Definition at line 336 of file rtcpcompoundpacketbuilder.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::AddSDESNormalItem(), and qrtplib::RTCPCompoundPacketBuilder::AddSDESPrivateItem().
         {
             std::list<SDESSource *>::const_iterator it;
             std::size_t x = 0;
             std::size_t n, d, r;
             if (sdessources.empty())
                 return 0;
             for (it = sdessources.begin(); it != sdesit; it++)
                 x += (*it)->NeededBytes();
             x += (*sdesit)->NeededBytesWithExtraItem(itemdatalength);
             n = sdessources.size();
             d = n / 31;
             r = n % 31;
             if (r != 0)
                 d++;
             x += d * sizeof(RTCPCommonHeader);
             return x;
         }
NeededBytesWithExtraSource()
std::size_t qrtplib::RTCPCompoundPacketBuilder::SDES::NeededBytesWithExtraSource () inline
Definition at line 357 of file rtcpcompoundpacketbuilder.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::AddSDESSource().
         {
             std::list<SDESSource *>::const_iterator it;
             std::size_t x = 0;
             std::size_t n, d, r;
             if (sdessources.empty())
                 return 0;
             for (it = sdessources.begin(); it != sdessources.end(); it++)
                 x += (*it)->NeededBytes();
             // for the extra source we'll need at least 8 bytes (ssrc and four 0 bytes)
             x += sizeof(uint32_t) * 2;
             n = sdessources.size() + 1; // also, the number of sources will increase
             d = n / 31;
             r = n % 31;
             if (r != 0)
                 d++;
             x += d * sizeof(RTCPCommonHeader);
             return x;
         }
Member Data Documentation
sdesit
std::list<SDESSource *>::const_iterator qrtplib::RTCPCompoundPacketBuilder::SDES::sdesit private
Definition at line 383 of file rtcpcompoundpacketbuilder.h.
sdessources
std::list<SDESSource *> qrtplib::RTCPCompoundPacketBuilder::SDES::sdessources
Definition at line 381 of file rtcpcompoundpacketbuilder.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::AddSDESNormalItem(), qrtplib::RTCPCompoundPacketBuilder::AddSDESPrivateItem(), and qrtplib::RTCPCompoundPacketBuilder::EndBuild().
The documentation for this class was generated from the following file:
qrtplib/rtcpcompoundpacketbuilder.h