SDRAngel: Bladerf1Output::MsgStartStop Class Reference
Bladerf1Output::MsgStartStop Class Reference
#include <bladerf1output.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 61 of file bladerf1output.h.
Constructor & Destructor Documentation
MsgStartStop()
Bladerf1Output::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 74 of file bladerf1output.h.
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* Bladerf1Output::MsgStartStop::create (bool startStop) inline static
Definition at line 67 of file bladerf1output.h.
Referenced by Bladerf1OutputGui::on_startStop_toggled(), and Bladerf1Output::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool Bladerf1Output::MsgStartStop::getStartStop () const inline
Definition at line 65 of file bladerf1output.h.
Referenced by Bladerf1OutputGui::handleMessage(), and Bladerf1Output::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool Bladerf1Output::MsgStartStop::m_startStop protected
Definition at line 72 of file bladerf1output.h.
The documentation for this class was generated from the following file:
plugins/samplesink/bladerf1output/bladerf1output.h