SDRAngel: BladeRF2Input Class Reference
BladeRF2Input Class Reference
#include <bladerf2input.h>
Classes
struct GainMode
class MsgConfigureBladeRF2
class MsgFileRecord
class MsgReportGainRange
class MsgStartStop
Public Member Functions
BladeRF2Input (DeviceAPI *deviceAPI)
virtual ~BladeRF2Input ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
BladeRF2InputThread * getThread ()
void setThread (BladeRF2InputThread *thread)
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
void getFrequencyRange (uint64_t &min, uint64_t &max, int &step)
void getSampleRateRange (int &min, int &max, int &step)
void getBandwidthRange (int &min, int &max, int &step)
void getGlobalGainRange (int &min, int &max, int &step)
const std::vector< GainMode > & getGainModes ()
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
BladeRF2InputThread * findThread ()
void moveThreadToBuddy ()
bool applySettings (const BladeRF2InputSettings &settings, bool force=false)
bool setDeviceCenterFrequency (struct bladerf *dev, int requestedChannel, quint64 freq_hz, int loPpmTenths)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const BladeRF2InputSettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const BladeRF2InputSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
BladeRF2InputSettings m_settings
QString m_deviceDescription
bool m_running
DeviceBladeRF2Shared m_deviceShared
BladeRF2InputThread * m_thread
FileRecord * m_fileSink
File sink to record device I/Q output.
std::vector< GainMode > m_gainModes
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 39 of file bladerf2input.h.
Constructor & Destructor Documentation
BladeRF2Input()
BladeRF2Input::BladeRF2Input (DeviceAPI * deviceAPI)
Definition at line 46 of file bladerf2input.cpp.
References arg(), and i.
                                                  :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_deviceDescription("BladeRF2Input"),
     m_running(false),
     m_thread(0)
 {
     openDevice();
     if (m_deviceShared.m_dev)
     {
         const bladerf_gain_modes *modes = 0;
         int nbModes = m_deviceShared.m_dev->getGainModesRx(&modes);
         if (modes)
         {
             for (int i = 0; i < nbModes; i++) {
                 m_gainModes.push_back(GainMode{QString(modes[i].name), modes[i].mode});
             }
         }
     }
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~BladeRF2Input()
BladeRF2Input::~BladeRF2Input () virtual
Definition at line 75 of file bladerf2input.cpp.
References closeDevice(), m_deviceAPI, m_fileSink, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::removeAncillarySink(), and stop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
     closeDevice();
 }
Member Function Documentation
applySettings()
bool BladeRF2Input::applySettings (const BladeRF2InputSettings & settings, bool force = false) private
Definition at line 768 of file bladerf2input.cpp.
References DeviceSampleSource::calculateDeviceCenterFrequency(), DeviceAPI::configureCorrections(), DeviceBladeRF2Shared::MsgReportBuddyChange::create(), BladeRF2Input::MsgReportGainRange::create(), findThread(), DeviceBladeRF2::getDev(), DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceAPI::getDeviceItemIndex(), getGlobalGainRange(), DeviceSampleSource::getMessageQueueToGUI(), DeviceAPI::getSinkBuddies(), DeviceAPI::getSourceBuddies(), FileRecord::handleMessage(), BladeRF2InputSettings::m_bandwidth, BladeRF2InputSettings::m_biasTee, BladeRF2InputSettings::m_centerFrequency, BladeRF2InputSettings::m_dcBlock, DeviceBladeRF2Shared::m_dev, m_deviceAPI, m_deviceShared, BladeRF2InputSettings::m_devSampleRate, BladeRF2InputSettings::m_fcPos, m_fileSink, BladeRF2InputSettings::m_gainMode, BladeRF2InputSettings::m_globalGain, BladeRF2InputSettings::m_iqCorrection, BladeRF2InputSettings::m_log2Decim, BladeRF2InputSettings::m_LOppmTenths, BladeRF2InputSettings::m_reverseAPIAddress, BladeRF2InputSettings::m_reverseAPIDeviceIndex, BladeRF2InputSettings::m_reverseAPIPort, m_settings, BladeRF2InputSettings::m_transverterDeltaFrequency, BladeRF2InputSettings::m_transverterMode, BladeRF2InputSettings::m_useReverseAPI, leansdr::max(), leansdr::min(), MessageQueue::push(), DeviceBladeRF2::setBiasTeeRx(), setDeviceCenterFrequency(), BladeRF2InputThread::setFcPos(), BladeRF2InputThread::setLog2Decimation(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     bool forwardChangeOwnDSP = false;
     bool forwardChangeRxBuddies  = false;
     bool forwardChangeTxBuddies = false;
     struct bladerf *dev = m_deviceShared.m_dev->getDev();
     int requestedChannel = m_deviceAPI->getDeviceItemIndex();
     qint64 xlatedDeviceCenterFrequency = settings.m_centerFrequency;
     xlatedDeviceCenterFrequency -= settings.m_transverterMode ? settings.m_transverterDeltaFrequency : 0;
     xlatedDeviceCenterFrequency = xlatedDeviceCenterFrequency < 0 ? 0 : xlatedDeviceCenterFrequency;
     QList<QString> reverseAPIKeys;
     if ((m_settings.m_dcBlock != settings.m_dcBlock) || force) {
         reverseAPIKeys.append("dcBlock");
     }
     if ((m_settings.m_iqCorrection != settings.m_iqCorrection) || force) {
         reverseAPIKeys.append("iqCorrection");
     }
     if ((m_settings.m_dcBlock != settings.m_dcBlock) ||
         (m_settings.m_iqCorrection != settings.m_iqCorrection) || force)
     {
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqCorrection);
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || force)
     {
         reverseAPIKeys.append("devSampleRate");
         forwardChangeOwnDSP = true;
         forwardChangeRxBuddies = true;
         forwardChangeTxBuddies = true;
         if (dev != 0)
         {
             unsigned int actualSamplerate;
             int status = bladerf_set_sample_rate(dev, BLADERF_CHANNEL_RX(requestedChannel), settings.m_devSampleRate, &actualSamplerate);
             if (status < 0)
             {
                 qCritical("BladeRF2Input::applySettings: could not set sample rate: %d: %s",
                         settings.m_devSampleRate, bladerf_strerror(status));
             }
             else
             {
                 qDebug() << "BladeRF2Input::applySettings: bladerf_set_sample_rate: actual sample rate is " << actualSamplerate;
             }
         }
     }
     if ((m_settings.m_bandwidth != settings.m_bandwidth) || force)
     {
         reverseAPIKeys.append("bandwidth");
         forwardChangeRxBuddies = true;
         if (dev != 0)
         {
             unsigned int actualBandwidth;
             int status = bladerf_set_bandwidth(dev, BLADERF_CHANNEL_RX(requestedChannel), settings.m_bandwidth, &actualBandwidth);
             if(status < 0)
             {
                 qCritical("BladeRF2Input::applySettings: could not set bandwidth: %d: %s",
                         settings.m_bandwidth, bladerf_strerror(status));
             }
             else
             {
                 qDebug() << "BladeRF2Input::applySettings: bladerf_set_bandwidth: actual bandwidth is " << actualBandwidth;
             }
         }
     }
     if ((m_settings.m_fcPos != settings.m_fcPos) || force)
     {
         reverseAPIKeys.append("fcPos");
         BladeRF2InputThread *inputThread = findThread();
         if (inputThread != 0)
         {
             inputThread->setFcPos(requestedChannel, (int) settings.m_fcPos);
             qDebug() << "BladeRF2Input::applySettings: set fc pos (enum) to " << (int) settings.m_fcPos;
         }
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         reverseAPIKeys.append("log2Decim");
         forwardChangeOwnDSP = true;
         BladeRF2InputThread *inputThread = findThread();
         if (inputThread != 0)
         {
             inputThread->setLog2Decimation(requestedChannel, settings.m_log2Decim);
             qDebug() << "BladeRF2Input::applySettings: set decimation to " << (1<<settings.m_log2Decim);
         }
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency) || force) {
         reverseAPIKeys.append("centerFrequency");
     }
     if ((m_settings.m_transverterMode != settings.m_transverterMode) || force) {
         reverseAPIKeys.append("transverterMode");
     }
     if ((m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency) || force) {
         reverseAPIKeys.append("transverterDeltaFrequency");
     }
     if ((m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force) {
         reverseAPIKeys.append("LOppmTenths");
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || force) {
         reverseAPIKeys.append("devSampleRate");
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency)
         || (m_settings.m_transverterMode != settings.m_transverterMode)
         || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency)
         || (m_settings.m_LOppmTenths != settings.m_LOppmTenths)
         || (m_settings.m_devSampleRate != settings.m_devSampleRate)
         || (m_settings.m_fcPos != settings.m_fcPos)
         || (m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         qint64 deviceCenterFrequency = DeviceSampleSource::calculateDeviceCenterFrequency(
                 xlatedDeviceCenterFrequency,
                 0,
                 settings.m_log2Decim,
                 (DeviceSampleSource::fcPos_t) settings.m_fcPos,
                 settings.m_devSampleRate,
                 DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD,
                 false);
         forwardChangeOwnDSP = true;
         forwardChangeRxBuddies = true;
         if (dev != 0)
         {
             if (setDeviceCenterFrequency(dev, requestedChannel, deviceCenterFrequency, settings.m_LOppmTenths))
             {
                 if (getMessageQueueToGUI())
                 {
                     int min, max, step;
                     getGlobalGainRange(min, max, step);
                     MsgReportGainRange *msg = MsgReportGainRange::create(min, max, step);
                     getMessageQueueToGUI()->push(msg);
                 }
             }
         }
     }
     if ((m_settings.m_biasTee != settings.m_biasTee) || force)
     {
         reverseAPIKeys.append("biasTee");
         forwardChangeRxBuddies = true;
         m_deviceShared.m_dev->setBiasTeeRx(settings.m_biasTee);
     }
     if ((m_settings.m_gainMode != settings.m_gainMode) || force)
     {
         reverseAPIKeys.append("gainMode");
         forwardChangeRxBuddies = true;
         if (dev)
         {
             int status = bladerf_set_gain_mode(dev, BLADERF_CHANNEL_RX(requestedChannel), (bladerf_gain_mode) settings.m_gainMode);
             if (status < 0) {
                 qWarning("BladeRF2Input::applySettings: bladerf_set_gain_mode(%d) failed: %s",
                         settings.m_gainMode, bladerf_strerror(status));
             } else {
                 qDebug("BladeRF2Input::applySettings: bladerf_set_gain_mode(%d)", settings.m_gainMode);
             }
         }
     }
     if ((m_settings.m_globalGain != settings.m_globalGain) || force) {
         reverseAPIKeys.append("globalGain");
     }
     if ((m_settings.m_gainMode != settings.m_gainMode) || force) {
         reverseAPIKeys.append("gainMode");
     }
     if ((m_settings.m_globalGain != settings.m_globalGain)
        || ((m_settings.m_gainMode != settings.m_gainMode) && (settings.m_gainMode == BLADERF_GAIN_MANUAL)) || force)
     {
         forwardChangeRxBuddies = true;
         if (dev)
         {
 //            qDebug("BladeRF2Input::applySettings: channel: %d gain: %d", requestedChannel, settings.m_globalGain);
             int status = bladerf_set_gain(dev, BLADERF_CHANNEL_RX(requestedChannel), settings.m_globalGain);
             if (status < 0) {
                 qWarning("BladeRF2Input::applySettings: bladerf_set_gain(%d) failed: %s",
                         settings.m_globalGain, bladerf_strerror(status));
             } else {
                 qDebug("BladeRF2Input::applySettings: bladerf_set_gain(%d)", settings.m_globalGain);
             }
         }
     }
     if (forwardChangeOwnDSP)
     {
         int sampleRate = settings.m_devSampleRate/(1<<settings.m_log2Decim);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     if (forwardChangeRxBuddies)
     {
         // send to source buddies
         const std::vector<DeviceAPI*>& sourceBuddies = m_deviceAPI->getSourceBuddies();
         std::vector<DeviceAPI*>::const_iterator itSource = sourceBuddies.begin();
         for (; itSource != sourceBuddies.end(); ++itSource)
         {
             DeviceBladeRF2Shared::MsgReportBuddyChange *report = DeviceBladeRF2Shared::MsgReportBuddyChange::create(
                     settings.m_centerFrequency,
                     settings.m_LOppmTenths,
                     (int) settings.m_fcPos,
                     settings.m_devSampleRate,
                     true);
             (*itSource)->getSamplingDeviceInputMessageQueue()->push(report);
         }
     }
     if (forwardChangeTxBuddies)
     {
         // send to sink buddies
         const std::vector<DeviceAPI*>& sinkBuddies = m_deviceAPI->getSinkBuddies();
         std::vector<DeviceAPI*>::const_iterator itSink = sinkBuddies.begin();
         for (; itSink != sinkBuddies.end(); ++itSink)
         {
             DeviceBladeRF2Shared::MsgReportBuddyChange *report = DeviceBladeRF2Shared::MsgReportBuddyChange::create(
                     settings.m_centerFrequency,
                     settings.m_LOppmTenths,
                     (int) settings.m_fcPos,
                     settings.m_devSampleRate,
                     true);
             (*itSink)->getSamplingDeviceInputMessageQueue()->push(report);
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     qDebug() << "BladeRF2Input::applySettings: "
             << " m_transverterMode: " << m_settings.m_transverterMode
             << " m_transverterDeltaFrequency: " << m_settings.m_transverterDeltaFrequency
             << " m_centerFrequency: " << m_settings.m_centerFrequency << " Hz"
             << " m_LOppmTenths: " << m_settings.m_LOppmTenths
             << " m_bandwidth: " << m_settings.m_bandwidth
             << " m_log2Decim: " << m_settings.m_log2Decim
             << " m_fcPos: " << m_settings.m_fcPos
             << " m_devSampleRate: " << m_settings.m_devSampleRate
             << " m_globalGain: " << m_settings.m_globalGain
             << " m_gainMode: " << m_settings.m_gainMode
             << " m_dcBlock: " << m_settings.m_dcBlock
             << " m_iqCorrection: " << m_settings.m_iqCorrection
             << " m_biasTee: " << m_settings.m_biasTee;
     return true;
 }
closeDevice()
void BladeRF2Input::closeDevice () private
Definition at line 176 of file bladerf2input.cpp.
References DeviceBladeRF2::close(), DeviceAPI::getSinkBuddies(), DeviceAPI::getSourceBuddies(), DeviceBladeRF2Shared::m_channel, DeviceBladeRF2Shared::m_dev, m_deviceAPI, m_deviceShared, m_running, DeviceBladeRF2Shared::m_source, m_thread, moveThreadToBuddy(), and stop().
Referenced by ~BladeRF2Input().
 {
     if (m_deviceShared.m_dev == 0) { // was never open
         return;
     }
     if (m_running) {
         stop();
     }
     if (m_thread) { // stills own the thread => transfer to a buddy
         moveThreadToBuddy();
     }
     m_deviceShared.m_channel = -1; // publicly release channel
     m_deviceShared.m_source = 0;
     // No buddies so effectively close the device
     if ((m_deviceAPI->getSinkBuddies().size() == 0) && (m_deviceAPI->getSourceBuddies().size() == 0))
     {
         m_deviceShared.m_dev->close();
         delete m_deviceShared.m_dev;
         m_deviceShared.m_dev = 0;
     }
 }
deserialize()
bool BladeRF2Input::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 506 of file bladerf2input.cpp.
References BladeRF2Input::MsgConfigureBladeRF2::create(), BladeRF2InputSettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and BladeRF2InputSettings::resetToDefaults().
Referenced by setThread().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureBladeRF2* message = MsgConfigureBladeRF2::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureBladeRF2* messageToGUI = MsgConfigureBladeRF2::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void BladeRF2Input::destroy () virtual
Implements DeviceSampleSource.
Definition at line 89 of file bladerf2input.cpp.
 {
     delete this;
 }
findThread()
BladeRF2InputThread * BladeRF2Input::findThread () private
Definition at line 208 of file bladerf2input.cpp.
References DeviceAPI::getSourceBuddies(), getThread(), m_deviceAPI, and m_thread.
Referenced by applySettings(), handleMessage(), start(), and stop().
 {
     if (m_thread == 0) // this does not own the thread
     {
         BladeRF2InputThread *bladerf2InputThread = 0;
         // find a buddy that has allocated the thread
         const std::vector<DeviceAPI*>& sourceBuddies = m_deviceAPI->getSourceBuddies();
         std::vector<DeviceAPI*>::const_iterator it = sourceBuddies.begin();
         for (; it != sourceBuddies.end(); ++it)
         {
             BladeRF2Input *buddySource = ((DeviceBladeRF2Shared*) (*it)->getBuddySharedPtr())->m_source;
             if (buddySource)
             {
                 bladerf2InputThread = buddySource->getThread();
                 if (bladerf2InputThread) {
                     break;
                 }
             }
         }
         return bladerf2InputThread;
     }
     else
     {
         return m_thread; // own thread
     }
 }
getBandwidthRange()
void BladeRF2Input::getBandwidthRange (int & min, int & max, int & step)
Definition at line 592 of file bladerf2input.cpp.
References DeviceBladeRF2::getBandwidthRangeRx(), DeviceBladeRF2Shared::m_dev, and m_deviceShared.
Referenced by BladeRF2InputGui::BladeRF2InputGui(), and setSampleRate().
 {
     if (m_deviceShared.m_dev) {
         m_deviceShared.m_dev->getBandwidthRangeRx(min, max, step);
     }
 }
getCenterFrequency()
quint64 BladeRF2Input::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 539 of file bladerf2input.cpp.
References BladeRF2InputSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & BladeRF2Input::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 528 of file bladerf2input.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getFrequencyRange()
void BladeRF2Input::getFrequencyRange (uint64_t & min, uint64_t & max, int & step)
Definition at line 578 of file bladerf2input.cpp.
References DeviceBladeRF2::getFrequencyRangeRx(), DeviceBladeRF2Shared::m_dev, and m_deviceShared.
Referenced by BladeRF2InputGui::BladeRF2InputGui(), setSampleRate(), and BladeRF2InputGui::updateFrequencyLimits().
 {
     if (m_deviceShared.m_dev) {
         m_deviceShared.m_dev->getFrequencyRangeRx(min, max, step);
     }
 }
getGainModes()
const std::vector<GainMode>& BladeRF2Input::getGainModes () inline
Definition at line 158 of file bladerf2input.h.
References handleMessage(), m_gainModes, webapiReportGet(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
Referenced by BladeRF2InputGui::BladeRF2InputGui(), BladeRF2InputGui::on_gainMode_currentIndexChanged(), and webapiFormatDeviceReport().
 { return m_gainModes; }
getGlobalGainRange()
void BladeRF2Input::getGlobalGainRange (int & min, int & max, int & step)
Definition at line 599 of file bladerf2input.cpp.
References DeviceBladeRF2::getGlobalGainRangeRx(), DeviceBladeRF2Shared::m_dev, and m_deviceShared.
Referenced by applySettings(), BladeRF2InputGui::BladeRF2InputGui(), BladeRF2InputGui::handleMessage(), handleMessage(), and setSampleRate().
 {
     if (m_deviceShared.m_dev) {
         m_deviceShared.m_dev->getGlobalGainRangeRx(min, max, step);
     }
 }
getSampleRate()
int BladeRF2Input::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 533 of file bladerf2input.cpp.
References BladeRF2InputSettings::m_devSampleRate, BladeRF2InputSettings::m_log2Decim, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     int rate = m_settings.m_devSampleRate;
     return (rate / (1<<m_settings.m_log2Decim));
 }
getSampleRateRange()
void BladeRF2Input::getSampleRateRange (int & min, int & max, int & step)
Definition at line 585 of file bladerf2input.cpp.
References DeviceBladeRF2::getSampleRateRangeRx(), DeviceBladeRF2Shared::m_dev, and m_deviceShared.
Referenced by BladeRF2InputGui::BladeRF2InputGui(), BladeRF2InputGui::displaySampleRate(), and setSampleRate().
 {
     if (m_deviceShared.m_dev) {
         m_deviceShared.m_dev->getSampleRateRangeRx(min, max, step);
     }
 }
getThread()
BladeRF2InputThread* BladeRF2Input::getThread () inline
Definition at line 141 of file bladerf2input.h.
References m_thread.
Referenced by findThread().
 { return m_thread; }
handleMessage()
bool BladeRF2Input::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 606 of file bladerf2input.cpp.
References applySettings(), DeviceSampleSource::calculateDeviceCenterFrequency(), BladeRF2Input::MsgConfigureBladeRF2::create(), BladeRF2Input::MsgReportGainRange::create(), findThread(), FileRecord::genUniqueFileName(), DeviceBladeRF2Shared::MsgReportBuddyChange::getCenterFrequency(), DeviceBladeRF2::getDev(), DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceAPI::getDeviceItemIndex(), DeviceAPI::getDeviceUID(), DeviceBladeRF2Shared::MsgReportBuddyChange::getDevSampleRate(), DeviceBladeRF2Shared::MsgReportBuddyChange::getFcPos(), BladeRF2Input::MsgConfigureBladeRF2::getForce(), getGlobalGainRange(), DeviceBladeRF2Shared::MsgReportBuddyChange::getLOppmTenths(), DeviceSampleSource::getMessageQueueToGUI(), DeviceBladeRF2Shared::MsgReportBuddyChange::getRxElseTx(), BladeRF2Input::MsgConfigureBladeRF2::getSettings(), BladeRF2Input::MsgFileRecord::getStartStop(), BladeRF2Input::MsgStartStop::getStartStop(), FileRecord::handleMessage(), DeviceAPI::initDeviceEngine(), BladeRF2InputSettings::m_bandwidth, BladeRF2InputSettings::m_biasTee, BladeRF2InputSettings::m_centerFrequency, DeviceBladeRF2Shared::m_dev, m_deviceAPI, m_deviceShared, BladeRF2InputSettings::m_devSampleRate, BladeRF2InputSettings::m_fcPos, BladeRF2InputSettings::m_fileRecordName, m_fileSink, BladeRF2InputSettings::m_log2Decim, BladeRF2InputSettings::m_LOppmTenths, m_settings, BladeRF2InputSettings::m_useReverseAPI, Message::match(), leansdr::max(), leansdr::min(), MessageQueue::push(), setDeviceCenterFrequency(), BladeRF2InputThread::setFcPos(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
Referenced by getGainModes().
 {
     if (MsgConfigureBladeRF2::match(message))
     {
         MsgConfigureBladeRF2& conf = (MsgConfigureBladeRF2&) message;
         qDebug() << "BladeRF2Input::handleMessage: MsgConfigureBladeRF2";
         if (!applySettings(conf.getSettings(), conf.getForce()))
         {
             qDebug("BladeRF2Input::handleMessage: MsgConfigureBladeRF2 config error");
         }
         return true;
     }
     else if (DeviceBladeRF2Shared::MsgReportBuddyChange::match(message))
     {
         DeviceBladeRF2Shared::MsgReportBuddyChange& report = (DeviceBladeRF2Shared::MsgReportBuddyChange&) message;
         struct bladerf *dev = m_deviceShared.m_dev->getDev();
         BladeRF2InputSettings settings = m_settings;
         int status;
         unsigned int tmp_uint;
         bool tmp_bool;
         // evaluate changes that may have been introduced by changes in a buddy
         if (dev) // The BladeRF device must have been open to do so
         {
             int requestedChannel = m_deviceAPI->getDeviceItemIndex();
             if (report.getRxElseTx()) // Rx buddy change: check for: frequency, LO correction, gain mode and value, bias tee, sample rate, bandwidth
             {
                 settings.m_devSampleRate = report.getDevSampleRate();
                 settings.m_LOppmTenths = report.getLOppmTenths();
                 settings.m_centerFrequency = report.getCenterFrequency();
                 settings.m_fcPos = (BladeRF2InputSettings::fcPos_t) report.getFcPos();
                 BladeRF2InputThread *inputThread = findThread();
                 if (inputThread) {
                     inputThread->setFcPos(requestedChannel, (int) settings.m_fcPos);
                 }
                 status = bladerf_get_bandwidth(dev, BLADERF_CHANNEL_RX(requestedChannel), &tmp_uint);
                 if (status < 0) {
                     qCritical("BladeRF2Input::handleMessage: MsgReportBuddyChange: bladerf_get_bandwidth error: %s", bladerf_strerror(status));
                 } else {
                     settings.m_bandwidth = tmp_uint;
                 }
                 status = bladerf_get_bias_tee(dev, BLADERF_CHANNEL_RX(requestedChannel), &tmp_bool);
                 if (status < 0) {
                     qCritical("BladeRF2Input::handleMessage: MsgReportBuddyChange: bladerf_get_bias_tee error: %s", bladerf_strerror(status));
                 } else {
                     settings.m_biasTee = tmp_bool;
                 }
             }
             else // Tx buddy change: check for sample rate change only
             {
                 settings.m_devSampleRate = report.getDevSampleRate();
 //                status = bladerf_get_sample_rate(dev, BLADERF_CHANNEL_RX(requestedChannel), &tmp_uint);
 //
 //                if (status < 0) {
 //                    qCritical("BladeRF2Input::handleMessage: MsgReportBuddyChange: bladerf_get_sample_rate error: %s", bladerf_strerror(status));
 //                } else {
 //                    settings.m_devSampleRate = tmp_uint;
 //                }
                 qint64 deviceCenterFrequency = DeviceSampleSource::calculateDeviceCenterFrequency(
                         settings.m_centerFrequency,
                         0,
                         settings.m_log2Decim,
                         (DeviceSampleSource::fcPos_t) settings.m_fcPos,
                         settings.m_devSampleRate,
                         DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD,
                         false);
                 if (setDeviceCenterFrequency(dev, requestedChannel, deviceCenterFrequency, settings.m_LOppmTenths))
                 {
                     if (getMessageQueueToGUI())
                     {
                         int min, max, step;
                         getGlobalGainRange(min, max, step);
                         MsgReportGainRange *msg = MsgReportGainRange::create(min, max, step);
                         getMessageQueueToGUI()->push(msg);
                     }
                 }
             }
             // change DSP settings if buddy change introduced a change in center frequency or base rate
             if ((settings.m_centerFrequency != m_settings.m_centerFrequency) || (settings.m_devSampleRate != m_settings.m_devSampleRate))
             {
                 int sampleRate = settings.m_devSampleRate/(1<<settings.m_log2Decim);
                 DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, settings.m_centerFrequency);
                 m_fileSink->handleMessage(*notif); // forward to file sink
                 m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
             }
             m_settings = settings; // acknowledge the new settings
             // propagate settings to GUI if any
             if (getMessageQueueToGUI())
             {
                 MsgConfigureBladeRF2 *reportToGUI = MsgConfigureBladeRF2::create(m_settings, false);
                 getMessageQueueToGUI()->push(reportToGUI);
             }
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "BladeRF2Input::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "BladeRF2Input::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void BladeRF2Input::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 203 of file bladerf2input.cpp.
References applySettings(), and m_settings.
 {
     applySettings(m_settings, true);
 }
moveThreadToBuddy()
void BladeRF2Input::moveThreadToBuddy () private
Definition at line 240 of file bladerf2input.cpp.
References DeviceAPI::getSourceBuddies(), m_deviceAPI, m_thread, and setThread().
Referenced by closeDevice().
 {
     const std::vector<DeviceAPI*>& sourceBuddies = m_deviceAPI->getSourceBuddies();
     std::vector<DeviceAPI*>::const_iterator it = sourceBuddies.begin();
     for (; it != sourceBuddies.end(); ++it)
     {
         BladeRF2Input *buddySource = ((DeviceBladeRF2Shared*) (*it)->getBuddySharedPtr())->m_source;
         if (buddySource)
         {
             buddySource->setThread(m_thread);
             m_thread = 0;  // zero for others
         }
     }
 }
networkManagerFinished
void BladeRF2Input::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 1350 of file bladerf2input.cpp.
Referenced by ~BladeRF2Input().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "BladeRF2Input::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("BladeRF2Input::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openDevice()
bool BladeRF2Input::openDevice () private
Definition at line 94 of file bladerf2input.cpp.
References DeviceAPI::getBuddySharedPtr(), DeviceAPI::getDeviceItemIndex(), DeviceAPI::getSamplingDeviceSerial(), DeviceAPI::getSinkBuddies(), DeviceAPI::getSourceBuddies(), DeviceBladeRF2Shared::m_channel, DeviceBladeRF2Shared::m_dev, m_deviceAPI, m_deviceShared, DeviceSampleSource::m_sampleFifo, DeviceBladeRF2Shared::m_source, DeviceBladeRF2::open(), DeviceAPI::setBuddySharedPtr(), and SampleSinkFifo::setSize().
 {
     if (!m_sampleFifo.setSize(96000 * 4))
     {
         qCritical("BladeRF2Input::openDevice: could not allocate SampleFifo");
         return false;
     }
     else
     {
         qDebug("BladeRF2Input::openDevice: allocated SampleFifo");
     }
     // look for Rx buddies and get reference to the device object
     if (m_deviceAPI->getSourceBuddies().size() > 0) // look source sibling first
     {
         qDebug("BladeRF2Input::openDevice: look in Rx buddies");
         DeviceAPI *sourceBuddy = m_deviceAPI->getSourceBuddies()[0];
         DeviceBladeRF2Shared *deviceBladeRF2Shared = (DeviceBladeRF2Shared*) sourceBuddy->getBuddySharedPtr();
         if (deviceBladeRF2Shared == 0)
         {
             qCritical("BladeRF2Input::openDevice: the source buddy shared pointer is null");
             return false;
         }
         DeviceBladeRF2 *device = deviceBladeRF2Shared->m_dev;
         if (device == 0)
         {
             qCritical("BladeRF2Input::openDevice: cannot get device pointer from Rx buddy");
             return false;
         }
         m_deviceShared.m_dev = device;
     }
     // look for Tx buddies and get reference to the device object
     else if (m_deviceAPI->getSinkBuddies().size() > 0) // then sink
     {
         qDebug("BladeRF2Input::openDevice: look in Tx buddies");
         DeviceAPI *sinkBuddy = m_deviceAPI->getSinkBuddies()[0];
         DeviceBladeRF2Shared *deviceBladeRF2Shared = (DeviceBladeRF2Shared*) sinkBuddy->getBuddySharedPtr();
         if (deviceBladeRF2Shared == 0)
         {
             qCritical("BladeRF2Input::openDevice: the sink buddy shared pointer is null");
             return false;
         }
         DeviceBladeRF2 *device = deviceBladeRF2Shared->m_dev;
         if (device == 0)
         {
             qCritical("BladeRF2Input::openDevice: cannot get device pointer from Tx buddy");
             return false;
         }
         m_deviceShared.m_dev = device;
     }
     // There are no buddies then create the first BladeRF2 device
     else
     {
         qDebug("BladeRF2Input::openDevice: open device here");
         m_deviceShared.m_dev = new DeviceBladeRF2();
         char serial[256];
         strcpy(serial, qPrintable(m_deviceAPI->getSamplingDeviceSerial()));
         if (!m_deviceShared.m_dev->open(serial))
         {
             qCritical("BladeRF2Input::openDevice: cannot open BladeRF2 device");
             return false;
         }
     }
     m_deviceShared.m_channel = m_deviceAPI->getDeviceItemIndex(); // publicly allocate channel
     m_deviceShared.m_source = this;
     m_deviceAPI->setBuddySharedPtr(&m_deviceShared); // propagate common parameters to API
     return true;
 }
serialize()
QByteArray BladeRF2Input::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 501 of file bladerf2input.cpp.
References m_settings, and BladeRF2InputSettings::serialize().
Referenced by setThread().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void BladeRF2Input::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 544 of file bladerf2input.cpp.
References BladeRF2Input::MsgConfigureBladeRF2::create(), BladeRF2InputSettings::m_centerFrequency, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     BladeRF2InputSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureBladeRF2* message = MsgConfigureBladeRF2::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureBladeRF2* messageToGUI = MsgConfigureBladeRF2::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setDeviceCenterFrequency()
bool BladeRF2Input::setDeviceCenterFrequency (struct bladerf * dev, int requestedChannel, quint64 freq_hz, int loPpmTenths) private
Definition at line 559 of file bladerf2input.cpp.
Referenced by applySettings(), and handleMessage().
 {
     qint64 df = ((qint64)freq_hz * loPpmTenths) / 10000000LL;
     freq_hz += df;
     int status = bladerf_set_frequency(dev, BLADERF_CHANNEL_RX(requestedChannel), freq_hz);
     if (status < 0) {
         qWarning("BladeRF2Input::setDeviceCenterFrequency: bladerf_set_frequency(%lld) failed: %s",
                 freq_hz, bladerf_strerror(status));
         return false;
     }
     else
     {
         qDebug("BladeRF2Input::setDeviceCenterFrequency: bladerf_set_frequency(%lld)", freq_hz);
         return true;
     }
 }
setMessageQueueToGUI()
virtual void BladeRF2Input::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 147 of file bladerf2input.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSource::m_guiMessageQueue.
Referenced by BladeRF2InputGui::BladeRF2InputGui().
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void BladeRF2Input::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 150 of file bladerf2input.h.
References getBandwidthRange(), getCenterFrequency(), getFrequencyRange(), getGlobalGainRange(), getSampleRateRange(), leansdr::max(), leansdr::min(), and setCenterFrequency().
 { (void) sampleRate; }
setThread()
void BladeRF2Input::setThread (BladeRF2InputThread * thread) inline
Definition at line 142 of file bladerf2input.h.
References deserialize(), m_thread, and serialize().
Referenced by moveThreadToBuddy().
 { m_thread = thread; }
start()
bool BladeRF2Input::start () virtual
Implements DeviceSampleSource.
Definition at line 257 of file bladerf2input.cpp.
References applySettings(), findThread(), DeviceBladeRF2::getDev(), DeviceAPI::getDeviceItemIndex(), BladeRF2InputThread::getFcPos(), BladeRF2InputThread::getFifo(), BladeRF2InputThread::getLog2Decimation(), BladeRF2InputThread::getNbChannels(), DeviceAPI::getSourceBuddies(), i, DeviceBladeRF2Shared::m_dev, m_deviceAPI, m_deviceShared, BladeRF2InputSettings::m_fcPos, BladeRF2InputSettings::m_log2Decim, m_running, DeviceSampleSource::m_sampleFifo, m_settings, m_thread, DeviceBladeRF2::openRx(), BladeRF2InputThread::setFcPos(), BladeRF2InputThread::setFifo(), BladeRF2InputThread::setLog2Decimation(), BladeRF2InputThread::startWork(), and BladeRF2InputThread::stopWork().
 {
     // There is a single thread per physical device (Rx side). This thread is unique and referenced by a unique
     // buddy in the group of source buddies associated with this physical device.
     //
     // This start method is responsible for managing the thread and channel enabling when the streaming of a Rx channel is started
     //
     // It checks the following conditions
     //   - the thread is allocated or not (by itself or one of its buddies). If it is it grabs the thread pointer.
     //   - the requested channel is the first (0) or the following (just 1 in BladeRF 2 case)
     //
     // The BladeRF support library lets you work in two possible modes:
     //   - Single Input (SI) with only one channel streaming. This HAS to be channel 0.
     //   - Multiple Input (MI) with two channels streaming using interleaved samples. It MUST be in this configuration if channel 1
     //     is used irrespective of what you actually do with samples coming from channel 0. When we will run with only channel 1
     //     streaming from the client perspective the channel 0 will actually be enabled and streaming but its samples will
     //     just be disregarded.
     //
     // It manages the transition form SI where only one channel (the first or channel 0) should be running to the
     // Multiple Input (MI) if the requested channel is 1. More generally it checks if the requested channel is within the current
     // channel range allocated in the thread or past it. To perform the transition it stops the thread, deletes it and creates a new one.
     // It marks the thread as needing start.
     //
     // If the requested channel is within the thread channel range (this thread being already allocated) it simply adds its FIFO reference
     // so that the samples are fed to the FIFO and leaves the thread unchanged (no stop, no delete/new)
     //
     // If there is no thread allocated it creates a new one with a number of channels that fits the requested channel. That is
     // 1 if channel 0 is requested (SI mode) and 2 if channel 1 is requested (MI mode). It marks the thread as needing start.
     //
     // Eventually it registers the FIFO in the thread. If the thread has to be started it enables the channels up to the number of channels
     // allocated in the thread and starts the thread.
     if (!m_deviceShared.m_dev)
     {
         qDebug("BladeRF2Input::start: no device object");
         return false;
     }
     int requestedChannel = m_deviceAPI->getDeviceItemIndex();
     BladeRF2InputThread *bladerf2InputThread = findThread();
     bool needsStart = false;
     if (bladerf2InputThread) // if thread is already allocated
     {
         qDebug("BladeRF2Input::start: thread is already allocated");
         int nbOriginalChannels = bladerf2InputThread->getNbChannels();
         if (requestedChannel+1 > nbOriginalChannels) // expansion by deleting and re-creating the thread
         {
             qDebug("BladeRF2Input::start: expand channels. Re-allocate thread and take ownership");
             SampleSinkFifo **fifos = new SampleSinkFifo*[nbOriginalChannels];
             unsigned int *log2Decims = new unsigned int[nbOriginalChannels];
             int *fcPoss = new int[nbOriginalChannels];
             for (int i = 0; i < nbOriginalChannels; i++) // save original FIFO references and data
             {
                 fifos[i] = bladerf2InputThread->getFifo(i);
                 log2Decims[i] = bladerf2InputThread->getLog2Decimation(i);
                 fcPoss[i] = bladerf2InputThread->getFcPos(i);
             }
             bladerf2InputThread->stopWork();
             delete bladerf2InputThread;
             bladerf2InputThread = new BladeRF2InputThread(m_deviceShared.m_dev->getDev(), requestedChannel+1);
             m_thread = bladerf2InputThread; // take ownership
             for (int i = 0; i < nbOriginalChannels; i++) // restore original FIFO references
             {
                 bladerf2InputThread->setFifo(i, fifos[i]);
                 bladerf2InputThread->setLog2Decimation(i, log2Decims[i]);
                 bladerf2InputThread->setFcPos(i, fcPoss[i]);
             }
             // remove old thread address from buddies (reset in all buddies). The address being held only in the owning source.
             const std::vector<DeviceAPI*>& sourceBuddies = m_deviceAPI->getSourceBuddies();
             std::vector<DeviceAPI*>::const_iterator it = sourceBuddies.begin();
             for (; it != sourceBuddies.end(); ++it) {
                 ((DeviceBladeRF2Shared*) (*it)->getBuddySharedPtr())->m_source->setThread(0);
             }
             // was used as temporary storage:
             delete[] fifos;
             delete[] log2Decims;
             delete[] fcPoss;
             needsStart = true;
         }
         else
         {
             qDebug("BladeRF2Input::start: keep buddy thread");
         }
     }
     else // first allocation
     {
         qDebug("BladeRF2Input::start: allocate thread and take ownership");
         bladerf2InputThread = new BladeRF2InputThread(m_deviceShared.m_dev->getDev(), requestedChannel+1);
         m_thread = bladerf2InputThread; // take ownership
         needsStart = true;
     }
     bladerf2InputThread->setFifo(requestedChannel, &m_sampleFifo);
     bladerf2InputThread->setLog2Decimation(requestedChannel, m_settings.m_log2Decim);
     bladerf2InputThread->setFcPos(requestedChannel, (int) m_settings.m_fcPos);
     if (needsStart)
     {
         qDebug("BladeRF2Input::start: enabling channel(s) and (re)sart buddy thread");
         int nbChannels = bladerf2InputThread->getNbChannels();
         for (int i = 0; i < nbChannels; i++)
         {
             if (!m_deviceShared.m_dev->openRx(i)) {
                 qCritical("BladeRF2Input::start: channel %u cannot be enabled", i);
             }
         }
         bladerf2InputThread->startWork();
     }
     applySettings(m_settings, true);
     qDebug("BladeRF2Input::start: started");
     m_running = true;
     return true;
 }
stop()
void BladeRF2Input::stop () virtual
Implements DeviceSampleSource.
Definition at line 388 of file bladerf2input.cpp.
References DeviceBladeRF2::closeRx(), findThread(), DeviceBladeRF2::getDev(), DeviceAPI::getDeviceItemIndex(), BladeRF2InputThread::getFcPos(), BladeRF2InputThread::getFifo(), BladeRF2InputThread::getLog2Decimation(), BladeRF2InputThread::getNbChannels(), DeviceAPI::getSourceBuddies(), i, DeviceBladeRF2Shared::m_dev, m_deviceAPI, m_deviceShared, m_running, m_thread, BladeRF2InputThread::setFcPos(), BladeRF2InputThread::setFifo(), BladeRF2InputThread::setLog2Decimation(), BladeRF2InputThread::startWork(), and BladeRF2InputThread::stopWork().
Referenced by closeDevice(), and ~BladeRF2Input().
 {
     // This stop method is responsible for managing the thread and channel disabling when the streaming of
     // a Rx channel is stopped
     //
     // If the thread is currently managing only one channel (SI mode). The thread can be just stopped and deleted.
     // Then the channel is closed (disabled).
     //
     // If the thread is currently managing many channels (MI mode) and we are removing the last channel. The transition
     // from MI to SI or reduction of MI size is handled by stopping the thread, deleting it and creating a new one
     // with one channel less if (and only if) there is still a channel active.
     //
     // If the thread is currently managing many channels (MI mode) but the channel being stopped is not the last
     // channel then the FIFO reference is simply removed from the thread so that it will not stream into this FIFO
     // anymore. In this case the channel is not closed (disabled) so that other channels can continue with the
     // same configuration. The device continues streaming on this channel but the samples are simply dropped (by
     // removing FIFO reference).
     if (!m_running) {
         return;
     }
     int requestedChannel = m_deviceAPI->getDeviceItemIndex();
     BladeRF2InputThread *bladerf2InputThread = findThread();
     if (bladerf2InputThread == 0) { // no thread allocated
         return;
     }
     int nbOriginalChannels = bladerf2InputThread->getNbChannels();
     if (nbOriginalChannels == 1) // SI mode => just stop and delete the thread
     {
         qDebug("BladeRF2Input::stop: SI mode. Just stop and delete the thread");
         bladerf2InputThread->stopWork();
         delete bladerf2InputThread;
         m_thread = 0;
         // remove old thread address from buddies (reset in all buddies)
         const std::vector<DeviceAPI*>& sourceBuddies = m_deviceAPI->getSourceBuddies();
         std::vector<DeviceAPI*>::const_iterator it = sourceBuddies.begin();
         for (; it != sourceBuddies.end(); ++it) {
             ((DeviceBladeRF2Shared*) (*it)->getBuddySharedPtr())->m_source->setThread(0);
         }
         m_deviceShared.m_dev->closeRx(0); // close the unique channel
     }
     else if (requestedChannel == nbOriginalChannels - 1) // remove last MI channel => reduce by deleting and re-creating the thread
     {
         qDebug("BladeRF2Input::stop: MI mode. Reduce by deleting and re-creating the thread");
         bladerf2InputThread->stopWork();
         SampleSinkFifo **fifos = new SampleSinkFifo*[nbOriginalChannels-1];
         unsigned int *log2Decims = new unsigned int[nbOriginalChannels-1];
         int *fcPoss = new int[nbOriginalChannels-1];
         bool stillActiveFIFO = false;
         for (int i = 0; i < nbOriginalChannels-1; i++) // save original FIFO references
         {
             fifos[i] = bladerf2InputThread->getFifo(i);
             stillActiveFIFO = stillActiveFIFO || (bladerf2InputThread->getFifo(i) != 0);
             log2Decims[i] = bladerf2InputThread->getLog2Decimation(i);
             fcPoss[i] = bladerf2InputThread->getFcPos(i);
         }
         delete bladerf2InputThread;
         m_thread = 0;
         if (stillActiveFIFO)
         {
             bladerf2InputThread = new BladeRF2InputThread(m_deviceShared.m_dev->getDev(), nbOriginalChannels-1);
             m_thread = bladerf2InputThread; // take ownership
             for (int i = 0; i < nbOriginalChannels-1; i++)  // restore original FIFO references
             {
                 bladerf2InputThread->setFifo(i, fifos[i]);
                 bladerf2InputThread->setLog2Decimation(i, log2Decims[i]);
                 bladerf2InputThread->setFcPos(i, fcPoss[i]);
             }
         }
         else
         {
             qDebug("BladeRF2Input::stop: do not re-create thread as there are no more FIFOs active");
         }
         // remove old thread address from buddies (reset in all buddies). The address being held only in the owning source.
         const std::vector<DeviceAPI*>& sourceBuddies = m_deviceAPI->getSourceBuddies();
         std::vector<DeviceAPI*>::const_iterator it = sourceBuddies.begin();
         for (; it != sourceBuddies.end(); ++it) {
             ((DeviceBladeRF2Shared*) (*it)->getBuddySharedPtr())->m_source->setThread(0);
         }
         m_deviceShared.m_dev->closeRx(requestedChannel); // close the last channel
         if (stillActiveFIFO) {
             bladerf2InputThread->startWork();
         }
         // was used as temporary storage:
         delete[] fifos;
         delete[] log2Decims;
         delete[] fcPoss;
     }
     else // remove channel from existing thread
     {
         qDebug("BladeRF2Input::stop: MI mode. Not changing MI configuration. Just remove FIFO reference");
         bladerf2InputThread->setFifo(requestedChannel, 0); // remove FIFO
     }
     m_running = false;
 }
webapiFormatDeviceReport()
void BladeRF2Input::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 1171 of file bladerf2input.cpp.
References SWGSDRangel::SWGBladeRF2InputReport::getBandwidthRange(), DeviceBladeRF2::getBandwidthRangeRx(), SWGSDRangel::SWGDeviceReport::getBladeRf2InputReport(), SWGSDRangel::SWGBladeRF2InputReport::getFrequencyRange(), DeviceBladeRF2::getFrequencyRangeRx(), SWGSDRangel::SWGBladeRF2InputReport::getGainModes(), getGainModes(), SWGSDRangel::SWGBladeRF2InputReport::getGlobalGainRange(), DeviceBladeRF2::getGlobalGainRangeRx(), SWGSDRangel::SWGBladeRF2InputReport::getSampleRateRange(), DeviceBladeRF2::getSampleRateRangeRx(), DeviceBladeRF2Shared::m_dev, m_deviceShared, leansdr::max(), leansdr::min(), SWGSDRangel::SWGBladeRF2InputReport::setBandwidthRange(), SWGSDRangel::SWGBladeRF2InputReport::setFrequencyRange(), SWGSDRangel::SWGBladeRF2InputReport::setGainModes(), SWGSDRangel::SWGBladeRF2InputReport::setGlobalGainRange(), SWGSDRangel::SWGFrequencyRange::setMax(), SWGSDRangel::SWGRange::setMax(), SWGSDRangel::SWGRange::setMin(), SWGSDRangel::SWGFrequencyRange::setMin(), SWGSDRangel::SWGBladeRF2InputReport::setSampleRateRange(), SWGSDRangel::SWGFrequencyRange::setStep(), and SWGSDRangel::SWGRange::setStep().
Referenced by webapiReportGet().
 {
     DeviceBladeRF2 *device = m_deviceShared.m_dev;
     if (device)
     {
         int min, max, step;
         uint64_t f_min, f_max;
         device->getBandwidthRangeRx(min, max, step);
         response.getBladeRf2InputReport()->setBandwidthRange(new SWGSDRangel::SWGRange);
         response.getBladeRf2InputReport()->getBandwidthRange()->setMin(min);
         response.getBladeRf2InputReport()->getBandwidthRange()->setMax(max);
         response.getBladeRf2InputReport()->getBandwidthRange()->setStep(step);
         device->getFrequencyRangeRx(f_min, f_max, step);
         response.getBladeRf2InputReport()->setFrequencyRange(new SWGSDRangel::SWGFrequencyRange);
         response.getBladeRf2InputReport()->getFrequencyRange()->setMin(f_min);
         response.getBladeRf2InputReport()->getFrequencyRange()->setMax(f_max);
         response.getBladeRf2InputReport()->getFrequencyRange()->setStep(step);
         device->getGlobalGainRangeRx(min, max, step);
         response.getBladeRf2InputReport()->setGlobalGainRange(new SWGSDRangel::SWGRange);
         response.getBladeRf2InputReport()->getGlobalGainRange()->setMin(min);
         response.getBladeRf2InputReport()->getGlobalGainRange()->setMax(max);
         response.getBladeRf2InputReport()->getGlobalGainRange()->setStep(step);
         device->getSampleRateRangeRx(min, max, step);
         response.getBladeRf2InputReport()->setSampleRateRange(new SWGSDRangel::SWGRange);
         response.getBladeRf2InputReport()->getSampleRateRange()->setMin(min);
         response.getBladeRf2InputReport()->getSampleRateRange()->setMax(max);
         response.getBladeRf2InputReport()->getSampleRateRange()->setStep(step);
         response.getBladeRf2InputReport()->setGainModes(new QList<SWGSDRangel::SWGNamedEnum*>);
         const std::vector<GainMode>& modes = getGainModes();
         std::vector<GainMode>::const_iterator it = modes.begin();
         for (; it != modes.end(); ++it)
         {
             response.getBladeRf2InputReport()->getGainModes()->append(new SWGSDRangel::SWGNamedEnum);
             response.getBladeRf2InputReport()->getGainModes()->back()->setName(new QString(it->m_name));
             response.getBladeRf2InputReport()->getGainModes()->back()->setValue(it->m_value);
         }
     }
 }
webapiFormatDeviceSettings()
void BladeRF2Input::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const BladeRF2InputSettings & settings) private
Definition at line 1137 of file bladerf2input.cpp.
References SWGSDRangel::SWGDeviceSettings::getBladeRf2InputSettings(), SWGSDRangel::SWGBladeRF2InputSettings::getFileRecordName(), SWGSDRangel::SWGBladeRF2InputSettings::getReverseApiAddress(), BladeRF2InputSettings::m_bandwidth, BladeRF2InputSettings::m_biasTee, BladeRF2InputSettings::m_centerFrequency, BladeRF2InputSettings::m_dcBlock, BladeRF2InputSettings::m_devSampleRate, BladeRF2InputSettings::m_fcPos, BladeRF2InputSettings::m_fileRecordName, BladeRF2InputSettings::m_gainMode, BladeRF2InputSettings::m_globalGain, BladeRF2InputSettings::m_iqCorrection, BladeRF2InputSettings::m_log2Decim, BladeRF2InputSettings::m_LOppmTenths, BladeRF2InputSettings::m_reverseAPIAddress, BladeRF2InputSettings::m_reverseAPIDeviceIndex, BladeRF2InputSettings::m_reverseAPIPort, BladeRF2InputSettings::m_transverterDeltaFrequency, BladeRF2InputSettings::m_transverterMode, BladeRF2InputSettings::m_useReverseAPI, SWGSDRangel::SWGBladeRF2InputSettings::setBandwidth(), SWGSDRangel::SWGBladeRF2InputSettings::setBiasTee(), SWGSDRangel::SWGBladeRF2InputSettings::setCenterFrequency(), SWGSDRangel::SWGBladeRF2InputSettings::setDcBlock(), SWGSDRangel::SWGBladeRF2InputSettings::setDevSampleRate(), SWGSDRangel::SWGBladeRF2InputSettings::setFcPos(), SWGSDRangel::SWGBladeRF2InputSettings::setFileRecordName(), SWGSDRangel::SWGBladeRF2InputSettings::setGainMode(), SWGSDRangel::SWGBladeRF2InputSettings::setGlobalGain(), SWGSDRangel::SWGBladeRF2InputSettings::setIqCorrection(), SWGSDRangel::SWGBladeRF2InputSettings::setLog2Decim(), SWGSDRangel::SWGBladeRF2InputSettings::setLOppmTenths(), SWGSDRangel::SWGBladeRF2InputSettings::setReverseApiAddress(), SWGSDRangel::SWGBladeRF2InputSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGBladeRF2InputSettings::setReverseApiPort(), SWGSDRangel::SWGBladeRF2InputSettings::setTransverterDeltaFrequency(), SWGSDRangel::SWGBladeRF2InputSettings::setTransverterMode(), and SWGSDRangel::SWGBladeRF2InputSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getBladeRf2InputSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getBladeRf2InputSettings()->setLOppmTenths(settings.m_LOppmTenths);
     response.getBladeRf2InputSettings()->setDevSampleRate(settings.m_devSampleRate);
     response.getBladeRf2InputSettings()->setBandwidth(settings.m_bandwidth);
     response.getBladeRf2InputSettings()->setLog2Decim(settings.m_log2Decim);
     response.getBladeRf2InputSettings()->setFcPos((int) settings.m_fcPos);
     response.getBladeRf2InputSettings()->setDcBlock(settings.m_dcBlock ? 1 : 0);
     response.getBladeRf2InputSettings()->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     response.getBladeRf2InputSettings()->setBiasTee(settings.m_biasTee ? 1 : 0);
     response.getBladeRf2InputSettings()->setGainMode(settings.m_gainMode);
     response.getBladeRf2InputSettings()->setGlobalGain(settings.m_globalGain);
     response.getBladeRf2InputSettings()->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     response.getBladeRf2InputSettings()->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     if (response.getBladeRf2InputSettings()->getFileRecordName()) {
         *response.getBladeRf2InputSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getBladeRf2InputSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getBladeRf2InputSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getBladeRf2InputSettings()->getReverseApiAddress()) {
         *response.getBladeRf2InputSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getBladeRf2InputSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getBladeRf2InputSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getBladeRf2InputSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int BladeRF2Input::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 1128 of file bladerf2input.cpp.
References SWGSDRangel::SWGDeviceReport::getBladeRf2InputReport(), SWGSDRangel::SWGBladeRF2InputReport::init(), SWGSDRangel::SWGDeviceReport::setBladeRf2InputReport(), and webapiFormatDeviceReport().
Referenced by getGainModes().
 {
     (void) errorMessage;
     response.setBladeRf2InputReport(new SWGSDRangel::SWGBladeRF2InputReport());
     response.getBladeRf2InputReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void BladeRF2Input::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const BladeRF2InputSettings & settings, bool force) private
Definition at line 1250 of file bladerf2input.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), SWGSDRangel::SWGDeviceSettings::getBladeRf2InputSettings(), DeviceAPI::getDeviceSetIndex(), BladeRF2InputSettings::m_bandwidth, BladeRF2InputSettings::m_biasTee, BladeRF2InputSettings::m_centerFrequency, BladeRF2InputSettings::m_dcBlock, m_deviceAPI, BladeRF2InputSettings::m_devSampleRate, BladeRF2InputSettings::m_fcPos, BladeRF2InputSettings::m_fileRecordName, BladeRF2InputSettings::m_gainMode, BladeRF2InputSettings::m_globalGain, BladeRF2InputSettings::m_iqCorrection, BladeRF2InputSettings::m_log2Decim, BladeRF2InputSettings::m_LOppmTenths, m_networkManager, m_networkRequest, BladeRF2InputSettings::m_reverseAPIAddress, BladeRF2InputSettings::m_reverseAPIDeviceIndex, BladeRF2InputSettings::m_reverseAPIPort, BladeRF2InputSettings::m_transverterDeltaFrequency, BladeRF2InputSettings::m_transverterMode, SWGSDRangel::SWGBladeRF2InputSettings::setBandwidth(), SWGSDRangel::SWGBladeRF2InputSettings::setBiasTee(), SWGSDRangel::SWGDeviceSettings::setBladeRf2InputSettings(), SWGSDRangel::SWGBladeRF2InputSettings::setCenterFrequency(), SWGSDRangel::SWGBladeRF2InputSettings::setDcBlock(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGBladeRF2InputSettings::setDevSampleRate(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGBladeRF2InputSettings::setFcPos(), SWGSDRangel::SWGBladeRF2InputSettings::setFileRecordName(), SWGSDRangel::SWGBladeRF2InputSettings::setGainMode(), SWGSDRangel::SWGBladeRF2InputSettings::setGlobalGain(), SWGSDRangel::SWGBladeRF2InputSettings::setIqCorrection(), SWGSDRangel::SWGBladeRF2InputSettings::setLog2Decim(), SWGSDRangel::SWGBladeRF2InputSettings::setLOppmTenths(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGBladeRF2InputSettings::setTransverterDeltaFrequency(), and SWGSDRangel::SWGBladeRF2InputSettings::setTransverterMode().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("BladeRF2"));
     swgDeviceSettings->setBladeRf2InputSettings(new SWGSDRangel::SWGBladeRF2InputSettings());
     SWGSDRangel::SWGBladeRF2InputSettings *swgBladeRF2Settings = swgDeviceSettings->getBladeRf2InputSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgBladeRF2Settings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("LOppmTenths") || force) {
         swgBladeRF2Settings->setLOppmTenths(settings.m_LOppmTenths);
     }
     if (deviceSettingsKeys.contains("log2Decim") || force) {
         swgBladeRF2Settings->setLog2Decim(settings.m_log2Decim);
     }
     if (deviceSettingsKeys.contains("fcPos") || force) {
         swgBladeRF2Settings->setFcPos((int) settings.m_fcPos);
     }
     if (deviceSettingsKeys.contains("dcBlock") || force) {
         swgBladeRF2Settings->setDcBlock(settings.m_dcBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("iqCorrection") || force) {
         swgBladeRF2Settings->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency") || force) {
         swgBladeRF2Settings->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     }
     if (deviceSettingsKeys.contains("transverterMode") || force) {
         swgBladeRF2Settings->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgBladeRF2Settings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     if (deviceSettingsKeys.contains("devSampleRate")) {
         swgBladeRF2Settings->setDevSampleRate(settings.m_devSampleRate);
     }
     if (deviceSettingsKeys.contains("bandwidth")) {
         swgBladeRF2Settings->setBandwidth(settings.m_bandwidth);
     }
     if (deviceSettingsKeys.contains("biasTee")) {
         swgBladeRF2Settings->setBiasTee(settings.m_biasTee);
     }
     if (deviceSettingsKeys.contains("gainMode")) {
         swgBladeRF2Settings->setGainMode(settings.m_gainMode);
     }
     if (deviceSettingsKeys.contains("globalGain")) {
         swgBladeRF2Settings->setGlobalGain(settings.m_globalGain);
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void BladeRF2Input::webapiReverseSendStartStop (bool start) private
Definition at line 1322 of file bladerf2input.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, BladeRF2InputSettings::m_reverseAPIAddress, BladeRF2InputSettings::m_reverseAPIDeviceIndex, BladeRF2InputSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("BladeRF2"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int BladeRF2Input::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 1231 of file bladerf2input.cpp.
References BladeRF2Input::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by getGainModes().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int BladeRF2Input::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 1222 of file bladerf2input.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by getGainModes().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int BladeRF2Input::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 1040 of file bladerf2input.cpp.
References SWGSDRangel::SWGDeviceSettings::getBladeRf2InputSettings(), SWGSDRangel::SWGBladeRF2InputSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setBladeRf2InputSettings(), and webapiFormatDeviceSettings().
Referenced by getGainModes().
 {
     (void) errorMessage;
     response.setBladeRf2InputSettings(new SWGSDRangel::SWGBladeRF2InputSettings());
     response.getBladeRf2InputSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int BladeRF2Input::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 1051 of file bladerf2input.cpp.
References BladeRF2Input::MsgConfigureBladeRF2::create(), SWGSDRangel::SWGBladeRF2InputSettings::getBandwidth(), SWGSDRangel::SWGBladeRF2InputSettings::getBiasTee(), SWGSDRangel::SWGDeviceSettings::getBladeRf2InputSettings(), SWGSDRangel::SWGBladeRF2InputSettings::getCenterFrequency(), SWGSDRangel::SWGBladeRF2InputSettings::getDcBlock(), SWGSDRangel::SWGBladeRF2InputSettings::getDevSampleRate(), SWGSDRangel::SWGBladeRF2InputSettings::getFcPos(), SWGSDRangel::SWGBladeRF2InputSettings::getFileRecordName(), SWGSDRangel::SWGBladeRF2InputSettings::getGainMode(), SWGSDRangel::SWGBladeRF2InputSettings::getGlobalGain(), SWGSDRangel::SWGBladeRF2InputSettings::getIqCorrection(), SWGSDRangel::SWGBladeRF2InputSettings::getLog2Decim(), SWGSDRangel::SWGBladeRF2InputSettings::getLOppmTenths(), SWGSDRangel::SWGBladeRF2InputSettings::getReverseApiAddress(), SWGSDRangel::SWGBladeRF2InputSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGBladeRF2InputSettings::getReverseApiPort(), SWGSDRangel::SWGBladeRF2InputSettings::getTransverterDeltaFrequency(), SWGSDRangel::SWGBladeRF2InputSettings::getTransverterMode(), SWGSDRangel::SWGBladeRF2InputSettings::getUseReverseApi(), BladeRF2InputSettings::m_bandwidth, BladeRF2InputSettings::m_biasTee, BladeRF2InputSettings::m_centerFrequency, BladeRF2InputSettings::m_dcBlock, BladeRF2InputSettings::m_devSampleRate, BladeRF2InputSettings::m_fcPos, BladeRF2InputSettings::m_fileRecordName, BladeRF2InputSettings::m_gainMode, BladeRF2InputSettings::m_globalGain, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, BladeRF2InputSettings::m_iqCorrection, BladeRF2InputSettings::m_log2Decim, BladeRF2InputSettings::m_LOppmTenths, BladeRF2InputSettings::m_reverseAPIAddress, BladeRF2InputSettings::m_reverseAPIDeviceIndex, BladeRF2InputSettings::m_reverseAPIPort, m_settings, BladeRF2InputSettings::m_transverterDeltaFrequency, BladeRF2InputSettings::m_transverterMode, BladeRF2InputSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by getGainModes().
 {
     (void) errorMessage;
     BladeRF2InputSettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getBladeRf2InputSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("LOppmTenths")) {
         settings.m_LOppmTenths = response.getBladeRf2InputSettings()->getLOppmTenths();
     }
     if (deviceSettingsKeys.contains("devSampleRate")) {
         settings.m_devSampleRate = response.getBladeRf2InputSettings()->getDevSampleRate();
     }
     if (deviceSettingsKeys.contains("bandwidth")) {
         settings.m_bandwidth = response.getBladeRf2InputSettings()->getBandwidth();
     }
     if (deviceSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getBladeRf2InputSettings()->getLog2Decim();
     }
     if (deviceSettingsKeys.contains("fcPos")) {
         settings.m_fcPos = static_cast<BladeRF2InputSettings::fcPos_t>(response.getBladeRf2InputSettings()->getFcPos());
     }
     if (deviceSettingsKeys.contains("dcBlock")) {
         settings.m_dcBlock = response.getBladeRf2InputSettings()->getDcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("iqCorrection")) {
         settings.m_iqCorrection = response.getBladeRf2InputSettings()->getIqCorrection() != 0;
     }
     if (deviceSettingsKeys.contains("biasTee")) {
         settings.m_biasTee = response.getBladeRf2InputSettings()->getBiasTee() != 0;
     }
     if (deviceSettingsKeys.contains("gainMode")) {
         settings.m_gainMode = response.getBladeRf2InputSettings()->getGainMode();
     }
     if (deviceSettingsKeys.contains("globalGain")) {
         settings.m_globalGain = response.getBladeRf2InputSettings()->getGlobalGain();
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency")) {
         settings.m_transverterDeltaFrequency = response.getBladeRf2InputSettings()->getTransverterDeltaFrequency();
     }
     if (deviceSettingsKeys.contains("transverterMode")) {
         settings.m_transverterMode = response.getBladeRf2InputSettings()->getTransverterMode() != 0;
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getBladeRf2InputSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getBladeRf2InputSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getBladeRf2InputSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getBladeRf2InputSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getBladeRf2InputSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureBladeRF2 *msg = MsgConfigureBladeRF2::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureBladeRF2 *msgToGUI = MsgConfigureBladeRF2::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_deviceAPI
DeviceAPI* BladeRF2Input::m_deviceAPI private
Definition at line 186 of file bladerf2input.h.
Referenced by applySettings(), closeDevice(), findThread(), handleMessage(), moveThreadToBuddy(), openDevice(), start(), stop(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~BladeRF2Input().
m_deviceDescription
QString BladeRF2Input::m_deviceDescription private
Definition at line 189 of file bladerf2input.h.
Referenced by getDeviceDescription().
m_deviceShared
DeviceBladeRF2Shared BladeRF2Input::m_deviceShared private
Definition at line 191 of file bladerf2input.h.
Referenced by applySettings(), closeDevice(), getBandwidthRange(), getFrequencyRange(), getGlobalGainRange(), getSampleRateRange(), handleMessage(), openDevice(), start(), stop(), and webapiFormatDeviceReport().
m_fileSink
FileRecord* BladeRF2Input::m_fileSink private
File sink to record device I/Q output.
Definition at line 193 of file bladerf2input.h.
Referenced by applySettings(), handleMessage(), and ~BladeRF2Input().
m_gainModes
std::vector<GainMode> BladeRF2Input::m_gainModes private
Definition at line 194 of file bladerf2input.h.
Referenced by getGainModes().
m_mutex
QMutex BladeRF2Input::m_mutex private
Definition at line 187 of file bladerf2input.h.
m_networkManager
QNetworkAccessManager* BladeRF2Input::m_networkManager private
Definition at line 195 of file bladerf2input.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~BladeRF2Input().
m_networkRequest
QNetworkRequest BladeRF2Input::m_networkRequest private
Definition at line 196 of file bladerf2input.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool BladeRF2Input::m_running private
Definition at line 190 of file bladerf2input.h.
Referenced by closeDevice(), start(), stop(), and ~BladeRF2Input().
m_settings
BladeRF2InputSettings BladeRF2Input::m_settings private
Definition at line 188 of file bladerf2input.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), serialize(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_thread
BladeRF2InputThread* BladeRF2Input::m_thread private
Definition at line 192 of file bladerf2input.h.
Referenced by closeDevice(), findThread(), getThread(), moveThreadToBuddy(), setThread(), start(), and stop().
The documentation for this class was generated from the following files:
plugins/samplesource/bladerf2input/bladerf2input.h
plugins/samplesource/bladerf2input/bladerf2input.cpp