SDRAngel: SWGSDRangel::SWGBandwidth Class Reference
SWGSDRangel::SWGBandwidth Class Reference
#include <SWGBandwidth.h>
Public Member Functions
SWGBandwidth ()
SWGBandwidth (QString *json)
virtual ~SWGBandwidth ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGBandwidth * fromJson (QString &jsonString) override
qint32 getBandwidth ()
void setBandwidth (qint32 bandwidth)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 bandwidth
bool m_bandwidth_isSet
Detailed Description
Definition at line 31 of file SWGBandwidth.h.
Constructor & Destructor Documentation
SWGBandwidth() [1/2]
SWGSDRangel::SWGBandwidth::SWGBandwidth ()
Definition at line 30 of file SWGBandwidth.cpp.
References bandwidth, and m_bandwidth_isSet.
{
     bandwidth = 0;
     m_bandwidth_isSet = false;
 }
SWGBandwidth() [2/2]
SWGSDRangel::SWGBandwidth::SWGBandwidth (QString * json)
Definition at line 25 of file SWGBandwidth.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGBandwidth()
SWGSDRangel::SWGBandwidth::~SWGBandwidth () virtual
Definition at line 35 of file SWGBandwidth.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGBandwidth::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 66 of file SWGBandwidth.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGBandwidth::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 77 of file SWGBandwidth.cpp.
References bandwidth, and m_bandwidth_isSet.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_bandwidth_isSet){
         obj->insert("bandwidth", QJsonValue(bandwidth));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGBandwidth::cleanup ()
Definition at line 46 of file SWGBandwidth.cpp.
Referenced by ~SWGBandwidth().
                       {
 }
fromJson()
SWGBandwidth * SWGSDRangel::SWGBandwidth::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 51 of file SWGBandwidth.cpp.
References fromJsonObject().
Referenced by SWGBandwidth().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGBandwidth::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 60 of file SWGBandwidth.cpp.
References bandwidth, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&bandwidth, pJson["bandwidth"], "qint32", "");
 }
getBandwidth()
qint32 SWGSDRangel::SWGBandwidth::getBandwidth ()
Definition at line 87 of file SWGBandwidth.cpp.
References bandwidth.
{
     return bandwidth;
 }
init()
void SWGSDRangel::SWGBandwidth::init ()
Definition at line 40 of file SWGBandwidth.cpp.
References bandwidth, and m_bandwidth_isSet.
Referenced by SWGBandwidth().
                    {
     bandwidth = 0;
     m_bandwidth_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGBandwidth::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 98 of file SWGBandwidth.cpp.
References m_bandwidth_isSet.
                    {
     bool isObjectUpdated = false;
     do{
         if(m_bandwidth_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setBandwidth()
void SWGSDRangel::SWGBandwidth::setBandwidth (qint32 bandwidth)
Definition at line 91 of file SWGBandwidth.cpp.
References bandwidth, and m_bandwidth_isSet.
{
     this->bandwidth = bandwidth;
     this->m_bandwidth_isSet = true;
 }
Member Data Documentation
bandwidth
qint32 SWGSDRangel::SWGBandwidth::bandwidth private
Definition at line 51 of file SWGBandwidth.h.
Referenced by asJsonObject(), fromJsonObject(), getBandwidth(), init(), setBandwidth(), and SWGBandwidth().
m_bandwidth_isSet
bool SWGSDRangel::SWGBandwidth::m_bandwidth_isSet private
Definition at line 52 of file SWGBandwidth.h.
Referenced by asJsonObject(), init(), isSet(), setBandwidth(), and SWGBandwidth().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGBandwidth.h
swagger/sdrangel/code/qt5/client/SWGBandwidth.cpp