SDRAngel: RemoteSource::MsgConfigureRemoteSource Class Reference
RemoteSource::MsgConfigureRemoteSource Class Reference
#include <remotesource.h>
Public Member Functions
const RemoteSourceSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureRemoteSource * create (const RemoteSourceSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureRemoteSource (const RemoteSourceSettings &settings, bool force)
Private Attributes
RemoteSourceSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 48 of file remotesource.h.
Constructor & Destructor Documentation
MsgConfigureRemoteSource()
RemoteSource::MsgConfigureRemoteSource::MsgConfigureRemoteSource (const RemoteSourceSettings & settings, bool force) inline private
Definition at line 64 of file remotesource.h.
Referenced by create().
                                                                                    :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureRemoteSource* RemoteSource::MsgConfigureRemoteSource::create (const RemoteSourceSettings & settings, bool force) inline static
Definition at line 55 of file remotesource.h.
References MsgConfigureRemoteSource().
Referenced by RemoteSourceGUI::applySettings(), RemoteSource::deserialize(), RemoteSource::setDataLink(), and RemoteSource::webapiSettingsPutPatch().
         {
             return new MsgConfigureRemoteSource(settings, force);
         }
getForce()
bool RemoteSource::MsgConfigureRemoteSource::getForce () const inline
Definition at line 53 of file remotesource.h.
References m_force.
Referenced by RemoteSource::handleMessage().
 { return m_force; }
getSettings()
const RemoteSourceSettings& RemoteSource::MsgConfigureRemoteSource::getSettings () const inline
Definition at line 52 of file remotesource.h.
References m_settings.
Referenced by RemoteSourceGUI::handleMessage(), and RemoteSource::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool RemoteSource::MsgConfigureRemoteSource::m_force private
Definition at line 62 of file remotesource.h.
Referenced by getForce().
m_settings
RemoteSourceSettings RemoteSource::MsgConfigureRemoteSource::m_settings private
Definition at line 61 of file remotesource.h.
Referenced by getSettings(), and RemoteSource::getTitle().
The documentation for this class was generated from the following file:
plugins/channeltx/remotesource/remotesource.h