SDRAngel: leansdr::pipewriter< T > Struct Template Reference
leansdr::pipewriter< T > Struct Template Reference
#include <framework.h>
Public Member Functions
pipewriter (pipebuf< T > &_buf, unsigned long min_write=1)
long writable ()
T * wr ()
void written (unsigned long n)
void write (const T &e)
Public Attributes
pipebuf< T > & buf
Detailed Description
template<typename T>
struct leansdr::pipewriter< T >
Definition at line 286 of file framework.h.
Constructor & Destructor Documentation
pipewriter()
template<typename T> leansdr::pipewriter< T >::pipewriter (pipebuf< T > & _buf, unsigned long min_write = 1) inline
Definition at line 290 of file framework.h.
                                                               : buf(_buf)
     {
         if (min_write > buf.min_write)
             buf.min_write = min_write;
     }
Member Function Documentation
wr()
template<typename T> T* leansdr::pipewriter< T >::wr () inline
Definition at line 303 of file framework.h.
Referenced by leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::receive_frame(), leansdr::etr192_descrambler::run(), leansdr::simple_agc< T >::run(), leansdr::s2_interleaver::run(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::run(), leansdr::s2_fecenc::run(), leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::run(), leansdr::s2_framer::run(), and leansdr::s2_deframer::run_bbframe().
     {
         return buf.wr;
     }
writable()
template<typename T> long leansdr::pipewriter< T >::writable () inline
Definition at line 296 of file framework.h.
Referenced by leansdr::opt_writable(), leansdr::etr192_descrambler::run(), leansdr::simple_agc< T >::run(), leansdr::s2_interleaver::run(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::run(), leansdr::viterbi_sync::run(), leansdr::s2_fecenc::run(), leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::run(), leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::run(), leansdr::s2_framer::run(), and leansdr::s2_deframer::run().
     {
         if (buf.end < buf.min_write + buf.wr)
             buf.pack();
         return buf.end - buf.wr;
     }
write()
template<typename T> void leansdr::pipewriter< T >::write (const T & e) inline
Definition at line 319 of file framework.h.
Referenced by leansdr::opt_write(), and leansdr::viterbi_sync::run().
     {
         *wr() = e;
         written(1);
     }
written()
template<typename T> void leansdr::pipewriter< T >::written (unsigned long n) inline
Definition at line 308 of file framework.h.
Referenced by leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::receive_frame(), leansdr::etr192_descrambler::run(), leansdr::simple_agc< T >::run(), leansdr::s2_interleaver::run(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::run(), leansdr::s2_fecenc::run(), leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::run(), leansdr::s2_framer::run(), and leansdr::s2_deframer::run_bbframe().
     {
         if (buf.wr + n > buf.end)
         {
             fprintf(stderr, "Bug: overflow to %s\n", buf.name);
         }
         buf.wr += n;
         buf.total_written += n;
     }
Member Data Documentation
buf
template<typename T> pipebuf<T>& leansdr::pipewriter< T >::buf
Definition at line 288 of file framework.h.
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/framework.h