SDRAngel: qtwebapp::LoggerWithFile Class Reference
qtwebapp::LoggerWithFile Class Reference
#include <loggerwithfile.h>
Public Member Functions
LoggerWithFile (QObject *parent=0)
virtual ~LoggerWithFile ()
void createOrSetFileLogger (const FileLoggerSettings &settings, const int refreshInterval=10000)
void destroyFileLogger ()
virtual void log (const QtMsgType type, const QString &message, const QString &file="", const QString &function="", const int line=0)
virtual void clear (const bool buffer=true, const bool variables=true)
bool getUseFileLogger () const
void setUseFileLogger (bool use)
bool hasFileLogger () const
FileLoggerSettings getFileLoggerSettings () const
void setFileLoggerSettings (const FileLoggerSettings &settings)
void setConsoleMinMessageLevel (const QtMsgType &msgLevel)
void setFileMinMessageLevel (const QtMsgType &msgLevel)
void getConsoleMinMessageLevelStr (QString &levelStr)
void getFileMinMessageLevelStr (QString &levelStr)
void getLogFileName (QString &fileName)
void logToFile (const QtMsgType type, const QString &message, const QString &file="", const QString &function="", const int line=0)
Public Member Functions inherited from qtwebapp::Logger
Logger (QObject *parent)
Logger (const QString msgFormat="{timestamp} {type} {msg}", const QString timestampFormat="yyyy-MM-dd HH:mm:ss.zzz", const QtMsgType minLevel=QtDebugMsg, const int bufferSize=0, QObject *parent=0)
virtual ~Logger ()
void installMsgHandler ()
void setMinMessageLevel (const QtMsgType &minMsgLevel)
QtMsgType getMinMessageLevel () const
Private Attributes
Logger * consoleLogger
FileLogger * fileLogger
bool useFileFlogger
Additional Inherited Members
Static Public Member Functions inherited from qtwebapp::Logger
static void set (const QString &name, const QString &value)
Protected Member Functions inherited from qtwebapp::Logger
virtual void write (const LogMessage *logMessage)
Protected Attributes inherited from qtwebapp::Logger
QString msgFormat
QString timestampFormat
QtMsgType minLevel
int bufferSize
Static Protected Attributes inherited from qtwebapp::Logger
static QMutex mutex
Detailed Description
Logs messages to console and optionally to a file simultaneously.
See also
FileLogger for a description of the two underlying file logger.
Logger for a description of the console loger.
Definition at line 25 of file loggerwithfile.h.
Constructor & Destructor Documentation
LoggerWithFile()
LoggerWithFile::LoggerWithFile (QObject * parent = 0)
Definition at line 12 of file loggerwithfile.cpp.
References consoleLogger, and qtwebapp::Logger::Logger().
     :Logger(parent), fileLogger(0), useFileFlogger(false)
 {
      consoleLogger = new Logger(this);
 }
~LoggerWithFile()
LoggerWithFile::~LoggerWithFile () virtual
Definition at line 18 of file loggerwithfile.cpp.
References consoleLogger, and destroyFileLogger().
 {
     destroyFileLogger();
     delete consoleLogger;
 }
Member Function Documentation
clear()
void LoggerWithFile::clear (const bool buffer = true, const bool variables = true) virtual
Clear the thread-local data of the current thread. This method is thread safe.
Parameters
buffer Whether to clear the backtrace buffer
variables Whether to clear the log variables
Reimplemented from qtwebapp::Logger.
Definition at line 58 of file loggerwithfile.cpp.
References qtwebapp::Logger::clear(), consoleLogger, fileLogger, and useFileFlogger.
 {
     consoleLogger->clear(buffer,variables);
     if (fileLogger && useFileFlogger) {
         fileLogger->clear(buffer,variables);
     }
 }
createOrSetFileLogger()
void LoggerWithFile::createOrSetFileLogger (const FileLoggerSettings & settings, const int refreshInterval = 10000)
Definition at line 24 of file loggerwithfile.cpp.
References fileLogger, and qtwebapp::FileLogger::setFileLoggerSettings().
Referenced by MainCore::setLoggingOptions(), and MainWindow::setLoggingOptions().
 {
     if (!fileLogger) {
         fileLogger = new FileLogger(settings, refreshInterval, this);
     } else {
         fileLogger->setFileLoggerSettings(settings);
     }
 }
destroyFileLogger()
void LoggerWithFile::destroyFileLogger ()
Definition at line 33 of file loggerwithfile.cpp.
References fileLogger.
Referenced by ~LoggerWithFile().
 {
     if (fileLogger)
     {
         delete fileLogger;
         fileLogger = 0;
     }
 }
getConsoleMinMessageLevelStr()
void LoggerWithFile::getConsoleMinMessageLevelStr (QString & levelStr)
Definition at line 79 of file loggerwithfile.cpp.
References consoleLogger, and qtwebapp::Logger::getMinMessageLevel().
Referenced by WebAPIAdapterGUI::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingGet(), WebAPIAdapterSrv::instanceSummary(), and WebAPIAdapterGUI::instanceSummary().
 {
     switch (consoleLogger->getMinMessageLevel())
     {
     case QtDebugMsg:
         levelStr = "debug";
         break;
     case QtInfoMsg:
         levelStr = "info";
         break;
     case QtWarningMsg:
         levelStr = "warning";
         break;
     case QtCriticalMsg:
     case QtFatalMsg:
         levelStr = "error";
         break;
     default:
         levelStr = "debug";
         break;
     }
 }
getFileLoggerSettings()
FileLoggerSettings qtwebapp::LoggerWithFile::getFileLoggerSettings () const inline
Get a file logger settings copy
Returns
The current file logger settings
Definition at line 64 of file loggerwithfile.h.
Referenced by MainCore::setLoggingOptions(), and MainWindow::setLoggingOptions().
 { return fileLogger->getFileLoggerSettings(); }
getFileMinMessageLevelStr()
void LoggerWithFile::getFileMinMessageLevelStr (QString & levelStr)
Definition at line 102 of file loggerwithfile.cpp.
References fileLogger, and qtwebapp::Logger::getMinMessageLevel().
Referenced by WebAPIAdapterGUI::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingGet(), WebAPIAdapterSrv::instanceSummary(), and WebAPIAdapterGUI::instanceSummary().
 {
     switch (fileLogger->getMinMessageLevel())
     {
     case QtDebugMsg:
         levelStr = "debug";
         break;
     case QtInfoMsg:
         levelStr = "info";
         break;
     case QtWarningMsg:
         levelStr = "warning";
         break;
     case QtCriticalMsg:
     case QtFatalMsg:
         levelStr = "error";
         break;
     default:
         levelStr = "debug";
         break;
     }
 }
getLogFileName()
void LoggerWithFile::getLogFileName (QString & fileName)
Definition at line 125 of file loggerwithfile.cpp.
References fileLogger, qtwebapp::FileLoggerSettings::fileName, and qtwebapp::FileLogger::getFileLoggerSettings().
Referenced by WebAPIAdapterGUI::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingGet(), WebAPIAdapterSrv::instanceSummary(), and WebAPIAdapterGUI::instanceSummary().
 {
     fileName = fileLogger->getFileLoggerSettings().fileName;
 }
getUseFileLogger()
bool qtwebapp::LoggerWithFile::getUseFileLogger () const inline
Definition at line 56 of file loggerwithfile.h.
Referenced by WebAPIAdapterGUI::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingGet(), WebAPIAdapterSrv::instanceSummary(), and WebAPIAdapterGUI::instanceSummary().
 { return useFileFlogger; }
hasFileLogger()
bool qtwebapp::LoggerWithFile::hasFileLogger () const inline
Definition at line 58 of file loggerwithfile.h.
Referenced by MainCore::setLoggingOptions(), and MainWindow::setLoggingOptions().
 { return fileLogger != 0; }
log()
void LoggerWithFile::log (const QtMsgType type, const QString & message, const QString & file = "", const QString & function = "", const int line = 0) virtual
Decorate and log the message, if type>=minLevel. This method is thread safe.
Parameters
type Message type (level)
message Message text
file Name of the source file where the message was generated (usually filled with the macro FILE)
function Name of the function where the message was generated (usually filled with the macro LINE)
line Line Number of the source file, where the message was generated (usually filles with the macro func or FUNCTION)
See also
LogMessage for a description of the message decoration.
Reimplemented from qtwebapp::Logger.
Definition at line 42 of file loggerwithfile.cpp.
References consoleLogger, fileLogger, qtwebapp::Logger::log(), and useFileFlogger.
 {
     consoleLogger->log(type,message,file,function,line);
     if (fileLogger && useFileFlogger) {
         fileLogger->log(type,message,file,function,line);
     }
 }
logToFile()
void LoggerWithFile::logToFile (const QtMsgType type, const QString & message, const QString & file = "", const QString & function = "", const int line = 0)
This will log to file only
Definition at line 51 of file loggerwithfile.cpp.
References fileLogger, qtwebapp::Logger::log(), and useFileFlogger.
Referenced by MainCore::setLoggingOptions(), and MainWindow::setLoggingOptions().
 {
     if (fileLogger && useFileFlogger) {
         fileLogger->log(type,message,file,function,line);
     }
 }
setConsoleMinMessageLevel()
void LoggerWithFile::setConsoleMinMessageLevel (const QtMsgType & msgLevel)
Definition at line 67 of file loggerwithfile.cpp.
References consoleLogger, and qtwebapp::Logger::setMinMessageLevel().
Referenced by MainCore::setLoggingOptions(), and MainWindow::setLoggingOptions().
 {
     consoleLogger->setMinMessageLevel(msgLevel);
 }
setFileLoggerSettings()
void qtwebapp::LoggerWithFile::setFileLoggerSettings (const FileLoggerSettings & settings) inline
Set new file logger settings data
Parameters
File logger settings to replace current data
Definition at line 70 of file loggerwithfile.h.
 { fileLogger->setFileLoggerSettings(settings); }
setFileMinMessageLevel()
void LoggerWithFile::setFileMinMessageLevel (const QtMsgType & msgLevel)
Definition at line 72 of file loggerwithfile.cpp.
References fileLogger, and qtwebapp::Logger::setMinMessageLevel().
Referenced by MainCore::setLoggingOptions(), and MainWindow::setLoggingOptions().
 {
     if (fileLogger) {
         fileLogger->setMinMessageLevel(msgLevel);
     }
 }
setUseFileLogger()
void qtwebapp::LoggerWithFile::setUseFileLogger (bool use) inline
Definition at line 57 of file loggerwithfile.h.
Referenced by MainCore::setLoggingOptions(), and MainWindow::setLoggingOptions().
 { useFileFlogger = use; }
Member Data Documentation
consoleLogger
Logger* qtwebapp::LoggerWithFile::consoleLogger private
First console logger
Definition at line 84 of file loggerwithfile.h.
Referenced by clear(), getConsoleMinMessageLevelStr(), log(), LoggerWithFile(), setConsoleMinMessageLevel(), and ~LoggerWithFile().
fileLogger
FileLogger* qtwebapp::LoggerWithFile::fileLogger private
Second file logger
Definition at line 87 of file loggerwithfile.h.
Referenced by clear(), createOrSetFileLogger(), destroyFileLogger(), getFileMinMessageLevelStr(), getLogFileName(), log(), logToFile(), and setFileMinMessageLevel().
useFileFlogger
bool qtwebapp::LoggerWithFile::useFileFlogger private
Use file logger indicator
Definition at line 90 of file loggerwithfile.h.
Referenced by clear(), log(), and logToFile().
The documentation for this class was generated from the following files:
logging/loggerwithfile.h
logging/loggerwithfile.cpp