SDRAngel: RemoteSourceGUI Class Reference
RemoteSourceGUI Class Reference
#include <remotesourcegui.h>
Public Slots
void channelMarkerChangedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static RemoteSourceGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx)
Private Slots
void handleSourceMessages ()
void on_dataAddress_returnPressed ()
void on_dataPort_returnPressed ()
void on_dataApplyButton_clicked (bool checked)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void on_eventCountsReset_clicked (bool checked)
void tick ()
Private Member Functions
RemoteSourceGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx, QWidget *parent=0)
virtual ~RemoteSourceGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
void displayEventCounts ()
void displayEventStatus (int recoverableCount, int unrecoverableCount)
void displayEventTimer ()
Private Attributes
Ui::RemoteSourceGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
RemoteSourceSettings m_settings
bool m_doApplySettings
RemoteSource * m_remoteSrc
MessageQueue m_inputMessageQueue
uint32_t m_countUnrecoverable
uint32_t m_countRecovered
uint32_t m_lastCountUnrecoverable
uint32_t m_lastCountRecovered
uint32_t m_lastSampleCount
uint64_t m_lastTimestampUs
bool m_resetCounts
QTime m_time
uint32_t m_tickCount
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 39 of file remotesourcegui.h.
Constructor & Destructor Documentation
RemoteSourceGUI()
RemoteSourceGUI::RemoteSourceGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx, QWidget * parent = 0) explicit private
Definition at line 158 of file remotesourcegui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), channelMarkerChangedByCursor(), displaySettings(), getInputMessageQueue(), DeviceAPI::getMasterTimer(), handleSourceMessages(), RemoteSource::m_channelIdURI, m_channelMarker, DeviceUISet::m_deviceAPI, m_deviceUISet, m_remoteSrc, RemoteSourceSettings::m_rgbColor, m_settings, m_time, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerTxChannelInstance(), ChannelMarker::setCenterFrequency(), RemoteSourceSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSource::setMessageQueueToGUI(), ChannelMarker::setSourceOrSinkStream(), ChannelMarker::setTitle(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                                  :
         RollupWidget(parent),
         ui(new Ui::RemoteSourceGUI),
         m_pluginAPI(pluginAPI),
         m_deviceUISet(deviceUISet),
         m_countUnrecoverable(0),
         m_countRecovered(0),
         m_lastCountUnrecoverable(0),
         m_lastCountRecovered(0),
         m_lastSampleCount(0),
         m_lastTimestampUs(0),
         m_resetCounts(true),
         m_tickCount(0)
 {
     (void) channelTx;
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_remoteSrc = (RemoteSource*) channelTx;
     m_remoteSrc->setMessageQueueToGUI(getInputMessageQueue());
     connect(&(m_deviceUISet->m_deviceAPI->getMasterTimer()), SIGNAL(timeout()), this, SLOT(tick()));
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("Remote source");
     m_channelMarker.setSourceOrSinkStream(false);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     m_settings.setChannelMarker(&m_channelMarker);
     m_deviceUISet->registerTxChannelInstance(RemoteSource::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     m_time.start();
     displaySettings();
     applySettings(true);
 }
~RemoteSourceGUI()
RemoteSourceGUI::~RemoteSourceGUI () private virtual
Definition at line 206 of file remotesourcegui.cpp.
References m_deviceUISet, m_remoteSrc, DeviceUISet::removeTxChannelInstance(), and ui.
 {
     m_deviceUISet->removeTxChannelInstance(this);
     delete m_remoteSrc;
     delete ui;
 }
Member Function Documentation
applySettings()
void RemoteSourceGUI::applySettings (bool force = false) private
Definition at line 218 of file remotesourcegui.cpp.
References RemoteSource::MsgConfigureRemoteSource::create(), ChannelMarker::getColor(), BasebandSampleSource::getInputMessageQueue(), m_channelMarker, m_doApplySettings, m_remoteSrc, m_settings, MessageQueue::push(), and RollupWidget::setTitleColor().
Referenced by deserialize(), on_dataAddress_returnPressed(), on_dataApplyButton_clicked(), on_dataPort_returnPressed(), onMenuDialogCalled(), RemoteSourceGUI(), and resetToDefaults().
 {
     if (m_doApplySettings)
     {
         setTitleColor(m_channelMarker.getColor());
         RemoteSource::MsgConfigureRemoteSource* message = RemoteSource::MsgConfigureRemoteSource::create(m_settings, force);
         m_remoteSrc->getInputMessageQueue()->push(message);
     }
 }
blockApplySettings()
void RemoteSourceGUI::blockApplySettings (bool block) private
Definition at line 213 of file remotesourcegui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void RemoteSourceGUI::channelMarkerChangedByCursor () slot
Definition at line 403 of file remotesourcegui.cpp.
Referenced by RemoteSourceGUI().
 {
 }
create()
RemoteSourceGUI * RemoteSourceGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx) static
Definition at line 28 of file remotesourcegui.cpp.
References RemoteSourceGUI().
Referenced by RemoteSourcePlugin::createTxChannelGUI().
 {
     RemoteSourceGUI* gui = new RemoteSourceGUI(pluginAPI, deviceUISet, channelTx);
     return gui;
 }
deserialize()
bool RemoteSourceGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 70 of file remotesourcegui.cpp.
References applySettings(), RemoteSourceSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void RemoteSourceGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 34 of file remotesourcegui.cpp.
 {
     delete this;
 }
displayEventCounts()
void RemoteSourceGUI::displayEventCounts () private
Definition at line 356 of file remotesourcegui.cpp.
References m_countRecovered, m_countUnrecoverable, and ui.
Referenced by handleMessage(), and on_eventCountsReset_clicked().
 {
     QString nstr = QString("%1").arg(m_countUnrecoverable, 3, 10, QChar('0'));
     ui->eventUnrecText->setText(nstr);
     nstr = QString("%1").arg(m_countRecovered, 3, 10, QChar('0'));
     ui->eventRecText->setText(nstr);
 }
displayEventStatus()
void RemoteSourceGUI::displayEventStatus (int recoverableCount, int unrecoverableCount) private
Definition at line 364 of file remotesourcegui.cpp.
References ui.
Referenced by handleMessage().
 {
     if (unrecoverableCount == 0)
     {
         if (recoverableCount == 0) {
             ui->allFramesDecoded->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->allFramesDecoded->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         }
     }
     else
     {
         ui->allFramesDecoded->setStyleSheet("QToolButton { background-color : red; }");
     }
 }
displayEventTimer()
void RemoteSourceGUI::displayEventTimer () private
Definition at line 381 of file remotesourcegui.cpp.
References m_time, and ui.
Referenced by on_eventCountsReset_clicked(), and tick().
 {
     int elapsedTimeMillis = m_time.elapsed();
     QTime recordLength(0, 0, 0, 0);
     recordLength = recordLength.addSecs(elapsedTimeMillis/1000);
     QString s_time = recordLength.toString("HH:mm:ss");
     ui->eventCountsTimeText->setText(s_time);
 }
displaySettings()
void RemoteSourceGUI::displaySettings () private
Definition at line 229 of file remotesourcegui.cpp.
References arg(), blockApplySettings(), ChannelMarker::getTitle(), m_channelMarker, RemoteSourceSettings::m_dataAddress, RemoteSourceSettings::m_dataPort, RemoteSourceSettings::m_rgbColor, m_settings, RemoteSourceSettings::m_title, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by deserialize(), handleMessage(), RemoteSourceGUI(), and resetToDefaults().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.setBandwidth(5000); // TODO
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->dataAddress->setText(m_settings.m_dataAddress);
     ui->dataPort->setText(tr("%1").arg(m_settings.m_dataPort));
     blockApplySettings(false);
 }
enterEvent()
void RemoteSourceGUI::enterEvent (QEvent *) private
Definition at line 252 of file remotesourcegui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 RemoteSourceGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 49 of file remotesourcegui.cpp.
{
     return 0;
 }
getInputMessageQueue()
virtual MessageQueue* RemoteSourceGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 54 of file remotesourcegui.h.
Referenced by handleSourceMessages(), and RemoteSourceGUI().
 { return &m_inputMessageQueue; }
getName()
QString RemoteSourceGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 44 of file remotesourcegui.cpp.
 {
     return objectName();
 }
handleMessage()
bool RemoteSourceGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 82 of file remotesourcegui.cpp.
References arg(), blockApplySettings(), displayEventCounts(), displayEventStatus(), displaySettings(), RemoteSource::MsgReportStreamData::get_nbCorrectableErrors(), RemoteSource::MsgReportStreamData::get_nbFECBlocks(), RemoteSource::MsgReportStreamData::get_nbOriginalBlocks(), RemoteSource::MsgReportStreamData::get_nbUncorrectableErrors(), RemoteSource::MsgReportStreamData::get_queueLength(), RemoteSource::MsgReportStreamData::get_queueSize(), RemoteSource::MsgReportStreamData::get_readSamplesCount(), RemoteSource::MsgReportStreamData::get_sampleRate(), RemoteSource::MsgReportStreamData::get_tv_sec(), RemoteSource::MsgReportStreamData::get_tv_usec(), RemoteSource::MsgSampleRateNotification::getSampleRate(), RemoteSource::MsgConfigureRemoteSource::getSettings(), m_channelMarker, m_countRecovered, m_countUnrecoverable, m_lastCountRecovered, m_lastCountUnrecoverable, m_lastSampleCount, m_lastTimestampUs, m_resetCounts, m_settings, Message::match(), ChannelMarker::setBandwidth(), and ui.
Referenced by handleSourceMessages().
 {
     if (RemoteSource::MsgSampleRateNotification::match(message))
     {
         RemoteSource::MsgSampleRateNotification& notif = (RemoteSource::MsgSampleRateNotification&) message;
         m_channelMarker.setBandwidth(notif.getSampleRate());
         return true;
     }
     else if (RemoteSource::MsgConfigureRemoteSource::match(message))
     {
         const RemoteSource::MsgConfigureRemoteSource& cfg = (RemoteSource::MsgConfigureRemoteSource&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (RemoteSource::MsgReportStreamData::match(message))
     {
         const RemoteSource::MsgReportStreamData& report = (RemoteSource::MsgReportStreamData&) message;
         ui->sampleRate->setText(QString("%1").arg(report.get_sampleRate()));
         QString nominalNbBlocksText = QString("%1/%2")
                 .arg(report.get_nbOriginalBlocks() + report.get_nbFECBlocks())
                 .arg(report.get_nbFECBlocks());
         ui->nominalNbBlocksText->setText(nominalNbBlocksText);
         QString queueLengthText = QString("%1/%2").arg(report.get_queueLength()).arg(report.get_queueSize());
         ui->queueLengthText->setText(queueLengthText);
         int queueLengthPercent = (report.get_queueLength()*100)/report.get_queueSize();
         ui->queueLengthGauge->setValue(queueLengthPercent);
         int unrecoverableCount = report.get_nbUncorrectableErrors();
         int recoverableCount = report.get_nbCorrectableErrors();
         uint64_t timestampUs = report.get_tv_sec()*1000000ULL + report.get_tv_usec();
         if (!m_resetCounts)
         {
             int recoverableCountDelta = recoverableCount - m_lastCountRecovered;
             int unrecoverableCountDelta = unrecoverableCount - m_lastCountUnrecoverable;
             displayEventStatus(recoverableCountDelta, unrecoverableCountDelta);
             m_countRecovered += recoverableCountDelta;
             m_countUnrecoverable += unrecoverableCountDelta;
             displayEventCounts();
         }
         uint32_t sampleCountDelta, sampleCount;
         sampleCount = report.get_readSamplesCount();
         if (sampleCount < m_lastSampleCount) {
             sampleCountDelta = (0xFFFFFFFFU - sampleCount) + m_lastSampleCount + 1;
         } else {
             sampleCountDelta = sampleCount - m_lastSampleCount;
         }
         if (sampleCountDelta == 0) {
             ui->allFramesDecoded->setStyleSheet("QToolButton { background-color : blue; }");
         }
         double remoteStreamRate = sampleCountDelta*1e6 / (double) (timestampUs - m_lastTimestampUs);
         if (remoteStreamRate != 0) {
             ui->streamRateText->setText(QString("%1").arg(remoteStreamRate, 0, 'f', 0));
         }
         m_resetCounts = false;
         m_lastCountRecovered = recoverableCount;
         m_lastCountUnrecoverable = unrecoverableCount;
         m_lastSampleCount = sampleCount;
         m_lastTimestampUs = timestampUs;
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void RemoteSourceGUI::handleSourceMessages () private slot
Definition at line 257 of file remotesourcegui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by RemoteSourceGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void RemoteSourceGUI::leaveEvent (QEvent *) private
Definition at line 247 of file remotesourcegui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_dataAddress_returnPressed
void RemoteSourceGUI::on_dataAddress_returnPressed () private slot
Definition at line 307 of file remotesourcegui.cpp.
References applySettings(), RemoteSourceSettings::m_dataAddress, m_settings, and ui.
 {
     m_settings.m_dataAddress = ui->dataAddress->text();
     applySettings();
 }
on_dataApplyButton_clicked
void RemoteSourceGUI::on_dataApplyButton_clicked (bool checked) private slot
Definition at line 330 of file remotesourcegui.cpp.
References applySettings(), RemoteSourceSettings::m_dataAddress, RemoteSourceSettings::m_dataPort, m_settings, and ui.
 {
     (void) checked;
     m_settings.m_dataAddress = ui->dataAddress->text();
     bool dataOk;
     int udpDataPort = ui->dataPort->text().toInt(&dataOk);
     if((dataOk) && (udpDataPort >= 1024) && (udpDataPort < 65535))
     {
         m_settings.m_dataPort = udpDataPort;
     }
     applySettings();
 }
on_dataPort_returnPressed
void RemoteSourceGUI::on_dataPort_returnPressed () private slot
Definition at line 313 of file remotesourcegui.cpp.
References applySettings(), RemoteSourceSettings::m_dataPort, m_settings, and ui.
 {
     bool dataOk;
     int dataPort = ui->dataPort->text().toInt(&dataOk);
     if((!dataOk) || (dataPort < 1024) || (dataPort > 65535))
     {
         return;
     }
     else
     {
         m_settings.m_dataPort = dataPort;
     }
     applySettings();
 }
on_eventCountsReset_clicked
void RemoteSourceGUI::on_eventCountsReset_clicked (bool checked) private slot
Definition at line 346 of file remotesourcegui.cpp.
References displayEventCounts(), displayEventTimer(), m_countRecovered, m_countUnrecoverable, and m_time.
 {
     (void) checked;
     m_countUnrecoverable = 0;
     m_countRecovered = 0;
     m_time.start();
     displayEventCounts();
     displayEventTimer();
 }
onMenuDialogCalled
void RemoteSourceGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 276 of file remotesourcegui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, RemoteSourceSettings::m_reverseAPIAddress, RemoteSourceSettings::m_reverseAPIChannelIndex, RemoteSourceSettings::m_reverseAPIDeviceIndex, RemoteSourceSettings::m_reverseAPIPort, RemoteSourceSettings::m_rgbColor, m_settings, RemoteSourceSettings::m_title, RemoteSourceSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by RemoteSourceGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void RemoteSourceGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 270 of file remotesourcegui.cpp.
Referenced by RemoteSourceGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void RemoteSourceGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 58 of file remotesourcegui.cpp.
References applySettings(), displaySettings(), m_settings, and RemoteSourceSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
serialize()
QByteArray RemoteSourceGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 65 of file remotesourcegui.cpp.
References m_settings, and RemoteSourceSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void RemoteSourceGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 53 of file remotesourcegui.cpp.
 {
     (void) centerFrequency;
 }
setName()
void RemoteSourceGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 39 of file remotesourcegui.cpp.
 {
     setObjectName(name);
 }
tick
void RemoteSourceGUI::tick () private slot
Definition at line 390 of file remotesourcegui.cpp.
References RemoteSource::MsgQueryStreamData::create(), displayEventTimer(), BasebandSampleSource::getInputMessageQueue(), m_remoteSrc, m_tickCount, and MessageQueue::push().
Referenced by RemoteSourceGUI().
 {
     if (++m_tickCount == 20) // once per second
     {
         RemoteSource::MsgQueryStreamData *msg = RemoteSource::MsgQueryStreamData::create();
         m_remoteSrc->getInputMessageQueue()->push(msg);
         displayEventTimer();
         m_tickCount = 0;
     }
 }
Member Data Documentation
m_channelMarker
ChannelMarker RemoteSourceGUI::m_channelMarker private
Definition at line 64 of file remotesourcegui.h.
Referenced by applySettings(), displaySettings(), enterEvent(), handleMessage(), leaveEvent(), onMenuDialogCalled(), and RemoteSourceGUI().
m_countRecovered
uint32_t RemoteSourceGUI::m_countRecovered private
Definition at line 72 of file remotesourcegui.h.
Referenced by displayEventCounts(), handleMessage(), and on_eventCountsReset_clicked().
m_countUnrecoverable
uint32_t RemoteSourceGUI::m_countUnrecoverable private
Definition at line 71 of file remotesourcegui.h.
Referenced by displayEventCounts(), handleMessage(), and on_eventCountsReset_clicked().
m_deviceUISet
DeviceUISet* RemoteSourceGUI::m_deviceUISet private
Definition at line 63 of file remotesourcegui.h.
Referenced by RemoteSourceGUI(), and ~RemoteSourceGUI().
m_doApplySettings
bool RemoteSourceGUI::m_doApplySettings private
Definition at line 66 of file remotesourcegui.h.
Referenced by applySettings(), and blockApplySettings().
m_inputMessageQueue
MessageQueue RemoteSourceGUI::m_inputMessageQueue private
Definition at line 69 of file remotesourcegui.h.
m_lastCountRecovered
uint32_t RemoteSourceGUI::m_lastCountRecovered private
Definition at line 74 of file remotesourcegui.h.
Referenced by handleMessage().
m_lastCountUnrecoverable
uint32_t RemoteSourceGUI::m_lastCountUnrecoverable private
Definition at line 73 of file remotesourcegui.h.
Referenced by handleMessage().
m_lastSampleCount
uint32_t RemoteSourceGUI::m_lastSampleCount private
Definition at line 75 of file remotesourcegui.h.
Referenced by handleMessage().
m_lastTimestampUs
uint64_t RemoteSourceGUI::m_lastTimestampUs private
Definition at line 76 of file remotesourcegui.h.
Referenced by handleMessage().
m_pluginAPI
PluginAPI* RemoteSourceGUI::m_pluginAPI private
Definition at line 62 of file remotesourcegui.h.
m_remoteSrc
RemoteSource* RemoteSourceGUI::m_remoteSrc private
Definition at line 68 of file remotesourcegui.h.
Referenced by applySettings(), RemoteSourceGUI(), tick(), and ~RemoteSourceGUI().
m_resetCounts
bool RemoteSourceGUI::m_resetCounts private
Definition at line 77 of file remotesourcegui.h.
Referenced by handleMessage().
m_settings
RemoteSourceSettings RemoteSourceGUI::m_settings private
Definition at line 65 of file remotesourcegui.h.
Referenced by applySettings(), deserialize(), displaySettings(), handleMessage(), on_dataAddress_returnPressed(), on_dataApplyButton_clicked(), on_dataPort_returnPressed(), onMenuDialogCalled(), RemoteSourceGUI(), resetToDefaults(), and serialize().
m_tickCount
uint32_t RemoteSourceGUI::m_tickCount private
Definition at line 79 of file remotesourcegui.h.
Referenced by tick().
m_time
QTime RemoteSourceGUI::m_time private
Definition at line 78 of file remotesourcegui.h.
Referenced by displayEventTimer(), on_eventCountsReset_clicked(), and RemoteSourceGUI().
ui
Ui::RemoteSourceGUI* RemoteSourceGUI::ui private
Definition at line 61 of file remotesourcegui.h.
Referenced by displayEventCounts(), displayEventStatus(), displayEventTimer(), displaySettings(), handleMessage(), on_dataAddress_returnPressed(), on_dataApplyButton_clicked(), on_dataPort_returnPressed(), RemoteSourceGUI(), and ~RemoteSourceGUI().
The documentation for this class was generated from the following files:
plugins/channeltx/remotesource/remotesourcegui.h
plugins/channeltx/remotesource/remotesourcegui.cpp