SDRAngel: SWGSDRangel::SWGRangeFloat Class Reference
SWGSDRangel::SWGRangeFloat Class Reference
#include <SWGRangeFloat.h>
Public Member Functions
SWGRangeFloat ()
SWGRangeFloat (QString *json)
virtual ~SWGRangeFloat ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGRangeFloat * fromJson (QString &jsonString) override
float getMin ()
void setMin (float min)
float getMax ()
void setMax (float max)
float getStep ()
void setStep (float step)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
float min
bool m_min_isSet
float max
bool m_max_isSet
float step
bool m_step_isSet
Detailed Description
Definition at line 31 of file SWGRangeFloat.h.
Constructor & Destructor Documentation
SWGRangeFloat() [1/2]
SWGSDRangel::SWGRangeFloat::SWGRangeFloat ()
Definition at line 30 of file SWGRangeFloat.cpp.
References m_max_isSet, m_min_isSet, m_step_isSet, max, min, and step.
{
     min = 0.0f;
     m_min_isSet = false;
     max = 0.0f;
     m_max_isSet = false;
     step = 0.0f;
     m_step_isSet = false;
 }
SWGRangeFloat() [2/2]
SWGSDRangel::SWGRangeFloat::SWGRangeFloat (QString * json)
Definition at line 25 of file SWGRangeFloat.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGRangeFloat()
SWGSDRangel::SWGRangeFloat::~SWGRangeFloat () virtual
Definition at line 39 of file SWGRangeFloat.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGRangeFloat::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 80 of file SWGRangeFloat.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGRangeFloat::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 91 of file SWGRangeFloat.cpp.
References m_max_isSet, m_min_isSet, m_step_isSet, max, min, and step.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_min_isSet){
         obj->insert("min", QJsonValue(min));
     }
     if(m_max_isSet){
         obj->insert("max", QJsonValue(max));
     }
     if(m_step_isSet){
         obj->insert("step", QJsonValue(step));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGRangeFloat::cleanup ()
Definition at line 54 of file SWGRangeFloat.cpp.
Referenced by ~SWGRangeFloat().
{
 }
fromJson()
SWGRangeFloat * SWGSDRangel::SWGRangeFloat::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 61 of file SWGRangeFloat.cpp.
References fromJsonObject().
Referenced by SWGRangeFloat().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGRangeFloat::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 70 of file SWGRangeFloat.cpp.
References max, min, SWGSDRangel::setValue(), and step.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&min, pJson["min"], "float", "");
     ::SWGSDRangel::setValue(&max, pJson["max"], "float", "");
     ::SWGSDRangel::setValue(&step, pJson["step"], "float", "");
 }
getMax()
float SWGSDRangel::SWGRangeFloat::getMax ()
Definition at line 117 of file SWGRangeFloat.cpp.
References max.
                       {
     return max;
 }
getMin()
float SWGSDRangel::SWGRangeFloat::getMin ()
Definition at line 107 of file SWGRangeFloat.cpp.
References min.
                       {
     return min;
 }
getStep()
float SWGSDRangel::SWGRangeFloat::getStep ()
Definition at line 127 of file SWGRangeFloat.cpp.
References step.
{
     return step;
 }
init()
void SWGSDRangel::SWGRangeFloat::init ()
Definition at line 44 of file SWGRangeFloat.cpp.
References m_max_isSet, m_min_isSet, m_step_isSet, max, min, and step.
Referenced by SWGRangeFloat().
                     {
     min = 0.0f;
     m_min_isSet = false;
     max = 0.0f;
     m_max_isSet = false;
     step = 0.0f;
     m_step_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGRangeFloat::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 138 of file SWGRangeFloat.cpp.
References m_max_isSet, m_min_isSet, and m_step_isSet.
Referenced by SWGSDRangel::SWGSoapySDRGainSetting::asJsonObject(), SWGSDRangel::SWGArgInfo::asJsonObject(), SWGSDRangel::SWGSoapySDRReport::asJsonObject(), SWGSDRangel::SWGSoapySDRGainSetting::isSet(), SWGSDRangel::SWGArgInfo::isSet(), and SWGSDRangel::SWGSoapySDRReport::isSet().
                     {
     bool isObjectUpdated = false;
     do{
         if(m_min_isSet){ isObjectUpdated = true; break;}
         if(m_max_isSet){ isObjectUpdated = true; break;}
         if(m_step_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setMax()
void SWGSDRangel::SWGRangeFloat::setMax (float max)
Definition at line 121 of file SWGRangeFloat.cpp.
References m_max_isSet, and max.
Referenced by SoapySDROutput::webapiFormatArgInfo(), SoapySDRInput::webapiFormatArgInfo(), SoapySDROutput::webapiFormatDeviceReport(), and SoapySDRInput::webapiFormatDeviceReport().
{
     this->max = max;
     this->m_max_isSet = true;
 }
setMin()
void SWGSDRangel::SWGRangeFloat::setMin (float min)
Definition at line 111 of file SWGRangeFloat.cpp.
References m_min_isSet, and min.
Referenced by SoapySDROutput::webapiFormatArgInfo(), SoapySDRInput::webapiFormatArgInfo(), SoapySDROutput::webapiFormatDeviceReport(), and SoapySDRInput::webapiFormatDeviceReport().
{
     this->min = min;
     this->m_min_isSet = true;
 }
setStep()
void SWGSDRangel::SWGRangeFloat::setStep (float step)
Definition at line 131 of file SWGRangeFloat.cpp.
References m_step_isSet, and step.
{
     this->step = step;
     this->m_step_isSet = true;
 }
Member Data Documentation
m_max_isSet
bool SWGSDRangel::SWGRangeFloat::m_max_isSet private
Definition at line 61 of file SWGRangeFloat.h.
Referenced by asJsonObject(), init(), isSet(), setMax(), and SWGRangeFloat().
m_min_isSet
bool SWGSDRangel::SWGRangeFloat::m_min_isSet private
Definition at line 58 of file SWGRangeFloat.h.
Referenced by asJsonObject(), init(), isSet(), setMin(), and SWGRangeFloat().
m_step_isSet
bool SWGSDRangel::SWGRangeFloat::m_step_isSet private
Definition at line 64 of file SWGRangeFloat.h.
Referenced by asJsonObject(), init(), isSet(), setStep(), and SWGRangeFloat().
max
float SWGSDRangel::SWGRangeFloat::max private
Definition at line 60 of file SWGRangeFloat.h.
Referenced by asJsonObject(), fromJsonObject(), getMax(), init(), setMax(), and SWGRangeFloat().
min
float SWGSDRangel::SWGRangeFloat::min private
Definition at line 57 of file SWGRangeFloat.h.
Referenced by asJsonObject(), fromJsonObject(), getMin(), init(), setMin(), and SWGRangeFloat().
step
float SWGSDRangel::SWGRangeFloat::step private
Definition at line 63 of file SWGRangeFloat.h.
Referenced by asJsonObject(), fromJsonObject(), getStep(), init(), setStep(), and SWGRangeFloat().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGRangeFloat.h
swagger/sdrangel/code/qt5/client/SWGRangeFloat.cpp