SDRAngel: ATVMod::MsgConfigureVideoFileName Class Reference
ATVMod::MsgConfigureVideoFileName Class Reference
#include <atvmod.h>
Public Member Functions
const QString & getFileName () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureVideoFileName * create (const QString &fileName)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureVideoFileName (const QString &fileName)
Private Attributes
QString m_fileName
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 117 of file atvmod.h.
Constructor & Destructor Documentation
MsgConfigureVideoFileName()
ATVMod::MsgConfigureVideoFileName::MsgConfigureVideoFileName (const QString & fileName) inline private
Definition at line 132 of file atvmod.h.
                                                            :
             Message(),
             m_fileName(fileName)
         { }
Member Function Documentation
create()
static MsgConfigureVideoFileName* ATVMod::MsgConfigureVideoFileName::create (const QString & fileName) inline static
Definition at line 124 of file atvmod.h.
Referenced by ATVModGUI::configureVideoFileName(), and ATVMod::webapiSettingsPutPatch().
         {
             return new MsgConfigureVideoFileName(fileName);
         }
getFileName()
const QString& ATVMod::MsgConfigureVideoFileName::getFileName () const inline
Definition at line 122 of file atvmod.h.
Referenced by ATVModGUI::handleMessage(), and ATVMod::handleMessage().
 { return m_fileName; }
Member Data Documentation
m_fileName
QString ATVMod::MsgConfigureVideoFileName::m_fileName private
Definition at line 130 of file atvmod.h.
The documentation for this class was generated from the following file:
plugins/channeltx/modatv/atvmod.h