SDRAngel: AGC Class Reference
AGC Class Reference abstract
#include <agc.h>
Public Member Functions
AGC (int historySize, double R)
virtual ~AGC ()
void resize (int historySize, double R)
void setOrder (double R)
Real getValue ()
Real getAverage ()
virtual void feed (Complex &ci)=0
Protected Attributes
double m_u0
AGC factor.
double m_R
ordered magnitude
MovingAverage< double > m_moving_average
Averaging engine. The stack length conditions the smoothness of AGC.
int m_historySize
Averaging length (attack)
int m_count
Samples counter.
Detailed Description
Definition at line 15 of file agc.h.
Constructor & Destructor Documentation
AGC()
AGC::AGC (int historySize, double R)
Definition at line 13 of file agc.cpp.
                                   :
     m_u0(1.0),
     m_R(R),
     m_moving_average(historySize, m_R),
     m_historySize(historySize),
     m_count(0)
 {}
~AGC()
AGC::~AGC () virtual
Definition at line 21 of file agc.cpp.
 {}
Member Function Documentation
feed()
virtual void AGC::feed (Complex & ci) pure virtual
Implemented in MagAGC.
Referenced by MagAGC::setSquared().
getAverage()
Real AGC::getAverage ()
Definition at line 37 of file agc.cpp.
References MovingAverage< Type >::average(), and m_moving_average.
 {
     return m_moving_average.average();
 }
getValue()
Real AGC::getValue ()
Definition at line 32 of file agc.cpp.
References m_u0.
 {
     return m_u0;
 }
resize()
void AGC::resize (int historySize, double R)
Definition at line 24 of file agc.cpp.
References m_count, m_historySize, m_moving_average, m_R, and MovingAverage< Type >::resize().
Referenced by MagAGC::resize(), and MagAGC::setSquared().
 {
     m_R = R;
     m_moving_average.resize(historySize, R);
     m_historySize = historySize;
     m_count = 0;
 }
setOrder()
void AGC::setOrder (double R) inline
Definition at line 22 of file agc.h.
Referenced by MagAGC::setOrder(), and MagAGC::setSquared().
 { m_R = R; }
Member Data Documentation
m_count
int AGC::m_count protected
Samples counter.
Definition at line 32 of file agc.h.
Referenced by MagAGC::feedAndGetValue(), MagAGC::getStepValue(), and resize().
m_historySize
int AGC::m_historySize protected
Averaging length (attack)
Definition at line 31 of file agc.h.
Referenced by resize().
m_moving_average
MovingAverage<double> AGC::m_moving_average protected
Averaging engine. The stack length conditions the smoothness of AGC.
Definition at line 30 of file agc.h.
Referenced by MagAGC::feedAndGetValue(), getAverage(), resize(), MagAGC::resize(), and MagAGC::setOrder().
m_R
double AGC::m_R protected
ordered magnitude
Definition at line 29 of file agc.h.
Referenced by MagAGC::feedAndGetValue(), and resize().
m_u0
double AGC::m_u0 protected
AGC factor.
Definition at line 28 of file agc.h.
Referenced by MagAGC::feedAndGetValue(), and getValue().
The documentation for this class was generated from the following files:
sdrbase/dsp/agc.h
sdrbase/dsp/agc.cpp