SDRAngel: DeviceSampleSink Class Reference
DeviceSampleSink Class Reference abstract
#include <devicesamplesink.h>
Public Types
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
Public Member Functions
DeviceSampleSink ()
virtual ~DeviceSampleSink ()
virtual void destroy ()=0
virtual void init ()=0
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()=0
virtual void stop ()=0
virtual QByteArray serialize () const =0
virtual bool deserialize (const QByteArray &data)=0
virtual const QString & getDeviceDescription () const =0
virtual int getSampleRate () const =0
Sample rate exposed by the sink.
virtual void setSampleRate (int sampleRate)=0
For when the sink sample rate is set externally.
virtual quint64 getCenterFrequency () const =0
Center frequency exposed by the sink.
virtual void setCenterFrequency (qint64 centerFrequency)=0
virtual bool handleMessage (const Message &message)=0
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
MessageQueue * getInputMessageQueue ()
virtual void setMessageQueueToGUI (MessageQueue *queue)=0
MessageQueue * getMessageQueueToGUI ()
SampleSourceFifo * getSampleFifo ()
Static Public Member Functions
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Interp, fcPos_t fcPos, quint32 devSampleRate)
Protected Slots
void handleInputMessages ()
Protected Attributes
SampleSourceFifo m_sampleSourceFifo
MessageQueue m_inputMessageQueue
Input queue to the sink.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 36 of file devicesamplesink.h.
Member Enumeration Documentation
fcPos_t
enum DeviceSampleSink::fcPos_t
Enumerator
FC_POS_INFRA
FC_POS_SUPRA
FC_POS_CENTER
Definition at line 39 of file devicesamplesink.h.
                  {
         FC_POS_INFRA = 0,
         FC_POS_SUPRA,
         FC_POS_CENTER
     } fcPos_t;
Constructor & Destructor Documentation
DeviceSampleSink()
DeviceSampleSink::DeviceSampleSink ()
Definition at line 23 of file devicesamplesink.cpp.
References handleInputMessages(), and m_inputMessageQueue.
                                    :
     m_sampleSourceFifo(1<<19),
     m_guiMessageQueue(0)
 {
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
 }
~DeviceSampleSink()
DeviceSampleSink::~DeviceSampleSink () virtual
Definition at line 30 of file devicesamplesink.cpp.
 {
 }
Member Function Documentation
calculateCenterFrequency()
qint64 DeviceSampleSink::calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode = false) static
Definition at line 74 of file devicesamplesink.cpp.
References calculateFrequencyShift().
Referenced by HackRFOutput::handleMessage().
 {
     qint64 centerFrequency = deviceCenterFrequency;
     centerFrequency += calculateFrequencyShift(log2Interp, fcPos, devSampleRate);
     centerFrequency += transverterMode ? transverterDeltaFrequency : 0;
     centerFrequency = centerFrequency < 0 ? 0 : centerFrequency;
     qDebug() << "DeviceSampleSink::calculateCenterFrequency:"
             << " desired center freq: " << centerFrequency << " Hz"
             << " device center freq: " << deviceCenterFrequency << " Hz"
             << " device sample rate: " << devSampleRate << "S/s"
             << " Actual sample rate: " << devSampleRate/(1<<log2Interp) << "S/s"
             << " center freq position code: " << fcPos;
     return centerFrequency;
 }
calculateDeviceCenterFrequency()
qint64 DeviceSampleSink::calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode = false) static
Definition at line 47 of file devicesamplesink.cpp.
References calculateFrequencyShift().
Referenced by HackRFOutput::applySettings().
 {
     qint64 deviceCenterFrequency = centerFrequency;
     deviceCenterFrequency -= transverterMode ? transverterDeltaFrequency : 0;
     deviceCenterFrequency = deviceCenterFrequency < 0 ? 0 : deviceCenterFrequency;
     qint64 f_img = deviceCenterFrequency;
     deviceCenterFrequency -= calculateFrequencyShift(log2Interp, fcPos, devSampleRate);
     f_img -= 2*calculateFrequencyShift(log2Interp, fcPos, devSampleRate);
     qDebug() << "DeviceSampleSink::calculateDeviceCenterFrequency:"
             << " desired center freq: " << centerFrequency << " Hz"
             << " device center freq: " << deviceCenterFrequency << " Hz"
             << " device sample rate: " << devSampleRate << "S/s"
             << " Actual sample rate: " << devSampleRate/(1<<log2Interp) << "S/s"
             << " center freq position code: " << fcPos
             << " image frequency: " << f_img << "Hz";
     return deviceCenterFrequency;
 }
calculateFrequencyShift()
qint32 DeviceSampleSink::calculateFrequencyShift (int log2Interp, fcPos_t fcPos, quint32 devSampleRate) static
log2Interp = 0: no shift
log2Interp = 1: middle of side band (inf or sup: 1/2) ^ | ^ | inf | inf | sup | sup |
log2Interp = 2: middle of far side half side band (inf, inf or sup, sup: 1/2 + 1/4) ^ | ^ | inf | inf | sup | sup |
log2Interp = 3: inf, inf, sup or sup, sup, inf: 1/2 + 1/4 - 1/8 = 5/8 log2Interp = 4: inf, inf, sup, inf or sup, sup, inf, sup: 1/2 + 1/4 - 1/8 + 1/16 = 11/16 log2Interp = 5: inf, inf, sup, inf, sup or sup, sup, inf, sup, inf: 1/2 + 1/4 - 1/8 + 1/16 - 1/32 = 21/32 log2Interp = 6: inf, sup, inf, sup, inf, sup or sup, inf, sup, inf, sup, inf: 1/2 - 1/4 + 1/8 -1/16 + 1/32 - 1/64 = 21/64
Definition at line 114 of file devicesamplesink.cpp.
References FC_POS_CENTER, and FC_POS_INFRA.
Referenced by calculateCenterFrequency(), calculateDeviceCenterFrequency(), and HackRFOutputGui::displayFcTooltip().
 {
     if (fcPos == FC_POS_CENTER) {
         return 0;
     }
     int sign = fcPos == FC_POS_INFRA ? -1 : 1;
     int halfSampleRate = devSampleRate / 2; // fractions are relative to sideband thus based on half the sample rate
     if (log2Interp == 0) {
         return 0;
     } else if (log2Interp == 1) {
         return sign * (halfSampleRate / 2);
     } else if (log2Interp == 2) {
         return sign * ((halfSampleRate * 3) / 4);
     } else if (log2Interp == 3) {
         return sign * ((halfSampleRate * 5) / 8);
     } else if (log2Interp == 4) {
         return sign * ((halfSampleRate * 11) / 16);
     } else if (log2Interp == 5) {
         return sign * ((halfSampleRate * 21) / 32);
     } else if (log2Interp == 6) {
         return sign * ((halfSampleRate * 21) / 64);
     } else {
         return 0;
     }
 }
deserialize()
virtual bool DeviceSampleSink::deserialize (const QByteArray & data) pure virtual
Implemented in LimeSDROutput, XTRXOutput, FileSinkOutput, RemoteOutput, SoapySDROutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Referenced by DeviceAPI::loadSamplingDeviceSettings().
destroy()
virtual void DeviceSampleSink::destroy () pure virtual
Implemented in LimeSDROutput, FileSinkOutput, XTRXOutput, RemoteOutput, SoapySDROutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Referenced by PluginInterface::deleteSampleSinkPluginInstanceOutput().
getCenterFrequency()
virtual quint64 DeviceSampleSink::getCenterFrequency () const pure virtual
Center frequency exposed by the sink.
Implemented in LimeSDROutput, XTRXOutput, FileSinkOutput, RemoteOutput, SoapySDROutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Referenced by WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), DSPDeviceSinkEngine::gotoInit(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), DeviceAPI::saveSamplingDeviceSettings(), and RemoteSource::webapiFormatChannelReport().
getDeviceDescription()
virtual const QString& DeviceSampleSink::getDeviceDescription () const pure virtual
Implemented in LimeSDROutput, XTRXOutput, FileSinkOutput, RemoteOutput, SoapySDROutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Referenced by LocalSource::getLocalDevice(), LocalSource::getLocalDevices(), DSPDeviceSinkEngine::gotoInit(), and DSPDeviceSinkEngine::handleSetSink().
getInputMessageQueue()
MessageQueue* DeviceSampleSink::getInputMessageQueue () inline
Definition at line 114 of file devicesamplesink.h.
Referenced by FileSinkGui::configureFileName(), DeviceAPI::getSamplingDeviceInputMessageQueue(), LocalOutputGui::handleInputMessages(), PlutoSDROutputGUI::on_startStop_toggled(), XTRXOutputGUI::on_startStop_toggled(), LimeSDROutputGUI::on_startStop_toggled(), Bladerf1OutputGui::on_startStop_toggled(), BladeRF2OutputGui::on_startStop_toggled(), FileSinkGui::on_startStop_toggled(), LocalOutputGui::on_startStop_toggled(), HackRFOutputGui::on_startStop_toggled(), SoapySDROutputGui::on_startStop_toggled(), RemoteOutputSinkGui::on_startStop_toggled(), RemoteOutput::sampleRateCorrection(), FileSinkGui::tick(), Bladerf1OutputGui::updateHardware(), BladeRF2OutputGui::updateHardware(), LocalOutputGui::updateHardware(), FileSinkGui::updateHardware(), PlutoSDROutputGUI::updateHardware(), XTRXOutputGUI::updateHardware(), HackRFOutputGui::updateHardware(), LimeSDROutputGUI::updateHardware(), SoapySDROutputGui::updateHardware(), RemoteOutputSinkGui::updateHardware(), XTRXOutputGUI::updateStatus(), and LimeSDROutputGUI::updateStatus().
 { return &m_inputMessageQueue; }
getMessageQueueToGUI()
MessageQueue* DeviceSampleSink::getMessageQueueToGUI () inline
Definition at line 116 of file devicesamplesink.h.
Referenced by BladeRF2Output::applySettings(), SoapySDROutput::applySettings(), XTRXOutput::applySettings(), DeviceAPI::getSamplingDeviceGUIMessageQueue(), DSPDeviceSinkEngine::gotoInit(), DSPDeviceSinkEngine::handleInputMessages(), BladeRF2Output::handleMessage(), SoapySDROutput::handleMessage(), FileSinkOutput::handleMessage(), XTRXOutput::handleMessage(), LimeSDROutput::handleMessage(), LocalOutput::setCenterFrequency(), LocalOutput::setSampleRate(), FileSinkOutput::start(), and FileSinkOutput::stop().
 { return m_guiMessageQueue; }
getSampleFifo()
SampleSourceFifo* DeviceSampleSink::getSampleFifo () inline
Definition at line 117 of file devicesamplesink.h.
Referenced by LocalSource::applySettings(), DSPDeviceSinkEngine::checkNumberOfBasebandSources(), DSPDeviceSinkEngine::gotoIdle(), DSPDeviceSinkEngine::gotoRunning(), DSPDeviceSinkEngine::handleForwardToSpectrumSink(), LocalSource::start(), and DSPDeviceSinkEngine::work().
 { return &m_sampleSourceFifo; }
getSampleRate()
virtual int DeviceSampleSink::getSampleRate () const pure virtual
Sample rate exposed by the sink.
Implemented in LimeSDROutput, XTRXOutput, FileSinkOutput, RemoteOutput, SoapySDROutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Referenced by WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), DSPDeviceSinkEngine::gotoInit(), and RemoteSource::webapiFormatChannelReport().
handleInputMessages
void DeviceSampleSink::handleInputMessages () protected slot
Definition at line 34 of file devicesamplesink.cpp.
References handleMessage(), m_inputMessageQueue, and MessageQueue::pop().
Referenced by DeviceSampleSink().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
virtual bool DeviceSampleSink::handleMessage (const Message & message) pure virtual
Implemented in LimeSDROutput, XTRXOutput, FileSinkOutput, RemoteOutput, SoapySDROutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Referenced by handleInputMessages().
init()
virtual void DeviceSampleSink::init () pure virtual
initializations to be done when all collaborating objects are created and possibly connected
Implemented in LimeSDROutput, FileSinkOutput, XTRXOutput, RemoteOutput, SoapySDROutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
serialize()
virtual QByteArray DeviceSampleSink::serialize () const pure virtual
Implemented in LimeSDROutput, XTRXOutput, FileSinkOutput, RemoteOutput, SoapySDROutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Referenced by DeviceAPI::saveSamplingDeviceSettings().
setCenterFrequency()
virtual void DeviceSampleSink::setCenterFrequency (qint64 centerFrequency) pure virtual
Implemented in LimeSDROutput, XTRXOutput, FileSinkOutput, RemoteOutput, SoapySDROutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Referenced by DeviceAPI::loadSamplingDeviceSettings(), and LocalSource::propagateSampleRateAndFrequency().
setMessageQueueToGUI()
virtual void DeviceSampleSink::setMessageQueueToGUI (MessageQueue * queue) pure virtual
Implemented in LimeSDROutput, XTRXOutput, FileSinkOutput, RemoteOutput, SoapySDROutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Referenced by MainWindow::sampleSinkChanged().
setSampleRate()
virtual void DeviceSampleSink::setSampleRate (int sampleRate) pure virtual
For when the sink sample rate is set externally.
Implemented in LimeSDROutput, XTRXOutput, FileSinkOutput, RemoteOutput, SoapySDROutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Referenced by LocalSource::propagateSampleRateAndFrequency().
start()
virtual bool DeviceSampleSink::start () pure virtual
Implemented in LimeSDROutput, FileSinkOutput, XTRXOutput, RemoteOutput, SoapySDROutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Referenced by DSPDeviceSinkEngine::gotoRunning().
stop()
virtual void DeviceSampleSink::stop () pure virtual
Implemented in LimeSDROutput, FileSinkOutput, XTRXOutput, RemoteOutput, SoapySDROutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Referenced by DSPDeviceSinkEngine::gotoIdle().
webapiReportGet()
virtual int DeviceSampleSink::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) inline virtual
Reimplemented in LimeSDROutput, XTRXOutput, SoapySDROutput, RemoteOutput, BladeRF2Output, LocalOutput, and PlutoSDROutput.
Definition at line 105 of file devicesamplesink.h.
Referenced by WebAPIAdapterGUI::devicesetDeviceReportGet(), and WebAPIAdapterSrv::devicesetDeviceReportGet().
     {
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
webapiRun()
virtual int DeviceSampleSink::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) inline virtual
Reimplemented in LimeSDROutput, XTRXOutput, FileSinkOutput, SoapySDROutput, RemoteOutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Definition at line 95 of file devicesamplesink.h.
Referenced by WebAPIAdapterGUI::devicesetDeviceRunDelete(), WebAPIAdapterSrv::devicesetDeviceRunDelete(), WebAPIAdapterGUI::devicesetDeviceRunPost(), and WebAPIAdapterSrv::devicesetDeviceRunPost().
     {
         (void) run;
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
webapiRunGet()
virtual int DeviceSampleSink::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) inline virtual
Reimplemented in LimeSDROutput, XTRXOutput, FileSinkOutput, SoapySDROutput, RemoteOutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Definition at line 86 of file devicesamplesink.h.
Referenced by WebAPIAdapterGUI::devicesetDeviceRunGet(), and WebAPIAdapterSrv::devicesetDeviceRunGet().
     {
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
webapiSettingsGet()
virtual int DeviceSampleSink::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) inline virtual
Reimplemented in LimeSDROutput, XTRXOutput, SoapySDROutput, RemoteOutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Definition at line 64 of file devicesamplesink.h.
Referenced by WebAPIAdapterGUI::devicesetDeviceSettingsGet(), and WebAPIAdapterSrv::devicesetDeviceSettingsGet().
     {
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
webapiSettingsPutPatch()
virtual int DeviceSampleSink::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) inline virtual
Parameters
force true to force settings = put
Reimplemented in LimeSDROutput, XTRXOutput, SoapySDROutput, RemoteOutput, BladeRF2Output, LocalOutput, HackRFOutput, Bladerf1Output, and PlutoSDROutput.
Definition at line 73 of file devicesamplesink.h.
Referenced by WebAPIAdapterGUI::devicesetDeviceSettingsPutPatch(), and WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch().
     {
         (void) force;
         (void) deviceSettingsKeys;
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
Member Data Documentation
m_guiMessageQueue
MessageQueue* DeviceSampleSink::m_guiMessageQueue protected
Input message queue to the GUI.
Definition at line 146 of file devicesamplesink.h.
Referenced by PlutoSDROutput::deserialize(), Bladerf1Output::deserialize(), HackRFOutput::deserialize(), LocalOutput::deserialize(), BladeRF2Output::deserialize(), SoapySDROutput::deserialize(), RemoteOutput::deserialize(), FileSinkOutput::deserialize(), XTRXOutput::deserialize(), LimeSDROutput::deserialize(), HackRFOutput::handleMessage(), PlutoSDROutput::setCenterFrequency(), Bladerf1Output::setCenterFrequency(), HackRFOutput::setCenterFrequency(), BladeRF2Output::setCenterFrequency(), SoapySDROutput::setCenterFrequency(), FileSinkOutput::setCenterFrequency(), XTRXOutput::setCenterFrequency(), LimeSDROutput::setCenterFrequency(), PlutoSDROutput::setMessageQueueToGUI(), Bladerf1Output::setMessageQueueToGUI(), HackRFOutput::setMessageQueueToGUI(), LocalOutput::setMessageQueueToGUI(), BladeRF2Output::setMessageQueueToGUI(), RemoteOutput::setMessageQueueToGUI(), FileSinkOutput::setMessageQueueToGUI(), XTRXOutput::setMessageQueueToGUI(), LimeSDROutput::setMessageQueueToGUI(), PlutoSDROutput::webapiRun(), Bladerf1Output::webapiRun(), HackRFOutput::webapiRun(), LocalOutput::webapiRun(), BladeRF2Output::webapiRun(), RemoteOutput::webapiRun(), SoapySDROutput::webapiRun(), FileSinkOutput::webapiRun(), XTRXOutput::webapiRun(), LimeSDROutput::webapiRun(), PlutoSDROutput::webapiSettingsPutPatch(), Bladerf1Output::webapiSettingsPutPatch(), HackRFOutput::webapiSettingsPutPatch(), LocalOutput::webapiSettingsPutPatch(), BladeRF2Output::webapiSettingsPutPatch(), RemoteOutput::webapiSettingsPutPatch(), SoapySDROutput::webapiSettingsPutPatch(), XTRXOutput::webapiSettingsPutPatch(), and LimeSDROutput::webapiSettingsPutPatch().
m_inputMessageQueue
MessageQueue DeviceSampleSink::m_inputMessageQueue protected
Input queue to the sink.
Definition at line 145 of file devicesamplesink.h.
Referenced by PlutoSDROutput::deserialize(), Bladerf1Output::deserialize(), HackRFOutput::deserialize(), LocalOutput::deserialize(), BladeRF2Output::deserialize(), SoapySDROutput::deserialize(), RemoteOutput::deserialize(), FileSinkOutput::deserialize(), XTRXOutput::deserialize(), LimeSDROutput::deserialize(), DeviceSampleSink(), handleInputMessages(), PlutoSDROutput::setCenterFrequency(), Bladerf1Output::setCenterFrequency(), HackRFOutput::setCenterFrequency(), BladeRF2Output::setCenterFrequency(), SoapySDROutput::setCenterFrequency(), FileSinkOutput::setCenterFrequency(), XTRXOutput::setCenterFrequency(), LimeSDROutput::setCenterFrequency(), PlutoSDROutput::webapiRun(), Bladerf1Output::webapiRun(), HackRFOutput::webapiRun(), LocalOutput::webapiRun(), BladeRF2Output::webapiRun(), RemoteOutput::webapiRun(), SoapySDROutput::webapiRun(), FileSinkOutput::webapiRun(), XTRXOutput::webapiRun(), LimeSDROutput::webapiRun(), PlutoSDROutput::webapiSettingsPutPatch(), Bladerf1Output::webapiSettingsPutPatch(), HackRFOutput::webapiSettingsPutPatch(), LocalOutput::webapiSettingsPutPatch(), BladeRF2Output::webapiSettingsPutPatch(), RemoteOutput::webapiSettingsPutPatch(), SoapySDROutput::webapiSettingsPutPatch(), XTRXOutput::webapiSettingsPutPatch(), and LimeSDROutput::webapiSettingsPutPatch().
m_sampleSourceFifo
SampleSourceFifo DeviceSampleSink::m_sampleSourceFifo protected
Definition at line 144 of file devicesamplesink.h.
Referenced by PlutoSDROutput::applySettings(), Bladerf1Output::applySettings(), HackRFOutput::applySettings(), BladeRF2Output::applySettings(), SoapySDROutput::applySettings(), LimeSDROutput::applySettings(), PlutoSDROutput::openDevice(), Bladerf1Output::openDevice(), HackRFOutput::openDevice(), BladeRF2Output::openDevice(), SoapySDROutput::openDevice(), XTRXOutput::openDevice(), PlutoSDROutput::start(), Bladerf1Output::start(), HackRFOutput::start(), BladeRF2Output::start(), SoapySDROutput::start(), RemoteOutput::start(), XTRXOutput::start(), FileSinkOutput::start(), LimeSDROutput::start(), XTRXOutput::stop(), and RemoteOutput::webapiFormatDeviceReport().
The documentation for this class was generated from the following files:
sdrbase/dsp/devicesamplesink.h
sdrbase/dsp/devicesamplesink.cpp