SDRAngel: NFMMod::MsgReportFileSourceStreamData Class Reference
NFMMod::MsgReportFileSourceStreamData Class Reference
#include <nfmmod.h>
Public Member Functions
int getSampleRate () const
quint32 getRecordLength () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportFileSourceStreamData * create (int sampleRate, quint32 recordLength)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportFileSourceStreamData (int sampleRate, quint32 recordLength)
Protected Attributes
int m_sampleRate
quint32 m_recordLength
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 179 of file nfmmod.h.
Constructor & Destructor Documentation
MsgReportFileSourceStreamData()
NFMMod::MsgReportFileSourceStreamData::MsgReportFileSourceStreamData (int sampleRate, quint32 recordLength) inline protected
Definition at line 196 of file nfmmod.h.
References NFMMod::NFMMod(), and NFMMod::~NFMMod().
                                       :
             Message(),
             m_sampleRate(sampleRate),
             m_recordLength(recordLength)
         { }
Member Function Documentation
create()
static MsgReportFileSourceStreamData* NFMMod::MsgReportFileSourceStreamData::create (int sampleRate, quint32 recordLength) inline static
Definition at line 186 of file nfmmod.h.
Referenced by NFMMod::openFileStream().
         {
             return new MsgReportFileSourceStreamData(sampleRate, recordLength);
         }
getRecordLength()
quint32 NFMMod::MsgReportFileSourceStreamData::getRecordLength () const inline
Definition at line 184 of file nfmmod.h.
References NFMMod::m_recordLength.
 { return m_recordLength; }
getSampleRate()
int NFMMod::MsgReportFileSourceStreamData::getSampleRate () const inline
Definition at line 183 of file nfmmod.h.
References NFMMod::m_sampleRate.
 { return m_sampleRate; }
Member Data Documentation
m_recordLength
quint32 NFMMod::MsgReportFileSourceStreamData::m_recordLength protected
Definition at line 194 of file nfmmod.h.
m_sampleRate
int NFMMod::MsgReportFileSourceStreamData::m_sampleRate protected
Definition at line 193 of file nfmmod.h.
The documentation for this class was generated from the following file:
plugins/channeltx/modnfm/nfmmod.h