SDRAngel: DeviceUserArgs Struct Reference
DeviceUserArgs Struct Reference
#include <deviceuserargs.h>
Classes
struct Args
Public Member Functions
QByteArray serialize () const
bool deserialize (const QByteArray &data)
QString findUserArgs (const QString &id, int sequence)
void addDeviceArgs (const QString &id, int sequence, const QString &args)
Will not add if it exists for same reference.
void addOrUpdateDeviceArgs (const QString &id, int sequence, const QString &args)
Add or update if it exists for same reference.
void updateDeviceArgs (const QString &id, int sequence, const QString &args)
Will not update if reference does not exist.
void deleteDeviceArgs (const QString &id, int sequence)
const QList< Args > & getArgsByDevice () const
Public Attributes
QList< Args > m_argsByDevice
args corresponding to a device
Detailed Description
Definition at line 27 of file deviceuserargs.h.
Member Function Documentation
addDeviceArgs()
void DeviceUserArgs::addDeviceArgs (const QString & id, int sequence, const QString & args)
Will not add if it exists for same reference.
Definition at line 81 of file deviceuserargs.cpp.
References i, and m_argsByDevice.
Referenced by DeviceUserArgsDialog::on_importDevice_clicked().
 {
     int i = 0;
     for (; i < m_argsByDevice.size(); i++)
     {
         if ((m_argsByDevice.at(i).m_id == id) && (m_argsByDevice.at(i).m_sequence == sequence)) {
             break;
         }
     }
     if (i == m_argsByDevice.size()) {
         m_argsByDevice.push_back(Args(id, sequence, deviceArgs));
     }
 }
addOrUpdateDeviceArgs()
void DeviceUserArgs::addOrUpdateDeviceArgs (const QString & id, int sequence, const QString & args)
Add or update if it exists for same reference.
Definition at line 97 of file deviceuserargs.cpp.
References i, and m_argsByDevice.
 {
     int i = 0;
     for (; i < m_argsByDevice.size(); i++)
     {
         if ((m_argsByDevice.at(i).m_id == id) && (m_argsByDevice.at(i).m_sequence == sequence)) {
             m_argsByDevice[i].m_args = deviceArgs;
         }
     }
     if (i == m_argsByDevice.size()) {
         m_argsByDevice.push_back(Args(id, sequence, deviceArgs));
     }
 }
deleteDeviceArgs()
void DeviceUserArgs::deleteDeviceArgs (const QString & id, int sequence)
Definition at line 125 of file deviceuserargs.cpp.
References i, and m_argsByDevice.
Referenced by DeviceUserArgsDialog::on_deleteArgs_clicked().
 {
     int i = 0;
     for (; i < m_argsByDevice.size(); i++)
     {
         if ((m_argsByDevice.at(i).m_id == id) && (m_argsByDevice.at(i).m_sequence == sequence))
         {
             m_argsByDevice.takeAt(i);
             return;
         }
     }
 }
deserialize()
bool DeviceUserArgs::deserialize (const QByteArray & data)
Definition at line 45 of file deviceuserargs.cpp.
References SimpleDeserializer::getVersion(), SimpleDeserializer::isValid(), m_argsByDevice, and SimpleDeserializer::readBlob().
Referenced by MainSettings::load().
 {
     SimpleDeserializer d(data);
     if (!d.isValid()) {
         return false;
     }
     if(d.getVersion() == 1)
     {
         QByteArray data;
         d.readBlob(1, &data);
         QDataStream readStream(&data, QIODevice::ReadOnly);
         readStream >> m_argsByDevice;
         return true;
     }
     else
     {
         return false;
     }
 }
findUserArgs()
QString DeviceUserArgs::findUserArgs (const QString & id, int sequence)
Definition at line 69 of file deviceuserargs.cpp.
References i, and m_argsByDevice.
Referenced by MainWindow::addMIMODevice(), MainCore::addSinkDevice(), MainWindow::addSinkDevice(), MainCore::addSourceDevice(), MainWindow::addSourceDevice(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 {
     for (int i = 0; i < m_argsByDevice.size(); i++)
     {
         if ((m_argsByDevice.at(i).m_id == id) && (m_argsByDevice.at(i).m_sequence == sequence)) {
             return m_argsByDevice.at(i).m_args;
         }
     }
     return "";
 }
getArgsByDevice()
const QList<Args>& DeviceUserArgs::getArgsByDevice () const inline
Definition at line 58 of file deviceuserargs.h.
Referenced by DeviceUserArgsDialog::displayArgsByDevice().
 { return m_argsByDevice; }
serialize()
QByteArray DeviceUserArgs::serialize () const
Definition at line 35 of file deviceuserargs.cpp.
References SimpleSerializer::final(), m_argsByDevice, and SimpleSerializer::writeBlob().
Referenced by MainSettings::save().
 {
     SimpleSerializer s(1);
     QByteArray data;
     QDataStream *stream = new QDataStream(&data, QIODevice::WriteOnly);
     *stream << m_argsByDevice;
     s.writeBlob(1, data);
     return s.final();
 }
updateDeviceArgs()
void DeviceUserArgs::updateDeviceArgs (const QString & id, int sequence, const QString & args)
Will not update if reference does not exist.
Definition at line 113 of file deviceuserargs.cpp.
References i, and m_argsByDevice.
Referenced by DeviceUserArgsDialog::on_argStringEdit_editingFinished().
 {
     int i = 0;
     for (; i < m_argsByDevice.size(); i++)
     {
         if ((m_argsByDevice.at(i).m_id == id) && (m_argsByDevice.at(i).m_sequence == sequence)) {
             m_argsByDevice[i].m_args = deviceArgs;
         }
     }
 }
Member Data Documentation
m_argsByDevice
QList<Args> DeviceUserArgs::m_argsByDevice
args corresponding to a device
Definition at line 60 of file deviceuserargs.h.
Referenced by addDeviceArgs(), addOrUpdateDeviceArgs(), deleteDeviceArgs(), deserialize(), findUserArgs(), serialize(), and updateDeviceArgs().
The documentation for this struct was generated from the following files:
sdrbase/device/deviceuserargs.h
sdrbase/device/deviceuserargs.cpp