SDRAngel: AMDemod::MsgConfigureAMDemod Class Reference
AMDemod::MsgConfigureAMDemod Class Reference
#include <amdemod.h>
Public Member Functions
const AMDemodSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureAMDemod * create (const AMDemodSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureAMDemod (const AMDemodSettings &settings, bool force)
Private Attributes
AMDemodSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 51 of file amdemod.h.
Constructor & Destructor Documentation
MsgConfigureAMDemod()
AMDemod::MsgConfigureAMDemod::MsgConfigureAMDemod (const AMDemodSettings & settings, bool force) inline private
Definition at line 67 of file amdemod.h.
Referenced by create().
                                                                          :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureAMDemod* AMDemod::MsgConfigureAMDemod::create (const AMDemodSettings & settings, bool force) inline static
Definition at line 58 of file amdemod.h.
References MsgConfigureAMDemod().
Referenced by AMDemodGUI::applySettings(), AMDemod::deserialize(), and AMDemod::webapiSettingsPutPatch().
         {
             return new MsgConfigureAMDemod(settings, force);
         }
getForce()
bool AMDemod::MsgConfigureAMDemod::getForce () const inline
Definition at line 56 of file amdemod.h.
References m_force.
Referenced by AMDemod::handleMessage().
 { return m_force; }
getSettings()
const AMDemodSettings& AMDemod::MsgConfigureAMDemod::getSettings () const inline
Definition at line 55 of file amdemod.h.
References m_settings.
Referenced by AMDemodGUI::handleMessage(), and AMDemod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool AMDemod::MsgConfigureAMDemod::m_force private
Definition at line 65 of file amdemod.h.
Referenced by getForce().
m_settings
AMDemodSettings AMDemod::MsgConfigureAMDemod::m_settings private
Definition at line 64 of file amdemod.h.
Referenced by AMDemod::getCenterFrequency(), AMDemod::getPllLocked(), getSettings(), AMDemod::getStreamCenterFrequency(), and AMDemod::getTitle().
The documentation for this class was generated from the following file:
plugins/channelrx/demodam/amdemod.h