SDRAngel: IntHalfbandFilterEO1< HBFilterOrder > Class Template Reference
IntHalfbandFilterEO1< HBFilterOrder > Class Template Reference
#include <inthalfbandfiltereo1.h>
Public Member Functions
IntHalfbandFilterEO1 ()
bool workDecimateCenter (Sample *sample)
bool workInterpolateCenterZeroStuffing (Sample *sampleIn, Sample *SampleOut)
bool workInterpolateCenter (Sample *sampleIn, Sample *SampleOut)
bool workDecimateCenter (int32_t *x, int32_t *y)
bool workDecimateLowerHalf (Sample *sample)
bool workInterpolateLowerHalfZeroStuffing (Sample *sampleIn, Sample *sampleOut)
bool workInterpolateLowerHalf (Sample *sampleIn, Sample *sampleOut)
bool workDecimateUpperHalf (Sample *sample)
bool workInterpolateUpperHalfZeroStuffing (Sample *sampleIn, Sample *sampleOut)
bool workInterpolateUpperHalf (Sample *sampleIn, Sample *sampleOut)
void myDecimate (const Sample *sample1, Sample *sample2)
void myDecimate (int32_t x1, int32_t y1, int32_t *x2, int32_t *y2)
void myInterpolateZeroStuffing (Sample *sample1, Sample *sample2)
void myInterpolateZeroStuffing (int32_t *x1, int32_t *y1, int32_t *x2, int32_t *y2)
void myInterpolate (qint32 *x1, qint32 *y1, qint32 *x2, qint32 *y2)
void myInterpolateInf (qint32 *x1, qint32 *y1, qint32 *x2, qint32 *y2, qint32 *x3, qint32 *y3, qint32 *x4, qint32 *y4)
void myInterpolateSup (qint32 *x1, qint32 *y1, qint32 *x2, qint32 *y2, qint32 *x3, qint32 *y3, qint32 *x4, qint32 *y4)
Protected Member Functions
void storeSample (const FixReal &sampleI, const FixReal &sampleQ)
void storeSample32 (int32_t x, int32_t y)
void advancePointer ()
int32_t rand (int32_t mod)
void doFIR (Sample *sample)
void doFIR (int32_t *x, int32_t *y)
void doInterpolateFIR (Sample *sample)
void doInterpolateFIR (qint32 *x, qint32 *y)
Protected Attributes
int32_t m_even [2][HBFIRFilterTraits< HBFilterOrder >::hbOrder]
int32_t m_odd [2][HBFIRFilterTraits< HBFilterOrder >::hbOrder]
int32_t m_samples [HBFIRFilterTraits< HBFilterOrder >::hbOrder][2]
int m_ptr
int m_size
int m_state
Detailed Description
template<uint32_t HBFilterOrder>
class IntHalfbandFilterEO1< HBFilterOrder >
Definition at line 33 of file inthalfbandfiltereo1.h.
Constructor & Destructor Documentation
IntHalfbandFilterEO1()
template<uint32_t HBFilterOrder> IntHalfbandFilterEO1< HBFilterOrder >::IntHalfbandFilterEO1 ()
Definition at line 835 of file inthalfbandfiltereo1.h.
References i, IntHalfbandFilterEO1< HBFilterOrder >::m_even, IntHalfbandFilterEO1< HBFilterOrder >::m_odd, IntHalfbandFilterEO1< HBFilterOrder >::m_ptr, IntHalfbandFilterEO1< HBFilterOrder >::m_samples, IntHalfbandFilterEO1< HBFilterOrder >::m_size, and IntHalfbandFilterEO1< HBFilterOrder >::m_state.
 {
     m_size = HBFIRFilterTraits<HBFilterOrder>::hbOrder/2;
     for (int i = 0; i < 2*m_size; i++)
     {
         m_even[0][i] = 0;
         m_even[1][i] = 0;
         m_odd[0][i] = 0;
         m_odd[1][i] = 0;
         m_samples[i][0] = 0;
         m_samples[i][1] = 0;
     }
     m_ptr = 0;
     m_state = 0;
 }
Member Function Documentation
advancePointer()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::advancePointer () inline protected
Definition at line 701 of file inthalfbandfiltereo1.h.
Referenced by IntHalfbandFilterEO1< HBFilterOrder >::myDecimate(), IntHalfbandFilterEO1< HBFilterOrder >::myInterpolateZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), and IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalfZeroStuffing().
     {
         m_ptr = m_ptr + 1 < 2*m_size ? m_ptr + 1: 0;
     }
doFIR() [1/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::doFIR (Sample * sample) inline protected
Definition at line 711 of file inthalfbandfiltereo1.h.
References i, IntHalfbandFilterEO1< HBFilterOrder >::m_size, Sample::setImag(), and Sample::setReal().
Referenced by IntHalfbandFilterEO1< HBFilterOrder >::myDecimate(), IntHalfbandFilterEO1< HBFilterOrder >::myInterpolateZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), and IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalfZeroStuffing().
     {
         int32_t iAcc = 0;
         int32_t qAcc = 0;
         int a = m_ptr/2 + m_size; // tip pointer
         int b = m_ptr/2 + 1; // tail pointer
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             if ((m_ptr % 2) == 0)
             {
                 iAcc += (m_even[0][a] + m_even[0][b]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 qAcc += (m_even[1][a] + m_even[1][b]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             }
             else
             {
                 iAcc += (m_odd[0][a] + m_odd[0][b]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 qAcc += (m_odd[1][a] + m_odd[1][b]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             }
             a -= 1;
             b += 1;
         }
         if ((m_ptr % 2) == 0)
         {
             iAcc += ((int32_t)m_odd[0][m_ptr/2 + m_size/2]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             qAcc += ((int32_t)m_odd[1][m_ptr/2 + m_size/2]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         }
         else
         {
             iAcc += ((int32_t)m_even[0][m_ptr/2 + m_size/2 + 1]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             qAcc += ((int32_t)m_even[1][m_ptr/2 + m_size/2 + 1]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         }
         sample->setReal(iAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1));
         sample->setImag(qAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1));
     }
doFIR() [2/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::doFIR (int32_t * x, int32_t * y) inline protected
Definition at line 751 of file inthalfbandfiltereo1.h.
References i, and IntHalfbandFilterEO1< HBFilterOrder >::m_size.
     {
         int32_t iAcc = 0;
         int32_t qAcc = 0;
         int a = m_ptr/2 + m_size; // tip pointer
         int b = m_ptr/2 + 1; // tail pointer
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             if ((m_ptr % 2) == 0)
             {
                 iAcc += (m_even[0][a] + m_even[0][b]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 qAcc += (m_even[1][a] + m_even[1][b]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             }
             else
             {
                 iAcc += (m_odd[0][a] + m_odd[0][b]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
                 qAcc += (m_odd[1][a] + m_odd[1][b]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             }
             a -= 1;
             b += 1;
         }
         if ((m_ptr % 2) == 0)
         {
             iAcc += ((int32_t)m_odd[0][m_ptr/2 + m_size/2]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             qAcc += ((int32_t)m_odd[1][m_ptr/2 + m_size/2]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         }
         else
         {
             iAcc += ((int32_t)m_even[0][m_ptr/2 + m_size/2 + 1]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
             qAcc += ((int32_t)m_even[1][m_ptr/2 + m_size/2 + 1]) << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         }
         *x = iAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1); // HB_SHIFT incorrect do not loose the gained bit
         *y = qAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
     }
doInterpolateFIR() [1/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::doInterpolateFIR (Sample * sample) inline protected
Definition at line 791 of file inthalfbandfiltereo1.h.
References i, IntHalfbandFilterEO1< HBFilterOrder >::m_ptr, Sample::setImag(), and Sample::setReal().
Referenced by IntHalfbandFilterEO1< HBFilterOrder >::myInterpolate(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalf(), and IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalf().
     {
         qint32 iAcc = 0;
         qint32 qAcc = 0;
         qint16 a = m_ptr;
         qint16 b = m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder / 2) - 1;
         // go through samples in buffer
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += (m_samples[a][0] + m_samples[b][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             qAcc += (m_samples[a][1] + m_samples[b][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             a++;
             b--;
         }
         sample->setReal(iAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1));
         sample->setImag(qAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1));
     }
doInterpolateFIR() [2/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::doInterpolateFIR (qint32 * x, qint32 * y) inline protected
Definition at line 812 of file inthalfbandfiltereo1.h.
References i, and IntHalfbandFilterEO1< HBFilterOrder >::m_ptr.
     {
         qint32 iAcc = 0;
         qint32 qAcc = 0;
         qint16 a = m_ptr;
         qint16 b = m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder / 2) - 1;
         // go through samples in buffer
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += (m_samples[a][0] + m_samples[b][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             qAcc += (m_samples[a][1] + m_samples[b][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffs[i];
             a++;
             b--;
         }
         *x = iAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
         *y = qAcc >> (HBFIRFilterTraits<HBFilterOrder>::hbShift -1);
     }
myDecimate() [1/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::myDecimate (const Sample * sample1, Sample * sample2) inline
Definition at line 556 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::advancePointer(), IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), Sample::imag(), Sample::real(), and IntHalfbandFilterEO1< HBFilterOrder >::storeSample().
     {
         storeSample((FixReal) sample1->real(), (FixReal) sample1->imag());
         advancePointer();
         storeSample((FixReal) sample2->real(), (FixReal) sample2->imag());
         doFIR(sample2);
         advancePointer();
     }
myDecimate() [2/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::myDecimate (int32_t x1, int32_t y1, int32_t * x2, int32_t * y2) inline
Definition at line 566 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::advancePointer(), IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), and IntHalfbandFilterEO1< HBFilterOrder >::storeSample32().
     {
         storeSample32(x1, y1);
         advancePointer();
         storeSample32(*x2, *y2);
         doFIR(x2, y2);
         advancePointer();
     }
myInterpolate()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::myInterpolate (qint32 * x1, qint32 * y1, qint32 * x2, qint32 * y2) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 601 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::doInterpolateFIR(), IntHalfbandFilterEO1< HBFilterOrder >::m_ptr, and IntHalfbandFilterEO1< HBFilterOrder >::m_samples.
Referenced by IntHalfbandFilterEO1< HBFilterOrder >::myInterpolateInf(), and IntHalfbandFilterEO1< HBFilterOrder >::myInterpolateSup().
     {
         // insert sample into ring double buffer
         m_samples[m_ptr][0] = *x1;
         m_samples[m_ptr][1] = *y1;
         m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = *x1;
         m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = *y1;
         // advance pointer
         if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
             m_ptr++;
         } else {
             m_ptr = 0;
         }
         // first output sample calculated with the middle peak
         *x1 = m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0];
         *y1 = m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1];
         // second sample calculated with the filter
         doInterpolateFIR(x2, y2);
     }
myInterpolateInf()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::myInterpolateInf (qint32 * x1, qint32 * y1, qint32 * x2, qint32 * y2, qint32 * x3, qint32 * y3, qint32 * x4, qint32 * y4) inline
Definition at line 624 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::myInterpolate().
     {
         myInterpolate(x1, y1, x2, y2);
         myInterpolate(x3, y3, x4, y4);
         // rotation
         qint32 x;
         x = *x1;
         *x1 = *y1;
         *y1 = -x;
         *x2 = -*x2;
         *y2 = -*y2;
         x = *x3;
         *x3 = -*y3;
         *y3 = x;
     }
myInterpolateSup()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::myInterpolateSup (qint32 * x1, qint32 * y1, qint32 * x2, qint32 * y2, qint32 * x3, qint32 * y3, qint32 * x4, qint32 * y4) inline
Definition at line 640 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::myInterpolate().
     {
         myInterpolate(x1, y1, x2, y2);
         myInterpolate(x3, y3, x4, y4);
         // rotation
         qint32 x;
         x = *x1;
         *x1 = -*y1;
         *y1 = x;
         *x2 = -*x2;
         *y2 = -*y2;
         x = *x3;
         *x3 = *y3;
         *y3 = -x;
     }
myInterpolateZeroStuffing() [1/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::myInterpolateZeroStuffing (Sample * sample1, Sample * sample2) inline
Simple zero stuffing and filter
Definition at line 577 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::advancePointer(), IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), Sample::imag(), Sample::real(), and IntHalfbandFilterEO1< HBFilterOrder >::storeSample().
     {
         storeSample((FixReal) sample1->real(), (FixReal) sample1->imag());
         doFIR(sample1);
         advancePointer();
         storeSample((FixReal) 0, (FixReal) 0);
         doFIR(sample2);
         advancePointer();
     }
myInterpolateZeroStuffing() [2/2]
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::myInterpolateZeroStuffing (int32_t * x1, int32_t * y1, int32_t * x2, int32_t * y2) inline
Simple zero stuffing and filter
Definition at line 589 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::advancePointer(), IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), and IntHalfbandFilterEO1< HBFilterOrder >::storeSample32().
     {
         storeSample32(*x1, *y1);
         doFIR(x1, y1);
         advancePointer();
         storeSample32(0, 0);
         doFIR(x2, y2);
         advancePointer();
     }
rand()
template<uint32_t HBFilterOrder> int32_t IntHalfbandFilterEO1< HBFilterOrder >::rand (int32_t mod) inline protected
Definition at line 706 of file inthalfbandfiltereo1.h.
     {
         return (RAND_MAX/2 - std::rand()) % mod;
     }
storeSample()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::storeSample (const FixReal & sampleI, const FixReal & sampleQ) inline protected
Definition at line 665 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::m_size.
Referenced by IntHalfbandFilterEO1< HBFilterOrder >::myDecimate(), IntHalfbandFilterEO1< HBFilterOrder >::myInterpolateZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), and IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalfZeroStuffing().
     {
         if ((m_ptr % 2) == 0)
         {
             m_even[0][m_ptr/2] = sampleI;
             m_even[1][m_ptr/2] = sampleQ;
             m_even[0][m_ptr/2 + m_size] = sampleI;
             m_even[1][m_ptr/2 + m_size] = sampleQ;
         }
         else
         {
             m_odd[0][m_ptr/2] = sampleI;
             m_odd[1][m_ptr/2] = sampleQ;
             m_odd[0][m_ptr/2 + m_size] = sampleI;
             m_odd[1][m_ptr/2 + m_size] = sampleQ;
         }
     }
storeSample32()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEO1< HBFilterOrder >::storeSample32 (int32_t x, int32_t y) inline protected
Definition at line 683 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::m_size.
Referenced by IntHalfbandFilterEO1< HBFilterOrder >::myDecimate(), IntHalfbandFilterEO1< HBFilterOrder >::myInterpolateZeroStuffing(), and IntHalfbandFilterEO1< HBFilterOrder >::workDecimateCenter().
     {
         if ((m_ptr % 2) == 0)
         {
             m_even[0][m_ptr/2] = x;
             m_even[1][m_ptr/2] = y;
             m_even[0][m_ptr/2 + m_size] = x;
             m_even[1][m_ptr/2 + m_size] = y;
         }
         else
         {
             m_odd[0][m_ptr/2] = x;
             m_odd[1][m_ptr/2] = y;
             m_odd[0][m_ptr/2 + m_size] = x;
             m_odd[1][m_ptr/2 + m_size] = y;
         }
     }
workDecimateCenter() [1/2]
template<uint32_t HBFilterOrder> bool IntHalfbandFilterEO1< HBFilterOrder >::workDecimateCenter (Sample * sample) inline
Definition at line 38 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::advancePointer(), IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), Sample::imag(), IntHalfbandFilterEO1< HBFilterOrder >::m_state, Sample::real(), and IntHalfbandFilterEO1< HBFilterOrder >::storeSample().
     {
         // insert sample into ring-buffer
         storeSample((FixReal) sample->real(), (FixReal) sample->imag());
         switch(m_state)
         {
             case 0:
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workDecimateCenter() [2/2]
template<uint32_t HBFilterOrder> bool IntHalfbandFilterEO1< HBFilterOrder >::workDecimateCenter (int32_t * x, int32_t * y) inline
Definition at line 131 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::advancePointer(), IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), IntHalfbandFilterEO1< HBFilterOrder >::m_state, and IntHalfbandFilterEO1< HBFilterOrder >::storeSample32().
     {
         // insert sample into ring-buffer
         storeSample32(*x, *y);
         switch(m_state)
         {
             case 0:
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // save result
                 doFIR(x, y);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workDecimateLowerHalf()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterEO1< HBFilterOrder >::workDecimateLowerHalf (Sample * sample) inline
Definition at line 159 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::advancePointer(), IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), Sample::imag(), IntHalfbandFilterEO1< HBFilterOrder >::m_state, Sample::real(), and IntHalfbandFilterEO1< HBFilterOrder >::storeSample().
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSample((FixReal) -sample->imag(), (FixReal) sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             case 1:
                 // insert sample into ring-buffer
                 storeSample((FixReal) -sample->real(), (FixReal) -sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 2;
                 // tell caller we have a new sample
                 return true;
             case 2:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sample->imag(), (FixReal) -sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 3;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sample->real(), (FixReal) sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workDecimateUpperHalf()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterEO1< HBFilterOrder >::workDecimateUpperHalf (Sample * sample) inline
Definition at line 358 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::advancePointer(), IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), Sample::imag(), IntHalfbandFilterEO1< HBFilterOrder >::m_state, Sample::real(), and IntHalfbandFilterEO1< HBFilterOrder >::storeSample().
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sample->imag(), (FixReal) -sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             case 1:
                 // insert sample into ring-buffer
                 storeSample((FixReal) -sample->real(), (FixReal) -sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 2;
                 // tell caller we have a new sample
                 return true;
             case 2:
                 // insert sample into ring-buffer
                 storeSample((FixReal) -sample->imag(), (FixReal) sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 3;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sample->real(), (FixReal) sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workInterpolateCenter()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenter (Sample * sampleIn, Sample * SampleOut) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 98 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::doInterpolateFIR(), Sample::imag(), IntHalfbandFilterEO1< HBFilterOrder >::m_ptr, IntHalfbandFilterEO1< HBFilterOrder >::m_samples, IntHalfbandFilterEO1< HBFilterOrder >::m_state, Sample::real(), Sample::setImag(), and Sample::setReal().
     {
         switch(m_state)
         {
         case 0:
             // return the middle peak
             SampleOut->setReal(m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]);
             SampleOut->setImag(m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);
             m_state = 1;  // next state
             return false; // tell caller we didn't consume the sample
         default:
             // calculate with non null samples
             doInterpolateFIR(SampleOut);
             // insert sample into ring double buffer
             m_samples[m_ptr][0] = sampleIn->real();
             m_samples[m_ptr][1] = sampleIn->imag();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 0; // next state
             return true; // tell caller we consumed the sample
         }
     }
workInterpolateCenterZeroStuffing()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenterZeroStuffing (Sample * sampleIn, Sample * SampleOut) inline
Definition at line 67 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::advancePointer(), IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), Sample::imag(), IntHalfbandFilterEO1< HBFilterOrder >::m_state, Sample::real(), and IntHalfbandFilterEO1< HBFilterOrder >::storeSample().
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSample((FixReal) 0, (FixReal) 0);
                 // save result
                 doFIR(SampleOut);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we didn't consume the sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
                 // save result
                 doFIR(SampleOut);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we consumed the sample
                 return true;
         }
     }
workInterpolateLowerHalf()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalf (Sample * sampleIn, Sample * sampleOut) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 291 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::doInterpolateFIR(), Sample::imag(), IntHalfbandFilterEO1< HBFilterOrder >::m_ptr, IntHalfbandFilterEO1< HBFilterOrder >::m_samples, IntHalfbandFilterEO1< HBFilterOrder >::m_state, Sample::real(), Sample::setImag(), and Sample::setReal().
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // return the middle peak
             sampleOut->setReal(m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);  // imag
             sampleOut->setImag(-m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]); // - real
             m_state = 1;  // next state
             return false; // tell caller we didn't consume the sample
         case 1:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // insert sample into ring double buffer
             m_samples[m_ptr][0] = sampleIn->real();
             m_samples[m_ptr][1] = sampleIn->imag();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 2; // next state
             return true; // tell caller we consumed the sample
         case 2:
             // return the middle peak
             sampleOut->setReal(-m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);  // - imag
             sampleOut->setImag(m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]); // real
             m_state = 3;  // next state
             return false; // tell caller we didn't consume the sample
         default:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // insert sample into ring double buffer
             m_samples[m_ptr][0] = sampleIn->real();
             m_samples[m_ptr][1] = sampleIn->imag();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 0; // next state
             return true; // tell caller we consumed the sample
         }
     }
workInterpolateLowerHalfZeroStuffing()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalfZeroStuffing (Sample * sampleIn, Sample * sampleOut) inline
Definition at line 210 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::advancePointer(), IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), Sample::imag(), IntHalfbandFilterEO1< HBFilterOrder >::m_state, Sample::real(), Sample::setImag(), Sample::setReal(), and IntHalfbandFilterEO1< HBFilterOrder >::storeSample().
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // insert sample into ring-buffer
             storeSample((FixReal) 0, (FixReal) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(s.imag());
             sampleOut->setImag(-s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 1;
             // tell caller we didn't consume the sample
             return false;
         case 1:
             // insert sample into ring-buffer
             storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 2;
             // tell caller we consumed the sample
             return true;
         case 2:
             // insert sample into ring-buffer
             storeSample((FixReal) 0, (FixReal) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.imag());
             sampleOut->setImag(s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 3;
             // tell caller we didn't consume the sample
             return false;
         default:
             // insert sample into ring-buffer
             storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 0;
             // tell caller we consumed the sample
             return true;
         }
     }
workInterpolateUpperHalf()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalf (Sample * sampleIn, Sample * sampleOut) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 490 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::doInterpolateFIR(), Sample::imag(), IntHalfbandFilterEO1< HBFilterOrder >::m_ptr, IntHalfbandFilterEO1< HBFilterOrder >::m_samples, IntHalfbandFilterEO1< HBFilterOrder >::m_state, Sample::real(), Sample::setImag(), and Sample::setReal().
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // return the middle peak
             sampleOut->setReal(-m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]); // - imag
             sampleOut->setImag(m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]); // + real
             m_state = 1;  // next state
             return false; // tell caller we didn't consume the sample
         case 1:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // insert sample into ring double buffer
             m_samples[m_ptr][0] = sampleIn->real();
             m_samples[m_ptr][1] = sampleIn->imag();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 2; // next state
             return true; // tell caller we consumed the sample
         case 2:
             // return the middle peak
             sampleOut->setReal(m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);  // + imag
             sampleOut->setImag(-m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]);   // - real
             m_state = 3;  // next state
             return false; // tell caller we didn't consume the sample
         default:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // insert sample into ring double buffer
             m_samples[m_ptr][0] = sampleIn->real();
             m_samples[m_ptr][1] = sampleIn->imag();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 0; // next state
             return true; // tell caller we consumed the sample
         }
     }
workInterpolateUpperHalfZeroStuffing()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalfZeroStuffing (Sample * sampleIn, Sample * sampleOut) inline
Definition at line 409 of file inthalfbandfiltereo1.h.
References IntHalfbandFilterEO1< HBFilterOrder >::advancePointer(), IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), Sample::imag(), IntHalfbandFilterEO1< HBFilterOrder >::m_state, Sample::real(), Sample::setImag(), Sample::setReal(), and IntHalfbandFilterEO1< HBFilterOrder >::storeSample().
     {
         Sample s;
         switch(m_state)
         {
         case 0:
             // insert sample into ring-buffer
             storeSample((FixReal) 0, (FixReal) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.imag());
             sampleOut->setImag(s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 1;
             // tell caller we didn't consume the sample
             return false;
         case 1:
             // insert sample into ring-buffer
             storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 2;
             // tell caller we consumed the sample
             return true;
         case 2:
             // insert sample into ring-buffer
             storeSample((FixReal) 0, (FixReal) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(s.imag());
             sampleOut->setImag(-s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 3;
             // tell caller we didn't consume the sample
             return false;
         default:
             // insert sample into ring-buffer
             storeSample((FixReal) sampleIn->real(), (FixReal) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 0;
             // tell caller we consumed the sample
             return true;
         }
     }
Member Data Documentation
m_even
template<uint32_t HBFilterOrder> int32_t IntHalfbandFilterEO1< HBFilterOrder >::m_even[2][HBFIRFilterTraits< HBFilterOrder >::hbOrder] protected
Definition at line 657 of file inthalfbandfiltereo1.h.
Referenced by IntHalfbandFilterEO1< HBFilterOrder >::IntHalfbandFilterEO1().
m_odd
template<uint32_t HBFilterOrder> int32_t IntHalfbandFilterEO1< HBFilterOrder >::m_odd[2][HBFIRFilterTraits< HBFilterOrder >::hbOrder] protected
Definition at line 658 of file inthalfbandfiltereo1.h.
Referenced by IntHalfbandFilterEO1< HBFilterOrder >::IntHalfbandFilterEO1().
m_ptr
template<uint32_t HBFilterOrder> int IntHalfbandFilterEO1< HBFilterOrder >::m_ptr protected
Definition at line 661 of file inthalfbandfiltereo1.h.
Referenced by IntHalfbandFilterEO1< HBFilterOrder >::doInterpolateFIR(), IntHalfbandFilterEO1< HBFilterOrder >::IntHalfbandFilterEO1(), IntHalfbandFilterEO1< HBFilterOrder >::myInterpolate(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalf(), and IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalf().
m_samples
template<uint32_t HBFilterOrder> int32_t IntHalfbandFilterEO1< HBFilterOrder >::m_samples[HBFIRFilterTraits< HBFilterOrder >::hbOrder][2] protected
Definition at line 659 of file inthalfbandfiltereo1.h.
Referenced by IntHalfbandFilterEO1< HBFilterOrder >::IntHalfbandFilterEO1(), IntHalfbandFilterEO1< HBFilterOrder >::myInterpolate(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalf(), and IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalf().
m_size
template<uint32_t HBFilterOrder> int IntHalfbandFilterEO1< HBFilterOrder >::m_size protected
Definition at line 662 of file inthalfbandfiltereo1.h.
Referenced by IntHalfbandFilterEO1< HBFilterOrder >::doFIR(), IntHalfbandFilterEO1< HBFilterOrder >::IntHalfbandFilterEO1(), IntHalfbandFilterEO1< HBFilterOrder >::storeSample(), and IntHalfbandFilterEO1< HBFilterOrder >::storeSample32().
m_state
template<uint32_t HBFilterOrder> int IntHalfbandFilterEO1< HBFilterOrder >::m_state protected
Definition at line 663 of file inthalfbandfiltereo1.h.
Referenced by IntHalfbandFilterEO1< HBFilterOrder >::IntHalfbandFilterEO1(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateLowerHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workDecimateUpperHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenter(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateCenterZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalf(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateLowerHalfZeroStuffing(), IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalf(), and IntHalfbandFilterEO1< HBFilterOrder >::workInterpolateUpperHalfZeroStuffing().
The documentation for this class was generated from the following file:
sdrbase/dsp/inthalfbandfiltereo1.h