SDRAngel: DeviceLimeSDRParams Struct Reference
DeviceLimeSDRParams Struct Reference
#include <devicelimesdrparam.h>
Public Types
enum LimeType { LimeSPI, LimeMini, LimeUSB, LimeUndefined }
Public Member Functions
DeviceLimeSDRParams ()
bool open (lms_info_str_t deviceStr)
void close ()
lms_device_t * getDevice ()
~DeviceLimeSDRParams ()
Public Attributes
lms_device_t * m_dev
device handle
uint32_t m_nbRxChannels
number of Rx channels (normally 2, we'll see if we really use it...)
uint32_t m_nbTxChannels
number of Tx channels (normally 2, we'll see if we really use it...)
lms_range_t m_lpfRangeRx
Low pass filter range information (Rx side)
lms_range_t m_lpfRangeTx
Low pass filter range information (Tx side)
lms_range_t m_loRangeRx
LO range for Rx.
lms_range_t m_loRangeTx
LO range for Tx.
lms_range_t m_srRangeRx
ADC sample rate range.
lms_range_t m_srRangeTx
DAC sample rate range.
float m_sampleRate
ADC/DAC sample rate.
int m_log2OvSRRx
log2 of Rx oversampling (0..5)
int m_log2OvSRTx
log2 of Tx oversampling (0..5)
float m_rxFrequency
Rx frequency.
float m_txFrequency
Tx frequency.
LimeType m_type
Hardware type.
Private Member Functions
void getHardwareType (const char *device_str)
Detailed Description
This structure refers to one physical device shared among parties (logical devices represented by the DeviceAPI with single Rx or Tx stream type). It allows storing information on the common resources in one place and is shared among participants. There is only one copy that is constructed by the first participant and destroyed by the last. A participant knows it is the first or last by checking the lists of buddies (Rx + Tx).
Definition at line 32 of file devicelimesdrparam.h.
Member Enumeration Documentation
LimeType
enum DeviceLimeSDRParams::LimeType
Enumerator
LimeSPI
LimeMini
LimeUSB
LimeUndefined
Definition at line 34 of file devicelimesdrparam.h.
     {
         LimeSPI,
         LimeMini,
         LimeUSB,
         LimeUndefined
     };
Constructor & Destructor Documentation
DeviceLimeSDRParams()
DeviceLimeSDRParams::DeviceLimeSDRParams () inline
Definition at line 58 of file devicelimesdrparam.h.
                           :
         m_dev(0),
         m_nbRxChannels(0),
         m_nbTxChannels(0),
         m_sampleRate(1e6),
         m_log2OvSRRx(0),
         m_log2OvSRTx(0),
         m_rxFrequency(1e6),
         m_txFrequency(1e6),
         m_type(LimeUndefined)
     {
         m_lpfRangeRx.max = 0.0f;
         m_lpfRangeRx.min = 0.0f;
         m_lpfRangeRx.step = 0.0f;
         m_lpfRangeTx.max = 0.0f;
         m_lpfRangeTx.min = 0.0f;
         m_lpfRangeTx.step = 0.0f;
         m_loRangeRx.max = 0.0f;
         m_loRangeRx.min = 0.0f;
         m_loRangeRx.step = 0.0f;
         m_loRangeTx.max = 0.0f;
         m_loRangeTx.min = 0.0f;
         m_loRangeTx.step = 0.0f;
         m_srRangeRx.max = 0.0f;
         m_srRangeRx.min = 0.0f;
         m_srRangeRx.step = 0.0f;
         m_srRangeTx.max = 0.0f;
         m_srRangeTx.min = 0.0f;
         m_srRangeTx.step = 0.0f;
     }
~DeviceLimeSDRParams()
DeviceLimeSDRParams::~DeviceLimeSDRParams () inline
Definition at line 101 of file devicelimesdrparam.h.
     {
     }
Member Function Documentation
close()
void DeviceLimeSDRParams::close ()
Definition at line 102 of file devicelimesdrparam.cpp.
References m_dev.
Referenced by LimeSDROutput::closeDevice(), LimeSDRInput::closeDevice(), LimeSDROutputPlugin::enumSampleSinks(), and LimeSDRInputPlugin::enumSampleSources().
 {
     if (m_dev)
     {
         LMS_Close(m_dev);
         m_dev = 0;
     }
 }
getDevice()
lms_device_t* DeviceLimeSDRParams::getDevice () inline
Definition at line 99 of file devicelimesdrparam.h.
Referenced by LimeSDROutput::acquireChannel(), LimeSDRInput::acquireChannel(), LimeSDROutput::applySettings(), LimeSDRInput::applySettings(), LimeSDROutput::closeDevice(), LimeSDRInput::closeDevice(), LimeSDROutput::handleMessage(), LimeSDRInput::handleMessage(), LimeSDROutput::releaseChannel(), LimeSDRInput::releaseChannel(), LimeSDROutput::start(), LimeSDRInput::start(), LimeSDROutput::webapiFormatDeviceReport(), and LimeSDRInput::webapiFormatDeviceReport().
 { return m_dev; }
getHardwareType()
void DeviceLimeSDRParams::getHardwareType (const char * device_str) private
Definition at line 111 of file devicelimesdrparam.cpp.
References LimeMini, LimeSPI, LimeUndefined, LimeUSB, and m_type.
Referenced by open().
 {
     QString deviceStr(device_str);
     if (deviceStr.contains(QString("LimeSDR Mini"))) {
         m_type = LimeMini;
     } else if (deviceStr.contains(QString("LimeSDR-USB"))) {
         m_type = LimeUSB;
     } else if (deviceStr.contains(QString("media=SPI"))) {
         m_type = LimeSPI;
     } else {
         m_type = LimeUndefined;
     }
 }
open()
bool DeviceLimeSDRParams::open (lms_info_str_t deviceStr)
Opens and initialize the device and obtain information (# channels, ranges, ...)
Definition at line 21 of file devicelimesdrparam.cpp.
References getHardwareType(), m_dev, m_loRangeRx, m_loRangeTx, m_lpfRangeRx, m_lpfRangeTx, m_nbRxChannels, m_nbTxChannels, m_srRangeRx, m_srRangeTx, and m_type.
Referenced by LimeSDROutputPlugin::enumSampleSinks(), LimeSDRInputPlugin::enumSampleSources(), LimeSDROutput::openDevice(), and LimeSDRInput::openDevice().
 {
     getHardwareType((const char *) deviceStr);
     qDebug("DeviceLimeSDRParams::open: serial: %s type: %d", (const char *) deviceStr, (int) m_type);
     if (LMS_Open(&m_dev, deviceStr, 0) < 0)
     {
         qCritical() << "DeviceLimeSDRParams::open: cannot open device " << deviceStr;
         return false;
     }
     if (LMS_Init(m_dev) < 0)
     {
         qCritical() << "DeviceLimeSDRParams::open: cannot init device " << deviceStr;
         return false;
     }
     int n;
     if ((n = LMS_GetNumChannels(m_dev, LMS_CH_RX)) < 0)
     {
         qCritical() << "DeviceLimeSDRParams::open: cannot get the number of Rx channels for device " << deviceStr;
         return false;
     }
     else
     {
         m_nbRxChannels = n;
         qDebug() << "DeviceLimeSDRParams::open: " << n << " Rx channels for device " << deviceStr;
     }
     if ((n = LMS_GetNumChannels(m_dev, LMS_CH_TX)) < 0)
     {
         qCritical() << "DeviceLimeSDRParams::open: cannot get the number of Tx channels for device " << deviceStr;
         return false;
     }
     else
     {
         m_nbTxChannels = n;
         qDebug() << "DeviceLimeSDRParams::open: " << n << " Tx channels for device " << deviceStr;
     }
     if (LMS_GetLPFBWRange(m_dev, LMS_CH_RX, &m_lpfRangeRx) < 0)
     {
         qCritical() << "DeviceLimeSDRParams::open: cannot get the Rx LPF range for device " << deviceStr;
         return false;
     }
     if (LMS_GetLPFBWRange(m_dev, LMS_CH_TX, &m_lpfRangeTx) < 0)
     {
         qCritical() << "DeviceLimeSDRParams::open: cannot get the Tx LPF range for device " << deviceStr;
         return false;
     }
     if (LMS_GetLOFrequencyRange(m_dev, LMS_CH_RX, &m_loRangeRx) < 0)
     {
         qDebug() << "DeviceLimeSDRParams::open: cannot get the Rx LO range for device " << deviceStr;
         return false;
     }
     if (LMS_GetLOFrequencyRange(m_dev, LMS_CH_TX, &m_loRangeTx) < 0)
     {
         qCritical() << "DeviceLimeSDRParams::open: cannot get the Tx LO range for device " << deviceStr;
         return false;
     }
     if (LMS_GetSampleRateRange(m_dev, LMS_CH_RX, &m_srRangeRx) < 0)
     {
         qCritical() << "DeviceLimeSDRParams::open: cannot get the Rx sample rate range for device " << deviceStr;
         return false;
     }
     if (LMS_GetSampleRateRange(m_dev, LMS_CH_TX, &m_srRangeTx) < 0)
     {
         qCritical() << "DeviceLimeSDRParams::open: cannot get the Tx sample rate range for device " << deviceStr;
         return false;
     }
     return true;
 }
Member Data Documentation
m_dev
lms_device_t* DeviceLimeSDRParams::m_dev
device handle
Definition at line 42 of file devicelimesdrparam.h.
Referenced by close(), and open().
m_log2OvSRRx
int DeviceLimeSDRParams::m_log2OvSRRx
log2 of Rx oversampling (0..5)
Definition at line 52 of file devicelimesdrparam.h.
Referenced by LimeSDRInput::applySettings(), and LimeSDRInput::getHWLog2Decim().
m_log2OvSRTx
int DeviceLimeSDRParams::m_log2OvSRTx
log2 of Tx oversampling (0..5)
Definition at line 53 of file devicelimesdrparam.h.
Referenced by LimeSDROutput::applySettings(), and LimeSDROutput::getHWLog2Interp().
m_loRangeRx
lms_range_t DeviceLimeSDRParams::m_loRangeRx
LO range for Rx.
Definition at line 47 of file devicelimesdrparam.h.
Referenced by LimeSDRInput::getLORange(), and open().
m_loRangeTx
lms_range_t DeviceLimeSDRParams::m_loRangeTx
LO range for Tx.
Definition at line 48 of file devicelimesdrparam.h.
Referenced by LimeSDROutput::getLORange(), and open().
m_lpfRangeRx
lms_range_t DeviceLimeSDRParams::m_lpfRangeRx
Low pass filter range information (Rx side)
Definition at line 45 of file devicelimesdrparam.h.
Referenced by LimeSDRInput::getLPRange(), and open().
m_lpfRangeTx
lms_range_t DeviceLimeSDRParams::m_lpfRangeTx
Low pass filter range information (Tx side)
Definition at line 46 of file devicelimesdrparam.h.
Referenced by LimeSDROutput::getLPRange(), and open().
m_nbRxChannels
uint32_t DeviceLimeSDRParams::m_nbRxChannels
number of Rx channels (normally 2, we'll see if we really use it...)
Definition at line 43 of file devicelimesdrparam.h.
Referenced by LimeSDRInputPlugin::enumSampleSources(), open(), and LimeSDRInput::openDevice().
m_nbTxChannels
uint32_t DeviceLimeSDRParams::m_nbTxChannels
number of Tx channels (normally 2, we'll see if we really use it...)
Definition at line 44 of file devicelimesdrparam.h.
Referenced by LimeSDROutputPlugin::enumSampleSinks(), open(), and LimeSDROutput::openDevice().
m_rxFrequency
float DeviceLimeSDRParams::m_rxFrequency
Rx frequency.
Definition at line 54 of file devicelimesdrparam.h.
m_sampleRate
float DeviceLimeSDRParams::m_sampleRate
ADC/DAC sample rate.
Definition at line 51 of file devicelimesdrparam.h.
Referenced by LimeSDROutput::applySettings(), and LimeSDRInput::applySettings().
m_srRangeRx
lms_range_t DeviceLimeSDRParams::m_srRangeRx
ADC sample rate range.
Definition at line 49 of file devicelimesdrparam.h.
Referenced by LimeSDRInput::getSRRange(), and open().
m_srRangeTx
lms_range_t DeviceLimeSDRParams::m_srRangeTx
DAC sample rate range.
Definition at line 50 of file devicelimesdrparam.h.
Referenced by LimeSDROutput::getSRRange(), and open().
m_txFrequency
float DeviceLimeSDRParams::m_txFrequency
Tx frequency.
Definition at line 55 of file devicelimesdrparam.h.
m_type
LimeType DeviceLimeSDRParams::m_type
Hardware type.
Definition at line 56 of file devicelimesdrparam.h.
Referenced by LimeSDROutput::applySettings(), LimeSDRInput::applySettings(), getHardwareType(), LimeSDROutput::getLimeType(), LimeSDRInput::getLimeType(), LimeSDROutput::handleMessage(), LimeSDRInput::handleMessage(), and open().
The documentation for this struct was generated from the following files:
devices/limesdr/devicelimesdrparam.h
devices/limesdr/devicelimesdrparam.cpp