SDRAngel: WFMMod::MsgReportFileSourceStreamData Class Reference
WFMMod::MsgReportFileSourceStreamData Class Reference
#include <wfmmod.h>
Public Member Functions
int getSampleRate () const
quint32 getRecordLength () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportFileSourceStreamData * create (int sampleRate, quint32 recordLength)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportFileSourceStreamData (int sampleRate, quint32 recordLength)
Protected Attributes
int m_sampleRate
quint32 m_recordLength
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 178 of file wfmmod.h.
Constructor & Destructor Documentation
MsgReportFileSourceStreamData()
WFMMod::MsgReportFileSourceStreamData::MsgReportFileSourceStreamData (int sampleRate, quint32 recordLength) inline protected
Definition at line 195 of file wfmmod.h.
References WFMMod::WFMMod(), and WFMMod::~WFMMod().
                                       :
             Message(),
             m_sampleRate(sampleRate),
             m_recordLength(recordLength)
         { }
Member Function Documentation
create()
static MsgReportFileSourceStreamData* WFMMod::MsgReportFileSourceStreamData::create (int sampleRate, quint32 recordLength) inline static
Definition at line 185 of file wfmmod.h.
Referenced by WFMMod::openFileStream().
         {
             return new MsgReportFileSourceStreamData(sampleRate, recordLength);
         }
getRecordLength()
quint32 WFMMod::MsgReportFileSourceStreamData::getRecordLength () const inline
Definition at line 183 of file wfmmod.h.
References WFMMod::m_recordLength.
 { return m_recordLength; }
getSampleRate()
int WFMMod::MsgReportFileSourceStreamData::getSampleRate () const inline
Definition at line 182 of file wfmmod.h.
References WFMMod::m_sampleRate.
 { return m_sampleRate; }
Member Data Documentation
m_recordLength
quint32 WFMMod::MsgReportFileSourceStreamData::m_recordLength protected
Definition at line 193 of file wfmmod.h.
m_sampleRate
int WFMMod::MsgReportFileSourceStreamData::m_sampleRate protected
Definition at line 192 of file wfmmod.h.
The documentation for this class was generated from the following file:
plugins/channeltx/modwfm/wfmmod.h