SDRAngel: LocalInput::MsgStartStop Class Reference
LocalInput::MsgStartStop Class Reference
#include <localinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 84 of file localinput.h.
Constructor & Destructor Documentation
MsgStartStop()
LocalInput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 97 of file localinput.h.
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* LocalInput::MsgStartStop::create (bool startStop) inline static
Definition at line 90 of file localinput.h.
Referenced by LocalInputGui::on_startStop_toggled(), and LocalInput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool LocalInput::MsgStartStop::getStartStop () const inline
Definition at line 88 of file localinput.h.
Referenced by LocalInputGui::handleMessage(), and LocalInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool LocalInput::MsgStartStop::m_startStop protected
Definition at line 95 of file localinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/localinput/localinput.h