SDRAngel: SDRPlayInput::MsgConfigureSDRPlay Class Reference
SDRPlayInput::MsgConfigureSDRPlay Class Reference
#include <sdrplayinput.h>
Public Member Functions
const SDRPlaySettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureSDRPlay * create (const SDRPlaySettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureSDRPlay (const SDRPlaySettings &settings, bool force)
Private Attributes
SDRPlaySettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 48 of file sdrplayinput.h.
Constructor & Destructor Documentation
MsgConfigureSDRPlay()
SDRPlayInput::MsgConfigureSDRPlay::MsgConfigureSDRPlay (const SDRPlaySettings & settings, bool force) inline private
Definition at line 64 of file sdrplayinput.h.
Referenced by create().
                                                                          :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureSDRPlay* SDRPlayInput::MsgConfigureSDRPlay::create (const SDRPlaySettings & settings, bool force) inline static
Definition at line 55 of file sdrplayinput.h.
References MsgConfigureSDRPlay().
Referenced by SDRPlayInput::deserialize(), SDRPlayInput::setCenterFrequency(), SDRPlayGui::updateHardware(), and SDRPlayInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureSDRPlay(settings, force);
         }
getForce()
bool SDRPlayInput::MsgConfigureSDRPlay::getForce () const inline
Definition at line 53 of file sdrplayinput.h.
References m_force.
Referenced by SDRPlayInput::handleMessage().
 { return m_force; }
getSettings()
const SDRPlaySettings& SDRPlayInput::MsgConfigureSDRPlay::getSettings () const inline
Definition at line 52 of file sdrplayinput.h.
References m_settings.
Referenced by SDRPlayGui::handleMessage(), and SDRPlayInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool SDRPlayInput::MsgConfigureSDRPlay::m_force private
Definition at line 62 of file sdrplayinput.h.
Referenced by getForce().
m_settings
SDRPlaySettings SDRPlayInput::MsgConfigureSDRPlay::m_settings private
Definition at line 61 of file sdrplayinput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/sdrplay/sdrplayinput.h