SDRAngel: WFMPlugin Class Reference
WFMPlugin Class Reference
#include <wfmplugin.h>
Public Member Functions
WFMPlugin (QObject *parent=NULL)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
Private Attributes
PluginAPI * m_pluginAPI
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Private Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Private Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Detailed Description
Definition at line 10 of file wfmplugin.h.
Constructor & Destructor Documentation
WFMPlugin()
WFMPlugin::WFMPlugin (QObject * parent = NULL) explicit
Definition at line 20 of file wfmplugin.cpp.
                                     :
     QObject(parent),
     m_pluginAPI(0)
 {
 }
Member Function Documentation
createRxChannelBS()
BasebandSampleSink * WFMPlugin::createRxChannelBS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 53 of file wfmplugin.cpp.
 {
     return new WFMDemod(deviceAPI);
 }
createRxChannelCS()
ChannelAPI * WFMPlugin::createRxChannelCS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 58 of file wfmplugin.cpp.
 {
     return new WFMDemod(deviceAPI);
 }
createRxChannelGUI()
PluginInstanceGUI * WFMPlugin::createRxChannelGUI (DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) virtual
Reimplemented from PluginInterface.
Definition at line 47 of file wfmplugin.cpp.
References WFMDemodGUI::create(), and m_pluginAPI.
Referenced by initPlugin().
 {
     return WFMDemodGUI::create(m_pluginAPI, deviceUISet, rxChannel);
 }
getPluginDescriptor()
const PluginDescriptor & WFMPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 26 of file wfmplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void WFMPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 31 of file wfmplugin.cpp.
References createRxChannelGUI(), WFMDemod::m_channelId, WFMDemod::m_channelIdURI, m_pluginAPI, and PluginAPI::registerRxChannel().
 {
     m_pluginAPI = pluginAPI;
     // register WFM demodulator
     m_pluginAPI->registerRxChannel(WFMDemod::m_channelIdURI, WFMDemod::m_channelId, this);
 }
Member Data Documentation
m_pluginAPI
PluginAPI* WFMPlugin::m_pluginAPI private
Definition at line 28 of file wfmplugin.h.
Referenced by createRxChannelGUI(), and initPlugin().
m_pluginDescriptor
const PluginDescriptor WFMPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("WFM Demodulator"),
    QString("4.9.1"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 26 of file wfmplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/channelrx/demodwfm/wfmplugin.h
plugins/channelrx/demodwfm/wfmplugin.cpp