SDRAngel: MainCore::MsgAddChannel Class Reference
MainCore::MsgAddChannel Class Reference
Public Member Functions
int getDeviceSetIndex () const
int getChannelRegistrationIndex () const
bool isTx () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgAddChannel * create (int deviceSetIndex, int channelRegistrationIndex, bool tx)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgAddChannel (int deviceSetIndex, int channelRegistrationIndex, bool tx)
Private Attributes
int m_deviceSetIndex
int m_channelRegistrationIndex
bool m_tx
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 220 of file maincore.h.
Constructor & Destructor Documentation
MsgAddChannel()
MainCore::MsgAddChannel::MsgAddChannel (int deviceSetIndex, int channelRegistrationIndex, bool tx) inline private
Definition at line 238 of file maincore.h.
                                                                                  :
             Message(),
             m_deviceSetIndex(deviceSetIndex),
             m_channelRegistrationIndex(channelRegistrationIndex),
             m_tx(tx)
         { }
Member Function Documentation
create()
static MsgAddChannel* MainCore::MsgAddChannel::create (int deviceSetIndex, int channelRegistrationIndex, bool tx) inline static
Definition at line 228 of file maincore.h.
Referenced by WebAPIAdapterSrv::devicesetChannelPost().
         {
             return new MsgAddChannel(deviceSetIndex, channelRegistrationIndex, tx);
         }
getChannelRegistrationIndex()
int MainCore::MsgAddChannel::getChannelRegistrationIndex () const inline
Definition at line 225 of file maincore.h.
Referenced by MainCore::handleMessage().
 { return m_channelRegistrationIndex; }
getDeviceSetIndex()
int MainCore::MsgAddChannel::getDeviceSetIndex () const inline
Definition at line 224 of file maincore.h.
Referenced by MainCore::handleMessage().
 { return m_deviceSetIndex; }
isTx()
bool MainCore::MsgAddChannel::isTx () const inline
Definition at line 226 of file maincore.h.
 { return m_tx; }
Member Data Documentation
m_channelRegistrationIndex
int MainCore::MsgAddChannel::m_channelRegistrationIndex private
Definition at line 235 of file maincore.h.
m_deviceSetIndex
int MainCore::MsgAddChannel::m_deviceSetIndex private
Definition at line 234 of file maincore.h.
m_tx
bool MainCore::MsgAddChannel::m_tx private
Definition at line 236 of file maincore.h.
The documentation for this class was generated from the following file:
sdrsrv/maincore.h