SDRAngel: SDRPlaySampleRates Class Reference
SDRPlaySampleRates Class Reference
#include <sdrplayinput.h>
Static Public Member Functions
static unsigned int getRate (unsigned int rate_index)
static unsigned int getRateIndex (unsigned int rate)
static unsigned int getNbRates ()
Static Private Attributes
static const unsigned int m_nb_rates = 18
static unsigned int m_rates [m_nb_rates]
Detailed Description
Definition at line 212 of file sdrplayinput.h.
Member Function Documentation
getNbRates()
unsigned int SDRPlaySampleRates::getNbRates () static
Definition at line 1022 of file sdrplayinput.cpp.
References SDRPlayBandwidths::m_bw, and m_nb_rates.
Referenced by SDRPlayGui::SDRPlayGui(), and SDRPlayInput::webapiFormatDeviceReport().
 {
     return SDRPlaySampleRates::m_nb_rates;
 }
getRate()
unsigned int SDRPlaySampleRates::getRate (unsigned int rate_index) static
Definition at line 997 of file sdrplayinput.cpp.
Referenced by SDRPlayInput::applySettings(), SDRPlayInput::getSampleRate(), SDRPlayGui::SDRPlayGui(), SDRPlayInput::start(), and SDRPlayInput::webapiFormatDeviceReport().
 {
     if (rate_index < m_nb_rates)
     {
         return m_rates[rate_index];
     }
     else
     {
         return m_rates[0];
     }
 }
getRateIndex()
unsigned int SDRPlaySampleRates::getRateIndex (unsigned int rate) static
Definition at line 1009 of file sdrplayinput.cpp.
References i.
 {
     for (unsigned int i=0; i < m_nb_rates; i++)
     {
         if (rate == m_rates[i])
         {
             return i;
         }
     }
     return 0;
 }
Member Data Documentation
m_nb_rates
const unsigned int SDRPlaySampleRates::m_nb_rates = 18 static private
Definition at line 218 of file sdrplayinput.h.
Referenced by getNbRates().
m_rates
unsigned int SDRPlaySampleRates::m_rates static private
Initial value:
= {
        1536000,
        1792000,
        2000000,
        2048000,
        2304000,
        2400000,
        3072000,
        3200000,
        4000000,
        4096000,
        4608000,
        4800000,
        5000000,
        6000000,
        6144000,
        6400000,
        8000000,
        8192000,
}
Definition at line 219 of file sdrplayinput.h.
Referenced by SDRPlayInput::networkManagerFinished().
The documentation for this class was generated from the following files:
plugins/samplesource/sdrplay/sdrplayinput.h
plugins/samplesource/sdrplay/sdrplayinput.cpp