SDRAngel: TestSourceInput Class Reference
TestSourceInput Class Reference
#include <testsourceinput.h>
Classes
class MsgConfigureTestSource
class MsgFileRecord
class MsgStartStop
Public Member Functions
TestSourceInput (DeviceAPI *deviceAPI)
virtual ~TestSourceInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool applySettings (const TestSourceSettings &settings, bool force)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const TestSourceSettings &settings)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const TestSourceSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
FileRecord * m_fileSink
File sink to record device I/Q output.
QMutex m_mutex
TestSourceSettings m_settings
TestSourceThread * m_testSourceThread
QString m_deviceDescription
bool m_running
const QTimer & m_masterTimer
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 35 of file testsourceinput.h.
Constructor & Destructor Documentation
TestSourceInput()
TestSourceInput::TestSourceInput (DeviceAPI * deviceAPI)
Definition at line 41 of file testsourceinput.cpp.
References arg().
Referenced by TestSourceInput::MsgStartStop::MsgStartStop().
                                                      :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_testSourceThread(0),
     m_deviceDescription(),
     m_running(false),
     m_masterTimer(deviceAPI->getMasterTimer())
 {
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     if (!m_sampleFifo.setSize(96000 * 4)) {
         qCritical("TestSourceInput::TestSourceInput: Could not allocate SampleFifo");
     }
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~TestSourceInput()
TestSourceInput::~TestSourceInput () virtual
Definition at line 61 of file testsourceinput.cpp.
References m_deviceAPI, m_fileSink, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::removeAncillarySink(), and stop().
Referenced by TestSourceInput::MsgStartStop::MsgStartStop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
 }
Member Function Documentation
applySettings()
bool TestSourceInput::applySettings (const TestSourceSettings & settings, bool force) private
Definition at line 240 of file testsourceinput.cpp.
References TestSourceSettings::AutoCorrDC, TestSourceSettings::AutoCorrDCAndIQ, TestSourceSettings::AutoCorrNone, DeviceSampleSource::calculateDeviceCenterFrequency(), DeviceSampleSource::calculateFrequencyShift(), DeviceAPI::configureCorrections(), DeviceSampleSource::FSHIFT_STD, DeviceAPI::getDeviceEngineInputMessageQueue(), FileRecord::handleMessage(), TestSourceSettings::m_amModulation, TestSourceSettings::m_amplitudeBits, TestSourceSettings::m_autoCorrOptions, TestSourceSettings::m_centerFrequency, TestSourceSettings::m_dcFactor, m_deviceAPI, TestSourceSettings::m_fcPos, m_fileSink, TestSourceSettings::m_fmDeviation, TestSourceSettings::m_frequencyShift, TestSourceSettings::m_iFactor, TestSourceSettings::m_log2Decim, TestSourceSettings::m_modulation, TestSourceSettings::m_modulationTone, TestSourceSettings::m_phaseImbalance, TestSourceSettings::m_qFactor, TestSourceSettings::m_reverseAPIAddress, TestSourceSettings::m_reverseAPIDeviceIndex, TestSourceSettings::m_reverseAPIPort, TestSourceSettings::m_sampleRate, TestSourceSettings::m_sampleSizeIndex, m_settings, m_testSourceThread, TestSourceSettings::m_useReverseAPI, TestSourceSettings::ModulationPattern0, TestSourceSettings::ModulationPattern1, TestSourceSettings::ModulationPattern2, MessageQueue::push(), TestSourceThread::setAMModulation(), TestSourceThread::setAmplitudeBits(), TestSourceThread::setBitSize(), TestSourceThread::setDCFactor(), TestSourceThread::setFcPos(), TestSourceThread::setFMDeviation(), TestSourceThread::setFrequencyShift(), TestSourceThread::setIFactor(), TestSourceThread::setLog2Decimation(), TestSourceThread::setModulation(), TestSourceThread::setPattern0(), TestSourceThread::setPattern1(), TestSourceThread::setPattern2(), TestSourceThread::setPhaseImbalance(), TestSourceThread::setQFactor(), TestSourceThread::setSamplerate(), TestSourceThread::setToneFrequency(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     QList<QString> reverseAPIKeys;
     if ((m_settings.m_autoCorrOptions != settings.m_autoCorrOptions) || force)
     {
         reverseAPIKeys.append("autoCorrOptions");
         switch(settings.m_autoCorrOptions)
         {
         case TestSourceSettings::AutoCorrDC:
             m_deviceAPI->configureCorrections(true, false);
             break;
         case TestSourceSettings::AutoCorrDCAndIQ:
             m_deviceAPI->configureCorrections(true, true);
             break;
         case TestSourceSettings::AutoCorrNone:
         default:
             m_deviceAPI->configureCorrections(false, false);
             break;
         }
     }
     if ((m_settings.m_sampleRate != settings.m_sampleRate) || force)
     {
         reverseAPIKeys.append("sampleRate");
         if (m_testSourceThread != 0)
         {
             m_testSourceThread->setSamplerate(settings.m_sampleRate);
             qDebug("TestSourceInput::applySettings: sample rate set to %d", settings.m_sampleRate);
         }
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         reverseAPIKeys.append("log2Decim");
         if (m_testSourceThread != 0)
         {
             m_testSourceThread->setLog2Decimation(settings.m_log2Decim);
             qDebug() << "TestSourceInput::applySettings: set decimation to " << (1<<settings.m_log2Decim);
         }
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency)
         || (m_settings.m_fcPos != settings.m_fcPos)
         || (m_settings.m_frequencyShift != settings.m_frequencyShift)
         || (m_settings.m_sampleRate != settings.m_sampleRate)
         || (m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         reverseAPIKeys.append("centerFrequency");
         reverseAPIKeys.append("fcPos");
         reverseAPIKeys.append("frequencyShift");
         qint64 deviceCenterFrequency = DeviceSampleSource::calculateDeviceCenterFrequency(
                 settings.m_centerFrequency,
                 0, // no transverter mode
                 settings.m_log2Decim,
                 (DeviceSampleSource::fcPos_t) settings.m_fcPos,
                 settings.m_sampleRate,
                 DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD,
                 false);
         int frequencyShift = settings.m_frequencyShift;
         quint32 devSampleRate = settings.m_sampleRate;
         if (settings.m_log2Decim != 0)
         {
             frequencyShift += DeviceSampleSource::calculateFrequencyShift(
                     settings.m_log2Decim,
                     (DeviceSampleSource::fcPos_t) settings.m_fcPos,
                     settings.m_sampleRate,
                     DeviceSampleSource::FSHIFT_STD);
         }
         if (m_testSourceThread != 0)
         {
             m_testSourceThread->setFcPos((int) settings.m_fcPos);
             m_testSourceThread->setFrequencyShift(frequencyShift);
             qDebug() << "TestSourceInput::applySettings:"
                     << " center freq: " << settings.m_centerFrequency << " Hz"
                     << " device center freq: " << deviceCenterFrequency << " Hz"
                     << " device sample rate: " << devSampleRate << "Hz"
                     << " Actual sample rate: " << devSampleRate/(1<<m_settings.m_log2Decim) << "Hz"
                     << " f shift: " << settings.m_frequencyShift;
         }
     }
     if ((m_settings.m_amplitudeBits != settings.m_amplitudeBits) || force)
     {
         reverseAPIKeys.append("amplitudeBits");
         if (m_testSourceThread != 0) {
             m_testSourceThread->setAmplitudeBits(settings.m_amplitudeBits);
         }
     }
     if ((m_settings.m_dcFactor != settings.m_dcFactor) || force)
     {
         reverseAPIKeys.append("dcFactor");
         if (m_testSourceThread != 0) {
             m_testSourceThread->setDCFactor(settings.m_dcFactor);
         }
     }
     if ((m_settings.m_iFactor != settings.m_iFactor) || force)
     {
         reverseAPIKeys.append("iFactor");
         if (m_testSourceThread != 0) {
             m_testSourceThread->setIFactor(settings.m_iFactor);
         }
     }
     if ((m_settings.m_qFactor != settings.m_qFactor) || force)
     {
         reverseAPIKeys.append("qFactor");
         if (m_testSourceThread != 0) {
             m_testSourceThread->setQFactor(settings.m_qFactor);
         }
     }
     if ((m_settings.m_phaseImbalance != settings.m_phaseImbalance) || force)
     {
         reverseAPIKeys.append("phaseImbalance");
         if (m_testSourceThread != 0) {
             m_testSourceThread->setPhaseImbalance(settings.m_phaseImbalance);
         }
     }
     if ((m_settings.m_sampleSizeIndex != settings.m_sampleSizeIndex) || force)
     {
         reverseAPIKeys.append("sampleSizeIndex");
         if (m_testSourceThread != 0) {
             m_testSourceThread->setBitSize(settings.m_sampleSizeIndex);
         }
     }
     if ((m_settings.m_sampleRate != settings.m_sampleRate)
         || (m_settings.m_centerFrequency != settings.m_centerFrequency)
         || (m_settings.m_log2Decim != settings.m_log2Decim)
         || (m_settings.m_fcPos != settings.m_fcPos) || force)
     {
         int sampleRate = settings.m_sampleRate/(1<<settings.m_log2Decim);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     if ((m_settings.m_modulationTone != settings.m_modulationTone) || force)
     {
         reverseAPIKeys.append("modulationTone");
         if (m_testSourceThread != 0) {
             m_testSourceThread->setToneFrequency(settings.m_modulationTone * 10);
         }
     }
     if ((m_settings.m_modulation != settings.m_modulation) || force)
     {
         reverseAPIKeys.append("modulation");
         if (m_testSourceThread != 0)
         {
             m_testSourceThread->setModulation(settings.m_modulation);
             if (settings.m_modulation == TestSourceSettings::ModulationPattern0) {
                 m_testSourceThread->setPattern0();
             } else if (settings.m_modulation == TestSourceSettings::ModulationPattern1) {
                 m_testSourceThread->setPattern1();
             } else if (settings.m_modulation == TestSourceSettings::ModulationPattern2) {
                 m_testSourceThread->setPattern2();
             }
         }
     }
     if ((m_settings.m_amModulation != settings.m_amModulation) || force)
     {
         reverseAPIKeys.append("amModulation");
         if (m_testSourceThread != 0) {
             m_testSourceThread->setAMModulation(settings.m_amModulation / 100.0f);
         }
     }
     if ((m_settings.m_fmDeviation != settings.m_fmDeviation) || force)
     {
         reverseAPIKeys.append("fmDeviation");
         if (m_testSourceThread != 0) {
             m_testSourceThread->setFMDeviation(settings.m_fmDeviation * 100.0f);
         }
     }
     if (settings.m_useReverseAPI)
     {
         qDebug("TestSourceInput::applySettings: call webapiReverseSendSettings");
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     return true;
 }
deserialize()
bool TestSourceInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 121 of file testsourceinput.cpp.
References TestSourceInput::MsgConfigureTestSource::create(), TestSourceSettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and TestSourceSettings::resetToDefaults().
Referenced by TestSourceInput::MsgStartStop::MsgStartStop().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureTestSource* message = MsgConfigureTestSource::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureTestSource* messageToGUI = MsgConfigureTestSource::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void TestSourceInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 74 of file testsourceinput.cpp.
Referenced by TestSourceInput::MsgStartStop::MsgStartStop().
 {
     delete this;
 }
getCenterFrequency()
quint64 TestSourceInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 153 of file testsourceinput.cpp.
References TestSourceSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & TestSourceInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 143 of file testsourceinput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getSampleRate()
int TestSourceInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 148 of file testsourceinput.cpp.
References TestSourceSettings::m_log2Decim, TestSourceSettings::m_sampleRate, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     return m_settings.m_sampleRate/(1<<m_settings.m_log2Decim);
 }
handleMessage()
bool TestSourceInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 173 of file testsourceinput.cpp.
References applySettings(), FileRecord::genUniqueFileName(), DeviceAPI::getDeviceUID(), TestSourceInput::MsgConfigureTestSource::getForce(), TestSourceInput::MsgConfigureTestSource::getSettings(), TestSourceInput::MsgFileRecord::getStartStop(), TestSourceInput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), m_deviceAPI, TestSourceSettings::m_fileRecordName, m_fileSink, m_settings, TestSourceSettings::m_useReverseAPI, Message::match(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (MsgConfigureTestSource::match(message))
     {
         MsgConfigureTestSource& conf = (MsgConfigureTestSource&) message;
         qDebug() << "TestSourceInput::handleMessage: MsgConfigureTestSource";
         bool success = applySettings(conf.getSettings(), conf.getForce());
         if (!success)
         {
             qDebug("TestSourceInput::handleMessage: config error");
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "TestSourceInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "TestSourceInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void TestSourceInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 79 of file testsourceinput.cpp.
References applySettings(), and m_settings.
Referenced by TestSourceInput::MsgStartStop::MsgStartStop().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void TestSourceInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 734 of file testsourceinput.cpp.
Referenced by ~TestSourceInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "TestSourceInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("TestSourceInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
serialize()
QByteArray TestSourceInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 116 of file testsourceinput.cpp.
References m_settings, and TestSourceSettings::serialize().
Referenced by TestSourceInput::MsgStartStop::MsgStartStop().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void TestSourceInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 158 of file testsourceinput.cpp.
References TestSourceInput::MsgConfigureTestSource::create(), TestSourceSettings::m_centerFrequency, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     TestSourceSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureTestSource* message = MsgConfigureTestSource::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureTestSource* messageToGUI = MsgConfigureTestSource::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setMessageQueueToGUI()
virtual void TestSourceInput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 110 of file testsourceinput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSource::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void TestSourceInput::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 113 of file testsourceinput.h.
References getCenterFrequency(), handleMessage(), setCenterFrequency(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
start()
bool TestSourceInput::start () virtual
Implements DeviceSampleSource.
Definition at line 84 of file testsourceinput.cpp.
References applySettings(), m_mutex, m_running, DeviceSampleSource::m_sampleFifo, TestSourceSettings::m_sampleRate, m_settings, m_testSourceThread, TestSourceThread::setSamplerate(), TestSourceThread::startStop(), and stop().
Referenced by TestSourceInput::MsgStartStop::MsgStartStop().
 {
     QMutexLocker mutexLocker(&m_mutex);
     if (m_running) stop();
     m_testSourceThread = new TestSourceThread(&m_sampleFifo);
     m_testSourceThread->setSamplerate(m_settings.m_sampleRate);
     m_testSourceThread->startStop(true);
     mutexLocker.unlock();
     applySettings(m_settings, true);
     m_running = true;
     return true;
 }
stop()
void TestSourceInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 102 of file testsourceinput.cpp.
References m_mutex, m_running, m_testSourceThread, and TestSourceThread::startStop().
Referenced by TestSourceInput::MsgStartStop::MsgStartStop(), start(), and ~TestSourceInput().
 {
     QMutexLocker mutexLocker(&m_mutex);
     if (m_testSourceThread != 0)
     {
         m_testSourceThread->startStop(false);
         m_testSourceThread->deleteLater();
         m_testSourceThread = 0;
     }
     m_running = false;
 }
webapiFormatDeviceSettings()
void TestSourceInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const TestSourceSettings & settings) private
Definition at line 586 of file testsourceinput.cpp.
References SWGSDRangel::SWGTestSourceSettings::getFileRecordName(), SWGSDRangel::SWGTestSourceSettings::getReverseApiAddress(), SWGSDRangel::SWGDeviceSettings::getTestSourceSettings(), TestSourceSettings::m_amModulation, TestSourceSettings::m_amplitudeBits, TestSourceSettings::m_autoCorrOptions, TestSourceSettings::m_centerFrequency, TestSourceSettings::m_dcFactor, TestSourceSettings::m_fcPos, TestSourceSettings::m_fileRecordName, TestSourceSettings::m_fmDeviation, TestSourceSettings::m_frequencyShift, TestSourceSettings::m_iFactor, TestSourceSettings::m_log2Decim, TestSourceSettings::m_modulation, TestSourceSettings::m_modulationTone, TestSourceSettings::m_phaseImbalance, TestSourceSettings::m_qFactor, TestSourceSettings::m_reverseAPIAddress, TestSourceSettings::m_reverseAPIDeviceIndex, TestSourceSettings::m_reverseAPIPort, TestSourceSettings::m_sampleRate, TestSourceSettings::m_sampleSizeIndex, TestSourceSettings::m_useReverseAPI, SWGSDRangel::SWGTestSourceSettings::setAmModulation(), SWGSDRangel::SWGTestSourceSettings::setAmplitudeBits(), SWGSDRangel::SWGTestSourceSettings::setAutoCorrOptions(), SWGSDRangel::SWGTestSourceSettings::setCenterFrequency(), SWGSDRangel::SWGTestSourceSettings::setDcFactor(), SWGSDRangel::SWGTestSourceSettings::setFcPos(), SWGSDRangel::SWGTestSourceSettings::setFileRecordName(), SWGSDRangel::SWGTestSourceSettings::setFmDeviation(), SWGSDRangel::SWGTestSourceSettings::setFrequencyShift(), SWGSDRangel::SWGTestSourceSettings::setIFactor(), SWGSDRangel::SWGTestSourceSettings::setLog2Decim(), SWGSDRangel::SWGTestSourceSettings::setModulation(), SWGSDRangel::SWGTestSourceSettings::setModulationTone(), SWGSDRangel::SWGTestSourceSettings::setPhaseImbalance(), SWGSDRangel::SWGTestSourceSettings::setQFactor(), SWGSDRangel::SWGTestSourceSettings::setReverseApiAddress(), SWGSDRangel::SWGTestSourceSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGTestSourceSettings::setReverseApiPort(), SWGSDRangel::SWGTestSourceSettings::setSampleRate(), SWGSDRangel::SWGTestSourceSettings::setSampleSizeIndex(), and SWGSDRangel::SWGTestSourceSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getTestSourceSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getTestSourceSettings()->setFrequencyShift(settings.m_frequencyShift);
     response.getTestSourceSettings()->setSampleRate(settings.m_sampleRate);
     response.getTestSourceSettings()->setLog2Decim(settings.m_log2Decim);
     response.getTestSourceSettings()->setFcPos((int) settings.m_fcPos);
     response.getTestSourceSettings()->setSampleSizeIndex((int) settings.m_sampleSizeIndex);
     response.getTestSourceSettings()->setAmplitudeBits(settings.m_amplitudeBits);
     response.getTestSourceSettings()->setAutoCorrOptions((int) settings.m_autoCorrOptions);
     response.getTestSourceSettings()->setModulation((int) settings.m_modulation);
     response.getTestSourceSettings()->setModulationTone(settings.m_modulationTone);
     response.getTestSourceSettings()->setAmModulation(settings.m_amModulation);
     response.getTestSourceSettings()->setFmDeviation(settings.m_fmDeviation);
     response.getTestSourceSettings()->setDcFactor(settings.m_dcFactor);
     response.getTestSourceSettings()->setIFactor(settings.m_iFactor);
     response.getTestSourceSettings()->setQFactor(settings.m_qFactor);
     response.getTestSourceSettings()->setPhaseImbalance(settings.m_phaseImbalance);
     if (response.getTestSourceSettings()->getFileRecordName()) {
         *response.getTestSourceSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getTestSourceSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getTestSourceSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getTestSourceSettings()->getReverseApiAddress()) {
         *response.getTestSourceSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getTestSourceSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getTestSourceSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getTestSourceSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReverseSendSettings()
void TestSourceInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const TestSourceSettings & settings, bool force) private
Definition at line 623 of file testsourceinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getTestSourceSettings(), TestSourceSettings::m_amModulation, TestSourceSettings::m_amplitudeBits, TestSourceSettings::m_centerFrequency, TestSourceSettings::m_dcFactor, m_deviceAPI, TestSourceSettings::m_fcPos, TestSourceSettings::m_fileRecordName, TestSourceSettings::m_fmDeviation, TestSourceSettings::m_frequencyShift, TestSourceSettings::m_iFactor, TestSourceSettings::m_log2Decim, TestSourceSettings::m_modulation, TestSourceSettings::m_modulationTone, m_networkManager, m_networkRequest, TestSourceSettings::m_phaseImbalance, TestSourceSettings::m_qFactor, TestSourceSettings::m_reverseAPIAddress, TestSourceSettings::m_reverseAPIDeviceIndex, TestSourceSettings::m_reverseAPIPort, TestSourceSettings::m_sampleRate, TestSourceSettings::m_sampleSizeIndex, SWGSDRangel::SWGTestSourceSettings::setAmModulation(), SWGSDRangel::SWGTestSourceSettings::setAmplitudeBits(), SWGSDRangel::SWGTestSourceSettings::setAutoCorrOptions(), SWGSDRangel::SWGTestSourceSettings::setCenterFrequency(), SWGSDRangel::SWGTestSourceSettings::setDcFactor(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGTestSourceSettings::setFcPos(), SWGSDRangel::SWGTestSourceSettings::setFileRecordName(), SWGSDRangel::SWGTestSourceSettings::setFmDeviation(), SWGSDRangel::SWGTestSourceSettings::setFrequencyShift(), SWGSDRangel::SWGTestSourceSettings::setIFactor(), SWGSDRangel::SWGTestSourceSettings::setLog2Decim(), SWGSDRangel::SWGTestSourceSettings::setModulation(), SWGSDRangel::SWGTestSourceSettings::setModulationTone(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGTestSourceSettings::setPhaseImbalance(), SWGSDRangel::SWGTestSourceSettings::setQFactor(), SWGSDRangel::SWGTestSourceSettings::setSampleRate(), SWGSDRangel::SWGTestSourceSettings::setSampleSizeIndex(), and SWGSDRangel::SWGDeviceSettings::setTestSourceSettings().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("TestSource"));
     swgDeviceSettings->setTestSourceSettings(new SWGSDRangel::SWGTestSourceSettings());
     SWGSDRangel::SWGTestSourceSettings *swgTestSourceSettings = swgDeviceSettings->getTestSourceSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgTestSourceSettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("frequencyShift") || force) {
         swgTestSourceSettings->setFrequencyShift(settings.m_frequencyShift);
     }
     if (deviceSettingsKeys.contains("sampleRate") || force) {
         swgTestSourceSettings->setSampleRate(settings.m_sampleRate);
     }
     if (deviceSettingsKeys.contains("log2Decim") || force) {
         swgTestSourceSettings->setLog2Decim(settings.m_log2Decim);
     }
     if (deviceSettingsKeys.contains("fcPos") || force) {
         swgTestSourceSettings->setFcPos((int) settings.m_fcPos);
     }
     if (deviceSettingsKeys.contains("sampleSizeIndex") || force) {
         swgTestSourceSettings->setSampleSizeIndex(settings.m_sampleSizeIndex);
     }
     if (deviceSettingsKeys.contains("amplitudeBits") || force) {
         swgTestSourceSettings->setAmplitudeBits(settings.m_amplitudeBits);
     }
     if (deviceSettingsKeys.contains("autoCorrOptions") || force) {
         swgTestSourceSettings->setAutoCorrOptions((int) settings.m_sampleSizeIndex);
     }
     if (deviceSettingsKeys.contains("modulation") || force) {
         swgTestSourceSettings->setModulation((int) settings.m_modulation);
     }
     if (deviceSettingsKeys.contains("modulationTone")) {
         swgTestSourceSettings->setModulationTone(settings.m_modulationTone);
     }
     if (deviceSettingsKeys.contains("amModulation") || force) {
         swgTestSourceSettings->setAmModulation(settings.m_amModulation);
     };
     if (deviceSettingsKeys.contains("fmDeviation") || force) {
         swgTestSourceSettings->setFmDeviation(settings.m_fmDeviation);
     };
     if (deviceSettingsKeys.contains("dcFactor") || force) {
         swgTestSourceSettings->setDcFactor(settings.m_dcFactor);
     };
     if (deviceSettingsKeys.contains("iFactor") || force) {
         swgTestSourceSettings->setIFactor(settings.m_iFactor);
     };
     if (deviceSettingsKeys.contains("qFactor") || force) {
         swgTestSourceSettings->setQFactor(settings.m_qFactor);
     };
     if (deviceSettingsKeys.contains("phaseImbalance") || force) {
         swgTestSourceSettings->setPhaseImbalance(settings.m_phaseImbalance);
     };
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgTestSourceSettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
 //    qDebug("TestSourceInput::webapiReverseSendSettings: %s", channelSettingsURL.toStdString().c_str());
 //    qDebug("TestSourceInput::webapiReverseSendSettings: query:\n%s", swgDeviceSettings->asJson().toStdString().c_str());
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void TestSourceInput::webapiReverseSendStartStop (bool start) private
Definition at line 706 of file testsourceinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, TestSourceSettings::m_reverseAPIAddress, TestSourceSettings::m_reverseAPIDeviceIndex, TestSourceSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("TestSource"));
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int TestSourceInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 462 of file testsourceinput.cpp.
References TestSourceInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int TestSourceInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 453 of file testsourceinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int TestSourceInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 481 of file testsourceinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getTestSourceSettings(), SWGSDRangel::SWGTestSourceSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setTestSourceSettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setTestSourceSettings(new SWGSDRangel::SWGTestSourceSettings());
     response.getTestSourceSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int TestSourceInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 492 of file testsourceinput.cpp.
References TestSourceSettings::AutoCorrLast, TestSourceInput::MsgConfigureTestSource::create(), SWGSDRangel::SWGTestSourceSettings::getAmModulation(), SWGSDRangel::SWGTestSourceSettings::getAmplitudeBits(), SWGSDRangel::SWGTestSourceSettings::getAutoCorrOptions(), SWGSDRangel::SWGTestSourceSettings::getCenterFrequency(), SWGSDRangel::SWGTestSourceSettings::getDcFactor(), SWGSDRangel::SWGTestSourceSettings::getFcPos(), SWGSDRangel::SWGTestSourceSettings::getFileRecordName(), SWGSDRangel::SWGTestSourceSettings::getFmDeviation(), SWGSDRangel::SWGTestSourceSettings::getFrequencyShift(), SWGSDRangel::SWGTestSourceSettings::getIFactor(), SWGSDRangel::SWGTestSourceSettings::getLog2Decim(), SWGSDRangel::SWGTestSourceSettings::getModulation(), SWGSDRangel::SWGTestSourceSettings::getModulationTone(), SWGSDRangel::SWGTestSourceSettings::getPhaseImbalance(), SWGSDRangel::SWGTestSourceSettings::getQFactor(), SWGSDRangel::SWGTestSourceSettings::getReverseApiAddress(), SWGSDRangel::SWGTestSourceSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGTestSourceSettings::getReverseApiPort(), SWGSDRangel::SWGTestSourceSettings::getSampleRate(), SWGSDRangel::SWGTestSourceSettings::getSampleSizeIndex(), SWGSDRangel::SWGDeviceSettings::getTestSourceSettings(), SWGSDRangel::SWGTestSourceSettings::getUseReverseApi(), TestSourceSettings::m_amModulation, TestSourceSettings::m_amplitudeBits, TestSourceSettings::m_centerFrequency, TestSourceSettings::m_dcFactor, TestSourceSettings::m_fcPos, TestSourceSettings::m_fileRecordName, TestSourceSettings::m_fmDeviation, TestSourceSettings::m_frequencyShift, DeviceSampleSource::m_guiMessageQueue, TestSourceSettings::m_iFactor, DeviceSampleSource::m_inputMessageQueue, TestSourceSettings::m_log2Decim, TestSourceSettings::m_modulation, TestSourceSettings::m_modulationTone, TestSourceSettings::m_phaseImbalance, TestSourceSettings::m_qFactor, TestSourceSettings::m_reverseAPIAddress, TestSourceSettings::m_reverseAPIDeviceIndex, TestSourceSettings::m_reverseAPIPort, TestSourceSettings::m_sampleRate, TestSourceSettings::m_sampleSizeIndex, m_settings, TestSourceSettings::m_useReverseAPI, TestSourceSettings::ModulationLast, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     TestSourceSettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getTestSourceSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("frequencyShift")) {
         settings.m_frequencyShift = response.getTestSourceSettings()->getFrequencyShift();
     }
     if (deviceSettingsKeys.contains("sampleRate")) {
         settings.m_sampleRate = response.getTestSourceSettings()->getSampleRate();
     }
     if (deviceSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getTestSourceSettings()->getLog2Decim();
     }
     if (deviceSettingsKeys.contains("fcPos")) {
         int fcPos = response.getTestSourceSettings()->getFcPos();
         fcPos = fcPos < 0 ? 0 : fcPos > 2 ? 2 : fcPos;
         settings.m_fcPos = (TestSourceSettings::fcPos_t) fcPos;
     }
     if (deviceSettingsKeys.contains("sampleSizeIndex")) {
         int sampleSizeIndex = response.getTestSourceSettings()->getSampleSizeIndex();
         sampleSizeIndex = sampleSizeIndex < 0 ? 0 : sampleSizeIndex > 1 ? 2 : sampleSizeIndex;
         settings.m_sampleSizeIndex = sampleSizeIndex;
     }
     if (deviceSettingsKeys.contains("amplitudeBits")) {
         settings.m_amplitudeBits = response.getTestSourceSettings()->getAmplitudeBits();
     }
     if (deviceSettingsKeys.contains("autoCorrOptions")) {
         int autoCorrOptions = response.getTestSourceSettings()->getAutoCorrOptions();
         autoCorrOptions = autoCorrOptions < 0 ? 0 : autoCorrOptions >= TestSourceSettings::AutoCorrLast ? TestSourceSettings::AutoCorrLast-1 : autoCorrOptions;
         settings.m_sampleSizeIndex = (TestSourceSettings::AutoCorrOptions) autoCorrOptions;
     }
     if (deviceSettingsKeys.contains("modulation")) {
         int modulation = response.getTestSourceSettings()->getModulation();
         modulation = modulation < 0 ? 0 : modulation >= TestSourceSettings::ModulationLast ? TestSourceSettings::ModulationLast-1 : modulation;
         settings.m_modulation = (TestSourceSettings::Modulation) modulation;
     }
     if (deviceSettingsKeys.contains("modulationTone")) {
         settings.m_modulationTone = response.getTestSourceSettings()->getModulationTone();
     }
     if (deviceSettingsKeys.contains("amModulation")) {
         settings.m_amModulation = response.getTestSourceSettings()->getAmModulation();
     };
     if (deviceSettingsKeys.contains("fmDeviation")) {
         settings.m_fmDeviation = response.getTestSourceSettings()->getFmDeviation();
     };
     if (deviceSettingsKeys.contains("dcFactor")) {
         settings.m_dcFactor = response.getTestSourceSettings()->getDcFactor();
     };
     if (deviceSettingsKeys.contains("iFactor")) {
         settings.m_iFactor = response.getTestSourceSettings()->getIFactor();
     };
     if (deviceSettingsKeys.contains("qFactor")) {
         settings.m_qFactor = response.getTestSourceSettings()->getQFactor();
     };
     if (deviceSettingsKeys.contains("phaseImbalance")) {
         settings.m_phaseImbalance = response.getTestSourceSettings()->getPhaseImbalance();
     };
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getTestSourceSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getTestSourceSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getTestSourceSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getTestSourceSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getTestSourceSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureTestSource *msg = MsgConfigureTestSource::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureTestSource *msgToGUI = MsgConfigureTestSource::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_deviceAPI
DeviceAPI* TestSourceInput::m_deviceAPI private
Definition at line 139 of file testsourceinput.h.
Referenced by applySettings(), handleMessage(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~TestSourceInput().
m_deviceDescription
QString TestSourceInput::m_deviceDescription private
Definition at line 144 of file testsourceinput.h.
Referenced by getDeviceDescription().
m_fileSink
FileRecord* TestSourceInput::m_fileSink private
File sink to record device I/Q output.
Definition at line 140 of file testsourceinput.h.
Referenced by applySettings(), handleMessage(), and ~TestSourceInput().
m_masterTimer
const QTimer& TestSourceInput::m_masterTimer private
Definition at line 146 of file testsourceinput.h.
m_mutex
QMutex TestSourceInput::m_mutex private
Definition at line 141 of file testsourceinput.h.
Referenced by start(), and stop().
m_networkManager
QNetworkAccessManager* TestSourceInput::m_networkManager private
Definition at line 147 of file testsourceinput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~TestSourceInput().
m_networkRequest
QNetworkRequest TestSourceInput::m_networkRequest private
Definition at line 148 of file testsourceinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool TestSourceInput::m_running private
Definition at line 145 of file testsourceinput.h.
Referenced by start(), stop(), and ~TestSourceInput().
m_settings
TestSourceSettings TestSourceInput::m_settings private
Definition at line 142 of file testsourceinput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), serialize(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_testSourceThread
TestSourceThread* TestSourceInput::m_testSourceThread private
Definition at line 143 of file testsourceinput.h.
Referenced by applySettings(), start(), and stop().
The documentation for this class was generated from the following files:
plugins/samplesource/testsource/testsourceinput.h
plugins/samplesource/testsource/testsourceinput.cpp