SDRAngel: WFMDemod Class Reference
WFMDemod Class Reference
#include <wfmdemod.h>
Classes
struct MagSqLevelsStore
class MsgConfigureChannelizer
class MsgConfigureWFMDemod
Public Member Functions
WFMDemod (DeviceAPI *deviceAPI)
virtual ~WFMDemod ()
virtual void destroy ()
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool po)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
double getMagSq () const
bool getSquelchOpen () const
void getMagSqLevels (double &avg, double &peak, int &nbSamples)
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Member Functions
static int requiredBW (int rfBW)
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.wfmdemod"
static const QString m_channelId = "WFMDemod"
Private Types
enum RateState { RSInitialFill, RSRunning }
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applyAudioSampleRate (int sampleRate)
void applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const WFMDemodSettings &settings, bool force=false)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const WFMDemodSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const WFMDemodSettings &settings, bool force)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
int m_inputSampleRate
int m_inputFrequencyOffset
WFMDemodSettings m_settings
quint32 m_audioSampleRate
NCO m_nco
Interpolator m_interpolator
Interpolator between sample rate sent from DSP engine and requested RF bandwidth (rational)
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
fftfilt * m_rfFilter
Real m_squelchLevel
int m_squelchState
bool m_squelchOpen
double m_magsq
displayed averaged value
double m_magsqSum
double m_magsqPeak
int m_magsqCount
MagSqLevelsStore m_magSqLevelStore
MovingAverageUtil< Real, double, 16 > m_movingAverage
Real m_fmExcursion
AudioVector m_audioBuffer
uint m_audioBufferFill
AudioFifo m_audioFifo
SampleVector m_sampleBuffer
QMutex m_settingsMutex
PhaseDiscriminators m_phaseDiscri
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Static Private Attributes
static const int m_udpBlockSize = 512
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 48 of file wfmdemod.h.
Member Enumeration Documentation
RateState
enum WFMDemod::RateState private
Enumerator
RSInitialFill
RSRunning
Definition at line 181 of file wfmdemod.h.
                    {
         RSInitialFill,
         RSRunning
     };
Constructor & Destructor Documentation
WFMDemod()
WFMDemod::WFMDemod (DeviceAPI * deviceAPI)
Definition at line 51 of file wfmdemod.cpp.
References AudioDeviceManager::addAudioSink(), DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), applyChannelSettings(), applySettings(), DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_channelId, m_channelizer, m_deviceAPI, m_inputFrequencyOffset, m_inputSampleRate, m_networkManager, m_phaseDiscri, m_rfFilter, m_settings, m_threadedChannelizer, networkManagerFinished(), rfFilterFftLength, and PhaseDiscriminators::setFMScaling().
Referenced by WFMDemod::MsgConfigureChannelizer::MsgConfigureChannelizer().
                                        :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(deviceAPI),
         m_inputSampleRate(384000),
         m_inputFrequencyOffset(0),
         m_squelchOpen(false),
         m_magsq(0.0f),
         m_magsqSum(0.0f),
         m_magsqPeak(0.0f),
         m_magsqCount(0),
         m_audioFifo(250000),
         m_settingsMutex(QMutex::Recursive)
 {
     setObjectName(m_channelId);
     m_rfFilter = new fftfilt(-50000.0 / 384000.0, 50000.0 / 384000.0, rfFilterFftLength);
     m_phaseDiscri.setFMScaling(384000/75000);
     m_audioBuffer.resize(16384);
     m_audioBufferFill = 0;
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSink(&m_audioFifo, getInputMessageQueue());
     m_audioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getOutputSampleRate();
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~WFMDemod()
WFMDemod::~WFMDemod () virtual
Definition at line 87 of file wfmdemod.cpp.
References DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo, m_channelizer, m_deviceAPI, m_networkManager, m_rfFilter, m_threadedChannelizer, networkManagerFinished(), AudioDeviceManager::removeAudioSink(), DeviceAPI::removeChannelSink(), and DeviceAPI::removeChannelSinkAPI().
Referenced by WFMDemod::MsgConfigureChannelizer::MsgConfigureChannelizer().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_audioFifo);
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete m_rfFilter;
 }
Member Function Documentation
applyAudioSampleRate()
void WFMDemod::applyAudioSampleRate (int sampleRate) private
Definition at line 273 of file wfmdemod.cpp.
References Interpolator::create(), WFMDemodSettings::m_afBandwidth, m_audioSampleRate, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_settings, and m_settingsMutex.
Referenced by applySettings(), and handleMessage().
 {
     qDebug("WFMDemod::applyAudioSampleRate: %d", sampleRate);
     m_settingsMutex.lock();
     m_interpolator.create(16, m_inputSampleRate, m_settings.m_afBandwidth);
     m_interpolatorDistanceRemain = (Real) m_inputSampleRate / sampleRate;
     m_interpolatorDistance =  (Real) m_inputSampleRate / (Real) sampleRate;
     m_settingsMutex.unlock();
     m_audioSampleRate = sampleRate;
 }
applyChannelSettings()
void WFMDemod::applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 288 of file wfmdemod.cpp.
References Interpolator::create(), fftfilt::create_filter(), WFMDemodSettings::m_afBandwidth, m_audioSampleRate, m_fmExcursion, m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_nco, m_phaseDiscri, WFMDemodSettings::m_rfBandwidth, m_rfFilter, m_settings, m_settingsMutex, PhaseDiscriminators::setFMScaling(), and NCO::setFreq().
Referenced by handleMessage(), start(), and WFMDemod().
 {
     qDebug() << "WFMDemod::applyChannelSettings:"
             << " inputSampleRate: " << inputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if((inputFrequencyOffset != m_inputFrequencyOffset) ||
         (inputSampleRate != m_inputSampleRate) || force)
     {
         m_nco.setFreq(-inputFrequencyOffset, inputSampleRate);
     }
     if ((inputSampleRate != m_inputSampleRate) || force)
     {
         qDebug() << "WFMDemod::applyChannelSettings: m_interpolator.create";
         m_settingsMutex.lock();
         m_interpolator.create(16, inputSampleRate, m_settings.m_afBandwidth);
         m_interpolatorDistanceRemain = (Real) inputSampleRate / (Real) m_audioSampleRate;
         m_interpolatorDistance =  (Real) inputSampleRate / (Real) m_audioSampleRate;
         m_settingsMutex.unlock();
         qDebug() << "WFMDemod::applySettings: m_rfFilter->create_filter";
         Real lowCut = -(m_settings.m_rfBandwidth / 2.0) / inputSampleRate;
         Real hiCut  = (m_settings.m_rfBandwidth / 2.0) / inputSampleRate;
         m_rfFilter->create_filter(lowCut, hiCut);
         m_fmExcursion = m_settings.m_rfBandwidth / (Real) inputSampleRate;
         m_phaseDiscri.setFMScaling(1.0f/m_fmExcursion);
         qDebug("WFMDemod::applySettings: m_fmExcursion: %f", m_fmExcursion);
     }
     m_inputSampleRate = inputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applySettings()
void WFMDemod::applySettings (const WFMDemodSettings & settings, bool force = false) private
Definition at line 321 of file wfmdemod.cpp.
References AudioDeviceManager::addAudioSink(), applyAudioSampleRate(), Interpolator::create(), fftfilt::create_filter(), DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputDeviceIndex(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), WFMDemodSettings::m_afBandwidth, WFMDemodSettings::m_audioDeviceName, m_audioFifo, WFMDemodSettings::m_audioMute, m_audioSampleRate, m_fmExcursion, WFMDemodSettings::m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_phaseDiscri, WFMDemodSettings::m_reverseAPIAddress, WFMDemodSettings::m_reverseAPIChannelIndex, WFMDemodSettings::m_reverseAPIDeviceIndex, WFMDemodSettings::m_reverseAPIPort, WFMDemodSettings::m_rfBandwidth, m_rfFilter, WFMDemodSettings::m_rgbColor, m_settings, m_settingsMutex, WFMDemodSettings::m_squelch, m_squelchLevel, WFMDemodSettings::m_title, WFMDemodSettings::m_useReverseAPI, WFMDemodSettings::m_volume, PhaseDiscriminators::setFMScaling(), and webapiReverseSendSettings().
Referenced by handleMessage(), and WFMDemod().
 {
     qDebug() << "WFMDemod::applySettings:"
             << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
             << " m_rfBandwidth: " << settings.m_rfBandwidth
             << " m_afBandwidth: " << settings.m_afBandwidth
             << " m_volume: " << settings.m_volume
             << " m_squelch: " << settings.m_squelch
             << " m_audioDeviceName: " << settings.m_audioDeviceName
             << " m_audioMute: " << settings.m_audioMute
             << " m_useReverseAPI: " << settings.m_useReverseAPI
             << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
             << " m_reverseAPIPort: " << settings.m_reverseAPIPort
             << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex
             << " m_reverseAPIChannelIndex: " << settings.m_reverseAPIChannelIndex
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if((settings.m_inputFrequencyOffset != m_settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if((settings.m_rfBandwidth != m_settings.m_rfBandwidth) || force) {
         reverseAPIKeys.append("rfBandwidth");
     }
     if((settings.m_afBandwidth != m_settings.m_afBandwidth) || force) {
         reverseAPIKeys.append("afBandwidth");
     }
     if((settings.m_volume != m_settings.m_volume) || force) {
         reverseAPIKeys.append("volume");
     }
     if((settings.m_squelch != m_settings.m_squelch) || force) {
         reverseAPIKeys.append("squelch");
     }
     if((settings.m_audioMute != m_settings.m_audioMute) || force) {
         reverseAPIKeys.append("audioMute");
     }
     if((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force) {
         reverseAPIKeys.append("audioDeviceName");
     }
     if((settings.m_title != m_settings.m_title) || force) {
         reverseAPIKeys.append("title");
     }
     if((settings.m_rgbColor != m_settings.m_rgbColor) || force) {
         reverseAPIKeys.append("rgbColor");
     }
     if((settings.m_afBandwidth != m_settings.m_afBandwidth) ||
        (settings.m_rfBandwidth != m_settings.m_rfBandwidth) || force)
     {
         m_settingsMutex.lock();
         qDebug() << "WFMDemod::applySettings: m_interpolator.create";
         m_interpolator.create(16, m_inputSampleRate, settings.m_afBandwidth);
         m_interpolatorDistanceRemain = (Real) m_inputSampleRate / (Real) m_audioSampleRate;
         m_interpolatorDistance =  (Real) m_inputSampleRate / (Real) m_audioSampleRate;
         qDebug() << "WFMDemod::applySettings: m_rfFilter->create_filter";
         Real lowCut = -(settings.m_rfBandwidth / 2.0) / m_inputSampleRate;
         Real hiCut  = (settings.m_rfBandwidth / 2.0) / m_inputSampleRate;
         m_rfFilter->create_filter(lowCut, hiCut);
         m_fmExcursion = settings.m_rfBandwidth / (Real) m_inputSampleRate;
         m_phaseDiscri.setFMScaling(1.0f/m_fmExcursion);
         qDebug("WFMDemod::applySettings: m_fmExcursion: %f", m_fmExcursion);
         m_settingsMutex.unlock();
     }
     if ((settings.m_squelch != m_settings.m_squelch) || force)
     {
         qDebug() << "WFMDemod::applySettings: set m_squelchLevel";
         m_squelchLevel = pow(10.0, settings.m_squelch / 10.0);
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force)
     {
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getOutputDeviceIndex(settings.m_audioDeviceName);
         //qDebug("AMDemod::applySettings: audioDeviceName: %s audioDeviceIndex: %d", qPrintable(settings.m_audioDeviceName), audioDeviceIndex);
         audioDeviceManager->addAudioSink(&m_audioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getOutputSampleRate(audioDeviceIndex);
         if (m_audioSampleRate != audioSampleRate) {
             applyAudioSampleRate(audioSampleRate);
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
deserialize()
bool WFMDemod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 423 of file wfmdemod.cpp.
References WFMDemod::MsgConfigureWFMDemod::create(), WFMDemodSettings::deserialize(), BasebandSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and WFMDemodSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureWFMDemod *msg = MsgConfigureWFMDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureWFMDemod *msg = MsgConfigureWFMDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void WFMDemod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 99 of file wfmdemod.h.
References feed(), handleMessage(), start(), and stop().
 { delete this; }
feed()
void WFMDemod::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool po) virtual
Implements BasebandSampleSink.
Definition at line 100 of file wfmdemod.cpp.
References Interpolator::decimate(), i, m_audioBuffer, m_audioBufferFill, m_audioFifo, WFMDemodSettings::m_audioMute, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_magsqCount, m_magsqPeak, m_magsqSum, m_movingAverage, m_nco, m_phaseDiscri, WFMDemodSettings::m_rfBandwidth, m_rfFilter, m_sampleBuffer, m_settings, m_settingsMutex, m_squelchLevel, m_squelchOpen, m_squelchState, WFMDemodSettings::m_volume, NCO::nextIQ(), PhaseDiscriminators::phaseDiscriminatorDelta(), fftfilt::runFilt(), SDR_RX_SCALED, and AudioFifo::write().
Referenced by destroy().
 {
     (void) firstOfBurst;
     Complex ci;
     fftfilt::cmplx *rf;
     int rf_out;
     Real demod;
     double msq;
     float fmDev;
     m_settingsMutex.lock();
     for (SampleVector::const_iterator it = begin; it != end; ++it)
     {
         Complex c(it->real(), it->imag());
         c *= m_nco.nextIQ();
         rf_out = m_rfFilter->runFilt(c, &rf); // filter RF before demod
         for (int i = 0 ; i < rf_out; i++)
         {
             msq = rf[i].real()*rf[i].real() + rf[i].imag()*rf[i].imag();
             Real magsq = msq / (SDR_RX_SCALED*SDR_RX_SCALED);
             m_magsqSum += magsq;
             m_movingAverage(magsq);
             if (magsq > m_magsqPeak) {
                 m_magsqPeak = magsq;
             }
             m_magsqCount++;
             if (magsq >= m_squelchLevel)
             {
                 if (m_squelchState < m_settings.m_rfBandwidth / 10) { // twice attack and decay rate
                     m_squelchState++;
                 }
             }
             else
             {
                 if (m_squelchState > 0) {
                     m_squelchState--;
                 }
             }
             m_squelchOpen = (m_squelchState > (m_settings.m_rfBandwidth / 20));
             if (m_squelchOpen && !m_settings.m_audioMute) { // squelch open and not mute
                 demod = m_phaseDiscri.phaseDiscriminatorDelta(rf[i], msq, fmDev);
             } else {
                 demod = 0;
             }
             Complex e(demod, 0);
             if (m_interpolator.decimate(&m_interpolatorDistanceRemain, e, &ci))
             {
                 qint16 sample = (qint16)(ci.real() * 3276.8f * m_settings.m_volume);
                 m_sampleBuffer.push_back(Sample(sample, sample));
                 m_audioBuffer[m_audioBufferFill].l = sample;
                 m_audioBuffer[m_audioBufferFill].r = sample;
                 ++m_audioBufferFill;
                 if(m_audioBufferFill >= m_audioBuffer.size())
                 {
                     uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
                     if (res != m_audioBufferFill) {
                         qDebug("WFMDemod::feed: %u/%u audio samples written", res, m_audioBufferFill);
                     }
                     m_audioBufferFill = 0;
                 }
                 m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
         }
     }
     if (m_audioBufferFill > 0)
     {
         uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
         if (res != m_audioBufferFill) {
             qDebug("WFMDemod::feed: %u/%u tail samples written", res, m_audioBufferFill);
         }
         m_audioBufferFill = 0;
     }
     m_sampleBuffer.clear();
     m_settingsMutex.unlock();
 }
getCenterFrequency()
virtual qint64 WFMDemod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 108 of file wfmdemod.h.
References deserialize(), WFMDemodSettings::m_inputFrequencyOffset, WFMDemod::MsgConfigureWFMDemod::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getIdentifier()
virtual void WFMDemod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 106 of file wfmdemod.h.
 { id = objectName(); }
getMagSq()
double WFMDemod::getMagSq () const inline
Definition at line 123 of file wfmdemod.h.
References MovingAverageUtil< T, Total, N >::asDouble(), and m_movingAverage.
 { return m_movingAverage.asDouble(); }
getMagSqLevels()
void WFMDemod::getMagSqLevels (double & avg, double & peak, int & nbSamples) inline
Definition at line 126 of file wfmdemod.h.
References WFMDemod::MagSqLevelsStore::m_magsq, m_magsq, m_magsqCount, m_magSqLevelStore, WFMDemod::MagSqLevelsStore::m_magsqPeak, m_magsqPeak, m_magsqSum, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
Referenced by WFMDemodGUI::tick(), and webapiFormatChannelReport().
     {
         if (m_magsqCount > 0)
         {
             m_magsq = m_magsqSum / m_magsqCount;
             m_magSqLevelStore.m_magsq = m_magsq;
             m_magSqLevelStore.m_magsqPeak = m_magsqPeak;
         }
         avg = m_magSqLevelStore.m_magsq;
         peak = m_magSqLevelStore.m_magsqPeak;
         nbSamples = m_magsqCount == 0 ? 1 : m_magsqCount;
         m_magsqSum = 0.0f;
         m_magsqPeak = 0.0f;
         m_magsqCount = 0;
     }
getNbSinkStreams()
virtual int WFMDemod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 113 of file wfmdemod.h.
 { return 1; }
getNbSourceStreams()
virtual int WFMDemod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 114 of file wfmdemod.h.
 { return 0; }
getSquelchOpen()
bool WFMDemod::getSquelchOpen () const inline
Definition at line 124 of file wfmdemod.h.
References m_squelchOpen.
Referenced by WFMDemodGUI::tick().
 { return m_squelchOpen; }
getStreamCenterFrequency()
virtual qint64 WFMDemod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 116 of file wfmdemod.h.
References WFMDemodSettings::m_inputFrequencyOffset, and WFMDemod::MsgConfigureWFMDemod::m_settings.
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void WFMDemod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 107 of file wfmdemod.h.
References WFMDemod::MsgConfigureWFMDemod::m_settings, and WFMDemodSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool WFMDemod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 208 of file wfmdemod.cpp.
References applyAudioSampleRate(), applyChannelSettings(), applySettings(), DownChannelizer::configure(), WFMDemod::MsgConfigureChannelizer::getCenterFrequency(), WFMDemod::MsgConfigureWFMDemod::getForce(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSink::getInputMessageQueue(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), WFMDemod::MsgConfigureChannelizer::getSampleRate(), DSPConfigureAudio::getSampleRate(), WFMDemod::MsgConfigureWFMDemod::getSettings(), BasebandSampleSink::MsgThreadedSink::getThread(), m_audioSampleRate, m_channelizer, and Message::match().
Referenced by destroy().
 {
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& notif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "WFMDemod::handleMessage: MsgChannelizerNotification: m_inputSampleRate: " << notif.getSampleRate()
                 << " m_inputFrequencyOffset: " << notif.getFrequencyOffset();
         applyChannelSettings(notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "WFMDemod::handleMessage: MsgConfigureChannelizer:"
                 << " sampleRate: " << cfg.getSampleRate()
                 << " inputFrequencyOffset: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureWFMDemod::match(cmd))
     {
         MsgConfigureWFMDemod& cfg = (MsgConfigureWFMDemod&) cmd;
         qDebug("WFMDemod::handleMessage: MsgConfigureWFMDemod");
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (BasebandSampleSink::MsgThreadedSink::match(cmd))
     {
         BasebandSampleSink::MsgThreadedSink& cfg = (BasebandSampleSink::MsgThreadedSink&) cmd;
         const QThread *thread = cfg.getThread();
         qDebug("WFMDemod::handleMessage: BasebandSampleSink::MsgThreadedSink: %p", thread);
         return true;
     }
     else if (DSPConfigureAudio::match(cmd))
     {
         DSPConfigureAudio& cfg = (DSPConfigureAudio&) cmd;
         uint32_t sampleRate = cfg.getSampleRate();
         qDebug() << "WFMDemod::handleMessage: DSPConfigureAudio:"
                 << " sampleRate: " << sampleRate;
         if (sampleRate != m_audioSampleRate) {
             applyAudioSampleRate(sampleRate);
         }
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         return false;
     }
 }
networkManagerFinished
void WFMDemod::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 645 of file wfmdemod.cpp.
Referenced by WFMDemod(), and ~WFMDemod().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "WFMDemod::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("WFMDemod::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
requiredBW()
static int WFMDemod::requiredBW (int rfBW) inline static
Definition at line 158 of file wfmdemod.h.
Referenced by WFMDemodGUI::applySettings(), and webapiSettingsPutPatch().
     {
         if (rfBW <= 48000) {
             return 48000;
         } else {
             return (3*rfBW)/2;
         }
     }
serialize()
QByteArray WFMDemod::serialize () const virtual
Implements ChannelAPI.
Definition at line 418 of file wfmdemod.cpp.
References m_settings, and WFMDemodSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
start()
void WFMDemod::start () virtual
Implements BasebandSampleSink.
Definition at line 196 of file wfmdemod.cpp.
References applyChannelSettings(), AudioFifo::clear(), m_audioFifo, m_inputFrequencyOffset, m_inputSampleRate, m_phaseDiscri, m_squelchState, and PhaseDiscriminators::reset().
Referenced by destroy().
 {
     m_squelchState = 0;
     m_audioFifo.clear();
     m_phaseDiscri.reset();
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void WFMDemod::stop () virtual
Implements BasebandSampleSink.
Definition at line 204 of file wfmdemod.cpp.
Referenced by destroy().
 {
 }
webapiFormatChannelReport()
void WFMDemod::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 574 of file wfmdemod.cpp.
References CalcDb::dbPower(), getMagSqLevels(), SWGSDRangel::SWGChannelReport::getWfmDemodReport(), m_audioSampleRate, m_inputSampleRate, m_squelchState, SWGSDRangel::SWGWFMDemodReport::setAudioSampleRate(), SWGSDRangel::SWGWFMDemodReport::setChannelPowerDb(), SWGSDRangel::SWGWFMDemodReport::setChannelSampleRate(), and SWGSDRangel::SWGWFMDemodReport::setSquelch().
Referenced by webapiReportGet().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     response.getWfmDemodReport()->setChannelPowerDb(CalcDb::dbPower(magsqAvg));
     response.getWfmDemodReport()->setSquelch(m_squelchState > 0 ? 1 : 0);
     response.getWfmDemodReport()->setAudioSampleRate(m_audioSampleRate);
     response.getWfmDemodReport()->setChannelSampleRate(m_inputSampleRate);
 }
webapiFormatChannelSettings()
void WFMDemod::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const WFMDemodSettings & settings) private
Definition at line 539 of file wfmdemod.cpp.
References SWGSDRangel::SWGWFMDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGWFMDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGWFMDemodSettings::getTitle(), SWGSDRangel::SWGChannelSettings::getWfmDemodSettings(), WFMDemodSettings::m_afBandwidth, WFMDemodSettings::m_audioDeviceName, WFMDemodSettings::m_audioMute, WFMDemodSettings::m_inputFrequencyOffset, WFMDemodSettings::m_reverseAPIAddress, WFMDemodSettings::m_reverseAPIChannelIndex, WFMDemodSettings::m_reverseAPIDeviceIndex, WFMDemodSettings::m_reverseAPIPort, WFMDemodSettings::m_rfBandwidth, WFMDemodSettings::m_rgbColor, WFMDemodSettings::m_squelch, WFMDemodSettings::m_title, WFMDemodSettings::m_useReverseAPI, WFMDemodSettings::m_volume, SWGSDRangel::SWGWFMDemodSettings::setAfBandwidth(), SWGSDRangel::SWGWFMDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGWFMDemodSettings::setAudioMute(), SWGSDRangel::SWGWFMDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGWFMDemodSettings::setReverseApiAddress(), SWGSDRangel::SWGWFMDemodSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGWFMDemodSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGWFMDemodSettings::setReverseApiPort(), SWGSDRangel::SWGWFMDemodSettings::setRfBandwidth(), SWGSDRangel::SWGWFMDemodSettings::setRgbColor(), SWGSDRangel::SWGWFMDemodSettings::setSquelch(), SWGSDRangel::SWGWFMDemodSettings::setTitle(), SWGSDRangel::SWGWFMDemodSettings::setUseReverseApi(), and SWGSDRangel::SWGWFMDemodSettings::setVolume().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getWfmDemodSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getWfmDemodSettings()->setRfBandwidth(settings.m_rfBandwidth);
     response.getWfmDemodSettings()->setAfBandwidth(settings.m_afBandwidth);
     response.getWfmDemodSettings()->setVolume(settings.m_volume);
     response.getWfmDemodSettings()->setSquelch(settings.m_squelch);
     response.getWfmDemodSettings()->setAudioMute(settings.m_audioMute ? 1 : 0);
     response.getWfmDemodSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getWfmDemodSettings()->getTitle()) {
         *response.getWfmDemodSettings()->getTitle() = settings.m_title;
     } else {
         response.getWfmDemodSettings()->setTitle(new QString(settings.m_title));
     }
     if (response.getWfmDemodSettings()->getAudioDeviceName()) {
         *response.getWfmDemodSettings()->getAudioDeviceName() = settings.m_audioDeviceName;
     } else {
         response.getWfmDemodSettings()->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     response.getWfmDemodSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getWfmDemodSettings()->getReverseApiAddress()) {
         *response.getWfmDemodSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getWfmDemodSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getWfmDemodSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getWfmDemodSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getWfmDemodSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int WFMDemod::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 528 of file wfmdemod.cpp.
References SWGSDRangel::SWGChannelReport::getWfmDemodReport(), SWGSDRangel::SWGWFMDemodReport::init(), SWGSDRangel::SWGChannelReport::setWfmDemodReport(), and webapiFormatChannelReport().
Referenced by getMagSqLevels().
 {
     (void) errorMessage;
     response.setWfmDemodReport(new SWGSDRangel::SWGWFMDemodReport());
     response.getWfmDemodReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendSettings()
void WFMDemod::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const WFMDemodSettings & settings, bool force) private
Definition at line 586 of file wfmdemod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), SWGSDRangel::SWGChannelSettings::getWfmDemodSettings(), WFMDemodSettings::m_afBandwidth, WFMDemodSettings::m_audioDeviceName, WFMDemodSettings::m_audioMute, WFMDemodSettings::m_inputFrequencyOffset, m_networkManager, m_networkRequest, WFMDemodSettings::m_reverseAPIAddress, WFMDemodSettings::m_reverseAPIChannelIndex, WFMDemodSettings::m_reverseAPIDeviceIndex, WFMDemodSettings::m_reverseAPIPort, WFMDemodSettings::m_rfBandwidth, WFMDemodSettings::m_rgbColor, WFMDemodSettings::m_squelch, WFMDemodSettings::m_title, WFMDemodSettings::m_volume, SWGSDRangel::SWGWFMDemodSettings::setAfBandwidth(), SWGSDRangel::SWGWFMDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGWFMDemodSettings::setAudioMute(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGWFMDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGWFMDemodSettings::setRfBandwidth(), SWGSDRangel::SWGWFMDemodSettings::setRgbColor(), SWGSDRangel::SWGWFMDemodSettings::setSquelch(), SWGSDRangel::SWGWFMDemodSettings::setTitle(), SWGSDRangel::SWGWFMDemodSettings::setVolume(), and SWGSDRangel::SWGChannelSettings::setWfmDemodSettings().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(0); // single sink (Rx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("WFMDemod"));
     swgChannelSettings->setWfmDemodSettings(new SWGSDRangel::SWGWFMDemodSettings());
     SWGSDRangel::SWGWFMDemodSettings *swgWFMDemodSettings = swgChannelSettings->getWfmDemodSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgWFMDemodSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("rfBandwidth") || force) {
         swgWFMDemodSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (channelSettingsKeys.contains("afBandwidth") || force) {
         swgWFMDemodSettings->setAfBandwidth(settings.m_afBandwidth);
     }
     if (channelSettingsKeys.contains("volume") || force) {
         swgWFMDemodSettings->setVolume(settings.m_volume);
     }
     if (channelSettingsKeys.contains("squelch") || force) {
         swgWFMDemodSettings->setSquelch(settings.m_squelch);
     }
     if (channelSettingsKeys.contains("audioMute") || force) {
         swgWFMDemodSettings->setAudioMute(settings.m_audioMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgWFMDemodSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgWFMDemodSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("audioDeviceName") || force) {
         swgWFMDemodSettings->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int WFMDemod::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 440 of file wfmdemod.cpp.
References SWGSDRangel::SWGChannelSettings::getWfmDemodSettings(), SWGSDRangel::SWGWFMDemodSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setWfmDemodSettings(), and webapiFormatChannelSettings().
Referenced by getMagSqLevels().
 {
     (void) errorMessage;
     response.setWfmDemodSettings(new SWGSDRangel::SWGWFMDemodSettings());
     response.getWfmDemodSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int WFMDemod::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 451 of file wfmdemod.cpp.
References WFMDemod::MsgConfigureWFMDemod::create(), WFMDemod::MsgConfigureChannelizer::create(), SWGSDRangel::SWGWFMDemodSettings::getAfBandwidth(), SWGSDRangel::SWGWFMDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGWFMDemodSettings::getAudioMute(), SWGSDRangel::SWGWFMDemodSettings::getInputFrequencyOffset(), SWGSDRangel::SWGWFMDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGWFMDemodSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGWFMDemodSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGWFMDemodSettings::getReverseApiPort(), SWGSDRangel::SWGWFMDemodSettings::getRfBandwidth(), SWGSDRangel::SWGWFMDemodSettings::getRgbColor(), SWGSDRangel::SWGWFMDemodSettings::getSquelch(), SWGSDRangel::SWGWFMDemodSettings::getTitle(), SWGSDRangel::SWGWFMDemodSettings::getUseReverseApi(), SWGSDRangel::SWGWFMDemodSettings::getVolume(), SWGSDRangel::SWGChannelSettings::getWfmDemodSettings(), WFMDemodSettings::m_afBandwidth, WFMDemodSettings::m_audioDeviceName, WFMDemodSettings::m_audioMute, BasebandSampleSink::m_guiMessageQueue, WFMDemodSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, WFMDemodSettings::m_reverseAPIAddress, WFMDemodSettings::m_reverseAPIChannelIndex, WFMDemodSettings::m_reverseAPIDeviceIndex, WFMDemodSettings::m_reverseAPIPort, WFMDemodSettings::m_rfBandwidth, WFMDemodSettings::m_rgbColor, m_settings, WFMDemodSettings::m_squelch, WFMDemodSettings::m_title, WFMDemodSettings::m_useReverseAPI, WFMDemodSettings::m_volume, MessageQueue::push(), requiredBW(), and webapiFormatChannelSettings().
Referenced by getMagSqLevels().
 {
     (void) errorMessage;
     WFMDemodSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getWfmDemodSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getWfmDemodSettings()->getRfBandwidth();
     }
     if (channelSettingsKeys.contains("afBandwidth")) {
         settings.m_afBandwidth = response.getWfmDemodSettings()->getAfBandwidth();
     }
     if (channelSettingsKeys.contains("volume")) {
         settings.m_volume = response.getWfmDemodSettings()->getVolume();
     }
     if (channelSettingsKeys.contains("squelch")) {
         settings.m_squelch = response.getWfmDemodSettings()->getSquelch();
     }
     if (channelSettingsKeys.contains("audioMute")) {
         settings.m_audioMute = response.getWfmDemodSettings()->getAudioMute() != 0;
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getWfmDemodSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getWfmDemodSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("audioDeviceName")) {
         settings.m_audioDeviceName = *response.getWfmDemodSettings()->getAudioDeviceName();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getWfmDemodSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getWfmDemodSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getWfmDemodSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getWfmDemodSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getWfmDemodSettings()->getReverseApiChannelIndex();
     }
     if (frequencyOffsetChanged)
     {
         MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
                 requiredBW(settings.m_rfBandwidth), settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(channelConfigMsg);
     }
     MsgConfigureWFMDemod *msg = MsgConfigureWFMDemod::create(settings, force);
     m_inputMessageQueue.push(msg);
     qDebug("WFMDemod::webapiSettingsPutPatch: forward to GUI: %p", m_guiMessageQueue);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureWFMDemod *msgToGUI = MsgConfigureWFMDemod::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_audioBuffer
AudioVector WFMDemod::m_audioBuffer private
Definition at line 213 of file wfmdemod.h.
Referenced by feed(), and WFMDemod().
m_audioBufferFill
uint WFMDemod::m_audioBufferFill private
Definition at line 214 of file wfmdemod.h.
Referenced by feed(), and WFMDemod().
m_audioFifo
AudioFifo WFMDemod::m_audioFifo private
Definition at line 216 of file wfmdemod.h.
Referenced by applySettings(), feed(), start(), WFMDemod(), and ~WFMDemod().
m_audioSampleRate
quint32 WFMDemod::m_audioSampleRate private
Definition at line 193 of file wfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), handleMessage(), webapiFormatChannelReport(), and WFMDemod().
m_channelId
const QString WFMDemod::m_channelId = "WFMDemod" static
Definition at line 168 of file wfmdemod.h.
Referenced by WFMPlugin::initPlugin(), and WFMDemod().
m_channelIdURI
const QString WFMDemod::m_channelIdURI = "sdrangel.channel.wfmdemod" static
Definition at line 167 of file wfmdemod.h.
Referenced by WFMPlugin::initPlugin(), and WFMDemodGUI::WFMDemodGUI().
m_channelizer
DownChannelizer* WFMDemod::m_channelizer private
Definition at line 188 of file wfmdemod.h.
Referenced by handleMessage(), WFMDemod(), and ~WFMDemod().
m_deviceAPI
DeviceAPI* WFMDemod::m_deviceAPI private
Definition at line 186 of file wfmdemod.h.
Referenced by WFMDemod(), and ~WFMDemod().
m_fmExcursion
Real WFMDemod::m_fmExcursion private
Definition at line 211 of file wfmdemod.h.
Referenced by applyChannelSettings(), and applySettings().
m_inputFrequencyOffset
int WFMDemod::m_inputFrequencyOffset private
Definition at line 191 of file wfmdemod.h.
Referenced by applyChannelSettings(), start(), and WFMDemod().
m_inputSampleRate
int WFMDemod::m_inputSampleRate private
Definition at line 190 of file wfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), start(), webapiFormatChannelReport(), and WFMDemod().
m_interpolator
Interpolator WFMDemod::m_interpolator private
Interpolator between sample rate sent from DSP engine and requested RF bandwidth (rational)
Definition at line 196 of file wfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_interpolatorDistance
Real WFMDemod::m_interpolatorDistance private
Definition at line 197 of file wfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_interpolatorDistanceRemain
Real WFMDemod::m_interpolatorDistanceRemain private
Definition at line 198 of file wfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_magsq
double WFMDemod::m_magsq private
displayed averaged value
Definition at line 204 of file wfmdemod.h.
Referenced by getMagSqLevels().
m_magsqCount
int WFMDemod::m_magsqCount private
Definition at line 207 of file wfmdemod.h.
Referenced by feed(), and getMagSqLevels().
m_magSqLevelStore
MagSqLevelsStore WFMDemod::m_magSqLevelStore private
Definition at line 208 of file wfmdemod.h.
Referenced by getMagSqLevels().
m_magsqPeak
double WFMDemod::m_magsqPeak private
Definition at line 206 of file wfmdemod.h.
Referenced by feed(), and getMagSqLevels().
m_magsqSum
double WFMDemod::m_magsqSum private
Definition at line 205 of file wfmdemod.h.
Referenced by feed(), and getMagSqLevels().
m_movingAverage
MovingAverageUtil<Real, double, 16> WFMDemod::m_movingAverage private
Definition at line 210 of file wfmdemod.h.
Referenced by feed(), and getMagSq().
m_nco
NCO WFMDemod::m_nco private
Definition at line 195 of file wfmdemod.h.
Referenced by applyChannelSettings(), and feed().
m_networkManager
QNetworkAccessManager* WFMDemod::m_networkManager private
Definition at line 222 of file wfmdemod.h.
Referenced by webapiReverseSendSettings(), WFMDemod(), and ~WFMDemod().
m_networkRequest
QNetworkRequest WFMDemod::m_networkRequest private
Definition at line 223 of file wfmdemod.h.
Referenced by webapiReverseSendSettings().
m_phaseDiscri
PhaseDiscriminators WFMDemod::m_phaseDiscri private
Definition at line 220 of file wfmdemod.h.
Referenced by applyChannelSettings(), applySettings(), feed(), start(), and WFMDemod().
m_rfFilter
fftfilt* WFMDemod::m_rfFilter private
Definition at line 199 of file wfmdemod.h.
Referenced by applyChannelSettings(), applySettings(), feed(), WFMDemod(), and ~WFMDemod().
m_sampleBuffer
SampleVector WFMDemod::m_sampleBuffer private
Definition at line 217 of file wfmdemod.h.
Referenced by feed().
m_settings
WFMDemodSettings WFMDemod::m_settings private
Definition at line 192 of file wfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), deserialize(), feed(), serialize(), webapiSettingsGet(), webapiSettingsPutPatch(), and WFMDemod().
m_settingsMutex
QMutex WFMDemod::m_settingsMutex private
Definition at line 218 of file wfmdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_squelchLevel
Real WFMDemod::m_squelchLevel private
Definition at line 201 of file wfmdemod.h.
Referenced by applySettings(), and feed().
m_squelchOpen
bool WFMDemod::m_squelchOpen private
Definition at line 203 of file wfmdemod.h.
Referenced by feed(), and getSquelchOpen().
m_squelchState
int WFMDemod::m_squelchState private
Definition at line 202 of file wfmdemod.h.
Referenced by feed(), start(), and webapiFormatChannelReport().
m_threadedChannelizer
ThreadedBasebandSampleSink* WFMDemod::m_threadedChannelizer private
Definition at line 187 of file wfmdemod.h.
Referenced by WFMDemod(), and ~WFMDemod().
m_udpBlockSize
const int WFMDemod::m_udpBlockSize = 512 static private
Definition at line 225 of file wfmdemod.h.
The documentation for this class was generated from the following files:
plugins/channelrx/demodwfm/wfmdemod.h
plugins/channelrx/demodwfm/wfmdemod.cpp