SDRAngel: BladeRF2Input::MsgReportGainRange Class Reference
BladeRF2Input::MsgReportGainRange Class Reference
#include <bladerf2input.h>
Public Member Functions
int getMin () const
int getMax () const
int getStep () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportGainRange * create (int min, int max, int step)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportGainRange (int min, int max, int step)
Protected Attributes
int m_min
int m_max
int m_step
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 103 of file bladerf2input.h.
Constructor & Destructor Documentation
MsgReportGainRange()
BladeRF2Input::MsgReportGainRange::MsgReportGainRange (int min, int max, int step) inline protected
Definition at line 120 of file bladerf2input.h.
                                                        :
             Message(),
             m_min(min),
             m_max(max),
             m_step(step)
         {}
Member Function Documentation
create()
static MsgReportGainRange* BladeRF2Input::MsgReportGainRange::create (int min, int max, int step) inline static
Definition at line 111 of file bladerf2input.h.
Referenced by BladeRF2Input::applySettings(), and BladeRF2Input::handleMessage().
{
             return new MsgReportGainRange(min, max, step);
         }
getMax()
int BladeRF2Input::MsgReportGainRange::getMax () const inline
Definition at line 108 of file bladerf2input.h.
Referenced by BladeRF2InputGui::handleMessage().
 { return m_max; }
getMin()
int BladeRF2Input::MsgReportGainRange::getMin () const inline
Definition at line 107 of file bladerf2input.h.
Referenced by BladeRF2InputGui::handleMessage().
 { return m_min; }
getStep()
int BladeRF2Input::MsgReportGainRange::getStep () const inline
Definition at line 109 of file bladerf2input.h.
Referenced by BladeRF2InputGui::handleMessage().
 { return m_step; }
Member Data Documentation
m_max
int BladeRF2Input::MsgReportGainRange::m_max protected
Definition at line 117 of file bladerf2input.h.
m_min
int BladeRF2Input::MsgReportGainRange::m_min protected
Definition at line 116 of file bladerf2input.h.
m_step
int BladeRF2Input::MsgReportGainRange::m_step protected
Definition at line 118 of file bladerf2input.h.
The documentation for this class was generated from the following file:
plugins/samplesource/bladerf2input/bladerf2input.h