SDRAngel: ScopeVis::MsgScopeVisNGMoveTrigger Class Reference
ScopeVis::MsgScopeVisNGMoveTrigger Class Reference
Public Member Functions
uint32_t getTriggerIndex () const
bool getMoveUp () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgScopeVisNGMoveTrigger * create (uint32_t triggerIndex, bool moveUpElseDown)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgScopeVisNGMoveTrigger (uint32_t triggerIndex, bool moveUpElseDown)
Private Attributes
uint32_t m_triggerIndex
bool m_moveUpElseDown
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 359 of file scopevis.h.
Constructor & Destructor Documentation
MsgScopeVisNGMoveTrigger()
ScopeVis::MsgScopeVisNGMoveTrigger::MsgScopeVisNGMoveTrigger (uint32_t triggerIndex, bool moveUpElseDown) inline private
Definition at line 377 of file scopevis.h.
                                                                              :
             m_triggerIndex(triggerIndex),
             m_moveUpElseDown(moveUpElseDown)
         {}
Member Function Documentation
create()
static MsgScopeVisNGMoveTrigger* ScopeVis::MsgScopeVisNGMoveTrigger::create (uint32_t triggerIndex, bool moveUpElseDown) inline static
Definition at line 363 of file scopevis.h.
Referenced by ScopeVis::moveTrigger().
         {
             return new MsgScopeVisNGMoveTrigger(triggerIndex, moveUpElseDown);
         }
getMoveUp()
bool ScopeVis::MsgScopeVisNGMoveTrigger::getMoveUp () const inline
Definition at line 371 of file scopevis.h.
Referenced by ScopeVis::handleMessage().
 { return m_moveUpElseDown; }
getTriggerIndex()
uint32_t ScopeVis::MsgScopeVisNGMoveTrigger::getTriggerIndex () const inline
Definition at line 370 of file scopevis.h.
Referenced by ScopeVis::handleMessage().
 { return m_triggerIndex; }
Member Data Documentation
m_moveUpElseDown
bool ScopeVis::MsgScopeVisNGMoveTrigger::m_moveUpElseDown private
Definition at line 375 of file scopevis.h.
m_triggerIndex
uint32_t ScopeVis::MsgScopeVisNGMoveTrigger::m_triggerIndex private
Definition at line 374 of file scopevis.h.
The documentation for this class was generated from the following file:
sdrgui/dsp/scopevis.h