SDRAngel: Command Class Reference
Command Class Reference
#include <command.h>
Inherits QObject.
Public Member Functions
Command ()
Command (const Command &command)
~Command ()
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
void setCommand (const QString &command)
const QString & getCommand () const
void setArgString (const QString &argString)
const QString & getArgString () const
void setGroup (const QString &group)
const QString & getGroup () const
void setDescription (const QString &description)
const QString & getDescription () const
void setKey (Qt::Key key)
Qt::Key getKey () const
void setKeyModifiers (Qt::KeyboardModifiers keyModifiers)
Qt::KeyboardModifiers getKeyModifiers () const
void setAssociateKey (bool associate)
bool getAssociateKey () const
void setRelease (bool release)
bool getRelease () const
QString getKeyLabel () const
void run (const QString &apiAddress, int apiPort, int deviceSetIndex)
void kill ()
QProcess::ProcessState getLastProcessState () const
bool getLastProcessError (QProcess::ProcessError &error) const
bool getLastProcessExit (int &exitCode, QProcess::ExitStatus &exitStatus) const
const QString & getLastProcessLog () const
uint64_t getLastProcessStartTimestampms () const
uint64_t getLastProcessFinishTimestampms () const
const QString & getLastProcessCommandLine () const
qint64 getLastProcessPid () const
Static Public Member Functions
static bool commandCompare (const Command *c1, Command *c2)
Private Slots
void processStateChanged (QProcess::ProcessState newState)
void processError (QProcess::ProcessError error)
void processFinished (int exitCode, QProcess::ExitStatus exitStatus)
Private Attributes
QString m_group
QString m_description
QString m_command
QString m_argString
Qt::Key m_key
Qt::KeyboardModifiers m_keyModifiers
bool m_associateKey
bool m_release
QProcess * m_currentProcess
QProcess::ProcessState m_currentProcessState
bool m_isInError
QProcess::ProcessError m_currentProcessError
bool m_hasExited
int m_currentProcessExitCode
QProcess::ExitStatus m_currentProcessExitStatus
QString m_log
uint64_t m_currentProcessStartTimeStampms
uint64_t m_currentProcessFinishTimeStampms
QString m_currentProcessCommandLine
qint64 m_currentProcessPid
Detailed Description
Definition at line 31 of file command.h.
Constructor & Destructor Documentation
Command() [1/2]
Command::Command ()
Definition at line 27 of file command.cpp.
References m_currentProcessFinishTimeStampms, m_currentProcessStartTimeStampms, and resetToDefaults().
                  :
     m_currentProcess(nullptr),
     m_currentProcessState(QProcess::NotRunning),
     m_isInError(false),
     m_currentProcessError(QProcess::UnknownError),
     m_hasExited(false),
     m_currentProcessExitCode(0),
     m_currentProcessExitStatus(QProcess::NormalExit),
     m_currentProcessPid(0)
 {
     m_currentProcessStartTimeStampms = 0;
     m_currentProcessFinishTimeStampms = 0;
     resetToDefaults();
 }
Command() [2/2]
Command::Command (const Command & command)
Definition at line 43 of file command.cpp.
References m_currentProcessFinishTimeStampms, and m_currentProcessStartTimeStampms.
                                        :
         QObject(),
         m_group(command.m_group),
         m_description(command.m_description),
         m_command(command.m_command),
         m_argString(command.m_argString),
         m_key(command.m_key),
         m_keyModifiers(command.m_keyModifiers),
         m_associateKey(command.m_associateKey),
         m_release(command.m_release),
         m_currentProcess(nullptr),
         m_currentProcessState(QProcess::NotRunning),
         m_isInError(false),
         m_currentProcessError(QProcess::UnknownError),
         m_hasExited(false),
         m_currentProcessExitCode(0),
         m_currentProcessExitStatus(QProcess::NormalExit),
         m_currentProcessPid(0)
 {
     m_currentProcessStartTimeStampms = 0;
     m_currentProcessFinishTimeStampms = 0;
 }
~Command()
Command::~Command ()
Definition at line 66 of file command.cpp.
References m_currentProcess, processError(), processFinished(), and processStateChanged().
 {
     if (m_currentProcess)
     {
 #if QT_VERSION < 0x051000
         disconnect(m_currentProcess, SIGNAL(error(QProcess::ProcessError)), this, SLOT(processError(QProcess::ProcessError)));
 #else
         disconnect(m_currentProcess, SIGNAL(errorOccurred(QProcess::ProcessError)), this, SLOT(processError(QProcess::ProcessError)));
 #endif
         disconnect(m_currentProcess, SIGNAL(finished(int, QProcess::ExitStatus)), this, SLOT(processFinished(int, QProcess::ExitStatus)));
         disconnect(m_currentProcess, SIGNAL(stateChanged(QProcess::ProcessState)), this, SLOT(processStateChanged(QProcess::ProcessState)));
         m_currentProcess->deleteLater();
     }
 }
Member Function Documentation
commandCompare()
static bool Command::commandCompare (const Command * c1, Command * c2) inline static
Definition at line 72 of file command.h.
References m_description, m_group, m_key, and m_release.
Referenced by MainSettings::sortCommands().
     {
         if (c1->m_group != c2->m_group)
         {
             return c1->m_group < c2->m_group;
         }
         else
         {
             if (c1->m_description != c2->m_description) {
                 return c1->m_description < c2->m_description;
             }
             else
             {
                 if (c1->m_key != c2->m_key) {
                     return c1->m_key < c2->m_key;
                 } else {
                     return c1->m_release;
                 }
             }
         }
     }
deserialize()
bool Command::deserialize (const QByteArray & data)
Definition at line 110 of file command.cpp.
References SimpleDeserializer::getVersion(), SimpleDeserializer::isValid(), m_argString, m_associateKey, m_command, m_description, m_group, m_key, m_keyModifiers, m_release, SimpleDeserializer::readBool(), SimpleDeserializer::readS32(), SimpleDeserializer::readString(), and resetToDefaults().
Referenced by MainSettings::load().
 {
     SimpleDeserializer d(data);
     if (!d.isValid())
     {
         resetToDefaults();
         return false;
     }
     if (d.getVersion() == 1)
     {
         int tmpInt;
         d.readString(1, &m_group, "default");
         d.readString(2, &m_description, "no name");
         d.readString(3, &m_command, "");
         d.readString(4, &m_argString, "");
         d.readS32(5, &tmpInt, 0);
         m_key = static_cast<Qt::Key>(tmpInt);
         d.readS32(6, &tmpInt, 0);
         m_keyModifiers = static_cast<Qt::KeyboardModifiers>(tmpInt);
         d.readBool(7, &m_associateKey, false);
         d.readBool(8, &m_release, false);
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
getArgString()
const QString& Command::getArgString () const inline
Definition at line 46 of file command.h.
Referenced by EditCommandDialog::fromCommand().
 { return m_argString; }
getAssociateKey()
bool Command::getAssociateKey () const inline
Definition at line 56 of file command.h.
Referenced by MainWindow::addCommandToTree(), MainWindow::commandKeyPressed(), and EditCommandDialog::fromCommand().
 { return m_associateKey; }
getCommand()
const QString& Command::getCommand () const inline
Definition at line 44 of file command.h.
Referenced by EditCommandDialog::fromCommand().
 { return m_command; }
getDescription()
const QString& Command::getDescription () const inline
Definition at line 50 of file command.h.
Referenced by MainWindow::addCommandToTree(), EditCommandDialog::fromCommand(), and MainWindow::on_commandDelete_clicked().
 { return m_description; }
getGroup()
const QString& Command::getGroup () const inline
Definition at line 48 of file command.h.
Referenced by MainWindow::addCommandToTree(), EditCommandDialog::fromCommand(), MainWindow::on_commandEdit_clicked(), and MainWindow::on_commandRun_clicked().
 { return m_group; }
getKey()
Qt::Key Command::getKey () const inline
Definition at line 52 of file command.h.
Referenced by MainWindow::commandKeyPressed(), and EditCommandDialog::fromCommand().
 { return m_key; }
getKeyLabel()
QString Command::getKeyLabel () const
Definition at line 144 of file command.cpp.
References m_key, and m_keyModifiers.
Referenced by MainWindow::addCommandToTree().
 {
     if (m_key == 0)
     {
        return "";
     }
     else if (m_keyModifiers != Qt::NoModifier)
     {
         QString altGrStr = m_keyModifiers & Qt::GroupSwitchModifier ? "Gr " : "";
         int maskedModifiers = (m_keyModifiers & 0x3FFFFFFF) + ((m_keyModifiers & 0x40000000)>>3);
         return altGrStr + QKeySequence(maskedModifiers, m_key).toString();
     }
     else
     {
         return QKeySequence(m_key).toString();
     }
 }
getKeyModifiers()
Qt::KeyboardModifiers Command::getKeyModifiers () const inline
Definition at line 54 of file command.h.
Referenced by MainWindow::commandKeyPressed(), and EditCommandDialog::fromCommand().
 { return m_keyModifiers; }
getLastProcessCommandLine()
const QString& Command::getLastProcessCommandLine () const inline
Definition at line 69 of file command.h.
Referenced by CommandOutputDialog::refresh().
 { return m_currentProcessCommandLine; }
getLastProcessError()
bool Command::getLastProcessError (QProcess::ProcessError & error) const
Definition at line 223 of file command.cpp.
References m_currentProcessError, and m_isInError.
Referenced by CommandOutputDialog::refresh().
 {
     if (m_isInError) {
         error = m_currentProcessError;
     }
     return m_isInError;
 }
getLastProcessExit()
bool Command::getLastProcessExit (int & exitCode, QProcess::ExitStatus & exitStatus) const
Definition at line 232 of file command.cpp.
References m_currentProcessExitCode, m_currentProcessExitStatus, and m_hasExited.
Referenced by CommandOutputDialog::refresh().
 {
     if (m_hasExited)
     {
         exitCode = m_currentProcessExitCode;
         exitStatus = m_currentProcessExitStatus;
     }
     return m_hasExited;
 }
getLastProcessFinishTimestampms()
uint64_t Command::getLastProcessFinishTimestampms () const inline
Definition at line 68 of file command.h.
Referenced by CommandOutputDialog::refresh().
 { return m_currentProcessFinishTimeStampms; }
getLastProcessLog()
const QString & Command::getLastProcessLog () const
Definition at line 243 of file command.cpp.
References m_log.
Referenced by CommandOutputDialog::refresh().
 {
     return m_log;
 }
getLastProcessPid()
qint64 Command::getLastProcessPid () const inline
Definition at line 70 of file command.h.
Referenced by CommandOutputDialog::refresh().
 { return m_currentProcessPid; }
getLastProcessStartTimestampms()
uint64_t Command::getLastProcessStartTimestampms () const inline
Definition at line 67 of file command.h.
Referenced by CommandOutputDialog::refresh().
 { return m_currentProcessStartTimeStampms; }
getLastProcessState()
QProcess::ProcessState Command::getLastProcessState () const
Definition at line 218 of file command.cpp.
References m_currentProcessState.
Referenced by CommandOutputDialog::refresh().
 {
     return m_currentProcessState;
 }
getRelease()
bool Command::getRelease () const inline
Definition at line 58 of file command.h.
Referenced by MainWindow::addCommandToTree(), MainWindow::commandKeyPressed(), and EditCommandDialog::fromCommand().
 { return m_release; }
kill()
void Command::kill ()
Definition at line 209 of file command.cpp.
References m_currentProcess, and m_currentProcessPid.
Referenced by CommandOutputDialog::on_processKill_toggled().
 {
     if (m_currentProcess)
     {
         qDebug("Command::kill: %lld", m_currentProcessPid);
         m_currentProcess->kill();
     }
 }
processError
void Command::processError (QProcess::ProcessError error) private slot
Definition at line 258 of file command.cpp.
References m_currentProcess, m_currentProcessError, m_currentProcessFinishTimeStampms, m_currentProcessState, m_isInError, m_log, TimeUtil::nowms(), processFinished(), and processStateChanged().
Referenced by processFinished(), run(), and ~Command().
 {
     //qDebug("Command::processError: %d state: %d", error, m_currentProcessState);
     m_currentProcessFinishTimeStampms = TimeUtil::nowms();
     m_currentProcessError = error;
     m_isInError = true;
     if (m_currentProcessState == QProcess::NotRunning)
     {
         m_log = m_currentProcess->readAllStandardOutput();
 #if QT_VERSION < 0x051000
         disconnect(m_currentProcess, SIGNAL(error(QProcess::ProcessError)), this, SLOT(processError(QProcess::ProcessError)));
 #else
         disconnect(m_currentProcess, SIGNAL(errorOccurred(QProcess::ProcessError)), this, SLOT(processError(QProcess::ProcessError)));
 #endif
         disconnect(m_currentProcess, SIGNAL(finished(int, QProcess::ExitStatus)), this, SLOT(processFinished(int, QProcess::ExitStatus)));
         disconnect(m_currentProcess, SIGNAL(stateChanged(QProcess::ProcessState)), this, SLOT(processStateChanged(QProcess::ProcessState)));
         m_currentProcess->deleteLater(); // make sure other threads can still access it until all events have been processed
         m_currentProcess = nullptr; // for this thread it can assume it was deleted
     }
 }
processFinished
void Command::processFinished (int exitCode, QProcess::ExitStatus exitStatus) private slot
Definition at line 282 of file command.cpp.
References m_currentProcess, m_currentProcessExitCode, m_currentProcessExitStatus, m_currentProcessFinishTimeStampms, m_hasExited, m_log, TimeUtil::nowms(), processError(), and processStateChanged().
Referenced by processError(), run(), and ~Command().
 {
     //qDebug("Command::processFinished: (%d) %d", exitCode, exitStatus);
     m_currentProcessFinishTimeStampms = TimeUtil::nowms();
     m_currentProcessExitCode = exitCode;
     m_currentProcessExitStatus = exitStatus;
     m_hasExited = true;
     m_log = m_currentProcess->readAllStandardOutput();
 #if QT_VERSION < 0x051000
     disconnect(m_currentProcess, SIGNAL(error(QProcess::ProcessError)), this, SLOT(processError(QProcess::ProcessError)));
 #else
     disconnect(m_currentProcess, SIGNAL(errorOccurred(QProcess::ProcessError)), this, SLOT(processError(QProcess::ProcessError)));
 #endif
     disconnect(m_currentProcess, SIGNAL(finished(int, QProcess::ExitStatus)), this, SLOT(processFinished(int, QProcess::ExitStatus)));
     disconnect(m_currentProcess, SIGNAL(stateChanged(QProcess::ProcessState)), this, SLOT(processStateChanged(QProcess::ProcessState)));
     m_currentProcess->deleteLater(); // make sure other threads can still access it until all events have been processed
     m_currentProcess = nullptr; // for this thread it can assume it was deleted
 }
processStateChanged
void Command::processStateChanged (QProcess::ProcessState newState) private slot
Definition at line 248 of file command.cpp.
References m_currentProcess, m_currentProcessPid, and m_currentProcessState.
Referenced by processError(), processFinished(), run(), and ~Command().
 {
     //qDebug("Command::processStateChanged: %d", newState);
     if (newState == QProcess::Running) {
         m_currentProcessPid = m_currentProcess->processId();
     }
     m_currentProcessState = newState;
 }
resetToDefaults()
void Command::resetToDefaults ()
Definition at line 81 of file command.cpp.
References m_argString, m_associateKey, m_command, m_description, m_group, m_key, m_keyModifiers, and m_release.
Referenced by Command(), and deserialize().
 {
     m_group = "default";
     m_description = "no name";
     m_command = "";
     m_argString = "";
     m_key = static_cast<Qt::Key>(0);
     m_keyModifiers = Qt::NoModifier;
     m_associateKey = false;
     m_release = false;
 }
run()
void Command::run (const QString & apiAddress, int apiPort, int deviceSetIndex)
Definition at line 162 of file command.cpp.
References m_argString, m_command, m_currentProcess, m_currentProcessCommandLine, m_currentProcessStartTimeStampms, m_hasExited, m_isInError, TimeUtil::nowms(), processError(), processFinished(), and processStateChanged().
Referenced by MainWindow::commandKeyPressed(), and MainWindow::on_commandRun_clicked().
 {
     if (m_currentProcess)
     {
         qWarning("Command::run: process already running");
         return;
     }
     QString args = m_argString;
     if (m_argString.contains("%1"))
     {
         args = args.arg(apiAddress);
     }
     if (m_argString.contains("%2"))
     {
         args.replace("%2", "%1");
         args = args.arg(apiPort);
     }
     if (m_argString.contains("%3"))
     {
         args.replace("%3", "%1");
         args = args.arg(deviceSetIndex);
     }
     m_currentProcessCommandLine = QString("%1 %2").arg(m_command).arg(args);
     qDebug("Command::run: %s", qPrintable(m_currentProcessCommandLine));
     m_currentProcess = new QProcess(this);
     m_isInError = false;
     m_hasExited = false;
 #if QT_VERSION < 0x051000
     connect(m_currentProcess, SIGNAL(error(QProcess::ProcessError)), this, SLOT(processError(QProcess::ProcessError)));
 #else
     connect(m_currentProcess, SIGNAL(errorOccurred(QProcess::ProcessError)), this, SLOT(processError(QProcess::ProcessError)));
 #endif
     connect(m_currentProcess, SIGNAL(finished(int, QProcess::ExitStatus)), this, SLOT(processFinished(int, QProcess::ExitStatus)));
     connect(m_currentProcess, SIGNAL(stateChanged(QProcess::ProcessState)), this, SLOT(processStateChanged(QProcess::ProcessState)));
     m_currentProcess->setProcessChannelMode(QProcess::MergedChannels);
     m_currentProcessStartTimeStampms = TimeUtil::nowms();
     m_currentProcess->start(m_currentProcessCommandLine);
 }
serialize()
QByteArray Command::serialize () const
Definition at line 93 of file command.cpp.
References SimpleSerializer::final(), m_argString, m_associateKey, m_command, m_description, m_group, m_key, m_keyModifiers, m_release, SimpleSerializer::writeBool(), SimpleSerializer::writeS32(), and SimpleSerializer::writeString().
 {
     SimpleSerializer s(1);
     s.writeString(1, m_group);
     s.writeString(2, m_description);
     s.writeString(3, m_command);
     s.writeString(4, m_argString);
     s.writeS32(5, (int) m_key);
     s.writeS32(6, (int) m_keyModifiers);
     s.writeBool(7, m_associateKey);
     s.writeBool(8, m_release);
     return s.final();
 }
setArgString()
void Command::setArgString (const QString & argString) inline
Definition at line 45 of file command.h.
Referenced by EditCommandDialog::toCommand().
 { m_argString = argString; }
setAssociateKey()
void Command::setAssociateKey (bool associate) inline
Definition at line 55 of file command.h.
Referenced by EditCommandDialog::toCommand().
 { m_associateKey = associate; }
setCommand()
void Command::setCommand (const QString & command) inline
Definition at line 43 of file command.h.
Referenced by EditCommandDialog::toCommand().
 { m_command = command; }
setDescription()
void Command::setDescription (const QString & description) inline
Definition at line 49 of file command.h.
Referenced by MainWindow::on_commandNew_clicked(), and EditCommandDialog::toCommand().
 { m_description = description; }
setGroup()
void Command::setGroup (const QString & group) inline
Definition at line 47 of file command.h.
Referenced by MainWindow::on_commandNew_clicked(), MainSettings::renameCommandGroup(), and EditCommandDialog::toCommand().
 { m_group = group; }
setKey()
void Command::setKey (Qt::Key key) inline
Definition at line 51 of file command.h.
Referenced by EditCommandDialog::toCommand().
 { m_key = key; }
setKeyModifiers()
void Command::setKeyModifiers (Qt::KeyboardModifiers keyModifiers) inline
Definition at line 53 of file command.h.
Referenced by EditCommandDialog::toCommand().
 { m_keyModifiers = keyModifiers; }
setRelease()
void Command::setRelease (bool release) inline
Definition at line 57 of file command.h.
Referenced by EditCommandDialog::toCommand().
 { m_release = release; }
Member Data Documentation
m_argString
QString Command::m_argString private
Definition at line 98 of file command.h.
Referenced by deserialize(), resetToDefaults(), run(), and serialize().
m_associateKey
bool Command::m_associateKey private
Definition at line 101 of file command.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_command
QString Command::m_command private
Definition at line 97 of file command.h.
Referenced by deserialize(), resetToDefaults(), run(), and serialize().
m_currentProcess
QProcess* Command::m_currentProcess private
Definition at line 103 of file command.h.
Referenced by kill(), processError(), processFinished(), processStateChanged(), run(), and ~Command().
m_currentProcessCommandLine
QString Command::m_currentProcessCommandLine private
Definition at line 113 of file command.h.
Referenced by run().
m_currentProcessError
QProcess::ProcessError Command::m_currentProcessError private
Definition at line 106 of file command.h.
Referenced by getLastProcessError(), and processError().
m_currentProcessExitCode
int Command::m_currentProcessExitCode private
Definition at line 108 of file command.h.
Referenced by getLastProcessExit(), and processFinished().
m_currentProcessExitStatus
QProcess::ExitStatus Command::m_currentProcessExitStatus private
Definition at line 109 of file command.h.
Referenced by getLastProcessExit(), and processFinished().
m_currentProcessFinishTimeStampms
uint64_t Command::m_currentProcessFinishTimeStampms private
Definition at line 112 of file command.h.
Referenced by Command(), processError(), and processFinished().
m_currentProcessPid
qint64 Command::m_currentProcessPid private
Definition at line 114 of file command.h.
Referenced by kill(), and processStateChanged().
m_currentProcessStartTimeStampms
uint64_t Command::m_currentProcessStartTimeStampms private
Definition at line 111 of file command.h.
Referenced by Command(), and run().
m_currentProcessState
QProcess::ProcessState Command::m_currentProcessState private
Definition at line 104 of file command.h.
Referenced by getLastProcessState(), processError(), and processStateChanged().
m_description
QString Command::m_description private
Definition at line 96 of file command.h.
Referenced by commandCompare(), deserialize(), resetToDefaults(), and serialize().
m_group
QString Command::m_group private
Definition at line 95 of file command.h.
Referenced by commandCompare(), deserialize(), resetToDefaults(), and serialize().
m_hasExited
bool Command::m_hasExited private
Definition at line 107 of file command.h.
Referenced by getLastProcessExit(), processFinished(), and run().
m_isInError
bool Command::m_isInError private
Definition at line 105 of file command.h.
Referenced by getLastProcessError(), processError(), and run().
m_key
Qt::Key Command::m_key private
Definition at line 99 of file command.h.
Referenced by commandCompare(), deserialize(), getKeyLabel(), resetToDefaults(), and serialize().
m_keyModifiers
Qt::KeyboardModifiers Command::m_keyModifiers private
Definition at line 100 of file command.h.
Referenced by deserialize(), getKeyLabel(), resetToDefaults(), and serialize().
m_log
QString Command::m_log private
Definition at line 110 of file command.h.
Referenced by getLastProcessLog(), processError(), and processFinished().
m_release
bool Command::m_release private
Definition at line 102 of file command.h.
Referenced by commandCompare(), deserialize(), resetToDefaults(), and serialize().
The documentation for this class was generated from the following files:
sdrbase/commands/command.h
sdrbase/commands/command.cpp