SDRAngel: RemoteSinkPlugin Class Reference
RemoteSinkPlugin Class Reference
#include <remotesinkplugin.h>
Public Member Functions
RemoteSinkPlugin (QObject *parent=0)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
Private Attributes
PluginAPI * m_pluginAPI
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Private Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Private Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Detailed Description
Definition at line 28 of file remotesinkplugin.h.
Constructor & Destructor Documentation
RemoteSinkPlugin()
RemoteSinkPlugin::RemoteSinkPlugin (QObject * parent = 0) explicit
Definition at line 37 of file remotesinkplugin.cpp.
                                                   :
     QObject(parent),
     m_pluginAPI(0)
 {
 }
Member Function Documentation
createRxChannelBS()
BasebandSampleSink * RemoteSinkPlugin::createRxChannelBS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 70 of file remotesinkplugin.cpp.
 {
     return new RemoteSink(deviceAPI);
 }
createRxChannelCS()
ChannelAPI * RemoteSinkPlugin::createRxChannelCS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 75 of file remotesinkplugin.cpp.
 {
     return new RemoteSink(deviceAPI);
 }
createRxChannelGUI()
PluginInstanceGUI * RemoteSinkPlugin::createRxChannelGUI (DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) virtual
Reimplemented from PluginInterface.
Definition at line 64 of file remotesinkplugin.cpp.
References RemoteSinkGUI::create(), and m_pluginAPI.
Referenced by initPlugin().
 {
     return RemoteSinkGUI::create(m_pluginAPI, deviceUISet, rxChannel);
 }
getPluginDescriptor()
const PluginDescriptor & RemoteSinkPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 43 of file remotesinkplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void RemoteSinkPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 48 of file remotesinkplugin.cpp.
References createRxChannelGUI(), RemoteSink::m_channelId, RemoteSink::m_channelIdURI, m_pluginAPI, and PluginAPI::registerRxChannel().
 {
     m_pluginAPI = pluginAPI;
     // register channel Source
     m_pluginAPI->registerRxChannel(RemoteSink::m_channelIdURI, RemoteSink::m_channelId, this);
 }
Member Data Documentation
m_pluginAPI
PluginAPI* RemoteSinkPlugin::m_pluginAPI private
Definition at line 46 of file remotesinkplugin.h.
Referenced by createRxChannelGUI(), and initPlugin().
m_pluginDescriptor
const PluginDescriptor RemoteSinkPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("Remote channel sink"),
    QString("4.5.6"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 44 of file remotesinkplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/channelrx/remotesink/remotesinkplugin.h
plugins/channelrx/remotesink/remotesinkplugin.cpp