SDRAngel: SSBDemod Class Reference
SSBDemod Class Reference
#include <ssbdemod.h>
Classes
struct MagSqLevelsStore
class MsgConfigureChannelizer
class MsgConfigureSSBDemod
class MsgConfigureSSBDemodPrivate
Public Member Functions
SSBDemod (DeviceAPI *deviceAPI)
virtual ~SSBDemod ()
virtual void destroy ()
void setSampleSink (BasebandSampleSink *sampleSink)
void configure (MessageQueue *messageQueue, Real Bandwidth, Real LowCutoff, Real volume, int spanLog2, bool audioBinaural, bool audioFlipChannels, bool dsb, bool audioMute, bool agc, bool agcClamping, int agcTimeLog2, int agcPowerThreshold, int agcThresholdGate)
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool positiveOnly)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
uint32_t getAudioSampleRate () const
uint32_t getInputSampleRate () const
double getMagSq () const
bool getAudioActive () const
void getMagSqLevels (double &avg, double &peak, int &nbSamples)
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.ssbdemod"
static const QString m_channelId = "SSBDemod"
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const SSBDemodSettings &settings, bool force=false)
void applyAudioSampleRate (int sampleRate)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const SSBDemodSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const SSBDemodSettings &settings, bool force)
void processOneSample (Complex &ci)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
SSBDemodSettings m_settings
Real m_Bandwidth
Real m_LowCutoff
Real m_volume
int m_spanLog2
fftfilt::cmplx m_sum
int m_undersampleCount
int m_inputSampleRate
int m_inputFrequencyOffset
bool m_audioBinaual
bool m_audioFlipChannels
bool m_usb
bool m_dsb
bool m_audioMute
double m_magsq
double m_magsqSum
double m_magsqPeak
int m_magsqCount
MagSqLevelsStore m_magSqLevelStore
MagAGC m_agc
bool m_agcActive
bool m_agcClamping
int m_agcNbSamples
number of audio (48 kHz) samples for AGC averaging
double m_agcPowerThreshold
AGC power threshold (linear)
int m_agcThresholdGate
Gate length in number of samples befor threshold triggers.
DoubleBufferFIFO< fftfilt::cmplx > m_squelchDelayLine
bool m_audioActive
True if an audio signal is produced (no AGC or AGC and above threshold)
NCOF m_nco
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
fftfilt * SSBFilter
fftfilt * DSBFilter
BasebandSampleSink * m_sampleSink
SampleVector m_sampleBuffer
AudioVector m_audioBuffer
uint m_audioBufferFill
AudioFifo m_audioFifo
quint32 m_audioSampleRate
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
QMutex m_settingsMutex
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 48 of file ssbdemod.h.
Constructor & Destructor Documentation
SSBDemod()
SSBDemod::SSBDemod (DeviceAPI * deviceAPI)
Definition at line 51 of file ssbdemod.cpp.
References AudioDeviceManager::addAudioSink(), DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), applyChannelSettings(), applySettings(), DSBFilter, DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), m_agc, m_agcClamping, m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_Bandwidth, m_channelId, m_channelizer, m_deviceAPI, m_inputFrequencyOffset, m_inputSampleRate, m_LowCutoff, m_magsq, m_magsqCount, m_magsqPeak, m_magsqSum, m_networkManager, m_settings, m_spanLog2, m_sum, m_threadedChannelizer, m_undersampleCount, m_usb, m_volume, networkManagerFinished(), SDR_RX_SCALED, MagAGC::setClamping(), MagAGC::setClampMax(), ssbFftLen, and SSBFilter.
Referenced by SSBDemod::MsgConfigureChannelizer::MsgConfigureChannelizer().
                                        :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(deviceAPI),
         m_audioBinaual(false),
         m_audioFlipChannels(false),
         m_dsb(false),
         m_audioMute(false),
         m_agc(12000, agcTarget, 1e-2),
         m_agcActive(false),
         m_agcClamping(false),
         m_agcNbSamples(12000),
         m_agcPowerThreshold(1e-2),
         m_agcThresholdGate(0),
         m_squelchDelayLine(2*48000),
         m_audioActive(false),
         m_sampleSink(0),
         m_audioFifo(24000),
         m_settingsMutex(QMutex::Recursive)
 {
     setObjectName(m_channelId);
     m_Bandwidth = 5000;
     m_LowCutoff = 300;
     m_volume = 2.0;
     m_spanLog2 = 3;
     m_inputSampleRate = 48000;
     m_inputFrequencyOffset = 0;
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSink(&m_audioFifo, getInputMessageQueue());
     m_audioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getOutputSampleRate();
     m_audioBuffer.resize(1<<14);
     m_audioBufferFill = 0;
     m_undersampleCount = 0;
     m_sum = 0;
     m_usb = true;
     m_magsq = 0.0f;
     m_magsqSum = 0.0f;
     m_magsqPeak = 0.0f;
     m_magsqCount = 0;
     m_agc.setClampMax(SDR_RX_SCALED/100.0);
     m_agc.setClamping(m_agcClamping);
     SSBFilter = new fftfilt(m_LowCutoff / m_audioSampleRate, m_Bandwidth / m_audioSampleRate, ssbFftLen);
     DSBFilter = new fftfilt((2.0f * m_Bandwidth) / m_audioSampleRate, 2 * ssbFftLen);
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~SSBDemod()
SSBDemod::~SSBDemod () virtual
Definition at line 111 of file ssbdemod.cpp.
References DSBFilter, DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo, m_channelizer, m_deviceAPI, m_networkManager, m_threadedChannelizer, networkManagerFinished(), AudioDeviceManager::removeAudioSink(), DeviceAPI::removeChannelSink(), DeviceAPI::removeChannelSinkAPI(), and SSBFilter.
Referenced by SSBDemod::MsgConfigureChannelizer::MsgConfigureChannelizer().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_audioFifo);
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete SSBFilter;
     delete DSBFilter;
 }
Member Function Documentation
applyAudioSampleRate()
void SSBDemod::applyAudioSampleRate (int sampleRate) private
Definition at line 411 of file ssbdemod.cpp.
References agcTarget, DSPConfigureAudio::AudioOutput, Interpolator::create(), SSBDemod::MsgConfigureChannelizer::create(), fftfilt::create_dsb_filter(), fftfilt::create_filter(), DSBFilter, m_agc, m_agcNbSamples, SSBDemodSettings::m_agcThresholdGate, m_agcThresholdGate, SSBDemodSettings::m_agcTimeLog2, m_audioFifo, m_audioSampleRate, m_Bandwidth, BasebandSampleSink::m_guiMessageQueue, SSBDemodSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_LowCutoff, m_settings, m_settingsMutex, MessageQueue::push(), MagAGC::resize(), MagAGC::setGate(), AudioFifo::setSize(), MagAGC::setStepDownDelay(), and SSBFilter.
Referenced by applySettings(), and handleMessage().
 {
     qDebug("SSBDemod::applyAudioSampleRate: %d", sampleRate);
     MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
             sampleRate, m_settings.m_inputFrequencyOffset);
     m_inputMessageQueue.push(channelConfigMsg);
     m_settingsMutex.lock();
     Real interpolatorBandwidth = (m_Bandwidth * 1.5f) > m_inputSampleRate ? m_inputSampleRate : (m_Bandwidth * 1.5f);
     m_interpolator.create(16, m_inputSampleRate, interpolatorBandwidth, 2.0f);
     m_interpolatorDistanceRemain = 0;
     m_interpolatorDistance = (Real) m_inputSampleRate / (Real) sampleRate;
     SSBFilter->create_filter(m_LowCutoff / (float) sampleRate, m_Bandwidth / (float) sampleRate);
     DSBFilter->create_dsb_filter((2.0f * m_Bandwidth) / (float) sampleRate);
     int agcNbSamples = (sampleRate / 1000) * (1<<m_settings.m_agcTimeLog2);
     int agcThresholdGate = (sampleRate / 1000) * m_settings.m_agcThresholdGate; // ms
     if (m_agcNbSamples != agcNbSamples)
     {
         m_agc.resize(agcNbSamples, agcNbSamples/2, agcTarget);
         m_agc.setStepDownDelay(agcNbSamples);
         m_agcNbSamples = agcNbSamples;
     }
     if (m_agcThresholdGate != agcThresholdGate)
     {
         m_agc.setGate(agcThresholdGate);
         m_agcThresholdGate = agcThresholdGate;
     }
     m_audioFifo.setSize(sampleRate);
     m_settingsMutex.unlock();
     m_audioSampleRate = sampleRate;
     if (m_guiMessageQueue) // forward to GUI if any
     {
         DSPConfigureAudio *cfg = new DSPConfigureAudio(m_audioSampleRate, DSPConfigureAudio::AudioOutput);
         m_guiMessageQueue->push(cfg);
     }
 }
applyChannelSettings()
void SSBDemod::applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 385 of file ssbdemod.cpp.
References Interpolator::create(), m_audioSampleRate, m_Bandwidth, m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_nco, m_settingsMutex, and NCOF::setFreq().
Referenced by handleMessage(), SSBDemod(), and start().
 {
     qDebug() << "SSBDemod::applyChannelSettings:"
             << " inputSampleRate: " << inputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if ((m_inputFrequencyOffset != inputFrequencyOffset) ||
         (m_inputSampleRate != inputSampleRate) || force)
     {
         m_nco.setFreq(-inputFrequencyOffset, inputSampleRate);
     }
     if ((m_inputSampleRate != inputSampleRate) || force)
     {
         m_settingsMutex.lock();
         Real interpolatorBandwidth = (m_Bandwidth * 1.5f) > inputSampleRate ? inputSampleRate : (m_Bandwidth * 1.5f);
         m_interpolator.create(16, inputSampleRate, interpolatorBandwidth, 2.0f);
         m_interpolatorDistanceRemain = 0;
         m_interpolatorDistance = (Real) inputSampleRate / (Real) m_audioSampleRate;
         m_settingsMutex.unlock();
     }
     m_inputSampleRate = inputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applySettings()
void SSBDemod::applySettings (const SSBDemodSettings & settings, bool force = false) private
Definition at line 458 of file ssbdemod.cpp.
References AudioDeviceManager::addAudioSink(), agcTarget, applyAudioSampleRate(), Interpolator::create(), fftfilt::create_dsb_filter(), fftfilt::create_filter(), DSBFilter, DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), AudioDeviceManager::getOutputDeviceIndex(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), SSBDemodSettings::m_agc, m_agc, m_agcActive, SSBDemodSettings::m_agcClamping, m_agcClamping, m_agcNbSamples, SSBDemodSettings::m_agcPowerThreshold, m_agcPowerThreshold, SSBDemodSettings::m_agcThresholdGate, m_agcThresholdGate, SSBDemodSettings::m_agcTimeLog2, m_audioBinaual, SSBDemodSettings::m_audioBinaural, SSBDemodSettings::m_audioDeviceName, m_audioFifo, SSBDemodSettings::m_audioFlipChannels, m_audioFlipChannels, SSBDemodSettings::m_audioMute, m_audioMute, m_audioSampleRate, m_Bandwidth, SSBDemodSettings::m_dsb, m_dsb, SSBDemodSettings::m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, SSBDemodSettings::m_lowCutoff, m_LowCutoff, SSBDemodSettings::m_minPowerThresholdDB, SSBDemodSettings::m_reverseAPIAddress, SSBDemodSettings::m_reverseAPIChannelIndex, SSBDemodSettings::m_reverseAPIDeviceIndex, SSBDemodSettings::m_reverseAPIPort, SSBDemodSettings::m_rfBandwidth, m_settings, m_settingsMutex, SSBDemodSettings::m_spanLog2, m_spanLog2, m_usb, SSBDemodSettings::m_useReverseAPI, SSBDemodSettings::m_volume, m_volume, CalcDb::powerFromdB(), MagAGC::resize(), SDR_RX_SCALED, MagAGC::setClamping(), MagAGC::setGate(), MagAGC::setStepDownDelay(), MagAGC::setThreshold(), MagAGC::setThresholdEnable(), SSBFilter, and webapiReverseSendSettings().
Referenced by handleMessage(), and SSBDemod().
 {
     qDebug() << "SSBDemod::applySettings:"
             << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
             << " m_rfBandwidth: " << settings.m_rfBandwidth
             << " m_lowCutoff: " << settings.m_lowCutoff
             << " m_volume: " << settings.m_volume
             << " m_spanLog2: " << settings.m_spanLog2
             << " m_audioBinaual: " << settings.m_audioBinaural
             << " m_audioFlipChannels: " << settings.m_audioFlipChannels
             << " m_dsb: " << settings.m_dsb
             << " m_audioMute: " << settings.m_audioMute
             << " m_agcActive: " << settings.m_agc
             << " m_agcClamping: " << settings.m_agcClamping
             << " m_agcTimeLog2: " << settings.m_agcTimeLog2
             << " agcPowerThreshold: " << settings.m_agcPowerThreshold
             << " agcThresholdGate: " << settings.m_agcThresholdGate
             << " m_audioDeviceName: " << settings.m_audioDeviceName
             << " m_useReverseAPI: " << settings.m_useReverseAPI
             << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
             << " m_reverseAPIPort: " << settings.m_reverseAPIPort
             << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex
             << " m_reverseAPIChannelIndex: " << settings.m_reverseAPIChannelIndex
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if((m_settings.m_inputFrequencyOffset != settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if((m_settings.m_rfBandwidth != settings.m_rfBandwidth) || force) {
         reverseAPIKeys.append("rfBandwidth");
     }
     if((m_settings.m_lowCutoff != settings.m_lowCutoff) || force) {
         reverseAPIKeys.append("lowCutoff");
     }
     if((m_settings.m_rfBandwidth != settings.m_rfBandwidth) ||
         (m_settings.m_lowCutoff != settings.m_lowCutoff) || force)
     {
         float band, lowCutoff;
         band = settings.m_rfBandwidth;
         lowCutoff = settings.m_lowCutoff;
         if (band < 0) {
             band = -band;
             lowCutoff = -lowCutoff;
             m_usb = false;
         } else {
             m_usb = true;
         }
         if (band < 100.0f)
         {
             band = 100.0f;
             lowCutoff = 0;
         }
         m_Bandwidth = band;
         m_LowCutoff = lowCutoff;
         m_settingsMutex.lock();
         Real interpolatorBandwidth = (m_Bandwidth * 1.5f) > m_inputSampleRate ? m_inputSampleRate : (m_Bandwidth * 1.5f);
         m_interpolator.create(16, m_inputSampleRate, interpolatorBandwidth, 2.0f);
         m_interpolatorDistanceRemain = 0;
         m_interpolatorDistance = (Real) m_inputSampleRate / (Real) m_audioSampleRate;
         SSBFilter->create_filter(m_LowCutoff / (float) m_audioSampleRate, m_Bandwidth / (float) m_audioSampleRate);
         DSBFilter->create_dsb_filter((2.0f * m_Bandwidth) / (float) m_audioSampleRate);
         m_settingsMutex.unlock();
     }
     if ((m_settings.m_volume != settings.m_volume) || force)
     {
         reverseAPIKeys.append("volume");
         m_volume = settings.m_volume;
         m_volume /= 4.0; // for 3276.8
     }
     if ((m_settings.m_agcTimeLog2 != settings.m_agcTimeLog2) || force) {
         reverseAPIKeys.append("agcTimeLog2");
     }
     if ((m_settings.m_agcPowerThreshold != settings.m_agcPowerThreshold) || force) {
         reverseAPIKeys.append("agcPowerThreshold");
     }
     if ((m_settings.m_agcThresholdGate != settings.m_agcThresholdGate) || force) {
         reverseAPIKeys.append("agcThresholdGate");
     }
     if ((m_settings.m_agcClamping != settings.m_agcClamping) || force) {
         reverseAPIKeys.append("agcClamping");
     }
     if ((m_settings.m_agcTimeLog2 != settings.m_agcTimeLog2) ||
         (m_settings.m_agcPowerThreshold != settings.m_agcPowerThreshold) ||
         (m_settings.m_agcThresholdGate != settings.m_agcThresholdGate) ||
         (m_settings.m_agcClamping != settings.m_agcClamping) || force)
     {
         int agcNbSamples = (m_audioSampleRate / 1000) * (1<<settings.m_agcTimeLog2);
         m_agc.setThresholdEnable(settings.m_agcPowerThreshold != -SSBDemodSettings::m_minPowerThresholdDB);
         double agcPowerThreshold = CalcDb::powerFromdB(settings.m_agcPowerThreshold) * (SDR_RX_SCALED*SDR_RX_SCALED);
         int agcThresholdGate = (m_audioSampleRate / 1000) * settings.m_agcThresholdGate; // ms
         bool agcClamping = settings.m_agcClamping;
         if (m_agcNbSamples != agcNbSamples)
         {
             m_settingsMutex.lock();
             m_agc.resize(agcNbSamples, agcNbSamples/2, agcTarget);
             m_agc.setStepDownDelay(agcNbSamples);
             m_agcNbSamples = agcNbSamples;
             m_settingsMutex.unlock();
         }
         if (m_agcPowerThreshold != agcPowerThreshold)
         {
             m_agc.setThreshold(agcPowerThreshold);
             m_agcPowerThreshold = agcPowerThreshold;
         }
         if (m_agcThresholdGate != agcThresholdGate)
         {
             m_agc.setGate(agcThresholdGate);
             m_agcThresholdGate = agcThresholdGate;
         }
         if (m_agcClamping != agcClamping)
         {
             m_agc.setClamping(agcClamping);
             m_agcClamping = agcClamping;
         }
         qDebug() << "SBDemod::applySettings: AGC:"
             << " agcNbSamples: " << agcNbSamples
             << " agcPowerThreshold: " << agcPowerThreshold
             << " agcThresholdGate: " << agcThresholdGate
             << " agcClamping: " << agcClamping;
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force)
     {
         reverseAPIKeys.append("audioDeviceName");
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getOutputDeviceIndex(settings.m_audioDeviceName);
         audioDeviceManager->addAudioSink(&m_audioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getOutputSampleRate(audioDeviceIndex);
         if (m_audioSampleRate != audioSampleRate) {
             applyAudioSampleRate(audioSampleRate);
         }
     }
     if ((m_settings.m_spanLog2 != settings.m_spanLog2) || force) {
         reverseAPIKeys.append("spanLog2");
     }
     if ((m_settings.m_audioBinaural != settings.m_audioBinaural) || force) {
         reverseAPIKeys.append("audioBinaural");
     }
     if ((m_settings.m_audioFlipChannels != settings.m_audioFlipChannels) || force) {
         reverseAPIKeys.append("audioFlipChannels");
     }
     if ((m_settings.m_dsb != settings.m_dsb) || force) {
         reverseAPIKeys.append("dsb");
     }
     if ((m_settings.m_audioMute != settings.m_audioMute) || force) {
         reverseAPIKeys.append("audioMute");
     }
     if ((m_settings.m_agc != settings.m_agc) || force) {
         reverseAPIKeys.append("agc");
     }
     m_spanLog2 = settings.m_spanLog2;
     m_audioBinaual = settings.m_audioBinaural;
     m_audioFlipChannels = settings.m_audioFlipChannels;
     m_dsb = settings.m_dsb;
     m_audioMute = settings.m_audioMute;
     m_agcActive = settings.m_agc;
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
configure()
void SSBDemod::configure (MessageQueue * messageQueue, Real Bandwidth, Real LowCutoff, Real volume, int spanLog2, bool audioBinaural, bool audioFlipChannels, bool dsb, bool audioMute, bool agc, bool agcClamping, int agcTimeLog2, int agcPowerThreshold, int agcThresholdGate)
Definition at line 125 of file ssbdemod.cpp.
References SSBDemod::MsgConfigureSSBDemodPrivate::create(), and MessageQueue::push().
Referenced by setSampleSink().
 {
     Message* cmd = MsgConfigureSSBDemodPrivate::create(
             Bandwidth,
             LowCutoff,
             volume,
             spanLog2,
             audioBinaural,
             audioFlipChannel,
             dsb,
             audioMute,
             agc,
             agcClamping,
             agcTimeLog2,
             agcPowerThreshold,
             agcThresholdGate);
     messageQueue->push(cmd);
 }
deserialize()
bool SSBDemod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 652 of file ssbdemod.cpp.
References SSBDemod::MsgConfigureSSBDemod::create(), SSBDemodSettings::deserialize(), BasebandSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and SSBDemodSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureSSBDemod *msg = MsgConfigureSSBDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureSSBDemod *msg = MsgConfigureSSBDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void SSBDemod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 99 of file ssbdemod.h.
 { delete this; }
feed()
void SSBDemod::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool positiveOnly) virtual
Implements BasebandSampleSink.
Definition at line 157 of file ssbdemod.cpp.
References Interpolator::decimate(), Interpolator::interpolate(), m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_nco, m_settingsMutex, NCOF::nextIQ(), and processOneSample().
Referenced by setSampleSink().
 {
     (void) positiveOnly;
     Complex ci;
     m_settingsMutex.lock();
     for(SampleVector::const_iterator it = begin; it < end; ++it)
     {
         Complex c(it->real(), it->imag());
         c *= m_nco.nextIQ();
         if (m_interpolatorDistance < 1.0f) // interpolate
         {
             while (!m_interpolator.interpolate(&m_interpolatorDistanceRemain, c, &ci))
             {
                 processOneSample(ci);
                 m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
         }
         else
         {
             if (m_interpolator.decimate(&m_interpolatorDistanceRemain, c, &ci))
             {
                 processOneSample(ci);
                 m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
         }
     }
     m_settingsMutex.unlock();
 }
getAudioActive()
bool SSBDemod::getAudioActive () const inline
Definition at line 142 of file ssbdemod.h.
References m_audioActive.
Referenced by SSBDemodGUI::tick().
 { return m_audioActive; }
getAudioSampleRate()
uint32_t SSBDemod::getAudioSampleRate () const inline
Definition at line 139 of file ssbdemod.h.
References m_audioSampleRate.
Referenced by SSBDemodGUI::applyBandwidths(), SSBDemodGUI::applySettings(), SSBDemodGUI::handleMessage(), and SSBDemodGUI::spanLog2Limit().
 { return m_audioSampleRate; }
getCenterFrequency()
virtual qint64 SSBDemod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 124 of file ssbdemod.h.
References deserialize(), SSBDemodSettings::m_inputFrequencyOffset, SSBDemod::MsgConfigureSSBDemod::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getIdentifier()
virtual void SSBDemod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 122 of file ssbdemod.h.
 { id = objectName(); }
getInputSampleRate()
uint32_t SSBDemod::getInputSampleRate () const inline
Definition at line 140 of file ssbdemod.h.
References m_inputSampleRate.
Referenced by SSBDemodGUI::applyBandwidths(), and SSBDemodGUI::spanLog2Limit().
 { return m_inputSampleRate; }
getMagSq()
double SSBDemod::getMagSq () const inline
Definition at line 141 of file ssbdemod.h.
References m_magsq.
 { return m_magsq; }
getMagSqLevels()
void SSBDemod::getMagSqLevels (double & avg, double & peak, int & nbSamples) inline
Definition at line 144 of file ssbdemod.h.
References SSBDemod::MagSqLevelsStore::m_magsq, m_magsq, m_magsqCount, m_magSqLevelStore, SSBDemod::MagSqLevelsStore::m_magsqPeak, m_magsqPeak, m_magsqSum, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
Referenced by SSBDemodGUI::tick(), and webapiFormatChannelReport().
     {
         if (m_magsqCount > 0)
         {
             m_magsq = m_magsqSum / m_magsqCount;
             m_magSqLevelStore.m_magsq = m_magsq;
             m_magSqLevelStore.m_magsqPeak = m_magsqPeak;
         }
         avg = m_magSqLevelStore.m_magsq;
         peak = m_magSqLevelStore.m_magsqPeak;
         nbSamples = m_magsqCount == 0 ? 1 : m_magsqCount;
         m_magsqSum = 0.0f;
         m_magsqPeak = 0.0f;
         m_magsqCount = 0;
     }
getNbSinkStreams()
virtual int SSBDemod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 129 of file ssbdemod.h.
 { return 1; }
getNbSourceStreams()
virtual int SSBDemod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 130 of file ssbdemod.h.
 { return 0; }
getStreamCenterFrequency()
virtual qint64 SSBDemod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 132 of file ssbdemod.h.
References SSBDemodSettings::m_inputFrequencyOffset, and SSBDemod::MsgConfigureSSBDemod::m_settings.
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void SSBDemod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 123 of file ssbdemod.h.
References SSBDemod::MsgConfigureSSBDemod::m_settings, and SSBDemodSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool SSBDemod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 315 of file ssbdemod.cpp.
References applyAudioSampleRate(), applyChannelSettings(), applySettings(), DownChannelizer::configure(), SSBDemod::MsgConfigureChannelizer::getCenterFrequency(), SSBDemod::MsgConfigureSSBDemod::getForce(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSink::getInputMessageQueue(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), SSBDemod::MsgConfigureChannelizer::getSampleRate(), DSPConfigureAudio::getSampleRate(), SSBDemod::MsgConfigureSSBDemod::getSettings(), BasebandSampleSink::MsgThreadedSink::getThread(), BasebandSampleSink::handleMessage(), m_audioSampleRate, m_channelizer, m_sampleSink, and Message::match().
Referenced by setSampleSink().
 {
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& notif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         qDebug("SSBDemod::handleMessage: MsgChannelizerNotification: m_sampleRate");
         applyChannelSettings(notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "SSBDemod::handleMessage: MsgConfigureChannelizer: sampleRate: " << cfg.getSampleRate()
                 << " centerFrequency: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureSSBDemod::match(cmd))
     {
         MsgConfigureSSBDemod& cfg = (MsgConfigureSSBDemod&) cmd;
         qDebug("SSBDemod::handleMessage: MsgConfigureSSBDemod");
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (BasebandSampleSink::MsgThreadedSink::match(cmd))
     {
         BasebandSampleSink::MsgThreadedSink& cfg = (BasebandSampleSink::MsgThreadedSink&) cmd;
         const QThread *thread = cfg.getThread();
         qDebug("SSBDemod::handleMessage: BasebandSampleSink::MsgThreadedSink: %p", thread);
         return true;
     }
     else if (DSPConfigureAudio::match(cmd))
     {
         DSPConfigureAudio& cfg = (DSPConfigureAudio&) cmd;
         uint32_t sampleRate = cfg.getSampleRate();
         qDebug() << "SSBDemod::handleMessage: DSPConfigureAudio:"
                 << " sampleRate: " << sampleRate;
         if (sampleRate != m_audioSampleRate) {
             applyAudioSampleRate(sampleRate);
         }
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         if(m_sampleSink != 0)
         {
            return m_sampleSink->handleMessage(cmd);
         }
         else
         {
             return false;
         }
     }
 }
networkManagerFinished
void SSBDemod::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 931 of file ssbdemod.cpp.
Referenced by SSBDemod(), and ~SSBDemod().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "SSBDemod::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("SSBDemod::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
processOneSample()
void SSBDemod::processOneSample (Complex & ci) private
Definition at line 189 of file ssbdemod.cpp.
References DSBFilter, BasebandSampleSink::feed(), MagAGC::feedAndGetValue(), MagAGC::getStepDownDelay(), MagAGC::getStepValue(), i, m_agc, m_agcActive, m_audioActive, m_audioBinaual, m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioFlipChannels, m_audioMute, m_dsb, m_magsq, m_magsqCount, m_magsqPeak, m_magsqSum, m_sampleBuffer, m_sampleSink, m_spanLog2, m_squelchDelayLine, m_sum, m_undersampleCount, m_usb, m_volume, DoubleBufferFIFO< T >::readBack(), fftfilt::runDSB(), fftfilt::runSSB(), SDR_RX_SCALED, SSBFilter, AudioFifo::write(), and DoubleBufferFIFO< T >::write().
Referenced by feed().
 {
     fftfilt::cmplx *sideband;
     int n_out = 0;
     int decim = 1<<(m_spanLog2 - 1);
     unsigned char decim_mask = decim - 1; // counter LSB bit mask for decimation by 2^(m_scaleLog2 - 1)
     if (m_dsb) {
         n_out = DSBFilter->runDSB(ci, &sideband);
     } else {
         n_out = SSBFilter->runSSB(ci, &sideband, m_usb);
     }
     for (int i = 0; i < n_out; i++)
     {
         // Downsample by 2^(m_scaleLog2 - 1) for SSB band spectrum display
         // smart decimation with bit gain using float arithmetic (23 bits significand)
         m_sum += sideband[i];
         if (!(m_undersampleCount++ & decim_mask))
         {
             Real avgr = m_sum.real() / decim;
             Real avgi = m_sum.imag() / decim;
             m_magsq = (avgr * avgr + avgi * avgi) / (SDR_RX_SCALED*SDR_RX_SCALED);
             m_magsqSum += m_magsq;
             if (m_magsq > m_magsqPeak)
             {
                 m_magsqPeak = m_magsq;
             }
             m_magsqCount++;
             if (!m_dsb & !m_usb)
             { // invert spectrum for LSB
                 m_sampleBuffer.push_back(Sample(avgi, avgr));
             }
             else
             {
                 m_sampleBuffer.push_back(Sample(avgr, avgi));
             }
             m_sum.real(0.0);
             m_sum.imag(0.0);
         }
         float agcVal = m_agcActive ? m_agc.feedAndGetValue(sideband[i]) : 0.1;
         fftfilt::cmplx& delayedSample = m_squelchDelayLine.readBack(m_agc.getStepDownDelay());
         m_audioActive = delayedSample.real() != 0.0;
         m_squelchDelayLine.write(sideband[i]*agcVal);
         if (m_audioMute)
         {
             m_audioBuffer[m_audioBufferFill].r = 0;
             m_audioBuffer[m_audioBufferFill].l = 0;
         }
         else
         {
             fftfilt::cmplx z = m_agcActive ? delayedSample * m_agc.getStepValue() : delayedSample;
             if (m_audioBinaual)
             {
                 if (m_audioFlipChannels)
                 {
                     m_audioBuffer[m_audioBufferFill].r = (qint16)(z.imag() * m_volume);
                     m_audioBuffer[m_audioBufferFill].l = (qint16)(z.real() * m_volume);
                 }
                 else
                 {
                     m_audioBuffer[m_audioBufferFill].r = (qint16)(z.real() * m_volume);
                     m_audioBuffer[m_audioBufferFill].l = (qint16)(z.imag() * m_volume);
                 }
             }
             else
             {
                 Real demod = (z.real() + z.imag()) * 0.7;
                 qint16 sample = (qint16)(demod * m_volume);
                 m_audioBuffer[m_audioBufferFill].l = sample;
                 m_audioBuffer[m_audioBufferFill].r = sample;
             }
         }
         ++m_audioBufferFill;
         if (m_audioBufferFill >= m_audioBuffer.size())
         {
             uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
             if (res != m_audioBufferFill)
             {
                 qDebug("SSBDemod::feed: %u/%u samples written", res, m_audioBufferFill);
             }
             m_audioBufferFill = 0;
         }
     }
     uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
     if (res != m_audioBufferFill)
     {
         qDebug("SSBDemod::feed: %u/%u tail samples written", res, m_audioBufferFill);
     }
     m_audioBufferFill = 0;
     if (m_sampleSink != 0)
     {
         m_sampleSink->feed(m_sampleBuffer.begin(), m_sampleBuffer.end(), !m_dsb);
     }
     m_sampleBuffer.clear();
 }
serialize()
QByteArray SSBDemod::serialize () const virtual
Implements ChannelAPI.
Definition at line 647 of file ssbdemod.cpp.
References m_settings, and SSBDemodSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
setSampleSink()
void SSBDemod::setSampleSink (BasebandSampleSink * sampleSink) inline
Definition at line 100 of file ssbdemod.h.
References configure(), feed(), handleMessage(), m_sampleSink, start(), and stop().
Referenced by SSBDemodGUI::SSBDemodGUI().
 { m_sampleSink = sampleSink; }
start()
void SSBDemod::start () virtual
Implements BasebandSampleSink.
Definition at line 306 of file ssbdemod.cpp.
References applyChannelSettings(), m_inputFrequencyOffset, and m_inputSampleRate.
Referenced by setSampleSink().
 {
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void SSBDemod::stop () virtual
Implements BasebandSampleSink.
Definition at line 311 of file ssbdemod.cpp.
Referenced by setSampleSink().
 {
 }
webapiFormatChannelReport()
void SSBDemod::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 836 of file ssbdemod.cpp.
References CalcDb::dbPower(), getMagSqLevels(), SWGSDRangel::SWGChannelReport::getSsbDemodReport(), m_audioActive, m_audioSampleRate, m_inputSampleRate, SWGSDRangel::SWGSSBDemodReport::setAudioSampleRate(), SWGSDRangel::SWGSSBDemodReport::setChannelPowerDb(), SWGSDRangel::SWGSSBDemodReport::setChannelSampleRate(), and SWGSDRangel::SWGSSBDemodReport::setSquelch().
Referenced by webapiReportGet().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     response.getSsbDemodReport()->setChannelPowerDb(CalcDb::dbPower(magsqAvg));
     response.getSsbDemodReport()->setSquelch(m_audioActive ? 1 : 0);
     response.getSsbDemodReport()->setAudioSampleRate(m_audioSampleRate);
     response.getSsbDemodReport()->setChannelSampleRate(m_inputSampleRate);
 }
webapiFormatChannelSettings()
void SSBDemod::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const SSBDemodSettings & settings) private
Definition at line 792 of file ssbdemod.cpp.
References SWGSDRangel::SWGSSBDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGSSBDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGChannelSettings::getSsbDemodSettings(), SWGSDRangel::SWGSSBDemodSettings::getTitle(), SSBDemodSettings::m_agc, SSBDemodSettings::m_agcClamping, SSBDemodSettings::m_agcPowerThreshold, SSBDemodSettings::m_agcThresholdGate, SSBDemodSettings::m_agcTimeLog2, SSBDemodSettings::m_audioBinaural, SSBDemodSettings::m_audioDeviceName, SSBDemodSettings::m_audioFlipChannels, SSBDemodSettings::m_audioMute, SSBDemodSettings::m_dsb, SSBDemodSettings::m_inputFrequencyOffset, SSBDemodSettings::m_lowCutoff, SSBDemodSettings::m_reverseAPIAddress, SSBDemodSettings::m_reverseAPIChannelIndex, SSBDemodSettings::m_reverseAPIDeviceIndex, SSBDemodSettings::m_reverseAPIPort, SSBDemodSettings::m_rfBandwidth, SSBDemodSettings::m_rgbColor, SSBDemodSettings::m_spanLog2, SSBDemodSettings::m_title, SSBDemodSettings::m_useReverseAPI, SSBDemodSettings::m_volume, SWGSDRangel::SWGSSBDemodSettings::setAgc(), SWGSDRangel::SWGSSBDemodSettings::setAgcClamping(), SWGSDRangel::SWGSSBDemodSettings::setAgcPowerThreshold(), SWGSDRangel::SWGSSBDemodSettings::setAgcThresholdGate(), SWGSDRangel::SWGSSBDemodSettings::setAgcTimeLog2(), SWGSDRangel::SWGSSBDemodSettings::setAudioBinaural(), SWGSDRangel::SWGSSBDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGSSBDemodSettings::setAudioFlipChannels(), SWGSDRangel::SWGSSBDemodSettings::setAudioMute(), SWGSDRangel::SWGSSBDemodSettings::setDsb(), SWGSDRangel::SWGSSBDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGSSBDemodSettings::setLowCutoff(), SWGSDRangel::SWGSSBDemodSettings::setReverseApiAddress(), SWGSDRangel::SWGSSBDemodSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGSSBDemodSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGSSBDemodSettings::setReverseApiPort(), SWGSDRangel::SWGSSBDemodSettings::setRfBandwidth(), SWGSDRangel::SWGSSBDemodSettings::setRgbColor(), SWGSDRangel::SWGSSBDemodSettings::setSpanLog2(), SWGSDRangel::SWGSSBDemodSettings::setTitle(), SWGSDRangel::SWGSSBDemodSettings::setUseReverseApi(), and SWGSDRangel::SWGSSBDemodSettings::setVolume().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getSsbDemodSettings()->setAudioMute(settings.m_audioMute ? 1 : 0);
     response.getSsbDemodSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getSsbDemodSettings()->setRfBandwidth(settings.m_rfBandwidth);
     response.getSsbDemodSettings()->setLowCutoff(settings.m_lowCutoff);
     response.getSsbDemodSettings()->setVolume(settings.m_volume);
     response.getSsbDemodSettings()->setSpanLog2(settings.m_spanLog2);
     response.getSsbDemodSettings()->setAudioBinaural(settings.m_audioBinaural ? 1 : 0);
     response.getSsbDemodSettings()->setAudioFlipChannels(settings.m_audioFlipChannels ? 1 : 0);
     response.getSsbDemodSettings()->setDsb(settings.m_dsb ? 1 : 0);
     response.getSsbDemodSettings()->setAudioMute(settings.m_audioMute ? 1 : 0);
     response.getSsbDemodSettings()->setAgc(settings.m_agc ? 1 : 0);
     response.getSsbDemodSettings()->setAgcClamping(settings.m_agcClamping ? 1 : 0);
     response.getSsbDemodSettings()->setAgcTimeLog2(settings.m_agcTimeLog2);
     response.getSsbDemodSettings()->setAgcPowerThreshold(settings.m_agcPowerThreshold);
     response.getSsbDemodSettings()->setAgcThresholdGate(settings.m_agcThresholdGate);
     response.getSsbDemodSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getSsbDemodSettings()->getTitle()) {
         *response.getSsbDemodSettings()->getTitle() = settings.m_title;
     } else {
         response.getSsbDemodSettings()->setTitle(new QString(settings.m_title));
     }
     if (response.getSsbDemodSettings()->getAudioDeviceName()) {
         *response.getSsbDemodSettings()->getAudioDeviceName() = settings.m_audioDeviceName;
     } else {
         response.getSsbDemodSettings()->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     response.getSsbDemodSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getSsbDemodSettings()->getReverseApiAddress()) {
         *response.getSsbDemodSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getSsbDemodSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getSsbDemodSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getSsbDemodSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getSsbDemodSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int SSBDemod::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 781 of file ssbdemod.cpp.
References SWGSDRangel::SWGChannelReport::getSsbDemodReport(), SWGSDRangel::SWGSSBDemodReport::init(), SWGSDRangel::SWGChannelReport::setSsbDemodReport(), and webapiFormatChannelReport().
Referenced by getMagSqLevels().
 {
     (void) errorMessage;
     response.setSsbDemodReport(new SWGSDRangel::SWGSSBDemodReport());
     response.getSsbDemodReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendSettings()
void SSBDemod::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const SSBDemodSettings & settings, bool force) private
Definition at line 848 of file ssbdemod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), SWGSDRangel::SWGChannelSettings::getSsbDemodSettings(), SSBDemodSettings::m_agc, SSBDemodSettings::m_agcClamping, SSBDemodSettings::m_agcPowerThreshold, SSBDemodSettings::m_agcThresholdGate, SSBDemodSettings::m_agcTimeLog2, SSBDemodSettings::m_audioBinaural, SSBDemodSettings::m_audioDeviceName, SSBDemodSettings::m_audioFlipChannels, SSBDemodSettings::m_audioMute, SSBDemodSettings::m_dsb, SSBDemodSettings::m_inputFrequencyOffset, SSBDemodSettings::m_lowCutoff, m_networkManager, m_networkRequest, SSBDemodSettings::m_reverseAPIAddress, SSBDemodSettings::m_reverseAPIChannelIndex, SSBDemodSettings::m_reverseAPIDeviceIndex, SSBDemodSettings::m_reverseAPIPort, SSBDemodSettings::m_rfBandwidth, SSBDemodSettings::m_rgbColor, SSBDemodSettings::m_spanLog2, SSBDemodSettings::m_title, SSBDemodSettings::m_volume, SWGSDRangel::SWGSSBDemodSettings::setAgc(), SWGSDRangel::SWGSSBDemodSettings::setAgcClamping(), SWGSDRangel::SWGSSBDemodSettings::setAgcPowerThreshold(), SWGSDRangel::SWGSSBDemodSettings::setAgcThresholdGate(), SWGSDRangel::SWGSSBDemodSettings::setAgcTimeLog2(), SWGSDRangel::SWGSSBDemodSettings::setAudioBinaural(), SWGSDRangel::SWGSSBDemodSettings::setAudioDeviceName(), SWGSDRangel::SWGSSBDemodSettings::setAudioFlipChannels(), SWGSDRangel::SWGSSBDemodSettings::setAudioMute(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGSSBDemodSettings::setDsb(), SWGSDRangel::SWGSSBDemodSettings::setInputFrequencyOffset(), SWGSDRangel::SWGSSBDemodSettings::setLowCutoff(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGSSBDemodSettings::setRfBandwidth(), SWGSDRangel::SWGSSBDemodSettings::setRgbColor(), SWGSDRangel::SWGSSBDemodSettings::setSpanLog2(), SWGSDRangel::SWGChannelSettings::setSsbDemodSettings(), SWGSDRangel::SWGSSBDemodSettings::setTitle(), and SWGSDRangel::SWGSSBDemodSettings::setVolume().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(0); // single sink (Rx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("SSBDemod"));
     swgChannelSettings->setSsbDemodSettings(new SWGSDRangel::SWGSSBDemodSettings());
     SWGSDRangel::SWGSSBDemodSettings *swgSSBDemodSettings = swgChannelSettings->getSsbDemodSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgSSBDemodSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("rfBandwidth") || force) {
         swgSSBDemodSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (channelSettingsKeys.contains("lowCutoff") || force) {
         swgSSBDemodSettings->setLowCutoff(settings.m_lowCutoff);
     }
     if (channelSettingsKeys.contains("volume") || force) {
         swgSSBDemodSettings->setVolume(settings.m_volume);
     }
     if (channelSettingsKeys.contains("spanLog2") || force) {
         swgSSBDemodSettings->setSpanLog2(settings.m_spanLog2);
     }
     if (channelSettingsKeys.contains("audioBinaural") || force) {
         swgSSBDemodSettings->setAudioBinaural(settings.m_audioBinaural ? 1 : 0);
     }
     if (channelSettingsKeys.contains("audioFlipChannels") || force) {
         swgSSBDemodSettings->setAudioFlipChannels(settings.m_audioFlipChannels ? 1 : 0);
     }
     if (channelSettingsKeys.contains("dsb") || force) {
         swgSSBDemodSettings->setDsb(settings.m_dsb ? 1 : 0);
     }
     if (channelSettingsKeys.contains("audioMute") || force) {
         swgSSBDemodSettings->setAudioMute(settings.m_audioMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("agc") || force) {
         swgSSBDemodSettings->setAgc(settings.m_agc ? 1 : 0);
     }
     if (channelSettingsKeys.contains("agcClamping") || force) {
         swgSSBDemodSettings->setAgcClamping(settings.m_agcClamping ? 1 : 0);
     }
     if (channelSettingsKeys.contains("agcTimeLog2") || force) {
         swgSSBDemodSettings->setAgcTimeLog2(settings.m_agcTimeLog2);
     }
     if (channelSettingsKeys.contains("agcPowerThreshold") || force) {
         swgSSBDemodSettings->setAgcPowerThreshold(settings.m_agcPowerThreshold);
     }
     if (channelSettingsKeys.contains("agcThresholdGate") || force) {
         swgSSBDemodSettings->setAgcThresholdGate(settings.m_agcThresholdGate);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgSSBDemodSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgSSBDemodSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("audioDeviceName") || force) {
         swgSSBDemodSettings->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int SSBDemod::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 669 of file ssbdemod.cpp.
References SWGSDRangel::SWGChannelSettings::getSsbDemodSettings(), SWGSDRangel::SWGSSBDemodSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setSsbDemodSettings(), and webapiFormatChannelSettings().
Referenced by getMagSqLevels().
 {
     (void) errorMessage;
     response.setSsbDemodSettings(new SWGSDRangel::SWGSSBDemodSettings());
     response.getSsbDemodSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int SSBDemod::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 680 of file ssbdemod.cpp.
References SSBDemod::MsgConfigureSSBDemod::create(), SSBDemod::MsgConfigureChannelizer::create(), SWGSDRangel::SWGSSBDemodSettings::getAgc(), SWGSDRangel::SWGSSBDemodSettings::getAgcClamping(), SWGSDRangel::SWGSSBDemodSettings::getAgcPowerThreshold(), SWGSDRangel::SWGSSBDemodSettings::getAgcThresholdGate(), SWGSDRangel::SWGSSBDemodSettings::getAgcTimeLog2(), SWGSDRangel::SWGSSBDemodSettings::getAudioBinaural(), SWGSDRangel::SWGSSBDemodSettings::getAudioDeviceName(), SWGSDRangel::SWGSSBDemodSettings::getAudioFlipChannels(), SWGSDRangel::SWGSSBDemodSettings::getAudioMute(), SWGSDRangel::SWGSSBDemodSettings::getDsb(), SWGSDRangel::SWGSSBDemodSettings::getInputFrequencyOffset(), SWGSDRangel::SWGSSBDemodSettings::getLowCutoff(), SWGSDRangel::SWGSSBDemodSettings::getReverseApiAddress(), SWGSDRangel::SWGSSBDemodSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGSSBDemodSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGSSBDemodSettings::getReverseApiPort(), SWGSDRangel::SWGSSBDemodSettings::getRfBandwidth(), SWGSDRangel::SWGSSBDemodSettings::getRgbColor(), SWGSDRangel::SWGSSBDemodSettings::getSpanLog2(), SWGSDRangel::SWGChannelSettings::getSsbDemodSettings(), SWGSDRangel::SWGSSBDemodSettings::getTitle(), SWGSDRangel::SWGSSBDemodSettings::getUseReverseApi(), SWGSDRangel::SWGSSBDemodSettings::getVolume(), SSBDemodSettings::m_agc, SSBDemodSettings::m_agcClamping, SSBDemodSettings::m_agcPowerThreshold, SSBDemodSettings::m_agcThresholdGate, SSBDemodSettings::m_agcTimeLog2, SSBDemodSettings::m_audioBinaural, SSBDemodSettings::m_audioDeviceName, SSBDemodSettings::m_audioFlipChannels, SSBDemodSettings::m_audioMute, m_audioSampleRate, SSBDemodSettings::m_dsb, BasebandSampleSink::m_guiMessageQueue, SSBDemodSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, SSBDemodSettings::m_lowCutoff, SSBDemodSettings::m_reverseAPIAddress, SSBDemodSettings::m_reverseAPIChannelIndex, SSBDemodSettings::m_reverseAPIDeviceIndex, SSBDemodSettings::m_reverseAPIPort, SSBDemodSettings::m_rfBandwidth, SSBDemodSettings::m_rgbColor, m_settings, SSBDemodSettings::m_spanLog2, SSBDemodSettings::m_title, SSBDemodSettings::m_useReverseAPI, SSBDemodSettings::m_volume, MessageQueue::push(), and webapiFormatChannelSettings().
Referenced by getMagSqLevels().
 {
     (void) errorMessage;
     SSBDemodSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getSsbDemodSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getSsbDemodSettings()->getRfBandwidth();
     }
     if (channelSettingsKeys.contains("lowCutoff")) {
         settings.m_lowCutoff = response.getSsbDemodSettings()->getLowCutoff();
     }
     if (channelSettingsKeys.contains("volume")) {
         settings.m_volume = response.getSsbDemodSettings()->getVolume();
     }
     if (channelSettingsKeys.contains("spanLog2")) {
         settings.m_spanLog2 = response.getSsbDemodSettings()->getSpanLog2();
     }
     if (channelSettingsKeys.contains("audioBinaural")) {
         settings.m_audioBinaural = response.getSsbDemodSettings()->getAudioBinaural() != 0;
     }
     if (channelSettingsKeys.contains("audioFlipChannels")) {
         settings.m_audioFlipChannels = response.getSsbDemodSettings()->getAudioFlipChannels() != 0;
     }
     if (channelSettingsKeys.contains("dsb")) {
         settings.m_dsb = response.getSsbDemodSettings()->getDsb() != 0;
     }
     if (channelSettingsKeys.contains("audioMute")) {
         settings.m_audioMute = response.getSsbDemodSettings()->getAudioMute() != 0;
     }
     if (channelSettingsKeys.contains("agc")) {
         settings.m_agc = response.getSsbDemodSettings()->getAgc() != 0;
     }
     if (channelSettingsKeys.contains("agcClamping")) {
         settings.m_agcClamping = response.getSsbDemodSettings()->getAgcClamping() != 0;
     }
     if (channelSettingsKeys.contains("agcTimeLog2")) {
         settings.m_agcTimeLog2 = response.getSsbDemodSettings()->getAgcTimeLog2();
     }
     if (channelSettingsKeys.contains("agcPowerThreshold")) {
         settings.m_agcPowerThreshold = response.getSsbDemodSettings()->getAgcPowerThreshold();
     }
     if (channelSettingsKeys.contains("agcThresholdGate")) {
         settings.m_agcThresholdGate = response.getSsbDemodSettings()->getAgcThresholdGate();
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getSsbDemodSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getSsbDemodSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("audioDeviceName")) {
         settings.m_audioDeviceName = *response.getSsbDemodSettings()->getAudioDeviceName();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getSsbDemodSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getSsbDemodSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getSsbDemodSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getSsbDemodSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getSsbDemodSettings()->getReverseApiChannelIndex();
     }
     if (frequencyOffsetChanged)
     {
         MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
                 m_audioSampleRate, settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(channelConfigMsg);
     }
     MsgConfigureSSBDemod *msg = MsgConfigureSSBDemod::create(settings, force);
     m_inputMessageQueue.push(msg);
     qDebug("SSBDemod::webapiSettingsPutPatch: forward to GUI: %p", m_guiMessageQueue);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureSSBDemod *msgToGUI = MsgConfigureSSBDemod::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
DSBFilter
fftfilt* SSBDemod::DSBFilter private
Definition at line 320 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), processOneSample(), SSBDemod(), and ~SSBDemod().
m_agc
MagAGC SSBDemod::m_agc private
Definition at line 306 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), SSBDemod::MsgConfigureSSBDemodPrivate::getAGC(), processOneSample(), and SSBDemod().
m_agcActive
bool SSBDemod::m_agcActive private
Definition at line 307 of file ssbdemod.h.
Referenced by applySettings(), and processOneSample().
m_agcClamping
bool SSBDemod::m_agcClamping private
Definition at line 308 of file ssbdemod.h.
Referenced by applySettings(), SSBDemod::MsgConfigureSSBDemodPrivate::getAGCClamping(), and SSBDemod().
m_agcNbSamples
int SSBDemod::m_agcNbSamples private
number of audio (48 kHz) samples for AGC averaging
Definition at line 309 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), and applySettings().
m_agcPowerThreshold
double SSBDemod::m_agcPowerThreshold private
AGC power threshold (linear)
Definition at line 310 of file ssbdemod.h.
Referenced by applySettings(), and SSBDemod::MsgConfigureSSBDemodPrivate::getAGCPowerThershold().
m_agcThresholdGate
int SSBDemod::m_agcThresholdGate private
Gate length in number of samples befor threshold triggers.
Definition at line 311 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), and SSBDemod::MsgConfigureSSBDemodPrivate::getAGCThersholdGate().
m_audioActive
bool SSBDemod::m_audioActive private
True if an audio signal is produced (no AGC or AGC and above threshold)
Definition at line 313 of file ssbdemod.h.
Referenced by getAudioActive(), processOneSample(), and webapiFormatChannelReport().
m_audioBinaual
bool SSBDemod::m_audioBinaual private
Definition at line 296 of file ssbdemod.h.
Referenced by applySettings(), and processOneSample().
m_audioBuffer
AudioVector SSBDemod::m_audioBuffer private
Definition at line 325 of file ssbdemod.h.
Referenced by processOneSample(), and SSBDemod().
m_audioBufferFill
uint SSBDemod::m_audioBufferFill private
Definition at line 326 of file ssbdemod.h.
Referenced by processOneSample(), and SSBDemod().
m_audioFifo
AudioFifo SSBDemod::m_audioFifo private
Definition at line 327 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), processOneSample(), SSBDemod(), and ~SSBDemod().
m_audioFlipChannels
bool SSBDemod::m_audioFlipChannels private
Definition at line 297 of file ssbdemod.h.
Referenced by applySettings(), SSBDemod::MsgConfigureSSBDemodPrivate::getAudioFlipChannels(), and processOneSample().
m_audioMute
bool SSBDemod::m_audioMute private
Definition at line 300 of file ssbdemod.h.
Referenced by applySettings(), SSBDemod::MsgConfigureSSBDemodPrivate::getAudioMute(), and processOneSample().
m_audioSampleRate
quint32 SSBDemod::m_audioSampleRate private
Definition at line 328 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), getAudioSampleRate(), handleMessage(), SSBDemod(), webapiFormatChannelReport(), and webapiSettingsPutPatch().
m_Bandwidth
Real SSBDemod::m_Bandwidth private
Definition at line 288 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), SSBDemod::MsgConfigureSSBDemodPrivate::getBandwidth(), and SSBDemod().
m_channelId
const QString SSBDemod::m_channelId = "SSBDemod" static
Definition at line 177 of file ssbdemod.h.
Referenced by SSBPlugin::initPlugin(), and SSBDemod().
m_channelIdURI
const QString SSBDemod::m_channelIdURI = "sdrangel.channel.ssbdemod" static
Definition at line 176 of file ssbdemod.h.
Referenced by SSBPlugin::initPlugin(), and SSBDemodGUI::SSBDemodGUI().
m_channelizer
DownChannelizer* SSBDemod::m_channelizer private
Definition at line 285 of file ssbdemod.h.
Referenced by handleMessage(), SSBDemod(), and ~SSBDemod().
m_deviceAPI
DeviceAPI* SSBDemod::m_deviceAPI private
Definition at line 283 of file ssbdemod.h.
Referenced by SSBDemod(), and ~SSBDemod().
m_dsb
bool SSBDemod::m_dsb private
Definition at line 299 of file ssbdemod.h.
Referenced by applySettings(), SSBDemod::MsgConfigureSSBDemodPrivate::getDSB(), and processOneSample().
m_inputFrequencyOffset
int SSBDemod::m_inputFrequencyOffset private
Definition at line 295 of file ssbdemod.h.
Referenced by applyChannelSettings(), SSBDemod(), and start().
m_inputSampleRate
int SSBDemod::m_inputSampleRate private
Definition at line 294 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), getInputSampleRate(), SSBDemod(), start(), and webapiFormatChannelReport().
m_interpolator
Interpolator SSBDemod::m_interpolator private
Definition at line 316 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_interpolatorDistance
Real SSBDemod::m_interpolatorDistance private
Definition at line 317 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_interpolatorDistanceRemain
Real SSBDemod::m_interpolatorDistanceRemain private
Definition at line 318 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_LowCutoff
Real SSBDemod::m_LowCutoff private
Definition at line 289 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), SSBDemod::MsgConfigureSSBDemodPrivate::getLoCutoff(), and SSBDemod().
m_magsq
double SSBDemod::m_magsq private
Definition at line 301 of file ssbdemod.h.
Referenced by getMagSq(), getMagSqLevels(), processOneSample(), and SSBDemod().
m_magsqCount
int SSBDemod::m_magsqCount private
Definition at line 304 of file ssbdemod.h.
Referenced by getMagSqLevels(), processOneSample(), and SSBDemod().
m_magSqLevelStore
MagSqLevelsStore SSBDemod::m_magSqLevelStore private
Definition at line 305 of file ssbdemod.h.
Referenced by getMagSqLevels().
m_magsqPeak
double SSBDemod::m_magsqPeak private
Definition at line 303 of file ssbdemod.h.
Referenced by getMagSqLevels(), processOneSample(), and SSBDemod().
m_magsqSum
double SSBDemod::m_magsqSum private
Definition at line 302 of file ssbdemod.h.
Referenced by getMagSqLevels(), processOneSample(), and SSBDemod().
m_nco
NCOF SSBDemod::m_nco private
Definition at line 315 of file ssbdemod.h.
Referenced by applyChannelSettings(), and feed().
m_networkManager
QNetworkAccessManager* SSBDemod::m_networkManager private
Definition at line 330 of file ssbdemod.h.
Referenced by SSBDemod(), webapiReverseSendSettings(), and ~SSBDemod().
m_networkRequest
QNetworkRequest SSBDemod::m_networkRequest private
Definition at line 331 of file ssbdemod.h.
Referenced by webapiReverseSendSettings().
m_sampleBuffer
SampleVector SSBDemod::m_sampleBuffer private
Definition at line 323 of file ssbdemod.h.
Referenced by processOneSample().
m_sampleSink
BasebandSampleSink* SSBDemod::m_sampleSink private
Definition at line 322 of file ssbdemod.h.
Referenced by handleMessage(), processOneSample(), and setSampleSink().
m_settings
SSBDemodSettings SSBDemod::m_settings private
Definition at line 286 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), deserialize(), serialize(), SSBDemod(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex SSBDemod::m_settingsMutex private
Definition at line 333 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and feed().
m_spanLog2
int SSBDemod::m_spanLog2 private
Definition at line 291 of file ssbdemod.h.
Referenced by applySettings(), SSBDemod::MsgConfigureSSBDemodPrivate::getSpanLog2(), processOneSample(), and SSBDemod().
m_squelchDelayLine
DoubleBufferFIFO<fftfilt::cmplx> SSBDemod::m_squelchDelayLine private
Definition at line 312 of file ssbdemod.h.
Referenced by processOneSample().
m_sum
fftfilt::cmplx SSBDemod::m_sum private
Definition at line 292 of file ssbdemod.h.
Referenced by processOneSample(), and SSBDemod().
m_threadedChannelizer
ThreadedBasebandSampleSink* SSBDemod::m_threadedChannelizer private
Definition at line 284 of file ssbdemod.h.
Referenced by SSBDemod(), and ~SSBDemod().
m_undersampleCount
int SSBDemod::m_undersampleCount private
Definition at line 293 of file ssbdemod.h.
Referenced by processOneSample(), and SSBDemod().
m_usb
bool SSBDemod::m_usb private
Definition at line 298 of file ssbdemod.h.
Referenced by applySettings(), processOneSample(), and SSBDemod().
m_volume
Real SSBDemod::m_volume private
Definition at line 290 of file ssbdemod.h.
Referenced by applySettings(), SSBDemod::MsgConfigureSSBDemodPrivate::getVolume(), processOneSample(), and SSBDemod().
SSBFilter
fftfilt* SSBDemod::SSBFilter private
Definition at line 319 of file ssbdemod.h.
Referenced by applyAudioSampleRate(), applySettings(), processOneSample(), SSBDemod(), and ~SSBDemod().
The documentation for this class was generated from the following files:
plugins/channelrx/demodssb/ssbdemod.h
plugins/channelrx/demodssb/ssbdemod.cpp