SDRAngel: DeviceUISet Class Reference
DeviceUISet Class Reference
#include <deviceuiset.h>
Classes
struct ChannelInstanceRegistration
Public Member Functions
DeviceUISet (int tabIndex, int deviceType, QTimer &timer)
~DeviceUISet ()
GLSpectrum * getSpectrum ()
Direct spectrum getter.
void addChannelMarker (ChannelMarker *channelMarker)
Add channel marker to spectrum.
void addRollupWidget (QWidget *widget)
Add rollup widget to channel window.
int getNumberOfRxChannels () const
int getNumberOfTxChannels () const
void registerRxChannelInstance (const QString &channelName, PluginInstanceGUI *pluginGUI)
void registerTxChannelInstance (const QString &channelName, PluginInstanceGUI *pluginGUI)
void removeRxChannelInstance (PluginInstanceGUI *pluginGUI)
void removeTxChannelInstance (PluginInstanceGUI *pluginGUI)
void freeRxChannels ()
void freeTxChannels ()
void deleteRxChannel (int channelIndex)
void deleteTxChannel (int channelIndex)
void loadRxChannelSettings (const Preset *preset, PluginAPI *pluginAPI)
void saveRxChannelSettings (Preset *preset)
void loadTxChannelSettings (const Preset *preset, PluginAPI *pluginAPI)
void saveTxChannelSettings (Preset *preset)
void setNumberOfAvailableRxChannels (int number)
void setNumberOfAvailableTxChannels (int number)
void setNumberOfAvailableMIMOChannels (int number)
int getNumberOfAvailableRxChannels () const
int getNumberOfAvailableTxChannels () const
int getNumberOfAvailableMIMOChannels () const
Public Attributes
SpectrumVis * m_spectrumVis
GLSpectrum * m_spectrum
GLSpectrumGUI * m_spectrumGUI
ChannelWindow * m_channelWindow
SamplingDeviceControl * m_samplingDeviceControl
DeviceAPI * m_deviceAPI
DSPDeviceSourceEngine * m_deviceSourceEngine
DSPDeviceSinkEngine * m_deviceSinkEngine
DSPDeviceMIMOEngine * m_deviceMIMOEngine
QByteArray m_mainWindowState
Private Types
typedef QList< ChannelInstanceRegistration > ChannelInstanceRegistrations
Private Member Functions
void renameRxChannelInstances ()
void renameTxChannelInstances ()
bool compareRxChannelURIs (const QString &registerdChannelURI, const QString &xChannelURI)
Private Attributes
ChannelInstanceRegistrations m_rxChannelInstanceRegistrations
ChannelInstanceRegistrations m_txChannelInstanceRegistrations
int m_deviceTabIndex
int m_nbAvailableRxChannels
Number of Rx channels available for selection.
int m_nbAvailableTxChannels
Number of Tx channels available for selection.
int m_nbAvailableMIMOChannels
Number of MIMO channels available for selection.
Detailed Description
Definition at line 40 of file deviceuiset.h.
Member Typedef Documentation
ChannelInstanceRegistrations
typedef QList<ChannelInstanceRegistration> DeviceUISet::ChannelInstanceRegistrations private
Definition at line 103 of file deviceuiset.h.
Constructor & Destructor Documentation
DeviceUISet()
DeviceUISet::DeviceUISet (int tabIndex, int deviceType, QTimer & timer)
Definition at line 34 of file deviceuiset.cpp.
References GLSpectrum::connectTimer(), BasebandSampleSink::getInputMessageQueue(), m_channelWindow, m_deviceAPI, m_deviceMIMOEngine, m_deviceSinkEngine, m_deviceSourceEngine, m_deviceTabIndex, m_nbAvailableMIMOChannels, m_nbAvailableRxChannels, m_nbAvailableTxChannels, m_samplingDeviceControl, m_spectrum, m_spectrumGUI, m_spectrumVis, SDR_RX_SCALEF, SDR_TX_SCALEF, and GLSpectrumGUI::setBuddies().
 {
     m_spectrum = new GLSpectrum;
     if ((deviceType == 0) || (deviceType == 2)) { // Single Rx or MIMO
         m_spectrumVis = new SpectrumVis(SDR_RX_SCALEF, m_spectrum);
     } else if (deviceType == 1) { // Single Tx
         m_spectrumVis = new SpectrumVis(SDR_TX_SCALEF, m_spectrum);
     }
     m_spectrum->connectTimer(timer);
     m_spectrumGUI = new GLSpectrumGUI;
     m_spectrumGUI->setBuddies(m_spectrumVis->getInputMessageQueue(), m_spectrumVis, m_spectrum);
     m_channelWindow = new ChannelWindow;
     m_samplingDeviceControl = new SamplingDeviceControl(tabIndex, deviceType);
     m_deviceAPI = nullptr;
     m_deviceSourceEngine = nullptr;
     m_deviceSinkEngine = nullptr;
     m_deviceMIMOEngine = nullptr;
     m_deviceTabIndex = tabIndex;
     m_nbAvailableRxChannels = 0;   // updated at enumeration for UI selector
     m_nbAvailableTxChannels = 0;   // updated at enumeration for UI selector
     m_nbAvailableMIMOChannels = 0; // updated at enumeration for UI selector
     // m_spectrum needs to have its font to be set since it cannot be inherited from the main window
     QFont font;
     font.setFamily(QStringLiteral("Liberation Sans"));
     font.setPointSize(9);
     m_spectrum->setFont(font);
 }
~DeviceUISet()
DeviceUISet::~DeviceUISet ()
Definition at line 63 of file deviceuiset.cpp.
References m_channelWindow, m_samplingDeviceControl, m_spectrum, m_spectrumGUI, and m_spectrumVis.
 {
     delete m_samplingDeviceControl;
     delete m_channelWindow;
     delete m_spectrumGUI;
     delete m_spectrumVis;
     delete m_spectrum;
 }
Member Function Documentation
addChannelMarker()
void DeviceUISet::addChannelMarker (ChannelMarker * channelMarker)
Add channel marker to spectrum.
Definition at line 72 of file deviceuiset.cpp.
References GLSpectrum::addChannelMarker(), and m_spectrum.
Referenced by AMDemodGUI::AMDemodGUI(), AMModGUI::AMModGUI(), ATVDemodGUI::ATVDemodGUI(), ATVModGUI::ATVModGUI(), BFMDemodGUI::BFMDemodGUI(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), DATVDemodGUI::DATVDemodGUI(), DSDDemodGUI::DSDDemodGUI(), FileSourceGUI::FileSourceGUI(), FreeDVDemodGUI::FreeDVDemodGUI(), FreeDVModGUI::FreeDVModGUI(), FreqTrackerGUI::FreqTrackerGUI(), LocalSinkGUI::LocalSinkGUI(), LocalSourceGUI::LocalSourceGUI(), LoRaDemodGUI::LoRaDemodGUI(), NFMDemodGUI::NFMDemodGUI(), NFMModGUI::NFMModGUI(), RemoteSinkGUI::RemoteSinkGUI(), RemoteSourceGUI::RemoteSourceGUI(), SSBDemodGUI::SSBDemodGUI(), SSBModGUI::SSBModGUI(), UDPSinkGUI::UDPSinkGUI(), UDPSourceGUI::UDPSourceGUI(), WFMDemodGUI::WFMDemodGUI(), and WFMModGUI::WFMModGUI().
 {
     m_spectrum->addChannelMarker(channelMarker);
 }
addRollupWidget()
void DeviceUISet::addRollupWidget (QWidget * widget)
Add rollup widget to channel window.
Definition at line 77 of file deviceuiset.cpp.
References ChannelWindow::addRollupWidget(), and m_channelWindow.
Referenced by AMDemodGUI::AMDemodGUI(), AMModGUI::AMModGUI(), ATVDemodGUI::ATVDemodGUI(), ATVModGUI::ATVModGUI(), BFMDemodGUI::BFMDemodGUI(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), DATVDemodGUI::DATVDemodGUI(), DSDDemodGUI::DSDDemodGUI(), FileSourceGUI::FileSourceGUI(), FreeDVDemodGUI::FreeDVDemodGUI(), FreeDVModGUI::FreeDVModGUI(), FreqTrackerGUI::FreqTrackerGUI(), LocalSinkGUI::LocalSinkGUI(), LocalSourceGUI::LocalSourceGUI(), LoRaDemodGUI::LoRaDemodGUI(), NFMDemodGUI::NFMDemodGUI(), NFMModGUI::NFMModGUI(), RemoteSinkGUI::RemoteSinkGUI(), RemoteSourceGUI::RemoteSourceGUI(), SSBDemodGUI::SSBDemodGUI(), SSBModGUI::SSBModGUI(), UDPSinkGUI::UDPSinkGUI(), UDPSourceGUI::UDPSourceGUI(), WFMDemodGUI::WFMDemodGUI(), and WFMModGUI::WFMModGUI().
 {
     m_channelWindow->addRollupWidget(widget);
 }
compareRxChannelURIs()
bool DeviceUISet::compareRxChannelURIs (const QString & registerdChannelURI, const QString & xChannelURI) private
Use this function to support possible older identifiers in presets
Definition at line 357 of file deviceuiset.cpp.
Referenced by loadRxChannelSettings().
 {
     if ((xChannelURI == "sdrangel.channel.chanalyzerng") || (xChannelURI == "sdrangel.channel.chanalyzer")) { // renamed ChanalyzerNG to Chanalyzer in 4.0.0
         return registerdChannelURI == "sdrangel.channel.chanalyzer";
     } else if ((xChannelURI == "de.maintech.sdrangelove.channel.am") || (xChannelURI == "sdrangel.channel.amdemod")) {
         return registerdChannelURI == "sdrangel.channel.amdemod";
     } else  if ((xChannelURI == "de.maintech.sdrangelove.channel.nfm") || (xChannelURI == "sdrangel.channel.nfmdemod")) {
         return registerdChannelURI == "sdrangel.channel.nfmdemod";
     } else  if ((xChannelURI == "de.maintech.sdrangelove.channel.ssb") || (xChannelURI == "sdrangel.channel.ssbdemod")) {
         return registerdChannelURI == "sdrangel.channel.ssbdemod";
     } else  if ((xChannelURI == "de.maintech.sdrangelove.channel.wfm") || (xChannelURI == "sdrangel.channel.wfmdemod")) {
         return registerdChannelURI == "sdrangel.channel.wfmdemod";
     } else {
         return registerdChannelURI == xChannelURI;
     }
 }
deleteRxChannel()
void DeviceUISet::deleteRxChannel (int channelIndex)
Definition at line 140 of file deviceuiset.cpp.
References m_rxChannelInstanceRegistrations, and renameRxChannelInstances().
Referenced by MainWindow::deleteChannel().
 {
     if ((channelIndex >= 0) && (channelIndex < m_rxChannelInstanceRegistrations.count()))
     {
         qDebug("DeviceUISet::deleteRxChennel: delete channel [%s] at %d",
                 qPrintable(m_rxChannelInstanceRegistrations[channelIndex].m_channelName),
                 channelIndex);
         m_rxChannelInstanceRegistrations[channelIndex].m_gui->destroy();
         m_rxChannelInstanceRegistrations.removeAt(channelIndex);
         renameRxChannelInstances();
     }
 }
deleteTxChannel()
void DeviceUISet::deleteTxChannel (int channelIndex)
Definition at line 153 of file deviceuiset.cpp.
References m_txChannelInstanceRegistrations, and renameTxChannelInstances().
Referenced by MainWindow::deleteChannel().
 {
     if ((channelIndex >= 0) && (channelIndex < m_txChannelInstanceRegistrations.count()))
     {
         qDebug("DeviceUISet::deleteTxChennel: delete channel [%s] at %d",
                 qPrintable(m_txChannelInstanceRegistrations[channelIndex].m_channelName),
                 channelIndex);
         m_txChannelInstanceRegistrations[channelIndex].m_gui->destroy();
         m_txChannelInstanceRegistrations.removeAt(channelIndex);
         renameTxChannelInstances();
     }
 }
freeRxChannels()
void DeviceUISet::freeRxChannels ()
Definition at line 122 of file deviceuiset.cpp.
References i, and m_rxChannelInstanceRegistrations.
 {
     for(int i = 0; i < m_rxChannelInstanceRegistrations.count(); i++)
     {
         qDebug("DeviceUISet::freeAll: destroying channel [%s]", qPrintable(m_rxChannelInstanceRegistrations[i].m_channelName));
         m_rxChannelInstanceRegistrations[i].m_gui->destroy();
     }
 }
freeTxChannels()
void DeviceUISet::freeTxChannels ()
Definition at line 131 of file deviceuiset.cpp.
References i, and m_txChannelInstanceRegistrations.
 {
     for(int i = 0; i < m_txChannelInstanceRegistrations.count(); i++)
     {
         qDebug("DeviceUISet::freeAll: destroying channel [%s]", qPrintable(m_txChannelInstanceRegistrations[i].m_channelName));
         m_txChannelInstanceRegistrations[i].m_gui->destroy();
     }
 }
getNumberOfAvailableMIMOChannels()
int DeviceUISet::getNumberOfAvailableMIMOChannels () const inline
Definition at line 82 of file deviceuiset.h.
 { return m_nbAvailableMIMOChannels; }
getNumberOfAvailableRxChannels()
int DeviceUISet::getNumberOfAvailableRxChannels () const inline
Definition at line 80 of file deviceuiset.h.
Referenced by MainWindow::channelAddClicked().
 { return m_nbAvailableRxChannels; }
getNumberOfAvailableTxChannels()
int DeviceUISet::getNumberOfAvailableTxChannels () const inline
Definition at line 81 of file deviceuiset.h.
Referenced by MainWindow::channelAddClicked().
 { return m_nbAvailableTxChannels; }
getNumberOfRxChannels()
int DeviceUISet::getNumberOfRxChannels () const inline
Definition at line 61 of file deviceuiset.h.
 { return m_rxChannelInstanceRegistrations.size(); }
getNumberOfTxChannels()
int DeviceUISet::getNumberOfTxChannels () const inline
Definition at line 62 of file deviceuiset.h.
 { return m_txChannelInstanceRegistrations.size(); }
getSpectrum()
GLSpectrum* DeviceUISet::getSpectrum () inline
Direct spectrum getter.
Definition at line 57 of file deviceuiset.h.
Referenced by RemoteOutputSinkGui::analyzeApiReply(), RemoteOutputSinkGui::RemoteOutputSinkGui(), RemoteOutputSinkGui::updateSampleRate(), FCDProPlusGui::updateSampleRateAndFrequency(), FCDProGui::updateSampleRateAndFrequency(), SDRPlayGui::updateSampleRateAndFrequency(), TestSourceGui::updateSampleRateAndFrequency(), BladeRF2InputGui::updateSampleRateAndFrequency(), BladeRF2OutputGui::updateSampleRateAndFrequency(), Bladerf1OutputGui::updateSampleRateAndFrequency(), Bladerf1InputGui::updateSampleRateAndFrequency(), PlutoSDROutputGUI::updateSampleRateAndFrequency(), AirspyGui::updateSampleRateAndFrequency(), TestMIGui::updateSampleRateAndFrequency(), RTLSDRGui::updateSampleRateAndFrequency(), KiwiSDRGui::updateSampleRateAndFrequency(), PerseusGui::updateSampleRateAndFrequency(), PlutoSDRInputGui::updateSampleRateAndFrequency(), AirspyHFGui::updateSampleRateAndFrequency(), LimeSDRInputGUI::updateSampleRateAndFrequency(), XTRXOutputGUI::updateSampleRateAndFrequency(), LimeSDROutputGUI::updateSampleRateAndFrequency(), XTRXInputGUI::updateSampleRateAndFrequency(), FileInputGUI::updateSampleRateAndFrequency(), FileSinkGui::updateSampleRateAndFrequency(), HackRFInputGui::updateSampleRateAndFrequency(), HackRFOutputGui::updateSampleRateAndFrequency(), LocalOutputGui::updateSampleRateAndFrequency(), SoapySDRInputGui::updateSampleRateAndFrequency(), SoapySDROutputGui::updateSampleRateAndFrequency(), LocalInputGui::updateSampleRateAndFrequency(), and RemoteInputGui::updateSampleRateAndFrequency().
loadRxChannelSettings()
void DeviceUISet::loadRxChannelSettings (const Preset * preset, PluginAPI * pluginAPI)
Definition at line 166 of file deviceuiset.cpp.
References compareRxChannelURIs(), PluginInstanceGUI::deserialize(), Preset::getChannelConfig(), Preset::getChannelCount(), Preset::getDescription(), Preset::getGroup(), PluginAPI::getRxChannelRegistrations(), i, Preset::isSourcePreset(), Preset::ChannelConfig::m_channelIdURI, Preset::ChannelConfig::m_config, m_deviceAPI, DeviceUISet::ChannelInstanceRegistration::m_gui, m_rxChannelInstanceRegistrations, and renameRxChannelInstances().
Referenced by MainWindow::loadPresetSettings().
 {
     if (preset->isSourcePreset())
     {
         qDebug("DeviceUISet::loadRxChannelSettings: Loading preset [%s | %s]", qPrintable(preset->getGroup()), qPrintable(preset->getDescription()));
         // Available channel plugins
         PluginAPI::ChannelRegistrations *channelRegistrations = pluginAPI->getRxChannelRegistrations();
         // copy currently open channels and clear list
         ChannelInstanceRegistrations openChannels = m_rxChannelInstanceRegistrations;
         m_rxChannelInstanceRegistrations.clear();
         for(int i = 0; i < openChannels.count(); i++)
         {
             qDebug("DeviceUISet::loadRxChannelSettings: destroying old channel [%s]", qPrintable(openChannels[i].m_channelName));
             openChannels[i].m_gui->destroy(); // FIXME: stop channel before
         }
         qDebug("DeviceUISet::loadRxChannelSettings: %d channel(s) in preset", preset->getChannelCount());
         for (int i = 0; i < preset->getChannelCount(); i++)
         {
             const Preset::ChannelConfig& channelConfig = preset->getChannelConfig(i);
             ChannelInstanceRegistration reg;
             // create channel instance
             for(int i = 0; i < channelRegistrations->count(); i++)
             {
                 //if((*channelRegistrations)[i].m_channelIdURI == channelConfig.m_channelIdURI)
                 if (compareRxChannelURIs((*channelRegistrations)[i].m_channelIdURI, channelConfig.m_channelIdURI))
                 {
                     qDebug("DeviceUISet::loadRxChannelSettings: creating new channel [%s] from config [%s]",
                             qPrintable((*channelRegistrations)[i].m_channelIdURI),
                             qPrintable(channelConfig.m_channelIdURI));
                     BasebandSampleSink *rxChannel =
                             (*channelRegistrations)[i].m_plugin->createRxChannelBS(m_deviceAPI);
                     PluginInstanceGUI *rxChannelGUI =
                             (*channelRegistrations)[i].m_plugin->createRxChannelGUI(this, rxChannel);
                     reg = ChannelInstanceRegistration(channelConfig.m_channelIdURI, rxChannelGUI);
                     break;
                 }
             }
             if (reg.m_gui != 0)
             {
                 qDebug("DeviceUISet::loadRxChannelSettings: deserializing channel [%s]", qPrintable(channelConfig.m_channelIdURI));
                 reg.m_gui->deserialize(channelConfig.m_config);
             }
         }
         renameRxChannelInstances();
     }
     else
     {
         qDebug("DeviceUISet::loadRxChannelSettings: Loading preset [%s | %s] not a source preset", qPrintable(preset->getGroup()), qPrintable(preset->getDescription()));
     }
 }
loadTxChannelSettings()
void DeviceUISet::loadTxChannelSettings (const Preset * preset, PluginAPI * pluginAPI)
Definition at line 244 of file deviceuiset.cpp.
References PluginInstanceGUI::deserialize(), Preset::getChannelConfig(), Preset::getChannelCount(), Preset::getDescription(), Preset::getGroup(), PluginAPI::getTxChannelRegistrations(), i, Preset::isSourcePreset(), Preset::ChannelConfig::m_channelIdURI, Preset::ChannelConfig::m_config, m_deviceAPI, DeviceUISet::ChannelInstanceRegistration::m_gui, m_txChannelInstanceRegistrations, and renameTxChannelInstances().
Referenced by MainWindow::loadPresetSettings().
 {
     if (preset->isSourcePreset())
     {
         qDebug("DeviceUISet::loadTxChannelSettings: Loading preset [%s | %s] not a sink preset", qPrintable(preset->getGroup()), qPrintable(preset->getDescription()));
     }
     else
     {
         qDebug("DeviceUISet::loadTxChannelSettings: Loading preset [%s | %s]", qPrintable(preset->getGroup()), qPrintable(preset->getDescription()));
         // Available channel plugins
         PluginAPI::ChannelRegistrations *channelRegistrations = pluginAPI->getTxChannelRegistrations();
         // copy currently open channels and clear list
         ChannelInstanceRegistrations openChannels = m_txChannelInstanceRegistrations;
         m_txChannelInstanceRegistrations.clear();
         for(int i = 0; i < openChannels.count(); i++)
         {
             qDebug("DeviceUISet::loadTxChannelSettings: destroying old channel [%s]", qPrintable(openChannels[i].m_channelName));
             openChannels[i].m_gui->destroy();
         }
         qDebug("DeviceUISet::loadTxChannelSettings: %d channel(s) in preset", preset->getChannelCount());
         for(int i = 0; i < preset->getChannelCount(); i++)
         {
             const Preset::ChannelConfig& channelConfig = preset->getChannelConfig(i);
             ChannelInstanceRegistration reg;
             // create channel instance
             for(int i = 0; i < channelRegistrations->count(); i++)
             {
                 if ((*channelRegistrations)[i].m_channelIdURI == channelConfig.m_channelIdURI)
                 {
                     qDebug("DeviceUISet::loadTxChannelSettings: creating new channel [%s] from config [%s]",
                             qPrintable((*channelRegistrations)[i].m_channelIdURI),
                             qPrintable(channelConfig.m_channelIdURI));
                     BasebandSampleSource *txChannel =
                             (*channelRegistrations)[i].m_plugin->createTxChannelBS(m_deviceAPI);
                     PluginInstanceGUI *txChannelGUI =
                             (*channelRegistrations)[i].m_plugin->createTxChannelGUI(this, txChannel);
                     reg = ChannelInstanceRegistration(channelConfig.m_channelIdURI, txChannelGUI);
                     break;
                 }
             }
             if(reg.m_gui != 0)
             {
                 qDebug("DeviceUISet::loadTxChannelSettings: deserializing channel [%s]", qPrintable(channelConfig.m_channelIdURI));
                 reg.m_gui->deserialize(channelConfig.m_config);
             }
         }
         renameTxChannelInstances();
     }
 }
registerRxChannelInstance()
void DeviceUISet::registerRxChannelInstance (const QString & channelName, PluginInstanceGUI * pluginGUI)
Definition at line 82 of file deviceuiset.cpp.
References m_rxChannelInstanceRegistrations, and renameRxChannelInstances().
Referenced by AMDemodGUI::AMDemodGUI(), ATVDemodGUI::ATVDemodGUI(), BFMDemodGUI::BFMDemodGUI(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), DATVDemodGUI::DATVDemodGUI(), DSDDemodGUI::DSDDemodGUI(), FreeDVDemodGUI::FreeDVDemodGUI(), FreqTrackerGUI::FreqTrackerGUI(), LocalSinkGUI::LocalSinkGUI(), LoRaDemodGUI::LoRaDemodGUI(), NFMDemodGUI::NFMDemodGUI(), RemoteSinkGUI::RemoteSinkGUI(), SSBDemodGUI::SSBDemodGUI(), UDPSinkGUI::UDPSinkGUI(), and WFMDemodGUI::WFMDemodGUI().
 {
     m_rxChannelInstanceRegistrations.append(ChannelInstanceRegistration(channelName, pluginGUI));
     renameRxChannelInstances();
 }
registerTxChannelInstance()
void DeviceUISet::registerTxChannelInstance (const QString & channelName, PluginInstanceGUI * pluginGUI)
Definition at line 88 of file deviceuiset.cpp.
References m_txChannelInstanceRegistrations, and renameTxChannelInstances().
Referenced by AMModGUI::AMModGUI(), ATVModGUI::ATVModGUI(), FileSourceGUI::FileSourceGUI(), FreeDVModGUI::FreeDVModGUI(), LocalSourceGUI::LocalSourceGUI(), NFMModGUI::NFMModGUI(), RemoteSourceGUI::RemoteSourceGUI(), SSBModGUI::SSBModGUI(), UDPSourceGUI::UDPSourceGUI(), and WFMModGUI::WFMModGUI().
 {
     m_txChannelInstanceRegistrations.append(ChannelInstanceRegistration(channelName, pluginGUI));
     renameTxChannelInstances();
 }
removeRxChannelInstance()
void DeviceUISet::removeRxChannelInstance (PluginInstanceGUI * pluginGUI)
Definition at line 94 of file deviceuiset.cpp.
References m_rxChannelInstanceRegistrations, and renameRxChannelInstances().
Referenced by AMDemodGUI::~AMDemodGUI(), ATVDemodGUI::~ATVDemodGUI(), BFMDemodGUI::~BFMDemodGUI(), ChannelAnalyzerGUI::~ChannelAnalyzerGUI(), DATVDemodGUI::~DATVDemodGUI(), DSDDemodGUI::~DSDDemodGUI(), FreeDVDemodGUI::~FreeDVDemodGUI(), FreqTrackerGUI::~FreqTrackerGUI(), LocalSinkGUI::~LocalSinkGUI(), LoRaDemodGUI::~LoRaDemodGUI(), NFMDemodGUI::~NFMDemodGUI(), RemoteSinkGUI::~RemoteSinkGUI(), SSBDemodGUI::~SSBDemodGUI(), UDPSinkGUI::~UDPSinkGUI(), and WFMDemodGUI::~WFMDemodGUI().
 {
     for(ChannelInstanceRegistrations::iterator it = m_rxChannelInstanceRegistrations.begin(); it != m_rxChannelInstanceRegistrations.end(); ++it)
     {
         if(it->m_gui == pluginGUI)
         {
             m_rxChannelInstanceRegistrations.erase(it);
             break;
         }
     }
     renameRxChannelInstances();
 }
removeTxChannelInstance()
void DeviceUISet::removeTxChannelInstance (PluginInstanceGUI * pluginGUI)
Definition at line 108 of file deviceuiset.cpp.
References m_txChannelInstanceRegistrations, and renameTxChannelInstances().
Referenced by AMModGUI::~AMModGUI(), ATVModGUI::~ATVModGUI(), FileSourceGUI::~FileSourceGUI(), FreeDVModGUI::~FreeDVModGUI(), LocalSourceGUI::~LocalSourceGUI(), NFMModGUI::~NFMModGUI(), RemoteSourceGUI::~RemoteSourceGUI(), SSBModGUI::~SSBModGUI(), UDPSourceGUI::~UDPSourceGUI(), and WFMModGUI::~WFMModGUI().
 {
     for(ChannelInstanceRegistrations::iterator it = m_txChannelInstanceRegistrations.begin(); it != m_txChannelInstanceRegistrations.end(); ++it)
     {
         if(it->m_gui == pluginGUI)
         {
             m_txChannelInstanceRegistrations.erase(it);
             break;
         }
     }
     renameTxChannelInstances();
 }
renameRxChannelInstances()
void DeviceUISet::renameRxChannelInstances () private
Definition at line 321 of file deviceuiset.cpp.
References arg(), i, and m_rxChannelInstanceRegistrations.
Referenced by deleteRxChannel(), loadRxChannelSettings(), registerRxChannelInstance(), and removeRxChannelInstance().
 {
     for(int i = 0; i < m_rxChannelInstanceRegistrations.count(); i++)
     {
         m_rxChannelInstanceRegistrations[i].m_gui->setName(QString("%1:%2").arg(m_rxChannelInstanceRegistrations[i].m_channelName).arg(i));
     }
 }
renameTxChannelInstances()
void DeviceUISet::renameTxChannelInstances () private
Definition at line 329 of file deviceuiset.cpp.
References arg(), i, and m_txChannelInstanceRegistrations.
Referenced by deleteTxChannel(), loadTxChannelSettings(), registerTxChannelInstance(), and removeTxChannelInstance().
 {
     for(int i = 0; i < m_txChannelInstanceRegistrations.count(); i++)
     {
         m_txChannelInstanceRegistrations[i].m_gui->setName(QString("%1:%2").arg(m_txChannelInstanceRegistrations[i].m_channelName).arg(i));
     }
 }
saveRxChannelSettings()
void DeviceUISet::saveRxChannelSettings (Preset * preset)
Definition at line 226 of file deviceuiset.cpp.
References Preset::addChannel(), i, Preset::isSourcePreset(), and m_rxChannelInstanceRegistrations.
Referenced by MainWindow::savePresetSettings().
 {
     if (preset->isSourcePreset())
     {
         qSort(m_rxChannelInstanceRegistrations.begin(), m_rxChannelInstanceRegistrations.end()); // sort by increasing delta frequency and type
         for(int i = 0; i < m_rxChannelInstanceRegistrations.count(); i++)
         {
             qDebug("DeviceUISet::saveRxChannelSettings: channel [%s] saved", qPrintable(m_rxChannelInstanceRegistrations[i].m_channelName));
             preset->addChannel(m_rxChannelInstanceRegistrations[i].m_channelName, m_rxChannelInstanceRegistrations[i].m_gui->serialize());
         }
     }
     else
     {
         qDebug("DeviceUISet::saveRxChannelSettings: not a source preset");
     }
 }
saveTxChannelSettings()
void DeviceUISet::saveTxChannelSettings (Preset * preset)
Definition at line 303 of file deviceuiset.cpp.
References Preset::addChannel(), i, Preset::isSourcePreset(), and m_txChannelInstanceRegistrations.
Referenced by MainWindow::savePresetSettings().
 {
     if (preset->isSourcePreset())
     {
         qDebug("DeviceUISet::saveTxChannelSettings: not a sink preset");
     }
     else
     {
         qSort(m_txChannelInstanceRegistrations.begin(), m_txChannelInstanceRegistrations.end()); // sort by increasing delta frequency and type
         for(int i = 0; i < m_txChannelInstanceRegistrations.count(); i++)
         {
             qDebug("DeviceUISet::saveTxChannelSettings: channel [%s] saved", qPrintable(m_txChannelInstanceRegistrations[i].m_channelName));
             preset->addChannel(m_txChannelInstanceRegistrations[i].m_channelName, m_txChannelInstanceRegistrations[i].m_gui->serialize());
         }
     }
 }
setNumberOfAvailableMIMOChannels()
void DeviceUISet::setNumberOfAvailableMIMOChannels (int number) inline
Definition at line 79 of file deviceuiset.h.
 { m_nbAvailableMIMOChannels = number; }
setNumberOfAvailableRxChannels()
void DeviceUISet::setNumberOfAvailableRxChannels (int number) inline
Definition at line 77 of file deviceuiset.h.
 { m_nbAvailableRxChannels = number; }
setNumberOfAvailableTxChannels()
void DeviceUISet::setNumberOfAvailableTxChannels (int number) inline
Definition at line 78 of file deviceuiset.h.
 { m_nbAvailableTxChannels = number; }
Member Data Documentation
m_channelWindow
ChannelWindow* DeviceUISet::m_channelWindow
Definition at line 46 of file deviceuiset.h.
Referenced by MainWindow::addChannelRollup(), addRollupWidget(), DeviceUISet(), and ~DeviceUISet().
m_deviceAPI
DeviceAPI* DeviceUISet::m_deviceAPI
Definition at line 48 of file deviceuiset.h.
Referenced by AirspyGui::AirspyGui(), AirspyHFGui::AirspyHFGui(), Bladerf1InputGui::Bladerf1InputGui(), Bladerf1OutputGui::Bladerf1OutputGui(), BladeRF2InputGui::BladeRF2InputGui(), BladeRF2OutputGui::BladeRF2OutputGui(), MainWindow::channelAddClicked(), WebAPIAdapterGUI::devicesetChannelReportGet(), WebAPIAdapterGUI::devicesetChannelSettingsGet(), WebAPIAdapterGUI::devicesetChannelSettingsPutPatch(), WebAPIAdapterGUI::devicesetDeviceReportGet(), WebAPIAdapterGUI::devicesetDeviceRunDelete(), WebAPIAdapterGUI::devicesetDeviceRunGet(), WebAPIAdapterGUI::devicesetDeviceRunPost(), WebAPIAdapterGUI::devicesetDeviceSettingsGet(), WebAPIAdapterGUI::devicesetDeviceSettingsPutPatch(), DeviceUISet(), FCDProGui::FCDProGui(), FCDProPlusGui::FCDProPlusGui(), FileInputGUI::FileInputGUI(), FileSinkGui::FileSinkGui(), FileSourceGUI::FileSourceGUI(), WebAPIAdapterGUI::getChannelsDetail(), WebAPIAdapterGUI::getDeviceSet(), HackRFInputGui::HackRFInputGui(), HackRFOutputGui::HackRFOutputGui(), KiwiSDRGui::KiwiSDRGui(), LimeSDRInputGUI::LimeSDRInputGUI(), LimeSDROutputGUI::LimeSDROutputGUI(), MainWindow::loadPresetSettings(), loadRxChannelSettings(), loadTxChannelSettings(), LocalInputGui::LocalInputGui(), LocalOutputGui::LocalOutputGui(), TestMIGui::on_spectrumSource_currentIndexChanged(), TestMIGui::on_streamIndex_currentIndexChanged(), PerseusGui::PerseusGui(), PlutoSDRInputGui::PlutoSDRInputGui(), PlutoSDROutputGUI::PlutoSDROutputGUI(), RemoteInputGui::RemoteInputGui(), RemoteOutputSinkGui::RemoteOutputSinkGui(), RemoteSourceGUI::RemoteSourceGUI(), RTLSDRGui::RTLSDRGui(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), MainWindow::sampleSourceChanged(), MainWindow::savePresetSettings(), SDRPlayGui::SDRPlayGui(), SoapySDRInputGui::SoapySDRInputGui(), SoapySDROutputGui::SoapySDROutputGui(), TestMIGui::TestMIGui(), TestSourceGui::TestSourceGui(), SDRPlayGui::updateStatus(), Bladerf1OutputGui::updateStatus(), KiwiSDRGui::updateStatus(), BladeRF2OutputGui::updateStatus(), LocalOutputGui::updateStatus(), PerseusGui::updateStatus(), FileSinkGui::updateStatus(), FCDProPlusGui::updateStatus(), Bladerf1InputGui::updateStatus(), AirspyGui::updateStatus(), PlutoSDROutputGUI::updateStatus(), BladeRF2InputGui::updateStatus(), AirspyHFGui::updateStatus(), XTRXOutputGUI::updateStatus(), FileInputGUI::updateStatus(), RTLSDRGui::updateStatus(), TestSourceGui::updateStatus(), HackRFOutputGui::updateStatus(), LimeSDROutputGUI::updateStatus(), PlutoSDRInputGui::updateStatus(), HackRFInputGui::updateStatus(), FCDProGui::updateStatus(), XTRXInputGUI::updateStatus(), TestMIGui::updateStatus(), LimeSDRInputGUI::updateStatus(), LocalInputGui::updateStatus(), RemoteInputGui::updateStatus(), SoapySDROutputGui::updateStatus(), SoapySDRInputGui::updateStatus(), RemoteOutputSinkGui::updateStatus(), XTRXInputGUI::XTRXInputGUI(), and XTRXOutputGUI::XTRXOutputGUI().
m_deviceMIMOEngine
DSPDeviceMIMOEngine* DeviceUISet::m_deviceMIMOEngine
Definition at line 51 of file deviceuiset.h.
Referenced by MainWindow::channelAddClicked(), DeviceUISet(), AMDemodGUI::displayStreamIndex(), and AMDemodGUI::onMenuDialogCalled().
m_deviceSinkEngine
DSPDeviceSinkEngine* DeviceUISet::m_deviceSinkEngine
Definition at line 50 of file deviceuiset.h.
Referenced by MainWindow::channelAddClicked(), MainWindow::deleteChannel(), WebAPIAdapterGUI::devicesetChannelDelete(), WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterGUI::devicesetChannelReportGet(), WebAPIAdapterGUI::devicesetChannelSettingsGet(), WebAPIAdapterGUI::devicesetChannelSettingsPutPatch(), WebAPIAdapterGUI::devicesetDevicePut(), WebAPIAdapterGUI::devicesetDeviceReportGet(), WebAPIAdapterGUI::devicesetDeviceRunDelete(), WebAPIAdapterGUI::devicesetDeviceRunGet(), WebAPIAdapterGUI::devicesetDeviceRunPost(), WebAPIAdapterGUI::devicesetDeviceSettingsGet(), WebAPIAdapterGUI::devicesetDeviceSettingsPutPatch(), DeviceUISet(), WebAPIAdapterGUI::getChannelsDetail(), WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), MainWindow::loadPresetSettings(), and MainWindow::savePresetSettings().
m_deviceSourceEngine
DSPDeviceSourceEngine* DeviceUISet::m_deviceSourceEngine
Definition at line 49 of file deviceuiset.h.
Referenced by MainWindow::channelAddClicked(), MainWindow::deleteChannel(), WebAPIAdapterGUI::devicesetChannelDelete(), WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterGUI::devicesetChannelReportGet(), WebAPIAdapterGUI::devicesetChannelSettingsGet(), WebAPIAdapterGUI::devicesetChannelSettingsPutPatch(), WebAPIAdapterGUI::devicesetDevicePut(), WebAPIAdapterGUI::devicesetDeviceReportGet(), WebAPIAdapterGUI::devicesetDeviceRunDelete(), WebAPIAdapterGUI::devicesetDeviceRunGet(), WebAPIAdapterGUI::devicesetDeviceRunPost(), WebAPIAdapterGUI::devicesetDeviceSettingsGet(), WebAPIAdapterGUI::devicesetDeviceSettingsPutPatch(), DeviceUISet(), WebAPIAdapterGUI::getChannelsDetail(), WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), MainWindow::loadPresetSettings(), and MainWindow::savePresetSettings().
m_deviceTabIndex
int DeviceUISet::m_deviceTabIndex private
Definition at line 107 of file deviceuiset.h.
Referenced by DeviceUISet().
m_mainWindowState
QByteArray DeviceUISet::m_mainWindowState
Definition at line 52 of file deviceuiset.h.
Referenced by MainWindow::tabInputViewIndexChanged().
m_nbAvailableMIMOChannels
int DeviceUISet::m_nbAvailableMIMOChannels private
Number of MIMO channels available for selection.
Definition at line 110 of file deviceuiset.h.
Referenced by DeviceUISet().
m_nbAvailableRxChannels
int DeviceUISet::m_nbAvailableRxChannels private
Number of Rx channels available for selection.
Definition at line 108 of file deviceuiset.h.
Referenced by DeviceUISet().
m_nbAvailableTxChannels
int DeviceUISet::m_nbAvailableTxChannels private
Number of Tx channels available for selection.
Definition at line 109 of file deviceuiset.h.
Referenced by DeviceUISet().
m_rxChannelInstanceRegistrations
ChannelInstanceRegistrations DeviceUISet::m_rxChannelInstanceRegistrations private
Definition at line 105 of file deviceuiset.h.
Referenced by deleteRxChannel(), freeRxChannels(), loadRxChannelSettings(), registerRxChannelInstance(), removeRxChannelInstance(), renameRxChannelInstances(), and saveRxChannelSettings().
m_samplingDeviceControl
SamplingDeviceControl* DeviceUISet::m_samplingDeviceControl
Definition at line 47 of file deviceuiset.h.
Referenced by MainWindow::channelAddClicked(), DeviceUISet(), MainWindow::handleMessage(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), MainWindow::sampleSourceChanged(), and ~DeviceUISet().
m_spectrum
GLSpectrum* DeviceUISet::m_spectrum
Definition at line 44 of file deviceuiset.h.
Referenced by addChannelMarker(), DeviceUISet(), TestMIGui::on_spectrumSource_currentIndexChanged(), TestMIGui::on_streamIndex_currentIndexChanged(), and ~DeviceUISet().
m_spectrumGUI
GLSpectrumGUI* DeviceUISet::m_spectrumGUI
Definition at line 45 of file deviceuiset.h.
Referenced by DeviceUISet(), MainWindow::loadPresetSettings(), MainWindow::savePresetSettings(), and ~DeviceUISet().
m_spectrumVis
SpectrumVis* DeviceUISet::m_spectrumVis
Definition at line 43 of file deviceuiset.h.
Referenced by DeviceUISet(), and ~DeviceUISet().
m_txChannelInstanceRegistrations
ChannelInstanceRegistrations DeviceUISet::m_txChannelInstanceRegistrations private
Definition at line 106 of file deviceuiset.h.
Referenced by deleteTxChannel(), freeTxChannels(), loadTxChannelSettings(), registerTxChannelInstance(), removeTxChannelInstance(), renameTxChannelInstances(), and saveTxChannelSettings().
The documentation for this class was generated from the following files:
sdrgui/device/deviceuiset.h
sdrgui/device/deviceuiset.cpp