SDRAngel: HackRFInputThread Class Reference
HackRFInputThread Class Reference
#include <hackrfinputthread.h>
Inherits QThread.
Public Member Functions
HackRFInputThread (hackrf_device *dev, SampleSinkFifo *sampleFifo, QObject *parent=NULL)
~HackRFInputThread ()
void startWork ()
void stopWork ()
void setSamplerate (uint32_t samplerate)
void setLog2Decimation (unsigned int log2_decim)
void setFcPos (int fcPos)
Private Member Functions
void run ()
void callback (const qint8 *buf, qint32 len)
Static Private Member Functions
static int rx_callback (hackrf_transfer *transfer)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
hackrf_device * m_dev
qint16 m_buf [2 *HACKRF_BLOCKSIZE]
SampleVector m_convertBuffer
SampleSinkFifo * m_sampleFifo
int m_samplerate
unsigned int m_log2Decim
int m_fcPos
Decimators< qint32, qint8, SDR_RX_SAMP_SZ, 8 > m_decimators
Detailed Description
Definition at line 31 of file hackrfinputthread.h.
Constructor & Destructor Documentation
HackRFInputThread()
HackRFInputThread::HackRFInputThread (hackrf_device * dev, SampleSinkFifo * sampleFifo, QObject * parent = NULL)
Definition at line 26 of file hackrfinputthread.cpp.
References HACKRF_BLOCKSIZE, and m_buf.
                                                                                                     :
     QThread(parent),
     m_running(false),
     m_dev(dev),
     m_convertBuffer(HACKRF_BLOCKSIZE),
     m_sampleFifo(sampleFifo),
     m_samplerate(10),
     m_log2Decim(0),
     m_fcPos(0)
 {
     std::fill(m_buf, m_buf + 2*HACKRF_BLOCKSIZE, 0);
 }
~HackRFInputThread()
HackRFInputThread::~HackRFInputThread ()
Definition at line 39 of file hackrfinputthread.cpp.
References stopWork().
 {
     stopWork();
 }
Member Function Documentation
callback()
void HackRFInputThread::callback (const qint8 * buf, qint32 len) private
Definition at line 125 of file hackrfinputthread.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf_txsync(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup_txsync(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf_txsync(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup_txsync(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf_txsync(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup_txsync(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf_txsync(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup_txsync(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf_txsync(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup_txsync(), m_convertBuffer, m_decimators, m_fcPos, m_log2Decim, m_sampleFifo, and SampleSinkFifo::write().
Referenced by rx_callback().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     if (m_log2Decim == 0)
     {
         m_decimators.decimate1(&it, buf, len);
     }
     else
     {
         if (m_fcPos == 0) // Infra
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_inf(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_inf_txsync(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_inf_txsync(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_inf_txsync(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_inf_txsync(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_inf_txsync(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 1) // Supra
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_sup(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_sup_txsync(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_sup_txsync(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_sup_txsync(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_sup_txsync(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_sup_txsync(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 2) // Center
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_cen(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_cen(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_cen(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_cen(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_cen(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_cen(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
     }
     m_sampleFifo->write(m_convertBuffer.begin(), it);
 }
run()
void HackRFInputThread::run () private
Definition at line 75 of file hackrfinputthread.cpp.
References m_dev, m_running, m_startWaiter, and rx_callback().
 {
     hackrf_error rc;
     m_running = true;
     m_startWaiter.wakeAll();
     if (hackrf_is_streaming(m_dev) == HACKRF_TRUE)
     {
         qDebug("HackRFInputThread::run: HackRF is streaming already");
     }
     else
     {
         qDebug("HackRFInputThread::run: HackRF is not streaming");
         rc = (hackrf_error) hackrf_start_rx(m_dev, rx_callback, this);
         if (rc == HACKRF_SUCCESS)
         {
             qDebug("HackRFInputThread::run: started HackRF Rx");
         }
         else
         {
             qDebug("HackRFInputThread::run: failed to start HackRF Rx: %s", hackrf_error_name(rc));
         }
     }
     while ((m_running) && (hackrf_is_streaming(m_dev) == HACKRF_TRUE))
     {
         usleep(200000);
     }
     if (hackrf_is_streaming(m_dev) == HACKRF_TRUE)
     {
         rc = (hackrf_error) hackrf_stop_rx(m_dev);
         if (rc == HACKRF_SUCCESS)
         {
             qDebug("HackRFInputThread::run: stopped HackRF Rx");
         }
         else
         {
             qDebug("HackRFInputThread::run: failed to stop HackRF Rx: %s", hackrf_error_name(rc));
         }
     }
     m_running = false;
 }
rx_callback()
int HackRFInputThread::rx_callback (hackrf_transfer * transfer) static private
Definition at line 219 of file hackrfinputthread.cpp.
References callback().
Referenced by run().
 {
     HackRFInputThread *thread = (HackRFInputThread *) transfer->rx_ctx;
     qint32 bytes_to_write = transfer->valid_length;
     thread->callback((qint8 *) transfer->buffer, bytes_to_write);
     return 0;
 }
setFcPos()
void HackRFInputThread::setFcPos (int fcPos)
Definition at line 70 of file hackrfinputthread.cpp.
References m_fcPos.
Referenced by HackRFInput::applySettings(), and HackRFInput::start().
 {
     m_fcPos = fcPos;
 }
setLog2Decimation()
void HackRFInputThread::setLog2Decimation (unsigned int log2_decim)
Definition at line 65 of file hackrfinputthread.cpp.
References m_log2Decim.
Referenced by HackRFInput::applySettings(), and HackRFInput::start().
 {
     m_log2Decim = log2_decim;
 }
setSamplerate()
void HackRFInputThread::setSamplerate (uint32_t samplerate)
Definition at line 60 of file hackrfinputthread.cpp.
References m_samplerate.
Referenced by HackRFInput::applySettings(), and HackRFInput::start().
 {
     m_samplerate = samplerate;
 }
startWork()
void HackRFInputThread::startWork ()
Definition at line 44 of file hackrfinputthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by HackRFInput::start().
 {
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void HackRFInputThread::stopWork ()
Definition at line 53 of file hackrfinputthread.cpp.
References m_running.
Referenced by HackRFInput::stop(), and ~HackRFInputThread().
 {
     qDebug("HackRFThread::stopWork");
     m_running = false;
     wait();
 }
Member Data Documentation
m_buf
qint16 HackRFInputThread::m_buf[2 *HACKRF_BLOCKSIZE] private
Definition at line 50 of file hackrfinputthread.h.
Referenced by HackRFInputThread().
m_convertBuffer
SampleVector HackRFInputThread::m_convertBuffer private
Definition at line 51 of file hackrfinputthread.h.
Referenced by callback().
m_decimators
Decimators<qint32, qint8, SDR_RX_SAMP_SZ, 8> HackRFInputThread::m_decimators private
Definition at line 58 of file hackrfinputthread.h.
Referenced by callback().
m_dev
hackrf_device* HackRFInputThread::m_dev private
Definition at line 49 of file hackrfinputthread.h.
Referenced by run().
m_fcPos
int HackRFInputThread::m_fcPos private
Definition at line 56 of file hackrfinputthread.h.
Referenced by callback(), and setFcPos().
m_log2Decim
unsigned int HackRFInputThread::m_log2Decim private
Definition at line 55 of file hackrfinputthread.h.
Referenced by callback(), and setLog2Decimation().
m_running
bool HackRFInputThread::m_running private
Definition at line 47 of file hackrfinputthread.h.
Referenced by run(), startWork(), and stopWork().
m_sampleFifo
SampleSinkFifo* HackRFInputThread::m_sampleFifo private
Definition at line 52 of file hackrfinputthread.h.
Referenced by callback().
m_samplerate
int HackRFInputThread::m_samplerate private
Definition at line 54 of file hackrfinputthread.h.
Referenced by setSamplerate().
m_startWaiter
QWaitCondition HackRFInputThread::m_startWaiter private
Definition at line 46 of file hackrfinputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex HackRFInputThread::m_startWaitMutex private
Definition at line 45 of file hackrfinputthread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/samplesource/hackrfinput/hackrfinputthread.h
plugins/samplesource/hackrfinput/hackrfinputthread.cpp