SDRAngel: leansdr::sampler_interface< T > Struct Template Reference
leansdr::sampler_interface< T > Struct Template Reference abstract
#include <sdr.h>
Public Member Functions
virtual ~sampler_interface ()
virtual complex< T > interp (const complex< T > *pin, float mu, float phase)=0
virtual void update_freq (float freqw, int period=1)
virtual int readahead ()=0
Detailed Description
template<typename T>
struct leansdr::sampler_interface< T >
Definition at line 888 of file sdr.h.
Constructor & Destructor Documentation
~sampler_interface()
template<typename T> virtual leansdr::sampler_interface< T >::~sampler_interface () inline virtual
Definition at line 890 of file sdr.h.
     {
     }
Member Function Documentation
interp()
template<typename T> virtual complex<T> leansdr::sampler_interface< T >::interp (const complex< T > * pin, float mu, float phase) pure virtual
Implemented in leansdr::fir_sampler< T, Tc >, leansdr::linear_sampler< T >, and leansdr::nearest_sampler< T >.
Referenced by leansdr::s2_frame_receiver< T, SOFTSYMB >::interp_next(), and leansdr::cstln_receiver< leansdr::f32, leansdr::eucl_ss >::run().
readahead()
template<typename T> virtual int leansdr::sampler_interface< T >::readahead () pure virtual
Implemented in leansdr::fir_sampler< T, Tc >, leansdr::linear_sampler< T >, and leansdr::nearest_sampler< T >.
Referenced by leansdr::s2_frame_receiver< T, SOFTSYMB >::run(), and leansdr::cstln_receiver< leansdr::f32, leansdr::eucl_ss >::run().
update_freq()
template<typename T> virtual void leansdr::sampler_interface< T >::update_freq (float freqw, int period = 1) inline virtual
Reimplemented in leansdr::fir_sampler< T, Tc >, and leansdr::linear_sampler< T >.
Definition at line 894 of file sdr.h.
Referenced by leansdr::cstln_receiver< leansdr::f32, leansdr::eucl_ss >::run(), leansdr::s2_frame_receiver< T, SOFTSYMB >::run_frame_locked(), and leansdr::s2_frame_receiver< T, SOFTSYMB >::run_frame_search().
     {
         (void) freqw;
         (void) period;
     } // 65536 = 1 Hz
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/sdr.h