SDRAngel: MessageQueue Class Reference
MessageQueue Class Reference
#include <messagequeue.h>
Inherits QObject.
Signals
void messageEnqueued ()
Public Member Functions
MessageQueue (QObject *parent=NULL)
~MessageQueue ()
void push (Message *message, bool emitSignal=true)
Push message onto queue.
Message * pop ()
Pop message from queue.
int size ()
Returns queue size.
void clear ()
Empty queue.
Private Attributes
QMutex m_lock
QQueue< Message * > m_queue
Detailed Description
Definition at line 29 of file messagequeue.h.
Constructor & Destructor Documentation
MessageQueue()
MessageQueue::MessageQueue (QObject * parent = NULL)
Definition at line 24 of file messagequeue.cpp.
                                           :
     QObject(parent),
     m_lock(QMutex::Recursive),
     m_queue()
 {
 }
~MessageQueue()
MessageQueue::~MessageQueue ()
Definition at line 31 of file messagequeue.cpp.
References Message::getIdentifier(), and pop().
 {
     Message* message;
     while ((message = pop()) != 0)
     {
         qDebug() << "MessageQueue::~MessageQueue: message: " << message->getIdentifier() << " was still in queue";
         delete message;
     }
 }
Member Function Documentation
clear()
void MessageQueue::clear ()
Empty queue.
Definition at line 78 of file messagequeue.cpp.
References m_lock, and m_queue.
Referenced by AMBEWorker::handleInputMessages().
 {
     QMutexLocker locker(&m_lock);
     while (!m_queue.isEmpty()) {
         delete m_queue.takeFirst();
     }
 }
messageEnqueued
void MessageQueue::messageEnqueued () signal
Referenced by push().
pop()
Message * MessageQueue::pop ()
Pop message from queue.
Definition at line 57 of file messagequeue.cpp.
References m_lock, and m_queue.
Referenced by BasebandSampleSink::handleInputMessages(), BasebandSampleSource::handleInputMessages(), LocalSinkThread::handleInputMessages(), FCDProPlusGui::handleInputMessages(), FCDProGui::handleInputMessages(), SDRPlayGui::handleInputMessages(), Bladerf1OutputGui::handleInputMessages(), LocalSourceThread::handleInputMessages(), BladeRF2OutputGui::handleInputMessages(), Bladerf1InputGui::handleInputMessages(), KiwiSDRGui::handleInputMessages(), TestSourceGui::handleInputMessages(), BladeRF2InputGui::handleInputMessages(), RTLSDRGui::handleInputMessages(), XTRXOutputGUI::handleInputMessages(), XTRXInputGUI::handleInputMessages(), TestMIGui::handleInputMessages(), LimeSDRInputGUI::handleInputMessages(), LimeSDROutputGUI::handleInputMessages(), FileSinkGui::handleInputMessages(), HackRFInputGui::handleInputMessages(), HackRFOutputGui::handleInputMessages(), LocalOutputGui::handleInputMessages(), RemoteSinkThread::handleInputMessages(), FileInputGUI::handleInputMessages(), PerseusGui::handleInputMessages(), AirspyGui::handleInputMessages(), PlutoSDROutputGUI::handleInputMessages(), AirspyHFGui::handleInputMessages(), GLSpectrumGUI::handleInputMessages(), RemoteSourceThread::handleInputMessages(), PlutoSDRInputGui::handleInputMessages(), SoapySDRInputGui::handleInputMessages(), LocalInputGui::handleInputMessages(), SoapySDROutputGui::handleInputMessages(), RemoteInputGui::handleInputMessages(), DSPDeviceSinkEngine::handleInputMessages(), UDPSinkFECWorker::handleInputMessages(), AMBEWorker::handleInputMessages(), DeviceSampleMIMO::handleInputMessages(), RemoteOutputSinkGui::handleInputMessages(), DeviceSampleSink::handleInputMessages(), DSPDeviceSourceEngine::handleInputMessages(), DeviceSampleSource::handleInputMessages(), DSPDeviceMIMOEngine::handleInputMessages(), TestMIThread::handleInputMessages(), TestSourceThread::handleInputMessages(), UDPSourceUDPHandler::handleMessages(), MainCore::handleMessages(), MainWindow::handleMessages(), and ~MessageQueue().
 {
     QMutexLocker locker(&m_lock);
     if (m_queue.isEmpty())
     {
         return 0;
     }
     else
     {
         return m_queue.takeFirst();
     }
 }
push()
void MessageQueue::push (Message * message, bool emitSignal = true)
Push message onto queue.
Definition at line 42 of file messagequeue.cpp.
References m_lock, m_queue, and messageEnqueued().
Referenced by ScopeVis::addTrace(), ScopeVis::addTrigger(), UDPSourceUDPHandler::advanceReadPointer(), AMDemod::applyAudioSampleRate(), NFMDemod::applyAudioSampleRate(), AMMod::applyAudioSampleRate(), NFMMod::applyAudioSampleRate(), SSBDemod::applyAudioSampleRate(), SSBMod::applyAudioSampleRate(), LocalSourceGUI::applyChannelSettings(), LocalSinkGUI::applyChannelSettings(), RemoteSinkGUI::applyChannelSettings(), FileSourceGUI::applyChannelSettings(), ATVMod::applyChannelSettings(), DownChannelizer::applyConfiguration(), UpChannelizer::applyConfiguration(), FreeDVMod::applyFreeDVMode(), FreeDVDemod::applyFreeDVMode(), DownChannelizer::applySetting(), UpChannelizer::applySetting(), WFMDemodGUI::applySettings(), LoRaDemodGUI::applySettings(), NFMDemodGUI::applySettings(), AMDemodGUI::applySettings(), CWKeyerGUI::applySettings(), SSBDemodGUI::applySettings(), LocalSourceGUI::applySettings(), FreqTrackerGUI::applySettings(), LocalSinkGUI::applySettings(), RemoteSinkGUI::applySettings(), UDPSourceGUI::applySettings(), BFMDemodGUI::applySettings(), NFMModGUI::applySettings(), AMModGUI::applySettings(), RemoteSourceGUI::applySettings(), WFMModGUI::applySettings(), ATVDemodGUI::applySettings(), ATVModGUI::applySettings(), UDPSinkGUI::applySettings(), FreeDVModGUI::applySettings(), FileSourceGUI::applySettings(), ChannelAnalyzerGUI::applySettings(), FreeDVDemodGUI::applySettings(), SSBModGUI::applySettings(), DSDDemodGUI::applySettings(), DATVDemodGUI::applySettings(), PlutoSDROutput::applySettings(), Bladerf1Output::applySettings(), TestSourceInput::applySettings(), HackRFOutput::applySettings(), Bladerf1Input::applySettings(), PerseusInput::applySettings(), AirspyInput::applySettings(), AirspyHFInput::applySettings(), TestMI::applySettings(), RTLSDRInput::applySettings(), BladeRF2Output::applySettings(), PlutoSDRInput::applySettings(), FCDProPlusInput::applySettings(), HackRFInput::applySettings(), KiwiSDRInput::applySettings(), FCDProInput::applySettings(), RemoteOutput::applySettings(), SDRPlayInput::applySettings(), SoapySDROutput::applySettings(), BladeRF2Input::applySettings(), FileSinkOutput::applySettings(), SoapySDRInput::applySettings(), XTRXOutput::applySettings(), LimeSDROutput::applySettings(), LimeSDRInput::applySettings(), ATVDemod::applySettings(), ATVMod::applySettings(), UDPSinkGUI::applySettingsImmediate(), ScopeVis::changeTrace(), ScopeVis::changeTrigger(), ATVDemod::channelSampleRateChanged(), SpectrumVis::configure(), DownChannelizer::configure(), UpChannelizer::configure(), SSBDemod::configure(), FreeDVDemod::configure(), ScopeVis::configure(), ATVDemod::configure(), FreqTracker::configureChannelizer(), DSPDeviceSourceEngine::configureCorrections(), DSPDeviceMIMOEngine::configureCorrections(), FileSinkGui::configureFileName(), FileInputGUI::configureFileName(), FileSourceGUI::configureFileName(), AMModGUI::configureFileName(), FreeDVModGUI::configureFileName(), NFMModGUI::configureFileName(), WFMModGUI::configureFileName(), SSBModGUI::configureFileName(), ATVModGUI::configureImageFileName(), DSDDemod::configureMyPosition(), ATVDemod::configureRF(), UDPSourceUDPHandler::configureUDPLink(), ATVModGUI::configureVideoFileName(), RemoteSourceThread::dataBind(), PlutoSDROutput::deserialize(), Bladerf1Output::deserialize(), HackRFOutput::deserialize(), LoRaDemod::deserialize(), AirspyInput::deserialize(), TestSourceInput::deserialize(), AirspyHFInput::deserialize(), UDPSource::deserialize(), PerseusInput::deserialize(), RTLSDRInput::deserialize(), Bladerf1Input::deserialize(), AMDemod::deserialize(), TestMI::deserialize(), WFMDemod::deserialize(), PlutoSDRInput::deserialize(), LocalOutput::deserialize(), DSDDemod::deserialize(), BladeRF2Output::deserialize(), FCDProInput::deserialize(), FCDProPlusInput::deserialize(), LocalSink::deserialize(), UDPSink::deserialize(), LocalSource::deserialize(), RemoteSink::deserialize(), SSBDemod::deserialize(), HackRFInput::deserialize(), KiwiSDRInput::deserialize(), SoapySDROutput::deserialize(), NFMDemod::deserialize(), LocalInput::deserialize(), FreqTracker::deserialize(), RemoteOutput::deserialize(), BFMDemod::deserialize(), FreeDVDemod::deserialize(), BladeRF2Input::deserialize(), SDRPlayInput::deserialize(), FileSinkOutput::deserialize(), XTRXOutput::deserialize(), LimeSDROutput::deserialize(), XTRXInput::deserialize(), RemoteSource::deserialize(), LimeSDRInput::deserialize(), AMMod::deserialize(), WFMMod::deserialize(), NFMMod::deserialize(), SSBMod::deserialize(), FreeDVMod::deserialize(), RemoteInput::deserialize(), FileInput::deserialize(), FileSource::deserialize(), ATVMod::deserialize(), WebAPIAdapterGUI::devicesetChannelDelete(), WebAPIAdapterSrv::devicesetChannelDelete(), WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterSrv::devicesetChannelPost(), WebAPIAdapterGUI::devicesetDevicePut(), WebAPIAdapterSrv::devicesetDevicePut(), WebAPIAdapterGUI::devicesetFocusPatch(), DATVDemod::feed(), ScopeVis::focusOnTrace(), ScopeVis::focusOnTrigger(), ATVMod::getCameraNumbers(), DSPDeviceSinkEngine::gotoInit(), DSPDeviceSourceEngine::gotoInit(), FileSource::handleEOF(), LocalOutputGui::handleInputMessages(), LocalInputGui::handleInputMessages(), RemoteInputGui::handleInputMessages(), DSPDeviceSinkEngine::handleInputMessages(), DSPDeviceSourceEngine::handleInputMessages(), DSPDeviceMIMOEngine::handleInputMessages(), DownChannelizer::handleMessage(), UpChannelizer::handleMessage(), LocalSink::handleMessage(), LocalSource::handleMessage(), HackRFOutput::handleMessage(), RemoteSink::handleMessage(), BladeRF2Output::handleMessage(), BFMDemod::handleMessage(), HackRFInput::handleMessage(), ChannelAnalyzer::handleMessage(), SoapySDROutput::handleMessage(), BladeRF2Input::handleMessage(), SoapySDRInput::handleMessage(), RemoteSource::handleMessage(), FileSinkOutput::handleMessage(), XTRXOutput::handleMessage(), LimeSDROutput::handleMessage(), AMMod::handleMessage(), WFMMod::handleMessage(), NFMMod::handleMessage(), XTRXInput::handleMessage(), SSBMod::handleMessage(), FreeDVMod::handleMessage(), LimeSDRInput::handleMessage(), FileInput::handleMessage(), FileSource::handleMessage(), ATVMod::handleMessage(), FileInput::init(), WebAPIAdapterSrv::instanceDelete(), WebAPIAdapterGUI::instanceDeviceSetDelete(), WebAPIAdapterSrv::instanceDeviceSetDelete(), WebAPIAdapterGUI::instanceDeviceSetPost(), WebAPIAdapterSrv::instanceDeviceSetPost(), WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), ScopeVis::moveTrace(), ScopeVis::moveTrigger(), FileInputGUI::on_acceleration_currentIndexChanged(), ATVModGUI::on_cameraManualFPS_valueChanged(), ATVModGUI::on_cameraManualFPSEnable_toggled(), ATVModGUI::on_camSelect_currentIndexChanged(), FileSourceGUI::on_navTime_valueChanged(), FileInputGUI::on_navTimeSlider_valueChanged(), AMModGUI::on_navTimeSlider_valueChanged(), NFMModGUI::on_navTimeSlider_valueChanged(), FreeDVModGUI::on_navTimeSlider_valueChanged(), WFMModGUI::on_navTimeSlider_valueChanged(), SSBModGUI::on_navTimeSlider_valueChanged(), ATVModGUI::on_navTimeSlider_valueChanged(), FileInputGUI::on_play_toggled(), FileSourceGUI::on_play_toggled(), FileInputGUI::on_playLoop_toggled(), FileSourceGUI::on_playLoop_toggled(), KiwiSDRGui::on_record_toggled(), PlutoSDRInputGui::on_record_toggled(), XTRXInputGUI::on_record_toggled(), LimeSDRInputGUI::on_record_toggled(), PerseusGui::on_record_toggled(), AirspyHFGui::on_record_toggled(), FCDProPlusGui::on_record_toggled(), Bladerf1InputGui::on_record_toggled(), AirspyGui::on_record_toggled(), BladeRF2InputGui::on_record_toggled(), RTLSDRGui::on_record_toggled(), SDRPlayGui::on_record_toggled(), TestSourceGui::on_record_toggled(), HackRFInputGui::on_record_toggled(), FCDProGui::on_record_toggled(), TestMIGui::on_record_toggled(), LocalInputGui::on_record_toggled(), RemoteInputGui::on_record_toggled(), SoapySDRInputGui::on_record_toggled(), FreeDVDemodGUI::on_reSync_clicked(), KiwiSDRGui::on_startStop_toggled(), TestSourceGui::on_startStop_toggled(), PlutoSDROutputGUI::on_startStop_toggled(), PlutoSDRInputGui::on_startStop_toggled(), XTRXOutputGUI::on_startStop_toggled(), TestMIGui::on_startStop_toggled(), LimeSDRInputGUI::on_startStop_toggled(), XTRXInputGUI::on_startStop_toggled(), LimeSDROutputGUI::on_startStop_toggled(), PerseusGui::on_startStop_toggled(), Bladerf1OutputGui::on_startStop_toggled(), BladeRF2OutputGui::on_startStop_toggled(), AirspyHFGui::on_startStop_toggled(), FCDProPlusGui::on_startStop_toggled(), FileSinkGui::on_startStop_toggled(), LocalOutputGui::on_startStop_toggled(), Bladerf1InputGui::on_startStop_toggled(), FileInputGUI::on_startStop_toggled(), AirspyGui::on_startStop_toggled(), BladeRF2InputGui::on_startStop_toggled(), SDRPlayGui::on_startStop_toggled(), RTLSDRGui::on_startStop_toggled(), HackRFOutputGui::on_startStop_toggled(), HackRFInputGui::on_startStop_toggled(), FCDProGui::on_startStop_toggled(), LocalInputGui::on_startStop_toggled(), RemoteInputGui::on_startStop_toggled(), SoapySDROutputGui::on_startStop_toggled(), SoapySDRInputGui::on_startStop_toggled(), RemoteOutputSinkGui::on_startStop_toggled(), WFMMod::openFileStream(), AMMod::openFileStream(), FileInput::openFileStream(), NFMMod::openFileStream(), FreeDVMod::openFileStream(), SSBMod::openFileStream(), FileSource::openFileStream(), ATVMod::openVideo(), RemoteInputUDPHandler::processData(), NFMDemod::processOneSample(), ATVMod::pullVideo(), AMBEWorker::pushMbeFrame(), UDPSinkFECWorker::pushTxFrame(), ScopeVis::removeTrace(), ScopeVis::removeTrigger(), UDPSource::resetReadIndex(), RemoteOutput::sampleRateCorrection(), DownChannelizer::set(), UpChannelizer::set(), PlutoSDROutput::setCenterFrequency(), Bladerf1Output::setCenterFrequency(), HackRFOutput::setCenterFrequency(), AirspyInput::setCenterFrequency(), TestSourceInput::setCenterFrequency(), AirspyHFInput::setCenterFrequency(), PerseusInput::setCenterFrequency(), RTLSDRInput::setCenterFrequency(), Bladerf1Input::setCenterFrequency(), PlutoSDRInput::setCenterFrequency(), LocalOutput::setCenterFrequency(), BladeRF2Output::setCenterFrequency(), FCDProPlusInput::setCenterFrequency(), FCDProInput::setCenterFrequency(), HackRFInput::setCenterFrequency(), KiwiSDRInput::setCenterFrequency(), SoapySDROutput::setCenterFrequency(), LocalInput::setCenterFrequency(), BladeRF2Input::setCenterFrequency(), SDRPlayInput::setCenterFrequency(), SoapySDRInput::setCenterFrequency(), FileSinkOutput::setCenterFrequency(), XTRXOutput::setCenterFrequency(), LimeSDROutput::setCenterFrequency(), XTRXInput::setCenterFrequency(), LimeSDRInput::setCenterFrequency(), FileInput::setCenterFrequency(), RemoteSource::setDataLink(), ScopeVis::setMemoryIndex(), ScopeVis::setOneShot(), UDPSinkFECWorker::setRemoteAddress(), GLSpectrum::setSampleRate(), CWKeyer::setSampleRate(), LocalOutput::setSampleRate(), LocalInput::setSampleRate(), TestMI::setSourceCenterFrequency(), UDPSink::setSpectrum(), UDPSource::setSpectrum(), KiwiSDRInput::setWorkerStatus(), FileSinkOutput::start(), FileInput::start(), FileSource::start(), LocalSinkThread::startStop(), LocalSourceThread::startStop(), TestMIThread::startStop(), TestSourceThread::startStop(), RemoteSinkThread::startStop(), RemoteSourceThread::startStop(), UDPSinkFECWorker::startStop(), FileSinkOutput::stop(), FileInput::stop(), FileSource::stop(), RemoteInputUDPHandler::tick(), FileSinkGui::tick(), FileInputThread::tick(), FileInputGUI::tick(), RemoteSourceGUI::tick(), FileSourceGUI::tick(), AMModGUI::tick(), FreeDVModGUI::tick(), NFMModGUI::tick(), WFMModGUI::tick(), SSBModGUI::tick(), ATVModGUI::tick(), SDRPlayGui::updateHardware(), Bladerf1OutputGui::updateHardware(), KiwiSDRGui::updateHardware(), BladeRF2OutputGui::updateHardware(), LocalOutputGui::updateHardware(), PerseusGui::updateHardware(), FCDProPlusGui::updateHardware(), FileSinkGui::updateHardware(), Bladerf1InputGui::updateHardware(), AirspyGui::updateHardware(), PlutoSDROutputGUI::updateHardware(), AirspyHFGui::updateHardware(), BladeRF2InputGui::updateHardware(), XTRXOutputGUI::updateHardware(), RTLSDRGui::updateHardware(), HackRFOutputGui::updateHardware(), LimeSDROutputGUI::updateHardware(), TestSourceGui::updateHardware(), PlutoSDRInputGui::updateHardware(), HackRFInputGui::updateHardware(), FCDProGui::updateHardware(), XTRXInputGUI::updateHardware(), TestMIGui::updateHardware(), LimeSDRInputGUI::updateHardware(), LocalInputGui::updateHardware(), RemoteInputGui::updateHardware(), SoapySDROutputGui::updateHardware(), SoapySDRInputGui::updateHardware(), RemoteOutputSinkGui::updateHardware(), XTRXOutputGUI::updateStatus(), LimeSDROutputGUI::updateStatus(), XTRXInputGUI::updateStatus(), LimeSDRInputGUI::updateStatus(), PlutoSDROutput::webapiRun(), PlutoSDRInput::webapiRun(), Bladerf1Output::webapiRun(), HackRFOutput::webapiRun(), TestSourceInput::webapiRun(), FCDProPlusInput::webapiRun(), AirspyInput::webapiRun(), Bladerf1Input::webapiRun(), RTLSDRInput::webapiRun(), PerseusInput::webapiRun(), AirspyHFInput::webapiRun(), TestMI::webapiRun(), FCDProInput::webapiRun(), LocalOutput::webapiRun(), BladeRF2Output::webapiRun(), HackRFInput::webapiRun(), KiwiSDRInput::webapiRun(), LocalInput::webapiRun(), RemoteOutput::webapiRun(), SDRPlayInput::webapiRun(), SoapySDROutput::webapiRun(), BladeRF2Input::webapiRun(), FileSinkOutput::webapiRun(), SoapySDRInput::webapiRun(), XTRXOutput::webapiRun(), LimeSDROutput::webapiRun(), XTRXInput::webapiRun(), LimeSDRInput::webapiRun(), RemoteInput::webapiRun(), FileInput::webapiRun(), PlutoSDROutput::webapiSettingsPutPatch(), Bladerf1Output::webapiSettingsPutPatch(), HackRFOutput::webapiSettingsPutPatch(), TestSourceInput::webapiSettingsPutPatch(), AirspyInput::webapiSettingsPutPatch(), PerseusInput::webapiSettingsPutPatch(), RTLSDRInput::webapiSettingsPutPatch(), AirspyHFInput::webapiSettingsPutPatch(), UDPSource::webapiSettingsPutPatch(), Bladerf1Input::webapiSettingsPutPatch(), AMDemod::webapiSettingsPutPatch(), LocalOutput::webapiSettingsPutPatch(), TestMI::webapiSettingsPutPatch(), FCDProInput::webapiSettingsPutPatch(), UDPSink::webapiSettingsPutPatch(), LocalSink::webapiSettingsPutPatch(), PlutoSDRInput::webapiSettingsPutPatch(), LocalSource::webapiSettingsPutPatch(), BladeRF2Output::webapiSettingsPutPatch(), RemoteSink::webapiSettingsPutPatch(), FCDProPlusInput::webapiSettingsPutPatch(), HackRFInput::webapiSettingsPutPatch(), KiwiSDRInput::webapiSettingsPutPatch(), WFMDemod::webapiSettingsPutPatch(), LocalInput::webapiSettingsPutPatch(), NFMDemod::webapiSettingsPutPatch(), RemoteOutput::webapiSettingsPutPatch(), FreqTracker::webapiSettingsPutPatch(), DSDDemod::webapiSettingsPutPatch(), SDRPlayInput::webapiSettingsPutPatch(), SoapySDROutput::webapiSettingsPutPatch(), SSBDemod::webapiSettingsPutPatch(), BladeRF2Input::webapiSettingsPutPatch(), FreeDVDemod::webapiSettingsPutPatch(), SoapySDRInput::webapiSettingsPutPatch(), BFMDemod::webapiSettingsPutPatch(), XTRXOutput::webapiSettingsPutPatch(), LimeSDROutput::webapiSettingsPutPatch(), RemoteSource::webapiSettingsPutPatch(), XTRXInput::webapiSettingsPutPatch(), LimeSDRInput::webapiSettingsPutPatch(), AMMod::webapiSettingsPutPatch(), WFMMod::webapiSettingsPutPatch(), NFMMod::webapiSettingsPutPatch(), SSBMod::webapiSettingsPutPatch(), FreeDVMod::webapiSettingsPutPatch(), RemoteInput::webapiSettingsPutPatch(), FileInput::webapiSettingsPutPatch(), FileSource::webapiSettingsPutPatch(), and ATVMod::webapiSettingsPutPatch().
 {
     if (message)
     {
         m_lock.lock();
         m_queue.append(message);
         m_lock.unlock();
     }
     if (emitSignal)
     {
         emit messageEnqueued();
     }
 }
size()
int MessageQueue::size ()
Returns queue size.
Definition at line 71 of file messagequeue.cpp.
References m_lock, and m_queue.
Referenced by DSPDeviceSinkEngine::gotoRunning(), DSPDeviceSourceEngine::gotoRunning(), DSPDeviceMIMOEngine::gotoRunning(), ThreadedBasebandSampleSinkFifo::handleFifoData(), AMBEWorker::handleInputMessages(), DSPDeviceSourceEngine::work(), DSPDeviceMIMOEngine::work(), and DSPDeviceMIMOEngine::workSampleSink().
 {
     QMutexLocker locker(&m_lock);
     return m_queue.size();
 }
Member Data Documentation
m_lock
QMutex MessageQueue::m_lock private
Definition at line 46 of file messagequeue.h.
Referenced by clear(), pop(), push(), and size().
m_queue
QQueue<Message*> MessageQueue::m_queue private
Definition at line 47 of file messagequeue.h.
Referenced by clear(), pop(), push(), and size().
The documentation for this class was generated from the following files:
sdrbase/util/messagequeue.h
sdrbase/util/messagequeue.cpp