SDRAngel: qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal Class Reference
qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal Class Reference
Public Member Functions
RTCPSDESInfoInternal ()
void ClearFlags ()
bool ProcessedName () const
bool ProcessedEMail () const
bool ProcessedLocation () const
bool ProcessedPhone () const
bool ProcessedTool () const
bool ProcessedNote () const
void SetProcessedName (bool v)
void SetProcessedEMail (bool v)
void SetProcessedLocation (bool v)
void SetProcessedPhone (bool v)
void SetProcessedTool (bool v)
void SetProcessedNote (bool v)
Public Member Functions inherited from qrtplib::RTCPSDESInfo
RTCPSDESInfo ()
virtual ~RTCPSDESInfo ()
void Clear ()
int SetCNAME (const uint8_t *s, std::size_t l)
int SetName (const uint8_t *s, std::size_t l)
int SetEMail (const uint8_t *s, std::size_t l)
int SetPhone (const uint8_t *s, std::size_t l)
int SetLocation (const uint8_t *s, std::size_t l)
int SetTool (const uint8_t *s, std::size_t l)
int SetNote (const uint8_t *s, std::size_t l)
int SetPrivateValue (const uint8_t *prefix, std::size_t prefixlen, const uint8_t *value, std::size_t valuelen)
int DeletePrivatePrefix (const uint8_t *s, std::size_t len)
uint8_t * GetCNAME (std::size_t *len) const
uint8_t * GetName (std::size_t *len) const
uint8_t * GetEMail (std::size_t *len) const
uint8_t * GetPhone (std::size_t *len) const
uint8_t * GetLocation (std::size_t *len) const
uint8_t * GetTool (std::size_t *len) const
uint8_t * GetNote (std::size_t *len) const
void GotoFirstPrivateValue ()
bool GetNextPrivateValue (uint8_t **prefix, std::size_t *prefixlen, uint8_t **value, std::size_t *valuelen)
bool GetPrivateValue (const uint8_t *prefix, std::size_t prefixlen, uint8_t **value, std::size_t *valuelen) const
Private Attributes
bool pname
bool pemail
bool plocation
bool pphone
bool ptool
bool pnote
Detailed Description
Definition at line 284 of file rtcppacketbuilder.h.
Constructor & Destructor Documentation
RTCPSDESInfoInternal()
qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::RTCPSDESInfoInternal () inline
Definition at line 287 of file rtcppacketbuilder.h.
         {
             ClearFlags();
         }
Member Function Documentation
ClearFlags()
void qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::ClearFlags () inline
Definition at line 291 of file rtcppacketbuilder.h.
Referenced by qrtplib::RTCPPacketBuilder::ClearAllSDESFlags().
         {
             pname = false;
             pemail = false;
             plocation = false;
             pphone = false;
             ptool = false;
             pnote = false;
         }
ProcessedEMail()
bool qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::ProcessedEMail () const inline
Definition at line 304 of file rtcppacketbuilder.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
         {
             return pemail;
         }
ProcessedLocation()
bool qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::ProcessedLocation () const inline
Definition at line 308 of file rtcppacketbuilder.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
         {
             return plocation;
         }
ProcessedName()
bool qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::ProcessedName () const inline
Definition at line 300 of file rtcppacketbuilder.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
         {
             return pname;
         }
ProcessedNote()
bool qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::ProcessedNote () const inline
Definition at line 320 of file rtcppacketbuilder.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
         {
             return pnote;
         }
ProcessedPhone()
bool qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::ProcessedPhone () const inline
Definition at line 312 of file rtcppacketbuilder.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
         {
             return pphone;
         }
ProcessedTool()
bool qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::ProcessedTool () const inline
Definition at line 316 of file rtcppacketbuilder.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
         {
             return ptool;
         }
SetProcessedEMail()
void qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::SetProcessedEMail (bool v) inline
Definition at line 328 of file rtcppacketbuilder.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
         {
             pemail = v;
         }
SetProcessedLocation()
void qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::SetProcessedLocation (bool v) inline
Definition at line 332 of file rtcppacketbuilder.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
         {
             plocation = v;
         }
SetProcessedName()
void qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::SetProcessedName (bool v) inline
Definition at line 324 of file rtcppacketbuilder.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
         {
             pname = v;
         }
SetProcessedNote()
void qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::SetProcessedNote (bool v) inline
Definition at line 344 of file rtcppacketbuilder.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
         {
             pnote = v;
         }
SetProcessedPhone()
void qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::SetProcessedPhone (bool v) inline
Definition at line 336 of file rtcppacketbuilder.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
         {
             pphone = v;
         }
SetProcessedTool()
void qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::SetProcessedTool (bool v) inline
Definition at line 340 of file rtcppacketbuilder.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInSDES().
         {
             ptool = v;
         }
Member Data Documentation
pemail
bool qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::pemail private
Definition at line 349 of file rtcppacketbuilder.h.
plocation
bool qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::plocation private
Definition at line 349 of file rtcppacketbuilder.h.
pname
bool qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::pname private
Definition at line 349 of file rtcppacketbuilder.h.
pnote
bool qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::pnote private
Definition at line 349 of file rtcppacketbuilder.h.
pphone
bool qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::pphone private
Definition at line 349 of file rtcppacketbuilder.h.
ptool
bool qrtplib::RTCPPacketBuilder::RTCPSDESInfoInternal::ptool private
Definition at line 349 of file rtcppacketbuilder.h.
The documentation for this class was generated from the following file:
qrtplib/rtcppacketbuilder.h