SDRAngel: DevicePlutoSDRParams Class Reference
DevicePlutoSDRParams Class Reference
#include <deviceplutosdrparams.h>
Public Member Functions
DevicePlutoSDRParams ()
~DevicePlutoSDRParams ()
bool open (const std::string &serial)
void close ()
DevicePlutoSDRBox * getBox ()
Private Attributes
DevicePlutoSDRBox * m_box
Detailed Description
This structure refers to one physical device shared among parties (logical devices represented by the DeviceAPI with single Rx or Tx stream type). It allows storing information on the common resources in one place and is shared among participants. There is only one copy that is constructed by the first participant and destroyed by the last. A participant knows it is the first or last by checking the lists of buddies (Rx + Tx).
Definition at line 34 of file deviceplutosdrparams.h.
Constructor & Destructor Documentation
DevicePlutoSDRParams()
DevicePlutoSDRParams::DevicePlutoSDRParams ()
Definition at line 22 of file deviceplutosdrparams.cpp.
                                            :
     m_box(0)
 {
 }
~DevicePlutoSDRParams()
DevicePlutoSDRParams::~DevicePlutoSDRParams ()
Definition at line 27 of file deviceplutosdrparams.cpp.
 {
 }
Member Function Documentation
close()
void DevicePlutoSDRParams::close ()
Definition at line 37 of file deviceplutosdrparams.cpp.
References m_box.
Referenced by PlutoSDROutput::closeDevice(), and PlutoSDRInput::closeDevice().
 {
     delete m_box;
     m_box = 0;
 }
getBox()
DevicePlutoSDRBox* DevicePlutoSDRParams::getBox () inline
Definition at line 43 of file deviceplutosdrparams.h.
Referenced by PlutoSDROutput::applySettings(), PlutoSDRInput::applySettings(), PlutoSDROutput::closeDevice(), PlutoSDRInput::closeDevice(), PlutoSDROutput::fetchTemperature(), PlutoSDRInput::fetchTemperature(), PlutoSDROutput::getbbLPRange(), PlutoSDRInput::getbbLPRange(), PlutoSDRInput::getGain(), PlutoSDROutput::getLORange(), PlutoSDRInput::getLORange(), PlutoSDROutput::getRSSI(), PlutoSDRInput::getRSSI(), PlutoSDROutput::getTemperature(), PlutoSDRInput::getTemperature(), PlutoSDROutput::openDevice(), PlutoSDRInput::openDevice(), PlutoSDROutput::start(), and PlutoSDRInput::start().
 { return m_box; }
open()
bool DevicePlutoSDRParams::open (const std::string & serial)
Definition at line 31 of file deviceplutosdrparams.cpp.
References DevicePlutoSDR::getDeviceFromSerial(), DevicePlutoSDR::instance(), and m_box.
Referenced by PlutoSDROutput::openDevice(), and PlutoSDRInput::openDevice().
 {
     m_box = DevicePlutoSDR::instance().getDeviceFromSerial(serial);
     return m_box != 0;
 }
Member Data Documentation
m_box
DevicePlutoSDRBox* DevicePlutoSDRParams::m_box private
Definition at line 46 of file deviceplutosdrparams.h.
Referenced by close(), and open().
The documentation for this class was generated from the following files:
devices/plutosdr/deviceplutosdrparams.h
devices/plutosdr/deviceplutosdrparams.cpp