SDRAngel: ExternalClockButton Class Reference
ExternalClockButton Class Reference
#include <externalclockbutton.h>
Inherits QPushButton.
Public Member Functions
ExternalClockButton (QWidget *parent=0)
qint64 getExternalClockFrequency () const
bool getExternalClockActive () const
void setExternalClockFrequency (qint64 deltaFrequency)
void setExternalClockActive (bool active)
Private Slots
void onClicked ()
Private Member Functions
void updateState ()
Private Attributes
qint64 m_externalClockFrequency
bool m_externalClockActive
Detailed Description
Definition at line 29 of file externalclockbutton.h.
Constructor & Destructor Documentation
ExternalClockButton()
ExternalClockButton::ExternalClockButton (QWidget * parent = 0)
Definition at line 25 of file externalclockbutton.cpp.
References onClicked().
                                                         :
     QPushButton(parent),
     m_externalClockFrequency(0),
     m_externalClockActive(false)
 {
     setObjectName("ExternalClockButton");
     connect(this, SIGNAL(clicked()), this, SLOT(onClicked()));
 }
Member Function Documentation
getExternalClockActive()
bool ExternalClockButton::getExternalClockActive () const inline
Definition at line 35 of file externalclockbutton.h.
 { return m_externalClockActive; }
getExternalClockFrequency()
qint64 ExternalClockButton::getExternalClockFrequency () const inline
Definition at line 34 of file externalclockbutton.h.
 { return m_externalClockFrequency; }
onClicked
void ExternalClockButton::onClicked () private slot
Definition at line 34 of file externalclockbutton.cpp.
References m_externalClockActive, m_externalClockFrequency, and updateState().
Referenced by ExternalClockButton().
 {
     ExternalClockDialog externalClockDialog(m_externalClockFrequency, m_externalClockActive, this);
     externalClockDialog.exec();
     updateState();
 }
setExternalClockActive()
void ExternalClockButton::setExternalClockActive (bool active) inline
Definition at line 43 of file externalclockbutton.h.
     {
         m_externalClockActive = active;
         updateState();
     }
setExternalClockFrequency()
void ExternalClockButton::setExternalClockFrequency (qint64 deltaFrequency) inline
Definition at line 37 of file externalclockbutton.h.
     {
         m_externalClockFrequency = deltaFrequency;
         updateState();
     }
updateState()
void ExternalClockButton::updateState () private
Definition at line 41 of file externalclockbutton.cpp.
References arg(), m_externalClockActive, and m_externalClockFrequency.
Referenced by onClicked().
 {
     setToolTip(tr("External clock dialog. External clock frequency %1 MHz %2")
             .arg(m_externalClockFrequency/1000000.0)
             .arg(m_externalClockActive ? "enabled" : "disabled"));
     if(m_externalClockActive)
     {
         setStyleSheet("ExternalClockButton { background:rgb(128, 70, 0); }");
     }
     else
     {
         setStyleSheet("ExternalClockButton { background:rgb(48, 48, 48); }");
     }
 }
Member Data Documentation
m_externalClockActive
bool ExternalClockButton::m_externalClockActive private
Definition at line 54 of file externalclockbutton.h.
Referenced by onClicked(), and updateState().
m_externalClockFrequency
qint64 ExternalClockButton::m_externalClockFrequency private
Definition at line 53 of file externalclockbutton.h.
Referenced by onClicked(), and updateState().
The documentation for this class was generated from the following files:
sdrgui/gui/externalclockbutton.h
sdrgui/gui/externalclockbutton.cpp