SDRAngel: leansdr::pipebuf_common Struct Reference
leansdr::pipebuf_common Struct Reference
#include <framework.h>
Public Member Functions
virtual int sizeofT ()
virtual long long hash ()
virtual void dump (std::size_t *total_bufs)
pipebuf_common (const char *_name)
virtual ~pipebuf_common ()
Public Attributes
const char * name
Detailed Description
Definition at line 53 of file framework.h.
Constructor & Destructor Documentation
pipebuf_common()
leansdr::pipebuf_common::pipebuf_common (const char * _name) inline
Definition at line 72 of file framework.h.
                                       : name(_name)
     {
     }
~pipebuf_common()
virtual leansdr::pipebuf_common::~pipebuf_common () inline virtual
Definition at line 76 of file framework.h.
     {
     }
Member Function Documentation
dump()
virtual void leansdr::pipebuf_common::dump (std::size_t * total_bufs) inline virtual
Reimplemented in leansdr::pipebuf< T >, leansdr::pipebuf< SOFTSYMB >, leansdr::pipebuf< leansdr::rspacket< Tbyte > >, leansdr::pipebuf< Tin >, leansdr::pipebuf< unsigned long >, leansdr::pipebuf< leansdr::plslot< SOFTSYMB > >, leansdr::pipebuf< leansdr::rspacket< u8 > >, leansdr::pipebuf< decoded_byte >, leansdr::pipebuf< float >, leansdr::pipebuf< leansdr::bbframe >, leansdr::pipebuf< int >, leansdr::pipebuf< leansdr::complex< Tin > >, leansdr::pipebuf< complex< u8 > >, leansdr::pipebuf< leansdr::u8 >, leansdr::pipebuf< leansdr::tspacket >, leansdr::pipebuf< Tbyte >, leansdr::pipebuf< leansdr::complex< T > >, leansdr::pipebuf< leansdr::fecframe< hard_sb > >, leansdr::pipebuf< leansdr::complex< Tout > >, leansdr::pipebuf< uncoded_byte >, leansdr::pipebuf< unsigned char >, leansdr::pipebuf< u8 >, leansdr::pipebuf< Tout >, leansdr::pipebuf< leansdr::u32 >, leansdr::pipebuf< leansdr::complex< float > >, leansdr::pipebuf< leansdr::plslot< hard_ss > >, leansdr::pipebuf< leansdr::eucl_ss >, leansdr::pipebuf< leansdr::complex >, leansdr::pipebuf< leansdr::fecframe< SOFTBYTE > >, leansdr::pipebuf< leansdr::f32 >, leansdr::pipebuf< leansdr::rspacket< leansdr::u8 > >, leansdr::pipebuf< hardsymbol >, and leansdr::pipebuf< leansdr::complex< leansdr::f32 > >.
Definition at line 65 of file framework.h.
Referenced by leansdr::scheduler::dump().
     {
         (void)total_bufs;
     }
hash()
virtual long long leansdr::pipebuf_common::hash () inline virtual
Reimplemented in leansdr::pipebuf< T >, leansdr::pipebuf< SOFTSYMB >, leansdr::pipebuf< leansdr::rspacket< Tbyte > >, leansdr::pipebuf< Tin >, leansdr::pipebuf< unsigned long >, leansdr::pipebuf< leansdr::plslot< SOFTSYMB > >, leansdr::pipebuf< leansdr::rspacket< u8 > >, leansdr::pipebuf< decoded_byte >, leansdr::pipebuf< float >, leansdr::pipebuf< leansdr::bbframe >, leansdr::pipebuf< int >, leansdr::pipebuf< leansdr::complex< Tin > >, leansdr::pipebuf< complex< u8 > >, leansdr::pipebuf< leansdr::u8 >, leansdr::pipebuf< leansdr::tspacket >, leansdr::pipebuf< Tbyte >, leansdr::pipebuf< leansdr::complex< T > >, leansdr::pipebuf< leansdr::fecframe< hard_sb > >, leansdr::pipebuf< leansdr::complex< Tout > >, leansdr::pipebuf< uncoded_byte >, leansdr::pipebuf< unsigned char >, leansdr::pipebuf< u8 >, leansdr::pipebuf< Tout >, leansdr::pipebuf< leansdr::u32 >, leansdr::pipebuf< leansdr::complex< float > >, leansdr::pipebuf< leansdr::plslot< hard_ss > >, leansdr::pipebuf< leansdr::eucl_ss >, leansdr::pipebuf< leansdr::complex >, leansdr::pipebuf< leansdr::fecframe< SOFTBYTE > >, leansdr::pipebuf< leansdr::f32 >, leansdr::pipebuf< leansdr::rspacket< leansdr::u8 > >, leansdr::pipebuf< hardsymbol >, and leansdr::pipebuf< leansdr::complex< leansdr::f32 > >.
Definition at line 60 of file framework.h.
Referenced by leansdr::scheduler::hash(), and leansdr::scheduler::run().
     {
         return 0;
     }
sizeofT()
virtual int leansdr::pipebuf_common::sizeofT () inline virtual
Reimplemented in leansdr::pipebuf< T >, leansdr::pipebuf< SOFTSYMB >, leansdr::pipebuf< leansdr::rspacket< Tbyte > >, leansdr::pipebuf< Tin >, leansdr::pipebuf< unsigned long >, leansdr::pipebuf< leansdr::plslot< SOFTSYMB > >, leansdr::pipebuf< leansdr::rspacket< u8 > >, leansdr::pipebuf< decoded_byte >, leansdr::pipebuf< float >, leansdr::pipebuf< leansdr::bbframe >, leansdr::pipebuf< int >, leansdr::pipebuf< leansdr::complex< Tin > >, leansdr::pipebuf< complex< u8 > >, leansdr::pipebuf< leansdr::u8 >, leansdr::pipebuf< leansdr::tspacket >, leansdr::pipebuf< Tbyte >, leansdr::pipebuf< leansdr::complex< T > >, leansdr::pipebuf< leansdr::fecframe< hard_sb > >, leansdr::pipebuf< leansdr::complex< Tout > >, leansdr::pipebuf< uncoded_byte >, leansdr::pipebuf< unsigned char >, leansdr::pipebuf< u8 >, leansdr::pipebuf< Tout >, leansdr::pipebuf< leansdr::u32 >, leansdr::pipebuf< leansdr::complex< float > >, leansdr::pipebuf< leansdr::plslot< hard_ss > >, leansdr::pipebuf< leansdr::eucl_ss >, leansdr::pipebuf< leansdr::complex >, leansdr::pipebuf< leansdr::fecframe< SOFTBYTE > >, leansdr::pipebuf< leansdr::f32 >, leansdr::pipebuf< leansdr::rspacket< leansdr::u8 > >, leansdr::pipebuf< hardsymbol >, and leansdr::pipebuf< leansdr::complex< leansdr::f32 > >.
Definition at line 55 of file framework.h.
     {
         return 0;
     }
Member Data Documentation
name
const char* leansdr::pipebuf_common::name
Definition at line 70 of file framework.h.
Referenced by leansdr::pipebuf< leansdr::complex< leansdr::f32 > >::dump(), leansdr::pipereader< leansdr::complex< leansdr::f32 > >::read(), and leansdr::pipewriter< leansdr::complex< leansdr::f32 > >::written().
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/framework.h