SDRAngel: SimpleSerializer Class Reference
SimpleSerializer Class Reference
#include <simpleserializer.h>
Public Member Functions
SimpleSerializer (quint32 version)
void writeS32 (quint32 id, qint32 value)
void writeU32 (quint32 id, quint32 value)
void writeS64 (quint32 id, qint64 value)
void writeU64 (quint32 id, quint64 value)
void writeFloat (quint32 id, float value)
void writeDouble (quint32 id, double value)
void writeReal (quint32 id, Real value)
void writeBool (quint32 id, bool value)
void writeString (quint32 id, const QString &value)
void writeBlob (quint32 id, const QByteArray &value)
const QByteArray & final ()
Protected Types
enum Type {
TSigned32 = 0, TUnsigned32 = 1, TSigned64 = 2, TUnsigned64 = 3,
TFloat = 4, TDouble = 5, TBool = 6, TString = 7,
TBlob = 8, TVersion = 9
}
Protected Member Functions
bool writeTag (Type type, quint32 id, quint32 length)
Protected Attributes
QByteArray m_data
bool m_finalized
Detailed Description
Definition at line 9 of file simpleserializer.h.
Member Enumeration Documentation
Type
enum SimpleSerializer::Type protected
Enumerator
TSigned32
TUnsigned32
TSigned64
TUnsigned64
TFloat
TDouble
TBool
TString
TBlob
TVersion
Definition at line 32 of file simpleserializer.h.
               {
         TSigned32 = 0,
         TUnsigned32 = 1,
         TSigned64 = 2,
         TUnsigned64 = 3,
         TFloat = 4,
         TDouble = 5,
         TBool = 6,
         TString = 7,
         TBlob = 8,
         TVersion = 9
     };
Constructor & Destructor Documentation
SimpleSerializer()
SimpleSerializer::SimpleSerializer (quint32 version)
Definition at line 20 of file simpleserializer.cpp.
References i, m_data, TVersion, and writeTag().
                                                :
     m_data(),
     m_finalized(false)
 {
     m_data.reserve(100);
     // write version information
     int length;
     if(version >= (1 << 24))
         length = 4;
     else if(version >= (1 << 16))
         length = 3;
     else if(version >= (1 << 8))
         length = 2;
     else if(version > 0)
         length = 1;
     else length = 0;
     if(!writeTag(TVersion, 0, length))
         return;
     length--;
     for(int i = length; i >= 0; i--)
         m_data.push_back((char)((version >> (i * 8)) & 0xff));
 }
Member Function Documentation
final()
const QByteArray & SimpleSerializer::final ()
Definition at line 257 of file simpleserializer.cpp.
References m_data, and m_finalized.
Referenced by Preferences::serialize(), LoRaDemodSettings::serialize(), FileSinkSettings::serialize(), LocalOutputSettings::serialize(), GLSpectrumGUI::serialize(), LocalInputSettings::serialize(), RemoteInputSettings::serialize(), Command::serialize(), FileInputSettings::serialize(), KiwiSDRSettings::serialize(), BladeRF2OutputSettings::serialize(), RemoteOutputSettings::serialize(), BladeRF1OutputSettings::serialize(), RemoteSourceSettings::serialize(), LocalSourceSettings::serialize(), LocalSinkSettings::serialize(), FileSourceSettings::serialize(), AirspyHFSettings::serialize(), HackRFOutputSettings::serialize(), SoapySDROutputSettings::serialize(), HackRFInputSettings::serialize(), DeviceUserArgs::serialize(), BladeRF2InputSettings::serialize(), WFMDemodSettings::serialize(), ATVDemodGUI::serialize(), AirspySettings::serialize(), BladeRF1InputSettings::serialize(), FCDProPlusSettings::serialize(), PerseusSettings::serialize(), RTLSDRSettings::serialize(), RemoteSinkSettings::serialize(), CWKeyerSettings::serialize(), BFMDemodSettings::serialize(), XTRXOutputSettings::serialize(), AMDemodSettings::serialize(), SDRPlaySettings::serialize(), PlutoSDROutputSettings::serialize(), NFMDemodSettings::serialize(), SSBDemodSettings::serialize(), GLScopeGUI::serialize(), ChannelAnalyzerSettings::serialize(), FreqTrackerSettings::serialize(), FreeDVDemodSettings::serialize(), FCDProSettings::serialize(), SoapySDRInputSettings::serialize(), DSDDemodSettings::serialize(), AMModSettings::serialize(), WFMModSettings::serialize(), XTRXInputSettings::serialize(), Preset::serialize(), LimeSDROutputSettings::serialize(), TestSourceSettings::serialize(), NFMModSettings::serialize(), UDPSourceSettings::serialize(), FreeDVModSettings::serialize(), SSBModSettings::serialize(), UDPSinkSettings::serialize(), TestMISettings::serialize(), LimeSDRInputSettings::serialize(), ChannelMarker::serialize(), PlutoSDRInputSettings::serialize(), ATVModSettings::serialize(), ATVDemodSettings::serialize(), DoubleBufferSimple< Sample >::serialize(), DATVDemodSettings::serialize(), AudioDeviceManager::serialize(), SoapySDRInput::serialize(), ScopeVis::TraceBackBuffer::serialize(), ScopeVis::TraceBackDiscreteMemory::serialize(), ScopeVis::serializeMemory(), and SampleSourceSerializer::writeSerializedData().
 {
     m_finalized = true;
     return m_data;
 }
writeBlob()
void SimpleSerializer::writeBlob (quint32 id, const QByteArray & value)
Definition at line 245 of file simpleserializer.cpp.
References m_data, TBlob, and writeTag().
Referenced by LoRaDemodSettings::serialize(), SoapySDROutputSettings::serialize(), DeviceUserArgs::serialize(), WFMDemodSettings::serialize(), BFMDemodSettings::serialize(), AMDemodSettings::serialize(), NFMDemodSettings::serialize(), SSBDemodSettings::serialize(), ChannelAnalyzerSettings::serialize(), FreqTrackerSettings::serialize(), FreeDVDemodSettings::serialize(), SoapySDRInputSettings::serialize(), DSDDemodSettings::serialize(), AMModSettings::serialize(), WFMModSettings::serialize(), Preset::serialize(), NFMModSettings::serialize(), UDPSourceSettings::serialize(), FreeDVModSettings::serialize(), SSBModSettings::serialize(), UDPSinkSettings::serialize(), ATVModSettings::serialize(), ATVDemodSettings::serialize(), DoubleBufferSimple< Sample >::serialize(), DATVDemodSettings::serialize(), AudioDeviceManager::serialize(), ScopeVis::TraceBackBuffer::serialize(), ScopeVis::TraceBackDiscreteMemory::serialize(), and ScopeVis::serializeMemory().
 {
     if(id == 0) {
         qCritical("SimpleSerializer: ID 0 is not allowed");
         return;
     }
     if(!writeTag(TBlob, id, value.size()))
         return;
     m_data.append(value);
 }
writeBool()
void SimpleSerializer::writeBool (quint32 id, bool value)
Definition at line 218 of file simpleserializer.cpp.
References m_data, TBool, and writeTag().
Referenced by Preferences::serialize(), LocalInputSettings::serialize(), GLSpectrumGUI::serialize(), RemoteInputSettings::serialize(), Command::serialize(), BladeRF2OutputSettings::serialize(), FileInputSettings::serialize(), KiwiSDRSettings::serialize(), RemoteOutputSettings::serialize(), RemoteSourceSettings::serialize(), BladeRF1OutputSettings::serialize(), LocalSourceSettings::serialize(), LocalSinkSettings::serialize(), FileSourceSettings::serialize(), AirspyHFSettings::serialize(), HackRFOutputSettings::serialize(), SoapySDROutputSettings::serialize(), HackRFInputSettings::serialize(), BladeRF2InputSettings::serialize(), WFMDemodSettings::serialize(), ATVDemodGUI::serialize(), AirspySettings::serialize(), BladeRF1InputSettings::serialize(), FCDProPlusSettings::serialize(), PerseusSettings::serialize(), RTLSDRSettings::serialize(), CWKeyerSettings::serialize(), RemoteSinkSettings::serialize(), XTRXOutputSettings::serialize(), BFMDemodSettings::serialize(), AMDemodSettings::serialize(), SDRPlaySettings::serialize(), NFMDemodSettings::serialize(), SSBDemodSettings::serialize(), GLScopeGUI::serialize(), PlutoSDROutputSettings::serialize(), ChannelAnalyzerSettings::serialize(), FreqTrackerSettings::serialize(), FreeDVDemodSettings::serialize(), FCDProSettings::serialize(), DSDDemodSettings::serialize(), SoapySDRInputSettings::serialize(), AMModSettings::serialize(), WFMModSettings::serialize(), XTRXInputSettings::serialize(), Preset::serialize(), NFMModSettings::serialize(), LimeSDROutputSettings::serialize(), TestSourceSettings::serialize(), UDPSourceSettings::serialize(), FreeDVModSettings::serialize(), SSBModSettings::serialize(), LimeSDRInputSettings::serialize(), UDPSinkSettings::serialize(), TestMISettings::serialize(), PlutoSDRInputSettings::serialize(), ATVModSettings::serialize(), ATVDemodSettings::serialize(), and DATVDemodSettings::serialize().
 {
     if(id == 0) {
         qCritical("SimpleSerializer: ID 0 is not allowed");
         return;
     }
     if(!writeTag(TBool, id, 1))
         return;
     if(value)
         m_data.push_back((char)0x01);
     else m_data.push_back((char)0x00);
 }
writeDouble()
void SimpleSerializer::writeDouble (quint32 id, double value)
Definition at line 196 of file simpleserializer.cpp.
References doubleasint::d, m_data, TDouble, doubleasint::u, and writeTag().
Referenced by SoapySDROutputSettings::serialize(), XTRXOutputSettings::serialize(), SoapySDRInputSettings::serialize(), and XTRXInputSettings::serialize().
 {
     union doubleasint tmp;
     if(id == 0) {
         qCritical("SimpleSerializer: ID 0 is not allowed");
         return;
     }
     if(!writeTag(TDouble, id, 8))
         return;
     tmp.d = value;
     m_data.push_back((char)((tmp.u >> 56) & 0xff));
     m_data.push_back((char)((tmp.u >> 48) & 0xff));
     m_data.push_back((char)((tmp.u >> 40) & 0xff));
     m_data.push_back((char)((tmp.u >> 32) & 0xff));
     m_data.push_back((char)((tmp.u >> 24) & 0xff));
     m_data.push_back((char)((tmp.u >> 16) & 0xff));
     m_data.push_back((char)((tmp.u >> 8) & 0xff));
     m_data.push_back((char)(tmp.u & 0xff));
 }
writeFloat()
void SimpleSerializer::writeFloat (quint32 id, float value)
Definition at line 173 of file simpleserializer.cpp.
References floatasint::f, m_data, TFloat, floatasint::u, and writeTag().
Referenced by Preferences::serialize(), RemoteOutputSettings::serialize(), XTRXOutputSettings::serialize(), GLScopeGUI::serialize(), FreqTrackerSettings::serialize(), XTRXInputSettings::serialize(), TestSourceSettings::serialize(), LimeSDROutputSettings::serialize(), TestMISettings::serialize(), LimeSDRInputSettings::serialize(), and DATVDemodSettings::serialize().
 {
     union floatasint tmp;
     if(id == 0) {
         qCritical("SimpleSerializer: ID 0 is not allowed");
         return;
     }
     if(!writeTag(TFloat, id, 4))
         return;
     tmp.f = value;
     m_data.push_back((char)((tmp.u >> 24) & 0xff));
     m_data.push_back((char)((tmp.u >> 16) & 0xff));
     m_data.push_back((char)((tmp.u >> 8) & 0xff));
     m_data.push_back((char)(tmp.u & 0xff));
 }
writeReal()
void SimpleSerializer::writeReal (quint32 id, Real value) inline
Definition at line 19 of file simpleserializer.h.
Referenced by GLSpectrumGUI::serialize(), AMModSettings::serialize(), WFMModSettings::serialize(), NFMModSettings::serialize(), UDPSourceSettings::serialize(), SSBModSettings::serialize(), UDPSinkSettings::serialize(), and ATVModSettings::serialize().
     {
         if(sizeof(Real) == 4)
             writeFloat(id, value);
         else writeDouble(id, value);
     }
writeS32()
void SimpleSerializer::writeS32 (quint32 id, qint32 value)
Definition at line 44 of file simpleserializer.cpp.
References i, m_data, TSigned32, and writeTag().
Referenced by Preferences::serialize(), LoRaDemodSettings::serialize(), GLSpectrumGUI::serialize(), Command::serialize(), BladeRF2OutputSettings::serialize(), BladeRF1OutputSettings::serialize(), FileSourceSettings::serialize(), AirspyHFSettings::serialize(), HackRFOutputSettings::serialize(), HackRFInputSettings::serialize(), SoapySDROutputSettings::serialize(), BladeRF2InputSettings::serialize(), WFMDemodSettings::serialize(), ATVDemodGUI::serialize(), BladeRF1InputSettings::serialize(), FCDProPlusSettings::serialize(), PerseusSettings::serialize(), RTLSDRSettings::serialize(), CWKeyerSettings::serialize(), AirspySettings::serialize(), BFMDemodSettings::serialize(), XTRXOutputSettings::serialize(), SDRPlaySettings::serialize(), AMDemodSettings::serialize(), NFMDemodSettings::serialize(), SSBDemodSettings::serialize(), GLScopeGUI::serialize(), PlutoSDROutputSettings::serialize(), ChannelAnalyzerSettings::serialize(), FreqTrackerSettings::serialize(), FreeDVDemodSettings::serialize(), FCDProSettings::serialize(), SoapySDRInputSettings::serialize(), DSDDemodSettings::serialize(), AMModSettings::serialize(), WFMModSettings::serialize(), XTRXInputSettings::serialize(), Preset::serialize(), NFMModSettings::serialize(), LimeSDROutputSettings::serialize(), TestSourceSettings::serialize(), UDPSourceSettings::serialize(), FreeDVModSettings::serialize(), SSBModSettings::serialize(), TestMISettings::serialize(), UDPSinkSettings::serialize(), LimeSDRInputSettings::serialize(), ChannelMarker::serialize(), PlutoSDRInputSettings::serialize(), ATVModSettings::serialize(), ATVDemodSettings::serialize(), DoubleBufferSimple< Sample >::serialize(), DATVDemodSettings::serialize(), ScopeVis::serializeMemory(), and SampleSourceSerializer::writeSerializedData().
 {
     int length;
     if(id == 0) {
         qCritical("SimpleSerializer: ID 0 is not allowed");
         return;
     }
     if((value < -(1 << 23)) || (value >= (1 << 23)))
         length = 4;
     else if((value < -(1 << 15)) || (value >= (1 << 15)))
         length = 3;
     else if((value < -(1 << 7)) || (value >= (1 << 7)))
         length = 2;
     else if(value != 0)
         length = 1;
     else length = 0;
     if(!writeTag(TSigned32, id, length))
         return;
     length--;
     for(int i = length; i >= 0; i--)
         m_data.push_back((char)((value >> (i * 8)) & 0xff));
 }
writeS64()
void SimpleSerializer::writeS64 (quint32 id, qint64 value)
Definition at line 98 of file simpleserializer.cpp.
References i, m_data, TSigned64, and writeTag().
Referenced by BladeRF2OutputSettings::serialize(), AirspyHFSettings::serialize(), SoapySDROutputSettings::serialize(), BladeRF2InputSettings::serialize(), PerseusSettings::serialize(), FCDProPlusSettings::serialize(), AirspySettings::serialize(), RTLSDRSettings::serialize(), PlutoSDROutputSettings::serialize(), FCDProSettings::serialize(), SoapySDRInputSettings::serialize(), LimeSDROutputSettings::serialize(), LimeSDRInputSettings::serialize(), and PlutoSDRInputSettings::serialize().
 {
     int length;
     if(id == 0) {
         qCritical("SimpleSerializer: ID 0 is not allowed");
         return;
     }
     if((value < -(1ll << 55)) || (value >= (1ll << 55)))
         length = 8;
     else if((value < -(1ll << 47)) || (value >= (1ll << 47)))
         length = 7;
     else if((value < -(1ll << 39)) || (value >= (1ll << 39)))
         length = 6;
     else if((value < -(1ll << 31)) || (value >= (1ll << 31)))
         length = 5;
     else if((value < -(1ll << 23)) || (value >= (1ll << 23)))
         length = 4;
     else if((value < -(1ll << 15)) || (value >= (1ll << 15)))
         length = 3;
     else if((value < -(1ll << 7)) || (value >= (1ll << 7)))
         length = 2;
     else if(value != 0)
         length = 1;
     else length = 0;
     if(!writeTag(TSigned64, id, length))
         return;
     length--;
     for(int i = length; i >= 0; i--)
         m_data.push_back((char)((value >> (i * 8)) & 0xff));
 }
writeString()
void SimpleSerializer::writeString (quint32 id, const QString & value)
Definition at line 232 of file simpleserializer.cpp.
References m_data, TString, and writeTag().
Referenced by Preferences::serialize(), LoRaDemodSettings::serialize(), LocalOutputSettings::serialize(), LocalInputSettings::serialize(), RemoteInputSettings::serialize(), Command::serialize(), FileInputSettings::serialize(), KiwiSDRSettings::serialize(), BladeRF2OutputSettings::serialize(), RemoteOutputSettings::serialize(), BladeRF1OutputSettings::serialize(), RemoteSourceSettings::serialize(), LocalSourceSettings::serialize(), LocalSinkSettings::serialize(), FileSourceSettings::serialize(), AirspyHFSettings::serialize(), HackRFOutputSettings::serialize(), SoapySDROutputSettings::serialize(), HackRFInputSettings::serialize(), WFMDemodSettings::serialize(), BladeRF2InputSettings::serialize(), AirspySettings::serialize(), BladeRF1InputSettings::serialize(), FCDProPlusSettings::serialize(), PerseusSettings::serialize(), RTLSDRSettings::serialize(), CWKeyerSettings::serialize(), RemoteSinkSettings::serialize(), XTRXOutputSettings::serialize(), BFMDemodSettings::serialize(), AMDemodSettings::serialize(), SDRPlaySettings::serialize(), PlutoSDROutputSettings::serialize(), NFMDemodSettings::serialize(), SSBDemodSettings::serialize(), ChannelAnalyzerSettings::serialize(), FreqTrackerSettings::serialize(), FreeDVDemodSettings::serialize(), FCDProSettings::serialize(), DSDDemodSettings::serialize(), SoapySDRInputSettings::serialize(), AMModSettings::serialize(), WFMModSettings::serialize(), XTRXInputSettings::serialize(), Preset::serialize(), LimeSDROutputSettings::serialize(), NFMModSettings::serialize(), TestSourceSettings::serialize(), UDPSourceSettings::serialize(), FreeDVModSettings::serialize(), SSBModSettings::serialize(), TestMISettings::serialize(), UDPSinkSettings::serialize(), LimeSDRInputSettings::serialize(), ChannelMarker::serialize(), PlutoSDRInputSettings::serialize(), ATVModSettings::serialize(), ATVDemodSettings::serialize(), and DATVDemodSettings::serialize().
 {
     if(id == 0) {
         qCritical("SimpleSerializer: ID 0 is not allowed");
         return;
     }
     QByteArray utf8 = value.toUtf8();
     if(!writeTag(TString, id, utf8.size()))
         return;
     m_data.append(utf8);
 }
writeTag()
bool SimpleSerializer::writeTag (Type type, quint32 id, quint32 length) protected
Definition at line 263 of file simpleserializer.cpp.
References i, m_data, and m_finalized.
Referenced by SimpleSerializer(), writeBlob(), writeBool(), writeDouble(), writeFloat(), writeS32(), writeS64(), writeString(), writeU32(), and writeU64().
 {
     if(m_finalized) {
         qCritical("SimpleSerializer: config has already been finalized (id %u)", id);
         return false;
     }
     int idLen;
     int lengthLen;
     if(id < (1 << 8))
         idLen = 0;
     else if(id < (1 << 16))
         idLen = 1;
     else if(id < (1 << 24))
         idLen = 2;
     else idLen = 3;
     if(length < (1 << 8))
         lengthLen = 0;
     else if(length < (1 << 16))
         lengthLen = 1;
     else if(length < (1 << 24))
         lengthLen = 2;
     else lengthLen = 3;
     m_data.push_back((char)((type << 4) | (idLen << 2) | lengthLen));
     for(int i = idLen; i >= 0; i--)
         m_data.push_back((char)((id >> (i * 8)) & 0xff));
     for(int i = lengthLen; i >= 0; i--)
         m_data.push_back((char)((length >> (i * 8)) & 0xff));
     return true;
 }
writeU32()
void SimpleSerializer::writeU32 (quint32 id, quint32 value)
Definition at line 71 of file simpleserializer.cpp.
References i, m_data, TUnsigned32, and writeTag().
Referenced by FileSinkSettings::serialize(), LocalOutputSettings::serialize(), LocalInputSettings::serialize(), RemoteInputSettings::serialize(), FileInputSettings::serialize(), KiwiSDRSettings::serialize(), BladeRF2OutputSettings::serialize(), RemoteOutputSettings::serialize(), RemoteSourceSettings::serialize(), BladeRF1OutputSettings::serialize(), LocalSourceSettings::serialize(), LocalSinkSettings::serialize(), FileSourceSettings::serialize(), AirspyHFSettings::serialize(), HackRFOutputSettings::serialize(), SoapySDROutputSettings::serialize(), HackRFInputSettings::serialize(), BladeRF2InputSettings::serialize(), WFMDemodSettings::serialize(), ATVDemodGUI::serialize(), AirspySettings::serialize(), BladeRF1InputSettings::serialize(), FCDProPlusSettings::serialize(), PerseusSettings::serialize(), RTLSDRSettings::serialize(), CWKeyerSettings::serialize(), RemoteSinkSettings::serialize(), XTRXOutputSettings::serialize(), BFMDemodSettings::serialize(), AMDemodSettings::serialize(), SDRPlaySettings::serialize(), PlutoSDROutputSettings::serialize(), NFMDemodSettings::serialize(), SSBDemodSettings::serialize(), GLScopeGUI::serialize(), ChannelAnalyzerSettings::serialize(), FreqTrackerSettings::serialize(), FreeDVDemodSettings::serialize(), FCDProSettings::serialize(), SoapySDRInputSettings::serialize(), DSDDemodSettings::serialize(), AMModSettings::serialize(), WFMModSettings::serialize(), XTRXInputSettings::serialize(), LimeSDROutputSettings::serialize(), NFMModSettings::serialize(), TestSourceSettings::serialize(), UDPSourceSettings::serialize(), FreeDVModSettings::serialize(), SSBModSettings::serialize(), TestMISettings::serialize(), UDPSinkSettings::serialize(), LimeSDRInputSettings::serialize(), ChannelMarker::serialize(), PlutoSDRInputSettings::serialize(), ATVModSettings::serialize(), ATVDemodSettings::serialize(), DoubleBufferSimple< Sample >::serialize(), DATVDemodSettings::serialize(), ScopeVis::TraceBackBuffer::serialize(), ScopeVis::TraceBackDiscreteMemory::serialize(), ScopeVis::serializeMemory(), and SampleSourceSerializer::writeSerializedData().
 {
     int length;
     if(id == 0) {
         qCritical("SimpleSerializer: ID 0 is not allowed");
         return;
     }
     if(value >= (1 << 24))
         length = 4;
     else if(value >= (1 << 16))
         length = 3;
     else if(value >= (1 << 8))
         length = 2;
     else if(value > 0)
         length = 1;
     else length = 0;
     if(!writeTag(TUnsigned32, id, length))
         return;
     length--;
     for(int i = length; i >= 0; i--)
         m_data.push_back((char)((value >> (i * 8)) & 0xff));
 }
writeU64()
void SimpleSerializer::writeU64 (quint32 id, quint64 value)
Definition at line 133 of file simpleserializer.cpp.
References i, m_data, TUnsigned64, and writeTag().
Referenced by FileSinkSettings::serialize(), RemoteOutputSettings::serialize(), HackRFOutputSettings::serialize(), HackRFInputSettings::serialize(), PlutoSDROutputSettings::serialize(), Preset::serialize(), PlutoSDRInputSettings::serialize(), and SampleSourceSerializer::writeSerializedData().
 {
     int length;
     if(id == 0) {
         qCritical("SimpleSerializer: ID 0 is not allowed");
         return;
     }
     if(value >= (1ll << 56))
         length = 8;
     else if(value >= (1ll << 48))
         length = 7;
     else if(value >= (1ll << 40))
         length = 6;
     else if(value >= (1ll << 32))
         length = 5;
     else if(value >= (1ll << 24))
         length = 4;
     else if(value >= (1ll << 16))
         length = 3;
     else if(value >= (1ll << 8))
         length = 2;
     else if(value > 0)
         length = 1;
     else length = 0;
     if(!writeTag(TUnsigned64, id, length))
         return;
     length--;
     for(int i = length; i >= 0; i--)
         m_data.push_back((char)((value >> (i * 8)) & 0xff));
 }
Member Data Documentation
m_data
QByteArray SimpleSerializer::m_data protected
Definition at line 45 of file simpleserializer.h.
Referenced by final(), SimpleSerializer(), writeBlob(), writeBool(), writeDouble(), writeFloat(), writeS32(), writeS64(), writeString(), writeTag(), writeU32(), and writeU64().
m_finalized
bool SimpleSerializer::m_finalized protected
Definition at line 46 of file simpleserializer.h.
Referenced by final(), and writeTag().
The documentation for this class was generated from the following files:
sdrbase/util/simpleserializer.h
sdrbase/util/simpleserializer.cpp