SDRAngel: SDRPlayInput::MsgStartStop Class Reference
SDRPlayInput::MsgStartStop Class Reference
#include <sdrplayinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 119 of file sdrplayinput.h.
Constructor & Destructor Documentation
MsgStartStop()
SDRPlayInput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 132 of file sdrplayinput.h.
References SDRPlayInput::deserialize(), SDRPlayInput::destroy(), SDRPlayInput::init(), SDRPlayInput::SDRPlayInput(), SDRPlayInput::serialize(), SDRPlayInput::start(), SDRPlayInput::stop(), and SDRPlayInput::~SDRPlayInput().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* SDRPlayInput::MsgStartStop::create (bool startStop) inline static
Definition at line 125 of file sdrplayinput.h.
Referenced by SDRPlayGui::on_startStop_toggled(), and SDRPlayInput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool SDRPlayInput::MsgStartStop::getStartStop () const inline
Definition at line 123 of file sdrplayinput.h.
Referenced by SDRPlayGui::handleMessage(), and SDRPlayInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool SDRPlayInput::MsgStartStop::m_startStop protected
Definition at line 130 of file sdrplayinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/sdrplay/sdrplayinput.h