SDRAngel: SWGSDRangel::SWGDeviceState Class Reference
SWGSDRangel::SWGDeviceState Class Reference
#include <SWGDeviceState.h>
Public Member Functions
SWGDeviceState ()
SWGDeviceState (QString *json)
virtual ~SWGDeviceState ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGDeviceState * fromJson (QString &jsonString) override
QString * getState ()
void setState (QString *state)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * state
bool m_state_isSet
Detailed Description
Definition at line 32 of file SWGDeviceState.h.
Constructor & Destructor Documentation
SWGDeviceState() [1/2]
SWGSDRangel::SWGDeviceState::SWGDeviceState ()
Definition at line 30 of file SWGDeviceState.cpp.
References m_state_isSet, and state.
{
     state = nullptr;
     m_state_isSet = false;
 }
SWGDeviceState() [2/2]
SWGSDRangel::SWGDeviceState::SWGDeviceState (QString * json)
Definition at line 25 of file SWGDeviceState.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGDeviceState()
SWGSDRangel::SWGDeviceState::~SWGDeviceState () virtual
Definition at line 35 of file SWGDeviceState.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGDeviceState::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 68 of file SWGDeviceState.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::devicesetDeviceRunService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGDeviceState::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 79 of file SWGDeviceState.cpp.
References state, and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(state != nullptr && *state != QString("")){
         toJsonValue(QString("state"), state, obj, QString("QString"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGDeviceState::cleanup ()
Definition at line 46 of file SWGDeviceState.cpp.
References state.
Referenced by ~SWGDeviceState().
{
     if(state != nullptr) {
         delete state;
     }
 }
fromJson()
SWGDeviceState * SWGSDRangel::SWGDeviceState::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 53 of file SWGDeviceState.cpp.
References fromJsonObject().
Referenced by SWGDeviceState().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGDeviceState::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 62 of file SWGDeviceState.cpp.
References SWGSDRangel::setValue(), and state.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&state, pJson["state"], "QString", "QString");
 }
getState()
QString * SWGSDRangel::SWGDeviceState::getState ()
Definition at line 89 of file SWGDeviceState.cpp.
References state.
Referenced by PlutoSDROutput::webapiRun(), PlutoSDRInput::webapiRun(), Bladerf1Output::webapiRun(), HackRFOutput::webapiRun(), FCDProPlusInput::webapiRun(), TestSourceInput::webapiRun(), AirspyInput::webapiRun(), Bladerf1Input::webapiRun(), PerseusInput::webapiRun(), RTLSDRInput::webapiRun(), AirspyHFInput::webapiRun(), TestMI::webapiRun(), FCDProInput::webapiRun(), LocalOutput::webapiRun(), BladeRF2Output::webapiRun(), HackRFInput::webapiRun(), KiwiSDRInput::webapiRun(), LocalInput::webapiRun(), RemoteOutput::webapiRun(), SDRPlayInput::webapiRun(), SoapySDROutput::webapiRun(), BladeRF2Input::webapiRun(), FileSinkOutput::webapiRun(), SoapySDRInput::webapiRun(), XTRXOutput::webapiRun(), LimeSDROutput::webapiRun(), XTRXInput::webapiRun(), LimeSDRInput::webapiRun(), RemoteInput::webapiRun(), FileInput::webapiRun(), PlutoSDROutput::webapiRunGet(), PlutoSDRInput::webapiRunGet(), Bladerf1Output::webapiRunGet(), HackRFOutput::webapiRunGet(), FCDProPlusInput::webapiRunGet(), TestSourceInput::webapiRunGet(), AirspyInput::webapiRunGet(), Bladerf1Input::webapiRunGet(), PerseusInput::webapiRunGet(), RTLSDRInput::webapiRunGet(), AirspyHFInput::webapiRunGet(), TestMI::webapiRunGet(), FCDProInput::webapiRunGet(), LocalOutput::webapiRunGet(), BladeRF2Output::webapiRunGet(), HackRFInput::webapiRunGet(), KiwiSDRInput::webapiRunGet(), LocalInput::webapiRunGet(), RemoteOutput::webapiRunGet(), SDRPlayInput::webapiRunGet(), SoapySDROutput::webapiRunGet(), BladeRF2Input::webapiRunGet(), FileSinkOutput::webapiRunGet(), SoapySDRInput::webapiRunGet(), XTRXOutput::webapiRunGet(), LimeSDROutput::webapiRunGet(), XTRXInput::webapiRunGet(), LimeSDRInput::webapiRunGet(), RemoteInput::webapiRunGet(), and FileInput::webapiRunGet().
{
     return state;
 }
init()
void SWGSDRangel::SWGDeviceState::init ()
Definition at line 40 of file SWGDeviceState.cpp.
References m_state_isSet, and state.
Referenced by WebAPIAdapterGUI::devicesetDeviceRunDelete(), WebAPIAdapterSrv::devicesetDeviceRunDelete(), WebAPIAdapterGUI::devicesetDeviceRunGet(), WebAPIAdapterSrv::devicesetDeviceRunGet(), WebAPIAdapterGUI::devicesetDeviceRunPost(), WebAPIAdapterSrv::devicesetDeviceRunPost(), and SWGDeviceState().
                      {
     state = new QString("");
     m_state_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGDeviceState::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 100 of file SWGDeviceState.cpp.
References state.
                      {
     bool isObjectUpdated = false;
     do{
         if(state != nullptr && *state != QString("")){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setState()
void SWGSDRangel::SWGDeviceState::setState (QString * state)
Definition at line 93 of file SWGDeviceState.cpp.
References m_state_isSet, and state.
{
     this->state = state;
     this->m_state_isSet = true;
 }
Member Data Documentation
m_state_isSet
bool SWGSDRangel::SWGDeviceState::m_state_isSet private
Definition at line 53 of file SWGDeviceState.h.
Referenced by init(), setState(), and SWGDeviceState().
state
QString* SWGSDRangel::SWGDeviceState::state private
Definition at line 52 of file SWGDeviceState.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getState(), init(), isSet(), setState(), and SWGDeviceState().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGDeviceState.h
swagger/sdrangel/code/qt5/client/SWGDeviceState.cpp