SDRAngel: SWGSDRangel::SWGDeviceReport Class Reference
SWGSDRangel::SWGDeviceReport Class Reference
#include <SWGDeviceReport.h>
Public Member Functions
SWGDeviceReport ()
SWGDeviceReport (QString *json)
virtual ~SWGDeviceReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGDeviceReport * fromJson (QString &jsonString) override
QString * getDeviceHwType ()
void setDeviceHwType (QString *device_hw_type)
qint32 getDirection ()
void setDirection (qint32 direction)
SWGAirspyReport * getAirspyReport ()
void setAirspyReport (SWGAirspyReport *airspy_report)
SWGAirspyHFReport * getAirspyHfReport ()
void setAirspyHfReport (SWGAirspyHFReport *airspy_hf_report)
SWGBladeRF2InputReport * getBladeRf2InputReport ()
void setBladeRf2InputReport (SWGBladeRF2InputReport *blade_rf2_input_report)
SWGBladeRF2OutputReport * getBladeRf2OutputReport ()
void setBladeRf2OutputReport (SWGBladeRF2OutputReport *blade_rf2_output_report)
SWGFileInputReport * getFileInputReport ()
void setFileInputReport (SWGFileInputReport *file_input_report)
SWGLimeSdrInputReport * getLimeSdrInputReport ()
void setLimeSdrInputReport (SWGLimeSdrInputReport *lime_sdr_input_report)
SWGKiwiSDRReport * getKiwiSdrReport ()
void setKiwiSdrReport (SWGKiwiSDRReport *kiwi_sdr_report)
SWGLimeSdrOutputReport * getLimeSdrOutputReport ()
void setLimeSdrOutputReport (SWGLimeSdrOutputReport *lime_sdr_output_report)
SWGLocalInputReport * getLocalInputReport ()
void setLocalInputReport (SWGLocalInputReport *local_input_report)
SWGLocalOutputReport * getLocalOutputReport ()
void setLocalOutputReport (SWGLocalOutputReport *local_output_report)
SWGPerseusReport * getPerseusReport ()
void setPerseusReport (SWGPerseusReport *perseus_report)
SWGPlutoSdrInputReport * getPlutoSdrInputReport ()
void setPlutoSdrInputReport (SWGPlutoSdrInputReport *pluto_sdr_input_report)
SWGPlutoSdrOutputReport * getPlutoSdrOutputReport ()
void setPlutoSdrOutputReport (SWGPlutoSdrOutputReport *pluto_sdr_output_report)
SWGRtlSdrReport * getRtlSdrReport ()
void setRtlSdrReport (SWGRtlSdrReport *rtl_sdr_report)
SWGRemoteOutputReport * getRemoteOutputReport ()
void setRemoteOutputReport (SWGRemoteOutputReport *remote_output_report)
SWGRemoteInputReport * getRemoteInputReport ()
void setRemoteInputReport (SWGRemoteInputReport *remote_input_report)
SWGSDRPlayReport * getSdrPlayReport ()
void setSdrPlayReport (SWGSDRPlayReport *sdr_play_report)
SWGSoapySDRReport * getSoapySdrInputReport ()
void setSoapySdrInputReport (SWGSoapySDRReport *soapy_sdr_input_report)
SWGSoapySDRReport * getSoapySdrOutputReport ()
void setSoapySdrOutputReport (SWGSoapySDRReport *soapy_sdr_output_report)
SWGXtrxInputReport * getXtrxInputReport ()
void setXtrxInputReport (SWGXtrxInputReport *xtrx_input_report)
SWGXtrxOutputReport * getXtrxOutputReport ()
void setXtrxOutputReport (SWGXtrxOutputReport *xtrx_output_report)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * device_hw_type
bool m_device_hw_type_isSet
qint32 direction
bool m_direction_isSet
SWGAirspyReport * airspy_report
bool m_airspy_report_isSet
SWGAirspyHFReport * airspy_hf_report
bool m_airspy_hf_report_isSet
SWGBladeRF2InputReport * blade_rf2_input_report
bool m_blade_rf2_input_report_isSet
SWGBladeRF2OutputReport * blade_rf2_output_report
bool m_blade_rf2_output_report_isSet
SWGFileInputReport * file_input_report
bool m_file_input_report_isSet
SWGLimeSdrInputReport * lime_sdr_input_report
bool m_lime_sdr_input_report_isSet
SWGKiwiSDRReport * kiwi_sdr_report
bool m_kiwi_sdr_report_isSet
SWGLimeSdrOutputReport * lime_sdr_output_report
bool m_lime_sdr_output_report_isSet
SWGLocalInputReport * local_input_report
bool m_local_input_report_isSet
SWGLocalOutputReport * local_output_report
bool m_local_output_report_isSet
SWGPerseusReport * perseus_report
bool m_perseus_report_isSet
SWGPlutoSdrInputReport * pluto_sdr_input_report
bool m_pluto_sdr_input_report_isSet
SWGPlutoSdrOutputReport * pluto_sdr_output_report
bool m_pluto_sdr_output_report_isSet
SWGRtlSdrReport * rtl_sdr_report
bool m_rtl_sdr_report_isSet
SWGRemoteOutputReport * remote_output_report
bool m_remote_output_report_isSet
SWGRemoteInputReport * remote_input_report
bool m_remote_input_report_isSet
SWGSDRPlayReport * sdr_play_report
bool m_sdr_play_report_isSet
SWGSoapySDRReport * soapy_sdr_input_report
bool m_soapy_sdr_input_report_isSet
SWGSoapySDRReport * soapy_sdr_output_report
bool m_soapy_sdr_output_report_isSet
SWGXtrxInputReport * xtrx_input_report
bool m_xtrx_input_report_isSet
SWGXtrxOutputReport * xtrx_output_report
bool m_xtrx_output_report_isSet
Detailed Description
Definition at line 52 of file SWGDeviceReport.h.
Constructor & Destructor Documentation
SWGDeviceReport() [1/2]
SWGSDRangel::SWGDeviceReport::SWGDeviceReport ()
Definition at line 30 of file SWGDeviceReport.cpp.
References airspy_hf_report, airspy_report, blade_rf2_input_report, blade_rf2_output_report, device_hw_type, direction, file_input_report, kiwi_sdr_report, lime_sdr_input_report, lime_sdr_output_report, local_input_report, local_output_report, m_airspy_hf_report_isSet, m_airspy_report_isSet, m_blade_rf2_input_report_isSet, m_blade_rf2_output_report_isSet, m_device_hw_type_isSet, m_direction_isSet, m_file_input_report_isSet, m_kiwi_sdr_report_isSet, m_lime_sdr_input_report_isSet, m_lime_sdr_output_report_isSet, m_local_input_report_isSet, m_local_output_report_isSet, m_perseus_report_isSet, m_pluto_sdr_input_report_isSet, m_pluto_sdr_output_report_isSet, m_remote_input_report_isSet, m_remote_output_report_isSet, m_rtl_sdr_report_isSet, m_sdr_play_report_isSet, m_soapy_sdr_input_report_isSet, m_soapy_sdr_output_report_isSet, m_xtrx_input_report_isSet, m_xtrx_output_report_isSet, perseus_report, pluto_sdr_input_report, pluto_sdr_output_report, remote_input_report, remote_output_report, rtl_sdr_report, sdr_play_report, soapy_sdr_input_report, soapy_sdr_output_report, xtrx_input_report, and xtrx_output_report.
{
     device_hw_type = nullptr;
     m_device_hw_type_isSet = false;
     direction = 0;
     m_direction_isSet = false;
     airspy_report = nullptr;
     m_airspy_report_isSet = false;
     airspy_hf_report = nullptr;
     m_airspy_hf_report_isSet = false;
     blade_rf2_input_report = nullptr;
     m_blade_rf2_input_report_isSet = false;
     blade_rf2_output_report = nullptr;
     m_blade_rf2_output_report_isSet = false;
     file_input_report = nullptr;
     m_file_input_report_isSet = false;
     lime_sdr_input_report = nullptr;
     m_lime_sdr_input_report_isSet = false;
     kiwi_sdr_report = nullptr;
     m_kiwi_sdr_report_isSet = false;
     lime_sdr_output_report = nullptr;
     m_lime_sdr_output_report_isSet = false;
     local_input_report = nullptr;
     m_local_input_report_isSet = false;
     local_output_report = nullptr;
     m_local_output_report_isSet = false;
     perseus_report = nullptr;
     m_perseus_report_isSet = false;
     pluto_sdr_input_report = nullptr;
     m_pluto_sdr_input_report_isSet = false;
     pluto_sdr_output_report = nullptr;
     m_pluto_sdr_output_report_isSet = false;
     rtl_sdr_report = nullptr;
     m_rtl_sdr_report_isSet = false;
     remote_output_report = nullptr;
     m_remote_output_report_isSet = false;
     remote_input_report = nullptr;
     m_remote_input_report_isSet = false;
     sdr_play_report = nullptr;
     m_sdr_play_report_isSet = false;
     soapy_sdr_input_report = nullptr;
     m_soapy_sdr_input_report_isSet = false;
     soapy_sdr_output_report = nullptr;
     m_soapy_sdr_output_report_isSet = false;
     xtrx_input_report = nullptr;
     m_xtrx_input_report_isSet = false;
     xtrx_output_report = nullptr;
     m_xtrx_output_report_isSet = false;
 }
SWGDeviceReport() [2/2]
SWGSDRangel::SWGDeviceReport::SWGDeviceReport (QString * json)
Definition at line 25 of file SWGDeviceReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGDeviceReport()
SWGSDRangel::SWGDeviceReport::~SWGDeviceReport () virtual
Definition at line 79 of file SWGDeviceReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGDeviceReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 264 of file SWGDeviceReport.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::devicesetDeviceReportService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGDeviceReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 275 of file SWGDeviceReport.cpp.
References airspy_hf_report, airspy_report, blade_rf2_input_report, blade_rf2_output_report, device_hw_type, direction, file_input_report, SWGSDRangel::SWGKiwiSDRReport::isSet(), SWGSDRangel::SWGRtlSdrReport::isSet(), SWGSDRangel::SWGAirspyHFReport::isSet(), SWGSDRangel::SWGPerseusReport::isSet(), SWGSDRangel::SWGAirspyReport::isSet(), SWGSDRangel::SWGRemoteOutputReport::isSet(), SWGSDRangel::SWGLocalInputReport::isSet(), SWGSDRangel::SWGLocalOutputReport::isSet(), SWGSDRangel::SWGPlutoSdrOutputReport::isSet(), SWGSDRangel::SWGPlutoSdrInputReport::isSet(), SWGSDRangel::SWGBladeRF2OutputReport::isSet(), SWGSDRangel::SWGXtrxInputReport::isSet(), SWGSDRangel::SWGXtrxOutputReport::isSet(), SWGSDRangel::SWGSDRPlayReport::isSet(), SWGSDRangel::SWGRemoteInputReport::isSet(), SWGSDRangel::SWGBladeRF2InputReport::isSet(), SWGSDRangel::SWGFileInputReport::isSet(), SWGSDRangel::SWGLimeSdrInputReport::isSet(), SWGSDRangel::SWGLimeSdrOutputReport::isSet(), SWGSDRangel::SWGSoapySDRReport::isSet(), kiwi_sdr_report, lime_sdr_input_report, lime_sdr_output_report, local_input_report, local_output_report, m_direction_isSet, perseus_report, pluto_sdr_input_report, pluto_sdr_output_report, remote_input_report, remote_output_report, rtl_sdr_report, sdr_play_report, soapy_sdr_input_report, soapy_sdr_output_report, SWGSDRangel::toJsonValue(), xtrx_input_report, and xtrx_output_report.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(device_hw_type != nullptr && *device_hw_type != QString("")){
         toJsonValue(QString("deviceHwType"), device_hw_type, obj, QString("QString"));
     }
     if(m_direction_isSet){
         obj->insert("direction", QJsonValue(direction));
     }
     if((airspy_report != nullptr) && (airspy_report->isSet())){
         toJsonValue(QString("airspyReport"), airspy_report, obj, QString("SWGAirspyReport"));
     }
     if((airspy_hf_report != nullptr) && (airspy_hf_report->isSet())){
         toJsonValue(QString("airspyHFReport"), airspy_hf_report, obj, QString("SWGAirspyHFReport"));
     }
     if((blade_rf2_input_report != nullptr) && (blade_rf2_input_report->isSet())){
         toJsonValue(QString("bladeRF2InputReport"), blade_rf2_input_report, obj, QString("SWGBladeRF2InputReport"));
     }
     if((blade_rf2_output_report != nullptr) && (blade_rf2_output_report->isSet())){
         toJsonValue(QString("bladeRF2OutputReport"), blade_rf2_output_report, obj, QString("SWGBladeRF2OutputReport"));
     }
     if((file_input_report != nullptr) && (file_input_report->isSet())){
         toJsonValue(QString("fileInputReport"), file_input_report, obj, QString("SWGFileInputReport"));
     }
     if((lime_sdr_input_report != nullptr) && (lime_sdr_input_report->isSet())){
         toJsonValue(QString("limeSdrInputReport"), lime_sdr_input_report, obj, QString("SWGLimeSdrInputReport"));
     }
     if((kiwi_sdr_report != nullptr) && (kiwi_sdr_report->isSet())){
         toJsonValue(QString("kiwiSDRReport"), kiwi_sdr_report, obj, QString("SWGKiwiSDRReport"));
     }
     if((lime_sdr_output_report != nullptr) && (lime_sdr_output_report->isSet())){
         toJsonValue(QString("limeSdrOutputReport"), lime_sdr_output_report, obj, QString("SWGLimeSdrOutputReport"));
     }
     if((local_input_report != nullptr) && (local_input_report->isSet())){
         toJsonValue(QString("localInputReport"), local_input_report, obj, QString("SWGLocalInputReport"));
     }
     if((local_output_report != nullptr) && (local_output_report->isSet())){
         toJsonValue(QString("localOutputReport"), local_output_report, obj, QString("SWGLocalOutputReport"));
     }
     if((perseus_report != nullptr) && (perseus_report->isSet())){
         toJsonValue(QString("perseusReport"), perseus_report, obj, QString("SWGPerseusReport"));
     }
     if((pluto_sdr_input_report != nullptr) && (pluto_sdr_input_report->isSet())){
         toJsonValue(QString("plutoSdrInputReport"), pluto_sdr_input_report, obj, QString("SWGPlutoSdrInputReport"));
     }
     if((pluto_sdr_output_report != nullptr) && (pluto_sdr_output_report->isSet())){
         toJsonValue(QString("plutoSdrOutputReport"), pluto_sdr_output_report, obj, QString("SWGPlutoSdrOutputReport"));
     }
     if((rtl_sdr_report != nullptr) && (rtl_sdr_report->isSet())){
         toJsonValue(QString("rtlSdrReport"), rtl_sdr_report, obj, QString("SWGRtlSdrReport"));
     }
     if((remote_output_report != nullptr) && (remote_output_report->isSet())){
         toJsonValue(QString("remoteOutputReport"), remote_output_report, obj, QString("SWGRemoteOutputReport"));
     }
     if((remote_input_report != nullptr) && (remote_input_report->isSet())){
         toJsonValue(QString("remoteInputReport"), remote_input_report, obj, QString("SWGRemoteInputReport"));
     }
     if((sdr_play_report != nullptr) && (sdr_play_report->isSet())){
         toJsonValue(QString("sdrPlayReport"), sdr_play_report, obj, QString("SWGSDRPlayReport"));
     }
     if((soapy_sdr_input_report != nullptr) && (soapy_sdr_input_report->isSet())){
         toJsonValue(QString("soapySDRInputReport"), soapy_sdr_input_report, obj, QString("SWGSoapySDRReport"));
     }
     if((soapy_sdr_output_report != nullptr) && (soapy_sdr_output_report->isSet())){
         toJsonValue(QString("soapySDROutputReport"), soapy_sdr_output_report, obj, QString("SWGSoapySDRReport"));
     }
     if((xtrx_input_report != nullptr) && (xtrx_input_report->isSet())){
         toJsonValue(QString("xtrxInputReport"), xtrx_input_report, obj, QString("SWGXtrxInputReport"));
     }
     if((xtrx_output_report != nullptr) && (xtrx_output_report->isSet())){
         toJsonValue(QString("xtrxOutputReport"), xtrx_output_report, obj, QString("SWGXtrxOutputReport"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGDeviceReport::cleanup ()
Definition at line 134 of file SWGDeviceReport.cpp.
References airspy_hf_report, airspy_report, blade_rf2_input_report, blade_rf2_output_report, device_hw_type, file_input_report, kiwi_sdr_report, lime_sdr_input_report, lime_sdr_output_report, local_input_report, local_output_report, perseus_report, pluto_sdr_input_report, pluto_sdr_output_report, remote_input_report, remote_output_report, rtl_sdr_report, sdr_play_report, soapy_sdr_input_report, soapy_sdr_output_report, xtrx_input_report, and xtrx_output_report.
Referenced by WebAPIRequestMapper::resetDeviceReport(), and ~SWGDeviceReport().
{
     if(device_hw_type != nullptr) {
         delete device_hw_type;
     }
     if(airspy_report != nullptr) {
         delete airspy_report;
     }
     if(airspy_hf_report != nullptr) {
         delete airspy_hf_report;
     }
     if(blade_rf2_input_report != nullptr) {
         delete blade_rf2_input_report;
     }
     if(blade_rf2_output_report != nullptr) {
         delete blade_rf2_output_report;
     }
     if(file_input_report != nullptr) {
         delete file_input_report;
     }
     if(lime_sdr_input_report != nullptr) {
         delete lime_sdr_input_report;
     }
     if(kiwi_sdr_report != nullptr) {
         delete kiwi_sdr_report;
     }
     if(lime_sdr_output_report != nullptr) {
         delete lime_sdr_output_report;
     }
     if(local_input_report != nullptr) {
         delete local_input_report;
     }
     if(local_output_report != nullptr) {
         delete local_output_report;
     }
     if(perseus_report != nullptr) {
         delete perseus_report;
     }
     if(pluto_sdr_input_report != nullptr) {
         delete pluto_sdr_input_report;
     }
     if(pluto_sdr_output_report != nullptr) {
         delete pluto_sdr_output_report;
     }
     if(rtl_sdr_report != nullptr) {
         delete rtl_sdr_report;
     }
     if(remote_output_report != nullptr) {
         delete remote_output_report;
     }
     if(remote_input_report != nullptr) {
         delete remote_input_report;
     }
     if(sdr_play_report != nullptr) {
         delete sdr_play_report;
     }
     if(soapy_sdr_input_report != nullptr) {
         delete soapy_sdr_input_report;
     }
     if(soapy_sdr_output_report != nullptr) {
         delete soapy_sdr_output_report;
     }
     if(xtrx_input_report != nullptr) {
         delete xtrx_input_report;
     }
     if(xtrx_output_report != nullptr) {
         delete xtrx_output_report;
     }
 }
fromJson()
SWGDeviceReport * SWGSDRangel::SWGDeviceReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 205 of file SWGDeviceReport.cpp.
References fromJsonObject().
Referenced by SWGDeviceReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGDeviceReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 214 of file SWGDeviceReport.cpp.
References airspy_hf_report, airspy_report, blade_rf2_input_report, blade_rf2_output_report, device_hw_type, direction, file_input_report, kiwi_sdr_report, lime_sdr_input_report, lime_sdr_output_report, local_input_report, local_output_report, perseus_report, pluto_sdr_input_report, pluto_sdr_output_report, remote_input_report, remote_output_report, rtl_sdr_report, sdr_play_report, SWGSDRangel::setValue(), soapy_sdr_input_report, soapy_sdr_output_report, xtrx_input_report, and xtrx_output_report.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&device_hw_type, pJson["deviceHwType"], "QString", "QString");
     ::SWGSDRangel::setValue(&direction, pJson["direction"], "qint32", "");
     ::SWGSDRangel::setValue(&airspy_report, pJson["airspyReport"], "SWGAirspyReport", "SWGAirspyReport");
     ::SWGSDRangel::setValue(&airspy_hf_report, pJson["airspyHFReport"], "SWGAirspyHFReport", "SWGAirspyHFReport");
     ::SWGSDRangel::setValue(&blade_rf2_input_report, pJson["bladeRF2InputReport"], "SWGBladeRF2InputReport", "SWGBladeRF2InputReport");
     ::SWGSDRangel::setValue(&blade_rf2_output_report, pJson["bladeRF2OutputReport"], "SWGBladeRF2OutputReport", "SWGBladeRF2OutputReport");
     ::SWGSDRangel::setValue(&file_input_report, pJson["fileInputReport"], "SWGFileInputReport", "SWGFileInputReport");
     ::SWGSDRangel::setValue(&lime_sdr_input_report, pJson["limeSdrInputReport"], "SWGLimeSdrInputReport", "SWGLimeSdrInputReport");
     ::SWGSDRangel::setValue(&kiwi_sdr_report, pJson["kiwiSDRReport"], "SWGKiwiSDRReport", "SWGKiwiSDRReport");
     ::SWGSDRangel::setValue(&lime_sdr_output_report, pJson["limeSdrOutputReport"], "SWGLimeSdrOutputReport", "SWGLimeSdrOutputReport");
     ::SWGSDRangel::setValue(&local_input_report, pJson["localInputReport"], "SWGLocalInputReport", "SWGLocalInputReport");
     ::SWGSDRangel::setValue(&local_output_report, pJson["localOutputReport"], "SWGLocalOutputReport", "SWGLocalOutputReport");
     ::SWGSDRangel::setValue(&perseus_report, pJson["perseusReport"], "SWGPerseusReport", "SWGPerseusReport");
     ::SWGSDRangel::setValue(&pluto_sdr_input_report, pJson["plutoSdrInputReport"], "SWGPlutoSdrInputReport", "SWGPlutoSdrInputReport");
     ::SWGSDRangel::setValue(&pluto_sdr_output_report, pJson["plutoSdrOutputReport"], "SWGPlutoSdrOutputReport", "SWGPlutoSdrOutputReport");
     ::SWGSDRangel::setValue(&rtl_sdr_report, pJson["rtlSdrReport"], "SWGRtlSdrReport", "SWGRtlSdrReport");
     ::SWGSDRangel::setValue(&remote_output_report, pJson["remoteOutputReport"], "SWGRemoteOutputReport", "SWGRemoteOutputReport");
     ::SWGSDRangel::setValue(&remote_input_report, pJson["remoteInputReport"], "SWGRemoteInputReport", "SWGRemoteInputReport");
     ::SWGSDRangel::setValue(&sdr_play_report, pJson["sdrPlayReport"], "SWGSDRPlayReport", "SWGSDRPlayReport");
     ::SWGSDRangel::setValue(&soapy_sdr_input_report, pJson["soapySDRInputReport"], "SWGSoapySDRReport", "SWGSoapySDRReport");
     ::SWGSDRangel::setValue(&soapy_sdr_output_report, pJson["soapySDROutputReport"], "SWGSoapySDRReport", "SWGSoapySDRReport");
     ::SWGSDRangel::setValue(&xtrx_input_report, pJson["xtrxInputReport"], "SWGXtrxInputReport", "SWGXtrxInputReport");
     ::SWGSDRangel::setValue(&xtrx_output_report, pJson["xtrxOutputReport"], "SWGXtrxOutputReport", "SWGXtrxOutputReport");
 }
getAirspyHfReport()
SWGAirspyHFReport * SWGSDRangel::SWGDeviceReport::getAirspyHfReport ()
Definition at line 381 of file SWGDeviceReport.cpp.
References airspy_hf_report.
Referenced by AirspyHFInput::webapiFormatDeviceReport(), and AirspyHFInput::webapiReportGet().
{
     return airspy_hf_report;
 }
getAirspyReport()
SWGAirspyReport * SWGSDRangel::SWGDeviceReport::getAirspyReport ()
Definition at line 371 of file SWGDeviceReport.cpp.
References airspy_report.
Referenced by AirspyInput::webapiFormatDeviceReport(), and AirspyInput::webapiReportGet().
{
     return airspy_report;
 }
getBladeRf2InputReport()
SWGBladeRF2InputReport * SWGSDRangel::SWGDeviceReport::getBladeRf2InputReport ()
Definition at line 391 of file SWGDeviceReport.cpp.
References blade_rf2_input_report.
Referenced by BladeRF2Input::webapiFormatDeviceReport(), and BladeRF2Input::webapiReportGet().
{
     return blade_rf2_input_report;
 }
getBladeRf2OutputReport()
SWGBladeRF2OutputReport * SWGSDRangel::SWGDeviceReport::getBladeRf2OutputReport ()
Definition at line 401 of file SWGDeviceReport.cpp.
References blade_rf2_output_report.
Referenced by BladeRF2Output::webapiFormatDeviceReport(), and BladeRF2Output::webapiReportGet().
{
     return blade_rf2_output_report;
 }
getDeviceHwType()
QString * SWGSDRangel::SWGDeviceReport::getDeviceHwType ()
Definition at line 351 of file SWGDeviceReport.cpp.
References device_hw_type.
{
     return device_hw_type;
 }
getDirection()
qint32 SWGSDRangel::SWGDeviceReport::getDirection ()
Definition at line 361 of file SWGDeviceReport.cpp.
References direction.
{
     return direction;
 }
getFileInputReport()
SWGFileInputReport * SWGSDRangel::SWGDeviceReport::getFileInputReport ()
Definition at line 411 of file SWGDeviceReport.cpp.
References file_input_report.
Referenced by FileInput::webapiFormatDeviceReport(), and FileInput::webapiReportGet().
{
     return file_input_report;
 }
getKiwiSdrReport()
SWGKiwiSDRReport * SWGSDRangel::SWGDeviceReport::getKiwiSdrReport ()
Definition at line 431 of file SWGDeviceReport.cpp.
References kiwi_sdr_report.
Referenced by KiwiSDRInput::webapiFormatDeviceReport(), and KiwiSDRInput::webapiReportGet().
{
     return kiwi_sdr_report;
 }
getLimeSdrInputReport()
SWGLimeSdrInputReport * SWGSDRangel::SWGDeviceReport::getLimeSdrInputReport ()
Definition at line 421 of file SWGDeviceReport.cpp.
References lime_sdr_input_report.
Referenced by LimeSDRInput::webapiFormatDeviceReport(), and LimeSDRInput::webapiReportGet().
{
     return lime_sdr_input_report;
 }
getLimeSdrOutputReport()
SWGLimeSdrOutputReport * SWGSDRangel::SWGDeviceReport::getLimeSdrOutputReport ()
Definition at line 441 of file SWGDeviceReport.cpp.
References lime_sdr_output_report.
Referenced by LimeSDROutput::webapiFormatDeviceReport(), and LimeSDROutput::webapiReportGet().
{
     return lime_sdr_output_report;
 }
getLocalInputReport()
SWGLocalInputReport * SWGSDRangel::SWGDeviceReport::getLocalInputReport ()
Definition at line 451 of file SWGDeviceReport.cpp.
References local_input_report.
Referenced by LocalInput::webapiFormatDeviceReport(), and LocalInput::webapiReportGet().
{
     return local_input_report;
 }
getLocalOutputReport()
SWGLocalOutputReport * SWGSDRangel::SWGDeviceReport::getLocalOutputReport ()
Definition at line 461 of file SWGDeviceReport.cpp.
References local_output_report.
Referenced by LocalOutput::webapiFormatDeviceReport(), and LocalOutput::webapiReportGet().
{
     return local_output_report;
 }
getPerseusReport()
SWGPerseusReport * SWGSDRangel::SWGDeviceReport::getPerseusReport ()
Definition at line 471 of file SWGDeviceReport.cpp.
References perseus_report.
Referenced by PerseusInput::webapiFormatDeviceReport(), and PerseusInput::webapiReportGet().
{
     return perseus_report;
 }
getPlutoSdrInputReport()
SWGPlutoSdrInputReport * SWGSDRangel::SWGDeviceReport::getPlutoSdrInputReport ()
Definition at line 481 of file SWGDeviceReport.cpp.
References pluto_sdr_input_report.
Referenced by PlutoSDRInput::webapiFormatDeviceReport(), and PlutoSDRInput::webapiReportGet().
{
     return pluto_sdr_input_report;
 }
getPlutoSdrOutputReport()
SWGPlutoSdrOutputReport * SWGSDRangel::SWGDeviceReport::getPlutoSdrOutputReport ()
Definition at line 491 of file SWGDeviceReport.cpp.
References pluto_sdr_output_report.
Referenced by PlutoSDROutput::webapiFormatDeviceReport(), and PlutoSDROutput::webapiReportGet().
{
     return pluto_sdr_output_report;
 }
getRemoteInputReport()
SWGRemoteInputReport * SWGSDRangel::SWGDeviceReport::getRemoteInputReport ()
Definition at line 521 of file SWGDeviceReport.cpp.
References remote_input_report.
Referenced by RemoteInput::webapiFormatDeviceReport(), and RemoteInput::webapiReportGet().
{
     return remote_input_report;
 }
getRemoteOutputReport()
SWGRemoteOutputReport * SWGSDRangel::SWGDeviceReport::getRemoteOutputReport ()
Definition at line 511 of file SWGDeviceReport.cpp.
References remote_output_report.
Referenced by RemoteOutput::webapiFormatDeviceReport(), and RemoteOutput::webapiReportGet().
{
     return remote_output_report;
 }
getRtlSdrReport()
SWGRtlSdrReport * SWGSDRangel::SWGDeviceReport::getRtlSdrReport ()
Definition at line 501 of file SWGDeviceReport.cpp.
References rtl_sdr_report.
Referenced by RTLSDRInput::webapiFormatDeviceReport(), and RTLSDRInput::webapiReportGet().
{
     return rtl_sdr_report;
 }
getSdrPlayReport()
SWGSDRPlayReport * SWGSDRangel::SWGDeviceReport::getSdrPlayReport ()
Definition at line 531 of file SWGDeviceReport.cpp.
References sdr_play_report.
Referenced by SDRPlayInput::webapiFormatDeviceReport(), and SDRPlayInput::webapiReportGet().
{
     return sdr_play_report;
 }
getSoapySdrInputReport()
SWGSoapySDRReport * SWGSDRangel::SWGDeviceReport::getSoapySdrInputReport ()
Definition at line 541 of file SWGDeviceReport.cpp.
References soapy_sdr_input_report.
Referenced by SoapySDRInput::webapiFormatDeviceReport(), and SoapySDRInput::webapiReportGet().
{
     return soapy_sdr_input_report;
 }
getSoapySdrOutputReport()
SWGSoapySDRReport * SWGSDRangel::SWGDeviceReport::getSoapySdrOutputReport ()
Definition at line 551 of file SWGDeviceReport.cpp.
References soapy_sdr_output_report.
Referenced by SoapySDROutput::webapiFormatDeviceReport(), and SoapySDROutput::webapiReportGet().
{
     return soapy_sdr_output_report;
 }
getXtrxInputReport()
SWGXtrxInputReport * SWGSDRangel::SWGDeviceReport::getXtrxInputReport ()
Definition at line 561 of file SWGDeviceReport.cpp.
References xtrx_input_report.
Referenced by XTRXInput::webapiFormatDeviceReport(), and XTRXInput::webapiReportGet().
{
     return xtrx_input_report;
 }
getXtrxOutputReport()
SWGXtrxOutputReport * SWGSDRangel::SWGDeviceReport::getXtrxOutputReport ()
Definition at line 571 of file SWGDeviceReport.cpp.
References xtrx_output_report.
Referenced by XTRXOutput::webapiFormatDeviceReport(), and XTRXOutput::webapiReportGet().
{
     return xtrx_output_report;
 }
init()
void SWGSDRangel::SWGDeviceReport::init ()
Definition at line 84 of file SWGDeviceReport.cpp.
References airspy_hf_report, airspy_report, blade_rf2_input_report, blade_rf2_output_report, device_hw_type, direction, file_input_report, kiwi_sdr_report, lime_sdr_input_report, lime_sdr_output_report, local_input_report, local_output_report, m_airspy_hf_report_isSet, m_airspy_report_isSet, m_blade_rf2_input_report_isSet, m_blade_rf2_output_report_isSet, m_device_hw_type_isSet, m_direction_isSet, m_file_input_report_isSet, m_kiwi_sdr_report_isSet, m_lime_sdr_input_report_isSet, m_lime_sdr_output_report_isSet, m_local_input_report_isSet, m_local_output_report_isSet, m_perseus_report_isSet, m_pluto_sdr_input_report_isSet, m_pluto_sdr_output_report_isSet, m_remote_input_report_isSet, m_remote_output_report_isSet, m_rtl_sdr_report_isSet, m_sdr_play_report_isSet, m_soapy_sdr_input_report_isSet, m_soapy_sdr_output_report_isSet, m_xtrx_input_report_isSet, m_xtrx_output_report_isSet, perseus_report, pluto_sdr_input_report, pluto_sdr_output_report, remote_input_report, remote_output_report, rtl_sdr_report, sdr_play_report, soapy_sdr_input_report, soapy_sdr_output_report, xtrx_input_report, and xtrx_output_report.
Referenced by SWGDeviceReport().
                       {
     device_hw_type = new QString("");
     m_device_hw_type_isSet = false;
     direction = 0;
     m_direction_isSet = false;
     airspy_report = new SWGAirspyReport();
     m_airspy_report_isSet = false;
     airspy_hf_report = new SWGAirspyHFReport();
     m_airspy_hf_report_isSet = false;
     blade_rf2_input_report = new SWGBladeRF2InputReport();
     m_blade_rf2_input_report_isSet = false;
     blade_rf2_output_report = new SWGBladeRF2OutputReport();
     m_blade_rf2_output_report_isSet = false;
     file_input_report = new SWGFileInputReport();
     m_file_input_report_isSet = false;
     lime_sdr_input_report = new SWGLimeSdrInputReport();
     m_lime_sdr_input_report_isSet = false;
     kiwi_sdr_report = new SWGKiwiSDRReport();
     m_kiwi_sdr_report_isSet = false;
     lime_sdr_output_report = new SWGLimeSdrOutputReport();
     m_lime_sdr_output_report_isSet = false;
     local_input_report = new SWGLocalInputReport();
     m_local_input_report_isSet = false;
     local_output_report = new SWGLocalOutputReport();
     m_local_output_report_isSet = false;
     perseus_report = new SWGPerseusReport();
     m_perseus_report_isSet = false;
     pluto_sdr_input_report = new SWGPlutoSdrInputReport();
     m_pluto_sdr_input_report_isSet = false;
     pluto_sdr_output_report = new SWGPlutoSdrOutputReport();
     m_pluto_sdr_output_report_isSet = false;
     rtl_sdr_report = new SWGRtlSdrReport();
     m_rtl_sdr_report_isSet = false;
     remote_output_report = new SWGRemoteOutputReport();
     m_remote_output_report_isSet = false;
     remote_input_report = new SWGRemoteInputReport();
     m_remote_input_report_isSet = false;
     sdr_play_report = new SWGSDRPlayReport();
     m_sdr_play_report_isSet = false;
     soapy_sdr_input_report = new SWGSoapySDRReport();
     m_soapy_sdr_input_report_isSet = false;
     soapy_sdr_output_report = new SWGSoapySDRReport();
     m_soapy_sdr_output_report_isSet = false;
     xtrx_input_report = new SWGXtrxInputReport();
     m_xtrx_input_report_isSet = false;
     xtrx_output_report = new SWGXtrxOutputReport();
     m_xtrx_output_report_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGDeviceReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 582 of file SWGDeviceReport.cpp.
References airspy_hf_report, airspy_report, blade_rf2_input_report, blade_rf2_output_report, device_hw_type, file_input_report, SWGSDRangel::SWGKiwiSDRReport::isSet(), SWGSDRangel::SWGAirspyReport::isSet(), SWGSDRangel::SWGAirspyHFReport::isSet(), SWGSDRangel::SWGPerseusReport::isSet(), SWGSDRangel::SWGRtlSdrReport::isSet(), SWGSDRangel::SWGRemoteOutputReport::isSet(), SWGSDRangel::SWGLocalInputReport::isSet(), SWGSDRangel::SWGLocalOutputReport::isSet(), SWGSDRangel::SWGPlutoSdrOutputReport::isSet(), SWGSDRangel::SWGPlutoSdrInputReport::isSet(), SWGSDRangel::SWGBladeRF2OutputReport::isSet(), SWGSDRangel::SWGXtrxOutputReport::isSet(), SWGSDRangel::SWGXtrxInputReport::isSet(), SWGSDRangel::SWGSDRPlayReport::isSet(), SWGSDRangel::SWGRemoteInputReport::isSet(), SWGSDRangel::SWGBladeRF2InputReport::isSet(), SWGSDRangel::SWGFileInputReport::isSet(), SWGSDRangel::SWGLimeSdrOutputReport::isSet(), SWGSDRangel::SWGLimeSdrInputReport::isSet(), SWGSDRangel::SWGSoapySDRReport::isSet(), kiwi_sdr_report, lime_sdr_input_report, lime_sdr_output_report, local_input_report, local_output_report, m_direction_isSet, perseus_report, pluto_sdr_input_report, pluto_sdr_output_report, remote_input_report, remote_output_report, rtl_sdr_report, sdr_play_report, soapy_sdr_input_report, soapy_sdr_output_report, xtrx_input_report, and xtrx_output_report.
                       {
     bool isObjectUpdated = false;
     do{
         if(device_hw_type != nullptr && *device_hw_type != QString("")){ isObjectUpdated = true; break;}
         if(m_direction_isSet){ isObjectUpdated = true; break;}
         if(airspy_report != nullptr && airspy_report->isSet()){ isObjectUpdated = true; break;}
         if(airspy_hf_report != nullptr && airspy_hf_report->isSet()){ isObjectUpdated = true; break;}
         if(blade_rf2_input_report != nullptr && blade_rf2_input_report->isSet()){ isObjectUpdated = true; break;}
         if(blade_rf2_output_report != nullptr && blade_rf2_output_report->isSet()){ isObjectUpdated = true; break;}
         if(file_input_report != nullptr && file_input_report->isSet()){ isObjectUpdated = true; break;}
         if(lime_sdr_input_report != nullptr && lime_sdr_input_report->isSet()){ isObjectUpdated = true; break;}
         if(kiwi_sdr_report != nullptr && kiwi_sdr_report->isSet()){ isObjectUpdated = true; break;}
         if(lime_sdr_output_report != nullptr && lime_sdr_output_report->isSet()){ isObjectUpdated = true; break;}
         if(local_input_report != nullptr && local_input_report->isSet()){ isObjectUpdated = true; break;}
         if(local_output_report != nullptr && local_output_report->isSet()){ isObjectUpdated = true; break;}
         if(perseus_report != nullptr && perseus_report->isSet()){ isObjectUpdated = true; break;}
         if(pluto_sdr_input_report != nullptr && pluto_sdr_input_report->isSet()){ isObjectUpdated = true; break;}
         if(pluto_sdr_output_report != nullptr && pluto_sdr_output_report->isSet()){ isObjectUpdated = true; break;}
         if(rtl_sdr_report != nullptr && rtl_sdr_report->isSet()){ isObjectUpdated = true; break;}
         if(remote_output_report != nullptr && remote_output_report->isSet()){ isObjectUpdated = true; break;}
         if(remote_input_report != nullptr && remote_input_report->isSet()){ isObjectUpdated = true; break;}
         if(sdr_play_report != nullptr && sdr_play_report->isSet()){ isObjectUpdated = true; break;}
         if(soapy_sdr_input_report != nullptr && soapy_sdr_input_report->isSet()){ isObjectUpdated = true; break;}
         if(soapy_sdr_output_report != nullptr && soapy_sdr_output_report->isSet()){ isObjectUpdated = true; break;}
         if(xtrx_input_report != nullptr && xtrx_input_report->isSet()){ isObjectUpdated = true; break;}
         if(xtrx_output_report != nullptr && xtrx_output_report->isSet()){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setAirspyHfReport()
void SWGSDRangel::SWGDeviceReport::setAirspyHfReport (SWGAirspyHFReport * airspy_hf_report)
Definition at line 385 of file SWGDeviceReport.cpp.
References airspy_hf_report, and m_airspy_hf_report_isSet.
Referenced by WebAPIRequestMapper::resetDeviceReport(), and AirspyHFInput::webapiReportGet().
{
     this->airspy_hf_report = airspy_hf_report;
     this->m_airspy_hf_report_isSet = true;
 }
setAirspyReport()
void SWGSDRangel::SWGDeviceReport::setAirspyReport (SWGAirspyReport * airspy_report)
Definition at line 375 of file SWGDeviceReport.cpp.
References airspy_report, and m_airspy_report_isSet.
Referenced by WebAPIRequestMapper::resetDeviceReport(), and AirspyInput::webapiReportGet().
{
     this->airspy_report = airspy_report;
     this->m_airspy_report_isSet = true;
 }
setBladeRf2InputReport()
void SWGSDRangel::SWGDeviceReport::setBladeRf2InputReport (SWGBladeRF2InputReport * blade_rf2_input_report)
Definition at line 395 of file SWGDeviceReport.cpp.
References blade_rf2_input_report, and m_blade_rf2_input_report_isSet.
Referenced by BladeRF2Input::webapiReportGet().
{
     this->blade_rf2_input_report = blade_rf2_input_report;
     this->m_blade_rf2_input_report_isSet = true;
 }
setBladeRf2OutputReport()
void SWGSDRangel::SWGDeviceReport::setBladeRf2OutputReport (SWGBladeRF2OutputReport * blade_rf2_output_report)
Definition at line 405 of file SWGDeviceReport.cpp.
References blade_rf2_output_report, and m_blade_rf2_output_report_isSet.
Referenced by BladeRF2Output::webapiReportGet().
{
     this->blade_rf2_output_report = blade_rf2_output_report;
     this->m_blade_rf2_output_report_isSet = true;
 }
setDeviceHwType()
void SWGSDRangel::SWGDeviceReport::setDeviceHwType (QString * device_hw_type)
Definition at line 355 of file SWGDeviceReport.cpp.
References device_hw_type, and m_device_hw_type_isSet.
Referenced by WebAPIAdapterGUI::devicesetDeviceReportGet(), WebAPIAdapterSrv::devicesetDeviceReportGet(), and WebAPIRequestMapper::resetDeviceReport().
{
     this->device_hw_type = device_hw_type;
     this->m_device_hw_type_isSet = true;
 }
setDirection()
void SWGSDRangel::SWGDeviceReport::setDirection (qint32 direction)
Definition at line 365 of file SWGDeviceReport.cpp.
References direction, and m_direction_isSet.
Referenced by WebAPIAdapterGUI::devicesetDeviceReportGet(), and WebAPIAdapterSrv::devicesetDeviceReportGet().
{
     this->direction = direction;
     this->m_direction_isSet = true;
 }
setFileInputReport()
void SWGSDRangel::SWGDeviceReport::setFileInputReport (SWGFileInputReport * file_input_report)
Definition at line 415 of file SWGDeviceReport.cpp.
References file_input_report, and m_file_input_report_isSet.
Referenced by WebAPIRequestMapper::resetDeviceReport(), and FileInput::webapiReportGet().
{
     this->file_input_report = file_input_report;
     this->m_file_input_report_isSet = true;
 }
setKiwiSdrReport()
void SWGSDRangel::SWGDeviceReport::setKiwiSdrReport (SWGKiwiSDRReport * kiwi_sdr_report)
Definition at line 435 of file SWGDeviceReport.cpp.
References kiwi_sdr_report, and m_kiwi_sdr_report_isSet.
Referenced by KiwiSDRInput::webapiReportGet().
{
     this->kiwi_sdr_report = kiwi_sdr_report;
     this->m_kiwi_sdr_report_isSet = true;
 }
setLimeSdrInputReport()
void SWGSDRangel::SWGDeviceReport::setLimeSdrInputReport (SWGLimeSdrInputReport * lime_sdr_input_report)
Definition at line 425 of file SWGDeviceReport.cpp.
References lime_sdr_input_report, and m_lime_sdr_input_report_isSet.
Referenced by WebAPIRequestMapper::resetDeviceReport(), and LimeSDRInput::webapiReportGet().
{
     this->lime_sdr_input_report = lime_sdr_input_report;
     this->m_lime_sdr_input_report_isSet = true;
 }
setLimeSdrOutputReport()
void SWGSDRangel::SWGDeviceReport::setLimeSdrOutputReport (SWGLimeSdrOutputReport * lime_sdr_output_report)
Definition at line 445 of file SWGDeviceReport.cpp.
References lime_sdr_output_report, and m_lime_sdr_output_report_isSet.
Referenced by WebAPIRequestMapper::resetDeviceReport(), and LimeSDROutput::webapiReportGet().
{
     this->lime_sdr_output_report = lime_sdr_output_report;
     this->m_lime_sdr_output_report_isSet = true;
 }
setLocalInputReport()
void SWGSDRangel::SWGDeviceReport::setLocalInputReport (SWGLocalInputReport * local_input_report)
Definition at line 455 of file SWGDeviceReport.cpp.
References local_input_report, and m_local_input_report_isSet.
Referenced by LocalInput::webapiReportGet().
{
     this->local_input_report = local_input_report;
     this->m_local_input_report_isSet = true;
 }
setLocalOutputReport()
void SWGSDRangel::SWGDeviceReport::setLocalOutputReport (SWGLocalOutputReport * local_output_report)
Definition at line 465 of file SWGDeviceReport.cpp.
References local_output_report, and m_local_output_report_isSet.
Referenced by LocalOutput::webapiReportGet().
{
     this->local_output_report = local_output_report;
     this->m_local_output_report_isSet = true;
 }
setPerseusReport()
void SWGSDRangel::SWGDeviceReport::setPerseusReport (SWGPerseusReport * perseus_report)
Definition at line 475 of file SWGDeviceReport.cpp.
References m_perseus_report_isSet, and perseus_report.
Referenced by WebAPIRequestMapper::resetDeviceReport(), and PerseusInput::webapiReportGet().
{
     this->perseus_report = perseus_report;
     this->m_perseus_report_isSet = true;
 }
setPlutoSdrInputReport()
void SWGSDRangel::SWGDeviceReport::setPlutoSdrInputReport (SWGPlutoSdrInputReport * pluto_sdr_input_report)
Definition at line 485 of file SWGDeviceReport.cpp.
References m_pluto_sdr_input_report_isSet, and pluto_sdr_input_report.
Referenced by WebAPIRequestMapper::resetDeviceReport(), and PlutoSDRInput::webapiReportGet().
{
     this->pluto_sdr_input_report = pluto_sdr_input_report;
     this->m_pluto_sdr_input_report_isSet = true;
 }
setPlutoSdrOutputReport()
void SWGSDRangel::SWGDeviceReport::setPlutoSdrOutputReport (SWGPlutoSdrOutputReport * pluto_sdr_output_report)
Definition at line 495 of file SWGDeviceReport.cpp.
References m_pluto_sdr_output_report_isSet, and pluto_sdr_output_report.
Referenced by WebAPIRequestMapper::resetDeviceReport(), and PlutoSDROutput::webapiReportGet().
{
     this->pluto_sdr_output_report = pluto_sdr_output_report;
     this->m_pluto_sdr_output_report_isSet = true;
 }
setRemoteInputReport()
void SWGSDRangel::SWGDeviceReport::setRemoteInputReport (SWGRemoteInputReport * remote_input_report)
Definition at line 525 of file SWGDeviceReport.cpp.
References m_remote_input_report_isSet, and remote_input_report.
Referenced by WebAPIRequestMapper::resetDeviceReport(), and RemoteInput::webapiReportGet().
{
     this->remote_input_report = remote_input_report;
     this->m_remote_input_report_isSet = true;
 }
setRemoteOutputReport()
void SWGSDRangel::SWGDeviceReport::setRemoteOutputReport (SWGRemoteOutputReport * remote_output_report)
Definition at line 515 of file SWGDeviceReport.cpp.
References m_remote_output_report_isSet, and remote_output_report.
Referenced by WebAPIRequestMapper::resetDeviceReport(), and RemoteOutput::webapiReportGet().
{
     this->remote_output_report = remote_output_report;
     this->m_remote_output_report_isSet = true;
 }
setRtlSdrReport()
void SWGSDRangel::SWGDeviceReport::setRtlSdrReport (SWGRtlSdrReport * rtl_sdr_report)
Definition at line 505 of file SWGDeviceReport.cpp.
References m_rtl_sdr_report_isSet, and rtl_sdr_report.
Referenced by WebAPIRequestMapper::resetDeviceReport(), and RTLSDRInput::webapiReportGet().
{
     this->rtl_sdr_report = rtl_sdr_report;
     this->m_rtl_sdr_report_isSet = true;
 }
setSdrPlayReport()
void SWGSDRangel::SWGDeviceReport::setSdrPlayReport (SWGSDRPlayReport * sdr_play_report)
Definition at line 535 of file SWGDeviceReport.cpp.
References m_sdr_play_report_isSet, and sdr_play_report.
Referenced by WebAPIRequestMapper::resetDeviceReport(), and SDRPlayInput::webapiReportGet().
{
     this->sdr_play_report = sdr_play_report;
     this->m_sdr_play_report_isSet = true;
 }
setSoapySdrInputReport()
void SWGSDRangel::SWGDeviceReport::setSoapySdrInputReport (SWGSoapySDRReport * soapy_sdr_input_report)
Definition at line 545 of file SWGDeviceReport.cpp.
References m_soapy_sdr_input_report_isSet, and soapy_sdr_input_report.
Referenced by SoapySDRInput::webapiReportGet().
{
     this->soapy_sdr_input_report = soapy_sdr_input_report;
     this->m_soapy_sdr_input_report_isSet = true;
 }
setSoapySdrOutputReport()
void SWGSDRangel::SWGDeviceReport::setSoapySdrOutputReport (SWGSoapySDRReport * soapy_sdr_output_report)
Definition at line 555 of file SWGDeviceReport.cpp.
References m_soapy_sdr_output_report_isSet, and soapy_sdr_output_report.
Referenced by SoapySDROutput::webapiReportGet().
{
     this->soapy_sdr_output_report = soapy_sdr_output_report;
     this->m_soapy_sdr_output_report_isSet = true;
 }
setXtrxInputReport()
void SWGSDRangel::SWGDeviceReport::setXtrxInputReport (SWGXtrxInputReport * xtrx_input_report)
Definition at line 565 of file SWGDeviceReport.cpp.
References m_xtrx_input_report_isSet, and xtrx_input_report.
Referenced by XTRXInput::webapiReportGet().
{
     this->xtrx_input_report = xtrx_input_report;
     this->m_xtrx_input_report_isSet = true;
 }
setXtrxOutputReport()
void SWGSDRangel::SWGDeviceReport::setXtrxOutputReport (SWGXtrxOutputReport * xtrx_output_report)
Definition at line 575 of file SWGDeviceReport.cpp.
References m_xtrx_output_report_isSet, and xtrx_output_report.
Referenced by XTRXOutput::webapiReportGet().
{
     this->xtrx_output_report = xtrx_output_report;
     this->m_xtrx_output_report_isSet = true;
 }
Member Data Documentation
airspy_hf_report
SWGAirspyHFReport* SWGSDRangel::SWGDeviceReport::airspy_hf_report private
Definition at line 147 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getAirspyHfReport(), init(), isSet(), setAirspyHfReport(), and SWGDeviceReport().
airspy_report
SWGAirspyReport* SWGSDRangel::SWGDeviceReport::airspy_report private
Definition at line 144 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getAirspyReport(), init(), isSet(), setAirspyReport(), and SWGDeviceReport().
blade_rf2_input_report
SWGBladeRF2InputReport* SWGSDRangel::SWGDeviceReport::blade_rf2_input_report private
Definition at line 150 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getBladeRf2InputReport(), init(), isSet(), setBladeRf2InputReport(), and SWGDeviceReport().
blade_rf2_output_report
SWGBladeRF2OutputReport* SWGSDRangel::SWGDeviceReport::blade_rf2_output_report private
Definition at line 153 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getBladeRf2OutputReport(), init(), isSet(), setBladeRf2OutputReport(), and SWGDeviceReport().
device_hw_type
QString* SWGSDRangel::SWGDeviceReport::device_hw_type private
Definition at line 138 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getDeviceHwType(), init(), isSet(), setDeviceHwType(), and SWGDeviceReport().
direction
qint32 SWGSDRangel::SWGDeviceReport::direction private
Definition at line 141 of file SWGDeviceReport.h.
Referenced by asJsonObject(), fromJsonObject(), getDirection(), init(), setDirection(), and SWGDeviceReport().
file_input_report
SWGFileInputReport* SWGSDRangel::SWGDeviceReport::file_input_report private
Definition at line 156 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFileInputReport(), init(), isSet(), setFileInputReport(), and SWGDeviceReport().
kiwi_sdr_report
SWGKiwiSDRReport* SWGSDRangel::SWGDeviceReport::kiwi_sdr_report private
Definition at line 162 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getKiwiSdrReport(), init(), isSet(), setKiwiSdrReport(), and SWGDeviceReport().
lime_sdr_input_report
SWGLimeSdrInputReport* SWGSDRangel::SWGDeviceReport::lime_sdr_input_report private
Definition at line 159 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getLimeSdrInputReport(), init(), isSet(), setLimeSdrInputReport(), and SWGDeviceReport().
lime_sdr_output_report
SWGLimeSdrOutputReport* SWGSDRangel::SWGDeviceReport::lime_sdr_output_report private
Definition at line 165 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getLimeSdrOutputReport(), init(), isSet(), setLimeSdrOutputReport(), and SWGDeviceReport().
local_input_report
SWGLocalInputReport* SWGSDRangel::SWGDeviceReport::local_input_report private
Definition at line 168 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getLocalInputReport(), init(), isSet(), setLocalInputReport(), and SWGDeviceReport().
local_output_report
SWGLocalOutputReport* SWGSDRangel::SWGDeviceReport::local_output_report private
Definition at line 171 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getLocalOutputReport(), init(), isSet(), setLocalOutputReport(), and SWGDeviceReport().
m_airspy_hf_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_airspy_hf_report_isSet private
Definition at line 148 of file SWGDeviceReport.h.
Referenced by init(), setAirspyHfReport(), and SWGDeviceReport().
m_airspy_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_airspy_report_isSet private
Definition at line 145 of file SWGDeviceReport.h.
Referenced by init(), setAirspyReport(), and SWGDeviceReport().
m_blade_rf2_input_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_blade_rf2_input_report_isSet private
Definition at line 151 of file SWGDeviceReport.h.
Referenced by init(), setBladeRf2InputReport(), and SWGDeviceReport().
m_blade_rf2_output_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_blade_rf2_output_report_isSet private
Definition at line 154 of file SWGDeviceReport.h.
Referenced by init(), setBladeRf2OutputReport(), and SWGDeviceReport().
m_device_hw_type_isSet
bool SWGSDRangel::SWGDeviceReport::m_device_hw_type_isSet private
Definition at line 139 of file SWGDeviceReport.h.
Referenced by init(), setDeviceHwType(), and SWGDeviceReport().
m_direction_isSet
bool SWGSDRangel::SWGDeviceReport::m_direction_isSet private
Definition at line 142 of file SWGDeviceReport.h.
Referenced by asJsonObject(), init(), isSet(), setDirection(), and SWGDeviceReport().
m_file_input_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_file_input_report_isSet private
Definition at line 157 of file SWGDeviceReport.h.
Referenced by init(), setFileInputReport(), and SWGDeviceReport().
m_kiwi_sdr_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_kiwi_sdr_report_isSet private
Definition at line 163 of file SWGDeviceReport.h.
Referenced by init(), setKiwiSdrReport(), and SWGDeviceReport().
m_lime_sdr_input_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_lime_sdr_input_report_isSet private
Definition at line 160 of file SWGDeviceReport.h.
Referenced by init(), setLimeSdrInputReport(), and SWGDeviceReport().
m_lime_sdr_output_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_lime_sdr_output_report_isSet private
Definition at line 166 of file SWGDeviceReport.h.
Referenced by init(), setLimeSdrOutputReport(), and SWGDeviceReport().
m_local_input_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_local_input_report_isSet private
Definition at line 169 of file SWGDeviceReport.h.
Referenced by init(), setLocalInputReport(), and SWGDeviceReport().
m_local_output_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_local_output_report_isSet private
Definition at line 172 of file SWGDeviceReport.h.
Referenced by init(), setLocalOutputReport(), and SWGDeviceReport().
m_perseus_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_perseus_report_isSet private
Definition at line 175 of file SWGDeviceReport.h.
Referenced by init(), setPerseusReport(), and SWGDeviceReport().
m_pluto_sdr_input_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_pluto_sdr_input_report_isSet private
Definition at line 178 of file SWGDeviceReport.h.
Referenced by init(), setPlutoSdrInputReport(), and SWGDeviceReport().
m_pluto_sdr_output_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_pluto_sdr_output_report_isSet private
Definition at line 181 of file SWGDeviceReport.h.
Referenced by init(), setPlutoSdrOutputReport(), and SWGDeviceReport().
m_remote_input_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_remote_input_report_isSet private
Definition at line 190 of file SWGDeviceReport.h.
Referenced by init(), setRemoteInputReport(), and SWGDeviceReport().
m_remote_output_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_remote_output_report_isSet private
Definition at line 187 of file SWGDeviceReport.h.
Referenced by init(), setRemoteOutputReport(), and SWGDeviceReport().
m_rtl_sdr_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_rtl_sdr_report_isSet private
Definition at line 184 of file SWGDeviceReport.h.
Referenced by init(), setRtlSdrReport(), and SWGDeviceReport().
m_sdr_play_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_sdr_play_report_isSet private
Definition at line 193 of file SWGDeviceReport.h.
Referenced by init(), setSdrPlayReport(), and SWGDeviceReport().
m_soapy_sdr_input_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_soapy_sdr_input_report_isSet private
Definition at line 196 of file SWGDeviceReport.h.
Referenced by init(), setSoapySdrInputReport(), and SWGDeviceReport().
m_soapy_sdr_output_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_soapy_sdr_output_report_isSet private
Definition at line 199 of file SWGDeviceReport.h.
Referenced by init(), setSoapySdrOutputReport(), and SWGDeviceReport().
m_xtrx_input_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_xtrx_input_report_isSet private
Definition at line 202 of file SWGDeviceReport.h.
Referenced by init(), setXtrxInputReport(), and SWGDeviceReport().
m_xtrx_output_report_isSet
bool SWGSDRangel::SWGDeviceReport::m_xtrx_output_report_isSet private
Definition at line 205 of file SWGDeviceReport.h.
Referenced by init(), setXtrxOutputReport(), and SWGDeviceReport().
perseus_report
SWGPerseusReport* SWGSDRangel::SWGDeviceReport::perseus_report private
Definition at line 174 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getPerseusReport(), init(), isSet(), setPerseusReport(), and SWGDeviceReport().
pluto_sdr_input_report
SWGPlutoSdrInputReport* SWGSDRangel::SWGDeviceReport::pluto_sdr_input_report private
Definition at line 177 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getPlutoSdrInputReport(), init(), isSet(), setPlutoSdrInputReport(), and SWGDeviceReport().
pluto_sdr_output_report
SWGPlutoSdrOutputReport* SWGSDRangel::SWGDeviceReport::pluto_sdr_output_report private
Definition at line 180 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getPlutoSdrOutputReport(), init(), isSet(), setPlutoSdrOutputReport(), and SWGDeviceReport().
remote_input_report
SWGRemoteInputReport* SWGSDRangel::SWGDeviceReport::remote_input_report private
Definition at line 189 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getRemoteInputReport(), init(), isSet(), setRemoteInputReport(), and SWGDeviceReport().
remote_output_report
SWGRemoteOutputReport* SWGSDRangel::SWGDeviceReport::remote_output_report private
Definition at line 186 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getRemoteOutputReport(), init(), isSet(), setRemoteOutputReport(), and SWGDeviceReport().
rtl_sdr_report
SWGRtlSdrReport* SWGSDRangel::SWGDeviceReport::rtl_sdr_report private
Definition at line 183 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getRtlSdrReport(), init(), isSet(), setRtlSdrReport(), and SWGDeviceReport().
sdr_play_report
SWGSDRPlayReport* SWGSDRangel::SWGDeviceReport::sdr_play_report private
Definition at line 192 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSdrPlayReport(), init(), isSet(), setSdrPlayReport(), and SWGDeviceReport().
soapy_sdr_input_report
SWGSoapySDRReport* SWGSDRangel::SWGDeviceReport::soapy_sdr_input_report private
Definition at line 195 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSoapySdrInputReport(), init(), isSet(), setSoapySdrInputReport(), and SWGDeviceReport().
soapy_sdr_output_report
SWGSoapySDRReport* SWGSDRangel::SWGDeviceReport::soapy_sdr_output_report private
Definition at line 198 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSoapySdrOutputReport(), init(), isSet(), setSoapySdrOutputReport(), and SWGDeviceReport().
xtrx_input_report
SWGXtrxInputReport* SWGSDRangel::SWGDeviceReport::xtrx_input_report private
Definition at line 201 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getXtrxInputReport(), init(), isSet(), setXtrxInputReport(), and SWGDeviceReport().
xtrx_output_report
SWGXtrxOutputReport* SWGSDRangel::SWGDeviceReport::xtrx_output_report private
Definition at line 204 of file SWGDeviceReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getXtrxOutputReport(), init(), isSet(), setXtrxOutputReport(), and SWGDeviceReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGDeviceReport.h
swagger/sdrangel/code/qt5/client/SWGDeviceReport.cpp