SDRAngel: Bladerf1Input Class Reference
Bladerf1Input Class Reference
#include <bladerf1input.h>
Classes
class MsgConfigureBladerf1
class MsgFileRecord
class MsgStartStop
Public Member Functions
Bladerf1Input (DeviceAPI *deviceAPI)
virtual ~Bladerf1Input ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
bool applySettings (const BladeRF1InputSettings &settings, bool force)
bladerf_lna_gain getLnaGain (int lnaGain)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const BladeRF1InputSettings &settings)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const BladeRF1InputSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
BladeRF1InputSettings m_settings
struct bladerf * m_dev
Bladerf1InputThread * m_bladerfThread
QString m_deviceDescription
DeviceBladeRF1Params m_sharedParams
bool m_running
FileRecord * m_fileSink
File sink to record device I/Q output.
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 38 of file bladerf1input.h.
Constructor & Destructor Documentation
Bladerf1Input()
Bladerf1Input::Bladerf1Input (DeviceAPI * deviceAPI)
Definition at line 43 of file bladerf1input.cpp.
References arg().
Referenced by Bladerf1Input::MsgStartStop::MsgStartStop().
                                                  :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_dev(0),
     m_bladerfThread(0),
     m_deviceDescription("BladeRFInput"),
     m_running(false)
 {
     openDevice();
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     m_deviceAPI->setBuddySharedPtr(&m_sharedParams);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~Bladerf1Input()
Bladerf1Input::~Bladerf1Input () virtual
Definition at line 62 of file bladerf1input.cpp.
References closeDevice(), m_deviceAPI, m_fileSink, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::removeAncillarySink(), DeviceAPI::setBuddySharedPtr(), and stop().
Referenced by Bladerf1Input::MsgStartStop::MsgStartStop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
     closeDevice();
     m_deviceAPI->setBuddySharedPtr(0);
 }
Member Function Documentation
applySettings()
bool Bladerf1Input::applySettings (const BladeRF1InputSettings & settings, bool force) private
Definition at line 340 of file bladerf1input.cpp.
References DeviceSampleSource::calculateDeviceCenterFrequency(), DeviceAPI::configureCorrections(), DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceAPI::getDeviceSinkEngine(), getLnaGain(), DeviceAPI::getSinkBuddies(), FileRecord::handleMessage(), BladeRF1InputSettings::m_bandwidth, m_bladerfThread, BladeRF1InputSettings::m_centerFrequency, BladeRF1InputSettings::m_dcBlock, m_dev, m_deviceAPI, BladeRF1InputSettings::m_devSampleRate, BladeRF1InputSettings::m_fcPos, m_fileSink, BladeRF1InputSettings::m_iqCorrection, BladeRF1InputSettings::m_lnaGain, BladeRF1InputSettings::m_log2Decim, BladeRF1InputSettings::m_reverseAPIAddress, BladeRF1InputSettings::m_reverseAPIDeviceIndex, BladeRF1InputSettings::m_reverseAPIPort, m_settings, m_sharedParams, BladeRF1InputSettings::m_useReverseAPI, BladeRF1InputSettings::m_vga1, BladeRF1InputSettings::m_vga2, BladeRF1InputSettings::m_xb200, DeviceBladeRF1Params::m_xb200Attached, BladeRF1InputSettings::m_xb200Filter, BladeRF1InputSettings::m_xb200Path, MessageQueue::push(), Bladerf1InputThread::setFcPos(), Bladerf1InputThread::setLog2Decimation(), DSPDeviceSinkEngine::state(), DSPDeviceSinkEngine::StRunning, and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     bool forwardChange = false;
     QList<QString> reverseAPIKeys;
 //  QMutexLocker mutexLocker(&m_mutex);
     qDebug() << "BladerfInput::applySettings: m_dev: " << m_dev;
     if ((m_settings.m_dcBlock != settings.m_dcBlock) || force) {
         reverseAPIKeys.append("dcBlock");
     }
     if ((m_settings.m_iqCorrection != settings.m_iqCorrection) || force) {
         reverseAPIKeys.append("iqCorrection");
     }
     if ((m_settings.m_dcBlock != settings.m_dcBlock) ||
         (m_settings.m_iqCorrection != settings.m_iqCorrection) || force)
     {
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqCorrection);
     }
     if ((m_settings.m_lnaGain != settings.m_lnaGain) || force)
     {
         reverseAPIKeys.append("lnaGain");
         if (m_dev != 0)
         {
             if(bladerf_set_lna_gain(m_dev, getLnaGain(settings.m_lnaGain)) != 0) {
                 qDebug("BladerfInput::applySettings: bladerf_set_lna_gain() failed");
             } else {
                 qDebug() << "BladerfInput::applySettings: LNA gain set to " << getLnaGain(settings.m_lnaGain);
             }
         }
     }
     if ((m_settings.m_vga1 != settings.m_vga1) || force)
     {
         reverseAPIKeys.append("vga1");
         if (m_dev != 0)
         {
             if(bladerf_set_rxvga1(m_dev, settings.m_vga1) != 0) {
                 qDebug("BladerfInput::applySettings: bladerf_set_rxvga1() failed");
             } else {
                 qDebug() << "BladerfInput::applySettings: VGA1 gain set to " << settings.m_vga1;
             }
         }
     }
     if ((m_settings.m_vga2 != settings.m_vga2) || force)
     {
         reverseAPIKeys.append("vga2");
         if(m_dev != 0)
         {
             if(bladerf_set_rxvga2(m_dev, settings.m_vga2) != 0) {
                 qDebug("BladerfInput::applySettings: bladerf_set_rxvga2() failed");
             } else {
                 qDebug() << "BladerfInput::applySettings: VGA2 gain set to " << settings.m_vga2;
             }
         }
     }
     if ((m_settings.m_xb200 != settings.m_xb200) || force)
     {
         reverseAPIKeys.append("xb200");
         if (m_dev != 0)
         {
             bool changeSettings;
             if (m_deviceAPI->getSinkBuddies().size() > 0)
             {
                 DeviceAPI *buddy = m_deviceAPI->getSinkBuddies()[0];
                 if (buddy->getDeviceSinkEngine()->state() == DSPDeviceSinkEngine::StRunning) { // Tx side running
                     changeSettings = false;
                 } else {
                     changeSettings = true;
                 }
             }
             else // No Tx open
             {
                 changeSettings = true;
             }
             if (changeSettings)
             {
                 if (settings.m_xb200)
                 {
                     if (bladerf_expansion_attach(m_dev, BLADERF_XB_200) != 0) {
                         qDebug("BladerfInput::applySettings: bladerf_expansion_attach(xb200) failed");
                     } else {
                         qDebug() << "BladerfInput::applySettings: Attach XB200";
                     }
                 }
                 else
                 {
                     if (bladerf_expansion_attach(m_dev, BLADERF_XB_NONE) != 0) {
                         qDebug("BladerfInput::applySettings: bladerf_expansion_attach(none) failed");
                     } else {
                         qDebug() << "BladerfInput::applySettings: Detach XB200";
                     }
                 }
                 m_sharedParams.m_xb200Attached = settings.m_xb200;
             }
         }
     }
     if ((m_settings.m_xb200Path != settings.m_xb200Path) || force)
     {
         reverseAPIKeys.append("xb200Path");
         if (m_dev != 0)
         {
             if(bladerf_xb200_set_path(m_dev, BLADERF_MODULE_RX, settings.m_xb200Path) != 0) {
                 qDebug("BladerfInput::applySettings: bladerf_xb200_set_path(BLADERF_MODULE_RX) failed");
             } else {
                 qDebug() << "BladerfInput::applySettings: set xb200 path to " << settings.m_xb200Path;
             }
         }
     }
     if ((m_settings.m_xb200Filter != settings.m_xb200Filter) || force)
     {
         reverseAPIKeys.append("xb200Filter");
         if (m_dev != 0)
         {
             if(bladerf_xb200_set_filterbank(m_dev, BLADERF_MODULE_RX, settings.m_xb200Filter) != 0) {
                 qDebug("BladerfInput::applySettings: bladerf_xb200_set_filterbank(BLADERF_MODULE_RX) failed");
             } else {
                 qDebug() << "BladerfInput::applySettings: set xb200 filter to " << settings.m_xb200Filter;
             }
         }
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || force)
     {
         reverseAPIKeys.append("devSampleRate");
         forwardChange = true;
         if (m_dev != 0)
         {
             unsigned int actualSamplerate;
             if (bladerf_set_sample_rate(m_dev, BLADERF_MODULE_RX, settings.m_devSampleRate, &actualSamplerate) < 0) {
                 qCritical("BladerfInput::applySettings: could not set sample rate: %d", settings.m_devSampleRate);
             } else {
                 qDebug() << "BladerfInput::applySettings: bladerf_set_sample_rate(BLADERF_MODULE_RX) actual sample rate is " << actualSamplerate;
             }
         }
     }
     if ((m_settings.m_bandwidth != settings.m_bandwidth) || force)
     {
         reverseAPIKeys.append("bandwidth");
         if(m_dev != 0)
         {
             unsigned int actualBandwidth;
             if( bladerf_set_bandwidth(m_dev, BLADERF_MODULE_RX, settings.m_bandwidth, &actualBandwidth) < 0) {
                 qCritical("BladerfInput::applySettings: could not set bandwidth: %d", settings.m_bandwidth);
             } else {
                 qDebug() << "BladerfInput::applySettings: bladerf_set_bandwidth(BLADERF_MODULE_RX) actual bandwidth is " << actualBandwidth;
             }
         }
     }
     if ((m_settings.m_fcPos != settings.m_fcPos) || force)
     {
         reverseAPIKeys.append("fcPos");
         if (m_bladerfThread != 0)
         {
             m_bladerfThread->setFcPos((int) settings.m_fcPos);
             qDebug() << "BladerfInput::applySettings: set fc pos (enum) to " << (int) settings.m_fcPos;
         }
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         reverseAPIKeys.append("log2Decim");
         forwardChange = true;
         if (m_bladerfThread != 0)
         {
             m_bladerfThread->setLog2Decimation(settings.m_log2Decim);
             qDebug() << "BladerfInput::applySettings: set decimation to " << (1<<settings.m_log2Decim);
         }
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency) || force) {
         reverseAPIKeys.append("centerFrequency");
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency)
         || (m_settings.m_devSampleRate != settings.m_devSampleRate)
         || (m_settings.m_fcPos != settings.m_fcPos)
         || (m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         qint64 deviceCenterFrequency = DeviceSampleSource::calculateDeviceCenterFrequency(
                 settings.m_centerFrequency,
                 0,
                 settings.m_log2Decim,
                 (DeviceSampleSource::fcPos_t) settings.m_fcPos,
                 settings.m_devSampleRate,
                 DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD,
                 false);
         forwardChange = true;
         if (m_dev != 0)
         {
             if (bladerf_set_frequency( m_dev, BLADERF_MODULE_RX, deviceCenterFrequency ) != 0) {
                 qWarning("BladerfInput::applySettings: bladerf_set_frequency(%lld) failed", settings.m_centerFrequency);
             } else {
                 qDebug("BladerfInput::applySettings: bladerf_set_frequency(%lld)", settings.m_centerFrequency);
             }
         }
     }
     if (forwardChange)
     {
         int sampleRate = settings.m_devSampleRate/(1<<settings.m_log2Decim);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     qDebug() << "BladerfInput::applySettings: "
             << " m_centerFrequency: " << m_settings.m_centerFrequency << " Hz"
             << " m_bandwidth: " << m_settings.m_bandwidth
             << " m_lnaGain: " << m_settings.m_lnaGain
             << " m_vga1: " << m_settings.m_vga1
             << " m_vga2: " << m_settings.m_vga2
             << " m_log2Decim: " << m_settings.m_log2Decim
             << " m_fcPos: " << m_settings.m_fcPos
             << " m_devSampleRate: " << m_settings.m_devSampleRate
             << " m_dcBlock: " << m_settings.m_dcBlock
             << " m_iqCorrection: " << m_settings.m_iqCorrection
             << " m_xb200Filter: " << m_settings.m_xb200Filter
             << " m_xb200Path: " << m_settings.m_xb200Path
             << " m_xb200: " << m_settings.m_xb200;
     return true;
 }
closeDevice()
void Bladerf1Input::closeDevice () private
Definition at line 176 of file bladerf1input.cpp.
References DeviceAPI::getSinkBuddies(), DeviceBladeRF1Params::m_dev, m_dev, m_deviceAPI, and m_sharedParams.
Referenced by openDevice(), and ~Bladerf1Input().
 {
     int res;
     if (m_dev == 0) { // was never open
         return;
     }
     if ((res = bladerf_enable_module(m_dev, BLADERF_MODULE_RX, false)) < 0)
     {
         qCritical("BladerfInput::stop: bladerf_enable_module with return code %d", res);
     }
     if (m_deviceAPI->getSinkBuddies().size() == 0)
     {
         qDebug("BladerfInput::closeDevice: closing device since Tx side is not open");
         if(m_dev != 0) // close BladeRF
         {
             bladerf_close(m_dev);
         }
     }
     m_sharedParams.m_dev = 0;
     m_dev = 0;
 }
deserialize()
bool Bladerf1Input::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 222 of file bladerf1input.cpp.
References Bladerf1Input::MsgConfigureBladerf1::create(), BladeRF1InputSettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and BladeRF1InputSettings::resetToDefaults().
Referenced by Bladerf1Input::MsgStartStop::MsgStartStop().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureBladerf1* message = MsgConfigureBladerf1::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureBladerf1* messageToGUI = MsgConfigureBladerf1::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void Bladerf1Input::destroy () virtual
Implements DeviceSampleSource.
Definition at line 77 of file bladerf1input.cpp.
Referenced by Bladerf1Input::MsgStartStop::MsgStartStop().
 {
     delete this;
 }
getCenterFrequency()
quint64 Bladerf1Input::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 255 of file bladerf1input.cpp.
References BladeRF1InputSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & Bladerf1Input::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 244 of file bladerf1input.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getLnaGain()
bladerf_lna_gain Bladerf1Input::getLnaGain (int lnaGain) private
Definition at line 601 of file bladerf1input.cpp.
Referenced by applySettings().
 {
     if (lnaGain == 2)
     {
         return BLADERF_LNA_GAIN_MAX;
     }
     else if (lnaGain == 1)
     {
         return BLADERF_LNA_GAIN_MID;
     }
     else
     {
         return BLADERF_LNA_GAIN_BYPASS;
     }
 }
getSampleRate()
int Bladerf1Input::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 249 of file bladerf1input.cpp.
References BladeRF1InputSettings::m_devSampleRate, BladeRF1InputSettings::m_log2Decim, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     int rate = m_settings.m_devSampleRate;
     return (rate / (1<<m_settings.m_log2Decim));
 }
handleMessage()
bool Bladerf1Input::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 275 of file bladerf1input.cpp.
References applySettings(), FileRecord::genUniqueFileName(), DeviceAPI::getDeviceUID(), Bladerf1Input::MsgConfigureBladerf1::getForce(), Bladerf1Input::MsgConfigureBladerf1::getSettings(), Bladerf1Input::MsgFileRecord::getStartStop(), Bladerf1Input::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), m_deviceAPI, BladeRF1InputSettings::m_fileRecordName, m_fileSink, m_settings, BladeRF1InputSettings::m_useReverseAPI, Message::match(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (MsgConfigureBladerf1::match(message))
     {
         MsgConfigureBladerf1& conf = (MsgConfigureBladerf1&) message;
         qDebug() << "Bladerf1Input::handleMessage: MsgConfigureBladerf1";
         if (!applySettings(conf.getSettings(), conf.getForce()))
         {
             qDebug("BladeRF config error");
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "BladerfInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "BladerfInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void Bladerf1Input::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 144 of file bladerf1input.cpp.
References applySettings(), and m_settings.
Referenced by Bladerf1Input::MsgStartStop::MsgStartStop().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void Bladerf1Input::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 867 of file bladerf1input.cpp.
Referenced by ~Bladerf1Input().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "Bladerf1Input::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("Bladerf1Input::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openDevice()
bool Bladerf1Input::openDevice () private
Definition at line 82 of file bladerf1input.cpp.
References closeDevice(), DeviceAPI::getBuddySharedPtr(), DeviceAPI::getSamplingDeviceSerial(), DeviceAPI::getSinkBuddies(), DeviceBladeRF1Params::m_dev, m_dev, m_deviceAPI, DeviceSampleSource::m_sampleFifo, m_sharedParams, DeviceBladeRF1::open_bladerf(), and SampleSinkFifo::setSize().
 {
     if (m_dev != 0)
     {
         closeDevice();
     }
     int res;
     if (!m_sampleFifo.setSize(96000 * 4))
     {
         qCritical("BladerfInput::openDevice: could not allocate SampleFifo");
         return false;
     }
     if (m_deviceAPI->getSinkBuddies().size() > 0)
     {
         DeviceAPI *sinkBuddy = m_deviceAPI->getSinkBuddies()[0];
         DeviceBladeRF1Params *buddySharedParams = (DeviceBladeRF1Params *) sinkBuddy->getBuddySharedPtr();
         if (buddySharedParams == 0)
         {
             qCritical("BladerfInput::openDevice: could not get shared parameters from buddy");
             return false;
         }
         if (buddySharedParams->m_dev == 0) // device is not opened by buddy
         {
             qCritical("BladerfInput::openDevice: could not get BladeRF handle from buddy");
             return false;
         }
         m_sharedParams = *(buddySharedParams); // copy parameters from buddy
         m_dev = m_sharedParams.m_dev;          // get BladeRF handle
     }
     else
     {
         if (!DeviceBladeRF1::open_bladerf(&m_dev, qPrintable(m_deviceAPI->getSamplingDeviceSerial())))
         {
             qCritical("BladerfInput::start: could not open BladeRF %s", qPrintable(m_deviceAPI->getSamplingDeviceSerial()));
             return false;
         }
         m_sharedParams.m_dev = m_dev;
     }
     // TODO: adjust USB transfer data according to sample rate
     if ((res = bladerf_sync_config(m_dev, BLADERF_RX_X1, BLADERF_FORMAT_SC16_Q11, 64, 8192, 32, 10000)) < 0)
     {
         qCritical("BladerfInput::start: bladerf_sync_config with return code %d", res);
         return false;
     }
     if ((res = bladerf_enable_module(m_dev, BLADERF_MODULE_RX, true)) < 0)
     {
         qCritical("BladerfInput::start: bladerf_enable_module with return code %d", res);
         return false;
     }
     return true;
 }
serialize()
QByteArray Bladerf1Input::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 217 of file bladerf1input.cpp.
References m_settings, and BladeRF1InputSettings::serialize().
Referenced by Bladerf1Input::MsgStartStop::MsgStartStop().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void Bladerf1Input::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 260 of file bladerf1input.cpp.
References Bladerf1Input::MsgConfigureBladerf1::create(), BladeRF1InputSettings::m_centerFrequency, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     BladeRF1InputSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureBladerf1* message = MsgConfigureBladerf1::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureBladerf1* messageToGUI = MsgConfigureBladerf1::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setMessageQueueToGUI()
virtual void Bladerf1Input::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 113 of file bladerf1input.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSource::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void Bladerf1Input::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 116 of file bladerf1input.h.
References getCenterFrequency(), handleMessage(), setCenterFrequency(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
start()
bool Bladerf1Input::start () virtual
Implements DeviceSampleSource.
Definition at line 149 of file bladerf1input.cpp.
References applySettings(), m_bladerfThread, m_dev, BladeRF1InputSettings::m_fcPos, BladeRF1InputSettings::m_log2Decim, m_running, DeviceSampleSource::m_sampleFifo, m_settings, Bladerf1InputThread::setFcPos(), Bladerf1InputThread::setLog2Decimation(), Bladerf1InputThread::startWork(), and stop().
Referenced by Bladerf1Input::MsgStartStop::MsgStartStop().
 {
 //  QMutexLocker mutexLocker(&m_mutex);
     if (!m_dev)
     {
         qDebug("BladerfInput::start: no device handle");
         return false;
     }
     if (m_running) stop();
     m_bladerfThread = new Bladerf1InputThread(m_dev, &m_sampleFifo);
     m_bladerfThread->setLog2Decimation(m_settings.m_log2Decim);
     m_bladerfThread->setFcPos((int) m_settings.m_fcPos);
     m_bladerfThread->startWork();
 //  mutexLocker.unlock();
     applySettings(m_settings, true);
     qDebug("BladerfInput::startInput: started");
     m_running = true;
     return true;
 }
stop()
void Bladerf1Input::stop () virtual
Implements DeviceSampleSource.
Definition at line 203 of file bladerf1input.cpp.
References m_bladerfThread, m_running, and Bladerf1InputThread::stopWork().
Referenced by Bladerf1Input::MsgStartStop::MsgStartStop(), start(), and ~Bladerf1Input().
 {
 //  QMutexLocker mutexLocker(&m_mutex);
     if(m_bladerfThread != 0)
     {
         m_bladerfThread->stopWork();
         delete m_bladerfThread;
         m_bladerfThread = 0;
     }
     m_running = false;
 }
webapiFormatDeviceSettings()
void Bladerf1Input::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const BladeRF1InputSettings & settings) private
Definition at line 628 of file bladerf1input.cpp.
References SWGSDRangel::SWGDeviceSettings::getBladeRf1InputSettings(), SWGSDRangel::SWGBladeRF1InputSettings::getFileRecordName(), SWGSDRangel::SWGBladeRF1InputSettings::getReverseApiAddress(), BladeRF1InputSettings::m_bandwidth, BladeRF1InputSettings::m_centerFrequency, BladeRF1InputSettings::m_dcBlock, BladeRF1InputSettings::m_devSampleRate, BladeRF1InputSettings::m_fcPos, BladeRF1InputSettings::m_fileRecordName, BladeRF1InputSettings::m_iqCorrection, BladeRF1InputSettings::m_lnaGain, BladeRF1InputSettings::m_log2Decim, BladeRF1InputSettings::m_reverseAPIAddress, BladeRF1InputSettings::m_reverseAPIDeviceIndex, BladeRF1InputSettings::m_reverseAPIPort, BladeRF1InputSettings::m_useReverseAPI, BladeRF1InputSettings::m_vga1, BladeRF1InputSettings::m_vga2, BladeRF1InputSettings::m_xb200, BladeRF1InputSettings::m_xb200Filter, BladeRF1InputSettings::m_xb200Path, SWGSDRangel::SWGBladeRF1InputSettings::setBandwidth(), SWGSDRangel::SWGBladeRF1InputSettings::setCenterFrequency(), SWGSDRangel::SWGBladeRF1InputSettings::setDcBlock(), SWGSDRangel::SWGBladeRF1InputSettings::setDevSampleRate(), SWGSDRangel::SWGBladeRF1InputSettings::setFcPos(), SWGSDRangel::SWGBladeRF1InputSettings::setFileRecordName(), SWGSDRangel::SWGBladeRF1InputSettings::setIqCorrection(), SWGSDRangel::SWGBladeRF1InputSettings::setLnaGain(), SWGSDRangel::SWGBladeRF1InputSettings::setLog2Decim(), SWGSDRangel::SWGBladeRF1InputSettings::setReverseApiAddress(), SWGSDRangel::SWGBladeRF1InputSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGBladeRF1InputSettings::setReverseApiPort(), SWGSDRangel::SWGBladeRF1InputSettings::setUseReverseApi(), SWGSDRangel::SWGBladeRF1InputSettings::setVga1(), SWGSDRangel::SWGBladeRF1InputSettings::setVga2(), SWGSDRangel::SWGBladeRF1InputSettings::setXb200(), SWGSDRangel::SWGBladeRF1InputSettings::setXb200Filter(), and SWGSDRangel::SWGBladeRF1InputSettings::setXb200Path().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getBladeRf1InputSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getBladeRf1InputSettings()->setDevSampleRate(settings.m_devSampleRate);
     response.getBladeRf1InputSettings()->setLnaGain(settings.m_lnaGain);
     response.getBladeRf1InputSettings()->setVga1(settings.m_vga1);
     response.getBladeRf1InputSettings()->setVga2(settings.m_vga2);
     response.getBladeRf1InputSettings()->setBandwidth(settings.m_bandwidth);
     response.getBladeRf1InputSettings()->setLog2Decim(settings.m_log2Decim);
     response.getBladeRf1InputSettings()->setFcPos((int) settings.m_fcPos);
     response.getBladeRf1InputSettings()->setXb200(settings.m_xb200 ? 1 : 0);
     response.getBladeRf1InputSettings()->setXb200Path((int) settings.m_xb200Path);
     response.getBladeRf1InputSettings()->setXb200Filter((int) settings.m_xb200Filter);
     response.getBladeRf1InputSettings()->setDcBlock(settings.m_dcBlock ? 1 : 0);
     response.getBladeRf1InputSettings()->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     if (response.getBladeRf1InputSettings()->getFileRecordName()) {
         *response.getBladeRf1InputSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getBladeRf1InputSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getBladeRf1InputSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getBladeRf1InputSettings()->getReverseApiAddress()) {
         *response.getBladeRf1InputSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getBladeRf1InputSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getBladeRf1InputSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getBladeRf1InputSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReverseSendSettings()
void Bladerf1Input::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const BladeRF1InputSettings & settings, bool force) private
Definition at line 767 of file bladerf1input.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), SWGSDRangel::SWGDeviceSettings::getBladeRf1InputSettings(), DeviceAPI::getDeviceSetIndex(), BladeRF1InputSettings::m_bandwidth, BladeRF1InputSettings::m_centerFrequency, BladeRF1InputSettings::m_dcBlock, m_deviceAPI, BladeRF1InputSettings::m_devSampleRate, BladeRF1InputSettings::m_fcPos, BladeRF1InputSettings::m_fileRecordName, BladeRF1InputSettings::m_iqCorrection, BladeRF1InputSettings::m_lnaGain, BladeRF1InputSettings::m_log2Decim, m_networkManager, m_networkRequest, BladeRF1InputSettings::m_reverseAPIAddress, BladeRF1InputSettings::m_reverseAPIDeviceIndex, BladeRF1InputSettings::m_reverseAPIPort, BladeRF1InputSettings::m_vga1, BladeRF1InputSettings::m_vga2, BladeRF1InputSettings::m_xb200, BladeRF1InputSettings::m_xb200Filter, BladeRF1InputSettings::m_xb200Path, SWGSDRangel::SWGBladeRF1InputSettings::setBandwidth(), SWGSDRangel::SWGDeviceSettings::setBladeRf1InputSettings(), SWGSDRangel::SWGBladeRF1InputSettings::setCenterFrequency(), SWGSDRangel::SWGBladeRF1InputSettings::setDcBlock(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGBladeRF1InputSettings::setDevSampleRate(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGBladeRF1InputSettings::setFcPos(), SWGSDRangel::SWGBladeRF1InputSettings::setFileRecordName(), SWGSDRangel::SWGBladeRF1InputSettings::setIqCorrection(), SWGSDRangel::SWGBladeRF1InputSettings::setLnaGain(), SWGSDRangel::SWGBladeRF1InputSettings::setLog2Decim(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGBladeRF1InputSettings::setVga1(), SWGSDRangel::SWGBladeRF1InputSettings::setXb200(), SWGSDRangel::SWGBladeRF1InputSettings::setXb200Filter(), and SWGSDRangel::SWGBladeRF1InputSettings::setXb200Path().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("BladeRF1"));
     swgDeviceSettings->setBladeRf1InputSettings(new SWGSDRangel::SWGBladeRF1InputSettings());
     SWGSDRangel::SWGBladeRF1InputSettings *swgBladeRF1Settings = swgDeviceSettings->getBladeRf1InputSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgBladeRF1Settings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("devSampleRate") || force) {
         swgBladeRF1Settings->setDevSampleRate(settings.m_devSampleRate);
     }
     if (deviceSettingsKeys.contains("lnaGain") || force) {
         swgBladeRF1Settings->setLnaGain(settings.m_lnaGain);
     }
     if (deviceSettingsKeys.contains("vga1") || force) {
         swgBladeRF1Settings->setVga1(settings.m_vga1);
     }
     if (deviceSettingsKeys.contains("vga2") || force) {
         swgBladeRF1Settings->setVga1(settings.m_vga2);
     }
     if (deviceSettingsKeys.contains("bandwidth") || force) {
         swgBladeRF1Settings->setBandwidth(settings.m_bandwidth);
     }
     if (deviceSettingsKeys.contains("log2Decim") || force) {
         swgBladeRF1Settings->setLog2Decim(settings.m_log2Decim);
     }
     if (deviceSettingsKeys.contains("fcPos") || force) {
         swgBladeRF1Settings->setFcPos((int) settings.m_fcPos);
     }
     if (deviceSettingsKeys.contains("xb200") || force) {
         swgBladeRF1Settings->setXb200(settings.m_xb200 ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("xb200Path") || force) {
         swgBladeRF1Settings->setXb200Path((int) settings.m_xb200Path);
     }
     if (deviceSettingsKeys.contains("xb200Filter") || force) {
         swgBladeRF1Settings->setXb200Filter((int) settings.m_xb200Filter);
     }
     if (deviceSettingsKeys.contains("dcBlock") || force) {
         swgBladeRF1Settings->setDcBlock(settings.m_dcBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("iqCorrection") || force) {
         swgBladeRF1Settings->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgBladeRF1Settings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void Bladerf1Input::webapiReverseSendStartStop (bool start) private
Definition at line 839 of file bladerf1input.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, BladeRF1InputSettings::m_reverseAPIAddress, BladeRF1InputSettings::m_reverseAPIDeviceIndex, BladeRF1InputSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("BladeRF1"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int Bladerf1Input::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 748 of file bladerf1input.cpp.
References Bladerf1Input::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int Bladerf1Input::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 739 of file bladerf1input.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int Bladerf1Input::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 617 of file bladerf1input.cpp.
References SWGSDRangel::SWGDeviceSettings::getBladeRf1InputSettings(), SWGSDRangel::SWGBladeRF1InputSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setBladeRf1InputSettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setBladeRf1InputSettings(new SWGSDRangel::SWGBladeRF1InputSettings());
     response.getBladeRf1InputSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int Bladerf1Input::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 662 of file bladerf1input.cpp.
References Bladerf1Input::MsgConfigureBladerf1::create(), SWGSDRangel::SWGBladeRF1InputSettings::getBandwidth(), SWGSDRangel::SWGDeviceSettings::getBladeRf1InputSettings(), SWGSDRangel::SWGBladeRF1InputSettings::getCenterFrequency(), SWGSDRangel::SWGBladeRF1InputSettings::getDcBlock(), SWGSDRangel::SWGBladeRF1InputSettings::getDevSampleRate(), SWGSDRangel::SWGBladeRF1InputSettings::getFcPos(), SWGSDRangel::SWGBladeRF1InputSettings::getFileRecordName(), SWGSDRangel::SWGBladeRF1InputSettings::getIqCorrection(), SWGSDRangel::SWGBladeRF1InputSettings::getLnaGain(), SWGSDRangel::SWGBladeRF1InputSettings::getLog2Decim(), SWGSDRangel::SWGBladeRF1InputSettings::getReverseApiAddress(), SWGSDRangel::SWGBladeRF1InputSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGBladeRF1InputSettings::getReverseApiPort(), SWGSDRangel::SWGBladeRF1InputSettings::getUseReverseApi(), SWGSDRangel::SWGBladeRF1InputSettings::getVga1(), SWGSDRangel::SWGBladeRF1InputSettings::getVga2(), SWGSDRangel::SWGBladeRF1InputSettings::getXb200(), SWGSDRangel::SWGBladeRF1InputSettings::getXb200Filter(), SWGSDRangel::SWGBladeRF1InputSettings::getXb200Path(), BladeRF1InputSettings::m_bandwidth, BladeRF1InputSettings::m_centerFrequency, BladeRF1InputSettings::m_dcBlock, BladeRF1InputSettings::m_devSampleRate, BladeRF1InputSettings::m_fcPos, BladeRF1InputSettings::m_fileRecordName, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, BladeRF1InputSettings::m_iqCorrection, BladeRF1InputSettings::m_lnaGain, BladeRF1InputSettings::m_log2Decim, BladeRF1InputSettings::m_reverseAPIAddress, BladeRF1InputSettings::m_reverseAPIDeviceIndex, BladeRF1InputSettings::m_reverseAPIPort, m_settings, BladeRF1InputSettings::m_useReverseAPI, BladeRF1InputSettings::m_vga1, BladeRF1InputSettings::m_vga2, BladeRF1InputSettings::m_xb200, BladeRF1InputSettings::m_xb200Filter, BladeRF1InputSettings::m_xb200Path, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     BladeRF1InputSettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getBladeRf1InputSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("devSampleRate")) {
         settings.m_devSampleRate = response.getBladeRf1InputSettings()->getDevSampleRate();
     }
     if (deviceSettingsKeys.contains("lnaGain")) {
         settings.m_lnaGain = response.getBladeRf1InputSettings()->getLnaGain();
     }
     if (deviceSettingsKeys.contains("vga1")) {
         settings.m_vga1 = response.getBladeRf1InputSettings()->getVga1();
     }
     if (deviceSettingsKeys.contains("vga2")) {
         settings.m_vga2 = response.getBladeRf1InputSettings()->getVga2();
     }
     if (deviceSettingsKeys.contains("bandwidth")) {
         settings.m_bandwidth = response.getBladeRf1InputSettings()->getBandwidth();
     }
     if (deviceSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getBladeRf1InputSettings()->getLog2Decim();
     }
     if (deviceSettingsKeys.contains("fcPos")) {
         settings.m_fcPos = static_cast<BladeRF1InputSettings::fcPos_t>(response.getBladeRf1InputSettings()->getFcPos());
     }
     if (deviceSettingsKeys.contains("xb200")) {
         settings.m_xb200 = response.getBladeRf1InputSettings()->getXb200() == 0 ? 0 : 1;
     }
     if (deviceSettingsKeys.contains("xb200Path")) {
         settings.m_xb200Path = static_cast<bladerf_xb200_path>(response.getBladeRf1InputSettings()->getXb200Path());
     }
     if (deviceSettingsKeys.contains("xb200Filter")) {
         settings.m_xb200Filter = static_cast<bladerf_xb200_filter>(response.getBladeRf1InputSettings()->getXb200Filter());
     }
     if (deviceSettingsKeys.contains("dcBlock")) {
         settings.m_dcBlock = response.getBladeRf1InputSettings()->getDcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("iqCorrection")) {
         settings.m_iqCorrection = response.getBladeRf1InputSettings()->getIqCorrection() != 0;
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getBladeRf1InputSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getBladeRf1InputSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getBladeRf1InputSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getBladeRf1InputSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getBladeRf1InputSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureBladerf1 *msg = MsgConfigureBladerf1::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureBladerf1 *msgToGUI = MsgConfigureBladerf1::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_bladerfThread
Bladerf1InputThread* Bladerf1Input::m_bladerfThread private
Definition at line 146 of file bladerf1input.h.
Referenced by applySettings(), start(), and stop().
m_dev
struct bladerf* Bladerf1Input::m_dev private
Definition at line 145 of file bladerf1input.h.
Referenced by applySettings(), closeDevice(), openDevice(), and start().
m_deviceAPI
DeviceAPI* Bladerf1Input::m_deviceAPI private
Definition at line 142 of file bladerf1input.h.
Referenced by applySettings(), closeDevice(), handleMessage(), openDevice(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~Bladerf1Input().
m_deviceDescription
QString Bladerf1Input::m_deviceDescription private
Definition at line 147 of file bladerf1input.h.
Referenced by getDeviceDescription().
m_fileSink
FileRecord* Bladerf1Input::m_fileSink private
File sink to record device I/Q output.
Definition at line 150 of file bladerf1input.h.
Referenced by applySettings(), handleMessage(), and ~Bladerf1Input().
m_mutex
QMutex Bladerf1Input::m_mutex private
Definition at line 143 of file bladerf1input.h.
m_networkManager
QNetworkAccessManager* Bladerf1Input::m_networkManager private
Definition at line 151 of file bladerf1input.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~Bladerf1Input().
m_networkRequest
QNetworkRequest Bladerf1Input::m_networkRequest private
Definition at line 152 of file bladerf1input.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool Bladerf1Input::m_running private
Definition at line 149 of file bladerf1input.h.
Referenced by start(), stop(), and ~Bladerf1Input().
m_settings
BladeRF1InputSettings Bladerf1Input::m_settings private
Definition at line 144 of file bladerf1input.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), serialize(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_sharedParams
DeviceBladeRF1Params Bladerf1Input::m_sharedParams private
Definition at line 148 of file bladerf1input.h.
Referenced by applySettings(), closeDevice(), and openDevice().
The documentation for this class was generated from the following files:
plugins/samplesource/bladerf1input/bladerf1input.h
plugins/samplesource/bladerf1input/bladerf1input.cpp