SDRAngel: PlutoSDRInput Class Reference
PlutoSDRInput Class Reference
#include <plutosdrinput.h>
Classes
class MsgConfigurePlutoSDR
class MsgFileRecord
class MsgStartStop
Public Member Functions
PlutoSDRInput (DeviceAPI *deviceAPI)
~PlutoSDRInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
uint32_t getADCSampleRate () const
uint32_t getFIRSampleRate () const
void getRSSI (std::string &rssiStr)
void getLORange (qint64 &minLimit, qint64 &maxLimit)
void getbbLPRange (quint32 &minLimit, quint32 &maxLimit)
void getGain (int &gainStr)
bool fetchTemperature ()
float getTemperature ()
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
void suspendBuddies ()
void resumeBuddies ()
bool applySettings (const PlutoSDRInputSettings &settings, bool force=false)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const PlutoSDRInputSettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const PlutoSDRInputSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
FileRecord * m_fileSink
QString m_deviceDescription
PlutoSDRInputSettings m_settings
bool m_running
DevicePlutoSDRShared m_deviceShared
struct iio_buffer * m_plutoRxBuffer
PlutoSDRInputThread * m_plutoSDRInputThread
DevicePlutoSDRBox::SampleRates m_deviceSampleRates
QMutex m_mutex
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 38 of file plutosdrinput.h.
Constructor & Destructor Documentation
PlutoSDRInput()
PlutoSDRInput::PlutoSDRInput (DeviceAPI * deviceAPI)
Definition at line 43 of file plutosdrinput.cpp.
References arg().
Referenced by PlutoSDRInput::MsgStartStop::MsgStartStop().
                                                  :
     m_deviceAPI(deviceAPI),
     m_fileSink(0),
     m_deviceDescription("PlutoSDRInput"),
     m_running(false),
     m_plutoRxBuffer(0),
     m_plutoSDRInputThread(0)
 {
     m_deviceSampleRates.m_addaConnvRate = 0;
     m_deviceSampleRates.m_bbRateHz = 0;
     m_deviceSampleRates.m_firRate = 0;
     m_deviceSampleRates.m_hb1Rate = 0;
     m_deviceSampleRates.m_hb2Rate = 0;
     m_deviceSampleRates.m_hb3Rate = 0;
     suspendBuddies();
     openDevice();
     resumeBuddies();
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~PlutoSDRInput()
PlutoSDRInput::~PlutoSDRInput ()
Definition at line 70 of file plutosdrinput.cpp.
References closeDevice(), m_deviceAPI, m_fileSink, m_networkManager, networkManagerFinished(), DeviceAPI::removeAncillarySink(), resumeBuddies(), and suspendBuddies().
Referenced by PlutoSDRInput::MsgStartStop::MsgStartStop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
     suspendBuddies();
     closeDevice();
     resumeBuddies();
 }
Member Function Documentation
applySettings()
bool PlutoSDRInput::applySettings (const PlutoSDRInputSettings & settings, bool force = false) private
Definition at line 359 of file plutosdrinput.cpp.
References arg(), DeviceSampleSource::calculateDeviceCenterFrequency(), DeviceAPI::configureCorrections(), DevicePlutoSDRShared::MsgCrossReportToBuddy::create(), DevicePlutoSDRBox::DEVICE_PHY, DevicePlutoSDRParams::getBox(), DeviceAPI::getDeviceEngineInputMessageQueue(), DevicePlutoSDRBox::getRxSampleRates(), DeviceAPI::getSinkBuddies(), FileRecord::handleMessage(), PlutoSDRInputThread::isRunning(), DevicePlutoSDRBox::SampleRates::m_addaConnvRate, PlutoSDRInputSettings::m_antennaPath, DevicePlutoSDRBox::SampleRates::m_bbRateHz, PlutoSDRInputSettings::m_centerFrequency, PlutoSDRInputSettings::m_dcBlock, m_deviceAPI, DevicePlutoSDRShared::m_deviceParams, m_deviceSampleRates, m_deviceShared, PlutoSDRInputSettings::m_devSampleRate, PlutoSDRInputSettings::m_fcPos, PlutoSDRInputSettings::m_fileRecordName, m_fileSink, DevicePlutoSDRBox::SampleRates::m_firRate, PlutoSDRInputSettings::m_gain, PlutoSDRInputSettings::m_gainMode, DevicePlutoSDRBox::SampleRates::m_hb1Rate, DevicePlutoSDRBox::SampleRates::m_hb2Rate, DevicePlutoSDRBox::SampleRates::m_hb3Rate, PlutoSDRInputSettings::m_hwBBDCBlock, PlutoSDRInputSettings::m_hwIQCorrection, PlutoSDRInputSettings::m_hwRFDCBlock, PlutoSDRInputSettings::m_iqCorrection, PlutoSDRInputSettings::m_log2Decim, PlutoSDRInputSettings::m_LOppmTenths, PlutoSDRInputSettings::m_lpfBW, PlutoSDRInputSettings::m_lpfFIRBW, PlutoSDRInputSettings::m_lpfFIREnable, PlutoSDRInputSettings::m_lpfFIRGain, PlutoSDRInputSettings::m_lpfFIRlog2Decim, m_plutoSDRInputThread, PlutoSDRInputSettings::m_reverseAPIAddress, PlutoSDRInputSettings::m_reverseAPIDeviceIndex, PlutoSDRInputSettings::m_reverseAPIPort, m_settings, DevicePlutoSDRShared::m_thread, DevicePlutoSDRShared::m_threadWasRunning, PlutoSDRInputSettings::m_transverterDeltaFrequency, PlutoSDRInputSettings::m_transverterMode, PlutoSDRInputSettings::m_useReverseAPI, MessageQueue::push(), DevicePlutoSDRBox::set_params(), PlutoSDRInputThread::setFcPos(), DevicePlutoSDRBox::setFIR(), DevicePlutoSDRBox::setFIREnable(), PlutoSDRInputThread::setLog2Decimation(), DevicePlutoSDRBox::setLOPPMTenths(), DevicePlutoSDRBox::setSampleRate(), PlutoSDRInputThread::startWork(), DevicePlutoSDRShared::ThreadInterface::startWork(), PlutoSDRInputThread::stopWork(), DevicePlutoSDRShared::ThreadInterface::stopWork(), PlutoSDRInputSettings::translateGainMode(), PlutoSDRInputSettings::translateRFPath(), DevicePlutoSDRBox::USE_RX, and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     bool forwardChangeOwnDSP    = false;
     bool forwardChangeOtherDSP  = false;
     bool ownThreadWasRunning    = false;
     bool suspendAllOtherThreads = false; // All others means Tx in fact
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     QLocale loc;
     QList<QString> reverseAPIKeys;
     qDebug().noquote() << "PlutoSDRInput::applySettings: center freq: " << m_settings.m_centerFrequency << " Hz"
             << " m_devSampleRate: " << loc.toString(m_settings.m_devSampleRate) << "S/s"
             << " m_LOppmTenths: " << m_settings.m_LOppmTenths
             << " m_dcBlock: " << m_settings.m_dcBlock
             << " m_iqCorrection: " << m_settings.m_iqCorrection
             << " m_hwBBDCBlock: " << m_settings.m_hwBBDCBlock
             << " m_hwRFDCBlock: " << m_settings.m_hwRFDCBlock
             << " m_hwIQCorrection: " << m_settings.m_hwIQCorrection
             << " m_lpfFIREnable: " << m_settings.m_lpfFIREnable
             << " m_lpfFIRBW: " << loc.toString(m_settings.m_lpfFIRBW)
             << " m_lpfFIRlog2Decim: " << m_settings.m_lpfFIRlog2Decim
             << " m_lpfFIRGain: " << m_settings.m_lpfFIRGain
             << " m_log2Decim: " << loc.toString(1<<m_settings.m_log2Decim)
             << " m_fcPos: " << m_settings.m_fcPos
             << " m_lpfBW: " << loc.toString(m_settings.m_lpfBW)
             << " m_gain: " << m_settings.m_gain
             << " m_antennaPath: " << (int) m_settings.m_antennaPath
             << " m_gainMode: " << (int) m_settings.m_gainMode
             << " m_transverterMode: " << m_settings.m_transverterMode
             << " m_transverterDeltaFrequency: " << m_settings.m_transverterDeltaFrequency
             << " force: " << force;
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency) || force) {
         reverseAPIKeys.append("centerFrequency");
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || force) {
         reverseAPIKeys.append("devSampleRate");
     }
     if ((m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force) {
         reverseAPIKeys.append("LOppmTenths");
     }
     if ((m_settings.m_dcBlock != settings.m_dcBlock) || force) {
         reverseAPIKeys.append("dcBlock");
     }
     if ((m_settings.m_iqCorrection != settings.m_iqCorrection) || force) {
         reverseAPIKeys.append("iqCorrection");
     }
     if ((m_settings.m_hwBBDCBlock != settings.m_hwBBDCBlock) || force) {
         reverseAPIKeys.append("hwBBDCBlock");
     }
     if ((m_settings.m_hwRFDCBlock != settings.m_hwRFDCBlock) || force) {
         reverseAPIKeys.append("hwRFDCBlock");
     }
     if ((m_settings.m_hwIQCorrection != settings.m_hwIQCorrection) || force) {
         reverseAPIKeys.append("hwIQCorrection");
     }
     if ((m_settings.m_lpfFIREnable != settings.m_lpfFIREnable) || force) {
         reverseAPIKeys.append("lpfFIREnable");
     }
     if ((m_settings.m_lpfFIRBW != settings.m_lpfFIRBW) || force) {
         reverseAPIKeys.append("lpfFIRBW");
     }
     if ((m_settings.m_lpfFIRlog2Decim != settings.m_lpfFIRlog2Decim) || force) {
         reverseAPIKeys.append("lpfFIRlog2Decim");
     }
     if ((m_settings.m_lpfFIRGain != settings.m_lpfFIRGain) || force) {
         reverseAPIKeys.append("lpfFIRGain");
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force) {
         reverseAPIKeys.append("log2Decim");
     }
     if ((m_settings.m_fcPos != settings.m_fcPos) || force) {
         reverseAPIKeys.append("fcPos");
     }
     if ((m_settings.m_lpfBW != settings.m_lpfBW) || force) {
         reverseAPIKeys.append("lpfBW");
     }
     if ((m_settings.m_gain != settings.m_gain) || force) {
         reverseAPIKeys.append("gain");
     }
     if ((m_settings.m_antennaPath != settings.m_antennaPath) || force) {
         reverseAPIKeys.append("antennaPath");
     }
     if ((m_settings.m_gainMode != settings.m_gainMode) || force) {
         reverseAPIKeys.append("gainMode");
     }
     if ((m_settings.m_transverterMode != settings.m_transverterMode) || force) {
         reverseAPIKeys.append("transverterMode");
     }
     if ((m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency) || force) {
         reverseAPIKeys.append("transverterDeltaFrequency");
     }
     if ((m_settings.m_fileRecordName != settings.m_fileRecordName) || force) {
         reverseAPIKeys.append("fileRecordName");
     }
     // determine if buddies threads or own thread need to be suspended
     // changes affecting all buddies can occur if
     //   - device to host sample rate is changed
     //   - FIR filter is enabled or disabled
     //   - FIR filter is changed
     //   - LO correction is changed
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) ||
         (m_settings.m_lpfFIREnable != settings.m_lpfFIREnable) ||
         (m_settings.m_lpfFIRlog2Decim != settings.m_lpfFIRlog2Decim) ||
         (settings.m_lpfFIRBW != m_settings.m_lpfFIRBW) ||
         (settings.m_lpfFIRGain != m_settings.m_lpfFIRGain) ||
         (m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force)
     {
         suspendAllOtherThreads = true;
     }
     if (suspendAllOtherThreads)
     {
         const std::vector<DeviceAPI*>& sinkBuddies = m_deviceAPI->getSinkBuddies();
         std::vector<DeviceAPI*>::const_iterator itSink = sinkBuddies.begin();
         for (; itSink != sinkBuddies.end(); ++itSink)
         {
             DevicePlutoSDRShared *buddySharedPtr = (DevicePlutoSDRShared *) (*itSink)->getBuddySharedPtr();
             if (buddySharedPtr->m_thread) {
                 buddySharedPtr->m_thread->stopWork();
                 buddySharedPtr->m_threadWasRunning = true;
             }
             else
             {
                 buddySharedPtr->m_threadWasRunning = false;
             }
         }
     }
     if (m_plutoSDRInputThread && m_plutoSDRInputThread->isRunning())
     {
         m_plutoSDRInputThread->stopWork();
         ownThreadWasRunning = true;
     }
     // apply settings
     if ((m_settings.m_dcBlock != settings.m_dcBlock) ||
         (m_settings.m_iqCorrection != settings.m_iqCorrection) || force)
     {
         m_deviceAPI->configureCorrections(settings.m_dcBlock, m_settings.m_iqCorrection);
     }
     // Change affecting device sample rate chain and other buddies
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) ||
         (m_settings.m_lpfFIREnable != settings.m_lpfFIREnable) ||
         (m_settings.m_lpfFIRlog2Decim != settings.m_lpfFIRlog2Decim) ||
         (settings.m_lpfFIRBW != m_settings.m_lpfFIRBW) ||
         (settings.m_lpfFIRGain != m_settings.m_lpfFIRGain) || force)
     {
         plutoBox->setFIR(settings.m_devSampleRate, settings.m_lpfFIRlog2Decim, DevicePlutoSDRBox::USE_RX, settings.m_lpfFIRBW, settings.m_lpfFIRGain);
         plutoBox->setFIREnable(settings.m_lpfFIREnable);   // eventually enable/disable FIR
         plutoBox->setSampleRate(settings.m_devSampleRate); // and set end point sample rate
         plutoBox->getRxSampleRates(m_deviceSampleRates); // pick up possible new rates
         qDebug() << "PlutoSDRInput::applySettings: BBPLL(Hz): " << m_deviceSampleRates.m_bbRateHz
                  << " ADC: " << m_deviceSampleRates.m_addaConnvRate
                  << " -HB3-> " << m_deviceSampleRates.m_hb3Rate
                  << " -HB2-> " << m_deviceSampleRates.m_hb2Rate
                  << " -HB1-> " << m_deviceSampleRates.m_hb1Rate
                  << " -FIR-> " << m_deviceSampleRates.m_firRate;
         forwardChangeOtherDSP = true;
         forwardChangeOwnDSP = (m_settings.m_devSampleRate != settings.m_devSampleRate) || force;
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         if (m_plutoSDRInputThread != 0)
         {
             m_plutoSDRInputThread->setLog2Decimation(settings.m_log2Decim);
             qDebug() << "PlutoSDRInput::applySettings: set soft decimation to " << (1<<settings.m_log2Decim);
         }
         forwardChangeOwnDSP = true;
     }
     if ((m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force)
     {
         plutoBox->setLOPPMTenths(settings.m_LOppmTenths);
         forwardChangeOtherDSP = true;
     }
     std::vector<std::string> params;
     bool paramsToSet = false;
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency)
         || (m_settings.m_fcPos != settings.m_fcPos)
         || (m_settings.m_log2Decim != settings.m_log2Decim)
         || (m_settings.m_devSampleRate != settings.m_devSampleRate)
         || (m_settings.m_transverterMode != settings.m_transverterMode)
         || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency) || force)
     {
         qint64 deviceCenterFrequency = DeviceSampleSource::calculateDeviceCenterFrequency(
                 settings.m_centerFrequency,
                 settings.m_transverterDeltaFrequency,
                 settings.m_log2Decim,
                 (DeviceSampleSource::fcPos_t) settings.m_fcPos,
                 settings.m_devSampleRate,
                 DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD,
                 settings.m_transverterMode);
         params.push_back(QString(tr("out_altvoltage0_RX_LO_frequency=%1").arg(deviceCenterFrequency)).toStdString());
         paramsToSet = true;
         forwardChangeOwnDSP = true;
         if ((m_settings.m_fcPos != settings.m_fcPos) || force)
         {
             if (m_plutoSDRInputThread != 0)
             {
                 m_plutoSDRInputThread->setFcPos(settings.m_fcPos);
                 qDebug() << "PlutoSDRInput::applySettings: set fcPos to " << settings.m_fcPos;
             }
         }
     }
     if ((m_settings.m_lpfBW != settings.m_lpfBW) || force)
     {
         params.push_back(QString(tr("in_voltage_rf_bandwidth=%1").arg(settings.m_lpfBW)).toStdString());
         paramsToSet = true;
     }
     if ((m_settings.m_antennaPath != settings.m_antennaPath) || force)
     {
         QString rfPortStr;
         PlutoSDRInputSettings::translateRFPath(settings.m_antennaPath, rfPortStr);
         params.push_back(QString(tr("in_voltage0_rf_port_select=%1").arg(rfPortStr)).toStdString());
         paramsToSet = true;
     }
     if ((m_settings.m_gainMode != settings.m_gainMode) || force)
     {
         QString gainModeStr;
         PlutoSDRInputSettings::translateGainMode(settings.m_gainMode, gainModeStr);
         params.push_back(QString(tr("in_voltage0_gain_control_mode=%1").arg(gainModeStr)).toStdString());
         paramsToSet = true;
     }
     if ((m_settings.m_gain != settings.m_gain) || force)
     {
         params.push_back(QString(tr("in_voltage0_hardwaregain=%1").arg(settings.m_gain)).toStdString());
         paramsToSet = true;
     }
     if ((m_settings.m_hwBBDCBlock != settings.m_hwBBDCBlock) || force)
     {
         params.push_back(QString(tr("in_voltage_bb_dc_offset_tracking_en=%1").arg(settings.m_hwBBDCBlock ? 1 : 0)).toStdString());
         paramsToSet = true;
     }
     if ((m_settings.m_hwRFDCBlock != settings.m_hwRFDCBlock) || force)
     {
         params.push_back(QString(tr("in_voltage_rf_dc_offset_tracking_en=%1").arg(settings.m_hwRFDCBlock ? 1 : 0)).toStdString());
         paramsToSet = true;
     }
     if ((m_settings.m_hwIQCorrection != settings.m_hwIQCorrection) || force)
     {
         params.push_back(QString(tr("in_voltage_quadrature_tracking_en=%1").arg(settings.m_hwIQCorrection ? 1 : 0)).toStdString());
         paramsToSet = true;
     }
     if (paramsToSet)
     {
         plutoBox->set_params(DevicePlutoSDRBox::DEVICE_PHY, params);
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     if (suspendAllOtherThreads)
     {
         const std::vector<DeviceAPI*>& sinkBuddies = m_deviceAPI->getSinkBuddies();
         std::vector<DeviceAPI*>::const_iterator itSink = sinkBuddies.begin();
         for (; itSink != sinkBuddies.end(); ++itSink)
         {
             DevicePlutoSDRShared *buddySharedPtr = (DevicePlutoSDRShared *) (*itSink)->getBuddySharedPtr();
             if (buddySharedPtr->m_threadWasRunning) {
                 buddySharedPtr->m_thread->startWork();
             }
         }
     }
     if (ownThreadWasRunning) {
         m_plutoSDRInputThread->startWork();
     }
     // TODO: forward changes to other (Tx) DSP
     if (forwardChangeOtherDSP)
     {
         qDebug("PlutoSDRInput::applySettings: forwardChangeOtherDSP");
         const std::vector<DeviceAPI*>& sinkBuddies = m_deviceAPI->getSinkBuddies();
         std::vector<DeviceAPI*>::const_iterator itSink = sinkBuddies.begin();
         for (; itSink != sinkBuddies.end(); ++itSink)
         {
             DevicePlutoSDRShared::MsgCrossReportToBuddy *msg = DevicePlutoSDRShared::MsgCrossReportToBuddy::create(
                     settings.m_devSampleRate,
                     settings.m_lpfFIREnable,
                     settings.m_lpfFIRlog2Decim,
                     settings.m_lpfFIRBW,
                     settings.m_LOppmTenths);
             if ((*itSink)->getSamplingDeviceGUIMessageQueue())
             {
                 DevicePlutoSDRShared::MsgCrossReportToBuddy *msgToGUI = new DevicePlutoSDRShared::MsgCrossReportToBuddy(*msg);
                 (*itSink)->getSamplingDeviceGUIMessageQueue()->push(msgToGUI);
             }
             (*itSink)->getSamplingDeviceInputMessageQueue()->push(msg);
         }
     }
     if (forwardChangeOwnDSP)
     {
         qDebug("PlutoSDRInput::applySettings: forward change to self");
         int sampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Decim);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, m_settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     return true;
 }
closeDevice()
void PlutoSDRInput::closeDevice () private
Definition at line 315 of file plutosdrinput.cpp.
References DevicePlutoSDRParams::close(), DevicePlutoSDRParams::getBox(), DeviceAPI::getSinkBuddies(), m_deviceAPI, DevicePlutoSDRShared::m_deviceParams, and m_deviceShared.
Referenced by ~PlutoSDRInput().
 {
     if (m_deviceShared.m_deviceParams->getBox() == 0) { // was never open
         return;
     }
     if (m_deviceAPI->getSinkBuddies().size() == 0)
     {
         m_deviceShared.m_deviceParams->close();
         delete m_deviceShared.m_deviceParams;
         m_deviceShared.m_deviceParams = 0;
     }
 }
deserialize()
bool PlutoSDRInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 133 of file plutosdrinput.cpp.
References PlutoSDRInput::MsgConfigurePlutoSDR::create(), PlutoSDRInputSettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and PlutoSDRInputSettings::resetToDefaults().
Referenced by PlutoSDRInput::MsgStartStop::MsgStartStop().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigurePlutoSDR* message = MsgConfigurePlutoSDR::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigurePlutoSDR* messageToGUI = MsgConfigurePlutoSDR::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void PlutoSDRInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 81 of file plutosdrinput.cpp.
Referenced by PlutoSDRInput::MsgStartStop::MsgStartStop().
 {
     delete this;
 }
fetchTemperature()
bool PlutoSDRInput::fetchTemperature ()
Definition at line 739 of file plutosdrinput.cpp.
References DevicePlutoSDRBox::fetchTemp(), DevicePlutoSDRParams::getBox(), DevicePlutoSDRShared::m_deviceParams, and m_deviceShared.
Referenced by getFIRSampleRate(), and webapiFormatDeviceReport().
 {
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     return plutoBox->fetchTemp();
 }
getADCSampleRate()
uint32_t PlutoSDRInput::getADCSampleRate () const inline
Definition at line 145 of file plutosdrinput.h.
References DevicePlutoSDRBox::SampleRates::m_addaConnvRate, and m_deviceSampleRates.
Referenced by webapiFormatDeviceReport().
 { return m_deviceSampleRates.m_addaConnvRate; }
getbbLPRange()
void PlutoSDRInput::getbbLPRange (quint32 & minLimit, quint32 & maxLimit)
Definition at line 720 of file plutosdrinput.cpp.
References DevicePlutoSDRBox::getbbLPRxRange(), DevicePlutoSDRParams::getBox(), DevicePlutoSDRShared::m_deviceParams, m_deviceShared, leansdr::max(), and leansdr::min().
Referenced by getFIRSampleRate().
 {
     uint32_t min, max;
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     plutoBox->getbbLPRxRange(min, max);
     minLimit = min;
     maxLimit = max;
 }
getCenterFrequency()
quint64 PlutoSDRInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 164 of file plutosdrinput.cpp.
References PlutoSDRInputSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & PlutoSDRInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 155 of file plutosdrinput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getFIRSampleRate()
uint32_t PlutoSDRInput::getFIRSampleRate () const inline
Definition at line 146 of file plutosdrinput.h.
References fetchTemperature(), getbbLPRange(), getGain(), getLORange(), getRSSI(), getTemperature(), m_deviceSampleRates, and DevicePlutoSDRBox::SampleRates::m_hb1Rate.
 { return m_deviceSampleRates.m_hb1Rate; }
getGain()
void PlutoSDRInput::getGain (int & gainStr)
Definition at line 730 of file plutosdrinput.cpp.
References DevicePlutoSDRParams::getBox(), DevicePlutoSDRBox::getRxGain(), DevicePlutoSDRShared::m_deviceParams, and m_deviceShared.
Referenced by getFIRSampleRate(), and webapiFormatDeviceReport().
 {
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     if (!plutoBox->getRxGain(gaindB, 0)) {
         gaindB = 0;
     }
 }
getLORange()
void PlutoSDRInput::getLORange (qint64 & minLimit, qint64 & maxLimit)
Definition at line 710 of file plutosdrinput.cpp.
References DevicePlutoSDRParams::getBox(), DevicePlutoSDRBox::getRxLORange(), DevicePlutoSDRShared::m_deviceParams, m_deviceShared, leansdr::max(), and leansdr::min().
Referenced by getFIRSampleRate().
 {
     uint64_t min, max;
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     plutoBox->getRxLORange(min, max);
     minLimit = min;
     maxLimit = max;
 }
getRSSI()
void PlutoSDRInput::getRSSI (std::string & rssiStr)
Definition at line 701 of file plutosdrinput.cpp.
References DevicePlutoSDRParams::getBox(), DevicePlutoSDRBox::getRxRSSI(), DevicePlutoSDRShared::m_deviceParams, and m_deviceShared.
Referenced by getFIRSampleRate(), and webapiFormatDeviceReport().
 {
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     if (!plutoBox->getRxRSSI(rssiStr, 0)) {
         rssiStr = "xxx dB";
     }
 }
getSampleRate()
int PlutoSDRInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 159 of file plutosdrinput.cpp.
References PlutoSDRInputSettings::m_devSampleRate, PlutoSDRInputSettings::m_log2Decim, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     return (m_settings.m_devSampleRate / (1<<m_settings.m_log2Decim));
 }
getTemperature()
float PlutoSDRInput::getTemperature ()
Definition at line 745 of file plutosdrinput.cpp.
References DevicePlutoSDRParams::getBox(), DevicePlutoSDRBox::getTemp(), DevicePlutoSDRShared::m_deviceParams, and m_deviceShared.
Referenced by getFIRSampleRate(), and webapiFormatDeviceReport().
 {
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     return plutoBox->getTemp();
 }
handleMessage()
bool PlutoSDRInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 184 of file plutosdrinput.cpp.
References applySettings(), FileRecord::genUniqueFileName(), DeviceAPI::getDeviceUID(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getDevSampleRate(), PlutoSDRInput::MsgConfigurePlutoSDR::getForce(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getLoPPMTenths(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getLpfFirbw(), DevicePlutoSDRShared::MsgCrossReportToBuddy::getLpfFiRlog2IntDec(), PlutoSDRInput::MsgConfigurePlutoSDR::getSettings(), PlutoSDRInput::MsgFileRecord::getStartStop(), PlutoSDRInput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), DevicePlutoSDRShared::MsgCrossReportToBuddy::isLpfFirEnable(), m_deviceAPI, PlutoSDRInputSettings::m_devSampleRate, PlutoSDRInputSettings::m_fileRecordName, m_fileSink, PlutoSDRInputSettings::m_LOppmTenths, PlutoSDRInputSettings::m_lpfFIRBW, PlutoSDRInputSettings::m_lpfFIREnable, PlutoSDRInputSettings::m_lpfFIRlog2Decim, m_settings, PlutoSDRInputSettings::m_useReverseAPI, Message::match(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (MsgConfigurePlutoSDR::match(message))
     {
         MsgConfigurePlutoSDR& conf = (MsgConfigurePlutoSDR&) message;
         qDebug() << "PlutoSDRInput::handleMessage: MsgConfigurePlutoSDR";
         if (!applySettings(conf.getSettings(), conf.getForce()))
         {
             qDebug("PlutoSDRInput::handleMessage config error");
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "PlutoSDRInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "PlutoSDRInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else if (DevicePlutoSDRShared::MsgCrossReportToBuddy::match(message)) // message from buddy
     {
         DevicePlutoSDRShared::MsgCrossReportToBuddy& conf = (DevicePlutoSDRShared::MsgCrossReportToBuddy&) message;
         m_settings.m_devSampleRate = conf.getDevSampleRate();
         m_settings.m_lpfFIRlog2Decim = conf.getLpfFiRlog2IntDec();
         m_settings.m_lpfFIRBW = conf.getLpfFirbw();
         m_settings.m_LOppmTenths = conf.getLoPPMTenths();
         PlutoSDRInputSettings newSettings = m_settings;
         newSettings.m_lpfFIREnable = conf.isLpfFirEnable();
         applySettings(newSettings);
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void PlutoSDRInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 86 of file plutosdrinput.cpp.
References applySettings(), and m_settings.
Referenced by PlutoSDRInput::MsgStartStop::MsgStartStop().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void PlutoSDRInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 1080 of file plutosdrinput.cpp.
Referenced by ~PlutoSDRInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "PlutoSDRInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("PlutoSDRInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openDevice()
bool PlutoSDRInput::openDevice () private
Definition at line 262 of file plutosdrinput.cpp.
References DevicePlutoSDRBox::createRxBuffer(), DevicePlutoSDRParams::getBox(), DeviceAPI::getBuddySharedPtr(), DeviceAPI::getSamplingDeviceSerial(), DeviceAPI::getSinkBuddies(), m_deviceAPI, DevicePlutoSDRShared::m_deviceParams, m_deviceShared, m_plutoRxBuffer, DeviceSampleSource::m_sampleFifo, DevicePlutoSDRParams::open(), DevicePlutoSDRBox::openRx(), PLUTOSDR_BLOCKSIZE_SAMPLES, DeviceAPI::setBuddySharedPtr(), and SampleSinkFifo::setSize().
 {
     if (!m_sampleFifo.setSize(PLUTOSDR_BLOCKSIZE_SAMPLES))
     {
         qCritical("PlutoSDRInput::openDevice: could not allocate SampleFifo");
         return false;
     }
     else
     {
         qDebug("PlutoSDRInput::openDevice: allocated SampleFifo");
     }
     // look for Tx buddy and get reference to common parameters
     if (m_deviceAPI->getSinkBuddies().size() > 0) // then sink
     {
         qDebug("PlutoSDRInput::openDevice: look at Tx buddy");
         DeviceAPI *sinkBuddy = m_deviceAPI->getSinkBuddies()[0];
         DevicePlutoSDRShared* buddySharedPtr = (DevicePlutoSDRShared*) sinkBuddy->getBuddySharedPtr();
         m_deviceShared.m_deviceParams = buddySharedPtr->m_deviceParams;
         if (m_deviceShared.m_deviceParams == 0)
         {
             qCritical("PlutoSDRInput::openDevice: cannot get device parameters from Tx buddy");
             return false; // the device params should have been created by the buddy
         }
         else
         {
             qDebug("PlutoSDRInput::openDevice: getting device parameters from Tx buddy");
         }
     }
     // There is no buddy then create the first PlutoSDR common parameters
     // open the device this will also populate common fields
     else
     {
         qDebug("PlutoSDRInput::openDevice: open device here");
         m_deviceShared.m_deviceParams = new DevicePlutoSDRParams();
         char serial[256];
         strcpy(serial, qPrintable(m_deviceAPI->getSamplingDeviceSerial()));
         m_deviceShared.m_deviceParams->open(serial);
     }
     m_deviceAPI->setBuddySharedPtr(&m_deviceShared); // propagate common parameters to API
     // acquire the channel
     DevicePlutoSDRBox *plutoBox =  m_deviceShared.m_deviceParams->getBox();
     plutoBox->openRx();
     m_plutoRxBuffer = plutoBox->createRxBuffer(PLUTOSDR_BLOCKSIZE_SAMPLES, false);
     return true;
 }
resumeBuddies()
void PlutoSDRInput::resumeBuddies () private
Definition at line 344 of file plutosdrinput.cpp.
References DeviceAPI::getBuddySharedPtr(), DeviceAPI::getSinkBuddies(), i, m_deviceAPI, DevicePlutoSDRShared::m_thread, and DevicePlutoSDRShared::ThreadInterface::startWork().
Referenced by ~PlutoSDRInput().
 {
     // resume Tx buddy's thread
     for (unsigned int i = 0; i < m_deviceAPI->getSinkBuddies().size(); i++)
     {
         DeviceAPI *buddy = m_deviceAPI->getSinkBuddies()[i];
         DevicePlutoSDRShared *buddyShared = (DevicePlutoSDRShared *) buddy->getBuddySharedPtr();
         if (buddyShared->m_thread) {
             buddyShared->m_thread->startWork();
         }
     }
 }
serialize()
QByteArray PlutoSDRInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 128 of file plutosdrinput.cpp.
References m_settings, and PlutoSDRInputSettings::serialize().
Referenced by PlutoSDRInput::MsgStartStop::MsgStartStop().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void PlutoSDRInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 169 of file plutosdrinput.cpp.
References PlutoSDRInput::MsgConfigurePlutoSDR::create(), PlutoSDRInputSettings::m_centerFrequency, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     PlutoSDRInputSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigurePlutoSDR* message = MsgConfigurePlutoSDR::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigurePlutoSDR* messageToGUI = MsgConfigurePlutoSDR::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setMessageQueueToGUI()
virtual void PlutoSDRInput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 113 of file plutosdrinput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSource::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void PlutoSDRInput::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 116 of file plutosdrinput.h.
References getCenterFrequency(), handleMessage(), setCenterFrequency(), webapiReportGet(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
start()
bool PlutoSDRInput::start () virtual
Implements DeviceSampleSource.
Definition at line 91 of file plutosdrinput.cpp.
References applySettings(), DevicePlutoSDRParams::getBox(), DevicePlutoSDRShared::m_deviceParams, m_deviceShared, PlutoSDRInputSettings::m_log2Decim, m_plutoSDRInputThread, m_running, DeviceSampleSource::m_sampleFifo, m_settings, DevicePlutoSDRShared::m_thread, PLUTOSDR_BLOCKSIZE_SAMPLES, PlutoSDRInputThread::setLog2Decimation(), PlutoSDRInputThread::startWork(), and stop().
Referenced by PlutoSDRInput::MsgStartStop::MsgStartStop().
 {
     if (!m_deviceShared.m_deviceParams->getBox()) {
         return false;
     }
     if (m_running) stop();
     // start / stop streaming is done in the thread.
     m_plutoSDRInputThread = new PlutoSDRInputThread(PLUTOSDR_BLOCKSIZE_SAMPLES, m_deviceShared.m_deviceParams->getBox(), &m_sampleFifo);
     qDebug("PlutoSDRInput::start: thread created");
     applySettings(m_settings, true);
     m_plutoSDRInputThread->setLog2Decimation(m_settings.m_log2Decim);
     m_plutoSDRInputThread->startWork();
     m_deviceShared.m_thread = m_plutoSDRInputThread;
     m_running = true;
     return true;
 }
stop()
void PlutoSDRInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 115 of file plutosdrinput.cpp.
References m_deviceShared, m_plutoSDRInputThread, m_running, DevicePlutoSDRShared::m_thread, and PlutoSDRInputThread::stopWork().
Referenced by PlutoSDRInput::MsgStartStop::MsgStartStop(), and start().
 {
     if (m_plutoSDRInputThread != 0)
     {
         m_plutoSDRInputThread->stopWork();
         delete m_plutoSDRInputThread;
         m_plutoSDRInputThread = 0;
     }
     m_deviceShared.m_thread = 0;
     m_running = false;
 }
suspendBuddies()
void PlutoSDRInput::suspendBuddies () private
Definition at line 329 of file plutosdrinput.cpp.
References DeviceAPI::getBuddySharedPtr(), DeviceAPI::getSinkBuddies(), i, m_deviceAPI, DevicePlutoSDRShared::m_thread, and DevicePlutoSDRShared::ThreadInterface::stopWork().
Referenced by ~PlutoSDRInput().
 {
     // suspend Tx buddy's thread
     for (unsigned int i = 0; i < m_deviceAPI->getSinkBuddies().size(); i++)
     {
         DeviceAPI *buddy = m_deviceAPI->getSinkBuddies()[i];
         DevicePlutoSDRShared *buddyShared = (DevicePlutoSDRShared *) buddy->getBuddySharedPtr();
         if (buddyShared->m_thread) {
             buddyShared->m_thread->stopWork();
         }
     }
 }
webapiFormatDeviceReport()
void PlutoSDRInput::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 946 of file plutosdrinput.cpp.
References fetchTemperature(), getADCSampleRate(), getGain(), SWGSDRangel::SWGDeviceReport::getPlutoSdrInputReport(), getRSSI(), getTemperature(), SWGSDRangel::SWGPlutoSdrInputReport::setAdcRate(), SWGSDRangel::SWGPlutoSdrInputReport::setGainDb(), SWGSDRangel::SWGPlutoSdrInputReport::setRssi(), and SWGSDRangel::SWGPlutoSdrInputReport::setTemperature().
Referenced by webapiReportGet().
 {
     response.getPlutoSdrInputReport()->setAdcRate(getADCSampleRate());
     std::string rssiStr;
     getRSSI(rssiStr);
     response.getPlutoSdrInputReport()->setRssi(new QString(rssiStr.c_str()));
     int gainDB;
     getGain(gainDB);
     response.getPlutoSdrInputReport()->setGainDb(gainDB);
     fetchTemperature();
     response.getPlutoSdrInputReport()->setTemperature(getTemperature());
 }
webapiFormatDeviceSettings()
void PlutoSDRInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const PlutoSDRInputSettings & settings) private
Definition at line 905 of file plutosdrinput.cpp.
References SWGSDRangel::SWGPlutoSdrInputSettings::getFileRecordName(), SWGSDRangel::SWGDeviceSettings::getPlutoSdrInputSettings(), SWGSDRangel::SWGPlutoSdrInputSettings::getReverseApiAddress(), PlutoSDRInputSettings::m_antennaPath, PlutoSDRInputSettings::m_centerFrequency, PlutoSDRInputSettings::m_dcBlock, PlutoSDRInputSettings::m_devSampleRate, PlutoSDRInputSettings::m_fcPos, PlutoSDRInputSettings::m_fileRecordName, PlutoSDRInputSettings::m_gain, PlutoSDRInputSettings::m_gainMode, PlutoSDRInputSettings::m_hwBBDCBlock, PlutoSDRInputSettings::m_hwIQCorrection, PlutoSDRInputSettings::m_hwRFDCBlock, PlutoSDRInputSettings::m_iqCorrection, PlutoSDRInputSettings::m_log2Decim, PlutoSDRInputSettings::m_LOppmTenths, PlutoSDRInputSettings::m_lpfBW, PlutoSDRInputSettings::m_lpfFIRBW, PlutoSDRInputSettings::m_lpfFIREnable, PlutoSDRInputSettings::m_lpfFIRGain, PlutoSDRInputSettings::m_lpfFIRlog2Decim, PlutoSDRInputSettings::m_reverseAPIAddress, PlutoSDRInputSettings::m_reverseAPIDeviceIndex, PlutoSDRInputSettings::m_reverseAPIPort, m_settings, PlutoSDRInputSettings::m_transverterDeltaFrequency, PlutoSDRInputSettings::m_transverterMode, PlutoSDRInputSettings::m_useReverseAPI, SWGSDRangel::SWGPlutoSdrInputSettings::setAntennaPath(), SWGSDRangel::SWGPlutoSdrInputSettings::setCenterFrequency(), SWGSDRangel::SWGPlutoSdrInputSettings::setDcBlock(), SWGSDRangel::SWGPlutoSdrInputSettings::setDevSampleRate(), SWGSDRangel::SWGPlutoSdrInputSettings::setFcPos(), SWGSDRangel::SWGPlutoSdrInputSettings::setFileRecordName(), SWGSDRangel::SWGPlutoSdrInputSettings::setGain(), SWGSDRangel::SWGPlutoSdrInputSettings::setGainMode(), SWGSDRangel::SWGPlutoSdrInputSettings::setHwBbdcBlock(), SWGSDRangel::SWGPlutoSdrInputSettings::setHwIqCorrection(), SWGSDRangel::SWGPlutoSdrInputSettings::setHwRfdcBlock(), SWGSDRangel::SWGPlutoSdrInputSettings::setIqCorrection(), SWGSDRangel::SWGPlutoSdrInputSettings::setLog2Decim(), SWGSDRangel::SWGPlutoSdrInputSettings::setLOppmTenths(), SWGSDRangel::SWGPlutoSdrInputSettings::setLpfBw(), SWGSDRangel::SWGPlutoSdrInputSettings::setLpfFirbw(), SWGSDRangel::SWGPlutoSdrInputSettings::setLpfFirEnable(), SWGSDRangel::SWGPlutoSdrInputSettings::setLpfFirGain(), SWGSDRangel::SWGPlutoSdrInputSettings::setLpfFiRlog2Decim(), SWGSDRangel::SWGPlutoSdrInputSettings::setReverseApiAddress(), SWGSDRangel::SWGPlutoSdrInputSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGPlutoSdrInputSettings::setReverseApiPort(), SWGSDRangel::SWGPlutoSdrInputSettings::setTransverterDeltaFrequency(), SWGSDRangel::SWGPlutoSdrInputSettings::setTransverterMode(), and SWGSDRangel::SWGPlutoSdrInputSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getPlutoSdrInputSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getPlutoSdrInputSettings()->setDevSampleRate(settings.m_devSampleRate);
     response.getPlutoSdrInputSettings()->setLOppmTenths(settings.m_LOppmTenths);
     response.getPlutoSdrInputSettings()->setLpfFirEnable(settings.m_lpfFIREnable ? 1 : 0);
     response.getPlutoSdrInputSettings()->setLpfFirbw(settings.m_lpfFIRBW);
     response.getPlutoSdrInputSettings()->setLpfFiRlog2Decim(settings.m_lpfFIRlog2Decim);
     response.getPlutoSdrInputSettings()->setLpfFirGain(settings.m_lpfFIRGain);
     response.getPlutoSdrInputSettings()->setFcPos((int) settings.m_fcPos);
     response.getPlutoSdrInputSettings()->setDcBlock(settings.m_dcBlock ? 1 : 0);
     response.getPlutoSdrInputSettings()->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     response.getPlutoSdrInputSettings()->setHwBbdcBlock(settings.m_hwBBDCBlock ? 1 : 0);
     response.getPlutoSdrInputSettings()->setHwRfdcBlock(settings.m_hwRFDCBlock ? 1 : 0);
     response.getPlutoSdrInputSettings()->setHwIqCorrection(settings.m_hwIQCorrection ? 1 : 0);
     response.getPlutoSdrInputSettings()->setLog2Decim(settings.m_log2Decim);
     response.getPlutoSdrInputSettings()->setLpfBw(settings.m_lpfBW);
     response.getPlutoSdrInputSettings()->setGain(settings.m_gain);
     response.getPlutoSdrInputSettings()->setAntennaPath((int) m_settings.m_antennaPath);
     response.getPlutoSdrInputSettings()->setGainMode((int) settings.m_gainMode);
     response.getPlutoSdrInputSettings()->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     response.getPlutoSdrInputSettings()->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     if (response.getPlutoSdrInputSettings()->getFileRecordName()) {
         *response.getPlutoSdrInputSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getPlutoSdrInputSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getPlutoSdrInputSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getPlutoSdrInputSettings()->getReverseApiAddress()) {
         *response.getPlutoSdrInputSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getPlutoSdrInputSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getPlutoSdrInputSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getPlutoSdrInputSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int PlutoSDRInput::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 894 of file plutosdrinput.cpp.
References SWGSDRangel::SWGDeviceReport::getPlutoSdrInputReport(), SWGSDRangel::SWGPlutoSdrInputReport::init(), SWGSDRangel::SWGDeviceReport::setPlutoSdrInputReport(), and webapiFormatDeviceReport().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setPlutoSdrInputReport(new SWGSDRangel::SWGPlutoSdrInputReport());
     response.getPlutoSdrInputReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void PlutoSDRInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const PlutoSDRInputSettings & settings, bool force) private
Definition at line 959 of file plutosdrinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getPlutoSdrInputSettings(), PlutoSDRInputSettings::m_antennaPath, PlutoSDRInputSettings::m_centerFrequency, PlutoSDRInputSettings::m_dcBlock, m_deviceAPI, PlutoSDRInputSettings::m_devSampleRate, PlutoSDRInputSettings::m_fcPos, PlutoSDRInputSettings::m_fileRecordName, PlutoSDRInputSettings::m_gain, PlutoSDRInputSettings::m_gainMode, PlutoSDRInputSettings::m_hwBBDCBlock, PlutoSDRInputSettings::m_hwIQCorrection, PlutoSDRInputSettings::m_hwRFDCBlock, PlutoSDRInputSettings::m_iqCorrection, PlutoSDRInputSettings::m_log2Decim, PlutoSDRInputSettings::m_LOppmTenths, PlutoSDRInputSettings::m_lpfBW, PlutoSDRInputSettings::m_lpfFIRBW, PlutoSDRInputSettings::m_lpfFIREnable, PlutoSDRInputSettings::m_lpfFIRGain, PlutoSDRInputSettings::m_lpfFIRlog2Decim, m_networkManager, m_networkRequest, PlutoSDRInputSettings::m_reverseAPIAddress, PlutoSDRInputSettings::m_reverseAPIDeviceIndex, PlutoSDRInputSettings::m_reverseAPIPort, PlutoSDRInputSettings::m_transverterDeltaFrequency, PlutoSDRInputSettings::m_transverterMode, SWGSDRangel::SWGPlutoSdrInputSettings::setAntennaPath(), SWGSDRangel::SWGPlutoSdrInputSettings::setCenterFrequency(), SWGSDRangel::SWGPlutoSdrInputSettings::setDcBlock(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGPlutoSdrInputSettings::setDevSampleRate(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGPlutoSdrInputSettings::setFcPos(), SWGSDRangel::SWGPlutoSdrInputSettings::setFileRecordName(), SWGSDRangel::SWGPlutoSdrInputSettings::setGain(), SWGSDRangel::SWGPlutoSdrInputSettings::setGainMode(), SWGSDRangel::SWGPlutoSdrInputSettings::setHwBbdcBlock(), SWGSDRangel::SWGPlutoSdrInputSettings::setHwIqCorrection(), SWGSDRangel::SWGPlutoSdrInputSettings::setHwRfdcBlock(), SWGSDRangel::SWGPlutoSdrInputSettings::setIqCorrection(), SWGSDRangel::SWGPlutoSdrInputSettings::setLog2Decim(), SWGSDRangel::SWGPlutoSdrInputSettings::setLOppmTenths(), SWGSDRangel::SWGPlutoSdrInputSettings::setLpfBw(), SWGSDRangel::SWGPlutoSdrInputSettings::setLpfFirbw(), SWGSDRangel::SWGPlutoSdrInputSettings::setLpfFirEnable(), SWGSDRangel::SWGPlutoSdrInputSettings::setLpfFirGain(), SWGSDRangel::SWGPlutoSdrInputSettings::setLpfFiRlog2Decim(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGDeviceSettings::setPlutoSdrInputSettings(), SWGSDRangel::SWGPlutoSdrInputSettings::setTransverterDeltaFrequency(), and SWGSDRangel::SWGPlutoSdrInputSettings::setTransverterMode().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("PlutoSDR"));
     swgDeviceSettings->setPlutoSdrInputSettings(new SWGSDRangel::SWGPlutoSdrInputSettings());
     SWGSDRangel::SWGPlutoSdrInputSettings *swgPlutoSdrInputSettings = swgDeviceSettings->getPlutoSdrInputSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgPlutoSdrInputSettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("devSampleRate") || force) {
         swgPlutoSdrInputSettings->setDevSampleRate(settings.m_devSampleRate);
     }
     if (deviceSettingsKeys.contains("LOppmTenths") || force) {
         swgPlutoSdrInputSettings->setLOppmTenths(settings.m_LOppmTenths);
     }
     if (deviceSettingsKeys.contains("lpfFIREnable") || force) {
         swgPlutoSdrInputSettings->setLpfFirEnable(settings.m_lpfFIREnable ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("lpfFIRBW") || force) {
         swgPlutoSdrInputSettings->setLpfFirbw(settings.m_lpfFIRBW);
     }
     if (deviceSettingsKeys.contains("lpfFIRlog2Decim") || force) {
         swgPlutoSdrInputSettings->setLpfFiRlog2Decim(settings.m_lpfFIRlog2Decim);
     }
     if (deviceSettingsKeys.contains("lpfFIRGain") || force) {
         swgPlutoSdrInputSettings->setLpfFirGain(settings.m_lpfFIRGain);
     }
     if (deviceSettingsKeys.contains("fcPos") || force) {
         swgPlutoSdrInputSettings->setFcPos((int) settings.m_fcPos);
     }
     if (deviceSettingsKeys.contains("dcBlock") || force) {
         swgPlutoSdrInputSettings->setDcBlock(settings.m_dcBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("iqCorrection") || force) {
         swgPlutoSdrInputSettings->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("hwBBDCBlock") || force) {
         swgPlutoSdrInputSettings->setHwBbdcBlock(settings.m_hwBBDCBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("hwRFDCBlock") || force) {
         swgPlutoSdrInputSettings->setHwRfdcBlock(settings.m_hwRFDCBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("hwIQCorrection") || force) {
         swgPlutoSdrInputSettings->setHwIqCorrection(settings.m_hwIQCorrection ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("log2Decim") || force) {
         swgPlutoSdrInputSettings->setLog2Decim(settings.m_log2Decim);
     }
     if (deviceSettingsKeys.contains("lpfBW") || force) {
         swgPlutoSdrInputSettings->setLpfBw(settings.m_lpfBW);
     }
     if (deviceSettingsKeys.contains("gain") || force) {
         swgPlutoSdrInputSettings->setGain(settings.m_gain);
     }
     if (deviceSettingsKeys.contains("antennaPath") || force) {
         swgPlutoSdrInputSettings->setAntennaPath((int) settings.m_antennaPath);
     }
     if (deviceSettingsKeys.contains("gainMode") || force) {
         swgPlutoSdrInputSettings->setGainMode((int) settings.m_gainMode);
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency") || force) {
         swgPlutoSdrInputSettings->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     }
     if (deviceSettingsKeys.contains("transverterMode") || force) {
         swgPlutoSdrInputSettings->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgPlutoSdrInputSettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void PlutoSDRInput::webapiReverseSendStartStop (bool start) private
Definition at line 1052 of file plutosdrinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, PlutoSDRInputSettings::m_reverseAPIAddress, PlutoSDRInputSettings::m_reverseAPIDeviceIndex, PlutoSDRInputSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("PlutoSDR"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int PlutoSDRInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 760 of file plutosdrinput.cpp.
References PlutoSDRInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int PlutoSDRInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 751 of file plutosdrinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int PlutoSDRInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 779 of file plutosdrinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getPlutoSdrInputSettings(), SWGSDRangel::SWGPlutoSdrInputSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setPlutoSdrInputSettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setPlutoSdrInputSettings(new SWGSDRangel::SWGPlutoSdrInputSettings());
     response.getPlutoSdrInputSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int PlutoSDRInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 790 of file plutosdrinput.cpp.
References PlutoSDRInput::MsgConfigurePlutoSDR::create(), PlutoSDRInputSettings::GAIN_END, SWGSDRangel::SWGPlutoSdrInputSettings::getAntennaPath(), SWGSDRangel::SWGPlutoSdrInputSettings::getCenterFrequency(), SWGSDRangel::SWGPlutoSdrInputSettings::getDcBlock(), SWGSDRangel::SWGPlutoSdrInputSettings::getDevSampleRate(), SWGSDRangel::SWGPlutoSdrInputSettings::getFcPos(), SWGSDRangel::SWGPlutoSdrInputSettings::getFileRecordName(), SWGSDRangel::SWGPlutoSdrInputSettings::getGain(), SWGSDRangel::SWGPlutoSdrInputSettings::getGainMode(), SWGSDRangel::SWGPlutoSdrInputSettings::getHwBbdcBlock(), SWGSDRangel::SWGPlutoSdrInputSettings::getHwIqCorrection(), SWGSDRangel::SWGPlutoSdrInputSettings::getHwRfdcBlock(), SWGSDRangel::SWGPlutoSdrInputSettings::getIqCorrection(), SWGSDRangel::SWGPlutoSdrInputSettings::getLog2Decim(), SWGSDRangel::SWGPlutoSdrInputSettings::getLOppmTenths(), SWGSDRangel::SWGPlutoSdrInputSettings::getLpfBw(), SWGSDRangel::SWGPlutoSdrInputSettings::getLpfFirbw(), SWGSDRangel::SWGPlutoSdrInputSettings::getLpfFirEnable(), SWGSDRangel::SWGPlutoSdrInputSettings::getLpfFirGain(), SWGSDRangel::SWGPlutoSdrInputSettings::getLpfFiRlog2Decim(), SWGSDRangel::SWGDeviceSettings::getPlutoSdrInputSettings(), SWGSDRangel::SWGPlutoSdrInputSettings::getReverseApiAddress(), SWGSDRangel::SWGPlutoSdrInputSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGPlutoSdrInputSettings::getReverseApiPort(), SWGSDRangel::SWGPlutoSdrInputSettings::getTransverterDeltaFrequency(), SWGSDRangel::SWGPlutoSdrInputSettings::getTransverterMode(), SWGSDRangel::SWGPlutoSdrInputSettings::getUseReverseApi(), PlutoSDRInputSettings::m_antennaPath, PlutoSDRInputSettings::m_centerFrequency, PlutoSDRInputSettings::m_dcBlock, PlutoSDRInputSettings::m_devSampleRate, PlutoSDRInputSettings::m_fcPos, PlutoSDRInputSettings::m_fileRecordName, PlutoSDRInputSettings::m_gain, PlutoSDRInputSettings::m_gainMode, DeviceSampleSource::m_guiMessageQueue, PlutoSDRInputSettings::m_hwBBDCBlock, DeviceSampleSource::m_inputMessageQueue, PlutoSDRInputSettings::m_iqCorrection, PlutoSDRInputSettings::m_log2Decim, PlutoSDRInputSettings::m_LOppmTenths, PlutoSDRInputSettings::m_lpfBW, PlutoSDRInputSettings::m_lpfFIRBW, PlutoSDRInputSettings::m_lpfFIREnable, PlutoSDRInputSettings::m_lpfFIRGain, PlutoSDRInputSettings::m_lpfFIRlog2Decim, PlutoSDRInputSettings::m_reverseAPIAddress, PlutoSDRInputSettings::m_reverseAPIDeviceIndex, PlutoSDRInputSettings::m_reverseAPIPort, m_settings, PlutoSDRInputSettings::m_transverterDeltaFrequency, PlutoSDRInputSettings::m_transverterMode, PlutoSDRInputSettings::m_useReverseAPI, MessageQueue::push(), PlutoSDRInputSettings::RFPATH_END, and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     PlutoSDRInputSettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getPlutoSdrInputSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("devSampleRate")) {
         settings.m_devSampleRate = response.getPlutoSdrInputSettings()->getDevSampleRate();
     }
     if (deviceSettingsKeys.contains("LOppmTenths")) {
         settings.m_LOppmTenths = response.getPlutoSdrInputSettings()->getLOppmTenths();
     }
     if (deviceSettingsKeys.contains("lpfFIREnable")) {
         settings.m_lpfFIREnable = response.getPlutoSdrInputSettings()->getLpfFirEnable() != 0;
     }
     if (deviceSettingsKeys.contains("lpfFIRBW")) {
         settings.m_lpfFIRBW = response.getPlutoSdrInputSettings()->getLpfFirbw();
     }
     if (deviceSettingsKeys.contains("lpfFIRlog2Decim")) {
         settings.m_lpfFIRlog2Decim = response.getPlutoSdrInputSettings()->getLpfFiRlog2Decim();
     }
     if (deviceSettingsKeys.contains("lpfFIRGain")) {
         settings.m_lpfFIRGain = response.getPlutoSdrInputSettings()->getLpfFirGain();
     }
     if (deviceSettingsKeys.contains("fcPos")) {
         int fcPos = response.getPlutoSdrInputSettings()->getFcPos();
         fcPos = fcPos < 0 ? 0 : fcPos > 2 ? 2 : fcPos;
         settings.m_fcPos = (PlutoSDRInputSettings::fcPos_t) fcPos;
     }
     if (deviceSettingsKeys.contains("dcBlock")) {
         settings.m_dcBlock = response.getPlutoSdrInputSettings()->getDcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("iqCorrection")) {
         settings.m_iqCorrection = response.getPlutoSdrInputSettings()->getIqCorrection() != 0;
     }
     if (deviceSettingsKeys.contains("hwBBDCBlock")) {
         settings.m_hwBBDCBlock = response.getPlutoSdrInputSettings()->getHwBbdcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("hwRFDCBlock")) {
         settings.m_hwBBDCBlock = response.getPlutoSdrInputSettings()->getHwRfdcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("hwIQCorrection")) {
         settings.m_hwBBDCBlock = response.getPlutoSdrInputSettings()->getHwIqCorrection() != 0;
     }
     if (deviceSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getPlutoSdrInputSettings()->getLog2Decim();
     }
     if (deviceSettingsKeys.contains("lpfBW")) {
         settings.m_lpfBW = response.getPlutoSdrInputSettings()->getLpfBw();
     }
     if (deviceSettingsKeys.contains("gain")) {
         settings.m_gain = response.getPlutoSdrInputSettings()->getGain();
     }
     if (deviceSettingsKeys.contains("antennaPath")) {
         int antennaPath = response.getPlutoSdrInputSettings()->getAntennaPath();
         antennaPath = antennaPath < 0 ? 0 : antennaPath >= PlutoSDRInputSettings::RFPATH_END ? PlutoSDRInputSettings::RFPATH_END-1 : antennaPath;
         settings.m_antennaPath = (PlutoSDRInputSettings::RFPath) antennaPath;
     }
     if (deviceSettingsKeys.contains("gainMode")) {
         int gainMode = response.getPlutoSdrInputSettings()->getGainMode();
         gainMode = gainMode < 0 ? 0 : gainMode >= PlutoSDRInputSettings::GAIN_END ? PlutoSDRInputSettings::GAIN_END-1 : gainMode;
         settings.m_gainMode = (PlutoSDRInputSettings::GainMode) gainMode;
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency")) {
         settings.m_transverterDeltaFrequency = response.getPlutoSdrInputSettings()->getTransverterDeltaFrequency();
     }
     if (deviceSettingsKeys.contains("transverterMode")) {
         settings.m_transverterMode = response.getPlutoSdrInputSettings()->getTransverterMode() != 0;
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getPlutoSdrInputSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getPlutoSdrInputSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getPlutoSdrInputSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getPlutoSdrInputSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getPlutoSdrInputSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigurePlutoSDR *msg = MsgConfigurePlutoSDR::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigurePlutoSDR *msgToGUI = MsgConfigurePlutoSDR::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_deviceAPI
DeviceAPI* PlutoSDRInput::m_deviceAPI private
Definition at line 155 of file plutosdrinput.h.
Referenced by applySettings(), closeDevice(), handleMessage(), openDevice(), resumeBuddies(), suspendBuddies(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~PlutoSDRInput().
m_deviceDescription
QString PlutoSDRInput::m_deviceDescription private
Definition at line 157 of file plutosdrinput.h.
Referenced by getDeviceDescription().
m_deviceSampleRates
DevicePlutoSDRBox::SampleRates PlutoSDRInput::m_deviceSampleRates private
Definition at line 163 of file plutosdrinput.h.
Referenced by applySettings(), getADCSampleRate(), and getFIRSampleRate().
m_deviceShared
DevicePlutoSDRShared PlutoSDRInput::m_deviceShared private
Definition at line 160 of file plutosdrinput.h.
Referenced by applySettings(), closeDevice(), fetchTemperature(), getbbLPRange(), getGain(), getLORange(), getRSSI(), getTemperature(), openDevice(), start(), and stop().
m_fileSink
FileRecord* PlutoSDRInput::m_fileSink private
Definition at line 156 of file plutosdrinput.h.
Referenced by applySettings(), handleMessage(), and ~PlutoSDRInput().
m_mutex
QMutex PlutoSDRInput::m_mutex private
Definition at line 164 of file plutosdrinput.h.
m_networkManager
QNetworkAccessManager* PlutoSDRInput::m_networkManager private
Definition at line 165 of file plutosdrinput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~PlutoSDRInput().
m_networkRequest
QNetworkRequest PlutoSDRInput::m_networkRequest private
Definition at line 166 of file plutosdrinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_plutoRxBuffer
struct iio_buffer* PlutoSDRInput::m_plutoRxBuffer private
Definition at line 161 of file plutosdrinput.h.
Referenced by openDevice().
m_plutoSDRInputThread
PlutoSDRInputThread* PlutoSDRInput::m_plutoSDRInputThread private
Definition at line 162 of file plutosdrinput.h.
Referenced by applySettings(), start(), and stop().
m_running
bool PlutoSDRInput::m_running private
Definition at line 159 of file plutosdrinput.h.
Referenced by start(), and stop().
m_settings
PlutoSDRInputSettings PlutoSDRInput::m_settings private
Definition at line 158 of file plutosdrinput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), serialize(), setCenterFrequency(), start(), webapiFormatDeviceSettings(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
The documentation for this class was generated from the following files:
plugins/samplesource/plutosdrinput/plutosdrinput.h
plugins/samplesource/plutosdrinput/plutosdrinput.cpp