SDRAngel: CWKeyer::MsgConfigureCWKeyer Class Reference
CWKeyer::MsgConfigureCWKeyer Class Reference
#include <cwkeyer.h>
Public Member Functions
const CWKeyerSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureCWKeyer * create (const CWKeyerSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureCWKeyer (const CWKeyerSettings &settings, bool force)
Private Attributes
CWKeyerSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 56 of file cwkeyer.h.
Constructor & Destructor Documentation
MsgConfigureCWKeyer()
CWKeyer::MsgConfigureCWKeyer::MsgConfigureCWKeyer (const CWKeyerSettings & settings, bool force) inline private
Definition at line 72 of file cwkeyer.h.
                                                                          :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureCWKeyer* CWKeyer::MsgConfigureCWKeyer::create (const CWKeyerSettings & settings, bool force) inline static
Definition at line 63 of file cwkeyer.h.
Referenced by CWKeyerGUI::applySettings(), CWKeyer::setSampleRate(), AMMod::webapiSettingsPutPatch(), WFMMod::webapiSettingsPutPatch(), NFMMod::webapiSettingsPutPatch(), SSBMod::webapiSettingsPutPatch(), and FreeDVMod::webapiSettingsPutPatch().
         {
             return new MsgConfigureCWKeyer(settings, force);
         }
getForce()
bool CWKeyer::MsgConfigureCWKeyer::getForce () const inline
Definition at line 61 of file cwkeyer.h.
Referenced by CWKeyer::handleMessage().
 { return m_force; }
getSettings()
const CWKeyerSettings& CWKeyer::MsgConfigureCWKeyer::getSettings () const inline
Definition at line 60 of file cwkeyer.h.
Referenced by NFMModGUI::handleMessage(), WFMModGUI::handleMessage(), AMModGUI::handleMessage(), SSBModGUI::handleMessage(), FreeDVModGUI::handleMessage(), CWKeyer::handleMessage(), AMMod::handleMessage(), WFMMod::handleMessage(), NFMMod::handleMessage(), SSBMod::handleMessage(), and FreeDVMod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool CWKeyer::MsgConfigureCWKeyer::m_force private
Definition at line 70 of file cwkeyer.h.
m_settings
CWKeyerSettings CWKeyer::MsgConfigureCWKeyer::m_settings private
Definition at line 69 of file cwkeyer.h.
The documentation for this class was generated from the following file:
sdrbase/dsp/cwkeyer.h