SDRAngel: leansdr::trellis< TS, NSTATES, TUS, NUS, NCS > Struct Template Reference
leansdr::trellis< TS, NSTATES, TUS, NUS, NCS > Struct Template Reference
#include <viterbi.h>
Classes
struct state
Public Member Functions
trellis ()
void init_convolutional (const uint16_t G[])
void dump ()
Public Attributes
struct leansdr::trellis::state states [NSTATES]
Static Public Attributes
static const int NOSTATE = NSTATES + 1
Detailed Description
template<typename TS, int NSTATES, typename TUS, int NUS, int NCS>
struct leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >
Definition at line 44 of file viterbi.h.
Constructor & Destructor Documentation
trellis()
template<typename TS, int NSTATES, typename TUS, int NUS, int NCS> leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::trellis () inline
Definition at line 57 of file viterbi.h.
References leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::state::branches, leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::state::branch::pred, and leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::states.
     {
         for (TS s = 0; s < NSTATES; ++s)
             for (int cs = 0; cs < NCS; ++cs)
                 states[s].branches[cs].pred = NOSTATE;
     }
Member Function Documentation
dump()
template<typename TS, int NSTATES, typename TUS, int NUS, int NCS> void leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::dump () inline
Definition at line 102 of file viterbi.h.
References leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::state::branches, leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::state::branch::pred, leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::states, and leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::state::branch::us.
     {
         for (int s = 0; s < NSTATES; ++s)
         {
             fprintf(stderr, "State %02x:", s);
             for (int cs = 0; cs < NCS; ++cs)
             {
                 typename state::branch *b = &states[s].branches[cs];
                 if (b->pred == NOSTATE)
                     fprintf(stderr, "     - ");
                 else
                     fprintf(stderr, "   %02x+%x", b->pred, b->us);
             }
             fprintf(stderr, "\n");
         }
     }
init_convolutional()
template<typename TS, int NSTATES, typename TUS, int NUS, int NCS> void leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::init_convolutional (const uint16_t G[]) inline
Definition at line 65 of file viterbi.h.
References leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::state::branches, leansdr::log2i(), leansdr::parity(), leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::state::branch::pred, leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::states, and leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::state::branch::us.
Referenced by leansdr::viterbi_sync::viterbi_sync().
     {
         if (NCS & (NCS - 1))
         {
             fprintf(stderr, "NCS must be a power of 2\n");
         }
         // Derive number of polynomials from NCS.
         int nG = log2i(NCS);
         for (TS s = 0; s < NSTATES; ++s)
         {
             for (TUS us = 0; us < NUS; ++us)
             {
                 // Run the convolutional encoder from state s with input us
                 uint64_t shiftreg = s; // TBD type
                 // Reverse bits
                 TUS us_rev = 0;
                 for (int b = 1; b < NUS; b *= 2)
                     if (us & b)
                         us_rev |= (NUS / 2 / b);
                 shiftreg |= us_rev * NSTATES;
                 uint32_t cs = 0; // TBD type
                 for (int g = 0; g < nG; ++g)
                     cs = (cs << 1) | parity(shiftreg & G[g]);
                 shiftreg /= NUS; // Shift bits for 1 uncoded symbol
                 // [us] at state [s] emits [cs] and leads to state [shiftreg].
                 typename state::branch *b = &states[shiftreg].branches[cs];
                 if (b->pred != NOSTATE)
                 {
                     fprintf(stderr, "Invalid convolutional code\n");
                 }
                 b->pred = s;
                 b->us = us;
             }
         }
     }
Member Data Documentation
NOSTATE
template<typename TS, int NSTATES, typename TUS, int NUS, int NCS> const int leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::NOSTATE = NSTATES + 1 static
Definition at line 46 of file viterbi.h.
Referenced by leansdr::viterbi_dec< TS, NSTATES, TUS, NUS, TCS, NCS, TBM, TPM, TP >::update().
states
template<typename TS, int NSTATES, typename TUS, int NUS, int NCS> struct leansdr::trellis::state leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::states[NSTATES]
Referenced by leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::dump(), leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::init_convolutional(), leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::trellis(), and leansdr::viterbi_dec< TS, NSTATES, TUS, NUS, TCS, NCS, TBM, TPM, TP >::update().
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/viterbi.h