SDRAngel: HackRFInput::MsgFileRecord Class Reference
HackRFInput::MsgFileRecord Class Reference
#include <hackrfinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgFileRecord * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgFileRecord (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 100 of file hackrfinput.h.
Constructor & Destructor Documentation
MsgFileRecord()
HackRFInput::MsgFileRecord::MsgFileRecord (bool startStop) inline protected
Definition at line 113 of file hackrfinput.h.
References HackRFInput::deserialize(), HackRFInput::destroy(), HackRFInput::HackRFInput(), HackRFInput::init(), HackRFInput::serialize(), HackRFInput::start(), HackRFInput::stop(), and HackRFInput::~HackRFInput().
                                       :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgFileRecord* HackRFInput::MsgFileRecord::create (bool startStop) inline static
Definition at line 106 of file hackrfinput.h.
Referenced by HackRFInputGui::on_record_toggled().
{
             return new MsgFileRecord(startStop);
         }
getStartStop()
bool HackRFInput::MsgFileRecord::getStartStop () const inline
Definition at line 104 of file hackrfinput.h.
Referenced by HackRFInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool HackRFInput::MsgFileRecord::m_startStop protected
Definition at line 111 of file hackrfinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/hackrfinput/hackrfinput.h