SDRAngel: DevicePlutoSDRShared::MsgCrossReportToBuddy Class Reference
DevicePlutoSDRShared::MsgCrossReportToBuddy Class Reference
#include <deviceplutosdrshared.h>
Public Member Functions
uint64_t getDevSampleRate () const
uint32_t getLpfFirbw () const
bool isLpfFirEnable () const
uint32_t getLpfFiRlog2IntDec () const
int32_t getLoPPMTenths () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgCrossReportToBuddy * create (uint64_t devSampleRate, bool lpfFIREnable, uint32_t lpfFIRlog2Interp, uint32_t lpfFIRBW, int32_t loPPMTenths)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgCrossReportToBuddy (uint64_t devSampleRate, bool lpfFIREnable, uint32_t lpfFIRlog2IntDec, uint32_t lpfFIRBW, int32_t loPPMTenths)
Private Attributes
uint64_t m_devSampleRate
bool m_lpfFIREnable
uint32_t m_lpfFIRlogIntDec
uint32_t m_lpfFIRBW
int32_t m_loPPMTenths
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 46 of file deviceplutosdrshared.h.
Constructor & Destructor Documentation
MsgCrossReportToBuddy()
DevicePlutoSDRShared::MsgCrossReportToBuddy::MsgCrossReportToBuddy (uint64_t devSampleRate, bool lpfFIREnable, uint32_t lpfFIRlog2IntDec, uint32_t lpfFIRBW, int32_t loPPMTenths) inline private
Definition at line 69 of file deviceplutosdrshared.h.
                                      :
             Message(),
             m_devSampleRate(devSampleRate),
             m_lpfFIREnable(lpfFIREnable),
             m_lpfFIRlogIntDec(lpfFIRlog2IntDec),
             m_lpfFIRBW(lpfFIRBW),
             m_loPPMTenths(loPPMTenths)
         { }
Member Function Documentation
create()
static MsgCrossReportToBuddy* DevicePlutoSDRShared::MsgCrossReportToBuddy::create (uint64_t devSampleRate, bool lpfFIREnable, uint32_t lpfFIRlog2Interp, uint32_t lpfFIRBW, int32_t loPPMTenths) inline static
Definition at line 55 of file deviceplutosdrshared.h.
Referenced by PlutoSDROutput::applySettings(), and PlutoSDRInput::applySettings().
         {
             return new MsgCrossReportToBuddy(devSampleRate,
                     lpfFIREnable,
                     lpfFIRlog2Interp,
                     lpfFIRBW,
                     loPPMTenths);
         }
getDevSampleRate()
uint64_t DevicePlutoSDRShared::MsgCrossReportToBuddy::getDevSampleRate () const inline
Definition at line 49 of file deviceplutosdrshared.h.
Referenced by PlutoSDROutputGUI::handleMessage(), PlutoSDRInputGui::handleMessage(), PlutoSDROutput::handleMessage(), and PlutoSDRInput::handleMessage().
 { return m_devSampleRate; }
getLoPPMTenths()
int32_t DevicePlutoSDRShared::MsgCrossReportToBuddy::getLoPPMTenths () const inline
Definition at line 53 of file deviceplutosdrshared.h.
Referenced by PlutoSDROutputGUI::handleMessage(), PlutoSDRInputGui::handleMessage(), PlutoSDROutput::handleMessage(), and PlutoSDRInput::handleMessage().
 { return m_loPPMTenths; }
getLpfFirbw()
uint32_t DevicePlutoSDRShared::MsgCrossReportToBuddy::getLpfFirbw () const inline
Definition at line 50 of file deviceplutosdrshared.h.
Referenced by PlutoSDROutputGUI::handleMessage(), PlutoSDRInputGui::handleMessage(), PlutoSDROutput::handleMessage(), and PlutoSDRInput::handleMessage().
 { return m_lpfFIRBW; }
getLpfFiRlog2IntDec()
uint32_t DevicePlutoSDRShared::MsgCrossReportToBuddy::getLpfFiRlog2IntDec () const inline
Definition at line 52 of file deviceplutosdrshared.h.
Referenced by PlutoSDROutputGUI::handleMessage(), PlutoSDRInputGui::handleMessage(), PlutoSDROutput::handleMessage(), and PlutoSDRInput::handleMessage().
 { return m_lpfFIRlogIntDec; }
isLpfFirEnable()
bool DevicePlutoSDRShared::MsgCrossReportToBuddy::isLpfFirEnable () const inline
Definition at line 51 of file deviceplutosdrshared.h.
Referenced by PlutoSDROutputGUI::handleMessage(), PlutoSDRInputGui::handleMessage(), PlutoSDROutput::handleMessage(), and PlutoSDRInput::handleMessage().
 { return m_lpfFIREnable; }
Member Data Documentation
m_devSampleRate
uint64_t DevicePlutoSDRShared::MsgCrossReportToBuddy::m_devSampleRate private
Definition at line 82 of file deviceplutosdrshared.h.
m_loPPMTenths
int32_t DevicePlutoSDRShared::MsgCrossReportToBuddy::m_loPPMTenths private
Definition at line 86 of file deviceplutosdrshared.h.
m_lpfFIRBW
uint32_t DevicePlutoSDRShared::MsgCrossReportToBuddy::m_lpfFIRBW private
Definition at line 85 of file deviceplutosdrshared.h.
m_lpfFIREnable
bool DevicePlutoSDRShared::MsgCrossReportToBuddy::m_lpfFIREnable private
Definition at line 83 of file deviceplutosdrshared.h.
m_lpfFIRlogIntDec
uint32_t DevicePlutoSDRShared::MsgCrossReportToBuddy::m_lpfFIRlogIntDec private
Definition at line 84 of file deviceplutosdrshared.h.
The documentation for this class was generated from the following file:
devices/plutosdr/deviceplutosdrshared.h