SDRAngel: AudioCompressor Class Reference
AudioCompressor Class Reference
#include <audiocompressor.h>
Public Member Functions
AudioCompressor ()
~AudioCompressor ()
void fillLUT ()
4 bands
void fillLUT2 ()
8 bands (default)
void fillALaw ()
A-law compression to 8 bits.
void fillULaw ()
u-law compression to 8 bits
int16_t compress (int16_t sample)
int8_t compress8 (int16_t sample)
Private Member Functions
int8_t ALaw_Encode (int16_t number)
int8_t MuLaw_Encode (int16_t number)
Private Attributes
int16_t m_lut [32768]
Static Private Attributes
static const uint16_t ALAW_MAX = 0xFFF
static const uint16_t MULAW_MAX = 0x1FFF
static const uint16_t MULAW_BIAS = 33
Detailed Description
Definition at line 25 of file audiocompressor.h.
Constructor & Destructor Documentation
AudioCompressor()
AudioCompressor::AudioCompressor ()
Definition at line 26 of file audiocompressor.cpp.
References fillLUT2().
 {
     fillLUT2();
 }
~AudioCompressor()
AudioCompressor::~AudioCompressor ()
Definition at line 31 of file audiocompressor.cpp.
 {}
Member Function Documentation
ALaw_Encode()
int8_t AudioCompressor::ALaw_Encode (int16_t number) private
Definition at line 139 of file audiocompressor.cpp.
References ALAW_MAX.
Referenced by fillALaw().
 {
     uint16_t mask = 0x800;
     uint8_t sign = 0;
     uint8_t position = 11;
     uint8_t lsb = 0;
     if (number < 0)
     {
        number = -number;
        sign = 0x80;
     }
     if (number > ALAW_MAX) {
        number = ALAW_MAX;
     }
     for (; ((number & mask) != mask && position >= 5); mask >>= 1, position--) {
     }
     lsb = (number >> ((position == 4) ? (1) : (position - 4))) & 0x0f;
     return (sign | ((position - 4) << 4) | lsb) ^ 0x55;
 }
compress()
int16_t AudioCompressor::compress (int16_t sample)
Definition at line 102 of file audiocompressor.cpp.
References abs(), and m_lut.
Referenced by AMBEWorker::upsample().
 {
     int16_t sign = sample < 0 ? -1 : 1;
     int16_t abs = sample < 0 ? -sample : sample;
     return sign * m_lut[abs];
 }
compress8()
int8_t AudioCompressor::compress8 (int16_t sample)
Definition at line 109 of file audiocompressor.cpp.
References m_lut.
Referenced by AudioNetSink::write().
 {
     return m_lut[sample/2 + 16384];
 }
fillALaw()
void AudioCompressor::fillALaw ()
A-law compression to 8 bits.
Definition at line 88 of file audiocompressor.cpp.
References ALaw_Encode(), i, and m_lut.
Referenced by AudioNetSink::setParameters().
 {
     for (int i=-16384; i<16384; i++) {
         m_lut[i+16384] = ALaw_Encode(2*i);
     }
 }
fillLUT()
void AudioCompressor::fillLUT ()
4 bands
Definition at line 34 of file audiocompressor.cpp.
References i, and m_lut.
 {
     for (int i=0; i<8192; i++) {
         m_lut[i] = (24576/8192)*i;
     }
     for (int i=8192; i<2*8192; i++) {
         m_lut[i] = 24576 + 0.5f*(i-8192);
     }
     for (int i=2*8192; i<3*8192; i++) {
         m_lut[i] = 24576 + 4096 + 0.25f*(i-2*8192);
     }
     for (int i=3*8192; i<4*8192; i++) {
         m_lut[i] = 24576 + 4096 + 2048 + 0.125f*(i-3*8192);
     }
 }
fillLUT2()
void AudioCompressor::fillLUT2 ()
8 bands (default)
Definition at line 53 of file audiocompressor.cpp.
References i, and m_lut.
Referenced by AudioCompressor().
 {
     for (int i=0; i<4096; i++) {
         m_lut[i] = (24576/4096)*i;
     }
     for (int i=4096; i<2*4096; i++) {
         m_lut[i] = 24576 + 0.5f*(i-4096);
     }
     for (int i=2*4096; i<3*4096; i++) {
         m_lut[i] = 24576 + 2048 + 0.25f*(i-2*4096);
     }
     for (int i=3*4096; i<4*4096; i++) {
         m_lut[i] = 24576 + 2048 + 1024 + 0.125f*(i-3*4096);
     }
     for (int i=4*4096; i<5*4096; i++) {
         m_lut[i] = 24576 + 2048 + 1024 + 512 + 0.0625f*(i-4*4096);
     }
     for (int i=5*4096; i<6*4096; i++) {
         m_lut[i] = 24576 + 2048 + 1024 + 512 + 256 + 0.03125f*(i-5*4096);
     }
     for (int i=6*4096; i<7*4096; i++) {
         m_lut[i] = 24576 + 2048 + 1024 + 512 + 256 + 128 + 0.015625f*(i-6*4096);
     }
     for (int i=7*4096; i<8*4096; i++) {
         m_lut[i] = 24576 + 2048 + 1024 + 512 + 256 + 128 + 64 + 0.0078125f*(i-7*4096);
     }
 }
fillULaw()
void AudioCompressor::fillULaw ()
u-law compression to 8 bits
Definition at line 95 of file audiocompressor.cpp.
References i, m_lut, and MuLaw_Encode().
Referenced by AudioNetSink::setParameters().
 {
     for (int i=-16384; i<16384; i++) {
         m_lut[i+16384] = MuLaw_Encode(2*i);
     }
 }
MuLaw_Encode()
int8_t AudioCompressor::MuLaw_Encode (int16_t number) private
Definition at line 175 of file audiocompressor.cpp.
References MULAW_BIAS, and MULAW_MAX.
Referenced by fillULaw().
 {
    uint16_t mask = 0x1000;
    uint8_t sign = 0;
    uint8_t position = 12;
    uint8_t lsb = 0;
    if (number < 0)
    {
       number = -number;
       sign = 0x80;
    }
    number += MULAW_BIAS;
    if (number > MULAW_MAX) {
       number = MULAW_MAX;
    }
    for (; ((number & mask) != mask && position >= 5); mask >>= 1, position--) {
    }
    lsb = (number >> (position - 4)) & 0x0f;
    return (~(sign | ((position - 5) << 4) | lsb));
 }
Member Data Documentation
ALAW_MAX
const uint16_t AudioCompressor::ALAW_MAX = 0xFFF static private
Definition at line 42 of file audiocompressor.h.
Referenced by ALaw_Encode().
m_lut
int16_t AudioCompressor::m_lut[32768] private
Definition at line 41 of file audiocompressor.h.
Referenced by compress(), compress8(), fillALaw(), fillLUT(), fillLUT2(), and fillULaw().
MULAW_BIAS
const uint16_t AudioCompressor::MULAW_BIAS = 33 static private
Definition at line 44 of file audiocompressor.h.
Referenced by MuLaw_Encode().
MULAW_MAX
const uint16_t AudioCompressor::MULAW_MAX = 0x1FFF static private
Definition at line 43 of file audiocompressor.h.
Referenced by MuLaw_Encode().
The documentation for this class was generated from the following files:
sdrbase/audio/audiocompressor.h
sdrbase/audio/audiocompressor.cpp