SDRAngel: FileSinkOutput::MsgReportFileSinkStreamTiming Class Reference
FileSinkOutput::MsgReportFileSinkStreamTiming Class Reference
#include <filesinkoutput.h>
Public Member Functions
std::size_t getSamplesCount () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportFileSinkStreamTiming * create (std::size_t samplesCount)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportFileSinkStreamTiming (std::size_t samplesCount)
Protected Attributes
std::size_t m_samplesCount
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 154 of file filesinkoutput.h.
Constructor & Destructor Documentation
MsgReportFileSinkStreamTiming()
FileSinkOutput::MsgReportFileSinkStreamTiming::MsgReportFileSinkStreamTiming (std::size_t samplesCount) inline protected
Definition at line 168 of file filesinkoutput.h.
References FileSinkOutput::deserialize(), FileSinkOutput::destroy(), FileSinkOutput::FileSinkOutput(), FileSinkOutput::init(), FileSinkOutput::serialize(), FileSinkOutput::start(), FileSinkOutput::stop(), and FileSinkOutput::~FileSinkOutput().
                                                               :
             Message(),
             m_samplesCount(samplesCount)
         { }
Member Function Documentation
create()
static MsgReportFileSinkStreamTiming* FileSinkOutput::MsgReportFileSinkStreamTiming::create (std::size_t samplesCount) inline static
Definition at line 160 of file filesinkoutput.h.
Referenced by FileSinkOutput::handleMessage().
         {
             return new MsgReportFileSinkStreamTiming(samplesCount);
         }
getSamplesCount()
std::size_t FileSinkOutput::MsgReportFileSinkStreamTiming::getSamplesCount () const inline
Definition at line 158 of file filesinkoutput.h.
 { return m_samplesCount; }
Member Data Documentation
m_samplesCount
std::size_t FileSinkOutput::MsgReportFileSinkStreamTiming::m_samplesCount protected
Definition at line 166 of file filesinkoutput.h.
The documentation for this class was generated from the following file:
plugins/samplesink/filesink/filesinkoutput.h