SDRAngel: HackRFBandwidths Class Reference
HackRFBandwidths Class Reference
#include <devicehackrfvalues.h>
Static Public Member Functions
static unsigned int getBandwidth (unsigned int bandwidth_index)
static unsigned int getBandwidthIndex (unsigned int bandwidth)
Static Public Attributes
static const unsigned int m_nb_bw = 16
static const unsigned int m_bw_k []
Detailed Description
Definition at line 23 of file devicehackrfvalues.h.
Member Function Documentation
getBandwidth()
unsigned int HackRFBandwidths::getBandwidth (unsigned int bandwidth_index) static
Definition at line 39 of file devicehackrfvalues.cpp.
References m_bw_k, and m_nb_bw.
Referenced by HackRFOutputGui::on_bbFilter_currentIndexChanged(), and HackRFInputGui::on_bbFilter_currentIndexChanged().
 {
     if (bandwidth_index < m_nb_bw)
     {
         return m_bw_k[bandwidth_index];
     }
     else
     {
         return m_bw_k[0];
     }
 }
getBandwidthIndex()
unsigned int HackRFBandwidths::getBandwidthIndex (unsigned int bandwidth) static
Definition at line 51 of file devicehackrfvalues.cpp.
References i, m_bw_k, and m_nb_bw.
Referenced by HackRFInputGui::displayBandwidths(), HackRFOutputGui::displayBandwidths(), HackRFInputGui::displaySettings(), and HackRFOutputGui::displaySettings().
 {
     for (unsigned int i=0; i < m_nb_bw; i++)
     {
         if (bandwidth == m_bw_k[i])
         {
             return i;
         }
     }
     return 0;
 }
Member Data Documentation
m_bw_k
const unsigned int HackRFBandwidths::m_bw_k static
Initial value:
= {
        1750,
        2500,
        3500,
        5000,
        5500,
        6000,
        7000,
        8000,
        9000,
       10000,
       12000,
       14000,
       15000,
       20000,
       24000,
       28000}
Definition at line 28 of file devicehackrfvalues.h.
Referenced by HackRFInputGui::displayBandwidths(), HackRFOutputGui::displayBandwidths(), getBandwidth(), and getBandwidthIndex().
m_nb_bw
const unsigned int HackRFBandwidths::m_nb_bw = 16 static
Definition at line 27 of file devicehackrfvalues.h.
Referenced by HackRFInputGui::displayBandwidths(), HackRFOutputGui::displayBandwidths(), getBandwidth(), and getBandwidthIndex().
The documentation for this class was generated from the following files:
devices/hackrf/devicehackrfvalues.h
devices/hackrf/devicehackrfvalues.cpp