SDRAngel: LocalSourceThread::MsgStartStop Class Reference
LocalSourceThread::MsgStartStop Class Reference
#include <localsourcethread.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 35 of file localsourcethread.h.
Constructor & Destructor Documentation
MsgStartStop()
LocalSourceThread::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 48 of file localsourcethread.h.
References LocalSourceThread::LocalSourceThread(), LocalSourceThread::pullSamples(), LocalSourceThread::samplesAvailable(), LocalSourceThread::setSampleFifo(), LocalSourceThread::startStop(), and LocalSourceThread::~LocalSourceThread().
Referenced by create().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* LocalSourceThread::MsgStartStop::create (bool startStop) inline static
Definition at line 41 of file localsourcethread.h.
References MsgStartStop().
Referenced by LocalSourceThread::startStop().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool LocalSourceThread::MsgStartStop::getStartStop () const inline
Definition at line 39 of file localsourcethread.h.
References m_startStop.
Referenced by LocalSourceThread::handleInputMessages().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool LocalSourceThread::MsgStartStop::m_startStop protected
Definition at line 46 of file localsourcethread.h.
Referenced by getStartStop().
The documentation for this class was generated from the following file:
plugins/channeltx/localsource/localsourcethread.h