SDRAngel: UDPSource::MsgConfigureChannelizer Class Reference
UDPSource::MsgConfigureChannelizer Class Reference
#include <udpsource.h>
Public Member Functions
int getSampleRate () const
int getCenterFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (int sampleRate, int centerFrequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (int sampleRate, int centerFrequency)
Private Attributes
int m_sampleRate
int m_centerFrequency
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 70 of file udpsource.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
UDPSource::MsgConfigureChannelizer::MsgConfigureChannelizer (int sampleRate, int centerFrequency) inline private
Definition at line 86 of file udpsource.h.
References UDPSource::UDPSource(), and UDPSource::~UDPSource().
                                                                      :
             Message(),
             m_sampleRate(sampleRate),
             m_centerFrequency(centerFrequency)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* UDPSource::MsgConfigureChannelizer::create (int sampleRate, int centerFrequency) inline static
Definition at line 77 of file udpsource.h.
Referenced by UDPSourceGUI::applySettings(), and UDPSource::webapiSettingsPutPatch().
         {
             return new MsgConfigureChannelizer(sampleRate, centerFrequency);
         }
getCenterFrequency()
int UDPSource::MsgConfigureChannelizer::getCenterFrequency () const inline
Definition at line 75 of file udpsource.h.
Referenced by UDPSource::handleMessage().
 { return m_centerFrequency; }
getSampleRate()
int UDPSource::MsgConfigureChannelizer::getSampleRate () const inline
Definition at line 74 of file udpsource.h.
Referenced by UDPSource::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_centerFrequency
int UDPSource::MsgConfigureChannelizer::m_centerFrequency private
Definition at line 84 of file udpsource.h.
m_sampleRate
int UDPSource::MsgConfigureChannelizer::m_sampleRate private
Definition at line 83 of file udpsource.h.
The documentation for this class was generated from the following file:
plugins/channeltx/udpsource/udpsource.h