SDRAngel: DevicePlutoSDRBox Class Reference
DevicePlutoSDRBox Class Reference
#include <deviceplutosdrbox.h>
Classes
struct Sample
struct SampleRates
Public Types
enum DeviceType { DEVICE_PHY, DEVICE_RX, DEVICE_TX }
enum DeviceUse { USE_RX, USE_TX }
Public Member Functions
DevicePlutoSDRBox (const std::string &uri)
~DevicePlutoSDRBox ()
bool isValid () const
void set_params (DeviceType devType, const std::vector< std::string > &params)
bool get_param (DeviceType devType, const std::string &param, std::string &value)
bool openRx ()
bool openTx ()
void closeRx ()
void closeTx ()
struct iio_buffer * createRxBuffer (unsigned int size, bool cyclic)
struct iio_buffer * createTxBuffer (unsigned int size, bool cyclic)
void deleteRxBuffer ()
void deleteTxBuffer ()
ssize_t getRxSampleSize ()
ssize_t getTxSampleSize ()
struct iio_channel * getRxChannel0 ()
struct iio_channel * getTxChannel0I ()
struct iio_channel * getTxChannel0Q ()
ssize_t rxBufferRefill ()
ssize_t txBufferPush ()
std::ptrdiff_t rxBufferStep ()
char * rxBufferEnd ()
char * rxBufferFirst ()
std::ptrdiff_t txBufferStep ()
char * txBufferEnd ()
char * txBufferFirst ()
void txChannelConvert (int16_t *dst, int16_t *src)
bool getRxSampleRates (SampleRates &sampleRates)
bool getTxSampleRates (SampleRates &sampleRates)
void setSampleRate (uint32_t sampleRate)
void setFIR (uint32_t sampleRate, uint32_t intdec, DeviceUse use, uint32_t bw, int gain)
void setFIREnable (bool enable)
void setLOPPMTenths (int ppmTenths)
bool getRxGain (int &gaindB, unsigned int chan)
bool getRxRSSI (std::string &rssiStr, unsigned int chan)
bool getTxRSSI (std::string &rssiStr, unsigned int chan)
void getRxLORange (uint64_t &minLimit, uint64_t &maxLimit)
void getTxLORange (uint64_t &minLimit, uint64_t &maxLimit)
void getbbLPRxRange (uint32_t &minLimit, uint32_t &maxLimit)
void getbbLPTxRange (uint32_t &minLimit, uint32_t &maxLimit)
bool fetchTemp ()
float getTemp () const
bool getRateGovernors (std::string &rateGovernors)
Static Public Member Functions
static bool probeURI (const std::string &uri)
Public Attributes
uint64_t m_devSampleRate
Host interface sample rate.
int32_t m_LOppmTenths
XO correction.
bool m_lpfFIREnable
enable digital lowpass FIR filter
float m_lpfFIRBW
digital lowpass FIR filter bandwidth (Hz)
uint32_t m_lpfFIRlog2Decim
digital lowpass FIR filter log2 of decimation factor (0..2)
int m_lpfFIRRxGain
digital lowpass FIR filter gain Rx side (dB)
int m_lpfFIRTxGain
digital lowpass FIR filter gain Tx side (dB)
Private Member Functions
bool parseSampleRates (const std::string &rateStr, SampleRates &sampleRates)
void setFilter (const std::string &filterConfigStr)
void formatFIRHeader (std::ostringstream &str, uint32_t intdec)
void formatFIRCoefficients (std::ostringstream &str, uint32_t nbTaps, double normalizedBW)
void getXO ()
Private Attributes
struct iio_context * m_ctx
struct iio_device * m_devPhy
struct iio_device * m_devRx
struct iio_device * m_devTx
struct iio_channel * m_chnRx0
struct iio_channel * m_chnTx0i
struct iio_channel * m_chnTx0q
struct iio_buffer * m_rxBuf
struct iio_buffer * m_txBuf
bool m_valid
int64_t m_xoInitial
float m_temp
Detailed Description
Definition at line 33 of file deviceplutosdrbox.h.
Member Enumeration Documentation
DeviceType
enum DevicePlutoSDRBox::DeviceType
Enumerator
DEVICE_PHY
DEVICE_RX
DEVICE_TX
Definition at line 36 of file deviceplutosdrbox.h.
     {
         DEVICE_PHY,
         DEVICE_RX,
         DEVICE_TX
     } DeviceType;
DeviceUse
enum DevicePlutoSDRBox::DeviceUse
Enumerator
USE_RX
USE_TX
Definition at line 43 of file deviceplutosdrbox.h.
     {
         USE_RX,
         USE_TX
     } DeviceUse;
Constructor & Destructor Documentation
DevicePlutoSDRBox()
DevicePlutoSDRBox::DevicePlutoSDRBox (const std::string & uri)
Definition at line 31 of file deviceplutosdrbox.cpp.
References getXO(), m_ctx, m_devPhy, m_devRx, m_devTx, and m_valid.
                                                          :
         m_devSampleRate(0),
         m_LOppmTenths(0),
         m_lpfFIREnable(false),
         m_lpfFIRBW(100.0f),
         m_lpfFIRlog2Decim(0),
         m_lpfFIRRxGain(0),
         m_lpfFIRTxGain(0),
         m_ctx(0),
         m_devPhy(0),
         m_devRx(0),
         m_devTx(0),
         m_chnRx0(0),
         m_chnTx0i(0),
         m_chnTx0q(0),
         m_rxBuf(0),
         m_txBuf(0),
         m_xoInitial(0),
         m_temp(0.0f)
 {
     m_ctx = iio_create_context_from_uri(uri.c_str());
     if (m_ctx)
     {
         m_devPhy = iio_context_find_device(m_ctx, "ad9361-phy");
         m_devRx = iio_context_find_device(m_ctx, "cf-ad9361-lpc");
         m_devTx = iio_context_find_device(m_ctx, "cf-ad9361-dds-core-lpc");
     }
     m_valid = m_ctx && m_devPhy && m_devRx && m_devTx;
     if (m_valid) {
         getXO();
 //        int nb_channels = iio_device_get_channels_count(m_devRx);
 //        for (int i = 0; i < nb_channels; i++) {
 //            iio_channel_disable(iio_device_get_channel(m_devRx, i));
 //        }
 //        nb_channels = iio_device_get_channels_count(m_devTx);
 //        for (int i = 0; i < nb_channels; i++) {
 //            iio_channel_disable(iio_device_get_channel(m_devTx, i));
 //        }
     }
 }
~DevicePlutoSDRBox()
DevicePlutoSDRBox::~DevicePlutoSDRBox ()
Definition at line 75 of file deviceplutosdrbox.cpp.
References closeRx(), closeTx(), deleteRxBuffer(), deleteTxBuffer(), and m_ctx.
 {
     deleteRxBuffer();
     deleteTxBuffer();
     closeRx();
     closeTx();
     if (m_ctx) { iio_context_destroy(m_ctx); }
 }
Member Function Documentation
closeRx()
void DevicePlutoSDRBox::closeRx ()
Definition at line 328 of file deviceplutosdrbox.cpp.
References m_chnRx0.
Referenced by ~DevicePlutoSDRBox().
 {
     if (m_chnRx0) { iio_channel_disable(m_chnRx0); }
 }
closeTx()
void DevicePlutoSDRBox::closeTx ()
Definition at line 333 of file deviceplutosdrbox.cpp.
References m_chnTx0i, and m_chnTx0q.
Referenced by ~DevicePlutoSDRBox().
 {
     if (m_chnTx0i) { iio_channel_disable(m_chnTx0i); }
     if (m_chnTx0q) { iio_channel_disable(m_chnTx0q); }
 }
createRxBuffer()
struct iio_buffer * DevicePlutoSDRBox::createRxBuffer (unsigned int size, bool cyclic)
Definition at line 339 of file deviceplutosdrbox.cpp.
References m_devRx, and m_rxBuf.
Referenced by PlutoSDRInput::openDevice().
 {
     if (m_devRx) {
         m_rxBuf = iio_device_create_buffer(m_devRx, size, cyclic ? '\1' : '\0');
     } else {
         m_rxBuf = 0;
     }
     return m_rxBuf;
 }
createTxBuffer()
struct iio_buffer * DevicePlutoSDRBox::createTxBuffer (unsigned int size, bool cyclic)
Definition at line 350 of file deviceplutosdrbox.cpp.
References m_devTx, and m_txBuf.
Referenced by PlutoSDROutput::openDevice().
 {
     if (m_devTx) {
         m_txBuf =  iio_device_create_buffer(m_devTx, size, cyclic ? '\1' : '\0');
     } else {
         m_txBuf = 0;
     }
     return m_txBuf;
 }
deleteRxBuffer()
void DevicePlutoSDRBox::deleteRxBuffer ()
Definition at line 361 of file deviceplutosdrbox.cpp.
References m_rxBuf.
Referenced by ~DevicePlutoSDRBox().
 {
     if (m_rxBuf) {
         iio_buffer_destroy(m_rxBuf);
         m_rxBuf = 0;
     }
 }
deleteTxBuffer()
void DevicePlutoSDRBox::deleteTxBuffer ()
Definition at line 369 of file deviceplutosdrbox.cpp.
References m_txBuf.
Referenced by ~DevicePlutoSDRBox().
 {
     if (m_txBuf) {
         iio_buffer_destroy(m_txBuf);
         m_txBuf = 0;
     }
 }
fetchTemp()
bool DevicePlutoSDRBox::fetchTemp ()
Definition at line 801 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, get_param(), and m_temp.
Referenced by PlutoSDROutput::fetchTemperature(), and PlutoSDRInput::fetchTemperature().
 {
     std::string temp_mC_str;
     if (get_param(DEVICE_PHY, "in_temp0_input", temp_mC_str))
     {
         try
         {
             uint32_t temp_mC = boost::lexical_cast<uint32_t>(temp_mC_str);
             m_temp = temp_mC / 1000.0;
             return true;
         }
         catch (const boost::bad_lexical_cast &e)
         {
             std::cerr << "PlutoSDRDevice::getTemp: bad conversion to numeric" << std::endl;
             return false;
         }
     }
     else
     {
         return false;
     }
 }
formatFIRCoefficients()
void DevicePlutoSDRBox::formatFIRCoefficients (std::ostringstream & str, uint32_t nbTaps, double normalizedBW) private
Definition at line 642 of file deviceplutosdrbox.cpp.
References WFIR::BasicFIR(), i, WFIR::LPF, WFIR::wtBLACKMAN_HARRIS, and WFIR::wtHAMMING.
Referenced by setFIR().
 {
     double *fcoeffs = new double[nbTaps];
     WFIR::BasicFIR(fcoeffs, nbTaps, WFIR::LPF, normalizedBW, 0.0, normalizedBW < 0.2 ? WFIR::wtHAMMING : WFIR::wtBLACKMAN_HARRIS, 0.0);
     for (unsigned int i = 0; i < nbTaps; i++) {
         ostr << (int16_t) (fcoeffs[i] * 32768.0f) << ", " <<  (int16_t) (fcoeffs[i] * 32768.0f) << std::endl;
     }
     delete[] fcoeffs;
 }
formatFIRHeader()
void DevicePlutoSDRBox::formatFIRHeader (std::ostringstream & str, uint32_t intdec) private
Definition at line 636 of file deviceplutosdrbox.cpp.
References m_lpfFIRRxGain, and m_lpfFIRTxGain.
Referenced by setFIR().
 {
     ostr << "RX 3 GAIN " << m_lpfFIRRxGain << " DEC " << intdec << std::endl;
     ostr << "TX 3 GAIN " << m_lpfFIRTxGain << " INT " << intdec << std::endl;
 }
get_param()
bool DevicePlutoSDRBox::get_param (DeviceType devType, const std::string & param, std::string & value)
Definition at line 188 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, DEVICE_RX, DEVICE_TX, m_devPhy, m_devRx, and m_devTx.
Referenced by fetchTemp(), getbbLPRxRange(), getbbLPTxRange(), getRateGovernors(), getRxGain(), getRxLORange(), getRxRSSI(), getRxSampleRates(), getTxLORange(), getTxRSSI(), getTxSampleRates(), and getXO().
 {
     struct iio_channel *chn = 0;
     const char *attr = 0;
     char valuestr[256];
     int ret;
     ssize_t nchars;
     iio_device *dev;
     switch (devType)
     {
     case DEVICE_PHY:
         dev = m_devPhy;
         break;
     case DEVICE_RX:
         dev = m_devRx;
         break;
     case DEVICE_TX:
         dev = m_devTx;
         break;
     default:
         dev = m_devPhy;
         break;
     }
     ret = iio_device_identify_filename(dev, param.c_str(), &chn, &attr);
     if (ret)
     {
         std::cerr << "DevicePlutoSDRBox::get_param: Parameter not recognized: " << param << std::endl;
         return false;
     }
     if (chn) {
         nchars = iio_channel_attr_read(chn, attr, valuestr, 256);
     } else if (iio_device_find_attr(dev, attr)) {
         nchars = iio_device_attr_read(dev, attr, valuestr, 256);
     } else {
         nchars = iio_device_debug_attr_read(dev, attr, valuestr, 256);
     }
     if (nchars < 0)
     {
         std::cerr << "DevicePlutoSDRBox::get_param: Unable to read attribute " << param <<  ": " << nchars << std::endl;
         return false;
     }
     else
     {
         value.assign(valuestr);
         return true;
     }
 }
getbbLPRxRange()
void DevicePlutoSDRBox::getbbLPRxRange (uint32_t & minLimit, uint32_t & maxLimit)
Definition at line 758 of file deviceplutosdrbox.cpp.
References DevicePlutoSDR::bbLPRxHighLimitFreq, DevicePlutoSDR::bbLPRxLowLimitFreq, DEVICE_PHY, and get_param().
Referenced by PlutoSDRInput::getbbLPRange().
 {
     // values are returned in Hz of RF (complex channel) bandwidth
     qint32 stepLimit;
     std::string rangeStr;
     char buff[50];
     snprintf(buff, sizeof(buff), "in_voltage_rf_bandwidth_available");
     if (get_param(DEVICE_PHY, buff, rangeStr))
     {
     std::istringstream instream(rangeStr.substr(1, rangeStr.size() - 2));
     instream >> minLimit >> stepLimit >> maxLimit;
     }
     else
     {
     minLimit = DevicePlutoSDR::bbLPRxLowLimitFreq;
     maxLimit = DevicePlutoSDR::bbLPRxHighLimitFreq;
     }
 }
getbbLPTxRange()
void DevicePlutoSDRBox::getbbLPTxRange (uint32_t & minLimit, uint32_t & maxLimit)
Definition at line 779 of file deviceplutosdrbox.cpp.
References DevicePlutoSDR::bbLPTxHighLimitFreq, DevicePlutoSDR::bbLPTxLowLimitFreq, DEVICE_PHY, and get_param().
Referenced by PlutoSDROutput::getbbLPRange().
 {
     // values are returned in Hz
     qint32 stepLimit;
     std::string rangeStr;
     char buff[50];
     snprintf(buff, sizeof(buff), "out_voltage_rf_bandwidth_available");
     if (get_param(DEVICE_PHY, buff, rangeStr))
     {
         std::istringstream instream(rangeStr.substr(1, rangeStr.size() - 2));
         instream >> minLimit >> stepLimit >> maxLimit;
     }
     else
     {
     minLimit = DevicePlutoSDR::bbLPTxLowLimitFreq;
     maxLimit = DevicePlutoSDR::bbLPTxHighLimitFreq;
     }
 }
getRateGovernors()
bool DevicePlutoSDRBox::getRateGovernors (std::string & rateGovernors)
Definition at line 825 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, and get_param().
 {
     return get_param(DEVICE_PHY, "trx_rate_governor", rateGovernors);
 }
getRxChannel0()
struct iio_channel* DevicePlutoSDRBox::getRxChannel0 () inline
Definition at line 88 of file deviceplutosdrbox.h.
 { return m_chnRx0; }
getRxGain()
bool DevicePlutoSDRBox::getRxGain (int & gaindB, unsigned int chan)
Definition at line 669 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, and get_param().
Referenced by PlutoSDRInput::getGain().
 {
     chan = chan % 2;
     char buff[30];
     snprintf(buff, sizeof(buff), "in_voltage%d_hardwaregain", chan);
     std::string gainStr;
     get_param(DEVICE_PHY, buff, gainStr);
     std::regex gain_regex("(.+)\\.(.+) dB");
     std::smatch gain_match;
     std::regex_search(gainStr, gain_match, gain_regex);
     if (gain_match.size() == 3)
     {
         try
         {
             gaindB = boost::lexical_cast<int>(gain_match[1]);
             return true;
         }
         catch (const boost::bad_lexical_cast &e)
         {
             qWarning("DevicePlutoSDRBox::getRxGain: bad conversion to numeric");
             return false;
         }
     }
     else
     {
         return false;
     }
 }
getRxLORange()
void DevicePlutoSDRBox::getRxLORange (uint64_t & minLimit, uint64_t & maxLimit)
Definition at line 716 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, get_param(), DevicePlutoSDR::rxLOHighLimitFreq, and DevicePlutoSDR::rxLOLowLimitFreq.
Referenced by PlutoSDRInput::getLORange().
 {
     // values are returned in Hz
     qint64 stepLimit;
     std::string rangeStr;
     char buff[50];
     snprintf(buff, sizeof(buff), "out_altvoltage0_RX_LO_frequency_available");
     if (get_param(DEVICE_PHY, buff, rangeStr))
     {
         std::istringstream instream(rangeStr.substr(1, rangeStr.size() - 2));
         instream >> minLimit >> stepLimit >> maxLimit;
     }
     else
     {
         minLimit = DevicePlutoSDR::rxLOLowLimitFreq;
         maxLimit = DevicePlutoSDR::rxLOHighLimitFreq;
     }
 }
getRxRSSI()
bool DevicePlutoSDRBox::getRxRSSI (std::string & rssiStr, unsigned int chan)
Definition at line 700 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, and get_param().
Referenced by PlutoSDRInput::getRSSI().
 {
     chan = chan % 2;
     char buff[20];
     snprintf(buff, sizeof(buff), "in_voltage%d_rssi", chan);
     return get_param(DEVICE_PHY, buff, rssiStr);
 }
getRxSampleRates()
bool DevicePlutoSDRBox::getRxSampleRates (SampleRates & sampleRates)
Definition at line 477 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, get_param(), and parseSampleRates().
Referenced by PlutoSDRInput::applySettings(), and setFIR().
 {
     std::string srStr;
     if (get_param(DEVICE_PHY, "rx_path_rates", srStr)) {
         qDebug("DevicePlutoSDRBox::getRxSampleRates: %s", srStr.c_str());
         return parseSampleRates(srStr, sampleRates);
     } else {
         return false;
     }
 }
getRxSampleSize()
ssize_t DevicePlutoSDRBox::getRxSampleSize ()
Definition at line 377 of file deviceplutosdrbox.cpp.
References m_devRx.
Referenced by PlutoSDROutputThread::run(), and PlutoSDRInputThread::run().
 {
     if (m_devRx) {
         return iio_device_get_sample_size(m_devRx);
     } else {
         return 0;
     }
 }
getTemp()
float DevicePlutoSDRBox::getTemp () const inline
Definition at line 114 of file deviceplutosdrbox.h.
Referenced by PlutoSDROutput::getTemperature(), and PlutoSDRInput::getTemperature().
 { return m_temp; }
getTxChannel0I()
struct iio_channel* DevicePlutoSDRBox::getTxChannel0I () inline
Definition at line 89 of file deviceplutosdrbox.h.
 { return m_chnTx0i; }
getTxChannel0Q()
struct iio_channel* DevicePlutoSDRBox::getTxChannel0Q () inline
Definition at line 90 of file deviceplutosdrbox.h.
 { return m_chnTx0q; }
getTxLORange()
void DevicePlutoSDRBox::getTxLORange (uint64_t & minLimit, uint64_t & maxLimit)
Definition at line 737 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, get_param(), DevicePlutoSDR::txLOHighLimitFreq, and DevicePlutoSDR::txLOLowLimitFreq.
Referenced by PlutoSDROutput::getLORange().
 {
     // values are returned in Hz
     qint64 stepLimit;
     std::string rangeStr;
     char buff[50];
     snprintf(buff, sizeof(buff), "out_altvoltage1_TX_LO_frequency_available");
     if (get_param(DEVICE_PHY, buff, rangeStr))
     {
         std::istringstream instream(rangeStr.substr(1, rangeStr.size() - 2));
         instream >> minLimit >> stepLimit >> maxLimit;
     }
     else
     {
         minLimit = DevicePlutoSDR::txLOLowLimitFreq;
         maxLimit = DevicePlutoSDR::txLOHighLimitFreq;
     }
 }
getTxRSSI()
bool DevicePlutoSDRBox::getTxRSSI (std::string & rssiStr, unsigned int chan)
Definition at line 708 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, and get_param().
Referenced by PlutoSDROutput::getRSSI().
 {
     chan = chan % 2;
     char buff[20];
     snprintf(buff, sizeof(buff), "out_voltage%d_rssi", chan);
     return get_param(DEVICE_PHY, buff, rssiStr);
 }
getTxSampleRates()
bool DevicePlutoSDRBox::getTxSampleRates (SampleRates & sampleRates)
Definition at line 489 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, get_param(), and parseSampleRates().
Referenced by PlutoSDROutput::applySettings().
 {
     std::string srStr;
     if (get_param(DEVICE_PHY, "tx_path_rates", srStr)) {
         return parseSampleRates(srStr, sampleRates);
     } else {
         return false;
     }
 }
getTxSampleSize()
ssize_t DevicePlutoSDRBox::getTxSampleSize ()
Definition at line 386 of file deviceplutosdrbox.cpp.
References m_devTx.
Referenced by PlutoSDROutputThread::run(), and PlutoSDRInputThread::run().
 {
     if (m_devTx) {
         return iio_device_get_sample_size(m_devTx);
     } else {
         return 0;
     }
 }
getXO()
void DevicePlutoSDRBox::getXO () private
Definition at line 654 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, get_param(), and m_xoInitial.
Referenced by DevicePlutoSDRBox().
 {
     std::string valueStr;
     get_param(DEVICE_PHY, "xo_correction", valueStr);
     try
     {
         m_xoInitial = boost::lexical_cast<quint64>(valueStr);
         qDebug("DevicePlutoSDRBox::getXO: %ld", m_xoInitial);
     }
     catch (const boost::bad_lexical_cast &e)
     {
         qWarning("DevicePlutoSDRBox::getXO: cannot get initial XO correction");
     }
 }
isValid()
bool DevicePlutoSDRBox::isValid () const inline
Definition at line 73 of file deviceplutosdrbox.h.
 { return m_valid; }
openRx()
bool DevicePlutoSDRBox::openRx ()
Definition at line 253 of file deviceplutosdrbox.cpp.
References m_chnRx0, m_devRx, and m_valid.
Referenced by PlutoSDRInput::openDevice().
 {
     if (!m_valid) { return false; }
     if (!m_chnRx0) {
         m_chnRx0 = iio_device_find_channel(m_devRx, "voltage0", false);
     }
     if (m_chnRx0) {
         iio_channel_enable(m_chnRx0);
         const struct iio_data_format *df = iio_channel_get_data_format(m_chnRx0);
         qDebug("DevicePlutoSDRBox::openRx: length: %u bits: %u shift: %u signed: %s be: %s with_scale: %s scale: %lf repeat: %u",
                 df->length,
                 df->bits,
                 df->shift,
                 df->is_signed ? "true" : "false",
                 df->is_be ? "true" : "false",
                 df->with_scale? "true" : "false",
                 df->scale,
                 df->repeat);
         return true;
     } else {
         std::cerr << "DevicePlutoSDRBox::openRx: failed" << std::endl;
         return false;
     }
 }
openTx()
bool DevicePlutoSDRBox::openTx ()
Definition at line 280 of file deviceplutosdrbox.cpp.
References m_chnTx0i, m_chnTx0q, m_devTx, and m_valid.
Referenced by PlutoSDROutput::openDevice().
 {
     if (!m_valid) { return false; }
     if (!m_chnTx0i) {
         m_chnTx0i = iio_device_find_channel(m_devTx, "voltage0", true);
     }
     if (m_chnTx0i) {
         iio_channel_enable(m_chnTx0i);
         const struct iio_data_format *df = iio_channel_get_data_format(m_chnTx0i);
         qDebug("DevicePlutoSDRBox::openTx: channel I: length: %u bits: %u shift: %u signed: %s be: %s with_scale: %s scale: %lf repeat: %u",
                 df->length,
                 df->bits,
                 df->shift,
                 df->is_signed ? "true" : "false",
                 df->is_be ? "true" : "false",
                 df->with_scale? "true" : "false",
                 df->scale,
                 df->repeat);
     } else {
         std::cerr << "DevicePlutoSDRBox::openTx: failed to open I channel" << std::endl;
         return false;
     }
     if (!m_chnTx0q) {
         m_chnTx0q = iio_device_find_channel(m_devTx, "voltage1", true);
     }
     if (m_chnTx0q) {
         iio_channel_enable(m_chnTx0q);
         const struct iio_data_format *df = iio_channel_get_data_format(m_chnTx0q);
         qDebug("DevicePlutoSDRBox::openTx: channel Q: length: %u bits: %u shift: %u signed: %s be: %s with_scale: %s scale: %lf repeat: %u",
                 df->length,
                 df->bits,
                 df->shift,
                 df->is_signed ? "true" : "false",
                 df->is_be ? "true" : "false",
                 df->with_scale? "true" : "false",
                 df->scale,
                 df->repeat);
         return true;
     } else {
         std::cerr << "DevicePlutoSDRBox::openTx: failed to open Q channel" << std::endl;
         return false;
     }
 }
parseSampleRates()
bool DevicePlutoSDRBox::parseSampleRates (const std::string & rateStr, SampleRates & sampleRates) private
Definition at line 500 of file deviceplutosdrbox.cpp.
References DevicePlutoSDRBox::SampleRates::m_addaConnvRate, DevicePlutoSDRBox::SampleRates::m_bbRateHz, DevicePlutoSDRBox::SampleRates::m_firRate, DevicePlutoSDRBox::SampleRates::m_hb1Rate, DevicePlutoSDRBox::SampleRates::m_hb2Rate, and DevicePlutoSDRBox::SampleRates::m_hb3Rate.
Referenced by getRxSampleRates(), and getTxSampleRates().
 {
     // Rx: "BBPLL:983040000 ADC:245760000 R2:122880000 R1:61440000 RF:30720000 RXSAMP:30720000"
     // Tx: "BBPLL:983040000 DAC:122880000 T2:122880000 T1:61440000 TF:30720000 TXSAMP:30720000"
     std::regex desc_regex("BBPLL:(.+) ..C:(.+) .2:(.+) .1:(.+) .F:(.+) .XSAMP:(.+)");
     std::smatch desc_match;
     std::regex_search(rateStr, desc_match, desc_regex);
     std::string valueStr;
     if (desc_match.size() == 7)
     {
         try
         {
             sampleRates.m_bbRateHz = boost::lexical_cast<uint32_t>(desc_match[1]);
             sampleRates.m_addaConnvRate = boost::lexical_cast<uint32_t>(desc_match[2]);
             sampleRates.m_hb3Rate = boost::lexical_cast<uint32_t>(desc_match[3]);
             sampleRates.m_hb2Rate = boost::lexical_cast<uint32_t>(desc_match[4]);
             sampleRates.m_hb1Rate = boost::lexical_cast<uint32_t>(desc_match[5]);
             sampleRates.m_firRate = boost::lexical_cast<uint32_t>(desc_match[6]);
             return true;
         }
         catch (const boost::bad_lexical_cast &e)
         {
             qWarning("DevicePlutoSDRBox::parseSampleRates: bad conversion to numeric");
             return false;
         }
     }
     else
     {
         return false;
     }
 }
probeURI()
bool DevicePlutoSDRBox::probeURI (const std::string & uri) static
Definition at line 84 of file deviceplutosdrbox.cpp.
Referenced by DevicePlutoSDRScan::scan().
 {
     bool retVal;
     struct iio_context *ctx;
     ctx = iio_create_context_from_uri(uri.c_str());
     retVal = (ctx != 0);
     if (ctx) {
         iio_context_destroy(ctx);
     }
     return retVal;
 }
rxBufferEnd()
char * DevicePlutoSDRBox::rxBufferEnd ()
Definition at line 422 of file deviceplutosdrbox.cpp.
References m_rxBuf.
Referenced by PlutoSDRInputThread::run().
 {
     if (m_rxBuf) {
         return (char *) iio_buffer_end(m_rxBuf);
     } else {
         return 0;
     }
 }
rxBufferFirst()
char * DevicePlutoSDRBox::rxBufferFirst ()
Definition at line 431 of file deviceplutosdrbox.cpp.
References m_chnRx0, and m_rxBuf.
Referenced by PlutoSDRInputThread::run().
 {
     if (m_rxBuf) {
         return (char *) iio_buffer_first(m_rxBuf, m_chnRx0);
     } else {
         return 0;
     }
 }
rxBufferRefill()
ssize_t DevicePlutoSDRBox::rxBufferRefill ()
Definition at line 395 of file deviceplutosdrbox.cpp.
References m_rxBuf.
Referenced by PlutoSDRInputThread::run().
 {
     if (m_rxBuf) {
         return iio_buffer_refill(m_rxBuf);
     } else {
         return 0;
     }
 }
rxBufferStep()
std::ptrdiff_t DevicePlutoSDRBox::rxBufferStep ()
Definition at line 413 of file deviceplutosdrbox.cpp.
References m_rxBuf.
Referenced by PlutoSDRInputThread::run().
 {
     if (m_rxBuf) {
         return iio_buffer_step(m_rxBuf);
     } else {
         return 0;
     }
 }
set_params()
void DevicePlutoSDRBox::set_params (DeviceType devType, const std::vector< std::string > & params)
Definition at line 99 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, DEVICE_RX, DEVICE_TX, m_devPhy, m_devRx, and m_devTx.
Referenced by PlutoSDROutput::applySettings(), PlutoSDRInput::applySettings(), setFIREnable(), setLOPPMTenths(), and setSampleRate().
 {
     iio_device *dev;
     switch (devType)
     {
     case DEVICE_PHY:
         dev = m_devPhy;
         break;
     case DEVICE_RX:
         dev = m_devRx;
         break;
     case DEVICE_TX:
         dev = m_devTx;
         break;
     default:
         dev = m_devPhy;
         break;
     }
     for (std::vector<std::string>::const_iterator it = params.begin(); it != params.end(); ++it)
     {
         struct iio_channel *chn = 0;
         const char *attr = 0;
         std::size_t pos;
         int ret;
         int type;
         pos = it->find('=');
         if (pos == std::string::npos)
         {
             std::cerr << "DevicePlutoSDRBox::set_params: Misformed line: " << *it << std::endl;
             continue;
         }
         std::string key = it->substr(0, pos);
         std::string val = it->substr(pos + 1, std::string::npos);
         ret = iio_device_identify_filename(dev, key.c_str(), &chn, &attr);
         if (ret)
         {
             std::cerr << "DevicePlutoSDRBox::set_params: Parameter not recognized: " << key << std::endl;
             continue;
         }
         if (chn) {
             ret = iio_channel_attr_write(chn, attr, val.c_str());
             type = 0;
         } else if (iio_device_find_attr(dev, attr)) {
             ret = iio_device_attr_write(dev, attr, val.c_str());
             type = 1;
         } else {
             ret = iio_device_debug_attr_write(dev, attr, val.c_str());
             type = 2;
         }
         if (ret < 0)
         {
             std::string item;
            char errstr[256];
             switch (type)
             {
             case 0:
                 item = "channel";
                 break;
             case 1:
                 item = "device";
                 break;
             case 2:
                 item = "debug";
                 break;
             default:
                 item = "unknown";
                 break;
             }
             iio_strerror(-ret, errstr, 255);
             std::cerr << "DevicePlutoSDRBox::set_params: Unable to write " << item << " attribute " << key << "=" << val << ": " << errstr << " (" << ret << ") " << std::endl;
         }
         else
         {
             std::cerr << "DevicePlutoSDRBox::set_params: set attribute " << key << "=" << val << ": " << ret << std::endl;
         }
     }
 }
setFilter()
void DevicePlutoSDRBox::setFilter (const std::string & filterConfigStr) private
Definition at line 241 of file deviceplutosdrbox.cpp.
References m_devPhy.
Referenced by setFIR().
 {
     int ret;
     ret = iio_device_attr_write_raw(m_devPhy, "filter_fir_config", filterConfigStr.c_str(), filterConfigStr.size());
     if (ret < 0)
     {
         std::cerr << "DevicePlutoSDRBox::set_filter: Unable to set: " <<  filterConfigStr <<  ": " << ret << std::endl;
     }
 }
setFIR()
void DevicePlutoSDRBox::setFIR (uint32_t sampleRate, uint32_t log2IntDec, DeviceUse use, uint32_t bw, int gain)
Parameters
sampleRate baseband sample rate (S/s)
log2IntDec FIR interpolation or decimation factor
use Rx or Tx. Applies to the rest of the parameters
bw FIR filter bandwidth at approximately -6 dB cutoff (Hz)
gain FIR filter gain (dB)
Definition at line 552 of file deviceplutosdrbox.cpp.
References DevicePlutoSDR::firBWHighLimitFactor, DevicePlutoSDR::firBWLowLimitFactor, formatFIRCoefficients(), formatFIRHeader(), getRxSampleRates(), DevicePlutoSDRBox::SampleRates::m_addaConnvRate, DevicePlutoSDRBox::SampleRates::m_hb1Rate, m_lpfFIRBW, m_lpfFIRlog2Decim, m_lpfFIRRxGain, m_lpfFIRTxGain, setFilter(), setFIREnable(), setSampleRate(), and USE_RX.
Referenced by PlutoSDROutput::applySettings(), and PlutoSDRInput::applySettings().
 {
     SampleRates sampleRates;
     std::ostringstream ostr;
     uint32_t nbTaps;
     double normalizedBW;
     uint32_t intdec = 1<<(log2IntDec > 2 ? 2 : log2IntDec);
     // update gain parameter
     if (use == USE_RX) {
         m_lpfFIRRxGain = gain;
     } else {
         m_lpfFIRTxGain = gain;
     }
     // set a dummy minimal filter first to get the sample rates right
     setFIREnable(false); // disable first
     formatFIRHeader(ostr, intdec);
     formatFIRCoefficients(ostr, 16, 0.5);
     setFilter(ostr.str());
     ostr.str(""); // reset string stream
     setFIREnable(true);        // re-enable
     setSampleRate(sampleRate); // set to new sample rate
     if (!getRxSampleRates(sampleRates)) {
         return;
     }
     setFIREnable(false); // disable again
     uint32_t nbGroups = sampleRates.m_addaConnvRate / 16;
     nbTaps = nbGroups*8 > 128 ? 128 : nbGroups*8;
     nbTaps = intdec == 1 ? (nbTaps > 64 ? 64 : nbTaps) : nbTaps;
     normalizedBW = ((float) bw) / sampleRates.m_hb1Rate;
     normalizedBW = normalizedBW < DevicePlutoSDR::firBWLowLimitFactor ?
             DevicePlutoSDR::firBWLowLimitFactor :
             normalizedBW > DevicePlutoSDR::firBWHighLimitFactor ? DevicePlutoSDR::firBWHighLimitFactor : normalizedBW;
     qDebug("DevicePlutoSDRBox::setFIR: intdec: %u gain: %d nbTaps: %u BWin: %u BW: %f (%f)",
             intdec,
             gain,
             nbTaps,
             bw,
             normalizedBW*sampleRates.m_hb1Rate,
             normalizedBW);
     // set the right filter
     formatFIRHeader(ostr, intdec);
     formatFIRCoefficients(ostr, nbTaps, normalizedBW);
     setFilter(ostr.str());
     m_lpfFIRlog2Decim = log2IntDec;
     m_lpfFIRBW = bw;
     // enable and set sample rate will be done by the caller
 }
setFIREnable()
void DevicePlutoSDRBox::setFIREnable (bool enable)
Definition at line 615 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, m_lpfFIREnable, and set_params().
Referenced by PlutoSDROutput::applySettings(), PlutoSDRInput::applySettings(), and setFIR().
 {
     char buff[100];
     std::vector<std::string> params;
     snprintf(buff, sizeof(buff), "in_out_voltage_filter_fir_en=%d", enable ? 1 : 0);
     params.push_back(std::string(buff));
     set_params(DEVICE_PHY, params);
     m_lpfFIREnable = enable;
 }
setLOPPMTenths()
void DevicePlutoSDRBox::setLOPPMTenths (int ppmTenths)
Definition at line 625 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, m_LOppmTenths, m_xoInitial, and set_params().
Referenced by PlutoSDROutput::applySettings(), and PlutoSDRInput::applySettings().
 {
     char buff[100];
     std::vector<std::string> params;
     int64_t newXO = m_xoInitial + ((m_xoInitial*ppmTenths) / 10000000L);
     snprintf(buff, sizeof(buff), "xo_correction=%ld", (long int) newXO);
     params.push_back(std::string(buff));
     set_params(DEVICE_PHY, params);
     m_LOppmTenths = ppmTenths;
 }
setSampleRate()
void DevicePlutoSDRBox::setSampleRate (uint32_t sampleRate)
Definition at line 533 of file deviceplutosdrbox.cpp.
References DEVICE_PHY, m_devSampleRate, and set_params().
Referenced by PlutoSDROutput::applySettings(), PlutoSDRInput::applySettings(), and setFIR().
 {
     char buff[100];
     std::vector<std::string> params;
     snprintf(buff, sizeof(buff), "in_voltage_sampling_frequency=%d", sampleRate);
     params.push_back(std::string(buff));
     snprintf(buff, sizeof(buff), "out_voltage_sampling_frequency=%d", sampleRate);
     params.push_back(std::string(buff));
     set_params(DEVICE_PHY, params);
     m_devSampleRate = sampleRate;
 }
txBufferEnd()
char * DevicePlutoSDRBox::txBufferEnd ()
Definition at line 449 of file deviceplutosdrbox.cpp.
References m_txBuf.
Referenced by PlutoSDROutputThread::run().
 {
     if (m_txBuf) {
         return (char *) iio_buffer_end(m_txBuf);
     } else {
         return 0;
     }
 }
txBufferFirst()
char * DevicePlutoSDRBox::txBufferFirst ()
Definition at line 458 of file deviceplutosdrbox.cpp.
References m_chnTx0i, and m_txBuf.
Referenced by PlutoSDROutputThread::run().
 {
     if (m_txBuf) {
         return (char *) iio_buffer_first(m_txBuf, m_chnTx0i);
     } else {
         return 0;
     }
 }
txBufferPush()
ssize_t DevicePlutoSDRBox::txBufferPush ()
Definition at line 404 of file deviceplutosdrbox.cpp.
References m_txBuf.
Referenced by PlutoSDROutputThread::run().
 {
     if (m_txBuf) {
         return iio_buffer_push(m_txBuf);
     } else {
         return 0;
     }
 }
txBufferStep()
std::ptrdiff_t DevicePlutoSDRBox::txBufferStep ()
Definition at line 440 of file deviceplutosdrbox.cpp.
References m_txBuf.
Referenced by PlutoSDROutputThread::run().
 {
     if (m_txBuf) {
         return iio_buffer_step(m_txBuf);
     } else {
         return 0;
     }
 }
txChannelConvert()
void DevicePlutoSDRBox::txChannelConvert (int16_t * dst, int16_t * src)
Definition at line 467 of file deviceplutosdrbox.cpp.
References m_chnTx0i, and m_chnTx0q.
Referenced by PlutoSDROutputThread::run().
 {
     if (m_chnTx0i) {
         iio_channel_convert_inverse(m_chnTx0i, &dst[0], &src[0]);
     }
     if (m_chnTx0q) {
         iio_channel_convert_inverse(m_chnTx0q, &dst[1], &src[1]);
     }
 }
Member Data Documentation
m_chnRx0
struct iio_channel* DevicePlutoSDRBox::m_chnRx0 private
Definition at line 122 of file deviceplutosdrbox.h.
Referenced by closeRx(), openRx(), and rxBufferFirst().
m_chnTx0i
struct iio_channel* DevicePlutoSDRBox::m_chnTx0i private
Definition at line 123 of file deviceplutosdrbox.h.
Referenced by closeTx(), openTx(), txBufferFirst(), and txChannelConvert().
m_chnTx0q
struct iio_channel* DevicePlutoSDRBox::m_chnTx0q private
Definition at line 124 of file deviceplutosdrbox.h.
Referenced by closeTx(), openTx(), and txChannelConvert().
m_ctx
struct iio_context* DevicePlutoSDRBox::m_ctx private
Definition at line 118 of file deviceplutosdrbox.h.
Referenced by DevicePlutoSDRBox(), and ~DevicePlutoSDRBox().
m_devPhy
struct iio_device* DevicePlutoSDRBox::m_devPhy private
Definition at line 119 of file deviceplutosdrbox.h.
Referenced by DevicePlutoSDRBox(), get_param(), set_params(), and setFilter().
m_devRx
struct iio_device* DevicePlutoSDRBox::m_devRx private
Definition at line 120 of file deviceplutosdrbox.h.
Referenced by createRxBuffer(), DevicePlutoSDRBox(), get_param(), getRxSampleSize(), openRx(), and set_params().
m_devSampleRate
uint64_t DevicePlutoSDRBox::m_devSampleRate
Host interface sample rate.
Definition at line 63 of file deviceplutosdrbox.h.
Referenced by setSampleRate().
m_devTx
struct iio_device* DevicePlutoSDRBox::m_devTx private
Definition at line 121 of file deviceplutosdrbox.h.
Referenced by createTxBuffer(), DevicePlutoSDRBox(), get_param(), getTxSampleSize(), openTx(), and set_params().
m_LOppmTenths
int32_t DevicePlutoSDRBox::m_LOppmTenths
XO correction.
Definition at line 64 of file deviceplutosdrbox.h.
Referenced by setLOPPMTenths().
m_lpfFIRBW
float DevicePlutoSDRBox::m_lpfFIRBW
digital lowpass FIR filter bandwidth (Hz)
Definition at line 66 of file deviceplutosdrbox.h.
Referenced by setFIR().
m_lpfFIREnable
bool DevicePlutoSDRBox::m_lpfFIREnable
enable digital lowpass FIR filter
Definition at line 65 of file deviceplutosdrbox.h.
Referenced by setFIREnable().
m_lpfFIRlog2Decim
uint32_t DevicePlutoSDRBox::m_lpfFIRlog2Decim
digital lowpass FIR filter log2 of decimation factor (0..2)
Definition at line 67 of file deviceplutosdrbox.h.
Referenced by setFIR().
m_lpfFIRRxGain
int DevicePlutoSDRBox::m_lpfFIRRxGain
digital lowpass FIR filter gain Rx side (dB)
Definition at line 68 of file deviceplutosdrbox.h.
Referenced by formatFIRHeader(), and setFIR().
m_lpfFIRTxGain
int DevicePlutoSDRBox::m_lpfFIRTxGain
digital lowpass FIR filter gain Tx side (dB)
Definition at line 69 of file deviceplutosdrbox.h.
Referenced by formatFIRHeader(), and setFIR().
m_rxBuf
struct iio_buffer* DevicePlutoSDRBox::m_rxBuf private
Definition at line 125 of file deviceplutosdrbox.h.
Referenced by createRxBuffer(), deleteRxBuffer(), rxBufferEnd(), rxBufferFirst(), rxBufferRefill(), and rxBufferStep().
m_temp
float DevicePlutoSDRBox::m_temp private
Definition at line 129 of file deviceplutosdrbox.h.
Referenced by fetchTemp().
m_txBuf
struct iio_buffer* DevicePlutoSDRBox::m_txBuf private
Definition at line 126 of file deviceplutosdrbox.h.
Referenced by createTxBuffer(), deleteTxBuffer(), txBufferEnd(), txBufferFirst(), txBufferPush(), and txBufferStep().
m_valid
bool DevicePlutoSDRBox::m_valid private
Definition at line 127 of file deviceplutosdrbox.h.
Referenced by DevicePlutoSDRBox(), openRx(), and openTx().
m_xoInitial
int64_t DevicePlutoSDRBox::m_xoInitial private
Definition at line 128 of file deviceplutosdrbox.h.
Referenced by getXO(), and setLOPPMTenths().
The documentation for this class was generated from the following files:
devices/plutosdr/deviceplutosdrbox.h
devices/plutosdr/deviceplutosdrbox.cpp