SDRAngel: ATVDemod Class Reference
ATVDemod Class Reference
#include <atvdemod.h>
Classes
struct ATVConfig
struct ATVConfigPrivate
struct ATVRFConfig
class AvgExpInt
class MsgConfigureATVDemod
class MsgConfigureChannelizer
class MsgConfigureRFATVDemod
class MsgReportChannelSampleRateChanged
class MsgReportEffectiveSampleRate
Public Types
enum ATVStd {
ATVStdPAL625, ATVStdPAL525, ATVStd405, ATVStdShortInterleaved,
ATVStdShort, ATVStdHSkip
}
enum ATVModulation {
ATV_FM1, ATV_FM2, ATV_FM3, ATV_AM,
ATV_USB, ATV_LSB, ATV_NONE
}
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Public Member Functions
ATVDemod (DeviceAPI *deviceAPI)
~ATVDemod ()
virtual void destroy ()
void setScopeSink (BasebandSampleSink *scopeSink)
void configure (MessageQueue *objMessageQueue, float fltLineDurationUs, float fltTopDurationUs, float fltFramePerS, ATVStd enmATVStandard, int intNumberOfLines, float fltRatioOfRowsToDisplay, float fltVoltLevelSynchroTop, float fltVoltLevelSynchroBlack, bool blnHSync, bool blnVSync, bool blnInvertVideo, int intVideoTabIndex)
void configureRF (MessageQueue *objMessageQueue, int64_t frequencyOffset, ATVModulation enmModulation, float fltRFBandwidth, float fltRFOppBandwidth, bool blnFFTFiltering, bool blndecimatorEnable, float fltBFOFrequency, float fmDeviation)
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool po)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
void setTVScreen (TVScreen *objScreen)
set by the GUI
int getSampleRate ()
int getEffectiveSampleRate ()
double getMagSq () const
Beware this is scaled to 2^30.
bool getBFOLocked ()
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.demodatv"
static const QString m_channelId = "ATVDemod"
Private Slots
void channelSampleRateChanged ()
Private Member Functions
void applySettings ()
void applyStandard ()
void demod (Complex &c)
void processHSkip (float &fltVal, int &intVal)
void processClassic (float &fltVal, int &intVal)
Static Private Member Functions
static float getRFBandwidthDivisor (ATVModulation modulation)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
BasebandSampleSink * m_scopeSink
SampleVector m_scopeSampleBuffer
TVScreen * m_registeredTVScreen
int m_intNumberSamplePerTop
int m_intNumberOfLines
int m_intNumberOfSyncLines
this is the number of non displayable lines at the start of a frame. First displayable row comes next.
int m_intNumberOfBlackLines
this is the total number of lines not part of the image and is used for vertical screen size
int m_intNumberOfEqLines
number of equalizing lines both whole and partial
int m_intNumberSamplePerLineSignals
number of samples in the non image part of the line (signals)
int m_intNumberSaplesPerHSync
number of samples per horizontal synchronization pattern (pulse + back porch)
bool m_interleaved
interleaved image
int m_intImageIndex
int m_intSynchroPoints
bool m_blnSynchroDetected
bool m_blnVerticalSynchroDetected
float m_fltAmpLineAverage
float m_fltEffMin
float m_fltEffMax
float m_fltAmpMin
float m_fltAmpMax
float m_fltAmpDelta
float m_fltBufferI [6]
float m_fltBufferQ [6]
int m_intColIndex
int m_intSampleIndex
int m_intRowIndex
int m_intLineIndex
AvgExpInt m_objAvgColIndex
int m_intAvgColIndex
SampleVector m_sampleBuffer
MovingAverageUtil< double, double, 32 > m_objMagSqAverage
NCO m_nco
SimplePhaseLock m_bfoPLL
SecondOrderRecursiveFilter m_bfoFilter
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
fftfilt * m_DSBFilter
Complex * m_DSBFilterBuffer
int m_DSBFilterBufferIndex
PhaseDiscriminators m_objPhaseDiscri
ATVConfig m_running
ATVConfig m_config
ATVRFConfig m_rfRunning
ATVRFConfig m_rfConfig
ATVConfigPrivate m_runningPrivate
ATVConfigPrivate m_configPrivate
QMutex m_objSettingsMutex
Static Private Attributes
static const int m_ssbFftLen = 1024
Additional Inherited Members
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 47 of file atvdemod.h.
Member Enumeration Documentation
ATVModulation
enum ATVDemod::ATVModulation
Enumerator
ATV_FM1
Classical frequency modulation with discriminator #1.
ATV_FM2
Classical frequency modulation with discriminator #2.
ATV_FM3
Classical frequency modulation with phase derivative discriminator.
ATV_AM
Classical amplitude modulation.
ATV_USB
AM with vestigial lower side band (main signal is in the upper side)
ATV_LSB
AM with vestigial upper side band (main signal is in the lower side)
ATV_NONE
No modulation just produces zeros.
Definition at line 63 of file atvdemod.h.
{
         ATV_FM1,
         ATV_FM2,
         ATV_FM3,
         ATV_AM,
         ATV_USB,
         ATV_LSB,
         ATV_NONE
     };
ATVStd
enum ATVDemod::ATVStd
Enumerator
ATVStdPAL625
ATVStdPAL525
ATVStd405
ATVStdShortInterleaved
ATVStdShort
ATVStdHSkip
Definition at line 53 of file atvdemod.h.
     {
         ATVStdPAL625,
         ATVStdPAL525,
         ATVStd405,
         ATVStdShortInterleaved,
         ATVStdShort,
         ATVStdHSkip
     };
Constructor & Destructor Documentation
ATVDemod()
ATVDemod::ATVDemod (DeviceAPI * deviceAPI)
Definition at line 42 of file atvdemod.cpp.
References DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), applyStandard(), channelSampleRateChanged(), m_channelId, m_channelizer, m_deviceAPI, m_DSBFilter, m_DSBFilterBuffer, m_fltBufferI, m_fltBufferQ, ATVDemod::ATVRFConfig::m_fltRFBandwidth, m_interleaved, m_intNumberOfLines, m_intSynchroPoints, m_objPhaseDiscri, m_rfConfig, m_ssbFftLen, m_threadedChannelizer, and PhaseDiscriminators::setFMScaling().
Referenced by ATVDemod::MsgReportChannelSampleRateChanged::MsgReportChannelSampleRateChanged().
                                        :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(deviceAPI),
         m_scopeSink(0),
         m_registeredTVScreen(0),
         m_intNumberSamplePerTop(0),
         m_intImageIndex(0),
         m_intSynchroPoints(0),
         m_blnSynchroDetected(false),
         m_blnVerticalSynchroDetected(false),
         m_fltAmpLineAverage(0.0f),
         m_fltEffMin(2000000000.0f),
         m_fltEffMax(-2000000000.0f),
         m_fltAmpMin(-2000000000.0f),
         m_fltAmpMax(2000000000.0f),
         m_fltAmpDelta(1.0),
         m_intColIndex(0),
         m_intSampleIndex(0),
         m_intRowIndex(0),
         m_intLineIndex(0),
         m_objAvgColIndex(3),
         m_bfoPLL(200/1000000, 100/1000000, 0.01),
         m_bfoFilter(200.0, 1000000.0, 0.9),
         m_interpolatorDistance(1.0f),
         m_interpolatorDistanceRemain(0.0f),
         m_DSBFilter(0),
         m_DSBFilterBuffer(0),
         m_DSBFilterBufferIndex(0),
         m_objSettingsMutex(QMutex::Recursive)
 {
     setObjectName(m_channelId);
     //*************** ATV PARAMETERS  ***************
     //m_intNumberSamplePerLine=0;
     m_intSynchroPoints=0;
     m_intNumberOfLines=0;
     m_interleaved = true;
     m_DSBFilter = new fftfilt((2.0f * m_rfConfig.m_fltRFBandwidth) / 1000000, 2 * m_ssbFftLen); // arbitrary 1 MS/s sample rate
     m_DSBFilterBuffer = new Complex[m_ssbFftLen];
     memset(m_DSBFilterBuffer, 0, sizeof(Complex)*(m_ssbFftLen));
     memset((void*)m_fltBufferI,0,6*sizeof(float));
     memset((void*)m_fltBufferQ,0,6*sizeof(float));
     m_objPhaseDiscri.setFMScaling(1.0f);
     applyStandard();
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
     connect(m_channelizer, SIGNAL(inputSampleRateChanged()), this, SLOT(channelSampleRateChanged()));
 }
~ATVDemod()
ATVDemod::~ATVDemod ()
Definition at line 99 of file atvdemod.cpp.
References m_channelizer, m_deviceAPI, m_DSBFilter, m_DSBFilterBuffer, m_threadedChannelizer, DeviceAPI::removeChannelSink(), and DeviceAPI::removeChannelSinkAPI().
Referenced by ATVDemod::MsgReportChannelSampleRateChanged::MsgReportChannelSampleRateChanged().
 {
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete m_DSBFilter;
     delete m_DSBFilterBuffer;
 }
Member Function Documentation
applySettings()
void ATVDemod::applySettings () private
Definition at line 541 of file atvdemod.cpp.
References applyStandard(), PhaseLock::configure(), Interpolator::create(), ATVDemod::MsgReportEffectiveSampleRate::create(), fftfilt::create_asym_filter(), BasebandSampleSink::getMessageQueueToGUI(), getRFBandwidthDivisor(), i, m_bfoFilter, m_bfoPLL, ATVDemod::ATVRFConfig::m_blndecimatorEnable, m_config, m_configPrivate, m_DSBFilter, m_DSBFilterBuffer, m_DSBFilterBufferIndex, ATVDemod::ATVConfig::m_enmATVStandard, ATVDemod::ATVRFConfig::m_enmModulation, ATVDemod::ATVRFConfig::m_fltBFOFrequency, ATVDemod::ATVConfig::m_fltFramePerS, ATVDemod::ATVConfig::m_fltLineDuration, ATVDemod::ATVConfig::m_fltRatioOfRowsToDisplay, ATVDemod::ATVRFConfig::m_fltRFBandwidth, ATVDemod::ATVRFConfig::m_fltRFOppBandwidth, ATVDemod::ATVConfig::m_fltTopDuration, ATVDemod::ATVRFConfig::m_fmDeviation, m_intColIndex, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, ATVDemod::ATVRFConfig::m_intFrequencyOffset, m_intImageIndex, m_intNumberOfBlackLines, ATVDemod::ATVConfig::m_intNumberOfLines, m_intNumberOfLines, ATVDemod::ATVConfigPrivate::m_intNumberSamplePerLine, m_intNumberSamplePerLineSignals, m_intNumberSamplePerTop, m_intRowIndex, ATVDemod::ATVConfig::m_intSampleRate, ATVDemod::ATVConfigPrivate::m_intTVSampleRate, m_nco, m_objPhaseDiscri, m_objSettingsMutex, m_registeredTVScreen, m_rfConfig, m_rfRunning, m_running, m_runningPrivate, m_ssbFftLen, MessageQueue::push(), TVScreen::resizeTVScreen(), PhaseDiscriminators::setFMScaling(), NCO::setFreq(), and SecondOrderRecursiveFilter::setFrequencies().
Referenced by handleMessage().
 {
     if (m_config.m_intSampleRate == 0)
     {
         return;
     }
     bool forwardSampleRateChange = false;
     if((m_rfConfig.m_intFrequencyOffset != m_rfRunning.m_intFrequencyOffset)
        || (m_rfConfig.m_enmModulation != m_rfRunning.m_enmModulation)
        || (m_config.m_intSampleRate != m_running.m_intSampleRate))
     {
         m_nco.setFreq(-m_rfConfig.m_intFrequencyOffset, m_config.m_intSampleRate);
     }
     if ((m_config.m_intSampleRate != m_running.m_intSampleRate)
         || (m_rfConfig.m_fltRFBandwidth != m_rfRunning.m_fltRFBandwidth)
         || (m_config.m_fltFramePerS != m_running.m_fltFramePerS)
         || (m_config.m_intNumberOfLines != m_running.m_intNumberOfLines))
     {
         m_objSettingsMutex.lock();
         int linesPerSecond = m_config.m_intNumberOfLines * m_config.m_fltFramePerS;
         int maxPoints = m_config.m_intSampleRate / linesPerSecond;
         int i = maxPoints;
         for (; i > 0; i--)
         {
             if ((i * linesPerSecond) % 10 == 0)
                 break;
         }
         int nbPointsPerRateUnit = i == 0 ? maxPoints : i;
         m_configPrivate.m_intTVSampleRate = nbPointsPerRateUnit * linesPerSecond;
         if (m_configPrivate.m_intTVSampleRate > 0)
         {
             m_interpolatorDistance = (Real) m_configPrivate.m_intTVSampleRate / (Real) m_config.m_intSampleRate;
         }
         else
         {
             m_configPrivate.m_intTVSampleRate = m_config.m_intSampleRate;
             m_interpolatorDistance = 1.0f;
         }
         m_interpolatorDistanceRemain = 0;
         m_interpolator.create(24,
                 m_configPrivate.m_intTVSampleRate,
                 m_rfConfig.m_fltRFBandwidth / getRFBandwidthDivisor(m_rfConfig.m_enmModulation),
                 3.0);
         m_objSettingsMutex.unlock();
     }
     if((m_config.m_fltFramePerS != m_running.m_fltFramePerS)
        || (m_config.m_fltLineDuration != m_running.m_fltLineDuration)
        || (m_config.m_intSampleRate != m_running.m_intSampleRate)
        || (m_config.m_fltTopDuration != m_running.m_fltTopDuration)
        || (m_config.m_fltRatioOfRowsToDisplay != m_running.m_fltRatioOfRowsToDisplay)
        || (m_config.m_enmATVStandard != m_running.m_enmATVStandard)
        || (m_config.m_intNumberOfLines != m_running.m_intNumberOfLines))
     {
         m_objSettingsMutex.lock();
         m_intNumberOfLines = m_config.m_intNumberOfLines;
         applyStandard();
         m_configPrivate.m_intNumberSamplePerLine = (int) (m_config.m_fltLineDuration * m_config.m_intSampleRate);
         m_intNumberSamplePerTop = (int) (m_config.m_fltTopDuration * m_config.m_intSampleRate);
         if (m_registeredTVScreen)
         {
             //m_registeredTVScreen->setRenderImmediate(!(m_config.m_fltFramePerS > 25.0f));
             m_registeredTVScreen->resizeTVScreen(
                     m_configPrivate.m_intNumberSamplePerLine - m_intNumberSamplePerLineSignals,
                     m_intNumberOfLines - m_intNumberOfBlackLines);
         }
         qDebug() << "ATVDemod::applySettings:"
                 << " m_fltLineDuration: " << m_config.m_fltLineDuration
                 << " m_fltFramePerS: " << m_config.m_fltFramePerS
                 << " m_intNumberOfLines: " << m_intNumberOfLines
                 << " m_intNumberSamplePerLine: " << m_configPrivate.m_intNumberSamplePerLine
                 << " m_intNumberOfBlackLines: " << m_intNumberOfBlackLines;
         m_intImageIndex = 0;
         m_intColIndex=0;
         m_intRowIndex=0;
         m_objSettingsMutex.unlock();
     }
     if ((m_configPrivate.m_intTVSampleRate != m_runningPrivate.m_intTVSampleRate)
         || (m_configPrivate.m_intNumberSamplePerLine != m_runningPrivate.m_intNumberSamplePerLine)
         || (m_config.m_intSampleRate != m_running.m_intSampleRate)
         || (m_rfConfig.m_blndecimatorEnable != m_rfRunning.m_blndecimatorEnable))
     {
         forwardSampleRateChange = true;
     }
     if ((m_configPrivate.m_intTVSampleRate != m_runningPrivate.m_intTVSampleRate)
         || (m_rfConfig.m_fltRFBandwidth != m_rfRunning.m_fltRFBandwidth)
         || (m_rfConfig.m_fltRFOppBandwidth != m_rfRunning.m_fltRFOppBandwidth))
     {
         m_objSettingsMutex.lock();
         m_DSBFilter->create_asym_filter(m_rfConfig.m_fltRFOppBandwidth / m_configPrivate.m_intTVSampleRate,
                 m_rfConfig.m_fltRFBandwidth / m_configPrivate.m_intTVSampleRate);
         memset(m_DSBFilterBuffer, 0, sizeof(Complex)*(m_ssbFftLen));
         m_DSBFilterBufferIndex = 0;
         m_objSettingsMutex.unlock();
     }
     if ((m_configPrivate.m_intTVSampleRate != m_runningPrivate.m_intTVSampleRate)
         || (m_rfConfig.m_fltBFOFrequency != m_rfRunning.m_fltBFOFrequency))
     {
         m_bfoPLL.configure(m_rfConfig.m_fltBFOFrequency / m_configPrivate.m_intTVSampleRate,
                 100.0 / m_configPrivate.m_intTVSampleRate,
                 0.01);
         m_bfoFilter.setFrequencies(m_rfConfig.m_fltBFOFrequency, m_configPrivate.m_intTVSampleRate);
     }
     if (m_rfConfig.m_fmDeviation != m_rfRunning.m_fmDeviation)
     {
         m_objPhaseDiscri.setFMScaling(1.0f / m_rfConfig.m_fmDeviation);
     }
     m_running = m_config;
     m_rfRunning = m_rfConfig;
     m_runningPrivate = m_configPrivate;
     if (forwardSampleRateChange && getMessageQueueToGUI())
     {
         int sampleRate = m_rfRunning.m_blndecimatorEnable ? m_runningPrivate.m_intTVSampleRate : m_running.m_intSampleRate;
         MsgReportEffectiveSampleRate *report;
         report = MsgReportEffectiveSampleRate::create(sampleRate, m_runningPrivate.m_intNumberSamplePerLine);
         getMessageQueueToGUI()->push(report);
     }
 }
applyStandard()
void ATVDemod::applyStandard () private
Definition at line 683 of file atvdemod.cpp.
References ATVStd405, ATVStdHSkip, ATVStdPAL525, ATVStdPAL625, ATVStdShort, ATVStdShortInterleaved, m_config, ATVDemod::ATVConfig::m_enmATVStandard, ATVDemod::ATVConfig::m_fltLineDuration, m_interleaved, m_intNumberOfBlackLines, m_intNumberOfEqLines, m_intNumberOfSyncLines, m_intNumberSamplePerLineSignals, m_intNumberSaplesPerHSync, and ATVDemod::ATVConfig::m_intSampleRate.
Referenced by applySettings(), and ATVDemod().
 {
     switch(m_config.m_enmATVStandard)
     {
     case ATVStdHSkip:
         // what is left in a line for the image
         m_intNumberOfSyncLines  = 0;
         m_intNumberOfBlackLines = 0;
         m_intNumberOfEqLines    = 0; // not applicable
         m_interleaved = false;
         break;
     case ATVStdShort:
         // what is left in a line for the image
         m_intNumberOfSyncLines  = 4;
         m_intNumberOfBlackLines = 4;
         m_intNumberOfEqLines    = 0;
         m_interleaved = false;
         break;
     case ATVStdShortInterleaved:
         // what is left in a line for the image
         m_intNumberOfSyncLines  = 4;
         m_intNumberOfBlackLines = 4;
         m_intNumberOfEqLines    = 0;
         m_interleaved = true;
         break;
     case ATVStd405: // Follows loosely the 405 lines standard
         // what is left in a ine for the image
         m_intNumberOfSyncLines  = 24; // (15+7)*2 - 20
         m_intNumberOfBlackLines = 28; // above + 4
         m_intNumberOfEqLines    = 3;
         m_interleaved = true;
         break;
     case ATVStdPAL525: // Follows PAL-M standard
         // what is left in a 64/1.008 us line for the image
         m_intNumberOfSyncLines  = 40; // (15+15)*2 - 20
         m_intNumberOfBlackLines = 44; // above + 4
         m_intNumberOfEqLines    = 3;
         m_interleaved = true;
         break;
     case ATVStdPAL625: // Follows PAL-B/G/H standard
     default:
         // what is left in a 64 us line for the image
         m_intNumberOfSyncLines  = 44; // (15+17)*2 - 20
         m_intNumberOfBlackLines = 48; // above + 4
         m_intNumberOfEqLines    = 3;
         m_interleaved = true;
     }
     // for now all standards apply this
     m_intNumberSamplePerLineSignals = (int) ((12.0f/64.0f)*m_config.m_fltLineDuration * m_config.m_intSampleRate);  // 12.0 = 7.3 + 4.7
     m_intNumberSaplesPerHSync = (int) ((9.6f/64.0f)*m_config.m_fltLineDuration * m_config.m_intSampleRate);      // 9.4 = 4.7 + 4.7
 }
channelSampleRateChanged
void ATVDemod::channelSampleRateChanged () private slot
Definition at line 774 of file atvdemod.cpp.
References ATVDemod::MsgReportChannelSampleRateChanged::create(), DownChannelizer::getInputSampleRate(), BasebandSampleSink::getMessageQueueToGUI(), m_channelizer, and MessageQueue::push().
Referenced by ATVDemod().
 {
     qDebug("ATVDemod::channelSampleRateChanged");
     if (getMessageQueueToGUI())
     {
         MsgReportChannelSampleRateChanged *msg = MsgReportChannelSampleRateChanged::create(m_channelizer->getInputSampleRate());
         getMessageQueueToGUI()->push(msg);
     }
 }
configure()
void ATVDemod::configure (MessageQueue * objMessageQueue, float fltLineDurationUs, float fltTopDurationUs, float fltFramePerS, ATVStd enmATVStandard, int intNumberOfLines, float fltRatioOfRowsToDisplay, float fltVoltLevelSynchroTop, float fltVoltLevelSynchroBlack, bool blnHSync, bool blnVSync, bool blnInvertVideo, int intVideoTabIndex)
Definition at line 114 of file atvdemod.cpp.
References ATVDemod::MsgConfigureATVDemod::create(), and MessageQueue::push().
Referenced by ATVDemodGUI::applySettings(), and setScopeSink().
 {
     Message* msgCmd = MsgConfigureATVDemod::create(
             fltLineDurationUs,
             fltTopDurationUs,
             fltFramePerS,
             enmATVStandard,
             intNumberOfLines,
             fltRatioOfRowsToDisplay,
             fltVoltLevelSynchroTop,
             fltVoltLevelSynchroBlack,
             blnHSync,
             blnVSync,
             blnInvertVideo,
             intVideoTabIndex);
     objMessageQueue->push(msgCmd);
 }
configureRF()
void ATVDemod::configureRF (MessageQueue * objMessageQueue, int64_t frequencyOffset, ATVModulation enmModulation, float fltRFBandwidth, float fltRFOppBandwidth, bool blnFFTFiltering, bool blndecimatorEnable, float fltBFOFrequency, float fmDeviation)
Definition at line 145 of file atvdemod.cpp.
References ATVDemod::MsgConfigureRFATVDemod::create(), and MessageQueue::push().
Referenced by ATVDemodGUI::applyRFSettings(), and setScopeSink().
 {
     Message* msgCmd = MsgConfigureRFATVDemod::create(
             frequencyOffset,
             enmModulation,
             fltRFBandwidth,
             fltRFOppBandwidth,
             blnFFTFiltering,
             blnDecimatorEnable,
             fltBFOFrequency,
             fmDeviation);
     objMessageQueue->push(msgCmd);
 }
demod()
void ATVDemod::demod (Complex & c) private
Definition at line 248 of file atvdemod.cpp.
References ATV_AM, ATV_FM1, ATV_FM2, ATV_FM3, ATV_LSB, ATV_USB, ATVStdHSkip, m_bfoFilter, m_bfoPLL, ATVDemod::ATVRFConfig::m_blnFFTFiltering, ATVDemod::ATVConfig::m_blnInvertVideo, m_DSBFilter, m_DSBFilterBuffer, m_DSBFilterBufferIndex, ATVDemod::ATVConfig::m_enmATVStandard, ATVDemod::ATVRFConfig::m_enmModulation, m_fltAmpDelta, m_fltAmpLineAverage, m_fltAmpMin, m_fltBufferI, m_fltBufferQ, m_fltEffMax, m_fltEffMin, ATVDemod::ATVConfig::m_fltVoltLevelSynchroBlack, ATVDemod::ATVRFConfig::m_fmDeviation, ATVDemod::ATVConfig::m_intVideoTabIndex, m_objMagSqAverage, m_objPhaseDiscri, m_registeredTVScreen, m_rfRunning, m_running, m_scopeSampleBuffer, m_scopeSink, PhaseDiscriminators::phaseDiscriminatorDelta(), PhaseLock::process(), processClassic(), processHSkip(), SecondOrderRecursiveFilter::run(), fftfilt::runAsym(), SDR_RX_SCALEF, and sqrt().
Referenced by feed().
 {
     float fltDivSynchroBlack = 1.0f - m_running.m_fltVoltLevelSynchroBlack;
     float fltNormI;
     float fltNormQ;
     float fltNorm;
     float fltVal;
     int intVal;
     //********** FFT filtering **********
     if (m_rfRunning.m_blnFFTFiltering)
     {
         int n_out;
         fftfilt::cmplx *filtered;
         n_out = m_DSBFilter->runAsym(c, &filtered, m_rfRunning.m_enmModulation != ATV_LSB); // all usb except explicitely lsb
         if (n_out > 0)
         {
             memcpy((void *) m_DSBFilterBuffer, (const void *) filtered, n_out*sizeof(Complex));
             m_DSBFilterBufferIndex = 0;
         }
         m_DSBFilterBufferIndex++;
     }
     //********** demodulation **********
     const float& fltI = m_rfRunning.m_blnFFTFiltering ? m_DSBFilterBuffer[m_DSBFilterBufferIndex-1].real() : c.real();
     const float& fltQ = m_rfRunning.m_blnFFTFiltering ? m_DSBFilterBuffer[m_DSBFilterBufferIndex-1].imag() : c.imag();
     double magSq;
     if ((m_rfRunning.m_enmModulation == ATV_FM1) || (m_rfRunning.m_enmModulation == ATV_FM2))
     {
         //Amplitude FM
         magSq = fltI*fltI + fltQ*fltQ;
         m_objMagSqAverage(magSq);
         fltNorm = sqrt(magSq);
         fltNormI= fltI/fltNorm;
         fltNormQ= fltQ/fltNorm;
         //-2 > 2 : 0 -> 1 volt
         //0->0.3 synchro  0.3->1 image
         if (m_rfRunning.m_enmModulation == ATV_FM1)
         {
             //YDiff Cd
             fltVal = m_fltBufferI[0]*(fltNormQ - m_fltBufferQ[1]);
             fltVal -= m_fltBufferQ[0]*(fltNormI - m_fltBufferI[1]);
             fltVal += 2.0f;
             fltVal /= 4.0f;
         }
         else
         {
             //YDiff Folded
             fltVal =  m_fltBufferI[2]*((m_fltBufferQ[5]-fltNormQ)/16.0f + m_fltBufferQ[1] - m_fltBufferQ[3]);
             fltVal -= m_fltBufferQ[2]*((m_fltBufferI[5]-fltNormI)/16.0f + m_fltBufferI[1] - m_fltBufferI[3]);
             fltVal += 2.125f;
             fltVal /= 4.25f;
             m_fltBufferI[5]=m_fltBufferI[4];
             m_fltBufferQ[5]=m_fltBufferQ[4];
             m_fltBufferI[4]=m_fltBufferI[3];
             m_fltBufferQ[4]=m_fltBufferQ[3];
             m_fltBufferI[3]=m_fltBufferI[2];
             m_fltBufferQ[3]=m_fltBufferQ[2];
             m_fltBufferI[2]=m_fltBufferI[1];
             m_fltBufferQ[2]=m_fltBufferQ[1];
         }
         m_fltBufferI[1]=m_fltBufferI[0];
         m_fltBufferQ[1]=m_fltBufferQ[0];
         m_fltBufferI[0]=fltNormI;
         m_fltBufferQ[0]=fltNormQ;
         if (m_rfRunning.m_fmDeviation != 1.0f)
         {
             fltVal = ((fltVal - 0.5f) / m_rfRunning.m_fmDeviation) + 0.5f;
         }
     }
     else if (m_rfRunning.m_enmModulation == ATV_AM)
     {
         //Amplitude AM
         magSq = fltI*fltI + fltQ*fltQ;
         m_objMagSqAverage(magSq);
         fltNorm = sqrt(magSq);
         fltVal = fltNorm / SDR_RX_SCALEF;
         //********** Mini and Maxi Amplitude tracking **********
         if(fltVal<m_fltEffMin)
         {
             m_fltEffMin=fltVal;
         }
         if(fltVal>m_fltEffMax)
         {
             m_fltEffMax=fltVal;
         }
         //Normalisation
         fltVal -= m_fltAmpMin;
         fltVal /=m_fltAmpDelta;
     }
     else if ((m_rfRunning.m_enmModulation == ATV_USB) || (m_rfRunning.m_enmModulation == ATV_LSB))
     {
         magSq = fltI*fltI + fltQ*fltQ;
         m_objMagSqAverage(magSq);
         fltNorm = sqrt(magSq);
         Real bfoValues[2];
         float fltFiltered = m_bfoFilter.run(fltI);
         m_bfoPLL.process(fltFiltered, bfoValues);
         // do the mix
         float mixI = fltI * bfoValues[0] - fltQ * bfoValues[1];
         float mixQ = fltI * bfoValues[1] + fltQ * bfoValues[0];
         if (m_rfRunning.m_enmModulation == ATV_USB) {
             fltVal = (mixI + mixQ);
         } else {
             fltVal = (mixI - mixQ);
         }
         //********** Mini and Maxi Amplitude tracking **********
         if(fltVal<m_fltEffMin)
         {
             m_fltEffMin=fltVal;
         }
         if(fltVal>m_fltEffMax)
         {
             m_fltEffMax=fltVal;
         }
         //Normalisation
         fltVal -= m_fltAmpMin;
         fltVal /=m_fltAmpDelta;
     }
     else if (m_rfRunning.m_enmModulation == ATV_FM3)
     {
         float rawDeviation;
         fltVal = m_objPhaseDiscri.phaseDiscriminatorDelta(c, magSq, rawDeviation) + 0.5f;
         //fltVal = fltVal < 0.0f ? 0.0f : fltVal > 1.0f ? 1.0f : fltVal;
         m_objMagSqAverage(magSq);
         fltNorm = sqrt(magSq);
     }
     else
     {
         magSq = fltI*fltI + fltQ*fltQ;
         m_objMagSqAverage(magSq);
         fltNorm = sqrt(magSq);
         fltVal = 0.0f;
     }
     fltVal = m_running.m_blnInvertVideo ? 1.0f - fltVal : fltVal;
     fltVal = (fltVal < -1.0f) ? -1.0f : (fltVal > 1.0f) ? 1.0f : fltVal;
     if ((m_running.m_intVideoTabIndex == 1) && (m_scopeSink != 0)) { // feed scope buffer only if scope is present and visible
         m_scopeSampleBuffer.push_back(Sample(fltVal*SDR_RX_SCALEF, 0.0f));
     }
     m_fltAmpLineAverage += fltVal;
     //********** gray level **********
     //-0.3 -> 0.7
     intVal = (int) 255.0*(fltVal - m_running.m_fltVoltLevelSynchroBlack) / fltDivSynchroBlack;
     //0 -> 255
     if(intVal<0)
     {
         intVal=0;
     }
     else if(intVal>255)
     {
         intVal=255;
     }
     //********** process video sample **********
     if (m_registeredTVScreen) // can process only if the screen is available (set via the GUI)
     {
         if (m_running.m_enmATVStandard == ATVStdHSkip) {
             processHSkip(fltVal, intVal);
         } else {
             processClassic(fltVal, intVal);
         }
     }
 }
deserialize()
virtual bool ATVDemod::deserialize (const QByteArray & data) inline virtual
Implements ChannelAPI.
Definition at line 234 of file atvdemod.h.
 { (void) data; return false; }
destroy()
virtual void ATVDemod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 197 of file atvdemod.h.
 { delete this; }
feed()
void ATVDemod::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool po) virtual
Implements BasebandSampleSink.
Definition at line 168 of file atvdemod.cpp.
References Interpolator::decimate(), demod(), BasebandSampleSink::feed(), ATVDemod::ATVRFConfig::m_blndecimatorEnable, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, ATVDemod::ATVRFConfig::m_intFrequencyOffset, ATVDemod::ATVConfig::m_intVideoTabIndex, m_nco, m_objSettingsMutex, m_rfRunning, m_running, m_scopeSampleBuffer, m_scopeSink, and NCO::nextIQ().
Referenced by setScopeSink().
 {
     (void) firstOfBurst;
     float fltI;
     float fltQ;
     Complex ci;
     //********** Let's rock and roll buddy ! **********
     m_objSettingsMutex.lock();
     //********** Accessing ATV Screen context **********
 #ifdef EXTENDED_DIRECT_SAMPLE
     qint16 * ptrBufferToRelease = 0;
     qint16 * ptrBuffer;
     qint32 intLen;
     //********** Reading direct samples **********
     SampleVector::const_iterator it = begin;
     intLen = it->intLen;
     ptrBuffer = it->ptrBuffer;
     ptrBufferToRelease = ptrBuffer;
     ++it;
     for(qint32 intInd=0; intInd<intLen-1; intInd +=2)
     {
         fltI= ((qint32) (*ptrBuffer)) << 4;
         ptrBuffer ++;
         fltQ= ((qint32) (*ptrBuffer)) << 4;
         ptrBuffer ++;
 #else
     for (SampleVector::const_iterator it = begin; it != end; ++it /* ++it **/)
     {
         fltI = it->real();
         fltQ = it->imag();
 #endif
         Complex c(fltI, fltQ);
         if (m_rfRunning.m_intFrequencyOffset != 0)
         {
             c *= m_nco.nextIQ();
         }
         if (m_rfRunning.m_blndecimatorEnable)
         {
             if (m_interpolator.decimate(&m_interpolatorDistanceRemain, c, &ci))
             {
                 demod(ci);
                 m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
         }
         else
         {
             demod(c);
         }
     }
     if ((m_running.m_intVideoTabIndex == 1) && (m_scopeSink != 0)) // do only if scope tab is selected and scope is available
     {
         m_scopeSink->feed(m_scopeSampleBuffer.begin(), m_scopeSampleBuffer.end(), false); // m_ssb = positive only
         m_scopeSampleBuffer.clear();
     }
 #ifdef EXTENDED_DIRECT_SAMPLE
     if (ptrBufferToRelease != 0)
     {
         delete ptrBufferToRelease;
     }
 #endif
     m_objSettingsMutex.unlock();
 }
getBFOLocked()
bool ATVDemod::getBFOLocked ()
Definition at line 746 of file atvdemod.cpp.
References ATV_LSB, ATV_USB, PhaseLock::locked(), m_bfoPLL, ATVDemod::ATVRFConfig::m_enmModulation, and m_rfRunning.
Referenced by getMagSq(), and ATVDemodGUI::tick().
 {
     if ((m_rfRunning.m_enmModulation == ATV_USB) || (m_rfRunning.m_enmModulation == ATV_LSB))
     {
         return m_bfoPLL.locked();
     }
     else
     {
         return false;
     }
 }
getCenterFrequency()
virtual qint64 ATVDemod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 231 of file atvdemod.h.
References ATVDemod::ATVRFConfig::m_intFrequencyOffset, and m_rfRunning.
 { return m_rfRunning.m_intFrequencyOffset; }
getEffectiveSampleRate()
int ATVDemod::getEffectiveSampleRate ()
Definition at line 741 of file atvdemod.cpp.
References ATVDemod::ATVRFConfig::m_blndecimatorEnable, ATVDemod::ATVConfig::m_intSampleRate, ATVDemod::ATVConfigPrivate::m_intTVSampleRate, m_rfRunning, m_running, and m_runningPrivate.
Referenced by getStreamCenterFrequency(), ATVDemodGUI::lineTimeUpdate(), ATVDemodGUI::on_modulation_currentIndexChanged(), ATVDemodGUI::on_rfFiltering_toggled(), and ATVDemodGUI::topTimeUpdate().
 {
     return m_rfRunning.m_blndecimatorEnable ? m_runningPrivate.m_intTVSampleRate : m_running.m_intSampleRate;
 }
getIdentifier()
virtual void ATVDemod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 229 of file atvdemod.h.
 { id = objectName(); }
getMagSq()
double ATVDemod::getMagSq () const inline
Beware this is scaled to 2^30.
Definition at line 249 of file atvdemod.h.
References getBFOLocked(), and m_objMagSqAverage.
Referenced by ATVDemodGUI::tick().
getNbSinkStreams()
virtual int ATVDemod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 236 of file atvdemod.h.
 { return 1; }
getNbSourceStreams()
virtual int ATVDemod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 237 of file atvdemod.h.
 { return 0; }
getRFBandwidthDivisor()
float ATVDemod::getRFBandwidthDivisor (ATVModulation modulation) static private
Definition at line 758 of file atvdemod.cpp.
References ATV_AM, ATV_FM1, ATV_FM2, ATV_LSB, and ATV_USB.
Referenced by applySettings().
 {
     switch(modulation)
     {
     case ATV_USB:
     case ATV_LSB:
         return 1.05f;
         break;
     case ATV_FM1:
     case ATV_FM2:
     case ATV_AM:
     default:
         return 2.2f;
     }
 }
getSampleRate()
int ATVDemod::getSampleRate ()
Definition at line 736 of file atvdemod.cpp.
References ATVDemod::ATVConfig::m_intSampleRate, and m_running.
Referenced by ATVDemodGUI::applySettings(), and getStreamCenterFrequency().
 {
     return m_running.m_intSampleRate;
 }
getStreamCenterFrequency()
virtual qint64 ATVDemod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 239 of file atvdemod.h.
References getEffectiveSampleRate(), getSampleRate(), ATVDemod::ATVRFConfig::m_intFrequencyOffset, m_rfRunning, and setTVScreen().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_rfRunning.m_intFrequencyOffset;
     }
getTitle()
virtual void ATVDemod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 230 of file atvdemod.h.
 { title = objectName(); }
handleMessage()
bool ATVDemod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 457 of file atvdemod.cpp.
References applySettings(), DownChannelizer::configure(), ATVDemod::MsgConfigureChannelizer::getCenterFrequency(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSink::getInputMessageQueue(), DownChannelizer::getInputSampleRate(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), BasebandSampleSink::handleMessage(), ATVDemod::ATVRFConfig::m_blndecimatorEnable, ATVDemod::ATVRFConfig::m_blnFFTFiltering, ATVDemod::ATVConfig::m_blnHSync, ATVDemod::ATVConfig::m_blnVSync, m_channelizer, m_config, ATVDemod::ATVRFConfig::m_enmModulation, ATVDemod::ATVRFConfig::m_fltBFOFrequency, ATVDemod::ATVConfig::m_fltFramePerS, ATVDemod::ATVConfig::m_fltLineDuration, ATVDemod::ATVConfig::m_fltRatioOfRowsToDisplay, ATVDemod::ATVRFConfig::m_fltRFBandwidth, ATVDemod::ATVRFConfig::m_fltRFOppBandwidth, ATVDemod::ATVConfig::m_fltTopDuration, ATVDemod::ATVConfig::m_fltVoltLevelSynchroBlack, ATVDemod::ATVConfig::m_fltVoltLevelSynchroTop, ATVDemod::ATVRFConfig::m_fmDeviation, ATVDemod::ATVRFConfig::m_intFrequencyOffset, ATVDemod::ATVConfig::m_intSampleRate, ATVDemod::MsgConfigureATVDemod::m_objMsgConfig, ATVDemod::MsgConfigureRFATVDemod::m_objMsgConfig, m_rfConfig, m_scopeSink, and Message::match().
Referenced by setScopeSink().
 {
     qDebug() << "ATVDemod::handleMessage";
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& objNotif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         m_config.m_intSampleRate = objNotif.getSampleRate();
         m_rfConfig.m_intFrequencyOffset = objNotif.getFrequencyOffset();
         qDebug() << "ATVDemod::handleMessage: MsgChannelizerNotification:"
                 << " m_intSampleRate: " << m_config.m_intSampleRate
                 << " m_intFrequencyOffset: " << m_rfConfig.m_intFrequencyOffset;
         applySettings();
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
                 m_channelizer->getInputSampleRate(),
                 cfg.getCenterFrequency());
         qDebug() << "ATVDemod::handleMessage: MsgConfigureChannelizer: sampleRate: " << m_channelizer->getInputSampleRate()
                 << " centerFrequency: " << cfg.getCenterFrequency();
         return true;
     }
     else if (MsgConfigureATVDemod::match(cmd))
     {
         MsgConfigureATVDemod& objCfg = (MsgConfigureATVDemod&) cmd;
         m_config = objCfg.m_objMsgConfig;
         qDebug()  << "ATVDemod::handleMessage: MsgConfigureATVDemod:"
                 << " m_fltVoltLevelSynchroBlack:" << m_config.m_fltVoltLevelSynchroBlack
                 << " m_fltVoltLevelSynchroTop:" << m_config.m_fltVoltLevelSynchroTop
                 << " m_fltFramePerS:" << m_config.m_fltFramePerS
                 << " m_fltLineDurationUs:" << m_config.m_fltLineDuration
                 << " m_fltRatioOfRowsToDisplay:" << m_config.m_fltRatioOfRowsToDisplay
                 << " m_fltTopDurationUs:" << m_config.m_fltTopDuration
                 << " m_blnHSync:" << m_config.m_blnHSync
                 << " m_blnVSync:" << m_config.m_blnVSync;
         applySettings();
         return true;
     }
     else if (MsgConfigureRFATVDemod::match(cmd))
     {
         MsgConfigureRFATVDemod& objCfg = (MsgConfigureRFATVDemod&) cmd;
         m_rfConfig = objCfg.m_objMsgConfig;
         qDebug()  << "ATVDemod::handleMessage: MsgConfigureRFATVDemod:"
                 << " m_intFrequencyOffset:" << m_rfConfig.m_intFrequencyOffset
                 << " m_enmModulation:" << m_rfConfig.m_enmModulation
                 << " m_fltRFBandwidth:" << m_rfConfig.m_fltRFBandwidth
                 << " m_fltRFOppBandwidth:" << m_rfConfig.m_fltRFOppBandwidth
                 << " m_blnFFTFiltering:" << m_rfConfig.m_blnFFTFiltering
                 << " m_blnDecimatorEnable:" << m_rfConfig.m_blndecimatorEnable
                 << " m_fltBFOFrequency:" << m_rfConfig.m_fltBFOFrequency
                 << " m_fmDeviation:" << m_rfConfig.m_fmDeviation;
         applySettings();
         return true;
     }
     else
     {
         if (m_scopeSink != 0)
         {
            return m_scopeSink->handleMessage(cmd);
         }
         else
         {
             return false;
         }
     }
 }
processClassic()
void ATVDemod::processClassic (float & fltVal, int & intVal) inline private
Definition at line 591 of file atvdemod.h.
References ATV_AM, ATV_LSB, ATV_USB, ATVDemod::ATVConfig::m_blnHSync, ATVDemod::ATVConfig::m_blnVSync, ATVDemod::ATVRFConfig::m_enmModulation, m_fltEffMax, m_fltEffMin, ATVDemod::ATVConfig::m_fltVoltLevelSynchroBlack, ATVDemod::ATVConfig::m_fltVoltLevelSynchroTop, ATVDemod::ATVConfigPrivate::m_intNumberSamplePerLine, m_intNumberSamplePerTop, TVScreen::renderImage(), TVScreen::selectRow(), and TVScreen::setDataColor().
Referenced by demod().
     {
         int intSynchroTimeSamples= (3 * m_runningPrivate.m_intNumberSamplePerLine)/4;
         float fltSynchroTrameLevel =  0.5f*((float)intSynchroTimeSamples) * m_running.m_fltVoltLevelSynchroBlack;
         // Horizontal Synchro detection
         // Floor Detection 0
         if (fltVal < m_running.m_fltVoltLevelSynchroTop)
         {
             m_intSynchroPoints++;
         }
         // Black detection 0.3
         else if (fltVal > m_running.m_fltVoltLevelSynchroBlack)
         {
             m_intSynchroPoints = 0;
         }
         m_blnSynchroDetected = (m_intSynchroPoints == m_intNumberSamplePerTop);
         //Horizontal Synchro processing
         bool blnNewLine = false;
         if (m_blnSynchroDetected)
         {
             m_intAvgColIndex = m_intSampleIndex - m_intColIndex - (m_intColIndex < m_runningPrivate.m_intNumberSamplePerLine/2 ? 150 : 0);
             //qDebug("HSync: %d %d %d", m_intSampleIndex, m_intColIndex, m_intAvgColIndex);
             m_intSampleIndex = 0;
         }
         else
         {
             m_intSampleIndex++;
         }
         if (!m_running.m_blnHSync && (m_intColIndex >= m_runningPrivate.m_intNumberSamplePerLine)) // H Sync not active
         {
             m_intColIndex = 0;
             blnNewLine = true;
         }
         else if (m_intColIndex >= m_runningPrivate.m_intNumberSamplePerLine + m_intNumberSamplePerTop) // No valid H sync
         {
             if (m_running.m_blnHSync && (m_intLineIndex == 0))
             {
                 //qDebug("HSync: %d %d", m_intColIndex, m_intAvgColIndex);
                 m_intColIndex = m_intNumberSamplePerTop + m_intAvgColIndex/4; // amortizing 1/4
             }
             else
             {
                 m_intColIndex = m_intNumberSamplePerTop;
             }
             blnNewLine = true;
         }
         if (blnNewLine)
         {
             if ((m_rfRunning.m_enmModulation == ATV_AM)
                 || (m_rfRunning.m_enmModulation == ATV_USB)
                 || (m_rfRunning.m_enmModulation == ATV_LSB))
             {
                 m_fltAmpMin = m_fltEffMin;
                 m_fltAmpMax = m_fltEffMax;
                 m_fltAmpDelta = m_fltEffMax-m_fltEffMin;
                 if(m_fltAmpDelta<=0.0)
                 {
                     m_fltAmpDelta=1.0f;
                 }
                 //Reset extrema
                 m_fltEffMin = 2000000.0f;
                 m_fltEffMax = -2000000.0f;
             }
             m_fltAmpLineAverage=0.0f;
             //New line + Interleaving
             m_intRowIndex += m_interleaved ? 2 : 1;
             if (m_intRowIndex < m_intNumberOfLines)
             {
                 m_registeredTVScreen->selectRow(m_intRowIndex - m_intNumberOfSyncLines);
             }
             m_intLineIndex++;
         }
         // Filling pixels
         // +4 is to compensate shift due to hsync amortizing factor of 1/4
         m_registeredTVScreen->setDataColor(m_intColIndex - m_intNumberSaplesPerHSync + m_intNumberSamplePerTop + 4, intVal, intVal, intVal);
         m_intColIndex++;
         // Vertical sync and image rendering
         if ((m_running.m_blnVSync) && (m_intLineIndex < m_intNumberOfLines)) // VSync activated and lines in range
         {
             if (m_intColIndex >= intSynchroTimeSamples)
             {
                 if (m_fltAmpLineAverage <= fltSynchroTrameLevel)
                 {
                     m_fltAmpLineAverage = 0.0f;
                     if (!m_blnVerticalSynchroDetected) // not yet
                     {
                         m_blnVerticalSynchroDetected = true; // prevent repetition
                         if ((m_intLineIndex % 2 == 0) || !m_interleaved) // even => odd image
{
                             m_registeredTVScreen->renderImage(0);
                             m_intRowIndex = 1;
                         }
                         else
{
                             m_intRowIndex = 0;
                         }
                         m_registeredTVScreen->selectRow(m_intRowIndex - m_intNumberOfSyncLines);
                         m_intLineIndex = 0;
                         m_intImageIndex++;
                     }
                 }
                 else
                 {
                     m_blnVerticalSynchroDetected = false; // reset
                 }
             }
         }
         else // no VSync or lines out of range => arbitrary
         {
             if (m_intLineIndex >= m_intNumberOfLines/2)
             {
                 if (m_intImageIndex % 2 == 1) // odd image
                 {
                     m_registeredTVScreen->renderImage(0);
                     if (m_rfRunning.m_enmModulation == ATV_AM)
                     {
                         m_fltAmpMin = m_fltEffMin;
                         m_fltAmpMax = m_fltEffMax;
                         m_fltAmpDelta = m_fltEffMax-m_fltEffMin;
                         if(m_fltAmpDelta<=0.0)
{
                             m_fltAmpDelta=1.0f;
                         }
                         //Reset extrema
                         m_fltEffMin = 2000000.0f;
                         m_fltEffMax = -2000000.0f;
                     }
                     m_intRowIndex = 1;
                 }
                 else
                 {
                     m_intRowIndex = 0;
                 }
                 m_registeredTVScreen->selectRow(m_intRowIndex - m_intNumberOfSyncLines);
                 m_intLineIndex = 0;
                 m_intImageIndex++;
             }
         }
     }
processHSkip()
void ATVDemod::processHSkip (float & fltVal, int & intVal) inline private
Definition at line 510 of file atvdemod.h.
References ATV_AM, ATV_LSB, ATV_USB, ATVDemod::ATVConfig::m_blnHSync, ATVDemod::ATVRFConfig::m_enmModulation, m_fltEffMax, m_fltEffMin, ATVDemod::ATVConfig::m_fltVoltLevelSynchroBlack, ATVDemod::ATVConfig::m_fltVoltLevelSynchroTop, m_intAvgColIndex, m_intColIndex, ATVDemod::ATVConfigPrivate::m_intNumberSamplePerLine, m_intNumberSamplePerTop, TVScreen::renderImage(), TVScreen::selectRow(), and TVScreen::setDataColor().
Referenced by demod().
     {
         m_registeredTVScreen->setDataColor(m_intColIndex - m_intNumberSaplesPerHSync + m_intNumberSamplePerTop, intVal, intVal, intVal);
         // Horizontal Synchro detection
         // Floor Detection 0
         if (fltVal < m_running.m_fltVoltLevelSynchroTop)
         {
             m_intSynchroPoints++;
         }
         // Black detection 0.3
         else if (fltVal > m_running.m_fltVoltLevelSynchroBlack)
         {
             m_intSynchroPoints = 0;
         }
         // sync pulse
         m_blnSynchroDetected = (m_intSynchroPoints == m_intNumberSamplePerTop);
         if (m_blnSynchroDetected)
         {
             if (m_intSampleIndex >= (3 * m_runningPrivate.m_intNumberSamplePerLine)/2) // first after skip
             {
                 //qDebug("VSync: %d %d %d", m_intColIndex, m_intSampleIndex, m_intLineIndex);
                 m_intAvgColIndex = m_intColIndex;
                 m_registeredTVScreen->renderImage(0);
                 m_intImageIndex++;
                 m_intLineIndex = 0;
                 m_intRowIndex = 0;
             }
             m_intSampleIndex = 0;
         }
         else
         {
             m_intSampleIndex++;
         }
         if (m_intColIndex < m_runningPrivate.m_intNumberSamplePerLine + m_intNumberSamplePerTop - 1)
         {
             m_intColIndex++;
         }
         else
         {
             if (m_running.m_blnHSync && (m_intLineIndex == 0))
             {
                 //qDebug("HCorr: %d", m_intAvgColIndex);
                 m_intColIndex = m_intNumberSamplePerTop + (m_runningPrivate.m_intNumberSamplePerLine - m_intAvgColIndex)/2; // amortizing factor 1/2
             }
             else
             {
                 m_intColIndex = m_intNumberSamplePerTop;
             }
             if ((m_rfRunning.m_enmModulation == ATV_AM)
                 || (m_rfRunning.m_enmModulation == ATV_USB)
                 || (m_rfRunning.m_enmModulation == ATV_LSB))
             {
                 m_fltAmpMin = m_fltEffMin;
                 m_fltAmpMax = m_fltEffMax;
                 m_fltAmpDelta = m_fltEffMax-m_fltEffMin;
                 if(m_fltAmpDelta<=0.0)
                 {
                     m_fltAmpDelta=1.0f;
                 }
                 //Reset extrema
                 m_fltEffMin = 2000000.0f;
                 m_fltEffMax = -2000000.0f;
             }
             m_registeredTVScreen->selectRow(m_intRowIndex);
             m_intLineIndex++;
             m_intRowIndex++;
         }
     }
serialize()
virtual QByteArray ATVDemod::serialize () const inline virtual
Implements ChannelAPI.
Definition at line 233 of file atvdemod.h.
 { return QByteArray(); }
setScopeSink()
void ATVDemod::setScopeSink (BasebandSampleSink * scopeSink) inline
Definition at line 198 of file atvdemod.h.
References configure(), configureRF(), feed(), handleMessage(), m_scopeSink, start(), and stop().
Referenced by ATVDemodGUI::ATVDemodGUI().
 { m_scopeSink = scopeSink; }
setTVScreen()
void ATVDemod::setTVScreen (TVScreen * objScreen)
set by the GUI
Definition at line 109 of file atvdemod.cpp.
References m_registeredTVScreen.
Referenced by ATVDemodGUI::ATVDemodGUI(), and getStreamCenterFrequency().
 {
     m_registeredTVScreen = objScreen;
 }
start()
void ATVDemod::start () virtual
Implements BasebandSampleSink.
Definition at line 448 of file atvdemod.cpp.
Referenced by setScopeSink().
 {
     //m_objTimer.start();
 }
stop()
void ATVDemod::stop () virtual
Implements BasebandSampleSink.
Definition at line 453 of file atvdemod.cpp.
Referenced by setScopeSink().
 {
 }
Member Data Documentation
m_bfoFilter
SecondOrderRecursiveFilter ATVDemod::m_bfoFilter private
Definition at line 476 of file atvdemod.h.
Referenced by applySettings(), and demod().
m_bfoPLL
SimplePhaseLock ATVDemod::m_bfoPLL private
Definition at line 475 of file atvdemod.h.
Referenced by applySettings(), demod(), and getBFOLocked().
m_blnSynchroDetected
bool ATVDemod::m_blnSynchroDetected private
Definition at line 445 of file atvdemod.h.
m_blnVerticalSynchroDetected
bool ATVDemod::m_blnVerticalSynchroDetected private
Definition at line 446 of file atvdemod.h.
m_channelId
const QString ATVDemod::m_channelId = "ATVDemod" static
Definition at line 253 of file atvdemod.h.
Referenced by ATVDemod(), and ATVDemodPlugin::initPlugin().
m_channelIdURI
const QString ATVDemod::m_channelIdURI = "sdrangel.channel.demodatv" static
Definition at line 252 of file atvdemod.h.
Referenced by ATVDemodGUI::ATVDemodGUI(), and ATVDemodPlugin::initPlugin().
m_channelizer
DownChannelizer* ATVDemod::m_channelizer private
Definition at line 420 of file atvdemod.h.
Referenced by ATVDemod(), channelSampleRateChanged(), handleMessage(), and ~ATVDemod().
m_config
ATVConfig ATVDemod::m_config private
Definition at line 495 of file atvdemod.h.
Referenced by applySettings(), applyStandard(), and handleMessage().
m_configPrivate
ATVConfigPrivate ATVDemod::m_configPrivate private
Definition at line 501 of file atvdemod.h.
Referenced by applySettings().
m_deviceAPI
DeviceAPI* ATVDemod::m_deviceAPI private
Definition at line 418 of file atvdemod.h.
Referenced by ATVDemod(), and ~ATVDemod().
m_DSBFilter
fftfilt* ATVDemod::m_DSBFilter private
Definition at line 484 of file atvdemod.h.
Referenced by applySettings(), ATVDemod(), demod(), and ~ATVDemod().
m_DSBFilterBuffer
Complex* ATVDemod::m_DSBFilterBuffer private
Definition at line 485 of file atvdemod.h.
Referenced by applySettings(), ATVDemod(), demod(), and ~ATVDemod().
m_DSBFilterBufferIndex
int ATVDemod::m_DSBFilterBufferIndex private
Definition at line 486 of file atvdemod.h.
Referenced by applySettings(), and demod().
m_fltAmpDelta
float ATVDemod::m_fltAmpDelta private
Definition at line 455 of file atvdemod.h.
Referenced by demod().
m_fltAmpLineAverage
float ATVDemod::m_fltAmpLineAverage private
Definition at line 448 of file atvdemod.h.
Referenced by demod().
m_fltAmpMax
float ATVDemod::m_fltAmpMax private
Definition at line 454 of file atvdemod.h.
m_fltAmpMin
float ATVDemod::m_fltAmpMin private
Definition at line 453 of file atvdemod.h.
Referenced by demod().
m_fltBufferI
float ATVDemod::m_fltBufferI[6] private
Definition at line 457 of file atvdemod.h.
Referenced by ATVDemod(), and demod().
m_fltBufferQ
float ATVDemod::m_fltBufferQ[6] private
Definition at line 458 of file atvdemod.h.
Referenced by ATVDemod(), and demod().
m_fltEffMax
float ATVDemod::m_fltEffMax private
Definition at line 451 of file atvdemod.h.
Referenced by demod(), processClassic(), and processHSkip().
m_fltEffMin
float ATVDemod::m_fltEffMin private
Definition at line 450 of file atvdemod.h.
Referenced by demod(), processClassic(), and processHSkip().
m_intAvgColIndex
int ATVDemod::m_intAvgColIndex private
Definition at line 466 of file atvdemod.h.
Referenced by processHSkip().
m_intColIndex
int ATVDemod::m_intColIndex private
Definition at line 460 of file atvdemod.h.
Referenced by applySettings(), and processHSkip().
m_interleaved
bool ATVDemod::m_interleaved private
interleaved image
Definition at line 438 of file atvdemod.h.
Referenced by applyStandard(), and ATVDemod().
m_interpolator
Interpolator ATVDemod::m_interpolator private
Definition at line 479 of file atvdemod.h.
Referenced by applySettings(), and feed().
m_interpolatorDistance
Real ATVDemod::m_interpolatorDistance private
Definition at line 480 of file atvdemod.h.
Referenced by applySettings(), and feed().
m_interpolatorDistanceRemain
Real ATVDemod::m_interpolatorDistanceRemain private
Definition at line 481 of file atvdemod.h.
Referenced by applySettings(), and feed().
m_intImageIndex
int ATVDemod::m_intImageIndex private
Definition at line 442 of file atvdemod.h.
Referenced by applySettings().
m_intLineIndex
int ATVDemod::m_intLineIndex private
Definition at line 463 of file atvdemod.h.
m_intNumberOfBlackLines
int ATVDemod::m_intNumberOfBlackLines private
this is the total number of lines not part of the image and is used for vertical screen size
Definition at line 434 of file atvdemod.h.
Referenced by applySettings(), and applyStandard().
m_intNumberOfEqLines
int ATVDemod::m_intNumberOfEqLines private
number of equalizing lines both whole and partial
Definition at line 435 of file atvdemod.h.
Referenced by applyStandard().
m_intNumberOfLines
int ATVDemod::m_intNumberOfLines private
Definition at line 432 of file atvdemod.h.
Referenced by applySettings(), and ATVDemod().
m_intNumberOfSyncLines
int ATVDemod::m_intNumberOfSyncLines private
this is the number of non displayable lines at the start of a frame. First displayable row comes next.
Definition at line 433 of file atvdemod.h.
Referenced by applyStandard().
m_intNumberSamplePerLineSignals
int ATVDemod::m_intNumberSamplePerLineSignals private
number of samples in the non image part of the line (signals)
Definition at line 436 of file atvdemod.h.
Referenced by applySettings(), and applyStandard().
m_intNumberSamplePerTop
int ATVDemod::m_intNumberSamplePerTop private
Definition at line 431 of file atvdemod.h.
Referenced by applySettings(), processClassic(), and processHSkip().
m_intNumberSaplesPerHSync
int ATVDemod::m_intNumberSaplesPerHSync private
number of samples per horizontal synchronization pattern (pulse + back porch)
Definition at line 437 of file atvdemod.h.
Referenced by applyStandard().
m_intRowIndex
int ATVDemod::m_intRowIndex private
Definition at line 462 of file atvdemod.h.
Referenced by applySettings().
m_intSampleIndex
int ATVDemod::m_intSampleIndex private
Definition at line 461 of file atvdemod.h.
m_intSynchroPoints
int ATVDemod::m_intSynchroPoints private
Definition at line 443 of file atvdemod.h.
Referenced by ATVDemod().
m_nco
NCO ATVDemod::m_nco private
Definition at line 474 of file atvdemod.h.
Referenced by applySettings(), and feed().
m_objAvgColIndex
AvgExpInt ATVDemod::m_objAvgColIndex private
Definition at line 465 of file atvdemod.h.
m_objMagSqAverage
MovingAverageUtil<double, double, 32> ATVDemod::m_objMagSqAverage private
Definition at line 472 of file atvdemod.h.
Referenced by demod(), and getMagSq().
m_objPhaseDiscri
PhaseDiscriminators ATVDemod::m_objPhaseDiscri private
Definition at line 490 of file atvdemod.h.
Referenced by applySettings(), ATVDemod(), and demod().
m_objSettingsMutex
QMutex ATVDemod::m_objSettingsMutex private
Definition at line 503 of file atvdemod.h.
Referenced by applySettings(), and feed().
m_registeredTVScreen
TVScreen* ATVDemod::m_registeredTVScreen private
Definition at line 428 of file atvdemod.h.
Referenced by applySettings(), demod(), and setTVScreen().
m_rfConfig
ATVRFConfig ATVDemod::m_rfConfig private
Definition at line 498 of file atvdemod.h.
Referenced by applySettings(), ATVDemod(), and handleMessage().
m_rfRunning
ATVRFConfig ATVDemod::m_rfRunning private
Definition at line 497 of file atvdemod.h.
Referenced by applySettings(), demod(), feed(), getBFOLocked(), getCenterFrequency(), getEffectiveSampleRate(), and getStreamCenterFrequency().
m_running
ATVConfig ATVDemod::m_running private
Definition at line 494 of file atvdemod.h.
Referenced by applySettings(), demod(), feed(), getEffectiveSampleRate(), and getSampleRate().
m_runningPrivate
ATVConfigPrivate ATVDemod::m_runningPrivate private
Definition at line 500 of file atvdemod.h.
Referenced by applySettings(), and getEffectiveSampleRate().
m_sampleBuffer
SampleVector ATVDemod::m_sampleBuffer private
Definition at line 468 of file atvdemod.h.
m_scopeSampleBuffer
SampleVector ATVDemod::m_scopeSampleBuffer private
Definition at line 425 of file atvdemod.h.
Referenced by demod(), and feed().
m_scopeSink
BasebandSampleSink* ATVDemod::m_scopeSink private
Definition at line 424 of file atvdemod.h.
Referenced by demod(), feed(), handleMessage(), and setScopeSink().
m_ssbFftLen
const int ATVDemod::m_ssbFftLen = 1024 static private
Definition at line 487 of file atvdemod.h.
Referenced by applySettings(), and ATVDemod().
m_threadedChannelizer
ThreadedBasebandSampleSink* ATVDemod::m_threadedChannelizer private
Definition at line 419 of file atvdemod.h.
Referenced by ATVDemod(), and ~ATVDemod().
The documentation for this class was generated from the following files:
plugins/channelrx/demodatv/atvdemod.h
plugins/channelrx/demodatv/atvdemod.cpp