SDRAngel: SamplingDeviceDialog Class Reference
SamplingDeviceDialog Class Reference
#include <samplingdevicedialog.h>
Inherits QDialog.
Public Member Functions
SamplingDeviceDialog (int deviceType, int deviceTabIndex, QWidget *parent=0)
~SamplingDeviceDialog ()
int getSelectedDeviceIndex () const
Private Slots
void accept ()
Private Attributes
Ui::SamplingDeviceDialog * ui
int m_deviceType
int m_deviceTabIndex
int m_selectedDeviceIndex
std::vector< int > m_deviceIndexes
Detailed Description
Definition at line 34 of file samplingdevicedialog.h.
Constructor & Destructor Documentation
SamplingDeviceDialog()
SamplingDeviceDialog::SamplingDeviceDialog (int deviceType, int deviceTabIndex, QWidget * parent = 0) explicit
Definition at line 27 of file samplingdevicedialog.cpp.
References DeviceEnumerator::instance(), DeviceEnumerator::listMIMODeviceNames(), DeviceEnumerator::listRxDeviceNames(), DeviceEnumerator::listTxDeviceNames(), m_deviceIndexes, m_deviceType, and ui.
                                                                                               :
     QDialog(parent),
     ui(new Ui::SamplingDeviceDialog),
     m_deviceType(deviceType),
     m_deviceTabIndex(deviceTabIndex),
     m_selectedDeviceIndex(-1)
 {
     ui->setupUi(this);
     QList<QString> deviceDisplayNames;
     if (m_deviceType == 0) { // Single Rx
         DeviceEnumerator::instance()->listRxDeviceNames(deviceDisplayNames, m_deviceIndexes);
     } else if (m_deviceType == 1) { // Single Tx
         DeviceEnumerator::instance()->listTxDeviceNames(deviceDisplayNames, m_deviceIndexes);
     } else if (m_deviceType == 2) { // MIMO
         DeviceEnumerator::instance()->listMIMODeviceNames(deviceDisplayNames, m_deviceIndexes);
     }
     QStringList devicesNamesList(deviceDisplayNames);
     ui->deviceSelect->addItems(devicesNamesList);
 }
~SamplingDeviceDialog()
SamplingDeviceDialog::~SamplingDeviceDialog ()
Definition at line 50 of file samplingdevicedialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
accept
void SamplingDeviceDialog::accept () private slot
Definition at line 55 of file samplingdevicedialog.cpp.
References DeviceEnumerator::changeMIMOSelection(), DeviceEnumerator::changeRxSelection(), DeviceEnumerator::changeTxSelection(), DeviceEnumerator::instance(), m_deviceIndexes, m_deviceTabIndex, m_deviceType, m_selectedDeviceIndex, and ui.
 {
     m_selectedDeviceIndex = m_deviceIndexes[ui->deviceSelect->currentIndex()];
     if (m_deviceType == 0) { // Single Rx
         DeviceEnumerator::instance()->changeRxSelection(m_deviceTabIndex, m_selectedDeviceIndex);
     } else if (m_deviceType == 1) { // Single Tx
         DeviceEnumerator::instance()->changeTxSelection(m_deviceTabIndex, m_selectedDeviceIndex);
     } else if (m_deviceType == 2) { // MIMO
         DeviceEnumerator::instance()->changeMIMOSelection(m_deviceTabIndex, m_selectedDeviceIndex);
     }
     QDialog::accept();
 }
getSelectedDeviceIndex()
int SamplingDeviceDialog::getSelectedDeviceIndex () const inline
Definition at line 40 of file samplingdevicedialog.h.
Referenced by SamplingDeviceControl::on_deviceChange_clicked().
 { return m_selectedDeviceIndex; }
Member Data Documentation
m_deviceIndexes
std::vector<int> SamplingDeviceDialog::m_deviceIndexes private
Definition at line 47 of file samplingdevicedialog.h.
Referenced by accept(), and SamplingDeviceDialog().
m_deviceTabIndex
int SamplingDeviceDialog::m_deviceTabIndex private
Definition at line 45 of file samplingdevicedialog.h.
Referenced by accept().
m_deviceType
int SamplingDeviceDialog::m_deviceType private
Definition at line 44 of file samplingdevicedialog.h.
Referenced by accept(), and SamplingDeviceDialog().
m_selectedDeviceIndex
int SamplingDeviceDialog::m_selectedDeviceIndex private
Definition at line 46 of file samplingdevicedialog.h.
Referenced by accept().
ui
Ui::SamplingDeviceDialog* SamplingDeviceDialog::ui private
Definition at line 43 of file samplingdevicedialog.h.
Referenced by accept(), SamplingDeviceDialog(), and ~SamplingDeviceDialog().
The documentation for this class was generated from the following files:
sdrgui/gui/samplingdevicedialog.h
sdrgui/gui/samplingdevicedialog.cpp