SDRAngel: FileSinkOutput::MsgStartStop Class Reference
FileSinkOutput::MsgStartStop Class Reference
#include <filesinkoutput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 58 of file filesinkoutput.h.
Constructor & Destructor Documentation
MsgStartStop()
FileSinkOutput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 71 of file filesinkoutput.h.
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* FileSinkOutput::MsgStartStop::create (bool startStop) inline static
Definition at line 64 of file filesinkoutput.h.
Referenced by FileSinkGui::on_startStop_toggled(), and FileSinkOutput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool FileSinkOutput::MsgStartStop::getStartStop () const inline
Definition at line 62 of file filesinkoutput.h.
Referenced by FileSinkGui::handleMessage(), and FileSinkOutput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool FileSinkOutput::MsgStartStop::m_startStop protected
Definition at line 69 of file filesinkoutput.h.
The documentation for this class was generated from the following file:
plugins/samplesink/filesink/filesinkoutput.h