SDRAngel: plugins/channelrx/demoddatv/datvdemod.h File Reference
datvdemod.h File Reference
#include "leansdr/framework.h"
#include "leansdr/generic.h"
#include "leansdr/dvb.h"
#include "leansdr/filtergen.h"
#include "leansdr/hdlc.h"
#include "leansdr/iess.h"
#include "datvconstellation.h"
#include "datvdvbs2constellation.h"
#include "datvvideoplayer.h"
#include "datvideostream.h"
#include "datvudpstream.h"
#include "datvideorender.h"
#include "datvdemodsettings.h"
#include "channel/channelapi.h"
#include "dsp/basebandsamplesink.h"
#include "dsp/devicesamplesource.h"
#include "dsp/dspcommands.h"
#include "dsp/downchannelizer.h"
#include "dsp/fftfilt.h"
#include "dsp/nco.h"
#include "dsp/interpolator.h"
#include "dsp/movingaverage.h"
#include "dsp/agc.h"
#include "audio/audiofifo.h"
#include "util/message.h"
#include "util/movingaverage.h"
#include <QMutex>
Classes
struct config
class DATVDemod
class DATVDemod::MsgConfigureChannelizer
class DATVDemod::MsgConfigureDATVDemod
class DATVDemod::MsgReportModcodCstlnChange
Macros
#define rfFilterFftLength 1024
Functions
int decimation (float Fin, float Fout)
Macro Definition Documentation
rfFilterFftLength
#define rfFilterFftLength 1024
Definition at line 27 of file datvdemod.h.
Referenced by DATVDemod::DATVDemod(), and WFMDemod::WFMDemod().
Function Documentation
decimation()
int decimation (float Fin, float Fout) inline
Definition at line 66 of file datvdemod.h.
References leansdr::max().
Referenced by DATVDemod::InitDATVFramework(), DATVDemod::InitDATVS2Framework(), leansdr::file_printer< T >::run(), AudioResampler::setDecimation(), AudioNetSink::setDecimation(), and AudioOutput::setOnExit().
 { int d = Fin / Fout; return std::max(d, 1); }