SDRAngel: GLScopeGUI Class Reference
GLScopeGUI Class Reference
#include <glscopegui.h>
Classes
class MainUIBlocker
class TraceUIBlocker
class TrigUIBlocker
Public Types
enum DisplayMode {
DisplayXYH, DisplayXYV, DisplayX, DisplayY,
DisplayPol
}
Public Member Functions
GLScopeGUI (QWidget *parent=0)
~GLScopeGUI ()
void setBuddies (MessageQueue *messageQueue, ScopeVis *scopeVis, GLScope *glScope)
void setSampleRate (int sampleRate)
void resetToDefaults ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
bool handleMessage (Message *message)
void setDisplayMode (DisplayMode displayMode)
void setTraceIntensity (int value)
void setGridIntensity (int value)
void setTimeBase (int step)
void setTimeOffset (int step)
void setTraceLength (int step)
void setPreTrigger (int step)
void changeTrace (int traceIndex, const ScopeVis::TraceData &traceData)
void addTrace (const ScopeVis::TraceData &traceData)
void focusOnTrace (int traceIndex)
void changeTrigger (int triggerIndex, const ScopeVis::TriggerData &triggerData)
void addTrigger (const ScopeVis::TriggerData &triggerData)
void focusOnTrigger (int triggerIndex)
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Private Slots
void on_scope_sampleRateChanged (int value)
void on_scope_traceSizeChanged (uint32_t value)
void on_scope_preTriggerChanged (uint32_t value)
void on_onlyX_toggled (bool checked)
void on_onlyY_toggled (bool checked)
void on_horizontalXY_toggled (bool checked)
void on_verticalXY_toggled (bool checked)
void on_polar_toggled (bool checked)
void on_polarPoints_toggled (bool checked)
void on_traceIntensity_valueChanged (int value)
void on_gridIntensity_valueChanged (int value)
void on_time_valueChanged (int value)
void on_timeOfs_valueChanged (int value)
void on_traceLen_valueChanged (int value)
void on_trace_valueChanged (int value)
void on_traceAdd_clicked (bool checked)
void on_traceDel_clicked (bool checked)
void on_traceUp_clicked (bool checked)
void on_traceDown_clicked (bool checked)
void on_traceMode_currentIndexChanged (int index)
void on_amp_valueChanged (int value)
void on_ofsCoarse_valueChanged (int value)
void on_ofsFine_valueChanged (int value)
void on_traceDelayCoarse_valueChanged (int value)
void on_traceDelayFine_valueChanged (int value)
void on_traceView_toggled (bool checked)
void on_traceColor_clicked ()
void on_memorySave_clicked (bool checked)
void on_memoryLoad_clicked (bool checked)
void on_mem_valueChanged (int value)
void on_trig_valueChanged (int value)
void on_trigAdd_clicked (bool checked)
void on_trigDel_clicked (bool checked)
void on_trigUp_clicked (bool checked)
void on_trigDown_clicked (bool checked)
void on_trigMode_currentIndexChanged (int index)
void on_trigCount_valueChanged (int value)
void on_trigPos_toggled (bool checked)
void on_trigNeg_toggled (bool checked)
void on_trigBoth_toggled (bool checked)
void on_trigHoldoff_valueChanged (int value)
void on_trigLevelCoarse_valueChanged (int value)
void on_trigLevelFine_valueChanged (int value)
void on_trigDelayCoarse_valueChanged (int value)
void on_trigDelayFine_valueChanged (int value)
void on_trigPre_valueChanged (int value)
void on_trigColor_clicked ()
void on_trigOneShot_toggled (bool checked)
void on_freerun_toggled (bool checked)
Private Member Functions
void applySettings ()
void setTraceIndexDisplay ()
void setTimeScaleDisplay ()
void setTraceLenDisplay ()
void setTimeOfsDisplay ()
void setAmpScaleDisplay ()
void setAmpOfsDisplay ()
void setTraceDelayDisplay ()
void setTrigIndexDisplay ()
void setTrigCountDisplay ()
void setTrigLevelDisplay ()
void setTrigDelayDisplay ()
void setTrigPreDisplay ()
void changeCurrentTrace ()
void changeCurrentTrigger ()
void fillTraceData (ScopeVis::TraceData &traceData)
void fillTriggerData (ScopeVis::TriggerData &triggerData)
void setTriggerUI (const ScopeVis::TriggerData &triggerData)
void setTraceUI (const ScopeVis::TraceData &traceData)
void fillProjectionCombo (QComboBox *comboBox)
void disableLiveMode (bool disable)
Private Attributes
Ui::GLScopeGUI * ui
MessageQueue * m_messageQueue
ScopeVis * m_scopeVis
GLScope * m_glScope
int m_sampleRate
int m_timeBase
int m_timeOffset
int m_traceLenMult
QColor m_focusedTraceColor
QColor m_focusedTriggerColor
Static Private Attributes
static const double amps [27]
Detailed Description
Definition at line 38 of file glscopegui.h.
Member Enumeration Documentation
DisplayMode
enum GLScopeGUI::DisplayMode
Enumerator
DisplayXYH
DisplayXYV
DisplayX
DisplayY
DisplayPol
Definition at line 42 of file glscopegui.h.
                      {
         DisplayXYH,
         DisplayXYV,
         DisplayX,
         DisplayY,
         DisplayPol
     };
Constructor & Destructor Documentation
GLScopeGUI()
GLScopeGUI::GLScopeGUI (QWidget * parent = 0) explicit
Definition at line 40 of file glscopegui.cpp.
References m_focusedTraceColor, m_focusedTriggerColor, ScopeVis::m_nbTraceMemories, ScopeVis::m_traceChunkSize, and ui.
                                       :
     QWidget(parent),
     ui(new Ui::GLScopeGUI),
     m_messageQueue(0),
     m_scopeVis(0),
     m_glScope(0),
     m_sampleRate(0),
     m_timeBase(1),
     m_timeOffset(0),
     m_traceLenMult(1)
 {
     qDebug("GLScopeGUI::GLScopeGUI");
     setEnabled(false);
     ui->setupUi(this);
     ui->trigDelayFine->setMaximum(ScopeVis::m_traceChunkSize / 10.0);
     ui->traceColor->setStyleSheet("QLabel { background-color : rgb(255,255,64); }");
     m_focusedTraceColor.setRgb(255,255,64);
     ui->trigColor->setStyleSheet("QLabel { background-color : rgb(0,255,0); }");
     m_focusedTriggerColor.setRgb(0,255,0);
     ui->traceText->setText("X");
     ui->mem->setMaximum(ScopeVis::m_nbTraceMemories - 1);
 }
~GLScopeGUI()
GLScopeGUI::~GLScopeGUI ()
Definition at line 63 of file glscopegui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
addTrace()
void GLScopeGUI::addTrace (const ScopeVis::TraceData & traceData)
Definition at line 1657 of file glscopegui.cpp.
References ScopeVis::addTrace(), m_scopeVis, and ui.
Referenced by on_traceAdd_clicked().
 {
     if (ui->trace->maximum() < 3)
     {
         if (ui->trace->value() == 0)
         {
             ui->onlyY->setEnabled(true);
             ui->horizontalXY->setEnabled(true);
             ui->verticalXY->setEnabled(true);
             ui->polar->setEnabled(true);
         }
         m_scopeVis->addTrace(traceData);
         ui->trace->setMaximum(ui->trace->maximum() + 1);
     }
 }
addTrigger()
void GLScopeGUI::addTrigger (const ScopeVis::TriggerData & triggerData)
Definition at line 1684 of file glscopegui.cpp.
References ScopeVis::addTrigger(), m_scopeVis, and ui.
Referenced by on_trigAdd_clicked().
 {
     if (ui->trig->maximum() < 9)
     {
         m_scopeVis->addTrigger(triggerData);
         ui->trig->setMaximum(ui->trig->maximum() + 1);
     }
 }
applySettings()
void GLScopeGUI::applySettings () private
Definition at line 1460 of file glscopegui.cpp.
 {
 }
changeCurrentTrace()
void GLScopeGUI::changeCurrentTrace () private
Definition at line 1289 of file glscopegui.cpp.
References ScopeVis::changeTrace(), fillTraceData(), m_scopeVis, and ui.
Referenced by on_amp_valueChanged(), on_ofsCoarse_valueChanged(), on_ofsFine_valueChanged(), on_traceColor_clicked(), on_traceDel_clicked(), on_traceDelayCoarse_valueChanged(), on_traceDelayFine_valueChanged(), on_traceMode_currentIndexChanged(), and on_traceView_toggled().
 {
     ScopeVis::TraceData traceData;
     fillTraceData(traceData);
     uint32_t currentTraceIndex = ui->trace->value();
     m_scopeVis->changeTrace(traceData, currentTraceIndex);
 }
changeCurrentTrigger()
void GLScopeGUI::changeCurrentTrigger () private
Definition at line 1297 of file glscopegui.cpp.
References ScopeVis::changeTrigger(), fillTriggerData(), m_scopeVis, and ui.
Referenced by on_trigBoth_toggled(), on_trigColor_clicked(), on_trigCount_valueChanged(), on_trigDelayCoarse_valueChanged(), on_trigDelayFine_valueChanged(), on_trigHoldoff_valueChanged(), on_trigLevelCoarse_valueChanged(), on_trigLevelFine_valueChanged(), on_trigMode_currentIndexChanged(), on_trigNeg_toggled(), and on_trigPos_toggled().
 {
     ScopeVis::TriggerData triggerData;
     fillTriggerData(triggerData);
     uint32_t currentTriggerIndex = ui->trig->value();
     m_scopeVis->changeTrigger(triggerData, currentTriggerIndex);
 }
changeTrace()
void GLScopeGUI::changeTrace (int traceIndex, const ScopeVis::TraceData & traceData)
Definition at line 1652 of file glscopegui.cpp.
References ScopeVis::changeTrace(), and m_scopeVis.
 {
     m_scopeVis->changeTrace(traceData, traceIndex);
 }
changeTrigger()
void GLScopeGUI::changeTrigger (int triggerIndex, const ScopeVis::TriggerData & triggerData)
Definition at line 1679 of file glscopegui.cpp.
References ScopeVis::changeTrigger(), and m_scopeVis.
 {
     m_scopeVis->changeTrigger(triggerData, triggerIndex);
 }
deserialize()
bool GLScopeGUI::deserialize (const QByteArray & data) virtual
Implements Serializable.
Definition at line 230 of file glscopegui.cpp.
References ScopeVis::addTrace(), ScopeVis::addTrigger(), arg(), ScopeVis::changeTrace(), ScopeVis::changeTrigger(), GLScope::DisplayPol, GLScope::DisplayX, GLScope::DisplayXYH, GLScope::DisplayXYV, GLScope::DisplayY, fillTraceData(), fillTriggerData(), GLScope::getDisplayMode(), ScopeVis::getNbTriggers(), ScopeVis::getTracesData(), SimpleDeserializer::getVersion(), SimpleDeserializer::isValid(), m_focusedTraceColor, m_focusedTriggerColor, m_glScope, m_scopeVis, SimpleDeserializer::readBool(), SimpleDeserializer::readFloat(), SimpleDeserializer::readS32(), SimpleDeserializer::readU32(), ScopeVis::removeTrace(), ScopeVis::removeTrigger(), resetToDefaults(), setAmpOfsDisplay(), setAmpScaleDisplay(), GLScope::setDisplayMode(), GLScope::setFocusedTraceIndex(), GLScope::setFocusedTriggerData(), setTraceDelayDisplay(), setTraceIndexDisplay(), setTrigCountDisplay(), setTrigDelayDisplay(), setTrigIndexDisplay(), setTrigLevelDisplay(), setTrigPreDisplay(), and ui.
 {
     qDebug("GLScopeGUI::deserialize");
     SimpleDeserializer d(data);
     if(!d.isValid()) {
         resetToDefaults();
         return false;
     }
     if(d.getVersion() == 1)
     {
         TraceUIBlocker traceUIBlocker(ui);
         TrigUIBlocker trigUIBlocker(ui);
         int intValue;
         uint32_t uintValue;
         bool boolValue;
         ui->onlyX->setEnabled(false);
         ui->onlyY->setEnabled(false);
         ui->horizontalXY->setEnabled(false);
         ui->verticalXY->setEnabled(false);
         ui->polar->setEnabled(false);
         ui->traceMode->setCurrentIndex(0);
         d.readS32(1, &intValue, (int) GLScope::DisplayX);
         m_glScope->setDisplayMode((GLScope::DisplayMode) intValue);
         ui->onlyX->setChecked(false);
         ui->onlyY->setChecked(false);
         ui->horizontalXY->setChecked(false);
         ui->verticalXY->setChecked(false);
         ui->polar->setChecked(false);
         switch (m_glScope->getDisplayMode())
         {
         case GLScope::DisplayY:
             ui->onlyY->setChecked(true);
             break;
         case GLScope::DisplayXYH:
             ui->horizontalXY->setChecked(true);
             break;
         case GLScope::DisplayXYV:
             ui->verticalXY->setChecked(true);
             break;
         case GLScope::DisplayPol:
             ui->polar->setChecked(true);
             break;
         case GLScope::DisplayX:
         default:
             ui->onlyX->setChecked(true);
             break;
         }
         d.readS32(2, &intValue, 50);
         ui->traceIntensity->setValue(intValue);
         d.readS32(3, &intValue, 10);
         ui->gridIntensity->setValue(intValue);
         d.readS32(4, &intValue, 1);
         ui->time->setValue(intValue);
         d.readS32(5, &intValue, 0);
         ui->timeOfs->setValue(intValue);
         d.readS32(6, &intValue, 1);
         ui->traceLen->setValue(intValue);
         // trace stuff
         uint32_t nbTracesSaved;
         d.readU32(10, &nbTracesSaved, 1);
         const std::vector<ScopeVis::TraceData>& tracesData = m_scopeVis->getTracesData();
         uint32_t iTrace = tracesData.size();
         qDebug("GLScopeGUI::deserialize: nbTracesSaved: %u tracesData.size(): %lu", nbTracesSaved, tracesData.size());
         while (iTrace > nbTracesSaved) // remove possible traces in excess
         {
             m_scopeVis->removeTrace(iTrace - 1);
             iTrace--;
         }
         for (iTrace = 0; iTrace < nbTracesSaved; iTrace++)
         {
             ScopeVis::TraceData traceData;
             float r, g, b;
             d.readS32(20 + 16*iTrace, &intValue, 0);
             ui->traceMode->setCurrentIndex(intValue);
             d.readU32(21 + 16*iTrace, &uintValue, 0);
             ui->amp->setValue(uintValue);
             d.readS32(22 + 16*iTrace, &intValue, 0);
             ui->ofsCoarse->setValue(intValue);
             d.readS32(23 + 16*iTrace, &intValue, 0);
             ui->ofsFine->setValue(intValue);
             d.readS32(24 + 16*iTrace, &intValue, 0);
             ui->traceDelayCoarse->setValue(intValue);
             d.readS32(25 + 16*iTrace, &intValue, 0);
             ui->traceDelayFine->setValue(intValue);
             d.readFloat(26 + 16*iTrace, &r, 1.0f);
             d.readFloat(27 + 16*iTrace, &g, 1.0f);
             d.readFloat(28 + 16*iTrace, &b, 1.0f);
             m_focusedTraceColor.setRgbF(r, g, b);
             fillTraceData(traceData);
             if (iTrace < tracesData.size()) // change existing traces
             {
                 m_scopeVis->changeTrace(traceData, iTrace);
             }
             else // add new traces
             {
                 m_scopeVis->addTrace(traceData);
             }
         }
         ui->trace->setMaximum(nbTracesSaved-1);
         ui->trace->setValue(nbTracesSaved-1);
         m_glScope->setFocusedTraceIndex(nbTracesSaved-1);
         int r,g,b,a;
         m_focusedTraceColor.getRgb(&r, &g, &b, &a);
         ui->traceColor->setStyleSheet(tr("QLabel { background-color : rgb(%1,%2,%3); }").arg(r).arg(g).arg(b));
         setTraceIndexDisplay();
         setAmpScaleDisplay();
         setAmpOfsDisplay();
         setTraceDelayDisplay();
         ui->onlyX->setEnabled(true);
         ui->onlyY->setEnabled(nbTracesSaved > 1);
         ui->horizontalXY->setEnabled(nbTracesSaved > 1);
         ui->verticalXY->setEnabled(nbTracesSaved > 1);
         ui->polar->setEnabled(nbTracesSaved > 1);
         // trigger stuff
         uint32_t nbTriggersSaved;
         d.readU32(200, &nbTriggersSaved, 1);
         uint32_t nbTriggers = m_scopeVis->getNbTriggers();
         uint32_t iTrigger = nbTriggers;
         d.readS32(201, &intValue, 0);
         ui->trigPre->setValue(intValue);
         qDebug("GLScopeGUI::deserialize: nbTriggersSaved: %u nbTriggers: %u", nbTriggersSaved, nbTriggers);
         while (iTrigger > nbTriggersSaved) // remove possible triggers in excess
         {
             m_scopeVis->removeTrigger(iTrigger - 1);
             iTrigger--;
         }
         for (iTrigger = 0; iTrigger < nbTriggersSaved; iTrigger++)
         {
             ScopeVis::TriggerData triggerData;
             float r, g, b;
             d.readS32(210 + 16*iTrigger, &intValue, 0);
             ui->trigMode->setCurrentIndex(intValue);
             d.readS32(211 + 16*iTrigger, &intValue, 1);
             ui->trigCount->setValue(intValue);
             d.readBool(212 + 16*iTrigger, &boolValue, true);
             ui->trigPos->setChecked(boolValue);
             d.readBool(213 + 16*iTrigger, &boolValue, false);
             ui->trigBoth->setChecked(boolValue);
             d.readS32(214 + 16*iTrigger, &intValue, 1);
             ui->trigLevelCoarse->setValue(intValue);
             d.readS32(215 + 16*iTrigger, &intValue, 1);
             ui->trigLevelFine->setValue(intValue);
             d.readS32(216 + 16*iTrigger, &intValue, 1);
             ui->trigDelayCoarse->setValue(intValue);
             d.readS32(217 + 16*iTrigger, &intValue, 1);
             ui->trigDelayFine->setValue(intValue);
             d.readFloat(218 + 16*iTrigger, &r, 1.0f);
             d.readFloat(219 + 16*iTrigger, &g, 1.0f);
             d.readFloat(220 + 16*iTrigger, &b, 1.0f);
             m_focusedTriggerColor.setRgbF(r, g, b);
             d.readU32(221 + 16*iTrigger, &uintValue, 1);
             ui->trigHoldoff->setValue(uintValue);
             ui->trigHoldoffText->setText(tr("%1").arg(uintValue));
             fillTriggerData(triggerData);
             if (iTrigger < nbTriggers) // change existing triggers
             {
                 m_scopeVis->changeTrigger(triggerData, iTrigger);
             }
             else // add new trigers
             {
                 m_scopeVis->addTrigger(triggerData);
             }
             if (iTrigger == nbTriggersSaved-1)
             {
                 m_glScope->setFocusedTriggerData(triggerData);
             }
         }
         ui->trig->setMaximum(nbTriggersSaved-1);
         ui->trig->setValue(nbTriggersSaved-1);
         m_focusedTriggerColor.getRgb(&r, &g, &b, &a);
         ui->trigColor->setStyleSheet(tr("QLabel { background-color : rgb(%1,%2,%3); }").arg(r).arg(g).arg(b));
         setTrigCountDisplay();
         setTrigDelayDisplay();
         setTrigIndexDisplay();
         setTrigLevelDisplay();
         setTrigPreDisplay();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
disableLiveMode()
void GLScopeGUI::disableLiveMode (bool disable) private
Definition at line 1320 of file glscopegui.cpp.
References ui.
Referenced by on_mem_valueChanged().
 {
     ui->traceLen->setEnabled(!disable);
     ui->trig->setEnabled(!disable);
     ui->trigAdd->setEnabled(!disable);
     ui->trigDel->setEnabled(!disable);
     ui->trigMode->setEnabled(!disable);
     ui->trigCount->setEnabled(!disable);
     ui->trigPos->setEnabled(!disable);
     ui->trigNeg->setEnabled(!disable);
     ui->trigBoth->setEnabled(!disable);
     ui->trigLevelCoarse->setEnabled(!disable);
     ui->trigLevelFine->setEnabled(!disable);
     ui->trigDelayCoarse->setEnabled(!disable);
     ui->trigDelayFine->setEnabled(!disable);
     ui->trigPre->setEnabled(!disable);
     ui->trigOneShot->setEnabled(!disable);
     ui->freerun->setEnabled(!disable);
     ui->memorySave->setEnabled(disable);
     ui->memoryLoad->setEnabled(disable);
 }
fillProjectionCombo()
void GLScopeGUI::fillProjectionCombo (QComboBox * comboBox) private
Definition at line 1305 of file glscopegui.cpp.
References Projector::Projection16PSK, Projector::Projection8PSK, Projector::ProjectionBPSK, Projector::ProjectionDPhase, Projector::ProjectionImag, Projector::ProjectionMagDB, Projector::ProjectionMagLin, Projector::ProjectionMagSq, Projector::ProjectionPhase, Projector::ProjectionQPSK, and Projector::ProjectionReal.
Referenced by setBuddies().
 {
     comboBox->addItem("Real", Projector::ProjectionReal);
     comboBox->addItem("Imag", Projector::ProjectionImag);
     comboBox->addItem("Mag", Projector::ProjectionMagLin);
     comboBox->addItem("MagSq", Projector::ProjectionMagSq);
     comboBox->addItem("MagdB", Projector::ProjectionMagDB);
     comboBox->addItem("Phi", Projector::ProjectionPhase);
     comboBox->addItem("dPhi", Projector::ProjectionDPhase);
     comboBox->addItem("BPSK", Projector::ProjectionBPSK);
     comboBox->addItem("QPSK", Projector::ProjectionQPSK);
     comboBox->addItem("8PSK", Projector::Projection8PSK);
     comboBox->addItem("16PSK", Projector::Projection16PSK);
 }
fillTraceData()
void GLScopeGUI::fillTraceData (ScopeVis::TraceData & traceData) private
Definition at line 1342 of file glscopegui.cpp.
References amps, ScopeVis::TraceData::m_amp, ScopeVis::TraceData::m_ampIndex, m_focusedTraceColor, ScopeVis::TraceData::m_hasTextOverlay, ScopeVis::TraceData::m_inputIndex, ScopeVis::TraceData::m_ofs, ScopeVis::TraceData::m_ofsCoarse, ScopeVis::TraceData::m_ofsFine, ScopeVis::TraceData::m_projectionType, ScopeVis::TraceData::m_textOverlay, ScopeVis::TraceData::m_traceDelay, ScopeVis::TraceData::m_traceDelayCoarse, ScopeVis::TraceData::m_traceDelayFine, ScopeVis::TraceData::m_viewTrace, Projector::ProjectionMagDB, Projector::ProjectionMagLin, Projector::ProjectionMagSq, ScopeVis::TraceData::setColor(), and ui.
Referenced by changeCurrentTrace(), deserialize(), on_traceAdd_clicked(), and setBuddies().
 {
     traceData.m_projectionType = (Projector::ProjectionType) ui->traceMode->currentIndex();
     traceData.m_hasTextOverlay = (traceData.m_projectionType == Projector::ProjectionMagDB) || (traceData.m_projectionType == Projector::ProjectionMagSq);
     traceData.m_textOverlay.clear();
     traceData.m_inputIndex = 0;
     traceData.m_amp = 0.2 / amps[ui->amp->value()];
     traceData.m_ampIndex = ui->amp->value();
     traceData.m_ofsCoarse = ui->ofsCoarse->value();
     traceData.m_ofsFine = ui->ofsFine->value();
     if ((traceData.m_projectionType == Projector::ProjectionMagLin)  || (traceData.m_projectionType == Projector::ProjectionMagSq)) {
         traceData.m_ofs = ((10.0 * ui->ofsCoarse->value()) + (ui->ofsFine->value() / 20.0)) / 2000.0f;
     } else {
         traceData.m_ofs = ((10.0 * ui->ofsCoarse->value()) + (ui->ofsFine->value() / 20.0)) / 1000.0f;
     }
     traceData.m_traceDelayCoarse = ui->traceDelayCoarse->value();
     traceData.m_traceDelayFine = ui->traceDelayFine->value();
     traceData.m_traceDelay = traceData.m_traceDelayCoarse * 100 + traceData.m_traceDelayFine;
     traceData.setColor(m_focusedTraceColor);
     traceData.m_viewTrace = ui->traceView->isChecked();
 }
fillTriggerData()
void GLScopeGUI::fillTriggerData (ScopeVis::TriggerData & triggerData) private
Definition at line 1367 of file glscopegui.cpp.
References m_focusedTriggerColor, ScopeVis::TriggerData::m_inputIndex, ScopeVis::TriggerData::m_projectionType, ScopeVis::m_traceChunkSize, m_traceLenMult, ScopeVis::TriggerData::m_triggerBothEdges, ScopeVis::TriggerData::m_triggerDelay, ScopeVis::TriggerData::m_triggerDelayCoarse, ScopeVis::TriggerData::m_triggerDelayFine, ScopeVis::TriggerData::m_triggerDelayMult, ScopeVis::TriggerData::m_triggerHoldoff, ScopeVis::TriggerData::m_triggerLevel, ScopeVis::TriggerData::m_triggerLevelCoarse, ScopeVis::TriggerData::m_triggerLevelFine, ScopeVis::TriggerData::m_triggerPositiveEdge, ScopeVis::TriggerData::m_triggerRepeat, ScopeVis::TriggerData::setColor(), and ui.
Referenced by changeCurrentTrigger(), deserialize(), on_trigAdd_clicked(), and setBuddies().
 {
     triggerData.m_projectionType = (Projector::ProjectionType) ui->trigMode->currentIndex();
     triggerData.m_inputIndex = 0;
     triggerData.m_triggerLevel = (ui->trigLevelCoarse->value() / 100.0) + (ui->trigLevelFine->value() / 50000.0);
     triggerData.m_triggerLevelCoarse = ui->trigLevelCoarse->value();
     triggerData.m_triggerLevelFine = ui->trigLevelFine->value();
     triggerData.m_triggerPositiveEdge = ui->trigPos->isChecked();
     triggerData.m_triggerBothEdges = ui->trigBoth->isChecked();
     triggerData.m_triggerHoldoff = ui->trigHoldoff->value();
     triggerData.m_triggerRepeat = ui->trigCount->value();
     triggerData.m_triggerDelayMult = ui->trigDelayCoarse->value() + ui->trigDelayFine->value() / (ScopeVis::m_traceChunkSize / 10.0);
     triggerData.m_triggerDelay = (int) (m_traceLenMult * ScopeVis::m_traceChunkSize * triggerData.m_triggerDelayMult);
     triggerData.m_triggerDelayCoarse = ui->trigDelayCoarse->value();
     triggerData.m_triggerDelayFine = ui->trigDelayFine->value();
     triggerData.setColor(m_focusedTriggerColor);
 }
focusOnTrace()
void GLScopeGUI::focusOnTrace (int traceIndex)
Definition at line 1674 of file glscopegui.cpp.
References on_trace_valueChanged().
 {
     on_trace_valueChanged(traceIndex);
 }
focusOnTrigger()
void GLScopeGUI::focusOnTrigger (int triggerIndex)
Definition at line 1693 of file glscopegui.cpp.
References on_trig_valueChanged().
 {
     on_trig_valueChanged(triggerIndex);
 }
handleMessage()
bool GLScopeGUI::handleMessage (Message * message)
Definition at line 1464 of file glscopegui.cpp.
 {
     (void) message;
     return false;
 }
on_amp_valueChanged
void GLScopeGUI::on_amp_valueChanged (int value) private slot
Definition at line 755 of file glscopegui.cpp.
References changeCurrentTrace(), and setAmpScaleDisplay().
 {
     (void) value;
     setAmpScaleDisplay();
     changeCurrentTrace();
 }
on_freerun_toggled
void GLScopeGUI::on_freerun_toggled (bool checked) private slot
Definition at line 986 of file glscopegui.cpp.
References ScopeVis::configure(), GLScope::getTraceSize(), m_glScope, m_scopeVis, m_timeBase, m_timeOffset, ScopeVis::m_traceChunkSize, m_traceLenMult, and ui.
 {
     if (checked)
     {
         ui->trigOneShot->setChecked(false);
         ui->trigOneShot->setEnabled(false);
     }
     else
     {
         ui->trigOneShot->setEnabled(true);
     }
     m_scopeVis->configure(m_traceLenMult*ScopeVis::m_traceChunkSize,
             m_timeBase,
             m_timeOffset*10,
             (uint32_t) (m_glScope->getTraceSize() * (ui->trigPre->value()/100.0f)),
             ui->freerun->isChecked());
 }
on_gridIntensity_valueChanged
void GLScopeGUI::on_gridIntensity_valueChanged (int value) private slot
Definition at line 550 of file glscopegui.cpp.
References arg(), m_glScope, GLScope::setDisplayGridIntensity(), and ui.
 {
     ui->gridIntensity->setToolTip(QString("Grid intensity: %1").arg(value));
     m_glScope->setDisplayGridIntensity(value);
 }
on_horizontalXY_toggled
void GLScopeGUI::on_horizontalXY_toggled (bool checked) private slot
Definition at line 485 of file glscopegui.cpp.
References GLScope::DisplayXYH, m_glScope, GLScope::setDisplayMode(), and ui.
 {
     if (checked)
     {
         ui->onlyX->setChecked(false);
         ui->onlyY->setChecked(false);
         ui->verticalXY->setChecked(false);
         ui->polar->setChecked(false);
         m_glScope->setDisplayMode(GLScope::DisplayXYH);
     }
     else
     {
         if (!ui->onlyX->isChecked() && !ui->onlyY->isChecked() && !ui->verticalXY->isChecked() && !ui->polar->isChecked()) {
             ui->polar->setChecked(true);
         }
     }
 }
on_mem_valueChanged
void GLScopeGUI::on_mem_valueChanged (int value) private slot
Definition at line 869 of file glscopegui.cpp.
References disableLiveMode(), m_scopeVis, ScopeVis::setMemoryIndex(), and ui.
 {
     QString text;
     text.sprintf("%02d", value);
     ui->memText->setText(text);
     disableLiveMode(value > 0); // live / memory mode toggle
     m_scopeVis->setMemoryIndex(value);
 }
on_memoryLoad_clicked
void GLScopeGUI::on_memoryLoad_clicked (bool checked) private slot
Definition at line 841 of file glscopegui.cpp.
References arg(), ScopeVis::deserializeMemory(), and m_scopeVis.
 {
     (void) checked;
     qDebug("GLScopeGUI::on_memoryLoad_clicked");
     QString fileName = QFileDialog::getOpenFileName(this,
         tr("Open trace memory file"), ".", tr("Trace memory files (*.trcm)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "")
     {
         QFile exportFile(fileName);
         if (exportFile.open(QIODevice::ReadOnly | QIODevice::Text))
         {
             QByteArray base64Str;
             QTextStream instream(&exportFile);
             instream >> base64Str;
             exportFile.close();
             m_scopeVis->deserializeMemory(QByteArray::fromBase64(base64Str));
             qDebug("GLScopeGUI::on_memoryLoad_clicked: loaded from %s", qPrintable(fileName));
         }
         else
         {
             QMessageBox::information(this, tr("Message"), tr("Cannot open file %1 for reading").arg(fileName));
         }
     }
 }
on_memorySave_clicked
void GLScopeGUI::on_memorySave_clicked (bool checked) private slot
Definition at line 810 of file glscopegui.cpp.
References arg(), m_scopeVis, and ScopeVis::serializeMemory().
 {
     (void) checked;
     QString fileName = QFileDialog::getSaveFileName(this,
         tr("Open trace memory file"), ".", tr("Trace memory files (*.trcm)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "")
     {
         QFileInfo fileInfo(fileName);
         if (fileInfo.suffix() != "trcm") {
             fileName += ".trcm";
         }
         QFile exportFile(fileName);
         if (exportFile.open(QIODevice::WriteOnly | QIODevice::Text))
         {
             QString base64Str = m_scopeVis->serializeMemory().toBase64();
             QTextStream outstream(&exportFile);
             outstream << base64Str;
             exportFile.close();
             qDebug("GLScopeGUI::on_memorySave_clicked: saved to %s", qPrintable(fileName));
         }
         else
         {
             QMessageBox::information(this, tr("Message"), tr("Cannot open %1 file for writing").arg(fileName));
         }
     }
 }
on_ofsCoarse_valueChanged
void GLScopeGUI::on_ofsCoarse_valueChanged (int value) private slot
Definition at line 762 of file glscopegui.cpp.
References changeCurrentTrace(), and setAmpOfsDisplay().
 {
     (void) value;
     setAmpOfsDisplay();
     changeCurrentTrace();
 }
on_ofsFine_valueChanged
void GLScopeGUI::on_ofsFine_valueChanged (int value) private slot
Definition at line 769 of file glscopegui.cpp.
References changeCurrentTrace(), and setAmpOfsDisplay().
 {
     (void) value;
     setAmpOfsDisplay();
     changeCurrentTrace();
 }
on_onlyX_toggled
void GLScopeGUI::on_onlyX_toggled (bool checked) private slot
Definition at line 449 of file glscopegui.cpp.
References GLScope::DisplayX, m_glScope, GLScope::setDisplayMode(), and ui.
 {
     if (checked)
     {
         ui->onlyY->setChecked(false);
         ui->horizontalXY->setChecked(false);
         ui->verticalXY->setChecked(false);
         ui->polar->setChecked(false);
         m_glScope->setDisplayMode(GLScope::DisplayX);
     }
     else
     {
         if (!ui->onlyY->isChecked() && !ui->horizontalXY->isChecked() && !ui->verticalXY->isChecked() && !ui->polar->isChecked()) {
             ui->polar->setChecked(true);
         }
     }
 }
on_onlyY_toggled
void GLScopeGUI::on_onlyY_toggled (bool checked) private slot
Definition at line 467 of file glscopegui.cpp.
References GLScope::DisplayY, m_glScope, GLScope::setDisplayMode(), and ui.
 {
     if (checked)
     {
         ui->onlyX->setChecked(false);
         ui->horizontalXY->setChecked(false);
         ui->verticalXY->setChecked(false);
         ui->polar->setChecked(false);
         m_glScope->setDisplayMode(GLScope::DisplayY);
     }
     else
     {
         if (!ui->onlyX->isChecked() && !ui->horizontalXY->isChecked() && !ui->verticalXY->isChecked() && !ui->polar->isChecked()) {
             ui->polar->setChecked(true);
         }
     }
 }
on_polar_toggled
void GLScopeGUI::on_polar_toggled (bool checked) private slot
Definition at line 521 of file glscopegui.cpp.
References GLScope::DisplayPol, m_glScope, GLScope::setDisplayMode(), and ui.
 {
     if (checked)
     {
         ui->onlyX->setChecked(false);
         ui->onlyY->setChecked(false);
         ui->horizontalXY->setChecked(false);
         ui->verticalXY->setChecked(false);
         m_glScope->setDisplayMode(GLScope::DisplayPol);
     }
     else
     {
         if (!ui->onlyX->isChecked() && !ui->onlyY->isChecked() && !ui->horizontalXY->isChecked() && !ui->verticalXY->isChecked()) {
             ui->polar->setChecked(true);
         }
     }
 }
on_polarPoints_toggled
void GLScopeGUI::on_polarPoints_toggled (bool checked) private slot
Definition at line 539 of file glscopegui.cpp.
References m_glScope, and GLScope::setDisplayXYPoints().
 {
     m_glScope->setDisplayXYPoints(checked);
 }
on_scope_preTriggerChanged
void GLScopeGUI::on_scope_preTriggerChanged (uint32_t value) private slot
Definition at line 163 of file glscopegui.cpp.
References GLScope::getTraceSize(), m_glScope, setTrigPreDisplay(), and ui.
Referenced by setBuddies().
 {
     qDebug("GLScopeGUI::on_scope_preTriggerChanged: %u", preTriggerNbSamples);
     ui->trigPre->setValue(preTriggerNbSamples*100 / m_glScope->getTraceSize()); // slider position is a percentage value of the trace size
     setTrigPreDisplay();
 }
on_scope_sampleRateChanged
void GLScopeGUI::on_scope_sampleRateChanged (int value) private slot
Definition at line 142 of file glscopegui.cpp.
References arg(), m_sampleRate, setTimeOfsDisplay(), setTimeScaleDisplay(), setTraceDelayDisplay(), setTraceLenDisplay(), setTrigDelayDisplay(), setTrigPreDisplay(), and ui.
Referenced by setBuddies().
 {
     //m_sampleRate = m_glScope->getSampleRate();
     m_sampleRate = sampleRate;
     ui->sampleRateText->setText(tr("%1\nkS/s").arg(m_sampleRate / 1000.0f, 0, 'f', 2));
     setTraceLenDisplay();
     setTimeScaleDisplay();
     setTimeOfsDisplay();
     setTraceDelayDisplay();
     setTrigPreDisplay();
     setTrigDelayDisplay();
 }
on_scope_traceSizeChanged
void GLScopeGUI::on_scope_traceSizeChanged (uint32_t value) private slot
Definition at line 155 of file glscopegui.cpp.
References ScopeVis::m_traceChunkSize, m_traceLenMult, setTraceLenDisplay(), and ui.
Referenced by setBuddies().
 {
     qDebug("GLScopeGUI::on_scope_traceSizeChanged: %u", traceNbSamples);
     m_traceLenMult = traceNbSamples / ScopeVis::m_traceChunkSize;
     ui->traceLen->setValue(m_traceLenMult);
     setTraceLenDisplay();
 }
on_time_valueChanged
void GLScopeGUI::on_time_valueChanged (int value) private slot
Definition at line 556 of file glscopegui.cpp.
References ScopeVis::configure(), GLScope::getTraceSize(), m_glScope, m_scopeVis, m_timeBase, m_timeOffset, ScopeVis::m_traceChunkSize, m_traceLenMult, setTimeScaleDisplay(), setTraceDelayDisplay(), and ui.
 {
     m_timeBase = value;
     setTimeScaleDisplay();
     setTraceDelayDisplay();
     m_scopeVis->configure(m_traceLenMult*ScopeVis::m_traceChunkSize,
             m_timeBase,
             m_timeOffset*10,
             (uint32_t) (m_glScope->getTraceSize() * (ui->trigPre->value()/100.0f)),
             ui->freerun->isChecked());
 }
on_timeOfs_valueChanged
void GLScopeGUI::on_timeOfs_valueChanged (int value) private slot
Definition at line 568 of file glscopegui.cpp.
References ScopeVis::configure(), GLScope::getTraceSize(), m_glScope, m_scopeVis, m_timeBase, m_timeOffset, ScopeVis::m_traceChunkSize, m_traceLenMult, setTimeOfsDisplay(), and ui.
 {
     if ((value < 0) || (value > 100)) {
         return;
     }
     m_timeOffset = value;
     setTimeOfsDisplay();
     m_scopeVis->configure(m_traceLenMult*ScopeVis::m_traceChunkSize,
             m_timeBase,
             m_timeOffset*10,
             (uint32_t) (m_glScope->getTraceSize() * (ui->trigPre->value()/100.0f)),
             ui->freerun->isChecked());
 }
on_trace_valueChanged
void GLScopeGUI::on_trace_valueChanged (int value) private slot
Definition at line 602 of file glscopegui.cpp.
References arg(), ScopeVis::focusOnTrace(), ScopeVis::getTraceData(), ScopeVis::TraceData::m_amp, ScopeVis::TraceData::m_ofs, ScopeVis::TraceData::m_projectionType, m_scopeVis, ScopeVis::TraceData::m_traceDelay, setTraceUI(), and ui.
Referenced by focusOnTrace().
 {
     ui->traceText->setText(value == 0 ? "X" : QString("Y%1").arg(ui->trace->value()));
     ScopeVis::TraceData traceData;
     m_scopeVis->getTraceData(traceData, value);
     qDebug() << "GLScopeGUI::on_trace_valueChanged:"
             << " m_projectionType: " << (int) traceData.m_projectionType
             << " m_amp" << traceData.m_amp
             << " m_ofs" << traceData.m_ofs
             << " m_traceDelay" << traceData.m_traceDelay;
     setTraceUI(traceData);
     m_scopeVis->focusOnTrace(value);
 }
on_traceAdd_clicked
void GLScopeGUI::on_traceAdd_clicked (bool checked) private slot
Definition at line 620 of file glscopegui.cpp.
References addTrace(), and fillTraceData().
 {
     (void) checked;
     ScopeVis::TraceData traceData;
     fillTraceData(traceData);
     addTrace(traceData);
 }
on_traceColor_clicked
void GLScopeGUI::on_traceColor_clicked () private slot
Definition at line 796 of file glscopegui.cpp.
References arg(), changeCurrentTrace(), m_focusedTraceColor, and ui.
 {
     QColor newColor = QColorDialog::getColor(m_focusedTraceColor, this, tr("Select Color for trace"), QColorDialog::DontUseNativeDialog);
     if (newColor.isValid()) // user clicked OK and selected a color
     {
         m_focusedTraceColor = newColor;
         int r,g,b,a;
         m_focusedTraceColor.getRgb(&r, &g, &b, &a);
         ui->traceColor->setStyleSheet(tr("QLabel { background-color : rgb(%1,%2,%3); }").arg(r).arg(g).arg(b));
         changeCurrentTrace();
     }
 }
on_traceDel_clicked
void GLScopeGUI::on_traceDel_clicked (bool checked) private slot
Definition at line 628 of file glscopegui.cpp.
References changeCurrentTrace(), GLScope::DisplayX, m_glScope, m_scopeVis, ScopeVis::removeTrace(), GLScope::setDisplayMode(), and ui.
 {
     (void) checked;
     if (ui->trace->value() > 0) // not the X trace
     {
         ui->trace->setMaximum(ui->trace->maximum() - 1);
         if (ui->trace->value() == 0)
         {
             ui->onlyX->setChecked(true);
             ui->onlyY->setEnabled(false);
             ui->horizontalXY->setEnabled(false);
             ui->verticalXY->setEnabled(false);
             ui->polar->setEnabled(false);
             m_glScope->setDisplayMode(GLScope::DisplayX);
         }
         m_scopeVis->removeTrace(ui->trace->value());
         changeCurrentTrace();
     }
 }
on_traceDelayCoarse_valueChanged
void GLScopeGUI::on_traceDelayCoarse_valueChanged (int value) private slot
Definition at line 776 of file glscopegui.cpp.
References changeCurrentTrace(), and setTraceDelayDisplay().
 {
     (void) value;
     setTraceDelayDisplay();
     changeCurrentTrace();
 }
on_traceDelayFine_valueChanged
void GLScopeGUI::on_traceDelayFine_valueChanged (int value) private slot
Definition at line 783 of file glscopegui.cpp.
References changeCurrentTrace(), and setTraceDelayDisplay().
 {
     (void) value;
     setTraceDelayDisplay();
     changeCurrentTrace();
 }
on_traceDown_clicked
void GLScopeGUI::on_traceDown_clicked (bool checked) private slot
Definition at line 665 of file glscopegui.cpp.
References ScopeVis::focusOnTrace(), ScopeVis::getTraceData(), m_scopeVis, ScopeVis::moveTrace(), setTraceUI(), and ui.
 {
     (void) checked;
     if (ui->trace->value() > 0) // not the X (lowest) trace
     {
         int newTraceIndex = (ui->trace->value() - 1) % (ui->trace->maximum()+1);
         m_scopeVis->moveTrace(ui->trace->value(), false);
         ui->trace->setValue(newTraceIndex); // follow trace
         ScopeVis::TraceData traceData;
         m_scopeVis->getTraceData(traceData, ui->trace->value());
         setTraceUI(traceData);
         m_scopeVis->focusOnTrace(ui->trace->value());
     }
 }
on_traceIntensity_valueChanged
void GLScopeGUI::on_traceIntensity_valueChanged (int value) private slot
Definition at line 544 of file glscopegui.cpp.
References arg(), m_glScope, GLScope::setDisplayTraceIntensity(), and ui.
 {
     ui->traceIntensity->setToolTip(QString("Trace intensity: %1").arg(value));
     m_glScope->setDisplayTraceIntensity(value);
 }
on_traceLen_valueChanged
void GLScopeGUI::on_traceLen_valueChanged (int value) private slot
Definition at line 583 of file glscopegui.cpp.
References ScopeVis::configure(), GLScope::getTraceSize(), m_glScope, m_scopeVis, m_timeBase, m_timeOffset, ScopeVis::m_traceChunkSize, m_traceLenMult, setTimeOfsDisplay(), setTimeScaleDisplay(), setTraceLenDisplay(), setTrigDelayDisplay(), setTrigPreDisplay(), and ui.
 {
     if ((value < 1) || (value > 100)) {
         return;
     }
     m_traceLenMult = value;
     m_scopeVis->configure(m_traceLenMult*ScopeVis::m_traceChunkSize,
             m_timeBase,
             m_timeOffset*10,
             (uint32_t) (m_glScope->getTraceSize() * (ui->trigPre->value()/100.0f)),
             ui->freerun->isChecked());
     setTraceLenDisplay();
     setTimeScaleDisplay();
     setTimeOfsDisplay();
     setTrigDelayDisplay();
     setTrigPreDisplay();
 }
on_traceMode_currentIndexChanged
void GLScopeGUI::on_traceMode_currentIndexChanged (int index) private slot
Definition at line 747 of file glscopegui.cpp.
References changeCurrentTrace(), setAmpOfsDisplay(), and setAmpScaleDisplay().
 {
     (void) index;
     setAmpScaleDisplay();
     setAmpOfsDisplay();
     changeCurrentTrace();
 }
on_traceUp_clicked
void GLScopeGUI::on_traceUp_clicked (bool checked) private slot
Definition at line 650 of file glscopegui.cpp.
References ScopeVis::focusOnTrace(), ScopeVis::getTraceData(), m_scopeVis, ScopeVis::moveTrace(), setTraceUI(), and ui.
 {
     (void) checked;
     if (ui->trace->maximum() > 0) // more than one trace
     {
         int newTraceIndex = (ui->trace->value() + 1) % (ui->trace->maximum()+1);
         m_scopeVis->moveTrace(ui->trace->value(), true);
         ui->trace->setValue(newTraceIndex); // follow trace
         ScopeVis::TraceData traceData;
         m_scopeVis->getTraceData(traceData, ui->trace->value());
         setTraceUI(traceData);
         m_scopeVis->focusOnTrace(ui->trace->value());
     }
 }
on_traceView_toggled
void GLScopeGUI::on_traceView_toggled (bool checked) private slot
Definition at line 790 of file glscopegui.cpp.
References changeCurrentTrace().
 {
     (void) checked;
     changeCurrentTrace();
 }
on_trig_valueChanged
void GLScopeGUI::on_trig_valueChanged (int value) private slot
Definition at line 680 of file glscopegui.cpp.
References arg(), ScopeVis::focusOnTrigger(), ScopeVis::getTriggerData(), ScopeVis::TriggerData::m_projectionType, m_scopeVis, ScopeVis::TriggerData::m_triggerBothEdges, ScopeVis::TriggerData::m_triggerLevel, ScopeVis::TriggerData::m_triggerPositiveEdge, ScopeVis::TriggerData::m_triggerRepeat, setTriggerUI(), and ui.
Referenced by focusOnTrigger().
 {
     ui->trigText->setText(tr("%1").arg(value));
     ScopeVis::TriggerData triggerData;
     m_scopeVis->getTriggerData(triggerData, value);
     qDebug() << "GLScopeGUI::on_trig_valueChanged:"
             << " m_projectionType: " << (int) triggerData.m_projectionType
             << " m_triggerRepeat" << triggerData.m_triggerRepeat
             << " m_triggerPositiveEdge" << triggerData.m_triggerPositiveEdge
             << " m_triggerBothEdges" << triggerData.m_triggerBothEdges
             << " m_triggerLevel" << triggerData.m_triggerLevel;
     setTriggerUI(triggerData);
     m_scopeVis->focusOnTrigger(value);
 }
on_trigAdd_clicked
void GLScopeGUI::on_trigAdd_clicked (bool checked) private slot
Definition at line 699 of file glscopegui.cpp.
References addTrigger(), and fillTriggerData().
 {
     (void) checked;
     ScopeVis::TriggerData triggerData;
     fillTriggerData(triggerData);
     addTrigger(triggerData);
 }
on_trigBoth_toggled
void GLScopeGUI::on_trigBoth_toggled (bool checked) private slot
Definition at line 912 of file glscopegui.cpp.
References changeCurrentTrigger(), and ui.
 {
     if (checked)
     {
         ui->trigNeg->setChecked(false);
         ui->trigPos->setChecked(false);
     }
     changeCurrentTrigger();
 }
on_trigColor_clicked
void GLScopeGUI::on_trigColor_clicked () private slot
Definition at line 967 of file glscopegui.cpp.
References arg(), changeCurrentTrigger(), m_focusedTriggerColor, and ui.
 {
     QColor newColor = QColorDialog::getColor(m_focusedTriggerColor, this, tr("Select Color for trigger line"), QColorDialog::DontUseNativeDialog);
     if (newColor.isValid()) // user clicked "OK"
     {
         m_focusedTriggerColor = newColor;
         int r,g,b,a;
         m_focusedTriggerColor.getRgb(&r, &g, &b, &a);
         ui->trigColor->setStyleSheet(tr("QLabel { background-color : rgb(%1,%2,%3); }").arg(r).arg(g).arg(b));
         changeCurrentTrigger();
     }
 }
on_trigCount_valueChanged
void GLScopeGUI::on_trigCount_valueChanged (int value) private slot
Definition at line 885 of file glscopegui.cpp.
References changeCurrentTrigger(), and setTrigCountDisplay().
 {
     (void) value;
     setTrigCountDisplay();
     changeCurrentTrigger();
 }
on_trigDel_clicked
void GLScopeGUI::on_trigDel_clicked (bool checked) private slot
Definition at line 707 of file glscopegui.cpp.
References m_scopeVis, ScopeVis::removeTrigger(), and ui.
 {
     (void) checked;
     if (ui->trig->value() > 0)
     {
         m_scopeVis->removeTrigger(ui->trig->value());
         ui->trig->setMaximum(ui->trig->maximum() - 1);
     }
 }
on_trigDelayCoarse_valueChanged
void GLScopeGUI::on_trigDelayCoarse_valueChanged (int value) private slot
Definition at line 942 of file glscopegui.cpp.
References changeCurrentTrigger(), and setTrigDelayDisplay().
 {
     (void) value;
     setTrigDelayDisplay();
     changeCurrentTrigger();
 }
on_trigDelayFine_valueChanged
void GLScopeGUI::on_trigDelayFine_valueChanged (int value) private slot
Definition at line 949 of file glscopegui.cpp.
References changeCurrentTrigger(), and setTrigDelayDisplay().
 {
     (void) value;
     setTrigDelayDisplay();
     changeCurrentTrigger();
 }
on_trigDown_clicked
void GLScopeGUI::on_trigDown_clicked (bool checked) private slot
Definition at line 732 of file glscopegui.cpp.
References ScopeVis::focusOnTrigger(), ScopeVis::getTriggerData(), m_scopeVis, ScopeVis::moveTrigger(), setTriggerUI(), and ui.
 {
     (void) checked;
     if (ui->trig->value() > 0) // not the 0 (lowest) trigger
     {
         int newTriggerIndex = (ui->trig->value() - 1) % (ui->trig->maximum()+1);
         m_scopeVis->moveTrigger(ui->trace->value(), false);
         ui->trig->setValue(newTriggerIndex); // follow trigger
         ScopeVis::TriggerData triggerData;
         m_scopeVis->getTriggerData(triggerData, ui->trig->value());
         setTriggerUI(triggerData);
         m_scopeVis->focusOnTrigger(ui->trig->value());
     }
 }
on_trigHoldoff_valueChanged
void GLScopeGUI::on_trigHoldoff_valueChanged (int value) private slot
Definition at line 922 of file glscopegui.cpp.
References arg(), changeCurrentTrigger(), and ui.
 {
     ui->trigHoldoffText->setText(tr("%1").arg(value));
     changeCurrentTrigger();
 }
on_trigLevelCoarse_valueChanged
void GLScopeGUI::on_trigLevelCoarse_valueChanged (int value) private slot
Definition at line 928 of file glscopegui.cpp.
References changeCurrentTrigger(), and setTrigLevelDisplay().
 {
     (void) value;
     setTrigLevelDisplay();
     changeCurrentTrigger();
 }
on_trigLevelFine_valueChanged
void GLScopeGUI::on_trigLevelFine_valueChanged (int value) private slot
Definition at line 935 of file glscopegui.cpp.
References changeCurrentTrigger(), and setTrigLevelDisplay().
 {
     (void) value;
     setTrigLevelDisplay();
     changeCurrentTrigger();
 }
on_trigMode_currentIndexChanged
void GLScopeGUI::on_trigMode_currentIndexChanged (int index) private slot
Definition at line 878 of file glscopegui.cpp.
References changeCurrentTrigger(), and setTrigLevelDisplay().
 {
     (void) index;
     setTrigLevelDisplay();
     changeCurrentTrigger();
 }
on_trigNeg_toggled
void GLScopeGUI::on_trigNeg_toggled (bool checked) private slot
Definition at line 902 of file glscopegui.cpp.
References changeCurrentTrigger(), and ui.
 {
     if (checked)
     {
         ui->trigPos->setChecked(false);
         ui->trigBoth->setChecked(false);
     }
     changeCurrentTrigger();
 }
on_trigOneShot_toggled
void GLScopeGUI::on_trigOneShot_toggled (bool checked) private slot
Definition at line 981 of file glscopegui.cpp.
References m_scopeVis, and ScopeVis::setOneShot().
 {
     m_scopeVis->setOneShot(checked);
 }
on_trigPos_toggled
void GLScopeGUI::on_trigPos_toggled (bool checked) private slot
Definition at line 892 of file glscopegui.cpp.
References changeCurrentTrigger(), and ui.
 {
     if (checked)
     {
         ui->trigNeg->setChecked(false);
         ui->trigBoth->setChecked(false);
     }
     changeCurrentTrigger();
 }
on_trigPre_valueChanged
void GLScopeGUI::on_trigPre_valueChanged (int value) private slot
Definition at line 956 of file glscopegui.cpp.
References ScopeVis::configure(), GLScope::getTraceSize(), m_glScope, m_scopeVis, m_timeBase, m_timeOffset, ScopeVis::m_traceChunkSize, m_traceLenMult, setTrigPreDisplay(), and ui.
 {
     (void) value;
     setTrigPreDisplay();
     m_scopeVis->configure(m_traceLenMult*ScopeVis::m_traceChunkSize,
             m_timeBase,
             m_timeOffset*10,
             (uint32_t) (m_glScope->getTraceSize() * (ui->trigPre->value()/100.0f)),
             ui->freerun->isChecked());
 }
on_trigUp_clicked
void GLScopeGUI::on_trigUp_clicked (bool checked) private slot
Definition at line 717 of file glscopegui.cpp.
References ScopeVis::focusOnTrigger(), ScopeVis::getTriggerData(), m_scopeVis, ScopeVis::moveTrigger(), setTriggerUI(), and ui.
 {
     (void) checked;
     if (ui->trig->maximum() > 0) // more than one trigger
     {
         int newTriggerIndex = (ui->trig->value() + 1) % (ui->trig->maximum()+1);
         m_scopeVis->moveTrigger(ui->trace->value(), true);
         ui->trig->setValue(newTriggerIndex); // follow trigger
         ScopeVis::TriggerData triggerData;
         m_scopeVis->getTriggerData(triggerData, ui->trig->value());
         setTriggerUI(triggerData);
         m_scopeVis->focusOnTrigger(ui->trig->value());
     }
 }
on_verticalXY_toggled
void GLScopeGUI::on_verticalXY_toggled (bool checked) private slot
Definition at line 503 of file glscopegui.cpp.
References GLScope::DisplayXYV, m_glScope, GLScope::setDisplayMode(), and ui.
 {
     if (checked)
     {
         ui->onlyX->setChecked(false);
         ui->onlyY->setChecked(false);
         ui->horizontalXY->setChecked(false);
         ui->polar->setChecked(false);
         m_glScope->setDisplayMode(GLScope::DisplayXYV);
     }
     else
     {
         if (!ui->onlyX->isChecked() && !ui->onlyY->isChecked() && !ui->horizontalXY->isChecked() && !ui->polar->isChecked()) {
             ui->polar->setChecked(true);
         }
     }
 }
resetToDefaults()
void GLScopeGUI::resetToDefaults ()
Definition at line 170 of file glscopegui.cpp.
Referenced by deserialize().
 {
 }
serialize()
QByteArray GLScopeGUI::serialize () const virtual
Implements Serializable.
Definition at line 175 of file glscopegui.cpp.
References SimpleSerializer::final(), GLScope::getDisplayMode(), ScopeVis::getNbTriggers(), ScopeVis::getTracesData(), ScopeVis::getTriggerData(), i, m_glScope, ScopeVis::TriggerData::m_projectionType, m_scopeVis, ScopeVis::TriggerData::m_triggerBothEdges, ScopeVis::TriggerData::m_triggerColorB, ScopeVis::TriggerData::m_triggerColorG, ScopeVis::TriggerData::m_triggerColorR, ScopeVis::TriggerData::m_triggerDelayCoarse, ScopeVis::TriggerData::m_triggerDelayFine, ScopeVis::TriggerData::m_triggerHoldoff, ScopeVis::TriggerData::m_triggerLevelCoarse, ScopeVis::TriggerData::m_triggerLevelFine, ScopeVis::TriggerData::m_triggerPositiveEdge, ScopeVis::TriggerData::m_triggerRepeat, ui, SimpleSerializer::writeBool(), SimpleSerializer::writeFloat(), SimpleSerializer::writeS32(), and SimpleSerializer::writeU32().
 {
     SimpleSerializer s(1);
     // first row
     s.writeS32(1, (int) m_glScope->getDisplayMode());
     s.writeS32(2, ui->traceIntensity->value());
     s.writeS32(3, ui->gridIntensity->value());
     s.writeS32(4, ui->time->value());
     s.writeS32(5, ui->timeOfs->value());
     s.writeS32(6, ui->traceLen->value());
     // second row - by trace
     const std::vector<ScopeVis::TraceData>& tracesData = m_scopeVis->getTracesData();
     std::vector<ScopeVis::TraceData>::const_iterator traceDataIt = tracesData.begin();
     s.writeU32(10, (uint32_t) tracesData.size());
     int i = 0;
     for (; traceDataIt != tracesData.end(); ++traceDataIt, i++)
     {
         s.writeS32(20 + 16*i, (int) traceDataIt->m_projectionType);
         s.writeU32(21 + 16*i, traceDataIt->m_ampIndex);
         s.writeS32(22 + 16*i, traceDataIt->m_ofsCoarse);
         s.writeS32(23 + 16*i, traceDataIt->m_ofsFine);
         s.writeS32(24 + 16*i, traceDataIt->m_traceDelayCoarse);
         s.writeS32(25 + 16*i, traceDataIt->m_traceDelayFine);
         s.writeFloat(26 + 16*i, traceDataIt->m_traceColorR);
         s.writeFloat(27 + 16*i, traceDataIt->m_traceColorG);
         s.writeFloat(28 + 16*i, traceDataIt->m_traceColorB);
     }
     // third row - by trigger
     s.writeU32(200, (uint32_t) m_scopeVis->getNbTriggers());
     s.writeS32(201, ui->trigPre->value());
     for (unsigned int i = 0; i < m_scopeVis->getNbTriggers(); i++)
     {
         const ScopeVis::TriggerData& triggerData = m_scopeVis->getTriggerData(i);
         s.writeS32(210 + 16*i, (int) triggerData.m_projectionType);
         s.writeS32(211 + 16*i, triggerData.m_triggerRepeat);
         s.writeBool(212 + 16*i, triggerData.m_triggerPositiveEdge);
         s.writeBool(213 + 16*i, triggerData.m_triggerBothEdges);
         s.writeS32(214 + 16*i, triggerData.m_triggerLevelCoarse);
         s.writeS32(215 + 16*i, triggerData.m_triggerLevelFine);
         s.writeS32(216 + 16*i, triggerData.m_triggerDelayCoarse);
         s.writeS32(217 + 16*i, triggerData.m_triggerDelayFine);
         s.writeFloat(218 + 16*i, triggerData.m_triggerColorR);
         s.writeFloat(219 + 16*i, triggerData.m_triggerColorG);
         s.writeFloat(220 + 16*i, triggerData.m_triggerColorB);
         s.writeU32(221 + 16*i, triggerData.m_triggerHoldoff);
     }
     return s.final();
 }
setAmpOfsDisplay()
void GLScopeGUI::setAmpOfsDisplay () private
Definition at line 1132 of file glscopegui.cpp.
References arg(), Projector::ProjectionMagDB, Projector::ProjectionMagLin, Projector::ProjectionMagSq, and ui.
Referenced by deserialize(), on_ofsCoarse_valueChanged(), on_ofsFine_valueChanged(), on_traceMode_currentIndexChanged(), setBuddies(), and setTraceUI().
 {
     Projector::ProjectionType projectionType = (Projector::ProjectionType) ui->traceMode->currentIndex();
     double o = (ui->ofsCoarse->value() * 10.0f) + (ui->ofsFine->value() / 20.0f);
     if (projectionType == Projector::ProjectionMagDB)
     {
         ui->ofsText->setText(tr("%1\ndB").arg(o/10.0f - 100.0f, 0, 'f', 1));
     }
     else
     {
         double a;
         if ((projectionType == Projector::ProjectionMagLin) || (projectionType == Projector::ProjectionMagSq))
         {
             a = o/2000.0f;
         }
         else
         {
             a = o/1000.0f;
         }
         if(fabs(a) < 1e-9)
             ui->ofsText->setText(tr("%1\np").arg(a * 1e12));
         else if(fabs(a) < 1e-6)
             ui->ofsText->setText(tr("%1\nn").arg(a * 1e9));
         else if(fabs(a) < 1e-3)
             ui->ofsText->setText(tr("%1\n").arg(a * 1e6));
         else if(fabs(a) < 1.0f)
             ui->ofsText->setText(tr("%1\nm").arg(a * 1e3));
         else
             ui->ofsText->setText(tr("%1").arg(a * 1.0));
     }
 }
setAmpScaleDisplay()
void GLScopeGUI::setAmpScaleDisplay () private
Definition at line 1101 of file glscopegui.cpp.
References amps, arg(), Projector::ProjectionMagDB, and ui.
Referenced by deserialize(), on_amp_valueChanged(), on_traceMode_currentIndexChanged(), setBuddies(), and setTraceUI().
 {
     Projector::ProjectionType projectionType = (Projector::ProjectionType) ui->traceMode->currentIndex();
     double ampValue = amps[ui->amp->value()];
     if (projectionType == Projector::ProjectionMagDB)
     {
         double displayValue = ampValue*500.0f;
         if (displayValue < 10.0f) {
             ui->ampText->setText(tr("%1\ndB").arg(displayValue, 0, 'f', 2));
         }
         else {
             ui->ampText->setText(tr("%1\ndB").arg(displayValue, 0, 'f', 1));
         }
     }
     else
     {
         double a = ampValue*10.0f;
         if(a < 0.000001)
             ui->ampText->setText(tr("%1\nn").arg(a * 1000000000.0));
         else if(a < 0.001)
             ui->ampText->setText(tr("%1\n").arg(a * 1000000.0));
         else if(a < 1.0)
             ui->ampText->setText(tr("%1\nm").arg(a * 1000.0));
         else
             ui->ampText->setText(tr("%1").arg(a * 1.0));
     }
 }
setBuddies()
void GLScopeGUI::setBuddies (MessageQueue * messageQueue, ScopeVis * scopeVis, GLScope * glScope)
Definition at line 68 of file glscopegui.cpp.
References ScopeVis::addTrace(), ScopeVis::addTrigger(), ScopeVis::configure(), GLScope::DisplayX, fillProjectionCombo(), fillTraceData(), fillTriggerData(), GLScope::getTraceSize(), m_glScope, m_messageQueue, m_scopeVis, m_timeBase, m_timeOffset, ScopeVis::m_traceChunkSize, m_traceLenMult, on_scope_preTriggerChanged(), on_scope_sampleRateChanged(), on_scope_traceSizeChanged(), setAmpOfsDisplay(), setAmpScaleDisplay(), GLScope::setDisplayMode(), setTimeOfsDisplay(), setTimeScaleDisplay(), setTraceDelayDisplay(), setTraceLenDisplay(), and ui.
 {
     qDebug("GLScopeGUI::setBuddies");
     m_messageQueue = messageQueue;
     m_scopeVis = scopeVis;
     m_glScope = glScope;
     // initialize display combo
     ui->onlyX->setChecked(true);
     ui->onlyY->setChecked(false);
     ui->horizontalXY->setChecked(false);
     ui->verticalXY->setChecked(false);
     ui->polar->setChecked(false);
     ui->onlyY->setEnabled(false);
     ui->horizontalXY->setEnabled(false);
     ui->verticalXY->setEnabled(false);
     ui->polar->setEnabled(false);
     m_glScope->setDisplayMode(GLScope::DisplayX);
     // initialize trigger combo
     ui->trigPos->setChecked(true);
     ui->trigNeg->setChecked(false);
     ui->trigBoth->setChecked(false);
     ui->trigOneShot->setChecked(false);
     ui->trigOneShot->setEnabled(false);
     ui->freerun->setChecked(true);
     // Add a trigger
     ScopeVis::TriggerData triggerData;
     fillTriggerData(triggerData);
     m_scopeVis->addTrigger(triggerData);
     // Add a trace
     ScopeVis::TraceData traceData;
     fillTraceData(traceData);
     m_scopeVis->addTrace(traceData);
     setEnabled(true);
     connect(m_glScope, SIGNAL(sampleRateChanged(int)), this, SLOT(on_scope_sampleRateChanged(int)));
     connect(m_glScope, SIGNAL(traceSizeChanged(uint32_t)), this, SLOT(on_scope_traceSizeChanged(uint32_t)));
     connect(m_glScope, SIGNAL(preTriggerChanged(uint32_t)), this, SLOT(on_scope_preTriggerChanged(uint32_t)));
     ui->traceMode->clear();
     fillProjectionCombo(ui->traceMode);
     ui->trigMode->clear();
     fillProjectionCombo(ui->trigMode);
     m_scopeVis->configure(2*m_traceLenMult*ScopeVis::m_traceChunkSize,
             m_timeBase,
             m_timeOffset*10,
             (uint32_t) (m_glScope->getTraceSize() * (ui->trigPre->value()/100.0f)),
             ui->freerun->isChecked());
     m_scopeVis->configure(m_traceLenMult*ScopeVis::m_traceChunkSize,
             m_timeBase,
             m_timeOffset*10,
             (uint32_t) (m_glScope->getTraceSize() * (ui->trigPre->value()/100.0f)),
             ui->freerun->isChecked());
     setTraceLenDisplay();
     setTimeScaleDisplay();
     setTimeOfsDisplay();
     setAmpScaleDisplay();
     setAmpOfsDisplay();
     setTraceDelayDisplay();
 }
setDisplayMode()
void GLScopeGUI::setDisplayMode (DisplayMode displayMode)
Definition at line 1566 of file glscopegui.cpp.
References DisplayPol, DisplayX, DisplayXYH, DisplayXYV, DisplayY, and ui.
 {
     if (ui->trace->maximum() == 0)
     {
         ui->onlyX->setChecked(true);
     }
     else
     {
         switch (displayMode)
         {
         case DisplayX:
             ui->onlyX->setChecked(true);
             break;
         case DisplayY:
             ui->onlyY->setChecked(true);
             break;
         case DisplayXYH:
             ui->horizontalXY->setChecked(true);
             break;
         case DisplayXYV:
             ui->verticalXY->setChecked(true);
             break;
         case DisplayPol:
             ui->polar->setChecked(true);
             break;
         default:
             ui->onlyX->setChecked(true);
             break;
         }
     }
 }
setGridIntensity()
void GLScopeGUI::setGridIntensity (int value)
Definition at line 1607 of file glscopegui.cpp.
References ui.
 {
     if ((value < ui->gridIntensity->minimum()) || (value > ui->gridIntensity->maximum())) {
         return;
     }
     ui->gridIntensity->setValue(value);
 }
setPreTrigger()
void GLScopeGUI::setPreTrigger (int step)
Definition at line 1643 of file glscopegui.cpp.
References ui.
 {
     if ((step < ui->trigPre->minimum()) || (step > ui->trigPre->maximum())) {
         return;
     }
     ui->trigPre->setValue(step);
 }
setSampleRate()
void GLScopeGUI::setSampleRate (int sampleRate)
Definition at line 137 of file glscopegui.cpp.
References m_sampleRate.
 {
     m_sampleRate = sampleRate;
 }
setTimeBase()
void GLScopeGUI::setTimeBase (int step)
Definition at line 1616 of file glscopegui.cpp.
References ui.
 {
     if ((step < ui->time->minimum()) || (step > ui->time->maximum())) {
         return;
     }
     ui->time->setValue(step);
 }
setTimeOffset()
void GLScopeGUI::setTimeOffset (int step)
Definition at line 1625 of file glscopegui.cpp.
References ui.
 {
     if ((step < ui->timeOfs->minimum()) || (step > ui->timeOfs->maximum())) {
         return;
     }
     ui->timeOfs->setValue(step);
 }
setTimeOfsDisplay()
void GLScopeGUI::setTimeOfsDisplay () private
Definition at line 1078 of file glscopegui.cpp.
References arg(), GLScope::getTraceSize(), m_glScope, m_sampleRate, m_timeOffset, and ui.
Referenced by on_scope_sampleRateChanged(), on_timeOfs_valueChanged(), on_traceLen_valueChanged(), and setBuddies().
 {
     unsigned int n_samples = m_glScope->getTraceSize() * (m_timeOffset/100.0);
     double dt = m_glScope->getTraceSize() * (m_timeOffset/100.0) / m_sampleRate;
     if (n_samples < 1000) {
         ui->timeOfsText->setToolTip(tr("%1 S").arg(n_samples));
     } else if (n_samples < 1000000) {
         ui->timeOfsText->setToolTip(tr("%1 kS").arg(n_samples/1000.0));
     } else {
         ui->timeOfsText->setToolTip(tr("%1 MS").arg(n_samples/1000000.0));
     }
     if(dt < 0.000001)
         ui->timeOfsText->setText(tr("%1\nns").arg(dt * 1000000000.0, 0, 'f', 2));
     else if(dt < 0.001)
         ui->timeOfsText->setText(tr("%1\ns").arg(dt * 1000000.0, 0, 'f', 2));
     else if(dt < 1.0)
         ui->timeOfsText->setText(tr("%1\nms").arg(dt * 1000.0, 0, 'f', 2));
     else
         ui->timeOfsText->setText(tr("%1\ns").arg(dt * 1.0, 0, 'f', 2));
 }
setTimeScaleDisplay()
void GLScopeGUI::setTimeScaleDisplay () private
Definition at line 1017 of file glscopegui.cpp.
References arg(), GLScope::getSampleRate(), GLScope::getTraceSize(), m_glScope, m_sampleRate, m_timeBase, and ui.
Referenced by on_scope_sampleRateChanged(), on_time_valueChanged(), on_traceLen_valueChanged(), and setBuddies().
 {
     m_sampleRate = m_glScope->getSampleRate();
     unsigned int n_samples = (m_glScope->getTraceSize() * 1.0) / (double) m_timeBase;
     double t = (m_glScope->getTraceSize() * 1.0 / m_sampleRate) / (double) m_timeBase;
     if (n_samples < 1000) {
         ui->timeText->setToolTip(tr("%1 S").arg(n_samples));
     } else if (n_samples < 1000000) {
         ui->timeText->setToolTip(tr("%1 kS").arg(n_samples/1000.0));
     } else {
         ui->timeText->setToolTip(tr("%1 MS").arg(n_samples/1000000.0));
     }
     if(t < 0.000001)
     {
         t = round(t * 100000000000.0) / 100.0;
         ui->timeText->setText(tr("%1\nns").arg(t));
     }
     else if(t < 0.001)
     {
         t = round(t * 100000000.0) / 100.0;
         ui->timeText->setText(tr("%1\ns").arg(t));
     }
     else if(t < 1.0)
     {
         t = round(t * 100000.0) / 100.0;
         ui->timeText->setText(tr("%1\nms").arg(t));
     }
     else
     {
         t = round(t * 100.0) / 100.0;
         ui->timeText->setText(tr("%1\ns").arg(t));
     }
 }
setTraceDelayDisplay()
void GLScopeGUI::setTraceDelayDisplay () private
Definition at line 1167 of file glscopegui.cpp.
References arg(), m_sampleRate, and ui.
Referenced by deserialize(), on_scope_sampleRateChanged(), on_time_valueChanged(), on_traceDelayCoarse_valueChanged(), on_traceDelayFine_valueChanged(), setBuddies(), and setTraceUI().
 {
     if (m_sampleRate > 0)
     {
         int n_samples = ui->traceDelayCoarse->value()*100 + ui->traceDelayFine->value();
         double t = ((double) n_samples) / m_sampleRate;
         if (n_samples < 1000) {
             ui->traceDelayText->setToolTip(tr("%1 S").arg(n_samples));
         } else if (n_samples < 1000000) {
             ui->traceDelayText->setToolTip(tr("%1 kS").arg(n_samples/1000.0));
         } else {
             ui->traceDelayText->setToolTip(tr("%1 MS").arg(n_samples/1000000.0));
         }
         if(t < 0.000001)
             ui->traceDelayText->setText(tr("%1\nns").arg(t * 1000000000.0, 0, 'f', 2));
         else if(t < 0.001)
             ui->traceDelayText->setText(tr("%1\ns").arg(t * 1000000.0, 0, 'f', 2));
         else if(t < 1.0)
             ui->traceDelayText->setText(tr("%1\nms").arg(t * 1000.0, 0, 'f', 2));
         else
             ui->traceDelayText->setText(tr("%1\ns").arg(t * 1.0, 0, 'f', 2));
     }
 }
setTraceIndexDisplay()
void GLScopeGUI::setTraceIndexDisplay () private
Definition at line 1005 of file glscopegui.cpp.
References ui.
Referenced by deserialize().
 {
     ui->traceText->setText(ui->trace->value() == 0 ? "X" : QString("Y%1").arg(ui->trace->value()));
 }
setTraceIntensity()
void GLScopeGUI::setTraceIntensity (int value)
Definition at line 1598 of file glscopegui.cpp.
References ui.
 {
     if ((value < ui->traceIntensity->minimum()) || (value > ui->traceIntensity->maximum())) {
         return;
     }
     ui->traceIntensity->setValue(value);
 }
setTraceLenDisplay()
void GLScopeGUI::setTraceLenDisplay () private
Definition at line 1053 of file glscopegui.cpp.
References arg(), GLScope::getSampleRate(), GLScope::getTraceSize(), m_glScope, m_sampleRate, ScopeVis::m_traceChunkSize, m_traceLenMult, and ui.
Referenced by on_scope_sampleRateChanged(), on_scope_traceSizeChanged(), on_traceLen_valueChanged(), and setBuddies().
 {
     unsigned int n_samples = m_traceLenMult * ScopeVis::m_traceChunkSize;
     if (n_samples < 1000) {
         ui->traceLenText->setToolTip(tr("%1 S").arg(n_samples));
     } else if (n_samples < 1000000) {
         ui->traceLenText->setToolTip(tr("%1 kS").arg(n_samples/1000.0));
     } else {
         ui->traceLenText->setToolTip(tr("%1 MS").arg(n_samples/1000000.0));
     }
     m_sampleRate = m_glScope->getSampleRate();
     double t = (m_glScope->getTraceSize() * 1.0 / m_sampleRate);
     if(t < 0.000001)
         ui->traceLenText->setText(tr("%1\nns").arg(t * 1000000000.0, 0, 'f', 2));
     else if(t < 0.001)
         ui->traceLenText->setText(tr("%1\ns").arg(t * 1000000.0, 0, 'f', 2));
     else if(t < 1.0)
         ui->traceLenText->setText(tr("%1\nms").arg(t * 1000.0, 0, 'f', 2));
     else
         ui->traceLenText->setText(tr("%1\ns").arg(t * 1.0, 0, 'f', 2));
 }
setTraceLength()
void GLScopeGUI::setTraceLength (int step)
Definition at line 1634 of file glscopegui.cpp.
References ui.
 {
     if ((step < ui->traceLen->minimum()) || (step > ui->traceLen->maximum())) {
         return;
     }
     ui->traceLen->setValue(step);
 }
setTraceUI()
void GLScopeGUI::setTraceUI (const ScopeVis::TraceData & traceData) private
Definition at line 1385 of file glscopegui.cpp.
References arg(), ScopeVis::TraceData::m_ampIndex, m_focusedTraceColor, ScopeVis::TraceData::m_ofsCoarse, ScopeVis::TraceData::m_ofsFine, ScopeVis::TraceData::m_projectionType, ScopeVis::TraceData::m_traceColor, ScopeVis::TraceData::m_traceDelayCoarse, ScopeVis::TraceData::m_traceDelayFine, ScopeVis::TraceData::m_viewTrace, setAmpOfsDisplay(), setAmpScaleDisplay(), setTraceDelayDisplay(), and ui.
Referenced by on_trace_valueChanged(), on_traceDown_clicked(), and on_traceUp_clicked().
 {
     TraceUIBlocker traceUIBlocker(ui);
     ui->traceMode->setCurrentIndex((int) traceData.m_projectionType);
     ui->amp->setValue(traceData.m_ampIndex);
     setAmpScaleDisplay();
     ui->ofsCoarse->setValue(traceData.m_ofsCoarse);
     ui->ofsFine->setValue(traceData.m_ofsFine);
     setAmpOfsDisplay();
     ui->traceDelayCoarse->setValue(traceData.m_traceDelayCoarse);
     ui->traceDelayFine->setValue(traceData.m_traceDelayFine);
     setTraceDelayDisplay();
     m_focusedTraceColor = traceData.m_traceColor;
     int r, g, b, a;
     m_focusedTraceColor.getRgb(&r, &g, &b, &a);
     ui->traceColor->setStyleSheet(tr("QLabel { background-color : rgb(%1,%2,%3); }").arg(r).arg(g).arg(b));
     ui->traceView->setChecked(traceData.m_viewTrace);
 }
setTrigCountDisplay()
void GLScopeGUI::setTrigCountDisplay () private
Definition at line 1010 of file glscopegui.cpp.
References ui.
Referenced by deserialize(), on_trigCount_valueChanged(), and setTriggerUI().
 {
     QString text;
     text.sprintf("%02d", ui->trigCount->value());
     ui->trigCountText->setText(text);
 }
setTrigDelayDisplay()
void GLScopeGUI::setTrigDelayDisplay () private
Definition at line 1230 of file glscopegui.cpp.
References arg(), GLScope::getSampleRate(), m_glScope, m_sampleRate, ScopeVis::m_traceChunkSize, m_traceLenMult, and ui.
Referenced by deserialize(), on_scope_sampleRateChanged(), on_traceLen_valueChanged(), on_trigDelayCoarse_valueChanged(), on_trigDelayFine_valueChanged(), and setTriggerUI().
 {
     if (m_sampleRate > 0)
     {
         double delayMult = ui->trigDelayCoarse->value() + ui->trigDelayFine->value() / (ScopeVis::m_traceChunkSize / 10.0);
         unsigned int n_samples_delay = m_traceLenMult * ScopeVis::m_traceChunkSize * delayMult;
         if (n_samples_delay < 1000) {
             ui->trigDelayText->setToolTip(tr("%1 S").arg(n_samples_delay));
         } else if (n_samples_delay < 1000000) {
             ui->trigDelayText->setToolTip(tr("%1 kS").arg(n_samples_delay/1000.0));
         } else if (n_samples_delay < 1000000000) {
             ui->trigDelayText->setToolTip(tr("%1 MS").arg(n_samples_delay/1000000.0));
         } else {
             ui->trigDelayText->setToolTip(tr("%1 GS").arg(n_samples_delay/1000000000.0));
         }
         m_sampleRate = m_glScope->getSampleRate();
         double t = (n_samples_delay * 1.0f / m_sampleRate);
         if(t < 0.000001)
             ui->trigDelayText->setText(tr("%1\nns").arg(t * 1000000000.0, 0, 'f', 2));
         else if(t < 0.001)
             ui->trigDelayText->setText(tr("%1\ns").arg(t * 1000000.0, 0, 'f', 2));
         else if(t < 1.0)
             ui->trigDelayText->setText(tr("%1\nms").arg(t * 1000.0, 0, 'f', 2));
         else
             ui->trigDelayText->setText(tr("%1\ns").arg(t * 1.0, 0, 'f', 2));
     }
 }
setTriggerUI()
void GLScopeGUI::setTriggerUI (const ScopeVis::TriggerData & triggerData) private
Definition at line 1409 of file glscopegui.cpp.
References arg(), m_focusedTriggerColor, ScopeVis::TriggerData::m_projectionType, ScopeVis::TriggerData::m_triggerBothEdges, ScopeVis::TriggerData::m_triggerColor, ScopeVis::TriggerData::m_triggerDelayCoarse, ScopeVis::TriggerData::m_triggerDelayFine, ScopeVis::TriggerData::m_triggerHoldoff, ScopeVis::TriggerData::m_triggerLevelCoarse, ScopeVis::TriggerData::m_triggerLevelFine, ScopeVis::TriggerData::m_triggerPositiveEdge, ScopeVis::TriggerData::m_triggerRepeat, setTrigCountDisplay(), setTrigDelayDisplay(), setTrigLevelDisplay(), and ui.
Referenced by on_trig_valueChanged(), on_trigDown_clicked(), and on_trigUp_clicked().
 {
     TrigUIBlocker trigUIBlocker(ui);
     ui->trigMode->setCurrentIndex((int) triggerData.m_projectionType);
     ui->trigCount->setValue(triggerData.m_triggerRepeat);
     setTrigCountDisplay();
     ui->trigPos->setChecked(false);
     ui->trigNeg->setChecked(false);
     ui->trigPos->doToggle(false);
     ui->trigNeg->doToggle(false);
     if (triggerData.m_triggerBothEdges)
     {
         ui->trigBoth->setChecked(true);
         ui->trigBoth->doToggle(true);
     }
     else
     {
         ui->trigBoth->setChecked(false);
         ui->trigBoth->doToggle(false);
         if (triggerData.m_triggerPositiveEdge)
         {
             ui->trigPos->setChecked(true);
             ui->trigPos->doToggle(true);
         }
         else
         {
             ui->trigNeg->setChecked(true);
             ui->trigNeg->doToggle(true);
         }
     }
     ui->trigHoldoffText->setText(tr("%1").arg(triggerData.m_triggerHoldoff));
     ui->trigLevelCoarse->setValue(triggerData.m_triggerLevelCoarse);
     ui->trigLevelFine->setValue(triggerData.m_triggerLevelFine);
     setTrigLevelDisplay();
     ui->trigDelayCoarse->setValue(triggerData.m_triggerDelayCoarse);
     ui->trigDelayFine->setValue(triggerData.m_triggerDelayFine);
     setTrigDelayDisplay();
     m_focusedTriggerColor = triggerData.m_triggerColor;
     int r, g, b, a;
     m_focusedTriggerColor.getRgb(&r, &g, &b, &a);
     ui->trigColor->setStyleSheet(tr("QLabel { background-color : rgb(%1,%2,%3); }").arg(r).arg(g).arg(b));
 }
setTrigIndexDisplay()
void GLScopeGUI::setTrigIndexDisplay () private
Definition at line 1193 of file glscopegui.cpp.
References arg(), and ui.
Referenced by deserialize().
 {
     ui->trigText->setText(tr("%1").arg(ui->trig->value()));
 }
setTrigLevelDisplay()
void GLScopeGUI::setTrigLevelDisplay () private
Definition at line 1198 of file glscopegui.cpp.
References arg(), Projector::ProjectionMagDB, Projector::ProjectionMagLin, Projector::ProjectionMagSq, and ui.
Referenced by deserialize(), on_trigLevelCoarse_valueChanged(), on_trigLevelFine_valueChanged(), on_trigMode_currentIndexChanged(), and setTriggerUI().
 {
     double t = (ui->trigLevelCoarse->value() / 100.0f) + (ui->trigLevelFine->value() / 50000.0f);
     Projector::ProjectionType projectionType = (Projector::ProjectionType) ui->trigMode->currentIndex();
     ui->trigLevelCoarse->setToolTip(QString("Trigger level coarse: %1 %").arg(ui->trigLevelCoarse->value() / 100.0f));
     ui->trigLevelFine->setToolTip(QString("Trigger level fine: %1 ppm").arg(ui->trigLevelFine->value() * 20));
     if (projectionType == Projector::ProjectionMagDB) {
         ui->trigLevelText->setText(tr("%1\ndB").arg(100.0 * (t - 1.0), 0, 'f', 1));
     }
     else
     {
         double a;
         if ((projectionType == Projector::ProjectionMagLin) || (projectionType == Projector::ProjectionMagSq)) {
             a = 1.0 + t;
         } else {
             a = t;
         }
         if(fabs(a) < 0.000001)
             ui->trigLevelText->setText(tr("%1\nn").arg(a * 1000000000.0f, 0, 'f', 2));
         else if(fabs(a) < 0.001)
             ui->trigLevelText->setText(tr("%1\n").arg(a * 1000000.0f, 0, 'f', 2));
         else if(fabs(a) < 1.0)
             ui->trigLevelText->setText(tr("%1\nm").arg(a * 1000.0f, 0, 'f', 2));
         else
             ui->trigLevelText->setText(tr("%1").arg(a * 1.0f, 0, 'f', 2));
     }
 }
setTrigPreDisplay()
void GLScopeGUI::setTrigPreDisplay () private
Definition at line 1261 of file glscopegui.cpp.
References arg(), GLScope::getTraceSize(), m_glScope, m_sampleRate, and ui.
Referenced by deserialize(), on_scope_preTriggerChanged(), on_scope_sampleRateChanged(), on_traceLen_valueChanged(), and on_trigPre_valueChanged().
 {
     if (m_sampleRate > 0)
     {
         unsigned int n_samples_delay = m_glScope->getTraceSize() * (ui->trigPre->value()/100.0f);
         double dt = m_glScope->getTraceSize() * (ui->trigPre->value()/100.0f) / m_sampleRate;
         if (n_samples_delay < 1000) {
             ui->trigPreText->setToolTip(tr("%1 S").arg(n_samples_delay));
         } else if (n_samples_delay < 1000000) {
             ui->trigPreText->setToolTip(tr("%1 kS").arg(n_samples_delay/1000.0));
         } else if (n_samples_delay < 1000000000) {
             ui->trigPreText->setToolTip(tr("%1 MS").arg(n_samples_delay/1000000.0));
         } else {
             ui->trigPreText->setToolTip(tr("%1 GS").arg(n_samples_delay/1000000000.0));
         }
         if(dt < 0.000001)
             ui->trigPreText->setText(tr("%1\nns").arg(dt * 1000000000.0f, 0, 'f', 2));
         else if(dt < 0.001)
             ui->trigPreText->setText(tr("%1\ns").arg(dt * 1000000.0f, 0, 'f', 2));
         else if(dt < 1.0)
             ui->trigPreText->setText(tr("%1\nms").arg(dt * 1000.0f, 0, 'f', 2));
         else
             ui->trigPreText->setText(tr("%1\ns").arg(dt * 1.0f, 0, 'f', 2));
     }
 }
Member Data Documentation
amps
const double GLScopeGUI::amps static private
Initial value:
= {
        2e-1, 1e-1, 5e-2,
        2e-2, 1e-2, 5e-3,
        2e-3, 1e-3, 5e-4,
        2e-4, 1e-4, 5e-5,
        2e-5, 1e-5, 5e-6,
        2e-6, 1e-6, 5e-7,
        2e-7, 1e-7, 5e-8,
        2e-8, 1e-8, 5e-9,
        2e-9, 1e-9, 5e-10,
}
Definition at line 157 of file glscopegui.h.
Referenced by fillTraceData(), and setAmpScaleDisplay().
m_focusedTraceColor
QColor GLScopeGUI::m_focusedTraceColor private
Definition at line 154 of file glscopegui.h.
Referenced by deserialize(), fillTraceData(), GLScopeGUI(), on_traceColor_clicked(), and setTraceUI().
m_focusedTriggerColor
QColor GLScopeGUI::m_focusedTriggerColor private
Definition at line 155 of file glscopegui.h.
Referenced by deserialize(), fillTriggerData(), GLScopeGUI(), on_trigColor_clicked(), and setTriggerUI().
m_glScope
GLScope* GLScopeGUI::m_glScope private
Definition at line 148 of file glscopegui.h.
Referenced by deserialize(), on_freerun_toggled(), on_gridIntensity_valueChanged(), on_horizontalXY_toggled(), on_onlyX_toggled(), on_onlyY_toggled(), on_polar_toggled(), on_polarPoints_toggled(), on_scope_preTriggerChanged(), on_time_valueChanged(), on_timeOfs_valueChanged(), on_traceDel_clicked(), on_traceIntensity_valueChanged(), on_traceLen_valueChanged(), on_trigPre_valueChanged(), on_verticalXY_toggled(), serialize(), setBuddies(), setTimeOfsDisplay(), setTimeScaleDisplay(), setTraceLenDisplay(), setTrigDelayDisplay(), and setTrigPreDisplay().
m_messageQueue
MessageQueue* GLScopeGUI::m_messageQueue private
Definition at line 146 of file glscopegui.h.
Referenced by setBuddies().
m_sampleRate
int GLScopeGUI::m_sampleRate private
Definition at line 150 of file glscopegui.h.
Referenced by on_scope_sampleRateChanged(), setSampleRate(), setTimeOfsDisplay(), setTimeScaleDisplay(), setTraceDelayDisplay(), setTraceLenDisplay(), setTrigDelayDisplay(), and setTrigPreDisplay().
m_scopeVis
ScopeVis* GLScopeGUI::m_scopeVis private
Definition at line 147 of file glscopegui.h.
Referenced by addTrace(), addTrigger(), changeCurrentTrace(), changeCurrentTrigger(), changeTrace(), changeTrigger(), deserialize(), on_freerun_toggled(), on_mem_valueChanged(), on_memoryLoad_clicked(), on_memorySave_clicked(), on_time_valueChanged(), on_timeOfs_valueChanged(), on_trace_valueChanged(), on_traceDel_clicked(), on_traceDown_clicked(), on_traceLen_valueChanged(), on_traceUp_clicked(), on_trig_valueChanged(), on_trigDel_clicked(), on_trigDown_clicked(), on_trigOneShot_toggled(), on_trigPre_valueChanged(), on_trigUp_clicked(), serialize(), and setBuddies().
m_timeBase
int GLScopeGUI::m_timeBase private
Definition at line 151 of file glscopegui.h.
Referenced by on_freerun_toggled(), on_time_valueChanged(), on_timeOfs_valueChanged(), on_traceLen_valueChanged(), on_trigPre_valueChanged(), setBuddies(), and setTimeScaleDisplay().
m_timeOffset
int GLScopeGUI::m_timeOffset private
Definition at line 152 of file glscopegui.h.
Referenced by on_freerun_toggled(), on_time_valueChanged(), on_timeOfs_valueChanged(), on_traceLen_valueChanged(), on_trigPre_valueChanged(), setBuddies(), and setTimeOfsDisplay().
m_traceLenMult
int GLScopeGUI::m_traceLenMult private
Definition at line 153 of file glscopegui.h.
Referenced by fillTriggerData(), on_freerun_toggled(), on_scope_traceSizeChanged(), on_time_valueChanged(), on_timeOfs_valueChanged(), on_traceLen_valueChanged(), on_trigPre_valueChanged(), setBuddies(), setTraceLenDisplay(), and setTrigDelayDisplay().
ui
Ui::GLScopeGUI* GLScopeGUI::ui private
Definition at line 144 of file glscopegui.h.
Referenced by addTrace(), addTrigger(), changeCurrentTrace(), changeCurrentTrigger(), deserialize(), disableLiveMode(), fillTraceData(), fillTriggerData(), GLScopeGUI(), on_freerun_toggled(), on_gridIntensity_valueChanged(), on_horizontalXY_toggled(), on_mem_valueChanged(), on_onlyX_toggled(), on_onlyY_toggled(), on_polar_toggled(), on_scope_preTriggerChanged(), on_scope_sampleRateChanged(), on_scope_traceSizeChanged(), on_time_valueChanged(), on_timeOfs_valueChanged(), on_trace_valueChanged(), on_traceColor_clicked(), on_traceDel_clicked(), on_traceDown_clicked(), on_traceIntensity_valueChanged(), on_traceLen_valueChanged(), on_traceUp_clicked(), on_trig_valueChanged(), on_trigBoth_toggled(), on_trigColor_clicked(), on_trigDel_clicked(), on_trigDown_clicked(), on_trigHoldoff_valueChanged(), on_trigNeg_toggled(), on_trigPos_toggled(), on_trigPre_valueChanged(), on_trigUp_clicked(), on_verticalXY_toggled(), serialize(), setAmpOfsDisplay(), setAmpScaleDisplay(), setBuddies(), setDisplayMode(), setGridIntensity(), setPreTrigger(), setTimeBase(), setTimeOffset(), setTimeOfsDisplay(), setTimeScaleDisplay(), setTraceDelayDisplay(), setTraceIndexDisplay(), setTraceIntensity(), setTraceLenDisplay(), setTraceLength(), setTraceUI(), setTrigCountDisplay(), setTrigDelayDisplay(), setTriggerUI(), setTrigIndexDisplay(), setTrigLevelDisplay(), setTrigPreDisplay(), and ~GLScopeGUI().
The documentation for this class was generated from the following files:
sdrgui/gui/glscopegui.h
sdrgui/gui/glscopegui.cpp