SDRAngel: AMDemod::MsgConfigureChannelizer Class Reference
AMDemod::MsgConfigureChannelizer Class Reference
#include <amdemod.h>
Public Member Functions
int getSampleRate () const
int getCenterFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (int sampleRate, int centerFrequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (int sampleRate, int centerFrequency)
Private Attributes
int m_sampleRate
int m_centerFrequency
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 74 of file amdemod.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
AMDemod::MsgConfigureChannelizer::MsgConfigureChannelizer (int sampleRate, int centerFrequency) inline private
Definition at line 90 of file amdemod.h.
References AMDemod::AMDemod(), and AMDemod::~AMDemod().
                                                                      :
             Message(),
             m_sampleRate(sampleRate),
             m_centerFrequency(centerFrequency)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* AMDemod::MsgConfigureChannelizer::create (int sampleRate, int centerFrequency) inline static
Definition at line 81 of file amdemod.h.
Referenced by AMDemod::applyAudioSampleRate(), AMDemodGUI::applySettings(), and AMDemod::webapiSettingsPutPatch().
         {
             return new MsgConfigureChannelizer(sampleRate, centerFrequency);
         }
getCenterFrequency()
int AMDemod::MsgConfigureChannelizer::getCenterFrequency () const inline
Definition at line 79 of file amdemod.h.
Referenced by AMDemod::handleMessage().
 { return m_centerFrequency; }
getSampleRate()
int AMDemod::MsgConfigureChannelizer::getSampleRate () const inline
Definition at line 78 of file amdemod.h.
Referenced by AMDemod::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_centerFrequency
int AMDemod::MsgConfigureChannelizer::m_centerFrequency private
Definition at line 88 of file amdemod.h.
m_sampleRate
int AMDemod::MsgConfigureChannelizer::m_sampleRate private
Definition at line 87 of file amdemod.h.
The documentation for this class was generated from the following file:
plugins/channelrx/demodam/amdemod.h