SDRAngel: TestSourceThread Class Reference
TestSourceThread Class Reference
#include <testsourcethread.h>
Inherits QThread.
Classes
class MsgStartStop
Public Member Functions
TestSourceThread (SampleSinkFifo *sampleFifo, QObject *parent=0)
~TestSourceThread ()
void startStop (bool start)
void setSamplerate (int samplerate)
void setLog2Decimation (unsigned int log2_decim)
void setFcPos (int fcPos)
void setBitSize (uint32_t bitSizeIndex)
void setAmplitudeBits (int32_t amplitudeBits)
void setDCFactor (float iFactor)
void setIFactor (float iFactor)
void setQFactor (float qFactor)
void setPhaseImbalance (float phaseImbalance)
void setFrequencyShift (int shift)
void setToneFrequency (int toneFrequency)
void setModulation (TestSourceSettings::Modulation modulation)
void setAMModulation (float amModulation)
void setFMDeviation (float deviation)
void setPattern0 ()
void setPattern1 ()
void setPattern2 ()
Private Slots
void tick ()
void handleInputMessages ()
Private Member Functions
void startWork ()
void stopWork ()
void run ()
void callback (const qint16 *buf, qint32 len)
void setBuffers (quint32 chunksize)
void generate (quint32 chunksize)
void pullAF (Real &afSample)
void convert_8 (SampleVector::iterator *it, const qint16 *buf, qint32 len)
void convert_12 (SampleVector::iterator *it, const qint16 *buf, qint32 len)
void convert_16 (SampleVector::iterator *it, const qint16 *buf, qint32 len)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
volatile bool m_running
qint16 * m_buf
quint32 m_bufsize
quint32 m_chunksize
SampleVector m_convertBuffer
SampleSinkFifo * m_sampleFifo
NCOF m_nco
NCOF m_toneNco
int m_frequencyShift
int m_toneFrequency
TestSourceSettings::Modulation m_modulation
float m_amModulation
float m_fmDeviationUnit
float m_fmPhasor
uint32_t m_pulseWidth
pulse width in number of samples
uint32_t m_pulseSampleCount
uint32_t m_pulsePatternCount
uint32_t m_pulsePatternCycle
uint32_t m_pulsePatternPlaces
int m_samplerate
unsigned int m_log2Decim
int m_fcPos
uint32_t m_bitSizeIndex
uint32_t m_bitShift
int32_t m_amplitudeBits
float m_dcBias
float m_iBias
float m_qBias
float m_phaseImbalance
int32_t m_amplitudeBitsDC
int32_t m_amplitudeBitsI
int32_t m_amplitudeBitsQ
uint64_t m_frequency
int m_fcPosShift
int m_throttlems
QTimer m_timer
QElapsedTimer m_elapsedTimer
bool m_throttleToggle
QMutex m_mutex
MessageQueue m_inputMessageQueue
Decimators< qint32, qint16, SDR_RX_SAMP_SZ, 8 > m_decimators_8
Decimators< qint32, qint16, SDR_RX_SAMP_SZ, 12 > m_decimators_12
Decimators< qint32, qint16, SDR_RX_SAMP_SZ, 16 > m_decimators_16
std::map< int, int > m_timerHistogram
uint32_t m_histoCounter
Detailed Description
Definition at line 40 of file testsourcethread.h.
Constructor & Destructor Documentation
TestSourceThread()
TestSourceThread::TestSourceThread (SampleSinkFifo * sampleFifo, QObject * parent = 0)
Definition at line 30 of file testsourcethread.cpp.
Referenced by TestSourceThread::MsgStartStop::MsgStartStop().
                                                                               :
     QThread(parent),
     m_running(false),
     m_buf(0),
     m_bufsize(0),
     m_chunksize(0),
     m_convertBuffer(TESTSOURCE_BLOCKSIZE),
     m_sampleFifo(sampleFifo),
     m_frequencyShift(0),
     m_toneFrequency(440),
     m_modulation(TestSourceSettings::ModulationNone),
     m_amModulation(0.5f),
     m_fmDeviationUnit(0.0f),
     m_fmPhasor(0.0f),
     m_pulseWidth(150),
     m_pulseSampleCount(0),
     m_pulsePatternCount(0),
     m_pulsePatternCycle(8),
     m_pulsePatternPlaces(3),
     m_samplerate(48000),
     m_log2Decim(4),
     m_fcPos(0),
     m_bitSizeIndex(0),
     m_bitShift(8),
     m_amplitudeBits(127),
     m_dcBias(0.0f),
     m_iBias(0.0f),
     m_qBias(0.0f),
     m_phaseImbalance(0.0f),
     m_amplitudeBitsDC(0),
     m_amplitudeBitsI(127),
     m_amplitudeBitsQ(127),
     m_frequency(435*1000),
     m_fcPosShift(0),
     m_throttlems(TESTSOURCE_THROTTLE_MS),
     m_throttleToggle(false),
     m_mutex(QMutex::Recursive),
     m_histoCounter(0)
 {
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
 }
~TestSourceThread()
TestSourceThread::~TestSourceThread ()
Definition at line 72 of file testsourcethread.cpp.
Referenced by TestSourceThread::MsgStartStop::MsgStartStop().
 {
 }
Member Function Documentation
callback()
void TestSourceThread::callback (const qint16 * buf, qint32 len) private
Definition at line 370 of file testsourcethread.cpp.
References convert_12(), convert_16(), convert_8(), m_bitSizeIndex, m_convertBuffer, m_sampleFifo, and SampleSinkFifo::write().
Referenced by generate().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     switch (m_bitSizeIndex)
     {
     case 0: // 8 bit samples
         convert_8(&it, buf, len);
         break;
     case 1: // 12 bit samples
         convert_12(&it, buf, len);
         break;
     case 2: // 16 bit samples
     default:
         convert_16(&it, buf, len);
         break;
     }
     m_sampleFifo->write(m_convertBuffer.begin(), it);
 }
convert_12()
void TestSourceThread::convert_12 (SampleVector::iterator * it, const qint16 * buf, qint32 len) inline private
Definition at line 228 of file testsourcethread.h.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf(), and Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup().
Referenced by callback().
     {
         if (m_log2Decim == 0) {
             m_decimators_12.decimate1(it, buf, len);
         } else {
             if (m_fcPos == 0) { // Infradyne
                 switch (m_log2Decim) {
                 case 1:
                     m_decimators_12.decimate2_inf(it, buf, len);
                     break;
                 case 2:
                     m_decimators_12.decimate4_inf(it, buf, len);
                     break;
                 case 3:
                     m_decimators_12.decimate8_inf(it, buf, len);
                     break;
                 case 4:
                     m_decimators_12.decimate16_inf(it, buf, len);
                     break;
                 case 5:
                     m_decimators_12.decimate32_inf(it, buf, len);
                     break;
                 case 6:
                     m_decimators_12.decimate64_inf(it, buf, len);
                     break;
                 default:
                     break;
                 }
             } else if (m_fcPos == 1)  {// Supradyne
                 switch (m_log2Decim) {
                 case 1:
                     m_decimators_12.decimate2_sup(it, buf, len);
                     break;
                 case 2:
                     m_decimators_12.decimate4_sup(it, buf, len);
                     break;
                 case 3:
                     m_decimators_12.decimate8_sup(it, buf, len);
                     break;
                 case 4:
                     m_decimators_12.decimate16_sup(it, buf, len);
                     break;
                 case 5:
                     m_decimators_12.decimate32_sup(it, buf, len);
                     break;
                 case 6:
                     m_decimators_12.decimate64_sup(it, buf, len);
                     break;
                 default:
                     break;
                 }
             } else { // Centered
                 switch (m_log2Decim) {
                 case 1:
                     m_decimators_12.decimate2_cen(it, buf, len);
                     break;
                 case 2:
                     m_decimators_12.decimate4_cen(it, buf, len);
                     break;
                 case 3:
                     m_decimators_12.decimate8_cen(it, buf, len);
                     break;
                 case 4:
                     m_decimators_12.decimate16_cen(it, buf, len);
                     break;
                 case 5:
                     m_decimators_12.decimate32_cen(it, buf, len);
                     break;
                 case 6:
                     m_decimators_12.decimate64_cen(it, buf, len);
                     break;
                 default:
                     break;
                 }
             }
         }
     }
convert_16()
void TestSourceThread::convert_16 (SampleVector::iterator * it, const qint16 * buf, qint32 len) inline private
Definition at line 306 of file testsourcethread.h.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup(), handleInputMessages(), and tick().
Referenced by callback().
     {
         if (m_log2Decim == 0) {
             m_decimators_16.decimate1(it, buf, len);
         } else {
             if (m_fcPos == 0) { // Infradyne
                 switch (m_log2Decim) {
                 case 1:
                     m_decimators_16.decimate2_inf(it, buf, len);
                     break;
                 case 2:
                     m_decimators_16.decimate4_inf(it, buf, len);
                     break;
                 case 3:
                     m_decimators_16.decimate8_inf(it, buf, len);
                     break;
                 case 4:
                     m_decimators_16.decimate16_inf(it, buf, len);
                     break;
                 case 5:
                     m_decimators_16.decimate32_inf(it, buf, len);
                     break;
                 case 6:
                     m_decimators_16.decimate64_inf(it, buf, len);
                     break;
                 default:
                     break;
                 }
             } else if (m_fcPos == 1)  {// Supradyne
                 switch (m_log2Decim) {
                 case 1:
                     m_decimators_16.decimate2_sup(it, buf, len);
                     break;
                 case 2:
                     m_decimators_16.decimate4_sup(it, buf, len);
                     break;
                 case 3:
                     m_decimators_16.decimate8_sup(it, buf, len);
                     break;
                 case 4:
                     m_decimators_16.decimate16_sup(it, buf, len);
                     break;
                 case 5:
                     m_decimators_16.decimate32_sup(it, buf, len);
                     break;
                 case 6:
                     m_decimators_16.decimate64_sup(it, buf, len);
                     break;
                 default:
                     break;
                 }
             } else { // Centered
                 switch (m_log2Decim) {
                 case 1:
                     m_decimators_16.decimate2_cen(it, buf, len);
                     break;
                 case 2:
                     m_decimators_16.decimate4_cen(it, buf, len);
                     break;
                 case 3:
                     m_decimators_16.decimate8_cen(it, buf, len);
                     break;
                 case 4:
                     m_decimators_16.decimate16_cen(it, buf, len);
                     break;
                 case 5:
                     m_decimators_16.decimate32_cen(it, buf, len);
                     break;
                 case 6:
                     m_decimators_16.decimate64_cen(it, buf, len);
                     break;
                 default:
                     break;
                 }
             }
         }
     }
convert_8()
void TestSourceThread::convert_8 (SampleVector::iterator * it, const qint16 * buf, qint32 len) inline private
Definition at line 150 of file testsourcethread.h.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf(), and Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup().
Referenced by callback().
     {
         if (m_log2Decim == 0) {
             m_decimators_8.decimate1(it, buf, len);
         } else {
             if (m_fcPos == 0) { // Infradyne
                 switch (m_log2Decim) {
                 case 1:
                     m_decimators_8.decimate2_inf(it, buf, len);
                     break;
                 case 2:
                     m_decimators_8.decimate4_inf(it, buf, len);
                     break;
                 case 3:
                     m_decimators_8.decimate8_inf(it, buf, len);
                     break;
                 case 4:
                     m_decimators_8.decimate16_inf(it, buf, len);
                     break;
                 case 5:
                     m_decimators_8.decimate32_inf(it, buf, len);
                     break;
                 case 6:
                     m_decimators_8.decimate64_inf(it, buf, len);
                     break;
                 default:
                     break;
                 }
             } else if (m_fcPos == 1)  {// Supradyne
                 switch (m_log2Decim) {
                 case 1:
                     m_decimators_8.decimate2_sup(it, buf, len);
                     break;
                 case 2:
                     m_decimators_8.decimate4_sup(it, buf, len);
                     break;
                 case 3:
                     m_decimators_8.decimate8_sup(it, buf, len);
                     break;
                 case 4:
                     m_decimators_8.decimate16_sup(it, buf, len);
                     break;
                 case 5:
                     m_decimators_8.decimate32_sup(it, buf, len);
                     break;
                 case 6:
                     m_decimators_8.decimate64_sup(it, buf, len);
                     break;
                 default:
                     break;
                 }
             } else { // Centered
                 switch (m_log2Decim) {
                 case 1:
                     m_decimators_8.decimate2_cen(it, buf, len);
                     break;
                 case 2:
                     m_decimators_8.decimate4_cen(it, buf, len);
                     break;
                 case 3:
                     m_decimators_8.decimate8_cen(it, buf, len);
                     break;
                 case 4:
                     m_decimators_8.decimate16_cen(it, buf, len);
                     break;
                 case 5:
                     m_decimators_8.decimate32_cen(it, buf, len);
                     break;
                 case 6:
                     m_decimators_8.decimate64_cen(it, buf, len);
                     break;
                 default:
                     break;
                 }
             }
         }
     }
generate()
void TestSourceThread::generate (quint32 chunksize) private
Definition at line 241 of file testsourcethread.cpp.
References callback(), cos(), i, m_amModulation, m_amplitudeBitsDC, m_amplitudeBitsI, m_amplitudeBitsQ, m_buf, m_fmDeviationUnit, m_fmPhasor, m_modulation, m_nco, m_phaseImbalance, M_PI, m_pulsePatternCount, m_pulsePatternCycle, m_pulsePatternPlaces, m_pulseSampleCount, m_pulseWidth, TestSourceSettings::ModulationAM, TestSourceSettings::ModulationFM, TestSourceSettings::ModulationNone, TestSourceSettings::ModulationPattern0, TestSourceSettings::ModulationPattern1, TestSourceSettings::ModulationPattern2, NCOF::nextIQ(), pullAF(), setBuffers(), and sin().
Referenced by tick().
 {
     int n = chunksize / 2;
     setBuffers(chunksize);
     for (int i = 0; i < n-1;)
     {
         switch (m_modulation)
         {
         case TestSourceSettings::ModulationAM:
         {
             Complex c = m_nco.nextIQ();
             Real t, re, im;
             pullAF(t);
             t = (t*m_amModulation + 1.0f)*0.5f;
             re = c.real()*t;
             im = c.imag()*t + m_phaseImbalance*re;
             m_buf[i++] = (int16_t) (re * (float) m_amplitudeBitsI) + m_amplitudeBitsDC;
             m_buf[i++] = (int16_t) (im * (float) m_amplitudeBitsQ);
         }
         break;
         case TestSourceSettings::ModulationFM:
         {
             Complex c = m_nco.nextIQ();
             Real t, re, im;
             pullAF(t);
             m_fmPhasor += m_fmDeviationUnit * t;
             m_fmPhasor = m_fmPhasor < -1.0f ? -m_fmPhasor - 1.0f  : m_fmPhasor > 1.0f ? m_fmPhasor - 1.0f : m_fmPhasor;
             re =  c.real()*cos(m_fmPhasor*M_PI) - c.imag()*sin(m_fmPhasor*M_PI);
             im = (c.real()*sin(m_fmPhasor*M_PI) + c.imag()*cos(m_fmPhasor*M_PI)) + m_phaseImbalance*re;
             m_buf[i++] = (int16_t) (re * (float) m_amplitudeBitsI) + m_amplitudeBitsDC;
             m_buf[i++] = (int16_t) (im * (float) m_amplitudeBitsQ);
         }
         break;
         case TestSourceSettings::ModulationPattern0: // binary pattern
         {
             if (m_pulseSampleCount < m_pulseWidth) // sync pattern: 0
             {
                 m_buf[i++] = m_amplitudeBitsDC;
                 m_buf[i++] = 0;
             }
             else if (m_pulseSampleCount < 2*m_pulseWidth) // sync pattern: 1
             {
                 m_buf[i++] = (int16_t) (m_amplitudeBitsI + m_amplitudeBitsDC);
                 m_buf[i++] = (int16_t) (m_phaseImbalance * (float) m_amplitudeBitsQ);
             }
             else if (m_pulseSampleCount < 3*m_pulseWidth) // sync pattern: 0
             {
                 m_buf[i++] = m_amplitudeBitsDC;
                 m_buf[i++] = 0;
             }
             else if (m_pulseSampleCount < (3+m_pulsePatternPlaces)*m_pulseWidth) // binary pattern
             {
                 uint32_t patPulseSampleCount = m_pulseSampleCount - 3*m_pulseWidth;
                 uint32_t patPulseIndex = patPulseSampleCount / m_pulseWidth;
                 float patFigure = (m_pulsePatternCount & (1<<patPulseIndex)) != 0 ? 0.3 : 0.0; // make binary pattern ~-10dB vs sync pattern
                 m_buf[i++] = (int16_t) (patFigure * (float) m_amplitudeBitsI) + m_amplitudeBitsDC;
                 m_buf[i++] = (int16_t) (patFigure * (float) m_phaseImbalance * m_amplitudeBitsQ);
             }
             if (m_pulseSampleCount < (4+m_pulsePatternPlaces)*m_pulseWidth - 1)
             {
                 m_pulseSampleCount++;
             }
             else
             {
                 if (m_pulsePatternCount < m_pulsePatternCycle - 1) {
                     m_pulsePatternCount++;
                 } else {
                     m_pulsePatternCount = 0;
                 }
                 m_pulseSampleCount = 0;
             }
         }
         break;
         case TestSourceSettings::ModulationPattern1: // sawtooth pattern
         {
             Real re, im;
             re = (float) (m_pulseWidth - m_pulseSampleCount) / (float) m_pulseWidth;
             im = m_phaseImbalance*re;
             m_buf[i++] = (int16_t) (re * (float) m_amplitudeBitsI) + m_amplitudeBitsDC;
             m_buf[i++] = (int16_t) (im * (float) m_amplitudeBitsQ);
             if (m_pulseSampleCount < m_pulseWidth - 1) {
                 m_pulseSampleCount++;
             } else {
                 m_pulseSampleCount = 0;
             }
         }
         break;
         case TestSourceSettings::ModulationPattern2: // 50% duty cycle square pattern
         {
             if (m_pulseSampleCount < m_pulseWidth) // 1
             {
                 m_buf[i++] = (int16_t) (m_amplitudeBitsI + m_amplitudeBitsDC);
                 m_buf[i++] = (int16_t) (m_phaseImbalance * (float) m_amplitudeBitsQ);
             } else { // 0
                 m_buf[i++] = m_amplitudeBitsDC;
                 m_buf[i++] = 0;
             }
             if (m_pulseSampleCount < 2*m_pulseWidth - 1) {
                 m_pulseSampleCount++;
             } else {
                 m_pulseSampleCount = 0;
             }
         }
         break;
         case TestSourceSettings::ModulationNone:
         default:
         {
             Complex c = m_nco.nextIQ(m_phaseImbalance);
             m_buf[i++] = (int16_t) (c.real() * (float) m_amplitudeBitsI) + m_amplitudeBitsDC;
             m_buf[i++] = (int16_t) (c.imag() * (float) m_amplitudeBitsQ);
         }
         break;
         }
     }
     callback(m_buf, n);
 }
handleInputMessages
void TestSourceThread::handleInputMessages () private slot
Definition at line 428 of file testsourcethread.cpp.
References TestSourceThread::MsgStartStop::getStartStop(), m_inputMessageQueue, Message::match(), MessageQueue::pop(), startWork(), and stopWork().
Referenced by convert_16().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (MsgStartStop::match(*message))
         {
             MsgStartStop* notif = (MsgStartStop*) message;
             qDebug("TestSourceThread::handleInputMessages: MsgStartStop: %s", notif->getStartStop() ? "start" : "stop");
             if (notif->getStartStop()) {
                 startWork();
             } else {
                 stopWork();
             }
             delete message;
         }
     }
 }
pullAF()
void TestSourceThread::pullAF (Real & afSample) private
Definition at line 364 of file testsourcethread.cpp.
References m_toneNco, and NCOF::next().
Referenced by generate().
 {
     afSample = m_toneNco.next();
 }
run()
void TestSourceThread::run () private
Definition at line 202 of file testsourcethread.cpp.
References m_running, and m_startWaiter.
 {
     m_running = true;
     m_startWaiter.wakeAll();
     while (m_running) // actual work is in the tick() function
     {
         sleep(1);
     }
     m_running = false;
 }
setAMModulation()
void TestSourceThread::setAMModulation (float amModulation)
Definition at line 184 of file testsourcethread.cpp.
References m_amModulation.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_amModulation = amModulation < 0.0f ? 0.0f : amModulation > 1.0f ? 1.0f : amModulation;
 }
setAmplitudeBits()
void TestSourceThread::setAmplitudeBits (int32_t amplitudeBits)
Definition at line 138 of file testsourcethread.cpp.
References m_amplitudeBits, m_amplitudeBitsDC, m_amplitudeBitsI, m_amplitudeBitsQ, m_dcBias, m_iBias, and m_qBias.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_amplitudeBits = amplitudeBits;
     m_amplitudeBitsDC = m_dcBias * amplitudeBits;
     m_amplitudeBitsI = (1.0f + m_iBias) * amplitudeBits;
     m_amplitudeBitsQ = (1.0f + m_qBias) * amplitudeBits;
 }
setBitSize()
void TestSourceThread::setBitSize (uint32_t bitSizeIndex)
Definition at line 118 of file testsourcethread.cpp.
References m_bitShift, and m_bitSizeIndex.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     switch (bitSizeIndex)
     {
     case 0:
         m_bitShift = 7;
         m_bitSizeIndex = 0;
         break;
     case 1:
         m_bitShift = 11;
         m_bitSizeIndex = 1;
         break;
     case 2:
     default:
         m_bitShift = 15;
         m_bitSizeIndex = 2;
         break;
     }
 }
setBuffers()
void TestSourceThread::setBuffers (quint32 chunksize) private
Definition at line 215 of file testsourcethread.cpp.
References m_buf, m_bufsize, and m_convertBuffer.
Referenced by generate().
 {
     if (chunksize > m_bufsize)
     {
         m_bufsize = chunksize;
         if (m_buf == 0)
         {
             qDebug() << "TestSourceThread::setBuffer: Allocate buffer:    "
                     << " size: " << m_bufsize << " bytes"
                     << " #samples: " << (m_bufsize/4);
             m_buf = (qint16*) malloc(m_bufsize);
         }
         else
         {
             qDebug() << "TestSourceThread::setBuffer: Re-allocate buffer: "
                     << " size: " << m_bufsize << " bytes"
                     << " #samples: " << (m_bufsize/4);
             free(m_buf);
             m_buf = (qint16*) malloc(m_bufsize);
         }
         m_convertBuffer.resize(chunksize/4);
     }
 }
setDCFactor()
void TestSourceThread::setDCFactor (float iFactor)
Definition at line 146 of file testsourcethread.cpp.
References m_amplitudeBits, m_amplitudeBitsDC, and m_dcBias.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_dcBias = dcFactor;
     m_amplitudeBitsDC = m_dcBias * m_amplitudeBits;
 }
setFcPos()
void TestSourceThread::setFcPos (int fcPos)
Definition at line 113 of file testsourcethread.cpp.
References m_fcPos.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_fcPos = fcPos;
 }
setFMDeviation()
void TestSourceThread::setFMDeviation (float deviation)
Definition at line 189 of file testsourcethread.cpp.
References m_fmDeviationUnit, and m_samplerate.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     float fmDeviationUnit = deviation / (float) m_samplerate;
     m_fmDeviationUnit = fmDeviationUnit < 0.0f ? 0.0f : fmDeviationUnit > 0.5f ? 0.5f : fmDeviationUnit;
     qDebug("TestSourceThread::setFMDeviation: m_fmDeviationUnit: %f", m_fmDeviationUnit);
 }
setFrequencyShift()
void TestSourceThread::setFrequencyShift (int shift)
Definition at line 169 of file testsourcethread.cpp.
References m_nco, m_samplerate, and NCOF::setFreq().
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_nco.setFreq(shift, m_samplerate);
 }
setIFactor()
void TestSourceThread::setIFactor (float iFactor)
Definition at line 152 of file testsourcethread.cpp.
References m_amplitudeBits, m_amplitudeBitsI, and m_iBias.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_iBias = iFactor;
     m_amplitudeBitsI = (1.0f + m_iBias) * m_amplitudeBits;
 }
setLog2Decimation()
void TestSourceThread::setLog2Decimation (unsigned int log2_decim)
Definition at line 108 of file testsourcethread.cpp.
References m_log2Decim.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_log2Decim = log2_decim;
 }
setModulation()
void TestSourceThread::setModulation (TestSourceSettings::Modulation modulation)
Definition at line 179 of file testsourcethread.cpp.
References m_modulation.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_modulation = modulation;
 }
setPattern0()
void TestSourceThread::setPattern0 ()
Definition at line 450 of file testsourcethread.cpp.
References m_pulsePatternCount, m_pulsePatternCycle, m_pulsePatternPlaces, m_pulseSampleCount, and m_pulseWidth.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_pulseWidth = 150;
     m_pulseSampleCount = 0;
     m_pulsePatternCount = 0;
     m_pulsePatternCycle = 8;
     m_pulsePatternPlaces = 3;
 }
setPattern1()
void TestSourceThread::setPattern1 ()
Definition at line 459 of file testsourcethread.cpp.
References m_pulseSampleCount, and m_pulseWidth.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_pulseWidth = 1000;
     m_pulseSampleCount = 0;
 }
setPattern2()
void TestSourceThread::setPattern2 ()
Definition at line 465 of file testsourcethread.cpp.
References m_pulseSampleCount, and m_pulseWidth.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_pulseWidth = 1000;
     m_pulseSampleCount = 0;
 }
setPhaseImbalance()
void TestSourceThread::setPhaseImbalance (float phaseImbalance)
Definition at line 164 of file testsourcethread.cpp.
References m_phaseImbalance.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_phaseImbalance = phaseImbalance;
 }
setQFactor()
void TestSourceThread::setQFactor (float qFactor)
Definition at line 158 of file testsourcethread.cpp.
References m_amplitudeBits, m_amplitudeBitsQ, and m_qBias.
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_qBias = iFactor;
     m_amplitudeBitsQ = (1.0f + m_qBias) * m_amplitudeBits;
 }
setSamplerate()
void TestSourceThread::setSamplerate (int samplerate)
Definition at line 97 of file testsourcethread.cpp.
References m_chunksize, m_frequencyShift, m_mutex, m_nco, m_samplerate, m_throttlems, m_throttleToggle, m_toneFrequency, m_toneNco, and NCOF::setFreq().
Referenced by TestSourceInput::applySettings(), TestSourceThread::MsgStartStop::MsgStartStop(), and TestSourceInput::start().
 {
     QMutexLocker mutexLocker(&m_mutex);
     m_samplerate = samplerate;
     m_chunksize = 4 * ((m_samplerate * (m_throttlems+(m_throttleToggle ? 1 : 0))) / 1000);
     m_throttleToggle = !m_throttleToggle;
     m_nco.setFreq(m_frequencyShift, m_samplerate);
     m_toneNco.setFreq(m_toneFrequency, m_samplerate);
 }
setToneFrequency()
void TestSourceThread::setToneFrequency (int toneFrequency)
Definition at line 174 of file testsourcethread.cpp.
References m_samplerate, m_toneNco, and NCOF::setFreq().
Referenced by TestSourceInput::applySettings(), and TestSourceThread::MsgStartStop::MsgStartStop().
 {
     m_toneNco.setFreq(toneFrequency, m_samplerate);
 }
startStop()
void TestSourceThread::startStop (bool start)
Definition at line 196 of file testsourcethread.cpp.
References TestSourceThread::MsgStartStop::create(), m_inputMessageQueue, and MessageQueue::push().
Referenced by TestSourceThread::MsgStartStop::MsgStartStop(), TestSourceInput::start(), and TestSourceInput::stop().
 {
     MsgStartStop *msg = MsgStartStop::create(start);
     m_inputMessageQueue.push(msg);
 }
startWork()
void TestSourceThread::startWork () private
Definition at line 76 of file testsourcethread.cpp.
References m_elapsedTimer, m_running, m_startWaiter, m_startWaitMutex, m_timer, and tick().
Referenced by handleInputMessages().
 {
     m_timer.setTimerType(Qt::PreciseTimer);
     connect(&m_timer, SIGNAL(timeout()), this, SLOT(tick()));
     m_timer.start(50);
     m_startWaitMutex.lock();
     m_elapsedTimer.start();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void TestSourceThread::stopWork () private
Definition at line 89 of file testsourcethread.cpp.
References m_running, m_timer, and tick().
Referenced by handleInputMessages().
 {
     m_running = false;
     wait();
     m_timer.stop();
     disconnect(&m_timer, SIGNAL(timeout()), this, SLOT(tick()));
 }
tick
void TestSourceThread::tick () private slot
Definition at line 391 of file testsourcethread.cpp.
References generate(), m_chunksize, m_elapsedTimer, m_histoCounter, m_mutex, m_running, m_samplerate, m_throttlems, m_throttleToggle, and m_timerHistogram.
Referenced by convert_16(), startWork(), and stopWork().
 {
     if (m_running)
     {
         qint64 throttlems = m_elapsedTimer.restart();
         std::map<int,int>::iterator it;
         it = m_timerHistogram.find(throttlems);
         if (it == m_timerHistogram.end()) {
             m_timerHistogram[throttlems] = 1;
         } else {
             it->second++;
         }
         if (m_histoCounter < 49) {
             m_histoCounter++;
         } else {
             qDebug("TestSourceThread::tick: -----------");
             for (std::map<int,int>::iterator it = m_timerHistogram.begin(); it != m_timerHistogram.end(); ++it) {
                 qDebug("TestSourceThread::tick: %d: %d", it->first, it->second);
             }
             m_histoCounter = 0;
         }
         if ((throttlems > 45) && (throttlems < 55) && (throttlems != m_throttlems))
         {
             QMutexLocker mutexLocker(&m_mutex);
             m_throttlems = throttlems;
             m_chunksize = 4 * ((m_samplerate * (m_throttlems+(m_throttleToggle ? 1 : 0))) / 1000);
             m_throttleToggle = !m_throttleToggle;
         }
         generate(m_chunksize);
     }
 }
Member Data Documentation
m_amModulation
float TestSourceThread::m_amModulation private
Definition at line 100 of file testsourcethread.h.
Referenced by generate(), and setAMModulation().
m_amplitudeBits
int32_t TestSourceThread::m_amplitudeBits private
Definition at line 114 of file testsourcethread.h.
Referenced by setAmplitudeBits(), setDCFactor(), setIFactor(), and setQFactor().
m_amplitudeBitsDC
int32_t TestSourceThread::m_amplitudeBitsDC private
Definition at line 119 of file testsourcethread.h.
Referenced by generate(), setAmplitudeBits(), and setDCFactor().
m_amplitudeBitsI
int32_t TestSourceThread::m_amplitudeBitsI private
Definition at line 120 of file testsourcethread.h.
Referenced by generate(), setAmplitudeBits(), and setIFactor().
m_amplitudeBitsQ
int32_t TestSourceThread::m_amplitudeBitsQ private
Definition at line 121 of file testsourcethread.h.
Referenced by generate(), setAmplitudeBits(), and setQFactor().
m_bitShift
uint32_t TestSourceThread::m_bitShift private
Definition at line 113 of file testsourcethread.h.
Referenced by setBitSize().
m_bitSizeIndex
uint32_t TestSourceThread::m_bitSizeIndex private
Definition at line 112 of file testsourcethread.h.
Referenced by callback(), and setBitSize().
m_buf
qint16* TestSourceThread::m_buf private
Definition at line 90 of file testsourcethread.h.
Referenced by generate(), and setBuffers().
m_bufsize
quint32 TestSourceThread::m_bufsize private
Definition at line 91 of file testsourcethread.h.
Referenced by setBuffers().
m_chunksize
quint32 TestSourceThread::m_chunksize private
Definition at line 92 of file testsourcethread.h.
Referenced by setSamplerate(), and tick().
m_convertBuffer
SampleVector TestSourceThread::m_convertBuffer private
Definition at line 93 of file testsourcethread.h.
Referenced by callback(), and setBuffers().
m_dcBias
float TestSourceThread::m_dcBias private
Definition at line 115 of file testsourcethread.h.
Referenced by setAmplitudeBits(), and setDCFactor().
m_decimators_12
Decimators<qint32, qint16, SDR_RX_SAMP_SZ, 12> TestSourceThread::m_decimators_12 private
Definition at line 135 of file testsourcethread.h.
m_decimators_16
Decimators<qint32, qint16, SDR_RX_SAMP_SZ, 16> TestSourceThread::m_decimators_16 private
Definition at line 136 of file testsourcethread.h.
m_decimators_8
Decimators<qint32, qint16, SDR_RX_SAMP_SZ, 8> TestSourceThread::m_decimators_8 private
Definition at line 134 of file testsourcethread.h.
m_elapsedTimer
QElapsedTimer TestSourceThread::m_elapsedTimer private
Definition at line 128 of file testsourcethread.h.
Referenced by startWork(), and tick().
m_fcPos
int TestSourceThread::m_fcPos private
Definition at line 111 of file testsourcethread.h.
Referenced by setFcPos().
m_fcPosShift
int TestSourceThread::m_fcPosShift private
Definition at line 124 of file testsourcethread.h.
m_fmDeviationUnit
float TestSourceThread::m_fmDeviationUnit private
Definition at line 101 of file testsourcethread.h.
Referenced by generate(), and setFMDeviation().
m_fmPhasor
float TestSourceThread::m_fmPhasor private
Definition at line 102 of file testsourcethread.h.
Referenced by generate().
m_frequency
uint64_t TestSourceThread::m_frequency private
Definition at line 123 of file testsourcethread.h.
m_frequencyShift
int TestSourceThread::m_frequencyShift private
Definition at line 97 of file testsourcethread.h.
Referenced by setSamplerate().
m_histoCounter
uint32_t TestSourceThread::m_histoCounter private
Definition at line 139 of file testsourcethread.h.
Referenced by tick().
m_iBias
float TestSourceThread::m_iBias private
Definition at line 116 of file testsourcethread.h.
Referenced by setAmplitudeBits(), and setIFactor().
m_inputMessageQueue
MessageQueue TestSourceThread::m_inputMessageQueue private
Definition at line 132 of file testsourcethread.h.
Referenced by handleInputMessages(), and startStop().
m_log2Decim
unsigned int TestSourceThread::m_log2Decim private
Definition at line 110 of file testsourcethread.h.
Referenced by setLog2Decimation().
m_modulation
TestSourceSettings::Modulation TestSourceThread::m_modulation private
Definition at line 99 of file testsourcethread.h.
Referenced by generate(), and setModulation().
m_mutex
QMutex TestSourceThread::m_mutex private
Definition at line 130 of file testsourcethread.h.
Referenced by setSamplerate(), and tick().
m_nco
NCOF TestSourceThread::m_nco private
Definition at line 95 of file testsourcethread.h.
Referenced by generate(), setFrequencyShift(), and setSamplerate().
m_phaseImbalance
float TestSourceThread::m_phaseImbalance private
Definition at line 118 of file testsourcethread.h.
Referenced by generate(), and setPhaseImbalance().
m_pulsePatternCount
uint32_t TestSourceThread::m_pulsePatternCount private
Definition at line 105 of file testsourcethread.h.
Referenced by generate(), and setPattern0().
m_pulsePatternCycle
uint32_t TestSourceThread::m_pulsePatternCycle private
Definition at line 106 of file testsourcethread.h.
Referenced by generate(), and setPattern0().
m_pulsePatternPlaces
uint32_t TestSourceThread::m_pulsePatternPlaces private
Definition at line 107 of file testsourcethread.h.
Referenced by generate(), and setPattern0().
m_pulseSampleCount
uint32_t TestSourceThread::m_pulseSampleCount private
Definition at line 104 of file testsourcethread.h.
Referenced by generate(), setPattern0(), setPattern1(), and setPattern2().
m_pulseWidth
uint32_t TestSourceThread::m_pulseWidth private
pulse width in number of samples
Definition at line 103 of file testsourcethread.h.
Referenced by generate(), setPattern0(), setPattern1(), and setPattern2().
m_qBias
float TestSourceThread::m_qBias private
Definition at line 117 of file testsourcethread.h.
Referenced by setAmplitudeBits(), and setQFactor().
m_running
volatile bool TestSourceThread::m_running private
Definition at line 88 of file testsourcethread.h.
Referenced by run(), startWork(), stopWork(), and tick().
m_sampleFifo
SampleSinkFifo* TestSourceThread::m_sampleFifo private
Definition at line 94 of file testsourcethread.h.
Referenced by callback().
m_samplerate
int TestSourceThread::m_samplerate private
Definition at line 109 of file testsourcethread.h.
Referenced by setFMDeviation(), setFrequencyShift(), setSamplerate(), setToneFrequency(), and tick().
m_startWaiter
QWaitCondition TestSourceThread::m_startWaiter private
Definition at line 87 of file testsourcethread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex TestSourceThread::m_startWaitMutex private
Definition at line 86 of file testsourcethread.h.
Referenced by startWork().
m_throttlems
int TestSourceThread::m_throttlems private
Definition at line 126 of file testsourcethread.h.
Referenced by setSamplerate(), and tick().
m_throttleToggle
bool TestSourceThread::m_throttleToggle private
Definition at line 129 of file testsourcethread.h.
Referenced by setSamplerate(), and tick().
m_timer
QTimer TestSourceThread::m_timer private
Definition at line 127 of file testsourcethread.h.
Referenced by startWork(), and stopWork().
m_timerHistogram
std::map<int, int> TestSourceThread::m_timerHistogram private
Definition at line 138 of file testsourcethread.h.
Referenced by tick().
m_toneFrequency
int TestSourceThread::m_toneFrequency private
Definition at line 98 of file testsourcethread.h.
Referenced by setSamplerate().
m_toneNco
NCOF TestSourceThread::m_toneNco private
Definition at line 96 of file testsourcethread.h.
Referenced by pullAF(), setSamplerate(), and setToneFrequency().
The documentation for this class was generated from the following files:
plugins/samplesource/testsource/testsourcethread.h
plugins/samplesource/testsource/testsourcethread.cpp