SDRAngel: SDRPlayThread Class Reference
SDRPlayThread Class Reference
#include <sdrplaythread.h>
Inherits QThread.
Public Member Functions
SDRPlayThread (mirisdr_dev_t *dev, SampleSinkFifo *sampleFifo, QObject *parent=NULL)
~SDRPlayThread ()
void startWork ()
void stopWork ()
void setSamplerate (int samplerate)
void setLog2Decimation (unsigned int log2_decim)
void setFcPos (int fcPos)
Private Member Functions
void run ()
void callback (const qint16 *buf, qint32 len)
Static Private Member Functions
static void callbackHelper (unsigned char *buf, uint32_t len, void *ctx)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
mirisdr_dev_t * m_dev
SampleVector m_convertBuffer
SampleSinkFifo * m_sampleFifo
int m_samplerate
unsigned int m_log2Decim
int m_fcPos
Decimators< qint32, qint16, SDR_RX_SAMP_SZ, 12 > m_decimators
Detailed Description
Definition at line 30 of file sdrplaythread.h.
Constructor & Destructor Documentation
SDRPlayThread()
SDRPlayThread::SDRPlayThread (mirisdr_dev_t * dev, SampleSinkFifo * sampleFifo, QObject * parent = NULL)
Definition at line 23 of file sdrplaythread.cpp.
                                                                                             :
     QThread(parent),
     m_running(false),
     m_dev(dev),
     m_convertBuffer(SDRPLAY_INIT_NBSAMPLES),
     m_sampleFifo(sampleFifo),
     m_samplerate(288000),
     m_log2Decim(0),
     m_fcPos(0)
 {
 }
~SDRPlayThread()
SDRPlayThread::~SDRPlayThread ()
Definition at line 35 of file sdrplaythread.cpp.
References stopWork().
 {
     stopWork();
 }
Member Function Documentation
callback()
void SDRPlayThread::callback (const qint16 * buf, qint32 len) private
Definition at line 95 of file sdrplaythread.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup(), m_convertBuffer, m_decimators, m_dev, m_fcPos, m_log2Decim, m_running, m_sampleFifo, and SampleSinkFifo::write().
Referenced by callbackHelper().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     if (m_log2Decim == 0)
     {
         m_decimators.decimate1(&it, buf, len);
     }
     else
     {
         if (m_fcPos == 0) // Infradyne
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_inf(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_inf(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_inf(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_inf(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_inf(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_inf(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 1) // Supradyne
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_sup(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_sup(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_sup(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_sup(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_sup(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_sup(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else // Centered
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_cen(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_cen(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_cen(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_cen(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_cen(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_cen(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
     }
     m_sampleFifo->write(m_convertBuffer.begin(), it);
     if(!m_running)
     {
         mirisdr_cancel_async(m_dev);
     }
 }
callbackHelper()
void SDRPlayThread::callbackHelper (unsigned char * buf, uint32_t len, void * ctx) static private
Definition at line 89 of file sdrplaythread.cpp.
References callback().
Referenced by run().
 {
     SDRPlayThread* thread = (SDRPlayThread*) ctx;
     thread->callback((const qint16*) buf, len/2);
 }
run()
void SDRPlayThread::run () private
Definition at line 70 of file sdrplaythread.cpp.
References callbackHelper(), m_dev, m_running, m_startWaiter, and SDRPLAY_INIT_NBSAMPLES.
 {
     int res;
     m_running = true;
     m_startWaiter.wakeAll();
     while (m_running)
     {
         if ((res = mirisdr_read_async(m_dev, &SDRPlayThread::callbackHelper, this, 32, SDRPLAY_INIT_NBSAMPLES)) < 0)
         {
             qCritical("SDRPlayThread::run: async read error: rc %d: %s", res, strerror(errno));
             break;
         }
     }
     m_running = false;
 }
setFcPos()
void SDRPlayThread::setFcPos (int fcPos)
Definition at line 65 of file sdrplaythread.cpp.
References m_fcPos.
Referenced by SDRPlayInput::applySettings(), and SDRPlayInput::start().
 {
     m_fcPos = fcPos;
 }
setLog2Decimation()
void SDRPlayThread::setLog2Decimation (unsigned int log2_decim)
Definition at line 60 of file sdrplaythread.cpp.
References m_log2Decim.
Referenced by SDRPlayInput::applySettings(), and SDRPlayInput::start().
 {
     m_log2Decim = log2_decim;
 }
setSamplerate()
void SDRPlayThread::setSamplerate (int samplerate)
Definition at line 55 of file sdrplaythread.cpp.
References m_samplerate.
 {
     m_samplerate = samplerate;
 }
startWork()
void SDRPlayThread::startWork ()
Definition at line 40 of file sdrplaythread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by SDRPlayInput::start().
 {
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void SDRPlayThread::stopWork ()
Definition at line 49 of file sdrplaythread.cpp.
References m_running.
Referenced by SDRPlayInput::stop(), and ~SDRPlayThread().
 {
     m_running = false;
     wait();
 }
Member Data Documentation
m_convertBuffer
SampleVector SDRPlayThread::m_convertBuffer private
Definition at line 49 of file sdrplaythread.h.
Referenced by callback().
m_decimators
Decimators<qint32, qint16, SDR_RX_SAMP_SZ, 12> SDRPlayThread::m_decimators private
Definition at line 56 of file sdrplaythread.h.
Referenced by callback().
m_dev
mirisdr_dev_t* SDRPlayThread::m_dev private
Definition at line 48 of file sdrplaythread.h.
Referenced by callback(), and run().
m_fcPos
int SDRPlayThread::m_fcPos private
Definition at line 54 of file sdrplaythread.h.
Referenced by callback(), and setFcPos().
m_log2Decim
unsigned int SDRPlayThread::m_log2Decim private
Definition at line 53 of file sdrplaythread.h.
Referenced by callback(), and setLog2Decimation().
m_running
bool SDRPlayThread::m_running private
Definition at line 46 of file sdrplaythread.h.
Referenced by callback(), run(), startWork(), and stopWork().
m_sampleFifo
SampleSinkFifo* SDRPlayThread::m_sampleFifo private
Definition at line 50 of file sdrplaythread.h.
Referenced by callback().
m_samplerate
int SDRPlayThread::m_samplerate private
Definition at line 52 of file sdrplaythread.h.
Referenced by setSamplerate().
m_startWaiter
QWaitCondition SDRPlayThread::m_startWaiter private
Definition at line 45 of file sdrplaythread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex SDRPlayThread::m_startWaitMutex private
Definition at line 44 of file sdrplaythread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/samplesource/sdrplay/sdrplaythread.h
plugins/samplesource/sdrplay/sdrplaythread.cpp