SDRAngel: Lowpass< Type > Class Template Reference
Lowpass< Type > Class Template Reference
#include <lowpass.h>
Public Member Functions
Lowpass ()
void create (int nTaps, double sampleRate, double cutoff)
Type filter (Type sample)
Private Attributes
std::vector< Real > m_taps
std::vector< Type > m_samples
int m_ptr
Detailed Description
template<class Type>
class Lowpass< Type >
Definition at line 11 of file lowpass.h.
Constructor & Destructor Documentation
Lowpass()
template<class Type> Lowpass< Type >::Lowpass () inline
Definition at line 13 of file lowpass.h.
 : m_ptr(0) { }
Member Function Documentation
create()
template<class Type> void Lowpass< Type >::create (int nTaps, double sampleRate, double cutoff) inline
Definition at line 15 of file lowpass.h.
Referenced by AMDemod::AMDemod(), AMDemod::applyAudioSampleRate(), NFMDemod::applyAudioSampleRate(), NFMMod::applyAudioSampleRate(), AMDemod::applySettings(), NFMDemod::applySettings(), BFMDemod::applySettings(), NFMMod::applySettings(), and NFMMod::NFMMod().
     {
         double wc = 2.0 * M_PI * cutoff;
         double Wc = wc / sampleRate;
         int i;
         // check constraints
         if(!(nTaps & 1)) {
             qDebug("Lowpass filter has to have an odd number of taps");
             nTaps++;
         }
         // make room
         m_samples.resize(nTaps);
         for(int i = 0; i < nTaps; i++)
             m_samples[i] = 0;
         m_ptr = 0;
         m_taps.resize(nTaps / 2 + 1);
         // generate Sinc filter core
         for(i = 0; i < nTaps / 2 + 1; i++) {
             if(i == (nTaps - 1) / 2)
                 m_taps[i] = Wc / M_PI;
             else
                 m_taps[i] = sin(((double)i - ((double)nTaps - 1.0) / 2.0) * Wc) / (((double)i - ((double)nTaps - 1.0) / 2.0) * M_PI);
         }
         // apply Hamming window
         for(i = 0; i < nTaps / 2 + 1; i++)
             m_taps[i] *= 0.54 + 0.46 * cos((2.0 * M_PI * ((double)i - ((double)nTaps - 1.0) / 2.0)) / (double)nTaps);
         // normalize
         Real sum = 0;
         for(i = 0; i < (int)m_taps.size() - 1; i++)
             sum += m_taps[i] * 2;
         sum += m_taps[i];
         for(i = 0; i < (int)m_taps.size(); i++)
             m_taps[i] /= sum;
     }
filter()
template<class Type> Type Lowpass< Type >::filter (Type sample) inline
Definition at line 55 of file lowpass.h.
Referenced by AMDemod::processOneSample(), and NFMDemod::processOneSample().
     {
         Type acc = 0;
         int a = m_ptr;
         int b = a - 1;
         int i, n_taps, size;
         m_samples[m_ptr] = sample;
         size = m_samples.size(); // Valgrind optim (2)
         while (b < 0)
         {
             b += size;
         }
         n_taps = m_taps.size() - 1; // Valgrind optim
         for (i = 0; i < n_taps; i++)
         {
             acc += (m_samples[a] + m_samples[b]) * m_taps[i];
             a++;
             while (a >= size)
             {
                 a -= size;
             }
             b--;
             while(b < 0)
             {
                 b += size;
             }
         }
         acc += m_samples[a] * m_taps[i];
         m_ptr++;
         while(m_ptr >= size)
         {
             m_ptr -= size;
         }
         return acc;
     }
Member Data Documentation
m_ptr
template<class Type> int Lowpass< Type >::m_ptr private
Definition at line 104 of file lowpass.h.
Referenced by Lowpass< Real >::create(), and Lowpass< Real >::filter().
m_samples
template<class Type> std::vector<Type> Lowpass< Type >::m_samples private
Definition at line 103 of file lowpass.h.
Referenced by Lowpass< Real >::create(), and Lowpass< Real >::filter().
m_taps
template<class Type> std::vector<Real> Lowpass< Type >::m_taps private
Definition at line 102 of file lowpass.h.
Referenced by Lowpass< Real >::create(), and Lowpass< Real >::filter().
The documentation for this class was generated from the following file:
sdrbase/dsp/lowpass.h