SDRAngel: DeviceSoapySDRShared::MsgReportDeviceArgsChange Class Reference
DeviceSoapySDRShared::MsgReportDeviceArgsChange Class Reference
#include <devicesoapysdrshared.h>
Public Member Functions
const QMap< QString, QVariant > & getDeviceArgSettings () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportDeviceArgsChange * create (const QMap< QString, QVariant > &deviceArgSettings)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportDeviceArgsChange (const QMap< QString, QVariant > &deviceArgSettings)
Private Attributes
QMap< QString, QVariant > m_deviceArgSettings
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 86 of file devicesoapysdrshared.h.
Constructor & Destructor Documentation
MsgReportDeviceArgsChange()
DeviceSoapySDRShared::MsgReportDeviceArgsChange::MsgReportDeviceArgsChange (const QMap< QString, QVariant > & deviceArgSettings) inline private
Definition at line 99 of file devicesoapysdrshared.h.
                                                                                     :
             m_deviceArgSettings(deviceArgSettings)
         { }
Member Function Documentation
create()
static MsgReportDeviceArgsChange* DeviceSoapySDRShared::MsgReportDeviceArgsChange::create (const QMap< QString, QVariant > & deviceArgSettings) inline static
Definition at line 92 of file devicesoapysdrshared.h.
Referenced by SoapySDROutput::applySettings(), SoapySDRInput::applySettings(), SoapySDROutput::handleMessage(), and SoapySDRInput::handleMessage().
{
             return new MsgReportDeviceArgsChange(deviceArgSettings);
         }
getDeviceArgSettings()
const QMap<QString, QVariant>& DeviceSoapySDRShared::MsgReportDeviceArgsChange::getDeviceArgSettings () const inline
Definition at line 90 of file devicesoapysdrshared.h.
Referenced by SoapySDRInputGui::handleMessage(), SoapySDROutputGui::handleMessage(), SoapySDROutput::handleMessage(), and SoapySDRInput::handleMessage().
 { return m_deviceArgSettings; }
Member Data Documentation
m_deviceArgSettings
QMap<QString, QVariant> DeviceSoapySDRShared::MsgReportDeviceArgsChange::m_deviceArgSettings private
Definition at line 97 of file devicesoapysdrshared.h.
The documentation for this class was generated from the following file:
devices/soapysdr/devicesoapysdrshared.h