SDRAngel: BasicDeviceSettingsDialog Class Reference
BasicDeviceSettingsDialog Class Reference
#include <basicdevicesettingsdialog.h>
Inherits QDialog.
Public Member Functions
BasicDeviceSettingsDialog (QWidget *parent=0)
~BasicDeviceSettingsDialog ()
bool hasChanged () const
bool useReverseAPI () const
const QString & getReverseAPIAddress () const
uint16_t getReverseAPIPort () const
uint16_t getReverseAPIDeviceIndex () const
void setUseReverseAPI (bool useReverseAPI)
void setReverseAPIAddress (const QString &address)
void setReverseAPIPort (uint16_t port)
void setReverseAPIDeviceIndex (uint16_t deviceIndex)
Private Slots
void on_reverseAPI_toggled (bool checked)
void on_reverseAPIAddress_editingFinished ()
void on_reverseAPIPort_editingFinished ()
void on_reverseAPIDeviceIndex_editingFinished ()
void accept ()
Private Attributes
Ui::BasicDeviceSettingsDialog * ui
bool m_useReverseAPI
QString m_reverseAPIAddress
uint16_t m_reverseAPIPort
uint16_t m_reverseAPIDeviceIndex
bool m_hasChanged
Detailed Description
Definition at line 12 of file basicdevicesettingsdialog.h.
Constructor & Destructor Documentation
BasicDeviceSettingsDialog()
BasicDeviceSettingsDialog::BasicDeviceSettingsDialog (QWidget * parent = 0) explicit
Definition at line 4 of file basicdevicesettingsdialog.cpp.
References setReverseAPIAddress(), setReverseAPIDeviceIndex(), setReverseAPIPort(), setUseReverseAPI(), and ui.
                                                                     :
     QDialog(parent),
     ui(new Ui::BasicDeviceSettingsDialog),
     m_hasChanged(false)
 {
     ui->setupUi(this);
     setUseReverseAPI(false);
     setReverseAPIAddress("127.0.0.1");
     setReverseAPIPort(8888);
     setReverseAPIDeviceIndex(0);
 }
~BasicDeviceSettingsDialog()
BasicDeviceSettingsDialog::~BasicDeviceSettingsDialog ()
Definition at line 16 of file basicdevicesettingsdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
accept
void BasicDeviceSettingsDialog::accept () private slot
Definition at line 84 of file basicdevicesettingsdialog.cpp.
References m_hasChanged.
 {
     m_hasChanged = true;
     QDialog::accept();
 }
getReverseAPIAddress()
const QString& BasicDeviceSettingsDialog::getReverseAPIAddress () const inline
Definition at line 21 of file basicdevicesettingsdialog.h.
Referenced by KiwiSDRGui::openDeviceSettingsDialog(), Bladerf1OutputGui::openDeviceSettingsDialog(), BladeRF2OutputGui::openDeviceSettingsDialog(), LocalOutputGui::openDeviceSettingsDialog(), FCDProPlusGui::openDeviceSettingsDialog(), PerseusGui::openDeviceSettingsDialog(), Bladerf1InputGui::openDeviceSettingsDialog(), SDRPlayGui::openDeviceSettingsDialog(), AirspyGui::openDeviceSettingsDialog(), PlutoSDROutputGUI::openDeviceSettingsDialog(), BladeRF2InputGui::openDeviceSettingsDialog(), RTLSDRGui::openDeviceSettingsDialog(), XTRXOutputGUI::openDeviceSettingsDialog(), AirspyHFGui::openDeviceSettingsDialog(), FileInputGUI::openDeviceSettingsDialog(), LimeSDROutputGUI::openDeviceSettingsDialog(), TestSourceGui::openDeviceSettingsDialog(), HackRFOutputGui::openDeviceSettingsDialog(), TestMIGui::openDeviceSettingsDialog(), HackRFInputGui::openDeviceSettingsDialog(), LimeSDRInputGUI::openDeviceSettingsDialog(), XTRXInputGUI::openDeviceSettingsDialog(), FCDProGui::openDeviceSettingsDialog(), PlutoSDRInputGui::openDeviceSettingsDialog(), LocalInputGui::openDeviceSettingsDialog(), RemoteInputGui::openDeviceSettingsDialog(), SoapySDROutputGui::openDeviceSettingsDialog(), SoapySDRInputGui::openDeviceSettingsDialog(), and RemoteOutputSinkGui::openDeviceSettingsDialog().
 { return m_reverseAPIAddress; }
getReverseAPIDeviceIndex()
uint16_t BasicDeviceSettingsDialog::getReverseAPIDeviceIndex () const inline
Definition at line 23 of file basicdevicesettingsdialog.h.
Referenced by KiwiSDRGui::openDeviceSettingsDialog(), Bladerf1OutputGui::openDeviceSettingsDialog(), BladeRF2OutputGui::openDeviceSettingsDialog(), LocalOutputGui::openDeviceSettingsDialog(), FCDProPlusGui::openDeviceSettingsDialog(), PerseusGui::openDeviceSettingsDialog(), Bladerf1InputGui::openDeviceSettingsDialog(), SDRPlayGui::openDeviceSettingsDialog(), AirspyGui::openDeviceSettingsDialog(), PlutoSDROutputGUI::openDeviceSettingsDialog(), BladeRF2InputGui::openDeviceSettingsDialog(), RTLSDRGui::openDeviceSettingsDialog(), XTRXOutputGUI::openDeviceSettingsDialog(), AirspyHFGui::openDeviceSettingsDialog(), FileInputGUI::openDeviceSettingsDialog(), LimeSDROutputGUI::openDeviceSettingsDialog(), TestSourceGui::openDeviceSettingsDialog(), HackRFOutputGui::openDeviceSettingsDialog(), TestMIGui::openDeviceSettingsDialog(), HackRFInputGui::openDeviceSettingsDialog(), LimeSDRInputGUI::openDeviceSettingsDialog(), XTRXInputGUI::openDeviceSettingsDialog(), FCDProGui::openDeviceSettingsDialog(), PlutoSDRInputGui::openDeviceSettingsDialog(), LocalInputGui::openDeviceSettingsDialog(), RemoteInputGui::openDeviceSettingsDialog(), SoapySDROutputGui::openDeviceSettingsDialog(), SoapySDRInputGui::openDeviceSettingsDialog(), and RemoteOutputSinkGui::openDeviceSettingsDialog().
 { return m_reverseAPIDeviceIndex; }
getReverseAPIPort()
uint16_t BasicDeviceSettingsDialog::getReverseAPIPort () const inline
Definition at line 22 of file basicdevicesettingsdialog.h.
Referenced by KiwiSDRGui::openDeviceSettingsDialog(), Bladerf1OutputGui::openDeviceSettingsDialog(), BladeRF2OutputGui::openDeviceSettingsDialog(), LocalOutputGui::openDeviceSettingsDialog(), FCDProPlusGui::openDeviceSettingsDialog(), PerseusGui::openDeviceSettingsDialog(), Bladerf1InputGui::openDeviceSettingsDialog(), SDRPlayGui::openDeviceSettingsDialog(), AirspyGui::openDeviceSettingsDialog(), PlutoSDROutputGUI::openDeviceSettingsDialog(), BladeRF2InputGui::openDeviceSettingsDialog(), RTLSDRGui::openDeviceSettingsDialog(), XTRXOutputGUI::openDeviceSettingsDialog(), AirspyHFGui::openDeviceSettingsDialog(), FileInputGUI::openDeviceSettingsDialog(), LimeSDROutputGUI::openDeviceSettingsDialog(), TestSourceGui::openDeviceSettingsDialog(), HackRFOutputGui::openDeviceSettingsDialog(), TestMIGui::openDeviceSettingsDialog(), HackRFInputGui::openDeviceSettingsDialog(), LimeSDRInputGUI::openDeviceSettingsDialog(), XTRXInputGUI::openDeviceSettingsDialog(), FCDProGui::openDeviceSettingsDialog(), PlutoSDRInputGui::openDeviceSettingsDialog(), LocalInputGui::openDeviceSettingsDialog(), RemoteInputGui::openDeviceSettingsDialog(), SoapySDROutputGui::openDeviceSettingsDialog(), SoapySDRInputGui::openDeviceSettingsDialog(), and RemoteOutputSinkGui::openDeviceSettingsDialog().
 { return m_reverseAPIPort; }
hasChanged()
bool BasicDeviceSettingsDialog::hasChanged () const inline
Definition at line 19 of file basicdevicesettingsdialog.h.
 { return m_hasChanged; }
on_reverseAPI_toggled
void BasicDeviceSettingsDialog::on_reverseAPI_toggled (bool checked) private slot
Definition at line 50 of file basicdevicesettingsdialog.cpp.
References m_useReverseAPI.
 {
     m_useReverseAPI = checked;
 }
on_reverseAPIAddress_editingFinished
void BasicDeviceSettingsDialog::on_reverseAPIAddress_editingFinished () private slot
Definition at line 55 of file basicdevicesettingsdialog.cpp.
References m_reverseAPIAddress, and ui.
 {
     m_reverseAPIAddress = ui->reverseAPIAddress->text();
 }
on_reverseAPIDeviceIndex_editingFinished
void BasicDeviceSettingsDialog::on_reverseAPIDeviceIndex_editingFinished () private slot
Definition at line 72 of file basicdevicesettingsdialog.cpp.
References m_reverseAPIDeviceIndex, and ui.
 {
     bool dataOk;
     int reverseAPIDeviceIndex = ui->reverseAPIDeviceIndex->text().toInt(&dataOk);
     if ((!dataOk) || (reverseAPIDeviceIndex < 0)) {
         return;
     } else {
         m_reverseAPIDeviceIndex = reverseAPIDeviceIndex;
     }
 }
on_reverseAPIPort_editingFinished
void BasicDeviceSettingsDialog::on_reverseAPIPort_editingFinished () private slot
Definition at line 60 of file basicdevicesettingsdialog.cpp.
References m_reverseAPIPort, and ui.
 {
     bool dataOk;
     int reverseAPIPort = ui->reverseAPIPort->text().toInt(&dataOk);
     if((!dataOk) || (reverseAPIPort < 1024) || (reverseAPIPort > 65535)) {
         return;
     } else {
         m_reverseAPIPort = reverseAPIPort;
     }
 }
setReverseAPIAddress()
void BasicDeviceSettingsDialog::setReverseAPIAddress (const QString & address)
Definition at line 27 of file basicdevicesettingsdialog.cpp.
References m_reverseAPIAddress, and ui.
Referenced by BasicDeviceSettingsDialog(), KiwiSDRGui::openDeviceSettingsDialog(), Bladerf1OutputGui::openDeviceSettingsDialog(), BladeRF2OutputGui::openDeviceSettingsDialog(), LocalOutputGui::openDeviceSettingsDialog(), FCDProPlusGui::openDeviceSettingsDialog(), PerseusGui::openDeviceSettingsDialog(), Bladerf1InputGui::openDeviceSettingsDialog(), SDRPlayGui::openDeviceSettingsDialog(), AirspyGui::openDeviceSettingsDialog(), BladeRF2InputGui::openDeviceSettingsDialog(), PlutoSDROutputGUI::openDeviceSettingsDialog(), RTLSDRGui::openDeviceSettingsDialog(), XTRXOutputGUI::openDeviceSettingsDialog(), AirspyHFGui::openDeviceSettingsDialog(), FileInputGUI::openDeviceSettingsDialog(), LimeSDROutputGUI::openDeviceSettingsDialog(), TestSourceGui::openDeviceSettingsDialog(), HackRFOutputGui::openDeviceSettingsDialog(), TestMIGui::openDeviceSettingsDialog(), HackRFInputGui::openDeviceSettingsDialog(), LimeSDRInputGUI::openDeviceSettingsDialog(), XTRXInputGUI::openDeviceSettingsDialog(), FCDProGui::openDeviceSettingsDialog(), PlutoSDRInputGui::openDeviceSettingsDialog(), LocalInputGui::openDeviceSettingsDialog(), RemoteInputGui::openDeviceSettingsDialog(), SoapySDROutputGui::openDeviceSettingsDialog(), SoapySDRInputGui::openDeviceSettingsDialog(), and RemoteOutputSinkGui::openDeviceSettingsDialog().
 {
     m_reverseAPIAddress = address;
     ui->reverseAPIAddress->setText(m_reverseAPIAddress);
 }
setReverseAPIDeviceIndex()
void BasicDeviceSettingsDialog::setReverseAPIDeviceIndex (uint16_t deviceIndex)
Definition at line 44 of file basicdevicesettingsdialog.cpp.
References arg(), m_reverseAPIDeviceIndex, and ui.
Referenced by BasicDeviceSettingsDialog(), KiwiSDRGui::openDeviceSettingsDialog(), Bladerf1OutputGui::openDeviceSettingsDialog(), BladeRF2OutputGui::openDeviceSettingsDialog(), LocalOutputGui::openDeviceSettingsDialog(), FCDProPlusGui::openDeviceSettingsDialog(), PerseusGui::openDeviceSettingsDialog(), Bladerf1InputGui::openDeviceSettingsDialog(), SDRPlayGui::openDeviceSettingsDialog(), AirspyGui::openDeviceSettingsDialog(), BladeRF2InputGui::openDeviceSettingsDialog(), PlutoSDROutputGUI::openDeviceSettingsDialog(), RTLSDRGui::openDeviceSettingsDialog(), XTRXOutputGUI::openDeviceSettingsDialog(), AirspyHFGui::openDeviceSettingsDialog(), FileInputGUI::openDeviceSettingsDialog(), LimeSDROutputGUI::openDeviceSettingsDialog(), TestSourceGui::openDeviceSettingsDialog(), HackRFOutputGui::openDeviceSettingsDialog(), TestMIGui::openDeviceSettingsDialog(), HackRFInputGui::openDeviceSettingsDialog(), LimeSDRInputGUI::openDeviceSettingsDialog(), XTRXInputGUI::openDeviceSettingsDialog(), FCDProGui::openDeviceSettingsDialog(), PlutoSDRInputGui::openDeviceSettingsDialog(), LocalInputGui::openDeviceSettingsDialog(), RemoteInputGui::openDeviceSettingsDialog(), SoapySDROutputGui::openDeviceSettingsDialog(), SoapySDRInputGui::openDeviceSettingsDialog(), and RemoteOutputSinkGui::openDeviceSettingsDialog().
 {
     m_reverseAPIDeviceIndex = deviceIndex > 99 ? 99 : deviceIndex;
     ui->reverseAPIDeviceIndex->setText(tr("%1").arg(m_reverseAPIDeviceIndex));
 }
setReverseAPIPort()
void BasicDeviceSettingsDialog::setReverseAPIPort (uint16_t port)
Definition at line 33 of file basicdevicesettingsdialog.cpp.
References arg(), m_reverseAPIPort, and ui.
Referenced by BasicDeviceSettingsDialog(), KiwiSDRGui::openDeviceSettingsDialog(), Bladerf1OutputGui::openDeviceSettingsDialog(), BladeRF2OutputGui::openDeviceSettingsDialog(), LocalOutputGui::openDeviceSettingsDialog(), FCDProPlusGui::openDeviceSettingsDialog(), PerseusGui::openDeviceSettingsDialog(), Bladerf1InputGui::openDeviceSettingsDialog(), SDRPlayGui::openDeviceSettingsDialog(), AirspyGui::openDeviceSettingsDialog(), BladeRF2InputGui::openDeviceSettingsDialog(), PlutoSDROutputGUI::openDeviceSettingsDialog(), RTLSDRGui::openDeviceSettingsDialog(), XTRXOutputGUI::openDeviceSettingsDialog(), AirspyHFGui::openDeviceSettingsDialog(), FileInputGUI::openDeviceSettingsDialog(), LimeSDROutputGUI::openDeviceSettingsDialog(), TestSourceGui::openDeviceSettingsDialog(), HackRFOutputGui::openDeviceSettingsDialog(), TestMIGui::openDeviceSettingsDialog(), HackRFInputGui::openDeviceSettingsDialog(), LimeSDRInputGUI::openDeviceSettingsDialog(), XTRXInputGUI::openDeviceSettingsDialog(), FCDProGui::openDeviceSettingsDialog(), PlutoSDRInputGui::openDeviceSettingsDialog(), LocalInputGui::openDeviceSettingsDialog(), RemoteInputGui::openDeviceSettingsDialog(), SoapySDROutputGui::openDeviceSettingsDialog(), SoapySDRInputGui::openDeviceSettingsDialog(), and RemoteOutputSinkGui::openDeviceSettingsDialog().
 {
     if (port < 1024) {
         return;
     } else {
         m_reverseAPIPort = port;
     }
     ui->reverseAPIPort->setText(tr("%1").arg(m_reverseAPIPort));
 }
setUseReverseAPI()
void BasicDeviceSettingsDialog::setUseReverseAPI (bool useReverseAPI)
Definition at line 21 of file basicdevicesettingsdialog.cpp.
References m_useReverseAPI, ui, and useReverseAPI().
Referenced by BasicDeviceSettingsDialog(), KiwiSDRGui::openDeviceSettingsDialog(), Bladerf1OutputGui::openDeviceSettingsDialog(), BladeRF2OutputGui::openDeviceSettingsDialog(), LocalOutputGui::openDeviceSettingsDialog(), FCDProPlusGui::openDeviceSettingsDialog(), PerseusGui::openDeviceSettingsDialog(), Bladerf1InputGui::openDeviceSettingsDialog(), SDRPlayGui::openDeviceSettingsDialog(), AirspyGui::openDeviceSettingsDialog(), BladeRF2InputGui::openDeviceSettingsDialog(), PlutoSDROutputGUI::openDeviceSettingsDialog(), RTLSDRGui::openDeviceSettingsDialog(), XTRXOutputGUI::openDeviceSettingsDialog(), AirspyHFGui::openDeviceSettingsDialog(), FileInputGUI::openDeviceSettingsDialog(), LimeSDROutputGUI::openDeviceSettingsDialog(), TestSourceGui::openDeviceSettingsDialog(), HackRFOutputGui::openDeviceSettingsDialog(), TestMIGui::openDeviceSettingsDialog(), HackRFInputGui::openDeviceSettingsDialog(), LimeSDRInputGUI::openDeviceSettingsDialog(), XTRXInputGUI::openDeviceSettingsDialog(), FCDProGui::openDeviceSettingsDialog(), PlutoSDRInputGui::openDeviceSettingsDialog(), LocalInputGui::openDeviceSettingsDialog(), RemoteInputGui::openDeviceSettingsDialog(), SoapySDROutputGui::openDeviceSettingsDialog(), SoapySDRInputGui::openDeviceSettingsDialog(), and RemoteOutputSinkGui::openDeviceSettingsDialog().
 {
     m_useReverseAPI = useReverseAPI;
     ui->reverseAPI->setChecked(m_useReverseAPI);
 }
useReverseAPI()
bool BasicDeviceSettingsDialog::useReverseAPI () const inline
Definition at line 20 of file basicdevicesettingsdialog.h.
Referenced by KiwiSDRGui::openDeviceSettingsDialog(), Bladerf1OutputGui::openDeviceSettingsDialog(), BladeRF2OutputGui::openDeviceSettingsDialog(), LocalOutputGui::openDeviceSettingsDialog(), FCDProPlusGui::openDeviceSettingsDialog(), PerseusGui::openDeviceSettingsDialog(), Bladerf1InputGui::openDeviceSettingsDialog(), SDRPlayGui::openDeviceSettingsDialog(), AirspyGui::openDeviceSettingsDialog(), PlutoSDROutputGUI::openDeviceSettingsDialog(), BladeRF2InputGui::openDeviceSettingsDialog(), XTRXOutputGUI::openDeviceSettingsDialog(), RTLSDRGui::openDeviceSettingsDialog(), AirspyHFGui::openDeviceSettingsDialog(), FileInputGUI::openDeviceSettingsDialog(), LimeSDROutputGUI::openDeviceSettingsDialog(), TestSourceGui::openDeviceSettingsDialog(), HackRFOutputGui::openDeviceSettingsDialog(), LimeSDRInputGUI::openDeviceSettingsDialog(), TestMIGui::openDeviceSettingsDialog(), HackRFInputGui::openDeviceSettingsDialog(), PlutoSDRInputGui::openDeviceSettingsDialog(), XTRXInputGUI::openDeviceSettingsDialog(), FCDProGui::openDeviceSettingsDialog(), LocalInputGui::openDeviceSettingsDialog(), RemoteInputGui::openDeviceSettingsDialog(), SoapySDROutputGui::openDeviceSettingsDialog(), SoapySDRInputGui::openDeviceSettingsDialog(), RemoteOutputSinkGui::openDeviceSettingsDialog(), and setUseReverseAPI().
 { return m_useReverseAPI; }
Member Data Documentation
m_hasChanged
bool BasicDeviceSettingsDialog::m_hasChanged private
Definition at line 42 of file basicdevicesettingsdialog.h.
Referenced by accept().
m_reverseAPIAddress
QString BasicDeviceSettingsDialog::m_reverseAPIAddress private
Definition at line 39 of file basicdevicesettingsdialog.h.
Referenced by on_reverseAPIAddress_editingFinished(), and setReverseAPIAddress().
m_reverseAPIDeviceIndex
uint16_t BasicDeviceSettingsDialog::m_reverseAPIDeviceIndex private
Definition at line 41 of file basicdevicesettingsdialog.h.
Referenced by on_reverseAPIDeviceIndex_editingFinished(), and setReverseAPIDeviceIndex().
m_reverseAPIPort
uint16_t BasicDeviceSettingsDialog::m_reverseAPIPort private
Definition at line 40 of file basicdevicesettingsdialog.h.
Referenced by on_reverseAPIPort_editingFinished(), and setReverseAPIPort().
m_useReverseAPI
bool BasicDeviceSettingsDialog::m_useReverseAPI private
Definition at line 38 of file basicdevicesettingsdialog.h.
Referenced by on_reverseAPI_toggled(), and setUseReverseAPI().
ui
Ui::BasicDeviceSettingsDialog* BasicDeviceSettingsDialog::ui private
Definition at line 37 of file basicdevicesettingsdialog.h.
Referenced by BasicDeviceSettingsDialog(), on_reverseAPIAddress_editingFinished(), on_reverseAPIDeviceIndex_editingFinished(), on_reverseAPIPort_editingFinished(), setReverseAPIAddress(), setReverseAPIDeviceIndex(), setReverseAPIPort(), setUseReverseAPI(), and ~BasicDeviceSettingsDialog().
The documentation for this class was generated from the following files:
sdrgui/gui/basicdevicesettingsdialog.h
sdrgui/gui/basicdevicesettingsdialog.cpp