SDRAngel: SoapySDROutputThread Class Reference
SoapySDROutputThread Class Reference
#include <soapysdroutputthread.h>
Inherits QThread.
Classes
struct Channel
Public Member Functions
SoapySDROutputThread (SoapySDR::Device *dev, unsigned int nbTxChannels, QObject *parent=0)
~SoapySDROutputThread ()
void startWork ()
void stopWork ()
bool isRunning () const
unsigned int getNbChannels () const
void setLog2Interpolation (unsigned int channel, unsigned int log2_interp)
unsigned int getLog2Interpolation (unsigned int channel) const
void setSampleRate (unsigned int sampleRate)
unsigned int getSampleRate () const
void setFifo (unsigned int channel, SampleSourceFifo *sampleFifo)
SampleSourceFifo * getFifo (unsigned int channel)
Private Types
enum InterpolatorType { Interpolator8, Interpolator12, Interpolator16, InterpolatorFloat }
Private Member Functions
void run ()
unsigned int getNbFifos ()
void callbackSO8 (qint8 *buf, qint32 len, unsigned int channel=0)
void callbackSO12 (qint16 *buf, qint32 len, unsigned int channel=0)
void callbackSO16 (qint16 *buf, qint32 len, unsigned int channel=0)
void callbackSOIF (float *buf, qint32 len, unsigned int channel=0)
void callbackMO (std::vector< void *> &buffs, qint32 samplesPerChannel)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
SoapySDR::Device * m_dev
Channel * m_channels
Array of channels dynamically allocated for the given number of Tx channels.
unsigned int m_sampleRate
unsigned int m_nbChannels
InterpolatorType m_interpolatorType
Detailed Description
Definition at line 34 of file soapysdroutputthread.h.
Member Enumeration Documentation
InterpolatorType
enum SoapySDROutputThread::InterpolatorType private
Enumerator
Interpolator8
Interpolator12
Interpolator16
InterpolatorFloat
Definition at line 71 of file soapysdroutputthread.h.
     {
         Interpolator8,
         Interpolator12,
         Interpolator16,
         InterpolatorFloat
     };
Constructor & Destructor Documentation
SoapySDROutputThread()
SoapySDROutputThread::SoapySDROutputThread (SoapySDR::Device * dev, unsigned int nbTxChannels, QObject * parent = 0)
Definition at line 27 of file soapysdroutputthread.cpp.
References m_channels.
                                                                                                           :
     QThread(parent),
     m_running(false),
     m_dev(dev),
     m_sampleRate(0),
     m_nbChannels(nbTxChannels),
     m_interpolatorType(InterpolatorFloat)
 {
     qDebug("SoapySDROutputThread::SoapySDROutputThread");
     m_channels = new Channel[nbTxChannels];
 }
~SoapySDROutputThread()
SoapySDROutputThread::~SoapySDROutputThread ()
Definition at line 39 of file soapysdroutputthread.cpp.
References m_channels, m_running, and stopWork().
 {
     qDebug("SoapySDROutputThread::~SoapySDROutputThread");
     if (m_running) {
         stopWork();
     }
     delete[] m_channels;
 }
Member Function Documentation
callbackMO()
void SoapySDROutputThread::callbackMO (std::vector< void *> & buffs, qint32 samplesPerChannel) private
Definition at line 237 of file soapysdroutputthread.cpp.
References callbackSO12(), callbackSO16(), callbackSO8(), Interpolator12, Interpolator16, Interpolator8, InterpolatorFloat, m_channels, m_interpolatorType, and m_nbChannels.
Referenced by run().
 {
     for(unsigned int ichan = 0; ichan < m_nbChannels; ichan++)
     {
         if (m_channels[ichan].m_sampleFifo)
         {
             switch (m_interpolatorType)
             {
             case Interpolator8:
                 callbackSO8((qint8*) buffs[ichan], samplesPerChannel, ichan);
                 break;
             case Interpolator12:
                 callbackSO12((qint16*) buffs[ichan], samplesPerChannel, ichan);
                 break;
             case Interpolator16:
                 callbackSO16((qint16*) buffs[ichan], samplesPerChannel, ichan);
                 break;
             case InterpolatorFloat:
             default:
                 // TODO
                 break;
             }
         }
         else // no FIFO for this channel means channel is unused: fill with zeros
         {
             switch (m_interpolatorType)
             {
             case Interpolator8:
                 std::fill((qint8*) buffs[ichan], (qint8*) buffs[ichan] + 2*samplesPerChannel, 0);
                 break;
             case Interpolator12:
             case Interpolator16:
                 std::fill((qint16*) buffs[ichan], (qint16*) buffs[ichan] + 2*samplesPerChannel, 0);
                 break;
             case InterpolatorFloat:
             default:
                 std::fill((float*) buffs[ichan], (float*) buffs[ichan] + 2*samplesPerChannel, 0.0f);
                 break;
             }
         }
     }
 }
callbackSO12()
void SoapySDROutputThread::callbackSO12 (qint16 * buf, qint32 len, unsigned int channel = 0) private
Definition at line 335 of file soapysdroutputthread.cpp.
References SampleSourceFifo::getRWBalance(), Interpolators< T, SdrBits, OutputBits >::interpolate1(), Interpolators< T, SdrBits, OutputBits >::interpolate16_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate2_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate32_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate4_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate64_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate8_cen(), m_channels, SoapySDROutputThread::Channel::m_interpolators12, SoapySDROutputThread::Channel::m_sampleFifo, and SampleSourceFifo::readAdvance().
Referenced by callbackMO(), and run().
 {
     if (m_channels[channel].m_sampleFifo)
     {
         float bal = m_channels[channel].m_sampleFifo->getRWBalance();
         if (bal < -0.25) {
             qDebug("SoapySDROutputThread::callbackSO12: read lags: %f", bal);
         } else if (bal > 0.25) {
             qDebug("SoapySDROutputThread::callbackSO12: read leads: %f", bal);
         }
         SampleVector::iterator beginRead;
         m_channels[channel].m_sampleFifo->readAdvance(beginRead, len/(1<<m_channels[channel].m_log2Interp));
         beginRead -= len;
         if (m_channels[channel].m_log2Interp == 0)
         {
             m_channels[channel].m_interpolators12.interpolate1(&beginRead, buf, len*2);
         }
         else
         {
             switch (m_channels[channel].m_log2Interp)
             {
             case 1:
                 m_channels[channel].m_interpolators12.interpolate2_cen(&beginRead, buf, len*2);
                 break;
             case 2:
                 m_channels[channel].m_interpolators12.interpolate4_cen(&beginRead, buf, len*2);
                 break;
             case 3:
                 m_channels[channel].m_interpolators12.interpolate8_cen(&beginRead, buf, len*2);
                 break;
             case 4:
                 m_channels[channel].m_interpolators12.interpolate16_cen(&beginRead, buf, len*2);
                 break;
             case 5:
                 m_channels[channel].m_interpolators12.interpolate32_cen(&beginRead, buf, len*2);
                 break;
             case 6:
                 m_channels[channel].m_interpolators12.interpolate64_cen(&beginRead, buf, len*2);
                 break;
             default:
                 break;
             }
         }
     }
     else
     {
         std::fill(buf, buf+2*len, 0);
     }
 }
callbackSO16()
void SoapySDROutputThread::callbackSO16 (qint16 * buf, qint32 len, unsigned int channel = 0) private
Definition at line 388 of file soapysdroutputthread.cpp.
References SampleSourceFifo::getRWBalance(), Interpolators< T, SdrBits, OutputBits >::interpolate1(), Interpolators< T, SdrBits, OutputBits >::interpolate16_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate2_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate32_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate4_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate64_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate8_cen(), m_channels, SoapySDROutputThread::Channel::m_interpolators16, SoapySDROutputThread::Channel::m_sampleFifo, and SampleSourceFifo::readAdvance().
Referenced by callbackMO(), and run().
 {
     if (m_channels[channel].m_sampleFifo)
     {
         float bal = m_channels[channel].m_sampleFifo->getRWBalance();
         if (bal < -0.25) {
             qDebug("SoapySDROutputThread::callbackSO16: read lags: %f", bal);
         } else if (bal > 0.25) {
             qDebug("SoapySDROutputThread::callbackSO16: read leads: %f", bal);
         }
         SampleVector::iterator beginRead;
         m_channels[channel].m_sampleFifo->readAdvance(beginRead, len/(1<<m_channels[channel].m_log2Interp));
         beginRead -= len;
         if (m_channels[channel].m_log2Interp == 0)
         {
             m_channels[channel].m_interpolators16.interpolate1(&beginRead, buf, len*2);
         }
         else
         {
             switch (m_channels[channel].m_log2Interp)
             {
             case 1:
                 m_channels[channel].m_interpolators16.interpolate2_cen(&beginRead, buf, len*2);
                 break;
             case 2:
                 m_channels[channel].m_interpolators16.interpolate4_cen(&beginRead, buf, len*2);
                 break;
             case 3:
                 m_channels[channel].m_interpolators16.interpolate8_cen(&beginRead, buf, len*2);
                 break;
             case 4:
                 m_channels[channel].m_interpolators16.interpolate16_cen(&beginRead, buf, len*2);
                 break;
             case 5:
                 m_channels[channel].m_interpolators16.interpolate32_cen(&beginRead, buf, len*2);
                 break;
             case 6:
                 m_channels[channel].m_interpolators16.interpolate64_cen(&beginRead, buf, len*2);
                 break;
             default:
                 break;
             }
         }
     }
     else
     {
         std::fill(buf, buf+2*len, 0);
     }
 }
callbackSO8()
void SoapySDROutputThread::callbackSO8 (qint8 * buf, qint32 len, unsigned int channel = 0) private
Definition at line 282 of file soapysdroutputthread.cpp.
References SampleSourceFifo::getRWBalance(), Interpolators< T, SdrBits, OutputBits >::interpolate1(), Interpolators< T, SdrBits, OutputBits >::interpolate16_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate2_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate32_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate4_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate64_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate8_cen(), m_channels, SoapySDROutputThread::Channel::m_interpolators8, SoapySDROutputThread::Channel::m_sampleFifo, and SampleSourceFifo::readAdvance().
Referenced by callbackMO(), and run().
 {
     if (m_channels[channel].m_sampleFifo)
     {
         float bal = m_channels[channel].m_sampleFifo->getRWBalance();
         if (bal < -0.25) {
             qDebug("SoapySDROutputThread::callbackSO8: read lags: %f", bal);
         } else if (bal > 0.25) {
             qDebug("SoapySDROutputThread::callbackSO8: read leads: %f", bal);
         }
         SampleVector::iterator beginRead;
         m_channels[channel].m_sampleFifo->readAdvance(beginRead, len/(1<<m_channels[channel].m_log2Interp));
         beginRead -= len;
         if (m_channels[channel].m_log2Interp == 0)
         {
             m_channels[channel].m_interpolators8.interpolate1(&beginRead, buf, len*2);
         }
         else
         {
             switch (m_channels[channel].m_log2Interp)
             {
             case 1:
                 m_channels[channel].m_interpolators8.interpolate2_cen(&beginRead, buf, len*2);
                 break;
             case 2:
                 m_channels[channel].m_interpolators8.interpolate4_cen(&beginRead, buf, len*2);
                 break;
             case 3:
                 m_channels[channel].m_interpolators8.interpolate8_cen(&beginRead, buf, len*2);
                 break;
             case 4:
                 m_channels[channel].m_interpolators8.interpolate16_cen(&beginRead, buf, len*2);
                 break;
             case 5:
                 m_channels[channel].m_interpolators8.interpolate32_cen(&beginRead, buf, len*2);
                 break;
             case 6:
                 m_channels[channel].m_interpolators8.interpolate64_cen(&beginRead, buf, len*2);
                 break;
             default:
                 break;
             }
         }
     }
     else
     {
         std::fill(buf, buf+2*len, 0);
     }
 }
callbackSOIF()
void SoapySDROutputThread::callbackSOIF (float * buf, qint32 len, unsigned int channel = 0) private
Definition at line 442 of file soapysdroutputthread.cpp.
References SampleSourceFifo::getRWBalance(), InterpolatorsIF< OutBits, InBits >::interpolate1(), InterpolatorsIF< OutBits, InBits >::interpolate16_cen(), InterpolatorsIF< OutBits, InBits >::interpolate2_cen(), InterpolatorsIF< OutBits, InBits >::interpolate32_cen(), InterpolatorsIF< OutBits, InBits >::interpolate4_cen(), InterpolatorsIF< OutBits, InBits >::interpolate64_cen(), InterpolatorsIF< OutBits, InBits >::interpolate8_cen(), m_channels, SoapySDROutputThread::Channel::m_interpolatorsIF, SoapySDROutputThread::Channel::m_sampleFifo, and SampleSourceFifo::readAdvance().
Referenced by run().
 {
     if (m_channels[channel].m_sampleFifo)
     {
         float bal = m_channels[channel].m_sampleFifo->getRWBalance();
         if (bal < -0.25) {
             qDebug("SoapySDROutputThread::callbackSO16: read lags: %f", bal);
         } else if (bal > 0.25) {
             qDebug("SoapySDROutputThread::callbackSO16: read leads: %f", bal);
         }
         SampleVector::iterator beginRead;
         m_channels[channel].m_sampleFifo->readAdvance(beginRead, len/(1<<m_channels[channel].m_log2Interp));
         beginRead -= len;
         if (m_channels[channel].m_log2Interp == 0)
         {
             m_channels[channel].m_interpolatorsIF.interpolate1(&beginRead, buf, len*2);
         }
         else
         {
             switch (m_channels[channel].m_log2Interp)
             {
             case 1:
                 m_channels[channel].m_interpolatorsIF.interpolate2_cen(&beginRead, buf, len*2);
                 break;
             case 2:
                 m_channels[channel].m_interpolatorsIF.interpolate4_cen(&beginRead, buf, len*2);
                 break;
             case 3:
                 m_channels[channel].m_interpolatorsIF.interpolate8_cen(&beginRead, buf, len*2);
                 break;
             case 4:
                 m_channels[channel].m_interpolatorsIF.interpolate16_cen(&beginRead, buf, len*2);
                 break;
             case 5:
                 m_channels[channel].m_interpolatorsIF.interpolate32_cen(&beginRead, buf, len*2);
                 break;
             case 6:
                 m_channels[channel].m_interpolatorsIF.interpolate64_cen(&beginRead, buf, len*2);
                 break;
             default:
                 break;
             }
         }
     }
     else
     {
         std::fill(buf, buf+2*len, 0.0f);
     }
 }
getFifo()
SampleSourceFifo * SoapySDROutputThread::getFifo (unsigned int channel)
Definition at line 228 of file soapysdroutputthread.cpp.
References m_channels, m_nbChannels, and SoapySDROutputThread::Channel::m_sampleFifo.
Referenced by SoapySDROutput::applySettings(), getSampleRate(), SoapySDROutput::start(), and SoapySDROutput::stop().
 {
     if (channel < m_nbChannels) {
         return m_channels[channel].m_sampleFifo;
     } else {
         return 0;
     }
 }
getLog2Interpolation()
unsigned int SoapySDROutputThread::getLog2Interpolation (unsigned int channel) const
Definition at line 212 of file soapysdroutputthread.cpp.
References m_channels, SoapySDROutputThread::Channel::m_log2Interp, and m_nbChannels.
Referenced by getNbChannels(), SoapySDROutput::start(), and SoapySDROutput::stop().
 {
     if (channel < m_nbChannels) {
         return m_channels[channel].m_log2Interp;
     } else {
         return 0;
     }
 }
getNbChannels()
unsigned int SoapySDROutputThread::getNbChannels () const inline
Definition at line 44 of file soapysdroutputthread.h.
References getLog2Interpolation(), m_nbChannels, and setLog2Interpolation().
Referenced by SoapySDROutput::start(), and SoapySDROutput::stop().
 { return m_nbChannels; }
getNbFifos()
unsigned int SoapySDROutputThread::getNbFifos () private
Definition at line 191 of file soapysdroutputthread.cpp.
References i, m_channels, and m_nbChannels.
Referenced by run().
 {
     unsigned int fifoCount = 0;
     for (unsigned int i = 0; i < m_nbChannels; i++)
     {
         if (m_channels[i].m_sampleFifo) {
             fifoCount++;
         }
     }
     return fifoCount;
 }
getSampleRate()
unsigned int SoapySDROutputThread::getSampleRate () const inline
Definition at line 48 of file soapysdroutputthread.h.
References getFifo(), m_sampleRate, and setFifo().
 { return m_sampleRate; }
isRunning()
bool SoapySDROutputThread::isRunning () const inline
Definition at line 43 of file soapysdroutputthread.h.
References m_running.
Referenced by SoapySDROutput::applySettings().
 { return m_running; }
run()
void SoapySDROutputThread::run () private
Definition at line 76 of file soapysdroutputthread.cpp.
References callbackMO(), callbackSO12(), callbackSO16(), callbackSO8(), callbackSOIF(), getNbFifos(), i, Interpolator12, Interpolator16, Interpolator8, InterpolatorFloat, m_dev, m_interpolatorType, m_nbChannels, m_running, m_sampleRate, and m_startWaiter.
 {
     m_running = true;
     m_startWaiter.wakeAll();
     unsigned int nbFifos = getNbFifos();
     if ((m_nbChannels > 0) && (nbFifos > 0))
     {
         // build channels list
         std::vector<std::size_t> channels(m_nbChannels);
         std::iota(channels.begin(), channels.end(), 0); // Fill with 0, 1, ..., m_nbChannels-1.
         //initialize the sample rate for all channels
         qDebug("SoapySDROutputThread::run: m_sampleRate: %u", m_sampleRate);
         for (const auto &it : channels) {
             m_dev->setSampleRate(SOAPY_SDR_TX, it, m_sampleRate);
         }
         // Determine sample format to be used
         double fullScale(0.0);
         std::string format = m_dev->getNativeStreamFormat(SOAPY_SDR_TX, channels.front(), fullScale);
         qDebug("SoapySDROutputThread::run: format: %s fullScale: %f", format.c_str(), fullScale);
         if ((format == "CS8") && (fullScale == 128.0)) { // 8 bit signed - native
             m_interpolatorType = Interpolator8;
         } else if ((format == "CS16") && (fullScale == 2048.0)) { // 12 bit signed - native
             m_interpolatorType = Interpolator12;
         } else if ((format == "CS16") && (fullScale == 32768.0)) { // 16 bit signed - native
             m_interpolatorType = Interpolator16;
         } else { // for other types make a conversion to float
             m_interpolatorType = InterpolatorFloat;
             format = "CF32";
         }
         unsigned int elemSize = SoapySDR::formatToSize(format); // sample (I+Q) size in bytes
         SoapySDR::Stream *stream = m_dev->setupStream(SOAPY_SDR_TX, format, channels);
         //allocate buffers for the stream read/write
         const unsigned int numElems = m_dev->getStreamMTU(stream); // number of samples (I+Q)
         std::vector<std::vector<char>> buffMem(m_nbChannels, std::vector<char>(elemSize*numElems));
         std::vector<void *> buffs(m_nbChannels);
         for (std::size_t i = 0; i < m_nbChannels; i++) {
             buffs[i] = buffMem[i].data();
         }
         m_dev->activateStream(stream);
         int flags(0);
         long long timeNs(0);
         float blockTime = ((float) numElems) / (m_sampleRate <= 0 ? 1024000 : m_sampleRate);
         long initialTtimeoutUs = 10000000 * blockTime; // 10 times the block time
         long timeoutUs = initialTtimeoutUs < 250000 ? 250000 : initialTtimeoutUs; // 250ms minimum
         qDebug("SoapySDROutputThread::run: numElems: %u elemSize: %u initialTtimeoutUs: %ld  timeoutUs: %ld",
                 numElems, elemSize, initialTtimeoutUs, timeoutUs);
         qDebug("SoapySDROutputThread::run: start running loop");
         while (m_running)
         {
             int ret = m_dev->writeStream(stream, buffs.data(), numElems, flags, timeNs, timeoutUs);
             if (ret == SOAPY_SDR_TIMEOUT)
             {
                 qWarning("SoapySDROutputThread::run: timeout: flags: %d timeNs: %lld timeoutUs: %ld", flags, timeNs, timeoutUs);
             }
             else if (ret == SOAPY_SDR_OVERFLOW)
             {
                 qWarning("SoapySDROutputThread::run: overflow: flags: %d timeNs: %lld timeoutUs: %ld", flags, timeNs, timeoutUs);
             }
             else if (ret < 0)
             {
                 qCritical("SoapySDROutputThread::run: Unexpected write stream error: %s", SoapySDR::errToStr(ret));
                 break;
             }
             if (m_nbChannels > 1)
             {
                 callbackMO(buffs, numElems); // size given in number of samples (1 item per sample)
             }
             else
             {
                 switch (m_interpolatorType)
                 {
                 case Interpolator8:
                     callbackSO8((qint8*) buffs[0], numElems);
                     break;
                 case Interpolator12:
                     callbackSO12((qint16*) buffs[0], numElems);
                     break;
                 case Interpolator16:
                     callbackSO16((qint16*) buffs[0], numElems);
                     break;
                 case InterpolatorFloat:
                 default:
                     callbackSOIF((float*) buffs[0], numElems);
                     break;
                 }
             }
         }
         qDebug("SoapySDROutputThread::run: stop running loop");
         m_dev->deactivateStream(stream);
         m_dev->closeStream(stream);
     }
     else
     {
         qWarning("SoapySDROutputThread::run: no channels or FIFO allocated. Aborting");
     }
     m_running = false;
 }
setFifo()
void SoapySDROutputThread::setFifo (unsigned int channel, SampleSourceFifo * sampleFifo)
Definition at line 221 of file soapysdroutputthread.cpp.
References m_channels, m_nbChannels, and SoapySDROutputThread::Channel::m_sampleFifo.
Referenced by SoapySDROutput::applySettings(), getSampleRate(), SoapySDROutput::start(), and SoapySDROutput::stop().
 {
     if (channel < m_nbChannels) {
         m_channels[channel].m_sampleFifo = sampleFifo;
     }
 }
setLog2Interpolation()
void SoapySDROutputThread::setLog2Interpolation (unsigned int channel, unsigned int log2_interp)
Definition at line 205 of file soapysdroutputthread.cpp.
References m_channels, SoapySDROutputThread::Channel::m_log2Interp, and m_nbChannels.
Referenced by SoapySDROutput::applySettings(), getNbChannels(), SoapySDROutput::start(), and SoapySDROutput::stop().
 {
     if (channel < m_nbChannels) {
         m_channels[channel].m_log2Interp = log2_interp;
     }
 }
setSampleRate()
void SoapySDROutputThread::setSampleRate (unsigned int sampleRate) inline
Definition at line 47 of file soapysdroutputthread.h.
References m_sampleRate.
Referenced by SoapySDROutput::applySettings(), and SoapySDROutput::start().
 { m_sampleRate = sampleRate; }
startWork()
void SoapySDROutputThread::startWork ()
Definition at line 50 of file soapysdroutputthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by SoapySDROutput::applySettings(), SoapySDROutput::start(), and SoapySDROutput::stop().
 {
     if (m_running) {
         return;
     }
     m_startWaitMutex.lock();
     start();
     while(!m_running) {
         m_startWaiter.wait(&m_startWaitMutex, 100);
     }
     m_startWaitMutex.unlock();
 }
stopWork()
void SoapySDROutputThread::stopWork ()
Definition at line 66 of file soapysdroutputthread.cpp.
References m_running.
Referenced by SoapySDROutput::applySettings(), SoapySDROutput::start(), SoapySDROutput::stop(), and ~SoapySDROutputThread().
 {
     if (!m_running) {
         return;
     }
     m_running = false;
     wait();
 }
Member Data Documentation
m_channels
Channel* SoapySDROutputThread::m_channels private
Array of channels dynamically allocated for the given number of Tx channels.
Definition at line 85 of file soapysdroutputthread.h.
Referenced by callbackMO(), callbackSO12(), callbackSO16(), callbackSO8(), callbackSOIF(), getFifo(), getLog2Interpolation(), getNbFifos(), setFifo(), setLog2Interpolation(), SoapySDROutputThread(), and ~SoapySDROutputThread().
m_dev
SoapySDR::Device* SoapySDROutputThread::m_dev private
Definition at line 83 of file soapysdroutputthread.h.
Referenced by run().
m_interpolatorType
InterpolatorType SoapySDROutputThread::m_interpolatorType private
Definition at line 88 of file soapysdroutputthread.h.
Referenced by callbackMO(), and run().
m_nbChannels
unsigned int SoapySDROutputThread::m_nbChannels private
Definition at line 87 of file soapysdroutputthread.h.
Referenced by callbackMO(), getFifo(), getLog2Interpolation(), getNbChannels(), getNbFifos(), run(), setFifo(), and setLog2Interpolation().
m_running
bool SoapySDROutputThread::m_running private
Definition at line 82 of file soapysdroutputthread.h.
Referenced by isRunning(), run(), startWork(), stopWork(), and ~SoapySDROutputThread().
m_sampleRate
unsigned int SoapySDROutputThread::m_sampleRate private
Definition at line 86 of file soapysdroutputthread.h.
Referenced by getSampleRate(), run(), and setSampleRate().
m_startWaiter
QWaitCondition SoapySDROutputThread::m_startWaiter private
Definition at line 81 of file soapysdroutputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex SoapySDROutputThread::m_startWaitMutex private
Definition at line 80 of file soapysdroutputthread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/samplesink/soapysdroutput/soapysdroutputthread.h
plugins/samplesink/soapysdroutput/soapysdroutputthread.cpp