SDRAngel: BladeRF2OutputThread Class Reference
BladeRF2OutputThread Class Reference
#include <bladerf2outputthread.h>
Inherits QThread.
Classes
struct Channel
Public Member Functions
BladeRF2OutputThread (struct bladerf *dev, unsigned int nbTxChannels, QObject *parent=0)
~BladeRF2OutputThread ()
void startWork ()
void stopWork ()
bool isRunning () const
unsigned int getNbChannels () const
void setLog2Interpolation (unsigned int channel, unsigned int log2_interp)
unsigned int getLog2Interpolation (unsigned int channel) const
void setFifo (unsigned int channel, SampleSourceFifo *sampleFifo)
SampleSourceFifo * getFifo (unsigned int channel)
Private Member Functions
void run ()
unsigned int getNbFifos ()
void callbackSO (qint16 *buf, qint32 len, unsigned int channel=0)
void callbackMO (qint16 *buf, qint32 samplesPerChannel)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
struct bladerf * m_dev
Channel * m_channels
Array of channels dynamically allocated for the given number of Tx channels.
qint16 * m_buf
Full buffer for SISO or MIMO operation.
unsigned int m_nbChannels
Detailed Description
Definition at line 31 of file bladerf2outputthread.h.
Constructor & Destructor Documentation
BladeRF2OutputThread()
BladeRF2OutputThread::BladeRF2OutputThread (struct bladerf * dev, unsigned int nbTxChannels, QObject * parent = 0)
Definition at line 24 of file bladerf2outputthread.cpp.
References DeviceBladeRF2::blockSize, m_buf, and m_channels.
                                                                                                           :
     QThread(parent),
     m_running(false),
     m_dev(dev),
     m_nbChannels(nbTxChannels)
 {
     qDebug("BladeRF2OutputThread::BladeRF2OutputThread");
     m_channels = new Channel[nbTxChannels];
     m_buf = new qint16[2*DeviceBladeRF2::blockSize*nbTxChannels];
 }
~BladeRF2OutputThread()
BladeRF2OutputThread::~BladeRF2OutputThread ()
Definition at line 35 of file bladerf2outputthread.cpp.
References m_buf, m_channels, m_running, and stopWork().
 {
     qDebug("BladeRF2OutputThread::~BladeRF2OutputThread");
     if (m_running) {
         stopWork();
     }
     delete[] m_buf;
     delete[] m_channels;
 }
Member Function Documentation
callbackMO()
void BladeRF2OutputThread::callbackMO (qint16 * buf, qint32 samplesPerChannel) private
Definition at line 170 of file bladerf2outputthread.cpp.
References callbackSO(), m_channels, and m_nbChannels.
Referenced by run().
 {
     for (unsigned int channel = 0; channel < m_nbChannels; channel++)
     {
         if (m_channels[channel].m_sampleFifo) {
             callbackSO(&buf[2*samplesPerChannel*channel], samplesPerChannel, channel);
         } else {
             std::fill(&buf[2*samplesPerChannel*channel], &buf[2*samplesPerChannel*channel]+2*samplesPerChannel, 0); // fill with zero samples
         }
     }
     // TODO: write a set of interpolators that can write interleaved samples in output directly
     int status = bladerf_interleave_stream_buffer(BLADERF_TX_X2, BLADERF_FORMAT_SC16_Q11 , samplesPerChannel*m_nbChannels, (void *) buf);
     if (status < 0)
     {
         qCritical("BladeRF2OutputThread::callbackMI: cannot interleave buffer: %s", bladerf_strerror(status));
         return;
     }
 }
callbackSO()
void BladeRF2OutputThread::callbackSO (qint16 * buf, qint32 len, unsigned int channel = 0) private
Definition at line 192 of file bladerf2outputthread.cpp.
References SampleSourceFifo::getRWBalance(), Interpolators< T, SdrBits, OutputBits >::interpolate1(), Interpolators< T, SdrBits, OutputBits >::interpolate16_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate2_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate32_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate4_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate64_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate8_cen(), m_channels, BladeRF2OutputThread::Channel::m_interpolators, BladeRF2OutputThread::Channel::m_sampleFifo, and SampleSourceFifo::readAdvance().
Referenced by callbackMO(), and run().
 {
     if (m_channels[channel].m_sampleFifo)
     {
         float bal = m_channels[channel].m_sampleFifo->getRWBalance();
         if (bal < -0.25) {
             qDebug("BladeRF2OutputThread::callbackSO: read lags: %f", bal);
         } else if (bal > 0.25) {
             qDebug("BladeRF2OutputThread::callbackSO: read leads: %f", bal);
         }
         SampleVector::iterator beginRead;
         m_channels[channel].m_sampleFifo->readAdvance(beginRead, len/(1<<m_channels[channel].m_log2Interp));
         beginRead -= len;
         if (m_channels[channel].m_log2Interp == 0)
         {
             m_channels[channel].m_interpolators.interpolate1(&beginRead, buf, len*2);
         }
         else
         {
             switch (m_channels[channel].m_log2Interp)
             {
             case 1:
                 m_channels[channel].m_interpolators.interpolate2_cen(&beginRead, buf, len*2);
                 break;
             case 2:
                 m_channels[channel].m_interpolators.interpolate4_cen(&beginRead, buf, len*2);
                 break;
             case 3:
                 m_channels[channel].m_interpolators.interpolate8_cen(&beginRead, buf, len*2);
                 break;
             case 4:
                 m_channels[channel].m_interpolators.interpolate16_cen(&beginRead, buf, len*2);
                 break;
             case 5:
                 m_channels[channel].m_interpolators.interpolate32_cen(&beginRead, buf, len*2);
                 break;
             case 6:
                 m_channels[channel].m_interpolators.interpolate64_cen(&beginRead, buf, len*2);
                 break;
             default:
                 break;
             }
         }
     }
     else
     {
         std::fill(buf, buf+2*len, 0);
     }
 }
getFifo()
SampleSourceFifo * BladeRF2OutputThread::getFifo (unsigned int channel)
Definition at line 161 of file bladerf2outputthread.cpp.
References m_channels, m_nbChannels, and BladeRF2OutputThread::Channel::m_sampleFifo.
Referenced by BladeRF2Output::applySettings(), getNbChannels(), BladeRF2Output::start(), and BladeRF2Output::stop().
 {
     if (channel < m_nbChannels) {
         return m_channels[channel].m_sampleFifo;
     } else {
         return 0;
     }
 }
getLog2Interpolation()
unsigned int BladeRF2OutputThread::getLog2Interpolation (unsigned int channel) const
Definition at line 145 of file bladerf2outputthread.cpp.
References m_channels, BladeRF2OutputThread::Channel::m_log2Interp, and m_nbChannels.
Referenced by getNbChannels(), BladeRF2Output::start(), and BladeRF2Output::stop().
 {
     if (channel < m_nbChannels) {
         return m_channels[channel].m_log2Interp;
     } else {
         return 0;
     }
 }
getNbChannels()
unsigned int BladeRF2OutputThread::getNbChannels () const inline
Definition at line 41 of file bladerf2outputthread.h.
References getFifo(), getLog2Interpolation(), m_nbChannels, setFifo(), and setLog2Interpolation().
Referenced by BladeRF2Output::getNbChannels(), BladeRF2Output::start(), and BladeRF2Output::stop().
 { return m_nbChannels; }
getNbFifos()
unsigned int BladeRF2OutputThread::getNbFifos () private
Definition at line 124 of file bladerf2outputthread.cpp.
References i, m_channels, and m_nbChannels.
Referenced by run().
 {
     unsigned int fifoCount = 0;
     for (unsigned int i = 0; i < m_nbChannels; i++)
     {
         if (m_channels[i].m_sampleFifo) {
             fifoCount++;
         }
     }
     return fifoCount;
 }
isRunning()
bool BladeRF2OutputThread::isRunning () const inline
Definition at line 40 of file bladerf2outputthread.h.
References m_running.
 { return m_running; }
run()
void BladeRF2OutputThread::run () private
Definition at line 65 of file bladerf2outputthread.cpp.
References DeviceBladeRF2::blockSize, callbackMO(), callbackSO(), getNbFifos(), m_buf, m_dev, m_nbChannels, m_running, and m_startWaiter.
 {
     int res;
     m_running = true;
     m_startWaiter.wakeAll();
     unsigned int nbFifos = getNbFifos();
     if ((m_nbChannels > 0) && (nbFifos > 0))
     {
         int status;
         if (m_nbChannels > 1) {
             status = bladerf_sync_config(m_dev, BLADERF_TX_X2, BLADERF_FORMAT_SC16_Q11, 128, 16384, 32, 1500);
         } else {
             status = bladerf_sync_config(m_dev, BLADERF_TX_X1, BLADERF_FORMAT_SC16_Q11, 64, 8192, 32, 1500);
         }
         if (status < 0)
         {
             qCritical("BladeRF2OutputThread::run: cannot configure streams: %s", bladerf_strerror(status));
         }
         else
         {
             qDebug("BladeRF2OutputThread::run: start running loop");
             while (m_running)
             {
                 if (m_nbChannels > 1)
                 {
                     callbackMO(m_buf, DeviceBladeRF2::blockSize);
                     res = bladerf_sync_tx(m_dev, m_buf, DeviceBladeRF2::blockSize*m_nbChannels, 0, 1500);
                 }
                 else
                 {
                     callbackSO(m_buf, DeviceBladeRF2::blockSize);
                     res = bladerf_sync_tx(m_dev, m_buf, DeviceBladeRF2::blockSize, 0, 1500);
                 }
                 if (res < 0)
                 {
                     qCritical("BladeRF2OutputThread::run sync Rx error: %s", bladerf_strerror(res));
                     break;
                 }
             }
             qDebug("BladeRF2OutputThread::run: stop running loop");
         }
     }
     else
     {
         qWarning("BladeRF2OutputThread::run: no channels or FIFO allocated. Aborting");
     }
     m_running = false;
 }
setFifo()
void BladeRF2OutputThread::setFifo (unsigned int channel, SampleSourceFifo * sampleFifo)
Definition at line 154 of file bladerf2outputthread.cpp.
References m_channels, m_nbChannels, and BladeRF2OutputThread::Channel::m_sampleFifo.
Referenced by BladeRF2Output::applySettings(), getNbChannels(), BladeRF2Output::start(), and BladeRF2Output::stop().
 {
     if (channel < m_nbChannels) {
         m_channels[channel].m_sampleFifo = sampleFifo;
     }
 }
setLog2Interpolation()
void BladeRF2OutputThread::setLog2Interpolation (unsigned int channel, unsigned int log2_interp)
Definition at line 138 of file bladerf2outputthread.cpp.
References m_channels, BladeRF2OutputThread::Channel::m_log2Interp, and m_nbChannels.
Referenced by BladeRF2Output::applySettings(), getNbChannels(), BladeRF2Output::start(), and BladeRF2Output::stop().
 {
     if (channel < m_nbChannels) {
         m_channels[channel].m_log2Interp = log2_interp;
     }
 }
startWork()
void BladeRF2OutputThread::startWork ()
Definition at line 47 of file bladerf2outputthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by BladeRF2Output::start(), and BladeRF2Output::stop().
 {
     m_startWaitMutex.lock();
     start();
     while(!m_running) {
         m_startWaiter.wait(&m_startWaitMutex, 100);
     }
     m_startWaitMutex.unlock();
 }
stopWork()
void BladeRF2OutputThread::stopWork ()
Definition at line 59 of file bladerf2outputthread.cpp.
References m_running.
Referenced by BladeRF2Output::start(), BladeRF2Output::stop(), and ~BladeRF2OutputThread().
 {
     m_running = false;
     wait();
 }
Member Data Documentation
m_buf
qint16* BladeRF2OutputThread::m_buf private
Full buffer for SISO or MIMO operation.
Definition at line 69 of file bladerf2outputthread.h.
Referenced by BladeRF2OutputThread(), run(), and ~BladeRF2OutputThread().
m_channels
Channel* BladeRF2OutputThread::m_channels private
Array of channels dynamically allocated for the given number of Tx channels.
Definition at line 68 of file bladerf2outputthread.h.
Referenced by BladeRF2OutputThread(), callbackMO(), callbackSO(), getFifo(), getLog2Interpolation(), getNbFifos(), setFifo(), setLog2Interpolation(), and ~BladeRF2OutputThread().
m_dev
struct bladerf* BladeRF2OutputThread::m_dev private
Definition at line 66 of file bladerf2outputthread.h.
Referenced by run().
m_nbChannels
unsigned int BladeRF2OutputThread::m_nbChannels private
Definition at line 70 of file bladerf2outputthread.h.
Referenced by callbackMO(), getFifo(), getLog2Interpolation(), getNbChannels(), getNbFifos(), run(), setFifo(), and setLog2Interpolation().
m_running
bool BladeRF2OutputThread::m_running private
Definition at line 65 of file bladerf2outputthread.h.
Referenced by isRunning(), run(), startWork(), stopWork(), and ~BladeRF2OutputThread().
m_startWaiter
QWaitCondition BladeRF2OutputThread::m_startWaiter private
Definition at line 64 of file bladerf2outputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex BladeRF2OutputThread::m_startWaitMutex private
Definition at line 63 of file bladerf2outputthread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/samplesink/bladerf2output/bladerf2outputthread.h
plugins/samplesink/bladerf2output/bladerf2outputthread.cpp