SDRAngel: WebAPIServer Class Reference
WebAPIServer Class Reference
#include <webapiserver.h>
Public Member Functions
WebAPIServer (const QString &host, uint16_t port, WebAPIRequestMapper *requestMapper)
~WebAPIServer ()
void start ()
void stop ()
void setHostAndPort (const QString &host, uint16_t port)
const QString & getHost () const
int getPort () const
Private Attributes
WebAPIRequestMapper * m_requestMapper
qtwebapp::HttpListener * m_listener
qtwebapp::HttpListenerSettings m_settings
Detailed Description
Definition at line 33 of file webapiserver.h.
Constructor & Destructor Documentation
WebAPIServer()
WebAPIServer::WebAPIServer (const QString & host, uint16_t port, WebAPIRequestMapper * requestMapper)
Definition at line 26 of file webapiserver.cpp.
References qtwebapp::HttpListenerSettings::host, m_settings, and qtwebapp::HttpListenerSettings::port.
                                                                                                  :
     m_requestMapper(requestMapper),
     m_listener(0)
 {
     m_settings.host = host;
     m_settings.port = port;
 }
~WebAPIServer()
WebAPIServer::~WebAPIServer ()
Definition at line 34 of file webapiserver.cpp.
References m_listener.
 {
     if (m_listener) { delete m_listener; }
 }
Member Function Documentation
getHost()
const QString& WebAPIServer::getHost () const inline
Definition at line 43 of file webapiserver.h.
Referenced by MainWindow::commandKeyPressed(), and MainWindow::on_commandRun_clicked().
 { return m_settings.host; }
getPort()
int WebAPIServer::getPort () const inline
Definition at line 44 of file webapiserver.h.
Referenced by MainWindow::commandKeyPressed(), and MainWindow::on_commandRun_clicked().
 { return m_settings.port; }
setHostAndPort()
void WebAPIServer::setHostAndPort (const QString & host, uint16_t port)
Definition at line 58 of file webapiserver.cpp.
References qtwebapp::HttpListenerSettings::host, m_listener, m_requestMapper, m_settings, qtwebapp::HttpListenerSettings::port, and stop().
 {
     stop();
     m_settings.host = host;
     m_settings.port = port;
     m_listener = new qtwebapp::HttpListener(m_settings, m_requestMapper, qApp);
 }
start()
void WebAPIServer::start ()
Definition at line 39 of file webapiserver.cpp.
References qtwebapp::HttpListenerSettings::host, m_listener, m_requestMapper, m_settings, and qtwebapp::HttpListenerSettings::port.
Referenced by MainCore::MainCore(), and MainWindow::MainWindow().
 {
     if (!m_listener)
     {
         m_listener = new qtwebapp::HttpListener(m_settings, m_requestMapper, qApp);
         qInfo("WebAPIServer::start: starting web API server at http://%s:%d", qPrintable(m_settings.host), m_settings.port);
     }
 }
stop()
void WebAPIServer::stop ()
Definition at line 48 of file webapiserver.cpp.
References qtwebapp::HttpListenerSettings::host, m_listener, m_settings, and qtwebapp::HttpListenerSettings::port.
Referenced by setHostAndPort(), MainCore::~MainCore(), and MainWindow::~MainWindow().
 {
     if (m_listener)
     {
         delete m_listener;
         m_listener = 0;
         qInfo("WebAPIServer::stop: stopped web API server at http://%s:%d", qPrintable(m_settings.host), m_settings.port);
     }
 }
Member Data Documentation
m_listener
qtwebapp::HttpListener* WebAPIServer::m_listener private
Definition at line 48 of file webapiserver.h.
Referenced by setHostAndPort(), start(), stop(), and ~WebAPIServer().
m_requestMapper
WebAPIRequestMapper* WebAPIServer::m_requestMapper private
Definition at line 47 of file webapiserver.h.
Referenced by setHostAndPort(), and start().
m_settings
qtwebapp::HttpListenerSettings WebAPIServer::m_settings private
Definition at line 49 of file webapiserver.h.
Referenced by setHostAndPort(), start(), stop(), and WebAPIServer().
The documentation for this class was generated from the following files:
sdrbase/webapi/webapiserver.h
sdrbase/webapi/webapiserver.cpp