SDRAngel: NFMMod::MsgConfigureNFMMod Class Reference
NFMMod::MsgConfigureNFMMod Class Reference
#include <nfmmod.h>
Public Member Functions
const NFMModSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureNFMMod * create (const NFMModSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureNFMMod (const NFMModSettings &settings, bool force)
Private Attributes
NFMModSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 53 of file nfmmod.h.
Constructor & Destructor Documentation
MsgConfigureNFMMod()
NFMMod::MsgConfigureNFMMod::MsgConfigureNFMMod (const NFMModSettings & settings, bool force) inline private
Definition at line 69 of file nfmmod.h.
Referenced by create().
                                                                        :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureNFMMod* NFMMod::MsgConfigureNFMMod::create (const NFMModSettings & settings, bool force) inline static
Definition at line 60 of file nfmmod.h.
References MsgConfigureNFMMod().
Referenced by NFMModGUI::applySettings(), NFMMod::deserialize(), and NFMMod::webapiSettingsPutPatch().
         {
             return new MsgConfigureNFMMod(settings, force);
         }
getForce()
bool NFMMod::MsgConfigureNFMMod::getForce () const inline
Definition at line 58 of file nfmmod.h.
References m_force.
Referenced by NFMMod::handleMessage().
 { return m_force; }
getSettings()
const NFMModSettings& NFMMod::MsgConfigureNFMMod::getSettings () const inline
Definition at line 57 of file nfmmod.h.
References m_settings.
Referenced by NFMModGUI::handleMessage(), and NFMMod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool NFMMod::MsgConfigureNFMMod::m_force private
Definition at line 67 of file nfmmod.h.
Referenced by getForce().
m_settings
NFMModSettings NFMMod::MsgConfigureNFMMod::m_settings private
Definition at line 66 of file nfmmod.h.
Referenced by NFMMod::getCenterFrequency(), getSettings(), NFMMod::getStreamCenterFrequency(), and NFMMod::getTitle().
The documentation for this class was generated from the following file:
plugins/channeltx/modnfm/nfmmod.h