SDRAngel: SWGSDRangel::SWGErrorResponse Class Reference
SWGSDRangel::SWGErrorResponse Class Reference
#include <SWGErrorResponse.h>
Public Member Functions
SWGErrorResponse ()
SWGErrorResponse (QString *json)
virtual ~SWGErrorResponse ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGErrorResponse * fromJson (QString &jsonString) override
QString * getMessage ()
void setMessage (QString *message)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * message
bool m_message_isSet
Detailed Description
Definition at line 32 of file SWGErrorResponse.h.
Constructor & Destructor Documentation
SWGErrorResponse() [1/2]
SWGSDRangel::SWGErrorResponse::SWGErrorResponse ()
Definition at line 30 of file SWGErrorResponse.cpp.
References m_message_isSet, and message.
{
     message = nullptr;
     m_message_isSet = false;
 }
SWGErrorResponse() [2/2]
SWGSDRangel::SWGErrorResponse::SWGErrorResponse (QString * json)
Definition at line 25 of file SWGErrorResponse.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGErrorResponse()
SWGSDRangel::SWGErrorResponse::~SWGErrorResponse () virtual
Definition at line 35 of file SWGErrorResponse.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGErrorResponse::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 68 of file SWGErrorResponse.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::devicesetChannelIndexService(), WebAPIRequestMapper::devicesetChannelReportService(), WebAPIRequestMapper::devicesetChannelService(), WebAPIRequestMapper::devicesetChannelSettingsService(), WebAPIRequestMapper::devicesetChannelsReportService(), WebAPIRequestMapper::devicesetDeviceReportService(), WebAPIRequestMapper::devicesetDeviceRunService(), WebAPIRequestMapper::devicesetDeviceService(), WebAPIRequestMapper::devicesetDeviceSettingsService(), WebAPIRequestMapper::devicesetFocusService(), WebAPIRequestMapper::devicesetService(), WebAPIRequestMapper::instanceAMBEDevicesService(), WebAPIRequestMapper::instanceAMBESerialService(), WebAPIRequestMapper::instanceAudioInputCleanupService(), WebAPIRequestMapper::instanceAudioInputParametersService(), WebAPIRequestMapper::instanceAudioOutputCleanupService(), WebAPIRequestMapper::instanceAudioOutputParametersService(), WebAPIRequestMapper::instanceAudioService(), WebAPIRequestMapper::instanceChannelsService(), WebAPIRequestMapper::instanceConfigService(), WebAPIRequestMapper::instanceDeviceSetService(), WebAPIRequestMapper::instanceDeviceSetsService(), WebAPIRequestMapper::instanceDevicesService(), WebAPIRequestMapper::instanceLocationService(), WebAPIRequestMapper::instanceLoggingService(), WebAPIRequestMapper::instancePresetFileService(), WebAPIRequestMapper::instancePresetService(), WebAPIRequestMapper::instancePresetsService(), WebAPIRequestMapper::instanceSummaryService(), WebAPIRequestMapper::parseJsonBody(), and WebAPIRequestMapper::service().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGErrorResponse::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 79 of file SWGErrorResponse.cpp.
References message, and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(message != nullptr && *message != QString("")){
         toJsonValue(QString("message"), message, obj, QString("QString"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGErrorResponse::cleanup ()
Definition at line 46 of file SWGErrorResponse.cpp.
References message.
Referenced by ~SWGErrorResponse().
{
     if(message != nullptr) {
         delete message;
     }
 }
fromJson()
SWGErrorResponse * SWGSDRangel::SWGErrorResponse::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 53 of file SWGErrorResponse.cpp.
References fromJsonObject().
Referenced by SWGErrorResponse().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGErrorResponse::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 62 of file SWGErrorResponse.cpp.
References message, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&message, pJson["message"], "QString", "QString");
 }
getMessage()
QString * SWGSDRangel::SWGErrorResponse::getMessage ()
Definition at line 89 of file SWGErrorResponse.cpp.
References message.
Referenced by WebAPIAdapterGUI::devicesetChannelDelete(), WebAPIAdapterSrv::devicesetChannelDelete(), WebAPIAdapterInterface::devicesetChannelDelete(), WebAPIRequestMapper::devicesetChannelIndexService(), WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterSrv::devicesetChannelPost(), WebAPIAdapterInterface::devicesetChannelPost(), WebAPIAdapterGUI::devicesetChannelReportGet(), WebAPIAdapterSrv::devicesetChannelReportGet(), WebAPIAdapterInterface::devicesetChannelReportGet(), WebAPIRequestMapper::devicesetChannelReportService(), WebAPIRequestMapper::devicesetChannelService(), WebAPIAdapterGUI::devicesetChannelSettingsGet(), WebAPIAdapterSrv::devicesetChannelSettingsGet(), WebAPIAdapterInterface::devicesetChannelSettingsGet(), WebAPIAdapterGUI::devicesetChannelSettingsPutPatch(), WebAPIAdapterSrv::devicesetChannelSettingsPutPatch(), WebAPIAdapterInterface::devicesetChannelSettingsPutPatch(), WebAPIRequestMapper::devicesetChannelSettingsService(), WebAPIAdapterGUI::devicesetChannelsReportGet(), WebAPIAdapterSrv::devicesetChannelsReportGet(), WebAPIAdapterInterface::devicesetChannelsReportGet(), WebAPIRequestMapper::devicesetChannelsReportService(), WebAPIAdapterGUI::devicesetDevicePut(), WebAPIAdapterSrv::devicesetDevicePut(), WebAPIAdapterInterface::devicesetDevicePut(), WebAPIAdapterGUI::devicesetDeviceReportGet(), WebAPIAdapterSrv::devicesetDeviceReportGet(), WebAPIAdapterInterface::devicesetDeviceReportGet(), WebAPIRequestMapper::devicesetDeviceReportService(), WebAPIAdapterGUI::devicesetDeviceRunDelete(), WebAPIAdapterSrv::devicesetDeviceRunDelete(), WebAPIAdapterInterface::devicesetDeviceRunDelete(), WebAPIAdapterGUI::devicesetDeviceRunGet(), WebAPIAdapterSrv::devicesetDeviceRunGet(), WebAPIAdapterInterface::devicesetDeviceRunGet(), WebAPIAdapterGUI::devicesetDeviceRunPost(), WebAPIAdapterSrv::devicesetDeviceRunPost(), WebAPIAdapterInterface::devicesetDeviceRunPost(), WebAPIRequestMapper::devicesetDeviceRunService(), WebAPIRequestMapper::devicesetDeviceService(), WebAPIAdapterGUI::devicesetDeviceSettingsGet(), WebAPIAdapterSrv::devicesetDeviceSettingsGet(), WebAPIAdapterInterface::devicesetDeviceSettingsGet(), WebAPIAdapterGUI::devicesetDeviceSettingsPutPatch(), WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch(), WebAPIAdapterInterface::devicesetDeviceSettingsPutPatch(), WebAPIRequestMapper::devicesetDeviceSettingsService(), WebAPIAdapterGUI::devicesetFocusPatch(), WebAPIAdapterSrv::devicesetFocusPatch(), WebAPIAdapterInterface::devicesetFocusPatch(), WebAPIRequestMapper::devicesetFocusService(), WebAPIAdapterGUI::devicesetGet(), WebAPIAdapterSrv::devicesetGet(), WebAPIAdapterInterface::devicesetGet(), WebAPIRequestMapper::devicesetService(), WebAPIAdapterInterface::instanceAMBEDevicesDelete(), WebAPIAdapterInterface::instanceAMBEDevicesGet(), WebAPIAdapterInterface::instanceAMBEDevicesPatch(), WebAPIAdapterInterface::instanceAMBEDevicesPut(), WebAPIRequestMapper::instanceAMBEDevicesService(), WebAPIAdapterInterface::instanceAMBESerialGet(), WebAPIRequestMapper::instanceAMBESerialService(), WebAPIAdapterInterface::instanceAudioGet(), WebAPIAdapterInterface::instanceAudioInputCleanupPatch(), WebAPIRequestMapper::instanceAudioInputCleanupService(), WebAPIAdapterGUI::instanceAudioInputDelete(), WebAPIAdapterSrv::instanceAudioInputDelete(), WebAPIAdapterInterface::instanceAudioInputDelete(), WebAPIRequestMapper::instanceAudioInputParametersService(), WebAPIAdapterGUI::instanceAudioInputPatch(), WebAPIAdapterSrv::instanceAudioInputPatch(), WebAPIAdapterInterface::instanceAudioInputPatch(), WebAPIAdapterInterface::instanceAudioOutputCleanupPatch(), WebAPIRequestMapper::instanceAudioOutputCleanupService(), WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterInterface::instanceAudioOutputDelete(), WebAPIRequestMapper::instanceAudioOutputParametersService(), WebAPIAdapterGUI::instanceAudioOutputPatch(), WebAPIAdapterSrv::instanceAudioOutputPatch(), WebAPIAdapterInterface::instanceAudioOutputPatch(), WebAPIRequestMapper::instanceAudioService(), WebAPIAdapterInterface::instanceChannels(), WebAPIRequestMapper::instanceChannelsService(), WebAPIAdapterInterface::instanceConfigGet(), WebAPIAdapterGUI::instanceDelete(), WebAPIAdapterInterface::instanceDelete(), WebAPIAdapterInterface::instanceDevices(), WebAPIAdapterGUI::instanceDeviceSetDelete(), WebAPIAdapterSrv::instanceDeviceSetDelete(), WebAPIAdapterInterface::instanceDeviceSetDelete(), WebAPIAdapterInterface::instanceDeviceSetPost(), WebAPIRequestMapper::instanceDeviceSetService(), WebAPIAdapterInterface::instanceDeviceSetsGet(), WebAPIRequestMapper::instanceDeviceSetsService(), WebAPIRequestMapper::instanceDevicesService(), WebAPIAdapterInterface::instanceLocationGet(), WebAPIAdapterInterface::instanceLocationPut(), WebAPIRequestMapper::instanceLocationService(), WebAPIAdapterInterface::instanceLoggingGet(), WebAPIAdapterInterface::instanceLoggingPut(), WebAPIRequestMapper::instanceLoggingService(), WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterInterface::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterInterface::instancePresetFilePost(), WebAPIAdapterSrv::instancePresetFilePut(), WebAPIAdapterInterface::instancePresetFilePut(), WebAPIRequestMapper::instancePresetFileService(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterInterface::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterInterface::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), WebAPIAdapterInterface::instancePresetPut(), WebAPIRequestMapper::instancePresetService(), WebAPIAdapterInterface::instancePresetsGet(), WebAPIAdapterInterface::instanceSummary(), WebAPIRequestMapper::instanceSummaryService(), WebAPIRequestMapper::parseJsonBody(), and WebAPIRequestMapper::service().
{
     return message;
 }
init()
void SWGSDRangel::SWGErrorResponse::init ()
Definition at line 40 of file SWGErrorResponse.cpp.
References m_message_isSet, and message.
Referenced by WebAPIAdapterGUI::devicesetChannelDelete(), WebAPIAdapterSrv::devicesetChannelDelete(), WebAPIAdapterInterface::devicesetChannelDelete(), WebAPIRequestMapper::devicesetChannelIndexService(), WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterSrv::devicesetChannelPost(), WebAPIAdapterInterface::devicesetChannelPost(), WebAPIAdapterGUI::devicesetChannelReportGet(), WebAPIAdapterSrv::devicesetChannelReportGet(), WebAPIAdapterInterface::devicesetChannelReportGet(), WebAPIRequestMapper::devicesetChannelReportService(), WebAPIRequestMapper::devicesetChannelService(), WebAPIAdapterGUI::devicesetChannelSettingsGet(), WebAPIAdapterSrv::devicesetChannelSettingsGet(), WebAPIAdapterInterface::devicesetChannelSettingsGet(), WebAPIAdapterGUI::devicesetChannelSettingsPutPatch(), WebAPIAdapterSrv::devicesetChannelSettingsPutPatch(), WebAPIAdapterInterface::devicesetChannelSettingsPutPatch(), WebAPIRequestMapper::devicesetChannelSettingsService(), WebAPIAdapterGUI::devicesetChannelsReportGet(), WebAPIAdapterSrv::devicesetChannelsReportGet(), WebAPIAdapterInterface::devicesetChannelsReportGet(), WebAPIRequestMapper::devicesetChannelsReportService(), WebAPIAdapterGUI::devicesetDevicePut(), WebAPIAdapterSrv::devicesetDevicePut(), WebAPIAdapterInterface::devicesetDevicePut(), WebAPIAdapterGUI::devicesetDeviceReportGet(), WebAPIAdapterSrv::devicesetDeviceReportGet(), WebAPIAdapterInterface::devicesetDeviceReportGet(), WebAPIRequestMapper::devicesetDeviceReportService(), WebAPIAdapterGUI::devicesetDeviceRunDelete(), WebAPIAdapterSrv::devicesetDeviceRunDelete(), WebAPIAdapterInterface::devicesetDeviceRunDelete(), WebAPIAdapterGUI::devicesetDeviceRunGet(), WebAPIAdapterSrv::devicesetDeviceRunGet(), WebAPIAdapterInterface::devicesetDeviceRunGet(), WebAPIAdapterGUI::devicesetDeviceRunPost(), WebAPIAdapterSrv::devicesetDeviceRunPost(), WebAPIAdapterInterface::devicesetDeviceRunPost(), WebAPIRequestMapper::devicesetDeviceRunService(), WebAPIRequestMapper::devicesetDeviceService(), WebAPIAdapterGUI::devicesetDeviceSettingsGet(), WebAPIAdapterSrv::devicesetDeviceSettingsGet(), WebAPIAdapterInterface::devicesetDeviceSettingsGet(), WebAPIAdapterGUI::devicesetDeviceSettingsPutPatch(), WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch(), WebAPIAdapterInterface::devicesetDeviceSettingsPutPatch(), WebAPIRequestMapper::devicesetDeviceSettingsService(), WebAPIAdapterGUI::devicesetFocusPatch(), WebAPIAdapterInterface::devicesetFocusPatch(), WebAPIRequestMapper::devicesetFocusService(), WebAPIAdapterGUI::devicesetGet(), WebAPIAdapterSrv::devicesetGet(), WebAPIAdapterInterface::devicesetGet(), WebAPIRequestMapper::devicesetService(), WebAPIAdapterInterface::instanceAMBEDevicesDelete(), WebAPIAdapterInterface::instanceAMBEDevicesGet(), WebAPIAdapterInterface::instanceAMBEDevicesPatch(), WebAPIAdapterInterface::instanceAMBEDevicesPut(), WebAPIRequestMapper::instanceAMBEDevicesService(), WebAPIAdapterInterface::instanceAMBESerialGet(), WebAPIRequestMapper::instanceAMBESerialService(), WebAPIAdapterInterface::instanceAudioGet(), WebAPIAdapterInterface::instanceAudioInputCleanupPatch(), WebAPIRequestMapper::instanceAudioInputCleanupService(), WebAPIAdapterGUI::instanceAudioInputDelete(), WebAPIAdapterSrv::instanceAudioInputDelete(), WebAPIAdapterInterface::instanceAudioInputDelete(), WebAPIRequestMapper::instanceAudioInputParametersService(), WebAPIAdapterGUI::instanceAudioInputPatch(), WebAPIAdapterSrv::instanceAudioInputPatch(), WebAPIAdapterInterface::instanceAudioInputPatch(), WebAPIAdapterInterface::instanceAudioOutputCleanupPatch(), WebAPIRequestMapper::instanceAudioOutputCleanupService(), WebAPIAdapterGUI::instanceAudioOutputDelete(), WebAPIAdapterSrv::instanceAudioOutputDelete(), WebAPIAdapterInterface::instanceAudioOutputDelete(), WebAPIRequestMapper::instanceAudioOutputParametersService(), WebAPIAdapterGUI::instanceAudioOutputPatch(), WebAPIAdapterSrv::instanceAudioOutputPatch(), WebAPIAdapterInterface::instanceAudioOutputPatch(), WebAPIRequestMapper::instanceAudioService(), WebAPIAdapterInterface::instanceChannels(), WebAPIRequestMapper::instanceChannelsService(), WebAPIAdapterInterface::instanceConfigGet(), WebAPIAdapterInterface::instanceDelete(), WebAPIAdapterInterface::instanceDevices(), WebAPIAdapterGUI::instanceDeviceSetDelete(), WebAPIAdapterSrv::instanceDeviceSetDelete(), WebAPIAdapterInterface::instanceDeviceSetDelete(), WebAPIAdapterInterface::instanceDeviceSetPost(), WebAPIRequestMapper::instanceDeviceSetService(), WebAPIAdapterInterface::instanceDeviceSetsGet(), WebAPIRequestMapper::instanceDeviceSetsService(), WebAPIRequestMapper::instanceDevicesService(), WebAPIAdapterInterface::instanceLocationGet(), WebAPIAdapterInterface::instanceLocationPut(), WebAPIRequestMapper::instanceLocationService(), WebAPIAdapterInterface::instanceLoggingGet(), WebAPIAdapterInterface::instanceLoggingPut(), WebAPIRequestMapper::instanceLoggingService(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterInterface::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterInterface::instancePresetFilePost(), WebAPIAdapterSrv::instancePresetFilePut(), WebAPIAdapterInterface::instancePresetFilePut(), WebAPIRequestMapper::instancePresetFileService(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterInterface::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterInterface::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), WebAPIAdapterInterface::instancePresetPut(), WebAPIRequestMapper::instancePresetService(), WebAPIAdapterInterface::instancePresetsGet(), WebAPIAdapterInterface::instanceSummary(), WebAPIRequestMapper::instanceSummaryService(), WebAPIRequestMapper::parseJsonBody(), WebAPIRequestMapper::service(), and SWGErrorResponse().
{
     message = new QString("");
     m_message_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGErrorResponse::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 100 of file SWGErrorResponse.cpp.
References message.
{
     bool isObjectUpdated = false;
     do{
         if(message != nullptr && *message != QString("")){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setMessage()
void SWGSDRangel::SWGErrorResponse::setMessage (QString * message)
Definition at line 93 of file SWGErrorResponse.cpp.
References m_message_isSet, and message.
{
     this->message = message;
     this->m_message_isSet = true;
 }
Member Data Documentation
m_message_isSet
bool SWGSDRangel::SWGErrorResponse::m_message_isSet private
Definition at line 53 of file SWGErrorResponse.h.
Referenced by init(), setMessage(), and SWGErrorResponse().
message
QString* SWGSDRangel::SWGErrorResponse::message private
Definition at line 52 of file SWGErrorResponse.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getMessage(), init(), isSet(), setMessage(), and SWGErrorResponse().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGErrorResponse.h
swagger/sdrangel/code/qt5/client/SWGErrorResponse.cpp