SDRAngel: LocalSinkThread Class Reference
LocalSinkThread Class Reference
#include <localsinkthread.h>
Inherits QThread.
Classes
class MsgStartStop
Public Slots
void processSamples (const quint8 *data, uint count)
Public Member Functions
LocalSinkThread (QObject *parent=0)
~LocalSinkThread ()
void startStop (bool start)
void setSampleFifo (SampleSinkFifo *sampleFifo)
Private Slots
void handleInputMessages ()
Private Member Functions
void startWork ()
void stopWork ()
void run ()
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
volatile bool m_running
SampleSinkFifo * m_sampleFifo
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 31 of file localsinkthread.h.
Constructor & Destructor Documentation
LocalSinkThread()
LocalSinkThread::LocalSinkThread (QObject * parent = 0)
Definition at line 24 of file localsinkthread.cpp.
Referenced by LocalSinkThread::MsgStartStop::MsgStartStop().
                                                 :
     QThread(parent),
     m_running(false),
     m_sampleFifo(0)
 {
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
 }
~LocalSinkThread()
LocalSinkThread::~LocalSinkThread ()
Definition at line 32 of file localsinkthread.cpp.
Referenced by LocalSinkThread::MsgStartStop::MsgStartStop().
 {
     qDebug("LocalSinkThread::~LocalSinkThread");
 }
Member Function Documentation
handleInputMessages
void LocalSinkThread::handleInputMessages () private slot
Definition at line 82 of file localsinkthread.cpp.
References LocalSinkThread::MsgStartStop::getStartStop(), m_inputMessageQueue, Message::match(), MessageQueue::pop(), startWork(), and stopWork().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (MsgStartStop::match(*message))
         {
             MsgStartStop* notif = (MsgStartStop*) message;
             qDebug("LocalSinkThread::handleInputMessages: MsgStartStop: %s", notif->getStartStop() ? "start" : "stop");
             if (notif->getStartStop()) {
                 startWork();
             } else {
                 stopWork();
             }
             delete message;
         }
     }
 }
processSamples
void LocalSinkThread::processSamples (const quint8 * data, uint count) slot
Definition at line 75 of file localsinkthread.cpp.
References m_sampleFifo, and SampleSinkFifo::write().
Referenced by setSampleFifo().
 {
     if (m_sampleFifo) {
         m_sampleFifo->write(data, count);
     }
 }
run()
void LocalSinkThread::run () private
Definition at line 60 of file localsinkthread.cpp.
References m_running, and m_startWaiter.
 {
     qDebug("LocalSinkThread::run: begin");
     m_running = true;
     m_startWaiter.wakeAll();
     while (m_running)
     {
         sleep(1); // Do nothing as everything is in the data handler (dequeuer)
     }
     m_running = false;
     qDebug("LocalSinkThread::run: end");
 }
setSampleFifo()
void LocalSinkThread::setSampleFifo (SampleSinkFifo * sampleFifo) inline
Definition at line 58 of file localsinkthread.h.
References m_sampleFifo, and processSamples().
Referenced by LocalSink::applySettings(), and LocalSink::start().
 { m_sampleFifo = sampleFifo; }
startStop()
void LocalSinkThread::startStop (bool start)
Definition at line 37 of file localsinkthread.cpp.
References LocalSinkThread::MsgStartStop::create(), m_inputMessageQueue, and MessageQueue::push().
Referenced by LocalSinkThread::MsgStartStop::MsgStartStop(), LocalSink::start(), and LocalSink::stop().
 {
     MsgStartStop *msg = MsgStartStop::create(start);
     m_inputMessageQueue.push(msg);
 }
startWork()
void LocalSinkThread::startWork () private
Definition at line 43 of file localsinkthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by handleInputMessages().
 {
     qDebug("LocalSinkThread::startWork");
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void LocalSinkThread::stopWork () private
Definition at line 53 of file localsinkthread.cpp.
References m_running.
Referenced by handleInputMessages().
 {
     qDebug("LocalSinkThread::stopWork");
     m_running = false;
     wait();
 }
Member Data Documentation
m_inputMessageQueue
MessageQueue LocalSinkThread::m_inputMessageQueue private
Definition at line 69 of file localsinkthread.h.
Referenced by handleInputMessages(), and startStop().
m_running
volatile bool LocalSinkThread::m_running private
Definition at line 66 of file localsinkthread.h.
Referenced by run(), startWork(), and stopWork().
m_sampleFifo
SampleSinkFifo* LocalSinkThread::m_sampleFifo private
Definition at line 67 of file localsinkthread.h.
Referenced by processSamples(), and setSampleFifo().
m_startWaiter
QWaitCondition LocalSinkThread::m_startWaiter private
Definition at line 65 of file localsinkthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex LocalSinkThread::m_startWaitMutex private
Definition at line 64 of file localsinkthread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/channelrx/localsink/localsinkthread.h
plugins/channelrx/localsink/localsinkthread.cpp