SDRAngel: DATVDemod::MsgConfigureDATVDemod Class Reference
DATVDemod::MsgConfigureDATVDemod Class Reference
#include <datvdemod.h>
Public Member Functions
const DATVDemodSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureDATVDemod * create (const DATVDemodSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureDATVDemod (const DATVDemodSettings &settings, bool force)
Private Attributes
DATVDemodSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 220 of file datvdemod.h.
Constructor & Destructor Documentation
MsgConfigureDATVDemod()
DATVDemod::MsgConfigureDATVDemod::MsgConfigureDATVDemod (const DATVDemodSettings & settings, bool force) inline private
Definition at line 236 of file datvdemod.h.
                                                                              :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureDATVDemod* DATVDemod::MsgConfigureDATVDemod::create (const DATVDemodSettings & settings, bool force) inline static
Definition at line 227 of file datvdemod.h.
Referenced by DATVDemodGUI::applySettings().
         {
             return new MsgConfigureDATVDemod(settings, force);
         }
getForce()
bool DATVDemod::MsgConfigureDATVDemod::getForce () const inline
Definition at line 225 of file datvdemod.h.
Referenced by DATVDemod::handleMessage().
 { return m_force; }
getSettings()
const DATVDemodSettings& DATVDemod::MsgConfigureDATVDemod::getSettings () const inline
Definition at line 224 of file datvdemod.h.
Referenced by DATVDemod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool DATVDemod::MsgConfigureDATVDemod::m_force private
Definition at line 234 of file datvdemod.h.
m_settings
DATVDemodSettings DATVDemod::MsgConfigureDATVDemod::m_settings private
Definition at line 233 of file datvdemod.h.
The documentation for this class was generated from the following file:
plugins/channelrx/demoddatv/datvdemod.h