SDRAngel: SWGSDRangel::SWGLoggingInfo Class Reference
SWGSDRangel::SWGLoggingInfo Class Reference
#include <SWGLoggingInfo.h>
Public Member Functions
SWGLoggingInfo ()
SWGLoggingInfo (QString *json)
virtual ~SWGLoggingInfo ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGLoggingInfo * fromJson (QString &jsonString) override
QString * getConsoleLevel ()
void setConsoleLevel (QString *console_level)
QString * getFileLevel ()
void setFileLevel (QString *file_level)
qint32 getDumpToFile ()
void setDumpToFile (qint32 dump_to_file)
QString * getFileName ()
void setFileName (QString *file_name)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * console_level
bool m_console_level_isSet
QString * file_level
bool m_file_level_isSet
qint32 dump_to_file
bool m_dump_to_file_isSet
QString * file_name
bool m_file_name_isSet
Detailed Description
Definition at line 32 of file SWGLoggingInfo.h.
Constructor & Destructor Documentation
SWGLoggingInfo() [1/2]
SWGSDRangel::SWGLoggingInfo::SWGLoggingInfo ()
Definition at line 30 of file SWGLoggingInfo.cpp.
References console_level, dump_to_file, file_level, file_name, m_console_level_isSet, m_dump_to_file_isSet, m_file_level_isSet, and m_file_name_isSet.
{
     console_level = nullptr;
     m_console_level_isSet = false;
     file_level = nullptr;
     m_file_level_isSet = false;
     dump_to_file = 0;
     m_dump_to_file_isSet = false;
     file_name = nullptr;
     m_file_name_isSet = false;
 }
SWGLoggingInfo() [2/2]
SWGSDRangel::SWGLoggingInfo::SWGLoggingInfo (QString * json)
Definition at line 25 of file SWGLoggingInfo.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGLoggingInfo()
SWGSDRangel::SWGLoggingInfo::~SWGLoggingInfo () virtual
Definition at line 41 of file SWGLoggingInfo.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGLoggingInfo::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 93 of file SWGLoggingInfo.cpp.
References asJsonObject().
Referenced by SWGSDRangel::SWGInstanceApi::instanceLoggingPut(), and WebAPIRequestMapper::instanceLoggingService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGLoggingInfo::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 104 of file SWGLoggingInfo.cpp.
References console_level, dump_to_file, file_level, file_name, m_dump_to_file_isSet, and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(console_level != nullptr && *console_level != QString("")){
         toJsonValue(QString("consoleLevel"), console_level, obj, QString("QString"));
     }
     if(file_level != nullptr && *file_level != QString("")){
         toJsonValue(QString("fileLevel"), file_level, obj, QString("QString"));
     }
     if(m_dump_to_file_isSet){
         obj->insert("dumpToFile", QJsonValue(dump_to_file));
     }
     if(file_name != nullptr && *file_name != QString("")){
         toJsonValue(QString("fileName"), file_name, obj, QString("QString"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGLoggingInfo::cleanup ()
Definition at line 58 of file SWGLoggingInfo.cpp.
References console_level, file_level, and file_name.
Referenced by ~SWGLoggingInfo().
{
     if(console_level != nullptr) {
         delete console_level;
     }
     if(file_level != nullptr) {
         delete file_level;
     }
     if(file_name != nullptr) {
         delete file_name;
     }
 }
fromJson()
SWGLoggingInfo * SWGSDRangel::SWGLoggingInfo::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 72 of file SWGLoggingInfo.cpp.
References fromJsonObject().
Referenced by WebAPIRequestMapper::instanceLoggingService(), and SWGLoggingInfo().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGLoggingInfo::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 81 of file SWGLoggingInfo.cpp.
References console_level, dump_to_file, file_level, file_name, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&console_level, pJson["consoleLevel"], "QString", "QString");
     ::SWGSDRangel::setValue(&file_level, pJson["fileLevel"], "QString", "QString");
     ::SWGSDRangel::setValue(&dump_to_file, pJson["dumpToFile"], "qint32", "");
     ::SWGSDRangel::setValue(&file_name, pJson["fileName"], "QString", "QString");
 }
getConsoleLevel()
QString * SWGSDRangel::SWGLoggingInfo::getConsoleLevel ()
Definition at line 123 of file SWGLoggingInfo.cpp.
References console_level.
Referenced by WebAPIAdapterGUI::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingPut(), WebAPIAdapterGUI::instanceLoggingPut(), WebAPIAdapterSrv::instanceSummary(), and WebAPIAdapterGUI::instanceSummary().
{
     return console_level;
 }
getDumpToFile()
qint32 SWGSDRangel::SWGLoggingInfo::getDumpToFile ()
Definition at line 143 of file SWGLoggingInfo.cpp.
References dump_to_file.
Referenced by WebAPIAdapterGUI::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingPut(), WebAPIAdapterGUI::instanceLoggingPut(), WebAPIAdapterSrv::instanceSummary(), and WebAPIAdapterGUI::instanceSummary().
{
     return dump_to_file;
 }
getFileLevel()
QString * SWGSDRangel::SWGLoggingInfo::getFileLevel ()
Definition at line 133 of file SWGLoggingInfo.cpp.
References file_level.
Referenced by WebAPIAdapterGUI::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingPut(), WebAPIAdapterGUI::instanceLoggingPut(), WebAPIAdapterSrv::instanceSummary(), and WebAPIAdapterGUI::instanceSummary().
{
     return file_level;
 }
getFileName()
QString * SWGSDRangel::SWGLoggingInfo::getFileName ()
Definition at line 153 of file SWGLoggingInfo.cpp.
References file_name.
Referenced by WebAPIAdapterGUI::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingPut(), WebAPIAdapterGUI::instanceLoggingPut(), WebAPIAdapterSrv::instanceSummary(), and WebAPIAdapterGUI::instanceSummary().
{
     return file_name;
 }
init()
void SWGSDRangel::SWGLoggingInfo::init ()
Definition at line 46 of file SWGLoggingInfo.cpp.
References console_level, dump_to_file, file_level, file_name, m_console_level_isSet, m_dump_to_file_isSet, m_file_level_isSet, and m_file_name_isSet.
Referenced by WebAPIAdapterGUI::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingPut(), WebAPIAdapterGUI::instanceLoggingPut(), WebAPIAdapterSrv::instanceSummary(), WebAPIAdapterGUI::instanceSummary(), and SWGLoggingInfo().
                      {
     console_level = new QString("");
     m_console_level_isSet = false;
     file_level = new QString("");
     m_file_level_isSet = false;
     dump_to_file = 0;
     m_dump_to_file_isSet = false;
     file_name = new QString("");
     m_file_name_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGLoggingInfo::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 164 of file SWGLoggingInfo.cpp.
References console_level, file_level, file_name, and m_dump_to_file_isSet.
Referenced by SWGSDRangel::SWGInstanceSummaryResponse::asJsonObject(), and SWGSDRangel::SWGInstanceSummaryResponse::isSet().
                      {
     bool isObjectUpdated = false;
     do{
         if(console_level != nullptr && *console_level != QString("")){ isObjectUpdated = true; break;}
         if(file_level != nullptr && *file_level != QString("")){ isObjectUpdated = true; break;}
         if(m_dump_to_file_isSet){ isObjectUpdated = true; break;}
         if(file_name != nullptr && *file_name != QString("")){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setConsoleLevel()
void SWGSDRangel::SWGLoggingInfo::setConsoleLevel (QString * console_level)
Definition at line 127 of file SWGLoggingInfo.cpp.
References console_level, and m_console_level_isSet.
{
     this->console_level = console_level;
     this->m_console_level_isSet = true;
 }
setDumpToFile()
void SWGSDRangel::SWGLoggingInfo::setDumpToFile (qint32 dump_to_file)
Definition at line 147 of file SWGLoggingInfo.cpp.
References dump_to_file, and m_dump_to_file_isSet.
Referenced by WebAPIAdapterGUI::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingGet(), WebAPIAdapterSrv::instanceLoggingPut(), WebAPIAdapterGUI::instanceLoggingPut(), WebAPIAdapterSrv::instanceSummary(), and WebAPIAdapterGUI::instanceSummary().
{
     this->dump_to_file = dump_to_file;
     this->m_dump_to_file_isSet = true;
 }
setFileLevel()
void SWGSDRangel::SWGLoggingInfo::setFileLevel (QString * file_level)
Definition at line 137 of file SWGLoggingInfo.cpp.
References file_level, and m_file_level_isSet.
{
     this->file_level = file_level;
     this->m_file_level_isSet = true;
 }
setFileName()
void SWGSDRangel::SWGLoggingInfo::setFileName (QString * file_name)
Definition at line 157 of file SWGLoggingInfo.cpp.
References file_name, and m_file_name_isSet.
{
     this->file_name = file_name;
     this->m_file_name_isSet = true;
 }
Member Data Documentation
console_level
QString* SWGSDRangel::SWGLoggingInfo::console_level private
Definition at line 61 of file SWGLoggingInfo.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getConsoleLevel(), init(), isSet(), setConsoleLevel(), and SWGLoggingInfo().
dump_to_file
qint32 SWGSDRangel::SWGLoggingInfo::dump_to_file private
Definition at line 67 of file SWGLoggingInfo.h.
Referenced by asJsonObject(), fromJsonObject(), getDumpToFile(), init(), setDumpToFile(), and SWGLoggingInfo().
file_level
QString* SWGSDRangel::SWGLoggingInfo::file_level private
Definition at line 64 of file SWGLoggingInfo.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFileLevel(), init(), isSet(), setFileLevel(), and SWGLoggingInfo().
file_name
QString* SWGSDRangel::SWGLoggingInfo::file_name private
Definition at line 70 of file SWGLoggingInfo.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFileName(), init(), isSet(), setFileName(), and SWGLoggingInfo().
m_console_level_isSet
bool SWGSDRangel::SWGLoggingInfo::m_console_level_isSet private
Definition at line 62 of file SWGLoggingInfo.h.
Referenced by init(), setConsoleLevel(), and SWGLoggingInfo().
m_dump_to_file_isSet
bool SWGSDRangel::SWGLoggingInfo::m_dump_to_file_isSet private
Definition at line 68 of file SWGLoggingInfo.h.
Referenced by asJsonObject(), init(), isSet(), setDumpToFile(), and SWGLoggingInfo().
m_file_level_isSet
bool SWGSDRangel::SWGLoggingInfo::m_file_level_isSet private
Definition at line 65 of file SWGLoggingInfo.h.
Referenced by init(), setFileLevel(), and SWGLoggingInfo().
m_file_name_isSet
bool SWGSDRangel::SWGLoggingInfo::m_file_name_isSet private
Definition at line 71 of file SWGLoggingInfo.h.
Referenced by init(), setFileName(), and SWGLoggingInfo().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGLoggingInfo.h
swagger/sdrangel/code/qt5/client/SWGLoggingInfo.cpp