SDRAngel: ScopeVis::MsgScopeVisNGChangeTrigger Class Reference
ScopeVis::MsgScopeVisNGChangeTrigger Class Reference
Public Member Functions
const TriggerData & getTriggerData () const
uint32_t getTriggerIndex () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgScopeVisNGChangeTrigger * create (const TriggerData &triggerData, uint32_t triggerIndex)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgScopeVisNGChangeTrigger (const TriggerData &triggerData, uint32_t triggerIndex)
Private Attributes
TriggerData m_triggerData
uint32_t m_triggerIndex
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 314 of file scopevis.h.
Constructor & Destructor Documentation
MsgScopeVisNGChangeTrigger()
ScopeVis::MsgScopeVisNGChangeTrigger::MsgScopeVisNGChangeTrigger (const TriggerData & triggerData, uint32_t triggerIndex) inline private
Definition at line 331 of file scopevis.h.
                                                                                           :
             m_triggerData(triggerData),
             m_triggerIndex(triggerIndex)
         {}
Member Function Documentation
create()
static MsgScopeVisNGChangeTrigger* ScopeVis::MsgScopeVisNGChangeTrigger::create (const TriggerData & triggerData, uint32_t triggerIndex) inline static
Definition at line 318 of file scopevis.h.
Referenced by ScopeVis::changeTrigger().
         {
             return new MsgScopeVisNGChangeTrigger(triggerData, triggerIndex);
         }
getTriggerData()
const TriggerData& ScopeVis::MsgScopeVisNGChangeTrigger::getTriggerData () const inline
Definition at line 324 of file scopevis.h.
Referenced by ScopeVis::handleMessage().
 { return m_triggerData; }
getTriggerIndex()
uint32_t ScopeVis::MsgScopeVisNGChangeTrigger::getTriggerIndex () const inline
Definition at line 325 of file scopevis.h.
Referenced by ScopeVis::handleMessage().
 { return m_triggerIndex; }
Member Data Documentation
m_triggerData
TriggerData ScopeVis::MsgScopeVisNGChangeTrigger::m_triggerData private
Definition at line 328 of file scopevis.h.
m_triggerIndex
uint32_t ScopeVis::MsgScopeVisNGChangeTrigger::m_triggerIndex private
Definition at line 329 of file scopevis.h.
The documentation for this class was generated from the following file:
sdrgui/dsp/scopevis.h