SDRAngel: PerseusGui Class Reference
PerseusGui Class Reference
#include <perseusgui.h>
Public Member Functions
PerseusGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~PerseusGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
uint32_t getDevSampleRate (unsigned int index)
int getDevSampleRateIndex (uint32_t sampleRate)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void on_centerFrequency_changed (quint64 value)
void on_LOppm_valueChanged (int value)
void on_resetLOppm_clicked ()
void on_sampleRate_currentIndexChanged (int index)
void on_wideband_toggled (bool checked)
void on_decim_currentIndexChanged (int index)
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void on_transverter_clicked ()
void on_attenuator_currentIndexChanged (int index)
void on_adcDither_toggled (bool checked)
void on_adcPreamp_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void handleInputMessages ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void displaySampleRates ()
void updateFrequencyLimits ()
void sendSettings ()
void updateSampleRateAndFrequency ()
Private Attributes
Ui::PerseusGui * ui
DeviceUISet * m_deviceUISet
bool m_doApplySettings
bool m_forceSettings
PerseusSettings m_settings
QTimer m_updateTimer
QTimer m_statusTimer
std::vector< uint32_t > m_rates
PerseusInput * m_sampleSource
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 35 of file perseusgui.h.
Constructor & Destructor Documentation
PerseusGui()
PerseusGui::PerseusGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 34 of file perseusgui.cpp.
References displaySampleRates(), displaySettings(), PerseusInput::getSampleRates(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_rates, m_sampleSource, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), sendSettings(), PerseusInput::setMessageQueueToGUI(), ui, updateFrequencyLimits(), updateHardware(), and updateStatus().
                                                                 :
     QWidget(parent),
     ui(new Ui::PerseusGui),
     m_deviceUISet(deviceUISet),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_settings(),
     m_sampleSource(0),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     m_sampleSource = (PerseusInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     updateFrequencyLimits();
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     m_rates = m_sampleSource->getSampleRates();
     displaySampleRates();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
     sendSettings();
 }
~PerseusGui()
PerseusGui::~PerseusGui () virtual
Definition at line 67 of file perseusgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void PerseusGui::blockApplySettings (bool block) inline private
Definition at line 72 of file perseusgui.h.
Referenced by displaySettings(), and handleMessage().
 { m_doApplySettings = !block; }
deserialize()
bool PerseusGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 111 of file perseusgui.cpp.
References PerseusSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void PerseusGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 72 of file perseusgui.cpp.
 {
     delete this;
 }
displaySampleRates()
void PerseusGui::displaySampleRates () private
Definition at line 204 of file perseusgui.cpp.
References arg(), i, PerseusSettings::m_devSampleRateIndex, m_rates, m_settings, and ui.
Referenced by PerseusGui().
 {
     unsigned int savedIndex = m_settings.m_devSampleRateIndex;
     ui->sampleRate->blockSignals(true);
     if (m_rates.size() > 0)
     {
         ui->sampleRate->clear();
         for (unsigned int i = 0; i < m_rates.size(); i++)
         {
             int sampleRate = m_rates[i]/1000;
             ui->sampleRate->addItem(QString("%1").arg(QString("%1").arg(sampleRate, 5, 10, QChar(' '))));
         }
     }
     ui->sampleRate->blockSignals(false);
     if (savedIndex < m_rates.size())
     {
         ui->sampleRate->setCurrentIndex(savedIndex);
     }
     else
     {
         ui->sampleRate->setCurrentIndex((int) m_rates.size()-1);
     }
 }
displaySettings()
void PerseusGui::displaySettings () private
Definition at line 186 of file perseusgui.cpp.
References arg(), blockApplySettings(), PerseusSettings::m_adcDither, PerseusSettings::m_adcPreamp, PerseusSettings::m_attenuator, PerseusSettings::m_centerFrequency, PerseusSettings::m_devSampleRateIndex, PerseusSettings::m_log2Decim, PerseusSettings::m_LOppmTenths, m_settings, PerseusSettings::m_transverterDeltaFrequency, PerseusSettings::m_transverterMode, PerseusSettings::m_wideBand, ui, and updateFrequencyLimits().
Referenced by deserialize(), handleMessage(), PerseusGui(), resetToDefaults(), and setCenterFrequency().
 {
     blockApplySettings(true);
     updateFrequencyLimits();
     ui->transverter->setDeltaFrequency(m_settings.m_transverterDeltaFrequency);
     ui->transverter->setDeltaFrequencyActive(m_settings.m_transverterMode);
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     ui->LOppm->setValue(m_settings.m_LOppmTenths);
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     ui->sampleRate->setCurrentIndex(m_settings.m_devSampleRateIndex);
     ui->decim->setCurrentIndex(m_settings.m_log2Decim);
     ui->wideband->setChecked(m_settings.m_wideBand);
     ui->adcDither->setChecked(m_settings.m_adcDither);
     ui->adcPreamp->setChecked(m_settings.m_adcPreamp);
     ui->attenuator->setCurrentIndex((int) m_settings.m_attenuator);
     blockApplySettings(false);
 }
getCenterFrequency()
qint64 PerseusGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 94 of file perseusgui.cpp.
References PerseusSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getDevSampleRate()
uint32_t PerseusGui::getDevSampleRate (unsigned int index)
Definition at line 382 of file perseusgui.cpp.
References m_rates.
 {
     if (rate_index < m_rates.size())
     {
         return m_rates[rate_index];
     }
     else
     {
         return m_rates[0];
     }
 }
getDevSampleRateIndex()
int PerseusGui::getDevSampleRateIndex (uint32_t sampleRate)
Definition at line 394 of file perseusgui.cpp.
References i, and m_rates.
 {
     for (unsigned int i=0; i < m_rates.size(); i++)
     {
         if (sampeRate == m_rates[i])
         {
             return i;
         }
     }
     return -1;
 }
getInputMessageQueue()
virtual MessageQueue* PerseusGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 51 of file perseusgui.h.
 { return &m_inputMessageQueue; }
getName()
QString PerseusGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 82 of file perseusgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void PerseusGui::handleInputMessages () private slot
Definition at line 151 of file perseusgui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by PerseusGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("PerseusGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             qDebug("PerseusGui::handleInputMessages: message: %s", message->getIdentifier());
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool PerseusGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 124 of file perseusgui.cpp.
References blockApplySettings(), displaySettings(), PerseusInput::MsgConfigurePerseus::getSettings(), PerseusInput::MsgStartStop::getStartStop(), m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     // Returned messages to update the GUI (usually from web interface)
     if (PerseusInput::MsgConfigurePerseus::match(message))
     {
         const PerseusInput::MsgConfigurePerseus& cfg = (PerseusInput::MsgConfigurePerseus&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (PerseusInput::MsgStartStop::match(message))
     {
         PerseusInput::MsgStartStop& notif = (PerseusInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_adcDither_toggled
void PerseusGui::on_adcDither_toggled (bool checked) private slot
Definition at line 332 of file perseusgui.cpp.
References PerseusSettings::m_adcDither, m_settings, and sendSettings().
 {
     m_settings.m_adcDither = checked;
     sendSettings();
 }
on_adcPreamp_toggled
void PerseusGui::on_adcPreamp_toggled (bool checked) private slot
Definition at line 338 of file perseusgui.cpp.
References PerseusSettings::m_adcPreamp, m_settings, and sendSettings().
 {
     m_settings.m_adcPreamp = checked;
     sendSettings();
 }
on_attenuator_currentIndexChanged
void PerseusGui::on_attenuator_currentIndexChanged (int index) private slot
Definition at line 323 of file perseusgui.cpp.
References PerseusSettings::Attenuator_last, PerseusSettings::m_attenuator, m_settings, and sendSettings().
 {
     if ((index < 0) || (index >= (int) PerseusSettings::Attenuator_last)) {
         return;
     }
     m_settings.m_attenuator = (PerseusSettings::Attenuator) index;
     sendSettings();
 }
on_centerFrequency_changed
void PerseusGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 254 of file perseusgui.cpp.
References PerseusSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_decim_currentIndexChanged
void PerseusGui::on_decim_currentIndexChanged (int index) private slot
Definition at line 284 of file perseusgui.cpp.
References PerseusSettings::m_log2Decim, m_settings, and sendSettings().
 {
     if ((index < 0) || (index > 5))
         return;
     m_settings.m_log2Decim = index;
     sendSettings();
 }
on_LOppm_valueChanged
void PerseusGui::on_LOppm_valueChanged (int value) private slot
Definition at line 260 of file perseusgui.cpp.
References arg(), PerseusSettings::m_LOppmTenths, m_settings, sendSettings(), and ui.
 {
     m_settings.m_LOppmTenths = value;
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     sendSettings();
 }
on_record_toggled
void PerseusGui::on_record_toggled (bool checked) private slot
Definition at line 301 of file perseusgui.cpp.
References PerseusInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     PerseusInput::MsgFileRecord* message = PerseusInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_resetLOppm_clicked
void PerseusGui::on_resetLOppm_clicked () private slot
Definition at line 267 of file perseusgui.cpp.
References ui.
 {
     ui->LOppm->setValue(0);
 }
on_sampleRate_currentIndexChanged
void PerseusGui::on_sampleRate_currentIndexChanged (int index) private slot
Definition at line 272 of file perseusgui.cpp.
References PerseusSettings::m_devSampleRateIndex, m_settings, and sendSettings().
 {
     m_settings.m_devSampleRateIndex = index;
     sendSettings();
 }
on_startStop_toggled
void PerseusGui::on_startStop_toggled (bool checked) private slot
Definition at line 292 of file perseusgui.cpp.
References PerseusInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         PerseusInput::MsgStartStop *message = PerseusInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
on_transverter_clicked
void PerseusGui::on_transverter_clicked () private slot
Definition at line 313 of file perseusgui.cpp.
References PerseusSettings::m_centerFrequency, m_settings, PerseusSettings::m_transverterDeltaFrequency, PerseusSettings::m_transverterMode, sendSettings(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("PerseusGui::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     m_settings.m_centerFrequency = ui->centerFrequency->getValueNew()*1000;
     sendSettings();
 }
on_wideband_toggled
void PerseusGui::on_wideband_toggled (bool checked) private slot
Definition at line 278 of file perseusgui.cpp.
References m_settings, PerseusSettings::m_wideBand, and sendSettings().
 {
     m_settings.m_wideBand = checked;
     sendSettings();
 }
openDeviceSettingsDialog
void PerseusGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 407 of file perseusgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), PerseusSettings::m_reverseAPIAddress, PerseusSettings::m_reverseAPIDeviceIndex, PerseusSettings::m_reverseAPIPort, m_settings, PerseusSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by PerseusGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void PerseusGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 87 of file perseusgui.cpp.
References displaySettings(), m_settings, PerseusSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void PerseusGui::sendSettings () private
Definition at line 248 of file perseusgui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_adcDither_toggled(), on_adcPreamp_toggled(), on_attenuator_currentIndexChanged(), on_centerFrequency_changed(), on_decim_currentIndexChanged(), on_LOppm_valueChanged(), on_sampleRate_currentIndexChanged(), on_transverter_clicked(), on_wideband_toggled(), openDeviceSettingsDialog(), PerseusGui(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray PerseusGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 106 of file perseusgui.cpp.
References m_settings, and PerseusSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void PerseusGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 99 of file perseusgui.cpp.
References displaySettings(), PerseusSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void PerseusGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 77 of file perseusgui.cpp.
 {
     setObjectName(name);
 }
updateFrequencyLimits()
void PerseusGui::updateFrequencyLimits () private
Definition at line 232 of file perseusgui.cpp.
References m_settings, PerseusSettings::m_transverterDeltaFrequency, PerseusSettings::m_transverterMode, and ui.
Referenced by displaySettings(), on_transverter_clicked(), and PerseusGui().
 {
     // values in kHz
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     qint64 minLimit = 10 + deltaFrequency;
     qint64 maxLimit = 40000 + deltaFrequency;
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("PerseusGui::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void PerseusGui::updateHardware () private slot
Definition at line 344 of file perseusgui.cpp.
References PerseusInput::MsgConfigurePerseus::create(), DeviceSampleSource::getInputMessageQueue(), m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by PerseusGui().
 {
     qDebug() << "PerseusGui::updateHardware";
     PerseusInput::MsgConfigurePerseus* message = PerseusInput::MsgConfigurePerseus::create(m_settings, m_forceSettings);
     m_sampleSource->getInputMessageQueue()->push(message);
     m_forceSettings = false;
     m_updateTimer.stop();
 }
updateSampleRateAndFrequency()
void PerseusGui::updateSampleRateAndFrequency () private
Definition at line 179 of file perseusgui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg((float)m_sampleRate / 1000));
 }
updateStatus
void PerseusGui::updateStatus () private slot
Definition at line 353 of file perseusgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by PerseusGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 PerseusGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 68 of file perseusgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* PerseusGui::m_deviceUISet private
Definition at line 59 of file perseusgui.h.
Referenced by PerseusGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool PerseusGui::m_doApplySettings private
Definition at line 60 of file perseusgui.h.
Referenced by on_startStop_toggled().
m_forceSettings
bool PerseusGui::m_forceSettings private
Definition at line 61 of file perseusgui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue PerseusGui::m_inputMessageQueue private
Definition at line 70 of file perseusgui.h.
Referenced by handleInputMessages(), and PerseusGui().
m_lastEngineState
int PerseusGui::m_lastEngineState private
Definition at line 69 of file perseusgui.h.
Referenced by updateStatus().
m_rates
std::vector<uint32_t> PerseusGui::m_rates private
Definition at line 65 of file perseusgui.h.
Referenced by displaySampleRates(), getDevSampleRate(), getDevSampleRateIndex(), and PerseusGui().
m_sampleRate
int PerseusGui::m_sampleRate private
Definition at line 67 of file perseusgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleSource
PerseusInput* PerseusGui::m_sampleSource private
Definition at line 66 of file perseusgui.h.
Referenced by on_record_toggled(), on_startStop_toggled(), PerseusGui(), and updateHardware().
m_settings
PerseusSettings PerseusGui::m_settings private
Definition at line 62 of file perseusgui.h.
Referenced by deserialize(), displaySampleRates(), displaySettings(), getCenterFrequency(), handleMessage(), on_adcDither_toggled(), on_adcPreamp_toggled(), on_attenuator_currentIndexChanged(), on_centerFrequency_changed(), on_decim_currentIndexChanged(), on_LOppm_valueChanged(), on_sampleRate_currentIndexChanged(), on_transverter_clicked(), on_wideband_toggled(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), updateFrequencyLimits(), and updateHardware().
m_statusTimer
QTimer PerseusGui::m_statusTimer private
Definition at line 64 of file perseusgui.h.
Referenced by PerseusGui().
m_updateTimer
QTimer PerseusGui::m_updateTimer private
Definition at line 63 of file perseusgui.h.
Referenced by PerseusGui(), sendSettings(), and updateHardware().
ui
Ui::PerseusGui* PerseusGui::ui private
Definition at line 57 of file perseusgui.h.
Referenced by displaySampleRates(), displaySettings(), handleMessage(), on_LOppm_valueChanged(), on_record_toggled(), on_resetLOppm_clicked(), on_transverter_clicked(), PerseusGui(), updateFrequencyLimits(), updateSampleRateAndFrequency(), updateStatus(), and ~PerseusGui().
The documentation for this class was generated from the following files:
plugins/samplesource/perseus/perseusgui.h
plugins/samplesource/perseus/perseusgui.cpp