SDRAngel: UDPSource Class Reference
UDPSource Class Reference
#include <udpsource.h>
Classes
class MsgConfigureChannelizer
class MsgConfigureUDPSource
class MsgResetReadIndex
class MsgUDPSourceSpectrum
Signals
void levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples)
Public Member Functions
UDPSource (DeviceAPI *deviceAPI)
virtual ~UDPSource ()
virtual void destroy ()
void setSpectrumSink (BasebandSampleSink *spectrum)
virtual void start ()
virtual void stop ()
virtual void pull (Sample &sample)
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
double getMagSq () const
double getInMagSq () const
int32_t getBufferGauge () const
bool getSquelchOpen () const
void setSpectrum (bool enabled)
void resetReadIndex ()
Public Member Functions inherited from BasebandSampleSource
BasebandSampleSource ()
virtual ~BasebandSampleSource ()
virtual void pullAudio (int nbSamples)
void feed (SampleSourceFifo *sampleFifo, int nbSamples)
SampleSourceFifo & getSampleSourceFifo ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
void setDeviceSampleSourceFifo (SampleSourceFifo *deviceSampleFifo)
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channeltx.udpsource"
static const QString m_channelId = "UDPSource"
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applyChannelSettings (int basebandSampleRate, int outputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const UDPSourceSettings &settings, bool force=false)
void modulateSample ()
void calculateLevel (Real sample)
void calculateLevel (Complex sample)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const UDPSourceSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const UDPSourceSettings &settings, bool force)
void calculateSquelch (double value)
void initSquelch (bool open)
void readMonoSample (qint16 &t)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSource * m_threadedChannelizer
UpChannelizer * m_channelizer
int m_basebandSampleRate
Real m_outputSampleRate
int m_inputFrequencyOffset
UDPSourceSettings m_settings
Real m_squelch
NCO m_carrierNco
Complex m_modSample
BasebandSampleSink * m_spectrum
bool m_spectrumEnabled
SampleVector m_sampleBuffer
int m_spectrumChunkSize
int m_spectrumChunkCounter
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
bool m_interpolatorConsumed
double m_magsq
double m_inMagsq
MovingAverage< double > m_movingAverage
MovingAverage< double > m_inMovingAverage
UDPSourceUDPHandler m_udpHandler
Real m_actualInputSampleRate
sample rate with UDP buffer skew compensation
double m_sampleRateSum
int m_sampleRateAvgCounter
int m_levelCalcCount
Real m_peakLevel
double m_levelSum
int m_levelNbSamples
bool m_squelchOpen
int m_squelchOpenCount
int m_squelchCloseCount
int m_squelchThreshold
float m_modPhasor
Phasor for FM modulation.
fftfilt * m_SSBFilter
Complex filter for SSB modulation.
Complex * m_SSBFilterBuffer
int m_SSBFilterBufferIndex
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
QMutex m_settingsMutex
Static Private Attributes
static const int m_sampleRateAverageItems = 17
static const int m_ssbFftLen = 1024
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSource
void handleInputMessages ()
void handleWriteToFifo (int nbSamples)
void handleWriteToDeviceFifo (int nbSamples)
Protected Member Functions inherited from BasebandSampleSource
void handleWriteToFifo (SampleSourceFifo *sampleFifo, int nbSamples)
Protected Attributes inherited from BasebandSampleSource
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
SampleSourceFifo m_sampleFifo
Internal FIFO for multi-channel processing.
SampleSourceFifo * m_deviceSampleFifo
Reference to the device FIFO for single channel processing.
Detailed Description
Definition at line 42 of file udpsource.h.
Constructor & Destructor Documentation
UDPSource()
UDPSource::UDPSource (DeviceAPI * deviceAPI)
Definition at line 44 of file udpsource.cpp.
References DeviceAPI::addChannelSource(), DeviceAPI::addChannelSourceAPI(), applyChannelSettings(), applySettings(), m_basebandSampleRate, m_channelId, m_channelizer, m_deviceAPI, m_inputFrequencyOffset, BasebandSampleSource::m_inputMessageQueue, UDPSourceSettings::m_inputSampleRate, UDPSourceSettings::m_lowCutoff, m_networkManager, m_outputSampleRate, UDPSourceSettings::m_rfBandwidth, m_settings, m_ssbFftLen, m_SSBFilter, m_SSBFilterBuffer, m_threadedChannelizer, m_udpHandler, networkManagerFinished(), and UDPSourceUDPHandler::setFeedbackMessageQueue().
Referenced by UDPSource::MsgConfigureChannelizer::MsgConfigureChannelizer().
                                          :
     ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSource),
     m_deviceAPI(deviceAPI),
     m_basebandSampleRate(48000),
     m_outputSampleRate(48000),
     m_inputFrequencyOffset(0),
     m_squelch(1e-6),
     m_spectrum(0),
     m_spectrumEnabled(false),
     m_spectrumChunkSize(2160),
     m_spectrumChunkCounter(0),
     m_magsq(1e-10),
     m_movingAverage(16, 1e-10),
     m_inMovingAverage(480, 1e-10),
     m_sampleRateSum(0),
     m_sampleRateAvgCounter(0),
     m_levelCalcCount(0),
     m_peakLevel(0.0f),
     m_levelSum(0.0f),
     m_levelNbSamples(480),
     m_squelchOpen(false),
     m_squelchOpenCount(0),
     m_squelchCloseCount(0),
     m_squelchThreshold(4800),
     m_modPhasor(0.0f),
     m_SSBFilterBufferIndex(0),
     m_settingsMutex(QMutex::Recursive)
 {
     setObjectName(m_channelId);
     m_udpHandler.setFeedbackMessageQueue(&m_inputMessageQueue);
     m_SSBFilter = new fftfilt(m_settings.m_lowCutoff / m_settings.m_inputSampleRate, m_settings.m_rfBandwidth / m_settings.m_inputSampleRate, m_ssbFftLen);
     m_SSBFilterBuffer = new Complex[m_ssbFftLen>>1]; // filter returns data exactly half of its size
     applyChannelSettings(m_basebandSampleRate, m_outputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new UpChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSource(m_channelizer, this);
     m_deviceAPI->addChannelSource(m_threadedChannelizer);
     m_deviceAPI->addChannelSourceAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~UDPSource()
UDPSource::~UDPSource () virtual
Definition at line 90 of file udpsource.cpp.
References m_channelizer, m_deviceAPI, m_networkManager, m_SSBFilter, m_SSBFilterBuffer, m_threadedChannelizer, networkManagerFinished(), DeviceAPI::removeChannelSource(), and DeviceAPI::removeChannelSourceAPI().
Referenced by UDPSource::MsgConfigureChannelizer::MsgConfigureChannelizer().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     m_deviceAPI->removeChannelSourceAPI(this);
     m_deviceAPI->removeChannelSource(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete m_SSBFilter;
     delete[] m_SSBFilterBuffer;
 }
Member Function Documentation
applyChannelSettings()
void UDPSource::applyChannelSettings (int basebandSampleRate, int outputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 462 of file udpsource.cpp.
References Interpolator::create(), UDPSourceSettings::m_autoRWBalance, m_basebandSampleRate, m_carrierNco, m_inputFrequencyOffset, UDPSourceSettings::m_inputSampleRate, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, m_outputSampleRate, UDPSourceSettings::m_rfBandwidth, m_settings, m_settingsMutex, and NCO::setFreq().
Referenced by handleMessage(), start(), and UDPSource().
 {
     qDebug() << "UDPSource::applyChannelSettings:"
             << " basebandSampleRate: " << basebandSampleRate
             << " outputSampleRate: " << outputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if ((inputFrequencyOffset != m_inputFrequencyOffset) ||
         (outputSampleRate != m_outputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_carrierNco.setFreq(inputFrequencyOffset, outputSampleRate);
         m_settingsMutex.unlock();
     }
     if (((outputSampleRate != m_outputSampleRate) && (!m_settings.m_autoRWBalance)) || force)
     {
         m_settingsMutex.lock();
         m_interpolatorDistanceRemain = 0;
         m_interpolatorConsumed = false;
         m_interpolatorDistance = (Real) m_settings.m_inputSampleRate / (Real) outputSampleRate;
         m_interpolator.create(48, m_settings.m_inputSampleRate, m_settings.m_rfBandwidth / 2.2, 3.0);
         m_settingsMutex.unlock();
     }
     m_basebandSampleRate = basebandSampleRate;
     m_outputSampleRate = outputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applySettings()
void UDPSource::applySettings (const UDPSourceSettings & settings, bool force = false) private
Definition at line 492 of file udpsource.cpp.
References UDPSourceUDPHandler::configureUDPLink(), Interpolator::create(), fftfilt::create_filter(), initSquelch(), m_actualInputSampleRate, UDPSourceSettings::m_amModFactor, UDPSourceSettings::m_autoRWBalance, UDPSourceSettings::m_channelMute, UDPSourceSettings::m_fmDeviation, UDPSourceSettings::m_gainIn, UDPSourceSettings::m_gainOut, m_inMovingAverage, UDPSourceSettings::m_inputFrequencyOffset, UDPSourceSettings::m_inputSampleRate, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, m_levelCalcCount, m_levelNbSamples, m_levelSum, UDPSourceSettings::m_lowCutoff, m_outputSampleRate, m_peakLevel, UDPSourceSettings::m_reverseAPIAddress, UDPSourceSettings::m_reverseAPIChannelIndex, UDPSourceSettings::m_reverseAPIDeviceIndex, UDPSourceSettings::m_reverseAPIPort, UDPSourceSettings::m_rfBandwidth, UDPSourceSettings::m_sampleFormat, m_sampleRateAvgCounter, m_sampleRateSum, m_settings, m_settingsMutex, m_spectrumChunkCounter, m_spectrumChunkSize, UDPSourceSettings::m_squelch, m_squelch, UDPSourceSettings::m_squelchEnabled, UDPSourceSettings::m_squelchGate, m_squelchOpen, m_squelchThreshold, m_SSBFilter, UDPSourceSettings::m_stereoInput, UDPSourceSettings::m_udpAddress, m_udpHandler, UDPSourceSettings::m_udpPort, UDPSourceSettings::m_useReverseAPI, CalcDb::powerFromdB(), UDPSourceUDPHandler::resetReadIndex(), MovingAverage< Type >::resize(), UDPSourceUDPHandler::resizeBuffer(), UDPSourceUDPHandler::setAutoRWBalance(), and webapiReverseSendSettings().
Referenced by handleMessage(), and UDPSource().
 {
     qDebug() << "UDPSource::applySettings:"
             << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
             << " m_sampleFormat: " << settings.m_sampleFormat
             << " m_inputSampleRate: " << settings.m_inputSampleRate
             << " m_rfBandwidth: " << settings.m_rfBandwidth
             << " m_lowCutoff: " << settings.m_lowCutoff
             << " m_fmDeviation: " << settings.m_fmDeviation
             << " m_amModFactor: " << settings.m_amModFactor
             << " m_udpAddressStr: " << settings.m_udpAddress
             << " m_udpPort: " << settings.m_udpPort
             << " m_channelMute: " << settings.m_channelMute
             << " m_gainIn: " << settings.m_gainIn
             << " m_gainOut: " << settings.m_gainOut
             << " m_squelchGate: " << settings.m_squelchGate
             << " m_squelch: " << settings.m_squelch << "dB"
             << " m_squelchEnabled: " << settings.m_squelchEnabled
             << " m_autoRWBalance: " << settings.m_autoRWBalance
             << " m_stereoInput: " << settings.m_stereoInput
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if ((settings.m_inputFrequencyOffset != m_settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if ((settings.m_sampleFormat != m_settings.m_sampleFormat) || force) {
         reverseAPIKeys.append("sampleFormat");
     }
     if ((settings.m_inputSampleRate != m_settings.m_inputSampleRate) || force) {
         reverseAPIKeys.append("inputSampleRate");
     }
     if ((settings.m_rfBandwidth != m_settings.m_rfBandwidth) || force) {
         reverseAPIKeys.append("rfBandwidth");
     }
     if ((settings.m_lowCutoff != m_settings.m_lowCutoff) || force) {
         reverseAPIKeys.append("lowCutoff");
     }
     if ((settings.m_fmDeviation != m_settings.m_fmDeviation) || force) {
         reverseAPIKeys.append("fmDeviation");
     }
     if ((settings.m_amModFactor != m_settings.m_amModFactor) || force) {
         reverseAPIKeys.append("amModFactor");
     }
     if ((settings.m_udpAddress != m_settings.m_udpAddress) || force) {
         reverseAPIKeys.append("udpAddress");
     }
     if ((settings.m_udpPort != m_settings.m_udpPort) || force) {
         reverseAPIKeys.append("udpPort");
     }
     if ((settings.m_channelMute != m_settings.m_channelMute) || force) {
         reverseAPIKeys.append("channelMute");
     }
     if ((settings.m_gainIn != m_settings.m_gainIn) || force) {
         reverseAPIKeys.append("gainIn");
     }
     if ((settings.m_gainOut != m_settings.m_gainOut) || force) {
         reverseAPIKeys.append("gainOut");
     }
     if ((settings.m_squelchGate != m_settings.m_squelchGate) || force) {
         reverseAPIKeys.append("squelchGate");
     }
     if ((settings.m_squelch != m_settings.m_squelch) || force) {
         reverseAPIKeys.append("squelch");
     }
     if ((settings.m_squelchEnabled != m_settings.m_squelchEnabled) || force) {
         reverseAPIKeys.append("squelchEnabled");
     }
     if ((settings.m_autoRWBalance != m_settings.m_autoRWBalance) || force) {
         reverseAPIKeys.append("autoRWBalance");
     }
     if ((settings.m_stereoInput != m_settings.m_stereoInput) || force) {
         reverseAPIKeys.append("stereoInput");
     }
     if((settings.m_rfBandwidth != m_settings.m_rfBandwidth) ||
        (settings.m_lowCutoff != m_settings.m_lowCutoff) ||
        (settings.m_inputSampleRate != m_settings.m_inputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_interpolatorDistanceRemain = 0;
         m_interpolatorConsumed = false;
         m_interpolatorDistance = (Real) settings.m_inputSampleRate / (Real) m_outputSampleRate;
         m_interpolator.create(48, settings.m_inputSampleRate, settings.m_rfBandwidth / 2.2, 3.0);
         m_actualInputSampleRate = settings.m_inputSampleRate;
         m_udpHandler.resetReadIndex();
         m_sampleRateSum = 0.0;
         m_sampleRateAvgCounter = 0;
         m_spectrumChunkSize = settings.m_inputSampleRate * 0.05; // 50 ms chunk
         m_spectrumChunkCounter = 0;
         m_levelNbSamples = settings.m_inputSampleRate * 0.01; // every 10 ms
         m_levelCalcCount = 0;
         m_peakLevel = 0.0f;
         m_levelSum = 0.0f;
         m_udpHandler.resizeBuffer(settings.m_inputSampleRate);
         m_inMovingAverage.resize(settings.m_inputSampleRate * 0.01, 1e-10); // 10 ms
         m_squelchThreshold = settings.m_inputSampleRate * settings.m_squelchGate;
         initSquelch(m_squelchOpen);
         m_SSBFilter->create_filter(settings.m_lowCutoff / settings.m_inputSampleRate, settings.m_rfBandwidth / settings.m_inputSampleRate);
         m_settingsMutex.unlock();
     }
     if ((settings.m_squelch != m_settings.m_squelch) || force)
     {
         m_squelch = CalcDb::powerFromdB(settings.m_squelch);
     }
     if ((settings.m_squelchGate != m_settings.m_squelchGate) || force)
     {
         m_squelchThreshold = m_outputSampleRate * settings.m_squelchGate;
         initSquelch(m_squelchOpen);
     }
     if ((settings.m_udpAddress != m_settings.m_udpAddress) ||
         (settings.m_udpPort != m_settings.m_udpPort) || force)
     {
         m_settingsMutex.lock();
         m_udpHandler.configureUDPLink(settings.m_udpAddress, settings.m_udpPort);
         m_settingsMutex.unlock();
     }
     if ((settings.m_channelMute != m_settings.m_channelMute) || force)
     {
         if (!settings.m_channelMute) {
             m_udpHandler.resetReadIndex();
         }
     }
     if ((settings.m_autoRWBalance != m_settings.m_autoRWBalance) || force)
     {
         m_settingsMutex.lock();
         m_udpHandler.setAutoRWBalance(settings.m_autoRWBalance);
         if (!settings.m_autoRWBalance)
         {
             m_interpolatorDistanceRemain = 0;
             m_interpolatorConsumed = false;
             m_interpolatorDistance = (Real) settings.m_inputSampleRate / (Real) m_outputSampleRate;
             m_interpolator.create(48, settings.m_inputSampleRate, settings.m_rfBandwidth / 2.2, 3.0);
             m_actualInputSampleRate = settings.m_inputSampleRate;
             m_udpHandler.resetReadIndex();
         }
         m_settingsMutex.unlock();
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
calculateLevel() [1/2]
void UDPSource::calculateLevel (Real sample) private
Definition at line 291 of file udpsource.cpp.
References levelChanged(), m_levelCalcCount, m_levelNbSamples, m_levelSum, m_peakLevel, leansdr::max(), and sqrt().
Referenced by modulateSample().
 {
     if (m_levelCalcCount < m_levelNbSamples)
     {
         m_peakLevel = std::max(std::fabs(m_peakLevel), sample);
         m_levelSum += sample * sample;
         m_levelCalcCount++;
     }
     else
     {
         qreal rmsLevel = m_levelSum > 0.0 ? sqrt(m_levelSum / m_levelNbSamples) : 0.0;
         //qDebug("NFMMod::calculateLevel: %f %f", rmsLevel, m_peakLevel);
         emit levelChanged(rmsLevel, m_peakLevel, m_levelNbSamples);
         m_peakLevel = 0.0f;
         m_levelSum = 0.0f;
         m_levelCalcCount = 0;
     }
 }
calculateLevel() [2/2]
void UDPSource::calculateLevel (Complex sample) private
Definition at line 310 of file udpsource.cpp.
References abs(), levelChanged(), m_levelCalcCount, m_levelNbSamples, m_levelSum, m_peakLevel, leansdr::max(), SDR_TX_SCALED, SDR_TX_SCALEF, and sqrt().
 {
     Real t = std::abs(sample);
     if (m_levelCalcCount < m_levelNbSamples)
     {
         m_peakLevel = std::max(std::fabs(m_peakLevel), t);
         m_levelSum += (t * t);
         m_levelCalcCount++;
     }
     else
     {
         qreal rmsLevel = m_levelSum > 0.0 ? sqrt((m_levelSum/(SDR_TX_SCALED*SDR_TX_SCALED)) / m_levelNbSamples) : 0.0;
         emit levelChanged(rmsLevel, m_peakLevel / SDR_TX_SCALEF, m_levelNbSamples);
         m_peakLevel = 0.0f;
         m_levelSum = 0.0f;
         m_levelCalcCount = 0;
     }
 }
calculateSquelch()
void UDPSource::calculateSquelch (double value) inline private
Definition at line 264 of file udpsource.h.
References UDPSourceSettings::m_squelchEnabled, and m_squelchThreshold.
Referenced by modulateSample().
     {
         if ((!m_settings.m_squelchEnabled) || (value > m_squelch))
         {
             if (m_squelchThreshold == 0)
             {
                 m_squelchOpen = true;
             }
             else
             {
                 if (m_squelchOpenCount < m_squelchThreshold)
                 {
                     m_squelchOpenCount++;
                 }
                 else
                 {
                     m_squelchCloseCount = m_squelchThreshold;
                     m_squelchOpen = true;
                 }
             }
         }
         else
         {
             if (m_squelchThreshold == 0)
             {
                 m_squelchOpen = false;
             }
             else
             {
                 if (m_squelchCloseCount > 0)
                 {
                     m_squelchCloseCount--;
                 }
                 else
                 {
                     m_squelchOpenCount = 0;
                     m_squelchOpen = false;
                 }
             }
         }
     }
deserialize()
bool UDPSource::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 657 of file udpsource.cpp.
References UDPSource::MsgConfigureUDPSource::create(), UDPSourceSettings::deserialize(), BasebandSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and UDPSourceSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureUDPSource *msg = MsgConfigureUDPSource::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureUDPSource *msg = MsgConfigureUDPSource::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void UDPSource::destroy () inline virtual
Implements ChannelAPI.
Definition at line 95 of file udpsource.h.
 { delete this; }
getBufferGauge()
int32_t UDPSource::getBufferGauge () const inline
Definition at line 137 of file udpsource.h.
References UDPSourceUDPHandler::getBufferGauge(), and m_udpHandler.
Referenced by UDPSourceGUI::tick(), and webapiFormatChannelReport().
 { return m_udpHandler.getBufferGauge(); }
getCenterFrequency()
virtual qint64 UDPSource::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 106 of file udpsource.h.
References deserialize(), UDPSourceSettings::m_inputFrequencyOffset, UDPSource::MsgConfigureUDPSource::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getIdentifier()
virtual void UDPSource::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 104 of file udpsource.h.
 { id = objectName(); }
getInMagSq()
double UDPSource::getInMagSq () const inline
Definition at line 136 of file udpsource.h.
References m_inMagsq.
Referenced by UDPSourceGUI::tick(), and webapiFormatChannelReport().
 { return m_inMagsq; }
getMagSq()
double UDPSource::getMagSq () const inline
Definition at line 135 of file udpsource.h.
References m_magsq.
Referenced by UDPSourceGUI::tick(), and webapiFormatChannelReport().
 { return m_magsq; }
getNbSinkStreams()
virtual int UDPSource::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 111 of file udpsource.h.
 { return 1; }
getNbSourceStreams()
virtual int UDPSource::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 112 of file udpsource.h.
 { return 0; }
getSquelchOpen()
bool UDPSource::getSquelchOpen () const inline
Definition at line 138 of file udpsource.h.
References m_squelchOpen, resetReadIndex(), and setSpectrum().
Referenced by UDPSourceGUI::tick().
 { return m_squelchOpen; }
getStreamCenterFrequency()
virtual qint64 UDPSource::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 114 of file udpsource.h.
References UDPSourceSettings::m_inputFrequencyOffset, UDPSource::MsgConfigureUDPSource::m_settings, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void UDPSource::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 105 of file udpsource.h.
References UDPSource::MsgConfigureUDPSource::m_settings, and UDPSourceSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool UDPSource::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSource.
Definition at line 330 of file udpsource.cpp.
References applyChannelSettings(), applySettings(), UpChannelizer::configure(), UpChannelizer::MsgChannelizerNotification::getBasebandSampleRate(), UDPSource::MsgConfigureChannelizer::getCenterFrequency(), UDPSourceMessages::MsgSampleRateCorrection::getCorrectionFactor(), UDPSource::MsgUDPSourceSpectrum::getEnabled(), UDPSource::MsgConfigureUDPSource::getForce(), UpChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSource::getInputMessageQueue(), UDPSourceMessages::MsgSampleRateCorrection::getRawDeltaRatio(), UpChannelizer::MsgChannelizerNotification::getSampleRate(), UDPSource::MsgConfigureChannelizer::getSampleRate(), UDPSource::MsgConfigureUDPSource::getSettings(), BasebandSampleSink::handleMessage(), m_actualInputSampleRate, m_channelizer, UDPSourceSettings::m_inputSampleRate, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, m_outputSampleRate, m_sampleRateAverageItems, m_sampleRateAvgCounter, m_sampleRateSum, m_settings, m_settingsMutex, m_spectrum, m_spectrumEnabled, m_udpHandler, Message::match(), and UDPSourceUDPHandler::resetReadIndex().
Referenced by setSpectrumSink().
 {
     if (UpChannelizer::MsgChannelizerNotification::match(cmd))
     {
         UpChannelizer::MsgChannelizerNotification& notif = (UpChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "UDPSource::handleMessage: MsgChannelizerNotification";
         applyChannelSettings(notif.getBasebandSampleRate(), notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "UDPSource::handleMessage: MsgConfigureChannelizer:"
                 << " sampleRate: " << cfg.getSampleRate()
                 << " centerFrequency: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureUDPSource::match(cmd))
     {
         MsgConfigureUDPSource& cfg = (MsgConfigureUDPSource&) cmd;
         qDebug() << "UDPSource::handleMessage: MsgConfigureUDPSource";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (UDPSourceMessages::MsgSampleRateCorrection::match(cmd))
     {
         UDPSourceMessages::MsgSampleRateCorrection& cfg = (UDPSourceMessages::MsgSampleRateCorrection&) cmd;
         Real newSampleRate = m_actualInputSampleRate + cfg.getCorrectionFactor() * m_actualInputSampleRate;
         // exclude values too way out nominal sample rate (20%)
         if ((newSampleRate < m_settings.m_inputSampleRate * 1.2) && (newSampleRate >  m_settings.m_inputSampleRate * 0.8))
         {
             m_actualInputSampleRate = newSampleRate;
             if ((cfg.getRawDeltaRatio() > -0.05) && (cfg.getRawDeltaRatio() < 0.05))
             {
                 if (m_sampleRateAvgCounter < m_sampleRateAverageItems)
                 {
                     m_sampleRateSum += m_actualInputSampleRate;
                     m_sampleRateAvgCounter++;
                 }
             }
             else
             {
                 m_sampleRateSum = 0.0;
                 m_sampleRateAvgCounter = 0;
             }
             if (m_sampleRateAvgCounter == m_sampleRateAverageItems)
             {
                 float avgRate = m_sampleRateSum / m_sampleRateAverageItems;
                 qDebug("UDPSource::handleMessage: MsgSampleRateCorrection: corr: %+.6f new rate: %.0f: avg rate: %.0f",
                         cfg.getCorrectionFactor(),
                         m_actualInputSampleRate,
                         avgRate);
                 m_actualInputSampleRate = avgRate;
                 m_sampleRateSum = 0.0;
                 m_sampleRateAvgCounter = 0;
             }
 //            else
 //            {
 //                qDebug("UDPSource::handleMessage: MsgSampleRateCorrection: corr: %+.6f new rate: %.0f",
 //                        cfg.getCorrectionFactor(),
 //                        m_actualInputSampleRate);
 //            }
             m_settingsMutex.lock();
             m_interpolatorDistanceRemain = 0;
             m_interpolatorConsumed = false;
             m_interpolatorDistance = (Real) m_actualInputSampleRate / (Real) m_outputSampleRate;
             //m_interpolator.create(48, m_actualInputSampleRate, m_settings.m_rfBandwidth / 2.2, 3.0); // causes clicking: leaving at standard frequency
             m_settingsMutex.unlock();
         }
         return true;
     }
     else if (MsgUDPSourceSpectrum::match(cmd))
     {
         MsgUDPSourceSpectrum& spc = (MsgUDPSourceSpectrum&) cmd;
         m_spectrumEnabled = spc.getEnabled();
         qDebug() << "UDPSource::handleMessage: MsgUDPSourceSpectrum: m_spectrumEnabled: " << m_spectrumEnabled;
         return true;
     }
     else if (MsgResetReadIndex::match(cmd))
     {
         m_settingsMutex.lock();
         m_udpHandler.resetReadIndex();
         m_settingsMutex.unlock();
         qDebug() << "UDPSource::handleMessage: MsgResetReadIndex";
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         if(m_spectrum != 0)
         {
            return m_spectrum->handleMessage(cmd);
         }
         else
         {
             return false;
         }
     }
 }
initSquelch()
void UDPSource::initSquelch (bool open) inline private
Definition at line 306 of file udpsource.h.
References m_squelchThreshold.
Referenced by applySettings(), modulateSample(), and pull().
     {
         if (open)
         {
             m_squelchOpen = true;
             m_squelchOpenCount = m_squelchThreshold;
             m_squelchCloseCount = m_squelchThreshold;
         }
         else
         {
             m_squelchOpen = false;
             m_squelchOpenCount = 0;
             m_squelchCloseCount = 0;
         }
     }
levelChanged
void UDPSource::levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples) signal
Level changed
Parameters
rmsLevel RMS level in range 0.0 - 1.0
peakLevel Peak level in range 0.0 - 1.0
numSamples Number of audio samples analyzed
Referenced by calculateLevel().
modulateSample()
void UDPSource::modulateSample () private
Definition at line 159 of file udpsource.cpp.
References MovingAverage< Type >::average(), calculateLevel(), calculateSquelch(), cos(), MovingAverage< Type >::feed(), BasebandSampleSink::feed(), UDPSourceSettings::FormatAM, UDPSourceSettings::FormatLSB, UDPSourceSettings::FormatNFM, UDPSourceSettings::FormatSnLE, UDPSourceSettings::FormatUSB, initSquelch(), UDPSourceSettings::m_amModFactor, UDPSourceSettings::m_fmDeviation, UDPSourceSettings::m_gainOut, Sample::m_imag, m_inMagsq, m_inMovingAverage, UDPSourceSettings::m_inputSampleRate, m_modPhasor, m_modSample, M_PI, Sample::m_real, m_sampleBuffer, UDPSourceSettings::m_sampleFormat, m_settings, m_spectrum, m_spectrumChunkCounter, m_spectrumChunkSize, m_spectrumEnabled, m_squelchOpen, m_SSBFilter, m_SSBFilterBuffer, m_SSBFilterBufferIndex, m_udpHandler, readMonoSample(), UDPSourceUDPHandler::readSample(), fftfilt::runSSB(), SDR_TX_SCALED, SDR_TX_SCALEF, and sin().
Referenced by pull().
 {
     if (m_settings.m_sampleFormat == UDPSourceSettings::FormatSnLE) // Linear I/Q transponding
     {
         Sample s;
         m_udpHandler.readSample(s);
         uint64_t magsq = s.m_real * s.m_real + s.m_imag * s.m_imag;
         m_inMovingAverage.feed(magsq/(SDR_TX_SCALED*SDR_TX_SCALED));
         m_inMagsq = m_inMovingAverage.average();
         calculateSquelch(m_inMagsq);
         if (m_squelchOpen)
         {
             m_modSample.real(s.m_real * m_settings.m_gainOut);
             m_modSample.imag(s.m_imag * m_settings.m_gainOut);
             calculateLevel(m_modSample);
         }
         else
         {
             m_modSample.real(0.0f);
             m_modSample.imag(0.0f);
         }
     }
     else if (m_settings.m_sampleFormat == UDPSourceSettings::FormatNFM)
     {
         qint16 t;
         readMonoSample(t);
         m_inMovingAverage.feed((t*t)/1073741824.0);
         m_inMagsq = m_inMovingAverage.average();
         calculateSquelch(m_inMagsq);
         if (m_squelchOpen)
         {
             m_modPhasor += (m_settings.m_fmDeviation / m_settings.m_inputSampleRate) * (t / SDR_TX_SCALEF) * M_PI * 2.0f;
             m_modSample.real(cos(m_modPhasor) * 0.3162292f * SDR_TX_SCALEF * m_settings.m_gainOut);
             m_modSample.imag(sin(m_modPhasor) * 0.3162292f * SDR_TX_SCALEF * m_settings.m_gainOut);
             calculateLevel(m_modSample);
         }
         else
         {
             m_modSample.real(0.0f);
             m_modSample.imag(0.0f);
         }
     }
     else if (m_settings.m_sampleFormat == UDPSourceSettings::FormatAM)
     {
         qint16 t;
         readMonoSample(t);
         m_inMovingAverage.feed((t*t)/(SDR_TX_SCALED*SDR_TX_SCALED));
         m_inMagsq = m_inMovingAverage.average();
         calculateSquelch(m_inMagsq);
         if (m_squelchOpen)
         {
             m_modSample.real(((t / SDR_TX_SCALEF)*m_settings.m_amModFactor*m_settings.m_gainOut + 1.0f) * (SDR_TX_SCALEF/2)); // modulate and scale zero frequency carrier
             m_modSample.imag(0.0f);
             calculateLevel(m_modSample);
         }
         else
         {
             m_modSample.real(0.0f);
             m_modSample.imag(0.0f);
         }
     }
     else if ((m_settings.m_sampleFormat == UDPSourceSettings::FormatLSB) || (m_settings.m_sampleFormat == UDPSourceSettings::FormatUSB))
     {
         qint16 t;
         Complex c, ci;
         fftfilt::cmplx *filtered;
         int n_out = 0;
         readMonoSample(t);
         m_inMovingAverage.feed((t*t)/(SDR_TX_SCALED*SDR_TX_SCALED));
         m_inMagsq = m_inMovingAverage.average();
         calculateSquelch(m_inMagsq);
         if (m_squelchOpen)
         {
             ci.real((t / SDR_TX_SCALEF) * m_settings.m_gainOut);
             ci.imag(0.0f);
             n_out = m_SSBFilter->runSSB(ci, &filtered, (m_settings.m_sampleFormat == UDPSourceSettings::FormatUSB));
             if (n_out > 0)
             {
                 memcpy((void *) m_SSBFilterBuffer, (const void *) filtered, n_out*sizeof(Complex));
                 m_SSBFilterBufferIndex = 0;
             }
             c = m_SSBFilterBuffer[m_SSBFilterBufferIndex];
             m_modSample.real(m_SSBFilterBuffer[m_SSBFilterBufferIndex].real() * SDR_TX_SCALEF);
             m_modSample.imag(m_SSBFilterBuffer[m_SSBFilterBufferIndex].imag() * SDR_TX_SCALEF);
             m_SSBFilterBufferIndex++;
             calculateLevel(m_modSample);
         }
         else
         {
             m_modSample.real(0.0f);
             m_modSample.imag(0.0f);
         }
     }
     else
     {
         m_modSample.real(0.0f);
         m_modSample.imag(0.0f);
         initSquelch(false);
     }
     if (m_spectrum && m_spectrumEnabled && (m_spectrumChunkCounter < m_spectrumChunkSize - 1))
     {
         Sample s;
         s.m_real = (FixReal) m_modSample.real();
         s.m_imag = (FixReal) m_modSample.imag();
         m_sampleBuffer.push_back(s);
         m_spectrumChunkCounter++;
     }
     else if (m_spectrum)
     {
         m_spectrum->feed(m_sampleBuffer.begin(), m_sampleBuffer.end(), false);
         m_sampleBuffer.clear();
         m_spectrumChunkCounter = 0;
     }
 }
networkManagerFinished
void UDPSource::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 947 of file udpsource.cpp.
Referenced by UDPSource(), and ~UDPSource().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "UDPSource::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("UDPSource::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
pull()
void UDPSource::pull (Sample & sample) virtual
Implements BasebandSampleSource.
Definition at line 113 of file udpsource.cpp.
References MovingAverage< Type >::average(), Interpolator::decimate(), MovingAverage< Type >::feed(), initSquelch(), Interpolator::interpolate(), m_carrierNco, UDPSourceSettings::m_channelMute, Sample::m_imag, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_magsq, m_modSample, m_movingAverage, Sample::m_real, m_settings, m_settingsMutex, modulateSample(), NCO::nextIQ(), and SDR_TX_SCALED.
Referenced by setSpectrumSink().
 {
     if (m_settings.m_channelMute)
     {
         sample.m_real = 0.0f;
         sample.m_imag = 0.0f;
         initSquelch(false);
         return;
     }
     Complex ci;
     m_settingsMutex.lock();
     if (m_interpolatorDistance > 1.0f) // decimate
     {
         modulateSample();
         while (!m_interpolator.decimate(&m_interpolatorDistanceRemain, m_modSample, &ci))
         {
             modulateSample();
         }
     }
     else
     {
         if (m_interpolator.interpolate(&m_interpolatorDistanceRemain, m_modSample, &ci))
         {
             modulateSample();
         }
     }
     m_interpolatorDistanceRemain += m_interpolatorDistance;
     ci *= m_carrierNco.nextIQ(); // shift to carrier frequency
     m_settingsMutex.unlock();
     double magsq = ci.real() * ci.real() + ci.imag() * ci.imag();
     magsq /= (SDR_TX_SCALED*SDR_TX_SCALED);
     m_movingAverage.feed(magsq);
     m_magsq = m_movingAverage.average();
     sample.m_real = (FixReal) ci.real();
     sample.m_imag = (FixReal) ci.imag();
 }
readMonoSample()
void UDPSource::readMonoSample (qint16 & t) inline private
Definition at line 322 of file udpsource.h.
References AudioSample::l, UDPSourceSettings::m_gainIn, UDPSourceSettings::m_stereoInput, AudioSample::r, and UDPSourceUDPHandler::readSample().
Referenced by modulateSample().
     {
         if (m_settings.m_stereoInput)
         {
             AudioSample a;
             m_udpHandler.readSample(a);
             t = ((a.l + a.r) * m_settings.m_gainIn) / 2;
         }
         else
         {
             m_udpHandler.readSample(t);
             t *= m_settings.m_gainIn;
         }
     }
resetReadIndex()
void UDPSource::resetReadIndex ()
Definition at line 456 of file udpsource.cpp.
References UDPSource::MsgResetReadIndex::create(), BasebandSampleSource::getInputMessageQueue(), and MessageQueue::push().
Referenced by getSquelchOpen(), and UDPSourceGUI::on_resetUDPReadIndex_clicked().
 {
     Message* cmd = MsgResetReadIndex::create();
     getInputMessageQueue()->push(cmd);
 }
serialize()
QByteArray UDPSource::serialize () const virtual
Implements ChannelAPI.
Definition at line 652 of file udpsource.cpp.
References m_settings, and UDPSourceSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
setSpectrum()
void UDPSource::setSpectrum (bool enabled)
Definition at line 450 of file udpsource.cpp.
References UDPSource::MsgUDPSourceSpectrum::create(), BasebandSampleSource::getInputMessageQueue(), and MessageQueue::push().
Referenced by getSquelchOpen(), and UDPSourceGUI::onWidgetRolled().
 {
     Message* cmd = MsgUDPSourceSpectrum::create(enabled);
     getInputMessageQueue()->push(cmd);
 }
setSpectrumSink()
void UDPSource::setSpectrumSink (BasebandSampleSink * spectrum) inline
Definition at line 97 of file udpsource.h.
References handleMessage(), m_spectrum, pull(), start(), and stop().
Referenced by UDPSourceGUI::UDPSourceGUI().
 { m_spectrum = spectrum; }
start()
void UDPSource::start () virtual
Implements BasebandSampleSource.
Definition at line 102 of file udpsource.cpp.
References applyChannelSettings(), m_basebandSampleRate, m_inputFrequencyOffset, m_outputSampleRate, m_udpHandler, and UDPSourceUDPHandler::start().
Referenced by setSpectrumSink().
 {
     m_udpHandler.start();
     applyChannelSettings(m_basebandSampleRate, m_outputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void UDPSource::stop () virtual
Implements BasebandSampleSource.
Definition at line 108 of file udpsource.cpp.
References m_udpHandler, and UDPSourceUDPHandler::stop().
Referenced by setSpectrumSink().
 {
     m_udpHandler.stop();
 }
webapiFormatChannelReport()
void UDPSource::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 849 of file udpsource.cpp.
References CalcDb::dbPower(), getBufferGauge(), getInMagSq(), getMagSq(), SWGSDRangel::SWGChannelReport::getUdpSourceReport(), m_outputSampleRate, m_squelchOpen, SWGSDRangel::SWGUDPSourceReport::setBufferGauge(), SWGSDRangel::SWGUDPSourceReport::setChannelPowerDb(), SWGSDRangel::SWGUDPSourceReport::setChannelSampleRate(), SWGSDRangel::SWGUDPSourceReport::setInputPowerDb(), and SWGSDRangel::SWGUDPSourceReport::setSquelch().
Referenced by webapiReportGet().
 {
     response.getUdpSourceReport()->setInputPowerDb(CalcDb::dbPower(getInMagSq()));
     response.getUdpSourceReport()->setChannelPowerDb(CalcDb::dbPower(getMagSq()));
     response.getUdpSourceReport()->setSquelch(m_squelchOpen ? 1 : 0);
     response.getUdpSourceReport()->setBufferGauge(getBufferGauge());
     response.getUdpSourceReport()->setChannelSampleRate(m_outputSampleRate);
 }
webapiFormatChannelSettings()
void UDPSource::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const UDPSourceSettings & settings) private
Definition at line 803 of file udpsource.cpp.
References SWGSDRangel::SWGUDPSourceSettings::getReverseApiAddress(), SWGSDRangel::SWGUDPSourceSettings::getTitle(), SWGSDRangel::SWGUDPSourceSettings::getUdpAddress(), SWGSDRangel::SWGChannelSettings::getUdpSourceSettings(), UDPSourceSettings::m_amModFactor, UDPSourceSettings::m_autoRWBalance, UDPSourceSettings::m_channelMute, UDPSourceSettings::m_fmDeviation, UDPSourceSettings::m_gainIn, UDPSourceSettings::m_gainOut, UDPSourceSettings::m_inputFrequencyOffset, UDPSourceSettings::m_inputSampleRate, UDPSourceSettings::m_lowCutoff, UDPSourceSettings::m_reverseAPIAddress, UDPSourceSettings::m_reverseAPIChannelIndex, UDPSourceSettings::m_reverseAPIDeviceIndex, UDPSourceSettings::m_reverseAPIPort, UDPSourceSettings::m_rfBandwidth, UDPSourceSettings::m_rgbColor, UDPSourceSettings::m_sampleFormat, UDPSourceSettings::m_squelch, UDPSourceSettings::m_squelchEnabled, UDPSourceSettings::m_squelchGate, UDPSourceSettings::m_stereoInput, UDPSourceSettings::m_title, UDPSourceSettings::m_udpAddress, UDPSourceSettings::m_udpPort, UDPSourceSettings::m_useReverseAPI, SWGSDRangel::SWGUDPSourceSettings::setAmModFactor(), SWGSDRangel::SWGUDPSourceSettings::setAutoRwBalance(), SWGSDRangel::SWGUDPSourceSettings::setChannelMute(), SWGSDRangel::SWGUDPSourceSettings::setFmDeviation(), SWGSDRangel::SWGUDPSourceSettings::setGainIn(), SWGSDRangel::SWGUDPSourceSettings::setGainOut(), SWGSDRangel::SWGUDPSourceSettings::setInputFrequencyOffset(), SWGSDRangel::SWGUDPSourceSettings::setInputSampleRate(), SWGSDRangel::SWGUDPSourceSettings::setLowCutoff(), SWGSDRangel::SWGUDPSourceSettings::setReverseApiAddress(), SWGSDRangel::SWGUDPSourceSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGUDPSourceSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGUDPSourceSettings::setReverseApiPort(), SWGSDRangel::SWGUDPSourceSettings::setRfBandwidth(), SWGSDRangel::SWGUDPSourceSettings::setRgbColor(), SWGSDRangel::SWGUDPSourceSettings::setSampleFormat(), SWGSDRangel::SWGUDPSourceSettings::setSquelch(), SWGSDRangel::SWGUDPSourceSettings::setSquelchEnabled(), SWGSDRangel::SWGUDPSourceSettings::setSquelchGate(), SWGSDRangel::SWGUDPSourceSettings::setStereoInput(), SWGSDRangel::SWGUDPSourceSettings::setTitle(), SWGSDRangel::SWGUDPSourceSettings::setUdpAddress(), SWGSDRangel::SWGUDPSourceSettings::setUdpPort(), and SWGSDRangel::SWGUDPSourceSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getUdpSourceSettings()->setSampleFormat((int) settings.m_sampleFormat);
     response.getUdpSourceSettings()->setInputSampleRate(settings.m_inputSampleRate);
     response.getUdpSourceSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getUdpSourceSettings()->setRfBandwidth(settings.m_rfBandwidth);
     response.getUdpSourceSettings()->setLowCutoff(settings.m_lowCutoff);
     response.getUdpSourceSettings()->setFmDeviation(settings.m_fmDeviation);
     response.getUdpSourceSettings()->setAmModFactor(settings.m_amModFactor);
     response.getUdpSourceSettings()->setChannelMute(settings.m_channelMute ? 1 : 0);
     response.getUdpSourceSettings()->setGainIn(settings.m_gainIn);
     response.getUdpSourceSettings()->setGainOut(settings.m_gainOut);
     response.getUdpSourceSettings()->setSquelch(settings.m_squelch);
     response.getUdpSourceSettings()->setSquelchGate(settings.m_squelchGate);
     response.getUdpSourceSettings()->setSquelchEnabled(settings.m_squelchEnabled ? 1 : 0);
     response.getUdpSourceSettings()->setAutoRwBalance(settings.m_autoRWBalance ? 1 : 0);
     response.getUdpSourceSettings()->setStereoInput(settings.m_stereoInput ? 1 : 0);
     response.getUdpSourceSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getUdpSourceSettings()->getUdpAddress()) {
         *response.getUdpSourceSettings()->getUdpAddress() = settings.m_udpAddress;
     } else {
         response.getUdpSourceSettings()->setUdpAddress(new QString(settings.m_udpAddress));
     }
     response.getUdpSourceSettings()->setUdpPort(settings.m_udpPort);
     if (response.getUdpSourceSettings()->getTitle()) {
         *response.getUdpSourceSettings()->getTitle() = settings.m_title;
     } else {
         response.getUdpSourceSettings()->setTitle(new QString(settings.m_title));
     }
     response.getUdpSourceSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getUdpSourceSettings()->getReverseApiAddress()) {
         *response.getUdpSourceSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getUdpSourceSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getUdpSourceSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getUdpSourceSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getUdpSourceSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int UDPSource::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 792 of file udpsource.cpp.
References SWGSDRangel::SWGChannelReport::getUdpSourceReport(), SWGSDRangel::SWGUDPSourceReport::init(), SWGSDRangel::SWGChannelReport::setUdpSourceReport(), and webapiFormatChannelReport().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setUdpSourceReport(new SWGSDRangel::SWGUDPSourceReport());
     response.getUdpSourceReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendSettings()
void UDPSource::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const UDPSourceSettings & settings, bool force) private
Definition at line 858 of file udpsource.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), SWGSDRangel::SWGChannelSettings::getUdpSourceSettings(), UDPSourceSettings::m_amModFactor, UDPSourceSettings::m_autoRWBalance, UDPSourceSettings::m_channelMute, UDPSourceSettings::m_fmDeviation, UDPSourceSettings::m_gainIn, UDPSourceSettings::m_gainOut, UDPSourceSettings::m_inputFrequencyOffset, UDPSourceSettings::m_inputSampleRate, UDPSourceSettings::m_lowCutoff, m_networkManager, m_networkRequest, UDPSourceSettings::m_reverseAPIAddress, UDPSourceSettings::m_reverseAPIChannelIndex, UDPSourceSettings::m_reverseAPIDeviceIndex, UDPSourceSettings::m_reverseAPIPort, UDPSourceSettings::m_rfBandwidth, UDPSourceSettings::m_rgbColor, UDPSourceSettings::m_sampleFormat, UDPSourceSettings::m_squelch, UDPSourceSettings::m_squelchEnabled, UDPSourceSettings::m_squelchGate, UDPSourceSettings::m_stereoInput, UDPSourceSettings::m_title, UDPSourceSettings::m_udpAddress, UDPSourceSettings::m_udpPort, SWGSDRangel::SWGUDPSourceSettings::setAmModFactor(), SWGSDRangel::SWGUDPSourceSettings::setAutoRwBalance(), SWGSDRangel::SWGUDPSourceSettings::setChannelMute(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGUDPSourceSettings::setFmDeviation(), SWGSDRangel::SWGUDPSourceSettings::setGainIn(), SWGSDRangel::SWGUDPSourceSettings::setGainOut(), SWGSDRangel::SWGUDPSourceSettings::setInputFrequencyOffset(), SWGSDRangel::SWGUDPSourceSettings::setInputSampleRate(), SWGSDRangel::SWGUDPSourceSettings::setLowCutoff(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGUDPSourceSettings::setRfBandwidth(), SWGSDRangel::SWGUDPSourceSettings::setRgbColor(), SWGSDRangel::SWGUDPSourceSettings::setSampleFormat(), SWGSDRangel::SWGUDPSourceSettings::setSquelch(), SWGSDRangel::SWGUDPSourceSettings::setSquelchEnabled(), SWGSDRangel::SWGUDPSourceSettings::setSquelchGate(), SWGSDRangel::SWGUDPSourceSettings::setStereoInput(), SWGSDRangel::SWGUDPSourceSettings::setTitle(), SWGSDRangel::SWGUDPSourceSettings::setUdpAddress(), SWGSDRangel::SWGUDPSourceSettings::setUdpPort(), and SWGSDRangel::SWGChannelSettings::setUdpSourceSettings().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("UDPSource"));
     swgChannelSettings->setUdpSourceSettings(new SWGSDRangel::SWGUDPSourceSettings());
     SWGSDRangel::SWGUDPSourceSettings *swgUDPSourceSettings = swgChannelSettings->getUdpSourceSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("sampleFormat") || force) {
         swgUDPSourceSettings->setSampleFormat((int) settings.m_sampleFormat);
     }
     if (channelSettingsKeys.contains("inputSampleRate") || force) {
         swgUDPSourceSettings->setInputSampleRate(settings.m_inputSampleRate);
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgUDPSourceSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("rfBandwidth") || force) {
         swgUDPSourceSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (channelSettingsKeys.contains("lowCutoff") || force) {
         swgUDPSourceSettings->setLowCutoff(settings.m_lowCutoff);
     }
     if (channelSettingsKeys.contains("fmDeviation") || force) {
         swgUDPSourceSettings->setFmDeviation(settings.m_fmDeviation);
     }
     if (channelSettingsKeys.contains("amModFactor") || force) {
         swgUDPSourceSettings->setAmModFactor(settings.m_amModFactor);
     }
     if (channelSettingsKeys.contains("channelMute") || force) {
         swgUDPSourceSettings->setChannelMute(settings.m_channelMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("gainIn") || force) {
         swgUDPSourceSettings->setGainIn(settings.m_gainIn);
     }
     if (channelSettingsKeys.contains("gainOut") || force) {
         swgUDPSourceSettings->setGainOut(settings.m_gainOut);
     }
     if (channelSettingsKeys.contains("squelch") || force) {
         swgUDPSourceSettings->setSquelch(settings.m_squelch);
     }
     if (channelSettingsKeys.contains("squelchGate") || force) {
         swgUDPSourceSettings->setSquelchGate(settings.m_squelchGate);
     }
     if (channelSettingsKeys.contains("squelchEnabled") || force) {
         swgUDPSourceSettings->setSquelchEnabled(settings.m_squelchEnabled ? 1 : 0);
     }
     if (channelSettingsKeys.contains("autoRWBalance") || force) {
         swgUDPSourceSettings->setAutoRwBalance(settings.m_autoRWBalance ? 1 : 0);
     }
     if (channelSettingsKeys.contains("stereoInput") || force) {
         swgUDPSourceSettings->setStereoInput(settings.m_stereoInput ? 1 : 0);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgUDPSourceSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("udpAddress") || force) {
         swgUDPSourceSettings->setUdpAddress(new QString(settings.m_udpAddress));
     }
     if (channelSettingsKeys.contains("udpPort") || force) {
         swgUDPSourceSettings->setUdpPort(settings.m_udpPort);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgUDPSourceSettings->setTitle(new QString(settings.m_title));
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int UDPSource::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 674 of file udpsource.cpp.
References SWGSDRangel::SWGChannelSettings::getUdpSourceSettings(), SWGSDRangel::SWGUDPSourceSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setUdpSourceSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setUdpSourceSettings(new SWGSDRangel::SWGUDPSourceSettings());
     response.getUdpSourceSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int UDPSource::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 685 of file udpsource.cpp.
References UDPSource::MsgConfigureUDPSource::create(), UDPSource::MsgConfigureChannelizer::create(), SWGSDRangel::SWGUDPSourceSettings::getAmModFactor(), SWGSDRangel::SWGUDPSourceSettings::getAutoRwBalance(), SWGSDRangel::SWGUDPSourceSettings::getChannelMute(), SWGSDRangel::SWGUDPSourceSettings::getFmDeviation(), SWGSDRangel::SWGUDPSourceSettings::getGainIn(), SWGSDRangel::SWGUDPSourceSettings::getGainOut(), SWGSDRangel::SWGUDPSourceSettings::getInputFrequencyOffset(), SWGSDRangel::SWGUDPSourceSettings::getInputSampleRate(), SWGSDRangel::SWGUDPSourceSettings::getLowCutoff(), SWGSDRangel::SWGUDPSourceSettings::getReverseApiAddress(), SWGSDRangel::SWGUDPSourceSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGUDPSourceSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGUDPSourceSettings::getReverseApiPort(), SWGSDRangel::SWGUDPSourceSettings::getRfBandwidth(), SWGSDRangel::SWGUDPSourceSettings::getRgbColor(), SWGSDRangel::SWGUDPSourceSettings::getSampleFormat(), SWGSDRangel::SWGUDPSourceSettings::getSquelch(), SWGSDRangel::SWGUDPSourceSettings::getSquelchEnabled(), SWGSDRangel::SWGUDPSourceSettings::getSquelchGate(), SWGSDRangel::SWGUDPSourceSettings::getStereoInput(), SWGSDRangel::SWGUDPSourceSettings::getTitle(), SWGSDRangel::SWGUDPSourceSettings::getUdpAddress(), SWGSDRangel::SWGUDPSourceSettings::getUdpPort(), SWGSDRangel::SWGChannelSettings::getUdpSourceSettings(), SWGSDRangel::SWGUDPSourceSettings::getUseReverseApi(), UDPSourceSettings::m_amModFactor, UDPSourceSettings::m_autoRWBalance, UDPSourceSettings::m_channelMute, UDPSourceSettings::m_fmDeviation, UDPSourceSettings::m_gainIn, UDPSourceSettings::m_gainOut, BasebandSampleSource::m_guiMessageQueue, UDPSourceSettings::m_inputFrequencyOffset, BasebandSampleSource::m_inputMessageQueue, UDPSourceSettings::m_inputSampleRate, UDPSourceSettings::m_lowCutoff, UDPSourceSettings::m_reverseAPIAddress, UDPSourceSettings::m_reverseAPIChannelIndex, UDPSourceSettings::m_reverseAPIDeviceIndex, UDPSourceSettings::m_reverseAPIPort, UDPSourceSettings::m_rfBandwidth, UDPSourceSettings::m_rgbColor, UDPSourceSettings::m_sampleFormat, m_settings, UDPSourceSettings::m_squelch, UDPSourceSettings::m_squelchEnabled, UDPSourceSettings::m_squelchGate, UDPSourceSettings::m_stereoInput, UDPSourceSettings::m_title, UDPSourceSettings::m_udpAddress, UDPSourceSettings::m_udpPort, UDPSourceSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     UDPSourceSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
     if (channelSettingsKeys.contains("sampleFormat")) {
         settings.m_sampleFormat = (UDPSourceSettings::SampleFormat) response.getUdpSourceSettings()->getSampleFormat();
     }
     if (channelSettingsKeys.contains("inputSampleRate")) {
         settings.m_inputSampleRate = response.getUdpSourceSettings()->getInputSampleRate();
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getUdpSourceSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getUdpSourceSettings()->getRfBandwidth();
     }
     if (channelSettingsKeys.contains("lowCutoff")) {
         settings.m_lowCutoff = response.getUdpSourceSettings()->getLowCutoff();
     }
     if (channelSettingsKeys.contains("fmDeviation")) {
         settings.m_fmDeviation = response.getUdpSourceSettings()->getFmDeviation();
     }
     if (channelSettingsKeys.contains("amModFactor")) {
         settings.m_amModFactor = response.getUdpSourceSettings()->getAmModFactor();
     }
     if (channelSettingsKeys.contains("channelMute")) {
         settings.m_channelMute = response.getUdpSourceSettings()->getChannelMute() != 0;
     }
     if (channelSettingsKeys.contains("gainIn")) {
         settings.m_gainIn = response.getUdpSourceSettings()->getGainIn();
     }
     if (channelSettingsKeys.contains("gainOut")) {
         settings.m_gainOut = response.getUdpSourceSettings()->getGainOut();
     }
     if (channelSettingsKeys.contains("squelch")) {
         settings.m_squelch = response.getUdpSourceSettings()->getSquelch();
     }
     if (channelSettingsKeys.contains("squelchGate")) {
         settings.m_squelchGate = response.getUdpSourceSettings()->getSquelchGate();
     }
     if (channelSettingsKeys.contains("squelchEnabled")) {
         settings.m_squelchEnabled = response.getUdpSourceSettings()->getSquelchEnabled() != 0;
     }
     if (channelSettingsKeys.contains("autoRWBalance")) {
         settings.m_autoRWBalance = response.getUdpSourceSettings()->getAutoRwBalance() != 0;
     }
     if (channelSettingsKeys.contains("stereoInput")) {
         settings.m_stereoInput = response.getUdpSourceSettings()->getStereoInput() != 0;
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getUdpSourceSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("udpAddress")) {
         settings.m_udpAddress = *response.getUdpSourceSettings()->getUdpAddress();
     }
     if (channelSettingsKeys.contains("udpPort")) {
         settings.m_udpPort = response.getUdpSourceSettings()->getUdpPort();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getUdpSourceSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getUdpSourceSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getUdpSourceSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getUdpSourceSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getUdpSourceSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getUdpSourceSettings()->getReverseApiChannelIndex();
     }
     if (frequencyOffsetChanged)
     {
         UDPSource::MsgConfigureChannelizer *msgChan = UDPSource::MsgConfigureChannelizer::create(
                 settings.m_inputSampleRate,
                 settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(msgChan);
     }
     MsgConfigureUDPSource *msg = MsgConfigureUDPSource::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureUDPSource *msgToGUI = MsgConfigureUDPSource::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_actualInputSampleRate
Real UDPSource::m_actualInputSampleRate private
sample rate with UDP buffer skew compensation
Definition at line 227 of file udpsource.h.
Referenced by applySettings(), and handleMessage().
m_basebandSampleRate
int UDPSource::m_basebandSampleRate private
Definition at line 200 of file udpsource.h.
Referenced by applyChannelSettings(), start(), and UDPSource().
m_carrierNco
NCO UDPSource::m_carrierNco private
Definition at line 207 of file udpsource.h.
Referenced by applyChannelSettings(), and pull().
m_channelId
const QString UDPSource::m_channelId = "UDPSource" static
Definition at line 144 of file udpsource.h.
Referenced by UDPSourcePlugin::initPlugin(), and UDPSource().
m_channelIdURI
const QString UDPSource::m_channelIdURI = "sdrangel.channeltx.udpsource" static
Definition at line 143 of file udpsource.h.
Referenced by UDPSourcePlugin::initPlugin(), and UDPSourceGUI::UDPSourceGUI().
m_channelizer
UpChannelizer* UDPSource::m_channelizer private
Definition at line 198 of file udpsource.h.
Referenced by handleMessage(), UDPSource(), and ~UDPSource().
m_deviceAPI
DeviceAPI* UDPSource::m_deviceAPI private
Definition at line 196 of file udpsource.h.
Referenced by UDPSource(), and ~UDPSource().
m_inMagsq
double UDPSource::m_inMagsq private
Definition at line 222 of file udpsource.h.
Referenced by getInMagSq(), and modulateSample().
m_inMovingAverage
MovingAverage<double> UDPSource::m_inMovingAverage private
Definition at line 224 of file udpsource.h.
Referenced by applySettings(), and modulateSample().
m_inputFrequencyOffset
int UDPSource::m_inputFrequencyOffset private
Definition at line 202 of file udpsource.h.
Referenced by applyChannelSettings(), start(), and UDPSource().
m_interpolator
Interpolator UDPSource::m_interpolator private
Definition at line 216 of file udpsource.h.
Referenced by applyChannelSettings(), applySettings(), and pull().
m_interpolatorConsumed
bool UDPSource::m_interpolatorConsumed private
Definition at line 219 of file udpsource.h.
Referenced by applyChannelSettings(), applySettings(), and handleMessage().
m_interpolatorDistance
Real UDPSource::m_interpolatorDistance private
Definition at line 217 of file udpsource.h.
Referenced by applyChannelSettings(), applySettings(), handleMessage(), and pull().
m_interpolatorDistanceRemain
Real UDPSource::m_interpolatorDistanceRemain private
Definition at line 218 of file udpsource.h.
Referenced by applyChannelSettings(), applySettings(), handleMessage(), and pull().
m_levelCalcCount
int UDPSource::m_levelCalcCount private
Definition at line 231 of file udpsource.h.
Referenced by applySettings(), and calculateLevel().
m_levelNbSamples
int UDPSource::m_levelNbSamples private
Definition at line 234 of file udpsource.h.
Referenced by applySettings(), and calculateLevel().
m_levelSum
double UDPSource::m_levelSum private
Definition at line 233 of file udpsource.h.
Referenced by applySettings(), and calculateLevel().
m_magsq
double UDPSource::m_magsq private
Definition at line 221 of file udpsource.h.
Referenced by getMagSq(), and pull().
m_modPhasor
float UDPSource::m_modPhasor private
Phasor for FM modulation.
Definition at line 241 of file udpsource.h.
Referenced by modulateSample().
m_modSample
Complex UDPSource::m_modSample private
Definition at line 208 of file udpsource.h.
Referenced by modulateSample(), and pull().
m_movingAverage
MovingAverage<double> UDPSource::m_movingAverage private
Definition at line 223 of file udpsource.h.
Referenced by pull().
m_networkManager
QNetworkAccessManager* UDPSource::m_networkManager private
Definition at line 246 of file udpsource.h.
Referenced by UDPSource(), webapiReverseSendSettings(), and ~UDPSource().
m_networkRequest
QNetworkRequest UDPSource::m_networkRequest private
Definition at line 247 of file udpsource.h.
Referenced by webapiReverseSendSettings().
m_outputSampleRate
Real UDPSource::m_outputSampleRate private
Definition at line 201 of file udpsource.h.
Referenced by applyChannelSettings(), applySettings(), handleMessage(), start(), UDPSource(), and webapiFormatChannelReport().
m_peakLevel
Real UDPSource::m_peakLevel private
Definition at line 232 of file udpsource.h.
Referenced by applySettings(), and calculateLevel().
m_sampleBuffer
SampleVector UDPSource::m_sampleBuffer private
Definition at line 212 of file udpsource.h.
Referenced by modulateSample().
m_sampleRateAverageItems
const int UDPSource::m_sampleRateAverageItems = 17 static private
Definition at line 251 of file udpsource.h.
Referenced by handleMessage().
m_sampleRateAvgCounter
int UDPSource::m_sampleRateAvgCounter private
Definition at line 229 of file udpsource.h.
Referenced by applySettings(), and handleMessage().
m_sampleRateSum
double UDPSource::m_sampleRateSum private
Definition at line 228 of file udpsource.h.
Referenced by applySettings(), and handleMessage().
m_settings
UDPSourceSettings UDPSource::m_settings private
Definition at line 203 of file udpsource.h.
Referenced by applyChannelSettings(), applySettings(), deserialize(), handleMessage(), modulateSample(), pull(), serialize(), UDPSource(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex UDPSource::m_settingsMutex private
Definition at line 249 of file udpsource.h.
Referenced by applyChannelSettings(), applySettings(), handleMessage(), and pull().
m_spectrum
BasebandSampleSink* UDPSource::m_spectrum private
Definition at line 210 of file udpsource.h.
Referenced by handleMessage(), modulateSample(), and setSpectrumSink().
m_spectrumChunkCounter
int UDPSource::m_spectrumChunkCounter private
Definition at line 214 of file udpsource.h.
Referenced by applySettings(), and modulateSample().
m_spectrumChunkSize
int UDPSource::m_spectrumChunkSize private
Definition at line 213 of file udpsource.h.
Referenced by applySettings(), and modulateSample().
m_spectrumEnabled
bool UDPSource::m_spectrumEnabled private
Definition at line 211 of file udpsource.h.
Referenced by handleMessage(), and modulateSample().
m_squelch
Real UDPSource::m_squelch private
Definition at line 205 of file udpsource.h.
Referenced by applySettings().
m_squelchCloseCount
int UDPSource::m_squelchCloseCount private
Definition at line 238 of file udpsource.h.
m_squelchOpen
bool UDPSource::m_squelchOpen private
Definition at line 236 of file udpsource.h.
Referenced by applySettings(), getSquelchOpen(), modulateSample(), and webapiFormatChannelReport().
m_squelchOpenCount
int UDPSource::m_squelchOpenCount private
Definition at line 237 of file udpsource.h.
m_squelchThreshold
int UDPSource::m_squelchThreshold private
Definition at line 239 of file udpsource.h.
Referenced by applySettings(), calculateSquelch(), and initSquelch().
m_ssbFftLen
const int UDPSource::m_ssbFftLen = 1024 static private
Definition at line 252 of file udpsource.h.
Referenced by UDPSource().
m_SSBFilter
fftfilt* UDPSource::m_SSBFilter private
Complex filter for SSB modulation.
Definition at line 242 of file udpsource.h.
Referenced by applySettings(), modulateSample(), UDPSource(), and ~UDPSource().
m_SSBFilterBuffer
Complex* UDPSource::m_SSBFilterBuffer private
Definition at line 243 of file udpsource.h.
Referenced by modulateSample(), UDPSource(), and ~UDPSource().
m_SSBFilterBufferIndex
int UDPSource::m_SSBFilterBufferIndex private
Definition at line 244 of file udpsource.h.
Referenced by modulateSample().
m_threadedChannelizer
ThreadedBasebandSampleSource* UDPSource::m_threadedChannelizer private
Definition at line 197 of file udpsource.h.
Referenced by UDPSource(), and ~UDPSource().
m_udpHandler
UDPSourceUDPHandler UDPSource::m_udpHandler private
Definition at line 226 of file udpsource.h.
Referenced by applySettings(), getBufferGauge(), handleMessage(), modulateSample(), start(), stop(), and UDPSource().
The documentation for this class was generated from the following files:
plugins/channeltx/udpsource/udpsource.h
plugins/channeltx/udpsource/udpsource.cpp