SDRAngel: IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder > Class Template Reference
IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder > Class Template Reference
#include <inthalfbandfilterdbff.h>
Public Member Functions
IntHalfbandFilterDBFF ()
bool workDecimateCenter (FSample *sample)
bool workInterpolateCenterZeroStuffing (FSample *sampleIn, FSample *SampleOut)
bool workInterpolateCenter (FSample *sampleIn, FSample *SampleOut)
bool workDecimateLowerHalf (FSample *sample)
bool workInterpolateLowerHalf (FSample *sampleIn, FSample *sampleOut)
bool workInterpolateLowerHalfZeroStuffing (FSample *sampleIn, FSample *sampleOut)
bool workDecimateUpperHalf (FSample *sample)
bool workInterpolateUpperHalf (FSample *sampleIn, FSample *sampleOut)
bool workInterpolateUpperHalfZeroStuffing (FSample *sampleIn, FSample *sampleOut)
void myDecimate (const FSample *sample1, FSample *sample2)
void myDecimate (AccuType x1, AccuType y1, AccuType *x2, AccuType *y2)
void myInterpolateZeroStuffing (FSample *sample1, FSample *sample2)
void myInterpolate (qint32 *x1, qint32 *y1, qint32 *x2, qint32 *y2)
void myInterpolateInf (qint32 *x1, qint32 *y1, qint32 *x2, qint32 *y2, qint32 *x3, qint32 *y3, qint32 *x4, qint32 *y4)
void myInterpolateSup (qint32 *x1, qint32 *y1, qint32 *x2, qint32 *y2, qint32 *x3, qint32 *y3, qint32 *x4, qint32 *y4)
Protected Member Functions
void storeSampleReal (const Real &sampleI, const Real &sampleQ)
void storeSampleAccu (AccuType x, AccuType y)
void advancePointer ()
void doFIR (FSample *sample)
void doFIRAccu (AccuType *x, AccuType *y)
void doInterpolateFIR (FSample *sample)
void doInterpolateFIR (Real *x, Real *y)
Protected Attributes
SampleType m_samplesDB [2 *(HBFIRFilterTraits< HBFilterOrder >::hbOrder - 1)][2]
int m_ptr
int m_size
int m_state
Detailed Description
template<typename AccuType, typename SampleType, uint32_t HBFilterOrder>
class IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >
Definition at line 31 of file inthalfbandfilterdbff.h.
Constructor & Destructor Documentation
IntHalfbandFilterDBFF()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::IntHalfbandFilterDBFF ()
Definition at line 730 of file inthalfbandfilterdbff.h.
References i.
 {
     m_size = HBFIRFilterTraits<HBFilterOrder>::hbOrder - 1;
     for (int i = 0; i < m_size; i++)
     {
         m_samplesDB[i][0] = 0;
         m_samplesDB[i][1] = 0;
     }
     m_ptr = 0;
     m_state = 0;
 }
Member Function Documentation
advancePointer()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> void IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::advancePointer () inline protected
Definition at line 637 of file inthalfbandfilterdbff.h.
     {
         m_ptr = m_ptr + 1 < m_size ? m_ptr + 1: 0;
     }
doFIR()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> void IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::doFIR (FSample * sample) inline protected
Definition at line 642 of file inthalfbandfilterdbff.h.
References i, FSample::setImag(), and FSample::setReal().
     {
         int a = m_ptr + m_size; // tip pointer
         int b = m_ptr + 1; // tail pointer
         AccuType iAcc = 0;
         AccuType qAcc = 0;
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += (m_samplesDB[a][0] + m_samplesDB[b][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
             qAcc += (m_samplesDB[a][1] + m_samplesDB[b][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
             a -= 2;
             b += 2;
         }
         iAcc += m_samplesDB[b-1][0] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         qAcc += m_samplesDB[b-1][1] << (HBFIRFilterTraits<HBFilterOrder>::hbShift - 1);
         sample->setReal(iAcc);
         sample->setImag(qAcc);
     }
doFIRAccu()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> void IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::doFIRAccu (AccuType * x, AccuType * y) inline protected
Definition at line 664 of file inthalfbandfilterdbff.h.
References i.
     {
         int a = m_ptr + m_size; // tip pointer
         int b = m_ptr + 1; // tail pointer
         AccuType iAcc = 0;
         AccuType qAcc = 0;
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += (m_samplesDB[a][0] + m_samplesDB[b][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
             qAcc += (m_samplesDB[a][1] + m_samplesDB[b][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
             a -= 2;
             b += 2;
         }
         iAcc += m_samplesDB[b-1][0] / 2.0;
         qAcc += m_samplesDB[b-1][1] / 2.0;
         *x = iAcc; // HB_SHIFT incorrect do not loose the gained bit
         *y = qAcc;
     }
doInterpolateFIR() [1/2]
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> void IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::doInterpolateFIR (FSample * sample) inline protected
Definition at line 686 of file inthalfbandfilterdbff.h.
References i, FSample::setImag(), and FSample::setReal().
     {
         qint16 a = m_ptr;
         qint16 b = m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder / 2) - 1;
         // go through samples in buffer
         AccuType iAcc = 0;
         AccuType qAcc = 0;
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += (m_samplesDB[a][0] + m_samplesDB[b][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
             qAcc += (m_samplesDB[a][1] + m_samplesDB[b][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
             a++;
             b--;
         }
         sample->setReal(iAcc);
         sample->setImag(qAcc);
     }
doInterpolateFIR() [2/2]
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> void IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::doInterpolateFIR (Real * x, Real * y) inline protected
Definition at line 707 of file inthalfbandfilterdbff.h.
References i.
     {
         qint16 a = m_ptr;
         qint16 b = m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder / 2) - 1;
         // go through samples in buffer
         AccuType iAcc = 0;
         AccuType qAcc = 0;
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += (m_samplesDB[a][0] + m_samplesDB[b][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
             qAcc += (m_samplesDB[a][1] + m_samplesDB[b][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
             a++;
             b--;
         }
         *x = iAcc;
         *y = qAcc;
     }
myDecimate() [1/2]
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> void IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::myDecimate (const FSample * sample1, FSample * sample2) inline
Definition at line 527 of file inthalfbandfilterdbff.h.
References FSample::imag(), and FSample::real().
     {
         storeSampleReal((Real) sample1->real(), (Real) sample1->imag());
         advancePointer();
         storeSampleReal((Real) sample2->real(), (Real) sample2->imag());
         doFIR(sample2);
         advancePointer();
     }
myDecimate() [2/2]
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> void IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::myDecimate (AccuType x1, AccuType y1, AccuType * x2, AccuType * y2) inline
Definition at line 537 of file inthalfbandfilterdbff.h.
     {
         storeSampleAccu(x1, y1);
         advancePointer();
         storeSampleAccu(*x2, *y2);
         doFIRAccu(x2, y2);
         advancePointer();
     }
myInterpolate()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> void IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::myInterpolate (qint32 * x1, qint32 * y1, qint32 * x2, qint32 * y2) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 560 of file inthalfbandfilterdbff.h.
     {
         // insert sample into ring double buffer
         m_samplesDB[m_ptr][0] = *x1;
         m_samplesDB[m_ptr][1] = *y1;
         m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = *x1;
         m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = *y1;
         // advance pointer
         if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
             m_ptr++;
         } else {
             m_ptr = 0;
         }
         // first output sample calculated with the middle peak
         *x1 = m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0];
         *y1 = m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1];
         // second sample calculated with the filter
         doInterpolateFIR(x2, y2);
     }
myInterpolateInf()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> void IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::myInterpolateInf (qint32 * x1, qint32 * y1, qint32 * x2, qint32 * y2, qint32 * x3, qint32 * y3, qint32 * x4, qint32 * y4) inline
Definition at line 583 of file inthalfbandfilterdbff.h.
     {
         myInterpolate(x1, y1, x2, y2);
         myInterpolate(x3, y3, x4, y4);
         // rotation
         qint32 x;
         x = *x1;
         *x1 = *y1;
         *y1 = -x;
         *x2 = -*x2;
         *y2 = -*y2;
         x = *x3;
         *x3 = -*y3;
         *y3 = x;
     }
myInterpolateSup()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> void IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::myInterpolateSup (qint32 * x1, qint32 * y1, qint32 * x2, qint32 * y2, qint32 * x3, qint32 * y3, qint32 * x4, qint32 * y4) inline
Definition at line 599 of file inthalfbandfilterdbff.h.
     {
         myInterpolate(x1, y1, x2, y2);
         myInterpolate(x3, y3, x4, y4);
         // rotation
         qint32 x;
         x = *x1;
         *x1 = -*y1;
         *y1 = x;
         *x2 = -*x2;
         *y2 = -*y2;
         x = *x3;
         *x3 = *y3;
         *y3 = -x;
     }
myInterpolateZeroStuffing()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> void IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::myInterpolateZeroStuffing (FSample * sample1, FSample * sample2) inline
Simple zero stuffing and filter
Definition at line 548 of file inthalfbandfilterdbff.h.
References FSample::imag(), and FSample::real().
     {
         storeSampleReal((Real) sample1->real(), (Real) sample1->imag());
         doFIR(sample1);
         advancePointer();
         storeSampleReal((Real) 0, (Real) 0);
         doFIR(sample2);
         advancePointer();
     }
storeSampleAccu()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> void IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::storeSampleAccu (AccuType x, AccuType y) inline protected
Definition at line 629 of file inthalfbandfilterdbff.h.
     {
         m_samplesDB[m_ptr][0] = x;
         m_samplesDB[m_ptr][1] = y;
         m_samplesDB[m_ptr + m_size][0] = x;
         m_samplesDB[m_ptr + m_size][1] = y;
     }
storeSampleReal()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> void IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::storeSampleReal (const Real & sampleI, const Real & sampleQ) inline protected
Definition at line 621 of file inthalfbandfilterdbff.h.
     {
         m_samplesDB[m_ptr][0] = sampleI;
         m_samplesDB[m_ptr][1] = sampleQ;
         m_samplesDB[m_ptr + m_size][0] = sampleI;
         m_samplesDB[m_ptr + m_size][1] = sampleQ;
     }
workDecimateCenter()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> bool IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workDecimateCenter (FSample * sample) inline
Definition at line 36 of file inthalfbandfilterdbff.h.
References FSample::imag(), and FSample::real().
     {
         // insert sample into ring-buffer
         storeSampleReal((Real) sample->real(), (Real) sample->imag());
         switch(m_state)
         {
             case 0:
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workDecimateLowerHalf()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> bool IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workDecimateLowerHalf (FSample * sample) inline
Definition at line 130 of file inthalfbandfilterdbff.h.
References FSample::imag(), and FSample::real().
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSampleReal((Real) -sample->imag(), (Real) sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             case 1:
                 // insert sample into ring-buffer
                 storeSampleReal((Real) -sample->real(), (Real) -sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 2;
                 // tell caller we have a new sample
                 return true;
             case 2:
                 // insert sample into ring-buffer
                 storeSampleReal((Real) sample->imag(), (Real) -sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 3;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSampleReal((Real) sample->real(), (Real) sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workDecimateUpperHalf()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> bool IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workDecimateUpperHalf (FSample * sample) inline
Definition at line 329 of file inthalfbandfilterdbff.h.
References FSample::imag(), and FSample::real().
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSampleReal((Real) sample->imag(), (Real) -sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             case 1:
                 // insert sample into ring-buffer
                 storeSampleReal((Real) -sample->real(), (Real) -sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 2;
                 // tell caller we have a new sample
                 return true;
             case 2:
                 // insert sample into ring-buffer
                 storeSampleReal((Real) -sample->imag(), (Real) sample->real());
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 3;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSampleReal((Real) sample->real(), (Real) sample->imag());
                 // save result
                 doFIR(sample);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
workInterpolateCenter()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> bool IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateCenter (FSample * sampleIn, FSample * SampleOut) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 96 of file inthalfbandfilterdbff.h.
References FSample::imag(), FSample::real(), FSample::setImag(), and FSample::setReal().
     {
         switch(m_state)
         {
         case 0:
             // return the middle peak
             SampleOut->setReal(m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]);
             SampleOut->setImag(m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);
             m_state = 1;  // next state
             return false; // tell caller we didn't consume the sample
         default:
             // calculate with non null samples
             doInterpolateFIR(SampleOut);
             // insert sample into ring double buffer
             m_samplesDB[m_ptr][0] = sampleIn->real();
             m_samplesDB[m_ptr][1] = sampleIn->imag();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 0; // next state
             return true; // tell caller we consumed the sample
         }
     }
workInterpolateCenterZeroStuffing()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> bool IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateCenterZeroStuffing (FSample * sampleIn, FSample * SampleOut) inline
Definition at line 65 of file inthalfbandfilterdbff.h.
References FSample::imag(), and FSample::real().
     {
         switch(m_state)
         {
             case 0:
                 // insert sample into ring-buffer
                 storeSampleReal((Real) 0, (Real) 0);
                 // save result
                 doFIR(SampleOut);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we didn't consume the sample
                 return false;
             default:
                 // insert sample into ring-buffer
                 storeSampleReal((Real) sampleIn->real(), (Real) sampleIn->imag());
                 // save result
                 doFIR(SampleOut);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we consumed the sample
                 return true;
         }
     }
workInterpolateLowerHalf()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> bool IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalf (FSample * sampleIn, FSample * sampleOut) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 181 of file inthalfbandfilterdbff.h.
References FSample::imag(), FSample::real(), FSample::setImag(), and FSample::setReal().
     {
         FSample s;
         switch(m_state)
         {
         case 0:
             // return the middle peak
             sampleOut->setReal(m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);  // imag
             sampleOut->setImag(-m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]); // - real
             m_state = 1;  // next state
             return false; // tell caller we didn't consume the sample
         case 1:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // insert sample into ring double buffer
             m_samplesDB[m_ptr][0] = sampleIn->real();
             m_samplesDB[m_ptr][1] = sampleIn->imag();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 2; // next state
             return true; // tell caller we consumed the sample
         case 2:
             // return the middle peak
             sampleOut->setReal(-m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);  // - imag
             sampleOut->setImag(m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]); // real
             m_state = 3;  // next state
             return false; // tell caller we didn't consume the sample
         default:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // insert sample into ring double buffer
             m_samplesDB[m_ptr][0] = sampleIn->real();
             m_samplesDB[m_ptr][1] = sampleIn->imag();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 0; // next state
             return true; // tell caller we consumed the sample
         }
     }
workInterpolateLowerHalfZeroStuffing()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> bool IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateLowerHalfZeroStuffing (FSample * sampleIn, FSample * sampleOut) inline
Definition at line 248 of file inthalfbandfilterdbff.h.
References FSample::imag(), FSample::real(), FSample::setImag(), and FSample::setReal().
     {
         FSample s;
         switch(m_state)
         {
         case 0:
             // insert sample into ring-buffer
             storeSampleReal((Real) 0, (Real) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(s.imag());
             sampleOut->setImag(-s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 1;
             // tell caller we didn't consume the sample
             return false;
         case 1:
             // insert sample into ring-buffer
             storeSampleReal((Real) sampleIn->real(), (Real) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 2;
             // tell caller we consumed the sample
             return true;
         case 2:
             // insert sample into ring-buffer
             storeSampleReal((Real) 0, (Real) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.imag());
             sampleOut->setImag(s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 3;
             // tell caller we didn't consume the sample
             return false;
         default:
             // insert sample into ring-buffer
             storeSampleReal((Real) sampleIn->real(), (Real) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 0;
             // tell caller we consumed the sample
             return true;
         }
     }
workInterpolateUpperHalf()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> bool IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalf (FSample * sampleIn, FSample * sampleOut) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 380 of file inthalfbandfilterdbff.h.
References FSample::imag(), FSample::real(), FSample::setImag(), and FSample::setReal().
     {
         FSample s;
         switch(m_state)
         {
         case 0:
             // return the middle peak
             sampleOut->setReal(-m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]); // - imag
             sampleOut->setImag(m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]); // + real
             m_state = 1;  // next state
             return false; // tell caller we didn't consume the sample
         case 1:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // insert sample into ring double buffer
             m_samplesDB[m_ptr][0] = sampleIn->real();
             m_samplesDB[m_ptr][1] = sampleIn->imag();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 2; // next state
             return true; // tell caller we consumed the sample
         case 2:
             // return the middle peak
             sampleOut->setReal(m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1]);  // + imag
             sampleOut->setImag(-m_samplesDB[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0]);   // - real
             m_state = 3;  // next state
             return false; // tell caller we didn't consume the sample
         default:
             // calculate with non null samples
             doInterpolateFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // insert sample into ring double buffer
             m_samplesDB[m_ptr][0] = sampleIn->real();
             m_samplesDB[m_ptr][1] = sampleIn->imag();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = sampleIn->real();
             m_samplesDB[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = sampleIn->imag();
             // advance pointer
             if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
                 m_ptr++;
             } else {
                 m_ptr = 0;
             }
             m_state = 0; // next state
             return true; // tell caller we consumed the sample
         }
     }
workInterpolateUpperHalfZeroStuffing()
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> bool IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::workInterpolateUpperHalfZeroStuffing (FSample * sampleIn, FSample * sampleOut) inline
Definition at line 447 of file inthalfbandfilterdbff.h.
References FSample::imag(), FSample::real(), FSample::setImag(), and FSample::setReal().
     {
         FSample s;
         switch(m_state)
         {
         case 0:
             // insert sample into ring-buffer
             storeSampleReal((Real) 0, (Real) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.imag());
             sampleOut->setImag(s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 1;
             // tell caller we didn't consume the sample
             return false;
         case 1:
             // insert sample into ring-buffer
             storeSampleReal((Real) sampleIn->real(), (Real) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(-s.real());
             sampleOut->setImag(-s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 2;
             // tell caller we consumed the sample
             return true;
         case 2:
             // insert sample into ring-buffer
             storeSampleReal((Real) 0, (Real) 0);
             // save result
             doFIR(&s);
             sampleOut->setReal(s.imag());
             sampleOut->setImag(-s.real());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 3;
             // tell caller we didn't consume the sample
             return false;
         default:
             // insert sample into ring-buffer
             storeSampleReal((Real) sampleIn->real(), (Real) sampleIn->imag());
             // save result
             doFIR(&s);
             sampleOut->setReal(s.real());
             sampleOut->setImag(s.imag());
             // advance write-pointer
             advancePointer();
             // next state
             m_state = 0;
             // tell caller we consumed the sample
             return true;
         }
     }
Member Data Documentation
m_ptr
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> int IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::m_ptr protected
Definition at line 617 of file inthalfbandfilterdbff.h.
m_samplesDB
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> SampleType IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::m_samplesDB[2 *(HBFIRFilterTraits< HBFilterOrder >::hbOrder - 1)][2] protected
Definition at line 616 of file inthalfbandfilterdbff.h.
m_size
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> int IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::m_size protected
Definition at line 618 of file inthalfbandfilterdbff.h.
m_state
template<typename AccuType , typename SampleType , uint32_t HBFilterOrder> int IntHalfbandFilterDBFF< AccuType, SampleType, HBFilterOrder >::m_state protected
Definition at line 619 of file inthalfbandfilterdbff.h.
The documentation for this class was generated from the following file:
sdrbase/dsp/inthalfbandfilterdbff.h