SDRAngel: FileSinkThread Class Reference
FileSinkThread Class Reference
#include <filesinkthread.h>
Inherits QThread.
Public Member Functions
FileSinkThread (std::ofstream *samplesStream, SampleSourceFifo *sampleFifo, QObject *parent=0)
~FileSinkThread ()
void startWork ()
void stopWork ()
void setSamplerate (int samplerate)
void setLog2Interpolation (int log2Interpolation)
void setBuffer (std::size_t chunksize)
bool isRunning () const
std::size_t getSamplesCount () const
void setSamplesCount (int samplesCount)
void connectTimer (const QTimer &timer)
Private Slots
void tick ()
Private Member Functions
void run ()
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
volatile bool m_running
std::ofstream * m_ofstream
std::size_t m_bufsize
unsigned int m_samplesChunkSize
SampleSourceFifo * m_sampleFifo
std::size_t m_samplesCount
int m_samplerate
int m_log2Interpolation
int m_throttlems
int m_maxThrottlems
QElapsedTimer m_elapsedTimer
bool m_throttleToggle
Interpolators< qint16, SDR_TX_SAMP_SZ, 16 > m_interpolators
int16_t * m_buf
Detailed Description
Definition at line 38 of file filesinkthread.h.
Constructor & Destructor Documentation
FileSinkThread()
FileSinkThread::FileSinkThread (std::ofstream * samplesStream, SampleSourceFifo * sampleFifo, QObject * parent = 0)
Definition at line 27 of file filesinkthread.cpp.
References m_ofstream.
                                                                                                         :
     QThread(parent),
     m_running(false),
     m_ofstream(samplesStream),
     m_bufsize(0),
     m_samplesChunkSize(0),
     m_sampleFifo(sampleFifo),
     m_samplesCount(0),
     m_samplerate(0),
     m_log2Interpolation(0),
     m_throttlems(FILESINK_THROTTLE_MS),
     m_maxThrottlems(50),
     m_throttleToggle(false),
     m_buf(0)
 {
     assert(m_ofstream != 0);
 }
~FileSinkThread()
FileSinkThread::~FileSinkThread ()
Definition at line 45 of file filesinkthread.cpp.
References m_buf, m_running, and stopWork().
 {
     if (m_running) {
         stopWork();
     }
     if (m_buf) delete[] m_buf;
 }
Member Function Documentation
connectTimer()
void FileSinkThread::connectTimer (const QTimer & timer)
Definition at line 162 of file filesinkthread.cpp.
References tick().
Referenced by setSamplesCount(), and FileSinkOutput::start().
 {
     qDebug() << "FileSinkThread::connectTimer";
     connect(&timer, SIGNAL(timeout()), this, SLOT(tick()));
 }
getSamplesCount()
std::size_t FileSinkThread::getSamplesCount () const inline
Definition at line 51 of file filesinkthread.h.
References m_samplesCount.
Referenced by FileSinkOutput::handleMessage().
 { return m_samplesCount; }
isRunning()
bool FileSinkThread::isRunning () const inline
Definition at line 50 of file filesinkthread.h.
References m_running.
 { return m_running; }
run()
void FileSinkThread::run () private
Definition at line 149 of file filesinkthread.cpp.
References m_running, and m_startWaiter.
 {
     m_running = true;
     m_startWaiter.wakeAll();
     while(m_running) // actual work is in the tick() function
     {
         sleep(1);
     }
     m_running = false;
 }
setBuffer()
void FileSinkThread::setBuffer (std::size_t chunksize)
setLog2Interpolation()
void FileSinkThread::setLog2Interpolation (int log2Interpolation)
Definition at line 116 of file filesinkthread.cpp.
References m_buf, m_log2Interpolation, m_running, m_samplerate, startWork(), and stopWork().
Referenced by FileSinkOutput::applySettings(), and FileSinkOutput::start().
 {
     if ((log2Interpolation < 0) || (log2Interpolation > 6))
     {
         return;
     }
     if (log2Interpolation != m_log2Interpolation)
     {
         qDebug() << "FileSinkThread::setLog2Interpolation:"
                 << " new:" << log2Interpolation
                 << " old:" << m_log2Interpolation;
         bool wasRunning = false;
         if (m_running)
         {
             stopWork();
             wasRunning = true;
         }
         // resize output buffer
         if (m_buf) delete[] m_buf;
         m_buf = new int16_t[m_samplerate*(1<<log2Interpolation)*2];
         m_log2Interpolation = log2Interpolation;
         if (wasRunning) {
             startWork();
         }
     }
 }
setSamplerate()
void FileSinkThread::setSamplerate (int samplerate)
Definition at line 82 of file filesinkthread.cpp.
References m_buf, m_log2Interpolation, m_running, m_sampleFifo, m_samplerate, m_samplesChunkSize, m_throttlems, SampleSourceFifo::resize(), startWork(), and stopWork().
Referenced by FileSinkOutput::applySettings(), and FileSinkOutput::start().
 {
     if (samplerate != m_samplerate)
     {
         qDebug() << "FileSinkThread::setSamplerate:"
                 << " new:" << samplerate
                 << " old:" << m_samplerate;
         bool wasRunning = false;
         if (m_running)
         {
             stopWork();
             wasRunning = true;
         }
         // resize sample FIFO
         if (m_sampleFifo) {
             m_sampleFifo->resize(samplerate); // 1s buffer
         }
         // resize output buffer
         if (m_buf) delete[] m_buf;
         m_buf = new int16_t[samplerate*(1<<m_log2Interpolation)*2];
         m_samplerate = samplerate;
         m_samplesChunkSize = (m_samplerate * m_throttlems) / 1000;
         if (wasRunning) {
             startWork();
         }
     }
 }
setSamplesCount()
void FileSinkThread::setSamplesCount (int samplesCount) inline
Definition at line 52 of file filesinkthread.h.
References connectTimer(), and m_samplesCount.
 { m_samplesCount = samplesCount; }
startWork()
void FileSinkThread::startWork ()
Definition at line 54 of file filesinkthread.cpp.
References m_elapsedTimer, m_maxThrottlems, m_ofstream, m_running, m_startWaiter, and m_startWaitMutex.
Referenced by FileSinkOutput::handleMessage(), setLog2Interpolation(), setSamplerate(), and FileSinkOutput::start().
 {
     qDebug() << "FileSinkThread::startWork: ";
     if (m_ofstream->is_open())
     {
         qDebug() << "FileSinkThread::startWork: file stream open, starting...";
         m_maxThrottlems = 0;
         m_startWaitMutex.lock();
         m_elapsedTimer.start();
         start();
         while(!m_running)
             m_startWaiter.wait(&m_startWaitMutex, 100);
         m_startWaitMutex.unlock();
     }
     else
     {
         qDebug() << "FileSinkThread::startWork: file stream closed, not starting.";
     }
 }
stopWork()
void FileSinkThread::stopWork ()
Definition at line 75 of file filesinkthread.cpp.
References m_running.
Referenced by FileSinkOutput::handleMessage(), setLog2Interpolation(), setSamplerate(), FileSinkOutput::stop(), and ~FileSinkThread().
 {
     qDebug() << "FileSinkThread::stopWork";
     m_running = false;
     wait();
 }
tick
void FileSinkThread::tick () private slot
Definition at line 168 of file filesinkthread.cpp.
References Interpolators< T, SdrBits, OutputBits >::interpolate16_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate2_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate32_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate4_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate64_cen(), Interpolators< T, SdrBits, OutputBits >::interpolate8_cen(), m_buf, m_elapsedTimer, m_interpolators, m_log2Interpolation, m_ofstream, m_running, m_sampleFifo, m_samplerate, m_samplesChunkSize, m_samplesCount, m_throttlems, m_throttleToggle, leansdr::min(), and SampleSourceFifo::readAdvance().
Referenced by connectTimer().
 {
     if (m_running)
     {
         qint64 throttlems = m_elapsedTimer.restart();
         if (throttlems != m_throttlems)
         {
             m_throttlems = throttlems;
             m_samplesChunkSize = (m_samplerate * (m_throttlems+(m_throttleToggle ? 1 : 0))) / 1000;
             m_throttleToggle = !m_throttleToggle;
         }
 //        if (m_throttlems > m_maxThrottlems)
 //        {
 //            qDebug("FileSinkThread::tick: m_maxThrottlems: %d", m_maxThrottlems);
 //            m_maxThrottlems = m_throttlems;
 //        }
         SampleVector::iterator readUntil;
         m_sampleFifo->readAdvance(readUntil, m_samplesChunkSize);
         SampleVector::iterator beginRead = readUntil - m_samplesChunkSize;
         m_samplesCount += m_samplesChunkSize;
         if (m_log2Interpolation == 0)
         {
             m_ofstream->write(reinterpret_cast<char*>(&(*beginRead)), m_samplesChunkSize*sizeof(Sample));
         }
         else
         {
             int chunkSize = std::min((int) m_samplesChunkSize, m_samplerate);
             switch (m_log2Interpolation)
             {
             case 1:
                 m_interpolators.interpolate2_cen(&beginRead, m_buf, chunkSize*(1<<m_log2Interpolation)*2);
                 break;
             case 2:
                 m_interpolators.interpolate4_cen(&beginRead, m_buf, chunkSize*(1<<m_log2Interpolation)*2);
                 break;
             case 3:
                 m_interpolators.interpolate8_cen(&beginRead, m_buf, chunkSize*(1<<m_log2Interpolation)*2);
                 break;
             case 4:
                 m_interpolators.interpolate16_cen(&beginRead, m_buf, chunkSize*(1<<m_log2Interpolation)*2);
                 break;
             case 5:
                 m_interpolators.interpolate32_cen(&beginRead, m_buf, chunkSize*(1<<m_log2Interpolation)*2);
                 break;
             case 6:
                 m_interpolators.interpolate64_cen(&beginRead, m_buf, chunkSize*(1<<m_log2Interpolation)*2);
                 break;
             default:
                 break;
             }
             m_ofstream->write(reinterpret_cast<char*>(m_buf), m_samplesChunkSize*(1<<m_log2Interpolation)*2*sizeof(int16_t));
         }
     }
 }
Member Data Documentation
m_buf
int16_t* FileSinkThread::m_buf private
Definition at line 75 of file filesinkthread.h.
Referenced by setLog2Interpolation(), setSamplerate(), tick(), and ~FileSinkThread().
m_bufsize
std::size_t FileSinkThread::m_bufsize private
Definition at line 62 of file filesinkthread.h.
m_elapsedTimer
QElapsedTimer FileSinkThread::m_elapsedTimer private
Definition at line 71 of file filesinkthread.h.
Referenced by startWork(), and tick().
m_interpolators
Interpolators<qint16, SDR_TX_SAMP_SZ, 16> FileSinkThread::m_interpolators private
Definition at line 74 of file filesinkthread.h.
Referenced by tick().
m_log2Interpolation
int FileSinkThread::m_log2Interpolation private
Definition at line 68 of file filesinkthread.h.
Referenced by setLog2Interpolation(), setSamplerate(), and tick().
m_maxThrottlems
int FileSinkThread::m_maxThrottlems private
Definition at line 70 of file filesinkthread.h.
Referenced by startWork().
m_ofstream
std::ofstream* FileSinkThread::m_ofstream private
Definition at line 61 of file filesinkthread.h.
Referenced by FileSinkThread(), startWork(), and tick().
m_running
volatile bool FileSinkThread::m_running private
Definition at line 59 of file filesinkthread.h.
Referenced by isRunning(), run(), setLog2Interpolation(), setSamplerate(), startWork(), stopWork(), tick(), and ~FileSinkThread().
m_sampleFifo
SampleSourceFifo* FileSinkThread::m_sampleFifo private
Definition at line 64 of file filesinkthread.h.
Referenced by setSamplerate(), and tick().
m_samplerate
int FileSinkThread::m_samplerate private
Definition at line 67 of file filesinkthread.h.
Referenced by setLog2Interpolation(), setSamplerate(), and tick().
m_samplesChunkSize
unsigned int FileSinkThread::m_samplesChunkSize private
Definition at line 63 of file filesinkthread.h.
Referenced by setSamplerate(), and tick().
m_samplesCount
std::size_t FileSinkThread::m_samplesCount private
Definition at line 65 of file filesinkthread.h.
Referenced by getSamplesCount(), setSamplesCount(), and tick().
m_startWaiter
QWaitCondition FileSinkThread::m_startWaiter private
Definition at line 58 of file filesinkthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex FileSinkThread::m_startWaitMutex private
Definition at line 57 of file filesinkthread.h.
Referenced by startWork().
m_throttlems
int FileSinkThread::m_throttlems private
Definition at line 69 of file filesinkthread.h.
Referenced by setSamplerate(), and tick().
m_throttleToggle
bool FileSinkThread::m_throttleToggle private
Definition at line 72 of file filesinkthread.h.
Referenced by tick().
The documentation for this class was generated from the following files:
plugins/samplesink/filesink/filesinkthread.h
plugins/samplesink/filesink/filesinkthread.cpp