SDRAngel: LocalSinkGUI Class Reference
LocalSinkGUI Class Reference
#include <localsinkgui.h>
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static LocalSinkGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
Private Slots
void handleSourceMessages ()
void on_decimationFactor_currentIndexChanged (int index)
void on_position_valueChanged (int value)
void on_localDevice_currentIndexChanged (int index)
void on_localDevicesRefresh_clicked (bool checked)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void tick ()
Private Member Functions
LocalSinkGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *parent=0)
virtual ~LocalSinkGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void applyChannelSettings ()
void displaySettings ()
void displayRateAndShift ()
void updateLocalDevices ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
void applyDecimation ()
void applyPosition ()
Private Attributes
Ui::LocalSinkGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
LocalSinkSettings m_settings
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
double m_shiftFrequencyFactor
Channel frequency shift factor.
bool m_doApplySettings
LocalSink * m_localSink
MessageQueue m_inputMessageQueue
QTime m_time
uint32_t m_tickCount
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 42 of file localsinkgui.h.
Constructor & Destructor Documentation
LocalSinkGUI()
LocalSinkGUI::LocalSinkGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * parent = 0) explicit private
Definition at line 108 of file localsinkgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), displaySettings(), getInputMessageQueue(), handleSourceMessages(), LocalSink::m_channelIdURI, m_channelMarker, m_deviceUISet, m_localSink, LocalSinkSettings::m_rgbColor, m_settings, m_time, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), ChannelMarker::setCenterFrequency(), LocalSinkSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSink::setMessageQueueToGUI(), ChannelMarker::setTitle(), ChannelMarker::setVisible(), ui, updateLocalDevices(), and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                          :
         RollupWidget(parent),
         ui(new Ui::LocalSinkGUI),
         m_pluginAPI(pluginAPI),
         m_deviceUISet(deviceUISet),
         m_sampleRate(0),
         m_tickCount(0)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_localSink = (LocalSink*) channelrx;
     m_localSink->setMessageQueueToGUI(getInputMessageQueue());
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("Local Sink");
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     m_settings.setChannelMarker(&m_channelMarker);
     m_deviceUISet->registerRxChannelInstance(LocalSink::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     //connect(&(m_deviceUISet->m_deviceSourceAPI->getMasterTimer()), SIGNAL(timeout()), this, SLOT(tick()));
     m_time.start();
     updateLocalDevices();
     displaySettings();
     applySettings(true);
 }
~LocalSinkGUI()
LocalSinkGUI::~LocalSinkGUI () private virtual
Definition at line 147 of file localsinkgui.cpp.
References m_deviceUISet, m_localSink, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_localSink; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete ui;
 }
Member Function Documentation
applyChannelSettings()
void LocalSinkGUI::applyChannelSettings () private
Definition at line 170 of file localsinkgui.cpp.
References LocalSink::MsgConfigureChannelizer::create(), BasebandSampleSink::getInputMessageQueue(), m_doApplySettings, LocalSinkSettings::m_filterChainHash, m_localSink, LocalSinkSettings::m_log2Decim, m_settings, and MessageQueue::push().
Referenced by applyPosition().
 {
     if (m_doApplySettings)
     {
         LocalSink::MsgConfigureChannelizer *msgChan = LocalSink::MsgConfigureChannelizer::create(
                 m_settings.m_log2Decim,
                 m_settings.m_filterChainHash);
         m_localSink->getInputMessageQueue()->push(msgChan);
     }
 }
applyDecimation()
void LocalSinkGUI::applyDecimation () private
Definition at line 307 of file localsinkgui.cpp.
References applyPosition(), i, LocalSinkSettings::m_filterChainHash, LocalSinkSettings::m_log2Decim, m_settings, and ui.
Referenced by displaySettings(), and on_decimationFactor_currentIndexChanged().
 {
     uint32_t maxHash = 1;
     for (uint32_t i = 0; i < m_settings.m_log2Decim; i++) {
         maxHash *= 3;
     }
     ui->position->setMaximum(maxHash-1);
     ui->position->setValue(m_settings.m_filterChainHash);
     m_settings.m_filterChainHash = ui->position->value();
     applyPosition();
 }
applyPosition()
void LocalSinkGUI::applyPosition () private
Definition at line 321 of file localsinkgui.cpp.
References applyChannelSettings(), arg(), HBFilterChainConverter::convertToString(), displayRateAndShift(), LocalSinkSettings::m_filterChainHash, LocalSinkSettings::m_log2Decim, m_settings, m_shiftFrequencyFactor, and ui.
Referenced by applyDecimation(), and on_position_valueChanged().
 {
     ui->filterChainIndex->setText(tr("%1").arg(m_settings.m_filterChainHash));
     QString s;
     m_shiftFrequencyFactor = HBFilterChainConverter::convertToString(m_settings.m_log2Decim, m_settings.m_filterChainHash, s);
     ui->filterChainText->setText(s);
     displayRateAndShift();
     applyChannelSettings();
 }
applySettings()
void LocalSinkGUI::applySettings (bool force = false) private
Definition at line 159 of file localsinkgui.cpp.
References LocalSink::MsgConfigureLocalSink::create(), ChannelMarker::getColor(), BasebandSampleSink::getInputMessageQueue(), m_channelMarker, m_doApplySettings, m_localSink, m_settings, MessageQueue::push(), and RollupWidget::setTitleColor().
Referenced by deserialize(), LocalSinkGUI(), on_localDevice_currentIndexChanged(), onMenuDialogCalled(), and resetToDefaults().
 {
     if (m_doApplySettings)
     {
         setTitleColor(m_channelMarker.getColor());
         LocalSink::MsgConfigureLocalSink* message = LocalSink::MsgConfigureLocalSink::create(m_settings, force);
         m_localSink->getInputMessageQueue()->push(message);
     }
 }
blockApplySettings()
void LocalSinkGUI::blockApplySettings (bool block) private
Definition at line 154 of file localsinkgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
create()
LocalSinkGUI * LocalSinkGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) static
Definition at line 29 of file localsinkgui.cpp.
References LocalSinkGUI().
Referenced by LocalSinkPlugin::createRxChannelGUI().
 {
     LocalSinkGUI* gui = new LocalSinkGUI(pluginAPI, deviceUISet, channelRx);
     return gui;
 }
deserialize()
bool LocalSinkGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 71 of file localsinkgui.cpp.
References applySettings(), LocalSinkSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void LocalSinkGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 35 of file localsinkgui.cpp.
 {
     delete this;
 }
displayRateAndShift()
void LocalSinkGUI::displayRateAndShift () private
Definition at line 200 of file localsinkgui.cpp.
References arg(), m_channelMarker, LocalSinkSettings::m_log2Decim, m_sampleRate, m_settings, m_shiftFrequencyFactor, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), and ui.
Referenced by applyPosition(), and handleMessage().
 {
     int shift = m_shiftFrequencyFactor * m_sampleRate;
     double channelSampleRate = ((double) m_sampleRate) / (1<<m_settings.m_log2Decim);
     QLocale loc;
     ui->offsetFrequencyText->setText(tr("%1 Hz").arg(loc.toString(shift)));
     ui->channelRateText->setText(tr("%1k").arg(QString::number(channelSampleRate / 1000.0, 'g', 5)));
     m_channelMarker.setCenterFrequency(shift);
     m_channelMarker.setBandwidth(channelSampleRate);
 }
displaySettings()
void LocalSinkGUI::displaySettings () private
Definition at line 181 of file localsinkgui.cpp.
References applyDecimation(), blockApplySettings(), ChannelMarker::getTitle(), m_channelMarker, LocalSinkSettings::m_log2Decim, LocalSinkSettings::m_rgbColor, m_sampleRate, m_settings, LocalSinkSettings::m_title, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setMovable(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by deserialize(), handleMessage(), LocalSinkGUI(), and resetToDefaults().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.setBandwidth(m_sampleRate); // TODO
     m_channelMarker.setMovable(false); // do not let user move the center arbitrarily
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->decimationFactor->setCurrentIndex(m_settings.m_log2Decim);
     applyDecimation();
     blockApplySettings(false);
 }
enterEvent()
void LocalSinkGUI::enterEvent (QEvent *) private
Definition at line 228 of file localsinkgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 LocalSinkGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 50 of file localsinkgui.cpp.
{
     return 0;
 }
getInputMessageQueue()
virtual MessageQueue* LocalSinkGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 56 of file localsinkgui.h.
Referenced by handleSourceMessages(), and LocalSinkGUI().
 { return &m_inputMessageQueue; }
getName()
QString LocalSinkGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 45 of file localsinkgui.cpp.
 {
     return objectName();
 }
handleMessage()
bool LocalSinkGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 83 of file localsinkgui.cpp.
References blockApplySettings(), displayRateAndShift(), displaySettings(), LocalSink::MsgSampleRateNotification::getSampleRate(), LocalSink::MsgConfigureLocalSink::getSettings(), m_sampleRate, m_settings, and Message::match().
Referenced by handleSourceMessages().
 {
     if (LocalSink::MsgSampleRateNotification::match(message))
     {
         LocalSink::MsgSampleRateNotification& notif = (LocalSink::MsgSampleRateNotification&) message;
         //m_channelMarker.setBandwidth(notif.getSampleRate());
         m_sampleRate = notif.getSampleRate();
         displayRateAndShift();
         return true;
     }
     else if (LocalSink::MsgConfigureLocalSink::match(message))
     {
         const LocalSink::MsgConfigureLocalSink& cfg = (LocalSink::MsgConfigureLocalSink&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void LocalSinkGUI::handleSourceMessages () private slot
Definition at line 233 of file localsinkgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by LocalSinkGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void LocalSinkGUI::leaveEvent (QEvent *) private
Definition at line 223 of file localsinkgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_decimationFactor_currentIndexChanged
void LocalSinkGUI::on_decimationFactor_currentIndexChanged (int index) private slot
Definition at line 283 of file localsinkgui.cpp.
References applyDecimation(), LocalSinkSettings::m_log2Decim, and m_settings.
 {
     m_settings.m_log2Decim = index;
     applyDecimation();
 }
on_localDevice_currentIndexChanged
void LocalSinkGUI::on_localDevice_currentIndexChanged (int index) private slot
Definition at line 295 of file localsinkgui.cpp.
References applySettings(), LocalSinkSettings::m_localDeviceIndex, m_settings, and ui.
 {
     m_settings.m_localDeviceIndex = ui->localDevice->itemData(index).toInt();
     applySettings();
 }
on_localDevicesRefresh_clicked
void LocalSinkGUI::on_localDevicesRefresh_clicked (bool checked) private slot
Definition at line 301 of file localsinkgui.cpp.
References updateLocalDevices().
 {
     (void) checked;
     updateLocalDevices();
 }
on_position_valueChanged
void LocalSinkGUI::on_position_valueChanged (int value) private slot
Definition at line 289 of file localsinkgui.cpp.
References applyPosition(), LocalSinkSettings::m_filterChainHash, and m_settings.
 {
     m_settings.m_filterChainHash = value;
     applyPosition();
 }
onMenuDialogCalled
void LocalSinkGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 252 of file localsinkgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, LocalSinkSettings::m_reverseAPIAddress, LocalSinkSettings::m_reverseAPIChannelIndex, LocalSinkSettings::m_reverseAPIDeviceIndex, LocalSinkSettings::m_reverseAPIPort, LocalSinkSettings::m_rgbColor, m_settings, LocalSinkSettings::m_title, LocalSinkSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by LocalSinkGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void LocalSinkGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 246 of file localsinkgui.cpp.
Referenced by LocalSinkGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void LocalSinkGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 59 of file localsinkgui.cpp.
References applySettings(), displaySettings(), m_settings, and LocalSinkSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
serialize()
QByteArray LocalSinkGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 66 of file localsinkgui.cpp.
References m_settings, and LocalSinkSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void LocalSinkGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 54 of file localsinkgui.cpp.
 {
     (void) centerFrequency;
 }
setName()
void LocalSinkGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 40 of file localsinkgui.cpp.
 {
     setObjectName(name);
 }
tick
void LocalSinkGUI::tick () private slot
Definition at line 332 of file localsinkgui.cpp.
References m_tickCount.
 {
     if (++m_tickCount == 20) { // once per second
         m_tickCount = 0;
     }
 }
updateLocalDevices()
void LocalSinkGUI::updateLocalDevices () private
Definition at line 211 of file localsinkgui.cpp.
References arg(), LocalSink::getLocalDevices(), m_localSink, and ui.
Referenced by LocalSinkGUI(), and on_localDevicesRefresh_clicked().
 {
     std::vector<uint32_t> localDevicesIndexes;
     m_localSink->getLocalDevices(localDevicesIndexes);
     ui->localDevice->clear();
     std::vector<uint32_t>::const_iterator it = localDevicesIndexes.begin();
     for (; it != localDevicesIndexes.end(); ++it) {
         ui->localDevice->addItem(tr("%1").arg(*it), QVariant(*it));
     }
 }
Member Data Documentation
m_channelMarker
ChannelMarker LocalSinkGUI::m_channelMarker private
Definition at line 63 of file localsinkgui.h.
Referenced by applySettings(), displayRateAndShift(), displaySettings(), enterEvent(), leaveEvent(), LocalSinkGUI(), and onMenuDialogCalled().
m_deviceCenterFrequency
quint64 LocalSinkGUI::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 66 of file localsinkgui.h.
m_deviceUISet
DeviceUISet* LocalSinkGUI::m_deviceUISet private
Definition at line 62 of file localsinkgui.h.
Referenced by LocalSinkGUI(), and ~LocalSinkGUI().
m_doApplySettings
bool LocalSinkGUI::m_doApplySettings private
Definition at line 68 of file localsinkgui.h.
Referenced by applyChannelSettings(), applySettings(), and blockApplySettings().
m_inputMessageQueue
MessageQueue LocalSinkGUI::m_inputMessageQueue private
Definition at line 71 of file localsinkgui.h.
m_localSink
LocalSink* LocalSinkGUI::m_localSink private
Definition at line 70 of file localsinkgui.h.
Referenced by applyChannelSettings(), applySettings(), LocalSinkGUI(), updateLocalDevices(), and ~LocalSinkGUI().
m_pluginAPI
PluginAPI* LocalSinkGUI::m_pluginAPI private
Definition at line 61 of file localsinkgui.h.
m_sampleRate
int LocalSinkGUI::m_sampleRate private
Definition at line 65 of file localsinkgui.h.
Referenced by displayRateAndShift(), displaySettings(), and handleMessage().
m_settings
LocalSinkSettings LocalSinkGUI::m_settings private
Definition at line 64 of file localsinkgui.h.
Referenced by applyChannelSettings(), applyDecimation(), applyPosition(), applySettings(), deserialize(), displayRateAndShift(), displaySettings(), handleMessage(), LocalSinkGUI(), on_decimationFactor_currentIndexChanged(), on_localDevice_currentIndexChanged(), on_position_valueChanged(), onMenuDialogCalled(), resetToDefaults(), and serialize().
m_shiftFrequencyFactor
double LocalSinkGUI::m_shiftFrequencyFactor private
Channel frequency shift factor.
Definition at line 67 of file localsinkgui.h.
Referenced by applyPosition(), and displayRateAndShift().
m_tickCount
uint32_t LocalSinkGUI::m_tickCount private
Definition at line 74 of file localsinkgui.h.
Referenced by tick().
m_time
QTime LocalSinkGUI::m_time private
Definition at line 73 of file localsinkgui.h.
Referenced by LocalSinkGUI().
ui
Ui::LocalSinkGUI* LocalSinkGUI::ui private
Definition at line 60 of file localsinkgui.h.
Referenced by applyDecimation(), applyPosition(), displayRateAndShift(), displaySettings(), LocalSinkGUI(), on_localDevice_currentIndexChanged(), updateLocalDevices(), and ~LocalSinkGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/localsink/localsinkgui.h
plugins/channelrx/localsink/localsinkgui.cpp