SDRAngel: ATVMod::MsgConfigureATVMod Class Reference
ATVMod::MsgConfigureATVMod Class Reference
#include <atvmod.h>
Public Member Functions
const ATVModSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureATVMod * create (const ATVModSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureATVMod (const ATVModSettings &settings, bool force)
Private Attributes
ATVModSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 53 of file atvmod.h.
Constructor & Destructor Documentation
MsgConfigureATVMod()
ATVMod::MsgConfigureATVMod::MsgConfigureATVMod (const ATVModSettings & settings, bool force) inline private
Definition at line 69 of file atvmod.h.
Referenced by create().
                                                                        :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureATVMod* ATVMod::MsgConfigureATVMod::create (const ATVModSettings & settings, bool force) inline static
Definition at line 60 of file atvmod.h.
References MsgConfigureATVMod().
Referenced by ATVModGUI::applySettings(), ATVMod::deserialize(), and ATVMod::webapiSettingsPutPatch().
         {
             return new MsgConfigureATVMod(settings, force);
         }
getForce()
bool ATVMod::MsgConfigureATVMod::getForce () const inline
Definition at line 58 of file atvmod.h.
References m_force.
Referenced by ATVMod::handleMessage().
 { return m_force; }
getSettings()
const ATVModSettings& ATVMod::MsgConfigureATVMod::getSettings () const inline
Definition at line 57 of file atvmod.h.
References m_settings.
Referenced by ATVModGUI::handleMessage(), and ATVMod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool ATVMod::MsgConfigureATVMod::m_force private
Definition at line 67 of file atvmod.h.
Referenced by getForce().
m_settings
ATVModSettings ATVMod::MsgConfigureATVMod::m_settings private
Definition at line 66 of file atvmod.h.
Referenced by ATVMod::getCenterFrequency(), getSettings(), ATVMod::getStreamCenterFrequency(), and ATVMod::getTitle().
The documentation for this class was generated from the following file:
plugins/channeltx/modatv/atvmod.h