SDRAngel: ScopeVisXY Class Reference
ScopeVisXY Class Reference
#include <scopevisxy.h>
Public Member Functions
ScopeVisXY (TVScreen *tvScreen)
virtual ~ScopeVisXY ()
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool positiveOnly)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &message)
Processing of a message. Returns true if message has actually been processed.
void setScale (float scale)
void setStroke (int stroke)
void setDecay (int decay)
void setPixelsPerFrame (int pixelsPerFrame)
void setPlotRGB (const QRgb &plotRGB)
void setGridRGB (const QRgb &gridRGB)
void addGraticulePoint (const std::complex< float > &z)
void calculateGraticule (int rows, int cols)
void clearGraticule ()
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Private Member Functions
void drawGraticule ()
Private Attributes
TVScreen * m_tvScreen
float m_scale
int m_cols
int m_rows
int m_pixelsPerFrame
int m_pixelCount
int m_alphaTrace
this is the stroke value [0:255]
int m_alphaReset
alpha channel of screen blanking (blackening) is 255 minus decay value [0:255]
QRgb m_plotRGB
QRgb m_gridRGB
std::vector< std::complex< float > > m_graticule
std::vector< int > m_graticuleRows
std::vector< int > m_graticuleCols
Additional Inherited Members
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 32 of file scopevisxy.h.
Constructor & Destructor Documentation
ScopeVisXY()
ScopeVisXY::ScopeVisXY (TVScreen * tvScreen)
Definition at line 25 of file scopevisxy.cpp.
References m_pixelsPerFrame, m_tvScreen, TVScreen::setAlphaBlend(), and setPixelsPerFrame().
                                          :
     m_tvScreen(tvScreen),
     m_scale(1.0),
     m_cols(0),
     m_rows(0),
     m_pixelsPerFrame(480),
     m_pixelCount(0),
     m_alphaTrace(128),
     m_alphaReset(128),
     m_plotRGB(qRgb(0, 255, 0)),
     m_gridRGB(qRgb(255, 255 ,255))
 {
     setObjectName("ScopeVisXY");
     setPixelsPerFrame(m_pixelsPerFrame);
     m_tvScreen->setAlphaBlend(true);
 }
~ScopeVisXY()
ScopeVisXY::~ScopeVisXY () virtual
Definition at line 42 of file scopevisxy.cpp.
 {
 }
Member Function Documentation
addGraticulePoint()
void ScopeVisXY::addGraticulePoint (const std::complex< float > & z)
Definition at line 111 of file scopevisxy.cpp.
References m_graticule.
Referenced by DSDDemodGUI::DSDDemodGUI().
{
     m_graticule.push_back(z);
 }
calculateGraticule()
void ScopeVisXY::calculateGraticule (int rows, int cols)
Definition at line 119 of file scopevisxy.cpp.
References m_graticule, m_graticuleCols, and m_graticuleRows.
Referenced by DSDDemodGUI::DSDDemodGUI(), and feed().
 {
     m_graticuleRows.clear();
     m_graticuleCols.clear();
     std::vector<std::complex<float> >::const_iterator grIt = m_graticule.begin();
     for (; grIt != m_graticule.end(); ++grIt)
     {
         int y = rows * ((1.0 - grIt->imag()) / 2.0);
         int x = cols * ((1.0 + grIt->real()) / 2.0);
         for (int d = -4; d <= 4; ++d)
         {
             m_graticuleRows.push_back(y+d);
             m_graticuleCols.push_back(x);
             m_graticuleRows.push_back(y);
             m_graticuleCols.push_back(x+d);
         }
     }
 }
clearGraticule()
void ScopeVisXY::clearGraticule ()
Definition at line 115 of file scopevisxy.cpp.
References m_graticule.
{
     m_graticule.clear();
 }
drawGraticule()
void ScopeVisXY::drawGraticule () private
Definition at line 141 of file scopevisxy.cpp.
References m_graticuleCols, m_graticuleRows, m_gridRGB, m_tvScreen, TVScreen::selectRow(), and TVScreen::setDataColor().
Referenced by feed().
 {
     std::vector<int>::const_iterator rowIt = m_graticuleRows.begin();
     std::vector<int>::const_iterator colIt = m_graticuleCols.begin();
     for(; (rowIt != m_graticuleRows.end()) && (colIt != m_graticuleCols.end()); ++rowIt, ++colIt)
     {
         m_tvScreen->selectRow(*rowIt);
         m_tvScreen->setDataColor(*colIt, qRed(m_gridRGB), qGreen(m_gridRGB), qBlue(m_gridRGB));
     }
 }
feed()
void ScopeVisXY::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool positiveOnly) virtual
Implements BasebandSampleSink.
Definition at line 53 of file scopevisxy.cpp.
References calculateGraticule(), drawGraticule(), TVScreen::getSize(), m_alphaReset, m_alphaTrace, m_cols, m_pixelCount, m_pixelsPerFrame, m_plotRGB, m_rows, m_scale, m_tvScreen, TVScreen::renderImage(), TVScreen::resetImage(), SDR_RX_SCALEF, TVScreen::selectRow(), and TVScreen::setDataColor().
 {
     (void) positiveOnly;
     SampleVector::const_iterator begin(cbegin);
     while (begin < end)
     {
         float x = m_scale * (begin->m_real/SDR_RX_SCALEF);
         float y = m_scale * (begin->m_imag/SDR_RX_SCALEF);
         int row = m_rows * ((1.0 - y) / 2.0);
         int col = m_cols * ((1.0 + x) / 2.0);
         row = row < 0 ? 0 : row >= m_rows ? m_rows-1 : row;
         col = col < 0 ? 0 : col >= m_cols ? m_cols-1 : col;
         m_tvScreen->selectRow(row);
         m_tvScreen->setDataColor(col, qRed(m_plotRGB), qGreen(m_plotRGB), qBlue(m_plotRGB), m_alphaTrace);
         ++begin;
         m_pixelCount++;
         if (m_pixelCount == m_pixelsPerFrame)
         {
             int rows, cols;
             m_tvScreen->getSize(rows, cols);
             if ((rows != m_rows) || (cols != m_cols))
             {
                 calculateGraticule(rows, cols);
                 m_rows = rows;
                 m_cols = cols;
             }
             m_tvScreen->renderImage(0);
             m_tvScreen->update();
             std::this_thread::sleep_for(std::chrono::microseconds(5000));
             m_tvScreen->resetImage(m_alphaReset);
             drawGraticule();
             m_pixelCount = 0;
         }
     }
 }
handleMessage()
bool ScopeVisXY::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 105 of file scopevisxy.cpp.
 {
     (void) message;
     return false;
 }
setDecay()
void ScopeVisXY::setDecay (int decay) inline
Definition at line 44 of file scopevisxy.h.
Referenced by DSDDemodGUI::displaySettings(), and DSDDemodGUI::on_traceDecay_valueChanged().
 { m_alphaReset = 255 - decay; }
setGridRGB()
void ScopeVisXY::setGridRGB (const QRgb & gridRGB) inline
Definition at line 48 of file scopevisxy.h.
Referenced by DSDDemodGUI::DSDDemodGUI().
 { m_gridRGB = gridRGB; }
setPixelsPerFrame()
void ScopeVisXY::setPixelsPerFrame (int pixelsPerFrame)
Definition at line 46 of file scopevisxy.cpp.
References m_pixelCount, m_pixelsPerFrame, m_tvScreen, and TVScreen::setAlphaReset().
Referenced by DSDDemodGUI::displaySettings(), DSDDemodGUI::DSDDemodGUI(), DSDDemodGUI::on_traceLength_valueChanged(), and ScopeVisXY().
 {
    m_pixelsPerFrame = pixelsPerFrame;
    m_pixelCount = 0;
    m_tvScreen->setAlphaReset();
 }
setPlotRGB()
void ScopeVisXY::setPlotRGB (const QRgb & plotRGB) inline
Definition at line 47 of file scopevisxy.h.
Referenced by DSDDemodGUI::DSDDemodGUI().
 { m_plotRGB = plotRGB; }
setScale()
void ScopeVisXY::setScale (float scale) inline
Definition at line 42 of file scopevisxy.h.
Referenced by DSDDemodGUI::DSDDemodGUI().
 { m_scale = scale; }
setStroke()
void ScopeVisXY::setStroke (int stroke) inline
Definition at line 43 of file scopevisxy.h.
Referenced by DSDDemodGUI::displaySettings(), and DSDDemodGUI::on_traceStroke_valueChanged().
 { m_alphaTrace = stroke; }
start()
void ScopeVisXY::start () virtual
Implements BasebandSampleSink.
Definition at line 97 of file scopevisxy.cpp.
 {
 }
stop()
void ScopeVisXY::stop () virtual
Implements BasebandSampleSink.
Definition at line 101 of file scopevisxy.cpp.
 {
 }
Member Data Documentation
m_alphaReset
int ScopeVisXY::m_alphaReset private
alpha channel of screen blanking (blackening) is 255 minus decay value [0:255]
Definition at line 64 of file scopevisxy.h.
Referenced by feed().
m_alphaTrace
int ScopeVisXY::m_alphaTrace private
this is the stroke value [0:255]
Definition at line 63 of file scopevisxy.h.
Referenced by feed().
m_cols
int ScopeVisXY::m_cols private
Definition at line 59 of file scopevisxy.h.
Referenced by feed().
m_graticule
std::vector<std::complex<float> > ScopeVisXY::m_graticule private
Definition at line 67 of file scopevisxy.h.
Referenced by addGraticulePoint(), calculateGraticule(), and clearGraticule().
m_graticuleCols
std::vector<int> ScopeVisXY::m_graticuleCols private
Definition at line 69 of file scopevisxy.h.
Referenced by calculateGraticule(), and drawGraticule().
m_graticuleRows
std::vector<int> ScopeVisXY::m_graticuleRows private
Definition at line 68 of file scopevisxy.h.
Referenced by calculateGraticule(), and drawGraticule().
m_gridRGB
QRgb ScopeVisXY::m_gridRGB private
Definition at line 66 of file scopevisxy.h.
Referenced by drawGraticule().
m_pixelCount
int ScopeVisXY::m_pixelCount private
Definition at line 62 of file scopevisxy.h.
Referenced by feed(), and setPixelsPerFrame().
m_pixelsPerFrame
int ScopeVisXY::m_pixelsPerFrame private
Definition at line 61 of file scopevisxy.h.
Referenced by feed(), ScopeVisXY(), and setPixelsPerFrame().
m_plotRGB
QRgb ScopeVisXY::m_plotRGB private
Definition at line 65 of file scopevisxy.h.
Referenced by feed().
m_rows
int ScopeVisXY::m_rows private
Definition at line 60 of file scopevisxy.h.
Referenced by feed().
m_scale
float ScopeVisXY::m_scale private
Definition at line 58 of file scopevisxy.h.
Referenced by feed().
m_tvScreen
TVScreen* ScopeVisXY::m_tvScreen private
Definition at line 57 of file scopevisxy.h.
Referenced by drawGraticule(), feed(), ScopeVisXY(), and setPixelsPerFrame().
The documentation for this class was generated from the following files:
sdrgui/dsp/scopevisxy.h
sdrgui/dsp/scopevisxy.cpp