SDRAngel: AirspyThread Class Reference
AirspyThread Class Reference
#include <airspythread.h>
Inherits QThread.
Public Member Functions
AirspyThread (struct airspy_device *dev, SampleSinkFifo *sampleFifo, QObject *parent=NULL)
~AirspyThread ()
void startWork ()
void stopWork ()
void setSamplerate (uint32_t samplerate)
void setLog2Decimation (unsigned int log2_decim)
void setFcPos (int fcPos)
Private Member Functions
void run ()
void callback (const qint16 *buf, qint32 len)
Static Private Member Functions
static int rx_callback (airspy_transfer_t *transfer)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
struct airspy_device * m_dev
qint16 m_buf [2 *AIRSPY_BLOCKSIZE]
SampleVector m_convertBuffer
SampleSinkFifo * m_sampleFifo
int m_samplerate
unsigned int m_log2Decim
int m_fcPos
Decimators< qint32, qint16, SDR_RX_SAMP_SZ, 12 > m_decimators
Static Private Attributes
static AirspyThread * m_this = 0
Detailed Description
Definition at line 31 of file airspythread.h.
Constructor & Destructor Documentation
AirspyThread()
AirspyThread::AirspyThread (struct airspy_device * dev, SampleSinkFifo * sampleFifo, QObject * parent = NULL)
Definition at line 28 of file airspythread.cpp.
References AIRSPY_BLOCKSIZE, m_buf, and m_this.
                                                                                                  :
     QThread(parent),
     m_running(false),
     m_dev(dev),
     m_convertBuffer(AIRSPY_BLOCKSIZE),
     m_sampleFifo(sampleFifo),
     m_samplerate(10),
     m_log2Decim(0),
     m_fcPos(0)
 {
     m_this = this;
     std::fill(m_buf, m_buf + 2*AIRSPY_BLOCKSIZE, 0);
 }
~AirspyThread()
AirspyThread::~AirspyThread ()
Definition at line 42 of file airspythread.cpp.
References m_this, and stopWork().
 {
     stopWork();
     m_this = 0;
 }
Member Function Documentation
callback()
void AirspyThread::callback (const qint16 * buf, qint32 len) private
Definition at line 115 of file airspythread.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup(), m_convertBuffer, m_decimators, m_fcPos, m_log2Decim, m_sampleFifo, and SampleSinkFifo::write().
Referenced by rx_callback().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     if (m_log2Decim == 0)
     {
         m_decimators.decimate1(&it, buf, len);
     }
     else
     {
         if (m_fcPos == 0) // Infra
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_inf(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_inf(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_inf(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_inf(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_inf(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_inf(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 1) // Supra
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_sup(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_sup(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_sup(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_sup(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_sup(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_sup(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 2) // Center
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_cen(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_cen(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_cen(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_cen(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_cen(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_cen(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
     }
     m_sampleFifo->write(m_convertBuffer.begin(), it);
 }
run()
void AirspyThread::run () private
Definition at line 79 of file airspythread.cpp.
References m_dev, m_running, m_startWaiter, and rx_callback().
 {
     airspy_error rc;
     m_running = true;
     m_startWaiter.wakeAll();
     rc = (airspy_error) airspy_start_rx(m_dev, rx_callback, NULL);
     if (rc != AIRSPY_SUCCESS)
     {
         qCritical("AirspyThread::run: failed to start Airspy Rx: %s", airspy_error_name(rc));
     }
     else
     {
         while ((m_running) && (airspy_is_streaming(m_dev) == AIRSPY_TRUE))
         {
             sleep(1);
         }
     }
     rc = (airspy_error) airspy_stop_rx(m_dev);
     if (rc == AIRSPY_SUCCESS)
     {
         qDebug("AirspyThread::run: stopped Airspy Rx");
     }
     else
     {
         qDebug("AirspyThread::run: failed to stop Airspy Rx: %s", airspy_error_name(rc));
     }
     m_running = false;
 }
rx_callback()
int AirspyThread::rx_callback (airspy_transfer_t * transfer) static private
Definition at line 209 of file airspythread.cpp.
References callback(), and m_this.
Referenced by run().
 {
     qint32 bytes_to_write = transfer->sample_count * sizeof(qint16);
     m_this->callback((qint16 *) transfer->samples, bytes_to_write);
     return 0;
 }
setFcPos()
void AirspyThread::setFcPos (int fcPos)
Definition at line 74 of file airspythread.cpp.
References m_fcPos.
Referenced by AirspyInput::applySettings(), and AirspyInput::start().
 {
     m_fcPos = fcPos;
 }
setLog2Decimation()
void AirspyThread::setLog2Decimation (unsigned int log2_decim)
Definition at line 69 of file airspythread.cpp.
References m_log2Decim.
Referenced by AirspyInput::applySettings(), and AirspyInput::start().
 {
     m_log2Decim = log2_decim;
 }
setSamplerate()
void AirspyThread::setSamplerate (uint32_t samplerate)
Definition at line 64 of file airspythread.cpp.
References m_samplerate.
Referenced by AirspyInput::applySettings(), and AirspyInput::start().
 {
     m_samplerate = samplerate;
 }
startWork()
void AirspyThread::startWork ()
Definition at line 48 of file airspythread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by AirspyInput::start().
 {
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void AirspyThread::stopWork ()
Definition at line 57 of file airspythread.cpp.
References m_running.
Referenced by AirspyInput::stop(), and ~AirspyThread().
 {
     qDebug("AirspyThread::stopWork");
     m_running = false;
     wait();
 }
Member Data Documentation
m_buf
qint16 AirspyThread::m_buf[2 *AIRSPY_BLOCKSIZE] private
Definition at line 50 of file airspythread.h.
Referenced by AirspyThread().
m_convertBuffer
SampleVector AirspyThread::m_convertBuffer private
Definition at line 51 of file airspythread.h.
Referenced by callback().
m_decimators
Decimators<qint32, qint16, SDR_RX_SAMP_SZ, 12> AirspyThread::m_decimators private
Definition at line 59 of file airspythread.h.
Referenced by callback().
m_dev
struct airspy_device* AirspyThread::m_dev private
Definition at line 49 of file airspythread.h.
Referenced by run().
m_fcPos
int AirspyThread::m_fcPos private
Definition at line 56 of file airspythread.h.
Referenced by callback(), and setFcPos().
m_log2Decim
unsigned int AirspyThread::m_log2Decim private
Definition at line 55 of file airspythread.h.
Referenced by callback(), and setLog2Decimation().
m_running
bool AirspyThread::m_running private
Definition at line 47 of file airspythread.h.
Referenced by run(), startWork(), and stopWork().
m_sampleFifo
SampleSinkFifo* AirspyThread::m_sampleFifo private
Definition at line 52 of file airspythread.h.
Referenced by callback().
m_samplerate
int AirspyThread::m_samplerate private
Definition at line 54 of file airspythread.h.
Referenced by setSamplerate().
m_startWaiter
QWaitCondition AirspyThread::m_startWaiter private
Definition at line 46 of file airspythread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex AirspyThread::m_startWaitMutex private
Definition at line 45 of file airspythread.h.
Referenced by startWork().
m_this
AirspyThread * AirspyThread::m_this = 0 static private
Definition at line 57 of file airspythread.h.
Referenced by AirspyThread(), rx_callback(), and ~AirspyThread().
The documentation for this class was generated from the following files:
plugins/samplesource/airspy/airspythread.h
plugins/samplesource/airspy/airspythread.cpp