SDRAngel: HackRFInput::MsgConfigureHackRF Class Reference
HackRFInput::MsgConfigureHackRF Class Reference
#include <hackrfinput.h>
Public Member Functions
const HackRFInputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureHackRF * create (const HackRFInputSettings &settings, bool force=false)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureHackRF (const HackRFInputSettings &settings, bool force)
Private Attributes
HackRFInputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 41 of file hackrfinput.h.
Constructor & Destructor Documentation
MsgConfigureHackRF()
HackRFInput::MsgConfigureHackRF::MsgConfigureHackRF (const HackRFInputSettings & settings, bool force) inline private
Definition at line 57 of file hackrfinput.h.
Referenced by create().
                                                                             :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureHackRF* HackRFInput::MsgConfigureHackRF::create (const HackRFInputSettings & settings, bool force = false) inline static
Definition at line 48 of file hackrfinput.h.
References MsgConfigureHackRF().
Referenced by HackRFInput::deserialize(), HackRFInput::handleMessage(), HackRFInput::setCenterFrequency(), HackRFInputGui::updateHardware(), and HackRFInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureHackRF(settings, force);
         }
getForce()
bool HackRFInput::MsgConfigureHackRF::getForce () const inline
Definition at line 46 of file hackrfinput.h.
References m_force.
Referenced by HackRFInput::handleMessage().
 { return m_force; }
getSettings()
const HackRFInputSettings& HackRFInput::MsgConfigureHackRF::getSettings () const inline
Definition at line 45 of file hackrfinput.h.
References m_settings.
Referenced by HackRFInputGui::handleMessage(), and HackRFInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool HackRFInput::MsgConfigureHackRF::m_force private
Definition at line 55 of file hackrfinput.h.
Referenced by getForce().
m_settings
HackRFInputSettings HackRFInput::MsgConfigureHackRF::m_settings private
Definition at line 54 of file hackrfinput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/hackrfinput/hackrfinput.h