SDRAngel: leansdr::simple_agc< T > Struct Template Reference
leansdr::simple_agc< T > Struct Template Reference
#include <sdr.h>
Public Member Functions
simple_agc (scheduler *sch, pipebuf< complex< T >> &_in, pipebuf< complex< T >> &_out)
Public Member Functions inherited from leansdr::runnable
runnable (scheduler *_sch, const char *name)
Public Member Functions inherited from leansdr::runnable_common
runnable_common (const char *_name)
virtual ~runnable_common ()
virtual void shutdown ()
Public Attributes
float out_rms
float bw
float estimated
Public Attributes inherited from leansdr::runnable_common
const char * name
Static Public Attributes
static const int chunk_size = 128
Private Member Functions
void run ()
Private Attributes
pipereader< complex< T > > in
pipewriter< complex< T > > out
Additional Inherited Members
Protected Attributes inherited from leansdr::runnable
scheduler * sch
Detailed Description
template<typename T>
struct leansdr::simple_agc< T >
Definition at line 328 of file sdr.h.
Constructor & Destructor Documentation
simple_agc()
template<typename T > leansdr::simple_agc< T >::simple_agc (scheduler * sch, pipebuf< complex< T >> & _in, pipebuf< complex< T >> & _out) inline
Definition at line 335 of file sdr.h.
                                           : runnable(sch, "AGC"),
                                             out_rms(1),
                                             bw(0.001),
                                             estimated(0),
                                             in(_in),
                                             out(_out, chunk_size)
     {
     }
Member Function Documentation
run()
template<typename T > void leansdr::simple_agc< T >::run () inline private virtual
Reimplemented from leansdr::runnable_common.
Definition at line 350 of file sdr.h.
References leansdr::auto_notch< T >::gain, leansdr::complex< T >::im, leansdr::pipereader< T >::rd(), leansdr::complex< T >::re, leansdr::pipereader< T >::read(), leansdr::pipereader< T >::readable(), leansdr::pipewriter< T >::wr(), leansdr::pipewriter< T >::writable(), and leansdr::pipewriter< T >::written().
     {
         while (in.readable() >= chunk_size && out.writable() >= chunk_size)
         {
             complex<T> *pin = in.rd(), *pend = pin + chunk_size;
             float amp2 = 0;
             for (; pin < pend; ++pin)
                 amp2 += pin->re * pin->re + pin->im * pin->im;
             amp2 /= chunk_size;
             if (!estimated)
                 estimated = amp2;
             estimated = estimated * (1 - bw) + amp2 * bw;
             float gain = estimated ? out_rms / sqrtf(estimated) : 0;
             pin = in.rd();
             complex<T> *pout = out.wr();
             float bwcomp = 1 - bw;
             for (; pin < pend; ++pin, ++pout)
             {
                 pout->re = pin->re * gain;
                 pout->im = pin->im * gain;
             }
             in.read(chunk_size);
             out.written(chunk_size);
         }
     }
Member Data Documentation
bw
template<typename T > float leansdr::simple_agc< T >::bw
Definition at line 331 of file sdr.h.
chunk_size
template<typename T > const int leansdr::simple_agc< T >::chunk_size = 128 static
Definition at line 333 of file sdr.h.
estimated
template<typename T > float leansdr::simple_agc< T >::estimated
Definition at line 332 of file sdr.h.
in
template<typename T > pipereader<complex<T> > leansdr::simple_agc< T >::in private
Definition at line 347 of file sdr.h.
out
template<typename T > pipewriter<complex<T> > leansdr::simple_agc< T >::out private
Definition at line 348 of file sdr.h.
out_rms
template<typename T > float leansdr::simple_agc< T >::out_rms
Definition at line 330 of file sdr.h.
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/sdr.h