SDRAngel: leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE > Struct Template Reference
leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE > Struct Template Reference
#include <dvbs2.h>
Public Member Functions
s2_deinterleaver (scheduler *sch, pipebuf< plslot< SOFTSYMB >> &_in, pipebuf< fecframe< SOFTBYTE >> &_out)
void run ()
Public Member Functions inherited from leansdr::runnable
runnable (scheduler *_sch, const char *name)
Public Member Functions inherited from leansdr::runnable_common
runnable_common (const char *_name)
virtual ~runnable_common ()
virtual void shutdown ()
Static Private Member Functions
static void deserialize_qpsk (plslot< SOFTSYMB > *pin, int nslots, SOFTBYTE *pout)
static void deinterleave (int bps, int rows, const plslot< SOFTSYMB > *pin, int nslots, bool msb_first, SOFTBYTE *pout)
template<int MSB_FIRST, int BPS>
static void deinterleave (int rows, const plslot< SOFTSYMB > *pin, int nslots, SOFTBYTE *pout)
static void deinterleave4050 (const plslot< SOFTSYMB > *pin, int nslots, SOFTBYTE *pout)
static void split_symbol (const llr_ss &ps, int bps, hard_sb accs[], int nacc, bool msb_first)
template<int MSB_FIRST, int BPS>
static void split_symbol (const llr_ss &ps, hard_sb accs[], int nacc)
static void split_symbol (const llr_ss &ps, int bps, llr_sb accs[], int nacc, bool msb_first)
template<int MSB_FIRST, int BPS>
static void split_symbol (const llr_ss &ps, llr_sb accs[], int nacc)
static void pack_qpsk_symbol (const llr_ss &ps, hard_sb *acc, int nacc)
static void pack_qpsk_symbol (const llr_ss &ps, llr_sb *acc, int nacc)
Private Attributes
pipereader< plslot< SOFTSYMB > > in
pipewriter< fecframe< SOFTBYTE > > out
Additional Inherited Members
Public Attributes inherited from leansdr::runnable_common
const char * name
Protected Attributes inherited from leansdr::runnable
scheduler * sch
Detailed Description
template<typename SOFTSYMB, typename SOFTBYTE>
struct leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >
Definition at line 1559 of file dvbs2.h.
Constructor & Destructor Documentation
s2_deinterleaver()
template<typename SOFTSYMB, typename SOFTBYTE> leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::s2_deinterleaver (scheduler * sch, pipebuf< plslot< SOFTSYMB >> & _in, pipebuf< fecframe< SOFTBYTE >> & _out) inline
Definition at line 1561 of file dvbs2.h.
         : runnable(sch, "S2 deinterleaver"),
           in(_in), out(_out)
     {
     }
Member Function Documentation
deinterleave() [1/2]
template<typename SOFTSYMB, typename SOFTBYTE> static void leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deinterleave (int bps, int rows, const plslot< SOFTSYMB > * pin, int nslots, bool msb_first, SOFTBYTE * pout) inline static private
Definition at line 1652 of file dvbs2.h.
References leansdr::fail().
     {
         void (*func)(int rows, const plslot<SOFTSYMB> *pin, int nslots,
                      SOFTBYTE *pout) = 0;
         if (msb_first)
             switch (bps)
             {
             case 2:
                 func = deinterleave<1, 2>;
                 break;
             case 3:
                 func = deinterleave<1, 3>;
                 break;
             case 4:
                 func = deinterleave<1, 4>;
                 break;
             case 5:
                 func = deinterleave<1, 5>;
                 break;
             default:
                 fail("Bad bps");
             }
         else
             switch (bps)
             {
             case 2:
                 func = deinterleave<0, 2>;
                 break;
             case 3:
                 func = deinterleave<0, 3>;
                 break;
             case 4:
                 func = deinterleave<0, 4>;
                 break;
             case 5:
                 func = deinterleave<0, 5>;
                 break;
             default:
                 fail("Bad bps");
             }
         (*func)(rows, pin, nslots, pout);
     }
deinterleave() [2/2]
template<typename SOFTSYMB, typename SOFTBYTE> template<int MSB_FIRST, int BPS> static void leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deinterleave (int rows, const plslot< SOFTSYMB > * pin, int nslots, SOFTBYTE * pout) inline static private
Definition at line 1698 of file dvbs2.h.
References leansdr::fail(), leansdr::fatal(), leansdr::plslot< SOFTSYMB >::LENGTH, leansdr::softword_clear(), and leansdr::plslot< SOFTSYMB >::symbols.
     {
         if (BPS == 4 && rows == 4050 && MSB_FIRST)
             return deinterleave4050(pin, nslots, pout);
         if (rows % 8)
             fatal("modcod/framesize combination not supported\n");
         int stride = rows / 8; // Offset to next column, in bytes
         SOFTBYTE accs[BPS];
         for (int b = 0; b < BPS; ++b)
             softword_clear(&accs[b]); // gcc warning
         int nacc = 0;
         for (; nslots; --nslots, ++pin)
         {
             const SOFTSYMB *ps = pin->symbols;
             for (int ns = pin->LENGTH; ns--; ++ps)
             {
                 split_symbol(*ps, BPS, accs, nacc, MSB_FIRST);
                 ++nacc;
                 if (nacc == 8)
                 { // TBD Unroll, same as interleave()
                     SOFTBYTE *po = pout;
                     // TBD Pass stride as template parameter.
                     for (int b = 0; b < BPS; ++b, po += stride)
                         *po = accs[b];
                     ++pout;
                     nacc = 0;
                 }
             }
         }
         if (nacc)
             fail("Bug: s2_deinterleaver");
     }
deinterleave4050()
template<typename SOFTSYMB, typename SOFTBYTE> static void leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deinterleave4050 (const plslot< SOFTSYMB > * pin, int nslots, SOFTBYTE * pout) inline static private
Definition at line 1736 of file dvbs2.h.
References leansdr::fatal(), leansdr::plslot< SOFTSYMB >::LENGTH, leansdr::softword_clear(), leansdr::softword_get(), leansdr::softwords_set(), and leansdr::plslot< SOFTSYMB >::symbols.
     {
         const int rows = 4050;
         SOFTBYTE accs[4];
         for (int b = 0; b < 4; ++b)
             softword_clear(&accs[b]); // gcc warning
         int nacc = 0;
         for (; nslots; --nslots, ++pin)
         {
             const SOFTSYMB *ps = pin->symbols;
             for (int ns = pin->LENGTH; ns--; ++ps)
             {
                 split_symbol(*ps, 4, accs, nacc, true);
                 ++nacc;
                 if (nacc == 8)
                 {
                     for (int b = 0; b < 8; ++b)
                     {
                         softwords_set(pout, rows * 0 + b, softword_get(accs[0], b));
                         softwords_set(pout, rows * 1 + b, softword_get(accs[1], b));
                         softwords_set(pout, rows * 2 + b, softword_get(accs[2], b));
                         softwords_set(pout, rows * 3 + b, softword_get(accs[3], b));
                     }
                     ++pout;
                     nacc = 0;
                 }
             }
         }
         if (nacc != 2)
             fatal("Bug: Expected 2 leftover rows\n");
         // Pad with random symbol so that we can use accs[].
         for (int b = nacc; b < 8; ++b)
             split_symbol(pin->symbols[0], 4, accs, b, true);
         for (int b = 0; b < nacc; ++b)
         {
             softwords_set(pout, rows * 0 + b, softword_get(accs[0], b));
             softwords_set(pout, rows * 1 + b, softword_get(accs[1], b));
             softwords_set(pout, rows * 2 + b, softword_get(accs[2], b));
             softwords_set(pout, rows * 3 + b, softword_get(accs[3], b));
         }
     }
deserialize_qpsk()
template<typename SOFTSYMB, typename SOFTBYTE> static void leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deserialize_qpsk (plslot< SOFTSYMB > * pin, int nslots, SOFTBYTE * pout) inline static private
Definition at line 1601 of file dvbs2.h.
References leansdr::fail(), leansdr::fatal(), leansdr::plslot< SOFTSYMB >::LENGTH, leansdr::softword_clear(), and leansdr::plslot< SOFTSYMB >::symbols.
     {
         SOFTBYTE acc;
         softword_clear(&acc); // gcc warning
         int nacc = 0;
         for (; nslots; --nslots, ++pin)
         {
             SOFTSYMB *ps = pin->symbols;
             for (int ns = pin->LENGTH; ns--; ++ps)
             {
                 pack_qpsk_symbol(*ps, &acc, nacc);
                 nacc += 2;
                 if (nacc == 8)
                 { // TBD unroll
                     *pout++ = acc;
                     nacc = 0;
                 }
             }
         }
     }
pack_qpsk_symbol() [1/2]
template<typename SOFTSYMB, typename SOFTBYTE> static void leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::pack_qpsk_symbol (const llr_ss & ps, hard_sb * acc, int nacc) inline static private
Definition at line 1847 of file dvbs2.h.
References leansdr::llr_ss::bits, and leansdr::llr_harden().
     {
         // TBD Must match LLR law, see softsymb_harden.
         uint8_t s = llr_harden(ps.bits[0]) | (llr_harden(ps.bits[1]) << 1);
         *acc = (*acc << 2) | s;
     }
pack_qpsk_symbol() [2/2]
template<typename SOFTSYMB, typename SOFTBYTE> static void leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::pack_qpsk_symbol (const llr_ss & ps, llr_sb * acc, int nacc) inline static private
Definition at line 1856 of file dvbs2.h.
References leansdr::llr_sb::bits, and leansdr::llr_ss::bits.
     {
         acc->bits[nacc] = ps.bits[1];
         acc->bits[nacc + 1] = ps.bits[0];
     }
run()
template<typename SOFTSYMB, typename SOFTBYTE> void leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::run () inline virtual
Reimplemented from leansdr::runnable_common.
Definition at line 1568 of file dvbs2.h.
References leansdr::fecframe< SOFTBYTE >::bytes, leansdr::check_modcod(), leansdr::fail(), leansdr::FEC35, leansdr::s2_pls::framebits(), leansdr::plslot< SOFTSYMB >::is_pls, leansdr::s2_pls::modcod, leansdr::modcod_info::nslots_nf, leansdr::modcod_info::nsymbols, leansdr::plslot< SOFTSYMB >::pls, leansdr::fecframe< SOFTBYTE >::pls, leansdr::modcod_info::rate, leansdr::pipereader< T >::rd(), leansdr::pipereader< T >::read(), leansdr::pipereader< T >::readable(), leansdr::s2_pls::sf, leansdr::pipewriter< T >::wr(), leansdr::pipewriter< T >::writable(), and leansdr::pipewriter< T >::written().
     {
         while (in.readable() >= 1 && out.writable() >= 1)
         {
             plslot<SOFTSYMB> *pin = in.rd();
             if (!pin->is_pls)
                 fail("s2_deinterleaver: bad input sequence");
             s2_pls *pls = &pin->pls;
             const modcod_info *mcinfo = check_modcod(pls->modcod);
             int nslots = pls->sf ? mcinfo->nslots_nf / 4 : mcinfo->nslots_nf;
             if (in.readable() < 1 + nslots)
                 return;
             fecframe<SOFTBYTE> *pout = out.wr();
             pout->pls = *pls;
             SOFTBYTE *pbytes = pout->bytes;
             if (mcinfo->nsymbols == 4)
                 deserialize_qpsk(pin + 1, nslots, pbytes);
             else
             {
                 int bps = log2(mcinfo->nsymbols);
                 int rows = pls->framebits() / bps;
                 if (mcinfo->nsymbols == 8 && mcinfo->rate == FEC35)
                     deinterleave(bps, rows, pin + 1, nslots, false, pbytes);
                 else
                     deinterleave(bps, rows, pin + 1, nslots, true, pbytes);
             }
             in.read(1 + nslots);
             out.written(1);
         }
     }
split_symbol() [1/4]
template<typename SOFTSYMB, typename SOFTBYTE> static void leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::split_symbol (const llr_ss & ps, int bps, hard_sb accs[], int nacc, bool msb_first) inline static private
Definition at line 1781 of file dvbs2.h.
References leansdr::llr_ss::bits, and leansdr::llr_harden().
     {
         if (msb_first)
         {
             for (int b = 0; b < bps; ++b)
                 accs[b] = (accs[b] << 1) | llr_harden(ps.bits[bps - 1 - b]);
         }
         else
         {
             for (int b = 0; b < bps; ++b)
                 accs[b] = (accs[b] << 1) | llr_harden(ps.bits[b]);
         }
     }
split_symbol() [2/4]
template<typename SOFTSYMB, typename SOFTBYTE> template<int MSB_FIRST, int BPS> static void leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::split_symbol (const llr_ss & ps, hard_sb accs[], int nacc) inline static private
Definition at line 1798 of file dvbs2.h.
References leansdr::llr_ss::bits, and leansdr::llr_harden().
     {
         if (MSB_FIRST)
         {
             for (int b = 0; b < BPS; ++b)
                 accs[b] = (accs[b] << 1) | llr_harden(ps.bits[BPS - 1 - b]);
         }
         else
         {
             for (int b = 0; b < BPS; ++b)
                 accs[b] = (accs[b] << 1) | llr_harden(ps.bits[b]);
         }
     }
split_symbol() [3/4]
template<typename SOFTSYMB, typename SOFTBYTE> static void leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::split_symbol (const llr_ss & ps, int bps, llr_sb accs[], int nacc, bool msb_first) inline static private
Definition at line 1814 of file dvbs2.h.
References leansdr::llr_ss::bits.
     {
         if (msb_first)
         {
             for (int b = 0; b < bps; ++b)
                 accs[b].bits[nacc] = ps.bits[bps - 1 - b];
         }
         else
         {
             for (int b = 0; b < bps; ++b)
                 accs[b].bits[nacc] = ps.bits[b];
         }
     }
split_symbol() [4/4]
template<typename SOFTSYMB, typename SOFTBYTE> template<int MSB_FIRST, int BPS> static void leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::split_symbol (const llr_ss & ps, llr_sb accs[], int nacc) inline static private
Definition at line 1831 of file dvbs2.h.
References leansdr::llr_ss::bits.
     {
         if (MSB_FIRST)
         {
             for (int b = 0; b < BPS; ++b)
                 accs[b].bits[nacc] = ps.bits[BPS - 1 - b];
         }
         else
         {
             for (int b = 0; b < BPS; ++b)
                 accs[b].bits[nacc] = ps.bits[b];
         }
     }
Member Data Documentation
in
template<typename SOFTSYMB, typename SOFTBYTE> pipereader<plslot<SOFTSYMB> > leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::in private
Definition at line 1863 of file dvbs2.h.
out
template<typename SOFTSYMB, typename SOFTBYTE> pipewriter<fecframe<SOFTBYTE> > leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::out private
Definition at line 1864 of file dvbs2.h.
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/dvbs2.h