SDRAngel: leansdr::bch_interface Struct Reference
leansdr::bch_interface Struct Reference abstract
#include <bch.h>
Public Member Functions
virtual void encode (const uint8_t *msg, size_t msgbytes, uint8_t *out)=0
virtual int decode (uint8_t *cw, size_t cwbytes)=0
Detailed Description
Definition at line 27 of file bch.h.
Member Function Documentation
decode()
virtual int leansdr::bch_interface::decode (uint8_t * cw, size_t cwbytes) pure virtual
Implemented in leansdr::bch_engine< T, N, NP, DP, TGF, GFTRUNCGEN >.
Referenced by leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::receive_frame(), and leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::run().
encode()
virtual void leansdr::bch_interface::encode (const uint8_t * msg, size_t msgbytes, uint8_t * out) pure virtual
Implemented in leansdr::bch_engine< T, N, NP, DP, TGF, GFTRUNCGEN >.
Referenced by leansdr::s2_fecenc::run_frame().
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/bch.h