SDRAngel: ATVDemod::MsgReportChannelSampleRateChanged Class Reference
ATVDemod::MsgReportChannelSampleRateChanged Class Reference
#include <atvdemod.h>
Public Member Functions
int getSampleRate () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportChannelSampleRateChanged * create (int sampleRate)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportChannelSampleRateChanged (int sampleRate)
Private Attributes
int m_sampleRate
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 175 of file atvdemod.h.
Constructor & Destructor Documentation
MsgReportChannelSampleRateChanged()
ATVDemod::MsgReportChannelSampleRateChanged::MsgReportChannelSampleRateChanged (int sampleRate) inline private
Definition at line 189 of file atvdemod.h.
References ATVDemod::ATVDemod(), and ATVDemod::~ATVDemod().
                                                           :
             Message(),
             m_sampleRate(sampleRate)
         { }
Member Function Documentation
create()
static MsgReportChannelSampleRateChanged* ATVDemod::MsgReportChannelSampleRateChanged::create (int sampleRate) inline static
Definition at line 181 of file atvdemod.h.
Referenced by ATVDemod::channelSampleRateChanged().
         {
             return new MsgReportChannelSampleRateChanged(sampleRate);
         }
getSampleRate()
int ATVDemod::MsgReportChannelSampleRateChanged::getSampleRate () const inline
Definition at line 179 of file atvdemod.h.
Referenced by ATVDemodGUI::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_sampleRate
int ATVDemod::MsgReportChannelSampleRateChanged::m_sampleRate private
Definition at line 187 of file atvdemod.h.
The documentation for this class was generated from the following file:
plugins/channelrx/demodatv/atvdemod.h