SDRAngel: qtwebapp::FileLogger Class Reference
qtwebapp::FileLogger Class Reference
#include <filelogger.h>
Public Member Functions
FileLogger (QSettings *settings, const int refreshInterval=10000, QObject *parent=0)
FileLogger (const FileLoggerSettings &settings, const int refreshInterval=10000, QObject *parent=0)
virtual ~FileLogger ()
FileLoggerSettings getFileLoggerSettings () const
void setFileLoggerSettings (const FileLoggerSettings &settings)
virtual void write (const LogMessage *logMessage)
Public Member Functions inherited from qtwebapp::Logger
Logger (QObject *parent)
Logger (const QString msgFormat="{timestamp} {type} {msg}", const QString timestampFormat="yyyy-MM-dd HH:mm:ss.zzz", const QtMsgType minLevel=QtDebugMsg, const int bufferSize=0, QObject *parent=0)
virtual ~Logger ()
virtual void log (const QtMsgType type, const QString &message, const QString &file="", const QString &function="", const int line=0)
void installMsgHandler ()
void setMinMessageLevel (const QtMsgType &minMsgLevel)
QtMsgType getMinMessageLevel () const
virtual void clear (const bool buffer=true, const bool variables=true)
Protected Member Functions
void timerEvent (QTimerEvent *event)
Private Member Functions
void open ()
void close ()
void rotate ()
void refreshSettings ()
void refreshQtSettings ()
void refreshFileLogSettings ()
Private Attributes
QString fileName
long maxSize
int maxBackups
QSettings * settings
FileLoggerSettings fileLoggerSettings
QFile * file
QBasicTimer refreshTimer
QBasicTimer flushTimer
bool useQtSettings
Additional Inherited Members
Static Public Member Functions inherited from qtwebapp::Logger
static void set (const QString &name, const QString &value)
Protected Attributes inherited from qtwebapp::Logger
QString msgFormat
QString timestampFormat
QtMsgType minLevel
int bufferSize
Static Protected Attributes inherited from qtwebapp::Logger
static QMutex mutex
Detailed Description
Logger that uses a text file for output. Settings are read from a config file using a QSettings object. Config settings can be changed at runtime.
Example for the configuration settings:
fileName=logs/QtWebApp.log
maxSize=1000000
maxBackups=2
minLevel=0
msgformat={timestamp} {typeNr} {type} thread={thread}: {msg}
timestampFormat=yyyy-MM-dd HH:mm:ss.zzz
bufferSize=0
fileName is the name of the log file, relative to the directory of the settings file. In case of windows, if the settings are in the registry, the path is relative to the current working directory.
maxSize is the maximum size of that file in bytes. The file will be backed up and replaced by a new file if it becomes larger than this limit. Please note that the actual file size may become a little bit larger than this limit. Default is 0=unlimited.
maxBackups defines the number of backup files to keep. Default is 0=unlimited.
minLevel defines the minimum type of messages that are written (together with buffered messages) into the file. Defaults is 0=debug.
msgFormat defines the decoration of log messages, see LogMessage class. Default is "{timestamp} {type} {msg}".
timestampFormat defines the format of timestamps, see QDateTime::toString(). Default is "yyyy-MM-dd HH:mm:ss.zzz".
bufferSize defines the size of the buffer. Default is 0=disabled.
See also
set() describes how to set logger variables
LogMessage for a description of the message decoration.
Logger for a descrition of the buffer.
Definition at line 54 of file filelogger.h.
Constructor & Destructor Documentation
FileLogger() [1/2]
FileLogger::FileLogger (QSettings * settings, const int refreshInterval = 10000, QObject * parent = 0)
Constructor.
Parameters
settings Configuration settings, usually stored in an INI file. Must not be 0. Settings are read from the current group, so the caller must have called settings->beginGroup(). Because the group must not change during runtime, it is recommended to provide a separate QSettings instance to the logger that is not used by other parts of the program.
refreshInterval Interval of checking for changed config settings in msec, or 0=disabled
parent Parent object
Definition at line 97 of file filelogger.cpp.
References file, flushTimer, refreshSettings(), refreshTimer, and settings.
                                                                                       :
         Logger(parent), fileName(""), useQtSettings(true)
 {
     Q_ASSERT(settings != 0);
     Q_ASSERT(refreshInterval >= 0);
     this->settings = settings;
     file = 0;
     if (refreshInterval > 0) {
         refreshTimer.start(refreshInterval, this);
     }
     flushTimer.start(1000, this);
     refreshSettings();
 }
FileLogger() [2/2]
FileLogger::FileLogger (const FileLoggerSettings & settings, const int refreshInterval = 10000, QObject * parent = 0)
Constructor.
Parameters
settings Configuration settings as a simple structure (see: FileLoggerSettings).
refreshInterval Interval of checking for changed config settings in msec, or 0=disabled
parent Parent object
Definition at line 115 of file filelogger.cpp.
References file, fileLoggerSettings, flushTimer, refreshSettings(), refreshTimer, and settings.
                                                                                                      :
         Logger(parent), fileName(""), useQtSettings(false)
 {
     Q_ASSERT(refreshInterval >= 0);
     fileLoggerSettings = settings;
     file = 0;
     if (refreshInterval > 0) {
         refreshTimer.start(refreshInterval, this);
     }
     flushTimer.start(1000, this);
     refreshSettings();
 }
~FileLogger()
FileLogger::~FileLogger () virtual
Destructor. Closes the file.
Definition at line 132 of file filelogger.cpp.
References close().
 {
     close();
 }
Member Function Documentation
close()
void FileLogger::close () private
Close the output file
Definition at line 188 of file filelogger.cpp.
References file.
Referenced by refreshFileLogSettings(), refreshQtSettings(), timerEvent(), write(), and ~FileLogger().
 {
     if (file)
     {
         file->close();
         delete file;
         file = 0;
     }
 }
getFileLoggerSettings()
FileLoggerSettings qtwebapp::FileLogger::getFileLoggerSettings () const inline
Get a file logger settings copy
Returns
The current file logger settings
Definition at line 87 of file filelogger.h.
Referenced by qtwebapp::LoggerWithFile::getLogFileName().
 { return fileLoggerSettings; }
open()
void FileLogger::open () private
Open the output file
Definition at line 166 of file filelogger.cpp.
References file, and fileName.
Referenced by refreshFileLogSettings(), refreshQtSettings(), and timerEvent().
 {
     if (fileName.isEmpty())
     {
         fprintf(stderr, "FileLogger::open: Name of logFile is empty\n");
     }
     else
     {
         file = new QFile(fileName);
         if (!file->open(QIODevice::WriteOnly | QIODevice::Append | QIODevice::Text))
         {
             fprintf(stderr, "FileLogger::open: Cannot open log file %s: %s\n", qPrintable(fileName), qPrintable(file->errorString()));
             file = 0;
         }
         else
         {
             fprintf(stderr, "FileLogger::open: Opened log file %s\n", qPrintable(fileName));
         }
     }
 }
refreshFileLogSettings()
void FileLogger::refreshFileLogSettings () private
Refreshes the configuration settings with file log settings structure.
Definition at line 68 of file filelogger.cpp.
References qtwebapp::FileLoggerSettings::bufferSize, qtwebapp::Logger::bufferSize, close(), fileLoggerSettings, qtwebapp::FileLoggerSettings::fileName, fileName, qtwebapp::FileLoggerSettings::maxBackups, maxBackups, qtwebapp::FileLoggerSettings::maxSize, maxSize, qtwebapp::FileLoggerSettings::minLevel, qtwebapp::Logger::minLevel, qtwebapp::FileLoggerSettings::msgFormat, qtwebapp::Logger::msgFormat, open(), qtwebapp::FileLoggerSettings::timestampFormat, and qtwebapp::Logger::timestampFormat.
Referenced by refreshSettings().
 {
     // Save old file name for later comparison with new settings
     QString oldFileName = fileName;
     // Load new config settings
     fileName = fileLoggerSettings.fileName;
     // Convert relative fileName to absolute, based on the current working directory
     if (QDir::isRelativePath(fileName)) {
         fileName = QFileInfo(QDir::currentPath(), fileName).absoluteFilePath();
     }
     maxSize = fileLoggerSettings.maxSize;
     maxBackups = fileLoggerSettings.maxBackups;
     msgFormat = fileLoggerSettings.msgFormat;
     timestampFormat = fileLoggerSettings.timestampFormat;
     minLevel = fileLoggerSettings.minLevel;
     bufferSize = fileLoggerSettings.bufferSize;
     // Create new file if the filename has been changed
     if (oldFileName != fileName)
     {
         fprintf(stderr, "FileLogger::refreshQtSettings: Logging to new file %s\n", qPrintable(fileName));
         close();
         open();
     }
 }
refreshQtSettings()
void FileLogger::refreshQtSettings () private
Refreshes the configuration settings with Qt settings.
Definition at line 32 of file filelogger.cpp.
References qtwebapp::Logger::bufferSize, close(), fileName, maxBackups, maxSize, qtwebapp::Logger::minLevel, qtwebapp::Logger::msgFormat, open(), settings, and qtwebapp::Logger::timestampFormat.
Referenced by refreshSettings().
 {
     // Save old file name for later comparison with new settings
     QString oldFileName = fileName;
     // Load new config settings
     settings->sync();
     fileName = settings->value("fileName").toString();
     // Convert relative fileName to absolute, based on the directory of the config file.
 #ifdef Q_OS_WIN32
     if (QDir::isRelativePath(fileName) && settings->format()!=QSettings::NativeFormat)
 #else
     if (QDir::isRelativePath(fileName))
 #endif
     {
         QFileInfo configFile(settings->fileName());
         fileName = QFileInfo(configFile.absolutePath(), fileName).absoluteFilePath();
     }
     maxSize = settings->value("maxSize", 0).toLongLong();
     maxBackups = settings->value("maxBackups", 0).toInt();
     msgFormat = settings->value("msgFormat", "{timestamp} {type} {msg}").toString();
     timestampFormat = settings->value("timestampFormat", "yyyy-MM-dd HH:mm:ss.zzz").toString();
     minLevel = static_cast<QtMsgType>(settings->value("minLevel", 0).toInt());
     bufferSize = settings->value("bufferSize", 0).toInt();
     // Create new file if the filename has been changed
     if (oldFileName != fileName)
     {
         fprintf(stderr, "FileLogger::refreshQtSettings: Logging to %s\n", qPrintable(fileName));
         close();
         open();
     }
 }
refreshSettings()
void FileLogger::refreshSettings () private
Refreshes the configuration settings. This method is thread-safe.
Definition at line 19 of file filelogger.cpp.
References qtwebapp::Logger::mutex, refreshFileLogSettings(), refreshQtSettings(), and useQtSettings.
Referenced by FileLogger(), and timerEvent().
 {
     mutex.lock();
     if (useQtSettings) {
         refreshQtSettings();
     } else {
         refreshFileLogSettings();
     }
     mutex.unlock();
 }
rotate()
void FileLogger::rotate () private
Rotate files and delete some backups if there are too many
Definition at line 198 of file filelogger.cpp.
References arg(), fileName, i, and maxBackups.
Referenced by timerEvent().
 {
     fprintf(stderr, "FileLogger::rotate\n");
     // count current number of existing backup files
     int count = 0;
     forever
     {
         QFile bakFile(QString("%1.%2").arg(fileName).arg(count + 1));
         if (bakFile.exists()) {
             ++count;
         } else {
             break;
         }
     }
     // Remove all old backup files that exceed the maximum number
     while (maxBackups > 0 && count >= maxBackups)
     {
         QFile::remove(QString("%1.%2").arg(fileName).arg(count));
         --count;
     }
     // Rotate backup files
     for (int i = count; i > 0; --i)
     {
         QFile::rename(QString("%1.%2").arg(fileName).arg(i), QString("%1.%2").arg(fileName).arg(i + 1));
     }
     // Backup the current logfile
     QFile::rename(fileName, fileName + ".1");
 }
setFileLoggerSettings()
void qtwebapp::FileLogger::setFileLoggerSettings (const FileLoggerSettings & settings) inline
Set new file logger settings data
Parameters
File logger settings to replace current data
Definition at line 93 of file filelogger.h.
Referenced by qtwebapp::LoggerWithFile::createOrSetFileLogger().
 { fileLoggerSettings = settings; }
timerEvent()
void FileLogger::timerEvent (QTimerEvent * event) protected
Handler for timer events. Refreshes config settings or synchronizes I/O buffer, depending on the event. This method is thread-safe.
Parameters
event used to distinguish between the two timers.
Definition at line 232 of file filelogger.cpp.
References close(), file, flushTimer, maxSize, qtwebapp::Logger::mutex, open(), refreshSettings(), refreshTimer, and rotate().
 {
     if (!event) {
         return;
     } else if (event->timerId() == refreshTimer.timerId()) {
         refreshSettings();
     }
     else if (event->timerId() == flushTimer.timerId() && file)
     {
         mutex.lock();
         // Flush the I/O buffer
         file->flush();
         // Rotate the file if it is too large
         if (maxSize > 0 && file->size() >= maxSize)
         {
             close();
             rotate();
             open();
         }
         mutex.unlock();
     }
 }
write()
void FileLogger::write (const LogMessage * logMessage) virtual
Write a message to the log file
Reimplemented from qtwebapp::Logger.
Definition at line 137 of file filelogger.cpp.
References close(), file, fileName, qtwebapp::LogMessage::getType(), qtwebapp::Logger::msgFormat, qtwebapp::Logger::timestampFormat, qtwebapp::LogMessage::toString(), useQtSettings, and qtwebapp::Logger::write().
 {
     // Try to write to the file
     if (file)
     {
         // Write the message
         file->write(qPrintable(logMessage->toString(msgFormat, timestampFormat)));
         // Flush error messages immediately, to ensure that no important message
         // gets lost when the program terinates abnormally.
         if (logMessage->getType() >= QtCriticalMsg) {
             file->flush();
         }
         // Check for success
         if (file->error())
         {
             close();
             fprintf(stderr, "FileLogger::write: Cannot write to log file %s: %s\n", qPrintable(fileName), qPrintable(file->errorString()));
         }
     }
     // Fall-back to the super class method, if writing failed
     if (!file && useQtSettings) {
         Logger::write(logMessage);
     }
 }
Member Data Documentation
file
QFile* qtwebapp::FileLogger::file private
Output file, or 0=disabled
Definition at line 126 of file filelogger.h.
Referenced by close(), FileLogger(), open(), timerEvent(), and write().
fileLoggerSettings
FileLoggerSettings qtwebapp::FileLogger::fileLoggerSettings private
Pointer to the configuration settings
Definition at line 123 of file filelogger.h.
Referenced by FileLogger(), and refreshFileLogSettings().
fileName
QString qtwebapp::FileLogger::fileName private
Configured name of the log file
Definition at line 111 of file filelogger.h.
Referenced by open(), refreshFileLogSettings(), refreshQtSettings(), rotate(), and write().
flushTimer
QBasicTimer qtwebapp::FileLogger::flushTimer private
Timer for flushing the file I/O buffer
Definition at line 132 of file filelogger.h.
Referenced by FileLogger(), and timerEvent().
maxBackups
int qtwebapp::FileLogger::maxBackups private
Configured maximum number of backup files, or 0=unlimited
Definition at line 117 of file filelogger.h.
Referenced by refreshFileLogSettings(), refreshQtSettings(), and rotate().
maxSize
long qtwebapp::FileLogger::maxSize private
Configured maximum size of the file in bytes, or 0=unlimited
Definition at line 114 of file filelogger.h.
Referenced by refreshFileLogSettings(), refreshQtSettings(), and timerEvent().
refreshTimer
QBasicTimer qtwebapp::FileLogger::refreshTimer private
Timer for refreshing configuration settings
Definition at line 129 of file filelogger.h.
Referenced by FileLogger(), and timerEvent().
settings
QSettings* qtwebapp::FileLogger::settings private
Pointer to the configuration settings
Definition at line 120 of file filelogger.h.
Referenced by FileLogger(), and refreshQtSettings().
useQtSettings
bool qtwebapp::FileLogger::useQtSettings private
Use of Qt settings or simple structure settings
Definition at line 135 of file filelogger.h.
Referenced by refreshSettings(), and write().
The documentation for this class was generated from the following files:
logging/filelogger.h
logging/filelogger.cpp