SDRAngel: FreeDVDemodGUI Class Reference
FreeDVDemodGUI Class Reference
#include <freedvdemodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
void channelMarkerHighlightedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static FreeDVDemodGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
Private Slots
void on_deltaFrequency_changed (qint64 value)
void on_reSync_clicked (bool checked)
void on_freeDVMode_currentIndexChanged (int index)
void on_volume_valueChanged (int value)
void on_volumeIn_valueChanged (int value)
void on_agc_toggled (bool checked)
void on_audioMute_toggled (bool checked)
void on_spanLog2_valueChanged (int value)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void handleInputMessages ()
void audioSelect ()
void tick ()
Private Member Functions
FreeDVDemodGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *parent=0)
virtual ~FreeDVDemodGUI ()
bool blockApplySettings (bool block)
void applySettings (bool force=false)
void applyBandwidths (int spanLog2, bool force=false)
void displayBandwidths (int spanLog2)
void displaySettings ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::FreeDVDemodGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
FreeDVDemodSettings m_settings
bool m_doApplySettings
int m_spectrumRate
bool m_audioBinaural
bool m_audioFlipChannels
bool m_audioMute
bool m_squelchOpen
uint32_t m_tickCount
FreeDVDemod * m_freeDVDemod
SpectrumVis * m_spectrumVis
MessageQueue m_inputMessageQueue
QIcon m_iconDSBUSB
QIcon m_iconDSBLSB
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 42 of file freedvdemodgui.h.
Constructor & Destructor Documentation
FreeDVDemodGUI()
FreeDVDemodGUI::FreeDVDemodGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * parent = 0) explicit private
Definition at line 245 of file freedvdemodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applyBandwidths(), arg(), audioSelect(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), LevelMeterSignalDB::ColorCyanAndBlue, LevelMeterSignalDB::ColorGreenAndBlue, displaySettings(), getInputMessageQueue(), BasebandSampleSink::getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, handleInputMessages(), FreeDVDemod::m_channelIdURI, m_channelMarker, m_deviceUISet, m_freeDVDemod, m_iconDSBLSB, m_iconDSBUSB, m_settings, m_spectrumRate, m_spectrumVis, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), resetToDefaults(), SDR_RX_SCALEF, FreeDVDemodSettings::setChannelMarker(), BasebandSampleSink::setMessageQueueToGUI(), FreeDVDemod::setSampleSink(), FreeDVDemodSettings::setSpectrumGUI(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                              :
     RollupWidget(parent),
     ui(new Ui::FreeDVDemodGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_doApplySettings(true),
     m_spectrumRate(6000),
     m_audioBinaural(false),
     m_audioFlipChannels(false),
     m_audioMute(false),
     m_squelchOpen(false)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_spectrumVis = new SpectrumVis(SDR_RX_SCALEF, ui->glSpectrum);
     m_freeDVDemod = (FreeDVDemod*) rxChannel;
     m_freeDVDemod->setSampleSink(m_spectrumVis);
     m_freeDVDemod->setMessageQueueToGUI(getInputMessageQueue());
     resetToDefaults();
     ui->glSpectrum->setCenterFrequency(m_spectrumRate/2);
     ui->glSpectrum->setSampleRate(m_spectrumRate);
     ui->glSpectrum->setDisplayWaterfall(true);
     ui->glSpectrum->setDisplayMaxHold(true);
     ui->glSpectrum->setSsbSpectrum(true);
     ui->glSpectrum->connectTimer(MainWindow::getInstance()->getMasterTimer());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     CRightClickEnabler *audioMuteRightClickEnabler = new CRightClickEnabler(ui->audioMute);
     connect(audioMuteRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioSelect()));
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     ui->channelPowerMeter->setColorTheme(LevelMeterSignalDB::ColorGreenAndBlue);
     ui->snrMeter->setColorTheme(LevelMeterSignalDB::ColorCyanAndBlue);
     ui->snrMeter->setRange(-10, 30);
     ui->snrMeter->setAverageSmoothing(2);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     m_settings.setChannelMarker(&m_channelMarker);
     m_settings.setSpectrumGUI(ui->spectrumGUI);
     m_deviceUISet->registerRxChannelInstance(FreeDVDemod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(&m_channelMarker, SIGNAL(highlightedByCursor()), this, SLOT(channelMarkerHighlightedByCursor()));
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
     connect(m_freeDVDemod, SIGNAL(levelInChanged(qreal, qreal, int)), ui->volumeInMeter, SLOT(levelChanged(qreal, qreal, int)));
     ui->spectrumGUI->setBuddies(m_spectrumVis->getInputMessageQueue(), m_spectrumVis, ui->glSpectrum);
     m_iconDSBUSB.addPixmap(QPixmap("://dsb.png"), QIcon::Normal, QIcon::On);
     m_iconDSBUSB.addPixmap(QPixmap("://usb.png"), QIcon::Normal, QIcon::Off);
     m_iconDSBLSB.addPixmap(QPixmap("://dsb.png"), QIcon::Normal, QIcon::On);
     m_iconDSBLSB.addPixmap(QPixmap("://lsb.png"), QIcon::Normal, QIcon::Off);
     displaySettings();
     applyBandwidths(5 - ui->spanLog2->value(), true); // does applySettings(true)
 }
~FreeDVDemodGUI()
FreeDVDemodGUI::~FreeDVDemodGUI () private virtual
Definition at line 315 of file freedvdemodgui.cpp.
References m_deviceUISet, m_freeDVDemod, m_spectrumVis, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_freeDVDemod; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete m_spectrumVis;
     delete ui;
 }
Member Function Documentation
applyBandwidths()
void FreeDVDemodGUI::applyBandwidths (int spanLog2, bool force = false) private
Definition at line 343 of file freedvdemodgui.cpp.
References applySettings(), displayBandwidths(), m_settings, and FreeDVDemodSettings::m_spanLog2.
Referenced by deserialize(), FreeDVDemodGUI(), handleMessage(), and on_spanLog2_valueChanged().
 {
     displayBandwidths(m_settings.m_spanLog2);
     m_settings.m_spanLog2 = spanLog2;
     applySettings(force);
 }
applySettings()
void FreeDVDemodGUI::applySettings (bool force = false) private
Definition at line 330 of file freedvdemodgui.cpp.
References FreeDVDemod::MsgConfigureFreeDVDemod::create(), FreeDVDemod::MsgConfigureChannelizer::create(), FreeDVDemod::getAudioSampleRate(), ChannelMarker::getCenterFrequency(), BasebandSampleSink::getInputMessageQueue(), m_channelMarker, m_doApplySettings, m_freeDVDemod, m_settings, and MessageQueue::push().
Referenced by applyBandwidths(), audioSelect(), channelMarkerChangedByCursor(), on_agc_toggled(), on_audioMute_toggled(), on_deltaFrequency_changed(), on_freeDVMode_currentIndexChanged(), on_volume_valueChanged(), on_volumeIn_valueChanged(), onMenuDialogCalled(), and setCenterFrequency().
 {
     if (m_doApplySettings)
     {
         FreeDVDemod::MsgConfigureChannelizer* channelConfigMsg = FreeDVDemod::MsgConfigureChannelizer::create(
                 m_freeDVDemod->getAudioSampleRate(), m_channelMarker.getCenterFrequency());
         m_freeDVDemod->getInputMessageQueue()->push(channelConfigMsg);
         FreeDVDemod::MsgConfigureFreeDVDemod* message = FreeDVDemod::MsgConfigureFreeDVDemod::create( m_settings, force);
         m_freeDVDemod->getInputMessageQueue()->push(message);
     }
 }
audioSelect
void FreeDVDemodGUI::audioSelect () private slot
Definition at line 415 of file freedvdemodgui.cpp.
References applySettings(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, FreeDVDemodSettings::m_audioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by FreeDVDemodGUI().
 {
     qDebug("FreeDVDemodGUI::audioSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName);
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_audioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
blockApplySettings()
bool FreeDVDemodGUI::blockApplySettings (bool block) private
Definition at line 323 of file freedvdemodgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     bool ret = !m_doApplySettings;
     m_doApplySettings = !block;
     return ret;
 }
channelMarkerChangedByCursor
void FreeDVDemodGUI::channelMarkerChangedByCursor () slot
Definition at line 136 of file freedvdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, FreeDVDemodSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by FreeDVDemodGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
channelMarkerHighlightedByCursor
void FreeDVDemodGUI::channelMarkerHighlightedByCursor () slot
Definition at line 143 of file freedvdemodgui.cpp.
References ChannelMarker::getHighlighted(), m_channelMarker, and RollupWidget::setHighlighted().
Referenced by FreeDVDemodGUI().
 {
     setHighlighted(m_channelMarker.getHighlighted());
 }
create()
FreeDVDemodGUI * FreeDVDemodGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) static
Definition at line 39 of file freedvdemodgui.cpp.
References FreeDVDemodGUI().
Referenced by FreeDVPlugin::createRxChannelGUI().
 {
     FreeDVDemodGUI* gui = new FreeDVDemodGUI(pluginAPI, deviceUISet, rxChannel);
     return gui;
 }
deserialize()
bool FreeDVDemodGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 82 of file freedvdemodgui.cpp.
References applyBandwidths(), FreeDVDemodSettings::deserialize(), displaySettings(), m_settings, FreeDVDemodSettings::resetToDefaults(), and ui.
 {
     if(m_settings.deserialize(data))
     {
         displaySettings();
         applyBandwidths(5 - ui->spanLog2->value(), true); // does applySettings(true)
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         displaySettings();
         applyBandwidths(5 - ui->spanLog2->value(), true); // does applySettings(true)
         return false;
     }
 }
destroy()
void FreeDVDemodGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 45 of file freedvdemodgui.cpp.
 {
     delete this;
 }
displayBandwidths()
void FreeDVDemodGUI::displayBandwidths (int spanLog2) private
Definition at line 350 of file freedvdemodgui.cpp.
References arg(), FreeDVDemod::getModemSampleRate(), m_freeDVDemod, m_spectrumRate, and ui.
Referenced by applyBandwidths(), and displaySettings().
 {
     m_spectrumRate = m_freeDVDemod->getModemSampleRate() / (1<<spanLog2);
     int bwMax = m_freeDVDemod->getModemSampleRate() / (100*(1<<spanLog2));
     qDebug() << "FreeDVDemodGUI::displayBandwidths:"
             << " spanLog2: " << spanLog2
             << " m_spectrumRate: " << m_spectrumRate
             << " bwMax: " << bwMax;
     QString spanStr = QString::number(bwMax/10.0, 'f', 1);
     ui->spanText->setText(tr("%1k").arg(spanStr));
     ui->glSpectrum->setCenterFrequency(m_spectrumRate/2);
     ui->glSpectrum->setSampleRate(m_spectrumRate);
     ui->glSpectrum->setSsbSpectrum(true);
     ui->glSpectrum->setLsbDisplay(false);
 }
displaySettings()
void FreeDVDemodGUI::displaySettings () private
Definition at line 369 of file freedvdemodgui.cpp.
References arg(), blockApplySettings(), displayBandwidths(), ChannelMarker::getCenterFrequency(), FreeDVDemodSettings::getHiCutoff(), FreeDVDemodSettings::getLowCutoff(), ChannelMarker::getTitle(), FreeDVDemodSettings::m_agc, FreeDVDemodSettings::m_audioMute, m_channelMarker, FreeDVDemodSettings::m_freeDVMode, FreeDVDemodSettings::m_inputFrequencyOffset, FreeDVDemodSettings::m_rgbColor, m_settings, FreeDVDemodSettings::m_spanLog2, FreeDVDemodSettings::m_title, FreeDVDemodSettings::m_volume, FreeDVDemodSettings::m_volumeIn, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setLowCutoff(), ChannelMarker::setSidebands(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ui, and ChannelMarker::usb.
Referenced by deserialize(), FreeDVDemodGUI(), and handleMessage().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.setBandwidth(FreeDVDemodSettings::getHiCutoff(m_settings.m_freeDVMode) * 2);
     m_channelMarker.setLowCutoff(FreeDVDemodSettings::getLowCutoff(m_settings.m_freeDVMode));
     m_channelMarker.setSidebands(ChannelMarker::usb);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->freeDVMode->setCurrentIndex((int) m_settings.m_freeDVMode);
     ui->agc->setChecked(m_settings.m_agc);
     ui->audioMute->setChecked(m_settings.m_audioMute);
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     // Prevent uncontrolled triggering of applyBandwidths
     ui->spanLog2->blockSignals(true);
     ui->spanLog2->setValue(5 - m_settings.m_spanLog2);
     displayBandwidths(m_settings.m_spanLog2);
     ui->spanLog2->blockSignals(false);
     ui->volume->setValue(m_settings.m_volume * 10.0);
     ui->volumeText->setText(QString("%1").arg(m_settings.m_volume, 0, 'f', 1));
     ui->volumeIn->setValue(m_settings.m_volumeIn * 10.0);
     ui->volumeInText->setText(QString("%1").arg(m_settings.m_volumeIn, 0, 'f', 1));
     blockApplySettings(false);
 }
enterEvent()
void FreeDVDemodGUI::enterEvent (QEvent *) private
Definition at line 410 of file freedvdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 FreeDVDemodGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 60 of file freedvdemodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
 {
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* FreeDVDemodGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 57 of file freedvdemodgui.h.
Referenced by FreeDVDemodGUI(), and handleInputMessages().
 { return &m_inputMessageQueue; }
getName()
QString FreeDVDemodGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 55 of file freedvdemodgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void FreeDVDemodGUI::handleInputMessages () private slot
Definition at line 123 of file freedvdemodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by FreeDVDemodGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
bool FreeDVDemodGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 99 of file freedvdemodgui.cpp.
References applyBandwidths(), blockApplySettings(), displaySettings(), FreeDVDemod::getAudioSampleRate(), FreeDVDemod::MsgConfigureFreeDVDemod::getSettings(), m_freeDVDemod, m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (FreeDVDemod::MsgConfigureFreeDVDemod::match(message))
     {
         qDebug("FreeDVDemodGUI::handleMessage: FreeDVDemodGUI::MsgConfigureFreeDVDemod");
         const FreeDVDemod::MsgConfigureFreeDVDemod& cfg = (FreeDVDemod::MsgConfigureFreeDVDemod&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (DSPConfigureAudio::match(message))
     {
         qDebug("FreeDVDemodGUI::handleMessage: DSPConfigureAudio: %d", m_freeDVDemod->getAudioSampleRate());
         applyBandwidths(5 - ui->spanLog2->value()); // will update spectrum details with new sample rate
         return true;
     }
     else
     {
         return false;
     }
 }
leaveEvent()
void FreeDVDemodGUI::leaveEvent (QEvent *) private
Definition at line 405 of file freedvdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_agc_toggled
void FreeDVDemodGUI::on_agc_toggled (bool checked) private slot
Definition at line 185 of file freedvdemodgui.cpp.
References applySettings(), FreeDVDemodSettings::m_agc, and m_settings.
 {
     m_settings.m_agc = checked;
     applySettings();
 }
on_audioMute_toggled
void FreeDVDemodGUI::on_audioMute_toggled (bool checked) private slot
Definition at line 191 of file freedvdemodgui.cpp.
References applySettings(), FreeDVDemodSettings::m_audioMute, m_audioMute, and m_settings.
 {
     m_audioMute = checked;
     m_settings.m_audioMute = checked;
     applySettings();
 }
on_deltaFrequency_changed
void FreeDVDemodGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 148 of file freedvdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, FreeDVDemodSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_freeDVMode_currentIndexChanged
void FreeDVDemodGUI::on_freeDVMode_currentIndexChanged (int index) private slot
Definition at line 162 of file freedvdemodgui.cpp.
References applySettings(), FreeDVDemodSettings::getHiCutoff(), FreeDVDemodSettings::getLowCutoff(), m_channelMarker, FreeDVDemodSettings::m_freeDVMode, m_settings, ChannelMarker::setBandwidth(), ChannelMarker::setLowCutoff(), ChannelMarker::setSidebands(), and ChannelMarker::usb.
 {
     m_settings.m_freeDVMode = (FreeDVDemodSettings::FreeDVMode) index;
     m_channelMarker.setBandwidth(FreeDVDemodSettings::getHiCutoff(m_settings.m_freeDVMode) * 2);
     m_channelMarker.setLowCutoff(FreeDVDemodSettings::getLowCutoff(m_settings.m_freeDVMode));
     m_channelMarker.setSidebands(ChannelMarker::usb);
     applySettings();
 }
on_reSync_clicked
void FreeDVDemodGUI::on_reSync_clicked (bool checked) private slot
Definition at line 155 of file freedvdemodgui.cpp.
References FreeDVDemod::MsgResyncFreeDVDemod::create(), BasebandSampleSink::getInputMessageQueue(), m_freeDVDemod, and MessageQueue::push().
 {
     (void) checked;
     FreeDVDemod::MsgResyncFreeDVDemod* message = FreeDVDemod::MsgResyncFreeDVDemod::create();
     m_freeDVDemod->getInputMessageQueue()->push(message);
 }
on_spanLog2_valueChanged
void FreeDVDemodGUI::on_spanLog2_valueChanged (int value) private slot
Definition at line 198 of file freedvdemodgui.cpp.
References applyBandwidths(), and ui.
 {
     if ((value < 0) || (value > 4)) {
         return;
     }
     applyBandwidths(5 - ui->spanLog2->value());
 }
on_volume_valueChanged
void FreeDVDemodGUI::on_volume_valueChanged (int value) private slot
Definition at line 171 of file freedvdemodgui.cpp.
References applySettings(), arg(), m_settings, FreeDVDemodSettings::m_volume, and ui.
 {
     ui->volumeText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_volume = value / 10.0;
     applySettings();
 }
on_volumeIn_valueChanged
void FreeDVDemodGUI::on_volumeIn_valueChanged (int value) private slot
Definition at line 178 of file freedvdemodgui.cpp.
References applySettings(), arg(), m_settings, FreeDVDemodSettings::m_volumeIn, and ui.
 {
     ui->volumeInText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_volumeIn = value / 10.0;
     applySettings();
 }
onMenuDialogCalled
void FreeDVDemodGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 207 of file freedvdemodgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, FreeDVDemodSettings::m_inputFrequencyOffset, FreeDVDemodSettings::m_reverseAPIAddress, FreeDVDemodSettings::m_reverseAPIChannelIndex, FreeDVDemodSettings::m_reverseAPIDeviceIndex, FreeDVDemodSettings::m_reverseAPIPort, FreeDVDemodSettings::m_rgbColor, m_settings, FreeDVDemodSettings::m_title, FreeDVDemodSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by FreeDVDemodGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void FreeDVDemodGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 239 of file freedvdemodgui.cpp.
Referenced by FreeDVDemodGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void FreeDVDemodGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 72 of file freedvdemodgui.cpp.
References m_settings, and FreeDVDemodSettings::resetToDefaults().
Referenced by FreeDVDemodGUI().
 {
     m_settings.resetToDefaults();
 }
serialize()
QByteArray FreeDVDemodGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 77 of file freedvdemodgui.cpp.
References m_settings, and FreeDVDemodSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void FreeDVDemodGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 65 of file freedvdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, FreeDVDemodSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
setName()
void FreeDVDemodGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 50 of file freedvdemodgui.cpp.
 {
     setObjectName(name);
 }
tick
void FreeDVDemodGUI::tick () private slot
Definition at line 428 of file freedvdemodgui.cpp.
References arg(), CalcDb::dbPower(), FreeDVDemod::getAudioActive(), FreeDVDemod::getBER(), FreeDVDemod::getFrequencyOffset(), FreeDVDemod::getMagSqLevels(), FreeDVDemod::getSNRLevels(), FreeDVDemod::isSync(), m_freeDVDemod, FreeDVDemodSettings::m_mminPowerThresholdDBf, m_squelchOpen, m_tickCount, and ui.
Referenced by FreeDVDemodGUI().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     m_freeDVDemod->getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     double powDbAvg = CalcDb::dbPower(magsqAvg);
     double powDbPeak = CalcDb::dbPower(magsqPeak);
     ui->channelPowerMeter->levelChanged(
             (FreeDVDemodSettings::m_mminPowerThresholdDBf + powDbAvg) / FreeDVDemodSettings::m_mminPowerThresholdDBf,
             (FreeDVDemodSettings::m_mminPowerThresholdDBf + powDbPeak) / FreeDVDemodSettings::m_mminPowerThresholdDBf,
             nbMagsqSamples);
     double snrAvg, snrPeak;
     int nbSNRSamples;
     m_freeDVDemod->getSNRLevels(snrAvg, snrPeak, nbSNRSamples);
     ui->snrMeter->levelChanged(
         (10.0f + snrAvg) / 40.0f,
         (10.0f + snrPeak) / 40.0f,
         nbSNRSamples
     );
     ui->berText->setText(tr("%1").arg(m_freeDVDemod->getBER()));
     float freqOffset = m_freeDVDemod->getFrequencyOffset();
     int freqOffsetInt = freqOffset < -999 ? -999 : freqOffset > 999 ? 999 : freqOffset;
     ui->freqOffset->setText(tr("%1Hz").arg(freqOffsetInt));
     if (m_freeDVDemod->isSync()) {
         ui->syncLabel->setStyleSheet("QLabel { background-color : green; }");
     } else {
         ui->syncLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     }
     if (m_tickCount % 4 == 0) {
         ui->channelPower->setText(tr("%1 dB").arg(powDbAvg, 0, 'f', 1));
         ui->snrText->setText(tr("%1 dB").arg(snrAvg < -90 ? -90 : snrAvg > 90 ? 90 : snrAvg, 0, 'f', 1));
     }
     bool squelchOpen = m_freeDVDemod->getAudioActive();
     if (squelchOpen != m_squelchOpen)
     {
         if (squelchOpen) {
             ui->audioMute->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->audioMute->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         }
         m_squelchOpen = squelchOpen;
     }
     m_tickCount++;
 }
Member Data Documentation
m_audioBinaural
bool FreeDVDemodGUI::m_audioBinaural private
Definition at line 72 of file freedvdemodgui.h.
m_audioFlipChannels
bool FreeDVDemodGUI::m_audioFlipChannels private
Definition at line 73 of file freedvdemodgui.h.
m_audioMute
bool FreeDVDemodGUI::m_audioMute private
Definition at line 74 of file freedvdemodgui.h.
Referenced by on_audioMute_toggled().
m_channelMarker
ChannelMarker FreeDVDemodGUI::m_channelMarker private
Definition at line 68 of file freedvdemodgui.h.
Referenced by applySettings(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), displaySettings(), enterEvent(), FreeDVDemodGUI(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), on_freeDVMode_currentIndexChanged(), onMenuDialogCalled(), and setCenterFrequency().
m_deviceUISet
DeviceUISet* FreeDVDemodGUI::m_deviceUISet private
Definition at line 67 of file freedvdemodgui.h.
Referenced by FreeDVDemodGUI(), and ~FreeDVDemodGUI().
m_doApplySettings
bool FreeDVDemodGUI::m_doApplySettings private
Definition at line 70 of file freedvdemodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_freeDVDemod
FreeDVDemod* FreeDVDemodGUI::m_freeDVDemod private
Definition at line 78 of file freedvdemodgui.h.
Referenced by applySettings(), displayBandwidths(), FreeDVDemodGUI(), handleMessage(), on_reSync_clicked(), tick(), and ~FreeDVDemodGUI().
m_iconDSBLSB
QIcon FreeDVDemodGUI::m_iconDSBLSB private
Definition at line 83 of file freedvdemodgui.h.
Referenced by FreeDVDemodGUI().
m_iconDSBUSB
QIcon FreeDVDemodGUI::m_iconDSBUSB private
Definition at line 82 of file freedvdemodgui.h.
Referenced by FreeDVDemodGUI().
m_inputMessageQueue
MessageQueue FreeDVDemodGUI::m_inputMessageQueue private
Definition at line 80 of file freedvdemodgui.h.
m_pluginAPI
PluginAPI* FreeDVDemodGUI::m_pluginAPI private
Definition at line 66 of file freedvdemodgui.h.
m_settings
FreeDVDemodSettings FreeDVDemodGUI::m_settings private
Definition at line 69 of file freedvdemodgui.h.
Referenced by applyBandwidths(), applySettings(), audioSelect(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), FreeDVDemodGUI(), handleMessage(), on_agc_toggled(), on_audioMute_toggled(), on_deltaFrequency_changed(), on_freeDVMode_currentIndexChanged(), on_volume_valueChanged(), on_volumeIn_valueChanged(), onMenuDialogCalled(), resetToDefaults(), serialize(), and setCenterFrequency().
m_spectrumRate
int FreeDVDemodGUI::m_spectrumRate private
Definition at line 71 of file freedvdemodgui.h.
Referenced by displayBandwidths(), and FreeDVDemodGUI().
m_spectrumVis
SpectrumVis* FreeDVDemodGUI::m_spectrumVis private
Definition at line 79 of file freedvdemodgui.h.
Referenced by FreeDVDemodGUI(), and ~FreeDVDemodGUI().
m_squelchOpen
bool FreeDVDemodGUI::m_squelchOpen private
Definition at line 75 of file freedvdemodgui.h.
Referenced by tick().
m_tickCount
uint32_t FreeDVDemodGUI::m_tickCount private
Definition at line 76 of file freedvdemodgui.h.
Referenced by tick().
ui
Ui::FreeDVDemodGUI* FreeDVDemodGUI::ui private
Definition at line 65 of file freedvdemodgui.h.
Referenced by channelMarkerChangedByCursor(), deserialize(), displayBandwidths(), displaySettings(), FreeDVDemodGUI(), handleMessage(), on_spanLog2_valueChanged(), on_volume_valueChanged(), on_volumeIn_valueChanged(), tick(), and ~FreeDVDemodGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/demodfreedv/freedvdemodgui.h
plugins/channelrx/demodfreedv/freedvdemodgui.cpp