SDRAngel: RDSDemod Class Reference
RDSDemod Class Reference
#include <rdsdemod.h>
Inherits QObject.
Public Member Functions
RDSDemod ()
~RDSDemod ()
void setSampleRate (int srate)
FIXME: fix rate for now.
bool process (Real rdsSample, bool &bit)
Public Attributes
struct {
Real acc
Real qua
Real fclk
} m_report
double subcarr_phi
Real subcarr_bb [2]
double clock_offset
double clock_phi
double prev_clock_phi
Real lo_clock
Real prev_lo_clock
Real prev_bb
double d_cphi
int numsamples
Real prev_acc
int counter
int reading_frame
int tot_errs [2]
int dbit
Protected Member Functions
bool biphase (Real acc, bool &bit, Real d_cphi)
Real filter_lp_2400_iq (Real in, int iqIndex)
Real filter_lp_pll (Real input)
int sign (Real a)
Private Attributes
struct {
double subcarr_phi
Real subcarr_bb [2]
double clock_offset
double clock_phi
double prev_clock_phi
Real lo_clock
Real prev_lo_clock
Real prev_bb
double d_cphi
Real acc
int numsamples
Real prev_acc
int counter
int reading_frame
int tot_errs [2]
int dbit
} m_parms
Real m_xv [2][2+1]
Real m_yv [2][2+1]
Real m_xw [1+1]
Real m_yw [1+1]
Real m_prev
int m_srate
Static Private Attributes
static const Real m_pllBeta = 50
static const Real m_fsc = 1187.5
Detailed Description
Definition at line 28 of file rdsdemod.h.
Constructor & Destructor Documentation
RDSDemod()
RDSDemod::RDSDemod ()
Definition at line 34 of file rdsdemod.cpp.
References m_parms, m_prev, m_report, m_srate, m_xv, m_xw, m_yv, and m_yw.
 {
     m_srate = 250000;
     m_parms.subcarr_phi = 0;
     memset(m_parms.subcarr_bb, 0, sizeof(m_parms.subcarr_bb));
     m_parms.clock_offset = 0;
     m_parms.clock_phi = 0;
     m_parms.prev_clock_phi = 0;
     m_parms.lo_clock = 0;
     m_parms.prev_lo_clock = 0;
     m_parms.prev_bb = 0;
     m_parms.d_cphi = 0;
     m_parms.acc = 0;
     m_parms.numsamples = 0;
     m_parms.prev_acc = 0;
     m_parms.counter = 0;
     m_parms.reading_frame = 0;
     memset(m_parms.tot_errs, 0, sizeof(m_parms.tot_errs));
     m_parms.dbit = 0;
     m_prev = 0.0f;
     memset(m_xv, 0, 6*sizeof(Real));
     memset(m_yv, 0, 6*sizeof(Real));
     memset(m_xw, 0, 2*sizeof(Real));
     memset(m_yw, 0, 2*sizeof(Real));
     m_report.acc = 0.0f;
     m_report.fclk = 0.0f;
     m_report.qua = 0.0f;
 }
~RDSDemod()
RDSDemod::~RDSDemod ()
Definition at line 65 of file rdsdemod.cpp.
 {
     //delete m_socket;
 }
Member Function Documentation
biphase()
bool RDSDemod::biphase (Real acc, bool & bit, Real d_cphi) protected
Definition at line 138 of file rdsdemod.cpp.
References abs(), acc, m_parms, M_PI, m_report, m_srate, and sign().
Referenced by process().
 {
     bool ret = false;
     if (sign(acc) != sign(m_parms.prev_acc)) // two successive of different sign: error detected
     {
         m_parms.tot_errs[m_parms.counter % 2]++;
     }
     if (m_parms.counter % 2 == m_parms.reading_frame) // two successive of the same sing: OK
     {
         // new bit found
         int b = sign(m_parms.acc + m_parms.prev_acc);
         bit = b ^ m_parms.dbit;
         m_parms.dbit = b;
         ret = true;
     }
     if (m_parms.counter == 0)
     {
         if (m_parms.tot_errs[1 - m_parms.reading_frame] < m_parms.tot_errs[m_parms.reading_frame])
         {
             m_parms.reading_frame = 1 - m_parms.reading_frame;
         }
         m_report.qua = (1.0 * abs(m_parms.tot_errs[0] - m_parms.tot_errs[1]) / (m_parms.tot_errs[0] + m_parms.tot_errs[1])) * 100;
         m_report.acc = acc;
         m_report.fclk = (d_cphi / (2 * M_PI)) * m_srate;
         /*
         qDebug("RDSDemod::biphase: frame: %d  acc: %+6.3f errs: %3d %3d  qual: %3.0f%%  clk: %7.2f",
                 m_parms.reading_frame,
                 acc,
                 m_parms.tot_errs[0],
                 m_parms.tot_errs[1],
                 m_report.qua,
                 m_report.fclk);*/
         m_parms.tot_errs[0] = 0;
         m_parms.tot_errs[1] = 0;
     }
     m_parms.prev_acc = acc; // memorize (z^-1)
     m_parms.counter = (m_parms.counter + 1) % 800;
     return ret;
 }
filter_lp_2400_iq()
Real RDSDemod::filter_lp_2400_iq (Real in, int iqIndex) protected
Definition at line 186 of file rdsdemod.cpp.
References m_xv, and m_yv.
Referenced by process().
 {
     /* Digital filter designed by mkfilter/mkshape/gencode A.J. Fisher
      Command line: /www/usr/fisher/helpers/mkfilter -Bu -Lp -o 10
      -a 4.8000000000e-03 0.0000000000e+00 -l */
     m_xv[iqIndex][0] = m_xv[iqIndex][1]; m_xv[iqIndex][1] = m_xv[iqIndex][2];
     m_xv[iqIndex][2] = input / 4.491730007e+03;
     m_yv[iqIndex][0] = m_yv[iqIndex][1]; m_yv[iqIndex][1] = m_yv[iqIndex][2];
     m_yv[iqIndex][2] =   (m_xv[iqIndex][0] + m_xv[iqIndex][2]) + 2 * m_xv[iqIndex][1]
     + ( -0.9582451124 * m_yv[iqIndex][0]) + (  1.9573545869 * m_yv[iqIndex][1]);
     return m_yv[iqIndex][2];
 }
filter_lp_pll()
Real RDSDemod::filter_lp_pll (Real input) protected
Definition at line 201 of file rdsdemod.cpp.
References m_xw, and m_yw.
 {
       m_xw[0] = m_xw[1];
       m_xw[1] = input / 3.716236217e+01;
       m_yw[0] = m_yw[1];
       m_yw[1] =   (m_xw[0] + m_xw[1])
         + (  0.9461821078 * m_yw[0]);
       return m_yw[1];
 }
process()
bool RDSDemod::process (Real rdsSample, bool & bit)
Definition at line 75 of file rdsdemod.cpp.
References biphase(), filter_lp_2400_iq(), m_fsc, m_parms, M_PI, M_PI_2, m_prev, m_srate, and sign().
Referenced by BFMDemod::feed().
 {
     bool ret = false;
     //m_udpDebug.write(m_parms.lo_clock * m_parms.subcarr_bb[0]); // UDP debug
     // Subcarrier downmix & phase recovery
     m_parms.subcarr_bb[0] = filter_lp_2400_iq(demod, 0);
     // 1187.5 Hz clock
     /*
     if (m_parms.subcarr_phi > 1e9) // ~ every 37 hours =>  not really useful
     {
         qDebug("RDSDemod::process: reset 1187.5 Hz clock");
         m_parms.subcarr_phi = 0;
         m_parms.clock_offset = 0;
     }*/
     m_parms.subcarr_phi += (2 * M_PI * m_fsc) / (Real) m_srate;
     m_parms.clock_phi = m_parms.subcarr_phi + m_parms.clock_offset;
     // Clock phase recovery
     if (sign(m_parms.prev_bb) != sign(m_parms.subcarr_bb[0]))
     {
         m_parms.d_cphi = std::fmod(m_parms.clock_phi, M_PI);
         if (m_parms.d_cphi >= M_PI_2)
         {
             m_parms.d_cphi -= M_PI;
         }
         m_parms.clock_offset -= 0.005 * m_parms.d_cphi;
     }
     m_parms.clock_phi = std::fmod(m_parms.clock_phi, 2 * M_PI);
     m_parms.lo_clock = (m_parms.clock_phi < M_PI ? 1 : -1);
     /* Decimate band-limited signal */
     if (m_parms.numsamples % 8 == 0)
     {
         /* biphase symbol integrate & dump */
         m_parms.acc += m_parms.subcarr_bb[0] * m_parms.lo_clock;
         if (sign(m_parms.lo_clock) != sign(m_parms.prev_lo_clock))
         {
             ret = biphase(m_parms.acc, bit, m_parms.clock_phi - m_parms.prev_clock_phi);
             m_parms.acc = 0;
         }
         m_parms.prev_lo_clock = m_parms.lo_clock;
     }
     m_parms.numsamples++;
     m_parms.prev_bb = m_parms.subcarr_bb[0];
     m_parms.prev_clock_phi = m_parms.clock_phi;
     m_prev = demod;
     return ret;
 }
setSampleRate()
void RDSDemod::setSampleRate (int srate)
FIXME: fix rate for now.
Definition at line 70 of file rdsdemod.cpp.
 {
     (void) srate;
 }
sign()
int RDSDemod::sign (Real a) protected
Definition at line 211 of file rdsdemod.cpp.
Referenced by biphase(), and process().
 {
     return (a >= 0 ? 1 : 0);
 }
Member Data Documentation
acc
Real RDSDemod::acc
Definition at line 39 of file rdsdemod.h.
Referenced by biphase().
clock_offset
double RDSDemod::clock_offset
Definition at line 55 of file rdsdemod.h.
clock_phi
double RDSDemod::clock_phi
Definition at line 56 of file rdsdemod.h.
counter
int RDSDemod::counter
Definition at line 65 of file rdsdemod.h.
d_cphi
double RDSDemod::d_cphi
Definition at line 61 of file rdsdemod.h.
dbit
int RDSDemod::dbit
Definition at line 68 of file rdsdemod.h.
fclk
Real RDSDemod::fclk
Definition at line 41 of file rdsdemod.h.
lo_clock
Real RDSDemod::lo_clock
Definition at line 58 of file rdsdemod.h.
m_fsc
const Real RDSDemod::m_fsc = 1187.5 static private
Definition at line 80 of file rdsdemod.h.
Referenced by process().
m_parms
struct { ... } RDSDemod::m_parms
Referenced by biphase(), process(), and RDSDemod().
m_pllBeta
const Real RDSDemod::m_pllBeta = 50 static private
Definition at line 79 of file rdsdemod.h.
m_prev
Real RDSDemod::m_prev private
Definition at line 75 of file rdsdemod.h.
Referenced by process(), and RDSDemod().
m_report
struct { ... } RDSDemod::m_report
Referenced by biphase(), and RDSDemod().
m_srate
int RDSDemod::m_srate private
Definition at line 77 of file rdsdemod.h.
Referenced by biphase(), process(), and RDSDemod().
m_xv
Real RDSDemod::m_xv[2][2+1] private
Definition at line 71 of file rdsdemod.h.
Referenced by filter_lp_2400_iq(), and RDSDemod().
m_xw
Real RDSDemod::m_xw[1+1] private
Definition at line 73 of file rdsdemod.h.
Referenced by filter_lp_pll(), and RDSDemod().
m_yv
Real RDSDemod::m_yv[2][2+1] private
Definition at line 72 of file rdsdemod.h.
Referenced by filter_lp_2400_iq(), and RDSDemod().
m_yw
Real RDSDemod::m_yw[1+1] private
Definition at line 74 of file rdsdemod.h.
Referenced by filter_lp_pll(), and RDSDemod().
numsamples
int RDSDemod::numsamples
Definition at line 63 of file rdsdemod.h.
prev_acc
Real RDSDemod::prev_acc
Definition at line 64 of file rdsdemod.h.
prev_bb
Real RDSDemod::prev_bb
Definition at line 60 of file rdsdemod.h.
prev_clock_phi
double RDSDemod::prev_clock_phi
Definition at line 57 of file rdsdemod.h.
prev_lo_clock
Real RDSDemod::prev_lo_clock
Definition at line 59 of file rdsdemod.h.
qua
Real RDSDemod::qua
Definition at line 40 of file rdsdemod.h.
reading_frame
int RDSDemod::reading_frame
Definition at line 66 of file rdsdemod.h.
subcarr_bb
Real RDSDemod::subcarr_bb[2]
Definition at line 54 of file rdsdemod.h.
subcarr_phi
double RDSDemod::subcarr_phi
Definition at line 53 of file rdsdemod.h.
tot_errs
int RDSDemod::tot_errs[2]
Definition at line 67 of file rdsdemod.h.
The documentation for this class was generated from the following files:
plugins/channelrx/demodbfm/rdsdemod.h
plugins/channelrx/demodbfm/rdsdemod.cpp