SDRAngel: SampleSinkFifo Class Reference
SampleSinkFifo Class Reference
#include <samplesinkfifo.h>
Inherits QObject.
Signals
void dataReady ()
Public Member Functions
SampleSinkFifo (QObject *parent=nullptr)
SampleSinkFifo (int size, QObject *parent=nullptr)
SampleSinkFifo (const SampleSinkFifo &other)
~SampleSinkFifo ()
bool setSize (int size)
uint size () const
uint fill ()
uint write (const quint8 *data, uint count)
uint write (SampleVector::const_iterator begin, SampleVector::const_iterator end)
uint read (SampleVector::iterator begin, SampleVector::iterator end)
uint readBegin (uint count, SampleVector::iterator *part1Begin, SampleVector::iterator *part1End, SampleVector::iterator *part2Begin, SampleVector::iterator *part2End)
uint readCommit (uint count)
Private Member Functions
void create (uint s)
Private Attributes
QMutex m_mutex
QTime m_msgRateTimer
int m_suppressed
SampleVector m_data
uint m_size
uint m_fill
uint m_head
uint m_tail
Detailed Description
Definition at line 28 of file samplesinkfifo.h.
Constructor & Destructor Documentation
SampleSinkFifo() [1/3]
SampleSinkFifo::SampleSinkFifo (QObject * parent = nullptr)
Definition at line 37 of file samplesinkfifo.cpp.
References m_fill, m_head, m_size, m_suppressed, and m_tail.
                                               :
     QObject(parent),
     m_data()
 {
     m_suppressed = -1;
     m_size = 0;
     m_fill = 0;
     m_head = 0;
     m_tail = 0;
 }
SampleSinkFifo() [2/3]
SampleSinkFifo::SampleSinkFifo (int size, QObject * parent = nullptr)
Definition at line 48 of file samplesinkfifo.cpp.
References create(), and m_suppressed.
                                                         :
     QObject(parent),
     m_data()
 {
     m_suppressed = -1;
     create(size);
 }
SampleSinkFifo() [3/3]
SampleSinkFifo::SampleSinkFifo (const SampleSinkFifo & other)
Definition at line 57 of file samplesinkfifo.cpp.
References m_data, m_fill, m_head, m_size, m_suppressed, and m_tail.
                                                           :
     QObject(other.parent()),
     m_data(other.m_data)
 {
     m_suppressed = -1;
     m_size = m_data.size();
     m_fill = 0;
     m_head = 0;
     m_tail = 0;
 }
~SampleSinkFifo()
SampleSinkFifo::~SampleSinkFifo ()
Definition at line 68 of file samplesinkfifo.cpp.
References m_mutex, and m_size.
 {
     QMutexLocker mutexLocker(&m_mutex);
     m_size = 0;
 }
Member Function Documentation
create()
void SampleSinkFifo::create (uint s) private
Definition at line 23 of file samplesinkfifo.cpp.
References m_data, m_fill, m_head, m_size, and m_tail.
Referenced by SampleSinkFifo(), and setSize().
 {
     m_size = 0;
     m_fill = 0;
     m_head = 0;
     m_tail = 0;
     m_data.resize(s);
     m_size = m_data.size();
     if(m_size != s)
         qCritical("SampleSinkFifo: out of memory");
 }
dataReady
void SampleSinkFifo::dataReady () signal
Referenced by DSPDeviceMIMOEngine::handleSetMIMO(), and write().
fill()
uint SampleSinkFifo::fill () inline
Definition at line 53 of file samplesinkfifo.h.
References fill().
Referenced by fill(), ThreadedBasebandSampleSinkFifo::handleFifoData(), DSPDeviceSourceEngine::work(), DSPDeviceMIMOEngine::work(), DSPDeviceMIMOEngine::workSampleSink(), and ThreadedBasebandSampleSinkFifo::~ThreadedBasebandSampleSinkFifo().
 { QMutexLocker mutexLocker(&m_mutex); uint fill = m_fill; return fill; }
read()
uint SampleSinkFifo::read (SampleVector::iterator begin, SampleVector::iterator end)
Definition at line 167 of file samplesinkfifo.cpp.
References m_data, m_fill, m_head, m_mutex, m_size, and MIN.
 {
     QMutexLocker mutexLocker(&m_mutex);
     uint count = end - begin;
     uint total;
     uint remaining;
     uint len;
     total = MIN(count, m_fill);
     if(total < count)
         qCritical("SampleSinkFifo: underflow - missing %u samples", count - total);
     remaining = total;
     while(remaining > 0) {
         len = MIN(remaining, m_size - m_head);
         std::copy(m_data.begin() + m_head, m_data.begin() + m_head + len, begin);
         m_head += len;
         m_head %= m_size;
         m_fill -= len;
         begin += len;
         remaining -= len;
     }
     return total;
 }
readBegin()
uint SampleSinkFifo::readBegin (uint count, SampleVector::iterator * part1Begin, SampleVector::iterator * part1End, SampleVector::iterator * part2Begin, SampleVector::iterator * part2End)
Definition at line 193 of file samplesinkfifo.cpp.
References m_data, m_fill, m_head, m_mutex, m_size, and MIN.
Referenced by ThreadedBasebandSampleSinkFifo::handleFifoData(), DSPDeviceSourceEngine::work(), DSPDeviceMIMOEngine::work(), and DSPDeviceMIMOEngine::workSampleSink().
 {
     QMutexLocker mutexLocker(&m_mutex);
     uint total;
     uint remaining;
     uint len;
     uint head = m_head;
     total = MIN(count, m_fill);
     if(total < count)
         qCritical("SampleSinkFifo: underflow - missing %u samples", count - total);
     remaining = total;
     if(remaining > 0) {
         len = MIN(remaining, m_size - head);
         *part1Begin = m_data.begin() + head;
         *part1End = m_data.begin() + head + len;
         head += len;
         head %= m_size;
         remaining -= len;
     } else {
         *part1Begin = m_data.end();
         *part1End = m_data.end();
     }
     if(remaining > 0) {
         len = MIN(remaining, m_size - head);
         *part2Begin = m_data.begin() + head;
         *part2End = m_data.begin() + head + len;
     } else {
         *part2Begin = m_data.end();
         *part2End = m_data.end();
     }
     return total;
 }
readCommit()
uint SampleSinkFifo::readCommit (uint count)
Definition at line 231 of file samplesinkfifo.cpp.
References m_fill, m_head, m_mutex, and m_size.
Referenced by ThreadedBasebandSampleSinkFifo::handleFifoData(), DSPDeviceSourceEngine::work(), DSPDeviceMIMOEngine::work(), DSPDeviceMIMOEngine::workSampleSink(), and ThreadedBasebandSampleSinkFifo::~ThreadedBasebandSampleSinkFifo().
 {
     QMutexLocker mutexLocker(&m_mutex);
     if(count > m_fill) {
         qCritical("SampleSinkFifo: cannot commit more than available samples");
         count = m_fill;
     }
     m_head = (m_head + count) % m_size;
     m_fill -= count;
     return count;
 }
setSize()
bool SampleSinkFifo::setSize (int size)
Definition at line 75 of file samplesinkfifo.cpp.
References create(), and m_data.
Referenced by FileInput::applySettings(), Bladerf1Input::openDevice(), PerseusInput::openDevice(), AirspyInput::openDevice(), AirspyHFInput::openDevice(), PlutoSDRInput::openDevice(), RTLSDRInput::openDevice(), HackRFInput::openDevice(), SDRPlayInput::openDevice(), BladeRF2Input::openDevice(), SoapySDRInput::openDevice(), XTRXInput::openDevice(), LimeSDRInput::openDevice(), FCDProPlusInput::start(), FCDProInput::start(), FileInput::start(), and ThreadedBasebandSampleSinkFifo::ThreadedBasebandSampleSinkFifo().
 {
     create(size);
     return m_data.size() == (uint)size;
 }
size()
uint SampleSinkFifo::size () const inline
Definition at line 52 of file samplesinkfifo.h.
 { return m_size; }
write() [1/2]
uint SampleSinkFifo::write (const quint8 * data, uint count)
Definition at line 82 of file samplesinkfifo.cpp.
References dataReady(), m_data, m_fill, m_msgRateTimer, m_mutex, m_size, m_suppressed, m_tail, and MIN.
Referenced by Bladerf1InputThread::callback(), RTLSDRThread::callback(), SDRPlayThread::callback(), AirspyHFThread::callback(), PerseusThread::callback(), HackRFInputThread::callback(), AirspyThread::callback(), LimeSDRInputThread::callback(), TestMIThread::callback(), TestSourceThread::callback(), XTRXInputThread::callbackSI(), BladeRF2InputThread::callbackSI(), SoapySDRInputThread::callbackSI12(), SoapySDRInputThread::callbackSI16(), SoapySDRInputThread::callbackSI8(), SoapySDRInputThread::callbackSIF(), PlutoSDRInputThread::convert(), KiwiSDRWorker::onBinaryMessageReceived(), LocalSinkThread::processSamples(), RemoteInputUDPHandler::tick(), FCDProThread::work(), FCDProPlusThread::work(), ThreadedBasebandSampleSinkFifo::writeToFifo(), and FileInputThread::writeToSampleFifo().
 {
     QMutexLocker mutexLocker(&m_mutex);
     uint total;
     uint remaining;
     uint len;
     const Sample* begin = (const Sample*)data;
     count /= sizeof(Sample);
     total = MIN(count, m_size - m_fill);
     if(total < count) {
         if(m_suppressed < 0) {
             m_suppressed = 0;
             m_msgRateTimer.start();
             qCritical("SampleSinkFifo: overflow - dropping %u samples", count - total);
         } else {
             if(m_msgRateTimer.elapsed() > 2500) {
                 qCritical("SampleSinkFifo: %u messages dropped", m_suppressed);
                 qCritical("SampleSinkFifo: overflow - dropping %u samples", count - total);
                 m_suppressed = -1;
             } else {
                 m_suppressed++;
             }
         }
     }
     remaining = total;
     while(remaining > 0) {
         len = MIN(remaining, m_size - m_tail);
         std::copy(begin, begin + len, m_data.begin() + m_tail);
         m_tail += len;
         m_tail %= m_size;
         m_fill += len;
         begin += len;
         remaining -= len;
     }
     if(m_fill > 0)
         emit dataReady();
     return total;
 }
write() [2/2]
uint SampleSinkFifo::write (SampleVector::const_iterator begin, SampleVector::const_iterator end)
Definition at line 125 of file samplesinkfifo.cpp.
References dataReady(), m_data, m_fill, m_msgRateTimer, m_mutex, m_size, m_suppressed, m_tail, and MIN.
 {
     QMutexLocker mutexLocker(&m_mutex);
     uint count = end - begin;
     uint total;
     uint remaining;
     uint len;
     total = MIN(count, m_size - m_fill);
     if(total < count) {
         if(m_suppressed < 0) {
             m_suppressed = 0;
             m_msgRateTimer.start();
             qCritical("SampleSinkFifo: overflow - dropping %u samples", count - total);
         } else {
             if(m_msgRateTimer.elapsed() > 2500) {
                 qCritical("SampleSinkFifo: %u messages dropped", m_suppressed);
                 qCritical("SampleSinkFifo: overflow - dropping %u samples", count - total);
                 m_suppressed = -1;
             } else {
                 m_suppressed++;
             }
         }
     }
     remaining = total;
     while(remaining > 0) {
         len = MIN(remaining, m_size - m_tail);
         std::copy(begin, begin + len, m_data.begin() + m_tail);
         m_tail += len;
         m_tail %= m_size;
         m_fill += len;
         begin += len;
         remaining -= len;
     }
     if(m_fill > 0)
         emit dataReady();
     return total;
 }
Member Data Documentation
m_data
SampleVector SampleSinkFifo::m_data private
Definition at line 36 of file samplesinkfifo.h.
Referenced by create(), read(), readBegin(), SampleSinkFifo(), setSize(), and write().
m_fill
uint SampleSinkFifo::m_fill private
Definition at line 39 of file samplesinkfifo.h.
Referenced by create(), read(), readBegin(), readCommit(), SampleSinkFifo(), and write().
m_head
uint SampleSinkFifo::m_head private
Definition at line 40 of file samplesinkfifo.h.
Referenced by create(), read(), readBegin(), readCommit(), and SampleSinkFifo().
m_msgRateTimer
QTime SampleSinkFifo::m_msgRateTimer private
Definition at line 33 of file samplesinkfifo.h.
Referenced by write().
m_mutex
QMutex SampleSinkFifo::m_mutex private
Definition at line 32 of file samplesinkfifo.h.
Referenced by read(), readBegin(), readCommit(), write(), and ~SampleSinkFifo().
m_size
uint SampleSinkFifo::m_size private
Definition at line 38 of file samplesinkfifo.h.
Referenced by create(), read(), readBegin(), readCommit(), SampleSinkFifo(), write(), and ~SampleSinkFifo().
m_suppressed
int SampleSinkFifo::m_suppressed private
Definition at line 34 of file samplesinkfifo.h.
Referenced by SampleSinkFifo(), and write().
m_tail
uint SampleSinkFifo::m_tail private
Definition at line 41 of file samplesinkfifo.h.
Referenced by create(), SampleSinkFifo(), and write().
The documentation for this class was generated from the following files:
sdrbase/dsp/samplesinkfifo.h
sdrbase/dsp/samplesinkfifo.cpp