SDRAngel: qrtplib::RTPRandomRandS Class Reference
qrtplib::RTPRandomRandS Class Reference
#include <rtprandomrands.h>
Public Member Functions
RTPRandomRandS ()
~RTPRandomRandS ()
int Init ()
uint8_t GetRandom8 ()
uint16_t GetRandom16 ()
uint32_t GetRandom32 ()
double GetRandomDouble ()
Public Member Functions inherited from qrtplib::RTPRandom
RTPRandom ()
virtual ~RTPRandom ()
uint32_t PickSeed ()
Private Attributes
bool initialized
Additional Inherited Members
Static Public Member Functions inherited from qrtplib::RTPRandom
static RTPRandom * CreateDefaultRandomNumberGenerator ()
Detailed Description
A random number generator which tries to use the rand_s function on the Win32 platform.
Definition at line 52 of file rtprandomrands.h.
Constructor & Destructor Documentation
RTPRandomRandS()
qrtplib::RTPRandomRandS::RTPRandomRandS ()
Definition at line 53 of file rtprandomrands.cpp.
References initialized.
Referenced by GetRandomDouble().
 {
     initialized = false;
 }
~RTPRandomRandS()
qrtplib::RTPRandomRandS::~RTPRandomRandS ()
Definition at line 58 of file rtprandomrands.cpp.
Referenced by GetRandomDouble().
 {
 }
Member Function Documentation
GetRandom16()
uint16_t qrtplib::RTPRandomRandS::GetRandom16 () virtual
Returns a random sixteen bit value.
Implements qrtplib::RTPRandom.
Definition at line 72 of file rtprandomrands.cpp.
Referenced by GetRandomDouble().
 {
     return 0;
 }
GetRandom32()
uint32_t qrtplib::RTPRandomRandS::GetRandom32 () virtual
Returns a random thirty-two bit value.
Implements qrtplib::RTPRandom.
Definition at line 77 of file rtprandomrands.cpp.
Referenced by GetRandomDouble().
 {
     return 0;
 }
GetRandom8()
uint8_t qrtplib::RTPRandomRandS::GetRandom8 () virtual
Returns a random eight bit value.
Implements qrtplib::RTPRandom.
Definition at line 67 of file rtprandomrands.cpp.
Referenced by GetRandomDouble().
 {
     return 0;
 }
GetRandomDouble()
double qrtplib::RTPRandomRandS::GetRandomDouble () virtual
Returns a random number between $0.0$ and $1.0$.
Implements qrtplib::RTPRandom.
Definition at line 82 of file rtprandomrands.cpp.
References ERR_RTP_RTPRANDOMRANDS_NOTSUPPORTED, GetRandom16(), GetRandom32(), GetRandom8(), i, Init(), initialized, RTPRANDOM_2POWMIN63, RTPRandomRandS(), and ~RTPRandomRandS().
 {
     return 0;
 }
Init()
int qrtplib::RTPRandomRandS::Init ()
Initialize the random number generator.
Definition at line 62 of file rtprandomrands.cpp.
References ERR_RTP_RTPRANDOMRANDS_NOTSUPPORTED.
Referenced by GetRandomDouble().
 {
     return ERR_RTP_RTPRANDOMRANDS_NOTSUPPORTED;
 }
Member Data Documentation
initialized
bool qrtplib::RTPRandomRandS::initialized private
Definition at line 66 of file rtprandomrands.h.
Referenced by GetRandomDouble(), and RTPRandomRandS().
The documentation for this class was generated from the following files:
qrtplib/rtprandomrands.h
qrtplib/rtprandomrands.cpp