SDRAngel: SSBMod Class Reference
SSBMod Class Reference
#include <ssbmod.h>
Classes
class MsgConfigureChannelizer
class MsgConfigureFileSourceName
class MsgConfigureFileSourceSeek
class MsgConfigureFileSourceStreamTiming
class MsgConfigureSSBMod
class MsgReportFileSourceStreamData
class MsgReportFileSourceStreamTiming
Signals
void levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples)
Public Member Functions
SSBMod (DeviceAPI *deviceAPI)
~SSBMod ()
virtual void destroy ()
void setSpectrumSampleSink (BasebandSampleSink *sampleSink)
virtual void pull (Sample &sample)
virtual void pullAudio (int nbSamples)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
uint32_t getAudioSampleRate () const
double getMagSq () const
CWKeyer * getCWKeyer ()
Public Member Functions inherited from BasebandSampleSource
BasebandSampleSource ()
virtual ~BasebandSampleSource ()
void feed (SampleSourceFifo *sampleFifo, int nbSamples)
SampleSourceFifo & getSampleSourceFifo ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
void setDeviceSampleSourceFifo (SampleSourceFifo *deviceSampleFifo)
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channeltx.modssb"
static const QString m_channelId = "SSBMod"
Private Types
enum RateState { RSInitialFill, RSRunning }
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applyAudioSampleRate (int sampleRate)
void applyFeedbackAudioSampleRate (unsigned int sampleRate)
void processOneSample (Complex &ci)
void applyChannelSettings (int basebandSampleRate, int outputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const SSBModSettings &settings, bool force=false)
void pullAF (Complex &sample)
void pushFeedback (Complex sample)
void calculateLevel (Complex &sample)
void modulateSample ()
void openFileStream ()
void seekFileStream (int seekPercentage)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const SSBModSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const SSBModSettings &settings, bool force)
void webapiReverseSendCWSettings (const CWKeyerSettings &settings)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSource * m_threadedChannelizer
UpChannelizer * m_channelizer
int m_basebandSampleRate
int m_outputSampleRate
int m_inputFrequencyOffset
SSBModSettings m_settings
NCOF m_carrierNco
NCOF m_toneNco
Complex m_modSample
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
bool m_interpolatorConsumed
Interpolator m_feedbackInterpolator
Real m_feedbackInterpolatorDistance
Real m_feedbackInterpolatorDistanceRemain
bool m_feedbackInterpolatorConsumed
fftfilt * m_SSBFilter
fftfilt * m_DSBFilter
Complex * m_SSBFilterBuffer
Complex * m_DSBFilterBuffer
int m_SSBFilterBufferIndex
int m_DSBFilterBufferIndex
BasebandSampleSink * m_sampleSink
SampleVector m_sampleBuffer
fftfilt::cmplx m_sum
int m_undersampleCount
int m_sumCount
double m_magsq
MovingAverageUtil< double, double, 16 > m_movingAverage
quint32 m_audioSampleRate
AudioVector m_audioBuffer
uint m_audioBufferFill
AudioFifo m_audioFifo
quint32 m_feedbackAudioSampleRate
AudioVector m_feedbackAudioBuffer
uint m_feedbackAudioBufferFill
AudioFifo m_feedbackAudioFifo
QMutex m_settingsMutex
std::ifstream m_ifstream
QString m_fileName
quint64 m_fileSize
raw file size (bytes)
quint32 m_recordLength
record length in seconds computed from file size
int m_sampleRate
quint32 m_levelCalcCount
Real m_peakLevel
Real m_levelSum
CWKeyer m_cwKeyer
AudioCompressorSnd m_audioCompressor
int m_agcStepLength
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Static Private Attributes
static const int m_ssbFftLen = 1024
static const int m_levelNbSamples = 480
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSource
void handleInputMessages ()
void handleWriteToFifo (int nbSamples)
void handleWriteToDeviceFifo (int nbSamples)
Protected Member Functions inherited from BasebandSampleSource
void handleWriteToFifo (SampleSourceFifo *sampleFifo, int nbSamples)
Protected Attributes inherited from BasebandSampleSource
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
SampleSourceFifo m_sampleFifo
Internal FIFO for multi-channel processing.
SampleSourceFifo * m_deviceSampleFifo
Reference to the device FIFO for single channel processing.
Detailed Description
Definition at line 49 of file ssbmod.h.
Member Enumeration Documentation
RateState
enum SSBMod::RateState private
Enumerator
RSInitialFill
RSRunning
Definition at line 268 of file ssbmod.h.
                    {
         RSInitialFill,
         RSRunning
     };
Constructor & Destructor Documentation
SSBMod()
SSBMod::SSBMod (DeviceAPI * deviceAPI)
Definition at line 55 of file ssbmod.cpp.
References AudioDeviceManager::addAudioSink(), AudioDeviceManager::addAudioSource(), DeviceAPI::addChannelSource(), DeviceAPI::addChannelSourceAPI(), applyChannelSettings(), applyFeedbackAudioSampleRate(), applySettings(), DSPEngine::getAudioDeviceManager(), BasebandSampleSource::getInputMessageQueue(), AudioDeviceManager::getInputSampleRate(), AudioDeviceManager::getOutputSampleRate(), AudioCompressorSnd::initSimple(), DSPEngine::instance(), m_audioBuffer, m_audioBufferFill, m_audioCompressor, m_audioFifo, m_audioSampleRate, SSBModSettings::m_bandwidth, m_basebandSampleRate, m_channelId, m_channelizer, m_cwKeyer, m_deviceAPI, m_DSBFilter, m_DSBFilterBuffer, m_feedbackAudioBuffer, m_feedbackAudioBufferFill, m_feedbackAudioFifo, m_feedbackAudioSampleRate, m_inputFrequencyOffset, SSBModSettings::m_lowCutoff, m_magsq, m_networkManager, m_outputSampleRate, m_settings, m_ssbFftLen, m_SSBFilter, m_SSBFilterBuffer, m_sum, m_sumCount, m_threadedChannelizer, m_toneNco, m_undersampleCount, networkManagerFinished(), CWKeyer::reset(), NCOF::setFreq(), and CWKeyer::setSampleRate().
Referenced by SSBMod::MsgReportFileSourceStreamData::MsgReportFileSourceStreamData().
                                    :
     ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSource),
     m_deviceAPI(deviceAPI),
     m_basebandSampleRate(48000),
     m_outputSampleRate(48000),
     m_inputFrequencyOffset(0),
     m_SSBFilter(0),
     m_DSBFilter(0),
     m_SSBFilterBuffer(0),
     m_DSBFilterBuffer(0),
     m_SSBFilterBufferIndex(0),
     m_DSBFilterBufferIndex(0),
     m_sampleSink(0),
     m_audioFifo(4800),
     m_feedbackAudioFifo(48000),
     m_settingsMutex(QMutex::Recursive),
     m_fileSize(0),
     m_recordLength(0),
     m_sampleRate(48000),
     m_levelCalcCount(0),
     m_peakLevel(0.0f),
     m_levelSum(0.0f),
     m_agcStepLength(2400)
 {
     setObjectName(m_channelId);
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSource(&m_audioFifo, getInputMessageQueue());
     m_audioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getInputSampleRate();
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSink(&m_feedbackAudioFifo, getInputMessageQueue());
     m_feedbackAudioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getOutputSampleRate();
     applyFeedbackAudioSampleRate(m_feedbackAudioSampleRate);
     m_SSBFilter = new fftfilt(m_settings.m_lowCutoff / m_audioSampleRate, m_settings.m_bandwidth / m_audioSampleRate, m_ssbFftLen);
     m_DSBFilter = new fftfilt((2.0f * m_settings.m_bandwidth) / m_audioSampleRate, 2 * m_ssbFftLen);
     m_SSBFilterBuffer = new Complex[m_ssbFftLen>>1]; // filter returns data exactly half of its size
     m_DSBFilterBuffer = new Complex[m_ssbFftLen];
     std::fill(m_SSBFilterBuffer, m_SSBFilterBuffer+(m_ssbFftLen>>1), Complex{0,0});
     std::fill(m_DSBFilterBuffer, m_DSBFilterBuffer+m_ssbFftLen, Complex{0,0});
 //    memset(m_SSBFilterBuffer, 0, sizeof(Complex)*(m_ssbFftLen>>1));
 //    memset(m_DSBFilterBuffer, 0, sizeof(Complex)*(m_ssbFftLen));
     m_audioBuffer.resize(1<<14);
     m_audioBufferFill = 0;
     m_feedbackAudioBuffer.resize(1<<14);
     m_feedbackAudioBufferFill = 0;
     m_sum.real(0.0f);
     m_sum.imag(0.0f);
     m_undersampleCount = 0;
     m_sumCount = 0;
     m_magsq = 0.0;
     m_toneNco.setFreq(1000.0, m_audioSampleRate);
     m_cwKeyer.setSampleRate(48000);
     m_cwKeyer.reset();
     m_audioCompressor.initSimple(
         m_audioSampleRate,
         50,    // pregain (dB)
         -30,   // threshold (dB)
         20,    // knee (dB)
         12,    // ratio (dB)
         0.003, // attack (s)
         0.25   // release (s)
     );
     applyChannelSettings(m_basebandSampleRate, m_outputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new UpChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSource(m_channelizer, this);
     m_deviceAPI->addChannelSource(m_threadedChannelizer);
     m_deviceAPI->addChannelSourceAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~SSBMod()
SSBMod::~SSBMod ()
Definition at line 136 of file ssbmod.cpp.
References DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo, m_channelizer, m_deviceAPI, m_DSBFilter, m_DSBFilterBuffer, m_feedbackAudioFifo, m_networkManager, m_SSBFilter, m_SSBFilterBuffer, m_threadedChannelizer, networkManagerFinished(), AudioDeviceManager::removeAudioSink(), AudioDeviceManager::removeAudioSource(), DeviceAPI::removeChannelSource(), and DeviceAPI::removeChannelSourceAPI().
Referenced by SSBMod::MsgReportFileSourceStreamData::MsgReportFileSourceStreamData().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_feedbackAudioFifo);
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSource(&m_audioFifo);
     m_deviceAPI->removeChannelSourceAPI(this);
     m_deviceAPI->removeChannelSource(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete m_SSBFilter;
     delete m_DSBFilter;
     delete[] m_SSBFilterBuffer;
     delete[] m_DSBFilterBuffer;
 }
Member Function Documentation
applyAudioSampleRate()
void SSBMod::applyAudioSampleRate (int sampleRate) private
Definition at line 738 of file ssbmod.cpp.
References applyFeedbackAudioSampleRate(), DSPConfigureAudio::AudioInput, Interpolator::create(), SSBMod::MsgConfigureChannelizer::create(), fftfilt::create_dsb_filter(), fftfilt::create_filter(), BasebandSampleSource::getMessageQueueToGUI(), AudioCompressorSnd::initState(), m_audioCompressor, m_audioSampleRate, SSBModSettings::m_bandwidth, m_cwKeyer, m_DSBFilter, m_feedbackAudioSampleRate, SSBModSettings::m_inputFrequencyOffset, BasebandSampleSource::m_inputMessageQueue, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, SSBModSettings::m_lowCutoff, m_outputSampleRate, AudioCompressorSnd::m_rate, m_settings, m_settingsMutex, m_SSBFilter, SSBModSettings::m_toneFrequency, m_toneNco, SSBModSettings::m_usb, MessageQueue::push(), NCOF::setFreq(), and CWKeyer::setSampleRate().
Referenced by applySettings(), and handleMessage().
 {
     qDebug("SSBMod::applyAudioSampleRate: %d", sampleRate);
     MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
             sampleRate, m_settings.m_inputFrequencyOffset);
     m_inputMessageQueue.push(channelConfigMsg);
     m_settingsMutex.lock();
     m_interpolatorDistanceRemain = 0;
     m_interpolatorConsumed = false;
     m_interpolatorDistance = (Real) sampleRate / (Real) m_outputSampleRate;
     m_interpolator.create(48, sampleRate, m_settings.m_bandwidth, 3.0);
     float band = m_settings.m_bandwidth;
     float lowCutoff = m_settings.m_lowCutoff;
     bool usb = m_settings.m_usb;
     if (band < 100.0f) // at least 100 Hz
     {
         band = 100.0f;
         lowCutoff = 0;
     }
     if (band - lowCutoff < 100.0f) {
         lowCutoff = band - 100.0f;
     }
     m_SSBFilter->create_filter(lowCutoff / sampleRate, band / sampleRate);
     m_DSBFilter->create_dsb_filter((2.0f * band) / sampleRate);
     m_settings.m_bandwidth = band;
     m_settings.m_lowCutoff = lowCutoff;
     m_settings.m_usb = usb;
     m_toneNco.setFreq(m_settings.m_toneFrequency, sampleRate);
     m_cwKeyer.setSampleRate(sampleRate);
     m_audioCompressor.m_rate = sampleRate;
     m_audioCompressor.initState();
     m_settingsMutex.unlock();
     m_audioSampleRate = sampleRate;
     if (getMessageQueueToGUI())
     {
         DSPConfigureAudio *cfg = new DSPConfigureAudio(m_audioSampleRate, DSPConfigureAudio::AudioInput);
         getMessageQueueToGUI()->push(cfg);
     }
     applyFeedbackAudioSampleRate(m_feedbackAudioSampleRate);
 }
applyChannelSettings()
void SSBMod::applyChannelSettings (int basebandSampleRate, int outputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 811 of file ssbmod.cpp.
References Interpolator::create(), m_audioSampleRate, SSBModSettings::m_bandwidth, m_basebandSampleRate, m_carrierNco, m_inputFrequencyOffset, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, m_outputSampleRate, m_settings, m_settingsMutex, and NCOF::setFreq().
Referenced by handleMessage(), SSBMod(), and start().
 {
     qDebug() << "SSBMod::applyChannelSettings:"
             << " basebandSampleRate: " << basebandSampleRate
             << " outputSampleRate: " << outputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if ((inputFrequencyOffset != m_inputFrequencyOffset) ||
         (outputSampleRate != m_outputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_carrierNco.setFreq(inputFrequencyOffset, outputSampleRate);
         m_settingsMutex.unlock();
     }
     if ((outputSampleRate != m_outputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_interpolatorDistanceRemain = 0;
         m_interpolatorConsumed = false;
         m_interpolatorDistance = (Real) m_audioSampleRate / (Real) outputSampleRate;
         m_interpolator.create(48, m_audioSampleRate, m_settings.m_bandwidth, 3.0);
         m_settingsMutex.unlock();
     }
     m_basebandSampleRate = basebandSampleRate;
     m_outputSampleRate = outputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applyFeedbackAudioSampleRate()
void SSBMod::applyFeedbackAudioSampleRate (unsigned int sampleRate) private
Definition at line 794 of file ssbmod.cpp.
References Interpolator::create(), m_audioSampleRate, m_feedbackAudioSampleRate, m_feedbackInterpolator, m_feedbackInterpolatorConsumed, m_feedbackInterpolatorDistance, m_feedbackInterpolatorDistanceRemain, m_settingsMutex, and leansdr::min().
Referenced by applyAudioSampleRate(), applySettings(), handleMessage(), and SSBMod().
 {
     qDebug("SSBMod::applyFeedbackAudioSampleRate: %u", sampleRate);
     m_settingsMutex.lock();
     m_feedbackInterpolatorDistanceRemain = 0;
     m_feedbackInterpolatorConsumed = false;
     m_feedbackInterpolatorDistance = (Real) sampleRate / (Real) m_audioSampleRate;
     Real cutoff = std::min(sampleRate, m_audioSampleRate) / 2.2f;
     m_feedbackInterpolator.create(48, sampleRate, cutoff, 3.0);
     m_settingsMutex.unlock();
     m_feedbackAudioSampleRate = sampleRate;
 }
applySettings()
void SSBMod::applySettings (const SSBModSettings & settings, bool force = false) private
Definition at line 841 of file ssbmod.cpp.
References AudioDeviceManager::addAudioSink(), AudioDeviceManager::addAudioSource(), applyAudioSampleRate(), applyFeedbackAudioSampleRate(), Interpolator::create(), fftfilt::create_dsb_filter(), fftfilt::create_filter(), DSPEngine::getAudioDeviceManager(), AudioDeviceManager::getInputDeviceIndex(), BasebandSampleSource::getInputMessageQueue(), AudioDeviceManager::getInputSampleRate(), AudioDeviceManager::getOutputDeviceIndex(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), SSBModSettings::m_agc, SSBModSettings::m_audioBinaural, SSBModSettings::m_audioDeviceName, m_audioFifo, SSBModSettings::m_audioFlipChannels, SSBModSettings::m_audioMute, m_audioSampleRate, SSBModSettings::m_bandwidth, SSBModSettings::m_dsb, m_DSBFilter, m_DSBFilterBuffer, m_DSBFilterBufferIndex, SSBModSettings::m_feedbackAudioDeviceName, m_feedbackAudioFifo, m_feedbackAudioSampleRate, SSBModSettings::m_inputFrequencyOffset, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, SSBModSettings::m_lowCutoff, SSBModSettings::m_modAFInput, m_outputSampleRate, SSBModSettings::m_playLoop, SSBModSettings::m_reverseAPIAddress, SSBModSettings::m_reverseAPIChannelIndex, SSBModSettings::m_reverseAPIDeviceIndex, SSBModSettings::m_reverseAPIPort, SSBModSettings::m_rgbColor, m_settings, m_settingsMutex, SSBModSettings::m_spanLog2, m_ssbFftLen, m_SSBFilter, m_SSBFilterBuffer, m_SSBFilterBufferIndex, SSBModSettings::m_title, SSBModSettings::m_toneFrequency, m_toneNco, SSBModSettings::m_usb, SSBModSettings::m_useReverseAPI, SSBModSettings::m_volumeFactor, NCOF::setFreq(), and webapiReverseSendSettings().
Referenced by handleMessage(), and SSBMod().
 {
     float band = settings.m_bandwidth;
     float lowCutoff = settings.m_lowCutoff;
     bool usb = settings.m_usb;
     QList<QString> reverseAPIKeys;
     if ((settings.m_inputFrequencyOffset != m_settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if ((settings.m_bandwidth != m_settings.m_bandwidth) || force) {
         reverseAPIKeys.append("bandwidth");
     }
     if ((settings.m_lowCutoff != m_settings.m_lowCutoff) || force) {
         reverseAPIKeys.append("lowCutoff");
     }
     if ((settings.m_usb != m_settings.m_usb) || force) {
         reverseAPIKeys.append("usb");
     }
     if ((settings.m_toneFrequency != m_settings.m_toneFrequency) || force) {
         reverseAPIKeys.append("toneFrequency");
     }
     if ((settings.m_volumeFactor != m_settings.m_volumeFactor) || force) {
         reverseAPIKeys.append("volumeFactor");
     }
     if ((settings.m_spanLog2 != m_settings.m_spanLog2) || force) {
         reverseAPIKeys.append("spanLog2");
     }
     if ((settings.m_audioBinaural != m_settings.m_audioBinaural) || force) {
         reverseAPIKeys.append("audioBinaural");
     }
     if ((settings.m_audioFlipChannels != m_settings.m_audioFlipChannels) || force) {
         reverseAPIKeys.append("audioFlipChannels");
     }
     if ((settings.m_dsb != m_settings.m_dsb) || force) {
         reverseAPIKeys.append("dsb");
     }
     if ((settings.m_audioMute != m_settings.m_audioMute) || force) {
         reverseAPIKeys.append("audioMute");
     }
     if ((settings.m_playLoop != m_settings.m_playLoop) || force) {
         reverseAPIKeys.append("playLoop");
     }
     if ((settings.m_agc != m_settings.m_agc) || force) {
         reverseAPIKeys.append("agc");
     }
     if ((settings.m_rgbColor != m_settings.m_rgbColor) || force) {
         reverseAPIKeys.append("rgbColor");
     }
     if ((settings.m_title != m_settings.m_title) || force) {
         reverseAPIKeys.append("title");
     }
     if ((settings.m_modAFInput != m_settings.m_modAFInput) || force) {
         reverseAPIKeys.append("modAFInput");
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force) {
         reverseAPIKeys.append("audioDeviceName");
     }
     if ((settings.m_bandwidth != m_settings.m_bandwidth) ||
         (settings.m_lowCutoff != m_settings.m_lowCutoff) || force)
     {
         if (band < 100.0f) // at least 100 Hz
         {
             band = 100.0f;
             lowCutoff = 0;
         }
         if (band - lowCutoff < 100.0f) {
             lowCutoff = band - 100.0f;
         }
         m_settingsMutex.lock();
         m_interpolatorDistanceRemain = 0;
         m_interpolatorConsumed = false;
         m_interpolatorDistance = (Real) m_audioSampleRate / (Real) m_outputSampleRate;
         m_interpolator.create(48, m_audioSampleRate, band, 3.0);
         m_SSBFilter->create_filter(lowCutoff / m_audioSampleRate, band / m_audioSampleRate);
         m_DSBFilter->create_dsb_filter((2.0f * band) / m_audioSampleRate);
         m_settingsMutex.unlock();
     }
     if ((settings.m_toneFrequency != m_settings.m_toneFrequency) || force)
     {
         m_settingsMutex.lock();
         m_toneNco.setFreq(settings.m_toneFrequency, m_audioSampleRate);
         m_settingsMutex.unlock();
     }
     if ((settings.m_dsb != m_settings.m_dsb) || force)
     {
         if (settings.m_dsb)
         {
             std::fill(m_DSBFilterBuffer, m_DSBFilterBuffer+m_ssbFftLen, Complex{0,0});
             //memset(m_DSBFilterBuffer, 0, sizeof(Complex)*(m_ssbFftLen));
             m_DSBFilterBufferIndex = 0;
         }
         else
         {
             std::fill(m_SSBFilterBuffer, m_SSBFilterBuffer+(m_ssbFftLen>>1), Complex{0,0});
             //memset(m_SSBFilterBuffer, 0, sizeof(Complex)*(m_ssbFftLen>>1));
             m_SSBFilterBufferIndex = 0;
         }
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force)
     {
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getInputDeviceIndex(settings.m_audioDeviceName);
         audioDeviceManager->addAudioSource(&m_audioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getInputSampleRate(audioDeviceIndex);
         if (m_audioSampleRate != audioSampleRate) {
             applyAudioSampleRate(audioSampleRate);
         }
     }
     if ((settings.m_feedbackAudioDeviceName != m_settings.m_feedbackAudioDeviceName) || force)
     {
         reverseAPIKeys.append("feedbackAudioDeviceName");
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getOutputDeviceIndex(settings.m_feedbackAudioDeviceName);
         audioDeviceManager->addAudioSink(&m_feedbackAudioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getOutputSampleRate(audioDeviceIndex);
         if (m_feedbackAudioSampleRate != audioSampleRate) {
             reverseAPIKeys.append("feedbackAudioSampleRate");
             applyFeedbackAudioSampleRate(audioSampleRate);
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     m_settings.m_bandwidth = band;
     m_settings.m_lowCutoff = lowCutoff;
     m_settings.m_usb = usb;
 }
calculateLevel()
void SSBMod::calculateLevel (Complex & sample) private
Definition at line 555 of file ssbmod.cpp.
References levelChanged(), m_levelCalcCount, m_levelNbSamples, m_levelSum, m_peakLevel, leansdr::max(), and sqrt().
Referenced by modulateSample().
 {
     Real t = sample.real(); // TODO: possibly adjust depending on sample type
     if (m_levelCalcCount < m_levelNbSamples)
     {
         m_peakLevel = std::max(std::fabs(m_peakLevel), t);
         m_levelSum += t * t;
         m_levelCalcCount++;
     }
     else
     {
         qreal rmsLevel = sqrt(m_levelSum / m_levelNbSamples);
         //qDebug("NFMMod::calculateLevel: %f %f", rmsLevel, m_peakLevel);
         emit levelChanged(rmsLevel, m_peakLevel, m_levelNbSamples);
         m_peakLevel = 0.0f;
         m_levelSum = 0.0f;
         m_levelCalcCount = 0;
     }
 }
deserialize()
bool SSBMod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 993 of file ssbmod.cpp.
References SSBMod::MsgConfigureSSBMod::create(), SSBModSettings::deserialize(), BasebandSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and SSBModSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureSSBMod *msg = MsgConfigureSSBMod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureSSBMod *msg = MsgConfigureSSBMod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void SSBMod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 208 of file ssbmod.h.
 { delete this; }
getAudioSampleRate()
uint32_t SSBMod::getAudioSampleRate () const inline
Definition at line 249 of file ssbmod.h.
References m_audioSampleRate.
Referenced by SSBModGUI::applyBandwidths(), and SSBModGUI::handleMessage().
 { return m_audioSampleRate; }
getCenterFrequency()
virtual qint64 SSBMod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 220 of file ssbmod.h.
References deserialize(), SSBModSettings::m_inputFrequencyOffset, SSBMod::MsgConfigureSSBMod::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getCWKeyer()
CWKeyer* SSBMod::getCWKeyer () inline
Definition at line 252 of file ssbmod.h.
References m_cwKeyer.
Referenced by SSBModGUI::SSBModGUI().
 { return &m_cwKeyer; }
getIdentifier()
virtual void SSBMod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 218 of file ssbmod.h.
 { id = objectName(); }
getMagSq()
double SSBMod::getMagSq () const inline
Definition at line 250 of file ssbmod.h.
References m_magsq.
Referenced by SSBModGUI::tick(), and webapiFormatChannelReport().
 { return m_magsq; }
getNbSinkStreams()
virtual int SSBMod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 225 of file ssbmod.h.
 { return 1; }
getNbSourceStreams()
virtual int SSBMod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 226 of file ssbmod.h.
 { return 0; }
getStreamCenterFrequency()
virtual qint64 SSBMod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 228 of file ssbmod.h.
References SSBModSettings::m_inputFrequencyOffset, SSBMod::MsgConfigureSSBMod::m_settings, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void SSBMod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 219 of file ssbmod.h.
References SSBMod::MsgConfigureSSBMod::m_settings, and SSBModSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool SSBMod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSource.
Definition at line 589 of file ssbmod.cpp.
References applyAudioSampleRate(), applyChannelSettings(), applyFeedbackAudioSampleRate(), applySettings(), DSPConfigureAudio::AudioInput, DSPConfigureAudio::AudioOutput, UpChannelizer::configure(), SSBMod::MsgReportFileSourceStreamTiming::create(), DSPConfigureAudio::getAudioType(), UpChannelizer::MsgChannelizerNotification::getBasebandSampleRate(), SSBMod::MsgConfigureChannelizer::getCenterFrequency(), SSBMod::MsgConfigureFileSourceName::getFileName(), SSBMod::MsgConfigureSSBMod::getForce(), UpChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSource::getInputMessageQueue(), BasebandSampleSource::getMessageQueueToGUI(), SSBMod::MsgConfigureFileSourceSeek::getPercentage(), UpChannelizer::MsgChannelizerNotification::getSampleRate(), SSBMod::MsgConfigureChannelizer::getSampleRate(), DSPConfigureAudio::getSampleRate(), SSBMod::MsgConfigureSSBMod::getSettings(), CWKeyer::MsgConfigureCWKeyer::getSettings(), m_audioSampleRate, m_channelizer, m_fileName, m_fileSize, m_ifstream, m_settings, SSBModSettings::m_useReverseAPI, Message::match(), openFileStream(), MessageQueue::push(), seekFileStream(), and webapiReverseSendCWSettings().
Referenced by setSpectrumSampleSink().
 {
     if (UpChannelizer::MsgChannelizerNotification::match(cmd))
     {
         UpChannelizer::MsgChannelizerNotification& notif = (UpChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "SSBMod::handleMessage: MsgChannelizerNotification";
         applyChannelSettings(notif.getBasebandSampleRate(), notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "SSBMod::handleMessage: MsgConfigureChannelizer: sampleRate: " << cfg.getSampleRate()
                 << " centerFrequency: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureSSBMod::match(cmd))
     {
         MsgConfigureSSBMod& cfg = (MsgConfigureSSBMod&) cmd;
         qDebug() << "SSBMod::handleMessage: MsgConfigureSSBMod";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgConfigureFileSourceName::match(cmd))
     {
         MsgConfigureFileSourceName& conf = (MsgConfigureFileSourceName&) cmd;
         m_fileName = conf.getFileName();
         openFileStream();
         return true;
     }
     else if (MsgConfigureFileSourceSeek::match(cmd))
     {
         MsgConfigureFileSourceSeek& conf = (MsgConfigureFileSourceSeek&) cmd;
         int seekPercentage = conf.getPercentage();
         seekFileStream(seekPercentage);
         return true;
     }
     else if (MsgConfigureFileSourceStreamTiming::match(cmd))
     {
         std::size_t samplesCount;
         if (m_ifstream.eof()) {
             samplesCount = m_fileSize / sizeof(Real);
         } else {
             samplesCount = m_ifstream.tellg() / sizeof(Real);
         }
         if (getMessageQueueToGUI())
         {
             MsgReportFileSourceStreamTiming *report;
             report = MsgReportFileSourceStreamTiming::create(samplesCount);
             getMessageQueueToGUI()->push(report);
         }
         return true;
     }
     else if (CWKeyer::MsgConfigureCWKeyer::match(cmd))
     {
         const CWKeyer::MsgConfigureCWKeyer& cfg = (CWKeyer::MsgConfigureCWKeyer&) cmd;
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendCWSettings(cfg.getSettings());
         }
         return true;
     }
     else if (DSPConfigureAudio::match(cmd))
     {
         DSPConfigureAudio& cfg = (DSPConfigureAudio&) cmd;
         uint32_t sampleRate = cfg.getSampleRate();
         DSPConfigureAudio::AudioType audioType = cfg.getAudioType();
         qDebug() << "SSBMod::handleMessage: DSPConfigureAudio:"
                 << " sampleRate: " << sampleRate
                 << " audioType: " << audioType;
         if (audioType == DSPConfigureAudio::AudioInput)
         {
             if (sampleRate != m_audioSampleRate) {
                 applyAudioSampleRate(sampleRate);
             }
         }
         else if (audioType == DSPConfigureAudio::AudioOutput)
         {
             if (sampleRate != m_audioSampleRate) {
                 applyFeedbackAudioSampleRate(sampleRate);
             }
         }
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         return false;
     }
 }
levelChanged
void SSBMod::levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples) signal
Level changed
Parameters
rmsLevel RMS level in range 0.0 - 1.0
peakLevel Peak level in range 0.0 - 1.0
numSamples Number of audio samples analyzed
Referenced by calculateLevel().
modulateSample()
void SSBMod::modulateSample () private
Definition at line 207 of file ssbmod.cpp.
References calculateLevel(), m_audioBufferFill, SSBModSettings::m_feedbackAudioEnable, SSBModSettings::m_feedbackVolumeFactor, m_modSample, m_settings, pullAF(), and pushFeedback().
Referenced by pull().
 {
     pullAF(m_modSample);
     if (m_settings.m_feedbackAudioEnable) {
         pushFeedback(m_modSample * m_settings.m_feedbackVolumeFactor * 16384.0f);
     }
     calculateLevel(m_modSample);
     m_audioBufferFill++;
 }
networkManagerFinished
void SSBMod::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 1329 of file ssbmod.cpp.
Referenced by SSBMod(), and ~SSBMod().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "SSBMod::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("SSBMod::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openFileStream()
void SSBMod::openFileStream () private
Definition at line 700 of file ssbmod.cpp.
References SSBMod::MsgReportFileSourceStreamData::create(), BasebandSampleSource::getMessageQueueToGUI(), m_fileName, m_fileSize, m_ifstream, m_recordLength, m_sampleRate, and MessageQueue::push().
Referenced by handleMessage().
 {
     if (m_ifstream.is_open()) {
         m_ifstream.close();
     }
     m_ifstream.open(m_fileName.toStdString().c_str(), std::ios::binary | std::ios::ate);
     m_fileSize = m_ifstream.tellg();
     m_ifstream.seekg(0,std::ios_base::beg);
     m_sampleRate = 48000; // fixed rate
     m_recordLength = m_fileSize / (sizeof(Real) * m_sampleRate);
     qDebug() << "SSBMod::openFileStream: " << m_fileName.toStdString().c_str()
             << " fileSize: " << m_fileSize << "bytes"
             << " length: " << m_recordLength << " seconds";
     if (getMessageQueueToGUI())
     {
         MsgReportFileSourceStreamData *report;
         report = MsgReportFileSourceStreamData::create(m_sampleRate, m_recordLength);
         getMessageQueueToGUI()->push(report);
     }
 }
processOneSample()
void SSBMod::processOneSample (Complex & ci) private
Definition at line 534 of file ssbmod.cpp.
References AudioFifo::clear(), m_feedbackAudioBuffer, m_feedbackAudioBufferFill, m_feedbackAudioFifo, m_feedbackInterpolatorDistance, and AudioFifo::write().
Referenced by pushFeedback().
 {
     m_feedbackAudioBuffer[m_feedbackAudioBufferFill].l = ci.real();
     m_feedbackAudioBuffer[m_feedbackAudioBufferFill].r = ci.imag();
     ++m_feedbackAudioBufferFill;
     if (m_feedbackAudioBufferFill >= m_feedbackAudioBuffer.size())
     {
         uint res = m_feedbackAudioFifo.write((const quint8*)&m_feedbackAudioBuffer[0], m_feedbackAudioBufferFill);
         if (res != m_feedbackAudioBufferFill)
         {
             qDebug("AMDemod::pushFeedback: %u/%u audio samples written m_feedbackInterpolatorDistance: %f",
                 res, m_feedbackAudioBufferFill, m_feedbackInterpolatorDistance);
             m_feedbackAudioFifo.clear();
         }
         m_feedbackAudioBufferFill = 0;
     }
 }
pull()
void SSBMod::pull (Sample & sample) virtual
Implements BasebandSampleSource.
Definition at line 155 of file ssbmod.cpp.
References MovingAverageUtil< T, Total, N >::asDouble(), Interpolator::decimate(), Interpolator::interpolate(), m_carrierNco, Sample::m_imag, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_magsq, m_modSample, m_movingAverage, Sample::m_real, m_settingsMutex, modulateSample(), NCOF::nextIQ(), SDR_TX_SCALED, and SDR_TX_SCALEF.
Referenced by setSpectrumSampleSink().
 {
     Complex ci;
     m_settingsMutex.lock();
     if (m_interpolatorDistance > 1.0f) // decimate
     {
         modulateSample();
         while (!m_interpolator.decimate(&m_interpolatorDistanceRemain, m_modSample, &ci))
         {
             modulateSample();
         }
     }
     else
     {
         if (m_interpolator.interpolate(&m_interpolatorDistanceRemain, m_modSample, &ci))
         {
             modulateSample();
         }
     }
     m_interpolatorDistanceRemain += m_interpolatorDistance;
     ci *= m_carrierNco.nextIQ(); // shift to carrier frequency
     ci *= 0.891235351562f * SDR_TX_SCALEF; //scaling at -1 dB to account for possible filter overshoot
     m_settingsMutex.unlock();
     double magsq = ci.real() * ci.real() + ci.imag() * ci.imag();
     magsq /= (SDR_TX_SCALED*SDR_TX_SCALED);
     m_movingAverage(magsq);
     m_magsq = m_movingAverage.asDouble();
     sample.m_real = (FixReal) ci.real();
     sample.m_imag = (FixReal) ci.imag();
 }
pullAF()
void SSBMod::pullAF (Complex & sample) private
Definition at line 219 of file ssbmod.cpp.
References AudioCompressorSnd::compress(), BasebandSampleSink::feed(), CWKeyer::getCWSmoother(), CWSmoother::getFadeSample(), CWKeyer::getSample(), i, SSBModSettings::m_agc, SSBModSettings::m_audioBinaural, m_audioBuffer, m_audioBufferFill, m_audioCompressor, SSBModSettings::m_audioFlipChannels, SSBModSettings::m_audioMute, m_cwKeyer, SSBModSettings::m_dsb, m_DSBFilter, m_DSBFilterBuffer, m_DSBFilterBufferIndex, m_ifstream, SSBModSettings::m_modAFInput, SSBModSettings::m_playLoop, m_sampleBuffer, m_sampleSink, m_settings, SSBModSettings::m_spanLog2, m_ssbFftLen, m_SSBFilter, m_SSBFilterBuffer, m_SSBFilterBufferIndex, m_sum, m_sumCount, m_toneNco, m_undersampleCount, SSBModSettings::m_usb, SSBModSettings::m_volumeFactor, NCOF::next(), NCOF::nextIQ(), NCOF::nextQI(), fftfilt::runDSB(), fftfilt::runSSB(), SDR_TX_SCALEF, NCOF::setPhase(), SSBModSettings::SSBModInputAudio, SSBModSettings::SSBModInputCWTone, SSBModSettings::SSBModInputFile, SSBModSettings::SSBModInputNone, and SSBModSettings::SSBModInputTone.
Referenced by modulateSample().
 {
     if (m_settings.m_audioMute)
     {
         sample.real(0.0f);
         sample.imag(0.0f);
         return;
     }
     Complex ci;
     fftfilt::cmplx *filtered;
     int n_out = 0;
     int decim = 1<<(m_settings.m_spanLog2 - 1);
     unsigned char decim_mask = decim - 1; // counter LSB bit mask for decimation by 2^(m_scaleLog2 - 1)
     switch (m_settings.m_modAFInput)
     {
     case SSBModSettings::SSBModInputTone:
         if (m_settings.m_dsb)
         {
             Real t = m_toneNco.next()/1.25;
             sample.real(t);
             sample.imag(t);
         }
         else
         {
             if (m_settings.m_usb) {
                 sample = m_toneNco.nextIQ();
             } else {
                 sample = m_toneNco.nextQI();
             }
         }
         break;
     case SSBModSettings::SSBModInputFile:
         // Monaural (mono):
         // sox f4exb_call.wav --encoding float --endian little f4exb_call.raw
         // ffplay -f f32le -ar 48k -ac 1 f4exb_call.raw
         // Binaural (stereo):
         // sox f4exb_call.wav --encoding float --endian little f4exb_call.raw
         // ffplay -f f32le -ar 48k -ac 2 f4exb_call.raw
         if (m_ifstream.is_open())
         {
             if (m_ifstream.eof())
             {
                 if (m_settings.m_playLoop)
                 {
                     m_ifstream.clear();
                     m_ifstream.seekg(0, std::ios::beg);
                 }
             }
             if (m_ifstream.eof())
             {
                 ci.real(0.0f);
                 ci.imag(0.0f);
             }
             else
             {
                 if (m_settings.m_audioBinaural)
                 {
                     Complex c;
                     m_ifstream.read(reinterpret_cast<char*>(&c), sizeof(Complex));
                     if (m_settings.m_audioFlipChannels)
                     {
                         ci.real(c.imag() * m_settings.m_volumeFactor);
                         ci.imag(c.real() * m_settings.m_volumeFactor);
                     }
                     else
                     {
                         ci = c * m_settings.m_volumeFactor;
                     }
                 }
                 else
                 {
                     Real real;
                     m_ifstream.read(reinterpret_cast<char*>(&real), sizeof(Real));
                     if (m_settings.m_agc)
                     {
                         real = m_audioCompressor.compress(real);
                         ci.real(real);
                         ci.imag(0.0f);
                         ci *= m_settings.m_volumeFactor;
                     }
                     else
                     {
                         ci.real(real * m_settings.m_volumeFactor);
                         ci.imag(0.0f);
                     }
                 }
             }
         }
         else
         {
             ci.real(0.0f);
             ci.imag(0.0f);
         }
         break;
     case SSBModSettings::SSBModInputAudio:
         if (m_settings.m_audioBinaural)
         {
             if (m_settings.m_audioFlipChannels)
             {
                 ci.real((m_audioBuffer[m_audioBufferFill].r / SDR_TX_SCALEF) * m_settings.m_volumeFactor);
                 ci.imag((m_audioBuffer[m_audioBufferFill].l / SDR_TX_SCALEF) * m_settings.m_volumeFactor);
             }
             else
             {
                 ci.real((m_audioBuffer[m_audioBufferFill].l / SDR_TX_SCALEF) * m_settings.m_volumeFactor);
                 ci.imag((m_audioBuffer[m_audioBufferFill].r / SDR_TX_SCALEF) * m_settings.m_volumeFactor);
             }
         }
         else
         {
             if (m_settings.m_agc)
             {
                 ci.real(((m_audioBuffer[m_audioBufferFill].l + m_audioBuffer[m_audioBufferFill].r)  / 65536.0f));
                 ci.real(m_audioCompressor.compress(ci.real()));
                 ci.imag(0.0f);
                 ci *= m_settings.m_volumeFactor;
             }
             else
             {
                 ci.real(((m_audioBuffer[m_audioBufferFill].l + m_audioBuffer[m_audioBufferFill].r)  / 65536.0f) * m_settings.m_volumeFactor);
                 ci.imag(0.0f);
             }
         }
         break;
     case SSBModSettings::SSBModInputCWTone:
         Real fadeFactor;
         if (m_cwKeyer.getSample())
         {
             m_cwKeyer.getCWSmoother().getFadeSample(true, fadeFactor);
             if (m_settings.m_dsb)
             {
                 Real t = m_toneNco.next() * fadeFactor;
                 sample.real(t);
                 sample.imag(t);
             }
             else
             {
                 if (m_settings.m_usb) {
                     sample = m_toneNco.nextIQ() * fadeFactor;
                 } else {
                     sample = m_toneNco.nextQI() * fadeFactor;
                 }
             }
         }
         else
         {
             if (m_cwKeyer.getCWSmoother().getFadeSample(false, fadeFactor))
             {
                 if (m_settings.m_dsb)
                 {
                     Real t = (m_toneNco.next() * fadeFactor)/1.25;
                     sample.real(t);
                     sample.imag(t);
                 }
                 else
                 {
                     if (m_settings.m_usb) {
                         sample = m_toneNco.nextIQ() * fadeFactor;
                     } else {
                         sample = m_toneNco.nextQI() * fadeFactor;
                     }
                 }
             }
             else
             {
                 sample.real(0.0f);
                 sample.imag(0.0f);
                 m_toneNco.setPhase(0);
             }
         }
         break;
     case SSBModSettings::SSBModInputNone:
     default:
         sample.real(0.0f);
         sample.imag(0.0f);
         break;
     }
     if ((m_settings.m_modAFInput == SSBModSettings::SSBModInputFile)
        || (m_settings.m_modAFInput == SSBModSettings::SSBModInputAudio)) // real audio
     {
         if (m_settings.m_dsb)
         {
             n_out = m_DSBFilter->runDSB(ci, &filtered);
             if (n_out > 0)
             {
                 memcpy((void *) m_DSBFilterBuffer, (const void *) filtered, n_out*sizeof(Complex));
                 m_DSBFilterBufferIndex = 0;
             }
             sample = m_DSBFilterBuffer[m_DSBFilterBufferIndex];
             m_DSBFilterBufferIndex++;
         }
         else
         {
             n_out = m_SSBFilter->runSSB(ci, &filtered, m_settings.m_usb);
             if (n_out > 0)
             {
                 memcpy((void *) m_SSBFilterBuffer, (const void *) filtered, n_out*sizeof(Complex));
                 m_SSBFilterBufferIndex = 0;
             }
             sample = m_SSBFilterBuffer[m_SSBFilterBufferIndex];
             m_SSBFilterBufferIndex++;
         }
         if (n_out > 0)
         {
             for (int i = 0; i < n_out; i++)
             {
                 // Downsample by 2^(m_scaleLog2 - 1) for SSB band spectrum display
                 // smart decimation with bit gain using float arithmetic (23 bits significand)
                 m_sum += filtered[i];
                 if (!(m_undersampleCount++ & decim_mask))
                 {
                     Real avgr = (m_sum.real() / decim) * 0.891235351562f * SDR_TX_SCALEF; //scaling at -1 dB to account for possible filter overshoot
                     Real avgi = (m_sum.imag() / decim) * 0.891235351562f * SDR_TX_SCALEF;
                     if (!m_settings.m_dsb & !m_settings.m_usb)
                     { // invert spectrum for LSB
                         m_sampleBuffer.push_back(Sample(avgi, avgr));
                     }
                     else
                     {
                         m_sampleBuffer.push_back(Sample(avgr, avgi));
                     }
                     m_sum.real(0.0);
                     m_sum.imag(0.0);
                 }
             }
         }
     } // Real audio
     else if ((m_settings.m_modAFInput == SSBModSettings::SSBModInputTone)
           || (m_settings.m_modAFInput == SSBModSettings::SSBModInputCWTone)) // tone
     {
         m_sum += sample;
         if (!(m_undersampleCount++ & decim_mask))
         {
             Real avgr = (m_sum.real() / decim) * 0.891235351562f * SDR_TX_SCALEF; //scaling at -1 dB to account for possible filter overshoot
             Real avgi = (m_sum.imag() / decim) * 0.891235351562f * SDR_TX_SCALEF;
             if (!m_settings.m_dsb & !m_settings.m_usb)
             { // invert spectrum for LSB
                 m_sampleBuffer.push_back(Sample(avgi, avgr));
             }
             else
             {
                 m_sampleBuffer.push_back(Sample(avgr, avgi));
             }
             m_sum.real(0.0);
             m_sum.imag(0.0);
         }
         if (m_sumCount < (m_settings.m_dsb ? m_ssbFftLen : m_ssbFftLen>>1))
         {
             n_out = 0;
             m_sumCount++;
         }
         else
         {
             n_out = m_sumCount;
             m_sumCount = 0;
         }
     }
     if (n_out > 0)
     {
         if (m_sampleSink != 0)
         {
             m_sampleSink->feed(m_sampleBuffer.begin(), m_sampleBuffer.end(), !m_settings.m_dsb);
         }
         m_sampleBuffer.clear();
     }
 }
pullAudio()
void SSBMod::pullAudio (int nbSamples) virtual
Reimplemented from BasebandSampleSource.
Definition at line 194 of file ssbmod.cpp.
References m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_basebandSampleRate, and AudioFifo::read().
Referenced by setSpectrumSampleSink().
 {
     unsigned int nbSamplesAudio = nbSamples * ((Real) m_audioSampleRate / (Real) m_basebandSampleRate);
     if (nbSamplesAudio > m_audioBuffer.size())
     {
         m_audioBuffer.resize(nbSamplesAudio);
     }
     m_audioFifo.read(reinterpret_cast<quint8*>(&m_audioBuffer[0]), nbSamplesAudio);
     m_audioBufferFill = 0;
 }
pushFeedback()
void SSBMod::pushFeedback (Complex sample) private
Definition at line 512 of file ssbmod.cpp.
References Interpolator::decimate(), Interpolator::interpolate(), m_feedbackInterpolator, m_feedbackInterpolatorDistance, m_feedbackInterpolatorDistanceRemain, and processOneSample().
Referenced by modulateSample().
 {
     Complex ci;
     if (m_feedbackInterpolatorDistance < 1.0f) // interpolate
     {
         while (!m_feedbackInterpolator.interpolate(&m_feedbackInterpolatorDistanceRemain, c, &ci))
         {
             processOneSample(ci);
             m_feedbackInterpolatorDistanceRemain += m_feedbackInterpolatorDistance;
         }
     }
     else // decimate
     {
         if (m_feedbackInterpolator.decimate(&m_feedbackInterpolatorDistanceRemain, c, &ci))
         {
             processOneSample(ci);
             m_feedbackInterpolatorDistanceRemain += m_feedbackInterpolatorDistance;
         }
     }
 }
seekFileStream()
void SSBMod::seekFileStream (int seekPercentage) private
Definition at line 725 of file ssbmod.cpp.
References m_ifstream, m_recordLength, m_sampleRate, and m_settingsMutex.
Referenced by handleMessage().
 {
     QMutexLocker mutexLocker(&m_settingsMutex);
     if (m_ifstream.is_open())
     {
         int seekPoint = ((m_recordLength * seekPercentage) / 100) * m_sampleRate;
         seekPoint *= sizeof(Real);
         m_ifstream.clear();
         m_ifstream.seekg(seekPoint, std::ios::beg);
     }
 }
serialize()
QByteArray SSBMod::serialize () const virtual
Implements ChannelAPI.
Definition at line 988 of file ssbmod.cpp.
References m_settings, and SSBModSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
setSpectrumSampleSink()
void SSBMod::setSpectrumSampleSink (BasebandSampleSink * sampleSink) inline
Definition at line 210 of file ssbmod.h.
References handleMessage(), m_sampleSink, pull(), pullAudio(), start(), and stop().
Referenced by SSBModGUI::SSBModGUI().
 { m_sampleSink = sampleSink; }
start()
void SSBMod::start () virtual
Implements BasebandSampleSource.
Definition at line 576 of file ssbmod.cpp.
References applyChannelSettings(), AudioFifo::clear(), m_audioFifo, m_basebandSampleRate, SSBModSettings::m_inputFrequencyOffset, m_inputFrequencyOffset, m_outputSampleRate, and m_settings.
Referenced by setSpectrumSampleSink().
 {
     qDebug() << "SSBMod::start: m_outputSampleRate: " << m_outputSampleRate
             << " m_inputFrequencyOffset: " << m_settings.m_inputFrequencyOffset;
     m_audioFifo.clear();
     applyChannelSettings(m_basebandSampleRate, m_outputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void SSBMod::stop () virtual
Implements BasebandSampleSource.
Definition at line 585 of file ssbmod.cpp.
Referenced by setSpectrumSampleSink().
 {
 }
webapiFormatChannelReport()
void SSBMod::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 1200 of file ssbmod.cpp.
References CalcDb::dbPower(), getMagSq(), SWGSDRangel::SWGChannelReport::getSsbModReport(), m_audioSampleRate, m_outputSampleRate, SWGSDRangel::SWGSSBModReport::setAudioSampleRate(), SWGSDRangel::SWGSSBModReport::setChannelPowerDb(), and SWGSDRangel::SWGSSBModReport::setChannelSampleRate().
Referenced by webapiReportGet().
 {
     response.getSsbModReport()->setChannelPowerDb(CalcDb::dbPower(getMagSq()));
     response.getSsbModReport()->setAudioSampleRate(m_audioSampleRate);
     response.getSsbModReport()->setChannelSampleRate(m_outputSampleRate);
 }
webapiFormatChannelSettings()
void SSBMod::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const SSBModSettings & settings) private
Definition at line 1148 of file ssbmod.cpp.
References SWGSDRangel::SWGSSBModSettings::getAudioDeviceName(), SWGSDRangel::SWGSSBModSettings::getCwKeyer(), SWGSDRangel::SWGSSBModSettings::getReverseApiAddress(), CWKeyer::getSettings(), SWGSDRangel::SWGChannelSettings::getSsbModSettings(), SWGSDRangel::SWGSSBModSettings::getTitle(), SSBModSettings::m_agc, SSBModSettings::m_audioBinaural, SSBModSettings::m_audioDeviceName, SSBModSettings::m_audioFlipChannels, SSBModSettings::m_audioMute, SSBModSettings::m_bandwidth, m_cwKeyer, SSBModSettings::m_dsb, SSBModSettings::m_inputFrequencyOffset, SSBModSettings::m_lowCutoff, SSBModSettings::m_modAFInput, SSBModSettings::m_playLoop, SSBModSettings::m_reverseAPIAddress, SSBModSettings::m_reverseAPIChannelIndex, SSBModSettings::m_reverseAPIDeviceIndex, SSBModSettings::m_reverseAPIPort, SSBModSettings::m_rgbColor, SSBModSettings::m_spanLog2, SSBModSettings::m_title, SSBModSettings::m_toneFrequency, SSBModSettings::m_usb, SSBModSettings::m_useReverseAPI, SSBModSettings::m_volumeFactor, SWGSDRangel::SWGSSBModSettings::setAgc(), SWGSDRangel::SWGSSBModSettings::setAudioBinaural(), SWGSDRangel::SWGSSBModSettings::setAudioDeviceName(), SWGSDRangel::SWGSSBModSettings::setAudioFlipChannels(), SWGSDRangel::SWGSSBModSettings::setAudioMute(), SWGSDRangel::SWGSSBModSettings::setBandwidth(), SWGSDRangel::SWGSSBModSettings::setCwKeyer(), SWGSDRangel::SWGSSBModSettings::setDsb(), SWGSDRangel::SWGSSBModSettings::setInputFrequencyOffset(), SWGSDRangel::SWGSSBModSettings::setLowCutoff(), SWGSDRangel::SWGSSBModSettings::setModAfInput(), SWGSDRangel::SWGSSBModSettings::setPlayLoop(), SWGSDRangel::SWGSSBModSettings::setReverseApiAddress(), SWGSDRangel::SWGSSBModSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGSSBModSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGSSBModSettings::setReverseApiPort(), SWGSDRangel::SWGSSBModSettings::setRgbColor(), SWGSDRangel::SWGSSBModSettings::setSpanLog2(), SWGSDRangel::SWGSSBModSettings::setTitle(), SWGSDRangel::SWGSSBModSettings::setToneFrequency(), SWGSDRangel::SWGSSBModSettings::setUsb(), SWGSDRangel::SWGSSBModSettings::setUseReverseApi(), SWGSDRangel::SWGSSBModSettings::setVolumeFactor(), and CWKeyer::webapiFormatChannelSettings().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getSsbModSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getSsbModSettings()->setBandwidth(settings.m_bandwidth);
     response.getSsbModSettings()->setLowCutoff(settings.m_lowCutoff);
     response.getSsbModSettings()->setUsb(settings.m_usb ? 1 : 0);
     response.getSsbModSettings()->setToneFrequency(settings.m_toneFrequency);
     response.getSsbModSettings()->setVolumeFactor(settings.m_volumeFactor);
     response.getSsbModSettings()->setSpanLog2(settings.m_spanLog2);
     response.getSsbModSettings()->setAudioBinaural(settings.m_audioBinaural ? 1 : 0);
     response.getSsbModSettings()->setAudioFlipChannels(settings.m_audioFlipChannels ? 1 : 0);
     response.getSsbModSettings()->setDsb(settings.m_dsb ? 1 : 0);
     response.getSsbModSettings()->setAudioMute(settings.m_audioMute ? 1 : 0);
     response.getSsbModSettings()->setPlayLoop(settings.m_playLoop ? 1 : 0);
     response.getSsbModSettings()->setAgc(settings.m_agc ? 1 : 0);
     response.getSsbModSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getSsbModSettings()->getTitle()) {
         *response.getSsbModSettings()->getTitle() = settings.m_title;
     } else {
         response.getSsbModSettings()->setTitle(new QString(settings.m_title));
     }
     response.getSsbModSettings()->setModAfInput((int) settings.m_modAFInput);
     if (response.getSsbModSettings()->getAudioDeviceName()) {
         *response.getSsbModSettings()->getAudioDeviceName() = settings.m_audioDeviceName;
     } else {
         response.getSsbModSettings()->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     if (!response.getSsbModSettings()->getCwKeyer()) {
         response.getSsbModSettings()->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings);
     }
     SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = response.getSsbModSettings()->getCwKeyer();
     const CWKeyerSettings& cwKeyerSettings = m_cwKeyer.getSettings();
     m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     response.getSsbModSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getSsbModSettings()->getReverseApiAddress()) {
         *response.getSsbModSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getSsbModSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getSsbModSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getSsbModSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getSsbModSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int SSBMod::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 1137 of file ssbmod.cpp.
References SWGSDRangel::SWGChannelReport::getSsbModReport(), SWGSDRangel::SWGSSBModReport::init(), SWGSDRangel::SWGChannelReport::setSsbModReport(), and webapiFormatChannelReport().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setSsbModReport(new SWGSDRangel::SWGSSBModReport());
     response.getSsbModReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendCWSettings()
void SSBMod::webapiReverseSendCWSettings (const CWKeyerSettings & settings) private
Definition at line 1298 of file ssbmod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), SWGSDRangel::SWGSSBModSettings::getCwKeyer(), SWGSDRangel::SWGChannelSettings::getSsbModSettings(), m_cwKeyer, m_networkManager, m_networkRequest, SSBModSettings::m_reverseAPIAddress, SSBModSettings::m_reverseAPIChannelIndex, SSBModSettings::m_reverseAPIDeviceIndex, SSBModSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGSSBModSettings::setCwKeyer(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGChannelSettings::setSsbModSettings(), and CWKeyer::webapiFormatChannelSettings().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setChannelType(new QString("SSBMod"));
     swgChannelSettings->setSsbModSettings(new SWGSDRangel::SWGSSBModSettings());
     SWGSDRangel::SWGSSBModSettings *swgSSBModSettings = swgChannelSettings->getSsbModSettings();
     swgSSBModSettings->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings());
     SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = swgSSBModSettings->getCwKeyer();
     m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex)
             .arg(m_settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiReverseSendSettings()
void SSBMod::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const SSBModSettings & settings, bool force) private
Definition at line 1207 of file ssbmod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), SWGSDRangel::SWGSSBModSettings::getCwKeyer(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), CWKeyer::getSettings(), SWGSDRangel::SWGChannelSettings::getSsbModSettings(), SSBModSettings::m_agc, SSBModSettings::m_audioBinaural, SSBModSettings::m_audioDeviceName, SSBModSettings::m_audioFlipChannels, SSBModSettings::m_audioMute, SSBModSettings::m_bandwidth, m_cwKeyer, SSBModSettings::m_dsb, SSBModSettings::m_inputFrequencyOffset, SSBModSettings::m_lowCutoff, SSBModSettings::m_modAFInput, m_networkManager, m_networkRequest, SSBModSettings::m_playLoop, SSBModSettings::m_reverseAPIAddress, SSBModSettings::m_reverseAPIChannelIndex, SSBModSettings::m_reverseAPIDeviceIndex, SSBModSettings::m_reverseAPIPort, SSBModSettings::m_rgbColor, SSBModSettings::m_spanLog2, SSBModSettings::m_title, SSBModSettings::m_toneFrequency, SSBModSettings::m_usb, SSBModSettings::m_volumeFactor, SWGSDRangel::SWGSSBModSettings::setAgc(), SWGSDRangel::SWGSSBModSettings::setAudioBinaural(), SWGSDRangel::SWGSSBModSettings::setAudioDeviceName(), SWGSDRangel::SWGSSBModSettings::setAudioFlipChannels(), SWGSDRangel::SWGSSBModSettings::setAudioMute(), SWGSDRangel::SWGSSBModSettings::setBandwidth(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGSSBModSettings::setCwKeyer(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGSSBModSettings::setDsb(), SWGSDRangel::SWGSSBModSettings::setInputFrequencyOffset(), SWGSDRangel::SWGSSBModSettings::setLowCutoff(), SWGSDRangel::SWGSSBModSettings::setModAfInput(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGSSBModSettings::setPlayLoop(), SWGSDRangel::SWGSSBModSettings::setRgbColor(), SWGSDRangel::SWGSSBModSettings::setSpanLog2(), SWGSDRangel::SWGChannelSettings::setSsbModSettings(), SWGSDRangel::SWGSSBModSettings::setTitle(), SWGSDRangel::SWGSSBModSettings::setToneFrequency(), SWGSDRangel::SWGSSBModSettings::setUsb(), SWGSDRangel::SWGSSBModSettings::setVolumeFactor(), and CWKeyer::webapiFormatChannelSettings().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("SSBMod"));
     swgChannelSettings->setSsbModSettings(new SWGSDRangel::SWGSSBModSettings());
     SWGSDRangel::SWGSSBModSettings *swgSSBModSettings = swgChannelSettings->getSsbModSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgSSBModSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("bandwidth") || force) {
         swgSSBModSettings->setBandwidth(settings.m_bandwidth);
     }
     if (channelSettingsKeys.contains("lowCutoff") || force) {
         swgSSBModSettings->setLowCutoff(settings.m_lowCutoff);
     }
     if (channelSettingsKeys.contains("usb") || force) {
         swgSSBModSettings->setUsb(settings.m_usb ? 1 : 0);
     }
     if (channelSettingsKeys.contains("toneFrequency") || force) {
         swgSSBModSettings->setToneFrequency(settings.m_toneFrequency);
     }
     if (channelSettingsKeys.contains("volumeFactor") || force) {
         swgSSBModSettings->setVolumeFactor(settings.m_volumeFactor);
     }
     if (channelSettingsKeys.contains("spanLog2") || force) {
         swgSSBModSettings->setSpanLog2(settings.m_spanLog2);
     }
     if (channelSettingsKeys.contains("audioBinaural") || force) {
         swgSSBModSettings->setAudioBinaural(settings.m_audioBinaural ? 1 : 0);
     }
     if (channelSettingsKeys.contains("audioFlipChannels") || force) {
         swgSSBModSettings->setAudioFlipChannels(settings.m_audioFlipChannels ? 1 : 0);
     }
     if (channelSettingsKeys.contains("dsb") || force) {
         swgSSBModSettings->setDsb(settings.m_dsb ? 1 : 0);
     }
     if (channelSettingsKeys.contains("audioMute") || force) {
         swgSSBModSettings->setAudioMute(settings.m_audioMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("playLoop") || force) {
         swgSSBModSettings->setPlayLoop(settings.m_playLoop ? 1 : 0);
     }
     if (channelSettingsKeys.contains("agc") || force) {
         swgSSBModSettings->setAgc(settings.m_agc ? 1 : 0);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgSSBModSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgSSBModSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("modAFInput") || force) {
         swgSSBModSettings->setModAfInput((int) settings.m_modAFInput);
     }
     if (channelSettingsKeys.contains("audioDeviceName") || force) {
         swgSSBModSettings->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     if (force)
     {
         const CWKeyerSettings& cwKeyerSettings = m_cwKeyer.getSettings();
         swgSSBModSettings->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings());
         SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = swgSSBModSettings->getCwKeyer();
         m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int SSBMod::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 1010 of file ssbmod.cpp.
References SWGSDRangel::SWGChannelSettings::getSsbModSettings(), SWGSDRangel::SWGSSBModSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setSsbModSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setSsbModSettings(new SWGSDRangel::SWGSSBModSettings());
     response.getSsbModSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int SSBMod::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 1021 of file ssbmod.cpp.
References SSBMod::MsgConfigureSSBMod::create(), CWKeyer::MsgConfigureCWKeyer::create(), SSBMod::MsgConfigureChannelizer::create(), SWGSDRangel::SWGSSBModSettings::getAgc(), SWGSDRangel::SWGSSBModSettings::getAudioBinaural(), SWGSDRangel::SWGSSBModSettings::getAudioDeviceName(), SWGSDRangel::SWGSSBModSettings::getAudioFlipChannels(), SWGSDRangel::SWGSSBModSettings::getAudioMute(), SWGSDRangel::SWGSSBModSettings::getBandwidth(), SWGSDRangel::SWGSSBModSettings::getCwKeyer(), SWGSDRangel::SWGSSBModSettings::getDsb(), SWGSDRangel::SWGSSBModSettings::getInputFrequencyOffset(), CWKeyer::getInputMessageQueue(), SWGSDRangel::SWGSSBModSettings::getLowCutoff(), SWGSDRangel::SWGSSBModSettings::getModAfInput(), SWGSDRangel::SWGSSBModSettings::getPlayLoop(), SWGSDRangel::SWGSSBModSettings::getReverseApiAddress(), SWGSDRangel::SWGSSBModSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGSSBModSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGSSBModSettings::getReverseApiPort(), SWGSDRangel::SWGSSBModSettings::getRgbColor(), CWKeyer::getSettings(), SWGSDRangel::SWGSSBModSettings::getSpanLog2(), SWGSDRangel::SWGChannelSettings::getSsbModSettings(), SWGSDRangel::SWGSSBModSettings::getTitle(), SWGSDRangel::SWGSSBModSettings::getToneFrequency(), SWGSDRangel::SWGSSBModSettings::getUsb(), SWGSDRangel::SWGSSBModSettings::getUseReverseApi(), SWGSDRangel::SWGSSBModSettings::getVolumeFactor(), SSBModSettings::m_agc, SSBModSettings::m_audioBinaural, SSBModSettings::m_audioDeviceName, SSBModSettings::m_audioFlipChannels, SSBModSettings::m_audioMute, m_audioSampleRate, SSBModSettings::m_bandwidth, m_cwKeyer, SSBModSettings::m_dsb, BasebandSampleSource::m_guiMessageQueue, SSBModSettings::m_inputFrequencyOffset, BasebandSampleSource::m_inputMessageQueue, SSBModSettings::m_lowCutoff, SSBModSettings::m_modAFInput, SSBModSettings::m_playLoop, SSBModSettings::m_reverseAPIAddress, SSBModSettings::m_reverseAPIChannelIndex, SSBModSettings::m_reverseAPIDeviceIndex, SSBModSettings::m_reverseAPIPort, SSBModSettings::m_rgbColor, m_settings, SSBModSettings::m_spanLog2, SSBModSettings::m_title, SSBModSettings::m_toneFrequency, SSBModSettings::m_usb, SSBModSettings::m_useReverseAPI, SSBModSettings::m_volumeFactor, MessageQueue::push(), webapiFormatChannelSettings(), and CWKeyer::webapiSettingsPutPatch().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     SSBModSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getSsbModSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("bandwidth")) {
         settings.m_bandwidth = response.getSsbModSettings()->getBandwidth();
     }
     if (channelSettingsKeys.contains("lowCutoff")) {
         settings.m_lowCutoff = response.getSsbModSettings()->getLowCutoff();
     }
     if (channelSettingsKeys.contains("usb")) {
         settings.m_usb = response.getSsbModSettings()->getUsb() != 0;
     }
     if (channelSettingsKeys.contains("toneFrequency")) {
         settings.m_toneFrequency = response.getSsbModSettings()->getToneFrequency();
     }
     if (channelSettingsKeys.contains("volumeFactor")) {
         settings.m_volumeFactor = response.getSsbModSettings()->getVolumeFactor();
     }
     if (channelSettingsKeys.contains("spanLog2")) {
         settings.m_spanLog2 = response.getSsbModSettings()->getSpanLog2();
     }
     if (channelSettingsKeys.contains("audioBinaural")) {
         settings.m_audioBinaural = response.getSsbModSettings()->getAudioBinaural() != 0;
     }
     if (channelSettingsKeys.contains("audioFlipChannels")) {
         settings.m_audioFlipChannels = response.getSsbModSettings()->getAudioFlipChannels() != 0;
     }
     if (channelSettingsKeys.contains("dsb")) {
         settings.m_dsb = response.getSsbModSettings()->getDsb() != 0;
     }
     if (channelSettingsKeys.contains("audioMute")) {
         settings.m_audioMute = response.getSsbModSettings()->getAudioMute() != 0;
     }
     if (channelSettingsKeys.contains("playLoop")) {
         settings.m_playLoop = response.getSsbModSettings()->getPlayLoop() != 0;
     }
     if (channelSettingsKeys.contains("agc")) {
         settings.m_agc = response.getSsbModSettings()->getAgc() != 0;
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getSsbModSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getSsbModSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("modAFInput")) {
         settings.m_modAFInput = (SSBModSettings::SSBModInputAF) response.getSsbModSettings()->getModAfInput();
     }
     if (channelSettingsKeys.contains("audioDeviceName")) {
         settings.m_audioDeviceName = *response.getSsbModSettings()->getAudioDeviceName();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getSsbModSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getSsbModSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getSsbModSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getSsbModSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getSsbModSettings()->getReverseApiChannelIndex();
     }
     if (channelSettingsKeys.contains("cwKeyer"))
     {
         SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = response.getSsbModSettings()->getCwKeyer();
         CWKeyerSettings cwKeyerSettings = m_cwKeyer.getSettings();
         m_cwKeyer.webapiSettingsPutPatch(channelSettingsKeys, cwKeyerSettings, apiCwKeyerSettings);
         CWKeyer::MsgConfigureCWKeyer *msgCwKeyer = CWKeyer::MsgConfigureCWKeyer::create(cwKeyerSettings, force);
         m_cwKeyer.getInputMessageQueue()->push(msgCwKeyer);
         if (m_guiMessageQueue) // forward to GUI if any
         {
             CWKeyer::MsgConfigureCWKeyer *msgCwKeyerToGUI = CWKeyer::MsgConfigureCWKeyer::create(cwKeyerSettings, force);
             m_guiMessageQueue->push(msgCwKeyerToGUI);
         }
     }
     if (frequencyOffsetChanged)
     {
         SSBMod::MsgConfigureChannelizer *msgChan = SSBMod::MsgConfigureChannelizer::create(
                 m_audioSampleRate, settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(msgChan);
     }
     MsgConfigureSSBMod *msg = MsgConfigureSSBMod::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureSSBMod *msgToGUI = MsgConfigureSSBMod::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_agcStepLength
int SSBMod::m_agcStepLength private
Definition at line 338 of file ssbmod.h.
m_audioBuffer
AudioVector SSBMod::m_audioBuffer private
Definition at line 315 of file ssbmod.h.
Referenced by pullAF(), pullAudio(), and SSBMod().
m_audioBufferFill
uint SSBMod::m_audioBufferFill private
Definition at line 316 of file ssbmod.h.
Referenced by modulateSample(), pullAF(), pullAudio(), and SSBMod().
m_audioCompressor
AudioCompressorSnd SSBMod::m_audioCompressor private
Definition at line 337 of file ssbmod.h.
Referenced by applyAudioSampleRate(), pullAF(), and SSBMod().
m_audioFifo
AudioFifo SSBMod::m_audioFifo private
Definition at line 317 of file ssbmod.h.
Referenced by applySettings(), pullAudio(), SSBMod(), start(), and ~SSBMod().
m_audioSampleRate
quint32 SSBMod::m_audioSampleRate private
Definition at line 314 of file ssbmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applyFeedbackAudioSampleRate(), applySettings(), getAudioSampleRate(), handleMessage(), pullAudio(), SSBMod(), webapiFormatChannelReport(), and webapiSettingsPutPatch().
m_basebandSampleRate
int SSBMod::m_basebandSampleRate private
Definition at line 277 of file ssbmod.h.
Referenced by applyChannelSettings(), pullAudio(), SSBMod(), and start().
m_carrierNco
NCOF SSBMod::m_carrierNco private
Definition at line 282 of file ssbmod.h.
Referenced by applyChannelSettings(), and pull().
m_channelId
const QString SSBMod::m_channelId = "SSBMod" static
Definition at line 255 of file ssbmod.h.
Referenced by SSBModPlugin::initPlugin(), and SSBMod().
m_channelIdURI
const QString SSBMod::m_channelIdURI = "sdrangel.channeltx.modssb" static
Definition at line 254 of file ssbmod.h.
Referenced by SSBModPlugin::initPlugin(), and SSBModGUI::SSBModGUI().
m_channelizer
UpChannelizer* SSBMod::m_channelizer private
Definition at line 275 of file ssbmod.h.
Referenced by handleMessage(), SSBMod(), and ~SSBMod().
m_cwKeyer
CWKeyer SSBMod::m_cwKeyer private
Definition at line 335 of file ssbmod.h.
Referenced by applyAudioSampleRate(), getCWKeyer(), pullAF(), SSBMod(), webapiFormatChannelSettings(), webapiReverseSendCWSettings(), webapiReverseSendSettings(), and webapiSettingsPutPatch().
m_deviceAPI
DeviceAPI* SSBMod::m_deviceAPI private
Definition at line 273 of file ssbmod.h.
Referenced by SSBMod(), and ~SSBMod().
m_DSBFilter
fftfilt* SSBMod::m_DSBFilter private
Definition at line 297 of file ssbmod.h.
Referenced by applyAudioSampleRate(), applySettings(), pullAF(), SSBMod(), and ~SSBMod().
m_DSBFilterBuffer
Complex* SSBMod::m_DSBFilterBuffer private
Definition at line 299 of file ssbmod.h.
Referenced by applySettings(), pullAF(), SSBMod(), and ~SSBMod().
m_DSBFilterBufferIndex
int SSBMod::m_DSBFilterBufferIndex private
Definition at line 301 of file ssbmod.h.
Referenced by applySettings(), and pullAF().
m_feedbackAudioBuffer
AudioVector SSBMod::m_feedbackAudioBuffer private
Definition at line 320 of file ssbmod.h.
Referenced by processOneSample(), and SSBMod().
m_feedbackAudioBufferFill
uint SSBMod::m_feedbackAudioBufferFill private
Definition at line 321 of file ssbmod.h.
Referenced by processOneSample(), and SSBMod().
m_feedbackAudioFifo
AudioFifo SSBMod::m_feedbackAudioFifo private
Definition at line 322 of file ssbmod.h.
Referenced by applySettings(), processOneSample(), SSBMod(), and ~SSBMod().
m_feedbackAudioSampleRate
quint32 SSBMod::m_feedbackAudioSampleRate private
Definition at line 319 of file ssbmod.h.
Referenced by applyAudioSampleRate(), applyFeedbackAudioSampleRate(), applySettings(), and SSBMod().
m_feedbackInterpolator
Interpolator SSBMod::m_feedbackInterpolator private
Definition at line 291 of file ssbmod.h.
Referenced by applyFeedbackAudioSampleRate(), and pushFeedback().
m_feedbackInterpolatorConsumed
bool SSBMod::m_feedbackInterpolatorConsumed private
Definition at line 294 of file ssbmod.h.
Referenced by applyFeedbackAudioSampleRate().
m_feedbackInterpolatorDistance
Real SSBMod::m_feedbackInterpolatorDistance private
Definition at line 292 of file ssbmod.h.
Referenced by applyFeedbackAudioSampleRate(), processOneSample(), and pushFeedback().
m_feedbackInterpolatorDistanceRemain
Real SSBMod::m_feedbackInterpolatorDistanceRemain private
Definition at line 293 of file ssbmod.h.
Referenced by applyFeedbackAudioSampleRate(), and pushFeedback().
m_fileName
QString SSBMod::m_fileName private
Definition at line 327 of file ssbmod.h.
Referenced by SSBMod::MsgConfigureFileSourceName::getFileName(), handleMessage(), and openFileStream().
m_fileSize
quint64 SSBMod::m_fileSize private
raw file size (bytes)
Definition at line 328 of file ssbmod.h.
Referenced by handleMessage(), and openFileStream().
m_ifstream
std::ifstream SSBMod::m_ifstream private
Definition at line 326 of file ssbmod.h.
Referenced by handleMessage(), openFileStream(), pullAF(), and seekFileStream().
m_inputFrequencyOffset
int SSBMod::m_inputFrequencyOffset private
Definition at line 279 of file ssbmod.h.
Referenced by applyChannelSettings(), SSBMod(), and start().
m_interpolator
Interpolator SSBMod::m_interpolator private
Definition at line 286 of file ssbmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and pull().
m_interpolatorConsumed
bool SSBMod::m_interpolatorConsumed private
Definition at line 289 of file ssbmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), and applySettings().
m_interpolatorDistance
Real SSBMod::m_interpolatorDistance private
Definition at line 287 of file ssbmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and pull().
m_interpolatorDistanceRemain
Real SSBMod::m_interpolatorDistanceRemain private
Definition at line 288 of file ssbmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and pull().
m_levelCalcCount
quint32 SSBMod::m_levelCalcCount private
Definition at line 332 of file ssbmod.h.
Referenced by calculateLevel().
m_levelNbSamples
const int SSBMod::m_levelNbSamples = 480 static private
Definition at line 343 of file ssbmod.h.
Referenced by calculateLevel().
m_levelSum
Real SSBMod::m_levelSum private
Definition at line 334 of file ssbmod.h.
Referenced by calculateLevel().
m_magsq
double SSBMod::m_magsq private
Definition at line 311 of file ssbmod.h.
Referenced by getMagSq(), pull(), and SSBMod().
m_modSample
Complex SSBMod::m_modSample private
Definition at line 284 of file ssbmod.h.
Referenced by modulateSample(), and pull().
m_movingAverage
MovingAverageUtil<double, double, 16> SSBMod::m_movingAverage private
Definition at line 312 of file ssbmod.h.
Referenced by pull().
m_networkManager
QNetworkAccessManager* SSBMod::m_networkManager private
Definition at line 340 of file ssbmod.h.
Referenced by SSBMod(), webapiReverseSendCWSettings(), webapiReverseSendSettings(), and ~SSBMod().
m_networkRequest
QNetworkRequest SSBMod::m_networkRequest private
Definition at line 341 of file ssbmod.h.
Referenced by webapiReverseSendCWSettings(), and webapiReverseSendSettings().
m_outputSampleRate
int SSBMod::m_outputSampleRate private
Definition at line 278 of file ssbmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), SSBMod(), start(), and webapiFormatChannelReport().
m_peakLevel
Real SSBMod::m_peakLevel private
Definition at line 333 of file ssbmod.h.
Referenced by calculateLevel().
m_recordLength
quint32 SSBMod::m_recordLength private
record length in seconds computed from file size
Definition at line 329 of file ssbmod.h.
Referenced by SSBMod::MsgReportFileSourceStreamData::getRecordLength(), openFileStream(), and seekFileStream().
m_sampleBuffer
SampleVector SSBMod::m_sampleBuffer private
Definition at line 305 of file ssbmod.h.
Referenced by pullAF().
m_sampleRate
int SSBMod::m_sampleRate private
Definition at line 330 of file ssbmod.h.
Referenced by SSBMod::MsgConfigureChannelizer::getSampleRate(), SSBMod::MsgReportFileSourceStreamData::getSampleRate(), openFileStream(), and seekFileStream().
m_sampleSink
BasebandSampleSink* SSBMod::m_sampleSink private
Definition at line 304 of file ssbmod.h.
Referenced by pullAF(), and setSpectrumSampleSink().
m_settings
SSBModSettings SSBMod::m_settings private
Definition at line 280 of file ssbmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), deserialize(), handleMessage(), modulateSample(), pullAF(), serialize(), SSBMod(), start(), webapiReverseSendCWSettings(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex SSBMod::m_settingsMutex private
Definition at line 324 of file ssbmod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applyFeedbackAudioSampleRate(), applySettings(), pull(), and seekFileStream().
m_ssbFftLen
const int SSBMod::m_ssbFftLen = 1024 static private
Definition at line 302 of file ssbmod.h.
Referenced by applySettings(), pullAF(), and SSBMod().
m_SSBFilter
fftfilt* SSBMod::m_SSBFilter private
Definition at line 296 of file ssbmod.h.
Referenced by applyAudioSampleRate(), applySettings(), pullAF(), SSBMod(), and ~SSBMod().
m_SSBFilterBuffer
Complex* SSBMod::m_SSBFilterBuffer private
Definition at line 298 of file ssbmod.h.
Referenced by applySettings(), pullAF(), SSBMod(), and ~SSBMod().
m_SSBFilterBufferIndex
int SSBMod::m_SSBFilterBufferIndex private
Definition at line 300 of file ssbmod.h.
Referenced by applySettings(), and pullAF().
m_sum
fftfilt::cmplx SSBMod::m_sum private
Definition at line 307 of file ssbmod.h.
Referenced by pullAF(), and SSBMod().
m_sumCount
int SSBMod::m_sumCount private
Definition at line 309 of file ssbmod.h.
Referenced by pullAF(), and SSBMod().
m_threadedChannelizer
ThreadedBasebandSampleSource* SSBMod::m_threadedChannelizer private
Definition at line 274 of file ssbmod.h.
Referenced by SSBMod(), and ~SSBMod().
m_toneNco
NCOF SSBMod::m_toneNco private
Definition at line 283 of file ssbmod.h.
Referenced by applyAudioSampleRate(), applySettings(), pullAF(), and SSBMod().
m_undersampleCount
int SSBMod::m_undersampleCount private
Definition at line 308 of file ssbmod.h.
Referenced by pullAF(), and SSBMod().
The documentation for this class was generated from the following files:
plugins/channeltx/modssb/ssbmod.h
plugins/channeltx/modssb/ssbmod.cpp