SDRAngel: MainWindow::MsgSavePreset Class Reference
MainWindow::MsgSavePreset Class Reference
Public Member Functions
Preset * getPreset () const
int getDeviceSetIndex () const
bool isNewPreset () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgSavePreset * create (Preset *preset, int deviceSetIndex, bool newPreset)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgSavePreset (Preset *preset, int deviceSetIndex, bool newPreset)
Private Attributes
Preset * m_preset
int m_deviceSetIndex
bool m_newPreset
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 113 of file mainwindow.h.
Constructor & Destructor Documentation
MsgSavePreset()
MainWindow::MsgSavePreset::MsgSavePreset (Preset * preset, int deviceSetIndex, bool newPreset) inline private
Definition at line 131 of file mainwindow.h.
                                                                           :
             Message(),
             m_preset(preset),
             m_deviceSetIndex(deviceSetIndex),
             m_newPreset(newPreset)
         { }
Member Function Documentation
create()
static MsgSavePreset* MainWindow::MsgSavePreset::create (Preset * preset, int deviceSetIndex, bool newPreset) inline static
Definition at line 121 of file mainwindow.h.
Referenced by WebAPIAdapterGUI::instancePresetPost(), and WebAPIAdapterGUI::instancePresetPut().
         {
             return new MsgSavePreset(preset, deviceSetIndex, newPreset);
         }
getDeviceSetIndex()
int MainWindow::MsgSavePreset::getDeviceSetIndex () const inline
Definition at line 118 of file mainwindow.h.
Referenced by MainWindow::handleMessage().
 { return m_deviceSetIndex; }
getPreset()
Preset* MainWindow::MsgSavePreset::getPreset () const inline
Definition at line 117 of file mainwindow.h.
Referenced by MainWindow::handleMessage().
 { return m_preset; }
isNewPreset()
bool MainWindow::MsgSavePreset::isNewPreset () const inline
Definition at line 119 of file mainwindow.h.
Referenced by MainWindow::handleMessage().
 { return m_newPreset; }
Member Data Documentation
m_deviceSetIndex
int MainWindow::MsgSavePreset::m_deviceSetIndex private
Definition at line 128 of file mainwindow.h.
m_newPreset
bool MainWindow::MsgSavePreset::m_newPreset private
Definition at line 129 of file mainwindow.h.
m_preset
Preset* MainWindow::MsgSavePreset::m_preset private
Definition at line 127 of file mainwindow.h.
The documentation for this class was generated from the following file:
sdrgui/mainwindow.h