SDRAngel: XTRXInputGUI Class Reference
XTRXInputGUI Class Reference
#include <xtrxinputgui.h>
Public Member Functions
XTRXInputGUI (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~XTRXInputGUI ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void on_centerFrequency_changed (quint64 value)
void on_ncoFrequency_changed (qint64 value)
void on_ncoEnable_toggled (bool checked)
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_sampleRate_changed (quint64 value)
void on_hwDecim_currentIndexChanged (int index)
void on_swDecim_currentIndexChanged (int index)
void on_lpf_changed (quint64 value)
void on_gainMode_currentIndexChanged (int index)
void on_gain_valueChanged (int value)
void on_lnaGain_valueChanged (int value)
void on_tiaGain_currentIndexChanged (int index)
void on_pgaGain_valueChanged (int value)
void on_antenna_currentIndexChanged (int index)
void on_extClock_clicked ()
void on_pwrmode_currentIndexChanged (int index)
void on_sampleRateMode_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void displaySettings ()
void displaySampleRate ()
void setNCODisplay ()
void setCenterFrequencyDisplay ()
void setCenterFrequencySetting (uint64_t kHzValue)
void sendSettings ()
void updateSampleRateAndFrequency ()
void updateADCRate ()
void blockApplySettings (bool block)
Private Attributes
Ui::XTRXInputGUI * ui
DeviceUISet * m_deviceUISet
XTRXInput * m_XTRXInput
Same object as above but gives easy access to XTRXInput methods and attributes that are used intensively.
XTRXInputSettings m_settings
bool m_sampleRateMode
true: device, false: base band sample rate update mode
QTimer m_updateTimer
QTimer m_statusTimer
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
bool m_doApplySettings
bool m_forceSettings
int m_statusCounter
int m_deviceStatusCounter
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 36 of file xtrxinputgui.h.
Constructor & Destructor Documentation
XTRXInputGUI()
XTRXInputGUI::XTRXInputGUI (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 36 of file xtrxinputgui.cpp.
References arg(), displaySettings(), XTRXInput::getChannelIndex(), XTRXInput::getLORange(), XTRXInput::getLPRange(), DeviceAPI::getSampleSource(), XTRXInput::getSRRange(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, ColorMapper::GrayYellow, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_statusTimer, m_updateTimer, m_XTRXInput, openDeviceSettingsDialog(), ui, updateHardware(), and updateStatus().
                                                                     :
     QWidget(parent),
     ui(new Ui::XTRXInputGUI),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_sampleRateMode(true),
     m_sampleRate(0),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_statusCounter(0),
     m_deviceStatusCounter(0)
 {
     m_XTRXInput = (XTRXInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     float minF, maxF, stepF;
     m_XTRXInput->getLORange(minF, maxF, stepF);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, ((uint32_t) minF)/1000, ((uint32_t) maxF)/1000); // frequency dial is in kHz
     m_XTRXInput->getSRRange(minF, maxF, stepF);
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(8, (uint32_t) minF, (uint32_t) maxF);
     m_XTRXInput->getLPRange(minF, maxF, stepF);
     ui->lpf->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     ui->lpf->setValueRange(6, (minF/1000)+1, maxF/1000);
     ui->ncoFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->channelNumberText->setText(tr("#%1").arg(m_XTRXInput->getChannelIndex()));
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
 }
~XTRXInputGUI()
XTRXInputGUI::~XTRXInputGUI () virtual
Definition at line 83 of file xtrxinputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void XTRXInputGUI::blockApplySettings (bool block) private
Definition at line 480 of file xtrxinputgui.cpp.
References m_doApplySettings.
Referenced by handleMessage().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool XTRXInputGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 127 of file xtrxinputgui.cpp.
References XTRXInputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if (m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void XTRXInputGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 88 of file xtrxinputgui.cpp.
 {
     delete this;
 }
displaySampleRate()
void XTRXInputGUI::displaySampleRate () private
Definition at line 285 of file xtrxinputgui.cpp.
References arg(), XTRXInput::getSRRange(), XTRXInputSettings::m_devSampleRate, XTRXInputSettings::m_log2SoftDecim, m_sampleRateMode, m_settings, m_XTRXInput, and ui.
Referenced by displaySettings(), on_hwDecim_currentIndexChanged(), on_sampleRateMode_toggled(), and updateSampleRateAndFrequency().
 {
     float minF, maxF, stepF;
     m_XTRXInput->getSRRange(minF, maxF, stepF);
     ui->sampleRate->blockSignals(true);
     if (m_sampleRateMode)
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(60,60,60); }");
         ui->sampleRateMode->setText("SR");
         ui->sampleRate->setValueRange(8, (uint32_t) minF, (uint32_t) maxF);
         ui->sampleRate->setValue(m_settings.m_devSampleRate);
         ui->sampleRate->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setToolTip("Baseband sample rate (S/s)");
         uint32_t basebandSampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2SoftDecim);
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(basebandSampleRate / 1000.0f, 'g', 5)));
     }
     else
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(50,50,50); }");
         ui->sampleRateMode->setText("BB");
         ui->sampleRate->setValueRange(8, (uint32_t) minF/(1<<m_settings.m_log2SoftDecim), (uint32_t) maxF/(1<<m_settings.m_log2SoftDecim));
         ui->sampleRate->setValue(m_settings.m_devSampleRate/(1<<m_settings.m_log2SoftDecim));
         ui->sampleRate->setToolTip("Baseband sample rate (S/s)");
         ui->deviceRateText->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_settings.m_devSampleRate / 1000.0f, 'g', 5)));
     }
     ui->sampleRate->blockSignals(false);
 }
displaySettings()
void XTRXInputGUI::displaySettings () private
Definition at line 317 of file xtrxinputgui.cpp.
References arg(), displaySampleRate(), XTRXInputSettings::GAIN_AUTO, XTRXInputSettings::m_antennaPath, XTRXInputSettings::m_dcBlock, XTRXInputSettings::m_extClock, XTRXInputSettings::m_extClockFreq, XTRXInputSettings::m_gain, XTRXInputSettings::m_gainMode, XTRXInputSettings::m_iqCorrection, XTRXInputSettings::m_lnaGain, XTRXInputSettings::m_log2HardDecim, XTRXInputSettings::m_log2SoftDecim, XTRXInputSettings::m_lpfBW, XTRXInputSettings::m_ncoEnable, XTRXInputSettings::m_pgaGain, XTRXInputSettings::m_pwrmode, m_settings, XTRXInputSettings::m_tiaGain, setCenterFrequencyDisplay(), setNCODisplay(), ui, and updateADCRate().
Referenced by deserialize(), handleInputMessages(), handleMessage(), resetToDefaults(), setCenterFrequency(), and XTRXInputGUI().
 {
     ui->extClock->setExternalClockFrequency(m_settings.m_extClockFreq);
     ui->extClock->setExternalClockActive(m_settings.m_extClock);
     setCenterFrequencyDisplay();
     displaySampleRate();
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqCorrection);
     ui->hwDecim->setCurrentIndex(m_settings.m_log2HardDecim);
     ui->swDecim->setCurrentIndex(m_settings.m_log2SoftDecim);
     updateADCRate();
     ui->lpf->setValue(m_settings.m_lpfBW / 1000);
     ui->pwrmode->setCurrentIndex(m_settings.m_pwrmode);
     ui->gain->setValue(m_settings.m_gain);
     ui->gainText->setText(tr("%1").arg(m_settings.m_gain));
     ui->antenna->setCurrentIndex((int) m_settings.m_antennaPath);
     ui->gainMode->setCurrentIndex((int) m_settings.m_gainMode);
     ui->lnaGain->setValue(m_settings.m_lnaGain);
     ui->tiaGain->setCurrentIndex(m_settings.m_tiaGain - 1);
     ui->pgaGain->setValue(m_settings.m_pgaGain);
     if (m_settings.m_gainMode == XTRXInputSettings::GAIN_AUTO)
     {
         ui->gain->setEnabled(true);
         ui->lnaGain->setEnabled(false);
         ui->tiaGain->setEnabled(false);
         ui->pgaGain->setEnabled(false);
     }
     else
     {
         ui->gain->setEnabled(false);
         ui->lnaGain->setEnabled(true);
         ui->tiaGain->setEnabled(true);
         ui->pgaGain->setEnabled(true);
     }
     setNCODisplay();
     ui->ncoEnable->setChecked(m_settings.m_ncoEnable);
 }
getCenterFrequency()
qint64 XTRXInputGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 110 of file xtrxinputgui.cpp.
References XTRXInputSettings::m_centerFrequency, XTRXInputSettings::m_ncoEnable, XTRXInputSettings::m_ncoFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency + (m_settings.m_ncoEnable ? m_settings.m_ncoFrequency : 0);
 }
getInputMessageQueue()
virtual MessageQueue* XTRXInputGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 52 of file xtrxinputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString XTRXInputGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 98 of file xtrxinputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void XTRXInputGUI::handleInputMessages () private slot
Definition at line 233 of file xtrxinputgui.cpp.
References displaySettings(), DSPSignalNotification::getCenterFrequency(), DSPSignalNotification::getSampleRate(), XTRXInput::MsgConfigureXTRX::getSettings(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, m_settings, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by XTRXInputGUI().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("XTRXInputGUI::handleInputMessages: DSPSignalNotification: SampleRate: %d, CenterFrequency: %llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else if (XTRXInput::MsgConfigureXTRX::match(*message))
         {
             qDebug("XTRXInputGUI::handleInputMessages: MsgConfigureXTRX");
             const XTRXInput::MsgConfigureXTRX& cfg = (XTRXInput::MsgConfigureXTRX&) *message;
             m_settings = cfg.getSettings();
             displaySettings();
             delete message;
         }
         else
         {
             if (handleMessage(*message)) {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool XTRXInputGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 143 of file xtrxinputgui.cpp.
References arg(), blockApplySettings(), displaySettings(), XTRXInput::MsgReportStreamInfo::getActive(), DeviceXTRXShared::MsgReportBuddyChange::getCenterFrequency(), DeviceXTRXShared::MsgReportBuddyChange::getDevSampleRate(), XTRXInput::getDevSampleRate(), DeviceXTRXShared::MsgReportClockSourceChange::getExtClock(), DeviceXTRXShared::MsgReportClockSourceChange::getExtClockFeq(), XTRXInput::MsgReportStreamInfo::getFifoFilledCount(), XTRXInput::MsgReportStreamInfo::getFifoSize(), DeviceXTRXShared::MsgReportDeviceInfo::getGPSLocked(), DeviceXTRXShared::MsgReportBuddyChange::getLog2HardDecimInterp(), DeviceXTRXShared::MsgReportBuddyChange::getRxElseTx(), XTRXInput::MsgStartStop::getStartStop(), XTRXInput::MsgReportStreamInfo::getSuccess(), DeviceXTRXShared::MsgReportDeviceInfo::getTemperature(), XTRXInputSettings::m_centerFrequency, XTRXInputSettings::m_devSampleRate, XTRXInputSettings::m_extClock, XTRXInputSettings::m_extClockFreq, XTRXInputSettings::m_log2HardDecim, m_settings, m_XTRXInput, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (DeviceXTRXShared::MsgReportBuddyChange::match(message))
     {
         DeviceXTRXShared::MsgReportBuddyChange& report = (DeviceXTRXShared::MsgReportBuddyChange&) message;
         m_settings.m_devSampleRate = report.getDevSampleRate();
         m_settings.m_log2HardDecim = report.getLog2HardDecimInterp();
         if (report.getRxElseTx()) {
             m_settings.m_centerFrequency = report.getCenterFrequency();
         }
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (DeviceXTRXShared::MsgReportClockSourceChange::match(message))
     {
         DeviceXTRXShared::MsgReportClockSourceChange& report = (DeviceXTRXShared::MsgReportClockSourceChange&) message;
         m_settings.m_extClockFreq = report.getExtClockFeq();
         m_settings.m_extClock = report.getExtClock();
         blockApplySettings(true);
         ui->extClock->setExternalClockFrequency(m_settings.m_extClockFreq);
         ui->extClock->setExternalClockActive(m_settings.m_extClock);
         blockApplySettings(false);
         return true;
     }
     else if (XTRXInput::MsgReportClockGenChange::match(message))
     {
         m_settings.m_devSampleRate = m_XTRXInput->getDevSampleRate();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (XTRXInput::MsgReportStreamInfo::match(message))
     {
         XTRXInput::MsgReportStreamInfo& report = (XTRXInput::MsgReportStreamInfo&) message;
         if (report.getSuccess())
         {
             if (report.getActive()) {
                 ui->streamStatusLabel->setStyleSheet("QLabel { background-color : green; }");
             } else {
                 ui->streamStatusLabel->setStyleSheet("QLabel { background-color : blue; }");
             }
             ui->fifoBar->setMaximum(report.getFifoSize());
             ui->fifoBar->setValue(report.getFifoFilledCount());
             ui->fifoBar->setToolTip(tr("FIFO fill %1/%2 samples").arg(QString::number(report.getFifoFilledCount())).arg(QString::number(report.getFifoSize())));
         }
         else
         {
             ui->streamStatusLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
         }
         return true;
     }
     else if (DeviceXTRXShared::MsgReportDeviceInfo::match(message))
     {
         DeviceXTRXShared::MsgReportDeviceInfo& report = (DeviceXTRXShared::MsgReportDeviceInfo&) message;
         ui->temperatureText->setText(tr("%1C").arg(QString::number(report.getTemperature(), 'f', 0)));
         if (report.getGPSLocked()) {
             ui->gpsStatusLabel->setStyleSheet("QLabel { background-color : green; }");
         } else {
             ui->gpsStatusLabel->setStyleSheet("QLabel { background:rgb(48,48,48); }");
         }
         return true;
     }
     else if (XTRXInput::MsgStartStop::match(message))
     {
         XTRXInput::MsgStartStop& notif = (XTRXInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     return false;
 }
on_antenna_currentIndexChanged
void XTRXInputGUI::on_antenna_currentIndexChanged (int index) private slot
Definition at line 633 of file xtrxinputgui.cpp.
References XTRXInputSettings::m_antennaPath, m_settings, and sendSettings().
 {
     m_settings.m_antennaPath = (xtrx_antenna_t) index;
     sendSettings();
 }
on_centerFrequency_changed
void XTRXInputGUI::on_centerFrequency_changed (quint64 value) private slot
Definition at line 506 of file xtrxinputgui.cpp.
References sendSettings(), and setCenterFrequencySetting().
 {
     setCenterFrequencySetting(value);
     sendSettings();
 }
on_dcOffset_toggled
void XTRXInputGUI::on_dcOffset_toggled (bool checked) private slot
Definition at line 526 of file xtrxinputgui.cpp.
References XTRXInputSettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_extClock_clicked
void XTRXInputGUI::on_extClock_clicked () private slot
Definition at line 639 of file xtrxinputgui.cpp.
References XTRXInputSettings::m_extClock, XTRXInputSettings::m_extClockFreq, m_settings, sendSettings(), and ui.
 {
     m_settings.m_extClock = ui->extClock->getExternalClockActive();
     m_settings.m_extClockFreq = ui->extClock->getExternalClockFrequency();
     qDebug("XTRXInputGUI::on_extClock_clicked: %u Hz %s", m_settings.m_extClockFreq, m_settings.m_extClock ? "on" : "off");
     sendSettings();
 }
on_gain_valueChanged
void XTRXInputGUI::on_gain_valueChanged (int value) private slot
Definition at line 606 of file xtrxinputgui.cpp.
References arg(), XTRXInputSettings::m_gain, m_settings, sendSettings(), and ui.
 {
     m_settings.m_gain = value;
     ui->gainText->setText(tr("%1").arg(m_settings.m_gain));
     sendSettings();
 }
on_gainMode_currentIndexChanged
void XTRXInputGUI::on_gainMode_currentIndexChanged (int index) private slot
Definition at line 584 of file xtrxinputgui.cpp.
References XTRXInputSettings::m_gainMode, m_settings, sendSettings(), and ui.
 {
     m_settings.m_gainMode = (XTRXInputSettings::GainMode) index;
     if (index == 0)
     {
         ui->gain->setEnabled(true);
         ui->lnaGain->setEnabled(false);
         ui->tiaGain->setEnabled(false);
         ui->pgaGain->setEnabled(false);
     }
     else
     {
         ui->gain->setEnabled(false);
         ui->lnaGain->setEnabled(true);
         ui->tiaGain->setEnabled(true);
         ui->pgaGain->setEnabled(true);
     }
     sendSettings();
 }
on_hwDecim_currentIndexChanged
void XTRXInputGUI::on_hwDecim_currentIndexChanged (int index) private slot
Definition at line 550 of file xtrxinputgui.cpp.
References displaySampleRate(), XTRXInputSettings::m_devSampleRate, XTRXInputSettings::m_log2HardDecim, XTRXInputSettings::m_log2SoftDecim, m_sampleRateMode, m_settings, sendSettings(), setNCODisplay(), ui, and updateADCRate().
 {
     if ((index <0) || (index > 5))
         return;
     m_settings.m_log2HardDecim = index;
     displaySampleRate();
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     } else {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew() * (1 << m_settings.m_log2SoftDecim);
     }
     updateADCRate();
     setNCODisplay();
     sendSettings();
 }
on_iqImbalance_toggled
void XTRXInputGUI::on_iqImbalance_toggled (bool checked) private slot
Definition at line 532 of file xtrxinputgui.cpp.
References XTRXInputSettings::m_iqCorrection, m_settings, and sendSettings().
 {
     m_settings.m_iqCorrection = checked;
     sendSettings();
 }
on_lnaGain_valueChanged
void XTRXInputGUI::on_lnaGain_valueChanged (int value) private slot
Definition at line 613 of file xtrxinputgui.cpp.
References arg(), XTRXInputSettings::m_lnaGain, m_settings, sendSettings(), and ui.
 {
     m_settings.m_lnaGain = value;
     ui->lnaGainText->setText(tr("%1").arg(m_settings.m_lnaGain));
     sendSettings();
 }
on_lpf_changed
void XTRXInputGUI::on_lpf_changed (quint64 value) private slot
Definition at line 578 of file xtrxinputgui.cpp.
References XTRXInputSettings::m_lpfBW, m_settings, and sendSettings().
 {
     m_settings.m_lpfBW = value * 1000;
     sendSettings();
 }
on_ncoEnable_toggled
void XTRXInputGUI::on_ncoEnable_toggled (bool checked) private slot
Definition at line 519 of file xtrxinputgui.cpp.
References XTRXInputSettings::m_ncoEnable, m_settings, sendSettings(), and setCenterFrequencyDisplay().
 {
     m_settings.m_ncoEnable = checked;
     setCenterFrequencyDisplay();
     sendSettings();
 }
on_ncoFrequency_changed
void XTRXInputGUI::on_ncoFrequency_changed (qint64 value) private slot
Definition at line 512 of file xtrxinputgui.cpp.
References XTRXInputSettings::m_ncoFrequency, m_settings, sendSettings(), and setCenterFrequencyDisplay().
 {
     m_settings.m_ncoFrequency = value;
     setCenterFrequencyDisplay();
     sendSettings();
 }
on_pgaGain_valueChanged
void XTRXInputGUI::on_pgaGain_valueChanged (int value) private slot
Definition at line 626 of file xtrxinputgui.cpp.
References arg(), XTRXInputSettings::m_pgaGain, m_settings, sendSettings(), and ui.
 {
     m_settings.m_pgaGain = value;
     ui->pgaGainText->setText(tr("%1").arg(m_settings.m_pgaGain));
     sendSettings();
 }
on_pwrmode_currentIndexChanged
void XTRXInputGUI::on_pwrmode_currentIndexChanged (int index) private slot
Definition at line 647 of file xtrxinputgui.cpp.
References XTRXInputSettings::m_pwrmode, m_settings, and sendSettings().
 {
     m_settings.m_pwrmode = index;
     sendSettings();
 }
on_record_toggled
void XTRXInputGUI::on_record_toggled (bool checked) private slot
Definition at line 494 of file xtrxinputgui.cpp.
References XTRXInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_XTRXInput, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     XTRXInput::MsgFileRecord* message = XTRXInput::MsgFileRecord::create(checked);
     m_XTRXInput->getInputMessageQueue()->push(message);
 }
on_sampleRate_changed
void XTRXInputGUI::on_sampleRate_changed (quint64 value) private slot
Definition at line 538 of file xtrxinputgui.cpp.
References XTRXInputSettings::m_devSampleRate, XTRXInputSettings::m_log2SoftDecim, m_sampleRateMode, m_settings, sendSettings(), setNCODisplay(), and updateADCRate().
 {
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = value;
     } else {
         m_settings.m_devSampleRate = value * (1 << m_settings.m_log2SoftDecim);
     }
     updateADCRate();
     setNCODisplay();
     sendSettings();}
on_sampleRateMode_toggled
void XTRXInputGUI::on_sampleRateMode_toggled (bool checked) private slot
Definition at line 653 of file xtrxinputgui.cpp.
References displaySampleRate(), and m_sampleRateMode.
 {
     m_sampleRateMode = checked;
     displaySampleRate();
 }
on_startStop_toggled
void XTRXInputGUI::on_startStop_toggled (bool checked) private slot
Definition at line 485 of file xtrxinputgui.cpp.
References XTRXInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_XTRXInput, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         XTRXInput::MsgStartStop *message = XTRXInput::MsgStartStop::create(checked);
         m_XTRXInput->getInputMessageQueue()->push(message);
     }
 }
on_swDecim_currentIndexChanged
void XTRXInputGUI::on_swDecim_currentIndexChanged (int index) private slot
Definition at line 568 of file xtrxinputgui.cpp.
References XTRXInputSettings::m_log2SoftDecim, m_settings, and sendSettings().
 {
     if ((index <0) || (index > 6)) {
         return;
     }
     m_settings.m_log2SoftDecim = index;
     sendSettings();
 }
on_tiaGain_currentIndexChanged
void XTRXInputGUI::on_tiaGain_currentIndexChanged (int index) private slot
Definition at line 620 of file xtrxinputgui.cpp.
References m_settings, XTRXInputSettings::m_tiaGain, and sendSettings().
 {
     m_settings.m_tiaGain = index + 1;
     sendSettings();
 }
openDeviceSettingsDialog
void XTRXInputGUI::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 659 of file xtrxinputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), XTRXInputSettings::m_reverseAPIAddress, XTRXInputSettings::m_reverseAPIDeviceIndex, XTRXInputSettings::m_reverseAPIPort, m_settings, XTRXInputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by XTRXInputGUI().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void XTRXInputGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 103 of file xtrxinputgui.cpp.
References displaySettings(), m_settings, XTRXInputSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void XTRXInputGUI::sendSettings () private
Definition at line 407 of file xtrxinputgui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_antenna_currentIndexChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_extClock_clicked(), on_gain_valueChanged(), on_gainMode_currentIndexChanged(), on_hwDecim_currentIndexChanged(), on_iqImbalance_toggled(), on_lnaGain_valueChanged(), on_lpf_changed(), on_ncoEnable_toggled(), on_ncoFrequency_changed(), on_pgaGain_valueChanged(), on_pwrmode_currentIndexChanged(), on_sampleRate_changed(), on_swDecim_currentIndexChanged(), on_tiaGain_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray XTRXInputGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 122 of file xtrxinputgui.cpp.
References m_settings, and XTRXInputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void XTRXInputGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 115 of file xtrxinputgui.cpp.
References displaySettings(), XTRXInputSettings::m_centerFrequency, XTRXInputSettings::m_ncoEnable, XTRXInputSettings::m_ncoFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency - (m_settings.m_ncoEnable ? m_settings.m_ncoFrequency : 0);
     displaySettings();
     sendSettings();
 }
setCenterFrequencyDisplay()
void XTRXInputGUI::setCenterFrequencyDisplay () private
Definition at line 381 of file xtrxinputgui.cpp.
References arg(), XTRXInputSettings::m_centerFrequency, XTRXInputSettings::m_ncoEnable, XTRXInputSettings::m_ncoFrequency, m_settings, and ui.
Referenced by displaySettings(), on_ncoEnable_toggled(), and on_ncoFrequency_changed().
 {
     int64_t centerFrequency = m_settings.m_centerFrequency;
     ui->centerFrequency->setToolTip(QString("Main center frequency in kHz (LO: %1 kHz)").arg(centerFrequency/1000));
     if (m_settings.m_ncoEnable) {
         centerFrequency += m_settings.m_ncoFrequency;
     }
     ui->centerFrequency->blockSignals(true);
     ui->centerFrequency->setValue(centerFrequency < 0 ? 0 : (uint64_t) centerFrequency/1000); // kHz
     ui->centerFrequency->blockSignals(false);
 }
setCenterFrequencySetting()
void XTRXInputGUI::setCenterFrequencySetting (uint64_t kHzValue) private
Definition at line 395 of file xtrxinputgui.cpp.
References arg(), XTRXInputSettings::m_centerFrequency, XTRXInputSettings::m_ncoEnable, XTRXInputSettings::m_ncoFrequency, m_settings, and ui.
Referenced by on_centerFrequency_changed().
 {
     int64_t centerFrequency = kHzValue*1000;
     if (m_settings.m_ncoEnable) {
         centerFrequency -= m_settings.m_ncoFrequency;
     }
     m_settings.m_centerFrequency = centerFrequency < 0 ? 0 : (uint64_t) centerFrequency;
     ui->centerFrequency->setToolTip(QString("Main center frequency in kHz (LO: %1 kHz)").arg(centerFrequency/1000));
 }
setName()
void XTRXInputGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 93 of file xtrxinputgui.cpp.
 {
     setObjectName(name);
 }
setNCODisplay()
void XTRXInputGUI::setNCODisplay () private
Definition at line 366 of file xtrxinputgui.cpp.
References arg(), XTRXInputSettings::m_devSampleRate, XTRXInputSettings::m_log2HardDecim, XTRXInputSettings::m_ncoFrequency, m_settings, and ui.
Referenced by displaySettings(), on_hwDecim_currentIndexChanged(), and on_sampleRate_changed().
 {
     int ncoHalfRange = (m_settings.m_devSampleRate * (1<<(m_settings.m_log2HardDecim)))/2;
     ui->ncoFrequency->setValueRange(
             false,
             8,
             -ncoHalfRange,
             ncoHalfRange);
     ui->ncoFrequency->blockSignals(true);
     ui->ncoFrequency->setToolTip(QString("NCO frequency shift in Hz (Range: +/- %1 kHz)").arg(ncoHalfRange/1000));
     ui->ncoFrequency->setValue(m_settings.m_ncoFrequency);
     ui->ncoFrequency->blockSignals(false);
 }
updateADCRate()
void XTRXInputGUI::updateADCRate () private
Definition at line 267 of file xtrxinputgui.cpp.
References arg(), XTRXInput::getClockGen(), m_XTRXInput, and ui.
Referenced by displaySettings(), on_hwDecim_currentIndexChanged(), and on_sampleRate_changed().
 {
     uint32_t adcRate = m_XTRXInput->getClockGen() / 4;
     if (adcRate < 100000000) {
         ui->adcRateLabel->setText(tr("%1k").arg(QString::number(adcRate / 1000.0f, 'g', 5)));
     } else {
         ui->adcRateLabel->setText(tr("%1M").arg(QString::number(adcRate / 1000000.0f, 'g', 5)));
     }
 }
updateHardware
void XTRXInputGUI::updateHardware () private slot
Definition at line 413 of file xtrxinputgui.cpp.
References XTRXInput::MsgConfigureXTRX::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_settings, m_updateTimer, m_XTRXInput, and MessageQueue::push().
Referenced by XTRXInputGUI().
 {
     if (m_doApplySettings)
     {
         qDebug() << "XTRXInputGUI::updateHardware";
         XTRXInput::MsgConfigureXTRX* message = XTRXInput::MsgConfigureXTRX::create(m_settings, m_forceSettings);
         m_XTRXInput->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void XTRXInputGUI::updateSampleRateAndFrequency () private
Definition at line 278 of file xtrxinputgui.cpp.
References displaySampleRate(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), and GLSpectrum::setSampleRate().
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     displaySampleRate();
 }
updateStatus
void XTRXInputGUI::updateStatus () private slot
Definition at line 425 of file xtrxinputgui.cpp.
References XTRXInput::MsgGetStreamInfo::create(), XTRXInput::MsgGetDeviceInfo::create(), DeviceAPI::errorMessage(), DeviceSampleSource::getInputMessageQueue(), DeviceAPI::isBuddyLeader(), DeviceUISet::m_deviceAPI, m_deviceStatusCounter, m_deviceUISet, m_lastEngineState, m_statusCounter, m_XTRXInput, MessageQueue::push(), DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by XTRXInputGUI().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
         case DeviceAPI::StNotStarted:
             ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
             break;
         case DeviceAPI::StIdle:
             ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
             break;
         case DeviceAPI::StRunning:
             ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
             break;
         case DeviceAPI::StError:
             ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
             QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
             break;
         default:
             break;
         }
         m_lastEngineState = state;
     }
     if (m_statusCounter < 1)
     {
         m_statusCounter++;
     }
     else
     {
         XTRXInput::MsgGetStreamInfo* message = XTRXInput::MsgGetStreamInfo::create();
         m_XTRXInput->getInputMessageQueue()->push(message);
         m_statusCounter = 0;
     }
     if (m_deviceStatusCounter < 10)
     {
         m_deviceStatusCounter++;
     }
     else
     {
         if (m_deviceUISet->m_deviceAPI->isBuddyLeader())
         {
             XTRXInput::MsgGetDeviceInfo* message = XTRXInput::MsgGetDeviceInfo::create();
             m_XTRXInput->getInputMessageQueue()->push(message);
         }
         m_deviceStatusCounter = 0;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 XTRXInputGUI::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 65 of file xtrxinputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceStatusCounter
int XTRXInputGUI::m_deviceStatusCounter private
Definition at line 70 of file xtrxinputgui.h.
Referenced by updateStatus().
m_deviceUISet
DeviceUISet* XTRXInputGUI::m_deviceUISet private
Definition at line 58 of file xtrxinputgui.h.
Referenced by updateSampleRateAndFrequency(), updateStatus(), and XTRXInputGUI().
m_doApplySettings
bool XTRXInputGUI::m_doApplySettings private
Definition at line 67 of file xtrxinputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_forceSettings
bool XTRXInputGUI::m_forceSettings private
Definition at line 68 of file xtrxinputgui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue XTRXInputGUI::m_inputMessageQueue private
Definition at line 71 of file xtrxinputgui.h.
Referenced by handleInputMessages(), and XTRXInputGUI().
m_lastEngineState
int XTRXInputGUI::m_lastEngineState private
Definition at line 66 of file xtrxinputgui.h.
Referenced by updateStatus().
m_sampleRate
int XTRXInputGUI::m_sampleRate private
Definition at line 64 of file xtrxinputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateMode
bool XTRXInputGUI::m_sampleRateMode private
true: device, false: base band sample rate update mode
Definition at line 61 of file xtrxinputgui.h.
Referenced by displaySampleRate(), on_hwDecim_currentIndexChanged(), on_sampleRate_changed(), and on_sampleRateMode_toggled().
m_settings
XTRXInputSettings XTRXInputGUI::m_settings private
Definition at line 60 of file xtrxinputgui.h.
Referenced by deserialize(), displaySampleRate(), displaySettings(), getCenterFrequency(), handleInputMessages(), handleMessage(), on_antenna_currentIndexChanged(), on_dcOffset_toggled(), on_extClock_clicked(), on_gain_valueChanged(), on_gainMode_currentIndexChanged(), on_hwDecim_currentIndexChanged(), on_iqImbalance_toggled(), on_lnaGain_valueChanged(), on_lpf_changed(), on_ncoEnable_toggled(), on_ncoFrequency_changed(), on_pgaGain_valueChanged(), on_pwrmode_currentIndexChanged(), on_sampleRate_changed(), on_swDecim_currentIndexChanged(), on_tiaGain_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), setCenterFrequencyDisplay(), setCenterFrequencySetting(), setNCODisplay(), and updateHardware().
m_statusCounter
int XTRXInputGUI::m_statusCounter private
Definition at line 69 of file xtrxinputgui.h.
Referenced by updateStatus().
m_statusTimer
QTimer XTRXInputGUI::m_statusTimer private
Definition at line 63 of file xtrxinputgui.h.
Referenced by XTRXInputGUI().
m_updateTimer
QTimer XTRXInputGUI::m_updateTimer private
Definition at line 62 of file xtrxinputgui.h.
Referenced by sendSettings(), updateHardware(), and XTRXInputGUI().
m_XTRXInput
XTRXInput* XTRXInputGUI::m_XTRXInput private
Same object as above but gives easy access to XTRXInput methods and attributes that are used intensively.
Definition at line 59 of file xtrxinputgui.h.
Referenced by displaySampleRate(), handleMessage(), on_record_toggled(), on_startStop_toggled(), updateADCRate(), updateHardware(), updateStatus(), and XTRXInputGUI().
ui
Ui::XTRXInputGUI* XTRXInputGUI::ui private
Definition at line 56 of file xtrxinputgui.h.
Referenced by displaySampleRate(), displaySettings(), handleMessage(), on_extClock_clicked(), on_gain_valueChanged(), on_gainMode_currentIndexChanged(), on_hwDecim_currentIndexChanged(), on_lnaGain_valueChanged(), on_pgaGain_valueChanged(), on_record_toggled(), setCenterFrequencyDisplay(), setCenterFrequencySetting(), setNCODisplay(), updateADCRate(), updateStatus(), XTRXInputGUI(), and ~XTRXInputGUI().
The documentation for this class was generated from the following files:
plugins/samplesource/xtrxinput/xtrxinputgui.h
plugins/samplesource/xtrxinput/xtrxinputgui.cpp