SDRAngel: FileSinkGui Class Reference
FileSinkGui Class Reference
#include <filesinkgui.h>
Public Member Functions
FileSinkGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~FileSinkGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_centerFrequency_changed (quint64 value)
void on_sampleRate_changed (quint64 value)
void on_startStop_toggled (bool checked)
void on_showFileDialog_clicked (bool checked)
void on_interp_currentIndexChanged (int index)
void updateHardware ()
void updateStatus ()
void tick ()
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void displayTime ()
void sendSettings ()
void configureFileName ()
void updateWithGeneration ()
void updateWithStreamTime ()
void updateSampleRateAndFrequency ()
Private Attributes
Ui::FileSinkGui * ui
DeviceUISet * m_deviceUISet
bool m_doApplySettings
bool m_forceSettings
FileSinkSettings m_settings
QString m_fileName
QTimer m_updateTimer
QTimer m_statusTimer
DeviceSampleSink * m_deviceSampleSink
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
bool m_generation
std::time_t m_startingTimeStamp
int m_samplesCount
std::size_t m_tickCount
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 38 of file filesinkgui.h.
Constructor & Destructor Documentation
FileSinkGui()
FileSinkGui::FileSinkGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 39 of file filesinkgui.cpp.
References displaySettings(), DeviceAPI::getMasterTimer(), DeviceAPI::getSampleSink(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceSampleSink, m_deviceUISet, m_fileName, m_inputMessageQueue, m_statusTimer, m_updateTimer, tick(), ui, updateHardware(), and updateStatus().
                                                                   :
     QWidget(parent),
     ui(new Ui::FileSinkGui),
     m_deviceUISet(deviceUISet),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_settings(),
     m_fileName("./test.sdriq"),
     m_deviceSampleSink(0),
     m_sampleRate(0),
     m_generation(false),
     m_startingTimeStamp(0),
     m_samplesCount(0),
     m_tickCount(0),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, 0, pow(10,7));
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(7, 32000U, 9000000U);
     ui->fileNameText->setText(m_fileName);
     connect(&(m_deviceUISet->m_deviceAPI->getMasterTimer()), SIGNAL(timeout()), this, SLOT(tick()));
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     displaySettings();
     m_deviceSampleSink = (FileSinkOutput*) m_deviceUISet->m_deviceAPI->getSampleSink();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
 }
~FileSinkGui()
FileSinkGui::~FileSinkGui () virtual
Definition at line 76 of file filesinkgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void FileSinkGui::blockApplySettings (bool block) inline private
Definition at line 77 of file filesinkgui.h.
Referenced by handleMessage().
 { m_doApplySettings = !block; }
configureFileName()
void FileSinkGui::configureFileName () private
Definition at line 304 of file filesinkgui.cpp.
References FileSinkOutput::MsgConfigureFileSinkName::create(), DeviceSampleSink::getInputMessageQueue(), m_deviceSampleSink, m_fileName, and MessageQueue::push().
Referenced by on_showFileDialog_clicked().
 {
     qDebug() << "FileSinkGui::configureFileName: " << m_fileName.toStdString().c_str();
     FileSinkOutput::MsgConfigureFileSinkName* message = FileSinkOutput::MsgConfigureFileSinkName::create(m_fileName);
     m_deviceSampleSink->getInputMessageQueue()->push(message);
 }
deserialize()
bool FileSinkGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 120 of file filesinkgui.cpp.
References FileSinkSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void FileSinkGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 81 of file filesinkgui.cpp.
 {
     delete this;
 }
displaySettings()
void FileSinkGui::displaySettings () private
Definition at line 207 of file filesinkgui.cpp.
References FileSinkSettings::m_centerFrequency, FileSinkSettings::m_sampleRate, m_settings, and ui.
Referenced by deserialize(), FileSinkGui(), handleMessage(), resetToDefaults(), and setCenterFrequency().
 {
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     ui->sampleRate->setValue(m_settings.m_sampleRate);
 }
displayTime()
void FileSinkGui::displayTime () private
getCenterFrequency()
qint64 FileSinkGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 103 of file filesinkgui.cpp.
References FileSinkSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* FileSinkGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 54 of file filesinkgui.h.
 { return &m_inputMessageQueue; }
getName()
QString FileSinkGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 91 of file filesinkgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void FileSinkGui::handleInputMessages () private slot
Definition at line 173 of file filesinkgui.cpp.
References DSPSignalNotification::getCenterFrequency(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by FileSinkGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             qDebug("FileSinkGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool FileSinkGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 133 of file filesinkgui.cpp.
References blockApplySettings(), displaySettings(), FileSinkOutput::MsgConfigureFileSink::getSettings(), FileSinkOutput::MsgStartStop::getStartStop(), m_generation, m_samplesCount, m_settings, Message::match(), ui, updateWithGeneration(), and updateWithStreamTime().
Referenced by handleInputMessages().
 {
     if (FileSinkOutput::MsgConfigureFileSink::match(message))
     {
         qDebug("FileSinkGui::handleMessage: message: MsgConfigureFileSink");
         const FileSinkOutput::MsgConfigureFileSink& cfg = (FileSinkOutput::MsgConfigureFileSink&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (FileSinkOutput::MsgReportFileSinkGeneration::match(message))
     {
         m_generation = ((FileSinkOutput::MsgReportFileSinkGeneration&)message).getAcquisition();
         qDebug("FileSinkGui::handleMessage: message: MsgReportFileSinkGeneration: %s", m_generation ? "start" : "stop");
         updateWithGeneration();
         return true;
     }
     else if (FileSinkOutput::MsgReportFileSinkStreamTiming::match(message))
     {
         m_samplesCount = ((FileSinkOutput::MsgReportFileSinkStreamTiming&)message).getSamplesCount();
         updateWithStreamTime();
         return true;
     }
     else if (FileSinkOutput::MsgStartStop::match(message))
     {
         FileSinkOutput::MsgStartStop& notif = (FileSinkOutput::MsgStartStop&) message;
         qDebug("FileSinkGui::handleMessage: message: MsgStartStop: %s", notif.getStartStop() ? "start" : "stop");
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_centerFrequency_changed
void FileSinkGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 258 of file filesinkgui.cpp.
References FileSinkSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_interp_currentIndexChanged
void FileSinkGui::on_interp_currentIndexChanged (int index) private slot
Definition at line 270 of file filesinkgui.cpp.
References FileSinkSettings::m_log2Interp, m_settings, sendSettings(), and updateSampleRateAndFrequency().
 {
     if (index < 0) {
         return;
     }
     m_settings.m_log2Interp = index;
     updateSampleRateAndFrequency();
     sendSettings();
 }
on_sampleRate_changed
void FileSinkGui::on_sampleRate_changed (quint64 value) private slot
Definition at line 264 of file filesinkgui.cpp.
References FileSinkSettings::m_sampleRate, m_settings, and sendSettings().
 {
     m_settings.m_sampleRate = value;
     sendSettings();
 }
on_showFileDialog_clicked
void FileSinkGui::on_showFileDialog_clicked (bool checked) private slot
Definition at line 290 of file filesinkgui.cpp.
References configureFileName(), m_fileName, and ui.
 {
     (void) checked;
     QString fileName = QFileDialog::getSaveFileName(this,
         tr("Save I/Q record file"), ".", tr("SDR I/Q Files (*.sdriq)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "")
     {
         m_fileName = fileName;
         ui->fileNameText->setText(m_fileName);
         configureFileName();
     }
 }
on_startStop_toggled
void FileSinkGui::on_startStop_toggled (bool checked) private slot
Definition at line 281 of file filesinkgui.cpp.
References FileSinkOutput::MsgStartStop::create(), DeviceSampleSink::getInputMessageQueue(), m_deviceSampleSink, m_doApplySettings, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         FileSinkOutput::MsgStartStop *message = FileSinkOutput::MsgStartStop::create(checked);
         m_deviceSampleSink->getInputMessageQueue()->push(message);
     }
 }
resetToDefaults()
void FileSinkGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 96 of file filesinkgui.cpp.
References displaySettings(), m_settings, FileSinkSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void FileSinkGui::sendSettings () private
Definition at line 213 of file filesinkgui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_centerFrequency_changed(), on_interp_currentIndexChanged(), on_sampleRate_changed(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray FileSinkGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 115 of file filesinkgui.cpp.
References m_settings, and FileSinkSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void FileSinkGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 108 of file filesinkgui.cpp.
References displaySettings(), FileSinkSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void FileSinkGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 86 of file filesinkgui.cpp.
 {
     setObjectName(name);
 }
tick
void FileSinkGui::tick () private slot
Definition at line 333 of file filesinkgui.cpp.
References FileSinkOutput::MsgConfigureFileSinkStreamTiming::create(), DeviceSampleSink::getInputMessageQueue(), m_deviceSampleSink, m_tickCount, and MessageQueue::push().
Referenced by FileSinkGui().
 {
     if ((++m_tickCount & 0xf) == 0)
     {
         FileSinkOutput::MsgConfigureFileSinkStreamTiming* message = FileSinkOutput::MsgConfigureFileSinkStreamTiming::create();
         m_deviceSampleSink->getInputMessageQueue()->push(message);
     }
 }
updateHardware
void FileSinkGui::updateHardware () private slot
Definition at line 220 of file filesinkgui.cpp.
References FileSinkOutput::MsgConfigureFileSink::create(), DeviceSampleSink::getInputMessageQueue(), m_deviceSampleSink, m_forceSettings, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by FileSinkGui().
 {
     qDebug() << "FileSinkGui::updateHardware";
     FileSinkOutput::MsgConfigureFileSink* message = FileSinkOutput::MsgConfigureFileSink::create(m_settings, m_forceSettings);
     m_deviceSampleSink->getInputMessageQueue()->push(message);
     m_forceSettings = false;
     m_updateTimer.stop();
 }
updateSampleRateAndFrequency()
void FileSinkGui::updateSampleRateAndFrequency () private
Definition at line 200 of file filesinkgui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, FileSinkSettings::m_log2Interp, m_sampleRate, m_settings, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages(), and on_interp_currentIndexChanged().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg((float)(m_sampleRate*(1<<m_settings.m_log2Interp)) / 1000));
 }
updateStatus
void FileSinkGui::updateStatus () private slot
Definition at line 229 of file filesinkgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by FileSinkGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
updateWithGeneration()
void FileSinkGui::updateWithGeneration () private
Definition at line 311 of file filesinkgui.cpp.
References m_generation, and ui.
Referenced by handleMessage().
 {
     ui->showFileDialog->setEnabled(!m_generation);
 }
updateWithStreamTime()
void FileSinkGui::updateWithStreamTime () private
Definition at line 316 of file filesinkgui.cpp.
References FileSinkSettings::m_sampleRate, m_samplesCount, m_settings, and ui.
Referenced by handleMessage().
 {
     int t_sec = 0;
     int t_msec = 0;
     if (m_settings.m_sampleRate > 0){
         t_msec = ((m_samplesCount * 1000) / m_settings.m_sampleRate) % 1000;
         t_sec = m_samplesCount / m_settings.m_sampleRate;
     }
     QTime t(0, 0, 0, 0);
     t = t.addSecs(t_sec);
     t = t.addMSecs(t_msec);
     QString s_timems = t.toString("HH:mm:ss.zzz");
     ui->relTimeText->setText(s_timems);
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 FileSinkGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 69 of file filesinkgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceSampleSink
DeviceSampleSink* FileSinkGui::m_deviceSampleSink private
Definition at line 67 of file filesinkgui.h.
Referenced by configureFileName(), FileSinkGui(), on_startStop_toggled(), tick(), and updateHardware().
m_deviceUISet
DeviceUISet* FileSinkGui::m_deviceUISet private
Definition at line 60 of file filesinkgui.h.
Referenced by FileSinkGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool FileSinkGui::m_doApplySettings private
Definition at line 61 of file filesinkgui.h.
Referenced by on_startStop_toggled().
m_fileName
QString FileSinkGui::m_fileName private
Definition at line 64 of file filesinkgui.h.
Referenced by configureFileName(), FileSinkGui(), and on_showFileDialog_clicked().
m_forceSettings
bool FileSinkGui::m_forceSettings private
Definition at line 62 of file filesinkgui.h.
Referenced by deserialize(), and updateHardware().
m_generation
bool FileSinkGui::m_generation private
Definition at line 70 of file filesinkgui.h.
Referenced by handleMessage(), and updateWithGeneration().
m_inputMessageQueue
MessageQueue FileSinkGui::m_inputMessageQueue private
Definition at line 75 of file filesinkgui.h.
Referenced by FileSinkGui(), and handleInputMessages().
m_lastEngineState
int FileSinkGui::m_lastEngineState private
Definition at line 74 of file filesinkgui.h.
Referenced by updateStatus().
m_sampleRate
int FileSinkGui::m_sampleRate private
Definition at line 68 of file filesinkgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_samplesCount
int FileSinkGui::m_samplesCount private
Definition at line 72 of file filesinkgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_settings
FileSinkSettings FileSinkGui::m_settings private
Definition at line 63 of file filesinkgui.h.
Referenced by deserialize(), displaySettings(), getCenterFrequency(), handleMessage(), on_centerFrequency_changed(), on_interp_currentIndexChanged(), on_sampleRate_changed(), resetToDefaults(), serialize(), setCenterFrequency(), updateHardware(), updateSampleRateAndFrequency(), and updateWithStreamTime().
m_startingTimeStamp
std::time_t FileSinkGui::m_startingTimeStamp private
Definition at line 71 of file filesinkgui.h.
m_statusTimer
QTimer FileSinkGui::m_statusTimer private
Definition at line 66 of file filesinkgui.h.
Referenced by FileSinkGui().
m_tickCount
std::size_t FileSinkGui::m_tickCount private
Definition at line 73 of file filesinkgui.h.
Referenced by tick().
m_updateTimer
QTimer FileSinkGui::m_updateTimer private
Definition at line 65 of file filesinkgui.h.
Referenced by FileSinkGui(), sendSettings(), and updateHardware().
ui
Ui::FileSinkGui* FileSinkGui::ui private
Definition at line 58 of file filesinkgui.h.
Referenced by displaySettings(), FileSinkGui(), handleMessage(), on_showFileDialog_clicked(), updateSampleRateAndFrequency(), updateStatus(), updateWithGeneration(), updateWithStreamTime(), and ~FileSinkGui().
The documentation for this class was generated from the following files:
plugins/samplesink/filesink/filesinkgui.h
plugins/samplesink/filesink/filesinkgui.cpp