SDRAngel: AMModPlugin Class Reference
AMModPlugin Class Reference
#include <ammodplugin.h>
Public Member Functions
AMModPlugin (QObject *parent=0)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
Private Attributes
PluginAPI * m_pluginAPI
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Private Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Private Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Detailed Description
Definition at line 27 of file ammodplugin.h.
Constructor & Destructor Documentation
AMModPlugin()
AMModPlugin::AMModPlugin (QObject * parent = 0) explicit
Definition at line 36 of file ammodplugin.cpp.
                                         :
     QObject(parent),
     m_pluginAPI(0)
 {
 }
Member Function Documentation
createTxChannelBS()
BasebandSampleSource * AMModPlugin::createTxChannelBS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 69 of file ammodplugin.cpp.
 {
     return new AMMod(deviceAPI);
 }
createTxChannelCS()
ChannelAPI * AMModPlugin::createTxChannelCS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 74 of file ammodplugin.cpp.
 {
     return new AMMod(deviceAPI);
 }
createTxChannelGUI()
PluginInstanceGUI * AMModPlugin::createTxChannelGUI (DeviceUISet * deviceUISet, BasebandSampleSource * txChannel) virtual
Reimplemented from PluginInterface.
Definition at line 63 of file ammodplugin.cpp.
References AMModGUI::create(), and m_pluginAPI.
Referenced by initPlugin().
 {
     return AMModGUI::create(m_pluginAPI, deviceUISet, txChannel);
 }
getPluginDescriptor()
const PluginDescriptor & AMModPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 42 of file ammodplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void AMModPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 47 of file ammodplugin.cpp.
References createTxChannelGUI(), AMMod::m_channelId, AMMod::m_channelIdURI, m_pluginAPI, and PluginAPI::registerTxChannel().
 {
     m_pluginAPI = pluginAPI;
     // register AM modulator
     m_pluginAPI->registerTxChannel(AMMod::m_channelIdURI, AMMod::m_channelId, this);
 }
Member Data Documentation
m_pluginAPI
PluginAPI* AMModPlugin::m_pluginAPI private
Definition at line 45 of file ammodplugin.h.
Referenced by createTxChannelGUI(), and initPlugin().
m_pluginDescriptor
const PluginDescriptor AMModPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("AM Modulator"),
    QString("4.11.5"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 43 of file ammodplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/channeltx/modam/ammodplugin.h
plugins/channeltx/modam/ammodplugin.cpp