SDRAngel: Interpolator Class Reference
Interpolator Class Reference
#include <interpolator.h>
Public Member Functions
Interpolator ()
~Interpolator ()
void create (int phaseSteps, double sampleRate, double cutoff, double nbTapsPerPhase=4.5)
void free ()
bool decimate (Real *distance, const Complex &next, Complex *result)
bool interpolate (Real *distance, const Complex &next, Complex *result)
bool resample (Real *distance, const Complex &next, bool *consumed, Complex *result)
Private Member Functions
void createTaps (int nTaps, double sampleRate, double cutoff, std::vector< Real > *taps)
void advanceFilter (const Complex &next)
void advanceFilter ()
void doInterpolate (int phase, Complex *result)
Static Private Member Functions
static void createPolyphaseLowPass (std::vector< Real > &taps, int phaseSteps, double gain, double sampleRateHz, double cutoffFreqHz, double transitionWidthHz, double oobAttenuationdB)
static void createPolyphaseLowPass (std::vector< Real > &taps, int phaseSteps, double gain, double sampleRateHz, double cutoffFreqHz, double nbTapsPerPhase)
Private Attributes
float * m_taps
float * m_alignedTaps
float * m_taps2
float * m_alignedTaps2
std::vector< Complex > m_samples
int m_ptr
int m_phaseSteps
int m_nTaps
Detailed Description
Definition at line 28 of file interpolator.h.
Constructor & Destructor Documentation
Interpolator()
Interpolator::Interpolator ()
Definition at line 70 of file interpolator.cpp.
                            :
     m_taps(0),
     m_alignedTaps(0),
     m_taps2(0),
     m_alignedTaps2(0),
     m_ptr(0),
     m_phaseSteps(1),
     m_nTaps(1)
 {
 }
~Interpolator()
Interpolator::~Interpolator ()
Definition at line 81 of file interpolator.cpp.
References free().
 {
     free();
 }
Member Function Documentation
advanceFilter() [1/2]
void Interpolator::advanceFilter (const Complex & next) inline private
Definition at line 121 of file interpolator.h.
     {
         m_ptr--;
         if (m_ptr < 0) {
             m_ptr = m_nTaps - 1;
         }
         m_samples[m_ptr] = next;
     }
advanceFilter() [2/2]
void Interpolator::advanceFilter () inline private
Definition at line 132 of file interpolator.h.
     {
         m_ptr--;
         if (m_ptr < 0) {
             m_ptr = m_nTaps - 1;
         }
         m_samples[m_ptr].real(0.0);
         m_samples[m_ptr].imag(0.0);
     }
create()
void Interpolator::create (int phaseSteps, double sampleRate, double cutoff, double nbTapsPerPhase = 4.5)
Definition at line 86 of file interpolator.cpp.
References createPolyphaseLowPass(), free(), i, m_alignedTaps, m_alignedTaps2, m_nTaps, m_phaseSteps, m_ptr, m_samples, m_taps, and m_taps2.
Referenced by WFMDemod::applyAudioSampleRate(), AMDemod::applyAudioSampleRate(), NFMDemod::applyAudioSampleRate(), BFMDemod::applyAudioSampleRate(), WFMMod::applyAudioSampleRate(), AMMod::applyAudioSampleRate(), NFMMod::applyAudioSampleRate(), SSBDemod::applyAudioSampleRate(), SSBMod::applyAudioSampleRate(), ChannelAnalyzer::applyChannelSettings(), WFMDemod::applyChannelSettings(), AMDemod::applyChannelSettings(), UDPSink::applyChannelSettings(), UDPSource::applyChannelSettings(), NFMDemod::applyChannelSettings(), DSDDemod::applyChannelSettings(), BFMDemod::applyChannelSettings(), WFMMod::applyChannelSettings(), AMMod::applyChannelSettings(), NFMMod::applyChannelSettings(), SSBDemod::applyChannelSettings(), FreeDVMod::applyChannelSettings(), SSBMod::applyChannelSettings(), FreeDVDemod::applyChannelSettings(), ATVMod::applyChannelSettings(), AMMod::applyFeedbackAudioSampleRate(), NFMMod::applyFeedbackAudioSampleRate(), SSBMod::applyFeedbackAudioSampleRate(), FreeDVMod::applyFreeDVMode(), FreeDVDemod::applyFreeDVMode(), ChannelAnalyzer::applySettings(), WFMDemod::applySettings(), AMDemod::applySettings(), UDPSink::applySettings(), UDPSource::applySettings(), NFMDemod::applySettings(), DSDDemod::applySettings(), BFMDemod::applySettings(), WFMMod::applySettings(), AMMod::applySettings(), NFMMod::applySettings(), SSBDemod::applySettings(), SSBMod::applySettings(), ATVDemod::applySettings(), ATVMod::applySettings(), LoRaDemod::handleMessage(), LoRaDemod::LoRaDemod(), FreqTracker::setInterpolator(), and UDPSink::UDPSink().
 {
     free();
     std::vector<Real> taps;
     createPolyphaseLowPass(
         taps,
         phaseSteps, // number of polyphases
         1.0, // gain
         phaseSteps * sampleRate, // sampling frequency
         cutoff, // hz beginning of transition band
         nbTapsPerPhase);
     // init state
     m_ptr = 0;
     m_nTaps = taps.size() / phaseSteps;
     m_phaseSteps = phaseSteps;
     m_samples.resize(m_nTaps + 2);
     for (int i = 0; i < m_nTaps + 2; i++) {
         m_samples[i] = 0;
     }
     // reorder into polyphase
     std::vector<Real> polyphase(taps.size());
     for (int phase = 0; phase < phaseSteps; phase++)
     {
         for (int i = 0; i < m_nTaps; i++) {
             polyphase[phase * m_nTaps + i] = taps[i * phaseSteps + phase];
         }
     }
     // normalize phase filters
     for (int phase = 0; phase < phaseSteps; phase++)
     {
         Real sum = 0;
         for (int i = phase * m_nTaps; i < phase * m_nTaps + m_nTaps; i++) {
             sum += polyphase[i];
         }
         for (int i = phase * m_nTaps; i < phase * m_nTaps + m_nTaps; i++) {
             polyphase[i] /= sum;
         }
     }
     // move taps around to match sse storage requirements
     m_taps = new float[2 * taps.size() + 8];
     for (uint i = 0; i < 2 * taps.size() + 8; ++i) {
         m_taps[i] = 0;
     }
     m_alignedTaps = (float*)((((quint64)m_taps) + 15) & ~15);
     for (uint i = 0; i < taps.size(); ++i)
     {
         m_alignedTaps[2 * i + 0] = polyphase[i];
         m_alignedTaps[2 * i + 1] = polyphase[i];
     }
     m_taps2 = new float[2 * taps.size() + 8];
     for (uint i = 0; i < 2 * taps.size() + 8; ++i) {
         m_taps2[i] = 0;
     }
     m_alignedTaps2 = (float*)((((quint64)m_taps2) + 15) & ~15);
     for (uint i = 1; i < taps.size(); ++i)
     {
         m_alignedTaps2[2 * (i - 1) + 0] = polyphase[i];
         m_alignedTaps2[2 * (i - 1) + 1] = polyphase[i];
     }
 }
createPolyphaseLowPass() [1/2]
void Interpolator::createPolyphaseLowPass (std::vector< Real > & taps, int phaseSteps, double gain, double sampleRateHz, double cutoffFreqHz, double transitionWidthHz, double oobAttenuationdB) static private
Definition at line 7 of file interpolator.cpp.
Referenced by create().
 {
     double nbTapsPerPhase = (oobAttenuationdB * sampleRateHz) / (22.0 * transitionWidthHz * phaseSteps);
     return createPolyphaseLowPass(taps, phaseSteps, gain, sampleRateHz, cutoffFreqHz, nbTapsPerPhase);
 }
createPolyphaseLowPass() [2/2]
void Interpolator::createPolyphaseLowPass (std::vector< Real > & taps, int phaseSteps, double gain, double sampleRateHz, double cutoffFreqHz, double nbTapsPerPhase) static private
Definition at line 21 of file interpolator.cpp.
References cos(), i, M_PI, leansdr::max(), and sin().
 {
     int ntaps = (int)(nbTapsPerPhase * phaseSteps);
     qDebug("Interpolator::createPolyphaseLowPass: ntaps: %d", ntaps);
     if ((ntaps % 2) != 0) {
         ntaps++;
     }
     ntaps *= phaseSteps;
     taps.resize(ntaps);
     std::vector<float> window(ntaps);
     for (int n = 0; n < ntaps; n++) {
         window[n] = 0.54 - 0.46 * cos ((2 * M_PI * n) / (ntaps - 1));
     }
     int M = (ntaps - 1) / 2;
     double fwT0 = 2 * M_PI * cutoffFreqHz / sampleRateHz;
     for (int n = -M; n <= M; n++)
     {
         if (n == 0) {
             taps[n + M] = fwT0 / M_PI * window[n + M];
         } else {
             taps[n + M] =  sin (n * fwT0) / (n * M_PI) * window[n + M];
         }
     }
     double max = taps[0 + M];
     for (int n = 1; n <= M; n++) {
         max += 2.0 * taps[n + M];
     }
     gain /= max;
     for (int i = 0; i < ntaps; i++) {
         taps[i] *= gain;
     }
 }
createTaps()
void Interpolator::createTaps (int nTaps, double sampleRate, double cutoff, std::vector< Real > * taps) private
decimate()
bool Interpolator::decimate (Real * distance, const Complex & next, Complex * result) inline
Definition at line 38 of file interpolator.h.
References floor().
Referenced by LoRaDemod::feed(), WFMDemod::feed(), AMDemod::feed(), DSDDemod::feed(), UDPSink::feed(), SSBDemod::feed(), NFMDemod::feed(), FreqTracker::feed(), BFMDemod::feed(), FreeDVDemod::feed(), ChannelAnalyzer::feed(), ATVDemod::feed(), UDPSource::pull(), AMMod::pull(), NFMMod::pull(), SSBMod::pull(), FreeDVMod::pull(), ATVMod::pull(), AMMod::pushFeedback(), NFMMod::pushFeedback(), and SSBMod::pushFeedback().
     {
         advanceFilter(next);
         *distance -= 1.0;
         if (*distance >= 1.0) {
             return false;
         }
         doInterpolate((int) floor(*distance * (Real)m_phaseSteps), result);
         return true;
     }
doInterpolate()
void Interpolator::doInterpolate (int phase, Complex * result) inline private
Definition at line 144 of file interpolator.h.
References i.
     {
         if (phase < 0) {
             phase = 0;
         }
 #if USE_SSE2
         // beware of the ringbuffer
         if(m_ptr == 0) {
             // only one straight block
             const float* src = (const float*)&m_samples[0];
             const __m128* filter = (const __m128*)&m_alignedTaps[phase * m_nTaps * 2];
             __m128 sum = _mm_setzero_ps();
             int todo = m_nTaps / 2;
             for(int i = 0; i < todo; i++) {
                 sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadu_ps(src), *filter));
                 src += 4;
                 filter += 1;
             }
             // add upper half to lower half and store
             _mm_storel_pi((__m64*)result, _mm_add_ps(sum, _mm_shuffle_ps(sum, _mm_setzero_ps(), _MM_SHUFFLE(1, 0, 3, 2))));
         } else {
             // two blocks
             const float* src = (const float*)&m_samples[m_ptr];
             const __m128* filter = (const __m128*)&m_alignedTaps[phase * m_nTaps * 2];
             __m128 sum = _mm_setzero_ps();
             // first block
             int block = m_nTaps - m_ptr;
             int todo = block / 2;
             if(block & 1)
                 todo++;
             for(int i = 0; i < todo; i++) {
                 sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadu_ps(src), *filter));
                 src += 4;
                 filter += 1;
             }
             if(block & 1) {
                 // one sample beyond the end -> switch coefficient table
                 filter = (const __m128*)&m_alignedTaps2[phase * m_nTaps * 2 + todo * 4 - 4];
             }
             // second block
             src = (const float*)&m_samples[0];
             block = m_ptr;
             todo = block / 2;
             for(int i = 0; i < todo; i++) {
                 sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadu_ps(src), *filter));
                 src += 4;
                 filter += 1;
             }
             if(block & 1) {
                 // one sample remaining
                 sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadl_pi(_mm_setzero_ps(), (const __m64*)src), filter[0]));
             }
             // add upper half to lower half and store
             _mm_storel_pi((__m64*)result, _mm_add_ps(sum, _mm_shuffle_ps(sum, _mm_setzero_ps(), _MM_SHUFFLE(1, 0, 3, 2))));
         }
 #else
         int sample = m_ptr;
         const Real* coeff = &m_alignedTaps[phase * m_nTaps * 2];
         Real rAcc = 0;
         Real iAcc = 0;
         for (int i = 0; i < m_nTaps; i++) {
             rAcc += *coeff * m_samples[sample].real();
             iAcc += *coeff * m_samples[sample].imag();
             sample = (sample + 1) % m_nTaps;
             coeff += 2;
         }
         *result = Complex(rAcc, iAcc);
 #endif
     }
free()
void Interpolator::free ()
Definition at line 164 of file interpolator.cpp.
References m_alignedTaps, m_alignedTaps2, m_taps, and m_taps2.
Referenced by create(), and ~Interpolator().
 {
     if (m_taps != NULL)
     {
         delete[] m_taps;
         m_taps = NULL;
         m_alignedTaps = NULL;
         delete[] m_taps2;
         m_taps2 = NULL;
         m_alignedTaps2 = NULL;
     }
 }
interpolate()
bool Interpolator::interpolate (Real * distance, const Complex & next, Complex * result) inline
Definition at line 53 of file interpolator.h.
References floor().
Referenced by AMDemod::feed(), SSBDemod::feed(), NFMDemod::feed(), FreqTracker::feed(), FreeDVDemod::feed(), UDPSource::pull(), AMMod::pull(), WFMMod::pull(), NFMMod::pull(), SSBMod::pull(), FreeDVMod::pull(), ATVMod::pull(), AMMod::pushFeedback(), NFMMod::pushFeedback(), and SSBMod::pushFeedback().
     {
         bool consumed = false;
         if (*distance >= 1.0)
         {
             advanceFilter(next);
             *distance -= 1.0;
             consumed = true;
         }
         doInterpolate((int)floor(*distance * (Real)m_phaseSteps), result);
         return consumed;
     }
resample()
bool Interpolator::resample (Real * distance, const Complex & next, bool * consumed, Complex * result) inline
Definition at line 71 of file interpolator.h.
References floor().
     {
         while (*distance >= 1.0)
         {
             if (!(*consumed))
             {
                 advanceFilter(next);
                 *distance -= 1.0;
                 *consumed = true;
             }
             else
             {
                 return false;
             }
         }
         doInterpolate((int)floor(*distance * (Real)m_phaseSteps), result);
         return true;
     }
Member Data Documentation
m_alignedTaps
float* Interpolator::m_alignedTaps private
Definition at line 94 of file interpolator.h.
Referenced by create(), and free().
m_alignedTaps2
float* Interpolator::m_alignedTaps2 private
Definition at line 96 of file interpolator.h.
Referenced by create(), and free().
m_nTaps
int Interpolator::m_nTaps private
Definition at line 100 of file interpolator.h.
Referenced by create().
m_phaseSteps
int Interpolator::m_phaseSteps private
Definition at line 99 of file interpolator.h.
Referenced by create().
m_ptr
int Interpolator::m_ptr private
Definition at line 98 of file interpolator.h.
Referenced by create().
m_samples
std::vector<Complex> Interpolator::m_samples private
Definition at line 97 of file interpolator.h.
Referenced by create().
m_taps
float* Interpolator::m_taps private
Definition at line 93 of file interpolator.h.
Referenced by create(), and free().
m_taps2
float* Interpolator::m_taps2 private
Definition at line 95 of file interpolator.h.
Referenced by create(), and free().
The documentation for this class was generated from the following files:
sdrbase/dsp/interpolator.h
sdrbase/dsp/interpolator.cpp