SDRAngel: MainCore::MsgLoadPreset Class Reference
MainCore::MsgLoadPreset Class Reference
Public Member Functions
const Preset * getPreset () const
int getDeviceSetIndex () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgLoadPreset * create (const Preset *preset, int deviceSetIndex)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgLoadPreset (const Preset *preset, int deviceSetIndex)
Private Attributes
const Preset * m_preset
int m_deviceSetIndex
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 75 of file maincore.h.
Constructor & Destructor Documentation
MsgLoadPreset()
MainCore::MsgLoadPreset::MsgLoadPreset (const Preset * preset, int deviceSetIndex) inline private
Definition at line 91 of file maincore.h.
                                                                 :
             Message(),
             m_preset(preset),
             m_deviceSetIndex(deviceSetIndex)
         { }
Member Function Documentation
create()
static MsgLoadPreset* MainCore::MsgLoadPreset::create (const Preset * preset, int deviceSetIndex) inline static
Definition at line 82 of file maincore.h.
Referenced by WebAPIAdapterSrv::instancePresetPatch().
         {
             return new MsgLoadPreset(preset, deviceSetIndex);
         }
getDeviceSetIndex()
int MainCore::MsgLoadPreset::getDeviceSetIndex () const inline
Definition at line 80 of file maincore.h.
Referenced by MainCore::handleMessage().
 { return m_deviceSetIndex; }
getPreset()
const Preset* MainCore::MsgLoadPreset::getPreset () const inline
Definition at line 79 of file maincore.h.
Referenced by MainCore::handleMessage().
 { return m_preset; }
Member Data Documentation
m_deviceSetIndex
int MainCore::MsgLoadPreset::m_deviceSetIndex private
Definition at line 89 of file maincore.h.
m_preset
const Preset* MainCore::MsgLoadPreset::m_preset private
Definition at line 88 of file maincore.h.
The documentation for this class was generated from the following file:
sdrsrv/maincore.h