SDRAngel: LocalSink::MsgConfigureChannelizer Class Reference
LocalSink::MsgConfigureChannelizer Class Reference
#include <localsink.h>
Public Member Functions
int getLog2Decim () const
int getFilterChainHash () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (unsigned int log2Decim, unsigned int filterChainHash)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (unsigned int log2Decim, unsigned int filterChainHash)
Private Attributes
unsigned int m_log2Decim
unsigned int m_filterChainHash
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 83 of file localsink.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
LocalSink::MsgConfigureChannelizer::MsgConfigureChannelizer (unsigned int log2Decim, unsigned int filterChainHash) inline private
Definition at line 98 of file localsink.h.
References LocalSink::LocalSink(), and LocalSink::~LocalSink().
                                                                                       :
             Message(),
             m_log2Decim(log2Decim),
             m_filterChainHash(filterChainHash)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* LocalSink::MsgConfigureChannelizer::create (unsigned int log2Decim, unsigned int filterChainHash) inline static
Definition at line 90 of file localsink.h.
Referenced by LocalSinkGUI::applyChannelSettings(), and LocalSink::webapiSettingsPutPatch().
{
             return new MsgConfigureChannelizer(log2Decim, filterChainHash);
         }
getFilterChainHash()
int LocalSink::MsgConfigureChannelizer::getFilterChainHash () const inline
Definition at line 88 of file localsink.h.
Referenced by LocalSink::handleMessage().
 { return m_filterChainHash; }
getLog2Decim()
int LocalSink::MsgConfigureChannelizer::getLog2Decim () const inline
Definition at line 87 of file localsink.h.
Referenced by LocalSink::handleMessage().
 { return m_log2Decim; }
Member Data Documentation
m_filterChainHash
unsigned int LocalSink::MsgConfigureChannelizer::m_filterChainHash private
Definition at line 96 of file localsink.h.
m_log2Decim
unsigned int LocalSink::MsgConfigureChannelizer::m_log2Decim private
Definition at line 95 of file localsink.h.
The documentation for this class was generated from the following file:
plugins/channelrx/localsink/localsink.h