SDRAngel: ScopeVis::TriggerComparator Class Reference
ScopeVis::TriggerComparator Class Reference
Public Member Functions
TriggerComparator ()
bool triggered (const Sample &s, TriggerCondition &triggerCondition)
void reset ()
Private Member Functions
void computeLevels ()
Private Attributes
Real m_level
Real m_levelPowerDB
Real m_levelPowerLin
bool m_reset
Detailed Description
Definition at line 1031 of file scopevis.h.
Constructor & Destructor Documentation
TriggerComparator()
ScopeVis::TriggerComparator::TriggerComparator () inline
Definition at line 1034 of file scopevis.h.
                             : m_level(0), m_reset(true)
         {
             computeLevels();
         }
Member Function Documentation
computeLevels()
void ScopeVis::TriggerComparator::computeLevels () inline private
Definition at line 1109 of file scopevis.h.
         {
             m_levelPowerLin = m_level + 1.0f;
             m_levelPowerDB = (100.0f * (m_level - 1.0f));
         }
reset()
void ScopeVis::TriggerComparator::reset () inline
Definition at line 1103 of file scopevis.h.
Referenced by ScopeVis::processTrace().
         {
             m_reset = true;
         }
triggered()
bool ScopeVis::TriggerComparator::triggered (const Sample & s, TriggerCondition & triggerCondition) inline
Definition at line 1039 of file scopevis.h.
References Projector::getProjectionType(), ScopeVis::TriggerCondition::m_falses, ScopeVis::TriggerCondition::m_prevCondition, ScopeVis::TriggerCondition::m_projector, ScopeVis::TriggerData::m_triggerBothEdges, ScopeVis::TriggerCondition::m_triggerData, ScopeVis::TriggerData::m_triggerHoldoff, ScopeVis::TriggerData::m_triggerLevel, ScopeVis::TriggerData::m_triggerPositiveEdge, ScopeVis::TriggerCondition::m_trues, Projector::ProjectionMagDB, Projector::ProjectionMagLin, and Projector::run().
Referenced by ScopeVis::processTrace().
         {
             if (triggerCondition.m_triggerData.m_triggerLevel != m_level)
             {
                 m_level = triggerCondition.m_triggerData.m_triggerLevel;
                 computeLevels();
             }
             bool condition, trigger;
             if (triggerCondition.m_projector.getProjectionType() == Projector::ProjectionMagDB) {
                 condition = triggerCondition.m_projector.run(s) > m_levelPowerDB;
             } else if (triggerCondition.m_projector.getProjectionType() == Projector::ProjectionMagLin) {
                 condition = triggerCondition.m_projector.run(s) > m_levelPowerLin;
             } else {
                 condition = triggerCondition.m_projector.run(s) > m_level;
             }
             if (condition)
             {
                 if (triggerCondition.m_trues < triggerCondition.m_triggerData.m_triggerHoldoff) {
                     condition = false;
                     triggerCondition.m_trues++;
                 } else {
                     triggerCondition.m_falses = 0;
                 }
             }
             else
             {
                 if (triggerCondition.m_falses < triggerCondition.m_triggerData.m_triggerHoldoff) {
                     condition = true;
                     triggerCondition.m_falses++;
                 } else {
                     triggerCondition.m_trues = 0;
                 }
             }
             if (m_reset)
             {
                 triggerCondition.m_prevCondition = condition;
                 m_reset = false;
                 return false;
             }
             if (triggerCondition.m_triggerData.m_triggerBothEdges) {
                 trigger = triggerCondition.m_prevCondition ? !condition : condition; // This is a XOR between bools
             } else if (triggerCondition.m_triggerData.m_triggerPositiveEdge) {
                 trigger = !triggerCondition.m_prevCondition && condition;
             } else {
                 trigger = triggerCondition.m_prevCondition && !condition;
             }
 //            if (trigger) {
 //                qDebug("ScopeVis::triggered: %s/%s %f/%f",
 //                        triggerCondition.m_prevCondition ? "T" : "F",
 //                        condition ? "T" : "F",
 //                        triggerCondition.m_projector->run(s),
 //                        triggerCondition.m_triggerData.m_triggerLevel);
 //            }
             triggerCondition.m_prevCondition = condition;
             return trigger;
         }
Member Data Documentation
m_level
Real ScopeVis::TriggerComparator::m_level private
Definition at line 1115 of file scopevis.h.
m_levelPowerDB
Real ScopeVis::TriggerComparator::m_levelPowerDB private
Definition at line 1116 of file scopevis.h.
m_levelPowerLin
Real ScopeVis::TriggerComparator::m_levelPowerLin private
Definition at line 1117 of file scopevis.h.
m_reset
bool ScopeVis::TriggerComparator::m_reset private
Definition at line 1118 of file scopevis.h.
The documentation for this class was generated from the following file:
sdrgui/dsp/scopevis.h