SDRAngel: FreqTracker::MsgSampleRateNotification Class Reference
FreqTracker::MsgSampleRateNotification Class Reference
#include <freqtracker.h>
Public Member Functions
int getSampleRate () const
int getFrequencyOffset () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgSampleRateNotification * create (int sampleRate, int frequencyOffset)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgSampleRateNotification (int sampleRate, int frequencyOffset)
Private Attributes
int m_sampleRate
int m_frequencyOffset
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 98 of file freqtracker.h.
Constructor & Destructor Documentation
MsgSampleRateNotification()
FreqTracker::MsgSampleRateNotification::MsgSampleRateNotification (int sampleRate, int frequencyOffset) inline private
Definition at line 110 of file freqtracker.h.
                                                                        :
             Message(),
             m_sampleRate(sampleRate),
             m_frequencyOffset(frequencyOffset)
         { }
Member Function Documentation
create()
static MsgSampleRateNotification* FreqTracker::MsgSampleRateNotification::create (int sampleRate, int frequencyOffset) inline static
Definition at line 102 of file freqtracker.h.
Referenced by FreqTracker::configureChannelizer().
{
             return new MsgSampleRateNotification(sampleRate, frequencyOffset);
         }
getFrequencyOffset()
int FreqTracker::MsgSampleRateNotification::getFrequencyOffset () const inline
Definition at line 107 of file freqtracker.h.
Referenced by FreqTrackerGUI::handleMessage().
 { return m_frequencyOffset; }
getSampleRate()
int FreqTracker::MsgSampleRateNotification::getSampleRate () const inline
Definition at line 106 of file freqtracker.h.
Referenced by FreqTrackerGUI::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_frequencyOffset
int FreqTracker::MsgSampleRateNotification::m_frequencyOffset private
Definition at line 117 of file freqtracker.h.
m_sampleRate
int FreqTracker::MsgSampleRateNotification::m_sampleRate private
Definition at line 116 of file freqtracker.h.
The documentation for this class was generated from the following file:
plugins/channelrx/freqtracker/freqtracker.h