SDRAngel: GLShaderSimple Class Reference
GLShaderSimple Class Reference
#include <glshadersimple.h>
Public Member Functions
GLShaderSimple ()
~GLShaderSimple ()
void initializeGL ()
void drawPoints (const QMatrix4x4 &transformMatrix, const QVector4D &color, GLfloat *vertices, int nbVertices)
void drawPolyline (const QMatrix4x4 &transformMatrix, const QVector4D &color, GLfloat *vertices, int nbVertices)
void drawSegments (const QMatrix4x4 &transformMatrix, const QVector4D &color, GLfloat *vertices, int nbVertices)
void drawContour (const QMatrix4x4 &transformMatrix, const QVector4D &color, GLfloat *vertices, int nbVertices)
void drawSurface (const QMatrix4x4 &transformMatrix, const QVector4D &color, GLfloat *vertices, int nbVertices)
void cleanup ()
Private Member Functions
void draw (unsigned int mode, const QMatrix4x4 &transformMatrix, const QVector4D &color, GLfloat *vertices, int nbVertices)
Private Attributes
QOpenGLShaderProgram * m_program
int m_matrixLoc
int m_colorLoc
Static Private Attributes
static const QString m_vertexShaderSourceSimple
static const QString m_fragmentShaderSourceColored
Detailed Description
Definition at line 31 of file glshadersimple.h.
Constructor & Destructor Documentation
GLShaderSimple()
GLShaderSimple::GLShaderSimple ()
Definition at line 28 of file glshadersimple.cpp.
                                :
     m_program(0),
     m_matrixLoc(0),
     m_colorLoc(0)
 { }
~GLShaderSimple()
GLShaderSimple::~GLShaderSimple ()
Definition at line 34 of file glshadersimple.cpp.
References cleanup().
 {
     cleanup();
 }
Member Function Documentation
cleanup()
void GLShaderSimple::cleanup ()
Definition at line 104 of file glshadersimple.cpp.
References m_fragmentShaderSourceColored, m_program, and m_vertexShaderSourceSimple.
Referenced by GLScope::cleanup(), GLSpectrum::cleanup(), and ~GLShaderSimple().
 {
     if (m_program)
     {
         delete m_program;
         m_program = 0;
     }
 }
draw()
void GLShaderSimple::draw (unsigned int mode, const QMatrix4x4 & transformMatrix, const QVector4D & color, GLfloat * vertices, int nbVertices) private
Definition at line 88 of file glshadersimple.cpp.
References m_colorLoc, m_matrixLoc, and m_program.
Referenced by drawContour(), drawPoints(), drawPolyline(), drawSegments(), and drawSurface().
 {
     QOpenGLFunctions *f = QOpenGLContext::currentContext()->functions();
     m_program->bind();
     m_program->setUniformValue(m_matrixLoc, transformMatrix);
     m_program->setUniformValue(m_colorLoc, color);
     f->glEnable(GL_BLEND);
     f->glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
     f->glLineWidth(1.0f);
     f->glEnableVertexAttribArray(0); // vertex
     f->glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, vertices);
     f->glDrawArrays(mode, 0, nbVertices);
     f->glDisableVertexAttribArray(0);
     m_program->release();
 }
drawContour()
void GLShaderSimple::drawContour (const QMatrix4x4 & transformMatrix, const QVector4D & color, GLfloat * vertices, int nbVertices)
Definition at line 78 of file glshadersimple.cpp.
References draw().
Referenced by GLScope::paintGL(), and GLSpectrum::paintGL().
 {
     draw(GL_LINE_LOOP, transformMatrix, color, vertices, nbVertices);
 }
drawPoints()
void GLShaderSimple::drawPoints (const QMatrix4x4 & transformMatrix, const QVector4D & color, GLfloat * vertices, int nbVertices)
Definition at line 63 of file glshadersimple.cpp.
References draw().
Referenced by GLScope::paintGL().
 {
     draw(GL_POINTS, transformMatrix, color, vertices, nbVertices);
 }
drawPolyline()
void GLShaderSimple::drawPolyline (const QMatrix4x4 & transformMatrix, const QVector4D & color, GLfloat * vertices, int nbVertices)
Definition at line 68 of file glshadersimple.cpp.
References draw().
Referenced by GLScope::paintGL(), and GLSpectrum::paintGL().
 {
     draw(GL_LINE_STRIP, transformMatrix, color, vertices, nbVertices);
 }
drawSegments()
void GLShaderSimple::drawSegments (const QMatrix4x4 & transformMatrix, const QVector4D & color, GLfloat * vertices, int nbVertices)
Definition at line 73 of file glshadersimple.cpp.
References draw().
Referenced by GLScope::paintGL(), and GLSpectrum::paintGL().
 {
     draw(GL_LINES, transformMatrix, color, vertices, nbVertices);
 }
drawSurface()
void GLShaderSimple::drawSurface (const QMatrix4x4 & transformMatrix, const QVector4D & color, GLfloat * vertices, int nbVertices)
Definition at line 83 of file glshadersimple.cpp.
References draw().
Referenced by GLSpectrum::paintGL().
 {
     draw(GL_TRIANGLE_FAN, transformMatrix, color, vertices, nbVertices);
 }
initializeGL()
void GLShaderSimple::initializeGL ()
Definition at line 39 of file glshadersimple.cpp.
References m_colorLoc, m_fragmentShaderSourceColored, m_matrixLoc, m_program, and m_vertexShaderSourceSimple.
Referenced by GLScope::initializeGL(), and GLSpectrum::initializeGL().
 {
     m_program = new QOpenGLShaderProgram;
     if (!m_program->addShaderFromSourceCode(QOpenGLShader::Vertex, m_vertexShaderSourceSimple)) {
         qDebug() << "GLShaderSimple::initializeGL: error in vertex shader: " << m_program->log();
     }
     if (!m_program->addShaderFromSourceCode(QOpenGLShader::Fragment, m_fragmentShaderSourceColored)) {
         qDebug() << "GLShaderSimple::initializeGL: error in fragment shader: " << m_program->log();
     }
     m_program->bindAttributeLocation("vertex", 0);
     if (!m_program->link()) {
         qDebug() << "GLShaderSimple::initializeGL: error linking shader: " << m_program->log();
     }
     m_program->bind();
     m_matrixLoc = m_program->uniformLocation("uMatrix");
     m_colorLoc = m_program->uniformLocation("uColour");
     m_program->release();
 }
Member Data Documentation
m_colorLoc
int GLShaderSimple::m_colorLoc private
Definition at line 50 of file glshadersimple.h.
Referenced by draw(), and initializeGL().
m_fragmentShaderSourceColored
const QString GLShaderSimple::m_fragmentShaderSourceColored static private
Initial value:
= QString(
        "uniform mediump vec4 uColour;\n"
        "void main() {\n"
        "    gl_FragColor = uColour;\n"
        "}\n"
        )
Definition at line 52 of file glshadersimple.h.
Referenced by cleanup(), and initializeGL().
m_matrixLoc
int GLShaderSimple::m_matrixLoc private
Definition at line 49 of file glshadersimple.h.
Referenced by draw(), and initializeGL().
m_program
QOpenGLShaderProgram* GLShaderSimple::m_program private
Definition at line 48 of file glshadersimple.h.
Referenced by cleanup(), draw(), and initializeGL().
m_vertexShaderSourceSimple
const QString GLShaderSimple::m_vertexShaderSourceSimple static private
Initial value:
= QString(
        "uniform highp mat4 uMatrix;\n"
        "attribute highp vec4 vertex;\n"
        "void main() {\n"
        "    gl_Position = uMatrix * vertex;\n"
        "}\n"
        )
Definition at line 51 of file glshadersimple.h.
Referenced by cleanup(), and initializeGL().
The documentation for this class was generated from the following files:
sdrgui/gui/glshadersimple.h
sdrgui/gui/glshadersimple.cpp