SDRAngel: LimeSDROutputPlugin Class Reference
LimeSDROutputPlugin Class Reference
#include <limesdroutputplugin.h>
Public Member Functions
LimeSDROutputPlugin (QObject *parent=0)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "LimeSDR"
static const QString m_deviceTypeID = LIMESDROUTPUT_DEVICE_TYPE_ID
Static Private Member Functions
static bool findSerial (const char *lmsInfoStr, std::string &serial)
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 28 of file limesdroutputplugin.h.
Constructor & Destructor Documentation
LimeSDROutputPlugin()
LimeSDROutputPlugin::LimeSDROutputPlugin (QObject * parent = 0) explicit
Definition at line 47 of file limesdroutputplugin.cpp.
                                                         :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSinkPluginInstance()
DeviceSampleSink * LimeSDROutputPlugin::createSampleSinkPluginInstance (const QString & sinkId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 162 of file limesdroutputplugin.cpp.
References m_deviceTypeID.
 {
     if(sinkId == m_deviceTypeID)
     {
         LimeSDROutput* output = new LimeSDROutput(deviceAPI);
         return output;
     }
     else
     {
         return 0;
     }
 }
createSampleSinkPluginInstanceGUI()
PluginInstanceGUI * LimeSDROutputPlugin::createSampleSinkPluginInstanceGUI (const QString & sinkId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 126 of file limesdroutputplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSinks().
 {
     if(sinkId == m_deviceTypeID)
     {
         LimeSDROutputGUI* gui = new LimeSDROutputGUI(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSinks()
PluginInterface::SamplingDevices LimeSDROutputPlugin::enumSampleSinks () virtual
Reimplemented from PluginInterface.
Definition at line 62 of file limesdroutputplugin.cpp.
References arg(), DeviceLimeSDRParams::close(), createSampleSinkPluginInstanceGUI(), findSerial(), i, m_deviceTypeID, m_hardwareID, DeviceLimeSDRParams::m_nbTxChannels, DeviceLimeSDRParams::open(), PluginInterface::SamplingDevice::PhysicalDevice, and PluginInterface::SamplingDevice::StreamSingleTx.
 {
     lms_info_str_t* deviceList;
     int nbDevices;
     SamplingDevices result;
     if ((nbDevices = LMS_GetDeviceList(0)) <= 0)
     {
         qDebug("LimeSDROutputPlugin::enumSampleSources: Could not find any LimeSDR device");
         return result; // empty result
     }
     deviceList = new lms_info_str_t[nbDevices];
     if (LMS_GetDeviceList(deviceList) < 0)
     {
         qDebug("LimeSDROutputPlugin::enumSampleSources: Could not obtain LimeSDR devices information");
         delete[] deviceList;
         return result; // empty result
     }
     else
     {
         for (int i = 0; i < nbDevices; i++)
         {
             std::string serial("N/D");
             findSerial((const char *) deviceList[i], serial);
             DeviceLimeSDRParams limeSDRParams;
             limeSDRParams.open(deviceList[i]);
             limeSDRParams.close();
             for (unsigned int j = 0; j < limeSDRParams.m_nbTxChannels; j++)
             {
                 qDebug("LimeSDROutputPlugin::enumSampleSources: device #%d channel %u: %s", i, j, (char *) deviceList[i]);
                 QString displayedName(QString("LimeSDR[%1:%2] %3").arg(i).arg(j).arg(serial.c_str()));
                 result.append(SamplingDevice(displayedName,
                         m_hardwareID,
                         m_deviceTypeID,
                         QString(deviceList[i]),
                         i,
                         PluginInterface::SamplingDevice::PhysicalDevice,
                         PluginInterface::SamplingDevice::StreamSingleTx,
                         limeSDRParams.m_nbTxChannels,
                         j));
             }
         }
     }
     delete[] deviceList;
     return result;
 }
findSerial()
bool LimeSDROutputPlugin::findSerial (const char * lmsInfoStr, std::string & serial) static private
Definition at line 144 of file limesdroutputplugin.cpp.
Referenced by enumSampleSinks().
 {
     std::regex serial_reg("serial=([0-9,A-F]+)");
     std::string input(lmsInfoStr);
     std::smatch result;
     std::regex_search(input, result, serial_reg);
     if (result[1].str().length()>0)
     {
         serial = result[1].str();
         return true;
     }
     else
     {
         return false;
     }
 }
getPluginDescriptor()
const PluginDescriptor & LimeSDROutputPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 52 of file limesdroutputplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void LimeSDROutputPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 57 of file limesdroutputplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSink().
 {
     pluginAPI->registerSampleSink(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString LimeSDROutputPlugin::m_deviceTypeID = LIMESDROUTPUT_DEVICE_TYPE_ID static
Definition at line 47 of file limesdroutputplugin.h.
Referenced by createSampleSinkPluginInstance(), createSampleSinkPluginInstanceGUI(), enumSampleSinks(), and initPlugin().
m_hardwareID
const QString LimeSDROutputPlugin::m_hardwareID = "LimeSDR" static
Definition at line 46 of file limesdroutputplugin.h.
Referenced by enumSampleSinks().
m_pluginDescriptor
const PluginDescriptor LimeSDROutputPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("LimeSDR Output"),
    QString("4.5.5"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 50 of file limesdroutputplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesink/limesdroutput/limesdroutputplugin.h
plugins/samplesink/limesdroutput/limesdroutputplugin.cpp