SDRAngel: Bladerf1InputThread Class Reference
Bladerf1InputThread Class Reference
#include <bladerf1inputthread.h>
Inherits QThread.
Public Member Functions
Bladerf1InputThread (struct bladerf *dev, SampleSinkFifo *sampleFifo, QObject *parent=NULL)
~Bladerf1InputThread ()
void startWork ()
void stopWork ()
void setLog2Decimation (unsigned int log2_decim)
void setFcPos (int fcPos)
Private Member Functions
void run ()
void callback (const qint16 *buf, qint32 len)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
struct bladerf * m_dev
qint16 m_buf [2 *BLADERF_BLOCKSIZE]
SampleVector m_convertBuffer
SampleSinkFifo * m_sampleFifo
unsigned int m_log2Decim
int m_fcPos
Decimators< qint32, qint16, SDR_RX_SAMP_SZ, 12 > m_decimators
Detailed Description
Definition at line 30 of file bladerf1inputthread.h.
Constructor & Destructor Documentation
Bladerf1InputThread()
Bladerf1InputThread::Bladerf1InputThread (struct bladerf * dev, SampleSinkFifo * sampleFifo, QObject * parent = NULL)
Definition at line 27 of file bladerf1inputthread.cpp.
References BLADERF_BLOCKSIZE, and m_buf.
                                                                                                          :
     QThread(parent),
     m_running(false),
     m_dev(dev),
     m_convertBuffer(BLADERF_BLOCKSIZE),
     m_sampleFifo(sampleFifo),
     m_log2Decim(0),
     m_fcPos(0)
 {
     std::fill(m_buf, m_buf + 2*BLADERF_BLOCKSIZE, 0);
 }
~Bladerf1InputThread()
Bladerf1InputThread::~Bladerf1InputThread ()
Definition at line 39 of file bladerf1inputthread.cpp.
References stopWork().
 {
     stopWork();
 }
Member Function Documentation
callback()
void Bladerf1InputThread::callback (const qint16 * buf, qint32 len) private
Definition at line 89 of file bladerf1inputthread.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup(), m_convertBuffer, m_decimators, m_fcPos, m_log2Decim, m_sampleFifo, and SampleSinkFifo::write().
Referenced by run().
 {
     SampleVector::iterator it = m_convertBuffer.begin();
     if (m_log2Decim == 0)
     {
         m_decimators.decimate1(&it, buf, len);
     }
     else
     {
         if (m_fcPos == 0) // Infra
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_inf(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_inf(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_inf(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_inf(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_inf(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_inf(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 1) // Supra
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_sup(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_sup(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_sup(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_sup(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_sup(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_sup(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 2) // Center
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_cen(&it, buf, len);
                 break;
             case 2:
                 m_decimators.decimate4_cen(&it, buf, len);
                 break;
             case 3:
                 m_decimators.decimate8_cen(&it, buf, len);
                 break;
             case 4:
                 m_decimators.decimate16_cen(&it, buf, len);
                 break;
             case 5:
                 m_decimators.decimate32_cen(&it, buf, len);
                 break;
             case 6:
                 m_decimators.decimate64_cen(&it, buf, len);
                 break;
             default:
                 break;
             }
         }
     }
     m_sampleFifo->write(m_convertBuffer.begin(), it);
 }
run()
void Bladerf1InputThread::run () private
Definition at line 69 of file bladerf1inputthread.cpp.
References BLADERF_BLOCKSIZE, callback(), m_buf, m_dev, m_running, and m_startWaiter.
 {
     int res;
     m_running = true;
     m_startWaiter.wakeAll();
     while(m_running) {
         if((res = bladerf_sync_rx(m_dev, m_buf, BLADERF_BLOCKSIZE, NULL, 10000)) < 0) {
             qCritical("BladerfThread: sync error: %s", strerror(errno));
             break;
         }
         callback(m_buf, 2 * BLADERF_BLOCKSIZE);
     }
     m_running = false;
 }
setFcPos()
void Bladerf1InputThread::setFcPos (int fcPos)
Definition at line 64 of file bladerf1inputthread.cpp.
References m_fcPos.
Referenced by Bladerf1Input::applySettings(), and Bladerf1Input::start().
 {
     m_fcPos = fcPos;
 }
setLog2Decimation()
void Bladerf1InputThread::setLog2Decimation (unsigned int log2_decim)
Definition at line 59 of file bladerf1inputthread.cpp.
References m_log2Decim.
Referenced by Bladerf1Input::applySettings(), and Bladerf1Input::start().
 {
     m_log2Decim = log2_decim;
 }
startWork()
void Bladerf1InputThread::startWork ()
Definition at line 44 of file bladerf1inputthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by Bladerf1Input::start().
 {
     m_startWaitMutex.lock();
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void Bladerf1InputThread::stopWork ()
Definition at line 53 of file bladerf1inputthread.cpp.
References m_running.
Referenced by Bladerf1Input::stop(), and ~Bladerf1InputThread().
 {
     m_running = false;
     wait();
 }
Member Data Documentation
m_buf
qint16 Bladerf1InputThread::m_buf[2 *BLADERF_BLOCKSIZE] private
Definition at line 48 of file bladerf1inputthread.h.
Referenced by Bladerf1InputThread(), and run().
m_convertBuffer
SampleVector Bladerf1InputThread::m_convertBuffer private
Definition at line 49 of file bladerf1inputthread.h.
Referenced by callback().
m_decimators
Decimators<qint32, qint16, SDR_RX_SAMP_SZ, 12> Bladerf1InputThread::m_decimators private
Definition at line 55 of file bladerf1inputthread.h.
Referenced by callback().
m_dev
struct bladerf* Bladerf1InputThread::m_dev private
Definition at line 47 of file bladerf1inputthread.h.
Referenced by run().
m_fcPos
int Bladerf1InputThread::m_fcPos private
Definition at line 53 of file bladerf1inputthread.h.
Referenced by callback(), and setFcPos().
m_log2Decim
unsigned int Bladerf1InputThread::m_log2Decim private
Definition at line 52 of file bladerf1inputthread.h.
Referenced by callback(), and setLog2Decimation().
m_running
bool Bladerf1InputThread::m_running private
Definition at line 45 of file bladerf1inputthread.h.
Referenced by run(), startWork(), and stopWork().
m_sampleFifo
SampleSinkFifo* Bladerf1InputThread::m_sampleFifo private
Definition at line 50 of file bladerf1inputthread.h.
Referenced by callback().
m_startWaiter
QWaitCondition Bladerf1InputThread::m_startWaiter private
Definition at line 44 of file bladerf1inputthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex Bladerf1InputThread::m_startWaitMutex private
Definition at line 43 of file bladerf1inputthread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/samplesource/bladerf1input/bladerf1inputthread.h
plugins/samplesource/bladerf1input/bladerf1inputthread.cpp