SDRAngel: leansdr Namespace Reference
leansdr Namespace Reference
Namespaces
filtergen
Classes
struct adder
struct auto_notch
struct bbframe
struct bch_engine
struct bch_interface
struct bitpath
struct bitvect
struct buffer_reader
struct buffer_writer
struct cconverter
struct cfft_engine
struct cnr_fft
struct complex
struct convol_multipoly
struct convol_poly2
struct crc8_engine
struct cstln_base
struct cstln_lut
struct cstln_receiver
struct cstln_transmitter
struct datvconstellation
struct datvdvbs2constellation
struct datvvideoplayer
struct decimator
struct deconvol_poly
struct deconvol_poly2
struct deconvol_sync
struct deinterleaver
struct derandomizer
struct dvb_convol
struct dvb_deconvol_sync
struct etr192_descrambler
struct eucl_ss
struct fast_qpsk_receiver
struct fecframe
struct file_carrayprinter
struct file_printer
struct file_reader
struct file_vectorprinter
struct file_writer
struct fir_filter
struct fir_resampler
struct fir_sampler
struct full_ss
struct gf2n
struct gf2x_p
struct hdlc_dec
struct hdlc_sync
struct interleaver
struct itemcounter
struct ldpc_engine
struct ldpc_table
struct linear_sampler
struct llr_sb
struct llr_ss
struct modcod_info
struct mpeg_sync
struct naive_lowpass
struct nearest_sampler
struct pipebuf
struct pipebuf_common
struct pipereader
struct pipewriter
struct plslot
struct randomizer
struct rate_estimator
struct rotator
struct rs_decoder
struct rs_encoder
struct rs_engine
struct rspacket
struct runnable
struct runnable_common
struct s2_bbscrambling
struct s2_bch_engines
struct s2_deframer
struct s2_deinterleaver
struct s2_fecdec
struct s2_fecdec_helper
struct s2_fecenc
struct s2_frame_receiver
struct s2_frame_transmitter
struct s2_framer
struct s2_interleaver
struct s2_ldpc_engines
struct s2_pls
struct s2_plscodes
struct s2_scrambling
struct s2_sof
struct sampler_interface
struct scaler
struct scheduler
struct serializer
struct simple_agc
struct simplequeue
struct softsymbol
struct spectrum
struct ss_amp_estimator
struct ss_estimator
struct trellis
struct trig16
struct tspacket
struct viterbi_dec
struct viterbi_dec_interface
struct viterbi_sync
struct wgn_c
struct window_placement
Typedefs
typedef deconvol_sync< u8, 0 > deconvol_sync_simple
typedef dvb_deconvol_sync< eucl_ss > dvb_deconvol_sync_soft
typedef dvb_deconvol_sync< u8 > dvb_deconvol_sync_hard
typedef ldpc_table< uint16_t > s2_ldpc_table
typedef ldpc_engine< bool, hard_sb, 8, uint16_t > s2_ldpc_engine
typedef unsigned char u8
typedef unsigned short u16
typedef unsigned long u32
typedef signed char s8
typedef signed short s16
typedef signed long s32
typedef float f32
typedef complex< u8 > cu8
typedef complex< s8 > cs8
typedef complex< u16 > cu16
typedef complex< s16 > cs16
typedef complex< f32 > cf32
typedef uint16_t u_angle
typedef int16_t s_angle
typedef uint8_t hard_ss
typedef int8_t llr_t
typedef uint8_t hard_sb
Enumerations
enum code_rate {
FEC12, FEC23, FEC46, FEC34,
FEC56, FEC78, FEC45, FEC89,
FEC910, FEC14, FEC13, FEC25,
FEC35, FEC_COUNT
}
Functions
uint32_t crc32 (const uint8_t *buf, int len)
template<typename T , int N, typename Tm >
bitvect< T, N > divmod (const Tm *m, size_t nm, const bitvect< T, N > &p)
template<typename T , int N, typename Tm >
bitvect< T, N > shiftdivmod (const Tm *m, size_t nm, const bitvect< T, N > &p, T init=0)
template<typename T , int N>
bool operator== (const bitvect< T, N > &a, const bitvect< T, N > &b)
template<typename T , int N>
bitvect< T, N > operator+ (const bitvect< T, N > &a, const bitvect< T, N > &b)
template<typename T , int N, int NB>
bitvect< T, N > operator* (bitvect< T, N > a, const bitvect< T, NB > &b)
deconvol_sync_simple * make_deconvol_sync_simple (scheduler *sch, pipebuf< eucl_ss > &_in, pipebuf< u8 > &_out, enum code_rate rate)
const modcod_info * check_modcod (int m)
void fatal (const char *s)
void fail (const char *s)
template<typename T >
pipewriter< T > * opt_writer (pipebuf< T > *buf, unsigned long min_write=1)
template<typename T >
bool opt_writable (pipewriter< T > *p, int n=1)
template<typename T >
void opt_write (pipewriter< T > *p, T val)
template<typename T >
T gen_sqrt (T x)
float gen_sqrt (float x)
unsigned int gen_sqrt (unsigned int x)
long double gen_sqrt (long double x)
template<typename T >
T gen_abs (T x)
float gen_abs (float x)
int gen_abs (int x)
long int gen_abs (long int x)
template<typename T >
T gen_hypot (T x, T y)
float gen_hypot (float x, float y)
long double gen_hypot (long double x, long double y)
template<typename T >
T gen_atan2 (T y, T x)
float gen_atan2 (float y, float x)
long double gen_atan2 (long double y, long double x)
template<typename T >
T min (const T &x, const T &y)
template<typename T >
T max (const T &x, const T &y)
int hamming_weight (uint8_t x)
int hamming_weight (uint16_t x)
int hamming_weight (uint32_t x)
int hamming_weight (uint64_t x)
unsigned char parity (uint8_t x)
unsigned char parity (uint16_t x)
unsigned char parity (uint32_t x)
unsigned char parity (uint64_t x)
int log2i (uint64_t x)
template<typename T >
complex< T > operator+ (const complex< T > &a, const complex< T > &b)
template<typename T >
complex< T > operator* (const complex< T > &a, const complex< T > &b)
template<typename T >
complex< T > operator* (const complex< T > &a, const T &k)
template<typename T >
complex< T > operator* (const T &k, const complex< T > &a)
template<typename T >
T dotprod (const T *u, const T *v, int n)
template<typename T >
T cnorm2 (const complex< T > &u)
template<typename T >
T cnorm2 (const complex< T > *p, int n)
template<typename T >
complex< T > conjprod (const complex< T > &u, const complex< T > &v)
template<typename T >
complex< T > conjprod (const complex< T > *u, const complex< T > *v, int n)
void softsymb_harden (llr_ss *ss)
void softsymb_harden (hard_ss *ss)
void softsymb_harden (eucl_ss *ss)
uint8_t softsymb_to_dump (const llr_ss &ss, int bit)
uint8_t softsymb_to_dump (const hard_ss &ss, int bit)
uint8_t softsymb_to_dump (const eucl_ss &ss, int bit)
void to_softsymb (const full_ss *fss, hard_ss *ss)
void to_softsymb (const full_ss *fss, eucl_ss *ss)
void to_softsymb (const full_ss *fss, llr_ss *ss)
bool llr_harden (llr_t v)
bool softword_get (const hard_sb &p, int b)
void softword_set (hard_sb *p, int b, bool v)
void softword_clear (hard_sb *p)
bool softword_weight (const bool &l)
void softbit_set (bool *p, bool v)
bool softbit_harden (bool b)
uint8_t softbyte_harden (const hard_sb &b)
bool softbit_xor (bool x, bool y)
void softbit_clear (bool *p)
bool softwords_xor (const hard_sb p1[], const hard_sb p2[], int b)
void softword_zero (hard_sb *p)
void softwords_set (hard_sb p[], int b)
void softword_write (hard_sb &p, int b, bool v)
void softwords_write (hard_sb p[], int b, bool v)
void softwords_flip (hard_sb p[], int b)
uint8_t * softbytes_harden (hard_sb p[], int nbytes, uint8_t storage[])
float prob (llr_t l)
llr_t llr (float p)
llr_t llr_xor (llr_t lx, llr_t ly)
llr_t softword_get (const llr_sb &p, int b)
llr_t softwords_get (const llr_sb p[], int b)
void softword_set (llr_sb *p, int b, llr_t v)
void softword_clear (llr_sb *p)
llr_t softword_weight (llr_t l)
void softbit_set (llr_t *p, bool v)
bool softbit_harden (llr_t l)
uint8_t softbyte_harden (const llr_sb &b)
llr_t softbit_xor (llr_t x, llr_t y)
void softbit_clear (llr_t *p)
llr_t softwords_xor (const llr_sb p1[], const llr_sb p2[], int b)
void softword_zero (llr_sb *p)
void softwords_set (llr_sb p[], int b)
void softword_write (llr_sb &p, int b, llr_t v)
void softwords_write (llr_sb p[], int b, llr_t v)
void softwords_flip (llr_sb p[], int b)
uint8_t * softbytes_harden (llr_sb p[], int nbytes, uint8_t storage[])
template<typename SOFTBIT , typename SOFTBYTE >
SOFTBIT softwords_get (const SOFTBYTE p[], int b)
template<typename SOFTBIT , typename SOFTBYTE >
void softwords_set (SOFTBYTE p[], int b, SOFTBIT v)
template<typename SOFTBIT , typename SOFTBYTE >
SOFTBIT softwords_weight (const SOFTBYTE p[], int b)
Variables
const struct leansdr::modcod_info modcod_infos [32]
const float cstln_amp = 75
Typedef Documentation
cf32
typedef complex<f32> leansdr::cf32
Definition at line 34 of file sdr.h.
cs16
typedef complex<s16> leansdr::cs16
Definition at line 33 of file sdr.h.
cs8
typedef complex<s8> leansdr::cs8
Definition at line 31 of file sdr.h.
cu16
typedef complex<u16> leansdr::cu16
Definition at line 32 of file sdr.h.
cu8
typedef complex<u8> leansdr::cu8
Definition at line 30 of file sdr.h.
deconvol_sync_simple
typedef deconvol_sync<u8, 0> leansdr::deconvol_sync_simple
Definition at line 586 of file dvb.h.
dvb_deconvol_sync_hard
typedef dvb_deconvol_sync<u8> leansdr::dvb_deconvol_sync_hard
Definition at line 827 of file dvb.h.
dvb_deconvol_sync_soft
typedef dvb_deconvol_sync<eucl_ss> leansdr::dvb_deconvol_sync_soft
Definition at line 826 of file dvb.h.
f32
typedef float leansdr::f32
Definition at line 28 of file sdr.h.
hard_sb
typedef uint8_t leansdr::hard_sb
Definition at line 21 of file softword.h.
hard_ss
typedef uint8_t leansdr::hard_ss
Definition at line 423 of file sdr.h.
llr_t
typedef int8_t leansdr::llr_t
Definition at line 444 of file sdr.h.
s16
typedef signed short leansdr::s16
Definition at line 457 of file framework.h.
s2_ldpc_engine
typedef ldpc_engine<bool, hard_sb, 8, uint16_t> leansdr::s2_ldpc_engine
Definition at line 1868 of file dvbs2.h.
s2_ldpc_table
typedef ldpc_table<uint16_t> leansdr::s2_ldpc_table
Definition at line 1867 of file dvbs2.h.
s32
typedef signed long leansdr::s32
Definition at line 458 of file framework.h.
s8
typedef signed char leansdr::s8
Definition at line 456 of file framework.h.
s_angle
typedef int16_t leansdr::s_angle
Definition at line 385 of file sdr.h.
u16
typedef unsigned short leansdr::u16
Definition at line 454 of file framework.h.
u32
typedef unsigned long leansdr::u32
Definition at line 455 of file framework.h.
u8
typedef unsigned char leansdr::u8
Definition at line 453 of file framework.h.
u_angle
typedef uint16_t leansdr::u_angle
Definition at line 384 of file sdr.h.
Enumeration Type Documentation
code_rate
enum leansdr::code_rate
Enumerator
FEC12
FEC23
FEC46
FEC34
FEC56
FEC78
FEC45
FEC89
FEC910
FEC14
FEC13
FEC25
FEC35
FEC_COUNT
Definition at line 41 of file dvb.h.
 {
     FEC12,
     FEC23,
     FEC46,
     FEC34,
     FEC56,
     FEC78, // DVB-S
     FEC45,
     FEC89,
     FEC910, // DVB-S2
     FEC14,
     FEC13,
     FEC25,
     FEC35, // DVB-S2
     FEC_COUNT
 };
Function Documentation
check_modcod()
const modcod_info* leansdr::check_modcod (int m)
Definition at line 285 of file dvbs2.h.
References fail(), modcod_infos, and leansdr::modcod_info::nslots_nf.
Referenced by leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::receive_frame(), leansdr::s2_frame_transmitter< T >::run(), leansdr::s2_interleaver::run(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::run(), leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::run(), leansdr::s2_framer::run(), and leansdr::s2_fecenc::run_frame().
 {
     if (m < 0 || m > 31)
         fail("Invalid MODCOD number");
     const modcod_info *r = &modcod_infos[m];
     if (!r->nslots_nf)
         fail("Unsupported MODCOD");
     return r;
 }
cnorm2() [1/2]
template<typename T > T leansdr::cnorm2 (const complex< T > & u) inline
Definition at line 89 of file math.h.
References leansdr::complex< T >::im, and leansdr::complex< T >::re.
Referenced by cnorm2(), and leansdr::s2_frame_receiver< T, SOFTSYMB >::init_agc().
 {
     return u.re * u.re + u.im * u.im;
 }
cnorm2() [2/2]
template<typename T > T leansdr::cnorm2 (const complex< T > * p, int n)
Definition at line 95 of file math.h.
References cnorm2().
 {
     T res = 0;
     for (; n--; ++p)
         res += cnorm2(*p);
     return res;
 }
conjprod() [1/2]
template<typename T > complex<T> leansdr::conjprod (const complex< T > & u, const complex< T > & v) inline
Definition at line 105 of file math.h.
References leansdr::complex< T >::im, and leansdr::complex< T >::re.
Referenced by conjprod(), and leansdr::s2_frame_receiver< T, SOFTSYMB >::run_frame_locked().
 {
     return complex<T>(u.re * v.re + u.im * v.im,
                       u.re * v.im - u.im * v.re);
 }
conjprod() [2/2]
template<typename T > complex<T> leansdr::conjprod (const complex< T > * u, const complex< T > * v, int n)
Definition at line 113 of file math.h.
References conjprod(), hamming_weight(), log2i(), and parity().
 {
     complex<T> acc = 0;
     while (n--)
         acc += conjprod(*u++, *v++);
     return acc;
 }
crc32()
uint32_t leansdr::crc32 (const uint8_t * buf, int len)
Definition at line 58 of file crc.h.
References i.
Referenced by FileRecord::readHeader(), UDPSinkFEC::write(), and FileRecord::writeHeader().
 {
     static const uint32_t poly = 0xedb88320;
     uint32_t c = 0xffffffff;
     for (int i = 0; i < len; ++i)
     {
         c ^= buf[i];
         for (int bit = 8; bit--;)
             c = (c & 1) ? (c >> 1) ^ poly : (c >> 1);
     }
     return c ^ 0xffffffff;
 }
divmod()
template<typename T , int N, typename Tm > bitvect<T, N> leansdr::divmod (const Tm * m, size_t nm, const bitvect< T, N > & p)
Definition at line 111 of file discrmath.h.
References leansdr::bitvect< T, N >::v.
Referenced by leansdr::bch_engine< T, N, NP, DP, TGF, GFTRUNCGEN >::decode().
 {
     bitvect<T, N> res = 0;
     const Tm bitmask = (Tm)1 << (sizeof(Tm) * 8 - 1);
     for (; nm--; ++m)
     {
         Tm mi = *m;
         for (int bit = sizeof(Tm) * 8; bit--; mi <<= 1)
         {
             // Multiply by X, save outgoing coeff of degree N
             bool resN = res[N - 1];
             res <<= 1;
             // Add m[i]
             if (mi & bitmask)
                 res.v[0] ^= 1;
             // Modulo X^N+p
             if (resN)
                 res += p;
         }
     }
     return res;
 }
dotprod()
template<typename T > T leansdr::dotprod (const T * u, const T * v, int n)
Definition at line 80 of file math.h.
 {
     T acc = 0;
     while (n--)
         acc += (*u++) * (*v++);
     return acc;
 }
fail()
void leansdr::fail (const char * s)
Definition at line 11 of file framework.cpp.
Referenced by leansdr::scheduler::add_pipe(), leansdr::pipebuf< leansdr::complex< leansdr::f32 > >::add_reader(), leansdr::scheduler::add_runnable(), leansdr::s2_frame_receiver< T, SOFTSYMB >::add_syncs(), leansdr::bch_engine< T, N, NP, DP, TGF, GFTRUNCGEN >::bch_engine(), check_modcod(), leansdr::cnr_fft< leansdr::f32 >::cnr_fft(), leansdr::cstln_lut< SOFTSYMB, 256 >::cstln_lut(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::decode_bitflip(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deinterleave(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deserialize_qpsk(), leansdr::dvb_convol::dvb_convol(), leansdr::fir_resampler< T, Tc >::fir_resampler(), leansdr::gf2n< TGF, DP, 2, GFTRUNCGEN >::gf2n(), leansdr::gf2x_p< unsigned char, unsigned short, 0x11d, 8, 2 >::gf2x_p(), leansdr::s2_interleaver::interleave(), leansdr::deconvol_sync< leansdr::u8, 0 >::inverse_convolution(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::ldpc_engine(), leansdr::deconvol_sync< leansdr::u8, 0 >::next_sync(), leansdr::bitvect< T, DP >::operator<<=(), leansdr::deconvol_poly2< Tin, uint32_t, uint64_t, 0x3ba, 0x38f70 >::run(), leansdr::s2_frame_transmitter< T >::run(), leansdr::cstln_receiver< leansdr::f32, leansdr::eucl_ss >::run(), leansdr::rs_decoder< leansdr::u8, 0 >::run(), leansdr::fast_qpsk_receiver< T >::run(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::run(), leansdr::cstln_transmitter< Tout, Zout >::run(), leansdr::viterbi_sync::run(), leansdr::s2_framer::run(), leansdr::s2_frame_transmitter< T >::run_frame(), leansdr::s2_interleaver::serialize_qpsk(), leansdr::serializer< Tin, Tout >::serializer(), and leansdr::viterbi_sync::viterbi_sync().
 {
     fprintf(stderr, "** %s\n", s);
 }
fatal()
void leansdr::fatal (const char * s)
Definition at line 6 of file framework.cpp.
Referenced by leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::node::append(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::count_edges(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deinterleave(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deinterleave4050(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deserialize_qpsk(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::encode(), leansdr::convol_multipoly< uint16_t, 16 >::encode(), leansdr::file_vectorprinter< T, N >::file_vectorprinter(), leansdr::s2_interleaver::interleave(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::ldpc_engine(), leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::receive_frame(), leansdr::datvvideoplayer< leansdr::tspacket >::run(), leansdr::file_reader< T >::run(), leansdr::file_writer< leansdr::complex >::run(), leansdr::file_printer< T >::run(), leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::send_frame(), leansdr::s2_interleaver::serialize_qpsk(), leansdr::file_reader< T >::set_realtime(), and leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::spawn_helper().
 {
     perror(s);
 }
gen_abs() [1/4]
template<typename T > T leansdr::gen_abs (T x)
Referenced by leansdr::auto_notch< leansdr::f32 >::detect(), and gen_sqrt().
gen_abs() [2/4]
float leansdr::gen_abs (float x) inline
Definition at line 400 of file framework.h.
 {
     return fabsf(x);
 }
gen_abs() [3/4]
int leansdr::gen_abs (int x) inline
Definition at line 405 of file framework.h.
References abs().
 {
     return abs(x);
 }
gen_abs() [4/4]
long int leansdr::gen_abs (long int x) inline
Definition at line 410 of file framework.h.
References gen_hypot().
 {
     return labs(x);
 }
gen_atan2() [1/3]
template<typename T > T leansdr::gen_atan2 (T y, T x)
Referenced by gen_hypot().
gen_atan2() [2/3]
float leansdr::gen_atan2 (float y, float x) inline
Definition at line 429 of file framework.h.
 {
     return atan2f(y, x);
 }
gen_atan2() [3/3]
long double leansdr::gen_atan2 (long double y, long double x) inline
Definition at line 434 of file framework.h.
 {
     return atan2l(y, x);
 }
gen_hypot() [1/3]
template<typename T > T leansdr::gen_hypot (T x, T y)
Referenced by gen_abs().
gen_hypot() [2/3]
float leansdr::gen_hypot (float x, float y) inline
Definition at line 417 of file framework.h.
 {
     return hypotf(x, y);
 }
gen_hypot() [3/3]
long double leansdr::gen_hypot (long double x, long double y) inline
Definition at line 422 of file framework.h.
References gen_atan2().
 {
     return hypotl(x, y);
 }
gen_sqrt() [1/4]
template<typename T > T leansdr::gen_sqrt (T x)
Referenced by leansdr::auto_notch< leansdr::f32 >::detect(), leansdr::filtergen::normalize_power(), leansdr::pipereader< leansdr::complex< leansdr::f32 > >::read(), leansdr::cstln_receiver< leansdr::f32, leansdr::eucl_ss >::run(), and leansdr::s2_frame_receiver< T, SOFTSYMB >::update_agc().
gen_sqrt() [2/4]
float leansdr::gen_sqrt (float x) inline
Definition at line 383 of file framework.h.
 {
     return sqrtf(x);
 }
gen_sqrt() [3/4]
unsigned int leansdr::gen_sqrt (unsigned int x) inline
Definition at line 388 of file framework.h.
 {
     return sqrtl(x);
 }
gen_sqrt() [4/4]
long double leansdr::gen_sqrt (long double x) inline
Definition at line 393 of file framework.h.
References gen_abs().
 {
     return sqrtl(x);
 }
hamming_weight() [1/4]
int leansdr::hamming_weight (uint8_t x)
Definition at line 6 of file math.cpp.
Referenced by conjprod(), leansdr::rs_engine::correct(), leansdr::deconvol_sync< leansdr::u8, 0 >::deconvol_sync(), hamming_weight(), leansdr::deconvol_sync< leansdr::u8, 0 >::inverse_convolution(), leansdr::deconvol_poly2< Tin, uint32_t, uint64_t, 0x3ba, 0x38f70 >::run(), leansdr::s2_frame_receiver< T, SOFTSYMB >::run_frame_locked(), and leansdr::s2_frame_receiver< T, SOFTSYMB >::run_frame_search().
 {
     static const int lut[16] = {0, 1, 1, 2, 1, 2, 2, 3, 1, 2, 2, 3, 2, 3, 3, 4};
     return lut[x & 15] + lut[x >> 4];
 }
hamming_weight() [2/4]
int leansdr::hamming_weight (uint16_t x)
Definition at line 12 of file math.cpp.
References hamming_weight().
 {
     return hamming_weight((uint8_t)x) + hamming_weight((uint8_t)(x >> 8));
 }
hamming_weight() [3/4]
int leansdr::hamming_weight (uint32_t x)
Definition at line 17 of file math.cpp.
References hamming_weight().
 {
     return hamming_weight((uint16_t)x) + hamming_weight((uint16_t)(x >> 16));
 }
hamming_weight() [4/4]
int leansdr::hamming_weight (uint64_t x)
Definition at line 22 of file math.cpp.
References hamming_weight().
 {
     return hamming_weight((uint32_t)x) + hamming_weight((uint32_t)(x >> 32));
 }
llr()
llr_t leansdr::llr (float p)
Definition at line 83 of file softword.h.
Referenced by llr_xor().
 {
     int r = -127 + 254 * p;
     if (r < -127)
         r = -127;
     if (r > 127)
         r = 127;
     return r;
 }
llr_harden()
bool leansdr::llr_harden (llr_t v) inline
Definition at line 446 of file sdr.h.
Referenced by leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::pack_qpsk_symbol(), and leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::split_symbol().
 {
     return v & 128;
 }
llr_xor()
llr_t leansdr::llr_xor (llr_t lx, llr_t ly) inline
Definition at line 92 of file softword.h.
References llr(), and prob().
Referenced by softbit_xor(), and softwords_xor().
 {
     float px = prob(lx), py = prob(ly);
     return llr(px * (1 - py) + (1 - px) * py);
 }
log2i()
int leansdr::log2i (uint64_t x)
Definition at line 48 of file math.cpp.
Referenced by conjprod(), leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::init_convolutional(), and leansdr::viterbi_sync::viterbi_sync().
 {
     int n = -1;
     for (; x; ++n, x >>= 1)
         ;
     return n;
 }
make_deconvol_sync_simple()
deconvol_sync_simple * leansdr::make_deconvol_sync_simple (scheduler * sch, pipebuf< eucl_ss > & _in, pipebuf< u8 > & _out, enum code_rate rate)
Definition at line 6 of file dvb.cpp.
References FEC12, FEC23, FEC34, FEC46, FEC56, and FEC78.
 {
     // EN 300 421, section 4.4.3 Inner coding
     uint32_t pX, pY;
     switch (rate)
     {
     case FEC12:
         pX = 0x1; // 1
         pY = 0x1; // 1
         break;
     case FEC23:
     case FEC46:
         pX = 0xa; // 1010  (Handle as FEC4/6, no half-symbols)
         pY = 0xf; // 1111
         break;
     case FEC34:
         pX = 0x5; // 101
         pY = 0x6; // 110
         break;
     case FEC56:
         pX = 0x15; // 10101
         pY = 0x1a; // 11010
         break;
     case FEC78:
         pX = 0x45; // 1000101
         pY = 0x7a; // 1111010
         break;
     default:
         //fail("Code rate not implemented");
         // For testing DVB-S2 constellations.
         fprintf(stderr, "Code rate not implemented; proceeding anyway\n");
         pX = pY = 1;
     }
     return new deconvol_sync_simple(sch, _in, _out, DVBS_G1, DVBS_G2, pX, pY);
 }
max()
template<typename T > T leansdr::max (const T & x, const T & y)
Definition at line 446 of file framework.h.
Referenced by FreeDVDemod::FreeDVSNR::accumulate(), FreeDVDemod::LevelRMS::accumulate(), Bladerf1Output::applySettings(), HackRFOutput::applySettings(), BladeRF2Output::applySettings(), SoapySDROutput::applySettings(), BladeRF2Input::applySettings(), LimeSDROutput::applySettings(), BladeRF2InputGui::BladeRF2InputGui(), BladeRF2OutputGui::BladeRF2OutputGui(), ScaleEngine::calcCharSize(), UDPSource::calculateLevel(), WFMMod::calculateLevel(), AMMod::calculateLevel(), NFMMod::calculateLevel(), FreeDVMod::calculateLevel(), SSBMod::calculateLevel(), ATVMod::calculateLevel(), clamp(), AudioCompressorSnd::clampf(), SoapySDRInputGui::createGlobalGainControl(), SoapySDROutputGui::createGlobalGainControl(), Interpolator::createPolyphaseLowPass(), decimation(), BladeRF2InputGui::displaySampleRate(), BladeRF2OutputGui::displaySampleRate(), LoRaDemod::dumpRaw(), SpectrumVis::feed(), PlutoSDROutput::getbbLPRange(), PlutoSDRInput::getbbLPRange(), DeviceBladeRF2::getDev(), PlutoSDROutput::getLORange(), PlutoSDRInput::getLORange(), ScaleEngine::getScaleWidth(), ArgInfoGUI::getValueType(), BladeRF2InputGui::handleMessage(), BladeRF2OutputGui::handleMessage(), BladeRF2Input::handleMessage(), qrtplib::RTPPacketBuilder::Init(), DATVDemod::InitDATVFramework(), DATVDemod::InitDATVS2Framework(), polar(), PhaseLock::process(), PhaseLock::process_phasor(), UDPSourceUDPHandler::resizeBuffer(), LevelMeterSignalDB::setColorTheme(), qrtplib::RTPSessionParams::SetMaximumPacketSize(), qrtplib::RTPPacketBuilder::SetMaximumPacketSize(), ArgInfoGUI::setRange(), BladeRF2Output::setSampleRate(), SoapySDROutput::setSampleRate(), BladeRF2Input::setSampleRate(), SoapySDRInput::setSampleRate(), ValueDial::setValueRange(), ValueDialZ::setValueRange(), Max2D< double >::storeAndGetMax(), BladeRF2Output::webapiFormatDeviceReport(), and BladeRF2Input::webapiFormatDeviceReport().
 {
     return (x < y) ? y : x;
 }
min()
template<typename T > T leansdr::min (const T & x, const T & y)
Definition at line 440 of file framework.h.
Referenced by SSBDemodGUI::applyBandwidths(), GLScope::applyConfig(), AMMod::applyFeedbackAudioSampleRate(), NFMMod::applyFeedbackAudioSampleRate(), SSBMod::applyFeedbackAudioSampleRate(), BladeRF2Output::applySettings(), BladeRF2Input::applySettings(), BladeRF2InputGui::BladeRF2InputGui(), BladeRF2OutputGui::BladeRF2OutputGui(), clamp(), SoapySDRInputGui::createGlobalGainControl(), SoapySDROutputGui::createGlobalGainControl(), BladeRF2InputGui::displaySampleRate(), BladeRF2OutputGui::displaySampleRate(), PlutoSDROutput::getbbLPRange(), PlutoSDRInput::getbbLPRange(), DeviceBladeRF2::getDev(), PlutoSDROutput::getLORange(), PlutoSDRInput::getLORange(), ArgInfoGUI::getValueType(), BladeRF2InputGui::handleMessage(), BladeRF2OutputGui::handleMessage(), BladeRF2Input::handleMessage(), GLScope::paintGL(), PhaseLock::process(), PhaseLock::process_phasor(), leansdr::etr192_descrambler::run(), leansdr::cconverter< Tin, Zin, Tout, Zout, Gn, Gd >::run(), leansdr::scaler< Tscale, Tin, Tout >::run(), leansdr::naive_lowpass< T >::run(), leansdr::fir_filter< leansdr::complex, float >::run(), leansdr::decimator< leansdr::complex >::run(), leansdr::rate_estimator< float >::run(), leansdr::fir_resampler< T, Tc >::run(), leansdr::buffer_reader< T >::run(), leansdr::buffer_writer< T >::run(), leansdr::dvb_convol::run(), leansdr::cstln_transmitter< Tout, Zout >::run(), leansdr::rotator< leansdr::f32 >::run(), LevelMeterSignalDB::setColorTheme(), GLScope::setPolarDisplays(), ArgInfoGUI::setRange(), BladeRF2Output::setSampleRate(), SoapySDROutput::setSampleRate(), BladeRF2Input::setSampleRate(), SoapySDRInput::setSampleRate(), ValueDial::setValueRange(), ValueDialZ::setValueRange(), FileSinkThread::tick(), BladeRF2Output::webapiFormatDeviceReport(), and BladeRF2Input::webapiFormatDeviceReport().
 {
     return (x < y) ? x : y;
 }
operator*() [1/4]
template<typename T > complex<T> leansdr::operator* (const complex< T > & a, const complex< T > & b)
Definition at line 62 of file math.h.
References leansdr::complex< T >::im, and leansdr::complex< T >::re.
 {
     return complex<T>(a.re * b.re - a.im * b.im, a.re * b.im + a.im * b.re);
 }
operator*() [2/4]
template<typename T > complex<T> leansdr::operator* (const complex< T > & a, const T & k)
Definition at line 68 of file math.h.
References leansdr::complex< T >::im, and leansdr::complex< T >::re.
 {
     return complex<T>(a.re * k, a.im * k);
 }
operator*() [3/4]
template<typename T > complex<T> leansdr::operator* (const T & k, const complex< T > & a)
Definition at line 74 of file math.h.
References leansdr::complex< T >::im, and leansdr::complex< T >::re.
 {
     return complex<T>(k * a.re, k * a.im);
 }
operator*() [4/4]
template<typename T , int N, int NB> bitvect<T, N> leansdr::operator* (bitvect< T, N > a, const bitvect< T, NB > & b)
Definition at line 186 of file discrmath.h.
References i.
 {
     bitvect<T, N> res = 0;
     for (int i = 0; i < NB; ++i, a <<= 1)
         if (b[i])
             res += a;
     // TBD If truncation is needed, do it only once at the end.
     return res;
 }
operator+() [1/2]
template<typename T > complex<T> leansdr::operator+ (const complex< T > & a, const complex< T > & b)
Definition at line 56 of file math.h.
References leansdr::complex< T >::im, and leansdr::complex< T >::re.
 {
     return complex<T>(a.re + b.re, a.im + b.im);
 }
operator+() [2/2]
template<typename T , int N> bitvect<T, N> leansdr::operator+ (const bitvect< T, N > & a, const bitvect< T, N > & b)
Definition at line 175 of file discrmath.h.
References i, leansdr::bitvect< T, N >::NW, and leansdr::bitvect< T, N >::v.
 {
     bitvect<T, N> res;
     for (int i = 0; i < a.NW; ++i)
         res.v[i] = a.v[i] ^ b.v[i];
     return res;
 }
operator==()
template<typename T , int N> bool leansdr::operator== (const bitvect< T, N > & a, const bitvect< T, N > & b)
Definition at line 164 of file discrmath.h.
References i, leansdr::bitvect< T, N >::NW, and leansdr::bitvect< T, N >::v.
Referenced by qrtplib::RTPAddress::GetAddressType().
 {
     for (int i = 0; i < a.NW; ++i)
         if (a.v[i] != b.v[i])
             return false;
     return true;
 }
opt_writable()
template<typename T > bool leansdr::opt_writable (pipewriter< T > * p, int n = 1)
Definition at line 335 of file framework.h.
References leansdr::pipewriter< T >::writable().
Referenced by leansdr::hdlc_sync::run(), leansdr::s2_frame_receiver< T, SOFTSYMB >::run(), leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::run(), leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::run(), and leansdr::s2_deframer::run().
 {
     return (p == NULL) || p->writable() >= n;
 }
opt_write()
template<typename T > void leansdr::opt_write (pipewriter< T > * p, T val)
Definition at line 341 of file framework.h.
References leansdr::pipewriter< T >::write().
Referenced by leansdr::s2_frame_receiver< T, SOFTSYMB >::enter_coarse_freq(), leansdr::s2_frame_receiver< T, SOFTSYMB >::enter_frame_locked(), leansdr::s2_frame_receiver< T, SOFTSYMB >::enter_frame_search(), leansdr::s2_deframer::info_good_packet(), leansdr::s2_deframer::info_is_locked(), leansdr::hdlc_sync::output_frame(), leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::receive_frame(), leansdr::hdlc_sync::run(), leansdr::s2_frame_receiver< T, SOFTSYMB >::run(), leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::run(), leansdr::s2_deframer::run(), and leansdr::s2_frame_receiver< T, SOFTSYMB >::run_frame_locked().
 {
     if (p)
         p->write(val);
 }
opt_writer()
template<typename T > pipewriter<T>* leansdr::opt_writer (pipebuf< T > * buf, unsigned long min_write = 1)
Definition at line 329 of file framework.h.
 {
     return buf ? new pipewriter<T>(*buf, min_write) : NULL;
 }
parity() [1/4]
unsigned char leansdr::parity (uint8_t x)
Definition at line 27 of file math.cpp.
Referenced by conjprod(), leansdr::deconvol_sync< leansdr::u8, 0 >::convolve(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::count_edges(), leansdr::bch_engine< T, N, NP, DP, TGF, GFTRUNCGEN >::encode(), leansdr::convol_multipoly< uint16_t, 16 >::encode(), leansdr::trellis< TS, NSTATES, TUS, NUS, NCS >::init_convolutional(), leansdr::deconvol_sync< leansdr::u8, 0 >::inverse_convolution(), parity(), leansdr::deconvol_sync< leansdr::u8, 0 >::readbyte(), leansdr::deconvol_sync< leansdr::u8, 0 >::readerrors(), leansdr::deconvol_poly< Tin, Thist, POLY_DECONVOL, POLY_ERRORS >::run(), leansdr::convol_poly2< Thist, POLY1, POLY2 >::run(), and leansdr::deconvol_sync< leansdr::u8, 0 >::solve_rec().
 {
     x ^= x >> 4;
     return (0x6996 >> (x & 15)) & 1; // 16-entry look-up table
 }
parity() [2/4]
unsigned char leansdr::parity (uint16_t x)
Definition at line 33 of file math.cpp.
References parity().
 {
     return parity((uint8_t)(x ^ (x >> 8)));
 }
parity() [3/4]
unsigned char leansdr::parity (uint32_t x)
Definition at line 38 of file math.cpp.
References parity().
 {
     return parity((uint16_t)(x ^ (x >> 16)));
 }
parity() [4/4]
unsigned char leansdr::parity (uint64_t x)
Definition at line 43 of file math.cpp.
References parity().
 {
     return parity((uint32_t)(x ^ (x >> 32)));
 }
prob()
float leansdr::prob (llr_t l)
Definition at line 79 of file softword.h.
Referenced by llr_xor().
 {
     return (127.0 + l) / 254;
 }
shiftdivmod()
template<typename T , int N, typename Tm > bitvect<T, N> leansdr::shiftdivmod (const Tm * m, size_t nm, const bitvect< T, N > & p, T init = 0)
Definition at line 138 of file discrmath.h.
References i, leansdr::bitvect< T, N >::NW, and leansdr::bitvect< T, N >::v.
Referenced by leansdr::crc8_engine::crc8_engine(), and leansdr::bch_engine< T, N, NP, DP, TGF, GFTRUNCGEN >::encode().
 {
     bitvect<T, N> res;
     for (int i = 0; i < res.NW; ++i)
         res.v[i] = init;
     const Tm bitmask = (Tm)1 << (sizeof(Tm) * 8 - 1);
     for (; nm--; ++m)
     {
         Tm mi = *m;
         for (int bit = sizeof(Tm) * 8; bit--; mi <<= 1)
         {
             // Multiply by X, save outgoing coeff of degree N
             bool resN = res[N - 1];
             res <<= 1;
             // Add m[i]*X^N
             resN ^= (bool)(mi & bitmask);
             // Modulo X^N+p
             if (resN)
                 res += p;
         }
     }
     return res;
 }
softbit_clear() [1/2]
void leansdr::softbit_clear (bool * p) inline
Definition at line 41 of file softword.h.
Referenced by leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::diff_bits(), and leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::integrate_bits().
 { *p = false; }
softbit_clear() [2/2]
void leansdr::softbit_clear (llr_t * p) inline
Definition at line 135 of file softword.h.
 { *p = -127; }
softbit_harden() [1/2]
bool leansdr::softbit_harden (bool b) inline
Definition at line 38 of file softword.h.
Referenced by leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::compute_scores(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::decode_bitflip(), and leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::encode().
 { return b; }
softbit_harden() [2/2]
bool leansdr::softbit_harden (llr_t l) inline
Definition at line 120 of file softword.h.
 { return (l < 0); }
softbit_set() [1/2]
void leansdr::softbit_set (bool * p, bool v) inline
Definition at line 37 of file softword.h.
Referenced by leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::decode_bitflip().
 { *p = v; }
softbit_set() [2/2]
void leansdr::softbit_set (llr_t * p, bool v) inline
Definition at line 119 of file softword.h.
 { *p = v ? -127 : 127; }
softbit_xor() [1/2]
bool leansdr::softbit_xor (bool x, bool y) inline
Definition at line 40 of file softword.h.
Referenced by leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::diff_bits(), and leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::integrate_bits().
 { return x ^ y; }
softbit_xor() [2/2]
llr_t leansdr::softbit_xor (llr_t x, llr_t y) inline
Definition at line 134 of file softword.h.
References llr_xor().
 { return llr_xor(x, y); }
softbyte_harden() [1/2]
uint8_t leansdr::softbyte_harden (const hard_sb & b) inline
Definition at line 39 of file softword.h.
Referenced by softbytes_harden().
 { return b; }
softbyte_harden() [2/2]
uint8_t leansdr::softbyte_harden (const llr_sb & b) inline
Definition at line 121 of file softword.h.
References leansdr::llr_sb::bits.
 {
     // Without conditional jumps
     uint8_t r = (((b.bits[0] & 128) >> 0) |
                  ((b.bits[1] & 128) >> 1) |
                  ((b.bits[2] & 128) >> 2) |
                  ((b.bits[3] & 128) >> 3) |
                  ((b.bits[4] & 128) >> 4) |
                  ((b.bits[5] & 128) >> 5) |
                  ((b.bits[6] & 128) >> 6) |
                  ((b.bits[7] & 128) >> 7));
     return r;
 }
softbytes_harden() [1/2]
uint8_t* leansdr::softbytes_harden (hard_sb p[], int nbytes, uint8_t storage[])
Definition at line 67 of file softword.h.
Referenced by leansdr::s2_fecdec_helper< SOFTBIT, SOFTBYTE >::receive_frame(), and leansdr::s2_fecdec< SOFTBIT, SOFTBYTE >::run().
 {
     return p;
 }
softbytes_harden() [2/2]
uint8_t* leansdr::softbytes_harden (llr_sb p[], int nbytes, uint8_t storage[])
Definition at line 161 of file softword.h.
References softbyte_harden().
 {
     for (uint8_t *q = storage; nbytes--; ++p, ++q)
         *q = softbyte_harden(*p);
     return storage;
 }
softsymb_harden() [1/3]
void leansdr::softsymb_harden (llr_ss * ss)
Definition at line 20 of file sdr.cpp.
References leansdr::llr_ss::bits.
Referenced by leansdr::cstln_lut< SOFTSYMB, 256 >::harden().
 {
     for (int b = 0; b < 8; ++b)
         ss->bits[b] = (ss->bits[b] < 0) ? -127 : 127;
 }
softsymb_harden() [2/3]
void leansdr::softsymb_harden (hard_ss * ss)
Definition at line 26 of file sdr.cpp.
 {
     (void)ss; // NOP
 }
softsymb_harden() [3/3]
void leansdr::softsymb_harden (eucl_ss * ss)
Definition at line 31 of file sdr.cpp.
References leansdr::eucl_ss::dists2, leansdr::eucl_ss::MAX_SYMBOLS, and leansdr::eucl_ss::nearest.
 {
     for (int s = 0; s < ss->MAX_SYMBOLS; ++s)
         ss->dists2[s] = (s == ss->nearest) ? 0 : 1;
 }
softsymb_to_dump() [1/3]
uint8_t leansdr::softsymb_to_dump (const llr_ss & ss, int bit)
Definition at line 38 of file sdr.cpp.
References leansdr::llr_ss::bits.
Referenced by leansdr::cstln_lut< SOFTSYMB, 256 >::dump().
 {
     return 128 - ss.bits[bit];
 }
softsymb_to_dump() [2/3]
uint8_t leansdr::softsymb_to_dump (const hard_ss & ss, int bit)
Definition at line 43 of file sdr.cpp.
 {
     return ((ss >> bit) & 1) ? 255 : 0;
 }
softsymb_to_dump() [3/3]
uint8_t leansdr::softsymb_to_dump (const eucl_ss & ss, int bit)
Definition at line 48 of file sdr.cpp.
References leansdr::eucl_ss::dists2, and leansdr::eucl_ss::nearest.
 {
     (void)bit;
     return ss.dists2[ss.nearest] >> 8;
 }
softword_clear() [1/2]
void leansdr::softword_clear (hard_sb * p) inline
Definition at line 32 of file softword.h.
Referenced by leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deinterleave(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deinterleave4050(), and leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deserialize_qpsk().
 { *p = 0; }
softword_clear() [2/2]
void leansdr::softword_clear (llr_sb * p) inline
Definition at line 111 of file softword.h.
References leansdr::llr_sb::bits.
 {
     memset(p->bits, 0, sizeof(p->bits));
 }
softword_get() [1/2]
bool leansdr::softword_get (const hard_sb & p, int b) inline
Definition at line 23 of file softword.h.
Referenced by leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::count_edges(), leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deinterleave4050(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::diff_bits(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::encode(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::integrate_bits(), and softwords_get().
 {
     return p & (1 << (7 - b));
 }
softword_get() [2/2]
llr_t leansdr::softword_get (const llr_sb & p, int b) inline
Definition at line 98 of file softword.h.
References leansdr::llr_sb::bits.
 {
     return p.bits[b];
 }
softword_set() [1/2]
void leansdr::softword_set (hard_sb * p, int b, bool v) inline
Definition at line 27 of file softword.h.
Referenced by softwords_set().
 {
     hard_sb mask = 1 << (7 - b);
     *p = ((*p) & ~mask) | (v << (7 - b));
 }
softword_set() [2/2]
void leansdr::softword_set (llr_sb * p, int b, llr_t v) inline
Definition at line 107 of file softword.h.
References leansdr::llr_sb::bits.
 {
     p->bits[b] = v;
 }
softword_weight() [1/2]
bool leansdr::softword_weight (const bool & l) inline
Definition at line 33 of file softword.h.
Referenced by softwords_weight().
 {
     return true;
 }
softword_weight() [2/2]
llr_t leansdr::softword_weight (llr_t l) inline
Definition at line 118 of file softword.h.
References abs().
 { return abs(l); }
softword_write() [1/2]
void leansdr::softword_write (hard_sb & p, int b, bool v) inline
Definition at line 54 of file softword.h.
Referenced by leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::diff_bits(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::integrate_bits(), and softwords_write().
 {
     hard_sb mask = 1 << (7 - b);
     p = (p & ~mask) | (hard_sb)v << (7 - b);
 }
softword_write() [2/2]
void leansdr::softword_write (llr_sb & p, int b, llr_t v) inline
Definition at line 148 of file softword.h.
References leansdr::llr_sb::bits.
 {
     p.bits[b] = v;
 }
softword_zero() [1/2]
void leansdr::softword_zero (hard_sb * p) inline
Definition at line 46 of file softword.h.
Referenced by leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::count_edges(), and leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::encode().
 {
     *p = 0;
 }
softword_zero() [2/2]
void leansdr::softword_zero (llr_sb * p) inline
Definition at line 140 of file softword.h.
 {
     memset(p, -127, sizeof(*p));
 }
softwords_flip() [1/2]
void leansdr::softwords_flip (hard_sb p[], int b) inline
Definition at line 63 of file softword.h.
Referenced by leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::count_edges(), leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::decode_bitflip(), and leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::encode().
 {
     p[b / 8] ^= 1 << (7 - (b & 7));
 }
softwords_flip() [2/2]
void leansdr::softwords_flip (llr_sb p[], int b) inline
Definition at line 156 of file softword.h.
References leansdr::llr_sb::bits.
 {
     llr_t *l = &p[b / 8].bits[b & 7];
     *l = -*l;
 }
softwords_get() [1/2]
llr_t leansdr::softwords_get (const llr_sb p[], int b) inline
Definition at line 103 of file softword.h.
References leansdr::llr_sb::bits.
 {
     return p[0].bits[b]; // Beyond bounds on purpose
 }
softwords_get() [2/2]
template<typename SOFTBIT , typename SOFTBYTE > SOFTBIT leansdr::softwords_get (const SOFTBYTE p[], int b) inline
Definition at line 171 of file softword.h.
References softword_get().
 {
     return softword_get(p[b / 8], b & 7);
 }
softwords_set() [1/3]
void leansdr::softwords_set (hard_sb p[], int b) inline
Definition at line 50 of file softword.h.
Referenced by leansdr::s2_deinterleaver< SOFTSYMB, SOFTBYTE >::deinterleave4050().
 {
     p[b / 8] |= 1 << (7 - (b & 7));
 }
softwords_set() [2/3]
void leansdr::softwords_set (llr_sb p[], int b) inline
Definition at line 144 of file softword.h.
References leansdr::llr_sb::bits.
 {
     p[b / 8].bits[b & 7] = 127;
 }
softwords_set() [3/3]
template<typename SOFTBIT , typename SOFTBYTE > void leansdr::softwords_set (SOFTBYTE p[], int b, SOFTBIT v) inline
Definition at line 176 of file softword.h.
References softword_set().
 {
     softword_set(&p[b / 8], b & 7, v);
 }
softwords_weight()
template<typename SOFTBIT , typename SOFTBYTE > SOFTBIT leansdr::softwords_weight (const SOFTBYTE p[], int b) inline
Definition at line 181 of file softword.h.
References softword_weight().
 {
     return softword_weight(softwords_get<SOFTBIT, SOFTBYTE>(p, b));
 }
softwords_write() [1/2]
void leansdr::softwords_write (hard_sb p[], int b, bool v) inline
Definition at line 59 of file softword.h.
References softword_write().
 {
     softword_write(p[b / 8], b & 7, v);
 }
softwords_write() [2/2]
void leansdr::softwords_write (llr_sb p[], int b, llr_t v) inline
Definition at line 152 of file softword.h.
References softword_write().
 {
     softword_write(p[b / 8], b & 7, v);
 }
softwords_xor() [1/2]
bool leansdr::softwords_xor (const hard_sb p1[], const hard_sb p2[], int b) inline
Definition at line 42 of file softword.h.
Referenced by leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::compute_scores(), and leansdr::ldpc_engine< SOFTBIT, SOFTWORD, SWSIZE, Taddr >::decode_bitflip().
 {
     return (p1[b / 8] ^ p2[b / 8]) & (1 << (7 - (b & 7)));
 }
softwords_xor() [2/2]
llr_t leansdr::softwords_xor (const llr_sb p1[], const llr_sb p2[], int b) inline
Definition at line 136 of file softword.h.
References leansdr::llr_sb::bits, and llr_xor().
 {
     return llr_xor(p1[b / 8].bits[b & 7], p2[b / 8].bits[b & 7]);
 }
to_softsymb() [1/3]
void leansdr::to_softsymb (const full_ss * fss, hard_ss * ss)
Definition at line 55 of file sdr.cpp.
References leansdr::full_ss::nearest.
Referenced by leansdr::cstln_lut< SOFTSYMB, 256 >::make_lut_from_symbols().
 {
     *ss = fss->nearest;
 }
to_softsymb() [2/3]
void leansdr::to_softsymb (const full_ss * fss, eucl_ss * ss)
Definition at line 60 of file sdr.cpp.
References leansdr::eucl_ss::discr2, leansdr::full_ss::dists2, leansdr::eucl_ss::dists2, leansdr::eucl_ss::MAX_SYMBOLS, leansdr::full_ss::nearest, and leansdr::eucl_ss::nearest.
 {
     for (int s = 0; s < ss->MAX_SYMBOLS; ++s)
         ss->dists2[s] = fss->dists2[s];
     uint16_t best = 65535, best2 = 65535;
     for (int s = 0; s < ss->MAX_SYMBOLS; ++s)
     {
         if (fss->dists2[s] < best)
         {
             best2 = best;
             best = fss->dists2[s];
         }
         else if (fss->dists2[s] < best2)
         {
             best2 = fss->dists2[s];
         }
     }
     ss->discr2 = best2 - best;
     ss->nearest = fss->nearest;
 }
to_softsymb() [3/3]
void leansdr::to_softsymb (const full_ss * fss, llr_ss * ss)
Definition at line 84 of file sdr.cpp.
References leansdr::llr_ss::bits, and leansdr::full_ss::p.
 {
     for (int b = 0; b < 8; ++b)
     {
         float v = (1.0f - fss->p[b]) / (fss->p[b] + 1e-6);
         int r = logf(v) * 5; // TBD Optimal scaling vs saturation ?
         if (r < -127)
             r = -127;
         if (r > 127)
             r = 127;
         ss->bits[b] = r;
     }
 }
Variable Documentation
cstln_amp
const float leansdr::cstln_amp = 75
Definition at line 404 of file sdr.h.
Referenced by leansdr::cstln_lut< SOFTSYMB, 256 >::make_qam(), leansdr::cstln_lut< SOFTSYMB, 256 >::polar(), leansdr::cstln_lut< SOFTSYMB, 256 >::polar2(), leansdr::cstln_receiver< leansdr::f32, leansdr::eucl_ss >::run(), leansdr::fast_qpsk_receiver< T >::run(), leansdr::s2_frame_receiver< T, SOFTSYMB >::run_frame_locked(), leansdr::s2_frame_transmitter< T >::s2_frame_transmitter(), leansdr::s2_plscodes< T >::s2_plscodes(), leansdr::s2_sof< T >::s2_sof(), leansdr::s2_frame_receiver< T, SOFTSYMB >::track_symbol(), and leansdr::s2_frame_receiver< T, SOFTSYMB >::update_agc().
modcod_infos
const struct leansdr::modcod_info leansdr::modcod_infos[32]
Referenced by check_modcod(), and leansdr::s2_frame_receiver< T, SOFTSYMB >::run_frame_locked().