SDRAngel: FCDProPlusInput Class Reference
FCDProPlusInput Class Reference
#include <fcdproplusinput.h>
Classes
class MsgConfigureFCDProPlus
class MsgFileRecord
class MsgStartStop
Public Member Functions
FCDProPlusInput (DeviceAPI *deviceAPI)
virtual ~FCDProPlusInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
void set_center_freq (double freq)
void set_bias_t (bool on)
void set_lna_gain (bool on)
void set_mixer_gain (bool on)
void set_if_gain (int gain)
void set_rf_filter (int filterIndex)
void set_if_filter (int filterIndex)
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
bool openFCDAudio (const char *filename)
void closeFCDAudio ()
void applySettings (const FCDProPlusSettings &settings, bool force)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const FCDProPlusSettings &settings)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const FCDProPlusSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
hid_device * m_dev
AudioInput m_fcdAudioInput
AudioFifo m_fcdFIFO
QMutex m_mutex
FCDProPlusSettings m_settings
FCDProPlusThread * m_FCDThread
QString m_deviceDescription
bool m_running
FileRecord * m_fileSink
File sink to record device I/Q output.
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 45 of file fcdproplusinput.h.
Constructor & Destructor Documentation
FCDProPlusInput()
FCDProPlusInput::FCDProPlusInput (DeviceAPI * deviceAPI)
Definition at line 42 of file fcdproplusinput.cpp.
References arg().
                                                      :
     m_deviceAPI(deviceAPI),
     m_dev(0),
     m_settings(),
     m_FCDThread(0),
     m_deviceDescription(fcd_traits<ProPlus>::displayedName),
     m_running(false)
 {
     m_fcdFIFO.setSize(20*fcd_traits<ProPlus>::convBufSize);
     openDevice();
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~FCDProPlusInput()
FCDProPlusInput::~FCDProPlusInput () virtual
Definition at line 59 of file fcdproplusinput.cpp.
References closeDevice(), m_deviceAPI, m_fileSink, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::removeAncillarySink(), and stop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
     closeDevice();
 }
Member Function Documentation
applySettings()
void FCDProPlusInput::applySettings (const FCDProPlusSettings & settings, bool force) private
Definition at line 325 of file fcdproplusinput.cpp.
References DeviceSampleSource::calculateDeviceCenterFrequency(), DeviceAPI::configureCorrections(), DeviceAPI::getDeviceEngineInputMessageQueue(), FileRecord::handleMessage(), FCDProPlusSettings::m_biasT, FCDProPlusSettings::m_centerFrequency, FCDProPlusSettings::m_dcBlock, m_dev, m_deviceAPI, m_FCDThread, FCDProPlusSettings::m_fcPos, m_fileSink, FCDProPlusSettings::m_ifFilterIndex, FCDProPlusSettings::m_ifGain, FCDProPlusSettings::m_iqImbalance, FCDProPlusSettings::m_lnaGain, FCDProPlusSettings::m_log2Decim, FCDProPlusSettings::m_LOppmTenths, FCDProPlusSettings::m_mixGain, FCDProPlusSettings::m_reverseAPIAddress, FCDProPlusSettings::m_reverseAPIDeviceIndex, FCDProPlusSettings::m_reverseAPIPort, FCDProPlusSettings::m_rfFilterIndex, m_settings, FCDProPlusSettings::m_transverterDeltaFrequency, FCDProPlusSettings::m_transverterMode, FCDProPlusSettings::m_useReverseAPI, MessageQueue::push(), set_bias_t(), set_center_freq(), set_if_filter(), set_if_gain(), set_lna_gain(), set_mixer_gain(), set_rf_filter(), FCDProPlusThread::setFcPos(), FCDProPlusThread::setLog2Decimation(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     bool forwardChange = false;
     QList<QString> reverseAPIKeys;
     if (force || (m_settings.m_centerFrequency != settings.m_centerFrequency)) {
         reverseAPIKeys.append("centerFrequency");
     }
     if (force || (m_settings.m_transverterMode != settings.m_transverterMode)) {
         reverseAPIKeys.append("transverterMode");
     }
     if (force || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency)) {
         reverseAPIKeys.append("transverterDeltaFrequency");
     }
     if ((m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force) {
         reverseAPIKeys.append("LOppmTenths");
     }
     if (force || (m_settings.m_centerFrequency != settings.m_centerFrequency)
         || (m_settings.m_LOppmTenths != settings.m_LOppmTenths)
         || (m_settings.m_fcPos != settings.m_fcPos)
         || (m_settings.m_log2Decim != settings.m_log2Decim)
         || (m_settings.m_transverterMode != settings.m_transverterMode)
         || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency))
     {
         qint64 deviceCenterFrequency = DeviceSampleSource::calculateDeviceCenterFrequency(
                 settings.m_centerFrequency,
                 settings.m_transverterDeltaFrequency,
                 settings.m_log2Decim,
                 (DeviceSampleSource::fcPos_t) settings.m_fcPos,
                 fcd_traits<ProPlus>::sampleRate,
                 DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD,
                 settings.m_transverterMode);
         if (m_dev != 0) {
             set_center_freq((double) deviceCenterFrequency);
         }
         qDebug() << "FCDProPlusInput::applySettings: center freq: " << settings.m_centerFrequency << " Hz"
                 << " device center freq: " << deviceCenterFrequency << " Hz";
         forwardChange = (m_settings.m_centerFrequency != settings.m_centerFrequency) || force;
         m_settings.m_centerFrequency = settings.m_centerFrequency;
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         reverseAPIKeys.append("log2Decim");
         forwardChange = true;
         if (m_FCDThread != 0)
         {
             m_FCDThread->setLog2Decimation(settings.m_log2Decim);
             qDebug() << "FCDProPlusInput::applySettings: set decimation to " << (1<<settings.m_log2Decim);
         }
     }
     if ((m_settings.m_fcPos != settings.m_fcPos) || force)
     {
         reverseAPIKeys.append("fcPos");
         if (m_FCDThread != 0) {
             m_FCDThread->setFcPos((int) settings.m_fcPos);
         }
         qDebug() << "FCDProPlusInput::applySettings: set fc pos (enum) to " << (int) settings.m_fcPos;
     }
     if ((m_settings.m_lnaGain != settings.m_lnaGain) || force)
     {
         reverseAPIKeys.append("lnaGain");
         if (m_dev != 0) {
             set_lna_gain(settings.m_lnaGain);
         }
     }
     if ((m_settings.m_biasT != settings.m_biasT) || force)
     {
         reverseAPIKeys.append("biasT");
         if (m_dev != 0) {
             set_bias_t(settings.m_biasT);
         }
     }
     if ((m_settings.m_mixGain != settings.m_mixGain) || force)
     {
         reverseAPIKeys.append("mixGain");
         if (m_dev != 0) {
             set_mixer_gain(settings.m_mixGain);
         }
     }
     if ((m_settings.m_ifGain != settings.m_ifGain) || force)
     {
         reverseAPIKeys.append("ifGain");
         if (m_dev != 0) {
             set_if_gain(settings.m_ifGain);
         }
     }
     if ((m_settings.m_ifFilterIndex != settings.m_ifFilterIndex) || force)
     {
         reverseAPIKeys.append("ifFilterIndex");
         if (m_dev != 0) {
             set_if_filter(settings.m_ifFilterIndex);
         }
     }
     if ((m_settings.m_rfFilterIndex != settings.m_rfFilterIndex) || force)
     {
         reverseAPIKeys.append("rfFilterIndex");
         if (m_dev != 0) {
             set_rf_filter(settings.m_rfFilterIndex);
         }
     }
     if ((m_settings.m_dcBlock != settings.m_dcBlock) || force)
     {
         reverseAPIKeys.append("dcBlock");
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqImbalance);
     }
     if ((m_settings.m_iqImbalance != settings.m_iqImbalance) || force)
     {
         reverseAPIKeys.append("iqImbalance");
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqImbalance);
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     if (forwardChange)
     {
         DSPSignalNotification *notif = new DSPSignalNotification(fcd_traits<ProPlus>::sampleRate/(1<<settings.m_log2Decim), m_settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
 }
closeDevice()
void FCDProPlusInput::closeDevice () private
Definition at line 152 of file fcdproplusinput.cpp.
References closeFCDAudio(), fcdClose(), and m_dev.
Referenced by openDevice(), and ~FCDProPlusInput().
 {
     if (m_dev == 0) { // was never open
         return;
     }
     fcdClose(m_dev);
     m_dev = 0;
     closeFCDAudio();
 }
closeFCDAudio()
void FCDProPlusInput::closeFCDAudio () private
Definition at line 187 of file fcdproplusinput.cpp.
References m_fcdAudioInput, m_fcdFIFO, AudioInput::removeFifo(), and AudioInput::stop().
Referenced by closeDevice().
 {
     m_fcdAudioInput.removeFifo(&m_fcdFIFO);
     m_fcdAudioInput.stop();
 }
deserialize()
bool FCDProPlusInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 213 of file fcdproplusinput.cpp.
References FCDProPlusInput::MsgConfigureFCDProPlus::create(), FCDProPlusSettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and FCDProPlusSettings::resetToDefaults().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureFCDProPlus* message = MsgConfigureFCDProPlus::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureFCDProPlus* messageToGUI = MsgConfigureFCDProPlus::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void FCDProPlusInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 74 of file fcdproplusinput.cpp.
 {
     delete this;
 }
getCenterFrequency()
quint64 FCDProPlusInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 245 of file fcdproplusinput.cpp.
References FCDProPlusSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & FCDProPlusInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 235 of file fcdproplusinput.cpp.
References m_deviceDescription.
 {
     return m_deviceDescription;
 }
getSampleRate()
int FCDProPlusInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 240 of file fcdproplusinput.cpp.
References FCDProPlusSettings::m_log2Decim, and m_settings.
 {
     return fcd_traits<ProPlus>::sampleRate/(1<<m_settings.m_log2Decim);
 }
handleMessage()
bool FCDProPlusInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 265 of file fcdproplusinput.cpp.
References applySettings(), FileRecord::genUniqueFileName(), DeviceAPI::getDeviceUID(), FCDProPlusInput::MsgConfigureFCDProPlus::getForce(), FCDProPlusInput::MsgConfigureFCDProPlus::getSettings(), FCDProPlusInput::MsgStartStop::getStartStop(), FCDProPlusInput::MsgFileRecord::getStartStop(), DeviceAPI::initDeviceEngine(), m_deviceAPI, FCDProPlusSettings::m_fileRecordName, m_fileSink, m_settings, FCDProPlusSettings::m_useReverseAPI, Message::match(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
 {
     if(MsgConfigureFCDProPlus::match(message))
     {
         qDebug() << "FCDProPlusInput::handleMessage: MsgConfigureFCD";
         MsgConfigureFCDProPlus& conf = (MsgConfigureFCDProPlus&) message;
         applySettings(conf.getSettings(), conf.getForce());
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "FCDProPlusInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "FCDProPlusInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void FCDProPlusInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 108 of file fcdproplusinput.cpp.
References applySettings(), and m_settings.
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void FCDProPlusInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 820 of file fcdproplusinput.cpp.
Referenced by ~FCDProPlusInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "FCDProPlusInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("FCDProPlusInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openDevice()
bool FCDProPlusInput::openDevice () private
Definition at line 79 of file fcdproplusinput.cpp.
References closeDevice(), fcdOpen(), DeviceAPI::getSamplingDeviceSequence(), m_dev, m_deviceAPI, and openFCDAudio().
 {
     if (m_dev != 0) {
         closeDevice();
     }
     int device = m_deviceAPI->getSamplingDeviceSequence();
     qDebug() << "FCDProPlusInput::openDevice with device #" << device;
     m_dev = fcdOpen(fcd_traits<ProPlus>::vendorId, fcd_traits<ProPlus>::productId, device);
     if (m_dev == 0)
     {
         qCritical("FCDProPlusInput::start: could not open FCD");
         return false;
     }
     if (!openFCDAudio(fcd_traits<ProPlus>::qtDeviceName))
     {
         qCritical("FCDProPlusInput::start: could not open FCD audio source");
         return false;
     }
     else
     {
         qDebug("FCDProPlusInput::start: FCD audio source opened");
     }
     return true;
 }
openFCDAudio()
bool FCDProPlusInput::openFCDAudio (const char * filename) private
Definition at line 164 of file fcdproplusinput.cpp.
References AudioInput::addFifo(), DSPEngine::getAudioDeviceManager(), AudioDeviceManager::getInputDeviceIndex(), AudioDeviceManager::getInputDevices(), AudioInput::getRate(), DSPEngine::instance(), m_fcdAudioInput, m_fcdFIFO, and AudioInput::start().
Referenced by openDevice().
 {
     AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
     const QList<QAudioDeviceInfo>& audioList = audioDeviceManager->getInputDevices();
     for (const auto &itAudio : audioList)
     {
         if (itAudio.deviceName().contains(QString(cardname)))
         {
             int fcdDeviceIndex = audioDeviceManager->getInputDeviceIndex(itAudio.deviceName());
             m_fcdAudioInput.start(fcdDeviceIndex, fcd_traits<ProPlus>::sampleRate);
             int fcdSampleRate = m_fcdAudioInput.getRate();
             qDebug("FCDProPlusInput::openFCDAudio: %s index %d at %d S/s",
                     itAudio.deviceName().toStdString().c_str(), fcdDeviceIndex, fcdSampleRate);
             m_fcdAudioInput.addFifo(&m_fcdFIFO);
             return true;
         }
     }
     qCritical("FCDProPlusInput::openFCDAudio: device with name %s not found", cardname);
     return false;
 }
serialize()
QByteArray FCDProPlusInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 208 of file fcdproplusinput.cpp.
References m_settings, and FCDProPlusSettings::serialize().
 {
     return m_settings.serialize();
 }
set_bias_t()
void FCDProPlusInput::set_bias_t (bool on)
Definition at line 489 of file fcdproplusinput.cpp.
References fcdAppSetParam(), FCDPROPLUS_HID_CMD_SET_BIAS_TEE, and m_dev.
Referenced by applySettings().
 {
     quint8 cmd = on ? 1 : 0;
     fcdAppSetParam(m_dev, FCDPROPLUS_HID_CMD_SET_BIAS_TEE, &cmd, 1);
 }
set_center_freq()
void FCDProPlusInput::set_center_freq (double freq)
Definition at line 479 of file fcdproplusinput.cpp.
References FCD_MODE_NONE, fcdAppSetFreq(), m_dev, FCDProPlusSettings::m_LOppmTenths, and m_settings.
Referenced by applySettings().
 {
     freq += freq*(((double) m_settings.m_LOppmTenths)/10000000.0);
     if (fcdAppSetFreq(m_dev, freq) == FCD_MODE_NONE)
     {
         qDebug("No FCD HID found for frquency change");
     }
 }
set_if_filter()
void FCDProPlusInput::set_if_filter (int filterIndex)
Definition at line 525 of file fcdproplusinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPROPLUS_HID_CMD_SET_IF_FILTER, FCDProPlusConstants::fcdproplus_if_filter_nb_values(), FCDProPlusConstants::if_filters, m_dev, and fcdproplus_if_filter::value.
Referenced by applySettings().
 {
     if ((filterIndex < 0) || (filterIndex >= FCDProPlusConstants::fcdproplus_if_filter_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProPlusConstants::if_filters[filterIndex].value;
     if (fcdAppSetParam(m_dev, FCDPROPLUS_HID_CMD_SET_IF_FILTER, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_if_filter: failed to set at " << cmd_value;
     }
 }
set_if_gain()
void FCDProPlusInput::set_if_gain (int gain)
Definition at line 510 of file fcdproplusinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPROPLUS_HID_CMD_SET_IF_GAIN, and m_dev.
Referenced by applySettings().
 {
     if (gain < 0)
     {
         return;
     }
     quint8 cmd_value = gain;
     if (fcdAppSetParam(m_dev, FCDPROPLUS_HID_CMD_SET_IF_GAIN, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_if_gain: failed to set at " << cmd_value;
     }
 }
set_lna_gain()
void FCDProPlusInput::set_lna_gain (bool on)
Definition at line 496 of file fcdproplusinput.cpp.
References fcdAppSetParam(), FCDPROPLUS_HID_CMD_SET_LNA_GAIN, and m_dev.
Referenced by applySettings().
 {
     quint8 cmd = on ? 1 : 0;
     fcdAppSetParam(m_dev, FCDPROPLUS_HID_CMD_SET_LNA_GAIN, &cmd, 1);
 }
set_mixer_gain()
void FCDProPlusInput::set_mixer_gain (bool on)
Definition at line 503 of file fcdproplusinput.cpp.
References fcdAppSetParam(), FCDPROPLUS_HID_CMD_SET_MIXER_GAIN, and m_dev.
Referenced by applySettings().
 {
     quint8 cmd = on ? 1 : 0;
     fcdAppSetParam(m_dev, FCDPROPLUS_HID_CMD_SET_MIXER_GAIN, &cmd, 1);
 }
set_rf_filter()
void FCDProPlusInput::set_rf_filter (int filterIndex)
Definition at line 541 of file fcdproplusinput.cpp.
References FCD_MODE_APP, fcdAppSetParam(), FCDPROPLUS_HID_CMD_SET_RF_FILTER, FCDProPlusConstants::fcdproplus_rf_filter_nb_values(), m_dev, FCDProPlusConstants::rf_filters, and fcdproplus_rf_filter::value.
Referenced by applySettings().
 {
     if ((filterIndex < 0) || (filterIndex >= FCDProPlusConstants::fcdproplus_rf_filter_nb_values()))
     {
         return;
     }
     quint8 cmd_value = FCDProPlusConstants::rf_filters[filterIndex].value;
     if (fcdAppSetParam(m_dev, FCDPROPLUS_HID_CMD_SET_RF_FILTER, &cmd_value, 1) != FCD_MODE_APP)
     {
         qWarning() << "FCDProPlusInput::set_rf_filter: failed to set at " << cmd_value;
     }
 }
setCenterFrequency()
void FCDProPlusInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 250 of file fcdproplusinput.cpp.
References FCDProPlusInput::MsgConfigureFCDProPlus::create(), FCDProPlusSettings::m_centerFrequency, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
 {
     FCDProPlusSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureFCDProPlus* message = MsgConfigureFCDProPlus::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureFCDProPlus* messageToGUI = MsgConfigureFCDProPlus::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setMessageQueueToGUI()
virtual void FCDProPlusInput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 120 of file fcdproplusinput.h.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void FCDProPlusInput::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 123 of file fcdproplusinput.h.
 { (void) sampleRate; }
start()
bool FCDProPlusInput::start () virtual
Implements DeviceSampleSource.
Definition at line 113 of file fcdproplusinput.cpp.
References applySettings(), m_dev, m_fcdFIFO, m_FCDThread, m_running, DeviceSampleSource::m_sampleFifo, m_settings, SampleSinkFifo::setSize(), FCDProPlusThread::startWork(), and stop().
 {
 //  QMutexLocker mutexLocker(&m_mutex);
     if (!m_dev) {
         return false;
     }
     if (m_running) {
         stop();
     }
     qDebug() << "FCDProPlusInput::start";
     /* Apply settings before streaming to avoid bus contention;
      * there is very little spare bandwidth on a full speed USB device.
      * Failure is harmless if no device is found
      * ... This is rubbish...*/
     //applySettings(m_settings, true);
     if (!m_sampleFifo.setSize(96000*4))
     {
         qCritical("FCDProPlusInput::start: could not allocate SampleFifo");
         return false;
     }
     m_FCDThread = new FCDProPlusThread(&m_sampleFifo, &m_fcdFIFO);
     m_FCDThread->startWork();
 //  mutexLocker.unlock();
     applySettings(m_settings, true);
     qDebug("FCDProPlusInput::started");
     m_running = true;
     return true;
 }
stop()
void FCDProPlusInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 193 of file fcdproplusinput.cpp.
References m_FCDThread, m_mutex, m_running, and FCDProPlusThread::stopWork().
Referenced by start(), and ~FCDProPlusInput().
 {
     QMutexLocker mutexLocker(&m_mutex);
     if (m_FCDThread)
     {
         m_FCDThread->stopWork();
         // wait for thread to quit ?
         delete m_FCDThread;
         m_FCDThread = nullptr;
     }
     m_running = false;
 }
webapiFormatDeviceSettings()
void FCDProPlusInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const FCDProPlusSettings & settings) private
Definition at line 678 of file fcdproplusinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getFcdProPlusSettings(), SWGSDRangel::SWGFCDProPlusSettings::getFileRecordName(), SWGSDRangel::SWGFCDProPlusSettings::getReverseApiAddress(), FCDProPlusSettings::m_biasT, FCDProPlusSettings::m_centerFrequency, FCDProPlusSettings::m_dcBlock, FCDProPlusSettings::m_fcPos, FCDProPlusSettings::m_fileRecordName, FCDProPlusSettings::m_ifFilterIndex, FCDProPlusSettings::m_ifGain, FCDProPlusSettings::m_iqImbalance, FCDProPlusSettings::m_lnaGain, FCDProPlusSettings::m_log2Decim, FCDProPlusSettings::m_LOppmTenths, FCDProPlusSettings::m_mixGain, FCDProPlusSettings::m_rangeLow, FCDProPlusSettings::m_reverseAPIAddress, FCDProPlusSettings::m_reverseAPIDeviceIndex, FCDProPlusSettings::m_reverseAPIPort, FCDProPlusSettings::m_rfFilterIndex, FCDProPlusSettings::m_transverterDeltaFrequency, FCDProPlusSettings::m_transverterMode, FCDProPlusSettings::m_useReverseAPI, SWGSDRangel::SWGFCDProPlusSettings::setBiasT(), SWGSDRangel::SWGFCDProPlusSettings::setCenterFrequency(), SWGSDRangel::SWGFCDProPlusSettings::setDcBlock(), SWGSDRangel::SWGFCDProPlusSettings::setFcPos(), SWGSDRangel::SWGFCDProPlusSettings::setFileRecordName(), SWGSDRangel::SWGFCDProPlusSettings::setIfFilterIndex(), SWGSDRangel::SWGFCDProPlusSettings::setIfGain(), SWGSDRangel::SWGFCDProPlusSettings::setIqImbalance(), SWGSDRangel::SWGFCDProPlusSettings::setLnaGain(), SWGSDRangel::SWGFCDProPlusSettings::setLog2Decim(), SWGSDRangel::SWGFCDProPlusSettings::setLOppmTenths(), SWGSDRangel::SWGFCDProPlusSettings::setMixGain(), SWGSDRangel::SWGFCDProPlusSettings::setRangeLow(), SWGSDRangel::SWGFCDProPlusSettings::setReverseApiAddress(), SWGSDRangel::SWGFCDProPlusSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGFCDProPlusSettings::setReverseApiPort(), SWGSDRangel::SWGFCDProPlusSettings::setRfFilterIndex(), SWGSDRangel::SWGFCDProPlusSettings::setTransverterDeltaFrequency(), SWGSDRangel::SWGFCDProPlusSettings::setTransverterMode(), and SWGSDRangel::SWGFCDProPlusSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getFcdProPlusSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getFcdProPlusSettings()->setLog2Decim(settings.m_log2Decim);
     response.getFcdProPlusSettings()->setFcPos((int) settings.m_fcPos);
     response.getFcdProPlusSettings()->setRangeLow(settings.m_rangeLow ? 1 : 0);
     response.getFcdProPlusSettings()->setLnaGain(settings.m_lnaGain ? 1 : 0);
     response.getFcdProPlusSettings()->setMixGain(settings.m_mixGain ? 1 : 0);
     response.getFcdProPlusSettings()->setBiasT(settings.m_biasT ? 1 : 0);
     response.getFcdProPlusSettings()->setIfGain(settings.m_ifGain);
     response.getFcdProPlusSettings()->setIfFilterIndex(settings.m_ifFilterIndex);
     response.getFcdProPlusSettings()->setRfFilterIndex(settings.m_rfFilterIndex);
     response.getFcdProPlusSettings()->setLOppmTenths(settings.m_LOppmTenths);
     response.getFcdProPlusSettings()->setDcBlock(settings.m_dcBlock ? 1 : 0);
     response.getFcdProPlusSettings()->setIqImbalance(settings.m_iqImbalance ? 1 : 0);
     response.getFcdProPlusSettings()->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     response.getFcdProPlusSettings()->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     if (response.getFcdProPlusSettings()->getFileRecordName()) {
         *response.getFcdProPlusSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getFcdProPlusSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getFcdProPlusSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getFcdProPlusSettings()->getReverseApiAddress()) {
         *response.getFcdProPlusSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getFcdProPlusSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getFcdProPlusSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getFcdProPlusSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReverseSendSettings()
void FCDProPlusInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const FCDProPlusSettings & settings, bool force) private
Definition at line 714 of file fcdproplusinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getFcdProPlusSettings(), FCDProPlusSettings::m_biasT, FCDProPlusSettings::m_centerFrequency, FCDProPlusSettings::m_dcBlock, m_deviceAPI, FCDProPlusSettings::m_fcPos, FCDProPlusSettings::m_fileRecordName, FCDProPlusSettings::m_ifFilterIndex, FCDProPlusSettings::m_ifGain, FCDProPlusSettings::m_iqImbalance, FCDProPlusSettings::m_lnaGain, FCDProPlusSettings::m_log2Decim, FCDProPlusSettings::m_LOppmTenths, FCDProPlusSettings::m_mixGain, m_networkManager, m_networkRequest, FCDProPlusSettings::m_rangeLow, FCDProPlusSettings::m_reverseAPIAddress, FCDProPlusSettings::m_reverseAPIDeviceIndex, FCDProPlusSettings::m_reverseAPIPort, FCDProPlusSettings::m_rfFilterIndex, FCDProPlusSettings::m_transverterDeltaFrequency, FCDProPlusSettings::m_transverterMode, SWGSDRangel::SWGFCDProPlusSettings::setBiasT(), SWGSDRangel::SWGFCDProPlusSettings::setCenterFrequency(), SWGSDRangel::SWGFCDProPlusSettings::setDcBlock(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGDeviceSettings::setFcdProPlusSettings(), SWGSDRangel::SWGFCDProPlusSettings::setFcPos(), SWGSDRangel::SWGFCDProPlusSettings::setFileRecordName(), SWGSDRangel::SWGFCDProPlusSettings::setIfFilterIndex(), SWGSDRangel::SWGFCDProPlusSettings::setIfGain(), SWGSDRangel::SWGFCDProPlusSettings::setIqImbalance(), SWGSDRangel::SWGFCDProPlusSettings::setLnaGain(), SWGSDRangel::SWGFCDProPlusSettings::setLog2Decim(), SWGSDRangel::SWGFCDProPlusSettings::setLOppmTenths(), SWGSDRangel::SWGFCDProPlusSettings::setMixGain(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGFCDProPlusSettings::setRangeLow(), SWGSDRangel::SWGFCDProPlusSettings::setRfFilterIndex(), SWGSDRangel::SWGFCDProPlusSettings::setTransverterDeltaFrequency(), and SWGSDRangel::SWGFCDProPlusSettings::setTransverterMode().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("FCDPro+"));
     swgDeviceSettings->setFcdProPlusSettings(new SWGSDRangel::SWGFCDProPlusSettings());
     SWGSDRangel::SWGFCDProPlusSettings *swgFCDProPlusSettings = swgDeviceSettings->getFcdProPlusSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgFCDProPlusSettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("log2Decim") || force) {
         swgFCDProPlusSettings->setLog2Decim(settings.m_log2Decim);
     }
     if (deviceSettingsKeys.contains("fcPos") || force) {
         swgFCDProPlusSettings->setFcPos((int) settings.m_fcPos);
     }
     if (deviceSettingsKeys.contains("rangeLow") || force) {
         swgFCDProPlusSettings->setRangeLow(settings.m_rangeLow ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("lnaGain") || force) {
         swgFCDProPlusSettings->setLnaGain(settings.m_lnaGain ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("mixGain") || force) {
         swgFCDProPlusSettings->setMixGain(settings.m_mixGain ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("biasT") || force) {
         swgFCDProPlusSettings->setBiasT(settings.m_biasT ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("ifGain") || force) {
         swgFCDProPlusSettings->setIfGain(settings.m_ifGain);
     }
     if (deviceSettingsKeys.contains("ifFilterIndex") || force) {
         swgFCDProPlusSettings->setIfFilterIndex(settings.m_ifFilterIndex);
     }
     if (deviceSettingsKeys.contains("rfFilterIndex") || force) {
         swgFCDProPlusSettings->setRfFilterIndex(settings.m_rfFilterIndex);
     }
     if (deviceSettingsKeys.contains("LOppmTenths") || force) {
         swgFCDProPlusSettings->setLOppmTenths(settings.m_LOppmTenths);
     }
     if (deviceSettingsKeys.contains("dcBlock") || force) {
         swgFCDProPlusSettings->setDcBlock(settings.m_dcBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("iqImbalance") || force) {
         swgFCDProPlusSettings->setIqImbalance(settings.m_iqImbalance ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency") || force) {
         swgFCDProPlusSettings->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     }
     if (deviceSettingsKeys.contains("transverterMode") || force) {
         swgFCDProPlusSettings->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgFCDProPlusSettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void FCDProPlusInput::webapiReverseSendStartStop (bool start) private
Definition at line 792 of file fcdproplusinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, FCDProPlusSettings::m_reverseAPIAddress, FCDProPlusSettings::m_reverseAPIDeviceIndex, FCDProPlusSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("FCDPro+"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int FCDProPlusInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 565 of file fcdproplusinput.cpp.
References FCDProPlusInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int FCDProPlusInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 556 of file fcdproplusinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int FCDProPlusInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 584 of file fcdproplusinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getFcdProPlusSettings(), SWGSDRangel::SWGFCDProPlusSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setFcdProPlusSettings(), and webapiFormatDeviceSettings().
 {
     (void) errorMessage;
     response.setFcdProPlusSettings(new SWGSDRangel::SWGFCDProPlusSettings());
     response.getFcdProPlusSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int FCDProPlusInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 595 of file fcdproplusinput.cpp.
References FCDProPlusInput::MsgConfigureFCDProPlus::create(), SWGSDRangel::SWGFCDProPlusSettings::getBiasT(), SWGSDRangel::SWGFCDProPlusSettings::getCenterFrequency(), SWGSDRangel::SWGFCDProPlusSettings::getDcBlock(), SWGSDRangel::SWGDeviceSettings::getFcdProPlusSettings(), SWGSDRangel::SWGFCDProPlusSettings::getFcPos(), SWGSDRangel::SWGFCDProPlusSettings::getFileRecordName(), SWGSDRangel::SWGFCDProPlusSettings::getIfFilterIndex(), SWGSDRangel::SWGFCDProPlusSettings::getIfGain(), SWGSDRangel::SWGFCDProPlusSettings::getIqImbalance(), SWGSDRangel::SWGFCDProPlusSettings::getLnaGain(), SWGSDRangel::SWGFCDProPlusSettings::getLog2Decim(), SWGSDRangel::SWGFCDProPlusSettings::getLOppmTenths(), SWGSDRangel::SWGFCDProPlusSettings::getMixGain(), SWGSDRangel::SWGFCDProPlusSettings::getRangeLow(), SWGSDRangel::SWGFCDProPlusSettings::getReverseApiAddress(), SWGSDRangel::SWGFCDProPlusSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGFCDProPlusSettings::getReverseApiPort(), SWGSDRangel::SWGFCDProPlusSettings::getRfFilterIndex(), SWGSDRangel::SWGFCDProPlusSettings::getTransverterDeltaFrequency(), SWGSDRangel::SWGFCDProPlusSettings::getTransverterMode(), SWGSDRangel::SWGFCDProPlusSettings::getUseReverseApi(), FCDProPlusSettings::m_biasT, FCDProPlusSettings::m_centerFrequency, FCDProPlusSettings::m_dcBlock, FCDProPlusSettings::m_fcPos, FCDProPlusSettings::m_fileRecordName, DeviceSampleSource::m_guiMessageQueue, FCDProPlusSettings::m_ifFilterIndex, FCDProPlusSettings::m_ifGain, DeviceSampleSource::m_inputMessageQueue, FCDProPlusSettings::m_iqImbalance, FCDProPlusSettings::m_lnaGain, FCDProPlusSettings::m_log2Decim, FCDProPlusSettings::m_LOppmTenths, FCDProPlusSettings::m_mixGain, FCDProPlusSettings::m_rangeLow, FCDProPlusSettings::m_reverseAPIAddress, FCDProPlusSettings::m_reverseAPIDeviceIndex, FCDProPlusSettings::m_reverseAPIPort, FCDProPlusSettings::m_rfFilterIndex, m_settings, FCDProPlusSettings::m_transverterDeltaFrequency, FCDProPlusSettings::m_transverterMode, FCDProPlusSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatDeviceSettings().
 {
     (void) errorMessage;
     FCDProPlusSettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getFcdProPlusSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getFcdProPlusSettings()->getLog2Decim();
     }
     if (deviceSettingsKeys.contains("fcPos")) {
         settings.m_fcPos = (FCDProPlusSettings::fcPos_t) response.getFcdProPlusSettings()->getFcPos();
     }
     if (deviceSettingsKeys.contains("rangeLow")) {
         settings.m_rangeLow = response.getFcdProPlusSettings()->getRangeLow() != 0;
     }
     if (deviceSettingsKeys.contains("lnaGain")) {
         settings.m_lnaGain = response.getFcdProPlusSettings()->getLnaGain() != 0;
     }
     if (deviceSettingsKeys.contains("mixGain")) {
         settings.m_mixGain = response.getFcdProPlusSettings()->getMixGain() != 0;
     }
     if (deviceSettingsKeys.contains("biasT")) {
         settings.m_biasT = response.getFcdProPlusSettings()->getBiasT() != 0;
     }
     if (deviceSettingsKeys.contains("ifGain")) {
         settings.m_ifGain = response.getFcdProPlusSettings()->getIfGain();
     }
     if (deviceSettingsKeys.contains("ifFilterIndex")) {
         settings.m_ifFilterIndex = response.getFcdProPlusSettings()->getIfFilterIndex();
     }
     if (deviceSettingsKeys.contains("rfFilterIndex")) {
         settings.m_rfFilterIndex = response.getFcdProPlusSettings()->getRfFilterIndex();
     }
     if (deviceSettingsKeys.contains("LOppmTenths")) {
         settings.m_LOppmTenths = response.getFcdProPlusSettings()->getLOppmTenths();
     }
     if (deviceSettingsKeys.contains("dcBlock")) {
         settings.m_dcBlock = response.getFcdProPlusSettings()->getDcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("iqImbalance")) {
         settings.m_iqImbalance = response.getFcdProPlusSettings()->getIqImbalance() != 0;
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency")) {
         settings.m_transverterDeltaFrequency = response.getFcdProPlusSettings()->getTransverterDeltaFrequency();
     }
     if (deviceSettingsKeys.contains("transverterMode")) {
         settings.m_transverterMode = response.getFcdProPlusSettings()->getTransverterMode() != 0;
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getFcdProPlusSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getFcdProPlusSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getFcdProPlusSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getFcdProPlusSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getFcdProPlusSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureFCDProPlus *msg = MsgConfigureFCDProPlus::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureFCDProPlus *msgToGUI = MsgConfigureFCDProPlus::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_dev
hid_device* FCDProPlusInput::m_dev private
Definition at line 158 of file fcdproplusinput.h.
Referenced by applySettings(), closeDevice(), openDevice(), set_bias_t(), set_center_freq(), set_if_filter(), set_if_gain(), set_lna_gain(), set_mixer_gain(), set_rf_filter(), and start().
m_deviceAPI
DeviceAPI* FCDProPlusInput::m_deviceAPI private
Definition at line 157 of file fcdproplusinput.h.
Referenced by applySettings(), handleMessage(), openDevice(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~FCDProPlusInput().
m_deviceDescription
QString FCDProPlusInput::m_deviceDescription private
Definition at line 164 of file fcdproplusinput.h.
Referenced by getDeviceDescription().
m_fcdAudioInput
AudioInput FCDProPlusInput::m_fcdAudioInput private
Definition at line 159 of file fcdproplusinput.h.
Referenced by closeFCDAudio(), and openFCDAudio().
m_fcdFIFO
AudioFifo FCDProPlusInput::m_fcdFIFO private
Definition at line 160 of file fcdproplusinput.h.
Referenced by closeFCDAudio(), openFCDAudio(), and start().
m_FCDThread
FCDProPlusThread* FCDProPlusInput::m_FCDThread private
Definition at line 163 of file fcdproplusinput.h.
Referenced by applySettings(), start(), and stop().
m_fileSink
FileRecord* FCDProPlusInput::m_fileSink private
File sink to record device I/Q output.
Definition at line 166 of file fcdproplusinput.h.
Referenced by applySettings(), handleMessage(), and ~FCDProPlusInput().
m_mutex
QMutex FCDProPlusInput::m_mutex private
Definition at line 161 of file fcdproplusinput.h.
Referenced by stop().
m_networkManager
QNetworkAccessManager* FCDProPlusInput::m_networkManager private
Definition at line 167 of file fcdproplusinput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~FCDProPlusInput().
m_networkRequest
QNetworkRequest FCDProPlusInput::m_networkRequest private
Definition at line 168 of file fcdproplusinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool FCDProPlusInput::m_running private
Definition at line 165 of file fcdproplusinput.h.
Referenced by start(), stop(), and ~FCDProPlusInput().
m_settings
FCDProPlusSettings FCDProPlusInput::m_settings private
Definition at line 162 of file fcdproplusinput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), serialize(), set_center_freq(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
The documentation for this class was generated from the following files:
plugins/samplesource/fcdproplus/fcdproplusinput.h
plugins/samplesource/fcdproplus/fcdproplusinput.cpp