SDRAngel: leansdr::filtergen Namespace Reference
leansdr::filtergen Namespace Reference
Functions
void dump_filter (const char *name, int ncoeffs, float *coeffs)
template<typename T >
void normalize_power (int n, T *coeffs, float gain=1)
template<typename T >
void normalize_dcgain (int n, T *coeffs, float gain=1)
template<typename T >
void cancel_dcgain (int n, T *coeffs)
template<typename T >
int lowpass (int order, float Fcut, T **coeffs, float gain=1)
template<typename T >
int root_raised_cosine (int order, float Fs, float rolloff, T **coeffs)
Function Documentation
cancel_dcgain()
template<typename T > void leansdr::filtergen::cancel_dcgain (int n, T * coeffs)
Definition at line 54 of file filtergen.h.
References i.
 {
     float s = 0;
     for (int i = 0; i < n; ++i)
         s = s + coeffs[i];
     for (int i = 0; i < n; ++i)
         coeffs[i] -= s / n;
 }
dump_filter()
void leansdr::filtergen::dump_filter (const char * name, int ncoeffs, float * coeffs)
Definition at line 11 of file filtergen.cpp.
References i.
Referenced by root_raised_cosine().
 {
     fprintf(stderr, "%s = [", name);
     for (int i = 0; i < ncoeffs; ++i)
         fprintf(stderr, "%s %f", (i ? "," : ""), coeffs[i]);
     fprintf(stderr, " ];\n");
 }
lowpass()
template<typename T > int leansdr::filtergen::lowpass (int order, float Fcut, T ** coeffs, float gain = 1)
Definition at line 67 of file filtergen.h.
References cos(), i, M_PI, normalize_dcgain(), sin(), and sinc().
 {
     int ncoeffs = order + 1;
     *coeffs = new T[ncoeffs];
     for (int i = 0; i < ncoeffs; ++i)
     {
         float t = i - (ncoeffs - 1) * 0.5;
         float sinc = 2 * Fcut * (t ? sin(2 * M_PI * Fcut * t) / (2 * M_PI * Fcut * t) : 1);
 #if 0 // Hamming
     float alpha = 25.0/46, beta = 21.0/46;
     float window = alpha - beta*cos(2*M_PI*i/order);
 #else
         float window = 1;
 #endif
         (*coeffs)[i] = sinc * window;
     }
     normalize_dcgain(ncoeffs, *coeffs, gain);
     return ncoeffs;
 }
normalize_dcgain()
template<typename T > void leansdr::filtergen::normalize_dcgain (int n, T * coeffs, float gain = 1)
Definition at line 42 of file filtergen.h.
References i.
Referenced by lowpass(), and root_raised_cosine().
 {
     float s = 0;
     for (int i = 0; i < n; ++i)
         s = s + coeffs[i];
     if (s)
         gain /= s;
     for (int i = 0; i < n; ++i)
         coeffs[i] = coeffs[i] * gain;
 }
normalize_power()
template<typename T > void leansdr::filtergen::normalize_power (int n, T * coeffs, float gain = 1)
Definition at line 30 of file filtergen.h.
References leansdr::gen_sqrt(), and i.
 {
     float s2 = 0;
     for (int i = 0; i < n; ++i)
         s2 = s2 + coeffs[i] * coeffs[i]; // TBD complex
     if (s2)
         gain /= gen_sqrt(s2);
     for (int i = 0; i < n; ++i)
         coeffs[i] = coeffs[i] * gain;
 }
root_raised_cosine()
template<typename T > int leansdr::filtergen::root_raised_cosine (int order, float Fs, float rolloff, T ** coeffs)
Definition at line 91 of file filtergen.h.
References cos(), dump_filter(), i, M_PI, normalize_dcgain(), sin(), and sqrt().
Referenced by DATVDemod::InitDATVFramework(), and DATVDemod::InitDATVS2Framework().
 {
     float B = rolloff, pi = M_PI;
     int ncoeffs = (order + 1) | 1;
     *coeffs = new T[ncoeffs];
     for (int i = 0; i < ncoeffs; ++i)
     {
         int t = i - ncoeffs / 2;
         float c;
         if (t == 0)
             c = sqrt(Fs) * (1 - B + 4 * B / pi);
         else
         {
             float tT = t * Fs;
             float den = pi * tT * (1 - (4 * B * tT) * (4 * B * tT));
             if (!den)
                 c = B * sqrt(Fs / 2) * ((1 + 2 / pi) * sin(pi / (4 * B)) + (1 - 2 / pi) * cos(pi / (4 * B)));
             else
                 c = sqrt(Fs) * (sin(pi * tT * (1 - B)) + 4 * B * tT * cos(pi * tT * (1 + B))) / den;
         }
         (*coeffs)[i] = c;
     }
     normalize_dcgain(ncoeffs, *coeffs);
     return ncoeffs;
 }