SDRAngel: AMMod Class Reference
AMMod Class Reference
#include <ammod.h>
Classes
class MsgConfigureAMMod
class MsgConfigureChannelizer
class MsgConfigureFileSourceName
class MsgConfigureFileSourceSeek
class MsgConfigureFileSourceStreamTiming
class MsgReportFileSourceStreamData
class MsgReportFileSourceStreamTiming
Signals
void levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples)
Public Member Functions
AMMod (DeviceAPI *deviceAPI)
~AMMod ()
virtual void destroy ()
virtual void pull (Sample &sample)
virtual void pullAudio (int nbSamples)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
double getMagSq () const
CWKeyer * getCWKeyer ()
Public Member Functions inherited from BasebandSampleSource
BasebandSampleSource ()
virtual ~BasebandSampleSource ()
void feed (SampleSourceFifo *sampleFifo, int nbSamples)
SampleSourceFifo & getSampleSourceFifo ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
void setDeviceSampleSourceFifo (SampleSourceFifo *deviceSampleFifo)
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channeltx.modam"
static const QString m_channelId ="AMMod"
Private Types
enum RateState { RSInitialFill, RSRunning }
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applyAudioSampleRate (int sampleRate)
void applyFeedbackAudioSampleRate (unsigned int sampleRate)
void processOneSample (Complex &ci)
void applyChannelSettings (int basebandSampleRate, int outputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const AMModSettings &settings, bool force=false)
void pullAF (Real &sample)
void pushFeedback (Real sample)
void calculateLevel (Real &sample)
void modulateSample ()
void openFileStream ()
void seekFileStream (int seekPercentage)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const AMModSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const AMModSettings &settings, bool force)
void webapiReverseSendCWSettings (const CWKeyerSettings &settings)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSource * m_threadedChannelizer
UpChannelizer * m_channelizer
int m_basebandSampleRate
int m_outputSampleRate
int m_inputFrequencyOffset
AMModSettings m_settings
NCO m_carrierNco
NCOF m_toneNco
Complex m_modSample
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
bool m_interpolatorConsumed
Interpolator m_feedbackInterpolator
Real m_feedbackInterpolatorDistance
Real m_feedbackInterpolatorDistanceRemain
bool m_feedbackInterpolatorConsumed
double m_magsq
MovingAverageUtil< double, double, 16 > m_movingAverage
quint32 m_audioSampleRate
AudioVector m_audioBuffer
uint m_audioBufferFill
AudioFifo m_audioFifo
quint32 m_feedbackAudioSampleRate
AudioVector m_feedbackAudioBuffer
uint m_feedbackAudioBufferFill
AudioFifo m_feedbackAudioFifo
SampleVector m_sampleBuffer
QMutex m_settingsMutex
std::ifstream m_ifstream
QString m_fileName
quint64 m_fileSize
raw file size (bytes)
quint32 m_recordLength
record length in seconds computed from file size
int m_sampleRate
quint32 m_levelCalcCount
Real m_peakLevel
Real m_levelSum
CWKeyer m_cwKeyer
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Static Private Attributes
static const int m_levelNbSamples = 480
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSource
void handleInputMessages ()
void handleWriteToFifo (int nbSamples)
void handleWriteToDeviceFifo (int nbSamples)
Protected Member Functions inherited from BasebandSampleSource
void handleWriteToFifo (SampleSourceFifo *sampleFifo, int nbSamples)
Protected Attributes inherited from BasebandSampleSource
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
SampleSourceFifo m_sampleFifo
Internal FIFO for multi-channel processing.
SampleSourceFifo * m_deviceSampleFifo
Reference to the device FIFO for single channel processing.
Detailed Description
Definition at line 47 of file ammod.h.
Member Enumeration Documentation
RateState
enum AMMod::RateState private
Enumerator
RSInitialFill
RSRunning
Definition at line 263 of file ammod.h.
                    {
         RSInitialFill,
         RSRunning
     };
Constructor & Destructor Documentation
AMMod()
AMMod::AMMod (DeviceAPI * deviceAPI)
Definition at line 53 of file ammod.cpp.
References AudioDeviceManager::addAudioSink(), AudioDeviceManager::addAudioSource(), DeviceAPI::addChannelSource(), DeviceAPI::addChannelSourceAPI(), applyChannelSettings(), applyFeedbackAudioSampleRate(), applySettings(), DSPEngine::getAudioDeviceManager(), BasebandSampleSource::getInputMessageQueue(), AudioDeviceManager::getInputSampleRate(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_basebandSampleRate, m_channelId, m_channelizer, m_cwKeyer, m_deviceAPI, m_feedbackAudioBuffer, m_feedbackAudioBufferFill, m_feedbackAudioFifo, m_feedbackAudioSampleRate, m_inputFrequencyOffset, m_magsq, m_networkManager, m_outputSampleRate, m_settings, m_threadedChannelizer, m_toneNco, networkManagerFinished(), CWKeyer::reset(), NCOF::setFreq(), and CWKeyer::setSampleRate().
Referenced by AMMod::MsgReportFileSourceStreamData::MsgReportFileSourceStreamData().
                                  :
     ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSource),
     m_deviceAPI(deviceAPI),
     m_basebandSampleRate(48000),
     m_outputSampleRate(48000),
     m_inputFrequencyOffset(0),
     m_audioFifo(4800),
     m_feedbackAudioFifo(48000),
     m_settingsMutex(QMutex::Recursive),
     m_fileSize(0),
     m_recordLength(0),
     m_sampleRate(48000),
     m_levelCalcCount(0),
     m_peakLevel(0.0f),
     m_levelSum(0.0f)
 {
     setObjectName(m_channelId);
     m_audioBuffer.resize(1<<14);
     m_audioBufferFill = 0;
     m_feedbackAudioBuffer.resize(1<<14);
     m_feedbackAudioBufferFill = 0;
     m_magsq = 0.0;
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSource(&m_audioFifo, getInputMessageQueue());
     m_audioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getInputSampleRate();
     DSPEngine::instance()->getAudioDeviceManager()->addAudioSink(&m_feedbackAudioFifo, getInputMessageQueue());
     m_feedbackAudioSampleRate = DSPEngine::instance()->getAudioDeviceManager()->getOutputSampleRate();
     applyFeedbackAudioSampleRate(m_feedbackAudioSampleRate);
     m_toneNco.setFreq(1000.0, m_audioSampleRate);
     m_cwKeyer.setSampleRate(m_audioSampleRate);
     m_cwKeyer.reset();
     applyChannelSettings(m_basebandSampleRate, m_outputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new UpChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSource(m_channelizer, this);
     m_deviceAPI->addChannelSource(m_threadedChannelizer);
     m_deviceAPI->addChannelSourceAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~AMMod()
AMMod::~AMMod ()
Definition at line 102 of file ammod.cpp.
References DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo, m_channelizer, m_deviceAPI, m_feedbackAudioFifo, m_networkManager, m_threadedChannelizer, networkManagerFinished(), AudioDeviceManager::removeAudioSink(), AudioDeviceManager::removeAudioSource(), DeviceAPI::removeChannelSource(), and DeviceAPI::removeChannelSourceAPI().
Referenced by AMMod::MsgReportFileSourceStreamData::MsgReportFileSourceStreamData().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     m_deviceAPI->removeChannelSourceAPI(this);
     m_deviceAPI->removeChannelSource(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_feedbackAudioFifo);
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSource(&m_audioFifo);
 }
Member Function Documentation
applyAudioSampleRate()
void AMMod::applyAudioSampleRate (int sampleRate) private
Definition at line 480 of file ammod.cpp.
References applyFeedbackAudioSampleRate(), Interpolator::create(), AMMod::MsgConfigureChannelizer::create(), m_audioSampleRate, m_cwKeyer, m_feedbackAudioSampleRate, AMModSettings::m_inputFrequencyOffset, BasebandSampleSource::m_inputMessageQueue, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, m_outputSampleRate, AMModSettings::m_rfBandwidth, m_settings, m_settingsMutex, AMModSettings::m_toneFrequency, m_toneNco, MessageQueue::push(), NCOF::setFreq(), and CWKeyer::setSampleRate().
Referenced by applySettings(), and handleMessage().
 {
     qDebug("AMMod::applyAudioSampleRate: %d", sampleRate);
     MsgConfigureChannelizer* channelConfigMsg = MsgConfigureChannelizer::create(
             sampleRate, m_settings.m_inputFrequencyOffset);
     m_inputMessageQueue.push(channelConfigMsg);
     m_settingsMutex.lock();
     m_interpolatorDistanceRemain = 0;
     m_interpolatorConsumed = false;
     m_interpolatorDistance = (Real) sampleRate / (Real) m_outputSampleRate;
     m_interpolator.create(48, sampleRate, m_settings.m_rfBandwidth / 2.2, 3.0);
     m_toneNco.setFreq(m_settings.m_toneFrequency, sampleRate);
     m_cwKeyer.setSampleRate(sampleRate);
     m_settingsMutex.unlock();
     m_audioSampleRate = sampleRate;
     applyFeedbackAudioSampleRate(m_feedbackAudioSampleRate);
 }
applyChannelSettings()
void AMMod::applyChannelSettings (int basebandSampleRate, int outputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 520 of file ammod.cpp.
References Interpolator::create(), m_audioSampleRate, m_basebandSampleRate, m_carrierNco, m_inputFrequencyOffset, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, m_outputSampleRate, AMModSettings::m_rfBandwidth, m_settings, m_settingsMutex, and NCO::setFreq().
Referenced by AMMod(), handleMessage(), and start().
 {
     qDebug() << "AMMod::applyChannelSettings:"
             << " basebandSampleRate: " << basebandSampleRate
             << " outputSampleRate: " << outputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if ((inputFrequencyOffset != m_inputFrequencyOffset) ||
         (outputSampleRate != m_outputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_carrierNco.setFreq(inputFrequencyOffset, outputSampleRate);
         m_settingsMutex.unlock();
     }
     if ((outputSampleRate != m_outputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_interpolatorDistanceRemain = 0;
         m_interpolatorConsumed = false;
         m_interpolatorDistance = (Real) m_audioSampleRate / (Real) outputSampleRate;
         m_interpolator.create(48, m_audioSampleRate, m_settings.m_rfBandwidth / 2.2, 3.0);
         m_settingsMutex.unlock();
     }
     m_basebandSampleRate = basebandSampleRate;
     m_outputSampleRate = outputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applyFeedbackAudioSampleRate()
void AMMod::applyFeedbackAudioSampleRate (unsigned int sampleRate) private
Definition at line 503 of file ammod.cpp.
References Interpolator::create(), m_audioSampleRate, m_feedbackAudioSampleRate, m_feedbackInterpolator, m_feedbackInterpolatorConsumed, m_feedbackInterpolatorDistance, m_feedbackInterpolatorDistanceRemain, m_settingsMutex, and leansdr::min().
Referenced by AMMod(), applyAudioSampleRate(), applySettings(), and handleMessage().
 {
     qDebug("AMMod::applyFeedbackAudioSampleRate: %u", sampleRate);
     m_settingsMutex.lock();
     m_feedbackInterpolatorDistanceRemain = 0;
     m_feedbackInterpolatorConsumed = false;
     m_feedbackInterpolatorDistance = (Real) sampleRate / (Real) m_audioSampleRate;
     Real cutoff = std::min(sampleRate, m_audioSampleRate) / 2.2f;
     m_feedbackInterpolator.create(48, sampleRate, cutoff, 3.0);
     m_settingsMutex.unlock();
     m_feedbackAudioSampleRate = sampleRate;
 }
applySettings()
void AMMod::applySettings (const AMModSettings & settings, bool force = false) private
Definition at line 550 of file ammod.cpp.
References AudioDeviceManager::addAudioSink(), AudioDeviceManager::addAudioSource(), applyAudioSampleRate(), applyFeedbackAudioSampleRate(), Interpolator::create(), DSPEngine::getAudioDeviceManager(), AudioDeviceManager::getInputDeviceIndex(), BasebandSampleSource::getInputMessageQueue(), AudioDeviceManager::getInputSampleRate(), AudioDeviceManager::getOutputDeviceIndex(), AudioDeviceManager::getOutputSampleRate(), DSPEngine::instance(), AMModSettings::m_audioDeviceName, m_audioFifo, m_audioSampleRate, AMModSettings::m_channelMute, AMModSettings::m_feedbackAudioDeviceName, m_feedbackAudioFifo, m_feedbackAudioSampleRate, AMModSettings::m_inputFrequencyOffset, m_interpolator, m_interpolatorConsumed, m_interpolatorDistance, m_interpolatorDistanceRemain, AMModSettings::m_modAFInput, AMModSettings::m_modFactor, m_outputSampleRate, AMModSettings::m_playLoop, AMModSettings::m_reverseAPIAddress, AMModSettings::m_reverseAPIChannelIndex, AMModSettings::m_reverseAPIDeviceIndex, AMModSettings::m_reverseAPIPort, AMModSettings::m_rfBandwidth, m_settings, m_settingsMutex, AMModSettings::m_toneFrequency, m_toneNco, AMModSettings::m_useReverseAPI, AMModSettings::m_volumeFactor, NCOF::setFreq(), and webapiReverseSendSettings().
Referenced by AMMod(), and handleMessage().
 {
     qDebug() << "AMMod::applySettings:"
             << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
             << " m_rfBandwidth: " << settings.m_rfBandwidth
             << " m_modFactor: " << settings.m_modFactor
             << " m_toneFrequency: " << settings.m_toneFrequency
             << " m_volumeFactor: " << settings.m_volumeFactor
             << " m_channelMute: " << settings.m_channelMute
             << " m_playLoop: " << settings.m_playLoop
             << " m_modAFInput " << settings.m_modAFInput
             << " m_audioDeviceName: " << settings.m_audioDeviceName
             << " m_useReverseAPI: " << settings.m_useReverseAPI
             << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
             << " m_reverseAPIAddress: " << settings.m_reverseAPIPort
             << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex
             << " m_reverseAPIChannelIndex: " << settings.m_reverseAPIChannelIndex
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if ((settings.m_inputFrequencyOffset != m_settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if ((settings.m_modFactor != m_settings.m_modFactor) || force) {
         reverseAPIKeys.append("modFactor");
     }
     if ((settings.m_volumeFactor != m_settings.m_volumeFactor) || force) {
         reverseAPIKeys.append("volumeFactor");
     }
     if ((settings.m_channelMute != m_settings.m_channelMute) || force) {
         reverseAPIKeys.append("channelMute");
     }
     if ((settings.m_playLoop != m_settings.m_playLoop) || force) {
         reverseAPIKeys.append("playLoop");
     }
     if ((settings.m_modAFInput != m_settings.m_modAFInput) || force) {
         reverseAPIKeys.append("modAFInput");
     }
     if ((settings.m_rfBandwidth != m_settings.m_rfBandwidth) || force)
     {
         reverseAPIKeys.append("rfBandwidth");
         m_settingsMutex.lock();
         m_interpolatorDistanceRemain = 0;
         m_interpolatorConsumed = false;
         m_interpolatorDistance = (Real) m_audioSampleRate / (Real) m_outputSampleRate;
         m_interpolator.create(48, m_audioSampleRate, settings.m_rfBandwidth / 2.2, 3.0);
         m_settingsMutex.unlock();
     }
     if ((settings.m_toneFrequency != m_settings.m_toneFrequency) || force)
     {
         reverseAPIKeys.append("toneFrequency");
         m_settingsMutex.lock();
         m_toneNco.setFreq(settings.m_toneFrequency, m_audioSampleRate);
         m_settingsMutex.unlock();
     }
     if ((settings.m_audioDeviceName != m_settings.m_audioDeviceName) || force)
     {
         reverseAPIKeys.append("audioDeviceName");
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getInputDeviceIndex(settings.m_audioDeviceName);
         audioDeviceManager->addAudioSource(&m_audioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getInputSampleRate(audioDeviceIndex);
         if (m_audioSampleRate != audioSampleRate) {
             reverseAPIKeys.append("audioSampleRate");
             applyAudioSampleRate(audioSampleRate);
         }
     }
     if ((settings.m_feedbackAudioDeviceName != m_settings.m_feedbackAudioDeviceName) || force)
     {
         reverseAPIKeys.append("feedbackAudioDeviceName");
         AudioDeviceManager *audioDeviceManager = DSPEngine::instance()->getAudioDeviceManager();
         int audioDeviceIndex = audioDeviceManager->getOutputDeviceIndex(settings.m_feedbackAudioDeviceName);
         audioDeviceManager->addAudioSink(&m_feedbackAudioFifo, getInputMessageQueue(), audioDeviceIndex);
         uint32_t audioSampleRate = audioDeviceManager->getOutputSampleRate(audioDeviceIndex);
         if (m_feedbackAudioSampleRate != audioSampleRate) {
             reverseAPIKeys.append("feedbackAudioSampleRate");
             applyFeedbackAudioSampleRate(audioSampleRate);
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
calculateLevel()
void AMMod::calculateLevel (Real & sample) private
Definition at line 301 of file ammod.cpp.
References levelChanged(), m_levelCalcCount, m_levelNbSamples, m_levelSum, m_peakLevel, leansdr::max(), and sqrt().
Referenced by modulateSample().
 {
     if (m_levelCalcCount < m_levelNbSamples)
     {
         m_peakLevel = std::max(std::fabs(m_peakLevel), sample);
         m_levelSum += sample * sample;
         m_levelCalcCount++;
     }
     else
     {
         qreal rmsLevel = sqrt(m_levelSum / m_levelNbSamples);
         //qDebug("NFMMod::calculateLevel: %f %f", rmsLevel, m_peakLevel);
         emit levelChanged(rmsLevel, m_peakLevel, m_levelNbSamples);
         m_peakLevel = 0.0f;
         m_levelSum = 0.0f;
         m_levelCalcCount = 0;
     }
 }
deserialize()
bool AMMod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 660 of file ammod.cpp.
References AMMod::MsgConfigureAMMod::create(), AMModSettings::deserialize(), BasebandSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and AMModSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureAMMod *msg = MsgConfigureAMMod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureAMMod *msg = MsgConfigureAMMod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void AMMod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 206 of file ammod.h.
References handleMessage(), pull(), pullAudio(), start(), and stop().
 { delete this; }
getCenterFrequency()
virtual qint64 AMMod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 216 of file ammod.h.
References deserialize(), AMModSettings::m_inputFrequencyOffset, AMMod::MsgConfigureAMMod::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getCWKeyer()
CWKeyer* AMMod::getCWKeyer () inline
Definition at line 247 of file ammod.h.
References m_cwKeyer.
Referenced by AMModGUI::AMModGUI().
 { return &m_cwKeyer; }
getIdentifier()
virtual void AMMod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 214 of file ammod.h.
 { id = objectName(); }
getMagSq()
double AMMod::getMagSq () const inline
Definition at line 245 of file ammod.h.
References m_magsq.
Referenced by AMModGUI::tick(), and webapiFormatChannelReport().
 { return m_magsq; }
getNbSinkStreams()
virtual int AMMod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 221 of file ammod.h.
 { return 1; }
getNbSourceStreams()
virtual int AMMod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 222 of file ammod.h.
 { return 0; }
getStreamCenterFrequency()
virtual qint64 AMMod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 224 of file ammod.h.
References AMModSettings::m_inputFrequencyOffset, AMMod::MsgConfigureAMMod::m_settings, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void AMMod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 215 of file ammod.h.
References AMMod::MsgConfigureAMMod::m_settings, and AMModSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool AMMod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSource.
Definition at line 333 of file ammod.cpp.
References applyAudioSampleRate(), applyChannelSettings(), applyFeedbackAudioSampleRate(), applySettings(), DSPConfigureAudio::AudioInput, DSPConfigureAudio::AudioOutput, UpChannelizer::configure(), AMMod::MsgReportFileSourceStreamTiming::create(), DSPConfigureAudio::getAudioType(), UpChannelizer::MsgChannelizerNotification::getBasebandSampleRate(), AMMod::MsgConfigureChannelizer::getCenterFrequency(), AMMod::MsgConfigureFileSourceName::getFileName(), AMMod::MsgConfigureAMMod::getForce(), UpChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSource::getInputMessageQueue(), BasebandSampleSource::getMessageQueueToGUI(), AMMod::MsgConfigureFileSourceSeek::getPercentage(), UpChannelizer::MsgChannelizerNotification::getSampleRate(), AMMod::MsgConfigureChannelizer::getSampleRate(), DSPConfigureAudio::getSampleRate(), AMMod::MsgConfigureAMMod::getSettings(), CWKeyer::MsgConfigureCWKeyer::getSettings(), m_audioSampleRate, m_channelizer, m_fileName, m_fileSize, m_ifstream, m_settings, AMModSettings::m_useReverseAPI, Message::match(), openFileStream(), MessageQueue::push(), seekFileStream(), and webapiReverseSendCWSettings().
Referenced by destroy().
 {
     if (UpChannelizer::MsgChannelizerNotification::match(cmd))
     {
         UpChannelizer::MsgChannelizerNotification& notif = (UpChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "AMMod::handleMessage: MsgChannelizerNotification:"
                 << " basebandSampleRate: " << notif.getBasebandSampleRate()
                 << " outputSampleRate: " << notif.getSampleRate()
                 << " inputFrequencyOffset: " << notif.getFrequencyOffset();
         applyChannelSettings(notif.getBasebandSampleRate(), notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "AMMod::handleMessage: MsgConfigureChannelizer:"
                 << " getSampleRate: " << cfg.getSampleRate()
                 << " getCenterFrequency: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureAMMod::match(cmd))
     {
         MsgConfigureAMMod& cfg = (MsgConfigureAMMod&) cmd;
         qDebug() << "AMMod::handleMessage: MsgConfigureAMMod";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgConfigureFileSourceName::match(cmd))
     {
         MsgConfigureFileSourceName& conf = (MsgConfigureFileSourceName&) cmd;
         m_fileName = conf.getFileName();
         openFileStream();
         return true;
     }
     else if (MsgConfigureFileSourceSeek::match(cmd))
     {
         MsgConfigureFileSourceSeek& conf = (MsgConfigureFileSourceSeek&) cmd;
         int seekPercentage = conf.getPercentage();
         seekFileStream(seekPercentage);
         return true;
     }
     else if (MsgConfigureFileSourceStreamTiming::match(cmd))
     {
         std::size_t samplesCount;
         if (m_ifstream.eof()) {
             samplesCount = m_fileSize / sizeof(Real);
         } else {
             samplesCount = m_ifstream.tellg() / sizeof(Real);
         }
         MsgReportFileSourceStreamTiming *report;
         report = MsgReportFileSourceStreamTiming::create(samplesCount);
         getMessageQueueToGUI()->push(report);
         return true;
     }
     else if (CWKeyer::MsgConfigureCWKeyer::match(cmd))
     {
         const CWKeyer::MsgConfigureCWKeyer& cfg = (CWKeyer::MsgConfigureCWKeyer&) cmd;
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendCWSettings(cfg.getSettings());
         }
         return true;
     }
     else if (DSPConfigureAudio::match(cmd))
     {
         DSPConfigureAudio& cfg = (DSPConfigureAudio&) cmd;
         uint32_t sampleRate = cfg.getSampleRate();
         DSPConfigureAudio::AudioType audioType = cfg.getAudioType();
         qDebug() << "AMMod::handleMessage: DSPConfigureAudio:"
                 << " sampleRate: " << sampleRate
                 << " audioType: " << audioType;
         if (audioType == DSPConfigureAudio::AudioInput)
         {
             if (sampleRate != m_audioSampleRate) {
                 applyAudioSampleRate(sampleRate);
             }
         }
         else if (audioType == DSPConfigureAudio::AudioOutput)
         {
             if (sampleRate != m_audioSampleRate) {
                 applyFeedbackAudioSampleRate(sampleRate);
             }
         }
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         return false;
     }
 }
levelChanged
void AMMod::levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples) signal
Level changed
Parameters
rmsLevel RMS level in range 0.0 - 1.0
peakLevel Peak level in range 0.0 - 1.0
numSamples Number of audio samples analyzed
Referenced by calculateLevel().
modulateSample()
void AMMod::modulateSample () private
Definition at line 173 of file ammod.cpp.
References calculateLevel(), m_audioBufferFill, AMModSettings::m_feedbackAudioEnable, AMModSettings::m_feedbackVolumeFactor, AMModSettings::m_modFactor, m_modSample, m_settings, pullAF(), and pushFeedback().
Referenced by pull().
 {
     Real t;
     pullAF(t);
     if (m_settings.m_feedbackAudioEnable) {
         pushFeedback(t * m_settings.m_feedbackVolumeFactor * 16384.0f);
     }
     calculateLevel(t);
     m_audioBufferFill++;
     m_modSample.real((t*m_settings.m_modFactor + 1.0f) * 16384.0f); // modulate and scale zero frequency carrier
     m_modSample.imag(0.0f);
 }
networkManagerFinished
void AMMod::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 954 of file ammod.cpp.
Referenced by AMMod(), and ~AMMod().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "AMMod::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("AMMod::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openFileStream()
void AMMod::openFileStream () private
Definition at line 445 of file ammod.cpp.
References AMMod::MsgReportFileSourceStreamData::create(), BasebandSampleSource::getMessageQueueToGUI(), m_fileName, m_fileSize, m_ifstream, m_recordLength, m_sampleRate, and MessageQueue::push().
Referenced by handleMessage().
 {
     if (m_ifstream.is_open()) {
         m_ifstream.close();
     }
     m_ifstream.open(m_fileName.toStdString().c_str(), std::ios::binary | std::ios::ate);
     m_fileSize = m_ifstream.tellg();
     m_ifstream.seekg(0,std::ios_base::beg);
     m_sampleRate = 48000; // fixed rate
     m_recordLength = m_fileSize / (sizeof(Real) * m_sampleRate);
     qDebug() << "AMMod::openFileStream: " << m_fileName.toStdString().c_str()
             << " fileSize: " << m_fileSize << "bytes"
             << " length: " << m_recordLength << " seconds";
     MsgReportFileSourceStreamData *report;
     report = MsgReportFileSourceStreamData::create(m_sampleRate, m_recordLength);
     getMessageQueueToGUI()->push(report);
 }
processOneSample()
void AMMod::processOneSample (Complex & ci) private
Definition at line 280 of file ammod.cpp.
References AudioFifo::clear(), m_feedbackAudioBuffer, m_feedbackAudioBufferFill, m_feedbackAudioFifo, m_feedbackInterpolatorDistance, and AudioFifo::write().
Referenced by pushFeedback().
 {
     m_feedbackAudioBuffer[m_feedbackAudioBufferFill].l = ci.real();
     m_feedbackAudioBuffer[m_feedbackAudioBufferFill].r = ci.imag();
     ++m_feedbackAudioBufferFill;
     if (m_feedbackAudioBufferFill >= m_feedbackAudioBuffer.size())
     {
         uint res = m_feedbackAudioFifo.write((const quint8*)&m_feedbackAudioBuffer[0], m_feedbackAudioBufferFill);
         if (res != m_feedbackAudioBufferFill)
         {
             qDebug("AMDemod::pushFeedback: %u/%u audio samples written m_feedbackInterpolatorDistance: %f",
                 res, m_feedbackAudioBufferFill, m_feedbackInterpolatorDistance);
             m_feedbackAudioFifo.clear();
         }
         m_feedbackAudioBufferFill = 0;
     }
 }
pull()
void AMMod::pull (Sample & sample) virtual
Implements BasebandSampleSource.
Definition at line 114 of file ammod.cpp.
References MovingAverageUtil< T, Total, N >::asDouble(), Interpolator::decimate(), Interpolator::interpolate(), m_carrierNco, AMModSettings::m_channelMute, Sample::m_imag, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_magsq, m_modSample, m_movingAverage, Sample::m_real, m_settings, m_settingsMutex, modulateSample(), NCO::nextIQ(), and SDR_TX_SCALED.
Referenced by destroy().
 {
     if (m_settings.m_channelMute)
     {
         sample.m_real = 0.0f;
         sample.m_imag = 0.0f;
         return;
     }
     Complex ci;
     m_settingsMutex.lock();
     if (m_interpolatorDistance > 1.0f) // decimate
     {
         modulateSample();
         while (!m_interpolator.decimate(&m_interpolatorDistanceRemain, m_modSample, &ci))
         {
             modulateSample();
         }
     }
     else
     {
         if (m_interpolator.interpolate(&m_interpolatorDistanceRemain, m_modSample, &ci))
         {
             modulateSample();
         }
     }
     m_interpolatorDistanceRemain += m_interpolatorDistance;
     ci *= m_carrierNco.nextIQ(); // shift to carrier frequency
     m_settingsMutex.unlock();
     double magsq = ci.real() * ci.real() + ci.imag() * ci.imag();
     magsq /= (SDR_TX_SCALED*SDR_TX_SCALED);
     m_movingAverage(magsq);
     m_magsq = m_movingAverage.asDouble();
     sample.m_real = (FixReal) ci.real();
     sample.m_imag = (FixReal) ci.imag();
 }
pullAF()
void AMMod::pullAF (Real & sample) private
Definition at line 190 of file ammod.cpp.
References AMModSettings::AMModInputAudio, AMModSettings::AMModInputCWTone, AMModSettings::AMModInputFile, AMModSettings::AMModInputNone, AMModSettings::AMModInputTone, CWKeyer::getCWSmoother(), CWSmoother::getFadeSample(), CWKeyer::getSample(), m_audioBuffer, m_audioBufferFill, m_cwKeyer, m_ifstream, AMModSettings::m_modAFInput, AMModSettings::m_playLoop, m_settings, m_toneNco, AMModSettings::m_volumeFactor, NCOF::next(), and NCOF::setPhase().
Referenced by modulateSample().
 {
     switch (m_settings.m_modAFInput)
     {
     case AMModSettings::AMModInputTone:
         sample = m_toneNco.next();
         break;
     case AMModSettings::AMModInputFile:
         // sox f4exb_call.wav --encoding float --endian little f4exb_call.raw
         // ffplay -f f32le -ar 48k -ac 1 f4exb_call.raw
         if (m_ifstream.is_open())
         {
             if (m_ifstream.eof())
             {
                 if (m_settings.m_playLoop)
                 {
                     m_ifstream.clear();
                     m_ifstream.seekg(0, std::ios::beg);
                 }
             }
             if (m_ifstream.eof())
             {
                 sample = 0.0f;
             }
             else
             {
                 m_ifstream.read(reinterpret_cast<char*>(&sample), sizeof(Real));
                 sample *= m_settings.m_volumeFactor;
             }
         }
         else
         {
             sample = 0.0f;
         }
         break;
     case AMModSettings::AMModInputAudio:
         sample = ((m_audioBuffer[m_audioBufferFill].l + m_audioBuffer[m_audioBufferFill].r) / 65536.0f) * m_settings.m_volumeFactor;
         break;
     case AMModSettings::AMModInputCWTone:
         Real fadeFactor;
         if (m_cwKeyer.getSample())
         {
             m_cwKeyer.getCWSmoother().getFadeSample(true, fadeFactor);
             sample = m_toneNco.next() * fadeFactor;
         }
         else
         {
             if (m_cwKeyer.getCWSmoother().getFadeSample(false, fadeFactor))
             {
                 sample = m_toneNco.next() * fadeFactor;
             }
             else
             {
                 sample = 0.0f;
                 m_toneNco.setPhase(0);
             }
         }
         break;
     case AMModSettings::AMModInputNone:
     default:
         sample = 0.0f;
         break;
     }
 }
pullAudio()
void AMMod::pullAudio (int nbSamples) virtual
Reimplemented from BasebandSampleSource.
Definition at line 159 of file ammod.cpp.
References m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSampleRate, m_basebandSampleRate, and AudioFifo::read().
Referenced by destroy().
 {
 //    qDebug("AMMod::pullAudio: %d", nbSamples);
     unsigned int nbAudioSamples = nbSamples * ((Real) m_audioSampleRate / (Real) m_basebandSampleRate);
     if (nbAudioSamples > m_audioBuffer.size())
     {
         m_audioBuffer.resize(nbAudioSamples);
     }
     m_audioFifo.read(reinterpret_cast<quint8*>(&m_audioBuffer[0]), nbAudioSamples);
     m_audioBufferFill = 0;
 }
pushFeedback()
void AMMod::pushFeedback (Real sample) private
Definition at line 257 of file ammod.cpp.
References Interpolator::decimate(), Interpolator::interpolate(), m_feedbackInterpolator, m_feedbackInterpolatorDistance, m_feedbackInterpolatorDistanceRemain, and processOneSample().
Referenced by modulateSample().
 {
     Complex c(sample, sample);
     Complex ci;
     if (m_feedbackInterpolatorDistance < 1.0f) // interpolate
     {
         while (!m_feedbackInterpolator.interpolate(&m_feedbackInterpolatorDistanceRemain, c, &ci))
         {
             processOneSample(ci);
             m_feedbackInterpolatorDistanceRemain += m_feedbackInterpolatorDistance;
         }
     }
     else // decimate
     {
         if (m_feedbackInterpolator.decimate(&m_feedbackInterpolatorDistanceRemain, c, &ci))
         {
             processOneSample(ci);
             m_feedbackInterpolatorDistanceRemain += m_feedbackInterpolatorDistance;
         }
     }
 }
seekFileStream()
void AMMod::seekFileStream (int seekPercentage) private
Definition at line 467 of file ammod.cpp.
References m_ifstream, m_recordLength, m_sampleRate, and m_settingsMutex.
Referenced by handleMessage().
 {
     QMutexLocker mutexLocker(&m_settingsMutex);
     if (m_ifstream.is_open())
     {
         int seekPoint = ((m_recordLength * seekPercentage) / 100) * m_sampleRate;
         seekPoint *= sizeof(Real);
         m_ifstream.clear();
         m_ifstream.seekg(seekPoint, std::ios::beg);
     }
 }
serialize()
QByteArray AMMod::serialize () const virtual
Implements ChannelAPI.
Definition at line 655 of file ammod.cpp.
References m_settings, and AMModSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
start()
void AMMod::start () virtual
Implements BasebandSampleSource.
Definition at line 320 of file ammod.cpp.
References applyChannelSettings(), AudioFifo::clear(), m_audioFifo, m_basebandSampleRate, AMModSettings::m_inputFrequencyOffset, m_inputFrequencyOffset, m_outputSampleRate, and m_settings.
Referenced by destroy().
 {
     qDebug() << "AMMod::start: m_outputSampleRate: " << m_outputSampleRate
             << " m_inputFrequencyOffset: " << m_settings.m_inputFrequencyOffset;
     m_audioFifo.clear();
     applyChannelSettings(m_basebandSampleRate, m_outputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void AMMod::stop () virtual
Implements BasebandSampleSource.
Definition at line 329 of file ammod.cpp.
Referenced by destroy().
 {
 }
webapiFormatChannelReport()
void AMMod::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) private
Definition at line 843 of file ammod.cpp.
References CalcDb::dbPower(), SWGSDRangel::SWGChannelReport::getAmModReport(), getMagSq(), m_audioSampleRate, m_outputSampleRate, SWGSDRangel::SWGAMModReport::setAudioSampleRate(), SWGSDRangel::SWGAMModReport::setChannelPowerDb(), and SWGSDRangel::SWGAMModReport::setChannelSampleRate().
Referenced by webapiReportGet().
 {
     response.getAmModReport()->setChannelPowerDb(CalcDb::dbPower(getMagSq()));
     response.getAmModReport()->setAudioSampleRate(m_audioSampleRate);
     response.getAmModReport()->setChannelSampleRate(m_outputSampleRate);
 }
webapiFormatChannelSettings()
void AMMod::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const AMModSettings & settings) private
Definition at line 797 of file ammod.cpp.
References SWGSDRangel::SWGChannelSettings::getAmModSettings(), SWGSDRangel::SWGAMModSettings::getAudioDeviceName(), SWGSDRangel::SWGAMModSettings::getCwKeyer(), SWGSDRangel::SWGAMModSettings::getReverseApiAddress(), CWKeyer::getSettings(), SWGSDRangel::SWGAMModSettings::getTitle(), AMModSettings::m_audioDeviceName, AMModSettings::m_channelMute, m_cwKeyer, AMModSettings::m_inputFrequencyOffset, AMModSettings::m_modAFInput, AMModSettings::m_modFactor, AMModSettings::m_playLoop, AMModSettings::m_reverseAPIAddress, AMModSettings::m_reverseAPIChannelIndex, AMModSettings::m_reverseAPIDeviceIndex, AMModSettings::m_reverseAPIPort, AMModSettings::m_rfBandwidth, AMModSettings::m_rgbColor, AMModSettings::m_title, AMModSettings::m_toneFrequency, AMModSettings::m_useReverseAPI, AMModSettings::m_volumeFactor, SWGSDRangel::SWGAMModSettings::setAudioDeviceName(), SWGSDRangel::SWGAMModSettings::setChannelMute(), SWGSDRangel::SWGAMModSettings::setCwKeyer(), SWGSDRangel::SWGAMModSettings::setInputFrequencyOffset(), SWGSDRangel::SWGAMModSettings::setModAfInput(), SWGSDRangel::SWGAMModSettings::setModFactor(), SWGSDRangel::SWGAMModSettings::setPlayLoop(), SWGSDRangel::SWGAMModSettings::setReverseApiAddress(), SWGSDRangel::SWGAMModSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGAMModSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGAMModSettings::setReverseApiPort(), SWGSDRangel::SWGAMModSettings::setRfBandwidth(), SWGSDRangel::SWGAMModSettings::setRgbColor(), SWGSDRangel::SWGAMModSettings::setTitle(), SWGSDRangel::SWGAMModSettings::setToneFrequency(), SWGSDRangel::SWGAMModSettings::setUseReverseApi(), SWGSDRangel::SWGAMModSettings::setVolumeFactor(), and CWKeyer::webapiFormatChannelSettings().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getAmModSettings()->setChannelMute(settings.m_channelMute ? 1 : 0);
     response.getAmModSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getAmModSettings()->setModAfInput((int) settings.m_modAFInput);
     response.getAmModSettings()->setPlayLoop(settings.m_playLoop ? 1 : 0);
     response.getAmModSettings()->setRfBandwidth(settings.m_rfBandwidth);
     response.getAmModSettings()->setModFactor(settings.m_modFactor);
     response.getAmModSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getAmModSettings()->getTitle()) {
         *response.getAmModSettings()->getTitle() = settings.m_title;
     } else {
         response.getAmModSettings()->setTitle(new QString(settings.m_title));
     }
     response.getAmModSettings()->setToneFrequency(settings.m_toneFrequency);
     response.getAmModSettings()->setVolumeFactor(settings.m_volumeFactor);
     if (!response.getAmModSettings()->getCwKeyer()) {
         response.getAmModSettings()->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings);
     }
     SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = response.getAmModSettings()->getCwKeyer();
     const CWKeyerSettings& cwKeyerSettings = m_cwKeyer.getSettings();
     m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     if (response.getAmModSettings()->getAudioDeviceName()) {
         *response.getAmModSettings()->getAudioDeviceName() = settings.m_audioDeviceName;
     } else {
         response.getAmModSettings()->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     response.getAmModSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getAmModSettings()->getReverseApiAddress()) {
         *response.getAmModSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getAmModSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getAmModSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getAmModSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getAmModSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int AMMod::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 786 of file ammod.cpp.
References SWGSDRangel::SWGChannelReport::getAmModReport(), SWGSDRangel::SWGAMModReport::init(), SWGSDRangel::SWGChannelReport::setAmModReport(), and webapiFormatChannelReport().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setAmModReport(new SWGSDRangel::SWGAMModReport());
     response.getAmModReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendCWSettings()
void AMMod::webapiReverseSendCWSettings (const CWKeyerSettings & settings) private
Definition at line 923 of file ammod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), SWGSDRangel::SWGChannelSettings::getAmModSettings(), SWGSDRangel::SWGAMModSettings::getCwKeyer(), m_cwKeyer, m_networkManager, m_networkRequest, AMModSettings::m_reverseAPIAddress, AMModSettings::m_reverseAPIChannelIndex, AMModSettings::m_reverseAPIDeviceIndex, AMModSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGChannelSettings::setAmModSettings(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGAMModSettings::setCwKeyer(), SWGSDRangel::SWGChannelSettings::setDirection(), and CWKeyer::webapiFormatChannelSettings().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setChannelType(new QString("AMMod"));
     swgChannelSettings->setAmModSettings(new SWGSDRangel::SWGAMModSettings());
     SWGSDRangel::SWGAMModSettings *swgAMModSettings = swgChannelSettings->getAmModSettings();
     swgAMModSettings->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings());
     SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = swgAMModSettings->getCwKeyer();
     m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex)
             .arg(m_settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiReverseSendSettings()
void AMMod::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const AMModSettings & settings, bool force) private
Definition at line 850 of file ammod.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), SWGSDRangel::SWGChannelSettings::getAmModSettings(), SWGSDRangel::SWGAMModSettings::getCwKeyer(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), CWKeyer::getSettings(), AMModSettings::m_audioDeviceName, AMModSettings::m_channelMute, m_cwKeyer, AMModSettings::m_inputFrequencyOffset, AMModSettings::m_modAFInput, AMModSettings::m_modFactor, m_networkManager, m_networkRequest, AMModSettings::m_playLoop, AMModSettings::m_reverseAPIAddress, AMModSettings::m_reverseAPIChannelIndex, AMModSettings::m_reverseAPIDeviceIndex, AMModSettings::m_reverseAPIPort, AMModSettings::m_rfBandwidth, AMModSettings::m_rgbColor, AMModSettings::m_title, AMModSettings::m_toneFrequency, AMModSettings::m_volumeFactor, SWGSDRangel::SWGChannelSettings::setAmModSettings(), SWGSDRangel::SWGAMModSettings::setAudioDeviceName(), SWGSDRangel::SWGAMModSettings::setChannelMute(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGAMModSettings::setCwKeyer(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGAMModSettings::setInputFrequencyOffset(), SWGSDRangel::SWGAMModSettings::setModAfInput(), SWGSDRangel::SWGAMModSettings::setModFactor(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGAMModSettings::setPlayLoop(), SWGSDRangel::SWGAMModSettings::setRfBandwidth(), SWGSDRangel::SWGAMModSettings::setRgbColor(), SWGSDRangel::SWGAMModSettings::setTitle(), SWGSDRangel::SWGAMModSettings::setToneFrequency(), SWGSDRangel::SWGAMModSettings::setVolumeFactor(), and CWKeyer::webapiFormatChannelSettings().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(1); // single source (Tx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("AMMod"));
     swgChannelSettings->setAmModSettings(new SWGSDRangel::SWGAMModSettings());
     SWGSDRangel::SWGAMModSettings *swgAMModSettings = swgChannelSettings->getAmModSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("channelMute") || force) {
         swgAMModSettings->setChannelMute(settings.m_channelMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgAMModSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("modAFInput") || force) {
         swgAMModSettings->setModAfInput((int) settings.m_modAFInput);
     }
     if (channelSettingsKeys.contains("audioDeviceName") || force) {
         swgAMModSettings->setAudioDeviceName(new QString(settings.m_audioDeviceName));
     }
     if (channelSettingsKeys.contains("playLoop") || force) {
         swgAMModSettings->setPlayLoop(settings.m_playLoop ? 1 : 0);
     }
     if (channelSettingsKeys.contains("rfBandwidth") || force) {
         swgAMModSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgAMModSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgAMModSettings->setTitle(new QString(settings.m_title));
     }
     if (channelSettingsKeys.contains("toneFrequency") || force) {
         swgAMModSettings->setToneFrequency(settings.m_toneFrequency);
     }
     if (channelSettingsKeys.contains("volumeFactor") || force) {
         swgAMModSettings->setVolumeFactor(settings.m_volumeFactor);
     }
     if (channelSettingsKeys.contains("modFactor") || force) {
         swgAMModSettings->setModFactor(settings.m_modFactor);
     }
     if (force)
     {
         const CWKeyerSettings& cwKeyerSettings = m_cwKeyer.getSettings();
         swgAMModSettings->setCwKeyer(new SWGSDRangel::SWGCWKeyerSettings());
         SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = swgAMModSettings->getCwKeyer();
         m_cwKeyer.webapiFormatChannelSettings(apiCwKeyerSettings, cwKeyerSettings);
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int AMMod::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 677 of file ammod.cpp.
References SWGSDRangel::SWGChannelSettings::getAmModSettings(), SWGSDRangel::SWGAMModSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setAmModSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setAmModSettings(new SWGSDRangel::SWGAMModSettings());
     response.getAmModSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int AMMod::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 688 of file ammod.cpp.
References AMMod::MsgConfigureAMMod::create(), CWKeyer::MsgConfigureCWKeyer::create(), AMMod::MsgConfigureChannelizer::create(), SWGSDRangel::SWGChannelSettings::getAmModSettings(), SWGSDRangel::SWGAMModSettings::getAudioDeviceName(), SWGSDRangel::SWGAMModSettings::getChannelMute(), SWGSDRangel::SWGAMModSettings::getCwKeyer(), SWGSDRangel::SWGAMModSettings::getInputFrequencyOffset(), CWKeyer::getInputMessageQueue(), SWGSDRangel::SWGAMModSettings::getModAfInput(), SWGSDRangel::SWGAMModSettings::getModFactor(), SWGSDRangel::SWGAMModSettings::getPlayLoop(), SWGSDRangel::SWGAMModSettings::getReverseApiAddress(), SWGSDRangel::SWGAMModSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGAMModSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGAMModSettings::getReverseApiPort(), SWGSDRangel::SWGAMModSettings::getRfBandwidth(), SWGSDRangel::SWGAMModSettings::getRgbColor(), CWKeyer::getSettings(), SWGSDRangel::SWGAMModSettings::getTitle(), SWGSDRangel::SWGAMModSettings::getToneFrequency(), SWGSDRangel::SWGAMModSettings::getUseReverseApi(), SWGSDRangel::SWGAMModSettings::getVolumeFactor(), AMModSettings::m_audioDeviceName, m_audioSampleRate, AMModSettings::m_channelMute, m_cwKeyer, BasebandSampleSource::m_guiMessageQueue, AMModSettings::m_inputFrequencyOffset, BasebandSampleSource::m_inputMessageQueue, AMModSettings::m_modAFInput, AMModSettings::m_modFactor, AMModSettings::m_playLoop, AMModSettings::m_reverseAPIAddress, AMModSettings::m_reverseAPIChannelIndex, AMModSettings::m_reverseAPIDeviceIndex, AMModSettings::m_reverseAPIPort, AMModSettings::m_rfBandwidth, AMModSettings::m_rgbColor, m_settings, AMModSettings::m_title, AMModSettings::m_toneFrequency, AMModSettings::m_useReverseAPI, AMModSettings::m_volumeFactor, MessageQueue::push(), webapiFormatChannelSettings(), and CWKeyer::webapiSettingsPutPatch().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     AMModSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
     if (channelSettingsKeys.contains("channelMute")) {
         settings.m_channelMute = response.getAmModSettings()->getChannelMute() != 0;
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getAmModSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("modAFInput")) {
         settings.m_modAFInput = (AMModSettings::AMModInputAF) response.getAmModSettings()->getModAfInput();
     }
     if (channelSettingsKeys.contains("audioDeviceName")) {
         settings.m_audioDeviceName = *response.getAmModSettings()->getAudioDeviceName();
     }
     if (channelSettingsKeys.contains("playLoop")) {
         settings.m_playLoop = response.getAmModSettings()->getPlayLoop() != 0;
     }
     if (channelSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getAmModSettings()->getRfBandwidth();
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getAmModSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getAmModSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("toneFrequency")) {
         settings.m_toneFrequency = response.getAmModSettings()->getToneFrequency();
     }
     if (channelSettingsKeys.contains("volumeFactor")) {
         settings.m_volumeFactor = response.getAmModSettings()->getVolumeFactor();
     }
     if (channelSettingsKeys.contains("modFactor")) {
         settings.m_modFactor = response.getAmModSettings()->getModFactor();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getAmModSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getAmModSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getAmModSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getAmModSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getAmModSettings()->getReverseApiChannelIndex();
     }
     if (channelSettingsKeys.contains("cwKeyer"))
     {
         SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings = response.getAmModSettings()->getCwKeyer();
         CWKeyerSettings cwKeyerSettings = m_cwKeyer.getSettings();
         m_cwKeyer.webapiSettingsPutPatch(channelSettingsKeys, cwKeyerSettings, apiCwKeyerSettings);
         CWKeyer::MsgConfigureCWKeyer *msgCwKeyer = CWKeyer::MsgConfigureCWKeyer::create(cwKeyerSettings, force);
         m_cwKeyer.getInputMessageQueue()->push(msgCwKeyer);
         if (m_guiMessageQueue) // forward to GUI if any
         {
             CWKeyer::MsgConfigureCWKeyer *msgCwKeyerToGUI = CWKeyer::MsgConfigureCWKeyer::create(cwKeyerSettings, force);
             m_guiMessageQueue->push(msgCwKeyerToGUI);
         }
     }
     if (frequencyOffsetChanged)
     {
         AMMod::MsgConfigureChannelizer *msgChan = AMMod::MsgConfigureChannelizer::create(
                 m_audioSampleRate, settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(msgChan);
     }
     MsgConfigureAMMod *msg = MsgConfigureAMMod::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureAMMod *msgToGUI = MsgConfigureAMMod::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_audioBuffer
AudioVector AMMod::m_audioBuffer private
Definition at line 295 of file ammod.h.
Referenced by AMMod(), pullAF(), and pullAudio().
m_audioBufferFill
uint AMMod::m_audioBufferFill private
Definition at line 296 of file ammod.h.
Referenced by AMMod(), modulateSample(), pullAF(), and pullAudio().
m_audioFifo
AudioFifo AMMod::m_audioFifo private
Definition at line 297 of file ammod.h.
Referenced by AMMod(), applySettings(), pullAudio(), start(), and ~AMMod().
m_audioSampleRate
quint32 AMMod::m_audioSampleRate private
Definition at line 294 of file ammod.h.
Referenced by AMMod(), applyAudioSampleRate(), applyChannelSettings(), applyFeedbackAudioSampleRate(), applySettings(), handleMessage(), pullAudio(), webapiFormatChannelReport(), and webapiSettingsPutPatch().
m_basebandSampleRate
int AMMod::m_basebandSampleRate private
Definition at line 272 of file ammod.h.
Referenced by AMMod(), applyChannelSettings(), pullAudio(), and start().
m_carrierNco
NCO AMMod::m_carrierNco private
Definition at line 277 of file ammod.h.
Referenced by applyChannelSettings(), and pull().
m_channelId
const QString AMMod::m_channelId ="AMMod" static
Definition at line 250 of file ammod.h.
Referenced by AMMod(), and AMModPlugin::initPlugin().
m_channelIdURI
const QString AMMod::m_channelIdURI = "sdrangel.channeltx.modam" static
Definition at line 249 of file ammod.h.
Referenced by AMModGUI::AMModGUI(), and AMModPlugin::initPlugin().
m_channelizer
UpChannelizer* AMMod::m_channelizer private
Definition at line 270 of file ammod.h.
Referenced by AMMod(), handleMessage(), and ~AMMod().
m_cwKeyer
CWKeyer AMMod::m_cwKeyer private
Definition at line 316 of file ammod.h.
Referenced by AMMod(), applyAudioSampleRate(), getCWKeyer(), pullAF(), webapiFormatChannelSettings(), webapiReverseSendCWSettings(), webapiReverseSendSettings(), and webapiSettingsPutPatch().
m_deviceAPI
DeviceAPI* AMMod::m_deviceAPI private
Definition at line 268 of file ammod.h.
Referenced by AMMod(), and ~AMMod().
m_feedbackAudioBuffer
AudioVector AMMod::m_feedbackAudioBuffer private
Definition at line 300 of file ammod.h.
Referenced by AMMod(), and processOneSample().
m_feedbackAudioBufferFill
uint AMMod::m_feedbackAudioBufferFill private
Definition at line 301 of file ammod.h.
Referenced by AMMod(), and processOneSample().
m_feedbackAudioFifo
AudioFifo AMMod::m_feedbackAudioFifo private
Definition at line 302 of file ammod.h.
Referenced by AMMod(), applySettings(), processOneSample(), and ~AMMod().
m_feedbackAudioSampleRate
quint32 AMMod::m_feedbackAudioSampleRate private
Definition at line 299 of file ammod.h.
Referenced by AMMod(), applyAudioSampleRate(), applyFeedbackAudioSampleRate(), and applySettings().
m_feedbackInterpolator
Interpolator AMMod::m_feedbackInterpolator private
Definition at line 286 of file ammod.h.
Referenced by applyFeedbackAudioSampleRate(), and pushFeedback().
m_feedbackInterpolatorConsumed
bool AMMod::m_feedbackInterpolatorConsumed private
Definition at line 289 of file ammod.h.
Referenced by applyFeedbackAudioSampleRate().
m_feedbackInterpolatorDistance
Real AMMod::m_feedbackInterpolatorDistance private
Definition at line 287 of file ammod.h.
Referenced by applyFeedbackAudioSampleRate(), processOneSample(), and pushFeedback().
m_feedbackInterpolatorDistanceRemain
Real AMMod::m_feedbackInterpolatorDistanceRemain private
Definition at line 288 of file ammod.h.
Referenced by applyFeedbackAudioSampleRate(), and pushFeedback().
m_fileName
QString AMMod::m_fileName private
Definition at line 308 of file ammod.h.
Referenced by AMMod::MsgConfigureFileSourceName::getFileName(), handleMessage(), and openFileStream().
m_fileSize
quint64 AMMod::m_fileSize private
raw file size (bytes)
Definition at line 309 of file ammod.h.
Referenced by handleMessage(), and openFileStream().
m_ifstream
std::ifstream AMMod::m_ifstream private
Definition at line 307 of file ammod.h.
Referenced by handleMessage(), openFileStream(), pullAF(), and seekFileStream().
m_inputFrequencyOffset
int AMMod::m_inputFrequencyOffset private
Definition at line 274 of file ammod.h.
Referenced by AMMod(), applyChannelSettings(), and start().
m_interpolator
Interpolator AMMod::m_interpolator private
Definition at line 281 of file ammod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and pull().
m_interpolatorConsumed
bool AMMod::m_interpolatorConsumed private
Definition at line 284 of file ammod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), and applySettings().
m_interpolatorDistance
Real AMMod::m_interpolatorDistance private
Definition at line 282 of file ammod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and pull().
m_interpolatorDistanceRemain
Real AMMod::m_interpolatorDistanceRemain private
Definition at line 283 of file ammod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applySettings(), and pull().
m_levelCalcCount
quint32 AMMod::m_levelCalcCount private
Definition at line 313 of file ammod.h.
Referenced by calculateLevel().
m_levelNbSamples
const int AMMod::m_levelNbSamples = 480 static private
Definition at line 318 of file ammod.h.
Referenced by calculateLevel().
m_levelSum
Real AMMod::m_levelSum private
Definition at line 315 of file ammod.h.
Referenced by calculateLevel().
m_magsq
double AMMod::m_magsq private
Definition at line 291 of file ammod.h.
Referenced by AMMod(), getMagSq(), and pull().
m_modSample
Complex AMMod::m_modSample private
Definition at line 279 of file ammod.h.
Referenced by modulateSample(), and pull().
m_movingAverage
MovingAverageUtil<double, double, 16> AMMod::m_movingAverage private
Definition at line 292 of file ammod.h.
Referenced by pull().
m_networkManager
QNetworkAccessManager* AMMod::m_networkManager private
Definition at line 320 of file ammod.h.
Referenced by AMMod(), webapiReverseSendCWSettings(), webapiReverseSendSettings(), and ~AMMod().
m_networkRequest
QNetworkRequest AMMod::m_networkRequest private
Definition at line 321 of file ammod.h.
Referenced by webapiReverseSendCWSettings(), and webapiReverseSendSettings().
m_outputSampleRate
int AMMod::m_outputSampleRate private
Definition at line 273 of file ammod.h.
Referenced by AMMod(), applyAudioSampleRate(), applyChannelSettings(), applySettings(), start(), and webapiFormatChannelReport().
m_peakLevel
Real AMMod::m_peakLevel private
Definition at line 314 of file ammod.h.
Referenced by calculateLevel().
m_recordLength
quint32 AMMod::m_recordLength private
record length in seconds computed from file size
Definition at line 310 of file ammod.h.
Referenced by AMMod::MsgReportFileSourceStreamData::getRecordLength(), openFileStream(), and seekFileStream().
m_sampleBuffer
SampleVector AMMod::m_sampleBuffer private
Definition at line 304 of file ammod.h.
m_sampleRate
int AMMod::m_sampleRate private
Definition at line 311 of file ammod.h.
Referenced by AMMod::MsgConfigureChannelizer::getSampleRate(), AMMod::MsgReportFileSourceStreamData::getSampleRate(), openFileStream(), and seekFileStream().
m_settings
AMModSettings AMMod::m_settings private
Definition at line 275 of file ammod.h.
Referenced by AMMod(), applyAudioSampleRate(), applyChannelSettings(), applySettings(), deserialize(), handleMessage(), modulateSample(), pull(), pullAF(), serialize(), start(), webapiReverseSendCWSettings(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex AMMod::m_settingsMutex private
Definition at line 305 of file ammod.h.
Referenced by applyAudioSampleRate(), applyChannelSettings(), applyFeedbackAudioSampleRate(), applySettings(), pull(), and seekFileStream().
m_threadedChannelizer
ThreadedBasebandSampleSource* AMMod::m_threadedChannelizer private
Definition at line 269 of file ammod.h.
Referenced by AMMod(), and ~AMMod().
m_toneNco
NCOF AMMod::m_toneNco private
Definition at line 278 of file ammod.h.
Referenced by AMMod(), applyAudioSampleRate(), applySettings(), and pullAF().
The documentation for this class was generated from the following files:
plugins/channeltx/modam/ammod.h
plugins/channeltx/modam/ammod.cpp