SDRAngel: FileSource::MsgConfigureFileSource Class Reference
FileSource::MsgConfigureFileSource Class Reference
#include <filesource.h>
Public Member Functions
const FileSourceSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureFileSource * create (const FileSourceSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureFileSource (const FileSourceSettings &settings, bool force)
Private Attributes
FileSourceSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 70 of file filesource.h.
Constructor & Destructor Documentation
MsgConfigureFileSource()
FileSource::MsgConfigureFileSource::MsgConfigureFileSource (const FileSourceSettings & settings, bool force) inline private
Definition at line 86 of file filesource.h.
                                                                                :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureFileSource* FileSource::MsgConfigureFileSource::create (const FileSourceSettings & settings, bool force) inline static
Definition at line 77 of file filesource.h.
Referenced by FileSourceGUI::applySettings(), FileSource::deserialize(), FileSourceGUI::on_playLoop_toggled(), and FileSource::webapiSettingsPutPatch().
         {
             return new MsgConfigureFileSource(settings, force);
         }
getForce()
bool FileSource::MsgConfigureFileSource::getForce () const inline
Definition at line 75 of file filesource.h.
Referenced by FileSource::handleMessage().
 { return m_force; }
getSettings()
const FileSourceSettings& FileSource::MsgConfigureFileSource::getSettings () const inline
Definition at line 74 of file filesource.h.
References FileSource::m_settings.
Referenced by FileSourceGUI::handleMessage(), and FileSource::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool FileSource::MsgConfigureFileSource::m_force private
Definition at line 84 of file filesource.h.
m_settings
FileSourceSettings FileSource::MsgConfigureFileSource::m_settings private
Definition at line 83 of file filesource.h.
The documentation for this class was generated from the following file:
plugins/channeltx/filesource/filesource.h