SDRAngel: qrtplib::RTPSessionSources Class Reference
qrtplib::RTPSessionSources Class Reference
#include <rtpsessionsources.h>
Public Member Functions
RTPSessionSources (RTPSession &sess)
~RTPSessionSources ()
void ClearOwnCollisionFlag ()
bool DetectedOwnCollision () const
Public Member Functions inherited from qrtplib::RTPSources
RTPSources ()
virtual ~RTPSources ()
void Clear ()
int CreateOwnSSRC (uint32_t ssrc)
int DeleteOwnSSRC ()
void SentRTPPacket ()
int ProcessRawPacket (RTPRawPacket *rawpack, RTPTransmitter *trans, bool acceptownpackets)
int ProcessRawPacket (RTPRawPacket *rawpack, RTPTransmitter *trans[], int numtrans, bool acceptownpackets)
int ProcessRTPPacket (RTPPacket *rtppack, const RTPTime &receivetime, const RTPAddress *senderaddress, bool *stored)
int ProcessRTCPCompoundPacket (RTCPCompoundPacket *rtcpcomppack, const RTPTime &receivetime, const RTPAddress *senderaddress)
int ProcessRTCPSenderInfo (uint32_t ssrc, const RTPNTPTime &ntptime, uint32_t rtptime, uint32_t packetcount, uint32_t octetcount, const RTPTime &receivetime, const RTPAddress *senderaddress)
int ProcessRTCPReportBlock (uint32_t ssrc, uint8_t fractionlost, int32_t lostpackets, uint32_t exthighseqnr, uint32_t jitter, uint32_t lsr, uint32_t dlsr, const RTPTime &receivetime, const RTPAddress *senderaddress)
int ProcessSDESNormalItem (uint32_t ssrc, RTCPSDESPacket::ItemType t, std::size_t itemlength, const void *itemdata, const RTPTime &receivetime, const RTPAddress *senderaddress)
int ProcessSDESPrivateItem (uint32_t ssrc, std::size_t prefixlen, const void *prefixdata, std::size_t valuelen, const void *valuedata, const RTPTime &receivetime, const RTPAddress *senderaddress)
int ProcessBYE (uint32_t ssrc, std::size_t reasonlength, const void *reasondata, const RTPTime &receivetime, const RTPAddress *senderaddress)
int UpdateReceiveTime (uint32_t ssrc, const RTPTime &receivetime, const RTPAddress *senderaddress)
bool GotoFirstSource ()
bool GotoNextSource ()
bool GotoPreviousSource ()
bool GotoFirstSourceWithData ()
bool GotoNextSourceWithData ()
bool GotoPreviousSourceWithData ()
RTPSourceData * GetCurrentSourceInfo ()
RTPSourceData * GetSourceInfo (uint32_t ssrc)
RTPPacket * GetNextPacket ()
bool GotEntry (uint32_t ssrc)
RTPSourceData * GetOwnSourceInfo ()
void Timeout (const RTPTime &curtime, const RTPTime &timeoutdelay)
void SenderTimeout (const RTPTime &curtime, const RTPTime &timeoutdelay)
void BYETimeout (const RTPTime &curtime, const RTPTime &timeoutdelay)
void NoteTimeout (const RTPTime &curtime, const RTPTime &timeoutdelay)
void MultipleTimeouts (const RTPTime &curtime, const RTPTime &sendertimeout, const RTPTime &byetimeout, const RTPTime &generaltimeout, const RTPTime &notetimeout)
int GetSenderCount () const
int GetTotalCount () const
int GetActiveMemberCount () const
Private Member Functions
void OnRTPPacket (RTPPacket *pack, const RTPTime &receivetime, const RTPAddress *senderaddress)
void OnRTCPCompoundPacket (RTCPCompoundPacket *pack, const RTPTime &receivetime, const RTPAddress *senderaddress)
void OnSSRCCollision (RTPSourceData *srcdat, const RTPAddress *senderaddress, bool isrtp)
void OnCNAMECollision (RTPSourceData *srcdat, const RTPAddress *senderaddress, const uint8_t *cname, std::size_t cnamelength)
void OnNewSource (RTPSourceData *srcdat)
void OnRemoveSource (RTPSourceData *srcdat)
void OnTimeout (RTPSourceData *srcdat)
void OnBYETimeout (RTPSourceData *srcdat)
void OnBYEPacket (RTPSourceData *srcdat)
void OnAPPPacket (RTCPAPPPacket *apppacket, const RTPTime &receivetime, const RTPAddress *senderaddress)
void OnUnknownPacketType (RTCPPacket *rtcppack, const RTPTime &receivetime, const RTPAddress *senderaddress)
void OnUnknownPacketFormat (RTCPPacket *rtcppack, const RTPTime &receivetime, const RTPAddress *senderaddress)
void OnNoteTimeout (RTPSourceData *srcdat)
void OnValidatedRTPPacket (RTPSourceData *srcdat, RTPPacket *rtppack, bool isonprobation, bool *ispackethandled)
void OnRTCPSenderReport (RTPSourceData *srcdat)
void OnRTCPReceiverReport (RTPSourceData *srcdat)
void OnRTCPSDESItem (RTPSourceData *srcdat, RTCPSDESPacket::ItemType t, const void *itemdata, std::size_t itemlength)
void OnRTCPSDESPrivateItem (RTPSourceData *srcdat, const void *prefixdata, std::size_t prefixlen, const void *valuedata, std::size_t valuelen)
Private Attributes
RTPSession & rtpsession
bool owncollision
Additional Inherited Members
Public Types inherited from qrtplib::RTPSources
enum ProbationType { NoProbation, ProbationDiscard, ProbationStore }
Detailed Description
Definition at line 51 of file rtpsessionsources.h.
Constructor & Destructor Documentation
RTPSessionSources()
qrtplib::RTPSessionSources::RTPSessionSources (RTPSession & sess) inline
Definition at line 54 of file rtpsessionsources.h.
                                         :
             rtpsession(sess)
     {
         owncollision = false;
     }
~RTPSessionSources()
qrtplib::RTPSessionSources::~RTPSessionSources () inline
Definition at line 59 of file rtpsessionsources.h.
     {
     }
Member Function Documentation
ClearOwnCollisionFlag()
void qrtplib::RTPSessionSources::ClearOwnCollisionFlag () inline
Definition at line 62 of file rtpsessionsources.h.
Referenced by qrtplib::RTPSession::ProcessPolledData().
     {
         owncollision = false;
     }
DetectedOwnCollision()
bool qrtplib::RTPSessionSources::DetectedOwnCollision () const inline
Definition at line 66 of file rtpsessionsources.h.
Referenced by qrtplib::RTPSession::ProcessPolledData().
     {
         return owncollision;
     }
OnAPPPacket()
void qrtplib::RTPSessionSources::OnAPPPacket (RTCPAPPPacket * apppacket, const RTPTime & receivetime, const RTPAddress * senderaddress) private virtual
Is called when an RTCP APP packet apppacket has been received at time receivetime from address senderaddress.
Reimplemented from qrtplib::RTPSources.
Definition at line 91 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnAPPPacket(), and rtpsession.
 {
     rtpsession.OnAPPPacket(apppacket, receivetime, senderaddress);
 }
OnBYEPacket()
void qrtplib::RTPSessionSources::OnBYEPacket (RTPSourceData * srcdat) private virtual
Is called when a BYE packet has been processed for source srcdat.
Reimplemented from qrtplib::RTPSources.
Definition at line 85 of file rtpsessionsources.cpp.
References qrtplib::RTCPScheduler::ActiveMemberDecrease(), qrtplib::RTPSession::OnBYEPacket(), qrtplib::RTPSession::rtcpsched, and rtpsession.
 {
     rtpsession.rtcpsched.ActiveMemberDecrease();
     rtpsession.OnBYEPacket(srcdat);
 }
OnBYETimeout()
void qrtplib::RTPSessionSources::OnBYETimeout (RTPSourceData * srcdat) private virtual
Is called when participant srcdat is timed after having sent a BYE packet.
Reimplemented from qrtplib::RTPSources.
Definition at line 80 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnBYETimeout(), and rtpsession.
 {
     rtpsession.OnBYETimeout(srcdat);
 }
OnCNAMECollision()
void qrtplib::RTPSessionSources::OnCNAMECollision (RTPSourceData * srcdat, const RTPAddress * senderaddress, const uint8_t * cname, std::size_t cnamelength) private virtual
Is called when another CNAME was received than the one already present for source srcdat.
Reimplemented from qrtplib::RTPSources.
Definition at line 59 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnCNAMECollision(), and rtpsession.
 {
     rtpsession.OnCNAMECollision(srcdat, senderaddress, cname, cnamelength);
 }
OnNewSource()
void qrtplib::RTPSessionSources::OnNewSource (RTPSourceData * srcdat) private virtual
Is called when a new entry srcdat is added to the source table.
Reimplemented from qrtplib::RTPSources.
Definition at line 64 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnNewSource(), and rtpsession.
 {
     rtpsession.OnNewSource(srcdat);
 }
OnNoteTimeout()
void qrtplib::RTPSessionSources::OnNoteTimeout (RTPSourceData * srcdat) private virtual
Is called when the SDES NOTE item for source srcdat has been timed out.
Reimplemented from qrtplib::RTPSources.
Definition at line 106 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnNoteTimeout(), and rtpsession.
 {
     rtpsession.OnNoteTimeout(srcdat);
 }
OnRemoveSource()
void qrtplib::RTPSessionSources::OnRemoveSource (RTPSourceData * srcdat) private virtual
Is called when the entry srcdat is about to be deleted from the source table.
Reimplemented from qrtplib::RTPSources.
Definition at line 69 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnRemoveSource(), and rtpsession.
 {
     rtpsession.OnRemoveSource(srcdat);
 }
OnRTCPCompoundPacket()
void qrtplib::RTPSessionSources::OnRTCPCompoundPacket (RTCPCompoundPacket * pack, const RTPTime & receivetime, const RTPAddress * senderaddress) private virtual
Is called when an RTCP compound packet is about to be processed.
Reimplemented from qrtplib::RTPSources.
Definition at line 45 of file rtpsessionsources.cpp.
References qrtplib::RTCPScheduler::AnalyseIncoming(), qrtplib::RTPSession::OnRTCPCompoundPacket(), qrtplib::RTPSession::rtcpsched, and rtpsession.
 {
     if (senderaddress != 0) // don't analyse own RTCP packets again (they're already analysed on their way out)
         rtpsession.rtcpsched.AnalyseIncoming(*pack);
     rtpsession.OnRTCPCompoundPacket(pack, receivetime, senderaddress);
 }
OnRTCPReceiverReport()
void qrtplib::RTPSessionSources::OnRTCPReceiverReport (RTPSourceData * srcdat) private virtual
Is called when an RTCP receiver report has been processed for this source.
Reimplemented from qrtplib::RTPSources.
Definition at line 121 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnRTCPReceiverReport(), and rtpsession.
 {
     rtpsession.OnRTCPReceiverReport(srcdat);
 }
OnRTCPSDESItem()
void qrtplib::RTPSessionSources::OnRTCPSDESItem (RTPSourceData * srcdat, RTCPSDESPacket::ItemType t, const void * itemdata, std::size_t itemlength) private virtual
Is called when a specific SDES item was received for this source.
Reimplemented from qrtplib::RTPSources.
Definition at line 126 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnRTCPSDESItem(), and rtpsession.
 {
     rtpsession.OnRTCPSDESItem(srcdat, t, itemdata, itemlength);
 }
OnRTCPSDESPrivateItem()
void qrtplib::RTPSessionSources::OnRTCPSDESPrivateItem (RTPSourceData * srcdat, const void * prefixdata, std::size_t prefixlen, const void * valuedata, std::size_t valuelen) private virtual
Is called when a specific SDES item of 'private' type was received for this source.
Reimplemented from qrtplib::RTPSources.
Definition at line 132 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnRTCPSDESPrivateItem(), and rtpsession.
 {
     rtpsession.OnRTCPSDESPrivateItem(srcdat, prefixdata, prefixlen, valuedata, valuelen);
 }
OnRTCPSenderReport()
void qrtplib::RTPSessionSources::OnRTCPSenderReport (RTPSourceData * srcdat) private virtual
Is called when an RTCP sender report has been processed for this source.
Reimplemented from qrtplib::RTPSources.
Definition at line 116 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnRTCPSenderReport(), and rtpsession.
 {
     rtpsession.OnRTCPSenderReport(srcdat);
 }
OnRTPPacket()
void qrtplib::RTPSessionSources::OnRTPPacket (RTPPacket * pack, const RTPTime & receivetime, const RTPAddress * senderaddress) private virtual
Is called when an RTP packet is about to be processed.
Reimplemented from qrtplib::RTPSources.
Definition at line 40 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnRTPPacket(), and rtpsession.
 {
     rtpsession.OnRTPPacket(pack, receivetime, senderaddress);
 }
OnSSRCCollision()
void qrtplib::RTPSessionSources::OnSSRCCollision (RTPSourceData * srcdat, const RTPAddress * senderaddress, bool isrtp) private virtual
Is called when an SSRC collision was detected. Is called when an SSRC collision was detected. The instance srcdat is the one present in the table, the address senderaddress is the one that collided with one of the addresses and isrtp indicates against which address of srcdat the check failed.
Reimplemented from qrtplib::RTPSources.
Definition at line 52 of file rtpsessionsources.cpp.
References qrtplib::RTPSourceData::IsOwnSSRC(), qrtplib::RTPSession::OnSSRCCollision(), owncollision, and rtpsession.
 {
     if (srcdat->IsOwnSSRC())
         owncollision = true;
     rtpsession.OnSSRCCollision(srcdat, senderaddress, isrtp);
 }
OnTimeout()
void qrtplib::RTPSessionSources::OnTimeout (RTPSourceData * srcdat) private virtual
Is called when participant srcdat is timed out.
Reimplemented from qrtplib::RTPSources.
Definition at line 74 of file rtpsessionsources.cpp.
References qrtplib::RTCPScheduler::ActiveMemberDecrease(), qrtplib::RTPSession::OnTimeout(), qrtplib::RTPSession::rtcpsched, and rtpsession.
 {
     rtpsession.rtcpsched.ActiveMemberDecrease();
     rtpsession.OnTimeout(srcdat);
 }
OnUnknownPacketFormat()
void qrtplib::RTPSessionSources::OnUnknownPacketFormat (RTCPPacket * rtcppack, const RTPTime & receivetime, const RTPAddress * senderaddress) private virtual
Is called when an unknown packet format for a known packet type was detected.
Reimplemented from qrtplib::RTPSources.
Definition at line 101 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnUnknownPacketFormat(), and rtpsession.
 {
     rtpsession.OnUnknownPacketFormat(rtcppack, receivetime, senderaddress);
 }
OnUnknownPacketType()
void qrtplib::RTPSessionSources::OnUnknownPacketType (RTCPPacket * rtcppack, const RTPTime & receivetime, const RTPAddress * senderaddress) private virtual
Is called when an unknown RTCP packet type was detected.
Reimplemented from qrtplib::RTPSources.
Definition at line 96 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnUnknownPacketType(), and rtpsession.
 {
     rtpsession.OnUnknownPacketType(rtcppack, receivetime, senderaddress);
 }
OnValidatedRTPPacket()
void qrtplib::RTPSessionSources::OnValidatedRTPPacket (RTPSourceData * srcdat, RTPPacket * rtppack, bool isonprobation, bool * ispackethandled) private virtual
Allows you to use an RTP packet from the specified source directly. Allows you to use an RTP packet from the specified source directly. If ispackethandled is set to true, the packet will no longer be stored in this source's packet list.
Reimplemented from qrtplib::RTPSources.
Definition at line 111 of file rtpsessionsources.cpp.
References qrtplib::RTPSession::OnValidatedRTPPacket(), and rtpsession.
 {
     rtpsession.OnValidatedRTPPacket(srcdat, rtppack, isonprobation, ispackethandled);
 }
Member Data Documentation
owncollision
bool qrtplib::RTPSessionSources::owncollision private
Definition at line 93 of file rtpsessionsources.h.
Referenced by OnSSRCCollision().
rtpsession
RTPSession& qrtplib::RTPSessionSources::rtpsession private
Definition at line 92 of file rtpsessionsources.h.
Referenced by OnAPPPacket(), OnBYEPacket(), OnBYETimeout(), OnCNAMECollision(), OnNewSource(), OnNoteTimeout(), OnRemoveSource(), OnRTCPCompoundPacket(), OnRTCPReceiverReport(), OnRTCPSDESItem(), OnRTCPSDESPrivateItem(), OnRTCPSenderReport(), OnRTPPacket(), OnSSRCCollision(), OnTimeout(), OnUnknownPacketFormat(), OnUnknownPacketType(), and OnValidatedRTPPacket().
The documentation for this class was generated from the following files:
qrtplib/rtpsessionsources.h
qrtplib/rtpsessionsources.cpp