SDRAngel: qrtplib::RTPSessionParams Class Reference
qrtplib::RTPSessionParams Class Reference
#include <rtpsessionparams.h>
Public Member Functions
RTPSessionParams ()
int SetUsePollThread (bool usethread)
int SetNeedThreadSafety (bool s)
bool IsUsingPollThread () const
void SetMaximumPacketSize (std::size_t max)
std::size_t GetMaximumPacketSize () const
void SetAcceptOwnPackets (bool accept)
bool AcceptOwnPackets () const
void SetReceiveMode (RTPTransmitter::ReceiveMode recvmode)
RTPTransmitter::ReceiveMode GetReceiveMode () const
void SetOwnTimestampUnit (double tsunit)
double GetOwnTimestampUnit () const
void SetResolveLocalHostname (bool v)
bool GetResolveLocalHostname () const
void SetSessionBandwidth (double sessbw)
double GetSessionBandwidth () const
void SetControlTrafficFraction (double frac)
double GetControlTrafficFraction () const
void SetSenderControlBandwidthFraction (double frac)
double GetSenderControlBandwidthFraction () const
void SetMinimumRTCPTransmissionInterval (const RTPTime &t)
RTPTime GetMinimumRTCPTransmissionInterval () const
void SetUseHalfRTCPIntervalAtStartup (bool usehalf)
bool GetUseHalfRTCPIntervalAtStartup () const
void SetRequestImmediateBYE (bool v)
bool GetRequestImmediateBYE () const
void SetSenderReportForBYE (bool v)
bool GetSenderReportForBYE () const
void SetSenderTimeoutMultiplier (double m)
double GetSenderTimeoutMultiplier () const
void SetSourceTimeoutMultiplier (double m)
double GetSourceTimeoutMultiplier () const
void SetBYETimeoutMultiplier (double m)
double GetBYETimeoutMultiplier () const
void SetCollisionTimeoutMultiplier (double m)
double GetCollisionTimeoutMultiplier () const
void SetNoteTimeoutMultiplier (double m)
double GetNoteTimeoutMultiplier () const
void SetUsePredefinedSSRC (bool f)
bool GetUsePredefinedSSRC () const
void SetPredefinedSSRC (uint32_t ssrc)
uint32_t GetPredefinedSSRC () const
void SetCNAME (const std::string &s)
std::string GetCNAME () const
bool NeedThreadSafety () const
Private Attributes
bool acceptown
bool usepollthread
std::size_t maxpacksize
double owntsunit
RTPTransmitter::ReceiveMode receivemode
bool resolvehostname
double sessionbandwidth
double controlfrac
double senderfrac
RTPTime mininterval
bool usehalfatstartup
bool immediatebye
bool SR_BYE
double sendermultiplier
double generaltimeoutmultiplier
double byetimeoutmultiplier
double collisionmultiplier
double notemultiplier
bool usepredefinedssrc
uint32_t predefinedssrc
std::string cname
bool m_needThreadSafety
Detailed Description
Describes the parameters for to be used by an RTPSession instance. Describes the parameters for to be used by an RTPSession instance. Note that the own timestamp unit must be set to a valid number, otherwise the session can't be created.
Definition at line 56 of file rtpsessionparams.h.
Constructor & Destructor Documentation
RTPSessionParams()
qrtplib::RTPSessionParams::RTPSessionParams ()
Definition at line 41 of file rtpsessionparams.cpp.
References qrtplib::RTPTransmitter::AcceptAll, acceptown, byetimeoutmultiplier, collisionmultiplier, controlfrac, generaltimeoutmultiplier, immediatebye, m_needThreadSafety, maxpacksize, mininterval, notemultiplier, owntsunit, predefinedssrc, receivemode, resolvehostname, RTCP_DEFAULTBANDWIDTHFRACTION, RTCP_DEFAULTHALFATSTARTUP, RTCP_DEFAULTIMMEDIATEBYE, RTCP_DEFAULTMININTERVAL, RTCP_DEFAULTSENDERFRACTION, RTCP_DEFAULTSRBYE, RTP_BYETIMEOUTMULTIPLIER, RTP_COLLISIONTIMEOUTMULTIPLIER, RTP_DEFAULTPACKETSIZE, RTP_DEFAULTSESSIONBANDWIDTH, RTP_MEMBERTIMEOUTMULTIPLIER, RTP_NOTETTIMEOUTMULTIPLIER, RTP_SENDERTIMEOUTMULTIPLIER, senderfrac, sendermultiplier, sessionbandwidth, SR_BYE, usehalfatstartup, usepollthread, and usepredefinedssrc.
                                    :
         mininterval(0, 0)
 {
     usepollthread = false;
     m_needThreadSafety = false;
     maxpacksize = RTP_DEFAULTPACKETSIZE;
     receivemode = RTPTransmitter::AcceptAll;
     acceptown = false;
     owntsunit = -1; // The user will have to set it to the correct value himself
     resolvehostname = false;
     mininterval = RTPTime(RTCP_DEFAULTMININTERVAL);
     sessionbandwidth = RTP_DEFAULTSESSIONBANDWIDTH;
     controlfrac = RTCP_DEFAULTBANDWIDTHFRACTION;
     senderfrac = RTCP_DEFAULTSENDERFRACTION;
     usehalfatstartup = RTCP_DEFAULTHALFATSTARTUP;
     immediatebye = RTCP_DEFAULTIMMEDIATEBYE;
     SR_BYE = RTCP_DEFAULTSRBYE;
     sendermultiplier = RTP_SENDERTIMEOUTMULTIPLIER;
     generaltimeoutmultiplier = RTP_MEMBERTIMEOUTMULTIPLIER;
     byetimeoutmultiplier = RTP_BYETIMEOUTMULTIPLIER;
     collisionmultiplier = RTP_COLLISIONTIMEOUTMULTIPLIER;
     notemultiplier = RTP_NOTETTIMEOUTMULTIPLIER;
     usepredefinedssrc = false;
     predefinedssrc = 0;
 }
Member Function Documentation
AcceptOwnPackets()
bool qrtplib::RTPSessionParams::AcceptOwnPackets () const inline
Returns true if the session should accept its own packets (default is false).
Definition at line 97 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return acceptown;
     }
GetBYETimeoutMultiplier()
double qrtplib::RTPSessionParams::GetBYETimeoutMultiplier () const inline
Returns the multiplier to be used when timing out a member after it has sent a BYE packet (default is 1).
Definition at line 272 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return byetimeoutmultiplier;
     }
GetCNAME()
std::string qrtplib::RTPSessionParams::GetCNAME () const inline
Returns the currently set CNAME, is blank when this will be generated automatically (the default).
Definition at line 332 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return cname;
     }
GetCollisionTimeoutMultiplier()
double qrtplib::RTPSessionParams::GetCollisionTimeoutMultiplier () const inline
Returns the multiplier to be used when timing out entries in the collision table (default is 10).
Definition at line 284 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return collisionmultiplier;
     }
GetControlTrafficFraction()
double qrtplib::RTPSessionParams::GetControlTrafficFraction () const inline
Returns the fraction of the session bandwidth that will be used for control traffic (default is 5%).
Definition at line 168 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return controlfrac;
     }
GetMaximumPacketSize()
std::size_t qrtplib::RTPSessionParams::GetMaximumPacketSize () const inline
Returns the maximum allowed packet size (default is 1400 bytes).
Definition at line 83 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::Create(), and RTPSink::RTPSink().
     {
         return maxpacksize;
     }
GetMinimumRTCPTransmissionInterval()
RTPTime qrtplib::RTPSessionParams::GetMinimumRTCPTransmissionInterval () const inline
Returns the minimal time interval between sending RTCP packets (default is 5 seconds).
Definition at line 192 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return mininterval;
     }
GetNoteTimeoutMultiplier()
double qrtplib::RTPSessionParams::GetNoteTimeoutMultiplier () const inline
Returns the multiplier to be used when timing out SDES NOTE information (default is 25).
Definition at line 296 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return notemultiplier;
     }
GetOwnTimestampUnit()
double qrtplib::RTPSessionParams::GetOwnTimestampUnit () const inline
Returns the currently set timestamp unit.
Definition at line 126 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return owntsunit;
     }
GetPredefinedSSRC()
uint32_t qrtplib::RTPSessionParams::GetPredefinedSSRC () const inline
Returns the SSRC which will be used if RTPSessionParams::GetUsePredefinedSSRC returns true.
Definition at line 320 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return predefinedssrc;
     }
GetReceiveMode()
RTPTransmitter::ReceiveMode qrtplib::RTPSessionParams::GetReceiveMode () const inline
Sets the receive mode to be used by the session (default is: accept all packets).
Definition at line 109 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return receivemode;
     }
GetRequestImmediateBYE()
bool qrtplib::RTPSessionParams::GetRequestImmediateBYE () const inline
Returns whether the session should send a BYE packet immediately (if allowed) or not (default is true).
Definition at line 220 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return immediatebye;
     }
GetResolveLocalHostname()
bool qrtplib::RTPSessionParams::GetResolveLocalHostname () const inline
Returns whether the local hostname should be determined from the transmitter's list of local IP addresses or not (default is false).
Definition at line 144 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return resolvehostname;
     }
GetSenderControlBandwidthFraction()
double qrtplib::RTPSessionParams::GetSenderControlBandwidthFraction () const inline
Returns the minimum fraction of the control traffic that will be used by senders (default is 25%).
Definition at line 180 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return senderfrac;
     }
GetSenderReportForBYE()
bool qrtplib::RTPSessionParams::GetSenderReportForBYE () const inline
Returns true if a BYE packet will be sent in an RTCP compound packet which starts with a sender report; if a receiver report will be used, the function returns false (default is true).
Definition at line 236 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::Create().
     {
         return SR_BYE;
     }
GetSenderTimeoutMultiplier()
double qrtplib::RTPSessionParams::GetSenderTimeoutMultiplier () const inline
Returns the multiplier to be used when timing out senders (default is 2).
Definition at line 248 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return sendermultiplier;
     }
GetSessionBandwidth()
double qrtplib::RTPSessionParams::GetSessionBandwidth () const inline
Returns the session bandwidth in bytes per second (default is 10000 bytes per second).
Definition at line 156 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return sessionbandwidth;
     }
GetSourceTimeoutMultiplier()
double qrtplib::RTPSessionParams::GetSourceTimeoutMultiplier () const inline
Returns the multiplier to be used when timing out members (default is 5).
Definition at line 260 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return generaltimeoutmultiplier;
     }
GetUseHalfRTCPIntervalAtStartup()
bool qrtplib::RTPSessionParams::GetUseHalfRTCPIntervalAtStartup () const inline
Returns whether the session will only wait half of the calculated RTCP interval before sending its first RTCP packet or not (default is true).
Definition at line 208 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return usehalfatstartup;
     }
GetUsePredefinedSSRC()
bool qrtplib::RTPSessionParams::GetUsePredefinedSSRC () const inline
Returns a flag indicating if a predefined SSRC should be used.
Definition at line 308 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         return usepredefinedssrc;
     }
IsUsingPollThread()
bool qrtplib::RTPSessionParams::IsUsingPollThread () const inline
Returns whether the session should use a poll thread or not (default is true).
Definition at line 71 of file rtpsessionparams.h.
Referenced by qrtplib::RTPSession::Create().
     {
         return usepollthread;
     }
NeedThreadSafety()
bool qrtplib::RTPSessionParams::NeedThreadSafety () const inline
Returns true if thread safety was requested using RTPSessionParams::SetNeedThreadSafety.
Definition at line 338 of file rtpsessionparams.h.
     {
         return m_needThreadSafety;
     }
SetAcceptOwnPackets()
void qrtplib::RTPSessionParams::SetAcceptOwnPackets (bool accept) inline
If the argument is true, the session should accept its own packets and store them accordingly in the source table.
Definition at line 91 of file rtpsessionparams.h.
     {
         acceptown = accept;
     }
SetBYETimeoutMultiplier()
void qrtplib::RTPSessionParams::SetBYETimeoutMultiplier (double m) inline
Sets the multiplier to be used when timing out a member after it has sent a BYE packet.
Definition at line 266 of file rtpsessionparams.h.
     {
         byetimeoutmultiplier = m;
     }
SetCNAME()
void qrtplib::RTPSessionParams::SetCNAME (const std::string & s) inline
Forces this string to be used as the CNAME identifier.
Definition at line 326 of file rtpsessionparams.h.
     {
         cname = s;
     }
SetCollisionTimeoutMultiplier()
void qrtplib::RTPSessionParams::SetCollisionTimeoutMultiplier (double m) inline
Sets the multiplier to be used when timing out entries in the collision table.
Definition at line 278 of file rtpsessionparams.h.
     {
         collisionmultiplier = m;
     }
SetControlTrafficFraction()
void qrtplib::RTPSessionParams::SetControlTrafficFraction (double frac) inline
Sets the fraction of the session bandwidth to be used for control traffic.
Definition at line 162 of file rtpsessionparams.h.
     {
         controlfrac = frac;
     }
SetMaximumPacketSize()
void qrtplib::RTPSessionParams::SetMaximumPacketSize (std::size_t max) inline
Sets the maximum allowed packet size for the session.
Definition at line 77 of file rtpsessionparams.h.
References leansdr::max().
     {
         maxpacksize = max;
     }
SetMinimumRTCPTransmissionInterval()
void qrtplib::RTPSessionParams::SetMinimumRTCPTransmissionInterval (const RTPTime & t) inline
Set the minimal time interval between sending RTCP packets.
Definition at line 186 of file rtpsessionparams.h.
     {
         mininterval = t;
     }
SetNeedThreadSafety()
int qrtplib::RTPSessionParams::SetNeedThreadSafety (bool s)
if s is true, the session will use mutexes in case multiple threads are at work.
Definition at line 76 of file rtpsessionparams.cpp.
References ERR_RTP_NOTHREADSUPPORT.
 {
     (void) x;
     return ERR_RTP_NOTHREADSUPPORT;
 }
SetNoteTimeoutMultiplier()
void qrtplib::RTPSessionParams::SetNoteTimeoutMultiplier (double m) inline
Sets the multiplier to be used when timing out SDES NOTE information.
Definition at line 290 of file rtpsessionparams.h.
     {
         notemultiplier = m;
     }
SetOwnTimestampUnit()
void qrtplib::RTPSessionParams::SetOwnTimestampUnit (double tsunit) inline
Sets the timestamp unit for our own data. Sets the timestamp unit for our own data. The timestamp unit is defined as a time interval in seconds divided by the corresponding timestamp interval. For example, for 8000 Hz audio, the timestamp unit would typically be 1/8000. Since this value is initially set to an illegal value, the user must set this to an allowed value to be able to create a session.
Definition at line 120 of file rtpsessionparams.h.
Referenced by RTPSink::RTPSink().
     {
         owntsunit = tsunit;
     }
SetPredefinedSSRC()
void qrtplib::RTPSessionParams::SetPredefinedSSRC (uint32_t ssrc) inline
Sets the SSRC which will be used if RTPSessionParams::GetUsePredefinedSSRC returns true.
Definition at line 314 of file rtpsessionparams.h.
     {
         predefinedssrc = ssrc;
     }
SetReceiveMode()
void qrtplib::RTPSessionParams::SetReceiveMode (RTPTransmitter::ReceiveMode recvmode) inline
Sets the receive mode to be used by the session.
Definition at line 103 of file rtpsessionparams.h.
     {
         receivemode = recvmode;
     }
SetRequestImmediateBYE()
void qrtplib::RTPSessionParams::SetRequestImmediateBYE (bool v) inline
If v is true, the session will send a BYE packet immediately if this is allowed.
Definition at line 214 of file rtpsessionparams.h.
     {
         immediatebye = v;
     }
SetResolveLocalHostname()
void qrtplib::RTPSessionParams::SetResolveLocalHostname (bool v) inline
Sets a flag indicating if a DNS lookup should be done to determine our hostname (to construct a CNAME item). If v is set to true, the session will ask the transmitter to find a host name based upon the IP addresses in its list of local IP addresses. If set to false, a call to gethostname or something similar will be used to find the local hostname. Note that the first method might take some time.
Definition at line 136 of file rtpsessionparams.h.
     {
         resolvehostname = v;
     }
SetSenderControlBandwidthFraction()
void qrtplib::RTPSessionParams::SetSenderControlBandwidthFraction (double frac) inline
Sets the minimum fraction of the control traffic that will be used by senders.
Definition at line 174 of file rtpsessionparams.h.
     {
         senderfrac = frac;
     }
SetSenderReportForBYE()
void qrtplib::RTPSessionParams::SetSenderReportForBYE (bool v) inline
When sending a BYE packet, this indicates whether it will be part of an RTCP compound packet that begins with a sender report (if allowed) or a receiver report.
Definition at line 228 of file rtpsessionparams.h.
     {
         SR_BYE = v;
     }
SetSenderTimeoutMultiplier()
void qrtplib::RTPSessionParams::SetSenderTimeoutMultiplier (double m) inline
Sets the multiplier to be used when timing out senders.
Definition at line 242 of file rtpsessionparams.h.
     {
         sendermultiplier = m;
     }
SetSessionBandwidth()
void qrtplib::RTPSessionParams::SetSessionBandwidth (double sessbw) inline
Sets the session bandwidth in bytes per second.
Definition at line 150 of file rtpsessionparams.h.
     {
         sessionbandwidth = sessbw;
     }
SetSourceTimeoutMultiplier()
void qrtplib::RTPSessionParams::SetSourceTimeoutMultiplier (double m) inline
Sets the multiplier to be used when timing out members.
Definition at line 254 of file rtpsessionparams.h.
     {
         generaltimeoutmultiplier = m;
     }
SetUseHalfRTCPIntervalAtStartup()
void qrtplib::RTPSessionParams::SetUseHalfRTCPIntervalAtStartup (bool usehalf) inline
If usehalf is set to true, the session will only wait half of the calculated RTCP interval before sending its first RTCP packet.
Definition at line 200 of file rtpsessionparams.h.
     {
         usehalfatstartup = usehalf;
     }
SetUsePollThread()
int qrtplib::RTPSessionParams::SetUsePollThread (bool usethread)
If usethread is true, the session will use a poll thread to automatically process incoming data and to send RTCP packets when necessary.
Definition at line 70 of file rtpsessionparams.cpp.
References ERR_RTP_NOTHREADSUPPORT.
 {
     (void) usethread;
     return ERR_RTP_NOTHREADSUPPORT;
 }
SetUsePredefinedSSRC()
void qrtplib::RTPSessionParams::SetUsePredefinedSSRC (bool f) inline
Sets a flag which indicates if a predefined SSRC identifier should be used.
Definition at line 302 of file rtpsessionparams.h.
     {
         usepredefinedssrc = f;
     }
Member Data Documentation
acceptown
bool qrtplib::RTPSessionParams::acceptown private
Definition at line 343 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
byetimeoutmultiplier
double qrtplib::RTPSessionParams::byetimeoutmultiplier private
Definition at line 360 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
cname
std::string qrtplib::RTPSessionParams::cname private
Definition at line 367 of file rtpsessionparams.h.
collisionmultiplier
double qrtplib::RTPSessionParams::collisionmultiplier private
Definition at line 361 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
controlfrac
double qrtplib::RTPSessionParams::controlfrac private
Definition at line 351 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
generaltimeoutmultiplier
double qrtplib::RTPSessionParams::generaltimeoutmultiplier private
Definition at line 359 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
immediatebye
bool qrtplib::RTPSessionParams::immediatebye private
Definition at line 355 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
m_needThreadSafety
bool qrtplib::RTPSessionParams::m_needThreadSafety private
Definition at line 368 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
maxpacksize
std::size_t qrtplib::RTPSessionParams::maxpacksize private
Definition at line 345 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
mininterval
RTPTime qrtplib::RTPSessionParams::mininterval private
Definition at line 353 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
notemultiplier
double qrtplib::RTPSessionParams::notemultiplier private
Definition at line 362 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
owntsunit
double qrtplib::RTPSessionParams::owntsunit private
Definition at line 346 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
predefinedssrc
uint32_t qrtplib::RTPSessionParams::predefinedssrc private
Definition at line 365 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
receivemode
RTPTransmitter::ReceiveMode qrtplib::RTPSessionParams::receivemode private
Definition at line 347 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
resolvehostname
bool qrtplib::RTPSessionParams::resolvehostname private
Definition at line 348 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
senderfrac
double qrtplib::RTPSessionParams::senderfrac private
Definition at line 352 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
sendermultiplier
double qrtplib::RTPSessionParams::sendermultiplier private
Definition at line 358 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
sessionbandwidth
double qrtplib::RTPSessionParams::sessionbandwidth private
Definition at line 350 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
SR_BYE
bool qrtplib::RTPSessionParams::SR_BYE private
Definition at line 356 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
usehalfatstartup
bool qrtplib::RTPSessionParams::usehalfatstartup private
Definition at line 354 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
usepollthread
bool qrtplib::RTPSessionParams::usepollthread private
Definition at line 344 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
usepredefinedssrc
bool qrtplib::RTPSessionParams::usepredefinedssrc private
Definition at line 364 of file rtpsessionparams.h.
Referenced by RTPSessionParams().
The documentation for this class was generated from the following files:
qrtplib/rtpsessionparams.h
qrtplib/rtpsessionparams.cpp