SDRAngel: LoggingDialog Class Reference
LoggingDialog Class Reference
#include <loggingdialog.h>
Inherits QDialog.
Public Member Functions
LoggingDialog (MainSettings &mainSettings, QWidget *parent=0)
~LoggingDialog ()
Private Slots
void accept ()
void on_showFileDialog_clicked (bool checked)
Private Member Functions
QtMsgType msgLevelFromIndex (int intMsgLevel)
int msgLevelToIndex (const QtMsgType &msgLevel)
Private Attributes
Ui::LoggingDialog * ui
MainSettings & m_mainSettings
QString m_fileName
Detailed Description
Definition at line 30 of file loggingdialog.h.
Constructor & Destructor Documentation
LoggingDialog()
LoggingDialog::LoggingDialog (MainSettings & mainSettings, QWidget * parent = 0) explicit
Definition at line 24 of file loggingdialog.cpp.
References MainSettings::getConsoleMinLogLevel(), MainSettings::getFileMinLogLevel(), MainSettings::getLogFileName(), MainSettings::getUseLogFile(), m_fileName, m_mainSettings, msgLevelToIndex(), and ui.
                                                                         :
     QDialog(parent),
     ui(new Ui::LoggingDialog),
     m_mainSettings(mainSettings)
 {
     ui->setupUi(this);
     ui->consoleLevel->setCurrentIndex(msgLevelToIndex(m_mainSettings.getConsoleMinLogLevel()));
     ui->fileLevel->setCurrentIndex(msgLevelToIndex(m_mainSettings.getFileMinLogLevel()));
     ui->logToFile->setChecked(m_mainSettings.getUseLogFile());
     ui->logFileNameText->setText(m_mainSettings.getLogFileName());
     m_fileName = m_mainSettings.getLogFileName();
 }
~LoggingDialog()
LoggingDialog::~LoggingDialog ()
Definition at line 37 of file loggingdialog.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
accept
void LoggingDialog::accept () private slot
Definition at line 42 of file loggingdialog.cpp.
References m_fileName, m_mainSettings, msgLevelFromIndex(), MainSettings::setConsoleMinLogLevel(), MainSettings::setFileMinLogLevel(), MainSettings::setLogFileName(), MainSettings::setUseLogFile(), and ui.
 {
     m_mainSettings.setConsoleMinLogLevel(msgLevelFromIndex(ui->consoleLevel->currentIndex()));
     m_mainSettings.setFileMinLogLevel(msgLevelFromIndex(ui->fileLevel->currentIndex()));
     m_mainSettings.setUseLogFile(ui->logToFile->isChecked());
     m_mainSettings.setLogFileName(m_fileName);
     QDialog::accept();
 }
msgLevelFromIndex()
QtMsgType LoggingDialog::msgLevelFromIndex (int intMsgLevel) private
Definition at line 65 of file loggingdialog.cpp.
Referenced by accept().
 {
     switch (intMsgLevel)
     {
         case 0:
             return QtDebugMsg;
             break;
         case 1:
             return QtInfoMsg;
             break;
         case 2:
             return QtWarningMsg;
             break;
         case 3:
             return QtCriticalMsg;
             break;
         default:
             return QtDebugMsg;
             break;
     }
 }
msgLevelToIndex()
int LoggingDialog::msgLevelToIndex (const QtMsgType & msgLevel) private
Definition at line 87 of file loggingdialog.cpp.
Referenced by LoggingDialog().
 {
     switch (msgLevel)
     {
         case QtDebugMsg:
             return 0;
             break;
         case QtInfoMsg:
             return 1;
             break;
         case QtWarningMsg:
             return 2;
             break;
         case QtCriticalMsg:
         case QtFatalMsg:
             return 3;
             break;
         default:
             return 0;
             break;
     }
 }
on_showFileDialog_clicked
void LoggingDialog::on_showFileDialog_clicked (bool checked) private slot
Definition at line 51 of file loggingdialog.cpp.
References m_fileName, and ui.
 {
     (void) checked;
     QString fileName = QFileDialog::getSaveFileName(this,
         tr("Save log file"), ".", tr("Log Files (*.log)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "")
     {
         qDebug("LoggingDialog::on_showFileDialog_clicked: selected: %s", qPrintable(fileName));
         m_fileName = fileName;
         ui->logFileNameText->setText(fileName);
     }
 }
Member Data Documentation
m_fileName
QString LoggingDialog::m_fileName private
Definition at line 39 of file loggingdialog.h.
Referenced by accept(), LoggingDialog(), and on_showFileDialog_clicked().
m_mainSettings
MainSettings& LoggingDialog::m_mainSettings private
Definition at line 38 of file loggingdialog.h.
Referenced by accept(), and LoggingDialog().
ui
Ui::LoggingDialog* LoggingDialog::ui private
Definition at line 37 of file loggingdialog.h.
Referenced by accept(), LoggingDialog(), on_showFileDialog_clicked(), and ~LoggingDialog().
The documentation for this class was generated from the following files:
sdrgui/gui/loggingdialog.h
sdrgui/gui/loggingdialog.cpp