SDRAngel: MovingAverage< Type > Class Template Reference
MovingAverage< Type > Class Template Reference
#include <movingaverage.h>
Public Member Functions
MovingAverage (int historySize, Type initial)
void resize (int historySize, Type initial)
void feed (Type value)
void fill (Type value)
Type average () const
Type sum () const
int historySize () const
Protected Attributes
std::vector< Type > m_history
Type m_sum
uint32_t m_index
Detailed Description
template<typename Type>
class MovingAverage< Type >
Definition at line 9 of file movingaverage.h.
Constructor & Destructor Documentation
MovingAverage()
template<typename Type> MovingAverage< Type >::MovingAverage (int historySize, Type initial) inline
Definition at line 11 of file movingaverage.h.
                                                  : m_index(0)
     {
         resize(historySize, initial);
     }
Member Function Documentation
average()
template<typename Type> Type MovingAverage< Type >::average () const inline
Definition at line 43 of file movingaverage.h.
Referenced by UDPSink::feed(), MagAGC::feedAndGetValue(), AGC::getAverage(), UDPSource::modulateSample(), UDPSource::pull(), and UDPSinkGUI::tick().
     {
         return m_sum / (Type) m_history.size();
     }
feed()
template<typename Type> void MovingAverage< Type >::feed (Type value) inline
Definition at line 24 of file movingaverage.h.
Referenced by UDPSink::feed(), MagAGC::feedAndGetValue(), UDPSource::modulateSample(), UDPSource::pull(), and UDPSinkGUI::tick().
     {
         Type& oldest = m_history[m_index];
         m_sum += value - oldest;
         oldest = value;
         if (m_index < m_history.size() - 1) {
             m_index++;
         } else {
             m_index = 0;
         }
     }
fill()
template<typename Type> void MovingAverage< Type >::fill (Type value) inline
Definition at line 37 of file movingaverage.h.
Referenced by MagAGC::resize(), and MagAGC::setOrder().
     {
         std::fill(m_history.begin(), m_history.end(), value);
         m_sum = (Type) m_history.size() * value;
     }
historySize()
template<typename Type> int MovingAverage< Type >::historySize () const inline
Definition at line 53 of file movingaverage.h.
     {
         return m_history.size();
     }
resize()
template<typename Type> void MovingAverage< Type >::resize (int historySize, Type initial) inline
Definition at line 16 of file movingaverage.h.
Referenced by UDPSink::applySettings(), UDPSource::applySettings(), MovingAverage< double >::MovingAverage(), and AGC::resize().
     {
         m_history.resize(historySize);
         std::fill(m_history.begin(), m_history.end(), initial);
         m_sum = (Type) m_history.size() * initial;
         m_index = 0;
     }
sum()
template<typename Type> Type MovingAverage< Type >::sum () const inline
Definition at line 48 of file movingaverage.h.
     {
         return m_sum;
     }
Member Data Documentation
m_history
template<typename Type> std::vector<Type> MovingAverage< Type >::m_history protected
Definition at line 59 of file movingaverage.h.
Referenced by MovingAverage< double >::average(), MovingAverage< double >::feed(), MovingAverage< double >::fill(), MovingAverage< double >::historySize(), and MovingAverage< double >::resize().
m_index
template<typename Type> uint32_t MovingAverage< Type >::m_index protected
Definition at line 61 of file movingaverage.h.
Referenced by MovingAverage< double >::feed(), and MovingAverage< double >::resize().
m_sum
template<typename Type> Type MovingAverage< Type >::m_sum protected
Definition at line 60 of file movingaverage.h.
Referenced by MovingAverage< double >::average(), MovingAverage< double >::feed(), MovingAverage< double >::fill(), MovingAverage< double >::resize(), and MovingAverage< double >::sum().
The documentation for this class was generated from the following file:
sdrbase/dsp/movingaverage.h