SDRAngel: FCDProPlusThread Class Reference
FCDProPlusThread Class Reference
#include <fcdproplusthread.h>
Inherits QThread.
Public Member Functions
FCDProPlusThread (SampleSinkFifo *sampleFifo, AudioFifo *fcdFIFO, QObject *parent=nullptr)
~FCDProPlusThread ()
void startWork ()
void stopWork ()
void setLog2Decimation (unsigned int log2_decim)
void setFcPos (int fcPos)
Private Member Functions
void run ()
void work (unsigned int n_items)
Private Attributes
AudioFifo * m_fcdFIFO
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
bool m_running
unsigned int m_log2Decim
int m_fcPos
qint16 m_buf [fcd_traits< ProPlus >::convBufSize *2]
SampleVector m_convertBuffer
SampleSinkFifo * m_sampleFifo
Decimators< qint32, qint16, SDR_RX_SAMP_SZ, 16 > m_decimators
Detailed Description
Definition at line 32 of file fcdproplusthread.h.
Constructor & Destructor Documentation
FCDProPlusThread()
FCDProPlusThread::FCDProPlusThread (SampleSinkFifo * sampleFifo, AudioFifo * fcdFIFO, QObject * parent = nullptr)
Definition at line 29 of file fcdproplusthread.cpp.
                                                                                                   :
     QThread(parent),
     m_fcdFIFO(fcdFIFO),
     m_running(false),
     m_log2Decim(0),
     m_fcPos(2),
     m_convertBuffer(fcd_traits<ProPlus>::convBufSize), // nb samples
     m_sampleFifo(sampleFifo)
 {
     start();
 }
~FCDProPlusThread()
FCDProPlusThread::~FCDProPlusThread ()
Definition at line 41 of file fcdproplusthread.cpp.
 {
 }
Member Function Documentation
run()
void FCDProPlusThread::run () private
Definition at line 75 of file fcdproplusthread.cpp.
References m_running, and work().
 {
     m_running = true;
     qDebug("FCDThread::run: start running loop");
     while (m_running)
     {
         work(fcd_traits<ProPlus>::convBufSize);
         std::this_thread::sleep_for(std::chrono::microseconds(100));
     }
     qDebug("FCDThread::run: running loop stopped");
     m_running = false;
 }
setFcPos()
void FCDProPlusThread::setFcPos (int fcPos)
Definition at line 70 of file fcdproplusthread.cpp.
References m_fcPos.
Referenced by FCDProPlusInput::applySettings().
 {
     m_fcPos = fcPos;
 }
setLog2Decimation()
void FCDProPlusThread::setLog2Decimation (unsigned int log2_decim)
Definition at line 65 of file fcdproplusthread.cpp.
References m_log2Decim.
Referenced by FCDProPlusInput::applySettings().
 {
     m_log2Decim = log2_decim;
 }
startWork()
void FCDProPlusThread::startWork ()
Definition at line 45 of file fcdproplusthread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by FCDProPlusInput::start().
 {
     m_startWaitMutex.lock();
     start();
     while(!m_running)
     {
         m_startWaiter.wait(&m_startWaitMutex, 100);
     }
     m_startWaitMutex.unlock();
 }
stopWork()
void FCDProPlusThread::stopWork ()
Definition at line 59 of file fcdproplusthread.cpp.
References m_running.
Referenced by FCDProPlusInput::stop().
 {
     m_running = false;
     wait();
 }
work()
void FCDProPlusThread::work (unsigned int n_items) private
Definition at line 90 of file fcdproplusthread.cpp.
References Decimators< StorageType, T, SdrBits, InputBits >::decimate1(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate16_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate2_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate32_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate4_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate64_sup(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_cen(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_inf(), Decimators< StorageType, T, SdrBits, InputBits >::decimate8_sup(), m_buf, m_convertBuffer, m_decimators, m_fcdFIFO, m_fcPos, m_log2Decim, m_sampleFifo, AudioFifo::read(), and SampleSinkFifo::write().
Referenced by run().
 {
     uint32_t nbRead = m_fcdFIFO->read((unsigned char *) m_buf, n_items); // number of samples
     SampleVector::iterator it = m_convertBuffer.begin();
     if (m_log2Decim == 0)
     {
         m_decimators.decimate1(&it, m_buf, 2*nbRead);
     }
     else
     {
         if (m_fcPos == 0) // Infradyne
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_inf(&it, m_buf, 2*nbRead);
                 break;
             case 2:
                 m_decimators.decimate4_inf(&it, m_buf, 2*nbRead);
                 break;
             case 3:
                 m_decimators.decimate8_inf(&it, m_buf, 2*nbRead);
                 break;
             case 4:
                 m_decimators.decimate16_inf(&it, m_buf, 2*nbRead);
                 break;
             case 5:
                 m_decimators.decimate32_inf(&it, m_buf, 2*nbRead);
                 break;
             case 6:
                 m_decimators.decimate64_inf(&it, m_buf, 2*nbRead);
                 break;
             default:
                 break;
             }
         }
         else if (m_fcPos == 1) // Supradyne
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_sup(&it, m_buf, 2*nbRead);
                 break;
             case 2:
                 m_decimators.decimate4_sup(&it, m_buf, 2*nbRead);
                 break;
             case 3:
                 m_decimators.decimate8_sup(&it, m_buf, 2*nbRead);
                 break;
             case 4:
                 m_decimators.decimate16_sup(&it, m_buf, 2*nbRead);
                 break;
             case 5:
                 m_decimators.decimate32_sup(&it, m_buf, 2*nbRead);
                 break;
             case 6:
                 m_decimators.decimate64_sup(&it, m_buf, 2*nbRead);
                 break;
             default:
                 break;
             }
         }
         else // Centered
         {
             switch (m_log2Decim)
             {
             case 1:
                 m_decimators.decimate2_cen(&it, m_buf, 2*nbRead);
                 break;
             case 2:
                 m_decimators.decimate4_cen(&it, m_buf, 2*nbRead);
                 break;
             case 3:
                 m_decimators.decimate8_cen(&it, m_buf, 2*nbRead);
                 break;
             case 4:
                 m_decimators.decimate16_cen(&it, m_buf, 2*nbRead);
                 break;
             case 5:
                 m_decimators.decimate32_cen(&it, m_buf, 2*nbRead);
                 break;
             case 6:
                 m_decimators.decimate64_cen(&it, m_buf, 2*nbRead);
                 break;
             default:
                 break;
             }
         }
     }
     m_sampleFifo->write(m_convertBuffer.begin(), it);
 }
Member Data Documentation
m_buf
qint16 FCDProPlusThread::m_buf[fcd_traits< ProPlus >::convBufSize *2] private
Definition at line 53 of file fcdproplusthread.h.
Referenced by work().
m_convertBuffer
SampleVector FCDProPlusThread::m_convertBuffer private
Definition at line 54 of file fcdproplusthread.h.
Referenced by work().
m_decimators
Decimators<qint32, qint16, SDR_RX_SAMP_SZ, 16> FCDProPlusThread::m_decimators private
Definition at line 56 of file fcdproplusthread.h.
Referenced by work().
m_fcdFIFO
AudioFifo* FCDProPlusThread::m_fcdFIFO private
Definition at line 45 of file fcdproplusthread.h.
Referenced by work().
m_fcPos
int FCDProPlusThread::m_fcPos private
Definition at line 51 of file fcdproplusthread.h.
Referenced by setFcPos(), and work().
m_log2Decim
unsigned int FCDProPlusThread::m_log2Decim private
Definition at line 50 of file fcdproplusthread.h.
Referenced by setLog2Decimation(), and work().
m_running
bool FCDProPlusThread::m_running private
Definition at line 49 of file fcdproplusthread.h.
Referenced by run(), startWork(), and stopWork().
m_sampleFifo
SampleSinkFifo* FCDProPlusThread::m_sampleFifo private
Definition at line 55 of file fcdproplusthread.h.
Referenced by work().
m_startWaiter
QWaitCondition FCDProPlusThread::m_startWaiter private
Definition at line 48 of file fcdproplusthread.h.
Referenced by startWork().
m_startWaitMutex
QMutex FCDProPlusThread::m_startWaitMutex private
Definition at line 47 of file fcdproplusthread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/samplesource/fcdproplus/fcdproplusthread.h
plugins/samplesource/fcdproplus/fcdproplusthread.cpp