SDRAngel: DeviceSoapySDR Class Reference
DeviceSoapySDR Class Reference
#include <devicesoapysdr.h>
Public Member Functions
SoapySDR::Device * openSoapySDR (uint32_t sequence, const QString &hardwareUserArguments)
void closeSoapySdr (SoapySDR::Device *device)
uint32_t getNbDevices () const
const std::vector< DeviceSoapySDRScan::SoapySDRDeviceEnum > & getDevicesEnumeration () const
Static Public Member Functions
static DeviceSoapySDR & instance ()
Static Public Attributes
static const unsigned int blockSize = (1<<14)
Protected Member Functions
DeviceSoapySDR ()
DeviceSoapySDR (const DeviceSoapySDR &)
DeviceSoapySDR & operator= (const DeviceSoapySDR &other)
~DeviceSoapySDR ()
Private Member Functions
SoapySDR::Device * openopenSoapySDRFromSequence (uint32_t sequence, const QString &hardwareUserArguments)
Private Attributes
DeviceSoapySDRScan m_scanner
Detailed Description
Definition at line 27 of file devicesoapysdr.h.
Constructor & Destructor Documentation
DeviceSoapySDR() [1/2]
DeviceSoapySDR::DeviceSoapySDR () protected
Definition at line 21 of file devicesoapysdr.cpp.
References m_scanner, and DeviceSoapySDRScan::scan().
 {
     m_scanner.scan();
 }
DeviceSoapySDR() [2/2]
DeviceSoapySDR::DeviceSoapySDR (const DeviceSoapySDR &) inline protected
Definition at line 41 of file devicesoapysdr.h.
 {}
~DeviceSoapySDR()
DeviceSoapySDR::~DeviceSoapySDR () protected
Definition at line 26 of file devicesoapysdr.cpp.
 {}
Member Function Documentation
closeSoapySdr()
void DeviceSoapySDR::closeSoapySdr (SoapySDR::Device * device)
Definition at line 41 of file devicesoapysdr.cpp.
Referenced by SoapySDROutput::closeDevice(), and SoapySDRInput::closeDevice().
 {
     SoapySDR::Device::unmake(device);
 }
getDevicesEnumeration()
const std::vector<DeviceSoapySDRScan::SoapySDRDeviceEnum>& DeviceSoapySDR::getDevicesEnumeration () const inline
Definition at line 35 of file devicesoapysdr.h.
Referenced by SoapySDROutputPlugin::enumSampleSinks(), and SoapySDRInputPlugin::enumSampleSources().
 { return m_scanner.getDevicesEnumeration(); }
getNbDevices()
uint32_t DeviceSoapySDR::getNbDevices () const inline
Definition at line 34 of file devicesoapysdr.h.
 { return m_scanner.getNbDevices(); }
instance()
DeviceSoapySDR & DeviceSoapySDR::instance () static
Definition at line 29 of file devicesoapysdr.cpp.
Referenced by SoapySDROutput::closeDevice(), SoapySDRInput::closeDevice(), SoapySDROutputPlugin::enumSampleSinks(), SoapySDRInputPlugin::enumSampleSources(), SoapySDROutput::openDevice(), SoapySDRInput::openDevice(), and openSoapySDR().
 {
     static DeviceSoapySDR inst;
     return inst;
 }
openopenSoapySDRFromSequence()
SoapySDR::Device * DeviceSoapySDR::openopenSoapySDRFromSequence (uint32_t sequence, const QString & hardwareUserArguments) private
Definition at line 46 of file devicesoapysdr.cpp.
References DeviceSoapySDRScan::getDevicesEnumeration(), DeviceSoapySDRScan::getNbDevices(), i, DeviceSoapySDRScan::SoapySDRDeviceEnum::m_driverName, DeviceSoapySDRScan::SoapySDRDeviceEnum::m_idKey, DeviceSoapySDRScan::SoapySDRDeviceEnum::m_idValue, DeviceSoapySDRScan::SoapySDRDeviceEnum::m_label, and m_scanner.
Referenced by openSoapySDR().
 {
     if (sequence > m_scanner.getNbDevices())
     {
         return 0;
     }
     else
     {
         const DeviceSoapySDRScan::SoapySDRDeviceEnum& deviceEnum = m_scanner.getDevicesEnumeration()[sequence];
         try
         {
             SoapySDR::Kwargs kwargs;
             kwargs["driver"] = deviceEnum.m_driverName.toStdString();
             if (hardwareUserArguments.size() > 0)
             {
                 QStringList kvArgs = hardwareUserArguments.split(',');
                 for (int i = 0; i < kvArgs.size(); i++)
                 {
                     QStringList kv = kvArgs.at(i).split('=');
                     if (kv.size() > 1) {
                         kwargs[kv.at(0).toStdString()] = kv.at(1).toStdString();
                     }
                 }
             }
             else if (deviceEnum.m_idKey.size() > 0)
             {
                 kwargs[deviceEnum.m_idKey.toStdString()] = deviceEnum.m_idValue.toStdString();
             }
             SoapySDR::Kwargs::const_iterator it = kwargs.begin();
             for (; it != kwargs.end(); ++it) {
                 qDebug("DeviceSoapySDR::openopenSoapySDRFromSequence: %s=%s", it->first.c_str(), it->second.c_str());
             }
             SoapySDR::Device *device = SoapySDR::Device::make(kwargs);
             return device;
         }
         catch (const std::exception &ex)
         {
             qWarning("DeviceSoapySDR::openopenSoapySDRFromSequence: %s cannot be opened: %s",
                     deviceEnum.m_label.toStdString().c_str(), ex.what());
             return 0;
         }
     }
 }
openSoapySDR()
SoapySDR::Device * DeviceSoapySDR::openSoapySDR (uint32_t sequence, const QString & hardwareUserArguments)
Definition at line 35 of file devicesoapysdr.cpp.
References instance(), and openopenSoapySDRFromSequence().
Referenced by SoapySDROutput::openDevice(), and SoapySDRInput::openDevice().
 {
     instance();
     return openopenSoapySDRFromSequence(sequence, hardwareUserArguments);
 }
operator=()
DeviceSoapySDR& DeviceSoapySDR::operator= (const DeviceSoapySDR & other) inline protected
Definition at line 42 of file devicesoapysdr.h.
 { (void) other; return *this; }
Member Data Documentation
blockSize
const unsigned int DeviceSoapySDR::blockSize = (1<<14) static
Definition at line 37 of file devicesoapysdr.h.
m_scanner
DeviceSoapySDRScan DeviceSoapySDR::m_scanner private
Definition at line 47 of file devicesoapysdr.h.
Referenced by DeviceSoapySDR(), and openopenSoapySDRFromSequence().
The documentation for this class was generated from the following files:
devices/soapysdr/devicesoapysdr.h
devices/soapysdr/devicesoapysdr.cpp