SDRAngel: DATVDemodGUI Class Reference
DATVDemodGUI Class Reference
#include <datvdemodgui.h>
Public Member Functions
virtual void destroy ()
void setName (const QString &strName)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 intCenterFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &arrData)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &objMessage)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static DATVDemodGUI * create (PluginAPI *objPluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
Static Public Attributes
static const QString m_strChannelID = "sdrangel.channel.demoddatv"
Private Slots
void channelMarkerChangedByCursor ()
void channelMarkerHighlightedByCursor ()
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDoubleClicked ()
void handleInputMessages ()
void audioSelect ()
void tick ()
void on_cmbStandard_currentIndexChanged (int index)
void on_cmbModulation_currentIndexChanged (const QString &arg1)
void on_cmbFEC_currentIndexChanged (const QString &arg1)
void on_chkViterbi_clicked ()
void on_chkHardMetric_clicked ()
void on_resetDefaults_clicked ()
void on_spiSymbolRate_valueChanged (int arg1)
void on_spiNotchFilters_valueChanged (int arg1)
void on_chkAllowDrift_clicked ()
void on_fullScreen_clicked ()
void on_mouseEvent (QMouseEvent *obj)
void on_StreamDataAvailable (int *intPackets, int *intBytes, int *intPercent, qint64 *intTotalReceived)
void on_StreamMetaDataChanged (DataTSMetaData2 *objMetaData)
void on_chkFastlock_clicked ()
void on_cmbFilter_currentIndexChanged (int index)
void on_spiRollOff_valueChanged (int arg1)
void on_spiExcursion_valueChanged (int arg1)
void on_deltaFrequency_changed (qint64 value)
void on_rfBandwidth_changed (qint64 value)
void on_audioMute_toggled (bool checked)
void on_audioVolume_valueChanged (int value)
void on_videoMute_toggled (bool checked)
void on_udpTS_clicked (bool checked)
void on_udpTSAddress_editingFinished ()
void on_udpTSPort_editingFinished ()
Private Member Functions
DATVDemodGUI (PluginAPI *objPluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *objParent=0)
virtual ~DATVDemodGUI ()
void blockApplySettings (bool blnBlock)
void applySettings (bool force=false)
void displaySettings ()
void displaySystemConfiguration ()
QString formatBytes (qint64 intBytes)
void displayRRCParameters (bool blnVisible)
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::DATVDemodGUI * ui
PluginAPI * m_objPluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_objChannelMarker
ThreadedBasebandSampleSink * m_objThreadedChannelizer
DownChannelizer * m_objChannelizer
DATVDemod * m_objDATVDemod
MessageQueue m_inputMessageQueue
int m_intCenterFrequency
DATVDemodSettings m_settings
QTimer m_objTimer
qint64 m_intPreviousDecodedData
qint64 m_intLastDecodedData
qint64 m_intLastSpeed
int m_intReadyDecodedData
bool m_blnBasicSettingsShown
bool m_blnDoApplySettings
bool m_blnButtonPlayClicked
int m_modcodModulationIndex
int m_modcodCodeRateIndex
bool m_cstlnSetByModcod
MovingAverageUtil< double, double, 4 > m_objMagSqAverage
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 43 of file datvdemodgui.h.
Constructor & Destructor Documentation
DATVDemodGUI()
DATVDemodGUI::DATVDemodGUI (PluginAPI * objPluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * objParent = 0) explicit private
Definition at line 159 of file datvdemodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), arg(), audioSelect(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), getInputMessageQueue(), ColorMapper::GrayGold, ColorMapper::GrayYellow, handleInputMessages(), DATVDemod::m_channelIdURI, m_deviceUISet, m_intLastDecodedData, m_intLastSpeed, m_intPreviousDecodedData, m_intReadyDecodedData, m_objChannelMarker, m_objDATVDemod, m_objTimer, on_StreamDataAvailable(), on_StreamMetaDataChanged(), DATVideostream::onDataPackets(), DATVideoRender::onMetaDataChanged(), onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), resetToDefaults(), ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), BasebandSampleSink::setMessageQueueToGUI(), DATVDemod::SetTVScreen(), DATVDemod::SetVideoRender(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                                :
         RollupWidget(objParent),
         ui(new Ui::DATVDemodGUI),
         m_objPluginAPI(objPluginAPI),
         m_deviceUISet(deviceUISet),
         m_objChannelMarker(this),
         m_blnBasicSettingsShown(false),
         m_blnDoApplySettings(true),
         m_modcodModulationIndex(-1),
         m_modcodCodeRateIndex(-1),
         m_cstlnSetByModcod(false)
 {
     ui->setupUi(this);
     ui->screenTV->setColor(true);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
     m_objDATVDemod = (DATVDemod*) rxChannel;
     m_objDATVDemod->setMessageQueueToGUI(getInputMessageQueue());
     m_objDATVDemod->SetTVScreen(ui->screenTV);
     connect(m_objDATVDemod->SetVideoRender(ui->screenTV_2), &DATVideostream::onDataPackets, this, &DATVDemodGUI::on_StreamDataAvailable);
     connect(ui->screenTV_2, &DATVideoRender::onMetaDataChanged, this, &DATVDemodGUI::on_StreamMetaDataChanged);
     m_intPreviousDecodedData=0;
     m_intLastDecodedData=0;
     m_intLastSpeed=0;
     m_intReadyDecodedData=0;
     m_objTimer.setInterval(1000);
     connect(&m_objTimer, SIGNAL(timeout()), this, SLOT(tick()));
     m_objTimer.start();
     ui->fullScreen->setVisible(false);
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     ui->rfBandwidth->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     ui->rfBandwidth->setValueRange(true, 7, 0, 9999999);
     m_objChannelMarker.blockSignals(true);
     m_objChannelMarker.setColor(Qt::magenta);
     m_objChannelMarker.setBandwidth(6000000);
     m_objChannelMarker.setCenterFrequency(0);
     m_objChannelMarker.blockSignals(false);
     m_objChannelMarker.setVisible(true);
     connect(&m_objChannelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(&m_objChannelMarker, SIGNAL(highlightedByCursor()), this, SLOT(channelMarkerHighlightedByCursor()));
     m_deviceUISet->registerRxChannelInstance(DATVDemod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_objChannelMarker);
     m_deviceUISet->addRollupWidget(this);
     // QPixmap pixmapTarget = QPixmap(":/film.png");
     // pixmapTarget = pixmapTarget.scaled(16, 16, Qt::KeepAspectRatio, Qt::SmoothTransformation);
     // ui->videoPlay->setAlignment(Qt::AlignCenter);
     // ui->videoPlay->setPixmap(pixmapTarget);
     CRightClickEnabler *audioMuteRightClickEnabler = new CRightClickEnabler(ui->audioMute);
     connect(audioMuteRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioSelect()));
     resetToDefaults(); // does applySettings()
 }
~DATVDemodGUI()
DATVDemodGUI::~DATVDemodGUI () private virtual
Definition at line 228 of file datvdemodgui.cpp.
References m_deviceUISet, m_objDATVDemod, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_objDATVDemod;
     delete ui;
 }
Member Function Documentation
applySettings()
void DATVDemodGUI::applySettings (bool force = false) private
Definition at line 348 of file datvdemodgui.cpp.
References DATVDemod::MsgConfigureChannelizer::create(), DATVDemod::MsgConfigureDATVDemod::create(), DATVDemodSettings::debug(), ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasebandSampleSink::getInputMessageQueue(), m_blnDoApplySettings, m_objChannelMarker, m_objDATVDemod, m_settings, MessageQueue::push(), and RollupWidget::setTitleColor().
Referenced by audioSelect(), channelMarkerChangedByCursor(), deserialize(), on_audioMute_toggled(), on_audioVolume_valueChanged(), on_chkAllowDrift_clicked(), on_chkFastlock_clicked(), on_chkHardMetric_clicked(), on_chkViterbi_clicked(), on_cmbFEC_currentIndexChanged(), on_cmbFilter_currentIndexChanged(), on_cmbModulation_currentIndexChanged(), on_cmbStandard_currentIndexChanged(), on_deltaFrequency_changed(), on_rfBandwidth_changed(), on_spiExcursion_valueChanged(), on_spiNotchFilters_valueChanged(), on_spiRollOff_valueChanged(), on_spiSymbolRate_valueChanged(), on_udpTS_clicked(), on_udpTSAddress_editingFinished(), on_udpTSPort_editingFinished(), on_videoMute_toggled(), resetToDefaults(), and setCenterFrequency().
 {
     if (m_blnDoApplySettings)
     {
         qDebug("DATVDemodGUI::applySettings");
         DATVDemod::MsgConfigureChannelizer *msgChan = DATVDemod::MsgConfigureChannelizer::create(m_objChannelMarker.getCenterFrequency());
         m_objDATVDemod->getInputMessageQueue()->push(msgChan);
         setTitleColor(m_objChannelMarker.getColor());
         QString msg = tr("DATVDemodGUI::applySettings: force: %1").arg(force ? "true" : "false");
         m_settings.debug(msg);
         DATVDemod::MsgConfigureDATVDemod* message = DATVDemod::MsgConfigureDATVDemod::create(m_settings, force);
         m_objDATVDemod->getInputMessageQueue()->push(message);
     }
 }
audioSelect
void DATVDemodGUI::audioSelect () private slot
Definition at line 381 of file datvdemodgui.cpp.
References applySettings(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, DATVDemodSettings::m_audioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by DATVDemodGUI().
 {
     qDebug("AMDemodGUI::audioSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName);
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_audioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
blockApplySettings()
void DATVDemodGUI::blockApplySettings (bool blnBlock) private
Definition at line 235 of file datvdemodgui.cpp.
References m_blnDoApplySettings.
Referenced by displaySettings(), enterEvent(), and leaveEvent().
 {
     m_blnDoApplySettings = !blnBlock;
 }
channelMarkerChangedByCursor
void DATVDemodGUI::channelMarkerChangedByCursor () private slot
Definition at line 132 of file datvdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_intCenterFrequency, m_objChannelMarker, and ui.
Referenced by DATVDemodGUI().
 {
     ui->deltaFrequency->setValue(m_objChannelMarker.getCenterFrequency());
     if(m_intCenterFrequency!=m_objChannelMarker.getCenterFrequency())
     {
         m_intCenterFrequency=m_objChannelMarker.getCenterFrequency();
         applySettings();
     }
 }
channelMarkerHighlightedByCursor
void DATVDemodGUI::channelMarkerHighlightedByCursor () private slot
Definition at line 143 of file datvdemodgui.cpp.
References ChannelMarker::getHighlighted(), m_objChannelMarker, and RollupWidget::setHighlighted().
Referenced by DATVDemodGUI().
 {
     setHighlighted(m_objChannelMarker.getHighlighted());
 }
create()
DATVDemodGUI * DATVDemodGUI::create (PluginAPI * objPluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) static
Definition at line 41 of file datvdemodgui.cpp.
References DATVDemodGUI().
Referenced by DATVDemodPlugin::createRxChannelGUI().
 {
     DATVDemodGUI* gui = new DATVDemodGUI(objPluginAPI, deviceUISet, rxChannel);
     return gui;
 }
deserialize()
bool DATVDemodGUI::deserialize (const QByteArray & arrData) virtual
Implements PluginInstanceGUI.
Definition at line 87 of file datvdemodgui.cpp.
References applySettings(), DATVDemodSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if (m_settings.deserialize(arrData))
     {
         displaySettings();
         applySettings(true);
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void DATVDemodGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 49 of file datvdemodgui.cpp.
 {
     delete this;
 }
displayRRCParameters()
void DATVDemodGUI::displayRRCParameters (bool blnVisible) private
Definition at line 675 of file datvdemodgui.cpp.
References ui.
Referenced by displaySettings(), and on_cmbFilter_currentIndexChanged().
 {
     ui->spiRollOff->setVisible(blnVisible);
     ui->spiExcursion->setVisible(blnVisible);
     ui->rollOffLabel->setVisible(blnVisible);
     ui->excursionLabel->setVisible(blnVisible);
 }
displaySettings()
void DATVDemodGUI::displaySettings () private
Definition at line 240 of file datvdemodgui.cpp.
References arg(), blockApplySettings(), displayRRCParameters(), displaySystemConfiguration(), DATVDemodSettings::m_allowDrift, DATVDemodSettings::m_audioMute, DATVDemodSettings::m_audioVolume, DATVDemodSettings::m_centerFrequency, DATVDemodSettings::m_excursion, DATVDemodSettings::m_fastLock, DATVDemodSettings::m_filter, DATVDemodSettings::m_hardMetric, DATVDemodSettings::m_notchFilters, m_objChannelMarker, DATVDemodSettings::m_rfBandwidth, DATVDemodSettings::m_rgbColor, DATVDemodSettings::m_rollOff, m_settings, DATVDemodSettings::m_standard, DATVDemodSettings::m_symbolRate, DATVDemodSettings::m_udpTS, DATVDemodSettings::m_udpTSAddress, DATVDemodSettings::m_udpTSPort, DATVDemodSettings::m_videoMute, DATVDemodSettings::m_viterbi, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), and ui.
Referenced by deserialize(), and resetToDefaults().
 {
     m_objChannelMarker.blockSignals(true);
     blockApplySettings(true);
     m_objChannelMarker.setCenterFrequency(m_settings.m_centerFrequency);
     m_objChannelMarker.setBandwidth(m_settings.m_rfBandwidth);
     ui->deltaFrequency->setValue(m_settings.m_centerFrequency);
     m_objChannelMarker.setColor(m_settings.m_rgbColor);
     ui->chkAllowDrift->setChecked(m_settings.m_allowDrift);
     ui->chkHardMetric->setChecked(m_settings.m_hardMetric);
     ui->chkFastlock->setChecked(m_settings.m_fastLock);
     ui->chkViterbi->setChecked(m_settings.m_viterbi);
     if (m_settings.m_standard == DATVDemodSettings::dvb_version::DVB_S)
     {
         ui->chkAllowDrift->setEnabled(true);
         ui->chkHardMetric->setEnabled(true);
         ui->chkFastlock->setEnabled(true);
         ui->chkViterbi->setEnabled(true);
         ui->chkAllowDrift->setStyleSheet("QCheckBox { color: white }");
         ui->chkHardMetric->setStyleSheet("QCheckBox { color: white }");
         ui->chkFastlock->setStyleSheet("QCheckBox { color: white }");
         ui->chkViterbi->setStyleSheet("QCheckBox { color: white }");
     }
     else
     {
         ui->chkAllowDrift->setEnabled(false);
         ui->chkHardMetric->setEnabled(false);
         ui->chkFastlock->setEnabled(false);
         ui->chkViterbi->setEnabled(false);
         ui->chkAllowDrift->setStyleSheet("QCheckBox { color: gray }");
         ui->chkHardMetric->setStyleSheet("QCheckBox { color: gray }");
         ui->chkFastlock->setStyleSheet("QCheckBox { color: gray }");
         ui->chkViterbi->setStyleSheet("QCheckBox { color: gray }");
     }
     if (m_settings.m_standard == DATVDemodSettings::dvb_version::DVB_S) {
         ui->statusText->clear();
     }
     ui->cmbFilter->setCurrentIndex((int) m_settings.m_filter);
     displayRRCParameters(((int) m_settings.m_filter == 2));
     ui->spiRollOff->setValue((int) (m_settings.m_rollOff * 100.0f));
     ui->audioMute->setChecked(m_settings.m_audioMute);
     displaySystemConfiguration();
     ui->cmbStandard->setCurrentIndex((int) m_settings.m_standard);
     ui->spiNotchFilters->setValue(m_settings.m_notchFilters);
     ui->rfBandwidth->setValue(m_settings.m_rfBandwidth);
     ui->spiSymbolRate->setValue(m_settings.m_symbolRate);
     ui->spiExcursion->setValue(m_settings.m_excursion);
     ui->audioVolume->setValue(m_settings.m_audioVolume);
     ui->audioVolumeText->setText(tr("%1").arg(m_settings.m_audioVolume));
     ui->videoMute->setChecked(m_settings.m_videoMute);
     ui->udpTS->setChecked(m_settings.m_udpTS);
     ui->udpTSAddress->setText(m_settings.m_udpTSAddress);
     ui->udpTSPort->setText(tr("%1").arg(m_settings.m_udpTSPort));
     blockApplySettings(false);
     m_objChannelMarker.blockSignals(false);
 }
displaySystemConfiguration()
void DATVDemodGUI::displaySystemConfiguration () private
Definition at line 304 of file datvdemodgui.cpp.
References DATVDemodSettings::getAvailableCodeRates(), DATVDemodSettings::getAvailableModulations(), DATVDemodSettings::getStrFromCodeRate(), DATVDemodSettings::getStrFromModulation(), i, DATVDemodSettings::m_fec, DATVDemodSettings::m_modulation, m_settings, DATVDemodSettings::m_standard, and ui.
Referenced by displaySettings(), handleMessage(), on_cmbModulation_currentIndexChanged(), and on_cmbStandard_currentIndexChanged().
 {
     ui->cmbModulation->blockSignals(true);
     ui->cmbFEC->blockSignals(true);
     std::vector<DATVDemodSettings::DATVModulation> modulations;
     DATVDemodSettings::getAvailableModulations(m_settings.m_standard, modulations);
     std::vector<DATVDemodSettings::DATVCodeRate> codeRates;
     DATVDemodSettings::getAvailableCodeRates(m_settings.m_standard, m_settings.m_modulation, codeRates);
     ui->cmbModulation->clear();
     int modulationIndex = 0;
     int i;
     std::vector<DATVDemodSettings::DATVModulation>::const_iterator mIt = modulations.begin();
     for (i = 0; mIt != modulations.end(); ++mIt, i++)
     {
         ui->cmbModulation->addItem(DATVDemodSettings::getStrFromModulation(*mIt));
         if (m_settings.m_modulation == *mIt) {
             modulationIndex = i;
         }
     }
     ui->cmbFEC->clear();
     int rateIndex = 0;
     std::vector<DATVDemodSettings::DATVCodeRate>::const_iterator rIt = codeRates.begin();
     for (i = 0; rIt != codeRates.end(); ++rIt, i++)
     {
         ui->cmbFEC->addItem(DATVDemodSettings::getStrFromCodeRate(*rIt));
         if (m_settings.m_fec == *rIt) {
             rateIndex = i;
         }
     }
     ui->cmbModulation->setCurrentIndex(modulationIndex);
     ui->cmbFEC->setCurrentIndex(rateIndex);
     ui->cmbModulation->blockSignals(false);
     ui->cmbFEC->blockSignals(false);
 }
enterEvent()
void DATVDemodGUI::enterEvent (QEvent *) private
Definition at line 374 of file datvdemodgui.cpp.
References blockApplySettings(), m_objChannelMarker, and ChannelMarker::setHighlighted().
 {
     blockApplySettings(true);
     m_objChannelMarker.setHighlighted(true);
     blockApplySettings(false);
 }
formatBytes()
QString DATVDemodGUI::formatBytes (qint64 intBytes) private
Definition at line 572 of file datvdemodgui.cpp.
Referenced by on_StreamDataAvailable(), and tick().
 {
     if(intBytes<1024) {
         return QString("%1").arg(intBytes);
     } else if(intBytes<1024*1024) {
         return QString("%1 K").arg((float)(10*intBytes/1024)/10.0f);
     } else if(intBytes<1024*1024*1024) {
         return QString("%1 M").arg((float)(10*intBytes/(1024*1024))/10.0f);
     }
     return QString("%1 G").arg((float)(10*intBytes/(1024*1024*1024))/10.0f);
 }
getCenterFrequency()
qint64 DATVDemodGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 64 of file datvdemodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_objChannelMarker.
 {
     return m_objChannelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* DATVDemodGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 60 of file datvdemodgui.h.
Referenced by DATVDemodGUI(), and handleInputMessages().
 { return &m_inputMessageQueue; }
getName()
QString DATVDemodGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 59 of file datvdemodgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void DATVDemodGUI::handleInputMessages () private slot
Definition at line 119 of file datvdemodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by DATVDemodGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
bool DATVDemodGUI::handleMessage (const Message & objMessage) virtual
Implements PluginInstanceGUI.
Definition at line 102 of file datvdemodgui.cpp.
References displaySystemConfiguration(), DATVDemod::MsgReportModcodCstlnChange::getCodeRate(), DATVDemod::MsgReportModcodCstlnChange::getModulation(), DATVDemodSettings::m_fec, DATVDemodSettings::m_modulation, m_settings, Message::match(), and DATVDemodSettings::validateSystemConfiguration().
Referenced by handleInputMessages().
 {
     if (DATVDemod::MsgReportModcodCstlnChange::match(message))
     {
         DATVDemod::MsgReportModcodCstlnChange& notif = (DATVDemod::MsgReportModcodCstlnChange&) message;
         m_settings.m_fec = notif.getCodeRate();
         m_settings.m_modulation = notif.getModulation();
         m_settings.validateSystemConfiguration();
         displaySystemConfiguration();
         return true;
     }
     else
     {
         return false;
     }
 }
leaveEvent()
void DATVDemodGUI::leaveEvent (QEvent *) private
Definition at line 367 of file datvdemodgui.cpp.
References blockApplySettings(), m_objChannelMarker, and ChannelMarker::setHighlighted().
 {
     blockApplySettings(true);
     m_objChannelMarker.setHighlighted(false);
     blockApplySettings(false);
 }
on_audioMute_toggled
void DATVDemodGUI::on_audioMute_toggled (bool checked) private slot
Definition at line 621 of file datvdemodgui.cpp.
References applySettings(), DATVDemodSettings::m_audioMute, and m_settings.
 {
     m_settings.m_audioMute = checked;
     applySettings();
 }
on_audioVolume_valueChanged
void DATVDemodGUI::on_audioVolume_valueChanged (int value) private slot
Definition at line 633 of file datvdemodgui.cpp.
References applySettings(), arg(), DATVDemodSettings::m_audioVolume, m_settings, and ui.
 {
     ui->audioVolumeText->setText(tr("%1").arg(value));
     m_settings.m_audioVolume = value;
     applySettings();
 }
on_chkAllowDrift_clicked
void DATVDemodGUI::on_chkAllowDrift_clicked () private slot
Definition at line 556 of file datvdemodgui.cpp.
References applySettings(), DATVDemodSettings::m_allowDrift, m_settings, and ui.
 {
     m_settings.m_allowDrift = ui->chkAllowDrift->isChecked();
     applySettings();
 }
on_chkFastlock_clicked
void DATVDemodGUI::on_chkFastlock_clicked () private slot
Definition at line 615 of file datvdemodgui.cpp.
References applySettings(), DATVDemodSettings::m_fastLock, m_settings, and ui.
 {
     m_settings.m_fastLock = ui->chkFastlock->isChecked();
     applySettings();
 }
on_chkHardMetric_clicked
void DATVDemodGUI::on_chkHardMetric_clicked () private slot
Definition at line 533 of file datvdemodgui.cpp.
References applySettings(), DATVDemodSettings::m_hardMetric, m_settings, and ui.
 {
     m_settings.m_hardMetric = ui->chkHardMetric->isChecked();
     applySettings();
 }
on_chkViterbi_clicked
void DATVDemodGUI::on_chkViterbi_clicked () private slot
Definition at line 527 of file datvdemodgui.cpp.
References applySettings(), m_settings, DATVDemodSettings::m_viterbi, and ui.
 {
     m_settings.m_viterbi = ui->chkViterbi->isChecked();
     applySettings();
 }
on_cmbFEC_currentIndexChanged
void DATVDemodGUI::on_cmbFEC_currentIndexChanged (const QString & arg1) private slot
Definition at line 519 of file datvdemodgui.cpp.
References applySettings(), DATVDemodSettings::getCodeRateFromStr(), DATVDemodSettings::m_fec, m_settings, and ui.
 {
     (void) arg1;
     QString strFEC = ui->cmbFEC->currentText();
     m_settings.m_fec = DATVDemodSettings::getCodeRateFromStr(strFEC);
     applySettings();
 }
on_cmbFilter_currentIndexChanged
void DATVDemodGUI::on_cmbFilter_currentIndexChanged (int index) private slot
Definition at line 683 of file datvdemodgui.cpp.
References applySettings(), displayRRCParameters(), DATVDemodSettings::m_filter, m_settings, DATVDemodSettings::SAMP_LINEAR, DATVDemodSettings::SAMP_NEAREST, and DATVDemodSettings::SAMP_RRC.
 {
     if (index == 0) {
         m_settings.m_filter = DATVDemodSettings::SAMP_LINEAR;
     } else if (index == 1) {
         m_settings.m_filter = DATVDemodSettings::SAMP_NEAREST;
     } else {
         m_settings.m_filter = DATVDemodSettings::SAMP_RRC;
     }
     displayRRCParameters(index == 2);
     applySettings();
 }
on_cmbModulation_currentIndexChanged
void DATVDemodGUI::on_cmbModulation_currentIndexChanged (const QString & arg1) private slot
Definition at line 501 of file datvdemodgui.cpp.
References applySettings(), DATVDemodSettings::BPSK, displaySystemConfiguration(), DATVDemodSettings::getModulationFromStr(), DATVDemodSettings::m_modulation, m_settings, DATVDemodSettings::QPSK, ui, and DATVDemodSettings::validateSystemConfiguration().
 {
     (void) arg1;
     QString strModulation = ui->cmbModulation->currentText();
     m_settings.m_modulation = DATVDemodSettings::getModulationFromStr(strModulation);
     m_settings.validateSystemConfiguration();
     displaySystemConfiguration();
     //Viterbi only for BPSK and QPSK
     if ((m_settings.m_modulation != DATVDemodSettings::BPSK)
         && (m_settings.m_modulation != DATVDemodSettings::QPSK))
     {
         ui->chkViterbi->setChecked(false);
     }
     applySettings();
 }
on_cmbStandard_currentIndexChanged
void DATVDemodGUI::on_cmbStandard_currentIndexChanged (int index) private slot
Definition at line 465 of file datvdemodgui.cpp.
References applySettings(), displaySystemConfiguration(), m_settings, DATVDemodSettings::m_standard, ui, and DATVDemodSettings::validateSystemConfiguration().
 {
     m_settings.m_standard = (DATVDemodSettings::dvb_version) index;
     if (m_settings.m_standard == DATVDemodSettings::dvb_version::DVB_S)
     {
         ui->chkAllowDrift->setEnabled(true);
         ui->chkHardMetric->setEnabled(true);
         ui->chkFastlock->setEnabled(true);
         ui->chkViterbi->setEnabled(true);
         ui->chkAllowDrift->setStyleSheet("QCheckBox { color: white }");
         ui->chkHardMetric->setStyleSheet("QCheckBox { color: white }");
         ui->chkFastlock->setStyleSheet("QCheckBox { color: white }");
         ui->chkViterbi->setStyleSheet("QCheckBox { color: white }");
     }
     else
     {
         ui->chkAllowDrift->setEnabled(false);
         ui->chkHardMetric->setEnabled(false);
         ui->chkFastlock->setEnabled(false);
         ui->chkViterbi->setEnabled(false);
         ui->chkAllowDrift->setStyleSheet("QCheckBox { color: gray }");
         ui->chkHardMetric->setStyleSheet("QCheckBox { color: gray }");
         ui->chkFastlock->setStyleSheet("QCheckBox { color: gray }");
         ui->chkViterbi->setStyleSheet("QCheckBox { color: gray }");
     }
     if (m_settings.m_standard == DATVDemodSettings::dvb_version::DVB_S) {
         ui->statusText->clear();
     }
     m_settings.validateSystemConfiguration();
     displaySystemConfiguration();
     applySettings();
 }
on_deltaFrequency_changed
void DATVDemodGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 601 of file datvdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), DATVDemodSettings::m_centerFrequency, m_objChannelMarker, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_objChannelMarker.setCenterFrequency(value);
     m_settings.m_centerFrequency = m_objChannelMarker.getCenterFrequency();
     applySettings();
 }
on_fullScreen_clicked
void DATVDemodGUI::on_fullScreen_clicked () private slot
Definition at line 562 of file datvdemodgui.cpp.
References ui.
 {
     ui->screenTV_2->SetFullScreen(true);
 }
on_mouseEvent
void DATVDemodGUI::on_mouseEvent (QMouseEvent * obj) private slot
Definition at line 567 of file datvdemodgui.cpp.
 {
     (void) obj;
 }
on_resetDefaults_clicked
void DATVDemodGUI::on_resetDefaults_clicked () private slot
Definition at line 539 of file datvdemodgui.cpp.
References resetToDefaults().
 {
     resetToDefaults();
 }
on_rfBandwidth_changed
void DATVDemodGUI::on_rfBandwidth_changed (qint64 value) private slot
Definition at line 608 of file datvdemodgui.cpp.
References applySettings(), ChannelMarker::getBandwidth(), m_objChannelMarker, DATVDemodSettings::m_rfBandwidth, m_settings, and ChannelMarker::setBandwidth().
 {
     m_objChannelMarker.setBandwidth(value);
     m_settings.m_rfBandwidth = m_objChannelMarker.getBandwidth();
     applySettings();
 }
on_spiExcursion_valueChanged
void DATVDemodGUI::on_spiExcursion_valueChanged (int arg1) private slot
Definition at line 703 of file datvdemodgui.cpp.
References applySettings(), DATVDemodSettings::m_excursion, and m_settings.
 {
     m_settings.m_excursion = value;
     applySettings();
 }
on_spiNotchFilters_valueChanged
void DATVDemodGUI::on_spiNotchFilters_valueChanged (int arg1) private slot
Definition at line 550 of file datvdemodgui.cpp.
References applySettings(), DATVDemodSettings::m_notchFilters, and m_settings.
 {
     m_settings.m_notchFilters = value;
     applySettings();
 }
on_spiRollOff_valueChanged
void DATVDemodGUI::on_spiRollOff_valueChanged (int arg1) private slot
Definition at line 697 of file datvdemodgui.cpp.
References applySettings(), DATVDemodSettings::m_rollOff, and m_settings.
 {
     m_settings.m_rollOff = ((float) value) / 100.0f;
     applySettings();
 }
on_spiSymbolRate_valueChanged
void DATVDemodGUI::on_spiSymbolRate_valueChanged (int arg1) private slot
Definition at line 544 of file datvdemodgui.cpp.
References applySettings(), m_settings, and DATVDemodSettings::m_symbolRate.
 {
     m_settings.m_symbolRate = value;
     applySettings();
 }
on_StreamDataAvailable
void DATVDemodGUI::on_StreamDataAvailable (int * intPackets, int * intBytes, int * intPercent, qint64 * intTotalReceived) private slot
Definition at line 586 of file datvdemodgui.cpp.
References arg(), formatBytes(), m_intLastDecodedData, m_intReadyDecodedData, and ui.
Referenced by DATVDemodGUI().
 {
     (void) intPackets;
     ui->lblStatus->setText(QString("Data: %1B").arg(formatBytes(*intTotalReceived)));
     m_intLastDecodedData = *intTotalReceived;
     if((*intPercent)<100) {
         ui->prgSynchro->setValue(*intPercent);
     } else {
         ui->prgSynchro->setValue(100);
     }
     m_intReadyDecodedData = *intBytes;
 }
on_StreamMetaDataChanged
void DATVDemodGUI::on_StreamMetaDataChanged (DataTSMetaData2 * objMetaData) private slot
Definition at line 646 of file datvdemodgui.cpp.
References DataTSMetaData2::CodecDescription, DataTSMetaData2::Height, DataTSMetaData2::OK_Data, DataTSMetaData2::OK_Decoding, DataTSMetaData2::OK_TransportStream, DataTSMetaData2::OK_VideoStream, DataTSMetaData2::PID, DataTSMetaData2::Program, DataTSMetaData2::Stream, ui, and DataTSMetaData2::Width.
Referenced by DATVDemodGUI().
 {
     QString strMetaData="";
     if (objMetaData != nullptr)
     {
         if (objMetaData->OK_TransportStream == true)
         {
             strMetaData.sprintf("PID: %d - Width: %d - Height: %d\r\n%s%s\r\nCodec: %s\r\n",
                 objMetaData->PID,
                 objMetaData->Width,
                 objMetaData->Height,
                 objMetaData->Program.toStdString().c_str(),
                 objMetaData->Stream.toStdString().c_str(),
                 objMetaData->CodecDescription.toStdString().c_str());
         }
         ui->streamInfo->setText(strMetaData);
         ui->chkData->setChecked(objMetaData->OK_Data);
         ui->chkTS->setChecked(objMetaData->OK_TransportStream);
         ui->chkVS->setChecked(objMetaData->OK_VideoStream);
         ui->chkDecoding->setChecked(objMetaData->OK_Decoding);
         if (objMetaData->Height > 0) {
             ui->screenTV_2->setFixedWidth((int)objMetaData->Width*(270.0f/(float)objMetaData->Height));
         }
     }
 }
on_udpTS_clicked
void DATVDemodGUI::on_udpTS_clicked (bool checked) private slot
Definition at line 640 of file datvdemodgui.cpp.
References applySettings(), m_settings, and DATVDemodSettings::m_udpTS.
 {
     m_settings.m_udpTS = checked;
     applySettings();
 }
on_udpTSAddress_editingFinished
void DATVDemodGUI::on_udpTSAddress_editingFinished () private slot
Definition at line 709 of file datvdemodgui.cpp.
References applySettings(), m_settings, DATVDemodSettings::m_udpTSAddress, and ui.
 {
     m_settings.m_udpTSAddress = ui->udpTSAddress->text();
     applySettings();
 }
on_udpTSPort_editingFinished
void DATVDemodGUI::on_udpTSPort_editingFinished () private slot
Definition at line 715 of file datvdemodgui.cpp.
References applySettings(), arg(), m_settings, DATVDemodSettings::m_udpTSPort, and ui.
 {
     bool ok;
     quint16 udpPort = ui->udpTSPort->text().toInt(&ok);
     if((!ok) || (udpPort < 1024)) {
         udpPort = 8882;
     }
     m_settings.m_udpTSPort = udpPort;
     ui->udpTSPort->setText(tr("%1").arg(udpPort));
     applySettings();
 }
on_videoMute_toggled
void DATVDemodGUI::on_videoMute_toggled (bool checked) private slot
Definition at line 627 of file datvdemodgui.cpp.
References applySettings(), m_settings, and DATVDemodSettings::m_videoMute.
 {
     m_settings.m_videoMute = checked;
     applySettings();
 }
onMenuDoubleClicked
void DATVDemodGUI::onMenuDoubleClicked () private slot
Definition at line 155 of file datvdemodgui.cpp.
 {
 }
onWidgetRolled
void DATVDemodGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 149 of file datvdemodgui.cpp.
Referenced by DATVDemodGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void DATVDemodGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 75 of file datvdemodgui.cpp.
References applySettings(), displaySettings(), m_settings, and DATVDemodSettings::resetToDefaults().
Referenced by DATVDemodGUI(), deserialize(), and on_resetDefaults_clicked().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
serialize()
QByteArray DATVDemodGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 82 of file datvdemodgui.cpp.
References m_settings, and DATVDemodSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void DATVDemodGUI::setCenterFrequency (qint64 intCenterFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 69 of file datvdemodgui.cpp.
References applySettings(), m_objChannelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_objChannelMarker.setCenterFrequency(intCenterFrequency);
     applySettings();
 }
setName()
void DATVDemodGUI::setName (const QString & strName) virtual
Implements PluginInstanceGUI.
Definition at line 54 of file datvdemodgui.cpp.
 {
     setObjectName(strName);
 }
tick
void DATVDemodGUI::tick () private slot
Definition at line 394 of file datvdemodgui.cpp.
References arg(), DATVDemod::audioActive(), DATVDemod::audioDecodeOK(), CalcDb::dbPower(), formatBytes(), DATVDemod::getCodeRateFromLeanDVBCode(), DATVDemod::getMagSq(), DATVDemod::getModcodCodeRate(), DATVDemod::getModcodModulation(), DATVDemod::getModulationFromLeanDVBCode(), DATVDemodSettings::getStrFromCodeRate(), DATVDemodSettings::getStrFromModulation(), DATVDemod::isCstlnSetByModcod(), m_cstlnSetByModcod, m_intLastDecodedData, m_intLastSpeed, m_intPreviousDecodedData, m_modcodCodeRateIndex, m_modcodModulationIndex, m_objDATVDemod, m_objMagSqAverage, DATVDemod::PlayVideo(), SDR_RX_SCALED, ui, DATVDemod::videoActive(), and DATVDemod::videoDecodeOK().
Referenced by DATVDemodGUI().
 {
     if (m_objDATVDemod)
     {
         m_objMagSqAverage(m_objDATVDemod->getMagSq());
         double magSqDB = CalcDb::dbPower(m_objMagSqAverage / (SDR_RX_SCALED*SDR_RX_SCALED));
         ui->channePowerText->setText(tr("%1 dB").arg(magSqDB, 0, 'f', 1));
         if ((m_modcodModulationIndex != m_objDATVDemod->getModcodModulation()) || (m_modcodCodeRateIndex != m_objDATVDemod->getModcodCodeRate()))
         {
             m_modcodModulationIndex = m_objDATVDemod->getModcodModulation();
             m_modcodCodeRateIndex = m_objDATVDemod->getModcodCodeRate();
             DATVDemodSettings::DATVModulation modulation = DATVDemod::getModulationFromLeanDVBCode(m_modcodModulationIndex);
             DATVDemodSettings::DATVCodeRate rate = DATVDemod::getCodeRateFromLeanDVBCode(m_modcodCodeRateIndex);
             QString modcodModulationStr = DATVDemodSettings::getStrFromModulation(modulation);
             QString modcodCodeRateStr = DATVDemodSettings::getStrFromCodeRate(rate);
             ui->statusText->setText(tr("MCOD %1 %2").arg(modcodModulationStr).arg(modcodCodeRateStr));
         }
         if (m_cstlnSetByModcod != m_objDATVDemod->isCstlnSetByModcod())
         {
             m_cstlnSetByModcod = m_objDATVDemod->isCstlnSetByModcod();
             if (m_cstlnSetByModcod) {
                 ui->statusText->setStyleSheet("QLabel { background-color : green; }");
             } else {
                 ui->statusText->setStyleSheet("QLabel { background:rgb(79,79,79); }");
             }
         }
     }
     if((m_intLastDecodedData-m_intPreviousDecodedData)>=0)
     {
         m_intLastSpeed = 8*(m_intLastDecodedData-m_intPreviousDecodedData);
         ui->lblRate->setText(QString("Speed: %1b/s").arg(formatBytes(m_intLastSpeed)));
     }
     if (m_objDATVDemod->audioActive())
     {
         if (m_objDATVDemod->audioDecodeOK()) {
             ui->audioMute->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->audioMute->setStyleSheet("QToolButton { background-color : red; }");
         }
     }
     else
     {
         ui->audioMute->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     if (m_objDATVDemod->videoActive())
     {
         if (m_objDATVDemod->videoDecodeOK()) {
             ui->videoMute->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->videoMute->setStyleSheet("QToolButton { background-color : red; }");
         }
     }
     else
     {
         ui->videoMute->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     m_intPreviousDecodedData = m_intLastDecodedData;
     //Try to start video rendering
     m_objDATVDemod->PlayVideo(false);
     return;
 }
Member Data Documentation
m_blnBasicSettingsShown
bool DATVDemodGUI::m_blnBasicSettingsShown private
Definition at line 120 of file datvdemodgui.h.
m_blnButtonPlayClicked
bool DATVDemodGUI::m_blnButtonPlayClicked private
Definition at line 122 of file datvdemodgui.h.
m_blnDoApplySettings
bool DATVDemodGUI::m_blnDoApplySettings private
Definition at line 121 of file datvdemodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_cstlnSetByModcod
bool DATVDemodGUI::m_cstlnSetByModcod private
Definition at line 125 of file datvdemodgui.h.
Referenced by tick().
m_deviceUISet
DeviceUISet* DATVDemodGUI::m_deviceUISet private
Definition at line 104 of file datvdemodgui.h.
Referenced by DATVDemodGUI(), and ~DATVDemodGUI().
m_inputMessageQueue
MessageQueue DATVDemodGUI::m_inputMessageQueue private
Definition at line 110 of file datvdemodgui.h.
m_intCenterFrequency
int DATVDemodGUI::m_intCenterFrequency private
Definition at line 111 of file datvdemodgui.h.
Referenced by channelMarkerChangedByCursor().
m_intLastDecodedData
qint64 DATVDemodGUI::m_intLastDecodedData private
Definition at line 116 of file datvdemodgui.h.
Referenced by DATVDemodGUI(), on_StreamDataAvailable(), and tick().
m_intLastSpeed
qint64 DATVDemodGUI::m_intLastSpeed private
Definition at line 117 of file datvdemodgui.h.
Referenced by DATVDemodGUI(), and tick().
m_intPreviousDecodedData
qint64 DATVDemodGUI::m_intPreviousDecodedData private
Definition at line 115 of file datvdemodgui.h.
Referenced by DATVDemodGUI(), and tick().
m_intReadyDecodedData
int DATVDemodGUI::m_intReadyDecodedData private
Definition at line 118 of file datvdemodgui.h.
Referenced by DATVDemodGUI(), and on_StreamDataAvailable().
m_modcodCodeRateIndex
int DATVDemodGUI::m_modcodCodeRateIndex private
Definition at line 124 of file datvdemodgui.h.
Referenced by tick().
m_modcodModulationIndex
int DATVDemodGUI::m_modcodModulationIndex private
Definition at line 123 of file datvdemodgui.h.
Referenced by tick().
m_objChannelizer
DownChannelizer* DATVDemodGUI::m_objChannelizer private
Definition at line 108 of file datvdemodgui.h.
m_objChannelMarker
ChannelMarker DATVDemodGUI::m_objChannelMarker private
Definition at line 106 of file datvdemodgui.h.
Referenced by applySettings(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), DATVDemodGUI(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), on_rfBandwidth_changed(), and setCenterFrequency().
m_objDATVDemod
DATVDemod* DATVDemodGUI::m_objDATVDemod private
Definition at line 109 of file datvdemodgui.h.
Referenced by applySettings(), DATVDemodGUI(), tick(), and ~DATVDemodGUI().
m_objMagSqAverage
MovingAverageUtil<double, double, 4> DATVDemodGUI::m_objMagSqAverage private
Definition at line 127 of file datvdemodgui.h.
Referenced by tick().
m_objPluginAPI
PluginAPI* DATVDemodGUI::m_objPluginAPI private
Definition at line 103 of file datvdemodgui.h.
m_objThreadedChannelizer
ThreadedBasebandSampleSink* DATVDemodGUI::m_objThreadedChannelizer private
Definition at line 107 of file datvdemodgui.h.
m_objTimer
QTimer DATVDemodGUI::m_objTimer private
Definition at line 114 of file datvdemodgui.h.
Referenced by DATVDemodGUI().
m_settings
DATVDemodSettings DATVDemodGUI::m_settings private
Definition at line 112 of file datvdemodgui.h.
Referenced by applySettings(), audioSelect(), deserialize(), displaySettings(), displaySystemConfiguration(), handleMessage(), on_audioMute_toggled(), on_audioVolume_valueChanged(), on_chkAllowDrift_clicked(), on_chkFastlock_clicked(), on_chkHardMetric_clicked(), on_chkViterbi_clicked(), on_cmbFEC_currentIndexChanged(), on_cmbFilter_currentIndexChanged(), on_cmbModulation_currentIndexChanged(), on_cmbStandard_currentIndexChanged(), on_deltaFrequency_changed(), on_rfBandwidth_changed(), on_spiExcursion_valueChanged(), on_spiNotchFilters_valueChanged(), on_spiRollOff_valueChanged(), on_spiSymbolRate_valueChanged(), on_udpTS_clicked(), on_udpTSAddress_editingFinished(), on_udpTSPort_editingFinished(), on_videoMute_toggled(), resetToDefaults(), and serialize().
m_strChannelID
const QString DATVDemodGUI::m_strChannelID = "sdrangel.channel.demoddatv" static
Definition at line 63 of file datvdemodgui.h.
ui
Ui::DATVDemodGUI* DATVDemodGUI::ui private
Definition at line 102 of file datvdemodgui.h.
Referenced by channelMarkerChangedByCursor(), DATVDemodGUI(), displayRRCParameters(), displaySettings(), displaySystemConfiguration(), on_audioVolume_valueChanged(), on_chkAllowDrift_clicked(), on_chkFastlock_clicked(), on_chkHardMetric_clicked(), on_chkViterbi_clicked(), on_cmbFEC_currentIndexChanged(), on_cmbModulation_currentIndexChanged(), on_cmbStandard_currentIndexChanged(), on_fullScreen_clicked(), on_StreamDataAvailable(), on_StreamMetaDataChanged(), on_udpTSAddress_editingFinished(), on_udpTSPort_editingFinished(), tick(), and ~DATVDemodGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/demoddatv/datvdemodgui.h
plugins/channelrx/demoddatv/datvdemodgui.cpp