SDRAngel: AirspyHFInput Class Reference
AirspyHFInput Class Reference
#include <airspyhfinput.h>
Classes
class MsgConfigureAirspyHF
class MsgFileRecord
class MsgStartStop
Public Member Functions
AirspyHFInput (DeviceAPI *deviceAPI)
virtual ~AirspyHFInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
const std::vector< uint32_t > & getSampleRates () const
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Static Public Attributes
static const qint64 loLowLimitFreqHF = 9000L
static const qint64 loHighLimitFreqHF = 31000000L
static const qint64 loLowLimitFreqVHF = 60000000L
static const qint64 loHighLimitFreqVHF = 260000000L
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
bool applySettings (const AirspyHFSettings &settings, bool force)
airspyhf_device_t * open_airspyhf_from_serial (const QString &serialStr)
void setDeviceCenterFrequency (quint64 freq, const AirspyHFSettings &settings)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const AirspyHFSettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const AirspyHFSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
AirspyHFSettings m_settings
airspyhf_device_t * m_dev
AirspyHFThread * m_airspyHFThread
QString m_deviceDescription
std::vector< uint32_t > m_sampleRates
bool m_running
FileRecord * m_fileSink
File sink to record device I/Q output.
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 36 of file airspyhfinput.h.
Constructor & Destructor Documentation
AirspyHFInput()
AirspyHFInput::AirspyHFInput (DeviceAPI * deviceAPI)
Definition at line 50 of file airspyhfinput.cpp.
References DeviceAPI::addAncillarySink(), arg(), DeviceAPI::getDeviceUID(), m_deviceAPI, m_fileSink, m_networkManager, networkManagerFinished(), openDevice(), and DeviceAPI::setNbSourceStreams().
Referenced by AirspyHFInput::MsgStartStop::MsgStartStop().
                                                  :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_dev(0),
     m_airspyHFThread(0),
     m_deviceDescription("AirspyHF"),
     m_running(false)
 {
     openDevice();
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~AirspyHFInput()
AirspyHFInput::~AirspyHFInput () virtual
Definition at line 66 of file airspyhfinput.cpp.
References closeDevice(), m_deviceAPI, m_fileSink, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::removeAncillarySink(), and stop().
Referenced by AirspyHFInput::MsgStartStop::MsgStartStop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
     closeDevice();
 }
Member Function Documentation
applySettings()
bool AirspyHFInput::applySettings (const AirspyHFSettings & settings, bool force) private
Definition at line 381 of file airspyhfinput.cpp.
References DeviceAPI::configureCorrections(), DeviceAPI::getDeviceEngineInputMessageQueue(), FileRecord::handleMessage(), AirspyHFSettings::m_agcHigh, m_airspyHFThread, AirspyHFSettings::m_attenuatorSteps, AirspyHFSettings::m_bandIndex, AirspyHFSettings::m_centerFrequency, AirspyHFSettings::m_dcBlock, m_dev, m_deviceAPI, AirspyHFSettings::m_devSampleRateIndex, AirspyHFSettings::m_fileRecordName, m_fileSink, AirspyHFSettings::m_iqCorrection, AirspyHFSettings::m_log2Decim, AirspyHFSettings::m_LOppmTenths, m_mutex, AirspyHFSettings::m_reverseAPIAddress, AirspyHFSettings::m_reverseAPIDeviceIndex, AirspyHFSettings::m_reverseAPIPort, m_sampleRates, m_settings, AirspyHFSettings::m_transverterDeltaFrequency, AirspyHFSettings::m_transverterMode, AirspyHFSettings::m_useAGC, AirspyHFSettings::m_useDSP, AirspyHFSettings::m_useLNA, AirspyHFSettings::m_useReverseAPI, MessageQueue::push(), setDeviceCenterFrequency(), AirspyHFThread::setLog2Decimation(), AirspyHFThread::setSamplerate(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     qDebug() << "AirspyHFInput::applySettings: "
         << " m_centerFrequency: " << settings.m_centerFrequency
         << " m_devSampleRateIndex: " << settings.m_devSampleRateIndex
         << " m_log2Decim: " << settings.m_log2Decim
         << " m_LOppmTenths: " << settings.m_LOppmTenths
         << " m_bandIndex: " << settings.m_bandIndex
         << " m_transverterDeltaFrequency: " << settings.m_transverterDeltaFrequency
         << " m_transverterMode: " << settings.m_transverterMode
         << " m_fileRecordName: " << settings.m_fileRecordName
         << " m_useDSP: " << settings.m_useDSP
         << " m_useAGC: " << settings.m_useAGC
         << " m_agcHigh: " << settings.m_agcHigh
         << " m_useLNA: " << settings.m_useLNA
         << " m_attenuatorSteps: " << settings.m_attenuatorSteps
         << " m_useReverseAPI: " << settings.m_useReverseAPI
         << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
         << " m_reverseAPIPort: " << settings.m_reverseAPIPort
         << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex
         << " m_dcBlock: " << settings.m_dcBlock
         << " m_iqCorrection: " << settings.m_iqCorrection;
     QMutexLocker mutexLocker(&m_mutex);
     bool forwardChange = false;
     airspyhf_error rc;
     QList<QString> reverseAPIKeys;
     int sampleRateIndex = settings.m_devSampleRateIndex;
    if ((m_settings.m_dcBlock != settings.m_dcBlock) || force) {
         reverseAPIKeys.append("dcBlock");
     }
     if ((m_settings.m_iqCorrection != settings.m_iqCorrection) || force) {
         reverseAPIKeys.append("iqCorrection");
     }
     if ((m_settings.m_dcBlock != settings.m_dcBlock) ||
         (m_settings.m_iqCorrection != settings.m_iqCorrection) || force)
     {
         m_deviceAPI->configureCorrections(settings.m_dcBlock, settings.m_iqCorrection);
     }
     if ((m_settings.m_bandIndex != settings.m_bandIndex) || force) {
         reverseAPIKeys.append("bandIndex");
     }
     if ((m_settings.m_devSampleRateIndex != settings.m_devSampleRateIndex) || force)
     {
         reverseAPIKeys.append("devSampleRateIndex");
         forwardChange = true;
         if (settings.m_devSampleRateIndex >= m_sampleRates.size()) {
             sampleRateIndex = m_sampleRates.size() - 1;
         }
         if ((m_dev != 0) && (sampleRateIndex >= 0))
         {
             rc = (airspyhf_error) airspyhf_set_samplerate(m_dev, sampleRateIndex);
             if (rc != AIRSPYHF_SUCCESS)
             {
                 qCritical("AirspyHFInput::applySettings: could not set sample rate index %u (%d S/s)", sampleRateIndex, m_sampleRates[sampleRateIndex]);
             }
             else if (m_airspyHFThread != 0)
             {
                 qDebug("AirspyHFInput::applySettings: sample rate set to index: %u (%d S/s)", sampleRateIndex, m_sampleRates[sampleRateIndex]);
                 m_airspyHFThread->setSamplerate(m_sampleRates[sampleRateIndex]);
             }
         }
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         reverseAPIKeys.append("log2Decim");
         forwardChange = true;
         if (m_airspyHFThread != 0)
         {
             m_airspyHFThread->setLog2Decimation(settings.m_log2Decim);
             qDebug() << "AirspyInput: set decimation to " << (1<<settings.m_log2Decim);
         }
     }
     if ((m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force)
     {
         reverseAPIKeys.append("LOppmTenths");
         if (m_dev != 0)
         {
             rc = (airspyhf_error) airspyhf_set_calibration(m_dev, settings.m_LOppmTenths * 100);
             if (rc != AIRSPYHF_SUCCESS)
             {
                 qCritical("AirspyHFInput::applySettings: could not set LO ppm correction to %f", settings.m_LOppmTenths / 10.0f);
             }
             else if (m_airspyHFThread != 0)
             {
                 qDebug("AirspyHFInput::applySettings: LO ppm correction set to %f", settings.m_LOppmTenths / 10.0f);
             }
         }
     }
     if (force || (m_settings.m_centerFrequency != settings.m_centerFrequency)) {
         reverseAPIKeys.append("centerFrequency");
     }
     if (force || (m_settings.m_transverterMode != settings.m_transverterMode)) {
         reverseAPIKeys.append("transverterMode");
     }
     if (force || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency)) {
         reverseAPIKeys.append("transverterDeltaFrequency");
     }
     if (force || (m_settings.m_centerFrequency != settings.m_centerFrequency)
             || (m_settings.m_transverterMode != settings.m_transverterMode)
             || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency))
     {
         qint64 deviceCenterFrequency = settings.m_centerFrequency;
         deviceCenterFrequency -= settings.m_transverterMode ? settings.m_transverterDeltaFrequency : 0;
         deviceCenterFrequency = deviceCenterFrequency < 0 ? 0 : deviceCenterFrequency;
         qint64 f_img = deviceCenterFrequency;
         if ((m_dev != 0) && (sampleRateIndex >= 0))
         {
             quint32 devSampleRate = m_sampleRates[sampleRateIndex];
             setDeviceCenterFrequency(deviceCenterFrequency, settings);
             qDebug() << "AirspyHFInput::applySettings: center freq: " << settings.m_centerFrequency << " Hz"
                     << " device center freq: " << deviceCenterFrequency << " Hz"
                     << " device sample rate: " << devSampleRate << "Hz"
                     << " Actual sample rate: " << devSampleRate/(1<<m_settings.m_log2Decim) << "Hz"
                     << " img: " << f_img << "Hz";
         }
         forwardChange = true;
     }
     if ((m_settings.m_useAGC != settings.m_useAGC) || force)
     {
         reverseAPIKeys.append("useAGC");
         if (m_dev != 0)
         {
             rc = (airspyhf_error) airspyhf_set_hf_agc(m_dev, settings.m_useAGC ? 1 : 0);
             if (rc != AIRSPYHF_SUCCESS) {
                 qCritical("AirspyHFInput::applySettings: could not set AGC to %d", settings.m_useAGC ? 1 : 0);
             } else {
                 qDebug("AirspyHFInput::applySettings: set AGC to %d", settings.m_useAGC ? 1 : 0);
             }
         }
     }
     if ((m_settings.m_agcHigh != settings.m_agcHigh) || force)
     {
         reverseAPIKeys.append("agcHigh");
         if (m_dev != 0)
         {
             rc = (airspyhf_error) airspyhf_set_hf_agc_threshold(m_dev, settings.m_agcHigh ? 1 : 0);
             if (rc != AIRSPYHF_SUCCESS) {
                 qCritical("AirspyHFInput::applySettings: could not set AGC to %s", settings.m_agcHigh ? "high" : "low");
             } else {
                 qDebug("AirspyHFInput::applySettings: set AGC to %s", settings.m_agcHigh ? "high" : "low");
             }
         }
     }
     if ((m_settings.m_useDSP != settings.m_useDSP) || force)
     {
         reverseAPIKeys.append("useDSP");
         if (m_dev != 0)
         {
             rc = (airspyhf_error) airspyhf_set_lib_dsp(m_dev, settings.m_useDSP ? 1 : 0);
             if (rc != AIRSPYHF_SUCCESS) {
                 qCritical("AirspyHFInput::applySettings: could not set DSP to %d", settings.m_useDSP ? 1 : 0);
             } else {
                 qDebug("AirspyHFInput::applySettings: set DSP to %d", settings.m_useDSP ? 1 : 0);
             }
         }
     }
     if ((m_settings.m_useLNA != settings.m_useLNA) || force)
     {
         reverseAPIKeys.append("useLNA");
         if (m_dev != 0)
         {
             rc = (airspyhf_error) airspyhf_set_hf_lna(m_dev, settings.m_useLNA ? 1 : 0);
             if (rc != AIRSPYHF_SUCCESS) {
                 qCritical("AirspyHFInput::applySettings: could not set LNA to %d", settings.m_useLNA ? 1 : 0);
             } else {
                 qDebug("AirspyHFInput::applySettings: set LNA to %d", settings.m_useLNA ? 1 : 0);
             }
         }
     }
     if ((m_settings.m_attenuatorSteps != settings.m_attenuatorSteps) || force)
     {
         reverseAPIKeys.append("attenuatorSteps");
         if (m_dev != 0)
         {
             rc = (airspyhf_error) airspyhf_set_hf_att(m_dev, settings.m_attenuatorSteps);
             if (rc != AIRSPYHF_SUCCESS) {
                 qCritical("AirspyHFInput::applySettings: could not set attenuator to %d dB", settings.m_attenuatorSteps * 6);
             } else {
                 qDebug("AirspyHFInput::applySettings: set attenuator to %d dB", settings.m_attenuatorSteps * 6);
             }
         }
     }
     if (forwardChange && (sampleRateIndex >= 0))
     {
         int sampleRate = m_sampleRates[sampleRateIndex]/(1<<settings.m_log2Decim);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     return true;
 }
closeDevice()
void AirspyHFInput::closeDevice () private
Definition at line 194 of file airspyhfinput.cpp.
References m_dev, and m_deviceDescription.
Referenced by openDevice(), and ~AirspyHFInput().
 {
     if (m_dev != 0)
     {
         airspyhf_stop(m_dev);
         airspyhf_close(m_dev);
         m_dev = 0;
     }
     m_deviceDescription.clear();
 }
deserialize()
bool AirspyHFInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 226 of file airspyhfinput.cpp.
References AirspyHFInput::MsgConfigureAirspyHF::create(), AirspyHFSettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and AirspyHFSettings::resetToDefaults().
Referenced by AirspyHFInput::MsgStartStop::MsgStartStop().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureAirspyHF* message = MsgConfigureAirspyHF::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureAirspyHF* messageToGUI = MsgConfigureAirspyHF::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void AirspyHFInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 80 of file airspyhfinput.cpp.
Referenced by AirspyHFInput::MsgStartStop::MsgStartStop().
 {
     delete this;
 }
getCenterFrequency()
quint64 AirspyHFInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 272 of file airspyhfinput.cpp.
References AirspyHFSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & AirspyHFInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 248 of file airspyhfinput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getSampleRate()
int AirspyHFInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 253 of file airspyhfinput.cpp.
References AirspyHFSettings::m_devSampleRateIndex, AirspyHFSettings::m_log2Decim, m_sampleRates, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     int sampleRateIndex = m_settings.m_devSampleRateIndex;
     if (m_settings.m_devSampleRateIndex >= m_sampleRates.size()) {
         sampleRateIndex = m_sampleRates.size() - 1;
     }
     if (sampleRateIndex >= 0)
     {
         int rate = m_sampleRates[sampleRateIndex];
         return (rate / (1<<m_settings.m_log2Decim));
     }
     else
     {
         return 0;
     }
 }
getSampleRates()
const std::vector<uint32_t>& AirspyHFInput::getSampleRates () const inline
Definition at line 117 of file airspyhfinput.h.
References handleMessage(), m_sampleRates, webapiReportGet(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
Referenced by webapiFormatDeviceReport().
 { return m_sampleRates; }
handleMessage()
bool AirspyHFInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 292 of file airspyhfinput.cpp.
References applySettings(), FileRecord::genUniqueFileName(), DeviceAPI::getDeviceUID(), AirspyHFInput::MsgConfigureAirspyHF::getForce(), AirspyHFInput::MsgConfigureAirspyHF::getSettings(), AirspyHFInput::MsgFileRecord::getStartStop(), AirspyHFInput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), m_deviceAPI, AirspyHFSettings::m_fileRecordName, m_fileSink, m_settings, AirspyHFSettings::m_useReverseAPI, Message::match(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
Referenced by getSampleRates().
 {
     if (MsgConfigureAirspyHF::match(message))
     {
         MsgConfigureAirspyHF& conf = (MsgConfigureAirspyHF&) message;
         qDebug() << "MsgConfigureAirspyHF::handleMessage: MsgConfigureAirspyHF";
         bool success = applySettings(conf.getSettings(), conf.getForce());
         if (!success)
         {
             qDebug("MsgConfigureAirspyHF::handleMessage: AirspyHF config error");
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "AirspyHFInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "AirspyHFInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void AirspyHFInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 155 of file airspyhfinput.cpp.
References applySettings(), and m_settings.
Referenced by AirspyHFInput::MsgStartStop::MsgStartStop().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void AirspyHFInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 924 of file airspyhfinput.cpp.
Referenced by AirspyHFInput(), and ~AirspyHFInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "AirspyHFInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("AirspyHFInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
open_airspyhf_from_serial()
airspyhf_device_t * AirspyHFInput::open_airspyhf_from_serial (const QString & serialStr) private
Definition at line 620 of file airspyhfinput.cpp.
Referenced by openDevice().
 {
     airspyhf_device_t *devinfo;
     bool ok;
     airspyhf_error rc;
     uint64_t serial = serialStr.toULongLong(&ok, 16);
     if (!ok)
     {
         qCritical("AirspyHFInput::open_airspyhf_from_serial: invalid serial %s", qPrintable(serialStr));
         return 0;
     }
     else
     {
         rc = (airspyhf_error) airspyhf_open_sn(&devinfo, serial);
         if (rc == AIRSPYHF_SUCCESS) {
             return devinfo;
         } else {
             return 0;
         }
     }
 }
openDevice()
bool AirspyHFInput::openDevice () private
Definition at line 85 of file airspyhfinput.cpp.
References closeDevice(), DeviceAPI::getSamplingDeviceSerial(), i, m_dev, m_deviceAPI, DeviceSampleSource::m_sampleFifo, m_sampleRates, open_airspyhf_from_serial(), and SampleSinkFifo::setSize().
Referenced by AirspyHFInput().
 {
     if (m_dev != 0)
     {
         closeDevice();
     }
     airspyhf_error rc;
     if (!m_sampleFifo.setSize(1<<19))
     {
         qCritical("AirspyHFInput::openDevice: could not allocate SampleFifo");
         return false;
     }
     if ((m_dev = open_airspyhf_from_serial(m_deviceAPI->getSamplingDeviceSerial())) == 0)
     {
         qCritical("AirspyHFInput::openDevice: could not open Airspy HF with serial %s", qPrintable(m_deviceAPI->getSamplingDeviceSerial()));
         m_dev = 0;
         return false;
     }
     else
     {
         qDebug("AirspyHFInput::openDevice: opened Airspy HF with serial %s", qPrintable(m_deviceAPI->getSamplingDeviceSerial()));
     }
     uint32_t nbSampleRates;
     uint32_t *sampleRates;
     rc = (airspyhf_error) airspyhf_get_samplerates(m_dev, &nbSampleRates, 0);
     if (rc == AIRSPYHF_SUCCESS)
     {
         qDebug("AirspyHFInput::openDevice: %d sample rates for Airspy HF", nbSampleRates);
     }
     else
     {
         qCritical("AirspyHFInput::openDevice: could not obtain the number of Airspy HF sample rates");
         closeDevice();
         return false;
     }
     sampleRates = new uint32_t[nbSampleRates];
     rc = (airspyhf_error) airspyhf_get_samplerates(m_dev, sampleRates, nbSampleRates);
     if (rc == AIRSPYHF_SUCCESS)
     {
         qDebug("AirspyHFInput::openDevice: obtained Airspy HF sample rates");
     }
     else
     {
         qCritical("AirspyHFInput::openDevice: could not obtain Airspy HF sample rates");
         closeDevice();
         return false;
     }
     m_sampleRates.clear();
     for (unsigned int i = 0; i < nbSampleRates; i++)
     {
         m_sampleRates.push_back(sampleRates[i]);
         qDebug("AirspyHFInput::openDevice: sampleRates[%d] = %u Hz", i, sampleRates[i]);
     }
     delete[] sampleRates;
     return true;
 }
serialize()
QByteArray AirspyHFInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 221 of file airspyhfinput.cpp.
References m_settings, and AirspyHFSettings::serialize().
Referenced by AirspyHFInput::MsgStartStop::MsgStartStop().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void AirspyHFInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 277 of file airspyhfinput.cpp.
References AirspyHFInput::MsgConfigureAirspyHF::create(), AirspyHFSettings::m_centerFrequency, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     AirspyHFSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureAirspyHF* message = MsgConfigureAirspyHF::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureAirspyHF* messageToGUI = MsgConfigureAirspyHF::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setDeviceCenterFrequency()
void AirspyHFInput::setDeviceCenterFrequency (quint64 freq, const AirspyHFSettings & settings) private
Definition at line 359 of file airspyhfinput.cpp.
References loHighLimitFreqHF, loHighLimitFreqVHF, AirspyHFSettings::m_bandIndex, and m_dev.
Referenced by applySettings().
 {
     switch(settings.m_bandIndex)
     {
     case 1:
         freq_hz = freq_hz < loLowLimitFreqVHF ? loLowLimitFreqVHF : freq_hz > loHighLimitFreqVHF ? loHighLimitFreqVHF : freq_hz;
         break;
     case 0:
     default:
         freq_hz = freq_hz < loLowLimitFreqHF ? loLowLimitFreqHF : freq_hz > loHighLimitFreqHF ? loHighLimitFreqHF : freq_hz;
         break;
     }
     airspyhf_error rc = (airspyhf_error) airspyhf_set_freq(m_dev, static_cast<uint32_t>(freq_hz));
     if (rc == AIRSPYHF_SUCCESS) {
         qDebug("AirspyHFInput::setDeviceCenterFrequency: frequency set to %llu Hz", freq_hz);
     } else {
         qWarning("AirspyHFInput::setDeviceCenterFrequency: could not frequency to %llu Hz", freq_hz);
     }
 }
setMessageQueueToGUI()
virtual void AirspyHFInput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 111 of file airspyhfinput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSource::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void AirspyHFInput::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 114 of file airspyhfinput.h.
References getCenterFrequency(), and setCenterFrequency().
 { (void) sampleRate; }
start()
bool AirspyHFInput::start () virtual
Implements DeviceSampleSource.
Definition at line 160 of file airspyhfinput.cpp.
References applySettings(), m_airspyHFThread, m_dev, AirspyHFSettings::m_devSampleRateIndex, AirspyHFSettings::m_log2Decim, m_mutex, m_running, DeviceSampleSource::m_sampleFifo, m_sampleRates, m_settings, AirspyHFThread::setLog2Decimation(), AirspyHFThread::setSamplerate(), AirspyHFThread::startWork(), and stop().
Referenced by AirspyHFInput::MsgStartStop::MsgStartStop().
 {
     QMutexLocker mutexLocker(&m_mutex);
     if (!m_dev) {
         return false;
     }
     if (m_running) { stop(); }
     m_airspyHFThread = new AirspyHFThread(m_dev, &m_sampleFifo);
     int sampleRateIndex = m_settings.m_devSampleRateIndex;
     if (m_settings.m_devSampleRateIndex >= m_sampleRates.size()) {
         sampleRateIndex = m_sampleRates.size() - 1;
     }
     if (sampleRateIndex >= 0) {
         m_airspyHFThread->setSamplerate(m_sampleRates[sampleRateIndex]);
     }
     m_airspyHFThread->setLog2Decimation(m_settings.m_log2Decim);
     m_airspyHFThread->startWork();
     mutexLocker.unlock();
     applySettings(m_settings, true);
     qDebug("AirspyHFInput::startInput: started");
     m_running = true;
     return true;
 }
stop()
void AirspyHFInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 206 of file airspyhfinput.cpp.
References m_airspyHFThread, m_mutex, m_running, and AirspyHFThread::stopWork().
Referenced by AirspyHFInput::MsgStartStop::MsgStartStop(), start(), and ~AirspyHFInput().
 {
     qDebug("AirspyHFInput::stop");
     QMutexLocker mutexLocker(&m_mutex);
     if (m_airspyHFThread != 0)
     {
         m_airspyHFThread->stopWork();
         delete m_airspyHFThread;
         m_airspyHFThread = 0;
     }
     m_running = false;
 }
webapiFormatDeviceReport()
void AirspyHFInput::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 771 of file airspyhfinput.cpp.
References SWGSDRangel::SWGDeviceReport::getAirspyHfReport(), SWGSDRangel::SWGAirspyHFReport::getSampleRates(), getSampleRates(), and SWGSDRangel::SWGAirspyHFReport::setSampleRates().
Referenced by webapiReportGet().
 {
     response.getAirspyHfReport()->setSampleRates(new QList<SWGSDRangel::SWGSampleRate*>);
     for (std::vector<uint32_t>::const_iterator it = getSampleRates().begin(); it != getSampleRates().end(); ++it)
     {
         response.getAirspyHfReport()->getSampleRates()->append(new SWGSDRangel::SWGSampleRate);
         response.getAirspyHfReport()->getSampleRates()->back()->setRate(*it);
     }
 }
webapiFormatDeviceSettings()
void AirspyHFInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const AirspyHFSettings & settings) private
Definition at line 736 of file airspyhfinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getAirspyHfSettings(), SWGSDRangel::SWGAirspyHFSettings::getFileRecordName(), SWGSDRangel::SWGAirspyHFSettings::getReverseApiAddress(), AirspyHFSettings::m_agcHigh, AirspyHFSettings::m_attenuatorSteps, AirspyHFSettings::m_bandIndex, AirspyHFSettings::m_centerFrequency, AirspyHFSettings::m_dcBlock, AirspyHFSettings::m_devSampleRateIndex, AirspyHFSettings::m_fileRecordName, AirspyHFSettings::m_iqCorrection, AirspyHFSettings::m_log2Decim, AirspyHFSettings::m_LOppmTenths, AirspyHFSettings::m_reverseAPIAddress, AirspyHFSettings::m_reverseAPIDeviceIndex, AirspyHFSettings::m_reverseAPIPort, AirspyHFSettings::m_transverterDeltaFrequency, AirspyHFSettings::m_transverterMode, AirspyHFSettings::m_useAGC, AirspyHFSettings::m_useDSP, AirspyHFSettings::m_useLNA, AirspyHFSettings::m_useReverseAPI, SWGSDRangel::SWGAirspyHFSettings::setAgcHigh(), SWGSDRangel::SWGAirspyHFSettings::setAttenuatorSteps(), SWGSDRangel::SWGAirspyHFSettings::setBandIndex(), SWGSDRangel::SWGAirspyHFSettings::setCenterFrequency(), SWGSDRangel::SWGAirspyHFSettings::setDcBlock(), SWGSDRangel::SWGAirspyHFSettings::setDevSampleRateIndex(), SWGSDRangel::SWGAirspyHFSettings::setFileRecordName(), SWGSDRangel::SWGAirspyHFSettings::setIqCorrection(), SWGSDRangel::SWGAirspyHFSettings::setLog2Decim(), SWGSDRangel::SWGAirspyHFSettings::setLOppmTenths(), SWGSDRangel::SWGAirspyHFSettings::setReverseApiAddress(), SWGSDRangel::SWGAirspyHFSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGAirspyHFSettings::setReverseApiPort(), SWGSDRangel::SWGAirspyHFSettings::setTransverterDeltaFrequency(), SWGSDRangel::SWGAirspyHFSettings::setTransverterMode(), SWGSDRangel::SWGAirspyHFSettings::setUseAgc(), SWGSDRangel::SWGAirspyHFSettings::setUseDsp(), SWGSDRangel::SWGAirspyHFSettings::setUseLna(), and SWGSDRangel::SWGAirspyHFSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getAirspyHfSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getAirspyHfSettings()->setDevSampleRateIndex(settings.m_devSampleRateIndex);
     response.getAirspyHfSettings()->setLOppmTenths(settings.m_LOppmTenths);
     response.getAirspyHfSettings()->setLog2Decim(settings.m_log2Decim);
     response.getAirspyHfSettings()->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     response.getAirspyHfSettings()->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     response.getAirspyHfSettings()->setBandIndex(settings.m_bandIndex ? 1 : 0);
     if (response.getAirspyHfSettings()->getFileRecordName()) {
         *response.getAirspyHfSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getAirspyHfSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getAirspyHfSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getAirspyHfSettings()->getReverseApiAddress()) {
         *response.getAirspyHfSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getAirspyHfSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getAirspyHfSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getAirspyHfSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getAirspyHfSettings()->setUseAgc(settings.m_useAGC ? 1 : 0);
     response.getAirspyHfSettings()->setUseDsp(settings.m_useDSP ? 1 : 0);
     response.getAirspyHfSettings()->setUseLna(settings.m_useLNA ? 1 : 0);
     response.getAirspyHfSettings()->setAgcHigh(settings.m_agcHigh ? 1 : 0);
     response.getAirspyHfSettings()->setAttenuatorSteps(settings.m_attenuatorSteps);
     response.getAirspyHfSettings()->setDcBlock(settings.m_dcBlock ? 1 : 0);
     response.getAirspyHfSettings()->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
 }
webapiReportGet()
int AirspyHFInput::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 782 of file airspyhfinput.cpp.
References SWGSDRangel::SWGDeviceReport::getAirspyHfReport(), SWGSDRangel::SWGAirspyHFReport::init(), SWGSDRangel::SWGDeviceReport::setAirspyHfReport(), and webapiFormatDeviceReport().
Referenced by getSampleRates().
 {
     (void) errorMessage;
     response.setAirspyHfReport(new SWGSDRangel::SWGAirspyHFReport());
     response.getAirspyHfReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void AirspyHFInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const AirspyHFSettings & settings, bool force) private
Definition at line 821 of file airspyhfinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), SWGSDRangel::SWGDeviceSettings::getAirspyHfSettings(), DeviceAPI::getDeviceSetIndex(), AirspyHFSettings::m_agcHigh, AirspyHFSettings::m_attenuatorSteps, AirspyHFSettings::m_bandIndex, AirspyHFSettings::m_centerFrequency, AirspyHFSettings::m_dcBlock, m_deviceAPI, AirspyHFSettings::m_devSampleRateIndex, AirspyHFSettings::m_fileRecordName, AirspyHFSettings::m_iqCorrection, AirspyHFSettings::m_log2Decim, AirspyHFSettings::m_LOppmTenths, m_networkManager, m_networkRequest, AirspyHFSettings::m_reverseAPIAddress, AirspyHFSettings::m_reverseAPIDeviceIndex, AirspyHFSettings::m_reverseAPIPort, AirspyHFSettings::m_transverterDeltaFrequency, AirspyHFSettings::m_transverterMode, AirspyHFSettings::m_useAGC, AirspyHFSettings::m_useDSP, AirspyHFSettings::m_useLNA, SWGSDRangel::SWGAirspyHFSettings::setAgcHigh(), SWGSDRangel::SWGDeviceSettings::setAirspyHfSettings(), SWGSDRangel::SWGAirspyHFSettings::setAttenuatorSteps(), SWGSDRangel::SWGAirspyHFSettings::setBandIndex(), SWGSDRangel::SWGAirspyHFSettings::setCenterFrequency(), SWGSDRangel::SWGAirspyHFSettings::setDcBlock(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGAirspyHFSettings::setDevSampleRateIndex(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGAirspyHFSettings::setFileRecordName(), SWGSDRangel::SWGAirspyHFSettings::setIqCorrection(), SWGSDRangel::SWGAirspyHFSettings::setLog2Decim(), SWGSDRangel::SWGAirspyHFSettings::setLOppmTenths(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGAirspyHFSettings::setTransverterDeltaFrequency(), SWGSDRangel::SWGAirspyHFSettings::setTransverterMode(), SWGSDRangel::SWGAirspyHFSettings::setUseAgc(), SWGSDRangel::SWGAirspyHFSettings::setUseDsp(), and SWGSDRangel::SWGAirspyHFSettings::setUseLna().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("AirspyHF"));
     swgDeviceSettings->setAirspyHfSettings(new SWGSDRangel::SWGAirspyHFSettings());
     SWGSDRangel::SWGAirspyHFSettings *swgAirspyHFSettings = swgDeviceSettings->getAirspyHfSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgAirspyHFSettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("devSampleRateIndex") || force) {
         swgAirspyHFSettings->setDevSampleRateIndex(settings.m_devSampleRateIndex);
     }
     if (deviceSettingsKeys.contains("LOppmTenths") || force) {
         swgAirspyHFSettings->setLOppmTenths(settings.m_LOppmTenths);
     }
     if (deviceSettingsKeys.contains("log2Decim") || force) {
         swgAirspyHFSettings->setLog2Decim(settings.m_log2Decim);
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency") || force) {
         swgAirspyHFSettings->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     }
     if (deviceSettingsKeys.contains("transverterMode") || force) {
         swgAirspyHFSettings->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("bandIndex") || force) {
         swgAirspyHFSettings->setBandIndex(settings.m_bandIndex);
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgAirspyHFSettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     if (deviceSettingsKeys.contains("useAGC")) {
         swgAirspyHFSettings->setUseAgc(settings.m_useAGC ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("agcHigh")) {
         swgAirspyHFSettings->setAgcHigh(settings.m_agcHigh ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("useDSP")) {
         swgAirspyHFSettings->setUseDsp(settings.m_useDSP ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("useLNA")) {
         swgAirspyHFSettings->setUseLna(settings.m_useLNA ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("attenuatorSteps")) {
         swgAirspyHFSettings->setAttenuatorSteps(settings.m_attenuatorSteps);
     }
     if (deviceSettingsKeys.contains("dcBlock") || force) {
         swgAirspyHFSettings->setDcBlock(settings.m_dcBlock ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("iqCorrection") || force) {
         swgAirspyHFSettings->setIqCorrection(settings.m_iqCorrection ? 1 : 0);
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void AirspyHFInput::webapiReverseSendStartStop (bool start) private
Definition at line 896 of file airspyhfinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, AirspyHFSettings::m_reverseAPIAddress, AirspyHFSettings::m_reverseAPIDeviceIndex, AirspyHFSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("AirspyHF"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int AirspyHFInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 802 of file airspyhfinput.cpp.
References AirspyHFInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by getSampleRates().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int AirspyHFInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 793 of file airspyhfinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by getSampleRates().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int AirspyHFInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 645 of file airspyhfinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getAirspyHfSettings(), SWGSDRangel::SWGAirspyHFSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setAirspyHfSettings(), and webapiFormatDeviceSettings().
Referenced by getSampleRates().
 {
     (void) errorMessage;
     response.setAirspyHfSettings(new SWGSDRangel::SWGAirspyHFSettings());
     response.getAirspyHfSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int AirspyHFInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 656 of file airspyhfinput.cpp.
References AirspyHFInput::MsgConfigureAirspyHF::create(), SWGSDRangel::SWGAirspyHFSettings::getAgcHigh(), SWGSDRangel::SWGDeviceSettings::getAirspyHfSettings(), SWGSDRangel::SWGAirspyHFSettings::getAttenuatorSteps(), SWGSDRangel::SWGAirspyHFSettings::getBandIndex(), SWGSDRangel::SWGAirspyHFSettings::getCenterFrequency(), SWGSDRangel::SWGAirspyHFSettings::getDcBlock(), SWGSDRangel::SWGAirspyHFSettings::getDevSampleRateIndex(), SWGSDRangel::SWGAirspyHFSettings::getFileRecordName(), SWGSDRangel::SWGAirspyHFSettings::getIqCorrection(), SWGSDRangel::SWGAirspyHFSettings::getLog2Decim(), SWGSDRangel::SWGAirspyHFSettings::getLOppmTenths(), SWGSDRangel::SWGAirspyHFSettings::getReverseApiAddress(), SWGSDRangel::SWGAirspyHFSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGAirspyHFSettings::getReverseApiPort(), SWGSDRangel::SWGAirspyHFSettings::getTransverterDeltaFrequency(), SWGSDRangel::SWGAirspyHFSettings::getTransverterMode(), SWGSDRangel::SWGAirspyHFSettings::getUseAgc(), SWGSDRangel::SWGAirspyHFSettings::getUseDsp(), SWGSDRangel::SWGAirspyHFSettings::getUseLna(), SWGSDRangel::SWGAirspyHFSettings::getUseReverseApi(), AirspyHFSettings::m_agcHigh, AirspyHFSettings::m_attenuatorSteps, AirspyHFSettings::m_bandIndex, AirspyHFSettings::m_centerFrequency, AirspyHFSettings::m_dcBlock, AirspyHFSettings::m_devSampleRateIndex, AirspyHFSettings::m_fileRecordName, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, AirspyHFSettings::m_iqCorrection, AirspyHFSettings::m_log2Decim, AirspyHFSettings::m_LOppmTenths, AirspyHFSettings::m_reverseAPIAddress, AirspyHFSettings::m_reverseAPIDeviceIndex, AirspyHFSettings::m_reverseAPIPort, m_settings, AirspyHFSettings::m_transverterDeltaFrequency, AirspyHFSettings::m_transverterMode, AirspyHFSettings::m_useAGC, AirspyHFSettings::m_useDSP, AirspyHFSettings::m_useLNA, AirspyHFSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by getSampleRates().
 {
     (void) errorMessage;
     AirspyHFSettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getAirspyHfSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("devSampleRateIndex")) {
         settings.m_devSampleRateIndex = response.getAirspyHfSettings()->getDevSampleRateIndex();
     }
     if (deviceSettingsKeys.contains("LOppmTenths")) {
         settings.m_LOppmTenths = response.getAirspyHfSettings()->getLOppmTenths();
     }
     if (deviceSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getAirspyHfSettings()->getLog2Decim();
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency")) {
         settings.m_transverterDeltaFrequency = response.getAirspyHfSettings()->getTransverterDeltaFrequency();
     }
     if (deviceSettingsKeys.contains("transverterMode")) {
         settings.m_transverterMode = response.getAirspyHfSettings()->getTransverterMode() != 0;
     }
     if (deviceSettingsKeys.contains("bandIndex")) {
         settings.m_bandIndex = response.getAirspyHfSettings()->getBandIndex();
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getAirspyHfSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getAirspyHfSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getAirspyHfSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getAirspyHfSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getAirspyHfSettings()->getReverseApiDeviceIndex();
     }
     if (deviceSettingsKeys.contains("useAGC")) {
         settings.m_useAGC = response.getAirspyHfSettings()->getUseAgc();
     }
     if (deviceSettingsKeys.contains("agcHigh")) {
         settings.m_agcHigh = response.getAirspyHfSettings()->getAgcHigh();
     }
     if (deviceSettingsKeys.contains("useDSP")) {
         settings.m_useDSP = response.getAirspyHfSettings()->getUseDsp();
     }
     if (deviceSettingsKeys.contains("useLNA")) {
         settings.m_useLNA = response.getAirspyHfSettings()->getUseLna();
     }
     if (deviceSettingsKeys.contains("attenuatorSteps")) {
         settings.m_attenuatorSteps = response.getAirspyHfSettings()->getAttenuatorSteps();
     }
     if (deviceSettingsKeys.contains("dcBlock")) {
         settings.m_dcBlock = response.getAirspyHfSettings()->getDcBlock() != 0;
     }
     if (deviceSettingsKeys.contains("iqCorrection")) {
         settings.m_iqCorrection = response.getAirspyHfSettings()->getIqCorrection() != 0;
     }
     MsgConfigureAirspyHF *msg = MsgConfigureAirspyHF::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureAirspyHF *msgToGUI = MsgConfigureAirspyHF::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
loHighLimitFreqHF
const qint64 AirspyHFInput::loHighLimitFreqHF = 31000000L static
Definition at line 145 of file airspyhfinput.h.
Referenced by setDeviceCenterFrequency(), and AirspyHFGui::updateFrequencyLimits().
loHighLimitFreqVHF
const qint64 AirspyHFInput::loHighLimitFreqVHF = 260000000L static
Definition at line 147 of file airspyhfinput.h.
Referenced by setDeviceCenterFrequency(), and AirspyHFGui::updateFrequencyLimits().
loLowLimitFreqHF
const qint64 AirspyHFInput::loLowLimitFreqHF = 9000L static
Definition at line 144 of file airspyhfinput.h.
Referenced by AirspyHFGui::updateFrequencyLimits().
loLowLimitFreqVHF
const qint64 AirspyHFInput::loLowLimitFreqVHF = 60000000L static
Definition at line 146 of file airspyhfinput.h.
Referenced by AirspyHFGui::updateFrequencyLimits().
m_airspyHFThread
AirspyHFThread* AirspyHFInput::m_airspyHFThread private
Definition at line 154 of file airspyhfinput.h.
Referenced by applySettings(), start(), and stop().
m_dev
airspyhf_device_t* AirspyHFInput::m_dev private
Definition at line 153 of file airspyhfinput.h.
Referenced by applySettings(), closeDevice(), openDevice(), setDeviceCenterFrequency(), and start().
m_deviceAPI
DeviceAPI* AirspyHFInput::m_deviceAPI private
Definition at line 150 of file airspyhfinput.h.
Referenced by AirspyHFInput(), applySettings(), handleMessage(), openDevice(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~AirspyHFInput().
m_deviceDescription
QString AirspyHFInput::m_deviceDescription private
Definition at line 155 of file airspyhfinput.h.
Referenced by closeDevice(), and getDeviceDescription().
m_fileSink
FileRecord* AirspyHFInput::m_fileSink private
File sink to record device I/Q output.
Definition at line 158 of file airspyhfinput.h.
Referenced by AirspyHFInput(), applySettings(), handleMessage(), and ~AirspyHFInput().
m_mutex
QMutex AirspyHFInput::m_mutex private
Definition at line 151 of file airspyhfinput.h.
Referenced by applySettings(), start(), and stop().
m_networkManager
QNetworkAccessManager* AirspyHFInput::m_networkManager private
Definition at line 159 of file airspyhfinput.h.
Referenced by AirspyHFInput(), webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~AirspyHFInput().
m_networkRequest
QNetworkRequest AirspyHFInput::m_networkRequest private
Definition at line 160 of file airspyhfinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool AirspyHFInput::m_running private
Definition at line 157 of file airspyhfinput.h.
Referenced by start(), stop(), and ~AirspyHFInput().
m_sampleRates
std::vector<uint32_t> AirspyHFInput::m_sampleRates private
Definition at line 156 of file airspyhfinput.h.
Referenced by applySettings(), getSampleRate(), getSampleRates(), openDevice(), and start().
m_settings
AirspyHFSettings AirspyHFInput::m_settings private
Definition at line 152 of file airspyhfinput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), serialize(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
The documentation for this class was generated from the following files:
plugins/samplesource/airspyhf/airspyhfinput.h
plugins/samplesource/airspyhf/airspyhfinput.cpp