SDRAngel: leansdr::s2_interleaver Struct Reference
leansdr::s2_interleaver Struct Reference
#include <dvbs2.h>
Public Member Functions
s2_interleaver (scheduler *sch, pipebuf< fecframe< hard_sb >> &_in, pipebuf< plslot< hard_ss >> &_out)
void run ()
Public Member Functions inherited from leansdr::runnable
runnable (scheduler *_sch, const char *name)
Public Member Functions inherited from leansdr::runnable_common
runnable_common (const char *_name)
virtual ~runnable_common ()
virtual void shutdown ()
Static Private Member Functions
static void serialize_qpsk (const hard_sb *pin, int nslots, plslot< hard_ss > *pout)
static void interleave (int bps, int rows, const hard_sb *pin, int nslots, bool msb_first, plslot< hard_ss > *pout)
template<int MSB_FIRST, int BPS>
static void interleave (int rows, const hard_sb *pin, int nslots, plslot< hard_ss > *pout)
template<int BPS>
static void split_byte (const hard_sb *pi, int stride, hard_sb accs[BPS])
template<int MSB_FIRST, int BPS>
static void pop_symbols (hard_sb accs[BPS], hard_ss **ps, int ns)
static void interleave4050 (const hard_sb *pin, int nslots, plslot< hard_ss > *pout)
Private Attributes
pipereader< fecframe< hard_sb > > in
pipewriter< plslot< hard_ss > > out
Additional Inherited Members
Public Attributes inherited from leansdr::runnable_common
const char * name
Protected Attributes inherited from leansdr::runnable
scheduler * sch
Detailed Description
Definition at line 1227 of file dvbs2.h.
Constructor & Destructor Documentation
s2_interleaver()
leansdr::s2_interleaver::s2_interleaver (scheduler * sch, pipebuf< fecframe< hard_sb >> & _in, pipebuf< plslot< hard_ss >> & _out) inline
Definition at line 1229 of file dvbs2.h.
         : runnable(sch, "S2 interleaver"),
           in(_in), out(_out, 1 + 360)
     {
     }
Member Function Documentation
interleave() [1/2]
static void leansdr::s2_interleaver::interleave (int bps, int rows, const hard_sb * pin, int nslots, bool msb_first, plslot< hard_ss > * pout) inline static private
Definition at line 1368 of file dvbs2.h.
References leansdr::fail().
     {
         void (*func)(int rows, const hard_sb *pin, int nslots,
                      plslot<hard_ss> *pout) = 0;
         if (msb_first)
             switch (bps)
             {
             case 2:
                 func = interleave<1, 2>;
                 break;
             case 3:
                 func = interleave<1, 3>;
                 break;
             case 4:
                 func = interleave<1, 4>;
                 break;
             case 5:
                 func = interleave<1, 5>;
                 break;
             default:
                 fail("Bad bps");
             }
         else
             switch (bps)
             {
             case 2:
                 func = interleave<0, 2>;
                 break;
             case 3:
                 func = interleave<0, 3>;
                 break;
             case 4:
                 func = interleave<0, 4>;
                 break;
             case 5:
                 func = interleave<0, 5>;
                 break;
             default:
                 fail("Bad bps");
             }
         (*func)(rows, pin, nslots, pout);
     }
interleave() [2/2]
template<int MSB_FIRST, int BPS> static void leansdr::s2_interleaver::interleave (int rows, const hard_sb * pin, int nslots, plslot< hard_ss > * pout) inline static private
Definition at line 1413 of file dvbs2.h.
References leansdr::fatal(), i, leansdr::plslot< SOFTSYMB >::is_pls, and leansdr::plslot< SOFTSYMB >::symbols.
     {
         if (BPS == 4 && rows == 4050 && MSB_FIRST)
             return interleave4050(pin, nslots, pout);
         if (rows % 8)
             fatal("modcod/framesize combination not supported\n");
         int stride = rows / 8; // Offset to next column, in bytes
         if (nslots % 4)
             fatal("Bug: Truncated byte");
         // plslot::symbols[] are not packed across slots,
         // so we need tos split bytes at boundaries.
         for (; nslots; nslots -= 4)
         {
             const hard_sb *pi;
             hard_sb accs[BPS]; // One accumulator per column
             hard_ss *ps;
             // Slot 0 (mod 4): 88+2
             pout->is_pls = false;
             ps = pout->symbols;
             for (int i = 0; i < 11; ++i)
             {
                 split_byte<BPS>(pin++, stride, accs);
                 pop_symbols<MSB_FIRST, BPS>(accs, &ps, 8);
             }
             split_byte<BPS>(pin++, stride, accs);
             pop_symbols<MSB_FIRST, BPS>(accs, &ps, 2);
             ++pout;
             // Slot 1 (mod 4): 6+80+4
             pout->is_pls = false;
             ps = pout->symbols;
             pop_symbols<MSB_FIRST, BPS>(accs, &ps, 6);
             for (int i = 0; i < 10; ++i)
             {
                 split_byte<BPS>(pin++, stride, accs);
                 pop_symbols<MSB_FIRST, BPS>(accs, &ps, 8);
             }
             split_byte<BPS>(pin++, stride, accs);
             pop_symbols<MSB_FIRST, BPS>(accs, &ps, 4);
             ++pout;
             // Slot 2 (mod 4): 4+80+6
             pout->is_pls = false;
             ps = pout->symbols;
             pop_symbols<MSB_FIRST, BPS>(accs, &ps, 4);
             for (int i = 0; i < 10; ++i)
             {
                 split_byte<BPS>(pin++, stride, accs);
                 pop_symbols<MSB_FIRST, BPS>(accs, &ps, 8);
             }
             split_byte<BPS>(pin++, stride, accs);
             pop_symbols<MSB_FIRST, BPS>(accs, &ps, 6);
             ++pout;
             // Slot 3 (mod 4): 2+88
             pout->is_pls = false;
             ps = pout->symbols;
             pop_symbols<MSB_FIRST, BPS>(accs, &ps, 2);
             for (int i = 0; i < 11; ++i)
             {
                 split_byte<BPS>(pin++, stride, accs);
                 pop_symbols<MSB_FIRST, BPS>(accs, &ps, 8);
             }
             ++pout;
         }
     }
interleave4050()
static void leansdr::s2_interleaver::interleave4050 (const hard_sb * pin, int nslots, plslot< hard_ss > * pout) inline static private
Definition at line 1506 of file dvbs2.h.
References leansdr::plslot< SOFTSYMB >::is_pls, leansdr::plslot< SOFTSYMB >::LENGTH, and leansdr::plslot< SOFTSYMB >::symbols.
     {
         const hard_sb *pin0 = pin;
         int rows = 4050;
         hard_sb accs[4]; // One accumulator per column
         int nacc = 0;    // Bits in each column accumulator
         for (; nslots; --nslots, ++pout)
         {
             pout->is_pls = false;
             hard_ss *ps = pout->symbols;
             for (int ns = pout->LENGTH; ns--; ++ps)
             {
                 if (!nacc)
                 {
                     if (nslots == 1 && ns == 1)
                     {
                         // Special case just to avoid reading beyond end of buffer
                         accs[0] = pin[0];
                         accs[1] = (pin[506] << 2) | (pin[507] >> 6);
                         accs[2] = (pin[1012] << 4) | (pin[1013] >> 4);
                         accs[3] = (pin[1518] << 6);
                     }
                     else
                     {
                         accs[0] = pin[0];
                         accs[1] = (pin[506] << 2) | (pin[507] >> 6);
                         accs[2] = (pin[1012] << 4) | (pin[1013] >> 4);
                         accs[3] = (pin[1518] << 6) | (pin[1519] >> 2);
                     }
                     ++pin;
                     nacc = 8;
                 }
                 hard_ss symb = 0;
                 for (int b = 0; b < 4; ++b)
                 {
                     symb = (symb << 1) | (accs[b] >> 7);
                     accs[b] <<= 1;
                 }
                 --nacc;
                 *ps = symb;
             }
         }
     }
pop_symbols()
template<int MSB_FIRST, int BPS> static void leansdr::s2_interleaver::pop_symbols (hard_sb accs[BPS], hard_ss ** ps, int ns) inline static private
Definition at line 1486 of file dvbs2.h.
References i.
     {
         for (int i = 0; i < ns; ++i)
         {
             hard_ss symb = 0;
             // Check unrolling and constant propagation.
             for (int b = 0; b < BPS; ++b)
                 if (MSB_FIRST)
                     symb = (symb << 1) | (accs[b] >> 7);
                 else
                     symb = (symb << 1) | (accs[BPS - 1 - b] >> 7);
             for (int b = 0; b < BPS; ++b)
                 accs[b] <<= 1;
             *(*ps)++ = symb;
         }
     }
run()
void leansdr::s2_interleaver::run () inline virtual
Reimplemented from leansdr::runnable_common.
Definition at line 1236 of file dvbs2.h.
References leansdr::check_modcod(), leansdr::FEC35, leansdr::s2_pls::framebits(), leansdr::plslot< SOFTSYMB >::is_pls, leansdr::s2_pls::modcod, leansdr::modcod_info::nslots_nf, leansdr::modcod_info::nsymbols, leansdr::plslot< SOFTSYMB >::pls, leansdr::modcod_info::rate, leansdr::pipereader< T >::rd(), leansdr::pipereader< T >::read(), leansdr::pipereader< T >::readable(), leansdr::s2_pls::sf, leansdr::pipewriter< T >::wr(), leansdr::pipewriter< T >::writable(), and leansdr::pipewriter< T >::written().
     {
         while (in.readable() >= 1)
         {
             const s2_pls *pls = &in.rd()->pls;
             const modcod_info *mcinfo = check_modcod(pls->modcod);
             int nslots = pls->sf ? mcinfo->nslots_nf / 4 : mcinfo->nslots_nf;
             if (out.writable() < 1 + nslots)
                 return;
             const hard_sb *pbytes = in.rd()->bytes;
             // Output pseudo slot with PLS.
             plslot<hard_ss> *ppls = out.wr();
             ppls->is_pls = true;
             ppls->pls = *pls;
             out.written(1);
             // Interleave
             plslot<hard_ss> *pout = out.wr();
             if (mcinfo->nsymbols == 4)
                 serialize_qpsk(pbytes, nslots, pout);
             else
             {
                 int bps = log2(mcinfo->nsymbols);
                 int rows = pls->framebits() / bps;
                 if (mcinfo->nsymbols == 8 && mcinfo->rate == FEC35)
                     interleave(bps, rows, pbytes, nslots, false, pout);
                 else
                     interleave(bps, rows, pbytes, nslots, true, pout);
             }
             in.read(1);
             out.written(nslots);
         }
     }
serialize_qpsk()
static void leansdr::s2_interleaver::serialize_qpsk (const hard_sb * pin, int nslots, plslot< hard_ss > * pout) inline static private
Definition at line 1271 of file dvbs2.h.
References leansdr::fail(), leansdr::fatal(), i, leansdr::plslot< SOFTSYMB >::is_pls, leansdr::plslot< SOFTSYMB >::LENGTH, and leansdr::plslot< SOFTSYMB >::symbols.
     {
 #if 0 // For reference
       hard_sb acc;
       int nacc = 0;
       for ( ; nslots; --nslots,++pout ) {
     pout->is_pls = false;
     hard_ss *ps = pout->symbols;
     for ( int ns=pout->LENGTH; ns--; ++ps ) {
       if ( nacc < 2 ) { acc=*pin++; nacc=8; }
       *ps = acc>>6;
       acc <<= 2;
       nacc -= 2;
     }
       }
       if ( nacc ) fail("Bug: s2_interleaver");
 #else
         if (nslots % 2)
             fatal("Bug: Truncated byte");
         for (; nslots; nslots -= 2)
         {
             hard_sb b;
             hard_ss *ps;
             // Slot 0 (mod 2)
             pout->is_pls = false;
             ps = pout->symbols;
             for (int i = 0; i < 22; ++i)
             {
                 b = *pin++;
                 *ps++ = (b >> 6);
                 *ps++ = (b >> 4) & 3;
                 *ps++ = (b >> 2) & 3;
                 *ps++ = (b)&3;
             }
             b = *pin++;
             *ps++ = (b >> 6);
             *ps++ = (b >> 4) & 3;
             // Slot 1 (mod 2)
             ++pout;
             pout->is_pls = false;
             ps = pout->symbols;
             *ps++ = (b >> 2) & 3;
             *ps++ = (b)&3;
             for (int i = 0; i < 22; ++i)
             {
                 b = *pin++;
                 *ps++ = (b >> 6);
                 *ps++ = (b >> 4) & 3;
                 *ps++ = (b >> 2) & 3;
                 *ps++ = (b)&3;
             }
             ++pout;
         }
 #endif
     }
split_byte()
template<int BPS> static void leansdr::s2_interleaver::split_byte (const hard_sb * pi, int stride, hard_sb accs[BPS]) inline static private
Definition at line 1478 of file dvbs2.h.
     {
         // TBD Pass stride as template parameter.
         for (int b = 0; b < BPS; ++b, pi += stride)
             accs[b] = *pi;
     }
Member Data Documentation
in
pipereader<fecframe<hard_sb> > leansdr::s2_interleaver::in private
Definition at line 1551 of file dvbs2.h.
out
pipewriter<plslot<hard_ss> > leansdr::s2_interleaver::out private
Definition at line 1552 of file dvbs2.h.
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/dvbs2.h