SDRAngel: qrtplib::RTPSession Class Reference
qrtplib::RTPSession Class Reference
#include <rtpsession.h>
Public Member Functions
RTPSession (RTPRandom *rnd=0)
virtual ~RTPSession ()
int Create (const RTPSessionParams &sessparams, RTPTransmitter *transmitter)
void Destroy ()
void BYEDestroy (const RTPTime &maxwaittime, const void *reason, std::size_t reasonlength)
bool IsActive ()
uint32_t GetLocalSSRC ()
int AddDestination (const RTPAddress &addr)
int DeleteDestination (const RTPAddress &addr)
void ClearDestinations ()
bool SupportsMulticasting ()
int JoinMulticastGroup (const RTPAddress &addr)
int LeaveMulticastGroup (const RTPAddress &addr)
int SendPacket (const void *data, std::size_t len)
int SendPacket (const void *data, std::size_t len, uint8_t pt, bool mark, uint32_t timestampinc)
int SendPacketEx (const void *data, std::size_t len, uint16_t hdrextID, const void *hdrextdata, std::size_t numhdrextwords)
int SendPacketEx (const void *data, std::size_t len, uint8_t pt, bool mark, uint32_t timestampinc, uint16_t hdrextID, const void *hdrextdata, std::size_t numhdrextwords)
int SendRTCPAPPPacket (uint8_t subtype, const uint8_t name[4], const void *appdata, std::size_t appdatalen)
int SendRawData (const void *data, std::size_t len, bool usertpchannel)
int SetDefaultPayloadType (uint8_t pt)
int SetDefaultMark (bool m)
int SetDefaultTimestampIncrement (uint32_t timestampinc)
int IncrementTimestamp (uint32_t inc)
int IncrementTimestampDefault ()
int SetPreTransmissionDelay (const RTPTime &delay)
RTPTransmissionInfo * GetTransmissionInfo ()
void DeleteTransmissionInfo (RTPTransmissionInfo *inf)
RTPTime GetRTCPDelay ()
int BeginDataAccess ()
bool GotoFirstSource ()
bool GotoNextSource ()
bool GotoPreviousSource ()
bool GotoFirstSourceWithData ()
bool GotoNextSourceWithData ()
bool GotoPreviousSourceWithData ()
RTPSourceData * GetCurrentSourceInfo ()
RTPSourceData * GetSourceInfo (uint32_t ssrc)
RTPPacket * GetNextPacket ()
uint16_t GetNextSequenceNumber () const
void DeletePacket (RTPPacket *p)
int EndDataAccess ()
int SetReceiveMode (RTPTransmitter::ReceiveMode m)
int AddToIgnoreList (const RTPAddress &addr)
int DeleteFromIgnoreList (const RTPAddress &addr)
void ClearIgnoreList ()
int AddToAcceptList (const RTPAddress &addr)
int DeleteFromAcceptList (const RTPAddress &addr)
void ClearAcceptList ()
int SetMaximumPacketSize (std::size_t s)
int SetSessionBandwidth (double bw)
int SetTimestampUnit (double u)
void SetNameInterval (int count)
void SetEMailInterval (int count)
void SetLocationInterval (int count)
void SetPhoneInterval (int count)
void SetToolInterval (int count)
void SetNoteInterval (int count)
int SetLocalName (const void *s, std::size_t len)
int SetLocalEMail (const void *s, std::size_t len)
int SetLocalLocation (const void *s, std::size_t len)
int SetLocalPhone (const void *s, std::size_t len)
int SetLocalTool (const void *s, std::size_t len)
int SetLocalNote (const void *s, std::size_t len)
Protected Member Functions
virtual RTPTransmitter * NewUserDefinedTransmitter ()
virtual void OnRTPPacket (RTPPacket *pack, const RTPTime &receivetime, const RTPAddress *senderaddress)
virtual void OnRTCPCompoundPacket (RTCPCompoundPacket *pack, const RTPTime &receivetime, const RTPAddress *senderaddress)
virtual void OnSSRCCollision (RTPSourceData *srcdat, const RTPAddress *senderaddress, bool isrtp)
virtual void OnCNAMECollision (RTPSourceData *srcdat, const RTPAddress *senderaddress, const uint8_t *cname, std::size_t cnamelength)
virtual void OnNewSource (RTPSourceData *srcdat)
virtual void OnRemoveSource (RTPSourceData *srcdat)
virtual void OnTimeout (RTPSourceData *srcdat)
virtual void OnBYETimeout (RTPSourceData *srcdat)
virtual void OnAPPPacket (RTCPAPPPacket *apppacket, const RTPTime &receivetime, const RTPAddress *senderaddress)
virtual void OnUnknownPacketType (RTCPPacket *rtcppack, const RTPTime &receivetime, const RTPAddress *senderaddress)
virtual void OnUnknownPacketFormat (RTCPPacket *rtcppack, const RTPTime &receivetime, const RTPAddress *senderaddress)
virtual void OnNoteTimeout (RTPSourceData *srcdat)
virtual void OnRTCPSenderReport (RTPSourceData *srcdat)
virtual void OnRTCPReceiverReport (RTPSourceData *srcdat)
virtual void OnRTCPSDESItem (RTPSourceData *srcdat, RTCPSDESPacket::ItemType t, const void *itemdata, std::size_t itemlength)
virtual void OnRTCPSDESPrivateItem (RTPSourceData *srcdat, const void *prefixdata, std::size_t prefixlen, const void *valuedata, std::size_t valuelen)
virtual void OnBYEPacket (RTPSourceData *srcdat)
virtual void OnSendRTCPCompoundPacket (RTCPCompoundPacket *pack)
void SetChangeOutgoingData (bool change)
void SetChangeIncomingData (bool change)
virtual int OnChangeRTPOrRTCPData (const void *origdata, std::size_t origlen, bool isrtp, void **senddata, std::size_t *sendlen)
virtual void OnSentRTPOrRTCPData (void *senddata, std::size_t sendlen, bool isrtp)
virtual bool OnChangeIncomingData (RTPRawPacket *rawpack)
virtual void OnValidatedRTPPacket (RTPSourceData *srcdat, RTPPacket *rtppack, bool isonprobation, bool *ispackethandled)
Private Member Functions
int InternalCreate (const RTPSessionParams &sessparams)
int CreateCNAME (uint8_t *buffer, std::size_t *bufferlength, bool resolve)
int ProcessPolledData ()
int ProcessRTCPCompoundPacket (RTCPCompoundPacket &rtcpcomppack, RTPRawPacket *pack)
RTPRandom * GetRandomNumberGenerator (RTPRandom *r)
int SendRTPData (const void *data, std::size_t len)
int SendRTCPData (const void *data, std::size_t len)
Private Attributes
RTPRandom * rtprnd
bool deletertprnd
RTPTransmitter * rtptrans
bool created
bool deletetransmitter
bool usingpollthread
bool acceptownpackets
bool useSR_BYEifpossible
std::size_t maxpacksize
double sessionbandwidth
double controlfragment
double sendermultiplier
double byemultiplier
double membermultiplier
double collisionmultiplier
double notemultiplier
bool sentpackets
bool m_changeIncomingData
bool m_changeOutgoingData
RTPSessionSources sources
RTPPacketBuilder packetbuilder
RTCPScheduler rtcpsched
RTCPPacketBuilder rtcpbuilder
RTPCollisionList collisionlist
std::list< RTCPCompoundPacket * > byepackets
Friends
class RTPSessionSources
class RTCPSessionPacketBuilder
Detailed Description
High level class for using RTP. For most RTP based applications, the RTPSession class will probably be the one to use. It handles the RTCP part completely internally, so the user can focus on sending and receiving the actual data. In case you want to use SRTP, you should create an RTPSecureSession derived class.
Note
The RTPSession class is not meant to be thread safe. The user should use some kind of locking mechanism to prevent different threads from using the same RTPSession instance.
Definition at line 76 of file rtpsession.h.
Constructor & Destructor Documentation
RTPSession()
qrtplib::RTPSession::RTPSession (RTPRandom * rnd = 0)
Constructs an RTPSession instance, optionally using a specific instance of a random number generator, and optionally installing a memory manager. Constructs an RTPSession instance, optionally using a specific instance of a random number generator, and optionally installing a memory manager. If no random number generator is specified, the RTPSession object will try to use either a RTPRandomURandom or RTPRandomRandS instance. If neither is available on the current platform, a RTPRandomRand48 instance will be used instead. By specifying a random number generator yourself, it is possible to use the same generator in several RTPSession instances.
Definition at line 60 of file rtpsession.cpp.
References created, qrtplib::RTPTimeInitializerObject::Dummy(), m_changeIncomingData, m_changeOutgoingData, and qrtplib::timeinit.
                                    :
         rtprnd(GetRandomNumberGenerator(r)),
         sources(*this),
         packetbuilder(*rtprnd),
         rtcpsched(sources, *rtprnd),
         rtcpbuilder(sources, packetbuilder)
 {
     // We're not going to set these flags in Create, so that the constructor of a derived class
     // can already change them
     m_changeIncomingData = false;
     m_changeOutgoingData = false;
     created = false;
     timeinit.Dummy();
     //std::cout << (void *)(rtprnd) << std::endl;
 }
~RTPSession()
qrtplib::RTPSession::~RTPSession () virtual
Definition at line 78 of file rtpsession.cpp.
References deletertprnd, Destroy(), and rtprnd.
 {
     Destroy();
     if (deletertprnd)
         delete rtprnd;
 }
Member Function Documentation
AddDestination()
int qrtplib::RTPSession::AddDestination (const RTPAddress & addr)
Adds addr to the list of destinations.
Definition at line 415 of file rtpsession.cpp.
References qrtplib::RTPTransmitter::AddDestination(), created, ERR_RTP_SESSION_NOTCREATED, and rtptrans.
Referenced by RTPSink::addDestination(), and RTPSink::setDestination().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     return rtptrans->AddDestination(addr);
 }
AddToAcceptList()
int qrtplib::RTPSession::AddToAcceptList (const RTPAddress & addr)
Adds addr to the list of addresses to accept.
Definition at line 814 of file rtpsession.cpp.
References qrtplib::RTPTransmitter::AddToAcceptList(), created, ERR_RTP_SESSION_NOTCREATED, and rtptrans.
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     return rtptrans->AddToAcceptList(addr);
 }
AddToIgnoreList()
int qrtplib::RTPSession::AddToIgnoreList (const RTPAddress & addr)
Adds addr to the list of addresses to ignore.
Definition at line 793 of file rtpsession.cpp.
References qrtplib::RTPTransmitter::AddToIgnoreList(), created, ERR_RTP_SESSION_NOTCREATED, and rtptrans.
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     return rtptrans->AddToIgnoreList(addr);
 }
BeginDataAccess()
int qrtplib::RTPSession::BeginDataAccess ()
The following member functions (till EndDataAccess}) need to be accessed between a call to BeginDataAccess and EndDataAccess. The BeginDataAccess function makes sure that the poll thread won't access the source table at the same time that you're using it. When the EndDataAccess is called, the lock on the source table is freed again.
Definition at line 699 of file rtpsession.cpp.
References created, and ERR_RTP_SESSION_NOTCREATED.
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     return 0;
 }
BYEDestroy()
void qrtplib::RTPSession::BYEDestroy (const RTPTime & maxwaittime, const void * reason, std::size_t reasonlength)
Sends a BYE packet and leaves the session. Sends a BYE packet and leaves the session. At most a time maxwaittime will be waited to send the BYE packet. If this time expires, the session will be left without sending a BYE packet. The BYE packet will contain as reason for leaving reason with length reasonlength.
Definition at line 321 of file rtpsession.cpp.
References qrtplib::RTCPPacketBuilder::BuildBYEPacket(), byepackets, qrtplib::RTPCollisionList::Clear(), qrtplib::RTPSources::Clear(), collisionlist, created, qrtplib::RTPTime::CurrentTime(), deletetransmitter, qrtplib::RTPPacketBuilder::Destroy(), qrtplib::RTCPPacketBuilder::Destroy(), qrtplib::RTCPCompoundPacket::GetCompoundPacketData(), qrtplib::RTCPCompoundPacket::GetCompoundPacketLength(), qrtplib::RTCPScheduler::IsTime(), OnSendRTCPCompoundPacket(), packetbuilder, qrtplib::RTCPScheduler::Reset(), RTCP_BYE_MAXREASONLENGTH, rtcpbuilder, rtcpsched, rtptrans, qrtplib::RTCPScheduler::ScheduleBYEPacket(), SendRTCPData(), sentpackets, sources, useSR_BYEifpossible, and qrtplib::RTPTime::Wait().
Referenced by RTPSink::~RTPSink().
 {
     if (!created)
         return;
     // first, stop the thread so we have full control over all components
     RTPTime stoptime = RTPTime::CurrentTime();
     stoptime += maxwaittime;
     // add bye packet to the list if we've sent data
     RTCPCompoundPacket *pack;
     if (sentpackets)
     {
         int status;
         reasonlength = (reasonlength > RTCP_BYE_MAXREASONLENGTH) ? RTCP_BYE_MAXREASONLENGTH : reasonlength;
         status = rtcpbuilder.BuildBYEPacket(&pack, reason, reasonlength, useSR_BYEifpossible);
         if (status >= 0)
         {
             byepackets.push_back(pack);
             if (byepackets.size() == 1)
                 rtcpsched.ScheduleBYEPacket(pack->GetCompoundPacketLength());
         }
     }
     if (!byepackets.empty())
     {
         bool done = false;
         while (!done)
         {
             RTPTime curtime = RTPTime::CurrentTime();
             if (curtime >= stoptime)
                 done = true;
             if (rtcpsched.IsTime())
             {
                 pack = *(byepackets.begin());
                 byepackets.pop_front();
                 SendRTCPData(pack->GetCompoundPacketData(), pack->GetCompoundPacketLength());
                 OnSendRTCPCompoundPacket(pack); // we'll place this after the actual send to avoid tampering
                 delete pack;
                 if (!byepackets.empty()) // more bye packets to send, schedule them
                     rtcpsched.ScheduleBYEPacket((*(byepackets.begin()))->GetCompoundPacketLength());
                 else
                     done = true;
             }
             if (!done)
                 RTPTime::Wait(RTPTime(0, 100000));
         }
     }
     if (deletetransmitter)
         delete rtptrans;
     packetbuilder.Destroy();
     rtcpbuilder.Destroy();
     rtcpsched.Reset();
     collisionlist.Clear();
     sources.Clear();
     // clear rest of bye packets
     std::list<RTCPCompoundPacket *>::const_iterator it;
     for (it = byepackets.begin(); it != byepackets.end(); it++)
         delete *it;
     byepackets.clear();
     created = false;
 }
ClearAcceptList()
void qrtplib::RTPSession::ClearAcceptList ()
Clears the list of addresses to accept.
Definition at line 828 of file rtpsession.cpp.
References qrtplib::RTPTransmitter::ClearAcceptList(), created, and rtptrans.
 {
     if (!created)
         return;
     rtptrans->ClearAcceptList();
 }
ClearDestinations()
void qrtplib::RTPSession::ClearDestinations ()
Clears the list of destinations.
Definition at line 429 of file rtpsession.cpp.
References qrtplib::RTPTransmitter::ClearDestinations(), created, and rtptrans.
Referenced by RTPSink::setDestination().
 {
     if (!created)
         return;
     rtptrans->ClearDestinations();
 }
ClearIgnoreList()
void qrtplib::RTPSession::ClearIgnoreList ()
Clears the list of addresses to ignore.
Definition at line 807 of file rtpsession.cpp.
References qrtplib::RTPTransmitter::ClearIgnoreList(), created, and rtptrans.
 {
     if (!created)
         return;
     rtptrans->ClearIgnoreList();
 }
Create()
int qrtplib::RTPSession::Create (const RTPSessionParams & sessparams, RTPTransmitter * transmitter)
Creates an RTP session. This function creates an RTP session with parameters sessparams, which will use a transmitter corresponding to proto. Parameters for this transmitter can be specified as well. If proto is of type RTPTransmitter::UserDefinedProto, the NewUserDefinedTransmitter function must be implemented.Creates an RTP session using transmitter as transmission component. This function creates an RTP session with parameters sessparams, which will use the transmission component transmitter. Initialization and destruction of the transmitter will not be done by the RTPSession class if this Create function is used. This function can be useful if you which to reuse the transmission component in another RTPSession instance, once the original RTPSession isn't using the transmitter anymore.
Definition at line 145 of file rtpsession.cpp.
References created, deletetransmitter, ERR_RTP_SESSION_ALREADYCREATED, ERR_RTP_SESSION_MAXPACKETSIZETOOSMALL, qrtplib::RTPSessionParams::GetMaximumPacketSize(), qrtplib::RTPSessionParams::GetSenderReportForBYE(), InternalCreate(), qrtplib::RTPSessionParams::IsUsingPollThread(), maxpacksize, RTP_MINPACKETSIZE, rtptrans, sentpackets, qrtplib::RTPTransmitter::SetMaximumPacketSize(), useSR_BYEifpossible, and usingpollthread.
Referenced by RTPSink::RTPSink().
 {
     int status;
     if (created)
         return ERR_RTP_SESSION_ALREADYCREATED;
     usingpollthread = sessparams.IsUsingPollThread();
     useSR_BYEifpossible = sessparams.GetSenderReportForBYE();
     sentpackets = false;
     // Check max packet size
     if ((maxpacksize = sessparams.GetMaximumPacketSize()) < RTP_MINPACKETSIZE)
         return ERR_RTP_SESSION_MAXPACKETSIZETOOSMALL;
     rtptrans = transmitter;
     if ((status = rtptrans->SetMaximumPacketSize(maxpacksize)) < 0)
         return status;
     deletetransmitter = false;
     return InternalCreate(sessparams);
 }
CreateCNAME()
int qrtplib::RTPSession::CreateCNAME (uint8_t * buffer, std::size_t * bufferlength, bool resolve) private
Definition at line 1145 of file rtpsession.cpp.
References RTCP_SDES_MAXITEMLENGTH.
Referenced by InternalCreate().
 {
     (void) resolve;
     buffer[*bufferlength - 1] = 0;
     std::size_t offset = strlen((const char *) buffer);
     if (offset < (*bufferlength - 1))
         buffer[offset] = (uint8_t) '@';
     offset++;
     std::size_t buflen2 = *bufferlength - offset;
     QString hostnameStr = QHostInfo::localHostName();
     int hostnameSize = hostnameStr.size();
     strncpy((char * )(buffer + offset), hostnameStr.toStdString().c_str(), buflen2);
     *bufferlength = offset + hostnameSize;
     if (*bufferlength > RTCP_SDES_MAXITEMLENGTH)
         *bufferlength = RTCP_SDES_MAXITEMLENGTH;
     return 0;
 }
DeleteDestination()
int qrtplib::RTPSession::DeleteDestination (const RTPAddress & addr)
Deletes addr from the list of destinations.
Definition at line 422 of file rtpsession.cpp.
References created, qrtplib::RTPTransmitter::DeleteDestination(), ERR_RTP_SESSION_NOTCREATED, and rtptrans.
Referenced by RTPSink::deleteDestination(), and RTPSink::setDestination().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     return rtptrans->DeleteDestination(addr);
 }
DeleteFromAcceptList()
int qrtplib::RTPSession::DeleteFromAcceptList (const RTPAddress & addr)
Deletes addr from the list of addresses to accept.
Definition at line 821 of file rtpsession.cpp.
References created, qrtplib::RTPTransmitter::DeleteFromAcceptList(), ERR_RTP_SESSION_NOTCREATED, and rtptrans.
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     return rtptrans->DeleteFromAcceptList(addr);
 }
DeleteFromIgnoreList()
int qrtplib::RTPSession::DeleteFromIgnoreList (const RTPAddress & addr)
Deletes addr from the list of addresses to ignore.
Definition at line 800 of file rtpsession.cpp.
References created, qrtplib::RTPTransmitter::DeleteFromIgnoreList(), ERR_RTP_SESSION_NOTCREATED, and rtptrans.
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     return rtptrans->DeleteFromIgnoreList(addr);
 }
DeletePacket()
void qrtplib::RTPSession::DeletePacket (RTPPacket * p)
Frees the memory used by p.
Definition at line 774 of file rtpsession.cpp.
 {
     delete p;
 }
DeleteTransmissionInfo()
void qrtplib::RTPSession::DeleteTransmissionInfo (RTPTransmissionInfo * inf)
Frees the memory used by the transmission information inf.
Definition at line 681 of file rtpsession.cpp.
References created, qrtplib::RTPTransmitter::DeleteTransmissionInfo(), and rtptrans.
 {
     if (!created)
         return;
     rtptrans->DeleteTransmissionInfo(inf);
 }
Destroy()
void qrtplib::RTPSession::Destroy ()
Leaves the session without sending a BYE packet.
Definition at line 299 of file rtpsession.cpp.
References byepackets, qrtplib::RTPCollisionList::Clear(), qrtplib::RTPSources::Clear(), collisionlist, created, deletetransmitter, qrtplib::RTPPacketBuilder::Destroy(), qrtplib::RTCPPacketBuilder::Destroy(), packetbuilder, qrtplib::RTCPScheduler::Reset(), rtcpbuilder, rtcpsched, rtptrans, and sources.
Referenced by ~RTPSession().
 {
     if (!created)
         return;
     if (deletetransmitter)
         delete rtptrans;
     packetbuilder.Destroy();
     rtcpbuilder.Destroy();
     rtcpsched.Reset();
     collisionlist.Clear();
     sources.Clear();
     std::list<RTCPCompoundPacket *>::const_iterator it;
     for (it = byepackets.begin(); it != byepackets.end(); it++)
         delete *it;
     byepackets.clear();
     created = false;
 }
EndDataAccess()
int qrtplib::RTPSession::EndDataAccess ()
See BeginDataAccess.
Definition at line 779 of file rtpsession.cpp.
References created, and ERR_RTP_SESSION_NOTCREATED.
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     return 0;
 }
GetCurrentSourceInfo()
RTPSourceData * qrtplib::RTPSession::GetCurrentSourceInfo ()
Returns the RTPSourceData instance for the currently selected participant.
Definition at line 748 of file rtpsession.cpp.
References created, qrtplib::RTPSources::GetCurrentSourceInfo(), and sources.
 {
     if (!created)
         return 0;
     return sources.GetCurrentSourceInfo();
 }
GetLocalSSRC()
uint32_t qrtplib::RTPSession::GetLocalSSRC ()
Returns our own SSRC.
Definition at line 404 of file rtpsession.cpp.
References created, qrtplib::RTPPacketBuilder::GetSSRC(), and packetbuilder.
 {
     if (!created)
         return 0;
     uint32_t ssrc;
     ssrc = packetbuilder.GetSSRC();
     return ssrc;
 }
GetNextPacket()
RTPPacket * qrtplib::RTPSession::GetNextPacket ()
Extracts the next packet from the received packets queue of the current participant, or NULL if no more packets are available. Extracts the next packet from the received packets queue of the current participant, or NULL if no more packets are available. When the packet is no longer needed, its memory should be freed using the DeletePacket member function.
Definition at line 762 of file rtpsession.cpp.
References created, qrtplib::RTPSources::GetNextPacket(), and sources.
 {
     if (!created)
         return 0;
     return sources.GetNextPacket();
 }
GetNextSequenceNumber()
uint16_t qrtplib::RTPSession::GetNextSequenceNumber () const
Returns the Sequence Number that will be used in the next SendPacket function call.
Definition at line 769 of file rtpsession.cpp.
References qrtplib::RTPPacketBuilder::GetSequenceNumber(), and packetbuilder.
 {
     return packetbuilder.GetSequenceNumber();
 }
GetRandomNumberGenerator()
RTPRandom * qrtplib::RTPSession::GetRandomNumberGenerator (RTPRandom * r) private
Definition at line 1169 of file rtpsession.cpp.
References qrtplib::RTPRandom::CreateDefaultRandomNumberGenerator(), and deletertprnd.
 {
     RTPRandom *rnew = 0;
     if (r == 0)
     {
         rnew = RTPRandom::CreateDefaultRandomNumberGenerator();
         deletertprnd = true;
     }
     else
     {
         rnew = r;
         deletertprnd = false;
     }
     return rnew;
 }
GetRTCPDelay()
RTPTime qrtplib::RTPSession::GetRTCPDelay ()
Returns the time interval after which an RTCP compound packet may have to be sent (only works when you're not using the poll thread.
Definition at line 688 of file rtpsession.cpp.
References created, qrtplib::RTCPScheduler::GetTransmissionDelay(), rtcpsched, and usingpollthread.
 {
     if (!created)
         return RTPTime(0, 0);
     if (usingpollthread)
         return RTPTime(0, 0);
     RTPTime t = rtcpsched.GetTransmissionDelay();
     return t;
 }
GetSourceInfo()
RTPSourceData * qrtplib::RTPSession::GetSourceInfo (uint32_t ssrc)
Returns the RTPSourceData instance for the participant identified by ssrc, or NULL if no such entry exists.
Definition at line 755 of file rtpsession.cpp.
References created, qrtplib::RTPSources::GetSourceInfo(), and sources.
 {
     if (!created)
         return 0;
     return sources.GetSourceInfo(ssrc);
 }
GetTransmissionInfo()
RTPTransmissionInfo * qrtplib::RTPSession::GetTransmissionInfo ()
This function returns an instance of a subclass of RTPTransmissionInfo which will give some additional information about the transmitter (a list of local IP addresses for example). This function returns an instance of a subclass of RTPTransmissionInfo which will give some additional information about the transmitter (a list of local IP addresses for example). The user has to free the returned instance when it is no longer needed, preferably using the DeleteTransmissionInfo function.
Definition at line 674 of file rtpsession.cpp.
References created, qrtplib::RTPTransmitter::GetTransmissionInfo(), and rtptrans.
 {
     if (!created)
         return 0;
     return rtptrans->GetTransmissionInfo();
 }
GotoFirstSource()
bool qrtplib::RTPSession::GotoFirstSource ()
Starts the iteration over the participants by going to the first member in the table. Starts the iteration over the participants by going to the first member in the table. If a member was found, the function returns true, otherwise it returns false.
Definition at line 706 of file rtpsession.cpp.
References created, qrtplib::RTPSources::GotoFirstSource(), and sources.
 {
     if (!created)
         return false;
     return sources.GotoFirstSource();
 }
GotoFirstSourceWithData()
bool qrtplib::RTPSession::GotoFirstSourceWithData ()
Sets the current source to be the first source in the table which has RTPPacket instances that we haven't extracted yet. Sets the current source to be the first source in the table which has RTPPacket instances that we haven't extracted yet. If no such member was found, the function returns false, otherwise it returns true.
Definition at line 727 of file rtpsession.cpp.
References created, qrtplib::RTPSources::GotoFirstSourceWithData(), and sources.
 {
     if (!created)
         return false;
     return sources.GotoFirstSourceWithData();
 }
GotoNextSource()
bool qrtplib::RTPSession::GotoNextSource ()
Sets the current source to be the next source in the table. Sets the current source to be the next source in the table. If we're already at the last source, the function returns false, otherwise it returns true.
Definition at line 713 of file rtpsession.cpp.
References created, qrtplib::RTPSources::GotoNextSource(), and sources.
 {
     if (!created)
         return false;
     return sources.GotoNextSource();
 }
GotoNextSourceWithData()
bool qrtplib::RTPSession::GotoNextSourceWithData ()
Sets the current source to be the next source in the table which has RTPPacket instances that we haven't extracted yet. Sets the current source to be the next source in the table which has RTPPacket instances that we haven't extracted yet. If no such member was found, the function returns false, otherwise it returns true.
Definition at line 734 of file rtpsession.cpp.
References created, qrtplib::RTPSources::GotoNextSourceWithData(), and sources.
 {
     if (!created)
         return false;
     return sources.GotoNextSourceWithData();
 }
GotoPreviousSource()
bool qrtplib::RTPSession::GotoPreviousSource ()
Sets the current source to be the previous source in the table. Sets the current source to be the previous source in the table. If we're at the first source, the function returns false, otherwise it returns true.
Definition at line 720 of file rtpsession.cpp.
References created, qrtplib::RTPSources::GotoPreviousSource(), and sources.
 {
     if (!created)
         return false;
     return sources.GotoPreviousSource();
 }
GotoPreviousSourceWithData()
bool qrtplib::RTPSession::GotoPreviousSourceWithData ()
Sets the current source to be the previous source in the table which has RTPPacket instances that we haven't extracted yet. Sets the current source to be the previous source in the table which has RTPPacket instances that we haven't extracted yet. If no such member was found, the function returns false, otherwise it returns true.
Definition at line 741 of file rtpsession.cpp.
References created, qrtplib::RTPSources::GotoPreviousSourceWithData(), and sources.
 {
     if (!created)
         return false;
     return sources.GotoPreviousSourceWithData();
 }
IncrementTimestamp()
int qrtplib::RTPSession::IncrementTimestamp (uint32_t inc)
This function increments the timestamp with the amount given by inc. This function increments the timestamp with the amount given by inc. This can be useful if, for example, a packet was not sent because it contained only silence. Then, this function should be called to increment the timestamp with the appropriate amount so that the next packets will still be played at the correct time at other hosts.
Definition at line 641 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, qrtplib::RTPPacketBuilder::IncrementTimestamp(), and packetbuilder.
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     status = packetbuilder.IncrementTimestamp(inc);
     return status;
 }
IncrementTimestampDefault()
int qrtplib::RTPSession::IncrementTimestampDefault ()
This function increments the timestamp with the amount given set by the SetDefaultTimestampIncrement member function. This function increments the timestamp with the amount given set by the SetDefaultTimestampIncrement member function. This can be useful if, for example, a packet was not sent because it contained only silence. Then, this function should be called to increment the timestamp with the appropriate amount so that the next packets will still be played at the correct time at other hosts.
Definition at line 652 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, qrtplib::RTPPacketBuilder::IncrementTimestampDefault(), and packetbuilder.
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     status = packetbuilder.IncrementTimestampDefault();
     return status;
 }
InternalCreate()
int qrtplib::RTPSession::InternalCreate (const RTPSessionParams & sessparams) private
Definition at line 171 of file rtpsession.cpp.
References qrtplib::RTPSessionParams::AcceptOwnPackets(), acceptownpackets, qrtplib::RTPPacketBuilder::AdjustSSRC(), byemultiplier, qrtplib::RTPSources::Clear(), collisionmultiplier, controlfragment, CreateCNAME(), created, qrtplib::RTPSources::CreateOwnSSRC(), deletetransmitter, qrtplib::RTPPacketBuilder::Destroy(), qrtplib::RTCPPacketBuilder::Destroy(), qrtplib::RTPSessionParams::GetBYETimeoutMultiplier(), qrtplib::RTPSessionParams::GetCNAME(), qrtplib::RTPSessionParams::GetCollisionTimeoutMultiplier(), qrtplib::RTPSessionParams::GetControlTrafficFraction(), qrtplib::RTPTransmitter::GetHeaderOverhead(), qrtplib::RTPSessionParams::GetMinimumRTCPTransmissionInterval(), qrtplib::RTPSessionParams::GetNoteTimeoutMultiplier(), qrtplib::RTPSessionParams::GetOwnTimestampUnit(), qrtplib::RTPSessionParams::GetPredefinedSSRC(), qrtplib::RTPSessionParams::GetReceiveMode(), qrtplib::RTPSessionParams::GetRequestImmediateBYE(), qrtplib::RTPSessionParams::GetResolveLocalHostname(), qrtplib::RTPSessionParams::GetSenderControlBandwidthFraction(), qrtplib::RTPSessionParams::GetSenderTimeoutMultiplier(), qrtplib::RTPSessionParams::GetSessionBandwidth(), qrtplib::RTPSessionParams::GetSourceTimeoutMultiplier(), qrtplib::RTPPacketBuilder::GetSSRC(), qrtplib::RTPSessionParams::GetUseHalfRTCPIntervalAtStartup(), qrtplib::RTPSessionParams::GetUsePredefinedSSRC(), qrtplib::RTPPacketBuilder::Init(), qrtplib::RTCPPacketBuilder::Init(), maxpacksize, membermultiplier, notemultiplier, packetbuilder, qrtplib::RTCPScheduler::Reset(), rtcpbuilder, rtcpsched, rtptrans, sendermultiplier, sessionbandwidth, qrtplib::RTCPScheduler::SetHeaderOverhead(), qrtplib::RTCPSchedulerParams::SetMinimumTransmissionInterval(), qrtplib::RTCPScheduler::SetParameters(), qrtplib::RTPTransmitter::SetReceiveMode(), qrtplib::RTCPSchedulerParams::SetRequestImmediateBYE(), qrtplib::RTCPSchedulerParams::SetRTCPBandwidth(), qrtplib::RTCPSchedulerParams::SetSenderBandwidthFraction(), qrtplib::RTCPSchedulerParams::SetUseHalfAtStartup(), and sources.
Referenced by Create().
 {
     int status;
     // Initialize packet builder
     if ((status = packetbuilder.Init(maxpacksize)) < 0)
     {
         if (deletetransmitter)
             delete rtptrans;
         return status;
     }
     if (sessparams.GetUsePredefinedSSRC())
         packetbuilder.AdjustSSRC(sessparams.GetPredefinedSSRC());
     // Add our own ssrc to the source table
     if ((status = sources.CreateOwnSSRC(packetbuilder.GetSSRC())) < 0)
     {
         packetbuilder.Destroy();
         if (deletetransmitter)
             delete rtptrans;
         return status;
     }
     // Set the initial receive mode
     if ((status = rtptrans->SetReceiveMode(sessparams.GetReceiveMode())) < 0)
     {
         packetbuilder.Destroy();
         sources.Clear();
         if (deletetransmitter)
             delete rtptrans;
         return status;
     }
     // Init the RTCP packet builder
     double timestampunit = sessparams.GetOwnTimestampUnit();
     uint8_t buf[1024] = {0};
     std::size_t buflen = 1024;
     std::string forcedcname = sessparams.GetCNAME();
     if (forcedcname.length() == 0)
     {
         if ((status = CreateCNAME(buf, &buflen, sessparams.GetResolveLocalHostname())) < 0)
         {
             packetbuilder.Destroy();
             sources.Clear();
             if (deletetransmitter)
                 delete rtptrans;
             return status;
         }
     }
     else
     {
         strncpy((char * )buf, forcedcname.c_str(), buflen);
         buf[buflen - 1] = 0;
         buflen = strlen((char *) buf);
     }
     if ((status = rtcpbuilder.Init(maxpacksize, timestampunit, buf, buflen)) < 0)
     {
         packetbuilder.Destroy();
         sources.Clear();
         if (deletetransmitter)
             delete rtptrans;
         return status;
     }
     // Set scheduler parameters
     rtcpsched.Reset();
     rtcpsched.SetHeaderOverhead(rtptrans->GetHeaderOverhead());
     RTCPSchedulerParams schedparams;
     sessionbandwidth = sessparams.GetSessionBandwidth();
     controlfragment = sessparams.GetControlTrafficFraction();
     if ((status = schedparams.SetRTCPBandwidth(sessionbandwidth * controlfragment)) < 0)
     {
         if (deletetransmitter)
             delete rtptrans;
         packetbuilder.Destroy();
         sources.Clear();
         rtcpbuilder.Destroy();
         return status;
     }
     if ((status = schedparams.SetSenderBandwidthFraction(sessparams.GetSenderControlBandwidthFraction())) < 0)
     {
         if (deletetransmitter)
             delete rtptrans;
         packetbuilder.Destroy();
         sources.Clear();
         rtcpbuilder.Destroy();
         return status;
     }
     if ((status = schedparams.SetMinimumTransmissionInterval(sessparams.GetMinimumRTCPTransmissionInterval())) < 0)
     {
         if (deletetransmitter)
             delete rtptrans;
         packetbuilder.Destroy();
         sources.Clear();
         rtcpbuilder.Destroy();
         return status;
     }
     schedparams.SetUseHalfAtStartup(sessparams.GetUseHalfRTCPIntervalAtStartup());
     schedparams.SetRequestImmediateBYE(sessparams.GetRequestImmediateBYE());
     rtcpsched.SetParameters(schedparams);
     // copy other parameters
     acceptownpackets = sessparams.AcceptOwnPackets();
     membermultiplier = sessparams.GetSourceTimeoutMultiplier();
     sendermultiplier = sessparams.GetSenderTimeoutMultiplier();
     byemultiplier = sessparams.GetBYETimeoutMultiplier();
     collisionmultiplier = sessparams.GetCollisionTimeoutMultiplier();
     notemultiplier = sessparams.GetNoteTimeoutMultiplier();
     // Do thread stuff if necessary
     created = true;
     return 0;
 }
IsActive()
bool qrtplib::RTPSession::IsActive ()
Returns whether the session has been created or not.
Definition at line 399 of file rtpsession.cpp.
References created.
 {
     return created;
 }
JoinMulticastGroup()
int qrtplib::RTPSession::JoinMulticastGroup (const RTPAddress & addr)
Joins the multicast group specified by addr.
Definition at line 443 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, qrtplib::RTPTransmitter::JoinMulticastGroup(), and rtptrans.
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     return rtptrans->JoinMulticastGroup(addr);
 }
LeaveMulticastGroup()
int qrtplib::RTPSession::LeaveMulticastGroup (const RTPAddress & addr)
Leaves the multicast group specified by addr.
Definition at line 450 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, qrtplib::RTPTransmitter::LeaveMulticastGroup(), and rtptrans.
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     return rtptrans->LeaveMulticastGroup(addr);
 }
NewUserDefinedTransmitter()
RTPTransmitter * qrtplib::RTPSession::NewUserDefinedTransmitter () inline protected virtual
Allocate a user defined transmitter. In case you specified in the Create function that you want to use a user defined transmitter, you should override this function. The RTPTransmitter instance returned by this function will then be used to send and receive RTP and RTCP packets. Note that when the session is destroyed, this RTPTransmitter instance will be destroyed as well.
Definition at line 583 of file rtpsession.h.
 {
     return 0;
 }
OnAPPPacket()
void qrtplib::RTPSession::OnAPPPacket (RTCPAPPPacket * apppacket, const RTPTime & receivetime, const RTPAddress * senderaddress) inline protected virtual
Is called when an RTCP APP packet apppacket has been received at time receivetime from address senderaddress.
Definition at line 611 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnAPPPacket().
 {
 }
OnBYEPacket()
void qrtplib::RTPSession::OnBYEPacket (RTPSourceData * srcdat) inline protected virtual
Is called when a BYE packet has been processed for source srcdat.
Definition at line 639 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnBYEPacket().
 {
 }
OnBYETimeout()
void qrtplib::RTPSession::OnBYETimeout (RTPSourceData * srcdat) inline protected virtual
Is called when participant srcdat is timed after having sent a BYE packet.
Definition at line 608 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnBYETimeout().
 {
 }
OnChangeIncomingData()
bool qrtplib::RTPSession::OnChangeIncomingData (RTPRawPacket * rawpack) inline protected virtual
By overriding this function, the raw incoming data can be inspected and modified (e.g. for encryption). By overriding this function, the raw incoming data can be inspected and modified (e.g. for encryption). If the function returns false, the packet is discarded.
Definition at line 653 of file rtpsession.h.
Referenced by ProcessPolledData().
 {
     return true;
 }
OnChangeRTPOrRTCPData()
int qrtplib::RTPSession::OnChangeRTPOrRTCPData (const void * origdata, std::size_t origlen, bool isrtp, void ** senddata, std::size_t * sendlen) inline protected virtual
If RTPSession::SetChangeOutgoingData was sent to true, overriding this you can change the data packet that will actually be sent, for example adding encryption. If RTPSession::SetChangeOutgoingData was sent to true, overriding this you can change the data packet that will actually be sent, for example adding encryption. Note that no memory management will be performed on the senddata pointer you fill in, so if it needs to be deleted at some point you need to take care of this in some way yourself, a good way may be to do this in RTPSession::OnSentRTPOrRTCPData. If senddata is set to 0, no packet will be sent out. This also provides a way to turn off sending RTCP packets if desired.
Definition at line 646 of file rtpsession.h.
References ERR_RTP_RTPSESSION_CHANGEREQUESTEDBUTNOTIMPLEMENTED.
Referenced by SendRTCPData(), and SendRTPData().
 {
     return ERR_RTP_RTPSESSION_CHANGEREQUESTEDBUTNOTIMPLEMENTED;
 }
OnCNAMECollision()
void qrtplib::RTPSession::OnCNAMECollision (RTPSourceData * srcdat, const RTPAddress * senderaddress, const uint8_t * cname, std::size_t cnamelength) inline protected virtual
Is called when another CNAME was received than the one already present for source srcdat.
Definition at line 596 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnCNAMECollision().
 {
 }
OnNewSource()
void qrtplib::RTPSession::OnNewSource (RTPSourceData * srcdat) inline protected virtual
Is called when a new entry srcdat is added to the source table.
Definition at line 599 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnNewSource().
 {
 }
OnNoteTimeout()
void qrtplib::RTPSession::OnNoteTimeout (RTPSourceData * srcdat) inline protected virtual
Is called when the SDES NOTE item for source srcdat has been timed out.
Definition at line 620 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnNoteTimeout().
 {
 }
OnRemoveSource()
void qrtplib::RTPSession::OnRemoveSource (RTPSourceData * srcdat) inline protected virtual
Is called when the entry srcdat is about to be deleted from the source table.
Definition at line 602 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnRemoveSource().
 {
 }
OnRTCPCompoundPacket()
void qrtplib::RTPSession::OnRTCPCompoundPacket (RTCPCompoundPacket * pack, const RTPTime & receivetime, const RTPAddress * senderaddress) inline protected virtual
Is called when an incoming RTCP packet is about to be processed.
Definition at line 590 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnRTCPCompoundPacket().
 {
 }
OnRTCPReceiverReport()
void qrtplib::RTPSession::OnRTCPReceiverReport (RTPSourceData * srcdat) inline protected virtual
Is called when an RTCP receiver report has been processed for this source.
Definition at line 626 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnRTCPReceiverReport().
 {
 }
OnRTCPSDESItem()
void qrtplib::RTPSession::OnRTCPSDESItem (RTPSourceData * srcdat, RTCPSDESPacket::ItemType t, const void * itemdata, std::size_t itemlength) inline protected virtual
Is called when a specific SDES item was received for this source.
Definition at line 629 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnRTCPSDESItem().
 {
 }
OnRTCPSDESPrivateItem()
void qrtplib::RTPSession::OnRTCPSDESPrivateItem (RTPSourceData * srcdat, const void * prefixdata, std::size_t prefixlen, const void * valuedata, std::size_t valuelen) inline protected virtual
Is called when a specific SDES item of 'private' type was received for this source.
Definition at line 634 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnRTCPSDESPrivateItem().
 {
 }
OnRTCPSenderReport()
void qrtplib::RTPSession::OnRTCPSenderReport (RTPSourceData * srcdat) inline protected virtual
Is called when an RTCP sender report has been processed for this source.
Definition at line 623 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnRTCPSenderReport().
 {
 }
OnRTPPacket()
void qrtplib::RTPSession::OnRTPPacket (RTPPacket * pack, const RTPTime & receivetime, const RTPAddress * senderaddress) inline protected virtual
Is called when an incoming RTP packet is about to be processed. Is called when an incoming RTP packet is about to be processed. This is not a good function to process an RTP packet in, in case you want to avoid iterating over the sources using the GotoFirst/GotoNext functions. In that case, the RTPSession::OnValidatedRTPPacket function should be used.
Definition at line 587 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnRTPPacket().
 {
 }
OnSendRTCPCompoundPacket()
void qrtplib::RTPSession::OnSendRTCPCompoundPacket (RTCPCompoundPacket * pack) inline protected virtual
Is called when an RTCP compound packet has just been sent (useful to inspect outgoing RTCP data).
Definition at line 642 of file rtpsession.h.
Referenced by BYEDestroy(), and ProcessPolledData().
 {
 }
OnSentRTPOrRTCPData()
void qrtplib::RTPSession::OnSentRTPOrRTCPData (void * senddata, std::size_t sendlen, bool isrtp) inline protected virtual
This function is called when an RTP or RTCP packet was sent, it can be helpful when data was allocated in RTPSession::OnChangeRTPOrRTCPData to deallocate it here.
Definition at line 650 of file rtpsession.h.
Referenced by SendRTCPData(), and SendRTPData().
 {
 }
OnSSRCCollision()
void qrtplib::RTPSession::OnSSRCCollision (RTPSourceData * srcdat, const RTPAddress * senderaddress, bool isrtp) inline protected virtual
Is called when an SSRC collision was detected. Is called when an SSRC collision was detected. The instance srcdat is the one present in the table, the address senderaddress is the one that collided with one of the addresses and isrtp indicates against which address of srcdat the check failed.
Definition at line 593 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnSSRCCollision().
 {
 }
OnTimeout()
void qrtplib::RTPSession::OnTimeout (RTPSourceData * srcdat) inline protected virtual
Is called when participant srcdat is timed out.
Definition at line 605 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnTimeout().
 {
 }
OnUnknownPacketFormat()
void qrtplib::RTPSession::OnUnknownPacketFormat (RTCPPacket * rtcppack, const RTPTime & receivetime, const RTPAddress * senderaddress) inline protected virtual
Is called when an unknown packet format for a known packet type was detected.
Definition at line 617 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnUnknownPacketFormat().
 {
 }
OnUnknownPacketType()
void qrtplib::RTPSession::OnUnknownPacketType (RTCPPacket * rtcppack, const RTPTime & receivetime, const RTPAddress * senderaddress) inline protected virtual
Is called when an unknown RTCP packet type was detected.
Definition at line 614 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnUnknownPacketType().
 {
 }
OnValidatedRTPPacket()
void qrtplib::RTPSession::OnValidatedRTPPacket (RTPSourceData * srcdat, RTPPacket * rtppack, bool isonprobation, bool * ispackethandled) inline protected virtual
Allows you to use an RTP packet from the specified source directly. Allows you to use an RTP packet from the specified source directly. If ispackethandled is set to true, the packet will no longer be stored in this source's packet list. Note that if you do set this flag, you'll need to deallocate the packet yourself at an appropriate time.
The difference with RTPSession::OnRTPPacket is that that function will always process the RTP packet further and is therefore not really suited to actually do something with the data.
Definition at line 657 of file rtpsession.h.
Referenced by qrtplib::RTPSessionSources::OnValidatedRTPPacket().
 {
 }
ProcessPolledData()
int qrtplib::RTPSession::ProcessPolledData () private
Definition at line 994 of file rtpsession.cpp.
References acceptownpackets, qrtplib::RTCPScheduler::AnalyseOutgoing(), qrtplib::RTCPPacketBuilder::BuildBYEPacket(), qrtplib::RTCPPacketBuilder::BuildNextPacket(), byemultiplier, byepackets, qrtplib::RTCPScheduler::CalculateDeterministicInterval(), qrtplib::RTPSessionSources::ClearOwnCollisionFlag(), collisionlist, collisionmultiplier, created, qrtplib::RTPPacketBuilder::CreateNewSSRC(), qrtplib::RTPSources::CreateOwnSSRC(), qrtplib::RTPTime::CurrentTime(), qrtplib::RTPSources::DeleteOwnSSRC(), qrtplib::RTPSessionSources::DetectedOwnCollision(), qrtplib::RTCPCompoundPacket::GetCompoundPacketData(), qrtplib::RTCPCompoundPacket::GetCompoundPacketLength(), qrtplib::RTPTime::GetDouble(), qrtplib::RTPTransmitter::GetNextPacket(), qrtplib::RTPRawPacket::GetReceiveTime(), qrtplib::RTPRawPacket::GetSenderAddress(), qrtplib::RTCPScheduler::IsTime(), m_changeIncomingData, membermultiplier, qrtplib::RTPSources::MultipleTimeouts(), notemultiplier, OnChangeIncomingData(), OnSendRTCPCompoundPacket(), packetbuilder, qrtplib::RTPSources::ProcessRawPacket(), rtcpbuilder, rtcpsched, rtptrans, qrtplib::RTCPScheduler::ScheduleBYEPacket(), sendermultiplier, SendRTCPData(), sentpackets, sources, qrtplib::RTPCollisionList::Timeout(), qrtplib::RTPCollisionList::UpdateAddress(), and useSR_BYEifpossible.
 {
     RTPRawPacket *rawpack;
     int status;
     while ((rawpack = rtptrans->GetNextPacket()) != 0)
     {
         if (m_changeIncomingData)
         {
             // Provide a way to change incoming data, for decryption for example
             if (!OnChangeIncomingData(rawpack))
             {
                 delete rawpack;
                 continue;
             }
         }
         sources.ClearOwnCollisionFlag();
         // since our sources instance also uses the scheduler (analysis of incoming packets)
         // we'll lock it
         if ((status = sources.ProcessRawPacket(rawpack, rtptrans, acceptownpackets)) < 0)
         {
             delete rawpack;
             return status;
         }
         if (sources.DetectedOwnCollision()) // collision handling!
         {
             bool created;
             if ((status = collisionlist.UpdateAddress(&rawpack->GetSenderAddress(), rawpack->GetReceiveTime(), &created)) < 0)
             {
                 delete rawpack;
                 return status;
             }
             if (created) // first time we've encountered this address, send bye packet and
             {            // change our own SSRC
                 bool hassentpackets = sentpackets;
                 if (hassentpackets)
                 {
                     // Only send BYE packet if we've actually sent data using this
                     // SSRC
                     RTCPCompoundPacket *rtcpcomppack;
                     if ((status = rtcpbuilder.BuildBYEPacket(&rtcpcomppack, 0, 0, useSR_BYEifpossible)) < 0)
                     {
                         delete rawpack;
                         return status;
                     }
                     byepackets.push_back(rtcpcomppack);
                     if (byepackets.size() == 1) // was the first packet, schedule a BYE packet (otherwise there's already one scheduled)
                     {
                         rtcpsched.ScheduleBYEPacket(rtcpcomppack->GetCompoundPacketLength());
                     }
                 }
                 // bye packet is built and scheduled, now change our SSRC
                 // and reset the packet count in the transmitter
                 uint32_t newssrc = packetbuilder.CreateNewSSRC(sources);
                 sentpackets = false;
                 // remove old entry in source table and add new one
                 if ((status = sources.DeleteOwnSSRC()) < 0)
                 {
                     delete rawpack;
                     return status;
                 }
                 if ((status = sources.CreateOwnSSRC(newssrc)) < 0)
                 {
                     delete rawpack;
                     return status;
                 }
             }
         }
         delete rawpack;
     }
     RTPTime d = rtcpsched.CalculateDeterministicInterval(false);
     RTPTime t = RTPTime::CurrentTime();
     double Td = d.GetDouble();
     RTPTime sendertimeout = RTPTime(Td * sendermultiplier);
     RTPTime generaltimeout = RTPTime(Td * membermultiplier);
     RTPTime byetimeout = RTPTime(Td * byemultiplier);
     RTPTime colltimeout = RTPTime(Td * collisionmultiplier);
     RTPTime notetimeout = RTPTime(Td * notemultiplier);
     sources.MultipleTimeouts(t, sendertimeout, byetimeout, generaltimeout, notetimeout);
     collisionlist.Timeout(t, colltimeout);
     // We'll check if it's time for RTCP stuff
     bool istime = rtcpsched.IsTime();
     if (istime)
     {
         RTCPCompoundPacket *pack;
         // we'll check if there's a bye packet to send, or just a normal packet
         if (byepackets.empty())
         {
             if ((status = rtcpbuilder.BuildNextPacket(&pack)) < 0)
             {
                 return status;
             }
             if ((status = SendRTCPData(pack->GetCompoundPacketData(), pack->GetCompoundPacketLength())) < 0)
             {
                 delete pack;
                 return status;
             }
             sentpackets = true;
             OnSendRTCPCompoundPacket(pack); // we'll place this after the actual send to avoid tampering
         }
         else
         {
             pack = *(byepackets.begin());
             byepackets.pop_front();
             if ((status = SendRTCPData(pack->GetCompoundPacketData(), pack->GetCompoundPacketLength())) < 0)
             {
                 delete pack;
                 return status;
             }
             sentpackets = true;
             OnSendRTCPCompoundPacket(pack); // we'll place this after the actual send to avoid tampering
             if (!byepackets.empty()) // more bye packets to send, schedule them
             {
                 rtcpsched.ScheduleBYEPacket((*(byepackets.begin()))->GetCompoundPacketLength());
             }
         }
         rtcpsched.AnalyseOutgoing(*pack);
         delete pack;
     }
     return 0;
 }
ProcessRTCPCompoundPacket()
int qrtplib::RTPSession::ProcessRTCPCompoundPacket (RTCPCompoundPacket & rtcpcomppack, RTPRawPacket * pack) private
SendPacket() [1/2]
int qrtplib::RTPSession::SendPacket (const void * data, std::size_t len)
Sends the RTP packet with payload data which has length len. Sends the RTP packet with payload data which has length len. The used payload type, marker and timestamp increment will be those that have been set using the SetDefault member functions.
Definition at line 457 of file rtpsession.cpp.
References qrtplib::RTPPacketBuilder::BuildPacket(), created, ERR_RTP_SESSION_NOTCREATED, qrtplib::RTPPacketBuilder::GetPacket(), qrtplib::RTPPacketBuilder::GetPacketLength(), packetbuilder, SendRTPData(), sentpackets, qrtplib::RTPSources::SentRTPPacket(), and sources.
Referenced by RTPSink::write().
 {
     int status;
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     if ((status = packetbuilder.BuildPacket(data, len)) < 0)
     {
         return status;
     }
     if ((status = SendRTPData(packetbuilder.GetPacket(), packetbuilder.GetPacketLength())) < 0)
     {
         return status;
     }
     sources.SentRTPPacket();
     sentpackets = true;
     return 0;
 }
SendPacket() [2/2]
int qrtplib::RTPSession::SendPacket (const void * data, std::size_t len, uint8_t pt, bool mark, uint32_t timestampinc)
Sends the RTP packet with payload data which has length len. It will use payload type pt, marker mark and after the packet has been built, the timestamp will be incremented by timestampinc.
Definition at line 478 of file rtpsession.cpp.
References qrtplib::RTPPacketBuilder::BuildPacket(), created, ERR_RTP_SESSION_NOTCREATED, qrtplib::RTPPacketBuilder::GetPacket(), qrtplib::RTPPacketBuilder::GetPacketLength(), packetbuilder, SendRTPData(), sentpackets, qrtplib::RTPSources::SentRTPPacket(), and sources.
 {
     int status;
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     if ((status = packetbuilder.BuildPacket(data, len, pt, mark, timestampinc)) < 0)
     {
         return status;
     }
     if ((status = SendRTPData(packetbuilder.GetPacket(), packetbuilder.GetPacketLength())) < 0)
     {
         return status;
     }
     sources.SentRTPPacket();
     sentpackets = true;
     return 0;
 }
SendPacketEx() [1/2]
int qrtplib::RTPSession::SendPacketEx (const void * data, std::size_t len, uint16_t hdrextID, const void * hdrextdata, std::size_t numhdrextwords)
Sends the RTP packet with payload data which has length len. The packet will contain a header extension with identifier hdrextID and containing data hdrextdata. The length of this data is given by numhdrextwords and is specified in a number of 32-bit words. The used payload type, marker and timestamp increment will be those that have been set using the SetDefault member functions.
Definition at line 499 of file rtpsession.cpp.
References qrtplib::RTPPacketBuilder::BuildPacketEx(), created, ERR_RTP_SESSION_NOTCREATED, qrtplib::RTPPacketBuilder::GetPacket(), qrtplib::RTPPacketBuilder::GetPacketLength(), packetbuilder, SendRTPData(), sentpackets, qrtplib::RTPSources::SentRTPPacket(), and sources.
 {
     int status;
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     if ((status = packetbuilder.BuildPacketEx(data, len, hdrextID, hdrextdata, numhdrextwords)) < 0)
     {
         return status;
     }
     if ((status = SendRTPData(packetbuilder.GetPacket(), packetbuilder.GetPacketLength())) < 0)
     {
         return status;
     }
     sources.SentRTPPacket();
     sentpackets = true;
     return 0;
 }
SendPacketEx() [2/2]
int qrtplib::RTPSession::SendPacketEx (const void * data, std::size_t len, uint8_t pt, bool mark, uint32_t timestampinc, uint16_t hdrextID, const void * hdrextdata, std::size_t numhdrextwords)
Sends the RTP packet with payload data which has length len. It will use payload type pt, marker mark and after the packet has been built, the timestamp will be incremented by timestampinc. The packet will contain a header extension with identifier hdrextID and containing data hdrextdata. The length of this data is given by numhdrextwords and is specified in a number of 32-bit words.
Definition at line 520 of file rtpsession.cpp.
References qrtplib::RTPPacketBuilder::BuildPacketEx(), created, ERR_RTP_SESSION_NOTCREATED, qrtplib::RTPPacketBuilder::GetPacket(), qrtplib::RTPPacketBuilder::GetPacketLength(), packetbuilder, SendRTPData(), sentpackets, qrtplib::RTPSources::SentRTPPacket(), and sources.
 {
     int status;
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     if ((status = packetbuilder.BuildPacketEx(data, len, pt, mark, timestampinc, hdrextID, hdrextdata, numhdrextwords)) < 0)
     {
         return status;
     }
     if ((status = SendRTPData(packetbuilder.GetPacket(), packetbuilder.GetPacketLength())) < 0)
     {
         return status;
     }
     sources.SentRTPPacket();
     sentpackets = true;
     return 0;
 }
SendRawData()
int qrtplib::RTPSession::SendRawData (const void * data, std::size_t len, bool usertpchannel)
With this function raw data can be sent directly over the RTP or RTCP channel (if they are different); the data is not passed through the RTPSession::OnChangeRTPOrRTCPData function.
Definition at line 594 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, rtptrans, qrtplib::RTPTransmitter::SendRTCPData(), and qrtplib::RTPTransmitter::SendRTPData().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     if (usertpchannel)
         status = rtptrans->SendRTPData(data, len);
     else
         status = rtptrans->SendRTCPData(data, len);
     return status;
 }
SendRTCPAPPPacket()
int qrtplib::RTPSession::SendRTCPAPPPacket (uint8_t subtype, const uint8_t name[4], const void * appdata, std::size_t appdatalen)
If sending of RTCP APP packets was enabled at compile time, this function creates a compound packet containing an RTCP APP packet and sends it immediately. If sending of RTCP APP packets was enabled at compile time, this function creates a compound packet containing an RTCP APP packet and sends it immediately. If successful, the function returns the number of bytes in the RTCP compound packet. Note that this immediate sending is not compliant with the RTP specification, so use with care.
Definition at line 543 of file rtpsession.cpp.
References qrtplib::RTCPCompoundPacketBuilder::AddAPPPacket(), qrtplib::RTCPCompoundPacketBuilder::AddSDESNormalItem(), qrtplib::RTCPCompoundPacketBuilder::AddSDESSource(), qrtplib::RTCPSDESPacket::CNAME, created, qrtplib::RTCPCompoundPacketBuilder::EndBuild(), ERR_RTP_SESSION_NOTCREATED, qrtplib::RTCPCompoundPacket::GetCompoundPacketData(), qrtplib::RTCPCompoundPacket::GetCompoundPacketLength(), qrtplib::RTCPPacketBuilder::GetLocalCNAME(), qrtplib::RTPPacketBuilder::GetSSRC(), qrtplib::RTCPCompoundPacketBuilder::InitBuild(), maxpacksize, packetbuilder, rtcpbuilder, SendRTCPData(), sentpackets, and qrtplib::RTCPCompoundPacketBuilder::StartReceiverReport().
 {
     int status;
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     uint32_t ssrc = packetbuilder.GetSSRC();
     RTCPCompoundPacketBuilder pb;
     status = pb.InitBuild(maxpacksize);
     if (status < 0)
         return status;
     //first packet in an rtcp compound packet should always be SR or RR
     if ((status = pb.StartReceiverReport(ssrc)) < 0)
         return status;
     //add SDES packet with CNAME item
     if ((status = pb.AddSDESSource(ssrc)) < 0)
         return status;
     std::size_t owncnamelen = 0;
     uint8_t *owncname = rtcpbuilder.GetLocalCNAME(&owncnamelen);
     if ((status = pb.AddSDESNormalItem(RTCPSDESPacket::CNAME, owncname, owncnamelen)) < 0)
     {
         return status;
     }
     //add our application specific packet
     if ((status = pb.AddAPPPacket(subtype, ssrc, name, appdata, appdatalen)) < 0)
         return status;
     if ((status = pb.EndBuild()) < 0)
         return status;
     //send packet
     status = SendRTCPData(pb.GetCompoundPacketData(), pb.GetCompoundPacketLength());
     if (status < 0)
         return status;
     sentpackets = true;
     return pb.GetCompoundPacketLength();
 }
SendRTCPData()
int qrtplib::RTPSession::SendRTCPData (const void * data, std::size_t len) private
Definition at line 1209 of file rtpsession.cpp.
References m_changeOutgoingData, OnChangeRTPOrRTCPData(), OnSentRTPOrRTCPData(), rtptrans, and qrtplib::RTPTransmitter::SendRTCPData().
Referenced by BYEDestroy(), ProcessPolledData(), and SendRTCPAPPPacket().
 {
     if (!m_changeOutgoingData)
         return rtptrans->SendRTCPData(data, len);
     void *pSendData = 0;
     std::size_t sendLen = 0;
     int status = 0;
     status = OnChangeRTPOrRTCPData(data, len, false, &pSendData, &sendLen);
     if (status < 0)
         return status;
     if (pSendData)
     {
         status = rtptrans->SendRTCPData(pSendData, sendLen);
         OnSentRTPOrRTCPData(pSendData, sendLen, false);
     }
     return status;
 }
SendRTPData()
int qrtplib::RTPSession::SendRTPData (const void * data, std::size_t len) private
Definition at line 1187 of file rtpsession.cpp.
References m_changeOutgoingData, OnChangeRTPOrRTCPData(), OnSentRTPOrRTCPData(), rtptrans, and qrtplib::RTPTransmitter::SendRTPData().
Referenced by SendPacket(), and SendPacketEx().
 {
     if (!m_changeOutgoingData)
         return rtptrans->SendRTPData(data, len);
     void *pSendData = 0;
     std::size_t sendLen = 0;
     int status = 0;
     status = OnChangeRTPOrRTCPData(data, len, true, &pSendData, &sendLen);
     if (status < 0)
         return status;
     if (pSendData)
     {
         status = rtptrans->SendRTPData(pSendData, sendLen);
         OnSentRTPOrRTCPData(pSendData, sendLen, true);
     }
     return status;
 }
SetChangeIncomingData()
void qrtplib::RTPSession::SetChangeIncomingData (bool change) inline protected
If this is set to true, incoming data will be passed through RTPSession::OnChangeIncomingData, allowing you to modify the data (e.g. to decrypt it).
Definition at line 501 of file rtpsession.h.
     {
         m_changeIncomingData = change;
     }
SetChangeOutgoingData()
void qrtplib::RTPSession::SetChangeOutgoingData (bool change) inline protected
If this is set to true, outgoing data will be passed through RTPSession::OnChangeRTPOrRTCPData and RTPSession::OnSentRTPOrRTCPData, allowing you to modify the data (e.g. to encrypt it).
Definition at line 494 of file rtpsession.h.
     {
         m_changeOutgoingData = change;
     }
SetDefaultMark()
int qrtplib::RTPSession::SetDefaultMark (bool m)
Sets the default marker for RTP packets to m.
Definition at line 619 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, packetbuilder, and qrtplib::RTPPacketBuilder::SetDefaultMark().
Referenced by RTPSink::setPayloadInformation().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     status = packetbuilder.SetDefaultMark(m);
     return status;
 }
SetDefaultPayloadType()
int qrtplib::RTPSession::SetDefaultPayloadType (uint8_t pt)
Sets the default payload type for RTP packets to pt.
Definition at line 608 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, packetbuilder, and qrtplib::RTPPacketBuilder::SetDefaultPayloadType().
Referenced by RTPSink::setPayloadInformation().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     status = packetbuilder.SetDefaultPayloadType(pt);
     return status;
 }
SetDefaultTimestampIncrement()
int qrtplib::RTPSession::SetDefaultTimestampIncrement (uint32_t timestampinc)
Sets the default value to increment the timestamp with to timestampinc.
Definition at line 630 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, packetbuilder, and qrtplib::RTPPacketBuilder::SetDefaultTimestampIncrement().
Referenced by RTPSink::setPayloadInformation().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     status = packetbuilder.SetDefaultTimestampIncrement(timestampinc);
     return status;
 }
SetEMailInterval()
void qrtplib::RTPSession::SetEMailInterval (int count)
Sets the RTCP interval for the SDES e-mail item. After all possible sources in the source table have been processed, the class will check if other SDES items need to be sent. If count is zero or negative, nothing will happen. If count is positive, an SDES e-mail item will be added after the sources in the source table have been processed count times.
Definition at line 899 of file rtpsession.cpp.
References created, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetEMailInterval().
 {
     if (!created)
         return;
     rtcpbuilder.SetEMailInterval(count);
 }
SetLocalEMail()
int qrtplib::RTPSession::SetLocalEMail (const void * s, std::size_t len)
Sets the SDES e-mail item for the local participant to the value s with length len.
Definition at line 944 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetLocalEMail().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     status = rtcpbuilder.SetLocalEMail(s, len);
     return status;
 }
SetLocalLocation()
int qrtplib::RTPSession::SetLocalLocation (const void * s, std::size_t len)
Sets the SDES location item for the local participant to the value s with length len.
Definition at line 954 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetLocalLocation().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     status = rtcpbuilder.SetLocalLocation(s, len);
     return status;
 }
SetLocalName()
int qrtplib::RTPSession::SetLocalName (const void * s, std::size_t len)
Sets the SDES name item for the local participant to the value s with length len.
Definition at line 934 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetLocalName().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     status = rtcpbuilder.SetLocalName(s, len);
     return status;
 }
SetLocalNote()
int qrtplib::RTPSession::SetLocalNote (const void * s, std::size_t len)
Sets the SDES note item for the local participant to the value s with length len.
Definition at line 984 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetLocalNote().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     status = rtcpbuilder.SetLocalNote(s, len);
     return status;
 }
SetLocalPhone()
int qrtplib::RTPSession::SetLocalPhone (const void * s, std::size_t len)
Sets the SDES phone item for the local participant to the value s with length len.
Definition at line 964 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetLocalPhone().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     status = rtcpbuilder.SetLocalPhone(s, len);
     return status;
 }
SetLocalTool()
int qrtplib::RTPSession::SetLocalTool (const void * s, std::size_t len)
Sets the SDES tool item for the local participant to the value s with length len.
Definition at line 974 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetLocalTool().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     status = rtcpbuilder.SetLocalTool(s, len);
     return status;
 }
SetLocationInterval()
void qrtplib::RTPSession::SetLocationInterval (int count)
Sets the RTCP interval for the SDES location item. After all possible sources in the source table have been processed, the class will check if other SDES items need to be sent. If count is zero or negative, nothing will happen. If count is positive, an SDES location item will be added after the sources in the source table have been processed count times.
Definition at line 906 of file rtpsession.cpp.
References created, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetLocationInterval().
 {
     if (!created)
         return;
     rtcpbuilder.SetLocationInterval(count);
 }
SetMaximumPacketSize()
int qrtplib::RTPSession::SetMaximumPacketSize (std::size_t s)
Sets the maximum allowed packet size to s.
Definition at line 835 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_MAXPACKETSIZETOOSMALL, ERR_RTP_SESSION_NOTCREATED, maxpacksize, packetbuilder, rtcpbuilder, RTP_MINPACKETSIZE, rtptrans, qrtplib::RTPPacketBuilder::SetMaximumPacketSize(), qrtplib::RTCPPacketBuilder::SetMaximumPacketSize(), and qrtplib::RTPTransmitter::SetMaximumPacketSize().
Referenced by RTPSink::setPayloadInformation().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     if (s < RTP_MINPACKETSIZE)
         return ERR_RTP_SESSION_MAXPACKETSIZETOOSMALL;
     int status;
     if ((status = rtptrans->SetMaximumPacketSize(s)) < 0)
         return status;
     if ((status = packetbuilder.SetMaximumPacketSize(s)) < 0)
     {
         // restore previous max packet size
         rtptrans->SetMaximumPacketSize(maxpacksize);
         return status;
     }
     if ((status = rtcpbuilder.SetMaximumPacketSize(s)) < 0)
     {
         // restore previous max packet size
         packetbuilder.SetMaximumPacketSize(maxpacksize);
         rtptrans->SetMaximumPacketSize(maxpacksize);
         return status;
     }
     maxpacksize = s;
     return 0;
 }
SetNameInterval()
void qrtplib::RTPSession::SetNameInterval (int count)
Sets the RTCP interval for the SDES name item. After all possible sources in the source table have been processed, the class will check if other SDES items need to be sent. If count is zero or negative, nothing will happen. If count is positive, an SDES name item will be added after the sources in the source table have been processed count times.
Definition at line 892 of file rtpsession.cpp.
References created, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetNameInterval().
 {
     if (!created)
         return;
     rtcpbuilder.SetNameInterval(count);
 }
SetNoteInterval()
void qrtplib::RTPSession::SetNoteInterval (int count)
Sets the RTCP interval for the SDES note item. After all possible sources in the source table have been processed, the class will check if other SDES items need to be sent. If count is zero or negative, nothing will happen. If count is positive, an SDES note item will be added after the sources in the source table have been processed count times.
Definition at line 927 of file rtpsession.cpp.
References created, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetNoteInterval().
 {
     if (!created)
         return;
     rtcpbuilder.SetNoteInterval(count);
 }
SetPhoneInterval()
void qrtplib::RTPSession::SetPhoneInterval (int count)
Sets the RTCP interval for the SDES phone item. After all possible sources in the source table have been processed, the class will check if other SDES items need to be sent. If count is zero or negative, nothing will happen. If count is positive, an SDES phone item will be added after the sources in the source table have been processed count times.
Definition at line 913 of file rtpsession.cpp.
References created, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetPhoneInterval().
 {
     if (!created)
         return;
     rtcpbuilder.SetPhoneInterval(count);
 }
SetPreTransmissionDelay()
int qrtplib::RTPSession::SetPreTransmissionDelay (const RTPTime & delay)
This function allows you to inform the library about the delay between sampling the first sample of a packet and sending the packet. This function allows you to inform the library about the delay between sampling the first sample of a packet and sending the packet. This delay is taken into account when calculating the relation between RTP timestamp and wallclock time, used for inter-media synchronization.
Definition at line 663 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetPreTransmissionDelay().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     status = rtcpbuilder.SetPreTransmissionDelay(delay);
     return status;
 }
SetReceiveMode()
int qrtplib::RTPSession::SetReceiveMode (RTPTransmitter::ReceiveMode m)
Sets the receive mode to m. Sets the receive mode to m. Note that when the receive mode is changed, the list of addresses to be ignored ot accepted will be cleared.
Definition at line 786 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, rtptrans, and qrtplib::RTPTransmitter::SetReceiveMode().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     return rtptrans->SetReceiveMode(m);
 }
SetSessionBandwidth()
int qrtplib::RTPSession::SetSessionBandwidth (double bw)
Sets the session bandwidth to bw, which is specified in bytes per second.
Definition at line 865 of file rtpsession.cpp.
References controlfragment, created, ERR_RTP_SESSION_NOTCREATED, qrtplib::RTCPScheduler::GetParameters(), rtcpsched, sessionbandwidth, qrtplib::RTCPScheduler::SetParameters(), and qrtplib::RTCPSchedulerParams::SetRTCPBandwidth().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     RTCPSchedulerParams p = rtcpsched.GetParameters();
     status = p.SetRTCPBandwidth(bw * controlfragment);
     if (status >= 0)
     {
         rtcpsched.SetParameters(p);
         sessionbandwidth = bw;
     }
     return status;
 }
SetTimestampUnit()
int qrtplib::RTPSession::SetTimestampUnit (double u)
Sets the timestamp unit for our own data. Sets the timestamp unit for our own data. The timestamp unit is defined as a time interval in seconds divided by the corresponding timestamp interval. For example, for 8000 Hz audio, the timestamp unit would typically be 1/8000. Since this value is initially set to an illegal value, the user must set this to an allowed value to be able to create a session.
Definition at line 881 of file rtpsession.cpp.
References created, ERR_RTP_SESSION_NOTCREATED, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetTimestampUnit().
Referenced by RTPSink::setPayloadInformation().
 {
     if (!created)
         return ERR_RTP_SESSION_NOTCREATED;
     int status;
     status = rtcpbuilder.SetTimestampUnit(u);
     return status;
 }
SetToolInterval()
void qrtplib::RTPSession::SetToolInterval (int count)
Sets the RTCP interval for the SDES tool item. After all possible sources in the source table have been processed, the class will check if other SDES items need to be sent. If count is zero or negative, nothing will happen. If count is positive, an SDES tool item will be added after the sources in the source table have been processed count times.
Definition at line 920 of file rtpsession.cpp.
References created, rtcpbuilder, and qrtplib::RTCPPacketBuilder::SetToolInterval().
 {
     if (!created)
         return;
     rtcpbuilder.SetToolInterval(count);
 }
SupportsMulticasting()
bool qrtplib::RTPSession::SupportsMulticasting ()
Returns true if multicasting is supported.
Definition at line 436 of file rtpsession.cpp.
References created, rtptrans, and qrtplib::RTPTransmitter::SupportsMulticasting().
 {
     if (!created)
         return false;
     return rtptrans->SupportsMulticasting();
 }
Friends And Related Function Documentation
RTCPSessionPacketBuilder
friend class RTCPSessionPacketBuilder friend
Definition at line 580 of file rtpsession.h.
RTPSessionSources
friend class RTPSessionSources friend
Definition at line 579 of file rtpsession.h.
Member Data Documentation
acceptownpackets
bool qrtplib::RTPSession::acceptownpackets private
Definition at line 557 of file rtpsession.h.
Referenced by InternalCreate(), and ProcessPolledData().
byemultiplier
double qrtplib::RTPSession::byemultiplier private
Definition at line 563 of file rtpsession.h.
Referenced by InternalCreate(), and ProcessPolledData().
byepackets
std::list<RTCPCompoundPacket *> qrtplib::RTPSession::byepackets private
Definition at line 577 of file rtpsession.h.
Referenced by BYEDestroy(), Destroy(), and ProcessPolledData().
collisionlist
RTPCollisionList qrtplib::RTPSession::collisionlist private
Definition at line 575 of file rtpsession.h.
Referenced by BYEDestroy(), Destroy(), and ProcessPolledData().
collisionmultiplier
double qrtplib::RTPSession::collisionmultiplier private
Definition at line 565 of file rtpsession.h.
Referenced by InternalCreate(), and ProcessPolledData().
controlfragment
double qrtplib::RTPSession::controlfragment private
Definition at line 561 of file rtpsession.h.
Referenced by InternalCreate(), and SetSessionBandwidth().
created
bool qrtplib::RTPSession::created private
Definition at line 554 of file rtpsession.h.
Referenced by AddDestination(), AddToAcceptList(), AddToIgnoreList(), BeginDataAccess(), BYEDestroy(), ClearAcceptList(), ClearDestinations(), ClearIgnoreList(), Create(), DeleteDestination(), DeleteFromAcceptList(), DeleteFromIgnoreList(), DeleteTransmissionInfo(), Destroy(), EndDataAccess(), GetCurrentSourceInfo(), GetLocalSSRC(), GetNextPacket(), GetRTCPDelay(), GetSourceInfo(), GetTransmissionInfo(), GotoFirstSource(), GotoFirstSourceWithData(), GotoNextSource(), GotoNextSourceWithData(), GotoPreviousSource(), GotoPreviousSourceWithData(), IncrementTimestamp(), IncrementTimestampDefault(), InternalCreate(), IsActive(), JoinMulticastGroup(), LeaveMulticastGroup(), ProcessPolledData(), RTPSession(), SendPacket(), SendPacketEx(), SendRawData(), SendRTCPAPPPacket(), SetDefaultMark(), SetDefaultPayloadType(), SetDefaultTimestampIncrement(), SetEMailInterval(), SetLocalEMail(), SetLocalLocation(), SetLocalName(), SetLocalNote(), SetLocalPhone(), SetLocalTool(), SetLocationInterval(), SetMaximumPacketSize(), SetNameInterval(), SetNoteInterval(), SetPhoneInterval(), SetPreTransmissionDelay(), SetReceiveMode(), SetSessionBandwidth(), SetTimestampUnit(), SetToolInterval(), and SupportsMulticasting().
deletertprnd
bool qrtplib::RTPSession::deletertprnd private
Definition at line 551 of file rtpsession.h.
Referenced by GetRandomNumberGenerator(), and ~RTPSession().
deletetransmitter
bool qrtplib::RTPSession::deletetransmitter private
Definition at line 555 of file rtpsession.h.
Referenced by BYEDestroy(), Create(), Destroy(), and InternalCreate().
m_changeIncomingData
bool qrtplib::RTPSession::m_changeIncomingData private
Definition at line 569 of file rtpsession.h.
Referenced by ProcessPolledData(), and RTPSession().
m_changeOutgoingData
bool qrtplib::RTPSession::m_changeOutgoingData private
Definition at line 569 of file rtpsession.h.
Referenced by RTPSession(), SendRTCPData(), and SendRTPData().
maxpacksize
std::size_t qrtplib::RTPSession::maxpacksize private
Definition at line 559 of file rtpsession.h.
Referenced by Create(), InternalCreate(), SendRTCPAPPPacket(), and SetMaximumPacketSize().
membermultiplier
double qrtplib::RTPSession::membermultiplier private
Definition at line 564 of file rtpsession.h.
Referenced by InternalCreate(), and ProcessPolledData().
notemultiplier
double qrtplib::RTPSession::notemultiplier private
Definition at line 566 of file rtpsession.h.
Referenced by InternalCreate(), and ProcessPolledData().
packetbuilder
RTPPacketBuilder qrtplib::RTPSession::packetbuilder private
Definition at line 572 of file rtpsession.h.
Referenced by BYEDestroy(), Destroy(), GetLocalSSRC(), GetNextSequenceNumber(), IncrementTimestamp(), IncrementTimestampDefault(), InternalCreate(), ProcessPolledData(), SendPacket(), SendPacketEx(), SendRTCPAPPPacket(), SetDefaultMark(), SetDefaultPayloadType(), SetDefaultTimestampIncrement(), and SetMaximumPacketSize().
rtcpbuilder
RTCPPacketBuilder qrtplib::RTPSession::rtcpbuilder private
Definition at line 574 of file rtpsession.h.
Referenced by BYEDestroy(), Destroy(), InternalCreate(), ProcessPolledData(), SendRTCPAPPPacket(), SetEMailInterval(), SetLocalEMail(), SetLocalLocation(), SetLocalName(), SetLocalNote(), SetLocalPhone(), SetLocalTool(), SetLocationInterval(), SetMaximumPacketSize(), SetNameInterval(), SetNoteInterval(), SetPhoneInterval(), SetPreTransmissionDelay(), SetTimestampUnit(), and SetToolInterval().
rtcpsched
RTCPScheduler qrtplib::RTPSession::rtcpsched private
Definition at line 573 of file rtpsession.h.
Referenced by BYEDestroy(), Destroy(), GetRTCPDelay(), InternalCreate(), qrtplib::RTPSessionSources::OnBYEPacket(), qrtplib::RTPSessionSources::OnRTCPCompoundPacket(), qrtplib::RTPSessionSources::OnTimeout(), ProcessPolledData(), and SetSessionBandwidth().
rtprnd
RTPRandom* qrtplib::RTPSession::rtprnd private
Definition at line 550 of file rtpsession.h.
Referenced by ~RTPSession().
rtptrans
RTPTransmitter* qrtplib::RTPSession::rtptrans private
Definition at line 553 of file rtpsession.h.
Referenced by AddDestination(), AddToAcceptList(), AddToIgnoreList(), BYEDestroy(), ClearAcceptList(), ClearDestinations(), ClearIgnoreList(), Create(), DeleteDestination(), DeleteFromAcceptList(), DeleteFromIgnoreList(), DeleteTransmissionInfo(), Destroy(), GetTransmissionInfo(), InternalCreate(), JoinMulticastGroup(), LeaveMulticastGroup(), ProcessPolledData(), SendRawData(), SendRTCPData(), SendRTPData(), SetMaximumPacketSize(), SetReceiveMode(), and SupportsMulticasting().
sendermultiplier
double qrtplib::RTPSession::sendermultiplier private
Definition at line 562 of file rtpsession.h.
Referenced by InternalCreate(), and ProcessPolledData().
sentpackets
bool qrtplib::RTPSession::sentpackets private
Definition at line 567 of file rtpsession.h.
Referenced by BYEDestroy(), Create(), ProcessPolledData(), SendPacket(), SendPacketEx(), and SendRTCPAPPPacket().
sessionbandwidth
double qrtplib::RTPSession::sessionbandwidth private
Definition at line 560 of file rtpsession.h.
Referenced by InternalCreate(), and SetSessionBandwidth().
sources
RTPSessionSources qrtplib::RTPSession::sources private
Definition at line 571 of file rtpsession.h.
Referenced by BYEDestroy(), Destroy(), GetCurrentSourceInfo(), GetNextPacket(), GetSourceInfo(), GotoFirstSource(), GotoFirstSourceWithData(), GotoNextSource(), GotoNextSourceWithData(), GotoPreviousSource(), GotoPreviousSourceWithData(), InternalCreate(), ProcessPolledData(), SendPacket(), and SendPacketEx().
useSR_BYEifpossible
bool qrtplib::RTPSession::useSR_BYEifpossible private
Definition at line 558 of file rtpsession.h.
Referenced by BYEDestroy(), Create(), and ProcessPolledData().
usingpollthread
bool qrtplib::RTPSession::usingpollthread private
Definition at line 556 of file rtpsession.h.
Referenced by Create(), and GetRTCPDelay().
The documentation for this class was generated from the following files:
qrtplib/rtpsession.h
qrtplib/rtpsession.cpp