SDRAngel: WFMModGUI Class Reference
WFMModGUI Class Reference
#include <wfmmodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static WFMModGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx)
Private Slots
void handleSourceMessages ()
void on_deltaFrequency_changed (qint64 value)
void on_rfBW_currentIndexChanged (int index)
void on_afBW_valueChanged (int value)
void on_fmDev_valueChanged (int value)
void on_toneFrequency_valueChanged (int value)
void on_volume_valueChanged (int value)
void on_channelMute_toggled (bool checked)
void on_tone_toggled (bool checked)
void on_morseKeyer_toggled (bool checked)
void on_mic_toggled (bool checked)
void on_play_toggled (bool checked)
void on_playLoop_toggled (bool checked)
void on_navTimeSlider_valueChanged (int value)
void on_showFileDialog_clicked (bool checked)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void configureFileName ()
void audioSelect ()
void tick ()
Private Member Functions
WFMModGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSource *channelTx, QWidget *parent=0)
virtual ~WFMModGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
void updateWithStreamData ()
void updateWithStreamTime ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Static Private Member Functions
static int requiredBW (int rfBW)
Private Attributes
Ui::WFMModGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
WFMModSettings m_settings
bool m_doApplySettings
WFMMod * m_wfmMod
MovingAverageUtil< double, double, 20 > m_channelPowerDbAvg
QString m_fileName
quint32 m_recordLength
int m_recordSampleRate
int m_samplesCount
std::size_t m_tickCount
bool m_enableNavTime
MessageQueue m_inputMessageQueue
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 40 of file wfmmodgui.h.
Constructor & Destructor Documentation
WFMModGUI()
WFMModGUI::WFMModGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx, QWidget * parent = 0) explicit private
Definition at line 318 of file wfmmodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), arg(), audioSelect(), blockApplySettings(), channelMarkerChangedByCursor(), displaySettings(), WFMMod::getCWKeyer(), getInputMessageQueue(), MainWindow::getInstance(), WFMModSettings::getRFBW(), ColorMapper::GrayGold, handleSourceMessages(), i, WFMMod::m_channelIdURI, m_channelMarker, m_deviceUISet, WFMModSettings::m_nbRfBW, m_settings, m_wfmMod, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerTxChannelInstance(), ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), WFMModSettings::setChannelMarker(), ChannelMarker::setColor(), WFMModSettings::setCWKeyerGUI(), BasebandSampleSource::setMessageQueueToGUI(), ChannelMarker::setSourceOrSinkStream(), ChannelMarker::setTitle(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                      :
     RollupWidget(parent),
     ui(new Ui::WFMModGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_doApplySettings(true),
     m_recordLength(0),
     m_recordSampleRate(48000),
     m_samplesCount(0),
     m_tickCount(0),
     m_enableNavTime(false)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     blockApplySettings(true);
     ui->rfBW->clear();
     for (int i = 0; i < WFMModSettings::m_nbRfBW; i++) {
         ui->rfBW->addItem(QString("%1").arg(WFMModSettings::getRFBW(i) / 1000.0, 0, 'f', 2));
     }
     ui->rfBW->setCurrentIndex(7);
     blockApplySettings(false);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_wfmMod = (WFMMod*) channelTx; //new WFMMod(m_deviceUISet->m_deviceSinkAPI);
     m_wfmMod->setMessageQueueToGUI(getInputMessageQueue());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     CRightClickEnabler *audioMuteRightClickEnabler = new CRightClickEnabler(ui->mic);
     connect(audioMuteRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioSelect()));
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(Qt::blue);
     m_channelMarker.setBandwidth(125000);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("WFM Modulator");
     m_channelMarker.setSourceOrSinkStream(false);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     m_deviceUISet->registerTxChannelInstance(WFMMod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     ui->play->setEnabled(false);
     ui->play->setChecked(false);
     ui->tone->setChecked(false);
     ui->mic->setChecked(false);
     ui->cwKeyerGUI->setCWKeyer(m_wfmMod->getCWKeyer());
     m_settings.setChannelMarker(&m_channelMarker);
     m_settings.setCWKeyerGUI(ui->cwKeyerGUI);
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     connect(m_wfmMod, SIGNAL(levelChanged(qreal, qreal, int)), ui->volumeMeter, SLOT(levelChanged(qreal, qreal, int)));
     displaySettings();
     applySettings(true);
 }
~WFMModGUI()
WFMModGUI::~WFMModGUI () private virtual
Definition at line 391 of file wfmmodgui.cpp.
References m_deviceUISet, m_wfmMod, DeviceUISet::removeTxChannelInstance(), and ui.
 {
     m_deviceUISet->removeTxChannelInstance(this);
     delete m_wfmMod; // TODO: check this: when the GUI closes it has to delete the modulator
     delete ui;
 }
Member Function Documentation
applySettings()
void WFMModGUI::applySettings (bool force = false) private
Definition at line 403 of file wfmmodgui.cpp.
References WFMMod::MsgConfigureWFMMod::create(), WFMMod::MsgConfigureChannelizer::create(), ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasebandSampleSource::getInputMessageQueue(), WFMModSettings::getRFBW(), m_channelMarker, m_doApplySettings, m_settings, m_wfmMod, MessageQueue::push(), requiredBW(), RollupWidget::setTitleColor(), and ui.
Referenced by audioSelect(), channelMarkerChangedByCursor(), deserialize(), on_afBW_valueChanged(), on_channelMute_toggled(), on_deltaFrequency_changed(), on_fmDev_valueChanged(), on_mic_toggled(), on_morseKeyer_toggled(), on_play_toggled(), on_playLoop_toggled(), on_rfBW_currentIndexChanged(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), setCenterFrequency(), and WFMModGUI().
 {
     if (m_doApplySettings)
     {
         setTitleColor(m_channelMarker.getColor());
         WFMMod::MsgConfigureChannelizer *msgChan = WFMMod::MsgConfigureChannelizer::create(
                 requiredBW(WFMModSettings::getRFBW(ui->rfBW->currentIndex())),
                 m_channelMarker.getCenterFrequency());
         m_wfmMod->getInputMessageQueue()->push(msgChan);
         ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
         WFMMod::MsgConfigureWFMMod *msgConf = WFMMod::MsgConfigureWFMMod::create(m_settings, force);
         m_wfmMod->getInputMessageQueue()->push(msgConf);
     }
 }
audioSelect
void WFMModGUI::audioSelect () private slot
Definition at line 477 of file wfmmodgui.cpp.
References applySettings(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, WFMModSettings::m_audioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by WFMModGUI().
 {
     qDebug("WFMModGUI::audioSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName, true); // true for input
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_audioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
blockApplySettings()
void WFMModGUI::blockApplySettings (bool block) private
Definition at line 398 of file wfmmodgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), handleMessage(), and WFMModGUI().
 {
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void WFMModGUI::channelMarkerChangedByCursor () slot
Definition at line 132 of file wfmmodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, WFMModSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by WFMModGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
configureFileName
void WFMModGUI::configureFileName () private slot
Definition at line 273 of file wfmmodgui.cpp.
References WFMMod::MsgConfigureFileSourceName::create(), BasebandSampleSource::getInputMessageQueue(), m_fileName, m_wfmMod, and MessageQueue::push().
Referenced by on_showFileDialog_clicked().
 {
     qDebug() << "FileSourceGui::configureFileName: " << m_fileName.toStdString().c_str();
     WFMMod::MsgConfigureFileSourceName* message = WFMMod::MsgConfigureFileSourceName::create(m_fileName);
     m_wfmMod->getInputMessageQueue()->push(message);
 }
create()
WFMModGUI * WFMModGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSource * channelTx) static
Definition at line 39 of file wfmmodgui.cpp.
References WFMModGUI().
Referenced by WFMModPlugin::createTxChannelGUI().
 {
     WFMModGUI* gui = new WFMModGUI(pluginAPI, deviceUISet, channelTx);
     return gui;
 }
deserialize()
bool WFMModGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 82 of file wfmmodgui.cpp.
References applySettings(), WFMModSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void WFMModGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 45 of file wfmmodgui.cpp.
 {
     delete this;
 }
displaySettings()
void WFMModGUI::displaySettings () private
Definition at line 421 of file wfmmodgui.cpp.
References arg(), blockApplySettings(), ChannelMarker::getCenterFrequency(), WFMModSettings::getRFBWIndex(), ChannelMarker::getTitle(), WFMModSettings::m_afBandwidth, m_channelMarker, WFMModSettings::m_channelMute, WFMModSettings::m_fmDeviation, WFMModSettings::m_inputFrequencyOffset, WFMModSettings::m_modAFInput, WFMModSettings::m_playLoop, WFMModSettings::m_rfBandwidth, WFMModSettings::m_rgbColor, m_settings, WFMModSettings::m_title, WFMModSettings::m_toneFrequency, WFMModSettings::m_volumeFactor, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by deserialize(), handleMessage(), resetToDefaults(), and WFMModGUI().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.setBandwidth(m_settings.m_rfBandwidth);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     ui->rfBW->setCurrentIndex(WFMModSettings::getRFBWIndex(m_settings.m_rfBandwidth));
     ui->afBWText->setText(QString("%1k").arg(m_settings.m_afBandwidth / 1000.0));
     ui->afBW->setValue(m_settings.m_afBandwidth / 1000.0);
     ui->fmDevText->setText(QString("%1k").arg(m_settings.m_fmDeviation / 1000.0));
     ui->fmDev->setValue(m_settings.m_fmDeviation / 1000.0);
     ui->volumeText->setText(QString("%1").arg(m_settings.m_volumeFactor, 0, 'f', 1));
     ui->volume->setValue(m_settings.m_volumeFactor * 10.0);
     ui->toneFrequencyText->setText(QString("%1k").arg(m_settings.m_toneFrequency / 1000.0, 0, 'f', 2));
     ui->toneFrequency->setValue(m_settings.m_toneFrequency / 10.0);
     ui->channelMute->setChecked(m_settings.m_channelMute);
     ui->playLoop->setChecked(m_settings.m_playLoop);
     ui->tone->setEnabled((m_settings.m_modAFInput == WFMModSettings::WFMModInputAF::WFMModInputTone) || (m_settings.m_modAFInput == WFMModSettings::WFMModInputAF::WFMModInputNone));
     ui->mic->setEnabled((m_settings.m_modAFInput == WFMModSettings::WFMModInputAF::WFMModInputAudio) || (m_settings.m_modAFInput == WFMModSettings::WFMModInputAF::WFMModInputNone));
     ui->play->setEnabled((m_settings.m_modAFInput == WFMModSettings::WFMModInputAF::WFMModInputFile) || (m_settings.m_modAFInput == WFMModSettings::WFMModInputAF::WFMModInputNone));
     ui->morseKeyer->setEnabled((m_settings.m_modAFInput == WFMModSettings::WFMModInputAF::WFMModInputCWTone) || (m_settings.m_modAFInput == WFMModSettings::WFMModInputAF::WFMModInputNone));
     ui->tone->setChecked(m_settings.m_modAFInput == WFMModSettings::WFMModInputAF::WFMModInputTone);
     ui->mic->setChecked(m_settings.m_modAFInput == WFMModSettings::WFMModInputAF::WFMModInputAudio);
     ui->play->setChecked(m_settings.m_modAFInput == WFMModSettings::WFMModInputAF::WFMModInputFile);
     ui->morseKeyer->setChecked(m_settings.m_modAFInput == WFMModSettings::WFMModInputAF::WFMModInputCWTone);
     blockApplySettings(false);
 }
enterEvent()
void WFMModGUI::enterEvent (QEvent *) private
Definition at line 472 of file wfmmodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 WFMModGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 60 of file wfmmodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
{
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* WFMModGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 55 of file wfmmodgui.h.
Referenced by handleSourceMessages(), and WFMModGUI().
 { return &m_inputMessageQueue; }
getName()
QString WFMModGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 55 of file wfmmodgui.cpp.
 {
     return objectName();
 }
handleMessage()
bool WFMModGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 94 of file wfmmodgui.cpp.
References blockApplySettings(), displaySettings(), WFMMod::MsgConfigureWFMMod::getSettings(), CWKeyer::MsgConfigureCWKeyer::getSettings(), m_recordLength, m_recordSampleRate, m_samplesCount, m_settings, Message::match(), ui, updateWithStreamData(), and updateWithStreamTime().
Referenced by handleSourceMessages().
 {
     if (WFMMod::MsgReportFileSourceStreamData::match(message))
     {
         m_recordSampleRate = ((WFMMod::MsgReportFileSourceStreamData&)message).getSampleRate();
         m_recordLength = ((WFMMod::MsgReportFileSourceStreamData&)message).getRecordLength();
         m_samplesCount = 0;
         updateWithStreamData();
         return true;
     }
     else if (WFMMod::MsgReportFileSourceStreamTiming::match(message))
     {
         m_samplesCount = ((WFMMod::MsgReportFileSourceStreamTiming&)message).getSamplesCount();
         updateWithStreamTime();
         return true;
     }
     else if (WFMMod::MsgConfigureWFMMod::match(message))
     {
         const WFMMod::MsgConfigureWFMMod& cfg = (WFMMod::MsgConfigureWFMMod&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (CWKeyer::MsgConfigureCWKeyer::match(message))
     {
         const CWKeyer::MsgConfigureCWKeyer& cfg = (CWKeyer::MsgConfigureCWKeyer&) message;
         ui->cwKeyerGUI->setSettings(cfg.getSettings());
         ui->cwKeyerGUI->displaySettings();
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void WFMModGUI::handleSourceMessages () private slot
Definition at line 139 of file wfmmodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by WFMModGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void WFMModGUI::leaveEvent (QEvent *) private
Definition at line 467 of file wfmmodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_afBW_valueChanged
void WFMModGUI::on_afBW_valueChanged (int value) private slot
Definition at line 167 of file wfmmodgui.cpp.
References applySettings(), arg(), WFMModSettings::m_afBandwidth, m_settings, and ui.
 {
     ui->afBWText->setText(QString("%1k").arg(value));
     m_settings.m_afBandwidth = value * 1000.0;
     applySettings();
 }
on_channelMute_toggled
void WFMModGUI::on_channelMute_toggled (bool checked) private slot
Definition at line 195 of file wfmmodgui.cpp.
References applySettings(), WFMModSettings::m_channelMute, and m_settings.
 {
     m_settings.m_channelMute = checked;
     applySettings();
 }
on_deltaFrequency_changed
void WFMModGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 152 of file wfmmodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, WFMModSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_fmDev_valueChanged
void WFMModGUI::on_fmDev_valueChanged (int value) private slot
Definition at line 174 of file wfmmodgui.cpp.
References applySettings(), arg(), WFMModSettings::m_fmDeviation, m_settings, and ui.
 {
     ui->fmDevText->setText(QString("%1k").arg(value));
     m_settings.m_fmDeviation = value * 1000.0;
     applySettings();
 }
on_mic_toggled
void WFMModGUI::on_mic_toggled (bool checked) private slot
Definition at line 236 of file wfmmodgui.cpp.
References applySettings(), WFMModSettings::m_modAFInput, m_settings, ui, WFMModSettings::WFMModInputAudio, and WFMModSettings::WFMModInputNone.
 {
     ui->play->setEnabled(!checked); // release other source inputs
     ui->tone->setEnabled(!checked); // release other source inputs
     ui->morseKeyer->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? WFMModSettings::WFMModInputAudio : WFMModSettings::WFMModInputNone;
     applySettings();
 }
on_morseKeyer_toggled
void WFMModGUI::on_morseKeyer_toggled (bool checked) private slot
Definition at line 227 of file wfmmodgui.cpp.
References applySettings(), WFMModSettings::m_modAFInput, m_settings, ui, WFMModSettings::WFMModInputCWTone, and WFMModSettings::WFMModInputNone.
 {
     ui->tone->setEnabled(!checked); // release other source inputs
     ui->mic->setEnabled(!checked);
     ui->play->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? WFMModSettings::WFMModInputCWTone : WFMModSettings::WFMModInputNone;
     applySettings();
 }
on_navTimeSlider_valueChanged
void WFMModGUI::on_navTimeSlider_valueChanged (int value) private slot
Definition at line 245 of file wfmmodgui.cpp.
References WFMMod::MsgConfigureFileSourceSeek::create(), BasebandSampleSource::getInputMessageQueue(), m_enableNavTime, m_recordLength, m_wfmMod, and MessageQueue::push().
 {
     if (m_enableNavTime && ((value >= 0) && (value <= 100)))
     {
         int t_sec = (m_recordLength * value) / 100;
         QTime t(0, 0, 0, 0);
         t = t.addSecs(t_sec);
         WFMMod::MsgConfigureFileSourceSeek* message = WFMMod::MsgConfigureFileSourceSeek::create(value);
         m_wfmMod->getInputMessageQueue()->push(message);
     }
 }
on_play_toggled
void WFMModGUI::on_play_toggled (bool checked) private slot
Definition at line 207 of file wfmmodgui.cpp.
References applySettings(), m_enableNavTime, WFMModSettings::m_modAFInput, m_settings, ui, WFMModSettings::WFMModInputFile, and WFMModSettings::WFMModInputNone.
 {
     ui->tone->setEnabled(!checked); // release other source inputs
     ui->mic->setEnabled(!checked);
     ui->morseKeyer->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? WFMModSettings::WFMModInputFile : WFMModSettings::WFMModInputNone;
     applySettings();
     ui->navTimeSlider->setEnabled(!checked);
     m_enableNavTime = !checked;
 }
on_playLoop_toggled
void WFMModGUI::on_playLoop_toggled (bool checked) private slot
Definition at line 201 of file wfmmodgui.cpp.
References applySettings(), WFMModSettings::m_playLoop, and m_settings.
 {
     m_settings.m_playLoop = checked;
     applySettings();
 }
on_rfBW_currentIndexChanged
void WFMModGUI::on_rfBW_currentIndexChanged (int index) private slot
Definition at line 159 of file wfmmodgui.cpp.
References applySettings(), WFMModSettings::getRFBW(), m_channelMarker, WFMModSettings::m_rfBandwidth, m_settings, and ChannelMarker::setBandwidth().
 {
     float rfBW = WFMModSettings::getRFBW(index);
     m_channelMarker.setBandwidth(rfBW);
     m_settings.m_rfBandwidth = rfBW;
     applySettings();
 }
on_showFileDialog_clicked
void WFMModGUI::on_showFileDialog_clicked (bool checked) private slot
Definition at line 258 of file wfmmodgui.cpp.
References configureFileName(), m_fileName, and ui.
 {
     (void) checked;
     QString fileName = QFileDialog::getOpenFileName(this,
         tr("Open raw audio file"), ".", tr("Raw audio Files (*.raw)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "")
     {
         m_fileName = fileName;
         ui->recordFileText->setText(m_fileName);
         ui->play->setEnabled(true);
         configureFileName();
     }
 }
on_tone_toggled
void WFMModGUI::on_tone_toggled (bool checked) private slot
Definition at line 218 of file wfmmodgui.cpp.
References applySettings(), WFMModSettings::m_modAFInput, m_settings, ui, WFMModSettings::WFMModInputNone, and WFMModSettings::WFMModInputTone.
 {
     ui->play->setEnabled(!checked); // release other source inputs
     ui->mic->setEnabled(!checked);
     ui->morseKeyer->setEnabled(!checked);
     m_settings.m_modAFInput = checked ? WFMModSettings::WFMModInputTone : WFMModSettings::WFMModInputNone;
     applySettings();
 }
on_toneFrequency_valueChanged
void WFMModGUI::on_toneFrequency_valueChanged (int value) private slot
Definition at line 188 of file wfmmodgui.cpp.
References applySettings(), arg(), m_settings, WFMModSettings::m_toneFrequency, and ui.
 {
     ui->toneFrequencyText->setText(QString("%1k").arg(value / 100.0, 0, 'f', 2));
     m_settings.m_toneFrequency = value * 10.0;
     applySettings();
 }
on_volume_valueChanged
void WFMModGUI::on_volume_valueChanged (int value) private slot
Definition at line 181 of file wfmmodgui.cpp.
References applySettings(), arg(), m_settings, WFMModSettings::m_volumeFactor, and ui.
 {
     ui->volumeText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_volumeFactor = value / 10.0;
     applySettings();
 }
onMenuDialogCalled
void WFMModGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 286 of file wfmmodgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, WFMModSettings::m_inputFrequencyOffset, WFMModSettings::m_reverseAPIAddress, WFMModSettings::m_reverseAPIChannelIndex, WFMModSettings::m_reverseAPIDeviceIndex, WFMModSettings::m_reverseAPIPort, WFMModSettings::m_rgbColor, m_settings, WFMModSettings::m_title, WFMModSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by WFMModGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void WFMModGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 280 of file wfmmodgui.cpp.
Referenced by WFMModGUI().
 {
     (void) widget;
     (void) rollDown;
 }
requiredBW()
static int WFMModGUI::requiredBW (int rfBW) inline static private
Definition at line 94 of file wfmmodgui.h.
Referenced by applySettings().
     {
         if (rfBW <= 96000) {
             return 96000;
         } else {
             return (3*rfBW)/2;
         }
     }
resetToDefaults()
void WFMModGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 70 of file wfmmodgui.cpp.
References applySettings(), displaySettings(), m_settings, and WFMModSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
serialize()
QByteArray WFMModGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 77 of file wfmmodgui.cpp.
References m_settings, and WFMModSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void WFMModGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 64 of file wfmmodgui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     applySettings();
 }
setName()
void WFMModGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 50 of file wfmmodgui.cpp.
 {
     setObjectName(name);
 }
tick
void WFMModGUI::tick () private slot
Definition at line 490 of file wfmmodgui.cpp.
References arg(), WFMMod::MsgConfigureFileSourceStreamTiming::create(), CalcDb::dbPower(), BasebandSampleSource::getInputMessageQueue(), WFMMod::getMagSq(), m_channelPowerDbAvg, WFMModSettings::m_modAFInput, m_settings, m_tickCount, m_wfmMod, MessageQueue::push(), ui, and WFMModSettings::WFMModInputFile.
Referenced by WFMModGUI().
 {
     double powDb = CalcDb::dbPower(m_wfmMod->getMagSq());
     m_channelPowerDbAvg(powDb);
     ui->channelPower->setText(tr("%1 dB").arg(m_channelPowerDbAvg.asDouble(), 0, 'f', 1));
     if (((++m_tickCount & 0xf) == 0) && (m_settings.m_modAFInput == WFMModSettings::WFMModInputFile))
     {
         WFMMod::MsgConfigureFileSourceStreamTiming* message = WFMMod::MsgConfigureFileSourceStreamTiming::create();
         m_wfmMod->getInputMessageQueue()->push(message);
     }
 }
updateWithStreamData()
void WFMModGUI::updateWithStreamData () private
Definition at line 503 of file wfmmodgui.cpp.
References m_recordLength, ui, and updateWithStreamTime().
Referenced by handleMessage().
 {
     QTime recordLength(0, 0, 0, 0);
     recordLength = recordLength.addSecs(m_recordLength);
     QString s_time = recordLength.toString("HH:mm:ss");
     ui->recordLengthText->setText(s_time);
     updateWithStreamTime();
 }
updateWithStreamTime()
void WFMModGUI::updateWithStreamTime () private
Definition at line 512 of file wfmmodgui.cpp.
References m_enableNavTime, m_recordLength, m_recordSampleRate, m_samplesCount, and ui.
Referenced by handleMessage(), and updateWithStreamData().
 {
     int t_sec = 0;
     int t_msec = 0;
     if (m_recordSampleRate > 0)
     {
         t_msec = ((m_samplesCount * 1000) / m_recordSampleRate) % 1000;
         t_sec = m_samplesCount / m_recordSampleRate;
     }
     QTime t(0, 0, 0, 0);
     t = t.addSecs(t_sec);
     t = t.addMSecs(t_msec);
     QString s_timems = t.toString("HH:mm:ss.zzz");
     QString s_time = t.toString("HH:mm:ss");
     ui->relTimeText->setText(s_timems);
     if (!m_enableNavTime)
     {
         float posRatio = (float) t_sec / (float) m_recordLength;
         ui->navTimeSlider->setValue((int) (posRatio * 100.0));
     }
 }
Member Data Documentation
m_channelMarker
ChannelMarker WFMModGUI::m_channelMarker private
Definition at line 65 of file wfmmodgui.h.
Referenced by applySettings(), channelMarkerChangedByCursor(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), on_rfBW_currentIndexChanged(), onMenuDialogCalled(), setCenterFrequency(), and WFMModGUI().
m_channelPowerDbAvg
MovingAverageUtil<double, double, 20> WFMModGUI::m_channelPowerDbAvg private
Definition at line 72 of file wfmmodgui.h.
Referenced by tick().
m_deviceUISet
DeviceUISet* WFMModGUI::m_deviceUISet private
Definition at line 64 of file wfmmodgui.h.
Referenced by WFMModGUI(), and ~WFMModGUI().
m_doApplySettings
bool WFMModGUI::m_doApplySettings private
Definition at line 67 of file wfmmodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_enableNavTime
bool WFMModGUI::m_enableNavTime private
Definition at line 79 of file wfmmodgui.h.
Referenced by on_navTimeSlider_valueChanged(), on_play_toggled(), and updateWithStreamTime().
m_fileName
QString WFMModGUI::m_fileName private
Definition at line 74 of file wfmmodgui.h.
Referenced by configureFileName(), and on_showFileDialog_clicked().
m_inputMessageQueue
MessageQueue WFMModGUI::m_inputMessageQueue private
Definition at line 80 of file wfmmodgui.h.
m_pluginAPI
PluginAPI* WFMModGUI::m_pluginAPI private
Definition at line 63 of file wfmmodgui.h.
m_recordLength
quint32 WFMModGUI::m_recordLength private
Definition at line 75 of file wfmmodgui.h.
Referenced by handleMessage(), on_navTimeSlider_valueChanged(), updateWithStreamData(), and updateWithStreamTime().
m_recordSampleRate
int WFMModGUI::m_recordSampleRate private
Definition at line 76 of file wfmmodgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_samplesCount
int WFMModGUI::m_samplesCount private
Definition at line 77 of file wfmmodgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_settings
WFMModSettings WFMModGUI::m_settings private
Definition at line 66 of file wfmmodgui.h.
Referenced by applySettings(), audioSelect(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), handleMessage(), on_afBW_valueChanged(), on_channelMute_toggled(), on_deltaFrequency_changed(), on_fmDev_valueChanged(), on_mic_toggled(), on_morseKeyer_toggled(), on_play_toggled(), on_playLoop_toggled(), on_rfBW_currentIndexChanged(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), serialize(), tick(), and WFMModGUI().
m_tickCount
std::size_t WFMModGUI::m_tickCount private
Definition at line 78 of file wfmmodgui.h.
Referenced by tick().
m_wfmMod
WFMMod* WFMModGUI::m_wfmMod private
Definition at line 71 of file wfmmodgui.h.
Referenced by applySettings(), configureFileName(), on_navTimeSlider_valueChanged(), tick(), WFMModGUI(), and ~WFMModGUI().
ui
Ui::WFMModGUI* WFMModGUI::ui private
Definition at line 62 of file wfmmodgui.h.
Referenced by applySettings(), channelMarkerChangedByCursor(), displaySettings(), handleMessage(), on_afBW_valueChanged(), on_fmDev_valueChanged(), on_mic_toggled(), on_morseKeyer_toggled(), on_play_toggled(), on_showFileDialog_clicked(), on_tone_toggled(), on_toneFrequency_valueChanged(), on_volume_valueChanged(), tick(), updateWithStreamData(), updateWithStreamTime(), WFMModGUI(), and ~WFMModGUI().
The documentation for this class was generated from the following files:
plugins/channeltx/modwfm/wfmmodgui.h
plugins/channeltx/modwfm/wfmmodgui.cpp