SDRAngel: SWGSDRangel::SWGPresetImport Class Reference
SWGSDRangel::SWGPresetImport Class Reference
#include <SWGPresetImport.h>
Public Member Functions
SWGPresetImport ()
SWGPresetImport (QString *json)
virtual ~SWGPresetImport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGPresetImport * fromJson (QString &jsonString) override
QString * getGroupName ()
void setGroupName (QString *group_name)
QString * getDescription ()
void setDescription (QString *description)
QString * getFilePath ()
void setFilePath (QString *file_path)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * group_name
bool m_group_name_isSet
QString * description
bool m_description_isSet
QString * file_path
bool m_file_path_isSet
Detailed Description
Definition at line 32 of file SWGPresetImport.h.
Constructor & Destructor Documentation
SWGPresetImport() [1/2]
SWGSDRangel::SWGPresetImport::SWGPresetImport ()
Definition at line 30 of file SWGPresetImport.cpp.
References description, file_path, group_name, m_description_isSet, m_file_path_isSet, and m_group_name_isSet.
{
     group_name = nullptr;
     m_group_name_isSet = false;
     description = nullptr;
     m_description_isSet = false;
     file_path = nullptr;
     m_file_path_isSet = false;
 }
SWGPresetImport() [2/2]
SWGSDRangel::SWGPresetImport::SWGPresetImport (QString * json)
Definition at line 25 of file SWGPresetImport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGPresetImport()
SWGSDRangel::SWGPresetImport::~SWGPresetImport () virtual
Definition at line 39 of file SWGPresetImport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGPresetImport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 86 of file SWGPresetImport.cpp.
References asJsonObject().
Referenced by SWGSDRangel::SWGInstanceApi::instancePresetFilePut().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGPresetImport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 97 of file SWGPresetImport.cpp.
References description, file_path, group_name, and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(group_name != nullptr && *group_name != QString("")){
         toJsonValue(QString("groupName"), group_name, obj, QString("QString"));
     }
     if(description != nullptr && *description != QString("")){
         toJsonValue(QString("description"), description, obj, QString("QString"));
     }
     if(file_path != nullptr && *file_path != QString("")){
         toJsonValue(QString("filePath"), file_path, obj, QString("QString"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGPresetImport::cleanup ()
Definition at line 54 of file SWGPresetImport.cpp.
References description, file_path, and group_name.
Referenced by ~SWGPresetImport().
{
     if(group_name != nullptr) {
         delete group_name;
     }
     if(description != nullptr) {
         delete description;
     }
     if(file_path != nullptr) {
         delete file_path;
     }
 }
fromJson()
SWGPresetImport * SWGSDRangel::SWGPresetImport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 67 of file SWGPresetImport.cpp.
References fromJsonObject().
Referenced by WebAPIRequestMapper::instancePresetFileService(), and SWGPresetImport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGPresetImport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 76 of file SWGPresetImport.cpp.
References description, file_path, group_name, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&group_name, pJson["groupName"], "QString", "QString");
     ::SWGSDRangel::setValue(&description, pJson["description"], "QString", "QString");
     ::SWGSDRangel::setValue(&file_path, pJson["filePath"], "QString", "QString");
 }
getDescription()
QString * SWGSDRangel::SWGPresetImport::getDescription ()
Definition at line 123 of file SWGPresetImport.cpp.
References description.
Referenced by WebAPIAdapterSrv::instancePresetFilePut().
{
     return description;
 }
getFilePath()
QString * SWGSDRangel::SWGPresetImport::getFilePath ()
Definition at line 133 of file SWGPresetImport.cpp.
References file_path.
Referenced by WebAPIAdapterSrv::instancePresetFilePut(), and WebAPIRequestMapper::instancePresetFileService().
{
     return file_path;
 }
getGroupName()
QString * SWGSDRangel::SWGPresetImport::getGroupName ()
Definition at line 113 of file SWGPresetImport.cpp.
References group_name.
Referenced by WebAPIAdapterSrv::instancePresetFilePut().
{
     return group_name;
 }
init()
void SWGSDRangel::SWGPresetImport::init ()
Definition at line 44 of file SWGPresetImport.cpp.
References description, file_path, group_name, m_description_isSet, m_file_path_isSet, and m_group_name_isSet.
Referenced by SWGPresetImport().
                       {
     group_name = new QString("");
     m_group_name_isSet = false;
     description = new QString("");
     m_description_isSet = false;
     file_path = new QString("");
     m_file_path_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGPresetImport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 144 of file SWGPresetImport.cpp.
References description, file_path, and group_name.
                       {
     bool isObjectUpdated = false;
     do{
         if(group_name != nullptr && *group_name != QString("")){ isObjectUpdated = true; break;}
         if(description != nullptr && *description != QString("")){ isObjectUpdated = true; break;}
         if(file_path != nullptr && *file_path != QString("")){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setDescription()
void SWGSDRangel::SWGPresetImport::setDescription (QString * description)
Definition at line 127 of file SWGPresetImport.cpp.
References description, and m_description_isSet.
{
     this->description = description;
     this->m_description_isSet = true;
 }
setFilePath()
void SWGSDRangel::SWGPresetImport::setFilePath (QString * file_path)
Definition at line 137 of file SWGPresetImport.cpp.
References file_path, and m_file_path_isSet.
{
     this->file_path = file_path;
     this->m_file_path_isSet = true;
 }
setGroupName()
void SWGSDRangel::SWGPresetImport::setGroupName (QString * group_name)
Definition at line 117 of file SWGPresetImport.cpp.
References group_name, and m_group_name_isSet.
{
     this->group_name = group_name;
     this->m_group_name_isSet = true;
 }
Member Data Documentation
description
QString* SWGSDRangel::SWGPresetImport::description private
Definition at line 61 of file SWGPresetImport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getDescription(), init(), isSet(), setDescription(), and SWGPresetImport().
file_path
QString* SWGSDRangel::SWGPresetImport::file_path private
Definition at line 64 of file SWGPresetImport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFilePath(), init(), isSet(), setFilePath(), and SWGPresetImport().
group_name
QString* SWGSDRangel::SWGPresetImport::group_name private
Definition at line 58 of file SWGPresetImport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getGroupName(), init(), isSet(), setGroupName(), and SWGPresetImport().
m_description_isSet
bool SWGSDRangel::SWGPresetImport::m_description_isSet private
Definition at line 62 of file SWGPresetImport.h.
Referenced by init(), setDescription(), and SWGPresetImport().
m_file_path_isSet
bool SWGSDRangel::SWGPresetImport::m_file_path_isSet private
Definition at line 65 of file SWGPresetImport.h.
Referenced by init(), setFilePath(), and SWGPresetImport().
m_group_name_isSet
bool SWGSDRangel::SWGPresetImport::m_group_name_isSet private
Definition at line 59 of file SWGPresetImport.h.
Referenced by init(), setGroupName(), and SWGPresetImport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGPresetImport.h
swagger/sdrangel/code/qt5/client/SWGPresetImport.cpp