SDRAngel: RemoteOutputSinkGui Class Reference
RemoteOutputSinkGui Class Reference
#include <remoteoutputgui.h>
Public Member Functions
RemoteOutputSinkGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~RemoteOutputSinkGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_sampleRate_changed (quint64 value)
void on_txDelay_valueChanged (int value)
void on_nbFECBlocks_valueChanged (int value)
void on_deviceIndex_returnPressed ()
void on_channelIndex_returnPressed ()
void on_apiAddress_returnPressed ()
void on_apiPort_returnPressed ()
void on_dataAddress_returnPressed ()
void on_dataPort_returnPressed ()
void on_apiApplyButton_clicked (bool checked)
void on_dataApplyButton_clicked (bool checked)
void on_startStop_toggled (bool checked)
void on_eventCountsReset_clicked (bool checked)
void updateHardware ()
void updateStatus ()
void tick ()
void networkManagerFinished (QNetworkReply *reply)
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void displayTime ()
void sendControl (bool force=false)
void sendSettings ()
void updateSampleRate ()
void updateTxDelayTooltip ()
void displayEventCounts ()
void displayEventStatus (int recoverableCount, int unrecoverableCount)
void displayEventTimer ()
void analyzeApiReply (const QJsonObject &jsonObject)
Private Attributes
Ui::RemoteOutputGui * ui
DeviceUISet * m_deviceUISet
RemoteOutputSettings m_settings
current settings
RemoteOutputSettings m_controlSettings
settings last sent to device via control port
QTimer m_updateTimer
QTimer m_statusTimer
DeviceSampleSink * m_deviceSampleSink
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_samplesCount
uint32_t m_tickCount
std::size_t m_nbSinceLastFlowCheck
int m_lastEngineState
bool m_doApplySettings
bool m_forceSettings
uint32_t m_countUnrecoverable
uint32_t m_countRecovered
uint32_t m_lastCountUnrecoverable
uint32_t m_lastCountRecovered
uint32_t m_lastSampleCount
uint64_t m_lastTimestampUs
bool m_resetCounts
QTime m_time
QPalette m_paletteGreenText
QPalette m_paletteRedText
QPalette m_paletteWhiteText
MessageQueue m_inputMessageQueue
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Detailed Description
Definition at line 72 of file remoteoutputgui.h.
Constructor & Destructor Documentation
RemoteOutputSinkGui()
RemoteOutputSinkGui::RemoteOutputSinkGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 49 of file remoteoutputgui.cpp.
References displayEventCounts(), displayEventTimer(), displaySettings(), DeviceAPI::getMasterTimer(), DeviceAPI::getSampleSink(), DeviceUISet::getSpectrum(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, handleInputMessages(), m_countRecovered, m_countUnrecoverable, DeviceUISet::m_deviceAPI, m_deviceCenterFrequency, m_deviceSampleSink, m_deviceUISet, m_inputMessageQueue, m_lastCountRecovered, m_lastCountUnrecoverable, m_lastSampleCount, m_networkManager, m_paletteGreenText, m_paletteRedText, m_paletteWhiteText, m_resetCounts, m_statusTimer, m_time, m_updateTimer, networkManagerFinished(), openDeviceSettingsDialog(), sendSettings(), GLSpectrum::setCenterFrequency(), tick(), ui, updateHardware(), and updateStatus().
                                                                                   :
     QWidget(parent),
     ui(new Ui::RemoteOutputGui),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_deviceSampleSink(0),
     m_deviceCenterFrequency(0),
     m_samplesCount(0),
     m_tickCount(0),
     m_nbSinceLastFlowCheck(0),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_doApplySettings(true),
     m_forceSettings(true)
 {
     m_countUnrecoverable = 0;
     m_countRecovered = 0;
     m_lastCountUnrecoverable = 0;
     m_lastCountRecovered = 0;
     m_lastSampleCount = 0;
     m_resetCounts = true;
     m_paletteGreenText.setColor(QPalette::WindowText, Qt::green);
     m_paletteRedText.setColor(QPalette::WindowText, Qt::red);
     m_paletteWhiteText.setColor(QPalette::WindowText, Qt::white);
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, 0, pow(10,7));
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(7, 32000U, 9000000U);
     ui->apiAddressLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     connect(&(m_deviceUISet->m_deviceAPI->getMasterTimer()), SIGNAL(timeout()), this, SLOT(tick()));
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     m_deviceSampleSink = (RemoteOutput*) m_deviceUISet->m_deviceAPI->getSampleSink();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     m_time.start();
     displayEventCounts();
     displayEventTimer();
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     sendSettings();
 }
~RemoteOutputSinkGui()
RemoteOutputSinkGui::~RemoteOutputSinkGui () virtual
Definition at line 109 of file remoteoutputgui.cpp.
References m_networkManager, networkManagerFinished(), and ui.
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     delete ui;
 }
Member Function Documentation
analyzeApiReply()
void RemoteOutputSinkGui::analyzeApiReply (const QJsonObject & jsonObject) private
Definition at line 550 of file remoteoutputgui.cpp.
References arg(), displayEventCounts(), displayEventStatus(), DeviceUISet::getSpectrum(), m_countRecovered, m_countUnrecoverable, m_deviceCenterFrequency, m_deviceUISet, m_lastCountRecovered, m_lastCountUnrecoverable, m_lastSampleCount, m_lastTimestampUs, m_resetCounts, GLSpectrum::setCenterFrequency(), and ui.
Referenced by networkManagerFinished().
 {
     QString infoLine;
     if (jsonObject.contains("RemoteSourceReport"))
     {
         QJsonObject report = jsonObject["RemoteSourceReport"].toObject();
         m_deviceCenterFrequency = report["deviceCenterFreq"].toInt() * 1000;
         m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
         ui->centerFrequency->setValue(m_deviceCenterFrequency/1000);
         int remoteRate = report["deviceSampleRate"].toInt();
         ui->remoteRateText->setText(tr("%1k").arg((float)(remoteRate) / 1000));
         int queueSize = report["queueSize"].toInt();
         queueSize = queueSize == 0 ? 10 : queueSize;
         int queueLength = report["queueLength"].toInt();
         QString queueLengthText = QString("%1/%2").arg(queueLength).arg(queueSize);
         ui->queueLengthText->setText(queueLengthText);
         int queueLengthPercent = (queueLength*100)/queueSize;
         ui->queueLengthGauge->setValue(queueLengthPercent);
         int unrecoverableCount = report["uncorrectableErrorsCount"].toInt();
         int recoverableCount = report["correctableErrorsCount"].toInt();
         uint64_t timestampUs = report["tvSec"].toInt()*1000000ULL + report["tvUSec"].toInt();
         if (!m_resetCounts)
         {
             int recoverableCountDelta = recoverableCount - m_lastCountRecovered;
             int unrecoverableCountDelta = unrecoverableCount - m_lastCountUnrecoverable;
             displayEventStatus(recoverableCountDelta, unrecoverableCountDelta);
             m_countRecovered += recoverableCountDelta;
             m_countUnrecoverable += unrecoverableCountDelta;
             displayEventCounts();
         }
         uint32_t sampleCountDelta, sampleCount;
         sampleCount = report["samplesCount"].toInt();
         if (sampleCount < m_lastSampleCount) {
             sampleCountDelta = (0xFFFFFFFFU - m_lastSampleCount) + sampleCount + 1;
         } else {
             sampleCountDelta = sampleCount - m_lastSampleCount;
         }
         if (sampleCountDelta == 0)
         {
             ui->allFramesDecoded->setStyleSheet("QToolButton { background-color : blue; }");
         }
         double remoteStreamRate = sampleCountDelta*1e6 / (double) (timestampUs - m_lastTimestampUs);
         if (remoteStreamRate != 0) {
             ui->remoteStreamRateText->setText(QString("%1").arg(remoteStreamRate, 0, 'f', 0));
         }
         m_resetCounts = false;
         m_lastCountRecovered = recoverableCount;
         m_lastCountUnrecoverable = unrecoverableCount;
         m_lastSampleCount = sampleCount;
         m_lastTimestampUs = timestampUs;
     }
     if (jsonObject.contains("version")) {
         infoLine = "v" + jsonObject["version"].toString();
     }
     if (jsonObject.contains("qtVersion")) {
         infoLine += " Qt" + jsonObject["qtVersion"].toString();
     }
     if (jsonObject.contains("architecture")) {
         infoLine += " " + jsonObject["architecture"].toString();
     }
     if (jsonObject.contains("os")) {
         infoLine += " " + jsonObject["os"].toString();
     }
     if (jsonObject.contains("dspRxBits") && jsonObject.contains("dspTxBits")) {
         infoLine +=  QString(" %1/%2b").arg(jsonObject["dspRxBits"].toInt()).arg(jsonObject["dspTxBits"].toInt());
     }
     if (infoLine.size() > 0) {
         ui->infoText->setText(infoLine);
     }
 }
blockApplySettings()
void RemoteOutputSinkGui::blockApplySettings (bool block) private
Definition at line 116 of file remoteoutputgui.cpp.
References m_doApplySettings.
Referenced by deserialize(), displaySettings(), handleMessage(), and resetToDefaults().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool RemoteOutputSinkGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 150 of file remoteoutputgui.cpp.
References blockApplySettings(), RemoteOutputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, and sendSettings().
 {
     blockApplySettings(true);
     if(m_settings.deserialize(data))
     {
         displaySettings();
         blockApplySettings(false);
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         blockApplySettings(false);
         return false;
     }
 }
destroy()
void RemoteOutputSinkGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 121 of file remoteoutputgui.cpp.
 {
     delete this;
 }
displayEventCounts()
void RemoteOutputSinkGui::displayEventCounts () private
Definition at line 456 of file remoteoutputgui.cpp.
References m_countRecovered, m_countUnrecoverable, and ui.
Referenced by analyzeApiReply(), on_eventCountsReset_clicked(), and RemoteOutputSinkGui().
 {
     QString nstr = QString("%1").arg(m_countUnrecoverable, 3, 10, QChar('0'));
     ui->eventUnrecText->setText(nstr);
     nstr = QString("%1").arg(m_countRecovered, 3, 10, QChar('0'));
     ui->eventRecText->setText(nstr);
 }
displayEventStatus()
void RemoteOutputSinkGui::displayEventStatus (int recoverableCount, int unrecoverableCount) private
Definition at line 464 of file remoteoutputgui.cpp.
References ui.
Referenced by analyzeApiReply().
 {
     if (unrecoverableCount == 0)
     {
         if (recoverableCount == 0) {
             ui->allFramesDecoded->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->allFramesDecoded->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         }
     }
     else
     {
         ui->allFramesDecoded->setStyleSheet("QToolButton { background-color : red; }");
     }
 }
displayEventTimer()
void RemoteOutputSinkGui::displayEventTimer () private
Definition at line 481 of file remoteoutputgui.cpp.
References m_time, and ui.
Referenced by on_eventCountsReset_clicked(), RemoteOutputSinkGui(), and tick().
 {
     int elapsedTimeMillis = m_time.elapsed();
     QTime recordLength(0, 0, 0, 0);
     recordLength = recordLength.addSecs(elapsedTimeMillis/1000);
     QString s_time = recordLength.toString("HH:mm:ss");
     ui->eventCountsTimeText->setText(s_time);
 }
displaySettings()
void RemoteOutputSinkGui::displaySettings () private
Definition at line 231 of file remoteoutputgui.cpp.
References arg(), blockApplySettings(), RemoteOutputSettings::m_apiAddress, RemoteOutputSettings::m_apiPort, RemoteOutputSettings::m_channelIndex, RemoteOutputSettings::m_dataAddress, RemoteOutputSettings::m_dataPort, m_deviceCenterFrequency, RemoteOutputSettings::m_deviceIndex, RemoteOutputSettings::m_nbFECBlocks, RemoteOutputSettings::m_sampleRate, m_settings, RemoteOutputSettings::m_txDelay, and ui.
Referenced by deserialize(), handleMessage(), RemoteOutputSinkGui(), and resetToDefaults().
 {
     blockApplySettings(true);
     ui->centerFrequency->setValue(m_deviceCenterFrequency / 1000);
     ui->sampleRate->setValue(m_settings.m_sampleRate);
     ui->txDelay->setValue(m_settings.m_txDelay*100);
     ui->txDelayText->setText(tr("%1").arg(m_settings.m_txDelay*100));
     ui->nbFECBlocks->setValue(m_settings.m_nbFECBlocks);
     QString s0 = QString::number(128 + m_settings.m_nbFECBlocks, 'f', 0);
     QString s1 = QString::number(m_settings.m_nbFECBlocks, 'f', 0);
     ui->nominalNbBlocksText->setText(tr("%1/%2").arg(s0).arg(s1));
     ui->deviceIndex->setText(tr("%1").arg(m_settings.m_deviceIndex));
     ui->channelIndex->setText(tr("%1").arg(m_settings.m_channelIndex));
     ui->apiAddress->setText(m_settings.m_apiAddress);
     ui->apiPort->setText(tr("%1").arg(m_settings.m_apiPort));
     ui->dataAddress->setText(m_settings.m_dataAddress);
     ui->dataPort->setText(tr("%1").arg(m_settings.m_dataPort));
     blockApplySettings(false);
 }
displayTime()
void RemoteOutputSinkGui::displayTime () private
getCenterFrequency()
virtual qint64 RemoteOutputSinkGui::getCenterFrequency () const inline virtual
Implements PluginInstanceGUI.
Definition at line 84 of file remoteoutputgui.h.
 { return m_deviceCenterFrequency; }
getInputMessageQueue()
virtual MessageQueue* RemoteOutputSinkGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 88 of file remoteoutputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString RemoteOutputSinkGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 131 of file remoteoutputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void RemoteOutputSinkGui::handleInputMessages () private slot
Definition at line 194 of file remoteoutputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), DSPSignalNotification::getSampleRate(), handleMessage(), m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRate().
Referenced by RemoteOutputSinkGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             qDebug("RemoteOutputSinkGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRate();
             delete message;
         }
         else
         {
             if (handleMessage(*message)) {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool RemoteOutputSinkGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 169 of file remoteoutputgui.cpp.
References blockApplySettings(), displaySettings(), RemoteOutput::MsgConfigureRemoteOutput::getSettings(), RemoteOutput::MsgStartStop::getStartStop(), m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (RemoteOutput::MsgConfigureRemoteOutput::match(message))
     {
         const RemoteOutput::MsgConfigureRemoteOutput& cfg = (RemoteOutput::MsgConfigureRemoteOutput&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (RemoteOutput::MsgStartStop::match(message))
     {
         RemoteOutput::MsgStartStop& notif = (RemoteOutput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
networkManagerFinished
void RemoteOutputSinkGui::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 510 of file remoteoutputgui.cpp.
References analyzeApiReply(), and ui.
Referenced by RemoteOutputSinkGui(), and ~RemoteOutputSinkGui().
 {
     if (reply->error())
     {
         ui->apiAddressLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
         ui->statusText->setText(reply->errorString());
         return;
     }
     QString answer = reply->readAll();
     try
     {
         QByteArray jsonBytes(answer.toStdString().c_str());
         QJsonParseError error;
         QJsonDocument doc = QJsonDocument::fromJson(jsonBytes, &error);
         if (error.error == QJsonParseError::NoError)
         {
             ui->apiAddressLabel->setStyleSheet("QLabel { background-color : green; }");
             ui->statusText->setText(QString("API OK"));
             analyzeApiReply(doc.object());
         }
         else
         {
             ui->apiAddressLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
             QString errorMsg = QString("Reply JSON error: ") + error.errorString() + QString(" at offset ") + QString::number(error.offset);
             ui->statusText->setText(QString("JSON error. See log"));
             qInfo().noquote() << "RemoteOutputSinkGui::networkManagerFinished" << errorMsg;
         }
     }
     catch (const std::exception& ex)
     {
         ui->apiAddressLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
         QString errorMsg = QString("Error parsing request: ") + ex.what();
         ui->statusText->setText("Error parsing request. See log for details");
         qInfo().noquote() << "RemoteOutputSinkGui::networkManagerFinished" << errorMsg;
     }
 }
on_apiAddress_returnPressed
void RemoteOutputSinkGui::on_apiAddress_returnPressed () private slot
Definition at line 353 of file remoteoutputgui.cpp.
References RemoteOutputSettings::m_apiAddress, RemoteOutputSettings::m_apiPort, m_networkManager, m_networkRequest, m_settings, sendSettings(), and ui.
 {
     m_settings.m_apiAddress = ui->apiAddress->text();
     sendSettings();
     QString infoURL = QString("http://%1:%2/sdrangel").arg(m_settings.m_apiAddress).arg(m_settings.m_apiPort);
     m_networkRequest.setUrl(QUrl(infoURL));
     m_networkManager->get(m_networkRequest);
 }
on_apiApplyButton_clicked
void RemoteOutputSinkGui::on_apiApplyButton_clicked (bool checked) private slot
Definition at line 401 of file remoteoutputgui.cpp.
References RemoteOutputSettings::m_apiAddress, RemoteOutputSettings::m_apiPort, m_networkManager, m_networkRequest, m_settings, sendSettings(), and ui.
 {
     (void) checked;
     m_settings.m_apiAddress = ui->apiAddress->text();
     bool apiOk;
     int apiPort = ui->apiPort->text().toInt(&apiOk);
     if((apiOk) && (apiPort >= 1024) && (apiPort < 65535))
     {
         m_settings.m_apiPort = apiPort;
     }
     sendSettings();
     QString infoURL = QString("http://%1:%2/sdrangel").arg(m_settings.m_apiAddress).arg(m_settings.m_apiPort);
     m_networkRequest.setUrl(QUrl(infoURL));
     m_networkManager->get(m_networkRequest);
 }
on_apiPort_returnPressed
void RemoteOutputSinkGui::on_apiPort_returnPressed () private slot
Definition at line 363 of file remoteoutputgui.cpp.
References RemoteOutputSettings::m_apiAddress, RemoteOutputSettings::m_apiPort, m_networkManager, m_networkRequest, m_settings, sendSettings(), and ui.
 {
     bool dataOk;
     int apiPort = ui->apiPort->text().toInt(&dataOk);
     if((!dataOk) || (apiPort < 1024) || (apiPort > 65535)) {
         return;
     } else {
         m_settings.m_apiPort = apiPort;
     }
     sendSettings();
     QString infoURL = QString("http://%1:%2/sdrangel").arg(m_settings.m_apiAddress).arg(m_settings.m_apiPort);
     m_networkRequest.setUrl(QUrl(infoURL));
     m_networkManager->get(m_networkRequest);
 }
on_channelIndex_returnPressed
void RemoteOutputSinkGui::on_channelIndex_returnPressed () private slot
Definition at line 339 of file remoteoutputgui.cpp.
References RemoteOutputSettings::m_channelIndex, m_settings, sendSettings(), and ui.
 {
     bool dataOk;
     int channelIndex = ui->channelIndex->text().toInt(&dataOk);
     if ((!dataOk) || (channelIndex < 0)) {
         return;
     } else {
         m_settings.m_channelIndex = channelIndex;
     }
     sendSettings();
 }
on_dataAddress_returnPressed
void RemoteOutputSinkGui::on_dataAddress_returnPressed () private slot
Definition at line 381 of file remoteoutputgui.cpp.
References RemoteOutputSettings::m_dataAddress, m_settings, sendSettings(), and ui.
 {
     m_settings.m_dataAddress = ui->dataAddress->text();
     sendSettings();
 }
on_dataApplyButton_clicked
void RemoteOutputSinkGui::on_dataApplyButton_clicked (bool checked) private slot
Definition at line 421 of file remoteoutputgui.cpp.
References RemoteOutputSettings::m_dataAddress, RemoteOutputSettings::m_dataPort, m_settings, sendSettings(), and ui.
 {
     (void) checked;
     m_settings.m_dataAddress = ui->dataAddress->text();
     bool dataOk;
     int udpDataPort = ui->dataPort->text().toInt(&dataOk);
     if((dataOk) && (udpDataPort >= 1024) && (udpDataPort < 65535))
     {
         m_settings.m_dataPort = udpDataPort;
     }
     sendSettings();
 }
on_dataPort_returnPressed
void RemoteOutputSinkGui::on_dataPort_returnPressed () private slot
Definition at line 387 of file remoteoutputgui.cpp.
References RemoteOutputSettings::m_dataPort, m_settings, sendSettings(), and ui.
 {
     bool dataOk;
     int dataPort = ui->dataPort->text().toInt(&dataOk);
     if((!dataOk) || (dataPort < 1024) || (dataPort > 65535)) {
         return;
     } else {
         m_settings.m_dataPort = dataPort;
     }
     sendSettings();
 }
on_deviceIndex_returnPressed
void RemoteOutputSinkGui::on_deviceIndex_returnPressed () private slot
Definition at line 325 of file remoteoutputgui.cpp.
References RemoteOutputSettings::m_deviceIndex, m_settings, sendSettings(), and ui.
 {
     bool dataOk;
     int deviceIndex = ui->deviceIndex->text().toInt(&dataOk);
     if ((!dataOk) || (deviceIndex < 0)) {
         return;
     } else {
         m_settings.m_deviceIndex = deviceIndex;
     }
     sendSettings();
 }
on_eventCountsReset_clicked
void RemoteOutputSinkGui::on_eventCountsReset_clicked (bool checked) private slot
Definition at line 446 of file remoteoutputgui.cpp.
References displayEventCounts(), displayEventTimer(), m_countRecovered, m_countUnrecoverable, and m_time.
 {
     (void) checked;
     m_countUnrecoverable = 0;
     m_countRecovered = 0;
     m_time.start();
     displayEventCounts();
     displayEventTimer();
 }
on_nbFECBlocks_valueChanged
void RemoteOutputSinkGui::on_nbFECBlocks_valueChanged (int value) private slot
Definition at line 313 of file remoteoutputgui.cpp.
References arg(), RemoteOutputSettings::m_nbFECBlocks, m_settings, sendSettings(), ui, and updateTxDelayTooltip().
 {
     m_settings.m_nbFECBlocks = value;
     int nbOriginalBlocks = 128;
     int nbFECBlocks = value;
     QString s = QString::number(nbOriginalBlocks + nbFECBlocks, 'f', 0);
     QString s1 = QString::number(nbFECBlocks, 'f', 0);
     ui->nominalNbBlocksText->setText(tr("%1/%2").arg(s).arg(s1));
     updateTxDelayTooltip();
     sendSettings();
 }
on_sampleRate_changed
void RemoteOutputSinkGui::on_sampleRate_changed (quint64 value) private slot
Definition at line 298 of file remoteoutputgui.cpp.
References RemoteOutputSettings::m_sampleRate, m_settings, sendSettings(), and updateTxDelayTooltip().
 {
     m_settings.m_sampleRate = value;
     updateTxDelayTooltip();
     sendSettings();
 }
on_startStop_toggled
void RemoteOutputSinkGui::on_startStop_toggled (bool checked) private slot
Definition at line 437 of file remoteoutputgui.cpp.
References RemoteOutput::MsgStartStop::create(), DeviceSampleSink::getInputMessageQueue(), m_deviceSampleSink, m_doApplySettings, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         RemoteOutput::MsgStartStop *message = RemoteOutput::MsgStartStop::create(checked);
         m_deviceSampleSink->getInputMessageQueue()->push(message);
     }
 }
on_txDelay_valueChanged
void RemoteOutputSinkGui::on_txDelay_valueChanged (int value) private slot
Definition at line 305 of file remoteoutputgui.cpp.
References arg(), m_settings, RemoteOutputSettings::m_txDelay, sendSettings(), ui, and updateTxDelayTooltip().
 {
     m_settings.m_txDelay = value / 100.0;
     ui->txDelayText->setText(tr("%1").arg(value));
     updateTxDelayTooltip();
     sendSettings();
 }
openDeviceSettingsDialog
void RemoteOutputSinkGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 635 of file remoteoutputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), RemoteOutputSettings::m_reverseAPIAddress, RemoteOutputSettings::m_reverseAPIDeviceIndex, RemoteOutputSettings::m_reverseAPIPort, m_settings, RemoteOutputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by RemoteOutputSinkGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void RemoteOutputSinkGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 136 of file remoteoutputgui.cpp.
References blockApplySettings(), displaySettings(), m_settings, RemoteOutputSettings::resetToDefaults(), and sendSettings().
 {
     blockApplySettings(true);
     m_settings.resetToDefaults();
     displaySettings();
     blockApplySettings(false);
     sendSettings();
 }
sendControl()
void RemoteOutputSinkGui::sendControl (bool force = false) private
sendSettings()
void RemoteOutputSinkGui::sendSettings () private
Definition at line 253 of file remoteoutputgui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_apiAddress_returnPressed(), on_apiApplyButton_clicked(), on_apiPort_returnPressed(), on_channelIndex_returnPressed(), on_dataAddress_returnPressed(), on_dataApplyButton_clicked(), on_dataPort_returnPressed(), on_deviceIndex_returnPressed(), on_nbFECBlocks_valueChanged(), on_sampleRate_changed(), on_txDelay_valueChanged(), openDeviceSettingsDialog(), RemoteOutputSinkGui(), and resetToDefaults().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray RemoteOutputSinkGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 145 of file remoteoutputgui.cpp.
References m_settings, and RemoteOutputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
virtual void RemoteOutputSinkGui::setCenterFrequency (qint64 centerFrequency) inline virtual
Implements PluginInstanceGUI.
Definition at line 85 of file remoteoutputgui.h.
 { (void) centerFrequency; }
setName()
void RemoteOutputSinkGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 126 of file remoteoutputgui.cpp.
 {
     setObjectName(name);
 }
tick
void RemoteOutputSinkGui::tick () private slot
Definition at line 490 of file remoteoutputgui.cpp.
References displayEventTimer(), RemoteOutputSettings::m_apiAddress, RemoteOutputSettings::m_apiPort, RemoteOutputSettings::m_channelIndex, RemoteOutputSettings::m_deviceIndex, m_networkManager, m_networkRequest, m_settings, and m_tickCount.
Referenced by RemoteOutputSinkGui().
 {
     if (++m_tickCount == 20) // once per second
     {
         QString reportURL;
         reportURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/report")
                 .arg(m_settings.m_apiAddress)
                 .arg(m_settings.m_apiPort)
                 .arg(m_settings.m_deviceIndex)
                 .arg(m_settings.m_channelIndex);
         m_networkRequest.setUrl(QUrl(reportURL));
         m_networkManager->get(m_networkRequest);
         displayEventTimer();
         m_tickCount = 0;
     }
 }
updateHardware
void RemoteOutputSinkGui::updateHardware () private slot
Definition at line 260 of file remoteoutputgui.cpp.
References RemoteOutput::MsgConfigureRemoteOutput::create(), DeviceSampleSink::getInputMessageQueue(), m_deviceSampleSink, m_forceSettings, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by RemoteOutputSinkGui().
 {
     qDebug() << "RemoteOutputSinkGui::updateHardware";
     RemoteOutput::MsgConfigureRemoteOutput* message = RemoteOutput::MsgConfigureRemoteOutput::create(m_settings, m_forceSettings);
     m_deviceSampleSink->getInputMessageQueue()->push(message);
     m_forceSettings = false;
     m_updateTimer.stop();
 }
updateSampleRate()
void RemoteOutputSinkGui::updateSampleRate () private
Definition at line 218 of file remoteoutputgui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceUISet, m_sampleRate, GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     ui->deviceRateText->setText(tr("%1k").arg((float)(m_sampleRate) / 1000));
 }
updateStatus
void RemoteOutputSinkGui::updateStatus () private slot
Definition at line 269 of file remoteoutputgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by RemoteOutputSinkGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
updateTxDelayTooltip()
void RemoteOutputSinkGui::updateTxDelayTooltip () private
Definition at line 224 of file remoteoutputgui.cpp.
Referenced by on_nbFECBlocks_valueChanged(), on_sampleRate_changed(), and on_txDelay_valueChanged().
 {
     int samplesPerBlock = RemoteNbBytesPerBlock / (SDR_RX_SAMP_SZ <= 16 ? 4 : 8);
     double delay = ((127*samplesPerBlock*m_settings.m_txDelay) / m_settings.m_sampleRate)/(128 + m_settings.m_nbFECBlocks);
     ui->txDelayText->setToolTip(tr("%1 us").arg(QString::number(delay*1e6, 'f', 0)));
 }
Member Data Documentation
m_controlSettings
RemoteOutputSettings RemoteOutputSinkGui::m_controlSettings private
settings last sent to device via control port
Definition at line 96 of file remoteoutputgui.h.
m_countRecovered
uint32_t RemoteOutputSinkGui::m_countRecovered private
Definition at line 110 of file remoteoutputgui.h.
Referenced by analyzeApiReply(), displayEventCounts(), on_eventCountsReset_clicked(), and RemoteOutputSinkGui().
m_countUnrecoverable
uint32_t RemoteOutputSinkGui::m_countUnrecoverable private
Definition at line 109 of file remoteoutputgui.h.
Referenced by analyzeApiReply(), displayEventCounts(), on_eventCountsReset_clicked(), and RemoteOutputSinkGui().
m_deviceCenterFrequency
quint64 RemoteOutputSinkGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 101 of file remoteoutputgui.h.
Referenced by analyzeApiReply(), displaySettings(), and RemoteOutputSinkGui().
m_deviceSampleSink
DeviceSampleSink* RemoteOutputSinkGui::m_deviceSampleSink private
Definition at line 99 of file remoteoutputgui.h.
Referenced by on_startStop_toggled(), RemoteOutputSinkGui(), and updateHardware().
m_deviceUISet
DeviceUISet* RemoteOutputSinkGui::m_deviceUISet private
Definition at line 94 of file remoteoutputgui.h.
Referenced by analyzeApiReply(), RemoteOutputSinkGui(), updateSampleRate(), and updateStatus().
m_doApplySettings
bool RemoteOutputSinkGui::m_doApplySettings private
Definition at line 106 of file remoteoutputgui.h.
Referenced by blockApplySettings(), and on_startStop_toggled().
m_forceSettings
bool RemoteOutputSinkGui::m_forceSettings private
Definition at line 107 of file remoteoutputgui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue RemoteOutputSinkGui::m_inputMessageQueue private
Definition at line 122 of file remoteoutputgui.h.
Referenced by handleInputMessages(), and RemoteOutputSinkGui().
m_lastCountRecovered
uint32_t RemoteOutputSinkGui::m_lastCountRecovered private
Definition at line 112 of file remoteoutputgui.h.
Referenced by analyzeApiReply(), and RemoteOutputSinkGui().
m_lastCountUnrecoverable
uint32_t RemoteOutputSinkGui::m_lastCountUnrecoverable private
Definition at line 111 of file remoteoutputgui.h.
Referenced by analyzeApiReply(), and RemoteOutputSinkGui().
m_lastEngineState
int RemoteOutputSinkGui::m_lastEngineState private
Definition at line 105 of file remoteoutputgui.h.
Referenced by updateStatus().
m_lastSampleCount
uint32_t RemoteOutputSinkGui::m_lastSampleCount private
Definition at line 113 of file remoteoutputgui.h.
Referenced by analyzeApiReply(), and RemoteOutputSinkGui().
m_lastTimestampUs
uint64_t RemoteOutputSinkGui::m_lastTimestampUs private
Definition at line 114 of file remoteoutputgui.h.
Referenced by analyzeApiReply().
m_nbSinceLastFlowCheck
std::size_t RemoteOutputSinkGui::m_nbSinceLastFlowCheck private
Definition at line 104 of file remoteoutputgui.h.
m_networkManager
QNetworkAccessManager* RemoteOutputSinkGui::m_networkManager private
Definition at line 124 of file remoteoutputgui.h.
Referenced by on_apiAddress_returnPressed(), on_apiApplyButton_clicked(), on_apiPort_returnPressed(), RemoteOutputSinkGui(), tick(), and ~RemoteOutputSinkGui().
m_networkRequest
QNetworkRequest RemoteOutputSinkGui::m_networkRequest private
Definition at line 125 of file remoteoutputgui.h.
Referenced by on_apiAddress_returnPressed(), on_apiApplyButton_clicked(), on_apiPort_returnPressed(), and tick().
m_paletteGreenText
QPalette RemoteOutputSinkGui::m_paletteGreenText private
Definition at line 118 of file remoteoutputgui.h.
Referenced by RemoteOutputSinkGui().
m_paletteRedText
QPalette RemoteOutputSinkGui::m_paletteRedText private
Definition at line 119 of file remoteoutputgui.h.
Referenced by RemoteOutputSinkGui().
m_paletteWhiteText
QPalette RemoteOutputSinkGui::m_paletteWhiteText private
Definition at line 120 of file remoteoutputgui.h.
Referenced by RemoteOutputSinkGui().
m_resetCounts
bool RemoteOutputSinkGui::m_resetCounts private
Definition at line 115 of file remoteoutputgui.h.
Referenced by analyzeApiReply(), and RemoteOutputSinkGui().
m_sampleRate
int RemoteOutputSinkGui::m_sampleRate private
Definition at line 100 of file remoteoutputgui.h.
Referenced by handleInputMessages(), and updateSampleRate().
m_samplesCount
int RemoteOutputSinkGui::m_samplesCount private
Definition at line 102 of file remoteoutputgui.h.
m_settings
RemoteOutputSettings RemoteOutputSinkGui::m_settings private
current settings
Definition at line 95 of file remoteoutputgui.h.
Referenced by deserialize(), displaySettings(), handleMessage(), on_apiAddress_returnPressed(), on_apiApplyButton_clicked(), on_apiPort_returnPressed(), on_channelIndex_returnPressed(), on_dataAddress_returnPressed(), on_dataApplyButton_clicked(), on_dataPort_returnPressed(), on_deviceIndex_returnPressed(), on_nbFECBlocks_valueChanged(), on_sampleRate_changed(), on_txDelay_valueChanged(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), tick(), and updateHardware().
m_statusTimer
QTimer RemoteOutputSinkGui::m_statusTimer private
Definition at line 98 of file remoteoutputgui.h.
Referenced by RemoteOutputSinkGui().
m_tickCount
uint32_t RemoteOutputSinkGui::m_tickCount private
Definition at line 103 of file remoteoutputgui.h.
Referenced by tick().
m_time
QTime RemoteOutputSinkGui::m_time private
Definition at line 116 of file remoteoutputgui.h.
Referenced by displayEventTimer(), on_eventCountsReset_clicked(), and RemoteOutputSinkGui().
m_updateTimer
QTimer RemoteOutputSinkGui::m_updateTimer private
Definition at line 97 of file remoteoutputgui.h.
Referenced by RemoteOutputSinkGui(), sendSettings(), and updateHardware().
ui
Ui::RemoteOutputGui* RemoteOutputSinkGui::ui private
Definition at line 92 of file remoteoutputgui.h.
Referenced by analyzeApiReply(), displayEventCounts(), displayEventStatus(), displayEventTimer(), displaySettings(), handleMessage(), networkManagerFinished(), on_apiAddress_returnPressed(), on_apiApplyButton_clicked(), on_apiPort_returnPressed(), on_channelIndex_returnPressed(), on_dataAddress_returnPressed(), on_dataApplyButton_clicked(), on_dataPort_returnPressed(), on_deviceIndex_returnPressed(), on_nbFECBlocks_valueChanged(), on_txDelay_valueChanged(), RemoteOutputSinkGui(), updateSampleRate(), updateStatus(), and ~RemoteOutputSinkGui().
The documentation for this class was generated from the following files:
plugins/samplesink/remoteoutput/remoteoutputgui.h
plugins/samplesink/remoteoutput/remoteoutputgui.cpp