SDRAngel: BladeRF2InputGui Class Reference
BladeRF2InputGui Class Reference
#include <bladerf2inputgui.h>
Public Member Functions
BladeRF2InputGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~BladeRF2InputGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_centerFrequency_changed (quint64 value)
void on_LOppm_valueChanged (int value)
void on_sampleRate_changed (quint64 value)
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_biasTee_toggled (bool checked)
void on_bandwidth_changed (quint64 value)
void on_decim_currentIndexChanged (int index)
void on_fcPos_currentIndexChanged (int index)
void on_gainMode_currentIndexChanged (int index)
void on_gain_valueChanged (int value)
void on_transverter_clicked ()
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void on_sampleRateMode_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void displaySettings ()
void displaySampleRate ()
void displayFcTooltip ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void updateFrequencyLimits ()
void setCenterFrequencySetting (uint64_t kHzValue)
void blockApplySettings (bool block)
Private Attributes
Ui::Bladerf2InputGui * ui
DeviceUISet * m_deviceUISet
bool m_forceSettings
bool m_doApplySettings
BladeRF2InputSettings m_settings
bool m_sampleRateMode
true: device, false: base band sample rate update mode
QTimer m_updateTimer
QTimer m_statusTimer
std::vector< int > m_gains
BladeRF2Input * m_sampleSource
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 35 of file bladerf2inputgui.h.
Constructor & Destructor Documentation
BladeRF2InputGui()
BladeRF2InputGui::BladeRF2InputGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 35 of file bladerf2inputgui.cpp.
References displaySettings(), BladeRF2Input::getBandwidthRange(), BladeRF2Input::getFrequencyRange(), BladeRF2Input::getGainModes(), BladeRF2Input::getGlobalGainRange(), BladeRF2Input::getSampleRateRange(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, ColorMapper::GrayYellow, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_sampleSource, m_statusTimer, m_updateTimer, leansdr::max(), leansdr::min(), openDeviceSettingsDialog(), sendSettings(), BladeRF2Input::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                                             :
     QWidget(parent),
     ui(new Ui::Bladerf2InputGui),
     m_deviceUISet(deviceUISet),
     m_forceSettings(true),
     m_doApplySettings(true),
     m_settings(),
     m_sampleRateMode(true),
     m_sampleSource(0),
     m_sampleRate(0),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     m_sampleSource = (BladeRF2Input*) m_deviceUISet->m_deviceAPI->getSampleSource();
     int max, min, step;
     uint64_t f_min, f_max;
     ui->setupUi(this);
     m_sampleSource->getFrequencyRange(f_min, f_max, step);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, f_min/1000, f_max/1000);
     m_sampleSource->getSampleRateRange(min, max, step);
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(8, min, max);
     m_sampleSource->getBandwidthRange(min, max, step);
     ui->bandwidth->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     ui->bandwidth->setValueRange(5, min/1000, max/1000);
     const std::vector<BladeRF2Input::GainMode>& modes = m_sampleSource->getGainModes();
     std::vector<BladeRF2Input::GainMode>::const_iterator it = modes.begin();
     ui->gainMode->blockSignals(true);
     for (; it != modes.end(); ++it) {
         ui->gainMode->addItem(it->m_name);
     }
     ui->gainMode->blockSignals(false);
     m_sampleSource->getGlobalGainRange(min, max, step);
     ui->gain->setMinimum(min);
     ui->gain->setMaximum(max);
     ui->gain->setPageStep(step);
     ui->gain->setSingleStep(step);
     ui->label_decim->setText(QString::fromUtf8("D\u2193"));
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
     sendSettings();
 }
~BladeRF2InputGui()
BladeRF2InputGui::~BladeRF2InputGui () virtual
Definition at line 99 of file bladerf2inputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void BladeRF2InputGui::blockApplySettings (bool block) private
Definition at line 500 of file bladerf2inputgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool BladeRF2InputGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 143 of file bladerf2inputgui.cpp.
References BladeRF2InputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void BladeRF2InputGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 104 of file bladerf2inputgui.cpp.
 {
     delete this;
 }
displayFcTooltip()
void BladeRF2InputGui::displayFcTooltip () private
Definition at line 295 of file bladerf2inputgui.cpp.
References arg(), DeviceSampleSource::calculateFrequencyShift(), BladeRF2InputSettings::m_devSampleRate, BladeRF2InputSettings::m_fcPos, BladeRF2InputSettings::m_log2Decim, m_settings, and ui.
Referenced by displaySampleRate(), on_fcPos_currentIndexChanged(), and on_sampleRate_changed().
 {
     int32_t fShift = DeviceSampleSource::calculateFrequencyShift(
         m_settings.m_log2Decim,
         (DeviceSampleSource::fcPos_t) m_settings.m_fcPos,
         m_settings.m_devSampleRate,
         DeviceSampleSource::FrequencyShiftScheme::FSHIFT_STD
     );
     ui->fcPos->setToolTip(tr("Relative position of device center frequency: %1 kHz").arg(QString::number(fShift / 1000.0f, 'g', 5)));
 }
displaySampleRate()
void BladeRF2InputGui::displaySampleRate () private
Definition at line 260 of file bladerf2inputgui.cpp.
References arg(), displayFcTooltip(), BladeRF2Input::getSampleRateRange(), BladeRF2InputSettings::m_devSampleRate, BladeRF2InputSettings::m_log2Decim, m_sampleRateMode, m_sampleSource, m_settings, leansdr::max(), leansdr::min(), and ui.
Referenced by displaySettings(), on_decim_currentIndexChanged(), on_sampleRateMode_toggled(), and updateSampleRateAndFrequency().
 {
     int max, min, step;
     m_sampleSource->getSampleRateRange(min, max, step);
     ui->sampleRate->blockSignals(true);
     displayFcTooltip();
     if (m_sampleRateMode)
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(60,60,60); }");
         ui->sampleRateMode->setText("SR");
         // BladeRF can go as low as 80 kS/s but because of buffering in practice experience is not good below 330 kS/s
         ui->sampleRate->setValueRange(8, min, max);
         ui->sampleRate->setValue(m_settings.m_devSampleRate);
         ui->sampleRate->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setToolTip("Baseband sample rate (S/s)");
         uint32_t basebandSampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Decim);
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(basebandSampleRate / 1000.0f, 'g', 5)));
     }
     else
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(50,50,50); }");
         ui->sampleRateMode->setText("BB");
         // BladeRF can go as low as 80 kS/s but because of buffering in practice experience is not good below 330 kS/s
         ui->sampleRate->setValueRange(8, min/(1<<m_settings.m_log2Decim), max/(1<<m_settings.m_log2Decim));
         ui->sampleRate->setValue(m_settings.m_devSampleRate/(1<<m_settings.m_log2Decim));
         ui->sampleRate->setToolTip("Baseband sample rate (S/s)");
         ui->deviceRateText->setToolTip("Device to host sample rate (S/s)");
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_settings.m_devSampleRate / 1000.0f, 'g', 5)));
     }
     ui->sampleRate->blockSignals(false);
 }
displaySettings()
void BladeRF2InputGui::displaySettings () private
Definition at line 306 of file bladerf2inputgui.cpp.
References arg(), blockApplySettings(), displaySampleRate(), BladeRF2InputSettings::m_bandwidth, BladeRF2InputSettings::m_biasTee, BladeRF2InputSettings::m_centerFrequency, BladeRF2InputSettings::m_dcBlock, BladeRF2InputSettings::m_fcPos, BladeRF2InputSettings::m_gainMode, BladeRF2InputSettings::m_globalGain, BladeRF2InputSettings::m_iqCorrection, BladeRF2InputSettings::m_log2Decim, BladeRF2InputSettings::m_LOppmTenths, m_settings, BladeRF2InputSettings::m_transverterDeltaFrequency, BladeRF2InputSettings::m_transverterMode, and ui.
Referenced by BladeRF2InputGui(), deserialize(), handleMessage(), resetToDefaults(), and setCenterFrequency().
 {
     blockApplySettings(true);
     ui->transverter->setDeltaFrequency(m_settings.m_transverterDeltaFrequency);
     ui->transverter->setDeltaFrequencyActive(m_settings.m_transverterMode);
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     ui->LOppm->setValue(m_settings.m_LOppmTenths);
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     displaySampleRate();
     ui->bandwidth->setValue(m_settings.m_bandwidth / 1000);
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqCorrection);
     ui->biasTee->setChecked(m_settings.m_biasTee);
     ui->decim->setCurrentIndex(m_settings.m_log2Decim);
     ui->fcPos->setCurrentIndex((int) m_settings.m_fcPos);
     ui->gainMode->setCurrentIndex(m_settings.m_gainMode);
     ui->gainText->setText(tr("%1 dB").arg(m_settings.m_globalGain));
     ui->gain->setValue(m_settings.m_globalGain);
     if (m_settings.m_gainMode == BLADERF_GAIN_MANUAL) {
         ui->gain->setEnabled(true);
     } else {
         ui->gain->setEnabled(false);
     }
     blockApplySettings(false);
 }
getCenterFrequency()
qint64 BladeRF2InputGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 126 of file bladerf2inputgui.cpp.
References BladeRF2InputSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* BladeRF2InputGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 51 of file bladerf2inputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString BladeRF2InputGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 114 of file bladerf2inputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void BladeRF2InputGui::handleInputMessages () private slot
Definition at line 225 of file bladerf2inputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by BladeRF2InputGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("BladeRF2InputGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("BladeRF2InputGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool BladeRF2InputGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 182 of file bladerf2inputgui.cpp.
References blockApplySettings(), displaySettings(), BladeRF2Input::getGlobalGainRange(), BladeRF2Input::MsgReportGainRange::getMax(), BladeRF2Input::MsgReportGainRange::getMin(), BladeRF2Input::MsgConfigureBladeRF2::getSettings(), BladeRF2Input::MsgStartStop::getStartStop(), BladeRF2Input::MsgReportGainRange::getStep(), m_sampleSource, m_settings, Message::match(), leansdr::max(), leansdr::min(), and ui.
Referenced by handleInputMessages().
 {
     if (BladeRF2Input::MsgConfigureBladeRF2::match(message))
     {
         const BladeRF2Input::MsgConfigureBladeRF2& cfg = (BladeRF2Input::MsgConfigureBladeRF2&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         int min, max, step;
         m_sampleSource->getGlobalGainRange(min, max, step);
         ui->gain->setMinimum(min);
         ui->gain->setMaximum(max);
         ui->gain->setPageStep(step);
         ui->gain->setSingleStep(step);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (BladeRF2Input::MsgReportGainRange::match(message))
     {
         const BladeRF2Input::MsgReportGainRange& cfg = (BladeRF2Input::MsgReportGainRange&) message;
         ui->gain->setMinimum(cfg.getMin());
         ui->gain->setMaximum(cfg.getMax());
         ui->gain->setSingleStep(cfg.getStep());
         ui->gain->setPageStep(cfg.getStep());
         return true;
     }
     else if (BladeRF2Input::MsgStartStop::match(message))
     {
         BladeRF2Input::MsgStartStop& notif = (BladeRF2Input::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_bandwidth_changed
void BladeRF2InputGui::on_bandwidth_changed (quint64 value) private slot
Definition at line 388 of file bladerf2inputgui.cpp.
References BladeRF2InputSettings::m_bandwidth, m_settings, and sendSettings().
 {
     m_settings.m_bandwidth = value * 1000;
     sendSettings();
 }
on_biasTee_toggled
void BladeRF2InputGui::on_biasTee_toggled (bool checked) private slot
Definition at line 382 of file bladerf2inputgui.cpp.
References BladeRF2InputSettings::m_biasTee, m_settings, and sendSettings().
 {
     m_settings.m_biasTee = checked;
     sendSettings();
 }
on_centerFrequency_changed
void BladeRF2InputGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 345 of file bladerf2inputgui.cpp.
References BladeRF2InputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_dcOffset_toggled
void BladeRF2InputGui::on_dcOffset_toggled (bool checked) private slot
Definition at line 370 of file bladerf2inputgui.cpp.
References BladeRF2InputSettings::m_dcBlock, m_settings, and sendSettings().
 {
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_decim_currentIndexChanged
void BladeRF2InputGui::on_decim_currentIndexChanged (int index) private slot
Definition at line 394 of file bladerf2inputgui.cpp.
References displaySampleRate(), BladeRF2InputSettings::m_devSampleRate, BladeRF2InputSettings::m_log2Decim, m_sampleRateMode, m_settings, sendSettings(), and ui.
 {
     if ((index <0) || (index > 6)) {
         return;
     }
     m_settings.m_log2Decim = index;
     displaySampleRate();
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     } else {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew() * (1 << m_settings.m_log2Decim);
     }
     sendSettings();
 }
on_fcPos_currentIndexChanged
void BladeRF2InputGui::on_fcPos_currentIndexChanged (int index) private slot
Definition at line 412 of file bladerf2inputgui.cpp.
References displayFcTooltip(), BladeRF2InputSettings::m_fcPos, m_settings, and sendSettings().
 {
     m_settings.m_fcPos = (BladeRF2InputSettings::fcPos_t) (index < 0 ? 0 : index > 2 ? 2 : index);
     displayFcTooltip();
     sendSettings();
 }
on_gain_valueChanged
void BladeRF2InputGui::on_gain_valueChanged (int value) private slot
Definition at line 444 of file bladerf2inputgui.cpp.
References arg(), BladeRF2InputSettings::m_globalGain, m_settings, sendSettings(), and ui.
 {
     ui->gainText->setText(tr("%1 dB").arg(value));
     m_settings.m_globalGain = value;
     sendSettings();
 }
on_gainMode_currentIndexChanged
void BladeRF2InputGui::on_gainMode_currentIndexChanged (int index) private slot
Definition at line 419 of file bladerf2inputgui.cpp.
References BladeRF2Input::getGainModes(), BladeRF2InputSettings::m_gainMode, BladeRF2InputSettings::m_globalGain, m_sampleSource, m_settings, BladeRF2Input::GainMode::m_value, sendSettings(), and ui.
 {
     const std::vector<BladeRF2Input::GainMode>& modes = m_sampleSource->getGainModes();
     unsigned int uindex = index < 0 ? 0 : (unsigned int) index;
     if (uindex < modes.size())
     {
         BladeRF2Input::GainMode mode = modes[index];
         if (m_settings.m_gainMode != mode.m_value)
         {
             if (mode.m_value == BLADERF_GAIN_MANUAL)
             {
                 m_settings.m_globalGain = ui->gain->value();
                 ui->gain->setEnabled(true);
             } else {
                 ui->gain->setEnabled(false);
             }
         }
         m_settings.m_gainMode = mode.m_value;
         sendSettings();
     }
 }
on_iqImbalance_toggled
void BladeRF2InputGui::on_iqImbalance_toggled (bool checked) private slot
Definition at line 376 of file bladerf2inputgui.cpp.
References BladeRF2InputSettings::m_iqCorrection, m_settings, and sendSettings().
 {
     m_settings.m_iqCorrection = checked;
     sendSettings();
 }
on_LOppm_valueChanged
void BladeRF2InputGui::on_LOppm_valueChanged (int value) private slot
Definition at line 351 of file bladerf2inputgui.cpp.
References arg(), BladeRF2InputSettings::m_LOppmTenths, m_settings, sendSettings(), and ui.
 {
     ui->LOppmText->setText(QString("%1").arg(QString::number(value/10.0, 'f', 1)));
     m_settings.m_LOppmTenths = value;
     sendSettings();
 }
on_record_toggled
void BladeRF2InputGui::on_record_toggled (bool checked) private slot
Definition at line 470 of file bladerf2inputgui.cpp.
References BladeRF2Input::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     BladeRF2Input::MsgFileRecord* message = BladeRF2Input::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_sampleRate_changed
void BladeRF2InputGui::on_sampleRate_changed (quint64 value) private slot
Definition at line 358 of file bladerf2inputgui.cpp.
References displayFcTooltip(), BladeRF2InputSettings::m_devSampleRate, BladeRF2InputSettings::m_log2Decim, m_sampleRateMode, m_settings, and sendSettings().
 {
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = value;
     } else {
         m_settings.m_devSampleRate = value * (1 << m_settings.m_log2Decim);
     }
     displayFcTooltip();
     sendSettings();
 }
on_sampleRateMode_toggled
void BladeRF2InputGui::on_sampleRateMode_toggled (bool checked) private slot
Definition at line 482 of file bladerf2inputgui.cpp.
References displaySampleRate(), and m_sampleRateMode.
 {
     m_sampleRateMode = checked;
     displaySampleRate();
 }
on_startStop_toggled
void BladeRF2InputGui::on_startStop_toggled (bool checked) private slot
Definition at line 461 of file bladerf2inputgui.cpp.
References BladeRF2Input::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         BladeRF2Input::MsgStartStop *message = BladeRF2Input::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
on_transverter_clicked
void BladeRF2InputGui::on_transverter_clicked () private slot
Definition at line 451 of file bladerf2inputgui.cpp.
References m_settings, BladeRF2InputSettings::m_transverterDeltaFrequency, BladeRF2InputSettings::m_transverterMode, sendSettings(), setCenterFrequencySetting(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("BladeRF2InputGui::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     setCenterFrequencySetting(ui->centerFrequency->getValueNew());
     sendSettings();
 }
openDeviceSettingsDialog
void BladeRF2InputGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 534 of file bladerf2inputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), BladeRF2InputSettings::m_reverseAPIAddress, BladeRF2InputSettings::m_reverseAPIDeviceIndex, BladeRF2InputSettings::m_reverseAPIPort, m_settings, BladeRF2InputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by BladeRF2InputGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void BladeRF2InputGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 119 of file bladerf2inputgui.cpp.
References displaySettings(), m_settings, BladeRF2InputSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void BladeRF2InputGui::sendSettings () private
Definition at line 339 of file bladerf2inputgui.cpp.
References m_updateTimer.
Referenced by BladeRF2InputGui(), deserialize(), on_bandwidth_changed(), on_biasTee_toggled(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_gain_valueChanged(), on_gainMode_currentIndexChanged(), on_iqImbalance_toggled(), on_LOppm_valueChanged(), on_sampleRate_changed(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray BladeRF2InputGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 138 of file bladerf2inputgui.cpp.
References m_settings, and BladeRF2InputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void BladeRF2InputGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 131 of file bladerf2inputgui.cpp.
References displaySettings(), BladeRF2InputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setCenterFrequencySetting()
void BladeRF2InputGui::setCenterFrequencySetting (uint64_t kHzValue) private
Definition at line 174 of file bladerf2inputgui.cpp.
References arg(), BladeRF2InputSettings::m_centerFrequency, m_settings, and ui.
Referenced by on_transverter_clicked().
 {
     int64_t centerFrequency = kHzValue*1000;
     m_settings.m_centerFrequency = centerFrequency < 0 ? 0 : (uint64_t) centerFrequency;
     ui->centerFrequency->setToolTip(QString("Main center frequency in kHz (LO: %1 kHz)").arg(centerFrequency/1000));
 }
setName()
void BladeRF2InputGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 109 of file bladerf2inputgui.cpp.
 {
     setObjectName(name);
 }
updateFrequencyLimits()
void BladeRF2InputGui::updateFrequencyLimits () private
Definition at line 156 of file bladerf2inputgui.cpp.
References BladeRF2Input::getFrequencyRange(), m_sampleSource, m_settings, BladeRF2InputSettings::m_transverterDeltaFrequency, BladeRF2InputSettings::m_transverterMode, and ui.
Referenced by on_transverter_clicked().
 {
     // values in kHz
     uint64_t f_min, f_max;
     int step;
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     m_sampleSource->getFrequencyRange(f_min, f_max, step);
     qint64 minLimit = f_min/1000 + deltaFrequency;
     qint64 maxLimit = f_max/1000 + deltaFrequency;
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("BladeRF2OutputGui::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void BladeRF2InputGui::updateHardware () private slot
Definition at line 488 of file bladerf2inputgui.cpp.
References BladeRF2Input::MsgConfigureBladeRF2::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by BladeRF2InputGui().
 {
     if (m_doApplySettings)
     {
         qDebug() << "BladeRF2InputGui::updateHardware";
         BladeRF2Input::MsgConfigureBladeRF2* message = BladeRF2Input::MsgConfigureBladeRF2::create(m_settings, m_forceSettings);
         m_sampleSource->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void BladeRF2InputGui::updateSampleRateAndFrequency () private
Definition at line 253 of file bladerf2inputgui.cpp.
References displaySampleRate(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), and GLSpectrum::setSampleRate().
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     displaySampleRate();
 }
updateStatus
void BladeRF2InputGui::updateStatus () private slot
Definition at line 505 of file bladerf2inputgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by BladeRF2InputGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 BladeRF2InputGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 67 of file bladerf2inputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* BladeRF2InputGui::m_deviceUISet private
Definition at line 57 of file bladerf2inputgui.h.
Referenced by BladeRF2InputGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool BladeRF2InputGui::m_doApplySettings private
Definition at line 59 of file bladerf2inputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_forceSettings
bool BladeRF2InputGui::m_forceSettings private
Definition at line 58 of file bladerf2inputgui.h.
Referenced by deserialize(), and updateHardware().
m_gains
std::vector<int> BladeRF2InputGui::m_gains private
Definition at line 64 of file bladerf2inputgui.h.
m_inputMessageQueue
MessageQueue BladeRF2InputGui::m_inputMessageQueue private
Definition at line 69 of file bladerf2inputgui.h.
Referenced by BladeRF2InputGui(), and handleInputMessages().
m_lastEngineState
int BladeRF2InputGui::m_lastEngineState private
Definition at line 68 of file bladerf2inputgui.h.
Referenced by updateStatus().
m_sampleRate
int BladeRF2InputGui::m_sampleRate private
Definition at line 66 of file bladerf2inputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateMode
bool BladeRF2InputGui::m_sampleRateMode private
true: device, false: base band sample rate update mode
Definition at line 61 of file bladerf2inputgui.h.
Referenced by displaySampleRate(), on_decim_currentIndexChanged(), on_sampleRate_changed(), and on_sampleRateMode_toggled().
m_sampleSource
BladeRF2Input* BladeRF2InputGui::m_sampleSource private
Definition at line 65 of file bladerf2inputgui.h.
Referenced by BladeRF2InputGui(), displaySampleRate(), handleMessage(), on_gainMode_currentIndexChanged(), on_record_toggled(), on_startStop_toggled(), updateFrequencyLimits(), and updateHardware().
m_settings
BladeRF2InputSettings BladeRF2InputGui::m_settings private
Definition at line 60 of file bladerf2inputgui.h.
Referenced by deserialize(), displayFcTooltip(), displaySampleRate(), displaySettings(), getCenterFrequency(), handleMessage(), on_bandwidth_changed(), on_biasTee_toggled(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_gain_valueChanged(), on_gainMode_currentIndexChanged(), on_iqImbalance_toggled(), on_LOppm_valueChanged(), on_sampleRate_changed(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), setCenterFrequencySetting(), updateFrequencyLimits(), and updateHardware().
m_statusTimer
QTimer BladeRF2InputGui::m_statusTimer private
Definition at line 63 of file bladerf2inputgui.h.
Referenced by BladeRF2InputGui().
m_updateTimer
QTimer BladeRF2InputGui::m_updateTimer private
Definition at line 62 of file bladerf2inputgui.h.
Referenced by BladeRF2InputGui(), sendSettings(), and updateHardware().
ui
Ui::Bladerf2InputGui* BladeRF2InputGui::ui private
Definition at line 55 of file bladerf2inputgui.h.
Referenced by BladeRF2InputGui(), displayFcTooltip(), displaySampleRate(), displaySettings(), handleMessage(), on_decim_currentIndexChanged(), on_gain_valueChanged(), on_gainMode_currentIndexChanged(), on_LOppm_valueChanged(), on_record_toggled(), on_transverter_clicked(), setCenterFrequencySetting(), updateFrequencyLimits(), updateStatus(), and ~BladeRF2InputGui().
The documentation for this class was generated from the following files:
plugins/samplesource/bladerf2input/bladerf2inputgui.h
plugins/samplesource/bladerf2input/bladerf2inputgui.cpp