SDRAngel: PluginInstanceGUI Class Reference
PluginInstanceGUI Class Reference abstract
#include <plugininstancegui.h>
Public Member Functions
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
virtual void destroy ()=0
virtual void setName (const QString &name)=0
virtual QString getName () const =0
virtual void resetToDefaults ()=0
virtual qint64 getCenterFrequency () const =0
virtual void setCenterFrequency (qint64 centerFrequency)=0
virtual QByteArray serialize () const =0
virtual bool deserialize (const QByteArray &data)=0
virtual MessageQueue * getInputMessageQueue ()=0
virtual bool handleMessage (const Message &message)=0
Detailed Description
Definition at line 13 of file plugininstancegui.h.
Constructor & Destructor Documentation
PluginInstanceGUI()
PluginInstanceGUI::PluginInstanceGUI () inline
Definition at line 15 of file plugininstancegui.h.
 { };
~PluginInstanceGUI()
virtual PluginInstanceGUI::~PluginInstanceGUI () inline virtual
Definition at line 16 of file plugininstancegui.h.
 { };
Member Function Documentation
deserialize()
virtual bool PluginInstanceGUI::deserialize (const QByteArray & data) pure virtual
Implemented in RemoteOutputSinkGui, HackRFOutputGui, HackRFInputGui, DSDDemodGUI, SoapySDROutputGui, DATVDemodGUI, SoapySDRInputGui, ChannelAnalyzerGUI, FreeDVDemodGUI, LocalSinkGUI, RemoteSinkGUI, UDPSinkGUI, LocalSourceGUI, FreeDVModGUI, SSBModGUI, ATVDemodGUI, BFMDemodGUI, FreqTrackerGUI, AMModGUI, WFMModGUI, UDPSourceGUI, FileSourceGUI, ATVModGUI, RemoteSourceGUI, FileSinkGui, NFMModGUI, LocalOutputGui, PlutoSDROutputGUI, KiwiSDRGui, LocalInputGui, PlutoSDRInputGui, RemoteInputGui, SDRPlayGui, TestMIGui, Bladerf1OutputGui, BladeRF2OutputGui, LimeSDROutputGUI, AirspyHFGui, FCDProGui, FileInputGUI, RTLSDRGui, TestSourceGui, XTRXInputGUI, XTRXOutputGUI, AirspyGui, Bladerf1InputGui, BladeRF2InputGui, FCDProPlusGui, LimeSDRInputGUI, PerseusGui, SSBDemodGUI, AMDemodGUI, NFMDemodGUI, LoRaDemodGUI, and WFMDemodGUI.
Referenced by DeviceUISet::loadRxChannelSettings(), DeviceAPI::loadSamplingDeviceSettings(), and DeviceUISet::loadTxChannelSettings().
destroy()
virtual void PluginInstanceGUI::destroy () pure virtual
Implemented in RemoteOutputSinkGui, HackRFOutputGui, HackRFInputGui, DSDDemodGUI, SoapySDROutputGui, DATVDemodGUI, SoapySDRInputGui, ChannelAnalyzerGUI, FreeDVDemodGUI, LocalSinkGUI, RemoteSinkGUI, UDPSinkGUI, LocalSourceGUI, FreeDVModGUI, SSBModGUI, UDPSourceGUI, ATVDemodGUI, BFMDemodGUI, FreqTrackerGUI, AMModGUI, WFMModGUI, LocalOutputGui, PlutoSDROutputGUI, LocalInputGui, PlutoSDRInputGui, RemoteInputGui, FileSourceGUI, ATVModGUI, RemoteSourceGUI, FileSinkGui, NFMModGUI, KiwiSDRGui, SDRPlayGui, TestMIGui, Bladerf1OutputGui, BladeRF2OutputGui, LimeSDROutputGUI, AirspyHFGui, FCDProGui, FileInputGUI, RTLSDRGui, TestSourceGui, XTRXInputGUI, XTRXOutputGUI, AirspyGui, Bladerf1InputGui, BladeRF2InputGui, FCDProPlusGui, LimeSDRInputGUI, PerseusGui, SSBDemodGUI, AMDemodGUI, NFMDemodGUI, LoRaDemodGUI, and WFMDemodGUI.
Referenced by PluginInterface::deleteSampleMIMOPluginInstanceGUI(), PluginInterface::deleteSampleSinkPluginInstanceGUI(), and PluginInterface::deleteSampleSourcePluginInstanceGUI().
getCenterFrequency()
virtual qint64 PluginInstanceGUI::getCenterFrequency () const pure virtual
Implemented in RemoteOutputSinkGui, HackRFOutputGui, HackRFInputGui, SoapySDROutputGui, DSDDemodGUI, SoapySDRInputGui, DATVDemodGUI, LocalOutputGui, LocalInputGui, RemoteInputGui, ChannelAnalyzerGUI, FreeDVDemodGUI, LocalSinkGUI, RemoteSinkGUI, UDPSinkGUI, LocalSourceGUI, FreeDVModGUI, SSBModGUI, UDPSourceGUI, FileSinkGui, ATVDemodGUI, BFMDemodGUI, FreqTrackerGUI, AMModGUI, WFMModGUI, PlutoSDROutputGUI, KiwiSDRGui, PlutoSDRInputGui, SDRPlayGui, FileSourceGUI, ATVModGUI, RemoteSourceGUI, TestMIGui, Bladerf1OutputGui, BladeRF2OutputGui, LimeSDROutputGUI, AirspyHFGui, FCDProGui, FileInputGUI, RTLSDRGui, TestSourceGui, XTRXInputGUI, NFMModGUI, XTRXOutputGUI, AirspyGui, Bladerf1InputGui, BladeRF2InputGui, FCDProPlusGui, LimeSDRInputGUI, PerseusGui, SSBDemodGUI, AMDemodGUI, NFMDemodGUI, LoRaDemodGUI, and WFMDemodGUI.
Referenced by DeviceUISet::ChannelInstanceRegistration::operator<(), and DeviceAPI::saveSamplingDeviceSettings().
getInputMessageQueue()
virtual MessageQueue* PluginInstanceGUI::getInputMessageQueue () pure virtual
Implemented in RemoteOutputSinkGui, HackRFOutputGui, HackRFInputGui, DATVDemodGUI, DSDDemodGUI, SoapySDROutputGui, SoapySDRInputGui, ChannelAnalyzerGUI, FreeDVDemodGUI, LocalSinkGUI, RemoteSinkGUI, UDPSinkGUI, LocalSourceGUI, FreeDVModGUI, SSBModGUI, ATVDemodGUI, BFMDemodGUI, FreqTrackerGUI, AMModGUI, WFMModGUI, UDPSourceGUI, LocalOutputGui, LocalInputGui, RemoteInputGui, FileSourceGUI, ATVModGUI, RemoteSourceGUI, FileSinkGui, NFMModGUI, PlutoSDROutputGUI, KiwiSDRGui, PlutoSDRInputGui, SDRPlayGui, TestMIGui, Bladerf1OutputGui, BladeRF2OutputGui, LimeSDROutputGUI, AirspyHFGui, FCDProGui, FileInputGUI, RTLSDRGui, TestSourceGui, XTRXInputGUI, XTRXOutputGUI, AirspyGui, Bladerf1InputGui, BladeRF2InputGui, FCDProPlusGui, LimeSDRInputGUI, PerseusGui, SSBDemodGUI, AMDemodGUI, NFMDemodGUI, LoRaDemodGUI, and WFMDemodGUI.
Referenced by MainWindow::addMIMODevice(), MainWindow::addSinkDevice(), MainWindow::addSourceDevice(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
getName()
virtual QString PluginInstanceGUI::getName () const pure virtual
Implemented in RemoteOutputSinkGui, HackRFOutputGui, HackRFInputGui, DSDDemodGUI, SoapySDROutputGui, DATVDemodGUI, SoapySDRInputGui, ChannelAnalyzerGUI, FreeDVDemodGUI, LocalSinkGUI, RemoteSinkGUI, UDPSinkGUI, LocalSourceGUI, FreeDVModGUI, SSBModGUI, UDPSourceGUI, ATVDemodGUI, BFMDemodGUI, FreqTrackerGUI, AMModGUI, WFMModGUI, LocalOutputGui, LocalInputGui, RemoteInputGui, FileSourceGUI, ATVModGUI, RemoteSourceGUI, FileSinkGui, PlutoSDROutputGUI, PlutoSDRInputGui, NFMModGUI, KiwiSDRGui, SDRPlayGui, TestMIGui, Bladerf1OutputGui, BladeRF2OutputGui, LimeSDROutputGUI, AirspyHFGui, FCDProGui, FileInputGUI, RTLSDRGui, TestSourceGui, XTRXInputGUI, XTRXOutputGUI, AirspyGui, Bladerf1InputGui, BladeRF2InputGui, FCDProPlusGui, LimeSDRInputGUI, PerseusGui, SSBDemodGUI, AMDemodGUI, NFMDemodGUI, LoRaDemodGUI, and WFMDemodGUI.
Referenced by DeviceUISet::ChannelInstanceRegistration::operator<().
handleMessage()
virtual bool PluginInstanceGUI::handleMessage (const Message & message) pure virtual
Implemented in RemoteOutputSinkGui, HackRFOutputGui, HackRFInputGui, DATVDemodGUI, DSDDemodGUI, SoapySDROutputGui, SoapySDRInputGui, ChannelAnalyzerGUI, FreeDVDemodGUI, LocalSinkGUI, RemoteSinkGUI, UDPSinkGUI, LocalSourceGUI, FreeDVModGUI, SSBModGUI, ATVDemodGUI, BFMDemodGUI, FreqTrackerGUI, AMModGUI, WFMModGUI, UDPSourceGUI, LocalOutputGui, LocalInputGui, RemoteInputGui, FileSourceGUI, ATVModGUI, RemoteSourceGUI, FileSinkGui, NFMModGUI, PlutoSDROutputGUI, KiwiSDRGui, PlutoSDRInputGui, SDRPlayGui, TestMIGui, Bladerf1OutputGui, BladeRF2OutputGui, LimeSDROutputGUI, AirspyHFGui, FCDProGui, FileInputGUI, RTLSDRGui, TestSourceGui, XTRXInputGUI, XTRXOutputGUI, AirspyGui, Bladerf1InputGui, BladeRF2InputGui, FCDProPlusGui, LimeSDRInputGUI, PerseusGui, SSBDemodGUI, AMDemodGUI, NFMDemodGUI, LoRaDemodGUI, and WFMDemodGUI.
resetToDefaults()
virtual void PluginInstanceGUI::resetToDefaults () pure virtual
Implemented in RemoteOutputSinkGui, DSDDemodGUI, HackRFOutputGui, DATVDemodGUI, HackRFInputGui, SoapySDROutputGui, ChannelAnalyzerGUI, FreeDVDemodGUI, LocalSinkGUI, RemoteSinkGUI, UDPSinkGUI, LocalSourceGUI, FreeDVModGUI, SSBModGUI, SoapySDRInputGui, ATVDemodGUI, BFMDemodGUI, FreqTrackerGUI, AMModGUI, WFMModGUI, UDPSourceGUI, FileSourceGUI, ATVModGUI, RemoteSourceGUI, NFMModGUI, LocalOutputGui, LocalInputGui, RemoteInputGui, FileSinkGui, PlutoSDROutputGUI, KiwiSDRGui, PlutoSDRInputGui, SDRPlayGui, TestMIGui, Bladerf1OutputGui, BladeRF2OutputGui, LimeSDROutputGUI, AirspyHFGui, FCDProGui, FileInputGUI, RTLSDRGui, TestSourceGui, XTRXInputGUI, XTRXOutputGUI, AirspyGui, Bladerf1InputGui, BladeRF2InputGui, FCDProPlusGui, LimeSDRInputGUI, PerseusGui, SSBDemodGUI, AMDemodGUI, NFMDemodGUI, LoRaDemodGUI, and WFMDemodGUI.
serialize()
virtual QByteArray PluginInstanceGUI::serialize () const pure virtual
Implemented in RemoteOutputSinkGui, HackRFOutputGui, HackRFInputGui, DSDDemodGUI, SoapySDROutputGui, DATVDemodGUI, SoapySDRInputGui, ChannelAnalyzerGUI, FreeDVDemodGUI, LocalSinkGUI, RemoteSinkGUI, UDPSinkGUI, LocalSourceGUI, FreeDVModGUI, SSBModGUI, ATVDemodGUI, BFMDemodGUI, FreqTrackerGUI, AMModGUI, WFMModGUI, UDPSourceGUI, FileSourceGUI, ATVModGUI, RemoteSourceGUI, FileSinkGui, NFMModGUI, LocalOutputGui, PlutoSDROutputGUI, KiwiSDRGui, LocalInputGui, PlutoSDRInputGui, RemoteInputGui, SDRPlayGui, TestMIGui, Bladerf1OutputGui, BladeRF2OutputGui, LimeSDROutputGUI, AirspyHFGui, FCDProGui, FileInputGUI, RTLSDRGui, TestSourceGui, XTRXInputGUI, XTRXOutputGUI, AirspyGui, Bladerf1InputGui, BladeRF2InputGui, FCDProPlusGui, LimeSDRInputGUI, PerseusGui, SSBDemodGUI, AMDemodGUI, NFMDemodGUI, LoRaDemodGUI, and WFMDemodGUI.
Referenced by DeviceAPI::saveSamplingDeviceSettings().
setCenterFrequency()
virtual void PluginInstanceGUI::setCenterFrequency (qint64 centerFrequency) pure virtual
Implemented in RemoteOutputSinkGui, HackRFOutputGui, HackRFInputGui, SoapySDROutputGui, DSDDemodGUI, SoapySDRInputGui, DATVDemodGUI, LocalOutputGui, LocalInputGui, RemoteInputGui, ChannelAnalyzerGUI, FreeDVDemodGUI, LocalSinkGUI, RemoteSinkGUI, UDPSinkGUI, LocalSourceGUI, FreeDVModGUI, SSBModGUI, UDPSourceGUI, FileSinkGui, ATVDemodGUI, BFMDemodGUI, FreqTrackerGUI, AMModGUI, WFMModGUI, PlutoSDROutputGUI, KiwiSDRGui, PlutoSDRInputGui, SDRPlayGui, FileSourceGUI, ATVModGUI, RemoteSourceGUI, TestMIGui, Bladerf1OutputGui, BladeRF2OutputGui, LimeSDROutputGUI, AirspyHFGui, FCDProGui, FileInputGUI, RTLSDRGui, TestSourceGui, XTRXInputGUI, NFMModGUI, XTRXOutputGUI, AirspyGui, Bladerf1InputGui, BladeRF2InputGui, FCDProPlusGui, LimeSDRInputGUI, PerseusGui, SSBDemodGUI, AMDemodGUI, NFMDemodGUI, LoRaDemodGUI, and WFMDemodGUI.
Referenced by DeviceAPI::loadSamplingDeviceSettings().
setName()
virtual void PluginInstanceGUI::setName (const QString & name) pure virtual
Implemented in RemoteOutputSinkGui, HackRFOutputGui, HackRFInputGui, DSDDemodGUI, SoapySDROutputGui, DATVDemodGUI, SoapySDRInputGui, ChannelAnalyzerGUI, FreeDVDemodGUI, LocalSinkGUI, RemoteSinkGUI, UDPSinkGUI, LocalSourceGUI, FreeDVModGUI, SSBModGUI, UDPSourceGUI, ATVDemodGUI, BFMDemodGUI, FreqTrackerGUI, AMModGUI, WFMModGUI, LocalOutputGui, LocalInputGui, RemoteInputGui, FileSourceGUI, ATVModGUI, RemoteSourceGUI, FileSinkGui, PlutoSDROutputGUI, PlutoSDRInputGui, NFMModGUI, KiwiSDRGui, SDRPlayGui, TestMIGui, Bladerf1OutputGui, BladeRF2OutputGui, LimeSDROutputGUI, AirspyHFGui, FCDProGui, FileInputGUI, RTLSDRGui, TestSourceGui, XTRXInputGUI, XTRXOutputGUI, AirspyGui, Bladerf1InputGui, BladeRF2InputGui, FCDProPlusGui, LimeSDRInputGUI, PerseusGui, SSBDemodGUI, AMDemodGUI, NFMDemodGUI, LoRaDemodGUI, and WFMDemodGUI.
The documentation for this class was generated from the following file:
sdrbase/plugin/plugininstancegui.h