SDRAngel: UDPSink Class Reference
UDPSink Class Reference
#include <udpsink.h>
Classes
class MsgConfigureChannelizer
class MsgConfigureUDPSource
class MsgUDPSinkSpectrum
struct Sample16
struct Sample24
Public Slots
void audioReadyRead ()
Public Member Functions
UDPSink (DeviceAPI *deviceAPI)
virtual ~UDPSink ()
virtual void destroy ()
void setSpectrum (BasebandSampleSink *spectrum)
void setSpectrum (MessageQueue *messageQueue, bool enabled)
double getMagSq () const
double getInMagSq () const
bool getSquelchOpen () const
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool positiveOnly)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.udpsink"
static const QString m_channelId = "UDPSink"
static const int udpBlockSize = 512
Protected Member Functions
void applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force=true)
void applySettings (const UDPSinkSettings &settings, bool force=false)
void webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings &response, const UDPSinkSettings &settings)
void webapiFormatChannelReport (SWGSDRangel::SWGChannelReport &response)
void webapiReverseSendSettings (QList< QString > &channelSettingsKeys, const UDPSinkSettings &settings, bool force)
void calculateSquelch (double value)
void initSquelch (bool open)
void udpWrite (FixReal real, FixReal imag)
void udpWriteMono (FixReal sample)
void udpWriteNorm (Real real, Real imag)
void udpWriteNormMono (Real sample)
Protected Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
int m_inputSampleRate
int m_inputFrequencyOffset
UDPSinkSettings m_settings
QUdpSocket * m_audioSocket
double m_magsq
double m_inMagsq
MovingAverage< double > m_outMovingAverage
MovingAverage< double > m_inMovingAverage
MovingAverage< double > m_amMovingAverage
Real m_scale
Complex m_last
Complex m_this
NCO m_nco
Interpolator m_interpolator
Real m_sampleDistanceRemain
fftfilt * UDPFilter
SampleVector m_sampleBuffer
UDPSinkUtil< Sample16 > * m_udpBuffer16
UDPSinkUtil< int16_t > * m_udpBufferMono16
UDPSinkUtil< Sample24 > * m_udpBuffer24
AudioVector m_audioBuffer
uint m_audioBufferFill
AudioFifo m_audioFifo
BasebandSampleSink * m_spectrum
bool m_spectrumEnabled
quint32 m_nextSSBId
quint32 m_nextS16leId
char * m_udpAudioBuf
PhaseDiscriminators m_phaseDiscri
double m_squelch
bool m_squelchOpen
int m_squelchOpenCount
int m_squelchCloseCount
int m_squelchGate
number of samples computed from given gate
int m_squelchRelease
MagAGC m_agc
Bandpass< double > m_bandpass
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
QMutex m_settingsMutex
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Static Protected Attributes
static const int m_udpAudioPayloadSize = 8192
UDP audio samples buffer. No UDP block on Earth is larger than this.
static const Real m_agcTarget = 16384.0f
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Detailed Description
Definition at line 48 of file udpsink.h.
Constructor & Destructor Documentation
UDPSink()
UDPSink::UDPSink (DeviceAPI * deviceAPI)
Definition at line 48 of file udpsink.cpp.
References DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), applyChannelSettings(), applySettings(), audioReadyRead(), Interpolator::create(), m_agc, m_audioBuffer, m_audioBufferFill, UDPSinkSettings::m_audioPort, m_audioSocket, m_channelId, m_channelizer, m_deviceAPI, UDPSinkSettings::m_fmDeviation, m_inMagsq, m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_last, m_magsq, m_nco, m_networkManager, m_nextS16leId, m_nextSSBId, UDPSinkSettings::m_outputSampleRate, m_phaseDiscri, UDPSinkSettings::m_rfBandwidth, m_sampleDistanceRemain, m_scale, m_settings, m_spectrumEnabled, m_this, m_threadedChannelizer, m_udpAudioBuf, m_udpAudioPayloadSize, m_udpBuffer16, m_udpBuffer24, m_udpBufferMono16, UDPSinkSettings::m_udpPort, networkManagerFinished(), SDR_RX_SCALED, MagAGC::setClamping(), MagAGC::setClampMax(), PhaseDiscriminators::setFMScaling(), NCO::setFreq(), udpBlockSize, and UDPFilter.
Referenced by UDPSink::MsgConfigureChannelizer::MsgConfigureChannelizer().
                                      :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(deviceAPI),
         m_inputSampleRate(48000),
         m_inputFrequencyOffset(0),
         m_outMovingAverage(480, 1e-10),
         m_inMovingAverage(480, 1e-10),
         m_amMovingAverage(1200, 1e-10),
         m_audioFifo(24000),
         m_spectrum(0),
         m_squelch(1e-6),
         m_squelchOpen(false),
         m_squelchOpenCount(0),
         m_squelchCloseCount(0),
         m_squelchGate(4800),
         m_squelchRelease(4800),
         m_agc(9600, m_agcTarget, 1e-6),
         m_settingsMutex(QMutex::Recursive)
 {
     setObjectName(m_channelId);
     m_udpBuffer16 = new UDPSinkUtil<Sample16>(this, udpBlockSize, m_settings.m_udpPort);
     m_udpBufferMono16 = new UDPSinkUtil<int16_t>(this, udpBlockSize, m_settings.m_udpPort);
     m_udpBuffer24 = new UDPSinkUtil<Sample24>(this, udpBlockSize, m_settings.m_udpPort);
     m_audioSocket = new QUdpSocket(this);
     m_udpAudioBuf = new char[m_udpAudioPayloadSize];
     m_audioBuffer.resize(1<<9);
     m_audioBufferFill = 0;
     m_nco.setFreq(0, m_inputSampleRate);
     m_interpolator.create(16, m_inputSampleRate, m_settings.m_rfBandwidth / 2.0);
     m_sampleDistanceRemain = m_inputSampleRate / m_settings.m_outputSampleRate;
     m_spectrumEnabled = false;
     m_nextSSBId = 0;
     m_nextS16leId = 0;
     m_last = 0;
     m_this = 0;
     m_scale = 0;
     m_magsq = 0;
     m_inMagsq = 0;
     UDPFilter = new fftfilt(0.0, (m_settings.m_rfBandwidth / 2.0) / m_settings.m_outputSampleRate, udpBlockSize);
     m_phaseDiscri.setFMScaling((float) m_settings. m_outputSampleRate / (2.0f * m_settings.m_fmDeviation));
     if (m_audioSocket->bind(QHostAddress::LocalHost, m_settings.m_audioPort))
     {
         qDebug("UDPSink::UDPSink: bind audio socket to port %d", m_settings.m_audioPort);
         connect(m_audioSocket, SIGNAL(readyRead()), this, SLOT(audioReadyRead()), Qt::QueuedConnection);
     }
     else
     {
         qWarning("UDPSink::UDPSink: cannot bind audio port");
     }
     m_agc.setClampMax(SDR_RX_SCALED*SDR_RX_SCALED);
     m_agc.setClamping(true);
     //DSPEngine::instance()->addAudioSink(&m_audioFifo);
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~UDPSink()
UDPSink::~UDPSink () virtual
Definition at line 122 of file udpsink.cpp.
References DSPEngine::getAudioDeviceManager(), DSPEngine::instance(), m_audioFifo, m_audioSocket, m_channelizer, m_deviceAPI, m_networkManager, m_threadedChannelizer, m_udpAudioBuf, m_udpBuffer16, m_udpBuffer24, m_udpBufferMono16, networkManagerFinished(), AudioDeviceManager::removeAudioSink(), DeviceAPI::removeChannelSink(), DeviceAPI::removeChannelSinkAPI(), and UDPFilter.
Referenced by UDPSink::MsgConfigureChannelizer::MsgConfigureChannelizer().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     delete m_audioSocket;
     delete m_udpBuffer24;
     delete m_udpBuffer16;
     delete m_udpBufferMono16;
     delete[] m_udpAudioBuf;
     DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_audioFifo);
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete UDPFilter;
 }
Member Function Documentation
applyChannelSettings()
void UDPSink::applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force = true) protected
Definition at line 472 of file udpsink.cpp.
References Interpolator::create(), m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_nco, UDPSinkSettings::m_outputSampleRate, UDPSinkSettings::m_rfBandwidth, m_sampleDistanceRemain, m_settings, m_settingsMutex, and NCO::setFreq().
Referenced by handleMessage(), start(), and UDPSink().
 {
     qDebug() << "UDPSink::applyChannelSettings:"
             << " inputSampleRate: " << inputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if((inputFrequencyOffset != m_inputFrequencyOffset) ||
         (inputSampleRate != m_inputSampleRate) || force)
     {
         m_nco.setFreq(-inputFrequencyOffset, inputSampleRate);
     }
     if ((inputSampleRate != m_inputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_interpolator.create(16, inputSampleRate, m_settings.m_rfBandwidth / 2.0);
         m_sampleDistanceRemain = inputSampleRate / m_settings.m_outputSampleRate;
         m_settingsMutex.unlock();
     }
     m_inputSampleRate = inputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applySettings()
void UDPSink::applySettings (const UDPSinkSettings & settings, bool force = false) protected
Definition at line 496 of file udpsink.cpp.
References AudioDeviceManager::addAudioSink(), audioReadyRead(), Bandpass< Type >::create(), Interpolator::create(), UDPSinkSettings::FormatLSB, UDPSinkSettings::FormatLSBMono, UDPSinkSettings::FormatUSB, UDPSinkSettings::FormatUSBMono, DSPEngine::getAudioDeviceManager(), BasebandSampleSink::getInputMessageQueue(), initSquelch(), DSPEngine::instance(), UDPSinkSettings::m_agc, m_agc, m_agcTarget, m_amMovingAverage, UDPSinkSettings::m_audioActive, m_audioBufferFill, m_audioFifo, UDPSinkSettings::m_audioPort, m_audioSocket, UDPSinkSettings::m_audioStereo, m_bandpass, UDPSinkSettings::m_fmDeviation, UDPSinkSettings::m_gain, m_inMovingAverage, UDPSinkSettings::m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_outMovingAverage, UDPSinkSettings::m_outputSampleRate, m_phaseDiscri, UDPSinkSettings::m_reverseAPIAddress, UDPSinkSettings::m_reverseAPIChannelIndex, UDPSinkSettings::m_reverseAPIDeviceIndex, UDPSinkSettings::m_reverseAPIPort, UDPSinkSettings::m_rfBandwidth, m_sampleDistanceRemain, UDPSinkSettings::m_sampleFormat, m_settings, m_settingsMutex, m_squelch, UDPSinkSettings::m_squelchdB, UDPSinkSettings::m_squelchEnabled, UDPSinkSettings::m_squelchGate, m_squelchGate, m_squelchOpen, m_squelchRelease, UDPSinkSettings::m_udpAddress, m_udpBuffer16, m_udpBuffer24, m_udpBufferMono16, UDPSinkSettings::m_udpPort, UDPSinkSettings::m_useReverseAPI, UDPSinkSettings::m_volume, CalcDb::powerFromdB(), AudioDeviceManager::removeAudioSink(), MovingAverage< Type >::resize(), MagAGC::resize(), UDPSinkUtil< T >::setAddress(), PhaseDiscriminators::setFMScaling(), MagAGC::setGate(), UDPSinkUtil< T >::setPort(), MagAGC::setStepDownDelay(), MagAGC::setThreshold(), and webapiReverseSendSettings().
Referenced by handleMessage(), and UDPSink().
 {
     qDebug() << "UDPSink::applySettings:"
             << " m_inputFrequencyOffset: " << settings.m_inputFrequencyOffset
             << " m_audioActive: " << settings.m_audioActive
             << " m_audioStereo: " << settings.m_audioStereo
             << " m_gain: " << settings.m_gain
             << " m_volume: " << settings.m_volume
             << " m_squelchEnabled: " << settings.m_squelchEnabled
             << " m_squelchdB: " << settings.m_squelchdB
             << " m_squelchGate" << settings.m_squelchGate
             << " m_agc" << settings.m_agc
             << " m_sampleFormat: " << settings.m_sampleFormat
             << " m_outputSampleRate: " << settings.m_outputSampleRate
             << " m_rfBandwidth: " << settings.m_rfBandwidth
             << " m_fmDeviation: " << settings.m_fmDeviation
             << " m_udpAddressStr: " << settings.m_udpAddress
             << " m_udpPort: " << settings.m_udpPort
             << " m_audioPort: " << settings.m_audioPort
             << " m_useReverseAPI: " << settings.m_useReverseAPI
             << " m_reverseAPIAddress: " << settings.m_reverseAPIAddress
             << " m_reverseAPIPort: " << settings.m_reverseAPIPort
             << " m_reverseAPIDeviceIndex: " << settings.m_reverseAPIDeviceIndex
             << " m_reverseAPIChannelIndex: " << settings.m_reverseAPIChannelIndex
             << " force: " << force;
     QList<QString> reverseAPIKeys;
     if ((settings.m_inputFrequencyOffset != m_settings.m_inputFrequencyOffset) || force) {
         reverseAPIKeys.append("inputFrequencyOffset");
     }
     if ((settings.m_audioActive != m_settings.m_audioActive) || force) {
         reverseAPIKeys.append("audioActive");
     }
     if ((settings.m_audioStereo != m_settings.m_audioStereo) || force) {
         reverseAPIKeys.append("audioStereo");
     }
     if ((settings.m_gain != m_settings.m_gain) || force) {
         reverseAPIKeys.append("gain");
     }
     if ((settings.m_volume != m_settings.m_volume) || force) {
         reverseAPIKeys.append("volume");
     }
     if ((settings.m_squelchEnabled != m_settings.m_squelchEnabled) || force) {
         reverseAPIKeys.append("squelchEnabled");
     }
     if ((settings.m_squelchdB != m_settings.m_squelchdB) || force) {
         reverseAPIKeys.append("squelchDB");
     }
     if ((settings.m_squelchGate != m_settings.m_squelchGate) || force) {
         reverseAPIKeys.append("squelchGate");
     }
     if ((settings.m_agc != m_settings.m_agc) || force) {
         reverseAPIKeys.append("agc");
     }
     if ((settings.m_sampleFormat != m_settings.m_sampleFormat) || force) {
         reverseAPIKeys.append("sampleFormat");
     }
     if ((settings.m_outputSampleRate != m_settings.m_outputSampleRate) || force) {
         reverseAPIKeys.append("outputSampleRate");
     }
     if ((settings.m_rfBandwidth != m_settings.m_rfBandwidth) || force) {
         reverseAPIKeys.append("rfBandwidth");
     }
     if ((settings.m_fmDeviation != m_settings.m_fmDeviation) || force) {
         reverseAPIKeys.append("fmDeviation");
     }
     if ((settings.m_udpAddress != m_settings.m_udpAddress) || force) {
         reverseAPIKeys.append("udpAddress");
     }
     if ((settings.m_udpPort != m_settings.m_udpPort) || force) {
         reverseAPIKeys.append("udpPort");
     }
     if ((settings.m_audioPort != m_settings.m_audioPort) || force) {
         reverseAPIKeys.append("audioPort");
     }
     m_settingsMutex.lock();
     if ((settings.m_inputFrequencyOffset != m_settings.m_inputFrequencyOffset) ||
         (settings.m_rfBandwidth != m_settings.m_rfBandwidth) ||
         (settings.m_outputSampleRate != m_settings.m_outputSampleRate) || force)
     {
         m_interpolator.create(16, m_inputSampleRate, settings.m_rfBandwidth / 2.0);
         m_sampleDistanceRemain = m_inputSampleRate / settings.m_outputSampleRate;
         if ((settings.m_sampleFormat == UDPSinkSettings::FormatLSB) ||
             (settings.m_sampleFormat == UDPSinkSettings::FormatLSBMono) ||
             (settings.m_sampleFormat == UDPSinkSettings::FormatUSB) ||
             (settings.m_sampleFormat == UDPSinkSettings::FormatUSBMono))
         {
             m_squelchGate = settings.m_outputSampleRate * 0.05;
         }
         else
         {
             m_squelchGate = (settings.m_outputSampleRate * settings.m_squelchGate) / 100;
         }
         m_squelchRelease = (settings.m_outputSampleRate * settings.m_squelchGate) / 100;
         initSquelch(m_squelchOpen);
         m_agc.resize(settings.m_outputSampleRate/5, settings.m_outputSampleRate/20, m_agcTarget); // Fixed 200 ms
         int stepDownDelay =  (settings.m_outputSampleRate * (settings.m_squelchGate == 0 ? 1 : settings.m_squelchGate))/100;
         m_agc.setStepDownDelay(stepDownDelay);
         m_agc.setGate(settings.m_outputSampleRate * 0.05);
         m_bandpass.create(301, settings.m_outputSampleRate, 300.0, settings.m_rfBandwidth / 2.0f);
         m_inMovingAverage.resize(settings.m_outputSampleRate * 0.01, 1e-10);  // 10 ms
         m_amMovingAverage.resize(settings.m_outputSampleRate * 0.005, 1e-10); //  5 ms
         m_outMovingAverage.resize(settings.m_outputSampleRate * 0.01, 1e-10); // 10 ms
     }
     if ((settings.m_audioActive != m_settings.m_audioActive) || force)
     {
         if (settings.m_audioActive)
         {
             m_audioBufferFill = 0;
             DSPEngine::instance()->getAudioDeviceManager()->addAudioSink(&m_audioFifo, getInputMessageQueue());
         }
         else
         {
             DSPEngine::instance()->getAudioDeviceManager()->removeAudioSink(&m_audioFifo);
         }
     }
     if ((settings.m_squelchGate != m_settings.m_squelchGate) || force)
     {
         if ((settings.m_sampleFormat == UDPSinkSettings::FormatLSB) ||
             (settings.m_sampleFormat == UDPSinkSettings::FormatLSBMono) ||
             (settings.m_sampleFormat == UDPSinkSettings::FormatUSB) ||
             (settings.m_sampleFormat == UDPSinkSettings::FormatUSBMono))
         {
             m_squelchGate = settings.m_outputSampleRate * 0.05;
         }
         else
         {
             m_squelchGate = (settings.m_outputSampleRate * settings.m_squelchGate)/100;
         }
         m_squelchRelease = (settings.m_outputSampleRate * settings.m_squelchGate)/100;
         initSquelch(m_squelchOpen);
         int stepDownDelay =  (settings.m_outputSampleRate * (settings.m_squelchGate == 0 ? 1 : settings.m_squelchGate))/100;
         m_agc.setStepDownDelay(stepDownDelay); // same delay for up and down
     }
     if ((settings.m_squelchdB != m_settings.m_squelchdB) || force)
     {
         m_squelch = CalcDb::powerFromdB(settings.m_squelchdB);
         m_agc.setThreshold(m_squelch*(1<<23));
     }
     if ((settings.m_udpAddress != m_settings.m_udpAddress) || force)
     {
         m_udpBuffer16->setAddress(const_cast<QString&>(settings.m_udpAddress));
         m_udpBufferMono16->setAddress(const_cast<QString&>(settings.m_udpAddress));
         m_udpBuffer24->setAddress(const_cast<QString&>(settings.m_udpAddress));
     }
     if ((settings.m_udpPort != m_settings.m_udpPort) || force)
     {
         m_udpBuffer16->setPort(settings.m_udpPort);
         m_udpBufferMono16->setPort(settings.m_udpPort);
         m_udpBuffer24->setPort(settings.m_udpPort);
     }
     if ((settings.m_audioPort != m_settings.m_audioPort) || force)
     {
         disconnect(m_audioSocket, SIGNAL(readyRead()), this, SLOT(audioReadyRead()));
         delete m_audioSocket;
         m_audioSocket = new QUdpSocket(this);
         if (m_audioSocket->bind(QHostAddress::LocalHost, settings.m_audioPort))
         {
             connect(m_audioSocket, SIGNAL(readyRead()), this, SLOT(audioReadyRead()), Qt::QueuedConnection);
             qDebug("UDPSink::handleMessage: audio socket bound to port %d", settings.m_audioPort);
         }
         else
         {
             qWarning("UDPSink::handleMessage: cannot bind audio socket");
         }
     }
     if ((settings.m_fmDeviation != m_settings.m_fmDeviation) || force)
     {
         m_phaseDiscri.setFMScaling((float) settings.m_outputSampleRate / (2.0f * settings.m_fmDeviation));
     }
     m_settingsMutex.unlock();
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex) ||
                 (m_settings.m_reverseAPIChannelIndex != settings.m_reverseAPIChannelIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
 }
audioReadyRead
void UDPSink::audioReadyRead () slot
Definition at line 404 of file udpsink.cpp.
References i, UDPSinkSettings::m_audioActive, m_audioBuffer, m_audioBufferFill, m_audioFifo, m_audioSocket, UDPSinkSettings::m_audioStereo, m_settings, m_udpAudioBuf, UDPSinkSettings::m_volume, and AudioFifo::write().
Referenced by applySettings(), and UDPSink().
 {
     while (m_audioSocket->hasPendingDatagrams())
     {
         qint64 pendingDataSize = m_audioSocket->pendingDatagramSize();
         qint64 udpReadBytes = m_audioSocket->readDatagram(m_udpAudioBuf, pendingDataSize, 0, 0);
         //qDebug("UDPSink::audioReadyRead: %lld", udpReadBytes);
         if (m_settings.m_audioActive)
         {
             if (m_settings.m_audioStereo)
             {
                 for (int i = 0; i < udpReadBytes - 3; i += 4)
                 {
                     qint16 l_sample = (qint16) *(&m_udpAudioBuf[i]);
                     qint16 r_sample = (qint16) *(&m_udpAudioBuf[i+2]);
                     m_audioBuffer[m_audioBufferFill].l  = l_sample * m_settings.m_volume;
                     m_audioBuffer[m_audioBufferFill].r  = r_sample * m_settings.m_volume;
                     ++m_audioBufferFill;
                     if (m_audioBufferFill >= m_audioBuffer.size())
                     {
                         uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
                         if (res != m_audioBufferFill)
{
                             qDebug("UDPSink::audioReadyRead: (stereo) lost %u samples", m_audioBufferFill - res);
                         }
                         m_audioBufferFill = 0;
                     }
                 }
             }
             else
             {
                 for (int i = 0; i < udpReadBytes - 1; i += 2)
                 {
                     qint16 sample = (qint16) *(&m_udpAudioBuf[i]);
                     m_audioBuffer[m_audioBufferFill].l  = sample * m_settings.m_volume;
                     m_audioBuffer[m_audioBufferFill].r  = sample * m_settings.m_volume;
                     ++m_audioBufferFill;
                     if (m_audioBufferFill >= m_audioBuffer.size())
                     {
                         uint res = m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
                         if (res != m_audioBufferFill)
{
                             qDebug("UDPSink::audioReadyRead: (mono) lost %u samples", m_audioBufferFill - res);
                         }
                         m_audioBufferFill = 0;
                     }
                 }
             }
             if (m_audioFifo.write((const quint8*)&m_audioBuffer[0], m_audioBufferFill) != m_audioBufferFill)
             {
                 qDebug("UDPSink::audioReadyRead: lost samples");
             }
             m_audioBufferFill = 0;
         }
     }
     //qDebug("UDPSink::audioReadyRead: done");
 }
calculateSquelch()
void UDPSink::calculateSquelch (double value) inline protected
Definition at line 259 of file udpsink.h.
References UDPSinkSettings::m_squelchEnabled, and m_squelchRelease.
Referenced by feed().
     {
         if ((!m_settings.m_squelchEnabled) || (value > m_squelch))
         {
             if (m_squelchGate == 0)
             {
                 m_squelchOpen = true;
             }
             else
             {
                 if (m_squelchOpenCount < m_squelchGate)
                 {
                     m_squelchOpenCount++;
                 }
                 else
                 {
                     m_squelchCloseCount = m_squelchRelease;
                     m_squelchOpen = true;
                 }
             }
         }
         else
         {
             if (m_squelchGate == 0)
             {
                 m_squelchOpen = false;
             }
             else
             {
                 if (m_squelchCloseCount > 0)
                 {
                     m_squelchCloseCount--;
                 }
                 else
                 {
                     m_squelchOpenCount = 0;
                     m_squelchOpen = false;
                 }
             }
         }
     }
deserialize()
bool UDPSink::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 703 of file udpsink.cpp.
References UDPSink::MsgConfigureUDPSource::create(), UDPSinkSettings::deserialize(), BasebandSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and UDPSinkSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureUDPSource *msg = MsgConfigureUDPSource::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureUDPSource *msg = MsgConfigureUDPSource::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void UDPSink::destroy () inline virtual
Implements ChannelAPI.
Definition at line 101 of file udpsink.h.
 { delete this; }
feed()
void UDPSink::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool positiveOnly) virtual
Implements BasebandSampleSink.
Definition at line 145 of file udpsink.cpp.
References MovingAverage< Type >::average(), calculateSquelch(), Interpolator::decimate(), MovingAverage< Type >::feed(), BasebandSampleSink::feed(), MagAGC::feedAndGetValue(), Bandpass< Type >::filter(), UDPSinkSettings::FormatAMBPFMono, UDPSinkSettings::FormatAMMono, UDPSinkSettings::FormatAMNoDCMono, UDPSinkSettings::FormatIQ16, UDPSinkSettings::FormatIQ24, UDPSinkSettings::FormatLSB, UDPSinkSettings::FormatLSBMono, UDPSinkSettings::FormatNFM, UDPSinkSettings::FormatNFMMono, UDPSinkSettings::FormatUSB, UDPSinkSettings::FormatUSBMono, MagAGC::getMagSq(), i, UDPSinkSettings::m_agc, m_agc, m_amMovingAverage, m_bandpass, UDPSinkSettings::m_gain, m_inMagsq, m_inMovingAverage, m_inputSampleRate, m_interpolator, m_magsq, m_nco, m_outMovingAverage, UDPSinkSettings::m_outputSampleRate, m_phaseDiscri, m_sampleBuffer, m_sampleDistanceRemain, UDPSinkSettings::m_sampleFormat, m_settings, m_settingsMutex, m_spectrum, m_spectrumEnabled, m_squelchOpen, NCO::nextIQ(), PhaseDiscriminators::phaseDiscriminator(), fftfilt::runSSB(), SDR_RX_SCALED, SDR_RX_SCALEF, sqrt(), UDPFilter, udpWrite(), udpWriteMono(), udpWriteNorm(), and udpWriteNormMono().
Referenced by getSquelchOpen().
 {
     Complex ci;
     fftfilt::cmplx* sideband;
     double l, r;
     m_sampleBuffer.clear();
     m_settingsMutex.lock();
     for(SampleVector::const_iterator it = begin; it < end; ++it)
     {
         Complex c(it->real(), it->imag());
         c *= m_nco.nextIQ();
         if(m_interpolator.decimate(&m_sampleDistanceRemain, c, &ci))
         {
             double inMagSq;
             double agcFactor = 1.0;
             if ((m_settings.m_agc) &&
                 (m_settings.m_sampleFormat != UDPSinkSettings::FormatNFM) &&
                 (m_settings.m_sampleFormat != UDPSinkSettings::FormatNFMMono) &&
                 (m_settings.m_sampleFormat != UDPSinkSettings::FormatIQ16) &&
                 (m_settings.m_sampleFormat != UDPSinkSettings::FormatIQ24))
             {
                 agcFactor = m_agc.feedAndGetValue(ci);
                 inMagSq = m_agc.getMagSq();
             }
             else
             {
                 inMagSq = ci.real()*ci.real() + ci.imag()*ci.imag();
             }
             m_inMovingAverage.feed(inMagSq / (SDR_RX_SCALED*SDR_RX_SCALED));
             m_inMagsq = m_inMovingAverage.average();
             Sample ss(ci.real(), ci.imag());
             m_sampleBuffer.push_back(ss);
             m_sampleDistanceRemain += m_inputSampleRate / m_settings.m_outputSampleRate;
             calculateSquelch(m_inMagsq);
             if (m_settings.m_sampleFormat == UDPSinkSettings::FormatLSB) // binaural LSB
             {
                 ci *= agcFactor;
                 int n_out = UDPFilter->runSSB(ci, &sideband, false);
                 if (n_out)
                 {
                     for (int i = 0; i < n_out; i++)
                     {
                         l = m_squelchOpen ? sideband[i].real() * m_settings.m_gain : 0;
                         r = m_squelchOpen ? sideband[i].imag() * m_settings.m_gain : 0;
                         udpWrite(l, r);
                         m_outMovingAverage.feed((l*l + r*r) / (SDR_RX_SCALED*SDR_RX_SCALED));
                     }
                 }
             }
             if (m_settings.m_sampleFormat == UDPSinkSettings::FormatUSB) // binaural USB
             {
                 ci *= agcFactor;
                 int n_out = UDPFilter->runSSB(ci, &sideband, true);
                 if (n_out)
                 {
                     for (int i = 0; i < n_out; i++)
                     {
                         l = m_squelchOpen ? sideband[i].real() * m_settings.m_gain : 0;
                         r = m_squelchOpen ? sideband[i].imag() * m_settings.m_gain : 0;
                         udpWrite(l, r);
                         m_outMovingAverage.feed((l*l + r*r) / (SDR_RX_SCALED*SDR_RX_SCALED));
                     }
                 }
             }
             else if (m_settings.m_sampleFormat == UDPSinkSettings::FormatNFM)
             {
                 Real discri = m_squelchOpen ? m_phaseDiscri.phaseDiscriminator(ci) * m_settings.m_gain : 0;
                 udpWriteNorm(discri, discri);
                 m_outMovingAverage.feed(discri*discri);
             }
             else if (m_settings.m_sampleFormat == UDPSinkSettings::FormatNFMMono)
             {
                 Real discri = m_squelchOpen ? m_phaseDiscri.phaseDiscriminator(ci) * m_settings.m_gain : 0;
                 udpWriteNormMono(discri);
                 m_outMovingAverage.feed(discri*discri);
             }
             else if (m_settings.m_sampleFormat == UDPSinkSettings::FormatLSBMono) // Monaural LSB
             {
                 ci *= agcFactor;
                 int n_out = UDPFilter->runSSB(ci, &sideband, false);
                 if (n_out)
                 {
                     for (int i = 0; i < n_out; i++)
                     {
                         l = m_squelchOpen ? (sideband[i].real() + sideband[i].imag()) * 0.7 * m_settings.m_gain : 0;
                         udpWriteMono(l);
                         m_outMovingAverage.feed((l * l) / (SDR_RX_SCALED*SDR_RX_SCALED));
                     }
                 }
             }
             else if (m_settings.m_sampleFormat == UDPSinkSettings::FormatUSBMono) // Monaural USB
             {
                 ci *= agcFactor;
                 int n_out = UDPFilter->runSSB(ci, &sideband, true);
                 if (n_out)
                 {
                     for (int i = 0; i < n_out; i++)
                     {
                         l = m_squelchOpen ? (sideband[i].real() + sideband[i].imag()) * 0.7 * m_settings.m_gain : 0;
                         udpWriteMono(l);
                         m_outMovingAverage.feed((l * l) / (SDR_RX_SCALED*SDR_RX_SCALED));
                     }
                 }
             }
             else if (m_settings.m_sampleFormat == UDPSinkSettings::FormatAMMono)
             {
                 Real amplitude = m_squelchOpen ? sqrt(inMagSq) * agcFactor * m_settings.m_gain : 0;
                 FixReal demod = (FixReal) amplitude;
                 udpWriteMono(demod);
                 m_outMovingAverage.feed((amplitude/SDR_RX_SCALEF)*(amplitude/SDR_RX_SCALEF));
             }
             else if (m_settings.m_sampleFormat == UDPSinkSettings::FormatAMNoDCMono)
             {
                 if (m_squelchOpen)
                 {
                     double demodf = sqrt(inMagSq);
                     m_amMovingAverage.feed(demodf);
                     Real amplitude = (demodf - m_amMovingAverage.average()) * agcFactor * m_settings.m_gain;
                     FixReal demod = (FixReal) amplitude;
                     udpWriteMono(demod);
                     m_outMovingAverage.feed((amplitude/SDR_RX_SCALEF)*(amplitude/SDR_RX_SCALEF));
                 }
                 else
                 {
                     udpWriteMono(0);
                     m_outMovingAverage.feed(0);
                 }
             }
             else if (m_settings.m_sampleFormat == UDPSinkSettings::FormatAMBPFMono)
             {
                 if (m_squelchOpen)
                 {
                     double demodf = sqrt(inMagSq);
                     demodf = m_bandpass.filter(demodf);
                     demodf /= 301.0;
                     Real amplitude = demodf * agcFactor * m_settings.m_gain;
                     FixReal demod = (FixReal) amplitude;
                     udpWriteMono(demod);
                     m_outMovingAverage.feed((amplitude/SDR_RX_SCALEF)*(amplitude/SDR_RX_SCALEF));
                 }
                 else
                 {
                     udpWriteMono(0);
                     m_outMovingAverage.feed(0);
                 }
             }
             else // Raw I/Q samples
             {
                 if (m_squelchOpen)
                 {
                     udpWrite(ci.real() * m_settings.m_gain, ci.imag() * m_settings.m_gain);
                     m_outMovingAverage.feed((inMagSq*m_settings.m_gain*m_settings.m_gain) / (SDR_RX_SCALED*SDR_RX_SCALED));
                 }
                 else
                 {
                     udpWrite(0, 0);
                     m_outMovingAverage.feed(0);
                 }
             }
             m_magsq = m_outMovingAverage.average();
         }
     }
     //qDebug() << "UDPSink::feed: " << m_sampleBuffer.size() * 4;
     if((m_spectrum != 0) && (m_spectrumEnabled))
     {
         m_spectrum->feed(m_sampleBuffer.begin(), m_sampleBuffer.end(), positiveOnly);
     }
     m_settingsMutex.unlock();
 }
getCenterFrequency()
virtual qint64 UDPSink::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 116 of file udpsink.h.
References deserialize(), UDPSinkSettings::m_inputFrequencyOffset, UDPSink::MsgConfigureUDPSource::m_settings, and serialize().
 { return m_settings.m_inputFrequencyOffset; }
getIdentifier()
virtual void UDPSink::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 114 of file udpsink.h.
 { id = objectName(); }
getInMagSq()
double UDPSink::getInMagSq () const inline
Definition at line 106 of file udpsink.h.
References m_inMagsq.
Referenced by UDPSinkGUI::tick(), and webapiFormatChannelReport().
 { return m_inMagsq; }
getMagSq()
double UDPSink::getMagSq () const inline
Definition at line 105 of file udpsink.h.
References m_magsq.
Referenced by UDPSinkGUI::tick(), and webapiFormatChannelReport().
 { return m_magsq; }
getNbSinkStreams()
virtual int UDPSink::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 121 of file udpsink.h.
 { return 1; }
getNbSourceStreams()
virtual int UDPSink::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 122 of file udpsink.h.
 { return 0; }
getSquelchOpen()
bool UDPSink::getSquelchOpen () const inline
Definition at line 107 of file udpsink.h.
References feed(), handleMessage(), m_squelchOpen, start(), and stop().
Referenced by UDPSinkGUI::tick().
 { return m_squelchOpen; }
getStreamCenterFrequency()
virtual qint64 UDPSink::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 124 of file udpsink.h.
References UDPSinkSettings::m_inputFrequencyOffset, UDPSink::MsgConfigureUDPSource::m_settings, webapiReportGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_inputFrequencyOffset;
     }
getTitle()
virtual void UDPSink::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 115 of file udpsink.h.
References UDPSink::MsgConfigureUDPSource::m_settings, and UDPSinkSettings::m_title.
 { title = m_settings.m_title; }
handleMessage()
bool UDPSink::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 342 of file udpsink.cpp.
References applyChannelSettings(), applySettings(), DownChannelizer::configure(), UDPSink::MsgConfigureChannelizer::getCenterFrequency(), UDPSink::MsgUDPSinkSpectrum::getEnabled(), UDPSink::MsgConfigureUDPSource::getForce(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSink::getInputMessageQueue(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), UDPSink::MsgConfigureChannelizer::getSampleRate(), UDPSink::MsgConfigureUDPSource::getSettings(), BasebandSampleSink::handleMessage(), m_channelizer, m_spectrum, m_spectrumEnabled, and Message::match().
Referenced by getSquelchOpen().
 {
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& notif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "UDPSink::handleMessage: MsgChannelizerNotification: m_inputSampleRate: " << notif.getSampleRate()
                  << " frequencyOffset: " << notif.getFrequencyOffset();
         applyChannelSettings(notif.getSampleRate(), notif.getFrequencyOffset());
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "UDPSink::handleMessage: MsgConfigureChannelizer:"
                 << " sampleRate: " << cfg.getSampleRate()
                 << " centerFrequency: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureUDPSource::match(cmd))
     {
         MsgConfigureUDPSource& cfg = (MsgConfigureUDPSource&) cmd;
         qDebug("UDPSink::handleMessage: MsgConfigureUDPSource");
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else if (MsgUDPSinkSpectrum::match(cmd))
     {
         MsgUDPSinkSpectrum& spc = (MsgUDPSinkSpectrum&) cmd;
         m_spectrumEnabled = spc.getEnabled();
         qDebug() << "UDPSink::handleMessage: MsgUDPSinkSpectrum: m_spectrumEnabled: " << m_spectrumEnabled;
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         if(m_spectrum != 0)
         {
            return m_spectrum->handleMessage(cmd);
         }
         else
         {
             return false;
         }
     }
 }
initSquelch()
void UDPSink::initSquelch (bool open) inline protected
Definition at line 301 of file udpsink.h.
References m_squelchGate, and m_squelchRelease.
Referenced by applySettings().
     {
         if (open)
         {
             m_squelchOpen = true;
             m_squelchOpenCount = m_squelchGate;
             m_squelchCloseCount = m_squelchRelease;
         }
         else
         {
             m_squelchOpen = false;
             m_squelchOpenCount = 0;
             m_squelchCloseCount = 0;
         }
     }
networkManagerFinished
void UDPSink::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 993 of file udpsink.cpp.
Referenced by UDPSink(), and ~UDPSink().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "UDPSink::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("UDPSink::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
serialize()
QByteArray UDPSink::serialize () const virtual
Implements ChannelAPI.
Definition at line 698 of file udpsink.cpp.
References m_settings, and UDPSinkSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
setSpectrum() [1/2]
void UDPSink::setSpectrum (BasebandSampleSink * spectrum) inline
Definition at line 102 of file udpsink.h.
References m_spectrum.
Referenced by UDPSinkGUI::onWidgetRolled(), and UDPSinkGUI::UDPSinkGUI().
 { m_spectrum = spectrum; }
setSpectrum() [2/2]
void UDPSink::setSpectrum (MessageQueue * messageQueue, bool enabled)
Definition at line 139 of file udpsink.cpp.
References UDPSink::MsgUDPSinkSpectrum::create(), and MessageQueue::push().
 {
     Message* cmd = MsgUDPSinkSpectrum::create(enabled);
     messageQueue->push(cmd);
 }
start()
void UDPSink::start () virtual
Implements BasebandSampleSink.
Definition at line 332 of file udpsink.cpp.
References applyChannelSettings(), m_inputFrequencyOffset, m_inputSampleRate, m_phaseDiscri, and PhaseDiscriminators::reset().
Referenced by getSquelchOpen().
 {
     m_phaseDiscri.reset();
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void UDPSink::stop () virtual
Implements BasebandSampleSink.
Definition at line 338 of file udpsink.cpp.
Referenced by getSquelchOpen().
 {
 }
udpWrite()
void UDPSink::udpWrite (FixReal real, FixReal imag) inline protected
Definition at line 317 of file udpsink.h.
References UDPSinkSettings::FormatIQ16, UDPSinkSettings::FormatIQ24, UDPSinkSettings::m_sampleFormat, SDR_RX_SAMP_SZ, and UDPSinkUtil< T >::write().
Referenced by feed().
     {
         if (SDR_RX_SAMP_SZ == 16)
         {
             if (m_settings.m_sampleFormat == UDPSinkSettings::FormatIQ16) {
                 m_udpBuffer16->write(Sample16(real, imag));
             } else if (m_settings.m_sampleFormat == UDPSinkSettings::FormatIQ24) {
                 m_udpBuffer24->write(Sample24(real<<8, imag<<8));
             } else {
                 m_udpBuffer16->write(Sample16(real, imag));
             }
         }
         else if (SDR_RX_SAMP_SZ == 24)
         {
             if (m_settings.m_sampleFormat == UDPSinkSettings::FormatIQ16) {
                 m_udpBuffer16->write(Sample16(real>>8, imag>>8));
             } else if (m_settings.m_sampleFormat == UDPSinkSettings::FormatIQ24) {
                 m_udpBuffer24->write(Sample24(real, imag));
             } else {
                 m_udpBuffer16->write(Sample16(real>>8, imag>>8));
             }
         }
     }
udpWriteMono()
void UDPSink::udpWriteMono (FixReal sample) inline protected
Definition at line 341 of file udpsink.h.
References SDR_RX_SAMP_SZ, and UDPSinkUtil< T >::write().
Referenced by feed().
     {
         if (SDR_RX_SAMP_SZ == 16)
         {
             m_udpBufferMono16->write(sample);
         }
         else if (SDR_RX_SAMP_SZ == 24)
         {
             m_udpBufferMono16->write(sample>>8);
         }
     }
udpWriteNorm()
void UDPSink::udpWriteNorm (Real real, Real imag) inline protected
Definition at line 353 of file udpsink.h.
References UDPSinkUtil< T >::write().
Referenced by feed().
     {
         m_udpBuffer16->write(Sample16(real*32768.0, imag*32768.0));
     }
udpWriteNormMono()
void UDPSink::udpWriteNormMono (Real sample) inline protected
Definition at line 358 of file udpsink.h.
References UDPSinkUtil< T >::write().
Referenced by feed().
     {
         m_udpBufferMono16->write(sample*32768.0);
     }
webapiFormatChannelReport()
void UDPSink::webapiFormatChannelReport (SWGSDRangel::SWGChannelReport & response) protected
Definition at line 896 of file udpsink.cpp.
References CalcDb::dbPower(), getInMagSq(), getMagSq(), SWGSDRangel::SWGChannelReport::getUdpSinkReport(), m_inputSampleRate, m_squelchOpen, SWGSDRangel::SWGUDPSinkReport::setChannelPowerDb(), SWGSDRangel::SWGUDPSinkReport::setInputSampleRate(), SWGSDRangel::SWGUDPSinkReport::setOutputPowerDb(), and SWGSDRangel::SWGUDPSinkReport::setSquelch().
Referenced by webapiReportGet().
 {
     response.getUdpSinkReport()->setChannelPowerDb(CalcDb::dbPower(getInMagSq()));
     response.getUdpSinkReport()->setOutputPowerDb(CalcDb::dbPower(getMagSq()));
     response.getUdpSinkReport()->setSquelch(m_squelchOpen ? 1 : 0);
     response.getUdpSinkReport()->setInputSampleRate(m_inputSampleRate);
 }
webapiFormatChannelSettings()
void UDPSink::webapiFormatChannelSettings (SWGSDRangel::SWGChannelSettings & response, const UDPSinkSettings & settings) protected
Definition at line 850 of file udpsink.cpp.
References SWGSDRangel::SWGUDPSinkSettings::getReverseApiAddress(), SWGSDRangel::SWGUDPSinkSettings::getTitle(), SWGSDRangel::SWGUDPSinkSettings::getUdpAddress(), SWGSDRangel::SWGChannelSettings::getUdpSinkSettings(), UDPSinkSettings::m_agc, UDPSinkSettings::m_audioActive, UDPSinkSettings::m_audioPort, UDPSinkSettings::m_audioStereo, UDPSinkSettings::m_channelMute, UDPSinkSettings::m_fmDeviation, UDPSinkSettings::m_gain, UDPSinkSettings::m_inputFrequencyOffset, UDPSinkSettings::m_outputSampleRate, UDPSinkSettings::m_reverseAPIAddress, UDPSinkSettings::m_reverseAPIChannelIndex, UDPSinkSettings::m_reverseAPIDeviceIndex, UDPSinkSettings::m_reverseAPIPort, UDPSinkSettings::m_rfBandwidth, UDPSinkSettings::m_rgbColor, UDPSinkSettings::m_sampleFormat, UDPSinkSettings::m_squelchdB, UDPSinkSettings::m_squelchEnabled, UDPSinkSettings::m_squelchGate, UDPSinkSettings::m_title, UDPSinkSettings::m_udpAddress, UDPSinkSettings::m_udpPort, UDPSinkSettings::m_useReverseAPI, UDPSinkSettings::m_volume, SWGSDRangel::SWGUDPSinkSettings::setAgc(), SWGSDRangel::SWGUDPSinkSettings::setAudioActive(), SWGSDRangel::SWGUDPSinkSettings::setAudioPort(), SWGSDRangel::SWGUDPSinkSettings::setAudioStereo(), SWGSDRangel::SWGUDPSinkSettings::setChannelMute(), SWGSDRangel::SWGUDPSinkSettings::setFmDeviation(), SWGSDRangel::SWGUDPSinkSettings::setGain(), SWGSDRangel::SWGUDPSinkSettings::setInputFrequencyOffset(), SWGSDRangel::SWGUDPSinkSettings::setOutputSampleRate(), SWGSDRangel::SWGUDPSinkSettings::setReverseApiAddress(), SWGSDRangel::SWGUDPSinkSettings::setReverseApiChannelIndex(), SWGSDRangel::SWGUDPSinkSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGUDPSinkSettings::setReverseApiPort(), SWGSDRangel::SWGUDPSinkSettings::setRfBandwidth(), SWGSDRangel::SWGUDPSinkSettings::setRgbColor(), SWGSDRangel::SWGUDPSinkSettings::setSampleFormat(), SWGSDRangel::SWGUDPSinkSettings::setSquelchDb(), SWGSDRangel::SWGUDPSinkSettings::setSquelchEnabled(), SWGSDRangel::SWGUDPSinkSettings::setSquelchGate(), SWGSDRangel::SWGUDPSinkSettings::setTitle(), SWGSDRangel::SWGUDPSinkSettings::setUdpAddress(), SWGSDRangel::SWGUDPSinkSettings::setUdpPort(), SWGSDRangel::SWGUDPSinkSettings::setUseReverseApi(), and SWGSDRangel::SWGUDPSinkSettings::setVolume().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getUdpSinkSettings()->setOutputSampleRate(settings.m_outputSampleRate);
     response.getUdpSinkSettings()->setSampleFormat((int) settings.m_sampleFormat);
     response.getUdpSinkSettings()->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     response.getUdpSinkSettings()->setRfBandwidth(settings.m_rfBandwidth);
     response.getUdpSinkSettings()->setFmDeviation(settings.m_fmDeviation);
     response.getUdpSinkSettings()->setChannelMute(settings.m_channelMute ? 1 : 0);
     response.getUdpSinkSettings()->setGain(settings.m_gain);
     response.getUdpSinkSettings()->setSquelchDb(settings.m_squelchdB);
     response.getUdpSinkSettings()->setSquelchGate(settings.m_squelchGate);
     response.getUdpSinkSettings()->setSquelchEnabled(settings.m_squelchEnabled ? 1 : 0);
     response.getUdpSinkSettings()->setAgc(settings.m_agc ? 1 : 0);
     response.getUdpSinkSettings()->setAudioActive(settings.m_audioActive ? 1 : 0);
     response.getUdpSinkSettings()->setAudioStereo(settings.m_audioStereo ? 1 : 0);
     response.getUdpSinkSettings()->setVolume(settings.m_volume);
     if (response.getUdpSinkSettings()->getUdpAddress()) {
         *response.getUdpSinkSettings()->getUdpAddress() = settings.m_udpAddress;
     } else {
         response.getUdpSinkSettings()->setUdpAddress(new QString(settings.m_udpAddress));
     }
     response.getUdpSinkSettings()->setUdpPort(settings.m_udpPort);
     response.getUdpSinkSettings()->setAudioPort(settings.m_audioPort);
     response.getUdpSinkSettings()->setRgbColor(settings.m_rgbColor);
     if (response.getUdpSinkSettings()->getTitle()) {
         *response.getUdpSinkSettings()->getTitle() = settings.m_title;
     } else {
         response.getUdpSinkSettings()->setTitle(new QString(settings.m_title));
     }
     response.getUdpSinkSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getUdpSinkSettings()->getReverseApiAddress()) {
         *response.getUdpSinkSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getUdpSinkSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getUdpSinkSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getUdpSinkSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
     response.getUdpSinkSettings()->setReverseApiChannelIndex(settings.m_reverseAPIChannelIndex);
 }
webapiReportGet()
int UDPSink::webapiReportGet (SWGSDRangel::SWGChannelReport & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 839 of file udpsink.cpp.
References SWGSDRangel::SWGChannelReport::getUdpSinkReport(), SWGSDRangel::SWGUDPSinkReport::init(), SWGSDRangel::SWGChannelReport::setUdpSinkReport(), and webapiFormatChannelReport().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setUdpSinkReport(new SWGSDRangel::SWGUDPSinkReport());
     response.getUdpSinkReport()->init();
     webapiFormatChannelReport(response);
     return 200;
 }
webapiReverseSendSettings()
void UDPSink::webapiReverseSendSettings (QList< QString > & channelSettingsKeys, const UDPSinkSettings & settings, bool force) protected
Definition at line 904 of file udpsink.cpp.
References SWGSDRangel::SWGChannelSettings::asJson(), ChannelAPI::getDeviceSetIndex(), ChannelAPI::getIndexInDeviceSet(), SWGSDRangel::SWGChannelSettings::getUdpSinkSettings(), UDPSinkSettings::m_agc, UDPSinkSettings::m_audioActive, UDPSinkSettings::m_audioPort, UDPSinkSettings::m_audioStereo, UDPSinkSettings::m_channelMute, UDPSinkSettings::m_fmDeviation, UDPSinkSettings::m_gain, UDPSinkSettings::m_inputFrequencyOffset, m_networkManager, m_networkRequest, UDPSinkSettings::m_outputSampleRate, UDPSinkSettings::m_reverseAPIAddress, UDPSinkSettings::m_reverseAPIChannelIndex, UDPSinkSettings::m_reverseAPIDeviceIndex, UDPSinkSettings::m_reverseAPIPort, UDPSinkSettings::m_rfBandwidth, UDPSinkSettings::m_rgbColor, UDPSinkSettings::m_sampleFormat, UDPSinkSettings::m_squelchdB, UDPSinkSettings::m_squelchEnabled, UDPSinkSettings::m_squelchGate, UDPSinkSettings::m_title, UDPSinkSettings::m_udpAddress, UDPSinkSettings::m_udpPort, UDPSinkSettings::m_volume, SWGSDRangel::SWGUDPSinkSettings::setAgc(), SWGSDRangel::SWGUDPSinkSettings::setAudioActive(), SWGSDRangel::SWGUDPSinkSettings::setAudioPort(), SWGSDRangel::SWGUDPSinkSettings::setAudioStereo(), SWGSDRangel::SWGUDPSinkSettings::setChannelMute(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGUDPSinkSettings::setFmDeviation(), SWGSDRangel::SWGUDPSinkSettings::setGain(), SWGSDRangel::SWGUDPSinkSettings::setInputFrequencyOffset(), SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex(), SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex(), SWGSDRangel::SWGUDPSinkSettings::setOutputSampleRate(), SWGSDRangel::SWGUDPSinkSettings::setRfBandwidth(), SWGSDRangel::SWGUDPSinkSettings::setRgbColor(), SWGSDRangel::SWGUDPSinkSettings::setSampleFormat(), SWGSDRangel::SWGUDPSinkSettings::setSquelchDb(), SWGSDRangel::SWGUDPSinkSettings::setSquelchEnabled(), SWGSDRangel::SWGUDPSinkSettings::setSquelchGate(), SWGSDRangel::SWGUDPSinkSettings::setTitle(), SWGSDRangel::SWGUDPSinkSettings::setUdpAddress(), SWGSDRangel::SWGUDPSinkSettings::setUdpPort(), SWGSDRangel::SWGChannelSettings::setUdpSinkSettings(), and SWGSDRangel::SWGUDPSinkSettings::setVolume().
Referenced by applySettings().
 {
     SWGSDRangel::SWGChannelSettings *swgChannelSettings = new SWGSDRangel::SWGChannelSettings();
     swgChannelSettings->setDirection(0); // single sink (Rx)
     swgChannelSettings->setOriginatorChannelIndex(getIndexInDeviceSet());
     swgChannelSettings->setOriginatorDeviceSetIndex(getDeviceSetIndex());
     swgChannelSettings->setChannelType(new QString("UDPSink"));
     swgChannelSettings->setUdpSinkSettings(new SWGSDRangel::SWGUDPSinkSettings());
     SWGSDRangel::SWGUDPSinkSettings *swgUDPSinkSettings = swgChannelSettings->getUdpSinkSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (channelSettingsKeys.contains("outputSampleRate") || force) {
         swgUDPSinkSettings->setOutputSampleRate(settings.m_outputSampleRate);
     }
     if (channelSettingsKeys.contains("sampleFormat") || force) {
         swgUDPSinkSettings->setSampleFormat((int) settings.m_sampleFormat);
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset") || force) {
         swgUDPSinkSettings->setInputFrequencyOffset(settings.m_inputFrequencyOffset);
     }
     if (channelSettingsKeys.contains("rfBandwidth") || force) {
         swgUDPSinkSettings->setRfBandwidth(settings.m_rfBandwidth);
     }
     if (channelSettingsKeys.contains("fmDeviation") || force) {
         swgUDPSinkSettings->setFmDeviation(settings.m_fmDeviation);
     }
     if (channelSettingsKeys.contains("channelMute") || force) {
         swgUDPSinkSettings->setChannelMute(settings.m_channelMute ? 1 : 0);
     }
     if (channelSettingsKeys.contains("gain") || force) {
         swgUDPSinkSettings->setGain(settings.m_gain);
     }
     if (channelSettingsKeys.contains("squelchDB") || force) {
         swgUDPSinkSettings->setSquelchDb(settings.m_squelchdB);
     }
     if (channelSettingsKeys.contains("squelchGate") || force) {
         swgUDPSinkSettings->setSquelchGate(settings.m_squelchGate);
     }
     if (channelSettingsKeys.contains("squelchEnabled") || force) {
         swgUDPSinkSettings->setSquelchEnabled(settings.m_squelchEnabled ? 1 : 0);
     }
     if (channelSettingsKeys.contains("agc") || force) {
         swgUDPSinkSettings->setAgc(settings.m_agc ? 1 : 0);
     }
     if (channelSettingsKeys.contains("audioActive") || force) {
         swgUDPSinkSettings->setAudioActive(settings.m_audioActive ? 1 : 0);
     }
     if (channelSettingsKeys.contains("audioStereo") || force) {
         swgUDPSinkSettings->setAudioStereo(settings.m_audioStereo ? 1 : 0);
     }
     if (channelSettingsKeys.contains("volume") || force) {
         swgUDPSinkSettings->setVolume(settings.m_volume);
     }
     if (channelSettingsKeys.contains("udpAddress") || force) {
         swgUDPSinkSettings->setUdpAddress(new QString(settings.m_udpAddress));
     }
     if (channelSettingsKeys.contains("udpPort") || force) {
         swgUDPSinkSettings->setUdpPort(settings.m_udpPort);
     }
     if (channelSettingsKeys.contains("audioPort") || force) {
         swgUDPSinkSettings->setAudioPort(settings.m_audioPort);
     }
     if (channelSettingsKeys.contains("rgbColor") || force) {
         swgUDPSinkSettings->setRgbColor(settings.m_rgbColor);
     }
     if (channelSettingsKeys.contains("title") || force) {
         swgUDPSinkSettings->setTitle(new QString(settings.m_title));
     }
     QString channelSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/channel/%4/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex)
             .arg(settings.m_reverseAPIChannelIndex);
     m_networkRequest.setUrl(QUrl(channelSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgChannelSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgChannelSettings;
 }
webapiSettingsGet()
int UDPSink::webapiSettingsGet (SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 720 of file udpsink.cpp.
References SWGSDRangel::SWGChannelSettings::getUdpSinkSettings(), SWGSDRangel::SWGUDPSinkSettings::init(), m_settings, SWGSDRangel::SWGChannelSettings::setUdpSinkSettings(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     response.setUdpSinkSettings(new SWGSDRangel::SWGUDPSinkSettings());
     response.getUdpSinkSettings()->init();
     webapiFormatChannelSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int UDPSink::webapiSettingsPutPatch (bool force, const QStringList & channelSettingsKeys, SWGSDRangel::SWGChannelSettings & response, QString & errorMessage) virtual
Reimplemented from ChannelAPI.
Definition at line 731 of file udpsink.cpp.
References UDPSink::MsgConfigureUDPSource::create(), UDPSink::MsgConfigureChannelizer::create(), SWGSDRangel::SWGUDPSinkSettings::getAgc(), SWGSDRangel::SWGUDPSinkSettings::getAudioActive(), SWGSDRangel::SWGUDPSinkSettings::getAudioPort(), SWGSDRangel::SWGUDPSinkSettings::getAudioStereo(), SWGSDRangel::SWGUDPSinkSettings::getChannelMute(), SWGSDRangel::SWGUDPSinkSettings::getFmDeviation(), SWGSDRangel::SWGUDPSinkSettings::getGain(), SWGSDRangel::SWGUDPSinkSettings::getInputFrequencyOffset(), SWGSDRangel::SWGUDPSinkSettings::getOutputSampleRate(), SWGSDRangel::SWGUDPSinkSettings::getReverseApiAddress(), SWGSDRangel::SWGUDPSinkSettings::getReverseApiChannelIndex(), SWGSDRangel::SWGUDPSinkSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGUDPSinkSettings::getReverseApiPort(), SWGSDRangel::SWGUDPSinkSettings::getRfBandwidth(), SWGSDRangel::SWGUDPSinkSettings::getRgbColor(), SWGSDRangel::SWGUDPSinkSettings::getSampleFormat(), SWGSDRangel::SWGUDPSinkSettings::getSquelchDb(), SWGSDRangel::SWGUDPSinkSettings::getSquelchEnabled(), SWGSDRangel::SWGUDPSinkSettings::getSquelchGate(), SWGSDRangel::SWGUDPSinkSettings::getTitle(), SWGSDRangel::SWGUDPSinkSettings::getUdpAddress(), SWGSDRangel::SWGUDPSinkSettings::getUdpPort(), SWGSDRangel::SWGChannelSettings::getUdpSinkSettings(), SWGSDRangel::SWGUDPSinkSettings::getUseReverseApi(), SWGSDRangel::SWGUDPSinkSettings::getVolume(), UDPSinkSettings::m_agc, UDPSinkSettings::m_audioActive, UDPSinkSettings::m_audioPort, UDPSinkSettings::m_audioStereo, UDPSinkSettings::m_channelMute, UDPSinkSettings::m_fmDeviation, UDPSinkSettings::m_gain, BasebandSampleSink::m_guiMessageQueue, UDPSinkSettings::m_inputFrequencyOffset, BasebandSampleSink::m_inputMessageQueue, UDPSinkSettings::m_outputSampleRate, UDPSinkSettings::m_reverseAPIAddress, UDPSinkSettings::m_reverseAPIChannelIndex, UDPSinkSettings::m_reverseAPIDeviceIndex, UDPSinkSettings::m_reverseAPIPort, UDPSinkSettings::m_rfBandwidth, UDPSinkSettings::m_rgbColor, UDPSinkSettings::m_sampleFormat, m_settings, UDPSinkSettings::m_squelchdB, UDPSinkSettings::m_squelchEnabled, UDPSinkSettings::m_squelchGate, UDPSinkSettings::m_title, UDPSinkSettings::m_udpAddress, UDPSinkSettings::m_udpPort, UDPSinkSettings::m_useReverseAPI, UDPSinkSettings::m_volume, MessageQueue::push(), and webapiFormatChannelSettings().
Referenced by getStreamCenterFrequency().
 {
     (void) errorMessage;
     UDPSinkSettings settings = m_settings;
     bool frequencyOffsetChanged = false;
     if (channelSettingsKeys.contains("outputSampleRate")) {
         settings.m_outputSampleRate = response.getUdpSinkSettings()->getOutputSampleRate();
     }
     if (channelSettingsKeys.contains("sampleFormat")) {
         settings.m_sampleFormat = (UDPSinkSettings::SampleFormat) response.getUdpSinkSettings()->getSampleFormat();
     }
     if (channelSettingsKeys.contains("inputFrequencyOffset"))
     {
         settings.m_inputFrequencyOffset = response.getUdpSinkSettings()->getInputFrequencyOffset();
         frequencyOffsetChanged = true;
     }
     if (channelSettingsKeys.contains("rfBandwidth")) {
         settings.m_rfBandwidth = response.getUdpSinkSettings()->getRfBandwidth();
     }
     if (channelSettingsKeys.contains("fmDeviation")) {
         settings.m_fmDeviation = response.getUdpSinkSettings()->getFmDeviation();
     }
     if (channelSettingsKeys.contains("channelMute")) {
         settings.m_channelMute = response.getUdpSinkSettings()->getChannelMute() != 0;
     }
     if (channelSettingsKeys.contains("gain")) {
         settings.m_gain = response.getUdpSinkSettings()->getGain();
     }
     if (channelSettingsKeys.contains("squelchDB")) {
         settings.m_squelchdB = response.getUdpSinkSettings()->getSquelchDb();
     }
     if (channelSettingsKeys.contains("squelchGate")) {
         settings.m_squelchGate = response.getUdpSinkSettings()->getSquelchGate();
     }
     if (channelSettingsKeys.contains("squelchEnabled")) {
         settings.m_squelchEnabled = response.getUdpSinkSettings()->getSquelchEnabled() != 0;
     }
     if (channelSettingsKeys.contains("agc")) {
         settings.m_agc = response.getUdpSinkSettings()->getAgc() != 0;
     }
     if (channelSettingsKeys.contains("audioActive")) {
         settings.m_audioActive = response.getUdpSinkSettings()->getAudioActive() != 0;
     }
     if (channelSettingsKeys.contains("audioStereo")) {
         settings.m_audioStereo = response.getUdpSinkSettings()->getAudioStereo() != 0;
     }
     if (channelSettingsKeys.contains("volume")) {
         settings.m_volume = response.getUdpSinkSettings()->getVolume();
     }
     if (channelSettingsKeys.contains("udpAddress")) {
         settings.m_udpAddress = *response.getUdpSinkSettings()->getUdpAddress();
     }
     if (channelSettingsKeys.contains("udpPort")) {
         settings.m_udpPort = response.getUdpSinkSettings()->getUdpPort();
     }
     if (channelSettingsKeys.contains("audioPort")) {
         settings.m_audioPort = response.getUdpSinkSettings()->getAudioPort();
     }
     if (channelSettingsKeys.contains("rgbColor")) {
         settings.m_rgbColor = response.getUdpSinkSettings()->getRgbColor();
     }
     if (channelSettingsKeys.contains("title")) {
         settings.m_title = *response.getUdpSinkSettings()->getTitle();
     }
     if (channelSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getUdpSinkSettings()->getUseReverseApi() != 0;
     }
     if (channelSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getUdpSinkSettings()->getReverseApiAddress();
     }
     if (channelSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getUdpSinkSettings()->getReverseApiPort();
     }
     if (channelSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getUdpSinkSettings()->getReverseApiDeviceIndex();
     }
     if (channelSettingsKeys.contains("reverseAPIChannelIndex")) {
         settings.m_reverseAPIChannelIndex = response.getUdpSinkSettings()->getReverseApiChannelIndex();
     }
     if (frequencyOffsetChanged)
     {
         UDPSink::MsgConfigureChannelizer *msgChan = UDPSink::MsgConfigureChannelizer::create(
                 (int) settings.m_outputSampleRate,
                 (int) settings.m_inputFrequencyOffset);
         m_inputMessageQueue.push(msgChan);
     }
     MsgConfigureUDPSource *msg = MsgConfigureUDPSource::create(settings, force);
     m_inputMessageQueue.push(msg);
     qDebug("getUdpSinkSettings::webapiSettingsPutPatch: forward to GUI: %p", m_guiMessageQueue);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureUDPSource *msgToGUI = MsgConfigureUDPSource::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatChannelSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_agc
MagAGC UDPSink::m_agc protected
Definition at line 244 of file udpsink.h.
Referenced by applySettings(), feed(), and UDPSink().
m_agcTarget
const Real UDPSink::m_agcTarget = 16384.0f static protected
Definition at line 233 of file udpsink.h.
Referenced by applySettings().
m_amMovingAverage
MovingAverage<double> UDPSink::m_amMovingAverage protected
Definition at line 206 of file udpsink.h.
Referenced by applySettings(), and feed().
m_audioBuffer
AudioVector UDPSink::m_audioBuffer protected
Definition at line 221 of file udpsink.h.
Referenced by audioReadyRead(), and UDPSink().
m_audioBufferFill
uint UDPSink::m_audioBufferFill protected
Definition at line 222 of file udpsink.h.
Referenced by applySettings(), audioReadyRead(), and UDPSink().
m_audioFifo
AudioFifo UDPSink::m_audioFifo protected
Definition at line 223 of file udpsink.h.
Referenced by applySettings(), audioReadyRead(), and ~UDPSink().
m_audioSocket
QUdpSocket* UDPSink::m_audioSocket protected
Definition at line 200 of file udpsink.h.
Referenced by applySettings(), audioReadyRead(), UDPSink(), and ~UDPSink().
m_bandpass
Bandpass<double> UDPSink::m_bandpass protected
Definition at line 245 of file udpsink.h.
Referenced by applySettings(), and feed().
m_channelId
const QString UDPSink::m_channelId = "UDPSink" static
Definition at line 146 of file udpsink.h.
Referenced by UDPSinkPlugin::initPlugin(), and UDPSink().
m_channelIdURI
const QString UDPSink::m_channelIdURI = "sdrangel.channel.udpsink" static
Definition at line 145 of file udpsink.h.
Referenced by UDPSinkPlugin::initPlugin(), and UDPSinkGUI::UDPSinkGUI().
m_channelizer
DownChannelizer* UDPSink::m_channelizer protected
Definition at line 194 of file udpsink.h.
Referenced by handleMessage(), UDPSink(), and ~UDPSink().
m_deviceAPI
DeviceAPI* UDPSink::m_deviceAPI protected
Definition at line 192 of file udpsink.h.
Referenced by UDPSink(), and ~UDPSink().
m_inMagsq
double UDPSink::m_inMagsq protected
Definition at line 203 of file udpsink.h.
Referenced by feed(), getInMagSq(), and UDPSink().
m_inMovingAverage
MovingAverage<double> UDPSink::m_inMovingAverage protected
Definition at line 205 of file udpsink.h.
Referenced by applySettings(), and feed().
m_inputFrequencyOffset
int UDPSink::m_inputFrequencyOffset protected
Definition at line 197 of file udpsink.h.
Referenced by applyChannelSettings(), start(), and UDPSink().
m_inputSampleRate
int UDPSink::m_inputSampleRate protected
Definition at line 196 of file udpsink.h.
Referenced by applyChannelSettings(), applySettings(), feed(), start(), UDPSink(), and webapiFormatChannelReport().
m_interpolator
Interpolator UDPSink::m_interpolator protected
Definition at line 212 of file udpsink.h.
Referenced by applyChannelSettings(), applySettings(), feed(), and UDPSink().
m_last
Complex UDPSink::m_last protected
Definition at line 209 of file udpsink.h.
Referenced by UDPSink().
m_magsq
double UDPSink::m_magsq protected
Definition at line 202 of file udpsink.h.
Referenced by feed(), getMagSq(), and UDPSink().
m_nco
NCO UDPSink::m_nco protected
Definition at line 211 of file udpsink.h.
Referenced by applyChannelSettings(), feed(), and UDPSink().
m_networkManager
QNetworkAccessManager* UDPSink::m_networkManager protected
Definition at line 247 of file udpsink.h.
Referenced by UDPSink(), webapiReverseSendSettings(), and ~UDPSink().
m_networkRequest
QNetworkRequest UDPSink::m_networkRequest protected
Definition at line 248 of file udpsink.h.
Referenced by webapiReverseSendSettings().
m_nextS16leId
quint32 UDPSink::m_nextS16leId protected
Definition at line 229 of file udpsink.h.
Referenced by UDPSink().
m_nextSSBId
quint32 UDPSink::m_nextSSBId protected
Definition at line 228 of file udpsink.h.
Referenced by UDPSink().
m_outMovingAverage
MovingAverage<double> UDPSink::m_outMovingAverage protected
Definition at line 204 of file udpsink.h.
Referenced by applySettings(), and feed().
m_phaseDiscri
PhaseDiscriminators UDPSink::m_phaseDiscri protected
Definition at line 235 of file udpsink.h.
Referenced by applySettings(), feed(), start(), and UDPSink().
m_sampleBuffer
SampleVector UDPSink::m_sampleBuffer protected
Definition at line 216 of file udpsink.h.
Referenced by feed().
m_sampleDistanceRemain
Real UDPSink::m_sampleDistanceRemain protected
Definition at line 213 of file udpsink.h.
Referenced by applyChannelSettings(), applySettings(), feed(), and UDPSink().
m_scale
Real UDPSink::m_scale protected
Definition at line 208 of file udpsink.h.
Referenced by UDPSink().
m_settings
UDPSinkSettings UDPSink::m_settings protected
Definition at line 198 of file udpsink.h.
Referenced by applyChannelSettings(), applySettings(), audioReadyRead(), deserialize(), feed(), serialize(), UDPSink(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_settingsMutex
QMutex UDPSink::m_settingsMutex protected
Definition at line 250 of file udpsink.h.
Referenced by applyChannelSettings(), applySettings(), and feed().
m_spectrum
BasebandSampleSink* UDPSink::m_spectrum protected
Definition at line 225 of file udpsink.h.
Referenced by feed(), handleMessage(), and setSpectrum().
m_spectrumEnabled
bool UDPSink::m_spectrumEnabled protected
Definition at line 226 of file udpsink.h.
Referenced by feed(), handleMessage(), and UDPSink().
m_squelch
double UDPSink::m_squelch protected
Definition at line 237 of file udpsink.h.
Referenced by applySettings().
m_squelchCloseCount
int UDPSink::m_squelchCloseCount protected
Definition at line 240 of file udpsink.h.
m_squelchGate
int UDPSink::m_squelchGate protected
number of samples computed from given gate
Definition at line 241 of file udpsink.h.
Referenced by applySettings(), and initSquelch().
m_squelchOpen
bool UDPSink::m_squelchOpen protected
Definition at line 238 of file udpsink.h.
Referenced by applySettings(), feed(), getSquelchOpen(), and webapiFormatChannelReport().
m_squelchOpenCount
int UDPSink::m_squelchOpenCount protected
Definition at line 239 of file udpsink.h.
m_squelchRelease
int UDPSink::m_squelchRelease protected
Definition at line 242 of file udpsink.h.
Referenced by applySettings(), calculateSquelch(), and initSquelch().
m_this
Complex UDPSink::m_this protected
Definition at line 209 of file udpsink.h.
Referenced by UDPSink().
m_threadedChannelizer
ThreadedBasebandSampleSink* UDPSink::m_threadedChannelizer protected
Definition at line 193 of file udpsink.h.
Referenced by UDPSink(), and ~UDPSink().
m_udpAudioBuf
char* UDPSink::m_udpAudioBuf protected
Definition at line 231 of file udpsink.h.
Referenced by audioReadyRead(), UDPSink(), and ~UDPSink().
m_udpAudioPayloadSize
const int UDPSink::m_udpAudioPayloadSize = 8192 static protected
UDP audio samples buffer. No UDP block on Earth is larger than this.
Definition at line 232 of file udpsink.h.
Referenced by UDPSink().
m_udpBuffer16
UDPSinkUtil<Sample16>* UDPSink::m_udpBuffer16 protected
Definition at line 217 of file udpsink.h.
Referenced by applySettings(), UDPSink(), and ~UDPSink().
m_udpBuffer24
UDPSinkUtil<Sample24>* UDPSink::m_udpBuffer24 protected
Definition at line 219 of file udpsink.h.
Referenced by applySettings(), UDPSink(), and ~UDPSink().
m_udpBufferMono16
UDPSinkUtil<int16_t>* UDPSink::m_udpBufferMono16 protected
Definition at line 218 of file udpsink.h.
Referenced by applySettings(), UDPSink(), and ~UDPSink().
udpBlockSize
const int UDPSink::udpBlockSize = 512 static
Definition at line 147 of file udpsink.h.
Referenced by UDPSink().
UDPFilter
fftfilt* UDPSink::UDPFilter protected
Definition at line 214 of file udpsink.h.
Referenced by feed(), UDPSink(), and ~UDPSink().
The documentation for this class was generated from the following files:
plugins/channelrx/udpsink/udpsink.h
plugins/channelrx/udpsink/udpsink.cpp