SDRAngel: ChannelMarker Class Reference
ChannelMarker Class Reference
#include <channelmarker.h>
Public Types
enum sidebands_e {
dsb, lsb, usb, vusb,
vlsb
}
enum frequencyScaleDisplay_e {
FScaleDisplay_freq, FScaleDisplay_title, FScaleDisplay_addressSend, FScaleDisplay_addressReceive,
FScaleDisplay_none
}
typedef enum ChannelMarker::sidebands_e sidebands_t
typedef enum ChannelMarker::frequencyScaleDisplay_e frequencyScaleDisplay_t
Signals
void changedByAPI ()
void changedByCursor ()
void highlightedByCursor ()
Public Member Functions
ChannelMarker (QObject *parent=NULL)
void emitChangedByAPI ()
void setTitle (const QString &title)
const QString & getTitle () const
void setCenterFrequency (int centerFrequency)
void setCenterFrequencyByCursor (int centerFrequency)
int getCenterFrequency () const
void setBandwidth (int bandwidth)
int getBandwidth () const
void setOppositeBandwidth (int bandwidth)
int getOppositeBandwidth () const
void setLowCutoff (int lowCutoff)
int getLowCutoff () const
void setSidebands (sidebands_t sidebands)
sidebands_t getSidebands () const
void setVisible (bool visible)
bool getVisible () const
void setHighlighted (bool highlighted)
void setHighlightedByCursor (bool highlighted)
bool getHighlighted () const
void setColor (const QColor &color)
const QColor & getColor () const
void setMovable (bool movable)
bool getMovable () const
void setFrequencyScaleDisplayType (frequencyScaleDisplay_t type)
frequencyScaleDisplay_t getFrequencyScaleDisplayType () const
const QString & getDisplayAddressSend () const
const QString & getDisplayAddressReceive () const
void setSourceOrSinkStream (bool sourceOrSinkStream)
bool getSourceOrSinkStream () const
void setStreamIndex (int streamIndex)
int getStreamIndex () const
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Protected Member Functions
void resetToDefaults ()
Protected Attributes
QString m_title
QString m_displayAddressSend
QString m_displayAddressReceive
int m_centerFrequency
int m_bandwidth
int m_oppositeBandwidth
int m_lowCutoff
sidebands_t m_sidebands
bool m_visible
bool m_highlighted
QColor m_color
bool m_movable
frequencyScaleDisplay_t m_fScaleDisplayType
bool m_sourceOrSinkStream
int m_streamIndex
Static Protected Attributes
static QRgb m_colorTable []
static int m_nextColor = 0
Detailed Description
Definition at line 11 of file channelmarker.h.
Member Typedef Documentation
frequencyScaleDisplay_t
typedef enum ChannelMarker::frequencyScaleDisplay_e ChannelMarker::frequencyScaleDisplay_t
sidebands_t
typedef enum ChannelMarker::sidebands_e ChannelMarker::sidebands_t
Member Enumeration Documentation
frequencyScaleDisplay_e
enum ChannelMarker::frequencyScaleDisplay_e
Enumerator
FScaleDisplay_freq
FScaleDisplay_title
FScaleDisplay_addressSend
FScaleDisplay_addressReceive
FScaleDisplay_none
Definition at line 24 of file channelmarker.h.
     {
         FScaleDisplay_freq,
         FScaleDisplay_title,
         FScaleDisplay_addressSend,
         FScaleDisplay_addressReceive,
         FScaleDisplay_none
     } frequencyScaleDisplay_t;
sidebands_e
enum ChannelMarker::sidebands_e
Enumerator
dsb
lsb
usb
vusb
USB with vestigial LSB.
vlsb
LSB with vestigial USB.
Definition at line 15 of file channelmarker.h.
     {
         dsb,
         lsb,
         usb,
         vusb,
         vlsb
     } sidebands_t;
Constructor & Destructor Documentation
ChannelMarker()
ChannelMarker::ChannelMarker (QObject * parent = NULL)
Definition at line 29 of file channelmarker.cpp.
References m_colorTable, and m_nextColor.
                                             :
     QObject(parent),
     m_centerFrequency(0),
     m_bandwidth(0),
     m_oppositeBandwidth(0),
     m_lowCutoff(0),
     m_sidebands(dsb),
     m_visible(false),
     m_highlighted(false),
     m_color(m_colorTable[m_nextColor]),
     m_movable(true),
     m_fScaleDisplayType(FScaleDisplay_freq),
     m_sourceOrSinkStream(true),
     m_streamIndex(0)
 {
     ++m_nextColor;
     if(m_colorTable[m_nextColor] == 0)
         m_nextColor = 0;
 }
Member Function Documentation
changedByAPI
void ChannelMarker::changedByAPI () signal
Referenced by emitChangedByAPI(), setBandwidth(), setCenterFrequency(), setColor(), setHighlighted(), setLowCutoff(), setOppositeBandwidth(), setSidebands(), setTitle(), and setVisible().
changedByCursor
void ChannelMarker::changedByCursor () signal
Referenced by setCenterFrequencyByCursor().
deserialize()
bool ChannelMarker::deserialize (const QByteArray & data) virtual
Implements Serializable.
Definition at line 138 of file channelmarker.cpp.
References FScaleDisplay_freq, FScaleDisplay_none, SimpleDeserializer::getVersion(), SimpleDeserializer::isValid(), SimpleDeserializer::readS32(), SimpleDeserializer::readString(), SimpleDeserializer::readU32(), resetToDefaults(), setCenterFrequency(), setColor(), setFrequencyScaleDisplayType(), and setTitle().
 {
     SimpleDeserializer d(data);
     if(!d.isValid())
     {
         resetToDefaults();
         return false;
     }
     if(d.getVersion() == 1)
     {
         quint32 u32tmp;
         qint32 tmp;
         QString strtmp;
         blockSignals(true);
         d.readS32(1, &tmp, 0);
         setCenterFrequency(tmp);
         if(d.readU32(2, &u32tmp)) {
             setColor(u32tmp);
         }
         d.readString(3, &strtmp, "Channel");
         setTitle(strtmp);
         d.readS32(7, &tmp, 0);
         if ((tmp >= 0) && (tmp < FScaleDisplay_none)) {
             setFrequencyScaleDisplayType((frequencyScaleDisplay_t) tmp);
         } else {
             setFrequencyScaleDisplayType(FScaleDisplay_freq);
         }
         blockSignals(false);
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
emitChangedByAPI()
void ChannelMarker::emitChangedByAPI ()
Definition at line 49 of file channelmarker.cpp.
References changedByAPI().
Referenced by ATVDemodGUI::deserialize(), and ATVDemodGUI::setChannelMarkerBandwidth().
 {
     emit changedByAPI();
 }
getBandwidth()
int ChannelMarker::getBandwidth () const inline
Definition at line 45 of file channelmarker.h.
Referenced by GLSpectrum::applyChanges(), and DATVDemodGUI::on_rfBandwidth_changed().
 { return m_bandwidth; }
getCenterFrequency()
int ChannelMarker::getCenterFrequency () const inline
Definition at line 42 of file channelmarker.h.
Referenced by GLSpectrum::applyChanges(), ATVDemodGUI::applyRFSettings(), WFMDemodGUI::applySettings(), LoRaDemodGUI::applySettings(), NFMDemodGUI::applySettings(), AMDemodGUI::applySettings(), SSBDemodGUI::applySettings(), NFMModGUI::applySettings(), AMModGUI::applySettings(), UDPSinkGUI::applySettings(), ATVDemodGUI::applySettings(), ATVModGUI::applySettings(), WFMModGUI::applySettings(), ChannelAnalyzerGUI::applySettings(), FreeDVDemodGUI::applySettings(), DSDDemodGUI::applySettings(), DATVDemodGUI::applySettings(), BFMDemodGUI::changeFrequency(), WFMDemodGUI::channelMarkerChangedByCursor(), NFMDemodGUI::channelMarkerChangedByCursor(), AMDemodGUI::channelMarkerChangedByCursor(), SSBDemodGUI::channelMarkerChangedByCursor(), NFMModGUI::channelMarkerChangedByCursor(), ATVModGUI::channelMarkerChangedByCursor(), AMModGUI::channelMarkerChangedByCursor(), BFMDemodGUI::channelMarkerChangedByCursor(), WFMModGUI::channelMarkerChangedByCursor(), ATVDemodGUI::channelMarkerChangedByCursor(), UDPSourceGUI::channelMarkerChangedByCursor(), FreqTrackerGUI::channelMarkerChangedByCursor(), UDPSinkGUI::channelMarkerChangedByCursor(), FreeDVModGUI::channelMarkerChangedByCursor(), SSBModGUI::channelMarkerChangedByCursor(), FreeDVDemodGUI::channelMarkerChangedByCursor(), ChannelAnalyzerGUI::channelMarkerChangedByCursor(), DSDDemodGUI::channelMarkerChangedByCursor(), DATVDemodGUI::channelMarkerChangedByCursor(), WFMDemodGUI::displaySettings(), NFMDemodGUI::displaySettings(), AMDemodGUI::displaySettings(), SSBDemodGUI::displaySettings(), FreqTrackerGUI::displaySettings(), BFMDemodGUI::displaySettings(), NFMModGUI::displaySettings(), AMModGUI::displaySettings(), WFMModGUI::displaySettings(), UDPSinkGUI::displaySettings(), FreeDVDemodGUI::displaySettings(), DSDDemodGUI::displaySettings(), WFMDemodGUI::getCenterFrequency(), LoRaDemodGUI::getCenterFrequency(), NFMDemodGUI::getCenterFrequency(), AMDemodGUI::getCenterFrequency(), SSBDemodGUI::getCenterFrequency(), NFMModGUI::getCenterFrequency(), ATVModGUI::getCenterFrequency(), AMModGUI::getCenterFrequency(), WFMModGUI::getCenterFrequency(), BFMDemodGUI::getCenterFrequency(), ATVDemodGUI::getCenterFrequency(), FreqTrackerGUI::getCenterFrequency(), UDPSinkGUI::getCenterFrequency(), FreeDVModGUI::getCenterFrequency(), UDPSourceGUI::getCenterFrequency(), SSBModGUI::getCenterFrequency(), FreeDVDemodGUI::getCenterFrequency(), ChannelAnalyzerGUI::getCenterFrequency(), DATVDemodGUI::getCenterFrequency(), DSDDemodGUI::getCenterFrequency(), WFMDemodGUI::on_deltaFrequency_changed(), NFMDemodGUI::on_deltaFrequency_changed(), AMDemodGUI::on_deltaFrequency_changed(), SSBDemodGUI::on_deltaFrequency_changed(), FreqTrackerGUI::on_deltaFrequency_changed(), DATVDemodGUI::on_deltaFrequency_changed(), BFMDemodGUI::on_deltaFrequency_changed(), NFMModGUI::on_deltaFrequency_changed(), ChannelAnalyzerGUI::on_deltaFrequency_changed(), UDPSinkGUI::on_deltaFrequency_changed(), FreeDVDemodGUI::on_deltaFrequency_changed(), FreeDVModGUI::on_deltaFrequency_changed(), SSBModGUI::on_deltaFrequency_changed(), WFMModGUI::on_deltaFrequency_changed(), DSDDemodGUI::on_deltaFrequency_changed(), WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), ChannelAnalyzerGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), DSDDemodGUI::onMenuDialogCalled(), ATVDemodGUI::serialize(), serialize(), SSBDemodGUI::setCenterFrequency(), SSBModGUI::setCenterFrequency(), FreeDVModGUI::setCenterFrequency(), FreeDVDemodGUI::setCenterFrequency(), and ChannelAnalyzerGUI::setCenterFrequency().
 { return m_centerFrequency; }
getColor()
const QColor& ChannelMarker::getColor () const inline
Definition at line 64 of file channelmarker.h.
Referenced by AMDemodGUI::AMDemodGUI(), LoRaDemodGUI::applySettings(), LocalSinkGUI::applySettings(), RemoteSinkGUI::applySettings(), LocalSourceGUI::applySettings(), AMModGUI::applySettings(), RemoteSourceGUI::applySettings(), WFMModGUI::applySettings(), FileSourceGUI::applySettings(), DATVDemodGUI::applySettings(), ATVDemodGUI::ATVDemodGUI(), ATVModGUI::ATVModGUI(), BasicChannelSettingsDialog::BasicChannelSettingsDialog(), BFMDemodGUI::BFMDemodGUI(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), FreeDVModGUI::channelMarkerUpdate(), SSBModGUI::channelMarkerUpdate(), FreqTrackerGUI::FreqTrackerGUI(), WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), ChannelAnalyzerGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), DSDDemodGUI::onMenuDialogCalled(), GLSpectrum::paintGL(), ATVDemodGUI::serialize(), serialize(), SSBDemodGUI::SSBDemodGUI(), SSBModGUI::SSBModGUI(), UDPSinkGUI::UDPSinkGUI(), and WFMDemodGUI::WFMDemodGUI().
 { return m_color; }
getDisplayAddressReceive()
const QString& ChannelMarker::getDisplayAddressReceive () const inline
Definition at line 73 of file channelmarker.h.
Referenced by GLSpectrum::applyChanges().
 { return m_displayAddressReceive; }
getDisplayAddressSend()
const QString& ChannelMarker::getDisplayAddressSend () const inline
Definition at line 72 of file channelmarker.h.
Referenced by GLSpectrum::applyChanges().
 { return m_displayAddressSend; }
getFrequencyScaleDisplayType()
frequencyScaleDisplay_t ChannelMarker::getFrequencyScaleDisplayType () const inline
Definition at line 70 of file channelmarker.h.
Referenced by GLSpectrum::applyChanges(), BasicChannelSettingsDialog::BasicChannelSettingsDialog(), and serialize().
 { return m_fScaleDisplayType; }
getHighlighted()
bool ChannelMarker::getHighlighted () const inline
Definition at line 61 of file channelmarker.h.
Referenced by GLSpectrum::applyChanges(), WFMDemodGUI::channelMarkerHighlightedByCursor(), AMDemodGUI::channelMarkerHighlightedByCursor(), NFMDemodGUI::channelMarkerHighlightedByCursor(), SSBDemodGUI::channelMarkerHighlightedByCursor(), BFMDemodGUI::channelMarkerHighlightedByCursor(), FreqTrackerGUI::channelMarkerHighlightedByCursor(), ATVDemodGUI::channelMarkerHighlightedByCursor(), UDPSinkGUI::channelMarkerHighlightedByCursor(), ChannelAnalyzerGUI::channelMarkerHighlightedByCursor(), FreeDVDemodGUI::channelMarkerHighlightedByCursor(), DSDDemodGUI::channelMarkerHighlightedByCursor(), DATVDemodGUI::channelMarkerHighlightedByCursor(), and GLSpectrum::paintGL().
 { return m_highlighted; }
getLowCutoff()
int ChannelMarker::getLowCutoff () const inline
Definition at line 51 of file channelmarker.h.
Referenced by GLSpectrum::applyChanges().
 { return m_lowCutoff; }
getMovable()
bool ChannelMarker::getMovable () const inline
Definition at line 67 of file channelmarker.h.
 { return m_movable; }
getOppositeBandwidth()
int ChannelMarker::getOppositeBandwidth () const inline
Definition at line 48 of file channelmarker.h.
Referenced by GLSpectrum::applyChanges().
 { return m_oppositeBandwidth; }
getSidebands()
sidebands_t ChannelMarker::getSidebands () const inline
Definition at line 54 of file channelmarker.h.
Referenced by GLSpectrum::applyChanges(), and GLSpectrum::paintGL().
 { return m_sidebands; }
getSourceOrSinkStream()
bool ChannelMarker::getSourceOrSinkStream () const inline
Definition at line 76 of file channelmarker.h.
Referenced by GLSpectrum::applyChanges(), and GLSpectrum::paintGL().
 { return m_sourceOrSinkStream; }
getStreamIndex()
int ChannelMarker::getStreamIndex () const inline
Definition at line 78 of file channelmarker.h.
References Serializable::deserialize(), and Serializable::serialize().
Referenced by GLSpectrum::applyChanges(), and GLSpectrum::paintGL().
 { return m_streamIndex; }
getTitle()
const QString& ChannelMarker::getTitle () const inline
Definition at line 38 of file channelmarker.h.
Referenced by GLSpectrum::applyChanges(), BasicChannelSettingsDialog::BasicChannelSettingsDialog(), WFMDemodGUI::displaySettings(), NFMDemodGUI::displaySettings(), AMDemodGUI::displaySettings(), SSBDemodGUI::displaySettings(), FreqTrackerGUI::displaySettings(), LocalSinkGUI::displaySettings(), RemoteSinkGUI::displaySettings(), LocalSourceGUI::displaySettings(), UDPSourceGUI::displaySettings(), BFMDemodGUI::displaySettings(), NFMModGUI::displaySettings(), AMModGUI::displaySettings(), RemoteSourceGUI::displaySettings(), ATVModGUI::displaySettings(), WFMModGUI::displaySettings(), UDPSinkGUI::displaySettings(), ChannelAnalyzerGUI::displaySettings(), FreeDVModGUI::displaySettings(), SSBModGUI::displaySettings(), FreeDVDemodGUI::displaySettings(), FileSourceGUI::displaySettings(), DSDDemodGUI::displaySettings(), WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), ChannelAnalyzerGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), DSDDemodGUI::onMenuDialogCalled(), and serialize().
 { return m_title; }
getVisible()
bool ChannelMarker::getVisible () const inline
Definition at line 57 of file channelmarker.h.
Referenced by GLSpectrum::paintGL().
 { return m_visible; }
highlightedByCursor
void ChannelMarker::highlightedByCursor () signal
Referenced by setHighlightedByCursor().
resetToDefaults()
void ChannelMarker::resetToDefaults () protected
Definition at line 120 of file channelmarker.cpp.
References FScaleDisplay_freq, setCenterFrequency(), setColor(), setFrequencyScaleDisplayType(), and setTitle().
Referenced by deserialize().
 {
     setTitle("Channel");
     setCenterFrequency(0);
     setColor(Qt::white);
     setFrequencyScaleDisplayType(FScaleDisplay_freq);
 }
serialize()
QByteArray ChannelMarker::serialize () const virtual
Implements Serializable.
Definition at line 128 of file channelmarker.cpp.
References SimpleSerializer::final(), getCenterFrequency(), getColor(), getFrequencyScaleDisplayType(), getTitle(), SimpleSerializer::writeS32(), SimpleSerializer::writeString(), and SimpleSerializer::writeU32().
 {
     SimpleSerializer s(1);
     s.writeS32(1, getCenterFrequency());
     s.writeU32(2, getColor().rgb());
     s.writeString(3, getTitle());
     s.writeS32(7, (int) getFrequencyScaleDisplayType());
     return s.final();
 }
setBandwidth()
void ChannelMarker::setBandwidth (int bandwidth)
Definition at line 72 of file channelmarker.cpp.
References changedByAPI(), and m_bandwidth.
Referenced by AMDemodGUI::AMDemodGUI(), AMModGUI::AMModGUI(), SSBDemodGUI::applyBandwidths(), SSBModGUI::applyBandwidths(), ATVDemodGUI::ATVDemodGUI(), ATVModGUI::ATVModGUI(), BFMDemodGUI::BFMDemodGUI(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), DATVDemodGUI::DATVDemodGUI(), LocalSinkGUI::displayRateAndShift(), RemoteSinkGUI::displayRateAndShift(), LocalSourceGUI::displayRateAndShift(), FileSourceGUI::displayRateAndShift(), WFMDemodGUI::displaySettings(), LoRaDemodGUI::displaySettings(), NFMDemodGUI::displaySettings(), AMDemodGUI::displaySettings(), SSBDemodGUI::displaySettings(), FreqTrackerGUI::displaySettings(), LocalSinkGUI::displaySettings(), RemoteSinkGUI::displaySettings(), LocalSourceGUI::displaySettings(), BFMDemodGUI::displaySettings(), UDPSourceGUI::displaySettings(), NFMModGUI::displaySettings(), AMModGUI::displaySettings(), RemoteSourceGUI::displaySettings(), WFMModGUI::displaySettings(), UDPSinkGUI::displaySettings(), ChannelAnalyzerGUI::displaySettings(), FreeDVModGUI::displaySettings(), FreeDVDemodGUI::displaySettings(), SSBModGUI::displaySettings(), FileSourceGUI::displaySettings(), DATVDemodGUI::displaySettings(), DSDDemodGUI::DSDDemodGUI(), FreqTrackerGUI::FreqTrackerGUI(), RemoteSourceGUI::handleMessage(), NFMDemodGUI::NFMDemodGUI(), NFMModGUI::NFMModGUI(), UDPSourceGUI::on_applyBtn_clicked(), UDPSinkGUI::on_applyBtn_clicked(), LoRaDemodGUI::on_BW_valueChanged(), FreeDVDemodGUI::on_freeDVMode_currentIndexChanged(), FreeDVModGUI::on_freeDVMode_currentIndexChanged(), DATVDemodGUI::on_rfBandwidth_changed(), WFMDemodGUI::on_rfBW_changed(), NFMDemodGUI::on_rfBW_currentIndexChanged(), NFMModGUI::on_rfBW_currentIndexChanged(), WFMModGUI::on_rfBW_currentIndexChanged(), AMDemodGUI::on_rfBW_valueChanged(), FreqTrackerGUI::on_rfBW_valueChanged(), BFMDemodGUI::on_rfBW_valueChanged(), AMModGUI::on_rfBW_valueChanged(), DSDDemodGUI::on_rfBW_valueChanged(), ATVDemodGUI::setChannelMarkerBandwidth(), ATVModGUI::setChannelMarkerBandwidth(), ChannelAnalyzerGUI::setFiltersUIBoundaries(), SSBDemodGUI::SSBDemodGUI(), SSBModGUI::SSBModGUI(), UDPSinkGUI::UDPSinkGUI(), UDPSourceGUI::UDPSourceGUI(), WFMDemodGUI::WFMDemodGUI(), and WFMModGUI::WFMModGUI().
 {
     m_bandwidth = bandwidth;
     emit changedByAPI();
 }
setCenterFrequency()
void ChannelMarker::setCenterFrequency (int centerFrequency)
Definition at line 60 of file channelmarker.cpp.
References changedByAPI(), and m_centerFrequency.
Referenced by AMDemodGUI::AMDemodGUI(), AMModGUI::AMModGUI(), ATVDemodGUI::ATVDemodGUI(), ATVModGUI::ATVModGUI(), BFMDemodGUI::BFMDemodGUI(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), DATVDemodGUI::DATVDemodGUI(), ATVDemodGUI::deserialize(), deserialize(), LocalSinkGUI::displayRateAndShift(), RemoteSinkGUI::displayRateAndShift(), LocalSourceGUI::displayRateAndShift(), FileSourceGUI::displayRateAndShift(), WFMDemodGUI::displaySettings(), LoRaDemodGUI::displaySettings(), NFMDemodGUI::displaySettings(), AMDemodGUI::displaySettings(), SSBDemodGUI::displaySettings(), FreqTrackerGUI::displaySettings(), LocalSinkGUI::displaySettings(), RemoteSinkGUI::displaySettings(), LocalSourceGUI::displaySettings(), BFMDemodGUI::displaySettings(), UDPSourceGUI::displaySettings(), NFMModGUI::displaySettings(), AMModGUI::displaySettings(), RemoteSourceGUI::displaySettings(), ATVModGUI::displaySettings(), WFMModGUI::displaySettings(), UDPSinkGUI::displaySettings(), ChannelAnalyzerGUI::displaySettings(), FreeDVModGUI::displaySettings(), SSBModGUI::displaySettings(), FreeDVDemodGUI::displaySettings(), FileSourceGUI::displaySettings(), DSDDemodGUI::displaySettings(), DATVDemodGUI::displaySettings(), DSDDemodGUI::DSDDemodGUI(), FileSourceGUI::FileSourceGUI(), FreqTrackerGUI::FreqTrackerGUI(), FreqTrackerGUI::handleMessage(), LocalSinkGUI::LocalSinkGUI(), LocalSourceGUI::LocalSourceGUI(), NFMDemodGUI::NFMDemodGUI(), NFMModGUI::NFMModGUI(), WFMDemodGUI::on_deltaFrequency_changed(), NFMDemodGUI::on_deltaFrequency_changed(), AMDemodGUI::on_deltaFrequency_changed(), SSBDemodGUI::on_deltaFrequency_changed(), FreqTrackerGUI::on_deltaFrequency_changed(), UDPSourceGUI::on_deltaFrequency_changed(), DATVDemodGUI::on_deltaFrequency_changed(), BFMDemodGUI::on_deltaFrequency_changed(), NFMModGUI::on_deltaFrequency_changed(), AMModGUI::on_deltaFrequency_changed(), ChannelAnalyzerGUI::on_deltaFrequency_changed(), UDPSinkGUI::on_deltaFrequency_changed(), FreeDVDemodGUI::on_deltaFrequency_changed(), FreeDVModGUI::on_deltaFrequency_changed(), SSBModGUI::on_deltaFrequency_changed(), ATVModGUI::on_deltaFrequency_changed(), WFMModGUI::on_deltaFrequency_changed(), DSDDemodGUI::on_deltaFrequency_changed(), ATVDemodGUI::on_deltaFrequency_changed(), RemoteSinkGUI::RemoteSinkGUI(), RemoteSourceGUI::RemoteSourceGUI(), resetToDefaults(), WFMDemodGUI::setCenterFrequency(), LoRaDemodGUI::setCenterFrequency(), NFMDemodGUI::setCenterFrequency(), AMDemodGUI::setCenterFrequency(), SSBDemodGUI::setCenterFrequency(), NFMModGUI::setCenterFrequency(), ATVModGUI::setCenterFrequency(), WFMModGUI::setCenterFrequency(), ATVDemodGUI::setCenterFrequency(), AMModGUI::setCenterFrequency(), FreqTrackerGUI::setCenterFrequency(), BFMDemodGUI::setCenterFrequency(), UDPSourceGUI::setCenterFrequency(), UDPSinkGUI::setCenterFrequency(), SSBModGUI::setCenterFrequency(), FreeDVModGUI::setCenterFrequency(), FreeDVDemodGUI::setCenterFrequency(), ChannelAnalyzerGUI::setCenterFrequency(), DATVDemodGUI::setCenterFrequency(), DSDDemodGUI::setCenterFrequency(), SSBDemodGUI::SSBDemodGUI(), SSBModGUI::SSBModGUI(), UDPSinkGUI::UDPSinkGUI(), UDPSourceGUI::UDPSourceGUI(), WFMDemodGUI::WFMDemodGUI(), and WFMModGUI::WFMModGUI().
 {
     m_centerFrequency = centerFrequency;
     emit changedByAPI();
 }
setCenterFrequencyByCursor()
void ChannelMarker::setCenterFrequencyByCursor (int centerFrequency)
Definition at line 66 of file channelmarker.cpp.
References changedByCursor(), and m_centerFrequency.
 {
     m_centerFrequency = centerFrequency;
     emit changedByCursor();
 }
setColor()
void ChannelMarker::setColor (const QColor & color)
Definition at line 114 of file channelmarker.cpp.
References changedByAPI(), and m_color.
Referenced by BasicChannelSettingsDialog::accept(), AMDemodGUI::AMDemodGUI(), AMModGUI::AMModGUI(), ATVDemodGUI::ATVDemodGUI(), ATVModGUI::ATVModGUI(), BFMDemodGUI::BFMDemodGUI(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), DATVDemodGUI::DATVDemodGUI(), deserialize(), WFMDemodGUI::displaySettings(), LoRaDemodGUI::displaySettings(), NFMDemodGUI::displaySettings(), AMDemodGUI::displaySettings(), SSBDemodGUI::displaySettings(), FreqTrackerGUI::displaySettings(), LocalSinkGUI::displaySettings(), RemoteSinkGUI::displaySettings(), LocalSourceGUI::displaySettings(), UDPSourceGUI::displaySettings(), BFMDemodGUI::displaySettings(), NFMModGUI::displaySettings(), AMModGUI::displaySettings(), RemoteSourceGUI::displaySettings(), ATVModGUI::displaySettings(), WFMModGUI::displaySettings(), UDPSinkGUI::displaySettings(), ChannelAnalyzerGUI::displaySettings(), FreeDVModGUI::displaySettings(), SSBModGUI::displaySettings(), FreeDVDemodGUI::displaySettings(), FileSourceGUI::displaySettings(), DSDDemodGUI::displaySettings(), DATVDemodGUI::displaySettings(), DSDDemodGUI::DSDDemodGUI(), FileSourceGUI::FileSourceGUI(), FreqTrackerGUI::FreqTrackerGUI(), LocalSinkGUI::LocalSinkGUI(), LocalSourceGUI::LocalSourceGUI(), NFMDemodGUI::NFMDemodGUI(), NFMModGUI::NFMModGUI(), RemoteSinkGUI::RemoteSinkGUI(), RemoteSourceGUI::RemoteSourceGUI(), resetToDefaults(), SSBDemodGUI::SSBDemodGUI(), SSBModGUI::SSBModGUI(), UDPSinkGUI::UDPSinkGUI(), UDPSourceGUI::UDPSourceGUI(), WFMDemodGUI::WFMDemodGUI(), and WFMModGUI::WFMModGUI().
 {
     m_color = color;
     emit changedByAPI();
 }
setFrequencyScaleDisplayType()
void ChannelMarker::setFrequencyScaleDisplayType (frequencyScaleDisplay_t type) inline
Definition at line 69 of file channelmarker.h.
Referenced by BasicChannelSettingsDialog::accept(), deserialize(), and resetToDefaults().
 { m_fScaleDisplayType = type; }
setHighlighted()
void ChannelMarker::setHighlighted (bool highlighted)
Definition at line 102 of file channelmarker.cpp.
References changedByAPI(), and m_highlighted.
Referenced by WFMDemodGUI::enterEvent(), NFMDemodGUI::enterEvent(), AMDemodGUI::enterEvent(), SSBDemodGUI::enterEvent(), FreqTrackerGUI::enterEvent(), LocalSourceGUI::enterEvent(), LocalSinkGUI::enterEvent(), RemoteSinkGUI::enterEvent(), BFMDemodGUI::enterEvent(), UDPSourceGUI::enterEvent(), NFMModGUI::enterEvent(), RemoteSourceGUI::enterEvent(), AMModGUI::enterEvent(), WFMModGUI::enterEvent(), UDPSinkGUI::enterEvent(), ChannelAnalyzerGUI::enterEvent(), FreeDVDemodGUI::enterEvent(), FreeDVModGUI::enterEvent(), ATVDemodGUI::enterEvent(), ATVModGUI::enterEvent(), SSBModGUI::enterEvent(), FileSourceGUI::enterEvent(), DSDDemodGUI::enterEvent(), DATVDemodGUI::enterEvent(), WFMDemodGUI::leaveEvent(), NFMDemodGUI::leaveEvent(), AMDemodGUI::leaveEvent(), SSBDemodGUI::leaveEvent(), FreqTrackerGUI::leaveEvent(), RemoteSinkGUI::leaveEvent(), LocalSinkGUI::leaveEvent(), LocalSourceGUI::leaveEvent(), UDPSourceGUI::leaveEvent(), BFMDemodGUI::leaveEvent(), RemoteSourceGUI::leaveEvent(), NFMModGUI::leaveEvent(), AMModGUI::leaveEvent(), WFMModGUI::leaveEvent(), UDPSinkGUI::leaveEvent(), ChannelAnalyzerGUI::leaveEvent(), FreeDVDemodGUI::leaveEvent(), FreeDVModGUI::leaveEvent(), ATVDemodGUI::leaveEvent(), SSBModGUI::leaveEvent(), FileSourceGUI::leaveEvent(), ATVModGUI::leaveEvent(), DSDDemodGUI::leaveEvent(), and DATVDemodGUI::leaveEvent().
 {
     m_highlighted = highlighted;
     emit changedByAPI();
 }
setHighlightedByCursor()
void ChannelMarker::setHighlightedByCursor (bool highlighted)
Definition at line 108 of file channelmarker.cpp.
References highlightedByCursor(), and m_highlighted.
 {
     m_highlighted = highlighted;
     emit highlightedByCursor();
 }
setLowCutoff()
void ChannelMarker::setLowCutoff (int lowCutoff)
Definition at line 84 of file channelmarker.cpp.
References changedByAPI(), and m_lowCutoff.
Referenced by SSBDemodGUI::applyBandwidths(), SSBModGUI::applyBandwidths(), SSBDemodGUI::displaySettings(), ChannelAnalyzerGUI::displaySettings(), FreeDVModGUI::displaySettings(), FreeDVDemodGUI::displaySettings(), SSBModGUI::displaySettings(), FreeDVDemodGUI::on_freeDVMode_currentIndexChanged(), FreeDVModGUI::on_freeDVMode_currentIndexChanged(), and ChannelAnalyzerGUI::setFiltersUIBoundaries().
 {
     m_lowCutoff = lowCutoff;
     emit changedByAPI();
 }
setMovable()
void ChannelMarker::setMovable (bool movable) inline
Definition at line 66 of file channelmarker.h.
Referenced by LocalSinkGUI::displaySettings(), LocalSourceGUI::displaySettings(), RemoteSinkGUI::displaySettings(), FileSourceGUI::FileSourceGUI(), and LoRaDemodGUI::LoRaDemodGUI().
 { m_movable = movable; }
setOppositeBandwidth()
void ChannelMarker::setOppositeBandwidth (int bandwidth)
Definition at line 78 of file channelmarker.cpp.
References changedByAPI(), and m_oppositeBandwidth.
Referenced by ATVDemodGUI::setChannelMarkerBandwidth(), and ATVModGUI::setChannelMarkerBandwidth().
 {
     m_oppositeBandwidth = bandwidth;
     emit changedByAPI();
 }
setSidebands()
void ChannelMarker::setSidebands (sidebands_t sidebands)
Definition at line 90 of file channelmarker.cpp.
References changedByAPI(), and m_sidebands.
Referenced by SSBDemodGUI::applyBandwidths(), SSBModGUI::applyBandwidths(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), SSBDemodGUI::displaySettings(), ChannelAnalyzerGUI::displaySettings(), FreeDVModGUI::displaySettings(), SSBModGUI::displaySettings(), FreeDVDemodGUI::displaySettings(), FreeDVDemodGUI::on_freeDVMode_currentIndexChanged(), ATVDemodGUI::setChannelMarkerBandwidth(), ATVModGUI::setChannelMarkerBandwidth(), ChannelAnalyzerGUI::setFiltersUIBoundaries(), and SSBModGUI::SSBModGUI().
 {
     m_sidebands = sidebands;
     emit changedByAPI();
 }
setSourceOrSinkStream()
void ChannelMarker::setSourceOrSinkStream (bool sourceOrSinkStream) inline
Definition at line 75 of file channelmarker.h.
Referenced by AMModGUI::AMModGUI(), ATVModGUI::ATVModGUI(), FileSourceGUI::FileSourceGUI(), FreeDVModGUI::FreeDVModGUI(), LocalSourceGUI::LocalSourceGUI(), NFMModGUI::NFMModGUI(), RemoteSourceGUI::RemoteSourceGUI(), SSBModGUI::SSBModGUI(), UDPSourceGUI::UDPSourceGUI(), and WFMModGUI::WFMModGUI().
 { m_sourceOrSinkStream = sourceOrSinkStream; }
setStreamIndex()
void ChannelMarker::setStreamIndex (int streamIndex) inline
Definition at line 77 of file channelmarker.h.
Referenced by AMDemodGUI::onMenuDialogCalled().
 { m_streamIndex = streamIndex; }
setTitle()
void ChannelMarker::setTitle (const QString & title)
Definition at line 54 of file channelmarker.cpp.
References changedByAPI(), and m_title.
Referenced by BasicChannelSettingsDialog::accept(), AMDemodGUI::AMDemodGUI(), AMModGUI::AMModGUI(), ATVModGUI::ATVModGUI(), BFMDemodGUI::BFMDemodGUI(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), deserialize(), WFMDemodGUI::displaySettings(), NFMDemodGUI::displaySettings(), AMDemodGUI::displaySettings(), SSBDemodGUI::displaySettings(), FreqTrackerGUI::displaySettings(), LocalSinkGUI::displaySettings(), RemoteSinkGUI::displaySettings(), LocalSourceGUI::displaySettings(), BFMDemodGUI::displaySettings(), NFMModGUI::displaySettings(), AMModGUI::displaySettings(), RemoteSourceGUI::displaySettings(), WFMModGUI::displaySettings(), ATVModGUI::displaySettings(), UDPSinkGUI::displaySettings(), ChannelAnalyzerGUI::displaySettings(), FreeDVModGUI::displaySettings(), SSBModGUI::displaySettings(), FreeDVDemodGUI::displaySettings(), FileSourceGUI::displaySettings(), DSDDemodGUI::displaySettings(), DSDDemodGUI::DSDDemodGUI(), FileSourceGUI::FileSourceGUI(), FreqTrackerGUI::FreqTrackerGUI(), LocalSinkGUI::LocalSinkGUI(), LocalSourceGUI::LocalSourceGUI(), NFMDemodGUI::NFMDemodGUI(), NFMModGUI::NFMModGUI(), RemoteSinkGUI::RemoteSinkGUI(), RemoteSourceGUI::RemoteSourceGUI(), resetToDefaults(), SSBDemodGUI::SSBDemodGUI(), SSBModGUI::SSBModGUI(), UDPSinkGUI::UDPSinkGUI(), UDPSourceGUI::UDPSourceGUI(), WFMDemodGUI::WFMDemodGUI(), and WFMModGUI::WFMModGUI().
 {
     m_title = title;
     emit changedByAPI();
 }
setVisible()
void ChannelMarker::setVisible (bool visible)
Definition at line 96 of file channelmarker.cpp.
References changedByAPI(), and m_visible.
Referenced by AMDemodGUI::AMDemodGUI(), AMModGUI::AMModGUI(), ATVDemodGUI::ATVDemodGUI(), ATVModGUI::ATVModGUI(), BFMDemodGUI::BFMDemodGUI(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), DATVDemodGUI::DATVDemodGUI(), DSDDemodGUI::DSDDemodGUI(), FileSourceGUI::FileSourceGUI(), FreeDVDemodGUI::FreeDVDemodGUI(), FreeDVModGUI::FreeDVModGUI(), FreqTrackerGUI::FreqTrackerGUI(), LocalSinkGUI::LocalSinkGUI(), LocalSourceGUI::LocalSourceGUI(), LoRaDemodGUI::LoRaDemodGUI(), NFMDemodGUI::NFMDemodGUI(), NFMModGUI::NFMModGUI(), RemoteSinkGUI::RemoteSinkGUI(), RemoteSourceGUI::RemoteSourceGUI(), SSBDemodGUI::SSBDemodGUI(), SSBModGUI::SSBModGUI(), UDPSinkGUI::UDPSinkGUI(), UDPSourceGUI::UDPSourceGUI(), WFMDemodGUI::WFMDemodGUI(), and WFMModGUI::WFMModGUI().
 {
     m_visible = visible;
     emit changedByAPI();
 }
Member Data Documentation
m_bandwidth
int ChannelMarker::m_bandwidth protected
Definition at line 91 of file channelmarker.h.
Referenced by setBandwidth().
m_centerFrequency
int ChannelMarker::m_centerFrequency protected
Definition at line 90 of file channelmarker.h.
Referenced by setCenterFrequency(), and setCenterFrequencyByCursor().
m_color
QColor ChannelMarker::m_color protected
Definition at line 97 of file channelmarker.h.
Referenced by setColor().
m_colorTable
QRgb ChannelMarker::m_colorTable static protected
Initial value:
= {
    qRgb(0xc0, 0x00, 0x00),
    qRgb(0x00, 0xc0, 0x00),
    qRgb(0x00, 0x00, 0xc0),
    qRgb(0xc0, 0xc0, 0x00),
    qRgb(0xc0, 0x00, 0xc0),
    qRgb(0x00, 0xc0, 0xc0),
    qRgb(0xc0, 0x60, 0x00),
    qRgb(0xc0, 0x00, 0x60),
    qRgb(0x60, 0x00, 0xc0),
    qRgb(0x60, 0x00, 0x00),
    qRgb(0x00, 0x60, 0x00),
    qRgb(0x00, 0x00, 0x60),
    qRgb(0x60, 0x60, 0x00),
    qRgb(0x60, 0x00, 0x60),
    qRgb(0x00, 0x60, 0x60),
    0
}
Definition at line 84 of file channelmarker.h.
Referenced by ChannelMarker().
m_displayAddressReceive
QString ChannelMarker::m_displayAddressReceive protected
Definition at line 89 of file channelmarker.h.
m_displayAddressSend
QString ChannelMarker::m_displayAddressSend protected
Definition at line 88 of file channelmarker.h.
m_fScaleDisplayType
frequencyScaleDisplay_t ChannelMarker::m_fScaleDisplayType protected
Definition at line 99 of file channelmarker.h.
m_highlighted
bool ChannelMarker::m_highlighted protected
Definition at line 96 of file channelmarker.h.
Referenced by setHighlighted(), and setHighlightedByCursor().
m_lowCutoff
int ChannelMarker::m_lowCutoff protected
Definition at line 93 of file channelmarker.h.
Referenced by setLowCutoff().
m_movable
bool ChannelMarker::m_movable protected
Definition at line 98 of file channelmarker.h.
m_nextColor
int ChannelMarker::m_nextColor = 0 static protected
Definition at line 85 of file channelmarker.h.
Referenced by ChannelMarker().
m_oppositeBandwidth
int ChannelMarker::m_oppositeBandwidth protected
Definition at line 92 of file channelmarker.h.
Referenced by setOppositeBandwidth().
m_sidebands
sidebands_t ChannelMarker::m_sidebands protected
Definition at line 94 of file channelmarker.h.
Referenced by setSidebands().
m_sourceOrSinkStream
bool ChannelMarker::m_sourceOrSinkStream protected
Definition at line 100 of file channelmarker.h.
m_streamIndex
int ChannelMarker::m_streamIndex protected
Definition at line 101 of file channelmarker.h.
m_title
QString ChannelMarker::m_title protected
Definition at line 87 of file channelmarker.h.
Referenced by setTitle().
m_visible
bool ChannelMarker::m_visible protected
Definition at line 95 of file channelmarker.h.
Referenced by setVisible().
The documentation for this class was generated from the following files:
sdrbase/dsp/channelmarker.h
sdrbase/dsp/channelmarker.cpp