SDRAngel: qrtplib::RTPEndian Class Reference
qrtplib::RTPEndian Class Reference
#include <rtpendian.h>
Public Member Functions
RTPEndian ()
template<typename T >
T qToHost (const T &x) const
Private Attributes
bool m_isLittleEndian
Detailed Description
Definition at line 16 of file rtpendian.h.
Constructor & Destructor Documentation
RTPEndian()
qrtplib::RTPEndian::RTPEndian () inline
Definition at line 19 of file rtpendian.h.
References m_isLittleEndian.
     {
         uint32_t endianTest32 = 1;
         uint8_t *ptr = (uint8_t*) &endianTest32;
         m_isLittleEndian = (*ptr == 1);
     }
Member Function Documentation
qToHost()
template<typename T > T qrtplib::RTPEndian::qToHost (const T & x) const inline
Definition at line 27 of file rtpendian.h.
References m_isLittleEndian.
Referenced by qrtplib::RTPPacket::GetCSRC(), qrtplib::RTCPCompoundPacket::ParseData(), and qrtplib::RTPPacket::ParseRawPacket().
     {
         return m_isLittleEndian ? qToLittleEndian(x) : qToBigEndian(x);
     }
Member Data Documentation
m_isLittleEndian
bool qrtplib::RTPEndian::m_isLittleEndian private
Definition at line 33 of file rtpendian.h.
Referenced by qToHost(), and RTPEndian().
The documentation for this class was generated from the following file:
qrtplib/rtpendian.h