SDRAngel: SWGSDRangel::SWGInstanceChannelsResponse Class Reference
SWGSDRangel::SWGInstanceChannelsResponse Class Reference
#include <SWGInstanceChannelsResponse.h>
Public Member Functions
SWGInstanceChannelsResponse ()
SWGInstanceChannelsResponse (QString *json)
virtual ~SWGInstanceChannelsResponse ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGInstanceChannelsResponse * fromJson (QString &jsonString) override
qint32 getChannelcount ()
void setChannelcount (qint32 channelcount)
QList< SWGChannelListItem * > * getChannels ()
void setChannels (QList< SWGChannelListItem *> *channels)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 channelcount
bool m_channelcount_isSet
QList< SWGChannelListItem * > * channels
bool m_channels_isSet
Detailed Description
Definition at line 33 of file SWGInstanceChannelsResponse.h.
Constructor & Destructor Documentation
SWGInstanceChannelsResponse() [1/2]
SWGSDRangel::SWGInstanceChannelsResponse::SWGInstanceChannelsResponse ()
Definition at line 30 of file SWGInstanceChannelsResponse.cpp.
References channelcount, channels, m_channelcount_isSet, and m_channels_isSet.
{
     channelcount = 0;
     m_channelcount_isSet = false;
     channels = nullptr;
     m_channels_isSet = false;
 }
SWGInstanceChannelsResponse() [2/2]
SWGSDRangel::SWGInstanceChannelsResponse::SWGInstanceChannelsResponse (QString * json)
Definition at line 25 of file SWGInstanceChannelsResponse.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGInstanceChannelsResponse()
SWGSDRangel::SWGInstanceChannelsResponse::~SWGInstanceChannelsResponse () virtual
Definition at line 37 of file SWGInstanceChannelsResponse.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGInstanceChannelsResponse::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 79 of file SWGInstanceChannelsResponse.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::instanceChannelsService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGInstanceChannelsResponse::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 90 of file SWGInstanceChannelsResponse.cpp.
References channelcount, channels, m_channelcount_isSet, and SWGSDRangel::toJsonArray().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_channelcount_isSet){
         obj->insert("channelcount", QJsonValue(channelcount));
     }
     if(channels->size() > 0){
         toJsonArray((QList<void*>*)channels, obj, "channels", "SWGChannelListItem");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGInstanceChannelsResponse::cleanup ()
Definition at line 50 of file SWGInstanceChannelsResponse.cpp.
References channels.
Referenced by ~SWGInstanceChannelsResponse().
{
     if(channels != nullptr) {
         auto arr = channels;
         for(auto o: *arr) {
             delete o;
         }
         delete channels;
     }
 }
fromJson()
SWGInstanceChannelsResponse * SWGSDRangel::SWGInstanceChannelsResponse::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 62 of file SWGInstanceChannelsResponse.cpp.
References fromJsonObject().
Referenced by SWGInstanceChannelsResponse().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGInstanceChannelsResponse::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 71 of file SWGInstanceChannelsResponse.cpp.
References channelcount, channels, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&channelcount, pJson["channelcount"], "qint32", "");
     ::SWGSDRangel::setValue(&channels, pJson["channels"], "QList", "SWGChannelListItem");
 }
getChannelcount()
qint32 SWGSDRangel::SWGInstanceChannelsResponse::getChannelcount ()
Definition at line 103 of file SWGInstanceChannelsResponse.cpp.
References channelcount.
{
     return channelcount;
 }
getChannels()
QList< SWGChannelListItem * > * SWGSDRangel::SWGInstanceChannelsResponse::getChannels ()
Definition at line 113 of file SWGInstanceChannelsResponse.cpp.
References channels.
Referenced by WebAPIAdapterGUI::instanceChannels(), and WebAPIAdapterSrv::instanceChannels().
{
     return channels;
 }
init()
void SWGSDRangel::SWGInstanceChannelsResponse::init ()
Definition at line 42 of file SWGInstanceChannelsResponse.cpp.
References channelcount, channels, m_channelcount_isSet, and m_channels_isSet.
Referenced by WebAPIAdapterGUI::instanceChannels(), WebAPIAdapterSrv::instanceChannels(), and SWGInstanceChannelsResponse().
{
     channelcount = 0;
     m_channelcount_isSet = false;
     channels = new QList<SWGChannelListItem*>();
     m_channels_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGInstanceChannelsResponse::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 124 of file SWGInstanceChannelsResponse.cpp.
References channels, and m_channelcount_isSet.
{
     bool isObjectUpdated = false;
     do{
         if(m_channelcount_isSet){ isObjectUpdated = true; break;}
         if(channels->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setChannelcount()
void SWGSDRangel::SWGInstanceChannelsResponse::setChannelcount (qint32 channelcount)
Definition at line 107 of file SWGInstanceChannelsResponse.cpp.
References channelcount, and m_channelcount_isSet.
Referenced by WebAPIAdapterGUI::instanceChannels(), and WebAPIAdapterSrv::instanceChannels().
{
     this->channelcount = channelcount;
     this->m_channelcount_isSet = true;
 }
setChannels()
void SWGSDRangel::SWGInstanceChannelsResponse::setChannels (QList< SWGChannelListItem *> * channels)
Definition at line 117 of file SWGInstanceChannelsResponse.cpp.
References channels, and m_channels_isSet.
{
     this->channels = channels;
     this->m_channels_isSet = true;
 }
Member Data Documentation
channelcount
qint32 SWGSDRangel::SWGInstanceChannelsResponse::channelcount private
Definition at line 56 of file SWGInstanceChannelsResponse.h.
Referenced by asJsonObject(), fromJsonObject(), getChannelcount(), init(), setChannelcount(), and SWGInstanceChannelsResponse().
channels
QList<SWGChannelListItem*>* SWGSDRangel::SWGInstanceChannelsResponse::channels private
Definition at line 59 of file SWGInstanceChannelsResponse.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getChannels(), init(), isSet(), setChannels(), and SWGInstanceChannelsResponse().
m_channelcount_isSet
bool SWGSDRangel::SWGInstanceChannelsResponse::m_channelcount_isSet private
Definition at line 57 of file SWGInstanceChannelsResponse.h.
Referenced by asJsonObject(), init(), isSet(), setChannelcount(), and SWGInstanceChannelsResponse().
m_channels_isSet
bool SWGSDRangel::SWGInstanceChannelsResponse::m_channels_isSet private
Definition at line 60 of file SWGInstanceChannelsResponse.h.
Referenced by init(), setChannels(), and SWGInstanceChannelsResponse().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGInstanceChannelsResponse.h
swagger/sdrangel/code/qt5/client/SWGInstanceChannelsResponse.cpp