SDRAngel: LocalSourceThread Class Reference
LocalSourceThread Class Reference
#include <localsourcethread.h>
Inherits QThread.
Classes
class MsgStartStop
Public Slots
void pullSamples (unsigned int count)
Signals
void samplesAvailable (int offset)
Public Member Functions
LocalSourceThread (QObject *parent=0)
~LocalSourceThread ()
void startStop (bool start)
void setSampleFifo (SampleSourceFifo *sampleFifo)
Private Slots
void handleInputMessages ()
Private Member Functions
void startWork ()
void stopWork ()
void run ()
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
volatile bool m_running
SampleSourceFifo * m_sampleFifo
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 31 of file localsourcethread.h.
Constructor & Destructor Documentation
LocalSourceThread()
LocalSourceThread::LocalSourceThread (QObject * parent = 0)
Definition at line 24 of file localsourcethread.cpp.
Referenced by LocalSourceThread::MsgStartStop::MsgStartStop().
                                                     :
     QThread(parent),
     m_running(false),
     m_sampleFifo(0)
 {
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
 }
~LocalSourceThread()
LocalSourceThread::~LocalSourceThread ()
Definition at line 32 of file localsourcethread.cpp.
Referenced by LocalSourceThread::MsgStartStop::MsgStartStop().
 {
     qDebug("LocalSourceThread::~LocalSourceThread");
 }
Member Function Documentation
handleInputMessages
void LocalSourceThread::handleInputMessages () private slot
Definition at line 90 of file localsourcethread.cpp.
References LocalSourceThread::MsgStartStop::getStartStop(), m_inputMessageQueue, Message::match(), MessageQueue::pop(), startWork(), and stopWork().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (MsgStartStop::match(*message))
         {
             MsgStartStop* notif = (MsgStartStop*) message;
             qDebug("LocalSourceThread::handleInputMessages: MsgStartStop: %s", notif->getStartStop() ? "start" : "stop");
             if (notif->getStartStop()) {
                 startWork();
             } else {
                 stopWork();
             }
             delete message;
         }
     }
 }
pullSamples
void LocalSourceThread::pullSamples (unsigned int count) slot
Definition at line 48 of file localsourcethread.cpp.
References SampleSourceFifo::getIteratorOffset(), m_sampleFifo, SampleSourceFifo::readAdvance(), and samplesAvailable().
Referenced by LocalSourceThread::MsgStartStop::MsgStartStop().
 {
     SampleVector::iterator beginRead;
     m_sampleFifo->readAdvance(beginRead, count);
     emit samplesAvailable(m_sampleFifo->getIteratorOffset(beginRead));
 }
run()
void LocalSourceThread::run () private
Definition at line 75 of file localsourcethread.cpp.
References m_running, and m_startWaiter.
 {
     qDebug("LocalSinkThread::run: begin");
     m_running = true;
     m_startWaiter.wakeAll();
     while (m_running)
     {
         sleep(1); // Do nothing as everything is in the data handler (dequeuer)
     }
     m_running = false;
     qDebug("LocalSinkThread::run: end");
 }
samplesAvailable
void LocalSourceThread::samplesAvailable (int offset) signal
Referenced by LocalSourceThread::MsgStartStop::MsgStartStop(), and pullSamples().
setSampleFifo()
void LocalSourceThread::setSampleFifo (SampleSourceFifo * sampleFifo)
Definition at line 43 of file localsourcethread.cpp.
References m_sampleFifo.
Referenced by LocalSource::applySettings(), LocalSourceThread::MsgStartStop::MsgStartStop(), and LocalSource::start().
 {
     m_sampleFifo = sampleFifo;
 }
startStop()
void LocalSourceThread::startStop (bool start)
Definition at line 37 of file localsourcethread.cpp.
References LocalSourceThread::MsgStartStop::create(), m_inputMessageQueue, and MessageQueue::push().
Referenced by LocalSourceThread::MsgStartStop::MsgStartStop(), LocalSource::start(), and LocalSource::stop().
 {
     MsgStartStop *msg = MsgStartStop::create(start);
     m_inputMessageQueue.push(msg);
 }
startWork()
void LocalSourceThread::startWork () private
Definition at line 55 of file localsourcethread.cpp.
References m_running, m_startWaiter, and m_startWaitMutex.
Referenced by handleInputMessages().
 {
     qDebug("LocalSourceThread::startWork");
     m_startWaitMutex.lock();
     start();
     while(!m_running) {
         m_startWaiter.wait(&m_startWaitMutex, 100);
     }
     m_startWaitMutex.unlock();
 }
stopWork()
void LocalSourceThread::stopWork () private
Definition at line 68 of file localsourcethread.cpp.
References m_running.
Referenced by handleInputMessages().
 {
     qDebug("LocalSourceThread::stopWork");
     m_running = false;
     wait();
 }
Member Data Documentation
m_inputMessageQueue
MessageQueue LocalSourceThread::m_inputMessageQueue private
Definition at line 72 of file localsourcethread.h.
Referenced by handleInputMessages(), and startStop().
m_running
volatile bool LocalSourceThread::m_running private
Definition at line 69 of file localsourcethread.h.
Referenced by run(), startWork(), and stopWork().
m_sampleFifo
SampleSourceFifo* LocalSourceThread::m_sampleFifo private
Definition at line 70 of file localsourcethread.h.
Referenced by pullSamples(), and setSampleFifo().
m_startWaiter
QWaitCondition LocalSourceThread::m_startWaiter private
Definition at line 68 of file localsourcethread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex LocalSourceThread::m_startWaitMutex private
Definition at line 67 of file localsourcethread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/channeltx/localsource/localsourcethread.h
plugins/channeltx/localsource/localsourcethread.cpp