SDRAngel: SWGSDRangel::SWGPresetIdentifier Class Reference
SWGSDRangel::SWGPresetIdentifier Class Reference
#include <SWGPresetIdentifier.h>
Public Member Functions
SWGPresetIdentifier ()
SWGPresetIdentifier (QString *json)
virtual ~SWGPresetIdentifier ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGPresetIdentifier * fromJson (QString &jsonString) override
QString * getGroupName ()
void setGroupName (QString *group_name)
qint64 getCenterFrequency ()
void setCenterFrequency (qint64 center_frequency)
QString * getType ()
void setType (QString *type)
QString * getName ()
void setName (QString *name)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * group_name
bool m_group_name_isSet
qint64 center_frequency
bool m_center_frequency_isSet
QString * type
bool m_type_isSet
QString * name
bool m_name_isSet
Detailed Description
Definition at line 32 of file SWGPresetIdentifier.h.
Constructor & Destructor Documentation
SWGPresetIdentifier() [1/2]
SWGSDRangel::SWGPresetIdentifier::SWGPresetIdentifier ()
Definition at line 30 of file SWGPresetIdentifier.cpp.
References center_frequency, group_name, m_center_frequency_isSet, m_group_name_isSet, m_name_isSet, m_type_isSet, name, and type.
{
     group_name = nullptr;
     m_group_name_isSet = false;
     center_frequency = 0L;
     m_center_frequency_isSet = false;
     type = nullptr;
     m_type_isSet = false;
     name = nullptr;
     m_name_isSet = false;
 }
SWGPresetIdentifier() [2/2]
SWGSDRangel::SWGPresetIdentifier::SWGPresetIdentifier (QString * json)
Definition at line 25 of file SWGPresetIdentifier.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGPresetIdentifier()
SWGSDRangel::SWGPresetIdentifier::~SWGPresetIdentifier () virtual
Definition at line 41 of file SWGPresetIdentifier.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGPresetIdentifier::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 93 of file SWGPresetIdentifier.cpp.
References asJsonObject().
Referenced by SWGSDRangel::SWGInstanceApi::instancePresetDelete(), WebAPIRequestMapper::instancePresetFileService(), and WebAPIRequestMapper::instancePresetService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGPresetIdentifier::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 104 of file SWGPresetIdentifier.cpp.
References center_frequency, group_name, m_center_frequency_isSet, name, SWGSDRangel::toJsonValue(), and type.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(group_name != nullptr && *group_name != QString("")){
         toJsonValue(QString("groupName"), group_name, obj, QString("QString"));
     }
     if(m_center_frequency_isSet){
         obj->insert("centerFrequency", QJsonValue(center_frequency));
     }
     if(type != nullptr && *type != QString("")){
         toJsonValue(QString("type"), type, obj, QString("QString"));
     }
     if(name != nullptr && *name != QString("")){
         toJsonValue(QString("name"), name, obj, QString("QString"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGPresetIdentifier::cleanup ()
Definition at line 58 of file SWGPresetIdentifier.cpp.
References group_name, name, and type.
Referenced by ~SWGPresetIdentifier().
{
     if(group_name != nullptr) {
         delete group_name;
     }
     if(type != nullptr) {
         delete type;
     }
     if(name != nullptr) {
         delete name;
     }
 }
fromJson()
SWGPresetIdentifier * SWGSDRangel::SWGPresetIdentifier::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 72 of file SWGPresetIdentifier.cpp.
References fromJsonObject().
Referenced by WebAPIRequestMapper::instancePresetService(), and SWGPresetIdentifier().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGPresetIdentifier::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 81 of file SWGPresetIdentifier.cpp.
References center_frequency, group_name, name, SWGSDRangel::setValue(), and type.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&group_name, pJson["groupName"], "QString", "QString");
     ::SWGSDRangel::setValue(&center_frequency, pJson["centerFrequency"], "qint64", "");
     ::SWGSDRangel::setValue(&type, pJson["type"], "QString", "QString");
     ::SWGSDRangel::setValue(&name, pJson["name"], "QString", "QString");
 }
getCenterFrequency()
qint64 SWGSDRangel::SWGPresetIdentifier::getCenterFrequency ()
Definition at line 133 of file SWGPresetIdentifier.cpp.
References center_frequency.
Referenced by WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPut(), and WebAPIAdapterSrv::instancePresetPut().
{
     return center_frequency;
 }
getGroupName()
QString * SWGSDRangel::SWGPresetIdentifier::getGroupName ()
Definition at line 123 of file SWGPresetIdentifier.cpp.
References group_name.
Referenced by WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterSrv::instancePresetFilePut(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), and WebAPIRequestMapper::validatePresetIdentifer().
{
     return group_name;
 }
getName()
QString * SWGSDRangel::SWGPresetIdentifier::getName ()
Definition at line 153 of file SWGPresetIdentifier.cpp.
References name.
Referenced by WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterSrv::instancePresetFilePut(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), and WebAPIRequestMapper::validatePresetIdentifer().
{
     return name;
 }
getType()
QString * SWGSDRangel::SWGPresetIdentifier::getType ()
Definition at line 143 of file SWGPresetIdentifier.cpp.
References type.
Referenced by WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterSrv::instancePresetFilePut(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), and WebAPIRequestMapper::validatePresetIdentifer().
{
     return type;
 }
init()
void SWGSDRangel::SWGPresetIdentifier::init ()
Definition at line 46 of file SWGPresetIdentifier.cpp.
References center_frequency, group_name, m_center_frequency_isSet, m_group_name_isSet, m_name_isSet, m_type_isSet, name, and type.
Referenced by WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterSrv::instancePresetFilePut(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), and SWGPresetIdentifier().
{
     group_name = new QString("");
     m_group_name_isSet = false;
     center_frequency = 0L;
     m_center_frequency_isSet = false;
     type = new QString("");
     m_type_isSet = false;
     name = new QString("");
     m_name_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGPresetIdentifier::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 164 of file SWGPresetIdentifier.cpp.
References group_name, m_center_frequency_isSet, name, and type.
Referenced by SWGSDRangel::SWGPresetTransfer::asJsonObject(), SWGSDRangel::SWGPresetExport::asJsonObject(), SWGSDRangel::SWGPresetTransfer::isSet(), and SWGSDRangel::SWGPresetExport::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(group_name != nullptr && *group_name != QString("")){ isObjectUpdated = true; break;}
         if(m_center_frequency_isSet){ isObjectUpdated = true; break;}
         if(type != nullptr && *type != QString("")){ isObjectUpdated = true; break;}
         if(name != nullptr && *name != QString("")){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setCenterFrequency()
void SWGSDRangel::SWGPresetIdentifier::setCenterFrequency (qint64 center_frequency)
Definition at line 137 of file SWGPresetIdentifier.cpp.
References center_frequency, and m_center_frequency_isSet.
Referenced by WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterSrv::instancePresetFilePut(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), and WebAPIAdapterSrv::instancePresetPut().
{
     this->center_frequency = center_frequency;
     this->m_center_frequency_isSet = true;
 }
setGroupName()
void SWGSDRangel::SWGPresetIdentifier::setGroupName (QString * group_name)
Definition at line 127 of file SWGPresetIdentifier.cpp.
References group_name, and m_group_name_isSet.
{
     this->group_name = group_name;
     this->m_group_name_isSet = true;
 }
setName()
void SWGSDRangel::SWGPresetIdentifier::setName (QString * name)
Definition at line 157 of file SWGPresetIdentifier.cpp.
References m_name_isSet, and name.
{
     this->name = name;
     this->m_name_isSet = true;
 }
setType()
void SWGSDRangel::SWGPresetIdentifier::setType (QString * type)
Definition at line 147 of file SWGPresetIdentifier.cpp.
References m_type_isSet, and type.
{
     this->type = type;
     this->m_type_isSet = true;
 }
Member Data Documentation
center_frequency
qint64 SWGSDRangel::SWGPresetIdentifier::center_frequency private
Definition at line 64 of file SWGPresetIdentifier.h.
Referenced by asJsonObject(), fromJsonObject(), getCenterFrequency(), init(), setCenterFrequency(), and SWGPresetIdentifier().
group_name
QString* SWGSDRangel::SWGPresetIdentifier::group_name private
Definition at line 61 of file SWGPresetIdentifier.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getGroupName(), init(), isSet(), setGroupName(), and SWGPresetIdentifier().
m_center_frequency_isSet
bool SWGSDRangel::SWGPresetIdentifier::m_center_frequency_isSet private
Definition at line 65 of file SWGPresetIdentifier.h.
Referenced by asJsonObject(), init(), isSet(), setCenterFrequency(), and SWGPresetIdentifier().
m_group_name_isSet
bool SWGSDRangel::SWGPresetIdentifier::m_group_name_isSet private
Definition at line 62 of file SWGPresetIdentifier.h.
Referenced by init(), setGroupName(), and SWGPresetIdentifier().
m_name_isSet
bool SWGSDRangel::SWGPresetIdentifier::m_name_isSet private
Definition at line 71 of file SWGPresetIdentifier.h.
Referenced by init(), setName(), and SWGPresetIdentifier().
m_type_isSet
bool SWGSDRangel::SWGPresetIdentifier::m_type_isSet private
Definition at line 68 of file SWGPresetIdentifier.h.
Referenced by init(), setType(), and SWGPresetIdentifier().
name
QString* SWGSDRangel::SWGPresetIdentifier::name private
Definition at line 70 of file SWGPresetIdentifier.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getName(), init(), isSet(), setName(), and SWGPresetIdentifier().
type
QString* SWGSDRangel::SWGPresetIdentifier::type private
Definition at line 67 of file SWGPresetIdentifier.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getType(), init(), isSet(), setType(), and SWGPresetIdentifier().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGPresetIdentifier.h
swagger/sdrangel/code/qt5/client/SWGPresetIdentifier.cpp