SDRAngel: SWGSDRangel::SWGAMBEDevice Class Reference
SWGSDRangel::SWGAMBEDevice Class Reference
#include <SWGAMBEDevice.h>
Public Member Functions
SWGAMBEDevice ()
SWGAMBEDevice (QString *json)
virtual ~SWGAMBEDevice ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGAMBEDevice * fromJson (QString &jsonString) override
QString * getDeviceRef ()
void setDeviceRef (QString *device_ref)
qint32 getDelete ()
void setDelete (qint32 _delete)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * device_ref
bool m_device_ref_isSet
qint32 _delete
bool m__delete_isSet
Detailed Description
Definition at line 32 of file SWGAMBEDevice.h.
Constructor & Destructor Documentation
SWGAMBEDevice() [1/2]
SWGSDRangel::SWGAMBEDevice::SWGAMBEDevice ()
Definition at line 30 of file SWGAMBEDevice.cpp.
References _delete, device_ref, m__delete_isSet, and m_device_ref_isSet.
{
     device_ref = nullptr;
     m_device_ref_isSet = false;
     _delete = 0;
     m__delete_isSet = false;
 }
SWGAMBEDevice() [2/2]
SWGSDRangel::SWGAMBEDevice::SWGAMBEDevice (QString * json)
Definition at line 25 of file SWGAMBEDevice.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGAMBEDevice()
SWGSDRangel::SWGAMBEDevice::~SWGAMBEDevice () virtual
Definition at line 37 of file SWGAMBEDevice.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGAMBEDevice::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 75 of file SWGAMBEDevice.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGAMBEDevice::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 86 of file SWGAMBEDevice.cpp.
References _delete, device_ref, m__delete_isSet, and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(device_ref != nullptr && *device_ref != QString("")){
         toJsonValue(QString("deviceRef"), device_ref, obj, QString("QString"));
     }
     if(m__delete_isSet){
         obj->insert("delete", QJsonValue(_delete));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGAMBEDevice::cleanup ()
Definition at line 50 of file SWGAMBEDevice.cpp.
References device_ref.
Referenced by ~SWGAMBEDevice().
{
     if(device_ref != nullptr) {
         delete device_ref;
     }
 }
fromJson()
SWGAMBEDevice * SWGSDRangel::SWGAMBEDevice::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 58 of file SWGAMBEDevice.cpp.
References fromJsonObject().
Referenced by SWGAMBEDevice().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGAMBEDevice::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 67 of file SWGAMBEDevice.cpp.
References _delete, device_ref, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&device_ref, pJson["deviceRef"], "QString", "QString");
     ::SWGSDRangel::setValue(&_delete, pJson["delete"], "qint32", "");
 }
getDelete()
qint32 SWGSDRangel::SWGAMBEDevice::getDelete ()
Definition at line 109 of file SWGAMBEDevice.cpp.
References _delete.
{
     return _delete;
 }
getDeviceRef()
QString * SWGSDRangel::SWGAMBEDevice::getDeviceRef ()
Definition at line 99 of file SWGAMBEDevice.cpp.
References device_ref.
{
     return device_ref;
 }
init()
void SWGSDRangel::SWGAMBEDevice::init ()
Definition at line 42 of file SWGAMBEDevice.cpp.
References _delete, device_ref, m__delete_isSet, and m_device_ref_isSet.
Referenced by SWGAMBEDevice().
                     {
     device_ref = new QString("");
     m_device_ref_isSet = false;
     _delete = 0;
     m__delete_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGAMBEDevice::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 120 of file SWGAMBEDevice.cpp.
References device_ref, and m__delete_isSet.
                     {
     bool isObjectUpdated = false;
     do{
         if(device_ref != nullptr && *device_ref != QString("")){ isObjectUpdated = true; break;}
         if(m__delete_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setDelete()
void SWGSDRangel::SWGAMBEDevice::setDelete (qint32 _delete)
Definition at line 113 of file SWGAMBEDevice.cpp.
References _delete, and m__delete_isSet.
{
     this->_delete = _delete;
     this->m__delete_isSet = true;
 }
setDeviceRef()
void SWGSDRangel::SWGAMBEDevice::setDeviceRef (QString * device_ref)
Definition at line 103 of file SWGAMBEDevice.cpp.
References device_ref, and m_device_ref_isSet.
{
     this->device_ref = device_ref;
     this->m_device_ref_isSet = true;
 }
Member Data Documentation
_delete
qint32 SWGSDRangel::SWGAMBEDevice::_delete private
Definition at line 58 of file SWGAMBEDevice.h.
Referenced by asJsonObject(), fromJsonObject(), getDelete(), init(), setDelete(), and SWGAMBEDevice().
device_ref
QString* SWGSDRangel::SWGAMBEDevice::device_ref private
Definition at line 55 of file SWGAMBEDevice.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getDeviceRef(), init(), isSet(), setDeviceRef(), and SWGAMBEDevice().
m__delete_isSet
bool SWGSDRangel::SWGAMBEDevice::m__delete_isSet private
Definition at line 59 of file SWGAMBEDevice.h.
Referenced by asJsonObject(), init(), isSet(), setDelete(), and SWGAMBEDevice().
m_device_ref_isSet
bool SWGSDRangel::SWGAMBEDevice::m_device_ref_isSet private
Definition at line 56 of file SWGAMBEDevice.h.
Referenced by init(), setDeviceRef(), and SWGAMBEDevice().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGAMBEDevice.h
swagger/sdrangel/code/qt5/client/SWGAMBEDevice.cpp