SDRAngel: ItemSettingGUI Class Reference
ItemSettingGUI Class Reference abstract
#include <itemsettinggui.h>
Signals
void valueChanged (double value)
Public Member Functions
ItemSettingGUI (QWidget *parent=0)
virtual ~ItemSettingGUI ()
virtual double getCurrentValue ()=0
virtual void setValue (double value)=0
Detailed Description
Definition at line 27 of file itemsettinggui.h.
Constructor & Destructor Documentation
ItemSettingGUI()
ItemSettingGUI::ItemSettingGUI (QWidget * parent = 0) explicit
Definition at line 10 of file itemsettinggui.cpp.
 : QWidget(parent) {}
~ItemSettingGUI()
virtual ItemSettingGUI::~ItemSettingGUI () inline virtual
Definition at line 32 of file itemsettinggui.h.
References SWGSDRangel::setValue().
 {}
Member Function Documentation
getCurrentValue()
virtual double ItemSettingGUI::getCurrentValue () pure virtual
Implemented in IntervalRangeGUI, DiscreteRangeGUI, and IntervalSliderGUI.
Referenced by SoapySDRInputGui::displaySettings(), and SoapySDROutputGui::displaySettings().
setValue()
virtual void ItemSettingGUI::setValue (double value) pure virtual
Implemented in IntervalRangeGUI, DiscreteRangeGUI, and IntervalSliderGUI.
Referenced by SoapySDRInputGui::displaySettings(), and SoapySDROutputGui::displaySettings().
valueChanged
void ItemSettingGUI::valueChanged (double value) signal
Referenced by IntervalSliderGUI::on_intervalSlider_valueChanged(), DiscreteRangeGUI::on_rangeCombo_currentIndexChanged(), IntervalRangeGUI::on_rangeInterval_currentIndexChanged(), and IntervalRangeGUI::on_value_changed().
The documentation for this class was generated from the following files:
sdrgui/soapygui/itemsettinggui.h
sdrgui/soapygui/itemsettinggui.cpp