SDRAngel: DeviceBladeRF1 Class Reference
DeviceBladeRF1 Class Reference
#include <devicebladerf1.h>
Static Public Member Functions
static bool open_bladerf (struct bladerf **dev, const char *serial)
Static Private Member Functions
static struct bladerf * open_bladerf_from_serial (const char *serial)
Detailed Description
Definition at line 25 of file devicebladerf1.h.
Member Function Documentation
open_bladerf()
bool DeviceBladeRF1::open_bladerf (struct bladerf ** dev, const char * serial) static
Definition at line 25 of file devicebladerf1.cpp.
References open_bladerf_from_serial().
Referenced by Bladerf1Output::openDevice(), and Bladerf1Input::openDevice().
 {
     int fpga_loaded;
     if ((*dev = open_bladerf_from_serial(serial)) == 0)
     {
         qCritical("DeviceBladeRF::open_bladerf: could not open BladeRF");
         return false;
     }
     fpga_loaded = bladerf_is_fpga_configured(*dev);
     if (fpga_loaded < 0)
     {
         qCritical("DeviceBladeRF::open_bladerf: failed to check FPGA state: %s",
                 bladerf_strerror(fpga_loaded));
         return false;
     }
     else if (fpga_loaded == 0)
     {
         qCritical("BladerfOutput::start: the device's FPGA is not loaded.");
         return false;
     }
     return true;
 }
open_bladerf_from_serial()
struct bladerf * DeviceBladeRF1::open_bladerf_from_serial (const char * serial) static private
Definition at line 52 of file devicebladerf1.cpp.
References BladerfBandwidths::m_halfbw, and BladerfBandwidths::m_nb_halfbw.
Referenced by open_bladerf().
 {
     int status;
     struct bladerf *dev;
     struct bladerf_devinfo info;
     /* Initialize all fields to "don't care" wildcard values.
      *
      * Immediately passing this to bladerf_open_with_devinfo() would cause
      * libbladeRF to open any device on any available backend. */
     bladerf_init_devinfo(&info);
     /* Specify the desired device's serial number, while leaving all other
      * fields in the info structure wildcard values */
     if (serial != 0)
     {
         strncpy(info.serial, serial, BLADERF_SERIAL_LENGTH - 1);
         info.serial[BLADERF_SERIAL_LENGTH - 1] = '\0';
     }
     status = bladerf_open_with_devinfo(&dev, &info);
     if (status == BLADERF_ERR_NODEV)
     {
         qCritical("DeviceBladeRF::open_bladerf_from_serial: No devices available with serial %s", serial);
         return 0;
     }
     else if (status != 0)
     {
         qCritical("DeviceBladeRF::open_bladerf_from_serial: Failed to open device with serial %s (%s)",
                 serial, bladerf_strerror(status));
         return 0;
     }
     else
     {
         return dev;
     }
 }
The documentation for this class was generated from the following files:
devices/bladerf1/devicebladerf1.h
devices/bladerf1/devicebladerf1.cpp