SDRAngel: UDPSource::MsgConfigureUDPSource Class Reference
UDPSource::MsgConfigureUDPSource Class Reference
#include <udpsource.h>
Public Member Functions
const UDPSourceSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureUDPSource * create (const UDPSourceSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureUDPSource (const UDPSourceSettings &settings, bool force)
Private Attributes
UDPSourceSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 46 of file udpsource.h.
Constructor & Destructor Documentation
MsgConfigureUDPSource()
UDPSource::MsgConfigureUDPSource::MsgConfigureUDPSource (const UDPSourceSettings & settings, bool force) inline private
Definition at line 62 of file udpsource.h.
Referenced by create().
                                                                              :
             Message(),
             m_settings(settings),
             m_force(force)
         {
         }
Member Function Documentation
create()
static MsgConfigureUDPSource* UDPSource::MsgConfigureUDPSource::create (const UDPSourceSettings & settings, bool force) inline static
Definition at line 53 of file udpsource.h.
References MsgConfigureUDPSource().
Referenced by UDPSourceGUI::applySettings(), UDPSource::deserialize(), and UDPSource::webapiSettingsPutPatch().
         {
             return new MsgConfigureUDPSource(settings, force);
         }
getForce()
bool UDPSource::MsgConfigureUDPSource::getForce () const inline
Definition at line 51 of file udpsource.h.
References m_force.
Referenced by UDPSource::handleMessage().
 { return m_force; }
getSettings()
const UDPSourceSettings& UDPSource::MsgConfigureUDPSource::getSettings () const inline
Definition at line 50 of file udpsource.h.
References m_settings.
Referenced by UDPSourceGUI::handleMessage(), and UDPSource::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool UDPSource::MsgConfigureUDPSource::m_force private
Definition at line 60 of file udpsource.h.
Referenced by getForce().
m_settings
UDPSourceSettings UDPSource::MsgConfigureUDPSource::m_settings private
Definition at line 59 of file udpsource.h.
Referenced by UDPSource::getCenterFrequency(), getSettings(), UDPSource::getStreamCenterFrequency(), and UDPSource::getTitle().
The documentation for this class was generated from the following file:
plugins/channeltx/udpsource/udpsource.h