SDRAngel: SWGSDRangel::SWGDeviceSet Class Reference
SWGSDRangel::SWGDeviceSet Class Reference
#include <SWGDeviceSet.h>
Public Member Functions
SWGDeviceSet ()
SWGDeviceSet (QString *json)
virtual ~SWGDeviceSet ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGDeviceSet * fromJson (QString &jsonString) override
SWGSamplingDevice * getSamplingDevice ()
void setSamplingDevice (SWGSamplingDevice *sampling_device)
qint32 getChannelcount ()
void setChannelcount (qint32 channelcount)
QList< SWGChannel * > * getChannels ()
void setChannels (QList< SWGChannel *> *channels)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
SWGSamplingDevice * sampling_device
bool m_sampling_device_isSet
qint32 channelcount
bool m_channelcount_isSet
QList< SWGChannel * > * channels
bool m_channels_isSet
Detailed Description
Definition at line 34 of file SWGDeviceSet.h.
Constructor & Destructor Documentation
SWGDeviceSet() [1/2]
SWGSDRangel::SWGDeviceSet::SWGDeviceSet ()
Definition at line 30 of file SWGDeviceSet.cpp.
References channelcount, channels, m_channelcount_isSet, m_channels_isSet, m_sampling_device_isSet, and sampling_device.
{
     sampling_device = nullptr;
     m_sampling_device_isSet = false;
     channelcount = 0;
     m_channelcount_isSet = false;
     channels = nullptr;
     m_channels_isSet = false;
 }
SWGDeviceSet() [2/2]
SWGSDRangel::SWGDeviceSet::SWGDeviceSet (QString * json)
Definition at line 25 of file SWGDeviceSet.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGDeviceSet()
SWGSDRangel::SWGDeviceSet::~SWGDeviceSet () virtual
Definition at line 39 of file SWGDeviceSet.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGDeviceSet::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 88 of file SWGDeviceSet.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::devicesetService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGDeviceSet::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 99 of file SWGDeviceSet.cpp.
References channelcount, channels, SWGSDRangel::SWGSamplingDevice::isSet(), m_channelcount_isSet, sampling_device, SWGSDRangel::toJsonArray(), and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if((sampling_device != nullptr) && (sampling_device->isSet())){
         toJsonValue(QString("samplingDevice"), sampling_device, obj, QString("SWGSamplingDevice"));
     }
     if(m_channelcount_isSet){
         obj->insert("channelcount", QJsonValue(channelcount));
     }
     if(channels->size() > 0){
         toJsonArray((QList<void*>*)channels, obj, "channels", "SWGChannel");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGDeviceSet::cleanup ()
Definition at line 54 of file SWGDeviceSet.cpp.
References channels, and sampling_device.
Referenced by ~SWGDeviceSet().
                       {
     if(sampling_device != nullptr) {
         delete sampling_device;
     }
     if(channels != nullptr) {
         auto arr = channels;
         for(auto o: *arr) {
             delete o;
         }
         delete channels;
     }
 }
fromJson()
SWGDeviceSet * SWGSDRangel::SWGDeviceSet::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 69 of file SWGDeviceSet.cpp.
References fromJsonObject().
Referenced by SWGDeviceSet().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGDeviceSet::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 78 of file SWGDeviceSet.cpp.
References channelcount, channels, sampling_device, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&sampling_device, pJson["samplingDevice"], "SWGSamplingDevice", "SWGSamplingDevice");
     ::SWGSDRangel::setValue(&channelcount, pJson["channelcount"], "qint32", "");
     ::SWGSDRangel::setValue(&channels, pJson["channels"], "QList", "SWGChannel");
 }
getChannelcount()
qint32 SWGSDRangel::SWGDeviceSet::getChannelcount ()
Definition at line 125 of file SWGDeviceSet.cpp.
References channelcount.
Referenced by WebAPIAdapterGUI::getDeviceSet(), and WebAPIAdapterSrv::getDeviceSet().
{
     return channelcount;
 }
getChannels()
QList< SWGChannel * > * SWGSDRangel::SWGDeviceSet::getChannels ()
Definition at line 135 of file SWGDeviceSet.cpp.
References channels.
Referenced by WebAPIAdapterGUI::getDeviceSet(), and WebAPIAdapterSrv::getDeviceSet().
{
     return channels;
 }
getSamplingDevice()
SWGSamplingDevice * SWGSDRangel::SWGDeviceSet::getSamplingDevice ()
Definition at line 115 of file SWGDeviceSet.cpp.
References sampling_device.
Referenced by WebAPIAdapterGUI::getDeviceSet(), and WebAPIAdapterSrv::getDeviceSet().
{
     return sampling_device;
 }
init()
void SWGSDRangel::SWGDeviceSet::init ()
Definition at line 44 of file SWGDeviceSet.cpp.
References channelcount, channels, m_channelcount_isSet, m_channels_isSet, m_sampling_device_isSet, and sampling_device.
Referenced by WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), and SWGDeviceSet().
                    {
     sampling_device = new SWGSamplingDevice();
     m_sampling_device_isSet = false;
     channelcount = 0;
     m_channelcount_isSet = false;
     channels = new QList<SWGChannel*>();
     m_channels_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGDeviceSet::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 146 of file SWGDeviceSet.cpp.
References channels, SWGSDRangel::SWGSamplingDevice::isSet(), m_channelcount_isSet, and sampling_device.
                    {
     bool isObjectUpdated = false;
     do{
         if(sampling_device != nullptr && sampling_device->isSet()){ isObjectUpdated = true; break;}
         if(m_channelcount_isSet){ isObjectUpdated = true; break;}
         if(channels->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setChannelcount()
void SWGSDRangel::SWGDeviceSet::setChannelcount (qint32 channelcount)
Definition at line 129 of file SWGDeviceSet.cpp.
References channelcount, and m_channelcount_isSet.
Referenced by WebAPIAdapterGUI::getDeviceSet(), and WebAPIAdapterSrv::getDeviceSet().
{
     this->channelcount = channelcount;
     this->m_channelcount_isSet = true;
 }
setChannels()
void SWGSDRangel::SWGDeviceSet::setChannels (QList< SWGChannel *> * channels)
Definition at line 139 of file SWGDeviceSet.cpp.
References channels, and m_channels_isSet.
{
     this->channels = channels;
     this->m_channels_isSet = true;
 }
setSamplingDevice()
void SWGSDRangel::SWGDeviceSet::setSamplingDevice (SWGSamplingDevice * sampling_device)
Definition at line 119 of file SWGDeviceSet.cpp.
References m_sampling_device_isSet, and sampling_device.
{
     this->sampling_device = sampling_device;
     this->m_sampling_device_isSet = true;
 }
Member Data Documentation
channelcount
qint32 SWGSDRangel::SWGDeviceSet::channelcount private
Definition at line 63 of file SWGDeviceSet.h.
Referenced by asJsonObject(), fromJsonObject(), getChannelcount(), init(), setChannelcount(), and SWGDeviceSet().
channels
QList<SWGChannel*>* SWGSDRangel::SWGDeviceSet::channels private
Definition at line 66 of file SWGDeviceSet.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getChannels(), init(), isSet(), setChannels(), and SWGDeviceSet().
m_channelcount_isSet
bool SWGSDRangel::SWGDeviceSet::m_channelcount_isSet private
Definition at line 64 of file SWGDeviceSet.h.
Referenced by asJsonObject(), init(), isSet(), setChannelcount(), and SWGDeviceSet().
m_channels_isSet
bool SWGSDRangel::SWGDeviceSet::m_channels_isSet private
Definition at line 67 of file SWGDeviceSet.h.
Referenced by init(), setChannels(), and SWGDeviceSet().
m_sampling_device_isSet
bool SWGSDRangel::SWGDeviceSet::m_sampling_device_isSet private
Definition at line 61 of file SWGDeviceSet.h.
Referenced by init(), setSamplingDevice(), and SWGDeviceSet().
sampling_device
SWGSamplingDevice* SWGSDRangel::SWGDeviceSet::sampling_device private
Definition at line 60 of file SWGDeviceSet.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSamplingDevice(), init(), isSet(), setSamplingDevice(), and SWGDeviceSet().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGDeviceSet.h
swagger/sdrangel/code/qt5/client/SWGDeviceSet.cpp