SDRAngel: SWGSDRangel::SWGLocationInformation Class Reference
SWGSDRangel::SWGLocationInformation Class Reference
#include <SWGLocationInformation.h>
Public Member Functions
SWGLocationInformation ()
SWGLocationInformation (QString *json)
virtual ~SWGLocationInformation ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGLocationInformation * fromJson (QString &jsonString) override
float getLatitude ()
void setLatitude (float latitude)
float getLongitude ()
void setLongitude (float longitude)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
float latitude
bool m_latitude_isSet
float longitude
bool m_longitude_isSet
Detailed Description
Definition at line 31 of file SWGLocationInformation.h.
Constructor & Destructor Documentation
SWGLocationInformation() [1/2]
SWGSDRangel::SWGLocationInformation::SWGLocationInformation ()
Definition at line 30 of file SWGLocationInformation.cpp.
References latitude, longitude, m_latitude_isSet, and m_longitude_isSet.
{
     latitude = 0.0f;
     m_latitude_isSet = false;
     longitude = 0.0f;
     m_longitude_isSet = false;
 }
SWGLocationInformation() [2/2]
SWGSDRangel::SWGLocationInformation::SWGLocationInformation (QString * json)
Definition at line 25 of file SWGLocationInformation.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGLocationInformation()
SWGSDRangel::SWGLocationInformation::~SWGLocationInformation () virtual
Definition at line 37 of file SWGLocationInformation.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGLocationInformation::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 73 of file SWGLocationInformation.cpp.
References asJsonObject().
Referenced by SWGSDRangel::SWGInstanceApi::instanceLocationPut(), and WebAPIRequestMapper::instanceLocationService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGLocationInformation::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 84 of file SWGLocationInformation.cpp.
References latitude, longitude, m_latitude_isSet, and m_longitude_isSet.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_latitude_isSet){
         obj->insert("latitude", QJsonValue(latitude));
     }
     if(m_longitude_isSet){
         obj->insert("longitude", QJsonValue(longitude));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGLocationInformation::cleanup ()
Definition at line 50 of file SWGLocationInformation.cpp.
Referenced by ~SWGLocationInformation().
{
 }
fromJson()
SWGLocationInformation * SWGSDRangel::SWGLocationInformation::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 56 of file SWGLocationInformation.cpp.
References fromJsonObject().
Referenced by WebAPIRequestMapper::instanceLocationService(), and SWGLocationInformation().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGLocationInformation::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 65 of file SWGLocationInformation.cpp.
References latitude, longitude, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&latitude, pJson["latitude"], "float", "");
     ::SWGSDRangel::setValue(&longitude, pJson["longitude"], "float", "");
 }
getLatitude()
float SWGSDRangel::SWGLocationInformation::getLatitude ()
Definition at line 97 of file SWGLocationInformation.cpp.
References latitude.
Referenced by WebAPIAdapterGUI::instanceLocationPut(), and WebAPIAdapterSrv::instanceLocationPut().
{
     return latitude;
 }
getLongitude()
float SWGSDRangel::SWGLocationInformation::getLongitude ()
Definition at line 107 of file SWGLocationInformation.cpp.
References longitude.
Referenced by WebAPIAdapterGUI::instanceLocationPut(), and WebAPIAdapterSrv::instanceLocationPut().
{
     return longitude;
 }
init()
void SWGSDRangel::SWGLocationInformation::init ()
Definition at line 42 of file SWGLocationInformation.cpp.
References latitude, longitude, m_latitude_isSet, and m_longitude_isSet.
Referenced by WebAPIAdapterGUI::instanceLocationGet(), WebAPIAdapterSrv::instanceLocationGet(), and SWGLocationInformation().
{
     latitude = 0.0f;
     m_latitude_isSet = false;
     longitude = 0.0f;
     m_longitude_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGLocationInformation::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 118 of file SWGLocationInformation.cpp.
References m_latitude_isSet, and m_longitude_isSet.
{
     bool isObjectUpdated = false;
     do{
         if(m_latitude_isSet){ isObjectUpdated = true; break;}
         if(m_longitude_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setLatitude()
void SWGSDRangel::SWGLocationInformation::setLatitude (float latitude)
Definition at line 101 of file SWGLocationInformation.cpp.
References latitude, and m_latitude_isSet.
Referenced by WebAPIAdapterGUI::instanceLocationGet(), WebAPIAdapterSrv::instanceLocationGet(), WebAPIAdapterSrv::instanceLocationPut(), and WebAPIAdapterGUI::instanceLocationPut().
{
     this->latitude = latitude;
     this->m_latitude_isSet = true;
 }
setLongitude()
void SWGSDRangel::SWGLocationInformation::setLongitude (float longitude)
Definition at line 111 of file SWGLocationInformation.cpp.
References longitude, and m_longitude_isSet.
Referenced by WebAPIAdapterGUI::instanceLocationGet(), WebAPIAdapterSrv::instanceLocationGet(), WebAPIAdapterSrv::instanceLocationPut(), and WebAPIAdapterGUI::instanceLocationPut().
{
     this->longitude = longitude;
     this->m_longitude_isSet = true;
 }
Member Data Documentation
latitude
float SWGSDRangel::SWGLocationInformation::latitude private
Definition at line 54 of file SWGLocationInformation.h.
Referenced by asJsonObject(), fromJsonObject(), getLatitude(), init(), setLatitude(), and SWGLocationInformation().
longitude
float SWGSDRangel::SWGLocationInformation::longitude private
Definition at line 57 of file SWGLocationInformation.h.
Referenced by asJsonObject(), fromJsonObject(), getLongitude(), init(), setLongitude(), and SWGLocationInformation().
m_latitude_isSet
bool SWGSDRangel::SWGLocationInformation::m_latitude_isSet private
Definition at line 55 of file SWGLocationInformation.h.
Referenced by asJsonObject(), init(), isSet(), setLatitude(), and SWGLocationInformation().
m_longitude_isSet
bool SWGSDRangel::SWGLocationInformation::m_longitude_isSet private
Definition at line 58 of file SWGLocationInformation.h.
Referenced by asJsonObject(), init(), isSet(), setLongitude(), and SWGLocationInformation().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGLocationInformation.h
swagger/sdrangel/code/qt5/client/SWGLocationInformation.cpp