SDRAngel: TestMI::MsgFileRecord Class Reference
TestMI::MsgFileRecord Class Reference
#include <testmi.h>
Public Member Functions
bool getStartStop () const
int getStreamIndex () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgFileRecord * create (bool startStop, int streamIndex)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgFileRecord (bool startStop, int streamIndex)
Protected Attributes
bool m_startStop
int m_streamIndex
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 61 of file testmi.h.
Constructor & Destructor Documentation
MsgFileRecord()
TestMI::MsgFileRecord::MsgFileRecord (bool startStop, int streamIndex) inline protected
Definition at line 76 of file testmi.h.
                                                        :
             Message(),
             m_startStop(startStop),
             m_streamIndex(streamIndex)
         { }
Member Function Documentation
create()
static MsgFileRecord* TestMI::MsgFileRecord::create (bool startStop, int streamIndex) inline static
Definition at line 68 of file testmi.h.
Referenced by TestMIGui::on_record_toggled().
{
             return new MsgFileRecord(startStop, streamIndex);
         }
getStartStop()
bool TestMI::MsgFileRecord::getStartStop () const inline
Definition at line 65 of file testmi.h.
Referenced by TestMI::handleMessage().
 { return m_startStop; }
getStreamIndex()
int TestMI::MsgFileRecord::getStreamIndex () const inline
Definition at line 66 of file testmi.h.
Referenced by TestMI::handleMessage().
 { return m_streamIndex; }
Member Data Documentation
m_startStop
bool TestMI::MsgFileRecord::m_startStop protected
Definition at line 73 of file testmi.h.
m_streamIndex
int TestMI::MsgFileRecord::m_streamIndex protected
Definition at line 74 of file testmi.h.
The documentation for this class was generated from the following file:
plugins/samplemimo/testmi/testmi.h