SDRAngel: LoRaDemod::MsgConfigureChannelizer Class Reference
LoRaDemod::MsgConfigureChannelizer Class Reference
#include <lorademod.h>
Public Member Functions
int getSampleRate () const
int getCenterFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (int sampleRate, int centerFrequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (int sampleRate, int centerFrequency)
Private Attributes
int m_sampleRate
int m_centerFrequency
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 69 of file lorademod.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
LoRaDemod::MsgConfigureChannelizer::MsgConfigureChannelizer (int sampleRate, int centerFrequency) inline private
Definition at line 85 of file lorademod.h.
References LoRaDemod::LoRaDemod(), and LoRaDemod::~LoRaDemod().
                                                                      :
             Message(),
             m_sampleRate(sampleRate),
             m_centerFrequency(centerFrequency)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* LoRaDemod::MsgConfigureChannelizer::create (int sampleRate, int centerFrequency) inline static
Definition at line 76 of file lorademod.h.
Referenced by LoRaDemodGUI::applySettings().
         {
             return new MsgConfigureChannelizer(sampleRate, centerFrequency);
         }
getCenterFrequency()
int LoRaDemod::MsgConfigureChannelizer::getCenterFrequency () const inline
Definition at line 74 of file lorademod.h.
Referenced by LoRaDemod::handleMessage().
 { return m_centerFrequency; }
getSampleRate()
int LoRaDemod::MsgConfigureChannelizer::getSampleRate () const inline
Definition at line 73 of file lorademod.h.
References LoRaDemod::m_sampleRate.
Referenced by LoRaDemod::handleMessage().
 { return m_sampleRate; }
Member Data Documentation
m_centerFrequency
int LoRaDemod::MsgConfigureChannelizer::m_centerFrequency private
Definition at line 83 of file lorademod.h.
m_sampleRate
int LoRaDemod::MsgConfigureChannelizer::m_sampleRate private
Definition at line 82 of file lorademod.h.
The documentation for this class was generated from the following file:
plugins/channelrx/demodlora/lorademod.h