SDRAngel: sdrbase/util/fixed.h File Reference
fixed.h File Reference
#include <ostream>
#include <complex>
#include <limits>
#include <stdint.h>
#include "fixedtraits.h"
Classes
class Fixed< IntType, IntBits >
struct Fixed< IntType, IntBits >::internal
Functions
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (double a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (float a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (uint64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (int64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (unsigned a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (int a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (unsigned short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (unsigned char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (Fixed< IntType, IntBits > const &a, double b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (Fixed< IntType, IntBits > const &a, float b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (Fixed< IntType, IntBits > const &a, uint64_t b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (Fixed< IntType, IntBits > const &a, int64_t b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (Fixed< IntType, IntBits > const &a, unsigned b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (Fixed< IntType, IntBits > const &a, int b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (Fixed< IntType, IntBits > const &a, unsigned short b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (Fixed< IntType, IntBits > const &a, short b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (Fixed< IntType, IntBits > const &a, unsigned char b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (Fixed< IntType, IntBits > const &a, char b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator- (Fixed< IntType, IntBits > const &a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (double a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (float a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (uint64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (int64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (unsigned a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (int a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (unsigned short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (unsigned char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (Fixed< IntType, IntBits > const &a, double b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (Fixed< IntType, IntBits > const &a, float b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (Fixed< IntType, IntBits > const &a, uint64_t b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (Fixed< IntType, IntBits > const &a, int64_t b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (Fixed< IntType, IntBits > const &a, unsigned b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (Fixed< IntType, IntBits > const &a, int b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (Fixed< IntType, IntBits > const &a, unsigned short b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (Fixed< IntType, IntBits > const &a, short b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (Fixed< IntType, IntBits > const &a, unsigned char b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (Fixed< IntType, IntBits > const &a, char b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator% (Fixed< IntType, IntBits > const &a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (double a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (float a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (uint64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (int64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (unsigned a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (int a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (unsigned short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (unsigned char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (Fixed< IntType, IntBits > const &a, double b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (Fixed< IntType, IntBits > const &a, float b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (Fixed< IntType, IntBits > const &a, uint64_t b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (Fixed< IntType, IntBits > const &a, int64_t b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (Fixed< IntType, IntBits > const &a, unsigned b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (Fixed< IntType, IntBits > const &a, int b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (Fixed< IntType, IntBits > const &a, unsigned short b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (Fixed< IntType, IntBits > const &a, short b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (Fixed< IntType, IntBits > const &a, unsigned char b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (Fixed< IntType, IntBits > const &a, char b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator+ (Fixed< IntType, IntBits > const &a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (double a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (float a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (uint64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (int64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (unsigned a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (int a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (unsigned short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (unsigned char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (Fixed< IntType, IntBits > const &a, double b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (Fixed< IntType, IntBits > const &a, float b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (Fixed< IntType, IntBits > const &a, uint64_t b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (Fixed< IntType, IntBits > const &a, int64_t b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (Fixed< IntType, IntBits > const &a, unsigned b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (Fixed< IntType, IntBits > const &a, int b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (Fixed< IntType, IntBits > const &a, unsigned short b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (Fixed< IntType, IntBits > const &a, short b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (Fixed< IntType, IntBits > const &a, unsigned char b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (Fixed< IntType, IntBits > const &a, char b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator* (Fixed< IntType, IntBits > const &a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (double a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (float a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (uint64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (int64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (unsigned a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (int a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (unsigned short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (unsigned char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (Fixed< IntType, IntBits > const &a, double b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (Fixed< IntType, IntBits > const &a, float b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (Fixed< IntType, IntBits > const &a, uint64_t b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (Fixed< IntType, IntBits > const &a, int64_t b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (Fixed< IntType, IntBits > const &a, unsigned b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (Fixed< IntType, IntBits > const &a, int b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (Fixed< IntType, IntBits > const &a, unsigned short b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (Fixed< IntType, IntBits > const &a, short b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (Fixed< IntType, IntBits > const &a, unsigned char b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (Fixed< IntType, IntBits > const &a, char b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > operator/ (Fixed< IntType, IntBits > const &a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator== (double a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator== (float a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator== (uint64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator== (int64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator== (unsigned a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator== (int a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator== (unsigned short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator== (short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator== (unsigned char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator== (char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator== (Fixed< IntType, IntBits > const &a, double b)
template<typename IntType , uint32_t IntBits>
bool operator== (Fixed< IntType, IntBits > const &a, float b)
template<typename IntType , uint32_t IntBits>
bool operator== (Fixed< IntType, IntBits > const &a, uint64_t b)
template<typename IntType , uint32_t IntBits>
bool operator== (Fixed< IntType, IntBits > const &a, int64_t b)
template<typename IntType , uint32_t IntBits>
bool operator== (Fixed< IntType, IntBits > const &a, unsigned b)
template<typename IntType , uint32_t IntBits>
bool operator== (Fixed< IntType, IntBits > const &a, int b)
template<typename IntType , uint32_t IntBits>
bool operator== (Fixed< IntType, IntBits > const &a, unsigned short b)
template<typename IntType , uint32_t IntBits>
bool operator== (Fixed< IntType, IntBits > const &a, short b)
template<typename IntType , uint32_t IntBits>
bool operator== (Fixed< IntType, IntBits > const &a, unsigned char b)
template<typename IntType , uint32_t IntBits>
bool operator== (Fixed< IntType, IntBits > const &a, char b)
template<typename IntType , uint32_t IntBits>
bool operator!= (double a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator!= (float a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator!= (uint64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator!= (int64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator!= (unsigned a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator!= (int a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator!= (unsigned short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator!= (short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator!= (unsigned char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator!= (char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator!= (Fixed< IntType, IntBits > const &a, double b)
template<typename IntType , uint32_t IntBits>
bool operator!= (Fixed< IntType, IntBits > const &a, float b)
template<typename IntType , uint32_t IntBits>
bool operator!= (Fixed< IntType, IntBits > const &a, uint64_t b)
template<typename IntType , uint32_t IntBits>
bool operator!= (Fixed< IntType, IntBits > const &a, int64_t b)
template<typename IntType , uint32_t IntBits>
bool operator!= (Fixed< IntType, IntBits > const &a, unsigned b)
template<typename IntType , uint32_t IntBits>
bool operator!= (Fixed< IntType, IntBits > const &a, int b)
template<typename IntType , uint32_t IntBits>
bool operator!= (Fixed< IntType, IntBits > const &a, unsigned short b)
template<typename IntType , uint32_t IntBits>
bool operator!= (Fixed< IntType, IntBits > const &a, short b)
template<typename IntType , uint32_t IntBits>
bool operator!= (Fixed< IntType, IntBits > const &a, unsigned char b)
template<typename IntType , uint32_t IntBits>
bool operator!= (Fixed< IntType, IntBits > const &a, char b)
template<typename IntType , uint32_t IntBits>
bool operator< (double a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator< (float a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator< (uint64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator< (int64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator< (unsigned a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator< (int a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator< (unsigned short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator< (short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator< (unsigned char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator< (char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator< (Fixed< IntType, IntBits > const &a, double b)
template<typename IntType , uint32_t IntBits>
bool operator< (Fixed< IntType, IntBits > const &a, float b)
template<typename IntType , uint32_t IntBits>
bool operator< (Fixed< IntType, IntBits > const &a, uint64_t b)
template<typename IntType , uint32_t IntBits>
bool operator< (Fixed< IntType, IntBits > const &a, int64_t b)
template<typename IntType , uint32_t IntBits>
bool operator< (Fixed< IntType, IntBits > const &a, unsigned b)
template<typename IntType , uint32_t IntBits>
bool operator< (Fixed< IntType, IntBits > const &a, int b)
template<typename IntType , uint32_t IntBits>
bool operator< (Fixed< IntType, IntBits > const &a, unsigned short b)
template<typename IntType , uint32_t IntBits>
bool operator< (Fixed< IntType, IntBits > const &a, short b)
template<typename IntType , uint32_t IntBits>
bool operator< (Fixed< IntType, IntBits > const &a, unsigned char b)
template<typename IntType , uint32_t IntBits>
bool operator< (Fixed< IntType, IntBits > const &a, char b)
template<typename IntType , uint32_t IntBits>
bool operator> (double a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator> (float a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator> (uint64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator> (int64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator> (unsigned a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator> (int a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator> (unsigned short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator> (short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator> (unsigned char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator> (char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator> (Fixed< IntType, IntBits > const &a, double b)
template<typename IntType , uint32_t IntBits>
bool operator> (Fixed< IntType, IntBits > const &a, float b)
template<typename IntType , uint32_t IntBits>
bool operator> (Fixed< IntType, IntBits > const &a, uint64_t b)
template<typename IntType , uint32_t IntBits>
bool operator> (Fixed< IntType, IntBits > const &a, int64_t b)
template<typename IntType , uint32_t IntBits>
bool operator> (Fixed< IntType, IntBits > const &a, unsigned b)
template<typename IntType , uint32_t IntBits>
bool operator> (Fixed< IntType, IntBits > const &a, int b)
template<typename IntType , uint32_t IntBits>
bool operator> (Fixed< IntType, IntBits > const &a, unsigned short b)
template<typename IntType , uint32_t IntBits>
bool operator> (Fixed< IntType, IntBits > const &a, short b)
template<typename IntType , uint32_t IntBits>
bool operator> (Fixed< IntType, IntBits > const &a, unsigned char b)
template<typename IntType , uint32_t IntBits>
bool operator> (Fixed< IntType, IntBits > const &a, char b)
template<typename IntType , uint32_t IntBits>
bool operator<= (double a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator<= (float a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator<= (uint64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator<= (int64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator<= (unsigned a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator<= (int a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator<= (unsigned short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator<= (short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator<= (unsigned char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator<= (char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator<= (Fixed< IntType, IntBits > const &a, double b)
template<typename IntType , uint32_t IntBits>
bool operator<= (Fixed< IntType, IntBits > const &a, float b)
template<typename IntType , uint32_t IntBits>
bool operator<= (Fixed< IntType, IntBits > const &a, uint64_t b)
template<typename IntType , uint32_t IntBits>
bool operator<= (Fixed< IntType, IntBits > const &a, int64_t b)
template<typename IntType , uint32_t IntBits>
bool operator<= (Fixed< IntType, IntBits > const &a, unsigned b)
template<typename IntType , uint32_t IntBits>
bool operator<= (Fixed< IntType, IntBits > const &a, int b)
template<typename IntType , uint32_t IntBits>
bool operator<= (Fixed< IntType, IntBits > const &a, unsigned short b)
template<typename IntType , uint32_t IntBits>
bool operator<= (Fixed< IntType, IntBits > const &a, short b)
template<typename IntType , uint32_t IntBits>
bool operator<= (Fixed< IntType, IntBits > const &a, unsigned char b)
template<typename IntType , uint32_t IntBits>
bool operator<= (Fixed< IntType, IntBits > const &a, char b)
template<typename IntType , uint32_t IntBits>
bool operator>= (double a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator>= (float a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator>= (uint64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator>= (int64_t a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator>= (unsigned a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator>= (int a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator>= (unsigned short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator>= (short a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator>= (unsigned char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator>= (char a, Fixed< IntType, IntBits > const &b)
template<typename IntType , uint32_t IntBits>
bool operator>= (Fixed< IntType, IntBits > const &a, double b)
template<typename IntType , uint32_t IntBits>
bool operator>= (Fixed< IntType, IntBits > const &a, float b)
template<typename IntType , uint32_t IntBits>
bool operator>= (Fixed< IntType, IntBits > const &a, uint64_t b)
template<typename IntType , uint32_t IntBits>
bool operator>= (Fixed< IntType, IntBits > const &a, int64_t b)
template<typename IntType , uint32_t IntBits>
bool operator>= (Fixed< IntType, IntBits > const &a, unsigned b)
template<typename IntType , uint32_t IntBits>
bool operator>= (Fixed< IntType, IntBits > const &a, int b)
template<typename IntType , uint32_t IntBits>
bool operator>= (Fixed< IntType, IntBits > const &a, unsigned short b)
template<typename IntType , uint32_t IntBits>
bool operator>= (Fixed< IntType, IntBits > const &a, short b)
template<typename IntType , uint32_t IntBits>
bool operator>= (Fixed< IntType, IntBits > const &a, unsigned char b)
template<typename IntType , uint32_t IntBits>
bool operator>= (Fixed< IntType, IntBits > const &a, char b)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > sin (Fixed< IntType, IntBits > const &x)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > cos (Fixed< IntType, IntBits > const &x)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > tan (Fixed< IntType, IntBits > const &x)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > sqrt (Fixed< IntType, IntBits > const &x)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > exp (Fixed< IntType, IntBits > const &x)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > log (Fixed< IntType, IntBits > const &x)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > floor (Fixed< IntType, IntBits > const &x)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > ceil (Fixed< IntType, IntBits > const &x)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > abs (Fixed< IntType, IntBits > const &x)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > modf (Fixed< IntType, IntBits > const &x, Fixed< IntType, IntBits > *integral_part)
template<typename IntType , uint32_t IntBits>
Fixed< IntType, IntBits > arg (const std::complex< Fixed< IntType, IntBits > > &val)
template<typename IntType , uint32_t IntBits>
std::complex< Fixed< IntType, IntBits > > polar (const Fixed< IntType, IntBits > &rho, const Fixed< IntType, IntBits > &theta)
Function Documentation
abs()
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> abs (Fixed< IntType, IntBits > const & x) inline
Definition at line 2313 of file fixed.h.
References Fixed< IntType, IntBits >::abs().
Referenced by ValueDial::animate(), ValueDialZ::animate(), RDSDemod::biphase(), UDPSource::calculateLevel(), AudioCompressor::compress(), fftfilt::create_asym_filter(), fftfilt::create_dsb_filter(), fftfilt::create_filter(), fftfilt::create_rrc_filter(), SoapySDRInputGui::dcCorrectionArgumentChanged(), SoapySDROutputGui::dcCorrectionArgumentChanged(), SoapySDRInputGui::displayCorrectionsSettings(), SoapySDROutputGui::displayCorrectionsSettings(), RTLSDRGui::displayGains(), leansdr::gen_abs(), SoapySDRInputGui::iqCorrectionArgumentChanged(), SoapySDROutputGui::iqCorrectionArgumentChanged(), ValueDialZ::keyPressEvent(), RTLSDRGui::on_gain_valueChanged(), PhaseLock::process(), PhaseLock::process_phasor(), and leansdr::softword_weight().
 {
     return x.abs();
 }
arg()
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> arg (const std::complex< Fixed< IntType, IntBits > > & val) inline
Definition at line 2401 of file fixed.h.
References Fixed< IntType, IntBits >::to_polar().
Referenced by AboutDialog::AboutDialog(), MainWindow::addCommandToTree(), IntervalRangeGUI::addInterval(), DSDStatusTextDialog::addLine(), MainWindow::addPresetToTree(), AirspyHFInput::AirspyHFInput(), AirspyInput::AirspyInput(), AMDemodGUI::AMDemodGUI(), AMModGUI::AMModGUI(), RemoteOutputSinkGui::analyzeApiReply(), WebAPIRequestMapper::appendSettingsArrayKeys(), SSBDemodGUI::applyBandwidths(), SSBModGUI::applyBandwidths(), LocalSinkGUI::applyPosition(), RemoteSinkGUI::applyPosition(), LocalSourceGUI::applyPosition(), FileSourceGUI::applyPosition(), GLSpectrumGUI::applySettings(), PlutoSDROutput::applySettings(), PlutoSDRInput::applySettings(), ATVDemodGUI::ATVDemodGUI(), ATVModGUI::ATVModGUI(), AudioSelectDialog::AudioSelectDialog(), BFMDemodGUI::BFMDemodGUI(), Bladerf1Input::Bladerf1Input(), BladeRF2Input::BladeRF2Input(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), SoapySDRInputGui::createIndividualGainsControl(), SoapySDROutputGui::createIndividualGainsControl(), SoapySDRInputGui::createRangesControl(), SoapySDROutputGui::createRangesControl(), SoapySDRInputGui::createTunableElementsControl(), SoapySDROutputGui::createTunableElementsControl(), DATVDemodGUI::DATVDemodGUI(), SoapySDRInputGui::dcCorrectionModuleChanged(), SoapySDROutputGui::dcCorrectionModuleChanged(), GLScopeGUI::deserialize(), WebAPIAdapterGUI::devicesetChannelSettingsPutPatch(), WebAPIAdapterSrv::devicesetChannelSettingsPutPatch(), DeviceUserArgsDialog::DeviceUserArgsDialog(), TestSourceGui::displayAmplitude(), TestMIGui::displayAmplitude(), DeviceUserArgsDialog::displayArgsByDevice(), HackRFInputGui::displayBandwidths(), HackRFOutputGui::displayBandwidths(), FreeDVModGUI::displayBandwidths(), FreeDVDemodGUI::displayBandwidths(), SoapySDRInputGui::displayCorrectionsSettings(), SoapySDROutputGui::displayCorrectionsSettings(), Bladerf1InputGui::displayFcTooltip(), BladeRF2InputGui::displayFcTooltip(), PlutoSDRInputGui::displayFcTooltip(), RTLSDRGui::displayFcTooltip(), HackRFInputGui::displayFcTooltip(), HackRFOutputGui::displayFcTooltip(), RTLSDRGui::displayGains(), LocalSinkGUI::displayRateAndShift(), RemoteSinkGUI::displayRateAndShift(), LocalSourceGUI::displayRateAndShift(), FileSourceGUI::displayRateAndShift(), Bladerf1InputGui::displaySampleRate(), BladeRF2InputGui::displaySampleRate(), LimeSDRInputGUI::displaySampleRate(), PlutoSDRInputGui::displaySampleRate(), RTLSDRGui::displaySampleRate(), Bladerf1OutputGui::displaySampleRate(), BladeRF2OutputGui::displaySampleRate(), PlutoSDROutputGUI::displaySampleRate(), XTRXOutputGUI::displaySampleRate(), XTRXInputGUI::displaySampleRate(), LimeSDROutputGUI::displaySampleRate(), HackRFInputGui::displaySampleRate(), HackRFOutputGui::displaySampleRate(), AirspyGui::displaySampleRates(), PerseusGui::displaySampleRates(), AirspyHFGui::displaySampleRates(), CWKeyerGUI::displaySettings(), WFMDemodGUI::displaySettings(), LoRaDemodGUI::displaySettings(), NFMDemodGUI::displaySettings(), AMDemodGUI::displaySettings(), Bladerf1InputGui::displaySettings(), BladeRF2InputGui::displaySettings(), FCDProPlusGui::displaySettings(), FCDProGui::displaySettings(), LimeSDRInputGUI::displaySettings(), PlutoSDRInputGui::displaySettings(), SDRPlayGui::displaySettings(), TestSourceGui::displaySettings(), Bladerf1OutputGui::displaySettings(), BladeRF2OutputGui::displaySettings(), PlutoSDROutputGUI::displaySettings(), XTRXOutputGUI::displaySettings(), AirspyGui::displaySettings(), PerseusGui::displaySettings(), XTRXInputGUI::displaySettings(), LimeSDROutputGUI::displaySettings(), AirspyHFGui::displaySettings(), TestMIGui::displaySettings(), SSBDemodGUI::displaySettings(), RTLSDRGui::displaySettings(), HackRFInputGui::displaySettings(), FreqTrackerGUI::displaySettings(), HackRFOutputGui::displaySettings(), RemoteSinkGUI::displaySettings(), BFMDemodGUI::displaySettings(), UDPSourceGUI::displaySettings(), NFMModGUI::displaySettings(), LocalOutputGui::displaySettings(), AMModGUI::displaySettings(), RemoteSourceGUI::displaySettings(), ATVModGUI::displaySettings(), WFMModGUI::displaySettings(), UDPSinkGUI::displaySettings(), FreeDVModGUI::displaySettings(), SSBModGUI::displaySettings(), FreeDVDemodGUI::displaySettings(), FileSourceGUI::displaySettings(), SoapySDRInputGui::displaySettings(), SoapySDROutputGui::displaySettings(), DSDDemodGUI::displaySettings(), LocalInputGui::displaySettings(), RemoteInputGui::displaySettings(), RemoteOutputSinkGui::displaySettings(), DATVDemodGUI::displaySettings(), AMDemodGUI::displayStreamIndex(), DSDDemodGUI::DSDDemodGUI(), Bladerf1OutputPlugin::enumSampleSinks(), BladeRF2OutputPlugin::enumSampleSinks(), HackRFOutputPlugin::enumSampleSinks(), LimeSDROutputPlugin::enumSampleSinks(), PlutoSDROutputPlugin::enumSampleSinks(), SoapySDROutputPlugin::enumSampleSinks(), XTRXOutputPlugin::enumSampleSinks(), FCDProPlugin::enumSampleSources(), FCDProPlusPlugin::enumSampleSources(), RTLSDRPlugin::enumSampleSources(), AirspyPlugin::enumSampleSources(), AirspyHFPlugin::enumSampleSources(), HackRFInputPlugin::enumSampleSources(), LimeSDRInputPlugin::enumSampleSources(), PerseusPlugin::enumSampleSources(), PlutoSDRInputPlugin::enumSampleSources(), SDRPlayPlugin::enumSampleSources(), XTRXInputPlugin::enumSampleSources(), Blderf1InputPlugin::enumSampleSources(), Blderf2InputPlugin::enumSampleSources(), SoapySDRInputPlugin::enumSampleSources(), SWGSDRangel::SWGHttpRequestWorker::execute(), FCDProInput::FCDProInput(), FCDProPlusInput::FCDProPlusInput(), FreqLockComplex::feed(), PhaseLockComplex::feed(), FreeDVDemodGUI::FreeDVDemodGUI(), FreeDVModGUI::FreeDVModGUI(), FreqTrackerGUI::FreqTrackerGUI(), FileRecord::genUniqueFileName(), GLSpectrumGUI::GLSpectrumGUI(), HackRFInput::HackRFInput(), LimeSDRInputGUI::handleMessage(), XTRXOutputGUI::handleMessage(), XTRXInputGUI::handleMessage(), LimeSDROutputGUI::handleMessage(), RemoteSourceGUI::handleMessage(), ATVModGUI::handleMessage(), FreqTrackerGUI::handleMessage(), ATVDemodGUI::handleMessage(), TestMI::init(), WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), SoapySDRInputGui::iqCorrectionModuleChanged(), SoapySDROutputGui::iqCorrectionModuleChanged(), LimeSDRInput::LimeSDRInput(), LimeSDRInputGUI::LimeSDRInputGUI(), LimeSDROutputGUI::LimeSDROutputGUI(), ATVDemodGUI::lineTimeUpdate(), LocalInput::LocalInput(), NFMDemodGUI::NFMDemodGUI(), NFMModGUI::NFMModGUI(), WFMDemodGUI::on_afBW_valueChanged(), NFMDemodGUI::on_afBW_valueChanged(), BFMDemodGUI::on_afBW_valueChanged(), NFMModGUI::on_afBW_valueChanged(), WFMModGUI::on_afBW_valueChanged(), UDPSourceGUI::on_amModPercent_textEdited(), TestSourceGui::on_amModulation_valueChanged(), TestMIGui::on_amModulation_valueChanged(), ComplexFactorGUI::on_arg_valueChanged(), PlutoSDROutputGUI::on_att_valueChanged(), DATVDemodGUI::on_audioVolume_valueChanged(), ATVDemodGUI::on_bfo_valueChanged(), ATVDemodGUI::on_blackLevel_valueChanged(), LoRaDemodGUI::on_BW_valueChanged(), ATVModGUI::on_cameraManualFPS_valueChanged(), MainWindow::on_commandDelete_clicked(), CWKeyerGUI::on_cwSpeed_valueChanged(), TestSourceGui::on_dcBias_valueChanged(), TestMIGui::on_dcBias_valueChanged(), GLSpectrumGUI::on_decay_valueChanged(), NFMDemodGUI::on_deltaSquelch_toggled(), DSDDemodGUI::on_demodGain_valueChanged(), AMModGUI::on_feedbackVolume_valueChanged(), NFMModGUI::on_feedbackVolume_valueChanged(), SSBModGUI::on_feedbackVolume_valueChanged(), NFMModGUI::on_fmDev_valueChanged(), WFMModGUI::on_fmDev_valueChanged(), UDPSourceGUI::on_fmDeviation_textEdited(), UDPSinkGUI::on_fmDeviation_textEdited(), TestSourceGui::on_fmDeviation_valueChanged(), TestMIGui::on_fmDeviation_valueChanged(), ATVDemodGUI::on_fmDeviation_valueChanged(), DSDDemodGUI::on_fmDeviation_valueChanged(), ATVModGUI::on_fmExcursion_valueChanged(), BladeRF2OutputGui::on_gain_valueChanged(), BladeRF2InputGui::on_gain_valueChanged(), XTRXOutputGUI::on_gain_valueChanged(), RTLSDRGui::on_gain_valueChanged(), LimeSDROutputGUI::on_gain_valueChanged(), XTRXInputGUI::on_gain_valueChanged(), LimeSDRInputGUI::on_gain_valueChanged(), PlutoSDRInputGui::on_gain_valueChanged(), FileSourceGUI::on_gain_valueChanged(), UDPSinkGUI::on_gain_valueChanged(), UDPSourceGUI::on_gainIn_valueChanged(), UDPSourceGUI::on_gainOut_valueChanged(), GLSpectrumGUI::on_gridIntensity_valueChanged(), GLScopeGUI::on_gridIntensity_valueChanged(), TestSourceGui::on_iBias_valueChanged(), TestMIGui::on_iBias_valueChanged(), AMBEDevicesDialog::on_importAddress_clicked(), AMBEDevicesDialog::on_importAllSerial_clicked(), AMBEDevicesDialog::on_importSerial_clicked(), UDPSinkGUI::on_inputUDPAudioPort_editingFinished(), AudioDialogX::on_inputVolume_valueChanged(), IntervalSliderGUI::on_intervalSlider_valueChanged(), ATVDemodGUI::on_lineTime_valueChanged(), AirspyGui::on_lna_valueChanged(), HackRFInputGui::on_lna_valueChanged(), XTRXInputGUI::on_lnaGain_valueChanged(), LimeSDRInputGUI::on_lnaGain_valueChanged(), UDPSourceGUI::on_localUDPPort_editingFinished(), AirspyGui::on_LOppm_valueChanged(), PerseusGui::on_LOppm_valueChanged(), BladeRF2OutputGui::on_LOppm_valueChanged(), AirspyHFGui::on_LOppm_valueChanged(), BladeRF2InputGui::on_LOppm_valueChanged(), PlutoSDROutputGUI::on_loPPM_valueChanged(), PlutoSDRInputGui::on_loPPM_valueChanged(), HackRFInputGui::on_LOppm_valueChanged(), HackRFOutputGui::on_LOppm_valueChanged(), SoapySDRInputGui::on_LOppm_valueChanged(), SoapySDROutputGui::on_LOppm_valueChanged(), GLScopeGUI::on_memoryLoad_clicked(), GLScopeGUI::on_memorySave_clicked(), AirspyGui::on_mix_valueChanged(), AMModGUI::on_modPercent_valueChanged(), TestSourceGui::on_modulationFrequency_valueChanged(), TestMIGui::on_modulationFrequency_valueChanged(), ComplexFactorGUI::on_module_valueChanged(), RemoteSinkGUI::on_nbFECBlocks_valueChanged(), RemoteOutputSinkGui::on_nbFECBlocks_valueChanged(), AudioDialogX::on_outputUDPPort_editingFinished(), UDPSinkGUI::on_outputUDPPort_editingFinished(), XTRXInputGUI::on_pgaGain_valueChanged(), LimeSDRInputGUI::on_pgaGain_valueChanged(), TestSourceGui::on_phaseImbalance_valueChanged(), TestMIGui::on_phaseImbalance_valueChanged(), SDRPlayGui::on_ppm_valueChanged(), RTLSDRGui::on_ppm_valueChanged(), MainWindow::on_presetDelete_clicked(), TestSourceGui::on_qBias_valueChanged(), TestMIGui::on_qBias_valueChanged(), AMBEDevicesDialog::on_removeAmbeDevice_clicked(), UDPSourceGUI::on_rfBandwidth_textEdited(), UDPSinkGUI::on_rfBandwidth_textEdited(), AMDemodGUI::on_rfBW_valueChanged(), FreqTrackerGUI::on_rfBW_valueChanged(), BFMDemodGUI::on_rfBW_valueChanged(), AMModGUI::on_rfBW_valueChanged(), ATVModGUI::on_rfBW_valueChanged(), DSDDemodGUI::on_rfBW_valueChanged(), ATVDemodGUI::on_rfBW_valueChanged(), ATVModGUI::on_rfOppBW_valueChanged(), ATVDemodGUI::on_rfOppBW_valueChanged(), ATVModGUI::on_rfScaling_valueChanged(), UDPSourceGUI::on_sampleRate_textEdited(), UDPSinkGUI::on_sampleRate_textEdited(), GLScopeGUI::on_scope_sampleRateChanged(), WFMDemodGUI::on_squelch_valueChanged(), NFMDemodGUI::on_squelch_valueChanged(), AMDemodGUI::on_squelch_valueChanged(), FreqTrackerGUI::on_squelch_valueChanged(), BFMDemodGUI::on_squelch_valueChanged(), UDPSourceGUI::on_squelch_valueChanged(), UDPSinkGUI::on_squelch_valueChanged(), DSDDemodGUI::on_squelch_valueChanged(), NFMDemodGUI::on_squelchGate_valueChanged(), FreqTrackerGUI::on_squelchGate_valueChanged(), UDPSourceGUI::on_squelchGate_valueChanged(), UDPSinkGUI::on_squelchGate_valueChanged(), DSDDemodGUI::on_squelchGate_valueChanged(), DATVDemodGUI::on_StreamDataAvailable(), ATVDemodGUI::on_synchLevel_valueChanged(), NFMModGUI::on_toneFrequency_valueChanged(), AMModGUI::on_toneFrequency_valueChanged(), FreeDVModGUI::on_toneFrequency_valueChanged(), WFMModGUI::on_toneFrequency_valueChanged(), SSBModGUI::on_toneFrequency_valueChanged(), ATVDemodGUI::on_topTime_valueChanged(), GLScopeGUI::on_trace_valueChanged(), GLScopeGUI::on_traceColor_clicked(), DSDDemodGUI::on_traceDecay_valueChanged(), GLSpectrumGUI::on_traceIntensity_valueChanged(), GLScopeGUI::on_traceIntensity_valueChanged(), DSDDemodGUI::on_traceLength_valueChanged(), DSDDemodGUI::on_traceStroke_valueChanged(), GLScopeGUI::on_trig_valueChanged(), GLScopeGUI::on_trigColor_clicked(), GLScopeGUI::on_trigHoldoff_valueChanged(), RemoteSinkGUI::on_txDelay_valueChanged(), RemoteOutputSinkGui::on_txDelay_valueChanged(), HackRFOutputGui::on_txvga_valueChanged(), DATVDemodGUI::on_udpTSPort_editingFinished(), ATVModGUI::on_uniformLevel_valueChanged(), Bladerf1OutputGui::on_vga1_valueChanged(), Bladerf1InputGui::on_vga1_valueChanged(), Bladerf1OutputGui::on_vga2_valueChanged(), Bladerf1InputGui::on_vga2_valueChanged(), AirspyGui::on_vga_valueChanged(), HackRFInputGui::on_vga_valueChanged(), WFMDemodGUI::on_volume_valueChanged(), NFMDemodGUI::on_volume_valueChanged(), AMDemodGUI::on_volume_valueChanged(), SSBDemodGUI::on_volume_valueChanged(), BFMDemodGUI::on_volume_valueChanged(), AMModGUI::on_volume_valueChanged(), NFMModGUI::on_volume_valueChanged(), FreeDVDemodGUI::on_volume_valueChanged(), FreeDVModGUI::on_volume_valueChanged(), SSBModGUI::on_volume_valueChanged(), UDPSinkGUI::on_volume_valueChanged(), WFMModGUI::on_volume_valueChanged(), DSDDemodGUI::on_volume_valueChanged(), FreeDVDemodGUI::on_volumeIn_valueChanged(), BasicChannelSettingsDialog::paintColor(), PerseusInput::PerseusInput(), PluginsDialog::PluginsDialog(), PlutoSDRInput::PlutoSDRInput(), BFMDemodGUI::rdsUpdate(), CommandOutputDialog::refresh(), RemoteInput::RemoteInput(), DeviceSet::renameRxChannelInstances(), DeviceUISet::renameRxChannelInstances(), DeviceSet::renameTxChannelInstances(), DeviceUISet::renameTxChannelInstances(), qtwebapp::FileLogger::rotate(), RTLSDRInput::RTLSDRInput(), Projector::run(), DeviceSoapySDRScan::scan(), SDRPlayInput::SDRPlayInput(), GLScopeGUI::setAmpOfsDisplay(), GLScopeGUI::setAmpScaleDisplay(), ComplexFactorGUI::setArgument(), GLSpectrumGUI::setAveragingToolitp(), XTRXOutputGUI::setCenterFrequencyDisplay(), LimeSDRInputGUI::setCenterFrequencyDisplay(), LimeSDROutputGUI::setCenterFrequencyDisplay(), XTRXInputGUI::setCenterFrequencyDisplay(), LimeSDRInputGUI::setCenterFrequencySetting(), XTRXOutputGUI::setCenterFrequencySetting(), XTRXInputGUI::setCenterFrequencySetting(), BladeRF2InputGui::setCenterFrequencySetting(), BladeRF2OutputGui::setCenterFrequencySetting(), LimeSDROutputGUI::setCenterFrequencySetting(), SoapySDRInputGui::setCenterFrequencySetting(), SoapySDROutputGui::setCenterFrequencySetting(), NFMDemodGUI::setCtcssFreq(), ChannelAnalyzerGUI::setFiltersUIBoundaries(), MainCore::setLoggingOptions(), MainWindow::setLoggingOptions(), ComplexFactorGUI::setModule(), XTRXOutputGUI::setNCODisplay(), LimeSDRInputGUI::setNCODisplay(), XTRXInputGUI::setNCODisplay(), LimeSDROutputGUI::setNCODisplay(), ChannelAnalyzerGUI::setNewFinalRate(), DeviceStreamSelectionDialog::setNumberOfStreams(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicChannelSettingsDialog::setReverseAPIPort(), ATVDemodGUI::setRFFiltersSlidersRange(), ATVModGUI::setRFFiltersSlidersRange(), GLScopeGUI::setTimeOfsDisplay(), GLScopeGUI::setTimeScaleDisplay(), GLScopeGUI::setTraceDelayDisplay(), GLScopeGUI::setTraceLenDisplay(), GLScopeGUI::setTraceUI(), GLScopeGUI::setTrigDelayDisplay(), GLScopeGUI::setTriggerUI(), GLScopeGUI::setTrigIndexDisplay(), GLScopeGUI::setTrigLevelDisplay(), GLScopeGUI::setTrigPreDisplay(), IntervalSliderGUI::setValue(), SoapySDRInput::SoapySDRInput(), SSBDemodGUI::SSBDemodGUI(), SSBModGUI::SSBModGUI(), TestMIGui::TestMIGui(), TestSourceGui::TestSourceGui(), TestSourceInput::TestSourceInput(), DATVDemodGUI::tick(), NFMDemodGUI::tick(), AMDemodGUI::tick(), FreqTrackerGUI::tick(), ATVDemodGUI::tick(), SSBDemodGUI::tick(), FreeDVDemodGUI::tick(), UDPSourceGUI::tick(), ChannelAnalyzerGUI::tick(), AMModGUI::tick(), FreeDVModGUI::tick(), NFMModGUI::tick(), WFMModGUI::tick(), SSBModGUI::tick(), ATVModGUI::tick(), DSDDemodGUI::tick(), ATVDemodGUI::topTimeUpdate(), TransverterDialog::TransverterDialog(), UDPSinkGUI::UDPSinkGUI(), UDPSourceGUI::UDPSourceGUI(), LimeSDRInputGUI::updateADCRate(), XTRXInputGUI::updateADCRate(), XTRXOutputGUI::updateDACRate(), LimeSDROutputGUI::updateDACRate(), AudioDialogX::updateInputDisplay(), LocalSourceGUI::updateLocalDevices(), LocalSinkGUI::updateLocalDevices(), AudioDialogX::updateOutputDisplay(), AudioDialogX::updateOutputSDPString(), RemoteOutputSinkGui::updateSampleRate(), FCDProPlusGui::updateSampleRateAndFrequency(), TestSourceGui::updateSampleRateAndFrequency(), FCDProGui::updateSampleRateAndFrequency(), SDRPlayGui::updateSampleRateAndFrequency(), TestMIGui::updateSampleRateAndFrequency(), AirspyGui::updateSampleRateAndFrequency(), KiwiSDRGui::updateSampleRateAndFrequency(), PerseusGui::updateSampleRateAndFrequency(), AirspyHFGui::updateSampleRateAndFrequency(), FileInputGUI::updateSampleRateAndFrequency(), FileSinkGui::updateSampleRateAndFrequency(), LocalOutputGui::updateSampleRateAndFrequency(), SoapySDRInputGui::updateSampleRateAndFrequency(), SoapySDROutputGui::updateSampleRateAndFrequency(), LocalInputGui::updateSampleRateAndFrequency(), RemoteInputGui::updateSampleRateAndFrequency(), ExternalClockButton::updateState(), TransverterButton::updateState(), PlutoSDROutputGUI::updateStatus(), PlutoSDRInputGui::updateStatus(), ArgInfoGUI::updateUIFromFloat(), ArgInfoGUI::updateUIFromInt(), FileInputGUI::updateWithStreamData(), FileSourceGUI::updateWithStreamData(), RemoteInputGui::updateWithStreamTime(), SoapySDROutput::webapiFormatArgValue(), SoapySDRInput::webapiFormatArgValue(), SoapySDROutput::webapiFormatDeviceSettings(), SoapySDRInput::webapiFormatDeviceSettings(), TestMI::webapiSettingsPutPatch(), WFMDemodGUI::WFMDemodGUI(), WFMModGUI::WFMModGUI(), XTRXInput::XTRXInput(), XTRXInputGUI::XTRXInputGUI(), and XTRXOutputGUI::XTRXOutputGUI().
 {
     Fixed<IntType, IntBits> r,theta;
     Fixed<IntType, IntBits>::to_polar(val.real(),val.imag(),&r,&theta);
     return theta;
 }
ceil()
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> ceil (Fixed< IntType, IntBits > const & x) inline
Definition at line 2307 of file fixed.h.
References Fixed< IntType, IntBits >::ceil().
 {
     return x.ceil();
 }
cos()
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> cos (Fixed< IntType, IntBits > const & x) inline
Definition at line 2271 of file fixed.h.
References Fixed< IntType, IntBits >::cos().
Referenced by fftfilt::_blackman(), AFSquelch::AFSquelch(), WFIR::BasicFIR(), blackman(), FFTWindow::blackmanHarris(), AudioFilter::cheby_sub(), cosc(), Highpass< Type >::create(), Bandpass< Real >::create(), Lowpass< Real >::create(), Interpolator::createPolyphaseLowPass(), FreqLockComplex::feed(), PhaseLockComplex::feed(), LoRaDemod::feed(), BFMDemod::feed(), g_fft< float >::fftCosInit(), FFTWindow::flatTop(), fftfilt::frrc(), TestMIThread::generate(), TestSourceThread::generate(), hamming(), FFTWindow::hamming(), hanning(), FFTWindow::hanning(), leansdr::fast_qpsk_receiver< T >::init_lookup_tables(), NCO::initTable(), NCOF::initTable(), leansdr::filtergen::lowpass(), UDPSource::modulateSample(), NFMMod::modulateSample(), ATVMod::modulateSample(), PhaseLock::process(), WFMMod::pull(), rcos(), leansdr::filtergen::root_raised_cosine(), CTCSSDetector::setCoefficients(), AFSquelch::setCoefficients(), SecondOrderRecursiveFilter::setFrequencies(), sfft::sfft(), and WFIR::WindowData().
 {
     return x.cos();
 }
exp()
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> exp (Fixed< IntType, IntBits > const & x) inline
Definition at line 2289 of file fixed.h.
References Fixed< IntType, IntBits >::exp().
Referenced by AudioFilter::cheby_sub(), LowPassFilterRC::configure(), PhaseLock::configure(), kissfft_utils::traits< Real, Complex >::fill_twiddles(), LowPassFilterRC::LowPassFilterRC(), PhaseLock::PhaseLock(), and WFIR::WindowData().
 {
     return x.exp();
 }
floor()
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> floor (Fixed< IntType, IntBits > const & x) inline
Definition at line 2301 of file fixed.h.
References Fixed< IntType, IntBits >::floor().
Referenced by ScaleEngine::calcMajorTickUnits(), Interpolator::decimate(), leansdr::cnr_fft< leansdr::f32 >::do_cnr(), ScaleEngine::formatTick(), Interpolator::interpolate(), ScaleEngine::reCalc(), Interpolator::resample(), and leansdr::s2_frame_receiver< T, SOFTSYMB >::run_frame_search().
 {
     return x.floor();
 }
log()
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> log (Fixed< IntType, IntBits > const & x) inline
Definition at line 2295 of file fixed.h.
References Fixed< IntType, IntBits >::log().
Referenced by AudioFilter::cheby_sub(), and log2f().
 {
     return x.log();
 }
modf()
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> modf (Fixed< IntType, IntBits > const & x, Fixed< IntType, IntBits > * integral_part) inline
Definition at line 2319 of file fixed.h.
References Fixed< IntType, IntBits >::modf().
 {
     return x.modf(integral_part);
 }
operator!=() [1/20]
template<typename IntType , uint32_t IntBits> bool operator!= (double a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1665 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) != b;
 }
operator!=() [2/20]
template<typename IntType , uint32_t IntBits> bool operator!= (float a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1671 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) != b;
 }
operator!=() [3/20]
template<typename IntType , uint32_t IntBits> bool operator!= (uint64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1677 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) != b;
 }
operator!=() [4/20]
template<typename IntType , uint32_t IntBits> bool operator!= (int64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1683 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) != b;
 }
operator!=() [5/20]
template<typename IntType , uint32_t IntBits> bool operator!= (unsigned a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1689 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) != b;
 }
operator!=() [6/20]
template<typename IntType , uint32_t IntBits> bool operator!= (int a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1695 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) != b;
 }
operator!=() [7/20]
template<typename IntType , uint32_t IntBits> bool operator!= (unsigned short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1701 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) != b;
 }
operator!=() [8/20]
template<typename IntType , uint32_t IntBits> bool operator!= (short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1707 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) != b;
 }
operator!=() [9/20]
template<typename IntType , uint32_t IntBits> bool operator!= (unsigned char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1713 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) != b;
 }
operator!=() [10/20]
template<typename IntType , uint32_t IntBits> bool operator!= (char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1719 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) != b;
 }
operator!=() [11/20]
template<typename IntType , uint32_t IntBits> bool operator!= (Fixed< IntType, IntBits > const & a, double b) inline
Definition at line 1725 of file fixed.h.
 {
     return a != Fixed<IntType, IntBits>(b);
 }
operator!=() [12/20]
template<typename IntType , uint32_t IntBits> bool operator!= (Fixed< IntType, IntBits > const & a, float b) inline
Definition at line 1731 of file fixed.h.
 {
     return a != Fixed<IntType, IntBits>(b);
 }
operator!=() [13/20]
template<typename IntType , uint32_t IntBits> bool operator!= (Fixed< IntType, IntBits > const & a, uint64_t b) inline
Definition at line 1737 of file fixed.h.
 {
     return a != Fixed<IntType, IntBits>(b);
 }
operator!=() [14/20]
template<typename IntType , uint32_t IntBits> bool operator!= (Fixed< IntType, IntBits > const & a, int64_t b) inline
Definition at line 1743 of file fixed.h.
 {
     return a != Fixed<IntType, IntBits>(b);
 }
operator!=() [15/20]
template<typename IntType , uint32_t IntBits> bool operator!= (Fixed< IntType, IntBits > const & a, unsigned b) inline
Definition at line 1749 of file fixed.h.
 {
     return a != Fixed<IntType, IntBits>(b);
 }
operator!=() [16/20]
template<typename IntType , uint32_t IntBits> bool operator!= (Fixed< IntType, IntBits > const & a, int b) inline
Definition at line 1755 of file fixed.h.
 {
     return a != Fixed<IntType, IntBits>(b);
 }
operator!=() [17/20]
template<typename IntType , uint32_t IntBits> bool operator!= (Fixed< IntType, IntBits > const & a, unsigned short b) inline
Definition at line 1761 of file fixed.h.
 {
     return a != Fixed<IntType, IntBits>(b);
 }
operator!=() [18/20]
template<typename IntType , uint32_t IntBits> bool operator!= (Fixed< IntType, IntBits > const & a, short b) inline
Definition at line 1767 of file fixed.h.
 {
     return a != Fixed<IntType, IntBits>(b);
 }
operator!=() [19/20]
template<typename IntType , uint32_t IntBits> bool operator!= (Fixed< IntType, IntBits > const & a, unsigned char b) inline
Definition at line 1773 of file fixed.h.
 {
     return a != Fixed<IntType, IntBits>(b);
 }
operator!=() [20/20]
template<typename IntType , uint32_t IntBits> bool operator!= (Fixed< IntType, IntBits > const & a, char b) inline
Definition at line 1779 of file fixed.h.
 {
     return a != Fixed<IntType, IntBits>(b);
 }
operator%() [1/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (double a, Fixed< IntType, IntBits > const & b) inline
Definition at line 957 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [2/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (float a, Fixed< IntType, IntBits > const & b) inline
Definition at line 964 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [3/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (uint64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 971 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [4/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (int64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 978 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [5/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (unsigned a, Fixed< IntType, IntBits > const & b) inline
Definition at line 985 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [6/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (int a, Fixed< IntType, IntBits > const & b) inline
Definition at line 992 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [7/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (unsigned short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 999 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [8/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1006 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [9/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (unsigned char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1013 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [10/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1020 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [11/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (Fixed< IntType, IntBits > const & a, double b) inline
Definition at line 1027 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [12/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (Fixed< IntType, IntBits > const & a, float b) inline
Definition at line 1034 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [13/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (Fixed< IntType, IntBits > const & a, uint64_t b) inline
Definition at line 1041 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [14/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (Fixed< IntType, IntBits > const & a, int64_t b) inline
Definition at line 1048 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [15/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (Fixed< IntType, IntBits > const & a, unsigned b) inline
Definition at line 1055 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [16/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (Fixed< IntType, IntBits > const & a, int b) inline
Definition at line 1062 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [17/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (Fixed< IntType, IntBits > const & a, unsigned short b) inline
Definition at line 1069 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [18/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (Fixed< IntType, IntBits > const & a, short b) inline
Definition at line 1076 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [19/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (Fixed< IntType, IntBits > const & a, unsigned char b) inline
Definition at line 1083 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [20/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (Fixed< IntType, IntBits > const & a, char b) inline
Definition at line 1090 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator%() [21/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator% (Fixed< IntType, IntBits > const & a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1097 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp %= b;
 }
operator*() [1/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (double a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1251 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(b);
     return temp *= a;
 }
operator*() [2/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (float a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1258 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(b);
     return temp *= a;
 }
operator*() [3/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (uint64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1265 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(b);
     return temp *= a;
 }
operator*() [4/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (int64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1272 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(b);
     return temp *= a;
 }
operator*() [5/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (unsigned a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1279 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(b);
     return temp *= a;
 }
operator*() [6/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (int a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1286 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(b);
     return temp *= a;
 }
operator*() [7/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (unsigned short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1293 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(b);
     return temp *= a;
 }
operator*() [8/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1300 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(b);
     return temp *= a;
 }
operator*() [9/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (unsigned char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1307 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(b);
     return temp *= a;
 }
operator*() [10/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1314 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(b);
     return temp *= a;
 }
operator*() [11/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (Fixed< IntType, IntBits > const & a, double b) inline
Definition at line 1321 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp *= b;
 }
operator*() [12/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (Fixed< IntType, IntBits > const & a, float b) inline
Definition at line 1328 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp *= b;
 }
operator*() [13/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (Fixed< IntType, IntBits > const & a, uint64_t b) inline
Definition at line 1335 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp *= b;
 }
operator*() [14/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (Fixed< IntType, IntBits > const & a, int64_t b) inline
Definition at line 1342 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp *= b;
 }
operator*() [15/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (Fixed< IntType, IntBits > const & a, unsigned b) inline
Definition at line 1349 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp *= b;
 }
operator*() [16/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (Fixed< IntType, IntBits > const & a, int b) inline
Definition at line 1356 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp *= b;
 }
operator*() [17/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (Fixed< IntType, IntBits > const & a, unsigned short b) inline
Definition at line 1363 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp *= b;
 }
operator*() [18/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (Fixed< IntType, IntBits > const & a, short b) inline
Definition at line 1370 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp *= b;
 }
operator*() [19/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (Fixed< IntType, IntBits > const & a, unsigned char b) inline
Definition at line 1377 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp *= b;
 }
operator*() [20/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (Fixed< IntType, IntBits > const & a, char b) inline
Definition at line 1384 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp *= b;
 }
operator*() [21/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator* (Fixed< IntType, IntBits > const & a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1391 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp *= b;
 }
operator+() [1/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (double a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1104 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [2/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (float a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1111 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [3/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (uint64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1118 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [4/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (int64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1125 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [5/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (unsigned a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1132 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [6/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (int a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1139 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [7/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (unsigned short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1146 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [8/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1153 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [9/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (unsigned char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1160 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [10/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1167 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [11/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (Fixed< IntType, IntBits > const & a, double b) inline
Definition at line 1174 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [12/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (Fixed< IntType, IntBits > const & a, float b) inline
Definition at line 1181 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [13/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (Fixed< IntType, IntBits > const & a, uint64_t b) inline
Definition at line 1188 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [14/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (Fixed< IntType, IntBits > const & a, int64_t b) inline
Definition at line 1195 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [15/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (Fixed< IntType, IntBits > const & a, unsigned b) inline
Definition at line 1202 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [16/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (Fixed< IntType, IntBits > const & a, int b) inline
Definition at line 1209 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [17/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (Fixed< IntType, IntBits > const & a, unsigned short b) inline
Definition at line 1216 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [18/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (Fixed< IntType, IntBits > const & a, short b) inline
Definition at line 1223 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [19/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (Fixed< IntType, IntBits > const & a, unsigned char b) inline
Definition at line 1230 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [20/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (Fixed< IntType, IntBits > const & a, char b) inline
Definition at line 1237 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator+() [21/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator+ (Fixed< IntType, IntBits > const & a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1244 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp += b;
 }
operator-() [1/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (double a, Fixed< IntType, IntBits > const & b) inline
Definition at line 809 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [2/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (float a, Fixed< IntType, IntBits > const & b) inline
Definition at line 817 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [3/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (uint64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 824 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [4/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (int64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 831 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [5/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (unsigned a, Fixed< IntType, IntBits > const & b) inline
Definition at line 838 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [6/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (int a, Fixed< IntType, IntBits > const & b) inline
Definition at line 845 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [7/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (unsigned short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 852 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [8/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 859 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [9/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (unsigned char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 866 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [10/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 873 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [11/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (Fixed< IntType, IntBits > const & a, double b) inline
Definition at line 880 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [12/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (Fixed< IntType, IntBits > const & a, float b) inline
Definition at line 887 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [13/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (Fixed< IntType, IntBits > const & a, uint64_t b) inline
Definition at line 894 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [14/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (Fixed< IntType, IntBits > const & a, int64_t b) inline
Definition at line 901 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [15/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (Fixed< IntType, IntBits > const & a, unsigned b) inline
Definition at line 908 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [16/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (Fixed< IntType, IntBits > const & a, int b) inline
Definition at line 915 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [17/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (Fixed< IntType, IntBits > const & a, unsigned short b) inline
Definition at line 922 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [18/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (Fixed< IntType, IntBits > const & a, short b) inline
Definition at line 929 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [19/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (Fixed< IntType, IntBits > const & a, unsigned char b) inline
Definition at line 936 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [20/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (Fixed< IntType, IntBits > const & a, char b) inline
Definition at line 943 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator-() [21/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator- (Fixed< IntType, IntBits > const & a, Fixed< IntType, IntBits > const & b) inline
Definition at line 950 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp -= b;
 }
operator/() [1/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (double a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1398 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [2/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (float a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1405 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [3/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (uint64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1412 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [4/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (int64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1419 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [5/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (unsigned a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1426 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [6/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (int a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1433 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [7/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (unsigned short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1440 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [8/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1447 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [9/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (unsigned char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1454 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [10/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1461 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [11/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (Fixed< IntType, IntBits > const & a, double b) inline
Definition at line 1468 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [12/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (Fixed< IntType, IntBits > const & a, float b) inline
Definition at line 1475 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [13/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (Fixed< IntType, IntBits > const & a, uint64_t b) inline
Definition at line 1482 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [14/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (Fixed< IntType, IntBits > const & a, int64_t b) inline
Definition at line 1489 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [15/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (Fixed< IntType, IntBits > const & a, unsigned b) inline
Definition at line 1496 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [16/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (Fixed< IntType, IntBits > const & a, int b) inline
Definition at line 1503 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [17/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (Fixed< IntType, IntBits > const & a, unsigned short b) inline
Definition at line 1510 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [18/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (Fixed< IntType, IntBits > const & a, short b) inline
Definition at line 1517 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [19/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (Fixed< IntType, IntBits > const & a, unsigned char b) inline
Definition at line 1524 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [20/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (Fixed< IntType, IntBits > const & a, char b) inline
Definition at line 1531 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator/() [21/21]
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> operator/ (Fixed< IntType, IntBits > const & a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1538 of file fixed.h.
 {
     Fixed<IntType, IntBits> temp(a);
     return temp /= b;
 }
operator<() [1/20]
template<typename IntType , uint32_t IntBits> bool operator< (double a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1785 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) < b;
 }
operator<() [2/20]
template<typename IntType , uint32_t IntBits> bool operator< (float a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1791 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) < b;
 }
operator<() [3/20]
template<typename IntType , uint32_t IntBits> bool operator< (uint64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1797 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) < b;
 }
operator<() [4/20]
template<typename IntType , uint32_t IntBits> bool operator< (int64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1803 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) < b;
 }
operator<() [5/20]
template<typename IntType , uint32_t IntBits> bool operator< (unsigned a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1809 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) < b;
 }
operator<() [6/20]
template<typename IntType , uint32_t IntBits> bool operator< (int a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1815 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) < b;
 }
operator<() [7/20]
template<typename IntType , uint32_t IntBits> bool operator< (unsigned short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1821 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) < b;
 }
operator<() [8/20]
template<typename IntType , uint32_t IntBits> bool operator< (short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1827 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) < b;
 }
operator<() [9/20]
template<typename IntType , uint32_t IntBits> bool operator< (unsigned char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1833 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) < b;
 }
operator<() [10/20]
template<typename IntType , uint32_t IntBits> bool operator< (char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1839 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) < b;
 }
operator<() [11/20]
template<typename IntType , uint32_t IntBits> bool operator< (Fixed< IntType, IntBits > const & a, double b) inline
Definition at line 1845 of file fixed.h.
 {
     return a < Fixed<IntType, IntBits>(b);
 }
operator<() [12/20]
template<typename IntType , uint32_t IntBits> bool operator< (Fixed< IntType, IntBits > const & a, float b) inline
Definition at line 1851 of file fixed.h.
 {
     return a < Fixed<IntType, IntBits>(b);
 }
operator<() [13/20]
template<typename IntType , uint32_t IntBits> bool operator< (Fixed< IntType, IntBits > const & a, uint64_t b) inline
Definition at line 1857 of file fixed.h.
 {
     return a < Fixed<IntType, IntBits>(b);
 }
operator<() [14/20]
template<typename IntType , uint32_t IntBits> bool operator< (Fixed< IntType, IntBits > const & a, int64_t b) inline
Definition at line 1863 of file fixed.h.
 {
     return a < Fixed<IntType, IntBits>(b);
 }
operator<() [15/20]
template<typename IntType , uint32_t IntBits> bool operator< (Fixed< IntType, IntBits > const & a, unsigned b) inline
Definition at line 1869 of file fixed.h.
 {
     return a < Fixed<IntType, IntBits>(b);
 }
operator<() [16/20]
template<typename IntType , uint32_t IntBits> bool operator< (Fixed< IntType, IntBits > const & a, int b) inline
Definition at line 1875 of file fixed.h.
 {
     return a < Fixed<IntType, IntBits>(b);
 }
operator<() [17/20]
template<typename IntType , uint32_t IntBits> bool operator< (Fixed< IntType, IntBits > const & a, unsigned short b) inline
Definition at line 1881 of file fixed.h.
 {
     return a < Fixed<IntType, IntBits>(b);
 }
operator<() [18/20]
template<typename IntType , uint32_t IntBits> bool operator< (Fixed< IntType, IntBits > const & a, short b) inline
Definition at line 1887 of file fixed.h.
 {
     return a < Fixed<IntType, IntBits>(b);
 }
operator<() [19/20]
template<typename IntType , uint32_t IntBits> bool operator< (Fixed< IntType, IntBits > const & a, unsigned char b) inline
Definition at line 1893 of file fixed.h.
 {
     return a < Fixed<IntType, IntBits>(b);
 }
operator<() [20/20]
template<typename IntType , uint32_t IntBits> bool operator< (Fixed< IntType, IntBits > const & a, char b) inline
Definition at line 1899 of file fixed.h.
 {
     return a < Fixed<IntType, IntBits>(b);
 }
operator<=() [1/20]
template<typename IntType , uint32_t IntBits> bool operator<= (double a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2025 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) <= b;
 }
operator<=() [2/20]
template<typename IntType , uint32_t IntBits> bool operator<= (float a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2031 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) <= b;
 }
operator<=() [3/20]
template<typename IntType , uint32_t IntBits> bool operator<= (uint64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2037 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) <= b;
 }
operator<=() [4/20]
template<typename IntType , uint32_t IntBits> bool operator<= (int64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2043 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) <= b;
 }
operator<=() [5/20]
template<typename IntType , uint32_t IntBits> bool operator<= (unsigned a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2049 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) <= b;
 }
operator<=() [6/20]
template<typename IntType , uint32_t IntBits> bool operator<= (int a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2055 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) <= b;
 }
operator<=() [7/20]
template<typename IntType , uint32_t IntBits> bool operator<= (unsigned short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2061 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) <= b;
 }
operator<=() [8/20]
template<typename IntType , uint32_t IntBits> bool operator<= (short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2067 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) <= b;
 }
operator<=() [9/20]
template<typename IntType , uint32_t IntBits> bool operator<= (unsigned char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2073 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) <= b;
 }
operator<=() [10/20]
template<typename IntType , uint32_t IntBits> bool operator<= (char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2079 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) <= b;
 }
operator<=() [11/20]
template<typename IntType , uint32_t IntBits> bool operator<= (Fixed< IntType, IntBits > const & a, double b) inline
Definition at line 2085 of file fixed.h.
 {
     return a <= Fixed<IntType, IntBits>(b);
 }
operator<=() [12/20]
template<typename IntType , uint32_t IntBits> bool operator<= (Fixed< IntType, IntBits > const & a, float b) inline
Definition at line 2091 of file fixed.h.
 {
     return a <= Fixed<IntType, IntBits>(b);
 }
operator<=() [13/20]
template<typename IntType , uint32_t IntBits> bool operator<= (Fixed< IntType, IntBits > const & a, uint64_t b) inline
Definition at line 2097 of file fixed.h.
 {
     return a <= Fixed<IntType, IntBits>(b);
 }
operator<=() [14/20]
template<typename IntType , uint32_t IntBits> bool operator<= (Fixed< IntType, IntBits > const & a, int64_t b) inline
Definition at line 2103 of file fixed.h.
 {
     return a <= Fixed<IntType, IntBits>(b);
 }
operator<=() [15/20]
template<typename IntType , uint32_t IntBits> bool operator<= (Fixed< IntType, IntBits > const & a, unsigned b) inline
Definition at line 2109 of file fixed.h.
 {
     return a <= Fixed<IntType, IntBits>(b);
 }
operator<=() [16/20]
template<typename IntType , uint32_t IntBits> bool operator<= (Fixed< IntType, IntBits > const & a, int b) inline
Definition at line 2115 of file fixed.h.
 {
     return a <= Fixed<IntType, IntBits>(b);
 }
operator<=() [17/20]
template<typename IntType , uint32_t IntBits> bool operator<= (Fixed< IntType, IntBits > const & a, unsigned short b) inline
Definition at line 2121 of file fixed.h.
 {
     return a <= Fixed<IntType, IntBits>(b);
 }
operator<=() [18/20]
template<typename IntType , uint32_t IntBits> bool operator<= (Fixed< IntType, IntBits > const & a, short b) inline
Definition at line 2127 of file fixed.h.
 {
     return a <= Fixed<IntType, IntBits>(b);
 }
operator<=() [19/20]
template<typename IntType , uint32_t IntBits> bool operator<= (Fixed< IntType, IntBits > const & a, unsigned char b) inline
Definition at line 2133 of file fixed.h.
 {
     return a <= Fixed<IntType, IntBits>(b);
 }
operator<=() [20/20]
template<typename IntType , uint32_t IntBits> bool operator<= (Fixed< IntType, IntBits > const & a, char b) inline
Definition at line 2139 of file fixed.h.
 {
     return a <= Fixed<IntType, IntBits>(b);
 }
operator==() [1/20]
template<typename IntType , uint32_t IntBits> bool operator== (double a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1545 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) == b;
 }
operator==() [2/20]
template<typename IntType , uint32_t IntBits> bool operator== (float a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1551 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) == b;
 }
operator==() [3/20]
template<typename IntType , uint32_t IntBits> bool operator== (uint64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1557 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) == b;
 }
operator==() [4/20]
template<typename IntType , uint32_t IntBits> bool operator== (int64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1563 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) == b;
 }
operator==() [5/20]
template<typename IntType , uint32_t IntBits> bool operator== (unsigned a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1569 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) == b;
 }
operator==() [6/20]
template<typename IntType , uint32_t IntBits> bool operator== (int a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1575 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) == b;
 }
operator==() [7/20]
template<typename IntType , uint32_t IntBits> bool operator== (unsigned short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1581 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) == b;
 }
operator==() [8/20]
template<typename IntType , uint32_t IntBits> bool operator== (short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1587 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) == b;
 }
operator==() [9/20]
template<typename IntType , uint32_t IntBits> bool operator== (unsigned char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1593 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) == b;
 }
operator==() [10/20]
template<typename IntType , uint32_t IntBits> bool operator== (char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1599 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) == b;
 }
operator==() [11/20]
template<typename IntType , uint32_t IntBits> bool operator== (Fixed< IntType, IntBits > const & a, double b) inline
Definition at line 1605 of file fixed.h.
 {
     return a == Fixed<IntType, IntBits>(b);
 }
operator==() [12/20]
template<typename IntType , uint32_t IntBits> bool operator== (Fixed< IntType, IntBits > const & a, float b) inline
Definition at line 1611 of file fixed.h.
 {
     return a == Fixed<IntType, IntBits>(b);
 }
operator==() [13/20]
template<typename IntType , uint32_t IntBits> bool operator== (Fixed< IntType, IntBits > const & a, uint64_t b) inline
Definition at line 1617 of file fixed.h.
 {
     return a == Fixed<IntType, IntBits>(b);
 }
operator==() [14/20]
template<typename IntType , uint32_t IntBits> bool operator== (Fixed< IntType, IntBits > const & a, int64_t b) inline
Definition at line 1623 of file fixed.h.
 {
     return a == Fixed<IntType, IntBits>(b);
 }
operator==() [15/20]
template<typename IntType , uint32_t IntBits> bool operator== (Fixed< IntType, IntBits > const & a, unsigned b) inline
Definition at line 1629 of file fixed.h.
 {
     return a == Fixed<IntType, IntBits>(b);
 }
operator==() [16/20]
template<typename IntType , uint32_t IntBits> bool operator== (Fixed< IntType, IntBits > const & a, int b) inline
Definition at line 1635 of file fixed.h.
 {
     return a == Fixed<IntType, IntBits>(b);
 }
operator==() [17/20]
template<typename IntType , uint32_t IntBits> bool operator== (Fixed< IntType, IntBits > const & a, unsigned short b) inline
Definition at line 1641 of file fixed.h.
 {
     return a == Fixed<IntType, IntBits>(b);
 }
operator==() [18/20]
template<typename IntType , uint32_t IntBits> bool operator== (Fixed< IntType, IntBits > const & a, short b) inline
Definition at line 1647 of file fixed.h.
 {
     return a == Fixed<IntType, IntBits>(b);
 }
operator==() [19/20]
template<typename IntType , uint32_t IntBits> bool operator== (Fixed< IntType, IntBits > const & a, unsigned char b) inline
Definition at line 1653 of file fixed.h.
 {
     return a == Fixed<IntType, IntBits>(b);
 }
operator==() [20/20]
template<typename IntType , uint32_t IntBits> bool operator== (Fixed< IntType, IntBits > const & a, char b) inline
Definition at line 1659 of file fixed.h.
 {
     return a == Fixed<IntType, IntBits>(b);
 }
operator>() [1/20]
template<typename IntType , uint32_t IntBits> bool operator> (double a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1905 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) > b;
 }
operator>() [2/20]
template<typename IntType , uint32_t IntBits> bool operator> (float a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1911 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) > b;
 }
operator>() [3/20]
template<typename IntType , uint32_t IntBits> bool operator> (uint64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1917 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) > b;
 }
operator>() [4/20]
template<typename IntType , uint32_t IntBits> bool operator> (int64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1923 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) > b;
 }
operator>() [5/20]
template<typename IntType , uint32_t IntBits> bool operator> (unsigned a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1929 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) > b;
 }
operator>() [6/20]
template<typename IntType , uint32_t IntBits> bool operator> (int a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1935 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) > b;
 }
operator>() [7/20]
template<typename IntType , uint32_t IntBits> bool operator> (unsigned short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1941 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) > b;
 }
operator>() [8/20]
template<typename IntType , uint32_t IntBits> bool operator> (short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1947 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) > b;
 }
operator>() [9/20]
template<typename IntType , uint32_t IntBits> bool operator> (unsigned char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1953 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) > b;
 }
operator>() [10/20]
template<typename IntType , uint32_t IntBits> bool operator> (char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 1959 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) > b;
 }
operator>() [11/20]
template<typename IntType , uint32_t IntBits> bool operator> (Fixed< IntType, IntBits > const & a, double b) inline
Definition at line 1965 of file fixed.h.
 {
     return a > Fixed<IntType, IntBits>(b);
 }
operator>() [12/20]
template<typename IntType , uint32_t IntBits> bool operator> (Fixed< IntType, IntBits > const & a, float b) inline
Definition at line 1971 of file fixed.h.
 {
     return a > Fixed<IntType, IntBits>(b);
 }
operator>() [13/20]
template<typename IntType , uint32_t IntBits> bool operator> (Fixed< IntType, IntBits > const & a, uint64_t b) inline
Definition at line 1977 of file fixed.h.
 {
     return a > Fixed<IntType, IntBits>(b);
 }
operator>() [14/20]
template<typename IntType , uint32_t IntBits> bool operator> (Fixed< IntType, IntBits > const & a, int64_t b) inline
Definition at line 1983 of file fixed.h.
 {
     return a > Fixed<IntType, IntBits>(b);
 }
operator>() [15/20]
template<typename IntType , uint32_t IntBits> bool operator> (Fixed< IntType, IntBits > const & a, unsigned b) inline
Definition at line 1989 of file fixed.h.
 {
     return a > Fixed<IntType, IntBits>(b);
 }
operator>() [16/20]
template<typename IntType , uint32_t IntBits> bool operator> (Fixed< IntType, IntBits > const & a, int b) inline
Definition at line 1995 of file fixed.h.
 {
     return a > Fixed<IntType, IntBits>(b);
 }
operator>() [17/20]
template<typename IntType , uint32_t IntBits> bool operator> (Fixed< IntType, IntBits > const & a, unsigned short b) inline
Definition at line 2001 of file fixed.h.
 {
     return a > Fixed<IntType, IntBits>(b);
 }
operator>() [18/20]
template<typename IntType , uint32_t IntBits> bool operator> (Fixed< IntType, IntBits > const & a, short b) inline
Definition at line 2007 of file fixed.h.
 {
     return a > Fixed<IntType, IntBits>(b);
 }
operator>() [19/20]
template<typename IntType , uint32_t IntBits> bool operator> (Fixed< IntType, IntBits > const & a, unsigned char b) inline
Definition at line 2013 of file fixed.h.
 {
     return a > Fixed<IntType, IntBits>(b);
 }
operator>() [20/20]
template<typename IntType , uint32_t IntBits> bool operator> (Fixed< IntType, IntBits > const & a, char b) inline
Definition at line 2019 of file fixed.h.
 {
     return a > Fixed<IntType, IntBits>(b);
 }
operator>=() [1/20]
template<typename IntType , uint32_t IntBits> bool operator>= (double a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2145 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) >= b;
 }
operator>=() [2/20]
template<typename IntType , uint32_t IntBits> bool operator>= (float a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2151 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) >= b;
 }
operator>=() [3/20]
template<typename IntType , uint32_t IntBits> bool operator>= (uint64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2157 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) >= b;
 }
operator>=() [4/20]
template<typename IntType , uint32_t IntBits> bool operator>= (int64_t a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2163 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) >= b;
 }
operator>=() [5/20]
template<typename IntType , uint32_t IntBits> bool operator>= (unsigned a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2169 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) >= b;
 }
operator>=() [6/20]
template<typename IntType , uint32_t IntBits> bool operator>= (int a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2175 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) >= b;
 }
operator>=() [7/20]
template<typename IntType , uint32_t IntBits> bool operator>= (unsigned short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2181 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) >= b;
 }
operator>=() [8/20]
template<typename IntType , uint32_t IntBits> bool operator>= (short a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2187 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a)>=b;
 }
operator>=() [9/20]
template<typename IntType , uint32_t IntBits> bool operator>= (unsigned char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2193 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) >= b;
 }
operator>=() [10/20]
template<typename IntType , uint32_t IntBits> bool operator>= (char a, Fixed< IntType, IntBits > const & b) inline
Definition at line 2199 of file fixed.h.
 {
     return Fixed<IntType, IntBits>(a) >= b;
 }
operator>=() [11/20]
template<typename IntType , uint32_t IntBits> bool operator>= (Fixed< IntType, IntBits > const & a, double b) inline
Definition at line 2205 of file fixed.h.
 {
     return a >= Fixed<IntType, IntBits>(b);
 }
operator>=() [12/20]
template<typename IntType , uint32_t IntBits> bool operator>= (Fixed< IntType, IntBits > const & a, float b) inline
Definition at line 2211 of file fixed.h.
 {
     return a >= Fixed<IntType, IntBits>(b);
 }
operator>=() [13/20]
template<typename IntType , uint32_t IntBits> bool operator>= (Fixed< IntType, IntBits > const & a, uint64_t b) inline
Definition at line 2217 of file fixed.h.
 {
     return a >= Fixed<IntType, IntBits>(b);
 }
operator>=() [14/20]
template<typename IntType , uint32_t IntBits> bool operator>= (Fixed< IntType, IntBits > const & a, int64_t b) inline
Definition at line 2223 of file fixed.h.
 {
     return a >= Fixed<IntType, IntBits>(b);
 }
operator>=() [15/20]
template<typename IntType , uint32_t IntBits> bool operator>= (Fixed< IntType, IntBits > const & a, unsigned b) inline
Definition at line 2229 of file fixed.h.
 {
     return a >= Fixed<IntType, IntBits>(b);
 }
operator>=() [16/20]
template<typename IntType , uint32_t IntBits> bool operator>= (Fixed< IntType, IntBits > const & a, int b) inline
Definition at line 2235 of file fixed.h.
 {
     return a >= Fixed<IntType, IntBits>(b);
 }
operator>=() [17/20]
template<typename IntType , uint32_t IntBits> bool operator>= (Fixed< IntType, IntBits > const & a, unsigned short b) inline
Definition at line 2241 of file fixed.h.
 {
     return a >= Fixed<IntType, IntBits>(b);
 }
operator>=() [18/20]
template<typename IntType , uint32_t IntBits> bool operator>= (Fixed< IntType, IntBits > const & a, short b) inline
Definition at line 2247 of file fixed.h.
 {
     return a >= Fixed<IntType, IntBits>(b);
 }
operator>=() [19/20]
template<typename IntType , uint32_t IntBits> bool operator>= (Fixed< IntType, IntBits > const & a, unsigned char b) inline
Definition at line 2253 of file fixed.h.
 {
     return a >= Fixed<IntType, IntBits>(b);
 }
operator>=() [20/20]
template<typename IntType , uint32_t IntBits> bool operator>= (Fixed< IntType, IntBits > const & a, char b) inline
Definition at line 2259 of file fixed.h.
 {
     return a >= Fixed<IntType, IntBits>(b);
 }
polar()
template<typename IntType , uint32_t IntBits> std::complex<Fixed<IntType, IntBits> > polar (const Fixed< IntType, IntBits > & rho, const Fixed< IntType, IntBits > & theta) inline
Definition at line 2409 of file fixed.h.
References Fixed< IntType, IntBits >::fixed_half, Fixed< IntType, IntBits >::fixed_half_pi, Fixed< IntType, IntBits >::fixed_max, Fixed< IntType, IntBits >::fixed_one, Fixed< IntType, IntBits >::fixed_pi, Fixed< IntType, IntBits >::fixed_quarter_pi, Fixed< IntType, IntBits >::fixed_two_pi, Fixed< IntType, IntBits >::fixed_zero, leansdr::max(), and Fixed< IntType, IntBits >::sin_cos().
Referenced by leansdr::cstln_lut< SOFTSYMB, 256 >::cstln_lut().
 {
     Fixed<IntType, IntBits> s,c;
     Fixed<IntType, IntBits>::sin_cos(theta,&s,&c);
     return std::complex<Fixed<IntType, IntBits> >(rho * c, rho * s);
 }
sin()
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> sin (Fixed< IntType, IntBits > const & x) inline
Definition at line 2265 of file fixed.h.
References Fixed< IntType, IntBits >::sin().
Referenced by AudioFilter::cheby_sub(), Highpass< Type >::create(), Lowpass< Real >::create(), Bandpass< Real >::create(), Interpolator::createPolyphaseLowPass(), FreqLockComplex::feed(), PhaseLockComplex::feed(), LoRaDemod::feed(), fftfilt::fsinc(), TestMIThread::generate(), TestSourceThread::generate(), leansdr::fast_qpsk_receiver< T >::init_lookup_tables(), leansdr::filtergen::lowpass(), UDPSource::modulateSample(), NFMMod::modulateSample(), ATVMod::modulateSample(), PhaseLock::process(), WFMMod::pull(), rcos(), leansdr::filtergen::root_raised_cosine(), sfft::sfft(), sinc(), WFIR::Sinc(), and WFIR::WindowData().
 {
     return x.sin();
 }
sqrt()
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> sqrt (Fixed< IntType, IntBits > const & x) inline
Definition at line 2283 of file fixed.h.
References Fixed< IntType, IntBits >::sqrt().
Referenced by UDPSource::calculateLevel(), WFMMod::calculateLevel(), AMMod::calculateLevel(), NFMMod::calculateLevel(), FreeDVMod::calculateLevel(), SSBMod::calculateLevel(), ATVMod::calculateLevel(), AudioFilter::cheby_sub(), ATVDemod::demod(), UDPSink::feed(), MagAGC::feedAndGetValue(), MagAGC::hardLimiter(), DSPDeviceSourceEngine::iqCorrections(), DSPDeviceMIMOEngine::iqCorrections(), NFMDemod::NFMDemod(), PhaseDiscriminators::phaseDiscriminator3(), AutoCorrector< T >::process(), AMDemod::processOneSample(), FreeDVDemod::pushSampleToDV(), leansdr::filtergen::root_raised_cosine(), Projector::run(), and WFIR::WindowData().
 {
     return x.sqrt();
 }
tan()
template<typename IntType , uint32_t IntBits> Fixed<IntType, IntBits> tan (Fixed< IntType, IntBits > const & x) inline
Definition at line 2277 of file fixed.h.
References Fixed< IntType, IntBits >::tan().
Referenced by AudioFilter::cheby_sub().
 {
     return x.tan();
 }