SDRAngel: SpectrumScopeComboVis Class Reference
SpectrumScopeComboVis Class Reference
#include <spectrumscopecombovis.h>
Public Member Functions
SpectrumScopeComboVis (SpectrumVis *spectrumVis, ScopeVis *scopeVis)
virtual ~SpectrumScopeComboVis ()
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool positiveOnly)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &message)
Processing of a message. Returns true if message has actually been processed.
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Private Attributes
SpectrumVis * m_spectrumVis
ScopeVis * m_scopeVis
Additional Inherited Members
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 11 of file spectrumscopecombovis.h.
Constructor & Destructor Documentation
SpectrumScopeComboVis()
SpectrumScopeComboVis::SpectrumScopeComboVis (SpectrumVis * spectrumVis, ScopeVis * scopeVis)
Definition at line 6 of file spectrumscopecombovis.cpp.
                                                                                          :
     m_spectrumVis(spectrumVis),
     m_scopeVis(scopeVis)
 {
     setObjectName("SpectrumScopeComboVis");
 }
~SpectrumScopeComboVis()
SpectrumScopeComboVis::~SpectrumScopeComboVis () virtual
Definition at line 13 of file spectrumscopecombovis.cpp.
 {
 }
Member Function Documentation
feed()
void SpectrumScopeComboVis::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool positiveOnly) virtual
Implements BasebandSampleSink.
Definition at line 17 of file spectrumscopecombovis.cpp.
References ScopeVis::feed(), SpectrumVis::feedTriggered(), ScopeVis::getTriggerLocation(), m_scopeVis, and m_spectrumVis.
 {
     (void) positiveOnly;
     m_scopeVis->feed(begin, end, false);
     //SampleVector::const_iterator triggerPoint = m_scopeVis->getTriggerPoint();
     //m_spectrumVis->feedTriggered(triggerPoint, end, positiveOnly);
     int triggerPointLocation = m_scopeVis->getTriggerLocation();
     if ((triggerPointLocation >= 0) && (triggerPointLocation <= end - begin)) {
         m_spectrumVis->feedTriggered(end - triggerPointLocation, end, positiveOnly);
     } else {
         m_spectrumVis->feedTriggered(begin, end, positiveOnly);
     }
 }
handleMessage()
bool SpectrumScopeComboVis::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 43 of file spectrumscopecombovis.cpp.
References SpectrumVis::handleMessage(), ScopeVis::handleMessage(), m_scopeVis, and m_spectrumVis.
 {
     bool spectDone = m_spectrumVis->handleMessage(message);
     bool scopeDone = m_scopeVis->handleMessage(message);
     return (spectDone || scopeDone);
 }
start()
void SpectrumScopeComboVis::start () virtual
Implements BasebandSampleSink.
Definition at line 31 of file spectrumscopecombovis.cpp.
References m_scopeVis, m_spectrumVis, SpectrumVis::start(), and ScopeVis::start().
 {
     m_spectrumVis->start();
     m_scopeVis->start();
 }
stop()
void SpectrumScopeComboVis::stop () virtual
Implements BasebandSampleSink.
Definition at line 37 of file spectrumscopecombovis.cpp.
References m_scopeVis, m_spectrumVis, SpectrumVis::stop(), and ScopeVis::stop().
 {
     m_spectrumVis->stop();
     m_scopeVis->stop();
 }
Member Data Documentation
m_scopeVis
ScopeVis* SpectrumScopeComboVis::m_scopeVis private
Definition at line 24 of file spectrumscopecombovis.h.
Referenced by feed(), handleMessage(), start(), and stop().
m_spectrumVis
SpectrumVis* SpectrumScopeComboVis::m_spectrumVis private
Definition at line 23 of file spectrumscopecombovis.h.
Referenced by feed(), handleMessage(), start(), and stop().
The documentation for this class was generated from the following files:
sdrgui/dsp/spectrumscopecombovis.h
sdrgui/dsp/spectrumscopecombovis.cpp