SDRAngel: SoapySDRInput::MsgReportGainChange Class Reference
SoapySDRInput::MsgReportGainChange Class Reference
#include <soapysdrinput.h>
Public Member Functions
const SoapySDRInputSettings & getSettings () const
bool getGlobalGain () const
bool getIndividualGains () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportGainChange * create (const SoapySDRInputSettings &settings, bool globalGain, bool individualGains)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportGainChange (const SoapySDRInputSettings &settings, bool globalGain, bool individualGains)
Private Attributes
SoapySDRInputSettings m_settings
bool m_globalGain
bool m_individualGains
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 115 of file soapysdrinput.h.
Constructor & Destructor Documentation
MsgReportGainChange()
SoapySDRInput::MsgReportGainChange::MsgReportGainChange (const SoapySDRInputSettings & settings, bool globalGain, bool individualGains) inline private
Definition at line 133 of file soapysdrinput.h.
                                                                                                           :
             Message(),
             m_settings(settings),
             m_globalGain(globalGain),
             m_individualGains(individualGains)
         { }
Member Function Documentation
create()
static MsgReportGainChange* SoapySDRInput::MsgReportGainChange::create (const SoapySDRInputSettings & settings, bool globalGain, bool individualGains) inline static
Definition at line 123 of file soapysdrinput.h.
Referenced by SoapySDRInput::applySettings().
         {
             return new MsgReportGainChange(settings, globalGain, individualGains);
         }
getGlobalGain()
bool SoapySDRInput::MsgReportGainChange::getGlobalGain () const inline
Definition at line 120 of file soapysdrinput.h.
Referenced by SoapySDRInputGui::handleMessage().
 { return m_globalGain; }
getIndividualGains()
bool SoapySDRInput::MsgReportGainChange::getIndividualGains () const inline
Definition at line 121 of file soapysdrinput.h.
Referenced by SoapySDRInputGui::handleMessage().
 { return m_individualGains; }
getSettings()
const SoapySDRInputSettings& SoapySDRInput::MsgReportGainChange::getSettings () const inline
Definition at line 119 of file soapysdrinput.h.
Referenced by SoapySDRInputGui::handleMessage().
 { return m_settings; }
Member Data Documentation
m_globalGain
bool SoapySDRInput::MsgReportGainChange::m_globalGain private
Definition at line 130 of file soapysdrinput.h.
m_individualGains
bool SoapySDRInput::MsgReportGainChange::m_individualGains private
Definition at line 131 of file soapysdrinput.h.
m_settings
SoapySDRInputSettings SoapySDRInput::MsgReportGainChange::m_settings private
Definition at line 129 of file soapysdrinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/soapysdrinput/soapysdrinput.h