SDRAngel: PerseusInput Class Reference
PerseusInput Class Reference
#include <perseusinput.h>
Classes
class MsgConfigurePerseus
class MsgFileRecord
class MsgStartStop
Public Member Functions
PerseusInput (DeviceAPI *deviceAPI)
~PerseusInput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
const std::vector< uint32_t > & getSampleRates () const
Public Member Functions inherited from DeviceSampleSource
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
void setDeviceCenterFrequency (quint64 freq, const PerseusSettings &settings)
bool applySettings (const PerseusSettings &settings, bool force=false)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const PerseusSettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const PerseusSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
FileRecord * m_fileSink
QString m_deviceDescription
PerseusSettings m_settings
bool m_running
PerseusThread * m_perseusThread
perseus_descr * m_perseusDescriptor
std::vector< uint32_t > m_sampleRates
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSource
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Static Public Member Functions inherited from DeviceSampleSource
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots inherited from DeviceSampleSource
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSource
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 36 of file perseusinput.h.
Constructor & Destructor Documentation
PerseusInput()
PerseusInput::PerseusInput (DeviceAPI * deviceAPI)
Definition at line 40 of file perseusinput.cpp.
References arg().
Referenced by PerseusInput::MsgStartStop::MsgStartStop().
                                                :
     m_deviceAPI(deviceAPI),
     m_fileSink(0),
     m_deviceDescription("PerseusInput"),
     m_running(false),
     m_perseusThread(0),
     m_perseusDescriptor(0)
 {
     openDevice();
     m_fileSink = new FileRecord(QString("test_%1.sdriq").arg(m_deviceAPI->getDeviceUID()));
     m_deviceAPI->setNbSourceStreams(1);
     m_deviceAPI->addAncillarySink(m_fileSink);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~PerseusInput()
PerseusInput::~PerseusInput ()
Definition at line 57 of file perseusinput.cpp.
References closeDevice(), m_deviceAPI, m_fileSink, m_networkManager, networkManagerFinished(), and DeviceAPI::removeAncillarySink().
Referenced by PerseusInput::MsgStartStop::MsgStartStop().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     m_deviceAPI->removeAncillarySink(m_fileSink);
     delete m_fileSink;
     closeDevice();
 }
Member Function Documentation
applySettings()
bool PerseusInput::applySettings (const PerseusSettings & settings, bool force = false) private
Definition at line 299 of file perseusinput.cpp.
References DeviceAPI::getDeviceEngineInputMessageQueue(), FileRecord::handleMessage(), i, PerseusSettings::m_adcDither, PerseusSettings::m_adcPreamp, PerseusSettings::m_attenuator, PerseusSettings::m_centerFrequency, m_deviceAPI, PerseusSettings::m_devSampleRateIndex, m_fileSink, PerseusSettings::m_log2Decim, PerseusSettings::m_LOppmTenths, m_perseusDescriptor, m_perseusThread, PerseusSettings::m_reverseAPIAddress, PerseusSettings::m_reverseAPIDeviceIndex, PerseusSettings::m_reverseAPIPort, m_sampleRates, m_settings, PerseusSettings::m_transverterDeltaFrequency, PerseusSettings::m_transverterMode, PerseusSettings::m_useReverseAPI, PerseusSettings::m_wideBand, MessageQueue::push(), setDeviceCenterFrequency(), PerseusThread::setLog2Decimation(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     bool forwardChange = false;
     int sampleRateIndex = settings.m_devSampleRateIndex;
     QList<QString> reverseAPIKeys;
     if ((m_settings.m_devSampleRateIndex != settings.m_devSampleRateIndex) || force)
     {
         reverseAPIKeys.append("devSampleRateIndex");
         forwardChange = true;
         if (settings.m_devSampleRateIndex >= m_sampleRates.size()) {
             sampleRateIndex = m_sampleRates.size() - 1;
         }
         if (m_perseusDescriptor != 0)
         {
             int rate = m_sampleRates[settings.m_devSampleRateIndex < m_sampleRates.size() ? settings.m_devSampleRateIndex: 0];
             int rc;
             for (int i = 0; i < 2; i++) // it turns out that it has to be done twice
             {
                 rc = perseus_set_sampling_rate(m_perseusDescriptor, rate);
                 if (rc < 0) {
                     qCritical("PerseusInput::applySettings: could not set sample rate index %u (%d S/s): %s",
                             settings.m_devSampleRateIndex, rate, perseus_errorstr());
                     break;
                 }
                 else
                 {
                     qDebug("PerseusInput::applySettings: sample rate set to index #%d: %u (%d S/s)",
                             i, settings.m_devSampleRateIndex, rate);
                 }
             }
         }
     }
     if ((m_settings.m_log2Decim != settings.m_log2Decim) || force)
     {
         reverseAPIKeys.append("log2Decim");
         forwardChange = true;
         if (m_perseusThread != 0)
         {
             m_perseusThread->setLog2Decimation(settings.m_log2Decim);
             qDebug("PerseusInput: set decimation to %d", (1<<settings.m_log2Decim));
         }
     }
     if (force || (m_settings.m_centerFrequency != settings.m_centerFrequency)) {
         reverseAPIKeys.append("centerFrequency");
     }
     if (force || (m_settings.m_LOppmTenths != settings.m_LOppmTenths)) {
         reverseAPIKeys.append("LOppmTenths");
     }
     if (force || (m_settings.m_wideBand != settings.m_wideBand)) {
         reverseAPIKeys.append("wideBand");
     }
     if (force || (m_settings.m_transverterMode != settings.m_transverterMode)) {
         reverseAPIKeys.append("transverterMode");
     }
     if (force || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency)) {
         reverseAPIKeys.append("transverterDeltaFrequency");
     }
     if (force || (m_settings.m_centerFrequency != settings.m_centerFrequency)
             || (m_settings.m_LOppmTenths != settings.m_LOppmTenths)
             || (m_settings.m_wideBand != settings.m_wideBand)
             || (m_settings.m_transverterMode != settings.m_transverterMode)
             || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency)
             || (m_settings.m_devSampleRateIndex != settings.m_devSampleRateIndex))
     {
         qint64 deviceCenterFrequency = settings.m_centerFrequency;
         deviceCenterFrequency -= settings.m_transverterMode ? settings.m_transverterDeltaFrequency : 0;
         deviceCenterFrequency = deviceCenterFrequency < 0 ? 0 : deviceCenterFrequency;
         if (m_perseusDescriptor != 0)
         {
             setDeviceCenterFrequency(deviceCenterFrequency, settings);
             qDebug("PerseusInput::applySettings: center freq: %llu Hz", settings.m_centerFrequency);
         }
         forwardChange = true;
     }
     if ((m_settings.m_attenuator != settings.m_attenuator) || force)
     {
         reverseAPIKeys.append("attenuator");
         int rc = perseus_set_attenuator_n(m_perseusDescriptor, (int) settings.m_attenuator);
         if (rc < 0) {
             qWarning("PerseusInput::applySettings: cannot set attenuator to %d dB: %s", (int) settings.m_attenuator*10, perseus_errorstr());
         } else {
             qDebug("PerseusInput::applySettings: attenuator set to %d dB", (int) settings.m_attenuator*10);
         }
     }
     if (force || (m_settings.m_adcDither != settings.m_adcDither)) {
         reverseAPIKeys.append("adcDither");
     }
     if (force || (m_settings.m_adcPreamp != settings.m_adcPreamp)) {
         reverseAPIKeys.append("adcPreamp");
     }
     if ((m_settings.m_adcDither != settings.m_adcDither)
        || (m_settings.m_adcPreamp != settings.m_adcPreamp) || force)
     {
         int rc = perseus_set_adc(m_perseusDescriptor, settings.m_adcDither ? 1 : 0, settings.m_adcPreamp ? 1 : 0);
         if (rc < 0) {
             qWarning("PerseusInput::applySettings: cannot set ADC to dither %s and preamp %s: %s",
                     settings.m_adcDither ? "on" : "off", settings.m_adcPreamp ? "on" : "off", perseus_errorstr());
         } else {
             qDebug("PerseusInput::applySettings: ADC set to dither %s and preamp %s",
                     settings.m_adcDither ? "on" : "off", settings.m_adcPreamp ? "on" : "off");
         }
     }
     if (forwardChange)
     {
         int sampleRate = m_sampleRates[sampleRateIndex]/(1<<settings.m_log2Decim);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, settings.m_centerFrequency);
         m_fileSink->handleMessage(*notif); // forward to file sink
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     m_settings.m_devSampleRateIndex = sampleRateIndex;
     qDebug() << "PerseusInput::applySettings: "
             << " m_LOppmTenths: " << m_settings.m_LOppmTenths
             << " m_devSampleRateIndex: " << m_settings.m_devSampleRateIndex
             << " m_log2Decim: " << m_settings.m_log2Decim
             << " m_transverterMode: " << m_settings.m_transverterMode
             << " m_transverterDeltaFrequency: " << m_settings.m_transverterDeltaFrequency
             << " m_adcDither: " << m_settings.m_adcDither
             << " m_adcPreamp: " << m_settings.m_adcPreamp
             << " m_wideBand: " << m_settings.m_wideBand
             << " m_attenuator: " << m_settings.m_attenuator;
     return true;
 }
closeDevice()
void PerseusInput::closeDevice () private
Definition at line 275 of file perseusinput.cpp.
References m_perseusDescriptor, m_running, and stop().
Referenced by openDevice(), and ~PerseusInput().
 {
     if (m_perseusDescriptor)
     {
         if (m_running) { stop(); }
         perseus_close(m_perseusDescriptor);
     }
 }
deserialize()
bool PerseusInput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSource.
Definition at line 112 of file perseusinput.cpp.
References PerseusInput::MsgConfigurePerseus::create(), PerseusSettings::deserialize(), DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, MessageQueue::push(), and PerseusSettings::resetToDefaults().
Referenced by PerseusInput::MsgStartStop::MsgStartStop().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigurePerseus* message = MsgConfigurePerseus::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigurePerseus* messageToGUI = MsgConfigurePerseus::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void PerseusInput::destroy () virtual
Implements DeviceSampleSource.
Definition at line 66 of file perseusinput.cpp.
Referenced by PerseusInput::MsgStartStop::MsgStartStop().
 {
     delete this;
 }
getCenterFrequency()
quint64 PerseusInput::getCenterFrequency () const virtual
Center frequency exposed by the source.
Implements DeviceSampleSource.
Definition at line 147 of file perseusinput.cpp.
References PerseusSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & PerseusInput::getDeviceDescription () const virtual
Implements DeviceSampleSource.
Definition at line 134 of file perseusinput.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getSampleRate()
int PerseusInput::getSampleRate () const virtual
Sample rate exposed by the source.
Implements DeviceSampleSource.
Definition at line 138 of file perseusinput.cpp.
References PerseusSettings::m_devSampleRateIndex, PerseusSettings::m_log2Decim, m_sampleRates, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     if (m_settings.m_devSampleRateIndex < m_sampleRates.size()) {
         return (m_sampleRates[m_settings.m_devSampleRateIndex] / (1<<m_settings.m_log2Decim));
     } else {
         return (m_sampleRates[0] / (1<<m_settings.m_log2Decim));
     }
 }
getSampleRates()
const std::vector<uint32_t>& PerseusInput::getSampleRates () const inline
Definition at line 143 of file perseusinput.h.
References m_sampleRates.
Referenced by PerseusGui::PerseusGui(), and webapiFormatDeviceReport().
 { return m_sampleRates; }
handleMessage()
bool PerseusInput::handleMessage (const Message & message) virtual
Implements DeviceSampleSource.
Definition at line 167 of file perseusinput.cpp.
References applySettings(), FileRecord::genUniqueFileName(), DeviceAPI::getDeviceUID(), PerseusInput::MsgConfigurePerseus::getForce(), PerseusInput::MsgConfigurePerseus::getSettings(), PerseusInput::MsgFileRecord::getStartStop(), PerseusInput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), m_deviceAPI, PerseusSettings::m_fileRecordName, m_fileSink, m_settings, PerseusSettings::m_useReverseAPI, Message::match(), FileRecord::setFileName(), DeviceAPI::startDeviceEngine(), FileRecord::startRecording(), DeviceAPI::stopDeviceEngine(), FileRecord::stopRecording(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (MsgConfigurePerseus::match(message))
     {
         MsgConfigurePerseus& conf = (MsgConfigurePerseus&) message;
         qDebug() << "PerseusInput::handleMessage: MsgConfigurePerseus";
         bool success = applySettings(conf.getSettings(), conf.getForce());
         if (!success) {
             qDebug("MsgConfigurePerseus::handleMessage: Perseus config error");
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "PerseusInput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else if (MsgFileRecord::match(message))
     {
         MsgFileRecord& conf = (MsgFileRecord&) message;
         qDebug() << "PerseusInput::handleMessage: MsgFileRecord: " << conf.getStartStop();
         if (conf.getStartStop())
         {
             if (m_settings.m_fileRecordName.size() != 0) {
                 m_fileSink->setFileName(m_settings.m_fileRecordName);
             } else {
                 m_fileSink->genUniqueFileName(m_deviceAPI->getDeviceUID());
             }
             m_fileSink->startRecording();
         }
         else
         {
             m_fileSink->stopRecording();
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void PerseusInput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSource.
Definition at line 71 of file perseusinput.cpp.
References applySettings(), and m_settings.
Referenced by PerseusInput::MsgStartStop::MsgStartStop().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void PerseusInput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 705 of file perseusinput.cpp.
Referenced by ~PerseusInput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "PerseusInput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("PerseusInput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openDevice()
bool PerseusInput::openDevice () private
Definition at line 233 of file perseusinput.cpp.
References closeDevice(), DeviceAPI::getSamplingDeviceSerial(), DevicePerseus::getSequenceFromSerial(), i, DevicePerseus::instance(), m_deviceAPI, m_perseusDescriptor, DeviceSampleSource::m_sampleFifo, m_sampleRates, PERSEUS_NBSAMPLES, and SampleSinkFifo::setSize().
 {
     if (m_perseusDescriptor != 0) {
         closeDevice();
     }
     if (!m_sampleFifo.setSize(PERSEUS_NBSAMPLES))
     {
         qCritical("PerseusInput::start: could not allocate SampleFifo");
         return false;
     }
     m_deviceAPI->getSamplingDeviceSerial();
     int deviceSequence = DevicePerseus::instance().getSequenceFromSerial(m_deviceAPI->getSamplingDeviceSerial().toStdString());
     if ((m_perseusDescriptor = perseus_open(deviceSequence)) == 0)
     {
         qCritical("PerseusInput::openDevice: cannot open device: %s", perseus_errorstr());
         return false;
     }
     int buf[32];
     m_sampleRates.clear();
     if (perseus_get_sampling_rates(m_perseusDescriptor, buf, sizeof(buf)/sizeof(buf[0])) < 0)
     {
         qCritical("PerseusInput::openDevice: cannot get sampling rates: %s", perseus_errorstr());
         perseus_close(m_perseusDescriptor);
         return false;
     }
     else
     {
          for (int i = 0; (i < 32) && (buf[i] != 0); i++)
          {
              qDebug("PerseusInput::openDevice: sample rate: %d", buf[i]);
              m_sampleRates.push_back(buf[i]);
          }
     }
     return true;
 }
serialize()
QByteArray PerseusInput::serialize () const virtual
Implements DeviceSampleSource.
Definition at line 107 of file perseusinput.cpp.
References m_settings, and PerseusSettings::serialize().
Referenced by PerseusInput::MsgStartStop::MsgStartStop().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void PerseusInput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSource.
Definition at line 152 of file perseusinput.cpp.
References PerseusInput::MsgConfigurePerseus::create(), PerseusSettings::m_centerFrequency, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     PerseusSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigurePerseus* message = MsgConfigurePerseus::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigurePerseus* messageToGUI = MsgConfigurePerseus::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setDeviceCenterFrequency()
void PerseusInput::setDeviceCenterFrequency (quint64 freq, const PerseusSettings & settings) private
Definition at line 284 of file perseusinput.cpp.
References PerseusSettings::m_LOppmTenths, m_perseusDescriptor, and PerseusSettings::m_wideBand.
Referenced by applySettings().
 {
     qint64 df = ((qint64)freq_hz * settings.m_LOppmTenths) / 10000000LL;
     freq_hz += df;
     // wideband flag is inverted since parameter is set to enable preselection filters
     int rc = perseus_set_ddc_center_freq(m_perseusDescriptor, freq_hz, settings.m_wideBand ? 0 : 1);
     if (rc < 0) {
         qWarning("PerseusInput::setDeviceCenterFrequency: could not set frequency to %llu Hz: %s", freq_hz, perseus_errorstr());
     } else {
         qDebug("PerseusInput::setDeviceCenterFrequency: frequency set to %llu Hz", freq_hz);
     }
 }
setMessageQueueToGUI()
virtual void PerseusInput::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSource.
Definition at line 111 of file perseusinput.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSource::m_guiMessageQueue.
Referenced by PerseusGui::PerseusGui().
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void PerseusInput::setSampleRate (int sampleRate) inline virtual
For when the source sample rate is set externally.
Implements DeviceSampleSource.
Definition at line 114 of file perseusinput.h.
References getCenterFrequency(), handleMessage(), setCenterFrequency(), webapiReportGet(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
start()
bool PerseusInput::start () virtual
Implements DeviceSampleSource.
Definition at line 76 of file perseusinput.cpp.
References applySettings(), PerseusSettings::m_log2Decim, m_perseusDescriptor, m_perseusThread, m_running, DeviceSampleSource::m_sampleFifo, m_settings, PerseusThread::setLog2Decimation(), PerseusThread::startWork(), and stop().
Referenced by PerseusInput::MsgStartStop::MsgStartStop().
 {
     if (m_running) stop();
     // start / stop streaming is done in the thread.
     m_perseusThread = new PerseusThread(m_perseusDescriptor, &m_sampleFifo);
     qDebug("PerseusInput::start: thread created");
     applySettings(m_settings, true);
     m_perseusThread->setLog2Decimation(m_settings.m_log2Decim);
     m_perseusThread->startWork();
     m_running = true;
     return true;
 }
stop()
void PerseusInput::stop () virtual
Implements DeviceSampleSource.
Definition at line 95 of file perseusinput.cpp.
References m_perseusThread, m_running, and PerseusThread::stopWork().
Referenced by closeDevice(), PerseusInput::MsgStartStop::MsgStartStop(), and start().
 {
     if (m_perseusThread != 0)
     {
         m_perseusThread->stopWork();
         delete m_perseusThread;
         m_perseusThread = 0;
     }
     m_running = false;
 }
webapiFormatDeviceReport()
void PerseusInput::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 603 of file perseusinput.cpp.
References SWGSDRangel::SWGDeviceReport::getPerseusReport(), SWGSDRangel::SWGPerseusReport::getSampleRates(), getSampleRates(), and SWGSDRangel::SWGPerseusReport::setSampleRates().
Referenced by webapiReportGet().
 {
     response.getPerseusReport()->setSampleRates(new QList<SWGSDRangel::SWGSampleRate*>);
     for (std::vector<uint32_t>::const_iterator it = getSampleRates().begin(); it != getSampleRates().end(); ++it)
     {
         response.getPerseusReport()->getSampleRates()->append(new SWGSDRangel::SWGSampleRate);
         response.getPerseusReport()->getSampleRates()->back()->setRate(*it);
     }
 }
webapiFormatDeviceSettings()
void PerseusInput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const PerseusSettings & settings) private
Definition at line 572 of file perseusinput.cpp.
References SWGSDRangel::SWGPerseusSettings::getFileRecordName(), SWGSDRangel::SWGDeviceSettings::getPerseusSettings(), SWGSDRangel::SWGPerseusSettings::getReverseApiAddress(), PerseusSettings::m_adcDither, PerseusSettings::m_adcPreamp, PerseusSettings::m_attenuator, PerseusSettings::m_centerFrequency, PerseusSettings::m_devSampleRateIndex, PerseusSettings::m_fileRecordName, PerseusSettings::m_log2Decim, PerseusSettings::m_LOppmTenths, PerseusSettings::m_reverseAPIAddress, PerseusSettings::m_reverseAPIDeviceIndex, PerseusSettings::m_reverseAPIPort, PerseusSettings::m_transverterDeltaFrequency, PerseusSettings::m_transverterMode, PerseusSettings::m_useReverseAPI, PerseusSettings::m_wideBand, SWGSDRangel::SWGPerseusSettings::setAdcDither(), SWGSDRangel::SWGPerseusSettings::setAdcPreamp(), SWGSDRangel::SWGPerseusSettings::setAttenuator(), SWGSDRangel::SWGPerseusSettings::setCenterFrequency(), SWGSDRangel::SWGPerseusSettings::setDevSampleRateIndex(), SWGSDRangel::SWGPerseusSettings::setFileRecordName(), SWGSDRangel::SWGPerseusSettings::setLog2Decim(), SWGSDRangel::SWGPerseusSettings::setLOppmTenths(), SWGSDRangel::SWGPerseusSettings::setReverseApiAddress(), SWGSDRangel::SWGPerseusSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGPerseusSettings::setReverseApiPort(), SWGSDRangel::SWGPerseusSettings::setTransverterDeltaFrequency(), SWGSDRangel::SWGPerseusSettings::setTransverterMode(), SWGSDRangel::SWGPerseusSettings::setUseReverseApi(), and SWGSDRangel::SWGPerseusSettings::setWideBand().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getPerseusSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getPerseusSettings()->setLOppmTenths(settings.m_LOppmTenths);
     response.getPerseusSettings()->setDevSampleRateIndex(settings.m_devSampleRateIndex);
     response.getPerseusSettings()->setLog2Decim(settings.m_log2Decim);
     response.getPerseusSettings()->setAdcDither(settings.m_adcDither ? 1 : 0);
     response.getPerseusSettings()->setAdcPreamp(settings.m_adcPreamp ? 1 : 0);
     response.getPerseusSettings()->setWideBand(settings.m_wideBand ? 1 : 0);
     response.getPerseusSettings()->setAttenuator((int) settings.m_attenuator);
     response.getPerseusSettings()->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     response.getPerseusSettings()->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     if (response.getPerseusSettings()->getFileRecordName()) {
         *response.getPerseusSettings()->getFileRecordName() = settings.m_fileRecordName;
     } else {
         response.getPerseusSettings()->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     response.getPerseusSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getPerseusSettings()->getReverseApiAddress()) {
         *response.getPerseusSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getPerseusSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getPerseusSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getPerseusSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int PerseusInput::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 561 of file perseusinput.cpp.
References SWGSDRangel::SWGDeviceReport::getPerseusReport(), SWGSDRangel::SWGPerseusReport::init(), SWGSDRangel::SWGDeviceReport::setPerseusReport(), and webapiFormatDeviceReport().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setPerseusReport(new SWGSDRangel::SWGPerseusReport());
     response.getPerseusReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void PerseusInput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const PerseusSettings & settings, bool force) private
Definition at line 614 of file perseusinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), SWGSDRangel::SWGDeviceSettings::getPerseusSettings(), PerseusSettings::m_adcDither, PerseusSettings::m_adcPreamp, PerseusSettings::m_attenuator, PerseusSettings::m_centerFrequency, m_deviceAPI, PerseusSettings::m_devSampleRateIndex, PerseusSettings::m_fileRecordName, PerseusSettings::m_log2Decim, PerseusSettings::m_LOppmTenths, m_networkManager, m_networkRequest, PerseusSettings::m_reverseAPIAddress, PerseusSettings::m_reverseAPIDeviceIndex, PerseusSettings::m_reverseAPIPort, PerseusSettings::m_transverterDeltaFrequency, PerseusSettings::m_transverterMode, PerseusSettings::m_wideBand, SWGSDRangel::SWGPerseusSettings::setAdcDither(), SWGSDRangel::SWGPerseusSettings::setAdcPreamp(), SWGSDRangel::SWGPerseusSettings::setAttenuator(), SWGSDRangel::SWGPerseusSettings::setCenterFrequency(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGPerseusSettings::setDevSampleRateIndex(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGPerseusSettings::setFileRecordName(), SWGSDRangel::SWGPerseusSettings::setLog2Decim(), SWGSDRangel::SWGPerseusSettings::setLOppmTenths(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGDeviceSettings::setPerseusSettings(), SWGSDRangel::SWGPerseusSettings::setTransverterDeltaFrequency(), SWGSDRangel::SWGPerseusSettings::setTransverterMode(), and SWGSDRangel::SWGPerseusSettings::setWideBand().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("Perseus"));
     swgDeviceSettings->setPerseusSettings(new SWGSDRangel::SWGPerseusSettings());
     SWGSDRangel::SWGPerseusSettings *swgPerseusSettings = swgDeviceSettings->getPerseusSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgPerseusSettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("LOppmTenths") || force) {
         swgPerseusSettings->setLOppmTenths(settings.m_LOppmTenths);
     }
     if (deviceSettingsKeys.contains("devSampleRateIndex") || force) {
         swgPerseusSettings->setDevSampleRateIndex(settings.m_devSampleRateIndex);
     }
     if (deviceSettingsKeys.contains("log2Decim") || force) {
         swgPerseusSettings->setLog2Decim(settings.m_log2Decim);
     }
     if (deviceSettingsKeys.contains("adcDither") || force) {
         swgPerseusSettings->setAdcDither(settings.m_adcDither ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("adcPreamp") || force) {
         swgPerseusSettings->setAdcPreamp(settings.m_adcPreamp ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("wideBand") || force) {
         swgPerseusSettings->setWideBand(settings.m_wideBand ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("attenuator") || force) {
         swgPerseusSettings->setAttenuator((int) settings.m_attenuator);
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency") || force) {
         swgPerseusSettings->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     }
     if (deviceSettingsKeys.contains("transverterMode") || force) {
         swgPerseusSettings->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("fileRecordName") || force) {
         swgPerseusSettings->setFileRecordName(new QString(settings.m_fileRecordName));
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void PerseusInput::webapiReverseSendStartStop (bool start) private
Definition at line 677 of file perseusinput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, PerseusSettings::m_reverseAPIAddress, PerseusSettings::m_reverseAPIDeviceIndex, PerseusSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("Perseus"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int PerseusInput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 461 of file perseusinput.cpp.
References PerseusInput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int PerseusInput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 452 of file perseusinput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int PerseusInput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 480 of file perseusinput.cpp.
References SWGSDRangel::SWGDeviceSettings::getPerseusSettings(), SWGSDRangel::SWGPerseusSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setPerseusSettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setPerseusSettings(new SWGSDRangel::SWGPerseusSettings());
     response.getPerseusSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int PerseusInput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSource.
Definition at line 491 of file perseusinput.cpp.
References PerseusInput::MsgConfigurePerseus::create(), SWGSDRangel::SWGPerseusSettings::getAdcDither(), SWGSDRangel::SWGPerseusSettings::getAdcPreamp(), SWGSDRangel::SWGPerseusSettings::getAttenuator(), SWGSDRangel::SWGPerseusSettings::getCenterFrequency(), SWGSDRangel::SWGPerseusSettings::getDevSampleRateIndex(), SWGSDRangel::SWGPerseusSettings::getFileRecordName(), SWGSDRangel::SWGPerseusSettings::getLog2Decim(), SWGSDRangel::SWGPerseusSettings::getLOppmTenths(), SWGSDRangel::SWGDeviceSettings::getPerseusSettings(), SWGSDRangel::SWGPerseusSettings::getReverseApiAddress(), SWGSDRangel::SWGPerseusSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGPerseusSettings::getReverseApiPort(), SWGSDRangel::SWGPerseusSettings::getTransverterDeltaFrequency(), SWGSDRangel::SWGPerseusSettings::getTransverterMode(), SWGSDRangel::SWGPerseusSettings::getUseReverseApi(), SWGSDRangel::SWGPerseusSettings::getWideBand(), PerseusSettings::m_adcDither, PerseusSettings::m_adcPreamp, PerseusSettings::m_attenuator, PerseusSettings::m_centerFrequency, PerseusSettings::m_devSampleRateIndex, PerseusSettings::m_fileRecordName, DeviceSampleSource::m_guiMessageQueue, DeviceSampleSource::m_inputMessageQueue, PerseusSettings::m_log2Decim, PerseusSettings::m_LOppmTenths, PerseusSettings::m_reverseAPIAddress, PerseusSettings::m_reverseAPIDeviceIndex, PerseusSettings::m_reverseAPIPort, m_settings, PerseusSettings::m_transverterDeltaFrequency, PerseusSettings::m_transverterMode, PerseusSettings::m_useReverseAPI, PerseusSettings::m_wideBand, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     PerseusSettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getPerseusSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("LOppmTenths")) {
         settings.m_LOppmTenths = response.getPerseusSettings()->getLOppmTenths();
     }
     if (deviceSettingsKeys.contains("devSampleRateIndex")) {
         settings.m_devSampleRateIndex = response.getPerseusSettings()->getDevSampleRateIndex();
     }
     if (deviceSettingsKeys.contains("log2Decim")) {
         settings.m_log2Decim = response.getPerseusSettings()->getLog2Decim();
     }
     if (deviceSettingsKeys.contains("adcDither")) {
         settings.m_adcDither = response.getPerseusSettings()->getAdcDither() != 0;
     }
     if (deviceSettingsKeys.contains("adcPreamp")) {
         settings.m_adcPreamp = response.getPerseusSettings()->getAdcPreamp() != 0;
     }
     if (deviceSettingsKeys.contains("wideBand")) {
         settings.m_wideBand = response.getPerseusSettings()->getWideBand() != 0;
     }
     if (deviceSettingsKeys.contains("attenuator")) {
         int attenuator = response.getPerseusSettings()->getAttenuator();
         attenuator = attenuator < 0 ? 0 : attenuator > 3 ? 3 : attenuator;
         settings.m_attenuator = (PerseusSettings::Attenuator) attenuator;
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency")) {
         settings.m_transverterDeltaFrequency = response.getPerseusSettings()->getTransverterDeltaFrequency();
     }
     if (deviceSettingsKeys.contains("transverterMode")) {
         settings.m_transverterMode = response.getPerseusSettings()->getTransverterMode() != 0;
     }
     if (deviceSettingsKeys.contains("fileRecordName")) {
         settings.m_fileRecordName = *response.getPerseusSettings()->getFileRecordName();
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getPerseusSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getPerseusSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getPerseusSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getPerseusSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigurePerseus *msg = MsgConfigurePerseus::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigurePerseus *msgToGUI = MsgConfigurePerseus::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_deviceAPI
DeviceAPI* PerseusInput::m_deviceAPI private
Definition at line 146 of file perseusinput.h.
Referenced by applySettings(), handleMessage(), openDevice(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~PerseusInput().
m_deviceDescription
QString PerseusInput::m_deviceDescription private
Definition at line 148 of file perseusinput.h.
Referenced by getDeviceDescription().
m_fileSink
FileRecord* PerseusInput::m_fileSink private
Definition at line 147 of file perseusinput.h.
Referenced by applySettings(), handleMessage(), and ~PerseusInput().
m_networkManager
QNetworkAccessManager* PerseusInput::m_networkManager private
Definition at line 154 of file perseusinput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~PerseusInput().
m_networkRequest
QNetworkRequest PerseusInput::m_networkRequest private
Definition at line 155 of file perseusinput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_perseusDescriptor
perseus_descr* PerseusInput::m_perseusDescriptor private
Definition at line 152 of file perseusinput.h.
Referenced by applySettings(), closeDevice(), openDevice(), setDeviceCenterFrequency(), and start().
m_perseusThread
PerseusThread* PerseusInput::m_perseusThread private
Definition at line 151 of file perseusinput.h.
Referenced by applySettings(), start(), and stop().
m_running
bool PerseusInput::m_running private
Definition at line 150 of file perseusinput.h.
Referenced by closeDevice(), start(), and stop().
m_sampleRates
std::vector<uint32_t> PerseusInput::m_sampleRates private
Definition at line 153 of file perseusinput.h.
Referenced by applySettings(), getSampleRate(), getSampleRates(), and openDevice().
m_settings
PerseusSettings PerseusInput::m_settings private
Definition at line 149 of file perseusinput.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), serialize(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
The documentation for this class was generated from the following files:
plugins/samplesource/perseus/perseusinput.h
plugins/samplesource/perseus/perseusinput.cpp