SDRAngel: CWKeyer Class Reference
CWKeyer Class Reference
#include <cwkeyer.h>
Inherits QObject.
Classes
class MsgConfigureCWKeyer
Public Types
enum CWKeyIambicState { KeySilent, KeyDot, KeyDash }
enum CWTextState {
TextStart, TextStartChar, TextStartElement, TextElement,
TextCharSpace, TextWordSpace, TextEnd, TextStop
}
Public Member Functions
CWKeyer ()
~CWKeyer ()
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
void setSampleRate (int sampleRate)
const CWKeyerSettings & getSettings () const
void reset ()
CWSmoother & getCWSmoother ()
int getSample ()
bool eom ()
void resetText ()
void stopText ()
void setKeyboardDots ()
void setKeyboardDashes ()
void setKeyboardSilence ()
Static Public Member Functions
static void webapiSettingsPutPatch (const QStringList &channelSettingsKeys, CWKeyerSettings &cwKeyerSettings, SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings)
static void webapiFormatChannelSettings (SWGSDRangel::SWGCWKeyerSettings *apiCwKeyerSettings, const CWKeyerSettings &cwKeyerSettings)
Private Slots
void handleInputMessages ()
Private Member Functions
void applySettings (const CWKeyerSettings &settings, bool force=false)
bool handleMessage (const Message &cmd)
void nextStateIambic ()
void nextStateText ()
Private Attributes
QMutex m_mutex
CWKeyerSettings m_settings
MessageQueue m_inputMessageQueue
int m_dotLength
dot length in samples
int m_textPointer
int m_elementPointer
int m_samplePointer
bool m_elementSpace
bool m_characterSpace
bool m_key
bool m_dot
bool m_dash
bool m_elementOn
signed char m_asciiChar
CWKeyIambicState m_keyIambicState
CWTextState m_textState
CWSmoother m_cwSmoother
Static Private Attributes
static const signed char m_asciiToMorse [128][7]
Detailed Description
Definition at line 52 of file cwkeyer.h.
Member Enumeration Documentation
CWKeyIambicState
enum CWKeyer::CWKeyIambicState
Enumerator
KeySilent
KeyDot
KeyDash
Definition at line 79 of file cwkeyer.h.
     {
         KeySilent,
         KeyDot,
         KeyDash
     };
CWTextState
enum CWKeyer::CWTextState
Enumerator
TextStart
TextStartChar
TextStartElement
TextElement
TextCharSpace
TextWordSpace
TextEnd
TextStop
Definition at line 86 of file cwkeyer.h.
     {
         TextStart,
         TextStartChar,
         TextStartElement,
         TextElement,
         TextCharSpace,
         TextWordSpace,
         TextEnd,
         TextStop
     };
Constructor & Destructor Documentation
CWKeyer()
CWKeyer::CWKeyer ()
Definition at line 163 of file cwkeyer.cpp.
References applySettings(), handleInputMessages(), m_inputMessageQueue, and m_settings.
                  :
     m_mutex(QMutex::Recursive),
     m_textPointer(0),
     m_elementPointer(0),
     m_samplePointer(0),
     m_elementSpace(false),
     m_characterSpace(false),
     m_key(false),
     m_dot(false),
     m_dash(false),
     m_elementOn(false),
     m_asciiChar('\0'),
     m_keyIambicState(KeySilent),
     m_textState(TextStart)
 {
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
     applySettings(m_settings, true);
 }
~CWKeyer()
CWKeyer::~CWKeyer ()
Definition at line 182 of file cwkeyer.cpp.
 {
 }
Member Function Documentation
applySettings()
void CWKeyer::applySettings (const CWKeyerSettings & settings, bool force = false) private
Definition at line 552 of file cwkeyer.cpp.
References CWKeyerSettings::CWDashes, CWKeyerSettings::CWDots, CWKeyerSettings::CWKeyboard, CWKeyerSettings::CWText, CWKeyerSettings::m_mode, CWSmoother::m_mutex, CWKeyerSettings::m_sampleRate, CWKeyerSettings::m_text, and CWKeyerSettings::m_wpm.
Referenced by CWKeyer().
 {
     if ((m_settings.m_wpm != settings.m_wpm)
      || (m_settings.m_sampleRate != settings.m_sampleRate) || force)
     {
         QMutexLocker mutexLocker(&m_mutex);
         m_dotLength = (int) (0.24f * settings.m_sampleRate * (5.0f / settings.m_wpm));
         m_cwSmoother.setNbFadeSamples(m_dotLength/5); // 20% the dot time
     }
     if ((m_settings.m_mode != settings.m_mode) || force)
     {
         QMutexLocker mutexLocker(&m_mutex);
         if (settings.m_mode == CWKeyerSettings::CWText)
         {
             m_textState = TextStart;
         }
         else if (settings.m_mode == CWKeyerSettings::CWDots)
         {
             m_dot = true;
             m_dash = false;
             m_keyIambicState = KeySilent;
         }
         else if (settings.m_mode == CWKeyerSettings::CWDashes)
         {
             m_dot = false;
             m_dash = true;
             m_keyIambicState = KeySilent;
         }
         else if (settings.m_mode == CWKeyerSettings::CWKeyboard)
         {
             m_dot = false;
             m_dash = false;
             m_keyIambicState = KeySilent;
         }
     }
     if ((m_settings.m_text != settings.m_text) || force)
     {
         QMutexLocker mutexLocker(&m_mutex);
         m_textState = TextStart;
     }
     m_settings = settings;
 }
deserialize()
bool CWKeyer::deserialize (const QByteArray & data)
eom()
bool CWKeyer::eom ()
Definition at line 418 of file cwkeyer.cpp.
References m_settings, CWKeyerSettings::m_text, and m_textPointer.
 {
     return !(m_textPointer < m_settings.m_text.length());
 }
getCWSmoother()
CWSmoother& CWKeyer::getCWSmoother () inline
Definition at line 111 of file cwkeyer.h.
Referenced by WFMMod::pullAF(), AMMod::pullAF(), NFMMod::pullAF(), FreeDVMod::pullAF(), and SSBMod::pullAF().
 { return m_cwSmoother; }
getInputMessageQueue()
MessageQueue* CWKeyer::getInputMessageQueue () inline
Get the queue for asynchronous inbound communication.
Definition at line 104 of file cwkeyer.h.
Referenced by CWKeyerGUI::applySettings(), AMMod::webapiSettingsPutPatch(), WFMMod::webapiSettingsPutPatch(), NFMMod::webapiSettingsPutPatch(), SSBMod::webapiSettingsPutPatch(), and FreeDVMod::webapiSettingsPutPatch().
getSample()
int CWKeyer::getSample ()
Definition at line 194 of file cwkeyer.cpp.
References CWKeyerSettings::CWDashes, CWKeyerSettings::CWDots, CWKeyerSettings::CWKeyboard, CWKeyerSettings::CWText, m_dash, m_dot, m_key, CWKeyerSettings::m_keyboardIambic, CWKeyerSettings::m_mode, m_mutex, m_settings, nextStateIambic(), and nextStateText().
Referenced by WFMMod::pullAF(), AMMod::pullAF(), NFMMod::pullAF(), FreeDVMod::pullAF(), and SSBMod::pullAF().
 {
     QMutexLocker mutexLocker(&m_mutex);
     if (m_settings.m_mode == CWKeyerSettings::CWText)
     {
         nextStateText();
         return m_key ? 1 : 0;
     }
     else if ((m_settings.m_mode == CWKeyerSettings::CWDots) || (m_settings.m_mode == CWKeyerSettings::CWDashes))
     {
         nextStateIambic();
         return m_key ? 1 : 0;
     }
     else if (m_settings.m_mode == CWKeyerSettings::CWKeyboard)
     {
         if (m_settings.m_keyboardIambic)
         {
             nextStateIambic();
             return m_key ? 1 : 0;
         }
         else
         {
             return (m_dot || m_dash) ? 1 : 0;
         }
     }
     else
     {
         return 0;
     }
 }
getSettings()
const CWKeyerSettings& CWKeyer::getSettings () const inline
Definition at line 107 of file cwkeyer.h.
Referenced by CWKeyerGUI::keyboardKeyPressed(), CWKeyerGUI::setCWKeyer(), WFMMod::webapiFormatChannelSettings(), AMMod::webapiFormatChannelSettings(), NFMMod::webapiFormatChannelSettings(), FreeDVMod::webapiFormatChannelSettings(), SSBMod::webapiFormatChannelSettings(), WFMMod::webapiReverseSendSettings(), AMMod::webapiReverseSendSettings(), NFMMod::webapiReverseSendSettings(), FreeDVMod::webapiReverseSendSettings(), SSBMod::webapiReverseSendSettings(), AMMod::webapiSettingsPutPatch(), WFMMod::webapiSettingsPutPatch(), NFMMod::webapiSettingsPutPatch(), SSBMod::webapiSettingsPutPatch(), and FreeDVMod::webapiSettingsPutPatch().
 { return m_settings; }
handleInputMessages
void CWKeyer::handleInputMessages () private slot
Definition at line 540 of file cwkeyer.cpp.
Referenced by CWKeyer().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (handleMessage(*message)) {
             delete message;
         }
     }
 }
handleMessage()
bool CWKeyer::handleMessage (const Message & cmd) private
Definition at line 525 of file cwkeyer.cpp.
References CWKeyer::MsgConfigureCWKeyer::getForce(), and CWKeyer::MsgConfigureCWKeyer::getSettings().
 {
     if (MsgConfigureCWKeyer::match(cmd))
     {
         MsgConfigureCWKeyer& cfg = (MsgConfigureCWKeyer&) cmd;
         qDebug() << "CWKeyer::handleMessage: MsgConfigureCWKeyer";
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     return true;
 }
nextStateIambic()
void CWKeyer::nextStateIambic () private
Definition at line 226 of file cwkeyer.cpp.
References KeyDash, KeyDot, KeySilent, m_dash, m_dot, m_dotLength, m_key, m_keyIambicState, and m_samplePointer.
Referenced by getSample(), and nextStateText().
 {
     switch (m_keyIambicState)
     {
     case KeySilent:
         if (m_dot)
         {
             m_keyIambicState = KeyDot;
             m_samplePointer = 0;
         }
         else if (m_dash)
         {
             m_keyIambicState = KeyDash;
             m_samplePointer = 0;
         }
         m_key = false;
         break;
     case KeyDot:
         if (m_samplePointer < m_dotLength) // dot key
         {
             m_key = true;
             m_samplePointer++;
         }
         else if (m_samplePointer < 2*m_dotLength) // dot silence (+1 dot length)
         {
             m_key = false;
             m_samplePointer++;
         }
         else // end
         {
             if (m_dash)
             {
                 m_keyIambicState = KeyDash;
             }
             else if (!m_dot)
             {
                 m_keyIambicState = KeySilent;
             }
             m_samplePointer = 0;
             m_key = false;
         }
         break;
     case KeyDash:
         if (m_samplePointer < 3*m_dotLength) // dash key
         {
             m_key = true;
             m_samplePointer++;
         }
         else if (m_samplePointer < 4*m_dotLength) // dash silence (+1 dot length)
         {
             m_key = false;
             m_samplePointer++;
         }
         else // end
         {
             if (m_dot)
             {
                 m_keyIambicState = KeyDot;
             }
             else if (!m_dash)
             {
                 m_keyIambicState = KeySilent;
             }
             m_samplePointer = 0;
             m_key = false;
         }
         break;
     default:
         m_samplePointer = 0;
         m_key = false;
         break;
     }
 }
nextStateText()
void CWKeyer::nextStateText () private
Definition at line 303 of file cwkeyer.cpp.
References KeySilent, m_asciiChar, m_asciiToMorse, m_dash, m_dot, m_dotLength, m_elementPointer, m_key, m_keyIambicState, CWKeyerSettings::m_loop, m_samplePointer, m_settings, CWKeyerSettings::m_text, m_textPointer, m_textState, nextStateIambic(), TextCharSpace, TextElement, TextEnd, TextStart, TextStartChar, TextStartElement, TextStop, and TextWordSpace.
Referenced by getSample().
 {
     switch (m_textState)
     {
     case TextStart:
         m_samplePointer = 0;
         m_elementPointer = 0;
         m_textPointer = 0;
         m_textState = TextStartChar;
         m_key = false;
         m_dot = false;
         m_dash = false;
         break;
     case TextStartChar:
         m_samplePointer = 0;
         m_elementPointer = 0;
         if (m_textPointer < m_settings.m_text.length())
         {
             m_asciiChar = (m_settings.m_text.at(m_textPointer)).toLatin1();
 //            qDebug() << "CWKeyer::nextStateText: TextStartChar: " << m_asciiChar;
             if (m_asciiChar < 0) { // non ASCII
                 m_asciiChar = 0;
             }
             if (m_asciiChar == ' ')
             {
                 m_textState = TextWordSpace;
             }
             else
             {
                 m_textState = TextStartElement;
             }
             m_textPointer++;
         }
         else // end of text
         {
             m_textState = TextEnd;
         }
         break;
     case TextStartElement:
         m_samplePointer = 0;
 //        qDebug() << "CWKeyer::nextStateText: TextStartElement: " << (int) m_asciiToMorse[m_asciiChar][m_elementPointer];
         if (m_asciiToMorse[(uint8_t)(m_asciiChar&0x7F)][m_elementPointer] == -1) // end of morse character
         {
             m_elementPointer = 0;
             m_textState = TextCharSpace;
         }
         else
         {
             if (m_asciiToMorse[(uint8_t)(m_asciiChar&0x7F)][m_elementPointer] == 0) // dot
             {
                 m_dot = true;
                 m_dash = false;
             }
             else // dash
             {
                 m_dot = false;
                 m_dash = true;
             }
             m_keyIambicState = KeySilent; // reset iambic state
             nextStateIambic(); // init dash or dot
             m_dot = false; // release keys
             m_dash = false;
             m_textState = TextElement;
             m_elementPointer++;
         }
         break;
     case TextElement:
         nextStateIambic(); // dash or dot
         if (m_keyIambicState == KeySilent) // done
         {
             m_textState = TextStartElement; // next element
         }
         break;
     case TextCharSpace:
         if (m_samplePointer < 2*m_dotLength) // - 1 dot length space from element
         {
             m_samplePointer++;
             m_key = false;
         }
         else
         {
             m_textState = TextStartChar;
         }
         break;
     case TextWordSpace:
         if (m_samplePointer < 4*m_dotLength) // - 3 dot length space from character
         {
             m_samplePointer++;
             m_key = false;
         }
         else
         {
             m_textState = TextStartChar;
         }
         break;
     case TextEnd:
         if (m_settings.m_loop)
         {
             m_textState = TextStart;
         }
         m_key = false;
         m_dot = false;
         m_dash = false;
         break;
     case TextStop:
     default:
         m_key = false;
         m_dot = false;
         m_dash = false;
         break;
     }
 }
reset()
void CWKeyer::reset () inline
Definition at line 109 of file cwkeyer.h.
Referenced by AMMod::AMMod(), WFMMod::applyChannelSettings(), FreeDVMod::FreeDVMod(), NFMMod::NFMMod(), SSBMod::SSBMod(), and WFMMod::WFMMod().
 { m_keyIambicState = KeySilent; }
resetText()
void CWKeyer::resetText () inline
Definition at line 114 of file cwkeyer.h.
Referenced by CWKeyerGUI::on_playStop_toggled().
 { m_textState = TextStart; }
resetToDefaults()
void CWKeyer::resetToDefaults ()
serialize()
QByteArray CWKeyer::serialize () const
setKeyboardDashes()
void CWKeyer::setKeyboardDashes ()
Definition at line 430 of file cwkeyer.cpp.
References KeySilent, m_dash, m_dot, and m_keyIambicState.
Referenced by CWKeyerGUI::keyboardKeyPressed().
 {
     m_dot = false;
     m_dash = true;
     m_keyIambicState = KeySilent;
 }
setKeyboardDots()
void CWKeyer::setKeyboardDots ()
Definition at line 423 of file cwkeyer.cpp.
References KeySilent, m_dash, m_dot, and m_keyIambicState.
Referenced by CWKeyerGUI::keyboardKeyPressed().
 {
     m_dot = true;
     m_dash = false;
     m_keyIambicState = KeySilent;
 }
setKeyboardSilence()
void CWKeyer::setKeyboardSilence ()
Definition at line 437 of file cwkeyer.cpp.
References m_dash, and m_dot.
Referenced by CWKeyerGUI::keyboardKeyPressed().
 {
     m_dot = false;
     m_dash = false;
 }
setSampleRate()
void CWKeyer::setSampleRate (int sampleRate)
Definition at line 186 of file cwkeyer.cpp.
References CWKeyer::MsgConfigureCWKeyer::create(), m_inputMessageQueue, CWKeyerSettings::m_sampleRate, m_settings, and MessageQueue::push().
Referenced by AMMod::AMMod(), AMMod::applyAudioSampleRate(), NFMMod::applyAudioSampleRate(), SSBMod::applyAudioSampleRate(), WFMMod::applyChannelSettings(), FreeDVMod::FreeDVMod(), NFMMod::NFMMod(), SSBMod::SSBMod(), and WFMMod::WFMMod().
 {
     CWKeyerSettings settings = m_settings;
     settings.m_sampleRate = sampleRate;
     MsgConfigureCWKeyer *msg = MsgConfigureCWKeyer::create(settings, false);
     m_inputMessageQueue.push(msg);
 }
stopText()
void CWKeyer::stopText () inline
Definition at line 115 of file cwkeyer.h.
Referenced by CWKeyerGUI::on_playStop_toggled().
 { m_textState = TextStop; }
webapiFormatChannelSettings()
void CWKeyer::webapiFormatChannelSettings (SWGSDRangel::SWGCWKeyerSettings * apiCwKeyerSettings, const CWKeyerSettings & cwKeyerSettings) static
Definition at line 637 of file cwkeyer.cpp.
References SWGSDRangel::SWGCWKeyerSettings::getText(), CWKeyerSettings::m_dashKey, CWKeyerSettings::m_dashKeyModifiers, CWKeyerSettings::m_dotKey, CWKeyerSettings::m_dotKeyModifiers, CWKeyerSettings::m_keyboardIambic, CWKeyerSettings::m_loop, CWKeyerSettings::m_mode, CWKeyerSettings::m_sampleRate, CWKeyerSettings::m_text, CWKeyerSettings::m_wpm, SWGSDRangel::SWGCWKeyerSettings::setDashKey(), SWGSDRangel::SWGCWKeyerSettings::setDashKeyModifiers(), SWGSDRangel::SWGCWKeyerSettings::setDotKey(), SWGSDRangel::SWGCWKeyerSettings::setDotKeyModifiers(), SWGSDRangel::SWGCWKeyerSettings::setKeyboardIambic(), SWGSDRangel::SWGCWKeyerSettings::setLoop(), SWGSDRangel::SWGCWKeyerSettings::setMode(), SWGSDRangel::SWGCWKeyerSettings::setSampleRate(), SWGSDRangel::SWGCWKeyerSettings::setText(), and SWGSDRangel::SWGCWKeyerSettings::setWpm().
Referenced by WFMMod::webapiFormatChannelSettings(), AMMod::webapiFormatChannelSettings(), NFMMod::webapiFormatChannelSettings(), FreeDVMod::webapiFormatChannelSettings(), SSBMod::webapiFormatChannelSettings(), WFMMod::webapiReverseSendCWSettings(), AMMod::webapiReverseSendCWSettings(), NFMMod::webapiReverseSendCWSettings(), FreeDVMod::webapiReverseSendCWSettings(), SSBMod::webapiReverseSendCWSettings(), WFMMod::webapiReverseSendSettings(), AMMod::webapiReverseSendSettings(), NFMMod::webapiReverseSendSettings(), FreeDVMod::webapiReverseSendSettings(), and SSBMod::webapiReverseSendSettings().
 {
     apiCwKeyerSettings->setLoop(cwKeyerSettings.m_loop ? 1 : 0);
     apiCwKeyerSettings->setMode((int) cwKeyerSettings.m_mode);
     apiCwKeyerSettings->setSampleRate(cwKeyerSettings.m_sampleRate);
     if (apiCwKeyerSettings->getText()) {
         *apiCwKeyerSettings->getText() = cwKeyerSettings.m_text;
     } else {
         apiCwKeyerSettings->setText(new QString(cwKeyerSettings.m_text));
     }
     apiCwKeyerSettings->setWpm(cwKeyerSettings.m_wpm);
     apiCwKeyerSettings->setKeyboardIambic(cwKeyerSettings.m_keyboardIambic ? 1 : 0);
     apiCwKeyerSettings->setDotKey((int) cwKeyerSettings.m_dotKey);
     apiCwKeyerSettings->setDotKeyModifiers((unsigned int) cwKeyerSettings.m_dotKeyModifiers);
     apiCwKeyerSettings->setDashKey((int) cwKeyerSettings.m_dashKey);
     apiCwKeyerSettings->setDashKeyModifiers((unsigned int) cwKeyerSettings.m_dashKeyModifiers);
 }
webapiSettingsPutPatch()
void CWKeyer::webapiSettingsPutPatch (const QStringList & channelSettingsKeys, CWKeyerSettings & cwKeyerSettings, SWGSDRangel::SWGCWKeyerSettings * apiCwKeyerSettings) static
Definition at line 599 of file cwkeyer.cpp.
References SWGSDRangel::SWGCWKeyerSettings::getDashKey(), SWGSDRangel::SWGCWKeyerSettings::getDashKeyModifiers(), SWGSDRangel::SWGCWKeyerSettings::getDotKey(), SWGSDRangel::SWGCWKeyerSettings::getDotKeyModifiers(), SWGSDRangel::SWGCWKeyerSettings::getKeyboardIambic(), SWGSDRangel::SWGCWKeyerSettings::getLoop(), SWGSDRangel::SWGCWKeyerSettings::getMode(), SWGSDRangel::SWGCWKeyerSettings::getSampleRate(), SWGSDRangel::SWGCWKeyerSettings::getText(), SWGSDRangel::SWGCWKeyerSettings::getWpm(), CWKeyerSettings::m_dashKey, CWKeyerSettings::m_dashKeyModifiers, CWKeyerSettings::m_dotKey, CWKeyerSettings::m_dotKeyModifiers, CWKeyerSettings::m_loop, CWKeyerSettings::m_mode, CWKeyerSettings::m_sampleRate, CWKeyerSettings::m_text, and CWKeyerSettings::m_wpm.
Referenced by AMMod::webapiSettingsPutPatch(), WFMMod::webapiSettingsPutPatch(), NFMMod::webapiSettingsPutPatch(), SSBMod::webapiSettingsPutPatch(), and FreeDVMod::webapiSettingsPutPatch().
 {
     if (channelSettingsKeys.contains("cwKeyer.loop")) {
         cwKeyerSettings.m_loop = apiCwKeyerSettings->getLoop() != 0;
     }
     if (channelSettingsKeys.contains("cwKeyer.mode")) {
         cwKeyerSettings.m_mode = (CWKeyerSettings::CWMode) apiCwKeyerSettings->getMode();
     }
     if (channelSettingsKeys.contains("cwKeyer.text")) {
         cwKeyerSettings.m_text = *apiCwKeyerSettings->getText();
     }
     if (channelSettingsKeys.contains("cwKeyer.sampleRate")) {
         cwKeyerSettings.m_sampleRate = apiCwKeyerSettings->getSampleRate();
     }
     if (channelSettingsKeys.contains("cwKeyer.wpm")) {
         cwKeyerSettings.m_wpm = apiCwKeyerSettings->getWpm();
     }
     if (channelSettingsKeys.contains("cwKeyer.keyboardIambic")) {
         cwKeyerSettings.m_wpm = apiCwKeyerSettings->getKeyboardIambic() != 0;
     }
     if (channelSettingsKeys.contains("cwKeyer.dotKey")) {
         cwKeyerSettings.m_dotKey = (Qt::Key) apiCwKeyerSettings->getDotKey();
     }
     if (channelSettingsKeys.contains("cwKeyer.dotKeyModifiers")) {
         cwKeyerSettings.m_dotKeyModifiers = (Qt::KeyboardModifiers) apiCwKeyerSettings->getDotKeyModifiers();
     }
     if (channelSettingsKeys.contains("cwKeyer.dashKey")) {
         cwKeyerSettings.m_dashKey = (Qt::Key) apiCwKeyerSettings->getDashKey();
     }
     if (channelSettingsKeys.contains("cwKeyer.dashKeyModifiers")) {
         cwKeyerSettings.m_dashKeyModifiers = (Qt::KeyboardModifiers) apiCwKeyerSettings->getDashKeyModifiers();
     }
 }
Member Data Documentation
m_asciiChar
signed char CWKeyer::m_asciiChar private
Definition at line 145 of file cwkeyer.h.
Referenced by nextStateText().
m_asciiToMorse
const signed char CWKeyer::m_asciiToMorse static private
0: dot 1: dash -1: end of sequence
Definition at line 150 of file cwkeyer.h.
Referenced by nextStateText().
m_characterSpace
bool CWKeyer::m_characterSpace private
Definition at line 140 of file cwkeyer.h.
m_cwSmoother
CWSmoother CWKeyer::m_cwSmoother private
Definition at line 148 of file cwkeyer.h.
m_dash
bool CWKeyer::m_dash private
Definition at line 143 of file cwkeyer.h.
Referenced by getSample(), nextStateIambic(), nextStateText(), setKeyboardDashes(), setKeyboardDots(), and setKeyboardSilence().
m_dot
bool CWKeyer::m_dot private
Definition at line 142 of file cwkeyer.h.
Referenced by getSample(), nextStateIambic(), nextStateText(), setKeyboardDashes(), setKeyboardDots(), and setKeyboardSilence().
m_dotLength
int CWKeyer::m_dotLength private
dot length in samples
Definition at line 135 of file cwkeyer.h.
Referenced by nextStateIambic(), and nextStateText().
m_elementOn
bool CWKeyer::m_elementOn private
Definition at line 144 of file cwkeyer.h.
m_elementPointer
int CWKeyer::m_elementPointer private
Definition at line 137 of file cwkeyer.h.
Referenced by nextStateText().
m_elementSpace
bool CWKeyer::m_elementSpace private
Definition at line 139 of file cwkeyer.h.
m_inputMessageQueue
MessageQueue CWKeyer::m_inputMessageQueue private
Definition at line 134 of file cwkeyer.h.
Referenced by CWKeyer(), and setSampleRate().
m_key
bool CWKeyer::m_key private
Definition at line 141 of file cwkeyer.h.
Referenced by getSample(), nextStateIambic(), and nextStateText().
m_keyIambicState
CWKeyIambicState CWKeyer::m_keyIambicState private
Definition at line 146 of file cwkeyer.h.
Referenced by nextStateIambic(), nextStateText(), setKeyboardDashes(), and setKeyboardDots().
m_mutex
QMutex CWKeyer::m_mutex private
Definition at line 132 of file cwkeyer.h.
Referenced by getSample().
m_samplePointer
int CWKeyer::m_samplePointer private
Definition at line 138 of file cwkeyer.h.
Referenced by nextStateIambic(), and nextStateText().
m_settings
CWKeyerSettings CWKeyer::m_settings private
Definition at line 133 of file cwkeyer.h.
Referenced by CWKeyer(), eom(), getSample(), nextStateText(), and setSampleRate().
m_textPointer
int CWKeyer::m_textPointer private
Definition at line 136 of file cwkeyer.h.
Referenced by eom(), and nextStateText().
m_textState
CWTextState CWKeyer::m_textState private
Definition at line 147 of file cwkeyer.h.
Referenced by nextStateText().
The documentation for this class was generated from the following files:
sdrbase/dsp/cwkeyer.h
sdrbase/dsp/cwkeyer.cpp