SDRAngel: FileSource::MsgConfigureChannelizer Class Reference
FileSource::MsgConfigureChannelizer Class Reference
#include <filesource.h>
Public Member Functions
int getLog2Interp () const
int getFilterChainHash () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureChannelizer * create (unsigned int m_log2Interp, unsigned int m_filterChainHash)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureChannelizer (unsigned int log2Interp, unsigned int filterChainHash)
Private Attributes
unsigned int m_log2Interp
unsigned int m_filterChainHash
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 48 of file filesource.h.
Constructor & Destructor Documentation
MsgConfigureChannelizer()
FileSource::MsgConfigureChannelizer::MsgConfigureChannelizer (unsigned int log2Interp, unsigned int filterChainHash) inline private
Definition at line 63 of file filesource.h.
Referenced by create().
                                                                                        :
             Message(),
             m_log2Interp(log2Interp),
             m_filterChainHash(filterChainHash)
         { }
Member Function Documentation
create()
static MsgConfigureChannelizer* FileSource::MsgConfigureChannelizer::create (unsigned int m_log2Interp, unsigned int m_filterChainHash) inline static
Definition at line 55 of file filesource.h.
References MsgConfigureChannelizer().
Referenced by FileSourceGUI::applyChannelSettings().
{
             return new MsgConfigureChannelizer(m_log2Interp, m_filterChainHash);
         }
getFilterChainHash()
int FileSource::MsgConfigureChannelizer::getFilterChainHash () const inline
Definition at line 53 of file filesource.h.
References m_filterChainHash.
Referenced by FileSource::handleMessage().
 { return m_filterChainHash; }
getLog2Interp()
int FileSource::MsgConfigureChannelizer::getLog2Interp () const inline
Definition at line 52 of file filesource.h.
References m_log2Interp.
Referenced by FileSource::handleMessage().
 { return m_log2Interp; }
Member Data Documentation
m_filterChainHash
unsigned int FileSource::MsgConfigureChannelizer::m_filterChainHash private
Definition at line 61 of file filesource.h.
Referenced by getFilterChainHash().
m_log2Interp
unsigned int FileSource::MsgConfigureChannelizer::m_log2Interp private
Definition at line 60 of file filesource.h.
Referenced by getLog2Interp().
The documentation for this class was generated from the following file:
plugins/channeltx/filesource/filesource.h