SDRAngel: IntHalfbandFilterEOF< HBFilterOrder > Class Template Reference
IntHalfbandFilterEOF< HBFilterOrder > Class Template Reference
#include <inthalfbandfiltereof.h>
Public Member Functions
IntHalfbandFilterEOF ()
bool workDecimateCenter (float *x, float *y)
void myDecimate (float x1, float y1, float *x2, float *y2)
void myInterpolateZeroStuffing (float *x1, float *y1, float *x2, float *y2)
void myInterpolate (float *x1, float *y1, float *x2, float *y2)
void myInterpolateInf (float *x1, float *y1, float *x2, float *y2, float *x3, float *y3, float *x4, float *y4)
void myInterpolateSup (float *x1, float *y1, float *x2, float *y2, float *x3, float *y3, float *x4, float *y4)
Protected Member Functions
void storeSample (float x, float y)
void advancePointer ()
void doFIR (float *x, float *y)
void doInterpolateFIR (float *x, float *y)
Protected Attributes
float m_even [2][HBFIRFilterTraits< HBFilterOrder >::hbOrder]
float m_odd [2][HBFIRFilterTraits< HBFilterOrder >::hbOrder]
float m_samples [HBFIRFilterTraits< HBFilterOrder >::hbOrder][2]
int m_ptr
int m_size
int m_state
Detailed Description
template<uint32_t HBFilterOrder>
class IntHalfbandFilterEOF< HBFilterOrder >
Definition at line 33 of file inthalfbandfiltereof.h.
Constructor & Destructor Documentation
IntHalfbandFilterEOF()
template<uint32_t HBFilterOrder> IntHalfbandFilterEOF< HBFilterOrder >::IntHalfbandFilterEOF ()
Definition at line 237 of file inthalfbandfiltereof.h.
 {
     m_size = HBFIRFilterTraits<HBFilterOrder>::hbOrder/2;
     for (int i = 0; i < 2*m_size; i++)
     {
         m_even[0][i] = 0.0f;
         m_even[1][i] = 0.0f;
         m_odd[0][i] = 0.0f;
         m_odd[1][i] = 0.0f;
         m_samples[i][0] = 0.0f;
         m_samples[i][1] = 0.0f;
     }
     m_ptr = 0;
     m_state = 0;
 }
Member Function Documentation
advancePointer()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEOF< HBFilterOrder >::advancePointer () inline protected
Definition at line 169 of file inthalfbandfiltereof.h.
Referenced by IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::myDecimate(), IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::myInterpolateZeroStuffing(), and IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::workDecimateCenter().
     {
         m_ptr = m_ptr + 1 < 2*m_size ? m_ptr + 1: 0;
     }
doFIR()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEOF< HBFilterOrder >::doFIR (float * x, float * y) inline protected
Definition at line 174 of file inthalfbandfiltereof.h.
Referenced by IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::myDecimate(), IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::myInterpolateZeroStuffing(), and IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::workDecimateCenter().
     {
         float iAcc = 0;
         float qAcc = 0;
         int a = m_ptr/2 + m_size; // tip pointer
         int b = m_ptr/2 + 1; // tail pointer
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             if ((m_ptr % 2) == 0)
             {
                 iAcc += (m_even[0][a] + m_even[0][b]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
                 qAcc += (m_even[1][a] + m_even[1][b]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
             }
             else
             {
                 iAcc += (m_odd[0][a] + m_odd[0][b]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
                 qAcc += (m_odd[1][a] + m_odd[1][b]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
             }
             a -= 1;
             b += 1;
         }
         if ((m_ptr % 2) == 0)
         {
             iAcc += m_odd[0][m_ptr/2 + m_size/2] * 0.5f;
             qAcc += m_odd[1][m_ptr/2 + m_size/2] * 0.5f;
         }
         else
         {
             iAcc += m_even[0][m_ptr/2 + m_size/2 + 1] * 0.5f;
             qAcc += m_even[1][m_ptr/2 + m_size/2 + 1] * 0.5f;
         }
         *x = iAcc; // HB_SHIFT incorrect do not loose the gained bit
         *y = qAcc;
     }
doInterpolateFIR()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEOF< HBFilterOrder >::doInterpolateFIR (float * x, float * y) inline protected
Definition at line 214 of file inthalfbandfiltereof.h.
Referenced by IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::myInterpolate().
     {
         qint32 iAcc = 0;
         qint32 qAcc = 0;
         qint16 a = m_ptr;
         qint16 b = m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder / 2) - 1;
         // go through samples in buffer
         for (int i = 0; i < HBFIRFilterTraits<HBFilterOrder>::hbOrder / 4; i++)
         {
             iAcc += (m_samples[a][0] + m_samples[b][0]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
             qAcc += (m_samples[a][1] + m_samples[b][1]) * HBFIRFilterTraits<HBFilterOrder>::hbCoeffsF[i];
             a++;
             b--;
         }
         *x = iAcc * SDR_RX_SCALED;
         *y = qAcc * SDR_RX_SCALED;
     }
myDecimate()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEOF< HBFilterOrder >::myDecimate (float x1, float y1, float * x2, float * y2) inline
Definition at line 64 of file inthalfbandfiltereof.h.
Referenced by DecimatorsFF::decimate16_cen(), DecimatorsFI::decimate16_cen(), DecimatorsFI::decimate16_inf(), DecimatorsFF::decimate16_inf(), DecimatorsFF::decimate16_sup(), DecimatorsFI::decimate16_sup(), DecimatorsFF::decimate2_cen(), DecimatorsFI::decimate2_cen(), DecimatorsFF::decimate32_cen(), DecimatorsFI::decimate32_cen(), DecimatorsFI::decimate32_inf(), DecimatorsFF::decimate32_inf(), DecimatorsFI::decimate32_sup(), DecimatorsFF::decimate32_sup(), DecimatorsFF::decimate4_cen(), DecimatorsFI::decimate4_cen(), DecimatorsFI::decimate64_cen(), DecimatorsFF::decimate64_cen(), DecimatorsFF::decimate64_inf(), DecimatorsFI::decimate64_inf(), DecimatorsFI::decimate64_sup(), DecimatorsFF::decimate64_sup(), DecimatorsFI::decimate8_cen(), DecimatorsFF::decimate8_cen(), DecimatorsFI::decimate8_inf(), DecimatorsFF::decimate8_inf(), DecimatorsFI::decimate8_sup(), and DecimatorsFF::decimate8_sup().
     {
         storeSample(x1, y1);
         advancePointer();
         storeSample(*x2, *y2);
         doFIR(x2, y2);
         advancePointer();
     }
myInterpolate()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEOF< HBFilterOrder >::myInterpolate (float * x1, float * y1, float * x2, float * y2) inline
Optimized upsampler by 2 not calculating FIR with inserted null samples
Definition at line 87 of file inthalfbandfiltereof.h.
Referenced by IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::myInterpolateInf(), and IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::myInterpolateSup().
     {
         // insert sample into ring double buffer
         m_samples[m_ptr][0] = *x1;
         m_samples[m_ptr][1] = *y1;
         m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][0] = *x1;
         m_samples[m_ptr + HBFIRFilterTraits<HBFilterOrder>::hbOrder/2][1] = *y1;
         // advance pointer
         if (m_ptr < (HBFIRFilterTraits<HBFilterOrder>::hbOrder/2) - 1) {
             m_ptr++;
         } else {
             m_ptr = 0;
         }
         // first output sample calculated with the middle peak
         *x1 = m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][0];
         *y1 = m_samples[m_ptr + (HBFIRFilterTraits<HBFilterOrder>::hbOrder/4) - 1][1];
         // second sample calculated with the filter
         doInterpolateFIR(x2, y2);
     }
myInterpolateInf()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEOF< HBFilterOrder >::myInterpolateInf (float * x1, float * y1, float * x2, float * y2, float * x3, float * y3, float * x4, float * y4) inline
Definition at line 110 of file inthalfbandfiltereof.h.
     {
         myInterpolate(x1, y1, x2, y2);
         myInterpolate(x3, y3, x4, y4);
         // rotation
         qint32 x;
         x = *x1;
         *x1 = *y1;
         *y1 = -x;
         *x2 = -*x2;
         *y2 = -*y2;
         x = *x3;
         *x3 = -*y3;
         *y3 = x;
     }
myInterpolateSup()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEOF< HBFilterOrder >::myInterpolateSup (float * x1, float * y1, float * x2, float * y2, float * x3, float * y3, float * x4, float * y4) inline
Definition at line 126 of file inthalfbandfiltereof.h.
     {
         myInterpolate(x1, y1, x2, y2);
         myInterpolate(x3, y3, x4, y4);
         // rotation
         qint32 x;
         x = *x1;
         *x1 = -*y1;
         *y1 = x;
         *x2 = -*x2;
         *y2 = -*y2;
         x = *x3;
         *x3 = *y3;
         *y3 = -x;
     }
myInterpolateZeroStuffing()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEOF< HBFilterOrder >::myInterpolateZeroStuffing (float * x1, float * y1, float * x2, float * y2) inline
Simple zero stuffing and filter
Definition at line 75 of file inthalfbandfiltereof.h.
     {
         storeSample(*x1, *y1);
         doFIR(x1, y1);
         advancePointer();
         storeSample(0, 0);
         doFIR(x2, y2);
         advancePointer();
     }
storeSample()
template<uint32_t HBFilterOrder> void IntHalfbandFilterEOF< HBFilterOrder >::storeSample (float x, float y) inline protected
Definition at line 151 of file inthalfbandfiltereof.h.
Referenced by IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::myDecimate(), IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::myInterpolateZeroStuffing(), and IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::workDecimateCenter().
     {
         if ((m_ptr % 2) == 0)
         {
             m_even[0][m_ptr/2] = x;
             m_even[1][m_ptr/2] = y;
             m_even[0][m_ptr/2 + m_size] = x;
             m_even[1][m_ptr/2 + m_size] = y;
         }
         else
         {
             m_odd[0][m_ptr/2] = x;
             m_odd[1][m_ptr/2] = y;
             m_odd[0][m_ptr/2 + m_size] = x;
             m_odd[1][m_ptr/2 + m_size] = y;
         }
     }
workDecimateCenter()
template<uint32_t HBFilterOrder> bool IntHalfbandFilterEOF< HBFilterOrder >::workDecimateCenter (float * x, float * y) inline
Definition at line 37 of file inthalfbandfiltereof.h.
     {
         // insert sample into ring-buffer
         storeSample(*x, *y);
         switch(m_state)
         {
             case 0:
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 1;
                 // tell caller we don't have a new sample
                 return false;
             default:
                 // save result
                 doFIR(x, y);
                 // advance write-pointer
                 advancePointer();
                 // next state
                 m_state = 0;
                 // tell caller we have a new sample
                 return true;
         }
     }
Member Data Documentation
m_even
template<uint32_t HBFilterOrder> float IntHalfbandFilterEOF< HBFilterOrder >::m_even[2][HBFIRFilterTraits< HBFilterOrder >::hbOrder] protected
Definition at line 143 of file inthalfbandfiltereof.h.
Referenced by IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::IntHalfbandFilterEOF().
m_odd
template<uint32_t HBFilterOrder> float IntHalfbandFilterEOF< HBFilterOrder >::m_odd[2][HBFIRFilterTraits< HBFilterOrder >::hbOrder] protected
Definition at line 144 of file inthalfbandfiltereof.h.
Referenced by IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::IntHalfbandFilterEOF().
m_ptr
template<uint32_t HBFilterOrder> int IntHalfbandFilterEOF< HBFilterOrder >::m_ptr protected
Definition at line 147 of file inthalfbandfiltereof.h.
Referenced by IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::doInterpolateFIR(), IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::IntHalfbandFilterEOF(), and IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::myInterpolate().
m_samples
template<uint32_t HBFilterOrder> float IntHalfbandFilterEOF< HBFilterOrder >::m_samples[HBFIRFilterTraits< HBFilterOrder >::hbOrder][2] protected
Definition at line 145 of file inthalfbandfiltereof.h.
Referenced by IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::IntHalfbandFilterEOF(), and IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::myInterpolate().
m_size
template<uint32_t HBFilterOrder> int IntHalfbandFilterEOF< HBFilterOrder >::m_size protected
Definition at line 148 of file inthalfbandfiltereof.h.
Referenced by IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::doFIR(), IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::IntHalfbandFilterEOF(), and IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::storeSample().
m_state
template<uint32_t HBFilterOrder> int IntHalfbandFilterEOF< HBFilterOrder >::m_state protected
Definition at line 149 of file inthalfbandfiltereof.h.
Referenced by IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::IntHalfbandFilterEOF(), and IntHalfbandFilterEOF< DECIMATORS_IF_FILTER_ORDER >::workDecimateCenter().
The documentation for this class was generated from the following file:
sdrbase/dsp/inthalfbandfiltereof.h