SDRAngel: SimpleAGC< AvgSize > Class Template Reference
SimpleAGC< AvgSize > Class Template Reference
#include <agc.h>
Public Member Functions
SimpleAGC (Real initial, Real cutoff=0, Real clip=0)
void resize (Real initial, Real cutoff=0, Real clip=0)
void resizeNew (uint32_t newSize, Real initial, Real cutoff=0, Real clip=0)
void fill (double value)
Real getValue ()
void feed (Real value)
Private Attributes
Real m_cutoff
Real m_clip
MovingAverage< double > m_moving_average
Detailed Description
template<uint32_t AvgSize>
class SimpleAGC< AvgSize >
Definition at line 78 of file agc.h.
Constructor & Destructor Documentation
SimpleAGC()
template<uint32_t AvgSize> SimpleAGC< AvgSize >::SimpleAGC (Real initial, Real cutoff = 0, Real clip = 0) inline
Definition at line 81 of file agc.h.
                                                         :
         m_cutoff(cutoff),
         m_clip(clip),
         m_moving_average(AvgSize, initial)
     {
     }
Member Function Documentation
feed()
template<uint32_t AvgSize> void SimpleAGC< AvgSize >::feed (Real value) inline
Definition at line 116 of file agc.h.
Referenced by AMDemod::processOneSample(), and FreeDVDemod::processOneSample().
     {
         if (value > m_cutoff) {
             m_moving_average.feed(value);
         }
     }
fill()
template<uint32_t AvgSize> void SimpleAGC< AvgSize >::fill (double value) inline
Definition at line 102 of file agc.h.
     {
         m_moving_average.fill(value);
     }
getValue()
template<uint32_t AvgSize> Real SimpleAGC< AvgSize >::getValue () inline
Definition at line 107 of file agc.h.
Referenced by AMDemod::processOneSample(), and FreeDVDemod::processOneSample().
     {
         if ((Real) m_moving_average.average() > m_clip) {
             return (Real) m_moving_average.average();
         } else {
             return m_clip;
         }
     }
resize()
template<uint32_t AvgSize> void SimpleAGC< AvgSize >::resize (Real initial, Real cutoff = 0, Real clip = 0) inline
Definition at line 88 of file agc.h.
     {
         m_cutoff = cutoff;
         m_clip = clip;
         m_moving_average.resize(AvgSize, initial);
     }
resizeNew()
template<uint32_t AvgSize> void SimpleAGC< AvgSize >::resizeNew (uint32_t newSize, Real initial, Real cutoff = 0, Real clip = 0) inline
Definition at line 95 of file agc.h.
Referenced by AMDemod::applyAudioSampleRate(), FreeDVDemod::applyFreeDVMode(), AMDemod::applySettings(), and FreeDVDemod::FreeDVDemod().
     {
         m_cutoff = cutoff;
         m_clip = clip;
         m_moving_average.resize(newSize, initial);
     }
Member Data Documentation
m_clip
template<uint32_t AvgSize> Real SimpleAGC< AvgSize >::m_clip private
Definition at line 125 of file agc.h.
m_cutoff
template<uint32_t AvgSize> Real SimpleAGC< AvgSize >::m_cutoff private
Definition at line 124 of file agc.h.
m_moving_average
template<uint32_t AvgSize> MovingAverage<double> SimpleAGC< AvgSize >::m_moving_average private
Definition at line 126 of file agc.h.
The documentation for this class was generated from the following file:
sdrbase/dsp/agc.h