SDRAngel: WFMDemodGUI Class Reference
WFMDemodGUI Class Reference
#include <wfmdemodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
void channelMarkerHighlightedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static WFMDemodGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
Private Slots
void on_deltaFrequency_changed (qint64 value)
void on_rfBW_changed (quint64 value)
void on_afBW_valueChanged (int value)
void on_volume_valueChanged (int value)
void on_squelch_valueChanged (int value)
void on_audioMute_toggled (bool checked)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void handleInputMessages ()
void audioSelect ()
void tick ()
Private Member Functions
WFMDemodGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *parent=0)
virtual ~WFMDemodGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::WFMDemodGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
WFMDemodSettings m_settings
bool m_basicSettingsShown
bool m_doApplySettings
bool m_audioMute
bool m_squelchOpen
WFMDemod * m_wfmDemod
MessageQueue m_inputMessageQueue
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 20 of file wfmdemodgui.h.
Constructor & Destructor Documentation
WFMDemodGUI()
WFMDemodGUI::WFMDemodGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * parent = 0) explicit private
Definition at line 201 of file wfmdemodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), arg(), audioSelect(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), LevelMeterSignalDB::ColorGreenAndBlue, displaySettings(), ChannelMarker::getColor(), getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, ColorMapper::GrayYellow, handleInputMessages(), WFMDemod::m_channelIdURI, m_channelMarker, m_deviceUISet, WFMDemodSettings::m_rfBandwidth, WFMDemodSettings::m_rfBWDigits, WFMDemodSettings::m_rfBWMax, WFMDemodSettings::m_rfBWMin, WFMDemodSettings::m_rgbColor, m_settings, m_wfmDemod, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), WFMDemodSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSink::setMessageQueueToGUI(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                        :
     RollupWidget(parent),
     ui(new Ui::WFMDemodGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_basicSettingsShown(false)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
     m_wfmDemod = (WFMDemod*) rxChannel; //new WFMDemod(m_deviceUISet->m_deviceSourceAPI);
     m_wfmDemod->setMessageQueueToGUI(getInputMessageQueue());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     CRightClickEnabler *audioMuteRightClickEnabler = new CRightClickEnabler(ui->audioMute);
     connect(audioMuteRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioSelect()));
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     ui->channelPowerMeter->setColorTheme(LevelMeterSignalDB::ColorGreenAndBlue);
     ui->rfBW->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     ui->rfBW->setValueRange(WFMDemodSettings::m_rfBWDigits, WFMDemodSettings::m_rfBWMin, WFMDemodSettings::m_rfBWMax);
     m_channelMarker.blockSignals(true);
     m_channelMarker.setBandwidth(m_settings.m_rfBandwidth);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("WFM Demodulator");
     m_channelMarker.setColor(m_settings.m_rgbColor);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     setTitleColor(m_channelMarker.getColor());
     m_settings.setChannelMarker(&m_channelMarker);
     m_deviceUISet->registerRxChannelInstance(WFMDemod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(&m_channelMarker, SIGNAL(highlightedByCursor()), this, SLOT(channelMarkerHighlightedByCursor()));
     displaySettings();
     applySettings(true);
 }
~WFMDemodGUI()
WFMDemodGUI::~WFMDemodGUI () private virtual
Definition at line 253 of file wfmdemodgui.cpp.
References m_deviceUISet, m_wfmDemod, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_wfmDemod; // TODO: check this: when the GUI closes it has to delete the demodulator
     //delete m_channelMarker;
     delete ui;
 }
Member Function Documentation
applySettings()
void WFMDemodGUI::applySettings (bool force = false) private
Definition at line 266 of file wfmdemodgui.cpp.
References WFMDemod::MsgConfigureWFMDemod::create(), WFMDemod::MsgConfigureChannelizer::create(), ChannelMarker::getCenterFrequency(), BasebandSampleSink::getInputMessageQueue(), m_channelMarker, m_doApplySettings, WFMDemodSettings::m_rfBandwidth, m_settings, m_wfmDemod, MessageQueue::push(), and WFMDemod::requiredBW().
Referenced by audioSelect(), channelMarkerChangedByCursor(), deserialize(), on_afBW_valueChanged(), on_audioMute_toggled(), on_deltaFrequency_changed(), on_rfBW_changed(), on_squelch_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), setCenterFrequency(), and WFMDemodGUI().
 {
     if (m_doApplySettings)
     {
         WFMDemod::MsgConfigureChannelizer *msgChan = WFMDemod::MsgConfigureChannelizer::create(
                 WFMDemod::requiredBW(m_settings.m_rfBandwidth),
                 m_channelMarker.getCenterFrequency());
         m_wfmDemod->getInputMessageQueue()->push(msgChan);
         WFMDemod::MsgConfigureWFMDemod* msgConfig = WFMDemod::MsgConfigureWFMDemod::create( m_settings, force);
         m_wfmDemod->getInputMessageQueue()->push(msgConfig);
     }
 }
audioSelect
void WFMDemodGUI::audioSelect () private slot
Definition at line 317 of file wfmdemodgui.cpp.
References applySettings(), DSPEngine::instance(), WFMDemodSettings::m_audioDeviceName, AudioSelectDialog::m_audioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by WFMDemodGUI().
 {
     qDebug("WFMDemodGUI::audioSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName);
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_audioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
blockApplySettings()
void WFMDemodGUI::blockApplySettings (bool block) private
Definition at line 261 of file wfmdemodgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void WFMDemodGUI::channelMarkerChangedByCursor () slot
Definition at line 110 of file wfmdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, WFMDemodSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by WFMDemodGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
channelMarkerHighlightedByCursor
void WFMDemodGUI::channelMarkerHighlightedByCursor () slot
Definition at line 117 of file wfmdemodgui.cpp.
References ChannelMarker::getHighlighted(), m_channelMarker, and RollupWidget::setHighlighted().
Referenced by WFMDemodGUI().
 {
     setHighlighted(m_channelMarker.getHighlighted());
 }
create()
WFMDemodGUI * WFMDemodGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) static
Definition at line 22 of file wfmdemodgui.cpp.
References WFMDemodGUI().
Referenced by WFMPlugin::createRxChannelGUI().
 {
     WFMDemodGUI* gui = new WFMDemodGUI(pluginAPI, deviceUISet, rxChannel);
     return gui;
 }
deserialize()
bool WFMDemodGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 66 of file wfmdemodgui.cpp.
References applySettings(), WFMDemodSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void WFMDemodGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 28 of file wfmdemodgui.cpp.
 {
     delete this;
 }
displaySettings()
void WFMDemodGUI::displaySettings () private
Definition at line 280 of file wfmdemodgui.cpp.
References arg(), blockApplySettings(), ChannelMarker::getCenterFrequency(), ChannelMarker::getTitle(), WFMDemodSettings::m_afBandwidth, WFMDemodSettings::m_audioMute, m_channelMarker, WFMDemodSettings::m_inputFrequencyOffset, WFMDemodSettings::m_rfBandwidth, WFMDemodSettings::m_rgbColor, m_settings, WFMDemodSettings::m_squelch, WFMDemodSettings::m_title, WFMDemodSettings::m_volume, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by deserialize(), handleMessage(), resetToDefaults(), and WFMDemodGUI().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setBandwidth(m_settings.m_rfBandwidth);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     ui->rfBW->setValue(m_settings.m_rfBandwidth);
     ui->afBW->setValue(m_settings.m_afBandwidth/1000.0);
     ui->afBWText->setText(QString("%1 kHz").arg(m_settings.m_afBandwidth/1000.0));
     ui->volume->setValue(m_settings.m_volume * 10.0);
     ui->volumeText->setText(QString("%1").arg(m_settings.m_volume, 0, 'f', 1));
     ui->squelch->setValue(m_settings.m_squelch);
     ui->squelchText->setText(QString("%1 dB").arg(m_settings.m_squelch));
     ui->audioMute->setChecked(m_settings.m_audioMute);
     blockApplySettings(false);
 }
enterEvent()
void WFMDemodGUI::enterEvent (QEvent *) private
Definition at line 312 of file wfmdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 WFMDemodGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 43 of file wfmdemodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
 {
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* WFMDemodGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 35 of file wfmdemodgui.h.
Referenced by handleInputMessages(), and WFMDemodGUI().
 { return &m_inputMessageQueue; }
getName()
QString WFMDemodGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 38 of file wfmdemodgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void WFMDemodGUI::handleInputMessages () private slot
Definition at line 97 of file wfmdemodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by WFMDemodGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
bool WFMDemodGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 78 of file wfmdemodgui.cpp.
References blockApplySettings(), displaySettings(), WFMDemod::MsgConfigureWFMDemod::getSettings(), m_settings, and Message::match().
Referenced by handleInputMessages().
 {
     (void) message;
     if (WFMDemod::MsgConfigureWFMDemod::match(message))
     {
         qDebug("WFMDemodGUI::handleMessage: WFMDemod::MsgConfigureWFMDemod");
         const WFMDemod::MsgConfigureWFMDemod& cfg = (WFMDemod::MsgConfigureWFMDemod&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
leaveEvent()
void WFMDemodGUI::leaveEvent (QEvent *) private
Definition at line 307 of file wfmdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_afBW_valueChanged
void WFMDemodGUI::on_afBW_valueChanged (int value) private slot
Definition at line 136 of file wfmdemodgui.cpp.
References applySettings(), arg(), WFMDemodSettings::m_afBandwidth, m_settings, and ui.
 {
     ui->afBWText->setText(QString("%1 kHz").arg(value));
     m_settings.m_afBandwidth = value * 1000.0;
     applySettings();
 }
on_audioMute_toggled
void WFMDemodGUI::on_audioMute_toggled (bool checked) private slot
Definition at line 157 of file wfmdemodgui.cpp.
References applySettings(), WFMDemodSettings::m_audioMute, and m_settings.
 {
     m_settings.m_audioMute = checked;
     applySettings();
 }
on_deltaFrequency_changed
void WFMDemodGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 122 of file wfmdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, WFMDemodSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_rfBW_changed
void WFMDemodGUI::on_rfBW_changed (quint64 value) private slot
Definition at line 129 of file wfmdemodgui.cpp.
References applySettings(), m_channelMarker, WFMDemodSettings::m_rfBandwidth, m_settings, and ChannelMarker::setBandwidth().
 {
     m_channelMarker.setBandwidth(value);
     m_settings.m_rfBandwidth = value;
     applySettings();
 }
on_squelch_valueChanged
void WFMDemodGUI::on_squelch_valueChanged (int value) private slot
Definition at line 150 of file wfmdemodgui.cpp.
References applySettings(), arg(), m_settings, WFMDemodSettings::m_squelch, and ui.
 {
     ui->squelchText->setText(QString("%1 dB").arg(value));
     m_settings.m_squelch = value;
     applySettings();
 }
on_volume_valueChanged
void WFMDemodGUI::on_volume_valueChanged (int value) private slot
Definition at line 143 of file wfmdemodgui.cpp.
References applySettings(), arg(), m_settings, WFMDemodSettings::m_volume, and ui.
 {
     ui->volumeText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_volume = value / 10.0;
     applySettings();
 }
onMenuDialogCalled
void WFMDemodGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 169 of file wfmdemodgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, WFMDemodSettings::m_inputFrequencyOffset, WFMDemodSettings::m_reverseAPIAddress, WFMDemodSettings::m_reverseAPIChannelIndex, WFMDemodSettings::m_reverseAPIDeviceIndex, WFMDemodSettings::m_reverseAPIPort, WFMDemodSettings::m_rgbColor, m_settings, WFMDemodSettings::m_title, WFMDemodSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by WFMDemodGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void WFMDemodGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 163 of file wfmdemodgui.cpp.
Referenced by WFMDemodGUI().
 {
     (void) widget;
     (void) rollDown;
 }
resetToDefaults()
void WFMDemodGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 54 of file wfmdemodgui.cpp.
References applySettings(), displaySettings(), m_settings, and WFMDemodSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings();
 }
serialize()
QByteArray WFMDemodGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 61 of file wfmdemodgui.cpp.
References m_settings, and WFMDemodSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void WFMDemodGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 48 of file wfmdemodgui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     applySettings();
 }
setName()
void WFMDemodGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 33 of file wfmdemodgui.cpp.
 {
     setObjectName(name);
 }
tick
void WFMDemodGUI::tick () private slot
Definition at line 330 of file wfmdemodgui.cpp.
References CalcDb::dbPower(), WFMDemod::getMagSqLevels(), WFMDemod::getSquelchOpen(), m_squelchOpen, m_wfmDemod, and ui.
Referenced by WFMDemodGUI().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     m_wfmDemod->getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     double powDbAvg = CalcDb::dbPower(magsqAvg);
     double powDbPeak = CalcDb::dbPower(magsqPeak);
     ui->channelPower->setText(QString::number(powDbAvg, 'f', 1));
     ui->channelPowerMeter->levelChanged(
             (100.0f + powDbAvg) / 100.0f,
             (100.0f + powDbPeak) / 100.0f,
             nbMagsqSamples);
     bool squelchOpen = m_wfmDemod->getSquelchOpen();
     if (squelchOpen != m_squelchOpen)
     {
         if (squelchOpen) {
             ui->audioMute->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->audioMute->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         }
         m_squelchOpen = squelchOpen;
     }
 }
Member Data Documentation
m_audioMute
bool WFMDemodGUI::m_audioMute private
Definition at line 50 of file wfmdemodgui.h.
m_basicSettingsShown
bool WFMDemodGUI::m_basicSettingsShown private
Definition at line 48 of file wfmdemodgui.h.
m_channelMarker
ChannelMarker WFMDemodGUI::m_channelMarker private
Definition at line 46 of file wfmdemodgui.h.
Referenced by applySettings(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), on_rfBW_changed(), onMenuDialogCalled(), setCenterFrequency(), and WFMDemodGUI().
m_deviceUISet
DeviceUISet* WFMDemodGUI::m_deviceUISet private
Definition at line 45 of file wfmdemodgui.h.
Referenced by WFMDemodGUI(), and ~WFMDemodGUI().
m_doApplySettings
bool WFMDemodGUI::m_doApplySettings private
Definition at line 49 of file wfmdemodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_inputMessageQueue
MessageQueue WFMDemodGUI::m_inputMessageQueue private
Definition at line 54 of file wfmdemodgui.h.
m_pluginAPI
PluginAPI* WFMDemodGUI::m_pluginAPI private
Definition at line 44 of file wfmdemodgui.h.
m_settings
WFMDemodSettings WFMDemodGUI::m_settings private
Definition at line 47 of file wfmdemodgui.h.
Referenced by applySettings(), audioSelect(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), handleMessage(), on_afBW_valueChanged(), on_audioMute_toggled(), on_deltaFrequency_changed(), on_rfBW_changed(), on_squelch_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), serialize(), and WFMDemodGUI().
m_squelchOpen
bool WFMDemodGUI::m_squelchOpen private
Definition at line 51 of file wfmdemodgui.h.
Referenced by tick().
m_wfmDemod
WFMDemod* WFMDemodGUI::m_wfmDemod private
Definition at line 53 of file wfmdemodgui.h.
Referenced by applySettings(), tick(), WFMDemodGUI(), and ~WFMDemodGUI().
ui
Ui::WFMDemodGUI* WFMDemodGUI::ui private
Definition at line 43 of file wfmdemodgui.h.
Referenced by channelMarkerChangedByCursor(), displaySettings(), on_afBW_valueChanged(), on_squelch_valueChanged(), on_volume_valueChanged(), tick(), WFMDemodGUI(), and ~WFMDemodGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/demodwfm/wfmdemodgui.h
plugins/channelrx/demodwfm/wfmdemodgui.cpp