SDRAngel: SDRPlayGui Class Reference
SDRPlayGui Class Reference
#include <sdrplaygui.h>
Public Member Functions
SDRPlayGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~SDRPlayGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void updateHardware ()
void updateStatus ()
void handleInputMessages ()
void on_centerFrequency_changed (quint64 value)
void on_ppm_valueChanged (int value)
void on_dcOffset_toggled (bool checked)
void on_iqImbalance_toggled (bool checked)
void on_fBand_currentIndexChanged (int index)
void on_bandwidth_currentIndexChanged (int index)
void on_samplerate_currentIndexChanged (int index)
void on_ifFrequency_currentIndexChanged (int index)
void on_decim_currentIndexChanged (int index)
void on_fcPos_currentIndexChanged (int index)
void on_gainTunerOn_toggled (bool checked)
void on_gainTuner_valueChanged (int value)
void on_gainManualOn_toggled (bool checked)
void on_gainLNA_toggled (bool checked)
void on_gainMixer_toggled (bool checked)
void on_gainBaseband_valueChanged (int value)
void on_startStop_toggled (bool checked)
void on_record_toggled (bool checked)
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void sendSettings ()
void updateSampleRateAndFrequency ()
Private Attributes
Ui::SDRPlayGui * ui
DeviceUISet * m_deviceUISet
bool m_doApplySettings
bool m_forceSettings
SDRPlaySettings m_settings
QTimer m_updateTimer
QTimer m_statusTimer
DeviceSampleSource * m_sampleSource
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 37 of file sdrplaygui.h.
Constructor & Destructor Documentation
SDRPlayGui()
SDRPlayGui::SDRPlayGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 35 of file sdrplaygui.cpp.
References displaySettings(), SDRPlayBands::getBandName(), SDRPlayBandwidths::getBandwidth(), SDRPlayIF::getIF(), SDRPlayBands::getNbBands(), SDRPlayBandwidths::getNbBandwidths(), SDRPlayIF::getNbIFs(), SDRPlaySampleRates::getNbRates(), SDRPlaySampleRates::getRate(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, handleInputMessages(), i, DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_sampleSource, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), DeviceSampleSource::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                                 :
     QWidget(parent),
     ui(new Ui::SDRPlayGui),
     m_deviceUISet(deviceUISet),
     m_doApplySettings(true),
     m_forceSettings(true)
 {
     m_sampleSource = (SDRPlayInput*) m_deviceUISet->m_deviceAPI->getSampleSource();
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, 10U, 12000U);
     ui->fBand->clear();
     for (unsigned int i = 0; i < SDRPlayBands::getNbBands(); i++)
     {
         ui->fBand->addItem(SDRPlayBands::getBandName(i));
     }
     ui->ifFrequency->clear();
     for (unsigned int i = 0; i < SDRPlayIF::getNbIFs(); i++)
     {
         ui->ifFrequency->addItem(QString::number(SDRPlayIF::getIF(i)/1000));
     }
     ui->samplerate->clear();
     for (unsigned int i = 0; i < SDRPlaySampleRates::getNbRates(); i++)
     {
         ui->samplerate->addItem(QString::number(SDRPlaySampleRates::getRate(i)/1000));
     }
     ui->bandwidth->clear();
     for (unsigned int i = 0; i < SDRPlayBandwidths::getNbBandwidths(); i++)
     {
         ui->bandwidth->addItem(QString::number(SDRPlayBandwidths::getBandwidth(i)/1000));
     }
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
 }
~SDRPlayGui()
SDRPlayGui::~SDRPlayGui () virtual
Definition at line 85 of file sdrplaygui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void SDRPlayGui::blockApplySettings (bool block) inline private
Definition at line 71 of file sdrplaygui.h.
Referenced by handleMessage().
 { m_doApplySettings = !block; }
deserialize()
bool SDRPlayGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 129 of file sdrplaygui.cpp.
References SDRPlaySettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
destroy()
void SDRPlayGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 90 of file sdrplaygui.cpp.
 {
     delete this;
 }
displaySettings()
void SDRPlayGui::displaySettings () private
Definition at line 234 of file sdrplaygui.cpp.
References arg(), SDRPlaySettings::m_bandwidthIndex, SDRPlaySettings::m_basebandGain, SDRPlaySettings::m_centerFrequency, SDRPlaySettings::m_dcBlock, SDRPlaySettings::m_devSampleRateIndex, SDRPlaySettings::m_fcPos, SDRPlaySettings::m_frequencyBandIndex, SDRPlaySettings::m_ifFrequencyIndex, SDRPlaySettings::m_iqCorrection, SDRPlaySettings::m_lnaOn, SDRPlaySettings::m_log2Decim, SDRPlaySettings::m_LOppmTenths, SDRPlaySettings::m_mixerAmpOn, m_settings, SDRPlaySettings::m_tunerGain, SDRPlaySettings::m_tunerGainMode, and ui.
Referenced by deserialize(), handleMessage(), resetToDefaults(), SDRPlayGui(), and setCenterFrequency().
 {
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     ui->ppm->setValue(m_settings.m_LOppmTenths);
     ui->ppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     ui->samplerate->setCurrentIndex(m_settings.m_devSampleRateIndex);
     ui->dcOffset->setChecked(m_settings.m_dcBlock);
     ui->iqImbalance->setChecked(m_settings.m_iqCorrection);
     ui->fBand->setCurrentIndex(m_settings.m_frequencyBandIndex);
     ui->bandwidth->setCurrentIndex(m_settings.m_bandwidthIndex);
     ui->ifFrequency->setCurrentIndex(m_settings.m_ifFrequencyIndex);
     ui->samplerate->setCurrentIndex(m_settings.m_devSampleRateIndex);
     ui->decim->setCurrentIndex(m_settings.m_log2Decim);
     ui->fcPos->setCurrentIndex((int) m_settings.m_fcPos);
     ui->gainTunerOn->setChecked(m_settings.m_tunerGainMode);
     if (m_settings.m_tunerGainMode)
     {
         ui->gainTuner->setEnabled(true);
         ui->gainLNA->setEnabled(false);
         ui->gainMixer->setEnabled(false);
         ui->gainBaseband->setEnabled(false);
         int gain = m_settings.m_tunerGain;
         ui->gainTuner->setValue(gain);
         QString gainText;
         gainText.sprintf("%03d", gain);
         ui->gainTunerText->setText(gainText);
         m_settings.m_tunerGain = gain;
     }
     else
     {
         ui->gainTuner->setEnabled(false);
         ui->gainLNA->setEnabled(true);
         ui->gainMixer->setEnabled(true);
         ui->gainBaseband->setEnabled(true);
         ui->gainLNA->setChecked(m_settings.m_lnaOn != 0);
         ui->gainMixer->setChecked(m_settings.m_mixerAmpOn != 0);
         int gain = m_settings.m_basebandGain;
         ui->gainBaseband->setValue(gain);
         QString gainText;
         gainText.sprintf("%02d", gain);
         ui->gainBasebandText->setText(gainText);
     }
 }
getCenterFrequency()
qint64 SDRPlayGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 112 of file sdrplaygui.cpp.
References SDRPlaySettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* SDRPlayGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 53 of file sdrplaygui.h.
 { return &m_inputMessageQueue; }
getName()
QString SDRPlayGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 100 of file sdrplaygui.cpp.
 {
     return objectName();
 }
handleInputMessages
void SDRPlayGui::handleInputMessages () private slot
Definition at line 198 of file sdrplaygui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by SDRPlayGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("SDRPlayGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("SDRPlayGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool SDRPlayGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 145 of file sdrplaygui.cpp.
References blockApplySettings(), displaySettings(), SDRPlayInput::MsgReportSDRPlayGains::getBasebandGain(), SDRPlayInput::MsgReportSDRPlayGains::getLNAGain(), SDRPlayInput::MsgReportSDRPlayGains::getMixerGain(), SDRPlayInput::MsgConfigureSDRPlay::getSettings(), SDRPlayInput::MsgStartStop::getStartStop(), SDRPlayInput::MsgReportSDRPlayGains::getTunerGain(), m_settings, SDRPlaySettings::m_tunerGainMode, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (SDRPlayInput::MsgConfigureSDRPlay::match(message))
     {
         const SDRPlayInput::MsgConfigureSDRPlay& cfg = (SDRPlayInput::MsgConfigureSDRPlay&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (SDRPlayInput::MsgReportSDRPlayGains::match(message))
     {
         qDebug() << "SDRPlayGui::handleMessage: MsgReportSDRPlayGains";
         SDRPlayInput::MsgReportSDRPlayGains msg = (SDRPlayInput::MsgReportSDRPlayGains&) message;
         if (m_settings.m_tunerGainMode)
         {
             ui->gainLNA->setChecked(msg.getLNAGain() != 0);
             ui->gainMixer->setChecked(msg.getMixerGain() != 0);
             ui->gainBaseband->setValue(msg.getBasebandGain());
             QString gainText;
             gainText.sprintf("%02d", msg.getBasebandGain());
             ui->gainBasebandText->setText(gainText);
         }
         else
         {
             ui->gainTuner->setValue(msg.getTunerGain());
             QString gainText;
             gainText.sprintf("%03d", msg.getTunerGain());
             ui->gainTunerText->setText(gainText);
         }
         return true;
     }
     else if (SDRPlayInput::MsgStartStop::match(message))
     {
         SDRPlayInput::MsgStartStop& notif = (SDRPlayInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_bandwidth_currentIndexChanged
void SDRPlayGui::on_bandwidth_currentIndexChanged (int index) private slot
Definition at line 372 of file sdrplaygui.cpp.
References SDRPlaySettings::m_bandwidthIndex, m_settings, and sendSettings().
 {
     m_settings.m_bandwidthIndex = index;
     sendSettings();
 }
on_centerFrequency_changed
void SDRPlayGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 332 of file sdrplaygui.cpp.
References SDRPlaySettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_dcOffset_toggled
void SDRPlayGui::on_dcOffset_toggled (bool checked) private slot
Definition at line 345 of file sdrplaygui.cpp.
References SDRPlaySettings::m_dcBlock, m_settings, and sendSettings().
 {
     qDebug("SDRPlayGui::on_dcOffset_toggled: %s", checked ? "on" : "off");
     m_settings.m_dcBlock = checked;
     sendSettings();
 }
on_decim_currentIndexChanged
void SDRPlayGui::on_decim_currentIndexChanged (int index) private slot
Definition at line 390 of file sdrplaygui.cpp.
References SDRPlaySettings::m_log2Decim, m_settings, and sendSettings().
 {
     m_settings.m_log2Decim = index;
     sendSettings();
 }
on_fBand_currentIndexChanged
void SDRPlayGui::on_fBand_currentIndexChanged (int index) private slot
Definition at line 358 of file sdrplaygui.cpp.
References SDRPlayBands::getBandHigh(), SDRPlayBands::getBandLow(), SDRPlaySettings::m_centerFrequency, SDRPlaySettings::m_frequencyBandIndex, m_settings, sendSettings(), and ui.
 {
     ui->centerFrequency->setValueRange(
             7,
             SDRPlayBands::getBandLow(index),
             SDRPlayBands::getBandHigh(index));
     ui->centerFrequency->setValue((SDRPlayBands::getBandLow(index)+SDRPlayBands::getBandHigh(index)) / 2);
     m_settings.m_centerFrequency = (SDRPlayBands::getBandLow(index)+SDRPlayBands::getBandHigh(index)) * 500;
     m_settings.m_frequencyBandIndex = index;
     sendSettings();
 }
on_fcPos_currentIndexChanged
void SDRPlayGui::on_fcPos_currentIndexChanged (int index) private slot
Definition at line 396 of file sdrplaygui.cpp.
References SDRPlaySettings::m_fcPos, m_settings, and sendSettings().
 {
     m_settings.m_fcPos = (SDRPlaySettings::fcPos_t) index;
     sendSettings();
 }
on_gainBaseband_valueChanged
void SDRPlayGui::on_gainBaseband_valueChanged (int value) private slot
Definition at line 449 of file sdrplaygui.cpp.
References SDRPlaySettings::m_basebandGain, m_settings, sendSettings(), and ui.
 {
     m_settings.m_basebandGain = value;
     QString gainText;
     gainText.sprintf("%02d", value);
     ui->gainBasebandText->setText(gainText);
     sendSettings();
 }
on_gainLNA_toggled
void SDRPlayGui::on_gainLNA_toggled (bool checked) private slot
Definition at line 437 of file sdrplaygui.cpp.
References SDRPlaySettings::m_lnaOn, m_settings, and sendSettings().
 {
     m_settings.m_lnaOn = checked ? 1 : 0;
     sendSettings();
 }
on_gainManualOn_toggled
void SDRPlayGui::on_gainManualOn_toggled (bool checked) private slot
Definition at line 425 of file sdrplaygui.cpp.
References m_settings, SDRPlaySettings::m_tunerGainMode, sendSettings(), and ui.
 {
     qDebug("SDRPlayGui::on_gainManualOn_toggled: %s", checked ? "on" : "off");
     m_settings.m_tunerGainMode = false;
     ui->gainTuner->setEnabled(false);
     ui->gainLNA->setEnabled(true);
     ui->gainMixer->setEnabled(true);
     ui->gainBaseband->setEnabled(true);
     sendSettings();
 }
on_gainMixer_toggled
void SDRPlayGui::on_gainMixer_toggled (bool checked) private slot
Definition at line 443 of file sdrplaygui.cpp.
References SDRPlaySettings::m_mixerAmpOn, m_settings, and sendSettings().
 {
     m_settings.m_mixerAmpOn = checked ? 1 : 0;
     sendSettings();
 }
on_gainTuner_valueChanged
void SDRPlayGui::on_gainTuner_valueChanged (int value) private slot
Definition at line 414 of file sdrplaygui.cpp.
References m_settings, SDRPlaySettings::m_tunerGain, sendSettings(), and ui.
 {
     int gain = value;
     QString gainText;
     gainText.sprintf("%03d", gain);
     ui->gainTunerText->setText(gainText);
     m_settings.m_tunerGain = gain;
     sendSettings();
 }
on_gainTunerOn_toggled
void SDRPlayGui::on_gainTunerOn_toggled (bool checked) private slot
Definition at line 402 of file sdrplaygui.cpp.
References m_settings, SDRPlaySettings::m_tunerGainMode, sendSettings(), and ui.
 {
     qDebug("SDRPlayGui::on_gainTunerOn_toggled: %s", checked ? "on" : "off");
     m_settings.m_tunerGainMode = true;
     ui->gainTuner->setEnabled(true);
     ui->gainLNA->setEnabled(false);
     ui->gainMixer->setEnabled(false);
     ui->gainBaseband->setEnabled(false);
     sendSettings();
 }
on_ifFrequency_currentIndexChanged
void SDRPlayGui::on_ifFrequency_currentIndexChanged (int index) private slot
Definition at line 384 of file sdrplaygui.cpp.
References SDRPlaySettings::m_ifFrequencyIndex, m_settings, and sendSettings().
 {
     m_settings.m_ifFrequencyIndex = index;
     sendSettings();
 }
on_iqImbalance_toggled
void SDRPlayGui::on_iqImbalance_toggled (bool checked) private slot
Definition at line 352 of file sdrplaygui.cpp.
References SDRPlaySettings::m_iqCorrection, m_settings, and sendSettings().
 {
     m_settings.m_iqCorrection = checked;
     sendSettings();
 }
on_ppm_valueChanged
void SDRPlayGui::on_ppm_valueChanged (int value) private slot
Definition at line 338 of file sdrplaygui.cpp.
References arg(), SDRPlaySettings::m_LOppmTenths, m_settings, sendSettings(), and ui.
 {
     m_settings.m_LOppmTenths = value;
     ui->ppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     sendSettings();
 }
on_record_toggled
void SDRPlayGui::on_record_toggled (bool checked) private slot
Definition at line 469 of file sdrplaygui.cpp.
References SDRPlayInput::MsgFileRecord::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, MessageQueue::push(), and ui.
 {
     if (checked) {
         ui->record->setStyleSheet("QToolButton { background-color : red; }");
     } else {
         ui->record->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     SDRPlayInput::MsgFileRecord* message = SDRPlayInput::MsgFileRecord::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
on_samplerate_currentIndexChanged
void SDRPlayGui::on_samplerate_currentIndexChanged (int index) private slot
Definition at line 378 of file sdrplaygui.cpp.
References SDRPlaySettings::m_devSampleRateIndex, m_settings, and sendSettings().
 {
     m_settings.m_devSampleRateIndex = index;
     sendSettings();
 }
on_startStop_toggled
void SDRPlayGui::on_startStop_toggled (bool checked) private slot
Definition at line 460 of file sdrplaygui.cpp.
References SDRPlayInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         SDRPlayInput::MsgStartStop *message = SDRPlayInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
openDeviceSettingsDialog
void SDRPlayGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 481 of file sdrplaygui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), SDRPlaySettings::m_reverseAPIAddress, SDRPlaySettings::m_reverseAPIDeviceIndex, SDRPlaySettings::m_reverseAPIPort, m_settings, SDRPlaySettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by SDRPlayGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void SDRPlayGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 105 of file sdrplaygui.cpp.
References displaySettings(), m_settings, SDRPlaySettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void SDRPlayGui::sendSettings () private
Definition at line 288 of file sdrplaygui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_bandwidth_currentIndexChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fBand_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_gainBaseband_valueChanged(), on_gainLNA_toggled(), on_gainManualOn_toggled(), on_gainMixer_toggled(), on_gainTuner_valueChanged(), on_gainTunerOn_toggled(), on_ifFrequency_currentIndexChanged(), on_iqImbalance_toggled(), on_ppm_valueChanged(), on_samplerate_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray SDRPlayGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 124 of file sdrplaygui.cpp.
References m_settings, and SDRPlaySettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void SDRPlayGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 117 of file sdrplaygui.cpp.
References displaySettings(), SDRPlaySettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void SDRPlayGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 95 of file sdrplaygui.cpp.
 {
     setObjectName(name);
 }
updateHardware
void SDRPlayGui::updateHardware () private slot
Definition at line 294 of file sdrplaygui.cpp.
References SDRPlayInput::MsgConfigureSDRPlay::create(), DeviceSampleSource::getInputMessageQueue(), m_forceSettings, m_sampleSource, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by SDRPlayGui().
 {
     qDebug() << "SDRPlayGui::updateHardware";
     SDRPlayInput::MsgConfigureSDRPlay* message = SDRPlayInput::MsgConfigureSDRPlay::create( m_settings, m_forceSettings);
     m_sampleSource->getInputMessageQueue()->push(message);
     m_forceSettings = false;
     m_updateTimer.stop();
 }
updateSampleRateAndFrequency()
void SDRPlayGui::updateSampleRateAndFrequency () private
Definition at line 226 of file sdrplaygui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg((float)m_sampleRate / 1000));
 }
updateStatus
void SDRPlayGui::updateStatus () private slot
Definition at line 303 of file sdrplaygui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by SDRPlayGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 SDRPlayGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 67 of file sdrplaygui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* SDRPlayGui::m_deviceUISet private
Definition at line 59 of file sdrplaygui.h.
Referenced by SDRPlayGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool SDRPlayGui::m_doApplySettings private
Definition at line 60 of file sdrplaygui.h.
Referenced by on_startStop_toggled().
m_forceSettings
bool SDRPlayGui::m_forceSettings private
Definition at line 61 of file sdrplaygui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue SDRPlayGui::m_inputMessageQueue private
Definition at line 69 of file sdrplaygui.h.
Referenced by handleInputMessages(), and SDRPlayGui().
m_lastEngineState
int SDRPlayGui::m_lastEngineState private
Definition at line 68 of file sdrplaygui.h.
Referenced by updateStatus().
m_sampleRate
int SDRPlayGui::m_sampleRate private
Definition at line 66 of file sdrplaygui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleSource
DeviceSampleSource* SDRPlayGui::m_sampleSource private
Definition at line 65 of file sdrplaygui.h.
Referenced by on_record_toggled(), on_startStop_toggled(), SDRPlayGui(), and updateHardware().
m_settings
SDRPlaySettings SDRPlayGui::m_settings private
Definition at line 62 of file sdrplaygui.h.
Referenced by deserialize(), displaySettings(), getCenterFrequency(), handleMessage(), on_bandwidth_currentIndexChanged(), on_centerFrequency_changed(), on_dcOffset_toggled(), on_decim_currentIndexChanged(), on_fBand_currentIndexChanged(), on_fcPos_currentIndexChanged(), on_gainBaseband_valueChanged(), on_gainLNA_toggled(), on_gainManualOn_toggled(), on_gainMixer_toggled(), on_gainTuner_valueChanged(), on_gainTunerOn_toggled(), on_ifFrequency_currentIndexChanged(), on_iqImbalance_toggled(), on_ppm_valueChanged(), on_samplerate_currentIndexChanged(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), and updateHardware().
m_statusTimer
QTimer SDRPlayGui::m_statusTimer private
Definition at line 64 of file sdrplaygui.h.
Referenced by SDRPlayGui().
m_updateTimer
QTimer SDRPlayGui::m_updateTimer private
Definition at line 63 of file sdrplaygui.h.
Referenced by SDRPlayGui(), sendSettings(), and updateHardware().
ui
Ui::SDRPlayGui* SDRPlayGui::ui private
Definition at line 57 of file sdrplaygui.h.
Referenced by displaySettings(), handleMessage(), on_fBand_currentIndexChanged(), on_gainBaseband_valueChanged(), on_gainManualOn_toggled(), on_gainTuner_valueChanged(), on_gainTunerOn_toggled(), on_ppm_valueChanged(), on_record_toggled(), SDRPlayGui(), updateSampleRateAndFrequency(), updateStatus(), and ~SDRPlayGui().
The documentation for this class was generated from the following files:
plugins/samplesource/sdrplay/sdrplaygui.h
plugins/samplesource/sdrplay/sdrplaygui.cpp