SDRAngel: DSPDeviceMIMOEngine::ConfigureCorrection Class Reference
DSPDeviceMIMOEngine::ConfigureCorrection Class Reference
#include <dspdevicemimoengine.h>
Public Member Functions
ConfigureCorrection (bool dcOffsetCorrection, bool iqImbalanceCorrection, unsigned int index)
bool getDCOffsetCorrection () const
bool getIQImbalanceCorrection () const
unsigned int getIndex () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Private Attributes
bool m_dcOffsetCorrection
bool m_iqImbalanceCorrection
unsigned int m_index
Additional Inherited Members
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 202 of file dspdevicemimoengine.h.
Constructor & Destructor Documentation
ConfigureCorrection()
DSPDeviceMIMOEngine::ConfigureCorrection::ConfigureCorrection (bool dcOffsetCorrection, bool iqImbalanceCorrection, unsigned int index) inline
Definition at line 205 of file dspdevicemimoengine.h.
                                                                                                      :
             Message(),
             m_dcOffsetCorrection(dcOffsetCorrection),
             m_iqImbalanceCorrection(iqImbalanceCorrection),
             m_index(index)
         { }
Member Function Documentation
getDCOffsetCorrection()
bool DSPDeviceMIMOEngine::ConfigureCorrection::getDCOffsetCorrection () const inline
Definition at line 211 of file dspdevicemimoengine.h.
Referenced by DSPDeviceMIMOEngine::handleInputMessages().
 { return m_dcOffsetCorrection; }
getIndex()
unsigned int DSPDeviceMIMOEngine::ConfigureCorrection::getIndex () const inline
Definition at line 213 of file dspdevicemimoengine.h.
Referenced by DSPDeviceMIMOEngine::handleInputMessages().
 { return m_index; }
getIQImbalanceCorrection()
bool DSPDeviceMIMOEngine::ConfigureCorrection::getIQImbalanceCorrection () const inline
Definition at line 212 of file dspdevicemimoengine.h.
Referenced by DSPDeviceMIMOEngine::handleInputMessages().
 { return m_iqImbalanceCorrection; }
Member Data Documentation
m_dcOffsetCorrection
bool DSPDeviceMIMOEngine::ConfigureCorrection::m_dcOffsetCorrection private
Definition at line 215 of file dspdevicemimoengine.h.
m_index
unsigned int DSPDeviceMIMOEngine::ConfigureCorrection::m_index private
Definition at line 217 of file dspdevicemimoengine.h.
m_iqImbalanceCorrection
bool DSPDeviceMIMOEngine::ConfigureCorrection::m_iqImbalanceCorrection private
Definition at line 216 of file dspdevicemimoengine.h.
The documentation for this class was generated from the following file:
sdrbase/dsp/dspdevicemimoengine.h