SDRAngel: ChannelAnalyzer Class Reference
ChannelAnalyzer Class Reference
#include <chanalyzer.h>
Classes
class MsgConfigureChannelAnalyzer
class MsgConfigureChannelizer
class MsgReportChannelSampleRateChanged
Public Member Functions
ChannelAnalyzer (DeviceAPI *deviceAPI)
virtual ~ChannelAnalyzer ()
virtual void destroy ()
void setSampleSink (BasebandSampleSink *sampleSink)
DownChannelizer * getChannelizer ()
int getInputSampleRate () const
int getChannelSampleRate () const
int getDecimation () const
double getMagSq () const
double getMagSqAvg () const
bool isPllLocked () const
Real getPllFrequency () const
Real getPllDeltaPhase () const
Real getPllPhase () const
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool positiveOnly)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.chanalyzer"
static const QString m_channelId = "ChannelAnalyzer"
Private Member Functions
void applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force=false)
void applySettings (const ChannelAnalyzerSettings &settings, bool force=false)
void setFilters (int sampleRate, float bandwidth, float lowCutoff)
void processOneSample (Complex &c, fftfilt::cmplx *sideband)
void feedOneSample (const fftfilt::cmplx &s, const fftfilt::cmplx &pll)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
ChannelAnalyzerSettings m_settings
int m_inputSampleRate
int m_inputFrequencyOffset
int m_undersampleCount
fftfilt::cmplx m_sum
bool m_usb
double m_magsq
bool m_useInterpolator
NCOF m_nco
PhaseLockComplex m_pll
FreqLockComplex m_fll
Interpolator m_interpolator
Real m_interpolatorDistance
Real m_interpolatorDistanceRemain
fftfilt * SSBFilter
fftfilt * DSBFilter
fftfilt * RRCFilter
fftcorr * m_corr
BasebandSampleSink * m_sampleSink
SampleVector m_sampleBuffer
MovingAverageUtil< double, double, 480 > m_channelPowerAvg
QMutex m_settingsMutex
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 44 of file chanalyzer.h.
Constructor & Destructor Documentation
ChannelAnalyzer()
ChannelAnalyzer::ChannelAnalyzer (DeviceAPI * deviceAPI)
Definition at line 35 of file chanalyzer.cpp.
References DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), applyChannelSettings(), applySettings(), PhaseLockComplex::computeCoefficients(), DSBFilter, ChannelAnalyzerSettings::m_bandwidth, m_channelId, m_channelizer, m_corr, m_deviceAPI, m_inputFrequencyOffset, m_inputSampleRate, m_interpolatorDistance, m_interpolatorDistanceRemain, ChannelAnalyzerSettings::m_lowCutoff, m_magsq, m_pll, m_settings, m_sum, m_threadedChannelizer, m_undersampleCount, m_usb, m_useInterpolator, RRCFilter, ssbFftLen, and SSBFilter.
Referenced by ChannelAnalyzer::MsgReportChannelSampleRateChanged::MsgReportChannelSampleRateChanged().
                                                      :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(deviceAPI),
         m_sampleSink(0),
         m_settingsMutex(QMutex::Recursive)
 {
     setObjectName(m_channelId);
     m_undersampleCount = 0;
     m_sum = 0;
     m_usb = true;
     m_magsq = 0;
     m_useInterpolator = false;
     m_interpolatorDistance = 1.0f;
     m_interpolatorDistanceRemain = 0.0f;
     m_inputSampleRate = 48000;
     m_inputFrequencyOffset = 0;
     SSBFilter = new fftfilt(m_settings.m_lowCutoff / m_inputSampleRate, m_settings.m_bandwidth / m_inputSampleRate, ssbFftLen);
     DSBFilter = new fftfilt(m_settings.m_bandwidth / m_inputSampleRate, 2*ssbFftLen);
     RRCFilter = new fftfilt(m_settings.m_bandwidth / m_inputSampleRate, 2*ssbFftLen);
     m_corr = new fftcorr(8*ssbFftLen); // 8k for 4k effective samples
     m_pll.computeCoefficients(0.002f, 0.5f, 10.0f); // bandwidth, damping factor, loop gain
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
     applySettings(m_settings, true);
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer, this);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
 }
~ChannelAnalyzer()
ChannelAnalyzer::~ChannelAnalyzer () virtual
Definition at line 67 of file chanalyzer.cpp.
References DSBFilter, m_channelizer, m_deviceAPI, m_threadedChannelizer, DeviceAPI::removeChannelSink(), DeviceAPI::removeChannelSinkAPI(), RRCFilter, and SSBFilter.
Referenced by ChannelAnalyzer::MsgReportChannelSampleRateChanged::MsgReportChannelSampleRateChanged().
 {
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
     delete SSBFilter;
     delete DSBFilter;
     delete RRCFilter;
 }
Member Function Documentation
applyChannelSettings()
void ChannelAnalyzer::applyChannelSettings (int inputSampleRate, int inputFrequencyOffset, bool force = false) private
Definition at line 236 of file chanalyzer.cpp.
References Interpolator::create(), ChannelAnalyzerSettings::m_bandwidth, ChannelAnalyzerSettings::m_downSample, ChannelAnalyzerSettings::m_downSampleRate, m_fll, m_inputFrequencyOffset, m_inputSampleRate, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, ChannelAnalyzerSettings::m_lowCutoff, m_nco, m_pll, m_settings, m_settingsMutex, ChannelAnalyzerSettings::m_spanLog2, setFilters(), NCOF::setFreq(), FreqLockComplex::setSampleRate(), and PhaseLockComplex::setSampleRate().
Referenced by ChannelAnalyzer(), handleMessage(), and start().
 {
     qDebug() << "ChannelAnalyzer::applyChannelSettings:"
             << " inputSampleRate: " << inputSampleRate
             << " inputFrequencyOffset: " << inputFrequencyOffset;
     if ((m_inputFrequencyOffset != inputFrequencyOffset) ||
         (m_inputSampleRate != inputSampleRate) || force)
     {
         m_nco.setFreq(-inputFrequencyOffset, inputSampleRate);
     }
     if ((m_inputSampleRate != inputSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_interpolator.create(16, inputSampleRate, inputSampleRate / 2.2f);
         m_interpolatorDistanceRemain = 0;
         m_interpolatorDistance = (Real) inputSampleRate / (Real) m_settings.m_downSampleRate;
         if (!m_settings.m_downSample)
         {
             setFilters(inputSampleRate, m_settings.m_bandwidth, m_settings.m_lowCutoff);
             m_pll.setSampleRate(inputSampleRate / (1<<m_settings.m_spanLog2));
             m_fll.setSampleRate(inputSampleRate / (1<<m_settings.m_spanLog2));
         }
         m_settingsMutex.unlock();
     }
     m_inputSampleRate = inputSampleRate;
     m_inputFrequencyOffset = inputFrequencyOffset;
 }
applySettings()
void ChannelAnalyzer::applySettings (const ChannelAnalyzerSettings & settings, bool force = false) private
Definition at line 297 of file chanalyzer.cpp.
References Interpolator::create(), fftfilt::create_rrc_filter(), ChannelAnalyzerSettings::m_bandwidth, ChannelAnalyzerSettings::m_downSample, ChannelAnalyzerSettings::m_downSampleRate, ChannelAnalyzerSettings::m_fll, m_fll, m_inputSampleRate, ChannelAnalyzerSettings::m_inputType, m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, ChannelAnalyzerSettings::m_lowCutoff, ChannelAnalyzerSettings::m_pll, m_pll, ChannelAnalyzerSettings::m_pllPskOrder, ChannelAnalyzerSettings::m_rrc, ChannelAnalyzerSettings::m_rrcRolloff, m_settings, m_settingsMutex, ChannelAnalyzerSettings::m_spanLog2, ChannelAnalyzerSettings::m_ssb, m_useInterpolator, FreqLockComplex::reset(), PhaseLockComplex::reset(), RRCFilter, setFilters(), PhaseLockComplex::setPskOrder(), FreqLockComplex::setSampleRate(), and PhaseLockComplex::setSampleRate().
Referenced by ChannelAnalyzer(), and handleMessage().
 {
     qDebug() << "ChannelAnalyzer::applySettings:"
             << " m_downSample: " << settings.m_downSample
             << " m_downSampleRate: " << settings.m_downSampleRate
             << " m_rcc: " << settings.m_rrc
             << " m_rrcRolloff: " << settings.m_rrcRolloff / 100.0
             << " m_bandwidth: " << settings.m_bandwidth
             << " m_lowCutoff: " << settings.m_lowCutoff
             << " m_spanLog2: " << settings.m_spanLog2
             << " m_ssb: " << settings.m_ssb
             << " m_pll: " << settings.m_pll
             << " m_fll: " << settings.m_fll
             << " m_pllPskOrder: " << settings.m_pllPskOrder
             << " m_inputType: " << (int) settings.m_inputType;
     if ((settings.m_downSampleRate != m_settings.m_downSampleRate) || force)
     {
         m_settingsMutex.lock();
         m_interpolator.create(16, m_inputSampleRate, m_inputSampleRate / 2.2);
         m_interpolatorDistanceRemain = 0.0f;
         m_interpolatorDistance =  (Real) m_inputSampleRate / (Real) settings.m_downSampleRate;
         m_settingsMutex.unlock();
     }
     if ((settings.m_downSample != m_settings.m_downSample) || force)
     {
         int sampleRate = settings.m_downSample ? settings.m_downSampleRate : m_inputSampleRate;
         m_settingsMutex.lock();
         m_useInterpolator = settings.m_downSample;
         setFilters(sampleRate, settings.m_bandwidth, settings.m_lowCutoff);
         m_pll.setSampleRate(sampleRate / (1<<settings.m_spanLog2));
         m_fll.setSampleRate(sampleRate / (1<<settings.m_spanLog2));
         m_settingsMutex.unlock();
     }
     if ((settings.m_bandwidth != m_settings.m_bandwidth) ||
         (settings.m_lowCutoff != m_settings.m_lowCutoff)|| force)
     {
         m_settingsMutex.lock();
         setFilters(settings.m_downSample ? settings.m_downSampleRate : m_inputSampleRate, settings.m_bandwidth, settings.m_lowCutoff);
         m_settingsMutex.unlock();
     }
     if ((settings.m_rrcRolloff != m_settings.m_rrcRolloff) || force)
     {
         float sampleRate = settings.m_downSample ? (float) settings.m_downSampleRate : (float) m_inputSampleRate;
         m_settingsMutex.lock();
         RRCFilter->create_rrc_filter(settings.m_bandwidth / sampleRate, settings.m_rrcRolloff / 100.0);
         m_settingsMutex.unlock();
     }
     if ((settings.m_spanLog2 != m_settings.m_spanLog2) || force)
     {
         int sampleRate = (settings.m_downSample ? settings.m_downSampleRate : m_inputSampleRate) / (1<<m_settings.m_spanLog2);
         m_pll.setSampleRate(sampleRate);
         m_fll.setSampleRate(sampleRate);
     }
     if (settings.m_pll != m_settings.m_pll || force)
     {
         if (settings.m_pll)
         {
             m_pll.reset();
             m_fll.reset();
         }
     }
     if (settings.m_fll != m_settings.m_fll || force)
     {
         if (settings.m_fll) {
             m_fll.reset();
         }
     }
     if (settings.m_pllPskOrder != m_settings.m_pllPskOrder || force)
     {
         if (settings.m_pllPskOrder < 32) {
             m_pll.setPskOrder(settings.m_pllPskOrder);
         }
     }
     m_settings = settings;
 }
deserialize()
virtual bool ChannelAnalyzer::deserialize (const QByteArray & data) inline virtual
Implements ChannelAPI.
Definition at line 145 of file chanalyzer.h.
 { (void) data; return false; }
destroy()
virtual void ChannelAnalyzer::destroy () inline virtual
Implements ChannelAPI.
Definition at line 111 of file chanalyzer.h.
 { delete this; }
feed()
void ChannelAnalyzer::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool positiveOnly) virtual
Implements BasebandSampleSink.
Definition at line 78 of file chanalyzer.cpp.
References Interpolator::decimate(), BasebandSampleSink::feed(), m_interpolator, m_interpolatorDistance, m_interpolatorDistanceRemain, m_nco, m_sampleBuffer, m_sampleSink, m_settings, m_settingsMutex, ChannelAnalyzerSettings::m_ssb, m_useInterpolator, NCOF::nextIQ(), and processOneSample().
Referenced by getPllPhase().
 {
     (void) positiveOnly;
     fftfilt::cmplx *sideband = 0;
     Complex ci;
     m_settingsMutex.lock();
     for(SampleVector::const_iterator it = begin; it < end; ++it)
     {
         Complex c(it->real(), it->imag());
         c *= m_nco.nextIQ();
         if (m_useInterpolator)
         {
             if (m_interpolator.decimate(&m_interpolatorDistanceRemain, c, &ci))
             {
                 processOneSample(ci, sideband);
                 m_interpolatorDistanceRemain += m_interpolatorDistance;
             }
         }
         else
         {
             processOneSample(c, sideband);
         }
     }
     if(m_sampleSink != 0)
     {
         m_sampleSink->feed(m_sampleBuffer.begin(), m_sampleBuffer.end(), m_settings.m_ssb); // m_ssb = positive only
     }
     m_sampleBuffer.clear();
     m_settingsMutex.unlock();
 }
feedOneSample()
void ChannelAnalyzer::feedOneSample (const fftfilt::cmplx & s, const fftfilt::cmplx & pll) inline private
Definition at line 197 of file chanalyzer.h.
References ChannelAnalyzerSettings::InputAutoCorr, ChannelAnalyzerSettings::InputPLL, ChannelAnalyzerSettings::InputSignal, ChannelAnalyzerSettings::m_inputType, ChannelAnalyzerSettings::m_ssb, fftcorr::run(), and SDR_RX_SCALEF.
Referenced by processOneSample().
     {
         switch (m_settings.m_inputType)
         {
             case ChannelAnalyzerSettings::InputPLL:
             {
                 if (m_settings.m_ssb & !m_usb) { // invert spectrum for LSB
                     m_sampleBuffer.push_back(Sample(pll.imag()*SDR_RX_SCALEF, pll.real()*SDR_RX_SCALEF));
                 } else {
                     m_sampleBuffer.push_back(Sample(pll.real()*SDR_RX_SCALEF, pll.imag()*SDR_RX_SCALEF));
                 }
             }
                 break;
             case ChannelAnalyzerSettings::InputAutoCorr:
             {
                 std::complex<float> a = m_corr->run(s/(SDR_RX_SCALEF/768.0f), 0);
                 if (m_settings.m_ssb & !m_usb) { // invert spectrum for LSB
                     m_sampleBuffer.push_back(Sample(a.imag(), a.real()));
                 } else {
                     m_sampleBuffer.push_back(Sample(a.real(), a.imag()));
                 }
             }
                 break;
             case ChannelAnalyzerSettings::InputSignal:
             default:
             {
                 if (m_settings.m_ssb & !m_usb) { // invert spectrum for LSB
                     m_sampleBuffer.push_back(Sample(s.imag(), s.real()));
                 } else {
                     m_sampleBuffer.push_back(Sample(s.real(), s.imag()));
                 }
             }
                 break;
         }
     }
getCenterFrequency()
virtual qint64 ChannelAnalyzer::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 142 of file chanalyzer.h.
References ChannelAnalyzerSettings::m_frequency, and ChannelAnalyzer::MsgConfigureChannelAnalyzer::m_settings.
 { return m_settings.m_frequency; }
getChannelizer()
DownChannelizer* ChannelAnalyzer::getChannelizer () inline
Definition at line 124 of file chanalyzer.h.
References m_channelizer.
Referenced by ChannelAnalyzerGUI::getRequestedChannelSampleRate().
 { return m_channelizer; }
getChannelSampleRate()
int ChannelAnalyzer::getChannelSampleRate () const inline
Definition at line 126 of file chanalyzer.h.
References ChannelAnalyzerSettings::m_downSample, ChannelAnalyzerSettings::m_downSampleRate, m_inputSampleRate, and ChannelAnalyzer::MsgConfigureChannelAnalyzer::m_settings.
Referenced by ChannelAnalyzerGUI::tick().
 { return m_settings.m_downSample ? m_settings.m_downSampleRate : m_inputSampleRate; }
getDecimation()
int ChannelAnalyzer::getDecimation () const inline
Definition at line 127 of file chanalyzer.h.
References ChannelAnalyzer::MsgConfigureChannelAnalyzer::m_settings, and ChannelAnalyzerSettings::m_spanLog2.
Referenced by ChannelAnalyzerGUI::tick().
 { return 1<<m_settings.m_spanLog2; }
getIdentifier()
virtual void ChannelAnalyzer::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 140 of file chanalyzer.h.
 { id = objectName(); }
getInputSampleRate()
int ChannelAnalyzer::getInputSampleRate () const inline
Definition at line 125 of file chanalyzer.h.
References m_inputSampleRate.
Referenced by ChannelAnalyzerGUI::displaySettings(), and ChannelAnalyzerGUI::handleMessage().
 { return m_inputSampleRate; }
getMagSq()
double ChannelAnalyzer::getMagSq () const inline
Definition at line 128 of file chanalyzer.h.
References m_magsq.
 { return m_magsq; }
getMagSqAvg()
double ChannelAnalyzer::getMagSqAvg () const inline
Definition at line 129 of file chanalyzer.h.
References m_channelPowerAvg.
Referenced by ChannelAnalyzerGUI::tick().
 { return (double) m_channelPowerAvg; }
getNbSinkStreams()
virtual int ChannelAnalyzer::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 147 of file chanalyzer.h.
 { return 1; }
getNbSourceStreams()
virtual int ChannelAnalyzer::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 148 of file chanalyzer.h.
 { return 0; }
getPllDeltaPhase()
Real ChannelAnalyzer::getPllDeltaPhase () const inline
Definition at line 132 of file chanalyzer.h.
References PhaseLockComplex::getDeltaPhi(), and m_pll.
 { return m_pll.getDeltaPhi(); }
getPllFrequency()
Real ChannelAnalyzer::getPllFrequency () const
Definition at line 383 of file chanalyzer.cpp.
References FreqLockComplex::getFreq(), PhaseLockComplex::getFreq(), ChannelAnalyzerSettings::m_fll, m_fll, ChannelAnalyzerSettings::m_pll, m_pll, and m_settings.
Referenced by isPllLocked(), and ChannelAnalyzerGUI::tick().
 {
     if (m_settings.m_fll) {
         return m_fll.getFreq();
     } else if (m_settings.m_pll) {
         return m_pll.getFreq();
     } else {
         return 0.0;
     }
 }
getPllPhase()
Real ChannelAnalyzer::getPllPhase () const inline
Definition at line 133 of file chanalyzer.h.
References feed(), PhaseLockComplex::getPhiHat(), handleMessage(), m_pll, start(), and stop().
 { return m_pll.getPhiHat(); }
getStreamCenterFrequency()
virtual qint64 ChannelAnalyzer::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 150 of file chanalyzer.h.
References ChannelAnalyzerSettings::m_frequency, and ChannelAnalyzer::MsgConfigureChannelAnalyzer::m_settings.
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return m_settings.m_frequency;
     }
getTitle()
virtual void ChannelAnalyzer::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 141 of file chanalyzer.h.
 { title = objectName(); }
handleMessage()
bool ChannelAnalyzer::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 180 of file chanalyzer.cpp.
References applyChannelSettings(), applySettings(), DownChannelizer::configure(), ChannelAnalyzer::MsgReportChannelSampleRateChanged::create(), ChannelAnalyzer::MsgConfigureChannelizer::getCenterFrequency(), ChannelAnalyzer::MsgConfigureChannelAnalyzer::getForce(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSink::getInputMessageQueue(), BasebandSampleSink::getMessageQueueToGUI(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), ChannelAnalyzer::MsgConfigureChannelizer::getSampleRate(), ChannelAnalyzer::MsgConfigureChannelAnalyzer::getSettings(), m_channelizer, Message::match(), and MessageQueue::push().
Referenced by getPllPhase().
 {
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& notif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         qDebug() << "ChannelAnalyzer::handleMessage: DownChannelizer::MsgChannelizerNotification:"
                 << " sampleRate: " << notif.getSampleRate()
                 << " frequencyOffset: " << notif.getFrequencyOffset();
         applyChannelSettings(notif.getSampleRate(), notif.getFrequencyOffset());
         if (getMessageQueueToGUI())
         {
             MsgReportChannelSampleRateChanged *msg = MsgReportChannelSampleRateChanged::create();
             getMessageQueueToGUI()->push(msg);
         }
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         qDebug() << "ChannelAnalyzer::handleMessage: MsgConfigureChannelizer:"
                 << " sampleRate: " << cfg.getSampleRate()
                 << " centerFrequency: " << cfg.getCenterFrequency();
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
                 cfg.getSampleRate(),
                 cfg.getCenterFrequency());
         return true;
     }
     else if (MsgConfigureChannelAnalyzer::match(cmd))
     {
         qDebug("ChannelAnalyzer::handleMessage: MsgConfigureChannelAnalyzer");
         MsgConfigureChannelAnalyzer& cfg = (MsgConfigureChannelAnalyzer&) cmd;
         applySettings(cfg.getSettings(), cfg.getForce());
         return true;
     }
     else
     {
         // Processed through GUI
 //      if (m_sampleSink != 0)
 //      {
 //         return m_sampleSink->handleMessage(cmd);
 //      }
 //      else
 //      {
 //          return false;
 //      }
         return false;
     }
 }
isPllLocked()
bool ChannelAnalyzer::isPllLocked () const inline
Definition at line 130 of file chanalyzer.h.
References getPllFrequency(), PhaseLockComplex::locked(), ChannelAnalyzerSettings::m_pll, m_pll, and ChannelAnalyzer::MsgConfigureChannelAnalyzer::m_settings.
Referenced by ChannelAnalyzerGUI::tick().
 { return m_settings.m_pll && m_pll.locked(); }
processOneSample()
void ChannelAnalyzer::processOneSample (Complex & c, fftfilt::cmplx * sideband) private
Definition at line 115 of file chanalyzer.cpp.
References DSBFilter, FreqLockComplex::feed(), PhaseLockComplex::feed(), feedOneSample(), FreqLockComplex::getComplex(), PhaseLockComplex::getComplex(), i, m_channelPowerAvg, ChannelAnalyzerSettings::m_fll, m_fll, m_magsq, ChannelAnalyzerSettings::m_pll, m_pll, ChannelAnalyzerSettings::m_rrc, m_settings, ChannelAnalyzerSettings::m_spanLog2, ChannelAnalyzerSettings::m_ssb, m_sum, m_undersampleCount, m_usb, RRCFilter, fftfilt::runDSB(), fftfilt::runFilt(), fftfilt::runSSB(), SDR_RX_SCALEF, and SSBFilter.
Referenced by feed().
 {
     int n_out;
     int decim = 1<<m_settings.m_spanLog2;
     if (m_settings.m_ssb)
     {
         n_out = SSBFilter->runSSB(c, &sideband, m_usb);
     }
     else
     {
         if (m_settings.m_rrc) {
             n_out = RRCFilter->runFilt(c, &sideband);
         } else {
             n_out = DSBFilter->runDSB(c, &sideband);
         }
     }
     for (int i = 0; i < n_out; i++)
     {
         // Downsample by 2^(m_scaleLog2 - 1) for SSB band spectrum display
         // smart decimation with bit gain using float arithmetic (23 bits significand)
         m_sum += sideband[i];
         if (!(m_undersampleCount++ & (decim - 1))) // counter LSB bit mask for decimation by 2^(m_scaleLog2 - 1)
         {
             m_sum /= decim;
             Real re = m_sum.real() / SDR_RX_SCALEF;
             Real im = m_sum.imag() / SDR_RX_SCALEF;
             m_magsq = re*re + im*im;
             m_channelPowerAvg(m_magsq);
             std::complex<float> mix;
             if (m_settings.m_pll)
             {
                 if (m_settings.m_fll)
                 {
                     m_fll.feed(re, im);
                     // Use -fPLL to mix (exchange PLL real and image in the complex multiplication)
                     mix = m_sum * std::conj(m_fll.getComplex());
                 }
                 else
                 {
                     m_pll.feed(re, im);
                     // Use -fPLL to mix (exchange PLL real and image in the complex multiplication)
                     mix = m_sum * std::conj(m_pll.getComplex());
                 }
             }
             feedOneSample(m_settings.m_pll ? mix : m_sum, m_settings.m_fll ? m_fll.getComplex() : m_pll.getComplex());
             m_sum = 0;
         }
     }
 }
serialize()
virtual QByteArray ChannelAnalyzer::serialize () const inline virtual
Implements ChannelAPI.
Definition at line 144 of file chanalyzer.h.
 { return QByteArray(); }
setFilters()
void ChannelAnalyzer::setFilters (int sampleRate, float bandwidth, float lowCutoff) private
Definition at line 270 of file chanalyzer.cpp.
References fftfilt::create_dsb_filter(), fftfilt::create_filter(), fftfilt::create_rrc_filter(), DSBFilter, ChannelAnalyzerSettings::m_rrcRolloff, m_settings, m_usb, RRCFilter, and SSBFilter.
Referenced by applyChannelSettings(), and applySettings().
 {
     qDebug("ChannelAnalyzer::setFilters: sampleRate: %d bandwidth: %f lowCutoff: %f",
             sampleRate, bandwidth, lowCutoff);
     if (bandwidth < 0)
     {
         bandwidth = -bandwidth;
         lowCutoff = -lowCutoff;
         m_usb = false;
     }
     else
     {
         m_usb = true;
     }
     if (bandwidth < 100.0f)
     {
         bandwidth = 100.0f;
         lowCutoff = 0;
     }
     SSBFilter->create_filter(lowCutoff / sampleRate, bandwidth / sampleRate);
     DSBFilter->create_dsb_filter(bandwidth / sampleRate);
     RRCFilter->create_rrc_filter(bandwidth / sampleRate, m_settings.m_rrcRolloff / 100.0);
 }
setSampleSink()
void ChannelAnalyzer::setSampleSink (BasebandSampleSink * sampleSink) inline
Definition at line 112 of file chanalyzer.h.
References m_sampleSink.
Referenced by ChannelAnalyzerGUI::ChannelAnalyzerGUI().
 { m_sampleSink = sampleSink; }
start()
void ChannelAnalyzer::start () virtual
Implements BasebandSampleSink.
Definition at line 171 of file chanalyzer.cpp.
References applyChannelSettings(), m_inputFrequencyOffset, and m_inputSampleRate.
Referenced by getPllPhase().
 {
     applyChannelSettings(m_inputSampleRate, m_inputFrequencyOffset, true);
 }
stop()
void ChannelAnalyzer::stop () virtual
Implements BasebandSampleSink.
Definition at line 176 of file chanalyzer.cpp.
Referenced by getPllPhase().
 {
 }
Member Data Documentation
DSBFilter
fftfilt* ChannelAnalyzer::DSBFilter private
Definition at line 182 of file chanalyzer.h.
Referenced by ChannelAnalyzer(), processOneSample(), setFilters(), and ~ChannelAnalyzer().
m_channelId
const QString ChannelAnalyzer::m_channelId = "ChannelAnalyzer" static
Definition at line 158 of file chanalyzer.h.
Referenced by ChannelAnalyzer(), and ChannelAnalyzerPlugin::initPlugin().
m_channelIdURI
const QString ChannelAnalyzer::m_channelIdURI = "sdrangel.channel.chanalyzer" static
Definition at line 157 of file chanalyzer.h.
Referenced by ChannelAnalyzerGUI::ChannelAnalyzerGUI(), and ChannelAnalyzerPlugin::initPlugin().
m_channelizer
DownChannelizer* ChannelAnalyzer::m_channelizer private
Definition at line 163 of file chanalyzer.h.
Referenced by ChannelAnalyzer(), getChannelizer(), handleMessage(), and ~ChannelAnalyzer().
m_channelPowerAvg
MovingAverageUtil<double, double, 480> ChannelAnalyzer::m_channelPowerAvg private
Definition at line 188 of file chanalyzer.h.
Referenced by getMagSqAvg(), and processOneSample().
m_corr
fftcorr* ChannelAnalyzer::m_corr private
Definition at line 184 of file chanalyzer.h.
Referenced by ChannelAnalyzer().
m_deviceAPI
DeviceAPI* ChannelAnalyzer::m_deviceAPI private
Definition at line 161 of file chanalyzer.h.
Referenced by ChannelAnalyzer(), and ~ChannelAnalyzer().
m_fll
FreqLockComplex ChannelAnalyzer::m_fll private
Definition at line 176 of file chanalyzer.h.
Referenced by applyChannelSettings(), applySettings(), getPllFrequency(), and processOneSample().
m_inputFrequencyOffset
int ChannelAnalyzer::m_inputFrequencyOffset private
Definition at line 167 of file chanalyzer.h.
Referenced by applyChannelSettings(), ChannelAnalyzer(), and start().
m_inputSampleRate
int ChannelAnalyzer::m_inputSampleRate private
Definition at line 166 of file chanalyzer.h.
Referenced by applyChannelSettings(), applySettings(), ChannelAnalyzer(), getChannelSampleRate(), getInputSampleRate(), and start().
m_interpolator
Interpolator ChannelAnalyzer::m_interpolator private
Definition at line 177 of file chanalyzer.h.
Referenced by applyChannelSettings(), applySettings(), and feed().
m_interpolatorDistance
Real ChannelAnalyzer::m_interpolatorDistance private
Definition at line 178 of file chanalyzer.h.
Referenced by applyChannelSettings(), applySettings(), ChannelAnalyzer(), and feed().
m_interpolatorDistanceRemain
Real ChannelAnalyzer::m_interpolatorDistanceRemain private
Definition at line 179 of file chanalyzer.h.
Referenced by applyChannelSettings(), applySettings(), ChannelAnalyzer(), and feed().
m_magsq
double ChannelAnalyzer::m_magsq private
Definition at line 171 of file chanalyzer.h.
Referenced by ChannelAnalyzer(), getMagSq(), and processOneSample().
m_nco
NCOF ChannelAnalyzer::m_nco private
Definition at line 174 of file chanalyzer.h.
Referenced by applyChannelSettings(), and feed().
m_pll
PhaseLockComplex ChannelAnalyzer::m_pll private
Definition at line 175 of file chanalyzer.h.
Referenced by applyChannelSettings(), applySettings(), ChannelAnalyzer(), getPllDeltaPhase(), getPllFrequency(), getPllPhase(), isPllLocked(), and processOneSample().
m_sampleBuffer
SampleVector ChannelAnalyzer::m_sampleBuffer private
Definition at line 187 of file chanalyzer.h.
Referenced by feed().
m_sampleSink
BasebandSampleSink* ChannelAnalyzer::m_sampleSink private
Definition at line 186 of file chanalyzer.h.
Referenced by feed(), and setSampleSink().
m_settings
ChannelAnalyzerSettings ChannelAnalyzer::m_settings private
Definition at line 164 of file chanalyzer.h.
Referenced by applyChannelSettings(), applySettings(), ChannelAnalyzer(), feed(), getPllFrequency(), processOneSample(), and setFilters().
m_settingsMutex
QMutex ChannelAnalyzer::m_settingsMutex private
Definition at line 189 of file chanalyzer.h.
Referenced by applyChannelSettings(), applySettings(), and feed().
m_sum
fftfilt::cmplx ChannelAnalyzer::m_sum private
Definition at line 169 of file chanalyzer.h.
Referenced by ChannelAnalyzer(), and processOneSample().
m_threadedChannelizer
ThreadedBasebandSampleSink* ChannelAnalyzer::m_threadedChannelizer private
Definition at line 162 of file chanalyzer.h.
Referenced by ChannelAnalyzer(), and ~ChannelAnalyzer().
m_undersampleCount
int ChannelAnalyzer::m_undersampleCount private
Definition at line 168 of file chanalyzer.h.
Referenced by ChannelAnalyzer(), and processOneSample().
m_usb
bool ChannelAnalyzer::m_usb private
Definition at line 170 of file chanalyzer.h.
Referenced by ChannelAnalyzer(), processOneSample(), and setFilters().
m_useInterpolator
bool ChannelAnalyzer::m_useInterpolator private
Definition at line 172 of file chanalyzer.h.
Referenced by applySettings(), ChannelAnalyzer(), and feed().
RRCFilter
fftfilt* ChannelAnalyzer::RRCFilter private
Definition at line 183 of file chanalyzer.h.
Referenced by applySettings(), ChannelAnalyzer(), processOneSample(), setFilters(), and ~ChannelAnalyzer().
SSBFilter
fftfilt* ChannelAnalyzer::SSBFilter private
Definition at line 181 of file chanalyzer.h.
Referenced by ChannelAnalyzer(), processOneSample(), setFilters(), and ~ChannelAnalyzer().
The documentation for this class was generated from the following files:
plugins/channelrx/chanalyzer/chanalyzer.h
plugins/channelrx/chanalyzer/chanalyzer.cpp