SDRAngel: SWGSDRangel::SWGInstanceDevicesResponse Class Reference
SWGSDRangel::SWGInstanceDevicesResponse Class Reference
#include <SWGInstanceDevicesResponse.h>
Public Member Functions
SWGInstanceDevicesResponse ()
SWGInstanceDevicesResponse (QString *json)
virtual ~SWGInstanceDevicesResponse ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGInstanceDevicesResponse * fromJson (QString &jsonString) override
qint32 getDevicecount ()
void setDevicecount (qint32 devicecount)
QList< SWGDeviceListItem * > * getDevices ()
void setDevices (QList< SWGDeviceListItem *> *devices)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 devicecount
bool m_devicecount_isSet
QList< SWGDeviceListItem * > * devices
bool m_devices_isSet
Detailed Description
Definition at line 33 of file SWGInstanceDevicesResponse.h.
Constructor & Destructor Documentation
SWGInstanceDevicesResponse() [1/2]
SWGSDRangel::SWGInstanceDevicesResponse::SWGInstanceDevicesResponse ()
Definition at line 30 of file SWGInstanceDevicesResponse.cpp.
References devicecount, devices, m_devicecount_isSet, and m_devices_isSet.
{
     devicecount = 0;
     m_devicecount_isSet = false;
     devices = nullptr;
     m_devices_isSet = false;
 }
SWGInstanceDevicesResponse() [2/2]
SWGSDRangel::SWGInstanceDevicesResponse::SWGInstanceDevicesResponse (QString * json)
Definition at line 25 of file SWGInstanceDevicesResponse.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGInstanceDevicesResponse()
SWGSDRangel::SWGInstanceDevicesResponse::~SWGInstanceDevicesResponse () virtual
Definition at line 37 of file SWGInstanceDevicesResponse.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGInstanceDevicesResponse::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 79 of file SWGInstanceDevicesResponse.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::instanceDevicesService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGInstanceDevicesResponse::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 90 of file SWGInstanceDevicesResponse.cpp.
References devicecount, devices, m_devicecount_isSet, and SWGSDRangel::toJsonArray().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_devicecount_isSet){
         obj->insert("devicecount", QJsonValue(devicecount));
     }
     if(devices->size() > 0){
         toJsonArray((QList<void*>*)devices, obj, "devices", "SWGDeviceListItem");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGInstanceDevicesResponse::cleanup ()
Definition at line 50 of file SWGInstanceDevicesResponse.cpp.
References devices.
Referenced by ~SWGInstanceDevicesResponse().
{
     if(devices != nullptr) {
         auto arr = devices;
         for(auto o: *arr) {
             delete o;
         }
         delete devices;
     }
 }
fromJson()
SWGInstanceDevicesResponse * SWGSDRangel::SWGInstanceDevicesResponse::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 62 of file SWGInstanceDevicesResponse.cpp.
References fromJsonObject().
Referenced by SWGInstanceDevicesResponse().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGInstanceDevicesResponse::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 71 of file SWGInstanceDevicesResponse.cpp.
References devicecount, devices, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&devicecount, pJson["devicecount"], "qint32", "");
     ::SWGSDRangel::setValue(&devices, pJson["devices"], "QList", "SWGDeviceListItem");
 }
getDevicecount()
qint32 SWGSDRangel::SWGInstanceDevicesResponse::getDevicecount ()
Definition at line 103 of file SWGInstanceDevicesResponse.cpp.
References devicecount.
{
     return devicecount;
 }
getDevices()
QList< SWGDeviceListItem * > * SWGSDRangel::SWGInstanceDevicesResponse::getDevices ()
Definition at line 113 of file SWGInstanceDevicesResponse.cpp.
References devices.
Referenced by WebAPIAdapterGUI::instanceDevices(), and WebAPIAdapterSrv::instanceDevices().
{
     return devices;
 }
init()
void SWGSDRangel::SWGInstanceDevicesResponse::init ()
Definition at line 42 of file SWGInstanceDevicesResponse.cpp.
References devicecount, devices, m_devicecount_isSet, and m_devices_isSet.
Referenced by WebAPIAdapterGUI::instanceDevices(), WebAPIAdapterSrv::instanceDevices(), and SWGInstanceDevicesResponse().
{
     devicecount = 0;
     m_devicecount_isSet = false;
     devices = new QList<SWGDeviceListItem*>();
     m_devices_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGInstanceDevicesResponse::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 124 of file SWGInstanceDevicesResponse.cpp.
References devices, and m_devicecount_isSet.
{
     bool isObjectUpdated = false;
     do{
         if(m_devicecount_isSet){ isObjectUpdated = true; break;}
         if(devices->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setDevicecount()
void SWGSDRangel::SWGInstanceDevicesResponse::setDevicecount (qint32 devicecount)
Definition at line 107 of file SWGInstanceDevicesResponse.cpp.
References devicecount, and m_devicecount_isSet.
Referenced by WebAPIAdapterGUI::instanceDevices(), and WebAPIAdapterSrv::instanceDevices().
{
     this->devicecount = devicecount;
     this->m_devicecount_isSet = true;
 }
setDevices()
void SWGSDRangel::SWGInstanceDevicesResponse::setDevices (QList< SWGDeviceListItem *> * devices)
Definition at line 117 of file SWGInstanceDevicesResponse.cpp.
References devices, and m_devices_isSet.
{
     this->devices = devices;
     this->m_devices_isSet = true;
 }
Member Data Documentation
devicecount
qint32 SWGSDRangel::SWGInstanceDevicesResponse::devicecount private
Definition at line 56 of file SWGInstanceDevicesResponse.h.
Referenced by asJsonObject(), fromJsonObject(), getDevicecount(), init(), setDevicecount(), and SWGInstanceDevicesResponse().
devices
QList<SWGDeviceListItem*>* SWGSDRangel::SWGInstanceDevicesResponse::devices private
Definition at line 59 of file SWGInstanceDevicesResponse.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getDevices(), init(), isSet(), setDevices(), and SWGInstanceDevicesResponse().
m_devicecount_isSet
bool SWGSDRangel::SWGInstanceDevicesResponse::m_devicecount_isSet private
Definition at line 57 of file SWGInstanceDevicesResponse.h.
Referenced by asJsonObject(), init(), isSet(), setDevicecount(), and SWGInstanceDevicesResponse().
m_devices_isSet
bool SWGSDRangel::SWGInstanceDevicesResponse::m_devices_isSet private
Definition at line 60 of file SWGInstanceDevicesResponse.h.
Referenced by init(), setDevices(), and SWGInstanceDevicesResponse().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGInstanceDevicesResponse.h
swagger/sdrangel/code/qt5/client/SWGInstanceDevicesResponse.cpp