SDRAngel: LowPassFilterRC Class Reference
LowPassFilterRC Class Reference
#include <filterrc.h>
Public Member Functions
LowPassFilterRC (Real timeconst)
void configure (Real timeout)
void process (const Real &sample_in, Real &sample_out)
Private Attributes
Real m_timeconst
Real m_y1
Real m_a1
Real m_b0
Detailed Description
First order low-pass IIR filter for real-valued signals.
Definition at line 26 of file filterrc.h.
Constructor & Destructor Documentation
LowPassFilterRC()
LowPassFilterRC::LowPassFilterRC (Real timeconst)
Construct 1st order low-pass IIR filter.
timeconst :: RC time constant in seconds (1 / (2 * PI * cutoff_freq)
Definition at line 23 of file filterrc.cpp.
References exp(), m_a1, m_b0, and m_timeconst.
                                                :
     m_timeconst(timeconst),
     m_y1(0)
 {
     m_a1 = - exp(-1/m_timeconst);
     m_b0 = 1 + m_a1;
 }
Member Function Documentation
configure()
void LowPassFilterRC::configure (Real timeout)
Reconfigure filter with new time constant
Definition at line 32 of file filterrc.cpp.
References exp(), m_a1, m_b0, m_timeconst, and m_y1.
Referenced by BFMDemod::applyAudioSampleRate(), and BFMDemod::BFMDemod().
 {
     m_timeconst = timeconst;
     m_y1 = 0;
     m_a1 = - exp(-1/m_timeconst);
     m_b0 = 1 + m_a1;
     qDebug() << "LowPassFilterRC::configure: t: " << m_timeconst
             << " a1: " << m_a1
             << " b0: " << m_b0;
 }
process()
void LowPassFilterRC::process (const Real & sample_in, Real & sample_out)
Process samples.
Definition at line 45 of file filterrc.cpp.
References m_a1, m_b0, and m_y1.
Referenced by BFMDemod::feed().
 {
     /*
      * Continuous domain:
      *   H(s) = 1 / (1 - s * timeconst)
      *
      * Discrete domain:
      *   H(z) = (1 - exp(-1/timeconst)) / (1 - exp(-1/timeconst) / z)
      */
     m_y1 = (sample_in * m_b0) - (m_y1 * m_a1);
     sample_out = m_y1;
 }
Member Data Documentation
m_a1
Real LowPassFilterRC::m_a1 private
Definition at line 48 of file filterrc.h.
Referenced by configure(), LowPassFilterRC(), and process().
m_b0
Real LowPassFilterRC::m_b0 private
Definition at line 49 of file filterrc.h.
Referenced by configure(), LowPassFilterRC(), and process().
m_timeconst
Real LowPassFilterRC::m_timeconst private
Definition at line 46 of file filterrc.h.
Referenced by configure(), and LowPassFilterRC().
m_y1
Real LowPassFilterRC::m_y1 private
Definition at line 47 of file filterrc.h.
Referenced by configure(), and process().
The documentation for this class was generated from the following files:
sdrbase/dsp/filterrc.h
sdrbase/dsp/filterrc.cpp