SDRAngel: AMMod::MsgReportFileSourceStreamData Class Reference
AMMod::MsgReportFileSourceStreamData Class Reference
#include <ammod.h>
Public Member Functions
int getSampleRate () const
quint32 getRecordLength () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportFileSourceStreamData * create (int sampleRate, quint32 recordLength)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportFileSourceStreamData (int sampleRate, quint32 recordLength)
Protected Attributes
int m_sampleRate
quint32 m_recordLength
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 177 of file ammod.h.
Constructor & Destructor Documentation
MsgReportFileSourceStreamData()
AMMod::MsgReportFileSourceStreamData::MsgReportFileSourceStreamData (int sampleRate, quint32 recordLength) inline protected
Definition at line 194 of file ammod.h.
References AMMod::AMMod(), and AMMod::~AMMod().
                                       :
             Message(),
             m_sampleRate(sampleRate),
             m_recordLength(recordLength)
         { }
Member Function Documentation
create()
static MsgReportFileSourceStreamData* AMMod::MsgReportFileSourceStreamData::create (int sampleRate, quint32 recordLength) inline static
Definition at line 184 of file ammod.h.
Referenced by AMMod::openFileStream().
         {
             return new MsgReportFileSourceStreamData(sampleRate, recordLength);
         }
getRecordLength()
quint32 AMMod::MsgReportFileSourceStreamData::getRecordLength () const inline
Definition at line 182 of file ammod.h.
References AMMod::m_recordLength.
 { return m_recordLength; }
getSampleRate()
int AMMod::MsgReportFileSourceStreamData::getSampleRate () const inline
Definition at line 181 of file ammod.h.
References AMMod::m_sampleRate.
 { return m_sampleRate; }
Member Data Documentation
m_recordLength
quint32 AMMod::MsgReportFileSourceStreamData::m_recordLength protected
Definition at line 192 of file ammod.h.
m_sampleRate
int AMMod::MsgReportFileSourceStreamData::m_sampleRate protected
Definition at line 191 of file ammod.h.
The documentation for this class was generated from the following file:
plugins/channeltx/modam/ammod.h