SDRAngel: ScopeVis::TraceBackDiscreteMemory Struct Reference
ScopeVis::TraceBackDiscreteMemory Struct Reference
Public Member Functions
TraceBackDiscreteMemory (uint32_t size)
void resize (uint32_t size)
TraceBackBuffer & store (int samplesToReport)
TraceBackBuffer & recall (uint32_t shift)
TraceBackBuffer & current ()
TraceBackBuffer & at (int index)
uint32_t currentIndex () const
QByteArray serialize () const
bool deserialize (const QByteArray &data)
Public Attributes
std::vector< TraceBackBuffer > m_traceBackBuffers
uint32_t m_memSize
uint32_t m_currentMemIndex
uint32_t m_traceSize
Detailed Description
Definition at line 703 of file scopevis.h.
Constructor & Destructor Documentation
TraceBackDiscreteMemory()
ScopeVis::TraceBackDiscreteMemory::TraceBackDiscreteMemory (uint32_t size) inline
Give memory size in number of traces
Definition at line 713 of file scopevis.h.
                                                : m_memSize(size), m_currentMemIndex(0), m_traceSize(0)
         {
             m_traceBackBuffers.resize(m_memSize);
         }
Member Function Documentation
at()
TraceBackBuffer& ScopeVis::TraceBackDiscreteMemory::at (int index) inline
Return trace at given memory position
Definition at line 766 of file scopevis.h.
Referenced by ScopeVis::processMemoryTrace().
         {
             return m_traceBackBuffers[index];
         }
current()
TraceBackBuffer& ScopeVis::TraceBackDiscreteMemory::current () inline
Return trace at current memory position
Definition at line 758 of file scopevis.h.
Referenced by ScopeVis::processTrace().
         {
             return m_traceBackBuffers[m_currentMemIndex];
         }
currentIndex()
uint32_t ScopeVis::TraceBackDiscreteMemory::currentIndex () const inline
Return current memory index
Definition at line 774 of file scopevis.h.
Referenced by ScopeVis::processMemoryTrace().
 { return m_currentMemIndex; }
deserialize()
bool ScopeVis::TraceBackDiscreteMemory::deserialize (const QByteArray & data) inline
Deserializer
Definition at line 799 of file scopevis.h.
References SimpleDeserializer::getVersion(), i, SimpleDeserializer::isValid(), SimpleDeserializer::readBlob(), and SimpleDeserializer::readU32().
         {
             SimpleDeserializer d(data);
             if(!d.isValid()) {
                 return false;
             }
             if (d.getVersion() == 1)
             {
                 d.readU32(1, &m_memSize, 0);
                 d.readU32(2, &m_currentMemIndex, 0);
                 uint32_t traceSize;
                 d.readU32(3, &traceSize, 0);
                 m_traceBackBuffers.resize(m_memSize);
                 if (traceSize != m_traceSize) {
                     resize(traceSize);
                 }
                 for (unsigned int i = 0; i < m_memSize; i++)
                 {
                     QByteArray buffer;
                     d.readBlob(100+i, &buffer);
                     m_traceBackBuffers[i].deserialize(buffer);
                 }
                 return true;
             }
             else
             {
                 return false;
             }
         }
recall()
TraceBackBuffer& ScopeVis::TraceBackDiscreteMemory::recall (uint32_t shift) inline
Recalls trace at shift positions back. Therefore 0 is current. Wraps around memory size.
Definition at line 749 of file scopevis.h.
         {
             int index = (m_currentMemIndex + (m_memSize - (shift % m_memSize))) % m_memSize;
             return m_traceBackBuffers[index];
         }
resize()
void ScopeVis::TraceBackDiscreteMemory::resize (uint32_t size) inline
Resize all trace buffers in memory
Definition at line 721 of file scopevis.h.
Referenced by ScopeVis::ScopeVis(), and ScopeVis::setTraceSize().
         {
             m_traceSize = size;
             for (std::vector<TraceBackBuffer>::iterator it = m_traceBackBuffers.begin(); it != m_traceBackBuffers.end(); ++it)
             {
                 it->resize(2*m_traceSize); // was multiplied by 4
             }
         }
serialize()
QByteArray ScopeVis::TraceBackDiscreteMemory::serialize () const inline
Serializer
Definition at line 779 of file scopevis.h.
References SimpleSerializer::final(), i, SimpleSerializer::writeBlob(), and SimpleSerializer::writeU32().
         {
             SimpleSerializer s(1);
             s.writeU32(1, m_memSize);
             s.writeU32(2, m_currentMemIndex);
             s.writeU32(3, m_traceSize);
             for (unsigned int i = 0; i < m_memSize; i++)
             {
                 QByteArray buffer = m_traceBackBuffers[i].serialize();
                 s.writeBlob(100+i, buffer);
             }
             return s.final();
         }
store()
TraceBackBuffer& ScopeVis::TraceBackDiscreteMemory::store (int samplesToReport) inline
Move index forward by one position and return reference to the trace at this position Copy a trace length of samples into the new memory slot samplesToReport are the number of samples to report on the next trace
Definition at line 736 of file scopevis.h.
References ScopeVis::TraceBackBuffer::reset().
Referenced by ScopeVis::processTrace().
         {
             uint32_t nextMemIndex = m_currentMemIndex < (m_memSize-1) ? m_currentMemIndex+1 : 0;
             m_traceBackBuffers[nextMemIndex].reset();
             m_traceBackBuffers[nextMemIndex].write(m_traceBackBuffers[m_currentMemIndex].m_endPoint - samplesToReport,
                     m_traceBackBuffers[m_currentMemIndex].m_endPoint);
             m_currentMemIndex = nextMemIndex;
             return m_traceBackBuffers[m_currentMemIndex]; // new trace
         }
Member Data Documentation
m_currentMemIndex
uint32_t ScopeVis::TraceBackDiscreteMemory::m_currentMemIndex
Definition at line 707 of file scopevis.h.
m_memSize
uint32_t ScopeVis::TraceBackDiscreteMemory::m_memSize
Definition at line 706 of file scopevis.h.
m_traceBackBuffers
std::vector<TraceBackBuffer> ScopeVis::TraceBackDiscreteMemory::m_traceBackBuffers
Definition at line 705 of file scopevis.h.
m_traceSize
uint32_t ScopeVis::TraceBackDiscreteMemory::m_traceSize
Definition at line 708 of file scopevis.h.
The documentation for this struct was generated from the following file:
sdrgui/dsp/scopevis.h