SDRAngel: UDPSinkGUI Class Reference
UDPSinkGUI Class Reference
#include <udpsinkgui.h>
Public Slots
void channelMarkerChangedByCursor ()
void channelMarkerHighlightedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static UDPSinkGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
Private Slots
void handleSourceMessages ()
void on_deltaFrequency_changed (qint64 value)
void on_sampleFormat_currentIndexChanged (int index)
void on_outputUDPAddress_editingFinished ()
void on_outputUDPPort_editingFinished ()
void on_inputUDPAudioPort_editingFinished ()
void on_sampleRate_textEdited (const QString &arg1)
void on_rfBandwidth_textEdited (const QString &arg1)
void on_fmDeviation_textEdited (const QString &arg1)
void on_audioActive_toggled (bool active)
void on_audioStereo_toggled (bool stereo)
void on_applyBtn_clicked ()
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void on_gain_valueChanged (int value)
void on_volume_valueChanged (int value)
void on_squelch_valueChanged (int value)
void on_squelchGate_valueChanged (int value)
void on_agc_toggled (bool agc)
void tick ()
Private Member Functions
UDPSinkGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *parent=0)
virtual ~UDPSinkGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void applySettingsImmediate (bool force=false)
void displaySettings ()
void setSampleFormat (int index)
void setSampleFormatIndex (const UDPSinkSettings::SampleFormat &sampleFormat)
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::UDPSinkGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
UDPSink * m_udpSink
UDPSinkSettings m_settings
ChannelMarker m_channelMarker
MovingAverage< double > m_channelPowerAvg
MovingAverage< double > m_inPowerAvg
uint32_t m_tickCount
bool m_doApplySettings
bool m_rfBandwidthChanged
MessageQueue m_inputMessageQueue
SpectrumVis * m_spectrumVis
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 41 of file udpsinkgui.h.
Constructor & Destructor Documentation
UDPSinkGUI()
UDPSinkGUI::UDPSinkGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * parent = 0) explicit private
Definition at line 155 of file udpsinkgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), applySettingsImmediate(), arg(), FFTWindow::BlackmanHarris, channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), SpectrumVis::configure(), displaySettings(), ChannelMarker::getColor(), getInputMessageQueue(), BasebandSampleSink::getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, handleSourceMessages(), UDPSink::m_channelIdURI, m_channelMarker, m_deviceUISet, UDPSinkSettings::m_rgbColor, m_settings, m_spectrumVis, m_udpSink, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), SDR_RX_SCALEF, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), UDPSinkSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSink::setMessageQueueToGUI(), UDPSink::setSpectrum(), UDPSinkSettings::setSpectrumGUI(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                      :
     RollupWidget(parent),
     ui(new Ui::UDPSinkGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_udpSink(0),
     m_channelMarker(this),
     m_channelPowerAvg(4, 1e-10),
     m_inPowerAvg(4, 1e-10),
     m_tickCount(0),
     m_doApplySettings(true),
     m_rfBandwidthChanged(false)
 {
     ui->setupUi(this);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     setAttribute(Qt::WA_DeleteOnClose, true);
     m_spectrumVis = new SpectrumVis(SDR_RX_SCALEF, ui->glSpectrum);
     m_udpSink = (UDPSink*) rxChannel; //new UDPSrc(m_deviceUISet->m_deviceSourceAPI);
     m_udpSink->setSpectrum(m_spectrumVis);
     m_udpSink->setMessageQueueToGUI(getInputMessageQueue());
     ui->fmDeviation->setEnabled(false);
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     ui->squelchLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     ui->glSpectrum->setCenterFrequency(0);
     ui->glSpectrum->setSampleRate(ui->sampleRate->text().toInt());
     ui->glSpectrum->setDisplayWaterfall(true);
     ui->glSpectrum->setDisplayMaxHold(true);
     m_spectrumVis->configure(m_spectrumVis->getInputMessageQueue(),
             64, // FFT size
             10, // overlapping %
             0,  // number of averaging samples
             0,  // no averaging
             FFTWindow::BlackmanHarris,
             false); // logarithmic scale
     ui->glSpectrum->connectTimer(MainWindow::getInstance()->getMasterTimer());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     m_channelMarker.blockSignals(true);
     m_channelMarker.setBandwidth(16000);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("UDP Sample Source");
     m_channelMarker.setColor(m_settings.m_rgbColor);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     setTitleColor(m_channelMarker.getColor());
     m_settings.setChannelMarker(&m_channelMarker);
     m_settings.setSpectrumGUI(ui->spectrumGUI);
     m_deviceUISet->registerRxChannelInstance(UDPSink::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(&m_channelMarker, SIGNAL(highlightedByCursor()), this, SLOT(channelMarkerHighlightedByCursor()));
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleSourceMessages()));
     ui->spectrumGUI->setBuddies(m_spectrumVis->getInputMessageQueue(), m_spectrumVis, ui->glSpectrum);
     displaySettings();
     applySettingsImmediate(true);
     applySettings(true);
 }
~UDPSinkGUI()
UDPSinkGUI::~UDPSinkGUI () private virtual
Definition at line 228 of file udpsinkgui.cpp.
References m_deviceUISet, m_spectrumVis, m_udpSink, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_udpSink; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete m_spectrumVis;
     delete ui;
 }
Member Function Documentation
applySettings()
void UDPSinkGUI::applySettings (bool force = false) private
Definition at line 399 of file udpsinkgui.cpp.
References UDPSink::MsgConfigureUDPSource::create(), UDPSink::MsgConfigureChannelizer::create(), ChannelMarker::getCenterFrequency(), BasebandSampleSink::getInputMessageQueue(), m_channelMarker, m_doApplySettings, UDPSinkSettings::m_outputSampleRate, m_settings, m_udpSink, MessageQueue::push(), and ui.
Referenced by deserialize(), on_applyBtn_clicked(), on_deltaFrequency_changed(), resetToDefaults(), setCenterFrequency(), and UDPSinkGUI().
 {
     if (m_doApplySettings)
     {
         UDPSink::MsgConfigureChannelizer* channelConfigMsg = UDPSink::MsgConfigureChannelizer::create(
                 m_settings.m_outputSampleRate, m_channelMarker.getCenterFrequency());
         m_udpSink->getInputMessageQueue()->push(channelConfigMsg);
         UDPSink::MsgConfigureUDPSource* message = UDPSink::MsgConfigureUDPSource::create( m_settings, force);
         m_udpSink->getInputMessageQueue()->push(message);
         ui->applyBtn->setEnabled(false);
         ui->applyBtn->setStyleSheet("QPushButton { background:rgb(79,79,79); }");
     }
 }
applySettingsImmediate()
void UDPSinkGUI::applySettingsImmediate (bool force = false) private
Definition at line 390 of file udpsinkgui.cpp.
References UDPSink::MsgConfigureUDPSource::create(), BasebandSampleSink::getInputMessageQueue(), m_doApplySettings, m_settings, m_udpSink, and MessageQueue::push().
Referenced by channelMarkerChangedByCursor(), deserialize(), on_agc_toggled(), on_audioActive_toggled(), on_audioStereo_toggled(), on_gain_valueChanged(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), and UDPSinkGUI().
 {
     if (m_doApplySettings)
     {
         UDPSink::MsgConfigureUDPSource* message = UDPSink::MsgConfigureUDPSource::create( m_settings, force);
         m_udpSink->getInputMessageQueue()->push(message);
     }
 }
blockApplySettings()
void UDPSinkGUI::blockApplySettings (bool block) private
Definition at line 236 of file udpsinkgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), and handleMessage().
 {
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void UDPSinkGUI::channelMarkerChangedByCursor () slot
Definition at line 121 of file udpsinkgui.cpp.
References applySettingsImmediate(), ChannelMarker::getCenterFrequency(), m_channelMarker, UDPSinkSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by UDPSinkGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettingsImmediate();
 }
channelMarkerHighlightedByCursor
void UDPSinkGUI::channelMarkerHighlightedByCursor () slot
Definition at line 128 of file udpsinkgui.cpp.
References ChannelMarker::getHighlighted(), m_channelMarker, and RollupWidget::setHighlighted().
Referenced by UDPSinkGUI().
 {
     setHighlighted(m_channelMarker.getHighlighted());
 }
create()
UDPSinkGUI * UDPSinkGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) static
Definition at line 32 of file udpsinkgui.cpp.
References UDPSinkGUI().
Referenced by UDPSinkPlugin::createRxChannelGUI().
 {
     UDPSinkGUI* gui = new UDPSinkGUI(pluginAPI, deviceUISet, rxChannel);
     return gui;
 }
deserialize()
bool UDPSinkGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 77 of file udpsinkgui.cpp.
References applySettings(), applySettingsImmediate(), UDPSinkSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data))
     {
         displaySettings();
         applySettingsImmediate(true);
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void UDPSinkGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 38 of file udpsinkgui.cpp.
 {
     delete this;
 }
displaySettings()
void UDPSinkGUI::displaySettings () private
Definition at line 241 of file udpsinkgui.cpp.
References arg(), blockApplySettings(), ChannelMarker::getCenterFrequency(), ChannelMarker::getTitle(), UDPSinkSettings::m_agc, UDPSinkSettings::m_audioActive, UDPSinkSettings::m_audioPort, UDPSinkSettings::m_audioStereo, m_channelMarker, UDPSinkSettings::m_fmDeviation, UDPSinkSettings::m_gain, UDPSinkSettings::m_inputFrequencyOffset, UDPSinkSettings::m_outputSampleRate, UDPSinkSettings::m_rfBandwidth, UDPSinkSettings::m_rgbColor, UDPSinkSettings::m_sampleFormat, m_settings, UDPSinkSettings::m_squelchdB, UDPSinkSettings::m_squelchGate, UDPSinkSettings::m_title, UDPSinkSettings::m_udpAddress, UDPSinkSettings::m_udpPort, UDPSinkSettings::m_volume, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), setSampleFormatIndex(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by deserialize(), handleMessage(), resetToDefaults(), and UDPSinkGUI().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setBandwidth(m_settings.m_rfBandwidth);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     ui->sampleRate->setText(QString("%1").arg(m_settings.m_outputSampleRate, 0));
     setSampleFormatIndex(m_settings.m_sampleFormat);
     ui->outputUDPAddress->setText(m_settings.m_udpAddress);
     ui->outputUDPPort->setText(tr("%1").arg(m_settings.m_udpPort));
     ui->inputUDPAudioPort->setText(tr("%1").arg(m_settings.m_audioPort));
     ui->squelch->setValue(m_settings.m_squelchdB);
     ui->squelchText->setText(tr("%1").arg(ui->squelch->value()*1.0, 0, 'f', 0));
     qDebug("UDPSinkGUI::deserialize: m_squelchGate: %d", m_settings.m_squelchGate);
     ui->squelchGate->setValue(m_settings.m_squelchGate);
     ui->squelchGateText->setText(tr("%1").arg(m_settings.m_squelchGate*10.0, 0, 'f', 0));
     ui->rfBandwidth->setText(QString("%1").arg(m_settings.m_rfBandwidth, 0));
     ui->fmDeviation->setText(QString("%1").arg(m_settings.m_fmDeviation, 0));
     ui->agc->setChecked(m_settings.m_agc);
     ui->audioActive->setChecked(m_settings.m_audioActive);
     ui->audioStereo->setChecked(m_settings.m_audioStereo);
     ui->volume->setValue(m_settings.m_volume);
     ui->volumeText->setText(QString("%1").arg(ui->volume->value()));
     ui->gain->setValue(m_settings.m_gain*10.0);
     ui->gainText->setText(tr("%1").arg(ui->gain->value()/10.0, 0, 'f', 1));
     ui->applyBtn->setEnabled(false);
     ui->applyBtn->setStyleSheet("QPushButton { background:rgb(79,79,79); }");
     blockApplySettings(false);
     ui->glSpectrum->setSampleRate(m_settings.m_outputSampleRate);
 }
enterEvent()
void UDPSinkGUI::enterEvent (QEvent *) private
Definition at line 652 of file udpsinkgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 UDPSinkGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 48 of file udpsinkgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
 {
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* UDPSinkGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 56 of file udpsinkgui.h.
Referenced by handleSourceMessages(), and UDPSinkGUI().
 { return &m_inputMessageQueue; }
getName()
QString UDPSinkGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 59 of file udpsinkgui.cpp.
 {
     return objectName();
 }
handleMessage()
bool UDPSinkGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 91 of file udpsinkgui.cpp.
References blockApplySettings(), displaySettings(), UDPSink::MsgConfigureUDPSource::getSettings(), m_settings, and Message::match().
Referenced by handleSourceMessages().
 {
     if (UDPSink::MsgConfigureUDPSource::match(message))
     {
         const UDPSink::MsgConfigureUDPSource& cfg = (UDPSink::MsgConfigureUDPSource&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
handleSourceMessages
void UDPSinkGUI::handleSourceMessages () private slot
Definition at line 108 of file udpsinkgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by UDPSinkGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
leaveEvent()
void UDPSinkGUI::leaveEvent (QEvent *) private
Definition at line 647 of file udpsinkgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_agc_toggled
void UDPSinkGUI::on_agc_toggled (bool agc) private slot
Definition at line 562 of file udpsinkgui.cpp.
References applySettingsImmediate(), UDPSinkSettings::m_agc, and m_settings.
 {
     m_settings.m_agc = agc;
     applySettingsImmediate();
 }
on_applyBtn_clicked
void UDPSinkGUI::on_applyBtn_clicked () private slot
Definition at line 537 of file udpsinkgui.cpp.
References applySettings(), m_channelMarker, UDPSinkSettings::m_outputSampleRate, UDPSinkSettings::m_rfBandwidth, m_rfBandwidthChanged, m_settings, ChannelMarker::setBandwidth(), and ui.
 {
     if (m_rfBandwidthChanged)
     {
         m_channelMarker.setBandwidth((int) m_settings.m_rfBandwidth);
         m_rfBandwidthChanged = false;
     }
     ui->glSpectrum->setSampleRate(m_settings.m_outputSampleRate);
     applySettings();
 }
on_audioActive_toggled
void UDPSinkGUI::on_audioActive_toggled (bool active) private slot
Definition at line 550 of file udpsinkgui.cpp.
References applySettingsImmediate(), UDPSinkSettings::m_audioActive, and m_settings.
 {
     m_settings.m_audioActive = active;
     applySettingsImmediate();
 }
on_audioStereo_toggled
void UDPSinkGUI::on_audioStereo_toggled (bool stereo) private slot
Definition at line 556 of file udpsinkgui.cpp.
References applySettingsImmediate(), UDPSinkSettings::m_audioStereo, and m_settings.
 {
     m_settings.m_audioStereo = stereo;
     applySettingsImmediate();
 }
on_deltaFrequency_changed
void UDPSinkGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 415 of file udpsinkgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, UDPSinkSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_fmDeviation_textEdited
void UDPSinkGUI::on_fmDeviation_textEdited (const QString & arg1) private slot
Definition at line 517 of file udpsinkgui.cpp.
References arg(), UDPSinkSettings::m_fmDeviation, m_settings, and ui.
 {
     (void) arg1;
     bool ok;
     int fmDeviation = ui->fmDeviation->text().toInt(&ok);
     if ((!ok) || (fmDeviation < 1))
     {
         m_settings.m_fmDeviation = 2500;
         ui->fmDeviation->setText(QString("%1").arg(m_settings.m_fmDeviation));
     }
     else
     {
         m_settings.m_fmDeviation = fmDeviation;
     }
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_gain_valueChanged
void UDPSinkGUI::on_gain_valueChanged (int value) private slot
Definition at line 568 of file udpsinkgui.cpp.
References applySettingsImmediate(), arg(), UDPSinkSettings::m_gain, m_settings, and ui.
 {
     m_settings.m_gain = value / 10.0;
     ui->gainText->setText(tr("%1").arg(value/10.0, 0, 'f', 1));
     applySettingsImmediate();
 }
on_inputUDPAudioPort_editingFinished
void UDPSinkGUI::on_inputUDPAudioPort_editingFinished () private slot
Definition at line 459 of file udpsinkgui.cpp.
References arg(), UDPSinkSettings::m_audioPort, m_settings, and ui.
 {
     bool ok;
     quint16 udpPort = ui->inputUDPAudioPort->text().toInt(&ok);
     if((!ok) || (udpPort < 1024)) {
         udpPort = 9997;
     }
     m_settings.m_audioPort = udpPort;
     ui->inputUDPAudioPort->setText(tr("%1").arg(m_settings.m_audioPort));
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_outputUDPAddress_editingFinished
void UDPSinkGUI::on_outputUDPAddress_editingFinished () private slot
Definition at line 436 of file udpsinkgui.cpp.
References m_settings, UDPSinkSettings::m_udpAddress, and ui.
 {
     m_settings.m_udpAddress = ui->outputUDPAddress->text();
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_outputUDPPort_editingFinished
void UDPSinkGUI::on_outputUDPPort_editingFinished () private slot
Definition at line 443 of file udpsinkgui.cpp.
References arg(), m_settings, UDPSinkSettings::m_udpPort, and ui.
 {
     bool ok;
     quint16 udpPort = ui->outputUDPPort->text().toInt(&ok);
     if((!ok) || (udpPort < 1024)) {
         udpPort = 9998;
     }
     m_settings.m_udpPort = udpPort;
     ui->outputUDPPort->setText(tr("%1").arg(m_settings.m_udpPort));
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_rfBandwidth_textEdited
void UDPSinkGUI::on_rfBandwidth_textEdited (const QString & arg1) private slot
Definition at line 495 of file udpsinkgui.cpp.
References arg(), UDPSinkSettings::m_outputSampleRate, UDPSinkSettings::m_rfBandwidth, m_rfBandwidthChanged, m_settings, and ui.
 {
     (void) arg1;
     bool ok;
     Real rfBandwidth = ui->rfBandwidth->text().toDouble(&ok);
     if ((!ok) || (rfBandwidth > m_settings.m_outputSampleRate))
     {
         m_settings.m_rfBandwidth = m_settings.m_outputSampleRate;
         ui->rfBandwidth->setText(QString("%1").arg(m_settings.m_rfBandwidth, 0));
     }
     else
     {
         m_settings.m_rfBandwidth = rfBandwidth;
     }
     m_rfBandwidthChanged = true;
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_sampleFormat_currentIndexChanged
void UDPSinkGUI::on_sampleFormat_currentIndexChanged (int index) private slot
Definition at line 422 of file udpsinkgui.cpp.
References setSampleFormat(), and ui.
 {
     if ((index == 1) || (index == 2)) {
         ui->fmDeviation->setEnabled(true);
     } else {
         ui->fmDeviation->setEnabled(false);
     }
     setSampleFormat(index);
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_sampleRate_textEdited
void UDPSinkGUI::on_sampleRate_textEdited (const QString & arg1) private slot
Definition at line 475 of file udpsinkgui.cpp.
References arg(), UDPSinkSettings::m_outputSampleRate, m_settings, and ui.
 {
     (void) arg1;
     bool ok;
     Real outputSampleRate = ui->sampleRate->text().toDouble(&ok);
     if((!ok) || (outputSampleRate < 1000))
     {
         m_settings.m_outputSampleRate = 48000;
         ui->sampleRate->setText(QString("%1").arg(outputSampleRate, 0));
     }
     else
     {
         m_settings.m_outputSampleRate = outputSampleRate;
     }
     ui->applyBtn->setEnabled(true);
     ui->applyBtn->setStyleSheet("QPushButton { background-color : green; }");
 }
on_squelch_valueChanged
void UDPSinkGUI::on_squelch_valueChanged (int value) private slot
Definition at line 582 of file udpsinkgui.cpp.
References applySettingsImmediate(), arg(), m_settings, UDPSinkSettings::m_squelchdB, UDPSinkSettings::m_squelchEnabled, and ui.
 {
     m_settings.m_squelchdB = value;
     if (value == -100) // means disabled
     {
         ui->squelchText->setText("---");
         m_settings.m_squelchEnabled = false;
     }
     else
     {
         ui->squelchText->setText(tr("%1").arg(value*1.0, 0, 'f', 0));
         m_settings.m_squelchEnabled = true;
     }
     applySettingsImmediate();
 }
on_squelchGate_valueChanged
void UDPSinkGUI::on_squelchGate_valueChanged (int value) private slot
Definition at line 600 of file udpsinkgui.cpp.
References applySettingsImmediate(), arg(), m_settings, UDPSinkSettings::m_squelchGate, and ui.
 {
     m_settings.m_squelchGate = value;
     ui->squelchGateText->setText(tr("%1").arg(value*10.0, 0, 'f', 0));
     applySettingsImmediate();
 }
on_volume_valueChanged
void UDPSinkGUI::on_volume_valueChanged (int value) private slot
Definition at line 575 of file udpsinkgui.cpp.
References applySettingsImmediate(), arg(), m_settings, UDPSinkSettings::m_volume, and ui.
 {
     m_settings.m_volume = value;
     ui->volumeText->setText(QString("%1").arg(value));
     applySettingsImmediate();
 }
onMenuDialogCalled
void UDPSinkGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 615 of file udpsinkgui.cpp.
References applySettingsImmediate(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, UDPSinkSettings::m_inputFrequencyOffset, UDPSinkSettings::m_reverseAPIAddress, UDPSinkSettings::m_reverseAPIChannelIndex, UDPSinkSettings::m_reverseAPIDeviceIndex, UDPSinkSettings::m_reverseAPIPort, UDPSinkSettings::m_rgbColor, m_settings, UDPSinkSettings::m_title, UDPSinkSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by UDPSinkGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettingsImmediate();
     }
     resetContextMenuType();
 }
onWidgetRolled
void UDPSinkGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 607 of file udpsinkgui.cpp.
References BasebandSampleSink::getInputMessageQueue(), m_udpSink, UDPSink::setSpectrum(), and ui.
Referenced by UDPSinkGUI().
 {
     if ((widget == ui->spectrumBox) && (m_udpSink != 0))
     {
         m_udpSink->setSpectrum(m_udpSink->getInputMessageQueue(), rollDown);
     }
 }
resetToDefaults()
void UDPSinkGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 64 of file udpsinkgui.cpp.
References applySettings(), applySettingsImmediate(), displaySettings(), m_settings, and UDPSinkSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettingsImmediate(true);
     applySettings(true);
 }
serialize()
QByteArray UDPSinkGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 72 of file udpsinkgui.cpp.
References m_settings, and UDPSinkSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void UDPSinkGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 53 of file udpsinkgui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     applySettings();
 }
setName()
void UDPSinkGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 43 of file udpsinkgui.cpp.
 {
     setObjectName(name);
 }
setSampleFormat()
void UDPSinkGUI::setSampleFormat (int index) private
Definition at line 335 of file udpsinkgui.cpp.
References UDPSinkSettings::FormatAMBPFMono, UDPSinkSettings::FormatAMMono, UDPSinkSettings::FormatAMNoDCMono, UDPSinkSettings::FormatIQ16, UDPSinkSettings::FormatIQ24, UDPSinkSettings::FormatLSB, UDPSinkSettings::FormatLSBMono, UDPSinkSettings::FormatNFM, UDPSinkSettings::FormatNFMMono, UDPSinkSettings::FormatUSB, UDPSinkSettings::FormatUSBMono, UDPSinkSettings::m_sampleFormat, m_settings, and ui.
Referenced by on_sampleFormat_currentIndexChanged().
 {
     switch(index)
     {
         case 0:
             m_settings.m_sampleFormat = UDPSinkSettings::FormatIQ16;
             ui->fmDeviation->setEnabled(false);
             break;
         case 1:
             m_settings.m_sampleFormat = UDPSinkSettings::FormatIQ24;
             ui->fmDeviation->setEnabled(false);
             break;
         case 2:
             m_settings.m_sampleFormat = UDPSinkSettings::FormatNFM;
             ui->fmDeviation->setEnabled(true);
             break;
         case 3:
             m_settings.m_sampleFormat = UDPSinkSettings::FormatNFMMono;
             ui->fmDeviation->setEnabled(true);
             break;
         case 4:
             m_settings.m_sampleFormat = UDPSinkSettings::FormatLSB;
             ui->fmDeviation->setEnabled(false);
             break;
         case 5:
             m_settings.m_sampleFormat = UDPSinkSettings::FormatUSB;
             ui->fmDeviation->setEnabled(false);
             break;
         case 6:
             m_settings.m_sampleFormat = UDPSinkSettings::FormatLSBMono;
             ui->fmDeviation->setEnabled(false);
             break;
         case 7:
             m_settings.m_sampleFormat = UDPSinkSettings::FormatUSBMono;
             ui->fmDeviation->setEnabled(false);
             break;
         case 8:
             m_settings.m_sampleFormat = UDPSinkSettings::FormatAMMono;
             ui->fmDeviation->setEnabled(false);
             break;
         case 9:
             m_settings.m_sampleFormat = UDPSinkSettings::FormatAMNoDCMono;
             ui->fmDeviation->setEnabled(false);
             break;
         case 10:
             m_settings.m_sampleFormat = UDPSinkSettings::FormatAMBPFMono;
             ui->fmDeviation->setEnabled(false);
             break;
         default:
             m_settings.m_sampleFormat = UDPSinkSettings::FormatIQ16;
             ui->fmDeviation->setEnabled(false);
             break;
     }
 }
setSampleFormatIndex()
void UDPSinkGUI::setSampleFormatIndex (const UDPSinkSettings::SampleFormat & sampleFormat) private
Definition at line 292 of file udpsinkgui.cpp.
References UDPSinkSettings::FormatAMBPFMono, UDPSinkSettings::FormatAMMono, UDPSinkSettings::FormatAMNoDCMono, UDPSinkSettings::FormatIQ16, UDPSinkSettings::FormatIQ24, UDPSinkSettings::FormatLSB, UDPSinkSettings::FormatLSBMono, UDPSinkSettings::FormatNFM, UDPSinkSettings::FormatNFMMono, UDPSinkSettings::FormatUSB, UDPSinkSettings::FormatUSBMono, and ui.
Referenced by displaySettings().
 {
     switch(sampleFormat)
     {
         case UDPSinkSettings::FormatIQ16:
             ui->sampleFormat->setCurrentIndex(0);
             break;
         case UDPSinkSettings::FormatIQ24:
             ui->sampleFormat->setCurrentIndex(1);
             break;
         case UDPSinkSettings::FormatNFM:
             ui->sampleFormat->setCurrentIndex(2);
             break;
         case UDPSinkSettings::FormatNFMMono:
             ui->sampleFormat->setCurrentIndex(3);
             break;
         case UDPSinkSettings::FormatLSB:
             ui->sampleFormat->setCurrentIndex(4);
             break;
         case UDPSinkSettings::FormatUSB:
             ui->sampleFormat->setCurrentIndex(5);
             break;
         case UDPSinkSettings::FormatLSBMono:
             ui->sampleFormat->setCurrentIndex(6);
             break;
         case UDPSinkSettings::FormatUSBMono:
             ui->sampleFormat->setCurrentIndex(7);
             break;
         case UDPSinkSettings::FormatAMMono:
             ui->sampleFormat->setCurrentIndex(8);
             break;
         case UDPSinkSettings::FormatAMNoDCMono:
             ui->sampleFormat->setCurrentIndex(9);
             break;
         case UDPSinkSettings::FormatAMBPFMono:
             ui->sampleFormat->setCurrentIndex(10);
             break;
         default:
             ui->sampleFormat->setCurrentIndex(0);
             break;
     }
 }
tick
void UDPSinkGUI::tick () private slot
Definition at line 133 of file udpsinkgui.cpp.
References MovingAverage< Type >::average(), CalcDb::dbPower(), MovingAverage< Type >::feed(), UDPSink::getInMagSq(), UDPSink::getMagSq(), UDPSink::getSquelchOpen(), m_inPowerAvg, m_tickCount, m_udpSink, and ui.
Referenced by UDPSinkGUI().
 {
     if (m_tickCount % 4 == 0)
     {
 //        m_channelPowerAvg.feed(m_udpSrc->getMagSq());
 //        double powDb = CalcDb::dbPower(m_channelPowerAvg.average());
         double powDb = CalcDb::dbPower(m_udpSink->getMagSq());
         ui->channelPower->setText(QString::number(powDb, 'f', 1));
         m_inPowerAvg.feed(m_udpSink->getInMagSq());
         double inPowDb = CalcDb::dbPower(m_inPowerAvg.average());
         ui->inputPower->setText(QString::number(inPowDb, 'f', 1));
     }
     if (m_udpSink->getSquelchOpen()) {
         ui->squelchLabel->setStyleSheet("QLabel { background-color : green; }");
     } else {
         ui->squelchLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     }
     m_tickCount++;
 }
Member Data Documentation
m_channelMarker
ChannelMarker UDPSinkGUI::m_channelMarker private
Definition at line 69 of file udpsinkgui.h.
Referenced by applySettings(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), on_applyBtn_clicked(), on_deltaFrequency_changed(), onMenuDialogCalled(), setCenterFrequency(), and UDPSinkGUI().
m_channelPowerAvg
MovingAverage<double> UDPSinkGUI::m_channelPowerAvg private
Definition at line 70 of file udpsinkgui.h.
m_deviceUISet
DeviceUISet* UDPSinkGUI::m_deviceUISet private
Definition at line 66 of file udpsinkgui.h.
Referenced by UDPSinkGUI(), and ~UDPSinkGUI().
m_doApplySettings
bool UDPSinkGUI::m_doApplySettings private
Definition at line 75 of file udpsinkgui.h.
Referenced by applySettings(), applySettingsImmediate(), and blockApplySettings().
m_inPowerAvg
MovingAverage<double> UDPSinkGUI::m_inPowerAvg private
Definition at line 71 of file udpsinkgui.h.
Referenced by tick().
m_inputMessageQueue
MessageQueue UDPSinkGUI::m_inputMessageQueue private
Definition at line 77 of file udpsinkgui.h.
m_pluginAPI
PluginAPI* UDPSinkGUI::m_pluginAPI private
Definition at line 65 of file udpsinkgui.h.
m_rfBandwidthChanged
bool UDPSinkGUI::m_rfBandwidthChanged private
Definition at line 76 of file udpsinkgui.h.
Referenced by on_applyBtn_clicked(), and on_rfBandwidth_textEdited().
m_settings
UDPSinkSettings UDPSinkGUI::m_settings private
Definition at line 68 of file udpsinkgui.h.
Referenced by applySettings(), applySettingsImmediate(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), handleMessage(), on_agc_toggled(), on_applyBtn_clicked(), on_audioActive_toggled(), on_audioStereo_toggled(), on_deltaFrequency_changed(), on_fmDeviation_textEdited(), on_gain_valueChanged(), on_inputUDPAudioPort_editingFinished(), on_outputUDPAddress_editingFinished(), on_outputUDPPort_editingFinished(), on_rfBandwidth_textEdited(), on_sampleRate_textEdited(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), serialize(), setSampleFormat(), and UDPSinkGUI().
m_spectrumVis
SpectrumVis* UDPSinkGUI::m_spectrumVis private
Definition at line 80 of file udpsinkgui.h.
Referenced by UDPSinkGUI(), and ~UDPSinkGUI().
m_tickCount
uint32_t UDPSinkGUI::m_tickCount private
Definition at line 72 of file udpsinkgui.h.
Referenced by tick().
m_udpSink
UDPSink* UDPSinkGUI::m_udpSink private
Definition at line 67 of file udpsinkgui.h.
Referenced by applySettings(), applySettingsImmediate(), onWidgetRolled(), tick(), UDPSinkGUI(), and ~UDPSinkGUI().
ui
Ui::UDPSinkGUI* UDPSinkGUI::ui private
Definition at line 64 of file udpsinkgui.h.
Referenced by applySettings(), channelMarkerChangedByCursor(), displaySettings(), on_applyBtn_clicked(), on_fmDeviation_textEdited(), on_gain_valueChanged(), on_inputUDPAudioPort_editingFinished(), on_outputUDPAddress_editingFinished(), on_outputUDPPort_editingFinished(), on_rfBandwidth_textEdited(), on_sampleFormat_currentIndexChanged(), on_sampleRate_textEdited(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_volume_valueChanged(), onWidgetRolled(), setSampleFormat(), setSampleFormatIndex(), tick(), UDPSinkGUI(), and ~UDPSinkGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/udpsink/udpsinkgui.h
plugins/channelrx/udpsink/udpsinkgui.cpp