SDRAngel: fftfilt Class Reference
fftfilt Class Reference
#include <fftfilt.h>
Public Types
typedef std::complex< float > cmplx
Public Member Functions
fftfilt (float f1, float f2, int len)
fftfilt (float f2, int len)
~fftfilt ()
void create_filter (float f1, float f2)
void create_dsb_filter (float f2)
void create_asym_filter (float fopp, float fin)
two different filters for in band and opposite band
void create_rrc_filter (float fb, float a)
root raised cosine. fb is half the band pass
int noFilt (const cmplx &in, cmplx **out)
int runFilt (const cmplx &in, cmplx **out)
int runSSB (const cmplx &in, cmplx **out, bool usb, bool getDC=true)
int runDSB (const cmplx &in, cmplx **out, bool getDC=true)
int runAsym (const cmplx &in, cmplx **out, bool usb)
Asymmetrical fitering can be used for vestigial sideband.
Protected Member Functions
float fsinc (float fc, int i, int len)
float _blackman (int i, int len)
cmplx frrc (float fb, float a, int i, int len)
void init_filter ()
void init_dsb_filter ()
Protected Attributes
int flen
int flen2
g_fft< float > * fft
cmplx * filter
cmplx * filterOpp
cmplx * data
cmplx * ovlbuf
cmplx * output
int inptr
int pass
int window
Private Types
enum { NONE, BLACKMAN, HAMMING, HANNING }
Detailed Description
Definition at line 17 of file fftfilt.h.
Member Typedef Documentation
cmplx
typedef std::complex<float> fftfilt::cmplx
Definition at line 21 of file fftfilt.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
NONE
BLACKMAN
HAMMING
HANNING
Definition at line 18 of file fftfilt.h.
 {NONE, BLACKMAN, HAMMING, HANNING};
Constructor & Destructor Documentation
fftfilt() [1/2]
fftfilt::fftfilt (float f1, float f2, int len)
Definition at line 78 of file fftfilt.cpp.
References create_filter(), flen, init_filter(), pass, and window.
 {
     flen    = len;
     pass    = 0;
     window  = 0;
     init_filter();
     create_filter(f1, f2);
 }
fftfilt() [2/2]
fftfilt::fftfilt (float f2, int len)
Definition at line 87 of file fftfilt.cpp.
References create_dsb_filter(), flen, init_filter(), pass, and window.
 {
     flen    = len;
     pass    = 0;
     window  = 0;
     init_filter();
     create_dsb_filter(f2);
 }
~fftfilt()
fftfilt::~fftfilt ()
Definition at line 96 of file fftfilt.cpp.
References data, fft, filter, filterOpp, output, and ovlbuf.
 {
     if (fft) delete fft;
     if (filter) delete [] filter;
     if (filterOpp) delete [] filterOpp;
     if (data) delete [] data;
     if (output) delete [] output;
     if (ovlbuf) delete [] ovlbuf;
 }
Member Function Documentation
_blackman()
float fftfilt::_blackman (int i, int len) inline protected
Definition at line 59 of file fftfilt.h.
References cos(), and M_PI.
Referenced by create_asym_filter(), create_dsb_filter(), and create_filter().
     {
         return (0.42 -
                  0.50 * cos(2.0 * M_PI * i / len) +
                  0.08 * cos(4.0 * M_PI * i / len));
     }
create_asym_filter()
void fftfilt::create_asym_filter (float fopp, float fin)
two different filters for in band and opposite band
Definition at line 174 of file fftfilt.cpp.
References _blackman(), abs(), g_fft< FFT_TYPE >::ComplexFFT(), fft, filter, filterOpp, flen, flen2, fsinc(), and i.
Referenced by ATVDemod::applySettings(), and ATVMod::applySettings().
 {
     // in band
     // initialize the filter to zero
     memset(filter, 0, flen * sizeof(cmplx));
     for (int i = 0; i < flen2; i++) {
         filter[i] = fsinc(fin, i, flen2);
         filter[i] *= _blackman(i, flen2);
     }
     fft->ComplexFFT(filter); // filter was expressed in the time domain (impulse response)
     // normalize the output filter for unity gain
     float scale = 0, mag;
     for (int i = 0; i < flen2; i++) {
         mag = abs(filter[i]);
         if (mag > scale) scale = mag;
     }
     if (scale != 0) {
         for (int i = 0; i < flen; i++)
             filter[i] /= scale;
     }
     // opposite band
     // initialize the filter to zero
     memset(filterOpp, 0, flen * sizeof(cmplx));
     for (int i = 0; i < flen2; i++) {
         filterOpp[i] = fsinc(fopp, i, flen2);
         filterOpp[i] *= _blackman(i, flen2);
     }
     fft->ComplexFFT(filterOpp); // filter was expressed in the time domain (impulse response)
     // normalize the output filter for unity gain
     scale = 0;
     for (int i = 0; i < flen2; i++) {
         mag = abs(filterOpp[i]);
         if (mag > scale) scale = mag;
     }
     if (scale != 0) {
         for (int i = 0; i < flen; i++)
             filterOpp[i] /= scale;
     }
 }
create_dsb_filter()
void fftfilt::create_dsb_filter (float f2)
Definition at line 148 of file fftfilt.cpp.
References _blackman(), abs(), g_fft< FFT_TYPE >::ComplexFFT(), fft, filter, flen, flen2, fsinc(), and i.
Referenced by AMDemod::applyAudioSampleRate(), SSBDemod::applyAudioSampleRate(), SSBMod::applyAudioSampleRate(), AMDemod::applySettings(), SSBDemod::applySettings(), SSBMod::applySettings(), fftfilt(), and ChannelAnalyzer::setFilters().
 {
     // initialize the filter to zero
     memset(filter, 0, flen * sizeof(cmplx));
     for (int i = 0; i < flen2; i++) {
         filter[i] = fsinc(f2, i, flen2);
         filter[i] *= _blackman(i, flen2);
     }
     fft->ComplexFFT(filter); // filter was expressed in the time domain (impulse response)
     // normalize the output filter for unity gain
     float scale = 0, mag;
     for (int i = 0; i < flen2; i++) {
         mag = abs(filter[i]);
         if (mag > scale) scale = mag;
     }
     if (scale != 0) {
         for (int i = 0; i < flen; i++)
             filter[i] /= scale;
     }
 }
create_filter()
void fftfilt::create_filter (float f1, float f2)
Definition at line 107 of file fftfilt.cpp.
References _blackman(), abs(), g_fft< FFT_TYPE >::ComplexFFT(), fft, filter, flen, flen2, fsinc(), and i.
Referenced by SSBDemod::applyAudioSampleRate(), SSBMod::applyAudioSampleRate(), WFMDemod::applyChannelSettings(), BFMDemod::applyChannelSettings(), WFMMod::applyChannelSettings(), DATVDemod::applyChannelSettings(), ATVMod::applyChannelSettings(), FreeDVMod::applyFreeDVMode(), FreeDVDemod::applyFreeDVMode(), WFMDemod::applySettings(), UDPSource::applySettings(), BFMDemod::applySettings(), WFMMod::applySettings(), SSBDemod::applySettings(), SSBMod::applySettings(), DATVDemod::applySettings(), ATVMod::applySettings(), fftfilt(), and ChannelAnalyzer::setFilters().
 {
     // initialize the filter to zero
     memset(filter, 0, flen * sizeof(cmplx));
     // create the filter shape coefficients by fft
     bool b_lowpass, b_highpass;
     b_lowpass = (f2 != 0);
     b_highpass = (f1 != 0);
     for (int i = 0; i < flen2; i++) {
         filter[i] = 0;
     // lowpass @ f2
         if (b_lowpass)
             filter[i] += fsinc(f2, i, flen2);
     // highighpass @ f1
         if (b_highpass)
             filter[i] -= fsinc(f1, i, flen2);
     }
     // highpass is delta[flen2/2] - h(t)
     if (b_highpass && f2 < f1)
         filter[flen2 / 2] += 1;
     for (int i = 0; i < flen2; i++)
         filter[i] *= _blackman(i, flen2);
     fft->ComplexFFT(filter); // filter was expressed in the time domain (impulse response)
     // normalize the output filter for unity gain
     float scale = 0, mag;
     for (int i = 0; i < flen2; i++) {
         mag = abs(filter[i]);
         if (mag > scale) scale = mag;
     }
     if (scale != 0) {
         for (int i = 0; i < flen; i++)
             filter[i] /= scale;
     }
 }
create_rrc_filter()
void fftfilt::create_rrc_filter (float fb, float a)
root raised cosine. fb is half the band pass
Definition at line 222 of file fftfilt.cpp.
References abs(), filter, flen, frrc(), and i.
Referenced by ChannelAnalyzer::applySettings(), ChannelAnalyzer::setFilters(), and FreqTracker::setInterpolator().
 {
     std::fill(filter, filter+flen, 0);
     for (int i = 0; i < flen; i++) {
         filter[i] = frrc(fb, a, i, flen);
     }
     // normalize the output filter for unity gain
     float scale = 0, mag;
     for (int i = 0; i < flen; i++)
     {
         mag = abs(filter[i]);
         if (mag > scale) {
             scale = mag;
         }
     }
     if (scale != 0)
     {
         for (int i = 0; i < flen; i++) {
             filter[i] /= scale;
         }
     }
 }
frrc()
cmplx fftfilt::frrc (float fb, float a, int i, int len) inline protected
RRC function in the frequency domain. Zero frequency is on the sides with first half in positive frequencies and second half in negative frequencies
Definition at line 68 of file fftfilt.h.
References cos(), and M_PI.
Referenced by create_rrc_filter().
     {
         float x = i/(float)len; // normalize to [0..1]
         x = 0.5-fabs(x-0.5); // apply symmetry: now both halves overlap near 0
         float tr = fb*a; // half the transition zone
         if (x < fb-tr)
         {
             return 1.0; // in band
         }
         else if (x < fb+tr) // transition
         {
             float y = ((x-(fb-tr)) / (2.0*tr))*M_PI;
             return (cos(y) + 1.0f)/2.0f;
         }
         else
         {
             return 0.0; // out of band
         }
     }
fsinc()
float fftfilt::fsinc (float fc, int i, int len) inline protected
Definition at line 52 of file fftfilt.h.
References M_PI, and sin().
Referenced by create_asym_filter(), create_dsb_filter(), and create_filter().
     {
         int len2 = len/2;
         return (i == len2) ? 2.0 * fc:
                 sin(2 * M_PI * fc * (i - len2)) / (M_PI * (i - len2));
     }
init_dsb_filter()
void fftfilt::init_dsb_filter () protected
init_filter()
void fftfilt::init_filter () protected
Definition at line 51 of file fftfilt.cpp.
References data, fft, filter, filterOpp, flen, flen2, inptr, output, and ovlbuf.
Referenced by fftfilt().
 {
     flen2   = flen >> 1;
     fft = new g_fft<float>(flen);
     filter      = new cmplx[flen];
     filterOpp   = new cmplx[flen];
     data        = new cmplx[flen];
     output      = new cmplx[flen2];
     ovlbuf      = new cmplx[flen2];
     memset(filter, 0, flen * sizeof(cmplx));
     memset(filterOpp, 0, flen * sizeof(cmplx));
     memset(data, 0, flen * sizeof(cmplx));
     memset(output, 0, flen2 * sizeof(cmplx));
     memset(ovlbuf, 0, flen2 * sizeof(cmplx));
     inptr = 0;
 }
noFilt()
int fftfilt::noFilt (const cmplx & in, cmplx ** out)
Definition at line 248 of file fftfilt.cpp.
References data, flen2, and inptr.
 {
     data[inptr++] = in;
     if (inptr < flen2)
         return 0;
     inptr = 0;
     *out = data;
     return flen2;
 }
runAsym()
int fftfilt::runAsym (const cmplx & in, cmplx ** out, bool usb)
Asymmetrical fitering can be used for vestigial sideband.
Definition at line 360 of file fftfilt.cpp.
References g_fft< FFT_TYPE >::ComplexFFT(), data, fft, filter, filterOpp, flen, flen2, i, inptr, g_fft< FFT_TYPE >::InverseComplexFFT(), output, and ovlbuf.
Referenced by ATVDemod::demod(), and ATVMod::modulateVestigialSSB().
 {
     data[inptr++] = in;
     if (inptr < flen2)
         return 0;
     inptr = 0;
     fft->ComplexFFT(data);
     data[0] *= filter[0]; // always keep DC
     if (usb)
     {
         for (int i = 1; i < flen2; i++)
         {
             data[i] *= filter[i]; // usb
             data[flen2 + i] *= filterOpp[flen2 + i]; // lsb is the opposite
         }
     }
     else
     {
         for (int i = 1; i < flen2; i++)
         {
             data[i] *= filterOpp[i]; // usb is the opposite
             data[flen2 + i] *= filter[flen2 + i]; // lsb
         }
     }
     // in-place FFT: freqdata overwritten with filtered timedata
     fft->InverseComplexFFT(data);
     // overlap and add
     for (int i = 0; i < flen2; i++) {
         output[i] = ovlbuf[i] + data[i];
         ovlbuf[i] = data[i+flen2];
     }
     memset (data, 0, flen * sizeof(cmplx));
     *out = output;
     return flen2;
 }
runDSB()
int fftfilt::runDSB (const cmplx & in, cmplx ** out, bool getDC = true)
Definition at line 327 of file fftfilt.cpp.
References g_fft< FFT_TYPE >::ComplexFFT(), data, fft, filter, flen, flen2, i, inptr, g_fft< FFT_TYPE >::InverseComplexFFT(), output, and ovlbuf.
Referenced by ChannelAnalyzer::processOneSample(), AMDemod::processOneSample(), SSBDemod::processOneSample(), and SSBMod::pullAF().
 {
     data[inptr++] = in;
     if (inptr < flen2)
         return 0;
     inptr = 0;
     fft->ComplexFFT(data);
     for (int i = 0; i < flen2; i++) {
         data[i] *= filter[i];
         data[flen2 + i] *= filter[flen2 + i];
     }
     // get or reject DC component
     data[0] = getDC ? data[0] : 0;
     // in-place FFT: freqdata overwritten with filtered timedata
     fft->InverseComplexFFT(data);
     // overlap and add
     for (int i = 0; i < flen2; i++) {
         output[i] = ovlbuf[i] + data[i];
         ovlbuf[i] = data[i+flen2];
     }
     memset (data, 0, flen * sizeof(cmplx));
     *out = output;
     return flen2;
 }
runFilt()
int fftfilt::runFilt (const cmplx & in, cmplx ** out)
Definition at line 260 of file fftfilt.cpp.
References g_fft< FFT_TYPE >::ComplexFFT(), data, fft, filter, flen, flen2, i, inptr, g_fft< FFT_TYPE >::InverseComplexFFT(), output, and ovlbuf.
Referenced by WFMDemod::feed(), BFMDemod::feed(), DATVDemod::feed(), ChannelAnalyzer::processOneSample(), FreqTracker::processOneSample(), and WFMMod::pull().
 {
     data[inptr++] = in;
     if (inptr < flen2)
         return 0;
     inptr = 0;
     fft->ComplexFFT(data);
     for (int i = 0; i < flen; i++)
         data[i] *= filter[i];
     fft->InverseComplexFFT(data);
     for (int i = 0; i < flen2; i++) {
         output[i] = ovlbuf[i] + data[i];
         ovlbuf[i] = data[flen2 + i];
     }
     memset (data, 0, flen * sizeof(cmplx));
     *out = output;
     return flen2;
 }
runSSB()
int fftfilt::runSSB (const cmplx & in, cmplx ** out, bool usb, bool getDC = true)
Definition at line 284 of file fftfilt.cpp.
References g_fft< FFT_TYPE >::ComplexFFT(), data, fft, filter, flen, flen2, i, inptr, g_fft< FFT_TYPE >::InverseComplexFFT(), output, and ovlbuf.
Referenced by UDPSink::feed(), UDPSource::modulateSample(), ATVMod::modulateSSB(), ChannelAnalyzer::processOneSample(), AMDemod::processOneSample(), SSBDemod::processOneSample(), FreeDVDemod::processOneSample(), FreeDVMod::pullAF(), and SSBMod::pullAF().
 {
     data[inptr++] = in;
     if (inptr < flen2)
         return 0;
     inptr = 0;
     fft->ComplexFFT(data);
     // get or reject DC component
     data[0] = getDC ? data[0]*filter[0] : 0;
     // Discard frequencies for ssb
     if (usb)
     {
         for (int i = 1; i < flen2; i++) {
             data[i] *= filter[i];
             data[flen2 + i] = 0;
         }
     }
     else
     {
         for (int i = 1; i < flen2; i++) {
             data[i] = 0;
             data[flen2 + i] *= filter[flen2 + i];
         }
     }
     // in-place FFT: freqdata overwritten with filtered timedata
     fft->InverseComplexFFT(data);
     // overlap and add
     for (int i = 0; i < flen2; i++) {
         output[i] = ovlbuf[i] + data[i];
         ovlbuf[i] = data[i+flen2];
     }
     memset (data, 0, flen * sizeof(cmplx));
     *out = output;
     return flen2;
 }
Member Data Documentation
data
cmplx* fftfilt::data protected
Definition at line 45 of file fftfilt.h.
Referenced by init_filter(), noFilt(), runAsym(), runDSB(), runFilt(), runSSB(), and ~fftfilt().
fft
g_fft<float>* fftfilt::fft protected
Definition at line 42 of file fftfilt.h.
Referenced by create_asym_filter(), create_dsb_filter(), create_filter(), init_filter(), runAsym(), runDSB(), runFilt(), runSSB(), and ~fftfilt().
filter
cmplx* fftfilt::filter protected
Definition at line 43 of file fftfilt.h.
Referenced by create_asym_filter(), create_dsb_filter(), create_filter(), create_rrc_filter(), init_filter(), runAsym(), runDSB(), runFilt(), runSSB(), and ~fftfilt().
filterOpp
cmplx* fftfilt::filterOpp protected
Definition at line 44 of file fftfilt.h.
Referenced by create_asym_filter(), init_filter(), runAsym(), and ~fftfilt().
flen
int fftfilt::flen protected
Definition at line 40 of file fftfilt.h.
Referenced by create_asym_filter(), create_dsb_filter(), create_filter(), create_rrc_filter(), fftfilt(), init_filter(), runAsym(), runDSB(), runFilt(), and runSSB().
flen2
int fftfilt::flen2 protected
Definition at line 41 of file fftfilt.h.
Referenced by create_asym_filter(), create_dsb_filter(), create_filter(), init_filter(), noFilt(), runAsym(), runDSB(), runFilt(), and runSSB().
inptr
int fftfilt::inptr protected
Definition at line 48 of file fftfilt.h.
Referenced by init_filter(), noFilt(), runAsym(), runDSB(), runFilt(), and runSSB().
output
cmplx* fftfilt::output protected
Definition at line 47 of file fftfilt.h.
Referenced by init_filter(), runAsym(), runDSB(), runFilt(), runSSB(), and ~fftfilt().
ovlbuf
cmplx* fftfilt::ovlbuf protected
Definition at line 46 of file fftfilt.h.
Referenced by init_filter(), runAsym(), runDSB(), runFilt(), runSSB(), and ~fftfilt().
pass
int fftfilt::pass protected
Definition at line 49 of file fftfilt.h.
Referenced by fftfilt().
window
int fftfilt::window protected
Definition at line 50 of file fftfilt.h.
Referenced by fftfilt().
The documentation for this class was generated from the following files:
sdrbase/dsp/fftfilt.h
sdrbase/dsp/fftfilt.cpp