SDRAngel: RemoteSinkThread Class Reference
RemoteSinkThread Class Reference
#include <remotesinkthread.h>
Inherits QThread.
Classes
class MsgStartStop
Public Slots
void processDataBlock (RemoteDataBlock *dataBlock)
Public Member Functions
RemoteSinkThread (QObject *parent=0)
~RemoteSinkThread ()
void startStop (bool start)
Private Slots
void handleInputMessages ()
Private Member Functions
void startWork ()
void stopWork ()
void run ()
void handleDataBlock (RemoteDataBlock &dataBlock)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
volatile bool m_running
CM256 m_cm256
CM256 * m_cm256p
QHostAddress m_address
QUdpSocket * m_socket
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 41 of file remotesinkthread.h.
Constructor & Destructor Documentation
RemoteSinkThread()
RemoteSinkThread::RemoteSinkThread (QObject * parent = 0)
Definition at line 33 of file remotesinkthread.cpp.
Referenced by RemoteSinkThread::MsgStartStop::MsgStartStop().
                                                   :
     QThread(parent),
     m_running(false),
     m_address(QHostAddress::LocalHost),
     m_socket(0)
 {
     m_cm256p = m_cm256.isInitialized() ? &m_cm256 : 0;
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
 }
~RemoteSinkThread()
RemoteSinkThread::~RemoteSinkThread ()
Definition at line 44 of file remotesinkthread.cpp.
Referenced by RemoteSinkThread::MsgStartStop::MsgStartStop().
 {
     qDebug("RemoteSinkThread::~RemoteSinkThread");
 }
Member Function Documentation
handleDataBlock()
void RemoteSinkThread::handleDataBlock (RemoteDataBlock & dataBlock) private
< Main interface with CM256 encoder
< Pointers to data for CM256 encoder
< FEC data
Definition at line 96 of file remotesinkthread.cpp.
References i, m_address, m_cm256p, RemoteTxControlBlock::m_dataAddress, RemoteTxControlBlock::m_dataPort, RemoteTxControlBlock::m_frameIndex, RemoteTxControlBlock::m_nbBlocksFEC, m_socket, RemoteDataBlock::m_superBlocks, RemoteDataBlock::m_txControlBlock, and RemoteTxControlBlock::m_txDelay.
Referenced by processDataBlock().
 {
     CM256::cm256_encoder_params cm256Params;
     CM256::cm256_block descriptorBlocks[256];
     RemoteProtectedBlock fecBlocks[256];
     uint16_t frameIndex = dataBlock.m_txControlBlock.m_frameIndex;
     int nbBlocksFEC = dataBlock.m_txControlBlock.m_nbBlocksFEC;
     int txDelay = dataBlock.m_txControlBlock.m_txDelay;
     m_address.setAddress(dataBlock.m_txControlBlock.m_dataAddress);
     uint16_t dataPort = dataBlock.m_txControlBlock.m_dataPort;
     RemoteSuperBlock *txBlockx = dataBlock.m_superBlocks;
     if ((nbBlocksFEC == 0) || !m_cm256p) // Do not FEC encode
     {
         if (m_socket)
         {
             for (int i = 0; i < RemoteNbOrginalBlocks; i++)
             {
                 // send block via UDP
                 m_socket->writeDatagram((const char*)&txBlockx[i], (qint64 ) RemoteUdpSize, m_address, dataPort);
                 usleep(txDelay);
             }
         }
     }
     else
     {
         cm256Params.BlockBytes = sizeof(RemoteProtectedBlock);
         cm256Params.OriginalCount = RemoteNbOrginalBlocks;
         cm256Params.RecoveryCount = nbBlocksFEC;
         // Fill pointers to data
         for (int i = 0; i < cm256Params.OriginalCount + cm256Params.RecoveryCount; ++i)
         {
             if (i >= cm256Params.OriginalCount) {
                 memset((void *) &txBlockx[i].m_protectedBlock, 0, sizeof(RemoteProtectedBlock));
             }
             txBlockx[i].m_header.m_frameIndex = frameIndex;
             txBlockx[i].m_header.m_blockIndex = i;
             txBlockx[i].m_header.m_sampleBytes = (SDR_RX_SAMP_SZ <= 16 ? 2 : 4);
             txBlockx[i].m_header.m_sampleBits = SDR_RX_SAMP_SZ;
             descriptorBlocks[i].Block = (void *) &(txBlockx[i].m_protectedBlock);
             descriptorBlocks[i].Index = txBlockx[i].m_header.m_blockIndex;
         }
         // Encode FEC blocks
         if (m_cm256p->cm256_encode(cm256Params, descriptorBlocks, fecBlocks))
         {
             qWarning("RemoteSinkThread::handleDataBlock: CM256 encode failed. No transmission.");
             // TODO: send without FEC changing meta data to set indication of no FEC
         }
         // Merge FEC with data to transmit
         for (int i = 0; i < cm256Params.RecoveryCount; i++)
         {
             txBlockx[i + cm256Params.OriginalCount].m_protectedBlock = fecBlocks[i];
         }
         // Transmit all blocks
         if (m_socket)
         {
             for (int i = 0; i < cm256Params.OriginalCount + cm256Params.RecoveryCount; i++)
             {
                 // send block via UDP
                 m_socket->writeDatagram((const char*)&txBlockx[i], (qint64 ) RemoteUdpSize, m_address, dataPort);
                 usleep(txDelay);
             }
         }
     }
     dataBlock.m_txControlBlock.m_processed = true;
 }
handleInputMessages
void RemoteSinkThread::handleInputMessages () private slot
Definition at line 170 of file remotesinkthread.cpp.
References RemoteSinkThread::MsgStartStop::getStartStop(), m_inputMessageQueue, Message::match(), MessageQueue::pop(), startWork(), and stopWork().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (MsgStartStop::match(*message))
         {
             MsgStartStop* notif = (MsgStartStop*) message;
             qDebug("RemoteSinkThread::handleInputMessages: MsgStartStop: %s", notif->getStartStop() ? "start" : "stop");
             if (notif->getStartStop()) {
                 startWork();
             } else {
                 stopWork();
             }
             delete message;
         }
     }
 }
processDataBlock
void RemoteSinkThread::processDataBlock (RemoteDataBlock * dataBlock) slot
Definition at line 90 of file remotesinkthread.cpp.
References handleDataBlock().
Referenced by RemoteSinkThread::MsgStartStop::MsgStartStop().
 {
     handleDataBlock(*dataBlock);
     delete dataBlock;
 }
run()
void RemoteSinkThread::run () private
Definition at line 75 of file remotesinkthread.cpp.
References m_running, and m_startWaiter.
 {
     qDebug("RemoteSinkThread::run: begin");
     m_running = true;
     m_startWaiter.wakeAll();
     while (m_running)
     {
         sleep(1); // Do nothing as everything is in the data handler (dequeuer)
     }
     m_running = false;
     qDebug("RemoteSinkThread::run: end");
 }
startStop()
void RemoteSinkThread::startStop (bool start)
Definition at line 49 of file remotesinkthread.cpp.
References RemoteSinkThread::MsgStartStop::create(), m_inputMessageQueue, and MessageQueue::push().
Referenced by RemoteSinkThread::MsgStartStop::MsgStartStop(), RemoteSink::start(), and RemoteSink::stop().
 {
     MsgStartStop *msg = MsgStartStop::create(start);
     m_inputMessageQueue.push(msg);
 }
startWork()
void RemoteSinkThread::startWork () private
Definition at line 55 of file remotesinkthread.cpp.
References m_running, m_socket, m_startWaiter, and m_startWaitMutex.
Referenced by handleInputMessages().
 {
     qDebug("RemoteSinkThread::startWork");
     m_startWaitMutex.lock();
     m_socket = new QUdpSocket(this);
     start();
     while(!m_running)
         m_startWaiter.wait(&m_startWaitMutex, 100);
     m_startWaitMutex.unlock();
 }
stopWork()
void RemoteSinkThread::stopWork () private
Definition at line 66 of file remotesinkthread.cpp.
References m_running, and m_socket.
Referenced by handleInputMessages().
 {
     qDebug("RemoteSinkThread::stopWork");
     delete m_socket;
     m_socket = 0;
     m_running = false;
     wait();
 }
Member Data Documentation
m_address
QHostAddress RemoteSinkThread::m_address private
Definition at line 80 of file remotesinkthread.h.
Referenced by handleDataBlock().
m_cm256
CM256 RemoteSinkThread::m_cm256 private
Definition at line 77 of file remotesinkthread.h.
m_cm256p
CM256* RemoteSinkThread::m_cm256p private
Definition at line 78 of file remotesinkthread.h.
Referenced by handleDataBlock().
m_inputMessageQueue
MessageQueue RemoteSinkThread::m_inputMessageQueue private
Definition at line 83 of file remotesinkthread.h.
Referenced by handleInputMessages(), and startStop().
m_running
volatile bool RemoteSinkThread::m_running private
Definition at line 75 of file remotesinkthread.h.
Referenced by run(), startWork(), and stopWork().
m_socket
QUdpSocket* RemoteSinkThread::m_socket private
Definition at line 81 of file remotesinkthread.h.
Referenced by handleDataBlock(), startWork(), and stopWork().
m_startWaiter
QWaitCondition RemoteSinkThread::m_startWaiter private
Definition at line 74 of file remotesinkthread.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex RemoteSinkThread::m_startWaitMutex private
Definition at line 73 of file remotesinkthread.h.
Referenced by startWork().
The documentation for this class was generated from the following files:
plugins/channelrx/remotesink/remotesinkthread.h
plugins/channelrx/remotesink/remotesinkthread.cpp