SDRAngel: DSPMIMOSignalNotification Class Reference
DSPMIMOSignalNotification Class Reference
#include <dspcommands.h>
Public Member Functions
DSPMIMOSignalNotification (int samplerate, qint64 centerFrequency, bool sourceOrSink, unsigned int index)
int getSampleRate () const
qint64 getCenterFrequency () const
bool getSourceOrSink () const
unsigned int getIndex () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Private Attributes
int m_sampleRate
qint64 m_centerFrequency
bool m_sourceOrSink
unsigned int m_index
Additional Inherited Members
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 336 of file dspcommands.h.
Constructor & Destructor Documentation
DSPMIMOSignalNotification()
DSPMIMOSignalNotification::DSPMIMOSignalNotification (int samplerate, qint64 centerFrequency, bool sourceOrSink, unsigned int index) inline
Definition at line 339 of file dspcommands.h.
                                                                                                              :
         Message(),
         m_sampleRate(samplerate),
         m_centerFrequency(centerFrequency),
         m_sourceOrSink(sourceOrSink),
         m_index(index)
     { }
Member Function Documentation
getCenterFrequency()
qint64 DSPMIMOSignalNotification::getCenterFrequency () const inline
Definition at line 347 of file dspcommands.h.
Referenced by TestMIGui::handleInputMessages(), and DSPDeviceMIMOEngine::handleInputMessages().
 { return m_centerFrequency; }
getIndex()
unsigned int DSPMIMOSignalNotification::getIndex () const inline
Definition at line 349 of file dspcommands.h.
Referenced by TestMIGui::handleInputMessages(), and DSPDeviceMIMOEngine::handleInputMessages().
 { return m_index; }
getSampleRate()
int DSPMIMOSignalNotification::getSampleRate () const inline
Definition at line 346 of file dspcommands.h.
Referenced by TestMIGui::handleInputMessages(), and DSPDeviceMIMOEngine::handleInputMessages().
 { return m_sampleRate; }
getSourceOrSink()
bool DSPMIMOSignalNotification::getSourceOrSink () const inline
Definition at line 348 of file dspcommands.h.
Referenced by TestMIGui::handleInputMessages(), and DSPDeviceMIMOEngine::handleInputMessages().
 { return m_sourceOrSink; }
Member Data Documentation
m_centerFrequency
qint64 DSPMIMOSignalNotification::m_centerFrequency private
Definition at line 352 of file dspcommands.h.
m_index
unsigned int DSPMIMOSignalNotification::m_index private
Definition at line 354 of file dspcommands.h.
m_sampleRate
int DSPMIMOSignalNotification::m_sampleRate private
Definition at line 351 of file dspcommands.h.
m_sourceOrSink
bool DSPMIMOSignalNotification::m_sourceOrSink private
Definition at line 353 of file dspcommands.h.
The documentation for this class was generated from the following file:
sdrbase/dsp/dspcommands.h