SDRAngel: LocalOutputGui Class Reference
LocalOutputGui Class Reference
#include <localoutputgui.h>
Public Member Functions
LocalOutputGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~LocalOutputGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_startStop_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void sendSettings ()
void updateSampleRateAndFrequency ()
Private Attributes
Ui::LocalOutputGui * ui
DeviceUISet * m_deviceUISet
LocalOutputSettings m_settings
current settings
LocalOutput * m_sampleSink
bool m_acquisition
int m_streamSampleRate
Sample rate of received stream.
quint64 m_streamCenterFrequency
Center frequency of received stream.
QTimer m_updateTimer
QTimer m_statusTimer
int m_lastEngineState
MessageQueue m_inputMessageQueue
int m_samplesCount
std::size_t m_tickCount
bool m_doApplySettings
bool m_forceSettings
QPalette m_paletteGreenText
QPalette m_paletteWhiteText
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Detailed Description
Definition at line 39 of file localoutputgui.h.
Constructor & Destructor Documentation
LocalOutputGui()
LocalOutputGui::LocalOutputGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 47 of file localoutputgui.cpp.
References displaySettings(), DeviceAPI::getSampleSink(), ColorMapper::GrayGold, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_forceSettings, m_inputMessageQueue, m_networkManager, m_paletteGreenText, m_paletteWhiteText, m_sampleSink, m_statusTimer, m_updateTimer, openDeviceSettingsDialog(), sendSettings(), LocalOutput::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                                         :
     QWidget(parent),
     ui(new Ui::LocalOutputGui),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_sampleSink(0),
     m_acquisition(false),
     m_streamSampleRate(0),
     m_streamCenterFrequency(0),
     m_lastEngineState(DeviceAPI::StNotStarted),
     m_samplesCount(0),
     m_tickCount(0),
     m_doApplySettings(true),
     m_forceSettings(true)
 {
     m_paletteGreenText.setColor(QPalette::WindowText, Qt::green);
     m_paletteWhiteText.setColor(QPalette::WindowText, Qt::white);
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, 0, 9999999U);
     ui->centerFrequencyHz->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequencyHz->setValueRange(3, 0, 999U);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     m_sampleSink = (LocalOutput*) m_deviceUISet->m_deviceAPI->getSampleSink();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSink->setMessageQueueToGUI(&m_inputMessageQueue);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     m_forceSettings = true;
     sendSettings();
 }
~LocalOutputGui()
LocalOutputGui::~LocalOutputGui () virtual
Definition at line 94 of file localoutputgui.cpp.
References m_networkManager, and ui.
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void LocalOutputGui::blockApplySettings (bool block) private
Definition at line 101 of file localoutputgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), handleMessage(), and updateSampleRateAndFrequency().
 {
     m_doApplySettings = !block;
 }
deserialize()
bool LocalOutputGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 134 of file localoutputgui.cpp.
References LocalOutputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, and sendSettings().
 {
     qDebug("LocalOutputGui::deserialize");
     if (m_settings.deserialize(data))
     {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     }
     else
     {
         return false;
     }
 }
destroy()
void LocalOutputGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 106 of file localoutputgui.cpp.
 {
     delete this;
 }
displaySettings()
void LocalOutputGui::displaySettings () private
Definition at line 244 of file localoutputgui.cpp.
References arg(), blockApplySettings(), m_streamCenterFrequency, m_streamSampleRate, and ui.
Referenced by deserialize(), handleMessage(), LocalOutputGui(), and resetToDefaults().
 {
     blockApplySettings(true);
     ui->centerFrequency->setValue(m_streamCenterFrequency / 1000);
     ui->centerFrequencyHz->setValue(m_streamCenterFrequency % 1000);
     ui->deviceRateText->setText(tr("%1k").arg(m_streamSampleRate / 1000.0));
     blockApplySettings(false);
 }
getCenterFrequency()
qint64 LocalOutputGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 152 of file localoutputgui.cpp.
References m_streamCenterFrequency.
 {
     return m_streamCenterFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* LocalOutputGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 55 of file localoutputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString LocalOutputGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 116 of file localoutputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void LocalOutputGui::handleInputMessages () private slot
Definition at line 197 of file localoutputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), DeviceSampleSink::getInputMessageQueue(), DSPSignalNotification::getSampleRate(), handleMessage(), m_inputMessageQueue, m_sampleSink, m_streamCenterFrequency, m_streamSampleRate, Message::match(), MessageQueue::pop(), MessageQueue::push(), and updateSampleRateAndFrequency().
Referenced by LocalOutputGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         //qDebug("LocalOutputGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             if (notif->getSampleRate() != m_streamSampleRate) {
                 m_streamSampleRate = notif->getSampleRate();
             }
             m_streamCenterFrequency = notif->getCenterFrequency();
             qDebug("LocalOutputGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             DSPSignalNotification *fwd = new DSPSignalNotification(*notif);
             m_sampleSink->getInputMessageQueue()->push(fwd);
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool LocalOutputGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 162 of file localoutputgui.cpp.
References blockApplySettings(), displaySettings(), LocalOutput::MsgReportSampleRateAndFrequency::getCenterFrequency(), LocalOutput::MsgReportSampleRateAndFrequency::getSampleRate(), LocalOutput::MsgConfigureLocalOutput::getSettings(), LocalOutput::MsgStartStop::getStartStop(), m_settings, m_streamCenterFrequency, m_streamSampleRate, Message::match(), ui, and updateSampleRateAndFrequency().
Referenced by handleInputMessages().
 {
     if (LocalOutput::MsgConfigureLocalOutput::match(message))
     {
         const LocalOutput::MsgConfigureLocalOutput& cfg = (LocalOutput::MsgConfigureLocalOutput&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (LocalOutput::MsgStartStop::match(message))
     {
         LocalOutput::MsgStartStop& notif = (LocalOutput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else if (LocalOutput::MsgReportSampleRateAndFrequency::match(message))
     {
         LocalOutput::MsgReportSampleRateAndFrequency& notif = (LocalOutput::MsgReportSampleRateAndFrequency&) message;
         m_streamSampleRate = notif.getSampleRate();
         m_streamCenterFrequency = notif.getCenterFrequency();
         updateSampleRateAndFrequency();
         return true;
     }
     else
     {
         return false;
     }
 }
on_startStop_toggled
void LocalOutputGui::on_startStop_toggled (bool checked) private slot
Definition at line 261 of file localoutputgui.cpp.
References LocalOutput::MsgStartStop::create(), DeviceSampleSink::getInputMessageQueue(), m_doApplySettings, m_sampleSink, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         LocalOutput::MsgStartStop *message = LocalOutput::MsgStartStop::create(checked);
         m_sampleSink->getInputMessageQueue()->push(message);
     }
 }
openDeviceSettingsDialog
void LocalOutputGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 312 of file localoutputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), LocalOutputSettings::m_reverseAPIAddress, LocalOutputSettings::m_reverseAPIDeviceIndex, LocalOutputSettings::m_reverseAPIPort, m_settings, LocalOutputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by LocalOutputGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void LocalOutputGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 121 of file localoutputgui.cpp.
References displaySettings(), m_forceSettings, m_settings, LocalOutputSettings::resetToDefaults(), and sendSettings().
 {
     m_settings.resetToDefaults();
     displaySettings();
     m_forceSettings = true;
     sendSettings();
 }
sendSettings()
void LocalOutputGui::sendSettings () private
Definition at line 255 of file localoutputgui.cpp.
References m_updateTimer.
Referenced by deserialize(), LocalOutputGui(), openDeviceSettingsDialog(), and resetToDefaults().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray LocalOutputGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 129 of file localoutputgui.cpp.
References m_settings, and LocalOutputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void LocalOutputGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 157 of file localoutputgui.cpp.
 {
     (void) centerFrequency;
 }
setName()
void LocalOutputGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 111 of file localoutputgui.cpp.
 {
     setObjectName(name);
 }
updateHardware
void LocalOutputGui::updateHardware () private slot
Definition at line 270 of file localoutputgui.cpp.
References LocalOutput::MsgConfigureLocalOutput::create(), DeviceSampleSink::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSink, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by LocalOutputGui().
 {
     if (m_doApplySettings)
     {
         qDebug() << "LocalOutputGui::updateHardware";
         LocalOutput::MsgConfigureLocalOutput* message =
                 LocalOutput::MsgConfigureLocalOutput::create(m_settings, m_forceSettings);
         m_sampleSink->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void LocalOutputGui::updateSampleRateAndFrequency () private
Definition at line 233 of file localoutputgui.cpp.
References arg(), blockApplySettings(), DeviceUISet::getSpectrum(), m_deviceUISet, m_streamCenterFrequency, m_streamSampleRate, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages(), and handleMessage().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_streamSampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_streamCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg((float)m_streamSampleRate / 1000));
     blockApplySettings(true);
     ui->centerFrequency->setValue(m_streamCenterFrequency / 1000);
     ui->centerFrequencyHz->setValue(m_streamCenterFrequency % 1000);
     blockApplySettings(false);
 }
updateStatus
void LocalOutputGui::updateStatus () private slot
Definition at line 283 of file localoutputgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by LocalOutputGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_acquisition
bool LocalOutputGui::m_acquisition private
Definition at line 64 of file localoutputgui.h.
m_deviceUISet
DeviceUISet* LocalOutputGui::m_deviceUISet private
Definition at line 61 of file localoutputgui.h.
Referenced by LocalOutputGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool LocalOutputGui::m_doApplySettings private
Definition at line 75 of file localoutputgui.h.
Referenced by blockApplySettings(), on_startStop_toggled(), and updateHardware().
m_forceSettings
bool LocalOutputGui::m_forceSettings private
Definition at line 76 of file localoutputgui.h.
Referenced by deserialize(), LocalOutputGui(), resetToDefaults(), and updateHardware().
m_inputMessageQueue
MessageQueue LocalOutputGui::m_inputMessageQueue private
Definition at line 70 of file localoutputgui.h.
Referenced by handleInputMessages(), and LocalOutputGui().
m_lastEngineState
int LocalOutputGui::m_lastEngineState private
Definition at line 69 of file localoutputgui.h.
Referenced by updateStatus().
m_networkManager
QNetworkAccessManager* LocalOutputGui::m_networkManager private
Definition at line 81 of file localoutputgui.h.
Referenced by LocalOutputGui(), and ~LocalOutputGui().
m_networkRequest
QNetworkRequest LocalOutputGui::m_networkRequest private
Definition at line 82 of file localoutputgui.h.
m_paletteGreenText
QPalette LocalOutputGui::m_paletteGreenText private
Definition at line 78 of file localoutputgui.h.
Referenced by LocalOutputGui().
m_paletteWhiteText
QPalette LocalOutputGui::m_paletteWhiteText private
Definition at line 79 of file localoutputgui.h.
Referenced by LocalOutputGui().
m_samplesCount
int LocalOutputGui::m_samplesCount private
Definition at line 72 of file localoutputgui.h.
m_sampleSink
LocalOutput* LocalOutputGui::m_sampleSink private
Definition at line 63 of file localoutputgui.h.
Referenced by handleInputMessages(), LocalOutputGui(), on_startStop_toggled(), and updateHardware().
m_settings
LocalOutputSettings LocalOutputGui::m_settings private
current settings
Definition at line 62 of file localoutputgui.h.
Referenced by deserialize(), handleMessage(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), and updateHardware().
m_statusTimer
QTimer LocalOutputGui::m_statusTimer private
Definition at line 68 of file localoutputgui.h.
Referenced by LocalOutputGui().
m_streamCenterFrequency
quint64 LocalOutputGui::m_streamCenterFrequency private
Center frequency of received stream.
Definition at line 66 of file localoutputgui.h.
Referenced by displaySettings(), getCenterFrequency(), handleInputMessages(), handleMessage(), and updateSampleRateAndFrequency().
m_streamSampleRate
int LocalOutputGui::m_streamSampleRate private
Sample rate of received stream.
Definition at line 65 of file localoutputgui.h.
Referenced by displaySettings(), handleInputMessages(), handleMessage(), and updateSampleRateAndFrequency().
m_tickCount
std::size_t LocalOutputGui::m_tickCount private
Definition at line 73 of file localoutputgui.h.
m_updateTimer
QTimer LocalOutputGui::m_updateTimer private
Definition at line 67 of file localoutputgui.h.
Referenced by LocalOutputGui(), sendSettings(), and updateHardware().
ui
Ui::LocalOutputGui* LocalOutputGui::ui private
Definition at line 59 of file localoutputgui.h.
Referenced by displaySettings(), handleMessage(), LocalOutputGui(), updateSampleRateAndFrequency(), updateStatus(), and ~LocalOutputGui().
The documentation for this class was generated from the following files:
plugins/samplesink/localoutput/localoutputgui.h
plugins/samplesink/localoutput/localoutputgui.cpp