SDRAngel: ATVModPlugin Class Reference
ATVModPlugin Class Reference
#include <atvmodplugin.h>
Public Member Functions
ATVModPlugin (QObject *parent=0)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
Private Attributes
PluginAPI * m_pluginAPI
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Private Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Private Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Detailed Description
Definition at line 27 of file atvmodplugin.h.
Constructor & Destructor Documentation
ATVModPlugin()
ATVModPlugin::ATVModPlugin (QObject * parent = 0) explicit
Definition at line 36 of file atvmodplugin.cpp.
                                           :
     QObject(parent),
     m_pluginAPI(0)
 {
 }
Member Function Documentation
createTxChannelBS()
BasebandSampleSource * ATVModPlugin::createTxChannelBS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 69 of file atvmodplugin.cpp.
 {
     return new ATVMod(deviceAPI);
 }
createTxChannelCS()
ChannelAPI * ATVModPlugin::createTxChannelCS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 74 of file atvmodplugin.cpp.
 {
     return new ATVMod(deviceAPI);
 }
createTxChannelGUI()
PluginInstanceGUI * ATVModPlugin::createTxChannelGUI (DeviceUISet * deviceUISet, BasebandSampleSource * txChannel) virtual
Reimplemented from PluginInterface.
Definition at line 63 of file atvmodplugin.cpp.
References ATVModGUI::create(), and m_pluginAPI.
Referenced by initPlugin().
 {
     return ATVModGUI::create(m_pluginAPI, deviceUISet, txChannel);
 }
getPluginDescriptor()
const PluginDescriptor & ATVModPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 42 of file atvmodplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void ATVModPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 47 of file atvmodplugin.cpp.
References createTxChannelGUI(), ATVMod::m_channelId, ATVMod::m_channelIdURI, m_pluginAPI, and PluginAPI::registerTxChannel().
 {
     m_pluginAPI = pluginAPI;
     // register ATV modulator
     m_pluginAPI->registerTxChannel(ATVMod::m_channelIdURI, ATVMod::m_channelId, this);
 }
Member Data Documentation
m_pluginAPI
PluginAPI* ATVModPlugin::m_pluginAPI private
Definition at line 45 of file atvmodplugin.h.
Referenced by createTxChannelGUI(), and initPlugin().
m_pluginDescriptor
const PluginDescriptor ATVModPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("ATV Modulator"),
    QString("4.5.2"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 43 of file atvmodplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/channeltx/modatv/atvmodplugin.h
plugins/channeltx/modatv/atvmodplugin.cpp