SDRAngel: RollupWidget Class Reference
RollupWidget Class Reference
#include <rollupwidget.h>
Signals
void widgetRolled (QWidget *widget, bool rollDown)
Public Member Functions
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Protected Types
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 7 of file rollupwidget.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
VersionMarker
Definition at line 19 of file rollupwidget.h.
          {
         VersionMarker = 0xff
     };
ContextMenuType
enum RollupWidget::ContextMenuType protected
Enumerator
ContextMenuNone
ContextMenuChannelSettings
ContextMenuStreamSettings
Definition at line 23 of file rollupwidget.h.
     {
         ContextMenuNone,
         ContextMenuChannelSettings,
         ContextMenuStreamSettings
     };
Constructor & Destructor Documentation
RollupWidget()
RollupWidget::RollupWidget (QWidget * parent = NULL)
Definition at line 7 of file rollupwidget.cpp.
References m_titleColor, and m_titleTextColor.
                                           :
     QWidget(parent),
     m_highlighted(false),
     m_contextMenuType(ContextMenuNone),
     m_streamIndicator("S")
 {
     setMinimumSize(250, 150);
     setSizePolicy(QSizePolicy::MinimumExpanding, QSizePolicy::MinimumExpanding);
     setBackgroundRole(QPalette::Window);
     setAutoFillBackground(false);
     setAttribute(Qt::WA_OpaquePaintEvent, true);
     // Vorgaben aus der Palette
     m_titleColor = palette().highlight().color();
     m_titleTextColor = palette().highlightedText().color();
 }
Member Function Documentation
arrangeRollups()
int RollupWidget::arrangeRollups () protected
Definition at line 114 of file rollupwidget.cpp.
References i.
Referenced by event(), eventFilter(), mousePressEvent(), and resizeEvent().
 {
     QFontMetrics fm(font());
     int pos = fm.height() + 4;
     for(int i = 0; i < children().count(); ++i)
     {
         QWidget* r = qobject_cast<QWidget*>(children()[i]);
         if (r != nullptr)
         {
             pos += fm.height() + 2;
             if (!r->isHidden() && (r->windowTitle() != "Basic channel settings") && (r->windowTitle() != "Select device stream"))
             {
                 r->move(2, pos + 3);
                 int h = 0;
                 if(r->hasHeightForWidth()) {
                     h = r->heightForWidth(width() - 4);
                 } else {
                     h = r->sizeHint().height();
                 }
                 r->resize(width() - 4, h);
                 pos += r->height() + 5;
             }
         }
     }
     setMinimumHeight(pos);
     setMaximumHeight(pos);
     return pos;
 }
event()
bool RollupWidget::event (QEvent * event) protected
Definition at line 358 of file rollupwidget.cpp.
References arrangeRollups().
 {
     if(event->type() == QEvent::ChildAdded) {
         ((QChildEvent*)event)->child()->installEventFilter(this);
         arrangeRollups();
     } else if(event->type() == QEvent::ChildRemoved) {
         ((QChildEvent*)event)->child()->removeEventFilter(this);
         arrangeRollups();
     }
     return QWidget::event(event);
 }
eventFilter()
bool RollupWidget::eventFilter (QObject * object, QEvent * event) protected
Definition at line 370 of file rollupwidget.cpp.
References arrangeRollups(), and widgetRolled().
 {
     if(event->type() == QEvent::Show) {
         if(children().contains(object)) {
             arrangeRollups();
             emit widgetRolled(qobject_cast<QWidget*>(object), true);
         }
     } else if(event->type() == QEvent::Hide) {
         if(children().contains(object)) {
             arrangeRollups();
             emit widgetRolled(qobject_cast<QWidget*>(object), false);
         }
     } else if(event->type() == QEvent::WindowTitleChange) {
         if(children().contains(object))
             repaint();
     }
     return QWidget::eventFilter(object, event);
 }
mousePressEvent()
void RollupWidget::mousePressEvent (QMouseEvent * event) protected
Definition at line 307 of file rollupwidget.cpp.
References arrangeRollups(), ContextMenuChannelSettings, ContextMenuStreamSettings, i, and m_contextMenuType.
 {
     QFontMetrics fm(font());
     // menu box left
     if (QRectF(3.5, 3.5, fm.ascent(), fm.ascent()).contains(event->pos()))
     {
         m_contextMenuType = ContextMenuChannelSettings;
         emit customContextMenuRequested(event->globalPos());
         return;
     }
     // Stream channel menu left
     if (QRectF(5.5 + fm.ascent(), 2.5, fm.ascent() + 2.0, fm.ascent() + 2.0).contains(event->pos()))
     {
         m_contextMenuType = ContextMenuStreamSettings;
         emit customContextMenuRequested(event->globalPos());
         return;
     }
     // close button right
     if(QRectF(width() - 3.5 - fm.ascent(), 3.5, fm.ascent(), fm.ascent()).contains(event->pos())) {
         close();
         return;
     }
     // check if we need to change a rollup widget
     int pos = fm.height() + 4;
     for(int i = 0; i < children().count(); ++i) {
         QWidget* r = qobject_cast<QWidget*>(children()[i]);
         if(r != NULL) {
             if((event->y() >= pos) && (event->y() < (pos + fm.height() + 3))) {
                 if(r->isHidden()) {
                     r->show();
                     //emit widgetRolled(r, true);
                 } else {
                     r->hide();
                     //emit widgetRolled(r, false);
                 }
                 arrangeRollups();
                 repaint();
                 return;
             } else {
                 pos += fm.height() + 2;
                 if(!r->isHidden())
                     pos += r->height() + 5;
             }
         }
     }
 }
paintEvent()
void RollupWidget::paintEvent (QPaintEvent *) protected
Definition at line 149 of file rollupwidget.cpp.
References m_highlighted, m_streamIndicator, m_titleColor, m_titleTextColor, and paintRollup().
 {
     QPainter p(this);
     QColor frame = palette().highlight().color();
     // Eigenbau
     QFontMetrics fm(font());
     p.setRenderHint(QPainter::Antialiasing, true);
     // Ecken
     p.setPen(Qt::NoPen);
     p.setBrush(palette().base());
     p.drawRect(0, 0, 5, 5);
     p.drawRect(width() - 5, 0, 5, 5);
     p.drawRect(0, height() - 5, 5, 5);
     p.drawRect(width() - 5, height() - 5, 5, 5);
     // Rahmen
     p.setPen(m_highlighted ? Qt::white : frame);
     p.setBrush(palette().window());
     QRectF r(rect());
     r.adjust(0.5, 0.5, -0.5, -0.5);
     p.drawRoundedRect(r, 3.0, 3.0, Qt::AbsoluteSize);
     // Titel-Hintergrund
     p.setPen(Qt::NoPen);
     p.setBrush(m_titleColor);
     QPainterPath path;
     path.moveTo(1.5, fm.height() + 2.5);
     path.lineTo(width() - 1.5, fm.height() + 2.5);
     path.lineTo(width() - 1.5, 3.5);
     path.arcTo(QRectF(width() - 3.5, 0, 2.5, 2.5), 270, -90);
     path.lineTo(3.5, 1.5);
     path.arcTo(QRectF(1.5, 2.5, 2.5, 2.5), 90, 90);
     p.drawPath(path);
     // Titel-Abschlusslinie
     p.setPen(frame);
     p.drawLine(QPointF(0.5, 2 + fm.height() + 1.5), QPointF(width() - 1.5, 2 + fm.height() + 1.5));
     // Aktiv-Button links
     p.setPen(QPen(palette().windowText().color(), 1.0));
     p.setBrush(palette().light());
     p.drawRoundedRect(QRectF(3.5, 3.5, fm.ascent(), fm.ascent()), 2.0, 2.0, Qt::AbsoluteSize);
     p.setPen(QPen(Qt::white, 1.0));
     p.drawText(QRectF(3.5, 2.5, fm.ascent(), fm.ascent()),  Qt::AlignCenter, "c");
     // Stromkanal-Button links
     p.setPen(QPen(palette().windowText().color(), 1.0));
     p.setBrush(palette().light());
     p.drawRoundedRect(QRectF(5.5 + fm.ascent(), 2.5, fm.ascent() + 2.0, fm.ascent() + 2.0), 2.0, 2.0, Qt::AbsoluteSize);
     p.setPen(QPen(Qt::white, 1.0));
     p.drawText(QRectF(5.5 + fm.ascent(), 2.5, fm.ascent() + 2.0, fm.ascent() + 2.0),  Qt::AlignCenter, m_streamIndicator);
     // Schlieen-Button rechts
     p.setRenderHint(QPainter::Antialiasing, true);
     p.setPen(QPen(palette().windowText().color(), 1.0));
     p.setBrush(palette().light());
     r = QRectF(width() - 3.5 - fm.ascent(), 3.5, fm.ascent(), fm.ascent());
     p.drawRoundedRect(r, 2.0, 2.0, Qt::AbsoluteSize);
     p.setPen(QPen(palette().windowText().color(), 1.5));
     p.drawLine(r.topLeft() + QPointF(1, 1), r.bottomRight() + QPointF(-1, -1));
     p.drawLine(r.bottomLeft() + QPointF(1, -1), r.topRight() + QPointF(-1, 1));
     // Titel
     //p.setPen(palette().highlightedText().color());
     p.setPen(m_titleTextColor);
     p.drawText(QRect(2 + 2*fm.height() + 2, 2, width() - 6 - 3*fm.height(), fm.height()),
         fm.elidedText(windowTitle(), Qt::ElideMiddle, width() - 6 - 3*fm.height(), 0));
     // Rollups
     int pos = fm.height() + 4;
     const QObjectList& c = children();
     QObjectList::ConstIterator w = c.begin();
     QObjectList::ConstIterator n = c.begin();
     for(n = c.begin(); n != c.end(); ++n) {
         if(qobject_cast<QWidget*>(*n) != NULL)
             break;
     }
     for(w = n; w != c.end(); w = n) {
         if(n != c.end())
             ++n;
         for(; n != c.end(); ++n) {
             if(qobject_cast<QWidget*>(*n) != NULL)
                 break;
         }
         pos += paintRollup(qobject_cast<QWidget*>(*w), pos, &p, n == c.end(), frame);
     }
 }
paintRollup()
int RollupWidget::paintRollup (QWidget * rollup, int pos, QPainter * p, bool last, const QColor & frame) protected
Definition at line 242 of file rollupwidget.cpp.
Referenced by paintEvent().
 {
     if ((rollup->windowTitle() == "Basic channel settings") || (rollup->windowTitle() == "Select device stream")) {
         return 0;
     }
     QFontMetrics fm(font());
     int height = 1;
     // Titel-Abschlusslinie
     if(!rollup->isHidden()) {
         p->setPen(palette().dark().color());
         p->drawLine(QPointF(1.5, pos + fm.height() + 1.5), QPointF(width() - 1.5, pos + fm.height() + 1.5));
         p->setPen(palette().light().color());
         p->drawLine(QPointF(1.5, pos + fm.height() + 2.5), QPointF(width() - 1.5, pos + fm.height() + 2.5));
         height += 2;
     } else {
         if(!last) {
             p->setPen(frame);
             p->drawLine(QPointF(1.5, pos + fm.height() + 1.5), QPointF(width() - 1.5, pos + fm.height() + 1.5));
             height++;
         }
     }
     // Titel
     p->setPen(palette().windowText().color());
     p->drawText(QRect(2 + fm.height(), pos, width() - 4 - fm.height(), fm.height()),
         fm.elidedText(rollup->windowTitle(), Qt::ElideMiddle, width() - 4 - fm.height(), 0));
     height += fm.height();
     // Ausklapp-Icon
     p->setPen(palette().windowText().color());
     p->setBrush(palette().windowText());
     if(!rollup->isHidden()) {
         QPolygonF a;
         a.append(QPointF(3.5, pos + 2));
         a.append(QPointF(3.5 + fm.ascent(), pos + 2));
         a.append(QPointF(3.5 + fm.ascent() / 2.0, pos + fm.height() - 2));
         p->drawPolygon(a);
     } else {
         QPolygonF a;
         a.append(QPointF(3.5, pos + 2));
         a.append(QPointF(3.5, pos + fm.height() - 2));
         a.append(QPointF(3.5 + fm.ascent(), pos + fm.height() / 2));
         p->drawPolygon(a);
     }
     // Inhalt
     if(!rollup->isHidden() && (!last)) {
         // Rollup-Abschlusslinie
         p->setPen(frame);
         p->drawLine(QPointF(1.5, pos + fm.height() + rollup->height() + 6.5),
                     QPointF(width() - 1.5, pos + fm.height() + rollup->height() + 6.5));
         height += rollup->height() + 4;
     }
     return height;
 }
resetContextMenuType()
void RollupWidget::resetContextMenuType () inline protected
Definition at line 50 of file rollupwidget.h.
Referenced by WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), ChannelAnalyzerGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), and DSDDemodGUI::onMenuDialogCalled().
 { m_contextMenuType = ContextMenuNone; }
resizeEvent()
void RollupWidget::resizeEvent (QResizeEvent * size) protected
Definition at line 301 of file rollupwidget.cpp.
References arrangeRollups().
 {
     arrangeRollups();
     QWidget::resizeEvent(size);
 }
restoreState()
bool RollupWidget::restoreState (const QByteArray & state, int version = 0) protected
Definition at line 54 of file rollupwidget.cpp.
References i, and VersionMarker.
 {
     if(state.isEmpty())
         return false;
     QByteArray sd = state;
     QDataStream stream(&sd, QIODevice::ReadOnly);
     int marker, v;
     stream >> marker;
     stream >> v;
     if((stream.status() != QDataStream::Ok) || (marker != VersionMarker) || (v != version))
         return false;
     int count;
     stream >> count;
     if(stream.status() != QDataStream::Ok)
         return false;
     for(int i = 0; i < count; ++i) {
         QString name;
         int visible;
         stream >> name;
         stream >> visible;
         if(stream.status() != QDataStream::Ok)
             return false;
         for(int j = 0; j < children().count(); ++j) {
             QWidget* r = qobject_cast<QWidget*>(children()[j]);
             if(r != NULL) {
                 if(r->objectName() == name) {
                     if(visible)
                         r->show();
                     else r->hide();
                     break;
                 }
             }
         }
     }
     return true;
 }
saveState()
QByteArray RollupWidget::saveState (int version = 0) const protected
Definition at line 25 of file rollupwidget.cpp.
References i, and VersionMarker.
 {
     QByteArray state;
     QDataStream stream(&state, QIODevice::WriteOnly);
     int count = 0;
     for(int i = 0; i < children().count(); ++i) {
         QWidget* r = qobject_cast<QWidget*>(children()[i]);
         if(r != NULL)
             count++;
     }
     stream << VersionMarker;
     stream << version;
     stream << count;
     for(int i = 0; i < children().count(); ++i) {
         QWidget* r = qobject_cast<QWidget*>(children()[i]);
         if(r != NULL) {
             stream << r->objectName();
             if(r->isHidden())
                 stream << (int)0;
             else stream << (int)1;
         }
     }
     return state;
 }
setHighlighted()
void RollupWidget::setHighlighted (bool highlighted)
Definition at line 105 of file rollupwidget.cpp.
References m_highlighted.
Referenced by WFMDemodGUI::channelMarkerHighlightedByCursor(), AMDemodGUI::channelMarkerHighlightedByCursor(), NFMDemodGUI::channelMarkerHighlightedByCursor(), SSBDemodGUI::channelMarkerHighlightedByCursor(), BFMDemodGUI::channelMarkerHighlightedByCursor(), FreqTrackerGUI::channelMarkerHighlightedByCursor(), ATVDemodGUI::channelMarkerHighlightedByCursor(), UDPSinkGUI::channelMarkerHighlightedByCursor(), ChannelAnalyzerGUI::channelMarkerHighlightedByCursor(), FreeDVDemodGUI::channelMarkerHighlightedByCursor(), DSDDemodGUI::channelMarkerHighlightedByCursor(), and DATVDemodGUI::channelMarkerHighlightedByCursor().
 {
     if (m_highlighted != highlighted)
     {
         m_highlighted = highlighted;
         update();
     }
 }
setStreamIndicator()
void RollupWidget::setStreamIndicator (const QString & indicator) protected
Definition at line 389 of file rollupwidget.cpp.
References m_streamIndicator.
Referenced by AMDemodGUI::displayStreamIndex().
 {
     m_streamIndicator = indicator;
     update();
 }
setTitleColor()
void RollupWidget::setTitleColor (const QColor & c)
Definition at line 97 of file rollupwidget.cpp.
References m_titleColor, and m_titleTextColor.
Referenced by AMDemodGUI::AMDemodGUI(), LoRaDemodGUI::applySettings(), RemoteSinkGUI::applySettings(), LocalSourceGUI::applySettings(), LocalSinkGUI::applySettings(), AMModGUI::applySettings(), RemoteSourceGUI::applySettings(), WFMModGUI::applySettings(), FileSourceGUI::applySettings(), DATVDemodGUI::applySettings(), ATVDemodGUI::ATVDemodGUI(), ATVModGUI::ATVModGUI(), BFMDemodGUI::BFMDemodGUI(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), WFMDemodGUI::displaySettings(), LoRaDemodGUI::displaySettings(), NFMDemodGUI::displaySettings(), AMDemodGUI::displaySettings(), SSBDemodGUI::displaySettings(), FreqTrackerGUI::displaySettings(), RemoteSinkGUI::displaySettings(), LocalSourceGUI::displaySettings(), LocalSinkGUI::displaySettings(), BFMDemodGUI::displaySettings(), UDPSourceGUI::displaySettings(), NFMModGUI::displaySettings(), AMModGUI::displaySettings(), RemoteSourceGUI::displaySettings(), ATVModGUI::displaySettings(), WFMModGUI::displaySettings(), UDPSinkGUI::displaySettings(), ChannelAnalyzerGUI::displaySettings(), FreeDVModGUI::displaySettings(), FreeDVDemodGUI::displaySettings(), SSBModGUI::displaySettings(), FileSourceGUI::displaySettings(), DSDDemodGUI::displaySettings(), FreqTrackerGUI::FreqTrackerGUI(), WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), ChannelAnalyzerGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), DSDDemodGUI::onMenuDialogCalled(), SSBDemodGUI::SSBDemodGUI(), SSBModGUI::SSBModGUI(), UDPSinkGUI::UDPSinkGUI(), and WFMDemodGUI::WFMDemodGUI().
 {
     m_titleColor = c;
     float l = 0.2126*c.redF() + 0.7152*c.greenF() + 0.0722*c.blueF();
     m_titleTextColor = l < 0.5f ? Qt::white : Qt::black;
     update();
 }
widgetRolled
void RollupWidget::widgetRolled (QWidget * widget, bool rollDown) signal
Referenced by AMDemodGUI::AMDemodGUI(), AMModGUI::AMModGUI(), ATVDemodGUI::ATVDemodGUI(), ATVModGUI::ATVModGUI(), BFMDemodGUI::BFMDemodGUI(), ChannelAnalyzerGUI::ChannelAnalyzerGUI(), DATVDemodGUI::DATVDemodGUI(), DSDDemodGUI::DSDDemodGUI(), eventFilter(), FileSourceGUI::FileSourceGUI(), FreeDVDemodGUI::FreeDVDemodGUI(), FreeDVModGUI::FreeDVModGUI(), FreqTrackerGUI::FreqTrackerGUI(), LocalSinkGUI::LocalSinkGUI(), LocalSourceGUI::LocalSourceGUI(), LoRaDemodGUI::LoRaDemodGUI(), NFMDemodGUI::NFMDemodGUI(), NFMModGUI::NFMModGUI(), RemoteSinkGUI::RemoteSinkGUI(), RemoteSourceGUI::RemoteSourceGUI(), SSBDemodGUI::SSBDemodGUI(), SSBModGUI::SSBModGUI(), UDPSinkGUI::UDPSinkGUI(), UDPSourceGUI::UDPSourceGUI(), WFMDemodGUI::WFMDemodGUI(), and WFMModGUI::WFMModGUI().
Member Data Documentation
m_contextMenuType
ContextMenuType RollupWidget::m_contextMenuType protected
Definition at line 33 of file rollupwidget.h.
Referenced by mousePressEvent(), WFMDemodGUI::onMenuDialogCalled(), NFMDemodGUI::onMenuDialogCalled(), AMDemodGUI::onMenuDialogCalled(), FreqTrackerGUI::onMenuDialogCalled(), LocalSinkGUI::onMenuDialogCalled(), SSBDemodGUI::onMenuDialogCalled(), LocalSourceGUI::onMenuDialogCalled(), RemoteSourceGUI::onMenuDialogCalled(), UDPSourceGUI::onMenuDialogCalled(), RemoteSinkGUI::onMenuDialogCalled(), FileSourceGUI::onMenuDialogCalled(), FreeDVDemodGUI::onMenuDialogCalled(), BFMDemodGUI::onMenuDialogCalled(), UDPSinkGUI::onMenuDialogCalled(), ChannelAnalyzerGUI::onMenuDialogCalled(), AMModGUI::onMenuDialogCalled(), FreeDVModGUI::onMenuDialogCalled(), NFMModGUI::onMenuDialogCalled(), WFMModGUI::onMenuDialogCalled(), SSBModGUI::onMenuDialogCalled(), ATVModGUI::onMenuDialogCalled(), and DSDDemodGUI::onMenuDialogCalled().
m_highlighted
bool RollupWidget::m_highlighted protected
Definition at line 32 of file rollupwidget.h.
Referenced by paintEvent(), and setHighlighted().
m_streamIndicator
QString RollupWidget::m_streamIndicator protected
Definition at line 34 of file rollupwidget.h.
Referenced by paintEvent(), and setStreamIndicator().
m_titleColor
QColor RollupWidget::m_titleColor protected
Definition at line 30 of file rollupwidget.h.
Referenced by paintEvent(), RollupWidget(), and setTitleColor().
m_titleTextColor
QColor RollupWidget::m_titleTextColor protected
Definition at line 31 of file rollupwidget.h.
Referenced by paintEvent(), RollupWidget(), and setTitleColor().
The documentation for this class was generated from the following files:
sdrgui/gui/rollupwidget.h
sdrgui/gui/rollupwidget.cpp