SDRAngel: DeviceAPI Class Reference
DeviceAPI Class Reference
#include <deviceapi.h>
Inherits QObject.
Public Types
enum StreamType { StreamSingleRx, StreamSingleTx, StreamMIMO }
< This is the same enum as in PluginInterface
enum EngineState {
StNotStarted, StIdle, StReady, StRunning,
StError
}
Public Member Functions
DeviceAPI (StreamType streamType, int deviceTabIndex, DSPDeviceSourceEngine *deviceSourceEngine, DSPDeviceSinkEngine *deviceSinkEngine, DSPDeviceMIMOEngine *deviceMIMOEngine)
~DeviceAPI ()
void addSourceStream (bool connect)
void removeLastSourceStream ()
void addSinkStream (bool connect)
void removeLastSinkStream ()
void addAncillarySink (BasebandSampleSink *sink, unsigned int index=0)
Adds a sink to receive full baseband and that is not a channel (e.g. spectrum)
void removeAncillarySink (BasebandSampleSink *sink, unsigned int index=0)
Removes it.
void setSpectrumSinkInput (bool sourceElseSink=true, unsigned int index=0)
Used in the MIMO case to select which stream is used as input to main spectrum.
void addChannelSink (ThreadedBasebandSampleSink *sink, int streamIndex=0)
Add a channel sink (Rx)
void removeChannelSink (ThreadedBasebandSampleSink *sink, int streamIndex=0)
Remove a channel sink (Rx)
void addChannelSource (ThreadedBasebandSampleSource *sink, int streamIndex=0)
Add a channel source (Tx)
void removeChannelSource (ThreadedBasebandSampleSource *sink, int streamIndex=0)
Remove a channel source (Tx)
void addChannelSinkAPI (ChannelAPI *channelAPI, int streamIndex=0)
void removeChannelSinkAPI (ChannelAPI *channelAPI, int streamIndex=0)
void addChannelSourceAPI (ChannelAPI *channelAPI, int streamIndex=0)
void removeChannelSourceAPI (ChannelAPI *channelAPI, int streamIndex=0)
void setSampleSource (DeviceSampleSource *source)
Set the device sample source (single Rx)
void setSampleSink (DeviceSampleSink *sink)
Set the device sample sink (single Tx)
void setSampleMIMO (DeviceSampleMIMO *mimo)
Set the device sample MIMO.
DeviceSampleSource * getSampleSource ()
Return pointer to the device sample source (single Rx) or nullptr.
DeviceSampleSink * getSampleSink ()
Return pointer to the device sample sink (single Tx) or nullptr.
DeviceSampleMIMO * getSampleMIMO ()
Return pointer to the device sample MIMO or nullptr.
bool initDeviceEngine ()
Init the device engine corresponding to the stream type.
bool startDeviceEngine ()
Start the device engine corresponding to the stream type.
void stopDeviceEngine ()
Stop the device engine corresponding to the stream type.
EngineState state () const
Return the state of the device engine corresponding to the stream type.
QString errorMessage ()
Last error message from the device engine.
uint getDeviceUID () const
Return the current device engine unique ID.
MessageQueue * getDeviceEngineInputMessageQueue ()
Device engine message queue.
MessageQueue * getSamplingDeviceInputMessageQueue ()
Sampling device (ex: single Rx) input message queue.
MessageQueue * getSamplingDeviceGUIMessageQueue ()
Sampling device (ex: single Tx) GUI input message queue.
void configureCorrections (bool dcOffsetCorrection, bool iqImbalanceCorrection, int streamIndex=0)
Configure current device engine DSP corrections (Rx)
void setHardwareId (const QString &id)
void setSamplingDeviceId (const QString &id)
void resetSamplingDeviceId ()
void setSamplingDeviceSerial (const QString &serial)
void setSamplingDeviceDisplayName (const QString &name)
void setSamplingDeviceSequence (int sequence)
void setHardwareUserArguments (const QString &userArguments)
void setSamplingDevicePluginInterface (PluginInterface *iface)
void setSamplingDevicePluginInstanceGUI (PluginInstanceGUI *gui)
const QString & getHardwareId () const
const QString & getSamplingDeviceId () const
const QString & getSamplingDeviceSerial () const
const QString & getSamplingDeviceDisplayName () const
uint32_t getSamplingDeviceSequence () const
const QString & getHardwareUserArguments () const
void setDeviceNbItems (uint32_t nbItems)
void setDeviceItemIndex (uint32_t index)
uint32_t getDeviceNbItems () const
uint32_t getDeviceItemIndex () const
int getDeviceSetIndex () const
PluginInterface * getPluginInterface ()
PluginInstanceGUI * getSamplingDevicePluginInstanceGUI ()
void getDeviceEngineStateStr (QString &state)
ChannelAPI * getChanelSinkAPIAt (int index, int streamIndex=0)
ChannelAPI * getChanelSourceAPIAt (int index, int streamIndex=0)
int getNbSourceChannels () const
int getNbSinkChannels () const
void loadSamplingDeviceSettings (const Preset *preset)
void saveSamplingDeviceSettings (Preset *preset)
DSPDeviceSourceEngine * getDeviceSourceEngine ()
DSPDeviceSinkEngine * getDeviceSinkEngine ()
void addSourceBuddy (DeviceAPI *buddy)
void addSinkBuddy (DeviceAPI *buddy)
void removeSourceBuddy (DeviceAPI *buddy)
void removeSinkBuddy (DeviceAPI *buddy)
void clearBuddiesLists ()
void * getBuddySharedPtr () const
void setBuddySharedPtr (void *ptr)
bool isBuddyLeader () const
void setBuddyLeader (bool isBuddyLeader)
const std::vector< DeviceAPI * > & getSourceBuddies () const
const std::vector< DeviceAPI * > & getSinkBuddies () const
void setNbSourceStreams (uint32_t nbSourceStreams)
void setNbSinkStreams (uint32_t nbSinkStreams)
uint32_t getNbSourceStreams () const
uint32_t getNbSinkStreams () const
const QTimer & getMasterTimer () const
This is the DSPEngine master timer.
Protected Attributes
StreamType m_streamType
int m_deviceTabIndex
This is the tab index in the GUI and also the device set index.
QString m_hardwareId
The internal id that identifies the type of hardware (i.e. HackRF, BladeRF, ...)
uint32_t m_deviceNbItems
Number of items in the physical device either Rx or Tx. Can be >1 for NxM devices (i.e. 2 for LimeSDR)
uint32_t m_deviceItemIndex
The item index inb the Rx or Tx side of the physical device. Can be >0 for NxM devices (i.e. 0 or 1 for LimeSDR)
uint32_t m_nbSourceStreams
The number of source streams in the logical device. 1 for Single Rx (SI) can be 0 or more for MIMO.
uint32_t m_nbSinkStreams
The number of sink streams in the logical device. 1 for Single Tx (SO) can be 0 or more for MIMO.
PluginInterface * m_pluginInterface
const QTimer & m_masterTimer
This is the DSPEngine master timer.
QString m_samplingDeviceId
The internal plugin ID corresponding to the device (i.e. for HackRF input, for HackRF output ...)
QString m_samplingDeviceSerial
The device serial number defined by the vendor or a fake one (SDRplay)
QString m_samplingDeviceDisplayName
The human readable name identifying this instance.
uint32_t m_samplingDeviceSequence
The device sequence. >0 when more than one device of the same type is connected.
QString m_hardwareUserArguments
User given arguments to be used at hardware level i.e. for the hardware device and device sequence.
PluginInstanceGUI * m_samplingDevicePluginInstanceUI
std::vector< DeviceAPI * > m_sourceBuddies
Device source APIs referencing the same physical device.
std::vector< DeviceAPI * > m_sinkBuddies
Device sink APIs referencing the same physical device.
void * m_buddySharedPtr
bool m_isBuddyLeader
DSPDeviceSourceEngine * m_deviceSourceEngine
QList< ChannelAPI * > m_channelSinkAPIs
DSPDeviceSinkEngine * m_deviceSinkEngine
QList< ChannelAPI * > m_channelSourceAPIs
DSPDeviceMIMOEngine * m_deviceMIMOEngine
Private Member Functions
void renumerateChannels ()
Detailed Description
Definition at line 42 of file deviceapi.h.
Member Enumeration Documentation
EngineState
enum DeviceAPI::EngineState
Enumerator
StNotStarted
engine is before initialization
StIdle
engine is idle
StReady
engine is ready to run
StRunning
engine is running
StError
engine is in error
Definition at line 52 of file deviceapi.h.
                      {
         StNotStarted,
         StIdle,
         StReady,
         StRunning,
         StError
     };
StreamType
enum DeviceAPI::StreamType
< This is the same enum as in PluginInterface
Enumerator
StreamSingleRx
Exposes a single input stream that can be one of the streams of a physical device.
StreamSingleTx
Exposes a single output stream that can be one of the streams of a physical device.
StreamMIMO
May expose any number of input and/or output streams.
Definition at line 45 of file deviceapi.h.
     {
         StreamSingleRx,
         StreamSingleTx,
         StreamMIMO
     };
Constructor & Destructor Documentation
DeviceAPI()
DeviceAPI::DeviceAPI (StreamType streamType, int deviceTabIndex, DSPDeviceSourceEngine * deviceSourceEngine, DSPDeviceSinkEngine * deviceSinkEngine, DSPDeviceMIMOEngine * deviceMIMOEngine)
Definition at line 32 of file deviceapi.cpp.
   :
     m_streamType(streamType),
     m_deviceTabIndex(deviceTabIndex),
     m_deviceNbItems(1),
     m_deviceItemIndex(0),
     m_nbSourceStreams(0),
     m_nbSinkStreams(0),
     m_pluginInterface(nullptr),
     m_masterTimer(DSPEngine::instance()->getMasterTimer()),
     m_samplingDeviceSequence(0),
     m_samplingDevicePluginInstanceUI(0),
     m_buddySharedPtr(nullptr),
     m_isBuddyLeader(false),
     m_deviceSourceEngine(deviceSourceEngine),
     m_deviceSinkEngine(deviceSinkEngine),
     m_deviceMIMOEngine(deviceMIMOEngine)
 {
 }
~DeviceAPI()
DeviceAPI::~DeviceAPI ()
Definition at line 57 of file deviceapi.cpp.
 {
 }
Member Function Documentation
addAncillarySink()
void DeviceAPI::addAncillarySink (BasebandSampleSink * sink, unsigned int index = 0)
Adds a sink to receive full baseband and that is not a channel (e.g. spectrum)
Definition at line 89 of file deviceapi.cpp.
References DSPDeviceMIMOEngine::addAncillarySink(), DSPDeviceSourceEngine::addSink(), DSPDeviceSinkEngine::addSpectrumSink(), m_deviceMIMOEngine, m_deviceSinkEngine, and m_deviceSourceEngine.
Referenced by AirspyHFInput::AirspyHFInput(), AirspyInput::AirspyInput(), TestMI::init(), and RTLSDRInput::RTLSDRInput().
 {
     if (m_deviceSourceEngine) {
         m_deviceSourceEngine->addSink(sink);
     } else if (m_deviceSinkEngine) {
         m_deviceSinkEngine->addSpectrumSink(sink);
     } else if (m_deviceMIMOEngine) {
         m_deviceMIMOEngine->addAncillarySink(sink, index);
     }
 }
addChannelSink()
void DeviceAPI::addChannelSink (ThreadedBasebandSampleSink * sink, int streamIndex = 0)
Add a channel sink (Rx)
Definition at line 118 of file deviceapi.cpp.
References DSPDeviceMIMOEngine::addChannelSink(), DSPDeviceSourceEngine::addThreadedSink(), m_deviceMIMOEngine, and m_deviceSourceEngine.
Referenced by AMDemod::AMDemod(), AMDemod::applySettings(), ATVDemod::ATVDemod(), BFMDemod::BFMDemod(), ChannelAnalyzer::ChannelAnalyzer(), DSDDemod::DSDDemod(), FreeDVDemod::FreeDVDemod(), FreqTracker::FreqTracker(), LocalSink::LocalSink(), LoRaDemod::LoRaDemod(), RemoteSink::RemoteSink(), SSBDemod::SSBDemod(), UDPSink::UDPSink(), and WFMDemod::WFMDemod().
 {
     if (m_deviceSourceEngine) {
         m_deviceSourceEngine->addThreadedSink(sink);
     } else if (m_deviceMIMOEngine) {
         m_deviceMIMOEngine->addChannelSink(sink, streamIndex);
     }
 }
addChannelSinkAPI()
void DeviceAPI::addChannelSinkAPI (ChannelAPI * channelAPI, int streamIndex = 0)
Definition at line 156 of file deviceapi.cpp.
References m_channelSinkAPIs, and renumerateChannels().
Referenced by AMDemod::AMDemod(), AMDemod::applySettings(), ATVDemod::ATVDemod(), BFMDemod::BFMDemod(), ChannelAnalyzer::ChannelAnalyzer(), DSDDemod::DSDDemod(), FreeDVDemod::FreeDVDemod(), FreqTracker::FreqTracker(), LocalSink::LocalSink(), LoRaDemod::LoRaDemod(), RemoteSink::RemoteSink(), SSBDemod::SSBDemod(), UDPSink::UDPSink(), and WFMDemod::WFMDemod().
 {
     (void) streamIndex;
     m_channelSinkAPIs.append(channelAPI);
     renumerateChannels();
 }
addChannelSource()
void DeviceAPI::addChannelSource (ThreadedBasebandSampleSource * sink, int streamIndex = 0)
Add a channel source (Tx)
Definition at line 138 of file deviceapi.cpp.
References DSPDeviceSinkEngine::addThreadedSource(), and m_deviceSinkEngine.
Referenced by AMMod::AMMod(), ATVMod::ATVMod(), FileSource::FileSource(), FreeDVMod::FreeDVMod(), LocalSource::LocalSource(), NFMMod::NFMMod(), RemoteSource::RemoteSource(), SSBMod::SSBMod(), UDPSource::UDPSource(), and WFMMod::WFMMod().
 {
     (void) streamIndex;
     if (m_deviceSinkEngine) {
         m_deviceSinkEngine->addThreadedSource(source);
     }
 }
addChannelSourceAPI()
void DeviceAPI::addChannelSourceAPI (ChannelAPI * channelAPI, int streamIndex = 0)
Definition at line 174 of file deviceapi.cpp.
References m_channelSourceAPIs, and renumerateChannels().
Referenced by AMMod::AMMod(), ATVMod::ATVMod(), FileSource::FileSource(), FreeDVMod::FreeDVMod(), LocalSource::LocalSource(), NFMMod::NFMMod(), RemoteSource::RemoteSource(), SSBMod::SSBMod(), UDPSource::UDPSource(), and WFMMod::WFMMod().
 {
     (void) streamIndex;
     m_channelSourceAPIs.append(channelAPI);
     renumerateChannels();
 }
addSinkBuddy()
void DeviceAPI::addSinkBuddy (DeviceAPI * buddy)
Definition at line 646 of file deviceapi.cpp.
References getHardwareId(), getSamplingDeviceSerial(), m_sinkBuddies, m_sourceBuddies, m_streamType, StreamSingleRx, and StreamSingleTx.
 {
     if (buddy->m_streamType != StreamSingleTx)
     {
         qDebug("DeviceAPI::addSinkBuddy: buddy %s(%s) is not of single Tx type",
                 qPrintable(buddy->getHardwareId()),
                 qPrintable(buddy->getSamplingDeviceSerial()));
         return;
     }
     m_sinkBuddies.push_back(buddy);
     if (m_streamType == StreamSingleRx) {
         buddy->m_sourceBuddies.push_back(this); // this is a source
     } else if (m_streamType == StreamSingleTx) {
         buddy->m_sinkBuddies.push_back(this); // this is a sink
     } else {
         qDebug("DeviceAPI::addSinkBuddy: not relevant if this is not a  single Rx or Tx");
         return;
     }
     qDebug("DeviceAPI::addSinkBuddy: added buddy %s(%s) [%llu] <-> [%llu]",
             qPrintable(buddy->getHardwareId()),
             qPrintable(buddy->getSamplingDeviceSerial()),
             (quint64) buddy,
             (quint64) this);
 }
addSinkStream()
void DeviceAPI::addSinkStream (bool connect)
Definition at line 75 of file deviceapi.cpp.
References DSPDeviceMIMOEngine::addSinkStream(), and m_deviceMIMOEngine.
 {
     if (m_deviceMIMOEngine) {
         m_deviceMIMOEngine->addSinkStream(connect);
     }
 }
addSourceBuddy()
void DeviceAPI::addSourceBuddy (DeviceAPI * buddy)
Definition at line 617 of file deviceapi.cpp.
References getHardwareId(), getSamplingDeviceSerial(), m_sinkBuddies, m_sourceBuddies, m_streamType, StreamSingleRx, and StreamSingleTx.
 {
     if (buddy->m_streamType != StreamSingleRx)
     {
         qDebug("DeviceAPI::addSourceBuddy: buddy %s(%s) is not of single Rx type",
                 qPrintable(buddy->getHardwareId()),
                 qPrintable(buddy->getSamplingDeviceSerial()));
         return;
     }
     m_sourceBuddies.push_back(buddy);
     if (m_streamType == StreamSingleRx) {
         buddy->m_sourceBuddies.push_back(this); // this is a source
     } else if (m_streamType == StreamSingleTx) {
         buddy->m_sinkBuddies.push_back(this); // this is a sink
     } else {
         qDebug("DeviceAPI::addSourceBuddy: not relevant if this is not a single Rx or Tx");
         return;
     }
     qDebug("DeviceAPI::addSourceBuddy: added buddy %s(%s) [%llu] <-> [%llu]",
             qPrintable(buddy->getHardwareId()),
             qPrintable(buddy->getSamplingDeviceSerial()),
             (quint64) buddy,
             (quint64) this);
 }
addSourceStream()
void DeviceAPI::addSourceStream (bool connect)
Definition at line 61 of file deviceapi.cpp.
References DSPDeviceMIMOEngine::addSourceStream(), and m_deviceMIMOEngine.
 {
     if (m_deviceMIMOEngine) {
         m_deviceMIMOEngine->addSourceStream(connect);
     }
 }
clearBuddiesLists()
void DeviceAPI::clearBuddiesLists ()
Definition at line 740 of file deviceapi.cpp.
References isBuddyLeader(), m_sinkBuddies, and m_sourceBuddies.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 {
     std::vector<DeviceAPI*>::iterator itSource = m_sourceBuddies.begin();
     std::vector<DeviceAPI*>::iterator itSink = m_sinkBuddies.begin();
     bool leaderElected = false;
     for (;itSource != m_sourceBuddies.end(); ++itSource)
     {
         if (isBuddyLeader() && !leaderElected)
         {
             (*itSource)->setBuddyLeader(true);
             leaderElected = true;
         }
         (*itSource)->removeSinkBuddy(this);
     }
     m_sourceBuddies.clear();
     for (;itSink != m_sinkBuddies.end(); ++itSink)
     {
         if (isBuddyLeader() && !leaderElected)
         {
             (*itSink)->setBuddyLeader(true);
             leaderElected = true;
         }
         (*itSink)->removeSinkBuddy(this);
     }
     m_sinkBuddies.clear();
 }
configureCorrections()
void DeviceAPI::configureCorrections (bool dcOffsetCorrection, bool iqImbalanceCorrection, int streamIndex = 0)
Configure current device engine DSP corrections (Rx)
Definition at line 355 of file deviceapi.cpp.
References DSPDeviceSourceEngine::configureCorrections(), DSPDeviceMIMOEngine::configureCorrections(), m_deviceMIMOEngine, and m_deviceSourceEngine.
Referenced by TestSourceInput::applySettings(), Bladerf1Input::applySettings(), AirspyInput::applySettings(), AirspyHFInput::applySettings(), TestMI::applySettings(), RTLSDRInput::applySettings(), PlutoSDRInput::applySettings(), HackRFInput::applySettings(), FCDProPlusInput::applySettings(), KiwiSDRInput::applySettings(), LocalInput::applySettings(), FCDProInput::applySettings(), SDRPlayInput::applySettings(), BladeRF2Input::applySettings(), SoapySDRInput::applySettings(), XTRXInput::applySettings(), LimeSDRInput::applySettings(), and RemoteInput::applySettings().
 {
     if (m_deviceSourceEngine) {
         m_deviceSourceEngine->configureCorrections(dcOffsetCorrection, iqImbalanceCorrection);
     } else if (m_deviceMIMOEngine) {
         m_deviceMIMOEngine->configureCorrections(dcOffsetCorrection, iqImbalanceCorrection, streamIndex);
     }
 }
errorMessage()
QString DeviceAPI::errorMessage ()
Last error message from the device engine.
Definition at line 290 of file deviceapi.cpp.
References DSPDeviceSourceEngine::errorMessage(), DSPDeviceSinkEngine::errorMessage(), DSPDeviceMIMOEngine::errorMessage(), m_deviceMIMOEngine, m_deviceSinkEngine, and m_deviceSourceEngine.
Referenced by SDRPlayGui::updateStatus(), KiwiSDRGui::updateStatus(), Bladerf1OutputGui::updateStatus(), BladeRF2OutputGui::updateStatus(), PerseusGui::updateStatus(), LocalOutputGui::updateStatus(), FCDProPlusGui::updateStatus(), FileSinkGui::updateStatus(), Bladerf1InputGui::updateStatus(), PlutoSDROutputGUI::updateStatus(), AirspyGui::updateStatus(), AirspyHFGui::updateStatus(), BladeRF2InputGui::updateStatus(), FileInputGUI::updateStatus(), XTRXOutputGUI::updateStatus(), TestSourceGui::updateStatus(), RTLSDRGui::updateStatus(), HackRFOutputGui::updateStatus(), LimeSDROutputGUI::updateStatus(), PlutoSDRInputGui::updateStatus(), HackRFInputGui::updateStatus(), FCDProGui::updateStatus(), XTRXInputGUI::updateStatus(), TestMIGui::updateStatus(), LimeSDRInputGUI::updateStatus(), LocalInputGui::updateStatus(), RemoteInputGui::updateStatus(), SoapySDROutputGui::updateStatus(), SoapySDRInputGui::updateStatus(), and RemoteOutputSinkGui::updateStatus().
 {
     if (m_deviceSourceEngine) {
         return m_deviceSourceEngine->errorMessage();
     } else if (m_deviceSinkEngine) {
         return m_deviceSinkEngine->errorMessage();
     } else if (m_deviceMIMOEngine) {
         return m_deviceMIMOEngine->errorMessage();
     } else {
         return "Not implemented";
     }
 }
getBuddySharedPtr()
void* DeviceAPI::getBuddySharedPtr () const inline
Definition at line 161 of file deviceapi.h.
Referenced by PlutoSDROutput::openDevice(), Bladerf1Output::openDevice(), HackRFOutput::openDevice(), Bladerf1Input::openDevice(), BladeRF2Output::openDevice(), PlutoSDRInput::openDevice(), HackRFInput::openDevice(), SoapySDROutput::openDevice(), BladeRF2Input::openDevice(), SoapySDRInput::openDevice(), XTRXOutput::openDevice(), LimeSDROutput::openDevice(), XTRXInput::openDevice(), LimeSDRInput::openDevice(), PlutoSDROutput::resumeBuddies(), PlutoSDRInput::resumeBuddies(), PlutoSDROutput::suspendBuddies(), and PlutoSDRInput::suspendBuddies().
 { return m_buddySharedPtr; }
getChanelSinkAPIAt()
ChannelAPI * DeviceAPI::getChanelSinkAPIAt (int index, int streamIndex = 0)
Definition at line 445 of file deviceapi.cpp.
References m_channelSinkAPIs, m_streamType, and StreamSingleRx.
Referenced by WebAPIAdapterGUI::devicesetChannelReportGet(), WebAPIAdapterSrv::devicesetChannelReportGet(), WebAPIAdapterGUI::devicesetChannelSettingsGet(), WebAPIAdapterSrv::devicesetChannelSettingsGet(), WebAPIAdapterGUI::devicesetChannelSettingsPutPatch(), WebAPIAdapterSrv::devicesetChannelSettingsPutPatch(), WebAPIAdapterGUI::getChannelsDetail(), WebAPIAdapterSrv::getChannelsDetail(), WebAPIAdapterGUI::getDeviceSet(), and WebAPIAdapterSrv::getDeviceSet().
 {
     (void) streamIndex;
     if (m_streamType == StreamSingleRx)
     {
         if (index < m_channelSinkAPIs.size()) {
             return m_channelSinkAPIs.at(index);
         } else {
             return nullptr;
         }
     }
     else // TODO: not implemented
     {
         return nullptr;
     }
 }
getChanelSourceAPIAt()
ChannelAPI * DeviceAPI::getChanelSourceAPIAt (int index, int streamIndex = 0)
Definition at line 463 of file deviceapi.cpp.
References m_channelSourceAPIs, m_streamType, and StreamSingleTx.
Referenced by WebAPIAdapterGUI::devicesetChannelReportGet(), WebAPIAdapterSrv::devicesetChannelReportGet(), WebAPIAdapterGUI::devicesetChannelSettingsGet(), WebAPIAdapterSrv::devicesetChannelSettingsGet(), WebAPIAdapterGUI::devicesetChannelSettingsPutPatch(), WebAPIAdapterSrv::devicesetChannelSettingsPutPatch(), WebAPIAdapterGUI::getChannelsDetail(), WebAPIAdapterSrv::getChannelsDetail(), WebAPIAdapterGUI::getDeviceSet(), and WebAPIAdapterSrv::getDeviceSet().
 {
     (void) streamIndex;
      if (m_streamType == StreamSingleTx)
     {
         if (index < m_channelSourceAPIs.size()) {
             return m_channelSourceAPIs.at(index);
         } else {
             return nullptr;
         }
     }
     else // TODO: not implemented
     {
         return nullptr;
     }
 }
getDeviceEngineInputMessageQueue()
MessageQueue * DeviceAPI::getDeviceEngineInputMessageQueue ()
Device engine message queue.
Definition at line 316 of file deviceapi.cpp.
References DSPDeviceSourceEngine::getInputMessageQueue(), DSPDeviceSinkEngine::getInputMessageQueue(), DSPDeviceMIMOEngine::getInputMessageQueue(), m_deviceMIMOEngine, m_deviceSinkEngine, and m_deviceSourceEngine.
Referenced by PlutoSDROutput::applySettings(), TestSourceInput::applySettings(), Bladerf1Output::applySettings(), HackRFOutput::applySettings(), Bladerf1Input::applySettings(), PerseusInput::applySettings(), AirspyInput::applySettings(), AirspyHFInput::applySettings(), TestMI::applySettings(), RTLSDRInput::applySettings(), PlutoSDRInput::applySettings(), BladeRF2Output::applySettings(), FCDProPlusInput::applySettings(), HackRFInput::applySettings(), KiwiSDRInput::applySettings(), FCDProInput::applySettings(), RemoteOutput::applySettings(), SDRPlayInput::applySettings(), SoapySDROutput::applySettings(), BladeRF2Input::applySettings(), FileSinkOutput::applySettings(), SoapySDRInput::applySettings(), XTRXOutput::applySettings(), LimeSDROutput::applySettings(), LimeSDRInput::applySettings(), HackRFOutput::handleMessage(), BladeRF2Output::handleMessage(), HackRFInput::handleMessage(), BladeRF2Input::handleMessage(), XTRXOutput::handleMessage(), LimeSDROutput::handleMessage(), XTRXInput::handleMessage(), LimeSDRInput::handleMessage(), FileInput::init(), RemoteInputUDPHandler::processData(), LocalOutput::setCenterFrequency(), LocalInput::setCenterFrequency(), LocalOutput::setSampleRate(), and LocalInput::setSampleRate().
 {
     if (m_deviceSourceEngine) {
         return m_deviceSourceEngine->getInputMessageQueue();
     } else if (m_deviceSinkEngine) {
         return m_deviceSinkEngine->getInputMessageQueue();
     } else if (m_deviceMIMOEngine) {
         return m_deviceMIMOEngine->getInputMessageQueue();
     } else {
         return nullptr;
     }
 }
getDeviceEngineStateStr()
void DeviceAPI::getDeviceEngineStateStr (QString & state)
Definition at line 389 of file deviceapi.cpp.
References m_deviceSinkEngine, m_deviceSourceEngine, DSPDeviceSourceEngine::state(), DSPDeviceSinkEngine::state(), DSPDeviceSourceEngine::StError, DSPDeviceSinkEngine::StError, DSPDeviceSourceEngine::StIdle, DSPDeviceSinkEngine::StIdle, DSPDeviceSourceEngine::StNotStarted, DSPDeviceSinkEngine::StNotStarted, DSPDeviceSourceEngine::StReady, DSPDeviceSinkEngine::StReady, DSPDeviceSourceEngine::StRunning, and DSPDeviceSinkEngine::StRunning.
Referenced by WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), PlutoSDROutput::webapiRun(), PlutoSDRInput::webapiRun(), Bladerf1Output::webapiRun(), HackRFOutput::webapiRun(), FCDProPlusInput::webapiRun(), TestSourceInput::webapiRun(), AirspyInput::webapiRun(), Bladerf1Input::webapiRun(), PerseusInput::webapiRun(), RTLSDRInput::webapiRun(), AirspyHFInput::webapiRun(), TestMI::webapiRun(), FCDProInput::webapiRun(), LocalOutput::webapiRun(), BladeRF2Output::webapiRun(), HackRFInput::webapiRun(), KiwiSDRInput::webapiRun(), LocalInput::webapiRun(), RemoteOutput::webapiRun(), SDRPlayInput::webapiRun(), SoapySDROutput::webapiRun(), BladeRF2Input::webapiRun(), FileSinkOutput::webapiRun(), SoapySDRInput::webapiRun(), XTRXOutput::webapiRun(), LimeSDROutput::webapiRun(), XTRXInput::webapiRun(), LimeSDRInput::webapiRun(), RemoteInput::webapiRun(), FileInput::webapiRun(), PlutoSDROutput::webapiRunGet(), PlutoSDRInput::webapiRunGet(), Bladerf1Output::webapiRunGet(), HackRFOutput::webapiRunGet(), FCDProPlusInput::webapiRunGet(), TestSourceInput::webapiRunGet(), AirspyInput::webapiRunGet(), Bladerf1Input::webapiRunGet(), PerseusInput::webapiRunGet(), RTLSDRInput::webapiRunGet(), AirspyHFInput::webapiRunGet(), TestMI::webapiRunGet(), FCDProInput::webapiRunGet(), LocalOutput::webapiRunGet(), BladeRF2Output::webapiRunGet(), HackRFInput::webapiRunGet(), KiwiSDRInput::webapiRunGet(), LocalInput::webapiRunGet(), RemoteOutput::webapiRunGet(), SDRPlayInput::webapiRunGet(), SoapySDROutput::webapiRunGet(), BladeRF2Input::webapiRunGet(), FileSinkOutput::webapiRunGet(), SoapySDRInput::webapiRunGet(), XTRXOutput::webapiRunGet(), LimeSDROutput::webapiRunGet(), XTRXInput::webapiRunGet(), LimeSDRInput::webapiRunGet(), RemoteInput::webapiRunGet(), and FileInput::webapiRunGet().
 {
     if (m_deviceSourceEngine)
     {
         switch(m_deviceSourceEngine->state())
         {
         case DSPDeviceSourceEngine::StNotStarted:
             state = "notStarted";
             break;
         case DSPDeviceSourceEngine::StIdle:
             state = "idle";
             break;
         case DSPDeviceSourceEngine::StReady:
             state = "ready";
             break;
         case DSPDeviceSourceEngine::StRunning:
             state = "running";
             break;
         case DSPDeviceSourceEngine::StError:
             state = "error";
             break;
         default:
             state = "notStarted";
             break;
         }
     }
     else if (m_deviceSinkEngine)
     {
         switch(m_deviceSinkEngine->state())
         {
         case DSPDeviceSinkEngine::StNotStarted:
             state = "notStarted";
             break;
         case DSPDeviceSinkEngine::StIdle:
             state = "idle";
             break;
         case DSPDeviceSinkEngine::StReady:
             state = "ready";
             break;
         case DSPDeviceSinkEngine::StRunning:
             state = "running";
             break;
         case DSPDeviceSinkEngine::StError:
             state = "error";
             break;
         default:
             state = "notStarted";
             break;
         }
     }
     else
     {
         state = "notStarted";
     }
 }
getDeviceItemIndex()
uint32_t DeviceAPI::getDeviceItemIndex () const inline
Definition at line 129 of file deviceapi.h.
Referenced by BladeRF2Output::applySettings(), SoapySDROutput::applySettings(), BladeRF2Input::applySettings(), SoapySDRInput::applySettings(), XTRXOutput::applySettings(), XTRXInput::applySettings(), WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), BladeRF2Output::handleMessage(), SoapySDROutput::handleMessage(), BladeRF2Input::handleMessage(), SoapySDRInput::handleMessage(), BladeRF2Output::openDevice(), SoapySDROutput::openDevice(), BladeRF2Input::openDevice(), SoapySDRInput::openDevice(), XTRXOutput::openDevice(), LimeSDROutput::openDevice(), XTRXInput::openDevice(), LimeSDRInput::openDevice(), BladeRF2Output::start(), SoapySDROutput::start(), BladeRF2Input::start(), SoapySDRInput::start(), XTRXOutput::start(), XTRXInput::start(), BladeRF2Output::stop(), SoapySDROutput::stop(), BladeRF2Input::stop(), SoapySDRInput::stop(), XTRXOutput::stop(), and XTRXInput::stop().
 { return m_deviceItemIndex; }
getDeviceNbItems()
uint32_t DeviceAPI::getDeviceNbItems () const inline
Definition at line 128 of file deviceapi.h.
Referenced by WebAPIAdapterGUI::getDeviceSet(), and WebAPIAdapterSrv::getDeviceSet().
 { return m_deviceNbItems; }
getDeviceSetIndex()
int DeviceAPI::getDeviceSetIndex () const inline
Definition at line 131 of file deviceapi.h.
Referenced by Bladerf1Output::webapiReverseSendSettings(), PlutoSDROutput::webapiReverseSendSettings(), TestSourceInput::webapiReverseSendSettings(), HackRFOutput::webapiReverseSendSettings(), Bladerf1Input::webapiReverseSendSettings(), PerseusInput::webapiReverseSendSettings(), LocalOutput::webapiReverseSendSettings(), AirspyInput::webapiReverseSendSettings(), AirspyHFInput::webapiReverseSendSettings(), TestMI::webapiReverseSendSettings(), RTLSDRInput::webapiReverseSendSettings(), PlutoSDRInput::webapiReverseSendSettings(), FCDProPlusInput::webapiReverseSendSettings(), HackRFInput::webapiReverseSendSettings(), BladeRF2Output::webapiReverseSendSettings(), KiwiSDRInput::webapiReverseSendSettings(), LocalInput::webapiReverseSendSettings(), FCDProInput::webapiReverseSendSettings(), RemoteOutput::webapiReverseSendSettings(), SDRPlayInput::webapiReverseSendSettings(), BladeRF2Input::webapiReverseSendSettings(), SoapySDROutput::webapiReverseSendSettings(), SoapySDRInput::webapiReverseSendSettings(), XTRXOutput::webapiReverseSendSettings(), LimeSDROutput::webapiReverseSendSettings(), XTRXInput::webapiReverseSendSettings(), LimeSDRInput::webapiReverseSendSettings(), RemoteInput::webapiReverseSendSettings(), FileInput::webapiReverseSendSettings(), Bladerf1Output::webapiReverseSendStartStop(), TestSourceInput::webapiReverseSendStartStop(), PlutoSDROutput::webapiReverseSendStartStop(), HackRFOutput::webapiReverseSendStartStop(), Bladerf1Input::webapiReverseSendStartStop(), PerseusInput::webapiReverseSendStartStop(), LocalOutput::webapiReverseSendStartStop(), AirspyInput::webapiReverseSendStartStop(), TestMI::webapiReverseSendStartStop(), AirspyHFInput::webapiReverseSendStartStop(), RTLSDRInput::webapiReverseSendStartStop(), PlutoSDRInput::webapiReverseSendStartStop(), FCDProPlusInput::webapiReverseSendStartStop(), HackRFInput::webapiReverseSendStartStop(), BladeRF2Output::webapiReverseSendStartStop(), KiwiSDRInput::webapiReverseSendStartStop(), LocalInput::webapiReverseSendStartStop(), FCDProInput::webapiReverseSendStartStop(), RemoteOutput::webapiReverseSendStartStop(), SDRPlayInput::webapiReverseSendStartStop(), BladeRF2Input::webapiReverseSendStartStop(), SoapySDROutput::webapiReverseSendStartStop(), SoapySDRInput::webapiReverseSendStartStop(), XTRXOutput::webapiReverseSendStartStop(), LimeSDROutput::webapiReverseSendStartStop(), XTRXInput::webapiReverseSendStartStop(), LimeSDRInput::webapiReverseSendStartStop(), RemoteInput::webapiReverseSendStartStop(), and FileInput::webapiReverseSendStartStop().
 { return m_deviceTabIndex; }
getDeviceSinkEngine()
DSPDeviceSinkEngine* DeviceAPI::getDeviceSinkEngine () inline
Definition at line 154 of file deviceapi.h.
Referenced by Bladerf1Input::applySettings().
 { return m_deviceSinkEngine; }
getDeviceSourceEngine()
DSPDeviceSourceEngine* DeviceAPI::getDeviceSourceEngine () inline
Definition at line 153 of file deviceapi.h.
Referenced by Bladerf1Output::applySettings().
 { return m_deviceSourceEngine; }
getDeviceUID()
uint DeviceAPI::getDeviceUID () const
Return the current device engine unique ID.
Definition at line 303 of file deviceapi.cpp.
References DSPDeviceSourceEngine::getUID(), DSPDeviceSinkEngine::getUID(), DSPDeviceMIMOEngine::getUID(), m_deviceMIMOEngine, m_deviceSinkEngine, and m_deviceSourceEngine.
Referenced by AirspyHFInput::AirspyHFInput(), AirspyInput::AirspyInput(), TestSourceInput::handleMessage(), PerseusInput::handleMessage(), AirspyInput::handleMessage(), RTLSDRInput::handleMessage(), AirspyHFInput::handleMessage(), Bladerf1Input::handleMessage(), PlutoSDRInput::handleMessage(), TestMI::handleMessage(), FCDProInput::handleMessage(), FCDProPlusInput::handleMessage(), HackRFInput::handleMessage(), KiwiSDRInput::handleMessage(), LocalInput::handleMessage(), SDRPlayInput::handleMessage(), BladeRF2Input::handleMessage(), SoapySDRInput::handleMessage(), LimeSDRInput::handleMessage(), RemoteInput::handleMessage(), TestMI::init(), LimeSDROutputGUI::LimeSDROutputGUI(), and RTLSDRInput::RTLSDRInput().
 {
     if (m_deviceSourceEngine) {
         return m_deviceSourceEngine->getUID();
     } else if (m_deviceSinkEngine) {
         return m_deviceSinkEngine->getUID();
     } else if (m_deviceMIMOEngine) {
         return m_deviceMIMOEngine->getUID();
     } else {
         return 0;
     }
 }
getHardwareId()
const QString& DeviceAPI::getHardwareId () const inline
Definition at line 119 of file deviceapi.h.
Referenced by addSinkBuddy(), addSourceBuddy(), MainCore::changeSampleSink(), MainCore::changeSampleSource(), WebAPIAdapterGUI::devicesetDeviceReportGet(), WebAPIAdapterSrv::devicesetDeviceReportGet(), WebAPIAdapterGUI::devicesetDeviceSettingsGet(), WebAPIAdapterSrv::devicesetDeviceSettingsGet(), WebAPIAdapterGUI::devicesetDeviceSettingsPutPatch(), WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch(), WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), removeSinkBuddy(), removeSourceBuddy(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { return m_hardwareId; }
getHardwareUserArguments()
const QString& DeviceAPI::getHardwareUserArguments () const inline
Definition at line 124 of file deviceapi.h.
Referenced by SoapySDROutput::openDevice(), and SoapySDRInput::openDevice().
 { return m_hardwareUserArguments; }
getMasterTimer()
const QTimer& DeviceAPI::getMasterTimer () const inline
This is the DSPEngine master timer.
Definition at line 173 of file deviceapi.h.
Referenced by FileInputGUI::FileInputGUI(), FileSinkGui::FileSinkGui(), FileSourceGUI::FileSourceGUI(), RemoteOutputSinkGui::RemoteOutputSinkGui(), and RemoteSourceGUI::RemoteSourceGUI().
getNbSinkChannels()
int DeviceAPI::getNbSinkChannels () const inline
Definition at line 144 of file deviceapi.h.
Referenced by WebAPIAdapterGUI::getChannelsDetail(), WebAPIAdapterSrv::getChannelsDetail(), WebAPIAdapterGUI::getDeviceSet(), and WebAPIAdapterSrv::getDeviceSet().
 { return m_channelSinkAPIs.size(); }
getNbSinkStreams()
uint32_t DeviceAPI::getNbSinkStreams () const inline
Definition at line 171 of file deviceapi.h.
 { return m_nbSinkStreams; }
getNbSourceChannels()
int DeviceAPI::getNbSourceChannels () const inline
Definition at line 143 of file deviceapi.h.
Referenced by WebAPIAdapterGUI::getChannelsDetail(), WebAPIAdapterSrv::getChannelsDetail(), WebAPIAdapterGUI::getDeviceSet(), and WebAPIAdapterSrv::getDeviceSet().
 { return m_channelSourceAPIs.size(); }
getNbSourceStreams()
uint32_t DeviceAPI::getNbSourceStreams () const inline
Definition at line 170 of file deviceapi.h.
Referenced by AMDemod::getNumberOfDeviceStreams().
 { return m_nbSourceStreams; }
getPluginInterface()
PluginInterface* DeviceAPI::getPluginInterface () inline
Definition at line 132 of file deviceapi.h.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { return m_pluginInterface; }
getSampleMIMO()
DeviceSampleMIMO * DeviceAPI::getSampleMIMO ()
Return pointer to the device sample MIMO or nullptr.
Definition at line 231 of file deviceapi.cpp.
References DSPDeviceMIMOEngine::getMIMO(), and m_deviceMIMOEngine.
Referenced by AMDemod::applySettings(), MainWindow::sampleMIMOChanged(), and TestMIGui::TestMIGui().
 {
     if (m_deviceMIMOEngine) {
         return m_deviceMIMOEngine->getMIMO();
     } else {
         return nullptr;
     }
 }
getSampleSink()
DeviceSampleSink * DeviceAPI::getSampleSink ()
Return pointer to the device sample sink (single Tx) or nullptr.
Definition at line 222 of file deviceapi.cpp.
References DSPDeviceSinkEngine::getSink(), and m_deviceSinkEngine.
Referenced by Bladerf1OutputGui::Bladerf1OutputGui(), BladeRF2OutputGui::BladeRF2OutputGui(), MainCore::changeSampleSink(), WebAPIAdapterGUI::devicesetDeviceReportGet(), WebAPIAdapterSrv::devicesetDeviceReportGet(), WebAPIAdapterGUI::devicesetDeviceRunDelete(), WebAPIAdapterSrv::devicesetDeviceRunDelete(), WebAPIAdapterGUI::devicesetDeviceRunGet(), WebAPIAdapterSrv::devicesetDeviceRunGet(), WebAPIAdapterGUI::devicesetDeviceRunPost(), WebAPIAdapterSrv::devicesetDeviceRunPost(), WebAPIAdapterGUI::devicesetDeviceSettingsGet(), WebAPIAdapterSrv::devicesetDeviceSettingsGet(), WebAPIAdapterGUI::devicesetDeviceSettingsPutPatch(), WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch(), FileSinkGui::FileSinkGui(), HackRFOutputGui::HackRFOutputGui(), LimeSDROutputGUI::LimeSDROutputGUI(), LocalOutputGui::LocalOutputGui(), PlutoSDROutputGUI::PlutoSDROutputGUI(), RemoteOutputSinkGui::RemoteOutputSinkGui(), MainWindow::sampleSinkChanged(), SoapySDROutputGui::SoapySDROutputGui(), RemoteSource::webapiFormatChannelReport(), and XTRXOutputGUI::XTRXOutputGUI().
 {
     if (m_deviceSinkEngine) {
         return m_deviceSinkEngine->getSink();
     } else {
         return nullptr;
     }
 }
getSampleSource()
DeviceSampleSource * DeviceAPI::getSampleSource ()
Return pointer to the device sample source (single Rx) or nullptr.
Definition at line 213 of file deviceapi.cpp.
References DSPDeviceSourceEngine::getSource(), and m_deviceSourceEngine.
Referenced by AirspyGui::AirspyGui(), AirspyHFGui::AirspyHFGui(), Bladerf1InputGui::Bladerf1InputGui(), BladeRF2InputGui::BladeRF2InputGui(), MainCore::changeSampleSource(), WebAPIAdapterGUI::devicesetDeviceReportGet(), WebAPIAdapterSrv::devicesetDeviceReportGet(), WebAPIAdapterGUI::devicesetDeviceRunDelete(), WebAPIAdapterSrv::devicesetDeviceRunDelete(), WebAPIAdapterGUI::devicesetDeviceRunGet(), WebAPIAdapterSrv::devicesetDeviceRunGet(), WebAPIAdapterGUI::devicesetDeviceRunPost(), WebAPIAdapterSrv::devicesetDeviceRunPost(), WebAPIAdapterGUI::devicesetDeviceSettingsGet(), WebAPIAdapterSrv::devicesetDeviceSettingsGet(), WebAPIAdapterGUI::devicesetDeviceSettingsPutPatch(), WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch(), FCDProGui::FCDProGui(), FCDProPlusGui::FCDProPlusGui(), FileInputGUI::FileInputGUI(), HackRFInputGui::HackRFInputGui(), KiwiSDRGui::KiwiSDRGui(), LimeSDRInputGUI::LimeSDRInputGUI(), LocalInputGui::LocalInputGui(), PerseusGui::PerseusGui(), PlutoSDRInputGui::PlutoSDRInputGui(), RemoteInputGui::RemoteInputGui(), RTLSDRGui::RTLSDRGui(), MainWindow::sampleSourceChanged(), SDRPlayGui::SDRPlayGui(), SoapySDRInputGui::SoapySDRInputGui(), TestSourceGui::TestSourceGui(), and XTRXInputGUI::XTRXInputGUI().
 {
     if (m_deviceSourceEngine) {
         return m_deviceSourceEngine->getSource();
     } else {
         return nullptr;
     }
 }
getSamplingDeviceDisplayName()
const QString& DeviceAPI::getSamplingDeviceDisplayName () const inline
Definition at line 122 of file deviceapi.h.
Referenced by MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { return m_samplingDeviceDisplayName; }
getSamplingDeviceGUIMessageQueue()
MessageQueue * DeviceAPI::getSamplingDeviceGUIMessageQueue ()
Sampling device (ex: single Tx) GUI input message queue.
Definition at line 342 of file deviceapi.cpp.
References DeviceSampleSink::getMessageQueueToGUI(), DeviceSampleSource::getMessageQueueToGUI(), DeviceSampleMIMO::getMessageQueueToGUI(), DSPDeviceMIMOEngine::getMIMO(), DSPDeviceSinkEngine::getSink(), DSPDeviceSourceEngine::getSource(), m_deviceMIMOEngine, m_deviceSinkEngine, and m_deviceSourceEngine.
Referenced by XTRXOutput::handleMessage(), LimeSDROutput::handleMessage(), XTRXInput::handleMessage(), and LimeSDRInput::handleMessage().
 {
     if (m_deviceSourceEngine) {
         return m_deviceSourceEngine->getSource()->getMessageQueueToGUI();
     } else if (m_deviceSinkEngine) {
         return m_deviceSinkEngine->getSink()->getMessageQueueToGUI();
     } else if (m_deviceMIMOEngine) {
         return m_deviceMIMOEngine->getMIMO()->getMessageQueueToGUI();
     } else {
         return nullptr;
     }
 }
getSamplingDeviceId()
const QString& DeviceAPI::getSamplingDeviceId () const inline
Definition at line 120 of file deviceapi.h.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { return m_samplingDeviceId; }
getSamplingDeviceInputMessageQueue()
MessageQueue * DeviceAPI::getSamplingDeviceInputMessageQueue ()
Sampling device (ex: single Rx) input message queue.
Definition at line 329 of file deviceapi.cpp.
References DeviceSampleSink::getInputMessageQueue(), DeviceSampleSource::getInputMessageQueue(), DeviceSampleMIMO::getInputMessageQueue(), DSPDeviceMIMOEngine::getMIMO(), DSPDeviceSinkEngine::getSink(), DSPDeviceSourceEngine::getSource(), m_deviceMIMOEngine, m_deviceSinkEngine, and m_deviceSourceEngine.
Referenced by HackRFOutput::applySettings(), and HackRFInput::applySettings().
 {
     if (m_deviceSourceEngine) {
         return m_deviceSourceEngine->getSource()->getInputMessageQueue();
     } else if (m_deviceSinkEngine) {
         return m_deviceSinkEngine->getSink()->getInputMessageQueue();
     } else if (m_deviceMIMOEngine) {
         return m_deviceMIMOEngine->getMIMO()->getInputMessageQueue();
     } else {
         return nullptr;
     }
 }
getSamplingDevicePluginInstanceGUI()
PluginInstanceGUI* DeviceAPI::getSamplingDevicePluginInstanceGUI () inline
Definition at line 134 of file deviceapi.h.
Referenced by MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { return m_samplingDevicePluginInstanceUI; }
getSamplingDeviceSequence()
uint32_t DeviceAPI::getSamplingDeviceSequence () const inline
Definition at line 123 of file deviceapi.h.
Referenced by WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), AirspyInput::openDevice(), FCDProPlusInput::openDevice(), FCDProInput::openDevice(), SoapySDROutput::openDevice(), SDRPlayInput::openDevice(), and SoapySDRInput::openDevice().
 { return m_samplingDeviceSequence; }
getSamplingDeviceSerial()
const QString& DeviceAPI::getSamplingDeviceSerial () const inline
Definition at line 121 of file deviceapi.h.
Referenced by addSinkBuddy(), addSourceBuddy(), MainCore::changeSampleSink(), MainCore::changeSampleSource(), WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), PlutoSDROutput::openDevice(), Bladerf1Output::openDevice(), HackRFOutput::openDevice(), Bladerf1Input::openDevice(), PerseusInput::openDevice(), AirspyHFInput::openDevice(), BladeRF2Output::openDevice(), PlutoSDRInput::openDevice(), RTLSDRInput::openDevice(), HackRFInput::openDevice(), BladeRF2Input::openDevice(), XTRXOutput::openDevice(), LimeSDROutput::openDevice(), XTRXInput::openDevice(), LimeSDRInput::openDevice(), removeSinkBuddy(), removeSourceBuddy(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { return m_samplingDeviceSerial; }
getSinkBuddies()
const std::vector<DeviceAPI*>& DeviceAPI::getSinkBuddies () const inline
Definition at line 166 of file deviceapi.h.
Referenced by Bladerf1Input::applySettings(), BladeRF2Output::applySettings(), PlutoSDRInput::applySettings(), HackRFInput::applySettings(), SoapySDROutput::applySettings(), BladeRF2Input::applySettings(), SoapySDRInput::applySettings(), XTRXOutput::applySettings(), LimeSDROutput::applySettings(), LimeSDRInput::applySettings(), Bladerf1Input::closeDevice(), PlutoSDRInput::closeDevice(), BladeRF2Output::closeDevice(), HackRFInput::closeDevice(), SoapySDROutput::closeDevice(), BladeRF2Input::closeDevice(), SoapySDRInput::closeDevice(), XTRXOutput::closeDevice(), LimeSDROutput::closeDevice(), XTRXInput::closeDevice(), LimeSDRInput::closeDevice(), BladeRF2Output::findThread(), SoapySDROutput::findThread(), XTRXOutput::findThread(), XTRXOutput::handleMessage(), LimeSDROutput::handleMessage(), XTRXInput::handleMessage(), LimeSDRInput::handleMessage(), BladeRF2Output::moveThreadToBuddy(), SoapySDROutput::moveThreadToBuddy(), XTRXOutput::moveThreadToBuddy(), Bladerf1Input::openDevice(), BladeRF2Output::openDevice(), PlutoSDRInput::openDevice(), HackRFInput::openDevice(), SoapySDROutput::openDevice(), BladeRF2Input::openDevice(), SoapySDRInput::openDevice(), XTRXOutput::openDevice(), LimeSDROutput::openDevice(), XTRXInput::openDevice(), LimeSDRInput::openDevice(), PlutoSDRInput::resumeBuddies(), LimeSDROutput::resumeTxBuddies(), LimeSDRInput::resumeTxBuddies(), XTRXInput::resumeTxThread(), BladeRF2Output::start(), SoapySDROutput::start(), XTRXOutput::start(), BladeRF2Output::stop(), SoapySDROutput::stop(), XTRXOutput::stop(), PlutoSDRInput::suspendBuddies(), LimeSDROutput::suspendTxBuddies(), LimeSDRInput::suspendTxBuddies(), and XTRXInput::suspendTxThread().
 { return m_sinkBuddies; }
getSourceBuddies()
const std::vector<DeviceAPI*>& DeviceAPI::getSourceBuddies () const inline
Definition at line 165 of file deviceapi.h.
Referenced by PlutoSDROutput::applySettings(), Bladerf1Output::applySettings(), HackRFOutput::applySettings(), BladeRF2Output::applySettings(), SoapySDROutput::applySettings(), BladeRF2Input::applySettings(), SoapySDRInput::applySettings(), XTRXOutput::applySettings(), LimeSDROutput::applySettings(), LimeSDRInput::applySettings(), PlutoSDROutput::closeDevice(), Bladerf1Output::closeDevice(), HackRFOutput::closeDevice(), BladeRF2Output::closeDevice(), SoapySDROutput::closeDevice(), BladeRF2Input::closeDevice(), SoapySDRInput::closeDevice(), XTRXOutput::closeDevice(), LimeSDROutput::closeDevice(), XTRXInput::closeDevice(), LimeSDRInput::closeDevice(), BladeRF2Input::findThread(), SoapySDRInput::findThread(), XTRXInput::findThread(), XTRXOutput::handleMessage(), LimeSDROutput::handleMessage(), XTRXInput::handleMessage(), LimeSDRInput::handleMessage(), BladeRF2Input::moveThreadToBuddy(), SoapySDRInput::moveThreadToBuddy(), XTRXInput::moveThreadToBuddy(), PlutoSDROutput::openDevice(), Bladerf1Output::openDevice(), HackRFOutput::openDevice(), BladeRF2Output::openDevice(), SoapySDROutput::openDevice(), BladeRF2Input::openDevice(), SoapySDRInput::openDevice(), XTRXOutput::openDevice(), LimeSDROutput::openDevice(), XTRXInput::openDevice(), LimeSDRInput::openDevice(), PlutoSDROutput::resumeBuddies(), LimeSDROutput::resumeRxBuddies(), LimeSDRInput::resumeRxBuddies(), XTRXOutput::resumeRxThread(), BladeRF2Input::start(), SoapySDRInput::start(), XTRXInput::start(), BladeRF2Input::stop(), SoapySDRInput::stop(), XTRXInput::stop(), PlutoSDROutput::suspendBuddies(), LimeSDROutput::suspendRxBuddies(), LimeSDRInput::suspendRxBuddies(), and XTRXOutput::suspendRxThread().
 { return m_sourceBuddies; }
initDeviceEngine()
bool DeviceAPI::initDeviceEngine ()
Init the device engine corresponding to the stream type.
Definition at line 240 of file deviceapi.cpp.
References DSPDeviceSourceEngine::initAcquisition(), DSPDeviceSinkEngine::initGeneration(), DSPDeviceMIMOEngine::initProcess(), m_deviceMIMOEngine, m_deviceSinkEngine, and m_deviceSourceEngine.
Referenced by PlutoSDROutput::handleMessage(), Bladerf1Output::handleMessage(), HackRFOutput::handleMessage(), TestSourceInput::handleMessage(), PerseusInput::handleMessage(), RTLSDRInput::handleMessage(), AirspyInput::handleMessage(), AirspyHFInput::handleMessage(), PlutoSDRInput::handleMessage(), Bladerf1Input::handleMessage(), LocalOutput::handleMessage(), TestMI::handleMessage(), FCDProInput::handleMessage(), FCDProPlusInput::handleMessage(), BladeRF2Output::handleMessage(), HackRFInput::handleMessage(), KiwiSDRInput::handleMessage(), SoapySDROutput::handleMessage(), LocalInput::handleMessage(), RemoteOutput::handleMessage(), SDRPlayInput::handleMessage(), BladeRF2Input::handleMessage(), SoapySDRInput::handleMessage(), FileSinkOutput::handleMessage(), XTRXOutput::handleMessage(), LimeSDROutput::handleMessage(), XTRXInput::handleMessage(), LimeSDRInput::handleMessage(), RemoteInput::handleMessage(), and FileInput::handleMessage().
 {
     if (m_deviceSourceEngine) {
         return m_deviceSourceEngine->initAcquisition();
     } else if (m_deviceSinkEngine) {
         return m_deviceSinkEngine->initGeneration();
     } else if (m_deviceMIMOEngine) {
         return m_deviceMIMOEngine->initProcess();
     } else {
         return false;
     }
 }
isBuddyLeader()
bool DeviceAPI::isBuddyLeader () const inline
Definition at line 163 of file deviceapi.h.
Referenced by clearBuddiesLists(), PlutoSDROutputGUI::updateStatus(), XTRXOutputGUI::updateStatus(), LimeSDROutputGUI::updateStatus(), PlutoSDRInputGui::updateStatus(), XTRXInputGUI::updateStatus(), and LimeSDRInputGUI::updateStatus().
 { return m_isBuddyLeader; }
loadSamplingDeviceSettings()
void DeviceAPI::loadSamplingDeviceSettings (const Preset * preset)
Definition at line 481 of file deviceapi.cpp.
References PluginInstanceGUI::deserialize(), DeviceSampleSink::deserialize(), DeviceSampleSource::deserialize(), Preset::findBestDeviceConfig(), Preset::getCenterFrequency(), Preset::getDescription(), Preset::getGroup(), DSPDeviceSinkEngine::getSink(), DSPDeviceSourceEngine::getSource(), Preset::isSourcePreset(), m_deviceSinkEngine, m_deviceSourceEngine, m_samplingDeviceId, m_samplingDevicePluginInstanceUI, m_samplingDeviceSequence, m_samplingDeviceSerial, PluginInstanceGUI::setCenterFrequency(), DeviceSampleSink::setCenterFrequency(), and DeviceSampleSource::setCenterFrequency().
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainCore::loadPresetSettings(), MainWindow::loadPresetSettings(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 {
     if (m_deviceSourceEngine && (preset->isSourcePreset()))
     {
         qDebug("DeviceAPI::loadSamplingDeviceSettings: Loading preset [%s | %s]", qPrintable(preset->getGroup()), qPrintable(preset->getDescription()));
         const QByteArray* sourceConfig = preset->findBestDeviceConfig(m_samplingDeviceId, m_samplingDeviceSerial, m_samplingDeviceSequence);
         qint64 centerFrequency = preset->getCenterFrequency();
         qDebug("DeviceAPI::loadSamplingDeviceSettings: center frequency: %llu Hz", centerFrequency);
         if (sourceConfig != 0)
         {
             qDebug("DeviceAPI::loadSamplingDeviceSettings: deserializing source %s[%d]: %s",
                 qPrintable(m_samplingDeviceId), m_samplingDeviceSequence, qPrintable(m_samplingDeviceSerial));
             if (m_samplingDevicePluginInstanceUI != 0) // GUI flavor
             {
                 m_samplingDevicePluginInstanceUI->deserialize(*sourceConfig);
             }
             else if (m_deviceSourceEngine->getSource() != 0) // Server flavor
             {
                 m_deviceSourceEngine->getSource()->deserialize(*sourceConfig);
             }
             else
             {
                 qDebug("DeviceAPI::loadSamplingDeviceSettings: deserializing no source");
             }
         }
         else
         {
             qDebug("DeviceAPI::loadSamplingDeviceSettings: source %s[%d]: %s not found",
                 qPrintable(m_samplingDeviceId), m_samplingDeviceSequence, qPrintable(m_samplingDeviceSerial));
         }
         // set center frequency anyway
         if (m_samplingDevicePluginInstanceUI != 0) // GUI flavor
         {
             m_samplingDevicePluginInstanceUI->setCenterFrequency(centerFrequency);
         }
         else if (m_deviceSourceEngine->getSource() != 0) // Server flavor
         {
             m_deviceSourceEngine->getSource()->setCenterFrequency(centerFrequency);
         }
         else
         {
             qDebug("DeviceAPI::loadSamplingDeviceSettings: no source");
         }
     }
     else if (m_deviceSinkEngine && (!preset->isSourcePreset())) // TODO: refine preset stream type
     {
         qDebug("DeviceAPI::loadSamplingDeviceSettings: Loading preset [%s | %s]", qPrintable(preset->getGroup()), qPrintable(preset->getDescription()));
         const QByteArray* sinkConfig = preset->findBestDeviceConfig(m_samplingDeviceId, m_samplingDeviceSerial, m_samplingDeviceSequence);
         qint64 centerFrequency = preset->getCenterFrequency();
         qDebug("DeviceAPI::loadSamplingDeviceSettings: center frequency: %llu Hz", centerFrequency);
         if (sinkConfig != 0)
         {
             qDebug("DeviceAPI::loadSamplingDeviceSettings: deserializing sink %s[%d]: %s",
                 qPrintable(m_samplingDeviceId), m_samplingDeviceSequence, qPrintable(m_samplingDeviceSerial));
             if (m_samplingDevicePluginInstanceUI != 0) // GUI flavor
             {
                 m_samplingDevicePluginInstanceUI->deserialize(*sinkConfig);
                 m_samplingDevicePluginInstanceUI->setCenterFrequency(centerFrequency);
             }
             else if (m_deviceSinkEngine->getSink() != 0) // Server flavor
             {
                 m_deviceSinkEngine->getSink()->deserialize(*sinkConfig);
                 m_deviceSinkEngine->getSink()->setCenterFrequency(centerFrequency);
             }
             else
             {
                 qDebug("DeviceAPI::loadSamplingDeviceSettings: no sink");
             }
         }
         else
         {
             qDebug("DeviceAPI::loadSamplingDeviceSettings: sink %s[%d]: %s not found",
                 qPrintable(m_samplingDeviceId), m_samplingDeviceSequence, qPrintable(m_samplingDeviceSerial));
         }
     }
     else
     {
         qDebug("DeviceAPI::loadSamplingDeviceSettings: Loading preset [%s | %s] is not a suitable preset", qPrintable(preset->getGroup()), qPrintable(preset->getDescription()));
     }
 }
removeAncillarySink()
void DeviceAPI::removeAncillarySink (BasebandSampleSink * sink, unsigned int index = 0)
Removes it.
Definition at line 100 of file deviceapi.cpp.
References m_deviceMIMOEngine, m_deviceSinkEngine, m_deviceSourceEngine, DSPDeviceMIMOEngine::removeAncillarySink(), DSPDeviceSourceEngine::removeSink(), and DSPDeviceSinkEngine::removeSpectrumSink().
Referenced by AirspyHFInput::~AirspyHFInput(), AirspyInput::~AirspyInput(), Bladerf1Input::~Bladerf1Input(), BladeRF2Input::~BladeRF2Input(), FCDProInput::~FCDProInput(), FCDProPlusInput::~FCDProPlusInput(), HackRFInput::~HackRFInput(), KiwiSDRInput::~KiwiSDRInput(), LimeSDRInput::~LimeSDRInput(), LocalInput::~LocalInput(), PerseusInput::~PerseusInput(), PlutoSDRInput::~PlutoSDRInput(), RemoteInput::~RemoteInput(), RTLSDRInput::~RTLSDRInput(), SDRPlayInput::~SDRPlayInput(), SoapySDRInput::~SoapySDRInput(), TestMI::~TestMI(), TestSourceInput::~TestSourceInput(), and XTRXInput::~XTRXInput().
 {
     if (m_deviceSourceEngine) {
         m_deviceSourceEngine->removeSink(sink);
     } else if (m_deviceSinkEngine) {
         m_deviceSinkEngine->removeSpectrumSink(sink);
     } else if (m_deviceMIMOEngine) {
         m_deviceMIMOEngine->removeAncillarySink(sink, index);
     }
 }
removeChannelSink()
void DeviceAPI::removeChannelSink (ThreadedBasebandSampleSink * sink, int streamIndex = 0)
Remove a channel sink (Rx)
Definition at line 127 of file deviceapi.cpp.
References m_deviceMIMOEngine, m_deviceSourceEngine, DSPDeviceMIMOEngine::removeChannelSink(), and DSPDeviceSourceEngine::removeThreadedSink().
Referenced by AMDemod::applySettings(), AMDemod::~AMDemod(), ATVDemod::~ATVDemod(), BFMDemod::~BFMDemod(), ChannelAnalyzer::~ChannelAnalyzer(), DATVDemod::~DATVDemod(), DSDDemod::~DSDDemod(), FreeDVDemod::~FreeDVDemod(), FreqTracker::~FreqTracker(), LocalSink::~LocalSink(), LoRaDemod::~LoRaDemod(), NFMDemod::~NFMDemod(), RemoteSink::~RemoteSink(), SSBDemod::~SSBDemod(), UDPSink::~UDPSink(), and WFMDemod::~WFMDemod().
 {
     (void) streamIndex;
     if (m_deviceSourceEngine) {
         m_deviceSourceEngine->removeThreadedSink(sink);
     } else if (m_deviceMIMOEngine) {
         m_deviceMIMOEngine->removeChannelSink(sink, streamIndex);
     }
 }
removeChannelSinkAPI()
void DeviceAPI::removeChannelSinkAPI (ChannelAPI * channelAPI, int streamIndex = 0)
Definition at line 163 of file deviceapi.cpp.
References m_channelSinkAPIs, renumerateChannels(), and ChannelAPI::setIndexInDeviceSet().
Referenced by AMDemod::applySettings(), AMDemod::~AMDemod(), ATVDemod::~ATVDemod(), BFMDemod::~BFMDemod(), ChannelAnalyzer::~ChannelAnalyzer(), DATVDemod::~DATVDemod(), DSDDemod::~DSDDemod(), FreeDVDemod::~FreeDVDemod(), FreqTracker::~FreqTracker(), LocalSink::~LocalSink(), LoRaDemod::~LoRaDemod(), NFMDemod::~NFMDemod(), RemoteSink::~RemoteSink(), SSBDemod::~SSBDemod(), UDPSink::~UDPSink(), and WFMDemod::~WFMDemod().
 {
     (void) streamIndex;
     if (m_channelSinkAPIs.removeOne(channelAPI)) {
         renumerateChannels();
     }
     channelAPI->setIndexInDeviceSet(-1);
 }
removeChannelSource()
void DeviceAPI::removeChannelSource (ThreadedBasebandSampleSource * sink, int streamIndex = 0)
Remove a channel source (Tx)
Definition at line 147 of file deviceapi.cpp.
References m_deviceSinkEngine, and DSPDeviceSinkEngine::removeThreadedSource().
Referenced by AMMod::~AMMod(), ATVMod::~ATVMod(), FileSource::~FileSource(), FreeDVMod::~FreeDVMod(), LocalSource::~LocalSource(), NFMMod::~NFMMod(), RemoteSource::~RemoteSource(), SSBMod::~SSBMod(), UDPSource::~UDPSource(), and WFMMod::~WFMMod().
 {
     (void) streamIndex;
     if (m_deviceSinkEngine) {
         m_deviceSinkEngine->removeThreadedSource(source);
     }
 }
removeChannelSourceAPI()
void DeviceAPI::removeChannelSourceAPI (ChannelAPI * channelAPI, int streamIndex = 0)
Definition at line 181 of file deviceapi.cpp.
References m_channelSourceAPIs, renumerateChannels(), and ChannelAPI::setIndexInDeviceSet().
Referenced by AMMod::~AMMod(), ATVMod::~ATVMod(), FileSource::~FileSource(), FreeDVMod::~FreeDVMod(), LocalSource::~LocalSource(), NFMMod::~NFMMod(), RemoteSource::~RemoteSource(), SSBMod::~SSBMod(), UDPSource::~UDPSource(), and WFMMod::~WFMMod().
 {
     (void) streamIndex;
     if (m_channelSourceAPIs.removeOne(channelAPI)) {
         renumerateChannels();
     }
     channelAPI->setIndexInDeviceSet(-1);
 }
removeLastSinkStream()
void DeviceAPI::removeLastSinkStream ()
Definition at line 82 of file deviceapi.cpp.
References m_deviceMIMOEngine, and DSPDeviceMIMOEngine::removeLastSinkStream().
 {
     if (m_deviceMIMOEngine) {
         m_deviceMIMOEngine->removeLastSinkStream();
     }
 }
removeLastSourceStream()
void DeviceAPI::removeLastSourceStream ()
Definition at line 68 of file deviceapi.cpp.
References m_deviceMIMOEngine, and DSPDeviceMIMOEngine::removeLastSourceStream().
Referenced by TestMI::~TestMI().
 {
     if (m_deviceMIMOEngine) {
         m_deviceMIMOEngine->removeLastSourceStream();
     }
 }
removeSinkBuddy()
void DeviceAPI::removeSinkBuddy (DeviceAPI * buddy)
Definition at line 707 of file deviceapi.cpp.
References getHardwareId(), getSamplingDeviceSerial(), m_sinkBuddies, m_streamType, and StreamSingleTx.
 {
     if (buddy->m_streamType != StreamSingleTx)
     {
         qDebug("DeviceAPI::removeSinkBuddy: buddy %s(%s) is not of single Tx type",
                 qPrintable(buddy->getHardwareId()),
                 qPrintable(buddy->getSamplingDeviceSerial()));
         return;
     }
     std::vector<DeviceAPI*>::iterator it = m_sinkBuddies.begin();
     for (;it != m_sinkBuddies.end(); ++it)
     {
         if (*it == buddy)
         {
             qDebug("DeviceAPI::removeSinkBuddy: buddy %s(%s) [%llu] removed from the list of [%llu]",
                     qPrintable(buddy->getHardwareId()),
                     qPrintable(buddy->getSamplingDeviceSerial()),
                     (quint64) (*it),
                     (quint64) this);
             m_sinkBuddies.erase(it);
             return;
         }
     }
     qDebug("DeviceAPI::removeSourceBuddy: buddy %s(%s) [%llu] not found in the list of [%llu]",
             qPrintable(buddy->getHardwareId()),
             qPrintable(buddy->getSamplingDeviceSerial()),
             (quint64) buddy,
             (quint64) this);
 }
removeSourceBuddy()
void DeviceAPI::removeSourceBuddy (DeviceAPI * buddy)
Definition at line 674 of file deviceapi.cpp.
References getHardwareId(), getSamplingDeviceSerial(), m_sourceBuddies, m_streamType, and StreamSingleRx.
 {
     if (buddy->m_streamType != StreamSingleRx)
     {
         qDebug("DeviceAPI::removeSourceBuddy: buddy %s(%s) is not of single Rx type",
                 qPrintable(buddy->getHardwareId()),
                 qPrintable(buddy->getSamplingDeviceSerial()));
         return;
     }
     std::vector<DeviceAPI*>::iterator it = m_sourceBuddies.begin();
     for (;it != m_sourceBuddies.end(); ++it)
     {
         if (*it == buddy)
         {
             qDebug("DeviceAPI::removeSourceBuddy: buddy %s(%s) [%llu] removed from the list of [%llu]",
                     qPrintable(buddy->getHardwareId()),
                     qPrintable(buddy->getSamplingDeviceSerial()),
                     (quint64) (*it),
                     (quint64) this);
             m_sourceBuddies.erase(it);
             return;
         }
     }
     qDebug("DeviceAPI::removeSourceBuddy: buddy %s(%s) [%llu] not found in the list of [%llu]",
             qPrintable(buddy->getHardwareId()),
             qPrintable(buddy->getSamplingDeviceSerial()),
             (quint64) buddy,
             (quint64) this);
 }
renumerateChannels()
void DeviceAPI::renumerateChannels () private
Definition at line 773 of file deviceapi.cpp.
References i, m_channelSinkAPIs, m_channelSourceAPIs, m_deviceTabIndex, m_streamType, StreamSingleRx, and StreamSingleTx.
Referenced by addChannelSinkAPI(), addChannelSourceAPI(), removeChannelSinkAPI(), and removeChannelSourceAPI().
 {
     if (m_streamType == StreamSingleRx)
     {
         for (int i = 0; i < m_channelSinkAPIs.size(); ++i)
         {
             m_channelSinkAPIs.at(i)->setIndexInDeviceSet(i);
             m_channelSinkAPIs.at(i)->setDeviceSetIndex(m_deviceTabIndex);
             m_channelSinkAPIs.at(i)->setDeviceAPI(this);
         }
     }
     else if (m_streamType == StreamSingleTx)
     {
         for (int i = 0; i < m_channelSourceAPIs.size(); ++i)
         {
             m_channelSourceAPIs.at(i)->setIndexInDeviceSet(i);
             m_channelSourceAPIs.at(i)->setDeviceSetIndex(m_deviceTabIndex);
             m_channelSourceAPIs.at(i)->setDeviceAPI(this);
         }
     }
 }
resetSamplingDeviceId()
void DeviceAPI::resetSamplingDeviceId () inline
Definition at line 111 of file deviceapi.h.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { m_samplingDeviceId.clear(); }
saveSamplingDeviceSettings()
void DeviceAPI::saveSamplingDeviceSettings (Preset * preset)
Definition at line 569 of file deviceapi.cpp.
References Preset::addOrUpdateDeviceConfig(), PluginInstanceGUI::getCenterFrequency(), DeviceSampleSink::getCenterFrequency(), DeviceSampleSource::getCenterFrequency(), DSPDeviceSinkEngine::getSink(), DSPDeviceSourceEngine::getSource(), Preset::isSourcePreset(), m_deviceSinkEngine, m_deviceSourceEngine, m_samplingDeviceId, m_samplingDevicePluginInstanceUI, m_samplingDeviceSequence, m_samplingDeviceSerial, PluginInstanceGUI::serialize(), DeviceSampleSink::serialize(), DeviceSampleSource::serialize(), and Preset::setCenterFrequency().
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), MainWindow::sampleSourceChanged(), MainCore::savePresetSettings(), and MainWindow::savePresetSettings().
 {
     if (m_deviceSourceEngine && (preset->isSourcePreset()))
     {
         qDebug("DeviceAPI::saveSamplingDeviceSettings: serializing source %s[%d]: %s",
             qPrintable(m_samplingDeviceId), m_samplingDeviceSequence, qPrintable(m_samplingDeviceSerial));
         if (m_samplingDevicePluginInstanceUI != 0)
         {
             preset->addOrUpdateDeviceConfig(m_samplingDeviceId, m_samplingDeviceSerial, m_samplingDeviceSequence, m_samplingDevicePluginInstanceUI->serialize());
             preset->setCenterFrequency(m_samplingDevicePluginInstanceUI->getCenterFrequency());
         }
         else if (m_deviceSourceEngine->getSource() != 0)
         {
             preset->addOrUpdateDeviceConfig(m_samplingDeviceId, m_samplingDeviceSerial, m_samplingDeviceSequence, m_deviceSourceEngine->getSource()->serialize());
             preset->setCenterFrequency(m_deviceSourceEngine->getSource()->getCenterFrequency());
         }
         else
         {
             qDebug("DeviceAPI::saveSamplingDeviceSettings: no source");
         }
     }
     else if (m_deviceSinkEngine && (!preset->isSourcePreset())) // TODO: refine preset stream type
     {
         qDebug("DeviceAPI::saveSamplingDeviceSettings: serializing sink %s[%d]: %s",
             qPrintable(m_samplingDeviceId), m_samplingDeviceSequence, qPrintable(m_samplingDeviceSerial));
         if (m_samplingDevicePluginInstanceUI != 0) // GUI flavor
         {
             preset->addOrUpdateDeviceConfig(m_samplingDeviceId, m_samplingDeviceSerial, m_samplingDeviceSequence, m_deviceSinkEngine->getSink()->serialize());
             preset->setCenterFrequency(m_deviceSinkEngine->getSink()->getCenterFrequency());
         }
         else if (m_deviceSinkEngine->getSink() != 0) // Server flavor
         {
             preset->addOrUpdateDeviceConfig(m_samplingDeviceId, m_samplingDeviceSerial, m_samplingDeviceSequence, m_deviceSinkEngine->getSink()->serialize());
             preset->setCenterFrequency(m_deviceSinkEngine->getSink()->getCenterFrequency());
         }
         else
         {
             qDebug("DeviceAPI::saveSamplingDeviceSettings: no sink");
         }
     }
     else
     {
         qDebug("DeviceAPI::saveSamplingDeviceSettings: not a suitable preset");
     }
 }
setBuddyLeader()
void DeviceAPI::setBuddyLeader (bool isBuddyLeader) inline
Definition at line 164 of file deviceapi.h.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { m_isBuddyLeader = isBuddyLeader; }
setBuddySharedPtr()
void DeviceAPI::setBuddySharedPtr (void * ptr) inline
Definition at line 162 of file deviceapi.h.
Referenced by PlutoSDROutput::openDevice(), BladeRF2Output::openDevice(), PlutoSDRInput::openDevice(), SoapySDROutput::openDevice(), BladeRF2Input::openDevice(), SoapySDRInput::openDevice(), XTRXOutput::openDevice(), LimeSDROutput::openDevice(), XTRXInput::openDevice(), LimeSDRInput::openDevice(), Bladerf1Input::~Bladerf1Input(), Bladerf1Output::~Bladerf1Output(), HackRFInput::~HackRFInput(), and HackRFOutput::~HackRFOutput().
 { m_buddySharedPtr = ptr; }
setDeviceItemIndex()
void DeviceAPI::setDeviceItemIndex (uint32_t index)
Definition at line 374 of file deviceapi.cpp.
References m_deviceItemIndex.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 {
     m_deviceItemIndex = index;
 }
setDeviceNbItems()
void DeviceAPI::setDeviceNbItems (uint32_t nbItems)
Definition at line 369 of file deviceapi.cpp.
References m_deviceNbItems.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 {
     m_deviceNbItems = nbItems;
 }
setHardwareId()
void DeviceAPI::setHardwareId (const QString & id)
Definition at line 364 of file deviceapi.cpp.
References m_hardwareId.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 {
     m_hardwareId = id;
 }
setHardwareUserArguments()
void DeviceAPI::setHardwareUserArguments (const QString & userArguments) inline
Definition at line 115 of file deviceapi.h.
Referenced by MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { m_hardwareUserArguments = userArguments; }
setNbSinkStreams()
void DeviceAPI::setNbSinkStreams (uint32_t nbSinkStreams) inline
Definition at line 169 of file deviceapi.h.
Referenced by RemoteOutput::RemoteOutput().
 { m_nbSinkStreams = nbSinkStreams; }
setNbSourceStreams()
void DeviceAPI::setNbSourceStreams (uint32_t nbSourceStreams) inline
Definition at line 168 of file deviceapi.h.
Referenced by AirspyHFInput::AirspyHFInput(), AirspyInput::AirspyInput(), and RTLSDRInput::RTLSDRInput().
 { m_nbSourceStreams = nbSourceStreams; }
setSampleMIMO()
void DeviceAPI::setSampleMIMO (DeviceSampleMIMO * mimo)
Set the device sample MIMO.
Definition at line 206 of file deviceapi.cpp.
References m_deviceMIMOEngine, and DSPDeviceMIMOEngine::setMIMO().
Referenced by MainWindow::sampleMIMOChanged().
 {
     if (m_deviceMIMOEngine) {
         m_deviceMIMOEngine->setMIMO(mimo);
     }
 }
setSampleSink()
void DeviceAPI::setSampleSink (DeviceSampleSink * sink)
Set the device sample sink (single Tx)
Definition at line 199 of file deviceapi.cpp.
References m_deviceSinkEngine, and DSPDeviceSinkEngine::setSink().
Referenced by MainCore::changeSampleSink(), and MainWindow::sampleSinkChanged().
 {
     if (m_deviceSinkEngine) {
         m_deviceSinkEngine->setSink(sink);
     }
 }
setSampleSource()
void DeviceAPI::setSampleSource (DeviceSampleSource * source)
Set the device sample source (single Rx)
Definition at line 192 of file deviceapi.cpp.
References m_deviceSourceEngine, and DSPDeviceSourceEngine::setSource().
Referenced by MainCore::changeSampleSource(), and MainWindow::sampleSourceChanged().
 {
     if (m_deviceSourceEngine) {
         m_deviceSourceEngine->setSource(source);
     }
 }
setSamplingDeviceDisplayName()
void DeviceAPI::setSamplingDeviceDisplayName (const QString & name) inline
Definition at line 113 of file deviceapi.h.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { m_samplingDeviceDisplayName = name; }
setSamplingDeviceId()
void DeviceAPI::setSamplingDeviceId (const QString & id) inline
Definition at line 110 of file deviceapi.h.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { m_samplingDeviceId = id; }
setSamplingDevicePluginInstanceGUI()
void DeviceAPI::setSamplingDevicePluginInstanceGUI (PluginInstanceGUI * gui)
Definition at line 384 of file deviceapi.cpp.
References m_samplingDevicePluginInstanceUI.
Referenced by MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 {
     m_samplingDevicePluginInstanceUI = gui;
 }
setSamplingDevicePluginInterface()
void DeviceAPI::setSamplingDevicePluginInterface (PluginInterface * iface)
Definition at line 379 of file deviceapi.cpp.
References m_pluginInterface.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 {
      m_pluginInterface = iface;
 }
setSamplingDeviceSequence()
void DeviceAPI::setSamplingDeviceSequence (int sequence) inline
Definition at line 114 of file deviceapi.h.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { m_samplingDeviceSequence = sequence; }
setSamplingDeviceSerial()
void DeviceAPI::setSamplingDeviceSerial (const QString & serial) inline
Definition at line 112 of file deviceapi.h.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { m_samplingDeviceSerial = serial; }
setSpectrumSinkInput()
void DeviceAPI::setSpectrumSinkInput (bool sourceElseSink = true, unsigned int index = 0)
Used in the MIMO case to select which stream is used as input to main spectrum.
Definition at line 111 of file deviceapi.cpp.
References m_deviceMIMOEngine, and DSPDeviceMIMOEngine::setSpectrumSinkInput().
Referenced by TestMIGui::on_spectrumSource_currentIndexChanged(), and TestMIGui::on_streamIndex_currentIndexChanged().
 {
     if (m_deviceMIMOEngine) { // In practice this is only used in the MIMO case
         m_deviceMIMOEngine->setSpectrumSinkInput(sourceElseSink, index);
     }
 }
startDeviceEngine()
bool DeviceAPI::startDeviceEngine ()
Start the device engine corresponding to the stream type.
Definition at line 253 of file deviceapi.cpp.
References m_deviceMIMOEngine, m_deviceSinkEngine, m_deviceSourceEngine, DSPDeviceSourceEngine::startAcquisition(), DSPDeviceSinkEngine::startGeneration(), and DSPDeviceMIMOEngine::startProcess().
Referenced by PlutoSDROutput::handleMessage(), Bladerf1Output::handleMessage(), HackRFOutput::handleMessage(), TestSourceInput::handleMessage(), PerseusInput::handleMessage(), RTLSDRInput::handleMessage(), AirspyInput::handleMessage(), AirspyHFInput::handleMessage(), PlutoSDRInput::handleMessage(), Bladerf1Input::handleMessage(), LocalOutput::handleMessage(), TestMI::handleMessage(), FCDProInput::handleMessage(), FCDProPlusInput::handleMessage(), BladeRF2Output::handleMessage(), HackRFInput::handleMessage(), KiwiSDRInput::handleMessage(), SoapySDROutput::handleMessage(), LocalInput::handleMessage(), RemoteOutput::handleMessage(), SDRPlayInput::handleMessage(), BladeRF2Input::handleMessage(), SoapySDRInput::handleMessage(), FileSinkOutput::handleMessage(), XTRXOutput::handleMessage(), LimeSDROutput::handleMessage(), XTRXInput::handleMessage(), LimeSDRInput::handleMessage(), RemoteInput::handleMessage(), and FileInput::handleMessage().
 {
     if (m_deviceSourceEngine) {
         return m_deviceSourceEngine->startAcquisition();
     } else if (m_deviceSinkEngine) {
         return m_deviceSinkEngine->startGeneration();
     } else if (m_deviceMIMOEngine) {
         return m_deviceMIMOEngine->startProcess();
     } else {
         return false;
     }
 }
state()
DeviceAPI::EngineState DeviceAPI::state () const
Return the state of the device engine corresponding to the stream type.
Definition at line 277 of file deviceapi.cpp.
References m_deviceMIMOEngine, m_deviceSinkEngine, m_deviceSourceEngine, DSPDeviceSourceEngine::state(), DSPDeviceSinkEngine::state(), DSPDeviceMIMOEngine::state(), and StError.
Referenced by SDRPlayGui::updateStatus(), KiwiSDRGui::updateStatus(), Bladerf1OutputGui::updateStatus(), BladeRF2OutputGui::updateStatus(), PerseusGui::updateStatus(), LocalOutputGui::updateStatus(), FCDProPlusGui::updateStatus(), FileSinkGui::updateStatus(), Bladerf1InputGui::updateStatus(), PlutoSDROutputGUI::updateStatus(), AirspyGui::updateStatus(), AirspyHFGui::updateStatus(), BladeRF2InputGui::updateStatus(), FileInputGUI::updateStatus(), XTRXOutputGUI::updateStatus(), TestSourceGui::updateStatus(), RTLSDRGui::updateStatus(), HackRFOutputGui::updateStatus(), LimeSDROutputGUI::updateStatus(), PlutoSDRInputGui::updateStatus(), HackRFInputGui::updateStatus(), FCDProGui::updateStatus(), XTRXInputGUI::updateStatus(), TestMIGui::updateStatus(), LimeSDRInputGUI::updateStatus(), LocalInputGui::updateStatus(), RemoteInputGui::updateStatus(), SoapySDROutputGui::updateStatus(), SoapySDRInputGui::updateStatus(), and RemoteOutputSinkGui::updateStatus().
 {
     if (m_deviceSourceEngine) {
         return (DeviceAPI::EngineState) m_deviceSourceEngine->state();
     } else if (m_deviceSinkEngine) {
         return (DeviceAPI::EngineState) m_deviceSinkEngine->state();
     } else if (m_deviceMIMOEngine) {
         return (DeviceAPI::EngineState) m_deviceMIMOEngine->state();
     } else {
         return StError;
     }
 }
stopDeviceEngine()
void DeviceAPI::stopDeviceEngine ()
Stop the device engine corresponding to the stream type.
Definition at line 266 of file deviceapi.cpp.
References m_deviceMIMOEngine, m_deviceSinkEngine, m_deviceSourceEngine, DSPDeviceSourceEngine::stopAcquistion(), DSPDeviceSinkEngine::stopGeneration(), and DSPDeviceMIMOEngine::stopProcess().
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), PlutoSDROutput::handleMessage(), Bladerf1Output::handleMessage(), HackRFOutput::handleMessage(), TestSourceInput::handleMessage(), PerseusInput::handleMessage(), RTLSDRInput::handleMessage(), AirspyInput::handleMessage(), AirspyHFInput::handleMessage(), PlutoSDRInput::handleMessage(), Bladerf1Input::handleMessage(), LocalOutput::handleMessage(), TestMI::handleMessage(), FCDProPlusInput::handleMessage(), FCDProInput::handleMessage(), BladeRF2Output::handleMessage(), HackRFInput::handleMessage(), KiwiSDRInput::handleMessage(), SoapySDROutput::handleMessage(), LocalInput::handleMessage(), RemoteOutput::handleMessage(), SDRPlayInput::handleMessage(), BladeRF2Input::handleMessage(), SoapySDRInput::handleMessage(), FileSinkOutput::handleMessage(), XTRXOutput::handleMessage(), LimeSDROutput::handleMessage(), XTRXInput::handleMessage(), LimeSDRInput::handleMessage(), RemoteInput::handleMessage(), FileInput::handleMessage(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 {
     if (m_deviceSourceEngine) {
         m_deviceSourceEngine->stopAcquistion();
     } else if (m_deviceSinkEngine) {
         m_deviceSinkEngine->stopGeneration();
     } else if (m_deviceMIMOEngine) {
         m_deviceMIMOEngine->stopProcess();
     }
 }
Member Data Documentation
m_buddySharedPtr
void* DeviceAPI::m_buddySharedPtr protected
Definition at line 198 of file deviceapi.h.
m_channelSinkAPIs
QList<ChannelAPI*> DeviceAPI::m_channelSinkAPIs protected
Definition at line 204 of file deviceapi.h.
Referenced by addChannelSinkAPI(), getChanelSinkAPIAt(), removeChannelSinkAPI(), and renumerateChannels().
m_channelSourceAPIs
QList<ChannelAPI*> DeviceAPI::m_channelSourceAPIs protected
Definition at line 209 of file deviceapi.h.
Referenced by addChannelSourceAPI(), getChanelSourceAPIAt(), removeChannelSourceAPI(), and renumerateChannels().
m_deviceItemIndex
uint32_t DeviceAPI::m_deviceItemIndex protected
The item index inb the Rx or Tx side of the physical device. Can be >0 for NxM devices (i.e. 0 or 1 for LimeSDR)
Definition at line 182 of file deviceapi.h.
Referenced by setDeviceItemIndex().
m_deviceMIMOEngine
DSPDeviceMIMOEngine* DeviceAPI::m_deviceMIMOEngine protected
Definition at line 213 of file deviceapi.h.
Referenced by addAncillarySink(), addChannelSink(), addSinkStream(), addSourceStream(), configureCorrections(), errorMessage(), getDeviceEngineInputMessageQueue(), getDeviceUID(), getSampleMIMO(), getSamplingDeviceGUIMessageQueue(), getSamplingDeviceInputMessageQueue(), initDeviceEngine(), removeAncillarySink(), removeChannelSink(), removeLastSinkStream(), removeLastSourceStream(), setSampleMIMO(), setSpectrumSinkInput(), startDeviceEngine(), state(), and stopDeviceEngine().
m_deviceNbItems
uint32_t DeviceAPI::m_deviceNbItems protected
Number of items in the physical device either Rx or Tx. Can be >1 for NxM devices (i.e. 2 for LimeSDR)
Definition at line 181 of file deviceapi.h.
Referenced by setDeviceNbItems().
m_deviceSinkEngine
DSPDeviceSinkEngine* DeviceAPI::m_deviceSinkEngine protected
Definition at line 208 of file deviceapi.h.
Referenced by addAncillarySink(), addChannelSource(), errorMessage(), getDeviceEngineInputMessageQueue(), getDeviceEngineStateStr(), getDeviceUID(), getSampleSink(), getSamplingDeviceGUIMessageQueue(), getSamplingDeviceInputMessageQueue(), initDeviceEngine(), loadSamplingDeviceSettings(), removeAncillarySink(), removeChannelSource(), saveSamplingDeviceSettings(), setSampleSink(), startDeviceEngine(), state(), and stopDeviceEngine().
m_deviceSourceEngine
DSPDeviceSourceEngine* DeviceAPI::m_deviceSourceEngine protected
Definition at line 203 of file deviceapi.h.
Referenced by addAncillarySink(), addChannelSink(), configureCorrections(), errorMessage(), getDeviceEngineInputMessageQueue(), getDeviceEngineStateStr(), getDeviceUID(), getSampleSource(), getSamplingDeviceGUIMessageQueue(), getSamplingDeviceInputMessageQueue(), initDeviceEngine(), loadSamplingDeviceSettings(), removeAncillarySink(), removeChannelSink(), saveSamplingDeviceSettings(), setSampleSource(), startDeviceEngine(), state(), and stopDeviceEngine().
m_deviceTabIndex
int DeviceAPI::m_deviceTabIndex protected
This is the tab index in the GUI and also the device set index.
Definition at line 179 of file deviceapi.h.
Referenced by renumerateChannels().
m_hardwareId
QString DeviceAPI::m_hardwareId protected
The internal id that identifies the type of hardware (i.e. HackRF, BladeRF, ...)
Definition at line 180 of file deviceapi.h.
Referenced by setHardwareId().
m_hardwareUserArguments
QString DeviceAPI::m_hardwareUserArguments protected
User given arguments to be used at hardware level i.e. for the hardware device and device sequence.
Definition at line 191 of file deviceapi.h.
m_isBuddyLeader
bool DeviceAPI::m_isBuddyLeader protected
Definition at line 199 of file deviceapi.h.
m_masterTimer
const QTimer& DeviceAPI::m_masterTimer protected
This is the DSPEngine master timer.
Definition at line 186 of file deviceapi.h.
m_nbSinkStreams
uint32_t DeviceAPI::m_nbSinkStreams protected
The number of sink streams in the logical device. 1 for Single Tx (SO) can be 0 or more for MIMO.
Definition at line 184 of file deviceapi.h.
m_nbSourceStreams
uint32_t DeviceAPI::m_nbSourceStreams protected
The number of source streams in the logical device. 1 for Single Rx (SI) can be 0 or more for MIMO.
Definition at line 183 of file deviceapi.h.
m_pluginInterface
PluginInterface* DeviceAPI::m_pluginInterface protected
Definition at line 185 of file deviceapi.h.
Referenced by setSamplingDevicePluginInterface().
m_samplingDeviceDisplayName
QString DeviceAPI::m_samplingDeviceDisplayName protected
The human readable name identifying this instance.
Definition at line 189 of file deviceapi.h.
m_samplingDeviceId
QString DeviceAPI::m_samplingDeviceId protected
The internal plugin ID corresponding to the device (i.e. for HackRF input, for HackRF output ...)
Definition at line 187 of file deviceapi.h.
Referenced by loadSamplingDeviceSettings(), and saveSamplingDeviceSettings().
m_samplingDevicePluginInstanceUI
PluginInstanceGUI* DeviceAPI::m_samplingDevicePluginInstanceUI protected
Definition at line 192 of file deviceapi.h.
Referenced by loadSamplingDeviceSettings(), saveSamplingDeviceSettings(), and setSamplingDevicePluginInstanceGUI().
m_samplingDeviceSequence
uint32_t DeviceAPI::m_samplingDeviceSequence protected
The device sequence. >0 when more than one device of the same type is connected.
Definition at line 190 of file deviceapi.h.
Referenced by loadSamplingDeviceSettings(), and saveSamplingDeviceSettings().
m_samplingDeviceSerial
QString DeviceAPI::m_samplingDeviceSerial protected
The device serial number defined by the vendor or a fake one (SDRplay)
Definition at line 188 of file deviceapi.h.
Referenced by loadSamplingDeviceSettings(), and saveSamplingDeviceSettings().
m_sinkBuddies
std::vector<DeviceAPI*> DeviceAPI::m_sinkBuddies protected
Device sink APIs referencing the same physical device.
Definition at line 197 of file deviceapi.h.
Referenced by addSinkBuddy(), addSourceBuddy(), clearBuddiesLists(), and removeSinkBuddy().
m_sourceBuddies
std::vector<DeviceAPI*> DeviceAPI::m_sourceBuddies protected
Device source APIs referencing the same physical device.
Definition at line 196 of file deviceapi.h.
Referenced by addSinkBuddy(), addSourceBuddy(), clearBuddiesLists(), and removeSourceBuddy().
m_streamType
StreamType DeviceAPI::m_streamType protected
Definition at line 178 of file deviceapi.h.
Referenced by addSinkBuddy(), addSourceBuddy(), getChanelSinkAPIAt(), getChanelSourceAPIAt(), removeSinkBuddy(), removeSourceBuddy(), and renumerateChannels().
The documentation for this class was generated from the following files:
sdrbase/device/deviceapi.h
sdrbase/device/deviceapi.cpp