SDRAngel: qtwebapp::HttpListener Class Reference
qtwebapp::HttpListener Class Reference
#include <httplistener.h>
Inherits QTcpServer.
Signals
void handleConnection (tSocketDescriptor socketDescriptor)
Public Member Functions
HttpListener (QSettings *settings, HttpRequestHandler *requestHandler, QObject *parent=NULL)
HttpListener (const HttpListenerSettings &settings, HttpRequestHandler *requestHandler, QObject *parent=NULL)
virtual ~HttpListener ()
void listen ()
void close ()
HttpListenerSettings getListenerSettings () const
void setListenerSettings (const HttpListenerSettings &settings)
Protected Member Functions
void incomingConnection (tSocketDescriptor socketDescriptor)
Private Attributes
QSettings * settings
HttpListenerSettings listenerSettings
HttpRequestHandler * requestHandler
HttpConnectionHandlerPool * pool
bool useQtSettings
Detailed Description
Listens for incoming TCP connections and and passes all incoming HTTP requests to your implementation of HttpRequestHandler, which processes the request and generates the response (usually a HTML document).
Example for the required settings in the config file:
;host=192.168.0.100
port=8080
minThreads=1
maxThreads=10
cleanupInterval=1000
readTimeout=60000
;sslKeyFile=ssl/my.key
;sslCertFile=ssl/my.cert
maxRequestSize=16000
maxMultiPartSize=1000000
The optional host parameter binds the listener to one network interface. The listener handles all network interfaces if no host is configured. The port number specifies the incoming TCP port that this listener listens to.
See also
HttpConnectionHandlerPool for description of config settings minThreads, maxThreads, cleanupInterval and ssl settings
HttpConnectionHandler for description of the readTimeout
HttpRequest for description of config settings maxRequestSize and maxMultiPartSize
Definition at line 47 of file httplistener.h.
Constructor & Destructor Documentation
HttpListener() [1/2]
HttpListener::HttpListener (QSettings * settings, HttpRequestHandler * requestHandler, QObject * parent = NULL)
Constructor. Creates a connection pool and starts listening on the configured host and port.
Parameters
settings Configuration settings for the HTTP server. Must not be 0.
requestHandler Processes each received HTTP request, usually by dispatching to controller classes.
parent Parent object.
Warning
Ensure to close or delete the listener before deleting the request handler.
Definition at line 14 of file httplistener.cpp.
References listen(), pool, requestHandler, and settings.
     : QTcpServer(parent), useQtSettings(true)
 {
     Q_ASSERT(settings != 0);
     Q_ASSERT(requestHandler != 0);
     pool = 0;
     this->settings = settings;
     this->requestHandler = requestHandler;
     // Reqister type of socketDescriptor for signal/slot handling
     qRegisterMetaType<tSocketDescriptor>("tSocketDescriptor");
     // Start listening
     listen();
 }
HttpListener() [2/2]
HttpListener::HttpListener (const HttpListenerSettings & settings, HttpRequestHandler * requestHandler, QObject * parent = NULL)
Constructor. Creates a connection pool and starts listening on the configured host and port.
Parameters
settings Configuration settings for the HTTP server as a structure.
requestHandler Processes each received HTTP request, usually by dispatching to controller classes.
parent Parent object.
Warning
Ensure to close or delete the listener before deleting the request handler.
Definition at line 28 of file httplistener.cpp.
References listen(), listenerSettings, pool, requestHandler, and settings.
     : QTcpServer(parent), useQtSettings(false)
 {
     Q_ASSERT(requestHandler != 0);
     pool = 0;
     this->settings = 0;
     listenerSettings = settings;
     this->requestHandler = requestHandler;
     // Reqister type of socketDescriptor for signal/slot handling
     qRegisterMetaType<tSocketDescriptor>("tSocketDescriptor");
     // Start listening
     listen();
 }
~HttpListener()
HttpListener::~HttpListener () virtual
Destructor
Definition at line 43 of file httplistener.cpp.
References close().
 {
     close();
     qDebug("HttpListener: destroyed");
 }
Member Function Documentation
close()
void HttpListener::close ()
Closes the listener, waits until all pending requests are processed, then closes the connection pool.
Definition at line 73 of file httplistener.cpp.
References pool.
Referenced by ~HttpListener().
{
     QTcpServer::close();
     qDebug("HttpListener: closed");
     if (pool) {
         delete pool;
         pool=NULL;
     }
 }
getListenerSettings()
HttpListenerSettings qtwebapp::HttpListener::getListenerSettings () const inline
Get a listener settings copy
Returns
The current listener settings
Definition at line 90 of file httplistener.h.
 { return listenerSettings; }
handleConnection
void qtwebapp::HttpListener::handleConnection (tSocketDescriptor socketDescriptor) signal
Sent to the connection handler to process a new incoming connection.
Parameters
socketDescriptor references the accepted connection.
incomingConnection()
void HttpListener::incomingConnection (tSocketDescriptor socketDescriptor) protected
Serves new incoming connection requests
Definition at line 82 of file httplistener.cpp.
References qtwebapp::HttpConnectionHandlerPool::getConnectionHandler(), and pool.
{
 #ifdef SUPERVERBOSE
     qDebug("HttpListener: New connection");
 #endif
     HttpConnectionHandler* freeHandler=NULL;
     if (pool)
     {
         freeHandler=pool->getConnectionHandler();
     }
     // Let the handler process the new connection.
     if (freeHandler)
     {
         // The descriptor is passed via event queue because the handler lives in another thread
         QMetaObject::invokeMethod(freeHandler, "handleConnection", Qt::QueuedConnection, Q_ARG(tSocketDescriptor, socketDescriptor));
     }
     else
     {
         // Reject the connection
         qDebug("HttpListener: Too many incoming connections");
         QTcpSocket* socket=new QTcpSocket(this);
         socket->setSocketDescriptor(socketDescriptor);
         connect(socket, SIGNAL(disconnected()), socket, SLOT(deleteLater()));
         socket->write("HTTP/1.1 503 too many connections\r\nConnection: close\r\n\r\nToo many connections\r\n");
         socket->disconnectFromHost();
     }
 }
listen()
void HttpListener::listen ()
Restart listeing after close().
Definition at line 50 of file httplistener.cpp.
References qtwebapp::HttpListenerSettings::host, listenerSettings, pool, qtwebapp::HttpListenerSettings::port, requestHandler, settings, and useQtSettings.
Referenced by HttpListener().
 {
     if (!pool)
     {
         if (useQtSettings) {
             pool = new HttpConnectionHandlerPool(settings, requestHandler);
         } else {
             pool = new HttpConnectionHandlerPool(&listenerSettings, requestHandler);
         }
     }
     QString host = useQtSettings ? settings->value("host").toString() : listenerSettings.host;
     int port = useQtSettings ? settings->value("port").toInt() : listenerSettings.port;
     QTcpServer::listen(host.isEmpty() ? QHostAddress::Any : QHostAddress(host), port);
     if (!isListening())
     {
         qCritical("HttpListener: Cannot bind on port %i: %s",port,qPrintable(errorString()));
     }
     else {
         qDebug("HttpListener: Listening on port %i",port);
     }
 }
setListenerSettings()
void qtwebapp::HttpListener::setListenerSettings (const HttpListenerSettings & settings) inline
Set new listener settings data
Parameters
Listener settings to replace current data
Definition at line 96 of file httplistener.h.
 { listenerSettings = settings; }
Member Data Documentation
listenerSettings
HttpListenerSettings qtwebapp::HttpListener::listenerSettings private
Configuration settings for the HTTP server as a structure
Definition at line 109 of file httplistener.h.
Referenced by HttpListener(), and listen().
pool
HttpConnectionHandlerPool* qtwebapp::HttpListener::pool private
Pool of connection handlers
Definition at line 115 of file httplistener.h.
Referenced by close(), HttpListener(), incomingConnection(), and listen().
requestHandler
HttpRequestHandler* qtwebapp::HttpListener::requestHandler private
Point to the reuqest handler which processes all HTTP requests
Definition at line 112 of file httplistener.h.
Referenced by HttpListener(), and listen().
settings
QSettings* qtwebapp::HttpListener::settings private
Configuration settings for the HTTP server
Definition at line 106 of file httplistener.h.
Referenced by HttpListener(), and listen().
useQtSettings
bool qtwebapp::HttpListener::useQtSettings private
Settings flag
Definition at line 118 of file httplistener.h.
Referenced by listen().
The documentation for this class was generated from the following files:
httpserver/httplistener.h
httpserver/httplistener.cpp