SDRAngel: SWGSDRangel::SWGChannelSettings Class Reference
SWGSDRangel::SWGChannelSettings Class Reference
#include <SWGChannelSettings.h>
Public Member Functions
SWGChannelSettings ()
SWGChannelSettings (QString *json)
virtual ~SWGChannelSettings ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGChannelSettings * fromJson (QString &jsonString) override
QString * getChannelType ()
void setChannelType (QString *channel_type)
qint32 getDirection ()
void setDirection (qint32 direction)
qint32 getOriginatorDeviceSetIndex ()
void setOriginatorDeviceSetIndex (qint32 originator_device_set_index)
qint32 getOriginatorChannelIndex ()
void setOriginatorChannelIndex (qint32 originator_channel_index)
SWGAMDemodSettings * getAmDemodSettings ()
void setAmDemodSettings (SWGAMDemodSettings *am_demod_settings)
SWGAMModSettings * getAmModSettings ()
void setAmModSettings (SWGAMModSettings *am_mod_settings)
SWGATVModSettings * getAtvModSettings ()
void setAtvModSettings (SWGATVModSettings *atv_mod_settings)
SWGBFMDemodSettings * getBfmDemodSettings ()
void setBfmDemodSettings (SWGBFMDemodSettings *bfm_demod_settings)
SWGDSDDemodSettings * getDsdDemodSettings ()
void setDsdDemodSettings (SWGDSDDemodSettings *dsd_demod_settings)
SWGFileSourceSettings * getFileSourceSettings ()
void setFileSourceSettings (SWGFileSourceSettings *file_source_settings)
SWGFreeDVDemodSettings * getFreeDvDemodSettings ()
void setFreeDvDemodSettings (SWGFreeDVDemodSettings *free_dv_demod_settings)
SWGFreeDVModSettings * getFreeDvModSettings ()
void setFreeDvModSettings (SWGFreeDVModSettings *free_dv_mod_settings)
SWGFreqTrackerSettings * getFreqTrackerSettings ()
void setFreqTrackerSettings (SWGFreqTrackerSettings *freq_tracker_settings)
SWGNFMDemodSettings * getNfmDemodSettings ()
void setNfmDemodSettings (SWGNFMDemodSettings *nfm_demod_settings)
SWGNFMModSettings * getNfmModSettings ()
void setNfmModSettings (SWGNFMModSettings *nfm_mod_settings)
SWGLocalSinkSettings * getLocalSinkSettings ()
void setLocalSinkSettings (SWGLocalSinkSettings *local_sink_settings)
SWGLocalSourceSettings * getLocalSourceSettings ()
void setLocalSourceSettings (SWGLocalSourceSettings *local_source_settings)
SWGRemoteSinkSettings * getRemoteSinkSettings ()
void setRemoteSinkSettings (SWGRemoteSinkSettings *remote_sink_settings)
SWGRemoteSourceSettings * getRemoteSourceSettings ()
void setRemoteSourceSettings (SWGRemoteSourceSettings *remote_source_settings)
SWGSSBModSettings * getSsbModSettings ()
void setSsbModSettings (SWGSSBModSettings *ssb_mod_settings)
SWGSSBDemodSettings * getSsbDemodSettings ()
void setSsbDemodSettings (SWGSSBDemodSettings *ssb_demod_settings)
SWGUDPSourceSettings * getUdpSourceSettings ()
void setUdpSourceSettings (SWGUDPSourceSettings *udp_source_settings)
SWGUDPSinkSettings * getUdpSinkSettings ()
void setUdpSinkSettings (SWGUDPSinkSettings *udp_sink_settings)
SWGWFMDemodSettings * getWfmDemodSettings ()
void setWfmDemodSettings (SWGWFMDemodSettings *wfm_demod_settings)
SWGWFMModSettings * getWfmModSettings ()
void setWfmModSettings (SWGWFMModSettings *wfm_mod_settings)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * channel_type
bool m_channel_type_isSet
qint32 direction
bool m_direction_isSet
qint32 originator_device_set_index
bool m_originator_device_set_index_isSet
qint32 originator_channel_index
bool m_originator_channel_index_isSet
SWGAMDemodSettings * am_demod_settings
bool m_am_demod_settings_isSet
SWGAMModSettings * am_mod_settings
bool m_am_mod_settings_isSet
SWGATVModSettings * atv_mod_settings
bool m_atv_mod_settings_isSet
SWGBFMDemodSettings * bfm_demod_settings
bool m_bfm_demod_settings_isSet
SWGDSDDemodSettings * dsd_demod_settings
bool m_dsd_demod_settings_isSet
SWGFileSourceSettings * file_source_settings
bool m_file_source_settings_isSet
SWGFreeDVDemodSettings * free_dv_demod_settings
bool m_free_dv_demod_settings_isSet
SWGFreeDVModSettings * free_dv_mod_settings
bool m_free_dv_mod_settings_isSet
SWGFreqTrackerSettings * freq_tracker_settings
bool m_freq_tracker_settings_isSet
SWGNFMDemodSettings * nfm_demod_settings
bool m_nfm_demod_settings_isSet
SWGNFMModSettings * nfm_mod_settings
bool m_nfm_mod_settings_isSet
SWGLocalSinkSettings * local_sink_settings
bool m_local_sink_settings_isSet
SWGLocalSourceSettings * local_source_settings
bool m_local_source_settings_isSet
SWGRemoteSinkSettings * remote_sink_settings
bool m_remote_sink_settings_isSet
SWGRemoteSourceSettings * remote_source_settings
bool m_remote_source_settings_isSet
SWGSSBModSettings * ssb_mod_settings
bool m_ssb_mod_settings_isSet
SWGSSBDemodSettings * ssb_demod_settings
bool m_ssb_demod_settings_isSet
SWGUDPSourceSettings * udp_source_settings
bool m_udp_source_settings_isSet
SWGUDPSinkSettings * udp_sink_settings
bool m_udp_sink_settings_isSet
SWGWFMDemodSettings * wfm_demod_settings
bool m_wfm_demod_settings_isSet
SWGWFMModSettings * wfm_mod_settings
bool m_wfm_mod_settings_isSet
Detailed Description
Definition at line 53 of file SWGChannelSettings.h.
Constructor & Destructor Documentation
SWGChannelSettings() [1/2]
SWGSDRangel::SWGChannelSettings::SWGChannelSettings ()
Definition at line 30 of file SWGChannelSettings.cpp.
References am_demod_settings, am_mod_settings, atv_mod_settings, bfm_demod_settings, channel_type, direction, dsd_demod_settings, file_source_settings, free_dv_demod_settings, free_dv_mod_settings, freq_tracker_settings, local_sink_settings, local_source_settings, m_am_demod_settings_isSet, m_am_mod_settings_isSet, m_atv_mod_settings_isSet, m_bfm_demod_settings_isSet, m_channel_type_isSet, m_direction_isSet, m_dsd_demod_settings_isSet, m_file_source_settings_isSet, m_free_dv_demod_settings_isSet, m_free_dv_mod_settings_isSet, m_freq_tracker_settings_isSet, m_local_sink_settings_isSet, m_local_source_settings_isSet, m_nfm_demod_settings_isSet, m_nfm_mod_settings_isSet, m_originator_channel_index_isSet, m_originator_device_set_index_isSet, m_remote_sink_settings_isSet, m_remote_source_settings_isSet, m_ssb_demod_settings_isSet, m_ssb_mod_settings_isSet, m_udp_sink_settings_isSet, m_udp_source_settings_isSet, m_wfm_demod_settings_isSet, m_wfm_mod_settings_isSet, nfm_demod_settings, nfm_mod_settings, originator_channel_index, originator_device_set_index, remote_sink_settings, remote_source_settings, ssb_demod_settings, ssb_mod_settings, udp_sink_settings, udp_source_settings, wfm_demod_settings, and wfm_mod_settings.
{
     channel_type = nullptr;
     m_channel_type_isSet = false;
     direction = 0;
     m_direction_isSet = false;
     originator_device_set_index = 0;
     m_originator_device_set_index_isSet = false;
     originator_channel_index = 0;
     m_originator_channel_index_isSet = false;
     am_demod_settings = nullptr;
     m_am_demod_settings_isSet = false;
     am_mod_settings = nullptr;
     m_am_mod_settings_isSet = false;
     atv_mod_settings = nullptr;
     m_atv_mod_settings_isSet = false;
     bfm_demod_settings = nullptr;
     m_bfm_demod_settings_isSet = false;
     dsd_demod_settings = nullptr;
     m_dsd_demod_settings_isSet = false;
     file_source_settings = nullptr;
     m_file_source_settings_isSet = false;
     free_dv_demod_settings = nullptr;
     m_free_dv_demod_settings_isSet = false;
     free_dv_mod_settings = nullptr;
     m_free_dv_mod_settings_isSet = false;
     freq_tracker_settings = nullptr;
     m_freq_tracker_settings_isSet = false;
     nfm_demod_settings = nullptr;
     m_nfm_demod_settings_isSet = false;
     nfm_mod_settings = nullptr;
     m_nfm_mod_settings_isSet = false;
     local_sink_settings = nullptr;
     m_local_sink_settings_isSet = false;
     local_source_settings = nullptr;
     m_local_source_settings_isSet = false;
     remote_sink_settings = nullptr;
     m_remote_sink_settings_isSet = false;
     remote_source_settings = nullptr;
     m_remote_source_settings_isSet = false;
     ssb_mod_settings = nullptr;
     m_ssb_mod_settings_isSet = false;
     ssb_demod_settings = nullptr;
     m_ssb_demod_settings_isSet = false;
     udp_source_settings = nullptr;
     m_udp_source_settings_isSet = false;
     udp_sink_settings = nullptr;
     m_udp_sink_settings_isSet = false;
     wfm_demod_settings = nullptr;
     m_wfm_demod_settings_isSet = false;
     wfm_mod_settings = nullptr;
     m_wfm_mod_settings_isSet = false;
 }
SWGChannelSettings() [2/2]
SWGSDRangel::SWGChannelSettings::SWGChannelSettings (QString * json)
Definition at line 25 of file SWGChannelSettings.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGChannelSettings()
SWGSDRangel::SWGChannelSettings::~SWGChannelSettings () virtual
Definition at line 83 of file SWGChannelSettings.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGChannelSettings::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 278 of file SWGChannelSettings.cpp.
References asJsonObject().
Referenced by SWGSDRangel::SWGDeviceSetApi::devicesetChannelPost(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPatch(), SWGSDRangel::SWGDeviceSetApi::devicesetChannelSettingsPut(), WebAPIRequestMapper::devicesetChannelSettingsService(), WFMMod::webapiReverseSendCWSettings(), AMMod::webapiReverseSendCWSettings(), NFMMod::webapiReverseSendCWSettings(), FreeDVMod::webapiReverseSendCWSettings(), SSBMod::webapiReverseSendCWSettings(), LocalSink::webapiReverseSendSettings(), LocalSource::webapiReverseSendSettings(), RemoteSink::webapiReverseSendSettings(), WFMDemod::webapiReverseSendSettings(), AMDemod::webapiReverseSendSettings(), FreqTracker::webapiReverseSendSettings(), UDPSink::webapiReverseSendSettings(), RemoteSource::webapiReverseSendSettings(), UDPSource::webapiReverseSendSettings(), NFMDemod::webapiReverseSendSettings(), DSDDemod::webapiReverseSendSettings(), BFMDemod::webapiReverseSendSettings(), WFMMod::webapiReverseSendSettings(), AMMod::webapiReverseSendSettings(), SSBDemod::webapiReverseSendSettings(), NFMMod::webapiReverseSendSettings(), FreeDVMod::webapiReverseSendSettings(), SSBMod::webapiReverseSendSettings(), FreeDVDemod::webapiReverseSendSettings(), FileSource::webapiReverseSendSettings(), and ATVMod::webapiReverseSendSettings().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGChannelSettings::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 289 of file SWGChannelSettings.cpp.
References am_demod_settings, am_mod_settings, atv_mod_settings, bfm_demod_settings, channel_type, direction, dsd_demod_settings, file_source_settings, free_dv_demod_settings, free_dv_mod_settings, freq_tracker_settings, SWGSDRangel::SWGRemoteSourceSettings::isSet(), SWGSDRangel::SWGLocalSinkSettings::isSet(), SWGSDRangel::SWGLocalSourceSettings::isSet(), SWGSDRangel::SWGFileSourceSettings::isSet(), SWGSDRangel::SWGRemoteSinkSettings::isSet(), SWGSDRangel::SWGWFMDemodSettings::isSet(), SWGSDRangel::SWGFreeDVDemodSettings::isSet(), SWGSDRangel::SWGBFMDemodSettings::isSet(), SWGSDRangel::SWGAMDemodSettings::isSet(), SWGSDRangel::SWGAMModSettings::isSet(), SWGSDRangel::SWGFreqTrackerSettings::isSet(), SWGSDRangel::SWGWFMModSettings::isSet(), SWGSDRangel::SWGFreeDVModSettings::isSet(), SWGSDRangel::SWGNFMDemodSettings::isSet(), SWGSDRangel::SWGNFMModSettings::isSet(), SWGSDRangel::SWGSSBDemodSettings::isSet(), SWGSDRangel::SWGSSBModSettings::isSet(), SWGSDRangel::SWGUDPSinkSettings::isSet(), SWGSDRangel::SWGUDPSourceSettings::isSet(), SWGSDRangel::SWGDSDDemodSettings::isSet(), SWGSDRangel::SWGATVModSettings::isSet(), local_sink_settings, local_source_settings, m_direction_isSet, m_originator_channel_index_isSet, m_originator_device_set_index_isSet, nfm_demod_settings, nfm_mod_settings, originator_channel_index, originator_device_set_index, remote_sink_settings, remote_source_settings, ssb_demod_settings, ssb_mod_settings, SWGSDRangel::toJsonValue(), udp_sink_settings, udp_source_settings, wfm_demod_settings, and wfm_mod_settings.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(channel_type != nullptr && *channel_type != QString("")){
         toJsonValue(QString("channelType"), channel_type, obj, QString("QString"));
     }
     if(m_direction_isSet){
         obj->insert("direction", QJsonValue(direction));
     }
     if(m_originator_device_set_index_isSet){
         obj->insert("originatorDeviceSetIndex", QJsonValue(originator_device_set_index));
     }
     if(m_originator_channel_index_isSet){
         obj->insert("originatorChannelIndex", QJsonValue(originator_channel_index));
     }
     if((am_demod_settings != nullptr) && (am_demod_settings->isSet())){
         toJsonValue(QString("AMDemodSettings"), am_demod_settings, obj, QString("SWGAMDemodSettings"));
     }
     if((am_mod_settings != nullptr) && (am_mod_settings->isSet())){
         toJsonValue(QString("AMModSettings"), am_mod_settings, obj, QString("SWGAMModSettings"));
     }
     if((atv_mod_settings != nullptr) && (atv_mod_settings->isSet())){
         toJsonValue(QString("ATVModSettings"), atv_mod_settings, obj, QString("SWGATVModSettings"));
     }
     if((bfm_demod_settings != nullptr) && (bfm_demod_settings->isSet())){
         toJsonValue(QString("BFMDemodSettings"), bfm_demod_settings, obj, QString("SWGBFMDemodSettings"));
     }
     if((dsd_demod_settings != nullptr) && (dsd_demod_settings->isSet())){
         toJsonValue(QString("DSDDemodSettings"), dsd_demod_settings, obj, QString("SWGDSDDemodSettings"));
     }
     if((file_source_settings != nullptr) && (file_source_settings->isSet())){
         toJsonValue(QString("FileSourceSettings"), file_source_settings, obj, QString("SWGFileSourceSettings"));
     }
     if((free_dv_demod_settings != nullptr) && (free_dv_demod_settings->isSet())){
         toJsonValue(QString("FreeDVDemodSettings"), free_dv_demod_settings, obj, QString("SWGFreeDVDemodSettings"));
     }
     if((free_dv_mod_settings != nullptr) && (free_dv_mod_settings->isSet())){
         toJsonValue(QString("FreeDVModSettings"), free_dv_mod_settings, obj, QString("SWGFreeDVModSettings"));
     }
     if((freq_tracker_settings != nullptr) && (freq_tracker_settings->isSet())){
         toJsonValue(QString("FreqTrackerSettings"), freq_tracker_settings, obj, QString("SWGFreqTrackerSettings"));
     }
     if((nfm_demod_settings != nullptr) && (nfm_demod_settings->isSet())){
         toJsonValue(QString("NFMDemodSettings"), nfm_demod_settings, obj, QString("SWGNFMDemodSettings"));
     }
     if((nfm_mod_settings != nullptr) && (nfm_mod_settings->isSet())){
         toJsonValue(QString("NFMModSettings"), nfm_mod_settings, obj, QString("SWGNFMModSettings"));
     }
     if((local_sink_settings != nullptr) && (local_sink_settings->isSet())){
         toJsonValue(QString("LocalSinkSettings"), local_sink_settings, obj, QString("SWGLocalSinkSettings"));
     }
     if((local_source_settings != nullptr) && (local_source_settings->isSet())){
         toJsonValue(QString("LocalSourceSettings"), local_source_settings, obj, QString("SWGLocalSourceSettings"));
     }
     if((remote_sink_settings != nullptr) && (remote_sink_settings->isSet())){
         toJsonValue(QString("RemoteSinkSettings"), remote_sink_settings, obj, QString("SWGRemoteSinkSettings"));
     }
     if((remote_source_settings != nullptr) && (remote_source_settings->isSet())){
         toJsonValue(QString("RemoteSourceSettings"), remote_source_settings, obj, QString("SWGRemoteSourceSettings"));
     }
     if((ssb_mod_settings != nullptr) && (ssb_mod_settings->isSet())){
         toJsonValue(QString("SSBModSettings"), ssb_mod_settings, obj, QString("SWGSSBModSettings"));
     }
     if((ssb_demod_settings != nullptr) && (ssb_demod_settings->isSet())){
         toJsonValue(QString("SSBDemodSettings"), ssb_demod_settings, obj, QString("SWGSSBDemodSettings"));
     }
     if((udp_source_settings != nullptr) && (udp_source_settings->isSet())){
         toJsonValue(QString("UDPSourceSettings"), udp_source_settings, obj, QString("SWGUDPSourceSettings"));
     }
     if((udp_sink_settings != nullptr) && (udp_sink_settings->isSet())){
         toJsonValue(QString("UDPSinkSettings"), udp_sink_settings, obj, QString("SWGUDPSinkSettings"));
     }
     if((wfm_demod_settings != nullptr) && (wfm_demod_settings->isSet())){
         toJsonValue(QString("WFMDemodSettings"), wfm_demod_settings, obj, QString("SWGWFMDemodSettings"));
     }
     if((wfm_mod_settings != nullptr) && (wfm_mod_settings->isSet())){
         toJsonValue(QString("WFMModSettings"), wfm_mod_settings, obj, QString("SWGWFMModSettings"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGChannelSettings::cleanup ()
Definition at line 142 of file SWGChannelSettings.cpp.
References am_demod_settings, am_mod_settings, atv_mod_settings, bfm_demod_settings, channel_type, dsd_demod_settings, file_source_settings, free_dv_demod_settings, free_dv_mod_settings, freq_tracker_settings, local_sink_settings, local_source_settings, nfm_demod_settings, nfm_mod_settings, remote_sink_settings, remote_source_settings, ssb_demod_settings, ssb_mod_settings, udp_sink_settings, udp_source_settings, wfm_demod_settings, and wfm_mod_settings.
Referenced by WebAPIRequestMapper::resetChannelSettings(), and ~SWGChannelSettings().
{
     if(channel_type != nullptr) {
         delete channel_type;
     }
     if(am_demod_settings != nullptr) {
         delete am_demod_settings;
     }
     if(am_mod_settings != nullptr) {
         delete am_mod_settings;
     }
     if(atv_mod_settings != nullptr) {
         delete atv_mod_settings;
     }
     if(bfm_demod_settings != nullptr) {
         delete bfm_demod_settings;
     }
     if(dsd_demod_settings != nullptr) {
         delete dsd_demod_settings;
     }
     if(file_source_settings != nullptr) {
         delete file_source_settings;
     }
     if(free_dv_demod_settings != nullptr) {
         delete free_dv_demod_settings;
     }
     if(free_dv_mod_settings != nullptr) {
         delete free_dv_mod_settings;
     }
     if(freq_tracker_settings != nullptr) {
         delete freq_tracker_settings;
     }
     if(nfm_demod_settings != nullptr) {
         delete nfm_demod_settings;
     }
     if(nfm_mod_settings != nullptr) {
         delete nfm_mod_settings;
     }
     if(local_sink_settings != nullptr) {
         delete local_sink_settings;
     }
     if(local_source_settings != nullptr) {
         delete local_source_settings;
     }
     if(remote_sink_settings != nullptr) {
         delete remote_sink_settings;
     }
     if(remote_source_settings != nullptr) {
         delete remote_source_settings;
     }
     if(ssb_mod_settings != nullptr) {
         delete ssb_mod_settings;
     }
     if(ssb_demod_settings != nullptr) {
         delete ssb_demod_settings;
     }
     if(udp_source_settings != nullptr) {
         delete udp_source_settings;
     }
     if(udp_sink_settings != nullptr) {
         delete udp_sink_settings;
     }
     if(wfm_demod_settings != nullptr) {
         delete wfm_demod_settings;
     }
     if(wfm_mod_settings != nullptr) {
         delete wfm_mod_settings;
     }
 }
fromJson()
SWGChannelSettings * SWGSDRangel::SWGChannelSettings::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 215 of file SWGChannelSettings.cpp.
References fromJsonObject().
Referenced by SWGChannelSettings().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGChannelSettings::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 224 of file SWGChannelSettings.cpp.
References am_demod_settings, am_mod_settings, atv_mod_settings, bfm_demod_settings, channel_type, direction, dsd_demod_settings, file_source_settings, free_dv_demod_settings, free_dv_mod_settings, freq_tracker_settings, local_sink_settings, local_source_settings, nfm_demod_settings, nfm_mod_settings, originator_channel_index, originator_device_set_index, remote_sink_settings, remote_source_settings, SWGSDRangel::setValue(), ssb_demod_settings, ssb_mod_settings, udp_sink_settings, udp_source_settings, wfm_demod_settings, and wfm_mod_settings.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&channel_type, pJson["channelType"], "QString", "QString");
     ::SWGSDRangel::setValue(&direction, pJson["direction"], "qint32", "");
     ::SWGSDRangel::setValue(&originator_device_set_index, pJson["originatorDeviceSetIndex"], "qint32", "");
     ::SWGSDRangel::setValue(&originator_channel_index, pJson["originatorChannelIndex"], "qint32", "");
     ::SWGSDRangel::setValue(&am_demod_settings, pJson["AMDemodSettings"], "SWGAMDemodSettings", "SWGAMDemodSettings");
     ::SWGSDRangel::setValue(&am_mod_settings, pJson["AMModSettings"], "SWGAMModSettings", "SWGAMModSettings");
     ::SWGSDRangel::setValue(&atv_mod_settings, pJson["ATVModSettings"], "SWGATVModSettings", "SWGATVModSettings");
     ::SWGSDRangel::setValue(&bfm_demod_settings, pJson["BFMDemodSettings"], "SWGBFMDemodSettings", "SWGBFMDemodSettings");
     ::SWGSDRangel::setValue(&dsd_demod_settings, pJson["DSDDemodSettings"], "SWGDSDDemodSettings", "SWGDSDDemodSettings");
     ::SWGSDRangel::setValue(&file_source_settings, pJson["FileSourceSettings"], "SWGFileSourceSettings", "SWGFileSourceSettings");
     ::SWGSDRangel::setValue(&free_dv_demod_settings, pJson["FreeDVDemodSettings"], "SWGFreeDVDemodSettings", "SWGFreeDVDemodSettings");
     ::SWGSDRangel::setValue(&free_dv_mod_settings, pJson["FreeDVModSettings"], "SWGFreeDVModSettings", "SWGFreeDVModSettings");
     ::SWGSDRangel::setValue(&freq_tracker_settings, pJson["FreqTrackerSettings"], "SWGFreqTrackerSettings", "SWGFreqTrackerSettings");
     ::SWGSDRangel::setValue(&nfm_demod_settings, pJson["NFMDemodSettings"], "SWGNFMDemodSettings", "SWGNFMDemodSettings");
     ::SWGSDRangel::setValue(&nfm_mod_settings, pJson["NFMModSettings"], "SWGNFMModSettings", "SWGNFMModSettings");
     ::SWGSDRangel::setValue(&local_sink_settings, pJson["LocalSinkSettings"], "SWGLocalSinkSettings", "SWGLocalSinkSettings");
     ::SWGSDRangel::setValue(&local_source_settings, pJson["LocalSourceSettings"], "SWGLocalSourceSettings", "SWGLocalSourceSettings");
     ::SWGSDRangel::setValue(&remote_sink_settings, pJson["RemoteSinkSettings"], "SWGRemoteSinkSettings", "SWGRemoteSinkSettings");
     ::SWGSDRangel::setValue(&remote_source_settings, pJson["RemoteSourceSettings"], "SWGRemoteSourceSettings", "SWGRemoteSourceSettings");
     ::SWGSDRangel::setValue(&ssb_mod_settings, pJson["SSBModSettings"], "SWGSSBModSettings", "SWGSSBModSettings");
     ::SWGSDRangel::setValue(&ssb_demod_settings, pJson["SSBDemodSettings"], "SWGSSBDemodSettings", "SWGSSBDemodSettings");
     ::SWGSDRangel::setValue(&udp_source_settings, pJson["UDPSourceSettings"], "SWGUDPSourceSettings", "SWGUDPSourceSettings");
     ::SWGSDRangel::setValue(&udp_sink_settings, pJson["UDPSinkSettings"], "SWGUDPSinkSettings", "SWGUDPSinkSettings");
     ::SWGSDRangel::setValue(&wfm_demod_settings, pJson["WFMDemodSettings"], "SWGWFMDemodSettings", "SWGWFMDemodSettings");
     ::SWGSDRangel::setValue(&wfm_mod_settings, pJson["WFMModSettings"], "SWGWFMModSettings", "SWGWFMModSettings");
 }
getAmDemodSettings()
SWGAMDemodSettings * SWGSDRangel::SWGChannelSettings::getAmDemodSettings ()
Definition at line 411 of file SWGChannelSettings.cpp.
References am_demod_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), AMDemod::webapiFormatChannelSettings(), AMDemod::webapiReverseSendSettings(), AMDemod::webapiSettingsGet(), AMDemod::webapiSettingsPutPatch(), and FreqTracker::webapiSettingsPutPatch().
{
     return am_demod_settings;
 }
getAmModSettings()
SWGAMModSettings * SWGSDRangel::SWGChannelSettings::getAmModSettings ()
Definition at line 421 of file SWGChannelSettings.cpp.
References am_mod_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), AMMod::webapiFormatChannelSettings(), AMMod::webapiReverseSendCWSettings(), AMMod::webapiReverseSendSettings(), AMMod::webapiSettingsGet(), and AMMod::webapiSettingsPutPatch().
{
     return am_mod_settings;
 }
getAtvModSettings()
SWGATVModSettings * SWGSDRangel::SWGChannelSettings::getAtvModSettings ()
Definition at line 431 of file SWGChannelSettings.cpp.
References atv_mod_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), ATVMod::webapiFormatChannelSettings(), ATVMod::webapiReverseSendSettings(), ATVMod::webapiSettingsGet(), and ATVMod::webapiSettingsPutPatch().
{
     return atv_mod_settings;
 }
getBfmDemodSettings()
SWGBFMDemodSettings * SWGSDRangel::SWGChannelSettings::getBfmDemodSettings ()
Definition at line 441 of file SWGChannelSettings.cpp.
References bfm_demod_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), BFMDemod::webapiFormatChannelSettings(), BFMDemod::webapiReverseSendSettings(), BFMDemod::webapiSettingsGet(), and BFMDemod::webapiSettingsPutPatch().
{
     return bfm_demod_settings;
 }
getChannelType()
QString * SWGSDRangel::SWGChannelSettings::getChannelType ()
Definition at line 371 of file SWGChannelSettings.cpp.
References channel_type.
Referenced by WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterSrv::devicesetChannelPost(), WebAPIAdapterGUI::devicesetChannelSettingsGet(), WebAPIAdapterSrv::devicesetChannelSettingsGet(), WebAPIAdapterGUI::devicesetChannelSettingsPutPatch(), WebAPIAdapterSrv::devicesetChannelSettingsPutPatch(), and WebAPIRequestMapper::validateChannelSettings().
{
     return channel_type;
 }
getDirection()
qint32 SWGSDRangel::SWGChannelSettings::getDirection ()
Definition at line 381 of file SWGChannelSettings.cpp.
References direction.
Referenced by WebAPIAdapterGUI::devicesetChannelPost(), WebAPIAdapterSrv::devicesetChannelPost(), and WebAPIRequestMapper::validateChannelSettings().
{
     return direction;
 }
getDsdDemodSettings()
SWGDSDDemodSettings * SWGSDRangel::SWGChannelSettings::getDsdDemodSettings ()
Definition at line 451 of file SWGChannelSettings.cpp.
References dsd_demod_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), DSDDemod::webapiFormatChannelSettings(), DSDDemod::webapiReverseSendSettings(), DSDDemod::webapiSettingsGet(), and DSDDemod::webapiSettingsPutPatch().
{
     return dsd_demod_settings;
 }
getFileSourceSettings()
SWGFileSourceSettings * SWGSDRangel::SWGChannelSettings::getFileSourceSettings ()
Definition at line 461 of file SWGChannelSettings.cpp.
References file_source_settings.
Referenced by FileSource::webapiFormatChannelSettings(), FileSource::webapiReverseSendSettings(), FileSource::webapiSettingsGet(), and FileSource::webapiSettingsPutPatch().
{
     return file_source_settings;
 }
getFreeDvDemodSettings()
SWGFreeDVDemodSettings * SWGSDRangel::SWGChannelSettings::getFreeDvDemodSettings ()
Definition at line 471 of file SWGChannelSettings.cpp.
References free_dv_demod_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), FreeDVDemod::webapiFormatChannelSettings(), FreeDVDemod::webapiReverseSendSettings(), FreeDVDemod::webapiSettingsGet(), and FreeDVDemod::webapiSettingsPutPatch().
{
     return free_dv_demod_settings;
 }
getFreeDvModSettings()
SWGFreeDVModSettings * SWGSDRangel::SWGChannelSettings::getFreeDvModSettings ()
Definition at line 481 of file SWGChannelSettings.cpp.
References free_dv_mod_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), FreeDVMod::webapiFormatChannelSettings(), FreeDVMod::webapiReverseSendCWSettings(), FreeDVMod::webapiReverseSendSettings(), FreeDVMod::webapiSettingsGet(), and FreeDVMod::webapiSettingsPutPatch().
{
     return free_dv_mod_settings;
 }
getFreqTrackerSettings()
SWGFreqTrackerSettings * SWGSDRangel::SWGChannelSettings::getFreqTrackerSettings ()
Definition at line 491 of file SWGChannelSettings.cpp.
References freq_tracker_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), FreqTracker::webapiFormatChannelSettings(), FreqTracker::webapiReverseSendSettings(), FreqTracker::webapiSettingsGet(), and FreqTracker::webapiSettingsPutPatch().
{
     return freq_tracker_settings;
 }
getLocalSinkSettings()
SWGLocalSinkSettings * SWGSDRangel::SWGChannelSettings::getLocalSinkSettings ()
Definition at line 521 of file SWGChannelSettings.cpp.
References local_sink_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), LocalSink::webapiFormatChannelSettings(), LocalSink::webapiReverseSendSettings(), LocalSink::webapiSettingsGet(), and LocalSink::webapiSettingsPutPatch().
{
     return local_sink_settings;
 }
getLocalSourceSettings()
SWGLocalSourceSettings * SWGSDRangel::SWGChannelSettings::getLocalSourceSettings ()
Definition at line 531 of file SWGChannelSettings.cpp.
References local_source_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), LocalSource::webapiFormatChannelSettings(), LocalSource::webapiReverseSendSettings(), LocalSource::webapiSettingsGet(), and LocalSource::webapiSettingsPutPatch().
{
     return local_source_settings;
 }
getNfmDemodSettings()
SWGNFMDemodSettings * SWGSDRangel::SWGChannelSettings::getNfmDemodSettings ()
Definition at line 501 of file SWGChannelSettings.cpp.
References nfm_demod_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), NFMDemod::webapiFormatChannelSettings(), NFMDemod::webapiReverseSendSettings(), NFMDemod::webapiSettingsGet(), and NFMDemod::webapiSettingsPutPatch().
{
     return nfm_demod_settings;
 }
getNfmModSettings()
SWGNFMModSettings * SWGSDRangel::SWGChannelSettings::getNfmModSettings ()
Definition at line 511 of file SWGChannelSettings.cpp.
References nfm_mod_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), NFMMod::webapiFormatChannelSettings(), NFMMod::webapiReverseSendCWSettings(), NFMMod::webapiReverseSendSettings(), NFMMod::webapiSettingsGet(), and NFMMod::webapiSettingsPutPatch().
{
     return nfm_mod_settings;
 }
getOriginatorChannelIndex()
qint32 SWGSDRangel::SWGChannelSettings::getOriginatorChannelIndex ()
Definition at line 401 of file SWGChannelSettings.cpp.
References originator_channel_index.
{
     return originator_channel_index;
 }
getOriginatorDeviceSetIndex()
qint32 SWGSDRangel::SWGChannelSettings::getOriginatorDeviceSetIndex ()
Definition at line 391 of file SWGChannelSettings.cpp.
References originator_device_set_index.
{
     return originator_device_set_index;
 }
getRemoteSinkSettings()
SWGRemoteSinkSettings * SWGSDRangel::SWGChannelSettings::getRemoteSinkSettings ()
Definition at line 541 of file SWGChannelSettings.cpp.
References remote_sink_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), RemoteSink::webapiFormatChannelSettings(), RemoteSink::webapiReverseSendSettings(), RemoteSink::webapiSettingsGet(), and RemoteSink::webapiSettingsPutPatch().
{
     return remote_sink_settings;
 }
getRemoteSourceSettings()
SWGRemoteSourceSettings * SWGSDRangel::SWGChannelSettings::getRemoteSourceSettings ()
Definition at line 551 of file SWGChannelSettings.cpp.
References remote_source_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), RemoteSource::webapiFormatChannelSettings(), RemoteSource::webapiReverseSendSettings(), RemoteSource::webapiSettingsGet(), and RemoteSource::webapiSettingsPutPatch().
{
     return remote_source_settings;
 }
getSsbDemodSettings()
SWGSSBDemodSettings * SWGSDRangel::SWGChannelSettings::getSsbDemodSettings ()
Definition at line 571 of file SWGChannelSettings.cpp.
References ssb_demod_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), SSBDemod::webapiFormatChannelSettings(), SSBDemod::webapiReverseSendSettings(), SSBDemod::webapiSettingsGet(), and SSBDemod::webapiSettingsPutPatch().
{
     return ssb_demod_settings;
 }
getSsbModSettings()
SWGSSBModSettings * SWGSDRangel::SWGChannelSettings::getSsbModSettings ()
Definition at line 561 of file SWGChannelSettings.cpp.
References ssb_mod_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), SSBMod::webapiFormatChannelSettings(), SSBMod::webapiReverseSendCWSettings(), SSBMod::webapiReverseSendSettings(), SSBMod::webapiSettingsGet(), and SSBMod::webapiSettingsPutPatch().
{
     return ssb_mod_settings;
 }
getUdpSinkSettings()
SWGUDPSinkSettings * SWGSDRangel::SWGChannelSettings::getUdpSinkSettings ()
Definition at line 591 of file SWGChannelSettings.cpp.
References udp_sink_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), UDPSink::webapiFormatChannelSettings(), UDPSink::webapiReverseSendSettings(), UDPSink::webapiSettingsGet(), and UDPSink::webapiSettingsPutPatch().
{
     return udp_sink_settings;
 }
getUdpSourceSettings()
SWGUDPSourceSettings * SWGSDRangel::SWGChannelSettings::getUdpSourceSettings ()
Definition at line 581 of file SWGChannelSettings.cpp.
References udp_source_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), UDPSource::webapiFormatChannelSettings(), UDPSource::webapiReverseSendSettings(), UDPSource::webapiSettingsGet(), and UDPSource::webapiSettingsPutPatch().
{
     return udp_source_settings;
 }
getWfmDemodSettings()
SWGWFMDemodSettings * SWGSDRangel::SWGChannelSettings::getWfmDemodSettings ()
Definition at line 601 of file SWGChannelSettings.cpp.
References wfm_demod_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), WFMDemod::webapiFormatChannelSettings(), WFMDemod::webapiReverseSendSettings(), WFMDemod::webapiSettingsGet(), and WFMDemod::webapiSettingsPutPatch().
{
     return wfm_demod_settings;
 }
getWfmModSettings()
SWGWFMModSettings * SWGSDRangel::SWGChannelSettings::getWfmModSettings ()
Definition at line 611 of file SWGChannelSettings.cpp.
References wfm_mod_settings.
Referenced by WebAPIRequestMapper::validateChannelSettings(), WFMMod::webapiFormatChannelSettings(), WFMMod::webapiReverseSendCWSettings(), WFMMod::webapiReverseSendSettings(), WFMMod::webapiSettingsGet(), and WFMMod::webapiSettingsPutPatch().
{
     return wfm_mod_settings;
 }
init()
void SWGSDRangel::SWGChannelSettings::init ()
Definition at line 88 of file SWGChannelSettings.cpp.
References am_demod_settings, am_mod_settings, atv_mod_settings, bfm_demod_settings, channel_type, direction, dsd_demod_settings, file_source_settings, free_dv_demod_settings, free_dv_mod_settings, freq_tracker_settings, local_sink_settings, local_source_settings, m_am_demod_settings_isSet, m_am_mod_settings_isSet, m_atv_mod_settings_isSet, m_bfm_demod_settings_isSet, m_channel_type_isSet, m_direction_isSet, m_dsd_demod_settings_isSet, m_file_source_settings_isSet, m_free_dv_demod_settings_isSet, m_free_dv_mod_settings_isSet, m_freq_tracker_settings_isSet, m_local_sink_settings_isSet, m_local_source_settings_isSet, m_nfm_demod_settings_isSet, m_nfm_mod_settings_isSet, m_originator_channel_index_isSet, m_originator_device_set_index_isSet, m_remote_sink_settings_isSet, m_remote_source_settings_isSet, m_ssb_demod_settings_isSet, m_ssb_mod_settings_isSet, m_udp_sink_settings_isSet, m_udp_source_settings_isSet, m_wfm_demod_settings_isSet, m_wfm_mod_settings_isSet, nfm_demod_settings, nfm_mod_settings, originator_channel_index, originator_device_set_index, remote_sink_settings, remote_source_settings, ssb_demod_settings, ssb_mod_settings, udp_sink_settings, udp_source_settings, wfm_demod_settings, and wfm_mod_settings.
Referenced by SWGChannelSettings().
{
     channel_type = new QString("");
     m_channel_type_isSet = false;
     direction = 0;
     m_direction_isSet = false;
     originator_device_set_index = 0;
     m_originator_device_set_index_isSet = false;
     originator_channel_index = 0;
     m_originator_channel_index_isSet = false;
     am_demod_settings = new SWGAMDemodSettings();
     m_am_demod_settings_isSet = false;
     am_mod_settings = new SWGAMModSettings();
     m_am_mod_settings_isSet = false;
     atv_mod_settings = new SWGATVModSettings();
     m_atv_mod_settings_isSet = false;
     bfm_demod_settings = new SWGBFMDemodSettings();
     m_bfm_demod_settings_isSet = false;
     dsd_demod_settings = new SWGDSDDemodSettings();
     m_dsd_demod_settings_isSet = false;
     file_source_settings = new SWGFileSourceSettings();
     m_file_source_settings_isSet = false;
     free_dv_demod_settings = new SWGFreeDVDemodSettings();
     m_free_dv_demod_settings_isSet = false;
     free_dv_mod_settings = new SWGFreeDVModSettings();
     m_free_dv_mod_settings_isSet = false;
     freq_tracker_settings = new SWGFreqTrackerSettings();
     m_freq_tracker_settings_isSet = false;
     nfm_demod_settings = new SWGNFMDemodSettings();
     m_nfm_demod_settings_isSet = false;
     nfm_mod_settings = new SWGNFMModSettings();
     m_nfm_mod_settings_isSet = false;
     local_sink_settings = new SWGLocalSinkSettings();
     m_local_sink_settings_isSet = false;
     local_source_settings = new SWGLocalSourceSettings();
     m_local_source_settings_isSet = false;
     remote_sink_settings = new SWGRemoteSinkSettings();
     m_remote_sink_settings_isSet = false;
     remote_source_settings = new SWGRemoteSourceSettings();
     m_remote_source_settings_isSet = false;
     ssb_mod_settings = new SWGSSBModSettings();
     m_ssb_mod_settings_isSet = false;
     ssb_demod_settings = new SWGSSBDemodSettings();
     m_ssb_demod_settings_isSet = false;
     udp_source_settings = new SWGUDPSourceSettings();
     m_udp_source_settings_isSet = false;
     udp_sink_settings = new SWGUDPSinkSettings();
     m_udp_sink_settings_isSet = false;
     wfm_demod_settings = new SWGWFMDemodSettings();
     m_wfm_demod_settings_isSet = false;
     wfm_mod_settings = new SWGWFMModSettings();
     m_wfm_mod_settings_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGChannelSettings::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 622 of file SWGChannelSettings.cpp.
References am_demod_settings, am_mod_settings, atv_mod_settings, bfm_demod_settings, channel_type, dsd_demod_settings, file_source_settings, free_dv_demod_settings, free_dv_mod_settings, freq_tracker_settings, SWGSDRangel::SWGRemoteSourceSettings::isSet(), SWGSDRangel::SWGLocalSinkSettings::isSet(), SWGSDRangel::SWGLocalSourceSettings::isSet(), SWGSDRangel::SWGFileSourceSettings::isSet(), SWGSDRangel::SWGRemoteSinkSettings::isSet(), SWGSDRangel::SWGWFMDemodSettings::isSet(), SWGSDRangel::SWGFreeDVDemodSettings::isSet(), SWGSDRangel::SWGBFMDemodSettings::isSet(), SWGSDRangel::SWGAMDemodSettings::isSet(), SWGSDRangel::SWGAMModSettings::isSet(), SWGSDRangel::SWGFreqTrackerSettings::isSet(), SWGSDRangel::SWGFreeDVModSettings::isSet(), SWGSDRangel::SWGWFMModSettings::isSet(), SWGSDRangel::SWGNFMDemodSettings::isSet(), SWGSDRangel::SWGNFMModSettings::isSet(), SWGSDRangel::SWGSSBDemodSettings::isSet(), SWGSDRangel::SWGSSBModSettings::isSet(), SWGSDRangel::SWGUDPSourceSettings::isSet(), SWGSDRangel::SWGUDPSinkSettings::isSet(), SWGSDRangel::SWGDSDDemodSettings::isSet(), SWGSDRangel::SWGATVModSettings::isSet(), local_sink_settings, local_source_settings, m_direction_isSet, m_originator_channel_index_isSet, m_originator_device_set_index_isSet, nfm_demod_settings, nfm_mod_settings, remote_sink_settings, remote_source_settings, ssb_demod_settings, ssb_mod_settings, udp_sink_settings, udp_source_settings, wfm_demod_settings, and wfm_mod_settings.
{
     bool isObjectUpdated = false;
     do{
         if(channel_type != nullptr && *channel_type != QString("")){ isObjectUpdated = true; break;}
         if(m_direction_isSet){ isObjectUpdated = true; break;}
         if(m_originator_device_set_index_isSet){ isObjectUpdated = true; break;}
         if(m_originator_channel_index_isSet){ isObjectUpdated = true; break;}
         if(am_demod_settings != nullptr && am_demod_settings->isSet()){ isObjectUpdated = true; break;}
         if(am_mod_settings != nullptr && am_mod_settings->isSet()){ isObjectUpdated = true; break;}
         if(atv_mod_settings != nullptr && atv_mod_settings->isSet()){ isObjectUpdated = true; break;}
         if(bfm_demod_settings != nullptr && bfm_demod_settings->isSet()){ isObjectUpdated = true; break;}
         if(dsd_demod_settings != nullptr && dsd_demod_settings->isSet()){ isObjectUpdated = true; break;}
         if(file_source_settings != nullptr && file_source_settings->isSet()){ isObjectUpdated = true; break;}
         if(free_dv_demod_settings != nullptr && free_dv_demod_settings->isSet()){ isObjectUpdated = true; break;}
         if(free_dv_mod_settings != nullptr && free_dv_mod_settings->isSet()){ isObjectUpdated = true; break;}
         if(freq_tracker_settings != nullptr && freq_tracker_settings->isSet()){ isObjectUpdated = true; break;}
         if(nfm_demod_settings != nullptr && nfm_demod_settings->isSet()){ isObjectUpdated = true; break;}
         if(nfm_mod_settings != nullptr && nfm_mod_settings->isSet()){ isObjectUpdated = true; break;}
         if(local_sink_settings != nullptr && local_sink_settings->isSet()){ isObjectUpdated = true; break;}
         if(local_source_settings != nullptr && local_source_settings->isSet()){ isObjectUpdated = true; break;}
         if(remote_sink_settings != nullptr && remote_sink_settings->isSet()){ isObjectUpdated = true; break;}
         if(remote_source_settings != nullptr && remote_source_settings->isSet()){ isObjectUpdated = true; break;}
         if(ssb_mod_settings != nullptr && ssb_mod_settings->isSet()){ isObjectUpdated = true; break;}
         if(ssb_demod_settings != nullptr && ssb_demod_settings->isSet()){ isObjectUpdated = true; break;}
         if(udp_source_settings != nullptr && udp_source_settings->isSet()){ isObjectUpdated = true; break;}
         if(udp_sink_settings != nullptr && udp_sink_settings->isSet()){ isObjectUpdated = true; break;}
         if(wfm_demod_settings != nullptr && wfm_demod_settings->isSet()){ isObjectUpdated = true; break;}
         if(wfm_mod_settings != nullptr && wfm_mod_settings->isSet()){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setAmDemodSettings()
void SWGSDRangel::SWGChannelSettings::setAmDemodSettings (SWGAMDemodSettings * am_demod_settings)
Definition at line 415 of file SWGChannelSettings.cpp.
References am_demod_settings, and m_am_demod_settings_isSet.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), AMDemod::webapiReverseSendSettings(), and AMDemod::webapiSettingsGet().
{
     this->am_demod_settings = am_demod_settings;
     this->m_am_demod_settings_isSet = true;
 }
setAmModSettings()
void SWGSDRangel::SWGChannelSettings::setAmModSettings (SWGAMModSettings * am_mod_settings)
Definition at line 425 of file SWGChannelSettings.cpp.
References am_mod_settings, and m_am_mod_settings_isSet.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), AMMod::webapiReverseSendCWSettings(), AMMod::webapiReverseSendSettings(), and AMMod::webapiSettingsGet().
{
     this->am_mod_settings = am_mod_settings;
     this->m_am_mod_settings_isSet = true;
 }
setAtvModSettings()
void SWGSDRangel::SWGChannelSettings::setAtvModSettings (SWGATVModSettings * atv_mod_settings)
Definition at line 435 of file SWGChannelSettings.cpp.
References atv_mod_settings, and m_atv_mod_settings_isSet.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), ATVMod::webapiReverseSendSettings(), and ATVMod::webapiSettingsGet().
{
     this->atv_mod_settings = atv_mod_settings;
     this->m_atv_mod_settings_isSet = true;
 }
setBfmDemodSettings()
void SWGSDRangel::SWGChannelSettings::setBfmDemodSettings (SWGBFMDemodSettings * bfm_demod_settings)
Definition at line 445 of file SWGChannelSettings.cpp.
References bfm_demod_settings, and m_bfm_demod_settings_isSet.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), BFMDemod::webapiReverseSendSettings(), and BFMDemod::webapiSettingsGet().
{
     this->bfm_demod_settings = bfm_demod_settings;
     this->m_bfm_demod_settings_isSet = true;
 }
setChannelType()
void SWGSDRangel::SWGChannelSettings::setChannelType (QString * channel_type)
Definition at line 375 of file SWGChannelSettings.cpp.
References channel_type, and m_channel_type_isSet.
Referenced by WebAPIRequestMapper::devicesetChannelService(), WebAPIAdapterGUI::devicesetChannelSettingsGet(), WebAPIAdapterSrv::devicesetChannelSettingsGet(), WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), WFMMod::webapiReverseSendCWSettings(), AMMod::webapiReverseSendCWSettings(), NFMMod::webapiReverseSendCWSettings(), FreeDVMod::webapiReverseSendCWSettings(), SSBMod::webapiReverseSendCWSettings(), LocalSink::webapiReverseSendSettings(), LocalSource::webapiReverseSendSettings(), RemoteSink::webapiReverseSendSettings(), WFMDemod::webapiReverseSendSettings(), AMDemod::webapiReverseSendSettings(), FreqTracker::webapiReverseSendSettings(), UDPSink::webapiReverseSendSettings(), RemoteSource::webapiReverseSendSettings(), UDPSource::webapiReverseSendSettings(), NFMDemod::webapiReverseSendSettings(), DSDDemod::webapiReverseSendSettings(), BFMDemod::webapiReverseSendSettings(), WFMMod::webapiReverseSendSettings(), AMMod::webapiReverseSendSettings(), SSBDemod::webapiReverseSendSettings(), NFMMod::webapiReverseSendSettings(), FreeDVMod::webapiReverseSendSettings(), SSBMod::webapiReverseSendSettings(), FreeDVDemod::webapiReverseSendSettings(), FileSource::webapiReverseSendSettings(), and ATVMod::webapiReverseSendSettings().
{
     this->channel_type = channel_type;
     this->m_channel_type_isSet = true;
 }
setDirection()
void SWGSDRangel::SWGChannelSettings::setDirection (qint32 direction)
Definition at line 385 of file SWGChannelSettings.cpp.
References direction, and m_direction_isSet.
Referenced by WebAPIRequestMapper::devicesetChannelService(), WebAPIAdapterGUI::devicesetChannelSettingsGet(), WebAPIAdapterSrv::devicesetChannelSettingsGet(), WebAPIRequestMapper::validateChannelSettings(), WFMMod::webapiReverseSendCWSettings(), AMMod::webapiReverseSendCWSettings(), NFMMod::webapiReverseSendCWSettings(), FreeDVMod::webapiReverseSendCWSettings(), SSBMod::webapiReverseSendCWSettings(), LocalSink::webapiReverseSendSettings(), LocalSource::webapiReverseSendSettings(), RemoteSink::webapiReverseSendSettings(), WFMDemod::webapiReverseSendSettings(), AMDemod::webapiReverseSendSettings(), FreqTracker::webapiReverseSendSettings(), UDPSink::webapiReverseSendSettings(), RemoteSource::webapiReverseSendSettings(), UDPSource::webapiReverseSendSettings(), NFMDemod::webapiReverseSendSettings(), DSDDemod::webapiReverseSendSettings(), BFMDemod::webapiReverseSendSettings(), WFMMod::webapiReverseSendSettings(), AMMod::webapiReverseSendSettings(), SSBDemod::webapiReverseSendSettings(), NFMMod::webapiReverseSendSettings(), FreeDVMod::webapiReverseSendSettings(), SSBMod::webapiReverseSendSettings(), FreeDVDemod::webapiReverseSendSettings(), FileSource::webapiReverseSendSettings(), and ATVMod::webapiReverseSendSettings().
{
     this->direction = direction;
     this->m_direction_isSet = true;
 }
setDsdDemodSettings()
void SWGSDRangel::SWGChannelSettings::setDsdDemodSettings (SWGDSDDemodSettings * dsd_demod_settings)
Definition at line 455 of file SWGChannelSettings.cpp.
References dsd_demod_settings, and m_dsd_demod_settings_isSet.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), DSDDemod::webapiReverseSendSettings(), and DSDDemod::webapiSettingsGet().
{
     this->dsd_demod_settings = dsd_demod_settings;
     this->m_dsd_demod_settings_isSet = true;
 }
setFileSourceSettings()
void SWGSDRangel::SWGChannelSettings::setFileSourceSettings (SWGFileSourceSettings * file_source_settings)
Definition at line 465 of file SWGChannelSettings.cpp.
References file_source_settings, and m_file_source_settings_isSet.
Referenced by FileSource::webapiReverseSendSettings(), and FileSource::webapiSettingsGet().
{
     this->file_source_settings = file_source_settings;
     this->m_file_source_settings_isSet = true;
 }
setFreeDvDemodSettings()
void SWGSDRangel::SWGChannelSettings::setFreeDvDemodSettings (SWGFreeDVDemodSettings * free_dv_demod_settings)
Definition at line 475 of file SWGChannelSettings.cpp.
References free_dv_demod_settings, and m_free_dv_demod_settings_isSet.
Referenced by WebAPIRequestMapper::validateChannelSettings(), FreeDVDemod::webapiReverseSendSettings(), and FreeDVDemod::webapiSettingsGet().
{
     this->free_dv_demod_settings = free_dv_demod_settings;
     this->m_free_dv_demod_settings_isSet = true;
 }
setFreeDvModSettings()
void SWGSDRangel::SWGChannelSettings::setFreeDvModSettings (SWGFreeDVModSettings * free_dv_mod_settings)
Definition at line 485 of file SWGChannelSettings.cpp.
References free_dv_mod_settings, and m_free_dv_mod_settings_isSet.
Referenced by WebAPIRequestMapper::validateChannelSettings(), FreeDVMod::webapiReverseSendCWSettings(), FreeDVMod::webapiReverseSendSettings(), and FreeDVMod::webapiSettingsGet().
{
     this->free_dv_mod_settings = free_dv_mod_settings;
     this->m_free_dv_mod_settings_isSet = true;
 }
setFreqTrackerSettings()
void SWGSDRangel::SWGChannelSettings::setFreqTrackerSettings (SWGFreqTrackerSettings * freq_tracker_settings)
Definition at line 495 of file SWGChannelSettings.cpp.
References freq_tracker_settings, and m_freq_tracker_settings_isSet.
Referenced by WebAPIRequestMapper::validateChannelSettings(), FreqTracker::webapiReverseSendSettings(), and FreqTracker::webapiSettingsGet().
{
     this->freq_tracker_settings = freq_tracker_settings;
     this->m_freq_tracker_settings_isSet = true;
 }
setLocalSinkSettings()
void SWGSDRangel::SWGChannelSettings::setLocalSinkSettings (SWGLocalSinkSettings * local_sink_settings)
Definition at line 525 of file SWGChannelSettings.cpp.
References local_sink_settings, and m_local_sink_settings_isSet.
Referenced by WebAPIRequestMapper::validateChannelSettings(), LocalSink::webapiReverseSendSettings(), and LocalSink::webapiSettingsGet().
{
     this->local_sink_settings = local_sink_settings;
     this->m_local_sink_settings_isSet = true;
 }
setLocalSourceSettings()
void SWGSDRangel::SWGChannelSettings::setLocalSourceSettings (SWGLocalSourceSettings * local_source_settings)
Definition at line 535 of file SWGChannelSettings.cpp.
References local_source_settings, and m_local_source_settings_isSet.
Referenced by WebAPIRequestMapper::validateChannelSettings(), LocalSource::webapiReverseSendSettings(), and LocalSource::webapiSettingsGet().
{
     this->local_source_settings = local_source_settings;
     this->m_local_source_settings_isSet = true;
 }
setNfmDemodSettings()
void SWGSDRangel::SWGChannelSettings::setNfmDemodSettings (SWGNFMDemodSettings * nfm_demod_settings)
Definition at line 505 of file SWGChannelSettings.cpp.
References m_nfm_demod_settings_isSet, and nfm_demod_settings.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), NFMDemod::webapiReverseSendSettings(), and NFMDemod::webapiSettingsGet().
{
     this->nfm_demod_settings = nfm_demod_settings;
     this->m_nfm_demod_settings_isSet = true;
 }
setNfmModSettings()
void SWGSDRangel::SWGChannelSettings::setNfmModSettings (SWGNFMModSettings * nfm_mod_settings)
Definition at line 515 of file SWGChannelSettings.cpp.
References m_nfm_mod_settings_isSet, and nfm_mod_settings.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), NFMMod::webapiReverseSendCWSettings(), NFMMod::webapiReverseSendSettings(), and NFMMod::webapiSettingsGet().
{
     this->nfm_mod_settings = nfm_mod_settings;
     this->m_nfm_mod_settings_isSet = true;
 }
setOriginatorChannelIndex()
void SWGSDRangel::SWGChannelSettings::setOriginatorChannelIndex (qint32 originator_channel_index)
Definition at line 405 of file SWGChannelSettings.cpp.
References m_originator_channel_index_isSet, and originator_channel_index.
Referenced by LocalSink::webapiReverseSendSettings(), LocalSource::webapiReverseSendSettings(), RemoteSink::webapiReverseSendSettings(), WFMDemod::webapiReverseSendSettings(), AMDemod::webapiReverseSendSettings(), FreqTracker::webapiReverseSendSettings(), UDPSink::webapiReverseSendSettings(), RemoteSource::webapiReverseSendSettings(), UDPSource::webapiReverseSendSettings(), NFMDemod::webapiReverseSendSettings(), DSDDemod::webapiReverseSendSettings(), BFMDemod::webapiReverseSendSettings(), WFMMod::webapiReverseSendSettings(), AMMod::webapiReverseSendSettings(), SSBDemod::webapiReverseSendSettings(), NFMMod::webapiReverseSendSettings(), FreeDVMod::webapiReverseSendSettings(), SSBMod::webapiReverseSendSettings(), FreeDVDemod::webapiReverseSendSettings(), FileSource::webapiReverseSendSettings(), and ATVMod::webapiReverseSendSettings().
{
     this->originator_channel_index = originator_channel_index;
     this->m_originator_channel_index_isSet = true;
 }
setOriginatorDeviceSetIndex()
void SWGSDRangel::SWGChannelSettings::setOriginatorDeviceSetIndex (qint32 originator_device_set_index)
Definition at line 395 of file SWGChannelSettings.cpp.
References m_originator_device_set_index_isSet, and originator_device_set_index.
Referenced by LocalSink::webapiReverseSendSettings(), LocalSource::webapiReverseSendSettings(), RemoteSink::webapiReverseSendSettings(), WFMDemod::webapiReverseSendSettings(), AMDemod::webapiReverseSendSettings(), FreqTracker::webapiReverseSendSettings(), UDPSink::webapiReverseSendSettings(), RemoteSource::webapiReverseSendSettings(), UDPSource::webapiReverseSendSettings(), NFMDemod::webapiReverseSendSettings(), DSDDemod::webapiReverseSendSettings(), BFMDemod::webapiReverseSendSettings(), WFMMod::webapiReverseSendSettings(), AMMod::webapiReverseSendSettings(), SSBDemod::webapiReverseSendSettings(), NFMMod::webapiReverseSendSettings(), FreeDVMod::webapiReverseSendSettings(), SSBMod::webapiReverseSendSettings(), FreeDVDemod::webapiReverseSendSettings(), FileSource::webapiReverseSendSettings(), and ATVMod::webapiReverseSendSettings().
{
     this->originator_device_set_index = originator_device_set_index;
     this->m_originator_device_set_index_isSet = true;
 }
setRemoteSinkSettings()
void SWGSDRangel::SWGChannelSettings::setRemoteSinkSettings (SWGRemoteSinkSettings * remote_sink_settings)
Definition at line 545 of file SWGChannelSettings.cpp.
References m_remote_sink_settings_isSet, and remote_sink_settings.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), RemoteSink::webapiReverseSendSettings(), and RemoteSink::webapiSettingsGet().
{
     this->remote_sink_settings = remote_sink_settings;
     this->m_remote_sink_settings_isSet = true;
 }
setRemoteSourceSettings()
void SWGSDRangel::SWGChannelSettings::setRemoteSourceSettings (SWGRemoteSourceSettings * remote_source_settings)
Definition at line 555 of file SWGChannelSettings.cpp.
References m_remote_source_settings_isSet, and remote_source_settings.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), RemoteSource::webapiReverseSendSettings(), and RemoteSource::webapiSettingsGet().
{
     this->remote_source_settings = remote_source_settings;
     this->m_remote_source_settings_isSet = true;
 }
setSsbDemodSettings()
void SWGSDRangel::SWGChannelSettings::setSsbDemodSettings (SWGSSBDemodSettings * ssb_demod_settings)
Definition at line 575 of file SWGChannelSettings.cpp.
References m_ssb_demod_settings_isSet, and ssb_demod_settings.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), SSBDemod::webapiReverseSendSettings(), and SSBDemod::webapiSettingsGet().
{
     this->ssb_demod_settings = ssb_demod_settings;
     this->m_ssb_demod_settings_isSet = true;
 }
setSsbModSettings()
void SWGSDRangel::SWGChannelSettings::setSsbModSettings (SWGSSBModSettings * ssb_mod_settings)
Definition at line 565 of file SWGChannelSettings.cpp.
References m_ssb_mod_settings_isSet, and ssb_mod_settings.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), SSBMod::webapiReverseSendCWSettings(), SSBMod::webapiReverseSendSettings(), and SSBMod::webapiSettingsGet().
{
     this->ssb_mod_settings = ssb_mod_settings;
     this->m_ssb_mod_settings_isSet = true;
 }
setUdpSinkSettings()
void SWGSDRangel::SWGChannelSettings::setUdpSinkSettings (SWGUDPSinkSettings * udp_sink_settings)
Definition at line 595 of file SWGChannelSettings.cpp.
References m_udp_sink_settings_isSet, and udp_sink_settings.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), UDPSink::webapiReverseSendSettings(), and UDPSink::webapiSettingsGet().
{
     this->udp_sink_settings = udp_sink_settings;
     this->m_udp_sink_settings_isSet = true;
 }
setUdpSourceSettings()
void SWGSDRangel::SWGChannelSettings::setUdpSourceSettings (SWGUDPSourceSettings * udp_source_settings)
Definition at line 585 of file SWGChannelSettings.cpp.
References m_udp_source_settings_isSet, and udp_source_settings.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), UDPSource::webapiReverseSendSettings(), and UDPSource::webapiSettingsGet().
{
     this->udp_source_settings = udp_source_settings;
     this->m_udp_source_settings_isSet = true;
 }
setWfmDemodSettings()
void SWGSDRangel::SWGChannelSettings::setWfmDemodSettings (SWGWFMDemodSettings * wfm_demod_settings)
Definition at line 605 of file SWGChannelSettings.cpp.
References m_wfm_demod_settings_isSet, and wfm_demod_settings.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), WFMDemod::webapiReverseSendSettings(), and WFMDemod::webapiSettingsGet().
{
     this->wfm_demod_settings = wfm_demod_settings;
     this->m_wfm_demod_settings_isSet = true;
 }
setWfmModSettings()
void SWGSDRangel::SWGChannelSettings::setWfmModSettings (SWGWFMModSettings * wfm_mod_settings)
Definition at line 615 of file SWGChannelSettings.cpp.
References m_wfm_mod_settings_isSet, and wfm_mod_settings.
Referenced by WebAPIRequestMapper::resetChannelSettings(), WebAPIRequestMapper::validateChannelSettings(), WFMMod::webapiReverseSendCWSettings(), WFMMod::webapiReverseSendSettings(), and WFMMod::webapiSettingsGet().
{
     this->wfm_mod_settings = wfm_mod_settings;
     this->m_wfm_mod_settings_isSet = true;
 }
Member Data Documentation
am_demod_settings
SWGAMDemodSettings* SWGSDRangel::SWGChannelSettings::am_demod_settings private
Definition at line 157 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getAmDemodSettings(), init(), isSet(), setAmDemodSettings(), and SWGChannelSettings().
am_mod_settings
SWGAMModSettings* SWGSDRangel::SWGChannelSettings::am_mod_settings private
Definition at line 160 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getAmModSettings(), init(), isSet(), setAmModSettings(), and SWGChannelSettings().
atv_mod_settings
SWGATVModSettings* SWGSDRangel::SWGChannelSettings::atv_mod_settings private
Definition at line 163 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getAtvModSettings(), init(), isSet(), setAtvModSettings(), and SWGChannelSettings().
bfm_demod_settings
SWGBFMDemodSettings* SWGSDRangel::SWGChannelSettings::bfm_demod_settings private
Definition at line 166 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getBfmDemodSettings(), init(), isSet(), setBfmDemodSettings(), and SWGChannelSettings().
channel_type
QString* SWGSDRangel::SWGChannelSettings::channel_type private
Definition at line 145 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getChannelType(), init(), isSet(), setChannelType(), and SWGChannelSettings().
direction
qint32 SWGSDRangel::SWGChannelSettings::direction private
Definition at line 148 of file SWGChannelSettings.h.
Referenced by asJsonObject(), fromJsonObject(), getDirection(), init(), setDirection(), and SWGChannelSettings().
dsd_demod_settings
SWGDSDDemodSettings* SWGSDRangel::SWGChannelSettings::dsd_demod_settings private
Definition at line 169 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getDsdDemodSettings(), init(), isSet(), setDsdDemodSettings(), and SWGChannelSettings().
file_source_settings
SWGFileSourceSettings* SWGSDRangel::SWGChannelSettings::file_source_settings private
Definition at line 172 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFileSourceSettings(), init(), isSet(), setFileSourceSettings(), and SWGChannelSettings().
free_dv_demod_settings
SWGFreeDVDemodSettings* SWGSDRangel::SWGChannelSettings::free_dv_demod_settings private
Definition at line 175 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFreeDvDemodSettings(), init(), isSet(), setFreeDvDemodSettings(), and SWGChannelSettings().
free_dv_mod_settings
SWGFreeDVModSettings* SWGSDRangel::SWGChannelSettings::free_dv_mod_settings private
Definition at line 178 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFreeDvModSettings(), init(), isSet(), setFreeDvModSettings(), and SWGChannelSettings().
freq_tracker_settings
SWGFreqTrackerSettings* SWGSDRangel::SWGChannelSettings::freq_tracker_settings private
Definition at line 181 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFreqTrackerSettings(), init(), isSet(), setFreqTrackerSettings(), and SWGChannelSettings().
local_sink_settings
SWGLocalSinkSettings* SWGSDRangel::SWGChannelSettings::local_sink_settings private
Definition at line 190 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getLocalSinkSettings(), init(), isSet(), setLocalSinkSettings(), and SWGChannelSettings().
local_source_settings
SWGLocalSourceSettings* SWGSDRangel::SWGChannelSettings::local_source_settings private
Definition at line 193 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getLocalSourceSettings(), init(), isSet(), setLocalSourceSettings(), and SWGChannelSettings().
m_am_demod_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_am_demod_settings_isSet private
Definition at line 158 of file SWGChannelSettings.h.
Referenced by init(), setAmDemodSettings(), and SWGChannelSettings().
m_am_mod_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_am_mod_settings_isSet private
Definition at line 161 of file SWGChannelSettings.h.
Referenced by init(), setAmModSettings(), and SWGChannelSettings().
m_atv_mod_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_atv_mod_settings_isSet private
Definition at line 164 of file SWGChannelSettings.h.
Referenced by init(), setAtvModSettings(), and SWGChannelSettings().
m_bfm_demod_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_bfm_demod_settings_isSet private
Definition at line 167 of file SWGChannelSettings.h.
Referenced by init(), setBfmDemodSettings(), and SWGChannelSettings().
m_channel_type_isSet
bool SWGSDRangel::SWGChannelSettings::m_channel_type_isSet private
Definition at line 146 of file SWGChannelSettings.h.
Referenced by init(), setChannelType(), and SWGChannelSettings().
m_direction_isSet
bool SWGSDRangel::SWGChannelSettings::m_direction_isSet private
Definition at line 149 of file SWGChannelSettings.h.
Referenced by asJsonObject(), init(), isSet(), setDirection(), and SWGChannelSettings().
m_dsd_demod_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_dsd_demod_settings_isSet private
Definition at line 170 of file SWGChannelSettings.h.
Referenced by init(), setDsdDemodSettings(), and SWGChannelSettings().
m_file_source_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_file_source_settings_isSet private
Definition at line 173 of file SWGChannelSettings.h.
Referenced by init(), setFileSourceSettings(), and SWGChannelSettings().
m_free_dv_demod_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_free_dv_demod_settings_isSet private
Definition at line 176 of file SWGChannelSettings.h.
Referenced by init(), setFreeDvDemodSettings(), and SWGChannelSettings().
m_free_dv_mod_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_free_dv_mod_settings_isSet private
Definition at line 179 of file SWGChannelSettings.h.
Referenced by init(), setFreeDvModSettings(), and SWGChannelSettings().
m_freq_tracker_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_freq_tracker_settings_isSet private
Definition at line 182 of file SWGChannelSettings.h.
Referenced by init(), setFreqTrackerSettings(), and SWGChannelSettings().
m_local_sink_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_local_sink_settings_isSet private
Definition at line 191 of file SWGChannelSettings.h.
Referenced by init(), setLocalSinkSettings(), and SWGChannelSettings().
m_local_source_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_local_source_settings_isSet private
Definition at line 194 of file SWGChannelSettings.h.
Referenced by init(), setLocalSourceSettings(), and SWGChannelSettings().
m_nfm_demod_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_nfm_demod_settings_isSet private
Definition at line 185 of file SWGChannelSettings.h.
Referenced by init(), setNfmDemodSettings(), and SWGChannelSettings().
m_nfm_mod_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_nfm_mod_settings_isSet private
Definition at line 188 of file SWGChannelSettings.h.
Referenced by init(), setNfmModSettings(), and SWGChannelSettings().
m_originator_channel_index_isSet
bool SWGSDRangel::SWGChannelSettings::m_originator_channel_index_isSet private
Definition at line 155 of file SWGChannelSettings.h.
Referenced by asJsonObject(), init(), isSet(), setOriginatorChannelIndex(), and SWGChannelSettings().
m_originator_device_set_index_isSet
bool SWGSDRangel::SWGChannelSettings::m_originator_device_set_index_isSet private
Definition at line 152 of file SWGChannelSettings.h.
Referenced by asJsonObject(), init(), isSet(), setOriginatorDeviceSetIndex(), and SWGChannelSettings().
m_remote_sink_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_remote_sink_settings_isSet private
Definition at line 197 of file SWGChannelSettings.h.
Referenced by init(), setRemoteSinkSettings(), and SWGChannelSettings().
m_remote_source_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_remote_source_settings_isSet private
Definition at line 200 of file SWGChannelSettings.h.
Referenced by init(), setRemoteSourceSettings(), and SWGChannelSettings().
m_ssb_demod_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_ssb_demod_settings_isSet private
Definition at line 206 of file SWGChannelSettings.h.
Referenced by init(), setSsbDemodSettings(), and SWGChannelSettings().
m_ssb_mod_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_ssb_mod_settings_isSet private
Definition at line 203 of file SWGChannelSettings.h.
Referenced by init(), setSsbModSettings(), and SWGChannelSettings().
m_udp_sink_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_udp_sink_settings_isSet private
Definition at line 212 of file SWGChannelSettings.h.
Referenced by init(), setUdpSinkSettings(), and SWGChannelSettings().
m_udp_source_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_udp_source_settings_isSet private
Definition at line 209 of file SWGChannelSettings.h.
Referenced by init(), setUdpSourceSettings(), and SWGChannelSettings().
m_wfm_demod_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_wfm_demod_settings_isSet private
Definition at line 215 of file SWGChannelSettings.h.
Referenced by init(), setWfmDemodSettings(), and SWGChannelSettings().
m_wfm_mod_settings_isSet
bool SWGSDRangel::SWGChannelSettings::m_wfm_mod_settings_isSet private
Definition at line 218 of file SWGChannelSettings.h.
Referenced by init(), setWfmModSettings(), and SWGChannelSettings().
nfm_demod_settings
SWGNFMDemodSettings* SWGSDRangel::SWGChannelSettings::nfm_demod_settings private
Definition at line 184 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getNfmDemodSettings(), init(), isSet(), setNfmDemodSettings(), and SWGChannelSettings().
nfm_mod_settings
SWGNFMModSettings* SWGSDRangel::SWGChannelSettings::nfm_mod_settings private
Definition at line 187 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getNfmModSettings(), init(), isSet(), setNfmModSettings(), and SWGChannelSettings().
originator_channel_index
qint32 SWGSDRangel::SWGChannelSettings::originator_channel_index private
Definition at line 154 of file SWGChannelSettings.h.
Referenced by asJsonObject(), fromJsonObject(), getOriginatorChannelIndex(), init(), setOriginatorChannelIndex(), and SWGChannelSettings().
originator_device_set_index
qint32 SWGSDRangel::SWGChannelSettings::originator_device_set_index private
Definition at line 151 of file SWGChannelSettings.h.
Referenced by asJsonObject(), fromJsonObject(), getOriginatorDeviceSetIndex(), init(), setOriginatorDeviceSetIndex(), and SWGChannelSettings().
remote_sink_settings
SWGRemoteSinkSettings* SWGSDRangel::SWGChannelSettings::remote_sink_settings private
Definition at line 196 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getRemoteSinkSettings(), init(), isSet(), setRemoteSinkSettings(), and SWGChannelSettings().
remote_source_settings
SWGRemoteSourceSettings* SWGSDRangel::SWGChannelSettings::remote_source_settings private
Definition at line 199 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getRemoteSourceSettings(), init(), isSet(), setRemoteSourceSettings(), and SWGChannelSettings().
ssb_demod_settings
SWGSSBDemodSettings* SWGSDRangel::SWGChannelSettings::ssb_demod_settings private
Definition at line 205 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSsbDemodSettings(), init(), isSet(), setSsbDemodSettings(), and SWGChannelSettings().
ssb_mod_settings
SWGSSBModSettings* SWGSDRangel::SWGChannelSettings::ssb_mod_settings private
Definition at line 202 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getSsbModSettings(), init(), isSet(), setSsbModSettings(), and SWGChannelSettings().
udp_sink_settings
SWGUDPSinkSettings* SWGSDRangel::SWGChannelSettings::udp_sink_settings private
Definition at line 211 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getUdpSinkSettings(), init(), isSet(), setUdpSinkSettings(), and SWGChannelSettings().
udp_source_settings
SWGUDPSourceSettings* SWGSDRangel::SWGChannelSettings::udp_source_settings private
Definition at line 208 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getUdpSourceSettings(), init(), isSet(), setUdpSourceSettings(), and SWGChannelSettings().
wfm_demod_settings
SWGWFMDemodSettings* SWGSDRangel::SWGChannelSettings::wfm_demod_settings private
Definition at line 214 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getWfmDemodSettings(), init(), isSet(), setWfmDemodSettings(), and SWGChannelSettings().
wfm_mod_settings
SWGWFMModSettings* SWGSDRangel::SWGChannelSettings::wfm_mod_settings private
Definition at line 217 of file SWGChannelSettings.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getWfmModSettings(), init(), isSet(), setWfmModSettings(), and SWGChannelSettings().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGChannelSettings.h
swagger/sdrangel/code/qt5/client/SWGChannelSettings.cpp