SDRAngel: qrtplib::RTPSourceData Class Reference
qrtplib::RTPSourceData Class Reference
#include <rtpsourcedata.h>
Public Member Functions
RTPPacket * GetNextPacket ()
void FlushPackets ()
bool HasData () const
uint32_t GetSSRC () const
bool IsOwnSSRC () const
bool IsCSRC () const
bool IsSender () const
bool IsValidated () const
bool IsActive () const
void SetProcessedInRTCP (bool v)
bool IsProcessedInRTCP () const
bool IsRTPAddressSet () const
bool IsRTCPAddressSet () const
const RTPAddress * GetRTPDataAddress () const
const RTPAddress * GetRTCPDataAddress () const
bool ReceivedBYE () const
uint8_t * GetBYEReason (std::size_t *len) const
RTPTime GetBYETime () const
void SetTimestampUnit (double tsu)
double GetTimestampUnit () const
bool SR_HasInfo () const
RTPNTPTime SR_GetNTPTimestamp () const
uint32_t SR_GetRTPTimestamp () const
uint32_t SR_GetPacketCount () const
uint32_t SR_GetByteCount () const
RTPTime SR_GetReceiveTime () const
bool SR_Prev_HasInfo () const
RTPNTPTime SR_Prev_GetNTPTimestamp () const
uint32_t SR_Prev_GetRTPTimestamp () const
uint32_t SR_Prev_GetPacketCount () const
uint32_t SR_Prev_GetByteCount () const
RTPTime SR_Prev_GetReceiveTime () const
bool RR_HasInfo () const
double RR_GetFractionLost () const
int32_t RR_GetPacketsLost () const
uint32_t RR_GetExtendedHighestSequenceNumber () const
uint32_t RR_GetJitter () const
uint32_t RR_GetLastSRTimestamp () const
uint32_t RR_GetDelaySinceLastSR () const
RTPTime RR_GetReceiveTime () const
bool RR_Prev_HasInfo () const
double RR_Prev_GetFractionLost () const
int32_t RR_Prev_GetPacketsLost () const
uint32_t RR_Prev_GetExtendedHighestSequenceNumber () const
uint32_t RR_Prev_GetJitter () const
uint32_t RR_Prev_GetLastSRTimestamp () const
uint32_t RR_Prev_GetDelaySinceLastSR () const
RTPTime RR_Prev_GetReceiveTime () const
bool INF_HasSentData () const
int32_t INF_GetNumPacketsReceived () const
uint32_t INF_GetBaseSequenceNumber () const
uint32_t INF_GetExtendedHighestSequenceNumber () const
uint32_t INF_GetJitter () const
RTPTime INF_GetLastMessageTime () const
RTPTime INF_GetLastRTPPacketTime () const
double INF_GetEstimatedTimestampUnit () const
uint32_t INF_GetNumPacketsReceivedInInterval () const
uint32_t INF_GetSavedExtendedSequenceNumber () const
void INF_StartNewInterval ()
RTPTime INF_GetRoundtripTime () const
RTPTime INF_GetLastSDESNoteTime () const
uint8_t * SDES_GetCNAME (std::size_t *len) const
uint8_t * SDES_GetName (std::size_t *len) const
uint8_t * SDES_GetEMail (std::size_t *len) const
uint8_t * SDES_GetPhone (std::size_t *len) const
uint8_t * SDES_GetLocation (std::size_t *len) const
uint8_t * SDES_GetTool (std::size_t *len) const
uint8_t * SDES_GetNote (std::size_t *len) const
void SDES_GotoFirstPrivateValue ()
bool SDES_GetNextPrivateValue (uint8_t **prefix, std::size_t *prefixlen, uint8_t **value, std::size_t *valuelen)
bool SDES_GetPrivateValue (uint8_t *prefix, std::size_t prefixlen, uint8_t **value, std::size_t *valuelen) const
Protected Member Functions
RTPSourceData (uint32_t ssrc)
virtual ~RTPSourceData ()
Protected Attributes
std::list< RTPPacket * > packetlist
uint32_t ssrc
bool ownssrc
bool iscsrc
double timestampunit
bool receivedbye
bool validated
bool processedinrtcp
bool issender
RTCPSenderReportInfo SRinf
RTCPSenderReportInfo SRprevinf
RTCPReceiverReportInfo RRinf
RTCPReceiverReportInfo RRprevinf
RTPSourceStats stats
RTCPSDESInfo SDESinf
bool isrtpaddrset
bool isrtcpaddrset
RTPAddress * rtpaddr
RTPAddress * rtcpaddr
RTPTime byetime
uint8_t * byereason
std::size_t byereasonlen
Detailed Description
Describes an entry in the RTPSources source table.
Definition at line 283 of file rtpsourcedata.h.
Constructor & Destructor Documentation
RTPSourceData()
qrtplib::RTPSourceData::RTPSourceData (uint32_t ssrc) protected
Definition at line 198 of file rtpsourcedata.cpp.
References byereason, byereasonlen, iscsrc, isrtcpaddrset, isrtpaddrset, issender, ownssrc, processedinrtcp, receivedbye, rtcpaddr, rtpaddr, ssrc, timestampunit, and validated.
                                        :
         byetime(0, 0)
 {
     ssrc = s;
     issender = false;
     iscsrc = false;
     timestampunit = -1;
     receivedbye = false;
     byereason = 0;
     byereasonlen = 0;
     rtpaddr = 0;
     rtcpaddr = 0;
     ownssrc = false;
     validated = false;
     processedinrtcp = false;
     isrtpaddrset = false;
     isrtcpaddrset = false;
 }
~RTPSourceData()
qrtplib::RTPSourceData::~RTPSourceData () protected virtual
Definition at line 217 of file rtpsourcedata.cpp.
References byereason, FlushPackets(), rtcpaddr, and rtpaddr.
 {
     FlushPackets();
     if (byereason)
         delete[] byereason;
     if (rtpaddr)
         delete rtpaddr;
     if (rtcpaddr)
         delete rtcpaddr;
 }
Member Function Documentation
FlushPackets()
void qrtplib::RTPSourceData::FlushPackets () inline
Clears the participant's RTP packet list.
Definition at line 789 of file rtpsourcedata.h.
Referenced by ~RTPSourceData().
 {
     std::list<RTPPacket *>::const_iterator it;
     for (it = packetlist.begin(); it != packetlist.end(); ++it)
         delete *it;
     packetlist.clear();
 }
GetBYEReason()
uint8_t* qrtplib::RTPSourceData::GetBYEReason (std::size_t * len) const inline
Returns the reason for leaving contained in the BYE packet of this participant. Returns the reason for leaving contained in the BYE packet of this participant. The length of the reason is stored in len.
Definition at line 410 of file rtpsourcedata.h.
     {
         *len = byereasonlen;
         return byereason;
     }
GetBYETime()
RTPTime qrtplib::RTPSourceData::GetBYETime () const inline
Returns the time at which the BYE packet was received.
Definition at line 417 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::BYETimeout(), and qrtplib::RTPSources::MultipleTimeouts().
     {
         return byetime;
     }
GetNextPacket()
RTPPacket * qrtplib::RTPSourceData::GetNextPacket () inline
Extracts the first packet of this participants RTP packet queue.
Definition at line 775 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::GetNextPacket().
 {
     if (!validated)
         return 0;
     RTPPacket *p;
     if (packetlist.empty())
         return 0;
     p = *(packetlist.begin());
     packetlist.pop_front();
     return p;
 }
GetRTCPDataAddress()
const RTPAddress* qrtplib::RTPSourceData::GetRTCPDataAddress () const inline
Returns the address from which this participant's RTCP packets originate. Returns the address from which this participant's RTCP packets originate. If the address has been set and the returned value is NULL, this indicates that it originated from the local participant.
Definition at line 395 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::CheckCollision().
     {
         return rtcpaddr;
     }
GetRTPDataAddress()
const RTPAddress* qrtplib::RTPSourceData::GetRTPDataAddress () const inline
Returns the address from which this participant's RTP packets originate. Returns the address from which this participant's RTP packets originate. If the address has been set and the returned value is NULL, this indicates that it originated from the local participant.
Definition at line 385 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::CheckCollision().
     {
         return rtpaddr;
     }
GetSSRC()
uint32_t qrtplib::RTPSourceData::GetSSRC () const inline
Returns the SSRC identifier for this member.
Definition at line 304 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::DeleteOwnSSRC(), qrtplib::RTCPPacketBuilder::FillInReportBlocks(), and qrtplib::RTPSources::ProcessRTCPCompoundPacket().
     {
         return ssrc;
     }
GetTimestampUnit()
double qrtplib::RTPSourceData::GetTimestampUnit () const inline
Returns the timestamp unit used for this participant.
Definition at line 434 of file rtpsourcedata.h.
     {
         return timestampunit;
     }
HasData()
bool qrtplib::RTPSourceData::HasData () const inline
Returns true if there are RTP packets which can be extracted.
Definition at line 296 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::GotoFirstSourceWithData(), qrtplib::RTPSources::GotoNextSourceWithData(), and qrtplib::RTPSources::GotoPreviousSourceWithData().
     {
         if (!validated)
             return false;
         return packetlist.empty() ? false : true;
     }
INF_GetBaseSequenceNumber()
uint32_t qrtplib::RTPSourceData::INF_GetBaseSequenceNumber () const inline
Returns the base sequence number of this participant.
Definition at line 622 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         return stats.GetBaseSequenceNumber();
     }
INF_GetEstimatedTimestampUnit()
double qrtplib::RTPSourceData::INF_GetEstimatedTimestampUnit () const
Returns the estimated timestamp unit, calculated from two consecutive sender reports.
Definition at line 228 of file rtpsourcedata.cpp.
References qrtplib::RTPTime::GetDouble(), qrtplib::RTCPSenderReportInfo::GetNTPTimestamp(), qrtplib::RTCPSenderReportInfo::GetRTPTimestamp(), qrtplib::RTCPSenderReportInfo::HasInfo(), qrtplib::RTPTime::IsZero(), SRinf, and SRprevinf.
Referenced by qrtplib::RTPInternalSourceData::ProcessRTPPacket().
 {
     if (!SRprevinf.HasInfo())
         return -1.0;
     RTPTime t1 = RTPTime(SRinf.GetNTPTimestamp());
     RTPTime t2 = RTPTime(SRprevinf.GetNTPTimestamp());
     if (t1.IsZero() || t2.IsZero()) // one of the times couldn't be calculated
         return -1.0;
     if (t1 <= t2)
         return -1.0;
     t1 -= t2; // get the time difference
     uint32_t tsdiff = SRinf.GetRTPTimestamp() - SRprevinf.GetRTPTimestamp();
     return (t1.GetDouble() / ((double) tsdiff));
 }
INF_GetExtendedHighestSequenceNumber()
uint32_t qrtplib::RTPSourceData::INF_GetExtendedHighestSequenceNumber () const inline
Returns the extended highest sequence number received from this participant.
Definition at line 628 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         return stats.GetExtendedHighestSequenceNumber();
     }
INF_GetJitter()
uint32_t qrtplib::RTPSourceData::INF_GetJitter () const inline
Returns the current jitter value for this participant.
Definition at line 634 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         return stats.GetJitter();
     }
INF_GetLastMessageTime()
RTPTime qrtplib::RTPSourceData::INF_GetLastMessageTime () const inline
Returns the time at which something was last heard from this member.
Definition at line 640 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::MultipleTimeouts(), and qrtplib::RTPSources::Timeout().
     {
         return stats.GetLastMessageTime();
     }
INF_GetLastRTPPacketTime()
RTPTime qrtplib::RTPSourceData::INF_GetLastRTPPacketTime () const inline
Returns the time at which the last RTP packet was received.
Definition at line 646 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks(), qrtplib::RTPSources::MultipleTimeouts(), and qrtplib::RTPSources::SenderTimeout().
     {
         return stats.GetLastRTPPacketTime();
     }
INF_GetLastSDESNoteTime()
RTPTime qrtplib::RTPSourceData::INF_GetLastSDESNoteTime () const inline
Returns the time at which the last SDES NOTE item was received.
Definition at line 678 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::MultipleTimeouts(), and qrtplib::RTPSources::NoteTimeout().
     {
         return stats.GetLastNoteTime();
     }
INF_GetNumPacketsReceived()
int32_t qrtplib::RTPSourceData::INF_GetNumPacketsReceived () const inline
Returns the total number of received packets from this participant.
Definition at line 616 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         return stats.GetNumPacketsReceived();
     }
INF_GetNumPacketsReceivedInInterval()
uint32_t qrtplib::RTPSourceData::INF_GetNumPacketsReceivedInInterval () const inline
Returns the number of packets received since a new interval was started with INF_StartNewInterval.
Definition at line 655 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         return stats.GetNumPacketsReceivedInInterval();
     }
INF_GetRoundtripTime()
RTPTime qrtplib::RTPSourceData::INF_GetRoundtripTime () const
Estimates the round trip time by using the LSR and DLSR info from the last receiver report.
Definition at line 248 of file rtpsourcedata.cpp.
References qrtplib::RTCPReceiverReportInfo::GetDelaySinceLastSR(), qrtplib::RTCPReceiverReportInfo::GetLastSRTimestamp(), qrtplib::RTPNTPTime::GetLSW(), qrtplib::RTPNTPTime::GetMSW(), qrtplib::RTPTime::GetNTPTime(), qrtplib::RTCPReceiverReportInfo::GetReceiveTime(), qrtplib::RTCPReceiverReportInfo::HasInfo(), and RRinf.
 {
     if (!RRinf.HasInfo())
         return RTPTime(0, 0);
     if (RRinf.GetDelaySinceLastSR() == 0 && RRinf.GetLastSRTimestamp() == 0)
         return RTPTime(0, 0);
     RTPNTPTime recvtime = RRinf.GetReceiveTime().GetNTPTime();
     uint32_t rtt = ((recvtime.GetMSW() & 0xFFFF) << 16) | ((recvtime.GetLSW() >> 16) & 0xFFFF);
     rtt -= RRinf.GetLastSRTimestamp();
     rtt -= RRinf.GetDelaySinceLastSR();
     double drtt = (((double) rtt) / 65536.0);
     return RTPTime(drtt);
 }
INF_GetSavedExtendedSequenceNumber()
uint32_t qrtplib::RTPSourceData::INF_GetSavedExtendedSequenceNumber () const inline
Returns the extended sequence number which was stored by the INF_StartNewInterval call.
Definition at line 661 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         return stats.GetSavedExtendedSequenceNumber();
     }
INF_HasSentData()
bool qrtplib::RTPSourceData::INF_HasSentData () const inline
Returns true if validated RTP packets have been received from this participant.
Definition at line 610 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         return stats.HasSentData();
     }
INF_StartNewInterval()
void qrtplib::RTPSourceData::INF_StartNewInterval () inline
Starts a new interval to count received packets in; this also stores the current extended highest sequence number to be able to calculate the packet loss during the interval.
Definition at line 669 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         stats.StartNewInterval();
     }
IsActive()
bool qrtplib::RTPSourceData::IsActive () const inline
Returns true if the source was validated and had not yet sent a BYE packet.
Definition at line 339 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::BYETimeout(), qrtplib::RTPSources::DeleteOwnSSRC(), qrtplib::RTPSources::MultipleTimeouts(), qrtplib::RTPSources::NoteTimeout(), qrtplib::RTPSources::ProcessBYE(), qrtplib::RTPSources::ProcessRTPPacket(), qrtplib::RTPSources::ProcessSDESNormalItem(), qrtplib::RTPSources::SenderTimeout(), and qrtplib::RTPSources::Timeout().
     {
         if (!validated)
             return false;
         if (receivedbye)
             return false;
         return true;
     }
IsCSRC()
bool qrtplib::RTPSourceData::IsCSRC () const inline
Returns true if the source identifier is actually a CSRC from an RTP packet.
Definition at line 318 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         return iscsrc;
     }
IsOwnSSRC()
bool qrtplib::RTPSourceData::IsOwnSSRC () const inline
Returns true if the participant was added using the RTPSources member function CreateOwnSSRC and returns false otherwise.
Definition at line 312 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks(), and qrtplib::RTPSessionSources::OnSSRCCollision().
     {
         return ownssrc;
     }
IsProcessedInRTCP()
bool qrtplib::RTPSourceData::IsProcessedInRTCP () const inline
This function is used by the RTCPPacketBuilder class and returns whether this participant has been processed in a report block or not.
Definition at line 359 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         return processedinrtcp;
     }
IsRTCPAddressSet()
bool qrtplib::RTPSourceData::IsRTCPAddressSet () const inline
Returns true if the address from which this participant's RTCP packets originate has already been set.
Definition at line 375 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::CheckCollision().
     {
         return isrtcpaddrset;
     }
IsRTPAddressSet()
bool qrtplib::RTPSourceData::IsRTPAddressSet () const inline
Returns true if the address from which this participant's RTP packets originate has already been set.
Definition at line 367 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::CheckCollision().
     {
         return isrtpaddrset;
     }
IsSender()
bool qrtplib::RTPSourceData::IsSender () const inline
Returns true if this member is marked as a sender and false if not.
Definition at line 324 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::BuildBYEPacket(), qrtplib::RTCPPacketBuilder::BuildNextPacket(), qrtplib::RTPSources::BYETimeout(), qrtplib::RTCPScheduler::CalculateNextRTCPTime(), qrtplib::RTPSources::DeleteOwnSSRC(), qrtplib::RTCPScheduler::IsTime(), qrtplib::RTPSources::MultipleTimeouts(), qrtplib::RTPSources::NoteTimeout(), qrtplib::RTPSources::ProcessRTPPacket(), qrtplib::RTPSources::SenderTimeout(), qrtplib::RTPSources::SentRTPPacket(), and qrtplib::RTPSources::Timeout().
     {
         return issender;
     }
IsValidated()
bool qrtplib::RTPSourceData::IsValidated () const inline
Returns true if the participant is validated, which is the case if a number of consecutive RTP packets have been received or if a CNAME item has been received for this participant.
Definition at line 333 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::ProcessRTPPacket().
     {
         return validated;
     }
ReceivedBYE()
bool qrtplib::RTPSourceData::ReceivedBYE () const inline
Returns true if we received a BYE message for this participant and false otherwise.
Definition at line 401 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::BYETimeout(), and qrtplib::RTPSources::MultipleTimeouts().
     {
         return receivedbye;
     }
RR_GetDelaySinceLastSR()
uint32_t qrtplib::RTPSourceData::RR_GetDelaySinceLastSR () const inline
Returns the DLSR value from the last report.
Definition at line 548 of file rtpsourcedata.h.
     {
         return RRinf.GetDelaySinceLastSR();
     }
RR_GetExtendedHighestSequenceNumber()
uint32_t qrtplib::RTPSourceData::RR_GetExtendedHighestSequenceNumber () const inline
Returns the extended highest sequence number contained in the last report.
Definition at line 530 of file rtpsourcedata.h.
     {
         return RRinf.GetExtendedHighestSequenceNumber();
     }
RR_GetFractionLost()
double qrtplib::RTPSourceData::RR_GetFractionLost () const inline
Returns the fraction lost value from the last report.
Definition at line 518 of file rtpsourcedata.h.
     {
         return RRinf.GetFractionLost();
     }
RR_GetJitter()
uint32_t qrtplib::RTPSourceData::RR_GetJitter () const inline
Returns the jitter value from the last report.
Definition at line 536 of file rtpsourcedata.h.
     {
         return RRinf.GetJitter();
     }
RR_GetLastSRTimestamp()
uint32_t qrtplib::RTPSourceData::RR_GetLastSRTimestamp () const inline
Returns the LSR value from the last report.
Definition at line 542 of file rtpsourcedata.h.
     {
         return RRinf.GetLastSRTimestamp();
     }
RR_GetPacketsLost()
int32_t qrtplib::RTPSourceData::RR_GetPacketsLost () const inline
Returns the number of lost packets contained in the last report.
Definition at line 524 of file rtpsourcedata.h.
     {
         return RRinf.GetPacketsLost();
     }
RR_GetReceiveTime()
RTPTime qrtplib::RTPSourceData::RR_GetReceiveTime () const inline
Returns the time at which the last report was received.
Definition at line 554 of file rtpsourcedata.h.
     {
         return RRinf.GetReceiveTime();
     }
RR_HasInfo()
bool qrtplib::RTPSourceData::RR_HasInfo () const inline
Returns true if this participant sent a receiver report with information about the reception of our data.
Definition at line 512 of file rtpsourcedata.h.
     {
         return RRinf.HasInfo();
     }
RR_Prev_GetDelaySinceLastSR()
uint32_t qrtplib::RTPSourceData::RR_Prev_GetDelaySinceLastSR () const inline
Returns the DLSR value from the second to last report.
Definition at line 598 of file rtpsourcedata.h.
     {
         return RRprevinf.GetDelaySinceLastSR();
     }
RR_Prev_GetExtendedHighestSequenceNumber()
uint32_t qrtplib::RTPSourceData::RR_Prev_GetExtendedHighestSequenceNumber () const inline
Returns the extended highest sequence number contained in the second to last report.
Definition at line 580 of file rtpsourcedata.h.
     {
         return RRprevinf.GetExtendedHighestSequenceNumber();
     }
RR_Prev_GetFractionLost()
double qrtplib::RTPSourceData::RR_Prev_GetFractionLost () const inline
Returns the fraction lost value from the second to last report.
Definition at line 568 of file rtpsourcedata.h.
     {
         return RRprevinf.GetFractionLost();
     }
RR_Prev_GetJitter()
uint32_t qrtplib::RTPSourceData::RR_Prev_GetJitter () const inline
Returns the jitter value from the second to last report.
Definition at line 586 of file rtpsourcedata.h.
     {
         return RRprevinf.GetJitter();
     }
RR_Prev_GetLastSRTimestamp()
uint32_t qrtplib::RTPSourceData::RR_Prev_GetLastSRTimestamp () const inline
Returns the LSR value from the second to last report.
Definition at line 592 of file rtpsourcedata.h.
     {
         return RRprevinf.GetLastSRTimestamp();
     }
RR_Prev_GetPacketsLost()
int32_t qrtplib::RTPSourceData::RR_Prev_GetPacketsLost () const inline
Returns the number of lost packets contained in the second to last report.
Definition at line 574 of file rtpsourcedata.h.
     {
         return RRprevinf.GetPacketsLost();
     }
RR_Prev_GetReceiveTime()
RTPTime qrtplib::RTPSourceData::RR_Prev_GetReceiveTime () const inline
Returns the time at which the second to last report was received.
Definition at line 604 of file rtpsourcedata.h.
     {
         return RRprevinf.GetReceiveTime();
     }
RR_Prev_HasInfo()
bool qrtplib::RTPSourceData::RR_Prev_HasInfo () const inline
Returns true if this participant sent more than one receiver report with information about the reception of our data.
Definition at line 562 of file rtpsourcedata.h.
     {
         return RRprevinf.HasInfo();
     }
SDES_GetCNAME()
uint8_t* qrtplib::RTPSourceData::SDES_GetCNAME (std::size_t * len) const inline
Returns a pointer to the SDES CNAME item of this participant and stores its length in len.
Definition at line 684 of file rtpsourcedata.h.
     {
         return SDESinf.GetCNAME(len);
     }
SDES_GetEMail()
uint8_t* qrtplib::RTPSourceData::SDES_GetEMail (std::size_t * len) const inline
Returns a pointer to the SDES e-mail item of this participant and stores its length in len.
Definition at line 696 of file rtpsourcedata.h.
     {
         return SDESinf.GetEMail(len);
     }
SDES_GetLocation()
uint8_t* qrtplib::RTPSourceData::SDES_GetLocation (std::size_t * len) const inline
Returns a pointer to the SDES location item of this participant and stores its length in len.
Definition at line 708 of file rtpsourcedata.h.
     {
         return SDESinf.GetLocation(len);
     }
SDES_GetName()
uint8_t* qrtplib::RTPSourceData::SDES_GetName (std::size_t * len) const inline
Returns a pointer to the SDES name item of this participant and stores its length in len.
Definition at line 690 of file rtpsourcedata.h.
     {
         return SDESinf.GetName(len);
     }
SDES_GetNextPrivateValue()
bool qrtplib::RTPSourceData::SDES_GetNextPrivateValue (uint8_t ** prefix, std::size_t * prefixlen, uint8_t ** value, std::size_t * valuelen) inline
If available, returns true and stores the next SDES private item prefix in prefix and its length in prefixlen; the associated value and its length are then stored in value and valuelen.
Definition at line 735 of file rtpsourcedata.h.
     {
         return SDESinf.GetNextPrivateValue(prefix, prefixlen, value, valuelen);
     }
SDES_GetNote()
uint8_t* qrtplib::RTPSourceData::SDES_GetNote (std::size_t * len) const inline
Returns a pointer to the SDES note item of this participant and stores its length in len.
Definition at line 720 of file rtpsourcedata.h.
Referenced by qrtplib::RTPSources::MultipleTimeouts(), and qrtplib::RTPSources::NoteTimeout().
     {
         return SDESinf.GetNote(len);
     }
SDES_GetPhone()
uint8_t* qrtplib::RTPSourceData::SDES_GetPhone (std::size_t * len) const inline
Returns a pointer to the SDES phone item of this participant and stores its length in len.
Definition at line 702 of file rtpsourcedata.h.
     {
         return SDESinf.GetPhone(len);
     }
SDES_GetPrivateValue()
bool qrtplib::RTPSourceData::SDES_GetPrivateValue (uint8_t * prefix, std::size_t prefixlen, uint8_t ** value, std::size_t * valuelen) const inline
Looks for the entry which corresponds to the SDES private item prefix prefix with length prefixlen; if found, the function returns true and stores the associated value and its length in value and valuelen respectively.
Definition at line 744 of file rtpsourcedata.h.
     {
         return SDESinf.GetPrivateValue(prefix, prefixlen, value, valuelen);
     }
SDES_GetTool()
uint8_t* qrtplib::RTPSourceData::SDES_GetTool (std::size_t * len) const inline
Returns a pointer to the SDES tool item of this participant and stores its length in len.
Definition at line 714 of file rtpsourcedata.h.
     {
         return SDESinf.GetTool(len);
     }
SDES_GotoFirstPrivateValue()
void qrtplib::RTPSourceData::SDES_GotoFirstPrivateValue () inline
Starts the iteration over the stored SDES private item prefixes and their associated values.
Definition at line 727 of file rtpsourcedata.h.
     {
         SDESinf.GotoFirstPrivateValue();
     }
SetProcessedInRTCP()
void qrtplib::RTPSourceData::SetProcessedInRTCP (bool v) inline
This function is used by the RTCPPacketBuilder class to mark whether this participant's information has been processed in a report block or not.
Definition at line 351 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::ClearAllSourceFlags(), and qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         processedinrtcp = v;
     }
SetTimestampUnit()
void qrtplib::RTPSourceData::SetTimestampUnit (double tsu) inline
Sets the value for the timestamp unit to be used in jitter calculations for data received from this participant. Sets the value for the timestamp unit to be used in jitter calculations for data received from this participant. If not set, the library uses an approximation for the timestamp unit which is calculated from two consecutive RTCP sender reports. The timestamp unit is defined as a time interval divided by the corresponding timestamp interval. For 8000 Hz audio this would be 1/8000. For video, often a timestamp unit of 1/90000 is used.
Definition at line 428 of file rtpsourcedata.h.
     {
         timestampunit = tsu;
     }
SR_GetByteCount()
uint32_t qrtplib::RTPSourceData::SR_GetByteCount () const inline
Returns the octet count contained in the last sender report.
Definition at line 464 of file rtpsourcedata.h.
     {
         return SRinf.GetByteCount();
     }
SR_GetNTPTimestamp()
RTPNTPTime qrtplib::RTPSourceData::SR_GetNTPTimestamp () const inline
Returns the NTP timestamp contained in the last sender report.
Definition at line 446 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         return SRinf.GetNTPTimestamp();
     }
SR_GetPacketCount()
uint32_t qrtplib::RTPSourceData::SR_GetPacketCount () const inline
Returns the packet count contained in the last sender report.
Definition at line 458 of file rtpsourcedata.h.
     {
         return SRinf.GetPacketCount();
     }
SR_GetReceiveTime()
RTPTime qrtplib::RTPSourceData::SR_GetReceiveTime () const inline
Returns the time at which the last sender report was received.
Definition at line 470 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         return SRinf.GetReceiveTime();
     }
SR_GetRTPTimestamp()
uint32_t qrtplib::RTPSourceData::SR_GetRTPTimestamp () const inline
Returns the RTP timestamp contained in the last sender report.
Definition at line 452 of file rtpsourcedata.h.
     {
         return SRinf.GetRTPTimestamp();
     }
SR_HasInfo()
bool qrtplib::RTPSourceData::SR_HasInfo () const inline
Returns true if an RTCP sender report has been received from this participant.
Definition at line 440 of file rtpsourcedata.h.
Referenced by qrtplib::RTCPPacketBuilder::FillInReportBlocks().
     {
         return SRinf.HasInfo();
     }
SR_Prev_GetByteCount()
uint32_t qrtplib::RTPSourceData::SR_Prev_GetByteCount () const inline
Returns the octet count contained in the second to last sender report.
Definition at line 500 of file rtpsourcedata.h.
     {
         return SRprevinf.GetByteCount();
     }
SR_Prev_GetNTPTimestamp()
RTPNTPTime qrtplib::RTPSourceData::SR_Prev_GetNTPTimestamp () const inline
Returns the NTP timestamp contained in the second to last sender report.
Definition at line 482 of file rtpsourcedata.h.
     {
         return SRprevinf.GetNTPTimestamp();
     }
SR_Prev_GetPacketCount()
uint32_t qrtplib::RTPSourceData::SR_Prev_GetPacketCount () const inline
Returns the packet count contained in the second to last sender report.
Definition at line 494 of file rtpsourcedata.h.
     {
         return SRprevinf.GetPacketCount();
     }
SR_Prev_GetReceiveTime()
RTPTime qrtplib::RTPSourceData::SR_Prev_GetReceiveTime () const inline
Returns the time at which the second to last sender report was received.
Definition at line 506 of file rtpsourcedata.h.
     {
         return SRprevinf.GetReceiveTime();
     }
SR_Prev_GetRTPTimestamp()
uint32_t qrtplib::RTPSourceData::SR_Prev_GetRTPTimestamp () const inline
Returns the RTP timestamp contained in the second to last sender report.
Definition at line 488 of file rtpsourcedata.h.
     {
         return SRprevinf.GetRTPTimestamp();
     }
SR_Prev_HasInfo()
bool qrtplib::RTPSourceData::SR_Prev_HasInfo () const inline
Returns true if more than one RTCP sender report has been received.
Definition at line 476 of file rtpsourcedata.h.
     {
         return SRprevinf.HasInfo();
     }
Member Data Documentation
byereason
uint8_t* qrtplib::RTPSourceData::byereason protected
Definition at line 771 of file rtpsourcedata.h.
Referenced by qrtplib::RTPInternalSourceData::ProcessBYEPacket(), RTPSourceData(), and ~RTPSourceData().
byereasonlen
std::size_t qrtplib::RTPSourceData::byereasonlen protected
Definition at line 772 of file rtpsourcedata.h.
Referenced by qrtplib::RTPInternalSourceData::ProcessBYEPacket(), and RTPSourceData().
byetime
RTPTime qrtplib::RTPSourceData::byetime protected
Definition at line 770 of file rtpsourcedata.h.
Referenced by qrtplib::RTPInternalSourceData::ProcessBYEPacket().
iscsrc
bool qrtplib::RTPSourceData::iscsrc protected
Definition at line 755 of file rtpsourcedata.h.
Referenced by RTPSourceData().
isrtcpaddrset
bool qrtplib::RTPSourceData::isrtcpaddrset protected
Definition at line 767 of file rtpsourcedata.h.
Referenced by RTPSourceData().
isrtpaddrset
bool qrtplib::RTPSourceData::isrtpaddrset protected
Definition at line 767 of file rtpsourcedata.h.
Referenced by RTPSourceData().
issender
bool qrtplib::RTPSourceData::issender protected
Definition at line 760 of file rtpsourcedata.h.
Referenced by qrtplib::RTPInternalSourceData::ProcessRTPPacket(), and RTPSourceData().
ownssrc
bool qrtplib::RTPSourceData::ownssrc protected
Definition at line 754 of file rtpsourcedata.h.
Referenced by qrtplib::RTPInternalSourceData::ProcessRTPPacket(), and RTPSourceData().
packetlist
std::list<RTPPacket *> qrtplib::RTPSourceData::packetlist protected
Definition at line 751 of file rtpsourcedata.h.
Referenced by qrtplib::RTPInternalSourceData::ProcessRTPPacket().
processedinrtcp
bool qrtplib::RTPSourceData::processedinrtcp protected
Definition at line 759 of file rtpsourcedata.h.
Referenced by RTPSourceData().
receivedbye
bool qrtplib::RTPSourceData::receivedbye protected
Definition at line 757 of file rtpsourcedata.h.
Referenced by qrtplib::RTPInternalSourceData::ProcessBYEPacket(), and RTPSourceData().
RRinf
RTCPReceiverReportInfo qrtplib::RTPSourceData::RRinf protected
Definition at line 763 of file rtpsourcedata.h.
Referenced by INF_GetRoundtripTime().
RRprevinf
RTCPReceiverReportInfo qrtplib::RTPSourceData::RRprevinf protected
Definition at line 763 of file rtpsourcedata.h.
rtcpaddr
RTPAddress * qrtplib::RTPSourceData::rtcpaddr protected
Definition at line 768 of file rtpsourcedata.h.
Referenced by RTPSourceData(), and ~RTPSourceData().
rtpaddr
RTPAddress* qrtplib::RTPSourceData::rtpaddr protected
Definition at line 768 of file rtpsourcedata.h.
Referenced by RTPSourceData(), and ~RTPSourceData().
SDESinf
RTCPSDESInfo qrtplib::RTPSourceData::SDESinf protected
Definition at line 765 of file rtpsourcedata.h.
Referenced by qrtplib::RTPInternalSourceData::ProcessPrivateSDESItem(), and qrtplib::RTPInternalSourceData::ProcessSDESItem().
SRinf
RTCPSenderReportInfo qrtplib::RTPSourceData::SRinf protected
Definition at line 762 of file rtpsourcedata.h.
Referenced by INF_GetEstimatedTimestampUnit().
SRprevinf
RTCPSenderReportInfo qrtplib::RTPSourceData::SRprevinf protected
Definition at line 762 of file rtpsourcedata.h.
Referenced by INF_GetEstimatedTimestampUnit().
ssrc
uint32_t qrtplib::RTPSourceData::ssrc protected
Definition at line 753 of file rtpsourcedata.h.
Referenced by RTPSourceData().
stats
RTPSourceStats qrtplib::RTPSourceData::stats protected
Definition at line 764 of file rtpsourcedata.h.
Referenced by qrtplib::RTPInternalSourceData::ProcessBYEPacket(), qrtplib::RTPInternalSourceData::ProcessPrivateSDESItem(), qrtplib::RTPInternalSourceData::ProcessRTPPacket(), and qrtplib::RTPInternalSourceData::ProcessSDESItem().
timestampunit
double qrtplib::RTPSourceData::timestampunit protected
Definition at line 756 of file rtpsourcedata.h.
Referenced by qrtplib::RTPInternalSourceData::ProcessRTPPacket(), and RTPSourceData().
validated
bool qrtplib::RTPSourceData::validated protected
Definition at line 758 of file rtpsourcedata.h.
Referenced by qrtplib::RTPInternalSourceData::ProcessRTPPacket(), qrtplib::RTPInternalSourceData::ProcessSDESItem(), and RTPSourceData().
The documentation for this class was generated from the following files:
qrtplib/rtpsourcedata.h
qrtplib/rtpsourcedata.cpp