SDRAngel: SWGSDRangel::SWGFrequencyRange Class Reference
SWGSDRangel::SWGFrequencyRange Class Reference
#include <SWGFrequencyRange.h>
Public Member Functions
SWGFrequencyRange ()
SWGFrequencyRange (QString *json)
virtual ~SWGFrequencyRange ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGFrequencyRange * fromJson (QString &jsonString) override
qint64 getMin ()
void setMin (qint64 min)
qint64 getMax ()
void setMax (qint64 max)
qint32 getStep ()
void setStep (qint32 step)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint64 min
bool m_min_isSet
qint64 max
bool m_max_isSet
qint32 step
bool m_step_isSet
Detailed Description
Definition at line 31 of file SWGFrequencyRange.h.
Constructor & Destructor Documentation
SWGFrequencyRange() [1/2]
SWGSDRangel::SWGFrequencyRange::SWGFrequencyRange ()
Definition at line 30 of file SWGFrequencyRange.cpp.
References m_max_isSet, m_min_isSet, m_step_isSet, max, min, and step.
{
     min = 0L;
     m_min_isSet = false;
     max = 0L;
     m_max_isSet = false;
     step = 0;
     m_step_isSet = false;
 }
SWGFrequencyRange() [2/2]
SWGSDRangel::SWGFrequencyRange::SWGFrequencyRange (QString * json)
Definition at line 25 of file SWGFrequencyRange.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGFrequencyRange()
SWGSDRangel::SWGFrequencyRange::~SWGFrequencyRange () virtual
Definition at line 39 of file SWGFrequencyRange.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGFrequencyRange::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 80 of file SWGFrequencyRange.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGFrequencyRange::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 91 of file SWGFrequencyRange.cpp.
References m_max_isSet, m_min_isSet, m_step_isSet, max, min, and step.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_min_isSet){
         obj->insert("min", QJsonValue(min));
     }
     if(m_max_isSet){
         obj->insert("max", QJsonValue(max));
     }
     if(m_step_isSet){
         obj->insert("step", QJsonValue(step));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGFrequencyRange::cleanup ()
Definition at line 54 of file SWGFrequencyRange.cpp.
Referenced by ~SWGFrequencyRange().
{
 }
fromJson()
SWGFrequencyRange * SWGSDRangel::SWGFrequencyRange::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 61 of file SWGFrequencyRange.cpp.
References fromJsonObject().
Referenced by SWGFrequencyRange().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGFrequencyRange::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 70 of file SWGFrequencyRange.cpp.
References max, min, SWGSDRangel::setValue(), and step.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&min, pJson["min"], "qint64", "");
     ::SWGSDRangel::setValue(&max, pJson["max"], "qint64", "");
     ::SWGSDRangel::setValue(&step, pJson["step"], "qint32", "");
 }
getMax()
qint64 SWGSDRangel::SWGFrequencyRange::getMax ()
Definition at line 117 of file SWGFrequencyRange.cpp.
References max.
{
     return max;
 }
getMin()
qint64 SWGSDRangel::SWGFrequencyRange::getMin ()
Definition at line 107 of file SWGFrequencyRange.cpp.
References min.
{
     return min;
 }
getStep()
qint32 SWGSDRangel::SWGFrequencyRange::getStep ()
Definition at line 127 of file SWGFrequencyRange.cpp.
References step.
{
     return step;
 }
init()
void SWGSDRangel::SWGFrequencyRange::init ()
Definition at line 44 of file SWGFrequencyRange.cpp.
References m_max_isSet, m_min_isSet, m_step_isSet, max, min, and step.
Referenced by SWGFrequencyRange().
{
     min = 0L;
     m_min_isSet = false;
     max = 0L;
     m_max_isSet = false;
     step = 0;
     m_step_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGFrequencyRange::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 138 of file SWGFrequencyRange.cpp.
References m_max_isSet, m_min_isSet, and m_step_isSet.
Referenced by SWGSDRangel::SWGBladeRF2OutputReport::asJsonObject(), SWGSDRangel::SWGBladeRF2InputReport::asJsonObject(), SWGSDRangel::SWGBladeRF2OutputReport::isSet(), and SWGSDRangel::SWGBladeRF2InputReport::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(m_min_isSet){ isObjectUpdated = true; break;}
         if(m_max_isSet){ isObjectUpdated = true; break;}
         if(m_step_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setMax()
void SWGSDRangel::SWGFrequencyRange::setMax (qint64 max)
Definition at line 121 of file SWGFrequencyRange.cpp.
References m_max_isSet, and max.
Referenced by BladeRF2Output::webapiFormatDeviceReport(), and BladeRF2Input::webapiFormatDeviceReport().
{
     this->max = max;
     this->m_max_isSet = true;
 }
setMin()
void SWGSDRangel::SWGFrequencyRange::setMin (qint64 min)
Definition at line 111 of file SWGFrequencyRange.cpp.
References m_min_isSet, and min.
Referenced by BladeRF2Output::webapiFormatDeviceReport(), and BladeRF2Input::webapiFormatDeviceReport().
{
     this->min = min;
     this->m_min_isSet = true;
 }
setStep()
void SWGSDRangel::SWGFrequencyRange::setStep (qint32 step)
Definition at line 131 of file SWGFrequencyRange.cpp.
References m_step_isSet, and step.
Referenced by BladeRF2Output::webapiFormatDeviceReport(), and BladeRF2Input::webapiFormatDeviceReport().
{
     this->step = step;
     this->m_step_isSet = true;
 }
Member Data Documentation
m_max_isSet
bool SWGSDRangel::SWGFrequencyRange::m_max_isSet private
Definition at line 61 of file SWGFrequencyRange.h.
Referenced by asJsonObject(), init(), isSet(), setMax(), and SWGFrequencyRange().
m_min_isSet
bool SWGSDRangel::SWGFrequencyRange::m_min_isSet private
Definition at line 58 of file SWGFrequencyRange.h.
Referenced by asJsonObject(), init(), isSet(), setMin(), and SWGFrequencyRange().
m_step_isSet
bool SWGSDRangel::SWGFrequencyRange::m_step_isSet private
Definition at line 64 of file SWGFrequencyRange.h.
Referenced by asJsonObject(), init(), isSet(), setStep(), and SWGFrequencyRange().
max
qint64 SWGSDRangel::SWGFrequencyRange::max private
Definition at line 60 of file SWGFrequencyRange.h.
Referenced by asJsonObject(), fromJsonObject(), getMax(), init(), setMax(), and SWGFrequencyRange().
min
qint64 SWGSDRangel::SWGFrequencyRange::min private
Definition at line 57 of file SWGFrequencyRange.h.
Referenced by asJsonObject(), fromJsonObject(), getMin(), init(), setMin(), and SWGFrequencyRange().
step
qint32 SWGSDRangel::SWGFrequencyRange::step private
Definition at line 63 of file SWGFrequencyRange.h.
Referenced by asJsonObject(), fromJsonObject(), getStep(), init(), setStep(), and SWGFrequencyRange().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGFrequencyRange.h
swagger/sdrangel/code/qt5/client/SWGFrequencyRange.cpp