SDRAngel: WebAPIRequestMapper Class Reference
WebAPIRequestMapper Class Reference
#include <webapirequestmapper.h>
Public Member Functions
WebAPIRequestMapper (QObject *parent=0)
~WebAPIRequestMapper ()
void service (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void setAdapter (WebAPIAdapterInterface *adapter)
Public Member Functions inherited from qtwebapp::HttpRequestHandler
HttpRequestHandler (QObject *parent=NULL)
virtual ~HttpRequestHandler ()
Private Member Functions
void instanceSummaryService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceConfigService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceDevicesService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceChannelsService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceLoggingService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceAudioService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceAudioInputParametersService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceAudioOutputParametersService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceAudioInputCleanupService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceAudioOutputCleanupService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceLocationService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceDVSerialService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceAMBESerialService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceAMBEDevicesService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instancePresetsService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instancePresetService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instancePresetFileService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceDeviceSetsService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void instanceDeviceSetService (qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void devicesetService (const std::string &indexStr, qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void devicesetFocusService (const std::string &indexStr, qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void devicesetDeviceService (const std::string &indexStr, qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void devicesetDeviceSettingsService (const std::string &indexStr, qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void devicesetDeviceRunService (const std::string &indexStr, qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void devicesetDeviceReportService (const std::string &indexStr, qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void devicesetChannelsReportService (const std::string &deviceSetIndexStr, qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void devicesetChannelService (const std::string &deviceSetIndexStr, qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void devicesetChannelIndexService (const std::string &deviceSetIndexStr, const std::string &channelIndexStr, qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void devicesetChannelSettingsService (const std::string &deviceSetIndexStr, const std::string &channelIndexStr, qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
void devicesetChannelReportService (const std::string &deviceSetIndexStr, const std::string &channelIndexStr, qtwebapp::HttpRequest &request, qtwebapp::HttpResponse &response)
bool validatePresetTransfer (SWGSDRangel::SWGPresetTransfer &presetTransfer)
bool validatePresetIdentifer (SWGSDRangel::SWGPresetIdentifier &presetIdentifier)
bool validatePresetExport (SWGSDRangel::SWGPresetExport &presetExport)
bool validateDeviceListItem (SWGSDRangel::SWGDeviceListItem &deviceListItem, QJsonObject &jsonObject)
bool validateDeviceSettings (SWGSDRangel::SWGDeviceSettings &deviceSettings, QJsonObject &jsonObject, QStringList &deviceSettingsKeys)
bool validateChannelSettings (SWGSDRangel::SWGChannelSettings &deviceSettings, QJsonObject &jsonObject, QStringList &channelSettingsKeys)
bool validateAudioInputDevice (SWGSDRangel::SWGAudioInputDevice &audioInputDevice, QJsonObject &jsonObject, QStringList &audioInputDeviceKeys)
bool validateAudioOutputDevice (SWGSDRangel::SWGAudioOutputDevice &audioOutputDevice, QJsonObject &jsonObject, QStringList &audioOutputDeviceKeys)
bool validateAMBEDevices (SWGSDRangel::SWGAMBEDevices &ambeDevices, QJsonObject &jsonObject)
void appendSettingsSubKeys (const QJsonObject &parentSettingsJsonObject, QJsonObject &childSettingsJsonObject, const QString &parentKey, QStringList &keyList)
void appendSettingsArrayKeys (const QJsonObject &parentSettingsJsonObject, const QString &parentKey, QStringList &keyList)
bool parseJsonBody (QString &jsonStr, QJsonObject &jsonObject, qtwebapp::HttpResponse &response)
void resetDeviceSettings (SWGSDRangel::SWGDeviceSettings &deviceSettings)
void resetDeviceReport (SWGSDRangel::SWGDeviceReport &deviceReport)
void resetChannelSettings (SWGSDRangel::SWGChannelSettings &deviceSettings)
void resetChannelReport (SWGSDRangel::SWGChannelReport &deviceSettings)
void resetAudioInputDevice (SWGSDRangel::SWGAudioInputDevice &audioInputDevice)
void resetAudioOutputDevice (SWGSDRangel::SWGAudioOutputDevice &audioOutputDevice)
Private Attributes
WebAPIAdapterInterface * m_adapter
qtwebapp::StaticFileController * m_staticFileController
Detailed Description
Definition at line 39 of file webapirequestmapper.h.
Constructor & Destructor Documentation
WebAPIRequestMapper()
WebAPIRequestMapper::WebAPIRequestMapper (QObject * parent = 0)
Definition at line 50 of file webapirequestmapper.cpp.
References m_staticFileController, and qtwebapp::HttpDocrootSettings::path.
                                                         :
     HttpRequestHandler(parent),
     m_adapter(0)
 {
 #ifndef _MSC_VER
     Q_INIT_RESOURCE(webapi);
 #endif
     qtwebapp::HttpDocrootSettings docrootSettings;
     docrootSettings.path = ":/webapi";
     m_staticFileController = new qtwebapp::StaticFileController(docrootSettings, parent);
 }
~WebAPIRequestMapper()
WebAPIRequestMapper::~WebAPIRequestMapper ()
Definition at line 62 of file webapirequestmapper.cpp.
References m_staticFileController.
 {
     delete m_staticFileController;
 #ifndef _MSC_VER
     Q_CLEANUP_RESOURCE(webapi);
 #endif
 }
Member Function Documentation
appendSettingsArrayKeys()
void WebAPIRequestMapper::appendSettingsArrayKeys (const QJsonObject & parentSettingsJsonObject, const QString & parentKey, QStringList & keyList) private
Definition at line 2785 of file webapirequestmapper.cpp.
References arg(), and i.
Referenced by validateDeviceSettings().
 {
     QJsonArray streams = parentSettingsJsonObject[parentKey].toArray();
     for (int istream = 0; istream < streams.count(); istream++)
     {
         QJsonValue v = streams.takeAt(istream);
         if (v.isObject())
         {
             QJsonObject streamSettingsJsonObject = v.toObject();
             QStringList streamSettingsKeys = streamSettingsJsonObject.keys();
             for (int i = 0; i < streamSettingsKeys.size(); i++) {
                 keyList.append(tr("streams[%1].%2").arg(istream).arg(streamSettingsKeys[i]));
             }
         }
     }
 }
appendSettingsSubKeys()
void WebAPIRequestMapper::appendSettingsSubKeys (const QJsonObject & parentSettingsJsonObject, QJsonObject & childSettingsJsonObject, const QString & parentKey, QStringList & keyList) private
Definition at line 2771 of file webapirequestmapper.cpp.
References i.
Referenced by validateChannelSettings().
 {
     childSettingsJsonObject = parentSettingsJsonObject[parentKey].toObject();
     QStringList childSettingsKeys = childSettingsJsonObject.keys();
     for (int i = 0; i < childSettingsKeys.size(); i++) {
         keyList.append(parentKey + QString(".") + childSettingsKeys.at(i));
     }
 }
devicesetChannelIndexService()
void WebAPIRequestMapper::devicesetChannelIndexService (const std::string & deviceSetIndexStr, const std::string & channelIndexStr, qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 1557 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGSuccessResponse::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), WebAPIAdapterInterface::devicesetChannelDelete(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     try
     {
         int deviceSetIndex = boost::lexical_cast<int>(deviceSetIndexStr);
         int channelIndex = boost::lexical_cast<int>(channelIndexStr);
         if (request.getMethod() == "DELETE")
         {
             SWGSDRangel::SWGSuccessResponse normalResponse;
             int status = m_adapter->devicesetChannelDelete(deviceSetIndex, channelIndex, normalResponse, errorResponse);
             response.setStatus(status);
             if (status/100 == 2) {
                 response.write(normalResponse.asJson().toUtf8());
             } else {
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(405,"Invalid HTTP method");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid HTTP method";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     catch (const boost::bad_lexical_cast &e)
     {
         errorResponse.init();
         *errorResponse.getMessage() = "Wrong integer conversion on index";
         response.setStatus(400,"Invalid data");
         response.write(errorResponse.asJson().toUtf8());
     }
 }
devicesetChannelReportService()
void WebAPIRequestMapper::devicesetChannelReportService (const std::string & deviceSetIndexStr, const std::string & channelIndexStr, qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 1691 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGChannelReport::asJson(), WebAPIAdapterInterface::devicesetChannelReportGet(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), m_adapter, resetChannelReport(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     try
     {
         int deviceSetIndex = boost::lexical_cast<int>(deviceSetIndexStr);
         int channelIndex = boost::lexical_cast<int>(channelIndexStr);
         if (request.getMethod() == "GET")
         {
             SWGSDRangel::SWGChannelReport normalResponse;
             resetChannelReport(normalResponse);
             int status = m_adapter->devicesetChannelReportGet(deviceSetIndex, channelIndex, normalResponse, errorResponse);
             response.setStatus(status);
             if (status/100 == 2) {
                 response.write(normalResponse.asJson().toUtf8());
             } else {
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
     }
     catch (const boost::bad_lexical_cast &e)
     {
         errorResponse.init();
         *errorResponse.getMessage() = "Wrong integer conversion on index";
         response.setStatus(400,"Invalid data");
         response.write(errorResponse.asJson().toUtf8());
     }
 }
devicesetChannelService()
void WebAPIRequestMapper::devicesetChannelService (const std::string & deviceSetIndexStr, qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 1480 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGSuccessResponse::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), WebAPIAdapterInterface::devicesetChannelPost(), qtwebapp::HttpRequest::getBody(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), m_adapter, parseJsonBody(), resetChannelSettings(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     try
     {
         int deviceSetIndex = boost::lexical_cast<int>(deviceSetIndexStr);
         if (request.getMethod() == "POST")
         {
             QString jsonStr = request.getBody();
             QJsonObject jsonObject;
             if (parseJsonBody(jsonStr, jsonObject, response))
             {
                 SWGSDRangel::SWGChannelSettings query;
                 SWGSDRangel::SWGSuccessResponse normalResponse;
                 resetChannelSettings(query);
                 if (jsonObject.contains("direction")) {
                     query.setDirection(jsonObject["direction"].toInt());
                 } else {
                     query.setDirection(0); // assume Rx
                 }
                 if (jsonObject.contains("channelType") && jsonObject["channelType"].isString())
                 {
                     query.setChannelType(new QString(jsonObject["channelType"].toString()));
                     int status = m_adapter->devicesetChannelPost(deviceSetIndex, query, normalResponse, errorResponse);
                     response.setStatus(status);
                     if (status/100 == 2) {
                         response.write(normalResponse.asJson().toUtf8());
                     } else {
                         response.write(errorResponse.asJson().toUtf8());
                     }
                 }
                 else
                 {
                     response.setStatus(400,"Invalid JSON request");
                     errorResponse.init();
                     *errorResponse.getMessage() = "Invalid JSON request";
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else
             {
                 response.setStatus(400,"Invalid JSON format");
                 errorResponse.init();
                 *errorResponse.getMessage() = "Invalid JSON format";
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(405,"Invalid HTTP method");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid HTTP method";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     catch (const boost::bad_lexical_cast &e)
     {
         errorResponse.init();
         *errorResponse.getMessage() = "Wrong integer conversion on index";
         response.setStatus(400,"Invalid data");
         response.write(errorResponse.asJson().toUtf8());
     }
 }
devicesetChannelSettingsService()
void WebAPIRequestMapper::devicesetChannelSettingsService (const std::string & deviceSetIndexStr, const std::string & channelIndexStr, qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 1602 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGChannelSettings::asJson(), WebAPIAdapterInterface::devicesetChannelSettingsGet(), WebAPIAdapterInterface::devicesetChannelSettingsPutPatch(), qtwebapp::HttpRequest::getBody(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), m_adapter, parseJsonBody(), resetChannelSettings(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), validateChannelSettings(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     try
     {
         int deviceSetIndex = boost::lexical_cast<int>(deviceSetIndexStr);
         int channelIndex = boost::lexical_cast<int>(channelIndexStr);
         if (request.getMethod() == "GET")
         {
             SWGSDRangel::SWGChannelSettings normalResponse;
             resetChannelSettings(normalResponse);
             int status = m_adapter->devicesetChannelSettingsGet(deviceSetIndex, channelIndex, normalResponse, errorResponse);
             response.setStatus(status);
             if (status/100 == 2) {
                 response.write(normalResponse.asJson().toUtf8());
             } else {
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else if ((request.getMethod() == "PUT") || (request.getMethod() == "PATCH"))
         {
             QString jsonStr = request.getBody();
             QJsonObject jsonObject;
             if (parseJsonBody(jsonStr, jsonObject, response))
             {
                 SWGSDRangel::SWGChannelSettings normalResponse;
                 resetChannelSettings(normalResponse);
                 QStringList channelSettingsKeys;
                 if (validateChannelSettings(normalResponse, jsonObject, channelSettingsKeys))
                 {
                     int status = m_adapter->devicesetChannelSettingsPutPatch(
                             deviceSetIndex,
                             channelIndex,
                             (request.getMethod() == "PUT"), // force settings on PUT
                             channelSettingsKeys,
                             normalResponse,
                             errorResponse);
                     response.setStatus(status);
                     if (status/100 == 2) {
                         response.write(normalResponse.asJson().toUtf8());
                     } else {
                         response.write(errorResponse.asJson().toUtf8());
                     }
                 }
                 else
                 {
                     response.setStatus(400,"Invalid JSON request");
                     errorResponse.init();
                     *errorResponse.getMessage() = "Invalid JSON request";
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else
             {
                 response.setStatus(400,"Invalid JSON format");
                 errorResponse.init();
                 *errorResponse.getMessage() = "Invalid JSON format";
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(405,"Invalid HTTP method");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid HTTP method";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     catch (const boost::bad_lexical_cast &e)
     {
         errorResponse.init();
         *errorResponse.getMessage() = "Wrong integer conversion on index";
         response.setStatus(400,"Invalid data");
         response.write(errorResponse.asJson().toUtf8());
     }
 }
devicesetChannelsReportService()
void WebAPIRequestMapper::devicesetChannelsReportService (const std::string & deviceSetIndexStr, qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 1442 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGChannelsDetail::asJson(), WebAPIAdapterInterface::devicesetChannelsReportGet(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         try
         {
             SWGSDRangel::SWGChannelsDetail normalResponse;
             int deviceSetIndex = boost::lexical_cast<int>(indexStr);
             int status = m_adapter->devicesetChannelsReportGet(deviceSetIndex, normalResponse, errorResponse);
             response.setStatus(status);
             if (status/100 == 2) {
                 response.write(normalResponse.asJson().toUtf8());
             } else {
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         catch (const boost::bad_lexical_cast &e)
         {
             errorResponse.init();
             *errorResponse.getMessage() = "Wrong integer conversion on device set index";
             response.setStatus(400,"Invalid data");
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
devicesetDeviceReportService()
void WebAPIRequestMapper::devicesetDeviceReportService (const std::string & indexStr, qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 1403 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGDeviceReport::asJson(), WebAPIAdapterInterface::devicesetDeviceReportGet(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), m_adapter, resetDeviceReport(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         try
         {
             SWGSDRangel::SWGDeviceReport normalResponse;
             resetDeviceReport(normalResponse);
             int deviceSetIndex = boost::lexical_cast<int>(indexStr);
             int status = m_adapter->devicesetDeviceReportGet(deviceSetIndex, normalResponse, errorResponse);
             response.setStatus(status);
             if (status/100 == 2) {
                 response.write(normalResponse.asJson().toUtf8());
             } else {
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         catch (const boost::bad_lexical_cast &e)
         {
             errorResponse.init();
             *errorResponse.getMessage() = "Wrong integer conversion on device set index";
             response.setStatus(400,"Invalid data");
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
devicesetDeviceRunService()
void WebAPIRequestMapper::devicesetDeviceRunService (const std::string & indexStr, qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 1337 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGDeviceState::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), WebAPIAdapterInterface::devicesetDeviceRunDelete(), WebAPIAdapterInterface::devicesetDeviceRunGet(), WebAPIAdapterInterface::devicesetDeviceRunPost(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     try
     {
         int deviceSetIndex = boost::lexical_cast<int>(indexStr);
         if (request.getMethod() == "GET")
         {
             SWGSDRangel::SWGDeviceState normalResponse;
             int status = m_adapter->devicesetDeviceRunGet(deviceSetIndex, normalResponse, errorResponse);
             response.setStatus(status);
             if (status/100 == 2) {
                 response.write(normalResponse.asJson().toUtf8());
             } else {
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else if (request.getMethod() == "POST")
         {
             SWGSDRangel::SWGDeviceState normalResponse;
             int status = m_adapter->devicesetDeviceRunPost(deviceSetIndex, normalResponse, errorResponse);
             response.setStatus(status);
             if (status/100 == 2) {
                 response.write(normalResponse.asJson().toUtf8());
             } else {
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else if (request.getMethod() == "DELETE")
         {
             SWGSDRangel::SWGDeviceState normalResponse;
             int status = m_adapter->devicesetDeviceRunDelete(deviceSetIndex, normalResponse, errorResponse);
             response.setStatus(status);
             if (status/100 == 2) {
                 response.write(normalResponse.asJson().toUtf8());
             } else {
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(405,"Invalid HTTP method");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid HTTP method";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     catch (const boost::bad_lexical_cast &e)
     {
         errorResponse.init();
         *errorResponse.getMessage() = "Wrong integer conversion on device set index";
         response.setStatus(400,"Invalid data");
         response.write(errorResponse.asJson().toUtf8());
     }
 }
devicesetDeviceService()
void WebAPIRequestMapper::devicesetDeviceService (const std::string & indexStr, qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 1190 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGDeviceListItem::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), WebAPIAdapterInterface::devicesetDevicePut(), qtwebapp::HttpRequest::getBody(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), m_adapter, parseJsonBody(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), validateDeviceListItem(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     try
     {
         int deviceSetIndex = boost::lexical_cast<int>(indexStr);
         if (request.getMethod() == "PUT")
         {
             QString jsonStr = request.getBody();
             QJsonObject jsonObject;
             if (parseJsonBody(jsonStr, jsonObject, response))
             {
                 SWGSDRangel::SWGDeviceListItem query;
                 SWGSDRangel::SWGDeviceListItem normalResponse;
                 if (validateDeviceListItem(query, jsonObject))
                 {
                     int status = m_adapter->devicesetDevicePut(deviceSetIndex, query, normalResponse, errorResponse);
                     response.setStatus(status);
                     if (status/100 == 2) {
                         response.write(normalResponse.asJson().toUtf8());
                     } else {
                         response.write(errorResponse.asJson().toUtf8());
                     }
                 }
                 else
                 {
                     response.setStatus(400,"Missing device identification");
                     errorResponse.init();
                     *errorResponse.getMessage() = "Missing device identification";
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else
             {
                 response.setStatus(400,"Invalid JSON format");
                 errorResponse.init();
                 *errorResponse.getMessage() = "Invalid JSON format";
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(405,"Invalid HTTP method");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid HTTP method";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     catch (const boost::bad_lexical_cast &e)
     {
         errorResponse.init();
         *errorResponse.getMessage() = "Wrong integer conversion on device set index";
         response.setStatus(400,"Invalid data");
         response.write(errorResponse.asJson().toUtf8());
     }
 }
devicesetDeviceSettingsService()
void WebAPIRequestMapper::devicesetDeviceSettingsService (const std::string & indexStr, qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 1254 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGDeviceSettings::asJson(), WebAPIAdapterInterface::devicesetDeviceSettingsGet(), WebAPIAdapterInterface::devicesetDeviceSettingsPutPatch(), qtwebapp::HttpRequest::getBody(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), m_adapter, parseJsonBody(), resetDeviceSettings(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), validateDeviceSettings(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     try
     {
         int deviceSetIndex = boost::lexical_cast<int>(indexStr);
         if ((request.getMethod() == "PUT") || (request.getMethod() == "PATCH"))
         {
             QString jsonStr = request.getBody();
             QJsonObject jsonObject;
             if (parseJsonBody(jsonStr, jsonObject, response))
             {
                 SWGSDRangel::SWGDeviceSettings normalResponse;
                 resetDeviceSettings(normalResponse);
                 QStringList deviceSettingsKeys;
                 if (validateDeviceSettings(normalResponse, jsonObject, deviceSettingsKeys))
                 {
                     int status = m_adapter->devicesetDeviceSettingsPutPatch(
                             deviceSetIndex,
                             (request.getMethod() == "PUT"), // force settings on PUT
                             deviceSettingsKeys,
                             normalResponse,
                             errorResponse);
                     response.setStatus(status);
                     if (status/100 == 2) {
                         response.write(normalResponse.asJson().toUtf8());
                     } else {
                         response.write(errorResponse.asJson().toUtf8());
                     }
                 }
                 else
                 {
                     response.setStatus(400,"Invalid JSON request");
                     errorResponse.init();
                     *errorResponse.getMessage() = "Invalid JSON request";
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else
             {
                 response.setStatus(400,"Invalid JSON format");
                 errorResponse.init();
                 *errorResponse.getMessage() = "Invalid JSON format";
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else if (request.getMethod() == "GET")
         {
             SWGSDRangel::SWGDeviceSettings normalResponse;
             resetDeviceSettings(normalResponse);
             int status = m_adapter->devicesetDeviceSettingsGet(deviceSetIndex, normalResponse, errorResponse);
             response.setStatus(status);
             if (status/100 == 2) {
                 response.write(normalResponse.asJson().toUtf8());
             } else {
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(405,"Invalid HTTP method");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid HTTP method";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     catch (const boost::bad_lexical_cast &e)
     {
         errorResponse.init();
         *errorResponse.getMessage() = "Wrong integer conversion on device set index";
         response.setStatus(400,"Invalid data");
         response.write(errorResponse.asJson().toUtf8());
     }
 }
devicesetFocusService()
void WebAPIRequestMapper::devicesetFocusService (const std::string & indexStr, qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 1150 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGSuccessResponse::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), WebAPIAdapterInterface::devicesetFocusPatch(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     try
     {
         int deviceSetIndex = boost::lexical_cast<int>(indexStr);
         if (request.getMethod() == "PATCH")
         {
             SWGSDRangel::SWGSuccessResponse normalResponse;
             int status = m_adapter->devicesetFocusPatch(deviceSetIndex, normalResponse, errorResponse);
             response.setStatus(status);
             if (status/100 == 2) {
                 response.write(normalResponse.asJson().toUtf8());
             } else {
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(405,"Invalid HTTP method");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid HTTP method";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     catch (const boost::bad_lexical_cast &e)
     {
         errorResponse.init();
         *errorResponse.getMessage() = "Wrong integer conversion on device set index";
         response.setStatus(400,"Invalid data");
         response.write(errorResponse.asJson().toUtf8());
     }
 }
devicesetService()
void WebAPIRequestMapper::devicesetService (const std::string & indexStr, qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 1112 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGDeviceSet::asJson(), WebAPIAdapterInterface::devicesetGet(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         try
         {
             SWGSDRangel::SWGDeviceSet normalResponse;
             int deviceSetIndex = boost::lexical_cast<int>(indexStr);
             int status = m_adapter->devicesetGet(deviceSetIndex, normalResponse, errorResponse);
             response.setStatus(status);
             if (status/100 == 2) {
                 response.write(normalResponse.asJson().toUtf8());
             } else {
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         catch (const boost::bad_lexical_cast &e)
         {
             errorResponse.init();
             *errorResponse.getMessage() = "Wrong integer conversion on device set index";
             response.setStatus(400,"Invalid data");
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instanceAMBEDevicesService()
void WebAPIRequestMapper::instanceAMBEDevicesService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 673 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGSuccessResponse::asJson(), SWGSDRangel::SWGAMBEDevices::asJson(), qtwebapp::HttpRequest::getBody(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceAMBEDevicesDelete(), WebAPIAdapterInterface::instanceAMBEDevicesGet(), WebAPIAdapterInterface::instanceAMBEDevicesPatch(), WebAPIAdapterInterface::instanceAMBEDevicesPut(), m_adapter, parseJsonBody(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), validateAMBEDevices(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         SWGSDRangel::SWGAMBEDevices normalResponse;
         int status = m_adapter->instanceAMBEDevicesGet(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else if ((request.getMethod() == "PATCH") || (request.getMethod() == "PUT"))
     {
         SWGSDRangel::SWGAMBEDevices query;
         SWGSDRangel::SWGAMBEDevices normalResponse;
         QString jsonStr = request.getBody();
         QJsonObject jsonObject;
         if (parseJsonBody(jsonStr, jsonObject, response))
         {
             if (validateAMBEDevices(query, jsonObject))
             {
                 int status;
                 if (request.getMethod() == "PATCH") {
                     status = m_adapter->instanceAMBEDevicesPatch(query, normalResponse, errorResponse);
                 } else {
                     status = m_adapter->instanceAMBEDevicesPut(query, normalResponse, errorResponse);
                 }
                 response.setStatus(status);
                 if (status/100 == 2) {
                     response.write(normalResponse.asJson().toUtf8());
                 } else {
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else
             {
                 response.setStatus(400,"Invalid JSON request");
                 errorResponse.init();
                 *errorResponse.getMessage() = "Invalid JSON request";
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(400,"Invalid JSON format");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid JSON format";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else if (request.getMethod() == "DELETE")
     {
         SWGSDRangel::SWGSuccessResponse normalResponse;
         int status = m_adapter->instanceAMBEDevicesDelete(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instanceAMBESerialService()
void WebAPIRequestMapper::instanceAMBESerialService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 645 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGDVSerialDevices::asJson(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceAMBESerialGet(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         SWGSDRangel::SWGDVSerialDevices normalResponse;
         int status = m_adapter->instanceAMBESerialGet(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instanceAudioInputCleanupService()
void WebAPIRequestMapper::instanceAudioInputCleanupService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 535 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGSuccessResponse::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceAudioInputCleanupPatch(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "PATCH")
     {
         SWGSDRangel::SWGSuccessResponse normalResponse;
         int status = m_adapter->instanceAudioInputCleanupPatch(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instanceAudioInputParametersService()
void WebAPIRequestMapper::instanceAudioInputParametersService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 397 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGAudioInputDevice::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), qtwebapp::HttpRequest::getBody(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceAudioInputDelete(), WebAPIAdapterInterface::instanceAudioInputPatch(), m_adapter, parseJsonBody(), resetAudioInputDevice(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), validateAudioInputDevice(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     QString jsonStr = request.getBody();
     QJsonObject jsonObject;
     if (parseJsonBody(jsonStr, jsonObject, response))
     {
         SWGSDRangel::SWGAudioInputDevice normalResponse;
         resetAudioInputDevice(normalResponse);
         QStringList audioInputDeviceKeys;
         if (validateAudioInputDevice(normalResponse, jsonObject, audioInputDeviceKeys))
         {
             if (request.getMethod() == "PATCH")
             {
                 int status = m_adapter->instanceAudioInputPatch(
                         normalResponse,
                         audioInputDeviceKeys,
                         errorResponse);
                 response.setStatus(status);
                 if (status/100 == 2) {
                     response.write(normalResponse.asJson().toUtf8());
                 } else {
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else if (request.getMethod() == "DELETE")
             {
                 int status = m_adapter->instanceAudioInputDelete(
                         normalResponse,
                         errorResponse);
                 response.setStatus(status);
                 if (status/100 == 2) {
                     response.write(normalResponse.asJson().toUtf8());
                 } else {
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else
             {
                 response.setStatus(405,"Invalid HTTP method");
                 errorResponse.init();
                 *errorResponse.getMessage() = "Invalid HTTP method";
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(400,"Invalid JSON request");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid JSON request";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(400,"Invalid JSON format");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid JSON format";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instanceAudioOutputCleanupService()
void WebAPIRequestMapper::instanceAudioOutputCleanupService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 563 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGSuccessResponse::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceAudioOutputCleanupPatch(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "PATCH")
     {
         SWGSDRangel::SWGSuccessResponse normalResponse;
         int status = m_adapter->instanceAudioOutputCleanupPatch(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instanceAudioOutputParametersService()
void WebAPIRequestMapper::instanceAudioOutputParametersService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 466 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGAudioOutputDevice::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), qtwebapp::HttpRequest::getBody(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceAudioOutputDelete(), WebAPIAdapterInterface::instanceAudioOutputPatch(), m_adapter, parseJsonBody(), resetAudioOutputDevice(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), validateAudioOutputDevice(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     QString jsonStr = request.getBody();
     QJsonObject jsonObject;
     if (parseJsonBody(jsonStr, jsonObject, response))
     {
         SWGSDRangel::SWGAudioOutputDevice normalResponse;
         resetAudioOutputDevice(normalResponse);
         QStringList audioOutputDeviceKeys;
         if (validateAudioOutputDevice(normalResponse, jsonObject, audioOutputDeviceKeys))
         {
             if (request.getMethod() == "PATCH")
             {
                 int status = m_adapter->instanceAudioOutputPatch(
                         normalResponse,
                         audioOutputDeviceKeys,
                         errorResponse);
                 response.setStatus(status);
                 if (status/100 == 2) {
                     response.write(normalResponse.asJson().toUtf8());
                 } else {
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else if (request.getMethod() == "DELETE")
             {
                 int status = m_adapter->instanceAudioOutputDelete(
                         normalResponse,
                         errorResponse);
                 response.setStatus(status);
                 if (status/100 == 2) {
                     response.write(normalResponse.asJson().toUtf8());
                 } else {
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else
             {
                 response.setStatus(405,"Invalid HTTP method");
                 errorResponse.init();
                 *errorResponse.getMessage() = "Invalid HTTP method";
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(400,"Invalid JSON request");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid JSON request";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(400,"Invalid JSON format");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid JSON format";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instanceAudioService()
void WebAPIRequestMapper::instanceAudioService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 369 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGAudioDevices::asJson(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceAudioGet(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         SWGSDRangel::SWGAudioDevices normalResponse;
         int status = m_adapter->instanceAudioGet(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instanceChannelsService()
void WebAPIRequestMapper::instanceChannelsService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 277 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGInstanceChannelsResponse::asJson(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), qtwebapp::HttpRequest::getParameter(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceChannels(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGInstanceChannelsResponse normalResponse;
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         QByteArray dirStr = request.getParameter("direction");
         int direction = 0;
         if (dirStr.length() != 0)
         {
             bool ok;
             int tmp = dirStr.toInt(&ok);
             if (ok) {
                 direction = tmp;
             }
         }
         int status = m_adapter->instanceChannels(direction, normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instanceConfigService()
void WebAPIRequestMapper::instanceConfigService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 218 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGInstanceConfigResponse::asJson(), qtwebapp::HttpRequest::getMethod(), WebAPIAdapterInterface::instanceConfigGet(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         SWGSDRangel::SWGInstanceConfigResponse normalResponse;
         int status = m_adapter->instanceConfigGet(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
 }
instanceDeviceSetService()
void WebAPIRequestMapper::instanceDeviceSetService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 1061 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGSuccessResponse::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), qtwebapp::HttpRequest::getParameter(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceDeviceSetDelete(), WebAPIAdapterInterface::instanceDeviceSetPost(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "POST")
     {
         SWGSDRangel::SWGSuccessResponse normalResponse;
         QByteArray dirStr = request.getParameter("direction");
         int direction = 0;
         if (dirStr.length() != 0)
         {
             bool ok;
             int tmp = dirStr.toInt(&ok);
             if (ok) {
                 direction = tmp;
             }
         }
         int status = m_adapter->instanceDeviceSetPost(direction, normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else if (request.getMethod() == "DELETE")
     {
         SWGSDRangel::SWGSuccessResponse normalResponse;
         int status = m_adapter->instanceDeviceSetDelete(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instanceDeviceSetsService()
void WebAPIRequestMapper::instanceDeviceSetsService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 1034 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGDeviceSetList::asJson(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceDeviceSetsGet(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         SWGSDRangel::SWGDeviceSetList normalResponse;
         int status = m_adapter->instanceDeviceSetsGet(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instanceDevicesService()
void WebAPIRequestMapper::instanceDevicesService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 238 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGInstanceDevicesResponse::asJson(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), qtwebapp::HttpRequest::getParameter(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceDevices(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGInstanceDevicesResponse normalResponse;
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         QByteArray dirStr = request.getParameter("direction");
         int direction = 0;
         if (dirStr.length() != 0)
         {
             bool ok;
             int tmp = dirStr.toInt(&ok);
             if (ok) {
                 direction = tmp;
             }
         }
         int status = m_adapter->instanceDevices(direction, normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instanceDVSerialService()
void WebAPIRequestMapper::instanceDVSerialService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
instanceLocationService()
void WebAPIRequestMapper::instanceLocationService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 591 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGLocationInformation::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGLocationInformation::fromJson(), qtwebapp::HttpRequest::getBody(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceLocationGet(), WebAPIAdapterInterface::instanceLocationPut(), m_adapter, parseJsonBody(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         SWGSDRangel::SWGLocationInformation normalResponse;
         int status = m_adapter->instanceLocationGet(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else if (request.getMethod() == "PUT")
     {
         SWGSDRangel::SWGLocationInformation normalResponse;
         QString jsonStr = request.getBody();
         QJsonObject jsonObject;
         if (parseJsonBody(jsonStr, jsonObject, response))
         {
             normalResponse.fromJson(jsonStr);
             int status = m_adapter->instanceLocationPut(normalResponse, errorResponse);
             response.setStatus(status);
             if (status/100 == 2) {
                 response.write(normalResponse.asJson().toUtf8());
             } else {
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(400,"Invalid JSON format");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid JSON format";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instanceLoggingService()
void WebAPIRequestMapper::instanceLoggingService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 316 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGLoggingInfo::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGLoggingInfo::fromJson(), qtwebapp::HttpRequest::getBody(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceLoggingGet(), WebAPIAdapterInterface::instanceLoggingPut(), m_adapter, parseJsonBody(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGLoggingInfo query;
     SWGSDRangel::SWGLoggingInfo normalResponse;
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         int status = m_adapter->instanceLoggingGet(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else if (request.getMethod() == "PUT")
     {
         QString jsonStr = request.getBody();
         QJsonObject jsonObject;
         if (parseJsonBody(jsonStr, jsonObject, response))
         {
             query.fromJson(jsonStr);
             int status = m_adapter->instanceLoggingPut(query, normalResponse, errorResponse);
             response.setStatus(status);
             if (status/100 == 2) {
                 response.write(normalResponse.asJson().toUtf8());
             } else {
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(400,"Invalid JSON format");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid JSON format";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instancePresetFileService()
void WebAPIRequestMapper::instancePresetFileService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 943 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGPresetIdentifier::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGPresetImport::fromJson(), SWGSDRangel::SWGPresetExport::fromJson(), qtwebapp::HttpRequest::getBody(), SWGSDRangel::SWGPresetImport::getFilePath(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instancePresetFilePost(), WebAPIAdapterInterface::instancePresetFilePut(), m_adapter, parseJsonBody(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), validatePresetExport(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "PUT")
     {
         SWGSDRangel::SWGPresetImport query;
         SWGSDRangel::SWGPresetIdentifier normalResponse;
         QString jsonStr = request.getBody();
         QJsonObject jsonObject;
         if (parseJsonBody(jsonStr, jsonObject, response))
         {
             query.fromJson(jsonStr);
             if (query.getFilePath())
             {
                 int status = m_adapter->instancePresetFilePut(query, normalResponse, errorResponse);
                 response.setStatus(status);
                 if (status/100 == 2) {
                     response.write(normalResponse.asJson().toUtf8());
                 } else {
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else
             {
                 response.setStatus(400,"Invalid JSON request");
                 errorResponse.init();
                 *errorResponse.getMessage() = "Invalid JSON request";
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(400,"Invalid JSON format");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid JSON format";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else if (request.getMethod() == "POST")
     {
         SWGSDRangel::SWGPresetExport query;
         SWGSDRangel::SWGPresetIdentifier normalResponse;
         QString jsonStr = request.getBody();
         QJsonObject jsonObject;
         if (parseJsonBody(jsonStr, jsonObject, response))
         {
             query.fromJson(jsonStr);
             if (validatePresetExport(query))
             {
                 int status = m_adapter->instancePresetFilePost(query, normalResponse, errorResponse);
                 response.setStatus(status);
                 if (status/100 == 2) {
                     response.write(normalResponse.asJson().toUtf8());
                 } else {
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else
             {
                 response.setStatus(400,"Invalid JSON request");
                 errorResponse.init();
                 *errorResponse.getMessage() = "Invalid JSON request";
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(400,"Invalid JSON format");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid JSON format";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instancePresetService()
void WebAPIRequestMapper::instancePresetService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 777 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGPresetIdentifier::asJson(), SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGPresetTransfer::fromJson(), SWGSDRangel::SWGPresetIdentifier::fromJson(), qtwebapp::HttpRequest::getBody(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instancePresetDelete(), WebAPIAdapterInterface::instancePresetPatch(), WebAPIAdapterInterface::instancePresetPost(), WebAPIAdapterInterface::instancePresetPut(), m_adapter, parseJsonBody(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), validatePresetIdentifer(), validatePresetTransfer(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "PATCH")
     {
         SWGSDRangel::SWGPresetTransfer query;
         SWGSDRangel::SWGPresetIdentifier normalResponse;
         QString jsonStr = request.getBody();
         QJsonObject jsonObject;
         if (parseJsonBody(jsonStr, jsonObject, response))
         {
             query.fromJson(jsonStr);
             if (validatePresetTransfer(query))
             {
                 int status = m_adapter->instancePresetPatch(query, normalResponse, errorResponse);
                 response.setStatus(status);
                 if (status/100 == 2) {
                     response.write(normalResponse.asJson().toUtf8());
                 } else {
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else
             {
                 response.setStatus(400,"Invalid JSON request");
                 errorResponse.init();
                 *errorResponse.getMessage() = "Invalid JSON request";
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(400,"Invalid JSON format");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid JSON format";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else if (request.getMethod() == "PUT")
     {
         SWGSDRangel::SWGPresetTransfer query;
         SWGSDRangel::SWGPresetIdentifier normalResponse;
         QString jsonStr = request.getBody();
         QJsonObject jsonObject;
         if (parseJsonBody(jsonStr, jsonObject, response))
         {
             query.fromJson(jsonStr);
             if (validatePresetTransfer(query))
             {
                 int status = m_adapter->instancePresetPut(query, normalResponse, errorResponse);
                 response.setStatus(status);
                 if (status/100 == 2) {
                     response.write(normalResponse.asJson().toUtf8());
                 } else {
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else
             {
                 response.setStatus(400,"Invalid JSON request");
                 errorResponse.init();
                 *errorResponse.getMessage() = "Invalid JSON request";
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(400,"Invalid JSON format");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid JSON format";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else if (request.getMethod() == "POST")
     {
         SWGSDRangel::SWGPresetTransfer query;
         SWGSDRangel::SWGPresetIdentifier normalResponse;
         QString jsonStr = request.getBody();
         QJsonObject jsonObject;
         if (parseJsonBody(jsonStr, jsonObject, response))
         {
             query.fromJson(jsonStr);
             if (validatePresetTransfer(query))
             {
                 int status = m_adapter->instancePresetPost(query, normalResponse, errorResponse);
                 response.setStatus(status);
                 if (status/100 == 2) {
                     response.write(normalResponse.asJson().toUtf8());
                 } else {
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else
             {
                 response.setStatus(400,"Invalid JSON request");
                 errorResponse.init();
                 *errorResponse.getMessage() = "Invalid JSON request";
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(400,"Invalid JSON format");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid JSON format";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else if (request.getMethod() == "DELETE")
     {
         SWGSDRangel::SWGPresetIdentifier normalResponse;
         QString jsonStr = request.getBody();
         QJsonObject jsonObject;
         if (parseJsonBody(jsonStr, jsonObject, response))
         {
             normalResponse.fromJson(jsonStr);
             if (validatePresetIdentifer(normalResponse))
             {
                 int status = m_adapter->instancePresetDelete(normalResponse, errorResponse);
                 response.setStatus(status);
                 if (status/100 == 2) {
                     response.write(normalResponse.asJson().toUtf8());
                 } else {
                     response.write(errorResponse.asJson().toUtf8());
                 }
             }
             else
             {
                 response.setStatus(400,"Invalid JSON request");
                 errorResponse.init();
                 *errorResponse.getMessage() = "Invalid JSON request";
                 response.write(errorResponse.asJson().toUtf8());
             }
         }
         else
         {
             response.setStatus(400,"Invalid JSON format");
             errorResponse.init();
             *errorResponse.getMessage() = "Invalid JSON format";
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
instancePresetsService()
void WebAPIRequestMapper::instancePresetsService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 757 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGPresets::asJson(), qtwebapp::HttpRequest::getMethod(), WebAPIAdapterInterface::instancePresetsGet(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         SWGSDRangel::SWGPresets normalResponse;
         int status = m_adapter->instancePresetsGet(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
 }
instanceSummaryService()
void WebAPIRequestMapper::instanceSummaryService (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) private
Definition at line 177 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGSuccessResponse::asJson(), SWGSDRangel::SWGInstanceSummaryResponse::asJson(), SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), SWGSDRangel::SWGErrorResponse::init(), WebAPIAdapterInterface::instanceDelete(), WebAPIAdapterInterface::instanceSummary(), m_adapter, qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by service().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     response.setHeader("Content-Type", "application/json");
     response.setHeader("Access-Control-Allow-Origin", "*");
     if (request.getMethod() == "GET")
     {
         SWGSDRangel::SWGInstanceSummaryResponse normalResponse;
         int status = m_adapter->instanceSummary(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else if (request.getMethod() == "DELETE")
     {
         SWGSDRangel::SWGSuccessResponse normalResponse;
         int status = m_adapter->instanceDelete(normalResponse, errorResponse);
         response.setStatus(status);
         if (status/100 == 2) {
             response.write(normalResponse.asJson().toUtf8());
         } else {
             response.write(errorResponse.asJson().toUtf8());
         }
     }
     else
     {
         response.setStatus(405,"Invalid HTTP method");
         errorResponse.init();
         *errorResponse.getMessage() = "Invalid HTTP method";
         response.write(errorResponse.asJson().toUtf8());
     }
 }
parseJsonBody()
bool WebAPIRequestMapper::parseJsonBody (QString & jsonStr, QJsonObject & jsonObject, qtwebapp::HttpResponse & response) private
Definition at line 1729 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), SWGSDRangel::SWGErrorResponse::getMessage(), SWGSDRangel::SWGErrorResponse::init(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
Referenced by devicesetChannelService(), devicesetChannelSettingsService(), devicesetDeviceService(), devicesetDeviceSettingsService(), instanceAMBEDevicesService(), instanceAudioInputParametersService(), instanceAudioOutputParametersService(), instanceLocationService(), instanceLoggingService(), instancePresetFileService(), and instancePresetService().
 {
     SWGSDRangel::SWGErrorResponse errorResponse;
     try
     {
         QByteArray jsonBytes(jsonStr.toStdString().c_str());
         QJsonParseError error;
         QJsonDocument doc = QJsonDocument::fromJson(jsonBytes, &error);
         if (error.error == QJsonParseError::NoError)
         {
             jsonObject = doc.object();
         }
         else
         {
             QString errorMsg = QString("Input JSON error: ") + error.errorString() + QString(" at offset ") + QString::number(error.offset);
             errorResponse.init();
             *errorResponse.getMessage() = errorMsg;
             response.setStatus(400, errorMsg.toUtf8());
             response.write(errorResponse.asJson().toUtf8());
         }
         return (error.error == QJsonParseError::NoError);
     }
     catch (const std::exception& ex)
     {
         QString errorMsg = QString("Error parsing request: ") + ex.what();
         errorResponse.init();
         *errorResponse.getMessage() = errorMsg;
         response.setStatus(500, errorMsg.toUtf8());
         response.write(errorResponse.asJson().toUtf8());
         return false;
     }
 }
resetAudioInputDevice()
void WebAPIRequestMapper::resetAudioInputDevice (SWGSDRangel::SWGAudioInputDevice & audioInputDevice) private
Definition at line 2893 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGAudioInputDevice::cleanup(), and SWGSDRangel::SWGAudioInputDevice::setName().
Referenced by instanceAudioInputParametersService().
 {
     audioInputDevice.cleanup();
     audioInputDevice.setName(0);
 }
resetAudioOutputDevice()
void WebAPIRequestMapper::resetAudioOutputDevice (SWGSDRangel::SWGAudioOutputDevice & audioOutputDevice) private
Definition at line 2899 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGAudioOutputDevice::cleanup(), SWGSDRangel::SWGAudioOutputDevice::setName(), and SWGSDRangel::SWGAudioOutputDevice::setUdpAddress().
Referenced by instanceAudioOutputParametersService().
 {
     audioOutputDevice.cleanup();
     audioOutputDevice.setName(0);
     audioOutputDevice.setUdpAddress(0);
 }
resetChannelReport()
void WebAPIRequestMapper::resetChannelReport (SWGSDRangel::SWGChannelReport & deviceSettings) private
Definition at line 2873 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGChannelReport::cleanup(), SWGSDRangel::SWGChannelReport::setAmDemodReport(), SWGSDRangel::SWGChannelReport::setAmModReport(), SWGSDRangel::SWGChannelReport::setAtvModReport(), SWGSDRangel::SWGChannelReport::setBfmDemodReport(), SWGSDRangel::SWGChannelReport::setChannelType(), SWGSDRangel::SWGChannelReport::setDsdDemodReport(), SWGSDRangel::SWGChannelReport::setNfmDemodReport(), SWGSDRangel::SWGChannelReport::setNfmModReport(), SWGSDRangel::SWGChannelReport::setRemoteSourceReport(), SWGSDRangel::SWGChannelReport::setSsbDemodReport(), SWGSDRangel::SWGChannelReport::setSsbModReport(), SWGSDRangel::SWGChannelReport::setUdpSinkReport(), SWGSDRangel::SWGChannelReport::setUdpSourceReport(), SWGSDRangel::SWGChannelReport::setWfmDemodReport(), and SWGSDRangel::SWGChannelReport::setWfmModReport().
Referenced by devicesetChannelReportService().
 {
     channelReport.cleanup();
     channelReport.setChannelType(0);
     channelReport.setAmDemodReport(0);
     channelReport.setAmModReport(0);
     channelReport.setAtvModReport(0);
     channelReport.setBfmDemodReport(0);
     channelReport.setDsdDemodReport(0);
     channelReport.setNfmDemodReport(0);
     channelReport.setNfmModReport(0);
     channelReport.setRemoteSourceReport(0);
     channelReport.setSsbDemodReport(0);
     channelReport.setSsbModReport(0);
     channelReport.setUdpSourceReport(0);
     channelReport.setUdpSinkReport(0);
     channelReport.setWfmDemodReport(0);
     channelReport.setWfmModReport(0);
 }
resetChannelSettings()
void WebAPIRequestMapper::resetChannelSettings (SWGSDRangel::SWGChannelSettings & deviceSettings) private
Definition at line 2852 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGChannelSettings::cleanup(), SWGSDRangel::SWGChannelSettings::setAmDemodSettings(), SWGSDRangel::SWGChannelSettings::setAmModSettings(), SWGSDRangel::SWGChannelSettings::setAtvModSettings(), SWGSDRangel::SWGChannelSettings::setBfmDemodSettings(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDsdDemodSettings(), SWGSDRangel::SWGChannelSettings::setNfmDemodSettings(), SWGSDRangel::SWGChannelSettings::setNfmModSettings(), SWGSDRangel::SWGChannelSettings::setRemoteSinkSettings(), SWGSDRangel::SWGChannelSettings::setRemoteSourceSettings(), SWGSDRangel::SWGChannelSettings::setSsbDemodSettings(), SWGSDRangel::SWGChannelSettings::setSsbModSettings(), SWGSDRangel::SWGChannelSettings::setUdpSinkSettings(), SWGSDRangel::SWGChannelSettings::setUdpSourceSettings(), SWGSDRangel::SWGChannelSettings::setWfmDemodSettings(), and SWGSDRangel::SWGChannelSettings::setWfmModSettings().
Referenced by devicesetChannelService(), and devicesetChannelSettingsService().
 {
     channelSettings.cleanup();
     channelSettings.setChannelType(0);
     channelSettings.setAmDemodSettings(0);
     channelSettings.setAmModSettings(0);
     channelSettings.setAtvModSettings(0);
     channelSettings.setBfmDemodSettings(0);
     channelSettings.setDsdDemodSettings(0);
     channelSettings.setNfmDemodSettings(0);
     channelSettings.setNfmModSettings(0);
     channelSettings.setRemoteSinkSettings(0);
     channelSettings.setRemoteSourceSettings(0);
     channelSettings.setSsbDemodSettings(0);
     channelSettings.setSsbModSettings(0);
     channelSettings.setUdpSourceSettings(0);
     channelSettings.setUdpSinkSettings(0);
     channelSettings.setWfmDemodSettings(0);
     channelSettings.setWfmModSettings(0);
 }
resetDeviceReport()
void WebAPIRequestMapper::resetDeviceReport (SWGSDRangel::SWGDeviceReport & deviceReport) private
Definition at line 2834 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGDeviceReport::cleanup(), SWGSDRangel::SWGDeviceReport::setAirspyHfReport(), SWGSDRangel::SWGDeviceReport::setAirspyReport(), SWGSDRangel::SWGDeviceReport::setDeviceHwType(), SWGSDRangel::SWGDeviceReport::setFileInputReport(), SWGSDRangel::SWGDeviceReport::setLimeSdrInputReport(), SWGSDRangel::SWGDeviceReport::setLimeSdrOutputReport(), SWGSDRangel::SWGDeviceReport::setPerseusReport(), SWGSDRangel::SWGDeviceReport::setPlutoSdrInputReport(), SWGSDRangel::SWGDeviceReport::setPlutoSdrOutputReport(), SWGSDRangel::SWGDeviceReport::setRemoteInputReport(), SWGSDRangel::SWGDeviceReport::setRemoteOutputReport(), SWGSDRangel::SWGDeviceReport::setRtlSdrReport(), and SWGSDRangel::SWGDeviceReport::setSdrPlayReport().
Referenced by devicesetDeviceReportService().
 {
     deviceReport.cleanup();
     deviceReport.setDeviceHwType(0);
     deviceReport.setAirspyHfReport(0);
     deviceReport.setAirspyReport(0);
     deviceReport.setFileInputReport(0);
     deviceReport.setLimeSdrInputReport(0);
     deviceReport.setLimeSdrOutputReport(0);
     deviceReport.setPerseusReport(0);
     deviceReport.setPlutoSdrInputReport(0);
     deviceReport.setPlutoSdrOutputReport(0);
     deviceReport.setRtlSdrReport(0);
     deviceReport.setRemoteOutputReport(0);
     deviceReport.setRemoteInputReport(0);
     deviceReport.setSdrPlayReport(0);
 }
resetDeviceSettings()
void WebAPIRequestMapper::resetDeviceSettings (SWGSDRangel::SWGDeviceSettings & deviceSettings) private
Definition at line 2809 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGDeviceSettings::cleanup(), SWGSDRangel::SWGDeviceSettings::setAirspyHfSettings(), SWGSDRangel::SWGDeviceSettings::setAirspySettings(), SWGSDRangel::SWGDeviceSettings::setBladeRf1InputSettings(), SWGSDRangel::SWGDeviceSettings::setBladeRf1OutputSettings(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setFcdProPlusSettings(), SWGSDRangel::SWGDeviceSettings::setFcdProSettings(), SWGSDRangel::SWGDeviceSettings::setFileInputSettings(), SWGSDRangel::SWGDeviceSettings::setHackRfInputSettings(), SWGSDRangel::SWGDeviceSettings::setHackRfOutputSettings(), SWGSDRangel::SWGDeviceSettings::setLimeSdrInputSettings(), SWGSDRangel::SWGDeviceSettings::setLimeSdrOutputSettings(), SWGSDRangel::SWGDeviceSettings::setPerseusSettings(), SWGSDRangel::SWGDeviceSettings::setPlutoSdrInputSettings(), SWGSDRangel::SWGDeviceSettings::setPlutoSdrOutputSettings(), SWGSDRangel::SWGDeviceSettings::setRemoteInputSettings(), SWGSDRangel::SWGDeviceSettings::setRemoteOutputSettings(), SWGSDRangel::SWGDeviceSettings::setRtlSdrSettings(), SWGSDRangel::SWGDeviceSettings::setSdrPlaySettings(), and SWGSDRangel::SWGDeviceSettings::setTestSourceSettings().
Referenced by devicesetDeviceSettingsService().
 {
     deviceSettings.cleanup();
     deviceSettings.setDeviceHwType(0);
     deviceSettings.setAirspySettings(0);
     deviceSettings.setAirspyHfSettings(0);
     deviceSettings.setBladeRf1InputSettings(0);
     deviceSettings.setBladeRf1OutputSettings(0);
     deviceSettings.setFcdProPlusSettings(0);
     deviceSettings.setFcdProSettings(0);
     deviceSettings.setFileInputSettings(0);
     deviceSettings.setHackRfInputSettings(0);
     deviceSettings.setHackRfOutputSettings(0);
     deviceSettings.setLimeSdrInputSettings(0);
     deviceSettings.setLimeSdrOutputSettings(0);
     deviceSettings.setPerseusSettings(0);
     deviceSettings.setPlutoSdrInputSettings(0);
     deviceSettings.setPlutoSdrOutputSettings(0);
     deviceSettings.setRtlSdrSettings(0);
     deviceSettings.setRemoteOutputSettings(0);
     deviceSettings.setRemoteInputSettings(0);
     deviceSettings.setSdrPlaySettings(0);
     deviceSettings.setTestSourceSettings(0);
 }
service()
void WebAPIRequestMapper::service (qtwebapp::HttpRequest & request, qtwebapp::HttpResponse & response) virtual
Generate a response for an incoming HTTP request.
Parameters
request The received HTTP request
response Must be used to return the response
Warning
This method must be thread safe
Reimplemented from qtwebapp::HttpRequestHandler.
Definition at line 70 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGErrorResponse::asJson(), devicesetChannelIndexService(), WebAPIAdapterInterface::devicesetChannelIndexURLRe, devicesetChannelReportService(), WebAPIAdapterInterface::devicesetChannelReportURLRe, devicesetChannelService(), devicesetChannelSettingsService(), WebAPIAdapterInterface::devicesetChannelSettingsURLRe, devicesetChannelsReportService(), WebAPIAdapterInterface::devicesetChannelsReportURLRe, WebAPIAdapterInterface::devicesetChannelURLRe, devicesetDeviceReportService(), WebAPIAdapterInterface::devicesetDeviceReportURLRe, devicesetDeviceRunService(), WebAPIAdapterInterface::devicesetDeviceRunURLRe, devicesetDeviceService(), devicesetDeviceSettingsService(), WebAPIAdapterInterface::devicesetDeviceSettingsURLRe, WebAPIAdapterInterface::devicesetDeviceURLRe, devicesetFocusService(), WebAPIAdapterInterface::devicesetFocusURLRe, devicesetService(), WebAPIAdapterInterface::devicesetURLRe, SWGSDRangel::SWGErrorResponse::getMessage(), qtwebapp::HttpRequest::getMethod(), qtwebapp::HttpRequest::getPath(), SWGSDRangel::SWGErrorResponse::init(), instanceAMBEDevicesService(), WebAPIAdapterInterface::instanceAMBEDevicesURL, instanceAMBESerialService(), WebAPIAdapterInterface::instanceAMBESerialURL, instanceAudioInputCleanupService(), WebAPIAdapterInterface::instanceAudioInputCleanupURL, instanceAudioInputParametersService(), WebAPIAdapterInterface::instanceAudioInputParametersURL, instanceAudioOutputCleanupService(), WebAPIAdapterInterface::instanceAudioOutputCleanupURL, instanceAudioOutputParametersService(), WebAPIAdapterInterface::instanceAudioOutputParametersURL, instanceAudioService(), WebAPIAdapterInterface::instanceAudioURL, instanceChannelsService(), WebAPIAdapterInterface::instanceChannelsURL, instanceConfigService(), WebAPIAdapterInterface::instanceConfigURL, instanceDeviceSetService(), instanceDeviceSetsService(), WebAPIAdapterInterface::instanceDeviceSetsURL, WebAPIAdapterInterface::instanceDeviceSetURL, instanceDevicesService(), WebAPIAdapterInterface::instanceDevicesURL, instanceLocationService(), WebAPIAdapterInterface::instanceLocationURL, instanceLoggingService(), WebAPIAdapterInterface::instanceLoggingURL, instancePresetFileService(), WebAPIAdapterInterface::instancePresetFileURL, instancePresetService(), instancePresetsService(), WebAPIAdapterInterface::instancePresetsURL, WebAPIAdapterInterface::instancePresetURL, instanceSummaryService(), WebAPIAdapterInterface::instanceSummaryURL, m_adapter, m_staticFileController, qtwebapp::StaticFileController::service(), qtwebapp::HttpResponse::setHeader(), qtwebapp::HttpResponse::setStatus(), and qtwebapp::HttpResponse::write().
 {
     if (m_adapter == 0) // format service unavailable if adapter is null
     {
         SWGSDRangel::SWGErrorResponse errorResponse;
         response.setHeader("Content-Type", "application/json");
         response.setHeader("Access-Control-Allow-Origin", "*");
         response.setStatus(500,"Service not available");
         errorResponse.init();
         *errorResponse.getMessage() = "Service not available";
         response.write(errorResponse.asJson().toUtf8());
     }
     else // normal processing
     {
         QByteArray path=request.getPath();
         // Handle pre-flight requests
         if (request.getMethod() == "OPTIONS")
         {
             qDebug("WebAPIRequestMapper::service: method OPTIONS: assume pre-flight");
             response.setHeader("Access-Control-Allow-Origin", "*");
             response.setHeader("Access-Control-Allow-Headers", "*");
             response.setHeader("Access-Control-Allow-Methods", "*");
             response.setStatus(200, "OK");
             return;
         }
         if (path == WebAPIAdapterInterface::instanceSummaryURL) {
             instanceSummaryService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceConfigURL) {
             instanceConfigService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceDevicesURL) {
             instanceDevicesService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceChannelsURL) {
             instanceChannelsService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceLoggingURL) {
             instanceLoggingService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceAudioURL) {
             instanceAudioService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceAudioInputParametersURL) {
             instanceAudioInputParametersService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceAudioOutputParametersURL) {
             instanceAudioOutputParametersService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceAudioInputCleanupURL) {
             instanceAudioInputCleanupService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceAudioOutputCleanupURL) {
             instanceAudioOutputCleanupService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceLocationURL) {
             instanceLocationService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceAMBESerialURL) {
             instanceAMBESerialService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceAMBEDevicesURL) {
             instanceAMBEDevicesService(request, response);
         } else if (path == WebAPIAdapterInterface::instancePresetsURL) {
             instancePresetsService(request, response);
         } else if (path == WebAPIAdapterInterface::instancePresetURL) {
             instancePresetService(request, response);
         } else if (path == WebAPIAdapterInterface::instancePresetFileURL) {
             instancePresetFileService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceDeviceSetsURL) {
             instanceDeviceSetsService(request, response);
         } else if (path == WebAPIAdapterInterface::instanceDeviceSetURL) {
             instanceDeviceSetService(request, response);
         }
         else
         {
             std::smatch desc_match;
             std::string pathStr(path.constData(), path.length());
             if (std::regex_match(pathStr, desc_match, WebAPIAdapterInterface::devicesetURLRe)) {
                 devicesetService(std::string(desc_match[1]), request, response);
             } else if (std::regex_match(pathStr, desc_match, WebAPIAdapterInterface::devicesetDeviceURLRe)) {
                 devicesetDeviceService(std::string(desc_match[1]), request, response);
             } else if (std::regex_match(pathStr, desc_match, WebAPIAdapterInterface::devicesetFocusURLRe)) {
                 devicesetFocusService(std::string(desc_match[1]), request, response);
             } else if (std::regex_match(pathStr, desc_match, WebAPIAdapterInterface::devicesetDeviceSettingsURLRe)) {
                 devicesetDeviceSettingsService(std::string(desc_match[1]), request, response);
             } else if (std::regex_match(pathStr, desc_match, WebAPIAdapterInterface::devicesetDeviceRunURLRe)) {
                 devicesetDeviceRunService(std::string(desc_match[1]), request, response);
             } else if (std::regex_match(pathStr, desc_match, WebAPIAdapterInterface::devicesetDeviceReportURLRe)) {
                 devicesetDeviceReportService(std::string(desc_match[1]), request, response);
             } else if (std::regex_match(pathStr, desc_match, WebAPIAdapterInterface::devicesetChannelsReportURLRe)) {
                 devicesetChannelsReportService(std::string(desc_match[1]), request, response);
             } else if (std::regex_match(pathStr, desc_match, WebAPIAdapterInterface::devicesetChannelURLRe)) {
                 devicesetChannelService(std::string(desc_match[1]), request, response);
             } else if (std::regex_match(pathStr, desc_match, WebAPIAdapterInterface::devicesetChannelIndexURLRe)) {
                 devicesetChannelIndexService(std::string(desc_match[1]), std::string(desc_match[2]), request, response);
             } else if (std::regex_match(pathStr, desc_match, WebAPIAdapterInterface::devicesetChannelSettingsURLRe)) {
                 devicesetChannelSettingsService(std::string(desc_match[1]), std::string(desc_match[2]), request, response);
             } else if (std::regex_match(pathStr, desc_match, WebAPIAdapterInterface::devicesetChannelReportURLRe)) {
                 devicesetChannelReportService(std::string(desc_match[1]), std::string(desc_match[2]), request, response);
             }
             else // serve static documentation pages
             {
                 m_staticFileController->service(request, response);
             }
 //            QDirIterator it(":", QDirIterator::Subdirectories);
 //            while (it.hasNext()) {
 //                qDebug() << "WebAPIRequestMapper::service: " << it.next();
 //            }
         }
     }
 }
setAdapter()
void WebAPIRequestMapper::setAdapter (WebAPIAdapterInterface * adapter) inline
Definition at line 45 of file webapirequestmapper.h.
Referenced by MainCore::MainCore(), and MainWindow::MainWindow().
 { m_adapter = adapter; }
validateAMBEDevices()
bool WebAPIRequestMapper::validateAMBEDevices (SWGSDRangel::SWGAMBEDevices & ambeDevices, QJsonObject & jsonObject) private
Definition at line 2730 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGAMBEDevices::getAmbeDevices(), i, SWGSDRangel::SWGAMBEDevices::init(), and SWGSDRangel::SWGAMBEDevices::setNbDevices().
Referenced by instanceAMBEDevicesService().
 {
     if (jsonObject.contains("nbDevices"))
     {
         int nbDevices = jsonObject["nbDevices"].toInt();
         if (jsonObject.contains("ambeDevices"))
         {
             QJsonArray ambeDevicesJson = jsonObject["ambeDevices"].toArray();
             if (nbDevices != ambeDevicesJson.size()) {
                 return false;
             }
             ambeDevices.init();
             ambeDevices.setNbDevices(nbDevices);
             QList<SWGSDRangel::SWGAMBEDevice *> *ambeList = ambeDevices.getAmbeDevices();
             for (int i = 0; i < nbDevices; i++)
             {
                 QJsonObject ambeDeviceJson = ambeDevicesJson.at(i).toObject();
                 if (ambeDeviceJson.contains("deviceRef") && ambeDeviceJson.contains("delete"))
                 {
                     ambeList->push_back(new SWGSDRangel::SWGAMBEDevice());
                     ambeList->back()->init();
                     ambeList->back()->setDeviceRef(new QString(ambeDeviceJson["deviceRef"].toString()));
                     ambeList->back()->setDelete(ambeDeviceJson["delete"].toInt());
                 }
                 else
                 {
                     return false;
                 }
             }
             return true;
         }
     }
     return false;
 }
validateAudioInputDevice()
bool WebAPIRequestMapper::validateAudioInputDevice (SWGSDRangel::SWGAudioInputDevice & audioInputDevice, QJsonObject & jsonObject, QStringList & audioInputDeviceKeys) private
Definition at line 2654 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGAudioInputDevice::setIndex(), SWGSDRangel::SWGAudioInputDevice::setSampleRate(), and SWGSDRangel::SWGAudioInputDevice::setVolume().
Referenced by instanceAudioInputParametersService().
 {
     if (jsonObject.contains("index")) {
         audioInputDevice.setIndex(jsonObject["index"].toInt());
     } else {
         audioInputDevice.setIndex(-1); // assume systam default
     }
     if (jsonObject.contains("sampleRate"))
     {
         audioInputDevice.setSampleRate(jsonObject["sampleRate"].toInt());
         audioInputDeviceKeys.append("sampleRate");
     }
     if (jsonObject.contains("volume"))
     {
         audioInputDevice.setVolume(jsonObject["volume"].toDouble());
         audioInputDeviceKeys.append("volume");
     }
     return true;
 }
validateAudioOutputDevice()
bool WebAPIRequestMapper::validateAudioOutputDevice (SWGSDRangel::SWGAudioOutputDevice & audioOutputDevice, QJsonObject & jsonObject, QStringList & audioOutputDeviceKeys) private
Definition at line 2677 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGAudioOutputDevice::setCopyToUdp(), SWGSDRangel::SWGAudioOutputDevice::setIndex(), SWGSDRangel::SWGAudioOutputDevice::setSampleRate(), SWGSDRangel::SWGAudioOutputDevice::setUdpAddress(), SWGSDRangel::SWGAudioOutputDevice::setUdpChannelCodec(), SWGSDRangel::SWGAudioOutputDevice::setUdpChannelMode(), SWGSDRangel::SWGAudioOutputDevice::setUdpDecimationFactor(), SWGSDRangel::SWGAudioOutputDevice::setUdpPort(), and SWGSDRangel::SWGAudioOutputDevice::setUdpUsesRtp().
Referenced by instanceAudioOutputParametersService().
 {
     if (jsonObject.contains("index")) {
         audioOutputDevice.setIndex(jsonObject["index"].toInt());
     } else {
         audioOutputDevice.setIndex(-1); // assume systam default
     }
     if (jsonObject.contains("sampleRate"))
     {
         audioOutputDevice.setSampleRate(jsonObject["sampleRate"].toInt());
         audioOutputDeviceKeys.append("sampleRate");
     }
     if (jsonObject.contains("copyToUDP"))
     {
         audioOutputDevice.setCopyToUdp(jsonObject["copyToUDP"].toInt() == 0 ? 0 : 1);
         audioOutputDeviceKeys.append("copyToUDP");
     }
     if (jsonObject.contains("udpUsesRTP"))
     {
         audioOutputDevice.setUdpUsesRtp(jsonObject["udpUsesRTP"].toInt() == 0 ? 0 : 1);
         audioOutputDeviceKeys.append("udpUsesRTP");
     }
     if (jsonObject.contains("udpChannelMode"))
     {
         audioOutputDevice.setUdpChannelMode(jsonObject["udpChannelMode"].toInt());
         audioOutputDeviceKeys.append("udpChannelMode");
     }
     if (jsonObject.contains("udpChannelCodec"))
     {
         audioOutputDevice.setUdpChannelCodec(jsonObject["udpChannelCodec"].toInt());
         audioOutputDeviceKeys.append("udpChannelCodec");
     }
     if (jsonObject.contains("udpDecimationFactor"))
     {
         audioOutputDevice.setUdpDecimationFactor(jsonObject["udpDecimationFactor"].toInt());
         audioOutputDeviceKeys.append("udpDecimationFactor");
     }
     if (jsonObject.contains("udpAddress"))
     {
         audioOutputDevice.setUdpAddress(new QString(jsonObject["udpAddress"].toString()));
         audioOutputDeviceKeys.append("udpAddress");
     }
     if (jsonObject.contains("udpPort"))
     {
         audioOutputDevice.setUdpPort(jsonObject["udpPort"].toInt());
         audioOutputDeviceKeys.append("udpPort");
     }
     return true;
 }
validateChannelSettings()
bool WebAPIRequestMapper::validateChannelSettings (SWGSDRangel::SWGChannelSettings & deviceSettings, QJsonObject & jsonObject, QStringList & channelSettingsKeys) private
Definition at line 2321 of file webapirequestmapper.cpp.
References appendSettingsSubKeys(), SWGSDRangel::SWGAMDemodSettings::fromJsonObject(), SWGSDRangel::SWGBFMDemodSettings::fromJsonObject(), SWGSDRangel::SWGNFMDemodSettings::fromJsonObject(), SWGSDRangel::SWGLocalSinkSettings::fromJsonObject(), SWGSDRangel::SWGDSDDemodSettings::fromJsonObject(), SWGSDRangel::SWGLocalSourceSettings::fromJsonObject(), SWGSDRangel::SWGFreeDVDemodSettings::fromJsonObject(), SWGSDRangel::SWGRemoteSinkSettings::fromJsonObject(), SWGSDRangel::SWGRemoteSourceSettings::fromJsonObject(), SWGSDRangel::SWGATVModSettings::fromJsonObject(), SWGSDRangel::SWGSSBDemodSettings::fromJsonObject(), SWGSDRangel::SWGFreqTrackerSettings::fromJsonObject(), SWGSDRangel::SWGUDPSourceSettings::fromJsonObject(), SWGSDRangel::SWGUDPSinkSettings::fromJsonObject(), SWGSDRangel::SWGWFMDemodSettings::fromJsonObject(), SWGSDRangel::SWGWFMModSettings::fromJsonObject(), SWGSDRangel::SWGNFMModSettings::fromJsonObject(), SWGSDRangel::SWGAMModSettings::fromJsonObject(), SWGSDRangel::SWGFreeDVModSettings::fromJsonObject(), SWGSDRangel::SWGSSBModSettings::fromJsonObject(), SWGSDRangel::SWGChannelSettings::getAmDemodSettings(), SWGSDRangel::SWGChannelSettings::getAmModSettings(), SWGSDRangel::SWGChannelSettings::getAtvModSettings(), SWGSDRangel::SWGChannelSettings::getBfmDemodSettings(), SWGSDRangel::SWGChannelSettings::getChannelType(), SWGSDRangel::SWGChannelSettings::getDirection(), SWGSDRangel::SWGChannelSettings::getDsdDemodSettings(), SWGSDRangel::SWGChannelSettings::getFreeDvDemodSettings(), SWGSDRangel::SWGChannelSettings::getFreeDvModSettings(), SWGSDRangel::SWGChannelSettings::getFreqTrackerSettings(), SWGSDRangel::SWGChannelSettings::getLocalSinkSettings(), SWGSDRangel::SWGChannelSettings::getLocalSourceSettings(), SWGSDRangel::SWGChannelSettings::getNfmDemodSettings(), SWGSDRangel::SWGChannelSettings::getNfmModSettings(), SWGSDRangel::SWGChannelSettings::getRemoteSinkSettings(), SWGSDRangel::SWGChannelSettings::getRemoteSourceSettings(), SWGSDRangel::SWGChannelSettings::getSsbDemodSettings(), SWGSDRangel::SWGChannelSettings::getSsbModSettings(), SWGSDRangel::SWGChannelSettings::getUdpSinkSettings(), SWGSDRangel::SWGChannelSettings::getUdpSourceSettings(), SWGSDRangel::SWGChannelSettings::getWfmDemodSettings(), SWGSDRangel::SWGChannelSettings::getWfmModSettings(), SWGSDRangel::SWGChannelSettings::setAmDemodSettings(), SWGSDRangel::SWGChannelSettings::setAmModSettings(), SWGSDRangel::SWGChannelSettings::setAtvModSettings(), SWGSDRangel::SWGChannelSettings::setBfmDemodSettings(), SWGSDRangel::SWGChannelSettings::setChannelType(), SWGSDRangel::SWGChannelSettings::setDirection(), SWGSDRangel::SWGChannelSettings::setDsdDemodSettings(), SWGSDRangel::SWGChannelSettings::setFreeDvDemodSettings(), SWGSDRangel::SWGChannelSettings::setFreeDvModSettings(), SWGSDRangel::SWGChannelSettings::setFreqTrackerSettings(), SWGSDRangel::SWGChannelSettings::setLocalSinkSettings(), SWGSDRangel::SWGChannelSettings::setLocalSourceSettings(), SWGSDRangel::SWGChannelSettings::setNfmDemodSettings(), SWGSDRangel::SWGChannelSettings::setNfmModSettings(), SWGSDRangel::SWGChannelSettings::setRemoteSinkSettings(), SWGSDRangel::SWGChannelSettings::setRemoteSourceSettings(), SWGSDRangel::SWGChannelSettings::setSsbDemodSettings(), SWGSDRangel::SWGChannelSettings::setSsbModSettings(), SWGSDRangel::SWGChannelSettings::setUdpSinkSettings(), SWGSDRangel::SWGChannelSettings::setUdpSourceSettings(), SWGSDRangel::SWGChannelSettings::setWfmDemodSettings(), and SWGSDRangel::SWGChannelSettings::setWfmModSettings().
Referenced by devicesetChannelSettingsService().
 {
     if (jsonObject.contains("direction")) {
         channelSettings.setDirection(jsonObject["direction"].toInt());
     } else {
         channelSettings.setDirection(0); // assume single Rx
     }
     if (jsonObject.contains("channelType") && jsonObject["channelType"].isString()) {
         channelSettings.setChannelType(new QString(jsonObject["channelType"].toString()));
     } else {
         return false;
     }
     QString *channelType = channelSettings.getChannelType();
     if (*channelType == "AMDemod")
     {
         if (channelSettings.getDirection() == 0)
         {
             QJsonObject amDemodSettingsJsonObject = jsonObject["AMDemodSettings"].toObject();
             channelSettingsKeys = amDemodSettingsJsonObject.keys();
             channelSettings.setAmDemodSettings(new SWGSDRangel::SWGAMDemodSettings());
             channelSettings.getAmDemodSettings()->fromJsonObject(amDemodSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "AMMod")
     {
         if (channelSettings.getDirection() == 1)
         {
             QJsonObject amModSettingsJsonObject = jsonObject["AMModSettings"].toObject();
             channelSettingsKeys = amModSettingsJsonObject.keys();
             if (channelSettingsKeys.contains("cwKeyer"))
             {
                 QJsonObject cwKeyerSettingsJsonObject;
                 appendSettingsSubKeys(amModSettingsJsonObject, cwKeyerSettingsJsonObject, "cwKeyer", channelSettingsKeys);
             }
             channelSettings.setAmModSettings(new SWGSDRangel::SWGAMModSettings());
             channelSettings.getAmModSettings()->fromJsonObject(amModSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "ATVMod")
     {
         if (channelSettings.getDirection() == 1)
         {
             QJsonObject atvModSettingsJsonObject = jsonObject["ATVModSettings"].toObject();
             channelSettingsKeys = atvModSettingsJsonObject.keys();
             channelSettings.setAtvModSettings(new SWGSDRangel::SWGATVModSettings());
             channelSettings.getAtvModSettings()->fromJsonObject(atvModSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "BFMDemod")
     {
         if (channelSettings.getDirection() == 0)
         {
             QJsonObject bfmDemodSettingsJsonObject = jsonObject["BFMDemodSettings"].toObject();
             channelSettingsKeys = bfmDemodSettingsJsonObject.keys();
             channelSettings.setBfmDemodSettings(new SWGSDRangel::SWGBFMDemodSettings());
             channelSettings.getBfmDemodSettings()->fromJsonObject(bfmDemodSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "DSDDemod")
     {
         if (channelSettings.getDirection() == 0)
         {
             QJsonObject dsdDemodSettingsJsonObject = jsonObject["DSDDemodSettings"].toObject();
             channelSettingsKeys = dsdDemodSettingsJsonObject.keys();
             channelSettings.setDsdDemodSettings(new SWGSDRangel::SWGDSDDemodSettings());
             channelSettings.getDsdDemodSettings()->fromJsonObject(dsdDemodSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "FreeDVDemod")
     {
         if (channelSettings.getDirection() == 0)
         {
             QJsonObject freeDVDemodSettingsJsonObject = jsonObject["FreeDVDemodSettings"].toObject();
             channelSettingsKeys = freeDVDemodSettingsJsonObject.keys();
             channelSettings.setFreeDvDemodSettings(new SWGSDRangel::SWGFreeDVDemodSettings());
             channelSettings.getFreeDvDemodSettings()->fromJsonObject(freeDVDemodSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "FreeDVMod")
     {
         if (channelSettings.getDirection() == 1)
         {
             QJsonObject freeDVModSettingsJsonObject = jsonObject["FreeDVModSettings"].toObject();
             channelSettingsKeys = freeDVModSettingsJsonObject.keys();
             channelSettings.setFreeDvModSettings(new SWGSDRangel::SWGFreeDVModSettings());
             channelSettings.getFreeDvModSettings()->fromJsonObject(freeDVModSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "FreqTracker")
     {
         if (channelSettings.getDirection() == 0)
         {
             QJsonObject freqTrackerSettingsJsonObject = jsonObject["FreqTrackerSettings"].toObject();
             channelSettingsKeys = freqTrackerSettingsJsonObject.keys();
             channelSettings.setFreqTrackerSettings(new SWGSDRangel::SWGFreqTrackerSettings());
             channelSettings.getFreqTrackerSettings()->fromJsonObject(freqTrackerSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "NFMDemod")
     {
         if (channelSettings.getDirection() == 0)
         {
             QJsonObject nfmDemodSettingsJsonObject = jsonObject["NFMDemodSettings"].toObject();
             channelSettingsKeys = nfmDemodSettingsJsonObject.keys();
             channelSettings.setNfmDemodSettings(new SWGSDRangel::SWGNFMDemodSettings());
             channelSettings.getNfmDemodSettings()->fromJsonObject(nfmDemodSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "NFMMod")
     {
         if (channelSettings.getDirection() == 1)
         {
             QJsonObject nfmModSettingsJsonObject = jsonObject["NFMModSettings"].toObject();
             channelSettingsKeys = nfmModSettingsJsonObject.keys();
             if (channelSettingsKeys.contains("cwKeyer"))
             {
                 QJsonObject cwKeyerSettingsJsonObject;
                 appendSettingsSubKeys(nfmModSettingsJsonObject, cwKeyerSettingsJsonObject, "cwKeyer", channelSettingsKeys);
             }
             channelSettings.setNfmModSettings(new SWGSDRangel::SWGNFMModSettings());
             channelSettings.getNfmModSettings()->fromJsonObject(nfmModSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "LocalSink")
     {
         if (channelSettings.getDirection() == 0)
         {
             QJsonObject localChannelSinkSettingsJsonObject = jsonObject["LocalSinkSettings"].toObject();
             channelSettingsKeys = localChannelSinkSettingsJsonObject.keys();
             channelSettings.setLocalSinkSettings(new SWGSDRangel::SWGLocalSinkSettings());
             channelSettings.getLocalSinkSettings()->fromJsonObject(localChannelSinkSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "LocalSource")
     {
         if (channelSettings.getDirection() == 1)
         {
             QJsonObject localChannelSourceSettingsJsonObject = jsonObject["LocalSourceSettings"].toObject();
             channelSettingsKeys = localChannelSourceSettingsJsonObject.keys();
             channelSettings.setLocalSourceSettings(new SWGSDRangel::SWGLocalSourceSettings());
             channelSettings.getLocalSourceSettings()->fromJsonObject(localChannelSourceSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "RemoteSink")
     {
         if (channelSettings.getDirection() == 0)
         {
             QJsonObject remoteChannelSinkSettingsJsonObject = jsonObject["RemoteSinkSettings"].toObject();
             channelSettingsKeys = remoteChannelSinkSettingsJsonObject.keys();
             channelSettings.setRemoteSinkSettings(new SWGSDRangel::SWGRemoteSinkSettings());
             channelSettings.getRemoteSinkSettings()->fromJsonObject(remoteChannelSinkSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "RemoteSource")
     {
         if (channelSettings.getDirection() == 1)
         {
             QJsonObject remoteChannelSourceSettingsJsonObject = jsonObject["RemoteSourceSettings"].toObject();
             channelSettingsKeys = remoteChannelSourceSettingsJsonObject.keys();
             channelSettings.setRemoteSourceSettings(new SWGSDRangel::SWGRemoteSourceSettings());
             channelSettings.getRemoteSourceSettings()->fromJsonObject(remoteChannelSourceSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "SSBDemod")
     {
         if (channelSettings.getDirection() == 0)
         {
             QJsonObject ssbDemodSettingsJsonObject = jsonObject["SSBDemodSettings"].toObject();
             channelSettingsKeys = ssbDemodSettingsJsonObject.keys();
             channelSettings.setSsbDemodSettings(new SWGSDRangel::SWGSSBDemodSettings());
             channelSettings.getSsbDemodSettings()->fromJsonObject(ssbDemodSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "SSBMod")
     {
         if (channelSettings.getDirection() == 1)
         {
             QJsonObject ssbModSettingsJsonObject = jsonObject["SSBModSettings"].toObject();
             channelSettingsKeys = ssbModSettingsJsonObject.keys();
             if (channelSettingsKeys.contains("cwKeyer"))
             {
                 QJsonObject cwKeyerSettingsJsonObject;
                 appendSettingsSubKeys(ssbModSettingsJsonObject, cwKeyerSettingsJsonObject, "cwKeyer", channelSettingsKeys);
             }
             channelSettings.setSsbModSettings(new SWGSDRangel::SWGSSBModSettings());
             channelSettings.getSsbModSettings()->fromJsonObject(ssbModSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "UDPSource")
     {
         if (channelSettings.getDirection() == 1)
         {
             QJsonObject udpSourceSettingsJsonObject = jsonObject["UDPSourceSettings"].toObject();
             channelSettingsKeys = udpSourceSettingsJsonObject.keys();
             channelSettings.setUdpSourceSettings(new SWGSDRangel::SWGUDPSourceSettings());
             channelSettings.getUdpSourceSettings()->fromJsonObject(udpSourceSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "UDPSink")
     {
         if (channelSettings.getDirection() == 0)
         {
             QJsonObject udpSinkSettingsJsonObject = jsonObject["UDPSinkSettings"].toObject();
             channelSettingsKeys = udpSinkSettingsJsonObject.keys();
             channelSettings.setUdpSinkSettings(new SWGSDRangel::SWGUDPSinkSettings());
             channelSettings.getUdpSinkSettings()->fromJsonObject(udpSinkSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "WFMDemod")
     {
         if (channelSettings.getDirection() == 0)
         {
             QJsonObject wfmDemodSettingsJsonObject = jsonObject["WFMDemodSettings"].toObject();
             channelSettingsKeys = wfmDemodSettingsJsonObject.keys();
             channelSettings.setWfmDemodSettings(new SWGSDRangel::SWGWFMDemodSettings());
             channelSettings.getWfmDemodSettings()->fromJsonObject(wfmDemodSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else if (*channelType == "WFMMod")
     {
         if (channelSettings.getDirection() == 1)
         {
             QJsonObject wfmModSettingsJsonObject = jsonObject["WFMModSettings"].toObject();
             channelSettingsKeys = wfmModSettingsJsonObject.keys();
             if (channelSettingsKeys.contains("cwKeyer"))
             {
                 QJsonObject cwKeyerSettingsJsonObject;
                 appendSettingsSubKeys(wfmModSettingsJsonObject, cwKeyerSettingsJsonObject, "cwKeyer", channelSettingsKeys);
             }
             channelSettings.setWfmModSettings(new SWGSDRangel::SWGWFMModSettings());
             channelSettings.getWfmModSettings()->fromJsonObject(wfmModSettingsJsonObject);
             return true;
         }
         else {
             return false;
         }
     }
     else
     {
         return false;
     }
 }
validateDeviceListItem()
bool WebAPIRequestMapper::validateDeviceListItem (SWGSDRangel::SWGDeviceListItem & deviceListItem, QJsonObject & jsonObject) private
Definition at line 1797 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGDeviceListItem::setDeviceStreamIndex(), SWGSDRangel::SWGDeviceListItem::setDirection(), SWGSDRangel::SWGDeviceListItem::setDisplayedName(), SWGSDRangel::SWGDeviceListItem::setHwType(), SWGSDRangel::SWGDeviceListItem::setIndex(), SWGSDRangel::SWGDeviceListItem::setSequence(), and SWGSDRangel::SWGDeviceListItem::setSerial().
Referenced by devicesetDeviceService().
 {
     if (jsonObject.contains("direction")) {
         deviceListItem.setDirection(jsonObject["direction"].toInt());
     } else {
         deviceListItem.setDirection(0); // assume Rx
     }
     bool identified = false;
     if (jsonObject.contains("displayedName") && jsonObject["displayedName"].isString())
     {
         deviceListItem.setDisplayedName(new QString(jsonObject["displayedName"].toString()));
         identified = true;
     } else {
         deviceListItem.setDisplayedName(0);
     }
     if (jsonObject.contains("hwType") && jsonObject["hwType"].isString())
     {
         deviceListItem.setHwType(new QString(jsonObject["hwType"].toString()));
         identified = true;
     } else {
         deviceListItem.setHwType(0);
     }
     if (jsonObject.contains("serial") && jsonObject["serial"].isString())
     {
         deviceListItem.setSerial(new QString(jsonObject["serial"].toString()));
         identified = true;
     } else {
         deviceListItem.setSerial(0);
     }
     if (jsonObject.contains("index")) {
         deviceListItem.setIndex(jsonObject["index"].toInt(-1));
     } else {
         deviceListItem.setIndex(-1);
     }
     if (jsonObject.contains("sequence")){
         deviceListItem.setSequence(jsonObject["sequence"].toInt(-1));
     } else {
         deviceListItem.setSequence(-1);
     }
     if (jsonObject.contains("deviceStreamIndex")) {
         deviceListItem.setDeviceStreamIndex(jsonObject["deviceStreamIndex"].toInt(-1));
     } else {
         deviceListItem.setDeviceStreamIndex(-1);
     }
     return identified;
 }
validateDeviceSettings()
bool WebAPIRequestMapper::validateDeviceSettings (SWGSDRangel::SWGDeviceSettings & deviceSettings, QJsonObject & jsonObject, QStringList & deviceSettingsKeys) private
Definition at line 1853 of file webapirequestmapper.cpp.
References appendSettingsArrayKeys(), SWGSDRangel::SWGAirspySettings::fromJsonObject(), SWGSDRangel::SWGAirspyHFSettings::fromJsonObject(), SWGSDRangel::SWGHackRFInputSettings::fromJsonObject(), SWGSDRangel::SWGTestSourceSettings::fromJsonObject(), SWGSDRangel::SWGBladeRF1OutputSettings::fromJsonObject(), SWGSDRangel::SWGBladeRF2InputSettings::fromJsonObject(), SWGSDRangel::SWGHackRFOutputSettings::fromJsonObject(), SWGSDRangel::SWGXtrxInputSettings::fromJsonObject(), SWGSDRangel::SWGBladeRF2OutputSettings::fromJsonObject(), SWGSDRangel::SWGKiwiSDRSettings::fromJsonObject(), SWGSDRangel::SWGXtrxOutputSettings::fromJsonObject(), SWGSDRangel::SWGLimeSdrInputSettings::fromJsonObject(), SWGSDRangel::SWGRemoteInputSettings::fromJsonObject(), SWGSDRangel::SWGLocalInputSettings::fromJsonObject(), SWGSDRangel::SWGLimeSdrOutputSettings::fromJsonObject(), SWGSDRangel::SWGRemoteOutputSettings::fromJsonObject(), SWGSDRangel::SWGLocalOutputSettings::fromJsonObject(), SWGSDRangel::SWGBladeRF1InputSettings::fromJsonObject(), SWGSDRangel::SWGFCDProSettings::fromJsonObject(), SWGSDRangel::SWGPerseusSettings::fromJsonObject(), SWGSDRangel::SWGPlutoSdrInputSettings::fromJsonObject(), SWGSDRangel::SWGPlutoSdrOutputSettings::fromJsonObject(), SWGSDRangel::SWGFCDProPlusSettings::fromJsonObject(), SWGSDRangel::SWGRtlSdrSettings::fromJsonObject(), SWGSDRangel::SWGFileInputSettings::fromJsonObject(), SWGSDRangel::SWGSDRPlaySettings::fromJsonObject(), SWGSDRangel::SWGTestMISettings::fromJsonObject(), SWGSDRangel::SWGSoapySDRInputSettings::fromJsonObject(), SWGSDRangel::SWGSoapySDROutputSettings::fromJsonObject(), SWGSDRangel::SWGDeviceSettings::getAirspyHfSettings(), SWGSDRangel::SWGDeviceSettings::getAirspySettings(), SWGSDRangel::SWGDeviceSettings::getBladeRf1InputSettings(), SWGSDRangel::SWGDeviceSettings::getBladeRf1OutputSettings(), SWGSDRangel::SWGDeviceSettings::getBladeRf2InputSettings(), SWGSDRangel::SWGDeviceSettings::getBladeRf2OutputSettings(), SWGSDRangel::SWGDeviceSettings::getDeviceHwType(), SWGSDRangel::SWGDeviceSettings::getDirection(), SWGSDRangel::SWGDeviceSettings::getFcdProPlusSettings(), SWGSDRangel::SWGDeviceSettings::getFcdProSettings(), SWGSDRangel::SWGDeviceSettings::getFileInputSettings(), SWGSDRangel::SWGDeviceSettings::getHackRfInputSettings(), SWGSDRangel::SWGDeviceSettings::getHackRfOutputSettings(), SWGSDRangel::SWGDeviceSettings::getKiwiSdrSettings(), SWGSDRangel::SWGDeviceSettings::getLimeSdrInputSettings(), SWGSDRangel::SWGDeviceSettings::getLimeSdrOutputSettings(), SWGSDRangel::SWGDeviceSettings::getLocalInputSettings(), SWGSDRangel::SWGDeviceSettings::getLocalOutputSettings(), SWGSDRangel::SWGDeviceSettings::getPerseusSettings(), SWGSDRangel::SWGDeviceSettings::getPlutoSdrInputSettings(), SWGSDRangel::SWGDeviceSettings::getPlutoSdrOutputSettings(), SWGSDRangel::SWGDeviceSettings::getRemoteInputSettings(), SWGSDRangel::SWGDeviceSettings::getRemoteOutputSettings(), SWGSDRangel::SWGDeviceSettings::getRtlSdrSettings(), SWGSDRangel::SWGDeviceSettings::getSdrPlaySettings(), SWGSDRangel::SWGDeviceSettings::getSoapySdrInputSettings(), SWGSDRangel::SWGDeviceSettings::getSoapySdrOutputSettings(), SWGSDRangel::SWGDeviceSettings::getTestMiSettings(), SWGSDRangel::SWGDeviceSettings::getTestSourceSettings(), SWGSDRangel::SWGDeviceSettings::getXtrxInputSettings(), SWGSDRangel::SWGDeviceSettings::getXtrxOutputSettings(), SWGSDRangel::SWGSoapySDRInputSettings::init(), SWGSDRangel::SWGDeviceSettings::setAirspyHfSettings(), SWGSDRangel::SWGDeviceSettings::setAirspySettings(), SWGSDRangel::SWGDeviceSettings::setBladeRf1InputSettings(), SWGSDRangel::SWGDeviceSettings::setBladeRf1OutputSettings(), SWGSDRangel::SWGDeviceSettings::setBladeRf2InputSettings(), SWGSDRangel::SWGDeviceSettings::setBladeRf2OutputSettings(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGDeviceSettings::setFcdProPlusSettings(), SWGSDRangel::SWGDeviceSettings::setFcdProSettings(), SWGSDRangel::SWGDeviceSettings::setFileInputSettings(), SWGSDRangel::SWGDeviceSettings::setHackRfInputSettings(), SWGSDRangel::SWGDeviceSettings::setHackRfOutputSettings(), SWGSDRangel::SWGDeviceSettings::setKiwiSdrSettings(), SWGSDRangel::SWGDeviceSettings::setLimeSdrInputSettings(), SWGSDRangel::SWGDeviceSettings::setLimeSdrOutputSettings(), SWGSDRangel::SWGDeviceSettings::setLocalInputSettings(), SWGSDRangel::SWGDeviceSettings::setLocalOutputSettings(), SWGSDRangel::SWGDeviceSettings::setPerseusSettings(), SWGSDRangel::SWGDeviceSettings::setPlutoSdrInputSettings(), SWGSDRangel::SWGDeviceSettings::setPlutoSdrOutputSettings(), SWGSDRangel::SWGDeviceSettings::setRemoteInputSettings(), SWGSDRangel::SWGDeviceSettings::setRemoteOutputSettings(), SWGSDRangel::SWGDeviceSettings::setRtlSdrSettings(), SWGSDRangel::SWGDeviceSettings::setSdrPlaySettings(), SWGSDRangel::SWGDeviceSettings::setSoapySdrInputSettings(), SWGSDRangel::SWGDeviceSettings::setSoapySdrOutputSettings(), SWGSDRangel::SWGDeviceSettings::setTestMiSettings(), SWGSDRangel::SWGDeviceSettings::setTestSourceSettings(), SWGSDRangel::SWGDeviceSettings::setXtrxInputSettings(), and SWGSDRangel::SWGDeviceSettings::setXtrxOutputSettings().
Referenced by devicesetDeviceSettingsService().
 {
     if (jsonObject.contains("direction")) {
         deviceSettings.setDirection(jsonObject["direction"].toInt());
     } else {
         deviceSettings.setDirection(0); // assume single Rx
     }
     if (jsonObject.contains("deviceHwType") && jsonObject["deviceHwType"].isString()) {
         deviceSettings.setDeviceHwType(new QString(jsonObject["deviceHwType"].toString()));
     } else {
         return false;
     }
     QString *deviceHwType = deviceSettings.getDeviceHwType();
     if ((*deviceHwType == "Airspy") && (deviceSettings.getDirection() == 0))
     {
         if (jsonObject.contains("airspySettings") && jsonObject["airspySettings"].isObject())
         {
             QJsonObject airspySettingsJsonObject = jsonObject["airspySettings"].toObject();
             deviceSettingsKeys = airspySettingsJsonObject.keys();
             deviceSettings.setAirspySettings(new SWGSDRangel::SWGAirspySettings());
             deviceSettings.getAirspySettings()->fromJsonObject(airspySettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "AirspyHF") && (deviceSettings.getDirection() == 0))
     {
         if (jsonObject.contains("airspyHFSettings") && jsonObject["airspyHFSettings"].isObject())
         {
             QJsonObject airspyHFSettingsJsonObject = jsonObject["airspyHFSettings"].toObject();
             deviceSettingsKeys = airspyHFSettingsJsonObject.keys();
             deviceSettings.setAirspyHfSettings(new SWGSDRangel::SWGAirspyHFSettings());
             deviceSettings.getAirspyHfSettings()->fromJsonObject(airspyHFSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "BladeRF1") && (deviceSettings.getDirection() == 0))
     {
         if (jsonObject.contains("bladeRF1InputSettings") && jsonObject["bladeRF1InputSettings"].isObject())
         {
             QJsonObject bladeRF1InputSettingsJsonObject = jsonObject["bladeRF1InputSettings"].toObject();
             deviceSettingsKeys = bladeRF1InputSettingsJsonObject.keys();
             deviceSettings.setBladeRf1InputSettings(new SWGSDRangel::SWGBladeRF1InputSettings());
             deviceSettings.getBladeRf1InputSettings()->fromJsonObject(bladeRF1InputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "BladeRF1") && (deviceSettings.getDirection() == 1))
     {
         if (jsonObject.contains("bladeRF1OutputSettings") && jsonObject["bladeRF1OutputSettings"].isObject())
         {
             QJsonObject bladeRF1OutputSettingsJsonObject = jsonObject["bladeRF1OutputSettings"].toObject();
             deviceSettingsKeys = bladeRF1OutputSettingsJsonObject.keys();
             deviceSettings.setBladeRf1OutputSettings(new SWGSDRangel::SWGBladeRF1OutputSettings());
             deviceSettings.getBladeRf1OutputSettings()->fromJsonObject(bladeRF1OutputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "BladeRF2") && (deviceSettings.getDirection() == 0))
     {
         if (jsonObject.contains("bladeRF2InputSettings") && jsonObject["bladeRF2InputSettings"].isObject())
         {
             QJsonObject bladeRF2InputSettingsJsonObject = jsonObject["bladeRF2InputSettings"].toObject();
             deviceSettingsKeys = bladeRF2InputSettingsJsonObject.keys();
             deviceSettings.setBladeRf2InputSettings(new SWGSDRangel::SWGBladeRF2InputSettings());
             deviceSettings.getBladeRf2InputSettings()->fromJsonObject(bladeRF2InputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "BladeRF2") && (deviceSettings.getDirection() == 1))
     {
         if (jsonObject.contains("bladeRF2OutputSettings") && jsonObject["bladeRF2OutputSettings"].isObject())
         {
             QJsonObject bladeRF2OutputSettingsJsonObject = jsonObject["bladeRF2OutputSettings"].toObject();
             deviceSettingsKeys = bladeRF2OutputSettingsJsonObject.keys();
             deviceSettings.setBladeRf2OutputSettings(new SWGSDRangel::SWGBladeRF2OutputSettings());
             deviceSettings.getBladeRf2OutputSettings()->fromJsonObject(bladeRF2OutputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if (*deviceHwType == "FCDPro")
     {
         if (jsonObject.contains("fcdProSettings") && jsonObject["fcdProSettings"].isObject())
         {
             QJsonObject fcdProSettingsJsonObject = jsonObject["fcdProSettings"].toObject();
             deviceSettingsKeys = fcdProSettingsJsonObject.keys();
             deviceSettings.setFcdProSettings(new SWGSDRangel::SWGFCDProSettings());
             deviceSettings.getFcdProSettings()->fromJsonObject(fcdProSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if (*deviceHwType == "FCDPro+")
     {
         if (jsonObject.contains("fcdProPlusSettings") && jsonObject["fcdProPlusSettings"].isObject())
         {
             QJsonObject fcdProPlusSettingsJsonObject = jsonObject["fcdProPlusSettings"].toObject();
             deviceSettingsKeys = fcdProPlusSettingsJsonObject.keys();
             deviceSettings.setFcdProPlusSettings(new SWGSDRangel::SWGFCDProPlusSettings());
             deviceSettings.getFcdProPlusSettings()->fromJsonObject(fcdProPlusSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if (*deviceHwType == "FileInput")
     {
         if (jsonObject.contains("fileInputSettings") && jsonObject["fileInputSettings"].isObject())
         {
             QJsonObject fileInputSettingsJsonObject = jsonObject["fileInputSettings"].toObject();
             deviceSettingsKeys = fileInputSettingsJsonObject.keys();
             deviceSettings.setFileInputSettings(new SWGSDRangel::SWGFileInputSettings());
             deviceSettings.getFileInputSettings()->fromJsonObject(fileInputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "HackRF") && (deviceSettings.getDirection() == 0))
     {
         if (jsonObject.contains("hackRFInputSettings") && jsonObject["hackRFInputSettings"].isObject())
         {
             QJsonObject hackRFInputSettingsJsonObject = jsonObject["hackRFInputSettings"].toObject();
             deviceSettingsKeys = hackRFInputSettingsJsonObject.keys();
             deviceSettings.setHackRfInputSettings(new SWGSDRangel::SWGHackRFInputSettings());
             deviceSettings.getHackRfInputSettings()->fromJsonObject(hackRFInputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "HackRF") && (deviceSettings.getDirection() == 1))
     {
         if (jsonObject.contains("hackRFOutputSettings") && jsonObject["hackRFOutputSettings"].isObject())
         {
             QJsonObject hackRFOutputSettingsJsonObject = jsonObject["hackRFOutputSettings"].toObject();
             deviceSettingsKeys = hackRFOutputSettingsJsonObject.keys();
             deviceSettings.setHackRfOutputSettings(new SWGSDRangel::SWGHackRFOutputSettings());
             deviceSettings.getHackRfOutputSettings()->fromJsonObject(hackRFOutputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "KiwiSDR") && (deviceSettings.getDirection() == 0))
     {
         if (jsonObject.contains("kiwiSDRSettings") && jsonObject["kiwiSDRSettings"].isObject())
         {
             QJsonObject kiwiSDRSettingsJsonObject = jsonObject["kiwiSDRSettings"].toObject();
             deviceSettingsKeys = kiwiSDRSettingsJsonObject.keys();
             deviceSettings.setKiwiSdrSettings(new SWGSDRangel::SWGKiwiSDRSettings());
             deviceSettings.getKiwiSdrSettings()->fromJsonObject(kiwiSDRSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "LimeSDR") && (deviceSettings.getDirection() == 0))
     {
         if (jsonObject.contains("limeSdrInputSettings") && jsonObject["limeSdrInputSettings"].isObject())
         {
             QJsonObject limeSdrInputSettingsJsonObject = jsonObject["limeSdrInputSettings"].toObject();
             deviceSettingsKeys = limeSdrInputSettingsJsonObject.keys();
             deviceSettings.setLimeSdrInputSettings(new SWGSDRangel::SWGLimeSdrInputSettings());
             deviceSettings.getLimeSdrInputSettings()->fromJsonObject(limeSdrInputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "LimeSDR") && (deviceSettings.getDirection() == 1))
     {
         if (jsonObject.contains("limeSdrOutputSettings") && jsonObject["limeSdrOutputSettings"].isObject())
         {
             QJsonObject limeSdrOutputSettingsJsonObject = jsonObject["limeSdrOutputSettings"].toObject();
             deviceSettingsKeys = limeSdrOutputSettingsJsonObject.keys();
             deviceSettings.setLimeSdrOutputSettings(new SWGSDRangel::SWGLimeSdrOutputSettings());
             deviceSettings.getLimeSdrOutputSettings()->fromJsonObject(limeSdrOutputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if (*deviceHwType == "Perseus")
     {
         if (jsonObject.contains("perseusSettings") && jsonObject["perseusSettings"].isObject())
         {
             QJsonObject perseusSettingsJsonObject = jsonObject["perseusSettings"].toObject();
             deviceSettingsKeys = perseusSettingsJsonObject.keys();
             deviceSettings.setPerseusSettings(new SWGSDRangel::SWGPerseusSettings());
             deviceSettings.getPerseusSettings()->fromJsonObject(perseusSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "PlutoSDR") && (deviceSettings.getDirection() == 0))
     {
         if (jsonObject.contains("plutoSdrInputSettings") && jsonObject["plutoSdrInputSettings"].isObject())
         {
             QJsonObject plutoSdrInputSettingsJsonObject = jsonObject["plutoSdrInputSettings"].toObject();
             deviceSettingsKeys = plutoSdrInputSettingsJsonObject.keys();
             deviceSettings.setPlutoSdrInputSettings(new SWGSDRangel::SWGPlutoSdrInputSettings());
             deviceSettings.getPlutoSdrInputSettings()->fromJsonObject(plutoSdrInputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "PlutoSDR") && (deviceSettings.getDirection() == 1))
     {
         if (jsonObject.contains("plutoSdrOutputSettings") && jsonObject["plutoSdrOutputSettings"].isObject())
         {
             QJsonObject plutoSdrOutputSettingsJsonObject = jsonObject["plutoSdrOutputSettings"].toObject();
             deviceSettingsKeys = plutoSdrOutputSettingsJsonObject.keys();
             deviceSettings.setPlutoSdrOutputSettings(new SWGSDRangel::SWGPlutoSdrOutputSettings());
             deviceSettings.getPlutoSdrOutputSettings()->fromJsonObject(plutoSdrOutputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if (*deviceHwType == "RTLSDR")
     {
         if (jsonObject.contains("rtlSdrSettings") && jsonObject["rtlSdrSettings"].isObject())
         {
             QJsonObject rtlSdrSettingsJsonObject = jsonObject["rtlSdrSettings"].toObject();
             deviceSettingsKeys = rtlSdrSettingsJsonObject.keys();
             deviceSettings.setRtlSdrSettings(new SWGSDRangel::SWGRtlSdrSettings());
             deviceSettings.getRtlSdrSettings()->fromJsonObject(rtlSdrSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if (*deviceHwType == "SDRplay1")
     {
         if (jsonObject.contains("sdrPlaySettings") && jsonObject["sdrPlaySettings"].isObject())
         {
             QJsonObject sdrPlaySettingsJsonObject = jsonObject["sdrPlaySettings"].toObject();
             deviceSettingsKeys = sdrPlaySettingsJsonObject.keys();
             deviceSettings.setSdrPlaySettings(new SWGSDRangel::SWGSDRPlaySettings());
             deviceSettings.getSdrPlaySettings()->fromJsonObject(sdrPlaySettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "SoapySDR")  && (deviceSettings.getDirection() == 0))
     {
         if (jsonObject.contains("soapySDRInputSettings") && jsonObject["soapySDRInputSettings"].isObject())
         {
             QJsonObject soapySdrInputSettingsJsonObject = jsonObject["soapySDRInputSettings"].toObject();
             deviceSettingsKeys = soapySdrInputSettingsJsonObject.keys();
             deviceSettings.setSoapySdrInputSettings(new SWGSDRangel::SWGSoapySDRInputSettings());
             deviceSettings.getSoapySdrInputSettings()->init(); // contains complex objects
             deviceSettings.getSoapySdrInputSettings()->fromJsonObject(soapySdrInputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "SoapySDR")  && (deviceSettings.getDirection() == 1))
     {
         if (jsonObject.contains("soapySDROutputSettings") && jsonObject["soapySDROutputSettings"].isObject())
         {
             QJsonObject soapySdrOutputSettingsJsonObject = jsonObject["soapySDROutputSettings"].toObject();
             deviceSettingsKeys = soapySdrOutputSettingsJsonObject.keys();
             deviceSettings.setSoapySdrOutputSettings(new SWGSDRangel::SWGSoapySDROutputSettings());
             deviceSettings.getSoapySdrInputSettings()->init(); // contains complex objects
             deviceSettings.getSoapySdrOutputSettings()->fromJsonObject(soapySdrOutputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if (*deviceHwType == "TestSource")
     {
         if (jsonObject.contains("testSourceSettings") && jsonObject["testSourceSettings"].isObject())
         {
             QJsonObject testSourceSettingsJsonObject = jsonObject["testSourceSettings"].toObject();
             deviceSettingsKeys = testSourceSettingsJsonObject.keys();
             deviceSettings.setTestSourceSettings(new SWGSDRangel::SWGTestSourceSettings());
             deviceSettings.getTestSourceSettings()->fromJsonObject(testSourceSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "TestMI") && (deviceSettings.getDirection() == 2))
     {
         if (jsonObject.contains("TestMISettings") && jsonObject["TestMISettings"].isObject())
         {
             QJsonObject testMISettingsJsonObject = jsonObject["TestMISettings"].toObject();
             deviceSettingsKeys = testMISettingsJsonObject.keys();
             if (deviceSettingsKeys.contains("streams") && testMISettingsJsonObject["streams"].isArray())
             {
                 appendSettingsArrayKeys(testMISettingsJsonObject, "streams", deviceSettingsKeys);
             }
             deviceSettings.setTestMiSettings(new SWGSDRangel::SWGTestMISettings());
             deviceSettings.getTestMiSettings()->fromJsonObject(testMISettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "XTRX") && (deviceSettings.getDirection() == 0))
     {
         if (jsonObject.contains("xtrxInputSettings") && jsonObject["xtrxInputSettings"].isObject())
         {
             QJsonObject xtrxInputSettingsJsonObject = jsonObject["xtrxInputSettings"].toObject();
             deviceSettingsKeys = xtrxInputSettingsJsonObject.keys();
             deviceSettings.setXtrxInputSettings(new SWGSDRangel::SWGXtrxInputSettings());
             deviceSettings.getXtrxInputSettings()->fromJsonObject(xtrxInputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "XTRX") && (deviceSettings.getDirection() == 1))
     {
         if (jsonObject.contains("xtrxOutputSettings") && jsonObject["xtrxOutputSettings"].isObject())
         {
             QJsonObject xtrxOutputSettingsJsonObject = jsonObject["xtrxOutputSettings"].toObject();
             deviceSettingsKeys = xtrxOutputSettingsJsonObject.keys();
             deviceSettings.setXtrxOutputSettings(new SWGSDRangel::SWGXtrxOutputSettings());
             deviceSettings.getXtrxOutputSettings()->fromJsonObject(xtrxOutputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "RemoteInput") && (deviceSettings.getDirection() == 0))
     {
         if (jsonObject.contains("remoteInputSettings") && jsonObject["remoteInputSettings"].isObject())
         {
             QJsonObject remoteInputSettingsJsonObject = jsonObject["remoteInputSettings"].toObject();
             deviceSettingsKeys = remoteInputSettingsJsonObject.keys();
             deviceSettings.setRemoteInputSettings(new SWGSDRangel::SWGRemoteInputSettings());
             deviceSettings.getRemoteInputSettings()->fromJsonObject(remoteInputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "LocalInput") && (deviceSettings.getDirection() == 0))
     {
         if (jsonObject.contains("localInputSettings") && jsonObject["localInputSettings"].isObject())
         {
             QJsonObject localInputSettingsJsonObject = jsonObject["localInputSettings"].toObject();
             deviceSettingsKeys = localInputSettingsJsonObject.keys();
             deviceSettings.setLocalInputSettings(new SWGSDRangel::SWGLocalInputSettings());
             deviceSettings.getLocalInputSettings()->fromJsonObject(localInputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "RemoteOutput") && (deviceSettings.getDirection() == 1))
     {
         if (jsonObject.contains("remoteOutputSettings") && jsonObject["remoteOutputSettings"].isObject())
         {
             QJsonObject remoteOutputSettingsJsonObject = jsonObject["remoteOutputSettings"].toObject();
             deviceSettingsKeys = remoteOutputSettingsJsonObject.keys();
             deviceSettings.setRemoteOutputSettings(new SWGSDRangel::SWGRemoteOutputSettings());
             deviceSettings.getRemoteOutputSettings()->fromJsonObject(remoteOutputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else if ((*deviceHwType == "LocalOutput") && (deviceSettings.getDirection() == 1))
     {
         if (jsonObject.contains("localOutputSettings") && jsonObject["localOutputSettings"].isObject())
         {
             QJsonObject localOutputSettingsJsonObject = jsonObject["localOutputSettings"].toObject();
             deviceSettingsKeys = localOutputSettingsJsonObject.keys();
             deviceSettings.setLocalOutputSettings(new SWGSDRangel::SWGLocalOutputSettings());
             deviceSettings.getLocalOutputSettings()->fromJsonObject(localOutputSettingsJsonObject);
             return true;
         }
         else
         {
             return false;
         }
     }
     else
     {
         return false;
     }
 }
validatePresetExport()
bool WebAPIRequestMapper::validatePresetExport (SWGSDRangel::SWGPresetExport & presetExport) private
Definition at line 1782 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGPresetExport::getFilePath(), SWGSDRangel::SWGPresetExport::getPreset(), and validatePresetIdentifer().
Referenced by instancePresetFileService().
 {
     if (presetExport.getFilePath() == 0) {
         return false;
     }
     SWGSDRangel::SWGPresetIdentifier *presetIdentifier =  presetExport.getPreset();
     if (presetIdentifier == 0) {
         return false;
     }
     return validatePresetIdentifer(*presetIdentifier);
 }
validatePresetIdentifer()
bool WebAPIRequestMapper::validatePresetIdentifer (SWGSDRangel::SWGPresetIdentifier & presetIdentifier) private
Definition at line 1777 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGPresetIdentifier::getGroupName(), SWGSDRangel::SWGPresetIdentifier::getName(), and SWGSDRangel::SWGPresetIdentifier::getType().
Referenced by instancePresetService(), validatePresetExport(), and validatePresetTransfer().
 {
     return (presetIdentifier.getGroupName() && presetIdentifier.getName() && presetIdentifier.getType());
 }
validatePresetTransfer()
bool WebAPIRequestMapper::validatePresetTransfer (SWGSDRangel::SWGPresetTransfer & presetTransfer) private
Definition at line 1766 of file webapirequestmapper.cpp.
References SWGSDRangel::SWGPresetTransfer::getPreset(), and validatePresetIdentifer().
Referenced by instancePresetService().
 {
     SWGSDRangel::SWGPresetIdentifier *presetIdentifier = presetTransfer.getPreset();
     if (presetIdentifier == 0) {
         return false;
     }
     return validatePresetIdentifer(*presetIdentifier);
 }
Member Data Documentation
m_adapter
WebAPIAdapterInterface* WebAPIRequestMapper::m_adapter private
Definition at line 48 of file webapirequestmapper.h.
Referenced by devicesetChannelIndexService(), devicesetChannelReportService(), devicesetChannelService(), devicesetChannelSettingsService(), devicesetChannelsReportService(), devicesetDeviceReportService(), devicesetDeviceRunService(), devicesetDeviceService(), devicesetDeviceSettingsService(), devicesetFocusService(), devicesetService(), instanceAMBEDevicesService(), instanceAMBESerialService(), instanceAudioInputCleanupService(), instanceAudioInputParametersService(), instanceAudioOutputCleanupService(), instanceAudioOutputParametersService(), instanceAudioService(), instanceChannelsService(), instanceConfigService(), instanceDeviceSetService(), instanceDeviceSetsService(), instanceDevicesService(), instanceLocationService(), instanceLoggingService(), instancePresetFileService(), instancePresetService(), instancePresetsService(), instanceSummaryService(), and service().
m_staticFileController
qtwebapp::StaticFileController* WebAPIRequestMapper::m_staticFileController private
Definition at line 49 of file webapirequestmapper.h.
Referenced by service(), WebAPIRequestMapper(), and ~WebAPIRequestMapper().
The documentation for this class was generated from the following files:
sdrbase/webapi/webapirequestmapper.h
sdrbase/webapi/webapirequestmapper.cpp