SDRAngel: BFMDemodGUI Class Reference
BFMDemodGUI Class Reference
#include <bfmdemodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
void channelMarkerHighlightedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static BFMDemodGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceAPI, BasebandSampleSink *rxChannel)
Private Slots
void on_deltaFrequency_changed (qint64 value)
void on_rfBW_valueChanged (int value)
void on_afBW_valueChanged (int value)
void on_volume_valueChanged (int value)
void on_squelch_valueChanged (int value)
void on_audioStereo_toggled (bool stereo)
void on_lsbStereo_toggled (bool lsb)
void on_showPilot_clicked ()
void on_rds_clicked ()
void on_g14ProgServiceNames_currentIndexChanged (int index)
void on_clearData_clicked (bool checked)
void on_g00AltFrequenciesBox_activated (int index)
void on_g14MappedFrequencies_activated (int index)
void on_g14AltFrequencies_activated (int index)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void handleInputMessages ()
void audioSelect ()
void tick ()
Private Member Functions
BFMDemodGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *parent=0)
virtual ~BFMDemodGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
void rdsUpdate (bool force)
void rdsUpdateFixedFields ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
void changeFrequency (qint64 f)
Private Attributes
Ui::BFMDemodGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
BFMDemodSettings m_settings
bool m_doApplySettings
int m_rdsTimerCount
SpectrumVis * m_spectrumVis
BFMDemod * m_bfmDemod
int m_rate
std::vector< unsigned int > m_g14ComboIndex
MessageQueue m_inputMessageQueue
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 40 of file bfmdemodgui.h.
Constructor & Destructor Documentation
BFMDemodGUI()
BFMDemodGUI::BFMDemodGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * parent = 0) explicit private
Definition at line 351 of file bfmdemodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), arg(), audioSelect(), FFTWindow::BlackmanHarris, channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), LevelMeterSignalDB::ColorGreenAndBlue, SpectrumVis::configure(), displaySettings(), ChannelMarker::getColor(), getInputMessageQueue(), BasebandSampleSink::getInputMessageQueue(), MainWindow::getInstance(), ColorMapper::GrayGold, handleInputMessages(), m_bfmDemod, BFMDemod::m_channelIdURI, m_channelMarker, m_deviceUISet, m_rate, BFMDemodSettings::m_rgbColor, m_settings, m_spectrumVis, onMenuDialogCalled(), onWidgetRolled(), rdsUpdate(), rdsUpdateFixedFields(), DeviceUISet::registerRxChannelInstance(), SDR_RX_SCALEF, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), BFMDemodSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSink::setMessageQueueToGUI(), BFMDemod::setSampleSink(), BFMDemodSettings::setSpectrumGUI(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                        :
     RollupWidget(parent),
     ui(new Ui::BFMDemodGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_rdsTimerCount(0),
     m_rate(625000)
 {
     ui->setupUi(this);
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     ui->channelPowerMeter->setColorTheme(LevelMeterSignalDB::ColorGreenAndBlue);
     CRightClickEnabler *audioMuteRightClickEnabler = new CRightClickEnabler(ui->audioStereo);
     connect(audioMuteRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioSelect()));
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
     m_spectrumVis = new SpectrumVis(SDR_RX_SCALEF, ui->glSpectrum);
     m_bfmDemod = (BFMDemod*) rxChannel; //new BFMDemod(m_deviceUISet->m_deviceSourceAPI);
     m_bfmDemod->setMessageQueueToGUI(getInputMessageQueue());
     m_bfmDemod->setSampleSink(m_spectrumVis);
     ui->glSpectrum->setCenterFrequency(m_rate / 4);
     ui->glSpectrum->setSampleRate(m_rate / 2);
     ui->glSpectrum->setDisplayWaterfall(false);
     ui->glSpectrum->setDisplayMaxHold(false);
     ui->glSpectrum->setSsbSpectrum(true);
     m_spectrumVis->configure(
             m_spectrumVis->getInputMessageQueue(),
             64, // FFT size
             10, // overlapping %
             0,  // number of averaging samples
             0,  // no averaging
             FFTWindow::BlackmanHarris,
             false); // logarithmic scale
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     m_channelMarker.setBandwidth(12500);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("Broadcast FM Demod");
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     setTitleColor(m_channelMarker.getColor());
     m_settings.setChannelMarker(&m_channelMarker);
     m_settings.setSpectrumGUI(ui->spectrumGUI);
     m_deviceUISet->registerRxChannelInstance(BFMDemod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(&m_channelMarker, SIGNAL(highlightedByCursor()), this, SLOT(channelMarkerHighlightedByCursor()));
     ui->spectrumGUI->setBuddies(m_spectrumVis->getInputMessageQueue(), m_spectrumVis, ui->glSpectrum);
     ui->g00AltFrequenciesBox->setEnabled(false);
     ui->g14MappedFrequencies->setEnabled(false);
     ui->g14AltFrequencies->setEnabled(false);
     rdsUpdateFixedFields();
     rdsUpdate(true);
     displaySettings();
     applySettings(true);
 }
~BFMDemodGUI()
BFMDemodGUI::~BFMDemodGUI () private virtual
Definition at line 426 of file bfmdemodgui.cpp.
References m_bfmDemod, m_deviceUISet, m_spectrumVis, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_bfmDemod; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete m_spectrumVis;
     delete ui;
 }
Member Function Documentation
applySettings()
void BFMDemodGUI::applySettings (bool force = false) private
Definition at line 439 of file bfmdemodgui.cpp.
References BFMDemod::MsgConfigureBFMDemod::create(), BFMDemod::MsgConfigureChannelizer::create(), BasebandSampleSink::getInputMessageQueue(), m_bfmDemod, m_doApplySettings, BFMDemodSettings::m_inputFrequencyOffset, BFMDemodSettings::m_rfBandwidth, m_settings, MessageQueue::push(), and BFMDemod::requiredBW().
Referenced by audioSelect(), BFMDemodGUI(), channelMarkerChangedByCursor(), deserialize(), on_afBW_valueChanged(), on_audioStereo_toggled(), on_deltaFrequency_changed(), on_lsbStereo_toggled(), on_rds_clicked(), on_rfBW_valueChanged(), on_showPilot_clicked(), on_squelch_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), and setCenterFrequency().
 {
     if (m_doApplySettings)
     {
         BFMDemod::MsgConfigureChannelizer *msgChan = BFMDemod::MsgConfigureChannelizer::create(
                 BFMDemod::requiredBW(m_settings.m_rfBandwidth),
                 m_settings.m_inputFrequencyOffset);
         m_bfmDemod->getInputMessageQueue()->push(msgChan);
         BFMDemod::MsgConfigureBFMDemod* msgConfig = BFMDemod::MsgConfigureBFMDemod::create( m_settings, force);
         m_bfmDemod->getInputMessageQueue()->push(msgConfig);
     }
 }
audioSelect
void BFMDemodGUI::audioSelect () private slot
Definition at line 499 of file bfmdemodgui.cpp.
References applySettings(), DSPEngine::instance(), BFMDemodSettings::m_audioDeviceName, AudioSelectDialog::m_audioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by BFMDemodGUI().
 {
     qDebug("BFMDemodGUI::audioSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName);
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_audioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
blockApplySettings()
void BFMDemodGUI::blockApplySettings (bool block) private
Definition at line 434 of file bfmdemodgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), handleMessage(), and resetToDefaults().
 {
     m_doApplySettings = !block;
 }
changeFrequency()
void BFMDemodGUI::changeFrequency (qint64 f) private
Definition at line 809 of file bfmdemodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
Referenced by on_g00AltFrequenciesBox_activated(), on_g14AltFrequencies_activated(), and on_g14MappedFrequencies_activated().
 {
     qint64 df = m_channelMarker.getCenterFrequency();
     qDebug() << "BFMDemodGUI::changeFrequency: " << f - df;
 }
channelMarkerChangedByCursor
void BFMDemodGUI::channelMarkerChangedByCursor () slot
Definition at line 151 of file bfmdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, BFMDemodSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by BFMDemodGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
channelMarkerHighlightedByCursor
void BFMDemodGUI::channelMarkerHighlightedByCursor () slot
Definition at line 158 of file bfmdemodgui.cpp.
References ChannelMarker::getHighlighted(), m_channelMarker, and RollupWidget::setHighlighted().
Referenced by BFMDemodGUI().
 {
     setHighlighted(m_channelMarker.getHighlighted());
 }
create()
BFMDemodGUI * BFMDemodGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceAPI, BasebandSampleSink * rxChannel) static
Definition at line 48 of file bfmdemodgui.cpp.
References BFMDemodGUI().
Referenced by BFMPlugin::createRxChannelGUI().
 {
     BFMDemodGUI* gui = new BFMDemodGUI(pluginAPI, deviceUIset, rxChannel);
     return gui;
 }
deserialize()
bool BFMDemodGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 99 of file bfmdemodgui.cpp.
References applySettings(), BFMDemodSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void BFMDemodGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 54 of file bfmdemodgui.cpp.
 {
     delete this;
 }
displaySettings()
void BFMDemodGUI::displaySettings () private
Definition at line 453 of file bfmdemodgui.cpp.
References arg(), blockApplySettings(), ChannelMarker::getCenterFrequency(), BFMDemodSettings::getRFBWIndex(), ChannelMarker::getTitle(), BFMDemodSettings::m_afBandwidth, BFMDemodSettings::m_audioStereo, m_channelMarker, BFMDemodSettings::m_inputFrequencyOffset, BFMDemodSettings::m_lsbStereo, BFMDemodSettings::m_rdsActive, BFMDemodSettings::m_rfBandwidth, BFMDemodSettings::m_rgbColor, m_settings, BFMDemodSettings::m_showPilot, BFMDemodSettings::m_squelch, BFMDemodSettings::m_title, BFMDemodSettings::m_volume, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by BFMDemodGUI(), deserialize(), handleMessage(), and resetToDefaults().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setBandwidth(m_settings.m_rfBandwidth);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor); // activate signal on the last setting only
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     ui->rfBW->setValue(BFMDemodSettings::getRFBWIndex(m_settings.m_rfBandwidth));
     ui->rfBWText->setText(QString("%1 kHz").arg(m_settings.m_rfBandwidth / 1000.0));
     ui->afBW->setValue(m_settings.m_afBandwidth/1000.0);
     ui->afBWText->setText(QString("%1 kHz").arg(m_settings.m_afBandwidth/1000.0));
     ui->volume->setValue(m_settings.m_volume * 10.0);
     ui->volumeText->setText(QString("%1").arg(m_settings.m_volume, 0, 'f', 1));
     ui->squelch->setValue(m_settings.m_squelch);
     ui->squelchText->setText(QString("%1 dB").arg(m_settings.m_squelch));
     ui->audioStereo->setChecked(m_settings.m_audioStereo);
     ui->lsbStereo->setChecked(m_settings.m_lsbStereo);
     ui->showPilot->setChecked(m_settings.m_showPilot);
     ui->rds->setChecked(m_settings.m_rdsActive);
     blockApplySettings(false);
 }
enterEvent()
void BFMDemodGUI::enterEvent (QEvent *) private
Definition at line 494 of file bfmdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 BFMDemodGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 69 of file bfmdemodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
 {
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* BFMDemodGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 55 of file bfmdemodgui.h.
Referenced by BFMDemodGUI(), and handleInputMessages().
 { return &m_inputMessageQueue; }
getName()
QString BFMDemodGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 64 of file bfmdemodgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void BFMDemodGUI::handleInputMessages () private slot
Definition at line 138 of file bfmdemodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by BFMDemodGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
bool BFMDemodGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 111 of file bfmdemodgui.cpp.
References blockApplySettings(), displaySettings(), BFMDemod::MsgReportChannelSampleRateChanged::getSampleRate(), BFMDemod::MsgConfigureBFMDemod::getSettings(), m_rate, m_settings, Message::match(), and ui.
Referenced by handleInputMessages().
 {
     if (BFMDemod::MsgReportChannelSampleRateChanged::match(message))
     {
         BFMDemod::MsgReportChannelSampleRateChanged& report = (BFMDemod::MsgReportChannelSampleRateChanged&) message;
         m_rate = report.getSampleRate();
         qDebug("BFMDemodGUI::handleMessage: MsgReportChannelSampleRateChanged: %d S/s", m_rate);
         ui->glSpectrum->setCenterFrequency(m_rate / 4);
         ui->glSpectrum->setSampleRate(m_rate / 2);
         return true;
     }
     else if (BFMDemod::MsgConfigureBFMDemod::match(message))
     {
         qDebug("BFMDemodGUI::handleMessage: BFMDemod::MsgConfigureBFMDemod");
         const BFMDemod::MsgConfigureBFMDemod& cfg = (BFMDemod::MsgConfigureBFMDemod&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
leaveEvent()
void BFMDemodGUI::leaveEvent (QEvent *) private
Definition at line 489 of file bfmdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_afBW_valueChanged
void BFMDemodGUI::on_afBW_valueChanged (int value) private slot
Definition at line 178 of file bfmdemodgui.cpp.
References applySettings(), arg(), BFMDemodSettings::m_afBandwidth, m_settings, and ui.
 {
     ui->afBWText->setText(QString("%1 kHz").arg(value));
     m_settings.m_afBandwidth = value * 1000.0;
     applySettings();
 }
on_audioStereo_toggled
void BFMDemodGUI::on_audioStereo_toggled (bool stereo) private slot
Definition at line 199 of file bfmdemodgui.cpp.
References applySettings(), BFMDemodSettings::m_audioStereo, m_settings, and ui.
 {
     if (!stereo)
     {
         ui->audioStereo->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
     }
     m_settings.m_audioStereo = stereo;
     applySettings();
 }
on_clearData_clicked
void BFMDemodGUI::on_clearData_clicked (bool checked) private slot
Definition at line 228 of file bfmdemodgui.cpp.
References RDSParser::clearAllFields(), BFMDemod::getRDSParser(), m_bfmDemod, rdsUpdate(), and ui.
 {
     (void) checked;
     if (ui->rds->isChecked())
     {
         m_bfmDemod->getRDSParser().clearAllFields();
         ui->g14ProgServiceNames->clear();
         ui->g14MappedFrequencies->clear();
         ui->g14AltFrequencies->clear();
         ui->g00AltFrequenciesBox->setEnabled(false);
         ui->g14MappedFrequencies->setEnabled(false);
         ui->g14AltFrequencies->setEnabled(false);
         rdsUpdate(true);
     }
 }
on_deltaFrequency_changed
void BFMDemodGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 163 of file bfmdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, BFMDemodSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_g00AltFrequenciesBox_activated
void BFMDemodGUI::on_g00AltFrequenciesBox_activated (int index) private slot
Definition at line 292 of file bfmdemodgui.cpp.
References changeFrequency(), and ui.
 {
     (void) index;
     qint64 f = (qint64) ((ui->g00AltFrequenciesBox->currentText()).toDouble() * 1e6);
     changeFrequency(f);
 }
on_g14AltFrequencies_activated
void BFMDemodGUI::on_g14AltFrequencies_activated (int index) private slot
Definition at line 306 of file bfmdemodgui.cpp.
References changeFrequency(), and ui.
 {
     (void) index;
     qint64 f = (qint64) ((ui->g14AltFrequencies->currentText()).toDouble() * 1e6);
     changeFrequency(f);
 }
on_g14MappedFrequencies_activated
void BFMDemodGUI::on_g14MappedFrequencies_activated (int index) private slot
Definition at line 299 of file bfmdemodgui.cpp.
References changeFrequency(), and ui.
 {
     (void) index;
     qint64 f = (qint64) ((ui->g14MappedFrequencies->currentText()).toDouble() * 1e6);
     changeFrequency(f);
 }
on_g14ProgServiceNames_currentIndexChanged
void BFMDemodGUI::on_g14ProgServiceNames_currentIndexChanged (int index) private slot
Definition at line 247 of file bfmdemodgui.cpp.
References BFMDemod::getRDSParser(), m_bfmDemod, RDSParser::m_g14_alt_freqs, RDSParser::m_g14_mapped_freqs, m_g14ComboIndex, and ui.
 {
     uint32_t index = _index & 0x7FFFFFF;
     if (index < m_g14ComboIndex.size())
     {
         unsigned int piKey = m_g14ComboIndex[index];
         RDSParser::freqs_map_t::const_iterator mIt = m_bfmDemod->getRDSParser().m_g14_mapped_freqs.find(piKey);
         if (mIt != m_bfmDemod->getRDSParser().m_g14_mapped_freqs.end())
         {
             ui->g14MappedFrequencies->clear();
             RDSParser::freqs_set_t::iterator sIt = (mIt->second).begin();
             const RDSParser::freqs_set_t::iterator sItEnd = (mIt->second).end();
             for (; sIt != sItEnd; ++sIt)
             {
                 std::ostringstream os;
                 os << std::fixed << std::showpoint << std::setprecision(2) << *sIt;
                 ui->g14MappedFrequencies->addItem(os.str().c_str());
             }
             ui->g14MappedFrequencies->setEnabled(ui->g14MappedFrequencies->count() > 0);
         }
         mIt = m_bfmDemod->getRDSParser().m_g14_alt_freqs.find(piKey);
         if (mIt != m_bfmDemod->getRDSParser().m_g14_alt_freqs.end())
         {
             ui->g14AltFrequencies->clear();
             RDSParser::freqs_set_t::iterator sIt = (mIt->second).begin();
             const RDSParser::freqs_set_t::iterator sItEnd = (mIt->second).end();
             for (; sIt != sItEnd; ++sIt)
             {
                 std::ostringstream os;
                 os << std::fixed << std::showpoint << std::setprecision(2) << *sIt;
                 ui->g14AltFrequencies->addItem(os.str().c_str());
             }
             ui->g14AltFrequencies->setEnabled(ui->g14AltFrequencies->count() > 0);
         }
     }
 }
on_lsbStereo_toggled
void BFMDemodGUI::on_lsbStereo_toggled (bool lsb) private slot
Definition at line 210 of file bfmdemodgui.cpp.
References applySettings(), BFMDemodSettings::m_lsbStereo, and m_settings.
 {
     m_settings.m_lsbStereo = lsb;
     applySettings();
 }
on_rds_clicked
void BFMDemodGUI::on_rds_clicked () private slot
Definition at line 222 of file bfmdemodgui.cpp.
References applySettings(), BFMDemodSettings::m_rdsActive, m_settings, and ui.
 {
     m_settings.m_rdsActive = ui->rds->isChecked();
     applySettings();
 }
on_rfBW_valueChanged
void BFMDemodGUI::on_rfBW_valueChanged (int value) private slot
Definition at line 170 of file bfmdemodgui.cpp.
References applySettings(), arg(), BFMDemodSettings::getRFBW(), m_channelMarker, BFMDemodSettings::m_rfBandwidth, m_settings, ChannelMarker::setBandwidth(), and ui.
 {
     ui->rfBWText->setText(QString("%1 kHz").arg(BFMDemodSettings::getRFBW(value) / 1000.0));
     m_channelMarker.setBandwidth(BFMDemodSettings::getRFBW(value));
     m_settings.m_rfBandwidth = BFMDemodSettings::getRFBW(value);
     applySettings();
 }
on_showPilot_clicked
void BFMDemodGUI::on_showPilot_clicked () private slot
Definition at line 216 of file bfmdemodgui.cpp.
References applySettings(), m_settings, BFMDemodSettings::m_showPilot, and ui.
 {
     m_settings.m_showPilot = ui->showPilot->isChecked();
     applySettings();
 }
on_squelch_valueChanged
void BFMDemodGUI::on_squelch_valueChanged (int value) private slot
Definition at line 192 of file bfmdemodgui.cpp.
References applySettings(), arg(), m_settings, BFMDemodSettings::m_squelch, and ui.
 {
     ui->squelchText->setText(QString("%1 dB").arg(value));
     m_settings.m_squelch = value;
     applySettings();
 }
on_volume_valueChanged
void BFMDemodGUI::on_volume_valueChanged (int value) private slot
Definition at line 185 of file bfmdemodgui.cpp.
References applySettings(), arg(), m_settings, BFMDemodSettings::m_volume, and ui.
 {
     ui->volumeText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_volume = value / 10.0;
     applySettings();
 }
onMenuDialogCalled
void BFMDemodGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 319 of file bfmdemodgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, BFMDemodSettings::m_inputFrequencyOffset, BFMDemodSettings::m_reverseAPIAddress, BFMDemodSettings::m_reverseAPIChannelIndex, BFMDemodSettings::m_reverseAPIDeviceIndex, BFMDemodSettings::m_reverseAPIPort, BFMDemodSettings::m_rgbColor, m_settings, BFMDemodSettings::m_title, BFMDemodSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by BFMDemodGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void BFMDemodGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 313 of file bfmdemodgui.cpp.
Referenced by BFMDemodGUI().
 {
     (void) widget;
     (void) rollDown;
 }
rdsUpdate()
void BFMDemodGUI::rdsUpdate (bool force) private
Definition at line 584 of file bfmdemodgui.cpp.
References arg(), RDSParser::clearUpdateFlags(), RDSParser::coverage_area_codes, CalcDb::dbPower(), RDSTMC::get_tmc_event_code_index(), RDSTMC::get_tmc_events(), BFMDemod::getDecoderQua(), BFMDemod::getDecoderSynced(), BFMDemod::getDemodAcc(), BFMDemod::getDemodFclk(), BFMDemod::getDemodQua(), BFMDemod::getRDSParser(), i, RDSParser::label_descriptions, RDSParser::language_codes, m_bfmDemod, RDSParser::m_g0_af_updated, RDSParser::m_g0_alt_freq, RDSParser::m_g0_count, RDSParser::m_g0_mono_stereo, RDSParser::m_g0_music_speech, RDSParser::m_g0_program_service_name, RDSParser::m_g0_psn_bitmap, RDSParser::m_g0_traffic_announcement, RDSParser::m_g0_updated, RDSParser::m_g14_count, RDSParser::m_g14_data_available, RDSParser::m_g14_program_service_names, RDSParser::m_g14_updated, m_g14ComboIndex, RDSParser::m_g1_count, RDSParser::m_g1_country_index, RDSParser::m_g1_country_page_index, RDSParser::m_g1_language_index, RDSParser::m_g1_pin_day, RDSParser::m_g1_pin_hour, RDSParser::m_g1_pin_minute, RDSParser::m_g1_updated, RDSParser::m_g2_count, RDSParser::m_g2_radiotext, RDSParser::m_g2_updated, RDSParser::m_g3_aid, RDSParser::m_g3_appGroup, RDSParser::m_g3_count, RDSParser::m_g3_groupB, RDSParser::m_g3_message, RDSParser::m_g3_updated, RDSParser::m_g4_count, RDSParser::m_g4_day, RDSParser::m_g4_hours, RDSParser::m_g4_local_time_offset, RDSParser::m_g4_minutes, RDSParser::m_g4_month, RDSParser::m_g4_updated, RDSParser::m_g4_year, RDSParser::m_g5_count, RDSParser::m_g5_updated, RDSParser::m_g6_count, RDSParser::m_g6_updated, RDSParser::m_g7_count, RDSParser::m_g7_updated, RDSParser::m_g8_content, RDSParser::m_g8_count, RDSParser::m_g8_event, RDSParser::m_g8_extent, RDSParser::m_g8_label_index, RDSParser::m_g8_location, RDSParser::m_g8_sign, RDSParser::m_g8_updated, RDSParser::m_g9_cA, RDSParser::m_g9_count, RDSParser::m_g9_dA, RDSParser::m_g9_dB, RDSParser::m_g9_updated, RDSParser::m_g9_varA, RDSParser::m_g9_varB, RDSParser::m_pi_area_coverage_index, RDSParser::m_pi_count, RDSParser::m_pi_program_identification, RDSParser::m_pi_program_type, RDSParser::m_pi_traffic_program, RDSParser::m_pi_updated, RDSParser::pi_country_codes, RDSParser::pty_table, and ui.
Referenced by BFMDemodGUI(), on_clearData_clicked(), and tick().
 {
     // Quality metrics
     ui->demodQText->setText(QString("%1 %").arg(m_bfmDemod->getDemodQua(), 0, 'f', 0));
     ui->decoderQText->setText(QString("%1 %").arg(m_bfmDemod->getDecoderQua(), 0, 'f', 0));
     Real accDb = CalcDb::dbPower(std::fabs(m_bfmDemod->getDemodAcc()));
     ui->accumText->setText(QString("%1 dB").arg(accDb, 0, 'f', 1));
     ui->fclkText->setText(QString("%1 Hz").arg(m_bfmDemod->getDemodFclk(), 0, 'f', 2));
     if (m_bfmDemod->getDecoderSynced()) {
         ui->decoderQLabel->setStyleSheet("QLabel { background-color : green; }");
     } else {
         ui->decoderQLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     }
     // PI group
     if (m_bfmDemod->getRDSParser().m_pi_updated || force)
     {
         ui->piLabel->setStyleSheet("QLabel { background-color : green; }");
         ui->piCountText->setNum((int) m_bfmDemod->getRDSParser().m_pi_count);
         QString pistring(str(boost::format("%04X") % m_bfmDemod->getRDSParser().m_pi_program_identification).c_str());
         ui->piText->setText(pistring);
         if (m_bfmDemod->getRDSParser().m_pi_traffic_program) {
             ui->piTPIndicator->setStyleSheet("QLabel { background-color : green; }");
         } else {
             ui->piTPIndicator->setStyleSheet("QLabel { background:rgb(79,79,79); }");
         }
         ui->piType->setText(QString(m_bfmDemod->getRDSParser().pty_table[m_bfmDemod->getRDSParser().m_pi_program_type].c_str()));
         ui->piCoverage->setText(QString(m_bfmDemod->getRDSParser().coverage_area_codes[m_bfmDemod->getRDSParser().m_pi_area_coverage_index].c_str()));
     }
     else
     {
         ui->piLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     }
     // G0 group
     if (m_bfmDemod->getRDSParser().m_g0_updated || force)
     {
         ui->g00Label->setStyleSheet("QLabel { background-color : green; }");
         ui->g00CountText->setNum((int) m_bfmDemod->getRDSParser().m_g0_count);
         if (m_bfmDemod->getRDSParser().m_g0_psn_bitmap == 0b1111) {
             ui->g00ProgServiceName->setText(QString(m_bfmDemod->getRDSParser().m_g0_program_service_name));
         }
         if (m_bfmDemod->getRDSParser().m_g0_traffic_announcement) {
             ui->g00TrafficAnnouncement->setStyleSheet("QLabel { background-color : green; }");
         } else {
             ui->g00TrafficAnnouncement->setStyleSheet("QLabel { background:rgb(79,79,79); }");
         }
         ui->g00MusicSpeech->setText(QString((m_bfmDemod->getRDSParser().m_g0_music_speech ? "Music" : "Speech")));
         ui->g00MonoStereo->setText(QString((m_bfmDemod->getRDSParser().m_g0_mono_stereo ? "Mono" : "Stereo")));
         if (m_bfmDemod->getRDSParser().m_g0_af_updated)
         {
             ui->g00AltFrequenciesBox->clear();
             for (std::set<double>::iterator it = m_bfmDemod->getRDSParser().m_g0_alt_freq.begin(); it != m_bfmDemod->getRDSParser().m_g0_alt_freq.end(); ++it)
             {
                 if (*it > 76.0)
                 {
                     std::ostringstream os;
                     os << std::fixed << std::showpoint << std::setprecision(2) << *it;
                     ui->g00AltFrequenciesBox->addItem(QString(os.str().c_str()));
                 }
             }
             ui->g00AltFrequenciesBox->setEnabled(ui->g00AltFrequenciesBox->count() > 0);
         }
     }
     else
     {
         ui->g00Label->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     }
     // G1 group
     if (m_bfmDemod->getRDSParser().m_g1_updated || force)
     {
         ui->g01Label->setStyleSheet("QLabel { background-color : green; }");
         ui->g01CountText->setNum((int) m_bfmDemod->getRDSParser().m_g1_count);
         if ((m_bfmDemod->getRDSParser().m_g1_country_page_index >= 0) && (m_bfmDemod->getRDSParser().m_g1_country_index >= 0)) {
             ui->g01CountryCode->setText(QString((m_bfmDemod->getRDSParser().pi_country_codes[m_bfmDemod->getRDSParser().m_g1_country_page_index][m_bfmDemod->getRDSParser().m_g1_country_index]).c_str()));
         }
         if (m_bfmDemod->getRDSParser().m_g1_language_index >= 0) {
             ui->g01Language->setText(QString(m_bfmDemod->getRDSParser().language_codes[m_bfmDemod->getRDSParser().m_g1_language_index].c_str()));
         }
         ui->g01DHM->setText(QString(str(boost::format("%id:%i:%i") % m_bfmDemod->getRDSParser().m_g1_pin_day % m_bfmDemod->getRDSParser().m_g1_pin_hour % m_bfmDemod->getRDSParser().m_g1_pin_minute).c_str()));
     }
     else
     {
         ui->g01Label->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     }
     // G2 group
     if (m_bfmDemod->getRDSParser().m_g2_updated || force)
     {
         ui->g02Label->setStyleSheet("QLabel { background-color : green; }");
         ui->g02CountText->setNum((int) m_bfmDemod->getRDSParser().m_g2_count);
         ui->go2Text->setText(QString(m_bfmDemod->getRDSParser().m_g2_radiotext));
     }
     else
     {
         ui->g02Label->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     }
     // G3 group
     if (m_bfmDemod->getRDSParser().m_g3_updated || force)
     {
         ui->g03Label->setStyleSheet("QLabel { background-color : green; }");
         ui->g03CountText->setNum((int) m_bfmDemod->getRDSParser().m_g3_count);
         std::string g3str = str(boost::format("%02X%c %04X %04X") % m_bfmDemod->getRDSParser().m_g3_appGroup % (m_bfmDemod->getRDSParser().m_g3_groupB ? 'B' : 'A') % m_bfmDemod->getRDSParser().m_g3_message % m_bfmDemod->getRDSParser().m_g3_aid);
         ui->g03Data->setText(QString(g3str.c_str()));
     }
     else
     {
         ui->g03Label->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     }
     // G4 group
     if (m_bfmDemod->getRDSParser().m_g4_updated || force)
     {
         ui->g04Label->setStyleSheet("QLabel { background-color : green; }");
         ui->g04CountText->setNum((int) m_bfmDemod->getRDSParser().m_g4_count);
         std::string time = str(boost::format("%4i-%02i-%02i %02i:%02i (%+.1fh)")\
             % (1900 + m_bfmDemod->getRDSParser().m_g4_year) % m_bfmDemod->getRDSParser().m_g4_month % m_bfmDemod->getRDSParser().m_g4_day % m_bfmDemod->getRDSParser().m_g4_hours % m_bfmDemod->getRDSParser().m_g4_minutes % m_bfmDemod->getRDSParser().m_g4_local_time_offset);
         ui->g04Time->setText(QString(time.c_str()));
     }
     else
     {
         ui->g04Label->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     }
     // G5 group
     if (m_bfmDemod->getRDSParser().m_g5_updated || force)
     {
         ui->g05CountText->setNum((int) m_bfmDemod->getRDSParser().m_g5_count);
     }
     // G6 group
     if (m_bfmDemod->getRDSParser().m_g6_updated || force)
     {
         ui->g06CountText->setNum((int) m_bfmDemod->getRDSParser().m_g6_count);
     }
     // G7 group
     if (m_bfmDemod->getRDSParser().m_g7_updated || force)
     {
         ui->g07CountText->setNum((int) m_bfmDemod->getRDSParser().m_g7_count);
     }
     // G8 group
     if (m_bfmDemod->getRDSParser().m_g8_updated || force)
     {
         ui->g08Label->setStyleSheet("QLabel { background-color : green; }");
         ui->g08CountText->setNum((int) m_bfmDemod->getRDSParser().m_g8_count);
         std::ostringstream os;
         os << (m_bfmDemod->getRDSParser().m_g8_sign ? "-" : "+") << m_bfmDemod->getRDSParser().m_g8_extent + 1;
         ui->g08Extent->setText(QString(os.str().c_str()));
         int event_line = RDSTMC::get_tmc_event_code_index(m_bfmDemod->getRDSParser().m_g8_event, 1);
         ui->g08TMCEvent->setText(QString(RDSTMC::get_tmc_events(event_line, 1).c_str()));
         QString pistring(str(boost::format("%04X") % m_bfmDemod->getRDSParser().m_g8_location).c_str());
         ui->g08Location->setText(pistring);
         if (m_bfmDemod->getRDSParser().m_g8_label_index >= 0) {
             ui->g08Description->setText(QString(m_bfmDemod->getRDSParser().label_descriptions[m_bfmDemod->getRDSParser().m_g8_label_index].c_str()));
         }
         ui->g08Content->setNum(m_bfmDemod->getRDSParser().m_g8_content);
     }
     else
     {
         ui->g08Label->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     }
     // G9 group
     if (m_bfmDemod->getRDSParser().m_g9_updated || force)
     {
         ui->g09Label->setStyleSheet("QLabel { background-color : green; }");
         ui->g09CountText->setNum((int) m_bfmDemod->getRDSParser().m_g9_count);
         std::string g9str = str(boost::format("%02X %04X %04X %02X %04X") % m_bfmDemod->getRDSParser().m_g9_varA % m_bfmDemod->getRDSParser().m_g9_cA % m_bfmDemod->getRDSParser().m_g9_dA % m_bfmDemod->getRDSParser().m_g9_varB % m_bfmDemod->getRDSParser().m_g9_dB);
         ui->g09Data->setText(QString(g9str.c_str()));
     }
     else
     {
         ui->g09Label->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     }
     // G14 group
     if (m_bfmDemod->getRDSParser().m_g14_updated || force)
     {
         ui->g14CountText->setNum((int) m_bfmDemod->getRDSParser().m_g14_count);
         if (m_bfmDemod->getRDSParser().m_g14_data_available)
         {
             ui->g14Label->setStyleSheet("QLabel { background-color : green; }");
             m_g14ComboIndex.clear();
             ui->g14ProgServiceNames->clear();
             RDSParser::psns_map_t::iterator it = m_bfmDemod->getRDSParser().m_g14_program_service_names.begin();
             const RDSParser::psns_map_t::iterator itEnd = m_bfmDemod->getRDSParser().m_g14_program_service_names.end();
             int i = 0;
             for (; it != itEnd; ++it, i++)
             {
                 m_g14ComboIndex.push_back(it->first);
                 QString pistring(str(boost::format("%04X:%s") % it->first % it->second).c_str());
                 ui->g14ProgServiceNames->addItem(pistring);
             }
         }
         else
         {
             ui->g14Label->setStyleSheet("QLabel { background:rgb(79,79,79); }");
         }
     }
     m_bfmDemod->getRDSParser().clearUpdateFlags();
 }
rdsUpdateFixedFields()
void BFMDemodGUI::rdsUpdateFixedFields () private
Definition at line 557 of file bfmdemodgui.cpp.
References BFMDemod::getRDSParser(), m_bfmDemod, RDSParser::rds_group_acronym_tags, and ui.
Referenced by BFMDemodGUI().
 {
     ui->g00Label->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[0].c_str());
     ui->g01Label->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[1].c_str());
     ui->g02Label->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[2].c_str());
     ui->g03Label->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[3].c_str());
     ui->g04Label->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[4].c_str());
     //ui->g05Label->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[5].c_str());
     //ui->g06Label->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[6].c_str());
     //ui->g07Label->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[7].c_str());
     ui->g08Label->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[8].c_str());
     ui->g09Label->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[9].c_str());
     ui->g14Label->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[14].c_str());
     ui->g00CountLabel->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[0].c_str());
     ui->g01CountLabel->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[1].c_str());
     ui->g02CountLabel->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[2].c_str());
     ui->g03CountLabel->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[3].c_str());
     ui->g04CountLabel->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[4].c_str());
     ui->g05CountLabel->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[5].c_str());
     ui->g06CountLabel->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[6].c_str());
     ui->g07CountLabel->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[7].c_str());
     ui->g08CountLabel->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[8].c_str());
     ui->g09CountLabel->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[9].c_str());
     ui->g14CountLabel->setText(m_bfmDemod->getRDSParser().rds_group_acronym_tags[14].c_str());
 }
resetToDefaults()
void BFMDemodGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 80 of file bfmdemodgui.cpp.
References applySettings(), blockApplySettings(), displaySettings(), m_settings, BFMDemodSettings::resetToDefaults(), and ui.
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     blockApplySettings(true);
     ui->g00AltFrequenciesBox->setEnabled(false);
     ui->g14MappedFrequencies->setEnabled(false);
     ui->g14AltFrequencies->setEnabled(false);
     blockApplySettings(false);
     applySettings();
 }
serialize()
QByteArray BFMDemodGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 94 of file bfmdemodgui.cpp.
References m_settings, and BFMDemodSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void BFMDemodGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 74 of file bfmdemodgui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     applySettings();
 }
setName()
void BFMDemodGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 59 of file bfmdemodgui.cpp.
 {
     setObjectName(name);
 }
tick
void BFMDemodGUI::tick () private slot
Definition at line 512 of file bfmdemodgui.cpp.
References CalcDb::dbPower(), BFMDemod::getMagSqLevels(), BFMDemod::getPilotLevel(), BFMDemod::getPilotLock(), m_bfmDemod, m_rdsTimerCount, rdsUpdate(), and ui.
Referenced by BFMDemodGUI().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     m_bfmDemod->getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     Real powDbAvg = CalcDb::dbPower(magsqAvg);
     Real powDbPeak = CalcDb::dbPower(magsqPeak);
     ui->channelPowerMeter->levelChanged(
             (100.0f + powDbAvg) / 100.0f,
             (100.0f + powDbPeak) / 100.0f,
             nbMagsqSamples);
     ui->channelPower->setText(QString::number(powDbAvg, 'f', 1));
     Real pilotPowDb =  CalcDb::dbPower(m_bfmDemod->getPilotLevel());
     QString pilotPowDbStr;
     pilotPowDbStr.sprintf("%+02.1f", pilotPowDb);
     ui->pilotPower->setText(pilotPowDbStr);
     if (m_bfmDemod->getPilotLock())
     {
         if (ui->audioStereo->isChecked())
         {
             ui->audioStereo->setStyleSheet("QToolButton { background-color : green; }");
         }
     }
     else
     {
         if (ui->audioStereo->isChecked())
         {
             ui->audioStereo->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         }
     }
     if (ui->rds->isChecked() && (m_rdsTimerCount == 0))
     {
         rdsUpdate(false);
     }
     m_rdsTimerCount = (m_rdsTimerCount + 1) % 25;
     //qDebug() << "Pilot lock: " << m_bfmDemod->getPilotLock() << ":" << m_bfmDemod->getPilotLevel(); TODO: update a GUI item with status
 }
Member Data Documentation
m_bfmDemod
BFMDemod* BFMDemodGUI::m_bfmDemod private
Definition at line 73 of file bfmdemodgui.h.
Referenced by applySettings(), BFMDemodGUI(), on_clearData_clicked(), on_g14ProgServiceNames_currentIndexChanged(), rdsUpdate(), rdsUpdateFixedFields(), tick(), and ~BFMDemodGUI().
m_channelMarker
ChannelMarker BFMDemodGUI::m_channelMarker private
Definition at line 66 of file bfmdemodgui.h.
Referenced by BFMDemodGUI(), changeFrequency(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), on_deltaFrequency_changed(), on_rfBW_valueChanged(), onMenuDialogCalled(), and setCenterFrequency().
m_deviceUISet
DeviceUISet* BFMDemodGUI::m_deviceUISet private
Definition at line 65 of file bfmdemodgui.h.
Referenced by BFMDemodGUI(), and ~BFMDemodGUI().
m_doApplySettings
bool BFMDemodGUI::m_doApplySettings private
Definition at line 68 of file bfmdemodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_g14ComboIndex
std::vector<unsigned int> BFMDemodGUI::m_g14ComboIndex private
Definition at line 75 of file bfmdemodgui.h.
Referenced by on_g14ProgServiceNames_currentIndexChanged(), and rdsUpdate().
m_inputMessageQueue
MessageQueue BFMDemodGUI::m_inputMessageQueue private
Definition at line 76 of file bfmdemodgui.h.
m_pluginAPI
PluginAPI* BFMDemodGUI::m_pluginAPI private
Definition at line 64 of file bfmdemodgui.h.
m_rate
int BFMDemodGUI::m_rate private
Definition at line 74 of file bfmdemodgui.h.
Referenced by BFMDemodGUI(), and handleMessage().
m_rdsTimerCount
int BFMDemodGUI::m_rdsTimerCount private
Definition at line 69 of file bfmdemodgui.h.
Referenced by tick().
m_settings
BFMDemodSettings BFMDemodGUI::m_settings private
Definition at line 67 of file bfmdemodgui.h.
Referenced by applySettings(), audioSelect(), BFMDemodGUI(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), handleMessage(), on_afBW_valueChanged(), on_audioStereo_toggled(), on_deltaFrequency_changed(), on_lsbStereo_toggled(), on_rds_clicked(), on_rfBW_valueChanged(), on_showPilot_clicked(), on_squelch_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), and serialize().
m_spectrumVis
SpectrumVis* BFMDemodGUI::m_spectrumVis private
Definition at line 71 of file bfmdemodgui.h.
Referenced by BFMDemodGUI(), and ~BFMDemodGUI().
ui
Ui::BFMDemodGUI* BFMDemodGUI::ui private
Definition at line 63 of file bfmdemodgui.h.
Referenced by BFMDemodGUI(), channelMarkerChangedByCursor(), displaySettings(), handleMessage(), on_afBW_valueChanged(), on_audioStereo_toggled(), on_clearData_clicked(), on_g00AltFrequenciesBox_activated(), on_g14AltFrequencies_activated(), on_g14MappedFrequencies_activated(), on_g14ProgServiceNames_currentIndexChanged(), on_rds_clicked(), on_rfBW_valueChanged(), on_showPilot_clicked(), on_squelch_valueChanged(), on_volume_valueChanged(), rdsUpdate(), rdsUpdateFixedFields(), resetToDefaults(), tick(), and ~BFMDemodGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/demodbfm/bfmdemodgui.h
plugins/channelrx/demodbfm/bfmdemodgui.cpp