SDRAngel: Bladerf1Output Class Reference
Bladerf1Output Class Reference
#include <bladerf1output.h>
Classes
class MsgConfigureBladerf1
class MsgReportBladerf1
class MsgStartStop
Public Member Functions
Bladerf1Output (DeviceAPI *deviceAPI)
virtual ~Bladerf1Output ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the sink.
virtual void setSampleRate (int sampleRate)
For when the sink sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the sink.
virtual void setCenterFrequency (qint64 centerFrequency)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSink
DeviceSampleSink ()
virtual ~DeviceSampleSink ()
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSourceFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
bool applySettings (const BladeRF1OutputSettings &settings, bool force)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const BladeRF1OutputSettings &settings)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const BladeRF1OutputSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
BladeRF1OutputSettings m_settings
struct bladerf * m_dev
Bladerf1OutputThread * m_bladerfThread
QString m_deviceDescription
DeviceBladeRF1Params m_sharedParams
bool m_running
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSink
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
Static Public Member Functions inherited from DeviceSampleSink
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Interp, fcPos_t fcPos, quint32 devSampleRate)
Protected Slots inherited from DeviceSampleSink
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSink
SampleSourceFifo m_sampleSourceFifo
MessageQueue m_inputMessageQueue
Input queue to the sink.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 35 of file bladerf1output.h.
Constructor & Destructor Documentation
Bladerf1Output()
Bladerf1Output::Bladerf1Output (DeviceAPI * deviceAPI)
Definition at line 41 of file bladerf1output.cpp.
References BLADERFOUTPUT_BLOCKSIZE.
Referenced by Bladerf1Output::MsgReportBladerf1::MsgReportBladerf1().
                                                    :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_dev(0),
     m_bladerfThread(0),
     m_deviceDescription("BladeRFOutput"),
     m_running(false)
 {
     m_sampleSourceFifo.resize(16*BLADERFOUTPUT_BLOCKSIZE);
     openDevice();
     m_deviceAPI->setNbSinkStreams(1);
     m_deviceAPI->setBuddySharedPtr(&m_sharedParams);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~Bladerf1Output()
Bladerf1Output::~Bladerf1Output () virtual
Definition at line 57 of file bladerf1output.cpp.
References closeDevice(), m_deviceAPI, m_networkManager, m_running, networkManagerFinished(), DeviceAPI::setBuddySharedPtr(), and stop().
Referenced by Bladerf1Output::MsgReportBladerf1::MsgReportBladerf1().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     closeDevice();
     m_deviceAPI->setBuddySharedPtr(0);
 }
Member Function Documentation
applySettings()
bool Bladerf1Output::applySettings (const BladeRF1OutputSettings & settings, bool force) private
Definition at line 304 of file bladerf1output.cpp.
References DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceAPI::getDeviceSourceEngine(), DeviceAPI::getSourceBuddies(), Bladerf1OutputThread::isRunning(), BladeRF1OutputSettings::m_bandwidth, m_bladerfThread, BladeRF1OutputSettings::m_centerFrequency, m_dev, m_deviceAPI, BladeRF1OutputSettings::m_devSampleRate, BladeRF1OutputSettings::m_log2Interp, BladeRF1OutputSettings::m_reverseAPIAddress, BladeRF1OutputSettings::m_reverseAPIDeviceIndex, BladeRF1OutputSettings::m_reverseAPIPort, DeviceBladeRF1Shared::m_sampleFifoLengthInSeconds, DeviceBladeRF1Shared::m_sampleFifoMinSize, DeviceBladeRF1Shared::m_sampleFifoMinSize32, DeviceSampleSink::m_sampleSourceFifo, m_settings, m_sharedParams, BladeRF1OutputSettings::m_useReverseAPI, BladeRF1OutputSettings::m_vga1, BladeRF1OutputSettings::m_vga2, BladeRF1OutputSettings::m_xb200, DeviceBladeRF1Params::m_xb200Attached, BladeRF1OutputSettings::m_xb200Filter, BladeRF1OutputSettings::m_xb200Path, leansdr::max(), MessageQueue::push(), SampleSourceFifo::resize(), Bladerf1OutputThread::setLog2Interpolation(), Bladerf1OutputThread::startWork(), DSPDeviceSourceEngine::state(), Bladerf1OutputThread::stopWork(), DSPDeviceSourceEngine::StRunning, and webapiReverseSendSettings().
Referenced by handleMessage(), init(), and start().
 {
     bool forwardChange    = false;
     bool suspendOwnThread = false;
     bool threadWasRunning = false;
     QList<QString> reverseAPIKeys;
 //  QMutexLocker mutexLocker(&m_mutex);
     qDebug() << "BladerfOutput::applySettings: m_dev: " << m_dev;
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency) || force) {
         reverseAPIKeys.append("centerFrequency");
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || force) {
         reverseAPIKeys.append("devSampleRate");
     }
     if ((m_settings.m_log2Interp != settings.m_log2Interp) || force) {
         reverseAPIKeys.append("log2Interp");
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) ||
         (m_settings.m_log2Interp != settings.m_log2Interp) || force)
     {
         suspendOwnThread = true;
     }
     if (suspendOwnThread)
     {
         if (m_bladerfThread)
         {
             if (m_bladerfThread->isRunning())
             {
                 m_bladerfThread->stopWork();
                 threadWasRunning = true;
             }
         }
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || (m_settings.m_log2Interp != settings.m_log2Interp) || force)
     {
         int fifoSize;
         if (settings.m_log2Interp >= 5)
         {
             fifoSize = DeviceBladeRF1Shared::m_sampleFifoMinSize32;
         }
         else
         {
             fifoSize = (std::max)(
                 (int) ((settings.m_devSampleRate/(1<<settings.m_log2Interp)) * DeviceBladeRF1Shared::m_sampleFifoLengthInSeconds),
                 DeviceBladeRF1Shared::m_sampleFifoMinSize);
         }
         m_sampleSourceFifo.resize(fifoSize);
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || force)
     {
         forwardChange = true;
         if (m_dev != 0)
         {
             unsigned int actualSamplerate;
             if (bladerf_set_sample_rate(m_dev, BLADERF_MODULE_TX, settings.m_devSampleRate, &actualSamplerate) < 0) {
                 qCritical("BladerfOutput::applySettings: could not set sample rate: %d", settings.m_devSampleRate);
             } else {
                 qDebug() << "BladerfOutput::applySettings: bladerf_set_sample_rate(BLADERF_MODULE_TX) actual sample rate is " << actualSamplerate;
             }
         }
     }
     if ((m_settings.m_log2Interp != settings.m_log2Interp) || force)
     {
         forwardChange = true;
         if (m_bladerfThread != 0)
         {
             m_bladerfThread->setLog2Interpolation(settings.m_log2Interp);
             qDebug() << "BladerfOutput::applySettings: set interpolation to " << (1<<settings.m_log2Interp);
         }
     }
     if ((m_settings.m_vga1 != settings.m_vga1) || force)
     {
         reverseAPIKeys.append("vga1");
         if (m_dev != 0)
         {
             if (bladerf_set_txvga1(m_dev, settings.m_vga1) != 0) {
                 qDebug("BladerfOutput::applySettings: bladerf_set_txvga1() failed");
             } else {
                 qDebug() << "BladerfOutput::applySettings: VGA1 gain set to " << settings.m_vga1;
             }
         }
     }
     if ((m_settings.m_vga2 != settings.m_vga2) || force)
     {
         reverseAPIKeys.append("vga2");
         if(m_dev != 0)
         {
             if (bladerf_set_txvga2(m_dev, settings.m_vga2) != 0) {
                 qDebug("BladerfOutput::applySettings:bladerf_set_rxvga2() failed");
             } else {
                 qDebug() << "BladerfOutput::applySettings: VGA2 gain set to " << settings.m_vga2;
             }
         }
     }
     if ((m_settings.m_xb200 != settings.m_xb200) || force)
     {
         reverseAPIKeys.append("xb200");
         if (m_dev != 0)
         {
             bool changeSettings;
             if (m_deviceAPI->getSourceBuddies().size() > 0)
             {
                 DeviceAPI *buddy = m_deviceAPI->getSourceBuddies()[0];
                 if (buddy->getDeviceSourceEngine()->state() == DSPDeviceSourceEngine::StRunning) { // Tx side running
                     changeSettings = false;
                 } else {
                     changeSettings = true;
                 }
             }
             else // No Rx open
             {
                 changeSettings = true;
             }
             if (changeSettings)
             {
                 if (settings.m_xb200)
                 {
                     if (bladerf_expansion_attach(m_dev, BLADERF_XB_200) != 0) {
                         qDebug("BladerfOutput::applySettings: bladerf_expansion_attach(xb200) failed");
                     } else {
                         qDebug() << "BladerfOutput::applySettings: Attach XB200";
                     }
                 }
                 else
                 {
                     if (bladerf_expansion_attach(m_dev, BLADERF_XB_NONE) != 0) {
                         qDebug("BladerfOutput::applySettings: bladerf_expansion_attach(none) failed");
                     } else {
                         qDebug() << "BladerfOutput::applySettings: Detach XB200";
                     }
                 }
                 m_sharedParams.m_xb200Attached = settings.m_xb200;
             }
         }
     }
     if ((m_settings.m_xb200Path != settings.m_xb200Path) || force)
     {
         reverseAPIKeys.append("xb200Path");
         if (m_dev != 0)
         {
             if (bladerf_xb200_set_path(m_dev, BLADERF_MODULE_TX, settings.m_xb200Path) != 0) {
                 qDebug("BladerfOutput::applySettings: bladerf_xb200_set_path(BLADERF_MODULE_TX) failed");
             } else {
                 qDebug() << "BladerfOutput::applySettings: set xb200 path to " << settings.m_xb200Path;
             }
         }
     }
     if ((m_settings.m_xb200Filter != settings.m_xb200Filter) || force)
     {
         reverseAPIKeys.append("xb200Filter");
         if (m_dev != 0)
         {
             if (bladerf_xb200_set_filterbank(m_dev, BLADERF_MODULE_TX, settings.m_xb200Filter) != 0) {
                 qDebug("BladerfOutput::applySettings: bladerf_xb200_set_filterbank(BLADERF_MODULE_TX) failed");
             } else {
                 qDebug() << "BladerfOutput::applySettings: set xb200 filter to " << settings.m_xb200Filter;
             }
         }
     }
     if ((m_settings.m_bandwidth != settings.m_bandwidth) || force)
     {
         reverseAPIKeys.append("bandwidth");
         if (m_dev != 0)
         {
             unsigned int actualBandwidth;
             if (bladerf_set_bandwidth(m_dev, BLADERF_MODULE_TX, settings.m_bandwidth, &actualBandwidth) < 0) {
                 qCritical("BladerfOutput::applySettings: could not set bandwidth: %d", settings.m_bandwidth);
             } else {
                 qDebug() << "BladerfOutput::applySettings: bladerf_set_bandwidth(BLADERF_MODULE_TX) actual bandwidth is " << actualBandwidth;
             }
         }
     }
     if (m_settings.m_centerFrequency != settings.m_centerFrequency)
     {
         forwardChange = true;
     }
     if (m_dev != 0)
     {
         if (bladerf_set_frequency( m_dev, BLADERF_MODULE_TX, settings.m_centerFrequency ) != 0)
         {
             qDebug("BladerfOutput::applySettings: bladerf_set_frequency(%lld) failed", settings.m_centerFrequency);
         }
     }
     if (threadWasRunning)
     {
         m_bladerfThread->startWork();
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     if (forwardChange)
     {
         int sampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Interp);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, m_settings.m_centerFrequency);
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     qDebug() << "BladerfOutput::applySettings: center freq: " << m_settings.m_centerFrequency << " Hz"
             << " device sample rate: " << m_settings.m_devSampleRate << "S/s"
             << " baseband sample rate: " << m_settings.m_devSampleRate/(1<<m_settings.m_log2Interp) << "S/s"
             << " BW: " << m_settings.m_bandwidth << "Hz";
     return true;
 }
closeDevice()
void Bladerf1Output::closeDevice () private
Definition at line 163 of file bladerf1output.cpp.
References DeviceAPI::getSourceBuddies(), DeviceBladeRF1Params::m_dev, m_dev, m_deviceAPI, and m_sharedParams.
Referenced by openDevice(), and ~Bladerf1Output().
 {
     int res;
     if (m_dev == 0) { // was never open
         return;
     }
     if ((res = bladerf_enable_module(m_dev, BLADERF_MODULE_TX, false)) < 0)
     {
         qCritical("BladerfOutput::closeDevice: bladerf_enable_module with return code %d", res);
     }
     if (m_deviceAPI->getSourceBuddies().size() == 0)
     {
         qDebug("BladerfOutput::closeDevice: closing device since Rx side is not open");
         if (m_dev != 0) // close BladeRF
         {
             bladerf_close(m_dev);
         }
     }
     m_sharedParams.m_dev = 0;
     m_dev = 0;
 }
deserialize()
bool Bladerf1Output::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSink.
Definition at line 208 of file bladerf1output.cpp.
References Bladerf1Output::MsgConfigureBladerf1::create(), BladeRF1OutputSettings::deserialize(), DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and BladeRF1OutputSettings::resetToDefaults().
Referenced by Bladerf1Output::MsgReportBladerf1::MsgReportBladerf1().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureBladerf1* message = MsgConfigureBladerf1::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureBladerf1* messageToGUI = MsgConfigureBladerf1::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void Bladerf1Output::destroy () virtual
Implements DeviceSampleSink.
Definition at line 70 of file bladerf1output.cpp.
Referenced by Bladerf1Output::MsgReportBladerf1::MsgReportBladerf1().
 {
     delete this;
 }
getCenterFrequency()
quint64 Bladerf1Output::getCenterFrequency () const virtual
Center frequency exposed by the sink.
Implements DeviceSampleSink.
Definition at line 241 of file bladerf1output.cpp.
References BladeRF1OutputSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & Bladerf1Output::getDeviceDescription () const virtual
Implements DeviceSampleSink.
Definition at line 230 of file bladerf1output.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getSampleRate()
int Bladerf1Output::getSampleRate () const virtual
Sample rate exposed by the sink.
Implements DeviceSampleSink.
Definition at line 235 of file bladerf1output.cpp.
References BladeRF1OutputSettings::m_devSampleRate, BladeRF1OutputSettings::m_log2Interp, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     int rate = m_settings.m_devSampleRate;
     return (rate / (1<<m_settings.m_log2Interp));
 }
handleMessage()
bool Bladerf1Output::handleMessage (const Message & message) virtual
Implements DeviceSampleSink.
Definition at line 261 of file bladerf1output.cpp.
References applySettings(), Bladerf1Output::MsgConfigureBladerf1::getForce(), Bladerf1Output::MsgConfigureBladerf1::getSettings(), Bladerf1Output::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), m_deviceAPI, m_settings, BladeRF1OutputSettings::m_useReverseAPI, Message::match(), DeviceAPI::startDeviceEngine(), DeviceAPI::stopDeviceEngine(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (MsgConfigureBladerf1::match(message))
     {
         MsgConfigureBladerf1& conf = (MsgConfigureBladerf1&) message;
         qDebug() << "BladerfOutput::handleMessage: MsgConfigureBladerf";
         if (!applySettings(conf.getSettings(), conf.getForce()))
         {
             qDebug("BladeRF config error");
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "BladerfOutput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void Bladerf1Output::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSink.
Definition at line 133 of file bladerf1output.cpp.
References applySettings(), and m_settings.
Referenced by Bladerf1Output::MsgReportBladerf1::MsgReportBladerf1().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void Bladerf1Output::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 760 of file bladerf1output.cpp.
Referenced by ~Bladerf1Output().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "Bladerf1Output::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("Bladerf1Output::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openDevice()
bool Bladerf1Output::openDevice () private
Definition at line 75 of file bladerf1output.cpp.
References closeDevice(), DeviceAPI::getBuddySharedPtr(), DeviceAPI::getSamplingDeviceSerial(), DeviceAPI::getSourceBuddies(), DeviceBladeRF1Params::m_dev, m_dev, m_deviceAPI, BladeRF1OutputSettings::m_devSampleRate, BladeRF1OutputSettings::m_log2Interp, DeviceSampleSink::m_sampleSourceFifo, m_settings, m_sharedParams, DeviceBladeRF1::open_bladerf(), and SampleSourceFifo::resize().
 {
     if (m_dev != 0)
     {
         closeDevice();
     }
     int res;
     m_sampleSourceFifo.resize(m_settings.m_devSampleRate/(1<<(m_settings.m_log2Interp <= 4 ? m_settings.m_log2Interp : 4)));
     if (m_deviceAPI->getSourceBuddies().size() > 0)
     {
         DeviceAPI *sourceBuddy = m_deviceAPI->getSourceBuddies()[0];
         DeviceBladeRF1Params *buddySharedParams = (DeviceBladeRF1Params *) sourceBuddy->getBuddySharedPtr();
         if (buddySharedParams == 0)
         {
             qCritical("BladerfOutput::start: could not get shared parameters from buddy");
             return false;
         }
         if (buddySharedParams->m_dev == 0) // device is not opened by buddy
         {
             qCritical("BladerfOutput::start: could not get BladeRF handle from buddy");
             return false;
         }
         m_sharedParams = *(buddySharedParams); // copy parameters from buddy
         m_dev = m_sharedParams.m_dev;          // get BladeRF handle
     }
     else
     {
         if (!DeviceBladeRF1::open_bladerf(&m_dev, qPrintable(m_deviceAPI->getSamplingDeviceSerial())))
         {
             qCritical("BladerfOutput::start: could not open BladeRF %s", qPrintable(m_deviceAPI->getSamplingDeviceSerial()));
             return false;
         }
         m_sharedParams.m_dev = m_dev;
     }
     // TODO: adjust USB transfer data according to sample rate
     if ((res = bladerf_sync_config(m_dev, BLADERF_TX_X1, BLADERF_FORMAT_SC16_Q11, 64, 8192, 32, 10000)) < 0)
     {
         qCritical("BladerfOutput::start: bladerf_sync_config with return code %d", res);
         return false;
     }
     if ((res = bladerf_enable_module(m_dev, BLADERF_MODULE_TX, true)) < 0)
     {
         qCritical("BladerfOutput::start: bladerf_enable_module with return code %d", res);
         return false;
     }
     return true;
 }
serialize()
QByteArray Bladerf1Output::serialize () const virtual
Implements DeviceSampleSink.
Definition at line 203 of file bladerf1output.cpp.
References m_settings, and BladeRF1OutputSettings::serialize().
Referenced by Bladerf1Output::MsgReportBladerf1::MsgReportBladerf1().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void Bladerf1Output::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSink.
Definition at line 246 of file bladerf1output.cpp.
References Bladerf1Output::MsgConfigureBladerf1::create(), BladeRF1OutputSettings::m_centerFrequency, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     BladeRF1OutputSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureBladerf1* message = MsgConfigureBladerf1::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureBladerf1* messageToGUI = MsgConfigureBladerf1::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setMessageQueueToGUI()
virtual void Bladerf1Output::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSink.
Definition at line 108 of file bladerf1output.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSink::m_guiMessageQueue.
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void Bladerf1Output::setSampleRate (int sampleRate) inline virtual
For when the sink sample rate is set externally.
Implements DeviceSampleSink.
Definition at line 111 of file bladerf1output.h.
References getCenterFrequency(), handleMessage(), setCenterFrequency(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
start()
bool Bladerf1Output::start () virtual
Implements DeviceSampleSink.
Definition at line 138 of file bladerf1output.cpp.
References applySettings(), m_bladerfThread, m_dev, BladeRF1OutputSettings::m_log2Interp, m_running, DeviceSampleSink::m_sampleSourceFifo, m_settings, Bladerf1OutputThread::setLog2Interpolation(), Bladerf1OutputThread::startWork(), and stop().
Referenced by Bladerf1Output::MsgReportBladerf1::MsgReportBladerf1().
 {
 //  QMutexLocker mutexLocker(&m_mutex);
     if (!m_dev) {
         return false;
     }
     if (m_running) stop();
     m_bladerfThread = new Bladerf1OutputThread(m_dev, &m_sampleSourceFifo);
 //  mutexLocker.unlock();
     applySettings(m_settings, true);
     m_bladerfThread->setLog2Interpolation(m_settings.m_log2Interp);
     m_bladerfThread->startWork();
     qDebug("BladerfOutput::start: started");
     m_running = true;
     return true;
 }
stop()
void Bladerf1Output::stop () virtual
Implements DeviceSampleSink.
Definition at line 190 of file bladerf1output.cpp.
References m_bladerfThread, m_running, and Bladerf1OutputThread::stopWork().
Referenced by Bladerf1Output::MsgReportBladerf1::MsgReportBladerf1(), start(), and ~Bladerf1Output().
 {
 //  QMutexLocker mutexLocker(&m_mutex);
     if (m_bladerfThread != 0)
     {
         m_bladerfThread->stopWork();
         delete m_bladerfThread;
         m_bladerfThread = 0;
     }
     m_running = false;
 }
webapiFormatDeviceSettings()
void Bladerf1Output::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const BladeRF1OutputSettings & settings) private
Definition at line 561 of file bladerf1output.cpp.
References SWGSDRangel::SWGDeviceSettings::getBladeRf1OutputSettings(), SWGSDRangel::SWGBladeRF1OutputSettings::getReverseApiAddress(), BladeRF1OutputSettings::m_bandwidth, BladeRF1OutputSettings::m_centerFrequency, BladeRF1OutputSettings::m_devSampleRate, BladeRF1OutputSettings::m_log2Interp, BladeRF1OutputSettings::m_reverseAPIAddress, BladeRF1OutputSettings::m_reverseAPIDeviceIndex, BladeRF1OutputSettings::m_reverseAPIPort, BladeRF1OutputSettings::m_useReverseAPI, BladeRF1OutputSettings::m_vga1, BladeRF1OutputSettings::m_vga2, BladeRF1OutputSettings::m_xb200, BladeRF1OutputSettings::m_xb200Filter, BladeRF1OutputSettings::m_xb200Path, SWGSDRangel::SWGBladeRF1OutputSettings::setBandwidth(), SWGSDRangel::SWGBladeRF1OutputSettings::setCenterFrequency(), SWGSDRangel::SWGBladeRF1OutputSettings::setDevSampleRate(), SWGSDRangel::SWGBladeRF1OutputSettings::setLog2Interp(), SWGSDRangel::SWGBladeRF1OutputSettings::setReverseApiAddress(), SWGSDRangel::SWGBladeRF1OutputSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGBladeRF1OutputSettings::setReverseApiPort(), SWGSDRangel::SWGBladeRF1OutputSettings::setUseReverseApi(), SWGSDRangel::SWGBladeRF1OutputSettings::setVga1(), SWGSDRangel::SWGBladeRF1OutputSettings::setVga2(), SWGSDRangel::SWGBladeRF1OutputSettings::setXb200(), SWGSDRangel::SWGBladeRF1OutputSettings::setXb200Filter(), and SWGSDRangel::SWGBladeRF1OutputSettings::setXb200Path().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getBladeRf1OutputSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getBladeRf1OutputSettings()->setDevSampleRate(settings.m_devSampleRate);
     response.getBladeRf1OutputSettings()->setVga1(settings.m_vga1);
     response.getBladeRf1OutputSettings()->setVga2(settings.m_vga2);
     response.getBladeRf1OutputSettings()->setBandwidth(settings.m_bandwidth);
     response.getBladeRf1OutputSettings()->setLog2Interp(settings.m_log2Interp);
     response.getBladeRf1OutputSettings()->setXb200(settings.m_xb200 ? 1 : 0);
     response.getBladeRf1OutputSettings()->setXb200Path((int) settings.m_xb200Path);
     response.getBladeRf1OutputSettings()->setXb200Filter((int) settings.m_xb200Filter);
     response.getBladeRf1OutputSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getBladeRf1OutputSettings()->getReverseApiAddress()) {
         *response.getBladeRf1OutputSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getBladeRf1OutputSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getBladeRf1OutputSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getBladeRf1OutputSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReverseSendSettings()
void Bladerf1Output::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const BladeRF1OutputSettings & settings, bool force) private
Definition at line 675 of file bladerf1output.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), SWGSDRangel::SWGDeviceSettings::getBladeRf1OutputSettings(), DeviceAPI::getDeviceSetIndex(), BladeRF1OutputSettings::m_bandwidth, BladeRF1OutputSettings::m_centerFrequency, m_deviceAPI, BladeRF1OutputSettings::m_devSampleRate, BladeRF1OutputSettings::m_log2Interp, m_networkManager, m_networkRequest, BladeRF1OutputSettings::m_reverseAPIAddress, BladeRF1OutputSettings::m_reverseAPIDeviceIndex, BladeRF1OutputSettings::m_reverseAPIPort, BladeRF1OutputSettings::m_vga1, BladeRF1OutputSettings::m_vga2, BladeRF1OutputSettings::m_xb200, BladeRF1OutputSettings::m_xb200Filter, BladeRF1OutputSettings::m_xb200Path, SWGSDRangel::SWGBladeRF1OutputSettings::setBandwidth(), SWGSDRangel::SWGDeviceSettings::setBladeRf1OutputSettings(), SWGSDRangel::SWGBladeRF1OutputSettings::setCenterFrequency(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGBladeRF1OutputSettings::setDevSampleRate(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGBladeRF1OutputSettings::setLog2Interp(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGBladeRF1OutputSettings::setVga1(), SWGSDRangel::SWGBladeRF1OutputSettings::setVga2(), SWGSDRangel::SWGBladeRF1OutputSettings::setXb200(), SWGSDRangel::SWGBladeRF1OutputSettings::setXb200Filter(), and SWGSDRangel::SWGBladeRF1OutputSettings::setXb200Path().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(1); // single Tx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("BladeRF1"));
     swgDeviceSettings->setBladeRf1OutputSettings(new SWGSDRangel::SWGBladeRF1OutputSettings());
     SWGSDRangel::SWGBladeRF1OutputSettings *swgBladeRF1OutputSettings = swgDeviceSettings->getBladeRf1OutputSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgBladeRF1OutputSettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("devSampleRate") || force) {
         swgBladeRF1OutputSettings->setDevSampleRate(settings.m_devSampleRate);
     }
     if (deviceSettingsKeys.contains("vga1") || force) {
         swgBladeRF1OutputSettings->setVga1(settings.m_vga1);
     }
     if (deviceSettingsKeys.contains("vga2") || force) {
         swgBladeRF1OutputSettings->setVga2(settings.m_vga2);
     }
     if (deviceSettingsKeys.contains("bandwidth") || force) {
         swgBladeRF1OutputSettings->setBandwidth(settings.m_bandwidth);
     }
     if (deviceSettingsKeys.contains("log2Interp") || force) {
         swgBladeRF1OutputSettings->setLog2Interp(settings.m_log2Interp);
     }
     if (deviceSettingsKeys.contains("xb200") || force) {
         swgBladeRF1OutputSettings->setXb200(settings.m_xb200 ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("xb200Path") || force) {
         swgBladeRF1OutputSettings->setXb200Path((int) settings.m_xb200Path);
     }
     if (deviceSettingsKeys.contains("xb200Filter") || force) {
         swgBladeRF1OutputSettings->setXb200Filter((int) settings.m_xb200Filter);
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void Bladerf1Output::webapiReverseSendStartStop (bool start) private
Definition at line 732 of file bladerf1output.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, BladeRF1OutputSettings::m_reverseAPIAddress, BladeRF1OutputSettings::m_reverseAPIDeviceIndex, BladeRF1OutputSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(1); // single Tx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("BladeRF1"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int Bladerf1Output::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 656 of file bladerf1output.cpp.
References Bladerf1Output::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgStartStop *messagetoGui = MsgStartStop::create(run);
         m_guiMessageQueue->push(messagetoGui);
     }
     return 200;
 }
webapiRunGet()
int Bladerf1Output::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 647 of file bladerf1output.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int Bladerf1Output::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 550 of file bladerf1output.cpp.
References SWGSDRangel::SWGDeviceSettings::getBladeRf1OutputSettings(), SWGSDRangel::SWGBladeRF1OutputSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setBladeRf1OutputSettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setBladeRf1OutputSettings(new SWGSDRangel::SWGBladeRF1OutputSettings());
     response.getBladeRf1OutputSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int Bladerf1Output::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 585 of file bladerf1output.cpp.
References Bladerf1Output::MsgConfigureBladerf1::create(), SWGSDRangel::SWGBladeRF1OutputSettings::getBandwidth(), SWGSDRangel::SWGDeviceSettings::getBladeRf1OutputSettings(), SWGSDRangel::SWGBladeRF1OutputSettings::getCenterFrequency(), SWGSDRangel::SWGBladeRF1OutputSettings::getDevSampleRate(), SWGSDRangel::SWGBladeRF1OutputSettings::getLog2Interp(), SWGSDRangel::SWGBladeRF1OutputSettings::getReverseApiAddress(), SWGSDRangel::SWGBladeRF1OutputSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGBladeRF1OutputSettings::getReverseApiPort(), SWGSDRangel::SWGBladeRF1OutputSettings::getUseReverseApi(), SWGSDRangel::SWGBladeRF1OutputSettings::getVga1(), SWGSDRangel::SWGBladeRF1OutputSettings::getVga2(), SWGSDRangel::SWGBladeRF1OutputSettings::getXb200(), SWGSDRangel::SWGBladeRF1OutputSettings::getXb200Filter(), SWGSDRangel::SWGBladeRF1OutputSettings::getXb200Path(), BladeRF1OutputSettings::m_bandwidth, BladeRF1OutputSettings::m_centerFrequency, BladeRF1OutputSettings::m_devSampleRate, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, BladeRF1OutputSettings::m_log2Interp, BladeRF1OutputSettings::m_reverseAPIAddress, BladeRF1OutputSettings::m_reverseAPIDeviceIndex, BladeRF1OutputSettings::m_reverseAPIPort, m_settings, BladeRF1OutputSettings::m_useReverseAPI, BladeRF1OutputSettings::m_vga1, BladeRF1OutputSettings::m_vga2, BladeRF1OutputSettings::m_xb200, BladeRF1OutputSettings::m_xb200Filter, BladeRF1OutputSettings::m_xb200Path, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     BladeRF1OutputSettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getBladeRf1OutputSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("devSampleRate")) {
         settings.m_devSampleRate = response.getBladeRf1OutputSettings()->getDevSampleRate();
     }
     if (deviceSettingsKeys.contains("vga1")) {
         settings.m_vga1 = response.getBladeRf1OutputSettings()->getVga1();
     }
     if (deviceSettingsKeys.contains("vga2")) {
         settings.m_vga2 = response.getBladeRf1OutputSettings()->getVga2();
     }
     if (deviceSettingsKeys.contains("bandwidth")) {
         settings.m_bandwidth = response.getBladeRf1OutputSettings()->getBandwidth();
     }
     if (deviceSettingsKeys.contains("log2Interp")) {
         settings.m_log2Interp = response.getBladeRf1OutputSettings()->getLog2Interp();
     }
     if (deviceSettingsKeys.contains("xb200")) {
         settings.m_xb200 = response.getBladeRf1OutputSettings()->getXb200() == 0 ? 0 : 1;
     }
     if (deviceSettingsKeys.contains("xb200Path")) {
         settings.m_xb200Path = static_cast<bladerf_xb200_path>(response.getBladeRf1OutputSettings()->getXb200Path());
     }
     if (deviceSettingsKeys.contains("xb200Filter")) {
         settings.m_xb200Filter = static_cast<bladerf_xb200_filter>(response.getBladeRf1OutputSettings()->getXb200Filter());
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getBladeRf1OutputSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getBladeRf1OutputSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getBladeRf1OutputSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getBladeRf1OutputSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureBladerf1 *msg = MsgConfigureBladerf1::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureBladerf1 *msgToGUI = MsgConfigureBladerf1::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_bladerfThread
Bladerf1OutputThread* Bladerf1Output::m_bladerfThread private
Definition at line 141 of file bladerf1output.h.
Referenced by applySettings(), start(), and stop().
m_dev
struct bladerf* Bladerf1Output::m_dev private
Definition at line 140 of file bladerf1output.h.
Referenced by applySettings(), closeDevice(), openDevice(), and start().
m_deviceAPI
DeviceAPI* Bladerf1Output::m_deviceAPI private
Definition at line 137 of file bladerf1output.h.
Referenced by applySettings(), closeDevice(), handleMessage(), openDevice(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), webapiRunGet(), and ~Bladerf1Output().
m_deviceDescription
QString Bladerf1Output::m_deviceDescription private
Definition at line 142 of file bladerf1output.h.
Referenced by getDeviceDescription().
m_mutex
QMutex Bladerf1Output::m_mutex private
Definition at line 138 of file bladerf1output.h.
m_networkManager
QNetworkAccessManager* Bladerf1Output::m_networkManager private
Definition at line 145 of file bladerf1output.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~Bladerf1Output().
m_networkRequest
QNetworkRequest Bladerf1Output::m_networkRequest private
Definition at line 146 of file bladerf1output.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool Bladerf1Output::m_running private
Definition at line 144 of file bladerf1output.h.
Referenced by start(), stop(), and ~Bladerf1Output().
m_settings
BladeRF1OutputSettings Bladerf1Output::m_settings private
Definition at line 139 of file bladerf1output.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), openDevice(), serialize(), setCenterFrequency(), start(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_sharedParams
DeviceBladeRF1Params Bladerf1Output::m_sharedParams private
Definition at line 143 of file bladerf1output.h.
Referenced by applySettings(), closeDevice(), and openDevice().
The documentation for this class was generated from the following files:
plugins/samplesink/bladerf1output/bladerf1output.h
plugins/samplesink/bladerf1output/bladerf1output.cpp