SDRAngel: LoRaDemod Class Reference
LoRaDemod Class Reference
#include <lorademod.h>
Classes
class MsgConfigureChannelizer
class MsgConfigureLoRaDemod
Public Member Functions
LoRaDemod (DeviceAPI *deviceAPI)
virtual ~LoRaDemod ()
virtual void destroy ()
void setSpectrumSink (BasebandSampleSink *sampleSink)
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool pO)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &cmd)
Processing of a message. Returns true if message has actually been processed.
virtual void getIdentifier (QString &id)
virtual void getTitle (QString &title)
virtual qint64 getCenterFrequency () const
Applies to a default stream.
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual int getNbSinkStreams () const
virtual int getNbSourceStreams () const
virtual qint64 getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Public Member Functions inherited from ChannelAPI
ChannelAPI (const QString &name, StreamType streamType)
virtual ~ChannelAPI ()
virtual void setName (const QString &name)
virtual const QString & getName () const
virtual int webapiSettingsGet (SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &channelSettingsKeys, SWGSDRangel::SWGChannelSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGChannelReport &response, QString &errorMessage)
int getIndexInDeviceSet () const
void setIndexInDeviceSet (int indexInDeviceSet)
int getDeviceSetIndex () const
void setDeviceSetIndex (int deviceSetIndex)
DeviceAPI * getDeviceAPI ()
void setDeviceAPI (DeviceAPI *deviceAPI)
uint64_t getUID () const
StreamType getStreamType () const
Static Public Attributes
static const QString m_channelIdURI = "sdrangel.channel.lorademod"
static const QString m_channelId = "LoRaDemod"
Private Member Functions
int detect (Complex sample, Complex angle)
void dumpRaw (void)
short synch (short bin)
short toGray (short bin)
void interleave6 (char *inout, int size)
void hamming6 (char *inout, int size)
void prng6 (char *inout, int size)
Private Attributes
DeviceAPI * m_deviceAPI
ThreadedBasebandSampleSink * m_threadedChannelizer
DownChannelizer * m_channelizer
LoRaDemodSettings m_settings
Real m_Bandwidth
int m_sampleRate
int m_frequency
int m_chirp
int m_angle
int m_bin
int m_result
int m_count
int m_header
int m_time
short m_tune
sfft * loraFilter
sfft * negaFilter
float * mov
short * history
short * finetune
NCO m_nco
Interpolator m_interpolator
Real m_sampleDistanceRemain
BasebandSampleSink * m_sampleSink
SampleVector m_sampleBuffer
QMutex m_settingsMutex
Additional Inherited Members
Public Types inherited from ChannelAPI
enum StreamType { StreamSingleSink, StreamSingleSource, StreamMIMO }
< This is the same enum as in PluginInterface
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 44 of file lorademod.h.
Constructor & Destructor Documentation
LoRaDemod()
LoRaDemod::LoRaDemod (DeviceAPI * deviceAPI)
Definition at line 39 of file lorademod.cpp.
References DeviceAPI::addChannelSink(), DeviceAPI::addChannelSinkAPI(), LoRaDemodSettings::bandwidths, Interpolator::create(), finetune, history, LORA_SFFT_LEN, loraFilter, m_angle, m_Bandwidth, m_bin, m_channelId, m_channelizer, m_chirp, m_count, m_deviceAPI, m_frequency, m_header, m_interpolator, m_nco, m_result, m_sampleDistanceRemain, m_sampleRate, m_threadedChannelizer, m_time, m_tune, mov, negaFilter, and NCO::setFreq().
Referenced by LoRaDemod::MsgConfigureChannelizer::MsgConfigureChannelizer().
                                          :
         ChannelAPI(m_channelIdURI, ChannelAPI::StreamSingleSink),
         m_deviceAPI(deviceAPI),
         m_sampleSink(0),
         m_settingsMutex(QMutex::Recursive)
 {
     setObjectName(m_channelId);
     m_Bandwidth = LoRaDemodSettings::bandwidths[0];
     m_sampleRate = 96000;
     m_frequency = 0;
     m_nco.setFreq(m_frequency, m_sampleRate);
     m_interpolator.create(16, m_sampleRate, m_Bandwidth/1.9);
     m_sampleDistanceRemain = (Real)m_sampleRate / m_Bandwidth;
     m_chirp = 0;
     m_angle = 0;
     m_bin = 0;
     m_result = 0;
     m_count = 0;
     m_header = 0;
     m_time = 0;
     m_tune = 0;
     loraFilter = new sfft(LORA_SFFT_LEN);
     negaFilter = new sfft(LORA_SFFT_LEN);
     mov = new float[4*LORA_SFFT_LEN];
     history = new short[1024];
     finetune = new short[16];
     m_channelizer = new DownChannelizer(this);
     m_threadedChannelizer = new ThreadedBasebandSampleSink(m_channelizer);
     m_deviceAPI->addChannelSink(m_threadedChannelizer);
     m_deviceAPI->addChannelSinkAPI(this);
 }
~LoRaDemod()
LoRaDemod::~LoRaDemod () virtual
Definition at line 76 of file lorademod.cpp.
References finetune, history, loraFilter, m_channelizer, m_deviceAPI, m_threadedChannelizer, mov, negaFilter, DeviceAPI::removeChannelSink(), and DeviceAPI::removeChannelSinkAPI().
Referenced by LoRaDemod::MsgConfigureChannelizer::MsgConfigureChannelizer().
 {
     if (loraFilter)
         delete loraFilter;
     if (negaFilter)
         delete negaFilter;
     if (mov)
         delete [] mov;
     if (history)
         delete [] history;
     if (finetune)
         delete [] finetune;
     m_deviceAPI->removeChannelSinkAPI(this);
     m_deviceAPI->removeChannelSink(m_threadedChannelizer);
     delete m_threadedChannelizer;
     delete m_channelizer;
 }
Member Function Documentation
deserialize()
bool LoRaDemod::deserialize (const QByteArray & data) virtual
Implements ChannelAPI.
Definition at line 375 of file lorademod.cpp.
References LoRaDemod::MsgConfigureLoRaDemod::create(), LoRaDemodSettings::deserialize(), BasebandSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and LoRaDemodSettings::resetToDefaults().
Referenced by getCenterFrequency().
 {
     if (m_settings.deserialize(data))
     {
         MsgConfigureLoRaDemod *msg = MsgConfigureLoRaDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return true;
     }
     else
     {
         m_settings.resetToDefaults();
         MsgConfigureLoRaDemod *msg = MsgConfigureLoRaDemod::create(m_settings, true);
         m_inputMessageQueue.push(msg);
         return false;
     }
 }
destroy()
virtual void LoRaDemod::destroy () inline virtual
Implements ChannelAPI.
Definition at line 94 of file lorademod.h.
 { delete this; }
detect()
int LoRaDemod::detect (Complex sample, Complex angle) private
Definition at line 192 of file lorademod.cpp.
References DATA_BITS, sfft::fetch(), finetune, i, LORA_SFFT_LEN, LORA_SQUELCH, loraFilter, m_count, m_result, m_time, mov, negaFilter, sfft::run(), and synch().
Referenced by feed().
 {
     int p, q;
     short i, result, negresult, movpoint;
     float peak, negpeak, tfloat;
     float mag[LORA_SFFT_LEN];
     float rev[LORA_SFFT_LEN];
     loraFilter->run(c * a);
     negaFilter->run(c * conj(a));
     // process spectrum twice in FFTLEN
     if (++m_count & ((1 << DATA_BITS) - 1))
     {
         return m_result;
     }
     movpoint = 3 & (m_count >> DATA_BITS);
     loraFilter->fetch(mag);
     negaFilter->fetch(rev);
     peak = negpeak = 0.0f;
     result = negresult = 0;
     for (i = 0; i < LORA_SFFT_LEN; i++)
     {
         if (rev[i] > negpeak)
         {
             negpeak = rev[i];
             negresult = i;
         }
         tfloat = mov[i] + mov[LORA_SFFT_LEN + i] +mov[2 * LORA_SFFT_LEN + i]
                 + mov[3 * LORA_SFFT_LEN + i] + mag[i];
         if (tfloat > peak)
         {
             peak = tfloat;
             result = i;
         }
         mov[movpoint * LORA_SFFT_LEN + i] = mag[i];
     }
     p = (result - 1 + LORA_SFFT_LEN) & (LORA_SFFT_LEN -1);
     q = (result + 1) & (LORA_SFFT_LEN -1);
     finetune[15 & m_time] = (mag[p] > mag[q]) ? -1 : 1;
     if (peak < negpeak * LORA_SQUELCH)
     {
         result = -1;
     }
     result = synch(result);
     if (result >= 0)
     {
         m_result = result;
     }
     return m_result;
 }
dumpRaw()
void LoRaDemod::dumpRaw (void) private
Definition at line 95 of file lorademod.cpp.
References hamming6(), history, interleave6(), LORA_SFFT_LEN, m_time, m_tune, leansdr::max(), prng6(), and toGray().
Referenced by synch().
 {
     short bin, j, max;
     char text[256];
     max = m_time / 4 - 3;
     if (max > 140)
     {
         max = 140; // about 2 symbols to each char
     }
     for ( j=0; j < max; j++)
     {
         bin = (history[(j + 1)  * 4] + m_tune ) & (LORA_SFFT_LEN - 1);
         text[j] = toGray(bin >> 1);
     }
     prng6(text, max);
     // First block is always 8 symbols
     interleave6(text, 6);
     interleave6(&text[8], max);
     hamming6(text, 6);
     hamming6(&text[8], max);
     for ( j=0; j < max / 2; j++)
     {
         text[j] = (text[j * 2 + 1] << 4) | (0xf & text[j * 2 + 0]);
         if ((text[j] < 32 )||( text[j] > 126))
         {
             text[j] = 0x5f;
         }
     }
     text[3] = text[2];
     text[2] = text[1];
     text[1] = text[0];
     text[j] = 0;
     printf("%s\n", &text[1]);
 }
feed()
void LoRaDemod::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool pO) virtual
Implements BasebandSampleSink.
Definition at line 255 of file lorademod.cpp.
References cos(), Interpolator::decimate(), detect(), BasebandSampleSink::feed(), LORA_SFFT_LEN, m_angle, m_Bandwidth, m_bin, m_chirp, m_interpolator, m_nco, M_PI, m_sampleBuffer, m_sampleDistanceRemain, m_sampleRate, m_sampleSink, m_settingsMutex, NCO::nextIQ(), SDR_RX_SCALEF, sin(), and SPREADFACTOR.
Referenced by setSpectrumSink().
 {
     (void) pO;
     int newangle;
     Complex ci;
     m_sampleBuffer.clear();
     m_settingsMutex.lock();
     for(SampleVector::const_iterator it = begin; it < end; ++it)
     {
         Complex c(it->real() / SDR_RX_SCALEF, it->imag() / SDR_RX_SCALEF);
         c *= m_nco.nextIQ();
         if(m_interpolator.decimate(&m_sampleDistanceRemain, c, &ci))
         {
             m_chirp = (m_chirp + 1) & (SPREADFACTOR - 1);
                         m_angle = (m_angle + m_chirp) & (SPREADFACTOR - 1);
             Complex cangle(cos(M_PI*2*m_angle/SPREADFACTOR),-sin(M_PI*2*m_angle/SPREADFACTOR));
             newangle = detect(ci, cangle);
             m_bin = (m_bin + newangle) & (LORA_SFFT_LEN - 1);
             Complex nangle(cos(M_PI*2*m_bin/LORA_SFFT_LEN),sin(M_PI*2*m_bin/LORA_SFFT_LEN));
             m_sampleBuffer.push_back(Sample(nangle.real() * 100, nangle.imag() * 100));
             m_sampleDistanceRemain += (Real)m_sampleRate / m_Bandwidth;
         }
     }
     if(m_sampleSink != 0)
     {
         m_sampleSink->feed(m_sampleBuffer.begin(), m_sampleBuffer.end(), false);
     }
     m_settingsMutex.unlock();
 }
getCenterFrequency()
virtual qint64 LoRaDemod::getCenterFrequency () const inline virtual
Applies to a default stream.
Implements ChannelAPI.
Definition at line 104 of file lorademod.h.
References deserialize(), and serialize().
 { return 0; }
getIdentifier()
virtual void LoRaDemod::getIdentifier (QString & id) inline virtual
Implements ChannelAPI.
Definition at line 102 of file lorademod.h.
 { id = objectName(); }
getNbSinkStreams()
virtual int LoRaDemod::getNbSinkStreams () const inline virtual
Implements ChannelAPI.
Definition at line 109 of file lorademod.h.
 { return 1; }
getNbSourceStreams()
virtual int LoRaDemod::getNbSourceStreams () const inline virtual
Implements ChannelAPI.
Definition at line 110 of file lorademod.h.
 { return 0; }
getStreamCenterFrequency()
virtual qint64 LoRaDemod::getStreamCenterFrequency (int streamIndex, bool sinkElseSource) const inline virtual
Implements ChannelAPI.
Definition at line 112 of file lorademod.h.
     {
         (void) streamIndex;
         (void) sinkElseSource;
         return 0;
     }
getTitle()
virtual void LoRaDemod::getTitle (QString & title) inline virtual
Implements ChannelAPI.
Definition at line 103 of file lorademod.h.
References LoRaDemod::MsgConfigureLoRaDemod::m_settings, and LoRaDemodSettings::m_title.
 { title = m_settings.m_title; }
hamming6()
void LoRaDemod::hamming6 (char * inout, int size) private
Definition at line 42 of file lorabits.h.
References i.
Referenced by dumpRaw().
 {
     int i;
     for (i = 0; i < size; i++) {
         c[i] = ((c[i] & 1)<<3) | ((c[i] & 2)<<0) | ((c[i] & 4)>>0) | ((c[i] & 8)>>3);
         i++;
         c[i] = ((c[i] & 1)<<2) | ((c[i] & 2)<<2) | ((c[i] & 4)>>1) | ((c[i] & 8)>>3);
         i++;
         c[i] = ((c[i] &32)>>2) | ((c[i] & 2)<<1) | ((c[i] & 4)>>1) | ((c[i] & 8)>>3);
         i++;
         c[i] = ((c[i] & 1)<<3) | ((c[i] & 2)<<1) | ((c[i] & 4)>>1) | ((c[i] & 8)>>3);
         i++;
         c[i] = ((c[i] & 1)<<3) | ((c[i] & 2)<<1) | ((c[i] & 4)>>1) | ((c[i] &16)>>4);
         i++;
         c[i] = ((c[i] & 1)<<3) | ((c[i] & 2)<<1) | ((c[i] & 4)>>2) | ((c[i] & 8)>>2);
     }
     c[i] = 0;
 }
handleMessage()
bool LoRaDemod::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 300 of file lorademod.cpp.
References LoRaDemodSettings::bandwidths, DownChannelizer::configure(), Interpolator::create(), LoRaDemod::MsgConfigureChannelizer::getCenterFrequency(), DownChannelizer::MsgChannelizerNotification::getFrequencyOffset(), BasebandSampleSink::getInputMessageQueue(), DownChannelizer::MsgChannelizerNotification::getSampleRate(), LoRaDemod::MsgConfigureChannelizer::getSampleRate(), LoRaDemod::MsgConfigureLoRaDemod::getSettings(), BasebandSampleSink::handleMessage(), m_Bandwidth, LoRaDemodSettings::m_bandwidthIndex, m_channelizer, m_interpolator, m_nco, m_sampleDistanceRemain, m_sampleRate, m_sampleSink, m_settings, m_settingsMutex, Message::match(), and NCO::setFreq().
Referenced by setSpectrumSink().
 {
     qDebug() << "LoRaDemod::handleMessage";
     if (DownChannelizer::MsgChannelizerNotification::match(cmd))
     {
         DownChannelizer::MsgChannelizerNotification& notif = (DownChannelizer::MsgChannelizerNotification&) cmd;
         m_settingsMutex.lock();
         m_sampleRate = notif.getSampleRate();
         m_nco.setFreq(-notif.getFrequencyOffset(), m_sampleRate);
         m_interpolator.create(16, m_sampleRate, m_Bandwidth/1.9);
         m_sampleDistanceRemain = m_sampleRate / m_Bandwidth;
         m_settingsMutex.unlock();
         qDebug() << "LoRaDemod::handleMessage: MsgChannelizerNotification: m_sampleRate: " << m_sampleRate
                 << " frequencyOffset: " << notif.getFrequencyOffset();
         return true;
     }
     else if (MsgConfigureChannelizer::match(cmd))
     {
         MsgConfigureChannelizer& cfg = (MsgConfigureChannelizer&) cmd;
         m_channelizer->configure(m_channelizer->getInputMessageQueue(),
             cfg.getSampleRate(),
             cfg.getCenterFrequency());
         qDebug() << "LoRaDemod::handleMessage: MsgConfigureChannelizer: sampleRate: " << cfg.getSampleRate()
                 << " centerFrequency: " << cfg.getCenterFrequency();
         return true;
     }
     else if (MsgConfigureLoRaDemod::match(cmd))
     {
         MsgConfigureLoRaDemod& cfg = (MsgConfigureLoRaDemod&) cmd;
         m_settingsMutex.lock();
         LoRaDemodSettings settings = cfg.getSettings();
         m_Bandwidth = LoRaDemodSettings::bandwidths[settings.m_bandwidthIndex];
         m_interpolator.create(16, m_sampleRate, m_Bandwidth/1.9);
         m_settingsMutex.unlock();
         m_settings = settings;
         qDebug() << "LoRaDemod::handleMessage: MsgConfigureLoRaDemod: m_Bandwidth: " << m_Bandwidth;
         return true;
     }
     else if (DSPSignalNotification::match(cmd))
     {
         return true;
     }
     else
     {
         if(m_sampleSink != 0)
         {
              return m_sampleSink->handleMessage(cmd);
         }
         else
         {
             return false;
         }
     }
 }
interleave6()
void LoRaDemod::interleave6 (char * inout, int size) private
Definition at line 14 of file lorabits.h.
References i.
Referenced by dumpRaw().
 {
     int i, j;
     char in[6 * 2];
     short s;
     for (j = 0; j < size; j+=6) {
         for (i = 0; i < 6; i++)
             in[i] = in[i + 6] = inout[i + j];
         // top bits are swapped
         for (i = 0; i < 6; i++) {
             s = (32 & in[2 + i]) | (16 & in[1 + i]) | (8 & in[3 + i])
                 | (4 & in[4 + i]) | (2 & in[5 + i]) | (1 & in[6 + i]);
             // bits are also  rotated
             s = (s << 3) | (s >> 3);
             s &= 63;
             s = (s >> i) | (s << (6 - i));
             inout[i + j] = s & 63;
         }
     }
 }
prng6()
void LoRaDemod::prng6 (char * inout, int size) private
Definition at line 63 of file lorabits.h.
References i.
Referenced by dumpRaw().
 {
     const char otp[] = {
     //explicit mode
     "cOGGg7CM2=b5a?<`i;T2of5jDAB=2DoQ9ko?h_RLQR4@Z\\`9jY\\PX89lHX8h_R]c_^@OB<0`W08ik?Mg>dQZf3kn5Je5R=R4h[<Ph90HHh9j;h:mS^?f:lQ:GG;nU:b?WFU20Lf4@A?`hYJMnW\\QZ\\AMIZ<h:jQk[PP<`6[Z"
 #if 0
     // implicit mode (offset 2 symbols)
     "5^ZSm0=cOGMgUB=bNcb<@a^T;_f=6DEB]2ImPIKg:j]RlYT4YZ<`9hZ\\PPb;@8X8i]Zmc_6B52\\8oUPHIcBOc>dY?d9[n5Lg]b]R8hR<0`T008h9c9QJm[c?a:lQEGa;nU=b_WfUV2?V4@c=8h9B9njlQZDC@9Z<Q8\\iiX\\Rb6k:iY"
 #endif
     };
     int i, maxchars;
     maxchars = sizeof( otp );
     if (size < maxchars)
         maxchars = size;
     for (i = 0; i < maxchars; i++)
         inout[i] ^= (otp[i] - 48);
 }
serialize()
QByteArray LoRaDemod::serialize () const virtual
Implements ChannelAPI.
Definition at line 370 of file lorademod.cpp.
References m_settings, and LoRaDemodSettings::serialize().
Referenced by getCenterFrequency().
 {
     return m_settings.serialize();
 }
setSpectrumSink()
void LoRaDemod::setSpectrumSink (BasebandSampleSink * sampleSink) inline
Definition at line 95 of file lorademod.h.
References feed(), handleMessage(), m_sampleSink, start(), and stop().
Referenced by LoRaDemodGUI::LoRaDemodGUI().
 { m_sampleSink = sampleSink; }
start()
void LoRaDemod::start () virtual
Implements BasebandSampleSink.
Definition at line 292 of file lorademod.cpp.
Referenced by setSpectrumSink().
 {
 }
stop()
void LoRaDemod::stop () virtual
Implements BasebandSampleSink.
Definition at line 296 of file lorademod.cpp.
Referenced by setSpectrumSink().
 {
 }
synch()
short LoRaDemod::synch (short bin) private
Definition at line 138 of file lorademod.cpp.
References dumpRaw(), finetune, history, i, LORA_SFFT_LEN, m_time, and m_tune.
Referenced by detect().
 {
     short i, j;
     if (bin < 0)
     {
         if (m_time > 70)
         {
             dumpRaw();
         }
         m_time = 0;
         return -1;
     }
     history[m_time] = bin;
     if (m_time > 12)
     {
         if (bin == history[m_time - 6])
         {
             if (bin == history[m_time - 12])
             {
                 m_tune = LORA_SFFT_LEN - bin;
                 j = 0;
                 for (i=0; i<12; i++)
                 {
                     j += finetune[15 & (m_time - i)];
                 }
                 if (j < 0)
                 {
                     m_tune += 1;
                 }
                 m_tune &= (LORA_SFFT_LEN - 1);
                 m_time = 0;
                 return -1;
             }
         }
     }
     m_time++;
     m_time &= 1023;
     if (m_time & 3)
     {
         return -1;
     }
     return (bin + m_tune) & (LORA_SFFT_LEN - 1);
 }
toGray()
short LoRaDemod::toGray (short bin) private
Definition at line 36 of file lorabits.h.
Referenced by dumpRaw().
 {
         return (num >> 1) ^ num;
 }
Member Data Documentation
finetune
short* LoRaDemod::finetune private
Definition at line 152 of file lorademod.h.
Referenced by detect(), LoRaDemod(), synch(), and ~LoRaDemod().
history
short* LoRaDemod::history private
Definition at line 151 of file lorademod.h.
Referenced by dumpRaw(), LoRaDemod(), synch(), and ~LoRaDemod().
loraFilter
sfft* LoRaDemod::loraFilter private
Definition at line 148 of file lorademod.h.
Referenced by detect(), LoRaDemod(), and ~LoRaDemod().
m_angle
int LoRaDemod::m_angle private
Definition at line 140 of file lorademod.h.
Referenced by feed(), and LoRaDemod().
m_Bandwidth
Real LoRaDemod::m_Bandwidth private
Definition at line 136 of file lorademod.h.
Referenced by feed(), handleMessage(), and LoRaDemod().
m_bin
int LoRaDemod::m_bin private
Definition at line 141 of file lorademod.h.
Referenced by feed(), and LoRaDemod().
m_channelId
const QString LoRaDemod::m_channelId = "LoRaDemod" static
Definition at line 120 of file lorademod.h.
Referenced by LoRaPlugin::initPlugin(), and LoRaDemod().
m_channelIdURI
const QString LoRaDemod::m_channelIdURI = "sdrangel.channel.lorademod" static
Definition at line 119 of file lorademod.h.
Referenced by LoRaPlugin::initPlugin(), and LoRaDemodGUI::LoRaDemodGUI().
m_channelizer
DownChannelizer* LoRaDemod::m_channelizer private
Definition at line 133 of file lorademod.h.
Referenced by handleMessage(), LoRaDemod(), and ~LoRaDemod().
m_chirp
int LoRaDemod::m_chirp private
Definition at line 139 of file lorademod.h.
Referenced by feed(), and LoRaDemod().
m_count
int LoRaDemod::m_count private
Definition at line 143 of file lorademod.h.
Referenced by detect(), and LoRaDemod().
m_deviceAPI
DeviceAPI* LoRaDemod::m_deviceAPI private
Definition at line 131 of file lorademod.h.
Referenced by LoRaDemod(), and ~LoRaDemod().
m_frequency
int LoRaDemod::m_frequency private
Definition at line 138 of file lorademod.h.
Referenced by LoRaDemod().
m_header
int LoRaDemod::m_header private
Definition at line 144 of file lorademod.h.
Referenced by LoRaDemod().
m_interpolator
Interpolator LoRaDemod::m_interpolator private
Definition at line 155 of file lorademod.h.
Referenced by feed(), handleMessage(), and LoRaDemod().
m_nco
NCO LoRaDemod::m_nco private
Definition at line 154 of file lorademod.h.
Referenced by feed(), handleMessage(), and LoRaDemod().
m_result
int LoRaDemod::m_result private
Definition at line 142 of file lorademod.h.
Referenced by detect(), and LoRaDemod().
m_sampleBuffer
SampleVector LoRaDemod::m_sampleBuffer private
Definition at line 159 of file lorademod.h.
Referenced by feed().
m_sampleDistanceRemain
Real LoRaDemod::m_sampleDistanceRemain private
Definition at line 156 of file lorademod.h.
Referenced by feed(), handleMessage(), and LoRaDemod().
m_sampleRate
int LoRaDemod::m_sampleRate private
Definition at line 137 of file lorademod.h.
Referenced by feed(), LoRaDemod::MsgConfigureChannelizer::getSampleRate(), handleMessage(), and LoRaDemod().
m_sampleSink
BasebandSampleSink* LoRaDemod::m_sampleSink private
Definition at line 158 of file lorademod.h.
Referenced by feed(), handleMessage(), and setSpectrumSink().
m_settings
LoRaDemodSettings LoRaDemod::m_settings private
Definition at line 134 of file lorademod.h.
Referenced by deserialize(), handleMessage(), and serialize().
m_settingsMutex
QMutex LoRaDemod::m_settingsMutex private
Definition at line 160 of file lorademod.h.
Referenced by feed(), and handleMessage().
m_threadedChannelizer
ThreadedBasebandSampleSink* LoRaDemod::m_threadedChannelizer private
Definition at line 132 of file lorademod.h.
Referenced by LoRaDemod(), and ~LoRaDemod().
m_time
int LoRaDemod::m_time private
Definition at line 145 of file lorademod.h.
Referenced by detect(), dumpRaw(), LoRaDemod(), and synch().
m_tune
short LoRaDemod::m_tune private
Definition at line 146 of file lorademod.h.
Referenced by dumpRaw(), LoRaDemod(), and synch().
mov
float* LoRaDemod::mov private
Definition at line 150 of file lorademod.h.
Referenced by detect(), LoRaDemod(), and ~LoRaDemod().
negaFilter
sfft* LoRaDemod::negaFilter private
Definition at line 149 of file lorademod.h.
Referenced by detect(), LoRaDemod(), and ~LoRaDemod().
The documentation for this class was generated from the following files:
plugins/channelrx/demodlora/lorademod.h
plugins/channelrx/demodlora/lorabits.h
plugins/channelrx/demodlora/lorademod.cpp