SDRAngel: DeviceHackRFShared::MsgSynchronizeFrequency Class Reference
DeviceHackRFShared::MsgSynchronizeFrequency Class Reference
#include <devicehackrfshared.h>
Public Member Functions
uint64_t getFrequency () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgSynchronizeFrequency * create (uint64_t frequency)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgSynchronizeFrequency (uint64_t frequency)
Private Attributes
uint64_t m_frequency
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 29 of file devicehackrfshared.h.
Constructor & Destructor Documentation
MsgSynchronizeFrequency()
DeviceHackRFShared::MsgSynchronizeFrequency::MsgSynchronizeFrequency (uint64_t frequency) inline private
Definition at line 44 of file devicehackrfshared.h.
                                                     :
             Message(),
             m_frequency(frequency)
         { }
Member Function Documentation
create()
static MsgSynchronizeFrequency* DeviceHackRFShared::MsgSynchronizeFrequency::create (uint64_t frequency) inline static
Definition at line 36 of file devicehackrfshared.h.
Referenced by HackRFOutput::applySettings(), and HackRFInput::applySettings().
         {
             return new MsgSynchronizeFrequency(frequency);
         }
getFrequency()
uint64_t DeviceHackRFShared::MsgSynchronizeFrequency::getFrequency () const inline
Definition at line 34 of file devicehackrfshared.h.
Referenced by HackRFOutput::handleMessage(), and HackRFInput::handleMessage().
 { return m_frequency; }
Member Data Documentation
m_frequency
uint64_t DeviceHackRFShared::MsgSynchronizeFrequency::m_frequency private
Definition at line 42 of file devicehackrfshared.h.
The documentation for this class was generated from the following file:
devices/hackrf/devicehackrfshared.h