SDRAngel: FFTEngine Class Reference
FFTEngine Class Reference abstract
#include <fftengine.h>
Public Member Functions
virtual ~FFTEngine ()
virtual void configure (int n, bool inverse)=0
virtual void transform ()=0
virtual Complex * in ()=0
virtual Complex * out ()=0
Static Public Member Functions
static FFTEngine * create ()
Detailed Description
Definition at line 7 of file fftengine.h.
Constructor & Destructor Documentation
~FFTEngine()
FFTEngine::~FFTEngine () virtual
Definition at line 9 of file fftengine.cpp.
 {
 }
Member Function Documentation
configure()
virtual void FFTEngine::configure (int n, bool inverse) pure virtual
Implemented in FFTWEngine, and KissEngine.
Referenced by SpectrumVis::handleConfigure().
create()
FFTEngine * FFTEngine::create () static
Definition at line 13 of file fftengine.cpp.
 {
 #ifdef USE_FFTW
     qDebug("FFTEngine::create: using FFTW engine");
     return new FFTWEngine;
 #elif USE_KISSFFT
     qDebug("FFTEngine::create: using KissFFT engine");
     return new KissEngine;
 #else // USE_KISSFFT
     qCritical("FFTEngine::create: no engine built");
     return 0;
 #endif
 }
in()
virtual Complex* FFTEngine::in () pure virtual
Implemented in FFTWEngine, and KissEngine.
Referenced by SpectrumVis::feed().
out()
virtual Complex* FFTEngine::out () pure virtual
Implemented in FFTWEngine, and KissEngine.
Referenced by SpectrumVis::feed().
transform()
virtual void FFTEngine::transform () pure virtual
Implemented in FFTWEngine, and KissEngine.
Referenced by SpectrumVis::feed().
The documentation for this class was generated from the following files:
sdrbase/dsp/fftengine.h
sdrbase/dsp/fftengine.cpp