SDRAngel: SWGSDRangel::SWGLocalOutputReport Class Reference
SWGSDRangel::SWGLocalOutputReport Class Reference
#include <SWGLocalOutputReport.h>
Public Member Functions
SWGLocalOutputReport ()
SWGLocalOutputReport (QString *json)
virtual ~SWGLocalOutputReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGLocalOutputReport * fromJson (QString &jsonString) override
qint32 getCenterFrequency ()
void setCenterFrequency (qint32 center_frequency)
qint32 getSampleRate ()
void setSampleRate (qint32 sample_rate)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 center_frequency
bool m_center_frequency_isSet
qint32 sample_rate
bool m_sample_rate_isSet
Detailed Description
Definition at line 31 of file SWGLocalOutputReport.h.
Constructor & Destructor Documentation
SWGLocalOutputReport() [1/2]
SWGSDRangel::SWGLocalOutputReport::SWGLocalOutputReport ()
Definition at line 30 of file SWGLocalOutputReport.cpp.
References center_frequency, m_center_frequency_isSet, m_sample_rate_isSet, and sample_rate.
{
     center_frequency = 0;
     m_center_frequency_isSet = false;
     sample_rate = 0;
     m_sample_rate_isSet = false;
 }
SWGLocalOutputReport() [2/2]
SWGSDRangel::SWGLocalOutputReport::SWGLocalOutputReport (QString * json)
Definition at line 25 of file SWGLocalOutputReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGLocalOutputReport()
SWGSDRangel::SWGLocalOutputReport::~SWGLocalOutputReport () virtual
Definition at line 37 of file SWGLocalOutputReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGLocalOutputReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 73 of file SWGLocalOutputReport.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGLocalOutputReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 84 of file SWGLocalOutputReport.cpp.
References center_frequency, m_center_frequency_isSet, m_sample_rate_isSet, and sample_rate.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_center_frequency_isSet){
         obj->insert("centerFrequency", QJsonValue(center_frequency));
     }
     if(m_sample_rate_isSet){
         obj->insert("sampleRate", QJsonValue(sample_rate));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGLocalOutputReport::cleanup ()
Definition at line 50 of file SWGLocalOutputReport.cpp.
Referenced by ~SWGLocalOutputReport().
{
 }
fromJson()
SWGLocalOutputReport * SWGSDRangel::SWGLocalOutputReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 56 of file SWGLocalOutputReport.cpp.
References fromJsonObject().
Referenced by SWGLocalOutputReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGLocalOutputReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 65 of file SWGLocalOutputReport.cpp.
References center_frequency, sample_rate, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&center_frequency, pJson["centerFrequency"], "qint32", "");
     ::SWGSDRangel::setValue(&sample_rate, pJson["sampleRate"], "qint32", "");
 }
getCenterFrequency()
qint32 SWGSDRangel::SWGLocalOutputReport::getCenterFrequency ()
Definition at line 97 of file SWGLocalOutputReport.cpp.
References center_frequency.
{
     return center_frequency;
 }
getSampleRate()
qint32 SWGSDRangel::SWGLocalOutputReport::getSampleRate ()
Definition at line 107 of file SWGLocalOutputReport.cpp.
References sample_rate.
{
     return sample_rate;
 }
init()
void SWGSDRangel::SWGLocalOutputReport::init ()
Definition at line 42 of file SWGLocalOutputReport.cpp.
References center_frequency, m_center_frequency_isSet, m_sample_rate_isSet, and sample_rate.
Referenced by SWGLocalOutputReport(), and LocalOutput::webapiReportGet().
{
     center_frequency = 0;
     m_center_frequency_isSet = false;
     sample_rate = 0;
     m_sample_rate_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGLocalOutputReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 118 of file SWGLocalOutputReport.cpp.
References m_center_frequency_isSet, and m_sample_rate_isSet.
Referenced by SWGSDRangel::SWGDeviceReport::asJsonObject(), and SWGSDRangel::SWGDeviceReport::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(m_center_frequency_isSet){ isObjectUpdated = true; break;}
         if(m_sample_rate_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setCenterFrequency()
void SWGSDRangel::SWGLocalOutputReport::setCenterFrequency (qint32 center_frequency)
Definition at line 101 of file SWGLocalOutputReport.cpp.
References center_frequency, and m_center_frequency_isSet.
Referenced by LocalOutput::webapiFormatDeviceReport().
{
     this->center_frequency = center_frequency;
     this->m_center_frequency_isSet = true;
 }
setSampleRate()
void SWGSDRangel::SWGLocalOutputReport::setSampleRate (qint32 sample_rate)
Definition at line 111 of file SWGLocalOutputReport.cpp.
References m_sample_rate_isSet, and sample_rate.
Referenced by LocalOutput::webapiFormatDeviceReport().
{
     this->sample_rate = sample_rate;
     this->m_sample_rate_isSet = true;
 }
Member Data Documentation
center_frequency
qint32 SWGSDRangel::SWGLocalOutputReport::center_frequency private
Definition at line 54 of file SWGLocalOutputReport.h.
Referenced by asJsonObject(), fromJsonObject(), getCenterFrequency(), init(), setCenterFrequency(), and SWGLocalOutputReport().
m_center_frequency_isSet
bool SWGSDRangel::SWGLocalOutputReport::m_center_frequency_isSet private
Definition at line 55 of file SWGLocalOutputReport.h.
Referenced by asJsonObject(), init(), isSet(), setCenterFrequency(), and SWGLocalOutputReport().
m_sample_rate_isSet
bool SWGSDRangel::SWGLocalOutputReport::m_sample_rate_isSet private
Definition at line 58 of file SWGLocalOutputReport.h.
Referenced by asJsonObject(), init(), isSet(), setSampleRate(), and SWGLocalOutputReport().
sample_rate
qint32 SWGSDRangel::SWGLocalOutputReport::sample_rate private
Definition at line 57 of file SWGLocalOutputReport.h.
Referenced by asJsonObject(), fromJsonObject(), getSampleRate(), init(), setSampleRate(), and SWGLocalOutputReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGLocalOutputReport.h
swagger/sdrangel/code/qt5/client/SWGLocalOutputReport.cpp