SDRAngel: RTLSDRInput::MsgStartStop Class Reference
RTLSDRInput::MsgStartStop Class Reference
#include <rtlsdrinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 81 of file rtlsdrinput.h.
Constructor & Destructor Documentation
MsgStartStop()
RTLSDRInput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 94 of file rtlsdrinput.h.
References RTLSDRInput::deserialize(), RTLSDRInput::destroy(), RTLSDRInput::init(), RTLSDRInput::RTLSDRInput(), RTLSDRInput::serialize(), RTLSDRInput::start(), RTLSDRInput::stop(), and RTLSDRInput::~RTLSDRInput().
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* RTLSDRInput::MsgStartStop::create (bool startStop) inline static
Definition at line 87 of file rtlsdrinput.h.
Referenced by RTLSDRGui::on_startStop_toggled(), and RTLSDRInput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool RTLSDRInput::MsgStartStop::getStartStop () const inline
Definition at line 85 of file rtlsdrinput.h.
Referenced by RTLSDRGui::handleMessage(), and RTLSDRInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool RTLSDRInput::MsgStartStop::m_startStop protected
Definition at line 92 of file rtlsdrinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/rtlsdr/rtlsdrinput.h