SDRAngel: ChannelAnalyzer::MsgReportChannelSampleRateChanged Class Reference
ChannelAnalyzer::MsgReportChannelSampleRateChanged Class Reference
#include <chanalyzer.h>
Static Public Member Functions
static MsgReportChannelSampleRateChanged * create ()
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportChannelSampleRateChanged ()
Additional Inherited Members
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 92 of file chanalyzer.h.
Constructor & Destructor Documentation
MsgReportChannelSampleRateChanged()
ChannelAnalyzer::MsgReportChannelSampleRateChanged::MsgReportChannelSampleRateChanged () inline private
Definition at line 104 of file chanalyzer.h.
References ChannelAnalyzer::ChannelAnalyzer(), and ChannelAnalyzer::~ChannelAnalyzer().
                                             :
             Message()
         { }
Member Function Documentation
create()
static MsgReportChannelSampleRateChanged* ChannelAnalyzer::MsgReportChannelSampleRateChanged::create () inline static
Definition at line 97 of file chanalyzer.h.
Referenced by ChannelAnalyzer::handleMessage().
         {
             return new MsgReportChannelSampleRateChanged();
         }
The documentation for this class was generated from the following file:
plugins/channelrx/chanalyzer/chanalyzer.h