SDRAngel: qrtplib::RTCPSRPacket Class Reference
qrtplib::RTCPSRPacket Class Reference
#include <rtcpsrpacket.h>
Public Member Functions
RTCPSRPacket (uint8_t *data, std::size_t datalength)
~RTCPSRPacket ()
uint32_t GetSenderSSRC () const
RTPNTPTime GetNTPTimestamp () const
uint32_t GetRTPTimestamp () const
uint32_t GetSenderPacketCount () const
uint32_t GetSenderOctetCount () const
int GetReceptionReportCount () const
uint32_t GetSSRC (int index) const
uint8_t GetFractionLost (int index) const
int32_t GetLostPacketCount (int index) const
uint32_t GetExtendedHighestSequenceNumber (int index) const
uint32_t GetJitter (int index) const
uint32_t GetLSR (int index) const
uint32_t GetDLSR (int index) const
Public Member Functions inherited from qrtplib::RTCPPacket
virtual ~RTCPPacket ()
bool IsKnownFormat () const
PacketType GetPacketType () const
uint8_t * GetPacketData ()
std::size_t GetPacketLength () const
Private Member Functions
RTCPReceiverReport * GotoReport (int index) const
Private Attributes
RTPEndian m_endian
Additional Inherited Members
Public Types inherited from qrtplib::RTCPPacket
enum PacketType {
SR, RR, SDES, BYE,
APP, Unknown
}
Protected Member Functions inherited from qrtplib::RTCPPacket
RTCPPacket (PacketType t, uint8_t *d, std::size_t dlen)
Protected Attributes inherited from qrtplib::RTCPPacket
uint8_t * data
std::size_t datalen
bool knownformat
Detailed Description
Describes an RTCP sender report packet.
Definition at line 55 of file rtcpsrpacket.h.
Constructor & Destructor Documentation
RTCPSRPacket()
qrtplib::RTCPSRPacket::RTCPSRPacket (uint8_t * data, std::size_t datalength)
Creates an instance based on the data in data with length datalen. Creates an instance based on the data in data with length datalen. Since the data pointer is referenced inside the class (no copy of the data is made) one must make sure that the memory it points to is valid as long as the class instance exists.
Definition at line 38 of file rtcpsrpacket.cpp.
References qrtplib::RTCPCommonHeader::count, qrtplib::RTCPPacket::knownformat, and qrtplib::RTCPCommonHeader::padding.
                                                               :
         RTCPPacket(SR, data, datalength)
 {
     knownformat = false;
     RTCPCommonHeader *hdr;
     std::size_t len = datalength;
     std::size_t expectedlength;
     hdr = (RTCPCommonHeader *) data;
     if (hdr->padding)
     {
         uint8_t padcount = data[datalength - 1];
         if ((padcount & 0x03) != 0) // not a multiple of four! (see rfc 3550 p 37)
             return;
         if (((std::size_t) padcount) >= len)
             return;
         len -= (std::size_t) padcount;
     }
     expectedlength = sizeof(RTCPCommonHeader) + sizeof(uint32_t) + sizeof(RTCPSenderReport);
     expectedlength += sizeof(RTCPReceiverReport) * ((int) hdr->count);
     if (expectedlength != len)
         return;
     knownformat = true;
 }
~RTCPSRPacket()
qrtplib::RTCPSRPacket::~RTCPSRPacket () inline
Definition at line 64 of file rtcpsrpacket.h.
     {
     }
Member Function Documentation
GetDLSR()
uint32_t qrtplib::RTCPSRPacket::GetDLSR (int index) const inline
Returns the DLSR field of the reception report block described by index which may have a value from 0 to GetReceptionReportCount()-1 (note that no check is performed to see if index is valid).
Definition at line 242 of file rtcpsrpacket.h.
References qrtplib::RTCPReceiverReport::dlsr.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     RTCPReceiverReport *r = GotoReport(index);
     return m_endian.qToHost(r->dlsr);
 }
GetExtendedHighestSequenceNumber()
uint32_t qrtplib::RTCPSRPacket::GetExtendedHighestSequenceNumber (int index) const inline
Returns the extended highest sequence number of the reception report block described by index which may have a value from 0 to GetReceptionReportCount()-1 (note that no check is performed to see if index is valid).
Definition at line 218 of file rtcpsrpacket.h.
References qrtplib::RTCPReceiverReport::exthighseqnr.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     RTCPReceiverReport *r = GotoReport(index);
     return m_endian.qToHost(r->exthighseqnr);
 }
GetFractionLost()
uint8_t qrtplib::RTCPSRPacket::GetFractionLost (int index) const inline
Returns the `fraction lost' field of the reception report described by index which may have a value from 0 to GetReceptionReportCount()-1 (note that no check is performed to see if index is valid).
Definition at line 198 of file rtcpsrpacket.h.
References qrtplib::RTCPReceiverReport::fractionlost.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     RTCPReceiverReport *r = GotoReport(index);
     return r->fractionlost;
 }
GetJitter()
uint32_t qrtplib::RTCPSRPacket::GetJitter (int index) const inline
Returns the jitter field of the reception report block described by index which may have a value from 0 to GetReceptionReportCount()-1 (note that no check is performed to see if index is valid).
Definition at line 226 of file rtcpsrpacket.h.
References qrtplib::RTCPReceiverReport::jitter.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     RTCPReceiverReport *r = GotoReport(index);
     return m_endian.qToHost(r->jitter);
 }
GetLostPacketCount()
int32_t qrtplib::RTCPSRPacket::GetLostPacketCount (int index) const inline
Returns the number of lost packets in the reception report block described by index which may have a value from 0 to GetReceptionReportCount()-1 (note that no check is performed to see if index is valid).
Definition at line 206 of file rtcpsrpacket.h.
References qrtplib::RTCPReceiverReport::packetslost.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     RTCPReceiverReport *r = GotoReport(index);
     uint32_t count = ((uint32_t) r->packetslost[2]) | (((uint32_t) r->packetslost[1]) << 8) | (((uint32_t) r->packetslost[0]) << 16);
     if ((count & 0x00800000) != 0) // test for negative number
         count |= 0xFF000000;
     int32_t *count2 = (int32_t *) (&count);
     return (*count2);
 }
GetLSR()
uint32_t qrtplib::RTCPSRPacket::GetLSR (int index) const inline
Returns the LSR field of the reception report block described by index which may have a value from 0 to GetReceptionReportCount()-1 (note that no check is performed to see if index is valid).
Definition at line 234 of file rtcpsrpacket.h.
References qrtplib::RTCPReceiverReport::lsr.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     RTCPReceiverReport *r = GotoReport(index);
     return m_endian.qToHost(r->lsr);
 }
GetNTPTimestamp()
RTPNTPTime qrtplib::RTCPSRPacket::GetNTPTimestamp () const inline
Returns the NTP timestamp contained in the sender report.
Definition at line 143 of file rtcpsrpacket.h.
References qrtplib::RTCPSenderReport::ntptime_lsw, and qrtplib::RTCPSenderReport::ntptime_msw.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return RTPNTPTime(0, 0);
     RTCPSenderReport *sr = (RTCPSenderReport *) (data + sizeof(RTCPCommonHeader) + sizeof(uint32_t));
     return RTPNTPTime(m_endian.qToHost(sr->ntptime_msw), m_endian.qToHost(sr->ntptime_lsw));
 }
GetReceptionReportCount()
int qrtplib::RTCPSRPacket::GetReceptionReportCount () const inline
Returns the number of reception report blocks present in this packet.
Definition at line 176 of file rtcpsrpacket.h.
References qrtplib::RTCPCommonHeader::count.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     RTCPCommonHeader *hdr = (RTCPCommonHeader *) data;
     return ((int) hdr->count);
 }
GetRTPTimestamp()
uint32_t qrtplib::RTCPSRPacket::GetRTPTimestamp () const inline
Returns the RTP timestamp contained in the sender report.
Definition at line 152 of file rtcpsrpacket.h.
References qrtplib::RTCPSenderReport::rtptimestamp.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     RTCPSenderReport *sr = (RTCPSenderReport *) (data + sizeof(RTCPCommonHeader) + sizeof(uint32_t));
     return m_endian.qToHost(sr->rtptimestamp);
 }
GetSenderOctetCount()
uint32_t qrtplib::RTCPSRPacket::GetSenderOctetCount () const inline
Returns the sender's octet count contained in the sender report.
Definition at line 168 of file rtcpsrpacket.h.
References qrtplib::RTCPSenderReport::octetcount.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     RTCPSenderReport *sr = (RTCPSenderReport *) (data + sizeof(RTCPCommonHeader) + sizeof(uint32_t));
     return m_endian.qToHost(sr->octetcount);
 }
GetSenderPacketCount()
uint32_t qrtplib::RTCPSRPacket::GetSenderPacketCount () const inline
Returns the sender's packet count contained in the sender report.
Definition at line 160 of file rtcpsrpacket.h.
References qrtplib::RTCPSenderReport::packetcount.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     RTCPSenderReport *sr = (RTCPSenderReport *) (data + sizeof(RTCPCommonHeader) + sizeof(uint32_t));
     return m_endian.qToHost(sr->packetcount);
 }
GetSenderSSRC()
uint32_t qrtplib::RTCPSRPacket::GetSenderSSRC () const inline
Returns the SSRC of the participant who sent this packet.
Definition at line 134 of file rtcpsrpacket.h.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     uint32_t *ssrcptr = (uint32_t *) (data + sizeof(RTCPCommonHeader));
     return m_endian.qToHost(*ssrcptr);
 }
GetSSRC()
uint32_t qrtplib::RTCPSRPacket::GetSSRC (int index) const inline
Returns the SSRC of the reception report block described by index which may have a value from 0 to GetReceptionReportCount()-1 (note that no check is performed to see if index is valid).
Definition at line 190 of file rtcpsrpacket.h.
References qrtplib::RTCPReceiverReport::ssrc.
Referenced by qrtplib::RTPSources::ProcessRTCPCompoundPacket().
 {
     if (!knownformat)
         return 0;
     RTCPReceiverReport *r = GotoReport(index);
     return m_endian.qToHost(r->ssrc);
 }
GotoReport()
RTCPReceiverReport * qrtplib::RTCPSRPacket::GotoReport (int index) const inline private
Definition at line 184 of file rtcpsrpacket.h.
 {
     RTCPReceiverReport *r = (RTCPReceiverReport *) (data + sizeof(RTCPCommonHeader) + sizeof(uint32_t) + sizeof(RTCPSenderReport) + index * sizeof(RTCPReceiverReport));
     return r;
 }
Member Data Documentation
m_endian
RTPEndian qrtplib::RTCPSRPacket::m_endian private
Definition at line 131 of file rtcpsrpacket.h.
The documentation for this class was generated from the following files:
qrtplib/rtcpsrpacket.h
qrtplib/rtcpsrpacket.cpp