SDRAngel: FileInput::MsgConfigureFileInput Class Reference
FileInput::MsgConfigureFileInput Class Reference
#include <fileinput.h>
Public Member Functions
const FileInputSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureFileInput * create (const FileInputSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureFileInput (const FileInputSettings &settings, bool force)
Private Attributes
FileInputSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 41 of file fileinput.h.
Constructor & Destructor Documentation
MsgConfigureFileInput()
FileInput::MsgConfigureFileInput::MsgConfigureFileInput (const FileInputSettings & settings, bool force) inline private
Definition at line 57 of file fileinput.h.
Referenced by create().
                                                                              :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureFileInput* FileInput::MsgConfigureFileInput::create (const FileInputSettings & settings, bool force) inline static
Definition at line 48 of file fileinput.h.
References MsgConfigureFileInput().
Referenced by FileInput::deserialize(), FileInputGUI::on_acceleration_currentIndexChanged(), FileInputGUI::on_playLoop_toggled(), FileInput::setCenterFrequency(), and FileInput::webapiSettingsPutPatch().
         {
             return new MsgConfigureFileInput(settings, force);
         }
getForce()
bool FileInput::MsgConfigureFileInput::getForce () const inline
Definition at line 46 of file fileinput.h.
References m_force.
 { return m_force; }
getSettings()
const FileInputSettings& FileInput::MsgConfigureFileInput::getSettings () const inline
Definition at line 45 of file fileinput.h.
References m_settings.
Referenced by FileInputGUI::handleMessage(), and FileInput::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool FileInput::MsgConfigureFileInput::m_force private
Definition at line 55 of file fileinput.h.
Referenced by getForce().
m_settings
FileInputSettings FileInput::MsgConfigureFileInput::m_settings private
Definition at line 54 of file fileinput.h.
Referenced by getSettings().
The documentation for this class was generated from the following file:
plugins/samplesource/fileinput/fileinput.h