SDRAngel: SWGSDRangel::SWGSampleRate Class Reference
SWGSDRangel::SWGSampleRate Class Reference
#include <SWGSampleRate.h>
Public Member Functions
SWGSampleRate ()
SWGSampleRate (QString *json)
virtual ~SWGSampleRate ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGSampleRate * fromJson (QString &jsonString) override
qint32 getRate ()
void setRate (qint32 rate)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 rate
bool m_rate_isSet
Detailed Description
Definition at line 31 of file SWGSampleRate.h.
Constructor & Destructor Documentation
SWGSampleRate() [1/2]
SWGSDRangel::SWGSampleRate::SWGSampleRate ()
Definition at line 30 of file SWGSampleRate.cpp.
References m_rate_isSet, and rate.
{
     rate = 0;
     m_rate_isSet = false;
 }
SWGSampleRate() [2/2]
SWGSDRangel::SWGSampleRate::SWGSampleRate (QString * json)
Definition at line 25 of file SWGSampleRate.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGSampleRate()
SWGSDRangel::SWGSampleRate::~SWGSampleRate () virtual
Definition at line 35 of file SWGSampleRate.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGSampleRate::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 66 of file SWGSampleRate.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGSampleRate::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 77 of file SWGSampleRate.cpp.
References m_rate_isSet, and rate.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_rate_isSet){
         obj->insert("rate", QJsonValue(rate));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGSampleRate::cleanup ()
Definition at line 46 of file SWGSampleRate.cpp.
Referenced by ~SWGSampleRate().
{
 }
fromJson()
SWGSampleRate * SWGSDRangel::SWGSampleRate::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 51 of file SWGSampleRate.cpp.
References fromJsonObject().
Referenced by SWGSampleRate().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGSampleRate::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 60 of file SWGSampleRate.cpp.
References rate, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&rate, pJson["rate"], "qint32", "");
 }
getRate()
qint32 SWGSDRangel::SWGSampleRate::getRate ()
Definition at line 87 of file SWGSampleRate.cpp.
References rate.
{
     return rate;
 }
init()
void SWGSDRangel::SWGSampleRate::init ()
Definition at line 40 of file SWGSampleRate.cpp.
References m_rate_isSet, and rate.
Referenced by SWGSampleRate().
                     {
     rate = 0;
     m_rate_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGSampleRate::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 98 of file SWGSampleRate.cpp.
References m_rate_isSet.
                     {
     bool isObjectUpdated = false;
     do{
         if(m_rate_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setRate()
void SWGSDRangel::SWGSampleRate::setRate (qint32 rate)
Definition at line 91 of file SWGSampleRate.cpp.
References m_rate_isSet, and rate.
{
     this->rate = rate;
     this->m_rate_isSet = true;
 }
Member Data Documentation
m_rate_isSet
bool SWGSDRangel::SWGSampleRate::m_rate_isSet private
Definition at line 52 of file SWGSampleRate.h.
Referenced by asJsonObject(), init(), isSet(), setRate(), and SWGSampleRate().
rate
qint32 SWGSDRangel::SWGSampleRate::rate private
Definition at line 51 of file SWGSampleRate.h.
Referenced by asJsonObject(), fromJsonObject(), getRate(), init(), setRate(), and SWGSampleRate().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGSampleRate.h
swagger/sdrangel/code/qt5/client/SWGSampleRate.cpp