SDRAngel: qrtplib::RTCPCompoundPacket Class Reference
qrtplib::RTCPCompoundPacket Class Reference
#include <rtcpcompoundpacket.h>
Public Member Functions
RTCPCompoundPacket (RTPRawPacket &rawpack)
RTCPCompoundPacket (uint8_t *packet, std::size_t len)
virtual ~RTCPCompoundPacket ()
int GetCreationError ()
uint8_t * GetCompoundPacketData ()
std::size_t GetCompoundPacketLength ()
void GotoFirstPacket ()
RTCPPacket * GetNextPacket ()
Protected Member Functions
RTCPCompoundPacket ()
void ClearPacketList ()
int ParseData (uint8_t *packet, std::size_t len)
Protected Attributes
RTPEndian m_endian
int error
uint8_t * compoundpacket
std::size_t compoundpacketlength
std::list< RTCPPacket * > rtcppacklist
std::list< RTCPPacket * >::const_iterator rtcppackit
Detailed Description
Represents an RTCP compound packet.
Definition at line 55 of file rtcpcompoundpacket.h.
Constructor & Destructor Documentation
RTCPCompoundPacket() [1/3]
qrtplib::RTCPCompoundPacket::RTCPCompoundPacket (RTPRawPacket & rawpack)
Creates an RTCPCompoundPacket instance from the data in rawpack, installing a memory manager if specified.
Definition at line 48 of file rtcpcompoundpacket.cpp.
References compoundpacket, compoundpacketlength, ERR_RTP_RTCPCOMPOUND_INVALIDPACKET, error, qrtplib::RTPRawPacket::GetData(), qrtplib::RTPRawPacket::GetDataLength(), qrtplib::RTPRawPacket::IsRTP(), ParseData(), rtcppackit, and rtcppacklist.
 {
     compoundpacket = 0;
     compoundpacketlength = 0;
     error = 0;
     if (rawpack.IsRTP())
     {
         error = ERR_RTP_RTCPCOMPOUND_INVALIDPACKET;
         return;
     }
     uint8_t *data = rawpack.GetData();
     std::size_t datalen = rawpack.GetDataLength();
     error = ParseData(data, datalen);
     if (error < 0) {
         return;
     }
     compoundpacket = rawpack.GetData();
     compoundpacketlength = rawpack.GetDataLength();
     rtcppackit = rtcppacklist.begin();
 }
RTCPCompoundPacket() [2/3]
qrtplib::RTCPCompoundPacket::RTCPCompoundPacket (uint8_t * packet, std::size_t len)
Creates an RTCPCompoundPacket instance from the data in packet}, with size len.
Definition at line 75 of file rtcpcompoundpacket.cpp.
References compoundpacket, compoundpacketlength, error, ParseData(), rtcppackit, and rtcppacklist.
 {
     compoundpacket = 0;
     compoundpacketlength = 0;
     error = ParseData(packet, packetlen);
     if (error < 0) {
         return;
     }
     compoundpacket = packet;
     compoundpacketlength = packetlen;
     rtcppackit = rtcppacklist.begin();
 }
RTCPCompoundPacket() [3/3]
qrtplib::RTCPCompoundPacket::RTCPCompoundPacket () protected
Definition at line 92 of file rtcpcompoundpacket.cpp.
References compoundpacket, compoundpacketlength, and error.
 {
     compoundpacket = 0;
     compoundpacketlength = 0;
     error = 0;
 }
~RTCPCompoundPacket()
qrtplib::RTCPCompoundPacket::~RTCPCompoundPacket () virtual
Definition at line 188 of file rtcpcompoundpacket.cpp.
References ClearPacketList().
 {
     ClearPacketList();
 }
Member Function Documentation
ClearPacketList()
void qrtplib::RTCPCompoundPacket::ClearPacketList () protected
Definition at line 193 of file rtcpcompoundpacket.cpp.
References rtcppackit, and rtcppacklist.
Referenced by ParseData(), and ~RTCPCompoundPacket().
 {
     std::list<RTCPPacket *>::const_iterator it;
     for (it = rtcppacklist.begin(); it != rtcppacklist.end(); it++) {
         delete *it;
     }
     rtcppacklist.clear();
     rtcppackit = rtcppacklist.begin();
 }
GetCompoundPacketData()
uint8_t* qrtplib::RTCPCompoundPacket::GetCompoundPacketData () inline
Returns a pointer to the data of the entire RTCP compound packet.
Definition at line 78 of file rtcpcompoundpacket.h.
Referenced by qrtplib::RTPSession::BYEDestroy(), qrtplib::RTPSession::ProcessPolledData(), and qrtplib::RTPSession::SendRTCPAPPPacket().
     {
         return compoundpacket;
     }
GetCompoundPacketLength()
std::size_t qrtplib::RTCPCompoundPacket::GetCompoundPacketLength () inline
Returns the size of the entire RTCP compound packet.
Definition at line 84 of file rtcpcompoundpacket.h.
Referenced by qrtplib::RTCPScheduler::AnalyseIncoming(), qrtplib::RTCPScheduler::AnalyseOutgoing(), qrtplib::RTPSession::BYEDestroy(), qrtplib::RTPSession::ProcessPolledData(), and qrtplib::RTPSession::SendRTCPAPPPacket().
     {
         return compoundpacketlength;
     }
GetCreationError()
int qrtplib::RTCPCompoundPacket::GetCreationError () inline
Checks if the RTCP compound packet was created successfully. If the raw packet data in the constructor could not be parsed, this function returns the error code of what went wrong. If the packet had an invalid format, the return value is ERR_RTP_RTCPCOMPOUND_INVALIDPACKET.
Definition at line 72 of file rtcpcompoundpacket.h.
Referenced by qrtplib::RTPSources::ProcessRawPacket().
     {
         return error;
     }
GetNextPacket()
RTCPPacket* qrtplib::RTCPCompoundPacket::GetNextPacket () inline
Returns a pointer to the next individual RTCP packet. Returns a pointer to the next individual RTCP packet. Note that no delete call may be done on the RTCPPacket instance which is returned.
Definition at line 99 of file rtcpcompoundpacket.h.
Referenced by qrtplib::RTCPScheduler::AnalyseIncoming(), qrtplib::RTCPScheduler::AnalyseOutgoing(), and qrtplib::RTPSources::ProcessRTCPCompoundPacket().
     {
         if (rtcppackit == rtcppacklist.end())
             return 0;
         RTCPPacket *p = *rtcppackit;
         rtcppackit++;
         return p;
     }
GotoFirstPacket()
void qrtplib::RTCPCompoundPacket::GotoFirstPacket () inline
Starts the iteration over the individual RTCP packets in the RTCP compound packet.
Definition at line 90 of file rtcpcompoundpacket.h.
Referenced by qrtplib::RTCPScheduler::AnalyseIncoming(), qrtplib::RTCPScheduler::AnalyseOutgoing(), and qrtplib::RTPSources::ProcessRTCPCompoundPacket().
     {
         rtcppackit = rtcppacklist.begin();
     }
ParseData()
int qrtplib::RTCPCompoundPacket::ParseData (uint8_t * packet, std::size_t len) protected
Definition at line 99 of file rtcpcompoundpacket.cpp.
References ClearPacketList(), ERR_RTP_RTCPCOMPOUND_INVALIDPACKET, qrtplib::RTCPCommonHeader::length, m_endian, qrtplib::RTCPCommonHeader::packettype, qrtplib::RTCPCommonHeader::padding, qrtplib::RTPEndian::qToHost(), rtcppacklist, RTP_RTCPTYPE_APP, RTP_RTCPTYPE_BYE, RTP_RTCPTYPE_RR, RTP_RTCPTYPE_SDES, RTP_RTCPTYPE_SR, RTP_VERSION, and qrtplib::RTCPCommonHeader::version.
Referenced by RTCPCompoundPacket().
 {
     bool first;
     if (datalen < sizeof(RTCPCommonHeader))
         return ERR_RTP_RTCPCOMPOUND_INVALIDPACKET;
     first = true;
     do
     {
         RTCPCommonHeader *rtcphdr;
         std::size_t length;
         rtcphdr = (RTCPCommonHeader *) data;
         if (rtcphdr->version != RTP_VERSION) // check version
         {
             ClearPacketList();
             return ERR_RTP_RTCPCOMPOUND_INVALIDPACKET;
         }
         if (first)
         {
             // Check if first packet is SR or RR
             first = false;
             if (!(rtcphdr->packettype == RTP_RTCPTYPE_SR || rtcphdr->packettype == RTP_RTCPTYPE_RR))
             {
                 ClearPacketList();
                 return ERR_RTP_RTCPCOMPOUND_INVALIDPACKET;
             }
         }
         length = (std::size_t) m_endian.qToHost(rtcphdr->length);
         length++;
         length *= sizeof(uint32_t);
         if (length > datalen) // invalid length field
         {
             ClearPacketList();
             return ERR_RTP_RTCPCOMPOUND_INVALIDPACKET;
         }
         if (rtcphdr->padding)
         {
             // check if it's the last packet
             if (length != datalen)
             {
                 ClearPacketList();
                 return ERR_RTP_RTCPCOMPOUND_INVALIDPACKET;
             }
         }
         RTCPPacket *p;
         switch (rtcphdr->packettype)
         {
         case RTP_RTCPTYPE_SR:
             p = new RTCPSRPacket(data, length);
             break;
         case RTP_RTCPTYPE_RR:
             p = new RTCPRRPacket(data, length);
             break;
         case RTP_RTCPTYPE_SDES:
             p = new RTCPSDESPacket(data, length);
             break;
         case RTP_RTCPTYPE_BYE:
             p = new RTCPBYEPacket(data, length);
             break;
         case RTP_RTCPTYPE_APP:
             p = new RTCPAPPPacket(data, length);
             break;
         default:
             p = new RTCPUnknownPacket(data, length);
         }
         rtcppacklist.push_back(p);
         datalen -= length;
         data += length;
     } while (datalen >= (std::size_t) sizeof(RTCPCommonHeader));
     if (datalen != 0) // some remaining bytes
     {
         ClearPacketList();
         return ERR_RTP_RTCPCOMPOUND_INVALIDPACKET;
     }
     return 0;
 }
Member Data Documentation
compoundpacket
uint8_t* qrtplib::RTCPCompoundPacket::compoundpacket protected
Definition at line 115 of file rtcpcompoundpacket.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::EndBuild(), qrtplib::RTCPCompoundPacketBuilder::InitBuild(), RTCPCompoundPacket(), and qrtplib::RTCPCompoundPacketBuilder::~RTCPCompoundPacketBuilder().
compoundpacketlength
std::size_t qrtplib::RTCPCompoundPacket::compoundpacketlength protected
Definition at line 116 of file rtcpcompoundpacket.h.
Referenced by qrtplib::RTCPCompoundPacketBuilder::EndBuild(), and RTCPCompoundPacket().
error
int qrtplib::RTCPCompoundPacket::error protected
Definition at line 113 of file rtcpcompoundpacket.h.
Referenced by RTCPCompoundPacket().
m_endian
RTPEndian qrtplib::RTCPCompoundPacket::m_endian protected
Definition at line 112 of file rtcpcompoundpacket.h.
Referenced by ParseData().
rtcppackit
std::list<RTCPPacket *>::const_iterator qrtplib::RTCPCompoundPacket::rtcppackit protected
Definition at line 119 of file rtcpcompoundpacket.h.
Referenced by ClearPacketList(), and RTCPCompoundPacket().
rtcppacklist
std::list<RTCPPacket *> qrtplib::RTCPCompoundPacket::rtcppacklist protected
Definition at line 118 of file rtcpcompoundpacket.h.
Referenced by ClearPacketList(), qrtplib::RTCPCompoundPacketBuilder::EndBuild(), ParseData(), and RTCPCompoundPacket().
The documentation for this class was generated from the following files:
qrtplib/rtcpcompoundpacket.h
qrtplib/rtcpcompoundpacket.cpp