SDRAngel: SpectrumVis::MsgConfigureSpectrumVis Class Reference
SpectrumVis::MsgConfigureSpectrumVis Class Reference
#include <spectrumvis.h>
Public Member Functions
MsgConfigureSpectrumVis (int fftSize, int overlapPercent, unsigned int averageNb, int preProcessMode, FFTWindow::Function window, bool linear)
int getFFTSize () const
int getOverlapPercent () const
unsigned int getAverageNb () const
SpectrumVis::AvgMode getAvgMode () const
FFTWindow::Function getWindow () const
bool getLinear () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Private Attributes
int m_fftSize
int m_overlapPercent
unsigned int m_averageNb
SpectrumVis::AvgMode m_avgMode
FFTWindow::Function m_window
bool m_linear
Additional Inherited Members
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 28 of file spectrumvis.h.
Constructor & Destructor Documentation
MsgConfigureSpectrumVis()
SpectrumVis::MsgConfigureSpectrumVis::MsgConfigureSpectrumVis (int fftSize, int overlapPercent, unsigned int averageNb, int preProcessMode, FFTWindow::Function window, bool linear) inline
Definition at line 32 of file spectrumvis.h.
                              :
             Message(),
             m_fftSize(fftSize),
             m_overlapPercent(overlapPercent),
             m_averageNb(averageNb),
             m_window(window),
             m_linear(linear)
         {
             m_avgMode = preProcessMode < 0 ? AvgModeNone : preProcessMode > 3 ? AvgModeMax : (SpectrumVis::AvgMode) preProcessMode;
         }
Member Function Documentation
getAverageNb()
unsigned int SpectrumVis::MsgConfigureSpectrumVis::getAverageNb () const inline
Definition at line 51 of file spectrumvis.h.
Referenced by SpectrumVis::handleMessage().
 { return m_averageNb; }
getAvgMode()
SpectrumVis::AvgMode SpectrumVis::MsgConfigureSpectrumVis::getAvgMode () const inline
Definition at line 52 of file spectrumvis.h.
Referenced by SpectrumVis::handleMessage().
 { return m_avgMode; }
getFFTSize()
int SpectrumVis::MsgConfigureSpectrumVis::getFFTSize () const inline
Definition at line 49 of file spectrumvis.h.
Referenced by SpectrumVis::handleMessage().
 { return m_fftSize; }
getLinear()
bool SpectrumVis::MsgConfigureSpectrumVis::getLinear () const inline
Definition at line 54 of file spectrumvis.h.
Referenced by SpectrumVis::handleMessage().
 { return m_linear; }
getOverlapPercent()
int SpectrumVis::MsgConfigureSpectrumVis::getOverlapPercent () const inline
Definition at line 50 of file spectrumvis.h.
Referenced by SpectrumVis::handleMessage().
 { return m_overlapPercent; }
getWindow()
FFTWindow::Function SpectrumVis::MsgConfigureSpectrumVis::getWindow () const inline
Definition at line 53 of file spectrumvis.h.
Referenced by SpectrumVis::handleMessage().
 { return m_window; }
Member Data Documentation
m_averageNb
unsigned int SpectrumVis::MsgConfigureSpectrumVis::m_averageNb private
Definition at line 59 of file spectrumvis.h.
m_avgMode
SpectrumVis::AvgMode SpectrumVis::MsgConfigureSpectrumVis::m_avgMode private
Definition at line 60 of file spectrumvis.h.
m_fftSize
int SpectrumVis::MsgConfigureSpectrumVis::m_fftSize private
Definition at line 57 of file spectrumvis.h.
m_linear
bool SpectrumVis::MsgConfigureSpectrumVis::m_linear private
Definition at line 62 of file spectrumvis.h.
m_overlapPercent
int SpectrumVis::MsgConfigureSpectrumVis::m_overlapPercent private
Definition at line 58 of file spectrumvis.h.
m_window
FFTWindow::Function SpectrumVis::MsgConfigureSpectrumVis::m_window private
Definition at line 61 of file spectrumvis.h.
The documentation for this class was generated from the following file:
sdrgui/dsp/spectrumvis.h