SDRAngel: DeviceSampleMIMO Class Reference
DeviceSampleMIMO Class Reference abstract
#include <devicesamplemimo.h>
Public Types
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
Public Member Functions
DeviceSampleMIMO ()
virtual ~DeviceSampleMIMO ()
virtual void destroy ()=0
virtual void init ()=0
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()=0
virtual void stop ()=0
virtual QByteArray serialize () const =0
virtual bool deserialize (const QByteArray &data)=0
virtual const QString & getDeviceDescription () const =0
virtual int getSinkSampleRate (int index) const =0
Sample rate exposed by the sink at index.
virtual void setSinkSampleRate (int sampleRate, int index)=0
For when the sink sample rate is set externally.
virtual quint64 getSinkCenterFrequency (int index) const =0
Center frequency exposed by the sink at index.
virtual void setSinkCenterFrequency (qint64 centerFrequency, int index)=0
virtual int getSourceSampleRate (int index) const =0
Sample rate exposed by the source at index.
virtual void setSourceSampleRate (int sampleRate, int index)=0
For when the source sample rate is set externally.
virtual quint64 getSourceCenterFrequency (int index) const =0
Center frequency exposed by the source at index.
virtual void setSourceCenterFrequency (qint64 centerFrequency, int index)=0
virtual bool handleMessage (const Message &message)=0
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
MessageQueue * getInputMessageQueue ()
virtual void setMessageQueueToGUI (MessageQueue *queue)=0
MessageQueue * getMessageQueueToGUI ()
unsigned int getNbSourceFifos () const
Get the number of Tx FIFOs.
unsigned int getNbSinkFifos () const
Get the number of Rx FIFOs.
SampleSourceFifo * getSampleSourceFifo (unsigned int index)
Get Tx FIFO at index.
SampleSinkFifo * getSampleSinkFifo (unsigned int index)
Get Rx FIFO at index.
unsigned int getNbSourceStreams () const
Commodity function same as getNbSinkFifos (Rx or source streams)
unsigned int getNbSinkStreams () const
Commodity function same as getNbSourceFifos (Tx or sink streams)
Protected Slots
void handleInputMessages ()
Protected Attributes
std::vector< SampleSourceFifo > m_sampleSourceFifos
Tx FIFOs.
std::vector< SampleSinkFifo > m_sampleSinkFifos
Rx FIFOs.
MessageQueue m_inputMessageQueue
Input queue to the sink.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 37 of file devicesamplemimo.h.
Member Enumeration Documentation
fcPos_t
enum DeviceSampleMIMO::fcPos_t
Enumerator
FC_POS_INFRA
FC_POS_SUPRA
FC_POS_CENTER
Definition at line 40 of file devicesamplemimo.h.
                  {
         FC_POS_INFRA = 0,
         FC_POS_SUPRA,
         FC_POS_CENTER
     } fcPos_t;
Constructor & Destructor Documentation
DeviceSampleMIMO()
DeviceSampleMIMO::DeviceSampleMIMO ()
Definition at line 23 of file devicesamplemimo.cpp.
References handleInputMessages(), and m_inputMessageQueue.
                                    :
     m_guiMessageQueue(0)
 {
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
 }
~DeviceSampleMIMO()
DeviceSampleMIMO::~DeviceSampleMIMO () virtual
Definition at line 29 of file devicesamplemimo.cpp.
 {
 }
Member Function Documentation
deserialize()
virtual bool DeviceSampleMIMO::deserialize (const QByteArray & data) pure virtual
Implemented in TestMI.
destroy()
virtual void DeviceSampleMIMO::destroy () pure virtual
Implemented in TestMI.
Referenced by PluginInterface::deleteSampleMIMOPluginInstanceMIMO().
getDeviceDescription()
virtual const QString& DeviceSampleMIMO::getDeviceDescription () const pure virtual
Implemented in TestMI.
Referenced by DSPDeviceMIMOEngine::gotoInit(), and DSPDeviceMIMOEngine::handleSetMIMO().
getInputMessageQueue()
MessageQueue* DeviceSampleMIMO::getInputMessageQueue () inline
Definition at line 121 of file devicesamplemimo.h.
Referenced by DeviceAPI::getSamplingDeviceInputMessageQueue(), TestMIGui::on_record_toggled(), TestMIGui::on_startStop_toggled(), and TestMIGui::updateHardware().
 { return &m_inputMessageQueue; }
getMessageQueueToGUI()
MessageQueue* DeviceSampleMIMO::getMessageQueueToGUI () inline
Definition at line 123 of file devicesamplemimo.h.
Referenced by DeviceAPI::getSamplingDeviceGUIMessageQueue(), and DSPDeviceMIMOEngine::handleInputMessages().
 { return m_guiMessageQueue; }
getNbSinkFifos()
unsigned int DeviceSampleMIMO::getNbSinkFifos () const inline
Get the number of Rx FIFOs.
Definition at line 126 of file devicesamplemimo.h.
Referenced by DSPDeviceMIMOEngine::gotoInit().
getNbSinkStreams()
unsigned int DeviceSampleMIMO::getNbSinkStreams () const inline
Commodity function same as getNbSourceFifos (Tx or sink streams)
Definition at line 133 of file devicesamplemimo.h.
getNbSourceFifos()
unsigned int DeviceSampleMIMO::getNbSourceFifos () const inline
Get the number of Tx FIFOs.
Definition at line 125 of file devicesamplemimo.h.
getNbSourceStreams()
unsigned int DeviceSampleMIMO::getNbSourceStreams () const inline
Commodity function same as getNbSinkFifos (Rx or source streams)
Definition at line 132 of file devicesamplemimo.h.
Referenced by DSPDeviceMIMOEngine::work().
getSampleSinkFifo()
SampleSinkFifo * DeviceSampleMIMO::getSampleSinkFifo (unsigned int index)
Get Rx FIFO at index.
Definition at line 55 of file devicesamplemimo.cpp.
References m_sampleSinkFifos.
Referenced by DSPDeviceMIMOEngine::handleSetMIMO(), DSPDeviceMIMOEngine::work(), and DSPDeviceMIMOEngine::workSampleSink().
 {
     if (index >= m_sampleSinkFifos.size()) {
         return nullptr;
     } else {
         return &m_sampleSinkFifos[index];
     }
 }
getSampleSourceFifo()
SampleSourceFifo * DeviceSampleMIMO::getSampleSourceFifo (unsigned int index)
Get Tx FIFO at index.
Definition at line 46 of file devicesamplemimo.cpp.
References m_sampleSourceFifos.
Referenced by DSPDeviceMIMOEngine::handleForwardToSpectrumSink(), and DSPDeviceMIMOEngine::handleSynchronousMessages().
 {
     if (index >= m_sampleSourceFifos.size()) {
         return nullptr;
     } else {
         return &m_sampleSourceFifos[index];
     }
 }
getSinkCenterFrequency()
virtual quint64 DeviceSampleMIMO::getSinkCenterFrequency (int index) const pure virtual
Center frequency exposed by the sink at index.
Implemented in TestMI.
Referenced by DSPDeviceMIMOEngine::handleSynchronousMessages().
getSinkSampleRate()
virtual int DeviceSampleMIMO::getSinkSampleRate (int index) const pure virtual
Sample rate exposed by the sink at index.
Implemented in TestMI.
Referenced by DSPDeviceMIMOEngine::handleSynchronousMessages().
getSourceCenterFrequency()
virtual quint64 DeviceSampleMIMO::getSourceCenterFrequency (int index) const pure virtual
Center frequency exposed by the source at index.
Implemented in TestMI.
Referenced by DSPDeviceMIMOEngine::gotoInit(), and DSPDeviceMIMOEngine::handleSynchronousMessages().
getSourceSampleRate()
virtual int DeviceSampleMIMO::getSourceSampleRate (int index) const pure virtual
Sample rate exposed by the source at index.
Implemented in TestMI.
Referenced by AMDemod::applySettings(), DSPDeviceMIMOEngine::gotoInit(), and DSPDeviceMIMOEngine::handleSynchronousMessages().
handleInputMessages
void DeviceSampleMIMO::handleInputMessages () protected slot
Definition at line 33 of file devicesamplemimo.cpp.
References handleMessage(), m_inputMessageQueue, and MessageQueue::pop().
Referenced by DeviceSampleMIMO().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
virtual bool DeviceSampleMIMO::handleMessage (const Message & message) pure virtual
Implemented in TestMI.
Referenced by handleInputMessages().
init()
virtual void DeviceSampleMIMO::init () pure virtual
initializations to be done when all collaborating objects are created and possibly connected
Implemented in TestMI.
serialize()
virtual QByteArray DeviceSampleMIMO::serialize () const pure virtual
Implemented in TestMI.
setMessageQueueToGUI()
virtual void DeviceSampleMIMO::setMessageQueueToGUI (MessageQueue * queue) pure virtual
Implemented in TestMI.
Referenced by MainWindow::sampleMIMOChanged(), and TestMIGui::TestMIGui().
setSinkCenterFrequency()
virtual void DeviceSampleMIMO::setSinkCenterFrequency (qint64 centerFrequency, int index) pure virtual
Implemented in TestMI.
setSinkSampleRate()
virtual void DeviceSampleMIMO::setSinkSampleRate (int sampleRate, int index) pure virtual
For when the sink sample rate is set externally.
Implemented in TestMI.
setSourceCenterFrequency()
virtual void DeviceSampleMIMO::setSourceCenterFrequency (qint64 centerFrequency, int index) pure virtual
Implemented in TestMI.
setSourceSampleRate()
virtual void DeviceSampleMIMO::setSourceSampleRate (int sampleRate, int index) pure virtual
For when the source sample rate is set externally.
Implemented in TestMI.
start()
virtual bool DeviceSampleMIMO::start () pure virtual
Implemented in TestMI.
Referenced by DSPDeviceMIMOEngine::gotoRunning().
stop()
virtual void DeviceSampleMIMO::stop () pure virtual
Implemented in TestMI.
Referenced by DSPDeviceMIMOEngine::gotoIdle().
webapiReportGet()
virtual int DeviceSampleMIMO::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) inline virtual
Definition at line 112 of file devicesamplemimo.h.
     {
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
webapiRun()
virtual int DeviceSampleMIMO::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) inline virtual
Reimplemented in TestMI.
Definition at line 102 of file devicesamplemimo.h.
     {
         (void) run;
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
webapiRunGet()
virtual int DeviceSampleMIMO::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) inline virtual
Reimplemented in TestMI.
Definition at line 93 of file devicesamplemimo.h.
     {
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
webapiSettingsGet()
virtual int DeviceSampleMIMO::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) inline virtual
Reimplemented in TestMI.
Definition at line 71 of file devicesamplemimo.h.
     {
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
webapiSettingsPutPatch()
virtual int DeviceSampleMIMO::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) inline virtual
Parameters
force true to force settings = put
Reimplemented in TestMI.
Definition at line 80 of file devicesamplemimo.h.
     {
         (void) force;
         (void) deviceSettingsKeys;
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
Member Data Documentation
m_guiMessageQueue
MessageQueue* DeviceSampleMIMO::m_guiMessageQueue protected
Input message queue to the GUI.
Definition at line 142 of file devicesamplemimo.h.
Referenced by TestMI::deserialize(), TestMI::setMessageQueueToGUI(), TestMI::setSourceCenterFrequency(), TestMI::webapiRun(), and TestMI::webapiSettingsPutPatch().
m_inputMessageQueue
MessageQueue DeviceSampleMIMO::m_inputMessageQueue protected
Input queue to the sink.
Definition at line 141 of file devicesamplemimo.h.
Referenced by TestMI::deserialize(), DeviceSampleMIMO(), handleInputMessages(), TestMI::setSourceCenterFrequency(), TestMI::webapiRun(), and TestMI::webapiSettingsPutPatch().
m_sampleSinkFifos
std::vector<SampleSinkFifo> DeviceSampleMIMO::m_sampleSinkFifos protected
Rx FIFOs.
Definition at line 140 of file devicesamplemimo.h.
Referenced by getSampleSinkFifo(), and TestMI::start().
m_sampleSourceFifos
std::vector<SampleSourceFifo> DeviceSampleMIMO::m_sampleSourceFifos protected
Tx FIFOs.
Definition at line 139 of file devicesamplemimo.h.
Referenced by getSampleSourceFifo().
The documentation for this class was generated from the following files:
sdrbase/dsp/devicesamplemimo.h
sdrbase/dsp/devicesamplemimo.cpp