SDRAngel: AudioFilter Class Reference
AudioFilter Class Reference
#include <audiofilter.h>
Public Member Functions
AudioFilter ()
~AudioFilter ()
void useHP (bool useHP)
bool usesHP () const
void setDecimFilters (int srHigh, int srLow, float fcHigh, float fcLow, float gain=1.0f)
float run (const float &sample)
float runHP (const float &sample)
float runLP (const float &sample)
Private Member Functions
void calculate2 (bool highPass, double fc, float *a, float *b, float fgain)
void cheby (bool highPass, double fc, float pr, int np, double *a, double *b, float fgain)
void cheby_sub (bool highPass, double fc, float pr, int np, int stage, double &a0, double &a1, double &a2, double &b1, double &b2)
Private Attributes
IIRFilter< float, 2 > m_filterLP
IIRFilter< float, 2 > m_filterHP
bool m_useHP
float m_lpva [3]
float m_lpvb [3]
float m_hpva [3]
float m_hpvb [3]
Static Private Attributes
static const float m_lpa [3] = {1.0, 1.392667E+00, -5.474446E-01}
static const float m_lpb [3] = {3.869430E-02, 7.738860E-02, 3.869430E-02}
static const float m_hpa [3] = {1.000000e+00, 1.667871e+00, -7.156964e-01}
static const float m_hpb [3] = {8.459039e-01, -1.691760e+00, 8.459039e-01}
Detailed Description
By default this is a 2 pole lowpass Chebyshev (recursive) filter at fc=0.075 using coefficients found in table 20-1 of http://www.analog.com/media/en/technical-documentation/dsp-book/dsp_book_Ch20.pdf
At the interpolated sampling frequency of 48 kHz the -3 dB corner is at 48 * .075 = 3.6 kHz which is perfect for voice
a0= 3.869430E-02 a1= 7.738860E-02 b1= 1.392667E+00 a2= 3.869430E-02 b2= -5.474446E-01
given x[n] is the new input sample and y[n] the returned output sample:
y[n] = a0*x[n] + a1*x[n] + a2*x[n] + b1*y[n-1] + b2*y[n-2]
This one works directly with floats
It can be generalized using the program found in tables 20-4 and 20-5 of the same document. This form is used as a decimation filter and can be set with the setDecimFilters method
Definition at line 44 of file audiofilter.h.
Constructor & Destructor Documentation
AudioFilter()
AudioFilter::AudioFilter ()
Definition at line 32 of file audiofilter.cpp.
                          :
         m_filterLP(m_lpa, m_lpb),
         m_filterHP(m_hpa, m_hpb),
         m_useHP(false)
 {}
~AudioFilter()
AudioFilter::~AudioFilter ()
Definition at line 38 of file audiofilter.cpp.
 {}
Member Function Documentation
calculate2()
void AudioFilter::calculate2 (bool highPass, double fc, float * a, float * b, float fgain) private
Definition at line 54 of file audiofilter.cpp.
References cheby(), and i.
Referenced by setDecimFilters().
 {
     double a[22], b[22];
     cheby(highPass, fc, 0.5, 2, a, b, fgain); // low-pass, 0.5% ripple, 2 pole filter
     // Copy to the 2-pole filter coefficients
     for (int i=0; i<3; i++) {
         vb[i] = a[i];
         va[i] = b[i];
     }
     va[0] = 1.0;
     qDebug() << "AudioFilter::calculate2:"
         << " highPass: " << highPass
         << " fc: " << fc
         << " a0: " << va[0]
         << " a1: " << va[1]
         << " a2: " << va[2]
         << " b0: " << vb[0]
         << " b1: " << vb[1]
         << " b2: " << vb[2];
 }
cheby()
void AudioFilter::cheby (bool highPass, double fc, float pr, int np, double * a, double * b, float fgain) private
Definition at line 83 of file audiofilter.cpp.
References b1, b2, cheby_sub(), and i.
Referenced by calculate2().
 {
     double a0, a1, a2, b1, b2;
     double ta[22], tb[22];
     std::fill(a, a+22, 0.0);
     std::fill(b, b+22, 0.0);
     a[2] = 1.0;
     b[2] = 1.0;
     for (int p = 1; p <= np/2; p++)
     {
         cheby_sub(highPass, fc, pr, np, p, a0, a1, a2, b1, b2);
         // Add coefficients to the cascade
         for (int i=0; i<22; i++)
         {
             ta[i] = a[i];
             tb[i] = b[i];
         }
         for (int i=2; i<22; i++)
         {
             a[i] = a0*ta[i] + a1*ta[i-1] + a2*ta[i-2];
             b[i] = tb[i] - b1*tb[i-1] - b2*tb[i-2];
         }
     }
     // Finish combining coefficients
     b[2] = 0;
     for (int i=0; i<20; i++)
     {
         a[i] = a[i+2];
         b[i] = -b[i+2];
     }
     // Normalize the gain
     double sa = 0.0;
     double sb = 0.0;
     for (int i=0; i<20; i++)
     {
         if (highPass)
         {
             sa += i%2 == 0 ? a[i] : -a[i];
             sb += i%2 == 0 ? b[i] : -b[i];
         }
         else
         {
             sa += a[i];
             sb += b[i];
         }
     }
     double gain = sa/(1.0 -sb);
     gain /= fgain;
     for (int i=0; i<20; i++) {
         a[i] /= gain;
     }
 }
cheby_sub()
void AudioFilter::cheby_sub (bool highPass, double fc, float pr, int np, int stage, double & a0, double & a1, double & a2, double & b1, double & b2) private
Definition at line 150 of file audiofilter.cpp.
References b1, cos(), exp(), log(), M_PI, sin(), sqrt(), and tan().
Referenced by cheby().
 {
     double rp = -cos((M_PI/(np*2)) + (stage-1)*(M_PI/np));
     double ip = sin((M_PI/(np*2)) + (stage-1)*(M_PI/np));
     // Warp from a circle to an ellipse
     double esx = 100.0 / (100.0 - pr);
     double es = sqrt(esx*esx -1.0);
     double vx = (1.0/np) * log((1.0/es) + sqrt((1.0/(es*es)) + 1.0));
     double kx = (1.0/np) * log((1.0/es) + sqrt((1.0/(es*es)) - 1.0));
     kx = (exp(kx) + exp(-kx))/2.0;
     rp = rp * ((exp(vx) - exp(-vx))/2.0) / kx;
     ip = ip * ((exp(vx) + exp(-vx))/2.0) / kx;
     double t = 2.0 * tan(0.5);
     double w = 2.0 * M_PI * fc;
     double m = rp*rp + ip*ip;
     double d = 4.0 - 4.0*rp*t + m*t*t;
     double x0 = (t*t)/d;
     double x1 = (2.0*t*t)/d;
     double x2 = (t*t)/d;
     double y1 = (8.0 - 2.0*m*t*t)/d;
     double y2 = (-4.0 - 4.0*rp*t - m*t*t)/d;
     double k;
     if (highPass) {
         k = -cos(w/2.0 + 0.5) / cos(w/2.0 - 0.5);
     } else {
         k = sin(0.5 - w/2.0) / sin(0.5 + w/2.0);
     }
     d = 1.0 + y1*k - y2*k*k;
     a0 = (x0 - x1*k + x2*k*k)/d;
     a1 = (-2.0*x0*k + x1 + x1*k*k - 2.0*x2*k)/d;
     a2 = (x0*k*k - x1*k + x2)/d;
     b1 = (2.0*k + y1 + y1*k*k - 2.0*y2*k)/d;
     b2 = (-(k*k) - y1*k + y2)/d;
     if (highPass)
     {
         a1 = -a1;
         b1 = -b1;
     }
 }
run()
float AudioFilter::run (const float & sample)
Definition at line 196 of file audiofilter.cpp.
References m_filterHP, m_filterLP, m_useHP, and IIRFilter< Type, Order >::run().
Referenced by AudioResampler::downSample(), AudioResampler::upSample(), and AudioNetSink::write().
 {
     return m_useHP ? m_filterLP.run(m_filterHP.run(sample)) : m_filterLP.run(sample);
 }
runHP()
float AudioFilter::runHP (const float & sample)
Definition at line 201 of file audiofilter.cpp.
References m_filterHP, and IIRFilter< Type, Order >::run().
 {
     return m_filterHP.run(sample);
 }
runLP()
float AudioFilter::runLP (const float & sample)
Definition at line 206 of file audiofilter.cpp.
References m_filterLP, and IIRFilter< Type, Order >::run().
Referenced by AudioNetSink::write().
 {
     return m_filterLP.run(sample);
 }
setDecimFilters()
void AudioFilter::setDecimFilters (int srHigh, int srLow, float fcHigh, float fcLow, float gain = 1.0f)
Definition at line 42 of file audiofilter.cpp.
References calculate2(), m_filterHP, m_filterLP, m_hpva, m_hpvb, m_lpva, m_lpvb, and IIRFilter< Type, Order >::setCoeffs().
Referenced by AudioResampler::setAudioFilters(), and AudioNetSink::setDecimationFilters().
 {
     double fcNormHigh = fcHigh / srHigh;
     double fcNormLow = fcLow / srLow;
     calculate2(false, fcNormHigh, m_lpva, m_lpvb, fgain);
     calculate2(true, fcNormLow, m_hpva, m_hpvb, fgain);
     m_filterLP.setCoeffs(m_lpva, m_lpvb);
     m_filterHP.setCoeffs(m_hpva, m_hpvb);
 }
useHP()
void AudioFilter::useHP (bool useHP) inline
Definition at line 49 of file audiofilter.h.
References useHP().
Referenced by useHP().
 { m_useHP = useHP; }
usesHP()
bool AudioFilter::usesHP () const inline
Definition at line 50 of file audiofilter.h.
References b1, and b2.
 { return m_useHP; }
Member Data Documentation
m_filterHP
IIRFilter<float, 2> AudioFilter::m_filterHP private
Definition at line 63 of file audiofilter.h.
Referenced by run(), runHP(), and setDecimFilters().
m_filterLP
IIRFilter<float, 2> AudioFilter::m_filterLP private
Definition at line 62 of file audiofilter.h.
Referenced by run(), runLP(), and setDecimFilters().
m_hpa
const float AudioFilter::m_hpa = {1.000000e+00, 1.667871e+00, -7.156964e-01} static private
Definition at line 71 of file audiofilter.h.
m_hpb
const float AudioFilter::m_hpb = {8.459039e-01, -1.691760e+00, 8.459039e-01} static private
Definition at line 72 of file audiofilter.h.
m_hpva
float AudioFilter::m_hpva[3] private
Definition at line 67 of file audiofilter.h.
Referenced by setDecimFilters().
m_hpvb
float AudioFilter::m_hpvb[3] private
Definition at line 68 of file audiofilter.h.
Referenced by setDecimFilters().
m_lpa
const float AudioFilter::m_lpa = {1.0, 1.392667E+00, -5.474446E-01} static private
Definition at line 69 of file audiofilter.h.
m_lpb
const float AudioFilter::m_lpb = {3.869430E-02, 7.738860E-02, 3.869430E-02} static private
Definition at line 70 of file audiofilter.h.
m_lpva
float AudioFilter::m_lpva[3] private
Definition at line 65 of file audiofilter.h.
Referenced by setDecimFilters().
m_lpvb
float AudioFilter::m_lpvb[3] private
Definition at line 66 of file audiofilter.h.
Referenced by setDecimFilters().
m_useHP
bool AudioFilter::m_useHP private
Definition at line 64 of file audiofilter.h.
Referenced by run().
The documentation for this class was generated from the following files:
sdrbase/audio/audiofilter.h
sdrbase/audio/audiofilter.cpp