SDRAngel: NFMDemodGUI Class Reference
NFMDemodGUI Class Reference
#include <nfmdemodgui.h>
Public Slots
void channelMarkerChangedByCursor ()
void channelMarkerHighlightedByCursor ()
Public Member Functions
virtual void destroy ()
void setName (const QString &name)
QString getName () const
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
void setCtcssFreq (Real ctcssFreq)
Public Member Functions inherited from RollupWidget
RollupWidget (QWidget *parent=NULL)
void setTitleColor (const QColor &c)
void setHighlighted (bool highlighted)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Static Public Member Functions
static NFMDemodGUI * create (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
Private Slots
void on_deltaFrequency_changed (qint64 value)
void on_rfBW_currentIndexChanged (int index)
void on_afBW_valueChanged (int value)
void on_volume_valueChanged (int value)
void on_squelchGate_valueChanged (int value)
void on_deltaSquelch_toggled (bool checked)
void on_squelch_valueChanged (int value)
void on_ctcss_currentIndexChanged (int index)
void on_ctcssOn_toggled (bool checked)
void on_highPassFilter_toggled (bool checked)
void on_audioMute_toggled (bool checked)
void onWidgetRolled (QWidget *widget, bool rollDown)
void onMenuDialogCalled (const QPoint &p)
void handleInputMessages ()
void audioSelect ()
void tick ()
Private Member Functions
NFMDemodGUI (PluginAPI *pluginAPI, DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel, QWidget *parent=0)
virtual ~NFMDemodGUI ()
void blockApplySettings (bool block)
void applySettings (bool force=false)
void displaySettings ()
void leaveEvent (QEvent *)
void enterEvent (QEvent *)
Private Attributes
Ui::NFMDemodGUI * ui
PluginAPI * m_pluginAPI
DeviceUISet * m_deviceUISet
ChannelMarker m_channelMarker
NFMDemodSettings m_settings
bool m_basicSettingsShown
bool m_doApplySettings
NFMDemod * m_nfmDemod
bool m_squelchOpen
uint32_t m_tickCount
MessageQueue m_inputMessageQueue
Additional Inherited Members
Signals inherited from RollupWidget
void widgetRolled (QWidget *widget, bool rollDown)
Protected Types inherited from RollupWidget
enum { VersionMarker = 0xff }
enum ContextMenuType { ContextMenuNone, ContextMenuChannelSettings, ContextMenuStreamSettings }
Protected Member Functions inherited from RollupWidget
int arrangeRollups ()
QByteArray saveState (int version=0) const
bool restoreState (const QByteArray &state, int version=0)
void paintEvent (QPaintEvent *)
int paintRollup (QWidget *rollup, int pos, QPainter *p, bool last, const QColor &frame)
void resizeEvent (QResizeEvent *size)
void mousePressEvent (QMouseEvent *event)
bool event (QEvent *event)
bool eventFilter (QObject *object, QEvent *event)
void resetContextMenuType ()
void setStreamIndicator (const QString &indicator)
Protected Attributes inherited from RollupWidget
QColor m_titleColor
QColor m_titleTextColor
bool m_highlighted
ContextMenuType m_contextMenuType
QString m_streamIndicator
Detailed Description
Definition at line 22 of file nfmdemodgui.h.
Constructor & Destructor Documentation
NFMDemodGUI()
NFMDemodGUI::NFMDemodGUI (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel, QWidget * parent = 0) explicit private
Definition at line 263 of file nfmdemodgui.cpp.
References DeviceUISet::addChannelMarker(), DeviceUISet::addRollupWidget(), applySettings(), arg(), audioSelect(), blockApplySettings(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), LevelMeterSignalDB::ColorGreenAndBlue, displaySettings(), NFMDemod::getCtcssToneSet(), getInputMessageQueue(), MainWindow::getInstance(), NFMDemodSettings::getRFBW(), ColorMapper::GrayGold, handleInputMessages(), i, NFMDemod::m_channelIdURI, m_channelMarker, m_deviceUISet, NFMDemodSettings::m_nbRfBW, m_nfmDemod, m_settings, onMenuDialogCalled(), onWidgetRolled(), DeviceUISet::registerRxChannelInstance(), ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), NFMDemodSettings::setChannelMarker(), ChannelMarker::setColor(), BasebandSampleSink::setMessageQueueToGUI(), ChannelMarker::setTitle(), ChannelMarker::setVisible(), tick(), ui, and RollupWidget::widgetRolled().
Referenced by create().
                                                                                                                        :
     RollupWidget(parent),
     ui(new Ui::NFMDemodGUI),
     m_pluginAPI(pluginAPI),
     m_deviceUISet(deviceUISet),
     m_channelMarker(this),
     m_basicSettingsShown(false),
     m_doApplySettings(true),
     m_squelchOpen(false),
     m_tickCount(0)
 {
     ui->setupUi(this);
     setAttribute(Qt::WA_DeleteOnClose, true);
     connect(this, SIGNAL(widgetRolled(QWidget*,bool)), this, SLOT(onWidgetRolled(QWidget*,bool)));
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)), this, SLOT(onMenuDialogCalled(const QPoint &)));
     m_nfmDemod = reinterpret_cast<NFMDemod*>(rxChannel); //new NFMDemod(m_deviceUISet->m_deviceSourceAPI);
     m_nfmDemod->setMessageQueueToGUI(getInputMessageQueue());
     connect(&MainWindow::getInstance()->getMasterTimer(), SIGNAL(timeout()), this, SLOT(tick()));
     CRightClickEnabler *audioMuteRightClickEnabler = new CRightClickEnabler(ui->audioMute);
     connect(audioMuteRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(audioSelect()));
     blockApplySettings(true);
     ui->rfBW->clear();
     for (int i = 0; i < NFMDemodSettings::m_nbRfBW; i++) {
         ui->rfBW->addItem(QString("%1").arg(NFMDemodSettings::getRFBW(i) / 1000.0, 0, 'f', 2));
     }
     int ctcss_nbTones;
     const Real *ctcss_tones = m_nfmDemod->getCtcssToneSet(ctcss_nbTones);
     ui->ctcss->addItem("--");
     for (int i=0; i<ctcss_nbTones; i++)
     {
         ui->ctcss->addItem(QString("%1").arg(ctcss_tones[i]));
     }
     blockApplySettings(false);
     ui->audioMute->setStyleSheet("QToolButton { background:rgb(79,79,79); }"); // squelch closed
     ui->deltaFrequencyLabel->setText(QString("%1f").arg(QChar(0x94, 0x03)));
     ui->deltaFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->deltaFrequency->setValueRange(false, 7, -9999999, 9999999);
     ui->channelPowerMeter->setColorTheme(LevelMeterSignalDB::ColorGreenAndBlue);
     m_channelMarker.blockSignals(true);
     m_channelMarker.setColor(Qt::red);
     m_channelMarker.setBandwidth(5000);
     m_channelMarker.setCenterFrequency(0);
     m_channelMarker.setTitle("NFM Demodulator");
     m_channelMarker.blockSignals(false);
     m_channelMarker.setVisible(true); // activate signal on the last setting only
     m_settings.setChannelMarker(&m_channelMarker);
     m_deviceUISet->registerRxChannelInstance(NFMDemod::m_channelIdURI, this);
     m_deviceUISet->addChannelMarker(&m_channelMarker);
     m_deviceUISet->addRollupWidget(this);
     connect(&m_channelMarker, SIGNAL(changedByCursor()), this, SLOT(channelMarkerChangedByCursor()));
     connect(&m_channelMarker, SIGNAL(highlightedByCursor()), this, SLOT(channelMarkerHighlightedByCursor()));
     QChar delta = QChar(0x94, 0x03);
     ui->deltaSquelch->setText(delta);
     connect(getInputMessageQueue(), SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
     displaySettings();
     applySettings(true);
 }
~NFMDemodGUI()
NFMDemodGUI::~NFMDemodGUI () private virtual
Definition at line 341 of file nfmdemodgui.cpp.
References m_deviceUISet, m_nfmDemod, DeviceUISet::removeRxChannelInstance(), and ui.
 {
     m_deviceUISet->removeRxChannelInstance(this);
     delete m_nfmDemod; // TODO: check this: when the GUI closes it has to delete the demodulator
     delete ui;
 }
Member Function Documentation
applySettings()
void NFMDemodGUI::applySettings (bool force = false) private
Definition at line 348 of file nfmdemodgui.cpp.
References NFMDemod::MsgConfigureNFMDemod::create(), NFMDemod::MsgConfigureChannelizer::create(), ChannelMarker::getCenterFrequency(), BasebandSampleSink::getInputMessageQueue(), m_channelMarker, m_doApplySettings, m_nfmDemod, m_settings, and MessageQueue::push().
Referenced by audioSelect(), channelMarkerChangedByCursor(), deserialize(), NFMDemodGUI(), on_afBW_valueChanged(), on_audioMute_toggled(), on_ctcss_currentIndexChanged(), on_ctcssOn_toggled(), on_deltaFrequency_changed(), on_deltaSquelch_toggled(), on_highPassFilter_toggled(), on_rfBW_currentIndexChanged(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), and setCenterFrequency().
 {
     if (m_doApplySettings)
     {
         qDebug() << "NFMDemodGUI::applySettings";
         NFMDemod::MsgConfigureChannelizer* channelConfigMsg = NFMDemod::MsgConfigureChannelizer::create(
                 48000, m_channelMarker.getCenterFrequency());
         m_nfmDemod->getInputMessageQueue()->push(channelConfigMsg);
         NFMDemod::MsgConfigureNFMDemod* message = NFMDemod::MsgConfigureNFMDemod::create( m_settings, force);
         m_nfmDemod->getInputMessageQueue()->push(message);
     }
 }
audioSelect
void NFMDemodGUI::audioSelect () private slot
Definition at line 442 of file nfmdemodgui.cpp.
References applySettings(), DSPEngine::instance(), AudioSelectDialog::m_audioDeviceName, NFMDemodSettings::m_audioDeviceName, AudioSelectDialog::m_selected, and m_settings.
Referenced by NFMDemodGUI().
 {
     qDebug("NFMDemodGUI::audioSelect");
     AudioSelectDialog audioSelect(DSPEngine::instance()->getAudioDeviceManager(), m_settings.m_audioDeviceName);
     audioSelect.exec();
     if (audioSelect.m_selected)
     {
         m_settings.m_audioDeviceName = audioSelect.m_audioDeviceName;
         applySettings();
     }
 }
blockApplySettings()
void NFMDemodGUI::blockApplySettings (bool block) private
Definition at line 437 of file nfmdemodgui.cpp.
References m_doApplySettings.
Referenced by displaySettings(), handleMessage(), and NFMDemodGUI().
 {
     m_doApplySettings = !block;
 }
channelMarkerChangedByCursor
void NFMDemodGUI::channelMarkerChangedByCursor () slot
Definition at line 112 of file nfmdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, NFMDemodSettings::m_inputFrequencyOffset, m_settings, and ui.
Referenced by NFMDemodGUI().
 {
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
channelMarkerHighlightedByCursor
void NFMDemodGUI::channelMarkerHighlightedByCursor () slot
Definition at line 119 of file nfmdemodgui.cpp.
References ChannelMarker::getHighlighted(), m_channelMarker, and RollupWidget::setHighlighted().
Referenced by NFMDemodGUI().
 {
     setHighlighted(m_channelMarker.getHighlighted());
 }
create()
NFMDemodGUI * NFMDemodGUI::create (PluginAPI * pluginAPI, DeviceUISet * deviceUISet, BasebandSampleSink * rxChannel) static
Definition at line 19 of file nfmdemodgui.cpp.
References NFMDemodGUI().
Referenced by NFMPlugin::createRxChannelGUI().
 {
     NFMDemodGUI* gui = new NFMDemodGUI(pluginAPI, deviceUISet, rxChannel);
     return gui;
 }
deserialize()
bool NFMDemodGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 63 of file nfmdemodgui.cpp.
References applySettings(), NFMDemodSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         applySettings(true);
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void NFMDemodGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 25 of file nfmdemodgui.cpp.
 {
     delete this;
 }
displaySettings()
void NFMDemodGUI::displaySettings () private
Definition at line 363 of file nfmdemodgui.cpp.
References arg(), blockApplySettings(), ChannelMarker::getCenterFrequency(), NFMDemodSettings::getRFBWIndex(), ChannelMarker::getTitle(), NFMDemodSettings::m_afBandwidth, NFMDemodSettings::m_audioMute, m_channelMarker, NFMDemodSettings::m_ctcssIndex, NFMDemodSettings::m_ctcssOn, NFMDemodSettings::m_deltaSquelch, NFMDemodSettings::m_highPass, NFMDemodSettings::m_inputFrequencyOffset, NFMDemodSettings::m_rfBandwidth, NFMDemodSettings::m_rgbColor, m_settings, NFMDemodSettings::m_squelch, NFMDemodSettings::m_squelchGate, NFMDemodSettings::m_title, NFMDemodSettings::m_volume, ChannelMarker::setBandwidth(), ChannelMarker::setCenterFrequency(), ChannelMarker::setColor(), ChannelMarker::setTitle(), RollupWidget::setTitleColor(), and ui.
Referenced by deserialize(), handleMessage(), NFMDemodGUI(), and resetToDefaults().
 {
     m_channelMarker.blockSignals(true);
     m_channelMarker.setCenterFrequency(m_settings.m_inputFrequencyOffset);
     m_channelMarker.setBandwidth(m_settings.m_rfBandwidth);
     m_channelMarker.setTitle(m_settings.m_title);
     m_channelMarker.blockSignals(false);
     m_channelMarker.setColor(m_settings.m_rgbColor);
     setTitleColor(m_settings.m_rgbColor);
     setWindowTitle(m_channelMarker.getTitle());
     blockApplySettings(true);
     ui->deltaFrequency->setValue(m_channelMarker.getCenterFrequency());
     ui->rfBW->setCurrentIndex(NFMDemodSettings::getRFBWIndex(m_settings.m_rfBandwidth));
     ui->afBWText->setText(QString("%1 k").arg(m_settings.m_afBandwidth / 1000.0));
     ui->afBW->setValue(m_settings.m_afBandwidth / 1000.0);
     ui->volumeText->setText(QString("%1").arg(m_settings.m_volume, 0, 'f', 1));
     ui->volume->setValue(m_settings.m_volume * 10.0);
     ui->squelchGateText->setText(QString("%1").arg(m_settings.m_squelchGate * 10.0f, 0, 'f', 0));
     ui->squelchGate->setValue(m_settings.m_squelchGate);
     ui->deltaSquelch->setChecked(m_settings.m_deltaSquelch);
     ui->squelch->setValue(m_settings.m_squelch * 1.0);
     if (m_settings.m_deltaSquelch)
     {
         ui->squelchText->setText(QString("%1").arg((-m_settings.m_squelch) / 1.0, 0, 'f', 0));
         ui->squelchText->setToolTip(tr("Squelch AF balance threshold (%)"));
         ui->squelch->setToolTip(tr("Squelch AF balance threshold (%)"));
     }
     else
     {
         ui->squelchText->setText(QString("%1").arg(m_settings.m_squelch / 1.0, 0, 'f', 0));
         ui->squelchText->setToolTip(tr("Squelch power threshold (dB)"));
         ui->squelch->setToolTip(tr("Squelch power threshold (dB)"));
     }
     ui->ctcssOn->setChecked(m_settings.m_ctcssOn);
     ui->highPassFilter->setChecked(m_settings.m_highPass);
     ui->audioMute->setChecked(m_settings.m_audioMute);
     ui->ctcss->setCurrentIndex(m_settings.m_ctcssIndex);
     blockApplySettings(false);
 }
enterEvent()
void NFMDemodGUI::enterEvent (QEvent *) private
Definition at line 420 of file nfmdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(true);
 }
getCenterFrequency()
qint64 NFMDemodGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 40 of file nfmdemodgui.cpp.
References ChannelMarker::getCenterFrequency(), and m_channelMarker.
 {
     return m_channelMarker.getCenterFrequency();
 }
getInputMessageQueue()
virtual MessageQueue* NFMDemodGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 37 of file nfmdemodgui.h.
Referenced by handleInputMessages(), and NFMDemodGUI().
 { return &m_inputMessageQueue; }
getName()
QString NFMDemodGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 35 of file nfmdemodgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void NFMDemodGUI::handleInputMessages () private slot
Definition at line 99 of file nfmdemodgui.cpp.
References getInputMessageQueue(), and handleMessage().
Referenced by NFMDemodGUI().
 {
     Message* message;
     while ((message = getInputMessageQueue()->pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
bool NFMDemodGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 75 of file nfmdemodgui.cpp.
References blockApplySettings(), displaySettings(), NFMDemod::MsgReportCTCSSFreq::getFrequency(), NFMDemod::MsgConfigureNFMDemod::getSettings(), m_settings, Message::match(), and setCtcssFreq().
Referenced by handleInputMessages().
 {
     if (NFMDemod::MsgReportCTCSSFreq::match(message))
     {
         //qDebug("NFMDemodGUI::handleMessage: NFMDemod::MsgReportCTCSSFreq");
         NFMDemod::MsgReportCTCSSFreq& report = (NFMDemod::MsgReportCTCSSFreq&) message;
         setCtcssFreq(report.getFrequency());
         //qDebug("NFMDemodGUI::handleMessage: MsgReportCTCSSFreq: %f", report.getFrequency());
         return true;
     }
     else if (NFMDemod::MsgConfigureNFMDemod::match(message))
     {
         qDebug("NFMDemodGUI::handleMessage: NFMDemod::MsgConfigureNFMDemod");
         const NFMDemod::MsgConfigureNFMDemod& cfg = (NFMDemod::MsgConfigureNFMDemod&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     return false;
 }
leaveEvent()
void NFMDemodGUI::leaveEvent (QEvent *) private
Definition at line 415 of file nfmdemodgui.cpp.
References m_channelMarker, and ChannelMarker::setHighlighted().
 {
     m_channelMarker.setHighlighted(false);
 }
on_afBW_valueChanged
void NFMDemodGUI::on_afBW_valueChanged (int value) private slot
Definition at line 141 of file nfmdemodgui.cpp.
References applySettings(), arg(), NFMDemodSettings::m_afBandwidth, m_settings, and ui.
 {
     ui->afBWText->setText(QString("%1 k").arg(value));
     m_settings.m_afBandwidth = value * 1000.0;
     applySettings();
 }
on_audioMute_toggled
void NFMDemodGUI::on_audioMute_toggled (bool checked) private slot
Definition at line 210 of file nfmdemodgui.cpp.
References applySettings(), NFMDemodSettings::m_audioMute, and m_settings.
 {
     m_settings.m_audioMute = checked;
     applySettings();
 }
on_ctcss_currentIndexChanged
void NFMDemodGUI::on_ctcss_currentIndexChanged (int index) private slot
Definition at line 216 of file nfmdemodgui.cpp.
References applySettings(), NFMDemodSettings::m_ctcssIndex, and m_settings.
 {
     m_settings.m_ctcssIndex = index;
     applySettings();
 }
on_ctcssOn_toggled
void NFMDemodGUI::on_ctcssOn_toggled (bool checked) private slot
Definition at line 198 of file nfmdemodgui.cpp.
References applySettings(), NFMDemodSettings::m_ctcssOn, and m_settings.
 {
     m_settings.m_ctcssOn = checked;
     applySettings();
 }
on_deltaFrequency_changed
void NFMDemodGUI::on_deltaFrequency_changed (qint64 value) private slot
Definition at line 124 of file nfmdemodgui.cpp.
References applySettings(), ChannelMarker::getCenterFrequency(), m_channelMarker, NFMDemodSettings::m_inputFrequencyOffset, m_settings, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(value);
     m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
     applySettings();
 }
on_deltaSquelch_toggled
void NFMDemodGUI::on_deltaSquelch_toggled (bool checked) private slot
Definition at line 162 of file nfmdemodgui.cpp.
References applySettings(), arg(), NFMDemodSettings::m_deltaSquelch, m_settings, and ui.
 {
     if (checked)
     {
         ui->squelchText->setText(QString("%1").arg((-ui->squelch->value()) / 1.0, 0, 'f', 0));
         ui->squelchText->setToolTip(tr("Squelch AF balance threshold (%)"));
         ui->squelch->setToolTip(tr("Squelch AF balance threshold (%)"));
     }
     else
     {
         ui->squelchText->setText(QString("%1").arg(ui->squelch->value() / 1.0, 0, 'f', 0));
         ui->squelchText->setToolTip(tr("Squelch power threshold (dB)"));
         ui->squelch->setToolTip(tr("Squelch power threshold (dB)"));
     }
     m_settings.m_deltaSquelch = checked;
     applySettings();
 }
on_highPassFilter_toggled
void NFMDemodGUI::on_highPassFilter_toggled (bool checked) private slot
Definition at line 204 of file nfmdemodgui.cpp.
References applySettings(), NFMDemodSettings::m_highPass, and m_settings.
 {
     m_settings.m_highPass = checked;
     applySettings();
 }
on_rfBW_currentIndexChanged
void NFMDemodGUI::on_rfBW_currentIndexChanged (int index) private slot
Definition at line 131 of file nfmdemodgui.cpp.
References applySettings(), NFMDemodSettings::getFMDev(), NFMDemodSettings::getRFBW(), m_channelMarker, NFMDemodSettings::m_fmDeviation, NFMDemodSettings::m_rfBandwidth, m_settings, and ChannelMarker::setBandwidth().
 {
     qDebug() << "NFMDemodGUI::on_rfBW_currentIndexChanged" << index;
     //ui->rfBWText->setText(QString("%1 k").arg(m_rfBW[value] / 1000.0));
     m_channelMarker.setBandwidth(NFMDemodSettings::getRFBW(index));
     m_settings.m_rfBandwidth = NFMDemodSettings::getRFBW(index);
     m_settings.m_fmDeviation = NFMDemodSettings::getFMDev(index);
     applySettings();
 }
on_squelch_valueChanged
void NFMDemodGUI::on_squelch_valueChanged (int value) private slot
Definition at line 180 of file nfmdemodgui.cpp.
References applySettings(), arg(), m_settings, NFMDemodSettings::m_squelch, and ui.
 {
     if (ui->deltaSquelch->isChecked())
     {
         ui->squelchText->setText(QString("%1").arg(-value / 1.0, 0, 'f', 0));
         ui->squelchText->setToolTip(tr("Squelch AF balance threshold (%)"));
         ui->squelch->setToolTip(tr("Squelch AF balance threshold (%)"));
     }
     else
     {
         ui->squelchText->setText(QString("%1").arg(value / 1.0, 0, 'f', 0));
         ui->squelchText->setToolTip(tr("Squelch power threshold (dB)"));
         ui->squelch->setToolTip(tr("Squelch power threshold (dB)"));
     }
     m_settings.m_squelch = value * 1.0;
     applySettings();
 }
on_squelchGate_valueChanged
void NFMDemodGUI::on_squelchGate_valueChanged (int value) private slot
Definition at line 155 of file nfmdemodgui.cpp.
References applySettings(), arg(), m_settings, NFMDemodSettings::m_squelchGate, and ui.
 {
     ui->squelchGateText->setText(QString("%1").arg(value * 10.0f, 0, 'f', 0));
     m_settings.m_squelchGate = value;
     applySettings();
 }
on_volume_valueChanged
void NFMDemodGUI::on_volume_valueChanged (int value) private slot
Definition at line 148 of file nfmdemodgui.cpp.
References applySettings(), arg(), m_settings, NFMDemodSettings::m_volume, and ui.
 {
     ui->volumeText->setText(QString("%1").arg(value / 10.0, 0, 'f', 1));
     m_settings.m_volume = value / 10.0;
     applySettings();
 }
onMenuDialogCalled
void NFMDemodGUI::onMenuDialogCalled (const QPoint & p) private slot
Definition at line 232 of file nfmdemodgui.cpp.
References applySettings(), RollupWidget::ContextMenuChannelSettings, ChannelMarker::getCenterFrequency(), ChannelMarker::getColor(), BasicChannelSettingsDialog::getReverseAPIAddress(), BasicChannelSettingsDialog::getReverseAPIChannelIndex(), BasicChannelSettingsDialog::getReverseAPIDeviceIndex(), BasicChannelSettingsDialog::getReverseAPIPort(), ChannelMarker::getTitle(), m_channelMarker, RollupWidget::m_contextMenuType, NFMDemodSettings::m_inputFrequencyOffset, NFMDemodSettings::m_reverseAPIAddress, NFMDemodSettings::m_reverseAPIChannelIndex, NFMDemodSettings::m_reverseAPIDeviceIndex, NFMDemodSettings::m_reverseAPIPort, NFMDemodSettings::m_rgbColor, m_settings, NFMDemodSettings::m_title, NFMDemodSettings::m_useReverseAPI, RollupWidget::resetContextMenuType(), BasicChannelSettingsDialog::setReverseAPIAddress(), BasicChannelSettingsDialog::setReverseAPIChannelIndex(), BasicChannelSettingsDialog::setReverseAPIDeviceIndex(), BasicChannelSettingsDialog::setReverseAPIPort(), RollupWidget::setTitleColor(), BasicChannelSettingsDialog::setUseReverseAPI(), and BasicChannelSettingsDialog::useReverseAPI().
Referenced by NFMDemodGUI().
 {
     if (m_contextMenuType == ContextMenuChannelSettings)
     {
         BasicChannelSettingsDialog dialog(&m_channelMarker, this);
         dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
         dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
         dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
         dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
         dialog.setReverseAPIChannelIndex(m_settings.m_reverseAPIChannelIndex);
         dialog.move(p);
         dialog.exec();
         m_settings.m_inputFrequencyOffset = m_channelMarker.getCenterFrequency();
         m_settings.m_rgbColor = m_channelMarker.getColor().rgb();
         m_settings.m_title = m_channelMarker.getTitle();
         m_settings.m_useReverseAPI = dialog.useReverseAPI();
         m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
         m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
         m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
         m_settings.m_reverseAPIChannelIndex = dialog.getReverseAPIChannelIndex();
         setWindowTitle(m_settings.m_title);
         setTitleColor(m_settings.m_rgbColor);
         applySettings();
     }
     resetContextMenuType();
 }
onWidgetRolled
void NFMDemodGUI::onWidgetRolled (QWidget * widget, bool rollDown) private slot
Definition at line 222 of file nfmdemodgui.cpp.
Referenced by NFMDemodGUI().
 {
     (void) widget;
     (void) rollDown;
     /*
     if((widget == ui->spectrumContainer) && (m_nfmDemod != NULL))
         m_nfmDemod->setSpectrum(m_threadedSampleSink->getMessageQueue(), rollDown);
     */
 }
resetToDefaults()
void NFMDemodGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 51 of file nfmdemodgui.cpp.
References applySettings(), displaySettings(), m_settings, and NFMDemodSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings();
 }
serialize()
QByteArray NFMDemodGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 58 of file nfmdemodgui.cpp.
References m_settings, and NFMDemodSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void NFMDemodGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 45 of file nfmdemodgui.cpp.
References applySettings(), m_channelMarker, and ChannelMarker::setCenterFrequency().
 {
     m_channelMarker.setCenterFrequency(centerFrequency);
     applySettings();
 }
setCtcssFreq()
void NFMDemodGUI::setCtcssFreq (Real ctcssFreq)
Definition at line 425 of file nfmdemodgui.cpp.
References arg(), and ui.
Referenced by handleMessage().
 {
     if (ctcssFreq == 0)
     {
         ui->ctcssText->setText("--");
     }
     else
     {
         ui->ctcssText->setText(QString("%1").arg(ctcssFreq));
     }
 }
setName()
void NFMDemodGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 30 of file nfmdemodgui.cpp.
 {
     setObjectName(name);
 }
tick
void NFMDemodGUI::tick () private slot
Definition at line 455 of file nfmdemodgui.cpp.
References arg(), CalcDb::dbPower(), NFMDemod::getMagSqLevels(), NFMDemod::getSquelchOpen(), m_nfmDemod, m_squelchOpen, m_tickCount, and ui.
Referenced by NFMDemodGUI().
 {
     double magsqAvg, magsqPeak;
     int nbMagsqSamples;
     m_nfmDemod->getMagSqLevels(magsqAvg, magsqPeak, nbMagsqSamples);
     double powDbAvg = CalcDb::dbPower(magsqAvg);
     double powDbPeak = CalcDb::dbPower(magsqPeak);
     ui->channelPowerMeter->levelChanged(
             (100.0f + powDbAvg) / 100.0f,
             (100.0f + powDbPeak) / 100.0f,
             nbMagsqSamples);
     if (m_tickCount % 4 == 0) {
         ui->channelPower->setText(tr("%1 dB").arg(powDbAvg, 0, 'f', 1));
     }
     bool squelchOpen = m_nfmDemod->getSquelchOpen();
     if (squelchOpen != m_squelchOpen)
     {
         if (squelchOpen) {
             ui->audioMute->setStyleSheet("QToolButton { background-color : green; }");
         } else {
             ui->audioMute->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
         }
         m_squelchOpen = squelchOpen;
     }
     m_tickCount++;
 }
Member Data Documentation
m_basicSettingsShown
bool NFMDemodGUI::m_basicSettingsShown private
Definition at line 51 of file nfmdemodgui.h.
m_channelMarker
ChannelMarker NFMDemodGUI::m_channelMarker private
Definition at line 49 of file nfmdemodgui.h.
Referenced by applySettings(), channelMarkerChangedByCursor(), channelMarkerHighlightedByCursor(), displaySettings(), enterEvent(), getCenterFrequency(), leaveEvent(), NFMDemodGUI(), on_deltaFrequency_changed(), on_rfBW_currentIndexChanged(), onMenuDialogCalled(), and setCenterFrequency().
m_deviceUISet
DeviceUISet* NFMDemodGUI::m_deviceUISet private
Definition at line 48 of file nfmdemodgui.h.
Referenced by NFMDemodGUI(), and ~NFMDemodGUI().
m_doApplySettings
bool NFMDemodGUI::m_doApplySettings private
Definition at line 52 of file nfmdemodgui.h.
Referenced by applySettings(), and blockApplySettings().
m_inputMessageQueue
MessageQueue NFMDemodGUI::m_inputMessageQueue private
Definition at line 57 of file nfmdemodgui.h.
m_nfmDemod
NFMDemod* NFMDemodGUI::m_nfmDemod private
Definition at line 54 of file nfmdemodgui.h.
Referenced by applySettings(), NFMDemodGUI(), tick(), and ~NFMDemodGUI().
m_pluginAPI
PluginAPI* NFMDemodGUI::m_pluginAPI private
Definition at line 47 of file nfmdemodgui.h.
m_settings
NFMDemodSettings NFMDemodGUI::m_settings private
Definition at line 50 of file nfmdemodgui.h.
Referenced by applySettings(), audioSelect(), channelMarkerChangedByCursor(), deserialize(), displaySettings(), handleMessage(), NFMDemodGUI(), on_afBW_valueChanged(), on_audioMute_toggled(), on_ctcss_currentIndexChanged(), on_ctcssOn_toggled(), on_deltaFrequency_changed(), on_deltaSquelch_toggled(), on_highPassFilter_toggled(), on_rfBW_currentIndexChanged(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_volume_valueChanged(), onMenuDialogCalled(), resetToDefaults(), and serialize().
m_squelchOpen
bool NFMDemodGUI::m_squelchOpen private
Definition at line 55 of file nfmdemodgui.h.
Referenced by tick().
m_tickCount
uint32_t NFMDemodGUI::m_tickCount private
Definition at line 56 of file nfmdemodgui.h.
Referenced by tick().
ui
Ui::NFMDemodGUI* NFMDemodGUI::ui private
Definition at line 46 of file nfmdemodgui.h.
Referenced by channelMarkerChangedByCursor(), displaySettings(), NFMDemodGUI(), on_afBW_valueChanged(), on_deltaSquelch_toggled(), on_squelch_valueChanged(), on_squelchGate_valueChanged(), on_volume_valueChanged(), setCtcssFreq(), tick(), and ~NFMDemodGUI().
The documentation for this class was generated from the following files:
plugins/channelrx/demodnfm/nfmdemodgui.h
plugins/channelrx/demodnfm/nfmdemodgui.cpp