SDRAngel: CWKeyerGUI Class Reference
CWKeyerGUI Class Reference
#include <cwkeyergui.h>
Public Member Functions
CWKeyerGUI (QWidget *parent=nullptr)
~CWKeyerGUI ()
void setCWKeyer (CWKeyer *cwKeyer)
void resetToDefaults ()
QByteArray serialize () const
bool deserialize (const QByteArray &data)
void setSettings (const CWKeyerSettings &settings)
void displaySettings ()
Public Member Functions inherited from Serializable
virtual ~Serializable ()
Private Types
enum KeyScope { NoKeyScope, DotKeyScope, DashKeyScope }
Private Slots
void on_cwTextClear_clicked (bool checked)
void on_cwTextEdit_editingFinished ()
void on_cwSpeed_valueChanged (int value)
void on_playDots_toggled (bool checked)
void on_playDashes_toggled (bool checked)
void on_playText_toggled (bool checked)
void on_playLoopCW_toggled (bool checked)
void on_playStop_toggled (bool checked)
void on_keyingStyle_toggled (bool checked)
void on_keyDotCapture_toggled (bool checked)
void on_keyDashCapture_toggled (bool checked)
void on_keyboardKeyer_toggled (bool checked)
void commandKeyPressed (Qt::Key key, Qt::KeyboardModifiers keyModifiers, bool release)
void keyboardKeyPressed (Qt::Key key, Qt::KeyboardModifiers keyModifiers, bool release)
Private Member Functions
void applySettings (bool force=false)
void blockApplySettings (bool block)
void setKeyLabel (QLabel *label, Qt::Key key, Qt::KeyboardModifiers keyModifiers)
Private Attributes
Ui::CWKeyerGUI * ui
CWKeyer * m_cwKeyer
CWKeyerSettings m_settings
bool m_doApplySettings
CommandKeyReceiver * m_commandKeyReceiver
KeyScope m_keyScope
Detailed Description
Definition at line 38 of file cwkeyergui.h.
Member Enumeration Documentation
KeyScope
enum CWKeyerGUI::KeyScope private
Enumerator
NoKeyScope
DotKeyScope
DashKeyScope
Definition at line 55 of file cwkeyergui.h.
     {
         NoKeyScope,
         DotKeyScope,
         DashKeyScope
     };
Constructor & Destructor Documentation
CWKeyerGUI()
CWKeyerGUI::CWKeyerGUI (QWidget * parent = nullptr) explicit
Definition at line 30 of file cwkeyergui.cpp.
References m_commandKeyReceiver, CommandKeyReceiver::setRelease(), and ui.
                                       :
     QWidget(parent),
     ui(new Ui::CWKeyerGUI),
     m_cwKeyer(nullptr),
     m_doApplySettings(true),
     m_keyScope(NoKeyScope)
 {
     ui->setupUi(this);
     m_commandKeyReceiver = new CommandKeyReceiver();
     m_commandKeyReceiver->setRelease(true);
     this->installEventFilter(m_commandKeyReceiver);
 }
~CWKeyerGUI()
CWKeyerGUI::~CWKeyerGUI ()
Definition at line 43 of file cwkeyergui.cpp.
References m_commandKeyReceiver, and ui.
 {
     this->releaseKeyboard(); // just in case
     m_commandKeyReceiver->deleteLater();
     delete ui;
 }
Member Function Documentation
applySettings()
void CWKeyerGUI::applySettings (bool force = false) private
Definition at line 290 of file cwkeyergui.cpp.
References CWKeyer::MsgConfigureCWKeyer::create(), CWKeyer::getInputMessageQueue(), m_cwKeyer, m_doApplySettings, m_settings, and MessageQueue::push().
Referenced by commandKeyPressed(), deserialize(), on_cwSpeed_valueChanged(), on_cwTextClear_clicked(), on_cwTextEdit_editingFinished(), on_keyboardKeyer_toggled(), on_keyingStyle_toggled(), on_playDashes_toggled(), on_playDots_toggled(), on_playLoopCW_toggled(), on_playText_toggled(), and resetToDefaults().
 {
     if (m_doApplySettings && m_cwKeyer)
     {
         CWKeyer::MsgConfigureCWKeyer* message = CWKeyer::MsgConfigureCWKeyer::create(m_settings, force);
         m_cwKeyer->getInputMessageQueue()->push(message);
     }
 }
blockApplySettings()
void CWKeyerGUI::blockApplySettings (bool block) private
Definition at line 346 of file cwkeyergui.cpp.
References m_doApplySettings.
Referenced by displaySettings().
 {
     m_doApplySettings = !block;
 }
commandKeyPressed
void CWKeyerGUI::commandKeyPressed (Qt::Key key, Qt::KeyboardModifiers keyModifiers, bool release) private slot
Definition at line 221 of file cwkeyergui.cpp.
References applySettings(), DashKeyScope, DotKeyScope, m_commandKeyReceiver, CWKeyerSettings::m_dashKey, CWKeyerSettings::m_dashKeyModifiers, CWKeyerSettings::m_dotKey, CWKeyerSettings::m_dotKeyModifiers, m_keyScope, m_settings, setKeyLabel(), CommandKeyReceiver::setRelease(), and ui.
Referenced by on_keyDashCapture_toggled(), and on_keyDotCapture_toggled().
 {
     (void) release;
     // qDebug("CWKeyerGUI::commandKeyPressed: key scope: %d", (int) m_keyScope);
     // qDebug("CWKeyerGUI::commandKeyPressed: key: %x", key);
     // qDebug("CWKeyerGUI::commandKeyPressed: has modifiers: %x", QFlags<Qt::KeyboardModifier>::Int(keyModifiers));
     if (m_keyScope == DotKeyScope)
     {
         setKeyLabel(ui->keyDotLabel, key, keyModifiers);
         ui->keyDotCapture->setChecked(false);
         m_settings.m_dotKey = key;
         m_settings.m_dotKeyModifiers = keyModifiers;
         applySettings();
     }
     else if (m_keyScope == DashKeyScope)
     {
         setKeyLabel(ui->keyDashLabel, key, keyModifiers);
         ui->keyDashCapture->setChecked(false);
         m_settings.m_dashKey = key;
         m_settings.m_dashKeyModifiers = keyModifiers;
         applySettings();
     }
     m_commandKeyReceiver->setRelease(true);
 }
deserialize()
bool CWKeyerGUI::deserialize (const QByteArray & data) virtual
Implements Serializable.
Definition at line 69 of file cwkeyergui.cpp.
References applySettings(), CWKeyerSettings::deserialize(), displaySettings(), m_settings, and resetToDefaults().
 {
     if (m_settings.deserialize(data))
     {
         displaySettings();
         applySettings(true);
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
displaySettings()
void CWKeyerGUI::displaySettings ()
Definition at line 299 of file cwkeyergui.cpp.
References arg(), blockApplySettings(), CWKeyerSettings::CWDashes, CWKeyerSettings::CWDots, CWKeyerSettings::CWKeyboard, CWKeyerSettings::CWNone, CWKeyerSettings::CWText, CWKeyerSettings::m_dashKey, CWKeyerSettings::m_dashKeyModifiers, CWKeyerSettings::m_dotKey, CWKeyerSettings::m_dotKeyModifiers, CWKeyerSettings::m_keyboardIambic, CWKeyerSettings::m_loop, CWKeyerSettings::m_mode, m_settings, CWKeyerSettings::m_text, CWKeyerSettings::m_wpm, setKeyLabel(), and ui.
Referenced by deserialize(), resetToDefaults(), and setCWKeyer().
 {
     blockApplySettings(true);
     ui->playLoopCW->setChecked(m_settings.m_loop);
     ui->playDots->setEnabled((m_settings.m_mode == CWKeyerSettings::CWDots) || (m_settings.m_mode == CWKeyerSettings::CWNone));
     ui->playDots->setChecked(m_settings.m_mode == CWKeyerSettings::CWDots);
     ui->playDashes->setEnabled((m_settings.m_mode == CWKeyerSettings::CWDashes) || (m_settings.m_mode == CWKeyerSettings::CWNone));
     ui->playDashes->setChecked(m_settings.m_mode == CWKeyerSettings::CWDashes);
     ui->playText->setEnabled((m_settings.m_mode == CWKeyerSettings::CWText) || (m_settings.m_mode == CWKeyerSettings::CWNone));
     ui->playText->setChecked(m_settings.m_mode == CWKeyerSettings::CWText);
     ui->keyboardKeyer->setEnabled((m_settings.m_mode == CWKeyerSettings::CWKeyboard) || (m_settings.m_mode == CWKeyerSettings::CWNone));
     ui->keyboardKeyer->setChecked(m_settings.m_mode == CWKeyerSettings::CWKeyboard);
     ui->cwTextEdit->setText(m_settings.m_text);
     ui->cwSpeed->setValue(m_settings.m_wpm);
     ui->cwSpeedText->setText(QString("%1").arg(m_settings.m_wpm));
     ui->keyingStyle->setChecked(!m_settings.m_keyboardIambic);
     setKeyLabel(ui->keyDotLabel, m_settings.m_dotKey, m_settings.m_dotKeyModifiers);
     setKeyLabel(ui->keyDashLabel, m_settings.m_dashKey, m_settings.m_dashKeyModifiers);
     blockApplySettings(false);
 }
keyboardKeyPressed
void CWKeyerGUI::keyboardKeyPressed (Qt::Key key, Qt::KeyboardModifiers keyModifiers, bool release) private slot
Definition at line 264 of file cwkeyergui.cpp.
References CWKeyer::getSettings(), m_cwKeyer, CWKeyerSettings::m_dashKey, CWKeyerSettings::m_dashKeyModifiers, CWKeyerSettings::m_dotKey, CWKeyerSettings::m_dotKeyModifiers, CWKeyer::setKeyboardDashes(), CWKeyer::setKeyboardDots(), and CWKeyer::setKeyboardSilence().
Referenced by on_keyboardKeyer_toggled().
 {
     const CWKeyerSettings& settings = m_cwKeyer->getSettings();
     if ((key == settings.m_dotKey) && (keyModifiers == settings.m_dotKeyModifiers))
     {
         qDebug("CWKeyerGUI::keyboardKeyPressed: dot %s", release ? "released" : "pressed");
         if (release) {
             m_cwKeyer->setKeyboardSilence();
         } else {
             m_cwKeyer->setKeyboardDots();
         }
     }
     else if ((key == settings.m_dashKey) && (keyModifiers == settings.m_dashKeyModifiers))
     {
         qDebug("CWKeyerGUI::keyboardKeyPressed: dash %s", release ? "released" : "pressed");
         if (release) {
             m_cwKeyer->setKeyboardSilence();
         } else {
             m_cwKeyer->setKeyboardDashes();
         }
     }
 }
on_cwSpeed_valueChanged
void CWKeyerGUI::on_cwSpeed_valueChanged (int value) private slot
Definition at line 100 of file cwkeyergui.cpp.
References applySettings(), arg(), m_settings, CWKeyerSettings::m_wpm, and ui.
 {
     ui->cwSpeedText->setText(QString("%1").arg(value));
     m_settings.m_wpm = value;
     applySettings();
 }
on_cwTextClear_clicked
void CWKeyerGUI::on_cwTextClear_clicked (bool checked) private slot
Definition at line 86 of file cwkeyergui.cpp.
References applySettings(), m_settings, CWKeyerSettings::m_text, and ui.
 {
     (void) checked;
     ui->cwTextEdit->clear();
     m_settings.m_text = "";
     applySettings();
 }
on_cwTextEdit_editingFinished
void CWKeyerGUI::on_cwTextEdit_editingFinished () private slot
Definition at line 94 of file cwkeyergui.cpp.
References applySettings(), m_settings, CWKeyerSettings::m_text, and ui.
 {
     m_settings.m_text = ui->cwTextEdit->text();
     applySettings();
 }
on_keyboardKeyer_toggled
void CWKeyerGUI::on_keyboardKeyer_toggled (bool checked) private slot
Definition at line 248 of file cwkeyergui.cpp.
References applySettings(), MainWindow::commandKeysConnect(), MainWindow::commandKeysDisconnect(), CWKeyerSettings::CWKeyboard, CWKeyerSettings::CWNone, MainWindow::getInstance(), keyboardKeyPressed(), CWKeyerSettings::m_mode, m_settings, and ui.
 {
     qDebug("CWKeyerGUI::on_keyboardKeyer_toggled: %s", checked ? "true" : "false");
     ui->playDots->setEnabled(!checked);   // block or release other source inputs
     ui->playDashes->setEnabled(!checked);
     ui->playText->setEnabled(!checked);
     m_settings.m_mode = checked ? CWKeyerSettings::CWKeyboard : CWKeyerSettings::CWNone;
     applySettings();
     if (checked) {
         MainWindow::getInstance()->commandKeysConnect(this, SLOT(keyboardKeyPressed(Qt::Key, Qt::KeyboardModifiers, bool)));
     } else {
         MainWindow::getInstance()->commandKeysDisconnect(this, SLOT(keyboardKeyPressed(Qt::Key, Qt::KeyboardModifiers, bool)));
     }
 }
on_keyDashCapture_toggled
void CWKeyerGUI::on_keyDashCapture_toggled (bool checked) private slot
Definition at line 192 of file cwkeyergui.cpp.
References commandKeyPressed(), DashKeyScope, m_commandKeyReceiver, m_keyScope, NoKeyScope, CommandKeyReceiver::setRelease(), and ui.
 {
     if (checked && ui->keyDotCapture->isChecked())
     {
         ui->keyDotCapture->setChecked(false);
         ui->keyDashCapture->setChecked(false);
         return;
     }
     if (checked)
     {
         m_keyScope = DashKeyScope;
         m_commandKeyReceiver->setRelease(false);
         setFocus();
         setFocusPolicy(Qt::StrongFocus);
         connect(m_commandKeyReceiver, SIGNAL(capturedKey(Qt::Key, Qt::KeyboardModifiers, bool)),
                         this, SLOT(commandKeyPressed(Qt::Key, Qt::KeyboardModifiers, bool)));
     }
     else
     {
         m_keyScope = NoKeyScope;
         m_commandKeyReceiver->setRelease(false);
         disconnect(m_commandKeyReceiver, SIGNAL(capturedKey(Qt::Key, Qt::KeyboardModifiers, bool)),
                         this, SLOT(commandKeyPressed(Qt::Key, Qt::KeyboardModifiers, bool)));
         setFocusPolicy(Qt::NoFocus);
         clearFocus();
     }
 }
on_keyDotCapture_toggled
void CWKeyerGUI::on_keyDotCapture_toggled (bool checked) private slot
Definition at line 165 of file cwkeyergui.cpp.
References commandKeyPressed(), DotKeyScope, m_commandKeyReceiver, m_keyScope, NoKeyScope, and ui.
 {
     if (checked && ui->keyDashCapture->isChecked())
     {
         ui->keyDotCapture->setChecked(false);
         ui->keyDashCapture->setChecked(false);
         return;
     }
     if (checked)
     {
         m_keyScope = DotKeyScope;
         setFocus();
         setFocusPolicy(Qt::StrongFocus);
         connect(m_commandKeyReceiver, SIGNAL(capturedKey(Qt::Key, Qt::KeyboardModifiers, bool)),
                         this, SLOT(commandKeyPressed(Qt::Key, Qt::KeyboardModifiers, bool)));
     }
     else
     {
         m_keyScope = NoKeyScope;
         disconnect(m_commandKeyReceiver, SIGNAL(capturedKey(Qt::Key, Qt::KeyboardModifiers, bool)),
                         this, SLOT(commandKeyPressed(Qt::Key, Qt::KeyboardModifiers, bool)));
         setFocusPolicy(Qt::NoFocus);
         clearFocus();
     }
 }
on_keyingStyle_toggled
void CWKeyerGUI::on_keyingStyle_toggled (bool checked) private slot
Definition at line 159 of file cwkeyergui.cpp.
References applySettings(), CWKeyerSettings::m_keyboardIambic, and m_settings.
 {
     m_settings.m_keyboardIambic = !checked;
     applySettings();
 }
on_playDashes_toggled
void CWKeyerGUI::on_playDashes_toggled (bool checked) private slot
Definition at line 117 of file cwkeyergui.cpp.
References applySettings(), CWKeyerSettings::CWDashes, CWKeyerSettings::CWNone, CWKeyerSettings::m_mode, m_settings, and ui.
 {
     ui->playDots->setEnabled(!checked); // release other source inputs
     //ui->playDashes->setEnabled(!checked);
     ui->playText->setEnabled(!checked);
     ui->keyboardKeyer->setEnabled(!checked);
     m_settings.m_mode = checked ? CWKeyerSettings::CWDashes : CWKeyerSettings::CWNone;
     applySettings();
 }
on_playDots_toggled
void CWKeyerGUI::on_playDots_toggled (bool checked) private slot
Definition at line 107 of file cwkeyergui.cpp.
References applySettings(), CWKeyerSettings::CWDots, CWKeyerSettings::CWNone, CWKeyerSettings::m_mode, m_settings, and ui.
 {
     //ui->playDots->setEnabled(!checked); // release other source inputs
     ui->playDashes->setEnabled(!checked);
     ui->playText->setEnabled(!checked);
     ui->keyboardKeyer->setEnabled(!checked);
     m_settings.m_mode = checked ? CWKeyerSettings::CWDots : CWKeyerSettings::CWNone;
     applySettings();
 }
on_playLoopCW_toggled
void CWKeyerGUI::on_playLoopCW_toggled (bool checked) private slot
Definition at line 144 of file cwkeyergui.cpp.
References applySettings(), CWKeyerSettings::m_loop, and m_settings.
 {
     m_settings.m_loop = checked;
     applySettings();
 }
on_playStop_toggled
void CWKeyerGUI::on_playStop_toggled (bool checked) private slot
Definition at line 150 of file cwkeyergui.cpp.
References m_cwKeyer, CWKeyer::resetText(), and CWKeyer::stopText().
 {
     if (checked) {
         m_cwKeyer->resetText();
     } else {
         m_cwKeyer->stopText();
     }
 }
on_playText_toggled
void CWKeyerGUI::on_playText_toggled (bool checked) private slot
Definition at line 127 of file cwkeyergui.cpp.
References applySettings(), CWKeyerSettings::CWNone, CWKeyerSettings::CWText, CWKeyerSettings::m_mode, m_settings, and ui.
 {
     ui->playDots->setEnabled(!checked); // release other source inputs
     ui->playDashes->setEnabled(!checked);
     //ui->playText->setEnabled(!checked);
     ui->keyboardKeyer->setEnabled(!checked);
     if (checked) {
         ui->playStop->setChecked(true);
     } else {
         ui->playStop->setChecked(false);
     }
     m_settings.m_mode = checked ? CWKeyerSettings::CWText : CWKeyerSettings::CWNone;
     applySettings();
 }
resetToDefaults()
void CWKeyerGUI::resetToDefaults ()
Definition at line 57 of file cwkeyergui.cpp.
References applySettings(), displaySettings(), m_settings, and CWKeyerSettings::resetToDefaults().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     applySettings(true);
 }
serialize()
QByteArray CWKeyerGUI::serialize () const virtual
Implements Serializable.
Definition at line 64 of file cwkeyergui.cpp.
References m_settings, and CWKeyerSettings::serialize().
 {
     return m_settings.serialize();
 }
setCWKeyer()
void CWKeyerGUI::setCWKeyer (CWKeyer * cwKeyer)
Definition at line 50 of file cwkeyergui.cpp.
References displaySettings(), CWKeyer::getSettings(), m_cwKeyer, and setSettings().
 {
     m_cwKeyer = cwKeyer;
     setSettings(cwKeyer->getSettings());
     displaySettings();
 }
setKeyLabel()
void CWKeyerGUI::setKeyLabel (QLabel * label, Qt::Key key, Qt::KeyboardModifiers keyModifiers) private
Definition at line 328 of file cwkeyergui.cpp.
Referenced by commandKeyPressed(), and displaySettings().
 {
     if (key == 0)
     {
         label->setText("");
     }
     else if (keyModifiers != Qt::NoModifier)
     {
         QString altGrStr = keyModifiers & Qt::GroupSwitchModifier ? "Gr " : "";
         int maskedModifiers = (keyModifiers & 0x3FFFFFFF) + ((keyModifiers & 0x40000000)>>3);
         label->setText(altGrStr + QKeySequence(maskedModifiers, key).toString());
     }
     else
     {
         label->setText(QKeySequence(key).toString());
     }
 }
setSettings()
void CWKeyerGUI::setSettings (const CWKeyerSettings & settings) inline
Definition at line 51 of file cwkeyergui.h.
Referenced by setCWKeyer().
 { m_settings = settings; }
Member Data Documentation
m_commandKeyReceiver
CommandKeyReceiver* CWKeyerGUI::m_commandKeyReceiver private
Definition at line 67 of file cwkeyergui.h.
Referenced by commandKeyPressed(), CWKeyerGUI(), on_keyDashCapture_toggled(), on_keyDotCapture_toggled(), and ~CWKeyerGUI().
m_cwKeyer
CWKeyer* CWKeyerGUI::m_cwKeyer private
Definition at line 64 of file cwkeyergui.h.
Referenced by applySettings(), keyboardKeyPressed(), on_playStop_toggled(), and setCWKeyer().
m_doApplySettings
bool CWKeyerGUI::m_doApplySettings private
Definition at line 66 of file cwkeyergui.h.
Referenced by applySettings(), and blockApplySettings().
m_keyScope
KeyScope CWKeyerGUI::m_keyScope private
Definition at line 68 of file cwkeyergui.h.
Referenced by commandKeyPressed(), on_keyDashCapture_toggled(), and on_keyDotCapture_toggled().
m_settings
CWKeyerSettings CWKeyerGUI::m_settings private
Definition at line 65 of file cwkeyergui.h.
Referenced by applySettings(), commandKeyPressed(), deserialize(), displaySettings(), on_cwSpeed_valueChanged(), on_cwTextClear_clicked(), on_cwTextEdit_editingFinished(), on_keyboardKeyer_toggled(), on_keyingStyle_toggled(), on_playDashes_toggled(), on_playDots_toggled(), on_playLoopCW_toggled(), on_playText_toggled(), resetToDefaults(), and serialize().
ui
Ui::CWKeyerGUI* CWKeyerGUI::ui private
Definition at line 62 of file cwkeyergui.h.
Referenced by commandKeyPressed(), CWKeyerGUI(), displaySettings(), on_cwSpeed_valueChanged(), on_cwTextClear_clicked(), on_cwTextEdit_editingFinished(), on_keyboardKeyer_toggled(), on_keyDashCapture_toggled(), on_keyDotCapture_toggled(), on_playDashes_toggled(), on_playDots_toggled(), on_playText_toggled(), and ~CWKeyerGUI().
The documentation for this class was generated from the following files:
sdrgui/gui/cwkeyergui.h
sdrgui/gui/cwkeyergui.cpp