SDRAngel: AudioInput Class Reference
AudioInput Class Reference
#include <audioinput.h>
Inherits QIODevice.
Public Member Functions
AudioInput ()
virtual ~AudioInput ()
bool start (int device, int rate)
void stop ()
void addFifo (AudioFifo *audioFifo)
void removeFifo (AudioFifo *audioFifo)
int getNbFifos () const
uint getRate () const
void setOnExit (bool onExit)
void setVolume (float volume)
Private Member Functions
virtual qint64 readData (char *data, qint64 maxLen)
virtual qint64 writeData (const char *data, qint64 len)
Private Attributes
QMutex m_mutex
QAudioInput * m_audioInput
uint m_audioUsageCount
bool m_onExit
float m_volume
std::list< AudioFifo * > m_audioFifos
std::vector< qint32 > m_mixBuffer
QAudioFormat m_audioFormat
Friends
class AudioOutputPipe
Detailed Description
Definition at line 33 of file audioinput.h.
Constructor & Destructor Documentation
AudioInput()
AudioInput::AudioInput ()
Definition at line 25 of file audioinput.cpp.
                        :
     m_mutex(QMutex::Recursive),
     m_audioInput(0),
     m_audioUsageCount(0),
     m_onExit(false),
     m_volume(0.5f),
     m_audioFifos()
 {
 }
~AudioInput()
AudioInput::~AudioInput () virtual
Definition at line 35 of file audioinput.cpp.
References m_audioFifos, m_mutex, and stop().
 {
     stop();
     QMutexLocker mutexLocker(&m_mutex);
     for (std::list<AudioFifo*>::iterator it = m_audioFifos.begin(); it != m_audioFifos.end(); ++it)
     {
         delete *it;
     }
     m_audioFifos.clear();
 }
Member Function Documentation
addFifo()
void AudioInput::addFifo (AudioFifo * audioFifo)
Definition at line 142 of file audioinput.cpp.
References m_audioFifos, and m_mutex.
Referenced by FCDProPlusInput::openFCDAudio(), and FCDProInput::openFCDAudio().
 {
     QMutexLocker mutexLocker(&m_mutex);
     m_audioFifos.push_back(audioFifo);
 }
getNbFifos()
int AudioInput::getNbFifos () const inline
Definition at line 43 of file audioinput.h.
 { return m_audioFifos.size(); }
getRate()
uint AudioInput::getRate () const inline
Definition at line 45 of file audioinput.h.
Referenced by FCDProPlusInput::openFCDAudio(), FCDProInput::openFCDAudio(), and AudioDeviceManager::setInputDeviceInfo().
 { return m_audioFormat.sampleRate(); }
readData()
qint64 AudioInput::readData (char * data, qint64 maxLen) private virtual
Definition at line 156 of file audioinput.cpp.
 {
     Q_UNUSED(data);
     Q_UNUSED(maxLen);
     return 0;
 }
removeFifo()
void AudioInput::removeFifo (AudioFifo * audioFifo)
Definition at line 149 of file audioinput.cpp.
References m_audioFifos, and m_mutex.
Referenced by FCDProPlusInput::closeFCDAudio(), and FCDProInput::closeFCDAudio().
 {
     QMutexLocker mutexLocker(&m_mutex);
     m_audioFifos.remove(audioFifo);
 }
setOnExit()
void AudioInput::setOnExit (bool onExit) inline
Definition at line 46 of file audioinput.h.
 { m_onExit = onExit; }
setVolume()
void AudioInput::setVolume (float volume) inline
Definition at line 47 of file audioinput.h.
Referenced by AudioDeviceManager::setInputDeviceInfo().
 { m_volume = volume; }
start()
bool AudioInput::start (int device, int rate)
Definition at line 49 of file audioinput.cpp.
References m_audioFormat, m_audioInput, m_audioUsageCount, m_mutex, and m_volume.
Referenced by FCDProPlusInput::openFCDAudio(), FCDProInput::openFCDAudio(), and AudioDeviceManager::setInputDeviceInfo().
 {
     if (m_audioUsageCount == 0)
     {
         QMutexLocker mutexLocker(&m_mutex);
         QAudioDeviceInfo devInfo;
         if (device < 0)
         {
             devInfo = QAudioDeviceInfo::defaultInputDevice();
             qWarning("AudioInput::start: using default device %s", qPrintable(devInfo.defaultInputDevice().deviceName()));
         }
         else
         {
             QList<QAudioDeviceInfo> devicesInfo = QAudioDeviceInfo::availableDevices(QAudio::AudioInput);
             if (device < devicesInfo.size())
             {
                 devInfo = devicesInfo[device];
                 qWarning("AudioInput::start: using audio device #%d: %s", device, qPrintable(devInfo.deviceName()));
             }
             else
             {
                 devInfo = QAudioDeviceInfo::defaultInputDevice();
                 qWarning("AudioInput::start: audio device #%d does not exist. Using default device %s", device, qPrintable(devInfo.deviceName()));
             }
         }
         //QAudioDeviceInfo devInfo(QAudioDeviceInfo::defaultOutputDevice());
         m_audioFormat.setSampleRate(rate);
         m_audioFormat.setChannelCount(2);
         m_audioFormat.setSampleSize(16);
         m_audioFormat.setCodec("audio/pcm");
         m_audioFormat.setByteOrder(QAudioFormat::LittleEndian);
         m_audioFormat.setSampleType(QAudioFormat::SignedInt); // Unknown, SignedInt, UnSignedInt, Float
         if (!devInfo.isFormatSupported(m_audioFormat))
         {
             m_audioFormat = devInfo.nearestFormat(m_audioFormat);
             qWarning("AudioInput::start: %d Hz S16_LE audio format not supported. Nearest is sampleRate: %d channelCount: %d sampleSize: %d sampleType: %d",
                     rate, m_audioFormat.sampleRate(), m_audioFormat.channelCount(), m_audioFormat.sampleSize(), (int) m_audioFormat.sampleType());
         }
         else
         {
             qInfo("AudioInput::start: audio format OK");
         }
         if (m_audioFormat.sampleSize() != 16)
         {
             qWarning("AudioInput::start: Audio device '%s' failed", qPrintable(devInfo.defaultInputDevice().deviceName()));
             return false;
         }
         m_audioInput = new QAudioInput(devInfo, m_audioFormat);
         m_audioInput->setVolume(m_volume);
         QIODevice::open(QIODevice::ReadWrite);
         m_audioInput->start(this);
         if (m_audioInput->state() != QAudio::ActiveState)
         {
             qWarning("AudioInput::start: cannot start");
         }
     }
     m_audioUsageCount++;
     return true;
 }
stop()
void AudioInput::stop ()
Definition at line 121 of file audioinput.cpp.
References m_audioInput, m_audioUsageCount, m_mutex, and m_onExit.
Referenced by FCDProPlusInput::closeFCDAudio(), FCDProInput::closeFCDAudio(), AudioDeviceManager::setInputDeviceInfo(), and ~AudioInput().
 {
     qDebug("AudioInput::stop");
     if (m_audioUsageCount > 0)
     {
         m_audioUsageCount--;
         if (m_audioUsageCount == 0)
         {
             qDebug("AudioInput::stop: effectively close QIODevice");
             QMutexLocker mutexLocker(&m_mutex);
             QIODevice::close();
             if (!m_onExit) {
                 delete m_audioInput;
             }
         }
     }
 }
writeData()
qint64 AudioInput::writeData (const char * data, qint64 len) private virtual
Definition at line 163 of file audioinput.cpp.
References m_audioFifos, and m_audioFormat.
 {
     // Study this mutex on OSX, for now deadlocks possible
     // Removed as it may indeed cause lockups and is in fact useless.
 //#ifndef __APPLE__
 //    QMutexLocker mutexLocker(&m_mutex);
 //#endif
     if ((m_audioFormat.sampleSize() != 16)
             || (m_audioFormat.sampleType() != QAudioFormat::SignedInt)
             || (m_audioFormat.byteOrder() != QAudioFormat::LittleEndian))
     {
         qCritical("AudioInput::writeData: invalid format not S16LE");
         return 0;
     }
     if (m_audioFormat.channelCount() != 2) {
         qCritical("AudioInput::writeData: invalid format not stereo");
         return 0;
     }
     for (std::list<AudioFifo*>::iterator it = m_audioFifos.begin(); it != m_audioFifos.end(); ++it)
     {
         (*it)->write(reinterpret_cast<const quint8*>(data), len/4);
     }
     return len;
 }
Friends And Related Function Documentation
AudioOutputPipe
friend class AudioOutputPipe friend
Definition at line 65 of file audioinput.h.
Member Data Documentation
m_audioFifos
std::list<AudioFifo*> AudioInput::m_audioFifos private
Definition at line 56 of file audioinput.h.
Referenced by addFifo(), removeFifo(), writeData(), and ~AudioInput().
m_audioFormat
QAudioFormat AudioInput::m_audioFormat private
Definition at line 59 of file audioinput.h.
Referenced by start(), and writeData().
m_audioInput
QAudioInput* AudioInput::m_audioInput private
Definition at line 51 of file audioinput.h.
Referenced by start(), and stop().
m_audioUsageCount
uint AudioInput::m_audioUsageCount private
Definition at line 52 of file audioinput.h.
Referenced by start(), and stop().
m_mixBuffer
std::vector<qint32> AudioInput::m_mixBuffer private
Definition at line 57 of file audioinput.h.
m_mutex
QMutex AudioInput::m_mutex private
Definition at line 50 of file audioinput.h.
Referenced by addFifo(), removeFifo(), start(), stop(), and ~AudioInput().
m_onExit
bool AudioInput::m_onExit private
Definition at line 53 of file audioinput.h.
Referenced by stop().
m_volume
float AudioInput::m_volume private
Definition at line 54 of file audioinput.h.
Referenced by start().
The documentation for this class was generated from the following files:
sdrbase/audio/audioinput.h
sdrbase/audio/audioinput.cpp