SDRAngel: FCDProPlusInput::MsgStartStop Class Reference
FCDProPlusInput::MsgStartStop Class Reference
#include <fcdproplusinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgStartStop * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgStartStop (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 71 of file fcdproplusinput.h.
Constructor & Destructor Documentation
MsgStartStop()
FCDProPlusInput::MsgStartStop::MsgStartStop (bool startStop) inline protected
Definition at line 84 of file fcdproplusinput.h.
                                      :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgStartStop* FCDProPlusInput::MsgStartStop::create (bool startStop) inline static
Definition at line 77 of file fcdproplusinput.h.
Referenced by FCDProPlusGui::on_startStop_toggled(), and FCDProPlusInput::webapiRun().
{
             return new MsgStartStop(startStop);
         }
getStartStop()
bool FCDProPlusInput::MsgStartStop::getStartStop () const inline
Definition at line 75 of file fcdproplusinput.h.
Referenced by FCDProPlusGui::handleMessage(), and FCDProPlusInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool FCDProPlusInput::MsgStartStop::m_startStop protected
Definition at line 82 of file fcdproplusinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/fcdproplus/fcdproplusinput.h