SDRAngel: SDRPlayIF Class Reference
SDRPlayIF Class Reference
#include <sdrplayinput.h>
Static Public Member Functions
static unsigned int getIF (unsigned int if_index)
static unsigned int getIFIndex (unsigned int iff)
static unsigned int getNbIFs ()
Static Private Attributes
static const unsigned int m_nb_if = 4
static unsigned int m_if [m_nb_if]
Detailed Description
Definition at line 232 of file sdrplayinput.h.
Member Function Documentation
getIF()
unsigned int SDRPlayIF::getIF (unsigned int if_index) static
Definition at line 1079 of file sdrplayinput.cpp.
Referenced by SDRPlayInput::applySettings(), SDRPlayGui::SDRPlayGui(), and SDRPlayInput::webapiFormatDeviceReport().
 {
     if (if_index < m_nb_if)
     {
         return m_if[if_index];
     }
     else
     {
         return m_if[0];
     }
 }
getIFIndex()
unsigned int SDRPlayIF::getIFIndex (unsigned int iff) static
Definition at line 1091 of file sdrplayinput.cpp.
References i.
 {
     for (unsigned int i=0; i < m_nb_if; i++)
     {
         if (iff == m_if[i])
         {
             return i;
         }
     }
     return 0;
 }
getNbIFs()
unsigned int SDRPlayIF::getNbIFs () static
Definition at line 1104 of file sdrplayinput.cpp.
References SDRPlayBands::m_bandHigh, SDRPlayBands::m_bandLow, SDRPlayBands::m_bandName, and m_nb_if.
Referenced by SDRPlayGui::SDRPlayGui(), and SDRPlayInput::webapiFormatDeviceReport().
 {
     return SDRPlayIF::m_nb_if;
 }
Member Data Documentation
m_if
unsigned int SDRPlayIF::m_if static private
Initial value:
= {
        0,
        450000,
        1620000,
        2048000,
}
Definition at line 239 of file sdrplayinput.h.
Referenced by SDRPlayBandwidths::getNbBandwidths().
m_nb_if
const unsigned int SDRPlayIF::m_nb_if = 4 static private
Definition at line 238 of file sdrplayinput.h.
Referenced by getNbIFs().
The documentation for this class was generated from the following files:
plugins/samplesource/sdrplay/sdrplayinput.h
plugins/samplesource/sdrplay/sdrplayinput.cpp