SDRAngel: FileInputGUI Class Reference
FileInputGUI Class Reference
#include <fileinputgui.h>
Public Member Functions
FileInputGUI (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~FileInputGUI ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
QByteArray serialize () const
bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_startStop_toggled (bool checked)
void on_playLoop_toggled (bool checked)
void on_play_toggled (bool checked)
void on_navTimeSlider_valueChanged (int value)
void on_showFileDialog_clicked (bool checked)
void on_acceleration_currentIndexChanged (int index)
void updateStatus ()
void tick ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void displayTime ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void configureFileName ()
void updateWithAcquisition ()
void updateWithStreamData ()
void updateWithStreamTime ()
void setAccelerationCombo ()
void setNumberStr (int n, QString &s)
Private Attributes
Ui::FileInputGUI * ui
DeviceUISet * m_deviceUISet
FileInputSettings m_settings
bool m_doApplySettings
QTimer m_statusTimer
std::vector< int > m_gains
DeviceSampleSource * m_sampleSource
bool m_acquisition
QString m_fileName
int m_sampleRate
quint32 m_sampleSize
quint64 m_centerFrequency
quint64 m_recordLength
quint64 m_startingTimeStamp
quint64 m_samplesCount
std::size_t m_tickCount
bool m_enableNavTime
int m_deviceSampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 36 of file fileinputgui.h.
Constructor & Destructor Documentation
FileInputGUI()
FileInputGUI::FileInputGUI (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 41 of file fileinputgui.cpp.
References displaySettings(), DeviceAPI::getMasterTimer(), DeviceAPI::getSampleSource(), ColorMapper::GrayGold, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_fileName, m_inputMessageQueue, m_sampleSource, m_statusTimer, openDeviceSettingsDialog(), setAccelerationCombo(), DeviceSampleSource::setMessageQueueToGUI(), tick(), ui, and updateStatus().
                                                                     :
     QWidget(parent),
     ui(new Ui::FileInputGUI),
     m_deviceUISet(deviceUISet),
     m_settings(),
     m_doApplySettings(true),
     m_sampleSource(0),
     m_acquisition(false),
     m_fileName("..."),
     m_sampleRate(0),
     m_centerFrequency(0),
     m_recordLength(0),
     m_startingTimeStamp(0),
     m_samplesCount(0),
     m_tickCount(0),
     m_enableNavTime(false),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     ui->setupUi(this);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, 0, pow(10,7));
     ui->fileNameText->setText(m_fileName);
     ui->crcLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
     connect(&(m_deviceUISet->m_deviceAPI->getMasterTimer()), SIGNAL(timeout()), this, SLOT(tick()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     setAccelerationCombo();
     displaySettings();
     ui->navTimeSlider->setEnabled(false);
     ui->acceleration->setEnabled(false);
     m_sampleSource = m_deviceUISet->m_deviceAPI->getSampleSource();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSource->setMessageQueueToGUI(&m_inputMessageQueue);
 }
~FileInputGUI()
FileInputGUI::~FileInputGUI () virtual
Definition at line 84 of file fileinputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void FileInputGUI::blockApplySettings (bool block) inline private
Definition at line 79 of file fileinputgui.h.
Referenced by displaySettings(), and handleMessage().
 { m_doApplySettings = !block; }
configureFileName()
void FileInputGUI::configureFileName () private
Definition at line 344 of file fileinputgui.cpp.
References FileInput::MsgConfigureFileSourceName::create(), DeviceSampleSource::getInputMessageQueue(), m_fileName, m_sampleSource, and MessageQueue::push().
Referenced by on_showFileDialog_clicked().
 {
     qDebug() << "FileInputGUI::configureFileName: " << m_fileName.toStdString().c_str();
     FileInput::MsgConfigureFileSourceName* message = FileInput::MsgConfigureFileSourceName::create(m_fileName);
     m_sampleSource->getInputMessageQueue()->push(message);
 }
deserialize()
bool FileInputGUI::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 128 of file fileinputgui.cpp.
References FileInputSettings::deserialize(), displaySettings(), m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         sendSettings();
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void FileInputGUI::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 89 of file fileinputgui.cpp.
 {
     delete this;
 }
displaySettings()
void FileInputGUI::displaySettings () private
Definition at line 241 of file fileinputgui.cpp.
References blockApplySettings(), FileInputSettings::getAccelerationIndex(), FileInputSettings::m_accelerationFactor, FileInputSettings::m_loop, m_settings, and ui.
Referenced by deserialize(), FileInputGUI(), handleMessage(), resetToDefaults(), and setCenterFrequency().
 {
     blockApplySettings(true);
     ui->playLoop->setChecked(m_settings.m_loop);
     ui->acceleration->setCurrentIndex(FileInputSettings::getAccelerationIndex(m_settings.m_accelerationFactor));
     blockApplySettings(false);
 }
displayTime()
void FileInputGUI::displayTime () private
getCenterFrequency()
qint64 FileInputGUI::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 111 of file fileinputgui.cpp.
References m_centerFrequency.
 {
     return m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* FileInputGUI::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 52 of file fileinputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString FileInputGUI::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 99 of file fileinputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void FileInputGUI::handleInputMessages () private slot
Definition at line 140 of file fileinputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_deviceSampleRate, m_inputMessageQueue, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by FileInputGUI().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_deviceSampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("FileInputGUI::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool FileInputGUI::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 166 of file fileinputgui.cpp.
References blockApplySettings(), displaySettings(), FileInput::MsgPlayPause::getPlayPause(), FileInput::MsgConfigureFileInput::getSettings(), FileInput::MsgStartStop::getStartStop(), FileInput::MsgReportHeaderCRC::isOK(), m_acquisition, m_centerFrequency, m_enableNavTime, m_recordLength, m_sampleRate, m_samplesCount, m_sampleSize, m_settings, m_startingTimeStamp, Message::match(), ui, updateWithAcquisition(), updateWithStreamData(), and updateWithStreamTime().
Referenced by handleInputMessages().
 {
     if (FileInput::MsgConfigureFileInput::match(message))
     {
         const FileInput::MsgConfigureFileInput& cfg = (FileInput::MsgConfigureFileInput&) message;
         m_settings = cfg.getSettings();
         displaySettings();
         return true;
     }
     else if (FileInput::MsgReportFileSourceAcquisition::match(message))
     {
         m_acquisition = ((FileInput::MsgReportFileSourceAcquisition&)message).getAcquisition();
         updateWithAcquisition();
         return true;
     }
     else if (FileInput::MsgReportFileInputStreamData::match(message))
     {
         m_sampleRate = ((FileInput::MsgReportFileInputStreamData&)message).getSampleRate();
         m_sampleSize = ((FileInput::MsgReportFileInputStreamData&)message).getSampleSize();
         m_centerFrequency = ((FileInput::MsgReportFileInputStreamData&)message).getCenterFrequency();
         m_startingTimeStamp = ((FileInput::MsgReportFileInputStreamData&)message).getStartingTimeStamp();
         m_recordLength = ((FileInput::MsgReportFileInputStreamData&)message).getRecordLength();
         updateWithStreamData();
         return true;
     }
     else if (FileInput::MsgReportFileInputStreamTiming::match(message))
     {
         m_samplesCount = ((FileInput::MsgReportFileInputStreamTiming&)message).getSamplesCount();
         updateWithStreamTime();
         return true;
     }
     else if (FileInput::MsgStartStop::match(message))
     {
         FileInput::MsgStartStop& notif = (FileInput::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else if (FileInput::MsgPlayPause::match(message))
     {
         FileInput::MsgPlayPause& notif = (FileInput::MsgPlayPause&) message;
         bool checked = notif.getPlayPause();
         ui->play->setChecked(checked);
         ui->navTimeSlider->setEnabled(!checked);
         ui->acceleration->setEnabled(!checked);
         m_enableNavTime = !checked;
         return true;
     }
     else if (FileInput::MsgReportHeaderCRC::match(message))
     {
         FileInput::MsgReportHeaderCRC& notif = (FileInput::MsgReportHeaderCRC&) message;
         if (notif.isOK()) {
             ui->crcLabel->setStyleSheet("QLabel { background-color : green; }");
         } else {
             ui->crcLabel->setStyleSheet("QLabel { background-color : red; }");
         }
         return true;
     }
     else
     {
         return false;
     }
 }
on_acceleration_currentIndexChanged
void FileInputGUI::on_acceleration_currentIndexChanged (int index) private slot
Definition at line 334 of file fileinputgui.cpp.
References FileInput::MsgConfigureFileInput::create(), FileInputSettings::getAccelerationValue(), DeviceSampleSource::getInputMessageQueue(), FileInputSettings::m_accelerationFactor, m_doApplySettings, m_sampleSource, m_settings, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         m_settings.m_accelerationFactor = FileInputSettings::getAccelerationValue(index);
         FileInput::MsgConfigureFileInput *message = FileInput::MsgConfigureFileInput::create(m_settings, false);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
on_navTimeSlider_valueChanged
void FileInputGUI::on_navTimeSlider_valueChanged (int value) private slot
Definition at line 310 of file fileinputgui.cpp.
References FileInput::MsgConfigureFileSourceSeek::create(), DeviceSampleSource::getInputMessageQueue(), m_enableNavTime, m_sampleSource, and MessageQueue::push().
 {
     if (m_enableNavTime && ((value >= 0) && (value <= 1000)))
     {
         FileInput::MsgConfigureFileSourceSeek* message = FileInput::MsgConfigureFileSourceSeek::create(value);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
on_play_toggled
void FileInputGUI::on_play_toggled (bool checked) private slot
Definition at line 301 of file fileinputgui.cpp.
References FileInput::MsgConfigureFileInputWork::create(), DeviceSampleSource::getInputMessageQueue(), m_enableNavTime, m_sampleSource, MessageQueue::push(), and ui.
 {
     FileInput::MsgConfigureFileInputWork* message = FileInput::MsgConfigureFileInputWork::create(checked);
     m_sampleSource->getInputMessageQueue()->push(message);
     ui->navTimeSlider->setEnabled(!checked);
     ui->acceleration->setEnabled(!checked);
     m_enableNavTime = !checked;
 }
on_playLoop_toggled
void FileInputGUI::on_playLoop_toggled (bool checked) private slot
Definition at line 253 of file fileinputgui.cpp.
References FileInput::MsgConfigureFileInput::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, FileInputSettings::m_loop, m_sampleSource, m_settings, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         m_settings.m_loop = checked;
         FileInput::MsgConfigureFileInput *message = FileInput::MsgConfigureFileInput::create(m_settings, false);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
on_showFileDialog_clicked
void FileInputGUI::on_showFileDialog_clicked (bool checked) private slot
Definition at line 319 of file fileinputgui.cpp.
References configureFileName(), m_fileName, and ui.
 {
     (void) checked;
     QString fileName = QFileDialog::getOpenFileName(this,
         tr("Open I/Q record file"), ".", tr("SDR I/Q Files (*.sdriq)"), 0, QFileDialog::DontUseNativeDialog);
     if (fileName != "")
     {
         m_fileName = fileName;
         ui->fileNameText->setText(m_fileName);
         ui->crcLabel->setStyleSheet("QLabel { background:rgb(79,79,79); }");
         configureFileName();
     }
 }
on_startStop_toggled
void FileInputGUI::on_startStop_toggled (bool checked) private slot
Definition at line 263 of file fileinputgui.cpp.
References FileInput::MsgStartStop::create(), DeviceSampleSource::getInputMessageQueue(), m_doApplySettings, m_sampleSource, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         FileInput::MsgStartStop *message = FileInput::MsgStartStop::create(checked);
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
openDeviceSettingsDialog
void FileInputGUI::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 448 of file fileinputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), FileInputSettings::m_reverseAPIAddress, FileInputSettings::m_reverseAPIDeviceIndex, FileInputSettings::m_reverseAPIPort, m_settings, FileInputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by FileInputGUI().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void FileInputGUI::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 104 of file fileinputgui.cpp.
References displaySettings(), m_settings, FileInputSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void FileInputGUI::sendSettings () private
Definition at line 249 of file fileinputgui.cpp.
Referenced by deserialize(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
 }
serialize()
QByteArray FileInputGUI::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 123 of file fileinputgui.cpp.
References m_settings, and FileInputSettings::serialize().
 {
     return m_settings.serialize();
 }
setAccelerationCombo()
void FileInputGUI::setAccelerationCombo () private
Definition at line 409 of file fileinputgui.cpp.
References i, FileInputSettings::m_accelerationMaxScale, setNumberStr(), and ui.
Referenced by FileInputGUI().
 {
     ui->acceleration->blockSignals(true);
     ui->acceleration->clear();
     ui->acceleration->addItem(QString("1"));
     for (unsigned int i = 0; i <= FileInputSettings::m_accelerationMaxScale; i++)
     {
         QString s;
         int m = pow(10.0, i);
         int x = 2*m;
         setNumberStr(x, s);
         ui->acceleration->addItem(s);
         x = 5*m;
         setNumberStr(x, s);
         ui->acceleration->addItem(s);
         x = 10*m;
         setNumberStr(x, s);
         ui->acceleration->addItem(s);
     }
     ui->acceleration->blockSignals(false);
 }
setCenterFrequency()
void FileInputGUI::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 116 of file fileinputgui.cpp.
References displaySettings(), m_centerFrequency, and sendSettings().
 {
     m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setName()
void FileInputGUI::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 94 of file fileinputgui.cpp.
 {
     setObjectName(name);
 }
setNumberStr()
void FileInputGUI::setNumberStr (int n, QString & s) private
Definition at line 433 of file fileinputgui.cpp.
Referenced by setAccelerationCombo().
 {
     if (n < 1000) {
         s = tr("%1").arg(n);
     } else if (n < 100000) {
         s = tr("%1k").arg(n/1000);
     } else if (n < 1000000) {
         s = tr("%1e5").arg(n/100000);
     } else if (n < 1000000000) {
         s = tr("%1M").arg(n/1000000);
     } else {
         s = tr("%1G").arg(n/1000000000);
     }
 }
tick
void FileInputGUI::tick () private slot
Definition at line 401 of file fileinputgui.cpp.
References FileInput::MsgConfigureFileInputStreamTiming::create(), DeviceSampleSource::getInputMessageQueue(), m_sampleSource, m_tickCount, and MessageQueue::push().
Referenced by FileInputGUI().
 {
     if ((++m_tickCount & 0xf) == 0) {
         FileInput::MsgConfigureFileInputStreamTiming* message = FileInput::MsgConfigureFileInputStreamTiming::create();
         m_sampleSource->getInputMessageQueue()->push(message);
     }
 }
updateSampleRateAndFrequency()
void FileInputGUI::updateSampleRateAndFrequency () private
Definition at line 234 of file fileinputgui.cpp.
References arg(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceSampleRate, m_deviceUISet, GLSpectrum::setCenterFrequency(), GLSpectrum::setSampleRate(), and ui.
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_deviceSampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     ui->deviceRateText->setText(tr("%1k").arg((float)m_deviceSampleRate / 1000));
 }
updateStatus
void FileInputGUI::updateStatus () private slot
Definition at line 272 of file fileinputgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by FileInputGUI().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
updateWithAcquisition()
void FileInputGUI::updateWithAcquisition () private
Definition at line 351 of file fileinputgui.cpp.
References m_acquisition, and ui.
Referenced by handleMessage().
 {
     ui->play->setEnabled(m_acquisition);
     ui->play->setChecked(m_acquisition);
     ui->showFileDialog->setEnabled(!m_acquisition);
 }
updateWithStreamData()
void FileInputGUI::updateWithStreamData () private
Definition at line 358 of file fileinputgui.cpp.
References arg(), m_acquisition, m_centerFrequency, m_recordLength, m_sampleRate, m_sampleSize, ui, and updateWithStreamTime().
Referenced by handleMessage().
 {
     ui->centerFrequency->setValue(m_centerFrequency/1000);
     ui->sampleRateText->setText(tr("%1k").arg((float)m_sampleRate / 1000));
     ui->sampleSizeText->setText(tr("%1b").arg(m_sampleSize));
     ui->play->setEnabled(m_acquisition);
     QTime recordLength(0, 0, 0, 0);
     recordLength = recordLength.addSecs(m_recordLength);
     QString s_time = recordLength.toString("HH:mm:ss");
     ui->recordLengthText->setText(s_time);
     updateWithStreamTime();
 }
updateWithStreamTime()
void FileInputGUI::updateWithStreamTime () private
Definition at line 371 of file fileinputgui.cpp.
References m_enableNavTime, m_recordLength, m_sampleRate, m_samplesCount, m_startingTimeStamp, and ui.
Referenced by handleMessage(), and updateWithStreamData().
 {
     qint64 t_sec = 0;
     qint64 t_msec = 0;
     if (m_sampleRate > 0){
         t_sec = m_samplesCount / m_sampleRate;
         t_msec = (m_samplesCount - (t_sec * m_sampleRate)) * 1000LL / m_sampleRate;
     }
     QTime t(0, 0, 0, 0);
     t = t.addSecs(t_sec);
     t = t.addMSecs(t_msec);
     QString s_timems = t.toString("HH:mm:ss.zzz");
     ui->relTimeText->setText(s_timems);
     qint64 startingTimeStampMsec = m_startingTimeStamp * 1000LL;
     QDateTime dt = QDateTime::fromMSecsSinceEpoch(startingTimeStampMsec);
     dt = dt.addSecs(t_sec);
     dt = dt.addMSecs(t_msec);
     QString s_date = dt.toString("yyyy-MM-dd HH:mm:ss.zzz");
     ui->absTimeText->setText(s_date);
     if (!m_enableNavTime)
     {
         float posRatio = (float) t_sec / (float) m_recordLength;
         ui->navTimeSlider->setValue((int) (posRatio * 1000.0));
     }
 }
Member Data Documentation
m_acquisition
bool FileInputGUI::m_acquisition private
Definition at line 64 of file fileinputgui.h.
Referenced by handleMessage(), updateWithAcquisition(), and updateWithStreamData().
m_centerFrequency
quint64 FileInputGUI::m_centerFrequency private
Definition at line 68 of file fileinputgui.h.
Referenced by getCenterFrequency(), handleMessage(), setCenterFrequency(), and updateWithStreamData().
m_deviceCenterFrequency
quint64 FileInputGUI::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 75 of file fileinputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceSampleRate
int FileInputGUI::m_deviceSampleRate private
Definition at line 74 of file fileinputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* FileInputGUI::m_deviceUISet private
Definition at line 58 of file fileinputgui.h.
Referenced by FileInputGUI(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool FileInputGUI::m_doApplySettings private
Definition at line 60 of file fileinputgui.h.
Referenced by on_acceleration_currentIndexChanged(), on_playLoop_toggled(), and on_startStop_toggled().
m_enableNavTime
bool FileInputGUI::m_enableNavTime private
Definition at line 73 of file fileinputgui.h.
Referenced by handleMessage(), on_navTimeSlider_valueChanged(), on_play_toggled(), and updateWithStreamTime().
m_fileName
QString FileInputGUI::m_fileName private
Definition at line 65 of file fileinputgui.h.
Referenced by configureFileName(), FileInputGUI(), and on_showFileDialog_clicked().
m_gains
std::vector<int> FileInputGUI::m_gains private
Definition at line 62 of file fileinputgui.h.
m_inputMessageQueue
MessageQueue FileInputGUI::m_inputMessageQueue private
Definition at line 77 of file fileinputgui.h.
Referenced by FileInputGUI(), and handleInputMessages().
m_lastEngineState
int FileInputGUI::m_lastEngineState private
Definition at line 76 of file fileinputgui.h.
Referenced by updateStatus().
m_recordLength
quint64 FileInputGUI::m_recordLength private
Definition at line 69 of file fileinputgui.h.
Referenced by handleMessage(), updateWithStreamData(), and updateWithStreamTime().
m_sampleRate
int FileInputGUI::m_sampleRate private
Definition at line 66 of file fileinputgui.h.
Referenced by handleMessage(), updateWithStreamData(), and updateWithStreamTime().
m_samplesCount
quint64 FileInputGUI::m_samplesCount private
Definition at line 71 of file fileinputgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_sampleSize
quint32 FileInputGUI::m_sampleSize private
Definition at line 67 of file fileinputgui.h.
Referenced by handleMessage(), and updateWithStreamData().
m_sampleSource
DeviceSampleSource* FileInputGUI::m_sampleSource private
Definition at line 63 of file fileinputgui.h.
Referenced by configureFileName(), FileInputGUI(), on_acceleration_currentIndexChanged(), on_navTimeSlider_valueChanged(), on_play_toggled(), on_playLoop_toggled(), on_startStop_toggled(), and tick().
m_settings
FileInputSettings FileInputGUI::m_settings private
Definition at line 59 of file fileinputgui.h.
Referenced by deserialize(), displaySettings(), handleMessage(), on_acceleration_currentIndexChanged(), on_playLoop_toggled(), openDeviceSettingsDialog(), resetToDefaults(), and serialize().
m_startingTimeStamp
quint64 FileInputGUI::m_startingTimeStamp private
Definition at line 70 of file fileinputgui.h.
Referenced by handleMessage(), and updateWithStreamTime().
m_statusTimer
QTimer FileInputGUI::m_statusTimer private
Definition at line 61 of file fileinputgui.h.
Referenced by FileInputGUI().
m_tickCount
std::size_t FileInputGUI::m_tickCount private
Definition at line 72 of file fileinputgui.h.
Referenced by tick().
ui
Ui::FileInputGUI* FileInputGUI::ui private
Definition at line 56 of file fileinputgui.h.
Referenced by displaySettings(), FileInputGUI(), handleMessage(), on_play_toggled(), on_showFileDialog_clicked(), setAccelerationCombo(), updateSampleRateAndFrequency(), updateStatus(), updateWithAcquisition(), updateWithStreamData(), updateWithStreamTime(), and ~FileInputGUI().
The documentation for this class was generated from the following files:
plugins/samplesource/fileinput/fileinputgui.h
plugins/samplesource/fileinput/fileinputgui.cpp