SDRAngel: DeviceLimeSDRShared::ThreadInterface Class Reference
DeviceLimeSDRShared::ThreadInterface Class Reference abstract
#include <devicelimesdrshared.h>
Public Member Functions
virtual void startWork ()=0
virtual void stopWork ()=0
virtual void setDeviceSampleRate (int sampleRate)=0
virtual bool isRunning ()=0
Detailed Description
Definition at line 147 of file devicelimesdrshared.h.
Member Function Documentation
isRunning()
virtual bool DeviceLimeSDRShared::ThreadInterface::isRunning () pure virtual
Implemented in LimeSDROutputThread, and LimeSDRInputThread.
Referenced by LimeSDROutput::suspendRxBuddies(), LimeSDRInput::suspendRxBuddies(), LimeSDROutput::suspendTxBuddies(), and LimeSDRInput::suspendTxBuddies().
setDeviceSampleRate()
virtual void DeviceLimeSDRShared::ThreadInterface::setDeviceSampleRate (int sampleRate) pure virtual
Implemented in LimeSDROutputThread, and LimeSDRInputThread.
startWork()
virtual void DeviceLimeSDRShared::ThreadInterface::startWork () pure virtual
Implemented in LimeSDROutputThread, and LimeSDRInputThread.
Referenced by LimeSDROutput::resumeRxBuddies(), LimeSDRInput::resumeRxBuddies(), LimeSDROutput::resumeTxBuddies(), and LimeSDRInput::resumeTxBuddies().
stopWork()
virtual void DeviceLimeSDRShared::ThreadInterface::stopWork () pure virtual
Implemented in LimeSDROutputThread, and LimeSDRInputThread.
Referenced by LimeSDROutput::suspendRxBuddies(), LimeSDRInput::suspendRxBuddies(), LimeSDROutput::suspendTxBuddies(), and LimeSDRInput::suspendTxBuddies().
The documentation for this class was generated from the following file:
devices/limesdr/devicelimesdrshared.h