SDRAngel: AirspyHFPlugin Class Reference
AirspyHFPlugin Class Reference
#include <airspyhfplugin.h>
Public Member Functions
AirspyHFPlugin (QObject *parent=0)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "AirspyHF"
static const QString m_deviceTypeID = AIRSPYHF_DEVICE_TYPE_ID
static const int m_maxDevices = 32
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 28 of file airspyhfplugin.h.
Constructor & Destructor Documentation
AirspyHFPlugin()
AirspyHFPlugin::AirspyHFPlugin (QObject * parent = 0) explicit
Definition at line 44 of file airspyhfplugin.cpp.
                                               :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSourcePluginInstance()
DeviceSampleSource * AirspyHFPlugin::createSampleSourcePluginInstance (const QString & sourceId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 131 of file airspyhfplugin.cpp.
References m_deviceTypeID.
 {
     if (sourceId == m_deviceTypeID)
     {
         AirspyHFInput* input = new AirspyHFInput(deviceAPI);
         return input;
     }
     else
     {
         return 0;
     }
 }
createSampleSourcePluginInstanceGUI()
PluginInstanceGUI * AirspyHFPlugin::createSampleSourcePluginInstanceGUI (const QString & sourceId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 113 of file airspyhfplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSources().
 {
     if (sourceId == m_deviceTypeID)
     {
         AirspyHFGui* gui = new AirspyHFGui(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSources()
PluginInterface::SamplingDevices AirspyHFPlugin::enumSampleSources () virtual
Reimplemented from PluginInterface.
Definition at line 59 of file airspyhfplugin.cpp.
References arg(), createSampleSourcePluginInstanceGUI(), i, m_deviceTypeID, m_hardwareID, m_maxDevices, PluginInterface::SamplingDevice::PhysicalDevice, and PluginInterface::SamplingDevice::StreamSingleRx.
 {
     SamplingDevices result;
     int nbDevices;
     uint64_t deviceSerials[m_maxDevices];
     nbDevices = airspyhf_list_devices(deviceSerials, m_maxDevices);
     if (nbDevices < 0)
     {
         qCritical("AirspyHFPlugin::enumSampleSources: failed to list Airspy HF devices");
     }
     for (int i = 0; i < nbDevices; i++)
     {
         if (deviceSerials[i])
         {
             QString serial_str = QString::number(deviceSerials[i], 16);
             QString displayedName(QString("AirspyHF[%1] %2").arg(i).arg(serial_str));
             result.append(SamplingDevice(displayedName,
                     m_hardwareID,
                     m_deviceTypeID,
                     serial_str,
                     i,
                     PluginInterface::SamplingDevice::PhysicalDevice,
                     PluginInterface::SamplingDevice::StreamSingleRx,
                     1,
                     0));
             qDebug("AirspyHFPlugin::enumSampleSources: enumerated Airspy HF device #%d", i);
         }
         else
         {
             qDebug("AirspyHFPlugin::enumSampleSources: finished to enumerate Airspy HF. %d devices found", i);
             break; // finished
         }
     }
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & AirspyHFPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 49 of file airspyhfplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void AirspyHFPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 54 of file airspyhfplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSource().
 {
     pluginAPI->registerSampleSource(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString AirspyHFPlugin::m_deviceTypeID = AIRSPYHF_DEVICE_TYPE_ID static
Definition at line 47 of file airspyhfplugin.h.
Referenced by createSampleSourcePluginInstance(), createSampleSourcePluginInstanceGUI(), enumSampleSources(), and initPlugin().
m_hardwareID
const QString AirspyHFPlugin::m_hardwareID = "AirspyHF" static
Definition at line 46 of file airspyhfplugin.h.
Referenced by enumSampleSources().
m_maxDevices
const int AirspyHFPlugin::m_maxDevices = 32 static
Definition at line 48 of file airspyhfplugin.h.
Referenced by enumSampleSources().
m_pluginDescriptor
const PluginDescriptor AirspyHFPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("AirspyHF Input"),
    QString("4.5.2"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 51 of file airspyhfplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesource/airspyhf/airspyhfplugin.h
plugins/samplesource/airspyhf/airspyhfplugin.cpp