SDRAngel: BladeRF2OutputGui Class Reference
BladeRF2OutputGui Class Reference
#include <bladerf2outputgui.h>
Public Member Functions
BladeRF2OutputGui (DeviceUISet *deviceUISet, QWidget *parent=0)
virtual ~BladeRF2OutputGui ()
virtual void destroy ()
void setName (const QString &name)
QString getName () const
void resetToDefaults ()
virtual qint64 getCenterFrequency () const
virtual void setCenterFrequency (qint64 centerFrequency)
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual MessageQueue * getInputMessageQueue ()
virtual bool handleMessage (const Message &message)
Public Member Functions inherited from PluginInstanceGUI
PluginInstanceGUI ()
virtual ~PluginInstanceGUI ()
Private Slots
void handleInputMessages ()
void on_centerFrequency_changed (quint64 value)
void on_LOppm_valueChanged (int value)
void on_biasTee_toggled (bool checked)
void on_sampleRate_changed (quint64 value)
void on_bandwidth_changed (quint64 value)
void on_interp_currentIndexChanged (int index)
void on_gain_valueChanged (int value)
void on_startStop_toggled (bool checked)
void on_transverter_clicked ()
void on_sampleRateMode_toggled (bool checked)
void updateHardware ()
void updateStatus ()
void openDeviceSettingsDialog (const QPoint &p)
Private Member Functions
void blockApplySettings (bool block)
void displaySettings ()
void displaySampleRate ()
void sendSettings ()
void updateSampleRateAndFrequency ()
void updateFrequencyLimits ()
void setCenterFrequencySetting (uint64_t kHzValue)
Private Attributes
Ui::BladeRF2OutputGui * ui
DeviceUISet * m_deviceUISet
bool m_doApplySettings
bool m_forceSettings
BladeRF2OutputSettings m_settings
bool m_sampleRateMode
true: device, false: base band sample rate update mode
QTimer m_updateTimer
QTimer m_statusTimer
BladeRF2Output * m_sampleSink
int m_sampleRate
quint64 m_deviceCenterFrequency
Center frequency in device.
int m_lastEngineState
MessageQueue m_inputMessageQueue
Detailed Description
Definition at line 36 of file bladerf2outputgui.h.
Constructor & Destructor Documentation
BladeRF2OutputGui()
BladeRF2OutputGui::BladeRF2OutputGui (DeviceUISet * deviceUISet, QWidget * parent = 0) explicit
Definition at line 35 of file bladerf2outputgui.cpp.
References displaySettings(), BladeRF2Output::getBandwidthRange(), BladeRF2Output::getFrequencyRange(), BladeRF2Output::getGlobalGainRange(), BladeRF2Output::getSampleRateRange(), DeviceAPI::getSampleSink(), ColorMapper::GrayGold, ColorMapper::GrayGreenYellow, ColorMapper::GrayYellow, handleInputMessages(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_inputMessageQueue, m_sampleSink, m_statusTimer, m_updateTimer, leansdr::max(), leansdr::min(), openDeviceSettingsDialog(), BladeRF2Output::setMessageQueueToGUI(), ui, updateHardware(), and updateStatus().
                                                                               :
     QWidget(parent),
     ui(new Ui::BladeRF2OutputGui),
     m_deviceUISet(deviceUISet),
     m_doApplySettings(true),
     m_forceSettings(true),
     m_settings(),
     m_sampleRateMode(true),
     m_sampleRate(0),
     m_lastEngineState(DeviceAPI::StNotStarted)
 {
     m_sampleSink = (BladeRF2Output*) m_deviceUISet->m_deviceAPI->getSampleSink();
     int max, min, step;
     uint64_t f_min, f_max;
     ui->setupUi(this);
     m_sampleSink->getFrequencyRange(f_min, f_max, step);
     qDebug("BladeRF2OutputGui::BladeRF2OutputGui: getFrequencyRange: [%lu,%lu] step: %d", f_min, f_max, step);
     ui->centerFrequency->setColorMapper(ColorMapper(ColorMapper::GrayGold));
     ui->centerFrequency->setValueRange(7, f_min/1000, f_max/1000);
     m_sampleSink->getSampleRateRange(min, max, step);
     qDebug("BladeRF2OutputGui::BladeRF2OutputGui: getSampleRateRange: [%d,%d] step: %d", min, max, step);
     ui->sampleRate->setColorMapper(ColorMapper(ColorMapper::GrayGreenYellow));
     ui->sampleRate->setValueRange(8, min, max);
     m_sampleSink->getBandwidthRange(min, max, step);
     qDebug("BladeRF2OutputGui::BladeRF2OutputGui: getBandwidthRange: [%d,%d] step: %d", min, max, step);
     ui->bandwidth->setColorMapper(ColorMapper(ColorMapper::GrayYellow));
     ui->bandwidth->setValueRange(5, min/1000, max/1000);
     m_sampleSink->getGlobalGainRange(min, max, step);
     qDebug("BladeRF2OutputGui::BladeRF2OutputGui: getGlobalGainRange: [%d,%d] step: %d", min, max, step);
     ui->gain->setMinimum((min-max)/1000);
     ui->gain->setMaximum(0);
     ui->gain->setPageStep(1);
     ui->gain->setSingleStep(1);
     connect(&m_updateTimer, SIGNAL(timeout()), this, SLOT(updateHardware()));
     connect(&m_statusTimer, SIGNAL(timeout()), this, SLOT(updateStatus()));
     m_statusTimer.start(500);
     CRightClickEnabler *startStopRightClickEnabler = new CRightClickEnabler(ui->startStop);
     connect(startStopRightClickEnabler, SIGNAL(rightClick(const QPoint &)), this, SLOT(openDeviceSettingsDialog(const QPoint &)));
     displaySettings();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
     m_sampleSink->setMessageQueueToGUI(&m_inputMessageQueue);
 }
~BladeRF2OutputGui()
BladeRF2OutputGui::~BladeRF2OutputGui () virtual
Definition at line 87 of file bladerf2outputgui.cpp.
References ui.
 {
     delete ui;
 }
Member Function Documentation
blockApplySettings()
void BladeRF2OutputGui::blockApplySettings (bool block) inline private
Definition at line 71 of file bladerf2outputgui.h.
Referenced by displaySettings(), and handleMessage().
 { m_doApplySettings = !block; }
deserialize()
bool BladeRF2OutputGui::deserialize (const QByteArray & data) virtual
Implements PluginInstanceGUI.
Definition at line 131 of file bladerf2outputgui.cpp.
References BladeRF2OutputSettings::deserialize(), displaySettings(), m_forceSettings, m_settings, resetToDefaults(), and sendSettings().
 {
     if(m_settings.deserialize(data)) {
         displaySettings();
         m_forceSettings = true;
         sendSettings();
         return true;
     } else {
         resetToDefaults();
         return false;
     }
 }
destroy()
void BladeRF2OutputGui::destroy () virtual
Implements PluginInstanceGUI.
Definition at line 92 of file bladerf2outputgui.cpp.
 {
     delete this;
 }
displaySampleRate()
void BladeRF2OutputGui::displaySampleRate () private
Definition at line 248 of file bladerf2outputgui.cpp.
References arg(), BladeRF2Output::getSampleRateRange(), BladeRF2OutputSettings::m_devSampleRate, BladeRF2OutputSettings::m_log2Interp, m_sampleRateMode, m_sampleSink, m_settings, leansdr::max(), leansdr::min(), and ui.
Referenced by displaySettings(), on_interp_currentIndexChanged(), on_sampleRateMode_toggled(), and updateSampleRateAndFrequency().
 {
     int max, min, step;
     m_sampleSink->getSampleRateRange(min, max, step);
     ui->sampleRate->blockSignals(true);
     if (m_sampleRateMode)
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(60,60,60); }");
         ui->sampleRateMode->setText("SR");
         ui->sampleRate->setValueRange(8, min, max);
         ui->sampleRate->setValue(m_settings.m_devSampleRate);
         ui->sampleRate->setToolTip("Host to device sample rate (S/s)");
         ui->deviceRateText->setToolTip("Baseband sample rate (S/s)");
         uint32_t basebandSampleRate = m_settings.m_devSampleRate/(1<<m_settings.m_log2Interp);
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(basebandSampleRate / 1000.0f, 'g', 5)));
     }
     else
     {
         ui->sampleRateMode->setStyleSheet("QToolButton { background:rgb(50,50,50); }");
         ui->sampleRateMode->setText("BB");
         ui->sampleRate->setValueRange(8, min/(1<<m_settings.m_log2Interp), max/(1<<m_settings.m_log2Interp));
         ui->sampleRate->setValue(m_settings.m_devSampleRate/(1<<m_settings.m_log2Interp));
         ui->sampleRate->setToolTip("Baseband sample rate (S/s)");
         ui->deviceRateText->setToolTip("Host to device sample rate (S/s)");
         ui->deviceRateText->setText(tr("%1k").arg(QString::number(m_settings.m_devSampleRate / 1000.0f, 'g', 5)));
     }
     ui->sampleRate->blockSignals(false);
 }
displaySettings()
void BladeRF2OutputGui::displaySettings () private
Definition at line 280 of file bladerf2outputgui.cpp.
References arg(), blockApplySettings(), displaySampleRate(), BladeRF2OutputSettings::m_bandwidth, BladeRF2OutputSettings::m_biasTee, BladeRF2OutputSettings::m_centerFrequency, BladeRF2OutputSettings::m_globalGain, BladeRF2OutputSettings::m_log2Interp, BladeRF2OutputSettings::m_LOppmTenths, m_settings, BladeRF2OutputSettings::m_transverterDeltaFrequency, BladeRF2OutputSettings::m_transverterMode, and ui.
Referenced by BladeRF2OutputGui(), deserialize(), handleMessage(), resetToDefaults(), and setCenterFrequency().
 {
     blockApplySettings(true);
     ui->transverter->setDeltaFrequency(m_settings.m_transverterDeltaFrequency);
     ui->transverter->setDeltaFrequencyActive(m_settings.m_transverterMode);
     ui->centerFrequency->setValue(m_settings.m_centerFrequency / 1000);
     ui->LOppm->setValue(m_settings.m_LOppmTenths);
     ui->LOppmText->setText(QString("%1").arg(QString::number(m_settings.m_LOppmTenths/10.0, 'f', 1)));
     displaySampleRate();
     ui->bandwidth->setValue(m_settings.m_bandwidth / 1000);
     ui->interp->setCurrentIndex(m_settings.m_log2Interp);
     ui->gainText->setText(tr("%1 dB").arg(m_settings.m_globalGain));
     ui->gain->setValue(m_settings.m_globalGain);
     ui->biasTee->setChecked(m_settings.m_biasTee);
     blockApplySettings(false);
 }
getCenterFrequency()
qint64 BladeRF2OutputGui::getCenterFrequency () const virtual
Implements PluginInstanceGUI.
Definition at line 114 of file bladerf2outputgui.cpp.
References BladeRF2OutputSettings::m_centerFrequency, and m_settings.
 {
     return m_settings.m_centerFrequency;
 }
getInputMessageQueue()
virtual MessageQueue* BladeRF2OutputGui::getInputMessageQueue () inline virtual
Implements PluginInstanceGUI.
Definition at line 52 of file bladerf2outputgui.h.
 { return &m_inputMessageQueue; }
getName()
QString BladeRF2OutputGui::getName () const virtual
Implements PluginInstanceGUI.
Definition at line 102 of file bladerf2outputgui.cpp.
 {
     return objectName();
 }
handleInputMessages
void BladeRF2OutputGui::handleInputMessages () private slot
Definition at line 213 of file bladerf2outputgui.cpp.
References DSPSignalNotification::getCenterFrequency(), Message::getIdentifier(), DSPSignalNotification::getSampleRate(), handleMessage(), m_deviceCenterFrequency, m_inputMessageQueue, m_sampleRate, Message::match(), MessageQueue::pop(), and updateSampleRateAndFrequency().
Referenced by BladeRF2OutputGui().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         qDebug("BladeRF2OutputGui::handleInputMessages: message: %s", message->getIdentifier());
         if (DSPSignalNotification::match(*message))
         {
             DSPSignalNotification* notif = (DSPSignalNotification*) message;
             m_sampleRate = notif->getSampleRate();
             m_deviceCenterFrequency = notif->getCenterFrequency();
             qDebug("BladeRF2OutputGui::handleInputMessages: DSPSignalNotification: SampleRate:%d, CenterFrequency:%llu", notif->getSampleRate(), notif->getCenterFrequency());
             updateSampleRateAndFrequency();
             delete message;
         }
         else
         {
             if (handleMessage(*message))
             {
                 delete message;
             }
         }
     }
 }
handleMessage()
bool BladeRF2OutputGui::handleMessage (const Message & message) virtual
Implements PluginInstanceGUI.
Definition at line 170 of file bladerf2outputgui.cpp.
References blockApplySettings(), displaySettings(), BladeRF2Output::getGlobalGainRange(), BladeRF2Output::MsgReportGainRange::getMax(), BladeRF2Output::MsgReportGainRange::getMin(), BladeRF2Output::MsgConfigureBladeRF2::getSettings(), BladeRF2Output::MsgStartStop::getStartStop(), m_sampleSink, m_settings, Message::match(), leansdr::max(), leansdr::min(), and ui.
Referenced by handleInputMessages().
 {
     if (BladeRF2Output::MsgConfigureBladeRF2::match(message))
     {
         const BladeRF2Output::MsgConfigureBladeRF2& cfg = (BladeRF2Output::MsgConfigureBladeRF2&) message;
         m_settings = cfg.getSettings();
         blockApplySettings(true);
         int min, max, step;
         m_sampleSink->getGlobalGainRange(min, max, step);
         ui->gain->setMinimum((min-max)/1000);
         ui->gain->setMaximum(0);
         ui->gain->setPageStep(1);
         ui->gain->setSingleStep(1);
         displaySettings();
         blockApplySettings(false);
         return true;
     }
     else if (BladeRF2Output::MsgReportGainRange::match(message))
     {
         const BladeRF2Output::MsgReportGainRange& cfg = (BladeRF2Output::MsgReportGainRange&) message;
         ui->gain->setMinimum((cfg.getMin()-cfg.getMax())/1000);
         ui->gain->setMaximum(0);
         ui->gain->setSingleStep(1);
         ui->gain->setPageStep(1);
         return true;
     }
     else if (BladeRF2Output::MsgStartStop::match(message))
     {
         BladeRF2Output::MsgStartStop& notif = (BladeRF2Output::MsgStartStop&) message;
         blockApplySettings(true);
         ui->startStop->setChecked(notif.getStartStop());
         blockApplySettings(false);
         return true;
     }
     else
     {
         return false;
     }
 }
on_bandwidth_changed
void BladeRF2OutputGui::on_bandwidth_changed (quint64 value) private slot
Definition at line 338 of file bladerf2outputgui.cpp.
References BladeRF2OutputSettings::m_bandwidth, m_settings, and sendSettings().
 {
     m_settings.m_bandwidth = value * 1000;
     sendSettings();
 }
on_biasTee_toggled
void BladeRF2OutputGui::on_biasTee_toggled (bool checked) private slot
Definition at line 332 of file bladerf2outputgui.cpp.
References BladeRF2OutputSettings::m_biasTee, m_settings, and sendSettings().
 {
     m_settings.m_biasTee = checked;
     sendSettings();
 }
on_centerFrequency_changed
void BladeRF2OutputGui::on_centerFrequency_changed (quint64 value) private slot
Definition at line 308 of file bladerf2outputgui.cpp.
References BladeRF2OutputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = value * 1000;
     sendSettings();
 }
on_gain_valueChanged
void BladeRF2OutputGui::on_gain_valueChanged (int value) private slot
Definition at line 362 of file bladerf2outputgui.cpp.
References arg(), BladeRF2OutputSettings::m_globalGain, m_settings, sendSettings(), and ui.
 {
     ui->gainText->setText(tr("%1 dB").arg(value));
     m_settings.m_globalGain = value;
     sendSettings();
 }
on_interp_currentIndexChanged
void BladeRF2OutputGui::on_interp_currentIndexChanged (int index) private slot
Definition at line 344 of file bladerf2outputgui.cpp.
References displaySampleRate(), BladeRF2OutputSettings::m_devSampleRate, BladeRF2OutputSettings::m_log2Interp, m_sampleRateMode, m_settings, sendSettings(), and ui.
 {
     if ((index <0) || (index > 6)) {
         return;
     }
     m_settings.m_log2Interp = index;
     displaySampleRate();
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew();
     } else {
         m_settings.m_devSampleRate = ui->sampleRate->getValueNew() * (1 << m_settings.m_log2Interp);
     }
     sendSettings();
 }
on_LOppm_valueChanged
void BladeRF2OutputGui::on_LOppm_valueChanged (int value) private slot
Definition at line 314 of file bladerf2outputgui.cpp.
References arg(), BladeRF2OutputSettings::m_LOppmTenths, m_settings, sendSettings(), and ui.
 {
     ui->LOppmText->setText(QString("%1").arg(QString::number(value/10.0, 'f', 1)));
     m_settings.m_LOppmTenths = value;
     sendSettings();
 }
on_sampleRate_changed
void BladeRF2OutputGui::on_sampleRate_changed (quint64 value) private slot
Definition at line 321 of file bladerf2outputgui.cpp.
References BladeRF2OutputSettings::m_devSampleRate, BladeRF2OutputSettings::m_log2Interp, m_sampleRateMode, m_settings, and sendSettings().
 {
     if (m_sampleRateMode) {
         m_settings.m_devSampleRate = value;
     } else {
         m_settings.m_devSampleRate = value * (1 << m_settings.m_log2Interp);
     }
     sendSettings();
 }
on_sampleRateMode_toggled
void BladeRF2OutputGui::on_sampleRateMode_toggled (bool checked) private slot
Definition at line 388 of file bladerf2outputgui.cpp.
References displaySampleRate(), and m_sampleRateMode.
 {
     m_sampleRateMode = checked;
     displaySampleRate();
 }
on_startStop_toggled
void BladeRF2OutputGui::on_startStop_toggled (bool checked) private slot
Definition at line 379 of file bladerf2outputgui.cpp.
References BladeRF2Output::MsgStartStop::create(), DeviceSampleSink::getInputMessageQueue(), m_doApplySettings, m_sampleSink, and MessageQueue::push().
 {
     if (m_doApplySettings)
     {
         BladeRF2Output::MsgStartStop *message = BladeRF2Output::MsgStartStop::create(checked);
         m_sampleSink->getInputMessageQueue()->push(message);
     }
 }
on_transverter_clicked
void BladeRF2OutputGui::on_transverter_clicked () private slot
Definition at line 369 of file bladerf2outputgui.cpp.
References m_settings, BladeRF2OutputSettings::m_transverterDeltaFrequency, BladeRF2OutputSettings::m_transverterMode, sendSettings(), setCenterFrequencySetting(), ui, and updateFrequencyLimits().
 {
     m_settings.m_transverterMode = ui->transverter->getDeltaFrequencyAcive();
     m_settings.m_transverterDeltaFrequency = ui->transverter->getDeltaFrequency();
     qDebug("LimeSDRInputGUI::on_transverter_clicked: %lld Hz %s", m_settings.m_transverterDeltaFrequency, m_settings.m_transverterMode ? "on" : "off");
     updateFrequencyLimits();
     setCenterFrequencySetting(ui->centerFrequency->getValueNew());
     sendSettings();
 }
openDeviceSettingsDialog
void BladeRF2OutputGui::openDeviceSettingsDialog (const QPoint & p) private slot
Definition at line 435 of file bladerf2outputgui.cpp.
References BasicDeviceSettingsDialog::getReverseAPIAddress(), BasicDeviceSettingsDialog::getReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::getReverseAPIPort(), BladeRF2OutputSettings::m_reverseAPIAddress, BladeRF2OutputSettings::m_reverseAPIDeviceIndex, BladeRF2OutputSettings::m_reverseAPIPort, m_settings, BladeRF2OutputSettings::m_useReverseAPI, sendSettings(), BasicDeviceSettingsDialog::setReverseAPIAddress(), BasicDeviceSettingsDialog::setReverseAPIDeviceIndex(), BasicDeviceSettingsDialog::setReverseAPIPort(), BasicDeviceSettingsDialog::setUseReverseAPI(), and BasicDeviceSettingsDialog::useReverseAPI().
Referenced by BladeRF2OutputGui().
 {
     BasicDeviceSettingsDialog dialog(this);
     dialog.setUseReverseAPI(m_settings.m_useReverseAPI);
     dialog.setReverseAPIAddress(m_settings.m_reverseAPIAddress);
     dialog.setReverseAPIPort(m_settings.m_reverseAPIPort);
     dialog.setReverseAPIDeviceIndex(m_settings.m_reverseAPIDeviceIndex);
     dialog.move(p);
     dialog.exec();
     m_settings.m_useReverseAPI = dialog.useReverseAPI();
     m_settings.m_reverseAPIAddress = dialog.getReverseAPIAddress();
     m_settings.m_reverseAPIPort = dialog.getReverseAPIPort();
     m_settings.m_reverseAPIDeviceIndex = dialog.getReverseAPIDeviceIndex();
     sendSettings();
 }
resetToDefaults()
void BladeRF2OutputGui::resetToDefaults () virtual
Implements PluginInstanceGUI.
Definition at line 107 of file bladerf2outputgui.cpp.
References displaySettings(), m_settings, BladeRF2OutputSettings::resetToDefaults(), and sendSettings().
Referenced by deserialize().
 {
     m_settings.resetToDefaults();
     displaySettings();
     sendSettings();
 }
sendSettings()
void BladeRF2OutputGui::sendSettings () private
Definition at line 302 of file bladerf2outputgui.cpp.
References m_updateTimer.
Referenced by deserialize(), on_bandwidth_changed(), on_biasTee_toggled(), on_centerFrequency_changed(), on_gain_valueChanged(), on_interp_currentIndexChanged(), on_LOppm_valueChanged(), on_sampleRate_changed(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), and setCenterFrequency().
 {
     if(!m_updateTimer.isActive())
         m_updateTimer.start(100);
 }
serialize()
QByteArray BladeRF2OutputGui::serialize () const virtual
Implements PluginInstanceGUI.
Definition at line 126 of file bladerf2outputgui.cpp.
References m_settings, and BladeRF2OutputSettings::serialize().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void BladeRF2OutputGui::setCenterFrequency (qint64 centerFrequency) virtual
Implements PluginInstanceGUI.
Definition at line 119 of file bladerf2outputgui.cpp.
References displaySettings(), BladeRF2OutputSettings::m_centerFrequency, m_settings, and sendSettings().
 {
     m_settings.m_centerFrequency = centerFrequency;
     displaySettings();
     sendSettings();
 }
setCenterFrequencySetting()
void BladeRF2OutputGui::setCenterFrequencySetting (uint64_t kHzValue) private
Definition at line 162 of file bladerf2outputgui.cpp.
References arg(), BladeRF2OutputSettings::m_centerFrequency, m_settings, and ui.
Referenced by on_transverter_clicked().
 {
     int64_t centerFrequency = kHzValue*1000;
     m_settings.m_centerFrequency = centerFrequency < 0 ? 0 : (uint64_t) centerFrequency;
     ui->centerFrequency->setToolTip(QString("Main center frequency in kHz (LO: %1 kHz)").arg(centerFrequency/1000));
 }
setName()
void BladeRF2OutputGui::setName (const QString & name) virtual
Implements PluginInstanceGUI.
Definition at line 97 of file bladerf2outputgui.cpp.
 {
     setObjectName(name);
 }
updateFrequencyLimits()
void BladeRF2OutputGui::updateFrequencyLimits () private
Definition at line 144 of file bladerf2outputgui.cpp.
References BladeRF2Output::getFrequencyRange(), m_sampleSink, m_settings, BladeRF2OutputSettings::m_transverterDeltaFrequency, BladeRF2OutputSettings::m_transverterMode, and ui.
Referenced by on_transverter_clicked().
 {
     // values in kHz
     uint64_t f_min, f_max;
     int step;
     qint64 deltaFrequency = m_settings.m_transverterMode ? m_settings.m_transverterDeltaFrequency/1000 : 0;
     m_sampleSink->getFrequencyRange(f_min, f_max, step);
     qint64 minLimit = f_min/1000 + deltaFrequency;
     qint64 maxLimit = f_max/1000 + deltaFrequency;
     minLimit = minLimit < 0 ? 0 : minLimit > 9999999 ? 9999999 : minLimit;
     maxLimit = maxLimit < 0 ? 0 : maxLimit > 9999999 ? 9999999 : maxLimit;
     qDebug("BladeRF2OutputGui::updateFrequencyLimits: delta: %lld min: %lld max: %lld", deltaFrequency, minLimit, maxLimit);
     ui->centerFrequency->setValueRange(7, minLimit, maxLimit);
 }
updateHardware
void BladeRF2OutputGui::updateHardware () private slot
Definition at line 394 of file bladerf2outputgui.cpp.
References BladeRF2Output::MsgConfigureBladeRF2::create(), DeviceSampleSink::getInputMessageQueue(), m_doApplySettings, m_forceSettings, m_sampleSink, m_settings, m_updateTimer, and MessageQueue::push().
Referenced by BladeRF2OutputGui().
 {
     if (m_doApplySettings)
     {
         qDebug() << "BladeRF2OutputGui::updateHardware";
         BladeRF2Output::MsgConfigureBladeRF2* message = BladeRF2Output::MsgConfigureBladeRF2::create(m_settings, m_forceSettings);
         m_sampleSink->getInputMessageQueue()->push(message);
         m_forceSettings = false;
         m_updateTimer.stop();
     }
 }
updateSampleRateAndFrequency()
void BladeRF2OutputGui::updateSampleRateAndFrequency () private
Definition at line 241 of file bladerf2outputgui.cpp.
References displaySampleRate(), DeviceUISet::getSpectrum(), m_deviceCenterFrequency, m_deviceUISet, m_sampleRate, GLSpectrum::setCenterFrequency(), and GLSpectrum::setSampleRate().
Referenced by handleInputMessages().
 {
     m_deviceUISet->getSpectrum()->setSampleRate(m_sampleRate);
     m_deviceUISet->getSpectrum()->setCenterFrequency(m_deviceCenterFrequency);
     displaySampleRate();
 }
updateStatus
void BladeRF2OutputGui::updateStatus () private slot
Definition at line 406 of file bladerf2outputgui.cpp.
References DeviceAPI::errorMessage(), DeviceUISet::m_deviceAPI, m_deviceUISet, m_lastEngineState, DeviceAPI::state(), DeviceAPI::StError, DeviceAPI::StIdle, DeviceAPI::StNotStarted, DeviceAPI::StRunning, and ui.
Referenced by BladeRF2OutputGui().
 {
     int state = m_deviceUISet->m_deviceAPI->state();
     if(m_lastEngineState != state)
     {
         switch(state)
         {
             case DeviceAPI::StNotStarted:
                 ui->startStop->setStyleSheet("QToolButton { background:rgb(79,79,79); }");
                 break;
             case DeviceAPI::StIdle:
                 ui->startStop->setStyleSheet("QToolButton { background-color : blue; }");
                 break;
             case DeviceAPI::StRunning:
                 ui->startStop->setStyleSheet("QToolButton { background-color : green; }");
                 break;
             case DeviceAPI::StError:
                 ui->startStop->setStyleSheet("QToolButton { background-color : red; }");
                 QMessageBox::information(this, tr("Message"), m_deviceUISet->m_deviceAPI->errorMessage());
                 break;
             default:
                 break;
         }
         m_lastEngineState = state;
     }
 }
Member Data Documentation
m_deviceCenterFrequency
quint64 BladeRF2OutputGui::m_deviceCenterFrequency private
Center frequency in device.
Definition at line 67 of file bladerf2outputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_deviceUISet
DeviceUISet* BladeRF2OutputGui::m_deviceUISet private
Definition at line 58 of file bladerf2outputgui.h.
Referenced by BladeRF2OutputGui(), updateSampleRateAndFrequency(), and updateStatus().
m_doApplySettings
bool BladeRF2OutputGui::m_doApplySettings private
Definition at line 59 of file bladerf2outputgui.h.
Referenced by on_startStop_toggled(), and updateHardware().
m_forceSettings
bool BladeRF2OutputGui::m_forceSettings private
Definition at line 60 of file bladerf2outputgui.h.
Referenced by deserialize(), and updateHardware().
m_inputMessageQueue
MessageQueue BladeRF2OutputGui::m_inputMessageQueue private
Definition at line 69 of file bladerf2outputgui.h.
Referenced by BladeRF2OutputGui(), and handleInputMessages().
m_lastEngineState
int BladeRF2OutputGui::m_lastEngineState private
Definition at line 68 of file bladerf2outputgui.h.
Referenced by updateStatus().
m_sampleRate
int BladeRF2OutputGui::m_sampleRate private
Definition at line 66 of file bladerf2outputgui.h.
Referenced by handleInputMessages(), and updateSampleRateAndFrequency().
m_sampleRateMode
bool BladeRF2OutputGui::m_sampleRateMode private
true: device, false: base band sample rate update mode
Definition at line 62 of file bladerf2outputgui.h.
Referenced by displaySampleRate(), on_interp_currentIndexChanged(), on_sampleRate_changed(), and on_sampleRateMode_toggled().
m_sampleSink
BladeRF2Output* BladeRF2OutputGui::m_sampleSink private
Definition at line 65 of file bladerf2outputgui.h.
Referenced by BladeRF2OutputGui(), displaySampleRate(), handleMessage(), on_startStop_toggled(), updateFrequencyLimits(), and updateHardware().
m_settings
BladeRF2OutputSettings BladeRF2OutputGui::m_settings private
Definition at line 61 of file bladerf2outputgui.h.
Referenced by deserialize(), displaySampleRate(), displaySettings(), getCenterFrequency(), handleMessage(), on_bandwidth_changed(), on_biasTee_toggled(), on_centerFrequency_changed(), on_gain_valueChanged(), on_interp_currentIndexChanged(), on_LOppm_valueChanged(), on_sampleRate_changed(), on_transverter_clicked(), openDeviceSettingsDialog(), resetToDefaults(), serialize(), setCenterFrequency(), setCenterFrequencySetting(), updateFrequencyLimits(), and updateHardware().
m_statusTimer
QTimer BladeRF2OutputGui::m_statusTimer private
Definition at line 64 of file bladerf2outputgui.h.
Referenced by BladeRF2OutputGui().
m_updateTimer
QTimer BladeRF2OutputGui::m_updateTimer private
Definition at line 63 of file bladerf2outputgui.h.
Referenced by BladeRF2OutputGui(), sendSettings(), and updateHardware().
ui
Ui::BladeRF2OutputGui* BladeRF2OutputGui::ui private
Definition at line 56 of file bladerf2outputgui.h.
Referenced by BladeRF2OutputGui(), displaySampleRate(), displaySettings(), handleMessage(), on_gain_valueChanged(), on_interp_currentIndexChanged(), on_LOppm_valueChanged(), on_transverter_clicked(), setCenterFrequencySetting(), updateFrequencyLimits(), updateStatus(), and ~BladeRF2OutputGui().
The documentation for this class was generated from the following files:
plugins/samplesink/bladerf2output/bladerf2outputgui.h
plugins/samplesink/bladerf2output/bladerf2outputgui.cpp