SDRAngel: hidapi API
hidapi API
Functions
int HID_API_EXPORT HID_API_CALL hid_init (void)
Initialize the HIDAPI library.
int HID_API_EXPORT HID_API_CALL hid_exit (void)
Finalize the HIDAPI library.
struct hid_device_info HID_API_EXPORT *HID_API_CALL hid_enumerate (unsigned short vendor_id, unsigned short product_id)
Enumerate the HID Devices.
void HID_API_EXPORT HID_API_CALL hid_free_enumeration (struct hid_device_info *devs)
Free an enumeration Linked List.
HID_API_EXPORT hid_device *HID_API_CALL hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t *serial_number)
Open a HID device using a Vendor ID (VID), Product ID (PID) and optionally a serial number.
HID_API_EXPORT hid_device *HID_API_CALL hid_open_path (const char *path)
Open a HID device by its path name.
int HID_API_EXPORT HID_API_CALL hid_write (hid_device *device, const unsigned char *data, size_t length)
Write an Output report to a HID device.
int HID_API_EXPORT HID_API_CALL hid_read_timeout (hid_device *dev, unsigned char *data, size_t length, int milliseconds)
Read an Input report from a HID device with timeout.
int HID_API_EXPORT HID_API_CALL hid_read (hid_device *device, unsigned char *data, size_t length)
Read an Input report from a HID device.
int HID_API_EXPORT HID_API_CALL hid_set_nonblocking (hid_device *device, int nonblock)
Set the device handle to be non-blocking.
int HID_API_EXPORT HID_API_CALL hid_send_feature_report (hid_device *device, const unsigned char *data, size_t length)
Send a Feature report to the device.
int HID_API_EXPORT HID_API_CALL hid_get_feature_report (hid_device *device, unsigned char *data, size_t length)
Get a feature report from a HID device.
void HID_API_EXPORT HID_API_CALL hid_close (hid_device *device)
Close a HID device.
int HID_API_EXPORT_CALL hid_get_manufacturer_string (hid_device *device, wchar_t *string, size_t maxlen)
Get The Manufacturer String from a HID device.
int HID_API_EXPORT_CALL hid_get_product_string (hid_device *device, wchar_t *string, size_t maxlen)
Get The Product String from a HID device.
int HID_API_EXPORT_CALL hid_get_serial_number_string (hid_device *device, wchar_t *string, size_t maxlen)
Get The Serial Number String from a HID device.
int HID_API_EXPORT_CALL hid_get_indexed_string (hid_device *device, int string_index, wchar_t *string, size_t maxlen)
Get a string from a HID device, based on its string index.
HID_API_EXPORT const wchar_t *HID_API_CALL hid_error (hid_device *device)
Get a string describing the last error which occurred.
Detailed Description
Function Documentation
hid_close()
void HID_API_EXPORT HID_API_CALL hid_close (hid_device * device)
Close a HID device.
Parameters
device A device handle returned from hid_open().
Definition at line 1157 of file hid-libusb.c.
References hid_device_::device_handle, hid_device_::input_reports, hid_device_::interface, hid_device_::mutex, hid_device_::shutdown_thread, hid_device_::thread, and hid_device_::transfer.
Referenced by fcdClose().
 {
     if (!dev)
         return;
     /* Cause read_thread() to stop. */
     dev->shutdown_thread = 1;
     libusb_cancel_transfer(dev->transfer);
     /* Wait for read_thread() to end. */
     pthread_join(dev->thread, NULL);
     /* Clean up the Transfer objects allocated in read_thread(). */
     free(dev->transfer->buffer);
     libusb_free_transfer(dev->transfer);
     /* release the interface */
     libusb_release_interface(dev->device_handle, dev->interface);
     /* Close the handle */
     libusb_close(dev->device_handle);
     /* Clear out the queue of received reports. */
     pthread_mutex_lock(&dev->mutex);
     while (dev->input_reports) {
         return_data(dev, NULL, 0);
     }
     pthread_mutex_unlock(&dev->mutex);
     free_hid_device(dev);
 }
hid_enumerate()
struct hid_device_info HID_API_EXPORT* HID_API_CALL hid_enumerate (unsigned short vendor_id, unsigned short product_id)
Enumerate the HID Devices.
This function returns a linked list of all the HID devices attached to the system which match vendor_id and product_id. If vendor_id is set to 0 then any vendor matches. If product_id is set to 0 then any product matches. If vendor_id and product_id are both set to 0, then all HID devices will be returned.
Parameters
vendor_id The Vendor ID (VID) of the types of device to open.
product_id The Product ID (PID) of the types of device to open.
Returns
This function returns a pointer to a linked list of type struct hid_device, containing information about the HID devices attached to the system, or NULL in the case of failure. Free this linked list by calling hid_free_enumeration().
Definition at line 444 of file hid-libusb.c.
References hid_init(), i, hid_device_info::next, and hid_device_info::path.
Referenced by FCDProPlugin::enumSampleSources(), FCDProPlusPlugin::enumSampleSources(), fcdOpen(), and hid_open().
 {
     libusb_device **devs;
     libusb_device *dev;
     libusb_device_handle *handle;
     ssize_t num_devs;
     int i = 0;
     struct hid_device_info *root = NULL; /* return object */
     struct hid_device_info *cur_dev = NULL;
     if(hid_init() < 0)
         return NULL;
     num_devs = libusb_get_device_list(usb_context, &devs);
     if (num_devs < 0)
         return NULL;
     while ((dev = devs[i++]) != NULL) {
         struct libusb_device_descriptor desc;
         struct libusb_config_descriptor *conf_desc = NULL;
         int j, k;
         int interface_num = 0;
         int res = libusb_get_device_descriptor(dev, &desc);
         unsigned short dev_vid = desc.idVendor;
         unsigned short dev_pid = desc.idProduct;
         res = libusb_get_active_config_descriptor(dev, &conf_desc);
         if (res < 0)
             libusb_get_config_descriptor(dev, 0, &conf_desc);
         if (conf_desc) {
             for (j = 0; j < conf_desc->bNumInterfaces; j++) {
                 const struct libusb_interface *intf = &conf_desc->interface[j];
                 for (k = 0; k < intf->num_altsetting; k++) {
                     const struct libusb_interface_descriptor *intf_desc;
                     intf_desc = &intf->altsetting[k];
                     if (intf_desc->bInterfaceClass == LIBUSB_CLASS_HID) {
                         interface_num = intf_desc->bInterfaceNumber;
                         /* Check the VID/PID against the arguments */
                         if ((vendor_id == 0x0 || vendor_id == dev_vid) &&
                             (product_id == 0x0 || product_id == dev_pid)) {
                             struct hid_device_info *tmp;
                             /* VID/PID match. Create the record. */
                             tmp = calloc(1, sizeof(struct hid_device_info));
                             if (cur_dev) {
                                 cur_dev->next = tmp;
                             }
                             else {
                                 root = tmp;
                             }
                             cur_dev = tmp;
                             /* Fill out the record */
                             cur_dev->next = NULL;
                             cur_dev->path = make_path(dev, interface_num);
                             res = libusb_open(dev, &handle);
                             if (res >= 0) {
                                 /* Serial Number */
                                 if (desc.iSerialNumber > 0)
                                     cur_dev->serial_number =
                                         get_usb_string(handle, desc.iSerialNumber);
                                 /* Manufacturer and Product strings */
                                 if (desc.iManufacturer > 0)
                                     cur_dev->manufacturer_string =
                                         get_usb_string(handle, desc.iManufacturer);
                                 if (desc.iProduct > 0)
                                     cur_dev->product_string =
                                         get_usb_string(handle, desc.iProduct);
 #ifdef INVASIVE_GET_USAGE
 {
                             /*
                             This section is removed because it is too
                             invasive on the system. Getting a Usage Page
                             and Usage requires parsing the HID Report
                             descriptor. Getting a HID Report descriptor
                             involves claiming the interface. Claiming the
                             interface involves detaching the kernel driver.
                             Detaching the kernel driver is hard on the system
                             because it will unclaim interfaces (if another
                             app has them claimed) and the re-attachment of
                             the driver will sometimes change /dev entry names.
                             It is for these reasons that this section is
                             #if 0. For composite devices, use the interface
                             field in the hid_device_info struct to distinguish
                             between interfaces. */
                                 unsigned char data[256];
 #ifdef DETACH_KERNEL_DRIVER
                                 int detached = 0;
                                 /* Usage Page and Usage */
                                 res = libusb_kernel_driver_active(handle, interface_num);
                                 if (res == 1) {
                                     res = libusb_detach_kernel_driver(handle, interface_num);
                                     if (res < 0)
                                         LOG("Couldn't detach kernel driver, even though a kernel driver was attached.");
                                     else
                                         detached = 1;
                                 }
 #endif
                                 res = libusb_claim_interface(handle, interface_num);
                                 if (res >= 0) {
                                     /* Get the HID Report Descriptor. */
                                     res = libusb_control_transfer(handle, LIBUSB_ENDPOINT_IN|LIBUSB_RECIPIENT_INTERFACE, LIBUSB_REQUEST_GET_DESCRIPTOR, (LIBUSB_DT_REPORT << 8)|interface_num, 0, data, sizeof(data), 5000);
                                     if (res >= 0) {
                                         unsigned short page=0, usage=0;
                                         /* Parse the usage and usage page
                                            out of the report descriptor. */
                                         get_usage(data, res,  &page, &usage);
                                         cur_dev->usage_page = page;
                                         cur_dev->usage = usage;
                                     }
                                     else
                                         LOG("libusb_control_transfer() for getting the HID report failed with %d\n", res);
                                     /* Release the interface */
                                     res = libusb_release_interface(handle, interface_num);
                                     if (res < 0)
                                         LOG("Can't release the interface.\n");
                                 }
                                 else
                                     LOG("Can't claim interface %d\n", res);
 #ifdef DETACH_KERNEL_DRIVER
                                 /* Re-attach kernel driver if necessary. */
                                 if (detached) {
                                     res = libusb_attach_kernel_driver(handle, interface_num);
                                     if (res < 0)
                                         LOG("Couldn't re-attach kernel driver.\n");
                                 }
 #endif
 }
 #endif /* INVASIVE_GET_USAGE */
                                 libusb_close(handle);
                             }
                             /* VID/PID */
                             cur_dev->vendor_id = dev_vid;
                             cur_dev->product_id = dev_pid;
                             /* Release Number */
                             cur_dev->release_number = desc.bcdDevice;
                             /* Interface Number */
                             cur_dev->interface_number = interface_num;
                         }
                     }
                 } /* altsettings */
             } /* interfaces */
             libusb_free_config_descriptor(conf_desc);
         }
     }
     libusb_free_device_list(devs, 1);
     return root;
 }
hid_error()
HID_API_EXPORT const wchar_t* HID_API_CALL hid_error (hid_device * device)
Get a string describing the last error which occurred.
Parameters
device A device handle returned from hid_open().
Returns
This function returns a string containing the last error which occurred or NULL if none has occurred.
Definition at line 1221 of file hid-libusb.c.
 {
     return NULL;
 }
hid_exit()
int HID_API_EXPORT HID_API_CALL hid_exit (void)
Finalize the HIDAPI library.
This function frees all of the static data associated with HIDAPI. It should be called at the end of execution to avoid memory leaks.
Returns
This function returns 0 on success and -1 on error.
Definition at line 434 of file hid-libusb.c.
 {
     if (usb_context) {
         libusb_exit(usb_context);
         usb_context = NULL;
     }
     return 0;
 }
hid_free_enumeration()
void HID_API_EXPORT HID_API_CALL hid_free_enumeration (struct hid_device_info * devs)
Free an enumeration Linked List.
This function frees a linked list created by hid_enumerate().
Parameters
devs Pointer to a list of struct_device returned from hid_enumerate().
Definition at line 605 of file hid-libusb.c.
References hid_device_info::manufacturer_string, hid_device_info::next, input_report::next, hid_device_info::path, hid_device_info::product_string, and hid_device_info::serial_number.
Referenced by fcdOpen(), and hid_open().
 {
     struct hid_device_info *d = devs;
     while (d) {
         struct hid_device_info *next = d->next;
         free(d->path);
         free(d->serial_number);
         free(d->manufacturer_string);
         free(d->product_string);
         free(d);
         d = next;
     }
 }
hid_get_feature_report()
int HID_API_EXPORT HID_API_CALL hid_get_feature_report (hid_device * device, unsigned char * data, size_t length)
Get a feature report from a HID device.
Make sure to set the first byte of data[] to the Report ID of the report to be read. Make sure to allow space for this extra byte in data[].
Parameters
device A device handle returned from hid_open().
data A buffer to put the read data into, including the Report ID. Set the first byte of data[] to the Report ID of the report to be read.
length The number of bytes to read, including an extra byte for the report ID. The buffer can be longer than the actual report.
Returns
This function returns the number of bytes read and -1 on error.
Definition at line 1126 of file hid-libusb.c.
References hid_device_::device_handle, and hid_device_::interface.
 {
     int res = -1;
     int skipped_report_id = 0;
     int report_number = data[0];
     if (report_number == 0x0) {
         /* Offset the return buffer by 1, so that the report ID
            will remain in byte 0. */
         data++;
         length--;
         skipped_report_id = 1;
     }
     res = libusb_control_transfer(dev->device_handle,
         LIBUSB_REQUEST_TYPE_CLASS|LIBUSB_RECIPIENT_INTERFACE|LIBUSB_ENDPOINT_IN,
         0x01/*HID get_report*/,
         (3/*HID feature*/ << 8) | report_number,
         dev->interface,
         (unsigned char *)data, length,
         1000/*timeout millis*/);
     if (res < 0)
         return -1;
     if (skipped_report_id)
         res++;
     return res;
 }
hid_get_indexed_string()
int HID_API_EXPORT_CALL hid_get_indexed_string (hid_device * device, int string_index, wchar_t * string, size_t maxlen)
Get a string from a HID device, based on its string index.
Parameters
device A device handle returned from hid_open().
string_index The index of the string to get.
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error.
Definition at line 1205 of file hid-libusb.c.
Referenced by hid_get_manufacturer_string(), hid_get_product_string(), and hid_get_serial_number_string().
 {
     wchar_t *str;
     str = get_usb_string(dev->device_handle, string_index);
     if (str) {
         wcsncpy(string, str, maxlen);
         string[maxlen-1] = L'\0';
         free(str);
         return 0;
     }
     else
         return -1;
 }
hid_get_manufacturer_string()
int HID_API_EXPORT_CALL hid_get_manufacturer_string (hid_device * device, wchar_t * string, size_t maxlen)
Get The Manufacturer String from a HID device.
Parameters
device A device handle returned from hid_open().
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error.
Definition at line 1190 of file hid-libusb.c.
References hid_get_indexed_string(), and hid_device_::manufacturer_index.
 {
     return hid_get_indexed_string(dev, dev->manufacturer_index, string, maxlen);
 }
hid_get_product_string()
int HID_API_EXPORT_CALL hid_get_product_string (hid_device * device, wchar_t * string, size_t maxlen)
Get The Product String from a HID device.
Parameters
device A device handle returned from hid_open().
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error.
Definition at line 1195 of file hid-libusb.c.
References hid_get_indexed_string(), and hid_device_::product_index.
 {
     return hid_get_indexed_string(dev, dev->product_index, string, maxlen);
 }
hid_get_serial_number_string()
int HID_API_EXPORT_CALL hid_get_serial_number_string (hid_device * device, wchar_t * string, size_t maxlen)
Get The Serial Number String from a HID device.
Parameters
device A device handle returned from hid_open().
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error.
Definition at line 1200 of file hid-libusb.c.
References hid_get_indexed_string(), and hid_device_::serial_index.
 {
     return hid_get_indexed_string(dev, dev->serial_index, string, maxlen);
 }
hid_init()
int HID_API_EXPORT HID_API_CALL hid_init (void)
Initialize the HIDAPI library.
This function initializes the HIDAPI library. Calling it is not strictly necessary, as it will be called automatically by hid_enumerate() and any of the hid_open_*() functions if it is needed. This function should be called at the beginning of execution however, if there is a chance of HIDAPI handles being opened by different threads simultaneously.
Returns
This function returns 0 on success and -1 on error.
Definition at line 416 of file hid-libusb.c.
Referenced by hid_enumerate(), and hid_open_path().
 {
     if (!usb_context) {
         const char *locale;
         /* Init Libusb */
         if (libusb_init(&usb_context))
             return -1;
         /* Set the locale if it's not set. */
         locale = setlocale(LC_CTYPE, NULL);
         if (!locale)
             setlocale(LC_CTYPE, "");
     }
     return 0;
 }
hid_open()
HID_API_EXPORT hid_device* HID_API_CALL hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t * serial_number)
Open a HID device using a Vendor ID (VID), Product ID (PID) and optionally a serial number.
If serial_number is NULL, the first device with the specified VID and PID is opened.
Parameters
vendor_id The Vendor ID (VID) of the device to open.
product_id The Product ID (PID) of the device to open.
serial_number The Serial Number of the device to open (Optionally NULL).
Returns
This function returns a pointer to a hid_device object on success or NULL on failure.
Definition at line 619 of file hid-libusb.c.
References hid_enumerate(), hid_free_enumeration(), hid_open_path(), hid_device_info::next, hid_device_info::path, hid_device_info::product_id, hid_device_info::serial_number, and hid_device_info::vendor_id.
 {
     struct hid_device_info *devs, *cur_dev;
     const char *path_to_open = NULL;
     hid_device *handle = NULL;
     devs = hid_enumerate(vendor_id, product_id);
     cur_dev = devs;
     while (cur_dev) {
         if (cur_dev->vendor_id == vendor_id &&
             cur_dev->product_id == product_id) {
             if (serial_number) {
                 if (wcscmp(serial_number, cur_dev->serial_number) == 0) {
                     path_to_open = cur_dev->path;
                     break;
                 }
             }
             else {
                 path_to_open = cur_dev->path;
                 break;
             }
         }
         cur_dev = cur_dev->next;
     }
     if (path_to_open) {
         /* Open the device */
         handle = hid_open_path(path_to_open);
     }
     hid_free_enumeration(devs);
     return handle;
 }
hid_open_path()
HID_API_EXPORT hid_device* HID_API_CALL hid_open_path (const char * path)
Open a HID device by its path name.
The path name be determined by calling hid_enumerate(), or a platform-specific path name can be used (eg: /dev/hidraw0 on Linux).
Parameters
path The path name of the device to open
Returns
This function returns a pointer to a hid_device object on success or NULL on failure.
Definition at line 792 of file hid-libusb.c.
References hid_init().
Referenced by fcdOpen(), and hid_open().
 {
     hid_device *dev = NULL;
     libusb_device **devs;
     libusb_device *usb_dev;
     int res;
     int d = 0;
     int good_open = 0;
     if(hid_init() < 0)
         return NULL;
     dev = new_hid_device();
     libusb_get_device_list(usb_context, &devs);
     while ((usb_dev = devs[d++]) != NULL) {
         struct libusb_device_descriptor desc;
         struct libusb_config_descriptor *conf_desc = NULL;
         int i,j,k;
         libusb_get_device_descriptor(usb_dev, &desc);
         if (libusb_get_active_config_descriptor(usb_dev, &conf_desc) < 0)
             continue;
         for (j = 0; j < conf_desc->bNumInterfaces; j++) {
             const struct libusb_interface *intf = &conf_desc->interface[j];
             for (k = 0; k < intf->num_altsetting; k++) {
                 const struct libusb_interface_descriptor *intf_desc;
                 intf_desc = &intf->altsetting[k];
                 if (intf_desc->bInterfaceClass == LIBUSB_CLASS_HID) {
                     char *dev_path = make_path(usb_dev, intf_desc->bInterfaceNumber);
                     if (!strcmp(dev_path, path)) {
                         /* Matched Paths. Open this device */
                         /* OPEN HERE */
                         res = libusb_open(usb_dev, &dev->device_handle);
                         if (res < 0) {
                             LOG("can't open device\n");
                             free(dev_path);
                             break;
                         }
                         good_open = 1;
 #ifdef DETACH_KERNEL_DRIVER
                         /* Detach the kernel driver, but only if the
                            device is managed by the kernel */
                         if (libusb_kernel_driver_active(dev->device_handle, intf_desc->bInterfaceNumber) == 1) {
                             res = libusb_detach_kernel_driver(dev->device_handle, intf_desc->bInterfaceNumber);
                             if (res < 0) {
                                 libusb_close(dev->device_handle);
                                 LOG("Unable to detach Kernel Driver\n");
                                 free(dev_path);
                                 good_open = 0;
                                 break;
                             }
                         }
 #endif
                         res = libusb_claim_interface(dev->device_handle, intf_desc->bInterfaceNumber);
                         if (res < 0) {
                             LOG("can't claim interface %d: %d\n", intf_desc->bInterfaceNumber, res);
                             free(dev_path);
                             libusb_close(dev->device_handle);
                             good_open = 0;
                             break;
                         }
                         /* Store off the string descriptor indexes */
                         dev->manufacturer_index = desc.iManufacturer;
                         dev->product_index      = desc.iProduct;
                         dev->serial_index       = desc.iSerialNumber;
                         /* Store off the interface number */
                         dev->interface = intf_desc->bInterfaceNumber;
                         /* Find the INPUT and OUTPUT endpoints. An
                            OUTPUT endpoint is not required. */
                         for (i = 0; i < intf_desc->bNumEndpoints; i++) {
                             const struct libusb_endpoint_descriptor *ep
                                 = &intf_desc->endpoint[i];
                             /* Determine the type and direction of this
                                endpoint. */
                             int is_interrupt =
                                 (ep->bmAttributes & LIBUSB_TRANSFER_TYPE_MASK)
                                   == LIBUSB_TRANSFER_TYPE_INTERRUPT;
                             int is_output =
                                 (ep->bEndpointAddress & LIBUSB_ENDPOINT_DIR_MASK)
                                   == LIBUSB_ENDPOINT_OUT;
                             int is_input =
                                 (ep->bEndpointAddress & LIBUSB_ENDPOINT_DIR_MASK)
                                   == LIBUSB_ENDPOINT_IN;
                             /* Decide whether to use it for intput or output. */
                             if (dev->input_endpoint == 0 &&
                                 is_interrupt && is_input) {
                                 /* Use this endpoint for INPUT */
                                 dev->input_endpoint = ep->bEndpointAddress;
                                 dev->input_ep_max_packet_size = ep->wMaxPacketSize;
                             }
                             if (dev->output_endpoint == 0 &&
                                 is_interrupt && is_output) {
                                 /* Use this endpoint for OUTPUT */
                                 dev->output_endpoint = ep->bEndpointAddress;
                             }
                         }
                         pthread_create(&dev->thread, NULL, read_thread, dev);
                         /* Wait here for the read thread to be initialized. */
                         pthread_barrier_wait(&dev->barrier);
                     }
                     free(dev_path);
                 }
             }
         }
         libusb_free_config_descriptor(conf_desc);
     }
     libusb_free_device_list(devs, 1);
     /* If we have a good handle, return it. */
     if (good_open) {
         return dev;
     }
     else {
         /* Unable to open any devices. */
         free_hid_device(dev);
         return NULL;
     }
 }
hid_read()
int HID_API_EXPORT HID_API_CALL hid_read (hid_device * device, unsigned char * data, size_t length)
Read an Input report from a HID device.
Input reports are returned to the host through the INTERRUPT IN endpoint. The first byte will contain the Report number if the device uses numbered reports.
Parameters
device A device handle returned from hid_open().
data A buffer to put the read data into.
length The number of bytes to read. For devices with multiple reports, make sure to read an extra byte for the report number.
Returns
This function returns the actual number of bytes read and -1 on error. If no packet was available to be read and the handle is in non-blocking mode, this function returns 0.
Definition at line 1083 of file hid-libusb.c.
References hid_device_::blocking, and hid_read_timeout().
Referenced by fcdAppGetParam(), fcdAppSetFreq(), fcdAppSetFreqkHz(), fcdAppSetParam(), fcdBlErase(), fcdBlVerifyFirmware(), fcdBlWriteFirmware(), fcdGetCaps(), fcdGetCapsStr(), fcdGetFwVerStr(), and fcdGetMode().
 {
     return hid_read_timeout(dev, data, length, dev->blocking ? -1 : 0);
 }
hid_read_timeout()
int HID_API_EXPORT HID_API_CALL hid_read_timeout (hid_device * dev, unsigned char * data, size_t length, int milliseconds)
Read an Input report from a HID device with timeout.
Input reports are returned to the host through the INTERRUPT IN endpoint. The first byte will contain the Report number if the device uses numbered reports.
Parameters
device A device handle returned from hid_open().
data A buffer to put the read data into.
length The number of bytes to read. For devices with multiple reports, make sure to read an extra byte for the report number.
milliseconds timeout in milliseconds or -1 for blocking wait.
Returns
This function returns the actual number of bytes read and -1 on error. If no packet was available to be read within the timeout period, this function returns 0.
Definition at line 998 of file hid-libusb.c.
References hid_device_::device_handle, hid_device_::input_endpoint, LOG, and hid_device_::mutex.
Referenced by hid_read().
 {
     int bytes_read = -1;
 #if 0
     int transferred;
     int res = libusb_interrupt_transfer(dev->device_handle, dev->input_endpoint, data, length, &transferred, 5000);
     LOG("transferred: %d\n", transferred);
     return transferred;
 #endif
     pthread_mutex_lock(&dev->mutex);
     pthread_cleanup_push(&cleanup_mutex, dev);
     /* There's an input report queued up. Return it. */
     if (dev->input_reports) {
         /* Return the first one */
         bytes_read = return_data(dev, data, length);
         goto ret;
     }
     if (dev->shutdown_thread) {
         /* This means the device has been disconnected.
            An error code of -1 should be returned. */
         bytes_read = -1;
         goto ret;
     }
     if (milliseconds == -1) {
         /* Blocking */
         while (!dev->input_reports && !dev->shutdown_thread) {
             pthread_cond_wait(&dev->condition, &dev->mutex);
         }
         if (dev->input_reports) {
             bytes_read = return_data(dev, data, length);
         }
     }
     else if (milliseconds > 0) {
         /* Non-blocking, but called with timeout. */
         int res;
         struct timespec ts;
         clock_gettime(CLOCK_REALTIME, &ts);
         ts.tv_sec += milliseconds / 1000;
         ts.tv_nsec += (milliseconds % 1000) * 1000000;
         if (ts.tv_nsec >= 1000000000L) {
             ts.tv_sec++;
             ts.tv_nsec -= 1000000000L;
         }
         while (!dev->input_reports && !dev->shutdown_thread) {
             res = pthread_cond_timedwait(&dev->condition, &dev->mutex, &ts);
             if (res == 0) {
                 if (dev->input_reports) {
                     bytes_read = return_data(dev, data, length);
                     break;
                 }
                 /* If we're here, there was a spurious wake up
                    or the read thread was shutdown. Run the
                    loop again (ie: don't break). */
             }
             else if (res == ETIMEDOUT) {
                 /* Timed out. */
                 bytes_read = 0;
                 break;
             }
             else {
                 /* Error. */
                 bytes_read = -1;
                 break;
             }
         }
     }
     else {
         /* Purely non-blocking */
         bytes_read = 0;
     }
 ret:
     pthread_mutex_unlock(&dev->mutex);
     pthread_cleanup_pop(0);
     return bytes_read;
 }
hid_send_feature_report()
int HID_API_EXPORT HID_API_CALL hid_send_feature_report (hid_device * device, const unsigned char * data, size_t length)
Send a Feature report to the device.
Feature reports are sent over the Control endpoint as a Set_Report transfer. The first byte of data[] must contain the Report ID. For devices which only support a single report, this must be set to 0x0. The remaining bytes contain the report data. Since the Report ID is mandatory, calls to hid_send_feature_report() will always contain one more byte than the report contains. For example, if a hid report is 16 bytes long, 17 bytes must be passed to hid_send_feature_report(): the Report ID (or 0x0, for devices which do not use numbered reports), followed by the report data (16 bytes). In this example, the length passed in would be 17.
Parameters
device A device handle returned from hid_open().
data The data to send, including the report number as the first byte.
length The length in bytes of the data to send, including the report number.
Returns
This function returns the actual number of bytes written and -1 on error.
Definition at line 1096 of file hid-libusb.c.
References hid_device_::device_handle, and hid_device_::interface.
 {
     int res = -1;
     int skipped_report_id = 0;
     int report_number = data[0];
     if (report_number == 0x0) {
         data++;
         length--;
         skipped_report_id = 1;
     }
     res = libusb_control_transfer(dev->device_handle,
         LIBUSB_REQUEST_TYPE_CLASS|LIBUSB_RECIPIENT_INTERFACE|LIBUSB_ENDPOINT_OUT,
         0x09/*HID set_report*/,
         (3/*HID feature*/ << 8) | report_number,
         dev->interface,
         (unsigned char *)data, length,
         1000/*timeout millis*/);
     if (res < 0)
         return -1;
     /* Account for the report ID */
     if (skipped_report_id)
         length++;
     return length;
 }
hid_set_nonblocking()
int HID_API_EXPORT HID_API_CALL hid_set_nonblocking (hid_device * device, int nonblock)
Set the device handle to be non-blocking.
In non-blocking mode calls to hid_read() will return immediately with a value of 0 if there is no data to be read. In blocking mode, hid_read() will wait (block) until there is data to read before returning.
Nonblocking can be turned on and off at any time.
Parameters
device A device handle returned from hid_open().
nonblock enable or not the nonblocking reads
1 to enable nonblocking
0 to disable nonblocking.
Returns
This function returns 0 on success and -1 on error.
Definition at line 1088 of file hid-libusb.c.
References hid_device_::blocking.
 {
     dev->blocking = !nonblock;
     return 0;
 }
hid_write()
int HID_API_EXPORT HID_API_CALL hid_write (hid_device * device, const unsigned char * data, size_t length)
Write an Output report to a HID device.
The first byte of data[] must contain the Report ID. For devices which only support a single report, this must be set to 0x0. The remaining bytes contain the report data. Since the Report ID is mandatory, calls to hid_write() will always contain one more byte than the report contains. For example, if a hid report is 16 bytes long, 17 bytes must be passed to hid_write(), the Report ID (or 0x0, for devices with a single report), followed by the report data (16 bytes). In this example, the length passed in would be 17.
hid_write() will send the data on the first OUT endpoint, if one exists. If it does not, it will send the data through the Control Endpoint (Endpoint 0).
Parameters
device A device handle returned from hid_open().
data The data to send, including the report number as the first byte.
length The length in bytes of the data to send.
Returns
This function returns the actual number of bytes written and -1 on error.
Definition at line 925 of file hid-libusb.c.
References hid_device_::device_handle, hid_device_::interface, and hid_device_::output_endpoint.
Referenced by fcdAppGetParam(), fcdAppReset(), fcdAppSetFreq(), fcdAppSetFreqkHz(), fcdAppSetParam(), fcdBlErase(), fcdBlReset(), fcdBlVerifyFirmware(), fcdBlWriteFirmware(), fcdGetCaps(), fcdGetCapsStr(), fcdGetFwVerStr(), and fcdGetMode().
 {
     int res;
     int report_number = data[0];
     int skipped_report_id = 0;
     if (report_number == 0x0) {
         data++;
         length--;
         skipped_report_id = 1;
     }
     if (dev->output_endpoint <= 0) {
         /* No interrput out endpoint. Use the Control Endpoint */
         res = libusb_control_transfer(dev->device_handle,
             LIBUSB_REQUEST_TYPE_CLASS|LIBUSB_RECIPIENT_INTERFACE|LIBUSB_ENDPOINT_OUT,
             0x09/*HID Set_Report*/,
             (2/*HID output*/ << 8) | report_number,
             dev->interface,
             (unsigned char *)data, length,
             1000/*timeout millis*/);
         if (res < 0)
             return -1;
         if (skipped_report_id)
             length++;
         return length;
     }
     else {
         /* Use the interrupt out endpoint */
         int actual_length;
         res = libusb_interrupt_transfer(dev->device_handle,
             dev->output_endpoint,
             (unsigned char*)data,
             length,
             &actual_length, 1000);
         if (res < 0)
             return -1;
         if (skipped_report_id)
             actual_length++;
         return actual_length;
     }
 }