SDRAngel: LevelMeterSignalDB Class Reference
LevelMeterSignalDB Class Reference
#include <levelmeter.h>
Public Types
enum ColorTheme { ColorGold, ColorGreenYellow, ColorGreenAndBlue, ColorCyanAndBlue }
Public Member Functions
LevelMeterSignalDB (QWidget *parent=0)
virtual ~LevelMeterSignalDB ()
void setColorTheme (ColorTheme colorTheme)
void setRange (int min, int max)
Public Member Functions inherited from LevelMeter
LevelMeter (QWidget *parent=0)
virtual ~LevelMeter ()
void paintEvent (QPaintEvent *event)
void resizeEvent (QResizeEvent *event)
void setAverageSmoothing (uint32_t smoothingFactor)
Static Public Attributes
static const QColor m_avgColor [4]
static const QColor m_decayedPeakColor [4]
static const QColor m_peakColor [4]
Protected Member Functions
virtual void render (QPainter *painter)
virtual void resized ()
Protected Member Functions inherited from LevelMeter
int shiftx (int val, int width)
Protected Attributes
ColorTheme m_colorTheme
Protected Attributes inherited from LevelMeter
qreal m_avgLevel
qreal m_peakLevel
qreal m_decayedPeakLevel
QTime m_peakLevelChanged
qreal m_peakDecayRate
qreal m_peakHoldLevel
QTime m_peakHoldLevelChanged
uint32_t m_avgSmoothing
QTimer * m_redrawTimer
QColor m_avgColor
QColor m_peakColor
QColor m_decayedPeakColor
ScaleEngine m_scaleEngine
QPixmap * m_backgroundPixmap
Additional Inherited Members
Public Slots inherited from LevelMeter
void reset ()
void levelChanged (qreal rmsLevel, qreal peakLevel, int numSamples)
Protected Slots inherited from LevelMeter
void redrawTimerExpired ()
Detailed Description
Definition at line 158 of file levelmeter.h.
Member Enumeration Documentation
ColorTheme
enum LevelMeterSignalDB::ColorTheme
Enumerator
ColorGold
ColorGreenYellow
ColorGreenAndBlue
ColorCyanAndBlue
Definition at line 161 of file levelmeter.h.
     {
         ColorGold,
         ColorGreenYellow,
         ColorGreenAndBlue,
         ColorCyanAndBlue
     } ColorTheme;
Constructor & Destructor Documentation
LevelMeterSignalDB()
LevelMeterSignalDB::LevelMeterSignalDB (QWidget * parent = 0)
Definition at line 281 of file levelmeter.cpp.
References Unit::Decibel, LevelMeter::m_scaleEngine, resized(), ScaleEngine::setFont(), ScaleEngine::setOrientation(), and ScaleEngine::setRange().
                                                       :
         LevelMeter(parent),
         m_colorTheme(ColorGold)
 {
     m_scaleEngine.setFont(font());
     m_scaleEngine.setOrientation(Qt::Horizontal);
     m_scaleEngine.setRange(Unit::Decibel, -100, 0);
     resized();
 }
~LevelMeterSignalDB()
LevelMeterSignalDB::~LevelMeterSignalDB () virtual
Definition at line 292 of file levelmeter.cpp.
 {
 }
Member Function Documentation
render()
void LevelMeterSignalDB::render (QPainter * painter) protected virtual
Implements LevelMeter.
Definition at line 348 of file levelmeter.cpp.
References m_avgColor, LevelMeter::m_avgLevel, LevelMeter::m_backgroundPixmap, m_colorTheme, m_decayedPeakColor, LevelMeter::m_decayedPeakLevel, m_peakColor, and LevelMeter::m_peakHoldLevel.
 {
     painter->drawPixmap(rect(), *m_backgroundPixmap);
     QRect bar = rect();
     // Bottom moving gauge
     bar.setTop(0.5 * rect().height() + 2);
     bar.setBottom(0.75*rect().height());
     bar.setRight(rect().right() - (1.0 - m_avgLevel) * rect().width());
     bar.setLeft(1);
     painter->fillRect(bar, m_avgColor[m_colorTheme]);
     bar.setTop(0.75 * rect().height() + 1);
     bar.setBottom(rect().height() - 1);
     bar.setRight(rect().right() - (1.0 - m_decayedPeakLevel) * rect().width());
     painter->fillRect(bar, m_decayedPeakColor[m_colorTheme]);
     bar.setTop(0.5 * rect().height() + 2);
     bar.setBottom(rect().height() - 1);
     bar.setRight(rect().right() - (1.0 - m_peakHoldLevel) * rect().width());
     bar.setLeft(bar.right() - 2);
     painter->fillRect(bar, m_peakColor[m_colorTheme]);
     // borders
     painter->setPen(QColor(0,0,0));
     painter->drawLine(0, 0, rect().width() - 2, 0);
     painter->drawLine(0, rect().height() - 1, 0, 0);
     painter->setPen(QColor(80,80,80));
     painter->drawLine(1, rect().height() - 1, rect().width() - 1, rect().height() - 1);
     painter->drawLine(rect().width() - 1, rect().height() - 1, rect().width() - 1, 0);
 }
resized()
void LevelMeterSignalDB::resized () protected virtual
Implements LevelMeter.
Definition at line 301 of file levelmeter.cpp.
References ScaleEngine::getTickList(), i, LevelMeter::m_backgroundPixmap, LevelMeter::m_scaleEngine, ScaleEngine::Tick::major, ScaleEngine::Tick::pos, ScaleEngine::setSize(), LevelMeter::shiftx(), ScaleEngine::Tick::text, ScaleEngine::Tick::textPos, and ScaleEngine::Tick::textSize.
Referenced by LevelMeterSignalDB().
 {
     if (m_backgroundPixmap)
     {
         delete m_backgroundPixmap;
     }
     m_backgroundPixmap = new QPixmap(rect().width(), rect().height());
     m_backgroundPixmap->fill(QColor(42, 42, 42, 255));
     QPainter painter(m_backgroundPixmap);
     QRect bar = m_backgroundPixmap->rect();
     // 100% full height white line
     painter.setPen(Qt::white);
     painter.setFont(font());
     m_scaleEngine.setSize(bar.width());
     const ScaleEngine::TickList& scaleTickList = m_scaleEngine.getTickList();
     for (int i = 0; i < scaleTickList.count(); i++)
     {
 //        qDebug() << "LevelMeterVU::resized: tick #" << i
 //                << " major: " << scaleTickList[i].major
 //                << " pos: " << scaleTickList[i].pos
 //                << " text: " << scaleTickList[i].text
 //                << " textPos: " << scaleTickList[i].textPos
 //                << " textSize: " << scaleTickList[i].textSize;
         const ScaleEngine::Tick tick = scaleTickList[i];
         if(tick.major)
         {
             if ((tick.textSize > 0) && (tick.textPos > 0))
             {
                 painter.drawText(QPointF(tick.textPos - (tick.textSize/2) - 4, bar.height()/2 - 3), tick.text);
             }
             painter.drawLine(shiftx(tick.pos, bar.width()), 0, shiftx(scaleTickList[i].pos,bar.width()), bar.height());
         }
         else
         {
             painter.drawLine(tick.pos, bar.height()/2 - 2, scaleTickList[i].pos, bar.height()/2);
         }
     }
 }
setColorTheme()
void LevelMeterSignalDB::setColorTheme (ColorTheme colorTheme) inline
Definition at line 172 of file levelmeter.h.
References leansdr::max(), and leansdr::min().
 { m_colorTheme = colorTheme; }
setRange()
void LevelMeterSignalDB::setRange (int min, int max)
Definition at line 296 of file levelmeter.cpp.
References Unit::Decibel, LevelMeter::m_scaleEngine, and ScaleEngine::setRange().
 {
     m_scaleEngine.setRange(Unit::Decibel, min, max);
 }
Member Data Documentation
m_avgColor
const QColor LevelMeterSignalDB::m_avgColor static
Initial value:
= {
        QColor(0xff, 0x8b, 0x00, 128),
        QColor(0x8c, 0xff, 0x00, 128),
        QColor(0x8c, 0xff, 0x00, 128),
        QColor(0x8c, 0xbf, 0xff, 128),
}
Definition at line 175 of file levelmeter.h.
Referenced by LevelMeterVU::render(), and render().
m_colorTheme
ColorTheme LevelMeterSignalDB::m_colorTheme protected
Definition at line 183 of file levelmeter.h.
Referenced by render().
m_decayedPeakColor
const QColor LevelMeterSignalDB::m_decayedPeakColor static
Initial value:
= {
        QColor(0x97, 0x54, 0x00, 128),
        QColor(0x53, 0x96, 0x00, 128),
        QColor(0x00, 0x96, 0x53, 128),
        QColor(0x00, 0x94, 0x94, 128),
}
Definition at line 176 of file levelmeter.h.
Referenced by LevelMeterVU::render(), and render().
m_peakColor
const QColor LevelMeterSignalDB::m_peakColor static
Initial value:
= {
        Qt::red,
        Qt::green,
        Qt::green,
        Qt::cyan
}
Definition at line 177 of file levelmeter.h.
Referenced by LevelMeterVU::render(), and render().
The documentation for this class was generated from the following files:
sdrgui/gui/levelmeter.h
sdrgui/gui/levelmeter.cpp