SDRAngel: DeviceSampleSource Class Reference
DeviceSampleSource Class Reference abstract
#include <devicesamplesource.h>
Public Types
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
enum FrequencyShiftScheme { FSHIFT_STD = 0, FSHIFT_TXSYNC }
Public Member Functions
DeviceSampleSource ()
virtual ~DeviceSampleSource ()
virtual void destroy ()=0
virtual void init ()=0
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()=0
virtual void stop ()=0
virtual QByteArray serialize () const =0
virtual bool deserialize (const QByteArray &data)=0
virtual const QString & getDeviceDescription () const =0
virtual int getSampleRate () const =0
Sample rate exposed by the source.
virtual void setSampleRate (int sampleRate)=0
For when the source sample rate is set externally.
virtual quint64 getCenterFrequency () const =0
Center frequency exposed by the source.
virtual void setCenterFrequency (qint64 centerFrequency)=0
virtual bool handleMessage (const Message &message)=0
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
MessageQueue * getInputMessageQueue ()
virtual void setMessageQueueToGUI (MessageQueue *queue)=0
MessageQueue * getMessageQueueToGUI ()
SampleSinkFifo * getSampleFifo ()
Static Public Member Functions
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme)
Protected Slots
void handleInputMessages ()
Protected Attributes
SampleSinkFifo m_sampleFifo
MessageQueue m_inputMessageQueue
Input queue to the source.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 37 of file devicesamplesource.h.
Member Enumeration Documentation
fcPos_t
enum DeviceSampleSource::fcPos_t
Enumerator
FC_POS_INFRA
FC_POS_SUPRA
FC_POS_CENTER
Definition at line 40 of file devicesamplesource.h.
                  {
         FC_POS_INFRA = 0,
         FC_POS_SUPRA,
         FC_POS_CENTER
     } fcPos_t;
FrequencyShiftScheme
enum DeviceSampleSource::FrequencyShiftScheme
Enumerator
FSHIFT_STD
FSHIFT_TXSYNC
Definition at line 46 of file devicesamplesource.h.
                  {
         FSHIFT_STD = 0, // Standard Rx independent
         FSHIFT_TXSYNC   // Follows same scheme as Tx
     } FrequencyShiftScheme;
Constructor & Destructor Documentation
DeviceSampleSource()
DeviceSampleSource::DeviceSampleSource ()
Definition at line 22 of file devicesamplesource.cpp.
References handleInputMessages(), and m_inputMessageQueue.
                                        :
     m_guiMessageQueue(0)
 {
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
 }
~DeviceSampleSource()
DeviceSampleSource::~DeviceSampleSource () virtual
Definition at line 28 of file devicesamplesource.cpp.
 {
 }
Member Function Documentation
calculateCenterFrequency()
qint64 DeviceSampleSource::calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode = false) static
Definition at line 74 of file devicesamplesource.cpp.
References calculateFrequencyShift().
Referenced by HackRFInput::handleMessage().
 {
     qint64 centerFrequency = deviceCenterFrequency;
     centerFrequency += calculateFrequencyShift(log2Decim, fcPos, devSampleRate, frequencyShiftScheme);
     centerFrequency += transverterMode ? transverterDeltaFrequency : 0;
     centerFrequency = centerFrequency < 0 ? 0 : centerFrequency;
     qDebug() << "DeviceSampleSource::calculateCenterFrequency:"
             << " frequencyShiftScheme: " << frequencyShiftScheme
             << " desired center freq: " << centerFrequency << " Hz"
             << " device center freq: " << deviceCenterFrequency << " Hz"
             << " device sample rate: " << devSampleRate << "S/s"
             << " Actual sample rate: " << devSampleRate/(1<<log2Decim) << "S/s"
             << " center freq position code: " << fcPos;
     return centerFrequency;
 }
calculateDeviceCenterFrequency()
qint64 DeviceSampleSource::calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme, bool transverterMode = false) static
Definition at line 45 of file devicesamplesource.cpp.
References calculateFrequencyShift().
Referenced by TestSourceInput::applySettings(), Bladerf1Input::applySettings(), AirspyInput::applySettings(), TestMI::applySettings(), RTLSDRInput::applySettings(), PlutoSDRInput::applySettings(), HackRFInput::applySettings(), FCDProPlusInput::applySettings(), FCDProInput::applySettings(), SDRPlayInput::applySettings(), BladeRF2Input::applySettings(), SoapySDRInput::applySettings(), and BladeRF2Input::handleMessage().
 {
     qint64 deviceCenterFrequency = centerFrequency;
     deviceCenterFrequency -= transverterMode ? transverterDeltaFrequency : 0;
     deviceCenterFrequency = deviceCenterFrequency < 0 ? 0 : deviceCenterFrequency;
     qint64 f_img = deviceCenterFrequency;
     deviceCenterFrequency -= calculateFrequencyShift(log2Decim, fcPos, devSampleRate, frequencyShiftScheme);
     f_img -= 2*calculateFrequencyShift(log2Decim, fcPos, devSampleRate, frequencyShiftScheme);
     qDebug() << "DeviceSampleSource::calculateDeviceCenterFrequency:"
             << " frequencyShiftScheme: " << frequencyShiftScheme
             << " desired center freq: " << centerFrequency << " Hz"
             << " device center freq: " << deviceCenterFrequency << " Hz"
             << " device sample rate: " << devSampleRate << "S/s"
             << " Actual sample rate: " << devSampleRate/(1<<log2Decim) << "S/s"
             << " center freq position code: " << fcPos
             << " image frequency: " << f_img << "Hz";
     return deviceCenterFrequency;
 }
calculateFrequencyShift()
qint32 DeviceSampleSource::calculateFrequencyShift (int log2Decim, fcPos_t fcPos, quint32 devSampleRate, FrequencyShiftScheme frequencyShiftScheme) static
log2Decim = 0: no shift
n = log2Decim <= 2: fc = +/- 1/2^(n-1) center | ^ | | inf | sup | ^ ^
n = log2Decim > 2: fc = +/- 1/2^n center | ^ | | |inf| | |sup| | ^ ^
Definition at line 114 of file devicesamplesource.cpp.
References FC_POS_CENTER, FC_POS_INFRA, FC_POS_SUPRA, and FSHIFT_STD.
Referenced by TestSourceInput::applySettings(), TestMI::applySettings(), calculateCenterFrequency(), calculateDeviceCenterFrequency(), BladeRF2InputGui::displayFcTooltip(), Bladerf1InputGui::displayFcTooltip(), RTLSDRGui::displayFcTooltip(), PlutoSDRInputGui::displayFcTooltip(), and HackRFInputGui::displayFcTooltip().
 {
     if (frequencyShiftScheme == FSHIFT_STD)
     {
         if (log2Decim == 0) { // no shift at all
             return 0;
         } else if (log2Decim < 3) {
             if (fcPos == FC_POS_INFRA) { // shift in the square next to center frequency
                 return -(devSampleRate / (1<<(log2Decim+1)));
             } else if (fcPos == FC_POS_SUPRA) {
                 return devSampleRate / (1<<(log2Decim+1));
             } else {
                 return 0;
             }
         } else {
             if (fcPos == FC_POS_INFRA) { // shift centered in the square next to center frequency
                 return -(devSampleRate / (1<<(log2Decim)));
             } else if (fcPos == FC_POS_SUPRA) {
                 return devSampleRate / (1<<(log2Decim));
             } else {
                 return 0;
             }
         }
     }
     else // frequencyShiftScheme == FSHIFT_TXSYNC
     {
         if (fcPos == FC_POS_CENTER) {
             return 0;
         }
         int sign = fcPos == FC_POS_INFRA ? -1 : 1;
         int halfSampleRate = devSampleRate / 2; // fractions are relative to sideband thus based on half the sample rate
         if (log2Decim == 0) {
             return 0;
         } else if (log2Decim == 1) {
             return sign * (halfSampleRate / 2);         // inf or sup: 1/2
         } else if (log2Decim == 2) {
             return sign * ((halfSampleRate * 3) / 4);   // inf, inf or sup, sup: 1/2 + 1/4
         } else if (log2Decim == 3) {
             return sign * ((halfSampleRate * 5) / 8);   // inf, inf, sup or sup, sup, inf: 1/2 + 1/4 - 1/8 = 5/8
         } else if (log2Decim == 4) {
             return sign * ((halfSampleRate * 11) / 16); // inf, inf, sup, inf or sup, sup, inf, sup: 1/2 + 1/4 - 1/8 + 1/16 = 11/16
         } else if (log2Decim == 5) {
             return sign * ((halfSampleRate * 21) / 32); // inf, inf, sup, inf, sup or sup, sup, inf, sup, inf: 1/2 + 1/4 - 1/8 + 1/16 - 1/32 = 21/32
         } else if (log2Decim == 6) {
             return sign * ((halfSampleRate * 21) / 64); // inf, sup, inf, sup, inf, sup or sup, inf, sup, inf, sup, inf: 1/2 - 1/4 + 1/8 -1/16 + 1/32 - 1/64 = 21/64
         } else {
             return 0;
         }
     }
 }
deserialize()
virtual bool DeviceSampleSource::deserialize (const QByteArray & data) pure virtual
Implemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, SDRPlayInput, BladeRF2Input, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, FCDProPlusInput, Bladerf1Input, PlutoSDRInput, AirspyHFInput, PerseusInput, RTLSDRInput, AirspyInput, and TestSourceInput.
Referenced by DeviceAPI::loadSamplingDeviceSettings().
destroy()
virtual void DeviceSampleSource::destroy () pure virtual
Implemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, SDRPlayInput, BladeRF2Input, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, FCDProPlusInput, Bladerf1Input, PlutoSDRInput, AirspyHFInput, PerseusInput, RTLSDRInput, AirspyInput, and TestSourceInput.
Referenced by PluginInterface::deleteSampleSourcePluginInstanceInput().
getCenterFrequency()
virtual quint64 DeviceSampleSource::getCenterFrequency () const pure virtual
Center frequency exposed by the source.
Implemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, SDRPlayInput, BladeRF2Input, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, FCDProPlusInput, Bladerf1Input, PlutoSDRInput, AirspyHFInput, PerseusInput, RTLSDRInput, AirspyInput, and TestSourceInput.
Referenced by WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), DSPDeviceSourceEngine::gotoInit(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), and DeviceAPI::saveSamplingDeviceSettings().
getDeviceDescription()
virtual const QString& DeviceSampleSource::getDeviceDescription () const pure virtual
Implemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, SDRPlayInput, BladeRF2Input, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, FCDProPlusInput, Bladerf1Input, PlutoSDRInput, AirspyHFInput, PerseusInput, RTLSDRInput, AirspyInput, and TestSourceInput.
Referenced by LocalSink::getLocalDevice(), LocalSink::getLocalDevices(), DSPDeviceSourceEngine::gotoInit(), and DSPDeviceSourceEngine::handleSetSource().
getInputMessageQueue()
MessageQueue* DeviceSampleSource::getInputMessageQueue () inline
Definition at line 120 of file devicesamplesource.h.
Referenced by FileInputGUI::configureFileName(), DeviceAPI::getSamplingDeviceInputMessageQueue(), LocalInputGui::handleInputMessages(), RemoteInputGui::handleInputMessages(), FileInputGUI::on_acceleration_currentIndexChanged(), FileInputGUI::on_navTimeSlider_valueChanged(), FileInputGUI::on_play_toggled(), FileInputGUI::on_playLoop_toggled(), KiwiSDRGui::on_record_toggled(), PlutoSDRInputGui::on_record_toggled(), XTRXInputGUI::on_record_toggled(), LimeSDRInputGUI::on_record_toggled(), PerseusGui::on_record_toggled(), AirspyHFGui::on_record_toggled(), FCDProPlusGui::on_record_toggled(), Bladerf1InputGui::on_record_toggled(), AirspyGui::on_record_toggled(), BladeRF2InputGui::on_record_toggled(), RTLSDRGui::on_record_toggled(), SDRPlayGui::on_record_toggled(), TestSourceGui::on_record_toggled(), HackRFInputGui::on_record_toggled(), FCDProGui::on_record_toggled(), LocalInputGui::on_record_toggled(), RemoteInputGui::on_record_toggled(), SoapySDRInputGui::on_record_toggled(), KiwiSDRGui::on_startStop_toggled(), TestSourceGui::on_startStop_toggled(), PlutoSDRInputGui::on_startStop_toggled(), XTRXInputGUI::on_startStop_toggled(), LimeSDRInputGUI::on_startStop_toggled(), PerseusGui::on_startStop_toggled(), AirspyHFGui::on_startStop_toggled(), FCDProPlusGui::on_startStop_toggled(), Bladerf1InputGui::on_startStop_toggled(), AirspyGui::on_startStop_toggled(), FileInputGUI::on_startStop_toggled(), BladeRF2InputGui::on_startStop_toggled(), SDRPlayGui::on_startStop_toggled(), RTLSDRGui::on_startStop_toggled(), HackRFInputGui::on_startStop_toggled(), FCDProGui::on_startStop_toggled(), LocalInputGui::on_startStop_toggled(), RemoteInputGui::on_startStop_toggled(), SoapySDRInputGui::on_startStop_toggled(), FileInputGUI::tick(), SDRPlayGui::updateHardware(), KiwiSDRGui::updateHardware(), PerseusGui::updateHardware(), FCDProPlusGui::updateHardware(), Bladerf1InputGui::updateHardware(), AirspyGui::updateHardware(), AirspyHFGui::updateHardware(), BladeRF2InputGui::updateHardware(), RTLSDRGui::updateHardware(), TestSourceGui::updateHardware(), HackRFInputGui::updateHardware(), PlutoSDRInputGui::updateHardware(), XTRXInputGUI::updateHardware(), FCDProGui::updateHardware(), LimeSDRInputGUI::updateHardware(), LocalInputGui::updateHardware(), RemoteInputGui::updateHardware(), SoapySDRInputGui::updateHardware(), XTRXInputGUI::updateStatus(), and LimeSDRInputGUI::updateStatus().
 { return &m_inputMessageQueue; }
getMessageQueueToGUI()
MessageQueue* DeviceSampleSource::getMessageQueueToGUI () inline
Definition at line 122 of file devicesamplesource.h.
Referenced by SDRPlayInput::applySettings(), BladeRF2Input::applySettings(), SoapySDRInput::applySettings(), FileInput::deserialize(), DeviceAPI::getSamplingDeviceGUIMessageQueue(), DSPDeviceSourceEngine::gotoInit(), DSPDeviceSourceEngine::handleInputMessages(), BladeRF2Input::handleMessage(), SoapySDRInput::handleMessage(), XTRXInput::handleMessage(), LimeSDRInput::handleMessage(), FileInput::handleMessage(), FileInput::openFileStream(), LocalInput::setCenterFrequency(), FileInput::setCenterFrequency(), LocalInput::setSampleRate(), FileInput::start(), FileInput::stop(), and FileInput::webapiRun().
 { return m_guiMessageQueue; }
getSampleFifo()
SampleSinkFifo* DeviceSampleSource::getSampleFifo () inline
Definition at line 123 of file devicesamplesource.h.
Referenced by LocalSink::applySettings(), DSPDeviceSourceEngine::handleSetSource(), LocalSink::start(), and DSPDeviceSourceEngine::work().
 { return &m_sampleFifo; }
getSampleRate()
virtual int DeviceSampleSource::getSampleRate () const pure virtual
Sample rate exposed by the source.
Implemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, SDRPlayInput, BladeRF2Input, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, FCDProPlusInput, Bladerf1Input, PlutoSDRInput, AirspyHFInput, PerseusInput, RTLSDRInput, AirspyInput, and TestSourceInput.
Referenced by WebAPIAdapterGUI::getDeviceSet(), WebAPIAdapterSrv::getDeviceSet(), and DSPDeviceSourceEngine::gotoInit().
handleInputMessages
void DeviceSampleSource::handleInputMessages () protected slot
Definition at line 32 of file devicesamplesource.cpp.
References handleMessage(), m_inputMessageQueue, and MessageQueue::pop().
Referenced by DeviceSampleSource().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
virtual bool DeviceSampleSource::handleMessage (const Message & message) pure virtual
Implemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, BladeRF2Input, SDRPlayInput, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, FCDProPlusInput, Bladerf1Input, PlutoSDRInput, AirspyHFInput, AirspyInput, PerseusInput, RTLSDRInput, and TestSourceInput.
Referenced by handleInputMessages().
init()
virtual void DeviceSampleSource::init () pure virtual
initializations to be done when all collaborating objects are created and possibly connected
Implemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, SDRPlayInput, BladeRF2Input, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, FCDProPlusInput, Bladerf1Input, PlutoSDRInput, AirspyHFInput, PerseusInput, RTLSDRInput, AirspyInput, and TestSourceInput.
Referenced by MainWindow::sampleSourceChanged().
serialize()
virtual QByteArray DeviceSampleSource::serialize () const pure virtual
Implemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, SDRPlayInput, BladeRF2Input, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, FCDProPlusInput, Bladerf1Input, PlutoSDRInput, AirspyHFInput, PerseusInput, RTLSDRInput, AirspyInput, and TestSourceInput.
Referenced by DeviceAPI::saveSamplingDeviceSettings().
setCenterFrequency()
virtual void DeviceSampleSource::setCenterFrequency (qint64 centerFrequency) pure virtual
Implemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, SDRPlayInput, BladeRF2Input, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, FCDProPlusInput, Bladerf1Input, PlutoSDRInput, AirspyHFInput, PerseusInput, RTLSDRInput, AirspyInput, and TestSourceInput.
Referenced by DeviceAPI::loadSamplingDeviceSettings(), and LocalSink::propagateSampleRateAndFrequency().
setMessageQueueToGUI()
virtual void DeviceSampleSource::setMessageQueueToGUI (MessageQueue * queue) pure virtual
Implemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, SDRPlayInput, BladeRF2Input, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, FCDProPlusInput, Bladerf1Input, PlutoSDRInput, AirspyHFInput, PerseusInput, RTLSDRInput, AirspyInput, and TestSourceInput.
Referenced by AirspyGui::AirspyGui(), AirspyHFGui::AirspyHFGui(), Bladerf1InputGui::Bladerf1InputGui(), FCDProGui::FCDProGui(), FCDProPlusGui::FCDProPlusGui(), FileInputGUI::FileInputGUI(), HackRFInputGui::HackRFInputGui(), KiwiSDRGui::KiwiSDRGui(), PlutoSDRInputGui::PlutoSDRInputGui(), MainWindow::sampleSourceChanged(), SDRPlayGui::SDRPlayGui(), and TestSourceGui::TestSourceGui().
setSampleRate()
virtual void DeviceSampleSource::setSampleRate (int sampleRate) pure virtual
For when the source sample rate is set externally.
Implemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, SDRPlayInput, BladeRF2Input, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, FCDProPlusInput, Bladerf1Input, PlutoSDRInput, AirspyHFInput, PerseusInput, RTLSDRInput, AirspyInput, and TestSourceInput.
Referenced by LocalSink::propagateSampleRateAndFrequency().
start()
virtual bool DeviceSampleSource::start () pure virtual
Implemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, SDRPlayInput, BladeRF2Input, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, FCDProPlusInput, Bladerf1Input, PlutoSDRInput, AirspyHFInput, PerseusInput, RTLSDRInput, AirspyInput, and TestSourceInput.
Referenced by DSPDeviceSourceEngine::gotoRunning().
stop()
virtual void DeviceSampleSource::stop () pure virtual
Implemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, SDRPlayInput, BladeRF2Input, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, FCDProPlusInput, Bladerf1Input, PlutoSDRInput, AirspyHFInput, PerseusInput, RTLSDRInput, AirspyInput, and TestSourceInput.
Referenced by DSPDeviceSourceEngine::gotoIdle().
webapiReportGet()
virtual int DeviceSampleSource::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) inline virtual
Reimplemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, BladeRF2Input, SDRPlayInput, KiwiSDRInput, LocalInput, PlutoSDRInput, AirspyInput, AirspyHFInput, PerseusInput, and RTLSDRInput.
Definition at line 111 of file devicesamplesource.h.
Referenced by WebAPIAdapterGUI::devicesetDeviceReportGet(), and WebAPIAdapterSrv::devicesetDeviceReportGet().
     {
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
webapiRun()
virtual int DeviceSampleSource::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) inline virtual
Reimplemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, BladeRF2Input, SDRPlayInput, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, AirspyHFInput, PerseusInput, RTLSDRInput, Bladerf1Input, AirspyInput, FCDProPlusInput, TestSourceInput, and PlutoSDRInput.
Definition at line 101 of file devicesamplesource.h.
Referenced by WebAPIAdapterGUI::devicesetDeviceRunDelete(), WebAPIAdapterSrv::devicesetDeviceRunDelete(), WebAPIAdapterGUI::devicesetDeviceRunPost(), and WebAPIAdapterSrv::devicesetDeviceRunPost().
     {
         (void) run;
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
webapiRunGet()
virtual int DeviceSampleSource::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) inline virtual
Reimplemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, BladeRF2Input, SDRPlayInput, LocalInput, KiwiSDRInput, HackRFInput, FCDProInput, AirspyHFInput, PerseusInput, RTLSDRInput, Bladerf1Input, AirspyInput, FCDProPlusInput, TestSourceInput, and PlutoSDRInput.
Definition at line 92 of file devicesamplesource.h.
Referenced by WebAPIAdapterGUI::devicesetDeviceRunGet(), and WebAPIAdapterSrv::devicesetDeviceRunGet().
     {
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
webapiSettingsGet()
virtual int DeviceSampleSource::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) inline virtual
Reimplemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, BladeRF2Input, SDRPlayInput, LocalInput, KiwiSDRInput, HackRFInput, FCDProPlusInput, PlutoSDRInput, FCDProInput, Bladerf1Input, AirspyHFInput, AirspyInput, PerseusInput, RTLSDRInput, and TestSourceInput.
Definition at line 70 of file devicesamplesource.h.
Referenced by WebAPIAdapterGUI::devicesetDeviceSettingsGet(), and WebAPIAdapterSrv::devicesetDeviceSettingsGet().
     {
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
webapiSettingsPutPatch()
virtual int DeviceSampleSource::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) inline virtual
Parameters
force true to force settings = put
Reimplemented in FileInput, RemoteInput, LimeSDRInput, XTRXInput, SoapySDRInput, BladeRF2Input, SDRPlayInput, LocalInput, KiwiSDRInput, HackRFInput, FCDProPlusInput, PlutoSDRInput, FCDProInput, Bladerf1Input, AirspyHFInput, AirspyInput, PerseusInput, RTLSDRInput, and TestSourceInput.
Definition at line 79 of file devicesamplesource.h.
Referenced by WebAPIAdapterGUI::devicesetDeviceSettingsPutPatch(), and WebAPIAdapterSrv::devicesetDeviceSettingsPutPatch().
     {
         (void) force;
         (void) deviceSettingsKeys;
         (void) response;
         errorMessage = "Not implemented";
         return 501;
     }
Member Data Documentation
m_guiMessageQueue
MessageQueue* DeviceSampleSource::m_guiMessageQueue protected
Input message queue to the GUI.
Definition at line 158 of file devicesamplesource.h.
Referenced by AirspyInput::deserialize(), TestSourceInput::deserialize(), RTLSDRInput::deserialize(), AirspyHFInput::deserialize(), PerseusInput::deserialize(), Bladerf1Input::deserialize(), PlutoSDRInput::deserialize(), FCDProInput::deserialize(), FCDProPlusInput::deserialize(), HackRFInput::deserialize(), KiwiSDRInput::deserialize(), LocalInput::deserialize(), BladeRF2Input::deserialize(), SDRPlayInput::deserialize(), XTRXInput::deserialize(), LimeSDRInput::deserialize(), RemoteInput::deserialize(), HackRFInput::handleMessage(), TestSourceInput::setCenterFrequency(), AirspyInput::setCenterFrequency(), RTLSDRInput::setCenterFrequency(), PerseusInput::setCenterFrequency(), AirspyHFInput::setCenterFrequency(), Bladerf1Input::setCenterFrequency(), PlutoSDRInput::setCenterFrequency(), FCDProInput::setCenterFrequency(), FCDProPlusInput::setCenterFrequency(), HackRFInput::setCenterFrequency(), KiwiSDRInput::setCenterFrequency(), BladeRF2Input::setCenterFrequency(), SDRPlayInput::setCenterFrequency(), SoapySDRInput::setCenterFrequency(), XTRXInput::setCenterFrequency(), LimeSDRInput::setCenterFrequency(), TestSourceInput::setMessageQueueToGUI(), AirspyInput::setMessageQueueToGUI(), RTLSDRInput::setMessageQueueToGUI(), AirspyHFInput::setMessageQueueToGUI(), PerseusInput::setMessageQueueToGUI(), PlutoSDRInput::setMessageQueueToGUI(), Bladerf1Input::setMessageQueueToGUI(), HackRFInput::setMessageQueueToGUI(), KiwiSDRInput::setMessageQueueToGUI(), LocalInput::setMessageQueueToGUI(), BladeRF2Input::setMessageQueueToGUI(), SDRPlayInput::setMessageQueueToGUI(), XTRXInput::setMessageQueueToGUI(), LimeSDRInput::setMessageQueueToGUI(), RemoteInput::setMessageQueueToGUI(), FileInput::setMessageQueueToGUI(), KiwiSDRInput::setWorkerStatus(), PlutoSDRInput::webapiRun(), TestSourceInput::webapiRun(), FCDProPlusInput::webapiRun(), AirspyInput::webapiRun(), Bladerf1Input::webapiRun(), RTLSDRInput::webapiRun(), PerseusInput::webapiRun(), AirspyHFInput::webapiRun(), FCDProInput::webapiRun(), HackRFInput::webapiRun(), KiwiSDRInput::webapiRun(), LocalInput::webapiRun(), SDRPlayInput::webapiRun(), BladeRF2Input::webapiRun(), SoapySDRInput::webapiRun(), XTRXInput::webapiRun(), LimeSDRInput::webapiRun(), RemoteInput::webapiRun(), TestSourceInput::webapiSettingsPutPatch(), RTLSDRInput::webapiSettingsPutPatch(), AirspyInput::webapiSettingsPutPatch(), PerseusInput::webapiSettingsPutPatch(), AirspyHFInput::webapiSettingsPutPatch(), Bladerf1Input::webapiSettingsPutPatch(), FCDProInput::webapiSettingsPutPatch(), PlutoSDRInput::webapiSettingsPutPatch(), FCDProPlusInput::webapiSettingsPutPatch(), HackRFInput::webapiSettingsPutPatch(), KiwiSDRInput::webapiSettingsPutPatch(), LocalInput::webapiSettingsPutPatch(), SDRPlayInput::webapiSettingsPutPatch(), BladeRF2Input::webapiSettingsPutPatch(), SoapySDRInput::webapiSettingsPutPatch(), XTRXInput::webapiSettingsPutPatch(), LimeSDRInput::webapiSettingsPutPatch(), RemoteInput::webapiSettingsPutPatch(), and FileInput::webapiSettingsPutPatch().
m_inputMessageQueue
MessageQueue DeviceSampleSource::m_inputMessageQueue protected
Input queue to the source.
Definition at line 157 of file devicesamplesource.h.
Referenced by AirspyInput::deserialize(), TestSourceInput::deserialize(), AirspyHFInput::deserialize(), PerseusInput::deserialize(), RTLSDRInput::deserialize(), Bladerf1Input::deserialize(), PlutoSDRInput::deserialize(), FCDProInput::deserialize(), FCDProPlusInput::deserialize(), HackRFInput::deserialize(), KiwiSDRInput::deserialize(), LocalInput::deserialize(), BladeRF2Input::deserialize(), SDRPlayInput::deserialize(), XTRXInput::deserialize(), LimeSDRInput::deserialize(), RemoteInput::deserialize(), FileInput::deserialize(), DeviceSampleSource(), handleInputMessages(), TestSourceInput::setCenterFrequency(), AirspyInput::setCenterFrequency(), PerseusInput::setCenterFrequency(), AirspyHFInput::setCenterFrequency(), RTLSDRInput::setCenterFrequency(), Bladerf1Input::setCenterFrequency(), PlutoSDRInput::setCenterFrequency(), FCDProInput::setCenterFrequency(), FCDProPlusInput::setCenterFrequency(), HackRFInput::setCenterFrequency(), KiwiSDRInput::setCenterFrequency(), BladeRF2Input::setCenterFrequency(), SDRPlayInput::setCenterFrequency(), SoapySDRInput::setCenterFrequency(), XTRXInput::setCenterFrequency(), LimeSDRInput::setCenterFrequency(), FileInput::setCenterFrequency(), FileInput::start(), PlutoSDRInput::webapiRun(), TestSourceInput::webapiRun(), FCDProPlusInput::webapiRun(), AirspyInput::webapiRun(), Bladerf1Input::webapiRun(), PerseusInput::webapiRun(), RTLSDRInput::webapiRun(), AirspyHFInput::webapiRun(), FCDProInput::webapiRun(), HackRFInput::webapiRun(), KiwiSDRInput::webapiRun(), LocalInput::webapiRun(), SDRPlayInput::webapiRun(), BladeRF2Input::webapiRun(), SoapySDRInput::webapiRun(), XTRXInput::webapiRun(), LimeSDRInput::webapiRun(), RemoteInput::webapiRun(), FileInput::webapiRun(), TestSourceInput::webapiSettingsPutPatch(), AirspyInput::webapiSettingsPutPatch(), RTLSDRInput::webapiSettingsPutPatch(), PerseusInput::webapiSettingsPutPatch(), AirspyHFInput::webapiSettingsPutPatch(), Bladerf1Input::webapiSettingsPutPatch(), FCDProInput::webapiSettingsPutPatch(), PlutoSDRInput::webapiSettingsPutPatch(), FCDProPlusInput::webapiSettingsPutPatch(), HackRFInput::webapiSettingsPutPatch(), KiwiSDRInput::webapiSettingsPutPatch(), LocalInput::webapiSettingsPutPatch(), SDRPlayInput::webapiSettingsPutPatch(), BladeRF2Input::webapiSettingsPutPatch(), SoapySDRInput::webapiSettingsPutPatch(), XTRXInput::webapiSettingsPutPatch(), LimeSDRInput::webapiSettingsPutPatch(), RemoteInput::webapiSettingsPutPatch(), and FileInput::webapiSettingsPutPatch().
m_sampleFifo
SampleSinkFifo DeviceSampleSource::m_sampleFifo protected
Definition at line 156 of file devicesamplesource.h.
Referenced by FileInput::applySettings(), Bladerf1Input::openDevice(), PerseusInput::openDevice(), AirspyInput::openDevice(), AirspyHFInput::openDevice(), PlutoSDRInput::openDevice(), RTLSDRInput::openDevice(), HackRFInput::openDevice(), SDRPlayInput::openDevice(), BladeRF2Input::openDevice(), SoapySDRInput::openDevice(), XTRXInput::openDevice(), LimeSDRInput::openDevice(), AirspyInput::start(), TestSourceInput::start(), AirspyHFInput::start(), PerseusInput::start(), RTLSDRInput::start(), PlutoSDRInput::start(), Bladerf1Input::start(), FCDProInput::start(), FCDProPlusInput::start(), HackRFInput::start(), KiwiSDRInput::start(), BladeRF2Input::start(), SDRPlayInput::start(), SoapySDRInput::start(), XTRXInput::start(), LimeSDRInput::start(), FileInput::start(), and XTRXInput::stop().
The documentation for this class was generated from the following files:
sdrbase/dsp/devicesamplesource.h
sdrbase/dsp/devicesamplesource.cpp