SDRAngel: Preset Class Reference
Preset Class Reference
#include <preset.h>
Classes
struct ChannelConfig
struct DeviceConfig
Public Types
typedef QList< ChannelConfig > ChannelConfigs
typedef QList< DeviceConfig > DeviceeConfigs
Public Member Functions
Preset ()
void resetToDefaults ()
void setSourcePreset (bool isSourcePreset)
bool isSourcePreset () const
QByteArray serialize () const
bool deserialize (const QByteArray &data)
void setGroup (const QString &group)
const QString & getGroup () const
void setDescription (const QString &description)
const QString & getDescription () const
void setCenterFrequency (const quint64 centerFrequency)
quint64 getCenterFrequency () const
void setSpectrumConfig (const QByteArray &data)
const QByteArray & getSpectrumConfig () const
void setLayout (const QByteArray &data)
const QByteArray & getLayout () const
void clearChannels ()
void addChannel (const QString &channel, const QByteArray &config)
int getChannelCount () const
const ChannelConfig & getChannelConfig (int index) const
void setDeviceConfig (const QString &deviceId, const QString &deviceSerial, int deviceSequence, const QByteArray &config)
void addOrUpdateDeviceConfig (const QString &deviceId, const QString &deviceSerial, int deviceSequence, const QByteArray &config)
const QByteArray * findBestDeviceConfig (const QString &deviceId, const QString &deviceSerial, int deviceSequence) const
Static Public Member Functions
static bool presetCompare (const Preset *p1, Preset *p2)
Protected Attributes
bool m_sourcePreset
QString m_group
QString m_description
quint64 m_centerFrequency
QByteArray m_spectrumConfig
bool m_dcOffsetCorrection
bool m_iqImbalanceCorrection
ChannelConfigs m_channelConfigs
DeviceeConfigs m_deviceConfigs
QByteArray m_layout
Private Member Functions
const QByteArray * findBestDeviceConfigSoapy (const QString &sourceId, const QString &deviceSerial) const
Friends
class WebAPIAdapterBase
Detailed Description
Definition at line 28 of file preset.h.
Member Typedef Documentation
ChannelConfigs
typedef QList<ChannelConfig> Preset::ChannelConfigs
Definition at line 40 of file preset.h.
DeviceeConfigs
typedef QList<DeviceConfig> Preset::DeviceeConfigs
Definition at line 59 of file preset.h.
Constructor & Destructor Documentation
Preset()
Preset::Preset ()
Definition at line 25 of file preset.cpp.
References resetToDefaults().
 {
     resetToDefaults();
 }
Member Function Documentation
addChannel()
void Preset::addChannel (const QString & channel, const QByteArray & config) inline
Definition at line 85 of file preset.h.
Referenced by DeviceSet::saveRxChannelSettings(), DeviceUISet::saveRxChannelSettings(), DeviceSet::saveTxChannelSettings(), and DeviceUISet::saveTxChannelSettings().
 { m_channelConfigs.append(ChannelConfig(channel, config)); }
addOrUpdateDeviceConfig()
void Preset::addOrUpdateDeviceConfig (const QString & deviceId, const QString & deviceSerial, int deviceSequence, const QByteArray & config)
Definition at line 177 of file preset.cpp.
References m_deviceConfigs.
Referenced by DeviceAPI::saveSamplingDeviceSettings().
 {
     DeviceeConfigs::iterator it = m_deviceConfigs.begin();
     for (; it != m_deviceConfigs.end(); ++it)
     {
         if (it->m_deviceId == sourceId)
         {
             if (sourceSerial.isNull() || sourceSerial.isEmpty())
             {
                 if (it->m_deviceSequence == sourceSequence)
                 {
                     break;
                 }
             }
             else
             {
                 if (it->m_deviceSerial == sourceSerial)
                 {
                     break;
                 }
             }
         }
     }
     if (it == m_deviceConfigs.end())
     {
         m_deviceConfigs.append(DeviceConfig(sourceId, sourceSerial, sourceSequence, config));
     }
     else
     {
         it->m_config = config;
     }
 }
clearChannels()
void Preset::clearChannels () inline
Definition at line 84 of file preset.h.
Referenced by MainCore::savePresetSettings(), and MainWindow::savePresetSettings().
 { m_channelConfigs.clear(); }
deserialize()
bool Preset::deserialize (const QByteArray & data)
Definition at line 94 of file preset.cpp.
References SimpleDeserializer::getVersion(), i, SimpleDeserializer::isValid(), m_centerFrequency, m_channelConfigs, m_description, m_deviceConfigs, m_group, m_layout, m_sourcePreset, m_spectrumConfig, SimpleDeserializer::readBlob(), SimpleDeserializer::readBool(), SimpleDeserializer::readS32(), SimpleDeserializer::readString(), SimpleDeserializer::readU64(), and resetToDefaults().
Referenced by WebAPIAdapterSrv::instancePresetFilePut(), MainSettings::load(), and MainWindow::on_presetImport_clicked().
 {
     SimpleDeserializer d(data);
     if (!d.isValid())
     {
         resetToDefaults();
         return false;
     }
     if (d.getVersion() == 1)
     {
         d.readString(1, &m_group, "default");
         d.readString(2, &m_description, "no name");
         d.readU64(3, &m_centerFrequency, 0);
         d.readBlob(4, &m_layout);
         d.readBlob(5, &m_spectrumConfig);
         d.readBool(6, &m_sourcePreset, true);
 //      qDebug("Preset::deserialize: m_group: %s mode: %s m_description: %s m_centerFrequency: %llu",
 //              qPrintable(m_group),
 //              m_sourcePreset ? "Rx" : "Tx",
 //              qPrintable(m_description),
 //              m_centerFrequency);
         qint32 sourcesCount = 0;
         d.readS32(20, &sourcesCount, 0);
         if (sourcesCount >= (200-23)/4) // limit was hit!
         {
             sourcesCount = ((200-23)/4) - 1;
         }
         m_deviceConfigs.clear();
         for (int i = 0; i < sourcesCount; i++)
         {
             QString sourceId, sourceSerial;
             int sourceSequence;
             QByteArray sourceConfig;
             d.readString(24 + i*4, &sourceId, "");
             d.readString(25 + i*4, &sourceSerial, "");
             d.readS32(26 + i*4, &sourceSequence, 0);
             d.readBlob(27 + i*4, &sourceConfig);
             if (!sourceId.isEmpty())
             {
 //              qDebug("Preset::deserialize:  source: id: %s, ser: %s, seq: %d",
 //                  qPrintable(sourceId),
 //                  qPrintable(sourceSerial),
 //                  sourceSequence);
                 m_deviceConfigs.append(DeviceConfig(sourceId, sourceSerial, sourceSequence, sourceConfig));
             }
         }
         qint32 channelCount;
         d.readS32(200, &channelCount, 0);
         m_channelConfigs.clear();
         for (int i = 0; i < channelCount; i++)
         {
             QString channel;
             QByteArray config;
             d.readString(201 + i * 2, &channel, "unknown-channel");
             d.readBlob(202 + i * 2, &config);
 //          qDebug("Preset::deserialize:  channel: id: %s", qPrintable(channel));
             m_channelConfigs.append(ChannelConfig(channel, config));
         }
         return true;
     }
     else
     {
         resetToDefaults();
         return false;
     }
 }
findBestDeviceConfig()
const QByteArray * Preset::findBestDeviceConfig (const QString & deviceId, const QString & deviceSerial, int deviceSequence) const
Definition at line 215 of file preset.cpp.
References findBestDeviceConfigSoapy(), and m_deviceConfigs.
Referenced by DeviceAPI::loadSamplingDeviceSettings().
 {
     // Special case for SoapySDR based on serial (driver name)
     if (sourceId == "sdrangel.samplesource.soapysdrinput") {
         return findBestDeviceConfigSoapy(sourceId, sourceSerial);
     } else if (sourceId == "sdrangel.samplesource.soapysdroutput") {
         return findBestDeviceConfigSoapy(sourceId, sourceSerial);
     }
     DeviceeConfigs::const_iterator it = m_deviceConfigs.begin();
     DeviceeConfigs::const_iterator itFirstOfKind = m_deviceConfigs.end();
     DeviceeConfigs::const_iterator itMatchSequence = m_deviceConfigs.end();
     for (; it != m_deviceConfigs.end(); ++it)
     {
         if (it->m_deviceId == sourceId)
         {
             if (itFirstOfKind == m_deviceConfigs.end())
             {
                 itFirstOfKind = it;
             }
             if (sourceSerial.isNull() || sourceSerial.isEmpty())
             {
                 if (it->m_deviceSequence == sourceSequence)
                 {
                     break;
                 }
             }
             else
             {
                 if (it->m_deviceSerial == sourceSerial)
                 {
                     break;
                 }
                 else if(it->m_deviceSequence == sourceSequence)
                 {
                     itMatchSequence = it;
                 }
             }
         }
     }
     if (it == m_deviceConfigs.end()) // no exact match
     {
         if (itMatchSequence != m_deviceConfigs.end()) // match sequence ?
         {
             qDebug("Preset::findBestSourceConfig: sequence matched: id: %s ser: %s seq: %d",
                 qPrintable(itMatchSequence->m_deviceId), qPrintable(itMatchSequence->m_deviceSerial), itMatchSequence->m_deviceSequence);
             return &(itMatchSequence->m_config);
         }
         else if (itFirstOfKind != m_deviceConfigs.end()) // match source type ?
         {
             qDebug("Preset::findBestSourceConfig: first of kind matched: id: %s ser: %s seq: %d",
                 qPrintable(itFirstOfKind->m_deviceId), qPrintable(itFirstOfKind->m_deviceSerial), itFirstOfKind->m_deviceSequence);
             return &(itFirstOfKind->m_config);
         }
         else // definitely not found !
         {
             qDebug("Preset::findBestSourceConfig: no match");
             return 0;
         }
     }
     else // exact match
     {
         qDebug("Preset::findBestSourceConfig: serial matched (exact): id: %s ser: %s",
             qPrintable(it->m_deviceId), qPrintable(it->m_deviceSerial));
         return &(it->m_config);
     }
 }
findBestDeviceConfigSoapy()
const QByteArray * Preset::findBestDeviceConfigSoapy (const QString & sourceId, const QString & deviceSerial) const private
Definition at line 288 of file preset.cpp.
References m_deviceConfigs.
Referenced by findBestDeviceConfig().
 {
     QStringList sourceSerialPieces = sourceSerial.split("-");
     if (sourceSerialPieces.size() == 0) {
         return 0; // unable to process
     }
     DeviceeConfigs::const_iterator it = m_deviceConfigs.begin();
     DeviceeConfigs::const_iterator itFirstOfKind = m_deviceConfigs.end();
     for (; it != m_deviceConfigs.end(); ++it)
     {
         if (it->m_deviceId != sourceId) // skip non matching device
         {
             continue;
         }
         else if (it->m_deviceSerial == sourceSerial) // exact match
         {
             break;
         }
         else // try to find best match on driver id (first part of serial)
         {
             QStringList serialPieces = it->m_deviceSerial.split("-");
             if (serialPieces.size() == 0)
             {
                 continue;
             }
             else if (sourceSerialPieces[0] == serialPieces[0])
             {
                 if (itFirstOfKind == m_deviceConfigs.end())
                 {
                     itFirstOfKind = it;
                     break;
                 }
             }
         }
     }
     if (it == m_deviceConfigs.end()) // no exact match
     {
         if (itFirstOfKind == m_deviceConfigs.end())
         {
             qDebug("Preset::findBestDeviceConfigSoapy: no match");
             return 0;
         }
         else
         {
             qDebug("Preset::findBestSourceConfig: first of kind matched: id: %s ser: %s seq: %d",
                 qPrintable(itFirstOfKind->m_deviceId), qPrintable(itFirstOfKind->m_deviceSerial), itFirstOfKind->m_deviceSequence);
             return &(itFirstOfKind->m_config);
         }
     }
     else // exact match
     {
         qDebug("Preset::findBestDeviceConfigSoapy: serial matched (exact): id: %s ser: %s seq: %d",
             qPrintable(it->m_deviceId), qPrintable(it->m_deviceSerial), it->m_deviceSequence);
         return &(it->m_config);
     }
 }
getCenterFrequency()
quint64 Preset::getCenterFrequency () const inline
Definition at line 76 of file preset.h.
Referenced by MainWindow::addPresetToTree(), MainWindow::handleMessage(), WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterSrv::instancePresetFilePut(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), WebAPIAdapterGUI::instancePresetsGet(), WebAPIAdapterSrv::instancePresetsGet(), and DeviceAPI::loadSamplingDeviceSettings().
 { return m_centerFrequency; }
getChannelConfig()
const ChannelConfig& Preset::getChannelConfig (int index) const inline
Definition at line 87 of file preset.h.
Referenced by DeviceSet::loadRxChannelSettings(), DeviceUISet::loadRxChannelSettings(), DeviceSet::loadTxChannelSettings(), and DeviceUISet::loadTxChannelSettings().
 { return m_channelConfigs.at(index); }
getChannelCount()
int Preset::getChannelCount () const inline
Definition at line 86 of file preset.h.
Referenced by DeviceSet::loadRxChannelSettings(), DeviceUISet::loadRxChannelSettings(), DeviceSet::loadTxChannelSettings(), and DeviceUISet::loadTxChannelSettings().
 { return m_channelConfigs.count(); }
getDescription()
const QString& Preset::getDescription () const inline
Definition at line 74 of file preset.h.
Referenced by MainWindow::addPresetToTree(), MainWindow::handleMessage(), WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterSrv::instancePresetFilePut(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), WebAPIAdapterGUI::instancePresetsGet(), WebAPIAdapterSrv::instancePresetsGet(), MainCore::loadPresetSettings(), MainWindow::loadPresetSettings(), DeviceSet::loadRxChannelSettings(), DeviceUISet::loadRxChannelSettings(), DeviceAPI::loadSamplingDeviceSettings(), DeviceSet::loadTxChannelSettings(), DeviceUISet::loadTxChannelSettings(), MainWindow::on_presetDelete_clicked(), MainWindow::on_presetEdit_clicked(), MainCore::savePresetSettings(), and MainWindow::savePresetSettings().
 { return m_description; }
getGroup()
const QString& Preset::getGroup () const inline
Definition at line 72 of file preset.h.
Referenced by MainWindow::addPresetToTree(), MainWindow::handleMessage(), WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterSrv::instancePresetFilePut(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), WebAPIAdapterGUI::instancePresetsGet(), WebAPIAdapterSrv::instancePresetsGet(), MainCore::loadPresetSettings(), MainWindow::loadPresetSettings(), DeviceSet::loadRxChannelSettings(), DeviceUISet::loadRxChannelSettings(), DeviceAPI::loadSamplingDeviceSettings(), DeviceSet::loadTxChannelSettings(), DeviceUISet::loadTxChannelSettings(), MainWindow::on_presetEdit_clicked(), MainCore::savePresetSettings(), and MainWindow::savePresetSettings().
 { return m_group; }
getLayout()
const QByteArray& Preset::getLayout () const inline
Definition at line 82 of file preset.h.
Referenced by MainWindow::loadPresetSettings().
 { return m_layout; }
getSpectrumConfig()
const QByteArray& Preset::getSpectrumConfig () const inline
Definition at line 79 of file preset.h.
Referenced by MainWindow::loadPresetSettings().
 { return m_spectrumConfig; }
isSourcePreset()
bool Preset::isSourcePreset () const inline
Definition at line 66 of file preset.h.
Referenced by MainWindow::addPresetToTree(), MainWindow::handleMessage(), WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterSrv::instancePresetFilePut(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), WebAPIAdapterGUI::instancePresetsGet(), WebAPIAdapterSrv::instancePresetsGet(), DeviceSet::loadRxChannelSettings(), DeviceUISet::loadRxChannelSettings(), DeviceAPI::loadSamplingDeviceSettings(), DeviceSet::loadTxChannelSettings(), DeviceUISet::loadTxChannelSettings(), DeviceSet::saveRxChannelSettings(), DeviceUISet::saveRxChannelSettings(), DeviceAPI::saveSamplingDeviceSettings(), DeviceSet::saveTxChannelSettings(), and DeviceUISet::saveTxChannelSettings().
 { return m_sourcePreset; }
presetCompare()
static bool Preset::presetCompare (const Preset * p1, Preset * p2) inline static
Definition at line 103 of file preset.h.
References m_centerFrequency, m_description, and m_group.
Referenced by MainSettings::sortPresets().
     {
         if (p1->m_group != p2->m_group)
         {
             return p1->m_group < p2->m_group;
         }
         else
         {
             if (p1->m_centerFrequency != p2->m_centerFrequency) {
                 return p1->m_centerFrequency < p2->m_centerFrequency;
             } else {
                 return p1->m_description < p2->m_description;
             }
         }
     }
resetToDefaults()
void Preset::resetToDefaults ()
Definition at line 30 of file preset.cpp.
References m_centerFrequency, m_channelConfigs, m_dcOffsetCorrection, m_description, m_group, m_iqImbalanceCorrection, m_layout, m_sourcePreset, and m_spectrumConfig.
Referenced by deserialize(), Preset(), and MainSettings::resetToDefaults().
 {
     m_sourcePreset = true;
     m_group = "default";
     m_description = "no name";
     m_centerFrequency = 0;
     m_spectrumConfig.clear();
     m_layout.clear();
     m_channelConfigs.clear();
     m_dcOffsetCorrection = false;
     m_iqImbalanceCorrection = false;
 }
serialize()
QByteArray Preset::serialize () const
Definition at line 43 of file preset.cpp.
References SimpleSerializer::final(), i, m_centerFrequency, m_channelConfigs, m_description, m_deviceConfigs, m_group, m_layout, m_sourcePreset, m_spectrumConfig, SimpleSerializer::writeBlob(), SimpleSerializer::writeBool(), SimpleSerializer::writeS32(), SimpleSerializer::writeString(), and SimpleSerializer::writeU64().
Referenced by WebAPIAdapterSrv::instancePresetFilePost(), MainWindow::on_presetExport_clicked(), and MainSettings::save().
 {
 //  qDebug("Preset::serialize: m_group: %s mode: %s m_description: %s m_centerFrequency: %llu",
 //          qPrintable(m_group),
 //          m_sourcePreset ? "Rx" : "Tx",
 //          qPrintable(m_description),
 //          m_centerFrequency);
     SimpleSerializer s(1);
     s.writeString(1, m_group);
     s.writeString(2, m_description);
     s.writeU64(3, m_centerFrequency);
     s.writeBlob(4, m_layout);
     s.writeBlob(5, m_spectrumConfig);
     s.writeBool(6, m_sourcePreset);
     s.writeS32(20, m_deviceConfigs.size());
     for (int i = 0; i < m_deviceConfigs.size(); i++)
     {
         s.writeString(24 + i*4, m_deviceConfigs[i].m_deviceId);
         s.writeString(25 + i*4, m_deviceConfigs[i].m_deviceSerial);
         s.writeS32(26 + i*4, m_deviceConfigs[i].m_deviceSequence);
         s.writeBlob(27 + i*4, m_deviceConfigs[i].m_config);
 //      qDebug("Preset::serialize:  source: id: %s, ser: %s, seq: %d",
 //          qPrintable(m_deviceConfigs[i].m_deviceId),
 //          qPrintable(m_deviceConfigs[i].m_deviceSerial),
 //          m_deviceConfigs[i].m_deviceSequence);
         if (i >= (200-23)/4) // full!
         {
             qWarning("Preset::serialize: too many sources");
             break;
         }
     }
     s.writeS32(200, m_channelConfigs.size());
     for(int i = 0; i < m_channelConfigs.size(); i++)
     {
 //      qDebug("Preset::serialize:  channel: id: %s", qPrintable(m_channelConfigs[i].m_channel));
         s.writeString(201 + i * 2, m_channelConfigs[i].m_channelIdURI);
         s.writeBlob(202 + i * 2, m_channelConfigs[i].m_config);
     }
     return s.final();
 }
setCenterFrequency()
void Preset::setCenterFrequency (const quint64 centerFrequency) inline
Definition at line 75 of file preset.h.
Referenced by DeviceAPI::saveSamplingDeviceSettings().
 { m_centerFrequency = centerFrequency; }
setDescription()
void Preset::setDescription (const QString & description) inline
Definition at line 73 of file preset.h.
Referenced by WebAPIAdapterSrv::instancePresetFilePut(), MainSettings::newPreset(), and MainWindow::on_presetEdit_clicked().
 { m_description = description; }
setDeviceConfig()
void Preset::setDeviceConfig (const QString & deviceId, const QString & deviceSerial, int deviceSequence, const QByteArray & config) inline
Definition at line 89 of file preset.h.
     {
         addOrUpdateDeviceConfig(deviceId, deviceSerial, deviceSequence, config);
     }
setGroup()
void Preset::setGroup (const QString & group) inline
Definition at line 71 of file preset.h.
Referenced by WebAPIAdapterSrv::instancePresetFilePut(), MainSettings::newPreset(), MainWindow::on_presetEdit_clicked(), MainWindow::on_presetImport_clicked(), and MainSettings::renamePresetGroup().
 { m_group = group; }
setLayout()
void Preset::setLayout (const QByteArray & data) inline
Definition at line 81 of file preset.h.
Referenced by MainWindow::savePresetSettings().
 { m_layout = data; }
setSourcePreset()
void Preset::setSourcePreset (bool isSourcePreset) inline
Definition at line 65 of file preset.h.
Referenced by MainCore::savePresetSettings(), and MainWindow::savePresetSettings().
 { m_sourcePreset = isSourcePreset; }
setSpectrumConfig()
void Preset::setSpectrumConfig (const QByteArray & data) inline
Definition at line 78 of file preset.h.
Referenced by MainWindow::savePresetSettings().
 { m_spectrumConfig = data; }
Friends And Related Function Documentation
WebAPIAdapterBase
friend class WebAPIAdapterBase friend
Definition at line 119 of file preset.h.
Member Data Documentation
m_centerFrequency
quint64 Preset::m_centerFrequency protected
Definition at line 127 of file preset.h.
Referenced by deserialize(), presetCompare(), resetToDefaults(), serialize(), and WebAPIAdapterBase::webapiFormatPreset().
m_channelConfigs
ChannelConfigs Preset::m_channelConfigs protected
Definition at line 137 of file preset.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_dcOffsetCorrection
bool Preset::m_dcOffsetCorrection protected
Definition at line 133 of file preset.h.
Referenced by resetToDefaults(), and WebAPIAdapterBase::webapiFormatPreset().
m_description
QString Preset::m_description protected
Definition at line 126 of file preset.h.
Referenced by deserialize(), presetCompare(), resetToDefaults(), serialize(), and WebAPIAdapterBase::webapiFormatPreset().
m_deviceConfigs
DeviceeConfigs Preset::m_deviceConfigs protected
Definition at line 140 of file preset.h.
Referenced by addOrUpdateDeviceConfig(), deserialize(), findBestDeviceConfig(), findBestDeviceConfigSoapy(), and serialize().
m_group
QString Preset::m_group protected
Definition at line 125 of file preset.h.
Referenced by deserialize(), presetCompare(), resetToDefaults(), serialize(), and WebAPIAdapterBase::webapiFormatPreset().
m_iqImbalanceCorrection
bool Preset::m_iqImbalanceCorrection protected
Definition at line 134 of file preset.h.
Referenced by resetToDefaults(), and WebAPIAdapterBase::webapiFormatPreset().
m_layout
QByteArray Preset::m_layout protected
Definition at line 143 of file preset.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
m_sourcePreset
bool Preset::m_sourcePreset protected
Definition at line 122 of file preset.h.
Referenced by deserialize(), resetToDefaults(), serialize(), and WebAPIAdapterBase::webapiFormatPreset().
m_spectrumConfig
QByteArray Preset::m_spectrumConfig protected
Definition at line 130 of file preset.h.
Referenced by deserialize(), resetToDefaults(), and serialize().
The documentation for this class was generated from the following files:
sdrbase/settings/preset.h
sdrbase/settings/preset.cpp