SDRAngel: ScopeVis::Traces Struct Reference
ScopeVis::Traces Struct Reference
Public Member Functions
Traces ()
~Traces ()
bool isVerticalDisplayChange (const TraceData &traceData, uint32_t traceIndex)
void addTrace (const TraceData &traceData, int traceSize)
void changeTrace (const TraceData &traceData, uint32_t traceIndex)
void removeTrace (uint32_t traceIndex)
void moveTrace (uint32_t traceIndex, bool upElseDown)
void resize (int traceSize)
uint32_t currentBufferIndex () const
uint32_t size () const
void switchBuffer ()
Public Attributes
std::vector< TraceControl * > m_tracesControl
Corresponding traces control data.
std::vector< TraceData > m_tracesData
Corresponding traces data.
std::vector< float * > m_traces [2]
Double buffer of traces processed by glScope.
int m_traceSize
Current size of a trace in buffer.
int m_maxTraceSize
Maximum Size of a trace in buffer.
bool evenOddIndex
Even (true) or odd (false) index.
Private Attributes
float * m_x0
float * m_x1
Detailed Description
Definition at line 874 of file scopevis.h.
Constructor & Destructor Documentation
Traces()
ScopeVis::Traces::Traces () inline
Definition at line 883 of file scopevis.h.
                  :
             m_traceSize(0),
             m_maxTraceSize(0),
             evenOddIndex(true),
             m_x0(0),
             m_x1(0)
         {
         }
~Traces()
ScopeVis::Traces::~Traces () inline
Definition at line 892 of file scopevis.h.
         {
             for (std::vector<TraceControl*>::iterator it = m_tracesControl.begin(); it != m_tracesControl.end(); ++it) {
                 delete *it;
             }
             if (m_x0) {
                 delete[] m_x0;
             }
             if (m_x1) {
                 delete[] m_x1;
             }
             m_maxTraceSize = 0;
         }
Member Function Documentation
addTrace()
void ScopeVis::Traces::addTrace (const TraceData & traceData, int traceSize) inline
Definition at line 917 of file scopevis.h.
References ScopeVis::TraceControl::initProjector(), and ScopeVis::TraceData::m_projectionType.
Referenced by ScopeVis::handleMessage().
         {
             if (m_traces[0].size() < m_maxNbTraces)
             {
                 qDebug("ScopeVis::addTrace");
                 m_traces[0].push_back(0);
                 m_traces[1].push_back(0);
                 m_tracesData.push_back(traceData);
                 m_tracesControl.push_back(new TraceControl());
                 TraceControl *traceControl = m_tracesControl.back();
                 traceControl->initProjector(traceData.m_projectionType);
                 resize(traceSize);
             }
         }
changeTrace()
void ScopeVis::Traces::changeTrace (const TraceData & traceData, uint32_t traceIndex) inline
Definition at line 933 of file scopevis.h.
References ScopeVis::TraceControl::initProjector(), ScopeVis::TraceData::m_projectionType, and ScopeVis::TraceControl::releaseProjector().
Referenced by ScopeVis::handleMessage().
         {
             if (traceIndex < m_tracesControl.size()) {
                 TraceControl *traceControl = m_tracesControl[traceIndex];
                 traceControl->releaseProjector();
                 traceControl->initProjector(traceData.m_projectionType);
                 m_tracesData[traceIndex] = traceData;
             }
         }
currentBufferIndex()
uint32_t ScopeVis::Traces::currentBufferIndex () const inline
Definition at line 1013 of file scopevis.h.
Referenced by ScopeVis::processTraces().
 { return evenOddIndex? 0 : 1; }
isVerticalDisplayChange()
bool ScopeVis::Traces::isVerticalDisplayChange (const TraceData & traceData, uint32_t traceIndex) inline
Definition at line 909 of file scopevis.h.
References ScopeVis::TraceData::m_amp, ScopeVis::TraceData::m_ofs, ScopeVis::TraceData::m_projectionType, and ScopeVis::TraceData::m_traceColor.
Referenced by ScopeVis::handleMessage().
         {
             return (m_tracesData[traceIndex].m_projectionType != traceData.m_projectionType)
                     || (m_tracesData[traceIndex].m_amp != traceData.m_amp)
                     || (m_tracesData[traceIndex].m_ofs != traceData.m_ofs
                     || (m_tracesData[traceIndex].m_traceColor != traceData.m_traceColor));
         }
moveTrace()
void ScopeVis::Traces::moveTrace (uint32_t traceIndex, bool upElseDown) inline
Definition at line 960 of file scopevis.h.
References ScopeVis::TraceControl::initProjector(), and ScopeVis::TraceControl::releaseProjector().
Referenced by ScopeVis::handleMessage().
         {
             if ((!upElseDown) && (traceIndex == 0)) {
                 return;
             }
             int nextControlIndex = (traceIndex + (upElseDown ? 1 : -1)) % (m_tracesControl.size());
             int nextDataIndex = (traceIndex + (upElseDown ? 1 : -1)) % (m_tracesData.size()); // should be the same
             TraceControl *traceControl = m_tracesControl[traceIndex];
             TraceControl *nextTraceControl = m_tracesControl[nextControlIndex];
             traceControl->releaseProjector();
             nextTraceControl->releaseProjector();
             m_tracesControl[nextControlIndex] = traceControl;
             m_tracesControl[traceIndex] = nextTraceControl;
             TraceData nextData = m_tracesData[nextDataIndex];
             m_tracesData[nextDataIndex] = m_tracesData[traceIndex];
             m_tracesData[traceIndex] = nextData;
             traceControl = m_tracesControl[traceIndex];
             nextTraceControl = m_tracesControl[nextControlIndex];
             traceControl->initProjector(m_tracesData[traceIndex].m_projectionType);
             nextTraceControl->initProjector(m_tracesData[nextDataIndex].m_projectionType);
         }
removeTrace()
void ScopeVis::Traces::removeTrace (uint32_t traceIndex) inline
Definition at line 943 of file scopevis.h.
References ScopeVis::TraceControl::releaseProjector().
Referenced by ScopeVis::handleMessage().
         {
             if (traceIndex < m_tracesControl.size())
             {
                 qDebug("ScopeVis::removeTrace");
                 m_traces[0].erase(m_traces[0].begin() + traceIndex);
                 m_traces[1].erase(m_traces[1].begin() + traceIndex);
                 TraceControl *traceControl = m_tracesControl[traceIndex];
                 traceControl->releaseProjector();
                 m_tracesControl.erase(m_tracesControl.begin() + traceIndex);
                 m_tracesData.erase(m_tracesData.begin() + traceIndex);
                 delete traceControl;
                 resize(m_traceSize); // reallocate pointers
             }
         }
resize()
void ScopeVis::Traces::resize (int traceSize) inline
Definition at line 989 of file scopevis.h.
References i.
Referenced by ScopeVis::setTraceSize().
         {
             m_traceSize = traceSize;
             if (m_traceSize > m_maxTraceSize)
             {
                 delete[] m_x0;
                 delete[] m_x1;
                 m_x0 = new float[2*m_traceSize*m_maxNbTraces];
                 m_x1 = new float[2*m_traceSize*m_maxNbTraces];
                 m_maxTraceSize = m_traceSize;
             }
             std::fill_n(m_x0, 2*m_traceSize*m_traces[0].size(), 0.0f);
             std::fill_n(m_x1, 2*m_traceSize*m_traces[0].size(), 0.0f);
             for (unsigned int i = 0; i < m_traces[0].size(); i++)
             {
                 (m_traces[0])[i] = &m_x0[2*m_traceSize*i];
                 (m_traces[1])[i] = &m_x1[2*m_traceSize*i];
             }
         }
size()
uint32_t ScopeVis::Traces::size () const inline
Definition at line 1014 of file scopevis.h.
 { return m_tracesControl.size(); }
switchBuffer()
void ScopeVis::Traces::switchBuffer () inline
Definition at line 1016 of file scopevis.h.
Referenced by ScopeVis::processTraces().
         {
             evenOddIndex = !evenOddIndex;
             for (std::vector<TraceControl*>::iterator it = m_tracesControl.begin(); it != m_tracesControl.end(); ++it)
             {
                 (*it)->m_traceCount[currentBufferIndex()] = 0;
             }
         }
Member Data Documentation
evenOddIndex
bool ScopeVis::Traces::evenOddIndex
Even (true) or odd (false) index.
Definition at line 881 of file scopevis.h.
m_maxTraceSize
int ScopeVis::Traces::m_maxTraceSize
Maximum Size of a trace in buffer.
Definition at line 880 of file scopevis.h.
m_traces
std::vector<float *> ScopeVis::Traces::m_traces[2]
Double buffer of traces processed by glScope.
Definition at line 878 of file scopevis.h.
Referenced by ScopeVis::initTraceBuffers(), ScopeVis::processTraces(), and ScopeVis::ScopeVis().
m_tracesControl
std::vector<TraceControl*> ScopeVis::Traces::m_tracesControl
Corresponding traces control data.
Definition at line 876 of file scopevis.h.
Referenced by ScopeVis::processTraces(), and ScopeVis::updateMaxTraceDelay().
m_tracesData
std::vector<TraceData> ScopeVis::Traces::m_tracesData
Corresponding traces data.
Definition at line 877 of file scopevis.h.
Referenced by ScopeVis::computeDisplayTriggerLevels(), ScopeVis::handleMessage(), ScopeVis::processTraces(), ScopeVis::ScopeVis(), and ScopeVis::updateMaxTraceDelay().
m_traceSize
int ScopeVis::Traces::m_traceSize
Current size of a trace in buffer.
Definition at line 879 of file scopevis.h.
m_x0
float* ScopeVis::Traces::m_x0 private
Definition at line 1027 of file scopevis.h.
m_x1
float* ScopeVis::Traces::m_x1 private
Definition at line 1028 of file scopevis.h.
The documentation for this struct was generated from the following file:
sdrgui/dsp/scopevis.h