SDRAngel: FileInput::MsgReportHeaderCRC Class Reference
FileInput::MsgReportHeaderCRC Class Reference
#include <fileinput.h>
Public Member Functions
bool isOK () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportHeaderCRC * create (bool ok)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgReportHeaderCRC (bool ok)
Protected Attributes
bool m_ok
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 259 of file fileinput.h.
Constructor & Destructor Documentation
MsgReportHeaderCRC()
FileInput::MsgReportHeaderCRC::MsgReportHeaderCRC (bool ok) inline protected
Definition at line 272 of file fileinput.h.
References FileInput::deserialize(), FileInput::destroy(), FileInput::FileInput(), FileInput::init(), FileInput::serialize(), FileInput::start(), FileInput::stop(), and FileInput::~FileInput().
                                     :
             Message(),
             m_ok(ok)
         { }
Member Function Documentation
create()
static MsgReportHeaderCRC* FileInput::MsgReportHeaderCRC::create (bool ok) inline static
Definition at line 265 of file fileinput.h.
Referenced by FileInput::openFileStream().
{
             return new MsgReportHeaderCRC(ok);
         }
isOK()
bool FileInput::MsgReportHeaderCRC::isOK () const inline
Definition at line 263 of file fileinput.h.
Referenced by FileInputGUI::handleMessage().
 { return m_ok; }
Member Data Documentation
m_ok
bool FileInput::MsgReportHeaderCRC::m_ok protected
Definition at line 270 of file fileinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/fileinput/fileinput.h