SDRAngel: NFMModPlugin Class Reference
NFMModPlugin Class Reference
#include <nfmmodplugin.h>
Public Member Functions
NFMModPlugin (QObject *parent=0)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *rxChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
Private Attributes
PluginAPI * m_pluginAPI
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Private Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Private Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Detailed Description
Definition at line 27 of file nfmmodplugin.h.
Constructor & Destructor Documentation
NFMModPlugin()
NFMModPlugin::NFMModPlugin (QObject * parent = 0) explicit
Definition at line 36 of file nfmmodplugin.cpp.
                                           :
     QObject(parent),
     m_pluginAPI(0)
 {
 }
Member Function Documentation
createTxChannelBS()
BasebandSampleSource * NFMModPlugin::createTxChannelBS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 69 of file nfmmodplugin.cpp.
 {
     return new NFMMod(deviceAPI);
 }
createTxChannelCS()
ChannelAPI * NFMModPlugin::createTxChannelCS (DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 74 of file nfmmodplugin.cpp.
 {
     return new NFMMod(deviceAPI);
 }
createTxChannelGUI()
PluginInstanceGUI * NFMModPlugin::createTxChannelGUI (DeviceUISet * deviceUISet, BasebandSampleSource * rxChannel) virtual
Reimplemented from PluginInterface.
Definition at line 63 of file nfmmodplugin.cpp.
References NFMModGUI::create(), and m_pluginAPI.
Referenced by initPlugin().
 {
     return NFMModGUI::create(m_pluginAPI, deviceUISet, txChannel);
 }
getPluginDescriptor()
const PluginDescriptor & NFMModPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 42 of file nfmmodplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void NFMModPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 47 of file nfmmodplugin.cpp.
References createTxChannelGUI(), NFMMod::m_channelId, NFMMod::m_channelIdURI, m_pluginAPI, and PluginAPI::registerTxChannel().
 {
     m_pluginAPI = pluginAPI;
     // register AM modulator
     m_pluginAPI->registerTxChannel(NFMMod::m_channelIdURI, NFMMod::m_channelId, this);
 }
Member Data Documentation
m_pluginAPI
PluginAPI* NFMModPlugin::m_pluginAPI private
Definition at line 45 of file nfmmodplugin.h.
Referenced by createTxChannelGUI(), and initPlugin().
m_pluginDescriptor
const PluginDescriptor NFMModPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("NFM Modulator"),
    QString("4.11.5"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 43 of file nfmmodplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/channeltx/modnfm/nfmmodplugin.h
plugins/channeltx/modnfm/nfmmodplugin.cpp