SDRAngel: PerseusPlugin Class Reference
PerseusPlugin Class Reference
#include <perseusplugin.h>
Public Member Functions
PerseusPlugin (QObject *parent=0)
const PluginDescriptor & getPluginDescriptor () const
void initPlugin (PluginAPI *pluginAPI)
virtual SamplingDevices enumSampleSources ()
virtual PluginInstanceGUI * createSampleSourcePluginInstanceGUI (const QString &sourceId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSource * createSampleSourcePluginInstance (const QString &sourceId, DeviceAPI *deviceAPI)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()
virtual PluginInstanceGUI * createRxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSink *rxChannel)
virtual BasebandSampleSink * createRxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createRxChannelCS (DeviceAPI *deviceAPI)
virtual PluginInstanceGUI * createTxChannelGUI (DeviceUISet *deviceUISet, BasebandSampleSource *txChannel)
virtual BasebandSampleSource * createTxChannelBS (DeviceAPI *deviceAPI)
virtual ChannelAPI * createTxChannelCS (DeviceAPI *deviceAPI)
virtual void deleteSampleSourcePluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSourcePluginInstanceInput (DeviceSampleSource *source)
virtual SamplingDevices enumSampleSinks ()
virtual PluginInstanceGUI * createSampleSinkPluginInstanceGUI (const QString &sinkId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleSink * createSampleSinkPluginInstance (const QString &sinkId, DeviceAPI *deviceAPI)
virtual void deleteSampleSinkPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleSinkPluginInstanceOutput (DeviceSampleSink *sink)
virtual SamplingDevices enumSampleMIMO ()
virtual PluginInstanceGUI * createSampleMIMOPluginInstanceGUI (const QString &mimoId, QWidget **widget, DeviceUISet *deviceUISet)
virtual DeviceSampleMIMO * createSampleMIMOPluginInstance (const QString &mimoId, DeviceAPI *deviceAPI)
virtual void deleteSampleMIMOPluginInstanceGUI (PluginInstanceGUI *ui)
virtual void deleteSampleMIMOPluginInstanceMIMO (DeviceSampleMIMO *mimo)
Static Public Attributes
static const QString m_hardwareID = "Perseus"
static const QString m_deviceTypeID = PERSEUS_DEVICE_TYPE_ID
static const int m_maxDevices = 32
Static Private Attributes
static const PluginDescriptor m_pluginDescriptor
Additional Inherited Members
Public Types inherited from PluginInterface
typedef QList< SamplingDevice > SamplingDevices
Detailed Description
Definition at line 28 of file perseusplugin.h.
Constructor & Destructor Documentation
PerseusPlugin()
PerseusPlugin::PerseusPlugin (QObject * parent = 0) explicit
Definition at line 45 of file perseusplugin.cpp.
                                             :
     QObject(parent)
 {
 }
Member Function Documentation
createSampleSourcePluginInstance()
DeviceSampleSource * PerseusPlugin::createSampleSourcePluginInstance (const QString & sourceId, DeviceAPI * deviceAPI) virtual
Reimplemented from PluginInterface.
Definition at line 121 of file perseusplugin.cpp.
References m_deviceTypeID.
 {
     if (sourceId == m_deviceTypeID)
     {
         PerseusInput* input = new PerseusInput(deviceAPI);
         return input;
     }
     else
     {
         return 0;
     }
 }
createSampleSourcePluginInstanceGUI()
PluginInstanceGUI * PerseusPlugin::createSampleSourcePluginInstanceGUI (const QString & sourceId, QWidget ** widget, DeviceUISet * deviceUISet) virtual
Reimplemented from PluginInterface.
Definition at line 103 of file perseusplugin.cpp.
References m_deviceTypeID.
Referenced by enumSampleSources().
 {
     if (sourceId == m_deviceTypeID)
     {
         PerseusGui* gui = new PerseusGui(deviceUISet);
         *widget = gui;
         return gui;
     }
     else
     {
         return 0;
     }
 }
enumSampleSources()
PluginInterface::SamplingDevices PerseusPlugin::enumSampleSources () virtual
Reimplemented from PluginInterface.
Definition at line 60 of file perseusplugin.cpp.
References arg(), createSampleSourcePluginInstanceGUI(), DevicePerseus::getSerials(), i, DevicePerseus::instance(), m_deviceTypeID, m_hardwareID, PluginInterface::SamplingDevice::PhysicalDevice, DevicePerseus::scan(), and PluginInterface::SamplingDevice::StreamSingleRx.
 {
     DevicePerseus::instance().scan();
     std::vector<std::string> serials;
     DevicePerseus::instance().getSerials(serials);
     std::vector<std::string>::const_iterator it = serials.begin();
     int i;
     SamplingDevices result;
     for (i = 0; it != serials.end(); ++it, ++i)
     {
         QString serial_str = QString::fromLocal8Bit(it->c_str());
         QString displayedName(QString("Perseus[%1] %2").arg(i).arg(serial_str));
         result.append(SamplingDevice(displayedName,
                 m_hardwareID,
                 m_deviceTypeID,
                 serial_str,
                 i,
                 PluginInterface::SamplingDevice::PhysicalDevice,
                 PluginInterface::SamplingDevice::StreamSingleRx,
                 1,
                 0));
         qDebug("PerseusPlugin::enumSampleSources: enumerated Perseus device #%d", i);
     }
     return result;
 }
getPluginDescriptor()
const PluginDescriptor & PerseusPlugin::getPluginDescriptor () const virtual
Implements PluginInterface.
Definition at line 50 of file perseusplugin.cpp.
References m_pluginDescriptor.
 {
     return m_pluginDescriptor;
 }
initPlugin()
void PerseusPlugin::initPlugin (PluginAPI * pluginAPI) virtual
Implements PluginInterface.
Definition at line 55 of file perseusplugin.cpp.
References m_deviceTypeID, and PluginAPI::registerSampleSource().
 {
     pluginAPI->registerSampleSource(m_deviceTypeID, this);
 }
Member Data Documentation
m_deviceTypeID
const QString PerseusPlugin::m_deviceTypeID = PERSEUS_DEVICE_TYPE_ID static
Definition at line 47 of file perseusplugin.h.
Referenced by createSampleSourcePluginInstance(), createSampleSourcePluginInstanceGUI(), enumSampleSources(), and initPlugin().
m_hardwareID
const QString PerseusPlugin::m_hardwareID = "Perseus" static
Definition at line 46 of file perseusplugin.h.
Referenced by enumSampleSources().
m_maxDevices
const int PerseusPlugin::m_maxDevices = 32 static
Definition at line 48 of file perseusplugin.h.
m_pluginDescriptor
const PluginDescriptor PerseusPlugin::m_pluginDescriptor static private
Initial value:
= {
    QString("Perseus Input"),
    QString("4.5.2"),
    QString("(c) Edouard Griffiths, F4EXB"),
    QString("https://github.com/f4exb/sdrangel"),
    true,
    QString("https://github.com/f4exb/sdrangel")
}
Definition at line 51 of file perseusplugin.h.
Referenced by getPluginDescriptor().
The documentation for this class was generated from the following files:
plugins/samplesource/perseus/perseusplugin.h
plugins/samplesource/perseus/perseusplugin.cpp