SDRAngel: DeviceSoapySDRShared::MsgReportBuddyChange Class Reference
DeviceSoapySDRShared::MsgReportBuddyChange Class Reference
#include <devicesoapysdrshared.h>
Public Member Functions
uint64_t getCenterFrequency () const
int getLOppmTenths () const
int getFcPos () const
int getDevSampleRate () const
bool getRxElseTx () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgReportBuddyChange * create (uint64_t centerFrequency, int LOppmTenths, int fcPos, int devSampleRate, bool rxElseTx)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgReportBuddyChange (uint64_t centerFrequency, int LOppmTenths, int fcPos, int devSampleRate, bool rxElseTx)
Private Attributes
uint64_t m_centerFrequency
Center frequency.
int m_LOppmTenths
LO soft correction in tenths of ppm.
int m_fcPos
Center frequency position.
int m_devSampleRate
device/host sample rate
bool m_rxElseTx
tells which side initiated the message
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 39 of file devicesoapysdrshared.h.
Constructor & Destructor Documentation
MsgReportBuddyChange()
DeviceSoapySDRShared::MsgReportBuddyChange::MsgReportBuddyChange (uint64_t centerFrequency, int LOppmTenths, int fcPos, int devSampleRate, bool rxElseTx) inline private
Definition at line 71 of file devicesoapysdrshared.h.
                                :
             Message(),
             m_centerFrequency(centerFrequency),
             m_LOppmTenths(LOppmTenths),
             m_fcPos(fcPos),
             m_devSampleRate(devSampleRate),
             m_rxElseTx(rxElseTx)
         { }
Member Function Documentation
create()
static MsgReportBuddyChange* DeviceSoapySDRShared::MsgReportBuddyChange::create (uint64_t centerFrequency, int LOppmTenths, int fcPos, int devSampleRate, bool rxElseTx) inline static
Definition at line 49 of file devicesoapysdrshared.h.
Referenced by SoapySDROutput::applySettings(), and SoapySDRInput::applySettings().
         {
             return new MsgReportBuddyChange(
                     centerFrequency,
                     LOppmTenths,
                     fcPos,
                     devSampleRate,
                     rxElseTx);
         }
getCenterFrequency()
uint64_t DeviceSoapySDRShared::MsgReportBuddyChange::getCenterFrequency () const inline
Definition at line 43 of file devicesoapysdrshared.h.
 { return m_centerFrequency; }
getDevSampleRate()
int DeviceSoapySDRShared::MsgReportBuddyChange::getDevSampleRate () const inline
Definition at line 46 of file devicesoapysdrshared.h.
 { return m_devSampleRate; }
getFcPos()
int DeviceSoapySDRShared::MsgReportBuddyChange::getFcPos () const inline
Definition at line 45 of file devicesoapysdrshared.h.
Referenced by SoapySDRInput::handleMessage().
 { return m_fcPos; }
getLOppmTenths()
int DeviceSoapySDRShared::MsgReportBuddyChange::getLOppmTenths () const inline
Definition at line 44 of file devicesoapysdrshared.h.
 { return m_LOppmTenths; }
getRxElseTx()
bool DeviceSoapySDRShared::MsgReportBuddyChange::getRxElseTx () const inline
Definition at line 47 of file devicesoapysdrshared.h.
 { return m_rxElseTx; }
Member Data Documentation
m_centerFrequency
uint64_t DeviceSoapySDRShared::MsgReportBuddyChange::m_centerFrequency private
Center frequency.
Definition at line 65 of file devicesoapysdrshared.h.
m_devSampleRate
int DeviceSoapySDRShared::MsgReportBuddyChange::m_devSampleRate private
device/host sample rate
Definition at line 68 of file devicesoapysdrshared.h.
m_fcPos
int DeviceSoapySDRShared::MsgReportBuddyChange::m_fcPos private
Center frequency position.
Definition at line 67 of file devicesoapysdrshared.h.
m_LOppmTenths
int DeviceSoapySDRShared::MsgReportBuddyChange::m_LOppmTenths private
LO soft correction in tenths of ppm.
Definition at line 66 of file devicesoapysdrshared.h.
m_rxElseTx
bool DeviceSoapySDRShared::MsgReportBuddyChange::m_rxElseTx private
tells which side initiated the message
Definition at line 69 of file devicesoapysdrshared.h.
The documentation for this class was generated from the following file:
devices/soapysdr/devicesoapysdrshared.h