SDRAngel: qrtplib::RTCPSchedulerParams Class Reference
qrtplib::RTCPSchedulerParams Class Reference
#include <rtcpscheduler.h>
Public Member Functions
RTCPSchedulerParams ()
~RTCPSchedulerParams ()
int SetRTCPBandwidth (double bw)
double GetRTCPBandwidth () const
int SetSenderBandwidthFraction (double fraction)
double GetSenderBandwidthFraction () const
int SetMinimumTransmissionInterval (const RTPTime &t)
RTPTime GetMinimumTransmissionInterval () const
void SetUseHalfAtStartup (bool usehalf)
bool GetUseHalfAtStartup () const
void SetRequestImmediateBYE (bool v)
bool GetRequestImmediateBYE () const
Private Attributes
double bandwidth
double senderfraction
RTPTime mininterval
bool usehalfatstartup
bool immediatebye
Detailed Description
Describes parameters used by the RTCPScheduler class.
Definition at line 56 of file rtcpscheduler.h.
Constructor & Destructor Documentation
RTCPSchedulerParams()
qrtplib::RTCPSchedulerParams::RTCPSchedulerParams ()
Definition at line 46 of file rtcpscheduler.cpp.
References bandwidth, qrtplib::RTPTimeInitializerObject::Dummy(), immediatebye, RTCP_DEFAULTHALFATSTARTUP, RTCP_DEFAULTIMMEDIATEBYE, RTCP_DEFAULTSENDERFRACTION, senderfraction, qrtplib::timeinit, and usehalfatstartup.
                                          :
         mininterval(RTCP_DEFAULTMININTERVAL)
 {
     bandwidth = 1000; // TODO What is a good value here?
     senderfraction = RTCP_DEFAULTSENDERFRACTION;
     usehalfatstartup = RTCP_DEFAULTHALFATSTARTUP;
     immediatebye = RTCP_DEFAULTIMMEDIATEBYE;
     timeinit.Dummy();
 }
~RTCPSchedulerParams()
qrtplib::RTCPSchedulerParams::~RTCPSchedulerParams ()
Definition at line 56 of file rtcpscheduler.cpp.
 {
 }
Member Function Documentation
GetMinimumTransmissionInterval()
RTPTime qrtplib::RTCPSchedulerParams::GetMinimumTransmissionInterval () const inline
Returns the minimum RTCP transmission interval (default is 5 seconds).
Definition at line 84 of file rtcpscheduler.h.
Referenced by qrtplib::RTCPScheduler::CalculateBYETransmissionInterval(), and qrtplib::RTCPScheduler::CalculateDeterministicInterval().
     {
         return mininterval;
     }
GetRequestImmediateBYE()
bool qrtplib::RTCPSchedulerParams::GetRequestImmediateBYE () const inline
Returns if the scheduler will schedule a BYE packet to be sent immediately if allowed (default is true).
Definition at line 112 of file rtcpscheduler.h.
Referenced by qrtplib::RTCPScheduler::ScheduleBYEPacket().
     {
         return immediatebye;
     }
GetRTCPBandwidth()
double qrtplib::RTCPSchedulerParams::GetRTCPBandwidth () const inline
Returns the used RTCP bandwidth in bytes per second (default is 1000).
Definition at line 66 of file rtcpscheduler.h.
Referenced by qrtplib::RTCPScheduler::CalculateBYETransmissionInterval(), and qrtplib::RTCPScheduler::CalculateDeterministicInterval().
     {
         return bandwidth;
     }
GetSenderBandwidthFraction()
double qrtplib::RTCPSchedulerParams::GetSenderBandwidthFraction () const inline
Returns the fraction of the RTCP bandwidth reserved for senders (default is 25%).
Definition at line 75 of file rtcpscheduler.h.
Referenced by qrtplib::RTCPScheduler::CalculateBYETransmissionInterval(), and qrtplib::RTCPScheduler::CalculateDeterministicInterval().
     {
         return senderfraction;
     }
GetUseHalfAtStartup()
bool qrtplib::RTCPSchedulerParams::GetUseHalfAtStartup () const inline
Returns true if only half the minimum interval should be used before sending the first RTCP compound packet (defualt is true).
Definition at line 98 of file rtcpscheduler.h.
Referenced by qrtplib::RTCPScheduler::CalculateBYETransmissionInterval(), and qrtplib::RTCPScheduler::CalculateDeterministicInterval().
     {
         return usehalfatstartup;
     }
SetMinimumTransmissionInterval()
int qrtplib::RTCPSchedulerParams::SetMinimumTransmissionInterval (const RTPTime & t)
Sets the minimum (deterministic) interval between RTCP compound packets to t.
Definition at line 76 of file rtcpscheduler.cpp.
References ERR_RTP_SCHEDPARAMS_BADMINIMUMINTERVAL, qrtplib::RTPTime::GetDouble(), mininterval, and RTCPSCHED_MININTERVAL.
Referenced by qrtplib::RTPSession::InternalCreate().
 {
     double t2 = t.GetDouble();
     if (t2 < RTCPSCHED_MININTERVAL)
         return ERR_RTP_SCHEDPARAMS_BADMINIMUMINTERVAL;
     mininterval = t;
     return 0;
 }
SetRequestImmediateBYE()
void qrtplib::RTCPSchedulerParams::SetRequestImmediateBYE (bool v) inline
If v is true, the scheduler will schedule a BYE packet to be sent immediately if allowed.
Definition at line 104 of file rtcpscheduler.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         immediatebye = v;
     }
SetRTCPBandwidth()
int qrtplib::RTCPSchedulerParams::SetRTCPBandwidth (double bw)
Sets the RTCP bandwidth to be used to bw (in bytes per second).
Definition at line 60 of file rtcpscheduler.cpp.
References bandwidth, and ERR_RTP_SCHEDPARAMS_INVALIDBANDWIDTH.
Referenced by qrtplib::RTPSession::InternalCreate(), and qrtplib::RTPSession::SetSessionBandwidth().
 {
     if (bw < 0.0)
         return ERR_RTP_SCHEDPARAMS_INVALIDBANDWIDTH;
     bandwidth = bw;
     return 0;
 }
SetSenderBandwidthFraction()
int qrtplib::RTCPSchedulerParams::SetSenderBandwidthFraction (double fraction)
Sets the fraction of the RTCP bandwidth reserved for senders to fraction.
Definition at line 68 of file rtcpscheduler.cpp.
References ERR_RTP_SCHEDPARAMS_BADFRACTION, and senderfraction.
Referenced by qrtplib::RTPSession::InternalCreate().
 {
     if (fraction < 0.0 || fraction > 1.0)
         return ERR_RTP_SCHEDPARAMS_BADFRACTION;
     senderfraction = fraction;
     return 0;
 }
SetUseHalfAtStartup()
void qrtplib::RTCPSchedulerParams::SetUseHalfAtStartup (bool usehalf) inline
If usehalf is true, only use half the minimum interval before sending the first RTCP compound packet.
Definition at line 90 of file rtcpscheduler.h.
Referenced by qrtplib::RTPSession::InternalCreate().
     {
         usehalfatstartup = usehalf;
     }
Member Data Documentation
bandwidth
double qrtplib::RTCPSchedulerParams::bandwidth private
Definition at line 117 of file rtcpscheduler.h.
Referenced by RTCPSchedulerParams(), and SetRTCPBandwidth().
immediatebye
bool qrtplib::RTCPSchedulerParams::immediatebye private
Definition at line 121 of file rtcpscheduler.h.
Referenced by RTCPSchedulerParams().
mininterval
RTPTime qrtplib::RTCPSchedulerParams::mininterval private
Definition at line 119 of file rtcpscheduler.h.
Referenced by SetMinimumTransmissionInterval().
senderfraction
double qrtplib::RTCPSchedulerParams::senderfraction private
Definition at line 118 of file rtcpscheduler.h.
Referenced by RTCPSchedulerParams(), and SetSenderBandwidthFraction().
usehalfatstartup
bool qrtplib::RTCPSchedulerParams::usehalfatstartup private
Definition at line 120 of file rtcpscheduler.h.
Referenced by RTCPSchedulerParams().
The documentation for this class was generated from the following files:
qrtplib/rtcpscheduler.h
qrtplib/rtcpscheduler.cpp