SDRAngel: SWGSDRangel::SWGPresetExport Class Reference
SWGSDRangel::SWGPresetExport Class Reference
#include <SWGPresetExport.h>
Public Member Functions
SWGPresetExport ()
SWGPresetExport (QString *json)
virtual ~SWGPresetExport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGPresetExport * fromJson (QString &jsonString) override
QString * getFilePath ()
void setFilePath (QString *file_path)
SWGPresetIdentifier * getPreset ()
void setPreset (SWGPresetIdentifier *preset)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * file_path
bool m_file_path_isSet
SWGPresetIdentifier * preset
bool m_preset_isSet
Detailed Description
Definition at line 33 of file SWGPresetExport.h.
Constructor & Destructor Documentation
SWGPresetExport() [1/2]
SWGSDRangel::SWGPresetExport::SWGPresetExport ()
Definition at line 30 of file SWGPresetExport.cpp.
References file_path, m_file_path_isSet, m_preset_isSet, and preset.
{
     file_path = nullptr;
     m_file_path_isSet = false;
     preset = nullptr;
     m_preset_isSet = false;
 }
SWGPresetExport() [2/2]
SWGSDRangel::SWGPresetExport::SWGPresetExport (QString * json)
Definition at line 25 of file SWGPresetExport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGPresetExport()
SWGSDRangel::SWGPresetExport::~SWGPresetExport () virtual
Definition at line 37 of file SWGPresetExport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGPresetExport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 77 of file SWGPresetExport.cpp.
References asJsonObject().
Referenced by SWGSDRangel::SWGInstanceApi::instancePresetFilePost().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGPresetExport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 88 of file SWGPresetExport.cpp.
References file_path, SWGSDRangel::SWGPresetIdentifier::isSet(), preset, and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(file_path != nullptr && *file_path != QString("")){
         toJsonValue(QString("filePath"), file_path, obj, QString("QString"));
     }
     if((preset != nullptr) && (preset->isSet())){
         toJsonValue(QString("preset"), preset, obj, QString("SWGPresetIdentifier"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGPresetExport::cleanup ()
Definition at line 50 of file SWGPresetExport.cpp.
References file_path, and preset.
Referenced by ~SWGPresetExport().
{
     if(file_path != nullptr) {
         delete file_path;
     }
     if(preset != nullptr) {
         delete preset;
     }
 }
fromJson()
SWGPresetExport * SWGSDRangel::SWGPresetExport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 60 of file SWGPresetExport.cpp.
References fromJsonObject().
Referenced by WebAPIRequestMapper::instancePresetFileService(), and SWGPresetExport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGPresetExport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 69 of file SWGPresetExport.cpp.
References file_path, preset, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&file_path, pJson["filePath"], "QString", "QString");
     ::SWGSDRangel::setValue(&preset, pJson["preset"], "SWGPresetIdentifier", "SWGPresetIdentifier");
 }
getFilePath()
QString * SWGSDRangel::SWGPresetExport::getFilePath ()
Definition at line 101 of file SWGPresetExport.cpp.
References file_path.
Referenced by WebAPIAdapterSrv::instancePresetFilePost(), and WebAPIRequestMapper::validatePresetExport().
{
     return file_path;
 }
getPreset()
SWGPresetIdentifier * SWGSDRangel::SWGPresetExport::getPreset ()
Definition at line 111 of file SWGPresetExport.cpp.
References preset.
Referenced by WebAPIAdapterSrv::instancePresetFilePost(), and WebAPIRequestMapper::validatePresetExport().
{
     return preset;
 }
init()
void SWGSDRangel::SWGPresetExport::init ()
Definition at line 42 of file SWGPresetExport.cpp.
References file_path, m_file_path_isSet, m_preset_isSet, and preset.
Referenced by SWGPresetExport().
                       {
     file_path = new QString("");
     m_file_path_isSet = false;
     preset = new SWGPresetIdentifier();
     m_preset_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGPresetExport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 122 of file SWGPresetExport.cpp.
References file_path, SWGSDRangel::SWGPresetIdentifier::isSet(), and preset.
                       {
     bool isObjectUpdated = false;
     do{
         if(file_path != nullptr && *file_path != QString("")){ isObjectUpdated = true; break;}
         if(preset != nullptr && preset->isSet()){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setFilePath()
void SWGSDRangel::SWGPresetExport::setFilePath (QString * file_path)
Definition at line 105 of file SWGPresetExport.cpp.
References file_path, and m_file_path_isSet.
{
     this->file_path = file_path;
     this->m_file_path_isSet = true;
 }
setPreset()
void SWGSDRangel::SWGPresetExport::setPreset (SWGPresetIdentifier * preset)
Definition at line 115 of file SWGPresetExport.cpp.
References m_preset_isSet, and preset.
{
     this->preset = preset;
     this->m_preset_isSet = true;
 }
Member Data Documentation
file_path
QString* SWGSDRangel::SWGPresetExport::file_path private
Definition at line 56 of file SWGPresetExport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getFilePath(), init(), isSet(), setFilePath(), and SWGPresetExport().
m_file_path_isSet
bool SWGSDRangel::SWGPresetExport::m_file_path_isSet private
Definition at line 57 of file SWGPresetExport.h.
Referenced by init(), setFilePath(), and SWGPresetExport().
m_preset_isSet
bool SWGSDRangel::SWGPresetExport::m_preset_isSet private
Definition at line 60 of file SWGPresetExport.h.
Referenced by init(), setPreset(), and SWGPresetExport().
preset
SWGPresetIdentifier* SWGSDRangel::SWGPresetExport::preset private
Definition at line 59 of file SWGPresetExport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getPreset(), init(), isSet(), setPreset(), and SWGPresetExport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGPresetExport.h
swagger/sdrangel/code/qt5/client/SWGPresetExport.cpp