SDRAngel: MainSettings Class Reference
MainSettings Class Reference
#include <mainsettings.h>
Public Member Functions
MainSettings ()
~MainSettings ()
void load ()
void save () const
void resetToDefaults ()
QString getFileLocation () const
int getFileFormat () const
see QSettings::Format for the values
const Preferences & getPreferences () const
Preset * newPreset (const QString &group, const QString &description)
void deletePreset (const Preset *preset)
int getPresetCount () const
const Preset * getPreset (int index) const
const Preset * getPreset (const QString &groupName, quint64 centerFrequency, const QString &description, const QString &type) const
void sortPresets ()
void renamePresetGroup (const QString &oldGroupName, const QString &newGroupName)
void deletePresetGroup (const QString &groupName)
void addCommand (Command *command)
void deleteCommand (const Command *command)
int getCommandCount () const
const Command * getCommand (int index) const
const Command * getCommand (const QString &groupName, const QString &description) const
void sortCommands ()
void renameCommandGroup (const QString &oldGroupName, const QString &newGroupName)
void deleteCommandGroup (const QString &groupName)
const Preset & getWorkingPresetConst () const
Preset * getWorkingPreset ()
int getSourceIndex () const
void setSourceIndex (int value)
const QString & getSourceDeviceId () const
void setSourceDeviceId (const QString &deviceId)
void setLatitude (float latitude)
void setLongitude (float longitude)
float getLatitude () const
float getLongitude () const
void setConsoleMinLogLevel (const QtMsgType &minLogLevel)
void setFileMinLogLevel (const QtMsgType &minLogLevel)
void setUseLogFile (bool useLogFile)
void setLogFileName (const QString &value)
QtMsgType getConsoleMinLogLevel () const
QtMsgType getFileMinLogLevel () const
bool getUseLogFile () const
const QString & getLogFileName () const
DeviceUserArgs & getDeviceUserArgs ()
const AudioDeviceManager * getAudioDeviceManager () const
void setAudioDeviceManager (AudioDeviceManager *audioDeviceManager)
void setAMBEEngine (AMBEEngine *ambeEngine)
Protected Types
typedef QList< Preset * > Presets
typedef QList< Command * > Commands
Protected Attributes
Preferences m_preferences
AudioDeviceManager * m_audioDeviceManager
Preset m_workingPreset
Presets m_presets
Commands m_commands
DeviceUserArgs m_hardwareDeviceUserArgs
AMBEEngine * m_ambeEngine
Detailed Description
Definition at line 14 of file mainsettings.h.
Member Typedef Documentation
Commands
typedef QList<Command*> MainSettings::Commands protected
Definition at line 78 of file mainsettings.h.
Presets
typedef QList<Preset*> MainSettings::Presets protected
Definition at line 76 of file mainsettings.h.
Constructor & Destructor Documentation
MainSettings()
MainSettings::MainSettings ()
Definition at line 9 of file mainsettings.cpp.
References getFileFormat(), getFileLocation(), and resetToDefaults().
                            :
     m_audioDeviceManager(nullptr),
     m_ambeEngine(nullptr)
 {
     resetToDefaults();
     qInfo("MainSettings::MainSettings: settings file: format: %d location: %s", getFileFormat(), qPrintable(getFileLocation()));
 }
~MainSettings()
MainSettings::~MainSettings ()
Definition at line 17 of file mainsettings.cpp.
References i, m_commands, and m_presets.
 {
     for(int i = 0; i < m_presets.count(); ++i)
     {
         delete m_presets[i];
     }
     for(int i = 0; i < m_commands.count(); ++i)
     {
         delete m_commands[i];
     }
 }
Member Function Documentation
addCommand()
void MainSettings::addCommand (Command * command)
Definition at line 217 of file mainsettings.cpp.
References m_commands.
Referenced by MainWindow::on_commandDuplicate_clicked(), and MainWindow::on_commandNew_clicked().
 {
     m_commands.append(command);
 }
deleteCommand()
void MainSettings::deleteCommand (const Command * command)
Definition at line 222 of file mainsettings.cpp.
References m_commands.
Referenced by MainWindow::on_commandDelete_clicked().
 {
     m_commands.removeAll((Command*)command);
     delete (Command*)command;
 }
deleteCommandGroup()
void MainSettings::deleteCommandGroup (const QString & groupName)
Definition at line 228 of file mainsettings.cpp.
References m_commands.
Referenced by MainWindow::on_commandDelete_clicked().
 {
     Commands::iterator it = m_commands.begin();
     while (it != m_commands.end())
     {
         if ((*it)->getGroup() == groupName) {
             it = m_commands.erase(it);
         } else {
             ++it;
         }
     }
 }
deletePreset()
void MainSettings::deletePreset (const Preset * preset)
Definition at line 157 of file mainsettings.cpp.
References m_presets.
Referenced by MainCore::handleMessage(), MainWindow::handleMessage(), and MainWindow::on_presetDelete_clicked().
 {
     m_presets.removeAll((Preset*)preset);
     delete (Preset*)preset;
 }
deletePresetGroup()
void MainSettings::deletePresetGroup (const QString & groupName)
Definition at line 163 of file mainsettings.cpp.
References m_presets.
Referenced by MainWindow::on_presetDelete_clicked().
 {
     Presets::iterator it = m_presets.begin();
     while (it != m_presets.end())
     {
         if ((*it)->getGroup() == groupName) {
             it = m_presets.erase(it);
         } else {
             ++it;
         }
     }
 }
getAudioDeviceManager()
const AudioDeviceManager* MainSettings::getAudioDeviceManager () const inline
Definition at line 68 of file mainsettings.h.
 { return m_audioDeviceManager; }
getCommand() [1/2]
const Command* MainSettings::getCommand (int index) const inline
Definition at line 40 of file mainsettings.h.
Referenced by MainWindow::commandKeyPressed(), getCommand(), MainWindow::loadSettings(), MainWindow::on_commandDelete_clicked(), MainWindow::on_commandEdit_clicked(), MainWindow::on_commandRun_clicked(), and renameCommandGroup().
 { return m_commands[index]; }
getCommand() [2/2]
const Command * MainSettings::getCommand (const QString & groupName, const QString & description) const
Definition at line 261 of file mainsettings.cpp.
References getCommand(), getCommandCount(), and i.
 {
     int nbCommands = getCommandCount();
     for (int i = 0; i < nbCommands; i++)
     {
         if ((getCommand(i)->getGroup() == groupName) &&
             (getCommand(i)->getDescription() == description))
         {
             return getCommand(i);
         }
     }
     return 0;
 }
getCommandCount()
int MainSettings::getCommandCount () const inline
Definition at line 39 of file mainsettings.h.
Referenced by MainWindow::commandKeyPressed(), getCommand(), MainWindow::loadSettings(), MainWindow::on_commandDelete_clicked(), MainWindow::on_commandEdit_clicked(), MainWindow::on_commandRun_clicked(), and renameCommandGroup().
 { return m_commands.count(); }
getConsoleMinLogLevel()
QtMsgType MainSettings::getConsoleMinLogLevel () const inline
Definition at line 62 of file mainsettings.h.
Referenced by WebAPIAdapterGUI::instanceLoggingPut(), WebAPIAdapterSrv::instanceLoggingPut(), LoggingDialog::LoggingDialog(), MainCore::setLoggingOptions(), and MainWindow::setLoggingOptions().
 { return m_preferences.getConsoleMinLogLevel(); }
getDeviceUserArgs()
DeviceUserArgs& MainSettings::getDeviceUserArgs () inline
Definition at line 66 of file mainsettings.h.
Referenced by MainWindow::addMIMODevice(), MainCore::addSinkDevice(), MainWindow::addSinkDevice(), MainCore::addSourceDevice(), MainWindow::addSourceDevice(), MainWindow::on_action_DeviceUserArguments_triggered(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { return m_hardwareDeviceUserArgs; }
getFileFormat()
int MainSettings::getFileFormat () const
see QSettings::Format for the values
Definition at line 36 of file mainsettings.cpp.
Referenced by MainSettings().
 {
     QSettings s;
     return (int) s.format();
 }
getFileLocation()
QString MainSettings::getFileLocation () const
Definition at line 30 of file mainsettings.cpp.
Referenced by AboutDialog::AboutDialog(), and MainSettings().
 {
     QSettings s;
     return s.fileName();
 }
getFileMinLogLevel()
QtMsgType MainSettings::getFileMinLogLevel () const inline
Definition at line 63 of file mainsettings.h.
Referenced by WebAPIAdapterGUI::instanceLoggingPut(), WebAPIAdapterSrv::instanceLoggingPut(), LoggingDialog::LoggingDialog(), MainCore::setLoggingOptions(), and MainWindow::setLoggingOptions().
 { return m_preferences.getFileMinLogLevel(); }
getLatitude()
float MainSettings::getLatitude () const inline
Definition at line 55 of file mainsettings.h.
Referenced by WebAPIAdapterGUI::instanceLocationGet(), WebAPIAdapterSrv::instanceLocationGet(), WebAPIAdapterGUI::instanceLocationPut(), WebAPIAdapterSrv::instanceLocationPut(), MyPositionDialog::MyPositionDialog(), and DSDDemodGUI::updateMyPosition().
 { return m_preferences.getLatitude(); }
getLogFileName()
const QString& MainSettings::getLogFileName () const inline
Definition at line 65 of file mainsettings.h.
Referenced by WebAPIAdapterGUI::instanceLoggingPut(), WebAPIAdapterSrv::instanceLoggingPut(), LoggingDialog::LoggingDialog(), MainCore::setLoggingOptions(), and MainWindow::setLoggingOptions().
 { return m_preferences.getLogFileName(); }
getLongitude()
float MainSettings::getLongitude () const inline
Definition at line 56 of file mainsettings.h.
Referenced by WebAPIAdapterGUI::instanceLocationGet(), WebAPIAdapterSrv::instanceLocationGet(), WebAPIAdapterGUI::instanceLocationPut(), WebAPIAdapterSrv::instanceLocationPut(), MyPositionDialog::MyPositionDialog(), and DSDDemodGUI::updateMyPosition().
 { return m_preferences.getLongitude(); }
getPreferences()
const Preferences& MainSettings::getPreferences () const inline
Definition at line 26 of file mainsettings.h.
Referenced by WebAPIAdapterGUI::instanceConfigGet(), and WebAPIAdapterSrv::instanceConfigGet().
 { return m_preferences; }
getPreset() [1/2]
const Preset* MainSettings::getPreset (int index) const inline
Definition at line 31 of file mainsettings.h.
Referenced by getPreset(), WebAPIAdapterGUI::instanceConfigGet(), WebAPIAdapterSrv::instanceConfigGet(), WebAPIAdapterGUI::instancePresetDelete(), WebAPIAdapterSrv::instancePresetDelete(), WebAPIAdapterSrv::instancePresetFilePost(), WebAPIAdapterGUI::instancePresetPatch(), WebAPIAdapterSrv::instancePresetPatch(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), WebAPIAdapterGUI::instancePresetPut(), WebAPIAdapterSrv::instancePresetPut(), WebAPIAdapterGUI::instancePresetsGet(), WebAPIAdapterSrv::instancePresetsGet(), MainWindow::loadSettings(), MainWindow::on_presetDelete_clicked(), MainWindow::on_presetEdit_clicked(), MainWindow::on_presetUpdate_clicked(), and renamePresetGroup().
 { return m_presets[index]; }
getPreset() [2/2]
const Preset * MainSettings::getPreset (const QString & groupName, quint64 centerFrequency, const QString & description, const QString & type) const
Definition at line 196 of file mainsettings.cpp.
References getPreset(), getPresetCount(), and i.
 {
     int nbPresets = getPresetCount();
     for (int i = 0; i < nbPresets; i++)
     {
         if ((getPreset(i)->getGroup() == groupName) &&
             (getPreset(i)->getCenterFrequency() == centerFrequency) &&
             (getPreset(i)->getDescription() == description))
         {
             if (type == "R" && getPreset(i)->isSourcePreset()) {
                 return getPreset(i);
             } else if (type == "T" && !getPreset(i)->isSourcePreset()) {
                 return getPreset(i);
             }
         }
     }
     return 0;
 }
getPresetCount()
int MainSettings::getPresetCount () const inline
Definition at line 30 of file mainsettings.h.
Referenced by getPreset(), WebAPIAdapterSrv::instanceConfigGet(), WebAPIAdapterGUI::instanceConfigGet(), WebAPIAdapterGUI::instancePresetsGet(), WebAPIAdapterSrv::instancePresetsGet(), MainWindow::loadSettings(), MainWindow::on_presetDelete_clicked(), MainWindow::on_presetEdit_clicked(), MainWindow::on_presetUpdate_clicked(), and renamePresetGroup().
 { return m_presets.count(); }
getSourceDeviceId()
const QString& MainSettings::getSourceDeviceId () const inline
Definition at line 50 of file mainsettings.h.
Referenced by MainWindow::MainWindow().
 { return m_preferences.getSourceDevice(); }
getSourceIndex()
int MainSettings::getSourceIndex () const inline
Definition at line 48 of file mainsettings.h.
Referenced by MainWindow::MainWindow().
 { return m_preferences.getSourceIndex(); }
getUseLogFile()
bool MainSettings::getUseLogFile () const inline
Definition at line 64 of file mainsettings.h.
Referenced by WebAPIAdapterGUI::instanceLoggingPut(), WebAPIAdapterSrv::instanceLoggingPut(), LoggingDialog::LoggingDialog(), MainCore::setLoggingOptions(), and MainWindow::setLoggingOptions().
 { return m_preferences.getUseLogFile(); }
getWorkingPreset()
Preset* MainSettings::getWorkingPreset () inline
Definition at line 47 of file mainsettings.h.
Referenced by MainCore::changeSampleSink(), MainCore::changeSampleSource(), MainWindow::closeEvent(), MainWindow::MainWindow(), MainWindow::on_settingsSave_clicked(), MainWindow::sampleMIMOChanged(), MainWindow::sampleSinkChanged(), and MainWindow::sampleSourceChanged().
 { return &m_workingPreset; }
getWorkingPresetConst()
const Preset& MainSettings::getWorkingPresetConst () const inline
Definition at line 46 of file mainsettings.h.
Referenced by WebAPIAdapterGUI::instanceConfigGet(), and WebAPIAdapterSrv::instanceConfigGet().
 { return m_workingPreset; }
load()
void MainSettings::load ()
Definition at line 42 of file mainsettings.cpp.
References Preferences::deserialize(), Command::deserialize(), DeviceUserArgs::deserialize(), AMBEEngine::deserialize(), Preset::deserialize(), AudioDeviceManager::deserialize(), i, m_ambeEngine, m_audioDeviceManager, m_commands, m_hardwareDeviceUserArgs, m_preferences, m_presets, and m_workingPreset.
Referenced by MainCore::loadSettings(), and MainWindow::loadSettings().
 {
     QSettings s;
     m_preferences.deserialize(qUncompress(QByteArray::fromBase64(s.value("preferences").toByteArray())));
     m_workingPreset.deserialize(qUncompress(QByteArray::fromBase64(s.value("current").toByteArray())));
     if (m_audioDeviceManager) {
         m_audioDeviceManager->deserialize(qUncompress(QByteArray::fromBase64(s.value("audio").toByteArray())));
     }
     if (m_ambeEngine) {
         m_ambeEngine->deserialize(qUncompress(QByteArray::fromBase64(s.value("ambe").toByteArray())));
     }
     QStringList groups = s.childGroups();
     for(int i = 0; i < groups.size(); ++i)
     {
         if (groups[i].startsWith("preset"))
         {
             s.beginGroup(groups[i]);
             Preset* preset = new Preset;
             if(preset->deserialize(qUncompress(QByteArray::fromBase64(s.value("data").toByteArray()))))
             {
                 m_presets.append(preset);
             }
             else
             {
                 delete preset;
             }
             s.endGroup();
         }
         else if (groups[i].startsWith("command"))
         {
             s.beginGroup(groups[i]);
             Command* command = new Command;
             if(command->deserialize(qUncompress(QByteArray::fromBase64(s.value("data").toByteArray()))))
             {
                 m_commands.append(command);
             }
             else
             {
                 delete command;
             }
             s.endGroup();
         }
     }
     m_hardwareDeviceUserArgs.deserialize(qUncompress(QByteArray::fromBase64(s.value("hwDeviceUserArgs").toByteArray())));
 }
newPreset()
Preset * MainSettings::newPreset (const QString & group, const QString & description)
Definition at line 148 of file mainsettings.cpp.
References m_presets, Preset::setDescription(), and Preset::setGroup().
Referenced by WebAPIAdapterSrv::instancePresetFilePut(), WebAPIAdapterGUI::instancePresetPost(), WebAPIAdapterSrv::instancePresetPost(), MainWindow::on_presetImport_clicked(), and MainWindow::on_presetSave_clicked().
 {
     Preset* preset = new Preset();
     preset->setGroup(group);
     preset->setDescription(description);
     m_presets.append(preset);
     return preset;
 }
renameCommandGroup()
void MainSettings::renameCommandGroup (const QString & oldGroupName, const QString & newGroupName)
Definition at line 247 of file mainsettings.cpp.
References getCommand(), getCommandCount(), i, and Command::setGroup().
Referenced by MainWindow::on_commandEdit_clicked().
 {
     int nbCommands = getCommandCount();
     for (int i = 0; i < nbCommands; i++)
     {
         if (getCommand(i)->getGroup() == oldGroupName)
         {
             Command *command_mod = const_cast<Command*>(getCommand(i));
             command_mod->setGroup(newGroupName);
         }
     }
 }
renamePresetGroup()
void MainSettings::renamePresetGroup (const QString & oldGroupName, const QString & newGroupName)
Definition at line 182 of file mainsettings.cpp.
References getPreset(), getPresetCount(), i, and Preset::setGroup().
Referenced by MainWindow::on_presetEdit_clicked().
 {
     int nbPresets = getPresetCount();
     for (int i = 0; i < nbPresets; i++)
     {
         if (getPreset(i)->getGroup() == oldGroupName)
         {
             Preset *preset_mod = const_cast<Preset*>(getPreset(i));
             preset_mod->setGroup(newGroupName);
         }
     }
 }
resetToDefaults()
void MainSettings::resetToDefaults ()
Definition at line 142 of file mainsettings.cpp.
References m_preferences, m_workingPreset, Preferences::resetToDefaults(), and Preset::resetToDefaults().
Referenced by MainSettings().
 {
     m_preferences.resetToDefaults();
     m_workingPreset.resetToDefaults();
 }
save()
void MainSettings::save () const
Definition at line 98 of file mainsettings.cpp.
References i, m_ambeEngine, m_audioDeviceManager, m_commands, m_hardwareDeviceUserArgs, m_preferences, m_presets, m_workingPreset, Preferences::serialize(), DeviceUserArgs::serialize(), AMBEEngine::serialize(), Preset::serialize(), and AudioDeviceManager::serialize().
Referenced by MainWindow::closeEvent(), MainCore::handleMessage(), MainWindow::handleMessage(), MainWindow::on_commandsSave_clicked(), MainWindow::on_settingsSave_clicked(), and MainCore::~MainCore().
 {
     QSettings s;
     s.setValue("preferences", qCompress(m_preferences.serialize()).toBase64());
     s.setValue("current", qCompress(m_workingPreset.serialize()).toBase64());
     if (m_audioDeviceManager) {
         s.setValue("audio", qCompress(m_audioDeviceManager->serialize()).toBase64());
     }
     if (m_ambeEngine) {
         s.setValue("ambe", qCompress(m_ambeEngine->serialize()).toBase64());
     }
     QStringList groups = s.childGroups();
     for(int i = 0; i < groups.size(); ++i)
     {
         if ((groups[i].startsWith("preset")) || (groups[i].startsWith("command")))
         {
             s.remove(groups[i]);
         }
     }
     for (int i = 0; i < m_presets.count(); ++i)
     {
         QString group = QString("preset-%1").arg(i + 1);
         s.beginGroup(group);
         s.setValue("data", qCompress(m_presets[i]->serialize()).toBase64());
         s.endGroup();
     }
     for (int i = 0; i < m_commands.count(); ++i)
     {
         QString group = QString("command-%1").arg(i + 1);
         s.beginGroup(group);
         s.setValue("data", qCompress(m_commands[i]->serialize()).toBase64());
         s.endGroup();
     }
     s.setValue("hwDeviceUserArgs", qCompress(m_hardwareDeviceUserArgs.serialize()).toBase64());
 }
setAMBEEngine()
void MainSettings::setAMBEEngine (AMBEEngine * ambeEngine) inline
Definition at line 70 of file mainsettings.h.
Referenced by MainCore::MainCore(), and MainWindow::MainWindow().
 { m_ambeEngine = ambeEngine; }
setAudioDeviceManager()
void MainSettings::setAudioDeviceManager (AudioDeviceManager * audioDeviceManager) inline
Definition at line 69 of file mainsettings.h.
Referenced by MainCore::MainCore(), and MainWindow::MainWindow().
 { m_audioDeviceManager = audioDeviceManager; }
setConsoleMinLogLevel()
void MainSettings::setConsoleMinLogLevel (const QtMsgType & minLogLevel) inline
Definition at line 58 of file mainsettings.h.
Referenced by LoggingDialog::accept(), WebAPIAdapterSrv::instanceLoggingPut(), and WebAPIAdapterGUI::instanceLoggingPut().
 { m_preferences.setConsoleMinLogLevel(minLogLevel); }
setFileMinLogLevel()
void MainSettings::setFileMinLogLevel (const QtMsgType & minLogLevel) inline
Definition at line 59 of file mainsettings.h.
Referenced by LoggingDialog::accept(), WebAPIAdapterSrv::instanceLoggingPut(), and WebAPIAdapterGUI::instanceLoggingPut().
 { m_preferences.setFileMinLogLevel(minLogLevel); }
setLatitude()
void MainSettings::setLatitude (float latitude) inline
Definition at line 53 of file mainsettings.h.
Referenced by MyPositionDialog::accept(), WebAPIAdapterSrv::instanceLocationPut(), and WebAPIAdapterGUI::instanceLocationPut().
 { m_preferences.setLatitude(latitude); }
setLogFileName()
void MainSettings::setLogFileName (const QString & value) inline
Definition at line 61 of file mainsettings.h.
Referenced by LoggingDialog::accept(), WebAPIAdapterSrv::instanceLoggingPut(), and WebAPIAdapterGUI::instanceLoggingPut().
 { m_preferences.setLogFileName(value); }
setLongitude()
void MainSettings::setLongitude (float longitude) inline
Definition at line 54 of file mainsettings.h.
Referenced by MyPositionDialog::accept(), WebAPIAdapterSrv::instanceLocationPut(), and WebAPIAdapterGUI::instanceLocationPut().
 { m_preferences.setLongitude(longitude); }
setSourceDeviceId()
void MainSettings::setSourceDeviceId (const QString & deviceId) inline
Definition at line 51 of file mainsettings.h.
Referenced by MainWindow::sampleSourceChanged().
 { m_preferences.setSourceDevice(deviceId); }
setSourceIndex()
void MainSettings::setSourceIndex (int value) inline
Definition at line 49 of file mainsettings.h.
Referenced by MainWindow::sampleSourceChanged().
 { m_preferences.setSourceIndex(value); }
setUseLogFile()
void MainSettings::setUseLogFile (bool useLogFile) inline
Definition at line 60 of file mainsettings.h.
Referenced by LoggingDialog::accept(), WebAPIAdapterSrv::instanceLoggingPut(), and WebAPIAdapterGUI::instanceLoggingPut().
 { m_preferences.setUseLogFile(useLogFile); }
sortCommands()
void MainSettings::sortCommands ()
Definition at line 242 of file mainsettings.cpp.
References Command::commandCompare(), and m_commands.
Referenced by MainWindow::loadSettings(), MainWindow::on_commandDuplicate_clicked(), MainWindow::on_commandEdit_clicked(), and MainWindow::on_commandNew_clicked().
 {
     qSort(m_commands.begin(), m_commands.end(), Command::commandCompare);
 }
sortPresets()
void MainSettings::sortPresets ()
Definition at line 177 of file mainsettings.cpp.
References m_presets, and Preset::presetCompare().
Referenced by MainCore::handleMessage(), MainWindow::handleMessage(), MainCore::loadSettings(), MainWindow::loadSettings(), MainWindow::on_presetEdit_clicked(), MainWindow::on_presetSave_clicked(), and MainWindow::on_presetUpdate_clicked().
 {
     qSort(m_presets.begin(), m_presets.end(), Preset::presetCompare);
 }
Member Data Documentation
m_ambeEngine
AMBEEngine* MainSettings::m_ambeEngine protected
Definition at line 81 of file mainsettings.h.
Referenced by load(), and save().
m_audioDeviceManager
AudioDeviceManager* MainSettings::m_audioDeviceManager protected
Definition at line 74 of file mainsettings.h.
Referenced by load(), and save().
m_commands
Commands MainSettings::m_commands protected
Definition at line 79 of file mainsettings.h.
Referenced by addCommand(), deleteCommand(), deleteCommandGroup(), load(), save(), sortCommands(), and ~MainSettings().
m_hardwareDeviceUserArgs
DeviceUserArgs MainSettings::m_hardwareDeviceUserArgs protected
Definition at line 80 of file mainsettings.h.
Referenced by load(), and save().
m_preferences
Preferences MainSettings::m_preferences protected
Definition at line 73 of file mainsettings.h.
Referenced by load(), resetToDefaults(), and save().
m_presets
Presets MainSettings::m_presets protected
Definition at line 77 of file mainsettings.h.
Referenced by deletePreset(), deletePresetGroup(), load(), newPreset(), save(), sortPresets(), and ~MainSettings().
m_workingPreset
Preset MainSettings::m_workingPreset protected
Definition at line 75 of file mainsettings.h.
Referenced by load(), resetToDefaults(), and save().
The documentation for this class was generated from the following files:
sdrbase/settings/mainsettings.h
sdrbase/settings/mainsettings.cpp