SDRAngel: ScopeVis Class Reference
ScopeVis Class Reference
#include <scopevis.h>
Classes
class MsgConfigureScopeVisNG
class MsgScopeVisNGAddTrace
class MsgScopeVisNGAddTrigger
class MsgScopeVisNGChangeTrace
class MsgScopeVisNGChangeTrigger
class MsgScopeVisNGFocusOnTrace
class MsgScopeVisNGFocusOnTrigger
class MsgScopeVisNGMemoryTrace
class MsgScopeVisNGMoveTrace
class MsgScopeVisNGMoveTrigger
class MsgScopeVisNGOneShot
class MsgScopeVisNGRemoveTrace
class MsgScopeVisNGRemoveTrigger
struct TraceBackBuffer
struct TraceBackDiscreteMemory
struct TraceControl
struct TraceData
struct Traces
class TriggerComparator
struct TriggerCondition
struct TriggerData
Public Member Functions
ScopeVis (GLScope *glScope=0)
virtual ~ScopeVis ()
void setLiveRate (int sampleRate)
void setLiveRateLog2Decim (int log2Decim)
void configure (uint32_t traceSize, uint32_t timeBase, uint32_t timeOfsProMill, uint32_t triggerPre, bool freeRun)
void addTrace (const TraceData &traceData)
void changeTrace (const TraceData &traceData, uint32_t traceIndex)
void removeTrace (uint32_t traceIndex)
void moveTrace (uint32_t traceIndex, bool upElseDown)
void focusOnTrace (uint32_t traceIndex)
void addTrigger (const TriggerData &triggerData)
void changeTrigger (const TriggerData &triggerData, uint32_t triggerIndex)
void removeTrigger (uint32_t triggerIndex)
void moveTrigger (uint32_t triggerIndex, bool upElseDown)
void focusOnTrigger (uint32_t triggerIndex)
void setOneShot (bool oneShot)
void setMemoryIndex (uint32_t memoryIndex)
QByteArray serializeMemory () const
bool deserializeMemory (const QByteArray &data)
void getTriggerData (TriggerData &triggerData, uint32_t triggerIndex)
void getTraceData (TraceData &traceData, uint32_t traceIndex)
const TriggerData & getTriggerData (uint32_t triggerIndex) const
const std::vector< TraceData > & getTracesData () const
uint32_t getNbTriggers () const
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool positiveOnly)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &message)
Processing of a message. Returns true if message has actually been processed.
int getTriggerLocation () const
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Static Public Attributes
static const uint32_t m_traceChunkSize = 4800
static const uint32_t m_maxNbTriggers = 10
static const uint32_t m_maxNbTraces = 10
static const uint32_t m_nbTraceMemories = 50
Private Types
enum TriggerState { TriggerUntriggered, TriggerTriggered, TriggerDelay }
typedef DoubleBufferSimple< Sample > TraceBuffer
Private Member Functions
bool nextTrigger ()
Returns true if not final.
void processTrace (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, int &triggerPointToEnd)
void processMemoryTrace ()
int processTraces (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool traceBack=false)
void updateMaxTraceDelay ()
void initTraceBuffers ()
void computeDisplayTriggerLevels ()
void updateGLScopeDisplay ()
void setSampleRate (int sampleRate)
void setTraceSize (uint32_t traceSize, bool emitSignal=false)
void setPreTriggerDelay (uint32_t preTriggerDelay, bool emitSignal=false)
Private Attributes
GLScope * m_glScope
uint32_t m_preTriggerDelay
Pre-trigger delay in number of samples.
uint32_t m_livePreTriggerDelay
Pre-trigger delay in number of samples in live mode.
std::vector< TriggerCondition * > m_triggerConditions
Chain of triggers.
uint32_t m_currentTriggerIndex
Index of current index in the chain.
uint32_t m_focusedTriggerIndex
Index of the trigger that has focus.
TriggerState m_triggerState
Current trigger state.
Traces m_traces
Displayable traces.
int m_focusedTraceIndex
Index of the trace that has focus.
uint32_t m_traceSize
Size of traces in number of samples.
uint32_t m_liveTraceSize
Size of traces in number of samples in live mode.
int m_nbSamples
Number of samples yet to process in one complex trace.
uint32_t m_timeBase
Trace display time divisor.
uint32_t m_timeOfsProMill
Start trace shift in 1/1000 trace size.
bool m_traceStart
Trace is at start point.
int m_triggerLocation
Trigger location from end point.
int m_sampleRate
Actual sample rate being used.
int m_liveSampleRate
Sample rate in live mode.
int m_liveLog2Decim
Sample rate decimation log2 in live mode.
TraceBackDiscreteMemory m_traceDiscreteMemory
Complex trace memory for triggered states TODO: vectorize when more than on input is allowed.
bool m_freeRun
True if free running (trigger globally disabled)
int m_maxTraceDelay
Maximum trace delay.
TriggerComparator m_triggerComparator
Compares sample level to trigger level.
QMutex m_mutex
Real m_projectorCache [(int) Projector::nbProjectionTypes]
bool m_triggerOneShot
True when one shot mode is active.
bool m_triggerWaitForReset
In one shot mode suspended until reset by UI.
uint32_t m_currentTraceMemoryIndex
The current index of trace in memory (0: current)
Additional Inherited Members
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 45 of file scopevis.h.
Member Typedef Documentation
TraceBuffer
typedef DoubleBufferSimple<Sample> ScopeVis::TraceBuffer private
Complex trace stuff
Definition at line 631 of file scopevis.h.
Member Enumeration Documentation
TriggerState
enum ScopeVis::TriggerState private
Trigger stuff
Enumerator
TriggerUntriggered
Trigger is not kicked off yet (or trigger list is empty)
TriggerTriggered
Trigger has been kicked off.
TriggerDelay
Trigger conditions have been kicked off but it is waiting for delay before final kick off.
Definition at line 563 of file scopevis.h.
     {
         TriggerUntriggered,
         TriggerTriggered,
         TriggerDelay,
     };
Constructor & Destructor Documentation
ScopeVis()
ScopeVis::ScopeVis (GLScope * glScope = 0)
Definition at line 43 of file scopevis.cpp.
References i, m_glScope, m_projectorCache, m_traceChunkSize, m_traceDiscreteMemory, ScopeVis::Traces::m_traces, m_traces, ScopeVis::Traces::m_tracesData, Projector::nbProjectionTypes, ScopeVis::TraceBackDiscreteMemory::resize(), and GLScope::setTraces().
                                    :
     m_glScope(glScope),
     m_preTriggerDelay(0),
     m_livePreTriggerDelay(0),
     m_currentTriggerIndex(0),
     m_focusedTriggerIndex(0),
     m_triggerState(TriggerUntriggered),
     m_focusedTraceIndex(0),
     m_traceSize(m_traceChunkSize),
     m_liveTraceSize(m_traceChunkSize),
     m_nbSamples(0),
     m_timeBase(1),
     m_timeOfsProMill(0),
     m_traceStart(true),
     m_triggerLocation(0),
     m_sampleRate(0),
     m_liveSampleRate(0),
     m_liveLog2Decim(0),
     m_traceDiscreteMemory(m_nbTraceMemories),
     m_freeRun(true),
     m_maxTraceDelay(0),
     m_triggerOneShot(false),
     m_triggerWaitForReset(false),
     m_currentTraceMemoryIndex(0)
 {
     setObjectName("ScopeVis");
     m_traceDiscreteMemory.resize(m_traceChunkSize); // arbitrary
     m_glScope->setTraces(&m_traces.m_tracesData, &m_traces.m_traces[0]);
     for (int i = 0; i < (int) Projector::nbProjectionTypes; i++) {
         m_projectorCache[i] = 0.0;
     }
 }
~ScopeVis()
ScopeVis::~ScopeVis () virtual
Definition at line 76 of file scopevis.cpp.
References m_triggerConditions.
 {
     for (std::vector<TriggerCondition*>::iterator it = m_triggerConditions.begin(); it != m_triggerConditions.end(); ++ it) {
         delete *it;
     }
 }
Member Function Documentation
addTrace()
void ScopeVis::addTrace (const TraceData & traceData)
Definition at line 135 of file scopevis.cpp.
References ScopeVis::MsgScopeVisNGAddTrace::create(), BasebandSampleSink::getInputMessageQueue(), ScopeVis::TraceData::m_amp, ScopeVis::TraceData::m_ofs, ScopeVis::TraceData::m_traceDelay, and MessageQueue::push().
Referenced by GLScopeGUI::addTrace(), GLScopeGUI::deserialize(), and GLScopeGUI::setBuddies().
 {
     qDebug() << "ScopeVis::addTrace:"
             << " m_amp: " << traceData.m_amp
             << " m_ofs: " << traceData.m_ofs
             << " m_traceDelay: " << traceData.m_traceDelay;
     Message* cmd = MsgScopeVisNGAddTrace::create(traceData);
     getInputMessageQueue()->push(cmd);
 }
addTrigger()
void ScopeVis::addTrigger (const TriggerData & triggerData)
Definition at line 179 of file scopevis.cpp.
References ScopeVis::MsgScopeVisNGAddTrigger::create(), BasebandSampleSink::getInputMessageQueue(), and MessageQueue::push().
Referenced by GLScopeGUI::addTrigger(), GLScopeGUI::deserialize(), and GLScopeGUI::setBuddies().
 {
     Message* cmd = MsgScopeVisNGAddTrigger::create(triggerData);
     getInputMessageQueue()->push(cmd);
 }
changeTrace()
void ScopeVis::changeTrace (const TraceData & traceData, uint32_t traceIndex)
Definition at line 145 of file scopevis.cpp.
References ScopeVis::MsgScopeVisNGChangeTrace::create(), BasebandSampleSink::getInputMessageQueue(), ScopeVis::TraceData::m_amp, ScopeVis::TraceData::m_ofs, ScopeVis::TraceData::m_traceDelay, and MessageQueue::push().
Referenced by GLScopeGUI::changeCurrentTrace(), GLScopeGUI::changeTrace(), and GLScopeGUI::deserialize().
 {
     qDebug() << "ScopeVis::changeTrace:"
             << " trace: " << traceIndex
             << " m_amp: " << traceData.m_amp
             << " m_ofs: " << traceData.m_ofs
             << " m_traceDelay: " << traceData.m_traceDelay;
     Message* cmd = MsgScopeVisNGChangeTrace::create(traceData, traceIndex);
     getInputMessageQueue()->push(cmd);
 }
changeTrigger()
void ScopeVis::changeTrigger (const TriggerData & triggerData, uint32_t triggerIndex)
Definition at line 185 of file scopevis.cpp.
References ScopeVis::MsgScopeVisNGChangeTrigger::create(), BasebandSampleSink::getInputMessageQueue(), and MessageQueue::push().
Referenced by GLScopeGUI::changeCurrentTrigger(), GLScopeGUI::changeTrigger(), and GLScopeGUI::deserialize().
 {
     Message* cmd = MsgScopeVisNGChangeTrigger::create(triggerData, triggerIndex);
     getInputMessageQueue()->push(cmd);
 }
computeDisplayTriggerLevels()
void ScopeVis::computeDisplayTriggerLevels () private
Calculate trigger levels on display
every time a trigger condition focus changes TBD
every time the focused trigger condition changes its projection type or level
every time a trace data changes: projection type, amp, offset
every time a trace data is added or removed
Definition at line 978 of file scopevis.cpp.
References m_focusedTriggerIndex, m_traces, ScopeVis::Traces::m_tracesData, m_triggerConditions, Projector::ProjectionMagDB, Projector::ProjectionMagLin, and Projector::ProjectionMagSq.
Referenced by handleMessage().
 {
     std::vector<TraceData>::iterator itData = m_traces.m_tracesData.begin();
     for (; itData != m_traces.m_tracesData.end(); ++itData)
     {
         if ((m_focusedTriggerIndex < m_triggerConditions.size()) && (m_triggerConditions[m_focusedTriggerIndex]->m_projector.getProjectionType() == itData->m_projectionType))
         {
             float level = m_triggerConditions[m_focusedTriggerIndex]->m_triggerData.m_triggerLevel;
             float levelPowerLin = level + 1.0f;
             float levelPowerdB = (100.0f * (level - 1.0f));
             float v;
             if ((itData->m_projectionType == Projector::ProjectionMagLin) || (itData->m_projectionType == Projector::ProjectionMagSq))
             {
                 v = (levelPowerLin - itData->m_ofs)*itData->m_amp - 1.0f;
             }
             else if (itData->m_projectionType == Projector::ProjectionMagDB)
             {
                 float ofsdB = itData->m_ofs * 100.0f;
                 v = ((levelPowerdB + 100.0f - ofsdB)*itData->m_amp)/50.0f - 1.0f;
             }
             else
             {
                 v = (level - itData->m_ofs) * itData->m_amp;
             }
             if(v > 1.0f) {
                 v = 1.0f;
             } else if (v < -1.0f) {
                 v = -1.0f;
             }
             itData->m_triggerDisplayLevel = v;
         }
         else
         {
             itData->m_triggerDisplayLevel = 2.0f;
         }
     }
 }
configure()
void ScopeVis::configure (uint32_t traceSize, uint32_t timeBase, uint32_t timeOfsProMill, uint32_t triggerPre, bool freeRun)
Definition at line 129 of file scopevis.cpp.
References ScopeVis::MsgConfigureScopeVisNG::create(), BasebandSampleSink::getInputMessageQueue(), and MessageQueue::push().
Referenced by GLScopeGUI::on_freerun_toggled(), GLScopeGUI::on_time_valueChanged(), GLScopeGUI::on_timeOfs_valueChanged(), GLScopeGUI::on_traceLen_valueChanged(), GLScopeGUI::on_trigPre_valueChanged(), and GLScopeGUI::setBuddies().
 {
     Message* cmd = MsgConfigureScopeVisNG::create(traceSize, timeBase, timeOfsProMill, triggerPre, freeRun);
     getInputMessageQueue()->push(cmd);
 }
deserializeMemory()
bool ScopeVis::deserializeMemory (const QByteArray & data) inline
Definition at line 187 of file scopevis.h.
References SimpleDeserializer::getVersion(), SimpleDeserializer::isValid(), SimpleDeserializer::readBlob(), SimpleDeserializer::readS32(), and SimpleDeserializer::readU32().
Referenced by GLScopeGUI::on_memoryLoad_clicked().
     {
         SimpleDeserializer d(data);
         if(!d.isValid()) {
             return false;
         }
         if (d.getVersion() == 1)
         {
             uint32_t traceSize, preTriggerDelay;
             int sampleRate;
             QByteArray buf;
             bool traceDiscreteMemorySuccess;
             d.readU32(1, &traceSize, m_traceChunkSize);
             d.readU32(2, &preTriggerDelay, 0);
             d.readS32(3, &sampleRate, 0);
             setSampleRate(sampleRate);
             setTraceSize(traceSize, true);
             setPreTriggerDelay(preTriggerDelay, true);
             d.readBlob(4, &buf);
             traceDiscreteMemorySuccess = m_traceDiscreteMemory.deserialize(buf);
             if (traceDiscreteMemorySuccess && (m_glScope) && (m_currentTraceMemoryIndex > 0)) {
                 processMemoryTrace();
             }
             return traceDiscreteMemorySuccess;
         }
         else
         {
             return false;
         }
     }
feed()
void ScopeVis::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool positiveOnly) virtual
Implements BasebandSampleSink.
Definition at line 221 of file scopevis.cpp.
References m_currentTraceMemoryIndex, m_freeRun, m_mutex, m_traceSize, m_triggerLocation, m_triggerState, m_triggerWaitForReset, processTrace(), TriggerTriggered, and TriggerUntriggered.
Referenced by SpectrumScopeComboVis::feed().
 {
     (void) positiveOnly;
     if (m_currentTraceMemoryIndex > 0) { // in memory mode live trace is suspended
         return;
     }
     if (!m_mutex.tryLock(0)) { // prevent conflicts with configuration process
         return;
     }
     if (m_freeRun) {
         m_triggerLocation = end - cbegin;
     }
     else if (m_triggerState == TriggerTriggered) {
         m_triggerLocation = end - cbegin;
     }
     else if (m_triggerState == TriggerUntriggered) {
         m_triggerLocation = 0;
     }
     else if (m_triggerWaitForReset) {
         m_triggerLocation = 0;
     }
     else {
         m_triggerLocation = end - cbegin;
     }
     SampleVector::const_iterator begin(cbegin);
     int triggerPointToEnd;
     while (begin < end)
     {
         if (begin + m_traceSize > end) // buffer smaller than trace size (end - bagin) < m_traceSize
         {
             triggerPointToEnd = -1;
             processTrace(begin, end, triggerPointToEnd); // use all buffer
             m_triggerLocation = triggerPointToEnd < 0 ? 0 : triggerPointToEnd; // trim negative values
             m_triggerLocation = m_triggerLocation > end - begin ? end - begin : m_triggerLocation; // trim past begin values
             begin = end; // effectively breaks out the loop
         }
         else // trace size fits in buffer
         {
             triggerPointToEnd = -1;
             processTrace(begin, begin + m_traceSize, triggerPointToEnd); // use part of buffer to fit trace size
             //m_triggerPoint = begin + m_traceSize - triggerPointToEnd;
             m_triggerLocation = end - begin + m_traceSize - triggerPointToEnd; // should always refer to end iterator
             m_triggerLocation = m_triggerLocation < 0 ? 0 : m_triggerLocation; // trim negative values
             m_triggerLocation = m_triggerLocation > end - begin ? end - begin : m_triggerLocation; // trim past begin values
             begin += m_traceSize;
         }
     }
     m_mutex.unlock();
 }
focusOnTrace()
void ScopeVis::focusOnTrace (uint32_t traceIndex)
Definition at line 173 of file scopevis.cpp.
References ScopeVis::MsgScopeVisNGFocusOnTrace::create(), BasebandSampleSink::getInputMessageQueue(), and MessageQueue::push().
Referenced by GLScopeGUI::on_trace_valueChanged(), GLScopeGUI::on_traceDown_clicked(), and GLScopeGUI::on_traceUp_clicked().
 {
     Message* cmd = MsgScopeVisNGFocusOnTrace::create(traceIndex);
     getInputMessageQueue()->push(cmd);
 }
focusOnTrigger()
void ScopeVis::focusOnTrigger (uint32_t triggerIndex)
Definition at line 203 of file scopevis.cpp.
References ScopeVis::MsgScopeVisNGFocusOnTrigger::create(), BasebandSampleSink::getInputMessageQueue(), and MessageQueue::push().
Referenced by GLScopeGUI::on_trig_valueChanged(), GLScopeGUI::on_trigDown_clicked(), and GLScopeGUI::on_trigUp_clicked().
 {
     Message* cmd = MsgScopeVisNGFocusOnTrigger::create(triggerIndex);
     getInputMessageQueue()->push(cmd);
 }
getNbTriggers()
uint32_t ScopeVis::getNbTriggers () const inline
Definition at line 241 of file scopevis.h.
Referenced by GLScopeGUI::deserialize(), and GLScopeGUI::serialize().
 { return m_triggerConditions.size(); }
getTraceData()
void ScopeVis::getTraceData (TraceData & traceData, uint32_t traceIndex) inline
Definition at line 231 of file scopevis.h.
Referenced by GLScopeGUI::on_trace_valueChanged(), GLScopeGUI::on_traceDown_clicked(), and GLScopeGUI::on_traceUp_clicked().
     {
         if (traceIndex < m_traces.m_tracesData.size())
         {
             traceData = m_traces.m_tracesData[traceIndex];
         }
     }
getTracesData()
const std::vector<TraceData>& ScopeVis::getTracesData () const inline
Definition at line 240 of file scopevis.h.
Referenced by GLScopeGUI::deserialize(), and GLScopeGUI::serialize().
 { return m_traces.m_tracesData; }
getTriggerData() [1/2]
void ScopeVis::getTriggerData (TriggerData & triggerData, uint32_t triggerIndex) inline
Definition at line 223 of file scopevis.h.
Referenced by GLScopeGUI::on_trig_valueChanged(), GLScopeGUI::on_trigDown_clicked(), GLScopeGUI::on_trigUp_clicked(), and GLScopeGUI::serialize().
     {
         if (triggerIndex < m_triggerConditions.size())
         {
             triggerData = m_triggerConditions[triggerIndex]->m_triggerData;
         }
     }
getTriggerData() [2/2]
const TriggerData& ScopeVis::getTriggerData (uint32_t triggerIndex) const inline
Definition at line 239 of file scopevis.h.
 { return m_triggerConditions[triggerIndex]->m_triggerData; }
getTriggerLocation()
int ScopeVis::getTriggerLocation () const inline
Definition at line 247 of file scopevis.h.
Referenced by SpectrumScopeComboVis::feed().
 { return m_triggerLocation; }
handleMessage()
bool ScopeVis::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 650 of file scopevis.cpp.
References ScopeVis::Traces::addTrace(), ScopeVis::Traces::changeTrace(), computeDisplayTriggerLevels(), ScopeVis::MsgConfigureScopeVisNG::getFreeRun(), Message::getIdentifier(), ScopeVis::MsgScopeVisNGMemoryTrace::getMemoryIndex(), ScopeVis::MsgScopeVisNGMoveTrigger::getMoveUp(), ScopeVis::MsgScopeVisNGMoveTrace::getMoveUp(), ScopeVis::MsgScopeVisNGOneShot::getOneShot(), DSPSignalNotification::getSampleRate(), ScopeVis::MsgConfigureScopeVisNG::getTimeBase(), ScopeVis::MsgConfigureScopeVisNG::getTimeOfsProMill(), ScopeVis::MsgScopeVisNGAddTrace::getTraceData(), ScopeVis::MsgScopeVisNGChangeTrace::getTraceData(), ScopeVis::MsgScopeVisNGChangeTrace::getTraceIndex(), ScopeVis::MsgScopeVisNGRemoveTrace::getTraceIndex(), ScopeVis::MsgScopeVisNGMoveTrace::getTraceIndex(), ScopeVis::MsgScopeVisNGFocusOnTrace::getTraceIndex(), ScopeVis::MsgConfigureScopeVisNG::getTraceSize(), ScopeVis::MsgScopeVisNGAddTrigger::getTriggerData(), ScopeVis::MsgScopeVisNGChangeTrigger::getTriggerData(), ScopeVis::MsgScopeVisNGChangeTrigger::getTriggerIndex(), ScopeVis::MsgScopeVisNGRemoveTrigger::getTriggerIndex(), ScopeVis::MsgScopeVisNGMoveTrigger::getTriggerIndex(), ScopeVis::MsgScopeVisNGFocusOnTrigger::getTriggerIndex(), ScopeVis::MsgConfigureScopeVisNG::getTriggerPre(), initTraceBuffers(), ScopeVis::Traces::isVerticalDisplayChange(), m_currentTraceMemoryIndex, m_focusedTraceIndex, m_focusedTriggerIndex, m_freeRun, m_glScope, m_livePreTriggerDelay, m_liveSampleRate, m_liveTraceSize, m_mutex, m_preTriggerDelay, m_sampleRate, m_timeBase, m_timeOfsProMill, m_traces, ScopeVis::Traces::m_tracesData, m_traceSize, m_triggerConditions, m_triggerOneShot, m_triggerWaitForReset, Message::match(), ScopeVis::Traces::moveTrace(), nextTrigger(), processMemoryTrace(), ScopeVis::Traces::removeTrace(), GLScope::setFocusedTraceIndex(), GLScope::setFocusedTriggerData(), setLiveRate(), setPreTriggerDelay(), GLScope::setTimeBase(), GLScope::setTimeOfsProMill(), setTraceSize(), updateGLScopeDisplay(), and updateMaxTraceDelay().
Referenced by SpectrumScopeComboVis::handleMessage().
 {
     if (DSPSignalNotification::match(message))
     {
         DSPSignalNotification& notif = (DSPSignalNotification&) message;
         setLiveRate(notif.getSampleRate());
         qDebug() << "ScopeVis::handleMessage: DSPSignalNotification: m_sampleRate: " << m_sampleRate;
         return true;
     }
     else if (MsgConfigureScopeVisNG::match(message))
     {
         QMutexLocker configLocker(&m_mutex);
         MsgConfigureScopeVisNG& conf = (MsgConfigureScopeVisNG&) message;
         uint32_t traceSize = conf.getTraceSize();
         uint32_t timeBase = conf.getTimeBase();
         uint32_t timeOfsProMill = conf.getTimeOfsProMill();
         uint32_t triggerPre = conf.getTriggerPre();
         bool freeRun = conf.getFreeRun();
         if (m_traceSize != traceSize)
         {
             setTraceSize(traceSize);
         }
         if (m_timeBase != timeBase)
         {
             m_timeBase = timeBase;
             if (m_glScope) {
                 m_glScope->setTimeBase(m_timeBase);
             }
         }
         if (m_timeOfsProMill != timeOfsProMill)
         {
             m_timeOfsProMill = timeOfsProMill;
             if (m_glScope) {
                 m_glScope->setTimeOfsProMill(m_timeOfsProMill);
             }
         }
         if (m_preTriggerDelay != triggerPre)
         {
             setPreTriggerDelay(triggerPre);
         }
         if (freeRun != m_freeRun)
         {
             m_freeRun = freeRun;
         }
         qDebug() << "ScopeVis::handleMessage: MsgConfigureScopeVisNG:"
                 << " m_traceSize: " << m_traceSize
                 << " m_timeOfsProMill: " << m_timeOfsProMill
                 << " m_preTriggerDelay: " << m_preTriggerDelay
                 << " m_freeRun: " << m_freeRun;
         if ((m_glScope) && (m_currentTraceMemoryIndex > 0)) {
             processMemoryTrace();
         }
         return true;
     }
     else if (MsgScopeVisNGAddTrigger::match(message))
     {
         qDebug() << "ScopeVis::handleMessage: MsgScopeVisNGAddTrigger";
         QMutexLocker configLocker(&m_mutex);
         MsgScopeVisNGAddTrigger& conf = (MsgScopeVisNGAddTrigger&) message;
         m_triggerConditions.push_back(new TriggerCondition(conf.getTriggerData()));
         m_triggerConditions.back()->initProjector();
         return true;
     }
     else if (MsgScopeVisNGChangeTrigger::match(message))
     {
         QMutexLocker configLocker(&m_mutex);
         MsgScopeVisNGChangeTrigger& conf = (MsgScopeVisNGChangeTrigger&) message;
         uint32_t triggerIndex = conf.getTriggerIndex();
         qDebug() << "ScopeVis::handleMessage: MsgScopeVisNGChangeTrigger: " << triggerIndex;
         if (triggerIndex < m_triggerConditions.size())
         {
             m_triggerConditions[triggerIndex]->setData(conf.getTriggerData());
             if (triggerIndex == m_focusedTriggerIndex)
             {
                 computeDisplayTriggerLevels();
                 m_glScope->setFocusedTriggerData(m_triggerConditions[m_focusedTriggerIndex]->m_triggerData);
                 updateGLScopeDisplay();
             }
         }
         return true;
     }
     else if (MsgScopeVisNGRemoveTrigger::match(message))
     {
         QMutexLocker configLocker(&m_mutex);
         MsgScopeVisNGRemoveTrigger& conf = (MsgScopeVisNGRemoveTrigger&) message;
         uint32_t triggerIndex = conf.getTriggerIndex();
         qDebug() << "ScopeVis::handleMessage: MsgScopeVisNGRemoveTrigger: " << triggerIndex;
         if (triggerIndex < m_triggerConditions.size())
         {
             TriggerCondition *triggerCondition = m_triggerConditions[triggerIndex];
             m_triggerConditions.erase(m_triggerConditions.begin() + triggerIndex);
             delete triggerCondition;
         }
         return true;
     }
     else if (MsgScopeVisNGMoveTrigger::match(message))
     {
         QMutexLocker configLocker(&m_mutex);
         MsgScopeVisNGMoveTrigger& conf = (MsgScopeVisNGMoveTrigger&) message;
         int triggerIndex = conf.getTriggerIndex();
         qDebug() << "ScopeVis::handleMessage: MsgScopeVisNGMoveTrigger: " << triggerIndex;
         if (!conf.getMoveUp() && (triggerIndex == 0)) {
             return true;
         }
         int nextTriggerIndex = (triggerIndex + (conf.getMoveUp() ? 1 : -1)) % m_triggerConditions.size();
         TriggerCondition *nextTrigger = m_triggerConditions[nextTriggerIndex];
         m_triggerConditions[nextTriggerIndex] = m_triggerConditions[triggerIndex];
         m_triggerConditions[triggerIndex] = nextTrigger;
         computeDisplayTriggerLevels();
         m_glScope->setFocusedTriggerData(m_triggerConditions[m_focusedTriggerIndex]->m_triggerData);
         updateGLScopeDisplay();
         return true;
     }
     else if (MsgScopeVisNGFocusOnTrigger::match(message))
     {
         MsgScopeVisNGFocusOnTrigger& conf = (MsgScopeVisNGFocusOnTrigger&) message;
         uint32_t triggerIndex = conf.getTriggerIndex();
         qDebug() << "ScopeVis::handleMessage: MsgScopeVisNGFocusOnTrigger: " << triggerIndex;
         if (triggerIndex < m_triggerConditions.size())
         {
             m_focusedTriggerIndex = triggerIndex;
             computeDisplayTriggerLevels();
             m_glScope->setFocusedTriggerData(m_triggerConditions[m_focusedTriggerIndex]->m_triggerData);
             updateGLScopeDisplay();
         }
         return true;
     }
     else if (MsgScopeVisNGAddTrace::match(message))
     {
         qDebug() << "ScopeVis::handleMessage: MsgScopeVisNGAddTrace";
         QMutexLocker configLocker(&m_mutex);
         MsgScopeVisNGAddTrace& conf = (MsgScopeVisNGAddTrace&) message;
         m_traces.addTrace(conf.getTraceData(), m_traceSize);
         initTraceBuffers();
         updateMaxTraceDelay();
         computeDisplayTriggerLevels();
         updateGLScopeDisplay();
         return true;
     }
     else if (MsgScopeVisNGChangeTrace::match(message))
     {
         QMutexLocker configLocker(&m_mutex);
         MsgScopeVisNGChangeTrace& conf = (MsgScopeVisNGChangeTrace&) message;
         bool doComputeTriggerLevelsOnDisplay = m_traces.isVerticalDisplayChange(conf.getTraceData(), conf.getTraceIndex());
         uint32_t traceIndex = conf.getTraceIndex();
         qDebug() << "ScopeVis::handleMessage: MsgScopeVisNGChangeTrace: " << traceIndex;
         m_traces.changeTrace(conf.getTraceData(), traceIndex);
         updateMaxTraceDelay();
         if (doComputeTriggerLevelsOnDisplay) computeDisplayTriggerLevels();
         updateGLScopeDisplay();
         return true;
     }
     else if (MsgScopeVisNGRemoveTrace::match(message))
     {
         QMutexLocker configLocker(&m_mutex);
         MsgScopeVisNGRemoveTrace& conf = (MsgScopeVisNGRemoveTrace&) message;
         uint32_t traceIndex = conf.getTraceIndex();
         qDebug() << "ScopeVis::handleMessage: MsgScopeVisNGRemoveTrace: " << traceIndex;
         m_traces.removeTrace(traceIndex);
         updateMaxTraceDelay();
         computeDisplayTriggerLevels();
         updateGLScopeDisplay();
         return true;
     }
     else if (MsgScopeVisNGMoveTrace::match(message))
     {
         QMutexLocker configLocker(&m_mutex);
         MsgScopeVisNGMoveTrace& conf = (MsgScopeVisNGMoveTrace&) message;
         uint32_t traceIndex = conf.getTraceIndex();
         qDebug() << "ScopeVis::handleMessage: MsgScopeVisNGMoveTrace: " << traceIndex;
         m_traces.moveTrace(traceIndex, conf.getMoveUp());
         //updateMaxTraceDelay();
         computeDisplayTriggerLevels();
         updateGLScopeDisplay();
         return true;
     }
     else if (MsgScopeVisNGFocusOnTrace::match(message))
     {
         MsgScopeVisNGFocusOnTrace& conf = (MsgScopeVisNGFocusOnTrace&) message;
         uint32_t traceIndex = conf.getTraceIndex();
         qDebug() << "ScopeVis::handleMessage: MsgScopeVisNGFocusOnTrace: " << traceIndex;
         if (traceIndex < m_traces.m_tracesData.size())
         {
             m_focusedTraceIndex = traceIndex;
             computeDisplayTriggerLevels();
             m_glScope->setFocusedTraceIndex(m_focusedTraceIndex);
             updateGLScopeDisplay();
         }
         return true;
     }
     else if (MsgScopeVisNGOneShot::match(message))
     {
         qDebug() << "ScopeVis::handleMessage: MsgScopeVisNGOneShot";
         MsgScopeVisNGOneShot& conf = (MsgScopeVisNGOneShot&) message;
         bool oneShot = conf.getOneShot();
         m_triggerOneShot = oneShot;
         if (m_triggerWaitForReset && !oneShot) m_triggerWaitForReset = false;
         return true;
     }
     else if (MsgScopeVisNGMemoryTrace::match(message))
     {
         MsgScopeVisNGMemoryTrace& conf = (MsgScopeVisNGMemoryTrace&) message;
         uint32_t memoryIndex = conf.getMemoryIndex();
         qDebug() << "ScopeVis::handleMessage: MsgScopeVisNGMemoryTrace: " << memoryIndex;
         if (memoryIndex != m_currentTraceMemoryIndex)
         {
             // transition from live mode
             if (m_currentTraceMemoryIndex == 0)
             {
                 m_liveTraceSize = m_traceSize;
                 m_livePreTriggerDelay = m_preTriggerDelay;
             }
             m_currentTraceMemoryIndex = memoryIndex;
             // transition to live mode
             if (m_currentTraceMemoryIndex == 0)
             {
                 setLiveRate(m_liveSampleRate); // reset to live rate
                 setTraceSize(m_liveTraceSize, true); // reset to live trace size
                 setPreTriggerDelay(m_livePreTriggerDelay, true); // reset to live pre-trigger delay
             }
             else
             {
                 processMemoryTrace();
             }
         }
         return true;
     }
     else
     {
         qDebug() << "ScopeVis::handleMessage" << message.getIdentifier() << " not handled";
         return false;
     }
 }
initTraceBuffers()
void ScopeVis::initTraceBuffers () private
Initialize trace buffers
Definition at line 959 of file scopevis.cpp.
References i, m_timeOfsProMill, ScopeVis::Traces::m_traces, m_traces, and m_traceSize.
Referenced by handleMessage(), processTrace(), and setTraceSize().
 {
     int shift = (m_timeOfsProMill / 1000.0) * m_traceSize;
     std::vector<float *>::iterator it0 = m_traces.m_traces[0].begin();
     std::vector<float *>::iterator it1 = m_traces.m_traces[1].begin();
     for (; it0 != m_traces.m_traces[0].end(); ++it0, ++it1)
     {
         for (unsigned int i = 0; i < m_traceSize; i++)
         {
             (*it0)[2*i] = (i - shift); // display x
             (*it0)[2*i + 1] = 0.0f;    // display y
             (*it1)[2*i] = (i - shift); // display x
             (*it1)[2*i + 1] = 0.0f;    // display y
         }
     }
 }
moveTrace()
void ScopeVis::moveTrace (uint32_t traceIndex, bool upElseDown)
Definition at line 164 of file scopevis.cpp.
References ScopeVis::MsgScopeVisNGMoveTrace::create(), BasebandSampleSink::getInputMessageQueue(), and MessageQueue::push().
Referenced by GLScopeGUI::on_traceDown_clicked(), and GLScopeGUI::on_traceUp_clicked().
 {
     qDebug() << "ScopeVis::moveTrace:"
             << " trace: " << traceIndex
             << " up: " << upElseDown;
     Message* cmd = MsgScopeVisNGMoveTrace::create(traceIndex, upElseDown);
     getInputMessageQueue()->push(cmd);
 }
moveTrigger()
void ScopeVis::moveTrigger (uint32_t triggerIndex, bool upElseDown)
Definition at line 197 of file scopevis.cpp.
References ScopeVis::MsgScopeVisNGMoveTrigger::create(), BasebandSampleSink::getInputMessageQueue(), and MessageQueue::push().
Referenced by GLScopeGUI::on_trigDown_clicked(), and GLScopeGUI::on_trigUp_clicked().
 {
     Message* cmd = MsgScopeVisNGMoveTrigger::create(triggerIndex, upElseDown);
     getInputMessageQueue()->push(cmd);
 }
nextTrigger()
bool ScopeVis::nextTrigger () private
Returns true if not final.
Moves on to the next trigger if any or increments trigger count if in repeat mode
If not final it returns true
If final i.e. signal is actually triggerd it returns false
Definition at line 455 of file scopevis.cpp.
References m_currentTriggerIndex, m_triggerConditions, ScopeVis::TriggerCondition::m_triggerCounter, ScopeVis::TriggerCondition::m_triggerData, and ScopeVis::TriggerData::m_triggerRepeat.
Referenced by handleMessage(), and processTrace().
 {
     TriggerCondition *triggerCondition = m_triggerConditions[m_currentTriggerIndex]; // current trigger condition
     if (triggerCondition->m_triggerData.m_triggerRepeat > 0)
     {
         if (triggerCondition->m_triggerCounter < triggerCondition->m_triggerData.m_triggerRepeat)
         {
             triggerCondition->m_triggerCounter++;
             return true; // not final keep going
         }
         else
         {
             triggerCondition->m_triggerCounter = 0; // reset for next time
         }
     }
     if (m_triggerConditions.size() == 0)
     {
         m_currentTriggerIndex = 0;
         return false; // final
     }
     else if (m_currentTriggerIndex < m_triggerConditions.size() - 1) // check if next trigger is available
     {
         m_currentTriggerIndex++;
         return true; // not final keep going
     }
     else
     {
         // now this is really finished
         m_currentTriggerIndex = 0;
         return false; // final
     }
 }
processMemoryTrace()
void ScopeVis::processMemoryTrace () private
process a trace in memory at current trace index in memory
Definition at line 279 of file scopevis.cpp.
References ScopeVis::TraceBackDiscreteMemory::at(), ScopeVis::TraceBackDiscreteMemory::currentIndex(), m_currentTraceMemoryIndex, ScopeVis::TraceBackBuffer::m_endPoint, m_maxTraceDelay, m_nbSamples, m_nbTraceMemories, m_traceDiscreteMemory, m_traceSize, and processTraces().
Referenced by handleMessage(), and updateGLScopeDisplay().
 {
     if ((m_currentTraceMemoryIndex > 0) && (m_currentTraceMemoryIndex < m_nbTraceMemories))
     {
         int traceMemoryIndex = m_traceDiscreteMemory.currentIndex() - m_currentTraceMemoryIndex; // actual index in memory bank
         if (traceMemoryIndex < 0) {
             traceMemoryIndex += m_nbTraceMemories;
         }
         SampleVector::const_iterator mend = m_traceDiscreteMemory.at(traceMemoryIndex).m_endPoint;
         SampleVector::const_iterator mbegin = mend - m_traceSize;
         SampleVector::const_iterator mbegin_tb = mbegin - m_maxTraceDelay;
         m_nbSamples = m_traceSize + m_maxTraceDelay;
         processTraces(mbegin_tb, mbegin, true); // traceback
         processTraces(mbegin, mend, false);
     }
 }
processTrace()
void ScopeVis::processTrace (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, int & triggerPointToEnd) private
Process a sample trace which length is at most the trace length (m_traceSize)
Definition at line 299 of file scopevis.cpp.
References ScopeVis::TraceBackBuffer::current(), ScopeVis::TraceBackDiscreteMemory::current(), initTraceBuffers(), m_currentTriggerIndex, ScopeVis::TraceBackBuffer::m_endPoint, m_freeRun, m_maxTraceDelay, m_nbSamples, m_preTriggerDelay, m_sampleRate, m_traceDiscreteMemory, m_traceSize, m_traceStart, m_triggerComparator, m_triggerConditions, ScopeVis::TriggerCondition::m_triggerData, ScopeVis::TriggerData::m_triggerDelay, ScopeVis::TriggerCondition::m_triggerDelayCount, m_triggerOneShot, m_triggerState, m_triggerWaitForReset, nextTrigger(), processTraces(), ScopeVis::TriggerComparator::reset(), ScopeVis::TraceBackDiscreteMemory::store(), TriggerDelay, ScopeVis::TriggerComparator::triggered(), TriggerTriggered, TriggerUntriggered, and ScopeVis::TraceBackBuffer::write().
Referenced by feed().
 {
     SampleVector::const_iterator begin(cbegin);
     // memory storage
     m_traceDiscreteMemory.current().write(cbegin, end);
     // Removed in 4.2.4 may cause trigger bug
     // if (m_traceDiscreteMemory.current().absoluteFill() < m_traceSize)
     // {
     //     return; // not enough samples in memory
     // }
     // trigger process
     if ((m_freeRun) || (m_triggerConditions.size() == 0)) // immediate re-trigger
     {
         if (m_triggerState == TriggerUntriggered)
         {
             m_traceStart = true; // start trace processing
             m_nbSamples = m_traceSize + m_maxTraceDelay;
             m_triggerState = TriggerTriggered;
         }
     }
     else if ((m_triggerState == TriggerUntriggered) || (m_triggerState == TriggerDelay)) // look for trigger or past trigger in delay mode
     {
         TriggerCondition* triggerCondition = m_triggerConditions[m_currentTriggerIndex]; // current trigger condition
         while (begin < end)
         {
             if (m_triggerState == TriggerDelay) // delayed trigger
             {
                 if (triggerCondition->m_triggerDelayCount > 0) // skip samples during delay period
                 {
                     begin += triggerCondition->m_triggerDelayCount;
                     triggerCondition->m_triggerDelayCount = 0;
                     continue;
                 }
                 else // process trigger
                 {
                     if (nextTrigger()) // move to next trigger and keep going
                     {
                         m_triggerComparator.reset();
                         m_triggerState = TriggerUntriggered;
                         ++begin;
                         continue;
                     }
                     else // this was the last trigger then start trace
                     {
                         m_traceStart = true; // start trace processing
                         m_nbSamples = m_traceSize + m_maxTraceDelay;
                         m_triggerComparator.reset();
                         m_triggerState = TriggerTriggered;
                         triggerPointToEnd = end - begin;
                         break;
                     }
                 }
             }
             if (m_triggerComparator.triggered(*begin, *triggerCondition)) // matched the current trigger
             {
                 if (triggerCondition->m_triggerData.m_triggerDelay > 0)
                 {
                     triggerCondition->m_triggerDelayCount = triggerCondition->m_triggerData.m_triggerDelay; // initialize delayed samples counter
                     m_triggerState = TriggerDelay;
                     ++begin;
                     continue;
                 }
                 if (nextTrigger()) // move to next trigger and keep going
                 {
                     m_triggerComparator.reset();
                     m_triggerState = TriggerUntriggered;
                 }
                 else // this was the last trigger then start trace
                 {
                     m_traceStart = true; // start of trace processing
                     m_nbSamples = m_traceSize + m_maxTraceDelay;
                     m_triggerComparator.reset();
                     m_triggerState = TriggerTriggered;
                     triggerPointToEnd = end - begin;
                     break;
                 }
             }
             ++begin;
         } // look for trigger
     } // untriggered or delayed
     // trace process
     if (m_triggerState == TriggerTriggered)
     {
         int remainder;
         int count = end - begin; // number of samples in traceback buffer past the current point
         SampleVector::iterator mend = m_traceDiscreteMemory.current().current();
         SampleVector::iterator mbegin = mend - count;
         if (m_traceStart) // start of trace processing
         {
             // if trace time is 1s or more the display is progressive so we have to clear it first
             float traceTime = ((float) m_traceSize) / m_sampleRate;
             if (traceTime >= 1.0f) {
                 initTraceBuffers();
             }
             // process until begin point
             if (m_maxTraceDelay > 0) { // trace back
                 processTraces(mbegin - m_preTriggerDelay - m_maxTraceDelay, mbegin - m_preTriggerDelay, true);
             }
             if (m_preTriggerDelay > 0) { // pre-trigger
                 processTraces(mbegin - m_preTriggerDelay, mbegin);
             }
             // process the rest of the trace
             remainder = processTraces(mbegin, mend);
             m_traceStart = false;
         }
         else // process the current trace
         {
             remainder = processTraces(mbegin, mend);
         }
         if (remainder >= 0) // finished
         {
             mbegin = mend - remainder;
             m_traceDiscreteMemory.current().m_endPoint = mbegin;
             m_traceDiscreteMemory.store(m_preTriggerDelay+remainder); // next memory trace.
             m_triggerState = TriggerUntriggered;
             m_triggerWaitForReset = m_triggerOneShot;
             //if (m_glScope) m_glScope->incrementTraceCounter();
             // process remainder recursively
             if (remainder != 0)
             {
                 int mTriggerPointToEnd = -1;
                 processTrace(mbegin, mend, mTriggerPointToEnd);
                 if (mTriggerPointToEnd >= 0) {
                     triggerPointToEnd = mTriggerPointToEnd;
                 }
                 //qDebug("ScopeVis::processTrace: process remainder recursively (%d %d)", mpoint, mTriggerPoint);
             }
         }
     }
 }
processTraces()
int ScopeVis::processTraces (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool traceBack = false) private
Process traces from complex trace memory buffer.
if finished it returns the number of unprocessed samples left in the buffer
if not finished it returns -1
Definition at line 490 of file scopevis.cpp.
References ScopeVis::Traces::currentBufferIndex(), GLScope::getProcessingTraceIndex(), m_glScope, m_nbSamples, m_sampleRate, m_timeBase, m_timeOfsProMill, ScopeVis::Traces::m_traces, m_traces, ScopeVis::Traces::m_tracesControl, ScopeVis::Traces::m_tracesData, m_traceSize, GLScope::newTraces(), Projector::ProjectionMagDB, Projector::ProjectionMagLin, Projector::ProjectionMagSq, SDR_RX_SCALEF, and ScopeVis::Traces::switchBuffer().
Referenced by processMemoryTrace(), and processTrace().
 {
     SampleVector::const_iterator begin(cbegin);
     uint32_t shift = (m_timeOfsProMill / 1000.0) * m_traceSize;
     uint32_t length = m_traceSize / m_timeBase;
     while ((begin < end) && (m_nbSamples > 0))
     {
         std::vector<TraceControl*>::iterator itCtl = m_traces.m_tracesControl.begin();
         std::vector<TraceData>::iterator itData = m_traces.m_tracesData.begin();
         std::vector<float *>::iterator itTrace = m_traces.m_traces[m_traces.currentBufferIndex()].begin();
         for (; itCtl != m_traces.m_tracesControl.end(); ++itCtl, ++itData, ++itTrace)
         {
             if (traceBack && ((end - begin) > itData->m_traceDelay)) { // before start of trace
                 continue;
             }
             Projector::ProjectionType projectionType = itData->m_projectionType;
             if ((*itCtl)->m_traceCount[m_traces.currentBufferIndex()] < m_traceSize)
             {
                 uint32_t& traceCount = (*itCtl)->m_traceCount[m_traces.currentBufferIndex()]; // reference for code clarity
                 float v;
                 if (projectionType == Projector::ProjectionMagLin)
                 {
                     v = ((*itCtl)->m_projector.run(*begin) - itData->m_ofs)*itData->m_amp - 1.0f;
                 }
                 else if (projectionType == Projector::ProjectionMagSq)
                 {
                     Real magsq = (*itCtl)->m_projector.run(*begin);
                     v = (magsq - itData->m_ofs)*itData->m_amp - 1.0f;
                     if ((traceCount >= shift) && (traceCount < shift+length)) // power display overlay values construction
                     {
                         if (traceCount == shift)
{
                             (*itCtl)->m_maxPow = 0.0f;
                             (*itCtl)->m_sumPow = 0.0f;
                             (*itCtl)->m_nbPow = 1;
                         }
                         if (magsq > 0.0f)
{
                             if (magsq > (*itCtl)->m_maxPow)
{
                                 (*itCtl)->m_maxPow = magsq;
                             }
                             (*itCtl)->m_sumPow += magsq;
                             (*itCtl)->m_nbPow++;
                         }
                     }
                     if ((m_nbSamples == 1) && ((*itCtl)->m_nbPow > 0)) // on last sample create power display overlay
                     {
                         double avgPow = (*itCtl)->m_sumPow / (*itCtl)->m_nbPow;
                         itData->m_textOverlay = QString("%1  %2").arg((*itCtl)->m_maxPow, 0, 'e', 2).arg(avgPow, 0, 'e', 2);
                         (*itCtl)->m_nbPow = 0;
                     }
                 }
                 else if (projectionType == Projector::ProjectionMagDB)
                 {
                     Real re = begin->m_real / SDR_RX_SCALEF;
                     Real im = begin->m_imag / SDR_RX_SCALEF;
                     double magsq = re*re + im*im;
                     float pdB = log10f(magsq) * 10.0f;
                     float p = pdB - (100.0f * itData->m_ofs);
                     v = ((p/50.0f) + 2.0f)*itData->m_amp - 1.0f;
                     if ((traceCount >= shift) && (traceCount < shift+length)) // power display overlay values construction
                     {
                         if (traceCount == shift)
{
                             (*itCtl)->m_maxPow = 0.0f;
                             (*itCtl)->m_sumPow = 0.0f;
                             (*itCtl)->m_nbPow = 1;
                         }
                         if (magsq > 0.0f)
{
                             if (magsq > (*itCtl)->m_maxPow)
{
                                 (*itCtl)->m_maxPow = magsq;
                             }
                             (*itCtl)->m_sumPow += magsq;
                             (*itCtl)->m_nbPow++;
                         }
                     }
                     if ((m_nbSamples == 1) && ((*itCtl)->m_nbPow > 0)) // on last sample create power display overlay
                     {
                         double avgPow = log10f((*itCtl)->m_sumPow / (*itCtl)->m_nbPow)*10.0;
                         double peakPow = log10f((*itCtl)->m_maxPow)*10.0;
                         double peakToAvgPow = peakPow - avgPow;
                         itData->m_textOverlay = QString("%1  %2  %3").arg(peakPow, 0, 'f', 1).arg(avgPow, 0, 'f', 1).arg(peakToAvgPow, 4, 'f', 1, ' ');
                         (*itCtl)->m_nbPow = 0;
                     }
                 }
                 else
                 {
                     v = ((*itCtl)->m_projector.run(*begin) - itData->m_ofs) * itData->m_amp;
                 }
                 if(v > 1.0f) {
                     v = 1.0f;
                 } else if (v < -1.0f) {
                     v = -1.0f;
                 }
                 (*itTrace)[2*traceCount]
                            = traceCount - shift;   // display x
                 (*itTrace)[2*traceCount + 1] = v;  // display y
                 traceCount++;
             }
         }
         ++begin;
         m_nbSamples--;
     }
     float traceTime = ((float) m_traceSize) / m_sampleRate;
     if (traceTime >= 1.0f) { // display continuously if trace time is 1 second or more
         m_glScope->newTraces(m_traces.m_traces, m_traces.currentBufferIndex());
     }
     if (m_nbSamples == 0) // finished
     {
         // display only at trace end if trace time is less than 1 second
         if (traceTime < 1.0f)
         {
             if (m_glScope->getProcessingTraceIndex().load() < 0) {
                 m_glScope->newTraces(m_traces.m_traces, m_traces.currentBufferIndex());
             }
         }
         // switch to next buffer only if it is not being processed by the scope
         if (m_glScope->getProcessingTraceIndex().load() != (((int) m_traces.currentBufferIndex() + 1) % 2)) {
             m_traces.switchBuffer();
         }
         return end - begin; // return remainder count
     }
     else
     {
         return -1; // mark not finished
     }
 }
removeTrace()
void ScopeVis::removeTrace (uint32_t traceIndex)
Definition at line 156 of file scopevis.cpp.
References ScopeVis::MsgScopeVisNGRemoveTrace::create(), BasebandSampleSink::getInputMessageQueue(), and MessageQueue::push().
Referenced by GLScopeGUI::deserialize(), and GLScopeGUI::on_traceDel_clicked().
 {
     qDebug() << "ScopeVis::removeTrace:"
             << " trace: " << traceIndex;
     Message* cmd = MsgScopeVisNGRemoveTrace::create(traceIndex);
     getInputMessageQueue()->push(cmd);
 }
removeTrigger()
void ScopeVis::removeTrigger (uint32_t triggerIndex)
Definition at line 191 of file scopevis.cpp.
References ScopeVis::MsgScopeVisNGRemoveTrigger::create(), BasebandSampleSink::getInputMessageQueue(), and MessageQueue::push().
Referenced by GLScopeGUI::deserialize(), and GLScopeGUI::on_trigDel_clicked().
 {
     Message* cmd = MsgScopeVisNGRemoveTrigger::create(triggerIndex);
     getInputMessageQueue()->push(cmd);
 }
serializeMemory()
QByteArray ScopeVis::serializeMemory () const inline
Definition at line 174 of file scopevis.h.
References SimpleSerializer::final(), SimpleSerializer::writeBlob(), SimpleSerializer::writeS32(), and SimpleSerializer::writeU32().
Referenced by GLScopeGUI::on_memorySave_clicked().
     {
         SimpleSerializer s(1);
         s.writeU32(1, m_traceSize);
         s.writeU32(2, m_preTriggerDelay);
         s.writeS32(3, m_sampleRate);
         QByteArray buffer = m_traceDiscreteMemory.serialize();
         s.writeBlob(4, buffer);
         return s.final();
     }
setLiveRate()
void ScopeVis::setLiveRate (int sampleRate)
Definition at line 83 of file scopevis.cpp.
References m_currentTraceMemoryIndex, m_liveLog2Decim, m_liveSampleRate, and setSampleRate().
Referenced by ATVDemodGUI::handleMessage(), handleMessage(), setLiveRateLog2Decim(), and ChannelAnalyzerGUI::setNewFinalRate().
 {
     m_liveSampleRate = sampleRate;
     if (m_currentTraceMemoryIndex == 0) { // update only in live mode
         setSampleRate(m_liveSampleRate/(1<<m_liveLog2Decim));
     }
 }
setLiveRateLog2Decim()
void ScopeVis::setLiveRateLog2Decim (int log2Decim)
Definition at line 92 of file scopevis.cpp.
References m_liveLog2Decim, m_liveSampleRate, and setLiveRate().
Referenced by ChannelAnalyzerGUI::applySettings().
 {
     m_liveLog2Decim = log2Decim;
     setLiveRate(m_liveSampleRate);
 }
setMemoryIndex()
void ScopeVis::setMemoryIndex (uint32_t memoryIndex)
Definition at line 215 of file scopevis.cpp.
References ScopeVis::MsgScopeVisNGMemoryTrace::create(), BasebandSampleSink::getInputMessageQueue(), and MessageQueue::push().
Referenced by GLScopeGUI::on_mem_valueChanged().
 {
     Message* cmd = MsgScopeVisNGMemoryTrace::create(memoryIndex);
     getInputMessageQueue()->push(cmd);
 }
setOneShot()
void ScopeVis::setOneShot (bool oneShot)
Definition at line 209 of file scopevis.cpp.
References ScopeVis::MsgScopeVisNGOneShot::create(), BasebandSampleSink::getInputMessageQueue(), and MessageQueue::push().
Referenced by GLScopeGUI::on_trigOneShot_toggled().
 {
     Message* cmd = MsgScopeVisNGOneShot::create(oneShot);
     getInputMessageQueue()->push(cmd);
 }
setPreTriggerDelay()
void ScopeVis::setPreTriggerDelay (uint32_t preTriggerDelay, bool emitSignal = false) private
Set the pre trigger delay
Definition at line 120 of file scopevis.cpp.
References m_glScope, m_preTriggerDelay, and GLScope::setTriggerPre().
Referenced by handleMessage().
 {
     m_preTriggerDelay = preTriggerDelay;
     if (m_glScope) {
         m_glScope->setTriggerPre(m_preTriggerDelay, emitSignal);
     }
 }
setSampleRate()
void ScopeVis::setSampleRate (int sampleRate) private
Set the actual sample rate
Definition at line 98 of file scopevis.cpp.
References m_glScope, m_sampleRate, and GLScope::setSampleRate().
Referenced by setLiveRate().
 {
     qDebug("ScopeVis::setSampleRate: %d S/s", sampleRate);
     m_sampleRate = sampleRate;
     if (m_glScope) {
         m_glScope->setSampleRate(m_sampleRate);
     }
 }
setTraceSize()
void ScopeVis::setTraceSize (uint32_t traceSize, bool emitSignal = false) private
Set the traces size
Definition at line 108 of file scopevis.cpp.
References initTraceBuffers(), m_glScope, m_traceDiscreteMemory, m_traces, m_traceSize, ScopeVis::TraceBackDiscreteMemory::resize(), ScopeVis::Traces::resize(), and GLScope::setTraceSize().
Referenced by handleMessage().
 {
     m_traceSize = traceSize;
     m_traces.resize(m_traceSize);
     m_traceDiscreteMemory.resize(m_traceSize);
     initTraceBuffers();
     if (m_glScope) {
         m_glScope->setTraceSize(m_traceSize, emitSignal);
     }
 }
start()
void ScopeVis::start () virtual
Implements BasebandSampleSink.
Definition at line 642 of file scopevis.cpp.
Referenced by SpectrumScopeComboVis::start().
 {
 }
stop()
void ScopeVis::stop () virtual
Implements BasebandSampleSink.
Definition at line 646 of file scopevis.cpp.
Referenced by SpectrumScopeComboVis::stop().
 {
 }
updateGLScopeDisplay()
void ScopeVis::updateGLScopeDisplay () private
Update glScope display
Live trace: call glScipe update method
Trace in memory: call process memory trace
Definition at line 1020 of file scopevis.cpp.
References m_currentTraceMemoryIndex, m_glScope, processMemoryTrace(), GLScope::setConfigChanged(), and GLScope::updateDisplay().
Referenced by handleMessage().
 {
     if (m_currentTraceMemoryIndex > 0) {
         m_glScope->setConfigChanged();
         processMemoryTrace();
     } else {
         m_glScope->updateDisplay();
     }
 }
updateMaxTraceDelay()
void ScopeVis::updateMaxTraceDelay () private
Get maximum trace delay
Definition at line 912 of file scopevis.cpp.
References m_maxTraceDelay, m_projectorCache, m_traces, ScopeVis::Traces::m_tracesControl, ScopeVis::Traces::m_tracesData, Projector::nbProjectionTypes, and Projector::ProjectionReal.
Referenced by handleMessage().
 {
     int maxTraceDelay = 0;
     bool allocateCache = false;
     uint32_t projectorCounts[(int) Projector::nbProjectionTypes];
     memset(projectorCounts, 0, ((int) Projector::nbProjectionTypes)*sizeof(uint32_t));
     std::vector<TraceData>::iterator itData = m_traces.m_tracesData.begin();
     std::vector<TraceControl*>::iterator itCtrl = m_traces.m_tracesControl.begin();
     for (; itData != m_traces.m_tracesData.end(); ++itData, ++itCtrl)
     {
         if (itData->m_traceDelay > maxTraceDelay)
         {
             maxTraceDelay = itData->m_traceDelay;
         }
         if (itData->m_projectionType < 0) {
             itData->m_projectionType = Projector::ProjectionReal;
         }
         if (projectorCounts[(int) itData->m_projectionType] > 0)
         {
             allocateCache = true;
             (*itCtrl)->m_projector.setCacheMaster(false);
         }
         else
         {
             (*itCtrl)->m_projector.setCacheMaster(true);
         }
         projectorCounts[(int) itData->m_projectionType]++;
     }
     itCtrl = m_traces.m_tracesControl.begin();
     for (; itCtrl != m_traces.m_tracesControl.end(); ++itCtrl)
     {
         if (allocateCache) {
             (*itCtrl)->m_projector.setCache(m_projectorCache);
         } else {
             (*itCtrl)->m_projector.setCache(0);
         }
     }
     m_maxTraceDelay = maxTraceDelay;
 }
Member Data Documentation
m_currentTraceMemoryIndex
uint32_t ScopeVis::m_currentTraceMemoryIndex private
The current index of trace in memory (0: current)
Definition at line 1148 of file scopevis.h.
Referenced by feed(), handleMessage(), processMemoryTrace(), setLiveRate(), and updateGLScopeDisplay().
m_currentTriggerIndex
uint32_t ScopeVis::m_currentTriggerIndex private
Index of current index in the chain.
Definition at line 1125 of file scopevis.h.
Referenced by nextTrigger(), and processTrace().
m_focusedTraceIndex
int ScopeVis::m_focusedTraceIndex private
Index of the trace that has focus.
Definition at line 1129 of file scopevis.h.
Referenced by handleMessage().
m_focusedTriggerIndex
uint32_t ScopeVis::m_focusedTriggerIndex private
Index of the trigger that has focus.
Definition at line 1126 of file scopevis.h.
Referenced by computeDisplayTriggerLevels(), and handleMessage().
m_freeRun
bool ScopeVis::m_freeRun private
True if free running (trigger globally disabled)
Definition at line 1141 of file scopevis.h.
Referenced by feed(), handleMessage(), and processTrace().
m_glScope
GLScope* ScopeVis::m_glScope private
Definition at line 1121 of file scopevis.h.
Referenced by handleMessage(), processTraces(), ScopeVis(), setPreTriggerDelay(), setSampleRate(), setTraceSize(), and updateGLScopeDisplay().
m_liveLog2Decim
int ScopeVis::m_liveLog2Decim private
Sample rate decimation log2 in live mode.
Definition at line 1139 of file scopevis.h.
Referenced by setLiveRate(), and setLiveRateLog2Decim().
m_livePreTriggerDelay
uint32_t ScopeVis::m_livePreTriggerDelay private
Pre-trigger delay in number of samples in live mode.
Definition at line 1123 of file scopevis.h.
Referenced by handleMessage().
m_liveSampleRate
int ScopeVis::m_liveSampleRate private
Sample rate in live mode.
Definition at line 1138 of file scopevis.h.
Referenced by handleMessage(), setLiveRate(), and setLiveRateLog2Decim().
m_liveTraceSize
uint32_t ScopeVis::m_liveTraceSize private
Size of traces in number of samples in live mode.
Definition at line 1131 of file scopevis.h.
Referenced by handleMessage().
m_maxNbTraces
const uint32_t ScopeVis::m_maxNbTraces = 10 static
Definition at line 152 of file scopevis.h.
m_maxNbTriggers
const uint32_t ScopeVis::m_maxNbTriggers = 10 static
Definition at line 151 of file scopevis.h.
m_maxTraceDelay
int ScopeVis::m_maxTraceDelay private
Maximum trace delay.
Definition at line 1142 of file scopevis.h.
Referenced by processMemoryTrace(), processTrace(), and updateMaxTraceDelay().
m_mutex
QMutex ScopeVis::m_mutex private
Definition at line 1144 of file scopevis.h.
Referenced by feed(), and handleMessage().
m_nbSamples
int ScopeVis::m_nbSamples private
Number of samples yet to process in one complex trace.
Definition at line 1132 of file scopevis.h.
Referenced by processMemoryTrace(), processTrace(), and processTraces().
m_nbTraceMemories
const uint32_t ScopeVis::m_nbTraceMemories = 50 static
Definition at line 153 of file scopevis.h.
Referenced by GLScopeGUI::GLScopeGUI(), and processMemoryTrace().
m_preTriggerDelay
uint32_t ScopeVis::m_preTriggerDelay private
Pre-trigger delay in number of samples.
Definition at line 1122 of file scopevis.h.
Referenced by handleMessage(), processTrace(), and setPreTriggerDelay().
m_projectorCache
Real ScopeVis::m_projectorCache[(int) Projector::nbProjectionTypes] private
Definition at line 1145 of file scopevis.h.
Referenced by ScopeVis(), and updateMaxTraceDelay().
m_sampleRate
int ScopeVis::m_sampleRate private
Actual sample rate being used.
Definition at line 1137 of file scopevis.h.
Referenced by handleMessage(), processTrace(), processTraces(), and setSampleRate().
m_timeBase
uint32_t ScopeVis::m_timeBase private
Trace display time divisor.
Definition at line 1133 of file scopevis.h.
Referenced by handleMessage(), and processTraces().
m_timeOfsProMill
uint32_t ScopeVis::m_timeOfsProMill private
Start trace shift in 1/1000 trace size.
Definition at line 1134 of file scopevis.h.
Referenced by handleMessage(), initTraceBuffers(), and processTraces().
m_traceChunkSize
const uint ScopeVis::m_traceChunkSize = 4800 static
Definition at line 150 of file scopevis.h.
Referenced by GLScopeGUI::fillTriggerData(), GLScopeGUI::GLScopeGUI(), GLScopeGUI::on_freerun_toggled(), GLScopeGUI::on_scope_traceSizeChanged(), GLScopeGUI::on_time_valueChanged(), GLScopeGUI::on_timeOfs_valueChanged(), GLScopeGUI::on_traceLen_valueChanged(), GLScopeGUI::on_trigPre_valueChanged(), ScopeVis(), GLScopeGUI::setBuddies(), GLScopeGUI::setTraceLenDisplay(), and GLScopeGUI::setTrigDelayDisplay().
m_traceDiscreteMemory
TraceBackDiscreteMemory ScopeVis::m_traceDiscreteMemory private
Complex trace memory for triggered states TODO: vectorize when more than on input is allowed.
Definition at line 1140 of file scopevis.h.
Referenced by processMemoryTrace(), processTrace(), ScopeVis(), and setTraceSize().
m_traces
Traces ScopeVis::m_traces private
Displayable traces.
Definition at line 1128 of file scopevis.h.
Referenced by computeDisplayTriggerLevels(), handleMessage(), initTraceBuffers(), processTraces(), ScopeVis(), setTraceSize(), and updateMaxTraceDelay().
m_traceSize
uint32_t ScopeVis::m_traceSize private
Size of traces in number of samples.
Definition at line 1130 of file scopevis.h.
Referenced by feed(), handleMessage(), initTraceBuffers(), processMemoryTrace(), processTrace(), processTraces(), and setTraceSize().
m_traceStart
bool ScopeVis::m_traceStart private
Trace is at start point.
Definition at line 1135 of file scopevis.h.
Referenced by processTrace().
m_triggerComparator
TriggerComparator ScopeVis::m_triggerComparator private
Compares sample level to trigger level.
Definition at line 1143 of file scopevis.h.
Referenced by processTrace().
m_triggerConditions
std::vector<TriggerCondition*> ScopeVis::m_triggerConditions private
Chain of triggers.
Definition at line 1124 of file scopevis.h.
Referenced by computeDisplayTriggerLevels(), handleMessage(), nextTrigger(), processTrace(), and ~ScopeVis().
m_triggerLocation
int ScopeVis::m_triggerLocation private
Trigger location from end point.
Definition at line 1136 of file scopevis.h.
Referenced by feed().
m_triggerOneShot
bool ScopeVis::m_triggerOneShot private
True when one shot mode is active.
Definition at line 1146 of file scopevis.h.
Referenced by handleMessage(), and processTrace().
m_triggerState
TriggerState ScopeVis::m_triggerState private
Current trigger state.
Definition at line 1127 of file scopevis.h.
Referenced by feed(), and processTrace().
m_triggerWaitForReset
bool ScopeVis::m_triggerWaitForReset private
In one shot mode suspended until reset by UI.
Definition at line 1147 of file scopevis.h.
Referenced by feed(), handleMessage(), and processTrace().
The documentation for this class was generated from the following files:
sdrgui/dsp/scopevis.h
sdrgui/dsp/scopevis.cpp