SDRAngel: ScaleEngine Class Reference
ScaleEngine Class Reference
#include <scaleengine.h>
Classes
struct Tick
Public Types
typedef QList< Tick > TickList
Public Member Functions
ScaleEngine ()
void setOrientation (Qt::Orientation orientation)
void setFont (const QFont &font)
void setSize (float size)
float getSize ()
void setRange (Unit::Physical physicalUnit, float rangeMin, float rangeMax)
void setMakeOpposite (bool makeOpposite)
void setFixedDecimalPlaces (int decimalPlaces)
float getPosFromValue (double value)
float getValueFromPos (double pos)
const TickList & getTickList ()
QString getRangeMinStr ()
QString getRangeMaxStr ()
float getScaleWidth ()
Private Member Functions
QString formatTick (double value, int decimalPlaces)
void calcCharSize ()
void calcScaleFactor ()
double calcMajorTickUnits (double distance, int *retDecimalPlaces)
int calcTickTextSize (double distance)
void forceTwoTicks ()
void reCalc ()
double majorTickValue (int tick)
double minorTickValue (int tick)
Private Attributes
Qt::Orientation m_orientation
QFont m_font
float m_charSize
float m_size
Unit::Physical m_physicalUnit
float m_rangeMin
float m_rangeMax
bool m_recalc
double m_scale
QString m_unitStr
TickList m_tickList
double m_majorTickValueDistance
double m_firstMajorTickValue
int m_numMinorTicks
int m_decimalPlaces
int m_fixedDecimalPlaces
bool m_makeOpposite
Detailed Description
Definition at line 28 of file scaleengine.h.
Member Typedef Documentation
TickList
typedef QList<Tick> ScaleEngine::TickList
Definition at line 37 of file scaleengine.h.
Constructor & Destructor Documentation
ScaleEngine()
ScaleEngine::ScaleEngine ()
Definition at line 513 of file scaleengine.cpp.
                          :
     m_orientation(Qt::Horizontal),
     m_charSize(8),
     m_size(1.0f),
     m_physicalUnit(Unit::None),
     m_rangeMin(-1.0),
     m_rangeMax(1.0),
     m_recalc(true),
     m_scale(1.0f),
     m_majorTickValueDistance(1.0),
     m_firstMajorTickValue(1.0),
     m_numMinorTicks(1),
     m_decimalPlaces(1),
     m_fixedDecimalPlaces(2),
     m_makeOpposite(false)
 {
 }
Member Function Documentation
calcCharSize()
void ScaleEngine::calcCharSize () private
Definition at line 83 of file scaleengine.cpp.
References i, m_charSize, m_font, m_orientation, and leansdr::max().
Referenced by setFont().
 {
     QFontMetricsF fontMetrics(m_font);
     if(m_orientation == Qt::Vertical) {
         m_charSize = fontMetrics.height();
     } else {
         QString str("012345679.,-");
         int i;
         float size;
         float max = 0.0f;
         for(i = 0; i < str.length(); i++) {
             size = fontMetrics.width(QString(str[i]));
             if(size > max)
                 max = size;
         }
         m_charSize = max;
     }
 }
calcMajorTickUnits()
double ScaleEngine::calcMajorTickUnits (double distance, int * retDecimalPlaces) private
Definition at line 213 of file scaleengine.cpp.
References floor().
Referenced by calcTickTextSize(), and reCalc().
 {
     double sign;
     double log10x;
     double exponent;
     double base;
     int decimalPlaces;
     if(distance == 0.0)
         return 0.0;
     sign = (distance > 0.0) ? 1.0 : -1.0;
     log10x = log10(fabs(distance));
     exponent = floor(log10x);
     base = pow(10.0, log10x - exponent);
     decimalPlaces = (int)(-exponent);
 /*
     if((m_physicalUnit == Unit::Time) && (distance >= 1.0)) {
         if(retDecimalPlaces != NULL)
             *retDecimalPlaces = 0;
         if(distance < 1.0)
             return 1.0;
         else if(distance < 5.0)
             return 5.0;
         else if(distance < 10.0)
             return 10.0;
         else if(distance < 15.0)
             return 15.0;
         else if(distance < 30.0)
             return 30.0;
         else if(distance < 60.0)
             return 60.0;
         else if(distance < 5.0 * 60.0)
             return 5.0 * 60.0;
         else if(distance < 10.0 * 60.0)
             return 10.0 * 60.0;
         else if(distance < 15.0 * 60.0)
             return 15.0 * 60.0;
         else if(distance < 30.0 * 60.0)
             return 30.0 * 60.0;
         else if(distance < 3600.0)
             return 3600.0;
         else if(distance < 2.0 * 3600.0)
             return 2.0 * 3600.0;
         else if(distance < 3.0 * 3600.0)
             return 3.0 * 3600.0;
         else if(distance < 6.0 * 3600.0)
             return 6.0 * 3600.0;
         else if(distance < 12.0 * 3600.0)
             return 12.0 * 3600.0;
         else if(distance < 86000.0)
             return 86000.0;
         else if(distance < 2.0 * 86000.0)
             return 2.0 * 86000.0;
         else if(distance < 7.0 * 86000.0)
             return 7.0 * 86000.0;
         else if(distance < 10.0 * 86000.0)
             return 10.0 * 86000.0;
         else if(distance < 30.0 * 86000.0)
             return 30.0 * 86000.0;
         else return 90.0 * 86000.0;
     } */
     if(base <= 1.0) {
         base = 1.0;
     } else if(base <= 2.0) {
         base = 2.0;
     } else if(base <= 2.5) {
         base = 2.5;
         if(decimalPlaces >= 0)
             decimalPlaces++;
     } else if(base <= 5.0) {
         base = 5.0;
     } else {
         base = 10.0;
     }
     if(retDecimalPlaces != 0) {
         if(decimalPlaces < 0)
             decimalPlaces = 0;
         *retDecimalPlaces = decimalPlaces;
     }
     return sign * base * pow(10.0, exponent);
 }
calcScaleFactor()
void ScaleEngine::calcScaleFactor () private
Definition at line 103 of file scaleengine.cpp.
References Unit::AngleDegrees, Unit::Decibel, Unit::DecibelMicroVolt, Unit::DecibelMilliWatt, Unit::Frequency, Unit::Information, m_physicalUnit, m_rangeMax, m_rangeMin, m_scale, m_unitStr, Unit::None, Unit::Percent, Unit::Scientific, Unit::Time, Unit::TimeHMS, and Unit::Volt.
Referenced by reCalc().
 {
     double median, range, freqBase;
     median = ((m_rangeMax - m_rangeMin) / 2.0) + m_rangeMin;
     range = (m_rangeMax - m_rangeMin);
     freqBase = (median == 0 ? range : median);
     m_scale = 1.0;
     switch(m_physicalUnit) {
         case Unit::None:
         case Unit::Scientific:
             m_unitStr.clear();
             break;
         case Unit::Frequency:
             if(freqBase < 1000.0) {
                 m_unitStr = QObject::tr("Hz");
             } else if(freqBase < 1000000.0) {
                 m_unitStr = QObject::tr("kHz");
                 m_scale = 1000.0;
             } else if(freqBase < 1000000000.0) {
                 m_unitStr = QObject::tr("MHz");
                 m_scale = 1000000.0;
             } else if(freqBase < 1000000000000.0){
                 m_unitStr = QObject::tr("GHz");
                 m_scale = 1000000000.0;
             } else {
                 m_unitStr = QObject::tr("THz");
                 m_scale = 1000000000000.0;
             }
             break;
         case Unit::Information:
             if(median < 1024.0) {
                 m_unitStr = QObject::tr("Bytes");
             } else if(median < 1048576.0) {
                 m_unitStr = QObject::tr("KiBytes");
                 m_scale = 1024.0;
             } else if(median < 1073741824.0) {
                 m_unitStr = QObject::tr("MiBytes");
                 m_scale = 1048576.0;
             } else if(median < 1099511627776.0) {
                 m_unitStr = QObject::tr("GiBytes");
                 m_scale = 1073741824.0;
             } else if(median < 1125899906842624.0) {
                 m_unitStr = QObject::tr("TiBytes");
                 m_scale = 1099511627776.0;
             } else {
                 m_unitStr = QObject::tr("PiBytes");
                 m_scale = 1125899906842624.0;
             }
             break;
         case Unit::Percent:
             m_unitStr = QString("%");
             break;
         case Unit::Decibel:
             m_unitStr = QString("dB");
             break;
         case Unit::DecibelMilliWatt:
             m_unitStr = QString("dBm");
             break;
         case Unit::DecibelMicroVolt:
             m_unitStr = QString("dBV");
             break;
         case Unit::AngleDegrees:
             m_unitStr = QString("");
             break;
         case Unit::Time:
         case Unit::TimeHMS:
             if (median < 0.001) {
                 m_unitStr = QString("s");
                 m_scale = 0.000001;
             } else if (median < 1.0) {
                 m_unitStr = QString("ms");
                 m_scale = 0.001;
             } else if (median < 1000.0) {
                 m_unitStr = QString("s");
             } else {
                 m_unitStr = QString("ks");
                 m_scale = 1000.0;
             }
             break;
         case Unit::Volt:
             if (median < 1e-9) {
                 m_unitStr = QString("pV");
                 m_scale = 1e-12;
             } else if (median < 1e-6) {
                 m_unitStr = QString("nV");
                 m_scale = 1e-9;
             } else if (median < 1e-3) {
                 m_unitStr = QString("V");
                 m_scale = 1e-6;
             } else if (median < 1.0) {
                 m_unitStr = QString("mV");
                 m_scale = 1e-3;
             } else {
                 m_unitStr = QString("V");
             }
             break;
     }
 }
calcTickTextSize()
int ScaleEngine::calcTickTextSize (double distance) private
Definition at line 299 of file scaleengine.cpp.
References calcMajorTickUnits(), formatTick(), m_rangeMax, m_rangeMin, and m_scale.
Referenced by reCalc().
 {
     int tmp;
     int tickLen;
     int decimalPlaces;
     tickLen = 1;
     tmp = formatTick(m_rangeMin / m_scale, 0).length();
     if(tmp > tickLen)
         tickLen = tmp;
     tmp = formatTick(m_rangeMax / m_scale, 0).length();
     if(tmp > tickLen)
         tickLen = tmp;
     calcMajorTickUnits(distance, &decimalPlaces);
     return tickLen + decimalPlaces + 1;
 }
forceTwoTicks()
void ScaleEngine::forceTwoTicks () private
Definition at line 318 of file scaleengine.cpp.
References formatTick(), getPosFromValue(), m_decimalPlaces, m_font, m_orientation, m_rangeMax, m_rangeMin, m_scale, m_tickList, ScaleEngine::Tick::major, ScaleEngine::Tick::pos, ScaleEngine::Tick::text, ScaleEngine::Tick::textPos, and ScaleEngine::Tick::textSize.
Referenced by reCalc().
 {
     Tick tick;
     QFontMetricsF fontMetrics(m_font);
     m_tickList.clear();
     tick.major = true;
     tick.pos = getPosFromValue(m_rangeMin);
     tick.text = formatTick(m_rangeMin / m_scale, m_decimalPlaces);
     tick.textSize = fontMetrics.boundingRect(tick.text).width();
     if(m_orientation == Qt::Vertical)
         tick.textPos = tick.pos - fontMetrics.ascent() / 2;
     else tick.textPos = tick.pos - fontMetrics.boundingRect(tick.text).width() / 2;
     m_tickList.append(tick);
     tick.pos = getPosFromValue(m_rangeMax);
     tick.text = formatTick(m_rangeMax / m_scale, m_decimalPlaces);
     tick.textSize = fontMetrics.boundingRect(tick.text).width();
     if(m_orientation == Qt::Vertical)
         tick.textPos = tick.pos - fontMetrics.ascent() / 2;
     else tick.textPos = tick.pos - fontMetrics.boundingRect(tick.text).width() / 2;
     m_tickList.append(tick);
 }
formatTick()
QString ScaleEngine::formatTick (double value, int decimalPlaces) private
Definition at line 31 of file scaleengine.cpp.
References floor(), m_fixedDecimalPlaces, m_makeOpposite, m_physicalUnit, m_scale, Unit::Scientific, and Unit::TimeHMS.
Referenced by calcTickTextSize(), forceTwoTicks(), getRangeMaxStr(), getRangeMinStr(), and reCalc().
 {
     if (m_physicalUnit != Unit::TimeHMS)
     {
         if (m_physicalUnit == Unit::Scientific) {
             return QString("%1").arg(m_makeOpposite ? -value : value, 0, 'e', m_fixedDecimalPlaces);
         } else {
             return QString("%1").arg(m_makeOpposite ? -value : value, 0, 'f', decimalPlaces);
         }
     }
     else
     {
         if (m_scale < 1.0f) { // sub second prints just as is
             return QString("%1").arg(m_makeOpposite ? -value : value, 0, 'f', decimalPlaces);
         }
         QString str;
         double actual = value * m_scale; // this is the actual value in seconds
         double orig = fabs(actual);
         double tmp;
         if(orig >= 86400.0) {
             tmp = floor(actual / 86400.0);
             str = QString("%1.").arg(tmp, 0, 'f', 0);
             actual -= tmp * 86400.0;
             if(actual < 0.0)
                 actual *= -1.0;
         }
         if(orig >= 3600.0) {
             tmp = floor(actual / 3600.0);
             str += QString("%1:").arg(tmp, 2, 'f', 0, QChar('0'));
             actual -= tmp * 3600.0;
             if(actual < 0.0)
                 actual *= -1.0;
         }
         if(orig >= 60.0) {
             tmp = floor(actual / 60.0);
             str += QString("%1:").arg(tmp, 2, 'f', 0, QChar('0'));
             actual -= tmp * 60.0;
             if(actual < 0.0)
                 actual *= -1.0;
         }
         tmp = m_makeOpposite ? -actual : actual;
         str += QString("%1").arg(tmp, 2, 'f', decimalPlaces, QChar('0'));
         return str;
     }
 }
getPosFromValue()
float ScaleEngine::getPosFromValue (double value)
Definition at line 581 of file scaleengine.cpp.
References m_rangeMax, m_rangeMin, and m_size.
Referenced by GLSpectrum::applyChanges(), forceTwoTicks(), reCalc(), and GLSpectrum::wheelEvent().
 {
     return ((value - m_rangeMin) / (m_rangeMax - m_rangeMin)) * (m_size - 1.0);
 }
getRangeMaxStr()
QString ScaleEngine::getRangeMaxStr ()
Definition at line 604 of file scaleengine.cpp.
References formatTick(), m_decimalPlaces, m_rangeMax, m_scale, and m_unitStr.
 {
     if(m_unitStr.length() > 0)
         return QString("%1 %2").arg(formatTick(m_rangeMax / m_scale, m_decimalPlaces)).arg(m_unitStr);
         else return QString("%1").arg(formatTick(m_rangeMax / m_scale, m_decimalPlaces));
 }
getRangeMinStr()
QString ScaleEngine::getRangeMinStr ()
Definition at line 597 of file scaleengine.cpp.
References formatTick(), m_decimalPlaces, m_rangeMin, m_scale, and m_unitStr.
 {
     if(m_unitStr.length() > 0)
         return QString("%1 %2").arg(formatTick(m_rangeMin / m_scale, m_decimalPlaces)).arg(m_unitStr);
         else return QString("%1").arg(formatTick(m_rangeMin / m_scale, m_decimalPlaces));
 }
getScaleWidth()
float ScaleEngine::getScaleWidth ()
Definition at line 611 of file scaleengine.cpp.
References i, m_tickList, leansdr::max(), and reCalc().
Referenced by GLSpectrum::applyChanges().
 {
     float max;
     float len;
     int i;
     reCalc();
     max = 0.0f;
     for(i = 0; i < m_tickList.count(); i++) {
         len = m_tickList[i].textSize;
         if(len > max)
             max = len;
     }
     return max;
 }
getSize()
float ScaleEngine::getSize () inline
Definition at line 80 of file scaleengine.h.
Referenced by GLScope::paintGL(), GLSpectrum::paintGL(), and GLSpectrum::wheelEvent().
 { return m_size; }
getTickList()
const ScaleEngine::TickList & ScaleEngine::getTickList ()
Definition at line 591 of file scaleengine.cpp.
References m_tickList, and reCalc().
Referenced by GLSpectrum::applyChanges(), GLScope::applyConfig(), GLScope::paintGL(), GLSpectrum::paintGL(), LevelMeterVU::resized(), LevelMeterSignalDB::resized(), GLScope::setHorizontalDisplays(), GLScope::setPolarDisplays(), GLScope::setUniqueDisplays(), and GLScope::setVerticalDisplays().
 {
     reCalc();
     return m_tickList;
 }
getValueFromPos()
float ScaleEngine::getValueFromPos (double pos)
Definition at line 586 of file scaleengine.cpp.
References m_rangeMax, m_rangeMin, and m_size.
Referenced by GLSpectrum::mouseMoveEvent(), and GLSpectrum::mousePressEvent().
 {
     return ((pos * (m_rangeMax - m_rangeMin)) / (m_size - 1.0)) + m_rangeMin;
 }
majorTickValue()
double ScaleEngine::majorTickValue (int tick) private
Definition at line 501 of file scaleengine.cpp.
References m_firstMajorTickValue, and m_majorTickValueDistance.
Referenced by reCalc().
 {
     return m_firstMajorTickValue + (tick * m_majorTickValueDistance);
 }
minorTickValue()
double ScaleEngine::minorTickValue (int tick) private
Definition at line 506 of file scaleengine.cpp.
References m_majorTickValueDistance, and m_numMinorTicks.
Referenced by reCalc().
 {
     if(m_numMinorTicks < 1)
         return 0.0;
     return (m_majorTickValueDistance * tick) / m_numMinorTicks;
 }
reCalc()
void ScaleEngine::reCalc () private
Definition at line 343 of file scaleengine.cpp.
References calcMajorTickUnits(), calcScaleFactor(), calcTickTextSize(), floor(), forceTwoTicks(), formatTick(), getPosFromValue(), i, m_charSize, m_decimalPlaces, m_firstMajorTickValue, m_font, m_majorTickValueDistance, m_numMinorTicks, m_orientation, m_rangeMax, m_rangeMin, m_recalc, m_scale, m_size, m_tickList, ScaleEngine::Tick::major, majorTickValue(), minorTickValue(), ScaleEngine::Tick::pos, ScaleEngine::Tick::text, ScaleEngine::Tick::textPos, and ScaleEngine::Tick::textSize.
Referenced by getScaleWidth(), and getTickList().
 {
     float majorTickSize;
     double rangeMinScaled;
     double rangeMaxScaled;
     int maxNumMajorTicks;
     int numMajorTicks;
     int step;
     int skip;
     double value;
     double value2;
     int i;
     int j;
     Tick tick;
     float pos;
     QString str;
     QFontMetricsF fontMetrics(m_font);
     float endPos;
     float lastEndPos;
     bool done;
     if(!m_recalc)
         return;
     m_recalc = false;
     m_tickList.clear();
     calcScaleFactor();
     rangeMinScaled = m_rangeMin / m_scale;
     rangeMaxScaled = m_rangeMax / m_scale;
     if(m_orientation == Qt::Vertical)
     {
         maxNumMajorTicks = (int)(m_size / (fontMetrics.lineSpacing() * 1.3f));
         m_majorTickValueDistance = calcMajorTickUnits((rangeMaxScaled - rangeMinScaled) / maxNumMajorTicks, &m_decimalPlaces);
     }
     else
     {
         majorTickSize = (calcTickTextSize((rangeMaxScaled - rangeMinScaled) / 20) + 2) * m_charSize;
         if(majorTickSize != 0.0) {
             maxNumMajorTicks = (int)(m_size / majorTickSize);
         } else {
             maxNumMajorTicks = 20;
         }
         m_majorTickValueDistance = calcMajorTickUnits((rangeMaxScaled - rangeMinScaled) / maxNumMajorTicks, &m_decimalPlaces);
     }
     numMajorTicks = (int)((rangeMaxScaled - rangeMinScaled) / m_majorTickValueDistance);
     if(numMajorTicks == 0) {
         forceTwoTicks();
         return;
     }
     if(maxNumMajorTicks > 0)
         m_numMinorTicks = (int)(m_size / (maxNumMajorTicks * fontMetrics.height()));
         else m_numMinorTicks = 0;
     if(m_numMinorTicks < 1)
         m_numMinorTicks = 0;
     else if(m_numMinorTicks < 2)
         m_numMinorTicks = 1;
     else if(m_numMinorTicks < 5)
         m_numMinorTicks = 2;
     else if(m_numMinorTicks < 10)
         m_numMinorTicks = 5;
     else m_numMinorTicks = 10;
     m_firstMajorTickValue = floor(rangeMinScaled / m_majorTickValueDistance) * m_majorTickValueDistance;
     skip = 0;
     if(rangeMinScaled == rangeMaxScaled)
         return;
     while(true) {
         m_tickList.clear();
         step = 0;
         lastEndPos = -100000000;
         done = true;
         for(i = 0; true; i++) {
             value = majorTickValue(i);
             for(j = 1; j < m_numMinorTicks; j++) {
                 value2 = value + minorTickValue(j);
                 if(value2 < rangeMinScaled)
                     continue;
                 if(value2 > rangeMaxScaled)
                     break;
                 pos = getPosFromValue((value + minorTickValue(j)) * m_scale);
                 if((pos >= 0) && (pos < m_size)) {
                     tick.pos = pos;
                     tick.major = false;
                     tick.textPos = -1;
                     tick.textSize = -1;
                     tick.text.clear();
                 }
                 m_tickList.append(tick);
             }
             pos = getPosFromValue(value * m_scale);
             if(pos < 0.0)
                 continue;
             if(pos >= m_size)
                 break;
             tick.pos = pos;
             tick.major = true;
             tick.textPos = -1;
             tick.textSize = -1;
             tick.text.clear();
             if(step % (skip + 1) != 0) {
                 m_tickList.append(tick);
                 step++;
                 continue;
             }
             step++;
             str = formatTick(value, m_decimalPlaces);
             tick.text = str;
             tick.textSize = fontMetrics.boundingRect(tick.text).width();
             if(m_orientation == Qt::Vertical) {
                 tick.textPos = pos - fontMetrics.ascent() / 2;
                 endPos = tick.textPos + fontMetrics.ascent();
             } else {
                 tick.textPos = pos - fontMetrics.boundingRect(tick.text).width() / 2;
                 endPos = tick.textPos + tick.textSize;
             }
             if(lastEndPos >= tick.textPos) {
                 done = false;
                 break;
             } else {
                 lastEndPos = endPos;
             }
             m_tickList.append(tick);
         }
         if(done)
             break;
         skip++;
     }
     // make sure we have at least two major ticks with numbers
     numMajorTicks = 0;
     for(i = 0; i < m_tickList.count(); i++) {
         tick = m_tickList.at(i);
         if(tick.major)
             numMajorTicks++;
     }
     if(numMajorTicks < 2)
         forceTwoTicks();
 }
setFixedDecimalPlaces()
void ScaleEngine::setFixedDecimalPlaces (int decimalPlaces) inline
Definition at line 83 of file scaleengine.h.
 { m_fixedDecimalPlaces =decimalPlaces; }
setFont()
void ScaleEngine::setFont (const QFont & font)
Definition at line 537 of file scaleengine.cpp.
References calcCharSize(), m_font, and m_recalc.
Referenced by GLScope::GLScope(), LevelMeterSignalDB::LevelMeterSignalDB(), and LevelMeterVU::LevelMeterVU().
 {
     m_font = font;
     m_recalc = true;
     calcCharSize();
 }
setMakeOpposite()
void ScaleEngine::setMakeOpposite (bool makeOpposite) inline
Definition at line 82 of file scaleengine.h.
Referenced by GLSpectrum::applyChanges().
 { m_makeOpposite = makeOpposite; }
setOrientation()
void ScaleEngine::setOrientation (Qt::Orientation orientation)
Definition at line 531 of file scaleengine.cpp.
References m_orientation, and m_recalc.
Referenced by GLScope::GLScope(), LevelMeterSignalDB::LevelMeterSignalDB(), and LevelMeterVU::LevelMeterVU().
 {
     m_orientation = orientation;
     m_recalc = true;
 }
setRange()
void ScaleEngine::setRange (Unit::Physical physicalUnit, float rangeMin, float rangeMax)
Definition at line 554 of file scaleengine.cpp.
References m_physicalUnit, m_rangeMax, m_rangeMin, and m_recalc.
Referenced by GLSpectrum::applyChanges(), GLScope::applyConfig(), LevelMeterSignalDB::LevelMeterSignalDB(), LevelMeterVU::LevelMeterVU(), LevelMeterSignalDB::setRange(), and GLScope::setYScale().
 {
     double tmpRangeMin;
     double tmpRangeMax;
 /*
     if(rangeMin < rangeMax) {
         tmpRangeMin = rangeMin;
         tmpRangeMax = rangeMax;
     } else if(rangeMin > rangeMax) {
         tmpRangeMin = rangeMax;
         tmpRangeMax = rangeMin;
     } else {
         tmpRangeMin = rangeMin * 0.99;
         tmpRangeMax = rangeMin * 1.01 + 0.01;
     }
 */
     tmpRangeMin = rangeMin;
     tmpRangeMax = rangeMax;
     if((tmpRangeMin != m_rangeMin) || (tmpRangeMax != m_rangeMax) || (m_physicalUnit != physicalUnit)) {
         m_physicalUnit = physicalUnit;
         m_rangeMin = tmpRangeMin;
         m_rangeMax = tmpRangeMax;
         m_recalc = true;
     }
 }
setSize()
void ScaleEngine::setSize (float size)
Definition at line 544 of file scaleengine.cpp.
References m_recalc, and m_size.
Referenced by GLSpectrum::applyChanges(), LevelMeterVU::resized(), LevelMeterSignalDB::resized(), GLScope::setHorizontalDisplays(), GLScope::setPolarDisplays(), GLScope::setUniqueDisplays(), and GLScope::setVerticalDisplays().
 {
     if(size > 0.0f) {
         m_size = size;
     } else {
         m_size = 1.0f;
     }
     m_recalc = true;
 }
Member Data Documentation
m_charSize
float ScaleEngine::m_charSize private
Definition at line 43 of file scaleengine.h.
Referenced by calcCharSize(), and reCalc().
m_decimalPlaces
int ScaleEngine::m_decimalPlaces private
Definition at line 59 of file scaleengine.h.
Referenced by forceTwoTicks(), getRangeMaxStr(), getRangeMinStr(), and reCalc().
m_firstMajorTickValue
double ScaleEngine::m_firstMajorTickValue private
Definition at line 57 of file scaleengine.h.
Referenced by majorTickValue(), and reCalc().
m_fixedDecimalPlaces
int ScaleEngine::m_fixedDecimalPlaces private
Definition at line 60 of file scaleengine.h.
Referenced by formatTick().
m_font
QFont ScaleEngine::m_font private
Definition at line 42 of file scaleengine.h.
Referenced by calcCharSize(), forceTwoTicks(), reCalc(), and setFont().
m_majorTickValueDistance
double ScaleEngine::m_majorTickValueDistance private
Definition at line 56 of file scaleengine.h.
Referenced by majorTickValue(), minorTickValue(), and reCalc().
m_makeOpposite
bool ScaleEngine::m_makeOpposite private
Definition at line 61 of file scaleengine.h.
Referenced by formatTick().
m_numMinorTicks
int ScaleEngine::m_numMinorTicks private
Definition at line 58 of file scaleengine.h.
Referenced by minorTickValue(), and reCalc().
m_orientation
Qt::Orientation ScaleEngine::m_orientation private
Definition at line 41 of file scaleengine.h.
Referenced by calcCharSize(), forceTwoTicks(), reCalc(), and setOrientation().
m_physicalUnit
Unit::Physical ScaleEngine::m_physicalUnit private
Definition at line 47 of file scaleengine.h.
Referenced by calcScaleFactor(), formatTick(), and setRange().
m_rangeMax
float ScaleEngine::m_rangeMax private
Definition at line 49 of file scaleengine.h.
Referenced by calcScaleFactor(), calcTickTextSize(), forceTwoTicks(), getPosFromValue(), getRangeMaxStr(), getValueFromPos(), reCalc(), and setRange().
m_rangeMin
float ScaleEngine::m_rangeMin private
Definition at line 48 of file scaleengine.h.
Referenced by calcScaleFactor(), calcTickTextSize(), forceTwoTicks(), getPosFromValue(), getRangeMinStr(), getValueFromPos(), reCalc(), and setRange().
m_recalc
bool ScaleEngine::m_recalc private
Definition at line 52 of file scaleengine.h.
Referenced by reCalc(), setFont(), setOrientation(), setRange(), and setSize().
m_scale
double ScaleEngine::m_scale private
Definition at line 53 of file scaleengine.h.
Referenced by calcScaleFactor(), calcTickTextSize(), forceTwoTicks(), formatTick(), getRangeMaxStr(), getRangeMinStr(), and reCalc().
m_size
float ScaleEngine::m_size private
Definition at line 46 of file scaleengine.h.
Referenced by getPosFromValue(), getValueFromPos(), reCalc(), and setSize().
m_tickList
TickList ScaleEngine::m_tickList private
Definition at line 55 of file scaleengine.h.
Referenced by forceTwoTicks(), getScaleWidth(), getTickList(), and reCalc().
m_unitStr
QString ScaleEngine::m_unitStr private
Definition at line 54 of file scaleengine.h.
Referenced by calcScaleFactor(), getRangeMaxStr(), and getRangeMinStr().
The documentation for this class was generated from the following files:
sdrgui/gui/scaleengine.h
sdrgui/gui/scaleengine.cpp