SDRAngel: DevicePlutoSDR Class Reference
DevicePlutoSDR Class Reference
#include <deviceplutosdr.h>
Public Member Functions
void scan ()
void getSerials (std::vector< std::string > &serials) const
int getNbDevices () const
const std::string * getURIAt (unsigned int index) const
const std::string * getSerialAt (unsigned int index) const
DevicePlutoSDRBox * getDeviceFromURI (const std::string &uri)
DevicePlutoSDRBox * getDeviceFromSerial (const std::string &serial)
Static Public Member Functions
static DevicePlutoSDR & instance ()
Static Public Attributes
static const uint64_t rxLOLowLimitFreq = 70000000UL
Rx LO hard coded lower frequency limit (Hz)
static const uint64_t rxLOHighLimitFreq = 6000000000UL
Rx LO hard coded lower frequency limit (Hz)
static const uint64_t txLOLowLimitFreq = 46875000UL
Tx LO hard coded lower frequency limit (Hz)
static const uint64_t txLOHighLimitFreq = 6000000000UL
Tx LO hard coded lower frequency limit (Hz)
static const uint32_t srLowLimitFreq = (25000000U/12U)+3U
Device sample rate lower limit in S/s.
static const uint32_t srHighLimitFreq = 20000000U
Device sample rate higher limit in S/s.
static const uint32_t bbLPRxLowLimitFreq = 200000U
Analog base band Rx low pass filter lower frequency limit (Hz)
static const uint32_t bbLPRxHighLimitFreq = 14000000U
Analog base band Rx high pass filter lower frequency limit (Hz)
static const uint32_t bbLPTxLowLimitFreq = 625000U
Analog base band Tx low pass filter lower frequency limit (Hz)
static const uint32_t bbLPTxHighLimitFreq = 16000000U
Analog base band Tx high pass filter lower frequency limit (Hz)
static const float firBWLowLimitFactor = 0.05f
Factor by which the FIR working sample rate is multiplied to yield bandwidth lower limit.
static const float firBWHighLimitFactor = 0.9f
Factor by which the FIR working sample rate is multiplied to yield bandwidth higher limit.
Protected Member Functions
DevicePlutoSDR ()
~DevicePlutoSDR ()
Private Attributes
DevicePlutoSDRScan m_scan
Detailed Description
Definition at line 28 of file deviceplutosdr.h.
Constructor & Destructor Documentation
DevicePlutoSDR()
DevicePlutoSDR::DevicePlutoSDR () protected
Definition at line 37 of file deviceplutosdr.cpp.
 {
 }
~DevicePlutoSDR()
DevicePlutoSDR::~DevicePlutoSDR () protected
Definition at line 41 of file deviceplutosdr.cpp.
 {
 }
Member Function Documentation
getDeviceFromSerial()
DevicePlutoSDRBox * DevicePlutoSDR::getDeviceFromSerial (const std::string & serial)
Definition at line 56 of file deviceplutosdr.cpp.
References DevicePlutoSDRBox, DevicePlutoSDRScan::getURIFromSerial(), and m_scan.
Referenced by DevicePlutoSDRParams::open().
 {
     const std::string *uri = m_scan.getURIFromSerial(serial);
     if (uri) {
         return new DevicePlutoSDRBox(*uri);
     } else {
         return 0;
     }
 }
getDeviceFromURI()
DevicePlutoSDRBox * DevicePlutoSDR::getDeviceFromURI (const std::string & uri)
Definition at line 51 of file deviceplutosdr.cpp.
References DevicePlutoSDRBox.
 {
     return new DevicePlutoSDRBox(uri);
 }
getNbDevices()
int DevicePlutoSDR::getNbDevices () const inline
Definition at line 34 of file deviceplutosdr.h.
 { return m_scan.getNbDevices(); }
getSerialAt()
const std::string* DevicePlutoSDR::getSerialAt (unsigned int index) const inline
Definition at line 36 of file deviceplutosdr.h.
 { return m_scan.getSerialAt(index); }
getSerials()
void DevicePlutoSDR::getSerials (std::vector< std::string > & serials) const inline
Definition at line 33 of file deviceplutosdr.h.
Referenced by PlutoSDROutputPlugin::enumSampleSinks(), and PlutoSDRInputPlugin::enumSampleSources().
 { m_scan.getSerials(serials); }
getURIAt()
const std::string* DevicePlutoSDR::getURIAt (unsigned int index) const inline
Definition at line 35 of file deviceplutosdr.h.
 { return m_scan.getURIAt(index); }
instance()
DevicePlutoSDR & DevicePlutoSDR::instance () static
Definition at line 45 of file deviceplutosdr.cpp.
Referenced by PlutoSDROutputPlugin::enumSampleSinks(), PlutoSDRInputPlugin::enumSampleSources(), PlutoSDRInputPlugin::initPlugin(), PlutoSDROutputPlugin::initPlugin(), and DevicePlutoSDRParams::open().
 {
     static DevicePlutoSDR inst;
     return inst;
 }
scan()
void DevicePlutoSDR::scan () inline
Definition at line 32 of file deviceplutosdr.h.
Referenced by PlutoSDROutputPlugin::enumSampleSinks(), and PlutoSDRInputPlugin::enumSampleSources().
 { m_scan.scan(); }
Member Data Documentation
bbLPRxHighLimitFreq
const uint32_t DevicePlutoSDR::bbLPRxHighLimitFreq = 14000000U static
Analog base band Rx high pass filter lower frequency limit (Hz)
Definition at line 47 of file deviceplutosdr.h.
Referenced by DevicePlutoSDRBox::getbbLPRxRange().
bbLPRxLowLimitFreq
const uint32_t DevicePlutoSDR::bbLPRxLowLimitFreq = 200000U static
Analog base band Rx low pass filter lower frequency limit (Hz)
Definition at line 46 of file deviceplutosdr.h.
Referenced by DevicePlutoSDRBox::getbbLPRxRange().
bbLPTxHighLimitFreq
const uint32_t DevicePlutoSDR::bbLPTxHighLimitFreq = 16000000U static
Analog base band Tx high pass filter lower frequency limit (Hz)
Definition at line 49 of file deviceplutosdr.h.
Referenced by DevicePlutoSDRBox::getbbLPTxRange().
bbLPTxLowLimitFreq
const uint32_t DevicePlutoSDR::bbLPTxLowLimitFreq = 625000U static
Analog base band Tx low pass filter lower frequency limit (Hz)
Definition at line 48 of file deviceplutosdr.h.
Referenced by DevicePlutoSDRBox::getbbLPTxRange().
firBWHighLimitFactor
const float DevicePlutoSDR::firBWHighLimitFactor = 0.9f static
Factor by which the FIR working sample rate is multiplied to yield bandwidth higher limit.
Definition at line 51 of file deviceplutosdr.h.
Referenced by DevicePlutoSDRBox::setFIR(), PlutoSDROutputGUI::setFIRBWLimits(), and PlutoSDRInputGui::setFIRBWLimits().
firBWLowLimitFactor
const float DevicePlutoSDR::firBWLowLimitFactor = 0.05f static
Factor by which the FIR working sample rate is multiplied to yield bandwidth lower limit.
Definition at line 50 of file deviceplutosdr.h.
Referenced by DevicePlutoSDRBox::setFIR(), PlutoSDROutputGUI::setFIRBWLimits(), and PlutoSDRInputGui::setFIRBWLimits().
m_scan
DevicePlutoSDRScan DevicePlutoSDR::m_scan private
Definition at line 57 of file deviceplutosdr.h.
Referenced by getDeviceFromSerial().
rxLOHighLimitFreq
const uint64_t DevicePlutoSDR::rxLOHighLimitFreq = 6000000000UL static
Rx LO hard coded lower frequency limit (Hz)
Definition at line 41 of file deviceplutosdr.h.
Referenced by DevicePlutoSDRBox::getRxLORange().
rxLOLowLimitFreq
const uint64_t DevicePlutoSDR::rxLOLowLimitFreq = 70000000UL static
Rx LO hard coded lower frequency limit (Hz)
Definition at line 40 of file deviceplutosdr.h.
Referenced by DevicePlutoSDRBox::getRxLORange().
srHighLimitFreq
const uint32_t DevicePlutoSDR::srHighLimitFreq = 20000000U static
Device sample rate higher limit in S/s.
Definition at line 45 of file deviceplutosdr.h.
Referenced by PlutoSDROutputGUI::displaySampleRate(), PlutoSDRInputGui::displaySampleRate(), PlutoSDRInputGui::PlutoSDRInputGui(), PlutoSDROutputGUI::PlutoSDROutputGUI(), PlutoSDROutputGUI::setSampleRateLimits(), and PlutoSDRInputGui::setSampleRateLimits().
srLowLimitFreq
const uint32_t DevicePlutoSDR::srLowLimitFreq = (25000000U/12U)+3U static
Device sample rate lower limit in S/s.
Definition at line 44 of file deviceplutosdr.h.
Referenced by PlutoSDROutputGUI::displaySampleRate(), PlutoSDRInputGui::displaySampleRate(), PlutoSDRInputGui::PlutoSDRInputGui(), PlutoSDROutputGUI::PlutoSDROutputGUI(), PlutoSDROutputGUI::setSampleRateLimits(), and PlutoSDRInputGui::setSampleRateLimits().
txLOHighLimitFreq
const uint64_t DevicePlutoSDR::txLOHighLimitFreq = 6000000000UL static
Tx LO hard coded lower frequency limit (Hz)
Definition at line 43 of file deviceplutosdr.h.
Referenced by DevicePlutoSDRBox::getTxLORange().
txLOLowLimitFreq
const uint64_t DevicePlutoSDR::txLOLowLimitFreq = 46875000UL static
Tx LO hard coded lower frequency limit (Hz)
Definition at line 42 of file deviceplutosdr.h.
Referenced by DevicePlutoSDRBox::getTxLORange().
The documentation for this class was generated from the following files:
devices/plutosdr/deviceplutosdr.h
devices/plutosdr/deviceplutosdr.cpp