SDRAngel: leansdr::fast_qpsk_receiver< T > Struct Template Reference
leansdr::fast_qpsk_receiver< T > Struct Template Reference
#include <sdr.h>
Classes
struct polar
Public Types
typedef u8 hardsymbol
Public Member Functions
fast_qpsk_receiver (scheduler *sch, pipebuf< complex< T >> &_in, pipebuf< hardsymbol > &_out, pipebuf< float > *_freq_out=NULL, pipebuf< complex< T >> *_cstln_out=NULL)
void set_omega (float _omega, float tol=10e-6)
void set_freq (float freq)
void update_freq_limits ()
void run ()
Public Member Functions inherited from leansdr::runnable
runnable (scheduler *_sch, const char *name)
Public Member Functions inherited from leansdr::runnable_common
runnable_common (const char *_name)
virtual ~runnable_common ()
virtual void shutdown ()
Public Attributes
unsigned long meas_decimation
float omega
float min_omega
float max_omega
signed long freqw
signed long min_freqw
signed long max_freqw
float pll_adjustment
bool allow_drift
cu8 p
cu8 c
Public Attributes inherited from leansdr::runnable_common
const char * name
Static Public Attributes
static const unsigned int chunk_size = 128
static const int RLUT_BITS = 8
static const int RLUT_ANGLES = 1 << RLUT_BITS
Private Member Functions
u_angle fast_arg (const cu8 &c)
cu8 arg_to_symbol (u_angle a)
void init_lookup_tables ()
Private Attributes
struct leansdr::fast_qpsk_receiver::polar lut_polar [256][256]
cu8 lut_rect [RLUT_ANGLES][256]
cu8 lut_sincos [65536]
struct {
cu8 p
cu8 c
} hist [3]
pipereader< cu8 > in
pipewriter< hardsymbol > out
float mu
u_angle phase
unsigned long meas_count
pipewriter< float > * freq_out
pipewriter< float > * mer_out
pipewriter< cu8 > * cstln_out
Additional Inherited Members
Protected Attributes inherited from leansdr::runnable
scheduler * sch
Detailed Description
template<typename T>
struct leansdr::fast_qpsk_receiver< T >
Definition at line 1321 of file sdr.h.
Member Typedef Documentation
hardsymbol
template<typename T > typedef u8 leansdr::fast_qpsk_receiver< T >::hardsymbol
Definition at line 1323 of file sdr.h.
Constructor & Destructor Documentation
fast_qpsk_receiver()
template<typename T > leansdr::fast_qpsk_receiver< T >::fast_qpsk_receiver (scheduler * sch, pipebuf< complex< T >> & _in, pipebuf< hardsymbol > & _out, pipebuf< float > * _freq_out = NULL, pipebuf< complex< T >> * _cstln_out = NULL) inline
Definition at line 1331 of file sdr.h.
                                                                : runnable(sch, "Fast QPSK receiver"),
                                                                  meas_decimation(1048576),
                                                                  pll_adjustment(1.0),
                                                                  allow_drift(false),
                                                                  in(_in),
                                                                  out(_out, chunk_size),
                                                                  mu(0),
                                                                  phase(0),
                                                                  meas_count(0)
     {
         set_omega(1);
         set_freq(0);
         freq_out = _freq_out ? new pipewriter<float>(*_freq_out) : NULL;
         cstln_out = _cstln_out ? new pipewriter<complex<T>>(*_cstln_out) : NULL;
         memset(hist, 0, sizeof(hist));
         init_lookup_tables();
     }
Member Function Documentation
arg_to_symbol()
template<typename T > cu8 leansdr::fast_qpsk_receiver< T >::arg_to_symbol (u_angle a) inline private
Definition at line 1546 of file sdr.h.
     {
         return lut_sincos[a];
     }
fast_arg()
template<typename T > u_angle leansdr::fast_qpsk_receiver< T >::fast_arg (const cu8 & c) inline private
Definition at line 1537 of file sdr.h.
References leansdr::complex< T >::im, and leansdr::complex< T >::re.
     {
         // TBD read cu8 as u16 index, same endianness as in init()
         return lut_polar[c.re][c.im].a;
     }
init_lookup_tables()
template<typename T > void leansdr::fast_qpsk_receiver< T >::init_lookup_tables () inline private
Definition at line 1551 of file sdr.h.
References cos(), leansdr::auto_notch< T >::slot::i, leansdr::complex< T >::im, M_PI, leansdr::complex< T >::re, and sin().
     {
         for (int i = 0; i < 256; ++i)
         {
             for (int q = 0; q < 256; ++q)
             {
                 // Don't cast float to unsigned directly
                 lut_polar[i][q].a = (s_angle)(atan2f(q - 128, i - 128) * 65536 / (2 * M_PI));
                 lut_polar[i][q].r = (int)hypotf(i - 128, q - 128);
             }
         }
         for (unsigned long a = 0; a < 65536; ++a)
         {
             float f = 2 * M_PI * a / 65536;
             lut_sincos[a].re = 128 + cstln_amp * cosf(f);
             lut_sincos[a].im = 128 + cstln_amp * sinf(f);
         }
         for (int a = 0; a < RLUT_ANGLES; ++a)
         {
             for (int r = 0; r < 256; ++r)
             {
                 lut_rect[a][r].re = (int)(128 + r * cos(2 * M_PI * a / RLUT_ANGLES));
                 lut_rect[a][r].im = (int)(128 + r * sin(2 * M_PI * a / RLUT_ANGLES));
             }
         }
     }
run()
template<typename T > void leansdr::fast_qpsk_receiver< T >::run () inline virtual
Reimplemented from leansdr::runnable_common.
Definition at line 1378 of file sdr.h.
References leansdr::fast_qpsk_receiver< T >::polar::a, leansdr::cstln_amp, leansdr::fail(), leansdr::complex< T >::im, leansdr::auto_notch< T >::in, M_PI, leansdr::auto_notch< T >::out, leansdr::auto_notch< T >::phase, leansdr::fast_qpsk_receiver< T >::polar::r, and leansdr::complex< T >::re.
     {
         // Magic constants that work with the qa recordings.
         signed long freq_alpha = 0.04 * 65536;
         signed long freq_beta = 0.0012 * 256 * 65536 / omega * pll_adjustment;
         if (!freq_beta)
             fail("Excessive oversampling");
         float gain_mu = 0.02 / (cstln_amp * cstln_amp) * 2;
         int max_meas = chunk_size / meas_decimation + 1;
         // Largin margin on output_size because mu adjustments
         // can lead to more than chunk_size/min_omega symbols.
         while (in.readable() >= chunk_size + 1 && // +1 for interpolation
                out.writable() >= chunk_size && (!freq_out || freq_out->writable() >= max_meas) && (!cstln_out || cstln_out->writable() >= max_meas))
         {
             complex<T> *pin = in.rd(), *pin0 = pin, *pend = pin + chunk_size;
             hardsymbol *pout = out.wr(), *pout0 = pout;
             cu8 s;
             u_angle symbol_arg = 0; // Exported for constellation viewer
             while (pin < pend)
             {
                 // Here mu is the time of the next symbol counted from 0 at pin.
                 if (mu < 1)
                 {
                     // Here 0<=mu<1 is the fractional time of the next symbol
                     // between pin and pin+1.
                     // Derotate and interpolate
 #if 0   /* Phase only (does not work)
            Careful with the float/signed/unsigned casts */
                     u_angle a0 = fast_arg(pin[0]) - phase;
                     u_angle a1 = fast_arg(pin[1]) - (phase+freqw);
                     s_angle da = a1 - a0;
                     symbol_arg = a0 + (s_angle)(da*mu);
                     s = arg_to_symbol(symbol_arg);
 #elif 1 // Linear by lookup-table. 1.2M on bench3bishs
                     polar *p0 = &lut_polar[pin[0].re][pin[0].im];
                     u_angle a0 = (u_angle)(p0->a - phase) >> (16 - RLUT_BITS);
                     cu8 *p0r = &lut_rect[a0][p0->r >> 1];
                     polar *p1 = &lut_polar[pin[1].re][pin[1].im];
                     u_angle a1 = (u_angle)(p1->a - (phase + freqw)) >> (16 - RLUT_BITS);
                     cu8 *p1r = &lut_rect[a1][p1->r >> 1];
                     s.re = (int)(p0r->re + (p1r->re - p0r->re) * mu);
                     s.im = (int)(p0r->im + (p1r->im - p0r->im) * mu);
                     symbol_arg = fast_arg(s);
 #else   // Linear floating-point, for reference
                     float a0 = -(int)phase * M_PI / 32768;
                     float cosa0 = cosf(a0), sina0 = sinf(a0);
                     complex<float>
                         p0r(((float)pin[0].re - 128) * cosa0 - ((float)pin[0].im - 128) * sina0,
                             ((float)pin[0].re - 128) * sina0 + ((float)pin[0].im - 128) * cosa0);
                     float a1 = -(int)(phase + freqw) * M_PI / 32768;
                     float cosa1 = cosf(a1), sina1 = sinf(a1);
                     complex<float>
                         p1r(((float)pin[1].re - 128) * cosa1 - ((float)pin[1].im - 128) * sina1,
                             ((float)pin[1].re - 128) * sina1 + ((float)pin[1].im - 128) * cosa1);
                     s.re = (int)(128 + p0r.re + (p1r.re - p0r.re) * mu);
                     s.im = (int)(128 + p0r.im + (p1r.im - p0r.im) * mu);
                     symbol_arg = fast_arg(s);
 #endif
                     int quadrant = symbol_arg >> 14;
                     static unsigned char quadrant_to_symbol[4] = {0, 2, 3, 1};
                     *pout = quadrant_to_symbol[quadrant];
                     ++pout;
                     // PLL
                     s_angle phase_error = (s_angle)(symbol_arg & 16383) - 8192;
                     phase += (phase_error * freq_alpha + 32768) >> 16;
                     freqw += (phase_error * freq_beta + 32768 * 256) >> 24;
                     // Modified Mueller and Mller
                     // mu[k]=real((c[k]-c[k-2])*conj(p[k-1])-(p[k]-p[k-2])*conj(c[k-1]))
                     //      =dot(c[k]-c[k-2],p[k-1]) - dot(p[k]-p[k-2],c[k-1])
                     // p = received signals
                     // c = decisions (constellation points)
                     hist[2] = hist[1];
                     hist[1] = hist[0];
 #define HIST_FLOAT 0
 #if HIST_FLOAT
                     hist[0].p.re = (float)s.re - 128;
                     hist[0].p.im = (float)s.im - 128;
                     cu8 cp = arg_to_symbol((symbol_arg & 49152) + 8192);
                     hist[0].c.re = (float)cp.re - 128;
                     hist[0].c.im = (float)cp.im - 128;
                     float muerr =
                         ((hist[0].p.re - hist[2].p.re) * hist[1].c.re +
                          (hist[0].p.im - hist[2].p.im) * hist[1].c.im) -
                         ((hist[0].c.re - hist[2].c.re) * hist[1].p.re +
                          (hist[0].c.im - hist[2].c.im) * hist[1].p.im);
 #else
                     hist[0].p = s;
                     hist[0].c = arg_to_symbol((symbol_arg & 49152) + 8192);
                     int muerr =
                         ((signed char)(hist[0].p.re - hist[2].p.re) * ((int)hist[1].c.re - 128) + (signed char)(hist[0].p.im - hist[2].p.im) * ((int)hist[1].c.im - 128)) - ((signed char)(hist[0].c.re - hist[2].c.re) * ((int)hist[1].p.re - 128) + (signed char)(hist[0].c.im - hist[2].c.im) * ((int)hist[1].p.im - 128));
 #endif
                     float mucorr = muerr * gain_mu;
                     const float max_mucorr = 0.1;
                     // TBD Optimize out statically
                     if (mucorr < -max_mucorr)
                         mucorr = -max_mucorr;
                     if (mucorr > max_mucorr)
                         mucorr = max_mucorr;
                     mu += mucorr;
                     mu += omega; // Next symbol time;
                 }                // mu<1
                 // Next sample
                 ++pin;
                 --mu;
                 phase += freqw;
             } // chunk_size
             in.read(pin - pin0);
             out.written(pout - pout0);
             if (symbol_arg && cstln_out)
                 // Output the last interpolated PSK symbol, max once per chunk_size
                 cstln_out->write(s);
             // This is best done periodically ouside the inner loop,
             // but will cause non-deterministic output.
             if (!allow_drift)
             {
                 if (freqw < min_freqw || freqw > max_freqw)
                     freqw = (max_freqw + min_freqw) / 2;
             }
             // Output measurements
             meas_count += pin - pin0;
             while (meas_count >= meas_decimation)
             {
                 meas_count -= meas_decimation;
                 if (freq_out)
                     freq_out->write((float)freqw / 65536);
             }
         } // Work to do
     }
set_freq()
template<typename T > void leansdr::fast_qpsk_receiver< T >::set_freq (float freq) inline
Definition at line 1361 of file sdr.h.
     {
         freqw = freq * 65536;
         update_freq_limits();
     }
set_omega()
template<typename T > void leansdr::fast_qpsk_receiver< T >::set_omega (float _omega, float tol = 10e-6) inline
Definition at line 1353 of file sdr.h.
     {
         omega = _omega;
         min_omega = omega * (1 - tol);
         max_omega = omega * (1 + tol);
         update_freq_limits();
     }
update_freq_limits()
template<typename T > void leansdr::fast_qpsk_receiver< T >::update_freq_limits () inline
Definition at line 1367 of file sdr.h.
     {
         // Prevent PLL from locking at +-symbolrate/4.
         // TODO The +-SR/8 limit is suitable for QPSK only.
         min_freqw = freqw - 65536 / max_omega / 8;
         max_freqw = freqw + 65536 / max_omega / 8;
     }
Member Data Documentation
allow_drift
template<typename T > bool leansdr::fast_qpsk_receiver< T >::allow_drift
Definition at line 1328 of file sdr.h.
c
template<typename T > cu8 leansdr::fast_qpsk_receiver< T >::c
Definition at line 1587 of file sdr.h.
chunk_size
template<typename T > const unsigned int leansdr::fast_qpsk_receiver< T >::chunk_size = 128 static
Definition at line 1329 of file sdr.h.
cstln_out
template<typename T > pipewriter<cu8>* leansdr::fast_qpsk_receiver< T >::cstln_out private
Definition at line 1597 of file sdr.h.
freq_out
template<typename T > pipewriter<float>* leansdr::fast_qpsk_receiver< T >::freq_out private
Definition at line 1596 of file sdr.h.
freqw
template<typename T > signed long leansdr::fast_qpsk_receiver< T >::freqw
Definition at line 1326 of file sdr.h.
hist
struct { ... } leansdr::fast_qpsk_receiver< T >::hist[3]
in
template<typename T > pipereader<cu8> leansdr::fast_qpsk_receiver< T >::in private
Definition at line 1591 of file sdr.h.
lut_polar
template<typename T > struct leansdr::fast_qpsk_receiver::polar leansdr::fast_qpsk_receiver< T >::lut_polar[256][256] private
lut_rect
template<typename T > cu8 leansdr::fast_qpsk_receiver< T >::lut_rect[RLUT_ANGLES][256] private
Definition at line 1543 of file sdr.h.
lut_sincos
template<typename T > cu8 leansdr::fast_qpsk_receiver< T >::lut_sincos[65536] private
Definition at line 1544 of file sdr.h.
max_freqw
template<typename T > signed long leansdr::fast_qpsk_receiver< T >::max_freqw
Definition at line 1326 of file sdr.h.
max_omega
template<typename T > float leansdr::fast_qpsk_receiver< T >::max_omega
Definition at line 1325 of file sdr.h.
meas_count
template<typename T > unsigned long leansdr::fast_qpsk_receiver< T >::meas_count private
Definition at line 1595 of file sdr.h.
meas_decimation
template<typename T > unsigned long leansdr::fast_qpsk_receiver< T >::meas_decimation
Definition at line 1324 of file sdr.h.
mer_out
template<typename T > pipewriter<float> * leansdr::fast_qpsk_receiver< T >::mer_out private
Definition at line 1596 of file sdr.h.
min_freqw
template<typename T > signed long leansdr::fast_qpsk_receiver< T >::min_freqw
Definition at line 1326 of file sdr.h.
min_omega
template<typename T > float leansdr::fast_qpsk_receiver< T >::min_omega
Definition at line 1325 of file sdr.h.
mu
template<typename T > float leansdr::fast_qpsk_receiver< T >::mu private
Definition at line 1593 of file sdr.h.
omega
template<typename T > float leansdr::fast_qpsk_receiver< T >::omega
Definition at line 1325 of file sdr.h.
out
template<typename T > pipewriter<hardsymbol> leansdr::fast_qpsk_receiver< T >::out private
Definition at line 1592 of file sdr.h.
p
template<typename T > cu8 leansdr::fast_qpsk_receiver< T >::p
Definition at line 1586 of file sdr.h.
phase
template<typename T > u_angle leansdr::fast_qpsk_receiver< T >::phase private
Definition at line 1594 of file sdr.h.
pll_adjustment
template<typename T > float leansdr::fast_qpsk_receiver< T >::pll_adjustment
Definition at line 1327 of file sdr.h.
RLUT_ANGLES
template<typename T > const int leansdr::fast_qpsk_receiver< T >::RLUT_ANGLES = 1 << RLUT_BITS static
Definition at line 1376 of file sdr.h.
RLUT_BITS
template<typename T > const int leansdr::fast_qpsk_receiver< T >::RLUT_BITS = 8 static
Definition at line 1375 of file sdr.h.
The documentation for this struct was generated from the following file:
plugins/channelrx/demoddatv/leansdr/sdr.h