SDRAngel: AMBEWorker Class Reference
AMBEWorker Class Reference
#include <ambeworker.h>
Inherits QObject.
Classes
class MsgMbeDecode
class MsgTest
Public Slots
void handleInputMessages ()
Signals
void finished ()
Public Member Functions
AMBEWorker ()
~AMBEWorker ()
void pushMbeFrame (const unsigned char *mbeFrame, int mbeRateIndex, int mbeVolumeIndex, unsigned char channels, bool useHP, int upsampling, AudioFifo *audioFifo)
bool open (const std::string &deviceRef)
Either serial device or ip:port.
void close ()
void process ()
void stop ()
bool isAvailable ()
bool hasFifo (AudioFifo *audioFifo)
void postTest ()
Public Attributes
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
Private Member Functions
void upsample (int upsampling, short *in, int nbSamplesIn, unsigned char channels)
void noUpsample (short *in, int nbSamplesIn, unsigned char channels)
void setVolumeFactors ()
Private Attributes
SerialDV::DVController m_dvController
AudioFifo * m_audioFifo
QDateTime m_timestamp
volatile bool m_running
int m_currentGainIn
int m_currentGainOut
short m_dvAudioSamples [SerialDV::MBE_AUDIO_BLOCK_SIZE]
AudioVector m_audioBuffer
uint m_audioBufferFill
float m_upsamplerLastValue
float m_phase
MBEAudioInterpolatorFilter m_upsampleFilter
int m_upsampling
float m_volume
float m_upsamplingFactors [7]
AudioCompressor m_compressor
Detailed Description
Definition at line 37 of file ambeworker.h.
Constructor & Destructor Documentation
AMBEWorker()
AMBEWorker::AMBEWorker ()
Definition at line 29 of file ambeworker.cpp.
                        :
     m_running(false),
     m_currentGainIn(0),
     m_currentGainOut(0),
     m_upsamplerLastValue(0.0f),
     m_phase(0),
     m_upsampling(1),
     m_volume(1.0f)
 {
     m_audioBuffer.resize(48000);
     m_audioBufferFill = 0;
     m_audioFifo = 0;
     std::fill(m_dvAudioSamples, m_dvAudioSamples+SerialDV::MBE_AUDIO_BLOCK_SIZE, 0);
     setVolumeFactors();
 }
~AMBEWorker()
AMBEWorker::~AMBEWorker ()
Definition at line 45 of file ambeworker.cpp.
 {}
Member Function Documentation
close()
void AMBEWorker::close ()
Definition at line 53 of file ambeworker.cpp.
References m_dvController.
Referenced by AMBEEngine::scan().
 {
     m_dvController.close();
 }
finished
void AMBEWorker::finished () signal
Referenced by process().
handleInputMessages
void AMBEWorker::handleInputMessages () slot
Definition at line 77 of file ambeworker.cpp.
References MessageQueue::clear(), AMBEWorker::MsgMbeDecode::getAudioFifo(), AMBEWorker::MsgMbeDecode::getChannels(), AMBEWorker::MsgMbeDecode::getMbeFrame(), AMBEWorker::MsgMbeDecode::getMbeRate(), AMBEWorker::MsgMbeDecode::getUpsampling(), AMBEWorker::MsgMbeDecode::getUseHP(), AMBEWorker::MsgMbeDecode::getVolumeIndex(), m_audioBuffer, m_audioBufferFill, m_dvAudioSamples, m_dvController, m_inputMessageQueue, m_timestamp, m_upsampleFilter, m_upsampling, m_volume, Message::match(), noUpsample(), MessageQueue::pop(), setVolumeFactors(), MessageQueue::size(), upsample(), MBEAudioInterpolatorFilter::useHP(), and AudioFifo::write().
 {
     Message* message;
     m_audioBufferFill = 0;
     AudioFifo *audioFifo = 0;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (MsgMbeDecode::match(*message))
         {
             MsgMbeDecode *decodeMsg = (MsgMbeDecode *) message;
             int dBVolume = (decodeMsg->getVolumeIndex() - 30) / 4;
             float volume = pow(10.0, dBVolume / 10.0f);
             int upsampling = decodeMsg->getUpsampling();
             upsampling = upsampling > 6 ? 6 : upsampling < 1 ? 1 : upsampling;
             if ((volume != m_volume) || (upsampling != m_upsampling))
             {
                 m_volume = volume;
                 m_upsampling = upsampling;
                 setVolumeFactors();
             }
             m_upsampleFilter.useHP(decodeMsg->getUseHP());
             if (m_dvController.decode(m_dvAudioSamples, decodeMsg->getMbeFrame(), decodeMsg->getMbeRate()))
             {
                 if (upsampling > 1) {
                     upsample(upsampling, m_dvAudioSamples, SerialDV::MBE_AUDIO_BLOCK_SIZE, decodeMsg->getChannels());
                 } else {
                     noUpsample(m_dvAudioSamples, SerialDV::MBE_AUDIO_BLOCK_SIZE, decodeMsg->getChannels());
                 }
                 audioFifo = decodeMsg->getAudioFifo();
                 if (audioFifo && (m_audioBufferFill >= m_audioBuffer.size() - 960))
                 {
                     uint res = audioFifo->write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
                     if (res != m_audioBufferFill) {
                         qDebug("AMBEWorker::handleInputMessages: %u/%u audio samples written", res, m_audioBufferFill);
                     }
                     m_audioBufferFill = 0;
                 }
             }
             else
             {
                 qDebug("AMBEWorker::handleInputMessages: MsgMbeDecode: decode failed");
             }
         }
         delete message;
         if (m_inputMessageQueue.size() > 100)
         {
             qDebug("AMBEWorker::handleInputMessages: MsgMbeDecode: too many messages in queue. Flushing...");
             m_inputMessageQueue.clear();
             break;
         }
     }
     if (audioFifo)
     {
         uint res = audioFifo->write((const quint8*)&m_audioBuffer[0], m_audioBufferFill);
         if (res != m_audioBufferFill) {
             qDebug("AMBEWorker::handleInputMessages: %u/%u audio samples written", res, m_audioBufferFill);
         }
         m_audioBufferFill = 0;
     }
     m_timestamp = QDateTime::currentDateTime();
 }
hasFifo()
bool AMBEWorker::hasFifo (AudioFifo * audioFifo)
Definition at line 174 of file ambeworker.cpp.
References m_audioFifo.
 {
     return m_audioFifo == audioFifo;
 }
isAvailable()
bool AMBEWorker::isAvailable ()
Definition at line 165 of file ambeworker.cpp.
References m_audioFifo, and m_timestamp.
 {
     if (m_audioFifo == 0) {
         return true;
     }
     return m_timestamp.time().msecsTo(QDateTime::currentDateTime().time()) > 1000; // 1 second inactivity timeout
 }
noUpsample()
void AMBEWorker::noUpsample (short * in, int nbSamplesIn, unsigned char channels) private
Definition at line 207 of file ambeworker.cpp.
References i, m_audioBuffer, m_audioBufferFill, m_upsampleFilter, m_upsamplingFactors, MBEAudioInterpolatorFilter::runHP(), and MBEAudioInterpolatorFilter::usesHP().
Referenced by handleInputMessages().
 {
     for (int i = 0; i < nbSamplesIn; i++)
     {
         float cur = m_upsampleFilter.usesHP() ? m_upsampleFilter.runHP((float) in[i]) : (float) in[i];
         m_audioBuffer[m_audioBufferFill].l = channels & 1 ? cur*m_upsamplingFactors[0] : 0;
         m_audioBuffer[m_audioBufferFill].r = (channels>>1) & 1 ? cur*m_upsamplingFactors[0] : 0;
         if (m_audioBufferFill < m_audioBuffer.size() - 1) {
             ++m_audioBufferFill;
         }
     }
     if (m_audioBufferFill >= m_audioBuffer.size() - 1) {
         qDebug("AMBEWorker::noUpsample: audio buffer is full check its size");
     }
 }
open()
bool AMBEWorker::open (const std::string & deviceRef)
Either serial device or ip:port.
Definition at line 48 of file ambeworker.cpp.
References m_dvController.
Referenced by AMBEEngine::registerController(), and AMBEEngine::scan().
 {
     return m_dvController.open(deviceRef);
 }
postTest()
void AMBEWorker::postTest () inline
Definition at line 119 of file ambeworker.h.
References SWGSDRangel::create().
     {
         //emit inputMessageReady();
         m_inputMessageQueue.push(MsgTest::create());
     }
process()
void AMBEWorker::process ()
Definition at line 58 of file ambeworker.cpp.
References finished(), and m_running.
 {
     m_running  = true;
     qDebug("AMBEWorker::process: started");
     while (m_running)
     {
         std::this_thread::sleep_for(std::chrono::seconds(1));
     }
     qDebug("AMBEWorker::process: stopped");
     emit finished();
 }
pushMbeFrame()
void AMBEWorker::pushMbeFrame (const unsigned char * mbeFrame, int mbeRateIndex, int mbeVolumeIndex, unsigned char channels, bool useHP, int upsampling, AudioFifo * audioFifo)
Definition at line 153 of file ambeworker.cpp.
References AMBEWorker::MsgMbeDecode::create(), m_audioFifo, m_inputMessageQueue, and MessageQueue::push().
 {
     m_audioFifo = audioFifo;
     m_inputMessageQueue.push(MsgMbeDecode::create(mbeFrame, mbeRateIndex, mbeVolumeIndex, channels, useHP, upsampling, audioFifo));
 }
setVolumeFactors()
void AMBEWorker::setVolumeFactors () private
Definition at line 225 of file ambeworker.cpp.
References i, m_upsampling, m_upsamplingFactors, and m_volume.
Referenced by handleInputMessages().
 {
     m_upsamplingFactors[0] = m_volume;
     for (int i = 1; i <= m_upsampling; i++) {
         m_upsamplingFactors[i] = (i*m_volume) / (float) m_upsampling;
     }
 }
stop()
void AMBEWorker::stop ()
Definition at line 72 of file ambeworker.cpp.
References m_running.
 {
     m_running = false;
 }
upsample()
void AMBEWorker::upsample (int upsampling, short * in, int nbSamplesIn, unsigned char channels) private
Definition at line 179 of file ambeworker.cpp.
References AudioCompressor::compress(), i, m_audioBuffer, m_audioBufferFill, m_compressor, m_upsampleFilter, m_upsamplerLastValue, m_upsamplingFactors, MBEAudioInterpolatorFilter::runHP(), MBEAudioInterpolatorFilter::runLP(), and MBEAudioInterpolatorFilter::usesHP().
Referenced by handleInputMessages().
 {
     for (int i = 0; i < nbSamplesIn; i++)
     {
         //float cur = m_upsampleFilter.usesHP() ? m_upsampleFilter.runHP((float) m_compressor.compress(in[i])) : (float) m_compressor.compress(in[i]);
         float cur = m_upsampleFilter.usesHP() ? m_upsampleFilter.runHP((float) in[i]) : (float) in[i];
         float prev = m_upsamplerLastValue;
         qint16 upsample;
         for (int j = 1; j <= upsampling; j++)
         {
             upsample = (qint16) m_upsampleFilter.runLP(cur*m_upsamplingFactors[j] + prev*m_upsamplingFactors[upsampling-j]);
             m_audioBuffer[m_audioBufferFill].l = channels & 1 ? m_compressor.compress(upsample) : 0;
             m_audioBuffer[m_audioBufferFill].r = (channels>>1) & 1 ? m_compressor.compress(upsample) : 0;
             if (m_audioBufferFill < m_audioBuffer.size() - 1) {
                 ++m_audioBufferFill;
             }
         }
         m_upsamplerLastValue = cur;
     }
     if (m_audioBufferFill >= m_audioBuffer.size() - 1) {
         qDebug("AMBEWorker::upsample(%d): audio buffer is full check its size", upsampling);
     }
 }
Member Data Documentation
m_audioBuffer
AudioVector AMBEWorker::m_audioBuffer private
Definition at line 145 of file ambeworker.h.
Referenced by handleInputMessages(), noUpsample(), and upsample().
m_audioBufferFill
uint AMBEWorker::m_audioBufferFill private
Definition at line 146 of file ambeworker.h.
Referenced by handleInputMessages(), noUpsample(), and upsample().
m_audioFifo
AudioFifo* AMBEWorker::m_audioFifo private
Definition at line 139 of file ambeworker.h.
Referenced by hasFifo(), isAvailable(), and pushMbeFrame().
m_compressor
AudioCompressor AMBEWorker::m_compressor private
Definition at line 153 of file ambeworker.h.
Referenced by upsample().
m_currentGainIn
int AMBEWorker::m_currentGainIn private
Definition at line 142 of file ambeworker.h.
m_currentGainOut
int AMBEWorker::m_currentGainOut private
Definition at line 143 of file ambeworker.h.
m_dvAudioSamples
short AMBEWorker::m_dvAudioSamples[SerialDV::MBE_AUDIO_BLOCK_SIZE] private
Definition at line 144 of file ambeworker.h.
Referenced by handleInputMessages().
m_dvController
SerialDV::DVController AMBEWorker::m_dvController private
Definition at line 138 of file ambeworker.h.
Referenced by close(), handleInputMessages(), and open().
m_inputMessageQueue
MessageQueue AMBEWorker::m_inputMessageQueue
Queue for asynchronous inbound communication.
Definition at line 125 of file ambeworker.h.
Referenced by handleInputMessages(), and pushMbeFrame().
m_phase
float AMBEWorker::m_phase private
Definition at line 148 of file ambeworker.h.
m_running
volatile bool AMBEWorker::m_running private
Definition at line 141 of file ambeworker.h.
Referenced by process(), and stop().
m_timestamp
QDateTime AMBEWorker::m_timestamp private
Definition at line 140 of file ambeworker.h.
Referenced by handleInputMessages(), and isAvailable().
m_upsampleFilter
MBEAudioInterpolatorFilter AMBEWorker::m_upsampleFilter private
Definition at line 149 of file ambeworker.h.
Referenced by handleInputMessages(), noUpsample(), and upsample().
m_upsamplerLastValue
float AMBEWorker::m_upsamplerLastValue private
Definition at line 147 of file ambeworker.h.
Referenced by upsample().
m_upsampling
int AMBEWorker::m_upsampling private
Definition at line 150 of file ambeworker.h.
Referenced by handleInputMessages(), and setVolumeFactors().
m_upsamplingFactors
float AMBEWorker::m_upsamplingFactors[7] private
Definition at line 152 of file ambeworker.h.
Referenced by noUpsample(), setVolumeFactors(), and upsample().
m_volume
float AMBEWorker::m_volume private
Definition at line 151 of file ambeworker.h.
Referenced by handleInputMessages(), and setVolumeFactors().
The documentation for this class was generated from the following files:
sdrbase/ambe/ambeworker.h
sdrbase/ambe/ambeworker.cpp