SDRAngel: SpectrumVis Class Reference
SpectrumVis Class Reference
#include <spectrumvis.h>
Classes
class MsgConfigureSpectrumVis
Public Types
enum AvgMode { AvgModeNone, AvgModeMovingAvg, AvgModeFixedAvg, AvgModeMax }
Public Member Functions
SpectrumVis (Real scalef, GLSpectrum *glSpectrum=0)
virtual ~SpectrumVis ()
void configure (MessageQueue *msgQueue, int fftSize, int overlapPercent, unsigned int averagingNb, int averagingMode, FFTWindow::Function window, bool m_linear)
virtual void feed (const SampleVector::const_iterator &begin, const SampleVector::const_iterator &end, bool positiveOnly)
void feedTriggered (const SampleVector::const_iterator &triggerPoint, const SampleVector::const_iterator &end, bool positiveOnly)
virtual void start ()
virtual void stop ()
virtual bool handleMessage (const Message &message)
Processing of a message. Returns true if message has actually been processed.
Public Member Functions inherited from BasebandSampleSink
BasebandSampleSink ()
virtual ~BasebandSampleSink ()
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
Private Member Functions
void handleConfigure (int fftSize, int overlapPercent, unsigned int averageNb, AvgMode averagingMode, FFTWindow::Function window, bool linear)
Private Attributes
FFTEngine * m_fft
FFTWindow m_window
std::vector< Complex > m_fftBuffer
std::vector< Real > m_powerSpectrum
std::size_t m_fftSize
std::size_t m_overlapPercent
std::size_t m_overlapSize
std::size_t m_refillSize
std::size_t m_fftBufferFill
bool m_needMoreSamples
Real m_scalef
GLSpectrum * m_glSpectrum
MovingAverage2D< double > m_movingAverage
FixedAverage2D< double > m_fixedAverage
Max2D< double > m_max
unsigned int m_averageNb
AvgMode m_avgMode
bool m_linear
Real m_ofs
Real m_powFFTDiv
QMutex m_mutex
Static Private Attributes
static const Real m_mult = (10.0f / log2f(10.0f))
Additional Inherited Members
Protected Slots inherited from BasebandSampleSink
void handleInputMessages ()
Protected Attributes inherited from BasebandSampleSink
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 17 of file spectrumvis.h.
Member Enumeration Documentation
AvgMode
enum SpectrumVis::AvgMode
Enumerator
AvgModeNone
AvgModeMovingAvg
AvgModeFixedAvg
AvgModeMax
Definition at line 20 of file spectrumvis.h.
     {
         AvgModeNone,
         AvgModeMovingAvg,
         AvgModeFixedAvg,
         AvgModeMax
     };
Constructor & Destructor Documentation
SpectrumVis()
SpectrumVis::SpectrumVis (Real scalef, GLSpectrum * glSpectrum = 0)
Definition at line 19 of file spectrumvis.cpp.
References AvgModeNone, FFTWindow::BlackmanHarris, and handleConfigure().
                                                             :
     BasebandSampleSink(),
     m_fft(FFTEngine::create()),
     m_fftBuffer(MAX_FFT_SIZE),
     m_powerSpectrum(MAX_FFT_SIZE),
     m_fftBufferFill(0),
     m_needMoreSamples(false),
     m_scalef(scalef),
     m_glSpectrum(glSpectrum),
     m_averageNb(0),
     m_avgMode(AvgModeNone),
     m_linear(false),
     m_ofs(0),
     m_powFFTDiv(1.0),
     m_mutex(QMutex::Recursive)
 {
     setObjectName("SpectrumVis");
     handleConfigure(1024, 0, 0, AvgModeNone, FFTWindow::BlackmanHarris, false);
 }
~SpectrumVis()
SpectrumVis::~SpectrumVis () virtual
Definition at line 39 of file spectrumvis.cpp.
References m_fft.
 {
     delete m_fft;
 }
Member Function Documentation
configure()
void SpectrumVis::configure (MessageQueue * msgQueue, int fftSize, int overlapPercent, unsigned int averagingNb, int averagingMode, FFTWindow::Function window, bool m_linear)
Definition at line 44 of file spectrumvis.cpp.
References MessageQueue::push().
Referenced by GLSpectrumGUI::applySettings(), BFMDemodGUI::BFMDemodGUI(), GLSpectrumGUI::on_averaging_currentIndexChanged(), GLSpectrumGUI::on_averagingMode_currentIndexChanged(), GLSpectrumGUI::on_fftSize_currentIndexChanged(), GLSpectrumGUI::on_fftWindow_currentIndexChanged(), GLSpectrumGUI::on_linscale_toggled(), UDPSinkGUI::UDPSinkGUI(), and UDPSourceGUI::UDPSourceGUI().
 {
     MsgConfigureSpectrumVis* cmd = new MsgConfigureSpectrumVis(fftSize, overlapPercent, averagingNb, averagingMode, window, linear);
     msgQueue->push(cmd);
 }
feed()
void SpectrumVis::feed (const SampleVector::const_iterator & begin, const SampleVector::const_iterator & end, bool positiveOnly) virtual
Implements BasebandSampleSink.
Definition at line 77 of file spectrumvis.cpp.
References FFTWindow::apply(), AvgModeFixedAvg, AvgModeMax, AvgModeMovingAvg, AvgModeNone, i, FFTEngine::in(), log2f(), m_avgMode, m_fft, m_fftBuffer, m_fftBufferFill, m_fftSize, m_fixedAverage, m_glSpectrum, m_linear, m_max, m_movingAverage, m_mult, m_mutex, m_needMoreSamples, m_ofs, m_overlapSize, m_powerSpectrum, m_powFFTDiv, m_refillSize, m_scalef, m_window, leansdr::max(), GLSpectrum::newSpectrum(), FixedAverage2D< T >::nextAverage(), MovingAverage2D< T >::nextAverage(), Max2D< T >::nextMax(), FFTEngine::out(), FixedAverage2D< T >::storeAndGetAvg(), MovingAverage2D< T >::storeAndGetAvg(), Max2D< T >::storeAndGetMax(), and FFTEngine::transform().
Referenced by feedTriggered().
 {
     // if no visualisation is set, send the samples to /dev/null
     if (m_glSpectrum == 0) {
         return;
     }
     if (!m_mutex.tryLock(0)) { // prevent conflicts with configuration process
         return;
     }
     SampleVector::const_iterator begin(cbegin);
     while (begin < end)
     {
         std::size_t todo = end - begin;
         std::size_t samplesNeeded = m_refillSize - m_fftBufferFill;
         if (todo >= samplesNeeded)
         {
             // fill up the buffer
             std::vector<Complex>::iterator it = m_fftBuffer.begin() + m_fftBufferFill;
             for (std::size_t i = 0; i < samplesNeeded; ++i, ++begin)
             {
                 *it++ = Complex(begin->real() / m_scalef, begin->imag() / m_scalef);
             }
             // apply fft window (and copy from m_fftBuffer to m_fftIn)
             m_window.apply(&m_fftBuffer[0], m_fft->in());
             // calculate FFT
             m_fft->transform();
             // extract power spectrum and reorder buckets
             const Complex* fftOut = m_fft->out();
             Complex c;
             Real v;
             std::size_t halfSize = m_fftSize / 2;
             if (m_avgMode == AvgModeNone)
             {
                 if ( positiveOnly )
                 {
                     for (std::size_t i = 0; i < halfSize; i++)
                     {
                         c = fftOut[i];
                         v = c.real() * c.real() + c.imag() * c.imag();
                         v = m_linear ? v/m_powFFTDiv : m_mult * log2f(v) + m_ofs;
                         m_powerSpectrum[i * 2] = v;
                         m_powerSpectrum[i * 2 + 1] = v;
                     }
                 }
                 else
                 {
                     for (std::size_t i = 0; i < halfSize; i++)
                     {
                         c = fftOut[i + halfSize];
                         v = c.real() * c.real() + c.imag() * c.imag();
                         v = m_linear ? v/m_powFFTDiv : m_mult * log2f(v) + m_ofs;
                         m_powerSpectrum[i] = v;
                         c = fftOut[i];
                         v = c.real() * c.real() + c.imag() * c.imag();
                         v = m_linear ? v/m_powFFTDiv : m_mult * log2f(v) + m_ofs;
                         m_powerSpectrum[i + halfSize] = v;
                     }
                 }
                 // send new data to visualisation
                 m_glSpectrum->newSpectrum(m_powerSpectrum, m_fftSize);
             }
             else if (m_avgMode == AvgModeMovingAvg)
             {
                 if ( positiveOnly )
                 {
                     for (std::size_t i = 0; i < halfSize; i++)
                     {
                         c = fftOut[i];
                         v = c.real() * c.real() + c.imag() * c.imag();
                         v = m_movingAverage.storeAndGetAvg(v, i);
                         v = m_linear ? v/m_powFFTDiv : m_mult * log2f(v) + m_ofs;
                         m_powerSpectrum[i * 2] = v;
                         m_powerSpectrum[i * 2 + 1] = v;
                     }
                 }
                 else
                 {
                     for (std::size_t i = 0; i < halfSize; i++)
                     {
                         c = fftOut[i + halfSize];
                         v = c.real() * c.real() + c.imag() * c.imag();
                         v = m_movingAverage.storeAndGetAvg(v, i+halfSize);
                         v = m_linear ? v/m_powFFTDiv : m_mult * log2f(v) + m_ofs;
                         m_powerSpectrum[i] = v;
                         c = fftOut[i];
                         v = c.real() * c.real() + c.imag() * c.imag();
                         v = m_movingAverage.storeAndGetAvg(v, i);
                         v = m_linear ? v/m_powFFTDiv : m_mult * log2f(v) + m_ofs;
                         m_powerSpectrum[i + halfSize] = v;
                     }
                 }
                 // send new data to visualisation
                 m_glSpectrum->newSpectrum(m_powerSpectrum, m_fftSize);
                 m_movingAverage.nextAverage();
             }
             else if (m_avgMode == AvgModeFixedAvg)
             {
                 double avg;
                 if ( positiveOnly )
                 {
                     for (std::size_t i = 0; i < halfSize; i++)
                     {
                         c = fftOut[i];
                         v = c.real() * c.real() + c.imag() * c.imag();
                         if (m_fixedAverage.storeAndGetAvg(avg, v, i))
{
                             avg = m_linear ? avg/m_powFFTDiv : m_mult * log2f(avg) + m_ofs;
                             m_powerSpectrum[i * 2] = avg;
                             m_powerSpectrum[i * 2 + 1] = avg;
                         }
                     }
                 }
                 else
                 {
                     for (std::size_t i = 0; i < halfSize; i++)
                     {
                         c = fftOut[i + halfSize];
                         v = c.real() * c.real() + c.imag() * c.imag();
                         if (m_fixedAverage.storeAndGetAvg(avg, v, i+halfSize))
                         { // result available
                             avg = m_linear ? avg/m_powFFTDiv : m_mult * log2f(avg) + m_ofs;
                             m_powerSpectrum[i] = avg;
                         }
                         c = fftOut[i];
                         v = c.real() * c.real() + c.imag() * c.imag();
                         if (m_fixedAverage.storeAndGetAvg(avg, v, i))
                         { // result available
                             avg = m_linear ? avg/m_powFFTDiv : m_mult * log2f(avg) + m_ofs;
                             m_powerSpectrum[i + halfSize] = avg;
                         }
                     }
                 }
                 if (m_fixedAverage.nextAverage()) { // result available
                     m_glSpectrum->newSpectrum(m_powerSpectrum, m_fftSize); // send new data to visualisation
                 }
             }
             else if (m_avgMode == AvgModeMax)
             {
                 double max;
                 if ( positiveOnly )
                 {
                     for (std::size_t i = 0; i < halfSize; i++)
                     {
                         c = fftOut[i];
                         v = c.real() * c.real() + c.imag() * c.imag();
                         if (m_max.storeAndGetMax(max, v, i))
{
                             max = m_linear ? max/m_powFFTDiv : m_mult * log2f(max) + m_ofs;
                             m_powerSpectrum[i * 2] = max;
                             m_powerSpectrum[i * 2 + 1] = max;
                         }
                     }
                 }
                 else
                 {
                     for (std::size_t i = 0; i < halfSize; i++)
                     {
                         c = fftOut[i + halfSize];
                         v = c.real() * c.real() + c.imag() * c.imag();
                         if (m_max.storeAndGetMax(max, v, i+halfSize))
                         { // result available
                             max = m_linear ? max/m_powFFTDiv : m_mult * log2f(max) + m_ofs;
                             m_powerSpectrum[i] = max;
                         }
                         c = fftOut[i];
                         v = c.real() * c.real() + c.imag() * c.imag();
                         if (m_max.storeAndGetMax(max, v, i))
                         { // result available
                             max = m_linear ? max/m_powFFTDiv : m_mult * log2f(max) + m_ofs;
                             m_powerSpectrum[i + halfSize] = max;
                         }
                     }
                 }
                 if (m_max.nextMax()) { // result available
                     m_glSpectrum->newSpectrum(m_powerSpectrum, m_fftSize); // send new data to visualisation
                 }
             }
             // advance buffer respecting the fft overlap factor
             std::copy(m_fftBuffer.begin() + m_refillSize, m_fftBuffer.end(), m_fftBuffer.begin());
             // start over
             m_fftBufferFill = m_overlapSize;
             m_needMoreSamples = false;
         }
         else
         {
             // not enough samples for FFT - just fill in new data and return
             for(std::vector<Complex>::iterator it = m_fftBuffer.begin() + m_fftBufferFill; begin < end; ++begin)
             {
                 *it++ = Complex(begin->real() / m_scalef, begin->imag() / m_scalef);
             }
             m_fftBufferFill += todo;
             m_needMoreSamples = true;
         }
     }
      m_mutex.unlock();
 }
feedTriggered()
void SpectrumVis::feedTriggered (const SampleVector::const_iterator & triggerPoint, const SampleVector::const_iterator & end, bool positiveOnly)
Definition at line 56 of file spectrumvis.cpp.
References feed().
Referenced by SpectrumScopeComboVis::feed().
 {
     feed(triggerPoint, end, positiveOnly); // normal feed from trigger point
     /*
     if (triggerPoint == end)
     {
         // the following piece of code allows to terminate the FFT that ends past the end of scope captured data
         // that is the spectrum will include the captured data
         // just do nothing if you want the spectrum to be included inside the scope captured data
         // that is to drop the FFT that dangles past the end of captured data
         if (m_needMoreSamples) {
             feed(begin, end, positiveOnly);
             m_needMoreSamples = false;      // force finish
         }
     }
     else
     {
         feed(triggerPoint, end, positiveOnly); // normal feed from trigger point
     }*/
 }
handleConfigure()
void SpectrumVis::handleConfigure (int fftSize, int overlapPercent, unsigned int averageNb, AvgMode averagingMode, FFTWindow::Function window, bool linear) private
Definition at line 331 of file spectrumvis.cpp.
References FFTEngine::configure(), FFTWindow::create(), m_averageNb, m_avgMode, m_fft, m_fftBufferFill, m_fftSize, m_fixedAverage, m_linear, m_max, m_movingAverage, m_mutex, m_ofs, m_overlapPercent, m_overlapSize, m_powFFTDiv, m_refillSize, m_window, MAX_FFT_SIZE, Max2D< T >::resize(), FixedAverage2D< T >::resize(), and MovingAverage2D< T >::resize().
Referenced by handleMessage(), and SpectrumVis().
 {
 //    qDebug("SpectrumVis::handleConfigure, fftSize: %d overlapPercent: %d averageNb: %u averagingMode: %d window: %d linear: %s",
 //            fftSize, overlapPercent, averageNb, (int) averagingMode, (int) window, linear ? "true" : "false");
     QMutexLocker mutexLocker(&m_mutex);
     if (fftSize > MAX_FFT_SIZE)
     {
         fftSize = MAX_FFT_SIZE;
     }
     else if (fftSize < 64)
     {
         fftSize = 64;
     }
     if (overlapPercent > 100)
     {
         m_overlapPercent = 100;
     }
     else if (overlapPercent < 0)
     {
         m_overlapPercent = 0;
     }
     else
     {
         m_overlapPercent = overlapPercent;
     }
     m_fftSize = fftSize;
     m_fft->configure(m_fftSize, false);
     m_window.create(window, m_fftSize);
     m_overlapSize = (m_fftSize * m_overlapPercent) / 100;
     m_refillSize = m_fftSize - m_overlapSize;
     m_fftBufferFill = m_overlapSize;
     m_movingAverage.resize(fftSize, averageNb > 1000 ? 1000 : averageNb); // Capping to avoid out of memory condition
     m_fixedAverage.resize(fftSize, averageNb);
     m_max.resize(fftSize, averageNb);
     m_averageNb = averageNb;
     m_avgMode = averagingMode;
     m_linear = linear;
     m_ofs = 20.0f * log10f(1.0f / m_fftSize);
     m_powFFTDiv = m_fftSize*m_fftSize;
 }
handleMessage()
bool SpectrumVis::handleMessage (const Message & cmd) virtual
Processing of a message. Returns true if message has actually been processed.
Implements BasebandSampleSink.
Definition at line 312 of file spectrumvis.cpp.
References SpectrumVis::MsgConfigureSpectrumVis::getAverageNb(), SpectrumVis::MsgConfigureSpectrumVis::getAvgMode(), SpectrumVis::MsgConfigureSpectrumVis::getFFTSize(), SpectrumVis::MsgConfigureSpectrumVis::getLinear(), SpectrumVis::MsgConfigureSpectrumVis::getOverlapPercent(), SpectrumVis::MsgConfigureSpectrumVis::getWindow(), handleConfigure(), and Message::match().
Referenced by SpectrumScopeComboVis::handleMessage().
 {
     if (MsgConfigureSpectrumVis::match(message))
     {
         MsgConfigureSpectrumVis& conf = (MsgConfigureSpectrumVis&) message;
         handleConfigure(conf.getFFTSize(),
                 conf.getOverlapPercent(),
                 conf.getAverageNb(),
                 conf.getAvgMode(),
                 conf.getWindow(),
                 conf.getLinear());
         return true;
     }
     else
     {
         return false;
     }
 }
start()
void SpectrumVis::start () virtual
Implements BasebandSampleSink.
Definition at line 304 of file spectrumvis.cpp.
Referenced by SpectrumScopeComboVis::start().
 {
 }
stop()
void SpectrumVis::stop () virtual
Implements BasebandSampleSink.
Definition at line 308 of file spectrumvis.cpp.
Referenced by SpectrumScopeComboVis::stop().
 {
 }
Member Data Documentation
m_averageNb
unsigned int SpectrumVis::m_averageNb private
Definition at line 101 of file spectrumvis.h.
Referenced by handleConfigure().
m_avgMode
AvgMode SpectrumVis::m_avgMode private
Definition at line 102 of file spectrumvis.h.
Referenced by feed(), and handleConfigure().
m_fft
FFTEngine* SpectrumVis::m_fft private
Definition at line 83 of file spectrumvis.h.
Referenced by feed(), handleConfigure(), and ~SpectrumVis().
m_fftBuffer
std::vector<Complex> SpectrumVis::m_fftBuffer private
Definition at line 86 of file spectrumvis.h.
Referenced by feed().
m_fftBufferFill
std::size_t SpectrumVis::m_fftBufferFill private
Definition at line 93 of file spectrumvis.h.
Referenced by feed(), and handleConfigure().
m_fftSize
std::size_t SpectrumVis::m_fftSize private
Definition at line 89 of file spectrumvis.h.
Referenced by feed(), and handleConfigure().
m_fixedAverage
FixedAverage2D<double> SpectrumVis::m_fixedAverage private
Definition at line 99 of file spectrumvis.h.
Referenced by feed(), and handleConfigure().
m_glSpectrum
GLSpectrum* SpectrumVis::m_glSpectrum private
Definition at line 97 of file spectrumvis.h.
Referenced by feed().
m_linear
bool SpectrumVis::m_linear private
Definition at line 103 of file spectrumvis.h.
Referenced by feed(), and handleConfigure().
m_max
Max2D<double> SpectrumVis::m_max private
Definition at line 100 of file spectrumvis.h.
Referenced by feed(), and handleConfigure().
m_movingAverage
MovingAverage2D<double> SpectrumVis::m_movingAverage private
Definition at line 98 of file spectrumvis.h.
Referenced by feed(), and handleConfigure().
m_mult
const Real SpectrumVis::m_mult = (10.0f / log2f(10.0f)) static private
Definition at line 107 of file spectrumvis.h.
Referenced by feed(), and log2f().
m_mutex
QMutex SpectrumVis::m_mutex private
Definition at line 109 of file spectrumvis.h.
Referenced by feed(), and handleConfigure().
m_needMoreSamples
bool SpectrumVis::m_needMoreSamples private
Definition at line 94 of file spectrumvis.h.
Referenced by feed().
m_ofs
Real SpectrumVis::m_ofs private
Definition at line 105 of file spectrumvis.h.
Referenced by feed(), and handleConfigure().
m_overlapPercent
std::size_t SpectrumVis::m_overlapPercent private
Definition at line 90 of file spectrumvis.h.
Referenced by handleConfigure().
m_overlapSize
std::size_t SpectrumVis::m_overlapSize private
Definition at line 91 of file spectrumvis.h.
Referenced by feed(), and handleConfigure().
m_powerSpectrum
std::vector<Real> SpectrumVis::m_powerSpectrum private
Definition at line 87 of file spectrumvis.h.
Referenced by feed().
m_powFFTDiv
Real SpectrumVis::m_powFFTDiv private
Definition at line 106 of file spectrumvis.h.
Referenced by feed(), and handleConfigure().
m_refillSize
std::size_t SpectrumVis::m_refillSize private
Definition at line 92 of file spectrumvis.h.
Referenced by feed(), and handleConfigure().
m_scalef
Real SpectrumVis::m_scalef private
Definition at line 96 of file spectrumvis.h.
Referenced by feed().
m_window
FFTWindow SpectrumVis::m_window private
Definition at line 84 of file spectrumvis.h.
Referenced by feed(), and handleConfigure().
The documentation for this class was generated from the following files:
sdrgui/dsp/spectrumvis.h
sdrgui/dsp/spectrumvis.cpp