SDRAngel: SWGSDRangel::SWGComplex Class Reference
SWGSDRangel::SWGComplex Class Reference
#include <SWGComplex.h>
Public Member Functions
SWGComplex ()
SWGComplex (QString *json)
virtual ~SWGComplex ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGComplex * fromJson (QString &jsonString) override
float getReal ()
void setReal (float real)
float getImag ()
void setImag (float imag)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
float real
bool m_real_isSet
float imag
bool m_imag_isSet
Detailed Description
Definition at line 31 of file SWGComplex.h.
Constructor & Destructor Documentation
SWGComplex() [1/2]
SWGSDRangel::SWGComplex::SWGComplex ()
Definition at line 30 of file SWGComplex.cpp.
References imag, m_imag_isSet, m_real_isSet, and real.
{
     real = 0.0f;
     m_real_isSet = false;
     imag = 0.0f;
     m_imag_isSet = false;
 }
SWGComplex() [2/2]
SWGSDRangel::SWGComplex::SWGComplex (QString * json)
Definition at line 25 of file SWGComplex.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGComplex()
SWGSDRangel::SWGComplex::~SWGComplex () virtual
Definition at line 37 of file SWGComplex.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGComplex::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 73 of file SWGComplex.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGComplex::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 84 of file SWGComplex.cpp.
References imag, m_imag_isSet, m_real_isSet, and real.
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_real_isSet){
         obj->insert("real", QJsonValue(real));
     }
     if(m_imag_isSet){
         obj->insert("imag", QJsonValue(imag));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGComplex::cleanup ()
Definition at line 50 of file SWGComplex.cpp.
Referenced by ~SWGComplex().
                     {
 }
fromJson()
SWGComplex * SWGSDRangel::SWGComplex::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 56 of file SWGComplex.cpp.
References fromJsonObject().
Referenced by SWGComplex().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGComplex::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 65 of file SWGComplex.cpp.
References imag, real, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&real, pJson["real"], "float", "");
     ::SWGSDRangel::setValue(&imag, pJson["imag"], "float", "");
 }
getImag()
float SWGSDRangel::SWGComplex::getImag ()
Definition at line 107 of file SWGComplex.cpp.
References imag.
Referenced by SoapySDROutput::webapiSettingsPutPatch(), and SoapySDRInput::webapiSettingsPutPatch().
                     {
     return imag;
 }
getReal()
float SWGSDRangel::SWGComplex::getReal ()
Definition at line 97 of file SWGComplex.cpp.
References real.
Referenced by SoapySDROutput::webapiSettingsPutPatch(), and SoapySDRInput::webapiSettingsPutPatch().
                     {
     return real;
 }
init()
void SWGSDRangel::SWGComplex::init ()
Definition at line 42 of file SWGComplex.cpp.
References imag, m_imag_isSet, m_real_isSet, and real.
Referenced by SWGComplex().
                  {
     real = 0.0f;
     m_real_isSet = false;
     imag = 0.0f;
     m_imag_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGComplex::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 118 of file SWGComplex.cpp.
References m_imag_isSet, and m_real_isSet.
Referenced by SWGSDRangel::SWGSoapySDRInputSettings::asJsonObject(), SWGSDRangel::SWGSoapySDROutputSettings::asJsonObject(), SWGSDRangel::SWGSoapySDROutputSettings::isSet(), and SWGSDRangel::SWGSoapySDRInputSettings::isSet().
                  {
     bool isObjectUpdated = false;
     do{
         if(m_real_isSet){ isObjectUpdated = true; break;}
         if(m_imag_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setImag()
void SWGSDRangel::SWGComplex::setImag (float imag)
Definition at line 111 of file SWGComplex.cpp.
References imag, and m_imag_isSet.
Referenced by SoapySDROutput::webapiFormatDeviceSettings(), SoapySDRInput::webapiFormatDeviceSettings(), SoapySDROutput::webapiReverseSendSettings(), and SoapySDRInput::webapiReverseSendSettings().
{
     this->imag = imag;
     this->m_imag_isSet = true;
 }
setReal()
void SWGSDRangel::SWGComplex::setReal (float real)
Definition at line 101 of file SWGComplex.cpp.
References m_real_isSet, and real.
Referenced by SoapySDROutput::webapiFormatDeviceSettings(), SoapySDRInput::webapiFormatDeviceSettings(), SoapySDROutput::webapiReverseSendSettings(), and SoapySDRInput::webapiReverseSendSettings().
{
     this->real = real;
     this->m_real_isSet = true;
 }
Member Data Documentation
imag
float SWGSDRangel::SWGComplex::imag private
Definition at line 57 of file SWGComplex.h.
Referenced by asJsonObject(), fromJsonObject(), getImag(), init(), setImag(), and SWGComplex().
m_imag_isSet
bool SWGSDRangel::SWGComplex::m_imag_isSet private
Definition at line 58 of file SWGComplex.h.
Referenced by asJsonObject(), init(), isSet(), setImag(), and SWGComplex().
m_real_isSet
bool SWGSDRangel::SWGComplex::m_real_isSet private
Definition at line 55 of file SWGComplex.h.
Referenced by asJsonObject(), init(), isSet(), setReal(), and SWGComplex().
real
float SWGSDRangel::SWGComplex::real private
Definition at line 54 of file SWGComplex.h.
Referenced by asJsonObject(), fromJsonObject(), getReal(), init(), setReal(), and SWGComplex().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGComplex.h
swagger/sdrangel/code/qt5/client/SWGComplex.cpp