SDRAngel: SWGSDRangel::SWGPlutoSdrOutputReport Class Reference
SWGSDRangel::SWGPlutoSdrOutputReport Class Reference
#include <SWGPlutoSdrOutputReport.h>
Public Member Functions
SWGPlutoSdrOutputReport ()
SWGPlutoSdrOutputReport (QString *json)
virtual ~SWGPlutoSdrOutputReport ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGPlutoSdrOutputReport * fromJson (QString &jsonString) override
qint32 getDacRate ()
void setDacRate (qint32 dac_rate)
QString * getRssi ()
void setRssi (QString *rssi)
float getTemperature ()
void setTemperature (float temperature)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 dac_rate
bool m_dac_rate_isSet
QString * rssi
bool m_rssi_isSet
float temperature
bool m_temperature_isSet
Detailed Description
Definition at line 32 of file SWGPlutoSdrOutputReport.h.
Constructor & Destructor Documentation
SWGPlutoSdrOutputReport() [1/2]
SWGSDRangel::SWGPlutoSdrOutputReport::SWGPlutoSdrOutputReport ()
Definition at line 30 of file SWGPlutoSdrOutputReport.cpp.
References dac_rate, m_dac_rate_isSet, m_rssi_isSet, m_temperature_isSet, rssi, and temperature.
{
     dac_rate = 0;
     m_dac_rate_isSet = false;
     rssi = nullptr;
     m_rssi_isSet = false;
     temperature = 0.0f;
     m_temperature_isSet = false;
 }
SWGPlutoSdrOutputReport() [2/2]
SWGSDRangel::SWGPlutoSdrOutputReport::SWGPlutoSdrOutputReport (QString * json)
Definition at line 25 of file SWGPlutoSdrOutputReport.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGPlutoSdrOutputReport()
SWGSDRangel::SWGPlutoSdrOutputReport::~SWGPlutoSdrOutputReport () virtual
Definition at line 39 of file SWGPlutoSdrOutputReport.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGPlutoSdrOutputReport::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 82 of file SWGPlutoSdrOutputReport.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGPlutoSdrOutputReport::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 93 of file SWGPlutoSdrOutputReport.cpp.
References dac_rate, m_dac_rate_isSet, m_temperature_isSet, rssi, temperature, and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_dac_rate_isSet){
         obj->insert("dacRate", QJsonValue(dac_rate));
     }
     if(rssi != nullptr && *rssi != QString("")){
         toJsonValue(QString("rssi"), rssi, obj, QString("QString"));
     }
     if(m_temperature_isSet){
         obj->insert("temperature", QJsonValue(temperature));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGPlutoSdrOutputReport::cleanup ()
Definition at line 54 of file SWGPlutoSdrOutputReport.cpp.
References rssi.
Referenced by ~SWGPlutoSdrOutputReport().
{
     if(rssi != nullptr) {
         delete rssi;
     }
 }
fromJson()
SWGPlutoSdrOutputReport * SWGSDRangel::SWGPlutoSdrOutputReport::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 63 of file SWGPlutoSdrOutputReport.cpp.
References fromJsonObject().
Referenced by SWGPlutoSdrOutputReport().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGPlutoSdrOutputReport::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 72 of file SWGPlutoSdrOutputReport.cpp.
References dac_rate, rssi, SWGSDRangel::setValue(), and temperature.
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&dac_rate, pJson["dacRate"], "qint32", "");
     ::SWGSDRangel::setValue(&rssi, pJson["rssi"], "QString", "QString");
     ::SWGSDRangel::setValue(&temperature, pJson["temperature"], "float", "");
 }
getDacRate()
qint32 SWGSDRangel::SWGPlutoSdrOutputReport::getDacRate ()
Definition at line 109 of file SWGPlutoSdrOutputReport.cpp.
References dac_rate.
{
     return dac_rate;
 }
getRssi()
QString * SWGSDRangel::SWGPlutoSdrOutputReport::getRssi ()
Definition at line 119 of file SWGPlutoSdrOutputReport.cpp.
References rssi.
{
     return rssi;
 }
getTemperature()
float SWGSDRangel::SWGPlutoSdrOutputReport::getTemperature ()
Definition at line 129 of file SWGPlutoSdrOutputReport.cpp.
References temperature.
{
     return temperature;
 }
init()
void SWGSDRangel::SWGPlutoSdrOutputReport::init ()
Definition at line 44 of file SWGPlutoSdrOutputReport.cpp.
References dac_rate, m_dac_rate_isSet, m_rssi_isSet, m_temperature_isSet, rssi, and temperature.
Referenced by SWGPlutoSdrOutputReport(), and PlutoSDROutput::webapiReportGet().
{
     dac_rate = 0;
     m_dac_rate_isSet = false;
     rssi = new QString("");
     m_rssi_isSet = false;
     temperature = 0.0f;
     m_temperature_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGPlutoSdrOutputReport::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 140 of file SWGPlutoSdrOutputReport.cpp.
References m_dac_rate_isSet, m_temperature_isSet, and rssi.
Referenced by SWGSDRangel::SWGDeviceReport::asJsonObject(), and SWGSDRangel::SWGDeviceReport::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(m_dac_rate_isSet){ isObjectUpdated = true; break;}
         if(rssi != nullptr && *rssi != QString("")){ isObjectUpdated = true; break;}
         if(m_temperature_isSet){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setDacRate()
void SWGSDRangel::SWGPlutoSdrOutputReport::setDacRate (qint32 dac_rate)
Definition at line 113 of file SWGPlutoSdrOutputReport.cpp.
References dac_rate, and m_dac_rate_isSet.
Referenced by PlutoSDROutput::webapiFormatDeviceReport().
{
     this->dac_rate = dac_rate;
     this->m_dac_rate_isSet = true;
 }
setRssi()
void SWGSDRangel::SWGPlutoSdrOutputReport::setRssi (QString * rssi)
Definition at line 123 of file SWGPlutoSdrOutputReport.cpp.
References m_rssi_isSet, and rssi.
Referenced by PlutoSDROutput::webapiFormatDeviceReport().
{
     this->rssi = rssi;
     this->m_rssi_isSet = true;
 }
setTemperature()
void SWGSDRangel::SWGPlutoSdrOutputReport::setTemperature (float temperature)
Definition at line 133 of file SWGPlutoSdrOutputReport.cpp.
References m_temperature_isSet, and temperature.
Referenced by PlutoSDROutput::webapiFormatDeviceReport().
{
     this->temperature = temperature;
     this->m_temperature_isSet = true;
 }
Member Data Documentation
dac_rate
qint32 SWGSDRangel::SWGPlutoSdrOutputReport::dac_rate private
Definition at line 58 of file SWGPlutoSdrOutputReport.h.
Referenced by asJsonObject(), fromJsonObject(), getDacRate(), init(), setDacRate(), and SWGPlutoSdrOutputReport().
m_dac_rate_isSet
bool SWGSDRangel::SWGPlutoSdrOutputReport::m_dac_rate_isSet private
Definition at line 59 of file SWGPlutoSdrOutputReport.h.
Referenced by asJsonObject(), init(), isSet(), setDacRate(), and SWGPlutoSdrOutputReport().
m_rssi_isSet
bool SWGSDRangel::SWGPlutoSdrOutputReport::m_rssi_isSet private
Definition at line 62 of file SWGPlutoSdrOutputReport.h.
Referenced by init(), setRssi(), and SWGPlutoSdrOutputReport().
m_temperature_isSet
bool SWGSDRangel::SWGPlutoSdrOutputReport::m_temperature_isSet private
Definition at line 65 of file SWGPlutoSdrOutputReport.h.
Referenced by asJsonObject(), init(), isSet(), setTemperature(), and SWGPlutoSdrOutputReport().
rssi
QString* SWGSDRangel::SWGPlutoSdrOutputReport::rssi private
Definition at line 61 of file SWGPlutoSdrOutputReport.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getRssi(), init(), isSet(), setRssi(), and SWGPlutoSdrOutputReport().
temperature
float SWGSDRangel::SWGPlutoSdrOutputReport::temperature private
Definition at line 64 of file SWGPlutoSdrOutputReport.h.
Referenced by asJsonObject(), fromJsonObject(), getTemperature(), init(), setTemperature(), and SWGPlutoSdrOutputReport().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGPlutoSdrOutputReport.h
swagger/sdrangel/code/qt5/client/SWGPlutoSdrOutputReport.cpp