SDRAngel: FreeDVDemod::FreeDVSNR Struct Reference
FreeDVDemod::FreeDVSNR Struct Reference
Public Member Functions
FreeDVSNR ()
void accumulate (float snrdB)
Public Attributes
double m_sum
float m_peak
int m_n
bool m_reset
Detailed Description
Definition at line 238 of file freedvdemod.h.
Constructor & Destructor Documentation
FreeDVSNR()
FreeDVDemod::FreeDVSNR::FreeDVSNR ()
Definition at line 98 of file freedvdemod.cpp.
References FreeDVDemod::m_sum.
 {
     m_sum = 0.0f;
     m_peak = 0.0f;
     m_n = 0;
     m_reset = true;
 }
Member Function Documentation
accumulate()
void FreeDVDemod::FreeDVSNR::accumulate (float snrdB)
Definition at line 106 of file freedvdemod.cpp.
References FreeDVDemod::m_sum, leansdr::max(), and CalcDb::powerFromdB().
Referenced by FreeDVDemod::pushSampleToDV().
 {
     if (m_reset)
     {
         m_sum = CalcDb::powerFromdB(snrdB);
         m_peak = snrdB;
         m_n = 1;
         m_reset = false;
     }
     else
     {
         m_sum += CalcDb::powerFromdB(snrdB);
         m_peak = std::max(m_peak, snrdB);
         m_n++;
     }
 }
Member Data Documentation
m_n
int FreeDVDemod::FreeDVSNR::m_n
Definition at line 245 of file freedvdemod.h.
Referenced by FreeDVDemod::getSNRLevels().
m_peak
float FreeDVDemod::FreeDVSNR::m_peak
Definition at line 244 of file freedvdemod.h.
Referenced by FreeDVDemod::getSNRLevels().
m_reset
bool FreeDVDemod::FreeDVSNR::m_reset
Definition at line 246 of file freedvdemod.h.
Referenced by FreeDVDemod::getSNRLevels().
m_sum
double FreeDVDemod::FreeDVSNR::m_sum
Definition at line 243 of file freedvdemod.h.
Referenced by FreeDVDemod::getSNRLevels().
The documentation for this struct was generated from the following files:
plugins/channelrx/demodfreedv/freedvdemod.h
plugins/channelrx/demodfreedv/freedvdemod.cpp