SDRAngel: BasebandSampleSource Class Reference
BasebandSampleSource Class Reference abstract
#include <basebandsamplesource.h>
Public Member Functions
BasebandSampleSource ()
virtual ~BasebandSampleSource ()
virtual void start ()=0
virtual void stop ()=0
virtual void pull (Sample &sample)=0
virtual void pullAudio (int nbSamples)
void feed (SampleSourceFifo *sampleFifo, int nbSamples)
SampleSourceFifo & getSampleSourceFifo ()
virtual bool handleMessage (const Message &cmd)=0
Processing of a message. Returns true if message has actually been processed.
MessageQueue * getInputMessageQueue ()
Get the queue for asynchronous inbound communication.
virtual void setMessageQueueToGUI (MessageQueue *queue)
MessageQueue * getMessageQueueToGUI ()
void setDeviceSampleSourceFifo (SampleSourceFifo *deviceSampleFifo)
Protected Slots
void handleInputMessages ()
void handleWriteToFifo (int nbSamples)
void handleWriteToDeviceFifo (int nbSamples)
Protected Member Functions
void handleWriteToFifo (SampleSourceFifo *sampleFifo, int nbSamples)
Protected Attributes
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
SampleSourceFifo m_sampleFifo
Internal FIFO for multi-channel processing.
SampleSourceFifo * m_deviceSampleFifo
Reference to the device FIFO for single channel processing.
Detailed Description
Definition at line 30 of file basebandsamplesource.h.
Constructor & Destructor Documentation
BasebandSampleSource()
BasebandSampleSource::BasebandSampleSource ()
Definition at line 22 of file basebandsamplesource.cpp.
References handleInputMessages(), handleWriteToFifo(), m_inputMessageQueue, and m_sampleFifo.
                                            :
     m_guiMessageQueue(0),
     m_sampleFifo(48000), // arbitrary, will be adjusted to match device sink FIFO size
     m_deviceSampleFifo(0)
 {
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()));
     connect(&m_sampleFifo, SIGNAL(dataWrite(int)), this, SLOT(handleWriteToFifo(int)));
 }
~BasebandSampleSource()
BasebandSampleSource::~BasebandSampleSource () virtual
Definition at line 31 of file basebandsamplesource.cpp.
 {
 }
Member Function Documentation
feed()
void BasebandSampleSource::feed (SampleSourceFifo * sampleFifo, int nbSamples) inline
direct feeding of sample source FIFO
Definition at line 42 of file basebandsamplesource.h.
References SampleSourceFifo::bumpIndex(), SampleSourceFifo::getWriteIterator(), and i.
Referenced by ThreadedBasebandSampleSource::feed().
     {
         SampleVector::iterator writeAt;
         sampleFifo->getWriteIterator(writeAt);
         pullAudio(nbSamples); // Pre-fetch input audio samples this is mandatory to keep things running smoothly
         for (int i = 0; i < nbSamples; i++)
         {
             pull((*writeAt));
             sampleFifo->bumpIndex(writeAt);
         }
     }
getInputMessageQueue()
MessageQueue* BasebandSampleSource::getInputMessageQueue () inline
Get the queue for asynchronous inbound communication.
Definition at line 59 of file basebandsamplesource.h.
Referenced by AMMod::AMMod(), LocalSourceGUI::applyChannelSettings(), FileSourceGUI::applyChannelSettings(), UpChannelizer::applyConfiguration(), UpChannelizer::applySetting(), LocalSourceGUI::applySettings(), UDPSourceGUI::applySettings(), NFMModGUI::applySettings(), AMModGUI::applySettings(), RemoteSourceGUI::applySettings(), ATVModGUI::applySettings(), WFMModGUI::applySettings(), FreeDVModGUI::applySettings(), FileSourceGUI::applySettings(), SSBModGUI::applySettings(), WFMMod::applySettings(), AMMod::applySettings(), NFMMod::applySettings(), FreeDVMod::applySettings(), SSBMod::applySettings(), FileSourceGUI::configureFileName(), AMModGUI::configureFileName(), FreeDVModGUI::configureFileName(), NFMModGUI::configureFileName(), WFMModGUI::configureFileName(), SSBModGUI::configureFileName(), ATVModGUI::configureImageFileName(), ATVModGUI::configureVideoFileName(), FreeDVMod::FreeDVMod(), UpChannelizer::handleMessage(), UDPSource::handleMessage(), LocalSource::handleMessage(), AMMod::handleMessage(), WFMMod::handleMessage(), NFMMod::handleMessage(), SSBMod::handleMessage(), FreeDVMod::handleMessage(), FileSource::handleMessage(), ATVMod::handleMessage(), NFMMod::NFMMod(), ATVModGUI::on_cameraManualFPS_valueChanged(), ATVModGUI::on_cameraManualFPSEnable_toggled(), ATVModGUI::on_camSelect_currentIndexChanged(), FileSourceGUI::on_navTime_valueChanged(), AMModGUI::on_navTimeSlider_valueChanged(), NFMModGUI::on_navTimeSlider_valueChanged(), FreeDVModGUI::on_navTimeSlider_valueChanged(), WFMModGUI::on_navTimeSlider_valueChanged(), SSBModGUI::on_navTimeSlider_valueChanged(), ATVModGUI::on_navTimeSlider_valueChanged(), FileSourceGUI::on_play_toggled(), FileSourceGUI::on_playLoop_toggled(), UDPSource::resetReadIndex(), UDPSource::setSpectrum(), SSBMod::SSBMod(), RemoteSourceGUI::tick(), FileSourceGUI::tick(), AMModGUI::tick(), FreeDVModGUI::tick(), NFMModGUI::tick(), WFMModGUI::tick(), SSBModGUI::tick(), ATVModGUI::tick(), and WFMMod::WFMMod().
getMessageQueueToGUI()
MessageQueue* BasebandSampleSource::getMessageQueueToGUI () inline
Definition at line 61 of file basebandsamplesource.h.
Referenced by SSBMod::applyAudioSampleRate(), ATVMod::applyChannelSettings(), FreeDVMod::applyFreeDVMode(), ATVMod::applySettings(), ATVMod::getCameraNumbers(), FileSource::handleEOF(), AMMod::handleMessage(), WFMMod::handleMessage(), NFMMod::handleMessage(), SSBMod::handleMessage(), FreeDVMod::handleMessage(), FileSource::handleMessage(), ATVMod::handleMessage(), WFMMod::openFileStream(), AMMod::openFileStream(), NFMMod::openFileStream(), FreeDVMod::openFileStream(), SSBMod::openFileStream(), FileSource::openFileStream(), ATVMod::openVideo(), ATVMod::pullVideo(), FileSource::start(), and FileSource::stop().
 { return m_guiMessageQueue; }
getSampleSourceFifo()
SampleSourceFifo& BasebandSampleSource::getSampleSourceFifo () inline
Definition at line 55 of file basebandsamplesource.h.
 { return m_sampleFifo; }
handleInputMessages
void BasebandSampleSource::handleInputMessages () protected slot
Definition at line 35 of file basebandsamplesource.cpp.
References handleMessage(), m_inputMessageQueue, and MessageQueue::pop().
Referenced by BasebandSampleSource().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (handleMessage(*message))
         {
             delete message;
         }
     }
 }
handleMessage()
virtual bool BasebandSampleSource::handleMessage (const Message & cmd) pure virtual
Processing of a message. Returns true if message has actually been processed.
Implemented in ATVMod, FileSource, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, LocalSource, UDPSource, and UpChannelizer.
Referenced by handleInputMessages(), ThreadedBasebandSampleSource::handleSourceMessage(), and DSPDeviceSinkEngine::handleSynchronousMessages().
handleWriteToDeviceFifo
void BasebandSampleSource::handleWriteToDeviceFifo (int nbSamples) protected slot
Definition at line 53 of file basebandsamplesource.cpp.
References handleWriteToFifo(), and m_deviceSampleFifo.
Referenced by setDeviceSampleSourceFifo().
 {
     handleWriteToFifo(m_deviceSampleFifo, nbSamples);
 }
handleWriteToFifo() [1/2]
void BasebandSampleSource::handleWriteToFifo (SampleSourceFifo * sampleFifo, int nbSamples) protected
Definition at line 58 of file basebandsamplesource.cpp.
References SampleSourceFifo::bumpIndex(), SampleSourceFifo::getWriteIterator(), i, pull(), and pullAudio().
Referenced by BasebandSampleSource(), handleWriteToDeviceFifo(), and handleWriteToFifo().
 {
     SampleVector::iterator writeAt;
     sampleFifo->getWriteIterator(writeAt);
     pullAudio(nbSamples); // Pre-fetch input audio samples this is mandatory to keep things running smoothly
     for (int i = 0; i < nbSamples; i++)
     {
         pull((*writeAt));
         sampleFifo->bumpIndex(writeAt);
     }
 }
handleWriteToFifo [2/2]
void BasebandSampleSource::handleWriteToFifo (int nbSamples) protected slot
Definition at line 48 of file basebandsamplesource.cpp.
References handleWriteToFifo(), and m_sampleFifo.
 {
     handleWriteToFifo(&m_sampleFifo, nbSamples);
 }
pull()
virtual void BasebandSampleSource::pull (Sample & sample) pure virtual
Implemented in ATVMod, FileSource, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, LocalSource, UDPSource, and UpChannelizer.
Referenced by handleWriteToFifo(), ThreadedBasebandSampleSource::pull(), and UpChannelizer::pull().
pullAudio()
virtual void BasebandSampleSource::pullAudio (int nbSamples) inline virtual
Reimplemented in ATVMod, FileSource, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, LocalSource, and UpChannelizer.
Definition at line 39 of file basebandsamplesource.h.
Referenced by handleWriteToFifo().
 { (void) nbSamples; }
setDeviceSampleSourceFifo()
void BasebandSampleSource::setDeviceSampleSourceFifo (SampleSourceFifo * deviceSampleFifo)
Definition at line 72 of file basebandsamplesource.cpp.
References handleWriteToDeviceFifo(), and m_deviceSampleFifo.
 {
     if (m_deviceSampleFifo != deviceSampleFifo)
     {
         if (m_deviceSampleFifo) {
             qDebug("BasebandSampleSource::setDeviceSampleSourceFifo: disconnect device FIFO %p", m_deviceSampleFifo);
             disconnect(m_deviceSampleFifo, SIGNAL(dataWrite(int)), this, SLOT(handleWriteToDeviceFifo(int)));
         }
         if (deviceSampleFifo) {
             qDebug("BasebandSampleSource::setDeviceSampleSourceFifo: connect device FIFO %p", deviceSampleFifo);
             connect(deviceSampleFifo, SIGNAL(dataWrite(int)), this, SLOT(handleWriteToDeviceFifo(int)));
         }
         m_deviceSampleFifo = deviceSampleFifo;
     }
 }
setMessageQueueToGUI()
virtual void BasebandSampleSource::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Definition at line 60 of file basebandsamplesource.h.
Referenced by AMModGUI::AMModGUI(), ATVModGUI::ATVModGUI(), FileSourceGUI::FileSourceGUI(), FreeDVModGUI::FreeDVModGUI(), LocalSourceGUI::LocalSourceGUI(), NFMModGUI::NFMModGUI(), RemoteSourceGUI::RemoteSourceGUI(), SSBModGUI::SSBModGUI(), UDPSourceGUI::UDPSourceGUI(), and WFMModGUI::WFMModGUI().
 { m_guiMessageQueue = queue; }
start()
virtual void BasebandSampleSource::start () pure virtual
Implemented in ATVMod, FileSource, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, LocalSource, UDPSource, and UpChannelizer.
Referenced by DSPDeviceSinkEngine::handleSynchronousMessages(), ThreadedBasebandSampleSource::start(), and UpChannelizer::start().
stop()
virtual void BasebandSampleSource::stop () pure virtual
Implemented in ATVMod, FileSource, FreeDVMod, SSBMod, NFMMod, WFMMod, AMMod, RemoteSource, LocalSource, UDPSource, and UpChannelizer.
Referenced by DSPDeviceSinkEngine::handleSynchronousMessages(), ThreadedBasebandSampleSource::stop(), and UpChannelizer::stop().
Member Data Documentation
m_deviceSampleFifo
SampleSourceFifo* BasebandSampleSource::m_deviceSampleFifo protected
Reference to the device FIFO for single channel processing.
Definition at line 68 of file basebandsamplesource.h.
Referenced by handleWriteToDeviceFifo(), and setDeviceSampleSourceFifo().
m_guiMessageQueue
MessageQueue* BasebandSampleSource::m_guiMessageQueue protected
Input message queue to the GUI.
Definition at line 66 of file basebandsamplesource.h.
Referenced by LocalSource::handleMessage(), RemoteSource::handleMessage(), FileSource::handleMessage(), UDPSource::webapiSettingsPutPatch(), LocalSource::webapiSettingsPutPatch(), RemoteSource::webapiSettingsPutPatch(), AMMod::webapiSettingsPutPatch(), WFMMod::webapiSettingsPutPatch(), NFMMod::webapiSettingsPutPatch(), SSBMod::webapiSettingsPutPatch(), FreeDVMod::webapiSettingsPutPatch(), FileSource::webapiSettingsPutPatch(), and ATVMod::webapiSettingsPutPatch().
m_inputMessageQueue
MessageQueue BasebandSampleSource::m_inputMessageQueue protected
Queue for asynchronous inbound communication.
Definition at line 65 of file basebandsamplesource.h.
Referenced by AMMod::applyAudioSampleRate(), NFMMod::applyAudioSampleRate(), SSBMod::applyAudioSampleRate(), FreeDVMod::applyFreeDVMode(), BasebandSampleSource(), UDPSource::deserialize(), LocalSource::deserialize(), RemoteSource::deserialize(), AMMod::deserialize(), WFMMod::deserialize(), NFMMod::deserialize(), SSBMod::deserialize(), FreeDVMod::deserialize(), FileSource::deserialize(), ATVMod::deserialize(), handleInputMessages(), RemoteSource::setDataLink(), UDPSource::UDPSource(), UDPSource::webapiSettingsPutPatch(), LocalSource::webapiSettingsPutPatch(), RemoteSource::webapiSettingsPutPatch(), AMMod::webapiSettingsPutPatch(), WFMMod::webapiSettingsPutPatch(), NFMMod::webapiSettingsPutPatch(), SSBMod::webapiSettingsPutPatch(), FreeDVMod::webapiSettingsPutPatch(), FileSource::webapiSettingsPutPatch(), and ATVMod::webapiSettingsPutPatch().
m_sampleFifo
SampleSourceFifo BasebandSampleSource::m_sampleFifo protected
Internal FIFO for multi-channel processing.
Definition at line 67 of file basebandsamplesource.h.
Referenced by BasebandSampleSource(), and handleWriteToFifo().
The documentation for this class was generated from the following files:
sdrbase/dsp/basebandsamplesource.h
sdrbase/dsp/basebandsamplesource.cpp