SDRAngel: SWGSDRangel::SWGDeviceSetList Class Reference
SWGSDRangel::SWGDeviceSetList Class Reference
#include <SWGDeviceSetList.h>
Public Member Functions
SWGDeviceSetList ()
SWGDeviceSetList (QString *json)
virtual ~SWGDeviceSetList ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGDeviceSetList * fromJson (QString &jsonString) override
qint32 getDevicesetcount ()
void setDevicesetcount (qint32 devicesetcount)
qint32 getDevicesetfocus ()
void setDevicesetfocus (qint32 devicesetfocus)
QList< SWGDeviceSet * > * getDeviceSets ()
void setDeviceSets (QList< SWGDeviceSet *> *device_sets)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
qint32 devicesetcount
bool m_devicesetcount_isSet
qint32 devicesetfocus
bool m_devicesetfocus_isSet
QList< SWGDeviceSet * > * device_sets
bool m_device_sets_isSet
Detailed Description
Definition at line 33 of file SWGDeviceSetList.h.
Constructor & Destructor Documentation
SWGDeviceSetList() [1/2]
SWGSDRangel::SWGDeviceSetList::SWGDeviceSetList ()
Definition at line 30 of file SWGDeviceSetList.cpp.
References device_sets, devicesetcount, devicesetfocus, m_device_sets_isSet, m_devicesetcount_isSet, and m_devicesetfocus_isSet.
{
     devicesetcount = 0;
     m_devicesetcount_isSet = false;
     devicesetfocus = 0;
     m_devicesetfocus_isSet = false;
     device_sets = nullptr;
     m_device_sets_isSet = false;
 }
SWGDeviceSetList() [2/2]
SWGSDRangel::SWGDeviceSetList::SWGDeviceSetList (QString * json)
Definition at line 25 of file SWGDeviceSetList.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGDeviceSetList()
SWGSDRangel::SWGDeviceSetList::~SWGDeviceSetList () virtual
Definition at line 39 of file SWGDeviceSetList.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGDeviceSetList::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 86 of file SWGDeviceSetList.cpp.
References asJsonObject().
Referenced by WebAPIRequestMapper::instanceDeviceSetsService().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGDeviceSetList::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 97 of file SWGDeviceSetList.cpp.
References device_sets, devicesetcount, devicesetfocus, m_devicesetcount_isSet, m_devicesetfocus_isSet, and SWGSDRangel::toJsonArray().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(m_devicesetcount_isSet){
         obj->insert("devicesetcount", QJsonValue(devicesetcount));
     }
     if(m_devicesetfocus_isSet){
         obj->insert("devicesetfocus", QJsonValue(devicesetfocus));
     }
     if(device_sets->size() > 0){
         toJsonArray((QList<void*>*)device_sets, obj, "deviceSets", "SWGDeviceSet");
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGDeviceSetList::cleanup ()
Definition at line 54 of file SWGDeviceSetList.cpp.
References device_sets.
Referenced by ~SWGDeviceSetList().
{
     if(device_sets != nullptr) {
         auto arr = device_sets;
         for(auto o: *arr) {
             delete o;
         }
         delete device_sets;
     }
 }
fromJson()
SWGDeviceSetList * SWGSDRangel::SWGDeviceSetList::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 67 of file SWGDeviceSetList.cpp.
References fromJsonObject().
Referenced by SWGDeviceSetList().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGDeviceSetList::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 76 of file SWGDeviceSetList.cpp.
References device_sets, devicesetcount, devicesetfocus, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&devicesetcount, pJson["devicesetcount"], "qint32", "");
     ::SWGSDRangel::setValue(&devicesetfocus, pJson["devicesetfocus"], "qint32", "");
     ::SWGSDRangel::setValue(&device_sets, pJson["deviceSets"], "QList", "SWGDeviceSet");
 }
getDevicesetcount()
qint32 SWGSDRangel::SWGDeviceSetList::getDevicesetcount ()
Definition at line 113 of file SWGDeviceSetList.cpp.
References devicesetcount.
{
     return devicesetcount;
 }
getDevicesetfocus()
qint32 SWGSDRangel::SWGDeviceSetList::getDevicesetfocus ()
Definition at line 123 of file SWGDeviceSetList.cpp.
References devicesetfocus.
{
     return devicesetfocus;
 }
getDeviceSets()
QList< SWGDeviceSet * > * SWGSDRangel::SWGDeviceSetList::getDeviceSets ()
Definition at line 133 of file SWGDeviceSetList.cpp.
References device_sets.
Referenced by WebAPIAdapterGUI::getDeviceSetList(), and WebAPIAdapterSrv::getDeviceSetList().
{
     return device_sets;
 }
init()
void SWGSDRangel::SWGDeviceSetList::init ()
Definition at line 44 of file SWGDeviceSetList.cpp.
References device_sets, devicesetcount, devicesetfocus, m_device_sets_isSet, m_devicesetcount_isSet, and m_devicesetfocus_isSet.
Referenced by WebAPIAdapterGUI::getDeviceSetList(), WebAPIAdapterSrv::getDeviceSetList(), and SWGDeviceSetList().
{
     devicesetcount = 0;
     m_devicesetcount_isSet = false;
     devicesetfocus = 0;
     m_devicesetfocus_isSet = false;
     device_sets = new QList<SWGDeviceSet*>();
     m_device_sets_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGDeviceSetList::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 144 of file SWGDeviceSetList.cpp.
References device_sets, m_devicesetcount_isSet, and m_devicesetfocus_isSet.
Referenced by SWGSDRangel::SWGInstanceSummaryResponse::asJsonObject(), and SWGSDRangel::SWGInstanceSummaryResponse::isSet().
{
     bool isObjectUpdated = false;
     do{
         if(m_devicesetcount_isSet){ isObjectUpdated = true; break;}
         if(m_devicesetfocus_isSet){ isObjectUpdated = true; break;}
         if(device_sets->size() > 0){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setDevicesetcount()
void SWGSDRangel::SWGDeviceSetList::setDevicesetcount (qint32 devicesetcount)
Definition at line 117 of file SWGDeviceSetList.cpp.
References devicesetcount, and m_devicesetcount_isSet.
Referenced by WebAPIAdapterGUI::getDeviceSetList(), and WebAPIAdapterSrv::getDeviceSetList().
{
     this->devicesetcount = devicesetcount;
     this->m_devicesetcount_isSet = true;
 }
setDevicesetfocus()
void SWGSDRangel::SWGDeviceSetList::setDevicesetfocus (qint32 devicesetfocus)
Definition at line 127 of file SWGDeviceSetList.cpp.
References devicesetfocus, and m_devicesetfocus_isSet.
Referenced by WebAPIAdapterGUI::getDeviceSetList().
{
     this->devicesetfocus = devicesetfocus;
     this->m_devicesetfocus_isSet = true;
 }
setDeviceSets()
void SWGSDRangel::SWGDeviceSetList::setDeviceSets (QList< SWGDeviceSet *> * device_sets)
Definition at line 137 of file SWGDeviceSetList.cpp.
References device_sets, and m_device_sets_isSet.
{
     this->device_sets = device_sets;
     this->m_device_sets_isSet = true;
 }
Member Data Documentation
device_sets
QList<SWGDeviceSet*>* SWGSDRangel::SWGDeviceSetList::device_sets private
Definition at line 65 of file SWGDeviceSetList.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getDeviceSets(), init(), isSet(), setDeviceSets(), and SWGDeviceSetList().
devicesetcount
qint32 SWGSDRangel::SWGDeviceSetList::devicesetcount private
Definition at line 59 of file SWGDeviceSetList.h.
Referenced by asJsonObject(), fromJsonObject(), getDevicesetcount(), init(), setDevicesetcount(), and SWGDeviceSetList().
devicesetfocus
qint32 SWGSDRangel::SWGDeviceSetList::devicesetfocus private
Definition at line 62 of file SWGDeviceSetList.h.
Referenced by asJsonObject(), fromJsonObject(), getDevicesetfocus(), init(), setDevicesetfocus(), and SWGDeviceSetList().
m_device_sets_isSet
bool SWGSDRangel::SWGDeviceSetList::m_device_sets_isSet private
Definition at line 66 of file SWGDeviceSetList.h.
Referenced by init(), setDeviceSets(), and SWGDeviceSetList().
m_devicesetcount_isSet
bool SWGSDRangel::SWGDeviceSetList::m_devicesetcount_isSet private
Definition at line 60 of file SWGDeviceSetList.h.
Referenced by asJsonObject(), init(), isSet(), setDevicesetcount(), and SWGDeviceSetList().
m_devicesetfocus_isSet
bool SWGSDRangel::SWGDeviceSetList::m_devicesetfocus_isSet private
Definition at line 63 of file SWGDeviceSetList.h.
Referenced by asJsonObject(), init(), isSet(), setDevicesetfocus(), and SWGDeviceSetList().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGDeviceSetList.h
swagger/sdrangel/code/qt5/client/SWGDeviceSetList.cpp