SDRAngel: BladeRF2Output Class Reference
BladeRF2Output Class Reference
#include <bladerf2output.h>
Classes
class MsgConfigureBladeRF2
class MsgReportGainRange
class MsgStartStop
Public Member Functions
BladeRF2Output (DeviceAPI *deviceAPI)
virtual ~BladeRF2Output ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
BladeRF2OutputThread * getThread ()
void setThread (BladeRF2OutputThread *thread)
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the sink.
virtual void setSampleRate (int sampleRate)
For when the sink sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the sink.
virtual void setCenterFrequency (qint64 centerFrequency)
void getFrequencyRange (uint64_t &min, uint64_t &max, int &step)
void getSampleRateRange (int &min, int &max, int &step)
void getBandwidthRange (int &min, int &max, int &step)
void getGlobalGainRange (int &min, int &max, int &step)
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSink
DeviceSampleSink ()
virtual ~DeviceSampleSink ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSourceFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
bool openDevice ()
void closeDevice ()
BladeRF2OutputThread * findThread ()
void moveThreadToBuddy ()
bool applySettings (const BladeRF2OutputSettings &settings, bool force)
int getNbChannels ()
bool setDeviceCenterFrequency (struct bladerf *dev, int requestedChannel, quint64 freq_hz, int loPpmTenths)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const BladeRF2OutputSettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const BladeRF2OutputSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
BladeRF2OutputSettings m_settings
struct bladerf * m_dev
BladeRF2OutputThread * m_thread
QString m_deviceDescription
DeviceBladeRF2Shared m_deviceShared
bool m_running
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSink
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
Static Public Member Functions inherited from DeviceSampleSink
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Interp, fcPos_t fcPos, quint32 devSampleRate)
Protected Slots inherited from DeviceSampleSink
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSink
SampleSourceFifo m_sampleSourceFifo
MessageQueue m_inputMessageQueue
Input queue to the sink.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 36 of file bladerf2output.h.
Constructor & Destructor Documentation
BladeRF2Output()
BladeRF2Output::BladeRF2Output (DeviceAPI * deviceAPI)
Definition at line 45 of file bladerf2output.cpp.
Referenced by BladeRF2Output::MsgReportGainRange::MsgReportGainRange().
                                                    :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_dev(0),
     m_thread(0),
     m_deviceDescription("BladeRF2Output"),
     m_running(false)
 {
     openDevice();
     m_deviceAPI->setNbSinkStreams(1);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~BladeRF2Output()
BladeRF2Output::~BladeRF2Output () virtual
Definition at line 59 of file bladerf2output.cpp.
References closeDevice(), m_networkManager, m_running, networkManagerFinished(), and stop().
Referenced by BladeRF2Output::MsgReportGainRange::MsgReportGainRange().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     if (m_running) {
         stop();
     }
     closeDevice();
 }
Member Function Documentation
applySettings()
bool BladeRF2Output::applySettings (const BladeRF2OutputSettings & settings, bool force) private
Definition at line 699 of file bladerf2output.cpp.
References DeviceBladeRF2Shared::MsgReportBuddyChange::create(), BladeRF2Output::MsgReportGainRange::create(), findThread(), DeviceBladeRF2::getDev(), DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceAPI::getDeviceItemIndex(), BladeRF2OutputThread::getFifo(), getGlobalGainRange(), DeviceSampleSink::getMessageQueueToGUI(), getNbChannels(), DeviceAPI::getSinkBuddies(), DeviceAPI::getSourceBuddies(), BladeRF2OutputSettings::m_bandwidth, BladeRF2OutputSettings::m_biasTee, BladeRF2OutputSettings::m_centerFrequency, DeviceBladeRF2Shared::m_dev, m_deviceAPI, m_deviceShared, BladeRF2OutputSettings::m_devSampleRate, BladeRF2OutputSettings::m_globalGain, BladeRF2OutputSettings::m_log2Interp, BladeRF2OutputSettings::m_LOppmTenths, BladeRF2OutputSettings::m_reverseAPIAddress, BladeRF2OutputSettings::m_reverseAPIDeviceIndex, BladeRF2OutputSettings::m_reverseAPIPort, DeviceBladeRF2Shared::m_sampleFifoLengthInSeconds, DeviceBladeRF2Shared::m_sampleFifoMinSize, DeviceBladeRF2Shared::m_sampleFifoMinSize32, DeviceSampleSink::m_sampleSourceFifo, m_settings, BladeRF2OutputSettings::m_transverterDeltaFrequency, BladeRF2OutputSettings::m_transverterMode, BladeRF2OutputSettings::m_useReverseAPI, leansdr::max(), leansdr::min(), MessageQueue::push(), SampleSourceFifo::resize(), DeviceBladeRF2::setBiasTeeTx(), setDeviceCenterFrequency(), BladeRF2OutputThread::setFifo(), BladeRF2OutputThread::setLog2Interpolation(), and webapiReverseSendSettings().
Referenced by handleMessage(), init(), start(), and stop().
 {
     bool forwardChangeOwnDSP = false;
     bool forwardChangeRxBuddies  = false;
     bool forwardChangeTxBuddies = false;
     QList<QString> reverseAPIKeys;
     struct bladerf *dev = m_deviceShared.m_dev->getDev();
     int requestedChannel = m_deviceAPI->getDeviceItemIndex();
     int nbChannels = getNbChannels();
     qint64 deviceCenterFrequency = settings.m_centerFrequency;
     deviceCenterFrequency -= settings.m_transverterMode ? settings.m_transverterDeltaFrequency : 0;
     deviceCenterFrequency = deviceCenterFrequency < 0 ? 0 : deviceCenterFrequency;
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || (m_settings.m_log2Interp != settings.m_log2Interp) || force)
     {
         reverseAPIKeys.append("devSampleRate");
         BladeRF2OutputThread *bladeRF2OutputThread = findThread();
         SampleSourceFifo *fifo = 0;
         if (bladeRF2OutputThread)
         {
             fifo = bladeRF2OutputThread->getFifo(requestedChannel);
             bladeRF2OutputThread->setFifo(requestedChannel, 0);
         }
         int fifoSize;
         if (settings.m_log2Interp >= 5)
         {
             fifoSize = DeviceBladeRF2Shared::m_sampleFifoMinSize32;
         }
         else
         {
             fifoSize = (std::max)(
                 (int) ((settings.m_devSampleRate/(1<<settings.m_log2Interp)) * DeviceBladeRF2Shared::m_sampleFifoLengthInSeconds),
                 DeviceBladeRF2Shared::m_sampleFifoMinSize);
         }
         m_sampleSourceFifo.resize(fifoSize);
         if (fifo) {
             bladeRF2OutputThread->setFifo(requestedChannel, &m_sampleSourceFifo);
         }
     }
     if ((m_settings.m_devSampleRate != settings.m_devSampleRate) || force)
     {
         forwardChangeOwnDSP = true;
         forwardChangeRxBuddies = true;
         forwardChangeTxBuddies = true;
         if (dev != 0)
         {
             unsigned int actualSamplerate;
             int status = bladerf_set_sample_rate(dev, BLADERF_CHANNEL_TX(requestedChannel),
                     settings.m_devSampleRate,
                     &actualSamplerate);
             if (status < 0)
             {
                 qCritical("BladeRF2Output::applySettings: could not set sample rate: %d: %s",
                         settings.m_devSampleRate, bladerf_strerror(status));
             }
             else
             {
                 qDebug() << "BladeRF2Output::applySettings: bladerf_set_sample_rate: actual sample rate is " << actualSamplerate;
             }
         }
     }
     if ((m_settings.m_bandwidth != settings.m_bandwidth) || force)
     {
         reverseAPIKeys.append("bandwidth");
         forwardChangeTxBuddies = true;
         if (dev != 0)
         {
             unsigned int actualBandwidth;
             int status = bladerf_set_bandwidth(dev, BLADERF_CHANNEL_TX(requestedChannel), settings.m_bandwidth, &actualBandwidth);
             if(status < 0)
             {
                 qCritical("BladeRF2Output::applySettings: could not set bandwidth: %d: %s",
                         settings.m_bandwidth, bladerf_strerror(status));
             }
             else
             {
                 qDebug() << "BladeRF2Output::applySettings: bladerf_set_bandwidth: actual bandwidth is " << actualBandwidth;
             }
         }
     }
     if ((m_settings.m_log2Interp != settings.m_log2Interp) || force)
     {
         reverseAPIKeys.append("log2Interp");
         forwardChangeOwnDSP = true;
         BladeRF2OutputThread *outputThread = findThread();
         if (outputThread != 0)
         {
             outputThread->setLog2Interpolation(requestedChannel, settings.m_log2Interp);
             qDebug() << "BladeRF2Output::applySettings: set interpolation to " << (1<<settings.m_log2Interp);
         }
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency) || force) {
         reverseAPIKeys.append("centerFrequency");
     }
     if ((m_settings.m_transverterMode != settings.m_transverterMode) || force) {
         reverseAPIKeys.append("transverterMode");
     }
     if ((m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency) || force) {
         reverseAPIKeys.append("transverterDeltaFrequency");
     }
     if ((m_settings.m_LOppmTenths != settings.m_LOppmTenths) || force) {
         reverseAPIKeys.append("LOppmTenths");
     }
     if ((m_settings.m_centerFrequency != settings.m_centerFrequency)
         || (m_settings.m_transverterMode != settings.m_transverterMode)
         || (m_settings.m_transverterDeltaFrequency != settings.m_transverterDeltaFrequency)
         || (m_settings.m_LOppmTenths != settings.m_LOppmTenths)
         || (m_settings.m_devSampleRate != settings.m_devSampleRate) || force)
     {
         forwardChangeOwnDSP = true;
         forwardChangeTxBuddies = true;
         if (dev != 0)
         {
             if (setDeviceCenterFrequency(dev, requestedChannel, deviceCenterFrequency, settings.m_LOppmTenths))
             {
                 if (getMessageQueueToGUI())
                 {
                     int min, max, step;
                     getGlobalGainRange(min, max, step);
                     MsgReportGainRange *msg = MsgReportGainRange::create(min, max, step);
                     getMessageQueueToGUI()->push(msg);
                 }
             }
         }
     }
     if ((m_settings.m_biasTee != settings.m_biasTee) || force)
     {
         reverseAPIKeys.append("biasTee");
         forwardChangeTxBuddies = true;
         m_deviceShared.m_dev->setBiasTeeTx(settings.m_biasTee);
     }
     if ((m_settings.m_globalGain != settings.m_globalGain) || force)
     {
         reverseAPIKeys.append("globalGain");
         forwardChangeTxBuddies = true;
         if (dev)
         {
 //            qDebug("BladeRF2Output::applySettings: channel: %d gain: %d", requestedChannel, settings.m_globalGain);
             int status = bladerf_set_gain(dev, BLADERF_CHANNEL_TX(requestedChannel), settings.m_globalGain);
             if (status < 0) {
                 qWarning("BladeRF2Output::applySettings: bladerf_set_gain(%d) failed: %s",
                         settings.m_globalGain, bladerf_strerror(status));
             } else {
                 qDebug("BladeRF2Output::applySettings: bladerf_set_gain(%d)", settings.m_globalGain);
             }
         }
     }
     if (forwardChangeOwnDSP)
     {
         int sampleRate = settings.m_devSampleRate/(1<<settings.m_log2Interp);
         DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, settings.m_centerFrequency);
         m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     }
     if (forwardChangeRxBuddies)
     {
         // send to source buddies
         const std::vector<DeviceAPI*>& sourceBuddies = m_deviceAPI->getSourceBuddies();
         std::vector<DeviceAPI*>::const_iterator itSource = sourceBuddies.begin();
         for (; itSource != sourceBuddies.end(); ++itSource)
         {
             DeviceBladeRF2Shared::MsgReportBuddyChange *report = DeviceBladeRF2Shared::MsgReportBuddyChange::create(
                     settings.m_centerFrequency,
                     settings.m_LOppmTenths,
                     2,
                     settings.m_devSampleRate, // need to forward actual rate to the Rx side
                     false);
             (*itSource)->getSamplingDeviceInputMessageQueue()->push(report);
         }
     }
     if (forwardChangeTxBuddies)
     {
         // send to sink buddies
         const std::vector<DeviceAPI*>& sinkBuddies = m_deviceAPI->getSinkBuddies();
         std::vector<DeviceAPI*>::const_iterator itSink = sinkBuddies.begin();
         for (; itSink != sinkBuddies.end(); ++itSink)
         {
             DeviceBladeRF2Shared::MsgReportBuddyChange *report = DeviceBladeRF2Shared::MsgReportBuddyChange::create(
                     settings.m_centerFrequency,
                     settings.m_LOppmTenths,
                     2,
                     settings.m_devSampleRate,
                     false);
             (*itSink)->getSamplingDeviceInputMessageQueue()->push(report);
         }
     }
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     qDebug() << "BladeRF2Output::applySettings: "
             << " m_transverterMode: " << m_settings.m_transverterMode
             << " m_transverterDeltaFrequency: " << m_settings.m_transverterDeltaFrequency
             << " deviceCenterFrequency: " << deviceCenterFrequency
             << " m_centerFrequency: " << m_settings.m_centerFrequency << " Hz"
             << " m_LOppmTenths: " << m_settings.m_LOppmTenths
             << " m_bandwidth: " << m_settings.m_bandwidth
             << " m_log2Interp: " << m_settings.m_log2Interp
             << " m_devSampleRate: " << m_settings.m_devSampleRate
             << " nbChannels: " << nbChannels
             << " m_globalGain: " << m_settings.m_globalGain
             << " m_biasTee: " << m_settings.m_biasTee;
     return true;
 }
closeDevice()
void BladeRF2Output::closeDevice () private
Definition at line 150 of file bladerf2output.cpp.
References DeviceBladeRF2::close(), DeviceAPI::getSinkBuddies(), DeviceAPI::getSourceBuddies(), DeviceBladeRF2Shared::m_channel, DeviceBladeRF2Shared::m_dev, m_deviceAPI, m_deviceShared, m_running, DeviceBladeRF2Shared::m_sink, m_thread, moveThreadToBuddy(), and stop().
Referenced by ~BladeRF2Output().
 {
     if (m_deviceShared.m_dev == 0) { // was never open
         return;
     }
     if (m_running) {
         stop();
     }
     if (m_thread) { // stills own the thread => transfer to a buddy
         moveThreadToBuddy();
     }
     m_deviceShared.m_channel = -1; // publicly release channel
     m_deviceShared.m_sink = 0;
     // No buddies so effectively close the device
     if ((m_deviceAPI->getSinkBuddies().size() == 0) && (m_deviceAPI->getSourceBuddies().size() == 0))
     {
         m_deviceShared.m_dev->close();
         delete m_deviceShared.m_dev;
         m_deviceShared.m_dev = 0;
     }
 }
deserialize()
bool BladeRF2Output::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSink.
Definition at line 487 of file bladerf2output.cpp.
References BladeRF2Output::MsgConfigureBladeRF2::create(), BladeRF2OutputSettings::deserialize(), DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and BladeRF2OutputSettings::resetToDefaults().
Referenced by setThread().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureBladeRF2* message = MsgConfigureBladeRF2::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureBladeRF2* messageToGUI = MsgConfigureBladeRF2::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void BladeRF2Output::destroy () virtual
Implements DeviceSampleSink.
Definition at line 71 of file bladerf2output.cpp.
Referenced by BladeRF2Output::MsgReportGainRange::MsgReportGainRange().
 {
     delete this;
 }
findThread()
BladeRF2OutputThread * BladeRF2Output::findThread () private
Definition at line 182 of file bladerf2output.cpp.
References DeviceAPI::getSinkBuddies(), getThread(), m_deviceAPI, and m_thread.
Referenced by applySettings(), getNbChannels(), start(), and stop().
 {
     if (m_thread == 0) // this does not own the thread
     {
         BladeRF2OutputThread *bladeRF2OutputThread = 0;
         // find a buddy that has allocated the thread
         const std::vector<DeviceAPI*>& sinkBuddies = m_deviceAPI->getSinkBuddies();
         std::vector<DeviceAPI*>::const_iterator it = sinkBuddies.begin();
         for (; it != sinkBuddies.end(); ++it)
         {
             BladeRF2Output *buddySink = ((DeviceBladeRF2Shared*) (*it)->getBuddySharedPtr())->m_sink;
             if (buddySink)
             {
                 bladeRF2OutputThread = buddySink->getThread();
                 if (bladeRF2OutputThread) {
                     break;
                 }
             }
         }
         return bladeRF2OutputThread;
     }
     else
     {
         return m_thread; // own thread
     }
 }
getBandwidthRange()
void BladeRF2Output::getBandwidthRange (int & min, int & max, int & step)
Definition at line 573 of file bladerf2output.cpp.
References DeviceBladeRF2::getBandwidthRangeTx(), DeviceBladeRF2Shared::m_dev, and m_deviceShared.
Referenced by BladeRF2OutputGui::BladeRF2OutputGui(), and setSampleRate().
 {
     if (m_deviceShared.m_dev) {
         m_deviceShared.m_dev->getBandwidthRangeTx(min, max, step);
     }
 }
getCenterFrequency()
quint64 BladeRF2Output::getCenterFrequency () const virtual
Center frequency exposed by the sink.
Implements DeviceSampleSink.
Definition at line 520 of file bladerf2output.cpp.
References BladeRF2OutputSettings::m_centerFrequency, and m_settings.
Referenced by setSampleRate().
 {
     return m_settings.m_centerFrequency;
 }
getDeviceDescription()
const QString & BladeRF2Output::getDeviceDescription () const virtual
Implements DeviceSampleSink.
Definition at line 509 of file bladerf2output.cpp.
References m_deviceDescription.
Referenced by setMessageQueueToGUI().
 {
     return m_deviceDescription;
 }
getFrequencyRange()
void BladeRF2Output::getFrequencyRange (uint64_t & min, uint64_t & max, int & step)
Definition at line 559 of file bladerf2output.cpp.
References DeviceBladeRF2::getFrequencyRangeTx(), DeviceBladeRF2Shared::m_dev, and m_deviceShared.
Referenced by BladeRF2OutputGui::BladeRF2OutputGui(), setSampleRate(), and BladeRF2OutputGui::updateFrequencyLimits().
 {
     if (m_deviceShared.m_dev) {
         m_deviceShared.m_dev->getFrequencyRangeTx(min, max, step);
     }
 }
getGlobalGainRange()
void BladeRF2Output::getGlobalGainRange (int & min, int & max, int & step)
Definition at line 580 of file bladerf2output.cpp.
References DeviceBladeRF2::getGlobalGainRangeTx(), DeviceBladeRF2Shared::m_dev, and m_deviceShared.
Referenced by applySettings(), BladeRF2OutputGui::BladeRF2OutputGui(), BladeRF2OutputGui::handleMessage(), and setSampleRate().
 {
     if (m_deviceShared.m_dev) {
         m_deviceShared.m_dev->getGlobalGainRangeTx(min, max, step);
     }
 }
getNbChannels()
int BladeRF2Output::getNbChannels () private
Definition at line 939 of file bladerf2output.cpp.
References findThread(), and BladeRF2OutputThread::getNbChannels().
Referenced by applySettings().
 {
     BladeRF2OutputThread *bladeRF2OutputThread = findThread();
     if (bladeRF2OutputThread) {
         return bladeRF2OutputThread->getNbChannels();
     } else {
         return 0;
     }
 }
getSampleRate()
int BladeRF2Output::getSampleRate () const virtual
Sample rate exposed by the sink.
Implements DeviceSampleSink.
Definition at line 514 of file bladerf2output.cpp.
References BladeRF2OutputSettings::m_devSampleRate, BladeRF2OutputSettings::m_log2Interp, and m_settings.
Referenced by setMessageQueueToGUI().
 {
     int rate = m_settings.m_devSampleRate;
     return (rate / (1<<m_settings.m_log2Interp));
 }
getSampleRateRange()
void BladeRF2Output::getSampleRateRange (int & min, int & max, int & step)
Definition at line 566 of file bladerf2output.cpp.
References DeviceBladeRF2::getSampleRateRangeTx(), DeviceBladeRF2Shared::m_dev, and m_deviceShared.
Referenced by BladeRF2OutputGui::BladeRF2OutputGui(), BladeRF2OutputGui::displaySampleRate(), and setSampleRate().
 {
     if (m_deviceShared.m_dev) {
         m_deviceShared.m_dev->getSampleRateRangeTx(min, max, step);
     }
 }
getThread()
BladeRF2OutputThread* BladeRF2Output::getThread () inline
Definition at line 113 of file bladerf2output.h.
References m_thread.
Referenced by findThread().
 { return m_thread; }
handleMessage()
bool BladeRF2Output::handleMessage (const Message & message) virtual
Implements DeviceSampleSink.
Definition at line 587 of file bladerf2output.cpp.
References applySettings(), BladeRF2Output::MsgConfigureBladeRF2::create(), DeviceBladeRF2Shared::MsgReportBuddyChange::getCenterFrequency(), DeviceBladeRF2::getDev(), DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceAPI::getDeviceItemIndex(), DeviceBladeRF2Shared::MsgReportBuddyChange::getDevSampleRate(), BladeRF2Output::MsgConfigureBladeRF2::getForce(), DeviceBladeRF2Shared::MsgReportBuddyChange::getLOppmTenths(), DeviceSampleSink::getMessageQueueToGUI(), DeviceBladeRF2Shared::MsgReportBuddyChange::getRxElseTx(), BladeRF2Output::MsgConfigureBladeRF2::getSettings(), BladeRF2Output::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), BladeRF2OutputSettings::m_bandwidth, BladeRF2OutputSettings::m_biasTee, BladeRF2OutputSettings::m_centerFrequency, DeviceBladeRF2Shared::m_dev, m_deviceAPI, m_deviceShared, BladeRF2OutputSettings::m_devSampleRate, BladeRF2OutputSettings::m_log2Interp, BladeRF2OutputSettings::m_LOppmTenths, m_settings, BladeRF2OutputSettings::m_useReverseAPI, Message::match(), MessageQueue::push(), DeviceAPI::startDeviceEngine(), DeviceAPI::stopDeviceEngine(), and webapiReverseSendStartStop().
Referenced by setSampleRate().
 {
     if (MsgConfigureBladeRF2::match(message))
     {
         MsgConfigureBladeRF2& conf = (MsgConfigureBladeRF2&) message;
         qDebug() << "BladeRF2Output::handleMessage: MsgConfigureBladeRF2";
         if (!applySettings(conf.getSettings(), conf.getForce()))
         {
             qDebug("BladeRF2Output::handleMessage: MsgConfigureBladeRF2 config error");
         }
         return true;
     }
     else if (DeviceBladeRF2Shared::MsgReportBuddyChange::match(message))
     {
         DeviceBladeRF2Shared::MsgReportBuddyChange& report = (DeviceBladeRF2Shared::MsgReportBuddyChange&) message;
         struct bladerf *dev = m_deviceShared.m_dev->getDev();
         BladeRF2OutputSettings settings = m_settings;
         int status;
         unsigned int tmp_uint;
         bool tmp_bool;
         // evaluate changes that may have been introduced by changes in a buddy
         if (dev) // The BladeRF device must have been open to do so
         {
             int requestedChannel = m_deviceAPI->getDeviceItemIndex();
             if (report.getRxElseTx()) // Rx buddy change: check for sample rate change only
             {
                 settings.m_devSampleRate = report.getDevSampleRate();
 //                status = bladerf_get_sample_rate(dev, BLADERF_CHANNEL_TX(requestedChannel), &tmp_uint);
 //
 //                if (status < 0) {
 //                    qCritical("BladeRF2Output::handleMessage: MsgReportBuddyChange: bladerf_get_sample_rate error: %s", bladerf_strerror(status));
 //                } else {
 //                    settings.m_devSampleRate = tmp_uint;
 //                }
             }
             else // Tx buddy change: check for: frequency, gain mode and value, bias tee, sample rate, bandwidth
             {
                 settings.m_devSampleRate = report.getDevSampleRate();
                 settings.m_LOppmTenths = report.getLOppmTenths();
                 settings.m_centerFrequency = report.getCenterFrequency();
                 status = bladerf_get_bandwidth(dev, BLADERF_CHANNEL_TX(requestedChannel), &tmp_uint);
                 if (status < 0) {
                     qCritical("BladeRF2Output::handleMessage: MsgReportBuddyChange: bladerf_get_bandwidth error: %s", bladerf_strerror(status));
                 } else {
                     settings.m_bandwidth = tmp_uint;
                 }
                 status = bladerf_get_bias_tee(dev, BLADERF_CHANNEL_TX(requestedChannel), &tmp_bool);
                 if (status < 0) {
                     qCritical("BladeRF2Output::handleMessage: MsgReportBuddyChange: bladerf_get_bias_tee error: %s", bladerf_strerror(status));
                 } else {
                     settings.m_biasTee = tmp_bool;
                 }
             }
             // change DSP settings if buddy change introduced a change in center frequency or base rate
             if ((settings.m_centerFrequency != m_settings.m_centerFrequency) || (settings.m_devSampleRate != m_settings.m_devSampleRate))
             {
                 int sampleRate = settings.m_devSampleRate/(1<<settings.m_log2Interp);
                 DSPSignalNotification *notif = new DSPSignalNotification(sampleRate, settings.m_centerFrequency);
                 m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
             }
             m_settings = settings; // acknowledge the new settings
             // propagate settings to GUI if any
             if (getMessageQueueToGUI())
             {
                 MsgConfigureBladeRF2 *reportToGUI = MsgConfigureBladeRF2::create(m_settings, false);
                 getMessageQueueToGUI()->push(reportToGUI);
             }
         }
         return true;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "BladeRF2Input::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void BladeRF2Output::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSink.
Definition at line 177 of file bladerf2output.cpp.
References applySettings(), and m_settings.
Referenced by BladeRF2Output::MsgReportGainRange::MsgReportGainRange().
 {
     applySettings(m_settings, true);
 }
moveThreadToBuddy()
void BladeRF2Output::moveThreadToBuddy () private
Definition at line 214 of file bladerf2output.cpp.
References DeviceAPI::getSinkBuddies(), m_deviceAPI, m_thread, and setThread().
Referenced by closeDevice().
 {
     const std::vector<DeviceAPI*>& sinkBuddies = m_deviceAPI->getSinkBuddies();
     std::vector<DeviceAPI*>::const_iterator it = sinkBuddies.begin();
     for (; it != sinkBuddies.end(); ++it)
     {
         BladeRF2Output *buddySink = ((DeviceBladeRF2Shared*) (*it)->getBuddySharedPtr())->m_sink;
         if (buddySink)
         {
             buddySink->setThread(m_thread);
             m_thread = 0;  // zero for others
         }
     }
 }
networkManagerFinished
void BladeRF2Output::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 1208 of file bladerf2output.cpp.
Referenced by ~BladeRF2Output().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "BladeRF2Output::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("BladeRF2Output::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
openDevice()
bool BladeRF2Output::openDevice () private
Definition at line 76 of file bladerf2output.cpp.
References DeviceAPI::getBuddySharedPtr(), DeviceAPI::getDeviceItemIndex(), DeviceAPI::getSamplingDeviceSerial(), DeviceAPI::getSinkBuddies(), DeviceAPI::getSourceBuddies(), DeviceBladeRF2Shared::m_channel, DeviceBladeRF2Shared::m_dev, m_deviceAPI, m_deviceShared, BladeRF2OutputSettings::m_devSampleRate, BladeRF2OutputSettings::m_log2Interp, DeviceSampleSink::m_sampleSourceFifo, m_settings, DeviceBladeRF2Shared::m_sink, DeviceBladeRF2::open(), SampleSourceFifo::resize(), and DeviceAPI::setBuddySharedPtr().
 {
     m_sampleSourceFifo.resize(m_settings.m_devSampleRate/(1<<(m_settings.m_log2Interp <= 4 ? m_settings.m_log2Interp : 4)));
     // look for Tx buddies and get reference to the device object
     if (m_deviceAPI->getSinkBuddies().size() > 0) // look sink sibling first
     {
         qDebug("BladeRF2Output::openDevice: look in Tx buddies");
         DeviceAPI *sinkBuddy = m_deviceAPI->getSinkBuddies()[0];
         DeviceBladeRF2Shared *deviceBladeRF2Shared = (DeviceBladeRF2Shared*) sinkBuddy->getBuddySharedPtr();
         if (deviceBladeRF2Shared == 0)
         {
             qCritical("BladeRF2Output::openDevice: the sink buddy shared pointer is null");
             return false;
         }
         DeviceBladeRF2 *device = deviceBladeRF2Shared->m_dev;
         if (device == 0)
         {
             qCritical("BladeRF2Output::openDevice: cannot get device pointer from Tx buddy");
             return false;
         }
         m_deviceShared.m_dev = device;
     }
     // look for Rx buddies and get reference to the device object
     else if (m_deviceAPI->getSourceBuddies().size() > 0) // then source
     {
         qDebug("BladeRF2Output::openDevice: look in Rx buddies");
         DeviceAPI *sourceBuddy = m_deviceAPI->getSourceBuddies()[0];
         DeviceBladeRF2Shared *deviceBladeRF2Shared = (DeviceBladeRF2Shared*) sourceBuddy->getBuddySharedPtr();
         if (deviceBladeRF2Shared == 0)
         {
             qCritical("BladeRF2Output::openDevice: the source buddy shared pointer is null");
             return false;
         }
         DeviceBladeRF2 *device = deviceBladeRF2Shared->m_dev;
         if (device == 0)
         {
             qCritical("BladeRF2Output::openDevice: cannot get device pointer from Rx buddy");
             return false;
         }
         m_deviceShared.m_dev = device;
     }
     // There are no buddies then create the first BladeRF2 device
     else
     {
         qDebug("BladeRF2Output::openDevice: open device here");
         m_deviceShared.m_dev = new DeviceBladeRF2();
         char serial[256];
         strcpy(serial, qPrintable(m_deviceAPI->getSamplingDeviceSerial()));
         if (!m_deviceShared.m_dev->open(serial))
         {
             qCritical("BladeRF2Output::openDevice: cannot open BladeRF2 device");
             return false;
         }
     }
     m_deviceShared.m_channel = m_deviceAPI->getDeviceItemIndex(); // publicly allocate channel
     m_deviceShared.m_sink = this;
     m_deviceAPI->setBuddySharedPtr(&m_deviceShared); // propagate common parameters to API
     return true;
 }
serialize()
QByteArray BladeRF2Output::serialize () const virtual
Implements DeviceSampleSink.
Definition at line 482 of file bladerf2output.cpp.
References m_settings, and BladeRF2OutputSettings::serialize().
Referenced by setThread().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void BladeRF2Output::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSink.
Definition at line 525 of file bladerf2output.cpp.
References BladeRF2Output::MsgConfigureBladeRF2::create(), BladeRF2OutputSettings::m_centerFrequency, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, m_settings, and MessageQueue::push().
Referenced by setSampleRate().
 {
     BladeRF2OutputSettings settings = m_settings;
     settings.m_centerFrequency = centerFrequency;
     MsgConfigureBladeRF2* message = MsgConfigureBladeRF2::create(settings, false);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureBladeRF2* messageToGUI = MsgConfigureBladeRF2::create(settings, false);
         m_guiMessageQueue->push(messageToGUI);
     }
 }
setDeviceCenterFrequency()
bool BladeRF2Output::setDeviceCenterFrequency (struct bladerf * dev, int requestedChannel, quint64 freq_hz, int loPpmTenths) private
Definition at line 540 of file bladerf2output.cpp.
Referenced by applySettings().
 {
     qint64 df = ((qint64)freq_hz * loPpmTenths) / 10000000LL;
     freq_hz += df;
     int status = bladerf_set_frequency(dev, BLADERF_CHANNEL_TX(requestedChannel), freq_hz);
     if (status < 0) {
         qWarning("BladeRF2Output::setDeviceCenterFrequency: bladerf_set_frequency(%lld) failed: %s",
                 freq_hz, bladerf_strerror(status));
         return false;
     }
     else
     {
         qDebug("BladeRF2Output::setDeviceCenterFrequency: bladerf_set_frequency(%lld)", freq_hz);
         return true;
     }
 }
setMessageQueueToGUI()
virtual void BladeRF2Output::setMessageQueueToGUI (MessageQueue * queue) inline virtual
Implements DeviceSampleSink.
Definition at line 119 of file bladerf2output.h.
References getDeviceDescription(), getSampleRate(), and DeviceSampleSink::m_guiMessageQueue.
Referenced by BladeRF2OutputGui::BladeRF2OutputGui().
 { m_guiMessageQueue = queue; }
setSampleRate()
virtual void BladeRF2Output::setSampleRate (int sampleRate) inline virtual
For when the sink sample rate is set externally.
Implements DeviceSampleSink.
Definition at line 122 of file bladerf2output.h.
References getBandwidthRange(), getCenterFrequency(), getFrequencyRange(), getGlobalGainRange(), getSampleRateRange(), handleMessage(), leansdr::max(), leansdr::min(), setCenterFrequency(), webapiReportGet(), webapiRun(), webapiRunGet(), webapiSettingsGet(), and webapiSettingsPutPatch().
 { (void) sampleRate; }
setThread()
void BladeRF2Output::setThread (BladeRF2OutputThread * thread) inline
Definition at line 114 of file bladerf2output.h.
References deserialize(), m_thread, and serialize().
Referenced by moveThreadToBuddy().
 { m_thread = thread; }
start()
bool BladeRF2Output::start () virtual
Implements DeviceSampleSink.
Definition at line 231 of file bladerf2output.cpp.
References applySettings(), DeviceBladeRF2::closeTx(), findThread(), DeviceBladeRF2::getDev(), DeviceAPI::getDeviceItemIndex(), BladeRF2OutputThread::getFifo(), BladeRF2OutputThread::getLog2Interpolation(), BladeRF2OutputThread::getNbChannels(), DeviceAPI::getSinkBuddies(), i, DeviceBladeRF2Shared::m_dev, m_deviceAPI, m_deviceShared, BladeRF2OutputSettings::m_log2Interp, m_running, DeviceSampleSink::m_sampleSourceFifo, m_settings, m_thread, DeviceBladeRF2::openTx(), BladeRF2OutputThread::setFifo(), BladeRF2OutputThread::setLog2Interpolation(), BladeRF2OutputThread::startWork(), and BladeRF2OutputThread::stopWork().
Referenced by BladeRF2Output::MsgReportGainRange::MsgReportGainRange().
 {
     // There is a single thread per physical device (Tx side). This thread is unique and referenced by a unique
     // buddy in the group of sink buddies associated with this physical device.
     //
     // This start method is responsible for managing the thread and channel enabling when the streaming of a Tx channel is started
     //
     // It checks the following conditions
     //   - the thread is allocated or not (by itself or one of its buddies). If it is it grabs the thread pointer.
     //   - the requested channel is the first (0) or the following (just 1 in BladeRF 2 case)
     //
     // The BladeRF support library lets you work in two possible modes:
     //   - Single Output (SO) with only one channel streaming. This HAS to be channel 0.
     //   - Multiple Output (MO) with two channels streaming using interleaved samples. It MUST be in this configuration if channel 1
     //     is used. When we will run with only channel 1 streaming from the client perspective the channel 0 will actually be enabled
     //     and streaming but zero samples will be sent to it.
     //
     // It manages the transition form SO where only one channel (the first or channel 0) should be running to the
     // Multiple Output (MO) if the requested channel is 1. More generally it checks if the requested channel is within the current
     // channel range allocated in the thread or past it. To perform the transition it stops the thread, deletes it and creates a new one.
     // It marks the thread as needing start.
     //
     // If the requested channel is within the thread channel range (this thread being already allocated) it simply removes its FIFO reference
     // so that the samples are not taken from the FIFO anymore and leaves the thread unchanged (no stop, no delete/new)
     //
     // If there is no thread allocated it creates a new one with a number of channels that fits the requested channel. That is
     // 1 if channel 0 is requested (SO mode) and 2 if channel 1 is requested (MO mode). It marks the thread as needing start.
     //
     // Eventually it registers the FIFO in the thread. If the thread has to be started it enables the channels up to the number of channels
     // allocated in the thread and starts the thread.
     if (!m_deviceShared.m_dev)
     {
         qDebug("BladeRF2Output::start: no device object");
         return false;
     }
     int requestedChannel = m_deviceAPI->getDeviceItemIndex();
     BladeRF2OutputThread *bladeRF2OutputThread = findThread();
     bool needsStart = false;
     if (bladeRF2OutputThread) // if thread is already allocated
     {
         qDebug("BladeRF2Output::start: thread is already allocated");
         int nbOriginalChannels = bladeRF2OutputThread->getNbChannels();
         if (requestedChannel+1 > nbOriginalChannels) // expansion by deleting and re-creating the thread
         {
             qDebug("BladeRF2Output::start: expand channels. Re-allocate thread and take ownership");
             SampleSourceFifo **fifos = new SampleSourceFifo*[nbOriginalChannels];
             unsigned int *log2Interps = new unsigned int[nbOriginalChannels];
             for (int i = 0; i < nbOriginalChannels; i++) // save original FIFO references and data
             {
                 fifos[i] = bladeRF2OutputThread->getFifo(i);
                 log2Interps[i] = bladeRF2OutputThread->getLog2Interpolation(i);
             }
             bladeRF2OutputThread->stopWork();
             delete bladeRF2OutputThread;
             bladeRF2OutputThread = new BladeRF2OutputThread(m_deviceShared.m_dev->getDev(), requestedChannel+1);
             m_thread = bladeRF2OutputThread; // take ownership
             for (int i = 0; i < nbOriginalChannels; i++) // restore original FIFO references
             {
                 bladeRF2OutputThread->setFifo(i, fifos[i]);
                 bladeRF2OutputThread->setLog2Interpolation(i, log2Interps[i]);
             }
             // remove old thread address from buddies (reset in all buddies)
             const std::vector<DeviceAPI*>& sinkBuddies = m_deviceAPI->getSinkBuddies();
             std::vector<DeviceAPI*>::const_iterator it = sinkBuddies.begin();
             for (; it != sinkBuddies.end(); ++it) {
                 ((DeviceBladeRF2Shared*) (*it)->getBuddySharedPtr())->m_sink->setThread(0);
             }
             // close all channels
             for (int i = bladeRF2OutputThread->getNbChannels()-1; i >= 0; i--) {
                 m_deviceShared.m_dev->closeTx(i);
             }
             // was used as temporary storage:
             delete[] fifos;
             delete[] log2Interps;
             needsStart = true;
         }
         else
         {
             qDebug("BladeRF2Output::start: keep buddy thread");
         }
     }
     else // first allocation
     {
         qDebug("BladeRF2Output::start: allocate thread and take ownership");
         bladeRF2OutputThread = new BladeRF2OutputThread(m_deviceShared.m_dev->getDev(), requestedChannel+1);
         m_thread = bladeRF2OutputThread; // take ownership
         needsStart = true;
     }
     bladeRF2OutputThread->setFifo(requestedChannel, &m_sampleSourceFifo);
     bladeRF2OutputThread->setLog2Interpolation(requestedChannel, m_settings.m_log2Interp);
     applySettings(m_settings, true); // re-apply forcibly to set sample rate with the new number of channels
     if (needsStart)
     {
         qDebug("BladeRF2Output::start: enabling channel(s) and (re)starting the thread");
         for (unsigned int i = 0; i < bladeRF2OutputThread->getNbChannels(); i++) // open all channels
         {
             if (!m_deviceShared.m_dev->openTx(i)) {
                 qCritical("BladeRF2Output::start: channel %u cannot be enabled", i);
             }
         }
         bladeRF2OutputThread->startWork();
     }
     qDebug("BladeRF2Output::start: started");
     m_running = true;
     return true;
 }
stop()
void BladeRF2Output::stop () virtual
Implements DeviceSampleSink.
Definition at line 359 of file bladerf2output.cpp.
References applySettings(), DeviceBladeRF2::closeTx(), findThread(), DeviceBladeRF2::getDev(), DeviceAPI::getDeviceItemIndex(), BladeRF2OutputThread::getFifo(), BladeRF2OutputThread::getLog2Interpolation(), BladeRF2OutputThread::getNbChannels(), DeviceAPI::getSinkBuddies(), i, DeviceBladeRF2Shared::m_dev, m_deviceAPI, m_deviceShared, m_running, m_settings, m_thread, DeviceBladeRF2::openTx(), BladeRF2OutputThread::setFifo(), BladeRF2OutputThread::setLog2Interpolation(), BladeRF2OutputThread::startWork(), and BladeRF2OutputThread::stopWork().
Referenced by closeDevice(), BladeRF2Output::MsgReportGainRange::MsgReportGainRange(), and ~BladeRF2Output().
 {
     // This stop method is responsible for managing the thread and channel disabling when the streaming of
     // a Tx channel is stopped
     //
     // If the thread is currently managing only one channel (SO mode). The thread can be just stopped and deleted.
     // Then the channel is closed (disabled).
     //
     // If the thread is currently managing many channels (MO mode) and we are removing the last channel. The transition
     // from MO to SO or reduction of MO size is handled by stopping the thread, deleting it and creating a new one
     // with one channel less if (and only if) there is still a channel active.
     //
     // If the thread is currently managing many channels (MO mode) but the channel being stopped is not the last
     // channel then the FIFO reference is simply removed from the thread so that this FIFO will not be used anymore.
     // In this case the channel is not closed (disabled) so that other channels can continue with the
     // same configuration. The device continues streaming on this channel but the samples are set to all zeros.
     if (!m_running) {
         return;
     }
     int requestedChannel = m_deviceAPI->getDeviceItemIndex();
     BladeRF2OutputThread *bladeRF2OutputThread = findThread();
     if (bladeRF2OutputThread == 0) { // no thread allocated
         return;
     }
     int nbOriginalChannels = bladeRF2OutputThread->getNbChannels();
     if (nbOriginalChannels == 1) // SO mode => just stop and delete the thread
     {
         qDebug("BladeRF2Output::stop: SO mode. Just stop and delete the thread");
         bladeRF2OutputThread->stopWork();
         delete bladeRF2OutputThread;
         m_thread = 0;
         // remove old thread address from buddies (reset in all buddies)
         const std::vector<DeviceAPI*>& sinkBuddies = m_deviceAPI->getSinkBuddies();
         std::vector<DeviceAPI*>::const_iterator it = sinkBuddies.begin();
         for (; it != sinkBuddies.end(); ++it) {
             ((DeviceBladeRF2Shared*) (*it)->getBuddySharedPtr())->m_sink->setThread(0);
         }
         m_deviceShared.m_dev->closeTx(0); // close the unique channel
     }
     else if (requestedChannel == nbOriginalChannels - 1) // remove last MO channel => reduce by deleting and re-creating the thread
     {
         qDebug("BladeRF2Output::stop: MO mode. Reduce by deleting and re-creating the thread");
         bladeRF2OutputThread->stopWork();
         SampleSourceFifo **fifos = new SampleSourceFifo*[nbOriginalChannels-1];
         unsigned int *log2Interps = new unsigned int[nbOriginalChannels-1];
         bool stillActiveFIFO = false;
         for (int i = 0; i < nbOriginalChannels-1; i++) // save original FIFO references
         {
             fifos[i] = bladeRF2OutputThread->getFifo(i);
             stillActiveFIFO = stillActiveFIFO || (bladeRF2OutputThread->getFifo(i) != 0);
             log2Interps[i] = bladeRF2OutputThread->getLog2Interpolation(i);
         }
         delete bladeRF2OutputThread;
         m_thread = 0;
         if (stillActiveFIFO)
         {
             bladeRF2OutputThread = new BladeRF2OutputThread(m_deviceShared.m_dev->getDev(), nbOriginalChannels-1);
             m_thread = bladeRF2OutputThread; // take ownership
             for (int i = 0; i < nbOriginalChannels-1; i++)  // restore original FIFO references
             {
                 bladeRF2OutputThread->setFifo(i, fifos[i]);
                 bladeRF2OutputThread->setLog2Interpolation(i, log2Interps[i]);
             }
         }
         else
         {
             qDebug("BladeRF2Output::stop: do not re-create thread as there are no more FIFOs active");
         }
         // remove old thread address from buddies (reset in all buddies)
         const std::vector<DeviceAPI*>& sinkBuddies = m_deviceAPI->getSinkBuddies();
         std::vector<DeviceAPI*>::const_iterator it = sinkBuddies.begin();
         for (; it != sinkBuddies.end(); ++it) {
             ((DeviceBladeRF2Shared*) (*it)->getBuddySharedPtr())->m_sink->setThread(0);
         }
         // close all channels
         for (int i = nbOriginalChannels-1; i >= 0; i--) {
             m_deviceShared.m_dev->closeTx(i);
         }
         if (stillActiveFIFO)
         {
             qDebug("BladeRF2Output::stop: enabling channel(s) and restarting the thread");
             for (unsigned int i = 0; i < bladeRF2OutputThread->getNbChannels(); i++) // open all channels
             {
                 if (!m_deviceShared.m_dev->openTx(i)) {
                     qCritical("BladeRF2Output::start: channel %u cannot be enabled", i);
                 }
             }
             bladeRF2OutputThread->startWork();
         }
         // was used as temporary storage:
         delete[] fifos;
         delete[] log2Interps;
     }
     else // remove channel from existing thread
     {
         qDebug("BladeRF2Output::stop: MO mode. Not changing MO configuration. Just remove FIFO reference");
         bladeRF2OutputThread->setFifo(requestedChannel, 0); // remove FIFO
     }
     applySettings(m_settings, true); // re-apply forcibly to set sample rate with the new number of channels
     m_running = false;
 }
webapiFormatDeviceReport()
void BladeRF2Output::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 1056 of file bladerf2output.cpp.
References SWGSDRangel::SWGBladeRF2OutputReport::getBandwidthRange(), DeviceBladeRF2::getBandwidthRangeTx(), SWGSDRangel::SWGDeviceReport::getBladeRf2OutputReport(), SWGSDRangel::SWGBladeRF2OutputReport::getFrequencyRange(), DeviceBladeRF2::getFrequencyRangeTx(), SWGSDRangel::SWGBladeRF2OutputReport::getGlobalGainRange(), DeviceBladeRF2::getGlobalGainRangeTx(), SWGSDRangel::SWGBladeRF2OutputReport::getSampleRateRange(), DeviceBladeRF2::getSampleRateRangeTx(), DeviceBladeRF2Shared::m_dev, m_deviceShared, leansdr::max(), leansdr::min(), SWGSDRangel::SWGBladeRF2OutputReport::setBandwidthRange(), SWGSDRangel::SWGBladeRF2OutputReport::setFrequencyRange(), SWGSDRangel::SWGBladeRF2OutputReport::setGlobalGainRange(), SWGSDRangel::SWGFrequencyRange::setMax(), SWGSDRangel::SWGRange::setMax(), SWGSDRangel::SWGFrequencyRange::setMin(), SWGSDRangel::SWGRange::setMin(), SWGSDRangel::SWGBladeRF2OutputReport::setSampleRateRange(), SWGSDRangel::SWGRange::setStep(), and SWGSDRangel::SWGFrequencyRange::setStep().
Referenced by webapiReportGet().
 {
     DeviceBladeRF2 *device = m_deviceShared.m_dev;
     if (device)
     {
         int min, max, step;
         uint64_t f_min, f_max;
         device->getBandwidthRangeTx(min, max, step);
         response.getBladeRf2OutputReport()->setBandwidthRange(new SWGSDRangel::SWGRange);
         response.getBladeRf2OutputReport()->getBandwidthRange()->setMin(min);
         response.getBladeRf2OutputReport()->getBandwidthRange()->setMax(max);
         response.getBladeRf2OutputReport()->getBandwidthRange()->setStep(step);
         device->getFrequencyRangeTx(f_min, f_max, step);
         response.getBladeRf2OutputReport()->setFrequencyRange(new SWGSDRangel::SWGFrequencyRange);
         response.getBladeRf2OutputReport()->getFrequencyRange()->setMin(f_min);
         response.getBladeRf2OutputReport()->getFrequencyRange()->setMax(f_max);
         response.getBladeRf2OutputReport()->getFrequencyRange()->setStep(step);
         device->getGlobalGainRangeTx(min, max, step);
         response.getBladeRf2OutputReport()->setGlobalGainRange(new SWGSDRangel::SWGRange);
         response.getBladeRf2OutputReport()->getGlobalGainRange()->setMin(min);
         response.getBladeRf2OutputReport()->getGlobalGainRange()->setMax(max);
         response.getBladeRf2OutputReport()->getGlobalGainRange()->setStep(step);
         device->getSampleRateRangeTx(min, max, step);
         response.getBladeRf2OutputReport()->setSampleRateRange(new SWGSDRangel::SWGRange);
         response.getBladeRf2OutputReport()->getSampleRateRange()->setMin(min);
         response.getBladeRf2OutputReport()->getSampleRateRange()->setMax(max);
         response.getBladeRf2OutputReport()->getSampleRateRange()->setStep(step);
     }
 }
webapiFormatDeviceSettings()
void BladeRF2Output::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const BladeRF2OutputSettings & settings) private
Definition at line 1032 of file bladerf2output.cpp.
References SWGSDRangel::SWGDeviceSettings::getBladeRf2OutputSettings(), SWGSDRangel::SWGBladeRF2OutputSettings::getReverseApiAddress(), BladeRF2OutputSettings::m_bandwidth, BladeRF2OutputSettings::m_biasTee, BladeRF2OutputSettings::m_centerFrequency, BladeRF2OutputSettings::m_devSampleRate, BladeRF2OutputSettings::m_globalGain, BladeRF2OutputSettings::m_log2Interp, BladeRF2OutputSettings::m_LOppmTenths, BladeRF2OutputSettings::m_reverseAPIAddress, BladeRF2OutputSettings::m_reverseAPIDeviceIndex, BladeRF2OutputSettings::m_reverseAPIPort, BladeRF2OutputSettings::m_transverterDeltaFrequency, BladeRF2OutputSettings::m_transverterMode, BladeRF2OutputSettings::m_useReverseAPI, SWGSDRangel::SWGBladeRF2OutputSettings::setBandwidth(), SWGSDRangel::SWGBladeRF2OutputSettings::setBiasTee(), SWGSDRangel::SWGBladeRF2OutputSettings::setCenterFrequency(), SWGSDRangel::SWGBladeRF2OutputSettings::setDevSampleRate(), SWGSDRangel::SWGBladeRF2OutputSettings::setGlobalGain(), SWGSDRangel::SWGBladeRF2OutputSettings::setLog2Interp(), SWGSDRangel::SWGBladeRF2OutputSettings::setLOppmTenths(), SWGSDRangel::SWGBladeRF2OutputSettings::setReverseApiAddress(), SWGSDRangel::SWGBladeRF2OutputSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGBladeRF2OutputSettings::setReverseApiPort(), SWGSDRangel::SWGBladeRF2OutputSettings::setTransverterDeltaFrequency(), SWGSDRangel::SWGBladeRF2OutputSettings::setTransverterMode(), and SWGSDRangel::SWGBladeRF2OutputSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getBladeRf2OutputSettings()->setCenterFrequency(settings.m_centerFrequency);
     response.getBladeRf2OutputSettings()->setLOppmTenths(settings.m_LOppmTenths);
     response.getBladeRf2OutputSettings()->setDevSampleRate(settings.m_devSampleRate);
     response.getBladeRf2OutputSettings()->setBandwidth(settings.m_bandwidth);
     response.getBladeRf2OutputSettings()->setLog2Interp(settings.m_log2Interp);
     response.getBladeRf2OutputSettings()->setBiasTee(settings.m_biasTee ? 1 : 0);
     response.getBladeRf2OutputSettings()->setGlobalGain(settings.m_globalGain);
     response.getBladeRf2OutputSettings()->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     response.getBladeRf2OutputSettings()->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     response.getBladeRf2OutputSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getBladeRf2OutputSettings()->getReverseApiAddress()) {
         *response.getBladeRf2OutputSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getBladeRf2OutputSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getBladeRf2OutputSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getBladeRf2OutputSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int BladeRF2Output::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 1023 of file bladerf2output.cpp.
References SWGSDRangel::SWGDeviceReport::getBladeRf2OutputReport(), SWGSDRangel::SWGBladeRF2OutputReport::init(), SWGSDRangel::SWGDeviceReport::setBladeRf2OutputReport(), and webapiFormatDeviceReport().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setBladeRf2OutputReport(new SWGSDRangel::SWGBladeRF2OutputReport());
     response.getBladeRf2OutputReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void BladeRF2Output::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const BladeRF2OutputSettings & settings, bool force) private
Definition at line 1123 of file bladerf2output.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), SWGSDRangel::SWGDeviceSettings::getBladeRf2OutputSettings(), DeviceAPI::getDeviceSetIndex(), BladeRF2OutputSettings::m_bandwidth, BladeRF2OutputSettings::m_biasTee, BladeRF2OutputSettings::m_centerFrequency, m_deviceAPI, BladeRF2OutputSettings::m_devSampleRate, BladeRF2OutputSettings::m_globalGain, BladeRF2OutputSettings::m_log2Interp, BladeRF2OutputSettings::m_LOppmTenths, m_networkManager, m_networkRequest, BladeRF2OutputSettings::m_reverseAPIAddress, BladeRF2OutputSettings::m_reverseAPIDeviceIndex, BladeRF2OutputSettings::m_reverseAPIPort, BladeRF2OutputSettings::m_transverterDeltaFrequency, BladeRF2OutputSettings::m_transverterMode, SWGSDRangel::SWGBladeRF2OutputSettings::setBandwidth(), SWGSDRangel::SWGBladeRF2OutputSettings::setBiasTee(), SWGSDRangel::SWGDeviceSettings::setBladeRf2OutputSettings(), SWGSDRangel::SWGBladeRF2OutputSettings::setCenterFrequency(), SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGBladeRF2OutputSettings::setDevSampleRate(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGBladeRF2OutputSettings::setGlobalGain(), SWGSDRangel::SWGBladeRF2OutputSettings::setLog2Interp(), SWGSDRangel::SWGBladeRF2OutputSettings::setLOppmTenths(), SWGSDRangel::SWGDeviceSettings::setOriginatorIndex(), SWGSDRangel::SWGBladeRF2OutputSettings::setTransverterDeltaFrequency(), and SWGSDRangel::SWGBladeRF2OutputSettings::setTransverterMode().
Referenced by applySettings().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(1); // single Tx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("BladeRF2"));
     swgDeviceSettings->setBladeRf2OutputSettings(new SWGSDRangel::SWGBladeRF2OutputSettings());
     SWGSDRangel::SWGBladeRF2OutputSettings *swgBladeRF2OutputSettings = swgDeviceSettings->getBladeRf2OutputSettings();
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     if (deviceSettingsKeys.contains("centerFrequency") || force) {
         swgBladeRF2OutputSettings->setCenterFrequency(settings.m_centerFrequency);
     }
     if (deviceSettingsKeys.contains("LOppmTenths") || force) {
         swgBladeRF2OutputSettings->setLOppmTenths(settings.m_LOppmTenths);
     }
     if (deviceSettingsKeys.contains("devSampleRate") || force) {
         swgBladeRF2OutputSettings->setDevSampleRate(settings.m_devSampleRate);
     }
     if (deviceSettingsKeys.contains("bandwidth") || force) {
         swgBladeRF2OutputSettings->setBandwidth(settings.m_bandwidth);
     }
     if (deviceSettingsKeys.contains("log2Interp") || force) {
         swgBladeRF2OutputSettings->setLog2Interp(settings.m_log2Interp);
     }
     if (deviceSettingsKeys.contains("biasTee") || force) {
         swgBladeRF2OutputSettings->setBiasTee(settings.m_biasTee ? 1 : 0);
     }
     if (deviceSettingsKeys.contains("globalGain") || force) {
         swgBladeRF2OutputSettings->setGlobalGain(settings.m_globalGain);
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency") || force) {
         swgBladeRF2OutputSettings->setTransverterDeltaFrequency(settings.m_transverterDeltaFrequency);
     }
     if (deviceSettingsKeys.contains("transverterMode") || force) {
         swgBladeRF2OutputSettings->setTransverterMode(settings.m_transverterMode ? 1 : 0);
     }
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void BladeRF2Output::webapiReverseSendStartStop (bool start) private
Definition at line 1180 of file bladerf2output.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, BladeRF2OutputSettings::m_reverseAPIAddress, BladeRF2OutputSettings::m_reverseAPIDeviceIndex, BladeRF2OutputSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(1); // single Tx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("BladeRF2"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int BladeRF2Output::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 1104 of file bladerf2output.cpp.
References BladeRF2Output::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, and MessageQueue::push().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int BladeRF2Output::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 1095 of file bladerf2output.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by setSampleRate().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int BladeRF2Output::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 950 of file bladerf2output.cpp.
References SWGSDRangel::SWGDeviceSettings::getBladeRf2OutputSettings(), SWGSDRangel::SWGBladeRF2OutputSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setBladeRf2OutputSettings(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     response.setBladeRf2OutputSettings(new SWGSDRangel::SWGBladeRF2OutputSettings());
     response.getBladeRf2OutputSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int BladeRF2Output::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 961 of file bladerf2output.cpp.
References BladeRF2Output::MsgConfigureBladeRF2::create(), SWGSDRangel::SWGBladeRF2OutputSettings::getBandwidth(), SWGSDRangel::SWGBladeRF2OutputSettings::getBiasTee(), SWGSDRangel::SWGDeviceSettings::getBladeRf2OutputSettings(), SWGSDRangel::SWGBladeRF2OutputSettings::getCenterFrequency(), SWGSDRangel::SWGBladeRF2OutputSettings::getDevSampleRate(), SWGSDRangel::SWGBladeRF2OutputSettings::getGlobalGain(), SWGSDRangel::SWGBladeRF2OutputSettings::getLog2Interp(), SWGSDRangel::SWGBladeRF2OutputSettings::getLOppmTenths(), SWGSDRangel::SWGBladeRF2OutputSettings::getReverseApiAddress(), SWGSDRangel::SWGBladeRF2OutputSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGBladeRF2OutputSettings::getReverseApiPort(), SWGSDRangel::SWGBladeRF2OutputSettings::getTransverterDeltaFrequency(), SWGSDRangel::SWGBladeRF2OutputSettings::getTransverterMode(), SWGSDRangel::SWGBladeRF2OutputSettings::getUseReverseApi(), BladeRF2OutputSettings::m_bandwidth, BladeRF2OutputSettings::m_biasTee, BladeRF2OutputSettings::m_centerFrequency, BladeRF2OutputSettings::m_devSampleRate, BladeRF2OutputSettings::m_globalGain, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, BladeRF2OutputSettings::m_log2Interp, BladeRF2OutputSettings::m_LOppmTenths, BladeRF2OutputSettings::m_reverseAPIAddress, BladeRF2OutputSettings::m_reverseAPIDeviceIndex, BladeRF2OutputSettings::m_reverseAPIPort, m_settings, BladeRF2OutputSettings::m_transverterDeltaFrequency, BladeRF2OutputSettings::m_transverterMode, BladeRF2OutputSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by setSampleRate().
 {
     (void) errorMessage;
     BladeRF2OutputSettings settings = m_settings;
     if (deviceSettingsKeys.contains("centerFrequency")) {
         settings.m_centerFrequency = response.getBladeRf2OutputSettings()->getCenterFrequency();
     }
     if (deviceSettingsKeys.contains("LOppmTenths")) {
         settings.m_LOppmTenths = response.getBladeRf2OutputSettings()->getLOppmTenths();
     }
     if (deviceSettingsKeys.contains("devSampleRate")) {
         settings.m_devSampleRate = response.getBladeRf2OutputSettings()->getDevSampleRate();
     }
     if (deviceSettingsKeys.contains("bandwidth")) {
         settings.m_bandwidth = response.getBladeRf2OutputSettings()->getBandwidth();
     }
     if (deviceSettingsKeys.contains("log2Interp")) {
         settings.m_log2Interp = response.getBladeRf2OutputSettings()->getLog2Interp();
     }
     if (deviceSettingsKeys.contains("biasTee")) {
         settings.m_biasTee = response.getBladeRf2OutputSettings()->getBiasTee() != 0;
     }
     if (deviceSettingsKeys.contains("globalGain")) {
         settings.m_globalGain = response.getBladeRf2OutputSettings()->getGlobalGain();
     }
     if (deviceSettingsKeys.contains("transverterDeltaFrequency")) {
         settings.m_transverterDeltaFrequency = response.getBladeRf2OutputSettings()->getTransverterDeltaFrequency();
     }
     if (deviceSettingsKeys.contains("transverterMode")) {
         settings.m_transverterMode = response.getBladeRf2OutputSettings()->getTransverterMode() != 0;
     }
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getBladeRf2OutputSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getBladeRf2OutputSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getBladeRf2OutputSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getBladeRf2OutputSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureBladeRF2 *msg = MsgConfigureBladeRF2::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureBladeRF2 *msgToGUI = MsgConfigureBladeRF2::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_dev
struct bladerf* BladeRF2Output::m_dev private
Definition at line 160 of file bladerf2output.h.
m_deviceAPI
DeviceAPI* BladeRF2Output::m_deviceAPI private
Definition at line 157 of file bladerf2output.h.
Referenced by applySettings(), closeDevice(), findThread(), handleMessage(), moveThreadToBuddy(), openDevice(), start(), stop(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), and webapiRunGet().
m_deviceDescription
QString BladeRF2Output::m_deviceDescription private
Definition at line 162 of file bladerf2output.h.
Referenced by getDeviceDescription().
m_deviceShared
DeviceBladeRF2Shared BladeRF2Output::m_deviceShared private
Definition at line 163 of file bladerf2output.h.
Referenced by applySettings(), closeDevice(), getBandwidthRange(), getFrequencyRange(), getGlobalGainRange(), getSampleRateRange(), handleMessage(), openDevice(), start(), stop(), and webapiFormatDeviceReport().
m_mutex
QMutex BladeRF2Output::m_mutex private
Definition at line 158 of file bladerf2output.h.
m_networkManager
QNetworkAccessManager* BladeRF2Output::m_networkManager private
Definition at line 165 of file bladerf2output.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~BladeRF2Output().
m_networkRequest
QNetworkRequest BladeRF2Output::m_networkRequest private
Definition at line 166 of file bladerf2output.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_running
bool BladeRF2Output::m_running private
Definition at line 164 of file bladerf2output.h.
Referenced by closeDevice(), start(), stop(), and ~BladeRF2Output().
m_settings
BladeRF2OutputSettings BladeRF2Output::m_settings private
Definition at line 159 of file bladerf2output.h.
Referenced by applySettings(), deserialize(), getCenterFrequency(), getSampleRate(), handleMessage(), init(), openDevice(), serialize(), setCenterFrequency(), start(), stop(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
m_thread
BladeRF2OutputThread* BladeRF2Output::m_thread private
Definition at line 161 of file bladerf2output.h.
Referenced by closeDevice(), findThread(), getThread(), moveThreadToBuddy(), setThread(), start(), and stop().
The documentation for this class was generated from the following files:
plugins/samplesink/bladerf2output/bladerf2output.h
plugins/samplesink/bladerf2output/bladerf2output.cpp