SDRAngel: XTRXInput::MsgFileRecord Class Reference
XTRXInput::MsgFileRecord Class Reference
#include <xtrxinput.h>
Public Member Functions
bool getStartStop () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgFileRecord * create (bool startStop)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Protected Member Functions
MsgFileRecord (bool startStop)
Protected Attributes
bool m_startStop
Protected Attributes inherited from Message
void * m_destination
Additional Inherited Members
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 174 of file xtrxinput.h.
Constructor & Destructor Documentation
MsgFileRecord()
XTRXInput::MsgFileRecord::MsgFileRecord (bool startStop) inline protected
Definition at line 187 of file xtrxinput.h.
References XTRXInput::destroy(), XTRXInput::init(), XTRXInput::start(), XTRXInput::stop(), XTRXInput::XTRXInput(), and XTRXInput::~XTRXInput().
                                       :
             Message(),
             m_startStop(startStop)
         { }
Member Function Documentation
create()
static MsgFileRecord* XTRXInput::MsgFileRecord::create (bool startStop) inline static
Definition at line 180 of file xtrxinput.h.
Referenced by XTRXInputGUI::on_record_toggled().
{
             return new MsgFileRecord(startStop);
         }
getStartStop()
bool XTRXInput::MsgFileRecord::getStartStop () const inline
Definition at line 178 of file xtrxinput.h.
Referenced by XTRXInput::handleMessage().
 { return m_startStop; }
Member Data Documentation
m_startStop
bool XTRXInput::MsgFileRecord::m_startStop protected
Definition at line 185 of file xtrxinput.h.
The documentation for this class was generated from the following file:
plugins/samplesource/xtrxinput/xtrxinput.h