SDRAngel: SWGSDRangel::SWGDVSerialDevice Class Reference
SWGSDRangel::SWGDVSerialDevice Class Reference
#include <SWGDVSerialDevice.h>
Public Member Functions
SWGDVSerialDevice ()
SWGDVSerialDevice (QString *json)
virtual ~SWGDVSerialDevice ()
void init ()
void cleanup ()
virtual QString asJson () override
virtual QJsonObject * asJsonObject () override
virtual void fromJsonObject (QJsonObject &json) override
virtual SWGDVSerialDevice * fromJson (QString &jsonString) override
QString * getDeviceName ()
void setDeviceName (QString *device_name)
virtual bool isSet () override
Public Member Functions inherited from SWGSDRangel::SWGObject
virtual ~SWGObject ()
Private Attributes
QString * device_name
bool m_device_name_isSet
Detailed Description
Definition at line 32 of file SWGDVSerialDevice.h.
Constructor & Destructor Documentation
SWGDVSerialDevice() [1/2]
SWGSDRangel::SWGDVSerialDevice::SWGDVSerialDevice ()
Definition at line 30 of file SWGDVSerialDevice.cpp.
References device_name, and m_device_name_isSet.
{
     device_name = nullptr;
     m_device_name_isSet = false;
 }
SWGDVSerialDevice() [2/2]
SWGSDRangel::SWGDVSerialDevice::SWGDVSerialDevice (QString * json)
Definition at line 25 of file SWGDVSerialDevice.cpp.
References fromJson(), and init().
{
     init();
     this->fromJson(*json);
 }
~SWGDVSerialDevice()
SWGSDRangel::SWGDVSerialDevice::~SWGDVSerialDevice () virtual
Definition at line 35 of file SWGDVSerialDevice.cpp.
References cleanup().
{
     this->cleanup();
 }
Member Function Documentation
asJson()
QString SWGSDRangel::SWGDVSerialDevice::asJson () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 68 of file SWGDVSerialDevice.cpp.
References asJsonObject().
 {
     QJsonObject* obj = this->asJsonObject();
     QJsonDocument doc(*obj);
     QByteArray bytes = doc.toJson();
     delete obj;
     return QString(bytes);
 }
asJsonObject()
QJsonObject * SWGSDRangel::SWGDVSerialDevice::asJsonObject () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 79 of file SWGDVSerialDevice.cpp.
References device_name, and SWGSDRangel::toJsonValue().
Referenced by asJson().
{
     QJsonObject* obj = new QJsonObject();
     if(device_name != nullptr && *device_name != QString("")){
         toJsonValue(QString("deviceName"), device_name, obj, QString("QString"));
     }
     return obj;
 }
cleanup()
void SWGSDRangel::SWGDVSerialDevice::cleanup ()
Definition at line 46 of file SWGDVSerialDevice.cpp.
References device_name.
Referenced by ~SWGDVSerialDevice().
{
     if(device_name != nullptr) {
         delete device_name;
     }
 }
fromJson()
SWGDVSerialDevice * SWGSDRangel::SWGDVSerialDevice::fromJson (QString & jsonString) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 53 of file SWGDVSerialDevice.cpp.
References fromJsonObject().
Referenced by SWGDVSerialDevice().
{
     QByteArray array (json.toStdString().c_str());
     QJsonDocument doc = QJsonDocument::fromJson(array);
     QJsonObject jsonObject = doc.object();
     this->fromJsonObject(jsonObject);
     return this;
 }
fromJsonObject()
void SWGSDRangel::SWGDVSerialDevice::fromJsonObject (QJsonObject & json) override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 62 of file SWGDVSerialDevice.cpp.
References device_name, and SWGSDRangel::setValue().
Referenced by fromJson().
{
     ::SWGSDRangel::setValue(&device_name, pJson["deviceName"], "QString", "QString");
 }
getDeviceName()
QString * SWGSDRangel::SWGDVSerialDevice::getDeviceName ()
Definition at line 89 of file SWGDVSerialDevice.cpp.
References device_name.
{
     return device_name;
 }
init()
void SWGSDRangel::SWGDVSerialDevice::init ()
Definition at line 40 of file SWGDVSerialDevice.cpp.
References device_name, and m_device_name_isSet.
Referenced by SWGDVSerialDevice().
{
     device_name = new QString("");
     m_device_name_isSet = false;
 }
isSet()
bool SWGSDRangel::SWGDVSerialDevice::isSet () override virtual
Reimplemented from SWGSDRangel::SWGObject.
Definition at line 100 of file SWGDVSerialDevice.cpp.
References device_name.
{
     bool isObjectUpdated = false;
     do{
         if(device_name != nullptr && *device_name != QString("")){ isObjectUpdated = true; break;}
     }while(false);
     return isObjectUpdated;
 }
setDeviceName()
void SWGSDRangel::SWGDVSerialDevice::setDeviceName (QString * device_name)
Definition at line 93 of file SWGDVSerialDevice.cpp.
References device_name, and m_device_name_isSet.
{
     this->device_name = device_name;
     this->m_device_name_isSet = true;
 }
Member Data Documentation
device_name
QString* SWGSDRangel::SWGDVSerialDevice::device_name private
Definition at line 52 of file SWGDVSerialDevice.h.
Referenced by asJsonObject(), cleanup(), fromJsonObject(), getDeviceName(), init(), isSet(), setDeviceName(), and SWGDVSerialDevice().
m_device_name_isSet
bool SWGSDRangel::SWGDVSerialDevice::m_device_name_isSet private
Definition at line 53 of file SWGDVSerialDevice.h.
Referenced by init(), setDeviceName(), and SWGDVSerialDevice().
The documentation for this class was generated from the following files:
swagger/sdrangel/code/qt5/client/SWGDVSerialDevice.h
swagger/sdrangel/code/qt5/client/SWGDVSerialDevice.cpp