SDRAngel: LocalOutput Class Reference
LocalOutput Class Reference
#include <localoutput.h>
Classes
class MsgConfigureLocalOutput
class MsgReportSampleRateAndFrequency
class MsgStartStop
Public Member Functions
LocalOutput (DeviceAPI *deviceAPI)
virtual ~LocalOutput ()
virtual void destroy ()
virtual void init ()
initializations to be done when all collaborating objects are created and possibly connected
virtual bool start ()
virtual void stop ()
virtual QByteArray serialize () const
virtual bool deserialize (const QByteArray &data)
virtual void setMessageQueueToGUI (MessageQueue *queue)
virtual const QString & getDeviceDescription () const
virtual int getSampleRate () const
Sample rate exposed by the sink.
virtual void setSampleRate (int sampleRate)
For when the sink sample rate is set externally.
virtual quint64 getCenterFrequency () const
Center frequency exposed by the sink.
virtual void setCenterFrequency (qint64 centerFrequency)
std::time_t getStartingTimeStamp () const
virtual bool handleMessage (const Message &message)
virtual int webapiSettingsGet (SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiSettingsPutPatch (bool force, const QStringList &deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings &response, QString &errorMessage)
virtual int webapiReportGet (SWGSDRangel::SWGDeviceReport &response, QString &errorMessage)
virtual int webapiRunGet (SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
virtual int webapiRun (bool run, SWGSDRangel::SWGDeviceState &response, QString &errorMessage)
Public Member Functions inherited from DeviceSampleSink
DeviceSampleSink ()
virtual ~DeviceSampleSink ()
MessageQueue * getInputMessageQueue ()
MessageQueue * getMessageQueueToGUI ()
SampleSourceFifo * getSampleFifo ()
Private Slots
void networkManagerFinished (QNetworkReply *reply)
Private Member Functions
void applySettings (const LocalOutputSettings &settings, bool force=false)
void webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings &response, const LocalOutputSettings &settings)
void webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport &response)
void webapiReverseSendSettings (QList< QString > &deviceSettingsKeys, const LocalOutputSettings &settings, bool force)
void webapiReverseSendStartStop (bool start)
Private Attributes
DeviceAPI * m_deviceAPI
QMutex m_mutex
LocalOutputSettings m_settings
qint64 m_centerFrequency
int m_sampleRate
QString m_remoteAddress
QString m_deviceDescription
FileRecord * m_fileSink
File sink to record device I/Q output.
QNetworkAccessManager * m_networkManager
QNetworkRequest m_networkRequest
Additional Inherited Members
Public Types inherited from DeviceSampleSink
enum fcPos_t { FC_POS_INFRA = 0, FC_POS_SUPRA, FC_POS_CENTER }
Static Public Member Functions inherited from DeviceSampleSink
static qint64 calculateDeviceCenterFrequency (quint64 centerFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint64 calculateCenterFrequency (quint64 deviceCenterFrequency, qint64 transverterDeltaFrequency, int log2Interp, fcPos_t fcPos, quint32 devSampleRate, bool transverterMode=false)
static qint32 calculateFrequencyShift (int log2Interp, fcPos_t fcPos, quint32 devSampleRate)
Protected Slots inherited from DeviceSampleSink
void handleInputMessages ()
Protected Attributes inherited from DeviceSampleSink
SampleSourceFifo m_sampleSourceFifo
MessageQueue m_inputMessageQueue
Input queue to the sink.
MessageQueue * m_guiMessageQueue
Input message queue to the GUI.
Detailed Description
Definition at line 39 of file localoutput.h.
Constructor & Destructor Documentation
LocalOutput()
LocalOutput::LocalOutput (DeviceAPI * deviceAPI)
Definition at line 41 of file localoutput.cpp.
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
                                              :
     m_deviceAPI(deviceAPI),
     m_settings(),
     m_centerFrequency(0),
     m_sampleRate(48000),
     m_fileSink(nullptr),
     m_deviceDescription("LocalOutput")
 {
     m_sampleSourceFifo.resize(96000 * 4);
     m_deviceAPI->setNbSinkStreams(1);
     m_networkManager = new QNetworkAccessManager();
     connect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
 }
~LocalOutput()
LocalOutput::~LocalOutput () virtual
Definition at line 55 of file localoutput.cpp.
References m_networkManager, networkManagerFinished(), and stop().
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     disconnect(m_networkManager, SIGNAL(finished(QNetworkReply*)), this, SLOT(networkManagerFinished(QNetworkReply*)));
     delete m_networkManager;
     stop();
 }
Member Function Documentation
applySettings()
void LocalOutput::applySettings (const LocalOutputSettings & settings, bool force = false) private
Definition at line 200 of file localoutput.cpp.
References m_mutex, m_remoteAddress, LocalOutputSettings::m_reverseAPIAddress, LocalOutputSettings::m_reverseAPIDeviceIndex, LocalOutputSettings::m_reverseAPIPort, m_settings, LocalOutputSettings::m_useReverseAPI, and webapiReverseSendSettings().
Referenced by handleMessage(), and init().
 {
     QMutexLocker mutexLocker(&m_mutex);
     std::ostringstream os;
     QString remoteAddress;
     QList<QString> reverseAPIKeys;
     if (settings.m_useReverseAPI)
     {
         bool fullUpdate = ((m_settings.m_useReverseAPI != settings.m_useReverseAPI) && settings.m_useReverseAPI) ||
                 (m_settings.m_reverseAPIAddress != settings.m_reverseAPIAddress) ||
                 (m_settings.m_reverseAPIPort != settings.m_reverseAPIPort) ||
                 (m_settings.m_reverseAPIDeviceIndex != settings.m_reverseAPIDeviceIndex);
         webapiReverseSendSettings(reverseAPIKeys, settings, fullUpdate || force);
     }
     m_settings = settings;
     m_remoteAddress = remoteAddress;
     qDebug() << "LocalOutput::applySettings: "
             << " m_remoteAddress: " << m_remoteAddress;
 }
deserialize()
bool LocalOutput::deserialize (const QByteArray & data) virtual
Implements DeviceSampleSink.
Definition at line 88 of file localoutput.cpp.
References LocalOutput::MsgConfigureLocalOutput::create(), LocalOutputSettings::deserialize(), DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, m_settings, MessageQueue::push(), and LocalOutputSettings::resetToDefaults().
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     bool success = true;
     if (!m_settings.deserialize(data))
     {
         m_settings.resetToDefaults();
         success = false;
     }
     MsgConfigureLocalOutput* message = MsgConfigureLocalOutput::create(m_settings, true);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue)
     {
         MsgConfigureLocalOutput* messageToGUI = MsgConfigureLocalOutput::create(m_settings, true);
         m_guiMessageQueue->push(messageToGUI);
     }
     return success;
 }
destroy()
void LocalOutput::destroy () virtual
Implements DeviceSampleSink.
Definition at line 62 of file localoutput.cpp.
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     delete this;
 }
getCenterFrequency()
quint64 LocalOutput::getCenterFrequency () const virtual
Center frequency exposed by the sink.
Implements DeviceSampleSink.
Definition at line 139 of file localoutput.cpp.
References m_centerFrequency.
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     return m_centerFrequency;
 }
getDeviceDescription()
const QString & LocalOutput::getDeviceDescription () const virtual
Implements DeviceSampleSink.
Definition at line 115 of file localoutput.cpp.
References m_deviceDescription.
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     return m_deviceDescription;
 }
getSampleRate()
int LocalOutput::getSampleRate () const virtual
Sample rate exposed by the sink.
Implements DeviceSampleSink.
Definition at line 120 of file localoutput.cpp.
References m_sampleRate.
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     return m_sampleRate;
 }
getStartingTimeStamp()
std::time_t LocalOutput::getStartingTimeStamp () const
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
handleMessage()
bool LocalOutput::handleMessage (const Message & message) virtual
Implements DeviceSampleSink.
Definition at line 158 of file localoutput.cpp.
References applySettings(), LocalOutput::MsgConfigureLocalOutput::getForce(), Message::getIdentifier(), LocalOutput::MsgConfigureLocalOutput::getSettings(), LocalOutput::MsgStartStop::getStartStop(), DeviceAPI::initDeviceEngine(), m_deviceAPI, m_settings, LocalOutputSettings::m_useReverseAPI, Message::match(), DeviceAPI::startDeviceEngine(), DeviceAPI::stopDeviceEngine(), and webapiReverseSendStartStop().
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     if (DSPSignalNotification::match(message))
     {
         return false;
     }
     else if (MsgStartStop::match(message))
     {
         MsgStartStop& cmd = (MsgStartStop&) message;
         qDebug() << "LocalOutput::handleMessage: MsgStartStop: " << (cmd.getStartStop() ? "start" : "stop");
         if (cmd.getStartStop())
         {
             if (m_deviceAPI->initDeviceEngine())
             {
                 m_deviceAPI->startDeviceEngine();
             }
         }
         else
         {
             m_deviceAPI->stopDeviceEngine();
         }
         if (m_settings.m_useReverseAPI) {
             webapiReverseSendStartStop(cmd.getStartStop());
         }
         return true;
     }
     else if (MsgConfigureLocalOutput::match(message))
     {
         qDebug() << "LocalOutput::handleMessage:" << message.getIdentifier();
         MsgConfigureLocalOutput& conf = (MsgConfigureLocalOutput&) message;
         applySettings(conf.getSettings(), conf.getForce());
         return true;
     }
     else
     {
         return false;
     }
 }
init()
void LocalOutput::init () virtual
initializations to be done when all collaborating objects are created and possibly connected
Implements DeviceSampleSink.
Definition at line 67 of file localoutput.cpp.
References applySettings(), and m_settings.
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     applySettings(m_settings, true);
 }
networkManagerFinished
void LocalOutput::networkManagerFinished (QNetworkReply * reply) private slot
Definition at line 386 of file localoutput.cpp.
Referenced by ~LocalOutput().
 {
     QNetworkReply::NetworkError replyError = reply->error();
     if (replyError)
     {
         qWarning() << "LocalOutput::networkManagerFinished:"
                 << " error(" << (int) replyError
                 << "): " << replyError
                 << ": " << reply->errorString();
         return;
     }
     QString answer = reply->readAll();
     answer.chop(1); // remove last \n
     qDebug("LocalOutput::networkManagerFinished: reply:\n%s", answer.toStdString().c_str());
 }
serialize()
QByteArray LocalOutput::serialize () const virtual
Implements DeviceSampleSink.
Definition at line 83 of file localoutput.cpp.
References m_settings, and LocalOutputSettings::serialize().
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     return m_settings.serialize();
 }
setCenterFrequency()
void LocalOutput::setCenterFrequency (qint64 centerFrequency) virtual
Implements DeviceSampleSink.
Definition at line 144 of file localoutput.cpp.
References LocalOutput::MsgReportSampleRateAndFrequency::create(), DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceSampleSink::getMessageQueueToGUI(), m_centerFrequency, m_deviceAPI, m_sampleRate, and MessageQueue::push().
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     m_centerFrequency = centerFrequency;
     DSPSignalNotification *notif = new DSPSignalNotification(m_sampleRate, m_centerFrequency); // Frequency in Hz for the DSP engine
     m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     if (getMessageQueueToGUI())
     {
         MsgReportSampleRateAndFrequency *msg = MsgReportSampleRateAndFrequency::create(m_sampleRate, m_centerFrequency);
         getMessageQueueToGUI()->push(msg);
     }
 }
setMessageQueueToGUI()
void LocalOutput::setMessageQueueToGUI (MessageQueue * queue) virtual
Implements DeviceSampleSink.
Definition at line 110 of file localoutput.cpp.
References DeviceSampleSink::m_guiMessageQueue.
Referenced by LocalOutputGui::LocalOutputGui(), and LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     m_guiMessageQueue = queue;
 }
setSampleRate()
void LocalOutput::setSampleRate (int sampleRate) virtual
For when the sink sample rate is set externally.
Implements DeviceSampleSink.
Definition at line 125 of file localoutput.cpp.
References LocalOutput::MsgReportSampleRateAndFrequency::create(), DeviceAPI::getDeviceEngineInputMessageQueue(), DeviceSampleSink::getMessageQueueToGUI(), m_centerFrequency, m_deviceAPI, m_sampleRate, and MessageQueue::push().
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     m_sampleRate = sampleRate;
     DSPSignalNotification *notif = new DSPSignalNotification(m_sampleRate, m_centerFrequency); // Frequency in Hz for the DSP engine
     m_deviceAPI->getDeviceEngineInputMessageQueue()->push(notif);
     if (getMessageQueueToGUI())
     {
         MsgReportSampleRateAndFrequency *msg = MsgReportSampleRateAndFrequency::create(m_sampleRate, m_centerFrequency);
         getMessageQueueToGUI()->push(msg);
     }
 }
start()
bool LocalOutput::start () virtual
Implements DeviceSampleSink.
Definition at line 72 of file localoutput.cpp.
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     qDebug() << "LocalOutput::start";
     return true;
 }
stop()
void LocalOutput::stop () virtual
Implements DeviceSampleSink.
Definition at line 78 of file localoutput.cpp.
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency(), and ~LocalOutput().
 {
     qDebug() << "LocalOutput::stop";
 }
webapiFormatDeviceReport()
void LocalOutput::webapiFormatDeviceReport (SWGSDRangel::SWGDeviceReport & response) private
Definition at line 322 of file localoutput.cpp.
References SWGSDRangel::SWGDeviceReport::getLocalOutputReport(), m_centerFrequency, m_sampleRate, SWGSDRangel::SWGLocalOutputReport::setCenterFrequency(), and SWGSDRangel::SWGLocalOutputReport::setSampleRate().
Referenced by webapiReportGet().
 {
     response.getLocalOutputReport()->setCenterFrequency(m_centerFrequency);
     response.getLocalOutputReport()->setSampleRate(m_sampleRate);
 }
webapiFormatDeviceSettings()
void LocalOutput::webapiFormatDeviceSettings (SWGSDRangel::SWGDeviceSettings & response, const LocalOutputSettings & settings) private
Definition at line 297 of file localoutput.cpp.
References SWGSDRangel::SWGDeviceSettings::getLocalOutputSettings(), SWGSDRangel::SWGLocalOutputSettings::getReverseApiAddress(), LocalOutputSettings::m_reverseAPIAddress, LocalOutputSettings::m_reverseAPIDeviceIndex, LocalOutputSettings::m_reverseAPIPort, LocalOutputSettings::m_useReverseAPI, SWGSDRangel::SWGLocalOutputSettings::setReverseApiAddress(), SWGSDRangel::SWGLocalOutputSettings::setReverseApiDeviceIndex(), SWGSDRangel::SWGLocalOutputSettings::setReverseApiPort(), and SWGSDRangel::SWGLocalOutputSettings::setUseReverseApi().
Referenced by webapiSettingsGet(), and webapiSettingsPutPatch().
 {
     response.getLocalOutputSettings()->setUseReverseApi(settings.m_useReverseAPI ? 1 : 0);
     if (response.getLocalOutputSettings()->getReverseApiAddress()) {
         *response.getLocalOutputSettings()->getReverseApiAddress() = settings.m_reverseAPIAddress;
     } else {
         response.getLocalOutputSettings()->setReverseApiAddress(new QString(settings.m_reverseAPIAddress));
     }
     response.getLocalOutputSettings()->setReverseApiPort(settings.m_reverseAPIPort);
     response.getLocalOutputSettings()->setReverseApiDeviceIndex(settings.m_reverseAPIDeviceIndex);
 }
webapiReportGet()
int LocalOutput::webapiReportGet (SWGSDRangel::SWGDeviceReport & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 311 of file localoutput.cpp.
References SWGSDRangel::SWGDeviceReport::getLocalOutputReport(), SWGSDRangel::SWGLocalOutputReport::init(), SWGSDRangel::SWGDeviceReport::setLocalOutputReport(), and webapiFormatDeviceReport().
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     (void) errorMessage;
     response.setLocalOutputReport(new SWGSDRangel::SWGLocalOutputReport());
     response.getLocalOutputReport()->init();
     webapiFormatDeviceReport(response);
     return 200;
 }
webapiReverseSendSettings()
void LocalOutput::webapiReverseSendSettings (QList< QString > & deviceSettingsKeys, const LocalOutputSettings & settings, bool force) private
Definition at line 328 of file localoutput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, LocalOutputSettings::m_reverseAPIAddress, LocalOutputSettings::m_reverseAPIDeviceIndex, LocalOutputSettings::m_reverseAPIPort, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), SWGSDRangel::SWGDeviceSettings::setLocalOutputSettings(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by applySettings().
 {
     (void) deviceSettingsKeys;
     (void) force;
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(1); // single Tx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("LocalOutput"));
     swgDeviceSettings->setLocalOutputSettings(new SWGSDRangel::SWGLocalOutputSettings());
     // transfer data that has been modified. When force is on transfer all data except reverse API data
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/settings")
             .arg(settings.m_reverseAPIAddress)
             .arg(settings.m_reverseAPIPort)
             .arg(settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     // Always use PATCH to avoid passing reverse API settings
     m_networkManager->sendCustomRequest(m_networkRequest, "PATCH", buffer);
     delete swgDeviceSettings;
 }
webapiReverseSendStartStop()
void LocalOutput::webapiReverseSendStartStop (bool start) private
Definition at line 358 of file localoutput.cpp.
References SWGSDRangel::SWGDeviceSettings::asJson(), DeviceAPI::getDeviceSetIndex(), m_deviceAPI, m_networkManager, m_networkRequest, LocalOutputSettings::m_reverseAPIAddress, LocalOutputSettings::m_reverseAPIDeviceIndex, LocalOutputSettings::m_reverseAPIPort, m_settings, SWGSDRangel::SWGDeviceSettings::setDeviceHwType(), SWGSDRangel::SWGDeviceSettings::setDirection(), and SWGSDRangel::SWGDeviceSettings::setOriginatorIndex().
Referenced by handleMessage().
 {
     SWGSDRangel::SWGDeviceSettings *swgDeviceSettings = new SWGSDRangel::SWGDeviceSettings();
     swgDeviceSettings->setDirection(0); // single Rx
     swgDeviceSettings->setOriginatorIndex(m_deviceAPI->getDeviceSetIndex());
     swgDeviceSettings->setDeviceHwType(new QString("LocalInput"));
     QString deviceSettingsURL = QString("http://%1:%2/sdrangel/deviceset/%3/device/run")
             .arg(m_settings.m_reverseAPIAddress)
             .arg(m_settings.m_reverseAPIPort)
             .arg(m_settings.m_reverseAPIDeviceIndex);
     m_networkRequest.setUrl(QUrl(deviceSettingsURL));
     m_networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/json");
     QBuffer *buffer=new QBuffer();
     buffer->open((QBuffer::ReadWrite));
     buffer->write(swgDeviceSettings->asJson().toUtf8());
     buffer->seek(0);
     if (start) {
         m_networkManager->sendCustomRequest(m_networkRequest, "POST", buffer);
     } else {
         m_networkManager->sendCustomRequest(m_networkRequest, "DELETE", buffer);
     }
     delete swgDeviceSettings;
 }
webapiRun()
int LocalOutput::webapiRun (bool run, SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 232 of file localoutput.cpp.
References LocalOutput::MsgStartStop::create(), DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), m_deviceAPI, DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, and MessageQueue::push().
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     MsgStartStop *message = MsgStartStop::create(run);
     m_inputMessageQueue.push(message);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgStartStop *msgToGUI = MsgStartStop::create(run);
         m_guiMessageQueue->push(msgToGUI);
     }
     return 200;
 }
webapiRunGet()
int LocalOutput::webapiRunGet (SWGSDRangel::SWGDeviceState & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 223 of file localoutput.cpp.
References DeviceAPI::getDeviceEngineStateStr(), SWGSDRangel::SWGDeviceState::getState(), and m_deviceAPI.
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     (void) errorMessage;
     m_deviceAPI->getDeviceEngineStateStr(*response.getState());
     return 200;
 }
webapiSettingsGet()
int LocalOutput::webapiSettingsGet (SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 251 of file localoutput.cpp.
References SWGSDRangel::SWGDeviceSettings::getLocalOutputSettings(), SWGSDRangel::SWGLocalOutputSettings::init(), m_settings, SWGSDRangel::SWGDeviceSettings::setLocalOutputSettings(), and webapiFormatDeviceSettings().
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     (void) errorMessage;
     response.setLocalOutputSettings(new SWGSDRangel::SWGLocalOutputSettings());
     response.getLocalOutputSettings()->init();
     webapiFormatDeviceSettings(response, m_settings);
     return 200;
 }
webapiSettingsPutPatch()
int LocalOutput::webapiSettingsPutPatch (bool force, const QStringList & deviceSettingsKeys, SWGSDRangel::SWGDeviceSettings & response, QString & errorMessage) virtual
Reimplemented from DeviceSampleSink.
Definition at line 262 of file localoutput.cpp.
References LocalOutput::MsgConfigureLocalOutput::create(), SWGSDRangel::SWGDeviceSettings::getLocalOutputSettings(), SWGSDRangel::SWGLocalOutputSettings::getReverseApiAddress(), SWGSDRangel::SWGLocalOutputSettings::getReverseApiDeviceIndex(), SWGSDRangel::SWGLocalOutputSettings::getReverseApiPort(), SWGSDRangel::SWGLocalOutputSettings::getUseReverseApi(), DeviceSampleSink::m_guiMessageQueue, DeviceSampleSink::m_inputMessageQueue, LocalOutputSettings::m_reverseAPIAddress, LocalOutputSettings::m_reverseAPIDeviceIndex, LocalOutputSettings::m_reverseAPIPort, m_settings, LocalOutputSettings::m_useReverseAPI, MessageQueue::push(), and webapiFormatDeviceSettings().
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::MsgReportSampleRateAndFrequency().
 {
     (void) errorMessage;
     LocalOutputSettings settings = m_settings;
     if (deviceSettingsKeys.contains("useReverseAPI")) {
         settings.m_useReverseAPI = response.getLocalOutputSettings()->getUseReverseApi() != 0;
     }
     if (deviceSettingsKeys.contains("reverseAPIAddress")) {
         settings.m_reverseAPIAddress = *response.getLocalOutputSettings()->getReverseApiAddress();
     }
     if (deviceSettingsKeys.contains("reverseAPIPort")) {
         settings.m_reverseAPIPort = response.getLocalOutputSettings()->getReverseApiPort();
     }
     if (deviceSettingsKeys.contains("reverseAPIDeviceIndex")) {
         settings.m_reverseAPIDeviceIndex = response.getLocalOutputSettings()->getReverseApiDeviceIndex();
     }
     MsgConfigureLocalOutput *msg = MsgConfigureLocalOutput::create(settings, force);
     m_inputMessageQueue.push(msg);
     if (m_guiMessageQueue) // forward to GUI if any
     {
         MsgConfigureLocalOutput *msgToGUI = MsgConfigureLocalOutput::create(settings, force);
         m_guiMessageQueue->push(msgToGUI);
     }
     webapiFormatDeviceSettings(response, settings);
     return 200;
 }
Member Data Documentation
m_centerFrequency
qint64 LocalOutput::m_centerFrequency private
Definition at line 154 of file localoutput.h.
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::getCenterFrequency(), getCenterFrequency(), setCenterFrequency(), setSampleRate(), and webapiFormatDeviceReport().
m_deviceAPI
DeviceAPI* LocalOutput::m_deviceAPI private
Definition at line 151 of file localoutput.h.
Referenced by handleMessage(), setCenterFrequency(), setSampleRate(), webapiReverseSendSettings(), webapiReverseSendStartStop(), webapiRun(), and webapiRunGet().
m_deviceDescription
QString LocalOutput::m_deviceDescription private
Definition at line 157 of file localoutput.h.
Referenced by getDeviceDescription().
m_fileSink
FileRecord* LocalOutput::m_fileSink private
File sink to record device I/Q output.
Definition at line 158 of file localoutput.h.
m_mutex
QMutex LocalOutput::m_mutex private
Definition at line 152 of file localoutput.h.
Referenced by applySettings().
m_networkManager
QNetworkAccessManager* LocalOutput::m_networkManager private
Definition at line 159 of file localoutput.h.
Referenced by webapiReverseSendSettings(), webapiReverseSendStartStop(), and ~LocalOutput().
m_networkRequest
QNetworkRequest LocalOutput::m_networkRequest private
Definition at line 160 of file localoutput.h.
Referenced by webapiReverseSendSettings(), and webapiReverseSendStartStop().
m_remoteAddress
QString LocalOutput::m_remoteAddress private
Definition at line 156 of file localoutput.h.
Referenced by applySettings().
m_sampleRate
int LocalOutput::m_sampleRate private
Definition at line 155 of file localoutput.h.
Referenced by LocalOutput::MsgReportSampleRateAndFrequency::getSampleRate(), getSampleRate(), setCenterFrequency(), setSampleRate(), and webapiFormatDeviceReport().
m_settings
LocalOutputSettings LocalOutput::m_settings private
Definition at line 153 of file localoutput.h.
Referenced by applySettings(), deserialize(), handleMessage(), init(), serialize(), webapiReverseSendStartStop(), webapiSettingsGet(), and webapiSettingsPutPatch().
The documentation for this class was generated from the following files:
plugins/samplesink/localoutput/localoutput.h
plugins/samplesink/localoutput/localoutput.cpp