SDRAngel: WFMMod::MsgConfigureWFMMod Class Reference
WFMMod::MsgConfigureWFMMod Class Reference
#include <wfmmod.h>
Public Member Functions
const WFMModSettings & getSettings () const
bool getForce () const
Public Member Functions inherited from Message
Message ()
virtual ~Message ()
virtual const char * getIdentifier () const
virtual bool matchIdentifier (const char *identifier) const
void * getDestination () const
void setDestination (void *destination)
Static Public Member Functions
static MsgConfigureWFMMod * create (const WFMModSettings &settings, bool force)
Static Public Member Functions inherited from Message
static bool match (const Message *message)
Private Member Functions
MsgConfigureWFMMod (const WFMModSettings &settings, bool force)
Private Attributes
WFMModSettings m_settings
bool m_force
Additional Inherited Members
Protected Attributes inherited from Message
void * m_destination
Static Protected Attributes inherited from Message
static const char * m_identifier = 0
Detailed Description
Definition at line 52 of file wfmmod.h.
Constructor & Destructor Documentation
MsgConfigureWFMMod()
WFMMod::MsgConfigureWFMMod::MsgConfigureWFMMod (const WFMModSettings & settings, bool force) inline private
Definition at line 68 of file wfmmod.h.
Referenced by create().
                                                                        :
             Message(),
             m_settings(settings),
             m_force(force)
         { }
Member Function Documentation
create()
static MsgConfigureWFMMod* WFMMod::MsgConfigureWFMMod::create (const WFMModSettings & settings, bool force) inline static
Definition at line 59 of file wfmmod.h.
References MsgConfigureWFMMod().
Referenced by WFMModGUI::applySettings(), WFMMod::deserialize(), and WFMMod::webapiSettingsPutPatch().
         {
             return new MsgConfigureWFMMod(settings, force);
         }
getForce()
bool WFMMod::MsgConfigureWFMMod::getForce () const inline
Definition at line 57 of file wfmmod.h.
References m_force.
Referenced by WFMMod::handleMessage().
 { return m_force; }
getSettings()
const WFMModSettings& WFMMod::MsgConfigureWFMMod::getSettings () const inline
Definition at line 56 of file wfmmod.h.
References m_settings.
Referenced by WFMModGUI::handleMessage(), and WFMMod::handleMessage().
 { return m_settings; }
Member Data Documentation
m_force
bool WFMMod::MsgConfigureWFMMod::m_force private
Definition at line 66 of file wfmmod.h.
Referenced by getForce().
m_settings
WFMModSettings WFMMod::MsgConfigureWFMMod::m_settings private
Definition at line 65 of file wfmmod.h.
Referenced by WFMMod::getCenterFrequency(), getSettings(), WFMMod::getStreamCenterFrequency(), and WFMMod::getTitle().
The documentation for this class was generated from the following file:
plugins/channeltx/modwfm/wfmmod.h