SDRAngel: UDPSinkFECWorker Class Reference
UDPSinkFECWorker Class Reference
#include <udpsinkfecworker.h>
Inherits QThread.
Classes
class MsgConfigureRemoteAddress
class MsgStartStop
class MsgUDPFECEncodeAndSend
Public Member Functions
UDPSinkFECWorker ()
~UDPSinkFECWorker ()
void startStop (bool start)
void pushTxFrame (RemoteSuperBlock *txBlocks, uint32_t nbBlocksFEC, uint32_t txDelay, uint16_t frameIndex)
void setRemoteAddress (const QString &address, uint16_t port)
Public Attributes
MessageQueue m_inputMessageQueue
Queue for asynchronous inbound communication.
Private Slots
void handleInputMessages ()
Private Member Functions
void startWork ()
void stopWork ()
void run ()
void encodeAndTransmit (RemoteSuperBlock *txBlockx, uint16_t frameIndex, uint32_t nbBlocksFEC, uint32_t txDelay)
Private Attributes
QMutex m_startWaitMutex
QWaitCondition m_startWaiter
volatile bool m_running
CM256 m_cm256
CM256 library object.
bool m_cm256Valid
true if CM256 library is initialized correctly
QUdpSocket * m_udpSocket
QString m_remoteAddress
uint16_t m_remotePort
QHostAddress m_remoteHostAddress
Detailed Description
Definition at line 34 of file udpsinkfecworker.h.
Constructor & Destructor Documentation
UDPSinkFECWorker()
UDPSinkFECWorker::UDPSinkFECWorker ()
Definition at line 27 of file udpsinkfecworker.cpp.
Referenced by UDPSinkFECWorker::MsgStartStop::MsgStartStop().
                                    :
         m_running(false),
         m_udpSocket(0),
         m_remotePort(9090)
 {
     m_cm256Valid = m_cm256.isInitialized();
     connect(&m_inputMessageQueue, SIGNAL(messageEnqueued()), this, SLOT(handleInputMessages()), Qt::QueuedConnection);
 }
~UDPSinkFECWorker()
UDPSinkFECWorker::~UDPSinkFECWorker ()
Definition at line 36 of file udpsinkfecworker.cpp.
Referenced by UDPSinkFECWorker::MsgStartStop::MsgStartStop().
 {
 }
Member Function Documentation
encodeAndTransmit()
void UDPSinkFECWorker::encodeAndTransmit (RemoteSuperBlock * txBlockx, uint16_t frameIndex, uint32_t nbBlocksFEC, uint32_t txDelay) private
< Main interface with CM256 encoder
< Pointers to data for CM256 encoder
< FEC data
Definition at line 135 of file udpsinkfecworker.cpp.
References i, m_cm256Valid, and m_udpSocket.
Referenced by handleInputMessages().
 {
     CM256::cm256_encoder_params cm256Params;
     CM256::cm256_block descriptorBlocks[256];
     RemoteProtectedBlock fecBlocks[256];
     if ((nbBlocksFEC == 0) || !m_cm256Valid)
     {
         if (m_udpSocket)
         {
             for (unsigned int i = 0; i < RemoteNbOrginalBlocks; i++)
             {
                 m_udpSocket->writeDatagram((const char *) &txBlockx[i], RemoteUdpSize, m_remoteHostAddress, m_remotePort);
                 usleep(txDelay);
             }
         }
     }
     else
     {
         cm256Params.BlockBytes = sizeof(RemoteProtectedBlock);
         cm256Params.OriginalCount = RemoteNbOrginalBlocks;
         cm256Params.RecoveryCount = nbBlocksFEC;
         // Fill pointers to data
         for (int i = 0; i < cm256Params.OriginalCount + cm256Params.RecoveryCount; ++i)
         {
             if (i >= cm256Params.OriginalCount) {
                 memset((char *) &txBlockx[i].m_protectedBlock, 0, sizeof(RemoteProtectedBlock));
             }
             txBlockx[i].m_header.m_frameIndex = frameIndex;
             txBlockx[i].m_header.m_blockIndex = i;
             txBlockx[i].m_header.m_sampleBytes = (SDR_RX_SAMP_SZ <= 16 ? 2 : 4);
             txBlockx[i].m_header.m_sampleBits = SDR_RX_SAMP_SZ;
             descriptorBlocks[i].Block = (void *) &(txBlockx[i].m_protectedBlock);
             descriptorBlocks[i].Index = txBlockx[i].m_header.m_blockIndex;
         }
         // Encode FEC blocks
         if (m_cm256.cm256_encode(cm256Params, descriptorBlocks, fecBlocks))
         {
             qDebug("UDPSinkFECWorker::encodeAndTransmit: CM256 encode failed. No transmission.");
             return;
         }
         // Merge FEC with data to transmit
         for (int i = 0; i < cm256Params.RecoveryCount; i++)
         {
             txBlockx[i + cm256Params.OriginalCount].m_protectedBlock = fecBlocks[i];
         }
         // Transmit all blocks
         if (m_udpSocket)
         {
             for (int i = 0; i < cm256Params.OriginalCount + cm256Params.RecoveryCount; i++)
             {
     #ifdef REMOTE_PUNCTURE
                 if (i == REMOTE_PUNCTURE) {
                     continue;
                 }
     #endif
                 m_udpSocket->writeDatagram((const char *) &txBlockx[i], RemoteUdpSize, m_remoteHostAddress, m_remotePort);
                 usleep(txDelay);
             }
         }
     }
 }
handleInputMessages
void UDPSinkFECWorker::handleInputMessages () private slot
Definition at line 100 of file udpsinkfecworker.cpp.
References encodeAndTransmit(), UDPSinkFECWorker::MsgUDPFECEncodeAndSend::getFrameIndex(), Message::getIdentifier(), UDPSinkFECWorker::MsgUDPFECEncodeAndSend::getNbBlocsFEC(), UDPSinkFECWorker::MsgStartStop::getStartStop(), UDPSinkFECWorker::MsgUDPFECEncodeAndSend::getTxBlocks(), UDPSinkFECWorker::MsgUDPFECEncodeAndSend::getTxDelay(), m_inputMessageQueue, m_remoteAddress, m_remoteHostAddress, m_remotePort, Message::match(), MessageQueue::pop(), startWork(), and stopWork().
 {
     Message* message;
     while ((message = m_inputMessageQueue.pop()) != 0)
     {
         if (MsgUDPFECEncodeAndSend::match(*message))
         {
             MsgUDPFECEncodeAndSend *sendMsg = (MsgUDPFECEncodeAndSend *) message;
             encodeAndTransmit(sendMsg->getTxBlocks(), sendMsg->getFrameIndex(), sendMsg->getNbBlocsFEC(), sendMsg->getTxDelay());
         }
         else if (MsgConfigureRemoteAddress::match(*message))
         {
             qDebug("UDPSinkFECWorker::handleInputMessages: %s", message->getIdentifier());
             MsgConfigureRemoteAddress *addressMsg = (MsgConfigureRemoteAddress *) message;
             m_remoteAddress = addressMsg->getAddress();
             m_remotePort = addressMsg->getPort();
             m_remoteHostAddress.setAddress(addressMsg->getAddress());
         }
         else if (MsgStartStop::match(*message))
         {
             MsgStartStop* notif = (MsgStartStop*) message;
             qDebug("UDPSinkFECWorker::handleInputMessages: MsgStartStop: %s", notif->getStartStop() ? "start" : "stop");
             if (notif->getStartStop()) {
                 startWork();
             } else {
                 stopWork();
             }
         }
         delete message;
     }
 }
pushTxFrame()
void UDPSinkFECWorker::pushTxFrame (RemoteSuperBlock * txBlocks, uint32_t nbBlocksFEC, uint32_t txDelay, uint16_t frameIndex)
Definition at line 86 of file udpsinkfecworker.cpp.
References UDPSinkFECWorker::MsgUDPFECEncodeAndSend::create(), m_inputMessageQueue, and MessageQueue::push().
Referenced by UDPSinkFECWorker::MsgStartStop::MsgStartStop().
 {
     //qDebug("UDPSinkFECWorker::pushTxFrame. %d", m_inputMessageQueue.size());
     m_inputMessageQueue.push(MsgUDPFECEncodeAndSend::create(txBlocks, nbBlocksFEC, txDelay, frameIndex));
 }
run()
void UDPSinkFECWorker::run () private
Definition at line 70 of file udpsinkfecworker.cpp.
References m_running, and m_startWaiter.
 {
     m_running  = true;
     m_startWaiter.wakeAll();
     qDebug("UDPSinkFECWorker::process: started");
     while (m_running)
     {
         sleep(1);
     }
     m_running = false;
     qDebug("UDPSinkFECWorker::process: stopped");
 }
setRemoteAddress()
void UDPSinkFECWorker::setRemoteAddress (const QString & address, uint16_t port)
Definition at line 95 of file udpsinkfecworker.cpp.
References UDPSinkFECWorker::MsgConfigureRemoteAddress::create(), m_inputMessageQueue, and MessageQueue::push().
Referenced by UDPSinkFECWorker::MsgStartStop::MsgStartStop(), UDPSinkFEC::setRemoteAddress(), and UDPSinkFEC::start().
 {
     m_inputMessageQueue.push(MsgConfigureRemoteAddress::create(address, port));
 }
startStop()
void UDPSinkFECWorker::startStop (bool start)
Definition at line 40 of file udpsinkfecworker.cpp.
References UDPSinkFECWorker::MsgStartStop::create(), m_inputMessageQueue, and MessageQueue::push().
Referenced by UDPSinkFECWorker::MsgStartStop::MsgStartStop(), UDPSinkFEC::start(), and UDPSinkFEC::stop().
 {
     MsgStartStop *msg = MsgStartStop::create(start);
     m_inputMessageQueue.push(msg);
 }
startWork()
void UDPSinkFECWorker::startWork () private
Definition at line 46 of file udpsinkfecworker.cpp.
References m_running, m_startWaiter, m_startWaitMutex, and m_udpSocket.
Referenced by handleInputMessages().
 {
     qDebug("UDPSinkFECWorker::startWork");
     m_startWaitMutex.lock();
     m_udpSocket = new QUdpSocket(this);
     start();
     while(!m_running) {
         m_startWaiter.wait(&m_startWaitMutex, 100);
     }
     m_startWaitMutex.unlock();
 }
stopWork()
void UDPSinkFECWorker::stopWork () private
Definition at line 61 of file udpsinkfecworker.cpp.
References m_running, and m_udpSocket.
Referenced by handleInputMessages().
 {
     qDebug("UDPSinkFECWorker::stopWork");
     delete m_udpSocket;
     m_udpSocket = 0;
     m_running = false;
     wait();
 }
Member Data Documentation
m_cm256
CM256 UDPSinkFECWorker::m_cm256 private
CM256 library object.
Definition at line 140 of file udpsinkfecworker.h.
m_cm256Valid
bool UDPSinkFECWorker::m_cm256Valid private
true if CM256 library is initialized correctly
Definition at line 141 of file udpsinkfecworker.h.
Referenced by encodeAndTransmit().
m_inputMessageQueue
MessageQueue UDPSinkFECWorker::m_inputMessageQueue
Queue for asynchronous inbound communication.
Definition at line 126 of file udpsinkfecworker.h.
Referenced by handleInputMessages(), pushTxFrame(), setRemoteAddress(), and startStop().
m_remoteAddress
QString UDPSinkFECWorker::m_remoteAddress private
Definition at line 143 of file udpsinkfecworker.h.
Referenced by handleInputMessages().
m_remoteHostAddress
QHostAddress UDPSinkFECWorker::m_remoteHostAddress private
Definition at line 145 of file udpsinkfecworker.h.
Referenced by handleInputMessages().
m_remotePort
uint16_t UDPSinkFECWorker::m_remotePort private
Definition at line 144 of file udpsinkfecworker.h.
Referenced by handleInputMessages().
m_running
volatile bool UDPSinkFECWorker::m_running private
Definition at line 139 of file udpsinkfecworker.h.
Referenced by run(), startWork(), and stopWork().
m_startWaiter
QWaitCondition UDPSinkFECWorker::m_startWaiter private
Definition at line 138 of file udpsinkfecworker.h.
Referenced by run(), and startWork().
m_startWaitMutex
QMutex UDPSinkFECWorker::m_startWaitMutex private
Definition at line 137 of file udpsinkfecworker.h.
Referenced by startWork().
m_udpSocket
QUdpSocket* UDPSinkFECWorker::m_udpSocket private
Definition at line 142 of file udpsinkfecworker.h.
Referenced by encodeAndTransmit(), startWork(), and stopWork().
The documentation for this class was generated from the following files:
plugins/samplesink/remoteoutput/udpsinkfecworker.h
plugins/samplesink/remoteoutput/udpsinkfecworker.cpp